### ISSUE TITLE
Se buscan integrantes

### ISSUE THREAD

**Issue by emanuelcasco** [sisoputnfrba/foro#1001]
Buenas!! 👋 

¡Estamos buscando dos integrantes para completar el grupo! Si están interesados enviar un mail a: cascoemanuel@gmail.com

**Comment by tferraro** [comment]
Lo mismo que dijo Chris acá :slightly_smiling_face: :

https://github.com/sisoputnfrba/foro/issues/1002#issuecomment-380527264
