### ISSUE TITLE
Faltan 2 integrantes

### ISSUE THREAD

**Issue by ggabadian** [sisoputnfrba/foro#1002]
Hola.
Hasta ahora somos 3 en el grupo del TP y estamos buscando 2 integrantes más. Buscamos gente comprometida.
Los 3 somos del curso de los sábados por la mañana.

**Comment by varas-c** [comment]
Hola!

Si para el sábado no consiguen completar el grupo, el mismo sábado en las
charlas, seguramente se brinde un tiempo entre las mismas para que puedan
buscar integrantes ahí mismo.

Recuerden que el grupo tiene que ser de 5 integrantes +- 0.

Igualmente lo ideal es que traten de confirmar el grupo lo antes posible,
así que a no dormirse!

2018-04-11 14:04 GMT-03:00 ggabadian <notifications@github.com>:
