### ISSUE TITLE
Pantalla negra al iniciar Ubuntu

### ISSUE THREAD

**Issue by MBCaponelli** [sisoputnfrba/foro#1003]
Buenas! Desde ayer que cuando quiero usar ubuntu desde el usuario utnso me acepta la contraseña pero se me queda la pantalla en negro. Lo raro es que si entro desde el usuario de invitado no tengo ningun problema. Alguno sabe como arreglarlo? Gracias!

**Comment by varas-c** [comment]
Buenas!

Podrías adjuntar alguna captura de pantalla de "la pantalla en negro" ? (No
de la pantalla de Lubuntu en si misma, sacale una screenshot al escritorio
de tu maquina con el virtualbox en un tamaño "chico", asi se ve tu
escritorio, el virtualbox y la imagen de Lubuntu)

Por otra parte,te sale algún mensaje? Hiciste algun "cambio" que sospechas
que puede haberte producido el error?

Por ejemplo, instalaste X cosa y despues de instalarla, te empezó a salir
la pantalla en negro


2018-04-13 15:45 GMT-03:00 MBCaponelli <notifications@github.com>:

**Comment by MBCaponelli** [comment]
![so](https://user-images.githubusercontent.com/28991873/38755394-f14e8aee-3f3b-11e8-9603-7c68f634d5a5.png)

No muestra ningún mensaje ni tampoco hice ningún "cambio". La ultima vez lo único que hice fue usar eclipse

**Comment by iago64** [comment]
Buenas buenas? el problema lo tenes al ingresar con el usuario utnso solamente? si es así, lo que podrías hacer es ingresar como invitado y crear otro user con permisos de root, aunque es raro el problema.

Si podes mañana traete la PC a la charla y en un rato libre lo vemos.

**Comment by iago64** [comment]
@MBCaponelli pudiste resolver el inconveniente? seguís sin poder iniciar la vm con el usuario utnso?

**Comment by tferraro** [comment]
Por inactividad cierro este issue, pero @MBCaponelli no dudes en volverlo a abrir si la duda persiste,
