### ISSUE TITLE
Duda sobre el GET

### ISSUE THREAD

**Issue by FrancoVentrice** [sisoputnfrba/foro#1004]
Segun el anexo I, la operación GET sirve para obtener el valor de una clave (el cual se encuentra en una instancia). Según una aclaración en la página 9, la operación GET no requiere de acceso a instancias, y en la 10 dice que la operación sólo modifica el estado de bloqueos en el planificador.

Por lo que leo en el resto del TP, no habla de devolver valores tampoco, ¿Puedo asumir que se trata de una errata en el anexo?

Muchas gracias!

**Comment by afilgueira** [comment]
Hola, la palabra "obtener" se usa mucho para hablar de locks o semáforos. En ese contexto significa que ese proceso "bloquea" el recurso. De ahí un poco la confusión. Lo anoto para la errata, así lo aclaramos. Gracias!
