### ISSUE TITLE
Configuracion de eclipse para incluir archivos del directorio padre

### ISSUE THREAD

**Issue by rodroma** [sisoputnfrba/foro#1008]
Buenas! no encontre la respuesta a esto en el foro. Es probable que este buscando mal (y perdon por la falta de tildes, no puedo configurar bien el teclado en la VM :cry: )

Estaba tratando de configurar cspec en uno de los proyectos que tenemos en mi grupo, por lo que arme un proyecto tests dentro del proyecto padre, asi quedo la estructura de archivos:

![image](https://user-images.githubusercontent.com/18371776/38783257-2edf5596-40d6-11e8-8805-75fbae5cb87d.png)

Cuando trato de incluir el SUT en mi tests.c lo hago asi (tampoco estoy seguro si es la manera correcta de hacerlo):

`#include "../coordinador.h"`

Obviamente no funciona porque no estoy linkeando contra ese archivo compilado (creo), por lo que imagino que tendria que incluirlo en el makefile, pero no encuentro la opcion para hacerlo desde eclipse (Probe en varios de Properties -> Tool Settings).

Alguno sabe que es lo que estoy haciendo mal? o si lo que estoy intentando hacer es posible?

**Comment by iago64** [comment]
Buenas buenas!

El include en donde lo estas haciendo? porque si es por ejemplo en coordinador.c deberia ser simplemente:

`#include "coordinador.h"`

Ya que ambos estan en el mismo directorio.
Saludos.-

**Comment by rodroma** [comment]
Lo hago en tests.c, que esta dentro de la carpeta tests, en un directorio hijo de coordinador

**Comment by rodroma** [comment]
> El tema es que la única* forma de compartir tu código entre tu proyecto real, y el de tests, es que sea una biblioteca compartida; entonces te quedarían 3 proyectos "hermanos": uno de tests, uno que corra, y uno que sea la biblioteca compartida entre los dos.

Ahora trato de ver si puedo mover las funciones que queremos testear a una shared library. Cualquier cosa te arrobo en un issue de nuestro grupo joaco.
