### ISSUE TITLE
Consulta de enunciado, operación Status<CLAVE>.

### ISSUE THREAD

**Issue by mesaglio** [sisoputnfrba/foro#1011]
En el enunciado dice: "status <clave>: Debido a que para la correcta coordinación de las sentencias de
acuerdo a los algoritmos de distribución4 se requiere de cierta información sobre las instancias del sistema, el Coordinador proporcionará una consola que permita consultar esta información."

A que información hace referencia?

**Comment by afilgueira** [comment]
Hola, esto lo tenemos anotado para la errata. Se refiere a la consola del planificador.
