### ISSUE TITLE
Operación desbloquear del planificador no recibe ID

### ISSUE THREAD

**Issue by Mszlajen** [sisoputnfrba/foro#1013]
El TP dice que la consola del planificador tiene el comando desbloquear con el formato desbloquear
<clave>, se supone desbloquea un ESI previamente bloqueado desde la consola pero no tiene un parametro ID. ¿El parametro <clave> es un error y deberia ser <ID> o deberia recibir los dos parametros igual que bloquear (<clave> <ID>)?

**Comment by afilgueira** [comment]
Hola, esto lo comentamos en la charla. Vamos a pasarles solo el ID. En la errata lo van a ver claro. Saludos!

**Comment by LeaTex** [comment]
No se olviden porfa de hacer esta aclaración en la errata. En el GitBook sigue apareciendo como:

> bloquear clave ID: Se bloqueará el proceso ESI hasta ser desbloqueado (ver más adelante), especificado por dicho ID(^3) en la cola del recurso clave.
> 
> ^3: El Planificador empezará con una serie de claves bloqueadas de esta manera.

No termina de quedar claro si lo que se bloquea es un proceso (ESI) o un recurso (clave), o ambas cosas.

Perdón si ya está corregido en el proyecto del Git, no lo miré.

**Comment by afilgueira** [comment]
Se bloquea el ESI por una clave en particular. Es como si hicieras un `GET <clave>`. Fijate si en la última errata quedo claro, y si no aclaramos

**Comment by LeaTex** [comment]
Gracias!
