### ISSUE TITLE
Colaboración Planificador - Coordinador

### ISSUE THREAD

**Issue by AntonioDLC** [sisoputnfrba/foro#1014]
Hola,
El enunciado del TP empieza diciendo que el ESI (cuando el planificador se lo indica) ejecuta una sentencia.
El ESI la parsea y se la envía al Coordinador.
El Coordinador le retorna entonces un mensaje informando el resultado.
Finalmente el ESI le envía este resultado al Planificador.

Luego en la sección Planificador no se comenta nunca que este iniciará y se conectará al Coordinador pero en su configuración figuran IP y Puerto de Coordinador
Finalmente se explicita la existencia de esa conexión en la sección del Coordinador en la página 10 (arriba del todo) dice que cuando el recurso se encuentra tomado el Coordinador le informará directamente al Planificador.

Pero entonces, ¿el único resultado que se pasa del Coordinador al ESI y del ESI al Planificador es: "Ejecuté la sentencia"?
Si no ¿por qué debe el Planificador --informar resultado al--> Coordinador si el resultado del acceso al recurso (si estaba tomado, si fue accedido con éxito, o si no existía) de todos modos también se comunica de la forma Coord -> ESI -> Planificador?

**Comment by iago64** [comment]
Antonio, que tal?

En la sección del Planificador no se comenta que iniciara y se conectara al Coordinador, pero es algo que asumimos que se entendía por el diagrama de conexiones y por el archivo de config del Planificador y ademas porque la interacción viene del lado del Coordinador.

El objetivo de esta conexión es que el Coordinador le avise al Planificador que el ESI tiene que ser bloqueado y este lo bloquee, ya que el ESI no conoce ni tiene que conocer de estados.

Por ultimo, como bien decís, la comunicación Coordinador --> ESI --> Planificador se da en el caso de que el Coordinador pueda ejecutar correctamente la sentencia que le envío el ESI previamente.

Saludos.-

**Comment by AntonioDLC** [comment]
Muchísimas gracias, era lo que quería saber.
