### ISSUE TITLE
Duda sobre la consola del planificador,

### ISSUE THREAD

**Issue by nicokim** [sisoputnfrba/foro#1015]
Mi duda era que en algunas operaciones como:
continuar, bloquear <clave> <ID>, desbloquear <clave>, etc.
Se debería verificar que la cantidad de argumentos pasados sea valido? Por ejemplo:
>bloquear
>continuar 32
>kill 4 3 2

**Comment by CarolinaPonceRodriguez** [comment]
Buenas noches!
Antes que nada te comento que dudo que validar la cantidad de argumentos sea un punto excepcional a la hora de evaluarte el tp y todo depende de como vayas a implementarlo. Te suena a algo de lo que hayas visto para el tp0? (chan, tire una data).

Pensaste en tal caso que inconvenientes se te podrían generar el no hacerlo?
Supongamos que viene uno de tus compañeros y dice: "voy a probar la consola del planificador a ver que tal" y sin intención, comienza a tirar fruta, tu consola sera tolerante a fallos o estallara por los aires?

En mi caso, teniendo en cuenta que hay intervención humana de por medio, trataría de estar lo mas cubierto posible. Te pongo como ejemplo la terminal, prueba escribir algún comando mal y a ver que pasa!

Saludos
