### ISSUE TITLE
Instalación de Commons Library

### ISSUE THREAD

**Issue by GabrielRuderman** [sisoputnfrba/foro#1016]
Estimados,
paso a consultarles por un inconveniente en la instalación de la biblioteca commons:

estoy siguiendo los pasos de este link:
https://github.com/sisoputnfrba/so-commons-library

primero cloné el repo de commons en el workspace, luego dentro de la carpeta clonada, ejecute "make", y luego "sudo make install", todo igual al video. Posteriormente hice la misma verificación, todo concuerda.

Entonces abro Eclipse, importo el proyecto del TP, abro Properties > C/C++ Build > Settings, pero no encuentro la sección Tool Settings. Les dejo una foto de lo que me aparece.

Saludos
![virtualbox_lubuntu 5 0_16_04_2018_17_33_34](https://user-images.githubusercontent.com/26581497/38872756-676dd590-422a-11e8-8d7e-8274a6bab490.png)

**Comment by CarolinaPonceRodriguez** [comment]
Buenas, desconozco por que no te aparece la opcion, quiza alguien mas pueda ayudar pero a priori te comento esta otra manera de linkear las commons, comenta si te sirve:

Abris Properties ->C/C++General ->Path ans Symbols ->libraries -> add -> y agregas unicamente la palabra commons, aplicas y salvas

Saludos!

**Comment by jazcarate** [comment]
Como importaste el proyecto del TP?

o mejor pregunta: ¿Quien armó el `Makefile` del proyecto?

Si fué armado por UDs, entonces el Eclipse no sabe como "agregarle" la información de las bibliotecas a el Makefile; por eso no te da la opción.

**Comment by afilgueira** [comment]
@GabrielRuderman pudiste solucionarlo? Saludos!

**Comment by GabrielRuderman** [comment]
Si, muchas gracias! Estaba importando mal el proyecto. Gracias por las respuestas!

Saludos

**Comment by natoszme** [comment]
@GabrielRuderman cómo lo estás importando? A nosotros con la opción de Existing project no nos anda. 

Gracias!

**Comment by iago64** [comment]
@natoszme Fijate que en el [repo ](https://github.com/sisoputnfrba/so-commons-library) tenes explicado como instalar las commons y como linkearlas (muy similar a como se linkea pthread o readline)

**Comment by natoszme** [comment]
@iago64 la pregunta iba por [este ](https://github.com/sisoputnfrba/foro/issues/1028) lado, porque creemos que estamos importando las cosas bien. El tema es que al no aparecer los tool settings, no podemos importar nada (de hecho las commons está bien linkeadas porque cuando se creó el proyecto dicha opción si aparecía!)

**Comment by tferraro** [comment]
@natoszme fija que viene por ese lado. Como lo están importando? (Recuerden importarlo como proyecto existente, no como proyecto con makefile)

**Comment by iago64** [comment]
Se cierra el issue por encontrarse resuelto, el resto de las dudas se siguen en el issue creado para tal caso.
