### ISSUE TITLE
Configuración de directorios para compilar

### ISSUE THREAD

**Issue by soriac** [sisoputnfrba/foro#1017]
Buen día. Queremos configurar nuestro proyecto para tener una librería de commons propia, donde podamos compartir funciones nuestras entre los cuatro módulos. Armamos los directorios de la siguiente manera:

![screenshot from 2018-04-17 10-43-40](https://user-images.githubusercontent.com/12989318/38873493-406cba68-422c-11e8-8c1d-412c2bea1ddc.png)

Si entramos a `Coordinador` y ejecutamos `make all` compila perfectamente. Si abrimos Coordinador desde eclipse y hacemos un build también.

Lo que queremos lograr es importar un archivo desde `ours-commons`. No entendemos cómo configurar el makefile o eclipse para poder hacer eso. 

También nos gustaría poder abrir `tp-2018-1c-Las-Maquinas-de-Turing` en eclipse y poder compilar cualquiera de los 4 proyectos, pero intentamos y tampoco podemos lograr esto. Creamos una nueva configuración de build y pusimos solo a coordinador.c en esta configuración, que tiene una función main, pero al hacer un build nos devuelve esto:

![screenshot from 2018-04-17 10-47-21](https://user-images.githubusercontent.com/12989318/38873685-bda076b4-422c-11e8-955d-a0b1771fa8dc.png)

**Comment by jazcarate** [comment]
Buenas!

Una pregunta: ¿Ese proyecto lo creaste vos a mano? ¿O lo creaste con el wizard de Eclipse para crear proyectos?

Sobre la segunda:
Desde Eclipse si o si vas a tener que abrir cada proyectito por separado; no vas a poder abrir toda la carpeta. Tal vez puedas hacer alguna magia y compartír el workspace entre todos tus compañeros _(total las direcciones son todas iguales, por tener el mismo usuario de sistema operativo)_... pero la verdá que jamás lo probé.

**Comment by soriac** [comment]
En realidad copiamos el makefile del tp0, lo modificamos un poquito e hicimos el Coordinador a mano (que anda perfecto). El tema es que nos dimos cuenta que, por ejemplo, las funciones para abrir sockets, comunicarse, leer, etc. van a ser las mismas en los 4 modulos. Entonces se nos ocurrió hacer estas commons (que todavía no tienen código) para permanecer DRY.

No tenemos problema en abrir cada proyectito por separado, pero no entendemos cómo hacer que compartan esas commons, que estarían en una carpeta más en la raiz de la repo.

Gracias.

**Comment by jazcarate** [comment]
La forma para compartir el código sería crear un nuevo proyecto que sea del tipo "biblioteca compartida". Pueden intentar hacer un propio MakeFile (para esto hay un flag de `gcc -shared`); o desde el wizard de Eclipse les dá un par de facilidades (como crear el `Makefile`).

**Comment by tferraro** [comment]
https://www.youtube.com/watch?v=Aw9kXFqWu_I&feature=youtu.be

Video tutoriales al rescate!

**Comment by soriac** [comment]
@tferraro el video me sirvió y llegué a hacer que funcione, muchas gracias!

Me queda una duda mas, el makefile me lo crea solo en la carpeta debug, cuando entreguemos el tp al fin de cuatrimestre (si dios quiere) lo compilamos desde ahí? O debería estar junto al código fuente?

**Comment by tferraro** [comment]
Tengo la ligera sensación que esto es un problema de que no tienen la misma estructura de directorios. Prueben de chequear eso :)

**Comment by soriac** [comment]
Tenemos exactamente la misma estructura de directorios (~/tp-2018-1c-Las-Maquinas-De-Turing)

Decidimos usar includes relativos (#include "../../our-commons"), ya que estabamos perdiendo mucho tiempo en configurar esto.

Gracias.
