### ISSUE TITLE
Consulta de SCRIPT para ESI

### ISSUE THREAD

**Issue by ricardoAguirreSanchez** [sisoputnfrba/foro#1018]
Buenas,

Nos surgió una duda con el archivo que estaría recibiendo ESI como parámetro, puntualmente es un .txt?, en el enunciado dice "Script", debemos entender entonces que es un .sh?
Si fuera un .txt entendemos que ESI leerá del archivo línea por línea (si es que fue el elegido por el ola claro está) y se lo enviará luego de aplicar el parser al coordinador, en el caso de que sea una operación GET sobre una clave tomada, el coordinador se lo envía al planificador y espera la respectiva notificación, luego el coordinador le enviará otra notificación a ESI, ESI recibe el mensaje de que está "bloqueadada" (por ejemplo) y se queda esperando que el planificador le indique que puede continuar? Osea si estoy usando un .txt, me quedaría con el archivo abierto y esperando leer la siguiente línea? Qué pasa si son muchos los ESIs bloqueados? Todos se quedarían con sus respectivos archivos abiertos? 

Si fuera un .sh no tendríamos este problema? o es un .sh y tenemos que usar mmap para llevar a memoria todo el archivo o solo línea por línea? 

Saludos.

**Comment by iago64** [comment]
Buenas buenas!

Vamos por partes porque se te cruzaron un par de cosas:

1.- Un script no necesariamente termina en .sh (eso es una extension de bash), pero en una consola de linux bien podrias tener un script de bash terminado en .txt y podrias ejecutarlo igual, simplemente necesitas que tenga permisos de ejecución.

2.- Respecto a los archivos, acordate que los scripts los abren para lectura, con lo cual, podrian tener muuuuchos ESI abriendo el mismo archivo y no pasaría nada en absoluto, todos pueden leer incluso al mismo tiempo :)

Saludos.-

**Comment by ricardoAguirreSanchez** [comment]
Muchas gracias por la respuesta!

**Comment by afilgueira** [comment]
@ricardoAguirreSanchez podemos cerrar el issue?

**Comment by ricardoAguirreSanchez** [comment]
Si,gracias!
