### ISSUE TITLE
Ejecución de procesos

### ISSUE THREAD

**Issue by Mszlajen** [sisoputnfrba/foro#1019]
En mi grupo no estamos seguros de entender como va se supone que es la funcionalidad del TP.
Por el momento entendemos que vamos a tener un ejecutable (el proceso padre) que va a crear los procesos hijos para el coordinador, el planificador y, a medida que se requiera, las ESI e instancias.
Eso está bien? y en ese caso, cuando sabe que tiene que crear el proceso de una ESI o de una instancia?

**Comment by LeaTex** [comment]
Matías, los 4 componentes principales son 4 procesos (programas) aislados, cada uno con su ejecutable, que se pueden correr en cualquier máquina.
Esos 4 procesos se ejecutan de manera independiente y se van conectando entre sí.

Primero ejecutás el Coordinador, porque así lo indica el enunciado, y es el que más conexiones recibe. No se conecta con nadie, solo espera conexiones, y puede estar corriendo (haciendo nada) sin problema.

Luego ejecutás el Planificador, que se conecta con el coordinador, y ahí queda, a la espera. En este punto ambos procesos están conectados, haciendo nada.

Luego podrías ejecutar 1 o más Instancias, que se conectan al Coordinador, y de nuevo quedan haciendo nada (salvo la compactación, que no tendría sentido si no hay entradas).

Y por último ejecutás 1 o más ESIs, que se van conectando con el Planificador y el Coordinador, y son los procesos que le dan "vida" a todo el conjunto porque son los que requieren acciones.

No sé si te aclaré un poco. Pero básicamente programás 4 cosas por separado.
(Así se lo pueden dividir entre los miembros del equipo, y queda uno libre para los mates. o_O

**Comment by Mszlajen** [comment]
Sí, perfecto eso era justamente lo que necesitabamos aclaración
