### ISSUE TITLE
Consola del planificador

### ISSUE THREAD

**Issue by JulianColaiacovo** [sisoputnfrba/foro#1020]
Hola

En el enunciado se nombra la consola del planificador, y nos surgieron dudas de como implementarla

- ¿Al iniciar el planificador tiene que ejecutar las tareas en background mientras se queda a la espera de comandos en la consola?
- ¿O debería ser un proceso ajeno al planificador? En este caso: ¿podrían haber muchas consolas?

Saludos!

**Comment by iago64** [comment]
Julian, que tal?
Si me lo permitis te contesto con una pregunta y la misma es:

Que formas tenes de hacer que un proceso haga varias cosas en simultaneo? 

Si te contestas esa duda posiblemente tengas la respuesta a como implementar la consola del planificador.
Por otra parte, solo vas a tener 1 consola del planificador.
Saludos.-

**Comment by JulianColaiacovo** [comment]
Gracias

**Comment by tferraro** [comment]
![image](https://user-images.githubusercontent.com/7110539/39023942-03e55b9c-4414-11e8-8f89-0e738ef8cfd8.png)
