### ISSUE TITLE
Uso de bibliotecas compartidas: duda con export de LD_LIBRARY_PATH al buildear

### ISSUE THREAD

**Issue by lnapolillo** [sisoputnfrba/foro#1021]
Hola!
Para el TP creamos una biblioteca compartida siguiendo las instrucciones en este video en el canal de YouTube de la cátedra: https://www.youtube.com/watch?v=Aw9kXFqWu_I&feature=youtu.be.
Según el video, cada vez que tengamos que hacer un make (al menos si cambiamos de terminal) de cada módulo, para que linkee correctamente la biblioteca, hay que setear la variable de entorno LD_LIBRARY_PATH, con el path a la biblioteca. La duda es, ya que siempre va a haber que hacer un export, ¿podemos crear un script bash que se encargue de hacer el make de todos los módulos y además haga el export?, ¿se va a poder utilizar al momento de la entrega?
Gracias!

**Comment by iago64** [comment]
Buenas buenas!!
Pueden crear un script de bash? **SIII** totalmente, es mas, si hacen que el scirpt les clone el repo, les haga el export del LD_LIBRARY_PATH y de regalo les compile el tp, esta super perfecto :)

Saludos.-

**Comment by CarolinaPonceRodriguez** [comment]
Buenas!
Agregando a lo que dijo Dami, llegando a la instancia final de entrega del tp van a necesitar un script para poder hacer el deploy en el tiempo que se estime(un par de minutos), por lo cual terminaría resultando como un "mal necesario".
Saludos!

**Comment by fighthawkarg** [comment]
BASHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH <3
![win](https://user-images.githubusercontent.com/32005251/39013171-f715d60c-43ec-11e8-8fab-982618619c94.jpg)

**Comment by afilgueira** [comment]
Asunto solucionado? Cerramos el issue? :)

**Comment by lnapolillo** [comment]
Hola! Sí! Perdón, se me re pasó. Muchas gracias :)
