### ISSUE TITLE
Consola para el Planificador

### ISSUE THREAD

**Issue by sebastianciancio** [sisoputnfrba/foro#1022]
Según indica el enunciado, el proceso Planificador va a necesitar un consola interactiva. Es válido utilizar ReadLine? De usarlo, deberiamos atender las peticiones de la consola a través de un Hilo?

**Comment by tferraro** [comment]
Buenas!

Aprovecho esto para aclarar otras preguntas similares. Las NTP dicen:
> A excepción de la Commons Library[2] y otras bibliotecas o herramientas desarrolladas por la cátedra, no está permitido que el código que compone el trabajo práctico utilice bibliotecas de terceros que no hayan sido instaladas previamente por la cátedra en las máquinas virtuales provistas para el desarrollo y pruebas del mismo.

Y las VMs vienen con Readline instalado! Esto significa que si :) (justamente por eso está en el TP0).

A esa afirmación, agrego otro Si! Pueden crear la consola como un hilo independiente.

Saludos!
Tom

**Comment by sebastianciancio** [comment]
Muchas gracias @tferraro!!
