### ISSUE TITLE
Consulta Algoritmo Equitative Load

### ISSUE THREAD

**Issue by ricardoAguirreSanchez** [sisoputnfrba/foro#1023]
Buenas,

Analizando el algoritmo nos surgió la siguiente duda:
Este algoritmo tenemos que distribuir la cargar EQUITATIVAMENTE entre todas las instancias que tengan? es decir, si tengo 
INSTANCIA 1 -> HIZO 2 <-PUNTERO
INSTANCIA 2 -> HIZO 3
INSTANCIA 3 -> HIZO 0

Si tengo mi puntero que me indica que ahora toca la instancia 1, pero se conecto la instancia 3 que por ende no hizo nada, tengo q primero enviar a ejecutar a la instancia 3 buscando **balancear** ? o puedo ejecutar todo desde arriba a bajo independientemente de la cantidad de tareas que vayan ejecutando cada una?

*Balancear = q todas las instancias se hayan ejecutado la misma cantidad de veces.

Saludos.

**Comment by jazcarate** [comment]
>  Consiste en despachar una solicitud a una Instancia distinta cada vez.

**Comment by jazcarate** [comment]
> Consiste en despachar una solicitud a una Instancia distinta cada vez.

Osea, no pretende que se "balancee" si entra uno nuevo. Así que sería correcto agregarlo en la "cola" de instancias, y que _"le toque cuando le toque"_.

La "carga" equitativa que se refiere el algoritmo; es más pensado del lado de la "red", donde vas usando un poquito cada uno. Si quiciesemos balancear el *contenido*, tenemos el otro algoritmo: `Least Space Used`.

**Comment by afilgueira** [comment]
Cerramos este también? ;)

**Comment by ricardoAguirreSanchez** [comment]
Si, gracias!
