### ISSUE TITLE
Undefined reference to main

### ISSUE THREAD

**Issue by natoszme** [sisoputnfrba/foro#1024]
Buenas! Escribimos porque nos salta el siguiente error, y nos dijo Nahuel que levantemos este issue:

13:42:03 **** Incremental Build of configuration Default for project planificador ****
make all 
Building target: planificador
Invoking: GCC C Linker
gcc -L"/home/utnso/workspace/tp-2018-1c-youKnowNothing/our-commons/Debug" -o "planificador"   -lour-commons -lreadline
/usr/lib/gcc/i686-linux-gnu/5/../../../i386-linux-gnu/crt1.o: In function `_start':
(.text+0x18): undefined reference to `main'
makefile:34: recipe for target 'planificador' failed
collect2: error: ld returned 1 exit status
make: *** [planificador] Error 1

13:42:03 Build Finished (took 412ms)

Estamos usando el makefile generado por Eclipse. Alguna idea? Gracias!

**Comment by jazcarate** [comment]
Nos podrías pasar el `Makefile`? porque en esa linea de `gcc` que nos estás mostrando; no tiene ningún archivo qué compilar _(por lo tanto no tiene una función de `mail`)_.

**Comment by natoszme** [comment]
Si! Va:

[makefile](https://gist.github.com/natoszme/f80bcc4dc8db40eb3dc8540787b3654a)

**Comment by jazcarate** [comment]
Je. Perdón, debería haber sido más especifico.
El Eclipse cuando genera el `Makefile`, hace un par más de archivos que los vá incluyendo

> ```
> -include sources.mk
> -include src/subdir.mk
> -include subdir.mk
> -include objects.mk
> ...
> ```

Esos me interesan un poco más. Miré en su repo a ver si los tenían subidos, y no los veo. Es una buena idea subir todos los archivos necesarios para compilar; para que todos los del equipo puedan compilar 😃

**Comment by natoszme** [comment]
No debería poder compilarse sólo con el Makefile? De todas formas estoy mirando [acá](https://github.com/sisoputnfrba/tp-2018-1c-youKnowNothing/tree/master/planificador/Debug) si los veo. Todos salvo src/subdir.mk. Alguna idea? En mi local tengo esos mismos archivos,y .makefile.swp (además de socket.o y socket.d)

**Comment by natoszme** [comment]
Así es

**Comment by iago64** [comment]
Listo, concentremos todo en el otro issue, este lo cierro asi no queda dando vueltas in eternum ya que todo tiene la misma base :)
