### ISSUE TITLE
Problema para utilizar una shared library

### ISSUE THREAD

**Issue by aleperaltabazas** [sisoputnfrba/foro#1026]
Hola! Estuvimos tratando de armar una shared library, pero no funciona, no importa que intentemos. Ya [vimos este video](https://www.youtube.com/watch?v=Aw9kXFqWu_I), pero no logramos hallarle la vuelta para que funcione. Probamos agregando la dependencia, el LD_LIBRARY_PATH y sigue sin reconocerlo. Si de algo sirve, el error que me tira cuando compilo, por ejemplo, el módulo para el ESI es:

```
make all
Building file: ../esi.c
Invoking: GCC C Compiler
gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"esi.d" -MT"esi.o" -o "esi.o" "../esi.c"
In file included from ../esi.c:8:0:
../esi.h:13:43: fatal error: shared-library/shared-library.h: No such file or directory
compilation terminated.
subdir.mk:18: recipe for target 'esi.o' failed
make: *** [esi.o] Error 1
```

Si hace falta algo más, haré lo posible de decirles lo que necesiten.
Saludos!

**Comment by jazcarate** [comment]
Buenas!
`LD_LIBRARY_PATH` es a momento de ejecución. Vos estas teniendo problemas de compilación; un chiquito antes.

En el output ese; en `gcc` no está linkeando tu biblioteca. Debería haber un parámetro más onda: `-lfoo` para incluir la biblioteca `foo`.

Mirando su repo, tampoco veo que tengan un `#include <foo/bar.h>`.


En el video, a minuto [5:12](https://youtu.be/Aw9kXFqWu_I?t=312) está como agregar una bilioteca desde Eclipse. ¿Hicieron eso? porque en el archivo `Debug/objects.mk` tienen una linea:
> ```
> LIBS :=
> ```

acá deberían tener su biblioteca.

**Comment by aleperaltabazas** [comment]
Hola, gracias por contestar.

Entre otras cosas no figura ningún include porque no logramos entender por qué no estaba funcionando entonces sacamos todo tipo de includes relacionados con la shared library (por eso tampoco figuran las dependenencias ni nada, aunque lo intentamos).

Sin embargo, parece que está funcionando ahora. Hicimos un rollback a una versión vieja antes de intentar implementarla y volvimos a copiar lo que dice el video y anda perfecto. Pero ahora me surge otra cuestión, es necesario usar el LD_LIBRARY_PATH? Porque ahora mismo está funcionando sin tener eso agregado en la sección de enviroment. Además, si sí es necesario agregar LD_LIBRARY_PATH, es necesario para cada módulo que tengamos que tenga su propia extensión?

**Comment by aleperaltabazas** [comment]
Perfecto, todo aclarado.

Gracias!
