### ISSUE TITLE
Problema con el makefile

### ISSUE THREAD

**Issue by agnmeinardo** [sisoputnfrba/foro#1027]
Buenas!
Estamos teniendo problemas para compilar el proyecto. Nuestro directorio, por ahora, está de la siguiente manera:
![ejemplo](https://user-images.githubusercontent.com/11727327/39100240-5cddc860-465d-11e8-8109-0d6045e34198.png)
Al compilar el proyecto desde eclipse, nos tira lo siguiente:
![ejemplo2](https://user-images.githubusercontent.com/11727327/39100252-7faaa188-465d-11e8-89a0-4c117b39097f.png)
El makefile, sin toqueteo alguno, está así:
![ejemplo3](https://user-images.githubusercontent.com/11727327/39100262-a4aa690a-465d-11e8-9dca-6ad7c6b166ea.png)
¿Qué puede ser?

**Comment by fighthawkarg** [comment]
Deduzco que tenes un solo proyecto, y que en el hay dos archivos que tiene una función main.

Por lo que eclipse, no te deja tener dos o más archivos con main en un mismo "proyecto" ....

**Comment by agnmeinardo** [comment]
Gracias por la respuesta, @iago64  . En conclusión: abrimos la carpeta tp-2018... como workspace; dentro creamos los cuatros proyectos (procesos); por último, el código que ya tenemos, moverlo a cada proyecto unitario. Correcto?

**Comment by iago64** [comment]
Si señor! se mueven los archivos de código a cada proyecto nuevo y listo, ya lo único que les queda es configurar las commons, readline (si lo usan) y sus propias shared (si las tienen).

Saludos.-

**Comment by agnmeinardo** [comment]
Gracias!

Saludos.-
