### ISSUE TITLE
No aparecen las tool settings en un proyecto importado como Existing project into Workspace

### ISSUE THREAD

**Issue by natoszme** [sisoputnfrba/foro#1028]
Buenas!
Ayer en el soporte nos dijeron que no teníamos que usar la opción de import -> Existing code as Makefile Project, ya que eso se reserva a los casos en que uno creo su propio Makefile. Por lo tanto creamos los proyectos de vuelta y los importamos con Existing projects into Workspace. Compila lo más bien pero el problema es que no salen las tool settings dentro de Project -> Properties C/C++ Build -> Settings. Algo similar pasa [acá,](https://github.com/sisoputnfrba/foro/issues/12) pero la diferencia es que nosotros importamos el projecto (aparentemente) bien.

La necesidad surgió de agregar la biblioteca pthread. El tema es que ya hay otras agregadas como las commons lo mas bien, pero se ve que las agregó quien creo el proyecto y yo ahora no las puedo editar o agregar nuevas. La forma que encontré de que aparezcan las tool settings fue la de tildar la opción Generate Makefiles automatically en C/C++ Build. El tema es que eso usa una carpeta llamada Default para poner los ejecutables y etcétera, La cuestión es que ya tenemos todo en la carpeta Debug (que si bien es una también generada por Eclipse, le está poniendo un nombre distinto a la de Default). Deberíamos usar Default?

Por otro lado tenemos entendido que la única forma de evitar subir los archivos de settings de Eclipse al repo es creando nuestro propio Makefile, cosa que venimos evitando porque no creemos tener el conocimiento suficiente para hacer. Hay alguna alternativa? Eclipse nos está trayendo muchos dramas y ya perdimos mucho tiempo con eso.

Gracias!

**Comment by tferraro** [comment]
Buenas!

Prueben regenerando el proyecto, no usando la opción de `Existing projects into Workspace`. Eso termina haciendo que use los mismos metadatos que tenían en la carpeta (la carpeta `.settings` y los archivos `.project`y `.cproject`)...lo que implica que están dando vueltas en redondo.

Hagan lo siguiente;
- Borren esos 2 archivos y la carpeta que mencioné. En el gestor de archivos, no los van a poder ver de una, porque todo lo comenzado con . es tomado como un archivo oculto. Tendrán que habilitarlo con Ver>Mostrar archivos ocultos (o algo parecido) o borrandolos por consola.
- Cambien el nombre de la carpeta por alguna otra cosa para que no genere conflicto con lo que va a crear eclipse.
- Creen el proyecto de eclipse nuevamente, como un proyecto nuevo de C.
- Copien los archivos de la carpeta vieja a la nueva y denle un refresh al Eclipse (ya pueden borrar la carpeta vieja).

Ahí debería funcionarles bien.

Saludos!
Tom

**Comment by natoszme** [comment]
Gracias por responder al toque!
El tema es que eso es lo ya hicimos y creíamos que había resulto el problema, pero no.
Además, suponiendo que yo cree los proyectos y todo el resto se los va a tener que bajar del repo y agregar a su workspace, cómo van a hacer ellos para importarlo? Gracias!

**Comment by natoszme** [comment]
A alguien se le ocurre algo más?

**Comment by tferraro** [comment]
Colgué un poco con esto, perdón!

Para importarlo una vez creados los archivos nuevos, tenes que importar el proyecto como existing project (Import>General>Existing Project), nada de proyecto con makefile ni esas cosas.

**Comment by tferraro** [comment]
Eso si, recuerden subir al repo los `.settings` `.cproject`u `.project` sino no va a andar la cosa :/

**Comment by natoszme** [comment]
Es que ahí está la cuestión! Estamos haciendo exactamente eso. Todo está en el repo y lo importamos tal cual decís vos

**Comment by tferraro** [comment]
En las propiedades del proyecto, en C/C++ Build, les aparece habilitado el `Generate Makefiles automatically`?

**Comment by natoszme** [comment]
Al importar como te comentaba, no. Aparece destildada. Si la tildamos, se cambia la carpeta de Debug a Default (y no nos deja modificar ese textbox) aunque si nos deja tocar las tool settings

**Comment by natoszme** [comment]
Buenas! Primero que nada mil gracias por tomarte el tiempo. Es muy raro porque hasta ahora las tool settings aparecían en planificador y our-commons pero no en todo el resto. Por ejemplo yo hoy tenía que tocar el coordinador para agregarle pthread y no me quedó otra que crear el proyecto de nuevo. Supongo que si por ejemplo probás todo el procedimiento con los esi, vas a ver el problema. Te pido perdón por no haber mencionado justo esos dos casos en los que si se veían las settings y una vez más, gracias!

**Comment by natoszme** [comment]
Si aplico las casillas la opción aparece pero me cambia la ruta de Debug a Default. Se entiende? Gracias!

**Comment by iago64** [comment]
Y que problema te genera eso? Probaste que pasa si te lo cambia a Default?

**Comment by natoszme** [comment]
Sisi me tiraba varios errores de compilación. Si ayuda ahora los paso por acá

**Comment by iago64** [comment]
Seria bueno tenerlos para ir delimitando el problema

**Comment by natoszme** [comment]
Al cambiar la carpeta y que se use Default, no linkeaba con las commons de la cátedra y hubo que volver a linkearlas, pero como ahora si aparece la opción tool settings, se pudo hacer. Nos quedamos con las dos carpetas, Debug y Default?

**Comment by natoszme** [comment]
Mil gracias por todo!

**Comment by DSW-MarthaDiaz** [comment]
No aparece el setting en GitHub, que debo hacer¡
