### ISSUE TITLE
Claves bloqueadas por configuracion del planificador

### ISSUE THREAD

**Issue by NicoFeld** [sisoputnfrba/foro#1030]
En el enunciado del tp el planificador recibe por configuracion un listado de claves bloqueadas.
Segun tengo entendido todas las claves son bloqueadas por un ESI, a traves de la operacion GET, o por el usuario a traves de la consola, utilizando el comando bloquear. 
Las que son levantadas por configuracion, ¿se consideran bloqueadas por el usuario?

**Comment by LeaTex** [comment]
Nico, me parece que no importa cómo se bloquearon, el comportamiento va a ser el mismo.
Así que daría lo mismo si fueron bloqueadas por usuario, por configuración, o por GET. Están bloqueadas, y listo.
Si lo quieren guardar como dato informativo para mostrar en el status, no veo problema en que las pongan como "bloqueadas por configuración" o algo así.

**Comment by NicoFeld** [comment]
Lo entiendo, pero como dice que se desbloquea cuando se hace un STORE, por parte de la ESI bloqueadora, se supone que no va a venir un STORE si no la bloquean, por otro lado cuando habla de la consola del planificador dice que solo se pueden desbloquear las que son bloqueadas por el usuario.

Para que funcione como vos decis deberia poder venir un STORE de un ESI que no hizo GET de esa clave necesariamente

**Comment by varas-c** [comment]
Hola!

Tal cual, no importa "quién las bloqueó". Si está bloqueado, está bloqueado
independientemente de que lo haya hecho un esi o el usuario.

Sí podrías hacer una diferenciación de ésto en el log, por ejemplo "clave
tanta bloqueada por el usuario" o "clave tanta bloqueada por el esi 6".

No es necesario que lo hagas (es decir, no vamos a ponerte menos nota y/o
desaprobar porque no logueaste ésto) pero si lo haces, suma y más que nada
para ustedes mismos cuando intenten debuguear su código ante algún problema.


2018-04-23 17:31 GMT-03:00 Lea MM <notifications@github.com>:

**Comment by NicoFeld** [comment]
Se entendio, gracias

**Comment by LeaTex** [comment]
Nico, otra cosa, revisen este issue: https://github.com/sisoputnfrba/foro/issues/1013

Puede resultar confuso el enunciado porque se habla en algunos lados de "bloquear ESI" y en otros de "bloquear claves".

Bloquear un ESI entiendo que sería, en términos de SO, bloquear un proceso (mandarlo a la cola de bloqueados).
Bloquear una clave sería, considerando una clave como un recurso, que ese recurso está "tomado" por un proceso.

La consola del planificador permite bloquear y desbloquear ESIs (no claves).

Las claves que nacen bloqueadas por archivo de configuración serían recursos que están tomados por el mismo planificador, por decirlo de alguna forma.
Lo que yo me preguntaría es: ¿esas claves que vienen por configuración, están en alguna instancia, hay que validar que existan?

Otra cosa que se me ocurre, es que tiene lógica que una clave (recurso) bloqueada (tomado) por un ESI (proceso) sólo pueda ser desbloqueada por él mismo, sino pasaría que cualquiera podría "robarle" (expropiarle) el recurso. Pero el planificador es, en cierto modo, expropiativo, porque puede liberar una clave matando al ESI.

Mi conclusión con todo esto es que las claves que nacen bloqueadas por configuración nunca pueden ser desbloqueada, y si un ESI hace un GET de una de esas claves, no puede tomarla (porque ya está tomada), entonces el ESI pasa a bloqueado.

De nuevo, todo esto según mi interpretación del enunciado, puedo estar pifiándole a algo.

**Comment by NicoFeld** [comment]
Segun tu razonamiento que entiendo como correcto, las claves que vienen por configuracion no deberian estar en ninguna instancia, ya que al nunca poder ser desbloqueadas no van a tener valores.

Entiendo que nunca seran desbloqueadas porque en la charla se dijo que un ESI solo hace STORE si hizo un GET antes, por ende nunca llegaria un STORE pelado que libere el recurso tomado por el planificador.

**Comment by ricardoAguirreSanchez** [comment]
Buenas, 
Entonces si un ESI hace un GET de una clave que esta bloqueada por configuración se bloqueo eternamente dado que no puede darse el caso de que un ESI lo desbloquee con un STORE porque solo pueden liberar recursos que previamente pidieron??
