### ISSUE TITLE
Problema con la inclusión del parser

### ISSUE THREAD

**Issue by ltrinidad** [sisoputnfrba/foro#1031]
Buenas !! 
Vimos que estaba el parser así que lo quisimos integrar, pero tuvimos problemas con esto. 
Eclipse muestra la linea de error ```parsi/parser.h: No such file or directory``` sobre el include de <parsi/parser.h>. Ademas, en el resultado de la compilacion en Eclipse nos aparece: 

```
make all 
Building file: ../src/esi.c
Invoking: GCC C Compiler
gcc -I"/home/utnso/workspace/tp-2018-1c-A-la-grande-le-puse-Jacketing/sisopLib" -Icommons -Iparsi -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/esi.d" -MT"src/esi.o" -o "src/esi.o" "../src/esi.c"
In file included from ../src/esi.c:12:0:
../src/funciones_esi.h:18:26: fatal error: parsi/parser.h: No such file or directory
compilation terminated.
src/subdir.mk:21: recipe for target 'src/esi.o' failed
make: *** [src/esi.o] Error 1 
```
Para instalarlo clonamos el repo y despues hicimos make. **Creemos** que ya hicimos las configuraciones necesarias en eclipse para incluir la dependencia, pero capaz esta faltando algo: 

![sin titulo](https://user-images.githubusercontent.com/21223603/39154112-8d2ee492-4723-11e8-81b5-a23b5f0e4d2a.jpg)

![2](https://user-images.githubusercontent.com/21223603/39154137-a0c1c772-4723-11e8-92e4-c9d27fd62a2d.jpg)

Por otro lado, sabemos que la commons y readline aparecen en /usr/*algo* (lib o include), pero no vimos en ningun lado algo como *libparsi.so*, eso esta bien? 
(Lo de Settings/Include no sabíamos si hacia falta llenarlo, lo llenamos porque.... no hay por que)

**Comment by jazcarate** [comment]
Buenas!

En efecto; no hay un `install` en la carpeta "padre" de *ParSI*.

¿Te animas a pedir un [Pull Request](http://aprendegit.com/que-es-un-pull-request/) en el [ParSi](https://github.com/sisoputnfrba/parsi) para explicar como instalarlo; y/o agregar en el `Makefile` del rooy del proyecto la regla para "instalar"?

**Comment by ltrinidad** [comment]
Jaja, que groso Joaco!! dale, ahí veo si me sale 😄

**Comment by ltrinidad** [comment]
Creo que ya hice el pull request, cierro!
