### ISSUE TITLE
Consola del planificador mal subida en la errata

### ISSUE THREAD

**Issue by NicoFeld** [sisoputnfrba/foro#1032]
En el enunciado ahora dice por ejemplo: 
bloquear  : Se bloqueará el proceso ESI hasta ser desbloqueado (ver más adelante), especificado por dicho  en la cola del recurso . Vale recordar que cada línea del script a ejecutar es atómica, y no podrá ser interrumpida; si no que se bloqueará en la próxima oportunidad posible. Solo se podrán bloquear de esta manera ESIs que estén en el estado de listo o ejecutando.

El comando bloquear recibia parametros y ahora no, lo mismo con todos los otros que reciben parametros

**Comment by iago64** [comment]
Mil gracias @NicoFeld ahora lo revisamos y lo corregimos

**Comment by iago64** [comment]
@NicoFeld Mil disculpas por la demora, ya se encuentra fixeada la errata: https://sisoputnfrba.gitbook.io/re-distinto/planificador

Saludos.-
