### ISSUE TITLE
Fórmula de la media exponencia

### ISSUE THREAD

**Issue by sebastianciancio** [sisoputnfrba/foro#1034]
El alfa de esta fórmula no debiera ir entre 0 y 1?

**Comment by afilgueira** [comment]
Si, pero parsear decimales es algo que no necesitamos que hagan :tongue:. Piensenlo como un "porcentaje" (50 sería 0,5 por ejemplo)

**Comment by sebastianciancio** [comment]
Ok... muchas gracias.
