### ISSUE TITLE
Versión PDF del enunciado

### ISSUE THREAD

**Issue by thehighestprimenumber** [sisoputnfrba/foro#1035]
Hola!
Quería pedirles si podían habilitar una versión en pdf del enunciado a través de gitbooks, ya que actualmente hay que ir navegando sección por sección, y cuando estamos offline se complica.

https://help.gitbook.com/books/how-can-i-provide-a-pdf-version-of-my-book.html

Muchas gracias

**Comment by jazcarate** [comment]
Buenas!
GitBook está sufriendo una gran renovación, y no nos dimos cuenta que el
feature todavía no está implementado.

Voy a estar tratando de buscarle una solución; pero mientras tanto, siempre
podes [clonar en repo](https://github.com/sisoputnfrba/2018-1c-re-distinto)
del que se arma el libro, el formato es Markdown, así que es bastante
legible. Creo que en la vm está instalado el VisualCode para ver MDs.

**Comment by LeaTex** [comment]
También se puede usar el plugin MarkdownViewer para el Notepad++

**Comment by mgarciaisaia** [comment]
Ahí estoy pingueando a la gente de Gitbook a ver qué dicen sobre el export a PDF.

Se supone que hay un paquete de NodeJS para exportar un gitbook a pdf/epub/etc, pero parece que sólo funciona con la versión anterior de Gitbook. Si consiguiéramos una versión que funciona, podemos llegar a armar algo en Travis que compile el libro automágicamente, pero voy a esperar a que me contesten l@s amiguit@s de Gitbook primero ¯\\_(ツ)\_/¯

**Comment by thehighestprimenumber** [comment]
Gracias! no pensé que sería tan complicado :(

2018-04-26 14:03 GMT-03:00 Matias Garcia Isaia <notifications@github.com>:

**Comment by mgarciaisaia** [comment]
![In the 60s, Marvin Minsky assigned a couple of undergrads to spend the summer programming a computer to use a camera to identify objects in a scene. He figured they'd have the problem solved by the end of the summer. Half a century later, we're still working on it.](https://imgs.xkcd.com/comics/tasks_2x.png)

_In the 60s, Marvin Minsky assigned a couple of undergrads to spend the summer programming a computer to use a camera to identify objects in a scene. He figured they'd have the problem solved by the end of the summer. Half a century later, we're still working on it._

**Comment by afilgueira** [comment]
~He~ It

![image](https://user-images.githubusercontent.com/1786754/39598449-f201f242-4eee-11e8-9eb8-fbe354e4f76c.png)

**Comment by mgarciaisaia** [comment]
Siguiendo con la temática del enunciado, _ahí vino_ (no confundir con _hay vino_).

Si quieren revisar...

**Comment by afilgueira** [comment]
@mgarciaisaia lo revisé y convino. Pero no combino con vino
(bloqueame antes de que sea tarde)

**Comment by jazcarate** [comment]
Se puede cerrar? :dancer:

**Comment by iago64** [comment]
Lo damos por cerrado ya que en el post del blog están las versiones PDF, EPUB y MOBI del enunciado.

Saludos.-
