### ISSUE TITLE
Planificación de los procesos ESI y sus estimaciones

### ISSUE THREAD

**Issue by sebastianciancio** [sisoputnfrba/foro#1036]
Aca van mis dudas.

Suponiendo que tanto el Planificados, Coordinador y las Instancias ya están conectadas entre sí... y aparecen los ESIs en escena.

La secuencia sería:

1) El ESI1 se conecta al Coordinador y al Planificador para indicarle que existe un proceso nuevo. En esta conexión, debiera indicarle que existe un proceso nuevo y también la próxima operación a ejecutar.
2) Una vez que el Planificador cargo la cola de Ready con ESI1, automáticamente arranca (según el algoritmo de planificación determinado en el archivo de configuración) y le manda un mensaje a ESI1 para indicarle que ejecute la próxima instrucción.
3) El ESI1 determina cual es la próxima instrucción a ejecutar y se la pasa por mensaje al Coordinador. El Coordinador ejecuta la instrucción a través de una Instancia (según el Algoritmo de Distribución) y luego notifica a ESI1 sobre el resultado de la operación (EXITO o FRACASO)
4) El ESI1 se comunica con el Planificador y le transmite el resultado de la operación (EXITO o FRACASO)
5) El Planificador planifica el próximo proceso a ejecutar y le manda un mensaje al ESI correspondiente.

Creo que lo antes explicado es un resumen de la secuencia a grandes rasgos.

La consulta tiene que ver con las **estimaciones de las ráfagas**.

Para poder planificar SJF (por ej.), debo conocer entre todos los ESIs de la cola de Ready cual es la próxima ráfaga a ejecutar y cual fue la anterior... correcto?

**Comment by afilgueira** [comment]
Sobre la pregunta original, *no*. No debés *conocer* (de hecho no podés hacerlo) sino que tenés que estimarla.

**Comment by afilgueira** [comment]
Sobre la otra pregunta (tip pro: abran otro issue y linkeen el original con #1036), a que llaman "Fracaso"?

**Comment by sebastianciancio** [comment]
Muchas gracias por la respuesta.
