### ISSUE TITLE
asignación de códigos de instancias y ESI

### ISSUE THREAD

**Issue by gastoncastineira** [sisoputnfrba/foro#1038]
Hola Internet!

Como dice el título estamos con problemas entendiendo de donde salen esos códigos. 
Primero, los ESI sabemos que tienen una clave que los identifique en el sistema porque la consola del planificador la demanda para algunas instrucciones. No hay idea alguna de dónde se le asigna a cada ESI que entra en el sistema dónde se le debe asignar su clave unívoca o si debe seguir alguna estructura (como decir, ESIx y x sea algún número distinto para cada ESI). Esto es porque en los scripts de los ESI usan mucho cosas del estilo "materia:K3013", pero esos códigos son de los recursos que maneja la tabla de entradas del proceso instacias ¿no?
Eso además me lleva a la segunda pregunta. Si bien en caso que se use una clave de recurso errónea (osea, que no se encuentre en la tabla de entradas de instancia) el ESI se debe abortar, ¿dónde se le cargan estas claves y valores a instancia? Sé que la cantidad y tamaño de entradas viene dada por el coordinador, pero la clave de estas tampoco sabemos de dónde debe salir. Siguiendo el ejemplo, cómo sabe instancia que su entrada 17 es la clave materia:K3013. ¿Dónde debo cargarle yo esa información y, de nuevo, que estructura deben seguir esas claves?

**Comment by afilgueira** [comment]
Con lo que vimos hoy quedo la idea, seito?
Igualmente aclararemos dos o tres de estas cositas en la errata 2

**Comment by gastoncastineira** [comment]
Totalmente! Pensaba dar la explicación por acá para los que se confundieran como yo pero si vienen para la próxima errata me ahorro el testamento :P
Gracias de nuevo sensei!
