### ISSUE TITLE
Operacion store sobre Esi bloqueado.

### ISSUE THREAD

**Issue by imettaUTN** [sisoputnfrba/foro#1039]
Suponiendo que tengo un ESi1 Y  un ESI2 y una clave "Personaje"
1)Store  unicamente lo hace el Es1 que hizo get sobre la misma clave? o puede pasar que un esi haga un get sin hacer un store y viceversa .

2) Utilizando un algoritmo de desalojo,  si ambos Esis tienen en su script un store y get sobre la clave "Personaje" . Si antes de hacer un store de la clave en el ES1, comienzo a ejecutar el Es2 , leo un Get de la clave y me bloqueo ( Por estar el recurso tomado) . Vuelvo a ejecutar  el Esi1 y ejecuto el store. ¿Que debo hacer? Si ejecuto el store de ESI1 en teoria se desbloquearía  tanto el ESI1 y el ESI2 , pero al volver a correr el ESI2 y leer el store, estaria liberando un recurso que ya no esta tomado. ¿Lo ignoro?.

**Comment by afilgueira** [comment]
1) Puede pasar. Dependerá de qué tan malo sea quién arme las pruebas. De su lado no necesitan validarlo. Si un ESI hace un store y no hizo un get, él sabrá lo que hace...

2) No termine de entender el caso al 100%, pero el store desbloquea a *uno sólo* (el primero) si lo hubiera.

**Comment by afilgueira** [comment]
Hola, el que lo ejecutó no puede estar bloqueado. Si no, no podría haber ejecutado :thinking: 
La idea es que los get y store funcionen como los wait y signal de los semáforos (con alguna cosita extra).

**Comment by imettaUTN** [comment]
entonces Ejemplo
![primero](https://user-images.githubusercontent.com/31007863/39381612-206f8c3a-4a39-11e8-8b5d-550ef13882ef.jpg)
![segundo](https://user-images.githubusercontent.com/31007863/39381624-25b98a4c-4a39-11e8-8590-c8b010a68cf3.jpg)

:
Tenemos en la cola de listo a 3 ESIs 
todos tienen GET y STORE de la misma clave, 
comienza:
1.- ESI1 hace GET personaje
2.- ESI1 es desalojado por ESI2 (suponiendo q es de mas prioridad)
3.- ESI2 trata de hacer GET pero como el recurso esta 
tomando se bloquea
4.- ESI2 va a bloqueados y continuea ESI3
5.- ESI3 hace GET del recurso y dado que sigue tomado 
se bloquea
6.- regresa ESI1, hace STORE -> al hacer store, primero libera 
la clave que tenia tomado, luego busca al primero de la cola
de bloqueados por este recurso (ESI2), registra que ESI2 ahora
tiene este recurso y por ultimo manda a ESI2 a listos y finaliza
ESI1
7.- dado que el unico en listos es ESI2 por ahora, este
hace la siguiente operacion que es STORE, esto libera la 
clave nuevamente y busca el primero de la lista de bloqueados 
que seria ESI3 para asignarle el recurso y llevarlo a listo,
finalmente finaliza ESI2
8.- ahora ESI3 ejecuta su STORE, libera el recurso, no liberamos
a ningun ESI ya que no hay nadie bloqueado para
ese recurso y finaliza ESI3.

RESUMEN:
1.- STORE solo libera al primer ESI que este en bloqueados 
para ese recurso
2.- Al liberar a un ESI tambien le asigna el recurso para que 
cuando le toque ejecutar pueda hacer el store sin problemas.

**Comment by afilgueira** [comment]
Hola, el paso 6 está mal. El esi vuelve a listos y reintenta hacer el get.
Si esta vez puede obtenerlo, continua (está de hecho es la diferencia más
grande con un semáforo bloqueante).

Saludos!
