### ISSUE TITLE
Eliminar claves en desconexión de instancias

### ISSUE THREAD

**Issue by natoszme** [sisoputnfrba/foro#1040]
Buenas! 👋
En el Coordinador dice:

2- El Coordinador procesa la solicitud en su algoritmo de distribución con el fin de determinar la Instancia a la que se le asignará la solicitud(^6).

En el caso que el coordinador decida en el paso 2 que la operación no puede ser ejecutada porque la instancia no existe más en el sistema, o porque el recurso al que intenta acceder se encuentra tomado(^7), le avisará al Planificador. El Planificador encolará el ESI en cuestión en una cola de bloqueados; **en ambos casos haciendo referencia al recurso que se intentó bloquear.**

Supongamos el caso en que la instancia se cayó. Si buscamos lo que dice en Distribución:

"...No se deberá eliminar una clave si la instancia de desconectó; solo se elimina cuando un ESI intenta acceder a ella..."

En este caso, el esi está intentando acceder a la clave y la instancia se cayó, pero mientras que en la primer cita dice que se debe almacenar la clave, en la segunda dice que la clave se debe eliminar (y por lo tanto, supongo que no debe encolarse). Esto no me cierra.

Asumo que con eliminar se refiere a sacar de la lista de claves bloqueadas, y no físicamente del archivo de la instancia (ya que se perdió la referencia a la misma por haberse desconectado).

Aprovecho para hacer otra pregunta: los algoritmos de distribución sólo se utilizan para la operación SET o también en los otros casos? Por sentido común creería que es así, pero en los pasos del coordinador (más precisamente en el 2, el que cité arriba) parece utilizarse siempre. De hecho el algoritmo de equitative load no menciona nada al respecto pero los otros dos si. Más vale preguntar esto ahora que más adelante cuando sea tarde jeje

Gracias!

**Comment by natoszme** [comment]
PD: no estaría pudiendo agregarle un label. Debería pararme a la derecha del issue donde dice Labels?

**Comment by afilgueira** [comment]
Hola, la confusión viene porque, como vos decís, el set es el que dispara los algoritmos. Vamos a aclararlo mejor en la próxima errata. Saludos!

**Comment by natoszme** [comment]
Gracias!

**Comment by natoszme** [comment]
Qué onda con la primera parte de la duda? Lo cerré antes de tiempo jeje

**Comment by afilgueira** [comment]
En la errata lo vamos a aclarar. En principio pensalo en dos pasos: qué debería pasar si la instancia no está y qué debería pasar si la clave no existe.

Saludos!

**Comment by natoszme** [comment]
En la parte de que la clave no existe, a qué momento del sistema te referis?

Gracias!

**Comment by afilgueira** [comment]
Paso 1: El TP especifica cierto comportamiento si una instancia se desconecta. Si vas a buscar algo que no está (porque la instancia se cayó), dependiendo de la sentencia tenés que hacer algo.

Paso 2: La clave no existe, dependiendo de la sentencia, tenés que hacer algo.

Ejemplo: es un store sobre una instancia caída. El coordinador cree tener la clave, pero la instancia no está, se elimina de la tabla. Como no podés hacer un store sobre una instancia caída, devolvés el error que corresponde.

Saludos!

**Comment by afilgueira** [comment]
Lo vamos a aclarar bien en la errata 2. Entiendo que un store sobre algo que no existe debería ser un abort, pero aguanta a que lo definamos bien este finde. Saludos!

**Comment by ricardoAguirreSanchez** [comment]
Genial, porque así como ese caso hay otros por ejemplo, en el caso de un set, donde el coordinador busca en su tabla si tiene una instancia para esa clave, si no, aplica el algoritmo y elije una, cuando a esa que elijo le pido hacer el set  y esta se desconecta antes de mandarme la respuesta de la operación tampoco se menciona si esto seria un abort o si hay que hacer algo mas. Pero bueno espero a la errata.
O en el caso del store donde tengo que enviar mi petición tanto al planificador como a la instancia, si alguno de ellos me retorna que no pudo hacer la operación entendería que como son parte de un todo que es la operación STORE, el resultado seria que falló, cosa que tampoco se si seria un abort.

Entonces esperamos la errata.
Saludos.

**Comment by natoszme** [comment]
Cierro el issue aunque dependa de la errata?

Gracias!

**Comment by afilgueira** [comment]
Diria que si. Si cuando sale la errata te parece que queda algo gris, abri un issue nuevo referenciando a este. Saludos!

**Comment by natoszme** [comment]
Buenas! Reavivo porque no me quedó claro:

> 2- El Coordinador procesa la solicitud en su algoritmo de distribución con el fin de determinar la Instancia a la que se le asignará la solicitud(^6).
> 
> En el caso que el coordinador decida en el paso 2 que la operación no puede ser ejecutada porque la instancia no existe más en el sistema, o porque el recurso al que intenta acceder se encuentra tomado(^7),

En este caso de set (que es cuando se dispara el algoritmo de distribución) de clave no tomada por él, se bloquea la clave igual? Esto no sería sólo con el **get**?
Tenía entendido que en caso de set/store de clave no tomada por el esi, es un abort. O sea que si el esi hizo get y después hace un set pero la clave está todavía tomada por otro esi, se **aborta**.
Esto es así? Lo tenemos codeado así pero quería validarlo por las dudas

**Comment by iago64** [comment]
Buenas buenas!
El coordinador va a elegir a que instancia va a ir la operación (si es el primer SET va a aplicar el algoritmo de distribución, si es un segundo SET o un STORE va a ver en que instancia esta la clave)
El único que bloquea claves es GET, pero puede ser que alguien quiera hacer GET de un recurso ya tomado y asignado a una instancia y ahi se tenga que bloquear el ESI.
Y por ultimo si, set/store sin clave bloqueada, es un abort por [Error de Clave no Bloqueada](https://sisoputnfrba.gitbook.io/re-distinto/anexo-i-lenguaje-operactiones#error-de-clave-no-bloqueada)
Saludos.-
