### ISSUE TITLE
CONSULTA MODULO INSTANCIA implementacion de estructura de almacenamiento de datos 

### ISSUE THREAD

**Issue by nrmerlis** [sisoputnfrba/foro#1043]
Estamos con el equipo realizando el modulo INSTANCIA y nos surgió la duda de como deberíamos implementar la estructura de datos donde vamos a almacenar los valores que nos llegan. 
Pensamos que estaría bueno manejar la memoria con listas de nodos, donde cada nodo contiene una entrada con su tamaño máximo disponible y la lista tiene tantos nodos como entradas máximas permitidas.
¿hay algún problema en manejar la memoria así?

Gracias.

**Comment by afilgueira** [comment]
En principio, para nosotros no. Ahora, yo les recomendaría que miraran las commons, que creo que hay unas cuantas cosas que les van a resultar más útiles y fáciles (como diccionarios).

Saludos!

**Comment by tferraro** [comment]
@nrmerlis que onda con esto? Sigue la duda o te sirvió la respuesta? Si te sirvió, sentite libre de cerrar el issue, sino, de repreguntar :slightly_smiling_face:

**Comment by nrmerlis** [comment]
Todo muy claro, gracias.
