### ISSUE TITLE
Consulta de esi bolqueadas por get

### ISSUE THREAD

**Issue by natoszme** [sisoputnfrba/foro#1045]
En el caso de que un script ejectuado en el Esi haga un set/store debe considerarse que ese mismo script haya hecho get de la clave? En ese caso, la clave no sería considerada bloqueada, y por lo tanto se bloquearía al esi en cuestion? O por ser el mismo esi el que la bloqueo, puede ejecutar el set/store?

**Comment by afilgueira** [comment]
Hola, no deben considerar nada. Si el ESI hace un set/store, simplemente háganlo. Un "buen programador ESI" debería hacer el `get` antes y si no lo hace, y algo "se rompe", es algo esperable.

Saludos!
