### ISSUE TITLE
Segmentation fault mágico y misterioso

### ISSUE THREAD

**Issue by FrancoVentrice** [sisoputnfrba/foro#1046]
Buenas!

Va a ser difícil explicarlo dada su magitud y misteriosidad, pero voy a tratar de hacerlo simple a ver si lo sacan al toque, y sino trato de explayarme mas.

Cuando levanto la configuracion del planificador, me guardo un string de claves bloqueadas separadas por ", ", al cual luego hago string_split e itero para bloquearlas (eso lo debugueé y pareciera andar bien).

Cuando termino de levantar toda la configuración, loggeo todos los valores para checkear que todo esté correctín. Ese log andaba bien hasta hoy, pero cuando agregué la iteración de las claves, empezó a romper. (No rompe durante la iteración, sino en la linea que hago log_info(logger, blablabla);)

Si comento la parte de la iteracion, ese log vuelve a andar bien y el planificador sigue su curso

Suficientemente magico? nah

Probando y probando me di cuenta que si descomento la iteracion y agrego un "puts(algun string);" antes de hacer el log, el log_info deja de romper!

Por ultimo, si debuggeo sin el puts y me fijo que onda el log_info, el debugger me tira un mensaje algo asi como "can't find source file at "build/.../libio/fileops.c" Locate the file or edit the source lookup path to include its location" (la maquina virtual no me deja copiar y pegar con la maquina host)

Ya no se que puede ser, si se les cae una idea tirenla para aca xD

Saludos

**Comment by FrancoVentrice** [comment]
Update:
Hice un par de cambios en las estructuras que manejan las claves bloqueadas, y ahora anda con todo y sin el puts. Claramente algo mal tenia el manejo de esas estructuras, de todas formas lo dejo abierto por si alguno sabe por que el bug se presentó de esa manera.

**Comment by FrancoVentrice** [comment]
Buenas

Ya que no puedo reproducirlo nuevamente, me voy a limitar a quedarme con los videos que me pasaste y probar cuando vuelva a suceder. Como último comentario, sobre el tema del error que no es, es raro que me pase eso entonces porque siempre debuggeo con step over; y pensándolo bien tampoco responde a que anda con un puts previo. Pero bueno, ya volverá a aparecer (espero que no).

Cuando leas esto, cerralo si querés xD

Saludos!

**Comment by mgarciaisaia** [comment]
No te creas, che - no es tan raro.

Cuando tu programa intenta acceder a una zona de memoria que no le corresponde (aka, "un segmentation fault"), el sistema operativo envía una señal al proceso, y el proceso aborta.

En las charlas de este cuatri no vimos señales, pero en la teoría habrán visto que es un mecanismo de comunicación entre procesos. Una señal es, básicamente, un aviso de que algo sucedió - y tu proceso tiene la chance de ejecutar algo de código que reaccione a eso.

El debugger de C, por otro lado, está configurado para que, por defecto, pause la ejecución del proceso cuando éste reciba una señal. Entonces, claro - vos le das a `Step over`, pero durante la resolución de esa llamada (es decir, durante todas las instrucciones que componen a la función que llamaste), alguna genera un segmentation fault, y entonces el kernel envía una señal a tu proceso, y entonces el debugger ataja esa señal y se pausa y te ofrece debuggear. Y, como tu proceso estaba ejecutando una función _dentro_ de la que vos estabas intentando saltear, buen, el debugger intenta mostrarte la función de más adentro de todo. Y de esa no tenés los fuentes, y de esa eclipse te dice que no tenés los fuentes para ver.

Así que, eso: no es tan raro.

¡Salute!
