### ISSUE TITLE
Consulta sobre INSTANCIAS y ENTRADAS

### ISSUE THREAD

**Issue by ricardoAguirreSanchez** [sisoputnfrba/foro#1048]
Buenas,
Estamos empezando con la instancia y nos surgieron unas dudas:

1.- Tenemos entendido que una instancia tiene un STORAGE y una TABLA DE ENTRADAS, donde:
STORAGE: es una estructura creada de acuerdo a la cantidad de entradas por el tamaño de la entrada que nos da el coordinador, lo que queríamos saber con un ejemplo es que guarda una instancia en su storage y su tabla de entradas?

**Ejemplo** 
SET 00:44 persona -> lo que guardaría en el STORAGE seria:
Entrada 1 [ persona ]
Entrada 2 [               ]
Entrada 3 [               ]

(Y en mi TABLA DE ENTRADA lo que debo guardar según el enunciado es clave, n° de entrada y tamaño de entrada)

CLAVE  |  n° de ENTRADA | Tamaño
-----------------------------------------
00:44   |                         1  | 8 

es asi?

3.- Tenemos entendido que el algoritmo de distribución es para elegir una instancia y pedirle que haga la operación SET (porque GET y STORE van para el planificador), pero si yo llevo un registro de <INSTANCIA , CLAVE> y se por ejemplo que la INSTANCIA1 hizo anteriormente [SET **00:12** persona], entendemos que si ahora volvemos a recibir una operación [SET **00:12** animal], lo que hago es directamente pedirle a la INSTANCIA1 que lo haga sin necesidad de aplicar el algoritmo de distribución o siempre se aplica el algoritmo de distribución y que toque la instancia que toque?

4.- La idea de hacer el **DUMP** es para luego en caso de desconectarse la instancia y volver a conectarse poder cargar los datos en su STORAGE y TABLA DE ENTRADAS, no? 

Saludos.

**Comment by afilgueira** [comment]
1 - cómo lo guarden depende de cada equipo. Lo importante es que esa data esté ahi.
2 - ?
3 - El algoritmo es para guardar por primera vez la key
4 - Si

Saludos!

**Comment by ricardoAguirreSanchez** [comment]
3.- Si no me equivoco entiendo que la única operación que le llega a la instancia es hacer 
SET CLAVE VALOR
Es decir, los pasos serian:

Paso 1: coordinador recibe SET 00:11 Jugador1

Paso 2: me fijo si tengo alguna instancia que ya tenga la clave 00:11

Paso 3: si no, aplicó algoritmo para elegir alguna de las instancias que tenga disponibles

Paso 4: le pido a la instancia hacer set 00:11 jugador1, la instancia guardara el valor (jugador1) en su storage (el mismo que está dado por número de entradas y tamaño según el coordinador) y la clave (00:11) en su tabla de entradas

Paso 5: si luego llega la operación [SET 00:11 jugador2], y tengo registrado que la instancia1 tiene la clave 00:11, entonces no aplicó el algoritmo y directamente uso la instancia 1 para esta nueva operación.
Es así?

Saludos.

**Comment by natoszme** [comment]
La instancia no podría recibir también un store?

**Comment by ricardoAguirreSanchez** [comment]
Pensé que no, la operación GET y STORE era para tomar o liberar los recursos y pensé que eso lo manejaba el planificador, es decir, al coordinador le llega la tarea y este lo envía al planificador, y solo los SET los envía a un **instancia**, pero bien, si estoy equivocado es bueno saberlo desde ahora, si la operación store va a la instancia también, que debería hacer la instancia? borrar de su storage la clave ?

**Comment by afilgueira** [comment]
La instancia debería recibir el store, si si. El store, además de desbloquear, primero guarda "en disco".

**Comment by ricardoAguirreSanchez** [comment]
Bien, si al recibir:
STORE jugador1 (esta operación solo tiene clave), el coordinador se lo manda a la instancia y esta lo guarda PERO en el storage donde normalmente gustaba los VALORES (valores me refiero al segundo parámetro de la operación SET) de cada clave (SET CLAVE VALOR) ahora no guardaria nada?

**Comment by afilgueira** [comment]
No no, si mandas un STORE lo primero que necesitas saber es que instancia corresponde. Al darte cuenta de que no está disponible, haces algo al respecto conforme dice el enunciado (ej: borrar esa clave). Luego, continuas... que debería pasar si la clave donde necesito hacer el STORE no existe?

Como decía, en la errata vamos a agregar algunos ejemplos más para estos casos. Saludos!

**Comment by ricardoAguirreSanchez** [comment]
Gracias.
