### ISSUE TITLE
Conexión en VM

### ISSUE THREAD

**Issue by agnmeinardo** [sisoputnfrba/foro#1049]
👋 ¡Hola!

Buenas! Hoy fui a consultar sobre este tema al mediodía, pero no encontré a nadie. El problema es que de un día para el otro me dejó de tener red la VM. Dejo prints para mostrar cómo lo tengo configurado:

![2018-04-28](https://user-images.githubusercontent.com/11727327/39402816-e78f5752-4b40-11e8-81fd-209d8266d7b5.png)
![2018-04-29](https://user-images.githubusercontent.com/11727327/39402817-e7b48b8a-4b40-11e8-82fc-143202cd24b2.png)

En el nombre de adaptador de red de la configuración puse todos los que había y fui probando. Ninguno funcó

**Comment by tferraro** [comment]
Buenas!

Seguramente no encontraste a nadie debido a esto: https://www.utnso.com/suspension-de-la-charla-de-la-tarde/

Si lo tenés configurado como adaptador puente, puede que no te levante ip por conflicto de direcciones fisicas. Fijate de en Avanzadas de hacer click en el icono de refresh para cambiar la MAC address y contanos que onda.

Saludos!
Tom

**Comment by agnmeinardo** [comment]
Colgué en cerrar el issue. El sábado opté por lo más fácil: borrar la VM y se solucionó :)
Tendré en cuenta por si me vuelve a pasar. Gracias!
