### ISSUE TITLE
Consulta sobre los nombres de la Instancias + Sugerencia

### ISSUE THREAD

**Issue by santiluccadeguevara** [sisoputnfrba/foro#1050]
Hola de nuevo XD

Esta vez mi pregunta radica en si se pueden tener dos Instancias distintas con el mismo nombre. Nos interesa para la administración de Instancias del Coordinador, y para el tema de reincorporar una Instancia, por ahora.

De paso aprovecho para tirarles una sugerencia: hay muchos issues variados en el foro y cuesta encontrar si ya hubo alguno similar (al menos desde mi punto de vista).

Así que, como tienen un repo también para la errata del TP, estaría bueno que las consultas sobre el enunciado del TP también entren ahí y se les pueda asignar un label al mismo para que se pueda buscar mejor: por ejemplo, a este issue que tiré le hubiera puesto el label "instancia" en el repo "2018-1c-re-distinto". No sé si me explico.

Estaría bueno que lo consideren, si es que no lo hicieron. Es cierto que hay que vigilar más repositorios y no es algo para implementar de un día para el otro, pero pienso que podría agilizar las búsquedas a futuro. Desde ya, un saludo.

**Comment by LeaTex** [comment]
Según parece ser, nada impide que más de una instancia se ejecute con el mismo nombre en la configuración. Sería algo válido para la instancia, porque no se conocen entre ellas.
El que tiene este conocimiento es el coordinador, así que debería ser él quien decida qué hacer.
Al menos así lo veo yo (como diría Nimo).

**Comment by iago64** [comment]
Buenas buenas!!
Como bien dijo @LeaTex las instancias no saben que otras instancias están ejecutando, con lo cual podes tener 2 instancias con el mismo nombre, a fines prácticos para el coordinador van a ser 2 conexiones distintas, con lo cual, tenes 2 opciones:
1.- Rechazar la conexión de la segunda instancia con un mensaje de "Ya hay una instancia con ese nombre"
2.- Omitir el nombre de la instancia y utilizar algún identificador propio como para manejar la instancia y que si te dan ganas le agregues el nombre.

Pero volviendo sobre la idea, la instancia no es responsable de saber si hay más con su mismo nombre, sera algo que se va a enterar a posteriori.
Saludos.-

**Comment by santiluccadeguevara** [comment]
Buenísimo. Estábamos entre esas dos decisiones con el equipo. Ahora vamos a ver cuál preferimos más.

Gracias a ambos. Saludos!!
