### ISSUE TITLE
Retardo en el Coordinar - ¿Cuándo usarlo?

### ISSUE THREAD

**Issue by LeaTex** [sisoputnfrba/foro#1051]
Hola.
Vemos que el Coordinar tiene el parámetro "retardo" en la configuración. Y la única referencia que hay al mismo es en el checkpoint 4 que dice "implementar retardos".

Entendemos que la idea es simular que el procesamiento lleva cierto tiempo, para que no sea todo tan rápido.
La pregunta es: ¿en qué punto de la ejecución se debería aplicar dicho retardo?

**Comment by iago64** [comment]
Buenas buenas!!
En el enunciado te dice algo asi como:
> Para poder simular el paso del tiempo en la ejecución, cada vez que un ESI le pida ejecutar algo, la acción estará supeditada a un retardo ficticio dado por archivo de configuración.
Esto quiere decir, cuando vas a ejecutar la instrucción del ESI, podes:
1.- Ejecutar la instrucción -> hacer el sleep() -> contestarle a la instancia
2.- Hacer el sleep() -> ejecutar la instrucción -> contestarle a la instancia
No es mucho más que eso :)

Saludos.-

**Comment by LeaTex** [comment]
ah changos, lo tendría que haber buscado en el PDF.

en el buscador de gitbook no salió.

![image](https://user-images.githubusercontent.com/6115573/39448105-462cd41a-4c9a-11e8-96d9-d1668f054c49.png)

gracias! quedó claro.
