### ISSUE TITLE
Consulta deadlock

### ISSUE THREAD

**Issue by imettaUTN** [sisoputnfrba/foro#1052]
A efectos del trabajo practico 

1) ¿ como consideramos que se formo un deadlock en planificador? Dado que segun la teoria es cuando todos los procesos se encuentran bloqueados a la espera de un recurso que no es liberado por el proceso que lo tomo en forma exclusiva. Pero no sabemos si seria correcto considerar , en el tp, que el deadlock se va a producir cuando todos los Esis no finalizados , se encuentren bloqueados por una clave que tomo otro esi y que no libero nunca. De ser asi, ¿ que tiene que pasar para que consideremos que se formo un deadlock ?

2) ¿como resuelvo el deadlock?, segun el tp , deberia realizar un kill del esi que genero el bloqueo, pero que me asegura que no tenga n  esis bloqueados por la clave A, y que al liberar el Esi que bloqueo A, el siguiente esi en la cola de bloqueados me siga generando un Deadlock?.

Muchas Gracias!.

**Comment by varas-c** [comment]
Buenas!

1 - El planificador sabe que claves fueron bloqueadas por cada ESI, por lo
que podrías, a partir de esa info,deducir que ESIs estan en Deadlock.
Acordate que el algoritmo tiene que ser *de detección* y no de prevención.
En la parte de blocking del tp, podes leer un caso de còmo serìa un deadlock
<https://sisoputnfrba.gitbook.io/re-distinto/anexo-i-lenguaje-operactiones#blocking>

2 - Nada te lo asegura. Si estás en ese caso, simplemente vas a tener que
matar "n" procesos hasta que se elimine el deadlock. Si matas 1 y el
deadlock sigue, mala suerte, hay que matar otro y así sucesivamente.

2018-04-30 19:59 GMT-03:00 imettaUTN <notifications@github.com>:

**Comment by afilgueira** [comment]
Un detalle sobre 1) el deadlock está cuando se cumplen las 4 condiciones. A fines prácticos, vas a necesitar implementar el algoritmo de detección. Saludos!

**Comment by iago64** [comment]
@imettaUTN La duda fue resuelta? se puede cerrar el issue?

**Comment by imettaUTN** [comment]
si gracia!
