### ISSUE TITLE
servidor no conecta con cliente en pc's distintas

### ISSUE THREAD

**Issue by macetosella** [sisoputnfrba/foro#1054]
Hola que tal?

Nuestro problema es que si pruebo un servidor con un cliente en cosolas de la misma pc funciona todo ok pero cuando intento hacerlo en pc's distintas no me conecta.
Mire ambos ips, estoy en la misma red, si hago ping en ambas pc me responde correctamente, probe agregando las ip en el archivo /etc/hosts y sigue sin funcionar. El error que me tira es "Connection refused".
Estoy usando el puerto 8000. Ya mire q las mac sean distintas. Probe pidiendo un nuevo ip y tmp funciona ¿como puedo solucionar este tema o que pista me pueden dar?

Muchas gracias! y feliz dia del laburador

**Comment by natoszme** [comment]
Buenas! Si cambias NAT por puente en la configuración de Virtual Box? A nosotros nos anduvo eso

**Comment by macetosella** [comment]
Gracias por responder, me olvidé de ponerlo, Pero ya hice eso tmb.

**Comment by mgarciaisaia** [comment]
Tocayo, ¿estás segurísimo de que los pings están yendo a la máquina
correcta?

No se si conocés netcat (el comando nc - probá man nc si no), podrías
usarlo para probar la conexión con la garantía de que el código del
programa es correcto. Hacé nc -l 8998 en una máquina y nc
la-ip-de-esa-maquina 8998 en la otra para probar la conexión. Una vez
conectados, lo que escribas en una consola (y le des enter) debería
aparecer en la otra. Si no se conectan, tenés un problema en la red.

Podés compartirnos los datos de las conexiones de cada una, si no, para ver
qué onda.

**Comment by iago64** [comment]
@macetosella  que tal? Esta resuelta la consulta? Se puede cerrar el issue?

**Comment by macetosella** [comment]
Ya está resuelto. El problema era que como IP local  tenía q usar 0.0.0.0 y yo estaba usando 127.0.0.1
