### ISSUE TITLE
Consulta consola del planificador

### ISSUE THREAD

**Issue by melaibanez** [sisoputnfrba/foro#1055]
Hola. Estamos haciendo la consola del planificador. En el mismo tenemos un menú que muestra las operaciones que se puede ejecutar, y las funciones están en un switch. Para pausar/continuar la planificación que debería implementar? Busque para poder hacerlo con sycall pero la verdad es que no entiendo.

Disculpen pero me cuesta entender y seguramente los voy a llenar de preguntas.
Gracias.

**Comment by tferraro** [comment]
Buenas!

Como hablábamos con un compañero tuyo por acá #1053, la pausa del planificador es que para o continúa el llamado a ejecución de los ESIs. No tiene que ver con el proceso Planificador en si, sinó a la tarea de planificación :slightly_smiling_face:, por lo que no tendrías que buscar ninguna syscall para realizarlo.

Como se te ocurre de pausar alguna tarea que tenga tu mismo proceso, desde el hilo de la consola?

Tom

**Comment by iago64** [comment]
@melaibanez que tal? Esta resuelta la consulta? Se puede cerrar el issue?

**Comment by melaibanez** [comment]
Hola! Si, se nos ocurrió utilizar semáforos, la herramienta que nos explicaron el sábado pasado. 
Gracias!
