### ISSUE TITLE
Conexión Planificador - Esi

### ISSUE THREAD

**Issue by leandroszikora** [sisoputnfrba/foro#1058]
Si el único mensaje que recibe el planificador del esi es "finalicé", y todos los mensajes que necesita para planificarlos los recibe del coordinador, entonces el planificador no tendría que llevar ningún select no? Y si así y todo tiene que tener un select que función tendría éste?
Gracias.

**Comment by varas-c** [comment]
Hola!

El Select te va a servir para monitorear una o muchas conexiones al mismo
tiempo.

Cuántos esis se conectan al planificador? Si tu respuesta es muchos,
significa que el planificador va tener muchos clientes que atender, por lo
que Select sería un amigo ideal para este caso.

Se entiende la idea? No te quedes con la duda y pregunta lo que necesites,
es fundamental la parte de sockets en el tp, si esto no funciona el día de
la entrega, no van a llegar a buen puerto 😢

Saludos!

**Comment by leandroszikora** [comment]
Claro entiendo, muchas gracias
