### ISSUE TITLE
Pregunta sobre funciones de las commons que reciben funciones como parámetros

### ISSUE THREAD

**Issue by matiasgasparini** [sisoputnfrba/foro#1059]
Hola, cómo va?

Estaba terminando unas cosas usando la biblioteca de listas, y me topé con la función list_remove_by_condition, que me resultó muy útil, pero la logro hacer funcionar si la función que le paso tiene sólo un parámetro. Hay alguna manera de pasarle una función con más parámetros?
Gracias!

**Comment by mgarciaisaia** [comment]
Tocayo, fijate si sisoputnfrba/so-commons-library#72 te ayuda.

Pensé que tenía alguna explicación más larga escrita, pero se ve que no. Leete eso para zafar, y en estos días trato de explayarme un poco más.

**Comment by matiasgasparini** [comment]
Gracias, Mati, lo terminé resolviendo usando un parámetro solo. Tengo en cuenta el enlace que me compartiste para futuras dudas!

**Comment by mgarciaisaia** [comment]
Che, ojo con eso, eh. ¿Estás segurísimo de que con un único parámetro va la cosa?

Pensalo a nivel _información que necesitás para determinar si se cumple o no la condición_. Si únicamente necesitás conocer al elemento, joya - pero, si no, probablemente te esté faltando algo más.

No te ensartes sólo para evitar lidiar con una parte del lenguaje que aún no manejás súper bien.

**Comment by mgarciaisaia** [comment]
:wave: Recién (_decí que no soy bombero_) publiqué [un video](https://youtu.be/1kYyxZXGjp0) hablando de este tema. Probablemente tu caso de uso haya quedado en el olvido, pero si podés repasar el video y contarme si solucionaba tu duda, se agradece, @matiasgasparini 👍
