### ISSUE TITLE
Link caído de ejemplo de uso de select

### ISSUE THREAD

**Issue by mesaglio** [sisoputnfrba/foro#1060]
En la pagina utnso, en el apartado de links utiles, hay un ejemplo de uso de select. Intente entrar pero dice : We're sorry! This account is currently unavailable.

[http://developerweb.net/viewtopic.php?id=2934](url)

**Comment by iago64** [comment]
Mil gracias por avisar, ahi arme un gist con lo que tenía originalmente el link:

[Ejemplos de Select
](https://gist.github.com/iago64/9f6acf5959846dc2a0f548ae3af7d34d)

Saludos.-
