### ISSUE TITLE
Instancia MMAP

### ISSUE THREAD

**Issue by FedericoJoel** [sisoputnfrba/foro#1061]
Buen dia, como estan?

Tengo una duda con respecto al desarrollo de la instancia.
En los entregables dice que deberiamos de implementar MMAP que si no mal entiendo, mapea a memoria un archivo fisico. Segun entiendo, no hace falta ir persistiendo esta informacion sino que tiene que estar en memoria y cada X cantidad de tiempo o al llegar un STORE, tengo que generar un archivo clave.txt donde su contenido es el valor.
Es asi? Por que no utilizar MALLOC?

Adicionalmente, yo tengo un dump cada 10 segundos que va a generar estos archivos clave.txt para todos los que tenga en las tablas de entradas.
Tendria que ir marcando los nuevos para saber cuales persistir?
Y si usan un STORE, ya lo doy por persistido?

Me da la sensacion que algo no estoy entendiendo ahi.
Abrazo.

**Comment by FedericoJoel** [comment]
Agrego una duda mas que me surgio. Este es el script de ejemplo

GET deportes:futbol:messi
SET deportes:futbol:messi Lionel Messi
GET deportes:basquet:ginobili
SET deportes:basquet:ginobili Emanuel Ginobili
# Persiste el dato de la instancia y libera esta clave
STORE    deportes:basquet:ginobili

De que hace el primer GET si en teoria, la clave se persiste recien cuando hacen un SET?
Que pasa si hace sun SET sin hacer un GET antes?
Adicionalmente, tengo una clave clave:hola con valor "Valor1" y le hago un get y un SET con otro valor, lo reemplaza?

**Comment by ricardoAguirreSanchez** [comment]
Yo tengo la misma duda, supongo que antes de cualquier sentencia, las primeras deben ser SET para que persistan la clave y luego cuando se haga el GET no se aborte el ESI

**Comment by iago64** [comment]
Buenas buenas!!

Vamos por partes asi es mas facil entender el problema:

1.- mmap(), por que y para que? 
    El por que les recomendamos que usen mmap(), es simplemente porque les va a ahorrar horas y dolores de cabeza al momento de persistir las claves en los archivos. Como mmap() les permite tener mapeado un archivo a memoria para grabar dicho archivo simplemente hacen un memcpy() a la dirección que les devuelve mmap() y listo, despues mmap() en cuanto pueda les baja el archivo a disco y uds ni se enteraron.

2.- Por que no usar malloc()?
    malloc() lo van a seguir usando ya que la instancia en SI es un malloc() donde tienen que guardar los datos y después de ese malloc() van a ir haciendo memcpy() a las direcciones de los archivos mapeados por mmap().

3.- El primer GET de `GET deportes:futbol:messi` lo que hace es reservar la clave para el ESI que la ejecutó.

4.- Que pasa si haces un SET de algo que no tenias hecho un GET antes, depende de si existe o no la clave, si existe cambia el valor y listo, si no existe, adios ESI que ejecuto el SET.

5.- Adicionalmente, tengo una clave clave:hola con valor "Valor1" y le hago un get y un SET con otro valor, lo reemplaza? Afirmativo, si tenes una clave con un valor y le ejecutas un SET despues, lo cambias.

**Comment by ricardoAguirreSanchez** [comment]
Buenas,

En el enunciado esta el Error de clave no identificada (pag 19), tenia entendido que ese error aplicaba en casos de hacer GET o STORE de claves que no existan (es decir de claves que no tenga registrado que alguna vez hice un set), lo cual me lleva a hacer un abort del ESI.
Entonces, si hago un GET sin hacer un SET antes, directamente aborto al ESI, o no?

**Comment by iago64** [comment]
Buenas! mil millones de perdones por la demora.
Podrías hacer un GET antes, devolver un null y reservar la clave para ese ESI.

Saludos.-

**Comment by ricardoAguirreSanchez** [comment]
1.- Entonces una manera de registrar (por ejemplo en alguna tabla dentro del coordinador) que una instancia1 tiene la clave1 es con la operacion GET ?

2.- Y cuando borro este registro? (pensando en el caso de que las instancias se pueden reconectar), lo borraria si luego de hacer un GET, recibo la sentencia SET, busco en mi tabla que la instancia1 tiene esa clave y cuando se lo pido veo q en realidad ya no esta conectada, entoces ahi recien paso a borrar el registro?

2.- Entonces a que se refiere este Error de clave no identificada (pag 19)?

3.- Y si hago un STORE sin antes hacer un GET? en teoria nunca registre que la instancia1 tiene la clave1, entonces deberia abortar al ESI o solo mandarle un mensaje de "no se pudo" ?

**Comment by FedericoJoel** [comment]
Me parece que no esta quedando muy clara cual es la funcion del GET, OK entendemos que "reserva el recurso" pero si puedo hacer un SET sin antes haber reservado el recurso, para que querria reservarlo?

**Comment by iago64** [comment]
@ricardoAguirreSanchez 
1.- No, las claves se almacenan en las instancias segun el algoritmo de distribución del coordinador, a lo sumo GET te asocia una clave con un ESI.
2.- Si la instancia esta caída y no registraste la clave en otra mediante SET, si haces GET es un error.
3.- Es el error de que estas tratando de acceder a una clave (GET) y esta no exista en el sistema. Mala mía en la respuesta anterior, ahí la edito.
4.- Podes hacer STORE de la clave si esta existe en el sistema, si no es un error.
5.- Este quedo medio confuso pero si no entiendo mal tu pregunta, la respuesta sería: el STORE limpia los bloqueos si los hay de la clave, pero nada mas (un ejemplo seria hacer STORE de una clave que te vino bloqueada desde el config). Acordate que el que cambia los valores de las claves es el SET, el STORE baja la clave al archivo.

@FedericoJoel el GET si te fijas en el anexo, lo que hace es intentar obtener el valor de la clave, obviamente si la **clave** no existe, si la clave existe pero no tiene valor entonces simplemente debería devolver de alguna forma algo que diga: "Clave sin valor".

![image](https://user-images.githubusercontent.com/1622109/39714361-333e1e34-5200-11e8-8117-915ba4bdede1.png)

**Comment by natoszme** [comment]
Buenas! No entendí la parte de la respuesta de arriba que dice que el GET intenta obtener el valor de la clave: el GET no se limita a bloquear la clave, independiente de su valor?
Además: cómo podría obtener el valor de la clave si la clave no existe?

**Comment by iago64** [comment]
@natoszme  Buenas!
Vamos por partes:
1.- Si la clave existe y no esta bloqueada:
  - Bloquea la clave para el ESI
  - Devuelve el valor

2.- Si la clave existe pero esta bloqueada:
  - Bloquea el ESI que ejecuto el GET

3.- Si la clave no existe:
  - Devolves el error de Error de Clave inexistente y abortas el ESI

Mil disculpas si hubo varios y graves errores de explicación de mi parte :(
Saludos.-

**Comment by FedericoJoel** [comment]
Ah ok, eso de que el GET devuelve el valor no lo lei en ningun lugar, hasta donde yo entendia por el momento solo lo bloqueaba. y que pasa con ese valor? a quien le interesa? quien lo consume?

**Comment by iago64** [comment]
Se lo devolverías al ESI que lo solicito mediante el GET y en el ESI como mucho lo escribís en el LOG, ya que el TP llega hasta ahí, no tenes una capa arriba del ESI donde tengas alguien que aproveche ese valor para hacer algo.

Es importante que recuerden que esto es en parte una simplificación de la realidad, posiblemente en un escenario mas real el que pide el valor mediante GET sea para hacer algo (imprimir una factura por ejemplo) pero que al motor de Redis (lo que se intenta simular en el TP) le importa nada para que van a usar el dato.

**Comment by FedericoJoel** [comment]
Donde da esta explicacion de retornar el valor? Estoy leyendo el tp y no encuentro referencias a esto, siempre habla del bloqueo del valor.
Seria una errata?

**Comment by FedericoJoel** [comment]
Perdon el doble post, estoy leyendo algunos issues en donde explican que el GET nunca llegaria a la instancia por que al solo usarse para bloquear el valor, el coordinador puede atenderlo.
Como quedariamos con esto?

**Comment by iago64** [comment]
@FedericoJoel Revisando la ultima errata (como me permite el 3g porque en la vpn del laburo no tengo acceso a nada) veo que eso cambió de la versión original, con lo cual, queda la version que tenes: no llegamos a la instancia para el GET.

![image](https://user-images.githubusercontent.com/1622109/39718528-ee99343c-520c-11e8-92a9-f61928b08bdd.png)

Nuevamente mil disculpas por los malos entendidos (y por el internet de mierda que tengo en el laburo que bloquea github pero no youtube o facebook :@)
Saludos.-

**Comment by FedericoJoel** [comment]
No pasa nada, dejo este link en donde adriano aclaro este tema para que quede claro por cualquiera que lo lea.

https://github.com/sisoputnfrba/foro/issues/1004

**Comment by ricardoAguirreSanchez** [comment]
Buenas, 
Aun no quedo claro, puede que yo lo interprete mal pero cuando hablan de si **existe** o no la clave yo lo pensé como si existe dentro del coordinador dado que el coordinador le cree una tabla **(INSTANCIA,CLAVE)**, porque? bueno porque si recibo un **SET CLAVE VALOR** tengo que saber si la clave **EXISTE** para aplicar el algoritmo de distribución o no, ya que si **EXISTE** entonces uso directamente al instancia que maneja esa clave y no haría falta volver a aplicar el algoritmo y elegir otra instancia, bajo este contexto no me queda claro como se puede hacer un GET sin hacer SET antes.

**Comment by iago64** [comment]
Buenas!
Disculpen la falta de respuestas pero con este issue encontramos algunas cosas que no estaban del todo claras (y algunas otras que se contradecian un poco) en el enunciado asi que estamos trabajando en una errata para aclarar todo y eliminar las contradicciones.

Nuevamente les pido disculpas por los malos entendidos.
Saludos.-

**Comment by natoszme** [comment]
Buenas! En [este](https://github.com/sisoputnfrba/foro/issues/1061#issuecomment-387150714) comentario de más arriba dice que si la clave no existe en caso de GET, se aborta al esi. Pero en [este](https://github.com/sisoputnfrba/foro/issues/1061#issuecomment-387162475) otro dice que no se pasa por la instancia, y es la instancia la que sabe si existe la clave. Cuál es la posta?
Nosotros por ejemplo tenemos las claves de las instancias en el coordinador, por lo cual no pasaríamos literalmente por la instancia, pero esto no deja de ser confuso. 
Gracias!

**Comment by natoszme** [comment]
Dale @iago64  gracias!

**Comment by iago64** [comment]
@FedericoJoel como dueño original del issue, queda algo mas pendiente de esto o podemos cerrar el issue?
