### ISSUE TITLE
cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by GabrielRuderman** [sisoputnfrba/foro#1062]
Buenas, una consulta! Nos compila perfecto el Build All en Eclipse, y cuando le damos Run al coordinador funciona, pero nos tira que no puede encontrar el archivo de configuracion.. Debuggeando, vemos que el path llega bien, e incluso -antes cuando podiamos compilar por consola- funcionaba (encontraba el archivo config) y en Eclipse no.
Despues de muchos problemas con una biblioteca interna donde tuvimos que llegar a vaciar el repo global para empezar de 0, sucede que en Eclipse, como les decia, lo corre pero no termina de funcionar la ruta de archivo, y en consola nos tira esto:

![image](https://user-images.githubusercontent.com/26581497/39667504-41be251c-508e-11e8-8bbb-1e19cafa454e.png)

Alguna idea?
Gracias

**Comment by iago64** [comment]
Buenas buenas!

Veo que no están configurando la variable de entorno de LD_LIBRARY_PATH (si, ya se, en eclipse eso se soluciona tocando las run configurations, pero eso no pasa a la consola).

Para hacerlo desde consola tienen que hacer:

`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<Path a la carpeta donde tienen el .so>`

El Path a la carpeta donde tienen el .so es lo mismo mismo que tienen en las run configurations de eclipse :)

Saludos.-

**Comment by GabrielRuderman** [comment]
Esta es la idea? Copie tal cual el path que esta en run configurations del Eclipse, pero tampoco funciona.

![image](https://user-images.githubusercontent.com/26581497/39668691-08403eb6-50ab-11e8-92b9-e7e06ccd0fc2.png)

De paso mando un echo $LD_LIBRARY_PATH en consola, tal vez aporte algo.

**Comment by GabrielRuderman** [comment]
Solucionado.
Le mande make clean y luego make y pareciera funcionar, espero que de forma definitiva.

Gracias.
