### ISSUE TITLE
Consola Planificador y threads

### ISSUE THREAD

**Issue by juanimoli** [sisoputnfrba/foro#1063]
Buenas! Como va?

Nosotros actualmente para la implementación estamos usando la lib readline, separando en dos threads la consola de el manejo de conexiones del Planificador. El problema que tenemos es que a la hora de printear algo, se printea a continuación del prompt. Algo así:
```
planificador>
planificador> Se conectó un ESI. Socket numero N.
```
Pero lo que nosotros estamos buscando, para que no quede manchado el input es algo así:
```
planificador>
Se conectó un ESI. Socket numero N. 
planificador> 
```

Es decir, que con cada print que hagamos, corte el readline, printee y luego que vuelva a parecer el readline. Intentamos usar nuestra propia función de print, wrappeandolo con unos flags de readline que encontramos en su documentación, pero no funcionó. 

Pensamos en semáforos también, pero lo vemos muy overkill para la problemática. 

Gracias!

**Comment by tferraro** [comment]
Que tul con esto @juanimoli, te sirvió el comentario? Si es así, se puede cerrar el issue?

**Comment by iago64** [comment]
Cerramos el isue ante la falta de respuesta.

**Comment by juanimoli** [comment]
@tferraro @iago64 Me colgue en responder ya que segui y no lo vi como prioritario. Lei la respuesta y lo que hicimos fue que en vez de printear, loguee para ahorrarnos este problema. Lo del wrapper es lo que habiamos hecho pero no logramos hacerlo funcionar. Utilizamos los flags de readline pero no hubo caso. Gracias!
