### ISSUE TITLE
Comando DUMP

### ISSUE THREAD

**Issue by cheja** [sisoputnfrba/foro#1064]
Hola, como va?

En la charla de presentación del TP me dijeron que el comando DUMP almacenaba con un archivo por **entrada**, pero el enunciado dice que es uno por **clave**. Me gustaría saber cual de las dos es.

Gracias!

**Comment by iago64** [comment]
Buenas buenas!

Perdon por la demora, en el DUMP, el archivo va a tener como nombre la clave y como contenido el valor, independientemente de si ocupa 1 o más entradas.

Saludos.-

**Comment by iago64** [comment]
@cheja quedo claro el tema? podemos cerrar el issue?

**Comment by cheja** [comment]
@iago64 Perfecto!
