### ISSUE TITLE
Consulta: Comando "status"

### ISSUE THREAD

**Issue by FrancoEsposta** [sisoputnfrba/foro#1065]
Buenas!
No estaríamos entendiendo lo que se supone que haga el comando status de la consola del planificador, la información que hay en el enunciado en la parte de los comandos nos resulta medio escasa. Además ¿Para que se le pasa una clave al comando?. Si dice que quiere información sobre las instancias ¿Qué información es la que quiere sobre las mismas?

Desde ya muchas gracias.
Saludos!

**Comment by sebastianciancio** [comment]
Mi interpretación sobre el comando STATUS es saber que instancia tiene guardada una determinada KEY, por eso el parámetro. Por lo tanto, el Planificador debiera pedirte al Coordinador que le indique cual es la Instancia que persistió esa KEY. Depende en el momento que hagas la consulta, podría ser que esa KEY ya tenga Instancia o podría ser que nunca fue persistida. 

Así lo implementamos nosotros.

**Comment by LeaTex** [comment]
Entiendo que el enunciado está usando los términos "clave" y "recurso" para referirse a lo mismo.

- listar _recurso_: Lista los procesos encolados esperando al recurso.
- status _clave_: Debido a que para la correcta coordinación de las sentencias de acuerdo a los algoritmos de distribución se requiere de cierta información sobre las instancias del sistema.

¿Qué información mostrar? La que se te ocurra. Podés mostrar si existe o no, a qué Instancia pertenece, qué valor tiene (si lo tiene), si está tomado o no, qué ESI lo tiene tomado, etc.

**Comment by iago64** [comment]
Buenas buenas!

Por este tema estamos terminando de cerrar la errata para que el comando status tenga un objetivo y una salida predefinidas.

Mil disculpas por los malos entendidos y los inconvenientes.
Saludos.-

**Comment by FrancoEsposta** [comment]
Ahhh excelente! Espero a la próxima actualización de la errata entonces. Muchas gracias por las respuestas.

Saludos!
Franco
