### ISSUE TITLE
LRU y GET

### ISSUE THREAD

**Issue by Mszlajen** [sisoputnfrba/foro#1066]
Buenas, teniamos de si la operación cuenta como uso de una clave para el algoritmo de LRU dado que el enunciado dice:
>Es importante destacar que la operación GET no genera ningún registro dentro de la instancia, si no que solo modifica el estado de bloqueos y desbloqueos en el planificador.  

Gracias.

**Comment by afilgueira** [comment]
Buenas, lo vamos a aclarar en la próxima errata. El GET no pasa por la instancia, así que no cuenta. Saludos!

**Comment by afilgueira** [comment]
@Mszlajen quedó claro con la errata? Saludos!
