### ISSUE TITLE
Conexión ESI-Planificador, ESI-Instancia

### ISSUE THREAD

**Issue by rociochipian** [sisoputnfrba/foro#1068]
Hola! Con mi grupo tenemos varias preguntas:

1. Nosotros planteamos lo siguiente: cuando un ESI termina de ejecutar una instrucción, informa al Planificador el resultado de su ejecución, ya sea por éxito o por fallo, y recién en ese momento el Planificador actualiza la información que él posee del ESI, y le dice que ejecute otra instrucción, lo bloquea, etc. Es esto correcto? El ESI conoce su estado? O el Planificador, al recibir la solicitud de una clave bloqueada, ya debería bloquear al ESI?

2. El enunciado dice: "Por otro lado, en el caso de que el ESI haga una operación de GET sobre un recurso libre, no deberá moverse del estado de ejecución ni ser re-planificado"
Creo que es medio obvio, pero esto quiere decir que cuando un ESI hace un GET, entonces no puede ser desalojado/bloqueado hasta que termine de ejecutar todas sus intrucciones (o se bloquee por no poder acceder a un recurso)?

3. Para calcular el tiempo que estuvo esperando un ESI para ejecutar, tengo que considerar el tiempo que estuvo bloqueado + el tiempo que estuvo en la cola de Ready, o solamente el tiempo que estuvo en la cola de Ready?

4. Si a una Instancia se le pide hacer un SET de una clave, pero el contenido del SET excede el tamaño de la entrada asociada a esa clave, la Instancia sigue escribiendo en la entrada siguiente, no? Y por otro lado, si se hace un SET sobre una clave que ya había sido escrita, se continúa escribiendo en el espacio libre, o se sobrescribe de cero?

Muchas gracias!!

**Comment by afilgueira** [comment]
Hola,

1 - Les recomendamos que el ESI sea agnóstico de su estado. Simplemente debería recibir la instrucción "ejecutá vos" y ejecutar. Además tendría que poder saber que necesita reiniciar una instrucción (cuando vuelve de un bloqueo), pero no mucho más. Esto les va a hacer más sencillas las cosas a futuro, pero es una recomendación nomás.

2 - No no, significa que el simple hecho de "avisar" que hiciste un GET no te devuelve a la cola de listos. Va a listos si lo desalojan y a bloqueados si (sic) se bloquea . En algún momento había surgido una duda similar y de ahí que lo aclaremos.

3 - El tiempo de espera es sólo el de ready, y el actual. No importan "esperas anteriores".

4 - Sí, usás la entrada siguiente (si podés... si no, hay algo que hacer :wink:). El set pisa los valores.

Saludos!

**Comment by rociochipian** [comment]
Gracias!!!
Te hago otra pregunta acerca del punto 1 entonces:
No nos queda claro qué es lo que le diría el ESI al Planificador después de ejecutar una instrucción. Si puede ejecutarla bien, le avisa al Planificador, si no puede porque una Entrada estaba rota, le avisa eso al Planificador. Y si no pudo ejecutar porque la clave estaba bloqueada, guarda la instrucción y le avisa al Planificador para que replanifique, o el Planificador replanifica en el momento que le piden la clave bloqueando al ESI, y le avisa él al ESI para que guarde la instrucción?
Y relacionado a esto, entonces quien debe almacenar las últimas ráfagas, retardos, etc de los ESIS es el Planificador, y no el ESI?

**Comment by afilgueira** [comment]
Buenas, parte de la pregunta que me hacés es algo que dejamos sin definir, para que cada grupo lo arme como considere. Mi consejo es que lo hagan de forma "uniforme", evitando casos excepcionales.

Ej: el ESI ejecuta y siempre informa sobre el resultado*. El planificador siempre recibe un resultado y pone un ESI a ejecutar (podría ser el mismo). 

Sobre las tablas, en líneas generales fíjate quién necesita esa info y decidan donde ponerla para evitar duplicados y cosas así.

Saludos!
* Depende como lo implementen el ESI podría o no saber que la clave a la que le haces un GET lo bloqueo. Piensen un par de variantes a ver cuál les cierra más y cualquier duda arrimense!

**Comment by rociochipian** [comment]
Muchas gracias!!
