### ISSUE TITLE
Identificación de cada Proceso

### ISSUE THREAD

**Issue by sebastianciancio** [sisoputnfrba/foro#1069]
Prefiero consultar ahora antes de que sea tarde...

Nosotros estamos ejecutando los procesos ESI de la forma: ./esi <NOMBRE_PROCESO> <PATH_SCRIPT> y de esta forma identificamos a los procesos por su nombre.

La pregunta es la siguiente:

Esta bien que el ESI identifique a los procesos o el Planificador debería identificar univocamente a cada proceso, de forma tal que exitan dos o más procesos con el mismo nombre pero distinto ID?

**Comment by iago64** [comment]
Buenas buenas!!

@sebastianciancio Esta perfecto, pueden hacerlo sin ningun inconveniente, lo importante es que el path del script lo reciban por parametro, despues si quieren ponerle un Nombre, ID, o lo que sea por archivo de Config o mejor aun y mas dinámico por parametro esta perfecto.

@LeaTex Yo personalmente le veo sentido si lo que hacen es definir el ID del ESI por fuera de la app en lugar de hacerlo internamente en el handshake con el Coordinador y con el Planificador. 
Aun asi, identificar un ESI tenes que poder hacerlo porque en algún momento puede ser que te tiremos en la consola del planificador un kill <ID_ESI>

Saludos.-

**Comment by sebastianciancio** [comment]
Muchas gracias por la respuesta

**Comment by iago64** [comment]
Mas que un usuario malicioso, consideraría un posible error humano (lo cual **no** vamos a ser tan malas personas de probarlo) :)
