### ISSUE TITLE
Consultas sobre estimación planificador

### ISSUE THREAD

**Issue by FrancoVentrice** [sisoputnfrba/foro#1070]
Buenas, dejo dos dudas que me surgieron:

1. Me surgió de haberlo leído en un issue, pero tal vez lo entendí mal y quiero reconfirmar: Si estamos estimando en SJF con desalojo, supongamos que el ESI A tiene 8 de estimación. Va ejecutando y se va restando de a una sentencia a esa estimación. Cuando el ESI A tiene 4, entra a la cola de listos un ESI con estimacion 3, lo cual desaloja al ESI A. El ESI A no debe ser reestimado, sino que ese 4 tiene que valer como su estimación hasta que se bloquee o finalice?

2. El algoritmo HRRN va con desalojo?

**Comment by FrancoVentrice** [comment]
Agrego unas consultas más:

3. Si un ESI libera una clave, y uno de los ESIs bloqueados por esa clave había sido bloqueado por consola, ¿se libera también?

4. Siguiendo el punto anterior, si un ESI libera una clave, se liberan todos los ESIs que la estaban esperando, ¿no?
Hago esta pregunta porque me pareció haber leído algo así en el enunciado, pero no lo volví a encontrar, así que tal vez lo soñé (ieeeeeeeee (8))

**Comment by afilgueira** [comment]
Buenas

1 - Si, le quedaría 4. La estimación completa se hace cuando "arrancas" la ráfaga nomás
2 - No! Te dejo el ejercicio de pensar que pasaría si querés hacerlo con desalojo (quién dice, capaz es una buena pregunta de parcial :grin: )
3 - A fines prácticos nunca va a pasar. Los ESI van a estar bien hechos, así que cada uno va a hacer un GET antes de un STORE. Si les sirve separarlos para evitar casos borde, está perfecto.
4 - No. Sólo el primero, como si fuera un semáforo (suena superlógico, si?)

**Comment by FrancoVentrice** [comment]
Mil gracias!
