### ISSUE TITLE
Nombre de las Instancias

### ISSUE THREAD

**Issue by BelenTripodi** [sisoputnfrba/foro#1071]
Hola! Quisiera saber como cambian de nombre las instancias, es decir, en la config.

**Comment by iago64** [comment]
Buenas buenas!
@BelenTripodi La respuesta de @LeaTex te resulto útil?

Algo importante es que el nombre de la instancia no va a cambiar en tiempo de ejecución, es decir, la instancia inicia y muere como por ej: INSTANCIA1

Saludos.-

**Comment by iago64** [comment]
Por inactividad se cierra el issue.
