### ISSUE TITLE
Problema con función "parse" del parsi

### ISSUE THREAD

**Issue by Phiiliip** [sisoputnfrba/foro#1072]
Buenas tardes, instale las librerías del parsi como estaba en el tutorial sin ningún problema, el eclipse me lo reconoció y no tuve inconvenientes.

El problema fue a la hora de hacer el MakeFile. Ya que cuando hago "make all" me tira el siguiente error:
"undefined reference to 'parse'" y ya probe haciendo varias cosas que vi en otros issues y foros y no hay forma de que pueda resolver este conflicto.

Saludos

**Comment by jazcarate** [comment]
Estás haciendo vos tu propio `Makefile`? estas linekando la biblioteca? Ese error es en momento de compilación o de ejecución?

**Comment by Phiiliip** [comment]
Hola:

Yo agregué la biblioteca de parsi igual que como la de commons. Yendo a properties del proyecto -> gcc linker, etc. y agregándolos.

El eclipse me reconoce bien las funciones y no me tira ningún error.

El problema surge cuando yo tiro el make all, me tira 1 o 2 warning y antes de finalizar me muestra :

In function "FuncionMia" :
"Undefined reference to 'parse'"
ld returned 1 exit status

y corta el MakeFile

Saludos

**Comment by Phiiliip** [comment]
Buenas, en el branch "esi" esta todo lo que tengo hecho hasta el momento.

Saludos

**Comment by tferraro** [comment]
Holis :wave:

Mirando eso que decís, revisando el makefile encontré esta línea:
`LIBS=-lcommons -lreadline -lcrypto`

...yyy no veo linkeado el parsi :slightly_smiling_face:

**Comment by Phiiliip** [comment]
Estoy teniendo un problema entonces, porque voy a gcc linker -> Agrego la librería en el recuadro de arriba y por las dudas también agrego el directorio en la parte de abajo, pero sigue sin reconocérmela y el Makefile tira el mismo error.

Hay alguna otra forma de decirle al MakeFile que busque en x directorio lo que necesita?

saludos

**Comment by Phiiliip** [comment]
Disculpen, ya entendí el error, tenia que agregar manualmente la linea (-lparsi) al makefile.

Cierro el issue
