### ISSUE TITLE
Consulta -> aplicar formula de estimacion

### ISSUE THREAD

**Issue by ricardoAguirreSanchez** [sisoputnfrba/foro#1073]
Buenas, usando este issue como referencia (Consultas sobre estimación planificador #1070)

1.- Se menciona que solo se estima al arrancar la ráfaga no cuando vuelve a ejecutar si fue desalojado, esto me llevará a tener en mí lista de ready esis que ya tienen una estimación dada (esis que fueron desalojados) y esis a los cuales tengo que estimar recién (esis nuevos o que se desbloquearon), osea tengo que poder diferenciar entre ambos esis cuando quiera saber las prioridades de todos los que están en mí lista de ready?

2.Estimo solo cuando "arranca la ráfaga", es decir cuando llega uno nuevo o cuando viene de bloqueado, no?

Saludos.

**Comment by afilgueira** [comment]
1 - Nunca tenes que tener ESIs en ready sin estimar. Antes de meterlos a ready, estimalos.
2 - La estimación es cuando entra a ready desde nuevo o bloqueado. Cuando vuelve de ejecución, simplemente le restas lo que ejecuto (como el ejemplo del issue que linkeaste).

Saludos!

**Comment by afilgueira** [comment]
HRRN usa el *response ratio* (que no es una estimación, es un coeficiente que te da la prioridad). De ahí la diferencia entre lo que menciono yo y lo que decís vos. En todos los casos tenés que estimar la ráfaga como comentaba arriba. Con HRRN además calculas el RR de todos los ESI cuando tenés que poner uno a ejecutar. Para fortuna de uds, es sólo sin desalojo :sunglasses:.

Saludos!

**Comment by ricardoAguirreSanchez** [comment]
Entonces cuando sea HRRN lo que hago es usar la estimación que ya tiene (S) y me fijo el tiempo que estuvo en ready (w)  para poder calcular el RR ?

**Comment by afilgueira** [comment]
Claro, no tenés otra forma si no de saber cuanto vale S -> lo estimás.

Saludos!

**Comment by ricardoAguirreSanchez** [comment]
Gracias.
