### ISSUE TITLE
 [AYUDA] - Definiciones Instancia

### ISSUE THREAD

**Issue by AlexFalconR** [sisoputnfrba/foro#1074]
buen dia, como estan?

Estoy con algunas dudas hace una semana que me impiden comenzar a codear la administracion de memoria de la instancia.
Ya levante algunos thread y me acerque a hablar con ayudantes pero parece que no esta totalmente definido cual va a ser el funcionamiento.}
Les pido porfavor si me pueden pegar una mano.

1) Utilizacion del GET - Todavia no se entiende muy bien cual va a ser la funcion, en principio sabemos que se utiliza para bloquear recursos y nunca llega a la instancia. Si asi fuese, puedo hacer un SET sin primero hacer un GET para bloquear el recurso? y si no puedo, como hago un GET primero si no tengo la clave definida por que es el SET quien la define?

2) Con respecto a la estructura administrativa para la memoria, el tp habla de tener guardado para cada clave cual es la primer entrada y la longitud del valor. (un dictionary con un struct en el valor)
Esto trae aparejado que yo tendria que usar un bitmap para poder ver que entradas tengo libres, y ni hablar al momento de hacer comprimir la memoria, estas estructuras volverian el algoritmo dificil ya que tengo que inferir que bloques ocupa cada clave por su longitud y con el bitmap y revisando cuales estan libres.

Que pasa si armo una estrcutura Array de structs que tenga 1 registro para cada entrada (sabemos que la cantidad es estatica) y en este struct guardamos para cada una de las entradas cual es la clave con la cual esta asociada(de que clave esta conteniendo el valor)

3) Y muy relacionado a las consultas anteriores.
Si en ningun lugar del TP hace falta LEER un valor que este almacenado en la instancia, para que guardo la longitud del valor almacenado? es un dato de color si utilizo la estructura simil tabla de paginas invertida sugerida en el punto (2)

Espero su pronta respuesta para poder aclarar estos temas

Abrazo.

**Comment by LeaTex** [comment]
Otra cosa, fijate en el issue 1061 que algunas cosas más aclara: https://github.com/sisoputnfrba/foro/issues/1061

**Comment by FedericoJoel** [comment]
Si, tanto la pregunta esta como ese issue son mios, hoy no podia hacer este post por que me restringia un proxy y le pedi a mi compañero que lo suba.

La pregunta 1 fue respondida con la errata que subieron.

Con respecto a lo de las estrcuturas, tenes alguna opinion que me puedas dar? tampoco me quiero meter en camisa de 11 varas

**Comment by LeaTex** [comment]
Te diría que evites algo fijo como un array, porque el tamaño dependerá de lo que diga el coordinar (y es parametrizable por configuración, así que podría variar en cada ejecución).

También en el enunciado hay una nota al pié:
_^12: Para más información, investigar sobre el comando malloc()._

En mi grupo apuntamos a manejar todo con memoria dinámica (listas) que no debería ser muy complicado usando las librerías que nos da la cátedra.
También consideren qué datos van a necesitar, por más que no lo diga el enunciado explícitamente. Por ejemplo para algoritmo de reemplazo LRU vas a tener que guardarte algún dato de cuándo fue accedida cada clave.

Volviendo al tema del orden de ejecución, fijate el ejemplo que está acá: https://sisoputnfrba.gitbook.io/re-distinto/anexo-ii-lenguaje-secuencias-de-ejecucion

```
# Se crea la clave deportes:futbol:messi en la tabla de claves del coordinador
GET deportes:futbol:messi
​
# Se crea finalmente la clave deportes:futbol:messi en la instancia y se graba el valor Lionel Messi
SET deportes:futbol:messi Lionel Messi
```

Tanto con GET como con SET el comentario dice _se crea_.
Podrías suponer que al hacer el GET, si el coordinar la tiene, avisa al planificador para que la bloquee. Si no la tiene, le avisa a la instancia para que la cree, y luego al planificador para el bloqueo.

**Comment by iago64** [comment]
Buenas buenas!
Vamos en orden con las preguntas.

1.- Agregamos un [anexo de secuencias de ejecución](https://sisoputnfrba.gitbook.io/re-distinto/anexo-ii-lenguaje-secuencias-de-ejecucion) con el objetivo de entender algunas cosas por ej que es obligatorio hacer un GET antes de un SET o un STORE. La idea es que siempre tengan que hacer un GET y el GET les cree la entrada en la tabla de claves del coordinador, después cuando hagan el SET recién le asignen el valor y el tamaño de la clave. En los ejemplos 2 y 3 están los casos si no hacen un GET antes de hacer un SET o un STORE.

2.- Es un tema de como lo planteen uds, pero si, la idea es que la instancia al momento de compactar tenga cierta dificultad la lógica de ir moviendo los pedacitos de memoria (los valores) y tengan que ir jugando con los punteros para hacerlo.

3.- El valor lo vas a leer al momento de que hagas el dump y despues busques en el FS los archivos con el nombre de la clave y en el contenido el valor de la misma.

Saludos.-

**Comment by iago64** [comment]
Buenas @AlexFalconR Que tal? Quedo resuelta tu duda? podemos cerrar el issue?

**Comment by iago64** [comment]
Damos por resuelto el issue, cualquier cosa lo vuelven a abrir :)
