### ISSUE TITLE
Instancias y Algoritmo de Reemplazo de Entradas

### ISSUE THREAD

**Issue by sebastianciancio** [sisoputnfrba/foro#1075]
Supongamos que cada Instancia tiene asignado 10 entradas de X tamaño.

A lo largo de la ejecución de Procesos, irá guardando en estás entradas los valores de las key recibidas. Si pipo netos que los tamaños son inferiores al tamaño de la entrada, entonces podrán guardar 10 valores. A su vez, esos 10 valores fueron persistidos con el dump en archivos planos con el punto de montaje.

La consulta es:

Cuando se ejecute la 11 va key diferente, entonces entra en juego el Algoritmo de Reemplazo. Elijirá un candidato y lo reemplazará por el nuevo. La key reemplazada debería borrarse de los archivos planos para que al volver a iniciar una Instancia podamos reconocer cuales son las key que posee y reconstruir la Tabla de Entradas? 

Espero se haya entendido

**Comment by LeaTex** [comment]
Buena pregunta. Agrego otra:

Si tenemos varias instancias corriendo en la misma máquina y que apuntan el mismo punto de montaje, ¿cómo sabe cada una cuáles claves levantar?

**Comment by afilgueira** [comment]
- Si, debería borrarse.

- No van a apuntar al mismo punto. Mínimamente van a ser directorios diferentes.

Saludos!

**Comment by sebastianciancio** [comment]
Muchas gracias
