### ISSUE TITLE
[AYUDA] - Instancia - Definiciones

### ISSUE THREAD

**Issue by LucasBlanco** [sisoputnfrba/foro#1076]
buen dia, como estan?

Estoy con algunas dudas hace una semana que me impiden comenzar a codear la administracion de memoria de la instancia.
Ya levante algunos thread y me acerque a hablar con ayudantes pero parece que no esta totalmente definido cual va a ser el funcionamiento.}
Les pido porfavor si me pueden pegar una mano.

1) Utilizacion del GET - Todavia no se entiende muy bien cual va a ser la funcion, en principio sabemos que se utiliza para bloquear recursos y nunca llega a la instancia. Si asi fuese, puedo hacer un SET sin primero hacer un GET para bloquear el recurso? y si no puedo, como hago un GET primero si no tengo la clave definida por que es el SET quien la define?

2) Con respecto a la estructura administrativa para la memoria, el tp habla de tener guardado para cada clave cual es la primer entrada y la longitud del valor. (un dictionary con un struct en el valor)
Esto trae aparejado que yo tendria que usar un bitmap para poder ver que entradas tengo libres, y ni hablar al momento de hacer comprimir la memoria, estas estructuras volverian el algoritmo dificil ya que tengo que inferir que bloques ocupa cada clave por su longitud y con el bitmap y revisando cuales estan libres.

Que pasa si armo una estrcutura Array de structs que tenga 1 registro para cada entrada (sabemos que la cantidad es estatica) y en este struct guardamos para cada una de las entradas cual es la clave con la cual esta asociada(de que clave esta conteniendo el valor)

3) Y muy relacionado a las consultas anteriores.
Si en ningun lugar del TP hace falta LEER un valor que este almacenado en la instancia, para que guardo la longitud del valor almacenado? es un dato de color si utilizo la estructura simil tabla de paginas invertida sugerida en el punto (2)

Espero su pronta respuesta para poder aclarar estos temas

Abrazo.

**Comment by iago64** [comment]
Veo que este issue es duplicado del https://github.com/sisoputnfrba/foro/issues/1074, seguimos las dudas por aquel issue que ya tiene mensajes.

Saludos.-
