### ISSUE TITLE
¿Hay que distinguir claves bloqueadas por usuario o por ESI?

### ISSUE THREAD

**Issue by MelisaRodriguez** [sisoputnfrba/foro#1077]
Buenas! En la consola del planificador en la operación desbloquear clave, antes de la errata 2 decía: ". Solo se desbloqueará ESIs que fueron bloqueados con la consola. Si un ESI está bloqueado esperando un recurso, no podrá ser desbloqueado de esta forma". Ahora en desbloquear clave sacaron ese texto. ¿Eso quiere decir que nos es indistinto si hay las claves bloqueadas por usuario o por ESI? ¿Todos los bloqueados se pueden desbloquear por consola?
Desde ya, muchas gracias.

**Comment by iago64** [comment]
Buenas buenas!

Eso era así hasta antes de la errata, ahora les simplificamos eso para que no tengan que estar haciendo colas separadas (o tengan que estar buscando con algún flag) y ahora el desbloquear desbloquea el primero de la cola de bloqueados independientemente de como fue que se bloquearon.

Saludos.-

**Comment by iago64** [comment]
Buenas @ltrinidad si ya lo implementaron y les funciona no hay drama, lo unico que si por favor tengan en cuenta 2 cositas:

1.- Tengan logueado bien lindo que no pueden desbloquear el ESI porque no fue bloqueado por consola
2.- Aclárenlo en cuando estén evaluandoles el TP (Así lo tiene en cuenta el ayudante que los evalúe)

Saludos.-

**Comment by ltrinidad** [comment]
Excelente, gracias! 👍

**Comment by MelisaRodriguez** [comment]
Hola, muchas gracias por las respuestas
