### ISSUE TITLE
Comando Bloquear de la Consola

### ISSUE THREAD

**Issue by sebastianciancio** [sisoputnfrba/foro#1078]
Según enunciado, se entiende que este comando tiene 2 parámetros : CLAVE_RECURSO y ID_PROCESO
Por lo tanto, la invocación BLOQUEAR MATERIA1 ESI1, implica:

1. Si la key MATERIA1, no estaba previamente bloqueada por ningún proceso (previo GET), entonces se bloquea dicha clave y no se lo asocia a ningún proceso  (similar a las claves bloqueadas por archivo de configuración)
2. Si la key MATERIA1 ya estaba bloqueada por otro proceso, no se bloquea la key por ya estarlo.
3. El Proceso ESI1 se bloqueará y se lo carga en la Lista de Procesos que solicitan key bloqueadas.

Es correcto el análisis?

**Comment by iago64** [comment]
Buenas buenas!
El análisis esta bien encaminado, pero se reduce a 2 opciones:
1.- Si la key MATERIA1 no estaba bloqueada, la bloqueas para el ESI1
2.- Si la key MATERIA1 si estaba bloqueada (es decir que ya alguien te hizo un GET antes), solamente agregas a la cola de bloqueados el ESI1

Saludos.-

**Comment by sebastianciancio** [comment]
Muchas gracias
