### ISSUE TITLE
STORE sin SET previo

### ISSUE THREAD

**Issue by Mszlajen** [sisoputnfrba/foro#1079]
En el enunciado dice que el correcto proceso de vida de una clave es GET-SET (1 o más)-STORE pero que pasa si un ESI tiene codigo erroneo que hace solo GET-STORE? Se persiste la clave con un archivo vacio (dado que la clave existe pero no se le asigno valor), se considera error, o comportamiento desconocido del que no nos tenemos que preocupar?

**Comment by iago64** [comment]
Buenas buenas!
Efectivamente, persistís la clave pero el archivo va a estar vacío.

Saludos.-
