### ISSUE TITLE
Bloqueos y des conexión de instancia

### ISSUE THREAD

**Issue by gastoncastineira** [sisoputnfrba/foro#1080]
¡Buenas!

Traigo una duda por un pedazo del planificador en esta nueva errata.
En el caso triste de que un proceso quiera hacer una operación sobre una instancia inaccesible, en la errata anterior lo que debía hacer el planificador era encolar ese ESI en la lista de bloqueados por esa clave. Ahora, en esta errata dice que el ESI "se abortará" y que los ESIs ya bloqueados por esa clave no se deben mover de su lugar. Pongo este ejemplo a ver si entiendo lo que quiere decir:

1. ESI0 hace GET sobre recurso tomado y entra a la cola de bloqueados de esa clave.
2. ESI1 hace GET sobre el mismo recurso tomado y entra a la cola de bloqueados de la misma clave.
3. Se desconecta la instancia donde estaba esa clave.
4. ESI2 hace GET sobre la misma clave. Se determina que la instancia no está y el planificador lo elimina del sistema (aborta). Arbitrariamente digamos que le avisa también a ese ESI que no va más y este hará un Exit() adentro. Mientras, ESI0 y ESI1 todavía existen en el sistema, bloqueados en esa clave.

¿Esto es así? si esto es así me lleva a otra duda. ¿Si la instancia está caída qué debería pasar cuando el proceso que tenía esa clave intente hacer un STORE? En realidad sé la respuesta. Es un error de clave inaccesible, que lleva a que el ESI aborte su ejecución. Mi duda es cómo interactúa eso con toda mi duda de arriba.
Mi idea es que ese se va a romper, va a liberar su clave y los procesos que estaban bloqueados por dicha clave volverán a listos y sufrirán el mismo destino que ESI2 eventualmente (a menos que de casualidad vuelva a la vida la instancia desconectada antes que estos ejecuten). Dicho así hasta parece más fácil abortarlos junto ESI2, por eso pregunto pido que me digan si estoy entendiendo bien.

Poco largo y complicado de explicar. Espero haberme hecho entender.

**Comment by ricardoAguirreSanchez** [comment]
Buenas agrego una duda, las instancias no eran indiferentes ante operaciones GET ?

Saludos

**Comment by iago64** [comment]
Buenas buenas!

@gastoncastineira  Se van a ir bloqueando el ESI0, el ESI1 y el ESI2 aborta, en cuanto el ESI5 (suponiendo que este tomo la clave originalmente) quiera hacer un SET o un STORE, si la instancia no se reconecto, debería abortar y desbloquear las demás instancias, que eventualmente si les toca ejecutar va a ir abortando a menos que se reconecte la instancia. 
La idea de no abortarlos todos ni bien falla el primero, es porque puede darse el caso de que quieras hacer el GET con el ESI2 pero justo despues se reconecte la instancia y todo siga su curso sin el menor problema.

@ricardoAguirreSanchez si, el GET no hace nada con la instancia directamente, pero tenes que poder asegurarte que si la clave existe la puedas tomar, en esa comprobación deberías darte cuenta que la instancia esta desconectada.
Si la clave no existe es mas simple porque la derivas la asignación a otra instancia mediante el algoritmo de distribución

Saludos.-

**Comment by ricardoAguirreSanchez** [comment]
@iago64 Gracias!.

**Comment by ricardoAguirreSanchez** [comment]
Quiero plantear este flujo:
(Empezando sin claves en el sistema)
1.-Esi1 hace GET jugador
Como no tengo registro k exista esta clave la creo y se lo asignó a ese Esi1
2.- Esi1 hace SET jugador persona, aplicó el algoritmo porque no tengo esa clave en ninguna instancia, se lo doy a la instancia elegida (instancia 1) y hace lo q corresponda.
3.- Esi1 hace Store jugador, con lo cual si bien este eso deja de tener la clave, sigo teniendo en mí registro que la instancia1 tiene la clave jugador.
4.- Llega ESI 2 que pido GET jugador, como jugador es una clave que existe en el sistema, lo que hago es fijarme si la instancia 1 está conectada para poder recién darle el recurso a este ESI 2 ? O está verificacion se hace solo si ESI2 pide un SET jugador animal?

(Esto porque lo pregunto? Bueno porque el algoritmo de distribución es para elegir instancias y asignarles claves cuando recibo operaciones SET )

**Comment by natoszme** [comment]
Buenas! Para mi si la clave no existe (y según la errata v2), al hacer un get la clave se crea en la instancia (ahora si se pasa por ella en caso de get, antes no era así). Para hacer un set, tiene que estar la clave tomada por quién desea setear el valor. Eso entendí yo!

**Comment by ricardoAguirreSanchez** [comment]
Se crea en la instancia al hacer un get? Ah eso lo cambiaría todo.

**Comment by afilgueira** [comment]
No no, el ejemplo 1 lo dice claro: https://sisoputnfrba.gitbook.io/re-distinto/anexo-ii-lenguaje-secuencias-de-ejecucion

Línea 4, es un SET: `# Se crea finalmente la clave deportes:futbol:messi en la instancia y se graba el valor Lionel Messi`

Saludos

**Comment by ricardoAguirreSanchez** [comment]
Justamente, solo el get crea la clave en el coordinador pero para que la clave exista en la instancia es la operación SET

**Comment by natoszme** [comment]
10 puntos, mala mía. Gracias!

**Comment by iago64** [comment]
@natoszme Si, como la clave ya existía en el sistema, el ESI tiene que abortar, porque estarias queriendo tomar algo que es inaccesible en el sistema.

**Comment by natoszme** [comment]
Gracias!

**Comment by iago64** [comment]
@gastoncastineira La consulta esta resuelta? podemos cerrar el issue?

**Comment by iago64** [comment]
Como no hubo respuesta, cerramos el issue y si hace falta lo reabren :)
