### ISSUE TITLE
Cuando disparar el ALGORITMO DE DISTRIBUCION

### ISSUE THREAD

**Issue by ricardoAguirreSanchez** [sisoputnfrba/foro#1082]
Buenas,
Una consulta, anteriormente se dijo que el algoritmo de distribución se dispara ante operaciones SET (cuando no tengo registrado que alguna instancia tiene la clave), esto sigue así o cambio?

Saludos.

**Comment by afilgueira** [comment]
Sigue así. Lo único que se aclaró es cuándo se crea la clave en el coordinador (había un par de opiniones, definimos que sea en el GET). Saludos

**Comment by ricardoAguirreSanchez** [comment]
Gracias!

**Comment by ricardoAguirreSanchez** [comment]
Una consulta relacionada, dado que solo los set disparan el algoritmo de distribución, en el caso de tener la secuencia:
1.- GET AAA -> creo la clave AAA en el coordinador, aun no tiene ninguna instancia asociada
2.- STORE AAA -> como la clave existe en el coordinador no aborta por "error de clave no identificada", ahora al ver que esa clave no se encuentra en ninguna instancia y ademas q no dispara el algoritmo de distribución, que terminaría haciendo? 

Saludos

**Comment by natoszme** [comment]
Y yo hago otra, referenciada a la respuesta de @afilgueira de más arriba. Entre tanta confusión de quién hace cada cosa (y antes de leer este issue) habíamos implementado la elección del algoritmo de distribución al momento de hacer el get. Según nuestro modelo además, es necesario porque el coordinador tiene una lista de instancias y dentro de cada una de ellas, las claves que le corresponden. O sea que no podrías "guardar" la clave (como ahora se especifica) sin saber en qué instancia está. Cambiar esto para que se haga en el set implicaría un cambio enorme así que: estamos obligados a cambiarlo? Mil gracias!

**Comment by afilgueira** [comment]
@ricardoAguirreSanchez es similar al ejemplo 2: https://sisoputnfrba.gitbook.io/re-distinto/anexo-ii-lenguaje-secuencias-de-ejecucion#ejemplo-2-script-que-aborta-por-error-error-de-clave-no-identificada. En lineas generales (y así evitamos que pregunten los infinitos* casos), todo lo que no sea un ESI "correcto" o contemplado en los ejemplos, se aborta. Nuestras pruebas se van a enfocar en casos felices, y alguno de los mencionados para ver cómo manejan los errores.

@natoszme hasta donde entiendo, el get nunca hizo nada con la instancia (y siempre lo mantuvimos así más allá de las erratas), por lo que les recomiendo hablar con sus ayudantes y buscar alguna solución que no los complique tanto y que cumpla con lo de arriba. A ojo, se me ocurre que pueden tener una instancia "vacía" donde guarden las claves que no están aún en ningún lado, sin que esto los obligue a cambiar todo el diseño. Igualmente insisto, les recomiendo chequearlo con sus ayudantes, que están más al tanto del día a día del grupo.

Saludos!

* podrían ser finitos, pero no quiero calcular la complejidad ciclomática máxima de un ESI

**Comment by ricardoAguirreSanchez** [comment]
Genial!

**Comment by natoszme** [comment]
Buenas! Reavivo esto para preguntar lo siguente: si el planificador le dice al coordinador si una clave está tomada por el esi en cuestión (y no sólo si está tomada o no), podríamos prescindir de esa estructura que guarda las claves en el coordinador? Simplemente cuando un esi hace un get, el coordinador envía al planificador que la clave está bloqueada y la siguiente vez que ese esi quiera hacer set/store, me fijo si puede según lo que me responda el planificador (si está tomada por el o no). Qué opinas @afilgueira?
