### ISSUE TITLE
Consulta sobre "el dueño" de la tabla de claves

### ISSUE THREAD

**Issue by JuanQP** [sisoputnfrba/foro#1083]
Hola!

Tengo una duda sobre [este punto](https://github.com/sisoputnfrba/2018-1c-re-distinto/commit/0b44b1b7a327355b188161dd9e5d89ecca26ac3f#diff-875dd597ab2c854e98d353dc30a01ac4R13): dice que en una instrucción `GET` primero se *crea la clave en la tabla de **claves del coordinador***.

Sin embargo [acá](https://sisoputnfrba.gitbook.io/re-distinto/coordinador#bloqueos) dice que quién tiene una tabla de claves es **Planificador** (el que va a gestionar qué recursos están tomados y por quién). De hecho, busqué `claves` en la parte de Coordinador, y los únicos matchs que tienen que ver con claves hablan siempre de Planificador.

Había entendido que Planificador se encargaba de gestionar los recursos, y que era Coordinador quien se encargaba de distribuir el trabajo. Por eso primero me hizo ruido que aparezca ahí que Coordinador es quien tiene una tabla de claves, pero luego al consultar su apartado, me dí cuenta que en ningún momento dice que lo tiene.

No sé si fue una pifia y ahí tenía que ir "_tabla de claves de Planificador_" o si efectivamente tanto Planificador como Coordinador tienen una tabla de claves.

Busqué entre los issues pero no encontré esta consulta en específico, y esta duda surgió únicamente con [el último commit de la errata](https://github.com/sisoputnfrba/2018-1c-re-distinto/commit/0b44b1b7a327355b188161dd9e5d89ecca26ac3f), por eso vine a consultar

Muchas gracias!

**Comment by iago64** [comment]
Buenas buenas!
Muy buenas obsevaciones @FrancoVentrice efectivamente, se habla de a tabla de claves del planificador, pero esa tabla solamente tiene las claves que estan tomadas en el momento.
Por otro lado, el Coordinador, indefectiblemente tiene que tener alguna estructura (que no muy feliz mente es una tabla de claves tambien) para saber a que instancia tiene que ir por ejemplo a guardar un dato ante un SET o pedirle que haga un STORE y guarde el valor en un archivo :)

Saludos.-

**Comment by JuanQP** [comment]
Clarísimas las dos respuestas :+1: 

Muchas gracias a los dos :smile:

**Comment by FrancoVentrice** [comment]
Buenas!
Corregime si no entendí, pero yo lo pienso por el lado de que la idea de tener una estructura con las claves en el coordinador es porque idealmente el planificador no tiene conocimiento de que claves tiene cada instancia. Para ser sinceros no deberia saber ni de la existencia de ellas. Entonces por ejemplo si un ESI hace un SET sobre una clave existente, el coordinador deberia saber que instancia en particular tiene que procesar la instruccion, y no generar una clave duplicada en otra instancia.
Saludos!

**Comment by natoszme** [comment]
Sisi eso si. Se agrega a una estructura que tiene el coordinar que contiene las instancias y dentro de cada una de ellas, las claves que guarda. La duda es si hace falta tener otra estructura administrativa que guarde quien tomó la clave (esto no tiene que ver con las instancias) ya que esta info podría venir del planificador

**Comment by FrancoVentrice** [comment]
Claro, es responsabilidad del planificador saber eso, y no hace falta que el coordinador lo sepa. Totalmente de acuerdo con lo que planteás

Saludos!

**Comment by iago64** [comment]
Buenas buenas!

Me parece que están dándole vueltas de mas con las responsabilidades y eso puede generarles un pasaje de mensajes excesivo, las responsabilidades en limpio serían:

Coordinador: Saber que clave esta en que instancia
Planificador: Saber que claves están tomadas por que ESIs o que ESIs están bloqueados para que clave.

Saludos.-

**Comment by natoszme** [comment]
Comparto @iago64, entonces [acá](https://github.com/sisoputnfrba/foro/issues/1082#issuecomment-388590507) habría que ver, porque se ve que el coordinador está teniendo que la clave está tomada por algún esi y por lo que decís eso es responsabilidad del planificador. A lo que voy es a que esto se podría resolver sin guardar ninguna clave en el coordinador a la hora de hacer un get (como se menciona en ese comentario) y cuando se consulta el estado de la clave al planificador, ver si esta tomada por el esi en cuestión. Pregunto sólo para validar el modelado, no para decir que lo otro no sea correcto ni mucho menos!

**Comment by iago64** [comment]
@natoszme El problema que tenes es que cuando creas una clave mediante GET, tenes que hacer 2 cosas:
1.- Crear la entrada en el coordinador: ya que es una nueva clave en el sistema y tiene que ir a parar a alguna instancia a futuro
2.- Avisarle al planificador que el ESI1 tiene tomada la clave Y: ya que eventualmente si alguien hace GET Y a futuro va a tener que bloquearse a la espera de que termine el ESI1

De guardar cosas en el coordinador no tenes forma de safar porque es el que sabe donde esta cada clave a nivel de instancias
Y por otra parte de tener la tabla de claves tomadas en el planificador no vas a poder safar ya que en algún momento tenes que tener la lista de bloqueados para las claves tomadas.

Saludos.-

**Comment by natoszme** [comment]
@iago64 lo que yo digo es que cuando hacés el get, no guardás la clave en ningún lado en el coordinador, **pero le decís al esi que está bloqueado**. Esto hace que le llegue al planificador que este esi pudo tomar la clave. Cuando este mismo esi quiera hacer un set, el coordinador va a recibir del planificador que este esi tiene la clave bloqueada. Ahí es cuando en el coordinador elije a que instancia le corresponde ir a ese esi, en el momento del set, y por lo tanto es ahí cuando se guarda que la instancia tiene esa clave. Me seguís?

**Comment by NicoFeld** [comment]
Lo que dice nato, segun lo entiendo yo, es que en el momento de hacer un GETno es necesario que el coordinador se guarde la clave, ya que cuando se ejecute una instruccion SET, por parte del mismo ESI, cuando el coordinador le pregunte al planificador si esa clave esta bloqueada, le va a devolver que esta tomada por ese ESI, y en ese momento si se guarda el coordinador la clave en su estructura para el futuro. Estuvimos pensando si el coordinador necesita saber que la clave existe (aunque no este guardada en una instancia) para otro caso y no se nos ocurrio, si hay algun caso que se necesite ahi si deberia guardarse apenas se hace el GET

**Comment by natoszme** [comment]
Por ejemplo, si se hace un STORE sin un previo SET, la clave no estaría en la estructura del coordinador, pero esto es un problema? No, porque el cuando el store busque la instancia en la que se guarda la clave, no va a encontrar ninguna y se va a abortar al esi por clave no identificada.

Clave aclarar que nuestro coordinador _si_ guarda en qué instancia está cada clave, sólo que lo hacemos de forma distinta. Tenemos una lista de instancias donde cada instancia es una estructura que tiene un atributo que es las claves que esa instancia tiene guardadas.

**Comment by iago64** [comment]
@natoszme en el caso que me planteas la tabla de claves la tenes de una forma diferente a como se pensó en el enunciado, pero bueno, ahí si no tiene sentido que guarden en el coordinador la clave con el GET ya que a esa altura no deberían haber ejecutado el algoritmo de distribución, si no que deberían hacerlo al momento del SET.
Hubieras empezado por ahí y nos ahorrábamos un par de mensajes :)

Saludos.-

**Comment by natoszme** [comment]
Totalmente mala mía. Se ve que me mareé entre este issue y el otro que cité. En cuanto a lo de si el error de clave inexistente qué onda?

Gracias!

**Comment by iago64** [comment]
Traanca, son cosas que pasan :)
Respecto al error, perdón que se me paso por alto, si hicieron el GET previo, bien podrían correr el algoritmo de distribución y guardar la clave vacía y bajarlo a un archivo. o bien decir, es similar al caso 2 del anexo II, aborto el ESI y logueo bonito el motivo. Ambas opciones son validas y eventualmente no vamos a probarles los casos borde, posiblemente si probamos algo asi sea para validar la resilencia del sistema ante errores, pero el fuerte y lo importante de las pruebas va a estar enfocado en los casos felices donde todo corre bien y termina, no te olvides que tenemos varias combinaciones de algoritmos para probar :)

Saludos.-

**Comment by natoszme** [comment]
Mil gracias!

**Comment by iago64** [comment]
@natoszme No tenes nada que agradecer :)
@JuanQP quedo algo pendiente del issue o podemos cerrarlo?

**Comment by natoszme** [comment]
@iago64 pera pera yo tengo algo! Según lo que planteábamos recién, si se hace un store y se hizo un get la respuesta sería clave no identificada. Esto me decís que no hay drama.
Pero si un esi quiere hacer un store y **no** hizo un get (y nadie lo hizo antes), vamos a estar respondiendo que la clave no esta tomada por el esi en cuestión. Esto está ok? Como que lo que mostramos es verdad, pero también es cierto que la clave no existe

**Comment by afilgueira** [comment]
[Acá está contestado](https://github.com/sisoputnfrba/foro/issues/1082#issuecomment-388655449)

**Comment by natoszme** [comment]
Sisi, abortar se aborta. Sólo que estamos mostrando un error que tal vez no es. No hay drama? Gracias!

**Comment by afilgueira** [comment]
Arriba Damián les decía, no vamos a probar casos borde salvo para ver que "no se rompa todo". Con que diga "abortamos porque está mal" nos alcanza. Saludos!

**Comment by iago64** [comment]
Buenisimo, lo damos por cerrado y cualquier cosa creamos otro mas puntual :)
