### ISSUE TITLE
Ráfaga IO

### ISSUE THREAD

**Issue by sebastianciancio** [sisoputnfrba/foro#1084]
Para los Algoritmos de Planificación, consideramos que luego de una sentencia STORE comienza una ráfaga de IO? Si es así, cuando termina?

**Comment by afilgueira** [comment]
Hola, no. La ráfaga de IO va a estar "simulada" por los bloqueos que tenga un ESI. Podría nunca bloquearse. Pero cada GET que *efectivamente* bloquee, te corta la ráfaga de CPU.

Saludos!

**Comment by sebastianciancio** [comment]
Excelente. Muchas gracias
