### ISSUE TITLE
Buscas grupo o integrantes? Entrá acá

### ISSUE THREAD

**Issue by afilgueira** [sisoputnfrba/foro#1085]
Para unificar la "oferta y demanda" creamos este issue. Aquellos que busquen grupo y aquellos que busquen integrantes pueden publicar acá. Al hacer esto, van a quedar suscritos automáticamente a las nuevas respuestas que lleguen y centralizamos la info. Cuando la búsqueda esté cerrada, pueden borrar / editar su mensaje y desuscribirse.

Les recomendamos respetar el siguiente formato:

- Busco grupo / Buscamos N integrantes
- Nombre de grupo / persona
- Curso
- Mail o datos de contacto (opcional, esta en el perfil de github)
- Comentarios

Un detalle a tener en cuenta a la hora de dejar info de contacto: este foro es público (para cualquiera con cuenta en github).

Éxitos con eso!

**Comment by fmocchetti** [comment]
- Buscamos 1 integrante
- Grupo: Socketes
- Cursos: K3013 / K3011 / K3113
- fede.mo13990@gmail.com
- Comentarios: Que tenga ganas de laburar nomas, el conocimiento se adquiere

**Comment by ricardoAguirreSanchez** [comment]
Buscamos 1 integrante
Grupo: Real Mandril
Cursos: K3052
ricardo.aguirre.99@gmail.com
Comentarios: Que tenga tiempo y voluntad para meterse con el tp.

**Comment by kamipalomino** [comment]
-     Busco un grupo
-     Cursos: miércoles mañana profesora Nadiello
-     camilarpalomino@gmail.com
-     Comentarios: Cuento con mucho tiempo libre para dedicarle al TP. 
-     1° vez que curso la materia.

**Comment by rodillos** [comment]
- Busco grupo
- Curso : K3051 ( Lunes Noche)
- Mail  : rbotocorbal@gmail.com
- Comentarios: tengo la mayor parte del ESI completo , faltan afinar algunas cosas. aunque puedo dar una mano desde lo que se para las demás partes

**Comment by melaibanez** [comment]
*Buscamos 1 o 2 integrantes*
- Nombre de grupo : `EniacSO`
- Curso: `Viernes noche y Sábados.`
- Mail: [`melu.poker@gmail.com`](melu.poker@gmail.com)
- Comentarios: Buscamos gente que tenga ganas de trabajar y que tenga tiempo los sábados así nos podemos juntar.

**Comment by fakukpg** [comment]
- Buscamos un integrante
- Grupo: Lavate que viene gente
- Mail: faku.kpg@gmail.com
- Comentarios: buscamos una persona que tenga ganas de trabajar y tiempo los sabados para juntarnos.

**Comment by AleGonez** [comment]
Buscamos 2 integrantes
Nombre de grupo: los desconocidos
Curso: K3113 (sabados a la mañana)
Mail: Alejo.gonez@outlook.com 
Comentarios: estamos en la etapa inicial del TP por eso buscamos gente con voluntad y ganas de aportar, para meterle y poder avanzar.

Esperamos su msj.

**Comment by tferraro** [comment]
Habiendo cerrado el mercado de pases el pasado lunes, cierro el issue :slightly_smiling_face:
