### ISSUE TITLE
Error al generar una Commit

### ISSUE THREAD

**Issue by Giancarlo1107** [sisoputnfrba/foro#1087]
👋 ¡Hola!

Ojalá el foro te sea de ayuda. Para agilizar las cosas para tod@s, te pedimos un par de
cosas antes de que hagas una nueva pregunta:

- [ ] 🔍 ¡Buscá! Acá arriba hay un "Search" que te permite buscar consultas que hayan
hecho antes tus compañer@s. Quizá ya encontrás la respuesta servida.
- [ ] 📝 ¡Se detallad@! Si no encontraste tu respuesta, se tan clar@ y detallad@ en tu
pregunta como puedas. Tratá de contar qué hacés, qué observás, y qué entendés a partir
de eso - ¡pero sin mezclarlas!
- [ ] 📹 ¡Mirá cómo reportar desde Eclipse! Si tu problema es con código en Eclipse,
mirá el video [Cómo reportar errores desde Eclipse](https://youtu.be/18cN8Jk4WjQ) para
tener todos los detalles que necesitamos.

🙇 Gracias por leernos, y ¡éxitos!

tengo un problema para hacer una commit en la consola, cada vez que hago una commit sale el mensaje: ***Please, tell me who you are. y me indica que congifure nombre y correo, configuro mi nombre y correo y el porblema persiste con el mismo mensaje
![captura3](https://user-images.githubusercontent.com/39229419/40028884-01901994-57a7-11e8-947f-a491102aeee8.PNG) que debo hacer?

**Comment by NicoFeld** [comment]
Tenés que ejecutar los dos comandos que te recomienda la consola que hagas, poniendo tu email y tu nombre respectivamente

**Comment by Giancarlo1107** [comment]
Si, me di cuenta del error en que estaba recurriendo. Gracias por la ayuda.
