### ISSUE TITLE
Duda atomicidad SJF sin desalojo

### ISSUE THREAD

**Issue by feded94** [sisoputnfrba/foro#1088]
Buenas veniamos de realizar el fifo con la propiedad de atomicidad, en donde se ejecuta una linea del ESI y luego de ejecutarla, vuelve el ESI al fondo de la cola de listo (no ejecuta todas las lineas del ESI juntas, sino que ejecuta de a una y va cambiando de ESI).
La duda seria en el SJF sin desalojo, donde si sigo con el concepto de atomicidad ejecutaria de a una y creo que tendria el mismo resultado que el SJF con desalojo.
1-Entendi mal el concepto de atomicidad en FIFO?
2-Ejecutaria todas las lineas de cada ESI, y luego de terminarlas cambio de ESI, en el SJF sin desalojo? O deberia seguir ejecutando de a una? (Estoy casi seguro que es la primera opcion pero queria chequearlo)

**Comment by varas-c** [comment]
Buenas, como va?

Atomicidad significa que "una instrucción no puede ser interrumpida" no que
"ejecuta una instrucción y vuelve a la cola de listos". Que vuelva a la
cola de listos o no depende del algoritmo que estés usando en ese momento.
FIFO significa que el primer proceso que llegue, va a ser el primero en
ejecutar. Lo que vos implementaste no es un FIFO, sería un "Round Robin con
Quantum 1" (es decir, ejecuta una instrucción y es desalojado).
En FIFO el primer proceso en llegar, va a ejecutar hasta que termine o
hasta que es bloqueado por alguna operación de I/O.

Así que respondiendo la consulta 1, sí está mal 🙁 FIFO es el algoritmo mas
sencillo, fijate en los ejercicios de clase y es eso mismo lo que hay que
implementar.

Respecto a la consulta 2, Imaginate éste escenario, donde tenes un solo
proceso en la cola de listos (tiene 5 instrucciones para ejecutar) y estas
usando SJF con desalojo:
Como hay un solo proceso(A) en la cola de listos, ese va a ejecutar (no hay
otro, no?). imaginate que en el medio de la primer instrucción, llega otro
proceso(B) con mayor prioridad. La logica dice que "como el proceso B tiene
mayor prioridad que A, tengo que desalojar a A).

Pero que pasa? El proceso A está en el medio de su primer instrucción (es
decir, todavía no hizo una rafaga completa). Deberías desalojarlo en el
medio de la instrucción? No, porque las instrucciones son átomicas, no
podes "cortarlas por la mitad". Tenes que esperar a que A termine su primer
rafaga y recién ahí desalojarlo y meter al Proceso B.

En el mismo caso pero con SJF sin desalojo, no vas a desalojar al proceso A
porque si bien B tiene mas prioridad, el algoritmo es "sin desalojo".

Se entiende? Si no se entendió, no te quedes con las dudas y preguntanos
otra vez!




2018-05-21 10:17 GMT-03:00 feded94 <notifications@github.com>:

**Comment by feded94** [comment]
Perfecto, gracias, me habia complicado de mas
