### ISSUE TITLE
Funcionalidad list_iterate

### ISSUE THREAD

**Issue by leandroszikora** [sisoputnfrba/foro#1089]
Buenas, mi consulta es la función list_iterate que recibe una lista y un "closure". Estuve revisando la documentación de la función pero para asegurarme mi pregunta es si ese "closure" es una función que se le aplica a cada uno de los elementos de la lista.
Gracias.

**Comment by iago64** [comment]
Buenas buenas!
Vamos por partes:

list_iterate literalmente recorre la lista y ejecuta el clojure para cada elemento, ese clojure es una funcion que no retorna nada y recibe un void*

list_find es maaas o menos lo mismo solo que la condition es una funcion que devuelve un bool :)

list_remove_by_condition es lo mismo que el list find

y por ultimo list_any_satisfy recorre la lista y se fija si al menos 1 elemento cumple la condicion, es decir, la funcion de condicion es true.

En los 4 casos lo que tienen que hacer es mandarle funciones:
en iterate es para por ej, actualizar un campo en todos los elementos de la lista.
En los de find, remove, y any_satisfy lo que tienen que estar viendo es que se cumpla la condición.

Por una cuestion de generalidad la funcion siempre recibe un void* que uds los tienen que castear al tipo de su nodo de la lista.

**Comment by mgarciaisaia** [comment]
@LeaTex en los tests hay [un ejemplo de `list_any_satisfy`](https://github.com/sisoputnfrba/so-commons-library/blob/b244e38713afddef1a73dde35283baaecb3815c5/tests/unit-tests/test_list.c#L363-L369) que compara contra cosas hardcodeadas. El 16 del test sería equivalente a tu "Sr Tompson", digamos.

Pero la cosa se pone buena en [el último test](https://github.com/sisoputnfrba/so-commons-library/blob/b244e38713afddef1a73dde35283baaecb3815c5/tests/unit-tests/test_list.c#L401-L417): en ese, la función anónima (`_list_elements`) referencia a variables que existen en el scope de _afuera_ suyo - `names_array` no es un parámetro de la función `_list_elements`, si no que existe en el contexto en que `_list_elements` es declarada.

Y ahí está la papa del asunto. Las funciones que la juegan de bloque/closure/whatever sólo reciben a los elementos iterados - si necesitás más datos, tenés que hacer que estén disponibles en el contexto.

¿Se entiende?


CC: @leandroszikora

**Comment by LeaTex** [comment]
Gracias, había visto los tests, pero no me habían quedado claro.
Voy a darles otra mirada a ver si se me aclaran.

Lo de los bloques es fantástico, un gran potencial.
#AguanteSmalltalk

**Comment by leandroszikora** [comment]
Gracias por las respuestas! Cierro el issue

**Comment by mgarciaisaia** [comment]
Igual es una pregunta re frecuente esta. ¿Se les ocurre qué artefacto podríamos crear/mejorar para que quede más claro?

**Comment by mgarciaisaia** [comment]
@LeaTex, @leandroszikora, recién publicamos [este video](https://youtu.be/1kYyxZXGjp0) que intenta echar luz sobre este asunto. ¿Le pegan una mirada y me cuentan si soluciona?

También, _a largo plazo_, probablemente descartemos `cspec` en las commons y hagamos que los tests estén más en "C en criollo" para que se entiendan mejor (la sintaxis definitivamente es extraña a C).

Nada, gracias por el feedback - no es tan al pedo, after all :)

**Comment by LeaTex** [comment]
Ahí vi el video.
Muy bueno, aclara mucho más el panorama.
Gracias por tomarse el tiempo!!
