### ISSUE TITLE
Duda comando "pausar" 

### ISSUE THREAD

**Issue by ltrinidad** [sisoputnfrba/foro#1090]
Buenas! Tenemos la siguiente duda con respecto al comando _pausar_ en el planificador:
Cuando pausamos...
A) Hay que permitir conexiones de nuevos ESIs, **planificarlos**, peeeeero no mandar ninguno a ejecutar
B) Pausar todo el planificador y que no haga **nada de nada** (ni siquiera aceptar nuevas conexiones) hasta que alguien ingrese _continuar_
C) Permitir conexiones de nuevos ESIs pero **no planificarlos**, tenerlos por ahí en un rincón y cuando se ingresa _continuar_ agregarlos a la cola de listos y planificarlos.

No nos queda claro por lo que dice el enunciado es _"El Planificador no le dará nuevas órdenes de ejecución a ningún ESI mientras se encuentre pausado."_, pero no dice nada con respecto a la planificación o a la conexion de nuevos ESIs.

Estuvimos mirando las respuestas en los issues #1055 y #1053. En el #1055 se menciona que "No tiene que ver con el proceso Planificador en si, **sinó a la tarea de planificación**", y en el #1053 se aclara que "La pausa del planificador **impacta solamente sobre que no dará nuevas órdenes de ejecución**", por lo que nos quedan los baches que mencionamos antes.

Desde ya, muchas gracias ! :D

**Comment by iago64** [comment]
Buenas buenas!
Muy buena pregunta, la opción mas limpia y ajustada a la idea del TP es la opción A (permitir nuevas conexiones y dejarlos en la cola de Listos)

TL-TR:
La idea de que queden en la cola de Listos y no se manden a ejecutar va a asegurarnos de que todo queda frenado en ese momento y eventualmente no va a generar mas movimientos en las colas de procesos mas que las posibles llegadas a la de listos.
En un TP con un modelo de mas estados, los ESI que se conectaran cuando estuviera detenida la planificación deberían ir a una cola de NEW... pero en el TP no esta especificada, con lo cual no seria correcto tenerla.

**Comment by ltrinidad** [comment]
Perfecto!! Muchas gracias, vamos por la opción A. Cierro!
