### ISSUE TITLE
Problema con direcciones de memoria

### ISSUE THREAD

**Issue by GabrielRuderman** [sisoputnfrba/foro#1091]
Buenas, paso a consultarles el problema que tenemos: el ESI envía una instrucción al Coordinador y este se la envía a una Instancia, para lograr eso hacemos lo siguiente (resumen del código):

- ESI envía por socket un puntero del tipo t_esi_operacion:
`t_esi_operacion instruccion = parsearLineaScript(fp);`
`send(socketCoordinador, &instruccion, sizeof(t_esi_operacion*), 0);`
`printf("La direccion que envia ESI al Coordinador es: %p\n", &instruccion);`

- Coordinador recibe y envia:
`t_esi_operacion* instruccion = malloc(sizeof(t_esi_operacion);`
`recv(socketESI, instruccion, sizeof(t_esi_operacion*), 0);`
`printf("La direccion que recibe el Coordinador y se envia a Instancia es: %p\n", instruccion);`
`send(socketInstancia, instruccion, sizeof(t_esi_operacion*), 0);`

- Instancia recibe:
`t_esi_operacion* instruccion = malloc(sizeof(t_esi_operacion);`
`recv(socketCoordinador, instruccion, sizeof(t_esi_operacion*), 0);`
`printf("La direccion que recibe la Instancia es: %p\n", instruccion);`

Los printf imprimen lo siguiente:

`La direccion que envia ESI al Coordinador es: 0xbfe74698`
`La direccion que recibe el Coordinador y se envia a Instancia es: 0xb6c004b0`
`La direccion que recibe la Instancia es: 0x91225a0`

Lo cual está generando que la Instancia no pueda comprender la instrucción, ya que las direcciones a las que se apuntan son distintas.
Gracias.

**Comment by iago64** [comment]
Buenas buenas!
Si revisamos un poco la parte de memoria de la teoría, encontramos que las posiciones de memoria fijas no es algo que podamos usar libremente, ya que el SO dispone los programas en la memoria como a el se le ocurren, y menos si estamos haciendo algo en runtime donde los tamaños varían constantemente.

Teniendo lo anterior como premisa, lo que te conviene hacer en estos casos (ya que no podes controlar las posiciones de memoria de donde van a estar alojados los procesos) es mandar un mensaje serializado que en lugar del puntero tenga alguna forma de identificar la operación (1-GET, 2-SET, 3-STORE por dar un ejemplo) y que seguido del identificador de la operación por ej pongamos clave1 y despues el valor que sea valor1, entonces el mensaje que tendrías que mandar desde el ESI sea: '2 clave1 valor1'
Esto al llegarle al coordinador podrías parsear el mensaje y mandarle a la instancia que corresponda que el valor1 lo tiene que guardar en la entrada de la clave1

Saludos.-

**Comment by ricardoAguirreSanchez** [comment]
Buenas, quiero agregar un duda similar, en el caso que quiera solo mandar un entero, osea solo un número, puedo enviarlo en el send como:

int32_t numero=8
Send (fd,&número,sizeof(int32_t))

Puedo mandarlo así o también lo tengo q meter en un Buffer?

Saludos

**Comment by iago64** [comment]
@ricardoAguirreSanchez Si solo tienen que mandar un número, si pueden hacerlo de la forma que lo planteas, el buffer te sirve cuando serializas.

Saludos.-

**Comment by ricardoAguirreSanchez** [comment]
Gracias!

**Comment by GabrielRuderman** [comment]
Gracias Dami.
