### ISSUE TITLE
Consulta doble conexión coordinador-planificador

### ISSUE THREAD

**Issue by ricardoAguirreSanchez** [sisoputnfrba/foro#1092]
Buenas, 
Tenemos una duda, dada la estructura que tiene nuestro tp, nos vemos en la necesidad de habilitar algún medio extra de comunicación entre el coordinador y el planificador, especialmente por el comando status, unos de los ayudantes nos planteó dos alternativas, crear una conexión extra entre planificador y coordinador donde el coordinador sea nuestro cliente o enviar cada x cantidad de tiempo un mensaje preguntando al planificador si tenemos algo para pedir, creemos que lo que menos nos complicaria sería usar otra conexión, llendo por ese camino la duda que tenemos es: podemos en el archivo de configuración del coordinador agregar el puerto e IP del planificador auxiliar? Esto para que cuando el planificador le diga al coordinador "conectate" , este sepa dónde hacerlo.

Saludos

**Comment by tferraro** [comment]
Sip! Mientras que sea de forma criteriosa, pueden agregar lo que necesiten al archivo de configuración. Nosotros les detallamos lo mínimo que deberían tener :slightly_smiling_face:

**Comment by ricardoAguirreSanchez** [comment]
Ah perfecto, gracias!

**Comment by LeaTex** [comment]
Ricardo, no sé qué vuelta están dando, pero me atrevería a decir que esa conexión no sería necesaria.
Igual, sin meterme en la solución que están planteando, te aporto lo siguiente.

Si agregás en la configuración del **Coordinador** la IP y puerto del Planificador, para que se conecte, ¿cómo sabe el **Planificador** en qué puerto escuchar? Tendrían que agregarle al planificador también un parámetro de configuración que sea "puerto_escucha_para_coordinador".

Ahora, si se quieren evitar todo ese lía de parametría, voy a usar una frase tuya para dar una solución más linda:
> Esto para que cuando el planificador le diga al coordinador "conectate" , este sepa dónde hacerlo.

Yo haría que el Planificador le diga "conectate, estoy en la IP xxxxxx y el puerto nnnn" y listo.
El planificador sabe en qué servidor se levantó y en qué puerto está escuchando, así que puede pasarle esa info al coordinador para que se conecte, y no es necesario que lo agreguen en la configuración del coordinador.

**Comment by ricardoAguirreSanchez** [comment]
Gracias por la idea, vamos a ver con el grupo cual se nos complica menos.

Saludos
