### ISSUE TITLE
[Instancia] Almacenamiento contiguo, tabla de entradas, compactación, reemplazo y otras yerbas

### ISSUE THREAD

**Issue by LeaTex** [sisoputnfrba/foro#1094]
Buenas!
Entendemos que la tabla de entradas es una estructura administrativa que definimos nosotros.
En el enunciado dice:
> 10-  Dada la naturaleza de almacenamiento contiguo de los valores, en caso de que el tamaño del valor exceda el tamaño de la entrada, éste continuará en la siguiente entrada.

Y también:
> ...con la particularidad de que cada dato que se almacene será siempre en Entradas contiguas para facilitar el acceso.

P1: Según eso, deducimos que no podemos guardar valores fragmentados, por más que la tabla de entradas la administremos nosotros y sepamos cómo reconstruirlos. ¿Es correcta esta apreciación?

P2: Mientras haya lugar disponible, por más que esté fragmentado, no debería dispararse el algoritmo de reemplazo. Es decir, si el espacio total disponible permitiría almacenar el valor, se debe disparar la compactación de manera automática. ¿Es así?

P3: Podría ocurrir que hay espacio disponible, pero no lo suficiente. En este caso se ejecuta el algoritmo de reemplazo. Pero eso no nos asegura que la entrada reemplazada sea contigua a la entrada vacía, por lo que estaríamos en caso 2, y habría que disparar la compactación. ¿Está bien?

En resumen, según la situación, podríamos hacer:
- reemplazo
- compactación
- reemplazo + compactación

**Comment by iago64** [comment]
Buenas buenas!!

P1: efectivamente, no pueden guardar valores fragmentados, esto mas que nada es por una cuestion de que asi como en la teoría ven que los segmentos de memoria / bloques de archivo se almacenan juntos, aca se quiere modelar lo mismo (Si si, casi es una pregunta de coloquio la respuesta)

P2: Efectivamente, no hace falta compactar si todavía tienen espacio, en la realidad el compactar es un gasto de recursos mayor al buscar, por lo cual la compactación se utiliza en casos donde tengamos espacio suficiente pero no contiguo.

P3: Afirmativo 👍 si no alcanza el espacio aplican el reemplazo y eventualmente van a tener que compactar si la victima no es contigua al espacio libre que tienen, pero no lo tomen como una constante, si al reemplazar les queda el espacio suficiente contiguo no tienen que compactar.

**Comment by LeaTex** [comment]
Excelente!
![](https://ugc.kn3.net/i/origin/http://journeyhomeburke.files.wordpress.com/2007/05/350729-mrburns.gif)

Gracias.
