### ISSUE TITLE
Duda con tabla de entradas y storage 

### ISSUE THREAD

**Issue by LautaroOdriozola** [sisoputnfrba/foro#1095]
Hola!

La duda que tengo es la siguiente:

Cuando yo escriba un valor en mi storage de instancia, si éste es más grande que mi tamaño de entrada, voy a escribir más de una posición en el storage para poner ese valor completo. 

En mi tabla de entradas tengo la clave , la entrada asociada y el tamaño del valor. 

La consulta es si voy a tener una única "estructura" en la tabla de entradas por ese valor (sabiendo que el valor está dividido en varias posiciones dentro del storage) o voy a tener esa estructura por cada "partición" que haga del valor? ( Quedaría la misma clave para varias posiciones del storage). 

Espero una respuesta, gracias!

**Comment by LeaTex** [comment]
Según entendemos nosotros, ese manejo lo decide el grupo. No hay restricción al respecto, dado que la tabla de entradas es una estructura administrativa que podemos manejar como queramos.

La única restricción es que las entradas cumplan lo que dice el enunciado.

O sea, si un valor ocupa más de una entrada, solo tienen que asegurarse que esas entradas sean contiguas.

Podés guardarte algo como "la clave X tiene su valor guardado en las entradas N y M"; pero también podrías tener algo como "la clave X tiene la primera parte de su valor en la entrada N y la clave X tiene la segunda parte de su valor en la entrada M".

Cada solución tiene sus problemas, ya sea por tener que partir el valor, o tener que reconstruirlo, o dejarlo entero pero hacer la cuenta de cuántas entradas estaría ocupando según su tamaño.

**Comment by iago64** [comment]
Aloha!!
Tal cual como dice Lea, en caso de que tengan una clave cuyo valor ocupe mas de una entrada tienen que estar contiguas.

Despues como quieran adminsitrar las tablas queda a criterio de uds, igual mi recomendación (y no es mas que eso) teniendo en cuenta que en algun momento puede darse el caso que esa clave la saquen y puedan tener 2 entradas yo tendria un registro por entrada y despues en todo caso podria:
Ent1 - Clave1
Ent2 - Clave1

Asi no tienen que andar volviendo a dimensionar la tabla de entradas cuando saquen la Clave 1 :)

Saludos.-

**Comment by LautaroOdriozola** [comment]
Muchas gracias! Cierro issue
