### ISSUE TITLE
Reemplazo de valores Instancia

### ISSUE THREAD

**Issue by pablomonti** [sisoputnfrba/foro#1097]
Buenas a todos,
consulta, en el enunciado del TP dice que solo se reemplazaran los valores Atómicos, osea que ocupan una Entrada. Y que siempre se permitirá el almacenamiento de uno nuevo.
¿Entonces asumo que nunca puede darse el caso de que haya solo Valores No Atómicos cargados y ademas el Almacenamiento este completo?

Gracias!

**Comment by LeaTex** [comment]
Releyendo esa parte del enunciado, dice "el proceso de reemplazo de entradas solo se aplica a aquellos valores que cumplan con este criterio" (valores atómicos).

Y luego el algoritmo BSU dice "lleva registro del tamaño dentro de la entrada **atomica** que está siendo ocupado, y en el momento de un reemplazo, escoge aquél que ocupa más espacio dentro de una entrada".
Aunque la imagen que está genera confusión porque se indica para reemplazar una entrada no atómica.

Nosotros estamos considerando que sólo se pueden reemplazar valores atómicos. Por lo que podría pasar que todas las entradas estén ocupadas con valores no atómicos, y por lo tanto no se podría reemplazar ninguna.
Pero a su vez esto va en contra de la frase que dice "siempre se permitirá el almacenamiento de un nuevo".

**Comment by iago64** [comment]
Buenas buenas!! 

Efectivamente, el algoritmo BSU solo debe aplicarse sobre valores atómicos, esto quiere decir, si tienen un valor no atómico, va a quedarse ahí (ya que caso contrario siempre eliminarían las no atómicas). 
En el caso de los algoritmos LRU y Circular si pueden eliminar entradas no atómicas y por eso es necesario que hagan esa diferencia.

Saludos.-

**Comment by ivanpuchalka** [comment]
Creo que la pregunta era otra. Yo justo iba a abrir un issue por lo mismo. Suponiendo que no hay más espacio y no hay valores atómicos, o sea que no se puede reemplazar, ¿Qué se hace?

1. Siempre se tiene que poder almacenar un valor nuevo.
2. Si no hay espacio, se reemplaza un valor.
3. No se puede reemplazar valores que no sean atómicos.

Esas tres cosas juntas, en un almacenamiento lleno de valores no atómicos, no se pueden cumplir.

**Comment by iago64** [comment]
@ivanpuchalka Muy buena observación, yo pense que la pregunta venia del lado del algoritmo.
Ahora bien, para responder esto tengamos en cuenta una cosa y es que ese caso solo se te daria en un escenario donde todas las instancias esten completas, ya que a priori no deberias mandar nada a una instancia llena si tenes otras vacías.
En el caso de que este TODO lleno y tengas que almacenar un valor, ahi si tenes que recurrir a la opción de reemplazo.
Y como detalle no menor, no vamos a llenarles el almacenamiento de valores no atomicos, a lo mucho la prueba de valores no atomicos va a ir de la mano de asegurar que no los reemplacen cuando tengan que guardar un valor nuevo.

**Comment by pablomonti** [comment]
Gracias  por clarar la pregunta Ivan, exacto, esa era mi duda.
Ahora quedo mas claro Iago. 
Cierro. Saludos
