### ISSUE TITLE
Problema recibiendo header

### ISSUE THREAD

**Issue by agusmoles** [sisoputnfrba/foro#1098]
Buenas, tenemos un problema enviando el header de los mensajes entre ESI-Coordinador. En la maquina virtual imprimimos el Codigo de Operacion y el tamaño de la clave por pantalla y el primero esta bien, pero el tamaño tira un numero 'random' pero fijo siempre que ejecutamos. 

Verificamos que el send y recv manden/reciban todos los bytes, usamos int32_t y demas pero sigue pasando.

La cosa esta en que en Ubuntu funciona perfectamente y no entendemos por que, es simplemente un send y recv de sizeof(header)...

Saludos!

**Comment by tferraro** [comment]
Buenas!

Si es un código de operación solamente, al debuggear, que valores hexa tiene almacenada la variable? Cual es el numero "random" que les dá el tamaño? :slightly_smiling_face:

**Comment by iago64** [comment]
Mala mía por el cierre, quería consultar aparte de lo que dice Tom, es por casualidad están usando una pc de uds con Ubuntu 64 bits? ya que si es asi posiblemente si el header es un puntero las cosas cambien de longitudes :)

**Comment by agusmoles** [comment]
Lo que envia el ESI:

![tamano esi](https://user-images.githubusercontent.com/28370654/40506217-29b6e38a-5f6d-11e8-9f24-abb7cc948923.png)

Lo que recibe el Coordinador (en maq. virtual):

![tamano coordinador](https://user-images.githubusercontent.com/28370654/40506230-309d78c6-5f6d-11e8-9bfe-bb98d46933eb.png)

No entendi lo de los valores hexa, antes de enviar, despues o cuando?

Y si, Ubuntu es de 64bits, pense que si era eso se solucionaria con lo de int32_t, pero no.

Saludos!

**Comment by iago64** [comment]
Lo que te pidio @tferraro es que nos pases una captura del debug de eclipse entiendo.

Respecto a lo de ubuntu 64 bits, si, se soluciona el tamaño del tipo de dato con int32_t si y solo si estas definiendolo como:
`int32_t clave`
si haces
`int32_t* clave `
Estas complicado porque ahi es un puntero y si te cambia el tamaño.

Por otro lado, como estas mandando los datos? podes pegar el armado del buffer del send y como haces el recv?

Saludos.-

**Comment by agusmoles** [comment]
Te dejo el struct del header y como envio los datos:

`typedef struct header{
	int32_t codigoOperacion;
	int32_t tamanioClave;
}header;`

`case GET:
				tamanioClave = strlen(parsed.argumentos.GET.clave) + 1;
				header = crearHeader(0, tamanioClave);
				enviarHeader(socketCoordinador, header);
				enviarClave(socketCoordinador, parsed.argumentos.GET.clave);`

`void enviarHeader(int socket, header* header) {
	if (send(socket, header, sizeof(header), 0) < 0) {
		exitError(socket, ANSI_COLOR_BOLDRED"No se pudo enviar el header"ANSI_COLOR_RESET);
	}

	log_info(logger, ANSI_COLOR_BOLDGREEN"Se envio el header"ANSI_COLOR_RESET);
}`

Con respecto lo que me pidio @tferraro no entiendo que tengo que hacer. Disculpen la ignorancia

Saludos!

**Comment by iago64** [comment]
Fijate que estas haciendo el sizeof(header) cuando header es un header*, osea que en Ubuntu 64 Bits te funciona bien por pura suerte porque el sizeof de un header* es de 8 bytes (64 bits) y en la vm de lubuntu server es de 32bits (osea 4bytes)

Aca es donde nos ponemos densos y decimos: sean prolijos codeando, por ejemplo:

`
typedef struct header{
	int32_t codigoOperacion;
	int32_t tamanioClave;
}header;

//Podria y quedaria mejor si fuera:

typedef struct header{
	int32_t codigoOperacion;
	int32_t tamanioClave;
}header_t;
`

**Comment by agusmoles** [comment]
Claro, somos unos capos... 

Gracias por contestar tan rapido!

Cualquier duda vuelvo a abrir. Saludos!
