### ISSUE TITLE
Administración de tabla de entradas de la instancia

### ISSUE THREAD

**Issue by ricardoAguirreSanchez** [sisoputnfrba/foro#1099]
Buenas,

Tenemos una consulta en base a lo que pensamos que podría pasar del lado de la administración de la tabla de entradas cuando hay un reemplazo y queremos saber si esta bien.

Si tenemos en la instancia1  una clave1 con valor1 que ocupa 2 entradas donde la segunda no esta completa (atómico), si llega una operación **SET clave2 valor2** , el valor2 ocupa una entrada y no tengo lugares libres, paso a ejecutar el algoritmo de reemplazo donde terminare reemplazando en la única entrada atómica que tenia, al hacerlo actualizo mi TABLA DE ENTRADAS, es decir, agrego el registro para esta nueva clave2 pero también borro la clave1 ya que su valor no esta completo (y también borro el valor que quedo de la clave1 del storage).
Si luego llega una operación **SET clave1 valor3**, envio un error particular avisando al coordinador que esta clave no existe más dentro de esta instancia, así el coordinador pasara a actualizar su propia tabla y pueda borrar el registro de que la instancia1 tiene la clave1.

Este es un comportamiento aceptable o tendríamos que hacer algo diferente?

Saludos

**Comment by afilgueira** [comment]
[Hola, si ocupa dos entradas NO es atómico.](https://sisoputnfrba.gitbook.io/re-distinto/almacenamiento#valor-atomico) Saludos!

**Comment by ricardoAguirreSanchez** [comment]
Es muy cierto, mala mía, gracias !
