### ISSUE TITLE
Enunciado Coordinador - Bloqueos

### ISSUE THREAD

**Issue by ngoreico** [sisoputnfrba/foro#1100]
La descripción del próximo checkpoint dice que una de las cosas requeridas para la implementación mínima es:
"El Coordinador ... También deberá ser capaz de comunicar bloqueos."

A qué se refiere exactamente con comunicar bloqueos ? 

No es el planificador quien se encarga de esto, según los ejemplos que hay en la parte del coordinador ?

**Comment by iago64** [comment]
Si, el planificador es el encargado de controlar si estan bloqueadas o no las claves, pero por ej que pasa si queres hacer un SET o un STORE de una clave no bloqueada? 
La idea es que el coordinador tenga nocion de los bloqueos para el proximo checkpoint :)

**Comment by LeaTex** [comment]
Puede resultar confuso hablar de bloqueo para las claves (tengo la idea de que ya lo debatimos en otro issue).

Una clave "bloqueada" se refiere a una clave tomada. Es un recurso, que está usando un ESI (un proceso) y por lo tanto está tomado.

Por otro lado, los procesos se bloquean, en ese caso hablamos de los ESI, y el responsable es el Planificador.

clave bloqueada = clave tomada = recurso tomado

ESI bloqueado = proceso bloqueado

**Comment by ngoreico** [comment]
Perfecto, Gracias !

**Comment by ngoreico** [comment]
Vuelvo a abrir este issue, pensé que me había quedado claro pero no.

La idea entonces para este checkpoint es (por ejemplo) que el coordinador avise al planificador sobre un GET a un recurso, y sepa interpretar si el mismo le responde que esa clave ya está tomada ?

El coordinador solo se encarga de esta interacción, pero no se guarda nada, no ?

Gracias !

**Comment by iago64** [comment]
Buenas buenas!
Perdón por la demora, la idea del checkpoint es que el coordinador pueda consultarle al planificador por las claves tomadas, siempre y cuando las claves ya existan en el sistema. 
Si la clave no existe, es el primer ESI en hacer un GET por lo cual deberían crearla en el coordinador y avisarle al planificador que el ESI tomo la clave.

Saludos.-

**Comment by tferraro** [comment]
@ngoreico te sirvió la respuesta de Dami? Como venís con eso?

**Comment by ngoreico** [comment]
Buenas ! Recién lo pude ver.

Entonces el coordinador debería tener una estructura con las claves existentes ?

**Comment by iago64** [comment]
@ngoreico La estructura de las claves existentes la tenes que tener porque tenes que saber si estan en una instancia (y eventualmente en que instancia estan) sin tener que complicarte en andar pidiendo a cada una el listado de las claves que tienen :)

**Comment by ngoreico** [comment]
Gracias !
