### ISSUE TITLE
Valores no atómicos - Modo reemplazo

### ISSUE THREAD

**Issue by nataliasver** [sisoputnfrba/foro#1101]
Buenas! Estuvimos leyendo los otros issues, pero no nos terminaron de quedar claros algunos casos.

 Según el algoritmo de reemplazo, dice que no se pueden reemplazar valores no atómicos. Que pasaría en el caso de que este **activo el algoritmo de reemplazo**, y viene un valor no atómico con una operación de SET? 
  Caso 1 de respuesta: Se buscarían entradas atómicas contiguas para intentar guardarlo así? (horrible)  
  Caso 2 de respuesta: Le contesto que no se puede guardar y se aborta el esi?
  Caso 3 de respuesta: Le contesto que no se puede guardar, y lanzo la compactación? (y después intentaría guardar de nuevo?)
  Caso 4 de respuesta: Le contesto que no se puede guardar y el Coordinador elige otra instancia? (Dependería del algoritmo que tengo activo?, en el caso de Key explicit sería medio raro este caso)
Caso 5 de respuesta: Le contesto que no se puede guardar, y el Coordinador elige otra instancia, pero después de  enviar a todas, en ninguna se puede guardar (ya que están todas en modo reemplazo), ahí se manda la compactación?

PD: Nosotros entendimos en base a esto, que la fragmentación externa, solo se daría en el caso de que se hagan STORE de las claves que no son atómicas, ya que las atómicas eventualmente se pueden reemplazar (pero las no atómicas no). Así quedarían espacios vacios en el medio, que antes no podían ser reemplazados.

**Comment by iago64** [comment]
Buenas!
El caso que planteas es un caso borde, ya que vos estarías necesitando 2 entradas para almacenar un valor y solo tendrias 1 disponible. En ese caso, nos remitimos a la primera oración del algoritmo de reemplazo que dice lo siguiente

> Dado que nuestro sistema se enfoca en aspectos de disponibilidad y no tanto en aspectos de consistencia, siempre se permitirá el almacenamiento de un nuevo.

Dado esto, lo que tendrias que hacer sería:
1.- Liberar una entrada atómica según indique el algoritmo.
2A- Si las entradas libres quedan continuas grabar el nuevo valor
2B- Si las entradas libres no son contiguas, lanzar la compactación (tengamos en cuenta que esto va a hacer que todas las demas instancias tengan que compactarse tambien) y luego grabar el valor.

Saludos.-

**Comment by santiluccadeguevara** [comment]
Pero... si tenemos la desgracia que una instancia tenga todas sus entradas ocupadas con valores no atómicos ni fragmentación externa que genere compactación, dicha instancia no va a poder ejecutar el reemplazo porque no hay valores atómicos. O estoy entendiendo mal?

**Comment by LeaTex** [comment]
Sí, es lo mismo que entendimos nosotros.

**Comment by iago64** [comment]
Exactamente, si la instancia esta llena de valores no atómicos, siamo fuori, con lo cual a lo mucho deberían tenerlo en cuenta y no mandar cosas nuevas a esa instancia.

**Comment by santiluccadeguevara** [comment]
Qué raro... Pensé que los algoritmos de reemplazo no hacía esa distinción entre valor atómico y no atómico. Bueno. Sólo reemplazamos entradas atómicas entonces. Mejor XD Gracias por la respuesta a ambos. Saludos!

**Comment by santiluccadeguevara** [comment]
Perdón... Me acaba de surgir una cosa más (Estoy muy pesado hoy...): llegado al caso que ninguna Instancia pueda hacer ni reemplazo ni compactación por lo mencionado anteriormente, eso implica que la clave no se puede setear en ningún lado. Eso cómo quieren que lo manejemos? Es un error o simplemente se puede bloquear al ESI que ejecutó esa instrucción por falta de espacio?

**Comment by LeaTex** [comment]
![source 1](https://user-images.githubusercontent.com/6115573/40590496-116c989a-61d6-11e8-8133-0dcd2ae75318.gif)

**Comment by santiluccadeguevara** [comment]
Mejor no pregunto más nada porque va a venir toda la UTN FRBA y me van a prender fuego XDXDXD

**Comment by iago64** [comment]
@santiluccadeguevara No esta pensado hacer una prueba TAAAAAN borde, pero dado que se te ocurrio un caso tan extremo, la respuesta va a ser la más simple y es: _**Uds definan como quieren que se comporte el sistema en ese caso tan borde.**_ 
Llegado el caso que se de esa situación en la evaluación (cosa poco, muy poco probable), justifiquen el comportamiento y si los motivos son lógicos (a.k.a: no vale el nos pinto hacerlo así porque sí) esta perfecto :)

**Comment by LeaTex** [comment]
Bueno, para seguirle el tren a @santiluccadeguevara vengo con otro dilema filosófico:

¿Cuándo se produce la fragmentación externa?
Estoy viendo [el enunciado](https://sisoputnfrba.gitbook.io/re-distinto/almacenamiento#compactacion), pero la única forma de que queden esos huecos es cuando reemplazamos un valor no atómico por uno atómico.
Sin embargo, según lo que venimos debatiendo acá y en otros issues y lo que dice el enunciado, los valores no atómicos no se pueden reemplazar.

El único caso que se me ocurre donde haya que compactar es el que dijimos acá mismo: queda 1 entrada libre, y necesito 2 para almacenar un nuevo valor que no es atómico, entonces libero otra por algoritmo de reemplazo, compacto, y almaceno.

Salvo esto, no veo que de alguna otra forma pueda haber fragmentación externa. ¿Estoy en lo correcto, o debería irme a dormir dado que a esta hora no estoy pensando claro?

**Comment by santiluccadeguevara** [comment]
Hay otra situacion: Te puede pasar que volves a hacer un SET sobre una misma clave que antes ocupaba 10 entradas, y tras el SET, paso a ocupar 1 o bien paso a ocupar 15.

Ponele que tenes una instancia con 4 entradas de tamaño 1 y todas sus entradas libres haces:
```java
GET A
GET B
SET A, X
SET B, Y
SET A, XXX
```
Ahi te entra A, pero si la clave B te la pusieron en la 2da o 3ra entrada, deberias compactar, ya que la entrada que ocupaba antes A, "sigue siendo de A" por decirlo de alguna manera.

**Comment by iago64** [comment]
Buenas buenas!
Parece que estamos filosóficos hoy y ciertamente me encanta por un lado y me da cierto miedo que pierdan mucho tiempo por el otro, pero bueno vamos a la pregunta.
Tengan en cuenta que la fragmentación externa solo va a empezar a ocurrir en el momento que terminen / maten algunos ESIs, ya que antes de eso las entradas (si son prolijos) las van a ir asignando en orden y sumado a eso solo van a notar el inconveniente de la fragmentación externa en las entradas no atómicas (ya que las atómicas entran siempre).
Con lo cual, traten de no darle demasiadas vueltas al asunto, siéntense 5 minutos con sus compañeros, definan como lo hacen y nos avisan que decisión tomaron si llega a darse el caso en las pruebas (cosa que nuevamente les aviso _es muy muy muy poco probable_, es importante que no pierden de vista el hecho de que el TP en si hace varias cosas y si se queman con esto van a perder tiempo para la parte de los algoritmos de distribución del coordinador o los de planificación en el planificador :'()
Saludos.-

**Comment by LeaTex** [comment]
Perfecto!
Bueno ese caso @santiluccadeguevara se nos había escapado. Es como un reemplazo de la misma clave. Joya.

Gracias @iago64 , aclarado el tema.

**Comment by tferraro** [comment]
Veo medio cerrado ya el tema y tiene un poco de inactividad, por lo que cierro el issue. Igual, @nataliasver 
 veo que no respondiste nada a las seguidillas de respuestas que fueron apareciendo, si seguís con el problema, no dudes en volver a abrir el issue y lo vamos trabajando :muscle:
