### ISSUE TITLE
idEsi

### ISSUE THREAD

**Issue by thehighestprimenumber** [sisoputnfrba/foro#1102]
Hola! Les hago una consulta sobre el tema de los bloqueos de claves.
Según yo lo entiendo, el coordinador recibe una operacion de SET o STORE:
1. le pregunta al planificador si la clave está tomada por el ESI correspondiente
2.1 si da positivo, procede con la operacion
2.2 si da negativo, cierra la conexion con la ESI y el planificador la bloquea hasta que el recurso se libere

A) Esto es correcto?
B) para eso las ESIs deberan tener un ID, correcto? Esto nos será dado o podemos definirlo como nos resulte más conveniente?

Gracias!

**Comment by iago64** [comment]
Buenas Buenas!

Si intentas hacer un SET o un STORE para una clave la cual el ESI no la tiene tomada (o bloqueada), tiene que abortar por Clave no Bloqueada.

Saludos.-

**Comment by thehighestprimenumber** [comment]
El coordinador le manda 'clave no bloqueada' a la eso? O se aborta sola al leer del script?

**Comment by iago64** [comment]
La secuencia sería más o menos así:

1. El ESI1 solicita un SET sobre clave1 al coordinador.
2. El coordinador le consulta al planificador si el ESI1 tiene tomada la clave1.
3. El planificador le informa al coordinador que el ESI1 no tiene tomada la clave1.
4. El coordinador le avisa al ESI1 que no puede ejecutar el SET porque no tiene la clave bloqueada.
5. El ESI le avisa al planificador que no tiene la clave bloqueada y finaliza (previo informar correctamente el motivo de finalización).
6. El planificador pasa a la cola de EXIT al ESI1 y loguea que abortó el ESI1 por clave no bloqueada.

Eventualmente el paso 6 puede hacerlo el planificador en cuanto el coordinador le consulta si la clave1 esta tomada por el ESI1 (pero eso implicaría hacer que el planificador entienda que hay 3 operaciones en lugar de solo ESIs y Claves bloqueadas o tomadas)

Saludos.-

**Comment by thehighestprimenumber** [comment]
gracias! en este caso, vuelvo a mi pregunta sobre los nombres/ids de las
ESIs, los podemos definir nosotros o nos serán dados?

2018-05-26 22:14 GMT-03:00 Damian Facchini <notifications@github.com>:

**Comment by afilgueira** [comment]
Hola, sí. Pónganle ustedes un ID,[ porque de hecho podría tener que correr el mismo ESI N veces... ](http://i0.kym-cdn.com/photos/images/newsfeed/000/975/464/97d.gif)

**Comment by thehighestprimenumber** [comment]
gracias!
