### ISSUE TITLE
[Instancia] - Consulta sobre gestión de claves reemplazadas

### ISSUE THREAD

**Issue by santiluccadeguevara** [sisoputnfrba/foro#1103]
Holis. Tenemos una duda con la gestión de claves que se reemplazan en la Instancia:

Supongan que hay un solo ESI ejecutando con el siguiente script con una Instancia sola, sin importar sus dimensiones:
```java
GET A
GET B
SET A, X
SET B, Y // Este SET genera un reemplazo de la clave A en la Instancia
SET A, Z
````
Hasta donde tenemos entendido, la clave A debería dar error de clave inexistente, porque esta fue reemplazada en la Instancia.

En nuestro equipo, decidimos darle SET de todo lo que venga, ante lo cual, si nos viene un SET de una clave que ya reemplazó la Instancia, no habría problema en insertarla.

Esto claramente no cumple con el requerimiento pedido, y ahí nos surge la duda: qué modulo tiene la responsabilidad de llevar la cuenta de las claves reemplazadas? La Instancia o el Coordinador? Qué prefieren? Creemos que en la Instancia es un poco más simple, porque tranquilamente con una lista dentro de la Instancia se pueden saber las claves reemplazadas, pero en el Coordinador es mucho más eficiente porque directamente se pueden eliminar las claves reemplazadas de sus registros, aunque es bastante más complejo.

Espero que se entienda y sea válido el planteo, saludos.

**Comment by afilgueira** [comment]
[Cito el enunciado](https://sisoputnfrba.gitbook.io/re-distinto/almacenamiento#algoritmos-de-reemplazo)

> Dado que nuestro sistema se enfoca en aspectos de disponibilidad y no tanto en aspectos de consistencia, siempre se permitirá el almacenamiento de un nuevo. Para lograr esto cuando no existe más espacio, es necesario reemplazar entradas ya cargadas en la Instancia. **El valor previo se perderá, y si un ESI intenta acceder a este, se abortará por Clave no encontrada.**

Saludos!

**Comment by santiluccadeguevara** [comment]
Buenísimo. Ahora lo discutimos con el equipo a ver que nos conviene. Gracias!!
