### ISSUE TITLE
Consola del planificador

### ISSUE THREAD

**Issue by nahuelbranda91** [sisoputnfrba/foro#1104]
Hola!, en el enunciado, la parte de Consola de planificador, el "status clave" dice:
**status clave: Con el objetivo de conocer el estado de una clave y de probar la correcta distribución de las mismas se deberan obtener los siguientes valores: (Este comando se utilizara para probar el sistema)

Valor, en caso de no poseer valor un mensaje que lo indique.

Instancia actual en la cual se encuentra la clave. (En caso de que la clave no exista, la Instancia actual debería )**

(En caso de que la clave no exista, la Instancia actual debería )  -> está sin terminar la frase. 
Que debería suceder si no existe la clave?

Gracias!

**Comment by natoszme** [comment]
Buenas @iago64! Esto implica simular la distribución? Porque si ejecutamos el algoritmo posta y este por su implementación tiene efecto (modifica una variable global por ej), cuando hagas el set posta podría ir a otra instancia. Esto que decís ya está en la errata o algún lado?

**Comment by iago64** [comment]
@natoszme Si, la idea era simular el algoritmo de distribución para la clave, la misma no debería asignarse a ninguna instancia, ya que es a modo de consulta y por eso que se aclara que es un comando _para probar el sistema_.
En la errata no esta aun, estamos viendo si no tenemos más cambios menores para hacer para no estar sacando N versiones de errata por estos cambios.

**Comment by LeaTex** [comment]
@nahuelbranda91 creo que la frase que quedó mal expresada, es lo que se aclara en el punto que le sigue. Fijate cómo es el enunciado de ese comando:

**status clave**: Con el objetivo de conocer el estado de una clave y de probar la correcta distribución de las mismas se deberan obtener los siguientes valores: (Este comando se utilizara para probar el sistema)
- Valor, en caso de no poseer valor un mensaje que lo indique.
- Instancia actual en la cual se encuentra la clave. (En caso de que la clave no exista, la Instancia actual debería )
- Instancia en la cual se guardaría actualmente la clave (Calcular este valor mediante el algoritmo de distribución(^4), pero sin afectar la distribución actual de las claves).
- ESIs bloqueados a la espera de dicha clave.

@FrancoVentrice supongo que cuando hablás de "variable" te referís a una clave, ¿no?
Efectivamente, como hay que simular, ningún valor se alteraría realmente. O sea, tenés que hacer el "roolback" en lugar del "commit" :P
Lo mejor sería usar un puntero auxiliar, para no tocar el puntero original.
Y sí, en el caso del equitative load la simulación debería devolver siempre la misma respuesta para distintas claves no existentes, siempre y cuando no se haya ejecutado ninguna sentencia de un ESI que registre alguna clave nueva (imagino que esto podría estar pasando en background mientras uno está jugando con la consola).

**Comment by iago64** [comment]
@LeaTex venís muy afilado, me parece que me voy a anotar para evaluar tu TP ya que a este paso el cuatri que viene te estoy viendo del otro lado del sistema de inscripciones :)
Ahora bien, la pregunta de @FrancoVentrice la idea es que trabajan de forma modular y que por ejemplo tengan: 
Por un lado el calculo del algoritmo que sea inmutable y que si lo tiran 1 o 50 veces sin cambios en el sistema les de el mismo resultado
Por el otro la asignación de una clave a una instancia que ahí si actualice los punteros.
Esto es muy posible que no lo tengan planteado de esta forma, por lo cual en esos casos entonces si tienen que recurrir a alternativas como la que comenta Lea de tener algo auxiliar (un puntero, una estructura o lo que fuere)
Saludos.-

**Comment by FrancoVentrice** [comment]
Bien, duda resuelta, muchas gracias!

**Comment by iago64** [comment]
@nahuelbranda91 como va? te quedo alguna duda?

**Comment by nahuelbranda91** [comment]
resuelto gracias
