### ISSUE TITLE
Comando bloquear/desbloquear de la consola del Planificador

### ISSUE THREAD

**Issue by Criisss087** [sisoputnfrba/foro#1105]
Buenas! 

Estamos con los comandos bloquear/desbloquear de la consola, y leyendo el issue #1078 nos surgieron algunas dudas.

Bloquear (Sacado 1 y 2 del issue que mencioné, los 1.X y 2.X la duda):

1- Si la key MATERIA1 no estaba bloqueada, la bloqueas para el ESI1 esto implica:

	1.1 Agregar clave+pid del ESI al esa "lista de claves bloqueadas" que le sirve de control al planificador
	1.2.a Si el ESI estaba en Ready, hay que pasarlo a Bloqueados
	1.2.b Si el ESI estaba en ejecucion, hay que esperar a que termine la instruccion en ejecucion (por la atomicidad), desalojarlo y pasarlo a Bloqueados

2- Si la key MATERIA1 si estaba bloqueada (es decir que ya alguien te hizo un GET antes), solamente agregas a la cola de bloqueados el ESI1

	2.1.a Idem 1.2.a
	2.1.b Idem 1.2.b

Hasta acá está bien? Ademas notamos que:

3- Si el ESI que se pasa por parametro al comando (bloquear CLAVE ESI) no existe en el sistema, como debe actuar el planificador?

	Chance 1: Agregar la clave como bloqueada, sin ese pid de ESI "bloqueante" (Quedaria igual a las claves bloqueadas por configuracion)
	Chance 2: Informar error y no hacer nada

Para el comando desbloquear, la especificación menciona:
"desbloquear clave1: Se desbloqueara el primer proceso ESI bloquedo por la clave especificada." (clave1 = clave en el enunciado)

Esto implicaría:
1- Eliminar de esa lista de claves bloqueadas clave1, pasada por parametro al comando
2- Buscar el primer esi bloqueado por esa clave1 y pasarlo a ready

Con este escenario, despues de desbloquear "clave1" nos queda que:
*Lista de claves bloqueadas no tiene a "clave1"
*Hay un esi en ready, que cuando ejecute, hará el GET clave1
*En la lista de bloqueados, puede haber X cantidad de esi que sigan bloqueados por la clave "clave1" por mas que la misma no este en la lista de claves bloqueadas.

Esto estaria bien?

**Comment by iago64** [comment]
Buenas buenas!!

Vamos por partes 
**--Bloqueo de Claves--**
1.- Exactamente como lo describís (especialmente la parte de 1.2, ahi por mas que sea un algoritmo sin desalojo tenes que desalojarlo)
2.- Seguís de 10
3.- Si el ESI no existe simplemente creen la clave como si estuviera bloqueada por config (pero por favor logueen que el ESI no existe asi queda linda la trazabilidad)

**--Desbloqueo de Claves--**
1.- Si la clave no existe es el camino mas fácil ya que simplemente informan de que la clave no existe y todo sigue su curso
2.- Si la clave existe tienen que:
2.1.- Poner al primer ESI de la cola de bloqueados en Ready
2.2.- Si no hay mas ESIs bloqueados liberar la clave

Saludos.-

**Comment by Criisss087** [comment]
Perfecto, se entendió todo! 
Cierro.

**Comment by Criisss087** [comment]
Buenas!

Leyendo el issue #1114 quedé mas confundido que antes.

Originalmente, el comando "bloquear" lo que hace es bloquear un ESI, y lo que explicaron acá es el bloqueo de clave (creo)
En ese issue se dice que lo que hace el comando es simular un GET clave esi, cosa que, entiendo, contradice a lo anterior.

Creo que la confusión viene sobre que es lo que se bloquea, y quiero sacarme la duda.

Comando bloquear -> Bloquea proceso (esi), simulando que ese esi intenta apropiarse de la clave.
bloquear clave-> Bloquea la clave, es decir, se la asigna a el recurso (clave) al proceso (esi)

Hablando solamente del comando bloquear de la consola. Yo había comentado que hace:

Duda 1:
Especificamente, en el punto 1.1 mencione agregar clave+pid del comando a "claves bloqueadas" que en realidad podríamos decir que es "recursos asignados a procesos". Si el comando busca bloquear un proceso, eso está mal, porque en realidad le estoy asignando un recurso. ¿Esto está bien?
Porque si después en el mismo comando bloqueo ese mismo proceso (1.2 a y b), tendría un recurso asignado a un proceso, y ese mismo proceso bloqueado por intentar acceder a un recurso que el mismo tenia, y eso no tiene sentido.

Duda 2:
En cuanto a la "simulación de GET" si el comando de la consola estaría haciendo esto, dado el caso que la clave no este siendo usada por otro esi (si no esta bloqueada) ademas de crearla en esa lista "claves bloqueadas" (o recursos asignados a procesos) como el planificador no tiene esa clave, se deberia avisar al coordinador para que la cree en el sistema? (Tal cual como si fuese un GET)

Espero se entienda.

**Comment by iago64** [comment]
Buenas buenas!!
La duda creo que se entiende y es culpa de que tenemos palabras similares o iguales para lo mismo y a veces no es lo mas didáctico, con lo cual vamos a las dudas en puntual:

Duda 0: Se que esta duda no existe pero es una pequeña aclaración que no viene mal hacerla y es que el bloquear clave es lo mismo conceptualmente que tomar clave, es decir esa clave esta asociada a un proceso, que bien puede ser un ESI o bien puede ser un proceso "System" que es por ej el que tendrían que "usar" cuando crean las claves bloqueadas por archivo de config.

Duda 1:
La idea del comando bloquear, programaticamente hablando es que haga lo mismo que el GET, es decir, bloquee el proceso si la clave esta tomada.

Duda 2:
Simula las comprobaciones que hacen con el GET (verificar que la clave esta bloqueada y en consecuencia bloquear un ESI o solo asignarle la clave) la idea es que las mismas funcionen que usen en el GET las usen en el Bloquear de la consola (Nota: Por algo fuimos tan densos con el tema de que codeen las cosas lo mas atómico posible y que sigan las buenas practicas de programación que vieron en paradigmas.)

Saludos.-

**Comment by Criisss087** [comment]
Duda 0: Perfecto.

Duda 1: Entonces, lo que yo había puesto en el primer mensaje, estaría bien hasta el 1.1 (Asigno el recurso a ese proceso). Pero desde ahí, el resto esta mal, ¿no? porque yo estoy diciendo que hay que mover ese ESI a bloqueados, y en realidad solo le asigné un recurso (Cosa que como fue exitosa, no hay que bloquearlo tal como decis en la respuesta a la duda 2)

En cambio en el 2 (Clave ya estaba bloqueada, es decir, asignada a otro proceso o al sistema (como dice la respuesta 0) Ahí sí debo bloquear al ESI tal como dije en el mensaje original.

Duda 2: Perfecto.

**Comment by iago64** [comment]
Bien, nos quedamos en la duda 1, y si, vos le vas a decir bloquear y en realidad vas a hacer cooomo si el ESI estuviera haciendo un GET del recurso.
Igual un pequeño spoiler, _si la clave no es de las creadas de inicio con el sistema, vas a estar diciéndole que le haga GET a una clave que ya minimo creo y bloqueo otro ;)_

**Comment by Criisss087** [comment]
Bien, con esto la duda queda completamente resuelta jaja
Lo del spoiler, supongo que se refieren a las pruebas no? Eso espero jajaaj.

Gracias! Cierro
