### ISSUE TITLE
Automatización del Dump

### ISSUE THREAD

**Issue by sebastianciancio** [sisoputnfrba/foro#1106]
Estamos con la automatización del Dump en las Instancias. 

Una opción que vemos, para no estar verificando constantemente si el tiempo se alcanzó y evitar un ciclo infinito, es chequear cada vez que ingresa una Instrucción a la Instancia si el tiempo fue alcanzado. Es una aproximación a una solución no bloqueante.

Otra opción es crear un Hilo que solo lleve el tiempo transcurrido y notifique cuando debe ocurrir el evento.

Alguna observación o comentarios?

**Comment by LeaTex** [comment]
Sebas, una forma de hacerlo fácil es usando alarm() y signal().

Investiguen bien cómo funciona, pero básicamente usa el reloj del sistema para activarse disparando una señal al proceso, que deben tratarla. Así lo estamos haciendo nosotros ;-)

Por supuesto que hay otras formas, como las que indicás, y también otras mejores, pero esta que te digo es una buena solución y sencilla.

Lo de chequear luego de cada instrucción no se los recomiendo, porque si una instancia no está recibiendo instrucciones, está ociosa, y se podría pasar el tiempo de hacer el dump y no lo ejecuta.

**Comment by sebastianciancio** [comment]
Excelente lo de alarm()!! No lo conocía. Muchas gracias.
