### ISSUE TITLE
Duda deadlock

### ISSUE THREAD

**Issue by ricardoAguirreSanchez** [sisoputnfrba/foro#1107]
Buenas,
Tenemos una duda seguramente simple pero para dejar las cosas claras dentro del grupo preferimos preguntarlo, del enunciado:

"deadlock: Esta consola también permitirá analizar los deadlocks que existan en el sistema y a que ESI están asociados. Pudiendo resolverlos manualmente con la sentencia de kill previamente descrita."

Lo que se espera ver es que por cada deadlock que encuentre muestro todos los Esis que están involucrados?, es decir:
Deadlock1:
Esis involucrados: Esi1-Esi2-Esi3
Deadlock2:
Esis involucrados: Esi4-Esi5-Esi6-Esi7
....

Sería así?

Saludos.

**Comment by varas-c** [comment]
Hola! Como va?

Probablemente se te dificulte hacer eso, es decir "diferenciar" deadlocks.

Cómo que informes que ESI 1,2,3,4,5,6,7 están en deadlock es suficiente, no
vamos a pedir que "los diferencien".

Si te quedó alguna duda, acá estamos!

**Comment by ricardoAguirreSanchez** [comment]
Genial , gracias!
