### ISSUE TITLE
Soporte - Sabado 02/06

### ISSUE THREAD

**Issue by GabrielRuderman** [sisoputnfrba/foro#1108]
Que tal, queria consultar si este Sabado 02/06 va a haber algun ayudante en Medrano, ya que en el excel aparecen algunos ayudantes con "X" y no especifica donde se van a encontrar.

Gracias.

**Comment by afilgueira** [comment]
Entre hoy y mañana confirmamos bien. Seguramente haya un par de horas.

Saludos!
