### ISSUE TITLE
[Instancia] - Duda con necesidad de implementar mmap()

### ISSUE THREAD

**Issue by santiluccadeguevara** [sisoputnfrba/foro#1110]
Hola. Estoy con un par de dudas acerca de la implementación del `mmap()` en el Trabajo Práctico.

Se entiende que `mmap()` mapea un archivo a memoria, y esto nos permite escribir en un cacho de memoria con un `memcpy()` y que se refleje en el archivo mapeado, porque asocia a un bloque de disco con un frame de memoria.

El problema que surge es que lo noto bastante rebuscado/forzado su uso para el TP, o quizá estoy entendiendo algo mal:

El primer uso que se me ocurre es inicializar el Storage con un `mmap()` en lugar de un `malloc()`: tendría todo mi cacho de memoria listo para escribir en disco, pero a un solo archivo, lo cual no me sirve de nada, puesto que voy a tener tantos archivos como claves haya en la tabla de entradas (además que contradice al enunciado de iniciar el Storage con `malloc()`).

Así que el otro uso que se me ocurre es que en el momento que hago un `STORE`, mapeo el archivo asociado a la clave a memoria, le copio los bytes que tenga asociados al valor y al final unmapeo para no leakear memoria. Lo cual me parece forzado cuando puedo usar un simple `fwrite()`.

No estaría viendo un uso razonable de `mmap()`, aparte de que me simplifica el manejo de archivos. Más que nada, mi duda es si tengo alguna otra ventaja además de esa. Saludos.

**Comment by iago64** [comment]
Buenas buenas!

Si, puede que para este TP el uso de mmap() quede un toque grande, pero la idea de que usen mmap() en lugar de que tengan que hacer los fwrite es que uds puedan por ej tener en su lista de claves un puntero que sea su archivo que lo crean al momento de que tienen que crear la clave y que gracias a esto los dump / store sean mas faciles y rápidos  (a esta altura asumo que saben que mmap() devuelve un puntero a una dirección donde "esta el archivo en la memoria").

TL;DR: la idea del tp al final de cuentas es que usen herramientas que por ahí no van a ver en otros lenguajes / materias y que son base de muchas soluciones de mercado y que por ahí si las llegan a ver en un futuro después de usar mmap() (U otras cosas del tp de sisop) no sea algo escrito en celtíbero (antes decía escrito en chino hasta que conocí alguien que hablaba chino y me cago el ejemplo 👎 )

En fin, espero haberte podido ayudar.
Saludos.-

**Comment by santiluccadeguevara** [comment]
Ok. Buenísimo. Entiendo. Más que nada la duda era porque decía en el Checkpoint 2 "Comprender mmap()" algo así y pensé "Uh, lo tengo que usar en algún lado sí o sí" y no se me ocurría donde quedaba más útil y canchero en función de lo que pide el TP. Gracias!!

**Comment by mgarciaisaia** [comment]
Si leíste qué hacía una herramienta, lo pensaste, encontraste dos posibles lugares donde usarla, encontraste motivos fundamentados para no usarla en esos casos, y escribiste toda esta consulta - lo más probable es que hayas re cumplido la parte de Comprender 👌
