### ISSUE TITLE
Duda a la hora de compactar

### ISSUE THREAD

**Issue by BlacuttMatias** [sisoputnfrba/foro#1111]
Buenas!

Estábamos trabajando sobre la compactación en las instancias y nos surgió una duda. En el enunciado dice lo siguiente: “Mientras está en ejecución el proceso de Compactación, no se permitirá ejecutar operaciones en el Sistema de Re Distinto y quedarán en espera a que el proceso se complete correctamente.”. Ahora, sabiendo que si una instancia debe compactar, todas lo harán, se nos ocurrió tres maneras de tratar esto:

1 – Hacer que el coordinador no le mande mas instrucciones a las instancias hasta que todas estas le respondan que ya terminaron de compactar.
2 – Dejar que el coordinador siga mandando instrucciones, pero controlar en cada instancia que la misma no ejecute ninguna instrucción más hasta que haya terminado de compactar.
3 – No hacer nada. Capaz estamos pensando de más y en realidad no hay necesidad de hacer un control sobre esto.

Entonces, alguna de estas formas de encarar el problema es válida? En el caso de que la decisión quede entre elegir la opción 1 o la 2, hay alguna que recomienden mas que otra?

**Comment by iago64** [comment]
Buenas buenas!
La cosa va por el camino más simple y es que cuando mandan a compactar las instancias, lo que no pueden hacer es procesar instrucciones de los ESI.
Peeero ojo, eso no quiere decir que por ej no se puedan conectar nuevos ESIs :)
En resumidas cuentas lo que está prohibido mientras compactan es hacer GET, SET o STORE, todo lo demás, está permitido :)

Saludos.-

**Comment by LeaTex** [comment]
yo iría por la opción 1.
consulta: ¿el término **Coordinador** a qué les suena? ;-)

**Comment by tferraro** [comment]
Holis :wave:, vengo a ampliar lo que dijo Dami.

Es nesario **parar** las operaciones de los ESIs solamente. También como comenta @LeaTex la forma más cohesiva es que el coordinador haga un paro y reanude cuando todas las instancias estén listas, pero para eso, depende en gran parte de como hayan implementado el proceso de compactación, quien es "el que tiene la sartén por el mango" al momento de _coordinar_ las instancias para compactar.
Si es el coordinador (valga la redundancia), la opción 1 rinde infinito, si es la instancia original que sigue manejando eso usando el coodinador como un proxy, capás conviene usar la opción 2 manteniendo una especie de "buffer" de operaciones para no romper nada. Total, mientras que no devuelvan, el coodinador no dice nada a los ESIs.

Aprovechen esta reflexión y vean según su implementación que tiene más sentido para ustedes :slightly_smiling_face: 

Suerte!
Tom

**Comment by BlacuttMatias** [comment]
Perfecto, gracias!
