### ISSUE TITLE
Terminación ESI

### ISSUE THREAD

**Issue by ortizmarcosn** [sisoputnfrba/foro#1112]
Hola! Me surgió una consulta con respecto a la terminación del ESI.

El ESI está leyendo archivos de forma dinámica, por ejemplo, los 3 correspondientes al Checkpoint 3... Una vez que finaliza la ejecución de los 3, ¿El ESI debe seguir escuchando en caso de que ingrese algún archivo nuevo o debe finalizar?

Gracias!

**Comment by mgarciaisaia** [comment]
👋¡Aloha!

Cada ESI va a ejecutar _un único_ script. Cuando en las pruebas decimos que hay una VM que ejecuta 3 scripts (como dice la configuración default que tiene que hacer la VM 2, por ejemplo), eso significa que se van a ejecutar **3 procesos ESI**, cada uno ejecutando un script distinto.

Me parece entender de tu mensaje que pensaban que era una única instancia del proceso ESI la que ejecuta los 3 scripts - eso **no** es correcto.

Dicho esto, cada proceso ESI va a finalizar cuando el ESI sea finalizado en la planificación.

**Comment by iago64** [comment]
@ortizmarcosn La respuesta de Mati te sirvio? tenes alguna duda extra o podemos cerrar el issue?
