### ISSUE TITLE
Bloquear una clave que existe/no existe

### ISSUE THREAD

**Issue by ricardoAguirreSanchez** [sisoputnfrba/foro#1114]
Buenas,
Tras leer un par de issues (#1078, #1105), terminamos más confundidos que antes, así que queremos saber que debería pasar en estos 2 casos particulares:

CASO1:
**BLOQUEAR** **JUGADOR** **3**
Si la clave JUGADOR no existe en mi sistema, lo único que hago es hacer que el ESI de id=3 "tome" (o bloquee) a la clave JUGADOR?

CASO2:
**BLOQUEAR** **JUGADOR** **2**
Si la clave JUGADOR existe, lo único que hago es bloquear al ESI de id=2, es decir, simulo el comportamiento como si hubiera hecho un GET JUGADOR y esta clave estuviera previamente tomada por otro esi, esta bien?

Saludos.

**Comment by iago64** [comment]
Buenas buenas!

GET de una clave que no existe en el sistema, lo que hace justamente es crearla en el sistema y hacer que el ESI que hace el GET sea el "dueño" de esa clave.

GET de una clave que existe, tienen que verificar si esta tomada por algun ESI o no, ya que de ahi tenes los 2 caminos:
Si e

1. sta tomada por un ESI el nuevo que hizo GET de bloquea
2. Si no esta tomada por ningun ESI el ESI que acaba de hacer el GET es quien pasa a ser "dueño" de la clave

Saludos.-

**Comment by ricardoAguirreSanchez** [comment]
Buenas,
Lo que quería consultar era por el comando BLOQUEAR CLAVE ID

**Comment by iago64** [comment]
Buenas buenas!
Ahora si, hablamos del comando de la consola del planificador, en ambos casos, lo que tienen que hacer es simular como si ESI que pasan por ID hubiera hecho GET JUGADOR :)

Saludos.-

**Comment by ricardoAguirreSanchez** [comment]
Ahh listo, muchas gracias!
