### ISSUE TITLE
Reemplazo de multiples claves

### ISSUE THREAD

**Issue by Mszlajen** [sisoputnfrba/foro#1115]
Buenas, estabamos haciendo el algoritmo de reemplazo y nos surgio una duda:
Dado el caso de una instancia a la que le llega una clave que requiere 3 entradas y solo tiene una entrada libre, tiene que reemplazar 2 claves?

**Comment by iago64** [comment]
Buenas buenas!!
En el caso que planteas no te queda otra mas que reemplazar 2 claves, ya que el sistema tiene que aceptar los valores que se intentan ingresar.

Saludos.-

**Comment by Mszlajen** [comment]
Genial, eso pensamos pero queriamos estar seguros.
