### ISSUE TITLE
Consulta campo "valido" en t_esi_operacion del ParSI

### ISSUE THREAD

**Issue by LucianaNapolillo** [sisoputnfrba/foro#1116]
Hola!
Cuando el ESI parsea las sentencias del script, por cada sentencia ParSI devuelve si es válida o no, en el campo "valido". La duda es, el ESI debería primero parsear todo el script antes de comenzar a ejecutar, para ver si hay alguna sentencia inválida y en ese caso abortar? O a medida que se va ejecutando el script ir chequeando el campo "valido" y al encontrar una sentencia inválida abortar?

Gracias!

**Comment by tferraro** [comment]
Anda por la segunda opción.

No deberian haber sentencias inválidas, por lo que no hace falta que hagan
el chequeo de entrada.

Saludos!

Tom

**Comment by LucianaNapolillo** [comment]
Buenísimo, gracias!
