### ISSUE TITLE
Comando "status" consola planificador

### ISSUE THREAD

**Issue by alabarque** [sisoputnfrba/foro#1117]
Hola buenas tardes.

Estamos teniendo una discusion sobre cómo ejecutar este comando cuando el Planificador corre la consola y planifica un esi a la vez.

Para intentar simplificar las cosas, no sabemos si al ejecutar el comando status deberiamos esperar a que se termine de ejecutar la linea de codigo que envia el planificador al esi. O si este comando puede correr en paralelo ya que en el unico momento en donde se encuentran ambos hilos es cuando se debe listar los procesos bloqueados por la key.

Muchas gracias.

**Comment by iago64** [comment]
Buenas buenas!
Lo ideal sería que lo hagan en paralelo ya que de ultima su problema de "encuentro" de los hilos lo resolver con 1 semaforo :)

Saludos.-

**Comment by alabarque** [comment]
Perfecto, la discusion surgio por el problema de la atomicidad de la ejecucion de la linea del esi (osea que deberia ejecutar de forma ininterrumpida) y en ese momento particular se puede llegar a frenar la ejecucion de la sentencia hasta que se devuelvan los esis bloqueados. 

Gracias por aclarar, saludos.
