### ISSUE TITLE
Consultas sobre Planificador

### ISSUE THREAD

**Issue by FrancoVentrice** [sisoputnfrba/foro#1118]
Buenas, traigo algunas consultirijillas de n00b sobre el planificador. Entre tanta mescolanza, me volvieron a surgir algunas dudas básicas:

- Un ESI hace un GET sobre una clave libre, la toma.
- Un ESI hace un SET sobre una clave libre, queda abortado.
- Un ESI hace un STORE sobre una clave libre, queda abortado.
- Un ESI hace un GET sobre una clave tomada por otro ESI, queda bloqueado.
- Un ESI hace un SET sobre una clave tomada por otro ESI, queda abortado.
- Un ESI hace un STORE sobre una clave tomada por otro ESI, queda abortado.
¿Son todos los casos correctos?

Segunda pregunta: Según el enunciado, la consola del planificador tiene una opción para darle play/pausa al proceso de planificación. Cuando el planificador recién se levanta, comienza con la cola de listos vacía y por lo tanto no puede comenzar el proceso de planificación. 
¿La idea es que se puedan conectar todos los ESIs, y luego darle play por consola para que comience, o apenas se conecta un ESI el planificador arranca sin preguntarle a nadie?

Chas Gracias!

**Comment by iago64** [comment]
Buenas buenas!
Rapidamente esta todo correcto pero vamos por cada caso:

Un ESI hace un GET sobre una clave libre, la toma.
> Correcto

Un ESI hace un SET sobre una clave libre, queda abortado.
> Correcto - Error de Clave no Bloqueada

Un ESI hace un STORE sobre una clave libre, queda abortado.
> Correcto - Error de Clave no Bloqueada

Un ESI hace un GET sobre una clave tomada por otro ESI, queda bloqueado.
> Correcto

Un ESI hace un SET sobre una clave tomada por otro ESI, queda abortado.
> Correcto - Error de Clave no Bloqueada

Un ESI hace un STORE sobre una clave tomada por otro ESI, queda abortado.
> Correcto - Error de Clave no Bloqueada

**Comment by FrancoVentrice** [comment]
Gracias! Me faltaría saber lo de la pausa :)

**Comment by iago64** [comment]
Uh... mil disculpas, no vi esa parte jeje.
La idea es que estén a la espera de las conexiones y ni bien se conecte el primer ESI puedan arrancar a planificar sin tener que hacer nada.
Lo de Play/Pause es mas para frenar cuando ya pasaron cosas para ver el estado general del sistema y no tener que andar poniendo retardos eternos para ver como están las cosas :)

Saludos.-

**Comment by FrancoVentrice** [comment]
Perfecto, mil gracias!
