### ISSUE TITLE
Claves en instancias caídas al revivir

### ISSUE THREAD

**Issue by natoszme** [sisoputnfrba/foro#1119]
Buenas!

De momento tenemos que cuando un esi quiere operar con una clave que se encuentra en una instancia que está caída, se lo aborta y se elimina la clave de la estructura administrativa del coordinador. Entonces si viene otro esi, se le asignará otra instancia que esté viva cuando haga set/store. Por lo tanto sólo una instancia tendría la clave y no habría inconsistencias.

Peeero el tema es que cuando la instancia que se cayó, reviva, va a tener esa clave que el coordinador borró de su estructura administrativa (la va a tener si la bajó a disco con dump/store). Qué nos sugieren? Que cuando reviva se chequee si la clave ya está en otra instancia, y en ese caso que borre su archivo? Que la clave siga igual en la instancia caída y que el coordinador no lo sepa? No eliminar la clave de la estructura administrativa del coordinador? (Esto último iría en contra de la consigna)

Gracias che!

**Comment by iago64** [comment]
Buenas!
Muy buena pregunta!! Lo mas limpio sería, que cuando una instancia reconecta le pregunte al coordinador que claves tenia, y ahi como uds lo borraron / cambiaron en la tabla de claves, simplemente esa clave no le informan a la instancia que la tenia y en todo caso es un archivo que van a tener al pepe en el FS

Saludos.-

**Comment by natoszme** [comment]
Oka, y cuando le decimos cuáles tenía la instancia debería borrar los archivos que ya no le correspondan? Gracias!

**Comment by iago64** [comment]
Si los dejan no pasa nada, ahi son libres de elegir si quieren borrar los archivos o no, ambas opciones estan bien, fijense lo que les lleva menos tiempo ;)

**Comment by natoszme** [comment]
Claro pero si no los borramos, para qué avisarle a la instancia? En ese caso sería no hacer absolutamente nada jajaja (y la instancia se quedaría con esos archivos basura)
