### ISSUE TITLE
instancia-clave Reemplazada

### ISSUE THREAD

**Issue by acerbonimartin** [sisoputnfrba/foro#1120]
hola, mi duda es la siguiente. tengo la clave1 guardada en una instancia. luego se hace un SET de la clave 2, para lo cual se borra al contenido de Clave1 de la instancia.
  En este caso si un ESI hace set o store de esa clave, el ESI debe terminarse. Que pasa si un ESI hace un GET?
  .es como si la clave nunca hubiese existido antes y la vuelvo a generar como si nada? 
  .Tambien debería morir el ESI que hace ese GET? 
  .guardo una lista de Claves borradas para evitar volver a generarlas?
desde ya muchas gracias

**Comment by iago64** [comment]
Buenas buenas!
Vamos por partes asi es mas facil :)
En este caso si un ESI hace set o store de esa clave, el ESI debe terminarse. 
> Correcto, falla porque la clave no existe mas en el sistema
Que pasa si un ESI hace un GET?
> Crea la clave nuevamente :)
.es como si la clave nunca hubiese existido antes y la vuelvo a generar como si nada?
> Tal cual, le volves a correr el algoritmo de distribución y todo, con lo cual puede que se de que hasta caiga en otra instancia distinta
.Tambien debería morir el ESI que hace ese GET?
> No, el GET a lo mucho te bloquea un ESI, pero matarlo no way
.guardo una lista de Claves borradas para evitar volver a generarlas?
> No hace falta, con que tengan las que están en cada instancia (incluso si esta se cae) alcanza, después si reemplazan una la pueden hacer crema y olvidarse de que existió.

Saludos.-

**Comment by acerbonimartin** [comment]
mas claro imposible. gracias, cierro issue
