### ISSUE TITLE
Liberar recursos de ESI usando diccionario

### ISSUE THREAD

**Issue by agusmoles** [sisoputnfrba/foro#1121]
Buenas, para el manejo de las claves que toman los ESIs estoy utilizando un diccionario en que tengo las **claves tomadas** y el **value** es el **char*** **nombre del ESI** y me parecio buena la idea que lo maneje asi.

El problema que tengo ahora es que cuando voy a abortar a un ESI por alguno de los errores posibles, no tengo manera de tener la **clave** a partir del **value**, o sea, a partir del nombre del ESI ya que no hay comando del diccionario de las commons que lo haga. Por esto, no se si esta bien que lo maneje asi...

Estaba pensando en usar el **dictionary_iterator** de las commons pero no tendria manera de saber que ESI es el que estoy buscando de todas formas... pero pense, que utilizando una variable global, antes de entrar al **iterator** la setee para saberlo, y dentro del **closure** ahi sí poder saber y comparar.

Saludos. Gracias!
_EDIT:_ Probe lo del **iterator** y funciono pero quisiera saber si de todas maneras esta bien hacerlo asi o no...

_EDIT2:_ Estaba leyendo lo del **bloquear clave ID** de la consola del planificador y lei en un issue que seria como un **GET** normal, pero por la aclaracion del enunciado:

> ^3: El Planificador empezará con una serie de claves bloqueadas de esta manera.

Que referencia a tal comando, no entiendo si solo se usa el comando para claves que tiene el sistema inicialmente o podria ser para cualquier clave del sistema (incluso que tengan otros ESIs y demas)

**Comment by iago64** [comment]
Buenas buenas!

Vamos por partes:

1.- La implementación de las claves tomadas, pueden hacerlo como mas les guste, eventualmente, el diccionario es la solucion rapida, tambien podrian tener una lista de las commons o lo que uds gusten, no les vamos a complicar la vida con una estructura definida por nosotros para eso.

2.- Si, el bloquear clave es como si un ESI hiciera un GET, porque tienen que seguir el mismo flujo, peeero, como bien observas, esta el caso donde el planificador arranca con claves bloqueadas, eso lo que quiere decir es que vas a tener un ESI-1 o un System que va a tener tomada la clave (vendría a ser como una especie de recursos del sistema) y que en algun momento alguien desde la consola del planificador puede tirarle un desbloquear y sacarte esa clave de la lista de claves tomadas o eventualmente liberar al primer ESI que hizo un GET y se bloqueo :)

3.- El bloquear desde la consola bloquea cualquier clave del sistema sin importar si es una clave que arranca bloqueada o una clave que se cree en medio de la ejecución de un ESI.

Saludos.-

**Comment by agusmoles** [comment]
Bien, con respecto al 3, si por consola se hace un GET de una clave tomada por un ESI distinto al del comando, que debo hacer? Bloquearlo, abortarlo o que?

Y una pregunta mas offtopic es si tengo una lista de ESIS bloqueados esperando un recurso X y el ESI que lo tenia tomado hace un STORE de X. Mando a listos a todos los ESIS o solo al primero que se bloqueo?

Saludos!

**Comment by iago64** [comment]
Buenas!
GET de una clave que ya bloqueo otro = Cola de Bloqueados para la clave, no tenes que darle mas vueltas a eso :)

Respecto a la pregunta offtopic que no es offtopic porque tiene mucho sentido, la respuesta es simple y solo sacas al primero (concepto de cola tal cual deberían explicarlo en algoritmos, _primero que llega primero que sale_)

**Comment by agusmoles** [comment]
Si, me maree con lo primero y dije cualquier cosa jajaja.

Y era como pensaba lo de la cola de bloqueados.

Gracias!

**Comment by agusmoles** [comment]
Abro para una consulta mas...

Cuando desbloqueo el ESI que estaba esperando por un recurso, inmediatamente le asigno el recurso? Porque no va a volver a ejecutar la sentencia que contenia el **GET** de tal recurso porque ya lo hizo (y se **bloqueo**)

Porque sino habria que ver de que forma comunicarse para que vuelva a leerla y mandarla.

Saludos!

**Comment by iago64** [comment]
@agusmoles Si señor, por eso es que desbloqueas al primero ;)
Tenes la alternativa de no incrementar el contador de linea hasta que no tome el recurso y que vuelva a ejecutar el GET, pero, si se lo asignas de una y asumis que el GET ya fue ejecutado esta todo ok :)

**Comment by agusmoles** [comment]
Creo que la ultima... jajaja

Lo que hacemos en nuestro TP es que si un **ESI** hace un **GET** de una **clave tomada**, el Planificador avisa al Coordinador de esto (enviandole un 0 por "error" de operacion o un 1 si todo bien) y, si es un 0 el Coordinador no le envia el mensaje (un **OPOK**) al **ESI** que éste espera para seguir ejecutando...

La cosa es que mas tarde ese **ESI** que tenia la **clave tomada** puede hacer un **STORE** y el problema esta en como le avisamos al Coordinador en un momento X (porque no sabes cuando va a venir ese STORE) que le envie al ESI bloqueado (el cual el Planificador puede saber cual es y eso) el **OPOK**?

Estaba pensando que siempre despues un **STORE** se verifique entre Planificador-Coordinador si justamente hay que mandarle a un **ESI** bloqueado un **OPOK** antes de seguir con el curso algoritmico del programa y solucionaria el problema. Pero en el caso del desbloquear por **consola**?

Saludos. Disculpa por andar jodiendo con textos tan largos jaja

**Comment by iago64** [comment]
Buenas Buenas!
Se me complico seguirte un poco (estoy muy a mil con el laburo :( ), pero en el caso de la ejecución va más o menos bien la idea (es rebuscada pero puede andar) pero con la complicación que planteas de la consola, no te seria mas facil, que en lugar de frenar todo en el planificador, no podrías devolverle el error de clave ya bloqueada al ESI y que sea este que le avise al planificador que la clave estaba tomada? (Te lo pregunto porque la vuelta puede agregarte una cantidad de laburo bastante grande)

Saludos.-

**Comment by agusmoles** [comment]
No entendi lo que me planteaste. El planificador ya sabe que esta tomada porque justamente él se encarga de verificar eso en los GET/STORE. No entiendo como resolveria el problema de "descolgar" al ESI bloquedado (que se quedo esperando un **OPOK** luego del GET)

Saludos

**Comment by agusmoles** [comment]
Mientras tanto, intente hacer lo que te mencione y parece funcionar (sin usar lo de la consola que, como decis, va a ser un laburo creo) pero en distintos momentos del programa, el **dictionary_get()** me devuelve distintas cosas...

Hice un ESI que hace un GET de una clave, un monton de SET (para que me de tiempo de ejecutar el otro y se bloquee) y despues el STORE de esa clave. Entonces, ejecuto el ESI 0, toma la clave y arranca a hacer los SET... Ejecuto el ESI 1, como es SJF-CD con estimacion 0, desalojo al otro y se bloquea porque hace el GET de la misma clave... Termina de ejecutar el ESI 1 y pasa lo siguiente:

Aca cuando lo desbloqueo, se la asigno ya la clave y el **printf** me muestra bien el nombre del ESI como para hacer el put (lo probe con el **dictionary_get()** despues del **dictionary_put()** e imprime lo mismo)
![sin titulo](https://user-images.githubusercontent.com/28370654/41114321-7a352266-6a5a-11e8-9a27-a2ba2f066d82.png)

Pero despues cuando el ESI 1 termina de hacer todos los SET y quiere hacer el STORE de la clave, el **dictionary_get()** devuelve unos simbolos raros y el 1...
![sin titulo1](https://user-images.githubusercontent.com/28370654/41114322-7a5f89d4-6a5a-11e8-9434-4b374e0a762b.png)

El codigo es:
```
case 2: //OPERACION STORE
				if (dictionary_has_key(diccionarioClaves, clave)) {
					sem_wait(&mutexDiccionarioClaves);
					char* IDEsiQueTieneLaClaveTomada = dictionary_get(diccionarioClaves, clave);
					sem_post(&mutexDiccionarioClaves);

					printf(ANSI_COLOR_BOLDWHITE"El que la quiere storear es %s y el que la tiene es %s\n"ANSI_COLOR_BOLDWHITE, nombreESI, IDEsiQueTieneLaClaveTomada);

					if(strcmp(nombreESI, IDEsiQueTieneLaClaveTomada) == 0) {	// SI EL QUE QUIERE STOREAR ES EL MISMO QUE LA TIENE STOREADA, OK.
						sem_wait(&mutexDiccionarioClaves);
						dictionary_remove(diccionarioClaves, clave);
						sem_post(&mutexDiccionarioClaves);
						log_info(logger, ANSI_COLOR_BOLDCYAN"Se removio la clave %s tomada por el %s"ANSI_COLOR_RESET, clave, nombreESI);

						informarAlCoordinador(socket, 1); // 1 PORQUE SALIO BIEN

						// DESBLOQUEO AL ESI QUE ESTA ESPERANDO POR ESTE RECURSO, SI LO HUBIESE

						cliente* ESIDesbloqueado;
						int* codigoOP = malloc(sizeof(int));
						int* IDESIADesbloquear = malloc(sizeof(int));

						ESIDesbloqueado = desbloquearESI(clave);

						if (ESIDesbloqueado != NULL) {
							*codigoOP = 1;
							*IDESIADesbloquear = ESIDesbloqueado->identificadorESI;

							char* nombreESIDesbloqueado = malloc(7);

							strcpy(nombreESIDesbloqueado, "ESI ");

							char* IDESI = string_itoa(ESIDesbloqueado->identificadorESI);

							strcat(nombreESIDesbloqueado, IDESI);

							printf(ANSI_COLOR_BOLDWHITE"NOMBRE ESI DESBLOQUEADO: %s\n\n\n"ANSI_COLOR_RESET, nombreESIDesbloqueado);

							free(IDESI);

							sem_wait(&mutexDiccionarioClaves);
							dictionary_put(diccionarioClaves, clave, nombreESIDesbloqueado);
							sem_post(&mutexDiccionarioClaves);

							free(nombreESIDesbloqueado);

							if(send(socket, codigoOP, sizeof(int), 0) < 0) {
								_exit_with_error("No se pudo enviar el codigo de OP para desbloquear ESI");
							}

							if(send(socket, IDESIADesbloquear, sizeof(int), 0) < 0) {
								_exit_with_error("No se pudo enviar el ID de ESI al Coordinador para desbloquearlo");
							}
						} else {
							*codigoOP = 0;

							if(send(socket, codigoOP, sizeof(int), 0) < 0) {
								_exit_with_error("No se pudo enviar el codigo de OP para desbloquear ESI");
							}
						}

						free(codigoOP);
						free(IDESIADesbloquear);

					}
```

Y el **desbloquearESI()**:

```
cliente* desbloquearESI(char* clave) {
	cliente* primerESIBloqueadoEsperandoPorClave;

	for(int i=0; i<list_size(bloqueados); i++) {
		primerESIBloqueadoEsperandoPorClave = list_get(bloqueados, i);

		if (strcmp(primerESIBloqueadoEsperandoPorClave->recursoSolicitado, clave) == 0) {
			strcpy(primerESIBloqueadoEsperandoPorClave->recursoSolicitado, "");		// NO TIENE RECURSO PEDIDO AHORA...

			sem_wait(&mutexBloqueados);
			list_remove(bloqueados, i);		// LO SACO DE BLOQUEADOS AL ESI
			sem_post(&mutexBloqueados);

			sem_wait(&mutexListos);
			list_add(listos, primerESIBloqueadoEsperandoPorClave);	// LO MANDO A LISTOS
			sem_post(&mutexListos);

			log_info(logger, ANSI_COLOR_BOLDCYAN"Se desbloqueo al ESI %d ya que se libero la clave %s"ANSI_COLOR_RESET, primerESIBloqueadoEsperandoPorClave->identificadorESI, clave);

			return primerESIBloqueadoEsperandoPorClave;
		}
	}
	return NULL;
}
```

En serio disculpa que te moleste, si no podes ver tantas cosas decime que trato de arreglarmela

Saludos!

**Comment by iago64** [comment]
@agusmoles Ni se te ocurra pedirme disculpas por tener consultas, para algo estamos los ayudantes :)
Ahora bien, en tu codigo veo que estas usando strcmp, por esas casualidades, estas asegurandote de poner el \0 al final del nombre del ESI en el diccionario? Ya que si no pones el \0 el strcmp se te pasa de gira hasta que encuentre un \0 y eso puede hacer que te imprima caracteres no legibles y eventualmente no va a coincidir con la cadena que tenes actualmente.

La opción segura sería asignarle un ID de tipo int a cada ESI y manejarlo con eso.

Saludos.-

**Comment by agusmoles** [comment]
Muchas gracias, el problema estaba en lo que puse en el EDIT de arriba. Y no lo manejaba con enteros porque cuando queria asignarle a una clave la ID del Sistema que era -1, me la imprimia como '0'. Y ahora entiendo que debio haber sido por lo mismo, el **free()**...

Ahora, cuando remuevo una clave, se libera la memoria? O habria que usar **remove_and_destroy()** e inventarse una funcion que lo haga?

Saludos

**Comment by iago64** [comment]
Buenas!
El **diccionary_get()** te devuelve la referencia y no tenes que hacer malloc, eventualmente también el **diccionary_remove()** tambien te devuelve el valor y no necesitas hacer un destroy dentro del diccionario, solo tenes que acordarte de hacerle un free al valor que te devuelve cuando no lo necesites mas :)

Saludos.-

**Comment by agusmoles** [comment]
Ah claro tenes razon! Muchas gracias che. Cualquier cosa vuelvo a abrir o creo un issue. 

Suerte con el laburo!

**Comment by agusmoles** [comment]
Buenas, al final me paso lo que pusee aca con lo del tema de la consola:

> La cosa es que mas tarde ese ESI que tenia la clave tomada puede hacer un STORE y el problema esta en como le avisamos al Coordinador en un momento X (porque no sabes cuando va a venir ese STORE) que le envie al ESI bloqueado (el cual el Planificador puede saber cual es y eso) el OPOK?
> 
> Estaba pensando que siempre despues un STORE se verifique entre Planificador-Coordinador si justamente hay que mandarle a un ESI bloqueado un OPOK antes de seguir con el curso algoritmico del programa y solucionaria el problema. Pero en el caso del desbloquear por consola?

No tengo ni idea como solucionarlo, deberia cambiar toda la idea no? Porque nunca sabes cuando te va a llegar ese comando por consola para recibir algo en el Coordinador...

Saludos

**Comment by iago64** [comment]
@agusmoles es una situación medio dificil de ver en un issue y sin ver código, que te parece si lo charlan mañana con el ayudante que los evalue en el check?. 
Si solo tienen el problema de desbloquear les "falta" la prueba 4 nomas y es algo que capaz mañana en 5 minutos en el labo lo resuelven y no tienen la tarea titanica de cambiar todo. Porque a priori por aca mi respuesta sería, cambiar la implementación pero no quiero matarlos con tanto laburo de rehacer todo :(

Saludos.-
