### ISSUE TITLE
Problema con send y recv entre coordinador e instancia

### ISSUE THREAD

**Issue by leandroszikora** [sisoputnfrba/foro#1125]
Buenas estamos teniendo un problema con lo que envía el coordinador a la instancia. Tratamos de entender lo que pasa pero no encontramos el error.
![img-20180606-wa0043](https://user-images.githubusercontent.com/31076665/41068664-ecf44a1a-69c0-11e8-9475-3137e60aaea8.jpg)
![img-20180606-wa0042](https://user-images.githubusercontent.com/31076665/41068674-f977c4b0-69c0-11e8-8847-a03d4ef64a80.jpg)
El caso es que cuando se ejecuta ese código la instancia no recibe nada pero si el tamaño de lo que le estamos mandando.
![img-20180606-wa0044](https://user-images.githubusercontent.com/31076665/41068697-1a501534-69c1-11e8-8f36-e2eee78f1e60.jpg)
¿Alguno sabría que estamos haciendo mal?
Muchas gracias.

**Comment by iago64** [comment]
Buenas buenas?!
Por esas casualidades, le pegaste una leida al [man de send()](http://man7.org/linux/man-pages/man2/sendmsg.2.html) ?

Puntualmente la pregunta va por el ultimo parametro del send() que tiene MSG_WAITALL, que es un parámetro de la funcion recv(), capaz, por ahí empieza a sonarte el problema, ante la duda generalmente esos flags se setean en NULL.

Saludos.-

**Comment by leandroszikora** [comment]
Uh si, no nos dimos cuenta. Mil gracias!
