### ISSUE TITLE
Problema al compilar en la vm server

### ISSUE THREAD

**Issue by natoszme** [sisoputnfrba/foro#1127]
Buenas! Cómo va?
Preparando las cosas para el checkpoint del sábado, empezamos a probar el tp en la vm server.
Instalamos todo lo necesario (commons, parsi, readline) pero cuando vamos a compilar nuestras commons, aparece lo siguiente:

![1](https://user-images.githubusercontent.com/14940818/41077536-9205f450-69ed-11e8-9325-756be738cafc.jpg)

Nos llama la atención porque al hacer make clean, make en la consola de Lubuntu, compila lo más bien pero al hacerlo en la vm server no. No **debería** ser lo mismo, por más que el [makefile](https://github.com/sisoputnfrba/tp-2018-1c-youKnowNothing/blob/master/our-commons/Debug/makefile) haya sido generado con Eclipse?

Nuestros ayudantes nos tiraron el centro de que al ser uno generado por Eclipse, podría faltar incluir los .c. El tema es que no vemos por qué debería variar el makefile. Acaso nos faltan instalar más cosas en la server?

Mil gracias!

**Comment by iago64** [comment]
Buenas buenas!
Pregunta rapida, en objects.mk te aparecen todos los .c y .h que tienen en sus commons?
Porque fijate que de lo que se queja gcc es que no tiene input files 

Saludos.-

**Comment by natoszme** [comment]
En los sources.mk y objects.mk (usamos los mismos en ambas vms) nos aparecen los .c ni h. Lo que si aparece en el sources es
> # Every subdirectory with source files must be described here

SUBDIRS := \

our-commons/messages \

our-commons/sockets \

our-commons/tads \

que son los directorios que tienen .c's y h's. Pero en objects.mk esto es todo lo que figura
> USER_OBJS :=


LIBS :=

(Y es lo que nos da Eclipse)

**Comment by iago64** [comment]
Buenas buenas!
Me tome el atrevimiento de bajarme el repo (el branch master) de su grupo y si ejecuto el make que tienen en la carpeta de sus commons me genera el objeto (aclaro que es una vm limpia con las commons, readline y el parsi)

![image](https://user-images.githubusercontent.com/1622109/41132140-b1e358b4-6a95-11e8-9e02-fa7bb3851e01.png)

Saludos.-

**Comment by natoszme** [comment]
Jeje si porque lo acabo de solucionar. Había archivos en el gitignore que eran necesarios. Aprovecho para agregar un par de dudas:

Primero: la regla .PHONY: all no está funcionando. No me está quedando otra que cambiar los nombres de las reglas para que coincidan con el de las carpetas con los mismas nombres. Simplemente me tira no rule to make all o similar (si uso .phony e iguales nombres).

Otra: hay una línea en el [makefile](https://github.com/sisoputnfrba/tp-2018-1c-youKnowNothing/blob/master/makefile) que hace el export ld library path... Si la corro en el makefile como está ahora, cuando voy a correr el coordinador me tira que no encuentra nuestras commons. En cambio si escribo esa línea en la consola, corro el coordinador lo más bien. Es como si el makefile no la estaría ejecutando. Fija idea? Gracias!

**Comment by iago64** [comment]
Bueno, lo de que no te levante el export es normal y es puntualmente porque cuando ejecutan el make el export vive solamente durante la ejecución del script.

Dicho sea de paso lo acabo de ver en detalle y no hace falta que usen sudo para instalar las commons :wink:

La solución simple a tu problema puede ser el hacer crema la parte de makefile y dejarlo como un script de bash comun (lease que te compile TODO de una _compilarTP_ seria un buen nombre (?)) y si lo ejecutas como . ./compilarTP te deja el valor de LD_LIBRARY_PATH seteado (como opción para tener todo)

La otra solución un poquito mas desacoplada seria que simplemente hagan un script aparte con el export y lo corran tambien con el . ./hacerExportLibraryPath y listo.

Saludos.-

**Comment by natoszme** [comment]
Muy claro lo del export, lo paso a un script y te cuento. Alguna idea de lo del phony? :unicorn_face:

**Comment by mgarciaisaia** [comment]
Las variables de entorno que `export`ás se `export`an durante la sesión de shell actual.

Cuando hacés un script y lo ejecutás haciendo `./miscript.sh`, estás ejecutando un nuevo proceso `bash` o `sh` (es decir, _una nueva shell_), y corriendo el script dentro de ese otro proceso. Entonces el `export` se ejecuta en esa otra sesión, y cuando volvés a tu shell principal ya no hizo efecto.

La forma de "solucionar" esto es con el builtin `.` (ver con `help .`). `.` (que también está `alias`eado a `source`) es un builtin (es decir, una función de la shell) que _ejecuta un script en la shell actual_. Es decir, en vez de _crear una shell nueva_ y correr el script ahí, corre el script en la shell que llamó a `.`. De esa manera, si en vez de `./miscript.sh` ejecutás `. miscript.sh` (que es lo mismo que `. ./miscript.sh`), el `export` va a afectar a la sesión actual - lo que andabas buscando.


Por el tema del `.phony`, preferiría ver todo el log que hay cuando hacen un `make` (después de un `make clean`), pero estimo que estarán ejecutando las reglas default de `make` en lugar de las que tienen en el Makefile. `make` tiene algunos defaults (por ejemplo, sabe que para buildear un archivo .c tiene que hacer `gcc archivo.c -o archivo`), y cosas así. Cuando hacen `make mi/directorio`, encontrará los archivos de ahí y aplicará el default, calculo. Pero sin un log, es todo conjetura y chamuyo.

De todos modos, esto de _el makefile no me anda así que le hardcodeo cualquier valor hasta que parezca que me está dando bola_ se llama, técnicamente, _workaround_: esquivo un problema en lugar de solucionarlo.

Hagan workarounds la noche antes de la entrega, pero no antes. Si hoy bailan alrededor del problema, dejan chanchadas en el código, y la noche anterior a la entrega se chocan las chanchadas y ya no hay margen de maniobra. Aprovechen hoy que todavía hay tiempo, y solucionen posta.

Un buen primer paso es mirar en los proyectos que andan bien a ver qué contenido tienen esos archivos (el makefile, y los subdir/objects.mk), a ver qué es lo que está mal en los de ustedes. Vale crear un proyecto nuevo desde eclipse para ver cómo andaría bien, también.

¡Salute!

**Comment by natoszme** [comment]
Buenas! Antes de reveer lo del .phony, me puse a ver lo que me decías del source. 

Cambié el [makefile](https://github.com/sisoputnfrba/tp-2018-1c-youKnowNothing/blob/master/makefile) para que incluya el `.`, y nada. Si corro el [script](https://github.com/sisoputnfrba/tp-2018-1c-youKnowNothing/blob/master/our-commons/Debug/makeOurCommonsUsable.sh) desde afuera, con la misma línea que está ahí, va bien. Pero desde el makefile, nop. Qué onda?

Perdón por tantas dudas sobre lo mismo pero esto de crear makefiles es nuevo para mi jeje

**Comment by mgarciaisaia** [comment]
Pasa que si _desde el Makefile_ ejecutás el script, `make` ya es un proceso aparte de tu consola, entonces eso va a ejecutar _en otro shell_ sí o sí.

Si querés hacer ambas cosas de una, podrías/deberías hacer un script que `export`e la variable y llame a `make` - y `source`ar ese script.

**Comment by natoszme** [comment]
Sería algo así como [esto](https://github.com/sisoputnfrba/tp-2018-1c-youKnowNothing/blob/master/raiseRedistinto.sh)? Sigue mostrando vacía la variable de entorno jeje

**Comment by iago64** [comment]
Proba ejecutando . ./raiseRedistinto.sh y decime si te sigue mostrando la variable de entorno vacía :)

**Comment by natoszme** [comment]
@mgarciaisaia en cuanto a la parte del .phony, si yo le saco la terminacion de Rule a las reglas que se ven acá:
`.PHONY: default clean
`
`
default: so-commons-library our-commonsRule parsi readline coordinadorRule planificadorRule instanciaRule esiRule`

y borro, para probar, las reglas so-commons-library, parsi, y readline, al hacer make me dice
`make: Nothing to be done for 'default'`. Por eso digo que es como si no estuviera tomando el .phony

**Comment by mgarciaisaia** [comment]
https://faq.utnso.com/errores-eclipse or didn't happen.

Posta, pasanos todo el log, y lo que veas relevante del makefile, si no va a ser imposible entender el problema  :/

**Comment by natoszme** [comment]
El log no sería lo que aparece cuando hago make? Si es eso, eso es todo lo que figura

**Comment by mgarciaisaia** [comment]
Che, releí esto varias veces y no entiendo el problema que estás teniendo :/

Me cloné el repo (_rait nau_, en el commit [`e1465b39bfbdf51b58777b913391c7fc6aa06ff9`](https://github.com/sisoputnfrba/tp-2018-1c-youKnowNothing/tree/e1465b39bfbdf51b58777b913391c7fc6aa06ff9)), y al correr `make` en la raíz del repo parece funcionar todo. Primero me falló al clonar por un problema de includes, pero era porque el TP de ustedes hay que clonarlo dentro de un directorio `workspace` - hice eso y compiló joya.

No estoy entendiendo qué es lo que estás probando, y que error te está devolviendo :/

**Comment by natoszme** [comment]
El problema es que el Phony no está funcionando. Ahora si funciona, porque fijate que las reglas se llaman our-commondRule. Pero si le sacas el rule no las toma! (O sea, anda pero parcheado. Que es el que me decías que no está bueno hacer cuando tenés el tiempo para corregirlo)

**Comment by mgarciaisaia** [comment]
Probé de [renombrar la regla del coordinador](https://gist.github.com/mgarciaisaia/f89770c5bb022a8044f201d50a089489), y siguió andando, che.

Si no vemos qué `Makefile` usás, qué comando corrés, y qué error te da, no te puedo ayudar, che :/

Pasate el sábado por soporte, si no, y miralo con quien esté.

¡Salute!

**Comment by natoszme** [comment]
@mgarciaisaia sisi fijate que más arriba indiqué el mismo makefile al qué haces referencia vos ahora, y que el log del makefile surge al hacer `make`. Por otro lado, puede ser que hayas hecho make esta última vez que me decís que anduvo y que te haya funcionado porque si no hiciste un make clean antes, los archivos del coordinador siguen ahí, porque lo que podrías no haber corrido la regla coordinador

Igual mil gracias, cualquier cosa lo veo en soporte. Abrazo!

**Comment by iago64** [comment]
@natoszme Que tal? al final esto lo pudieron resolver en soporte? el issue se puede cerrar?

**Comment by iago64** [comment]
Cerramos el issue por inactividad, cualquier cosa lo vuelven a abrir :)
