### ISSUE TITLE
Problema de desconexión de internet en vm's

### ISSUE THREAD

**Issue by natoszme** [sisoputnfrba/foro#1128]
Buenas!

Estoy teniendo el siguiente problema con las conexiones de las vms. Después de dejar las vm's abiertas por mucho tiempo (léase 8hs aprox.) prendidas (aunque no en uso continuo) dejo de tener internet en las mismas.
Cuando reinicio, me sale
> a start job is running for raise network interfaces

![2](https://user-images.githubusercontent.com/14940818/41078587-18afd970-69f4-11e8-8e2b-1023f6e17398.jpg)

(La captura es de la vm server, pero me pasa también en Lubuntu)

Si paso de Adaptador puente a NAT en la configuración de red de Virtual Box, esto se soluciona y puedo seguir pulleando/pusheando. El tema es que no vamos a poder probar el tp.

Alguna idea? Gracias!

**Comment by iago64** [comment]
Buenas buenas?!
Una pregunta rapida porque estoy viajando y se me complica sacar la notebook en el tren en hora pico.
En algun momento mientras estuvo suspendida la vm cambiaste de red wifi?
Porque generalmente lo que pasa cuando esta en modo bridge y cambias de red es que virtual box queda medio salame y no entiende el cambio de red y no hace el reconnect.
Con nat no te pasa porque ahi es tu maquina la que hace las veces de router para la vm y ahi es tu pc siempre el access point.

Saludos.-

**Comment by mgarciaisaia** [comment]
La red en modo bridge la maneja el router al que está conectada tu computadora física, así que está un poco fuera de nuestro control. Podes revisar tu red, pero suele ser más fácil convivir con ello o cambiar el tipo de conexión.

Para convivir mejor, el comando `ifconfig` te lista las interfaces de red de la VM que están con una conexión activa (si le agregás el parámetro `-a` te muestra las inactivas, también). Con eso deberías encontrar una interfaz que, en las VMs nuevas, se llama algo como `en0pos2` o cosa parecida (pueden cambiar los números, y puede que no dijera `pos` si no otra cosa).

Teniendo ese nombre, cuando te quedas sin red hacé `sudo ifdown en0pos2` para desconectar la placa, y después `sudo ifup en0pos2` para que vuelva a conectarse, negocie una IP nueva con el router, y sarasa. Y con eso deberías salir andando.

Si no, está pasando algo más gede, que habría que mirar en la red probablemente.

Pero probá y fijate.

**Comment by natoszme** [comment]
@iago64 no cambié de red pero es posible que se haya conectado y desconectado de la misma.

@mgarciaisaia me sirvió lo de ifconfig, mil gracias.

Se ve que es algo raro de la red, porque hoy probé con el internet del celu y fue bien.

Gracias! Si no hay nada más que decir, se puede cerrar

**Comment by iago64** [comment]
Le damos cierre al tema y cualquier cosa lo reabren :)
