### ISSUE TITLE
Dudas con list_map

### ISSUE THREAD

**Issue by agnmeinardo** [sisoputnfrba/foro#1129]
Buenas,

Me está costando un poco entender cómo funciona list_map de las commons. 
Tengo la lista listaClaves y mi intención es mapear una función desbloquearClavesSegundID(int id). Esta función verifica cada elemento de la lista listaClaves: si la clave está tomada por ID id, entonces la desbloqueo, si no, sigue de largo al siguiente elemento.
Mi consulta es: poniendo la siguiente linea de código ( listaClaves = list_map(listaClaves,desbloquearClavesSegunID(id));), el list_map por sí mismo agarra el primer elemento de la lista, le aplica la función, luego pasa al segundo, aplica la función, y así sucesivamente? O tendría que aplicarle un list_iterate (como vi en este issue https://github.com/sisoputnfrba/foro/issues/64)? Además de eso, el id tendría que ser un puntero, no?

Saludos.

**Comment by tferraro** [comment]
Buenas!

Por lo general, las funciones de orden superior tienen este funcionamiento:
**map**: Según la funcion que le pases, te transforma o "mapea" cada elemento de la lista al resultado de la funcion y te devuelve un listado de elementos transformados sin tocar los elementos originales.
**forEach**: Ejecuta la funcion que le pases N cantidad de veces y en cada una le pasa por parámetro un elemento.
**filter**: Por cada elemento, le pasa por parámetro a la función y la misma devuelve un booleano. Entonces, con todos los elementos que devolvieron true, te devuelve una lista sin tocar los originales.

Ahora, lo que vos describís que querés hacer, es más un forEach que un map, no te parece? El forEach, en el caso de las commons, es list_iterate, como bien dijiste.

**Comment by agnmeinardo** [comment]
Buenísimo! Muchas gracias. Era una pregunta simple, pero me mareó un poco.

**Comment by mgarciaisaia** [comment]
Si querés repasar un poco más qué hacen las distintas funciones de orden superior que suelen haber, podés hacerte [este capítulo de Mumuki](https://mumuki.io/lessons/189-programacion-funcional-aplicacion-parcial-y-orden-superior). Habla de Haskell, por lo que no aplica directamente a las commons, pero tienen  _muchísimo_ en común - lo suficiente como para que valga la pena, creo yo.

¡Éxitos!
