### ISSUE TITLE
Consulta por necesidad de hilos para conexiones de instancias.

### ISSUE THREAD

**Issue by Jaugustopose** [sisoputnfrba/foro#1130]
Buenas noches chicos,

Les queríamos comentar una duda que nos surgió producto de leer la inicialización del coordinador. En esta, se menciona que por cada conexión entrante, se deberá abrir un hilo de escucha.

Ahora bien, entendemos que cada ESI deberá tener su propio hilo para ejecutar, pero no así las INSTANCIAS.

Al querer escribir en una instancia, solo voy a enviar información a UNA Y SOLO UNA, es decir que una vez identificada la instancia a la que debo comunicarle algo (seleccionada según algoritmo de distribución o si esa instancia ya tenía la clave), solo me comunicaré en ese intervalo de tiempo con ella, y no necesitaría escuchar a las demás al menos en ese instante.

Con esto, entendemos que el tema de las instancias podría solucionarse escuchando con un select e ingresando cada instancia dentro de una bolsa (fd_set).

¿Estaría muy mal esta implementación? ¿O nos estamos salteando algún caso en particular donde sí o sí necesitamos hilos para las conexiones de instancias? Se nos ocurre que con el dump podría ser necesario, pero podría realizarse de a una instancia a la vez.

**Comment by iago64** [comment]
Buenas buenas!
Justamente el DUMP como bien decis es el caso que hace que tengan que tener 1 hilo por cada conexión, ya que si manejan las instancias con un solo hilo no van a ser compactaciones en paralelo si no en serie (y no es la idea del TP).
Por otra parte, el enunciado pide explícitamente que se tenga un hilo por cada conexión ya que la idea es que apliquen un poco lo que vieron en la teoría de sincronización (_Spoiler_ ES una pregunta de coloquio generalmente como resolvieron la sincro y por que ;)).

Saludos.-

**Comment by LeaTex** [comment]
Ojo de no confundir "dump" con "compactación".

Lo que se ejecuta en paralelo en todas las instancias al mismo tiempo es la compactación.

**Comment by Jaugustopose** [comment]
Si, volé por la arbolada diciendo dump. Me refería a la compactación.

Gracias y cierro.
