### ISSUE TITLE
Observación sobre estimación esperada de ESI_Largo en Prueba 4

### ISSUE THREAD

**Issue by JuanQP** [sisoputnfrba/foro#1131]
Hola!

Estaba leyendo el apartado de pruebas de este checkpoint, en particular la prueba 4 y en la sección de *Resultados Esperados* dice:

> Los valores de las estimaciones deberán ser 1 para ESI_MultiClave y **0.5 para ESI_Largo**

Para el caso de ESI_MultiClave es correcto que sea `1` la única estimación realizada, ya que ejecutó con éxito 2 instrucciones, y al querer ejecutar la 3er instrucción, se bloqueó [según indica su script](https://github.com/sisoputnfrba/Pruebas-ESI/blob/master/ESI_MultiClave). Como la estimación inicial es 0, y el alfa para la última ráfaga es de 0.5, es fácil darse cuenta que la próxima estimación es `2 * 0.5 = 1`

Pero en el caso de ESI_Largo, [según su script](https://github.com/sisoputnfrba/Pruebas-ESI/blob/master/ESI_Largo), se bloquea en la primer instrucción, por lo que **no llegó a ejecutar ninguna instrucción**. Si este es el caso, entonces el valor de la próxima estimación debería ser `0` y no `0.5` como espera la Prueba 4. Debería dar `0.5` si hubiese ejecutado al menos una instrucción bien, pero no es el caso.

¿Es esto correcto?

Muchas gracias, saludos :slightly_smiling_face:

**Comment by ricardoAguirreSanchez** [comment]
Consulta bonus: nosotros tuvimos la duda de si un esi hace 3 sentencias y en la 3• se bloquea, esa cuenta como sentencia hecha, eso fue algo que nos aclararon un sábado que fuimos a consultarlo.

Saludos

**Comment by JuanQP** [comment]
El problema con eso que contás, es que si la instrucción que *termina bloqueando* un proceso contara, entonces los valores esperados deberían ser:

* ESI_MultiClave: `1.5` (3 instrucciones contando la que bloqueó)
* ESI_Largo: `0.5` (1 instrucción contando la que bloqueó)

Pero, si la instrucción que bloquea **no contara** (que eso es lo que dice la presentación del TP), entonces se da la situación que mencioné al principio: 

* ESI_MultiClave: `1` (2 instrucciones exitosas)
* ESI_Largo: `0` (0 instrucciones exitosas)

Fijate que lo que espera la Prueba 4, **no es ninguno de estos dos casos**, por eso hice la pregunta, pero en principio lo hice para que cuente las instrucciones exitosas ya que eso era lo que estaba mencionado en la presentación del TP :sweat_smile:

**Comment by afilgueira** [comment]
Si, es cierto. Ahí está corregido, gracias por la observación.
Toda instrucción que se ejecuta, cuenta. Si se ejecuta dos veces (porque se bloqueo y se vuelve a ejecutar) cuenta dos veces. Sin esto, el HRRN no anda (pregunta de coloquio: explicar porqué).

Saludos!

**Comment by agusmoles** [comment]
Hola! Una consulta re basica pero prefiero que se me aclare antes que quedarme con la duda...

La **estimacion de la rafaga anterior/actual** se iguala a la **estimacion de la proxima rafaga** cuando el ESI se **bloquea** o **desaloja** (en el caso de Con Desalojo) nada mas no?

Saludos!

**Comment by natoszme** [comment]
@afilgueira me llamó la atención el tema de la doble ejecución de una sentencia del esi. La verdad lo tenemos codeado así, pero me puse a buscar y no lo encuentro en el enunciado ni en issues cerrados. Dónde está propuesto que sea así? Sólo por curiosidad. Gracias!

**Comment by afilgueira** [comment]
@agusmoles no entendí la pregunta (sobre todo la parte de igualar). Gran momento para abrir otro issue con el tema específico.

@natoszme https://sisoputnfrba.gitbook.io/re-distinto/coordinador (la nota 11, abajo)

Saludos!

**Comment by JuanQP** [comment]
No había visto esa aclaración antes, no esperaba encontrarla ahí cuando es el Planificador el que se "queda" con ese dato

Adriano, muchas gracias por la aclaración 😋👌

Cierro el issue, considero mi inquietud respondida

**Comment by JuanQP** [comment]
Vuelvo a molestar, me parece que faltó algo en la observación :sweat_smile: 

El orden de ejecución esperado en la Prueba 4 es este:

1. Ejecutar el ESI_MultiClave y esperar que se bloquee. *(Ejecuta 3 instrucciones)*
2. Detener la planificación. *(Nadie entra a ejecución)*
3. Iniciar el ESI_Largo. *(Como la planificación está detenida, debería quedarse en la cola de listos, no ejecutó nada todavía)*
4. Desbloquear la clave “futbol:messi”. *(En este punto, el MultiClave se desbloquea, ya que es el único esperando esa clave, pero **no** pasa a ejecución porque la planificación está detenida)*
5. Reanudar la planificación desde la consola del coordinador. *(Como la clave no está bloqueada, ESI_Largo **debería ejecutar todo su script de una, no se debería bloquear en la primer instrucción**)*

Por lo cual, corríjanme si estoy diciendo una burrada, pero los valores finales deberían ser:

* ESI_MultiClave: `1.5` (ejecutó 3 instrucciones contando la que lo bloqueó)
* ESI_Largo: `0` (ya que pudo ejecutar todo de una)

**Comment by ricardoAguirreSanchez** [comment]
Me sumo a la misma duda, inicialmente pensábamos que el comando desbloquear solo  sacapa al primer esi bloqueado y lo manda a listo, claramente para que se den los resultados del test 3 , además de sacar al esi bloqueado lo que hace es "liberar " la clave de quien lo tomara, así es la única manera de que luego ambos esos puedan finalizar, llevando esa idea al test4, resulta en lo que vos decís, el esi_largo no se llegaría a bloquear, ya que estaba en listo y luego cuando el sistema continúa pasa a ejecutar sin parar.

En fin, tenemos la misma duda.

**Comment by iago64** [comment]
Muchachos, efectivamente el desbloquear no libera el recurso, fue un pifie cuando escribimos las pruebas para el check, peeeero lo que **si deberia pasar** es que empiece a ejecutar el ESI_Largo y que se bloquee cuando haga el GET y ahi le de paso al ESI_MultiClave.

Ahora lo cambio en el documento de pruebas :)

Saludos.-

**Comment by JuanQP** [comment]
Ahí revisé el documento, se cambió el orden de las actividades.

Igual una consulta: si la planificación está detenida, por qué se bloquea ESI Largo? Al agregarlo no debería haber quedado en la cola de listos?

**Comment by iago64** [comment]
Si, pero fijate que reanudas la planificación en el punto 5 :)

**Comment by iago64** [comment]
@JuanQP, que tal? 

Justamente deberían ejecutar de un tirón ESI_Largo y después retomar ESI_MultiClave, el primer punto donde dice que primero que ejecuta es el ESI_MultiClave y despues el ESI_Largo deberiamos haberlo sacado pero se nos paso en la revision, ahi ya esta ajustado.

Saludos.-

**Comment by JuanQP** [comment]
Perfecto, entonces el estado final va a ser `1.5` (3 instrucciones contando el bloqueo) para ESI_MultiClave y ESI_Largo como se ejecuta de un tirón, queda en `0`.

Muchas gracias!
