### ISSUE TITLE
Distribución con key excplicit

### ISSUE THREAD

**Issue by natoszme** [sisoputnfrba/foro#1133]
Buenas! Creo este issue a pedido de @iago64, porque en soporte surgió la duda del ejemplo que está dado con las 26 letras de abecedario. En ese caso, se incluye la ñ, porque sin ella tiene 25. Me pidió que levante este issue para aclarar que ninguna de las pruebas va a tener ñ, para que nos despreocupemos.

Algo que agregar @iago64?

**Comment by iago64** [comment]
Buenas buenas! 
Mil gracias por abrir el issue, porque necesitaba refrescar bien un detalle acerca de los caracteres ascii :)

Aclarando un poco las cosas (y porque me puse a buscar los detalles), para el TP van a tener que utilizar como cantidad máxima las 26 letras del [alfabeto inglés](https://es.wikipedia.org/wiki/Alfabeto_ingl%C3%A9s) que bien pueden ser en minúsculas o mayúsculas (Caracteres ASCII 65 hasta 90 inclusive para las mayúsculas o 97 hasta 122 inclusive para las minúsculas), pero se va a excluir a la letra Ñ ya que forma parte del código ASCII (164 y 165 para ñ y Ñ respectivamente).

Cualquier duda o inconveniente estoy a disposición.
Saludos.-

**Comment by iago64** [comment]
Damos este tema por cerrado por falta de inactividad, si hace lo reabrimos :)
