### ISSUE TITLE
Buscamos 2 integrantes

### ISSUE THREAD

**Issue by juanbanchero** [sisoputnfrba/foro#1134]
Hola, qué tal? Somos un grupo 3 y estamos buscando integrantes para completar el grupo. Cualquier interesado/s puede contactarme por mail. 
Saludos.

Mail: juan.banche@gmail.com

**Comment by tferraro** [comment]
Habiendo cerrado el mercado de pases el lunes, cierro el issue :slightly_smiling_face:
