### ISSUE TITLE
Consulta comando Desbloquear

### ISSUE THREAD

**Issue by Mszlajen** [sisoputnfrba/foro#1135]
Buenas, estamos corrigiendo un par de cosas que implementamos mal (sin seguir la consigna) y revisan issues cerrados y en el #1105 dice que si no hay más ESI bloqueados por es la clave que se paso por parametro, se libera la clave (o sea se la quita al ESI que la tiene) pero no encuentro en que parte del enunciado dice eso.
(No nos va llevar mucho más trabajo implementarlo pero queremos estar seguros antes de agregar cosas que pueden no ir)

**Comment by iago64** [comment]
Buenas buenas!

En base a como estamos encarando las pruebas, el caso de desbloquear si no hay nada en la cola de bloqueados tenes que liberarla, ya que es la única forma que van a tener por ej para desbloquear las claves bloqueadas desde el inicio (por el "sistema)

Saludos.-

**Comment by Mszlajen** [comment]
Perfecto.
