### ISSUE TITLE
Quién debe informar los errores

### ISSUE THREAD

**Issue by vickyRuiz** [sisoputnfrba/foro#1136]
En base al apartado de Manejo de Errores, del Anexo I, nos surge la duda de qué módulo le informa el error al usuario, si es que es importante. 

En el caso del error de tamaño de clave, es fácil porque lo hace el ESI cuando llama al parser (en realidad lo informa el parser). 

Qué sucede con los otros errores? Siempre lo tiene que informar el ESI? A veces lo puede informar otro módulo?

Gracias!

**Comment by iago64** [comment]
Buenas buenas!
Muy buena pregunta :)
En este caso podrías hacer 2 cosas:
1.- Loguear en quien detecta el error que lo detecto (por ej en el caso de clave no bloqueada el coordinador)
2.- Hacer que el ESI informe finalmente por pantalla por que termino.

Es importante que tengan como premisa que lo que nos importa a los ayudantes (y tambien les importa a uds en cierta forma) es  saber el estado del sistema, si son redundantes y por ej para el caso de un sET con clave no bloqueada vemos logs del estilo:
Planificador: `El ESI1 no posee la clave Bloqueada`
Coordinador: `El ESI1 no continua su ejecución por querer acceder a un recurso no bloqueado`
ESI: `Hice la gran Higuain y le pifie de clave que quise setear`

Esta perfecto :)

Saludos.-

**Comment by vickyRuiz** [comment]
Gracias por la respuesta, quedó claro :)
