### ISSUE TITLE
[Planificador] Comando desbloquear/status

### ISSUE THREAD

**Issue by agusmoles** [sisoputnfrba/foro#1137]
Buenas. Estuve leyendo varios issues de los comandos bloquear/desbloquear y como a varios les pasa, marea bastante...

Siguiendo lo del issue #1105, lo de **bloquear** entendi todo, las unicas dudas que tengo son:

_1._ Si esta ejecutando el ESI, apenas me llega que finalizo la sentencia, siempre tengo que verificar, por ej. una variable global, que me diga si tengo que desalojarlo? O como se haria?

_2:_ Los ESIs van a tener, a partir de este comando, mas de un recurso solicitado por el cual estan bloqueados? Porque yo habia pensado por como hice el sistema, que siempre van a tener como maximo 1 solo. Ya que siempre se van a bloquear y quedar esperando al primer **GET** y luego de ser **desbloqueado** recien ahi podrian volverse a bloquear por **otro GET**. Lo que pasa es que con este comando podria pasar que se bloquee a un ESI ya bloqueado y me c*ga lo que habia hecho, lo cual deberia modificar.

Bien, con lo de **desbloquear** tengo la duda que:

> --Desbloqueo de Claves--
> 1.- Si la clave no existe es el camino mas fácil ya que simplemente informan de que la clave no existe y todo sigue su curso
> 2.- Si la clave existe tienen que:
> 2.1.- Poner al primer ESI de la cola de bloqueados en Ready
> 2.2.- Si no hay mas ESIs bloqueados liberar la clave

_2.2:_ Si no libero la clave, el ESI se va a volver a bloquear porque va a volver a hacer el **GET** de ese recurso, no tendria sentido... no hay que liberar la clave de todas maneras? O es por como van a hacer las pruebas que se hace asi? (por ej. la prueba 4 del checkpoint presencial).

Saludos! Gracias

**Comment by iago64** [comment]
Buenas buenas!
Vamos por partes con las preguntas asi no nos perdemos :)

1.- Depende mucho de como lo implementen, yo personalmente lo encararía replanificando la cola de listos / bloqueados cada vez que un ESI me confirma que ejecuto la sentencia (ya sea correcta o que se bloqueo) pero ahí por ahí estaría bueno que consultes por mail con tus ayudantes asignados así pueden ver tu código y darte una respuesta mas acorde.

2.- MUY buen punto, este si tiene un peso bastante lindo y la respuesta es NO, un ESI va a estar bloqueado para un solo recurso a la vez y es legal que si tiramos un bloquear ESI1 C1 y el ESI1 esta bloqueado para la C2 nos dejen un mensaje que diga "El ESI1 ya se encuentra bloqueado para la C2"

2.2: No necesariamente se te van a volver a bloquear, pensa el caso donde un ESI que recién empieza lo bloqueamos a propósito para una clave que nunca va a hacerle un GET, bien podría continuar con su ejecución y ni se entera de la clave. 

Saludos.-

**Comment by agusmoles** [comment]
Buenisimo, todo aclarado, lo del punto 1 lo consulto y cualquier cosa vuelvo abrir. 

Gracias, muy rapido jajaja.

**Comment by agusmoles** [comment]
Abro para una consulta mas sobre el comando **status**. Me hace mucho ruido como lograr que en un momento no determinado se sincronicen tanto Coordinador y Planificador para el envio/recibimiento de mensajes necesarios para realizar lo que el comando pide. A tal punto que no encuentro manera de resolverlo y lo veo hasta imposible 😆 

Alguna ayuda? jajaja

Gracias!

**Comment by iago64** [comment]
@agusmoles Consulta, se que puede sonar feo, pero que te parece una conexión de backup?
Conexión de backup = 2 sockets, es lo mas caverna que se me ocurre peeero, es lo mas rápido también para que no se frenen con el desarrollo :)

**Comment by agusmoles** [comment]
Claro, justamente habia pensado eso, abrir un nuevo socket para que solo se trate ese tipo de mensaje y no seria mala idea... igual, por que seria lo mas caverna? Cual seria la forma de hacerlo? jajaja

Si es muy largo de explicar me quedo con esto y listo jaja

Saludos! Gracias Dami

**Comment by iago64** [comment]
La de los 2 sockets en el coordinador es simple, uno lo dejas a bloqueado en un recv() esperando mensajes del planificador (mas o menos sigue la misma idea de los ESI en ese sentido) y el otro lo dejas bloqueado en un semaforo esperando para cuando tengas para mandarle algo al planificador :)

Hay soluciones distintas pero es complicar la cosa mas de lo que les sirve en este punto.

**Comment by agusmoles** [comment]
Claro, me referia a la solucion complicada pero esta bien jajaja

Muchas gracias. Saludos!

**Comment by agusmoles** [comment]
Buenas, lo estaba haciendo y la conexion Planificador-Coordinador va bien (por lo menos para recibir/mandar mensajes random) pero con el punto este:

> Valor, en caso de no poseer valor un mensaje que lo indique.

Habria que hacer otra conexion mas entre la instancia y el coordinador al igual que Planificador-Coordinador? Ya que tambien llega en un momento X? Me parece que implica un tiempito y prefiero que me lo confirmen asi lo arranco a hacer asi...

Con los demas puntos no habria problema porque si lo puede manejar el Coordinador la respuesta.

Gracias. Saludos!

**Comment by natoszme** [comment]
Buenas! El coordinador no tiene conocimiento de los valores almacenados, para eso está la instancia. Así que para ese comando no te queda otra que mandarle un mensaje del estilo dame el valor de la clave, y después otro que indique la clave. O sea que sería otro de los mensajes que le podés mandar a una instancia (compactá, operá). Aunque corríjanme si me equivoco

**Comment by agusmoles** [comment]
Claro justamente por eso, pasaria el mismo problema que entre Planificador-Coordinador ya que en cualquier momento X te puede llegar el mensaje y no podes crear simplemente un hilo que este colgado en un **recv()** porque capaz "toma" algun mensaje que no deberia de tooodos los que recibe para el funcionamiento... entonces deberia crear otro socket, conectarse y manejarse por ahi.

Saludos!
Espero que se entienda.

**Comment by iago64** [comment]
@agusmoles no te compliques mucho, la instancia solo va a recibir mensajes del coordinador, ya sea pidiéndole un valor o mandandole un valor a grabar.

**Comment by agusmoles** [comment]
Claro, pero ocurre asincronicamente, tipo es lo mismo que pasa entre Planificador-Coordinador y que acoordamos que al final habia que:

> La de los 2 sockets en el coordinador es simple, uno lo dejas a bloqueado en un recv() esperando mensajes del planificador (mas o menos sigue la misma idea de los ESI en ese sentido) y el otro lo dejas bloqueado en un semaforo esperando para cuando tengas para mandarle algo al planificador :)

No sucede lo mismo?

**Comment by iago64** [comment]
Para que te hace falta? pensalo de esta forma, el coordinador te va a pedir una cosa a la vez y de ultima si tenes que encolar los msgs y atenderlos secuencialmente no hay drama :)

**Comment by natoszme** [comment]
O sea simplemente el coordinador puede recibir los mensajes del planificador de a uno, y este mensaje puede ser: respondeme el comando status o ejecuta x instrucción. Y en el caso del status, el coordinador le manda un mensaje a la instancia, la cual no va a estar haciendo nada porque suponemos que el coordinador recibe las cosas de a una. O sea que la instancia queda a la espera de que le pidan algo, pero ese algo no es simultáneo con otro (le piden de a una cosa). Decime si estoy en lo correcto @iago64

**Comment by agusmoles** [comment]
Perdon, pero no te entiendo. Es decir, creo que, desde el Coordinador, no podes mandarle cuando quiera un mensaje para recibir X valor o si? (capaz no lo se porque no estoy metido justamente en esa parte del codigo).

**Comment by natoszme** [comment]
El coordinador le puede mandar ese mensaje a la instancia cuando el planificador le pida al coordinador que responda el status. Y por cómo lo implementamos nosotros, los comandos no corren en simultáneo con las operaciones, sino que cuando termina de hacer una operación se busca si hay instrucciones de consola y ahí se ejecutan. O sea que como no se van a estar ejecutando instrucciones en la instancia, esta va a estar esperando a que le pidan que haga algo y ese algo puede ser el valor de x clave.

Ahora cierra mejor? Cualquier cosa decime. Tiene que ver con cómo lo hayan implementado supongo

**Comment by iago64** [comment]
Momento, vamos por partes porque estamos hablando de cosas diferentes:

1.- El coordinador, va a tener 1 o 2 hilos (Si tienen 2 sockets) para atender al planificador, uno de los hilos posiblemente este bloqueado en un recv esperando mensajes del planificador y otro el cual lo van a tener bloqueado con un semaforo y lo van a usar para mandarle mensajes al planificador a medida que lo necesiten (por ej para consultar los bloqueos de las claves)
2.- Las instancias son mono hilo con lo cual atienden de a 1 las peticiones, tengan 1 o tengan 45 

Saludos.-

**Comment by agusmoles** [comment]
@natoszme esta buena su implementacion, la nuestra fue por otro lado y si puede ocurrir "en paralelo" los comandos de consola y las instrucciones. Gracias igual!

@iago64 Buenisimo, entonces si deberia poder manejar los mensajes entre Coordinador-Instancia sin nada de mas, cualquier cosa aviso. Muchas gracias! Disculpa
