### ISSUE TITLE
Dos SET a la misma clave

### ISSUE THREAD

**Issue by ahufa** [sisoputnfrba/foro#1138]
Buenas a todos, tengo una duda, tendríamos que considerar el caso en que se haga un GET a clave1, luego un SET con el valor1 y por ultimo otro SET a la clave1 con el valor2. Ya que si el valor1 no tiene el mismo tamaño que el valor2 tendría que borrarla y volverla a guardar con el valor2 en otro lugar del storage dependiendo si la posición contigua este libre o no.

Saludos

**Comment by iago64** [comment]
Buenas buenas!
Muy buena pregunta, por simpleza tienen un 4 escenarios posibles:

1.- el valor se reduce y libera entradas (simplemente cambien el valor y marquen las entradas que no necensitan como libres
2.- el valor se amplía y necesitan entradas, acá pueden pasar 3 cosas:
2.1.- tienen espacio contiguo y lo asignan sin mayores problemas
2.2.- tienen el espacio pero no contiguo, ahi les recomiendo sacar la entrada, compactar y volver a grabarla
2.3.- no tienen espacio suficiente, ahi sacan la entrada, seleccionan las victimas que necesiten sacar para hacer el espacio, compactan y la vuelven a grabar.

Saludos.-

**Comment by ahufa** [comment]
En el caso 2.3 podría pasar que no tengo entradas atómicas por lo que si luego de compactar no encuentro lugar que debiera pasar?

**Comment by LeaTex** [comment]
Eso ya lo debatimos en otros issues @ahufa.
Quedamos en que no se puede guardar y la instancia devuelve un error el Coordinador. Pero también nos dijeron los ayudantes que difícilmente se de ese caso, por la forma en que van a pensar las pruebas.

**Comment by iago64** [comment]
Gracias @LeaTex 
Efectivamente, el caso 2.3 ya de por si va a ser raro que se de, y además como estamos pensando las pruebas, muy posiblemente no va a darse un caso donde no puedas hacer el reemplazo.

Saludos.-

**Comment by ahufa** [comment]
Ok cierro el issue

**Comment by fedekiwo** [comment]
@afilgueira una consulta; El sábado te consulte respecto a esto y me dijiste lo mismo solo que en los casos descriptos en los items 2.2 y 2.3 en vez de poder setear el valor, que directamente le tire "error" al coordinador de que no puede hacer el set. Cual es el criterio a seguir?? 
Gracias!

**Comment by afilgueira** [comment]
Dejame verlo con @iago64 y les contestamos bien, así tenemos una línea unificada. Saludos!

**Comment by afilgueira** [comment]
Buenas, quedó claro con la última versión? Saludos

**Comment by fedekiwo** [comment]
Clarísimo! Muchísimas gracias!

**Comment by iago64** [comment]
@ahufa podemos dar por cerrado el issue?

**Comment by ahufa** [comment]
Ahora sí!
