### ISSUE TITLE
Caracteres raros en el ESI

### ISSUE THREAD

**Issue by ahufa** [sisoputnfrba/foro#1139]
Buenas a todos!

Probando los casos del tp cree un script así:

GET deportes:futbol:messi
SET deportes:futbol:messi Lionel Messi
GET deportes:futbol:aguero
SET deportes:futbol:aguero Sergio Aguero

Y los log del ESI me muestran esto:

[TRACE] 16:08:30:616 esi/(8924:8924): GET	clave: <deportes:futbol:messi>

[TRACE] 16:08:30:630 esi/(8924:8924): SET	clave: <deportes:futbol:messi>	valor: <Lionel Messi��h"�	)>

[TRACE] 16:08:30:663 esi/(8924:8924): GET	clave: <deportes:futbol:aguero>

[TRACE] 16:08:30:669 esi/(8924:8924): SET	clave: <deportes:futbol:aguero>valor: <Sergio Aguero>

Si seria Sampaoli y cambio a Messi por Higuain:

GET deportes:futbol:higuain
SET deportes:futbol:higuain Gonzalo Higuain
GET deportes:futbol:aguero
SET deportes:futbol:aguero Sergio Aguero

Me muestra esto el ESI:

[DEBUG] 16:11:44:707 esi/(8977:8977): Abrio el archivo: /home/utnso/Archivo
[TRACE] 16:11:44:710 esi/(8977:8977): GET	clave: <deportes:futbol:higuain>

[TRACE] 16:11:44:718 esi/(8977:8977): SET	clave: <deportes:futbol:higuain>valor: <Gonzalo Higuain>

[TRACE] 16:11:44:751 esi/(8977:8977): GET	clave: <deportes:futbol:agueron>

[TRACE] 16:11:44:754 esi/(8977:8977): SET	clave: <deportes:futbol:aguero>valor: <Sergio Aguero>

Alguno sabe xq me muestra esos caracteres?

**Comment by varas-c** [comment]
Buenas, como va?

La forma más fácil en este caso es poner el debugger justo en la línea
antes de escribir en el log y fijarte que valor tiene la variable que estas
logueando.

Casi seguro que al char que mostrás le falta un \0 y por eso muestra
"Lionel Messi <basura>" y cosas similares.

**Comment by mgarciaisaia** [comment]
[`valgrind`](https://faq.utnso.com/valgrind)

**Comment by gastoncastineira** [comment]
Le pasó a un compañero de mí grupo. Esa basura sale por usar malloc e imprimir el string. Te recomiendo usar calloc en su lugar que hace lo mismo que malloc pero te pone todos los elementos en el nulo del tipo (0 para int, '\0' para char, etc)

**Comment by LeaTex** [comment]
Facu, fijate que puede ser lo que dijo Gastón.
Tal vez no están armando bien la cadena, asegurándose que tenga el terminador.

Con calloc() puede ser una buena forma de probarlo. Sino la otra es usar malloc() y luego memset() para poner 0 en todos los bytes de memoria reservados.

**Comment by ahufa** [comment]
Ya lo corregí con calloc
