### ISSUE TITLE
Comando Desbloquear - caso particular

### ISSUE THREAD

**Issue by ricardoAguirreSanchez** [sisoputnfrba/foro#1140]
Buenas, 
Tomando en cuenta la respuesta sobre que hace el comando desbloquear del issue #1137:

--Desbloqueo de Claves--
1.- Si la clave no existe es el camino mas fácil ya que simplemente informan de que la clave no existe y todo sigue su curso
2.- Si la clave existe tienen que:
2.1.- Poner al primer ESI de la cola de bloqueados en Ready
2.2.- Si no hay mas ESIs bloqueados liberar la clave

Si tenemos la siguiente situación quisiéramos saber que debería pasar:
1.- ESI1 hizo GET clave1 (no se bloqueo pork esta clave estaba disponible)
2.- ESI1 hizo GET clave2 y se bloquea pork otro esi ya lo pidio antes
3.- ESI3 pide GET clave1 y como esta clave quedo tomada por el ESI1, el ESI3 lo mando a lista de bloqueados esperando dicha clave
4.- Desde la consola usamos el comando DESBLOQUEAR clave1
5.- **¿Qué debería pasar?**, si vamos a los pasos comentados anteriormente, sacaríamos al ESI3 de bloqueados ya que era el **UNICO** que esperaba la **clave1**, luego habría que liberar la clave1 ? sabemos que no quedó ningún otro ESI esperando por esta clave PERO esta el ESI1 que la tienen tomada, si 
 "libero" la clave1 estaría quitandosela al ESI1, esta bien? 

Saludos.

**Comment by iago64** [comment]
Buenas buenas!!
Lo que debería pasar en ese caso es que el ESI3 sale de la cola de bloqueados a la cola de Listos y nada más.
La clave sólo se liberaría en caso de que **no tengas nada en la cola de bloqueados** para esa clave.
Saludos.-

**Comment by ricardoAguirreSanchez** [comment]
Bien, entonces mi error fue pensar que los puntos 2.1 y 2.2 eran secuenciales cuando en verdad son uno u otro

**Comment by ricardoAguirreSanchez** [comment]
Ahora, pensando este caso 2:
1.- ESI1 hizo GET clave1 (no se bloqueo pork esta clave estaba disponible)
2.- ESI1 hizo GET clave2 y se bloquea pork otro esi ya lo pidio antes
3.- Desde la consola usamos el comando DESBLOQUEAR clave1
Acá para la clave1 no tengo ningún ESI bloqueado, entonces libero la clave1 (osea le quito la clave1 al ESI1) , esta bien?

**Comment by ricardoAguirreSanchez** [comment]
Gracias.

**Comment by iago64** [comment]
Buenas!

Me gusta tu pregunta porque nos levanta una alerta en cuanto a cómo redactar las pruebas y evitar ambugüedades , la idea ahí era que tiren tantos desbloquear como sea necesario hasta que liberen la clave (en este caso 3 veces mínimo, ya que puede ser que justo intente llegar otro get y bueno... nos quedemos ahi hasta detener la planificación)

Abrazo y gracias por el heads up 👍 !

**Comment by ricardoAguirreSanchez** [comment]
ah joya, gracias a vos!
