### ISSUE TITLE
Consulta commons/bitarray

### ISSUE THREAD

**Issue by Mszlajen** [sisoputnfrba/foro#1142]
Bueno, más que consulta es un pedido de explicación.
Querias usar la commons de bitarray para la administración de espacio libre pero despues de ver el header, los test y el codigo en si, entendemos que el char* que se le pasa al crear un bitarray son los valores iniciales y lo que usa para manejarse (por lo tanto deberia existir mientras exista el bitarray), eso está bien? y de ser así, cómo hay que declararlo para una cierta cantidad de valores (por ejemplo, si quisieramos un bitarray de 8 bits con valor 10001010)?

**Comment by iago64** [comment]
Buenas buenas!!

El char* que le pasan para crearlo es simplemente el espacio de memoria donde van a definir su bitarray, por lo general yo suelo recomendar que lo empiecen limpio y despues seteen los bits que necesitan. Para eso lo que pueden hacer es reservar la memoria con calloc() (que es el equivalente a hacer malloc y despues hacer un memset en 0 de todo lo que reservaron)

Saludos.-
