### ISSUE TITLE
Algoritmo de distribución Least Space Used (LSU) y STORE

### ISSUE THREAD

**Issue by vickyRuiz** [sisoputnfrba/foro#1143]
Hola!
Cuando se ejecuta un STORE en la instancia, el coordinador debe considerar que el espacio ocupado por el valor asociado a esa clave se liberó? O recién considera liberado el espacio si la clave se borra del todo (o sea, después de que se reemplazó con otra cosa)?

Gracias!

**Comment by sebastianciancio** [comment]
Lo correcto es que la Instancia le avise al coordinador cual es el espacio libre luego de recibir un STORE/SET así reflejas lo que realmente sucedió en la Instancia.

**Comment by iago64** [comment]
Mas claro de lo que lo dijo @sebastianciancio no se puede decir :)

**Comment by vickyRuiz** [comment]
Me gusta el enfoque de que la contabilidad la lleve la instancia. De todas maneras, me sigue quedando la pregunta: cuando hace un STORE, la instancia considera que ese espacio se liberó? O sólo considera que se liberó cuando se borra (o sea reemplaza) una clave? En este último caso, sólo se liberaría espacio si el valor nuevo ocupa menos que el anterior. 
Y me surge otra pregunta: medimos el espacio libre en cantidad de claves libres o en cantidad de bits no ocupados?

**Comment by iago64** [comment]
Buenas!

Mil disculpas, colgue con la pregunta del BSU, fijate que en el enunciado dice:

> el algoritmo BSU lleva registro del tamaño dentro de la **entrada atomica** que está siendo ocupado, y en el momento de un reemplazo, escoge aquél **que ocupa más espacio dentro de una entrada.**

Te remarque lo que te hace definirte que es la cantidad de bytes libres en la entrada.

Saludos.-

**Comment by vickyRuiz** [comment]
Y esto aplica a lo que la instancia debería informarle al Coordinador también? El coordinador tiene que elegir una instancia por Least Space Used. El cómputo del espacio usado es el mismo que en BSU?

**Comment by iago64** [comment]
Uh, perdon de nuevo, no se por que me quede con la idea de que hablabamos de la instancia.
En el caso del LSU del coordinador, es en base a **entradas libres**, puede ser que va a llegar un momento en el cual posiblemente tengas que resolver con todas las instancias llenas y ahí el LSU empieza a dejar de ser util ya que al tener todo lleno empezas a volverlo una especie de circular (siempre y cuando no te liberen espacio achicando claves no atomicas)

![image](https://user-images.githubusercontent.com/1622109/41430732-400b92ae-6fe7-11e8-9a03-a92a8cd1302f.png)

**Comment by vickyRuiz** [comment]
Qué vergüenza, estaba re a la vista la respuesta en el enunciado, papelón! Muchas gracias!

**Comment by ricardoAguirreSanchez** [comment]
LSU entonces no vira cuántos espacio tiene una instancia en bytes sino cuántas entradas libres le quedan?

**Comment by iago64** [comment]
@ricardoAguirreSanchez afirmativo 👍

**Comment by vickyRuiz** [comment]
Y finalmente... si hago un STORE de una clave en la instancia, se considera que las claves que ocupaba se liberaron? O una vez que se llenó la instancia, queda llena y paso a rotarlas?

**Comment by ricardoAguirreSanchez** [comment]
En otros issues se habló que el STORE no liberaba nada en el storage de la instancia, solo se limitaba a bajar a disco la clave, por ende, yo pensaria que no.

**Comment by natoszme** [comment]
Buenas! Si el store no hace más que bajar la clave a disco (desde el punto de vista de la instancia), sólo habría que actualizar las entradas libres del coordinador para lsu después de un set y no después de un store, no?

**Comment by iago64** [comment]
@natoszme Afirmativo 👍 
Solo el SET puede ocuparte / liberarte entradas :)

**Comment by iago64** [comment]
@vickyRuiz el issue se puede cerrar? te queda alguna duda?

**Comment by iago64** [comment]
Cerramos el issue por inactividad.
