### ISSUE TITLE
Cuándo se debe frenar la ejecución de esis?

### ISSUE THREAD

**Issue by natoszme** [sisoputnfrba/foro#1144]
Hasta ahora teníamos entendido que se hacía cuando se mandaba a compactar a todas las instancias pero leyendo esto

> Mientras está en ejecución el proceso de Compactación y Dump, no se permitirá ejecutar operaciones en el Sistema de Re Distinto y quedarán en espera a que el proceso se complete correctamente.

nos surgió la duda de si también cuando hay un dump. Nos da la sensación de que es un error en la consigna porque el dump seguramente se haga con una frecuencia alta y podría ser en distintos momentos (según cuando se levante cada instancia), lo que podría generar starvation de los esis

**Comment by LeaTex** [comment]
No debería ser tan complicado, porque dado que las ejecuciones son secuenciales, y solo un ESI puede estar trabajando por vez, basta con tenerlo a la espera de una respuesta.

Mientras la Instancia está haciendo un dump, si el coordinador le mandó algo, no va a poder atenderlo, así que no es problema, porque el coordinador debería quedarse a la espera de que la instancia la responda (aunque sea un Ok).

En el caso de la compactación, cuando una instancia la ejecuta debe avisarle al coordinador, para que este le avise a las otras instancias y lo hagan todos al mismo tiempo.
Ahí es fácil, simplemente el coordinador se queda esperando que todas las instancias le digan "terminé de compactar" y mientras tanto no hace nada más, no atiende nuevas conexiones no le responde a nadie.

Ninguna de las acciones debería llevar más que unos pocos milisegundos, por lo que difícilmente ocurra starvation.

**Comment by iago64** [comment]
@natoszme por favor no te me ahogues en un vaso de agua :)
La cosa es mas o menos de la siguiente manera: Uds en la instancia van a tener 1 solo hilo verdad? y ademas muy posiblemente detenido en un select (con time out simplemente para que corte cuando les toca el DUMP). 
En el momento cuando uds salen del select para hacer el DUMP, van a estar procesando todo en su unico hilo y listo, nada mas va a poder atender esa instancia, hasta que vuelva al select y pregunte si tiene algo para hacer en el socket del coordinador y se enteren de que tienen un pedido. Con lo cual, punto resuelto.
Ahora bien, cuando les llega la compactación, salieron por una peticion del coordinador (en este punto si el coordinador te pidio algo se la va a tener que fumar hasta que termines) si es una compactació, un SET o un STORE, a vos te importa poco y como tenes un hilo recien cuando termines podes atender el siguiente pedido.

Ahora el unico problema lo tiene quien este haciendo el coordinador, ya que en el momento de la compactación tiene que saber que las instancias estan compactando, eso es taaan simple como agarrar y poner un flag que te bloquee (_spoiler: puede ser un semaforo_) y te libere al momento de finalizar la compactación.

Saludos.-

P.D: La solución que plantea @LeaTex es muy buena también, depende de como lo hayan implementado uds cual les puede quedar mas cómoda.

**Comment by natoszme** [comment]
Sisi, yo no preguntaba tanto por la implementación sino por la consigna porque para mi no tiene sentido que si una instancia ajena a la ejecución va a hacer un dump, se frene la misma. Ahora por tu respuesta @iago64 entiendo que se está hablando de la Instancia a la que se manda la óperación, y justo esta tiene que hacer un dump. 

O sea, al coordinador (que me toca a mi jeje) no le importa si alguna instancia (sea o no la que se va a encargar de la operación) va a dumpear, a lo sumo esta tardará más en responder. Decime si me equivoco.

Gracias a ambos!

**Comment by iago64** [comment]
Exacto, el problema del coordinador en si es cuando mande a compactar pero en los dump no hay drama (mismo el dump va a ser algo que va a tomar muy poco tiempo y capaz no te des cuenta que esta dumpeando)

**Comment by natoszme** [comment]
10 puntos, cierro. Abrazo

**Comment by natoszme** [comment]
Buenas ! Reabro porque releyendo me surgieron algunas dudas más: lo que dice @LeaTex de que cuando el coordinador está esperando a que todas compacten, a que se debe? Si el coordinador está esperando eso, no le va a llegar ninguna solicitud de ejecución (porque el planificador no va a mandar a ejecutar a ningún esi, por estar esperando a que el coordinador le avise) aunque no veo por qué no podrían llegarle nuevas instancias y conexiones de esis (que como decía recién, no van a ejecutar). 

En cuanto a lo del select de las instancias que decía @iago64, tiene alguna utilidad más que el timeout? Porque visto y considerando que la instancia va a hacer y le van llegar las conexiones de formar secuencial (de a una), no le veo otra ventaja más que la del timeout (que igual me parece una buena forma para evitar tener otro hilo que lleve la cuenta del tiempo pasado desde el último dump y sepa hacer el mismo)

Gracias!

**Comment by iago64** [comment]
Buenas buenas!
Vamos por partes:
Respecto al Coordinador, puede que se te conecten mas cosas, pero como vos vas creando un hilo por cada conexión, no deberías tener mayores problemas para aceptar nuevas conexiones.

Respecto al select, en el caso de la instancia, no te sirve para otra cosa, porque vos vas a tener un solo socket que de hecho vos lo vas a crear para conectarte. Pero es para no agregar un hilo y andar haciendo el dump a mano con otro hilo. Si lo quieren hacer, bienvenido sea, pero van a tener que ser criteriosos para estar jugando con los semáforos.

Saludos.-

**Comment by natoszme** [comment]
Perfecto, mil gracias. Vuelvo a cerrar jeje
