### ISSUE TITLE
Store y comando Desbloquear

### ISSUE THREAD

**Issue by NicoFeld** [sisoputnfrba/foro#1145]
Entiendo que el comando Desbloquear deberia funcionar como si fuera un store de la clave que pasan por consola, sin embargo viendo el issue #1105 veo que dice:
--Desbloqueo de Claves--
1.- Si la clave no existe es el camino mas fácil ya que simplemente informan de que la clave no existe y todo sigue su curso
2.- Si la clave existe tienen que:
2.1.- Poner al primer ESI de la cola de bloqueados en Ready
**2.2.- Si no hay mas ESIs bloqueados liberar la clave**

Segun lo que entendi del enunciado en general y las respuestas en los issues parece una conducta "antinatural" que se libere la clave solamente cuando no haya ESIs bloqueados. Ya que no es lo que pasa con un STORE por ejemplo, en el que se libera la clave aunque haya ESIs bloqueados en esa clave.

Siento que el tratar el STORE y el desbloqueo por consola de forma diferente no es lo que estaban planteando en un principio. Pero si es asi por favor necesitaria una reconfirmacion, gracias.

**Comment by agusmoles** [comment]
Por lo que me respondieron a mi en el issue que referencia ese issue que decis, sí, tiene toda la pinta de un STORE pero cambia un poco con eso que decis al principio. Solo se libera si no hay ESIs bloqueados por tal clave.

Por eso el orden de ejecucion de la Prueba 4, si hubiesen estado los dos bloqueados por la clave que tenia el Sistema, si desbloqueabas por consola no iba a continuar el curso esperado del programa por tal requerimiento.

Saludos. De todas maneras espera a que responda un ayudante jaja

**Comment by iago64** [comment]
Es bastante cercano a lo que dice @agusmoles justo en el issue https://github.com/sisoputnfrba/foro/issues/1140 se hablo justo de este tema :)
