### ISSUE TITLE
Duda tabla de instancias

### ISSUE THREAD

**Issue by LucasSaller** [sisoputnfrba/foro#1146]
Buenas una consulta, en las instancias, hay que usar una tabla (array con columna y fila), o se puede usar listas? Porque nosotros lo habíamos encarado con listas pero si es asi no tendria compactacion, como que no tendria sentido... por eso me surgio esta duda

**Comment by iago64** [comment]
Buenas buenas!

Por un lado deberían tener una lista para administrar las entradas y después las entradas en una estructura que pueden castearla como array o no, pero que tiene que ser un solo malloc().

Saludos.-

**Comment by nachozullo** [comment]
Buenas, no se si entendí bien. 

Lo que decís es que podemos tener la tabla de entradas como una lista pero la estructura ENTRADA - VALOR deberíamos implementarla de forma que no sea dinámica. Esto es porque el coordinador define el tamaño de cada entrada y la cantidad máxima de entradas. Entonces cada vez que se conecte una instancia, debería fijar su estructura ENTRADA - VALOR con la información recibida por parte del coordinador. 

Estoy muy lejos de lo que decis?

**Comment by iago64** [comment]
Estas bastante lejos, **en la tabla lo que van son solo los valores**. todo lo que sean claves y demás estructuras administrativas tienen que estar en otro lado.

**Comment by nachozullo** [comment]
Ahora estoy más mareado. La **TABLA DE ENTRADAS** en el enunciado dice:

`La Tabla de Entradas es una estructura administrativa de la Instancia de Re Distinto que permite gestionar el almacenamiento y facilitar el acceso a los valores almacenados. Para esto, en cada elemento de la tabla se almacenará una clave, el número de entrada asociada y el tamaño del valor almacenado.
`

Esto nosotros lo estamos manejando con una lista. Cuando se haga un SET o STORE, la instancia encargada debe buscar en la tabla de entradas el numero de entrada asociado a esa clave. Con ese numero de entrada puede buscar en el storage el valor almacenado. 
El problema surge en el **STORAGE** que es donde para cada entrada se almacena el valor que corresponde. Esta estructura es la que no debe ser dinámica ya que hay una cantidad fija de entradas por instancia cada una con un valor fijo. 

Sigo lejos?

**Comment by iago64** [comment]
Ahi estas en el lugar correcto, puede que el primer post tuviera un par de vueltas de mas jeje.

**Comment by nachozullo** [comment]
Si, mil disculpas. Gracias por responder rápido!

**Comment by iago64** [comment]
@LucasSaller el issue se puede cerrar? te queda alguna duda?

**Comment by kamipalomino** [comment]
hola, me queda la duda que si en vez de usar tablas o listas se puede utilizar un diccionario como estructura.

**Comment by varas-c** [comment]
Usar un vector, una lista, un diccionario o lo que deseen, depende de
ustedes. La idea es que ustedes hagan una "tabla" como el enunciado pide.
Si esa "tabla" la manejan como una lista, un vector o una matriz, es lo
mismo. Así que sí, podes usar un diccionario

**Comment by kamipalomino** [comment]
Perfecto muchas Gracias!

**Comment by iago64** [comment]
Cerramos el issue por inactividad, cualquier cosa lo reabrimos :)
