### ISSUE TITLE
Desconexión de instancia y su implicancia para algoritmos de distribución de Coordinador

### ISSUE THREAD

**Issue by vickyRuiz** [sisoputnfrba/foro#1147]
Estoy en la duda si estamos pensando bien la conexión entre instancias y coordinador.

Hasta ahora, lo encaramos de esta manera: 
- El coordinador tiene una lista de instancias que se conectaron alguna vez (cada una tiene su propio hilo)
- Cuando hace falta elegir una instancia para un SET, si no existe la clave aún, corremos el algoritmo de distribución y elegimos una. 
- Tanto para SET como STORE, nos enteramos de que la instancia no está conectada cuando no recibe nuestro mensaje.

Qué hacemos cuando está desconectada? En el enunciado dice: 

> En el caso que el coordinador decida en el paso 2 que la operación no puede ser ejecutada porque la instancia no existe más en el sistema(^9), le avisará al Planificador, el Planificador abortará al ESI en cuestión. No se deberán tomar acciones sobre los ESIs bloqueados para dicha clave ya que la instancia puede reincorporarse en el sistema a futuro.

Con esto entendemos que ese ESI se descartaría. Lo que no estoy segura es si el momento en que nos enteramos que está desconectada es el correcto. Deberíamos averiguar si está conectada regularmente, o al menos antes de elegirla? Sobre todo en el algoritmo Key Explicit, podría pasar que consideremos que hay muchas más instancias que las que realmente hay.

**Comment by iago64** [comment]
Buenas buenas!
Con que al momento de elegirla si le haces un send, te vuelve con error alcanza, no tenes que estar tirandole un ping (o viendo si esta viva la instancia) constantemente :)

Eventualmente en KeyExplicit, si vas a mandar algo y falla ahí recalculas las asignaciones :)

Saludos.-

**Comment by vickyRuiz** [comment]
Perfecto. Entiendo entonces que cuando un ESI pide SET o STORE (y está habilitado a hacerlo), el coordinador busca una instancia, intenta pedirle que lo ejecute, y si no puede, el ESI tendrá que abortar. Es correcto?

**Comment by iago64** [comment]
Exacto :)

**Comment by iago64** [comment]
@vickyRuiz el issue se puede cerrar? te queda alguna duda?

**Comment by natoszme** [comment]
@iago64 pregunta antes de cerrar. Si en nuestra implementación los hilos de instancia se quedan bloqueados en un recv, sería algo así como que "constantemente estamos viendo si se cayó" porque ese recv devolverá 0. No es ningún problema no? Digo por lo que decías más arriba

**Comment by iago64** [comment]
@natoszme Para nada, simplemente lo que dije más arriba es una solución posible y no muy complicada para alguien que no tenga los hilos pendientes en un recv, pero en tu caso no hay ningun drama :)
Abrazo!

**Comment by natoszme** [comment]
Una vez más, gracias @iago64

**Comment by vickyRuiz** [comment]
Quedó claro, gracias por la respuesta!
