### ISSUE TITLE
Duda sobre como responder al comando Status

### ISSUE THREAD

**Issue by natoszme** [sisoputnfrba/foro#1148]
Buenas! 

Armando el status desde el punto de vista del coordinador, nos encontramos con las siguientes situaciones:
1. El coordinador cree que instancia tiene la clave pero esta caída => **¿hay que simular?** acá no tiene valor
2. Instancia viva y tiene clave => este no es un problema, y si o si tiene valor
3. Instancia viva pero NO tiene la clave => **¿hay que simular?** Aca tampoco tiene valor
4. Ninguna instancia tiene clave => simular. Acá es otro caso donde no tiene valor

Tenemos dudas con lo que pintamos en negrita, no sabemos si habría que simular o simplemente decir que la instancia está caída. Qué opinan?

**Comment by iago64** [comment]
Buenas buenas!
Me agrada demasiado que pongan puntos, asi es mas facil contestar sin colgar nada 😄 

1. Si tienen el registro de la instancia que estaba asignada pero al pedir el valor esta caída no se la compliquen y devuelvan en que instancia estaba y que no recuperan el valor por estar caída.
2. 👍 
3. Hablamos de una clave que fue reemplazada? en ese caso no sabes en qué instancia está porque al reemplazarlo le avisan al coordinador, con lo cual quedan en el caso 4.
4. Simulan sin drama y nos avisan que no tienen valor :)

Saludos.-

**Comment by Mszlajen** [comment]
Me cuelgo con una duda sobre ese punto 3.
Vos estás diciendo que la instancia necesita avisarle al coordinador si al hacer SET se reemplazo alguna clave (y cuales fueron)? Pero en el issue #1126 dice que no es necesario hacerlo sino que el coordinador puede enterarse del reemplazo de una clave recien cuando un ESI quiere operar con ella, y acá es el caso donde se genera la situación 3 de la pregunta inicial.
Lo que yo entiendo que habria que hacer es, desde el punto de vista del coordinador, actualizar su tabla eliminando la clave (igual que si un ESI hubiera hecho SET/STORE), correr la simulación, y devolver el resultado de la simulación sin valor. ¿Eso está bien?

**Comment by ricardoAguirreSanchez** [comment]
Buenas,
Este caso tan particular de pedir un status de una clave que estaba en una instancia pero fue sobreescrita lo podemos manejar nosotros?, Es decir podemos ver que tipo de mensaje mostrar cómo resultado? 
Por ejemplo mostrar que existía la clave pero de valor vacío (ya que fue sobreescrita?), Esto ya que como mencionan el coordinador no se entera de que la clave fue pisada si antes un ESI no pide un set/store.

**Comment by iago64** [comment]
@Mszlajen Tengamos en cuenta que cada grupo tiene una implementación diferente de las cosas no definidas, con lo cual, estas cosas pueden variar :)
Lo importante en este punto es que si tienen el dato de en que instancia esta la clave lo muestren y si no simulen, de igual manera con el valor, si lo tienen, digan que valor es, si no lo tienen digan de la forma que les guste que no tienen el valor.

@ricardoAguirreSanchez Obvio que lo pueden manejar uds pero siempre tengan en cuenta una cosa, si tienen el dato de la instancia devuelvanlo, si no lo tienen simulen :)
Devolver un valor vacio no es feliz, porque no deja entender si es que no tiene valor o tuvieron algun error, siempre en esos casos lo mejor es un mensaje que diga "No tenemos el valor" o el famoso "404 Valor not found" como para entenderlo mas rapido :)

Saludos.-

**Comment by iago64** [comment]
@natoszme Como va? Te queda alguna duda o le damos fin al issue?

**Comment by natoszme** [comment]
Le damos fin noma
