### ISSUE TITLE
Dudas sobre resultado de Prueba 3

### ISSUE THREAD

**Issue by juanfatur** [sisoputnfrba/foro#1149]
Buenas! Surgió la siguiente duda con respecto a la prueba 3 del checkpoint presencial:
-El planificador inicia con la clave futbol:messi "bloqueada" por consola. 
-Se inicia el ESI_MultiClave, hace una ráfaga de 3 (GET futbol:ansaldi, SET futbol:ansaldi TraeVodka, GET futbol:messi) y se bloquea al no poder tomar la clave.
-Se inicia el ESI_Largo, hace una ráfaga de 1 (GET futbol:messi) y se bloquea al no poder tomar la clave.
-(Pausamos la planificación) -> Si no, se desbloquearía el ESI_Multiclave antes de que liberemos la clave.
-Desde la consola desbloqueamos clave una vez. El ESI_MultiClave se libera y pasa a la cola de listos, con estimación 3 (0.5 * 3 + 0.5 * 3).
-Desde la consola desbloqueamos clave otra vez. El ESI_Largo se libera y pasa a la cola de listos, con estimación 2 (0.5 * 3 + 0.5 * 1).
-Desde la consola desbloqueamos la clave por tercera vez, para liberarla del bloqueo por consola que tenia hecho.
-Reanudamos la planificación. Dado que planificamos con SJF SD, el siguiente ESI a ejecutar es el ESI_Largo, que ejecutará hasta que termine. Luego se ejecutará el ESI_MultiClave y terminará exitosamente. 

El valor final para la clave futbol:messi, por lo tanto, será el que le dio por último ESI_MultiClave ("TraemeLaCopa"). Pero en la prueba dice que el valor final debería ser "SeLoMeressi".

¿Estamos equivocados en el razonamiento o el resultado de la prueba está equivocado?
Gracias!

**Comment by iago64** [comment]
Buenas buenas!

Te confirmo que fue un error en el doc, ahi lo arreglamos, lo importante de todas formas es que terminen ambos y que estimen correctamente (es decir primero termina el ESI_Largo y después el MultiClave)

Saludos.-

**Comment by afilgueira** [comment]
Quedó claro @juanfatur? Podemos cerrar o querés repreguntar? Saludos!

**Comment by juanfatur** [comment]
Perdón por la demora. El análisis de lo que debería pasar con el comando desbloquear es correcto?

**Comment by iago64** [comment]
@juanfatur si, el análisis como lo planteas es correcto :smile:

**Comment by juanfatur** [comment]
Perfecto, gracias! Cierro...
