### ISSUE TITLE
Consulta - Instancia - algoritmos de reemplazo

### ISSUE THREAD

**Issue by AlejoZito** [sisoputnfrba/foro#1150]
Como andan, venía a hacer una consulta respecto al reemplazo de claves en la Instancia.
Entiendo que la consigna marca que solo aplica reemplazo para entradas atómicas, la duda es, lo atómico se refiere al valor que voy a guardar (y las entradas que voy a ocupar), o las claves-entradas que tengo almacenadas? ¿o a ambas?
Les planteo los casos que veo:

- Tanto la entrada que voy a guardar como la que voy a pisar tienen que ser atómicas -> Ok, el caso más sencillo. Ignoren el otro item.
- La entrada que vas a pisar tiene que ser atómica, el valor que queres guardar puede llegar a ocupar más de 1 entrada -> Esto lo veo implementable para circular (busco n espacios contiguos para pisar claves atomicas o espacios libres, si encuentro una clave que ocupa mas de 1 entrada empiezo a buscar de nuevo donde esta termina). Para los otros algoritmos no me terminaría de cerrar, por ejemplo LRU, busco la que se uso hace mas tiempo, la encuentro, si necesito 2 entradas contiguas, la entrada inmediata siguiente ya no termina de seguir la logica lru, simplemente es la que esta al lado de la menos usada. O peor, si no llego a tener las entradas contiguas que necesito, tendria que saltar a la siguiente clave menos usada? La veo un poco enroscada con esta logica. 

Y otra consulta aparte de todo esto. Si tengo 40 entradas, la entrada [39] y la [0] se consideran contigüas? Intuitivamente diria que no. Pero creo que el termino circular me desoriento.

Saludos!

**Comment by iago64** [comment]
Buenas buenas!
Vamos por partes para no perdernos :)
1.- El tema de que sean atómicas solo importa para las que tenes que reemplazar en la instancia, es decir, las que vas a sacar
2.- La entrada que vas a guardar puede o no ser atomica.
3.- Si la entrada que vas a guardar no es atomica y tenes que reemplazar mas de 1 entrada, segui las reglas del algoritmo para obtener las entradas libres suficientes y despues compactas si hace falta.
4.- La entrada 39 **no** es contigua a la 0, no hace falta que se la compliquen de mas.

Creo que no me quedó nada por contestar, cualquier cosa avisame y lo vemos.
Saludos.-

**Comment by AlejoZito** [comment]
Perfecto, pero retomando el punto 3), y para explicitar algunas cosas que no aparecen en la consigna del tp, para LRU o BSU:

- Me llega un valor que requiere 2 entradas. Obtengo el que hace mas tiempo no se usa (o el que ocupa mas espacio dentro de una entrada para bsu), para la entrada nro 2 que hago? Obtengo la inmediatamente siguiente? no hay ninguna garantia de que la siguiente sea usable, puede pertenecer a una clave no atomica-valor. Si me decis que la siguiente entrada tiene que ser la siguiente que hace mas tiempo no se usa, estamos en otro problema, porque ahi implicaria guardar registros en entradas no contiguas.
Tambien te pido aclarar por lo que mencionas de compactacion: entendi que la compactacion apuntaba a eliminar los espacios libres entre valores, y mover todo el espacio libre hacia el final. No estoy hablando de juntar valores no contiguos de una misma clave, me parece que eso nunca debería ocurrir si nos basamos en la premisa de que **no se pueden guardar valores en entradas no contiguas**.

**Comment by Mszlajen** [comment]
Buenas, ya que estoy te respondo yo en base a lo que implementamos y entiendo de la respuesta de iago.
Cuando llega una clave que no entra corres el algoritmo que este configurado, si despues de hacer el reemplazo te sigue sin entrar corres nuevamente el algoritmo y así las veces que sea necesario para que las entradas libres sean iguales a las necesarias.
Una vez hecho eso, te puede pasar, como vos decis, que esos espacios libres que generaste no sean contiguos, entonces no te queda otra que usar la compactación.

**Comment by AlejoZito** [comment]
@Mszlajen gracias che, lo que decis de ir volviendo a correr el algoritmo no lo habia pensado. De todas formas la pregunta va mas apuntada a cual es la bajada de la catedra respecto a esto, para sacar toda subjetividad de lo que podemos interpretar de lo que dijo la consigna o el otro. Más que nada porque ya nos pasó que preguntando la respuesta fue no eso sería demasiado complejo, resuelvanlo asi, o arrojen un error y ya,
**Corrijanme si me equivoco, pero compactación consiste solamente en agrupar el espacio libre, no implica analizar donde hay valores 'no contiguos'y reubicarlos**

**Comment by iago64** [comment]
Buenas buenas!
Es tal cual lo que dice @Mszlajen vas corriendo el algoritmo para obtener las entradas libres y despues compactas si te hace falta.

@AlejoZito Efectivamente, el compactar agrupa todo el espacio libre junto, nada mas, por eso en el caso 3 primero obtenes el espacio libre y después compactas si hace falta :)

Saludos.-

**Comment by iago64** [comment]
Buenas!
Si, en este caso como tenes que reemplazar mas de 1 entrada la forma mas "comoda" es marcar como libre las que necesites y despues compactar para obtener el espacio contiguo.
Saludos.-

**Comment by AlejoZito** [comment]
Perfecto gracias!
