### ISSUE TITLE
Duda comando bloquear

### ISSUE THREAD

**Issue by cheja** [sisoputnfrba/foro#1151]
Buenas, como va?

No termine de entender exactamente como funciona el comando `bloquear`. Segun entendí, se le pasa como parametro un ESI y una clave y se bloquea ese ESI hasta que se algun otro ESI haga `store` de dicha clave (o se utilize el comando desbloquear)? Aun si el ESI bloqueado nunca utilizaba la clave con la que se lo bloqueo?

Saludos y gracias!

**Comment by iago64** [comment]
Buenas buenas!
El comando bloquear lo que hace es literalmente bloquear un ESI para una clave (no importa si el ESI hace un GET o no de esa clave).
Después el desbloqueo como bien decis puede darse porque el ESI que tenia bloqueada la entrada hace un STORE o porque alguien usa el desbloquear desde la consola.

Saludos.-

**Comment by afilgueira** [comment]
@cheja quedó claro? Podemos cerrar o querés repreguntar? Saludos!

**Comment by cheja** [comment]
@afilgueira Perfecto, gracias!
