### ISSUE TITLE
STATUS - implementacion particular

### ISSUE THREAD

**Issue by ricardoAguirreSanchez** [sisoputnfrba/foro#1152]
Buenas,
Queremos corroborar si estamos contemplando bien cada caso, en general este issue puede parecerse al issue #1148, pero creamos este otro apuntando a como nosotros encaramos algunos aspectos que no estaban definidos.

Duda 1: STATUS clave1 -> si la clave existe en el sistema pero el coordinador ve que al tratar de pedir el valor a la instancia1, esta esta desconectada, lo que mostramos seria:
INSTANCIA: instancia1
VALOR: No tenemos el valor por instancia desconectada
ESIS: no hay ningún ESI bloqueado

Duda 2: STATUS clave2 -> si la clave existe en el sistema pero fue sobreescrita, con lo cual el coordinador puede pedir el valor a la instancia2 pero esta le informara de la ausencia de dato, entonces mostramos:
INSTANCIA: instancia2
VALOR: No tenemos el valor
ESIS: no hay ningún ESI bloqueado

Duda 3: en el primer caso es **NECESARIO** que el coordinador saque de su registro **<instancia,clave>** a la instancia que detecto que estaba desconectada? porque hasta el momento esta "limpieza" la habíamos dejado exclusiva solo para los casos de operaciones SET/STORE, es decir para el ERROR DE CLAVE INACCESIBLE (quizá no convendría limpiarlo y así poder dejar la opción de que la instancia se vuelva a conectar en el medio, pero por las dudas lo preguntamos antes :P)

Saludos.

**Comment by iago64** [comment]
Buenas buenas!
Vamos por partes
Duda 1: **PERFECTO** 👍 

Duda 2: **PERFECTO** 👍 

Duda 3: Es que en realidad en el status no tenes que limpiarlo por mas que sea que se te desconecto porque vos ahi queres el estado, pero si la instancia reconecta el valor va a ser accesible nuevamente. De hecho es una linda prueba que se puede hacer y rápida para probar la reconeccion de las instancias
1.- Setear un valor para una clave
2.- Desconectar la instancia
3.- Pedir el status de la clave
4.- Reconectar la instancia
5.- Pedir nuevamente el status de la clave y ver si trae el valor

Saludos.-

**Comment by ricardoAguirreSanchez** [comment]
Genial!, gracias por la respuesta (y el mini-test 👍)
