### ISSUE TITLE
Desempate en reemplazo

### ISSUE THREAD

**Issue by Mszlajen** [sisoputnfrba/foro#1153]
Queria comprobar que estoy entendiendo bien como es el funcionamiento del algoritmo circular como desempatador.
Tenien dos claves como pretendientes a ser reemplazadas, la primera en la posicion N y la segunda en la posicion M, con N menor que M, y el puntero apuntado a la posicion P.

**1- P menor o igual que N**
Se reemplaza N y el puntero queda en N+1.
**2- P mayor que N y menor o igual a M**
Se reemplaza M y el puntero queda en M+1
**3- P mayor que M**
Se reemplaza N y el puntero queda en N+1 (por la circularidad)

¿Es así o me estoy complicando de más?

**Comment by iago64** [comment]
Perfecto, por desgracia más fácil no se me ocurre que se pueda hacer

**Comment by Mszlajen** [comment]
Genial.
No me parece tan complicado (aunque capaz es porque ya pense como hacerlo) pero queria estar seguro que en realidad era una cosa como FIFO y yo me complicaba demás haciendo esto.
