### ISSUE TITLE
Problema funcion bitarray_set_bit

### ISSUE THREAD

**Issue by LautaroOdriozola** [sisoputnfrba/foro#1154]
Hola! Tengo un problema con estas dos funciones:

- bitarray_set_bit(t_bitarray*, off_t bit_index)

- bitarray_test_bit(t_bitarray*, off_t bit_index) 

Ésta última función la utilizo para recorrer todo el bitArray leyendo que posiciones estan seteadas para luego obtener la informacion de cada una de ellas. El problema está en que cuando seteo, me setea algunas posiciones pero no todas cuando yo estoy recorriendo posicion a posicion las que quiero escribir/setear. Estuve debuggeando un buen rato pero no encuentro el problema. Para crear el bitarray uso esta funcion pero no se si mi problema está ahi o cuando yo estoy seteando una posicion. 

t_bitarray * crearBitArray(uint32_t cantBloques){
	int tamanioBitarray=cantBloques/8;
	if(cantBloques % 8 != 0){
	  tamanioBitarray++;
	 }
	char* bits=malloc(tamanioBitarray);
	t_bitarray * bitarray = bitarray_create_with_mode(bits,tamanioBitarray,MSB_FIRST);
	int cont=0;
	for(; cont < tamanioBitarray*8; cont++){
		bitarray_clean_bit(bitarray, cont);
	}
	return bitarray;
}  

Espero alguna respuesta. Muchas gracias.

**Comment by tferraro** [comment]
Buenas!

Estuve viendo (por eso no contesté al toque) y no logro encontrarle el error a lo que estás armando, vendrá de otra parte el error?

Cual es el comportamiento exacto que tiene? Con que difiere en exactitud a lo que esperas? Cual es el estado de la memoria en ese momento debuggeando?

**Comment by LautaroOdriozola** [comment]
Hola! pude armar dos funciones para que se pueda ver como estoy seteando las posiciones. Las funciones son triviales ya que solo estoy guardando en mi storage valores atomicos y no que ocupen mas de una posición en el storage. Trato de imprimir todas las posiciones que estaria "seteando" pero despues no las setea.

Acá creo el bitarray y hago el malloc

int tamanioStorage = CANTIDAD_ENTRADAS*TAMANIO_ENTRADA;
void * storage = malloc(tamanioStorage);							
t_bitarray * bitArrayStorage = crearBitArray(CANTIDAD_ENTRADAS);

 Acá estan las dos funciones con comentarios: 

void escribirStorage(char * valor){

	int posicionLibreStorage = devolverPosicionLibreStorage();

	log_trace(logger, "Posicion Libre en STORAGE = %d", posicionLibreStorage);

	//Creo estructura para generar porcion de valor y guardarlo en el storage
	infoPosicion * datosAux = crearStrValor(valor);

	log_info(logger,"Escribo en la posicion : %d ", posicionLibreStorage);
	log_info(logger,"Valor = %s", valor);

	//Escribo en el storage el valor
	memcpy(storage + posicionLibreStorage * sizeof(infoPosicion), datosAux, sizeof(infoPosicion));

	//Para ver que guardo en esa posicion
	infoPosicion * datos = (infoPosicion*) (storage + posicionLibreStorage * sizeof(infoPosicion));
	log_info(logger, "ESTOY GUARDANDO ESTO: %s", datos->porcionDeValor);

	// Seteo la posicion actual.
	bitarray_set_bit(bitArrayStorage, posicionLibreStorage);
	log_trace(logger,"Seteo la posicion : %d.", posicionLibreStorage);
}

void mostrarValoresPosicionesSeteadas(){
	int cont=0;
	for(; cont < CANTIDAD_ENTRADAS; cont++){
        //Si una posicion esta seteada, entra al if
	if(bitarray_test_bit(storage,cont)){
			infoPosicion * datos = (infoPosicion*) (storage + cont * sizeof(infoPosicion));

			log_debug(logger, "Posicion %d SETEADA!", cont);

			log_warning(logger, "Imprimiendo Contenido = %s", datos->porcionDeValor);
		}
	}
}

Si yo hago escribirStorage de varios valores, me deberia setear cada posicion en la cual guardo cada valor pero cuando quiero mostrar el contenido de las posiciones seteadas entra a posiciones que nunca le hice un bitarray_set_bit. Espero que se entienda lo que quiero decir pero no veo cual es el problema del seteo.

**Comment by LautaroOdriozola** [comment]
Ya encontre el problema, cuando estaba haciendo la funcion bitarray_test_bit() no le estaba pasando bien los parametros. Muchas gracias!
