### ISSUE TITLE
Aumento de tamaño de claves en instancia

### ISSUE THREAD

**Issue by Mszlajen** [sisoputnfrba/foro#1155]
De darse el caso siguiente:
Tengo una clave cuyo valor ocupa N entradas, se hace un set dandole un valor que ocupa M entradas, con M mayor que N, y la instancia donde está almacenada esa clave no tiene las M-N entradas que necesitaria para setear el valor, qué tengo que hacer?
A) Tratar ese valor como si fuera de una clave nueva, o sea, llamar al algoritmo de reemplazo y, de ser necesario, la compactación.
B) Informar un error y dejar el valor de N entradas.
C) Informar un error y eliminar la clave.
D) Otra opción que se paso por alto.

(Me sonaba que esto se discutio en otro issue pero no lo pude encontrar así que no sé si no me lo habre imaginado).

**Comment by iago64** [comment]
Buenas buenas!
Opción D: No va a pasar y si pasa por algún tema extremo se nos pasa, nos avisan y fixeamos las pruebas :)

Si se había discutido en otro issue pero dado que es un caso muy borde decidimos no evaluar ese caso y que a lo mucho llenar las entradas que tenga asignada esa clave o si reducirlas para generar los huecos ;)

Abrazo!

**Comment by Mszlajen** [comment]
Genial, gracias.
