### ISSUE TITLE
reemplazo-algoritmo circular-puntero

### ISSUE THREAD

**Issue by acerbonimartin** [sisoputnfrba/foro#1156]
¡Hola!
tengo una duda respecto al posicionamiento del puntero
El caso es este: tengo el vectorBinario 1 111 1 0. teniendo:
1. - Clave A: ocupa 1 entrada- posicion 0
2. - Clave B ocupa 3 entradas-posicion 1
3. - Clave C ocupa 1 entrada-posicion 4
4. - El puntero esta apuntando a la posicion 5, que está libre.
  Entonces se hace un nuevo SET de la clave B, y pasa a ocupar una sola entrada, quedando el vector
binario: 1 1 00 1 0- con el Puntero apuntando al ultimo '0'.
y se me pide hacer un SET una nueva clave D, ocupa 2 espacios. No puede entrar en donde apunta el Puntero. antes que hacer Compacatcion, pongo esta clave en las 2 entradas contiguas que tengo, mas atras en el vector.
  Mi duda es: El puntero sigue apuntando a la Posicion 5 para no romper el orden de reemplazo y así proximamente reemplazar la clave A? o pasa a apuntar al final del nuevo dato ingresado, osea a la posicion 4?
    Desde ya muchas gracias

**Comment by iago64** [comment]
Buenas buenas!
Por qué compactarías si tenes un espacio donde entra perfecto la clave D?
A lo mucho tendrías que preocuparte a la hora de hacer algún reemplazo, pero para asignar no es necesario que se la compliquen compactando si tienen un hueco donde entra la clave en espacios contiguos :)

Saludos.-

**Comment by acerbonimartin** [comment]
sisii, justamente me refería a que, antes que compactar innecesariamente, lo inserto en el espacio libre.

> EDIT: El puntero de circular se mueve a medida que se van reemplazando las entradas, se me paso aclarar eso jeje

Mi pregunta viene porque al momento de hacer SET de una clave nueva, esta se tiene que poner donde señala el puntero. Si no muevo el puntero al agregar una nueva clave, cuando tenga que reemplazar voy a sacar a la clave mas reciente envez de la mas vieja. 
  Por lo tanto incremento el puntero cada vez que agrego una nueva clave tambien. Mi problema viene cuando la clave no entra en donde apunta el puntero, y la meto en algún otro hueco del vectorBinario. que hago con ese puntero? Sigue apuntando donde estaba o apunta al espacio próximo a donde puse la nueva clave?

**Comment by iago64** [comment]
Ojo, no te confundas (ni te la compliques), si tenes los espacios libres no tenes que asignar a donde tenes el puntero.
**El uso del puntero es solamente cuando reemplazas entradas.** Si no tenes reemplazo, asignalo donde puedas siempre y cuando te quede contiguo :)

El puntero lo vas a ir actualizando a medida que reemplaces, de hecho fijate que en el enunciado te dice:

>Una vez que se ha reemplazado la entrada, el puntero se mueve a la siguiente iterando hasta llegar al final. En cuanto llega a la última entrada, el puntero retorna a la primer posición.

Saludos.-

**Comment by acerbonimartin** [comment]
Eso era lo que yo hacía originalmente. Al momento de guardar una nueva entrada, empezaba a recorrer el vectorBinario hasta encontrar el primer hueco de espacios libres contiguos, y ahí lo guardaba. 
  Si por ejemplo tenia Clave A-1 entrada, Clave 2-2 entradas, Clave3-1 entrada tal que el vector binario lo tenía 1 11 1 0. ingresadas en orden alfabético.
 entonces la clave 2 pasaba a ser de una sola entrada, el vector quedaba 1 10 1 0.
originalmente, si quería ingresar una nueva entrada atómica, éstaba se guardaba en el primer 0 que se encontraba, asi eliminaba la fragmentacion externa cuando podía y evitaba compactar, me parecía lo mas óptimo.
  Pero cuando consulté respecto a esto en el laboratorio el dia de la entrega presencial, me dijeron que estaba conceptualmente mal.
  porque estaría afectando el orden en el que ingreso los valores, y el algoritmo circular dejaría de hacer lo que se supone que tiene que hacer: eliminar las entradas que se ingresaron hace mas tiempo. Por lo tanto me dijeron que en lo posible metiera las claves nuevas en donde señala el puntero, y de no ser posible entonces recién ahí busque un hueco en cualquier otro lugar del vectorBin

por todo esto vino mi duda de "que hacer con el puntero cuando ingreso la nueva entrada en un hueco donde no entra el puntero: dejarlo donde estaba o señalar al espacio contiguo a la nueva clave?"

**Comment by iago64** [comment]
Buenas buenas!
Antes que nada, perdon por la demora, este issue generó una grieta un tanto grande entre los ayudantes y quisimos parar la pelota y tomar una decisión unánime para no andar dando vueltas.

La respuesta es la más simple posible: Primero llenen la memoria y recien ahi ejecuten cualquier algoritmo de reemplazo (ya sea Circular, LRU o BSU), asi que si tienen un hueco sea donde sea y entra lo que están necesitando guardar, haganlo :)

Saludos.-

**Comment by iago64** [comment]
@acerbonimartin Te queda alguna duda o podemos dar por cerrado el issue?

**Comment by acerbonimartin** [comment]
Sisii ahí me quedó claro, gracias
