### ISSUE TITLE
Duda comando Listar

### ISSUE THREAD

**Issue by LeandroMauro** [sisoputnfrba/foro#1157]
Hola

Quería consultar acerca del comando "Listar" de la Consola, cual vendría a ser el recurso que se le enviaría por parámetro. De entrada interpreté que se refería a una clave, y que se listaban los ESIS que estaban bloqueados esperando por esta clave, pero después vi que esto lo pedía en el comando "Status"

Saludos

**Comment by afilgueira** [comment]
Buenas, a ojo diría que efectivamente son muy parecidos por esto que decís. Lo chequeamos y les contesto. Saludos!

**Comment by agusmoles** [comment]
Fijate que el status pide otras cosas ademas de listar los ESIS que estan bloqueados esperando por la clave. Es decir, solamente esa parte coinciden, despues el status agrega que tenes que saber el valor (comunicandote con el **Coordinador** y la **Instancia correspondiente**, la instancia donde esta guardada o se guardaria la clave (si es que no tiene valor).

Saludos!

**Comment by LeandroMauro** [comment]
Ok, me parecía raro porque es como que el comando Status terminaba incluyendo entre otras cosas a la funcionalidad del comando Listar, pero si es así listo, lo encaro de esa forma

Gracias!!

**Comment by iago64** [comment]
Buenas buenas!

Si, nos quedaron parecidos los comandos, de hecho el listar es como una operación más acotada del Status.
Les spoileo donde estaba la idea, con status podíamos ver todo lo referente a las claves y con listar solo listar los esis bloqueados para hacer mas rapido las pruebas y poder por ej ver nosotros a mano los deadlock para comparar con el resultado que les dé a uds el algoritmo de detección.

Abrazo!
