### ISSUE TITLE
Duda comandos 'desbloquear'/'bloquear'

### ISSUE THREAD

**Issue by FrancoEsposta** [sisoputnfrba/foro#1158]
Buenas!!

Duda 1: 
    Leyendo issues anteriores (#1140) vimos que dicen que ante la ejecución del comando 'desbloquear' sobre una clave que la tiene asignada un ESIx, y no hay ningun otro ESI que esté bloqueado para esa clave, se debe desalojar la clave para el ESI que la posee y así liberarla para que cualquiera la pueda tomar, generando así que cuando el ESIx quiera hacer un SET o STORE sobre la clave que en algún momento previo tomó exitosamente falle la operación abortando dicho ESI. Queríamos confirmar que esto es así antes de proceder a cambiar nuestra implementación.

Duda 2:
    Por otro lado, tenemos la duda de como se espera que se comporte el sistema cuando se ejecuta el comando 'bloquear' sobre una clave para un determinado ESI, el cual ya tiene asignada dicha clave. Una posible implementación que se nos ocurre para esto podría ser desalojar la clave para el ESI. Por ejemplo:

1) ESI1 tiene jugador
2) ESI2 bloqueado para jugador por ejecución propia
3) ejecutamos el comando "bloquear jugador ESI1"
4) desalojamos jugador de ESI1
5) bloqueamos ESI1 para jugador (lo agregamos a la cola de bloqueados)
6) el ESI2 toma (cuando le corresponda) la clave jugador
7) desbloqueamos jugador por consola (resultando en el desbloqueo de ESI1 al ser el único que estaba esperandola)
8) ESI1 intenta hacer SET/STORE sobre jugador (cuando lo dicte la planificación)
9) Falla ESI1 y aborta su ejecución

Si esta es la idea de como se debe comportar el sistema ante una situación de este estilo, nos aparecen dos dudas al respecto. 
          2.1) La primera es que el comando 'bloquear', por atrás, estaría haciendo un 'desbloquear' ¿Esto está bien?
          2.2) Y la 2da es si es correcto que el ESI1 termine abortando como dice el issue mencionado previamente (#1140)

Otra opción que se nos ocurre es que, debido a que el ESI1 ya posee la clave jugador, dicho ESI no pueda ser bloqueado para esa clave. De esta forma el ESI no se ve saboteado por la consola y además nos evitamos que se desbloqueen otros ESIs por consecuencia de la ejecución de este comando.

**Comment by iago64** [comment]
Buenas buenas!!
Me encanta que pongan puntos con las dudas, asi es mas fácil de responder 😸 
Duda 1: Perfecto asi es la idea.

Duda 2: No es un comportamiento que hayamos pensado para las pruebas, eventualmente bien podrian decir, ese recurso actualmente es el dueño de la clave y no hacer mas nada, lo que plantearon es demasiado complejo para lo que se busca en el TP, con lo cual no se la compliquen con el caso de que les tiremos un bloquear a una clave que ya tienen (lo que si sean buenos con el log de estos mensajes así nos queda claro al momento de la corrección por que "no pasa nada")

Abrazo!

**Comment by FrancoEsposta** [comment]
Esa era la idea de los puntos jajajaj
Excelente. Muchas gracias!! Cierro el issue

Abrazo!
Franco
