### ISSUE TITLE
Comando "pausar": "Interrumpir" ejecución de un ESI

### ISSUE THREAD

**Issue by JuanQP** [sisoputnfrba/foro#1159]
Buenas!

Tengo una duda que seguramente debe ser conceptual, espero que no, pero si ese es el caso, pueden *mandarme a leer* :laughing: 

La consola de Planificador está funcionando sin problemas con pausar, continuar, listar, bloquear y desbloquear, los mensajes se envían y reciben sin problemas.

El problema ocurre con el comando `pausar` **mientras hay un ESI ejecutando**. Hay un hilo que es el de la consola, el cual está esperando un input. Al llegar el input, va a intentar tomar un *mutex*, si puede, va a utilizar el planificador.

Mientras tanto, en otro hilo está el planificador en sí ejecutando. El cual, para cada instrucción que quiere ejecutar proveniente de un ESI también va a tomar el mismo mutex. Por lo cual, con esto dicho, está claro que se puede ejecutar: o la consola, o el planificador, hay mutua exclusión.

A fines de evitar hablar de implementación y de hacer esto lo más sencillo posible voy a poner una versión simplificada de lo que está pasando. El código (a grandes rasgos) es así:

**Consola**
```c
pthread_mutex_lock(planificadorMutex);
ejecutarComando(comando);
pthread_mutex_unlock(planificadorMutex);
```

**Planificador**
```c
pthread_mutex_lock(planificadorMutex);
// Muchas instrucciones...
pthread_mutex_unlock(planificadorMutex);
```

Cuando el Planificador está enviando mensajes a un ESI, yo utilizo el comando `pausar`, lo que esperaría es que cuando el Planificador haga el `unlock()`, empiece a ejecutar inmediatamente la consola (ya que trató de lockear el mutex mientras estaba ocupado). Sin embargo esto no ocurre: lo que ocurre es que el planificador hace `unlock()` y luego `lock()` (sigue enviando instrucciones) como si no hubiese pasado nada. Cuando finaliza, recién ahí el hilo de la consola ejecuta el comando (o sea, estuvo esperando efectivamente el mutex), y luego lo libera.

Tenía entendido que mutex o los semáforos podían manejar *una lista de espera* (o sea, si alguien intentó lockear un mutex o semáforo, entonces al desbloquearse, va a ser el siguiente en ejecutar). Pero no es esto lo que está pasando.

¿Es la idea del TP implementar nuestra propia lista de espera? ¿O me estoy metiendo en un bolonqui bárbaro? ¡Gracias!

**Comment by JuanQP** [comment]
Me quedo tranquilo entonces que al menos estaba bien planteado lo que quise hacer. Hoy a la tarde pruebo esto que comentaste y te digo

**Comment by iago64** [comment]
Buenisimo, si tenes alguna duda con lo que te dice helgrind avisame y lo vemos en detalle asi vemos que es lo que pasa 🙂

**Comment by afilgueira** [comment]
Ojo, los semáforos con lista de espera son los que no tienen espera activa y son útiles con una sóla CPU.

Es posible que, si tu VM está corriendo en variad

**Comment by JuanQP** [comment]
Quería dejar estos dos diagramas de secuencia para dejar un poco más claro lo que quería expresar, me dí cuenta que es medio complicado de explicar con texto

## Comportamiento esperado
![image](https://user-images.githubusercontent.com/11776905/41811163-bb8e9836-76e0-11e8-9651-bdeacdc982b4.png)


## Comportamiento real
![image](https://user-images.githubusercontent.com/11776905/41811097-6c0886f6-76df-11e8-9dc3-4a55dec153f7.png)

Lo corrí con Helgrind tal cual lo mencionaste @iago64 , y también probé algo que me sugirió @evguenitessov : "_¿Siempre espera a que termine de ejecutar un script? ¿O a veces interrumpe en el medio?_", y me dí cuenta que si pongo un sleep() después de cada instrucción finalizada, entonces **el hilo de la consola si puede interrumpir**.

Lo que esto me deja a mí en claro es lo siguiente: es como _si el hilo del Planificador libera el mutex y lo vuelve a tomar tan rápido que no deja que el hilo de la consola se desbloquee_. Pero si fuerzo una espera antes de que vuelva a tomar el mutex, entonces, la Consola "_tiene tiempo_" de desbloquearse.

Por lo cual, ahora tengo la siguiente pregunta: Viendo que en las pruebas del checkpoint pasado el "pausar" y "reanudar" solo se hacían cuando no había ningún ESI ejecutando, ¿Tiene sentido hacer lo que estoy tratando de hacer? Si es un requerimiento pausar mientras un ESI está mandando mensajes en el mismo momento, entonces sigo la sugerencia de @afilgueira , y pienso cómo solucionarlo

**Comment by JuanQP** [comment]
La salida de Valgrind (con Helgrind) de una ejecución de un ESI al cual logré pausar en el medio (pero dejó pasar varias instrucciones antes)

[valgrind.txt](https://github.com/sisoputnfrba/foro/files/2130085/valgrind.txt)

No encontré información en ese log que tenga que ver estrictamente con lo que estoy planteando. Me señala una condición de carrera pero en la consola, pero es porque la Consola además de un prompt tiene información de en qué estado está el planificador, y esa información (obviamente) en la ejecución de la próxima instrucción va a ser modificada, pero no tiene nada que ver con el mutex del que estamos hablando :disappointed:

**Comment by iago64** [comment]
Buenas buenas!!

Valgrind es medio mala leche con los output y de regalo en helgrind las cosas son un poco mas mala leche porque te dice que es "posible"

![image](https://user-images.githubusercontent.com/1622109/41814079-9f907ddc-7719-11e8-95a0-549e92e2a0fd.png)

Pegale una revisada a las lineas que te marque a ver que tenes ahi, porque fijate que te dice en una parte estas teniendo un semaforo tomado en un hilo y en el otro no, con lo cual, posiblemente lo que te falte sea definir el mutex a nivel global (a.k.a: arriba del main)

Abrazo!

**Comment by JuanQP** [comment]
El fuente donde está el `main()` es `planificador.c` y en ese fuente tiene definido el mutex arriba del main, es global
```c
pthread_mutex_t planificadorMutex;
```

Y eventualmente se inicializa

```c
pthread_mutex_init(&planificadorMutex, NULL);
```

Las líneas que señalaste no ocurren al mismo tiempo, de hecho, la primer línea que remarcaste se ejecuta al poner "exit" en la consola, lo que hace es liberar la memoria del struct del planificador justo antes de que finalice la aplicación. Y esa otra línea que marcaste es lo que hace el planificador cuando finaliza un proceso, pero esto último no ocurre al mismo tiempo del exit. El script primero dejé que finalice, y después escribí exit.

Lo que mencioné en https://github.com/sisoputnfrba/foro/issues/1159#issuecomment-399693242 ¿Tiene sentido al menos? ¿O no es lo que debería ocurrir al usar un mutex?

Muchas gracias!

**Comment by iago64** [comment]
Buenas buenas!
En las pruebas del checkpoint se puso de pausar cuando no habia scripts porque era una prueba simple :)
Eventualmente en las pruebas finales lo que puede pasar es que el pausar / reanudar sea entre la ejecución de los scripts. Lo importante es que siempre tenes que esperar que termine la rafaga en curso.

Lo que puede estarte pasando es que el mutex en el caso de frenar la planificación lo que podrias hacer seria cambiar ese mutex por un semaforo contador a ver si se te resuelve el inconveniente, ya que sigo sin terminar de entender por que cuando libera el mutex no levanta automaticamente el que esta bloquedo.

Abrazo.-

**Comment by JuanQP** [comment]
Anteriormente tenía un semáforo y luego lo cambié para que use el mutex de pthread porque también quería ver si cambiaba en algo, pero el comportamiento era el mismo.

Es muy raro ese comportamiento de no levantar automáticamente el otro thread y es aún más raro ver que si pongo un sleep() entonces si lo levanta. De más esta decir que no es determinista, a veces deja pasar una o dos instrucciones antes de que tome el control la consola y a veces son más instrucciones o directamente hasta que termine el script 🤔

**Comment by JuanQP** [comment]
Acá encontré un post donde describen exactamente el comportamiento que esta teniendo mi programa, y al parecer es "el esperado". Voy a dejar el link acá porque quizás otra persona se va a encontrar con la misma situación

https://stackoverflow.com/questions/16138072/pthread-mutex-not-updating-fast-enough-so-one-thread-hogs-the-lock

**Comment by JuanQP** [comment]
@iago64 , por lo que leí en la documentación de pthread, y un poco sobre la manera en que linux planifica, ví que el comportamiento de lo que está ocurriendo **es el comportamiento esperado**. [Como dice acá](https://www.systutorials.com/docs/linux/man/7-sched/#lbAI) y [acá](https://stackoverflow.com/questions/33724063/do-pthread-mutex-unlock-immediate-context-switch), la manera en que planifica linux por default al utilizar pthread es a través de un algoritmo en el cual se encarga de setearles prioridades, así que en el caso de un `unlock()` o de un `post()`, **no está garantizado nunca que otro hilo empiece a ejecutar**, lo que puede ocurrir (y eso está ocurriendo) es que el algoritmo de planificación vuelve a dejar que ese hilo siga ejecutando, por éso puede tomar el mutex nuevamente.

Traté de utilizar otra función de pthread `sched_yield()`, justo después del `pthread_mutex_unlock()` el cual fuerza al hilo actual a abandonar la utilización de la CPU. Si bien esto hizo que mandar la instrucción "pausar" sea "*un poco más determinista*" (ya que el hilo de la consola tiene una segunda oportunidad de ejecutar), sigue siendo pthread (o el sistema operativo) el que se encarga de decidir cuál hilo va a continuar ejecutando: pero potencialmente puede ser el mismo.

Así tal cual está, puede interrumpir un ESI durante la ejecución, pero podría pasar 2 o 3 instrucciones hasta que lo haga.

Parece que interrumpir la ejecución de un ESI inmediatamente después de un `unlock()` no está garantizada con pthread. Supongo que el consejo de @afilgueira implica utilizar otro tipo de biblioteca? ¿O quizás tener nuestra propia solución de software para hacer que un hilo tenga más prioridad para ejecutar que otro?

Por lo pronto me parece que nos vamos a acercar el sábado para ver si esto está mal planteado, o si estamos usando de manera incorrecta algo :laughing:

**Comment by iago64** [comment]
@JuanQP Me agarraste justo terminando de leer un poco mas de pthread al respecto y estaba viendo que alternativas te podria recomendar y que no sean una patada en la pera de implementar.

Por lo que estuve viendo, minimamente, tendrias una opcion bastante "rapida" de implementar que sería un "flag de planificación", en ese flag lo que harían seria controlar si pueden planificar (ya sea por no tener ESIs conectados o porque la pausaron por la consola) y que eso lo implementan bastante rapido con el mutex para asegurar que los 2 hilos no toquen el "flag" y el "flag" o semáforo contador (si si, trabajar con doble semáforos) en donde en cuanto tengan que parar la planificación lo fuerzan a 0 cosa de que en el momento que quieran planificar hacen el lock y ahí se quedan. La forma de hacer eso seria con el [sem_init()](http://man7.org/linux/man-pages/man3/sem_init.3.html) donde le pueden pasar 0 (para frenar) o la cantidad de ESIs que tengan en la cola de ready (para reanudar)

Abrazo!

**Comment by afilgueira** [comment]
Es que en realidad, usar un mutex y esperar un cierto orden está conceptualmente mal. La idea del mutex es evitar la condición de carrera. Por eso medio que nadie se preocupa por ordenarlos FIFO o de otra forma. Al margen de cómo solucionarlo, recuerden esto.

Si lo que necesitan es ordenar, probablemente les convenga pensar en una lista extra, un flag (con su mutex para que no se pisen, como dice Dami, etc).

Éxitos con eso!

**Comment by JuanQP** [comment]
[En este link](https://www.linuxquestions.org/questions/programming-9/how-to-have-fifo-thread-mutex-in-c-896655/#post4441272) encontré a alguien que tenía el mismo problema, y vamos a seguir la idea que proponen ya que utiliza exactamente las dos cosas que ustedes mencionaron: lista y flag y además hace uso de pthread

Muchas gracias a los dos :smiley:

**Comment by pmorrone10** [comment]
@JuanQP pudiste resolver esto? me estoy dando cuenta que la consola no esta stopeando todo en el instante que yo pido, sino un par de sentencias mas adelante.

**Comment by JuanQP** [comment]
Si, conceptualmente lo que hice fue "_darle la posibilidad al mutex de ordenar por FIFO_", fijate en el último comentario que hice, que dejé un link donde en esa misma página están debatiendo ésto, hay varios snippets que podés chequear que solucionan el problema, y todos usan las mismas herramientas que vimos en la cursada (pthread y C). A mí me funcionó de diez (lo probé de varias maneras) y el TP lo tengo aprobado, más allá del problema en sí, me pareció muy interesante el [por qué se pausa varias instrucciones más adelante](https://stackoverflow.com/a/42428112)

> The OS scheduler might even be more likely to allow an already-running thread to continue to run and obtain the lock.

Lo cual no es lo que queremos, por éso es necesario (de alguna forma) establecer un "orden" a las cosas que tienen que ejecutarse según el tiempo de llegada, y usar mutex y semáforos por sí solo no nos garantizan ese comportamiento

**Comment by pmorrone10** [comment]
muchas gracias, vamos a ver que sale.
