### ISSUE TITLE
Consulta errata 3 (Desconexión de instancia)

### ISSUE THREAD

**Issue by juanfatur** [sisoputnfrba/foro#1160]
Buenas! Viendo las correcciones que hicieron en la errata 3, hay algo que nos parece contradictorio en la consigna:
- Por un lado en la parte de Coordinador dice (modificado en la errata):
`En el caso que el coordinador decida en el paso 2 que la operación no puede ser ejecutada porque la instancia no existe más en el sistema(^9), le avisará al Planificador, el Planificador abortará al ESI en cuestión. `**No se deberán tomar acciones sobre los ESIs bloqueados para dicha clave ya que la instancia puede reincorporarse en el sistema a futuro.**

-Por otro, en Distribución dice:
`Durante la ejecución del Sistema, existe la posibilidad de que una o más Instancias dejen de estar disponibles para el Coordinador de Re Distinto. Ante éstas situaciones, el Coordinador deberá ajustar su distribución de forma acorde a la cantidad de Instancias disponibles. No se deberá eliminar una clave de las tablas del coordinador si la instancia de desconectó; solo se elimina cuando un ESI intenta acceder a ella; de tal forma, si la instancia se reincorpora previo al uso de la clave; la desconexión sera transparente para el/los ESI que deseen operar con dicha clave.`

Suponiendo el siguiente caso:
El ESI 1 tiene asignada la clave A. El ESI 2 está bloqueado esperando la misma clave.
1- El ESI 1 hace SET sobre la clave A. Se asigna la clave A a la Instancia 1.
2- La Instancia 1 se cae. (No se borra ninguna clave de las tablas del Coordinador)
3- El ESI 1 vuelve a hacer SET sobre la clave A. Al no estar la instancia, se aborta el ESI y se borra la clave A de las tablas del Coordinador. Por haber abortado el ESI 1, en el Planificador la clave A está libre (y el ESI 2, desbloqueado).
4- El ESI 2 hace GET sobre la clave A.
5- El ESI 2 hace SET sobre la clave A.

En este punto, da igual si la instancia volvió o no a conectarse, porque el Coordinador creará nuevamente la clave y se la asignará a una instancia cualquiera. Es correcto?

**Comment by iago64** [comment]
Buenas buenas!

Si, una vez que "se les cae la instancia" y no tienen mas la clave, al momento de que otro proceso les haga el GET la vuelven a crear en una nueva instancia según lo que les diga el algoritmo de distribución.

Saludos.-

**Comment by juanfatur** [comment]
Entonces la frase en negrita no tiene sentido.

**Comment by juanfatur** [comment]
(Perdón, lo cerré sin querer)

**Comment by iago64** [comment]
En realidad si tiene sentido, vos no tenes que tocar los ESIs en la cola de bloqueados, la idea es que pueden morir de inanicion o que alguien se tome la molestias de desbloquearlos por consola :)

**Comment by natoszme** [comment]
@iago64 el get crea la clave en la Instancia? Por el comentario de arriba digo :astonished:

En cuanto a lo de que se mueran por inhanición, si el planificador los elige para ejecutar y se borró la clave de esa instancia, cuando vuelvan a hacer get y después un set, se creará la clave en otra instancia. No veo por qué decís lo de starvation, me iluminas? Jaja

**Comment by iago64** [comment]
No señor, mala mía, quise resumir y la pifie, el GET crea la clave y el SET asigna la instancia :)

**Comment by juanfatur** [comment]
Coincido con @natoszme , si el ESI que tenía tomada la clave se abortó, los ESIs que la estaban esperando deberían poder tomarla.

**Comment by iago64** [comment]
En el enunciado dice que la instancia se puede reincorporar (y como spoiler les aviso que va a pasar)
La idea es que los procesos que están bloqueados para una clave siguen bloqueados porque nadie los desbloqueo ya que eso es tarea del planificador y el problema de las claves inaccesibles es problema del duo Coordinador / Instancia

**Comment by natoszme** [comment]
Claro, porque el planificador nunca va a planificar esos esis porque, al menos que se de el caso que decís, los esis van a estar en "bloqueados". Gracias!

**Comment by iago64** [comment]
Nada que agradecer, me quedo tranquilo que se entendio el motivo por el cual esos esis quedan ahi :).

P.D: cuando se pasan los efectos del quraplus es un mal momento para contestar dudas en el foro :sad:

**Comment by ricardoAguirreSanchez** [comment]
Buenas,
Una consulta más, ya que no me quedo del todo claro, del ejemplo que se está hablando al inicio del issue, el Punto 3 
"3- El ESI 1 vuelve a hacer SET sobre la clave A. Al no estar la instancia, se aborta el ESI y se borra la clave A de las tablas del Coordinador. Por haber abortado el ESI 1, en el Planificador la clave A está libre (y el ESI 2, desbloqueado)." 

Es correcto que se desbloquee al ESI2 ?

Saludos.

**Comment by juanfatur** [comment]
Claro, esa es mi duda. Aparentemente no debería desbloquearse el ESI 2, sino que debería quedar la clave "Tomada por falta de instancia"? Es rarísimo la verdad...

**Comment by juanfatur** [comment]
Con ese criterio, al abortar al ESI 1 deberían liberarse todas las claves que tuviera tomadas, menos la última que solicitó...

**Comment by natoszme** [comment]
Para mi, por lo que dice la consigna en
> No se deberán tomar acciones sobre los ESIs bloqueados para dicha clave ya que la instancia puede reincorporarse en el sistema a futuro.
el ESI 2 sigue bloqueado hasta que alguien le haga un desbloquear desde la consola

**Comment by iago64** [comment]
Es como dice @natoszme.
Igual existe otra posibilidad y es que la instancia reconecte y el ESI que tenia la clave pueda hacer el STORE y que todo siga sin problemas

**Comment by juanfatur** [comment]
A cual ESI te referís? (Siguiendo el ejemplo del issue)

**Comment by natoszme** [comment]
@iago64  Agregando a lo que comentaste antes, los ESIs bloqueados también podrían empezar a desbloquearse si viene un ESI nuevo que toma la clave con un get y después la libera con store

**Comment by iago64** [comment]
@natoszme EXACTO! de hecho mas o menos es la prueba que estaba pensando (ahora tengo que cambiarla un poquito y asegurarme que no sea tan rebuscada de hacer  😅)

**Comment by juanfatur** [comment]
@iago64 a cuál ESI te referís?

**Comment by ricardoAguirreSanchez** [comment]
Y si esta situación pasar cuando un ESI en vez de hacer SET hiciera STORE y detecto que la instancia se desconecto:
1.- Seria hacer lo mismo? abortar al esi y NO liberar a ningún otro ESI que este esperando esa clave (dado que error de clave inaccesible aplica a SET/STORE)
2.- Entonces para store, primero debería verificar que esta tarea lo haga la instancia sin problema y luego pedirle al planificador que también lo haga? (ya que store genera trabajo tanto en la instancia como en el planificador)

**Comment by iago64** [comment]
@juanfatur En que contexto haces la pregunta?
Tenemos 2 posibilidades a detallar:
1.- El ESI1 (el cual tiene la clave que es temporalmente inaccesible), sigue (ya que las instrucciones son sobre otra clave que no esta inaccesible) y cuando ejecuta nuevamente sobre la clave caída, la misma ya esta disponible porque reconectamos la instancia y llega a un STORE que libera la clave sin ningun problema. En ese caso los ESIs que esten en la cola de bloqueados, va a liberar al primero y la caida fue totalmente transparente para todos.
2.- El ESI1 intenta hacer un SET / STORE de la clave inaccesible y aborta, pero luego viene **OTRO ESI** y hace un GET de la misma clave y esta se crea nuevamente, hacemos 1 o varios SETs y luego un STORE. En este punto desbloqueamos al primero de la lista de bloqueados para la clave. En este caso tuvimos un ESI1 que aborto por clave inaccesible y tuvimos otro que creo la clave nuevamente, ejecuto y libero sin problemas. En este caso la caída no fue transparente para el ESI1.

@ricardoAguirreSanchez 
1.- Si también tiene que abortar porque al ir a la instancia a pedirle que haga el STORE la misma es inaccesible. Y no deberias hacer nada con la lista de bloqueados para esa clave.
2.- Exacto, primero te aseguras que la instancia pueda cumplir con el STORE y despues le decis al planificador que hiciste el STORE de la clave.

Saludos.-

**Comment by vickyRuiz** [comment]
Creo que estoy un poco confundida...

En nuestro TP, lo que hicimos es que el coordinador no se fija si una instancia está conectada a menos que se pida una operación que lo amerite. 

De los escenarios planteados por @iago64 en el último mensaje, el primero no nos sucedería nunca, porque si el ESI1 no intenta hacer SET o STORE, el coordinador ni se entera que esa instancia se cayó. 

Si tratara de hacer SET o STORE (escenario 2), sí nos enteramos, borramos la clave de la tabla de claves en el coordinador, abortamos el ESI1. El primero de la lista de los ESIs que estaba esperando a esta clave pasa a ready, y cuando le toque hacer GET, va a crear la clave sin instancia asociada, y luego va a ejecutar. 

Por eso, entiendo que no quedarían en inanición los procesos bloqueados para esa clave en ningún caso. 

Qué es lo que no estoy viendo?

**Comment by iago64** [comment]
Buenas buenas!

El escenario 1 es facil de que pase, simplemente es hacer que un script haga un SET o un STORE de una clave inaccesible, no es lo mas dificil (y de hecho es una de las pruebas mas básicas que vamos a tener)

Respecto al escenario 2, no deberían tocar ninguno de la lista de bloqueados, ya que nadie "liberó" la clave, sino más bien que están en una situación un tanto gris y la clave estaría retenida por nadie pero tendrían ESIs bloqueados (algo asi como cuando inician con claves bloqueadas por el sistema)

Saludos.-

**Comment by vickyRuiz** [comment]
No te sigo 😓 Voy a insistir una vez más, porque me da miedo que estemos interpretando el enunciado mal, y que tengamos que dar marcha atrás con muchas cosas. 

> 1.- El ESI1 (el cual tiene la clave que es temporalmente inaccesible), sigue (ya que las instrucciones son sobre otra clave que no esta inaccesible) y cuando ejecuta nuevamente sobre la clave caída, la misma ya esta disponible porque reconectamos la instancia y llega a un STORE que libera la clave sin ningun problema. En ese caso los ESIs que esten en la cola de bloqueados, va a liberar al primero y la caida fue totalmente transparente para todos.

En nuestro TP no nos enteraríamos de que esto pasó, porque sólo averiguamos si una instancia sigue conectada cuando un ESI nos pide ejecutar un SET o STORE. Sólo nos enteraríamos que la instancia que tiene la clave que ESI1 espera se bajó, si otro ESIx pide una clave que está en la misma instancia. En ese caso, borramos la clave que pidió ESIx, y seguimos con todas las demás claves igual hasta que le toque hacer lo suyo a ESI1 y con un poco de suerte, la instancia volvió. 

> 2.- El ESI1 intenta hacer un SET / STORE de la clave inaccesible y aborta, pero luego viene OTRO ESI y hace un GET de la misma clave y esta se crea nuevamente, hacemos 1 o varios SETs y luego un STORE. En este punto desbloqueamos al primero de la lista de bloqueados para la clave. En este caso tuvimos un ESI1 que aborto por clave inaccesible y tuvimos otro que creo la clave nuevamente, ejecuto y libero sin problemas. En este caso la caída no fue transparente para el ESI1.

Esto es lo que a nosotros nos pasaría más frecuentemente. Como dije arriba para el ESIx, en este caso abortamos al ESI, y borramos la clave de la tabla. 

Quizás acá haya una diferencia con lo que estamos haciendo... cuando abortamos al ESI, nosotros interpretamos que siempre libera todos los recursos que tiene. El enunciado dice, en la sección Coordinador:

> Cabe aclarar que la finalización de un ESI libera los recursos que este tenía tomados.

En el caso de que se baje una instancia, deberíamos abortar el ESI sin liberar sus recursos?

**Comment by iago64** [comment]
Buenas buenas!
Tranquila, no hay drama, para eso estoy, vamos por partes:

> En nuestro TP no nos enteraríamos de que esto pasó, porque sólo averiguamos si una instancia sigue conectada cuando un ESI nos pide ejecutar un SET o STORE. Sólo nos enteraríamos que la instancia que tiene la clave que ESI1 espera se bajó, si otro ESIx pide una clave que está en la misma instancia. En ese caso, borramos la clave que pidió ESIx, y seguimos con todas las demás claves igual hasta que le toque hacer lo suyo a ESI1 y con un poco de suerte, la instancia volvió.

Esta perfecto, no tienen por que enterarse en el momento de la caída, si la instancia se cae y se dan cuenta al momento de pedirle algo esta joya, lo único que deberían poder es que si se reconecta una instancia es marcar las claves como disponibles de nuevo.

>Esto es lo que a nosotros nos pasaría más frecuentemente. Como dije arriba para el ESIx, en este caso abortamos al ESI, y borramos la clave de la tabla.

Esto esta perfecto.

Respecto a lo ultimo:

>En el caso de que se baje una instancia, deberíamos abortar el ESI sin liberar sus recursos?

Estamos terminando de debatir este tema, estimo que en hoy o mañana ya tengamos la respuesta final, de momento no cambies nada :)

Saludos.-

**Comment by juanfatur** [comment]
Chicos estuve ayer unas 6 horas modificando gran parte del planificador para incorporar la posibilidad de este caso (que una clave esté libre, pero con esis bloqueados esperándola, cosa que hasta ahora nunca podía ocurrir). Por favor confirmen cómo es.

**Comment by iago64** [comment]
Buenas buenas!
Despues de debatir bastante llegamos a la solucion de que **el camino ideal es que cuando se aborte un ESI no se haga nada con la cola de bloqueados**.

Eventualmente _si ya tienen implementado que se libere el primer ESI bloqueado no va a ser causal de desaprobar_ ya que como dijo Adriano, _esto es el 0.1% del TP_, es un caso muy borde y que si el resto del TP funciona correctamente no tendria el mas minimo sentido que sea causa de deaprobar.

Saludos.-

**Comment by iago64** [comment]
@juanfatur Todavía te quedan dudas o cerramos el tema?

**Comment by juanfatur** [comment]
Todo ok, cerrado!
