### ISSUE TITLE
Error de virtualbox

### ISSUE THREAD

**Issue by lucasvalenzuela93** [sisoputnfrba/foro#1161]
Buenas, tengo este problema con virtual box, ya probe desactivando hyper-v, reinstalando virtualbox, antes me andaba bien pero despues me dejo de andar. adjunto una captura de pantalla del error que me tira.
![sin titulo](https://user-images.githubusercontent.com/11969660/41740879-ce894764-756f-11e8-909a-21a0512f0b94.jpg)

**Comment by mgarciaisaia** [comment]
:wave: En la ventana principal de VirtualBox, dale click derecho a la VM y poné "Show logs". Y subite ese archivo, así vemos qué onda. Porque acá no se ve el inicio del error, y andá a saber qué está pasando.

**Comment by lucasvalenzuela93** [comment]
lo paso como un.txt, aclaro que tengo activada la virtualizacion desde la bios.
[lubuntu-2018-06-21-17-04-29.log](https://github.com/sisoputnfrba/foro/files/2125173/lubuntu-2018-06-21-17-04-29.log)

**Comment by mgarciaisaia** [comment]
No veo nada raro ahí, che.

Fijate si podés abrir de nuevo la VM y, cuando te salta el error, scrolleá para arriba con [Shift + Pg Up](https://unix.stackexchange.com/a/60387/49371) para ver si encontrás el inicio del error. Capaz eso ayude un poco más 🤷

**Comment by iago64** [comment]
@lucasvalenzuela93  Te queda alguna duda o podemos dar por cerrado el issue?

**Comment by lucasvalenzuela93** [comment]
La verdad no pude encontar solucion, no me funciono la combinacion de las teclas, supongo que no me queda de otra que restaurar windows 10 a su estado de fabrica, gracias.

**Comment by lucasvalenzuela93** [comment]
No no, tengo una notebook, probe usando la tecla shift + fn pg up y nada, probe varias veces reinstalando virtualbox y la creacion de lubuntu, las soluciones de google, que recomiendan cambiar el procesador, en la opciones de sistema y tampoco funciono.

**Comment by iago64** [comment]
Lo de la tecla fn, si mal no recuerdo podes cambiarlo desde el bios/uefi de la maquina para no tener que apretar fn para usarlo (ya que depende el modelo el apretar shift no funca con fn, o al menos no en una de las que tengo en casa)

**Comment by lucasvalenzuela93** [comment]
Lo intente tmb; nada :(

**Comment by iago64** [comment]
Consulta, si dehabilitas las siguientes opciones te sigue dando el error?

![image](https://user-images.githubusercontent.com/1622109/41886095-4061d464-78d1-11e8-83ae-835aaaba696f.png)
![image](https://user-images.githubusercontent.com/1622109/41886101-4d093680-78d1-11e8-93f7-16166fb37afc.png)

Capaz le encontramos una vuelta al asunto por ese lado, en especial la parte de VT-x/AMD-V ya que esas son características especiales que tenes que habilitarlas desde el bios de la PC para que la virtualización sea full HW, caso contrario te las toma por SW y generalmente levanta sin mayores dramas (aunque anda mas lenta la VM)

Abrazo.-

**Comment by lucasvalenzuela93** [comment]
Si desabilito PAE/NX cuando quiero iniciar la vm me tira error (normamente carga el inicio, me muestra un contandor de tiempp en disminucion y me pide que elija alguna de las opciones, ej: *Ubuntu, Advanced options for Ubuntu).
En cuanto a la configuracion de aceleracion, no puedo acceder a la pestaña directamente.

**Comment by iago64** [comment]
Ok, una pregunta, en el BIOS / UEFI de tu pc, tenes habilitada la virtualización por Hw?

**Comment by lucasvalenzuela93** [comment]
Sisi, por que la vm me andaba normalmente, y despues me paso esto.

**Comment by iago64** [comment]
Después de que empezó a pasarte esto? Un update de Windows?

**Comment by lucasvalenzuela93** [comment]
Si, fue despues de una actualixacion de windows 10, la ultima grande que mandaron

**Comment by tferraro** [comment]
Esto tiene toda la pinta que algo de virtualbox se corrompió cuando windows se actualizó y nunca se enteró. Esto, por lo general, no se soluciona solamente con desinstalando, porque como mete mano con archivitos y registrando hardware virtual, toca bastante el registro de windows, esa gran bolsa de gatos que hace que nada funcione bien en windows.

Si no te agarra de ninguna manera, una posibilidad _a la que no querría llegar_ es restablecer de "fabrica" el windows actualizado y borrar los datos de instalaciones viejas con el Liberador de Espacio en Disco. Así queda lo más limpia posible y deberías poder instalar y correr el virtualbox sin problemas.

Pero sigamos indagando, estoy desvariando :stuck_out_tongue:

**Comment by iago64** [comment]
Bueno, ahora empezamos a tener algo mas de contexto, si fue despues del ultimo parche de Windows 10, entonces como dice Tom, es mucho muy posible que virtualbox haya quedado medio estrolado pero de la forma fiera.
Para empezar a ver que onda, primero, proba de desinstalar virtual box.
Despues fijate si te elimina el contenido / la carpeta: `C:\Users\[Usuario de Windows]\Appdata\Local\.virtualbox` si bien ahi tenes logs tambien tenes algunos certificados que capaz quedaron medio estrolados.
Despues en `C:\Windows\System32\drivers` deberias encontrar un par de drivers de Virtual Box que son los adaptadores de red:
![image](https://user-images.githubusercontent.com/1622109/41948548-aca7ada2-7993-11e8-9ec9-fa45459de19d.png)
Tambien hacelos crema.
Pegale una reiniciada a Windows (porque windows no recarga nada core en runtime)
Y una vez que levante trata de instalar VirtualBox de nuevo a ver si ahora si levanta la VM sin drama.

Abrazo!

**Comment by lucasvalenzuela93** [comment]
Probe como me dijiste iago64, tira el mismo error despues de instalar todo de nuevo.

**Comment by iago64** [comment]
Ok, entonces esto claramente lo mejor va a ser verlo con alguien en persona, fijate en la [planilla de soporte](http://faq.utnso.com/soporte) a ver quien esta y en que sede. 
Seguramente le puedan encontrar una vuelta en persona mucho mas rápido que por este medio.

Abrazo.-

**Comment by iago64** [comment]
@lucasvalenzuela93 Pudiste resolver el tema con alguno de los chicos en el soporte presencial?

**Comment by lucasvalenzuela93** [comment]
No, no pude ir a campus el sabado, igualmente restaure windows 10 a su estado de fabric y sin embargo tampoco funciono.

**Comment by iago64** [comment]
Este sabado entiendo que tienen parcial y ahí van a estar al menos con horario confirmado por ahora Adriano y Tomas, seguro ellos te pueden dar una mano.

**Comment by iago64** [comment]
@lucasvalenzuela93 pudiste acercarte a ver el problema con Tomas o Adriano?

**Comment by lucasvalenzuela93** [comment]
Si, y no se encontro otra solucion mas que el formateo completo desde cero, la restauracion de windows 10 a modo de fabrica no funciono. Segun entendi por lo que me explico uno de los ayudantes el tema puede ser que una actualizacion daño algo que se necesita. Gracias.
