### ISSUE TITLE
Memory leak al parsear operación GET con clave inválida

### ISSUE THREAD

**Issue by vickyRuiz** [sisoputnfrba/foro#1162]
Buenas noches! 

Corriendo pruebas, notamos que cuando el parser encuentra una clave inválida, aparecen algunos memory leaks. 

Ya comprobamos que cuando las claves son válidas, no tenemos ningún leak. También nos aseguramos de destruir la operación si es inválida, pero seguimos teniendo esos leaks. Este es nuestro código, con líneas comentadas con resultados de pruebas que hicimos para confirmar dónde surgen los leaks. 

```
flag_repeatOp = 0;
				t_esi_operacion parsed = parse(nueva_linea);

				//destruir_operacion(parsed); finalizarEsi(2203); //--> con script claveInvalida, acá ya hay leaks

				if(parsed.valido){
					interpretarLinea(parsed, nueva_linea);
				} else {
					log_error(logger, "La linea < %s > no es valida. Abortando ESI.\n", nueva_linea);
					destruir_operacion(parsed);
					finalizarEsi(EXIT_FAILURE);
				}
				code_result = EXECUTEOK;

				//finalizarEsi(2204); --> hay leaks

```

Valgrind nos devuelve esto: https://www.dropbox.com/s/ula6qp462mvq3pt/parsiGET.PNG?dl=0

Es posible que los leaks sean por un error del parser mismo, y no de nuestro código? Gracias!

**Comment by LeaTex** [comment]
@vickyRuiz ¿qué sería una "clave inválida" para ustedes.

Su supone que los scripts van a estar bien armados, por lo que los archivos deberían parsearse sin problemas.

**Comment by vickyRuiz** [comment]
Cierto, me olvidé de mencionar cuál era la clave inválida que usamos: 

GET holaquetal:holaquetal:holaquetal:holaquetal

Básicamente, es una clave de más de 40 caracteres, que parsi clasifica como valido = FALSE. Como está en el apartado de manejo de errores, entiendo que podría llegar a aparecer algo por el estilo.

**Comment by LeaTex** [comment]
Bueno, pueden revisar el código del Parsi para detectar el error.

Por lo que veo, lo que ocurre es que devuelve RETURN_ERROR sin liberar la memoria de auxLine ni split... creo.
Debe ser ahí que se lo está comiendo, pero son pocos bytes, nada grave me parece.
El tema sería si el script tiene 200 comandos para ejecutar, todos con claves inválidas. Sin embargo, dado que el ESI aborta luego de toparse con la primera, a lo sumo solo se pierde la memoria de la primera línea leída.

¿El comportamiento que notan ustedes es muy diferente?

Yo lo tomaría como memory leak si el proceso se mantiene corriendo, y se va comiendo la memoria de a poco sin liberarla, hasta el punto de ser extremadamente notorio. Por unos pocos bytes no me haría problema.

**Comment by iago64** [comment]
Buenas buenas!
Si, efectivamente tenemos ese pequeño leak :(
Pero tranqui, en el caso de los ESIs como la vida es muy efímera e intrascendente (como Sampaoli como DT de la selección), no se preocupen, los leak como tales nos van a importar y los vamos a estar revisando fuerte en Coordinador, Planificador e Instancias.

P.D: Las claves de 40 o más caracteres van a estar presentes en las pruebas (aunque ahora tengo que cambiar la temática por los acontecimientos recientes :cry: )

**Comment by vickyRuiz** [comment]
Genial, gracias por confirmarlo. Me quedo más tranquila. Nuestros ESIs no están tirando leaks más que en este caso si los quisieran testear 😎
