### ISSUE TITLE
Comunicacion Coordinador-Planificador

### ISSUE THREAD

**Issue by GabrielRuderman** [sisoputnfrba/foro#1163]
Buenas! Estamos teniendo una duda sobre cuál es el próposito de la comunicación entre el Coordinador y el Planificador: hasta ahora el Planificador se conecta solo con los ESIs para avisarles que pueden ejecutar una sentencia, y cuando un recurso se bloquea, el único que lleva registro de esto es el Planificador. Ahora notamos que en cuanto al uso de las claves, hay una conexión entre del Coordinador con el Planificador, pero no estaríamos entendiendo para qué se necesita especificamente.

**Comment by iago64** [comment]
Buenas buenas!!

Esa conexión tiene como objetivo que puedan consultarle desde el coordinador los bloqueos al planificador (recordá que tenes que verificar que el ESI que te pide un SET o un STORE tenga tomada la clave).
Ademas cuando tiras la consulta de status en la consola del planificador, como podes saber en que instancia esta la clave si no le preguntas al coordinador?

Saludos.-

**Comment by GabrielRuderman** [comment]
No se supone que si el ESI envio la instruccion al coordinador fue porque el planificador lo autorizo? Por ejemplo, si quiero hacer un SET el planificador chequea que tenga el GET previo, y ahi si le mando el SET al coordinador

**Comment by iago64** [comment]
Buenas!

El planificador no debería saber que instrucción va a ejecutar el ESI, simplemente lo manda a ejecutar y espera que este le responda y por otra parte espera que el coordinador eventualmente le consulte por una clave (SET o STORE) o le diga que un ESI quiere obtener una clave (GET)

Saludos.-

**Comment by GabrielRuderman** [comment]
Clarisimo, muchas gracias!
