### ISSUE TITLE
Interacciones de la Consola del Planificador

### ISSUE THREAD

**Issue by alabarque** [sisoputnfrba/foro#1164]
Hola, buen dia. 
Tengo un par de consultas sobre algunas interacciones de la consola, las tratare de dividir en distintos items para separar los temas. Antes de las consultas me gustaria aclarar que tenemos, para cada esi, un campo que indica quien es el esi que reservo esa key:

1. Supongamos que tenemos un ESIA que hizo _GET claveA_ y luego de esto, se escribe en consola _bloquear claveA ESIA_ La pregunta es, ¿como deberiamos seguir en este caso? Dado que tenemos el campo que indica quien es el dueño de la key, no sabemos que deberiamos hacer con ese campo: si dejarlo tal cual esta, o quitarle dicho atributo de que es el dueño y enviarlo a la cola de bloqueados de la key.

2. Esta consulta ahora va del lado del enunciado, respecto al comando desbloquear. _en caso de que no queden mas procesos bloqueados se debera liberar la clave._  Bajandolo a codigo se me ocurren dos formas de implementarlo (por el tema del campo del dueño de la key) y por eso queria su aclaracion. La primera es limpiar dicho dueño (obviamente, la cola de bloqueados vacia), por lo que la key sigue existiendo en el planificador, pero esta "limpia". La segunda es eliminarlo completamente del planificador, osea haciendo free y quitarlo de cualquier estructura adicional, lo cual en este caso mi pregunta es si habria que avisarle al coordinador que la key ya no existe.

3. Pasamos al algoritmo de deadlock. La pregunta en este caso viene del lado de la interaccion con las claves iniciales bloqueadas. Debido a que estas claves tienen la particularidad de que solo pueden ser liberadas usando el comando _desbloquear_, queriamos saber si los esis bloqueados por estas keys deberian figurar como en deadlock, ya que sin usar ese comando, nunca van a poder desbloquearse.

Muchas gracias, se que son varias cosas pero no queria hacer 3 issues distintos.

**Comment by iago64** [comment]
Buenas buenas!
Perdon la demora, mil gracias por separar las cosas en puntos 😄 

1.- Si ya tenes el ESI como dueño de la clave simplemente logueen y muestren un mensaje que sea algo asi como "El ESIA ya es el dueño de la _claveA_, segui participando" y no se la compliquen mas de ahi.

2.- Haganlo como a uds les resulte mas facil siempre y cuando cualquier otro ESI que haga GET de la clave la pueda tomar sin problema :)

3.- Buena pregunta, pero te puedo contestar con una pregunta? Cuales son las condiciones del deadlock? Hay alguna que no se te cumpla para el caso de las claves bloqueadas por _sistema_? 😉 

Abrazo!

**Comment by alabarque** [comment]
Hola, colgue 😅. Dale perfecto, cierro el issue.
