### ISSUE TITLE
Error en el Build - Nothing to be done for 'all'

### ISSUE THREAD

**Issue by suumoo5** [sisoputnfrba/foro#1165]
Buenas, cuando intento buildear el proyecto me sale el error de "Nothing to be done for 'all'. "

![image](https://user-images.githubusercontent.com/26445648/41813018-bcdfdce0-7703-11e8-8761-8cb4de1e5cba.png)

Busque la solucion y dicen de modificar alguna configuracion en las propiedades del proyecto, pero antes de meter mano y romper todo, pregunto por aca.

![image](https://user-images.githubusercontent.com/26445648/41813029-fbbc3a08-7703-11e8-948d-3c71572f99b7.png)
Esta es la ventana que decían, cuando busque, que habia que modificar, asique pense que podria servirles.

**Comment by iago64** [comment]
Buenas buenas!

Por favor te joderia subir un print del makefile que te está generando eclipse y del project explorer? Porque con lo que me pasaste no tengo mucha info para ayudarte

Abrazo!

**Comment by suumoo5** [comment]
Perdona pero soy un queso, me podes decir donde chequeo el lugar de creacion del makefile y el project explorer?

**Comment by iago64** [comment]
Tranqui, no tengo nada que disculparte porque estamos todos para aprender :)
Vamos en orden:
1.- Project Explorer, es de eclipse y lo deberías tener a la derecha como en la siguiente foto:
![image](https://user-images.githubusercontent.com/1622109/41815292-b0b03ef4-773c-11e8-88fc-2a1cf87ab633.png)
Eventualmente si alguna vez lo cerraste y no sabes como abrirlo esta en Window --> Show View --> Project Explorer
![image](https://user-images.githubusercontent.com/1622109/41815301-d919c446-773c-11e8-9661-e20c6264f7ab.png)

2.- Segunda parte, el makefile, la forma facil de verlo es en el explorador de archivos (o navigator como lo llama eclipse)
![image](https://user-images.githubusercontent.com/1622109/41815311-25390094-773d-11e8-9071-6830a6930e15.png)
Si no te aparece el navigator simplemente tenes que hacer lo mismo que para buscar el Project Explorer, pero haces click en el navigator.
Si no tenes makefile lo que tenes que hacer es hacer click en el martillo para que intente hacer el build :)

Abrazo.-

**Comment by iago64** [comment]
buenas buenas!
Ahora si tenemos la info :smile:
Fijate que tendrias que tener un makefile por cada proceso (un makefile para el Planificador, uno para el Coordinador, uno para la instancia y otro para el proceso ESI)
Ahi eclipse no te esta compilando porque en un mismo proyecto de eclipse tenes a todos los procesos.
fijate de importar un proyecto por cada proceso y ahi deberias podes compilar.
Abrazo!

**Comment by suumoo5** [comment]
Buenas,
Ahí parece que me lo genero al makefile (Planificador), pero me decia lo mismo, asique entre en el makefile que me creo: 

![image](https://user-images.githubusercontent.com/26445648/41823779-26b4562c-77dc-11e8-8230-cfe67306ff09.png)


Parece que no le gusta que el `all:` este vacio.

Espero comentarios o alguna salvacion. Gracias!!

**Comment by LeaTex** [comment]
@suumoo5 es un bug de Eclipse cuando se queda sin memoria. A mí me pasa a cada rato. Tengo la VM con 2 GB de RAM pero igual cada 2 por 3 se queda pavote en ese error.

¿Solución? Cerrá el Eclipse, y abrilo de nuevo. Si sigue haciendo escenitas de histérico, reiniciá la VM y listo.

**Comment by suumoo5** [comment]
Ya hice todo lo que decis y no hay caso. Cerre Eclipse, reinicie VM... todo. 

Espero un milagro.

**Comment by iago64** [comment]
Buenas? 
Te tiro un par de preguntas @suumoo5 capaz que con una damos en el clavo :)
1.- El proyecto es un proyecto de Linux GCC?
2.- Los archivos .c y .h los importaste al proyecto desde eclipse o simplemente fue un copy-paste en el file system?
3.- En las propiedades del proyecto tenes que te genere el makefile de manera automática?
![image](https://user-images.githubusercontent.com/1622109/41886014-ddc3279a-78d0-11e8-935a-d47331f95e83.png)

Si con alguna de estas preguntas damos en el clavo es un éxito, si no vemos como seguimos.
Abrazo.-

**Comment by suumoo5** [comment]
1.- Sisi, literal vi el video de UTN-SO para crear un proyecto cuando lo cree
2.- Idem aca, vi el video de youtube para importar un proyecto desde eclipse porque estaba teniendo problemas que me agarre el proyecto en si, y con el video me soluciono.
3.-Tambien tilde esa opcion en busqueda de la solucion del problema

![image](https://user-images.githubusercontent.com/26445648/41941350-15f1b4e6-7972-11e8-8ccb-b732c4611044.png)

Estoy pensando si desinstalar la VR e instalarla de nuevo, teniendo así un Eclipse no modificado (porque quiza habre modificado algo sin querer) funcionará.

**Comment by iago64** [comment]
Es raro, podrias probar en levantar otra VM sin tocar nada.
La otra opcion es que entres a la carpeta Debug desde una consola y trates de compilarlo como si fuese la vmserver (make all) y veas si te tira algo mas de info.

Saludos.-

**Comment by tferraro** [comment]
Holis :wave: , pasó mucho tiempo desde el último mensaje ahora que lo veo. Como fue eso @suumoo5 ? Pudiste solucionar el problema (y como)?

**Comment by afilgueira** [comment]
@suumoo5 :point_up:

**Comment by tferraro** [comment]
Buenas! Cierro el issue por inactividad, cualquier cosa volvamoslo a abrir 😉
