### ISSUE TITLE
Finalización de ESIs

### ISSUE THREAD

**Issue by agnmeinardo** [sisoputnfrba/foro#1166]
@iago64 , cómo andás? Ayer por la mañana, con mi grupo, te estuvimos haciendo unas preguntas. Una de ellas era sobre la finalización de los ESIs, pero no recordamos bien. Decime si estoy en lo correcto:
         . Si mato a un ESI por consola del planificador, éste termina como lo haría si ejecuta todo su código: pasa a la cola de Finalizados y libero los recursos que tenía tomados.
         . Si se produce algún error, el ESI se "aborta": pasa a la cola de Finalizados, peero no libera sus recursos.
Estoy en lo cierto??

**Comment by ricardoAguirreSanchez** [comment]
Buenas,

Una duda rápida y corta, si el esi aborta se hace el caso 1 o caso 2? 

Caso 1:
1.- lo mando a finalizado
2.- libero la clave (osea la dejo disponible para k otro esi la tome)
3.- NO saco al primer esi bloqueado por dicha clave si hubiese.

Caso 2:
1.- lo mando a finalizado
2.- NO saco al primer esi bloqueado por dicha clave si hubiese.

Saludos.

**Comment by iago64** [comment]
Buenas @ricardoAguirreSanchez si lo abortas por un error (sea el error que sea) es el caso 2

**Comment by ricardoAguirreSanchez** [comment]
Gracias.

**Comment by alabarque** [comment]
Buenas @iago64 , aprovecho que el issue sigue abierto para mencionar que estaria bueno aclarar eso en el enunciado del tp ya que en el anexo 2 (ejemplo 1 y 2, que es contradictorio con lo que mencionaste) se menciona que las claves que tenia tomadas se liberan al abortar y en el anexo 1 se menciona en los distintos errores que el esi aborta, pero nunca se aclara que deberia suceder al abortar. 

Lo menciono especificamente por la gente que tal vez no tenga tiempo para leer todos los issues.

**Comment by iago64** [comment]
@alabarque el ejemplo 1 esta bien, porque los ESIs que terminan bien no hacen nada, en el ejemplo 2 tenes razón, ahí lo arreglamos :)

**Comment by alabarque** [comment]
Mala mia, pase rapido pensando que abortaba como el segundo jeje.

Aprovecho para no crear otro issue, en el enunciado dice que se debe contemplar la desconexion de ESIs. Esto incluye al ESI que se envia a ejecutar? (por ejemplo, que se desconecte a mitad de la ejecucion de una sentencia).

**Comment by iago64** [comment]
No pasa nada, en el apure es normal que se nos pasen cosas :)
Respecto a la desconexión de los ESIs, si juuusto es el que mandaste a ejecutar, no pasa nada, en cuanto te llegue el mensaje de desconexion en el planificador (ya que te va a saltar la desconexion del socket) y ahi mandas a ejecutar otro ESI y del lado del coordinador, como los deberias manejar por hilos en cuanto te falle el send() liberas los recursos de ese hilo y listo :)

Abrazo.-

**Comment by iago64** [comment]
@agnmeinardo Todavía te quedan dudas o cerramos el tema?

**Comment by agnmeinardo** [comment]
Buenas! Cierro el issue entonces
