### ISSUE TITLE
Errores de Valgrind

### ISSUE THREAD

**Issue by ivimazzini** [sisoputnfrba/foro#1167]
Hola! Corriendo Valgrind me estuvieron saltando estos errores, pero la verdad es que son bastante raros y no pude encontrar nada parecido ni en las issues ni en google de como solucionarlos, lo que me resulta raro es que a diferencia de la mayoria de errores de Valgrind que te indican donde es el error o incluso nombrar el proyecto este no lo hace, por lo que podría ser algo relacionado con la configuración o también con el momento de ejecución por la carpeta build a la que hace referencia. Saben de que puede llegar a ser o por donde podría estar orientado?
Gracias!
![image](https://user-images.githubusercontent.com/37641820/41831288-76281a82-781c-11e8-834f-1b9d603f1390.png)

**Comment by iago64** [comment]
Buenas!

No tenes ningun mmap en tu código? 
El archivo de config existe o esta en la ruta que estas pasando?

Perdon por las preguntas pero me falta contexto para entender el problema.

Abrazo.-

**Comment by ivimazzini** [comment]
Sisi preguntame tranqui, porque yo no supe que mas info poner, no tengo ningun mmap y el archivo de configuracion existe es un txt que esta dentro de la instancia pero se lo paso igualmente por una ruta (no directamente por el nombre porque sino cuando se ejecuta lo busca el la carpeta de Instancia/debug)

**Comment by mgarciaisaia** [comment]
@ivimazzini ¿sabés cómo correr `valgrind` por la consola? Estimo que puede haber ahí algo más de info que Eclipse no está sabiendo mostrar.

La otra opción (que no creo que aporte mucho, pero bue) es que pruebes el botoncito de Export logs (el que está arriba a la derecha en tu screenshot, a la izquierda de la `X` de cerrar el panelcito). Con eso podés exportar los logs y _capaz_ te de algo más de info, pero realmente no creo.

La otra es que te arremangues un poquito más y pruebes, o bien de debuggear el proceso (por defecto, el debugger se frena cuando llega la señal del `SIGSEGV`, y podés mirar en el stack a ver qué instrucción se estaba ejecutando y qué valores tenían las variables), o bien [hacer un análisis postmortem](https://faq.utnso.com/eclipse-postmortem) si debuggear se vuelve complejo o no reproduce el error.

**Comment by ivimazzini** [comment]
La realidad es que por el momento el programa ejecuta bien, osea no tira ningún error cuando ni cuando se ejecuta ni cuando se debuguea con eclipse, pero como Valgrind podía tirar errores que no se vieran a simple vista, no quería seguir sin resolverlo porque capas después se hacía algo peor.

**Comment by iago64** [comment]
@ivimazzini pudiste resolver el tema en el soporte presencial?
