### ISSUE TITLE
Duda Compactar

### ISSUE THREAD

**Issue by pablomonti** [sisoputnfrba/foro#1168]
Buenas a todos,

Tengo una duda con respecto a la compactacion, 
supogamos que tenemos 2 entradas y cada entrada esta ocupada por un valor (de distintas claves obviamente) y cada uno ocupa la mitada de cada entrada. Osea por ejemplo valor1 y valor2 tiene un tamaño 1 y las entradas tamaño 2.
Aca se puede compactar? Porque podria poner los dos valores en una entrada y me queda la otra libre. Pero segun entiendo solo puede ocuparse una entrada con un valor

**Comment by LeaTex** [comment]
No @pablomonti . Si hacés eso estarías compactando el espacio "físico" de almacenamiento, pero no las entradas.
Para que sea consistente lo que decís tendrías que hacer que clave1 y clave2 estén en la misma entrada.

La fragmentación interna (el espacio desperdiciado dentro de cada bloque asociado a la entrada) no se puede compactar.

Si ya vieron filesystema en clase, hagan la siguiente analogía:
- tabla de entradas --> FAT
- tamaño de la entrada --> bloque

O sea, te pasa lo mismo en un disco rígido. Si los bloques que maneja el filesystem son de 4 K, pero vos guardás un archivo de 500 bytes, el resto es desperdiciado y no podés guardar nada ahí.

**Comment by iago64** [comment]
Buenas buenas!
Excelente ejemplo @LeaTex 
@pablomonti la instancia trabaja a nivel entradas, si tenes una entrada ocupada pero tiene espacio libre ese espacio libre queda ahi, se llama fragmentación interna y esta perfecto que este ahi, de hecho uno de los algoritmos de reemplazo se basa en eso :)

Abrazo.-

**Comment by pablomonti** [comment]
Gracias muchachos, 
Me ganó la duda por sobre la teoría.

Quedo mas que claro. Gracias!
