### ISSUE TITLE
Comando bloquear para estados de ESI 

### ISSUE THREAD

**Issue by Mszlajen** [sisoputnfrba/foro#1169]
Buenas, arreglando unas cosas del comando bloquear me acorde del issue #1114 donde dice que bloquear es simular que el ESI hizo GET de la CLAVE, lo que me lleva a pensar en los siguientes casos:

1. El ESI está en la cola de Ready o ejecutando, simulo el GET normalmente sincronizandolo con la ejecución.
2. El ESI está finalizado o no existe, le devuelvo un error al usuario.
3. El ESI está bloqueado por alguna clave, una de dos:
3.a. Si la clave está libre, se la asigno al ESI.
3.b. Si la clave ya está tomada, le devuelvo un error al usuario.

¿Ese razonamiento está bien?

**Comment by iago64** [comment]
Buenas buenas!

1.- Si está en cola de ready lo moves a bloqueados o le asignas la clave según corresponda. Si está ejecutando una rafaga esperas a que esta termine y ahi recien lo moves ya que la ejecución de las operaciones es atómica.
2.- Efectivamente, un error bien claro.
3.- Si está bloqueado, con que devuelvas un error diciendo que el recurso ya se encuentra bloqueado alcanza :)

Abrazo!

**Comment by Mszlajen** [comment]
> 3.- Si está bloqueado, con que devuelvas un error diciendo que el recurso ya se encuentra bloqueado alcanza.

Acá no te estaria entendiendo bien (me parece que se me están confundiendo los terminos), si el ESI ya está bloqueado esperando alguna clave, devuelvo el error independientemente de si la clave está libre para ser tomada?

Por ejemplo, yo tengo el ESI 1 bloqueado esperando la CLAVE 1, la CLAVE 2 no está tomada por nadie y hago por consola Bloquear CLAVE 2 ESI 1, ahí que hago?

**Comment by Mszlajen** [comment]
Ese caso que decis se me paso por alto escribirlo (seria un 3.c), pero con estoy ya está todo claro.
Gracias.
