### ISSUE TITLE
[Instancia] - Sincronización del Dump

### ISSUE THREAD

**Issue by santiluccadeguevara** [sisoputnfrba/foro#1170]
Hola. Me parece que estoy implementando mal el intervalo de Dump de la Instancia y recurro a ustedes para que me aclaren una duda rápida:

Si mal no entendí, cada cierto intervalo de tiempo, se ejecuta un Dump sobre la Instancia, que necesita a la Tabla de Entradas y al Storage para persistir los valores de las claves (y nada más, como se estuvo comentando en otros issues).

Ahora bien, mi duda es la siguiente: la Instancia tiene que recibir pedidos del Coordinador (Ya sea un SET, STORE, etc.) en concurrencia con el Dump? O tranquilamente se puede procesar un pedido del Coordinador y, pasado el intervalo de Dump, ejecutar el mismo? (Super ineficiente, lo cual me llevó a abrir el issue)

Suena medio obvio y no sé si me estoy avivando bastante tarde, pero me quiero asegurar antes de empezar a poner los mutex por todos lados.

Espero su respuesta. Gracias!

**Comment by LeaTex** [comment]
Nosotros implementamos el DUMP como una acción bloqueante en la instancia, es decir, mientras se guardan los archivos no puede hacer otra cosa.

Igual la acción debería tardar milésimas de segundos (salvo que nos hagan tener entradas de varias GB, lo cual dudo).

Así que no se vería afectada la performance general del sistema.

**Comment by santiluccadeguevara** [comment]
Ok. Entiendo. Con lo que me decís, creo que me expresé mal con la palabra "ineficiente": seguro el Dump se va a hacer rápido, pero el issue surge porque en mi equipo estábamos integrando el Dump de una forma secuencial:

1. Esperamos un pedido del Coordinador
2. Procesamos el pedido
3. Si se disparó una señal de Dump, ejecutar el Dump. (Tal como explicaste en el #1106)
4. Volver a 1

Entonces ahí ocurría el Dump como decís: exclusivamente eso y nada más, pero nos dimos cuenta que si a la Instancia no le caen pedidos durante mucho tiempo, no va a hacer el Dump hasta que le caiga otro pedido del Coordinador y hay un par de efectos no deseados que genera:

1. No vamos a poder tirar un printf("Ejecutando Dump\n") para quedar bien en la entrega.
2. Es inseguro, puesto que si tiran la Instancia mientras no recibe pedidos para disparar el Dump, perdés todos los datos que estuviste almacenando.
3. Más allá de que sea inseguro, estético, o cualquier atributo de calidad, el Dump no estaría cumpliendo con su responsabilidad, que es la de ejecutarse y persistir las claves cada cierto intervalo de tiempo. Estaría funcionando cómo una alarma-despertador: la configurás para que suene a las 7:00 y te levantás a las 8:00 XD

Para evitar esos problemas (si lo son) que mencioné, debería tirar dos hilos: uno para el Dump y otro para procesar pedidos, y sincronizarlos para que no haya condición de carrera con la Tabla de Entradas y el Storage.

Así que nada, con eso me refería con "ineficiente" (debí haber usado otra palabra XD).

**Comment by LeaTex** [comment]
ah bueno, entiendo lo que decís, pero ahí está la astucia de cada grupo de cómo solucionarlo ;-)

creo que damián en otro issue había tirado el tip de usar un select() con timeout, para así asegurarnos que cada cierto tiempo salimos de la función bloqueante y chequeamos que estemos en condiciones de hacer un dump.

esa es una de las alternativas.

**Comment by iago64** [comment]
Buenas buenas!!
Ciertamente la palabra que estabas buscando @santiluccadeguevara no era "ineficiente", pero bueno, tranqui, la performance no es algo que nos preocupe (a menos que graben byte a byte cada clave en el archivo y ahi si podemos estar horas con una sola prueba jaja).

Eventualmente, pueden hacer algo estupidamente simple que seria hacer un hilo que este en un while(1) y sea algo asi como

```
while(1){
    usleep(TIEMPO_DUMP_EN_MS);    
    printf("\nSoy un hilo amigable que empieza a hacer el dump");    
    hacerDump();    
    printf("\nListo vieja ya tenes el dump, ahora trata de no romper nada");    
}
```

Y ahí les puede importar entre nada y el cariño que le podemos tener a Sampalobby  cuando como y por que se ejecuta el dump.
Eventualmente si quieren asegurarse de no reemplazar justo una clave en el preciso instante que estan haciendo el DUMP, pueden tener un mutex para cuando accedan a cada clave o al storage, pero esa parte se las dejo para que la piensen un poquito y recuerden lo que les explicaron en la teoría 😸 

Abrazo!

**Comment by santiluccadeguevara** [comment]
Perfecto. Gracias por las respuestas!

Saludos!
