### ISSUE TITLE
Comando "status": consulta sobre la información a mostrar

### ISSUE THREAD

**Issue by JuanQP** [sisoputnfrba/foro#1172]
Hola!

Sobre el comando status tenemos estas dudas respecto a [lo mencionado en el TP](https://sisoputnfrba.gitbook.io/re-distinto/planificador#consola-del-planificador):

1. ¿"_Instancia actual en la cual se encuentra la clave_" es lo mismo que decir "_Instancia que persistió en disco el valor de la clave_"?
2. El caso "_En caso de no tener un valor..._", ¿Sería el caso de una clave a la cual se le hizo `GET` pero todavía no se le hizo un `SET`? (Es decir una clave creada pero sin un `SET`)
3. "_Instancia en la cual se guardaría actualmente la clave_" (de ahora en adelante _potencial instancia_): Me gustaría validar con un pequeño caso de uso lo siguiente para ver si estamos yendo por buen camino (la lista de bloqueados la vamos a obviar momentáneamente por simplicidad)

```sh
# Se ejecuta la siguiente instrucción...
GET personas:nombres # Se creó la clave personas:nombres

# Inmediatamente se ejecuta en la consola status...
> status personas:nombres # "Sin valor, no está storeada, la potencial instancia es A"

# Se ejecuta la siguiente instrucción...
SET personas:nombres gauss
> status personas:nombres # "Su valor es gauss, no está storeada, la potencial instancia es B"

# Se ejecuta la siguiente instrucción...
STORE personas:nombres
> status personas:nombres #"Su valor es gauss, está en A, la potencial instancia es B"
```

Aclaración: Luego del `SET` la potencial instancia pasó a ser B ya que la solicitud de operación fue distribuída por eso el algoritmo está apuntando a otra instancia, pero como no está storeada todavía, figura "no está storeada".

¿Es este el comportamiento esperado?

Muchas gracias, saludos!

**Comment by natoszme** [comment]
Buenas! En caso de ya saber en qué instancia está, tengo entendido que no tenés que simular. La simulación aplica cuando no tenés la clave en ninguna

**Comment by JuanQP** [comment]
Y "estar en una instancia" significa que está persistida?

**Comment by iago64** [comment]
Buenas buenas!

1.- Que esté en una instancia no necesariamente tiene que haber bajado a disco, si no que al menos tenes el valor en una o varias entradas (Lease hiciste un SET entonces ya calculaste la instancia que le corresponde y está ahí el valor o eventualmente si fue reemplazado cuando lo busques no lo vas a tener y devolverás valor reemplazado o un texto similar)
2.- Efectivamente, es solo los casos de GET pero sin ningún SET.
3.- Es solamente para los casos donde no hiciste SET y no sabes en que instancia esta efectivamente la clave, entonces le simulas el algoritmo de distribución para saber a donde caería.

Abrazo.-

**Comment by natoszme** [comment]
@iago64 [acá](https://github.com/sisoputnfrba/foro/issues/1148#issuecomment-397851175) no dice que ante este caso

> o eventualmente si fue reemplazado cuando lo busques no lo vas a tener y devolverás valor reemplazado o un texto similar

deberíamos simular?

**Comment by iago64** [comment]
@natoszme Si tenes el dato de la instancia en la que estaba antes del reemplazo no hace falta simular, si al reemplazar no tenes mas en que instancia porque le dijiste al coordinador que reemplazaste y eliminaste el dato ahí si tenes que simular
Tené en cuenta que hay tantas posibles implementaciones del reemplazo como grupos hay este cuatrimestre. En algunos casos al reemplazar matan el registro en el coordinador y en otros no, el camino ideal seria matarlo porque la instancia no tiene mas el valor, pero hay grupos donde no lo sacaron y eso no es core para decir si el tp aprueba o no, con lo cual ambas implementaciones son válidas :)
**Lo importante** del status es que digan _en que instancia esta_ (si tienen el registro) _o en que instancia debería estar_ (si no lo tienen) la clave, y que de hecho es lo que se va a probar con los algoritmos.

Abrazo.-

**Comment by natoszme** [comment]
@iago64 ah oka, ya lo habíamos hecho considerando que si había eliminado la clave, se simulaba. No hay drama no? Gracias!

**Comment by iago64** [comment]
@natoszme ninguno, sigan adelante con lo demás 😃

**Comment by JuanQP** [comment]
Clarísimas las dos respuestas @iago64 , nada más para preguntar por mi parte

Gracias!
