### ISSUE TITLE
Algoritmo de reemplazo LRU - ¿qué consideramos?

### ISSUE THREAD

**Issue by LeaTex** [sisoputnfrba/foro#1174]
Hola gente.
Nos surgió una duda, que no afecta mucho a lo que estamos haciendo, pero... si lo podemos hacer bien, mejor.

Respecto al algoritmo de reemplazo LRU, el enunciado dice:

_El algoritmo LRU se basa en llevar registro de hace cuánto fue **referenciada** cada entrada. Llegado el momento de reemplazar una entrada, se selecciona aquella entrada que ha sido **referenciada** hace mayor tiempo._

¿Qué deberíamos considerar como "referenciada"?
Estoy 100% seguro que el SET cuenta.
Estoy 95% seguro que el STORE también.
Y estoy 40% seguro de que el "STATUS CLAVE" que pedimos desde la consola del planificador también debería contar, dado que la consulta llega a la Instancia para poder devolver el valor, o sea, la estamos "referenciando".

¿Me podrían confirmar por favor? Gracias

**Comment by ricardoAguirreSanchez** [comment]
Buenas, 
Con mi grupo un sábado nos acercamos y nos dijeron que era solo con operaciones SET y STORE (tampoco tomar en cuenta el dump o la compactación, esas dos locuras también fueron parte de nuestra duda en ese momento).
Igual si lo pueden reconfirmar mejor.

Saludos.

**Comment by iago64** [comment]
Buenas buenas!

@LeaTex es tal cual dice @ricardoAguirreSanchez solo el SET y el STORE cuentan para la referencia de la clave, el status clave no debería cambiar la última referencia :)
De todas formas, si quieren ir probando el reemplazo en la carpeta de PruebasFinales hay un ESI_MultiReemplazo que pueden usar para jugar un ratito 😉

Abrazo!

**Comment by LeaTex** [comment]
Perfecto, gracias por reconfirmar.
