### ISSUE TITLE
Publicación de Pruebas finales

### ISSUE THREAD

**Issue by sebastianciancio** [sisoputnfrba/foro#1175]
Quisiera consultarles cuando está previsto publicar las pruebas finales que se realizarán el 14/07 en la entrega del TP.

Gracias

**Comment by iago64** [comment]
Sebas, que tal?

Estamos terminando de ajustar detalles para que las pruebas se puedan realizar en un tiempo de entre 15 a 30 minutos (eventualmente cuando salgan igual vamos a pedirles feedback), con lo cual en estos días las vamos a subir.

Abrazo!

**Comment by sebastianciancio** [comment]
Muchas gracias
