### ISSUE TITLE
Duda con la compactacion

### ISSUE THREAD

**Issue by agusmoles** [sisoputnfrba/foro#1176]
Buenas, tengo una duda con la compactacion...

_1._ Cuando es que hay que dispararse la compactacion? Despues de haber "liberado" todos los valores atomicos o apenas haya la suficiente fragmentación externa para que, luego de compactar, entre el valor de la clave?

_2._ En el enunciado dice que todas las instancias deben compactar a la vez... como es esto posible?

Saludos!

**Comment by iago64** [comment]
Buenas, buenas!

1.- La compactación la tenes que disparar ni bien tengas el espacio suficiente pero no tengas ese espacio continuo para 

2.- Es fácil, en cuanto una instancia detecta que tiene que compactar tienen que avisarle a las demas para que compacten (pasando por el coordinador)

Saludos.-

**Comment by agusmoles** [comment]
Listo. Gracias Dami. 

Saludos!

**Comment by agusmoles** [comment]
Buenas de nuevo, no sabemos como implementar lo de que todas las instancias compacten cuando lo hace una. Porque hasta ahora el **Coordinador** recibia de la **Instancia** asincronicamente el mensaje para lo del manejo del comando **status**. Entonces teniamos el hilo de la instancia colgado en un select (o en unico recv en realidad) esperando el tamanio del valor del status (manejado por semaforo) para justamente hacer lo del comando...

Lo mismo para lo del error del store cuando no existe la clave en la instancia (ya que tambien necesita recibir datos).

Saludos
p.d: No se si me explique bien, la cosa es que si hacemos un recv despues del STORE para ver lo del error o despues del SET tambien para ver si se necesita que compacten todas las instancias; el hilo de la instancia que esta en el recv() tambien se va a desbloquear por lo del status

**Comment by iago64** [comment]
Buenas buenas!

Tendria que revisar bien como lo tenes implementado para darte la solución más corta, a priori estas manejando una respuesta de parte de la instancia? (es decir, esperas a que te diga ok o error?)
Si esperas una respuesta por parte de la instancia, una respuesta podria ser, "tengo que compactar", que el coordinador te conteste: "Ok compacta" y cuando vos le devuelvas el "ok" (y del lado del coordinador tenga el "ok" de todas las instancias), te vuelva a pedir el SET.

Abrazo!

**Comment by agusmoles** [comment]
No, por eso se nos complica. Porque creiamos que ningun error surgia de la instancia, incluso dudamos si en el enunciado explica lo del error del store y bueno ahora nos surgio este problema jajaja

Saludos

**Comment by LeaTex** [comment]
@agusmoles es de mala educación que uno hable y el otro no le responda ;-)

cuando dos puntos (nodos/procesos/etc.) se comunican, lo normal sería que cualquier paquete enviado desde un lado, tenga una respuesta. aunque sea un simple "ok, me llegó", para que no pase como cuando mandás un mail y no sabés si al otro le llegó o qué pasó.

por ahí podrían ver de cambiar lo que hicieron para el caso concreto del SET (que es el que puede generar una compactación). cuando le mandan SET a la instancia se quedan esperando una respuesta, que podría ser, por ejemplo, Ok, Error, Compactar.

**Comment by agusmoles** [comment]
Si, me parece que lo mejor seria cambiar el hilo de la instancia, que en vez de esperar un int (que era para lo del status) espere un header para las distintas cosas que tenga que hacer la instancia, tanto para el error, compactacion y el status.

Despues respondo que onda la implementacion y les aviso. Lo dejo abierto mientras.

Muchas gracias!

**Comment by iago64** [comment]
@agusmoles cualquier cosa que se les complique demasiado hablame por mail (creo que alguien de tu grupo tenia mi mail después del checkpoint).

>Offtopic
@LeaTex en la edad media no hubiera sido de mala educación si las instancias eran los lacayos y el coordinador el noble :stuck_out_tongue_winking_eye:, pero bueno, estamos en el siglo XXI y ya lo van a ver en redes que la mayoría de los protocolos de comunicación funcionan con algo llamado ACK (a.k.a: me llego bien el mensaje)

Abrazo!

**Comment by agusmoles** [comment]
Al parecer anduvo la idea, tuvimos un problema con la compactacion y te mande mail Dami. 

Gracias a ambos!
Saludos
