### ISSUE TITLE
Eclipse finaliza solo

### ISSUE THREAD

**Issue by Jaugustopose** [sisoputnfrba/foro#1177]
Buen día

Estoy teniendo problemas para usar Eclipse. El mismo se cierra solo y sin previo aviso, lo que me lleva a tener que estar guardando cada 1 segundo cualquier parte que codee y a lo que ya se imaginan, cuando estoy debuggeando.

Una vez que se cierra solo, me deja este archivo:
[hs_err_pid30322.log](https://github.com/sisoputnfrba/foro/files/2167753/hs_err_pid30322.log)

El cual al leerlo y usando la recomendación **_try "ulimit -c unlimited" before starting Java again_**

Continua cerrándose por si solo, y ahora creando también este archivo, que creo que no aporta nada, pero lo dejo por las dudas:
[replay_pid29314.log](https://github.com/sisoputnfrba/foro/files/2167763/replay_pid29314.log)

Tal vez sirva de información, pero en la VM vieja esto no me sucedía.

Saludos y espero cualquier tipo de posible solución.

**Comment by iago64** [comment]
Buenas buenas!

Una pregunta, cuando hace referencia a la VM vieja te referís a las de cuatrimestres anteriores? Eventualmente si tenes una VM vieja no habria problema que la usen (simplemente las actualizamos porque las VMs viejas estaban algo obsoletas después de un par de años, pero para este TP no habría problema ya que no usan ninguna de las bibliotecas que actualizamos)

Saludos.-

**Comment by Jaugustopose** [comment]
Si, me referia a la vm de cuatris anteriores. Pero bueno, queria saber si hay alguna solucion para esto sin tener que bajarme la vm vieja otra vez y configurar todo ahi.

**Comment by tferraro** [comment]
Buenas!

Primero que nada, lo que estás haciendo con el `ulimit` es permitiendole escribir un dump del core del proceso, porque al ser grande supera el límite que tiene puesto el SO, pero es algo para poder debuggear sobre el core para ver que paso.

Por lo general, si el Eclipse se cae al iniciar, suele ser que algo cargó mal del Workspace, no tiene mucho que ver con las versiones (al menos pasaría siempre, todo el tiempo sino).

Fijate que dice el `workspace/.metadata/.log` para tener más info y no tener que matar todo el workspace (que seguramente solucione el problema, pero es como querer hacer un agujero con una colt).

Saludos!
Tom

**Comment by afilgueira** [comment]
@Jaugustopose pudiste solucionarlo? nos contás cómo? Saaudos!

**Comment by Jaugustopose** [comment]
Perdón por el cuelgue.

Revise el log que dijo Tomas en workspace/metadata/.log y era una cadena sin fin de errores a solucionar. Pude arreglar algunos y seguía sin funcionar. Dada la urgencia para finalizar el tp, clone el workspace de otro integrante del grupo y ahora funciona perfecto.

Cierro y gracias!
