### ISSUE TITLE
Consulta list_add_all

### ISSUE THREAD

**Issue by agnmeinardo** [sisoputnfrba/foro#1178]
Buen día! Pregunta que puede sonar muy simple y básica (por no decir tonta). Lo que estoy intentando hacer es clonar una lista. Primero, creo la lista nueva. Segundo, quería ver la forma de pasar (copiar) cada elemento de la lista x a esa nueva lista. Con la función list_add_all (que agrega a la primer lista, los elementos de la segunda): cuando los agrega, los borra de la segunda lista?
Saludo.-

**Comment by iago64** [comment]
Buenas buenas!
Antes que nada, una pequeña reflexion: _Preguntas tontas son aquellas que no se hacen_
Ahora si vamos al tema en cuestión, si vemos la definicion en el lits.h dice lo siguiente:
![image](https://user-images.githubusercontent.com/1622109/42421650-64f7ec7c-82af-11e8-8f00-7bb5a34667f9.png)
Con lo cual yo dudaría de que los borre, pero para confirmar podes checkear archivo [list.c de las commons.](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/collections/list.c)
Y confirmar si realmente borra o no las cosas de la segunda lista :)

Abrazo!

**Comment by afilgueira** [comment]
@agnmeinardo funcionó? Saludos!

**Comment by agnmeinardo** [comment]
Sisi. Saludos!
