### ISSUE TITLE
STORE para clave no registrada

### ISSUE THREAD

**Issue by GabrielRuderman** [sisoputnfrba/foro#1179]
Buenas, una consulta:
Nosotros lo que hacemos es que la Instancia para cada SET que recibe se fija si la clave del mismo esta registrada en alguna de sus entradas. Si no lo está, la crea y guarda el valor. Si lo está, sobrescribe el valor.
Y para cada STORE el mismo chequeo: si la clave está creada, entonces eso quiere decir que hubo un SET previo, y por lo tanto lleva adelante el dump. Y en caso de que no esté creada...help!!??
Obs: para que esos SET o STORE lleguen a la Instancia previamente se hizo un GET. La operación STORE, se le haya hecho un SET o no, va a desbloquear la clave. Pero no sabemos cómo reacciona la Instancia.

Gracias

**Comment by iago64** [comment]
Buenas buenas!
En las pruebas no tenemos ese caso planteado...
Pero eventualmente, lo que plantearon bien podría simplemente decir, se libero la clave y listo :)
Abrazo!

**Comment by GabrielRuderman** [comment]
Muy bien, gracias!
