### ISSUE TITLE
Desconexion inesperada de ESIs en Planificador

### ISSUE THREAD

**Issue by alabarque** [sisoputnfrba/foro#1180]
Buenos dias, tengo una duda respecto a esta seccion.

En nuestro codigo si se desconecta un ESI que se envio a ejecutar en el planificador, luego al hacer recv reconoce que se desconecto. 

Hasta aca todo bien, pero el problema estaria en que este es el unico momento de comunicacion entre un ESI y el planificador. Si un ESI se desconectara, por ejemplo, mientras esta en la cola de bloqueados de alguna key, recien cuando se enviaria a ejecutar se reconoceria que se desconecto.

Mi pregunta ahora es, el planificador deberia reconocer estas desconexiones en cualquier momento? O no hay problema de que se de dicha interaccion de esta manera?

**Comment by tferraro** [comment]
Buenas!

No hay problema de que sea medio-async, mientras que la razón sea justamente por un tema de que detecta la baja en el momento que se va a comunicar ([y no está preguntando todo el tiempo](https://www.youtube.com/watch?v=7ryEPlivh9Y)).

**Comment by alabarque** [comment]
jajaja, dale perfecto. 
Lo que me hacia ruido era sobre todo por la parte esa de las colas de bloqueados, porque como existen las claves inicialmente bloqueadas y dado que recien se comunica con un ESI cuando se envia a ejecutar, podrian estar ahi hasta que finalice el planificador.
