### ISSUE TITLE
Detalle en Prueba Algoritmos de Distribución

### ISSUE THREAD

**Issue by ricardoAguirreSanchez** [sisoputnfrba/foro#1182]
Buenas!

Revisando el documento de test, nos encontramos con algo que si bien no es el foco de la prueba, lo comento solo para que se tenga en cuenta o me corrijan en su defecto si estoy equivocado, esto es en Prueba Algoritmos de Distribución, cuando se ejecuta el ESI_MultiClave y luego el ESI_MultiReemplazo, ambos en su contenido tienen la clave nintendo:consola:gamecube, en ESI_MultiClave esta como **SET nintendo:consola:gamecube Mario** y en ESI_MultiReemplazo esta como **SET nintendo:consola:gamecube FinalFantasyTactics**, es decir, en la primera ocupa una entrada y en la segunda ocupa dos, caso que según el enunciado no debería poder darse.

"Aclaraciones importantes sobre las operaciones
SET: En caso de que la clave cuente previamente con un valor, el comando SET no podrá hacer que se ocupen mas entradas (puede ocupar mas espacio hasta llenar las entradas actualmente asignadas), pero si podrá hacer que se reduzca la cantidad de entradas utilizadas, es decir, que el SET puede liberar entradas ocupadas por la clave al achicar el valor."

Igual como dije, el foco de la prueba no se vería muy afectado ya que la distribución de las claves se va a ver igualmente en las instancias dado que esta clave esta casi al final del esi, solo queríamos avisar de esto para que se tenga en cuenta al momento de la revisión presencial.

Saludos

**Comment by iago64** [comment]
Gracias por el aviso, lo revisamos!

Abrazo!

**Comment by iago64** [comment]
Buenas Buenas!

Cambiar el ESI ahora nos puede complicar otras pruebas, ya que como notaste bien, no cambia el enfoque de las pruebas, vamos a dejarlo y si algo falla estamos advertidos de que es una posibilidad y que eventualmente como no es foco de la prueba no resta nada (pero un lindo manejo del error si suma ;) )

Abrazo!

**Comment by ricardoAguirreSanchez** [comment]
Listo , gracias!.
