### ISSUE TITLE
Reincorporacion Instancia

### ISSUE THREAD

**Issue by mgnizz** [sisoputnfrba/foro#1183]
Buenas! Tenemos la siguiente duda:
¿Cuando una instancia muere y se vuelve a levantar, los datos que están "storeados" se tienen que levantar con la instancia? Es probable que mientras estaba caída el coordinador haya eliminado un par de entradas/keys, y la instancia no se enteraría de esto.
La solución que se nos ocurrió es que cuando se reconecte la instancia, el coordinador le informe las claves que tiene almacenadas de ella y que la instancia solo cargue estas mismas.
¿Esto esta bien o hay algo en el enunciado que no estamos viendo?

Muchas gracias desde ya.

Saludos!

**Comment by iago64** [comment]
Esta perfecto, no se preocupen :)

**Comment by afilgueira** [comment]
@mgnizz quedó claro? Podemos cerrar?

**Comment by glepetic** [comment]
Si pueden cerrar, estamos en el mismo grupo, ya quedo resuelto, gracias!
