### ISSUE TITLE
Prueba Deadlock mal implementada

### ISSUE THREAD

**Issue by NicoFeld** [sisoputnfrba/foro#1185]
Hola estuve corriendo la prueba de deadlock y como esta solo quedan en deadlock ESI_MilanesaCompleta y  ESI_MenuCompleto.
Para que funcione todo correctamente como esta en el enunciado habria que **modificar el ESI_Bar2** moviento el GET bebida1 despues del GET bebida15.
Quedando:
GET bebida2
GET bebida3
GET bebida4
GET bebida5
GET bebida6
GET bebida7
GET bebida8
GET bebida9
GET bebida10
GET bebida11
GET bebida12
GET bebida13
GET bebida14
GET bebida15
GET bebida1

Y otra aclaracion chiquita, en los ESIs que tienen que esta cargados quedo el ESI_Simple, que no tiene ningun uso en la prueba.

**Comment by iago64** [comment]
Mil gracias de nuevo @NicoFeld si queres ese cambio podes subirlo como un PR al repo y lo mergeamos :)

Abrazo!

**Comment by iago64** [comment]
Listo, se hizo el cambio gracias por la prueba 😄
