### ISSUE TITLE
Errata Prueba y Consulta de Instancia

### ISSUE THREAD

**Issue by agusmoles** [sisoputnfrba/foro#1186]
Buenas, tres cosas:

_1._ En la prueba de algoritmos de reemplazo y compactacion, en el setup ponen que se usa el ESI_Compactador1 y en los pasos de ejecucion ponen que el 2. 

_2._ Cuando se reemplaza una clave, deberiamos primero storearla (bajarla a disco)? Porque tal vez no se haya hecho un store (ya sea por el propio ESI o por el dump) y, si se cae la instancia, cuando el coordinador le envie tal clave, va a fallar el **open()** del archivo de la clave (porque no verifico si el caso "malo" y basicamente es preguntar si hay que verificarlo o no jajaja)

_3._ Cuando dice: 
> Se ejecuta un error al recibir un pedido sobre una clave reemplazada

No entendemos a que se refiere, si nos podrian explicar...

Saludos! Gracias

**Comment by LeaTex** [comment]
2. No.
La condición que plantean se les va a dar igual aunque no haya reemplazo. Si tenés una clave recién seteada, y bajan la instancia antes de que se haga el store o el dump, igual no van a tener esa clave en un archivo del disco, y no la van a poder levantar cuando se reconecte.

**Comment by iago64** [comment]
Buenas Buenas!
1.- Si fue un pifie, originalmente estabamos pensando en usar el 2,  pero lo ajustamos a ultimo minuto al 1 para unificar pruebas, ahi lo fixeamos en las pruebas.

2.- Tal cual dice @LeaTex, no tienen que hacer nada, si se pierde el valor, una lastima, mas se perdía en los principios de los 90 con los discos de 5 1/4 y los de 3 1/2 y aun asi el mundo siguió viviendo.
Conclusión, no se la rebusquen al dope 😄 

3.- Simple, si reemplazaste una clave y por ej te pido que hagas el STORE de esa clave, me tenes que devolver el error de que la clave ya no existe en la instancia :)

Abrazo!

**Comment by agusmoles** [comment]
Bien, entonces con el 2 no hay que hacer nada? Es decir, aunque el Coordinador me diga que yo tengo esa clave cuando me reconecte, no va a tener valor, esta bien asi?

Perdón pero ando un poco mareado jaja

Gracias

**Comment by iago64** [comment]
Tranqui, el ESI_Compactador2 por ahi lo usemos en la prueba de Estres

**Comment by agusmoles** [comment]
Me referia al punto 2 jajaja aunque buen dato

**Comment by iago64** [comment]
Aaah joya 👍 
Por las dudas, agregale el if al open y si te devuelve error, creas la clave pero sin valor :)

**Comment by agusmoles** [comment]
Dale, gracias @LeaTex y @iago64 

Saludos

**Comment by iago64** [comment]
Podrías asignarle la entrada y ponerle que tiene ocupados 0 bytes.
Igual estas en un caso muy muy borde, porque si te fijas los retardos:

![image](https://user-images.githubusercontent.com/1622109/42512838-f6436b0c-842b-11e8-8171-b262c327af48.png)

El retardo de cada operación, es 30 veces mas grande que el de Dump 😸 

Abrazo!

**Comment by agusmoles** [comment]
Claro pero igual no me serviria porque yo aun sigo viendo los espacios desde el storage (viendo cual esta vacio). 

Con respecto a eso, yo pense que el retardo era en milisegundos, no es asi? No vamos a tardar bastante en hacer las pruebas con 300s? 😆 

Saludos!

**Comment by iago64** [comment]
Pero, vos te fijas el espacio en el storage o en tus estructuras administrativas? Si queres poner un null como palabra "reservada" no creo que te cambie las cosas.

Y si los retardos son en ms y aun asi puede ser que tarden bastante las pruebas, por eso es que estamos a la espera de que nos cuenten como vienen con los tiempos y de ahí que los vamos a ir ajustando de a poco para que no sean eternas, de todas formas, menos de 100ms no creo que tengamos entre operaciones.

Abrazo!

**Comment by agusmoles** [comment]
En el storage me fijo, justamente por eso, porque no tenemos una tabla de entradas por cada storage, sino por cada clave que tiene la instancia (aunque creo que recomendaban tener 1 a 1 pero bueno lo hicimos diferente 😆 ). Y con storage me refiero a la entrada en si, en donde va el valor.

Y el intervalo de dump es en ms tambien? Porque sino no me daria que es 30 veces mas grande jajaja y yo lo estaba manejando en segundos

Saludos!

**Comment by iago64** [comment]
Si señor, todos los retardos están en ms (porque así era mas simple controlar los tiempos)

**Comment by agusmoles** [comment]
Gracias Dami. Listo!

**Comment by LeaTex** [comment]
@iago64 
> Si señor, todos los retardos están en ms (porque así era mas simple controlar los tiempos)
No sé si me perdí una parte del issue, pero en el enunciado son unidades diferentes.

Coordinador:
![imagen](https://user-images.githubusercontent.com/6115573/42520771-82c753ac-843d-11e8-96cb-3fcfe57b2bbb.png)

Instancia:
![imagen](https://user-images.githubusercontent.com/6115573/42520786-90fa15ae-843d-11e8-9bfa-977271787c4a.png)

**Comment by iago64** [comment]
@LeaTex https://www.youtube.com/watch?v=ffjXNpszfB4 
En fin, habrá que bajar los tiempos de dump a 1 segundo 😢
Al menos me deja tranquilo que los retardos en la planificación si son en MS que es lo importante a fin de cuentas para los tiempos de las pruebas.
