### ISSUE TITLE
Conexión putty

### ISSUE THREAD

**Issue by vickyRuiz** [sisoputnfrba/foro#1188]
Buenas! Estamos tratando de usar putty para acceder a nuestra VM, y nos tira error de network timeout. Estamos usando la IP que nos tira ifconfig (por las dudas ya las probamos todas), SSH y puerto 22. El error es siempre el mismo.
Como dati adicional, estamos usando el wifi de la facu, en Medrano.
Por qué puede ser que no conecte?

**Comment by iago64** [comment]
Buenas, una pregunta, como tienen configurada la VM?
Para que putty funcione tienen que tener la VM conectada a Adaptador Puente:

![image](https://user-images.githubusercontent.com/1622109/42512539-41b7482a-842b-11e8-995f-744e1131f5c4.png)

Abrazo!

**Comment by iago64** [comment]
Joya lo damos por cerrado entonces :)
