### ISSUE TITLE
Detalles Varios Doc Test

### ISSUE THREAD

**Issue by ricardoAguirreSanchez** [sisoputnfrba/foro#1189]
Buenas,

Revisando los test encontramos algunos pequeños detalles que vimos:
1.- ESI_Spoilers en la 4° sentencia le estaría faltando una "i" (SET spoler2 también-esta-muerto), a menos que este así a propósito en ese caso no dije nada
2.- En la prueba de planificación, el HRRN con w=12 s=3 el RR seria 5 

Saludos.

**Comment by agusmoles** [comment]
Sumo tambien con respecto a la 1, que el ESI_Spoilers y el ESI_Westworld son abortados por hacer SET de una clave que no tienen "bloqueada". Queria saber si es a proposito tambien porque no muestro en esos casos cuanto era la rafaga y demas.

Saludos

**Comment by iago64** [comment]
Lo revisamos y les avisamos :)

**Comment by afilgueira** [comment]
@agusmoles que clave no tienen bloqueada?
Y aprovecho y te pregunto, qué valores te dieron diferentes? Yo calculé esto:

![image](https://user-images.githubusercontent.com/1786754/42545924-131b9d34-8491-11e8-892f-dfb1eb5fc772.png)

**Comment by agusmoles** [comment]
Buenas! El ESI Spoilers hace **STORE** de la clave **spoiler1** y luego un **SET**. En el Westworld hace un **STORE** de la clave **principal2** y luego un **SET**, por eso se abortan.

Dejo screens del planificador (al principio comienza igual que con SJF-SD y esta prueba tambien pero despues sigue distinto, capaz por mala implementacion mia):

![sin titulo](https://user-images.githubusercontent.com/28370654/42546367-7eeee91a-8493-11e8-935f-2f5cc7881015.png)
![sin titulo1](https://user-images.githubusercontent.com/28370654/42546372-82f3959c-8493-11e8-8d3b-f9d0a94a1d4a.png)
![sin titulo2](https://user-images.githubusercontent.com/28370654/42546373-831f3f3a-8493-11e8-97cd-4e8f02927fa2.png)
![sin titulo3](https://user-images.githubusercontent.com/28370654/42546374-834a4c98-8493-11e8-936e-349d5b8d1d59.png)

Saludos!

**Comment by afilgueira** [comment]
Genial, actualizamos los ESIs para que no se aborten. Si bien el algoritmo se ve en acción antes, no era la idea original. Sobre las estimaciones, me llama la atención la cantidad que veo. En principio deberías hacerlas cuando un ESI entra a ready y nada más. Es ese el caso?

Saludos!

**Comment by agusmoles** [comment]
Con el SJF-CD no tengo que recalcular la estimacion de la proxima rafaga cada vez que recibo que se ejecuto una sentencia? Y de ahi ver si lo tengo que desalojar con el primero de Listos (previamente ordenada tal cola). Es justamente eso lo que hago. Puede que este mal pero tenia entendido que era asi

Saludos!
p.d: Buenisimo, mas tarde pulleo y sigo fijandome

**Comment by afilgueira** [comment]
Buenas, sí; Pero la primera vez usas la fórmula, y las siguientes le restas lo que ejecuto.

Ejemplo: estimas la ráfaga del ESI1 en 5.5. Dos instrucciones más tarde llega el ESI2 con una estimación de 3.

5.5 - 2 (instrucciones) = 3.5 > 3 (del ESI2) --> desalojas porque según tu estimación "le falta 3.5"

Saludos!

**Comment by ricardoAguirreSanchez** [comment]
@afilgueira siguiendo el ejemplo que se planteo, tengo el ESI1 con 3.5, digamos que ejecuta una sentencia más y se bloquea y luego por algún desbloqueo de consola pasa a ready, cual seria la nueva estimación que tendría este ESI1 al llegar a ready?

Saludos

**Comment by afilgueira** [comment]
Si si, para las estimaciones usas la rafaga completa y la estimación anterior. En la imagen que subi, se distingue la estimacion del calculo del "remanente".

Saludos!

**Comment by ricardoAguirreSanchez** [comment]
Joya, gracias.

**Comment by agusmoles** [comment]
Buenas! 

@afilgueira sigue abortandose el ESI_Westworld porque tiene dos STORE de principal4. Mas tarde reviso lo de la planificacion porque no entendi muy bien lo que me planteaste.

Saludos!

**Comment by afilgueira** [comment]
Mala mía con el copy-paste. Gracias por el aviso y avisa si no quedo claro lo de planificación!

**Comment by agusmoles** [comment]
Dale, cualquier cosa creo un issue referenciando este y te menciono. Asi pueden cerrar este

Saludos!
