### ISSUE TITLE
Problema con SJF-CD

### ISSUE THREAD

**Issue by agusmoles** [sisoputnfrba/foro#1191]
Siguiendo con el issue #1189 @afilgueira, no entiendo por que no funciona como dice la prueba... dejo las partes del codigo que se basan en la actualizacion de las variables del algoritmo...

Apenas inician los ESIs, se setea la estimacion inicial en las variables "estimacionProximaRafaga" y "estimacionRafagaActual"

_Cada vez que ejecuta una sentencia:_

```
ESI->rafagaActual++;
ESI->estimacionProximaRafaga--;
```

Y verifico si se tiene que desalojar con los ESIs ordenados en la cola de Listos, _si se desaloja_:
`
ESIEjecutando->rafagaActual = 0;	// SE RESETEA LA RAFAGA ACTUAL (PORQUE FUE DESALOJADO)
`
Y lo paso a listos..

_Si se bloquea:_ 

```
ESI->rafagaActual++;			// CREO QUE AUNQUE SE HAYA BLOQUEADO CUENTA COMO UNA RAFAGA, ENTONCES ANTES DE SETEAR LAS VARIABLES LE SUMO UNO
ESI->estimacionProximaRafaga = (alfaPlanificacion / 100) * ESI->rafagaActual + (1 - (alfaPlanificacion / 100) ) * ESI->estimacionRafagaActual;
ESI->estimacionRafagaActual = ESI->estimacionProximaRafaga;		// AHORA LA RAFAGA ANTERIOR PASA A SER LA ESTIMADA PORQUE SE DESALOJO
ESI->rafagaActual = 0; 	// LO SETEO EN 0 PORQUE FUE "DESALOJADO" PORQUE SE BLOQUEO
```

_Y cuando termina:_

```
ESI->rafagaActual++;
ESI->estimacionProximaRafaga = (alfaPlanificacion / 100) * ESI->rafagaActual + (1 - (alfaPlanificacion / 100) ) * ESI->estimacionRafagaActual;
```

Muchas gracias! 
Saludos

**Comment by afilgueira** [comment]
Es medio difícil viendo de a cachitos, pero me llama la atención que lo pongas en cero al desalojarlo. Debería mantener su ráfaga; lo desalojaste, pero tu estimación dice que le faltan X (y no cero).

Saludos!

**Comment by agusmoles** [comment]
Al parecer era eso, ahora dan bien las estimaciones. Muchas gracias!

Saludos
