### ISSUE TITLE
1er Recuperatorio TP

### ISSUE THREAD

**Issue by cheja** [sisoputnfrba/foro#1192]
Buenas, como va?
Queria saber cuando es la fecha del 1er recuperatorio del TP, ya que en el enunciado si no me equivoco dice que es el 28/7 pero en el calendario de `utnso.com` dice que es el 21/7.

Saludos y gracias!

**Comment by tferraro** [comment]
el 21/7!

Se nos chispoteó en el enunciado :wink:.

Igual, la facu está cerrada en la semana del 23 al 29, así que no hay manera de hacerla de todas formas :stuck_out_tongue:.

Ahora mando una errata para corregir ese typo, gracias por el aviso! :smile: 

Tom

**Comment by cheja** [comment]
@tferraro Perfecto, gracias!
