### ISSUE TITLE
Duda prueba de distribución Key Explicit

### ISSUE THREAD

**Issue by vickyRuiz** [sisoputnfrba/foro#1193]
Hola! Corriendo las pruebas de Key Explicit, noté que el resultado esperado no coincide con mis cálculos de KE: 

> Los resultados esperados se irán validando según el algoritmo, pero debería verse en el
> caso de EL que las instancias se van llenando parejo (1 a 1) y en el caso de Key Explicit el
> ESI_Bar debería quedar todo junto en una sola instancia y el resto de las claves deberán
> ubicarse en la segunda instancia y eventualmente habrá reemplazos.

En particular, la diferencia que me da es que las claves del ESI_MultiClave que empiezan con M (microsoft:...) me quedan en la primera instancia. Como el alfabeto tiene 26 letras, y la m es la número 13, va en la primera instancia. De la n en adelante, van a la siguiente instancia. 

Estoy pensando mal las cuentas? Gracias!

**Comment by afilgueira** [comment]
Hola, tiene sentido lo que decís. En la entrega lo tenemos en cuenta, y después corregimos la prueba. Saludos!

**Comment by vickyRuiz** [comment]
Genial! Gracias.
