### ISSUE TITLE
Descripcion Prueba Algoritmos de Planificación incorrecta

### ISSUE THREAD

**Issue by NicoFeld** [sisoputnfrba/foro#1194]
Para SJF-CD
- Iniciar los ESIs en el orden especificado
- Esperar a que los tres se bloqueen
- Pausar, desbloquear "spoiler2", "principal3" y reanudar
Página 8/15
- La estimación de ESI_Spoilers debería ser 2,5 y la de ESI_Westworld 4,5.
- Debería ejecutar ESI_Spoilers y bloquearse, ESI_Westworld y desbloquear
"principal1". ESI_Fargo debería desalojarlo y bloquearse. Luego continúa
ESI_Westworld y desbloquea "principal2"**. ESI_Fargo debería desalojar nuevamente
y finalizar. ESI_Westworld continúa hasta bloquearse.**
- Pausar, desbloquear "spoiler3", "principal4" y reanudar
- La estimación de ESI_Spoilers debería ser 3,75 y la de ESI_Westworld 4,75.

Donde esta marcado en negrita deberia decir:
-ESI_Westworld sigue ejecutando ya que su remanente es 0,5 , menor a la estimacion de 2 del ESI_Fargo por lo que ejecuta GET principal4 y se bloquea.
-ESI_Fargo finaliza

Luego debe desbloquearse las claves como dice en la prueba y tambien sigue como dice la prueba.
 Los numeros no cambian, es solamente para tener en cuenta que ESI_Westworld no va a ser desalojado nuevamente

**Comment by afilgueira** [comment]
Sí, tenés razón. La prosa no es lo nuestro, pero el excel dice eso mismo. Lo tenemos en cuenta para la entrega y lo subimos corregido para la v1.2. Saludos!

![image](https://user-images.githubusercontent.com/1786754/42638106-348ac3a4-85c3-11e8-9a99-62de7fe42df3.png)

**Comment by agusmoles** [comment]
Justo iba a postear esto mismo, a mi me dio asi...

![sin titulo](https://user-images.githubusercontent.com/28370654/42642742-ea15dbb4-85cd-11e8-8390-d5b67579b7a3.png)

Saludos!

**Comment by afilgueira** [comment]
Ahi quedó acomodado. Si lo ven bien, cierren porfa!

**Comment by tferraro** [comment]
@NicoFeld @agusmoles que tul con esto, quedó bien arraglado? Se puede cerrar el issue? 👮

**Comment by agusmoles** [comment]
Sisi, habia quedado bien arreglado.

Saludos!
