### ISSUE TITLE
Duda Prueba Algoritmo de Planificacion HRRN

### ISSUE THREAD

**Issue by agusmoles** [sisoputnfrba/foro#1195]
Buenas, no tengo muy en claro como ver si el algoritmo esta yendo como la prueba dice...

No entiendo que significa S en el cuadro de la prueba y si es la estimacion de la proxima rafaga (lo cual creo, porque me coincide), la cuenta para calcular la tasa de respuesta (RR) no me estaria dando con los datos de la prueba y ya de por si me estaria dando distinto:

RR = (S + W) / S = 15 / 3 = 5

No entiendo por que en el ESI_Fargo me da menos W, solo se le va sumando uno por sentencia a los que estan en la cola de Listos, o no?

Dejo screen:

![sin titulo](https://user-images.githubusercontent.com/28370654/42644472-116d420c-85d2-11e8-8417-cd187b3d87ed.png)

Saludos! Gracias

**Comment by afilgueira** [comment]
Hola, estás viendo el doc de pruebas viejo. Esto lo corregimos hace unos días (y mandamos post con toda la info). Saludos!

**Comment by agusmoles** [comment]
Tenes razon, y con respecto a esto?:

> No entiendo por que en el ESI_Fargo me da menos W, solo se le va sumando uno por sentencia a los que estan en la cola de Listos, o no?

**Comment by ricardoAguirreSanchez** [comment]
@agusmoles, a nosotros nos paso algo parecido, pero revisando vemos que todo depende del orden de llegada de los 3 primeros ESIs a ready, es decir, el ESI_Fargo se perdía de contar algunas sentencias dado que era el ultimo que llegaba, viendo esto probamos pausando todo el sistema antes, luego ejecutar los 3 esis (ESI_Spoilers, ESI_Westworld, ESI_Fargo) y luego continuar el flujo (como para asegurar que no se pierdan de contar ninguna sentencia) haciendo esto nos da el W=12 del ESI_Fargo, nosotros lo vamos a justificar así el día de la entrega.

Saludos.

**Comment by agusmoles** [comment]
Y el desbloquear spoiler2 lo hacen mientras ejecuta o antes de continuar la ejecucion?

Buenisimo! Gracias

**Comment by ricardoAguirreSanchez** [comment]
Solo lo pausamos para ingresar los tres primeros esis, luego continuamos normal como en el enunciado, en cuando al desbloquear no hace falta pausar el sistema porque ya tenés al ESI_Spoiler bloqueado, así que con desbloquear dos veces (según nuestra implementación) bastaría ya que esto lo hace en paralelo.

Saludos

**Comment by agusmoles** [comment]
Buenisimo, mañana lo pruebo entonces. Gracias!
