### ISSUE TITLE
Prueba Algoritmos de Distribución

### ISSUE THREAD

**Issue by PabloAntivero** [sisoputnfrba/foro#1198]
Buen día : En las pruebas de Algoritmo de Distribución dicen que **en el caso de Key Explicit el
ESI_Bar debería quedar todo junto en una sola instancia y el resto de las claves deberán
ubicarse en la segunda instancia**  Sin  embargo existe el ESI_MultiClave con una clave que empieza con "m" , segun lo que dice el TP , ^15: La letra "a" se codifica como el carácter 97 y la "z" como el 122, por lo que habrá 25 letras a ser divididas en 4 instancias, cada una con 7 letras y la última con solo 4.

Con Lo cual si yo tengo 2 instancias Activas para hacer la prueba y la m esta en la posicion 13 de mis 25 letras totales y se redondea hacia arriba, esto quiere decir que en la instancia 1 grabo 13 letras (por que se redondea hacia arriba) y en la 2 las 12 restantes tal como se especifica en el ejemplo. con lo cual las claves que empiecen con "m" las tendria en la instancia1 tmb. Es correcto? puede que este mal aclarado en las pruebas?

**Comment by vickyRuiz** [comment]
Sí, es como vos decís. Lo confirmaron ayer en #1193

**Comment by natoszme** [comment]
Buenas! La misma duda está resuelta [acá](https://github.com/sisoputnfrba/foro/issues/1193)

**Comment by natoszme** [comment]
Igual ojo que son [26 letras](https://github.com/sisoputnfrba/foro/issues/1133)

**Comment by afilgueira** [comment]
Ahi quedó acomodado. Si lo ven bien, cierren porfa!

**Comment by PabloAntivero** [comment]
Solucionado
