### ISSUE TITLE
Prueba algoritmos compactacion

### ISSUE THREAD

**Issue by ricardoAguirreSanchez** [sisoputnfrba/foro#1199]
Buenas,

Viendo el caso planteado en el enunciado en la pag 5 (en la parte de compactación), se resalta que luego de la sentencia:
**SET opcion3 pizzacuatroquesosgrande**, el estado del storage seria todo completo, pero en la pagina anterior se dice que se usa el ESI_Compactador2 y dado que este no tiene esta sentencia puede que se trate de ESI_Compactador1 y sea un error de tipeo?, por las dudas lo consultamos.

Saludos.

**Comment by iago64** [comment]
Fue un pifie en el documento, lo vamos a cambiar para la V1.2 (que seguro la sacamos el lunes con los ajustes finos en los tiempos), pero el que va es el ESI_Compactador1, el 2 nos va a quedar para la prueba de estres nomas :)

Abrazo!

**Comment by ricardoAguirreSanchez** [comment]
LIsto, gracias!
