### ISSUE TITLE
Escala del Intervalo de Dump

### ISSUE THREAD

**Issue by santiluccadeguevara** [sisoputnfrba/foro#1200]
Hola!

En el issue #1170 pregunté si había que sincronizar el Dump y me dijeron que sí, y me tiraron un pseudocódigo con `usleep` que representaba el tiempo que se bloqueaba el hilo para ejecutar el Dump, así que asumí que el Dump se ejecuta cada X **microsegundos** en paralelo con los pedidos del Coordinador.

Y ejecutando las pruebas, `htop` me tira que consumo el 99% de la CPU por culpa de la Instancia, hecho que no sucede cuando pongo un intervalo muy grande de Dump (Algo así como de 10^6).

Por lo tanto, si no es casualidad que alargar el tiempo de Dump me consume menos CPU, las unidades del intervalo de Dump son en segundos, milisegundos, o microsegundos?

Desde ya, muchas gracias. Saludos!

**Comment by LeaTex** [comment]
santi, la unidad del dump es la que dice el enunciado: segundos.

lo aclaramos hace unos días acá: https://github.com/sisoputnfrba/foro/issues/1186#issuecomment-403867615

**Comment by santiluccadeguevara** [comment]
Ah... No lo había visto... Perdón DX Mil gracias!!
