### ISSUE TITLE
Cambio de horario para el sábado

### ISSUE THREAD

**Issue by sebastianciancio** [sisoputnfrba/foro#1201]
Buenos días,
   Acabamos de ver que nos asignaron el horario de 12.30 hs para el Sábado.

   Particularmente en nuestro grupo, uno de los miembros trabaja el sábado hasta las 14 hs. Es posible cambiar el horario para las 15 hs?

Nuestro grupo se llama LOS OPERANTES.

Aguardo sus comentarios. 
Gracias

**Comment by iago64** [comment]
Buenas buenas! 
Les cambiamos el horario a las 16hs, por favor sean puntuales porque estamos **muy complicados a la tarde**

Saludos.-

**Comment by sebastianciancio** [comment]
Muchas gracias. Así será.
