### ISSUE TITLE
Duda prueba minima

### ISSUE THREAD

**Issue by cheja** [sisoputnfrba/foro#1202]
Buenas, tengo una consulta sobre la prueba minima.
Me sucede lo siguiente:
```
ESI_Largo -> Ejecuta y finaliza
ESI_Tiramisu ->Ejecuta y se bloquea
ESI_MultiClave -> Ejecuta...
desbloquear postre:ingrediente1 -> se desbloquea ESI_Tiramisu
ESI_MultiClave -> Sigue ejecutando..

```
Cuando `ESI_MultiClave`  finalize no deberia ejecutarse `ESI_Tiramisu ` en lugar de `ESI_MilanesaCompleta`?
Estimacion  `ESI_Tiramisu ` : (1 rafaga + 3 est. inicial) / 2 => 2
Estimacion  `ESI_MilanesaCompleta` : 3 (ya que como todavía no ejecuto mantiene la estimación inicial)

Hay algo que estoy entendiendo mal?

**Comment by iago64** [comment]
Buenas buenas!
En la prueba mínima, estas con SJF-SD, con lo cual si contas la cantidad de lineas debería primero ejecutar ESI_MilanesaCompleta (15) que tiene menos instrucciones que ESI_Tiramisu (30) :)

Abrazo!

**Comment by cheja** [comment]
@iago64 Osea la estimacion se usa solo para SJF-CD y HRRN, y SJF-SD cuenta la cantidad de instrucciones? Tenia entendido que la estimacion se usaba en todos los casos

**Comment by iago64** [comment]
@cheja el tema es que vos en SJF (ya sea CD o SD) vos primero calculas con la fórmula y después vas restando lo que hiciste, fijate que en el issue https://github.com/sisoputnfrba/foro/issues/1189 justo Adriano habla del tema de como tomarlos (al menos como estan calculados en las pruebas)

Abrazo!

**Comment by cheja** [comment]
@iago64 @afilgueira  Ahi vi el issue, pero hay algo que no entiendo entonces. En la **Prueba de algoritmos de planificacion**, el caso con `SJF-SD` una linea dice:
```
- La estimación de ESI_Spoilers debería ser 2,5 y la de ESI_Westworld 4,5.
```

Esas estimaciones solo consideran la estimacion inicial y la rafaga ya ejecutada, porque en este caso (el de la prueba inicial) entra en consideracion la cantidad de sentencias del ESI y en ese no?

**Comment by afilgueira** [comment]
Ahi quedó acomodado. Si lo ven bien, cierren porfa!

**Comment by lcabello90** [comment]
Por mi si, ya aprobé el TP :D

**Comment by cheja** [comment]
@tferraro Sisi perfecto
