### ISSUE TITLE
Duda planificación en Prueba Mínima 

### ISSUE THREAD

**Issue by ltrinidad** [sisoputnfrba/foro#1203]
Buenas!!! 
Tenemos la siguiente duda con la prueba minima: 
La misma dice que hay que...
```
1) Pausar y Levantar ESI_Largo - ESI_Tiramisu - ESI_MultiClave
2) Continuar e iniciar los otros dos (ESI_MilanesaCompleta y ESI_MenuParrilla)
```
La duda puntualmente es como se espera que realicemos esta prueba, porque podemos interpretarla de dos formas:

A) Pausar el planificador y levantar los 3 iniciales, continuar y al toque levantar los otros dos
B) Pausar el planificadpor y levantar los  3 iniciales, **esperar que terminen, o se bloqueen** (como en el caso de ESI_Tiramisu para la clave postre:ingrediente1), y luego levantar los otros 2

Con A el orden de finalizacion es : 
```
ESI_Largo
ESI_Tiramisu
ESI_MultiClave
ESI_MilanesaCompleta
ESI_MenuParrilla
```
_(Creemos que termina así porque hay igualdad en la estimación inicial y desempata por FIFO, como dice el enunciado)._

Con B el orden de finalizacion es el correcto (según el documento de pruebas).

Entonces? 

Desde ya, muchas gracias!!!

**Comment by iago64** [comment]
Buenas buenas!
Va el orden B, ya que la idea es que ni bien lleguen arranquen a ejecutar.
Abrazo!

**Comment by ltrinidad** [comment]
Hola!! Gracias por responder Damian! 
Con eso de "ni bien lleguen arranquen a ejecutar" interpretamos que te referis a los ultimos 2 que llegan (MilanesaCompleta y MenuParrilla). Entonces, estariamos bien con la prueba minima!

Abrazo!

**Comment by iago64** [comment]
Si señor, la idea es que cuando carguen los 2 ESIs no esten obligados a tener la planificaciòn detenida (como para verificar que no tienen esperas activas si no tienen ESIs en la cola de ready... ups le tire un spoiler del objetivo de la prueba 😸 )
