### ISSUE TITLE
Duda matar ESI sin comando kill

### ISSUE THREAD

**Issue by pdelucchi** [sisoputnfrba/foro#1204]
Buenas!

Tengo una duda respecto a que pasaría si mato una ESI mediante un CTRL+C. En ese caso, libero los recursos o entraría en uno de los casos donde la ESI se aborta por error en los que solo se manda la ESI a finalizados sin liberar recursos? (Ejemplo, desconexión de instancia). Leí un par de issues similares pero no me termina de quedar en claro ese caso en particular.

Muchas gracias!!

Pablo.

**Comment by LeaTex** [comment]
Pablo, no creo que matar un proceso ESI con Ctrl+C forme parte de las pruebas (de hecho no está en el documento de pruebas), sobre todo porque la vida de un ESI suele ser de pocos segundos.

En mi grupo ni tuvimos en cuenta ese caso, pero si uds quieren meterse en ese baile, te diría que lo tomen como que el ESI se aborta por algún error, liberando los recursos que tenía tomados.

**Comment by mgarciaisaia** [comment]
Pablo, imaginemos por un momento que el Linux de la vm en que desarrollaron el tp no hubiera liberado los recursos de cada proceso que terminó con un segfault (o cada vez que crasheó eclipse). ¿Cuántas veces más hubieras tenido que reiniciar la vm en el cuatrimestre?

Cada vez que un esi sale del sistema (y el sistema siga funcionando) deberian liberar los recursos que tenga tomados.

Después, si llegamos a probar eso durante la entrega o no... esa es otra canción. El comportamiento esperado sigue siendo que libere.

Un abrazo.

**Comment by pdelucchi** [comment]
Genial, muchas gracias a ambos! quedó claro. Cierro el issue.

Un abrazo.
