### ISSUE TITLE
Dump y sincronizacion

### ISSUE THREAD

**Issue by FedericoJoel** [sisoputnfrba/foro#1205]
buen dia, como estan?

Mi duda es la siguiente, realizamos el dump generando un thread que esta corriendo continuamente, tira un sleep por X tiempo y ejecuta una funcion dump(); encargada de bajar lo que esta en la memoria a archivos de texto.

El tema viene cuando el enunciado dice, en cita literal `cuando esta en ejecucion el proceso de compactacion y dump, no se permitira ejecutar operaciones en el sistema de RedisTinto y quedaran en espera a que el proceso se complete correctamente`

Que es lo que tengo que sincronizar? 
1) que cuando estoy haciendo dump no pueda hacer un set o store (con un mutex)?
En este caso, es transparente para el coordinador, coordinador envia una instruccion a instancia, instancia la lee pero no la ejecuta en caso de estar haciendo dump debido al mutex, una vez terminado, ejecuta la instruccion.
2) que corte la ejecucion del sistema cuando estoy haciendo un dump como en el caso de la compactacion, enviado un mensaje al coordinador y diciendole que frene y deje de enviar mensajes a las instancias hasta que el dump termine?
3) no tengo mas opciones

Gracias, Saludos.

**Comment by mgarciaisaia** [comment]
:wave:

Lo que tenés que sincronizar es que mientras se esté haciendo una compactación o un dump no se hagan otras operaciones.

La implementación corre por cuenta de ustedes, pero tienen que garantizar la mutua exclusión entre la compactación, el dump y el resto de las operaciones. Es decir, durante un dump o compactación no deben ejecutarse GETs, SETs ni STOREs. Esas operaciones deberán esperar a que termine de hacerse el dump o compactación, y recién ahí podrán efectuarse.

Recapitulanding:

> que cuando estoy haciendo dump no pueda hacer un set o store

Ajam

> (con un mutex)?

¯\\_(ツ)\_/¯

> que corte la ejecucion del sistema cuando estoy haciendo un dump como en el caso de la compactacion, enviado un mensaje al coordinador y diciendole que frene y deje de enviar mensajes a las instancias hasta que el dump termine?

¯\\_(ツ)\_/¯

**Comment by FedericoJoel** [comment]
Gracias mati!

**Comment by FedericoJoel** [comment]
@mgarciaisaia me queda una duda con esto mati, la sincronizacion esde en la misma instancia solamente?

Osea, que pasa si yo estoy haciendo un SET en la instancia1 que tiene dump cada 100, y tengo una instancia 2 que tiene dump cada 10. 
Si yo implemento con un semaforo en la instancia, por mas que la instancia 2 este haciendo un dump, vos vas a poder hacer set en la instancia 1(lo cual es logico interpretando el enunciado)
Sino, tendria que frenar todas las operaciones, diciendole al coordinador que voy a hacer un dump y esperando a que este me de permiso para hacerlo y avisarle cuando termine.

Me podes ayudar con esto?

**Comment by mgarciaisaia** [comment]
Acordate lo que charlamos en la teoría: tu región crítica tiene que ser lo más chica posible (y no menos que eso).

Entonces la respuesta que estás buscando es la misma que la de "¿Comparten recursos el dump en una instancia con las operaciones que ejecuta otra instancia?".

¿Comparten?

**Comment by FedericoJoel** [comment]
No, no comparten recursos por eso yo decia que simplemente coordino dentro de cada instancia con semaforos, es correcto esto???(dame el ok porfavor de si esta bien asi) Me entro la duda por como esta definido en el tp. @mgarciaisaia

**Comment by mgarciaisaia** [comment]
Así parece 🙃

**Comment by tferraro** [comment]
Cierro por inactividad, cualquier cosa volve a abrir el issue :)
