### ISSUE TITLE
Duda comando desbloquear

### ISSUE THREAD

**Issue by LucianaNapolillo** [sisoputnfrba/foro#1207]
Hola!

Tenemos una duda con la siguiente situación:

- Supongamos que el planificador inicia con la clave "recursoA" bloqueada (esto lo tenemos implementado con un "ESI ficticio" que bloquea a ese recurso)
- Se ejecuta el ESI1 que hace un GET a "recursoA".
- El ESI1 queda en la cola de bloqueados esperando por "recursoA"

Al ejecutar el comando `desbloquear recursoA`, no nos queda claro qué debería pasar. Según el enunciado la lógica sería: 

1) Sacar el ESI1 de la cola de bloqueados y agregarlo a la cola de listos del planificador, porque es el primero de la cola de bloqueados del recursoA.

2) Al hacer de nuevo `desbloquear recursoA`, recién ahí se liberaría el recurso, porque ya no hay nadie esperando por el recurso

¿Esto es correcto?

Estuvimos leyendo los issues, pero no nos queda claro la verdad. En la prueba de deadlock por ejemplo, dice:

> Una vez que no se ejecute nada por bloqueos desbloquear desde la consola las claves
bebida13 y segundoplato:ingrediente3 y esperar que nuevamente quede todo el sistema
bloqueado

El planificador no fue pausado, entonces al desbloquear bebida13, el ESI que estaba esperando por ese recurso va a ser enviado a la cola de listos, y podría potencialmente intentar tomar bebida13, bloqueándose nuevamente, porque nunca se llegó a liberar el recurso. Está bien esto?

**Comment by afilgueira** [comment]
A fines prácticos (y a esta altura) es lo mismo. Mientras ejecutando una o n veces el desbloquear, desbloqueen al primero que tiene que hacer el GET estamos bárbaro.

Saludos!

**Comment by LucianaNapolillo** [comment]
Ok! gracias!
