### ISSUE TITLE
Duda prueba con ESI_Compactador2

### ISSUE THREAD

**Issue by pablomonti** [sisoputnfrba/foro#1208]
Buenas a todos,
en la prueba "Prueba Algoritmos de Reemplazo y Compactación" 
dice: 
"Actividades:
Iniciar solamente la Inst1 y ejecutar el ESI_MultiReemplazo y verificar el orden de ejecución
de los reemplazos.
Una vez finalizado el ESI_MultiReemplazo, bajar la Inst1 e iniciar la Inst2 y ejecutar el ESI
ESI_Compactador2 y verificar en el instante que se inicien las compactaciones si es posible
procesar otra operación (Recomendación​: utilizar el comando Status <clave>)"

El problema es que según veo se prueba con ENTRADAS: 8 TAMAÑO: 10
pero se estarían insertando:

SET opcion1 docenadecarnealcuchillo  <-- legth 23, entradas que ocupa 3
SET opcion2 dosdocenasdecarnesuave <-- legth 22, entradas que ocupa 3
SET opcion3 cuatrodocenasdehumita <-- legth 21, entradas que ocupa 3
SET opcion4 tresempanadas<-- legth 13, entradas que ocupa 2
SET opcion5 dosdocenasdecantimpalo ...........etc
SET opcion6 tresdocenasderoquefort .....................
SET opcion7 cuatrodocenasdejamonyqueso .......................

cosa que entiendo no debería pasar ya que primero estarían ocupando en los tres primeros sets 9 entradas y segundo que no son atómicas, por lo que al insertar la opción 4 no hay entradas atómicas para liberar...
Obviamente podría si quiero insertarlo igual, pero dijeron que esta situación particular no iba a suceder (todas entradas no atómicas)

**Comment by LeaTex** [comment]
@pablomonti efectivamente ese ESI no puede terminar. la instancia debería devolver algún error del tipo "no tengo espacio disponible" o algo así, y el ESI abortar.

de todos modos creo que es un problema de redacción del documento, porque en la tabla de configuración de la prueba dice que se usa ESI_Compactador1.

Con eso script debería funcionar bien.

![imagen](https://user-images.githubusercontent.com/6115573/43012113-e41bd44e-8c1b-11e8-8e21-62f1079c0243.png)

**Comment by afilgueira** [comment]
Hola Pablo, esto que mencionas es un typo. El que debe correr para ese test en particular es el 1. Saludos!

**Comment by pablomonti** [comment]
Ok, Gracias @afilgueira. Cierro

Saludos
