### ISSUE TITLE
Problemas linkeo commons_propias en server

### ISSUE THREAD

**Issue by lusalmeron** [sisoputnfrba/foro#1209]
Hola!

No logro que el server instale y reconozca las bibliotecas que creamos con mi grupo. Hasta ahora, con el makefile crea el _.so_ pero no logramos instalarlo como hicimos con las _so-commos-library_ o el _parsi_. Alguna pista sobre qué puede ser? Es el linkeo del library path? *Tengo que modificar algo en el makefile?*

Gracias y saludos!

![no_ejecuta_el_coordinador](https://user-images.githubusercontent.com/31140640/43028416-3c91c0f4-8c56-11e8-85b7-5439cd5dce65.png)
![no_instala_commons_propias](https://user-images.githubusercontent.com/31140640/43028417-3cbb1738-8c56-11e8-8af3-99c3c95b4efa.png)
![shell_del_coordi](https://user-images.githubusercontent.com/31140640/43028418-3cdfcf42-8c56-11e8-8b9a-59598e87c682.png)

**Comment by lusalmeron** [comment]
Bien, aparentemente ya está corregido el tema del path con el directorio workspace pero ahora rompe por algo nuevo. Comparto foto. Dice algo de un 'main' no reconocido pero en nuestras commons no usamos 'main'. Tiene que ver con el linkeo de la variable de entorno? Del makefile?
Perdón la hora. Saludos!

![librerias_ok_pregunta_por_main](https://user-images.githubusercontent.com/31140640/43032543-cabc7bba-8c8f-11e8-9b34-3cd114092d1b.png)

**Comment by mgarciaisaia** [comment]
👋

El log ese dice primero que las commons propias buildearon OK (`Finished building target: libcommons_propias.so`), pero el problema está al intentar buildear el Coordinador - y ese sí que debería tener un `main`. El error es, literalmente, que [el compilador no encuentra la función `main` del programa](https://stackoverflow.com/a/15905269/641451). En esa pregunta de StackOverflow, el problema era que estaba mal la sintaxis del comando `gcc`, y entonces lo que esperaban que fuera un archivo de entrada (el `runexp.o`) terminaba siendo interpretado como el archivo de salida, porque antes tenía el `-o`. No es este el caso de ustedes, pero el problema sí es que no están incluyendo los archivos en la compilación.

Si mirás tu comando, tenés `gcc -L /una/ruta -L /otra/ruta -pthread -o Coordinador -lcommons-propias -lcommons`. Es decir (en orden), compilador, dónde buscar bibliotecas, dónde más buscar bibliotecas, usar pthreads, que el archivo generado se llame Coordinador, usar las commons propias, usar las commons. ¡Nunca dicen qué archivos tomar como input para la compilación!

Si mirás el `Makefile` (en [la línea 36 de ahora](https://github.com/sisoputnfrba/tp-2018-1c-Solitario-Windows-95/blob/0a6baa38fcda3eaa0662e20f56192acc3b9d8598/Coordinador/Debug/makefile#L36)), lo que intenta compilar es lo que está en las variables `OBJS` y `USER_OBJS`. Y `OBJS` suele cargarse en el [`subdir.mk`](https://github.com/sisoputnfrba/ejemplo-orden-superior/blob/859dd156a9da7385fb37ec1a2866cbfd6ae15136/Debug/subdir.mk#L10-L12).

¿Puede que les haya faltado commitear esos archivos? Parece que [en algún momento los supieron tener](https://github.com/sisoputnfrba/tp-2018-1c-Solitario-Windows-95/commit/b2affa4005db39c8ea01622814449fc0512cf654#diff-ba8abbf5c93f23e87ecc9d19ed554635R10), pero después los borraron, y ahora que volvieron a agregar los `Makefile`s les faltó esos archivos.

**Comment by lusalmeron** [comment]
Me olvidé de avisar! Era lo de los makefiles y subdir.
Gracias! Cierro issue.
