### ISSUE TITLE
Log de Tabla (Instancia)

### ISSUE THREAD

**Issue by pablomonti** [sisoputnfrba/foro#1211]
Buenas gente,
Una consulta respecto a como se muestra el log de la tabla, yo actualmente lo estoy mostrando ej:

(E = Entrada)
E0 -- -----E1------- E2----- E3 ---------E4
FF8--GodOfWar--TLOU--FinalFantasyTactics-- .....
(Igualmente lo mostraría mas organizado que este ejemplo, quizas con un valor por renglon)
Es necesario mostrarlo dividido por entrada como muestra el pdf de pruebas o así estaría bien?

![image](https://user-images.githubusercontent.com/33211488/43361020-e64d2aee-929a-11e8-8d9f-18ac6c357f60.png)

**Comment by LeaTex** [comment]
@pablomonti te hago una consulta más básica: ¿en qué parte del anunciado habla de un log de tabla?

**Comment by pablomonti** [comment]
Nos presentamos la vez pasada, y un ayudante nos dijo que logearamos la tabla para seguir mejor los reemplazos..

**Comment by LeaTex** [comment]
Puff... ¿y van a loguarla cada vez que se hace un reemplazo?
Me parece un poco mucho, pero si quieren hacerlo y ya tienen todo lo demás andando.

La idea seguramente es que puedan ver cómo va cambiando, tiene que ser informativo y entendible. Pero háganlo lo más simple posible.
Nuestra instancia tenía "interfaz gráfica" que mostraba toda la info y hasta permitía ejecutar acciones a demanda (nos servía para las pruebas). Mostrábamos la tabla en pantalla, y se veía como una tabla, o sea, separada en columnas y con los espacios ajustados.
Eso puede demandarles demasiado tiempo, solo para que se vea "linda".

Te recomendaría que lo hagan tipo listado: nro entrada) clave: valor

Algo así:
1) pepe: el valor de la primer entrada
2) tito: el valor de otra entrada
3) juancho: el valor de la primera parte
4) juancho: de una entrada que no es atómica
5)
6)
7) lolo: una entrada perdida por ahi´
8)

5, 6 y 8 sería entradas vacías. 1, 2 y 7 entradas de claves con valores atómicos. 3 y 4 entradas de una clave con valor no atómico.

El punto es que puedan hacerle seguimiento a los reemplazos, no importa tanto cómo la muestren, pero tiene que ser claro.

O sea si lo querés mostrar tipo tabla, queda más lindo (considerando la que la línea de comandos tiene solo 80 caracteres de ancho). Pero se pueden complicar más.
Si lo hacen tipo listado sale de una.

**Comment by tferraro** [comment]
Holis👋🏻

Guarda que la idea era que loggeen algo, la tabla es el best-case-scenario,
como dice LeaMM. Pero tampoco loggeaban nada sobre el reemplazo.

Lo que si dice el enunciado, que los logs tienen que ser lo más claros
posibles.

Nada, eso, el formato es algo propio, mientras que sea entendible🙂

**Comment by pablomonti** [comment]
Gracias Muchachos!! , cierro
Saludos
