### ISSUE TITLE
Consultas ultima semana

### ISSUE THREAD

**Issue by juanicarramal** [sisoputnfrba/foro#1212]
Hola, quería saber si esta semana va a haber algún ayudante en alguna de las sedes que pueda dar soporte. Si van a estar abiertos los laboratorios y con alguien que nos pueda ayudar. 
De ser así, quisiera saber en que horarios podemos acudir y donde. 
Desde ya, muchas gracias. Saludos.

**Comment by mgarciaisaia** [comment]
¡Alo!

El labo de Medrano debería estar abierto durante la semana. Suele estarlo,
al menos (no se bien en qué horarios, a eso de las 19hs se que suele estar).

Ayudantes no tengo garantías, pero capaz alguno pasa, ni idea.
