### ISSUE TITLE
Duda SJF-CD

### ISSUE THREAD

**Issue by aleperaltabazas** [sisoputnfrba/foro#1213]
Buenas! Tengo una pequeña duda respecto a la prueba de SJF-CD. El enunciado dice 

[...] 
- La estimación de ESI_Spoilers debería ser 2,5 y la de ESI_Westworld 4,5.
- Debería ejecutar ESI_Spoilers y bloquearse, ESI_Westworld y desbloquear
"principal1". ESI_Fargo debería desalojarlo y bloquearse. Luego continúa
ESI_Westworld y desbloquea "principal2". ESI_Westworld continúa hasta
bloquearse. ESI_Fargo debería poder finalizar.
- Pausar, desbloquear "spoiler3", "principal4" y reanudar
- La estimación de ESI_Spoilers debería ser 3,75 y la de ESI_Westworld 4,75.

[...] 

Sin embargo, no veo por qué la estimación de ESI_Westworld debería ser de 4,75. ESI_Spoilers ejecuta una ráfaga de 5 y se bloquea, así que el 3,75 me da bien. Pero luego, ESI_Westworld ejecuta una ráfaga de 2, desbloqueando principal1 y con ello el ESI_Fargo. La estimación del ESI_Fargo pasa a ser 2 y el remanente de ESI_Westworld de 2,5, así que elijo al ESI_Fargo. Este ejecuta, se bloquea, sigue ESI_Westworld. 
Acá entra la duda, porque para que la estimación de 4,75, tendría que considerar que la ráfaga real es de 5 ((4,5 + 5)/2 = 4,75), pero la ráfaga real no sería de 3? Inicialmente hizo 2 y fue desalojado, luego hizo 3 y se bloqueó. Considero que si un ESI no se bloquea, su ráfaga sigue normal?

Saludos!

EDIT: lo planteé de esa manera y me dio todo bien, pero no entiendo conceptualmente por qué no se reinicia la ráfaga.

**Comment by afilgueira** [comment]
Hola, la ráfaga de CPU es todo el tiempo que pasa en ejecución, hasta que va a E/S (o termina). En un RR, tu quantum te sirve para partir una ráfaga en varias ejecuciones de tiempo fijo (y no en varias ráfagas). Acá pasa algo similar. El error viene en a qué estás llamando ráfaga.

Saludos!

**Comment by aleperaltabazas** [comment]
Ah, entiendo, genial!

Cierro, muchas gracias!
