### ISSUE TITLE
Error al instalar las Guest Additions

### ISSUE THREAD

**Issue by agomel** [sisoputnfrba/foro#1215]
Buenas!
Estoy teniendo un problema al momento de instalar las guest additions en la vm, les dejo el mensaje de error que me esta devolviendo.

![image](https://user-images.githubusercontent.com/17252074/44620358-39d39480-a869-11e8-8076-02bc92a4850d.png)

Saludos.

**Comment by mgarciaisaia** [comment]
[Por acá](https://askubuntu.com/a/597250/329506) hay un error _bastante igualito_, y dice que se solucionó reinstalando el kernel 🤷‍♂️ 

Así que abrite una Terminal (`CTRL + SHIFT + T` en la VM), y corré ese comando que dice en el post:

```
sudo apt-get install --reinstall linux-image-$(uname -r)
```

Después de eso pegale una reseteada al Linux, y fijate qué onda.

_Dice por ahí_ que el problema fue por actualizar la versión de VirtualBox. ¿Habrás actualizado VirtualBox (el programa) después de crear la VM?

Contanos qué onda :)

**Comment by agomel** [comment]
Mmmmm, creo que no actualize virtual box.

Corri ese comando y me tiro:

![image](https://user-images.githubusercontent.com/17252074/44696961-19b1fa00-aa50-11e8-9b30-42292def99e9.png)

No funciono :(

**Comment by mgarciaisaia** [comment]
Qué turbio está todo, che. ¿Se te ocurre alguna cosa medio rara que te haya pasado con la vm?

Probaría hacer `sudo apt-get update` para actualizar los índices de paquetes, y después insistir con el comando de reinstall anterior, a ver si cambia algo.

Si no, pasame lo que dice `uname -a` a ver qué onda.

Lo que sí, tratá de copiar y pegar el texto en vez de subir una captura, porque se pone mil incómodo de leer, y complica buscar después.

¡Un abrazo!

**Comment by tferraro** [comment]
Holis 👋 

Creeria haber leido lo mismo que mati por gogle y probá reiniciando la VM, como "restart" dentro del lunbuntu a ver que onda. Esto tiene mucha pinta que lo que actualizaste no fue virtualbox, sino el ubuntu (y si apagaste la vm no la "apagaste" sino que la guardaste). Fijate si sirve!

**Comment by agomel** [comment]
Buenas, hice sudo apt-get update y sigue sin andar el comando de arriba.
Te copio lo que devuelve:
utnso@ubuntu-server:~$ sudo apt-get install --reinstall linux-image-S(uname -r)
bash: syntax error near unexpected token `('
utnso@ubuntu-server:~$ sudo apt-get install --reinstall linux-image-$(uname -r)
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
Los paquetes indicados a continuación se instalaron de forma automática y ya no son necesarios.
  containerd runc
Utilice «sudo apt autoremove» para eliminarlos.
0 actualizados, 0 nuevos se instalarán, 1 reinstalados, 0 para eliminar y 29 no actualizados.
1 no instalados del todo o eliminados.
Se utilizarán 0 B de espacio de disco adicional después de esta operación.
E: Internal Error, No file name for linux-image-4.4.0-116-generic:i386

Tambien te paso el de uname -a :
utnso@ubuntu-server:~$ uname -a
Linux ubuntu-server 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:22:43 UTC 2018 i686 i686 i686 GNU/Linux

**Comment by agomel** [comment]
Pude!!!!

Al final lo que termine haciendo es volver a descargar todo, y volver a crear la vm.

Gracias!!!

**Comment by tferraro** [comment]
No fue lo ideal, pero que copado que al menos lo hayas solucionado y puedas
seguir😊

**Comment by agomel** [comment]
Si, me conformo con eso ya fue jaja
