### ISSUE TITLE
No obtengo el "hola" con recv luego de conectar correctamente al socket - WorkshopTp0

### ISSUE THREAD

**Issue by chamenwais** [sisoputnfrba/foro#1216]
Buen día.

Estoy teniendo un problema en la recepción del mensaje de bienvenida en ```wait_hello``` del tp0. Precisamente ```recv``` no almacena la información en mi buffer, 

El problema ocurre luego de conectar sin inconvenientes a la url y puerto especificados en el enunciado.
Cuando digo sin inconvenientes, me refiero a que ```getaddrinfo``` cargo mi varible ```server_info``` correctamente como se aprecia en la siguiente imágen:

![serverinfosocket](https://user-images.githubusercontent.com/11778309/44660305-9788ed80-a9dd-11e8-9b25-0bf3bbd70c21.png)

Luego ```socket``` me devuelve el valor ```4``` y ```connect``` retorna ```0```.

Mi código de ```wait_hello``` es el siguiente:
```
 void wait_hello(int socket) {
	char * hola = "hola";

	int holaBinaryLenght=16;//Probé tambien con size_t holaBinaryLengh = 16;
	char * buffer = malloc(holaBinaryLenght);

	int result_recv = recv(socket, &buffer, holaBinaryLenght, NULL);// Probé también con MSG_WAITALL como flag

	validarRetornoMensaje(result_recv);
	printf("Nos devolvio %s", buffer);//<--AQUÍ PINCHA
	validarSiEsHolaLoRecibido(buffer);

	free(buffer);
}

void validarRetornoMensaje(int retorno) {
	if (retorno < 0) {
		log_error(logger, "No se se obtuvo ningun mensaje");
	}
}
```

```recv``` me devolvió  ```16``` que son los bytes que indica el enunciado que debo recibir.

Sin embargo el ```buffer```, el cual en mi criterio tiene la memoria bien reservada, es inmanejable.
Si me paro sobre el en debug veo que, ni siquiera, me lo puede mostrar:
```
Name : buffer
	Details:0x54535953 <error: Cannot access memory at address 0x54535953>
	Default:0x54535953 <error: Cannot access memory at address 0x54535953>
	Decimal:1414748499
	Hex:0x54535953
	Binary:1010100010100110101100101010011
	Octal:012424654523
```

Y cuando se lo envío a ```printf```, el debug se va a un hilo extraño y me devuelve:
```
Can't find a source file at "/build/glibc-mUak1Y/glibc-2.23/stdio-common/vfprintf.c"
```
Algo similar ocurre si invierto el orden y antes del ```printf``` trato de preguntar si es igual a "hola" con las commons de ```string```:
```
void validarSiEsHolaLoRecibido(char * recibido) {
	if (!string_equals_ignore_case(recibido, "hola")) {//Aqui el debug se va a un hilo extraño
		log_info(logger, "No recibio el hola");
	}
}
```
```
Can't find a source file at "/build/glibc-mUak1Y/glibc-2.23/string/../string/strcasecmp.c" 
```

Lo que pude leer en otras issues es que puede ser que la memoria no está bien reservada para el ```buffer``` de ```recv```, pero entiendo que no es el caso, ya que además de las dos maneras de inicializar ```holaBinaryLenght``` que mostré, también usé ```strlen(hola) + 1``` lo que devuelve cinco (que estaría mal según el enunciado), o  ```strlen(hola)``` y el comportamiento del ```buffer``` fue el mismo.

Me suena a que puede ser que no deba recibir un ```string```, sino una secuencia de bytes, pero en ese caso no sabría como validar si es "hola" el mensaje, ni hacer otros manejos de ```string``` sobre dichos bytes.

Cabe aclarar que mi version workshop del Tp0 compila sin errores y que Valgrind me dice que está todo en orden:
 ```
HEAP SUMMARY:
==5728==     in use at exit: 0 bytes in 0 blocks
==5728==   total heap usage: 80 allocs, 80 frees, 94,360 bytes allocated
==5728== 
==5728== All heap blocks were freed -- no leaks are possible
```

**Comment by tferraro** [comment]
Buenas!

Terrible reporte!

Mirando lo que nos contás, me hace ruido el "16" que dice el enunciado, si mal no recuerdo, tenemos en el mismo tp0.c un `char * hola = "SYSTEM UTNSO 0.1";` que va a tener los caracteres que necesitas (no va a devolver 5, ahí le estás pifiando con el literal). Respecto a lo que rompe, me suena que es que justamente te falta el `/0` y no debe estar encontrando el fin y termina explotando.

Probá recibiendo usando `strlen` sobre el "hola" posta y enforzá el `/0`mediante o poniendolo en el ultimo byte oooo podés usar `calloc()` 😄 

Contanos que onda así lo vamos encarando 😉

**Comment by mgarciaisaia** [comment]
:wave:

Si levantamos apuestas, yo digo que el problema está en `int result_recv = recv(socket, &buffer, holaBinaryLenght, NULL);`. Más específicamente, en `&buffer`. Más más específicamente, en el `&`.

Tu `buffer` es un `char *` que apunta a un bloque de memoria que reservaste con `malloc`. Es decir, en el stack hay una variable de 4 bytes que tiene la dirección de memoria en que comienza un bloque de _varios_ bytes en el heap que reservaste con `malloc`.

`recv` te pide que le pases un `void *` con la dirección del primer byte en el que tiene que escribir los bytes que recibe. Vos querés que escriba esos bytes en el bloque que reservaste en el heap. Entonces tendrías que pasarle un puntero a ese bloque. El problema es que le estás pasando `&buffer` - la dirección de memoria del primer byte _del puntero a tu bloque_. ¿Se nota que hay un nivel extra de indirección?

Por eso no podés inspeccionar `buffer` después. Eclipse sabe que es un puntero, entonces intenta mostrarte el contenido apuntado. _Antes_ apuntaba a un bloque "válido" de memoria (el que te devolvió `malloc`). Pero ahora `recv` te puso los bytes que llegaron por socket en donde iban los bytes del puntero, y por eso tu `buffer` apunta a memoria inválida.

Fijate que `0x54535953` (el puntero cuyo contenido eclipse no te está sabiendo mostrar) son los bytes `0x54`, `0x53`, `0x59` y `0x53`. Hubiera esperado que esos caracteres fueran "imprimibles" (letras ASCII, digamos), pero parece que no. ¿Alguna idea de por qué el TP0 estará mandando esos valores?

**Comment by tferraro** [comment]
☝️ muy buen catch ese

**Comment by mgarciaisaia** [comment]
> Ahora si le doy bola a @mgarciaisaia y hago que mi `buffer` sea de tipo `void *`, la cosa cambia y ese puntero es de una dirección de memoria como `0x54535953`.

Ojo, que no cambia _tanto_ eso. Y, más importante, no era ese el cambio que te estaba sugiriendo - perdón si no fui tan explícito con eso.

------

El cambio _importante_ era el del `&`. Lo importante es que `recv` espera un puntero, y va a escribir en los bytes apuntados por eso.

Vos querés que `recv` escriba en los bytes que `malloc`easte, entonces le tenés que pasar un puntero a esos bytes. Tu puntero a esos bytes es `buffer`.

`&buffer` es un puntero a `buffer`. Si le pasás `&buffer`, `recv` va a escribir los bytes que reciba en `buffer` - en la variable, no en _lo apuntado por_ `buffer`. Va a modificar _la dirección_, no el contenido. ¿Me explico?

------

Cualquier tipo de datos de C que termine en `*` es un _puntero a_. Es decir, su tipo de datos ""principal"" es _puntero_. Todo lo que va _antes_ del `*` dice puntero _a qué_.

Saber de qué tipo es lo que está apuntado sirve para hacer aritmética de punteros. Por ejemplo, podés declarar una variable `int *numeros;`, y entonces el compilador va a saber resolverte que cuando digas `numeros + 1` te querés referir al _segundo elemento_ de números. Es decir, no el `int` apuntado por `numeros`, si no el que está _una posición a la derecha_ (el que está en la dirección `numeros` + `sizeof(int)`).

Pero hay mucha gente que dice que hacer aritmética de punteros _está muy mal_, así que si no entendiste del todo qué quise poner acá, no importa. Quedate con que al compilador le sirve que le digas de qué tipo son las cosas que apunta un puntero.

Y, buen, cuando no sabés o no te importa el tipo de lo que estás apuntando, ahí entra `void *`, que no es un "puntero a nada", si no un puntero _a bytes_. Si te sirve, leelo como un puntero _a nada EN PARTICULAR_, qué se yo.

La cuestión es que el `void *` apunta a bytes, entonces asume que _el siguiente_ es _un byte a la derecha_. Nada relevante porque no nos interesa la aritmética de punteros.

**Comment by chamenwais** [comment]
Gracias @tferraro y @mgarciaisaia . 
Terminé entendiendo que ```recv``` no necesita una dirección de memoria, si la referencia del primer byte del espacio que reservé, para escribir, y que eso se logra simplemente pasando el valor de la variable (en  mi caso es ```buffer```).
Anduvo esa parte, cierro la issue.

**Comment by mgarciaisaia** [comment]
Bien ahí, che :)

Igual, ojo de nuevo: `recv` **sí** necesita una dirección de memoria. El tema es que `buffer` _guarda_ una dirección de memoria, y entonces es esa la que tenés que pasarle a `recv`. `&buffer` _también_ es una dirección de memoria, pero, buen - _otra_. En particular, `buffer` apunta al cacho'e memoria que reservaste con `malloc`, mientras que `&buffer` apunta a... ¡`buffer`!

**Comment by tferraro** [comment]
@chamenwais 
> Bien, me mareó un poco lo de "recibir el hola" por eso borré el contenido "SYSTEM UTNSO 0.1".
Creo que hola es un nombre poco feliz para la variable y hubiese usado mensaje_de_bienvenida o algo por el estilo, pero bueno eso es mera opinión.

Concuerdo completamente con esto, te animás a tirarnos un Pull Request con el cambio de nombre en el repo del tp0 😉 ?

**Comment by chamenwais** [comment]
@tferraro , intenté hacer un "pull request" desde un branch ```mejora-expr-wait_hello``` que creé para mejorar la expresividad del método wait_hello en donde hice un cambio simple del nombre de la variable "hola" y readaptación de los comentarios en donde se mencionaba. Lo hice siguiendo la documentación de github https://services.github.com/on-demand/github-cli/open-pull-request-github.

Pero me rechazó como era de esperar:
```
$ git add tp0.c
$ git commit --author="Francisco Romero <francisco.a.romero.5@gmail.com>"
[mejora-expr-wait_hello dc41663] Se cambia el nombre de la variable hola por mensaje_de_bienvenida para hacerla mas expresiva
 Author: Francisco Romero <francisco.a.romero.5@gmail.com>
 1 file changed, 5 insertions(+), 5 deletions(-)
$ git push -u origin mejora-expr-wait_hello
Username for 'https://github.com': chamenwais
Password for 'https://chamenwais@github.com': 
remote: Permission to sisoputnfrba/tp0.git denied to chamenwais.
fatal: unable to access 'https://github.com/sisoputnfrba/tp0.git/': The requested URL returned error: 403
```
¿Tenés idea si le pifié a algo o si ustedes tienen que darme permisos primero?

**Comment by tferraro** [comment]
Buuu, eso es un claro "No tenés permisos para pushear". Lógico, porque sos un "alumno" no tenés permisos de escritura. Al menos se intentó 🤷‍♂️ . @mgarciaisaia podrías echar luz sobre esto a ver si hay alguna forma sin romper todo o directamente lo subo yo con referencia a este issue y @chamenwais ?

**Comment by chamenwais** [comment]
Es entendible que un alumno no tenga acceso a comitear al repo de la materia.
Para que no sea tan complicado les dejo el cambio que iba a hacer (- la linea de ustedes, + la mía), si ustedes tienen el tp0 "up-to-date", hechen mano ustedes si así lo desean:
```
void  wait_hello(int socket) {
-  char * hola = "SYSTEM UTNSO 0.1";
+  char * mensaje_de_bienvenida = "SYSTEM UTNSO 0.1";
 
   /*
     5.  Ya conectados al servidor, vamos a hacer un handshake!
         Para esto, vamos a, primero recibir un mensaje del
         servidor y luego mandar nosotros un mensaje.
-        Deberìamos recibir lo mismo que está contenido en la
-        variable "hola". Entonces, vamos por partes:
+        Deberíamos recibir, a modo de "hola", lo mismo que lo que está contenido en la
+        variable 'mensaje_de_bienvenida'. Entonces, vamos por partes:
         5.1.  Reservemos memoria para un buffer para recibir el mensaje.
   */
   // char * buffer = malloc(/*5.1*/);
@@ -73,8 +73,8 @@
   */
   // int result_recv = recv(/*5.2*/);
   /*
-        5.3.  Chequiemos errores al recibir! (y logiemos, por supuesto)
-        5.4.  Comparemos lo recibido con "hola".
+        5.3.  Chequeemos errores al recibir! (y logeemos, por supuesto)
+        5.4.  Comparemos lo recibido con el contenido de la variable 'mensaje_de_bienvenida'.
               Pueden usar las funciones de las commons para comparar!
         No se olviden de loggear y devolver la memoria que pedimos!
         (si, también si falló algo, tenemos que devolverla, atenti.)
```

**Comment by mgarciaisaia** [comment]
Durmió la gente de @github ahí, eh.

Sí, si estás en tu propio proyecto, ese tuto aplica bárbaro. Pero acá las commons "no son tu proyecto".

En este caso, tenés que [hacer un fork](https://help.github.com/articles/fork-a-repo/#propose-changes-to-someone-elses-project) de las commons, y [agregarlo como un segundo remote](https://help.github.com/articles/fork-a-repo/#step-3-configure-git-to-sync-your-fork-with-the-original-spoon-knife-repository). No exactamente igual que en ese tuto, igual.

Un fork es una copia del repo, pero tuya. En tu fork podés hacer _lo que quieras_. Por ejemplo, pushear un branch. Y, desde tu fork, podés mandar un PR al repo "upstream" (al original, digamos).

Un remote es un repositorio remoto con el que "conectás" tu repo local. Lo de conectar es bastante relativo, pero buen. Es un repo al que podés hacer push/pull, ponele. Cuando clonás un repo con `git clone`, git te agrega automáticamente a ese repo como un remote llamado `origin`. Por eso `git push origin master`, ponele.

Lo que tendrías que hacer (con el segundo link) es agregar tu fork como un remote a tu repo (yo suelo llamarlo `fork`). Algo como `git remote add fork https://github.com/VOS/so-commons-library`, seguramente. Y ahí sí vas a poder hacer `git push fork mi-branch`, y una vez que tu branch está en tu fork podés crear el PR.

Y una vez que hiciste eso ya sos cap@ de Github y podés ponerte a colaborar en el proyecto open-source que prefieras. Te puedo vender algunos, pero sería poco ético :P

¡Un abrazo!
