### ISSUE TITLE
Duda al crear una vm 64bits

### ISSUE THREAD

**Issue by ngrosso** [sisoputnfrba/foro#1220]
Hola chicos, consulta rapida, me parecio escuchar de uno de los ayudantes que crear la vm 64bits con la imagen de la catedra trae problemas, esto es asi? borro y creo de vuelta una vm con el iso de la catedra en 32bits?
Desde ya muchisimas gracias!

**Comment by mgarciaisaia** [comment]
El disco que les damos tiene instalado un [L]Ubuntu de 32 bits. Entonces, crear la máquina de 64 bits no va a hacer que tu Linux sea de 64 bits - porque el software es de 32 bits, entonces sólo va a usar ese set de instrucciones.

Si fueras a instalar vos el Linux y todo el stack, nada, vas a tener que tener cuidado a la hora de enviar datos por la red, asegurándote de tener un protocolo y respetarlo sin importar si la otra máquina con la que hablás también es de 64 bits o si es de 32.

Como consejo, no te sumes más problemas de los que ya tienen - usá la VM que les damos.

**Comment by ngrosso** [comment]
a modo de entender bien esto, entonces, que el virtualbox me diga 64bits es un problema? aclaro que siempre estoy usando la VM que me dieron, no sabia lo de los 64bits cuando lo configure la semana pasada y en la charla dijeron eso. Por lo tanto la recomendacion es borrarlas y volver a crearlas poniendo 32bits?
![image](https://user-images.githubusercontent.com/11824720/44936813-909b0b80-ad4c-11e8-8eec-8d8966c81204.png)

**Comment by mgarciaisaia** [comment]
No se si "un problema". Probablemente sea compatible, y no tengas inconvenientes. Se puede correr sistemas operativos de 32 bits en máquinas de 64 bits (cuando aparecieron los primeros procesadores comerciales de 64 bits, casi tod@s lo hacíamos - un Windows XP en un Athlon 64, ponele).

Pero seguramente arriba de ese `Ubuntu (64-bit)` tengas un `Ubuntu (32-bit)` - y ese estamos segurísimos de que anda.

Si te está funcionando, dejá las cosas como están. Deberían andar sin problema. Si algo falla, sería más un bug de VirtualBox que otra cosa. Así que, nada, no te hagas drama. Si eventualmente notás que la máquina falla o algo, lo revemos.

**Comment by ngrosso** [comment]
Muchisimas gracias!
