### ISSUE TITLE
Ayuda para comprender informe de Valgrind

### ISSUE THREAD

**Issue by chamenwais** [sisoputnfrba/foro#1221]
Hola.

Me hace un poco de ruido el informe de Valgrind, en este caso del workshop TP0 pero creo que me va a ayudar para cualquier otro proyecto en C que utilice bibliotecas ajenas.

En mi sourcefile tp0.c tengo 8 ```malloc``` y 11 ```free``` (3 más por flujos de error en los cuales libero antes de terminar el programa).

Pero si lo chequeo con Valgrind, en la sección HEAP veo muchísimos más ```malloc``` (es entendible estos que sean los de la biblioteca) y una cantidad de ```free``` menor a esa.

```
HEAP SUMMARY:
in use at exit: 64,393 bytes in 186 blocks
total heap usage: **493 allocs, 307 frees**, 183,823 bytes allocated
```

Y que tengo *memory leak*:
```
LEAK SUMMARY:
**definitely lost: 28 bytes in 3 blocks**
indirectly lost: 0 bytes in 0 blocks
possibly lost: 0 bytes in 0 blocks
still reachable: 64,365 bytes in 183 blocks
suppressed: 0 bytes in 0 blocks
```
- ¿Es correcto que hayan más ```malloc``` que ```free```?
- El workshop TP0 solo usa las commons. ¿Hay alguna chance de que esa memoria no la pierda yo, si no que lo hagan las commons?

Gracias.

**Comment by tferraro** [comment]
Buenas!

No deberia, lo ideal siempre es cant(malloc) == cant(free)

Respecto a leaks en las commons, puedo estar bastante seguro (digamos 90%),
que no sean las commons y sea el codigo, y lo que este pasando sea algún
error conceptual. Yo concentraría la energia en los definitely lost.

Tom

Yapa: Un buen tip es correr el programa sin valgrind, porque como valgrind
te habdlea algunas excepciones, puede haber un error que no estes viendo.

**Comment by gastoncastineira** [comment]
Buenas!
Te respondo en orden.

- No es correcto que haya más malloc's que free's. La regla general es que por cada malloc que hagas, también hagas en algún lugar un free.

- Ante ese tipo de dudas de dónde estás perdiendo la memoria, podés correr valgrind con el flag "--leak-check=full" (sin comillas) y te va a decir en qué línea de qué función estás perdiendo cada uno de esos tres bloques. Este reporte se lee de abajo para arriba (tipo la última función que te va a mostrar es el main y la primera es en dónde se genera el leak). Si no me expliqué bien, mandá por acá ese mismo informe y te ayudo a interpretarlo. Y de paso, si resultan ser las commons ya nos queda anotado para parcharlas :)

**Comment by chamenwais** [comment]
@gastoncastineira , @tferraro entiendo que la regla sería >cant(malloc) == cant(free)
Pero de los *493 allocs* que tiene el TP0, yo solo hice ocho y tengo sus respectivos free. Es código de las bibliotecas que usa este proyecto que nos pasaron, y yo no lo puedo corregir y/o controlar.

Con respecto a esta issue, me estaba comiendo los ```free``` para los ```readline```.
Gracias.
