### ISSUE TITLE
Problema al conectarse a un socket

### ISSUE THREAD

**Issue by brendaboryszanski** [sisoputnfrba/foro#1222]
En el video https://www.youtube.com/watch?v=IWyGFJFVWB8&feature=youtu.be
hay un problema al conectarse..

La solucion es ponerle  sin_size = sizeof(struct sockaddr_in);
       antes del accept.

**Comment by varas-c** [comment]
Hola! Cómo estás?

Podrías decirnos en que línea y/o minuto del video está el error que
mencionas?

Por otra parte, por qué la línea que propones es solución del problema?

**Comment by tferraro** [comment]
Buenas! @brendaboryszanski podés darnos más info sobre esto que comentaba Chris? Te referís a lo que en el video ponen como `tamañoDireccion`?

**Comment by tferraro** [comment]
@brendaboryszanski up up up! No nos olvides! Ayudanos a mejorar 😄

**Comment by brendaboryszanski** [comment]
Hola! disculpen por la demora.
Video: https://www.youtube.com/watch?v=IWyGFJFVWB8&feature=youtu.be
Minuto: 2:50
Linea de eclipse: 30 (se puede ver que se hace un accept)
Al correrlo, puede ser que tengan suerte y salga bien, pero eso es porque esta tomando un valor positivo como tamaño direccion. Puede ser que la siguiente vez que lo corran tome al azar uno negativo y les salga "recibi una conexion en -1"
Solucion: Reemplazar la linea 29 por: 
	int tamanioDireccion = sizeof(struct sockaddr_in);

Saludos!

**Comment by tferraro** [comment]
@brendaboryszanski Genial!! Gracias!

Ahí abri un ticket interno para seguirlo bien de cerca y poderlo arreglar. Cierro el issue así no hace falta que le sigas dando bola.

Posta, _gracias_ por el feedback, nos re ayuda a mejorar las herramientas, guias, videos e incluso la forma en la que interactuamos en el cuatri 🙂 

Tom
