### ISSUE TITLE
Build not configured correctly

### ISSUE THREAD

**Issue by fakukpg** [sisoputnfrba/foro#1223]
Hola gente, 

Hace rato estoy tratando de compilar lo que tenemos del tp en mi máquina y recibo el error "Build not configured correctly" en la consola.
El eclipse lo tengo instalado desde el cuatri pasado, donde siempre funcionó bien y pude compilar, pero desde que arranqué este TP no logro hacerlo.

¿Alguno tiene idea de qué podría estar pasando?

Gracias,

**Comment by mgarciaisaia** [comment]
¡Más info, más info!

¿Es todo lo que te dice? ¿En dónde te lo muestra? ¿Viste el video de [reportar errores de Eclipse](https://faq.utnso.com/errores-eclipse)? ¿Por qué no aplica?

**Comment by fakukpg** [comment]
Ví el video que pasaste en tu comentario y me ayudó a ver un poco mejor la consola de eclipse (odio eclipse), te adjunto el log de lo que estoy recibiendo al intentar compilar. 
Veo que solo intenta compilar FM9 y CPU pero nunca el resto y que tambien entiende, por ejemplo, que el main de SAFA es el mismo que el de FM9 cuando están en carpetas distintas.

[Log consola eclipse.txt](https://github.com/sisoputnfrba/foro/files/2373015/Log.consola.eclipse.txt)

**Comment by tferraro** [comment]
Holis👋🏻

Del log que mostraste, arrancaria por esto:

cliente_dummy.c:58: multiple definition of `main'

La pregunta que se me ocurre es, tenes 2 definiciones de main? Cual fue la
idea de fondo    con la cual llegaron a eso?🙂

Contanos asi lo seguimos viendo😉

Tom

**Comment by fakukpg** [comment]
Buenas, ahí hice lo que me dijeron de crear distintos proyectos y funciona todo de 10. La había manqueado ahi.

Gracias!
