### ISSUE TITLE
Destruír estructura de un string creado con string.h de las commons

### ISSUE THREAD

**Issue by chamenwais** [sisoputnfrba/foro#1224]
Buenas.

No sé si lo que estoy teniendo es realmente un error, pero me gustaría saber si lo es y cómo se arregla en ese hipotético caso.

Al crear una cadena de caracteres vacía con ```string_new()``` de  ```commons/string.h``` y de ir agregándole información con ```string_append(...)```, estoy teniendo memory leak.

Sé que ese memory leak no va a escalar, ya que el uso de ```string_append``` en mi contexto es limitado. Pero me molesta un poco el hecho de que ```valgrind``` me diga que estoy perdiendo tantos bytes como caracteres le agregue a dicha variable.

- ¿Conocen alguna forma de solucionar ese problema?

- Si la solución es un ```free```, ¿debo yo privarme de armar y usar funciones que devuelvan cadenas de caracteres creadas con ```string_new```? 
(Digo privarme, porque si por ejemplo uso una función que me devuelva un char *, como argumento de por ejemplo ```log_info```, pierdo la referencia de ese char *:
Ej: ```log_info(logger, funcion_que_crea_y_devuelve_un_string());``` => ¡Luego de esta sentencia ya no tengo forma de conocer a lo que devolvió la función  como para intentar hacer algún free!)

Gracias.

**Comment by mgarciaisaia** [comment]
¡Aloha!

Las funciones de `string.h` de las commons usan todas memoria dinámica, sí, por lo que vas a tener que liberar esa memoria cuando ya no la uses.

Habría que ver el error en particular que te marca `valgrind` para ver cómo/cuándo deberías liberarla, pero sí, tenés que liberarla. En [los tests de las commons](https://github.com/sisoputnfrba/so-commons-library/blob/0944b25908c0efa9e19d31f8046028749a8812c4/tests/unit-tests/test_string.c#L42-L51) dice que con hacerle `free` al string original al que estás `append`eando alcanza - no tenés que preocuparte por strings intermedios que se generen, digamos.

Entonces, no, no tenés que privarte de usar esas funciones - nomás tenés que usarlas _un poquito_ distinto a lo que te gustaría.

Si venís de un lenguaje con manejo automático de memoria dinámica (lenguajes de objetos con garbage-collection son los más fáciles de pensar), esa línea estaría genial. Pero acá nos tenemos que encargar nosotr@s de la memoria, así que vas a necesitar guardarte la referencia al resultado de `funcion_que_crea_y_devuelve_un_string()` para poder hacerle `free` después de ejecutar `log_info`.

Digamos, ponele que te quedaría así:

```c
char *nombre_descriptivo_para_tu_variable = funcion_que_crea_y_devuelve_un_string();
log_info(logger, nombre_descriptivo_para_tu_variable);
free(nombre_descriptivo_para_tu_variable);
```

Como siempre, salcondimentar a gusto :)

¡Éxitos!

**Comment by chamenwais** [comment]
Si, es masomenos el caso hipotético del que estábamos hablando.

Me armo un ```char *``` con una cadena de 50 caracteres, y la uso al *loggear*. Pero después pierdo la referencia y me genera un *memory leak*.

```
log_info(logger, mensaje_informativo_previa_conexion_con(const_name_fm9),
			ip_fm9, puerto_fm9);
```

```
50 bytes in 1 blocks are definitely lost in loss record 1 of 1
   at 0x402E2CC: realloc (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
   by 0x4053D7B: string_append (in /usr/lib/libcommons.so)
   by 0x80493DF: mensaje_informativo_previa_conexion_con (Utilidades.c:137)
```

Lo voy a solucionar como me sugeriste.

Gracias.
