### ISSUE TITLE
Problema con VM end kernel panic: not sync: Vfs:unable to mount root fs on unkwon-block(0,0)

### ISSUE THREAD

**Issue by mackhood** [sisoputnfrba/foro#1225]
Buen dia, una consulta alguno sabria como resolver este problema de la vm hace un par de dias estoy buscando una solucion en google pero no encuentro nada que me funcione.
El problema es  cada vez que inicio la vm me tira el siguiente error  :  end kernel panic: not sync: Vfs:unable to mount root fs on unkwon-block(0,0)   no dejandome ingresar al sistema.
![image](https://user-images.githubusercontent.com/26845494/45889292-6d390e80-bd96-11e8-9546-ffa67994fbde.png)

La unica forma de acceder es a través de una version anterior en advanced options for Ubuntu .
Queria consultar si alguno le paso y tiene idea de como resolverlo?
Aclaracion: La virtualizacion ya la tengo activada.
Saludos

**Comment by tferraro** [comment]
Buenas!

Probaste lo que comentaban en #1010 ?

Sino, cualquier cosa pasate mañana por campus a la mañana y lo vemos😊

Tom

**Comment by mackhood** [comment]
Hola buenas sisi la virtualizacion ya la tengo activada.
Saludos

**Comment by tferraro** [comment]
Me refería al https://github.com/sisoputnfrba/foro/issues/1010#issuecomment-381626798

Aparte de eso, probaste reinstalando virtualbox/bajando nuevamente la VM?

**Comment by mackhood** [comment]
Ahi hice baje la version anterior de virtual box y me tiro el mismo error.

**Comment by gastoncastineira** [comment]
Buenas! Un poco tarde pero vengo a tirar mí granito de arena por si seguís en el apuro

a priori, se me ocurren tres razones por las que te está tirando ese error.

1. Como dijo Tom, se te descargó mal un comprimido de la VM. Fijate que [donde se descargan](https://www.utnso.com/recursos/maquinas-virtuales/) les dejamos un md5. Básicamente si vos lo tirás en tu archivo descomprimido, te tiene que dar igual. Si da distinto se te descargó mal una parte.
También aclaro que hay que descomprimirlo con 7zip. Winrar se suele cagar bastante es ese formato

1. Estás configurando mal la VM al momento de arrancarla (por favor no te sientas ofendido por esta, estoy abarcando todos los casos nada más). Fijate comparando como lo hace Matías en [este video](https://www.youtube.com/watch?v=DmkSXv_Xa-U&feature=youtu.be) a ver si te ayuda.
También, hay un error en las versiones 5.0 y 5.1 de VBox con el kernel de Ubuntu que usa la VM. Fijate si descargando una versión considerablemente más vieja te funciona. Supuestamente lo arreglaron en la 5.2, pero no lo probé personalmente

1.  Descartado todo lo anterior, el problema deja de ser VBox y la VM, y pasa a ser tu computadora. una lectura muy rápida por Internet del error dice que puede ser algo tan estúpido como el driver de tu mouse como algo más áspero como hardware defectuoso. ¿Tenés suficiente RAM y disco disponibles para correr la VM? De ser así, te diría que pases algún día por el soporte para que puedan revisar tu máquina, porque por acá no se va poder hacer mucho :/


Y si en este tiempo lo pudiste arreglar, por favor avisá como lo lograste para el resto que pueda tener este error (¡y porque la curiosidad me está matando!)

**Comment by tferraro** [comment]
@mackhood, esto lo vimos el sabado no? Entiendo que se ree puede cerrar😛. Si te animas, comenta que era (como puedas), sino despues lo comento yo😊.

**Comment by mackhood** [comment]
Hola si lo resolvimos el sabado, no me acuerdo bien los comandos que escribio @tferraro  en la consola, pero el problema era que se me habia bajado cierta actualizacion del sistema y un archivo llamado dpkg se habia descargado mal causando este problema.
Para resolverlo entramos al sistema a traves de una version anterior de ubuntu que estaba guardada y por la consola bajamos de nuevo este archivo.Si mal no me acuerdo al principio vimos cuales fueron las actualizaciones que hizo el sistema y despues vimos que el dpkg habia fallado y lo descargamos y actualizamos.Yo habia anotado las instrucciones en un txt pero creo que no lo guarde porque  no lo estaria encontrando.
Esto fue lo que entendi yo del sabado, creo que otra opcion valida era bajarse las vm de la pagina de nuevo.
Gracias @tferraro  por la ayuda del sabado.
Saludos

**Comment by tferraro** [comment]
Holiss 👋,
**Amplío un poco más la explicación** conceptualmente bárbara de @mackhood, haciéndola un poco más técnica para generaciones futuras:

Ubuntu se actualiza pidiendole a uno que acepte las actualizaciones. Peeero, a veces falla.

Eventualmente, los gestores de "paquetes" o programas instalados en la VM terminan cayendo en el `dpkg`, que es el gestor de paquetes de bieeeen bajo nivel que tiene instalada la máquina.

Recapitulando, cuando `dpkg` falla por algún motivo y no termina de instalar toooodo, termina pidiendote (por mensaje en la consola) que corras el comando `sudo dpkg --configure -a` para volver a internarlo.
Como Ubuntu tiene "wrappeado" el `dpkg` no se da cuenta, prefiere ignorarlo, etc. Sea cual sea la razón, como toda buena actualización, termina pidiendote que reinicies la VM.

Ahora, si entre esas actualizaciones estaba una actualización del Sistema Operativo de Linux (que está abajo de ubuntu), cuando quiere volver a iniciar, falla!

Justamente por eso, al @mackhood iniciar desde una versión anterior del SO de Linux (que quedaron instalados en la VM porque no se completo la instalación), le funciona!.

Listo eso, como lo solucionamos? Como dijo @mackhood primero entramos bien al SO desde las "otras opciones de inicio" que aparecen a penas encendemos la VM.

Despúes, para detectar que ese es el problema corremos:
```
# Para saber si hay actualizaciones de programas
$ sudo apt update 
# Y luego actualizamos posta
$ sudo apt upgrade 
```

Si el último comando falla, suele decir que corramos el comando que dije antes (`sudo dpkg --configure -a`). Lo corremos y dejamos que instale todo.
Cuando termine es cuestión de probar reiniciando la VM y que todo siga el curso natural.

Si funciona, recomiendo hacer `$ sudo apt autoremove` para eliminar las versiones viejas que hayan quedado producto de la mala instalación que causo este problema 😄 

![image](https://user-images.githubusercontent.com/7110539/45971055-7d5b2300-c00e-11e8-8683-398e50888467.png)

PD: @mackhood PLZZZ cerrá el issue 😛

**Comment by mgarciaisaia** [comment]
PAAAAH

Alta investigación, che. Congrats a amb@s.


Lo de que las versiones anteriores del kernel queden igual instaladas creo que es una decisión de diseño más que una resaca de una instalación mal hecha. Justamente quedan para poder solucionar casos como este, u otros upgrades que puedas hacer que se apliquen bien, pero rompan compatibilidad con algún dispositivo o andá a saber qué.

Pero nunca había sabido de un caso puntual en que alguien lo aprovechara 😊

**Comment by 75985370** [comment]
Disculpen se que es tarde, pero una solución al problema es que si tienes Windows 10 o 11 desactives la opción  de integridad de la memoria  en Windows defender. 
1. Configuración Windows Defender → Inicio
2. Seguridad del Dispositivo
3.Desactivar la opción → integridad de la memoria
te va pedir que reinicies, eso será todo todo normal tal ves esta activado por seguridad de la PC 😉😉😉 espero que se ayuda
