### ISSUE TITLE
gitignore no permite subir el makefile

### ISSUE THREAD

**Issue by chamenwais** [sisoputnfrba/foro#1226]
Buen día.

Soy del grupo Leaking-Bad y en nuestro repositorio estamos usando el archivo .gitignore que encontramos cuando nos dieron el repo.
Solo le agregamos las extensiones .settings, .project y .cproject.

Nos está dando un error cuando queremos subir la carpeta Debug (donde está el archivo ```makefile```), o sus dependencias ```source.mk```, ```objects.mk```:

![image](https://user-images.githubusercontent.com/11778309/45917583-a635b980-be50-11e8-8f42-59fb8939f5e1.png)

Yo sé que lo puedo solucionar, y de hecho lo hice, forzando el ```add``` de github, pero me intriga conocer qué .gitignore lo está ignorando, ya que el único que ubico no lo hace

**Comment by natoszme** [comment]
Buenas! Cómo va?
Entiendo que lo que está pasando es que Eclipse se toma la molestia de generar algunos gitignore's por vos*, uno de ellos tiene solamente un /Debug/, lo que va a impedir que se suban los archivos en ese directorio. Para chequear que el problema sea este, tirate un ls -al en /FunesMemory9 a ver si está este .gitignore que te comento (uno distinto al que viene por default en el repo).

Contá qué onda!


*si es esto, hay una opción para desactivarlo en Eclipse desde Settings > Team > Git > Projects > Automatically ignore derived resources by adding them to .gitignore, si mal no recuerdo. Posiblemente tengas que borrar ese gitignore a mano porque dudo que Eclipse lo haga

**Comment by iago64** [comment]
@chamenwais Que tal te resulto la respuesta de @natoszme te fue util? seguis con el problema para subir los makefiles?

**Comment by chamenwais** [comment]
@natoszme se ve que era eso:
![image](https://user-images.githubusercontent.com/11778309/45989356-bf598880-c051-11e8-9511-f6ba8ae32623.png)

Ahí lo desactivé de Eclipse.
Muy útil y difícil de intuír. 
Gracias.
