### ISSUE TITLE
Duda enunciado

### ISSUE THREAD

**Issue by janicead** [sisoputnfrba/foro#1227]
En la ultima version de cambio V1.3, dice en el punto 1, que en la parte de DAM  de intermediario entre FM9 y MDJ, debiamos usar los terminos al reves.
El leer la parte de flush en la sintaxis del escriptorio, al hacer esta modificacion que ustedes plantean se terminan contradiciendo estas dos secciones.
Cual de los dos seria el correcto?
Desde ya, muchas gracias.
Janice

**Comment by tferraro** [comment]
Hola!

La aclaración está, porque el escenario propuesto para demostrar como seria
esa comunicación, es el caso MDJ->FM9. El flush si actuaría de la forma
inversa, solo que no es el escenario del ejemplo en si.

Es una buena aclaración poner de cual escenario estamos hablando, guarda😉
Me lo anoto para que le hagan mención a eso en la Versión de Cambios.

Salidos!
Tom

**Comment by janicead** [comment]
Muchas gracias!
Salidos!! 
Janice
