### ISSUE TITLE
Problema con el debugger 

### ISSUE THREAD

**Issue by IvanDL95** [sisoputnfrba/foro#1228]
Hola

Estoy teniendo un problema con el debug de Eclipse. Todos los procesos al inicializarse arman su configuración y para hacer eso usan una función de la commons, así que fallan todos en el mismo punto, nunca pasan de ahí.  
Me salta el error: "No source available for "config_has_property()"" siendo esta la primera función de la commons que usan.
Ya sea dandole a "Step Into", o a "Step Over" para que realice toda la función de una, el proceso termina inmediatamente.

Ya ví que había un issue con el mismo mensaje de error, pero no se que estaban intentando hacer y no entendí cual era la solución. Lo único que quiero hacer es que Eclipse me deje debuggear ya que sino no puedo probar el TP por cuenta propia.

**Comment by IvanDL95** [comment]
El vídeo no me sirvió no tanto en este caso (si bien se aprecia esa info) ya que el proyecto me compila bien y no tengo problemas corriendo los procesos, no tira ningún warning ni error ni nada, solamente sale a luz ese error al hacer debug. El que si me sirvió más fue el de debugging.
(lo linkeo por si alguien ve esto  y le sirve https://www.youtube.com/watch?v=XsefDXRfA9k).

Lo que sí pude detectar fue que al intentar usar la función config_has_property() ingresa siempre a la misma dirección de memoria, la consola de debug me manda el msje:
"Program Received signal SIGSEGV, Sementation fault.
 (direccion de memoria) in config_...() from /usr/lib/libcommons.so"
y al hacer un step más el proceso termina por sementation fault y deja de existir.

Me parece raro que salte un error así o que el proceso intente entrar a una posición de memoria que no debería al usar una función de la commons (que ademas tiene tests propios y los pasa correctamente)  y se cierre súbitamente. No sé si el problema está ahí o es un problema de configuración que no se puede detectar de esta forma.

Si comento esa parte y simplemente hardcodeo la configuración en el fuente no hay ningún problema al levantar el servidor y cada proceso queda a la espera de sus respectivas conexiones al correrse individualmente. Sólo me sucede al utilizar la función config_has_property(). Quizás pueda probar salteandomela, no es tan imprescindible ya que la usamos de validador del archivo de config, y si está bien armado no hay conflicto posible en esa parte.

**Comment by mgarciaisaia** [comment]
Tu solución está en este link, pero necesito que antes de abrirlo entiendas
el problema:
https://mgarciaisaia.github.io/tutorial-c/blog/2015/04/23/rutas-argentinas/

Si las commons están testeadas y confiamos en que funcionan, pero estás
teniendo un segmentation fault en una función de las commons que usa tu
programa, ¿en dónde puede quedar el problema?

Fijate en la línea en que llamás a esa función, y revisá qué parámetros le
estás pasando. Porque no todo es código, ¿no? También hay datos (la
división funciona perfecto, pero si mandas a dividir por cero, seguro
tengas un error).

Aprovechá el debugger y encontrá en qué línea empieza el problema, y tratá
de ver qué parámetro estás pasando mal.

Y después mirá ese link en el que Mati de hace unos años te contestó por
qué pasa tu problema y cómo solucionarlo.

Y después de hacer todo eso, contanos cómo fue, y seguí preguntando todo lo
que haga falta.

¡Un abrazo!

**Comment by IvanDL95** [comment]
Ahí pude solucionarlo. Borré todo el proyecto, volví a clonar el repositorio de mi grupo y lo pude correr. Tenía el repositorio también clonado en otra PC y le copié toda la configuración (es bastante lenta asi que uso la que tenía problemas). Me pareció raro esto porque ya habíamos armado toda la config y levantado el servidor y a mí no me andaba correctamente. No sé donde falló, pero se lo atribuyo a la magia de Eclipse que tiraba un segmentation fault mágico por alguna razón. 

Lo que sí tenemos es una carpeta propia para meter estructuras y funciones y surgía el problema cuando esta libreria llamaba a una función de la commons, no cuando compilaba, ahí no tenía problemas, es cuando corría donde tiraba ese segmentation fault. El problema lo debió causar algo de eso porque sino no se explica que el código esté bien armado (me fijé varias veces a ver si pasaba algún parametro raro aunque se tratase de una función bastante sencilla, aparte a los demás del grupo les corría), que esté todo correctamente linkeado como para que compile y aún así salte un error así a la hora de correrlo.

Gracias por la ayuda. De todos modos me puede ayudar a futuro para detectar problemas que puedan surgir del TP en sí.

**Comment by IvanDL95** [comment]
Buenas,

Estaba tratando de probar el TP en otra máquina y me surgió el MISMO problema. Pero... esta vez encontré esto.

![sdadsad](https://user-images.githubusercontent.com/30785918/49916752-19146680-fe7b-11e8-8611-5d97f8e5f0f9.png)

Me parece bastannte raro que esten esas direcciones sin definir (o eso parece por el hecho de que está una dirección en 0 y encima tiene un campo *UND* (no se que es lo que hace ese campo, pero me suena a undefined en este caso). Sé que el linker lo que hace es dejar una "especie de hueco" y hace referencia a una dirección lógica que es donde la commons (la libreria usada en este caso) se hace cargo del resto, pero parece que acá algo falla. Las commons las instale y no tuve drama, rebuildié todo y me fijé si estaba linkeada. Algún tema de configuración mal hecho debe haber, que si lo hago en cierto órden sucede esto, la otra vez me anduvo borrando y copiando todo. La verdad no sé que pueda ser porque lo googlié de varias formas y no encuentro una manera de expresarlo en una pregunta googleable.

No me tira errores al compilar, pero de nuevo me tira error al debuggear porque no encuentra la referencia a la libreria, igual que antes accede a config_has_property() en todos los proyectos al principio (por la forma en que ordenamos las funciones, obtiene la configuracion primero que nada) y ahí rompe todo, por eso hago foco en eso en la captura.

Igual no es la computadora que estaba usando principalmente para desarrollar el TP, lo estaba probando en otro lado por otras cuestiones, así que no hay apuro aunque quizás a alguien le sirva en un futuro.

**Comment by mgarciaisaia** [comment]
¡Hola @IvanDL95!

Lo primero que quería hacer es disculparme. Cuando cerraste el topic a fines de septiembre, estaba bastante seguro de que no habías encontrado el problema, pero, en vez de insistirte, repreguntarte, y hacerte dudar de lo que estabas haciendo, te solté la mano y dejé que sigas. Y acá estamos: con el bug de hace 2 meses, a 2 días de una entrega. Así que, eso: perdón por soltarte la mano.

Tu programa no tira errores a compilar porque tu sintaxis es correcta y todas tus expresiones tipan bien. El problema es que C no es un lenguaje muy seguro: [todos los tipos son `NULL`eables](https://www.infoq.com/presentations/Null-References-The-Billion-Dollar-Mistake-Tony-Hoare). Entonces, que tu programa tipe bien no significa que no pueda fallar al ejecutar.

No termino de entender qué es la captura de pantalla que subiste. Los nombres en las pestañas están tapados por el borde de la ventana de VirtualBox, y la verdad es que no recuerdo conocer esa vista. O capaz sí y nomás hace rato que no abro Eclipse, no lo se.

Como sea, sigo creyendo firmemente en lo que te dije en mis mensajes anteriores. El problema de "No source available" dice que el editor no te puede mostrar el código fuente de una función, pero eso no es el motivo por el que tu programa falla. Tu programa falla porque algo está funcionando mal. Cuando tu programa falla, el debugger de eclipse se mete en el medio e intenta mostrarte dónde está fallando tu programa. Y cuando intenta mostrarte el código que falla, como es código de una biblioteca compilada, no tiene el código fuente para mostrarte. Y cuando eclipse detecta que no tiene el código fuente que te quiere mostrar, te muestra el mensaje de "No source available".

En #516 hay un post mío con fotitos y todo de cómo usar la vista de Debug. Ahí vas a poder moverte en el stack para ver el último cacho de código _tuyo_ que llamó a una función que hizo que rompa el proceso. Y cuando estés mirando eso, vas a poder las variables locales, y ahí seguramente vas a encontrar alguna que tenga un valor que no sea el que estás esperando.

Si yo tuviera que apostar plata (no va a pasar), insistiría en lo mismo que en mi mensaje anterior: el path de tus archivos de configuración está seteado de algún modo que no funciona bien en todas las máquinas. Por eso la otra vez borraste todo, arrancaste de nuevo, y algo hiciste distinto que empezó a andar, pero ahora cambiaste de máquina y en esa no anda.

No te olvides que el sábado vas a tener que instalar el TP en otras máquinas, así que mejor pegale posta una leída al post de Rutas Argentinas que te linkeé por ahí, a ver si entendés el problema, y cómo solucionarlo.

Posta, solucionalo :)

Te mando un abrazo, y te leo cualquier cosa.

**Comment by IvanDL95** [comment]
>El problema es que C no es un lenguaje muy seguro: todos los tipos son NULLeables. Entonces, que tu programa tipe bien no significa que no pueda fallar al ejecutar.

Esto lo entiendo. Sé que si sucedería algo así, de hecho me tira warnings todo el tiempo acerca de cosas que no son seguras, que después voy revisando a ver que sucede. En este caso no era un error de ejecución, ya que no había cambiado nada (con respecto al proyecto en sí) y salió andando bien el debugger. Si tengo otro problema al debuggear otra cosa seguro que es algo de lo que yo haya hecho y no de una configuración del proyecto que haga que rompa.

>No termino de entender qué es la captura de pantalla que subiste. Los nombres en las pestañas están tapados por el borde de la ventana de VirtualBox, y la verdad es que no recuerdo conocer esa vista.

Es que saqué la captura desde el escritorio de Windows, no sé si había un problema de configuración de las guest addittions, que no me gasté en revisar en ese momento, que no me tomaba la captura de pantalla desde la VM. Decidí hacer eso para no perder tiempo.

> el path de tus archivos de configuración está seteado de algún modo que no funciona bien en todas las máquinas

Esto debe ser lo más probable. Lo que no sé bien es donde fijarme, dentro de la configuración del proyecto, donde está seteada bien la ruta. Porque al incluir las commons, simplemente hago que incluya automáticamente -lcommons al compilar, sin necesidad de fijarme esas cosas.

Estoy desde la computadora que me funciona bien. Indagué y encontré ciertos seteos de rutas dentro de las propiedades del código objeto (el .o) que, dentro de la pestañas de "Libraries" hace referencia a "commons", obviamente porque la estoy incluyendo al compilar. Probé debuggear y el problema en ese punto no reaparece, utiliza las funciones de las commons sin ningún drama como lo hizo desde antes, o sea, la referencia es correcta. Hasta advierte del uso de rutas relativas con esto al incluir pthread (haciendo -lpthread en los includes al compilar)

Lo que tenemos es una referencia relativa al Debug de nuestra library (usando $workspace_loc). Acá hay un mensaje advirtiendo sobre el uso de rutas relativas, pero el problema no es con esta ruta, ya que funciona correctamente, sino cuando accede a las commons. Si puede haber algún problema con estas configuraciones no lo estoy viendo.

Hay algo que noté también que puede ser un problema, que es distinto y por ahí hay algo que rompe por usar rutas relativas (en alguno de todas las referencias que puede haber dentro de las llamadas). La vez que no me andaba tenía la commons bajada DENTRO de la carpeta del proyecto (llamemosle "tp_SAFA" para simplificar). Entonces, las commons se encontrarían en workspace/tp_SAFA/so-commons-library, en cambio, en el caso que sí anda se encuentra en workspace/so-commons-library. No sé si esto genera algún problema, porque las commons se instalan igual. Ahora mismo se me complica un poco ver si haciendolo al revés rompe el debugger en ese punto como para fijarme si hay algo que el stack me diga.

>En #516 hay un post mío con fotitos y todo de cómo usar la vista de Debug. Ahí vas a poder moverte en el stack para ver el último cacho de código tuyo que llamó a una función que hizo que rompa el proceso. Y cuando estés mirando eso, vas a poder las variables locales, y ahí seguramente vas a encontrar alguna que tenga un valor que no sea el que estás esperando.

O también que la llamada a la función produzca segfault por no tener la referencia, que sería este caso. Está accediendo a una dirección de memoria que no le corresponde, por problemas de configuración. Quizás el stack pueda dar alguna data sobre que es lo que hace que rompa, voy a ver si puedo leer lo que me traiga.

**Comment by mgarciaisaia** [comment]
On Fri, 14 Dec 2018, 02:47 IvanDL95 <notifications@github.com wrote:

> de hecho me tira warnings todo el tiempo acerca de cosas que no son seguras
>
Más o menos, eh. Digo, seguramente sea cierto que te tira warnings por
cosas no seguras, pero también seguramente esté hablando de casteos medio
jugados. Estoy casi seguro de que el compilador de C no trackea potenciales
problemas por NULLs, principalmente porque el sistema de tipos no lo
permite. Lenguajes más modernos (Rust, Swift, creo que Kotlin, Crystal
seguro) tratan al NULL como un tipo aparte, y entonces te pueden avisar
cuando una variable puede ser nula pero tu código no está contemplando ese
caso. C no tiene esa capacidad, porque su sistema de tipos no permite
representarlo.

> En este caso no era un error de ejecución, ya que no había cambiado nada
> (con respecto al proyecto en sí) y salió andando bien el debugger.
>
Si el programa compila, y falla cuando lo ejecutás, es un error de
ejecución. Respecto a que no cambiaste nada, la ves que escribiste en
septiembre cambiaste _todo_.

No cambiaste el código, OK; pero borraste todo el proyecto y lo volviste a
clonar. Si te dio resultados distintos, es porque _algo_ del ambiente de
ejecución cambió.

> Es que saqué la captura desde el escritorio de Windows, no sé si había un
> problema de configuración de las guest addittions, que no me gasté en
> revisar en ese momento, que no me tomaba la captura de pantalla desde la
> VM. Decidí hacer eso para no perder tiempo.
>
No pasa nada. No era "reto"; nomás estaba tratando de mostrar el grado de
certidumbre con el que me estoy manejando, para que tomes con las
respectivas pinzas lo que concluyo.

Por otro lado, un amigo se pasó todas unas vacaciones repitiendo que
Napoleón decía "vísteme despacio, que estoy apurado". Andá a chequear si lo
decía en serio, pero la idea es buena igual. Un noble espíritu agrandece
hasta al hombre más pequeño, eh.

> Esto debe ser lo más probable. Lo que no sé bien es donde fijarme, dentro
> de la configuración del proyecto, donde está seteada bien la ruta. Porque
> al incluir las commons, simplemente hago que incluya automáticamente
> -lcommons al compilar, sin necesidad de fijarme esas cosas.
>
O también que la llamada a la función produzca segfault por no tener la
> referencia, que sería este caso. Está accediendo a una dirección de memoria
> que no le corresponde, por problemas de configuración. Quizás el stack
> pueda dar alguna data sobre que es lo que hace que rompa, voy a ver si
> puedo leer lo que me traiga.
>
Ojo al piojo con esto. Me suena a que estás pensando en que, al ejecutar tu
programa, el sistema operativo (bah, el linker, más precisamente) no está
encontrando el .so de las commons. *Estoy casi seguro de que no es el caso.*

Cuando pasa eso, la ejecución falla antes, con un menaje horrendo de "Error
while loading shared libraries. Cannot open shared object file: no such
file or directory.". Buscalo acá en el foro. Si me dieran un mango por cada
consulta sobre ese error, me habría empachado de licuados ya.


Si querés reproducir el problema en tu máquina que está andando bien
(porque, claro - si no te falla, es difícil entender cómo arreglarlo), mové
de directorio tu archivo de configuración. Es decir, agarrá tu safa.conf (o
el proyecto/nombre que sea) y cambialo a un directorio distinto, y después
volvé a correr tu proyecto. 99% de chances de que veas el mismo error de
siempre. Y ahí vas a poder jugar con el stack en la vista de debug, como en
el ticket que te conté.

Un abrazo.

>
