### ISSUE TITLE
Diseño de DMA

### ISSUE THREAD

**Issue by cmedrano** [sisoputnfrba/foro#1229]
Hola,
Queríamos validar con el grupo el diseño que pensamos para DMA ya que con la version 1.3 del enunciado quedamos en duda si esta correcto.
En un principio nosotros lo implementamos con un SELECT  con todos los sockets que atienden a las distintas cpus, un socket por cada cpu. 
Por cada petición de cada CPU (ya sea para pasar datos de FM9 a MDJ o al revés)  atendemos la petición completa de manera secuencial.
Es decir, cuando llega una petición  de una CPU atraves de un socket que sale del SELECT hacemos los sigueintes pasos:
Si es para pasar datos de MDJ a FM9 haríamos lo siguiente.
Mandamos una petición  a MDJ para que nos pase los datos de un archivo
Recibimos lo datos del archivo y luego le mandamos esos datos a FM9
Luego avisamos a SAFA que los datos ya se encuentran en FM9.
Fin--> atendemos otra petición de otra CPU que sale del SELECT.
Si es para pasar datos de FM9 a MDJ haríamos lo siguiente(Flush).
Mandamos una petición  a FM9 para que nos pase los datos de un archivo
Recibimos lo datos del archivo y luego le mandamos esos datos a MDJ
Fin--> atendemos otra petición de otra CPU que sale del SELECT.

Siguiendo esta idea pensamos a MDJ como un proceso server que atiende las solicitudes de DAM de manera secuencial, es decir, atiende una perición de DAM y hasta no responder la petición no atiende otra.

Nuestra idea es mas parecida a la "Opción 1" 

Por favor podrían decir si hay algo que no tuvimos en cuenta o estaría ok.
Muchas gracias
Saludos

**Comment by tferraro** [comment]
Buenas!

Las opciones son solo a modo ilustrativo para que tengan un norte.
Pasa que cuando uno evalúa una decisión de diseño tiene que, en primer lugar, generar un racional de _porqué se eligió lo que se eligió_. Una vez fijado eso, se puede iterar con opiniones ajenas para obtener una buena retroalimentación y mejorar.

Por eso, no puedo decir _ni "Si" ni "No", ni blanco ni negro_. Peeero, les recomiendo que estas decisiones más _intragrupo_ las discutan entre ustedes y validen con sus ayudantes asignados.
(Más que nada, porque no se que tanto les aporten a los demás grupos su solución específica, bajo sus condiciones y sin saber porqué la eligieron 😛 y va a terminar generando u thread de mensajes sin final).

Tom
