### ISSUE TITLE
t_log no reconocido

### ISSUE THREAD

**Issue by florlipchak** [sisoputnfrba/foro#1230]
Buenas,
Estábamos intentando usar el log de commons y no nos reconoce ni la estructura t_log ni ningún método del log.h

#include <commons/log.h>

t_log*

Hacemos el import de esta forma y no funciona. 
No es la primera vez que usamos las commons, y con las otras cosas no tuvimos problemas.
Si alguien nos da una mano vendría genial.

¡Muchas gracias!

**Comment by mgarciaisaia** [comment]
https://faq.utnso.com/errores-eclipse

En serio. Con esto solo no hacemos nada 😣

**Comment by brendaboryszanski** [comment]
Aparece este error: error: unknown type name ‘t_log’
Nosotros tampoco tenemos mas informacion!

**Comment by florencialipchak** [comment]
![image](https://user-images.githubusercontent.com/35460863/46608836-6f140900-cadc-11e8-9656-63fb692cb3a6.png)


![image](https://user-images.githubusercontent.com/35460863/46608813-5d326600-cadc-11e8-8819-a65d0f7145e4.png)

La consola no dice nada, no se muestra como si no pudiera compilar: (Lo corrimos después de hacer el project -> clean) 

Building file: ../biblioteca/logger.c
Invoking: GCC C Compiler
gcc -O0 -g3 -Wall -c -fmessage-length=0 -fPIC -MMD -MP -MF"biblioteca/logger.d" -MT"biblioteca/logger.o" -o "biblioteca/logger.o" "../biblioteca/logger.c"
Finished building: ../biblioteca/logger.c

**Comment by iago64** [comment]
Buenas buenas!

Pregunta técnica, las commons las instalaron en su VM o las tienen referenciadas como un proyecto?
Por otra parte, no veo en la salida del make que las tengan linkeadas (deberían tener algo asi como -lcommons en algún lado y no esta) las linkearon bien en eclipse?
En el [Repo de las Commons](https://github.com/sisoputnfrba/so-commons-library) esta explicado como instalarlas y como linkearlas correctamente para que no pasen estos problemas de que eclipse no les encuentra cosas / no les cunfionan

Saludos.-

**Comment by mgarciaisaia** [comment]
```
Finished building target: libbiblioteca.so
```

¡Entonces anduvo!

El subrayadito rojo es Eclipse que se marea un poco y deja de entender bien las cosas. Pero el que importa es `gcc`, que pudo compilar bien tu proyecto.

Para curar un poco a Eclipse, dale click derecho al proyecto, y andá a Index -> Rebuild index. Eso debería hacer que Eclipse vuelva a mirar todo el proyecto y regenere los índices internos que usa para el autocomplete y todas las tareas que Eclipse hace.

Cuenten si eso ayudó :)

**Comment by florencialipchak** [comment]
¡Perfecto! Era eso. 
Graciaaas

**Comment by tferraro** [comment]
@florlipchak plzzzz cerrá el issue 😄

**Comment by ggallici** [comment]
Buenas, tengo un issue similar. Tambien me tira "unknown type name", pero no me termina de compilar. Habia estado usando las commons como si nada, pero despues de mover un par de carpetas del proyecto y renombrar cosas, dejo de andar y empezo con este error. Ya intente clean/build, rebuild index, reinstalar las commons, no se que mas hacer.

**Comment by mgarciaisaia** [comment]
Podés intentar... ¡Pasar los logs! :tada:

En los logs vamos a poder ver qué es lo que eclipse le está pidiendo a gcc que haga. Y, con un poquito de suerte, vamos a poder entender qué de todo eso es lo que no está funcionando.

Sin los logs... medio que no sabemos mucho, excepto el síntoma. Te podemos recitar las 1001 causas posibles, pero vas a probar quinientas cosas que no tenían nada que ver, y encima capaz justo nos olvidamos de una opción, que justo justo justo era la que te estaba pasando, y estiramos el problema para siempre.

Vamos con los logs, mejor, ¿dale?

**Comment by ggallici** [comment]
No me quiero arriesgar a asegurarlo, pero creo que se solucionó. El problema es que había creado un .c con funcionalidad extras sobre listas y tenía el mismo nombre que el .c de las commons. Le cambie el nombre y magicamente compiló.

**Comment by mgarciaisaia** [comment]
Arthur C. Clarke decía que ["Cualquier tecnología lo suficientemente avanzada es indistinguible de la magia"](https://www.goodreads.com/quotes/14885-any-sufficiently-advanced-technology-is-indistinguishable-from-magic). El tema está en que nosotros nos dedicamos a [aprender sobre] la tecnología, y que, como bien nos enseñan en física, "avanzada" depende de tu sistema de referencia.

Así que, en resumen, que no nos sea magia :)

¡Un abrazo!
