### ISSUE TITLE
Pregunta tp sentencias

### ISSUE THREAD

**Issue by brendaboryszanski** [sisoputnfrba/foro#1231]
Hola! Quería consultar que serían las sentencias de las métricas del S-AFA. Si se podía dar más info acerca de ese tema.
Gracias!

**Comment by tferraro** [comment]
Buenas!

Vamos por partes. A que denominamos normalmente "sentencia" en un programa cualquiera? En función de eso, como te parece que podríamos usar eso, para inferir a "qué" hace referencia dentro el tp?

**Comment by tferraro** [comment]
> Sentencia en un programa es una instrucción,(...)

Eso, eso!

> es la cantidad de líneas que se hicieron en la cpu mientras estaba este proceso en new?

Sip :).

> Por lo que la cpu debería devolver la cantidad de líneas que ejecutó.

No necesariamente fisicamente así, pero en cierto punto, deberías saberlo, si.

> qué pasa si mientras la cpu estaba ejecutando el proceso pasó de new a ready?

Cuenten hasta ahí. La idea es mostrar mediante métricas el funcionamiento del sistema, diferencias pequeñas por estos casos bordes no cambian :)

> Y si hay varias cpus? Debería sumar las sentencias de cada una de estas?

Es un buen punto, pero si, _tiene sentido que se acumulen todas las CPUs_, porque el grado de multiprogramación está muy ligado a las CPUs del sistema.

**Comment by brendaboryszanski** [comment]
Muchisimas gracias!
