### ISSUE TITLE
Consulta error en semaforos

### ISSUE THREAD

**Issue by brendaboryszanski** [sisoputnfrba/foro#1232]
Hola! me esta rompiendo al hacer un wait de un sem_t y no entiendo porque...
Paso a mostrar como esta mi codigo:

Tengo un semaforo declarado asi:

**sem_t semOperaciones;**

Despues.. lo inicializo:

**inicializarSem(&semOperaciones, 0);**

Donde inicializarSem es una funcion mia que hace lo siguiente:

**void inicializarSem(sem_t* semaforo, int valorInicial){
	sem_init(semaforo, 0, valorInicial);
}**

Luego tengo una estructura que contiene al semaforo de esta forma:
**sem_t* semOperaciones;**

y se lo asigno:
**Miestructura* miestructura = malloc(sizeof(Miestructura)); 
miestructura->semOperaciones = &semOperaciones;**

Luego llamo a una funcion en mi biblioteca pasandole como parametro mi estructura
**realizarNuestroSelect(miestructura);**

y la funcion realizarNuestroSelect utiliza el semaforo. Al hacerle signal lo hace correctamente y cuando hago wait el proceso termina porque rompe.
Muestro como utilizo el semaforo en el signal y el wait:

Tengo otra estructura que contiene a miestructura agregandole un parametro mas

Tengo las funciones en mi libreria:

**int waitSem(sem_t* semaforo){
	int numero =  sem_wait(semaforo);
	return numero;
}

int signalSem(sem_t* semaforo){
	return sem_post(semaforo);
}**

Y lo utilizo 

**signalSem(miestructura->miotraestructura->semOperaciones);**

y donde rompe:

**waitSem(select->semOperaciones);**

Saben que puede ser?
gracias!

**Comment by natoszme** [comment]
Buenas! Cómo va? Puede ser que el parámetro de waitSem sea un struct sem_t y no un puntero a ese struct? Entonces rompe cuando le pasás un puntero al struct

Tiro esto que se me ocurre porque intenté buscar el código en su repo para tener un panorama más general y encontré que el código no era este tal cual.

Contanos si era eso!

**Comment by brendaboryszanski** [comment]
La definicion de sem_wait es asi:
extern int sem_wait (sem_t* sem)

y la que hicimos nosotros 

int waitSem(sem_t* semaforo){
int numero = sem_wait(semaforo);
return numero;
}


Al poner en negrita se salio el *. La estructura miestructura se llama select. En nuestro codigo se ve en S-AFA al llamar al crearSelect() y esas funciones se utilizan dentro de biblioteca en nuestroSelect.c


Gracias!

**Comment by natoszme** [comment]
Cuando decís que rompe, qué error tira? Supongo que con [esto] (https://faq.utnso.com/errores-eclipse) vamos a poder ayudarte mejor!

**Comment by brendaboryszanski** [comment]
No tiraba ningun error, rompia nomas. No rompia ahi... era un problema de que se mandaba.. no se poruqe aparecio que rompia ahi. Ya lo pude solucionar! gracias :)
