### ISSUE TITLE
Al enviar y recibir mensajes no se reciben

### ISSUE THREAD

**Issue by brendaboryszanski** [sisoputnfrba/foro#1233]
Hola, queria consultar si se les ocurre porque puede ser esto. Tenemos una estructura operacion que tiene un header y un emisor. Entonces por cada cliente que se conecta al servidor se abre un hilo productor que agrega operaciones a la cola, y despues se crea un hilo consumidor que las saca de la cola y realizan la operacion correspondiente, recibiendo los mensajes restantes del emisor. Al guardarlo en la cola todo bien, pero al sacarlo y querer recibir otro mensaje de este cliente... se queda esperando. Se manda un int por ejemplo correctamente de una forma que antes funcionaba, y al recibirlo se queda esperando que se lo mande. Puede tener que ver con el asincronismo de esto? 
Gracias!

**Comment by afilgueira** [comment]
Hola, no entendí completamente el escenario, pero un par de cosas que miraría:

- Hay un sólo hilo consumidor en ejecución? Si la respuesta es "no", chequearía que el mensaje que esperas no se lo "lleve" otro
- Quién es el que se queda esperando? El productor? O el consumidor no puede sacar más?
- Por si acaso, chequearon los tamaños en los `receive` que hagan? Es posible que, intentando recibir un mensaje,  reciban más que eso?
- Los hilos que no están "haciendo nada" se bloquean de alguna forma? Receive, semáforo, etc

Saludos!

**Comment by brendaboryszanski** [comment]
Genial Adro! era eso!

Pasaba esto:
Hay un sólo hilo consumidor en ejecución? Si la respuesta es "no", chequearía que el mensaje que esperas no se lo "lleve" otro

Ya que estaban los productores en un while(1) de recibir los headers del emisor y mientras el consumidor queria recibir el int, lo recibia este otro hilo(el de los productores).
Lo solucionamos poniendole un semaforo!
Muchas gracias por la respuesta :)
