### ISSUE TITLE
Arquitecturas con hilos DMA

### ISSUE THREAD

**Issue by IvanDL95** [sisoputnfrba/foro#1234]
Buenas. Tengo una consulta acerca del diseño del DMA. 

La guía propone 3 arquitecturas distintas. La opción 1 la comprendo bien (la secuencial), no tengo dudas mayores.

La opción 2 propone hilos con concurrencia, mientras que la 3 paralelismo con hilos. No comprendo bien que hace cada una y a partir de esto cuales son las diferencias de aplicar una opción o la otra. El gráfico me da una vaga idea de que la 2 atiende las consultas paralelamente por separado sin interacción entre los hilos y que la 3 hay un punto donde la información se entrecurza entre hilos. 

Yo entiendo que en la concurrencia se da que, cuando el CPU realiza una interrupción y consulta al DMA por la operación de E/S, se abre un hilo y este no se cierrra hasta que no termina la operación, es decir, realiza la serie de msjes al MDJ y al FM9 y "se queda esperando" la respuesta de ese msje para seguir la operación, cerrandose recién al completar la operación. En cambio en el paralelismo, el hilo ya abierto le manda mensaje al MDJ para que busque datos de un archivo (como ejemplo) y "vuelve" para atender otra operación de E/S, muy probablemente distinta, a la que estaba realizando hasta ese momento, pudiendo mezclarse la información si no se utilizan estructuras para controlar eso apropiadamente.

Me interesa entender esta diferencia porque (claramente) nos interesa aplicar una arquitectura con hilos para el DMA en nuestro TP.

**Comment by IvanDL95** [comment]
Y ya que estamos otra consulta que nada que ver. Como se ponen etiquetas a los issues? Me hubiese gustado ponerle alguna por mi obsesión de decorar los posteos de este estilo.

**Comment by afilgueira** [comment]
Buenas,

En líneas generales, vos tenés N CPUs haciendo "pedidos" al DAM. En la otra punta, el filesystem del MDJ atiende de a un "pedido" a la vez. Eso hace que en algún lado se encolen pedidos. Las 3 arquitecturas propuestas arman esta cola en diferentes lugares, y todas tienen sus ventajas y desventajas. 

Dependiendo de cada grupo (y sus conocimientos y ganas de aprender a usar multiplexación e hilos) pueden usar una u otra. La idea es que entiendan como funcionan, teniendo en cuenta lo que comentaba arriba. 

Saludos!

**Comment by tferraro** [comment]
@IvanDL95 te sirvió la respuesta de adro? Como venís con eso?

**Comment by tferraro** [comment]
Cierro por inactividad, cualquier cosa lo volvemos a abrir! @IvanDL95
