### ISSUE TITLE
Consulta - Condición de list_filter() con dos parámetros

### ISSUE THREAD

**Issue by EzequielVargas** [sisoputnfrba/foro#1235]
Hola! Cómo están?

Escribimos este issue porque tenemos la necesidad de filtrar una lista usando dos parámetros. Por ejemplo, tenemos una lista cuyos nodos tienen la siguiente estructura:

```
typedef struct {
    int pid;
} t_nodo;
```
Ahora, queremos filtrar los nodos, cuyo PID sea igual a uno pasado por parámetro. Sin embargo, no logramos hacer funcionar nuestro código.

Por favor, nos podrán dar una mano?

Muchas gracias!!!

**Comment by mgarciaisaia** [comment]
¡Aloha!

Contame si [este video](https://www.youtube.com/watch?v=1kYyxZXGjp0) es lo que andabas buscando.

¡Un abrazo!

**Comment by natoszme** [comment]
Buenas! Cómo va?

Como ya sabrás, el filter recibe por parámetro otra función (la que definirá el criterio a cumplir). Particularmente, [gcc ](http://gcc.gnu.org/onlinedocs/gcc/Nested-Functions.html) admite funciones anidadas, por lo que podrías definir una función dentro de la función que llama al filter, y pasarle esa por parámetro. Tiene sus limitaciones porque, según entiendo, te limita a usar este compilador, pero seguramente algún otro ayudante que la tenga más clara sepa explayarse más.

**Comment by tferraro** [comment]
@EzequielVargas ponete la 10 y cerranos el tické 😆
