### ISSUE TITLE
Sobre el Bitmap.bin

### ISSUE THREAD

**Issue by EzequielVargas** [sisoputnfrba/foro#1237]
Hola, cómo están!

Les escribo para hacerles algunas consultas sobre el Bitmap.bin. 

Entiendo que dicho archivo va a contener tantos 1s y 0s como cantidad de bloques que componen al FileSystem. Es decir, si mi FileSystem tiene 1000 bloques, entonces el Bitmap.bin tendrá 1000 dígitos entre 1s y 0s, que indican si un bloque está libre u ocupado.

Ahora bien, mi consulta radica sobre la lectura/carga del Bitmap.bin.

1) El Filesystem lo van a proveer ustedes junto **con** el Bitmap.bin que refleje la situación de los bloques? Con este escenario, entonces nosotros debemos traer el archivo a memoria y administrarlo con las funciones de bitarray de las commons para mantenerlo actualizado.

2) El Filesystem lo van a proveer ustedes pero **sin** el Bitmap.bin. Bajo este escenario, nosotros somos los responsables de recorrer todos los bloques del FS, (para determinar cuáles bloques están ocupados o no) crear dicho archivo y mantenerlo actualizado.

¿Cuál de las dos opciones es la que aplica para el TP?

Muchas gracias,

Ezequiel

**Comment by tferraro** [comment]
Buenas!

Si en la prueba hay bloques con info, va a venir el bitmap. No se calienten en hacer la búsqueda y regenerarlo a menos que tengan el tp ya funcional.

Tom

PD: A modo de aclaración "traerlo a memoria" != "traerlo al FM9".

**Comment by kamipalomino** [comment]
sobre este tema me genera una duda.. el bitmap.bin lo crea el mismos mdj o no?
al igual que el metadata.bin .. y demás?
o sea el FIFA por lo que habia entendido creaba 3 carpetas bloques, metadata y archivos

- Metadata -> metadata.bin y bitmap.bin ambos creados por FIFA

- Archivos -> [PathDelArchivo]  acá me surge la duda,  en este directorio van a estar los escriptorios?

- Bloques -> "Los datos estarán repartidos en archivos de **texto nombrados** con un número, el cual representará el número de bloque**. (Por ej 1.bin, 2.bin, 3.bin)..**  son .txt o .bin??? en cualquiera de los casos por ejemplo si en metadata.bin dice CANTIDAD_BLOQUES=5192 quiere decir que tengo que crear 5192 archivos en este fichero??

Nosotros habiamos implementado que FIFA crea todo el árbol de directorio partiendo desde el punto de montaje. A partir de ahi se iba creando y modificando todos los archivos pedidos por DAM.


lo que no nos quedaba claro luego de crear los ficheros.bin como hacer para verificar que la info cargada en sea la correcta? desde linux como los puedo abrir? 

Muchas gracias, Saludos.
Cami

**Comment by EzequielVargas** [comment]
Gracias!!!!
