### ISSUE TITLE
Duda funcion crear archivo MDJ

### ISSUE THREAD

**Issue by AxelFulop** [sisoputnfrba/foro#1241]
buenas en la funcion crear archivo del MDJ dice en una parte:

Además, el archivo nuevo deberá estar creado con
"N" cantidad de caracteres "\n"

si la el numero de bytes es 512, el archivo tendra que contener el caracter  "\n" 512 veces? o se refiere que se crea el archivo con ese tamaño?

otra consulta, cual es la diferencia cuando habla de lineas con la de byte? si aumentan las lineas no aumentan los bytes?

gracias

**Comment by tferraro** [comment]
Buenas!

A la primera preguntas: Si y si. Si tiene N "\n", dado que cada caracter ocupa 1 byte, entran en los N bytes.

A la otra consulta:
- Línea -> secuencia variable (hasta un tope) de bytes terminada en \n
- Bytes -> Unidad más chica en la que trabaja el MDJ

La cantidad de líneas queda fija, pero el tamaño de las mismas no, por lo que "aumenta" en bytes.
