### ISSUE TITLE
Problema mmap

### ISSUE THREAD

**Issue by brendaboryszanski** [sisoputnfrba/foro#1242]
Hola!
Estoy realizando la funcion mmap y me logra abrir el archivo pero al hacer el mmap me devuelve "0xffffffff <error: Cannot access memory at address 0xffffffff>"

Muestro el codigo:

```
char* obtenerDatosDeArchivo(int offset, int tamanio, char* path){
	size_t tamanioALeer = tamanio;
	off_t of = offset;
	int myFile = open(path, O_WRONLY | O_RDONLY | O_CREAT, S_IRWXU);
//ACA abre el archivo
	if(myFile < 0){
		log_info(logger, "Error abriendo el archivo!");
	}

	char* buffer = mmap(NULL, tamanioALeer, PROT_READ | PROT_WRITE | PROT_EXEC, MAP_SHARED, myFile, of);

	//free(rutaArchivo);
	return buffer;
}
```

Al correrlo desde consola tira segmentationfault
Al correrlo con valgrid aparece "invalid read of size 1" en una linea que le hacemos el print.
Al debuggearlo y ejecutar la linea de mmap al pasala y ver uqe quedo en buffer aparece "0xffffffff <error: Cannot access memory at address 0xffffffff>"

Se les ocurre que puede estar pasando??

Buscamos por el foro e internet y no encontramos solucion

El checkpoint es maniana!!!!
AYUDAAAA

**Comment by mgarciaisaia** [comment]
`0xffffffff` es, en binario, un montón de bits en 1.

_Curiosamente_, la representación del `-1` en entero signado de 32 bits (es decir, un `int` de 32 bits) es, también, _un montón de bits en 1_.

Es decir - ese `0xffffffff` es la interpretación como puntero del entero `-1`.

¿Qué significa esto? Que están usando mal la función `mmap`. Si leen la sección `Return Value` de [la página del manual de `mmap`](https://linux.die.net/man/2/mmap), van a ver que dice que, en caso de error, `mmap` va a devolver un `-1` casteado a puntero (y que, convenientemente, hay definida una constante `MAP_FAILED` que tiene ese mismo valor, para comparar).

_Además_, `mmap` setea el valor de la variable `errno` convenientemente, para indicar cuál fue el error que ocurrió. Y en el manual están las distintas posibilidades.

Antes de usar el valor devuelto por `mmap` como puntero, deberían chequear que no sea un error.

Peguenle una nueva mirada y vean qué está pasando :)

**Comment by tferraro** [comment]
Buenas! @brendaboryszanski te sirvió la respuesta de Mati? Como vienen con eso?

**Comment by tferraro** [comment]
Cierro por inactividad, cualquier cosa lo volvemos a abrir!
