### ISSUE TITLE
Script para correr en Ubuntu server

### ISSUE THREAD

**Issue by julisasla** [sisoputnfrba/foro#1243]
Hola,

Queria hacer una consulta sobre como crear un script en ubuntu para varios aspectos:

Actualmente nuestro TP lo corremos con luego de compilar el proyecto en eclipse desde la carpeta Debug,
al querer realizar esto desde el entorno donde se realizara la entrega, nos dimos cuenta que nos falta un comando para poder compilar el TP desde la consola, por lo que necesitaria realizar un script que lo haga.

Ademas, estamos utilizando una shared library por lo que debemos tambien configurar los LIBRARY_PATH y sus variables de entornos, para esto tambien necesitaria un script

Creo que algo modifica en el bash rc tambien, pero no estoy seguro de si eso es necesario en el script, creo que si

Saludos

**Comment by varas-c** [comment]
Buenas! Como va?

Podes crear un shell script con el lenguaje que mas te guste (python, bash,
etc). Lo mas sencillo que podes hacer para crearte un "instalador" para tu
tp, es usar los propios comandos de la terminal pero poniendolos en un
archivo y ejecutándolo. Como lo hacemos?

1 - Vamos a crear un archivo de texto, ponele instalador (Comando para
crearlo -> touch instalador)
2 - Vamos a escribir lo siguiente en el archivo y lo guardamos (voy a
suponer que lo guardamos en /home/utnso y se llama instalador)

#!/bin/sh
> cd tp-operativos
> make install
> export LD_LIBRARY_PATH=etc/etc/etc


3 - Vamos a correrlo por la terminal, ubicandonos en /home/utnso y haciendo
./instalador

Que hicimos con esto? Lo que hicimos fue simplemente poner en un archivo de
texto comandos que usariamos en la consola. Solo que al ejecutar el
archivo, automaticamente se van a ejecutar uno por uno los comandos que
escribimos *en el orden que los escribimos*

Es decir, cuando corremos el archivo, nuestra terminal va a ejecutar "cd
tp-operativos" (vamos a suponer que la carpeta existe). Despues va a
ejecutar "make install" y despues va a ejecutar export LD_LIBRARY_PATH.

Para terminar, seguramente estarás preguntándote: *"Que es esa linea
#!/bin/bash ???" . Se llama "Shebang" y googleandolo vas a encontrar mucha
info, como por ejemplo acá: https://bash.cyberciti.biz/guide/Shebang
<https://bash.cyberciti.biz/guide/Shebang>*

Cualquier otra duda o si algo no quedó claro, consultanos!

**Comment by mgarciaisaia** [comment]
A lo que dijo Cris, una única corrección.

Si creás un script y lo ejecutás corriendo `./instalador`, lo que ocurre (podés leer un poco más en [She bangs](https://mgarciaisaia.github.io/tutorial-c/blog/2014/03/20/she-bangs-she-bangs/)) es que el sistema operativo crea un nuevo proceso en el que ejecuta el intérprete que le indicamos en el script - en este caso, `/bin/sh` -, y _ahí_ ejecuta las instrucciones que el script indica. Cuando terminan de ejecutarse todos esos comandos, el proceso finaliza, y volvemos a nuestra shell original, donde podemos seguir ejecutando comandos.

El tema es que las variables de entorno (las que seteamos con el comando `export`, como la famosa `LD_LIBRARY_PATH`) viven en el contexto de una shell. Es decir, ese `export LD_LIBRARY_PATH` que hacemos en la última línea del script ocurre dentro de nuestro segundo proceso `/bin/sh`, que finaliza justo justo después de ejecutar ese comando. Cuando volvamos a nuestra shell original y podamos seguir tipeando comandos, esa variable ya no va a estar seteada*. De nuevo: la shell que origina la ejecución del script y la shell en que se ejecuta el script son dos procesos distintos. Y, como bien estudiamos en la materia, los procesos no comparten memoria/variables por default.

Como siempre, no me creas: corré el script como te cuenta Cris, y después hacé `echo $LD_LIBRARY_PATH`. El valor de esa variable no debería haber cambiado. Probá meter el `echo` _adentro_ del script, y vas a ver cómo primero tiene un valor, y después no.

Entonces, volvamos un poco para atrás. Lo que nosotros queremos es `export`ar la variable esa _en nuestra shell actual_, para poder ejecutar después los procesos del TP. Entonces no queremos crear un proceso nuevo: queremos que los cambios pasen en el proceso actual.

Para eso, la shell tiene otro comando: `.`, que también tiene un alias llamado `source`. Si ejecutamos el comando `.` pasándole un script (digamos, `. ./instalador`, que también se puede escribir `source ./instalador`), la shell va a abrir ese script y ejecutar cada una de las líneas que lo componen _en la shell actual_ en vez de en un proceso nuevo.

Las consecuencias de eso son un par. La primera, y más importante, es que los cambios que hagamos impactan en la sesión actual de consola. Eso es un poco lo que queríamos (que el `export` ocurra acá - probalo con el `echo`), pero puede que pasen cosas que capaz no esperábamos (por ejemplo, el cambio de directorio con `cd` antes ocurría en la sub-shell, mientras que ahora ejecutar el script hace que terminemos en un directorio distinto al que arrancamos - de nuevo: probalo).

La segunda consecuencia (que en este caso no te calienta ni un poquito, pero que difiere con lo que dice el post que linkeé) es que ahora es la shell actual la que ejecuta las instrucciones del script, entonces ni pelota al sha-bang - con `.` únicamente podemos interpretar scripts que sean válidos para la shell actual.

Nadie me preguntó, pero _si me preguntaran_, yo diría que no estoy tan, _tan_ seguro de que un script como este sea tan útil. El Mati que era cuando hice el TP hizo su script, sí. Pero el Mati que soy ahora, que vi pasar unas decenas de TPs, opina que quizá no tanto. Fijate que este script te está mezclando dos cosas: la compilación de tu TP, con el seteo de una variable de entorno.

Compilar el TP lo vas a tener que hacer, _hopefully_, una única vez durante la entrega. Clonás el repo, compilás, fiesta. En cambio, setear la variable de entorno lo vas a hacer una por consola que abras. Y, creeme: vas a abrir al menos 4 consolas durante la entrega. Así que capaz no esté tan mal separarlos.

Por otro lado, hacer un script que tiene una única línea suena medio raro. Pero después nos acordamos del embole que es tipear comandos en la VM server y, buen, un poquito deja de sernos un problema lo de que sea una línea sola. Que tampoco nos cobran los scripts, así que... ¯\\_(ツ)\_/¯

Nada, eso. Suerte que Cris es un tipo que sabe mucho y sólo tuve una cosa que corregirle, que si eran varias no me iban a alcanzar los bits para el mensaje... 🙃

¡Un abrazo, che!

* A menos que haya estado seteada desde antes, claro está.

**Comment by julisasla** [comment]
Hola, gracias por las aclaraciones y las respuestas!

Hay un par de cosas que no me quedaron claro:

Cuando corro el script que menciono cris entiendo que el make install va a compilar mi proyecto, por lo que en el caso de que abra una consola por cada modulo, debere de correr ese codigo en cada consola (si me equivoco en algo por favor corrijanme). Mismo tma. Mismo para las variables de entorno con el comando export LD_LIBRARY_PATH=etc/etc/etc, hasta este punto es lo que cris menciono

A este ultimo comando, no deberia de darle un poco mas de informacion acerca de la ruta en la cual debo configurar la variable de entorno? Como lo haria?

Y lo segundo, no me quedo claro cual seria el cambio que mencionas a este script. Pude entender masomenos la explicacion dada pero no estoy seguro de cual es el cambio que deberia hacer respecto al script mandado con anterioridad

Gracias por el tiempo 

Saludos

**Comment by mgarciaisaia** [comment]
> Cuando corro el script que menciono cris entiendo que el make install va a compilar mi proyecto, por lo que en el caso de que abra una consola por cada modulo, debere de correr ese codigo en cada consola (si me equivoco en algo por favor corrijanme).

_Compilar un programa_ significa _ejecutar un compilador que lee archivos fuente y genera un programa ejecutable_. Ese programa es un archivo que se persiste en la computadora - igual que cualquier otro programa ejecutable (tu browser, por ejemplo). Entonces, compilamos una vez, y lo podemos ejecutar tantas veces como queramos. Sólo lo tenemos que volver a compilar cuando hagamos cambios en el código fuente y queramos correr una nueva versión del programa que incluya esos cambios.

> Mismo para las variables de entorno con el comando export LD_LIBRARY_PATH=etc/etc/etc

Las variables de entorno sí son _por cada sesión de consola_, entonces vas a tener que hacer el `export` en cada consola que vayas a usar para ejecutar los procesos.

> A este ultimo comando, no deberia de darle un poco mas de informacion acerca de la ruta en la cual debo configurar la variable de entorno? Como lo haria?

No entendí esta pregunta, che. ¿Qué info le querrías pasar al comando? Cuando decís "este último comando", ¿te referís al `export`?

> Y lo segundo, no me quedo claro cual seria el cambio que mencionas a este script. Pude entender masomenos la explicacion dada pero no estoy seguro de cual es el cambio que deberia hacer respecto al script mandado con anterioridad

Es cierto, che. No quedó tan claro.

**El** cambio en _el script_ sería, básicamente, dividirlo en dos. Por esto mismo que hablamos acá arriba: compilar lo vas a hacer una vez, `export`ar las variables de entorno lo vas a hacer varias. El otro cambio grosso es en _cómo ejecutar_ el script. Ese es importantísimo. Lo de usar `.` en lugar del `./`. Eso creo que sí estaba un poco más claro en el post anterior, pero repreguntá lo que haga falta :)

¡Un abrazo!

**Comment by tferraro** [comment]
@julisasla como venís con esto? Te sirvieron las respuestas de Mati y de Cris?

**Comment by julisasla** [comment]
Me di cuenta que tenia mal las rutas, por lo que no estaba funcionando. Ademas puse el clonado de las commons en un script aparte por si las VM de la entrega ya vienen con las commons instaladas.

Pero estoy teniendo un problema para correrlo, cuando haogun make sobre la carpeta me dice: "nothing to be done for makefile".

Como podrias hacer para que lo ejecute?

Saludos

**Comment by julisasla** [comment]
Hola,

estuve revisando otros issues tambien, con esos hice hasta donde estoy ahora. Pero tengo un error el cual no puedo solucionar.

Voy a poner en contexto lo que hice asi no es una duda al aire.

Subimos al repo las carpetas Debug del TP para poder utilizar esos makefile

Este es el makefile que creo para el TP entero:

![makefile](https://user-images.githubusercontent.com/31742427/48879486-ba634c00-edea-11e8-97f5-9d5ef3f40193.png)

Este mi script con el que clono las commons (lo puse en un script aparte del resto porque tengo entendido que las VM en la entrega van a tener las commons instaladas):

![commons](https://user-images.githubusercontent.com/31742427/48879513-d961de00-edea-11e8-84a2-5ffcc6b1b7d0.png)

Este el script con el que configuro el LIBRARY_PATH:

![biblioteca](https://user-images.githubusercontent.com/31742427/48879550-057d5f00-edeb-11e8-922d-886d497227b5.png)

Y este es el script que corro para levantar el TP entero:

![levantartp](https://user-images.githubusercontent.com/31742427/48879579-1f1ea680-edeb-11e8-854a-1c4aae86cef6.png)


Lo que hice hasta ahora para poder hacerlas pruebas fue:

1. Creo la carpeta home,utnso,workspace para que el path quede /home/utnso/workspace
2. Clono mi proyecto en workspace
3. Instalo las commons con el comando **. ./commons** (siendo commons.sh el nombre del archivo donde esta el script)
4. Ejecuto el comando que levanta mi TP entero, fui muy original y llame al script levantarTP.sh y lo ejecuto haciendo **. ./levantarTP.sh**

Hasta donde tengo entendido, esto deberia de funcionar, pero me tira el siguiente error:

![tirarcomando](https://user-images.githubusercontent.com/31742427/48879728-d9aea900-edeb-11e8-96a2-79d9306b734a.png)

Probe tambien tirando un **make** en el S-AFA, por ejemplo, para ver si el makefile de la carpeta Debug del S-AFA se ejecutaba y me tira este error:

![comandoensafa](https://user-images.githubusercontent.com/31742427/48879747-f9de6800-edeb-11e8-940c-11a2c12ec9a3.png)


Perdonen lo extenso del pedido pero tengo que realizar la entrega el lunes por lo que estoy medio ansioso por resolver este tema


Mil gracias por el tiempo y espero respuesta

Saludos

**Comment by julisasla** [comment]
Entiendo, no se como corroborar si estan subidos los binaros. Que extension tienen? Donde deberian estar?

**Comment by julisasla** [comment]
saque la carpeta debug del gitignore, por lo que los binarios deberian de estar en la carpeta debug supongo

**Comment by julisasla** [comment]
Como haria para mover la referencia a un nivel inferior?

**Comment by julisasla** [comment]
Gracias por la respuesta

Me ayudarian a poder encararlo de la manera correcta?

Acorde a la primer respuesta que me dijeron, estoy usando el el export para setear las configuraciones de la shared library y haciendo un makefile del tp para poder correr el make. 

Esta mal que subas las carpetas Debug al repo para poder correr el makefile del modulo?

Estaria necesitando algun ejemplo mejor con el que basarme ya que queda todo muy abstracto

**Comment by varas-c** [comment]
Hola, como va?

Si, está mal que subas la carpeta Debug que te genera el Eclipse al
repositorio. Esa carpeta NO debes subirla. En la carpeta Debug está tu
programa compilado, por lo que si no lo subís al repo, de donde sacas el
programa compilado?

Para eso, tenes que compilar todo tu codigo fuente para obtener el
"ejecutable". Para esto, se usa un "compilador" que en éste caso será
"GCC". Entonces vos, tenes que decirle al comando "gcc" que te compile tu
codigo fuente. Fijate en la consola del lubuntu, que si escribis "gcc" te
lo va a reconocer como un comando.

Es un poco complicado "debuguear" por acá tu problema y como dice Tom,
puede ser que se extienda un montón de mensajes mas, asi que si mañana
podes acercarte a alguna sede, sería lo ideal para que lo podamos ver en
vivo y en directo.

Igualmente, cualquier otra cosa escribinos por acá.

Saludos!

**Comment by julisasla** [comment]
Gracias por la ayuda dada!!

Doy por cerrado el issue ya que no tengo ninguna otra consulta
