### ISSUE TITLE
Duda Diego Transfer Size

### ISSUE THREAD

**Issue by FranciscoII** [sisoputnfrba/foro#1244]
👋 ¡Hola!
Tenemos una duda con el Diego en la parte del transfer size. Para poner en contexto la duda, imaginen que tenemos los datos de nuestro archivo que son 10 bytes en el MDJ y el transfer size de nuestro DAM es 3 bytes y estamos ejecutando un "ABRIR". Estaria mal que cuando le hicieramos una petición al MDJ este nos devolviera (si existe el path y esta todo ok) la cantidad de bytes (en este caso 10) y dentro de nuestro DAM hagamos un malloc de esa cantidad y vayamos pasando la información a ese malloc desde MDJ de a 3 bytes?
Luego ya que tenemos ese malloc con la información podríamos hacer el pasaje a lineas (esto para poder decirle a nuestro FM9 cuantas lineas vamos a necesitar) y mandárselo al FM9 (tambien respetando el transfer size).
Saludos!

**Comment by tferraro** [comment]
Buenas!

La interfaz del MDJ queda fija dentro de las specs del enunciado, por lo que no podrían modificar validar_archivo. Ahora, porqué necesitarían la cantidad de bytes totales de un archivo? Te se ocurren otras alternativas sin modificar la interfaz del MDJ?

Tom

**Comment by FranciscoII** [comment]
Hola Tom, el tamaño lo tenemos dentro del path del archivo porque dice el tamaño y los bloques donde esta repartida esa información. No habría que modificar el funcionamiento del MDJ para tener ese dato. Lo necesitamos porque sino no sabemos cuando se termina de enviar el archivo en cuestión.

**Comment by tferraro** [comment]
Pasa que estarian modificando la interfaz del MDJ.
Me gustaría profundizar sobre el contexto en el que necesitan ese dato.
Como hacen las peticiones al MDJ?
Se me ocurren que si lo piden todo junto, van a necesitarel tamaño. Pero no
estaria jugando en contra del tranfer-size?
Se te ocurre otra modalidad que puedan usar? Podria servir, para la última
parte del archivo,  hacer lo que hace recv() (cuando devuelve menos bytes
de los que pediste).

Tom

**Comment by tferraro** [comment]
@FranciscoII que tul con esto? Pudiste resolver la duda? Se puede cerrar el issue? 👮

**Comment by FranciscoII** [comment]
Hablamos con nuestros ayudantes asignados y medio lo tenemos cocinado. Muchas gracias

**Comment by tferraro** [comment]
![image](https://user-images.githubusercontent.com/7110539/48661760-2abe4600-ea56-11e8-8abe-46c6bddd5dcb.png)

Cerrás el issue plz? 😆

**Comment by FranciscoII** [comment]
Y si no quiero?

**Comment by tferraro** [comment]
![image](https://user-images.githubusercontent.com/7110539/48661850-67d70800-ea57-11e8-860e-8ed5716a2133.png)


PD: Aunque se borre la publicación, los mails se mandan igual 😛

**Comment by FranciscoII** [comment]
Gg
