### ISSUE TITLE
FM9 - Tabla invertida de páginas y archivos

### ISSUE THREAD

**Issue by ammasotta** [sisoputnfrba/foro#1246]
Buenas, tengo una duda de como implementar la tabla invertida de páginas.
La duda viene por el lado de que un proceso puede tener varios archivos abiertos, y cada archivo puede ocupar varias páginas. El problema es cuando yo quiero hacer por ejemplo un flush, como se en que página empieza y en cual termina cada archivo?
En la segmentación paginada este problema de los archivos no está ya que puedo tener varios segmentos por proceso, pero en este caso como podría hacer para diferenciar los archivos?
Muchas gracias!
Saludos!

**Comment by tferraro** [comment]
Buenas!

Creería que estás pensando en un escenario típico de segmentación, en el que todo el segmento está junto. Entonces, cuando cambia la cosa y tenés páginas desperdigadas en varios marcos, la pregunta vendria a ser: `Como haces para ir a la siguiente página de un archivo, si solo tenés la dirección de la primera página?`

Lo que te estaría pasando acá, es que en el `offset` vos tenés implícito ese desplazamiento entre páginas.

En un esquema de Tablas de Páginas Invertidas (TPI), te faltaría hacer la conversión de esa dirección lógica a formato páginas. Es decir, tu dirección lógica es lo que tiene la CPU, apunta a la primera página. Es tarea de FM9 hacer esa conversión de la dirección lógica + el offset para ver cual es la página que debería corresponder (y de ahí sacar el marco).

Vamos a un ejemplo más práctico. Si tuviera la línea de operación: `asignar pepe.txt 3 dato`, esto terminaría siendo algo que se manda a la memoria parecido a `SET pos_mem_pepe offset soydato`, con offset=3.

Para conseguir la página, habría que hacer algo como:
`nro_página = dir_logica + (offset*TAM_MAX_LINEA) % TAM_PAGINA`
Entonces, para seguir la lógica del diagrama del enunciado (en el que esto está implícito), te quedaría:
`(SET) PID nro_página (resto[offset*TAM_MAX_LINEA, TAM_PAGINA]) datos`

Pudiste seguirme un poco con la lógica de como dividir el offset en este caso?

Tom

**Comment by Franco21198** [comment]
Buenas, yo tengo la misma pregunta, sobre _cómo saber cuando termina un archivo_ que no respondiste, creo que tu respuesta iba para otro lado.
De un archivo conocemos solamente su número de página inicial, y para obtener las siguientes, les sumamos 1. Pero un proceso puede tener varios archivos abiertos, y no hay ningún tipo de diferenciación de los mismos del lado de FM9 (ya que no dividimos los archivos en segmentos).
Entonces, para saber donde termina un archivo, deberíamos guardarnos en otra estructura, para cada proceso, una tabla que relacione un número de página inicial con su número de páginas máximo?
Saludos

**Comment by afilgueira** [comment]
Buenas, 

En un sistema real no manejas archivos de esta forma, pero si lo hacés con las diferentes partes de la imagen del proceso (código, stack, heap, datos). Cómo hace el PCB para saber dónde arranca y termina cada uno? Pensalo por ese lado.

Saludos!

**Comment by ammasotta** [comment]
Buenas!
Entonces según entendí, habría que guardar en algún lado información como la base y límite de cada archivo no?
Saludos!

**Comment by tferraro** [comment]
Tiene sentido para mi 😛

**Comment by ammasotta** [comment]
Genial! Muchas gracias!
Cierro el issue.
