### ISSUE TITLE
Pruebas bitmap en formato .bin

### ISSUE THREAD

**Issue by brendaboryszanski** [sisoputnfrba/foro#1248]
Hola! Queria consultar como hacer ya que nosotros habiamos pensado el bitmap con 010101010101. Donde 1 son los bloques ocupados y 0 los libres. En el repo de pruebas para el checkpoint 3 subido, el bitmap aparece en un formato raro. En el que no me deja abrirlo como un archivo de texto, y cuando lo abro desde el programa tampoco lo puede leer. Saben como abrir ese formato? gracias!

**Comment by AxelFulop** [comment]
Buenas , tijate con vim nombrearchivo o con cat nombrearchivo

**Comment by Franco21198** [comment]
Si querés ver los bits, usá el comando xxd -b bitmap.bin

**Comment by brendaboryszanski** [comment]
Y cómo levantaría eso? Porque fopen no me lo levanta bien en un char*

**Comment by brendaboryszanski** [comment]
Claro. Pero entonces como leería el bitmap? No entiendo como pasaría a tenerlo con el array de 1 y 0 sin el mmap

**Comment by tferraro** [comment]
Google y las commons son un buen inicio 😉
