### ISSUE TITLE
Estructura bytearray y bitmap

### ISSUE THREAD

**Issue by brendaboryszanski** [sisoputnfrba/foro#1249]
Hola. Vuelvo a abrir otro issue despues de mirar un poco la estructura de las commons Bytearray.

Por lo que entendi, mapea el contenido del archivo binario a un char*.

Paso a hacer un par de preguntas:

1) el t_bytarray lo obtengo con el bitmap_create_with_mode. Ahora, como hago para levantarlo sin pasarle los datos a guardar? Por ejemplo.. para las pruebas, me dan el bitmap creado, o mismo no quiero que cada vez que me levante el archivo yo pasarle los char* ya que siempre me lo crearia nuevo.

2)Segundo. Sin el mmap, no hay alguna forma de traerlo como lo tenia implementado yo antes? lo tenia implementado como 1010101011 y podia levantarlo todo.

3) hay una forma de recorrerlo sin el bytearray_test?

No estoy entendiendo bien la estructura creo
gracias!

**Comment by tferraro** [comment]
Buenas!

Veo un algo que no me termina de cerrar acá.
> Por lo que entendi, mapea el contenido del archivo binario a un char*.

las funciones de bitarray de las commons **no mapean nada**, solamente son un wrapper sobre un bitarray para operarlo más facil.

Como llegaste a esa conclusión? Sabiendo esto que dije, podés responder las demás preguntas?

Tom
