### ISSUE TITLE
Consulta técnica de limpieza parcial de memoria reservada

### ISSUE THREAD

**Issue by chamenwais** [sisoputnfrba/foro#1250]
Buenas noches.

Quisiera apelar al conocimiento y habilidad del grupo docente de SO, para disipar una duda acerca de algo que entiendo que podría hacer para la primitiva **Close** en el módulo de memoria **FM9**: *Se enviará a FM9 la solicitud para liberar la memoria del archivo deseado.*

Por ahora mi duda va de cara a remover todo un segmento, pero aplica perfectamente también a una página.
- Luego de haber reservado un espacio en memoria por el total indicado en el archivo de configuración, y de llenar una parte de ese espacio reservado, gracias a la aritmética de punteros, con información ¿puedo limpiar esa parte de espacio sin afectar la información que quizás haya en otro sector?
- ¿No me queda otra que pisar la información?

Ej: 
- El archivo de configuración de FM9 indica TAMANIO=512 y MAX_LINEA=32.
- Reservo la memoria por el total, y lo veo como *chars*: ```char * reserva=malloc(512);```
- Lleno parte de las primeras tres líneas ```memcpy(reserva, puntero_a_tres_lineas, 3*32);```
- Lleno parte de las siguientes dos líneas ```memcpy(reserva+(3*32), puntero_a_dos_lineas, 2*32);```
- Quiero borrar las primeras tres líneas del espacio reservado: ¿Cómo?

La duda viene por el lado que me parece mas limpio (valga la redundancia) remover la información de una parte de un sector del heap reservado, que pisarla. Es solo para saber, pisarla no me molesta en lo más mínimo.

Gracias.
Francisco Romero

Nota: Para mi pisar es colocar otra información conocida por mi, y remover es quitar información, pasando ese espacio a tener basura o Dios sabrá qué.

**Comment by tferraro** [comment]
![image](https://user-images.githubusercontent.com/7110539/48661817-debfd100-ea56-11e8-979f-9e4112eecfe7.png)
**Yo borré y cerré, pero la data, la data no se toca**


PD: En los sistemas reales que pasa?

PD2: Perdón, no me resistí al chiste 😛

**Comment by chamenwais** [comment]
Bien, la data no se toca entonces.

- *En los sistemas reales que pasa?*

En Stallings, Operating Systems: Principles and practice, 7th Ed., Chapter 7, Memory management se refiere:
- *At some point, none of the processes in memory is ready. The operating system swaps out process 2 which leaves sufficient room to load a new process, process 4. Because process 4 is smaller than process 2, another small hole is created* (Nada dice aquí, acerca de qué hizo con la info del proceso que quitó de la memoria principal, pasandola a la memoria secundaria)
- Luego en el capíttulo 8 dice: *"replacement policy", which deals with the selection of a page in main memory to be replaced when a new page must be borught in* por lo que entiendo que justamente se reemplaza la información.

Gracias por ayudarme a realizar esta conclusion.
