### ISSUE TITLE
Archivo binario

### ISSUE THREAD

**Issue by agomel** [sisoputnfrba/foro#1253]
Buenas,
Estamos queriendo leer el archivo Bitmap.bin y crear la estructura t_bitarray* de esta manera:
```
unsigned char byteArray [cantidadBloquesBitmapEnBytes() + 1];
FILE* archivoBitMap = fopen(rutaBitmap, "rb");
fread(byteArray, sizeof(byteArray), 1, archivoBitMap);
agregarBarraCero(byteArray);
return bitarray_create_with_mode(byteArray, cantidadBloquesBitmapEnBytes(), LSB_FIRST);
```
La estructura que crea esto no tiene lo que esperamos sobre el archivo Bitmap.bin(es el de las pruebas que nos pasaron)

No sabemos si el archivo que nos pasaron esta mal o si estamos leyendo mal el archivo binario.

**Comment by Franco21198** [comment]
Tienen que usar MSB_FIRST para crear el bitarray, así se llena de izquierda a derecha

**Comment by brendaboryszanski** [comment]
Con eso tambien se llena de cualquier forma. Al bitarray_create_with_mode hay que pasarle el bytearray o convertir los bytes a bits y pasarle eso? en ambos modos nos devuelve cualquier cosa

**Comment by brendaboryszanski** [comment]
Genial! era que en vez de unsigned char byteArray [cantidadBloquesBitmapEnBytes() + 1]; tenia que ser un char*
