### ISSUE TITLE
Consulta pruebas

### ISSUE THREAD

**Issue by agomel** [sisoputnfrba/foro#1254]
Buenas, al correr las pruebas del checkpoint 4 el script de prueba creaba un archivo equipo1 dentro de una carpeta equipos, pero la carpeta equipos no figura en la carpeta archivos del mnt. Tenia entendido que no debiamos crear carpetas. Tendriamos que crear la carpeta a mano nosotros o tendria que hacerlo el MDJ ?

Saludos!

**Comment by kamipalomino** [comment]
creo que eso lo tiene que hacer el MDJ por lo menos nuestro grupo lo implementó así

**Comment by tferraro** [comment]
Buenas!

Voy a arrancar con una breve introducción por la frase: `Tenia entendido que no debiamos crear carpetas.`
No tenés forma de crear directorios en la implementación de FIFA. Esto se da, porque al MDJ solo le  interesan que los archivos estén en un path.

Ahora si, el problema que tenés al momento de hacer esa implementación, es que el path corresponde a un path físico, donde si yo hiciera:
`crear /dir/pepe.txt 1` esto se mappea a algo como `/montaje/Archivos/dir/pepe.txt`.

Esto implicaría que los directorios internos que necesites para crear un nuevo path dentro de FIFA, los vas a tener que si o si crear.

Tom

**Comment by agomel** [comment]
Perdon, si sigo sin entender. 

`Esto implicaría que los directorios internos que necesites para crear un nuevo path dentro de FIFA, los vas a tener que si o si crear.`

Entonces cuando al MDJ le llegue `crear /dir/pepe.txt 1` siendo que la carpeta `dir` no exista, va a tener que el crear `dir`. 
O nosotros antes de ejecutar el tp sabiendo que se va a necesitar el directorio `dir` lo creamos a mano (desde la terminal, fuera del tp).

**Comment by tferraro** [comment]
> Entonces cuando al MDJ le llegue crear /dir/pepe.txt siendo que la carpeta dir no exista, va a tener que el crear dir.

Eso!

Uno desde un FileSystem no debería requerir trabajo manual para funcionar ante determinadas entradas del usuario, _debería soportarlo de forma automática_ no?

**Comment by agomel** [comment]
Oka, gracias!
