### ISSUE TITLE
Forma de atender peticiones del FM9

### ISSUE THREAD

**Issue by ammasotta** [sisoputnfrba/foro#1255]
Hola!
Me surgió la duda de como hay que implementar la forma de atender peticiones del FM9, de si hacerlo de forma concurrente o secuencial, ya que en el DAM y el MDJ esta específicado que tiene que ser de manera concurrente, pero en el FM9 no dice nada.
Muchas gracias!
Saludos!

**Comment by tferraro** [comment]
Buenas!

La forma de implementación del FM9 va a depender de lo que elijan ustedes como grupo. Hay muchas variantes y depende de ustedes diseñar algunas, ponderarlas, elegir finalmente una e implementarla 🙂.

Los procesos que tienen especificada parte de su interfaz o funcionamiento es para evitar soluciones atípicas que sean muy complejas, y simplificar un poco el asunto.

Les recomiendo que analicen como podrían implementar el FM9 y lo validen con su ayudante!

Tom

PD: Vale igual verlo un sábado de soporte también 😛

**Comment by ammasotta** [comment]
Muchas gracias!
