### ISSUE TITLE
Fecha de entrega 1 de diciembre

### ISSUE THREAD

**Issue by CorridoniMatias** [sisoputnfrba/foro#1257]
Buenas!

Quería preguntar si la fecha de entrega del sábado se va a ver afectada por las limitaciones que hay para moverse en la ciudad ese día: [fuente](http://www.buenosaires.gob.ar/jefedegobierno/xiii-cumbre-lideres-g20/cumbre-del-g20-sabado-1-de-diciembre).

No se si el espacio para preguntar es este pero no se me ocurrió otro lado!

Gracias, saludos!

**Comment by iago64** [comment]
Buenas buenas!
Es muy buena pregunta. La entrega se va a realizar, igual somos conscientes del problema de movilidad con lo cual vamos a tratar de asignar los horarios de forma tal que nos permita tener una tolerancia mayor en cuanto a los tiempos.

Saludos.-

**Comment by CorridoniMatias** [comment]
Genial gracias!

**Comment by AxelFulop** [comment]
acaba de salir este comunicado, parece no va a estar abierta la facu!
![whatsapp image 2018-11-27 at 19 42 42](https://user-images.githubusercontent.com/11843834/49116953-f0d31800-f27d-11e8-8b06-5c31227beb20.jpeg)

**Comment by CorridoniMatias** [comment]
Buenas, tuve que reabrir el issue por lo siguiente: https://www.frba.utn.edu.ar/comunicado-institucional-sin-actividad-del-29-de-noviembre-al-1o-de-diciembre/ :(

**Comment by afilgueira** [comment]
Gracias por el aviso. En breve comunicamos la reprogramación. Saludos!

**Comment by afilgueira** [comment]
Info subida, saludos!
