### ISSUE TITLE
Consulta enunciado Segmentacion Paginada.

### ISSUE THREAD

**Issue by FranciscoII** [sisoputnfrba/foro#1258]
👋 ¡Hola!
Tenia una duda con respecto al enunciado del FM9, más concretamente en segmentacion paginada.
Segun el TP:
"El concepto de segmentación paginada funcionará como visto en la teoría. De esta manera dicho proceso mínimamente dispondrá de las siguientes estructuras administrativas:
Tabla de Procesos
Tabla de Segmentos
Tabla de Páginas
Storage - Memoria Real
 "
El problema radica en que según Stallings, no hay ninguna tabla de procesos en la segmentacion paginada(pag 358). Además en la ilustración del enunciado, la dirección lógica que nos manda el CPU es Segmento|Offset y no termino de entender como implementar una "Tabla de Procesos" si solo me fijo en esos dos parámetros.
Por ahora lo pude implementar pero solo usando una tabla de segmentos y una tabla de paginas por segmento tal cual lo indica el Stallings.
🙇 Gracias por leerme y saludos

**Comment by tferraro** [comment]
Buenas!

La idea atrás de la segmentación paginada, es que la segmentación es un poco agnóstica de la paginación que se hace más abajo, por lo que el proceso es el mismo hubiera o no paginación.

Si solo con el Segmento+Offset no te alcanza, de donde podrías sacar la información restante?

**Comment by FranciscoII** [comment]
Hola Tom, gracias por responder. Perdón pero no entiendo a lo que te referis. Para la paginación también el cpu le pasa el PID del DTB, también se lo podria pasar a segmentacion paginada pero, no entiendo la necesidad en el contexto que lo arme yo (los segmentos del DTB se los identifica con un número que es buscado en la tabla de Segmentos, y siendo ese número único para cada escriptorio/archivo, por ejemplo, un DTB podría tener en memoria los segmentos 1,2 y 5 y otro DTB el 3 y 4).

**Comment by tferraro** [comment]
Buenas 👋 

Tené en cuenta que la denominación de cada segmento es _local a cada proceso_. Esto ocurre porque las "direcciones" de los segmentos son lógicas y no están asociadas a la posición de memoria en sí de forma directa. Esa traducción hace necesario que para entender de que segmento estás hablando, tengas que tener una "tabla de procesos" para saber a que tabla de segmentos apuntar.

**Comment by tferraro** [comment]
Buenas! Como viene esto @FranciscoII? Sigue estando la duda? Se resolvió con mi comentario? A que conclusión llegaste?

**Comment by FranciscoII** [comment]
Hola, perdón me colgué en contestarte.
Si me sirvió para entender y además que cuando me puse a hacer el "dump" me di cuenta que lo necesitaba. Esta mal si en el caso de segmentacion agrego a la tabla de segmentos el PID? Lo hago así para evitar manejar mas tablas porque estoy teniendo problemas liberándolas y no entiendo muy bien porque (estoy usando las funciones de las commons). De andar, anda igual pero no se si esta bien conceptual-mente para ustedes. Desde ya muchas gracias por la ayuda :)

**Comment by tferraro** [comment]
@FranciscoII como va todo? Te sirvió mi respuesta? Si es así, podrías decirnos a que conclusión llegaste y cerrar el issue :)?

**Comment by FranciscoII** [comment]
Hola Tom, todo pillo por ahora. Al final lo deje como lo tenia en el que en la tabla de segmentos se guarda el PID del DTB correspondiente. Para acceder a memoria el CPU le pasa el nro de segmento y el offset y la memoria busca en la tabla de segmentos el marco correspondiente. El campo de PID es utilizado solamente para el "dump" para mostrar todos los segmentos que tiene ese DTB abiertos en memoria y su contenido. Lo único que difiere un poco de la teoría es que la asignación de numero de segmento es global, por lo que un DTB puede tener asociados el segmento 1, 2 y 5 y otro el 3, 4 y 6.
La única justificación que tengo para eso es que fue lo mas practico y además es parte del funcionamiento interno de la memoria. Si esto ultimo esta bien entonces ya podríamos cerrar el issue.

**Comment by tferraro** [comment]
Buenas!

A estas alturas del cuatrimestre, que la asignación del nro de segmento sea global, _no se que tanto me preocuparía si fuera vos_, veo que hay cosas más importantes para atacar que algo que es más un detalle 😛.

**Comment by FranciscoII** [comment]
Dale, muchas gracias Tom. Cierro el issue ;)
