### ISSUE TITLE
errores bloques de las pruebas

### ISSUE THREAD

**Issue by kamipalomino** [sisoputnfrba/foro#1259]
Hola que consultarles sobre los scripts vi que actualizaron la carpeta de Archivos (de la entrega) pero los bloques sigue conteniendo cosas como: 

![captura de pantalla de 2018-11-29 12-08-28](https://user-images.githubusercontent.com/28968341/49230941-9a75ee80-f3cf-11e8-866e-a01bc5e6aee1.png)
![captura de pantalla de 2018-11-29 12-07-47](https://user-images.githubusercontent.com/28968341/49230942-9a75ee80-f3cf-11e8-9524-bcb11870efa6.png)
![captura de pantalla de 2018-11-29 12-07-19](https://user-images.githubusercontent.com/28968341/49230944-9b0e8500-f3cf-11e8-8406-55c7feaeb160.png)
![captura de pantalla de 2018-11-29 12-06-44](https://user-images.githubusercontent.com/28968341/49230945-9b0e8500-f3cf-11e8-8d4a-9e2b0a4724c6.png)

es adrede que aparezcan los nombres anteriores o falta que los actualicen?

**Comment by CMauro96** [comment]
Buenas!
Claramente cuando actualicé ayer los nombres me olvidé de este pequeño detalle. Trataremos de tenerlos actualizados lo antes posible.
Gracias por revisarlo y avisar 😃

**Comment by CMauro96** [comment]
Finalmente decidimos hacer un _rollback_ de los cambios realizados en el día de ayer. La decisión tomada se basa en que el rename de los scripts implicaba, indirectamente, rehacer completamente el FS. Este cambio, dada la cercanía a la fecha de la primer entrega, nos pareció innecesario y que podía generar inconvenientes.
@kamipalomino gracias nuevamente por avisarnos 😃 
Saludos 👋

**Comment by kamipalomino** [comment]
genial gracias :+1:
