### ISSUE TITLE
Consulta acerca del resultado esperado del MD5 en las pruebas finales

### ISSUE THREAD

**Issue by larreaf** [sisoputnfrba/foro#1260]
Buenas!
En la Prueba de Filesystem de las pruebas finales, el resultado esperado del comando md5 sobre /equipos/Rafaela es : **6cfbc91be57e33e47533cd7b5bf9df82**
Yo probé hacerlo desde la consola de nuestro mdj y, cómo el resultado era distinto, decidí crear un archivo de texto de con el contenido que debería tener Rafaela para contrastar el resultado. (En total tiene 5 saltos de línea)
![image](https://user-images.githubusercontent.com/26728292/49299644-ffe4e080-f49e-11e8-847c-d13e7c9471a5.png)
Mi duda es: ¿Está bien el resultado que figura en las pruebas? 

_Cabe aclarar que probé agregarle/sacarle saltos de línea y el resultado sigue siendo distinto. También probé hacerle un md5sum al bloque correspondiente (Rafaela me ocupaba 1 bloque) y obtuve el mismo resultado que aparece en la imagen._

**Comment by tferraro** [comment]
Buenas!

Estoy revisando y dió distinto, así que puede ser que se haya chispoteado algo 😛.

Según mis cálculos, debería ser: **a41143d13c15f6d59db85e68f9a275e7**. (ya impacté el cambio en el doc de pruebas).

Cualquier cosa nos avisan!

Tom

**Comment by Franco21198** [comment]
Tom, te olvidaste los saltos de línea al final. El md5 debería ser el que dijo más arriba

**Comment by tferraro** [comment]
Ups! Cierto que tiene 5 líneas 😜
