### ISSUE TITLE
Consulta prueba interbloqueo

### ISSUE THREAD

**Issue by Franco21198** [sisoputnfrba/foro#1261]
Buenas, realizando la parte de la última prueba de los scripts _inter.escriptorio_ y _bloqueo.escriptorio_ ocurre que los mismos no se bloquean, sino que uno finaliza antes (mientras el otro recién está realizando la op dummy), entonces al finalizar libera los semáforos que pidió, y el otro script se ejecuta sin problemas.
En mi caso, esto se podría solucionar disminuyendo el retardo en MDJ, o bien aumentando el retardo de S-AFA o de CPU, por ejemplo. Esto sería correcto? O no se podrían modificar las configs?
Saludos

**Comment by tferraro** [comment]
Buenas!

La prueba puede variar dependiendo de cada TP, dado que es lo más genérica posible.

No se precupen si tinenen que cambiar los retardos para forzar el deadlock, están para eso 🙂
