### ISSUE TITLE
Duda bloques MDJ

### ISSUE THREAD

**Issue by AxelFulop** [sisoputnfrba/foro#1262]
Buenas los bloques son algo fijo no?osea no tendriamos que crear ningun bloque, Sino utilizar Los que ustedes nos dieron y asignarlos segun cual Este libre verdad?

Gracias

**Comment by tferraro** [comment]
👋 

No te estaría siguiendo sobre que son algo fijo:
- Los bloques pueden cambiar su contenido y aumentar su tamaño hasta llegar al tamaño máximo de bloque? Si.
- Se van a incorporar más bloques? En un principio no, pero si se agrega un bloque y se cambian los archivos de Metadata/*, entonces si. Todo MDJ debe poder identificar cualquier configuración de FIFA.

Respecto a la segunda pregunta: Te puedo asegurar que no es un problema del Bitmap.bin. Pegale una reviada a varios issues dentro de este foro. Seguramente en función a lo que estás implementando, alguien se encontró con ese problema y nos puede ahorrar 10 mensajes 😛

Saludos!
