### ISSUE TITLE
Prueba Completa - Entrega Final

### ISSUE THREAD

**Issue by EzequielVargas** [sisoputnfrba/foro#1263]
Hola, cómo están?

Les escribo por una duda que nos surgió al realizar las pruebas completas para la entrega final, en particular, con los archivos _la_12.escriptorio_ y _los_borrachos.escriptorio_. El documento de pruebas especifica que luego de correr los scripts, el resultado obtenido es un nuevo archivo _resultados/superfinal.txt_ con el siguiente contenido:

_$ /resultados/superfinal.yxy
Fecha 24/11
Hora 17:00hs
Boca  1
River 2_

Sin embargo, en nuestro sistema el script _los_borrachos.escriptorio_ queda en estado Bloqueado, ya que realiza dos _wait_ sobre el recurso _segundo_tiempo_. 
Mirando los otros scripts que se deben ejecutar, no encontramos alguno que haga un _signal_ sobre el mismo recurso. Por lo tanto, el script _los_borrachos.escriptorio_ no ejecuta y no logramos llegar al archivo _superfinal.txt_ que se espera en el documento de pruebas.

Por favor, nos podrás ayudar en este punto?

Muchas gracias!!!!

**Comment by Franco21198** [comment]
_la_12.escriptorio_ hace signal al final

**Comment by EzequielVargas** [comment]
Genial!!!! No lo había visto! Vuelvo a verificar entonces! Muchas gracias :+1:
