### ISSUE TITLE
Serialización de t_list

### ISSUE THREAD

**Issue by fakukpg** [sisoputnfrba/foro#1266]
Hola, 

Estoy intentando enviar un DTB a la CPU y, al momento de serializar, no se me ocurre de que manera hacerlo con la tabla de archivos abiertos que tiene el DTB.

Mi struct es el siguiente:

typedef struct defDTB {
	int id_GDT;
	char* escriptorio; // ver si esto realmente es un char*
	int program_counter;
	int iniGDT; // 0 o 1
	t_list* tabla_dir_archivos; //tabla_dir_archivos;
	int quantum;
} t_DTB;

no tengo problemas al momento de serializar el resto de datos, pero al llegar a la t_list no se me ocurre de que manera hacerlo ya que dentro de la t_list tengo una cantidad variable de direcciones de archivos.

Pensé usar la funcion list_size() pero esa devuelve el tamaño de la lista, que entiendo es la cantidad de elementos que posee.

Podrían orientarme para donde disparar con esto?

Muchas gracias.

**Comment by fakukpg** [comment]
Para char* se calcula la cantidad de caracteres que tiene y se le suma 1 por el '/0', pero en este caso, que mi lista está formada por char* habiamos pensado en sumar las cantidades de esos para obtener el tamaño de la lista. No se si eso sería lo correcto ya que cada elemento del t_list, además de los datos, tiene un puntero al siguiente.

**Comment by iago64** [comment]
Te sirve de algo el puntero al siguiente? O simplemente con pasar los datos y despues rearmar la lista del otro lado te alcanza?

**Comment by tferraro** [comment]
Cierro el issue por inactividad! Cualquier cosa que la duda siga existiendo lo volvemos a abrir 💪
