### ISSUE TITLE
Dudas Metricas

### ISSUE THREAD

**Issue by GianCaneva** [sisoputnfrba/foro#1268]
Buenos dias, estamos teniendo algunas dudas respecto a la metrica "Tiempo de respuesta". En principio, 
-se refiere al tiempo que tarda la cpu en ejecutar un comando hasta la proxima ejecucion (por ejemplo, El tiempo desde que se ejecuto la funcion Crear hasta otra funcion  Abrir) o al tiempo en que  se encuentra el proceso en la cola de bloqueados?
-y la cantidad de sentencias ejecutadas  ser refiere a todo el camino desde NEW a EXIT o el se toma como inicio del camino EXIT desde READY?

**Comment by CMauro96** [comment]
Buenas! Cómo va? 👋 

Respecto al tiempo de respuesta del sistema, la idea es basarnos en lo que dice la teoría. Te dejo por acá una de las definiciones que se encuentra en el libro de Silberschatz:
_"...Por tanto, Otra medida es el tiempo transcurrido desde que se envia una solicitud hasta que se produce la primera respuesta. Esta medida. denominada tiempo de respuesta. es el tiempo que el proceso tarda en empezar a responder, no el tiempo que tarda en enviar a la salida toda la información de respuesta..."_

Respecto a la cantidad de sentencias ejecutadas ambas opciones son correctas dado que hay 1 métrica asociada a cuantas sentencias promedio ejecutó un escriptorio hasta llegar a la cola de Exit y otra asociada a la cantidad de sentencias que se ejecutaron mientras un DTB esperó en la cola de NEW para luego poder pasar a READY.

Espero te sirvan mis respuestas!
Saludos,
Mauro Corvaro

**Comment by tferraro** [comment]
Buenas! @GianCaneva te sirvió la respuesta de mauro? Como venís con eso?
