### ISSUE TITLE
Finalizacion de un DTB por consola

### ISSUE THREAD

**Issue by fernandosierra9** [sisoputnfrba/foro#1269]
Buenas.
  Tengo la siguiente duda , cuando por consola de safa , se pide finalizar un proceso , si este esta en ejecución supongo q esperara a q termine su ciclo pero después???
  Entiendo q mueve el DTB a finalización pero antes para liberar los recursos q se tenia abierto q se hace??
Opciones:
     1- Usa un Cpu y un ciclo para liberar los recursos a abrió?
     2- Manda msj a dam para q se encargue de liberar (menos probable por el dibujo).
     3-No se hace nada y quedo eso en memoria(fm9) y abierto en mdj
Otro es caso q puede ser q el proceso este en la cola de bloqueados/ready y se le pida terminar. 

Gracias.

**Comment by afilgueira** [comment]
Hola, a priori el enunciado no aclara cómo hacerlo. Siempre y cuando respetes la arquitectura del sistema (y finalices el proceso, devolviendo sus recursos) no hay mayores inconvenientes. En todo caso, esta es una buena pregunta para desarrollar en el coloquio.

Entiendo que 2 y 3 no deberían usarse por esto que menciono arriba.

Saludos!

**Comment by tferraro** [comment]
@fernandosierra9 como venís con eso? Te sirvió la respuesta de adro?

**Comment by julianpebe** [comment]
> Hola, a priori el enunciado no aclara cómo hacerlo. Siempre y cuando respetes la arquitectura del sistema (y finalices el proceso, devolviendo sus recursos) no hay mayores inconvenientes. En todo caso, esta es una buena pregunta para desarrollar en el coloquio.
> 
> Entiendo que 2 y 3 no deberían usarse por esto que menciono arriba.
> 
> Saludos!

Cuando arranca a describir a DAM, página 19 del TP dice:

> (...) Para esto, al ejecutarse, se conectará con los procesos S-AFA, Memoria y MDJ y quedará a la espera de futuras conexiones de CPU y/o pedidos de S-AFA. (...)

Mandar un mensaje de SAFA->DAM seguiría respetando la arquitectura?
Pregunto por el "quedará a la espera de pedidos de S-AFA".

**Comment by tferraro** [comment]
Buenas!

La Arquitectura habla que los mensajes van en una sola dirección, porque
habla del flujo normal de ejecución. Esto te restringiría poder implementar
esos mensajes? Recorda que la mayoria de las llamadas al sistema que
involucran sockets son bloqueantes.

Ahora, viendo que aportaste en los mensajes anteriores la opción (1), como
podrias desarollarla para que sea masomenos transparente? Quien deberia
dictar, a nivel de responsabilidades, que proceso hay que liberarle la
memoria y quien deberia liberarla?

Esos son interrogantes que se me ocurren que te pueden servir para poder
llegar a algun diseño masomenos copado sin meter mucha entropia en tu
sistema (a un par de días de la entrega🙂)

Saludos!
Tom

**Comment by fernandosierra9** [comment]
Hola .
Perdon q responda ahora 
Nos sirvió mucho la respuesta .
Implementamos la opcion 2 cuando preguntamos a los ayudantes el dia de soporte.
Nos dijeron q la opcion 1 y 2 eran validas, pero no habia un test q hacia eso.
gracias y cierron el issue
