### ISSUE TITLE
Prueba Completa - Tamaños incompatibles entre tamaño memoria y tamaño linea

### ISSUE THREAD

**Issue by ammasotta** [sisoputnfrba/foro#1270]
Buenas noches!
Estábamos haciendo la prueba completa y la configuración del FM9 dice:
TAMANIO=4000
MAX_LINEA=64

Puede ser que esto sea un error, y el tamaño de la memoria deba ser 4096, porque de lo contrario no habría una cantidad entera de lineas, no podrían haber 62,5 lineas de memoria según tengo entendido.
Saludos,
Augusto.

**Comment by CMauro96** [comment]
Buenas 👋 
Ante todo gracias por avisarnos del inconveniente. Si bien, deberían poder ejecutarse las pruebas aunque el tamaño total de la memoria no sea múltiplo de 64, creemos que es mejor subirlo a 4096 como propones. Acabo de actualizar el documento de pruebas con este nuevo valor.
Saludos 😄,
Mauro

**Comment by ammasotta** [comment]
Buenas!
Si bien las pruebas podían completarse igual, no me quedo claro si la idea es que siempre el tamaño de la memoria es un múltiplo del tamaño de la linea o puede pasar que los tamaños no sean múltiplos.
Saludos,
Augusto.
