### ISSUE TITLE
Comandos Consola MDJ.

### ISSUE THREAD

**Issue by FranciscoII** [sisoputnfrba/foro#1272]
¿Se puede usar la función system() para hacer algunos comandos de la consola del MDJ?
🙇 Gracias por leer.

**Comment by tferraro** [comment]
Holis 👋 

No le veo mucho inconveniente :). Lo que si, usalas a conciencia.
Recurrir a system() muchas veces es como matar un mosquito con una escopeta (y a veces el culatazo es medio fuerte y perdés más tiempo del que querías).

**Comment by tferraro** [comment]
Buenas!

El comportamiento no esta definido por el TP, elijan la opción que gusten a
criterio🙂

Tom
