### ISSUE TITLE
memory leak hilos

### ISSUE THREAD

**Issue by afondevilarevelli** [sisoputnfrba/foro#1273]
Hola, cuando corro un programa con valgrind me salta todos memory leaks en las lineas donde hago los pthread_create(...). Luego de que creo un hilo hago phread_detach() de ese hilo. Pero sigue con memory leak. Alguna solución? Gracias

**Comment by tferraro** [comment]
Buenas!

En primer lugar, necesitaríamos ver que es lo que dice valgrind 😄

**Comment by iago64** [comment]
Justamente si, van a ser muy parecidos los mensajes porque valgrind usa este estilo medio fulero.
Iguaaal, fijate que te dice algo asi como _possibly lost_ lo que no quiere decir que sea un memory leak, la papa para saber si es un leak valgrind te la tira al final, fijate de pasarnos el ultimo cachito de lo que te imprime valgrind y te ayudamos mejor.

Abrazo!
