### ISSUE TITLE
[Enunciado]Errores esperables escriptorio.

### ISSUE THREAD

**Issue by FranciscoII** [sisoputnfrba/foro#1274]
Hola, nos surgió una duda sobre el lenguaje escriptorio. ¿En cualquier caso de error esperable debemos mandar a exit el DTB asociado? O podemos ignorar algunos errores y seguir la ejecución? Desde ya muchas gracias.

**Comment by iago64** [comment]
Error -- Se va a --> Exit

No se la compliquen que faltan 24hs para la entrega.
Abrazo!
