### ISSUE TITLE
GUEST ADDITIONS: Error de instalacion

### ISSUE THREAD

**Issue by damianKreuter** [sisoputnfrba/foro#1275]
Hola gente,

Hace 1 semana que me vengo peleando con esto de instalar las guest additions pues no quiero que programar en una caja pequeña.

Mi problema es la que se vé en la imagen

https://cdn.discordapp.com/attachments/467357836494635008/554065722142097418/unknown.png

Si alguno me da una mano o ya sabe como arreglarlo que me avise que intenté por todos los medios.

La única forma que encontré de arreglarlo es actualizar la SO pero eso podría traer malas consecuencias al ser una diferente versión de la SO para el tp

PD: les paso la linea que da error, SE QUE ES UN ERROR COMUN pero todas las soluciones que vi no me funcionaron.

`VirtualBox Guest Additions: modprobe vboxsf failed`

**Comment by gastoncastineira** [comment]
Buenas!

Si bien el problema de que no te deje instalar las guest additions está, y es algo que no tenemos ningún problema de revisarlo con vos si podés traer la máquina porque a remoto tal vez sea un poco más complicado y no sabemos qué probaste y qué no, pero sí te puedo recontra asegurar que no te va a traer ninguna consecuencia actualizar la VM, así que por ese lado quedate tranquilo.

El TP se realiza en las VMs porque para el mismo se usan llamadas al sistema propias de Linux (si no sabés qué son, no te preocupes que ya lo vas a ver en la cursada y las charlas), y para que todos tengan un ambiente de desarrollo lo más similar posible para evitar problemas de compatibilidad porque uno tenga Windows, otro Mac, otro Linux, otro Android y otro labure desde su PS2 porque puede.

Cualquier duda volvé a escribir. Saludos!

**Comment by mgarciaisaia** [comment]
¡Aloha!

Como decías, sí - actualizar el sistema operativo suele ser una buena opción, pero justo justo para el caso de este trabajo práctico preferimos que no lo hagan, para que tod@s trabajen con ambientes exactamente iguales a los de la entrega final.

Descartada esa opción, nos serviría saber qué cosas probaste, para ver por qué no habrán andado, y qué cosas no volver a decirte que pruebes.

El [primer resultado de StackOverflow](https://superuser.com/questions/1268741/virtualbox-ubuntu-guest-additions-not-installing-modprobe-vboxsf-failed) es bastante variado: alguien sugiere que instales las guest additions usando el gestor de paquetes de Ubuntu, mientras que otr@s dicen que capaz estás a mitad de actualización del kernel, y entonces primero rebootees la máquina virtual para que el instalador de las guest additions detecten el kernel correcto.

Lo otro que se me ocurre que mires, para estar mil segur@s, es que tu versión de VirtualBox sea exactamente la misma que aparece en el directorio del instalador de las guest additions. Si no lo fuera, deberías desmontar el disco de las guest additions y volver a insertarlo.

Contanos cómo anduvo eso.

**Comment by jaks97** [comment]
Buenas! No se si lo solucionaste, pero dejo mi grano de arena por si otro tiene este mismo problema (al menos en VirtualBox 6.0.4):

`modprobe`, como quizás sabrás, básicamente [es un comando de Linux para cargar módulos al kernel](https://wiki.archlinux.org/index.php/Kernel_module#Manually_at_load_time_using_modprobe). El mensaje dice nada mas que falló al cargar el modulo **vboxsf** (que intuyo es para las shared folders). Pero si reiniciás la VM y ejecutas `lsmod` te va a mostrar los módulos cargados, y, al menos en mi caso, **vboxsf** si está cargado (O mas fácil, ejecutá `lsmod | grep vboxsf`). Así que, al menos suponiendo que el script de instalación no falló en otro lado, las Guest Additions están funcionando.

O bueno, hasta donde probé anda mas o menos. La redimensión de pantalla funciona medio como quiere (en mi caso, para redimensionar tengo que primero loguearme en el guest, cambiar el tamaño de la ventana, desloguearme y ahí se cambia. Pero queda así, después no cambia mas hasta el próximo reinicio).
El portapapeles compartido funciona perfecto.
Las carpetas compartidas también, pero fijate que (al menos si usas el montaje automático) tu user (utnso) va a tener que estar en el grupo **vboxsf** (simplemente, ejecutate un `sudo adduser utnso vboxsf` y después reiniciá el guest). Sino, no vas a tener permisos para acceder a esas carpetas desde el guest.
Y lo ultimo que probé, el drag and drop, que en mi caso no funciona de ninguna manera :/

**TLDR:** Si te sale ese error (`VirtualBox Guest Additions: modprobe vboxsf failed`) ignoralo, reinicia y fijate que seguro que igual las Guest Additions se instalaron bien y "funcionan".

**Comment by damianKreuter** [comment]
Hola gente de nuevo.

Perdon por no contestar, simplemente me olvidé.

De todas formas logre solucionarlo al bajar la version 5.02 de la VM (me habia bajado la 6 . Y pico y ahi daba problemas).  Ahi ya anduvo.

**Comment by JaniceFassi** [comment]
Hola!
Yo también estoy teniendo problemas. Seguí los pasos de la creación de la VM y la instalación de las guest additions y me tira la misma línea de error.

Me fijé y las versiones son las mismas.
Ejecuté lsmod y, en mi caso, vboxsf también está cargado. Si redimensiono la pantalla y luego cambio de usuario se agranda, pero cuando vuelvo a entrar a utnso se vuelve a achicar.
Me faltaría probar lo de rebootear la VM, pero necesitaría ayuda con eso.

Desde ya muchas gracias :)

**Comment by mgarciaisaia** [comment]
¡Hola @JaniceFassi!

No entendí del todo a cuáles versiones de qué cosas te referís cuando decís "las versiones son las mismas".

Cuando decís "necesitaría ayuda con eso", ¿te referís a que necesitás ayuda para rebootear? Just in case, rebootear es reiniciar la máquina. Desde la consola lo hacés con `sudo reboot`, y desde la interfaz gráfica... Buen, con el botón de reiniciar en el menú. Pero estimo que no era esa la pregunta.

Explayate un poco más, porfa :)

¡Un abrazo!

**Comment by JaniceFassi** [comment]
Con las versiones me refería a la de la VM (6.0.4) y el directorio del instalador de las guest additions. Con respecto al rebooteo no sabía que era simplemente reiniciar, creí que había que hacer algo más, de todas formas ya había probado reiniciarla.
Ahora por suerte me funcionó, no se muy bien por qué, despúes de repetirlo muchas veces. Tengo que redimensionar la pantalla, cerrar sesión y volver a entrar.
Gracias!!

**Comment by tferraro** [comment]
Como viene el resto con este tema? Lo que probó @JaniceFassi les sirvió?

**Comment by nico-abram** [comment]
Hola!

Me estuvo pasando lo mismo (Con Virtual Box 6.0.4). La version de las Guest Additions (El nombre de la carpeta en media) es la misma. Despues de reiniciar la vm el clipboard compartido anda, el redimensionar la pantalla no (Cuando cierro la sesion se redimensiona bien, pero cuando vuelvo a entrar vuelve a estar chiquita). Cuando tiro el `lsmod | grep vboxsf` que menciono  jaks97 me sale que esta.

**Comment by matiasdiaz142** [comment]
Holaaa, tengo los mismos errores, instale la ultima version del Virtual Box, y al instalar las Guest Additions me salta el error que comentan aca (el de la imagen del primer comentario). Si hay alguna solucion definitiva espero saberla (?
Hay varios amigos tambien con este tema de las Guest Additions (tmb con lo de cerrar sesion para que se redimensione). Ante todo gracias

**Comment by varas-c** [comment]
Estoy teniendo el mismo problema que todos los de este issue. 

Los pasos para 'solucionarlo' que hice fueron:
1 - Instalar las Guest Additions
2 - Reiniciar la VM (en la consola escriben sudo init 0 y listo, o lo hacen desde la interfaz grafica).
3 - Cuando la vm vuelva a iniciar, van a tener la ventana chiquita, lo que hacen es desloguearse (no apagar/reiniciar) y cuando vayan a la ventana de Login y se vuelven a loguear, la pantalla se deberia redimensionar automaticamente.

Y listo ... hasta ahora me funciono todo. El problema lo van a tener si 'apagan' la maquina virtual, porque van a tener que repetir estos mismos pasos. Para eso, no apaguen la maquina, si no que simplemente guarden el estado y carguenlo de nuevo cuando la quieren usar, y listo. Se que no es la solucion 'esperada' pero al menos asi ya pueden empezar a trabajar mas comodos en la VM. 

Lo probe con Vbox 5.2 que lo pueden bajar de aca https://www.virtualbox.org/wiki/Download_Old_Builds_5_2. Si no les funciona con la version 6, prueben con la 5.2 pero si hacen el cambio, van a tener que instalar las guest additions otra vez (montando el disco de guest additions y ejecutando el script, se da cuenta que hay una version instalada y la desistala o en todo caso le pasan el parametro uninstall asi ./[el-script] uninstall)

Cualquier cosa nos avisan!

**Comment by tferraro** [comment]
Holis! @damianKreuter te sirvió el comment de Chris? Como venís con eso? Si lograste solucionarlo, se puede cerrar el issue?

**Comment by tferraro** [comment]
Cierro el issue por inactividad! Cualquier cosa no dudes en volverlo a abrir! 😄
