### ISSUE TITLE
Buscás grupo o integrantes? Entrá acá

### ISSUE THREAD

**Issue by afilgueira** [sisoputnfrba/foro#1276]
Para unificar la "oferta y demanda" creamos este issue. Aquellos que busquen grupo y aquellos que busquen integrantes pueden publicar acá. Al hacer esto, van a quedar suscritos automáticamente a las nuevas respuestas que lleguen y centralizamos la info. Cuando la búsqueda esté cerrada, pueden borrar / editar su mensaje y desuscribirse.

Les recomendamos respetar el siguiente formato:

Busco grupo / Buscamos N integrantes
Nombre de grupo / persona
Curso
Mail o datos de contacto (opcional, esta en el perfil de github)
Comentarios
Un detalle a tener en cuenta a la hora de dejar info de contacto: este foro es público (para cualquiera con cuenta en github).

Éxitos con eso!

**Comment by ggallici** [comment]
Buscamos 1 integrante
Todavía no hay nombre de grupo (?
Cursos: K3054 y K3053
Mail: gallicig94@gmail.com
De preferencia que sea de los Martes o Miercoles como para vernos las caras en algun momento.
Saludos

**Comment by Bbaruzzini** [comment]
Buscamos 3 integrantes/Grupos al que le falten 2 personas
Nombre del grupo: todavía no fue discutido
Curso : K3052 Y K3054
Comentarios: Personas comprometidas hasta el final, somo recursantes y no queremos hacerla de nuevo por el TP. Cursamos los Miércoles y Viernes a la noche por lo que nos gustaría tratar de coincidir para poder charlar entre clases (la que cursa el Viernes no tiene problema en aparecer los Miércoles en la cursada).
Mail : brenbaru@gmail.com
Saludos

**Comment by DanielaCampiotti** [comment]
Busco grupo
Curso de lunes a la noche
mail: dacampiotti@gmail.com

**Comment by mateoBa** [comment]
Buen día, estoy buscando un grupo o compañeros para formarlo. Estoy cursando los sábados a la mañana. Mi email es mateobasaldua@gmail.com
Gracias.

**Comment by jaks97** [comment]
Somos 3 y buscamos a 2 mas para armar el grupo.
Curso: K3053 (Martes a la noche)
Mail: jkhalilsilva@gmail.com
Comentarios: No tienen que ser del mismo curso, pero estaría bueno poder coincidir. Es la primera vez que la cursamos, pero la idea es comprometernos para tratar de sacarla en este cuatri.

Saludos.

**Comment by Maldonado-J** [comment]
Somos 2, buscamos grupo
curso: k3055 sábados (tarde)
mail: maldonado.johana3@gmail.com

**Comment by isarasibar** [comment]
Somos 2 recursantes buscando completar grupo
Cursos K3013 y K3055
Mail: sarasibar.ignacio@gmail.com

**Comment by cotylopp** [comment]
Hola! Busco grupo.
Curso: Sabados a la mañana. 
Comentarios: Soy recursante y llegamos a ultimas instancias en el cuatri pasado. Tengo disponibilidad en la semana y findes para juntarnos.
cotylopp@hotmail.com

**Comment by Santiago-Lovelli** [comment]
Hola, busco grupo. 
Soy de los martes a la mañana (K3011). 
Contacto: lovelli.santiago.9@gmail.com

**Comment by GastonGalban** [comment]
Hola. Somos 4 buscando un último integrante para el grupo.
Curso: Miercoles noche
Contacto: 1541635591 o gaston.galban@gmail.com

**Comment by gebonora** [comment]
Busco grupo.
Curso: K3011 (martes mañana)
Contacto: 1531153528 o gebonora@gmail.com

**Comment by juanmaconstenla** [comment]
Buenas!

Buscamos 3 integrantes.
Somos del curso K3054 (Miércoles a la noche) así que, preferiblemente, estaríamos buscando gente del mismo curso.
Ambos somos recursantes, y estamos cursando sólo esta materia, por lo que tenemos bastante tiempo disponible para el TP y para reuniones grupales que se necesiten. Esperamos lo mismo del resto del grupo, sin importar si es la primera vez que la cursan o son recursantes.

Contacto: juanmaconstenla@gmail.com

**Comment by melaibanez** [comment]
Hola. Busco grupo. Estoy cursando los sábados en el curso K3013

Dejo mi mail: melu.poker@gmail.com

**Comment by matiasblanca** [comment]
Hola. Somos 4 personas buscando un integrante mas para formar el grupo.
Curso: Miercoles y jueves a la mañana. K3014
Contacto: 1131436344 o matiasblanca24@gmail.com

**Comment by fionalewis** [comment]
Somos 3 recursantes buscando para completar el equipo.
Cursos K3052 y K3055
Mail: fionalewisx@gmail.com

**Comment by Jonmisr** [comment]
Hola Fiona, mi nombre es Jonathan, soy recursante tambien.
Curso los lunes a la noche, queria saber si todavia no completaron el grupo.
Espero tu respuesta.
Muchas Gracias
________________________________
De: fionalewis <notifications@github.com>
Enviado: miércoles, 27 de marzo de 2019 16:07:34
Para: sisoputnfrba/foro
Cc: Jonathan Uriel; Manual
Asunto: Re: [sisoputnfrba/foro] Buscás grupo o integrantes? Entrá acá (#1276)


Somos 3 recursantes buscando para completar el equipo.
Cursos K3052 y K3055
Mail: fionalewisx@gmail.com<mailto:fionalewisx@gmail.com>

**Comment by ezelee** [comment]
Hola!

Buscamos 2 integrantes.
Somos del curso K3055 (Sábados a la tarde). 
Contacto: alecont0303@gmail.com , ezequiel.ariel.lee@gmail.com
Consideraciones a tener en cuanta: Estamos buscando gente responsable ya sea recursante o no, la cual se comprometa con las entregas / reuniones grupales y cuente con el tiempo necesario que hay que dedicarle a la materia.

**Comment by adelariestra** [comment]
Hola!
Somos del curso K3113 (Sábados a la mañana) y buscamos 3 integrantes o grupo en el que falten 2. 
Contacto: adelariestra@gmail.com, francogonzalez2303@gmail.com

**Comment by ezelee** [comment]
Hola chicos,
Al final ya se incorporó un chico al grupo y ya somos 4.
Cualquier cosa les avisamos,
Slds!

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by LucasRosende** [comment]
Hola, nos falta un integrante, estamos repartidos en los cursos de los martes a la noche (K3053), miércoles a la noche (K3054) y sábados a la tarde (K3055).
Mail: lucas.rosende@hotmail.com.ar o Wpp: 1144261176

**Comment by gabriell24** [comment]
Buenas
Estamos buscando 1 integrante,
preferentemente que curse Martes Noche(K3053) o Sábados Tarde(K3055).
Contacto: jgabriell24@hotmail.com

**Comment by contimro** [comment]
Busco grupo
Curso martes a la mañana

Mail: contimro@gmail.com

**Comment by manumaso** [comment]
Somos del curso K3055 sabados a la tarde, buscamos 1 integrante.
Contacto: manuelmaso@hotmail.com

**Comment by alanzhag** [comment]
¡Buenas!

Somos cuatro personas completamente comprometidas en aprobar el tp este cuatri y estamos buscamos un integrante más para nuestro grupo de TP. 
Tenemos una buena base técnico-profesional en desarrollo.
Si todavía no tenés grupo y querés sumarte, ¡Mandanos un mail! Respondemos al instante ya que estamos cerca del deadline para informar los grupos y no es nuestra intención hacerle perder el tiempo a nadie.

Contacto: alanzhag@hotmail.com

Saludos,

Alan.

**Comment by maticarugno** [comment]
Hola!
Buscamos 1 integrante para completar el grupo
contacto: mati.carugno@gmail.com

**Comment by AxelFurlanF** [comment]
Buenas!
Somos 4 en un grupo cursando los viernes a la noche K3051. Buscamos el último integrante, idealmente del mismo curso o cursando a la noche. Somos recursantes y queremos sacarnos esta materia _*ya*_.
Contacto: Axel.furlan95@gmail.com

**Comment by Bbaruzzini** [comment]
Hola !!
Buscamos 1 integrante para completar el grupo.
Somos del curso K3052 (Viernes a la noche) y K3054 (Miercoles a la noche). 
Contacto : brenbaru@gmail.com

**Comment by RuFlKo** [comment]
Busco grupo.
Curso: K3011 (martes mañana)
Contacto: 1169804072 o rulofk17@gmail.com

**Comment by ntaboada** [comment]
Busco grupo.
Curso: K3113 (Sabado mañana)
Contacto: 1125134779 o ntaboada93@gmail.com

**Comment by nvallejos17** [comment]
¡Buenas! Buscamos UN integrante para completar el grupo. Somos del curso K3052 del viernes a la noche.
Contacto: nacho.vallejos17@outlook.com

**Comment by RuFlKo** [comment]
Hola, curso martes a la mañana, tengo disponibilidad para reuniones grupales

El 1 abr. 2019 08:06, "Ignacio Vallejos" <notifications@github.com>
escribió:

¡Buenas! Buscamos UN integrante para completar el grupo. Somos del curso
K3052 del viernes a la noche.
Contacto: nacho.vallejos17@outlook.com

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/sisoputnfrba/foro/issues/1276#issuecomment-478535534>,
or mute the thread

**Comment by nvallejos17** [comment]
Escribime por privado al correo y charlamos.
________________________________
De: RuFlKo <notifications@github.com>
Enviado: lunes, 1 de abril de 2019 08:08
Para: sisoputnfrba/foro
Cc: Ignacio Vallejos; Comment
Asunto: Re: [sisoputnfrba/foro] Buscás grupo o integrantes? Entrá acá (#1276)

Hola, curso martes a la mañana, tengo disponibilidad para reuniones grupales

El 1 abr. 2019 08:06, "Ignacio Vallejos" <notifications@github.com>
escribió:

¡Buenas! Buscamos UN integrante para completar el grupo. Somos del curso
K3052 del viernes a la noche.
Contacto: nacho.vallejos17@outlook.com

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/sisoputnfrba/foro/issues/1276#issuecomment-478535534>,
or mute the thread

**Comment by SctBrian** [comment]
Busco grupo Responsable
Curso: K3051
mail: juankun25@gmail.com 
Curso los lunes a la noche, y voy a los workshops o seminarios los sabados.
Realmente quiero aprobar esta materia por eso, busco un equipo responsable.

**Comment by cruz636** [comment]
Buenos dias, nos falta un integrante para el grupo. 

juanbarcruz96@gmail.com

**Comment by maticarugno** [comment]
Hola, somos dos buacamos completar el grupo.
contacto: mati.carugno@gmail.com

**Comment by afviola** [comment]
Buenos dias, estamos buscando un integrante para completar el grupo. El unico requisito es que estes dispuesto a ponerle onda hasta el final de la materia.

contacto: fdviola93@gmail.com

**Comment by afviola** [comment]
> Buenos dias, estamos buscando un integrante para completar el grupo. El unico requisito es que estes dispuesto a ponerle onda hasta el final de la materia.
> 
> contacto: [fdviola93@gmail.com](mailto:fdviola93@gmail.com)

**Ya se completó el equipo**

**Comment by montenef** [comment]
Buenas, buscamos al último integrante.
K3053
contacto: franco.mtn@gmail.com

**Comment by Bbaruzzini** [comment]
Hola !!
Buscamos 1 integrante para completar el grupo.
Contacto : brenbaru@gmail.com

**Comment by lautaroh2394** [comment]
Hola, buscamos 1 integrante para completar,
lautarohaase_23@hotmail.com

**Comment by angelluisgo** [comment]
Hola, soy Angel.
Busco grupo para el TP, de preferencia que cursen los viernes por la noche.

Email: angelluisgo@gmail.com

**Comment by gonza-utn** [comment]
**BUSCO GRUPO**

Gonzalo.
gonzalo2014@gmail.com
wpp 1166548389

Curso martes a la noche con Masoero

Trabajo de 9 a 18hs como funcional (no programador)

1ra cursada de SO

Se agradece que me inviten a un grupo

Saludos.

**Comment by ezebergese** [comment]
Buenas, soy Ezequiel.
Curso los sabados a la tarde con Esquivel.
Curse la materia hace unos años y se me vencio el final. Programo hace bastante tiempo,  a alguien le falta un developer?

Laburo de lunes a viernes hasta las 18hs y vivo en Urquiza.

Saludos.

**Comment by paulorouss** [comment]
hola soy Paul 
Busco grupo
curso Sabados a la tarde
mail : rousselvasquez.96@gmail.com

**Comment by larasnr** [comment]
Buenas! Soy Lara y estoy buscando grupo
Curso por primera vez, los sábados a la tarde con Esquivel (K3055) 
Tengo muchas ganas de aprobar esta materia así que más que agradecida de que me agreguen 🙌 Saludos!
mail: larasnr@gmail.com

**Comment by mpaione** [comment]
Hola, busco grupo K3011 Martes a la mañana con Nardiello.
Saludos
marcospaione@hotmail.com

**Comment by afilgueira** [comment]
Hola, le envié un mail a toda la gente que está en el sistema de inscripciones, sin grupo.
La inscripción de grupos cerró hace dos días, con lo cual, si alguien está aún suelt@, por favor escribame a afilgueira@frba.utn.edu.ar
