### ISSUE TITLE
Pantalla en negro luego de loguearme

### ISSUE THREAD

**Issue by leoguerberg** [sisoputnfrba/foro#1277]
Buenas. Luego de loguearme en ubuntu con la contraseña de utnso, se me queda la pantalla de la vm completamente en negro, sin ningun mensaje o nada por el estilo

**Comment by leoguerberg** [comment]
Resuelto

**Comment by mgarciaisaia** [comment]
¿Cómo resolviste, che? ¿Cuál era el problema, al final?

>
