### ISSUE TITLE
No puedo actualizar la foto en la inscripccion de mi grupo

### ISSUE THREAD

**Issue by GastiV** [sisoputnfrba/foro#1278]
Hola! Durante la cursada del primer día me inscribí llenando mis datos y puse una foto provisional que encontré en el celular, la cual según el sitio de inscripciones (inscripciones.utnso) no tiene la resolución correcta pero tampoco la puedo modificar. Al intentar modificarla tira un 503 el post de la imagen. Confirmo el grupo con esa foto provisional? Si bien se nota que soy yo quizás no corresponde.

**Comment by mgarciaisaia** [comment]
Traté de mirar los logs del server pero no encontré mucho.

Si querés, mandame la foto nueva a mngi0410@gmail.com así trato de
actualizartela. Y con algo de suerte también me falla el upload y
encontramos el bug, o capaz no y buen.

Gracias por el aviso, che.

**Comment by JLaterza** [comment]
Buenas, 

Estoy en la misma situación que Gastón (una foto provisional no muy correspondiente), a lo que le sumo el caso de un compañero de grupo donde su foto no se muestra.

Podemos confirmar el grupo con dichas imágenes y luego actualizarlas (sea por la página o el medio disponible)?

Gracias y disculpen la molestia !

**Comment by mgarciaisaia** [comment]
Misma situación que Gastón: mail y a la bolsa :)

**Comment by JLaterza** [comment]
Buenas y disculpa las molestias de nuevo Matias,

Pude cambiar ambas fotos sin problemas usando otra maquina (vaya uno a saber por que).

Muchas gracias por la ayuda!

**Comment by tferraro** [comment]
@GastiV pudiste cambiar la foto? Como venis con eso?

**Comment by GastiV** [comment]
Lo solucionó mgarciaisaia. Le mandé la foto por mail!

**Comment by tferraro** [comment]
Genial! Te pido que cierres el issue entonces 😄
