### ISSUE TITLE
GUEST ADDITIONS CRASH

### ISSUE THREAD

**Issue by ncoen97** [sisoputnfrba/foro#1279]
Hola, intentando instalar las Guest Additions en la VM de lubuntu. Lo cual no tuve exito. Paso el error.
![image](https://user-images.githubusercontent.com/7952790/55193163-7058f100-5163-11e9-9c8f-3df74a653ccf.png)

Al reiniciar la pantalla sigue 800x600.

El vboxadd-setup.log dice lo siguiente.
![image](https://user-images.githubusercontent.com/7952790/55193361-f6753780-5163-11e9-83a2-5a5e646afb10.png)

**Comment by ncoen97** [comment]
Despues de reiniciar la pc, arranca 
![Screenshot_1](https://user-images.githubusercontent.com/7952790/55193811-456f9c80-5165-11e9-93d9-6bedf74f673b.png)
y dsp de logear 
![image](https://user-images.githubusercontent.com/7952790/55193845-57e9d600-5165-11e9-9e40-6027becbecad.png)

**Comment by gastoncastineira** [comment]
Tal vez el issue #1275 te ayude algo. Si no te sirve, avisá de nuevo por acá

nota: no hace falta instalar guest additions en el servidor, solo el Lubuntu
