### ISSUE TITLE
Archivos de metadata de tablas

### ISSUE THREAD

**Issue by nico-abram** [sisoputnfrba/foro#1280]
No estoy seguro si este foro es el lugar correcto para preguntas del TP mismo y no de configuracion de la vm, etc. Disculpen si no lo es.

Estoy un poco confundido con un parrafo sobre los archivos de metadata para las tablas.
El enunciado dice ("Proceso Lissandra" > "Lissandra"): 
```
Cada tabla estará representada mediante un directorio, dentro del cual se encontrarán todos los archivos metadata que correspondan a cada una de sus particiones, como también un archivo de Metadata.
```

Mi confusion esta en que dice "todos los archivos metadata que correspondan a cada una de sus particiones". Cuando habla de archivos de metadata por particion, se refiere a los temporales? En el anexo 1 muestra como que hay solo 1 archivo de Metadata.

De paso aviso por si alguien que lea esto puede editar el documento que el Anexo 1 no tiene link en el indice (Detalle sin importancia :P )

**Comment by iago64** [comment]
Buenas buenas!!
El archivo de metadata va a ser único para cada tabla, tal cual esta en el ejemplo, de hecho fijate que un poquito mas abajo en el enunciado dice:

> El archivo Metadata contendrá la información administrativa de la tabla

De ahí podías inferir que es único, de todas formas lo anotamos para fixear el enunciado ya que puede prestar a confusión y de paso tambien anoto para fixear el tema del Anexo I en el Índice.

Saludos./
