### ISSUE TITLE
Tamaño de Key

### ISSUE THREAD

**Issue by nico-abram** [sisoputnfrba/foro#1281]
¡Hola!

Queria preguntar si hay algun tamaño de Key minimo que tengamos que respetar (O, mejor, un rango de valores que si o si debe entrar, ej. [0, 255] o [-128,127]) ya que solamente lo vi definido como un "valor numerico" en la parte de Lissandra>Registro y no vi que su tamaño se defina en ningun archivo de configuracion:

```
Key: Clave numérica que identifica al registro unívocamente.
```

```
 - El Key será un campo numérico y no se proveerá una variante a esto.
```

**Comment by NaylaWinter** [comment]
Buenas!

Dentro del archivo de configuración del File System(Página 18) se encuentra el tamaño del value expresado en bytes:

![imagen](https://user-images.githubusercontent.com/31517059/55231967-da74a300-5202-11e9-87e5-1b1a68fd1f5f.png)

**Comment by nico-abram** [comment]
Buenas!

Pregunto por el tamaño de Key, no de Value.

**Comment by NaylaWinter** [comment]
Ah! Perdón, leí rápido y te contesté cualquier cosa

Para el tamaño de la Key vamos a estar usando un **uint16**.

En una próxima errata lo agregamos asi no se presta a confusión, gracias!

**Comment by chamenwais** [comment]
Buen día.

Cuando indican en el enunciado:
* _que las Keys serán de tipo **u_int16**_
* _para... las Key estaremos usando el tipo de dato **uint16**_

Se refieren precisamente al tipo de dato `uint16_t` ¿verdad?

`typedef unsigned short int	uint16_t;` que es de la biblioteca `stdint.h`.

Quizas sea trivial, pero me llevó un par de minutos encontrar un tipo de dato que compile, probando con los que explica el enunciado, considerando que también existen `int16_t`, y otros más puntuales `uint_least16_t`, `uint_fast16_t` .

**Comment by NaylaWinter** [comment]
Buenas,

Si, el tipo a utilizar es uint16_t.

**Comment by chamenwais** [comment]
¡Gracias!
