### ISSUE TITLE
Nomenclatura de criterio

### ISSUE THREAD

**Issue by nico-abram** [sisoputnfrba/foro#1282]
¡Hola!

El enunciado habla de asignar una memoria a un criterio en concreto. Seria asignar a un tipo de criterio (Tal que esa memoria quede asignada a todas las tablas con un tipo de critero), o a una "instancia" de un criterio para una tabla en particular (De manera que a lo que se le asigna la memoria es una tabla)? Me suena que lo segundo pero me gustaria estar seguro.

En caso de ser "asignar una memoria a una tabla" (Ya que la instancia de criterio seria para solo una tabla), la "nomenclatura utilizada para el parámetro [Criterio]" podria entonces ser tan solo algun identificador para la tabla?

**Comment by NaylaWinter** [comment]
Hola,

Los criterios son "globales" a todas las tablas que tengan esa consistencia, no hay instancias de criterios. Al asignar una memoria a un criterio esta quedará asignada a TODAS las tablas que tengan ese tipo de criterio.
Si vos le agregas una memoria al criterio EC entonces todas las tablas que tengan ese tipo de consistencia empezaran a poder enviarle request a esa memoria

**Comment by tferraro** [comment]
@nico-abram buenas! Te sirvió la respuesta de Nay?

**Comment by nico-abram** [comment]
Buenas!

Si, me aclaro la duda que tenias. Cierro el issue.

Gracias!
