### ISSUE TITLE
Error Instacion VM HP 64

### ISSUE THREAD

**Issue by sportel** [sisoputnfrba/foro#1284]
Hola buenas tardes, no me funciona la Maquina Virtual Instalada, se me indica el Siguiente Msj:

La aceleración por hardware VT-x/AMD-V no se encuentra en su sistema. Por lo tanto el sistema invitado de 64 bits no podrá detectar una CPU de 64 bits y no podrá iniciarse.

le doy continuar, abre la VM pero luego m emuestra el msj:
The guest is trying to switch to the PAE mode which is currently disabled by default in VirtualBox. PAE support can be enabled using the VM settings (System/Processor).

Y cierra la Aplicación.

Mi maquina es una HP – Compaq Pavilion 20-b249la All-inOne
Con procesador Intel (R) Celeron(R) CPU G1610 @ 2,60Ghz 
RAM Instalada 4,00 GB

Podrian ayudarme por favor. Desde ya muchas gracias.
Saludos

**Comment by tferraro** [comment]
Alo! Fijate si lo que hablamos hace un tiempito en #1161 viene por este lado :)

**Comment by tferraro** [comment]
Holis! Te sirvió mi comment? Como venís con eso? Si lograste solucionarlo, se puede cerrar el issue?

Saludos!

**Comment by sportel** [comment]
Hola sí ya lo solucione. Resulta que las hp vienen con la virtualización en off. Tuve que activarla desde los BIOS
