### ISSUE TITLE
Installing Guest Addittions [PROBLEMA]

### ISSUE THREAD

**Issue by YamilaOrlando** [sisoputnfrba/foro#1285]
¡Buenas gente! Pensé no iba a tener issues con las Guest Additions pero hella no, acá saltaron a hacerme la vida imposible. Primero, anduve buscando los problemas de los demás y veo qué les pasó lo mismo qué a mí, leí los dos post que hablan de lo mismo y resolví el tema del famoso error: VirtualBox Guest Additions: modprobe vboxsf failed.
PERO, al reiniciar para volver a instalar las GAs como se deben, me salta esto nuevo. No sé si considerarlo un error pero las GAs no se instalaron luego de esto y es algo muy distinto a lo que se ve en el vídeo informativo: 
![Captura](https://user-images.githubusercontent.com/22182698/55303165-f5b9fb00-541a-11e9-8163-37213be34dff.JPG)

Y esta es la virtual box qué uso;
https://imgur.com/a/exkZDxy

Dejo esto último porque quizás está mal la versión que bajé, no sé, yo seguí los links y tutos de la cátedra.
¡Saludos y gracias!

**Comment by janicead** [comment]
Tengo el mismo problema, me estoy volviendo loca

**Comment by iago64** [comment]
Buenas buenas!

Este problema lo estuvimos viendo le sábado en el receso entre la charla y el workshop y al parecer esta asociado a la version de virtual box.
Por las dudas prueben de bajar la [version 5.2 de VirtualBox](https://www.virtualbox.org/wiki/Download_Old_Builds_5_2) y confirmen si funciona.

Saludos.-

**Comment by tferraro** [comment]
:wave:

Si te fijás en la última línea, dice que se instalaron bien las guest additions 🙂.

Si tu intuición de que las guest additions no se instalaron es, porque no hay resolución full full, entonces en realidad, caiste en el bug que hablamos durante la charla del sábado (que habla dami acá, más arriba).
El bug persé es que la interacción entre Lubuntu y VBox no es del todo buena en las ultimas versiones y no hace resize de la pantalla de forma "fluida". Es decir, te obliga a o downgradear la versión de virtualbox, O **cada vez que inicies sesion** (si apagas y no guardas el estado), vas a tener que bloquear la pantalla (o cerrar sesión) y volver a loggearte. Esto ultimo fuerza a que Lubuntu reconozca el cambio de "resolución".

**Comment by tferraro** [comment]
Cris explicó un poco lo mismo, por acá: https://github.com/sisoputnfrba/foro/issues/1275#issuecomment-478191580

**Comment by YamilaOrlando** [comment]
Me bajé la versión _"VirtualBox 5.2.26 (released January 28 2019)"_, ahora... ¿Quizá está funcionando y no me doy cuenta? Instalé todo, y se repitieron los dos errores qué ya marqué antes. Vuelve a dejarme en la línea "Virtual Box Guest Additions: Starting..." ¿Así es cómo se ve mi pantalla, quizá sea cosa de mi pantalla de la pc de escritorio?
![image](https://user-images.githubusercontent.com/22182698/55339170-8d016b80-5478-11e9-9518-479145577ac3.png)

Traté de probar lo de copiar algo del host a la VM y tampoco me funcionó.

**Comment by varas-c** [comment]
Hola Yamila,

Pudiste ingresar al escritorio del Lubuntu? Si pudiste, deslogueate y volve
a ingresar con utnso/utnso (desloguear, no apagar ni reiniciar la maquina
virtual) y fijate si la pantalla aparece grande.

Lo de copar/pegar desde la maquina host y la virtual (o viceversa) es algo
que tenes que activar en las opciones del virtualBox. En el listado de
maquinas virtuales, dale click derecho a la que estes usando ->
configuracion -> tab avanzado y vas a ver las opciones de la imagen que te
adjunto. Ahi poné bidireccional para que puedas copiar y pegar desde deonde
quieras.

Avisanos si seguis con problemas.

Saludos!

**Comment by YamilaOrlando** [comment]
¡Ahora sí! ¡Muchísimas gracias, chicos! <3
![image](https://user-images.githubusercontent.com/22182698/55340557-524d0280-547b-11e9-9dcb-313c99e0c121.png)

**Comment by varas-c** [comment]
Buenísimo! Cómo lo solucionaste? Con lo que te comenté anteriormente de
desloguear/loguear?

Avisanos así les sirve a otros compañeros tuyos.

**Comment by YamilaOrlando** [comment]
Bien, en resumen es algo así: después de qué instalé todo no me funcionaba y me devolvio el mensaje de "Virtual Box Guest Additions: Starting...": Ahí al toque me dejó escribir usé el comando "sudo reboot" ,al menos dos veces creo, jaja. 
Después de eso, traté de estirarlo y no me sirvió, así que cerré sección y volví a abrir y, ahí recién la pantalla me lo resolvió. No sé si fueron los reboots o lo del login, pero bueno, por suerte arrancó. 

¡Muchas gracias! Internet te da miles de comandos para solucionarlo pero no pude con ninguno Y, comicamente, en las paginas que busqué, te recomendaban _actualizar_ tanto el VB como el Ubuntu: _por un problema tuvimos en mi grupo durante la Charla_ sé qué actualizar el Ubuntu no trae más que problemas con la librería readline, y la VB 6.0.4 tiene cierto tipo de "bug" con las VB_GAs_6.0.4.

¡Bueno, eso, saludos!

**Comment by tferraro** [comment]
Buenas! @YamilaOrlando voy a cerrar el issue, pero por favor cerrá los issues si el problema está resuelto, así podemos hacerle buena trazabilidad a tracks siguen ongoing 🙂 

Saludos!

**Comment by plbruniard** [comment]
> Buenas buenas!
> 
> Este problema lo estuvimos viendo le sábado en el receso entre la charla y el workshop y al parecer esta asociado a la version de virtual box.
> Por las dudas prueben de bajar la [version 5.2 de VirtualBox](https://www.virtualbox.org/wiki/Download_Old_Builds_5_2) y confirmen si funciona.
> 
> Saludos.-

Bajé esa version, la 5.2.42 y solucioné mis problemas que paso a contar.

Con la VMBox 6.1, cuando instalaba las guest additions, la máquina virtual nunca me devolvía control, llegaba hasta un escritorio pero no me daba el control ni me permitía login.

Bajé a a la 6.0 y, luego de instalar las guest adittions, pude tener control sobre la máquina, logeándome y ejecutando todo pero, no funcionaba el resize.

Cuando vi este issue, probé con el 5.2.42 y todo me funciona.

Muchas gracias, por su invalorable aporte.
