### ISSUE TITLE
Inicio de ejecucion de LQL

### ISSUE THREAD

**Issue by nico-abram** [sisoputnfrba/foro#1286]
¡Hola!

Leyendo la seccion del kernel, no me queda claro como inicia la ejecucion de un LQL. Hay que agregar un comando a la consola del kernel para empezar la ejecucion de un archivo lql?

Saludos.

**Comment by NaylaWinter** [comment]
Buen día!

Vamos a correrlos mediante el comando: **RUN <path>** en la consola del Kernel.  Siendo <path> la ruta del archivo LQL a correr.

Lo adjuntaremos en una nueva errata :)
