### ISSUE TITLE
Error en inscripcion de grupos

### ISSUE THREAD

**Issue by GuidoABeltrame** [sisoputnfrba/foro#1287]
Buenas, estoy intentando agregarme a nuestro grupo ya creado. Yo ya habia creado mi usuario que es GuidoABeltrame pero solo me faltaba unirme. Cuando quiero ingresar me lleva a la pantalla de alta de usuario nuevamente, pero al ingresar los datos me dice que ya se encuentra registrado y no me deja avanzar. Me podran dar una mano con eso?
<img width="583" alt="Untitled2" src="https://user-images.githubusercontent.com/38288664/55439080-e56c6200-5579-11e9-8e00-e181627a82ce.png">

gracias!

**Comment by tferraro** [comment]
Buenas!

Me dicen por la cuca que ya estás registrado bajo el usuario
*guidobeltrame.*
Fijate de loggearte con ese user!

**Comment by GuidoBeltrame** [comment]
Mala mia, estaba con la sesion iniciada en Github con el otro usuario y cuando entraba en el link de la inscricipcion no me dejaba ingresar otro.

Resuelto, Gracias!
