### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by nico-abram** [sisoputnfrba/foro#1288]
¡Hola!

Para no tener que andar abriendo y cerrando archivos, tenia pensado dejar los bloques abiertos durante todo el programa. El problema es que por default (Por lo menos en la vm) parece haber un limite de 1024 archivos que puede tener abierto un proceso (`ulimit -a` lo muestra). Me encontre con el limite probando con el archivo de configuracion de ejemplo del enunciado (5k bloques de 64 bytes) y teniendo errores con fopen, con "strerror(errno)" en "Too many open files". Ya encontre como modificarlo (En " /etc/security/limits.conf" agregando las lineas "* soft nofile 60000" y "* hard nofile 60000") pero queria saber si eso se valia (Que habria que por ahi hacerlo tambien en las compus durante la entrega) o era hacer trampa y no puedo saltearme ese limite, y tengo que andar abriendo y cerrando archivos para los bloques. 

Hay otro limite (sysctl -a | grep fs.file-max) pero ese esta en 196734 en la vm asi que no molesta.

(Lo mas raro fue que en eclipse me andaba perfecto, el error recien me salio cuando lo corri desde la terminal. No probe pero puede que con sudo no cuente el limite)

**Comment by tferraro** [comment]
Alo 👋🏻

Que cagada esto del límite che, pero guarda con cambiar los límites. Los límites existen para evitar penalizar la pérformance del kernel, dado que en linux *todo es un archivo*, ese límite afecta, sockets, archivos, etc. (ya la vamos a ver este sábado esta particularidad).

No tengo una respuesta (todavía) de que tanto querés modificar esos límites, sobretodo en la server. En un rato, cuando tenga una respuesta un poco más concreta (u otra alternativa), te comento 😛 .

Saludos!

PD: En la vm de entorno gráfico seguramente tenga otro límite por default y por eso seguramente no fallaba :) (incluso puede que eclipse esté cambiandolo en runtime). Estoy bastante seguro que el `sudo` no tiene mucho que ver.

**Comment by nico-abram** [comment]
No probe correrlo desde la vm de solo consola, solo probe de la terminial en la vm grafica. Asi que debe ser algo que esta tocando eclipse 😢

Gracias por la respuesta ultra rapida 😋

**Comment by tferraro** [comment]
Buenas! Volví.
Lo charlé un poco con los chicos y **no deberías cambiar el límite**. Nunca te va a pasar que necesites tener abiertos tantos archivos. Debería ser ondemand, o al menos tener algún pool.

Una solución que permita que estén siempre abiertos no escala y va a terminar pinchando si el tamaño del filesystem excede la cantidad de File Descriptors que puedas tener. Como son ints, te imaginarás donde está el hardlimit.

**Comment by tferraro** [comment]
Alo! Pudiste seguirme en la respuesta? Si es así, se puede cerrar el issue? Gracias!

**Comment by nico-abram** [comment]
Buenas!

Si.Cierro el issue.

Gracias!
