### ISSUE TITLE
Criterio Strong

### ISSUE THREAD

**Issue by ariel-** [sisoputnfrba/foro#1289]
Hola! Encontré un posible problema de interpretación con el enunciado:

En la parte sobre Criterio Strong Consistency dice que el mismo:
> solo dispondrá de una memoria asignada a él.​ 

Ahora bien en la parte de ejemplos se muestra que uno puede agregar memorias utilizando el comando ADD en cualquier criterio, como ser:
`ADD MEMORY 3 TO SC`

Ahora bien, que ocurre si uno intenta agregar más de una memoria al criterio strong? Está bien definido? Se pasan las "sobrantes" al SHC? Queda como backup en caso de que la asignada actualmente se caiga?

Y en el caso de que asi sea, estaría bien arrancar el kernel ya con una memoria predeterminada para el criterio sc?

**Comment by NaylaWinter** [comment]
Buen día, 

El criterio Strong consistency nomas va a utilizar una sola memoria asignada, en caso de que le quieras asignar una segunda memoria simplemente se deberá ignorar el pedido o informar el error, es indistinto.

Las memorias "que sobren" no se deben asignar al SHC, son criterios separados, para asignar al SHC debes utilizar ADD MEMORY X TO SHC.

Para los checkpoints iniciales, donde el Kernel aún no sabe utilizar el comando ADD estaría bien iniciar el criterio SC con una memoria predeterminada(la del archivo de config). Una vez que el Kernel ya "sabe" asignar memorias mediante ADD entonces deberá asignarle las memorias **A TODOS** los criterios aunque esto sea asignar solo una en el caso del criterio SC.

**Comment by ariel-** [comment]
Resuelto. Gracias!
