### ISSUE TITLE
Ayuda Ej 1 Guia de repaso de C

### ISSUE THREAD

**Issue by franpassa** [sisoputnfrba/foro#1290]
Hola gente, a ver si alguno con conocimiento de C me puede dar una mano, estuve arrancando con la guia de C como para tener idea de lo que voy a tener que saber para el TP, y me trabe en el primer ejercicio. No se porque el programa crashea cuando lo corro, el codigo buildea perfectamente y Eclipse no me marca ningun error. Es el ejercicio 1, les dejo el enunciado. Gracias!

Enunciado:

Ejercicio 1 (Básico de C)

Realizar las siguientes funciones (revisar qué funciones de Ansi C nos pueden ayudar):
/* 
*   Retorna un String nuevo que es la concatenación
*   de los dos Strings pasados por parámetro
*   Ejemplo:
*   char* nombre = "Ritchie";
*   char* saludo = string_concat("Hola ", nombre);
*   =>
*   saludo = "Hola Ritchie"
*/
char* string_concat(const char*, const char*);

![image](https://user-images.githubusercontent.com/48684467/55592034-9fe09e00-570d-11e9-8bc8-e25887fe3150.png)

**Comment by mgarciaisaia** [comment]
¡Aloha!

Que tu programa compile _es un comienzo_, pero de ahí a que sea correcto y libre de errores hay un largo camino. En particular, cuando se habla de que C no es un lenguaje seguro se habla de esto - de que no es tan difícil hacer un programa que compile pero no funcione.

La primer herramienta que tenés para atacar este problema es el debugger. El debugger te permite correr tu programa paso a paso, dándote la posibilidad de inspeccionar su estado a lo largo de la ejecución, y con un poquito de suerte eso te ayuda a encontrar dónde y por qué está fallando.

No tengo a mano ningún link para compartirte (aunque quiero creer que algo tenemos que tener), pero probá de debuggear el código a ver si entendés algo más sobre tu problema. Vos mirás, buscás, entendés un poco más, y nos preguntás otro poco, y nosotros validamos lo que entendiste y te guiamos para que des un paso más - ese es nuestro contrato.

Te leo :)

**Comment by rcomesan** [comment]
Hola. 

Te recomiendo leer la documentación de strcat acá: http://man7.org/linux/man-pages/man3/strcat.3.html

Una de las cosas que menciona es que el argumento dest (puntero a char) tiene que ser un buffer con suficiente espacio para contener ambas strings concatenadas (y ésto incluye el null-char final).

Independientemente de esto, estás pasando una string literal a strcat en el parámetro dest que no es constante (lo cual implica una posible modificación del argumento que le envíes) y esto es ilegal. Hacé de cuenta que una string literal es una especie de constante guardada en algún lugar fijo de tu memoria al cual solo tenés acceso de lectura.

El código es sintácticamente correcto por eso compila independientemente de su funcionamiento, pero de todas formas el compilador debería generarte una warning porque estas enviando un argumento constante a un parámetro de función que no tiene el calificador const.

**Comment by SofiCortes** [comment]
Hola @franpassa!

Ya hiciste el ejercicio del [TP0](https://www.utnso.com/workshop-de-tp0-1c2019/)? Es una buena manera de arrancar con lo que vas a necesitar para el TP (ojo, con los ejercicios que agarraste está perfecto - seguí así - pero el workshop está bien guiado si estás dando tus primeros pasos). Además, ahí explicamos como usar el debugger (herramienta que mencionó mgarciaisaia antes).

También está buenísimo lo que comenta @rcomesan. Leer la documentación de las funciones también es una práctica que vas a necesitar seguido.

**Comment by franpassa** [comment]
Hola!! Gracias a todos por contestar. Utilizando el debugger, me di cuenta que el programa crashea especificamente al usar la funcion strcat. Revisando la documentacion verifique lo que dijo @rcomesan. El tema es que no entiendo bien como aplicar bien el calificador const. Segun la documentacion seria asi: char *strcat(char *dest, const char *src); Y me trae un par de dudas, primero, entiendo que "desc" se refiere a puntero a char, pero "src" que seria?. Dejo la prueba que hice que sigue tirando el mismo error en el mismo lugar. Puede ser que tenga que usar malloc en algun lado junto con free? Y si es asi, como lo implemento?

![image](https://user-images.githubusercontent.com/48684467/55645349-b985f200-57ae-11e9-8b95-735752b4058e.png)

![image](https://user-images.githubusercontent.com/48684467/55645300-99eec980-57ae-11e9-93a2-76d2a3faf3fb.png)

**Comment by franpassa** [comment]
> Hola @franpassa!
> 
> Ya hiciste el ejercicio del [TP0](https://www.utnso.com/workshop-de-tp0-1c2019/)? Es una buena manera de arrancar con lo que vas a necesitar para el TP (ojo, con los ejercicios que agarraste está perfecto - seguí así - pero el workshop está bien guiado si estás dando tus primeros pasos). Además, ahí explicamos como usar el debugger (herramienta que mencionó mgarciaisaia antes).
> 
> También está buenísimo lo que comenta @rcomesan. Leer la documentación de las funciones también es una práctica que vas a necesitar seguido.

Si! Ya hice el tp0, lo hice en clase el sabado pasado, me faltaria ver las otras resoluciones que subieron nada mas.

**Comment by varas-c** [comment]
Buenas, cómo va?

 Como bien decis, en la documentación de la funcion "strcat", te va a decir
que está declarada de esta forma: char *strcat(char *dest, const char *src);

El primer parametro hace referencia a "destino" (destination) y el segundo
hace referencia a "fuente" (source). Basicamente lo que está intentando
decir es que la funcion va a ir de "fuente a destino". En este caso, como
es la funcion strcat, va a concatenar lo que está en "fuente" en "destino".

Un ejemplo basico sería pasar como 'destino' "hola" y como 'fuente' "
Fran". El resultado que querés obtener es [destino][fuente] o sea "hola
Fran"...Hasta ahí sería el uso básico de la funcion strcat.

Pero por qué está pinchando entonces?

El problema es que, como bien comentaba un compañero más arriba, el primer
parámetro (destino) tiene que tener "espacio suficiente" para poder alojar
(además de sí mismo) lo que "fuente" le quiere pasar. Un ejemplo rapido de
ver es intentar hacer esto: int numero =
999999999999999999999999999999999999999;

Ese numero gigante no entra en un int porque "no le da el espacio". Lo malo
de éste caso es que no podemos hacer nada para que entre en un int por
cuestiones de arquitectura y etc pero en tú caso SÍ que podemos hacer algo.

Según lo que pasaste, éste es tu codigo:

   - char* nombre = "Ritchie";
   - char* saludo = string_concat("Hola ", nombre);

Vemos que estas intentando pasar "nombre" a "Hola ". En este caso, esto NO
va a funcionar porque los literales cadenas (el primer parametro que estás
pasando) son de solo lectura, no podes modificarlo ni mucho menos agregarle
mas caracteres.

Una posible "casi solución" sería hacer:

   - char* nombre = "Ritchie"
   - char* hola = "Hola ";
   - char* saludo = string_concat(hola, nombre);

Esto sigue sin funcionar porque el puntero "hola" apunta a un literal
cadena y no se pueden modificar .... pero bueno, estamos más cerca.

Otra casi solución un poco mejor que la anterior ...

   - char* nombre = "Ritchie"
   - char* hola = //Sistema operativo por favor, dame memoria suficiente
   como para almacenar "Hola Ritchie" mas el fin de cadena
   - strcpy(hola, "Hola");

   //En mi puntero "hola" tengo espacio suficiente para almacenar "Hola
   Ritchie" porque el sistema operativo fue bueno y me dio espacio
   //Y yo despues copie en ese espacio "vacio" la cadena "Hola" pero por
   suerte todavia me sobra espacio

   - char* saludo = string_concat(hola, nombre);

              //y ahora al intentar copiar nombre en hola, SI va a
funcionar porque tengo espacio! El sistema operativo me lo dio antes :D

Se entendió? Te dejo una pista mas:
https://www.tutorialspoint.com/c_standard_library/c_function_malloc.htm

Cualquier cosa que no te salga, avisanos!

**Comment by franpassa** [comment]
Ya pudeee!!! Excelente, me vino bien para entender el manejo de la memoria dinamica, gracias a todos!!

**Comment by SofiCortes** [comment]
Si ya pudiste solucionarlo, acordate de cerrar el issue @franpassa :)
