### ISSUE TITLE
Posible inconsistencia en la memoria

### ISSUE THREAD

**Issue by nico-abram** [sisoputnfrba/foro#1291]
¡Hola!

Me quedo una duda respecto a la operatoria de la memoria:
Que pasa si nos llega un insert de una tabla que no existe en el fs, y luego un Select de la misma?

Por lo que entiendo del enunciado, si la memoria todavía no hizo journal al momento del Select, devolvería el dato "invalido" de la tabla inexistente (ya que (1) cuando un insert no encuentra segmento lo crea, y (2) cuando un Select encuentra la key no le pregunta al fs). Es correcta está interpretación? Hay que hacer algo para manejar este caso o está "bien" que se de esta inconsistencia?

Saludos y gracias de antemano.

**Comment by nahuelm** [comment]
Hola @nico-abram!! 

Es correcta la interpretación. No se debe manejar este caso, se devolvería el valor "invalido" hasta que la memoria realice su Journal y dicho valor sea eliminado de la misma.

Saludos. Nahuel.

**Comment by nico-abram** [comment]
Hola!

Gracias! Cierro el issue.

Saludos

**Comment by SofiCortes** [comment]
Buenas @nico-abram!

Te recomiendo que pases por el issue #1305, porque la operación de insert va a cambiar en la próxima errata. Por lo tanto, el caso que charlamos acá en este issue no sería un escenario posible.

Perdón las molestias!
Saludos
