### ISSUE TITLE
ERROR: MULTIPLE DEFINITIONS OF

### ISSUE THREAD

**Issue by damianKreuter** [sisoputnfrba/foro#1292]
Gente

Tengo un problema que nunca habia visto antes y me esta rompiendo las pelotas demasiado. Envio esta iasue por cel, mas tarde envio codigo en cuando llegue a la pc

Al compilar el programa, me tira un error que hay "multiples intancias de" una funcion. Tanto los mains de los 3 modulos como las 50 funciones de la biblioteca que estamos que la reutilizamos de cuatris anteriores.

Es raro porque no se como solucionarlo. 

Se me ocurrio la idea de borrar todo el proyecto para luego crearlo de nuevo todo pero aun no lo probe

**Comment by nico-abram** [comment]
Buenas!
Intenta separar el código en headers (.h) y el código con las definiciones/implementación (.c).

Después incluí solo los .h desde otros archivos (Con los prototipos/declaraciones de las funciones). Y asegurate de ponerles "guardas" (Si te fijas en los .h del tp0, es el patrón de del #ifndef #define #endif ) o el equivalente "#pragma once" (https://es.m.wikipedia.org/wiki/Pragma_once , en la parte de ventajas y desventajas hay un ejemplo con #ifndef etc)

El problema es que está compilando más de una vez la misma cosa. Con esas directiva del preproocesador haces que solo lo vea una vez.

Saludos!

**Comment by damianKreuter** [comment]
Vale, en cuanto llegue a casa me fijo eso

**Comment by ivigilante** [comment]
Buenas esto va a solucionar el tema de la biblioteca pero no el de los mains porque eso es del makefile. Yo estoy teniendo el problema del main. Pudiste solucionar eso?

**Comment by ivigilante** [comment]
#1027 
Dejo este issue donde plantean una manera de arrancar el TP, con esto solucioné mi problema del makefile de tener varios main().

**Comment by IvanDL95** [comment]
Esto me trae una pregunta a mí que no sirve para resolver esto pero es acerca de lo mismo porque estaba intentando ver si podía lograr algo.

C no soportaba múltiples definiciones? Lo que sería sobrecarga de funciones, yo declaro dos funciones iguales, pero que reciban distintos tipos como argumento (ambas de la misma cantidad de parámetros y devuelven lo mismo).

Estoy seguro que en C++ se podía hacer algo parecido, pero no recuerdo si se puede hacer C o directamente no se puede hacer.

**Comment by varas-c** [comment]
Buenas,

Respecto a lo que comenta Ivan, no, C no soporta sobrecarga de funciones
(function overloading). En C++ como bien comenta, sí se puede, pero en C no.

Respecto al autor del issue, pudiste solucionar tu inconveniente? Avisanos
para darte una mano en caso de que no hayas podido.

Saludos!

**Comment by tferraro** [comment]
Buenas! Cierro el issue por inactividad. Cualquier cosa que el issue persista, volvelo a abrir sin problemas :D
