### ISSUE TITLE
Problema desconocido con Guest Additions

### ISSUE THREAD

**Issue by gonza-utn** [sisoputnfrba/foro#1293]
Hola buenos días, ni bien trato de comenzar a instalar Guest Additions siguiendo el siguiente tutorial
https://www.youtube.com/watch?v=G3rFKfyoQEs&feature=youtu.be
me topo con este problema al darle clic a Dispositivos -> "insertar imagen de CD de las Guest Additions"

![image](https://user-images.githubusercontent.com/22229647/55671159-4e4a2780-5863-11e9-849a-e355afa2304f.png)

Desde ya muchas gracias
Saludos.
Gonzalo.

**Comment by tferraro** [comment]
Buenas!

Fijate si te sirve lo que dice este vago por stackoverflow: https://askubuntu.com/a/960324

**Comment by Santiago-Lovelli** [comment]
Hola, a mi me pasaba lo mismo. Lo intente solucionar pero me salta esto
![image](https://user-images.githubusercontent.com/40477288/55925598-65cb3c80-5be4-11e9-9ce1-38f5f4a0cf21.png)

estos son los archivos que tengo dentro de /media/utnso/
![image](https://user-images.githubusercontent.com/40477288/55925699-c65a7980-5be4-11e9-9a07-96c6870a092d.png)

**Comment by ivigilante** [comment]
Hola, yo tuve que pasarme entrar como root para poder correr todo bien, con sudo no me funciono 
Es escribir en la terminal
sudo su
Y te va a pedir contraseña. 
Una vez ingresada, debería aparecerte en vez de utnso@pathdondeestes
root@pathdondeeste

**Comment by Santiago-Lovelli** [comment]
Ya me sirve, al cerrar sesión cambia de tamaño, pero no cambia una vez abierta (si esta maximizada la pantalla en el momento de iniciar se adapta a ese tamaño, pero si minimizo queda en tamaño maximizado, no se ajusta al nuevo tamaño. Ni abriendo consola u otros programas)
![image](https://user-images.githubusercontent.com/40477288/55965884-ce9acf00-5c4d-11e9-99c1-44edc3b31f3c.png)

**Comment by tferraro** [comment]
Me dicen por la cuca que esto se parece a algo que charlamos por acá: https://github.com/sisoputnfrba/foro/issues/1285#issuecomment-478628384

Por otro lado, guarda con usar `sudo su`, traten solamente de usar `sudo <comando>`, pero no cambiar a root

**Comment by tferraro** [comment]
@gonza-utn fueron útiles las respuestas? Si pudiste solucionar el inconveniente, plz cerrá el issue comentando cual fue la solucion entre todas! 😄

**Comment by mgarciaisaia** [comment]
👋 ¡Hola!

Vengo a comentar que este issue habla del siguiente error de VirtualBox:

```
Could not mount the media/drive 'C:\Program Files\Oracle\VirtualBox/VBoxGuestAdditions.iso' (VERR_PDM_MEDIA_LOCKED)
```

Dejo el texto escrito acá para que el buscador de Github pueda encontrarlo en el futuro, y no sigamos duplicando issues sobre este tema.
