### ISSUE TITLE
Problema intentando levantar el archivo de configuración

### ISSUE THREAD

**Issue by Dragonflares** [sisoputnfrba/foro#1294]
Buenos días

Hace un par de días empecé a setear las configuraciones y el cómo levantarlas, usando un path absoluto y creé una consola básica y una función en main que la levanta y le asigna un hilo. 

![imagen](https://user-images.githubusercontent.com/28828524/55685311-fbd43e00-592a-11e9-9bcb-451489db4d17.png)

En un principio cuando ejecutaba pensé que no estaba funcionando la consola, ya que siempre tiraba "terminated" cuando ejecutaba el programa. Resulta que ayer lo vi con un ayudante usando el modo debug, y el problema resultó ser otro:

![imagen](https://user-images.githubusercontent.com/28828524/55685449-ccbecc00-592c-11e9-91aa-e21f27d8ac1d.png)

Al llegar a este paso el programa se termina con el error "Archivo de configuración no encontrado". Como se ve bien en el logger de Lissandra: 

![imagen](https://user-images.githubusercontent.com/28828524/55686371-c59cbb80-5936-11e9-9868-66cab6306c2d.png)

![imagen](https://user-images.githubusercontent.com/28828524/55685469-0f80a400-592d-11e9-8871-c4b96ffe4425.png)

Y también el correspondiente strtol. Luego se probó usando una dirección relativa, cambiando a que el Lissandra.cfg se levantara así, y el mismo error. Creamos 3 copias del .cfg, una en al carpeta de Debug, otra en la de Debug/src, y la original dentor del primer src. para ver si cambiando donde estaba el .cfg cambiaba algo, y nada. Ninguna de las 3 rutas levantó. Y siempre murió le programa ahí. 

![imagen](https://user-images.githubusercontent.com/28828524/55685567-4efbc000-592e-11e9-91bf-1e3f2eaeaf11.png)

Pero siempre la ruta la encontraba, y la ponía correctamente

![imagen](https://user-images.githubusercontent.com/28828524/55685577-6470ea00-592e-11e9-8693-d604ebcd68b5.png)

_Y la ruta no es incorrecta en ningún momento_
¿Alguna idea?

**Comment by gastoncastineira** [comment]
Buenas!

En principio voy a hacer una pregunta básica porque no lo estaría viendo en las capturas que pasaste. ¿Estás usando config_create para iniciar ese t_config?

Nota aparte: Ojo con los strdup que te pueden generar leaks. Podés pasarles el string como si nada a una función y anda igual, no hace falta setearlo en variables

**Comment by nico-abram** [comment]
Buenas!

Puede ser que lo esté buscando en la carpeta de todo el repo, o en LissandraFileSystem cuando usas un path relativo? Si mal no recuerdo eclipse toquetea cosas para que el current working directory sea el del proyecto (el de más afuera en el explorer de la izquierda adentro de eclipse).

Saludos.

**Comment by Dragonflares** [comment]
Buenas, al final era que el archivo de configuración tenía espacios, no se si no los habia visto antes, pero bueno, el tema está resuelto, Muchas gracias
