### ISSUE TITLE
Software Updater

### ISSUE THREAD

**Issue by mpaione** [sisoputnfrba/foro#1295]
Hola, alguna recomendación sobre ejecutar o no el software update en las VMs provistas por la cátedra?

Gracias

**Comment by gastoncastineira** [comment]
A diferencia de lo que dije hace unos posts, como cátedra no recomendamos actualizarlas. 
Podría pasar que en una actualización cambie alguna biblioteca que usemos y haga que después el código no te compile en la entrega, además que tratamos que todos tengan las VMs lo más similares posibles para evitar problemas de compatibilidad

No te olvides de cerrar el issue si te contentó mi respuesta!

**Comment by mpaione** [comment]
> A diferencia de lo que dije hace unos posts, como cátedra no recomendamos actualizarlas.
> Podría pasar que en una actualización cambie alguna biblioteca que usemos y haga que después el código no te compile en la entrega, además que tratamos que todos tengan las VMs lo más similares posibles para evitar problemas de compatibilidad
> No te olvides de cerrar el issue si te contentó mi respuesta!

Perfecto, gracias.
