### ISSUE TITLE
[DUDA] Seleccion de memoria

### ISSUE THREAD

**Issue by GastiV** [sisoputnfrba/foro#1296]
Buenas! Con mi grupo tenemos una duda sobre los criterios de consistencia.

Al recibir una request el kernel, éste debe planificar a qué memoria se la debe asignar teniendo en cuenta el criterio de la tabla asociada en la request. Cómo sabe el kernel, a la hora de recibir la request, qué criterio tiene la tabla y si existe la misma, ya que eso se comprueba en la memoria y en tal caso en el file system? En otras palabras, habría que hacer dos consultas a la memoria por cada request: una para saber el criterio de la tabla solicitada y a partir de éste, poder planificar a qué memoria del pool asignársela? En caso de que haya que consultar el criterio en una request aparte, ¿a qué memoria se le asigna esa consulta? ¿A una random o bajo una determinada especificación?

**Comment by NaylaWinter** [comment]
Buen día,

Por cada pedido al Kernel este solo debe realizar **1** request a memoria. Para saber la consistencia de las tablas cada cierto tiempo configurado por archivo de configuración vamos a estar haciendo un DESCRIBE global a alguna memoria que tenga conectada(es indistinto a cual). 
Con este DESCRIBE global vamos a estar siempre actualizando el Kernel en los nuevos cambios que se hayan realizado sobre la metadata de las tablas.

En caso de que llegue un pedido sobre una tabla de la cual el Kernel no tiene conocimiento, debido a que en el DESCRIBE anterior no apareció, entonces simplemente asumirá que esa tabla no existe y el pedido no podrá realizarse.

**Comment by GastiV** [comment]
No me había quedado claro, gracias!
