### ISSUE TITLE
[DUDA] Métricas

### ISSUE THREAD

**Issue by avaromatias** [sisoputnfrba/foro#1297]
Para mostrar las métricas por pantalla: ¿Va a existir un comando “MÉTRICAS”? ¿Éste debería pertenecer a la API del Kernel? La consigna especifica que la API no debe ser alterada (motivo de desaprobación) y en la charla se dijo que se debía mostrar con un comando por consola.

**Comment by SofiCortes** [comment]
Hola! Si, va a existir ese comando. En la próxima errata lo vamos a estar agregando en el enunciado.

**Comment by SofiCortes** [comment]
Si esto resuelve tu consulta, no te olvides de cerrar el issue!
