### ISSUE TITLE
Duda respecto al archivo metadata de FS

### ISSUE THREAD

**Issue by AxelFulop** [sisoputnfrba/foro#1298]
Buenas noches como va?
Leyendo detalladamente la parte del fs tengo dudas respecto  al metadata,en el enunciado se menciona dos veces, por lo que entendi cada tabla va a tener un archivo metadata el cual va a ser unico para cada tabla como  ejemplo:
mnt/LISSANDRA_FS/tablas/tablaA/MetadataA.txt
mnt/LISSANDRA_FS/tablas/tablab/MetadataB.txt 
y asi para cada tabla del fs?
y otra cosa distinta el el Metadata.bin unico del fs no?

diganme si estoy en lo correcto, muchas gracis

**Comment by NaylaWinter** [comment]
@AxelFulop te estabamos por contestar y justo cerraste el issue!

Quedo clara la duda? Sino sin drama te contestamos :)

**Comment by AxelFulop** [comment]
Sisi, justo me crucé ayer con un ayudante ayer a la noche en campus y me aclaro la duda, muchas gracias!
