### ISSUE TITLE
Duda de operatora de sentencia Create de memoria

### ISSUE THREAD

**Issue by chamenwais** [sisoputnfrba/foro#1299]
Hola.

Leyendo la descripción de la operatoria ante un INSERT en la memoria veo, resaltado, que la memoria no tiene que guardar metadata de las tablas de Lissandra, ni verifica su existencia.

Pero luego, en la descripción de CREATE, dice que en caso de que la tabla se cree exitosamente, la memoria debe agregar a su lista de tablas administrativas dicho dato.

A mi criterio suena como una contradicción, ya que por un lado nos piden no guardar estado de existencia de tablas, y por otro nos piden que guardemos el estado de que una tabla ahora existe en nuestro sistema, pero puedo estar equivocado.

¿A qué se refieren con "agregar a su lista de Tablas administrativas (de la memoria) dicho dato (la creación exitosa de una tabla)?

Gracias
Francisco Romero

**Comment by NaylaWinter** [comment]
Buen día Francisco,

Como decís vos es una contradicción, nos quedo desactualizado el enunciado con respecto a un cambio que hicimos.

En conclusión: las memorias **NO** mantienen metadata ni tablas administrativas de las tablas.
Frente a un CREATE no deben agregar esta nueva tabla a ninguna tabla administrativa.

Gracias por notarlo, vamos a corregirlo para una próxima errata

**Comment by chamenwais** [comment]
A vos Nayla.
