### ISSUE TITLE
Memtable dividido por tablas

### ISSUE THREAD

**Issue by AxelFurlanF** [sisoputnfrba/foro#1300]
Hola chicos!

Tenemos una duda con respecto a esta nota de página:
_El área de “memtable” deberá estar dividido por tablas_.

A qué se refiere con eso? Nosotros entendemos que la memtable es volátil, ergo, queremos alocar memoria de la máquina que ejecute el LFS.
Estamos pensando en armar una lista enlazada donde tenga los campos de lo que se quiere insertar (`timestamp, key, value`) y un id al siguiente registro. Estaría bien eso?

Saludos,

**Comment by NaylaWinter** [comment]
Buen día, 

Nos referimos a que dentro de la Memtable debes conocer a qué tabla pertenece cada uno de los INSERTS que se vayan realizando, para luego poder hacer el dump sobre el directorio de ESA tabla. En otras palabras, cada "TABLA" debe tener un espacio asignado en la Memtable.

Una opción para poder tener los distintos INSERTS podría ser una lista enlazada. 
Lo que tienen que pensar ahora es cómo hacer para adaptar ese ejemplo para soportar INSERTS de múltiples tablas y luego los dumps a los directorios correspondientes

**Comment by cmedrano** [comment]
Buen día,

Podría ser una lista de listas? donde los nodos de la primera lista me define la tabla y luego de cada nodo sale un puntero a los nodos de la otra lista que tendría los inserts de cada tabla.
De esta manera la búsqueda de un valor de una tabla sería mas rápido

Gracias

**Comment by nahuelm** [comment]
Hola @cmedrano 

Dicha implementación forma parte de la definición interna de cada equipo. Dicho esto, si la misma cumple y satisface todos los requerimientos del trabajo práctico, es correcta.

Saludos.

**Comment by NaylaWinter** [comment]
Buenas,
Si la duda ya esta resuelta les pido si pueden cerrar el issue, sino si nos pueden indicar la pregunta asi les contestamos
