### ISSUE TITLE
Tengo problema con cambiar la imagen de Usuario para Inscrpcion de grupos de sistemas operativo 

### ISSUE THREAD

**Issue by paulorouss** [sisoputnfrba/foro#1301]
👋 ¡Hola!

Ojalá el foro te sea de ayuda. Para agilizar las cosas para tod@s, te pedimos un par de
cosas antes de que hagas una nueva pregunta:

- [ ] 🔍 ¡Buscá! Acá arriba hay un "Search" que te permite buscar consultas que hayan
hecho antes tus compañer@s. Quizá ya encontrás la respuesta servida.
- [ ] 📝 ¡Se detallad@! Si no encontraste tu respuesta, se tan clar@ y detallad@ en tu
pregunta como puedas. Tratá de contar qué hacés, qué observás, y qué entendés a partir
de eso - ¡pero sin mezclarlas!
- [ ] 📹 ¡Mirá cómo reportar desde Eclipse! Si tu problema es con código en Eclipse,
mirá el video [Cómo reportar errores desde Eclipse](https://youtu.be/18cN8Jk4WjQ) para
tener todos los detalles que necesitamos.

🙇 Gracias por leernos, y ¡éxitos!

**Comment by NaylaWinter** [comment]
@paulorouss perdón pero no entiendo lo que comentaste sobre el issue.
Podrías darnos mas información sobre el problema?

**Comment by iago64** [comment]
Paul, como va?

Creo que entendi tu problema, si queres, mandanos a la casilla de inscripciones la foto y aclaranos que necesitas cambiarla y vemos de hacerlo.

Abrazo!

**Comment by tferraro** [comment]
@paulorouss mandáste el email a inscripciones@utnso.com? Se solucionó el inconveniente?
Si es así, no te olvides de cerrar el issue 😉

**Comment by iago64** [comment]
@paulorouss por favor no te olvides de mandarnos la foto para cambiarla en el sistema de inscripciones.

**Comment by paulorouss** [comment]
Hola envié la foto a inscripciones para el cambio en el sistema de inscripciones pero no recibí respuesta

**Comment by tferraro** [comment]
Puede ser que *hayamos* tenido problemas con esa casilla en estos días. ~Y cuando digo puede, quiere decir que posta algunos mails no llegaban.~

Nos hacés la gauchada de mandarlo a tferraro@frba.utn.edu.ar? Así tomo el punto de asegurarme de que se haga el cambio 🙂 

Y mil disculpas por la colgada che :/

**Comment by tferraro** [comment]
Listo el cambio!
