### ISSUE TITLE
Git siempre me pide usuario y contraseña de github

### ISSUE THREAD

**Issue by GastiV** [sisoputnfrba/foro#1302]
Buenas! Ya me estuvo hinchando un poco que cada vez que quiero hacer un pull o un push tenga que poner usuario y contraseña. Probé generando un key ssh en la VM y agregandola a mis claves en github pero no funcionó. Existe alguna solución? Quizás hice algo mal.
Me pareció haber visto algo de esto en utnso pero no logré encontrar nada. Hay alguna solución a esto?

**Comment by tferraro** [comment]
Buenas!

Siempre te va a pedir contraseñas si clonaste el repo como https. Chusmeate la docu que da github: https://help.github.com/en/articles/which-remote-url-should-i-use

Deberías configurar tu key y bajarlo usando ssh, sino no tenes alternativa más que usar la pass, son repos privados 🤷‍♂️

**Comment by mgarciaisaia** [comment]
No recuerdo la versión de git que tiene la VM, pero probablemente puedas
habilitar el credential helper para que cachee el password:
https://help.github.com/en/articles/caching-your-github-password-in-git

Para fijar el user, cloná el repo metiendo el usuario en la URL. Onda, `git
clone https://usuario@github.com/sisoputnfrba/turepo`. O hacé `git help
remote` para ver cómo cambiarle la URL (`set-url`?).

**Comment by tferraro** [comment]
@GastiV Te sirvieron las respuestas? Contanos que onda, y si se solucionó, no dudes en cerrar el issue 😉

**Comment by GastiV** [comment]
Cloné el repo con ssh y ya no me pidió las credenciales. Gracias!

**Comment by brunmans** [comment]
Hola soy nuevo en esto pero me gustaria saber como hiciste para clonar con ssh. saludos

**Comment by mgarciaisaia** [comment]
@brunmans [acá](https://help.github.com/es/github/using-git/which-remote-url-should-i-use#cloning-with-ssh-urls) hay algo de info, con la traducción bastante menos que a medias.

Pero probablemente te sea más sencillo probar el [credential helper](https://help.github.com/es/github/using-git/caching-your-github-password-in-git).

**Comment by JFEDERALwhoame** [comment]
A mi me pide esto para descargar packtermux.git 

Username for 'https://github.com': 
Password for 'https://:
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/3xploit666/packtermux.packtermux.git/'
$ git clone https://github.com/3xploit666/packtermux.packtermux.git
Cloning into 'packtermux.packtermux'...
Username for 'https://github.com': |

**Comment by FelipeAsenjo** [comment]
Hola a todos, se que llego un poco tarde, pero estaba buscando la respuesta a este problema y me puse a revisar la documentacion.

Asumiendo que ya tienen sus llaves publica y privada --> introdujeron la SSH publica en su repositorio de Github (setting --> SSH and GPG heys) --> y ya definieron el origin en su repo local para generar la conexion... Lo unico que falta para que no te pida la contraseña de manera repetitiva cada vez que haces push o pull es:

1) revisar que el ssh-agent este corriendo con el siguiente comando: "eval $(ssh-agent -s)" 
Si les devuelve el numero de proceso (PID), esta funcionando el ssh-agent y pueden aplicar la siguiente solucion

2) Añadir la clave SSH privada al SSH-agent con el siguiente comando: "ssh-add { la-ruta-de-su-llave-privada }",
normalmente la ruta es algo como "~/.ssh/id_rsa", y listo, no tienen que poner de manera recurrente su contraseña

**Comment by santiago1699** [comment]
**Hola** que tal con la nueva implementación de los token, al pedirme la clave cada vez que quiero hacer un pull o un push, como puedo hacer para que al menos me pida la clave de mi github y no tener que andar poniendo el token a cada rato, o como puedo hacer con las nuevas actualizaciones para directamente no poner claves?

**Comment by mgarciaisaia** [comment]
¡Aloha!

Una opción es usar el credential helper que mantiene las credenciales en caché durante un rato para que no te pida el token todo el tiempo. Pero igual es un poco un plomo.

Lo más cómodo me parece que sería que generes una clave de SSH con una passphrase más o menos sencilla de recordar y tipear, y que hagas las operaciones de git via SSH en lugar de HTTPs.

También podés usar el credential helper que guarda tu access token en disco, pero sería la versión menos segura de las 3 (si alguien obtiene ese archivo, puede iniciar sesión en tu nombre en Github).

**Comment by dario1091** [comment]
Tuve el mismo problema original 
lo que hice fue copiar el link de clonar con ssh 
eliminar el remote de mi repositorio y agregarlo de nuevo pero con la url de ssh

en el repo 

`git remote -v `
eso lista todos los remotes 

`git remote rm origin `
elimine el viejo 

`git remote add linkssh `

y listo

**Comment by mgarciaisaia** [comment]
Sí, eso funciona. Al último comando le falta un parámetro, que es cómo
llamar al remote ese. Lo más común es que quieras hacer `git remote add
origin <url de ssh>`.

Esto también implica que hayas creado una clave privada de SSH, la tengas
disponible en esa máquina (es decir, en la VM), y que la tengas asociada a
tu cuenta de Github.

**Comment by piterguardian** [comment]
hola que tal ayuda con scrip de ddos

**Comment by oneksson** [comment]
thank you @mgarciaisaia

**Comment by AndresMCardenas** [comment]
a mi nada de eso me funciona, tengo la llave ssh creada y agregada a mi cuenta, siempre clono desde ssh y aun asi todo el tiempo me pide la frase de confirmación.

**Comment by mgarciaisaia** [comment]
@AndresMCardenas Si tu clave de SSH está protegida con una passphrase, podés revisar la configuración de tu SSH Agent para ver con qué frecuencia te la volverá a pedir.

Podés empezar a leer al respecto en [este artículo de documentación de Github](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) - el proceso depende bastante de tu configuración local.

**Comment by EliabHdez** [comment]
> ¡Aloha!
> 
> Una opción es usar el credential helper que mantiene las credenciales en caché durante un rato para que no te pida el token todo el tiempo. Pero igual es un poco un plomo.
> 
> Lo más cómodo me parece que sería que generes una clave de SSH con una passphrase más o menos sencilla de recordar y tipear, y que hagas las operaciones de git via SSH en lugar de HTTPs.
> 
> También podés usar el credential helper que guarda tu access token en disco, pero sería la versión menos segura de las 3 (si alguien obtiene ese archivo, puede iniciar sesión en tu nombre en Github).

Como se hace eso de la segunda opción que comentas? Tengo una clave SSH con la passphrase, pero me sigue pidiendo el token en lugar de la passphrase, como le hago para que me pida esta última en lugar del token??? Y que es eso de hacer las operaciones de git vía SSH en lugar de hacerlas HTTPs???

**Comment by mgarciaisaia** [comment]
Si tenés la [clave pública asociada a tu usuario de Github](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account), deberías [usar la URL de SSH para clonar el repo](https://docs.github.com/en/authentication/troubleshooting-ssh/using-ssh-over-the-https-port).

**Comment by cachilo22** [comment]
> Cloné el repo con ssh y ya no me pidió las credenciales. ¡Gracias!

Me dirías cómo hicistes?? Gracias

**Comment by cachilo22** [comment]
Me dirías cómo hicistes?? Gracias

**Comment by GastiV** [comment]
@cachilo22 leé los comentarios que explican bien!
