### ISSUE TITLE
Kernel - Conocer las memorias que existen

### ISSUE THREAD

**Issue by cmedrano** [sisoputnfrba/foro#1303]
Buen día,

Tengo entendido que el Kernel conoce la cantidad de memorias que existen en el sistema debido a que el mismo va preguntando a la memoria que se conecto por primera vez por archivo de configuración, que memorias estan disponibles.

Mi duda es el tiempo que cada tanto va preguntando el Kernel a la memoria para conocer las memorias disponibles, ese tiempo lo obtenemos por archivo de configuración? porque no lo veo en el tp.
Entiendo que se va ejecutar automáticamente cada cierta cantidad de tiempo y no esta la posibilidad de que el usuario invoque algún comando para que ejecute eso, estoy en lo correcto?

El kernel tiene que mandar siempre a la misma memoria para saber los datos de las memorias o puede enviarle a cualquier otra  memoria? entiendo que solo a la que se conecto por primera vez pero quería validarlo.

Si el comando add lo hace el usuario por la consola del kernel, entonces antes tendría que haber un comando por la consola del Kernel que te responda las memorias que están sin agregar a algún criterio como para que luego el usuario pueda conocer las memorias?

Muchas gracias
Saludos

**Comment by NaylaWinter** [comment]
Buenas,

Inicialmente el Kernel debe preguntarle a la memoria que conoce por archivo de configuración quiénes estan disponibles dentro del pool. Una vez que esta se lo indica y el Kernel arma su "tabla de gossiping" con todas las memorias que existen entonces en el siguiente proceso de gossiping ya puede preguntarle a cualquier memoria quiénes conforman el pool, puede ser o no la del archivo de configuración.

Por consola no hay ningún comando para forzar el gossiping y este se va a dar cada cierto tiempo el cual se indica por archivo de configuración mediante el campo "RETARDO_GOSSIPING" en la Memoria. 

No hace falta tener ningún comando que muestre cuáles son las memorias sin asociar a ningún criterio. Quien levante las memorias(en el checkpoint o en las entregas finales) va a saber cuales memorias levantó y cuales ya asignó.

Cualquier cosa que no se haya entendido decime

**Comment by fighthawkarg** [comment]
Ya puede preguntarle a cualquier memoria quiénes conforman el pool, **puede ser o no la del archivo de configuración.**

Okey, entonces kernel además de la "tabla de gossiping" recibe también de memoria el valor de Retardo de Gossiping. Para así kernel saber en que tiempo iterar nuevamente lo de gossiping?

(En el enunciado en la tabla de ejemplo esta como Tiempo de Gossiping y en el ejemplo de tiempo de configuración como RETARDO_GOSSIPING...)

**Comment by NaylaWinter** [comment]
Buenas,

Es decisión de la implementación de cada equipo cómo quieren manejar el retardo gossiping en el Kernel.  Algunas opciones son: que el Kernel pregunte todo el tiempo si el retardo cambio, agregar el campo "RETARDO_GOSSIPING" también al archivo de configuración del Kernel o que el Kernel sea informado si el retardo cambio, entre otras.

En el enunciado intentamos que la tabla de ejemplo tenga un nombre significativo de lo que representa ese campo, mientras que en el ejemplo simplemente damos una forma de poder "nombrar" ese campo, como equipo pueden modificar estos nombres.

**Comment by cmedrano** [comment]
Muchas gracias

**Comment by chamenwais** [comment]
Buen día.

A mi me quedan dudas con la frase que se explica en la sección Ciclo de ejecución, luego de indicar cómo el kernel participa en el gossiping: "el kernel... utilizará el comando ADD para asociar dichas memorias a los distintos criterios".

Dado que el comando ADD es parte de la interfaz del mismo kernel:
¿Quiere decir que el kernel debería autoejecutarse un comando de su consola?

Si yo dibujo un diagrama de secuencia para explicar cómo el kernel asocia memorias con criterios: 
¿La primer línea sale del usuario? ¿del proceso kernel? ¿O ambos?

Gracias

**Comment by NaylaWinter** [comment]
Buenas,

No, el Kernel **no autoejecuta el comando ADD**. 
El ADD es utilizado manualmente por el usuario en la consola del Kernel para ir asociando memorias a los distintos criterios. Luego cuando el Kernel este en el ciclo de ejecución utilizará cada criterio con las memorias que ya previamente se asignaron, no se va agregando nuevas durante la ejecución de una linea.

**Comment by chamenwais** [comment]
Ahh. Perfecto, era lo razonable.
Al estar algo difusa la redacción de esa parte del enunciado, quería corroborar.

Gracias.

Pd: Como yo no abrí este issue, no lo puedo cerrar. Lo va a tener que hacer el amigo Cristian Medrano o algún moderador.
