### ISSUE TITLE
Duda enunciado: Datos en archivos de bloques...? -  FS

### ISSUE THREAD

**Issue by daimaidana** [sisoputnfrba/foro#1304]
Hola! Cómo va?
Necesito sacarme unas dudas con respecto a esto de los bloques, que no me termina de cerrar. 

En los archivos que no son metadata, dentro de una tabla se sabe que estan los:
     _**Blocks: es un array de números que contiene el orden de los archivos en donde se encuentran los datos propiamente dichos de ese archivo.**_
Esto se refiere al que el array tiene los nros de bloques, en donde estan los datos de ese archivo, no? 
O sea, un bloque puede guardar nada más que un dato. o me equivoco?? 

Estoy segura que es asi, porque tendria sentido el uso de bitarrays que todavia no sé como usar pero tengo algo de idea. Peeeero me confunde esto..
En  el paso 5 del CREATE dice:
_**Crear los archivos binarios asociados a cada partición de la tabla y asignar a cada uno un bloque**_
Ahi pareciera que una particion al asociarse con un bloque, este guardaria varios datos... 

Me re serviria si me pueden orientar con esto. Gracias!!

**Comment by Zheoden** [comment]
Buenas!! Como estas?

El file system esta dividido en bloques, y cada bloque tiene un tamaño fijo, por ende cada bloque va a poder almacenar tantos "datos" como ese tamaño lo indique. Es decir, si un timestamp;key;value ocupa 20 bytes y tus bloques son de 64 bytes todavía podes almacenar 44 bytes más, una vez completo este bloque, si la partición lo requiere (y todavía hay bloques disponibles) se le asigna un nuevo bloque.

De todas formas te comento, dado que no quedo muy claro el tema del file system, estamos trabajando en una errata para aclarar esto.

En caso de que queden dudas, por favor hacémelo saber!!

Saludos!

**Comment by daimaidana** [comment]
Bien, genial entonces... Porque me estaban dando vueltas ciertas definiciones en el enunciado. Más que nada estas, que redondean en lo mismo pero te las detallo:
1) Definir el contenido de **Blocks** de los archivos no-metadatas. (No me lo definiste en tu rta :P)
2) Con qué criterio digo que un bloque está ocupado con 1, o libre con 0 (Para los bitarrays). Ya que guardan varios datos, a lo mejor nunca llego a "Llenar" un bloque por completo. 
3) El paso 5 del CREATE. Es un bloque por particion?
4) Los ultimos pasos de la compactación... Que tambien tienen que ver, pero a lo mejor sacandome las 3 dudas anterior ya lo entiendo, o no jajja No lo puedo terminar de cerrar. 
Las cito por si las queres tener a mano..

> Bloquear la tabla para cualquier operación sobre la misma.
> Liberar los bloques que contengan el archivo “.tmpc”
> Liberar los bloques que contengan el archivo “.bin”
> Solicitar los bloques necesarios para el nuevo archivo “.bin”
> Grabar los datos en el nuevo archivo “.bin"
> Desbloquear la tabla y dejar un registro de cuánto tiempo estuvo bloqueada la tabla para realizar esta > operatoria.

A lo mejor en la nueva errata me solucionan estas dudas, muchas gracias desde ya! 👍

**Comment by Zheoden** [comment]
Buenas!!!

1) Los archivos Blocks van a tener los datos efectivos, es decir los bloques van a tener los timestamp;key;value.

2)Con el bitarray se indican los bloques libres. Y si, si los llegas a llenar por completo. Mira el siguiente ejemplo con bloques de 64 bytes:
El archivo partición 0.bin va a contener: 
Size=13
Block=[40]
El archivo bloque 40.bin va a contener:
30;18348;Azul

A su vez, los bloques se pueden llevar y tus timestamp;key;value quedar partidos en distintos bloques, como en el siguiente ejemplo:
El archivo partición 0.bin va a contener:
Size=79
Block=[1,37]
El archivo bloque 1.bin va a contener:
30;0;Vayne
65;3;Elise
86;6;Braum
2;9;Garen
1;12;Yasuo
7;15;Sivir
5;18
Y el archivo bloque 37.bin va a contener:
;Zoe
42;21;Annie

Entonces, en los archivos de partición vas a tener un size (que indica el tamaño real del archivo) y una lista de bloques, que van a almacenar el contenido real del archivo.

3) Correcto, va a ser un bloque por partición, tal como indique en el ejemplo pasado, los bloques son de cada partición.

4)Básicamente lo que te pide la compactacion, es leer los bloques de los tmpc, y de los bin, cuando tenes todo internamente en el FS y realizas la compactacion, liberas los bloques de los archivos .tmp y .bin, y volves a crear el .bin con el nuevo tamaño (liberar los bloques seria cambiando el bitarray).

De esto trata la errata. Pero si quedan dudas no esperes a que se publique, pregunta nuevamente por acá!!!!

Saludos!!

**Comment by daimaidana** [comment]
Ultra clarisimo!!! Muchas gracias!!

**Comment by daimaidana** [comment]
Consulta, en el ejemplo de 1.bin pusiste 63 datos, por que?? Pregunta a lo mejor media obvia, pero me la quiero sacar... tiene que ver con el EOF? O es mas segun la implementación de cada uno en la forma que guarde los datos?  Gracias!

**Comment by NaylaWinter** [comment]
@daimaidana si ya esta resuelta la consulta te pido si podes cerrar el issue y sino comentarnos lo que seguís con duda

**Comment by rcomesan** [comment]
@Zheoden disculpá que te moleste, tu explicación fue sumamente clara pero me surgió una duda: Puedo permitirme dejar algunos bytes sin utilizar al final de cada bloque de forma de evitar tener key;value;timestamps partidos o va en contra del TP? 

Eso simplificaría la implementación del binary search que estoy haciendo para buscar keys dentro de los distintos bloques sin revisarlos todos.

Otra alternativa simple podría ser cargar directamente el archivo completo en memoria (cargando cada uno de los bloques que lo forman) pero eso va a depender del tamaño/volumen de datos que maneje la tabla (desconocido).

**Comment by Zheoden** [comment]
Buenas!!

No, de ninguna manera podes dejar bloques sin completar. Para pedir otro bloque SI o SI tenes que tener el anterior completo.
Sobre cargar todo a memoria, depende de que quieras realizar, en caso de estar haciendo la compactacion no me parece mal, ahora, si estamos hablando de un select va a ser un poco engorroso hacer eso. Te invito a que pienses algún otro enfoque para tu algoritmo y que cualquier duda de como encararlo habla con tus ayudantes

**Comment by rcomesan** [comment]
Muchas gracias por la aclaración. No hay otro enfoque, o haces una búsqueda linear a lo pavote (ya sea cargando todo de una o por chunks bloque a bloque) o haces un binary search como estoy haciendo aprovechando que los dumps los hago yo y preproceso lo que estoy dumpeando (ordeno y elimino duplicados).

Casi siempre va a terminar quedando el último bloque incompleto porque lo que se guarda no necesariamente es de tamaño n * blockSize.. pero bueno habrá que controlar el caso de records partidos en los extremos para cumplir con el tp.

**Comment by NaylaWinter** [comment]
Buenas @rcomesan esta resuelta la duda? En todo caso te pido si podes cerrar el issue, sino volver a consultar lo que no te haya quedado claro

**Comment by rcomesan** [comment]
Gracias @NaylaWinter, cierren, ya está todo claro. No tengo forma de cerrarlo yo porque no es mío el issue.
