### ISSUE TITLE
Duda de sentencia INSERT en Kernel

### ISSUE THREAD

**Issue by ariel-** [sisoputnfrba/foro#1305]
Hola, me surgió una duda al leer el enunciado v1.2, que quizás no vi antes:

- En la parte sobre la sentencia INSERT en el Kernel, se dice que cuando dicha sentencia "produzca un fallo en el File System debido a un drop previo de la tabla afectada, se debe informar dicho error (...)"

Ahora bien, el problema surge de leer que el INSERT cuando es recibido por el Kernel, se lo envía al módulo memoria que corresponda al criterio asociado a la tabla especificada; pero cuando se lee la parte sobre INSERT en memoria, se especifica claramente que "**la memoria no verifica la existencia de las tablas al momento de insertar nuevos valores**" siendo que "en ningún momento hace una solicitud directa al FileSystem"

Por lo tanto la consulta es: Si la memoria no accede al FS para hacer el insert, y el Kernel se comunica sólo con la memoria... ¿Cómo hace para conocer el error de que la tabla fue dropeada previamente?

**Comment by NaylaWinter** [comment]
Buen día,
Gracias por notarlo, lo vamos a estar corrigiendo en una próxima errata.

Ante un INSERT el Kernel simplemente verificará la existencia de la tabla contra la metadata que conoce. Si dentro de esa metadata encuentra la tabla entonces realizará la operación correctamente., en caso de que no encuentre la tabla dentro de la metadata es que vamos a informar el error

**Comment by tferraro** [comment]
@ariel- te sirvió la respuesta de Nay? Se solucionó la duda? Si es así, recordá cerrar el issue :D

**Comment by ariel-** [comment]
Perfecto. Interpreté que al tener que modificar el enunciado, se iba a cerrar cuando publicaran la errata. En ese caso lo cierro, gracias!
