### ISSUE TITLE
Error al clonar el repositorio del TP

### ISSUE THREAD

**Issue by Nachiin** [sisoputnfrba/foro#1307]
Hola,
Tengo un problema al clonar el proyecto del repositorio del tp. Me salen  los siguientes errorres

![error al clonar](https://user-images.githubusercontent.com/48870904/56085006-a1e3e480-5e12-11e9-9795-39afa7a7db90.JPG)

**Comment by mgarciaisaia** [comment]
¡Aloha!

Mirá cómo se ve tu pregunta en mi celu:

![Screenshot_2019-04-13-18-01-28-377_com google android gm](https://user-images.githubusercontent.com/1190974/56085276-d9549000-5e16-11e9-89a8-9644225cd9b5.png)

Y, una vez que baje la imagen, después tengo que escribir a mano el texto de tu error para poder buscar algo. Multiplicado por cada persona que lee tu post y tenga intenciones de ayudar - un bardo, ¿no?

Copiemos los mensajes de error como texto, mejor, porfa. Haciendo eso, le simplificás el laburo a la persona que quiera ayudarte - y hay menos chances de que alguien que estaba dudando entre ayudarte o no decida hacer otra cosa, en cambio.

-----

Habiéndo resuelto lo de gritarle a las nubes, la pregunta.

¿Buscaste el mensaje de error ese en la Internet?

[En StackOverflow](https://stackoverflow.com/q/20370294) dan dos respuestas distintas, y ambas correctas. La primera dice que te falta settear el proxy en la configuración de git. La segunda dice que volvió a probar más tarde, y anduvo.

El error que tenés es `cannot resolve domain github.com`. En criollo, git te dice que no sabe quién es github.com, lo que habla de problemas de conectividad. Lo causa más probable es que la VM no tenga Internet. Abrí un browser en la VM y fíjate si te podés conectar a algún sitio. Si no anda, buscá por acá los issues preguntando por cómo configurar la red de la VM.

Si tenés la red configurada en modo bridge y estás trabajando en una notebook, es probable que hayas cambiado de red desde que prendiste la VM y tengas que reiniciar la conexión. O, si estabas en el laburo, o un McDonald's o alguna cosa así, capaz posta necesites configurar un proxy en la VM - o cambiar la interfaz de red a modo NAT, que capaz te ahorra laburo.

Pero, buen, la base es que no te está andando bien la conectividad en la VM.

Probá y contanos qué onda.

¡Un abrazo!
