### ISSUE TITLE
Consulta de memoria

### ISSUE THREAD

**Issue by mesaglio** [sisoputnfrba/foro#1308]
En el enunciado dice en el apartado de memoria: "Cada segmento estará identificado por el path de la tabla a la cual pertenece".
Ese path es el que tiene el LFS?? De ser así, se podría ejemplificar?

**Comment by damianKreuter** [comment]
Me uno al post

Supongo que si o al menos tener el nombre de la tabla y ese nombre de la tabla debe estar como atributo de la estructura SEGMENTO. 

Para mi esta al reverendo pedo que Memoria sepa a donde van a estar los archivos y las tablas, eso es trabajo de Filesystem. 

Vos le envias a FS las tablas y de que tabla pertenece, despues de ahi Lisandra hara lo que tenga que hacer porque es su trabajo, saber donde estan esas tablas, no el de memoria.

**Comment by NaylaWinter** [comment]
Buenas,

Efectivamente, es el path que tiene la tabla dentro del LFS. Un ejemplo: /mnt/FS_LISSANDRA/Tables/Tabla1/

**Comment by NaylaWinter** [comment]
@mesaglio @damianKreuter si ya quedo resuelta la duda les pido si pueden cerrar el issue, en caso contrario si nos pueden decir qué es lo que no quedo claro
