### ISSUE TITLE
Archivo Lissandra Query Language

### ISSUE THREAD

**Issue by lucasnvp** [sisoputnfrba/foro#1309]
Hola, leyendo la parte del Kernel para parsear un archivo LQL, tenemos las dudas: 

- de si las operaciones a parsear son todas las del file system ( Select, Insert, Create, Describe, Drop ) o solo algunas. 

- En el caso del Insert, el timestamp puede ser optativo? o siempre va a estar. 

- si el script tiene un `DROP tabla1` y luego `SELECT tabla1 3` se debe validar antes de ejecutar o lanzamos el error en tiempo de ejecución?

Muchas gracias.

Saludos.

**Comment by damianKreuter** [comment]
Pasar Timestamp como parametro de insert es optativo, sin embargo una vez en memoria es Memoria el que debe ponerselo si no lo tiene.

**Comment by damianKreuter** [comment]
Respecto a tu pregunta del drop y el select. 

Depende a que criterio se asocio la tabla.

Caso CS y CHS si o si se debe borrar la tabla antes de que se lea.

Caso EC, ahi da igual, si lo lee y bueno, fue mas rapido el select

**Comment by NaylaWinter** [comment]
Buenas,

1. El Kernel debe parsear todas las request que encuentre dentro del archivo LQL. Después de cada una hará lo que necesite hacer o simplemente la delegará.

2. Dado que el Kernel le redirige todas las request a la Memoria entonces la sintaxis de la sentencia INSERT sera **sin** timestamp, al igual que es en memoria. Tanto por si llega por Kernel o por Memoria será la Memoria quien le ponga el timestamp, el Kernel no se lo pone.

3. El kernel no debe "pre-analizar" el script que va a correr. De hecho simplemente va a agarrar cada una de las request(SELECT, INSERT, CREATE, DESCRIBE y DROP) y las va a redirigir a la Memoria elegida

**Comment by lucasnvp** [comment]
Gracias. Cierro el issue.
