### ISSUE TITLE
Tamaño máximo nombre tabla

### ISSUE THREAD

**Issue by matiasBusco** [sisoputnfrba/foro#1310]
Buenos días, para todo el resto de las cosas veo que tenemos tamaños maximos configurados, pero en el caso de los nombres de las tablas no encontré un tamaño máximo para su nombre, tenemos uno?

Mil gracias por la ayuda y perdonen si ya estaba respondida

**Comment by NaylaWinter** [comment]
Hola,

No es necesario tener un tamaño máximo para ese caso.

**Comment by matiasBusco** [comment]
Entonces como hago para esperar en cada uno de los procesos cual es el tamaño maximo del request que me vana  enviar?

**Comment by matiasBusco** [comment]
Porque por ahora estamos haciendo todo lo posible para que la comunicacion entre los procesos sea del tipo char* para que en caso de que quieran probarlo con un netcat pueda probarse y entre en el curso del programa
Como caso contrario podemos armar un pequeño proceso cliente que parsee el mensaje y meta todo en una estructura de la cuál voy a saber el tamaño entonces en el handshake voy a poder decirle al servidor el tamaño de lo que va a recibir y luego se lo envío

**Comment by gianotti92** [comment]
como hacemos para mandar algo del tipo typdef struct desde el netcat? porque para hablarse entre procesos podemos crear un protocolo pero no sabemos como @recrear ese protocolo desde netcat

**Comment by MaximilianoFelice** [comment]
[Escribía y Chris me ganó de mano, pero lo publico igual por si hay algo que sirve]

Hola chicos, cómo están?

Como el nombre de la tabla es de tamaño variable, no van a saber _mientras están codeando_ el tamaño del mensaje que van a enviar. Pero cuando el programa esté corriendo sí van a tener los valores en memoria.

Entonces lo que tienen que buscar es meter a todos esos valores en un único mensaje. En la tercer charla vamos a hablar de [serializacón dinámica](https://docs.google.com/presentation/d/1-kmFUjYXF4KO8BRnuIwFzGRkqVSzDgFIBMOy7wJHbVM) que justo apunta a resolver este problema.

Respecto al tema `netcat`: Van a tener un par de problemas para enviar estructuras por este medio, ya que la herramienta te permite _solo_ enviar bytes. Cuando elijan como serializar una estructura después deberian "imitar" este comportamiento desde los bytes que mandan por `nc`. También van a tener problemas por los tipos de datos: No es lo mismo enviar un 1 (entero) que un "1" (string, ASCII).

Saludos!

**Comment by rcomesan** [comment]
Esto dificilmente te sirva para implementar tu protocolo pero... el tamaño máximo de nombre de tabla es también el máximo permitido para archivos en el filesystem del OS ya que cada tabla crea su propio directorio con su nombre según el enunciado. 

Debería ser NAME_MAX (255 bytes) definido en limits.h.

**Comment by matiasBusco** [comment]
Pero el tamaño maximo se lo daremos nosotros, si el FS lo tenemos que armar nosotros

**Comment by tferraro** [comment]
👋 Holis.
Acá tenés 2 cosas mezcladas.
**Primero** tenés el hecho que comentan Maxi y Chris, que es que tu problema de "No tengo definido un máximo" es porque la realidad es que tu protocolo debería ser agnóstico a los tamaños de cosas variables. Es decir, si vas a enviar, por ejemplo, una cadena de tamaño variable como es el nombre una tabla, **no deberías enviar un tamaño fijo, sino usar dinámicas de serialización dinámica**.

Ahora, hay una segunda pata que es: ¿Porqué no usar un tamaño máximo del sistema y listo? Como menciona @rcomesan. Esto no está tan bueno porque estás dependiendo enteramente de la implementación que tenga específicamente ese SO.
De hecho, los sistemas que implementan GNU (linux es uno de ellos. macOS por ejemplo, **no lo hace**), tienen determinado un "tamaño máximo" que puede tener un nombre de archivo. Pero eso **no se encuentra enforceado** y dependen entéramente del flavour y modificaciones que tengan.
Tantos condicionantes me indica que no es un terreno en el que nos querramos meter sin estar completamente seguros que no hay mejores alternativas...que de hecho, las hay 🙂

**Comment by matiasBusco** [comment]
Mil gracias !
