### ISSUE TITLE
Creación de una nueva memoria.

### ISSUE THREAD

**Issue by IvanDL95** [sisoputnfrba/foro#1311]
Buenas,

Tengo una duda con el enunciado de la guía. En el apartado de "pool de memorias" se explica que van a existir varias memorias, y que las mismas se conocerán mediante el proceso de gossip. El problema es que nunca explica en que circunstancias se crean nuevas memorias. Si es cada vez que se realiza una acción, cada vez que se crea una nueva tabla (lo cual no podría ser, porque una memoria puede contener información de varias tablas) o esporádicamente en algún momento que cada grupo defina, lógicamente teniendo como criterio la performance general del sistema.

También me viene la pregunta a la cabeza de si las memorias pueden ser destruidas en algún momento. Se aclara que el sistema debe soportar la desconexión de memorias. No entiendo si esto es algo que se debe diseñar, para que suceda en algún momento conveniente para mejorar la performance sin perder información, o es algo que es esperable que pase con las conexiones con sockets (si es así, que dios bendiga mi tp en la entrega final).

No sé si hay algún detalle que me pasé por alto, me faltó leer algún apratado/anexo o sencillamente cada grupo lo diseña/implementa por su cuenta.

**Comment by SofiCortes** [comment]
Buenas!

Se crean nuevas memorias simplemente cuando ustedes decidan levantar varios procesos del tipo memoria. Cada prueba del TP va a estar probando esto, es decir, como se comporta el sistema cuando se levantan 1 o N memorias. 

Las memorias pueden desconectarse/ser destruidas matando el proceso. Hay que tener en cuenta que esto puede probarse en la entrega en cualquier momento del ciclo del sistema, y su sistema debe ser lo suficientemente resiliente (a.k.a. que no explote todo) para que siga funcionando el resto. Lo esperado es que los datos que estén en esa memoria (y no en el file system) se pierdan, y que el resto de las memorias y el kernel se enteren de esta desconexión.

Como lo implementan es decisión del grupo :)

Cualquier cosa que no se entienda preguntá!

**Comment by IvanDL95** [comment]
Entonces, a ver si entendí bien. Cuando inicio el proceso memoria simplemente levanto una cantidad predefinida de memorias y luego no puedo crear más? Que me impediría conectar todas las memorias entre sí desde un primer momento?

**Comment by Dragonflares** [comment]
Lo más comodo para crear múltiples memorias es abrir múltiples consolas donde uses el ejecutable del modulo memoria. Soportar la desconexión de una memoria significa que por ejemplo alguien agarre y cierre la consola donde vos le diste ejecutar a una de las memoria. Y podés agarrar y levantar memorias a mitad de la ejecución también. No se si se entiende

**Comment by IvanDL95** [comment]
Sí, se entiende mucho mejor así. No es lo mismo que haya muchas consolas a decir que "se levantan varios procesos", porque sino se entiende que se hace fork() para crear un proceso hijo, el cual formará parte del pool. 

Lo de la desconexión sí me quedó claro, es solamente que no se caiga ningún proceso ni que se quede bloqueado esperando una respuesta que nunca va a llegar al forzar la desconexión.
