### ISSUE TITLE
Duda elección de memorias - Kernel

### ISSUE THREAD

**Issue by afondevilarevelli** [sisoputnfrba/foro#1312]
Hola, tengo una duda con respecto a cómo el Kernel elige la memoria en ciertos casos. 
En primer lugar, cuando recién empieza el sistema y ya se le asignaron los criterios a cada memoria con el comando ADD del Kernel, cómo sé a qué memoria redirigir la sentencia de un script si al principio no hay tablas creadas y no sé qué tipo de consistencia tiene? Hago un random entre todas las memorias que tengo y la mando a la que me salga?
Otra duda es el comando DESCRIBE del Kernel y cómo el Kernel conoce qué tablas han sido creadas. El enunciado dice: "**Para mantener la metadata de las tablas actualizada el kernel llevará registro de cuáles son las tablas creadas en el sistema en una estructura administrativa. Esta estructura se cargará luego de haberse conectado a alguna memoria haciendo un DESCRIBE global a la misma. Luego, esta estructura se actualizará cada un tiempo obtenido por archivo de configuración realizando nuevos DESCRIBE globales a cualquier memoria que tenga conectada**." Según esto, si el describe se debe hacer cada 10 segundos (establecido por archivo de configuración), en los últimos 4 segs por ejemplo se crearon 20 tablas y el Kernel no sabría de su existencia, entonces cómo redireccionaría la request a una memoria si desconoce la tabla y, en consecuencia, su tipo de consistencia?
  Yo en mi caso particular, para que el Kernel conozca a las tablas que fueron creadas, cuando la memoria responde al Kernel que la sentencia realizada fue OK, éste se fija si dicha sentencia fue CREATE o DROP y actualiza la estructura interna de las tablas respectivamente, y de este modo la mantiene actualizada. Esta bien esta implementación? O se debe realizar el DESCRIBE? Gracias.

**Comment by NaylaWinter** [comment]
Buenas,

En el primer caso, cuando tengas al Kernel iniciado con las conexiones a las distintas memorias pero sin conocer la metadata de las tablas cualquier operación que no sea un CREATE va a fallar porque el Kernel no va a tener conocimiento de la existencia de las tablas en su metadata. En caso del CREATE simplemente vas a usar el criterio que te pasen en la sentencia, es decir, con el que quieren crear la tabla.

La segunda pregunta se responde de forma similar, si en la metadata de las tablas en el Kernel no conoce la tabla entonces simplemente fallará la request.

Con respecto a la implementación te planteo el siguiente problema: qué pasa en el caso que al llegar una sentencia DROP efectivamente en el Kernel borres la metadata de la tabla como si ya no existiese y luego esa operación no pueda realizarse correctamente en el LFS?

**Comment by tferraro** [comment]
@afondevilarevelli como venis con esto? Te sirvió la respuesta de Nay?

**Comment by afondevilarevelli** [comment]
SI! Me sirvió, muchas gracias! Y una pequeña duda más, si la sentencia es un describe sólo (sin argumento), a qué memoria se lo mando? Yo hice un random entre todas las memorias que tengo.

**Comment by tferraro** [comment]
No está tipificado _cual_ memoria, solamente necesitas elegir una de conjunto! El como queda relegado a criterio del grupo :)

**Comment by NaylaWinter** [comment]
Buenas @afondevilarevelli esta resuelta la duda? En todo caso te pido si podes cerrar el issue, sino volver a consultar lo que no te haya quedado claro
