### ISSUE TITLE
Consulta sobre timestamps

### ISSUE THREAD

**Issue by Dragonflares** [sisoputnfrba/foro#1313]
Buenas tardes! Como va?

Quería preguntar sobre la implementación de los timestamps, ya que cuando a uno le llegan desde consola, el valor que uno está obteniendo en si es un char* guardado en un "vector" args[] (O asi lo determinamos nosotros). Mis dos consultas son:

1) Estuve leyendo un rato largo la biblioteca de time.h, pero no logro determinar cuál es la funcion que devuelve el timestamp actual, me gustaría un poco de clarificación en eso.
2) Como podría hacer para convertir de un char* a un time_t? O en defecto de un int a un time_t? Ya que puedo lamar a atoi() para pasar de char* a int.

Desde ya gracias!

**Comment by NaylaWinter** [comment]
Hola,

1. La función que nos va a permitir conocer el timestamp es: [gettimeofday() ](http://man7.org/linux/man-pages/man2/gettimeofday.2.html)
Lo único ojo que te devuelve el tiempo en microsegundos y no en mili, por lo que hay que hacer una conversión.

2. La segunda es consulta para el amigo Google, recién busqué "convert char* to time_t" y "convert int to time_t" y ya entre los primeros resultados hay varias alternativas.

**Comment by nico-abram** [comment]
Buenas!
Se puede time (https://linux.die.net/man/2/time) en vez de gettimeofday?

**Comment by tferraro** [comment]
@nico-abram no te va a servir, vos necesitas el timestamp en millis, no en segundos🙂

**Comment by rcomesan** [comment]
@tferraro claro, precisión de segundos no debería ser suficiente para esto considerando que los nodos procesan requests de forma concurrente y tendriamos colisiones. Lo que no me cierra es por qué en la página 15 del enunciado linkean a un [articulo](https://www.systutorials.com/241697/how-to-get-the-epoch-timestamp-in-c/) usando la funcion time que devuelve segundos desde epoch.

pd: lo terminé implementando con gettimeofday y precision de ms.

**Comment by varas-c** [comment]
@rcomesan Como decís, la función linkeada en el tp no es correcta. Como
dijo Nayla, la correcta es gettimeofday() (que es la que usaste vos, así
que está bien). Lo arreglamos para la próxima errata!

**Comment by nahuelm** [comment]
Hola @rcomesan. 

Perdón que me meta pero si lees la descripción de dicha función (del link que vos acabas de enviar). La misma indica que devuelve los valores tanto en Segundos como en microsegundos. Si tenes dicho valor en microsegundos y se necesita en milisegundos...

Por otro lado, siendo un trabajo practico de casi 55 hojas puede darse el caso de que fallemos y en parte también para esto esta la comunidad del foro. Para discutir posibles inconsistencias y resolver dudas que vayan surgiendo en el transcurso del cuatrimestre.

Saludos. Nahuel Mazzeo.

**Comment by Dragonflares** [comment]
Buenas tardes, al final mi consulta creo que no fue respondida, porque también yo expresé mal la cuestión en si que quería manejar.

Cuando alguien ingresa por consola un valor de timestamp, me llega como un char* timestamp = 125626, por ejemplo. No es una fecha como 9-03-2018. Por ende, ese no es el tipo de conversión que estoy buscando, lo que estoy buscando es conversión directa. desde char* (o int) a time_t, sin pérdida de datos.

**Comment by AxelFulop** [comment]
El timestamp es un  insignes long a fin de cuentas... Para eso esta:
 unsigned long int strtoul(const char *str, char **endptr, int base)

Fíjate cómo usarla...

**Comment by Dragonflares** [comment]
Gracias Axel, otro detalle.

gettimeofday() devuelve cualquier cosa. Lo unico que devuelve es la cantidad de tiempo que paso desde la ultima vez que la llamaste. Y de acuerdo con el POSIX de linux, la funcion está discontinuada, asi que gettimeofday no sería la solución

**Comment by tferraro** [comment]
Buenas!

Respecto a `gettimeofday`, la función no está persé deprecada, solamente se recomienda el uso de otra función, particularmente, según [su propia docu](http://man7.org/linux/man-pages/man2/gettimeofday.2.html), por los siguientes 2 detalles:
- No especifica timezone, por lo que si uno quiere medir fechas y horas, termina siendo poco eficiente. No es nuestro caso por suerte 🙂 
- Es muy susceptible a cambios de la fecha del sistema, otra cosa que no nos importa 🙂 

Por lo que podrían usarla sin ningún problema para obtener el tiempo en milis desde "Epoch" (o el "Inicio", etc)

**Comment by Dragonflares** [comment]
Hola!

El problema que me sale cuando uso gettimeofday(), es que me devuelve el tiempo en milisegundos desde la última vez que se ejecutó un gettimeofday()... no el tiempo dle sistema, cualquier cosa lo llevo a ver el sábado a medrano, pero eso es lo que me devuelve cuando la implemento.

**Comment by NaylaWinter** [comment]
Estuvimos con @MaximilianoFelice realizando pruebas sobre la función que estas pasando. El código es el siguiente y nos devuelve correctamente en ambos llamados el tiempo en milisegundos desde el Epoch (no entre llamadas)

```
#include <stdio.h>
#include <stdlib.h>
#include <sys/time.h>
#include <unistd.h>

double getCurrentTime() {
	struct timeval tv;
	gettimeofday(&tv, NULL);
	return (tv.tv_sec) * 1000 + (tv.tv_usec) / 1000;
}

int main(void) {

	double firstReport = getCurrentTime();
	printf("%f\n", firstReport);

	sleep(5);

	double lastReport = getCurrentTime();
	printf("%f\n", lastReport);


	return EXIT_SUCCESS;
}

```

El resultado que nos arroja es este:
```
1465007542.000000
1465012545.000000

```

**Comment by ncoen97** [comment]
Buenas, intentamos cambiar el time() por el gettimeofday() y nos funcionó. El tema es que nosotros tenemos el timestamp definido como un uint32_t, y cuando quiero pasar el resultado de double a uint32_t, me cambia el valor y el signo. Puede ser que tenga que ver con el tamaño? Gracias.

![image](https://user-images.githubusercontent.com/7952790/57632114-3b6bf680-7577-11e9-9a12-06e6d1aa5a90.png)
