### ISSUE TITLE
Resultados de requests unitarios del Kernel

### ISSUE THREAD

**Issue by PabloPaglilla** [sisoputnfrba/foro#1314]
Buenas!

Quería consultar cómo se van a devolver los resultados de los requests unitarios realizados por la consola del Kernel.

En el seminario se dijo que los resultados de los requests de un script se escribieran en un archivo de log. El enunciado también específica que los requests unitarios se tratan como scripts de una única linea.

Ahora bien; cuando se ingresa un request unitario, ¿también bajamos el resultado a un archivo de log o lo mostramos por la consola cuando termine de ejecutarse?

Gracias!

**Comment by Dragonflares** [comment]
Si te vienen desde la consola de Kernel, los resultados se muestran en la consola de Kernel, el archivo de log es mas que nada para registrar errores o poner marcas de que tu programa envió un mensaje a memoria, o que abrió un script.

**Comment by NaylaWinter** [comment]
Buenas, 

En el archivo de log debería ir cualquier información que nos permita saber el estado del sistema, no hace falta logguear **todo** pero para el caso de las request, se hagan tanto unitariamente como por archivo LQL estaría bueno que logguen algo del estilo: "La request xx retornó ...."/"La request xx se ejecutó correctamente"

Mas que nada porque también les va a permitir a ustedes saber si sus componentes estan funcionando correctamente y también para poder verificar que esten ejecutandose bien tanto las pruebas del checkpoint presencial como las finales.

**Comment by tferraro** [comment]
@PabloPaglilla como venis con esto? Te sirvió la respuesta de Nay?

**Comment by PabloPaglilla** [comment]
Me sirvió! Justo terminé de implementarlo 😁 . Muchas gracias. Cierro el issue.
