### ISSUE TITLE
Duda con printf/puts

### ISSUE THREAD

**Issue by ggallici** [sisoputnfrba/foro#1315]
Buenas, tengo un tema con las funciones printf/puts que a veces andan a veces no. 
La cagada del problema es que no tira ningun error (limitando mi skill de googleo), solo se congela como si se quedara esperando algo.  Que puede ser??
Puntualmente tengo un main asi:

int main(void) {
	puts("Esto si se imprime");
	while (1) {
		void * buffer = recibir_mensaje(cliente);
		puts("Esto no se imprime");
	}
}

PD: la funcion recibir_mensaje termina y devuelve lo que tiene que devolver
PD2: El main anterior se comporta igual tanto con puts como con printf

Desde ya muchas gracias

**Comment by gastoncastineira** [comment]
Se congela porque estás en un en un while(1) que no te imprime nada, o queda bloqueado

Asumiendo que probaras poniendo el puts con una cadena literal en vez de lo que recibas en buffer, a priori la única alternativa que se me ocurre sin mirar todo el resto de tu código es que no te esté llegando ningún mensaje y quede bloqueado ahí adentro de esa función.

Si me podés dar más información tal vez te pueda guiar mejor

Saludos!

**Comment by ggallici** [comment]
Los puts los estoy probando con cadenas literales y, cuando depuro, la funcion termima. Otra cosa que probé fue poner el puts adentro de la funcion y en ese caso no llegaba a terminar

**Comment by gastoncastineira** [comment]
tira un fflush(stdout) después del primer puts y decime si te anda

**Comment by ggallici** [comment]
Buenas, mande el fflush(stdout) despues del primer puts y me dejo de andar la funcion de recibir_mensaje. Probe poniendola despues de la funcion y se congela igual que antes pero en el flush en vez de en el puts.

**Comment by gastoncastineira** [comment]
Tiene que ser algo en el contexto del código entonces. puts a veces tiene mambos con los bufferes de salida y queda bloqueado porque quedó basura en algún lado, por eso conviene usar siempre printf con un \n al final, pero si decís que probaste reemplazando los puts por printf y tampoco quiere andar, prefiero ver el código antes de hacer las cosas por tanteo.

Si no te molesta que lo revise,  mandame todo lo que consideres necesario para llegar a tu mismo error a castineira.gaston96@gmail.com

**Comment by tferraro** [comment]
Buenas!
Como viene eso? Pudieron llegar a algún puerto?

Por lo que comentás, voy a intentar parafrasear el comportamiento que se ve:
1) Ejecutás el proceso y el resultado es solo la impresión del primer `puts`
2) Debuggeando el proceso línea por línea, solo se imprime el primer `puts` y la variable `buffer` tiene sentido.
Parafrasié bien?

Ahora, estaría genial poder reproducirlo con el mínimo pedacito de código. Tenés un mini extracto como el que pasaste que reproduzca el error? Si ese extracto chiquito no funciona, fijate si podes hacer otra cosa en vez de `recibir_mensaje `, por ejemplo sumar una variable. _Puede ser que el problema está en esa función._

Como extra, particularmente la docu de `puts` https://linux.die.net/man/3/puts tiene una nota sobre bugs que tiene, lo que me hace desconfiar un poco de que no estemos ante un escenario como el que describe :/.

Cualquier cosa contame!

Tom

**Comment by ggallici** [comment]
Buenas, perdón por la demora estuve con otras materias. Ayer lo miramos con Lucho y lo arregló agregando un malloc que faltaba en la función recibir_mensaje. Creo que ni él ni yo entendimos porque malloc solucionó eso, pero funciona 🤘🤘🤘

Muchas gracias por la predisposición.

Saludos.
