### ISSUE TITLE
problema al hacer push "Modified Content", No pushea ciertos contenidos

### ISSUE THREAD

**Issue by TomasTakahashi** [sisoputnfrba/foro#1316]
A la hora de pushear al repo, hacemos el correspondiente git add pero no nos agrega ciertas carpetas. Hacemos el commit, pusheamos y nos sube las carpetas pero vacias....
Gracias. @natoszme @gastonprieto 

![Sin título](https://user-images.githubusercontent.com/37699451/56528333-5ec9f580-6525-11e9-89cc-3b94f95e5b37.png)

**Comment by gastonprieto** [comment]
Hola!

Mmm, que raro eso, buscando en stackoverflow alguien dice que puede que tengas dos .git dentro del mismo repositorio. Esto podrías chequear haciendo con un `tree -a | grep ".git$"` o un `ls -aR | grep ".git$"`.

Lo otro también que se me ocurre es que pruebes con hacer un `git add` de un archivo que conozcas que se haya modificado para ver si se hace el add o no.

**Comment by Dragonflares** [comment]
Buenos dias!

El problema es que estas escribiendo "git add ." Cuando es "git add ./". A no ser que me estés diciendo que agregando archivo por archivo no te deja, yo diría que tu problema es que no pusiste la barra (que por lo general es para que entienda que tiene que agarrar las carpetas dentro del repo y sus contenidos, y no solo las carpetas)

**Comment by mgarciaisaia** [comment]
Mmm... No, che. `git add .` debería funcionar (_indexame todo el directorio actual - y su contenido_).

Voto por que nos compartas el `tree -a` que pide Gastón. Pero subilo a gist.github.com o algo así, no suban screenshots 🙏

**Comment by behringertomas** [comment]
Gracias! el problema era porque teniamos carpetas copiadas que habian sido subidas desde otro directorio a git, y que todavia tenian el .git  Saludos.
