### ISSUE TITLE
Tamaño de memoria

### ISSUE THREAD

**Issue by mesaglio** [sisoputnfrba/foro#1317]
Una duda sobre el tamaño de las estructuras que tengamos en memoria.
La estructura de segmento, que junto a @ncoen97 definimos que tiene un char* nombre, y un t_list* paginas.
Para saber cuanto ocuparia deberiamos saber el tamaño maximo de nombre y el sizeof(pagina)*cantidad_de_paginas.
Como podemos saber la cantidad de paginas que vamos por segmento, antes de levantar todo?

**Comment by NaylaWinter** [comment]
Buenas,

Para qué necesitarías saber la cantidad de páginas que vas a tener por segmento al levantar la Memoria? De hecho la cantidad de páginas que va a tener un segmento va a ir variando a medida que vayamos ejecutando request y tenga que ir cargando nuevas páginas, como también no todos tus segmentos van a tener la misma cantidad de paginas.

De hecho, tu "cantidad_de_paginas" se va a limitar a saber simplemente cuantos elementos tenes en la t_list* de páginas. 

Era esta la consulta? Sino decime

**Comment by mesaglio** [comment]
La duda viene al momento de crear una pagina.
El tamaño de la memoria viene dado en el archivo de configuracion de la propia memoria.
Por ejemplo: el tamaño de la memoria es de 2048.
El tamaño maximo del value viene por el archivo de configuracion del fileSystem. Pongamos un ejemplo que sea de 10 bytes.
Una pagina por la estructura que definimos es de 9 bytes + el tamaño maximo de value. En este caso 19 bytes.

Entonces un segmento va a ocupar, como dijeron en [issue #1308 ](https://github.com/sisoputnfrba/foro/issues/1308), el tamaño del nombre del segmento + (el tamaño de cada pagina * cantidad_de_paginas)

Creo que pense esto porque dice que hay que inicializar toda la estructura al iniciar la memoria. 
Cuando tengo que agregar una nueva pagina, tengo que saber si el queda espacio. De no tenerlo debo ejecutar el algortimo de remplazo, LRU.
El size de la t_list* es un numero, yo tengo que saber cuando ese numero se acerca al limite de cantidad_de_paginas.

**Comment by tferraro** [comment]
Buenas!

Creo que entendí por donde viene la mano. Te invito a dejar una intro a como viene la traducción de direcciones en segmentación paginada acá para que todos nos sigan:
- Tenés una posición de memoria, que corresponde a un segmento y a un offset.
- Con la base de ese segmento podes conseguir que páginas están asociadas.
- Y usando el offset set, buscamos que página es y el offset dentro de la página.
- La página se traduce a "un puntero" dentro de mi memoria principal y con el offset te movés al puntero final donde va a estar tu memoria.

Esto implica varias cosas:
1) Tu memoria principal ya va a estar inicializada desde el vamos como un graaaan malloc, dado por el tamaño de tu memoria.
2) Vas a tener esa memoria fragmentada en páginas, segun el tamaño definido y alguna forma de manejar el cambio de "página" a memoria.
3) Estas páginas van a existir desde el vamos, porque referencian a un pedacito de la memoria principal.

Ahora, la consulta venía por el lado de:
> La duda viene al momento de crear una pagina.

Esto me da un indicio que el punto (3) nos viene a salvar las papas, porque como existen desde siempre, está todo fenómeno. Lo que te comenta Nay es que, como las páginas siempre existen, lo que terminás teniendo es una **asignación dinámica** de las páginas a los segmentos mientras se van creando y van necesitan más memoria.

Eventualmente, todas las páginas van a terminar siendo asignadas a un segmento y cuando sea necesario asignar una más, ahi entra en juego, como decís, el LRU. Una forma de implementarlo, es la comparación que sugerís.

Pude dar un poco más de insight a lo que escribió Nay? Cualquier cosa avisame! 🙂 

Tom

**Comment by tferraro** [comment]
@mesaglio Como viene eso? Te sirvieron las respuestas? Si no existen más dudas, podes cerrar el issue? 👮
