### ISSUE TITLE
Dudas con el enunciado de memoria

### ISSUE THREAD

**Issue by GonzaOrtega** [sisoputnfrba/foro#1318]
Tengo un par de dudas en el enunciado de memoria.

La primera tiene que ver con la estructura de la memoria.
Lo que entiendo hasta ahora es: a la memoria se le manda un header de segmento y un offset (como bloque), después la tabla de Segmentación transforma este header en una "base" y luego se manda una parte del offset original ("pagina") a la tabla de paginas junto con la base.
Acá viene mi duda, que seria la "base" para la tabla de pagina?? Creo que "pagina" es el numero de pagina a buscar pero no estoy seguro...

La segunda tiene que ver con lo que devuelve tabla de pagina.
Por lo que se ve en el gráfico del tp, pag 20 la tabla de pagina contiene paginas que están conformada por el timestamp, key y value, pero en el otro gráfico dice que saca elementos de esta tabla para llevarlos a memoria para encontrar el bloque de datos correspondiente. Entonces que diferencia hay entre la tabla de pagina y la memoria si ya la tabla de pagina ya tiene lo que yo necesito??

Gracias

**Comment by damianKreuter** [comment]
A ver, yo respecto a lo de Header y offset no se como es la onda porque yo hice una estructura Segmento propia sin eso con solo path, nombre tabla, y un puntero a su tabla de pagina.

Lo que si puedo responder es que, en memoria habra una pila de elementos que deben ser ordenados por LRU. Esa es la diferencia, y ahi es donde ira a buscar el modulo los elementos. 

Esos elementos deberian tener algo que puedan referenciar al segmento y pagina que pertenecen por si requiere verificar algo extra como el nombre de tabla y el estado de modificado

**Comment by MaximilianoFelice** [comment]
Buenas!

La tabla de páginas es una estructura que tiene el registro de todas las páginas del sistema. Pero **no tiene el contenido de las páginas**.
El contenido de las páginas, por su parte, esta en el bloque de memoria. Entonces, la tabla de página te va a decir algo como _"La página 23 son los bytes del bloque de memoria que se encuentran a partir del byte 3450."_

La segmentación, por su parte, peca un poco de no corresponderse tal cual a la teoría. En nuestro caso, en vez de tener una base+offset, nos alcanza con tener una lista de punteros a la tabla de página. O de indices (números de página), o como prefieran modelarla. Esto básicamente me tiene que contar _"Al segmento de la tabla A le corresponden las páginas 10, 25, 36 y 52 de la tabla de páginas."_

Se logra ver la función de cada uno?

Saludos!

**Comment by tferraro** [comment]
@GonzaOrtega se resolvió la duda? Como venís con eso? Te sirvió la respuesta de Max?

**Comment by GonzaOrtega** [comment]
Me quedo claro lo de las estructuras de la memoria. Pero no me quedo claro como se comunican.

O sea, la tabla de segmentación recibe el segmento y el offset y esto devuelve una base. Pero es la base o la página que se deriva del offset que me indica el número de página??

Gracias

**Comment by tferraro** [comment]
A eso se refería Maxi con lo de _pecar_ de no corresponder enteramente con la teoría. Cuando traducis el segmento, lo que vas a tener como "base" es en realidad una suerte de lista de páginas ordenadas según el segmento y vos terminás traduciendo al "offset interno" de la página y usando como base, "el indice de la pagina". Porque, a fin de cuentas, la "base" teórica es el principio de la primera página, por lo que te podes mover a lo largo de los índices usando el offset general.

**Comment by GonzaOrtega** [comment]
Ok, la base es una lista que contiene los números de página que voy a usar. Entonces para que necesito el índice de página si ya se las páginas que se van a utilizar??

**Comment by tferraro** [comment]
Decir índices es un eufemismo, lo estás usando en el momento de la traducción al moverte entre páginas. Pero la idea se mantiene :)
