### ISSUE TITLE
Memoria - Estructuras Segmento y Tabla Pagina

### ISSUE THREAD

**Issue by damianKreuter** [sisoputnfrba/foro#1319]
Sabiendo que en memoria solo iran las paginas.

Pus deberia hacer un nuevo malloc para estas 2 talas administrativas ya que no estan en memoria?

Pd: Memoria contigua es la que debo usar byte no?

Si en memoria uso una pila, esta bien o no?

**Comment by MaximilianoFelice** [comment]
Buenas! 

De alguna forma vas a tener que lograr reservar espacio para tanto la tabla de páginas como la de segmentos. Para eso, hay un par de consideraciones:

* Las páginas tienen tamaño fijo, por lo que siempre vamos a poder poner una determinada cantidad de páginas en memoria. Y como no tenemos swapping (un sistema en el que podes tener páginas que no estén todavía cargadas en memoria, lo van a ver en teoría),  entonces la cantidad máxima de páginas va a ser fija. Esto es bueno porque nos permite reservar todas esas páginas de antemano.
* El caso de la tabla de segmentos no es tan sencillo. Acá no sabemos de antemano cuál va a ser la composición de los mismos, por lo que vas a tener que ir reservando tamaño dinámicamente.


Después, la memoria contigua es un bloque de memoria (un gran malloc) que vas a dividir _logicamente_ por páginas. Lógicamente implica que vos leyendo la tabla de páginas vas a saber que, por ejemplo, la página 10 va del byte 1100 al 1200 de este gran bloque. Este gran bloque tiene bytes, si, que le corresponden al contenido de las páginas, asique asumo que quisiste decir con "usar byte acá", pero cualquier cosa repregunta!

Por otro lado, en que lugar pensabas que la pila podría ser una buena alternativa?

Saludos!

**Comment by damianKreuter** [comment]
La pila la pense para la memoria contigua ya que tendre que ordenarla, viendo que debo usar LRU y segun el libro tengo 2 opciones

1- por pila
2- Por una tabla enumerada

Por tema de que veo mas practico a la hora de ordenar por pila entonces veo de ir por ese camino.


Por otro lado, el tema de los segmentos entonces significa que debemos estar usando reallocs muchas veces a medida que se van agregando o eliminando paginas. Algo asi no?

**Comment by MaximilianoFelice** [comment]
Buenas!

No veo que una pila te pueda ayudar mucho en ese caso. Manejar una tabla suena a una buena idea.

> Por otro lado, el tema de los segmentos entonces significa que debemos estar usando reallocs muchas veces a medida que se van agregando o eliminando paginas. Algo asi no?

Para nada. Vas a hacer un `malloc()` grande al principio para mantener a todas las páginas, y cuando quieras settear una página, usamos un `memcpy()`.

Saludos!

**Comment by tferraro** [comment]
@GonzaOrtega se resolvió la duda? Como venís con eso? Te sirvió la respuesta de Max?

**Comment by tferraro** [comment]
Buenas! Cierro el issue por inactividad. Cualquier cosa que todavía persista la duda, no dudes en volver a abrirlo @damianKreuter !
