### ISSUE TITLE
Consulta sobre size de las particiones

### ISSUE THREAD

**Issue by IvanCasanova98** [sisoputnfrba/foro#1320]
@gastonprieto @natoszme 
En el enunciado dice que las parctiones de las tablas contienen el tamaño "real" de la particion y los key de los bloques que contienen.

Mi pregunta es: el size de las particiones, consiste en el size of de la particion en si? o es la sumatoria del size de los bloques que contiene dicha particion?

Gracias

**Comment by natoszme** [comment]
Buenas! Con el "size of de la partición en sí" a qué se refieren? Al size
of de un struct Partición que están modelando?

**Comment by tferraro** [comment]
@IvanCasanova98  se resolvió la duda? Como venís con eso?

**Comment by AxelFulop** [comment]
Buenas, yo había preguntado lo mismo, te copio la respuesta:
"
Por empezar los archivos se los vamos a dar ya con algún tamaño creado y designado. 
Eventualmente si tuvieras que crearlo desde 0 vas a empezar en SIZE=0 y vas a ir agregando tamaño según lo que calcules en base a la clave, tiempo y el valor que tengas que grabar, por ej:
Arrancas con un archivo particion0.bin que tiene
SIZE=0
BLOCKS=[40] (Porque le agregamos un bloque al crearlo)

Ahora en la compactación tenes que grabar solo "30;0;Vayne", en el/los bloque/s de particion0.bin cuanto te va a quedar de tamaño si tu archivo solo tiene ese texto? 
En ese caso el size de tu archivo va a ser 10, y en el archivo del bloque 40 vas a ir a copiar el texto "30;0;Vayne" sin el \0 final (ya que internamente no manejamos strings y tu delimitador aca va a ser un \n) y después en el particion0.bin vas a tener:
SIZE=10
BLOCKS=[40]"

**Comment by IvanCasanova98** [comment]
@tferraro ya esta resuelto. Gracias!
