### ISSUE TITLE
Consulta sobre archivos temporales 

### ISSUE THREAD

**Issue by Lucasresa** [sisoputnfrba/foro#1321]
Buenas, me acaba de surgir una duda con el tema de los archivos temporales. ¿El contenido de estos se debería guardar dentro de los bloques de mi file system al igual que las particiones? O simplemente debería tener el contenido directamente en cada uno de los .tmp?
No encontré que dentro del enunciado se especifique esto. Espero que se haya entendido la consulta, muchas gracias.

**Comment by NaylaWinter** [comment]
Buen día,

Efectivamente vas a seguir la misma lógica tanto con los .bin como con los .tmp.
Dentro del archivo .tmp vas a tener el Size + el listado de bloques que conforman ese archivo temporal.

**Comment by Lucasresa** [comment]
Buenísimo! Y tengo una duda mas, yo voy a poder tener mas temporales que particiones? O sea, podría pasar que yo tenga una tabla de 3 particiones y que se me acumulen 4 o mas temporales antes de realizar la compactación?
Gracias.

**Comment by NaylaWinter** [comment]
Si, se te va a poder dar el caso.

La cantidad de archivos temporales que tengas pendientes de compactación antes de arrancar la misma va a depender exclusivamente de la relación entre el tiempo de dump y el tiempo de compactación, no es independiente de la cantidad de particiones que tenga definida esa tabla.

**Comment by tferraro** [comment]
Buenas! @Lucasresa como venis con eso? Te sirvió la respuesta de Nay?

**Comment by tferraro** [comment]
Cierro el issue por inactividad! @Lucasresa si la duda persiste, no dudes en volver a abrir el issue!

**Comment by cmedrano** [comment]
Hola, 
establa leyendo este issue y me ayudo a sacarme algunas dudas. Pero me quedo una duda que creo que es correcto lo que pienso pero no estoy seguro por eso va la pregunta.
Suponiendo que tengo una tabla x  con 3 particiones entonces cuando se realiza el proceso Dump lo que genera es un solo archivo .tmp para todos los registros de la tabla x que estaban en la Memtable y  no un .tmp para cada partición verdad? es decir, el proceso Dump genera un .tmp por cada tabla y no por cada partición independientemente de que si las keys que se estan dumpenado corresponde a distintas particiones?

Muchas gracias

**Comment by NaylaWinter** [comment]
Buenas,

Efectivamente como tu Memtable esta separada a nivel "tabla" y no a nivel "partición" cuando realices un dump vas a estra generando un archivo .tmp con las keys correspondientes a múltiples particiones a la vez, no uno por partición.
Después la compactación se encargará de llevar cada Key a su partición correcta.

**Comment by cmedrano** [comment]
Perfecto! muchas gracias Nayla!!
