### ISSUE TITLE
Caida de memorias

### ISSUE THREAD

**Issue by PabloPaglilla** [sisoputnfrba/foro#1322]
Buenas!

Estuve implementando la comunicación con las memorias en el kernel y quería consultar cómo encarar la caída de estas. 

En el caso de que se caiga una memoria que está asociada a uno o más criterios, ¿la sacamos de los criterios y hacemos que tenga que volver a agregarse a los mismos por la consola si se reconecta? ¿O proseguimos de alguna forma distinta?

Por ejemplo, si se cae la memoria asociada al criterio SC. Como esta es única, el criterio se quedaría sin ninguna memoria asociada. En un caso como ese:
* ¿Informamos al usuario sobre la caída para que manualmente agregue una nueva memoria al criterio?
* ¿Seleccionamos nosotros alguna otra memoria para agregar al criterio?
* ¿o alguna otra cosa?

Este último problema se presentaría siempre que un criterio no tenga ninguna memoria asociada.

Gracias de antemano!

**Comment by NaylaWinter** [comment]
Buen día,

En el caso de que se caiga una memoria entonces vas a tener que desasociarla de todos los criterios en los cuales este incluida, basicamente para que no la puedan elegir como memoria para realizar un request porque no existe mas. En el caso de que la memoria se reconecte se va a tener que volver a asociar a los criterios nuevamente de forma manual (no se debe auto reconectarla) y podría perfectamente asociarse a criterios distintos que los que tenía antes.

Asimismo, una vez que se te cae una memoria deberías informarlo por consola/archivo de log, **no** debes asociar otra memoria al criterio, eso se hace solamente por consola y de forma manual.

En caso de que se te caiga la memoria del criterio SC entonces simplemente cualquier request que llegue para ese criterio no podrá ser realizada y se deberá informar el error. Recién comenzará a funcionar normalmente en cuanto se asocie una nueva memoria.

**Comment by PabloPaglilla** [comment]
Perfecto! Muchas gracias!

Cierro el issue.
