### ISSUE TITLE
Gossip y kernel

### ISSUE THREAD

**Issue by agustinlk** [sisoputnfrba/foro#1323]
Buenas tardes!

El Kernel ejecuta el proceso de Gossip al igual que las memorias? o el Kernel se entera de las memorias que hay cuando la memoria principal hace gossip? Nosotros lo pensábamos de la segunda manera pero el ejemplo nos mareo: 

> Para mantener una lógica en la explicación de nuestro ejemplo diremos que el proceso de gossip se ejecutará cada 4 unidades de tiempo en cada uno de los nodos.
...
A continuación (T1) ingresará el Kernel
...
En T5, El Kernel volverá a consultar a Memoria A cuáles son los nodos pertenecientes al sistema
> 

Entiendo como si el Kernel tambièn tiene configurado un tiempo para hacer gossip.

Gracias

Agustìn

**Comment by NaylaWinter** [comment]
Buenas,
El Kernel también tiene que realizar el proceso de gossiping al igual que las memorias. Podrías agregar este campo dentro del archivo de configuración del Kernel o asimismo pedirselo a cualquier memoria (teniendo en cuenta que este puede ser modifcado en tiempo de ejecución).

Inicialmente el Kernel solo puede hacer gossiping contra la memoria que tiene en su archivo de configuración pero una vez que consiga las demas ya lo deberá hacer con todas las que conozca.

**Comment by agustinlk** [comment]
Perfecto! Gracias

**Comment by chamenwais** [comment]
Hola @NaylaWinter.

Por favor, ¿aclararías tu comentario?:

_Inicialmente el Kernel solo puede hacer gossiping contra la memoria que tiene en su archivo de configuración pero una vez que consiga las demas ya lo deberá hacer con todas las que conozca._

Si es así, ¿porqué en el final del primer ejemplo del Anexo III, instante T9, muestran cláramente que a pesar de que el Kernel conocía a la memoria A y B, solo le pide la tabla a A (que me imagino que sería la que tiene en el archivo de conf) y no a B?

![image](https://user-images.githubusercontent.com/11778309/60531932-7dd9c600-9cd2-11e9-906d-d5ee4d035ef3.png)

_Finalmente, cuando lleguemos a **T9**, el **Kernel** volverá a consultar a **Memoria A** cuál es el estado del pool y el **Kernel** conocerá al pool en su totalidad._

Esto mismo planteo en [otro issue similar ](https://github.com/sisoputnfrba/foro/issues/1372#issuecomment-507754041)

**Comment by iago64** [comment]
@chamenwais podes pedirsela a todas las memorias que conozcas, pero como al principio solo vas a conocer a 1, vas a poder pedirle la tabla de seeds solo a esa memoria.

**Comment by chamenwais** [comment]
Mmm lo que indican en el enunciado es que en el Kernel no le pedis la tabla a todas las memorias que conozcas, sólo se la pedís a la que tenés en el archivo de conf. a pesar de que conozca más memorias.

Si no debería decir:

_Finalmente, cuando lleguemos a **T9**, el **Kernel** volverá a consultar a **Memoria A y ahora que la conoce, a la Memoria B** cuál es el estado del pool y el **Kernel** conocerá al pool en su totalidad (osea a conocerá a **Memoria C**)._

Supongo que estoy hilando fino, y que puedo limitarme a codear lo que indican en el enunciado sin mayor problema al momento de la entrega. 

Si me van a dar como erróneo el hecho de cumplir con el enunciado, en sólo pedir en el Kernel la tabla Gossip a la memoria del archivo de conf. les agradecería que me lo indiquen claramente.

Gracias, pueden cerrar el issue.
Francisco Romero

**Comment by NaylaWinter** [comment]
Buenas,

Mas allá de la discrepancia entre lo que esta en el enunciado y lo que se contestó en algunos de los issues te recomendaría que tomes el approach que mejor te parezca/convenga para tu implementación: tanto que el Kernel consulte contra todas las Memorias que tenga en su lista de seeds o que consulte solo la que tiene en el archivo de configuración.

Consultar solo con la memoria del archivo de configuración tiene, en un primer análisis, dos contras: 
1) Si la Memoria del archivo de configuración se cae entonces el Kernel queda completamente desconectado de los nuevos cambios(bajas y altas de nodos) que puedan realizarse en el pool
2) El Kernel va a tardar mas tiempo en ser completamente consistente con todo el pool en comparación con el tiempo que tardaría si le consultase a todas sus memorias conocidas su lista de memorias conocidas

Mas allá de estos dos puntos, para que te quedes tranquilo, no se va a tomar como incorrecto consultar únicamente con la memoria del archivo de configuración.
