### ISSUE TITLE
Tabla de Páginas

### ISSUE THREAD

**Issue by cmedrano** [sisoputnfrba/foro#1324]
Hola!

me surgió una duda con respecto al párrafo del enunciado "por única vez al iniciar el proceso, reservando en este momento la memoria necesaria para la memoria principal y tabla de páginas"

La parte de reservar la memoria necesaria para la memoria principal lo entendí.

Pero la parte de reservar memoria para la tabla de paginas me surgio una duda, entiendo que puedo calcular el tamaño de la tabla de paginas si tengo una sola tabla de páginas ya que conociendo el tamaño de la memoria  principal y el tamaño de la página entonces puedo calcular la cantidad de página, por ende puedo reservar espacio para una tabla de páginas.

Pero en el diseño que hice no tengo una sola tabla de páginas, si no que tengo varias tablas de página, una por cada segmento.

Por lo tanto cada una de las tabla de páginas va ser dinámica y va ir cambiando de tamaño de acuerdo a las solicitudes que vayan llegando.

Lo que si tengo es un bitmap de n elementos donde n es la cantidad de páginas, para saber que marco de la memoria tengo disponible.

Esta bien la forma que lo implementamo?, es decir no reservamos memoria para una tabla de páginas si no que tenemos varias tablas de página una por cada segmento, y cada una va cambiando de tamaño dinamicamente.

Muchas gracias
Saludos
Cristian Medrano

**Comment by tferraro** [comment]
Buenas!

Lo que decís tiene sentido en un escenario de **Memoria Virtual**. Todavía seguramente no lo vieron, por lo que no voy a indagar un poco por ahí.
Ahora, al no estar bajo un caso similar, cada página va a estar ligada a un único marco, por lo que tendría ningún sentido mantener muchas tablas de páginas? Cuando siempre la sumatoria de los elementos de todas va a ser siempre el mismo?

Tom

**Comment by cmedrano** [comment]
Muchas Gracias, 

entonces tendríamos que cambiar el diseño y volverlo hacer por que de la forma que está, estaría mal?

**Comment by fighthawkarg** [comment]
Si tuvieran una sola tabla de páginas única, sin una por cada segmento. 
Cual es la gracia que me digas que es segmentación paginada?

**Comment by cmedrano** [comment]
Entiendo, ya lo implementamos de la forma que se pide con una sola tabla de paginas.

Mucha gracias
