### ISSUE TITLE
Consulta sobre estructura del proyecto

### ISSUE THREAD

**Issue by mesaglio** [sisoputnfrba/foro#1325]
Esta mal escribir el desarrollo de la funcion en los .h y dentro del main en el .c solo llamar a las funciones??
De ese modo podriamos modularizar las distintas funciones, en distintos .h y el .c estaria mas "limpio".

**Comment by tferraro** [comment]
Buenas!

Los archivos de headers, están pensados para tener solamente los prototipos de las funciones o definiciones de tipos.

Vos lo que estás buscando es crear más archivos .c, que cada uno podría tener su respectivo .h

Tom
