### ISSUE TITLE
Consulta criterio SHC

### ISSUE THREAD

**Issue by ariel-** [sisoputnfrba/foro#1326]
Tengo una duda respecto a las siguientes partes del enunciado:

Enunciado (parte 1):
* SELECT
* INSERT
* CREATE
* DESCRIBE
* DROP

(...)
Los primeros cinco comandos cuando sean solicitados al Kernel serán directamente redireccionados a la memoria elegida por el criterio de la tabla en cuestión.

Enunciado (parte 2):
Criterio Strong-Hash Consistency
(...)
Al llegar un pedido a dicho criterio aplicará una función de Hash sobre la key que definirá a qué                   memoria deberá ir dicho pedido

Consulta: ¿cómo elegir a qué memoria del pool de SHC enviar comandos como CREATE, DESCRIBE y DROP que no tienen un key asociado a ellas?

**Comment by NaylaWinter** [comment]
Buenas,

En este caso va a ser indistinto a que memoria le redirijas la request, vas a elegir a cualquiera de las que tenga asociadas el criterio.

**Comment by ariel-** [comment]
Gracias! Cierro

**Comment by cmedrano** [comment]
En la última consulta cuando decis "Consulta: ¿cómo elegir a qué memoria del pool de SHC enviar comandos como CREATE, DESCRIBE y DROP que no tienen un key asociado a ellas?"

Si el comando es Create como sabes a que criterio de memoria tiene que ser redireccionado si no sabes la metadata de la tabla porque supuestamente no existe, asi que no sabes si es SC o SHC o EC? en este caso a  que criterio tiene que ir?

Muchas gracias

**Comment by ariel-** [comment]
> Si el comando es Create como sabes a que criterio de memoria tiene que ser redireccionado 

Uno de los parámetros que se le pasan a CREATE es justamente el criterio de la tabla a crear

**Comment by NaylaWinter** [comment]
Buenas, como indica Ariel: dentro de la misma sentencia se encuentra el tipo de consistencia, a este criterio le enviaras la request

**Comment by cmedrano** [comment]
Perfecto! Muchas Gracias!!
