### ISSUE TITLE
Tamaño de la memtable

### ISSUE THREAD

**Issue by cmedrano** [sisoputnfrba/foro#1327]
Hola, 

El tamaño de la memtable es variable verdad? es decir no hay un tamaño fijo si no que este va ir cambiando de tamaño a medida que lleguen las solicitudes.
Es decir no hay un limite para la cantidad de tablas ni para la cantidad de datos de cada una?

Toda solicitud (CREATE, INSERT,DROP, SELECT)  que llega a LFS, pasara primero por memtable verdad?

Otra pregunta, los datos de la  metadata de cada tabla puedo tenerlas cargadas en memoria del proceso LFS? además de tenerlas en los archivos obviamente, para que cada vez que me soliciten un describe pueda recorrer esa estructura en memoria(Que puede ser dentro de la misma estructura de memtable) . Tambien me puede servir para validar si la tabla existe o no en el LFS.

Muchas gracias

**Comment by NaylaWinter** [comment]
Buenas,

El tamaño de la memtable va a ser variable: irá variando a medida que te vayan realizando distintos INSERTS dentro de LFS como también siempre que realices un DUMP de los datos que tenes en la misma. Asimismo, cada una de las tablas tendra un area de memtable con un tamaño distinto que las demas, eso dependerá de la cantidad de INSERTS hasta el momento de dump.
No tenemos un limite para la cantidad de inserciones que se pueden hacer sobre Memtable.

Las únicas operaciones que pasan por memtable son los INSERTS (debido a que, como queremos rapidez, las inserciones se haran siempre primero dentro de este area) y los SELECTS debido a que se debe verificar si dentro de esta area hay algún valor para una key que aun no se persistió en el file system. 
Sobre los CREATE y los DROP los mismos se realizarán directamente sobre el file system, recordando crear el area de memtable para la tabla creada cuando se realize el CREATE.

Sobre la tercer pregunta: si, te va a convenir tenerlas en alguna estructura administrativa del LFS. Recordá que siempre que realices alguna modificación sobre el FS vas a tener que mantener esta estructura consistente con los cambios.
Podrías tener la metadata junto con la memtable como no, eso es decisión de cada grupo.

Cualquier otra cosa decime

**Comment by cmedrano** [comment]
Muchas gracias, 

Entiendo, pero al hacer DROP y CREATE tambien voy a ´pasar primero por la memtabla en el caso de DROP para borrar los registros y el metadata de la tabla a borrar. Luego recién voy a borrar en el archivo.
Lo mismo para el Create voy a pasar por Memtable para preparar el área memtable para dicha tabla.

Para el select el enunciado dice:

Esta operación incluye los siguientes pasos:
Verificar que la tabla exista en el file system.
Obtener la metadata asociada a dicha tabla.
Calcular cual es la partición que contiene dicho KEY.
Escanear la partición objetivo, todos los archivos temporales y la memoria temporal de dicha tabla (si existe) buscando la key deseada.
Encontradas las entradas para dicha Key, se retorna el valor con el Timestamp más grande.

Los pasos anteriores se tendría que hacer si la key buscada no esta en la memtable verdad?
En el caso que se encuentre la key  en la memtable lo devuelvo directamente desde la memtable y no voy a buscar a los archivos verdad?
En el caso que no se encuentre entonces si voy a buscar la key en los archivos y luego inserto ese value encontrado en la memtable?

Con respecto a lo que hace el INSERT me queda surge una duda,
EL enunciado dice lo siguiente:
Esta operación incluye los siguientes pasos:
Verificar que la tabla exista en el file system. En caso que no exista, informa el error y continúa su ejecución.
Obtener la metadata asociada a dicha tabla.
Verificar si existe en memoria una lista de datos a dumpear. De no existir, alocar dicha memoria.
El parámetro Timestamp es opcional. En caso que un request no lo provea (por ejemplo insertando un valor desde la consola), se usará el valor actual del Epoch UNIX.
Insertar en la memoria temporal del punto anterior una nueva entrada que contenga los datos enviados en la request.

Entiendo que si la tabla existe en la memtable hago el insert sobre la misma y listo, luego el proceso DUMP cuando sea el tiempo de ejecutar va a bajar los datos de la memtabla a los archivos. Es decir solo va a bajar los datos de la memtable a los archivos cuando se ejecute el DUMP y no en otro momento?
En el caso que no existe en la memtable voy a tener que hacer el insert tanto en el archivo como en la memtable, verdad?

Muchisimas gracias

**Comment by NaylaWinter** [comment]
Con respecto a la consulta de DROP: si, tendrias que vaciar la memtable, las estructuras administrativas de dicha tabla y los directorios de la misma. Para el CREATE deberias asignarle una memtable, crear las estructuras administrativas y crear los directorios.

Cuando te realizan un SELECT vos vas a tener que validar **todos los lugares** en donde pueda estar esa key, esto es: memtable, temporales y particiones originales. Es importante que no siempre vamos a encontrar el valor más actualizado dentro de la memtable, sino que vamos a tener que estar revisando todo.

Supongamos el siguiente ejemplo (voy a considerar un tiempo de dump de 10segundos)
En el tiempo 0 segundos realizo un INSERT en la tabla A, sobre la clave 1, valor "hola", timestamp 100. Ese dato llega al LFS y se almacena en la memtable de la tabla A.
En el segundo 10 esos datos en la memtable pasan por el proceso de dump y quedan en archivos temporales dentro del arbol de directorios. Dado que realice un dump, borro la memtable.
En el segundo 11 realizo un INSERT en la tabla A, sobre la clave 1, valor "chau", timestamp 90. Ese dato llega al LFS y se almacena en la memtable de la tabla A.

Qué paso? El valor de la memtable para la clave 1 esta desactualizado con respecto al que tengo en el archivo temporal, si devuelvo el que tengo en memtable entonces no voy a estar respondiendo con el último valor que toma esa clave.

Me hace un poco de ruido lo que mencionas de _"En el caso que no se encuentre entonces si voy a buscar la key en los archivos y luego inserto ese value encontrado en la memtable?"_. Una vez que vos encuentres el último valor para la Key simplemente vas a retornar el valor, sea por consola o por sockets, dependiendo de dónde haya venido la request. En la memtable se guardan los valores que llegan al LFS mediante la consulta **INSERT**, y que luego hay que persistir en los archivos finales, no vamos a estar actualizandola cuando se haga un SELECT.
Sobre este último punto te pido que si te quedan dudas consultes porque es muy importante que se entienda bien la lógica de la memtable y en qué operaciones influye.

Sobre el punto del INSERT: los datos se van a estar bajando de memtable a los archivos temporales mediante el proceso de DUMP y solo mediante este proceso(luego pasarán a los archivos originales mediante la COMPACTACIÓN). 
Si cuando realizan el comando CREATE de una tabla vos reservas un espacio en memoria para la memtable de la misma entonces nunca se va a poder dar el caso que al realizar un INSERT no vayas a tener nada creado, simplemente vas a tener que "agregarle" el nuevo registro que te acaban de insertar. De todas formas, nunca ante un insert vas a directamente insertar el valor en el archivo, **siempre** debe pasar antes por la memtable.

Te recomiendo chusmear el anexo de ejemplos al final del tp o la presentación del mismo en donde se ve cómo es el flujo de los datos en cada una de las distintas operaciones a ver si eso ayuda a aclarar las dudas

**Comment by cmedrano** [comment]
Muchas gracias, me quedo más claro!

Con respecto al ejemplo que mencionaste de tener en la memtable un valor desactualizado, me di cuenta entonces que es posible  que por consola hagan un insert con un timestamp que no es el mayor a todos los timestamp que tiene una key, ya que si no, no sería posible que el segundo insert del ejemplo que mencionaste tenga un timestamp menor que el primero.

Entonces la bajada de datos de la memtable a los archivos solo se hace por a través del proceso DUMP, **y este solo es ejecutado cada n cantidad de tiempo según archivo de configuración y no  puede ser llamado en otro momento**, verdad?

Muchisimas gracias

**Comment by cmedrano** [comment]
Perdón me falto aclarar que al momento de un Create, solo voy a crear un nodo para la lista de tablas que va a tener los datos de la memtable, dentro de esta estructura va haber un puntero a la lista de registros. Luego cuando venga el primer insert la lista de registros de dicha tambla va estar vacía y la lista de tablas tendrá  el nodo de la tabla ya creada.

La estructura sería una lista de listas.

Muchas gracias

**Comment by NaylaWinter** [comment]
1) Claro, podremos realizar por consola inserciones con timestamps desactualizados. La idea es que ustedes puedan devolver siempre el mas actualizado, corroborando los timestamp de todos los valores que encuentren para esa key-

2) Si, el dump es un proceso que corre solo cada cierta cantidad de tiempo que es configurable. No se puede realizar de otra forma.

3) Me parece bien el enfoque que le estas dando a la implementación.

Cualquier otra consulta decinos

**Comment by cmedrano** [comment]
Muchisimas Gracias Nayla!

Cierro issue!
