### ISSUE TITLE
Duda memoria = cpu?

### ISSUE THREAD

**Issue by afondevilarevelli** [sisoputnfrba/foro#1328]
Hola, tengo una duda. Cuando el Kernel selecciona una memoria para un script determinado, y por ejemplo el quantum es de 3, ese script ejecuta las 3 sentencias en la misma memoria? O por cada sentencia se debe reelegir la memoria en base a los criterios?
   Por ejemplo, puede pasar que el script tenga las siguientes sentencias:
_ create tablaLoca SC 5 3000
_ create tablita SHC 4 4000
_ insert tablaLoca 1 "Locura"
_ insert tablita 1 "blabla"
_ drop tablita
_ drop tablaLoca

   Suponiendo que el quantum es mayor a 1. Se selecciona el script para ejecutar y teniendo en cuenta el criterio de la tabla a crear ( SC ) se debería mandar a ejecutar esa sentencia a la memoria que tenga SC. Las dos sentencias que siguen se ejecutarían en la misma memoria? Por que si se tendría que reelegir la memoria, la segunda sentencia se debería ejecutar en una memoria que tenga el criterio SHC.

   Resumiendo, cada memoria se trataría como una unidad de procesamiento? Una vez seleccionada la memoria, se ejecutaría todo el quantum ahí?

**Comment by NaylaWinter** [comment]
Buenas,

Por cada una de las request vas a realizar todo el proceso de elección de memoria, cada sentencia se enviará a ejecutar a la memoria que corresponda.

El quantum simplemente te indica cuántas request se le permiten realizar a ese script "cada vez" que entre en un estado de Exec, después cada linea que corras dentro de tu quantum es independiente de las demas.

**Comment by afondevilarevelli** [comment]
Ahh bueno. Muchas gracias!

**Comment by iago64** [comment]
@afondevilarevelli la duda quedo clara? se puede cerrar? 👮

**Comment by afondevilarevelli** [comment]
Sisi, clarísimo. Gracias
