### ISSUE TITLE
File system - Bloques

### ISSUE THREAD

**Issue by cmedrano** [sisoputnfrba/foro#1329]
Hola, 
estaba viendo el ejemplo de a aclaración sobre bloques del file system y me surgio una duda.
https://www.utnso.com/aclaracion-sobre-bloques-del-file-system/

En el ejemplo hay una tabla X que tiene 3 particiones, la partición 0 va ocupar los bloques 1 y 37. 
¿ Puede  ser que haya otra partición de otra tabla Y que este utilizando alguno de esos bloques(1 o 37)?
¿o otra partición de la misma tabla X que este utilizando alguno de esos mismos bloques (1 o 37)?

¿Otra duda es puede ser que en los tests ya nos den los archivos creados con los bloques y los .bin ya creados con los datos adentro? es decir puede que carguen todos las tablas a mano sin tener que pasar por alguna de las consolas de los tres procesos creando las tablas y luego haciendo los insters para cargar las mismas?

Muchas gracias

**Comment by MaximilianoFelice** [comment]
Buenas!

Los bloques de un FileSystem se corresponden con un archivo. Cada archivo de cualquier FS va a tener: 

- Metadata asociada: La carpeta dónde está, la fecha/hora de creación, los permisos, etc. Parte de los metadatos, además, es saber qué bloques de bytes lo componen (y en qué orden).
- Los bloques de bytes: que tienen el contenido posta del archivo.

Yendo al TP y al ejemplo, los bloques 1 y 37 se corresponden con el archivo de la partición 0. No hay forma de que en nuestro FS dos archivos compartan los mismos bloques (incluso, en la vida real, también es muy extraño), por lo que tampoco va a suceder que haya otra tabla u otra partición usando el bloque 1 y 37.

Cabe notar que, luego de la compactación, los archivos viejos son borrados y los bloques, liberados, por lo que seguramente se utilizarán para los próximos archivos que se creen.

Puede pasar (y es bastante posible) que nosotros les demos un FileSystem que cumpla la especificación del TP con la información ya creada para las pruebas de la entrega.

Saludos!

**Comment by cmedrano** [comment]
Muchas gracias Maxi!

**Comment by cmedrano** [comment]
Si esta la posibilidad de que se carguen todos los archivos .bin , archivos .tmp etc. Es decir si nos dan un File System con los datos cargados entonces si mal no recuerdo nos dieron la posibilidad de llamar a los archivos de diferente manera pero se debe respetar la extencion, por ejemplo el archivo 1.bin se puede llamar particion1.bin o particion_1.bin o partition1.bin etc. Lo que me hace ruido es que nosotros no vamos a saber que nombre le van a poner a los archivos en los test por lo tanto no sabría como hacer para saber a que particion pertenece un archivo .bin se entiende?
por ejemplo si yo sabría que las particiones se van a llamar 0.bin y 1.bin entonces podría desarrollar una funcion para que me devuelva el numero de particion de acuerdo el nombre entonces la particion 0.bin será la particion 0 y 1.bin sera la particion 1. El nro de partición me va a servir para luego poder saber a que particion ir a buscar un dato ante un select por ejemplo.
Caso contrario, me parece que si no se como se van a llamar los nombres de los archivos va ser un poco dificil desarrollar una función que me devuelva el nro de particion segun el nombre.
Puede que este equivocado pero estoy desarrollando esta parte ahora y me surgio esa duda.

Muchas gracias

**Comment by cmedrano** [comment]
perdón, se entendió la duda?
Gracias

**Comment by MaximilianoFelice** [comment]
Buenas! Perdón por la demora. 

Creo que te entendí, pero cualquier cosa decime.

En el caso que les demos un FileSystem seguramente los archivos estarán nomenclados de forma tal que en el nombre aparezca el número de partición, siendo 0 la primera.

Luego de eso, lo único que tienen que hacer ustedes es extraer el número del nombre. Si es que necesitan hacer alguna adaptación, van a tener tiempo para hacerla, pero debería ser mínima, ya que es solo un prefijo/sufijo.

Saludos!

**Comment by cmedrano** [comment]
bueno muchas  gracias, nosotros lo estamos implementando el nombre compuesto solamente por el número de la partición como los ejemplos del enunciado del trabajo practico, ojalá se pueda mantener ese formato para los test, en otro caso lo vamos a modificar para acomodarnos a las pruebas.

Muchas gracias nuevamente por todo!
Saludos!
