### ISSUE TITLE
Buscamos 1 integrante

### ISSUE THREAD

**Issue by AxelFurlanF** [sisoputnfrba/foro#1330]
Hola gente!
Buscamos 1 integrante. Ya tuvimos una baja en el grupo y queremos seguirlo tranquilos siendo 5. Estamos bastante bien para la primera entrega por ahora, y no queremos ralentizar el trabajo por ser 4.

Pueden contactarme en axel.furlan95@gmail.com

Saludos,

**Comment by afilgueira** [comment]
Hola, para unificar les recomiendo comentar acá: #1331 

Saludos!
