### ISSUE TITLE
Cambios de grupo o integrantes? Entrá acá

### ISSUE THREAD

**Issue by afilgueira** [sisoputnfrba/foro#1331]
Para unificar la "oferta y demanda" creamos este issue. Aquellos que busquen grupo y aquellos que busquen integrantes pueden publicar acá. Al hacer esto, van a quedar suscritos automáticamente a las nuevas respuestas que lleguen y centralizamos la info. Cuando la búsqueda esté cerrada, pueden borrar / editar su mensaje y desuscribirse.

Les recomendamos respetar el siguiente formato:

Busco grupo / Buscamos N integrantes
Nombre de grupo / persona
Curso
Mail o datos de contacto (opcional, esta en el perfil de github)
Comentarios
Un detalle a tener en cuenta a la hora de dejar info de contacto: este foro es público (para cualquiera con cuenta en github).

Éxitos con eso!

**Comment by AxelFurlanF** [comment]
Buscamos 1 integrante
Grupo RYZEN
K3051 viernes noche, profesor Dan Balabunek
Contacto: axel.furlan95@gmail.com


Estamos bastante bien para la primera entrega. Hilos implementados. Sockets en proceso de terminar y consola terminada.

Priorizamos disponibilidad de respuesta y comunicación, y  levantar la mano cuando se está trabado, antes que ser un crack en C.

**Comment by pablo4225** [comment]
Buscamos 1 integrante
Nombre de grupo: arpuebame_o_morire
Curso 3055 (Sábados tarde, pero es lo de menos)

Nuestro grupo tiene lugar para una persona que tenga ganas de aprobar la materia. Que pueda mantener una comunicación fluida.

Cualquier cosa, comenten.

Gracias!!!

**Comment by sebastianvicente** [comment]
Buscamos 1 integrante
Nombre de grupo: dale_que_SO_vo
Curso 3053 (Martes Noche, Masoero) / 3054 (Miercoles Noche, Adriano)
Contacto: gimenoguido@gmail.com / nicolas.bernardelli@gmail.com / her.mateika@gmail.com / vicente.sebastian.ariel@gmail.com

Nuestro grupo quiere aprobar la materia este cuatrimestre y todos estamos comprometidos para ayudarnos entre nosotros a poder destrabar cualquier tema.

**Comment by benjamd** [comment]
Buscamos 2 integrantes
Nombre de grupo: LOS HIJOS DEL DIEGO
Cursamos Viernes Noche / Sabado Tarde 
Contacto: benjaexmachina@gmail.com / ojedashernan@gmail.com / romerocristianezequiel@gmail.com

**Comment by jsarrelli** [comment]
Buscamos 1 integrante.
Nombre de grupo: Los-Sisoperadores
Curso: k3013  / k3011 (nos juntamos los sábados o a veces en la semana)
Contacto : julisarrelli@gmail.com - 1138065093

Nos esta faltando un integrante, cualquier persona que tenga ganas de meterle y aprobar la materia este cuatrimestre es mas que bienvenida. (Por si eso no convence el que se quiera sumar a nuestro grupo tiene una docena de facturas de regalo)

**Comment by alejoUTN** [comment]
Buscamos grupo (somos 2)
- Alejo Aceval
- Kevin Wagner

Nombre de grupo: Kassadin

Cursos:
-K3051 (Lunes noche - Esquivel) 
-K3011 (Martes mañana - Nardiello)

Contacto : acevalalejo@gmail.com

Somos 2 integrantes que quedaron a la deriva pero quieren aprobar a toda costa.

Gracias.

**Comment by matiasBusco** [comment]
Buscamos 1 integrante

> Buscamos grupo (somos 2)
> 
> * Alejo Aceval
> * Kevin Wagner
> 
> Nombre de grupo: Kassadin
> 
> Cursos:
> 
> * K3051 (Lunes noche - Esquivel)
> * K3011 (Martes mañana - Nardiello)
> 
> Contacto : [acevalalejo@gmail.com](mailto:acevalalejo@gmail.com)
> 
> Somos 2 integrantes que quedaron a la deriva pero quieren aprobar a toda costa.
> 
> Ya tenemos el 95% del proceso FS hecho.
> 
> Gracias.

Estamos interesados que te unas a nuestro grupo, te mande un mail

**Comment by DianaMamani** [comment]
Buscamos grupo (somos 2)

Diana Mamani
Camila Mamani

Nombre de grupo: Equipo Socket

Curso: K3052 (Viernes noche - Dan Balabunek)
Contacto : dianamamanillan@gmail.com

Tenemos ganas de aprobar y meterle a la materia.
Gracias

**Comment by damianKreuter** [comment]
Buscamos 1 integrante

Grupo mi_ultimo_segundo_tp

Cursos:

K3013
K3113
K3055

Contacto: damiakreuter@outlook.com

Estamos buscando gente que se conprometa con el tp, y mantener mucha comunicacion en el grupo y cooperacion

**Comment by franchupedu** [comment]
Buscamos 1 integrante
Grupo: Pichones-MilenariOS
Curso: K3011 (Martes a la mañana)

Se nos bajo un integrante hace relativamente poco. Somos un grupo muy laburador e intercmunicado, no te va a ser muy difícil encajar ni superar las ganas de laburar del que se fue...

Si te interesa contactanos a: franchupedu@outlook.com

Gracias por considerarnos, que tengan un buen día!!

**Comment by Fedryus** [comment]
Buscamos grupo, somos 2.

Cursos:

- K3013
- K3113 

-ambos sábado a la mañana-

Estamos buscando un equipo, el nuestro quedó en la nada después de las charlas de Medrano.
Llegamos a ver lo básico del TP, pero estamos dispuestos a trabajar todo lo que se pueda y ayudar en lo que sea necesario.

Contactos:

ezequieltardieu@gmail.com
federicoaseijo@gmail.com

**Comment by Santiago-Lovelli** [comment]
> Buscamos 1 integrante
> Grupo: Pichones-MilenariOS
> Curso: K3011 (Martes a la mañana)
> 
> Se nos bajo un integrante hace relativamente poco. Somos un grupo muy laburador e intercmunicado, no te va a ser muy difícil encajar ni superar las ganas de laburar del que se fue...
> 
> Si te interesa contactanos a: [franchupedu@outlook.com](mailto:franchupedu@outlook.com)
> 
> Gracias por considerarnos, que tengan un buen día!!

Hola fran, sigue necesitando a uno? soy del curso de nardiello tambien. Si necesitan contestame que te mande un mail tambien. Saludos

**Comment by micaD** [comment]
Buscamos un integrante
Grupo: Segmentation-Fault
Curso: K3051
Hola estamos buscando un integrante, ya que se nos bajo uno hace muy poco. Se sumaria a la parte de file system. Queremos meterle al tp y aprobar la materia.
La mayoria cursamos lunes noche. 
Contacto: mica965@hotmail.com

**Comment by damianKreuter** [comment]
Se nos bajó 1 compañero debido a una causa externa que le imposibilita seguir con la cursada

Grupo mi_ultimo_segundo_tp

K3013 2 integrantes MAÑANA SABADO
K3055 1 integrante   MAÑANA SABADO
K3052 1 integrante   VIERNES NOCHE

Contacto: damiankreuter@outlook.com

Estamos buscando gente que se conprometa con el tp, y mantener mucha comunicacion en el grupo y cooperacion y que aporte ideas

**Comment by micayeza** [comment]
Buscamos grupo (somos 2)
Nombre de grupo: Somos-root

Cursos:
Martes mañana - Nardiello
Miercoles y Jueves mañana - Nardiello
Contacto : micayeza@gmail.com

Somos dos compañeros que tenemos bastante adelantada la memoria y el kernel.
Necesitamos gente que se sumen para desarrollar el FS.
Gracias!

**Comment by MatiCoarasa** [comment]
Buscamos grupo, somos dos personas.
Cursamos con Nardiello miércoles y jueves a la mañana. 
Tenemos desarrollado parte del LFS.

Lamentablemente se nos dieron de baja tres compañeros el día de ayer, así que si algún grupo nos puede recibir estaríamos muy agradecidos.

**Comment by MatiCoarasa** [comment]
Cursamos con Nardiello miércoles y jueves a la mañana.
Tenemos desarrollado parte del LFS.
Contacto: mscoarasa@hotmail.com 

Lamentablemente se nos dieron de baja tres compañeros el día de ayer, así que si algún grupo nos puede recibir estaríamos muy agradecidos.

**Comment by ivojawer** [comment]
Buscamos dos integrantes.
Grupo: U-TN Tecno
Contacto: ivojawerbaum@gmail.com 

Tenemos el Kernel muy avanzado así que necesitaríamos que los que se sumen trabajen en la memoria y el LFS.

**Comment by suumoo5** [comment]
Buscamos 1 integrante.
Grupo: UnNombre
Contacto1: laureano.cavallo@gmail.com
Contacto2: jkhalilsilva@gmail.com
Estamos necesitando alguien que pueda trabajar con Kernel ya que en Memoria y FileSystem venimos en regla con los checkpoints.

**Comment by Santiagobelogi** [comment]
Buscamos 1 integrante para completar
Grupo: SudoMakeTp
Contacto : santiagotbelogi@gmail.com
Facundofraguaga@hotmail.es

**Comment by AxelFulop** [comment]
Buscamos 1 integrante para sumarse al proceso Memoria
El Kernel esta listo y FS  viene en regla, terminando el dumpeo y la compactacion
Memoria viene bien pero necesitamos alguien que le de una mano al que esta con memoria
Grupo: C o no C
contacto: axelfulop@hotmail.com

**Comment by EstebanMellado** [comment]
Buscamos 1 integrante
Grupo: Targaryen
Curso K3051 y K3054
Necesitamos 1 más para LFS

**Comment by afilgueira** [comment]
Cierro este issue, aprovechando el cierre en los cambios de grupo. Saludos!
