### ISSUE TITLE
Desconfiguración Ntp

### ISSUE THREAD

**Issue by badialeo96** [sisoputnfrba/foro#1332]
Tengo un problema con NTP en la VM. 
La primera vez lo instalé sin problemas corriendo el script en la terminal:
curl -L faq.utnso.com/script-ntp.sh | bash
Pero hay veces que se me desconfigura. No encontré ninguna aparente causa ya que no me pasa siempre que apago la máquina virtual o guardo el estado, ni cuando me desconecto de internet o cambio de red, es como si fuera algo aleatorio.
Cuando se me desincroniza la hora ejecuto ntpstat y recibo como respuesta:
Unable to talk to NTP daemon. Is it running?
Lo que estoy hacieno cuando me ocurre esto es volviendo a correr el script para instalarlo, modificando la configuración del ajuste horario a manual, volviéndolo a poner a sincronizado con servidores y recién ahí cuando vuelvo a correr el script de instalación se me instala bien. 
Es algo tedioso pero tiene solución, por eso más que nada la pregunta que me surge es si esto puede llegar a pasar en la vm server donde se ejecutan las pruebas, y puedo llegar a tener problemas con esto durante la ejecución de alguno de los casos de prueba.

@iago64 

Gracias!

**Comment by iago64** [comment]
Buenas buenas!

Mil gracias por crear el issue asi nos queda de respaldo para todos los que puedan estar teniendo este problema.
En el momento que te tira ese error es porque no esta funcionando el servicio de fondo, para checkear si el servicio esta funcionando deberian tirar el comando: 
`systemctl status ntp`

y en caso de que este caido, para reiniciarlo pueden usar:
`sudo systemctl restart ntp`

Una vez reiniciado el servicio, debería sincronizar la hora correctamente. 
La caída puede deberse a un cambio en la red de la maquina virtual, cosa que en el laboratorio no les va a pasar, o no debería pasarles ya que van a estar siempre en la misma red :)

Espero haberte podido ayudar.
Abrazo!!

**Comment by tferraro** [comment]
@badialeo96 como viene eso? Te sirvió la respuesta de Dami?

**Comment by badialeo96** [comment]
Sí, gracias!
Cierro el issue.
