### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by GonzaOrtega** [sisoputnfrba/foro#1333]
Consulta, que framework recomiendan para hacer tests para el tp??

**Comment by gastoncastineira** [comment]
Tenés instalado en las vms Cunit y hay un apunte de eso en el blog.
También está dando vueltas Cspec, desarrollado por Federico Scarpa (docente de otra materia).
Ambos sirven para testear módulos puntuales dentro de un proceso. Para testear en un ambiente distribuido (estoy en memoria y me llegan tales datos del kernel, por ejemplo), no te va a quedar otra que hacer un módulo tonto que simule ser el que tenga que ser y envíe datos hardcodeados que sepas que funcionen

**Comment by martinzuccotti** [comment]
Hola. Al querer acceder al apunte de Cunit me dice que el archivo fue eliminado

**Comment by gastoncastineira** [comment]
Buenas! Perdón por la tardanza. Estuvimos estos días tratando de descubrir qué pasó con el documento, así que gracias por avisar!
El link se encuentra arreglado, y agregamos un documento con Cspec también para los interesados. 
Por favor, que el responsable cierre el issue cuando lo lea
