### ISSUE TITLE
Problema con timestamps

### ISSUE THREAD

**Issue by Dragonflares** [sisoputnfrba/foro#1334]
Buenas tardes a todos

Basicamente escribo porque tuve algo medio extraño hoy al mediodia:

![imagen](https://user-images.githubusercontent.com/28828524/57183310-2d381f00-6e81-11e9-8b4e-6c8b385e6e0f.png)
![imagen](https://user-images.githubusercontent.com/28828524/57183334-b9e2dd00-6e81-11e9-8ad6-50b28fd1852c.png)

En teoría, cuando uno no pone el timestamp desde la consola se debe asignar uno, y eso fue algo en lo que @NaylaWinter y @MaximilianoFelice ayudaron contribuyendo con la funcion getCurrentTime() acá abajo: 

![imagen](https://user-images.githubusercontent.com/28828524/57183374-8bb1cd00-6e82-11e9-93e8-3ef949426739.png)

La función funcionaba perfectamente hasta hace 20 horas, aproximadamente? Y ahora, en vez de devolver un timestamp común y corriente como venía devolviendo, me devuelve un número negativo. Y dije bueno, tirare un debug a ver que pasa.

![imagen](https://user-images.githubusercontent.com/28828524/57183356-383f7f00-6e82-11e9-843e-228fc7133925.png)
![imagen](https://user-images.githubusercontent.com/28828524/57183358-41c8e700-6e82-11e9-8550-0f8993225167.png)
![imagen](https://user-images.githubusercontent.com/28828524/57183360-47bec800-6e82-11e9-897b-358d3501aaea.png)

Y si uno ve esas tres imagenes se queda pensando, como puede ser que teniendo 2 numeros positivos quede en negativo?

Alguna idea de por que esta funcion paso de andar bien a romper de un día para otro? Ya arregle las NTP incluso, no viene por ahí el error.

**Comment by Dragonflares** [comment]
Agrego que vi este problema con los ayudantes del soporte de hoy, y probamos multiples maneras de asignar la variable, para ver si en algún lugar habia basura presente, pero nada, así que me pidieron que abra este issue.

**Comment by MaximilianoFelice** [comment]
Buenas! Como va?

Recién traté de reproducir el issue y no pude, me sigue dando el valor correcto. Alguien más puede confirmar/probar?

Saludos

**Comment by Dragonflares** [comment]
![imagen](https://user-images.githubusercontent.com/28828524/57184816-a6427100-6e97-11e9-8751-bc91f98f5b01.png)

Bueno,d espués de un rato buscando y con varios consejos más, descubrí que aparentemente la división jodía con los tipos de time_t y el s_usec, así que parcheando con unsigned long long, permite que los tipos se cambien antes y entonces la división se pueda hacer. 

Dato: No se puede usar double, porque entonces empieza a devolver con coma.
