### ISSUE TITLE
Importar modulo de serealizacion

### ISSUE THREAD

**Issue by mesaglio** [sisoputnfrba/foro#1335]
Hola, queria saber si era la manera correcta de incluir otro proyecto como biblioteca.
Armamos un proyecto llamado comun,donde desarrollamos todas las funciones de serealizacion, con su respectivo comun.h y comun.c 

Para poder inlcuirlo al modulo "memoria" hice:
Click-Derecho en el proyecto memoria, Propiedades.
C/C++ General >>Paths and Symbol
En la pestaña de include >> Lenguages GNU C >> Add  >> File system >> comun/src

Despues en memoria.h, agregue la linea: #include "comun.h"

Eso me modifico:
	modified:   memoria/.cproject
	modified:   memoria/Debug/src/subdir.mk
y me creo:
        memoria/.settings/org.eclipse.cdt.codan.core.prefs

**Comment by mesaglio** [comment]
@ncoen97 @tmakd @achani2497 @FrodriguezSandez

**Comment by iago64** [comment]
Buenas buenas!
Consulta, esta biblioteca comun que tienen de seriaización, la tienen en un proyecto exportado como shared library?
Por las dudas peguenle una revisada al video de [shared library en C](https://www.youtube.com/watch?v=Aw9kXFqWu_I) que tenemos en el canal de youtube a ver si resuelve los inconvenientes.

Saludos.-

**Comment by mesaglio** [comment]
La tenemos como un proyecto aparte. Como si fuera otro modulo.

**Comment by iago64** [comment]
Esta bien, pero de que tipo de proyecto estamos hablando? porque puede ser un proyecto comun o un proyecto que se compila como una shared library

**Comment by mesaglio** [comment]
Es un proyecto comun

**Comment by tferraro** [comment]
Sip, porque la forma de compilación no es la misma.

Si cursaste sintaxis, puede ser que te hayan hablado de varias etapas de la compilación. Hay una parte que se denomina "Linker" que solamente se ejecuta cuando vos querés generar binarios. Las bibliotecas, como su objetivo es "ser una porción de código reutilizable", suelen estar "pre-compiladas" pero no están linkeadas a nada. Porque? Porque así cualquier hijo de buen vecino que quiera usarlas, solo necesita "incluirlas" y hacer el linkery (y presto!).

El problema es que, para decirle a eclipse que no haga la ultima parte, tiene diferentes tipos de proyectos 🙂....yyyy por eso tenes que crearlo como shared 😛
