### ISSUE TITLE
Consulta metadata de tablas

### ISSUE THREAD

**Issue by eGoicoechea** [sisoputnfrba/foro#1336]
Buenas tardes,
Estamos en la duda con mi grupo si la metadata es un archivo de configuración. Tenemos entendido que en la misma se encuentran el tipo de consistencia de la tabla, las particiones y el tiempo de compactación, pero no estamos seguros del tipo de archivo que debe ser.
Les agradecemos su respuesta!
Los Raquelitos

**Comment by gastoncastineira** [comment]
Buenas!

Pueden utilizar la config de la commons, pero deben mantener la nomenclatura de *.bin que les solicita el enunciado para sus archivos

**Comment by Dragonflares** [comment]
El tipo de los archivos para levantar a manera de t_config* es indistinto, tanto podes levantar los Metadata sean .cfg como .bin, siempre y cuando la ruta esté bien. Así que con las funciones de config.h de las commons te alcanza y te sobra.
Ahora, tengo una duda, porque yo había leído en el enunciado (en el ejemplo de tabla lo muestra) que los Metadata de cada tabla son .cfg, mientras que las particiones si son .bin. Estoy equivocado?

**Comment by gastoncastineira** [comment]
Nop. Todos los archivos de metadata son del estilo .bin
El tema es que para simplificar el TP les hacemos que tengan formato de archivo de configuración para que puedan usar las commons como muy bien lo dijiste. Tal vez la confusión salga por los ejemplos, pero es así!

**Comment by Dragonflares** [comment]
Igual... mirando acá el Metadata de la tabla no tenía ningún formato especificado. Y medio lo había visto con un ayudante antes y no me dijeron nada, igual, cambiarlo ahora es solo cambiar que cuando los cree los cree como .bin y no como .cfg, no me cambia ni los malloc que uso para marcar la dirección. Pero como sea.

![imagen](https://user-images.githubusercontent.com/28828524/57265778-97062380-704f-11e9-9251-b58f95819885.png)

 Mas que nada porque el create ya está hecho.

**Comment by gastoncastineira** [comment]
Buenas!

Releí el enunciado y efectivamente tenés razón. Los archivos de metadata no llevan extensión (no son ni bin ni cfg), pero el contenido sí es cómo estaba en el ejemplo más arriba y como muy bien dijiste en la primera respuesta.
Te pido perdón, se me cruzaron los cables con el FS del TP anterior que sí tenían .bin los archivos de metadata

**Comment by NaylaWinter** [comment]
Buenas @eGoicoechea se resolvió la duda? En ese caso te pido si podes cerrar el issue, en caso contrario, volver a consultar lo que no quedo claro

**Comment by tferraro** [comment]
Buenas! Cierro el issue por inactividad 🙂 

Cualquier cosa vuelvanlo a abrir sin dudarlo!!
