### ISSUE TITLE
Consulta sobre el bitmap

### ISSUE THREAD

**Issue by Dragonflares** [sisoputnfrba/foro#1337]
Saludos! Como estan?

Tenia una consulta sobre como va a ser el formato del bitmap que nos iban a dar supuestamente. Ya que como tengo que tener previamente las funciones que lo puedan operar, mi duda es si por ejemplo el bitmap en si tiene un 0 o 1 por linea, o son multiples 0s y 1s en la misma línea. Yo actualmente, en mi bitmap.bin (que cree para poderir testeando las compactaciones en tabla) tengo un 0 o 1 por línea, así es mas sencillo para leer o buscar (o eso pensé yo)

**Comment by gastoncastineira** [comment]
Te voy a tener que romper el corazón
Los bitmaps que les vamos a dar no van a ser archivos de texto que contengan una secuencias de 0s y 1s texto, sino que van a ser, justamente, archivos binarios, donde cada 0 y 1 es un bit (en realidad no es tan así pero no lo manejás vos sino el SO).
Vas a tener que utilizar mmap para levantarlo y escribir sobre él, y el bitarray de las commons para manipularlo desde tu programa.

**Comment by Dragonflares** [comment]
JA! 
Bueno, dentro de todo me alegro de haber preguntado antes de haber hecho cualquiera de las funciones de lectura del bitmap. Eso es más interesante dentro de todo. Mi duda es entonces, ¿cuando nos lo van a proveer? Y en otro caso, ¿que manera me recomendás para crear uno temporal?

**Comment by gastoncastineira** [comment]
proveerlo no hay fecha exacta pero probablemente sea dos o tres semanas antes de las entregas
Para crearte uno, podés grabar forma binaria el contenido del bitarray que crees con fwrite, o utilizando el propio mmap (utilizando un pequeño [truncate](http://man7.org/linux/man-pages/man2/ftruncate.2.html) sobre tu bitmap vacío ya creado) y grabar el contenido del bitarray con eso

**Comment by cmedrano** [comment]
Hola, leyendo este issue. Me di cuenta que es probable que nos den un bitmap para saber los bloques libres y ocupados, hay alguna estructura más que nos  van a dar de entrada  para tenerlo en cuenta? ya que esto no lo sabíamos y lo estábamos pensando hacer con  un archivo común  con números 0s y 1s .

Muchas gracias

**Comment by Dragonflares** [comment]
En teoría nos van a dar tanto la estructura de bloques del FS como el bitmap. Sin embargo, hay que tener las funciones que asignen y respondan los datos que se necesitan desde antes, por ende hay que crear un bitmap y bloques para testear.

**Comment by cmedrano** [comment]
A que te referís con la estructura de bloques?

Gracias.

**Comment by Dragonflares** [comment]
La estructura de bloques es uno de los 3 directorios dentro del punto de montaje junto al de las tablas y al que contiene el metadata del FS + el bitmap. Sería donde las claves impactadas en le FS están guardadas, y donde están referenciadas las claves de los .tmp

![imagen](https://user-images.githubusercontent.com/28828524/57648994-69fcc800-759d-11e9-95aa-ad5311a954f9.png)

En otras palabras, los bloques son los cuadraditos de abajo, que están referenciados por las particiones

**Comment by cmedrano** [comment]
Perfecto, entonces entiendo que nos van a pasar todo el FS!

Muchas gracias
