### ISSUE TITLE
Problema con el update de la VM

### ISSUE THREAD

**Issue by Dragonflares** [sisoputnfrba/foro#1339]
Buenas! Como les va?

Hace como mas de 3 o 4 semanas que vengo tratando de updatear la VM (con los updates esos que caen de seguridad y etc) y me salta este archivo de error despues de que se crashea el update inmediatemente arranca:

![imagen](https://user-images.githubusercontent.com/28828524/57573072-44cf5480-73f9-11e9-8171-1f7516094335.png)
 
Y dentro del archivo dice ésto:

![imagen](https://user-images.githubusercontent.com/28828524/57573081-5ca6d880-73f9-11e9-8913-960d13d1011a.png)

Sin embargo tengo como 40gb de espacio libre? Que se rompió?

**Comment by gastoncastineira** [comment]
updatear estamos hablando de todas las actualizaciones que aparecen cuando prendés la VM?

Como cátedra recomendamos no actualizarla, ya que se puede dar el caso que alguna biblioteca relacionada al TP cambie y después el día de la entrega algo no les compile o funcione como deba.

Dicho eso, en cuanto al error no estoy completamente seguro, pero ahí dice que lo que falta es memoria, no disco. Puede que poniendo más RAM ande
otra razón puede ser que Lubuntu de 32 bits perdió soporte hace unos meses. Tal vez se deba por eso también

**Comment by Dragonflares** [comment]
Tengo 4gb de ram asignados a la VM, me tiraria a pensar que no le dan los 32 bits para direccionar el tamaño de memoria de manera correcta, cierro el issue nomas, Gracias!
