### ISSUE TITLE
Consultas varias sobre API en memoria

### ISSUE THREAD

**Issue by mesaglio** [sisoputnfrba/foro#1340]
Buenas, aca van varias consultas.
 - Comando **CREATE**:
Cuando le llega CREATE a la memoria, lo unico que hace es pasarle el comando a LFS y esperar el resultado. Tanto creada la tabla o error porque ya existia. Suponiendo que ese create vino por parte del kernel, la memoria le envia el resultado tambien a el. La memoria actuaria como "pasamanos", en este caso??
 - Comando **DESCRIBE**:
Al ejecutar el DESCRIBE de un tabla en especifica, hay que devolver como resultado del comando toda la informacion que se encuentra en el metadata??

**Comment by NaylaWinter** [comment]
Buenas!

La respuesta a ambas preguntas es que si. En el primer caso la Memoria funcionaría como pasamanos, lo mismo te va a pasar por ejemplo con el comando DROP.
El describe debe devolver la metadata de la tabla pedida, o la metadata de todas las tablas en el caso de que no se especifique ninguna.

**Comment by mesaglio** [comment]
Gracias
