### ISSUE TITLE
Consulta de baja de integrantes

### ISSUE THREAD

**Issue by GonzaOrtega** [sisoputnfrba/foro#1341]
Una consulta, cuando se baja un integrante cuenta como el único cambio de grupo que se puede hacer??

Gracias

**Comment by gastoncastineira** [comment]
No, pero si pueden hacer todos los cambios en una sola solicitud nos ahorran más trabajo a nosotros

Saludos

**Comment by GonzaOrtega** [comment]
Otra consulta, puede ocurrir que los miembros restantes se cambien a diferentes grupos dejando el grupo original vacío??

**Comment by iago64** [comment]
@GonzaOrtega Si, es posible, no te preocupes por ese tema :)

**Comment by GonzaOrtega** [comment]
Gracias!!!
