### ISSUE TITLE
Uso de gettimeofday() con uint32_t

### ISSUE THREAD

**Issue by ncoen97** [sisoputnfrba/foro#1342]
Buenas, intentamos cambiar el time() por el gettimeofday() y nos funcionó. El tema es que nosotros tenemos el timestamp definido como un uint32_t, y cuando quiero pasar el resultado de double a uint32_t, me cambia el valor y el signo. Puede ser que tenga que ver con el tamaño? Gracias.

![image](https://user-images.githubusercontent.com/7952790/57632257-900f7180-7577-11e9-99eb-bdbbfb9c9858.png)

**Comment by gastoncastineira** [comment]
Buenas!

El tema con esos tipos de datos es que no te dan los bytes para redireccionar el tamaño, y probablemente se termine desbordando el entero y te de esa representación que es basura.
uint32 es un seudónimo que una biblioteca estándar de C le da al tipo unsigned int, el cual pesa 4 bytes y como es no signado puede direccionar con los 32 bits (osea 2^32, 4 millones y pico, que como ves se queda bastante corto).
Double, en cambio, pesa 8 bytes porque necesita representar lugares después de la coma. Al no tener nada después de la coma, está usando algunos de esos bits para representar el número que le das y funciona (2^64, que si no me fallan las cuentas son 308 dígitos, obviando el tema de los decimales y el bit de signo). 
Ahora, vos no querés perder algunos de esos bits en representar los decimales porque el timestamp no tiene. Te recomendaría probar cambiando a un uint64_t, que es lo mismo que un unsigned long, que pesa 8 bytes y usa todos los bits para representar el valor entero.
Capaz [esto ](https://www.tutorialspoint.com/cprogramming/c_data_types.htm)te ayude a cerrar más la idea. Cualquier cosa volvé a escribir

**Comment by Dragonflares** [comment]
@ncoen97 también si querés proba mirar el issue #1334  , tiene funciones que por ahí te sirven para usar los tipos de datos

**Comment by ncoen97** [comment]
Intente de distintas maneras y el printf me seguía dando mal, pero debugueando termine llegando al valor esperado.
