### ISSUE TITLE
Leer los nombres de los archivos de un directorio

### ISSUE THREAD

**Issue by cmedrano** [sisoputnfrba/foro#1344]
Hola!

Estamos intentando leer los nombres de los archivos de una carpeta para luego abrir cada archivo y buscar un valor.
Al momento de leer un directorio por ejemplo cuando llega un select al LFS, estamos intentando leer por ejemplo todos los archivos .tmp que tengo en el directorio TablaA.
Hay alguna función que me pueda ayudar a hacer esto? estábamos utilizando la función System para ejecutar un comando ls de la shell y luego guardar el resultado con los nombres de los archivos en un archivo temporal, pero luego nos dimos cuenta que system tiene dificultades para programas multi hilo.

Muchas gracias

**Comment by gastoncastineira** [comment]
Ya les respondí el mail que me mandaron. Cerramos issue?

**Comment by cmedrano** [comment]
Si Gaston! muchas gracias!
