### ISSUE TITLE
Kernel - Sentencias scripts

### ISSUE THREAD

**Issue by afondevilarevelli** [sisoputnfrba/foro#1345]
Hola, una consulta sobre el Kernel. Dentro de los scripts de las sentencias, se ejecutarían CREATE, INSERT, SELECT, DROP y desde la consola del Kernel se ejecutarían ADD, JOURNAL, METRICS, RUN y DESCRIBE, no?

En resúmen, cuáles serían las sentencias que ejecutan los script que nos van a dar?

**Comment by NaylaWinter** [comment]
Buen día,

La API (es decir, todas las sentencias) deben poder ser ejecutadas desde cualquiera de los dos lugares(consola y scripts).

Si la pregunta viene asociada a saber de antemano qué comandos se deben tener en cuenta para parsear el script: deberías poder parsear todo en todos lados, después nosotros elegimos a discreción que correr en qué lugar

**Comment by NaylaWinter** [comment]
@afondevilarevelli como venís con esto? Si seguís teniendo dudas te pido me digas, sino si podes cerrar el issue
