### ISSUE TITLE
Consulta sobre config_set_value

### ISSUE THREAD

**Issue by Dragonflares** [sisoputnfrba/foro#1346]
Saludos!

        Estuve probando para la escritura de los .tmp, usar la funcion config_set_value, ya que cuando yo creo el .tmp originalmente, yo lo estoy creando como si fuera una particion vacía, y luego de que está creado, le asigno todos los bloques que use para almacenar las claves de dicho .tmp y le size del mismo. Ahora, para poder actualizar un archivo sin borrarlo completamente.

![imagen](https://user-images.githubusercontent.com/28828524/57702730-11790980-7635-11e9-9bb4-d4982b4e8138.png)

Estuve siguiendo la ejecución, viendo que todas las variables se asignaban correctamente. Hasta llegar a ésta parte:

![imagen](https://user-images.githubusercontent.com/28828524/57702837-42f1d500-7635-11e9-90fd-58bcaf32ae23.png)

El archivo de configuracion temporal (que es en si el 0.tmp) lo levanta, pero por algún motivo el config_set_value no hace ni devuelve nada del archivo, no salta ningun error, ni me llega ni un segmentation fault. Hay algo que estoy haciendo mal? O algo que le falle al sistema?

**Comment by gastoncastineira** [comment]
Buenas!

Es un tantito complicado de explicar en detalle cómo funciona por dentro config, pero explicado muy por arriba lo que hace cuando hacés un create, levanta todo lo que está en el archivo y se lo guarda en una estructura llamada diccionario (que también es parte de las commons). Cada vez que hacés get, te devuelve algo que tenés en el diccionario, no en el archivo. Por lo tanto, cuando hacés un set, se agrega la entrada en el diccionario en memoria, no en el archivo. Para bajar el contenido a archivo tenés que guardarlo, y estoy 100% seguro que había una función con el estilo config_save o algo así para hacerlo

**Comment by Dragonflares** [comment]
Muchisimas gracias! Era eso lo que estaba faltando, no entendía por que no escribía nada. Ahora, hacer eso también sirve si lo quiero actualizar a algo que ya tiene un valor de antes? Osea que funciona como un strcpy o una asignación?

**Comment by gastoncastineira** [comment]
No entendí. Decís de hacerle set a una clave ya existente? Depende de la implementación del diccionario. Lenguajes de más alto nivel como C# explotan cuando hacés set a una clave ya existente, y expone otro método para modificarlos. En Java (que ahí se llama Map), es llamado upsert, modifica (UPdate) si existe e inserta (inSERT) si no.
En el caso de las commons no estoy del todo seguro de cual era, pero me tiro más por el lado del upsert

**Comment by Dragonflares** [comment]
Estuve viendo si habia algo de upsert y no vi nada, lo mejor que vi es usar un dictionary_remove para remover la key y el valor que ya tienen y hacer un dictionary_put con los nuevos, el tema es que no se como modificar el dictionary del t_config, a no ser que le pase como t_dictionary al t_config->t_dictionary por ejemplo.
En caso de ser asi, después solo tendría que hacer un config_set_value y config_save para modificar los valores preexistentes en los archivos de tipo particion durante una compactación, por ejemplo.

**Comment by gastoncastineira** [comment]
no me entendiste. upsert como concepto, no nombre. put probablemente sea un upsert. 
Pero igualmente config_set hace un put por dentro, así que debería funcionar. Si dudás de mi palabra, siempre podés mirar el código de la commons o probarlo vos antes de llevarlo a tu TP, pero sí te recomiendo fuertemente que no toques vos directamente las estructuras y que utilices las funciones que les damos

**Comment by Dragonflares** [comment]
Dale gracias, pude hacer una prueba y funciono bien de momento! Cierro issue!
