### ISSUE TITLE
Registros repetidos

### ISSUE THREAD

**Issue by GonzaOrtega** [sisoputnfrba/foro#1347]
Se que en el proceso de compactacion voy a mergear los archivos .tmp con los .bin entonces quiere decir que en los .tmp no puede haber registros repetidos (con la misma key)??

También, en la memtable puede haber registros repetidos?? En donde se soluciona este problema?? En el proceso de dump o en el de compactacion??

Gracias

**Comment by NaylaWinter** [comment]
Buen día,

Dentro del enunciado dice: 
_Aclaración: En caso que se realice un nuevo Insert sobre una Key que ya se encuentra en la memtable, el Value no se actualizará, sino que se agregará el registro nuevamente teniendo “Keys duplicadas”._

Para esclarecer esto: en la Memtable puede haber registros repetidos, por lo tanto vas a poder realizar un dump en un .tmp donde tengas Keys repetidas. Este problema lo vas a resolver recién en el proceso de *compactación*, manteniendo siempre en los .bin el valor mas actualizado para cada clave.

**Comment by GonzaOrtega** [comment]
Buenisimo!! Gracias!!
