### ISSUE TITLE
NTP - Error al configurar

### ISSUE THREAD

**Issue by cmedrano** [sisoputnfrba/foro#1348]
Hola! Acudo a su ayuda ya que tengo estoy teniendo problemas al ejecutar el comando
curl -L faq.utnso.com/script-ntp.sh | bash

Algo que este haciendo mal? ejecute con sudo adelante y obtengo el mismo resultado.

![error ntp](https://user-images.githubusercontent.com/1707672/57720904-3c755480-7659-11e9-9345-64a470f6d06f.jpg)

Muchas gracias

**Comment by gastoncastineira** [comment]
Fijate si lo que charlaron en #1332 te sirve

**Comment by cmedrano** [comment]
Si lo estuve viendo pero no me sirve  ya que cuando ejecuto systemctl me devuelve "No se encontró la orden"

**Comment by mgarciaisaia** [comment]
@cmedrano corré un `sudo apt update` primero, y después el script (el `curl ...`).

Es un bug del script: antes de instalar los paquetes, debería hacer un `apt update` por si no tenés los índices de los repositorios bajados - como en tu caso.

Si sigue fallando, mostranos el resultado de un `cat /etc/sources.list` y de `cat -n /etc/sources*/*` para ver qué puede estar pasando.

**Comment by cmedrano** [comment]
Muchas Gracias Mati, hoy a la tarde apenas llegue a casa hago eso que me decís y les aviso.
Muchas gracias nuevamente, ojalá eso pueda resolver el problema!

**Comment by cmedrano** [comment]
Mati corri el sudo apt update y eso termino de ejecutar bien me devolvio al final (Leyendo lista de paquetes... Hecho) pero cuando vuelvo a ejecutar curl.. me sale el mismo error, te paso la imagen donde muestra lo que devuelve
![error2](https://user-images.githubusercontent.com/1707672/57813368-3c9f4e00-7746-11e9-9a4c-c6e35b9a72f8.png)

Muchas gracias

**Comment by mgarciaisaia** [comment]
Faltó la parte del "si sigue fallando..." :)

**Comment by cmedrano** [comment]
Si Mati, continúa fallando. Lo reinicie por las dudas luego de hacer el sudo apt update pero sigue dando el error ya no se que puede estar fallando!

Gracias

**Comment by iago64** [comment]
@cmedrano creo que lo que Mati te dijo es que si te seguia fallando despues de correr el curl pases las capturas de los siguientes comandos:

`cat /etc/sources.list `

`cat -n /etc/sources*/*`

Abrazo!

**Comment by cmedrano** [comment]
Uy perdón! no leí esa parte, re importante, mala mía. Mil disculpas, a la tarde pruebo eso y les aviso.

Muchísimas gracias

**Comment by cmedrano** [comment]
Puede ser que por alguna razón no exista el archivo o directorio? es lo que me devuelve la consola
![error cat](https://user-images.githubusercontent.com/1707672/57898242-954a1600-782e-11e9-9fa9-e69be4729e85.png)

Muchas gracias

**Comment by mgarciaisaia** [comment]
Uy, perdón, soy todo tarado. Las rutas son /etc/apt/sources.list

Me faltó el apt

**Comment by cmedrano** [comment]
si ahora si 
esta es la primera parte de lo que devuelve
![error1](https://user-images.githubusercontent.com/1707672/57899428-671b0500-7833-11e9-9852-9c61ea7fceeb.png)

**Comment by cmedrano** [comment]
y esta sería la última parte de la devolución de ejecutar cat /etc/apt/sources.list

![error2](https://user-images.githubusercontent.com/1707672/57899449-7dc15c00-7833-11e9-84d0-ef2c0b200ab5.png)

**Comment by cmedrano** [comment]
luego de ejecutar el segundo cat la consola me devuelve
![error3](https://user-images.githubusercontent.com/1707672/57899589-0f30ce00-7834-11e9-8196-fcfc22c17bc1.png)

Muchas gracias

**Comment by mgarciaisaia** [comment]
Cris, ¡estás usando VMs viejas!

Fíjate que tu `/etc/apt/sources.list` dice tener los repos de Ubuntu 14.04, así que deben ser las VMs anteriores - desde el 1c2018 tenemos unas VMs nuevas basadas en Ubuntu 16.04

Probablemente el paquete de ntp se llamaba distinto en esa versión anterior de Ubuntu.

Bajate las VMs nuevas :+1:

**Comment by cmedrano** [comment]
Muchísimas gracias Mati! voy a reinstalar la vm!
Saludos
