### ISSUE TITLE
Consulta sobre el uso de mmap.

### ISSUE THREAD

**Issue by Dragonflares** [sisoputnfrba/foro#1349]
Buenas tardes!

Estuve estos ultimos dias probando la creación del bitmap con mmap y hasta ahora no logro entender bien como crearlo, se que si escribo con mmap el archivo me queda con el tamaño de 5192 bytes (que es la cantidad de bloques del sistema), pero cuando lo abro, el archivo sigue vacío, no tengo prueba de que se haya escrito algo o no, así que no se si algo me faltó (porque vi ejemplos tales al que acabo de usar, y el archivo se podía leer). Además, si lo corro con valgrind, me dice que no tengo permisos para escribir, procedo con screens:

1) El creador de bitmap:
![imagen](https://user-images.githubusercontent.com/28828524/57722994-0dadad00-765e-11e9-9f79-20ce84c6c051.png)
![imagen](https://user-images.githubusercontent.com/28828524/57723018-1dc58c80-765e-11e9-8704-0e4a3034f08a.png)
![imagen](https://user-images.githubusercontent.com/28828524/57723377-dee40680-765e-11e9-849c-3a794b633fec.png)
![imagen](https://user-images.githubusercontent.com/28828524/57723078-3df54b80-765e-11e9-8370-b9c2b098d4d2.png)

2) Error del valgrind:
![imagen](https://user-images.githubusercontent.com/28828524/57723197-814fba00-765e-11e9-90d9-0c28793fddae.png)

La línea 101 corresponde a la que marque, y asumo que la 105 (que es casi idéntica) tirará el mismo error. Alguna idea?

PD: He intentado con una menor cantidad de bloques hardcodeando por ejemplo un 5, o un 100, y no tiró ese error, sin embargo el bitmap.bin aparecía vacío de todas formas.

**Comment by gastoncastineira** [comment]
Acá tenés varios problemas todos juntos. Primero, estás asumiendo que el archivo vacío ya tiene un tamaño predefinido de 5192 bytes, algo que podría ser así pero a mí nada en tu código me lo garantiza. Segundo, estás representando el mapeo con un int*, algo que claramente no es porque me estás hablando de un tamaño en bytes, y mmap precisamente te devuelve un void* para representar el contenido de lo que sea que te mapeo. Tercero, estás corriendo un bucle tantas veces como bloque tengas, que un (1) dijiste que tenías tanto bloques como bytes, y le estás grabando al mapeo un 1 o un 0, algo que sabemos que pesa más que 1 byte, y ahí viene el segfault.

Lo que tenés que hacer es mucho más sencillo que eso. Bitarray cuando lo creás recibe el cacho de memoria en el que tiene que escribir, y tiene funciones de escritura y lectura que escriben y leen sobre él. mmap te devuelve un cacho de memoria dentro del heap de tu proceso que te garantiza que va a impactar sobre el recurso compartido que haya mapeado. Creo que ya te dije demasiado. Tenés que tener un poco de cuidado sobre los tamaños, y ya te comenté en otro issue de truncate para eso

**Comment by Dragonflares** [comment]
Buenas, al final decidí borra toda esa función ya que era bastante mala, y armé una nueva usando bitarray y mmap de una manera más o menos interesante.

![imagen](https://user-images.githubusercontent.com/28828524/57875994-a6713380-77ea-11e9-9eb2-07a4f1ff22a7.png)

Al guardar el resultado de mmap dentro de un char*, obtengo la más minima relacion de tamanio de todas las demas variables (salvo una cadena de bools, pero eso era imposible).
En un principio la idea era buena, pero cuando lo corrí por primera vez (sin el test_bit y el set_bit) El resultado del printf de los primeros intentos fue un renglón vacío por cada línea:

![Imagen 1](https://user-images.githubusercontent.com/28828524/57876263-5777ce00-77eb-11e9-9a62-116d8f7a6b0d.jpeg)

Ahi fue donde decidí implementar el set_bit. Eso hizo que el resultado fuera un poco más satisfactorio, ahora tenía caracteres extraños y algo escrito en mi bitmap.bin (obviamente no se lo podía leer así nomas)

![Imagen 2](https://user-images.githubusercontent.com/28828524/57876309-6c546180-77eb-11e9-9464-ca1a5508a839.jpeg)
![Imagen 3](https://user-images.githubusercontent.com/28828524/57876350-7ece9b00-77eb-11e9-939b-f23840601084.jpeg)

Así que decidí llamar a test_bit (que devuelve en bool el valor del bit...) y lo decidí mostrar como int... me comí un error más grande e inesperado de lo que debería... 

![imagen](https://user-images.githubusercontent.com/28828524/57876396-9ad23c80-77eb-11e9-9465-e3c8322f5997.png)

No estaría muy seguro de porque ahora el set_bit llora con el bus, e internet no tiene mucho que ofrecerme... Alguna idea?

**Comment by cmedrano** [comment]
Hola! perdón por interrumpir pero estaba leyendo el issue porque justo tambien estoy desarrollando el bitmap. 
Veo que cuando creas el bitarray le tenes que pasar el tamaño del bitarray en bytes, entonces si tenes 16 bloques el bitarray va a tener 16 bits igual a 2 bytes, por lo tanto en este ejemplo vos le tendrías que pasar como parametro en lugar de blocks sería blocks / 8. Si bloks es la cantidad de bloques.

**Comment by Dragonflares** [comment]
@cmedrano acabo de probar eso que me dijiste, tiró sigbus de todos modos.

![imagen](https://user-images.githubusercontent.com/28828524/57954294-de4ea880-78c8-11e9-982e-8bc906243c8a.png)

**Comment by Dragonflares** [comment]
Bueno, me costó mas de lo que me gustaría pero resolví ese problema, cierro issue!

**Comment by gastoncastineira** [comment]
Por favor, no dejes con la duda de qué era el problema que capaz le sirve a otros!

**Comment by Dragonflares** [comment]
Tardé un rato en entender tu frase :
> Tenés que tener un poco de cuidado sobre los tamaños, y ya te comenté en otro issue de truncate para eso 

Después de buscar un rato encontré sobre que en realidad nunca le había asignado espacio suficiente al archivo, ya que mmap solo mapea lo que ya existe en el archivo, entonces si el archivo original solo tenía 5 bytes dentro solo iba a mapear 5 bytes por más que yo le pasara de tamaño 5000.
Ahí fue donde aplique un truncate de cantbloques/8 (para que quedara como un guante para los bits) y ahí solucioné una parte del problema. Después cayo todo en manos de solucionar un segmentation fault cuando el set_bit quería hacerse en una posición de 0xFFFFFFF, pero eso fue más rapido.
Lección que aprendí del issue, siempre hacer truncate a los archivos antes de mappear 😄
