### ISSUE TITLE
Consulta sobre Select en memoria

### ISSUE THREAD

**Issue by ncoen97** [sisoputnfrba/foro#1350]
Hola, implementando el select en memoria me surgió una consulta. Cuando a memoria le llega un select y 1) No encuentra la tabla o 2) No tiene la pagina solicitada, tenemos que pedirle el value solicitado a FileSystem " Si no la contiene, envía la solicitud a FileSystem para obtener el valor solicitado y almacenarlo". En este caso FS debería mandarnos ademas del value el timestamp? ya que sino tendríamos que ponerlo nosotros y no reflejaría el momento del insert.

**Comment by NaylaWinter** [comment]
Buenas,

Cuando le pidan una Key al FS para poder almacenarlo dentro de la Memoria te va a tener que pasar el registro completo, es decir, timestamp+key+value.

**Comment by ncoen97** [comment]
Perfecto, gracias

**Comment by chamenwais** [comment]
Buen día.

Amplío un poco la consulta:
* En las consolas del filesystem/memoria/kernel, cuando ejecutan el comando SELECT: ¿Hay que mostrar también el registro completo?

Gracias.

**Comment by NaylaWinter** [comment]
Buenas, 

No es condición necesaria pero estaría bueno si pueden mostrar todo el registro completo.

**Comment by chamenwais** [comment]
Gracias Nayla.

Ya podés cerrar el issue devuelta.
