### ISSUE TITLE
FS funcion DROP

### ISSUE THREAD

**Issue by AndresMarcovecchio** [sisoputnfrba/foro#1351]
El enunciado dice que la operación drop desde el FS consiste de:
1) Verificar que la tabla exista en el file system.
2) Eliminar directorio y todos los archivos de dicha tabla.
Habría que borrar también cualquier cosa que haya de esa tabla en la memtable también no?
Muchas gracias.

**Comment by Dragonflares** [comment]
En teoría si, también se tendría que borrar toda las claves que estén en los bloques del FS que se hayan asignado a las particiones de esa tabla.

**Comment by NaylaWinter** [comment]
Buenas,

Al realizar un DROP dentro de LFS se debe también borrar lo que haya en la memtable asociada para esa tabla.
Asimismo, como te comentó el compañero tendrían que borrar todas las claves en los bloques de la tabla. 

En conclusión, debes: 1. Eliminar  la memtable de esa tabla
2. Eliminar los archivos de esa tabla (.bin/.tmp/metadata) (También borrado de los bloques)
3. Eliminar el directorio de la tabla
4. Eliminar toda la información administrativa de la tabla

**Comment by AndresMarcovecchio** [comment]
Ah ok, preguntaba por que tal vez querían que quedara esa info, como habían especificado todo lo demás y no eso.
Muchas gracias.
