### ISSUE TITLE
Duda value de registro - memoria

### ISSUE THREAD

**Issue by ncoen97** [sisoputnfrba/foro#1352]
Buenas, nuestros registros que guardamos en memoria son del tipo:
 (`uint64_t` timestamp; `uint32_t` key; `char*` value)
Cuando creamos los registros, en registro->value hacemos un malloc para el char*, y ahora me entro la duda de si esto está bien o si en realidad el value tiene que quedar guardado directamente dentro del registro.

**Comment by NaylaWinter** [comment]
Buenas,

Te consulto a ver si entendí: la pregunta viene por el lado de si deberían usar un char* o si es mejor que fijen el tamaño de antemano? Es decir, utilizar un malloc vs un struct de tamaño fijo?

Si la pregunta es esa entonces la respuesta es que lo pueden manejar como ustedes quieran. Si no, te pido si me podes dar mas información porque no te entendí

**Comment by ncoen97** [comment]
Me intento expresar mejor. La consulta iba orientada a si el char* value queda guardado dentro de la estructura del registro (dentro de la memoria reservada de 2048) o está bien que en el registro quede guardado el puntero a otra direccion de memoria (con un malloc). Por ejemplo el timestamp es un int que queda guardado dentro del registro y ocupa ahi adentro unos 4/8 bytes, pero como el value es un char* puede apuntar a otro lado de memoria y no ocupar espacio dentro del registro mas allá del puntero.

**Comment by ezelee** [comment]
Perdón no quiero desviar mucho el tema, pero no debería ser un `uint16_t`? me refiero a la variable key.
Según el enunciado pagina 13 dice
> 3 Para poder limitar el tamaño de las Key estaremos usando el tipo de dato uint16 para las mismas

**Comment by gastoncastineira** [comment]
Interesantes propuestas che
Ahora, contame, ¿Cómo pensás encarar en tema del malloc gigantesco con ambas alternativas?

**Comment by mesaglio** [comment]
@NaylaWinter el tema es asi, nostros creamos la estructura
```
typedef struct{
	uint64_t timestamp;
	uint32_t key;
	char* value;
}registro;
```
Como el tamaño de la memoria es fijo una vez iniciada, ya que se obtiene por archivo de configuracion.
Hicimos los siguiente
```
 void* memoria = malloc(configuracion->tam_mem);
```
Siendo memoria el puntero al inicio del bloque de memoria.
Cada vez que agregamos un registro a la memoria usamos otra variable global de tipo void* que nos indica la proxima direccion del bloque a la cual tenemos que escribir.

Nosotros hicimos que el registro en memoria guarde el timestamp, la key y el puntero al value. Pero si solo guarda el puntero, que solo pesa 4 bytes, la memoria no se va a ver afectada por el tamaño del value en si porque solo esta guardando el puntero en el malloc gigante.

Queremos saber si es correcto que el tamaño que va a ocupar un registro en memoria no cambie depeniendo del tamaño del value.

**Comment by gastoncastineira** [comment]
Ok, bueno. Borremos un minuto el enunciado de nuestras cabezas y vayamos a la teoría. Vos sos el programador a cargo del desarrollo del módulo que gestiona el manejo de memoria de tu SO. Vos lo único que sabés que contiene tu memoria son un montón de bytes que no te representan absolutamente nada por sí solos, por lo que empezás a diseñar algún modo de poder entender qué es y dónde está cada cosa que le entre. Te decidiste, por razones, a hacer una segmentación paginada. Sabés que vas a tener que tener en algún lado definida una tabla de segmentos y una tabla de páginas (una de las mayores diferencias entre el TP y una memoria real, las estructuras administrativas no las estás poniendo dentro del malloc gigante que representa tu memoria). 
Volviendo al TP, vos sabés que tenés un segmento por tabla, y páginas para los registros. Presentás dos alternativas:

- Tamaño fijo: Dentro de lo que representa la memoria fija (malloc gigante), me guardás en una página el valor. Luego para poder accederlo y leerlo tendrás que saber el offset, pero siendo TS y key fijos no debería ser un problema mayor

- Puntero: Como ya dije antes, el malloc gigante representa tu memoria. Si vos me metés un puntero al que le hacés otro malloc y apunta a un lugar distinto, obviamente está mal. Si yo estoy programando la memoria, y mi malloc gigante representa su totalidad ¿tiene sentido poder hacer un malloc a un puntero y guardar el valor en otro lado? Estaríamos hablando de que ese puntero apunta a una posición de memoria no existe, y mágicamente anda (repito, pensando en la teoría)

- Puntero retrucado: Supongamos que lo hacés con un puntero, pero en vez de hacerle malloc hacés que apunte a algún lugar del malloc gigante. Ahora sí estamos hablando de algo que pueda andar, pero tiene un problema. Si bien no es una garantía, sí es altamente probable que por cuestiones de cómo anda la memoria el puntero no pueda apuntar a la posición que tenga al lado, por lo que lo tendría apuntado a otro marco de mi segmentación paginada, por lo cual o se la agrego al segmento o me tira segmentation fault. Entonces ya estaríamos hablando de que por cada registro tenemos que (muy probablemente, no seguro) ocupar dos marcos de la memoria. Suponiendo que pudiéramos hacer algún algoritmo para garantizar que el puntero apunte dentro de la misma página estaríamos eliminando mucho más esa fragmentación a costo de más overhead corriendo ese algoritmo para cada asignación para proteger el puntero, el cual a estas alturas ya me pareció redundante.

Entonces, te pregunto, ¿cuál de las ideas comprás más?

**Comment by NaylaWinter** [comment]
Buenas @ncoen97 @mesaglio, como vienen con este tema? Si siguen con dudas les pido que nos las consulten y sino si pueden cerrar el issue

**Comment by cmedrano** [comment]
Hola! 
estaba con una duda sobre algo que tiene que ver un poco con esto, perdón si quizas la respuesta es obvia, pero me gustaría estar seguro si realmente es asi.

Si el tamanio del value que viene por archivo de configuración es 10
Cuando se realice un insert desde la consola de la memoria o del Kernel por ejemplo
INSERT POSTRES 3 "ABC D" El valor es ABC(espacio)D por lo tanto el tamaño del value es 5 verdad? O tengo que contar las comillas  para calcular el tamaño del valor, en este caso si cuento las comillas también el tamaño sería 7 y no podría ingresar porque el tam de value es 5.?

Muchas gracias

**Comment by NaylaWinter** [comment]
Hola,

En ese caso el tamaño del value serían 5bytes, no cuentan las comillas

**Comment by ncoen97** [comment]
Hola, consulto sobre el mismo tema. En este caso no cuenta el \0 para el tamaño del value?

**Comment by cmedrano** [comment]
Muchas gracias Nayla!!

**Comment by NaylaWinter** [comment]
@ncoen97 buenas, si, el \0 cuenta para el tamaño del value.

**Comment by ncoen97** [comment]
Perfecto, gracias.
