### ISSUE TITLE
BitArray problema al grabar en archivo

### ISSUE THREAD

**Issue by cmedrano** [sisoputnfrba/foro#1354]
Hola!
Estoy utilizando bitarray_set_bit() seteando los bits  y luego consultandolos con bitarray_test_bit en el espacio que me devuelve mmap(es decir en el espacio de memoria) y veo reflegados los cambios hago.
Pero luego de ejecutar y terminar el proceso cuando voy a revisar el Bitmap.bin no veo las modificaciones en los bits, continuan en cero como en un pricipio.

Estoy utilizando al final de modificar el bitArray lo siguiente
 msync(bmap, sizeof(bitArray), MS_SYNC);
munmap(bmap, sizeof(bitArray))

Estuve investigando que tengo que utilizar estas funciones para sincronizar con el archivo pero quería saber si me falta alguna otra cosa para poder grabar los cambios en el archivo, o con eso ya debería grabar en el mismo.

Muchas gracias

**Comment by gastoncastineira** [comment]
Con un poco más de contexto capaz lo sacamos andando che! Con dos líneas sacadas de contexto no hacemos nada

**Comment by cmedrano** [comment]
Muchas gracias! ya pude resolver el inconveniente!
Cierro issue!
