### ISSUE TITLE
Consulta de la sintaxis del comando INSERT

### ISSUE THREAD

**Issue by chamenwais** [sisoputnfrba/foro#1355]
Hola.

Tenemos una consulta respecto a la sintaxis del comando INSERT:

`INSERT TABLA1 3 “Mi nombre es Lissandra” 1548421507`
`INSERT [NOMBRE_TABLA] [KEY] “[VALUE]” [Timestamp]`

Particularmente nuestra duda es con el value, que viene con un requerimiento implíscito.
En el ejemplo que colocan, se ve claramente que el token _value_ está encerrado entre comillas dobles:
* ¿Esto quiere decir que no debo aceptar values que no vengan encerrados entre comillas dobles en las consolas del kernel/memoria/filesystem? 
* El hecho de aceptar values con espacios ¿es también un requerimiento?
* ¿El timestamp tiene que poder ser opcional?

Gracias.

**Comment by NaylaWinter** [comment]
Buenas,

Sobre el primer punto: claro, vos tenes que aceptar los values que estén dentro de comillas dobles, porque así es la sintaxis que tiene que respetar cualquier consulta que este bien formulada.

Debes permitir values que tengan espacios adentro, tal como se muestra en el ejemplo podremos poner una frase que los incluya.

Por último, dependiendo el módulo el timestamp es opcional o no: en el caso del LFS es opcional enviar la operacion junto con el timestamp, en el caso de la Memoria y el Kernel la request va directamente sin el dato del timestamp, debido a que el mismo es calculado dentro de la Memoria.

**Comment by chamenwais** [comment]
¡Gracias Nayla!

**Comment by chamenwais** [comment]
Hola. 

Leyendo el [documento de pruebas del checkpoint presencial](https://docs.google.com/document/d/1V-ylzz6NyTiBqNpBKVd5TIeaa0DtpUpcXUQaQqEt03Q/edit?usp=sharing) y el [repositorio de archivos lql](https://github.com/sisoputnfrba/1C2019-Scripts-lql-checkpoint) me volvieron a surgir dudas acerca del formato del value en un insert, particularmente de las comillas.

Por ejemplo en el archivo `animales.lql` vienen sentencias _insert_ como:
- `INSERT MARINOS 983 “Ballena”`
Donde hay una comilla doble _diagonal_ para comenzar el value y otra _oblicua_ para cerrar

Sin embargo en el documento de pruebas dicen que probemos en línea de comandos, sentencias como:
- `INSERT FRUTAS 222 "Frutilla"`
Donde la comilla es doble, pero vertical para abrir y cerrar.

¿Qué tipo de comillas van a usar?
- La comilla doble _vertical_ `"` de código 22 en hexa
- O la comilla doble _diagonal_ para abrir `“`, de código hexa 201c; y una _oblicua_ para cerrar `”` cuyo código hexa es 201d.

Gracias.

**Comment by NaylaWinter** [comment]
Buenas,

Tuvimos un problema con el tema de las comillas dentro de los scripts. Recién actualizamos todas las sentencias de los scripts a las comillas doble vertical ", serían las de código 22 en hexa.

Deberían estar correctos ahora los scripts, cualquier otro problema te pido si nos lo podes hacer saber, gracias!

**Comment by chamenwais** [comment]
Gracias.
El documento de pruebas y los archivos lql son consistentes ahora.
