### ISSUE TITLE
Persistencia de datos en bloques

### ISSUE THREAD

**Issue by PabloOve** [sisoputnfrba/foro#1356]
Cuando nosotros manualmente guardamos un registro en un archivo .bin, al leerlo con mmap, lo hace correctamente. Así se ve el .bin si lo escribimos nosotros:

![1](https://user-images.githubusercontent.com/31904880/57986640-d66c4100-7a4d-11e9-9b26-7eb1de9ef40a.png)

Y usando la función mmap, nos arroja bien el resultado:

![3](https://user-images.githubusercontent.com/31904880/57986783-a1f98480-7a4f-11e9-8805-db70a0cfbbd7.png)

Si nosotros guardamos informacion en el archivo, pero no manualmente, si no utilizando las funciones que corresponden, en el archivo se puede ver que queda basura.

Usamos estas funciones para guardar en el binario:

![2](https://user-images.githubusercontent.com/31904880/57986657-13d0ce80-7a4e-11e9-82d5-7a0bc7a051c5.png)

El binario se ve así:

![binariofeo](https://user-images.githubusercontent.com/31904880/57986805-e08f3f00-7a4f-11e9-9c97-a2a9ab1e93b9.png)

Y usando la función mmap arroja este resultado:

![resultadofeo](https://user-images.githubusercontent.com/31904880/57986821-116f7400-7a50-11e9-8ece-0efca8cb5ac9.png)

Hay que aclarar que al leer la información que guardamos con esas funciones, usando fread y fopen lo abría y tomaba bien los datos.

¿Como deberíamos hacer para poder guardar la información de manera correcta para luego agarrarla con mmap para después cargarla en memoria y poder analizarla?

**Comment by rcomesan** [comment]
Estás escribiendo el texto de forma binaria. Los archivos .bin técnicamente no son archivos binarios, deberían contener únicamente texto serializado con el formato dado: timestamp;key;value. Lo cual significa que vas a tener que escribir al archivo strings o bien usar un buffer intermedio para formatear tu record serializado y después escribir ese buffer (string) con un solo fwrite al archivo.

Cuando hacés:
`fwrite(&timestamp, sizeof(time_t), 1, archivo);`

esto lee 4 bytes de la dirección en memoria donde está guardado timestamp (contiene en memoria la combinación de bits necesarios para representar tu entero sin signo de 4 bytes en formato little endian) y tal cual como están en memoria los escribe al archivo.

para tu valor de timestamp 1548421507 la representación en memoria (little endian) sería: 
```
binario: 10000011 00001001 01001011 01011100 <-- esto es exactamente lo que se escribe al archivo
decimal:      131        9       75      92
ascii:          â    H-TAB        K       \
octal:        203
eclipse:     \203       \t        K      \\
                ^
                |___ así representa ascii-extended chars eclipse :/
```

después haces:
`fwrite(&key, sizeof(uint16_t), 1, archivo);`

la representación en memoria de tu key (con valor 54) en little endian es:
```
binario: 00110110 00000000
decimal:        6        0
ascii:        ACK     NULL
eclipse:       \6     nada <-- fin de c-string (null-terminated), ignora el resto
```

Y si te fijás tiene sentido, lo que leiste en la variable información es exactamente lo que escribiste con fwrite. Fijate que eclipse en la inspección de variables te lo muestra con un formato distinto para que te sea (más fácil?) leerlo (más que nada para caracteres de control o "no-imprimibles").

En lugar de escribirlo de forma binaria, necesitás escribirlo como texto, esto significa: convertir cada valor a string.

Es un poco contra intuitivo elegir la extensión .bin para esto y posiblemente preste a confusión, pero así está definido en los requisitos.

**Comment by PabloOve** [comment]
Muchas gracias! Nos aclaraste muchas dudas!!

Cierro issue.
