### ISSUE TITLE
Error al Abrir Config

### ISSUE THREAD

**Issue by germanflighel** [sisoputnfrba/foro#1357]
Buenas!
Estamos teniendo un problema al intentar leer un archivo usando el config de las commons. 
```
	char* mi_ruta = string_new();
	string_append(&mi_ruta, ruta);
	char* mi_metadata = "/Metadata";
	string_append(&mi_ruta, mi_metadata);
	log_debug(logger, mi_ruta);

	log_debug(logger, "Abriendo config");
	t_config* config_metadata = config_create(mi_ruta);
	log_debug(logger, "Abri config");

	Metadata* metadata = malloc(sizeof(Metadata));
	int particiones = config_get_int_value(config_metadata, "PARTITIONS");
	metadata->partitions = particiones;
	long tiempoDeCompactacion = config_get_long_value(config_metadata,"COMPACTION_TIME");
	metadata->compaction_time = tiempoDeCompactacion;
	char* consistencia = malloc(4 * sizeof(char));
	char* temp = config_get_string_value(config_metadata, "CONSISTENCY");
	memcpy(consistencia, temp, 4 * sizeof(char));
	metadata->consistency = consistency_to_int(consistencia);

	free(temp);
	free(consistencia);

	config_destroy(config_metadata);
	log_debug(logger, "Cerre config");
	loguear_metadata(metadata);


	free(mi_ruta);

	return metadata;
```
El error se produce al intentar abrir una config luego de ya haber ejecutado el metodo una segunda vez. Nos parece muy raro, porque al revisar los logs, la ruta es correcta, y no tiene problemas al abrir o cerrar una config anterior.

**Comment by gastoncastineira** [comment]
¿Podrás mostrar un poco más de información? El error que te tira, los valores con lo que lo probás, capturas del debugger, etc

**Comment by germanflighel** [comment]
Hola Gastón. 
Revisando en issues viejos del foro, encontramos este: [issue] https://github.com/sisoputnfrba/foro/issues/900). 
Describe el mismo problema que teníamos. Ya lo pudimos resolver!
Gracias!
