### ISSUE TITLE
Maximo Value en Memoria

### ISSUE THREAD

**Issue by fighthawkarg** [sisoputnfrba/foro#1358]
Hola
Tengo una duda simple.
Yo tengo en memoria un valor máximo que puede ocupar el value en un registro que la obtengo de LFS. 

Supongamos que me insertan un registro el cual el value supera este maximo.
Lo que ami me parecería correcto es que no lo registre y muestre un mensaje tipo "segmentation fault" (esta escribiendo mas de lo que esta permitido por max_value)

Quería saber si esto que digo es valido o no.
Saludos
Javier

**Comment by gastoncastineira** [comment]
Efectivamente es así. ¿Por qué? Porque si te pasás del offset de la página (que es lo que compone el segmento) al no poder direccionar con todos los bits que la componen, te salís del segmento y entrás a un espacio de memoria que no es de él, y por lo tanto falla (de ahí el nombre segmentation fault)

**Comment by fighthawkarg** [comment]
Entendido. Muchas Gracias. Cierro Issue.
