### ISSUE TITLE
Duda de comunicacion con memorias

### ISSUE THREAD

**Issue by GonzaOrtega** [sisoputnfrba/foro#1359]
Tenia una duda: en el tp te ponen como ejemplo en el archivo de configuración del Kernel una única dirección IP de la memoria. En este ejemplo suponen que la memoria es única?? Porque yo puedo tener muchas memorias, cada una con su propio IP.

Lo que a mi se me había ocurrido es que sea una lista de IPs de las memorias que conforman el Pool (estas se obtienen mediante el gossiping)

Gracias

**Comment by gastoncastineira** [comment]
Pero, justamente usamos gossiping para no tener listas de IPs y puertos en los archivos de configuración. Te diría que releas el anexo y si seguís con dudas vuelvas a preguntar

**Comment by GonzaOrtega** [comment]
Esta pregunta esta medio relacionada con la otra duda que postee recién. Releí el anexo y por lo que entendí, primero el kernel hace gossiping con la única memoria y luego se va desarrollando el proceso hasta que al final todos las memorias se conozcan entre si y el Kernel las conozca a todas.

Al final vas a tener en el Kernel las IP y los puertos de todas las memorias del Pool. O no??

**Comment by iago64** [comment]
Buenas!

Si, vos al principio vas a conectarte a una sola memoria y por gossiping vas a ir conociendo el resto de las memorias y vas a ir guardando las IPs de alguna forma.

Abrazo!

**Comment by GonzaOrtega** [comment]
Buenísimo, gracias!!
