### ISSUE TITLE
Duda de IPs

### ISSUE THREAD

**Issue by GonzaOrtega** [sisoputnfrba/foro#1360]
Un pregunta tonta: por que en los archivos de configuración de ejemplo te ponen el IP del modulo con el que se van a conectar y no el suyo propio??(Ej, la memoria tiene el IP del FS). Porque por lo que entendí, tanto el cliente como el servidor requieren IPs. 

Gracias

**Comment by iago64** [comment]
Aloha! 
Antes que nada por favor desmitifiquemos el concepto de _pregunta tonta_, nadie nace sabiendo, estamos todos para aprender y a veces una pregunta simple resuelve un mar de dudas :)

Respecto a tu consulta, la respuesta es que vos siempre podes usar la IP del localhost (127.0.0.1) para crear el socket, como vos tenes que asegurarte que esa IP existe, la 127.0.0.1 existe y funciona.
Despues por ej de ahi que puedas levantar un servidor para aceptar conexiones nuevas o puedas usar ese socket para conectarte a un servidor, es un tema de como tengan planteada la arquitectura.

Abrazo!

**Comment by GonzaOrtega** [comment]
Tengo que asegurarme que la IP exista??

Por otro lado, para implementar las sockets utilice la funcion getaddrinfo() en la cual me pide el IP y el puerto, entonces en mi caso yo necesito que se tanto el cliente como el servidor tengan su propio IP y puerto, o no??

**Comment by iago64** [comment]
El asegurarte que la IP exista es porque _tenes que conectarte a algo_ y si no existe te va a devolver error el conect :)

Respecto al getaddrinfo() si, le tenes que pasar una IP, que si te fijas en el [tp0](https://github.com/sisoputnfrba/tp0) codeabas un **cliente** donde la IP la levantabas del config y era 127.0.0.1, ya que vos te conectabas a la _misma maquina_ o podes conectarte a otra maquina (ahi es donde tenes la IP del proceso al que te queres conectar)
Ahora si vos vas a hacer un socket **servidor** directamente no vas a pasar por getaddrinfo() ya que solo vas a hacer el bind() y el listen() 

Saludos.-

**Comment by GonzaOrtega** [comment]
Con respecto al tp0, el cliente y el servidor usaban la misma IP y puerto. En ese caso, yo al cambiar el IP de cualquiera de los 2 no me deja hacer la conexión. Por que??

Otra consulta, para el tp necesito hacer que la conexión sea local o remota??

Gracias

**Comment by iago64** [comment]
Vamos por partes de lo mas simple a lo mas complejo:

En el TP sus procesos tienen que poder conectarse entre 2 pcs distintas, eventualmente si se tienen que conectar a la misma pc es un caso particular (que en lugar de usar una ip de otra pc usan la misma ip de la pc en la que estan)

Ahora respecto a la pregunta del tp0, vos tenes que pasarle a getaddrinfo() la ip y el puerto del proceso al cual te queres conectar, con lo cual, es necesario que el puerto sea correcto, ya que podes llegar a un edificio y tenes que tocar el timbre correcto y despues, la ip es una dirección de la maquina, con lo cual, si vos pones la ip correcta vas a llegar, si pones una ip incorrecta el switch / router te va a mandar la conexion a cualquier lado, similar a como si queres ir a un edificio y te pasan mal la dirección y en lugar del edificio terminas en la plaza de la esquina.

En resumen:
IP --> Dirección (Calle y altura)
Puerto --> Timbre (Piso y Nro de Departamento)

Saludos.

Saludos.-

**Comment by GonzaOrtega** [comment]
Oka, me quedo mas claro con la analogía. Ahora, para conectarme a otro equipo necesito la IP remota o la local?? Porque lo que yo hice fue en el servidor use la IP local y el puerto de ejemplo del tp0 (4444) y me cargo el servidor pero puse los mismos valores en el cliente y no se me conecto (me fallo el connect() ).

**Comment by gastoncastineira** [comment]
Para conectarte a otro equipo necesitás la IP remota. La local es siempre 127.0.0.1 y se referencia a sí mismo. Si hablamos de dos equipos diferentes no se pueden comunicar mediante esa IP.

Te hago un preguntita. ¿Cómo estás consiguiendo la IP del equipo y dónde lo estás probando de manera distribuida? porque a veces pasa que el VirtualBox queda mal configurado y la VM no tiene acceso a la red y te tira una IP fruta que no existe, y quiero ver si viene por ahí

**Comment by GonzaOrtega** [comment]
Saco la info de: https://www.whatismyip.com/my-ip-information/?iref=home donde dice Local IP, pero me regresa otro valor (no 127.0.0.1). 

Esto lo estoy probando en las funciones del tp0 pero modificadas, pero pude hacer conexiones locales sin problema, hasta las use para hacer un especie de chat, así que no creo que sea las funciones el problema.

Para acceder a internet no tengo ningún problema.

**Comment by gastoncastineira** [comment]
Para simplificarte la vida en el futuro, tirando ifconfig en la consola te dice la IP de tu dispositivo en la red (que sería la local que ves ahí). Cuando dijiste "remota o local" entendí otra cosa, está bien que uses la local que te devuelve esa página.
Cuando dije dónde, me refería físicamente en qué lugar. Tu casa, el laboratorio de la facultad, etc. Explicame cómo es el ambiente en el que lo estás probando

Fijate si tenés la VM bien configurada. En VBox, andá a la configuración->Red y donde diga "conectado a" tiene que decir adaptador puente. Si el ifconfig te tira una IP del estilo 192.168.algo.algo entonces está bien, y el problema viene por algo que estés haciendo en el código o en el archivo de configuración. Tal vez con más capturas de pantalla podamos encontrar el problemas más fácil

**Comment by GonzaOrtega** [comment]
Esta es la captura de pantalla de lo que me sale con ifconfig, espero que se vea bien. En la pagina me tira "10.0.2.15", el cual me pareció muy raro.

![image](https://user-images.githubusercontent.com/38133971/58132024-9e543200-7bf6-11e9-9fc7-929e58ddc835.png)

Cual de los 3 es??

Todo esto lo estoy probando en la VM en mi casa. Respecto a lo de la configuracion de red, estaba en NAT. Al cambiarla por adaptador fuente se me fue el internet. Jajajaj

**Comment by gastoncastineira** [comment]
Porque efetivamente tenés mal configurada la VM!

Te paso captura de cómo se tiene que ver
Dónde dice nombra vas a tener que jugar con tus opciones hasta conseguir una que te funcione. Vas a saber que anduvo si el ifconfig te tira un 192.168.algo.algo en vez del 10.0.2.15
Donde dice cable conectado, va a depender de dónde lo estés probando (si la red es cableada o WiFi), supongo que no necesito decirte qué hacer ahí :P
![image](https://user-images.githubusercontent.com/28161802/58132880-deb4af80-7bf8-11e9-957e-e560fd6dddaa.png)

**Comment by GonzaOrtega** [comment]
En la compu me funciono, me devolvió un IP tipo como dijiste. Con la notebook no, no me tira la opción en Tipo de adaptador que te tiro a vos y a mi en la compu. Me tiro 2 opciones y ambas no funcionaron. Tengo que tocar el Tipo de adaptador también??

**Comment by gastoncastineira** [comment]
Alguna tiene que andar sí o sí! Tendrás que jugar hasta encontrarla. Sino, siempre podés llevarla a algún sábado de soporte y que te la revise alguno de los que estén allá

**Comment by iago64** [comment]
@GonzaOrtega Que onda este tema, pudiste resolverlo? 👮
