### ISSUE TITLE
Estructuras del LFS

### ISSUE THREAD

**Issue by cmedrano** [sisoputnfrba/foro#1361]
Hola!
Tenemos una pregunta con respecto a las estructuras del LFS como los archivos bloques(.bin)
las tablas, las particiones (.bin), es decir todos los archivos y carpetas que se encuentran dentro del LFS.
Antes de arrancar nuestro LFS tenemos que tener creados previamente nuestra carpeta mnt, mnt/LISSANDRA_LFS, nuestra carpeta mnt/LISSANDRA_LFS/Tables (En este caso vacío porque no hay tablas), mnt/LISSANDRA_LFS/Metadata/ , mnt/LISSANDRA_LFS/Metadata/Metadata.bin,mnt/LISSANDRA_LFS/Blocks/(Carpeta vacía porque no sabemos cuantos bloque habrá hasta levantar el LFS)

Entonces cuando arranca nuestro LFS tiene que crear los bloques .bin (de acuerdo a la cantidad de bloques que esta en el Metadata.bin) y el archivo Bitmap.bin. Solamente tiene que crear estas estructuras verdad? porque todo el resto ya esta creado a mano previo la ejecución del proceso. O tiene que crear todas las carpetas empezando desde nuestra carpeta mnt ? 

Entiendo que esta también la otra opción de que para las pruebas nos den un File system ya armado, en esto me genera la duda, el file system que nos daría sería todas las estructuras o solo una parte de las estructuras? Nos van a dar una carpeta mnt con todo ya cargado adentro para que nosotros los tengamos que leer y cargar nuestras estructuras?

Muchas gracias
Saludos

**Comment by Dragonflares** [comment]
Buenas!

Lo que nos van a dar en el FS va a ser el bitmap.bin y la carpeta Blocks, nada más, probablemente nos den la carpeta Metadata.bin entera, ya que esa tiene cuántos bloques hay en la misma, de modo que eso es lo que habría que esperar que haya. Te sugeriría (como me sugirieron otros ayudantes) que te crees tu propio FS y Bitmap de prueba, así ya tenés las funciones que leen, escriben y manejan dichas estructuras probadas correctamente.

Saludos
