### ISSUE TITLE
select con temporizacion

### ISSUE THREAD

**Issue by cmedrano** [sisoputnfrba/foro#1363]
Hola, 
Quería averiguar si existe algún problema utilizando un Select con contemporización, es decir pasarle un valor para los segundos y micro segundos con cero.
Esto porque necesito que revise si hay alguna actividad en algún socket y si no hay ninguna atender pedidos de una cola de querys.
Probé y si le paso 0 a esos parámetros sale enseguida del select si no hay actividad en algún socket, pero si le paso NULL no sale hasta que haya alguna actividad.
Entonces quiero pasarle cero pero no se si eso estaría bien?

Muchas gracias

**Comment by varas-c** [comment]
Buenas,

Si, se puede, el ultimo parametro de Select es un *struct timeval ** donde
le especificas el tiempo que querés que esté bloqueado. Igual ojo con la
implementación de ésto porque si el valor es muy muy corto tendiendo a 0,
practicamente estarías produciendo una espera activa, lo que claramente
está mal además de que seguramente te eleve el uso del CPU muchísimo y es
causa de desaprobación del TP (como se comentó en uno de los workshops,
para ver el uso del cpu tenes top o htop en la consola)

Así que resumiendo, se puede, pero con ciertas limitaciones y cuidados o
quizá podrías diseñar tu solución de otra forma para evitar hacer ésto.

Evalualo y cualquier cosa preguntá nuevamente!

**Comment by cmedrano** [comment]
Gracias! 
Claro, nosotros lo estabamos haciendo con un valor 0 para poder atender lo más rapido posible los pedidos por consola por lo tanto esto estaría, como me decís, generando espera activa.
Implementamos Select en el proceso Memoria.
Necesitamos que salga del select cuando no hay ninguna actividad en los sockets para atender los pedidos de que vienen por consola que estan encolados en una cola, ya que con un select tengo una sola conexión con el LFS.
Como veras no le puedo poner mucho tiempo de espera para que salga del select ya que tengo que responder el pedido que me realizaron por consola lo más rapido posible.
Quizas entonces lo mejor sea que utilice un semaforo mutex para el socket que se concecta con el lfs.

Muchas gracias

**Comment by NaylaWinter** [comment]
@cmedrano buenas, se resolvió este tema? En todo caso te pido si podes cerrar el issue, caso contrario que vuelvas a consultar lo que te quedo duda

**Comment by cmedrano** [comment]
Si el tema está resuelto, muchas gracias!
