### ISSUE TITLE
Duda de archivos temporales en el File System

### ISSUE THREAD

**Issue by germanflighel** [sisoputnfrba/foro#1364]
Buenas!
Implementando el SELECT nos surjió una duda respecto a los archivos temporales y su contenido.
Leyendo la consigna:
![image](https://user-images.githubusercontent.com/18614893/58224913-fcb40a00-7cf5-11e9-9fb5-c282c86a7752.png)
Entendemos que un archivos temporal **.tmp** es como un archivo **.bin**, ya que debe contener el SIZE y los BLOCKS.
Viendo uno de los ejemplos, corroboramos esto:
![image](https://user-images.githubusercontent.com/18614893/58224992-5583a280-7cf6-11e9-903d-e71be9a3cf64.png)
El problema viene al leer el **dump**, y al revisar otros ejemplos. Según lo que entendemos, el dump se ocupa de bajar los datos desde memoria, a los archivos temporales. Hacer el dump entonces, consistiría en tomar los registros y tablas, y guardarlos en estos archivos temporales.
![image](https://user-images.githubusercontent.com/18614893/58225143-1dc92a80-7cf7-11e9-9066-00a79ea2e307.png)
Y en otro ejemplo: 
![image](https://user-images.githubusercontent.com/18614893/58225106-e78bab00-7cf6-11e9-8017-6c6bc0f44b32.png)

En este ejemplo, los datos en los temporales son registros.

Pero, si seguimos el formato que está explicitado en la consigna, yo debería guardar esos datos dumpeados en **bloques**, y no directamente sobre el archivo temporal. Entonces, se guardaría en el archivo temporal, las referencias a esos bloques con los datos dumpeados.
Aquí el problema: el dumpeo actuaría casi como una compactación? No se pierde el punto de compactar, si ya escribo directamente sobre los bloques? O compactar sería tomar solamente los registros con timestamp más alto? No se pierde también la idea de tener disponibilidad, si al dumpear tengo que modificar los bloques?
Otra opción sería que el dumpeo se haga sobre bloques "temporales", y luego al compactar, tomar estos archivos de bloques. Pero esto nos parece que agrega demasiada complejidad, y no se menciona en el TP!

Sintetizando, qué debería haber en los temporales? Referencias o datos?

**Comment by Dragonflares** [comment]
Buenas!

En si? Referencias. El tema de hacerlo en forma de referencias es para separarlo del FS de Linux. Al armar nuestro propio FS hay que usarlo como tal, y guardar las referencias a los bloques en los cuales están guardados los datos. (eso fue lo que me dijeron cuando hice la misma consulta que vos)

Y no, no se pierde la idea de la compactación, porque al hacer un dump, estás bajando todas las claves, absolutamente todas. Sin filtrarlas ni fijarse si hay repetidas, el sacar las que tengan timestamps más viejos depende únicamente de la compactación. Por ende, dentro de los bloques de un .tmp, podes tener una dos veces la misma key con diferentes values y timestamps.

Lo que te digo yo? El select sobre particiones y temps lo hice en la misma función, ya que está leyendo la información de la misma manera, y eso te saca una comparación cuando le mandás el resultado al submódulo Lissandra, pero eso fue mi diea, por ahí se te ocurre una mejor.

**Comment by cmedrano** [comment]
Vale aclarar que también cuando se hace un select se tiene que buscar en los archivos .tmpc.

Éxitos!

**Comment by Dragonflares** [comment]
Cuando se hace un select y hay un tmp.c la tabla no se debería poder accceder. El anexo de compactación indica que una tabla no puede ser accedida (mientras se esté realizando una compactación) para hacer un select.

Saludos!

**Comment by cmedrano** [comment]
Gracias, yo pregunte y me dijeron que si tenía que buscar en los .tmpc también, de hecho ya tenemos desarrollado el select y lo hicimos buscando en los .tmpc.

El único momento en que la tabla queda bloqueada es el momento en que se  borra y se crean los nuevos .bin, que esto es en la etapa final de la compactación, es decir no queda bloqueado durante la compactación sino solamente en el momento en que se borra y se crean los nuevos .bin. 

De todas maneras me alegra que se haya planteado esta duda, quizas hay otras personas que están con la misma duda, esperemos que alguien de la cátedra nos confirme como es el tema.

Saludos!

**Comment by germanflighel** [comment]
Muchachos
Gracias por la respuesta. Les comento que esta duda se la planteé a los ayudantes, y no pudieron darme una respuesta en el momento. Me dijeron que abra este issue, y que luego de charlarlo entre ellos, me darían una respuesta final.

Sobre el dumpeo, en el caso que se haga sobre los bloques, que evita que yo filtre en ese momento y guarde la key con timestamp más alto? Sólo la consigna? No veo el beneficio de sólo dumpear, teniendo la posibilidad de filtrar en ese momento.
Igualmente, estaría perdiendo la disponibilidad al dumpear, si es que estoy modificando los bloques, ya que tendría una concurrencia en los bloques en un dumpeo y un select!

Les pido que esperemos la respuesta de los ayudantes, porque en el TP queda poco claro!

**Comment by rcomesan** [comment]
Todos los archivos del LFS (exceptuando los metadata) se guardan en el formato propio del filesystem. Esto significa que son ini files mas o menos así:

```
blocksCount=3
size=438
blocks=[2,5,9]
```
Respecto del bloqueo de tabla durante la compactación yo tengo la misma duda. En el enunciado primero dice:

> Dentro del sistema las tablas únicamente pueden quedar bloqueadas mientras se realiza el proceso de compactación (Ver Anexo 1).


Pero en el anexo después aclara que la intención es que la tabla se bloquee durante el menor tiempo posible, por lo tanto pide sólo bloquear una tabla durante el remombrado final (una vez ya calculado el resultado de la compactación y las nuevas particiones).

El tema es que bloquear únicamente durante el proceso de renombrado final introduciría problemas.

Supongamos el caso de una compactación recién comenzando y renombrando todos los archivos DUMP#.tmp a DUMP#.tmpc. Y supongamos también que durante ese proceso de renombrado hay una query select ejecutándose sobre la misma tabla. La misma busca (dentro del mismo directorio donde estamos renombrando en otro thread) los archivos dump existentes mediante la syscall readdir() que no garantiza la devolución de archivos agregados/eliminados/renombrados después de la primera call a opendir().

Ahí estaríamos ante un problema, porque puede que la query select esté leyendo archivos del directorio con readdir() y justo la compactación haya renombrado algún dump .tmp a .tmpc y el readdir() del select se lo pierda causando una inconsistencia al no encontrar una key existente.

Por lo cual, para que el LFS sea consistente, minimamente necesitaríamos 2 bloqueos de tabla. Uno para el renombrado inicial y después otro para el renombrado final, lo cual me parece un poquito demasiado. Estimo que un bloqueo general durante todo el proceso de compactación debería ser aceptable según consulté con mis ayudantes, pero no estaría de más poder confirmarlo acá también.

**Comment by Dragonflares** [comment]
Como un minitip, me dijeron que no podemos agregarle un campo al archivo.bin, tiene que ser unicamente BLOCKS y SIZE, y que este en mayus. Es medio quisquilloso, pero habrá que hacerles caso

> 
> Todos los archivos del LFS (exceptuando los metadata) se guardan en el formato propio del filesystem. Esto significa que son ini files mas o menos así:
> 
> ```
> blocksCount=3
> size=438
> blocks=[2,5,9]
> ```
> 
 Con respecto a ésto:

>Por lo cual, para que el LFS sea consistente, minimamente necesitaríamos 2 bloqueos de tabla. Uno para el renombrado inicial y después otro para el renombrado final, lo cual me parece un poquito demasiado. Estimo que un bloqueo general durante todo el proceso de compactación debería ser aceptable según consulté con mis ayudantes, pero no estaría de más poder confirmarlo acá también.

Diría que seguimos necesitando un doble bloqueo de tabla. Porque si, como dijiste, estamos haciendo un select, no convendría congelarlo a mitad de la ejecucion porque mientras estabamos haciendo un select ocurrió una compactación. Está bien que el select pueda ser muy rápido.. pero si esos milisegundos chocan, el select podría llegar a quebrarse. En mi opinión, habría que implementar un semaforo que frene la compactación hasta que termine el select actual antes de iniciarse, y otro para que el select espere a que la compactación termine.

**Comment by Dragonflares** [comment]
Bueno, no se si les sirve lo que cuento por ahí, ya que como no nos dieron mucha pista cuento más o menos como y donde puse yo los semáforos. Puse 4, por cosas que fui descubriendo mientras debuggeaba y mientras ejecutaba. Puse un semaforo durante toda la compactación que no deje hacer un select. Después hay otro semáforo que mientras está renombrando los .tmp que no deje hacer un dump. Por que? Porque hay una chance de milisegundos de que entre esté renombrando el archivo aparezca otro .tmp que no se le hayan escrito los datos correspondientes ni las referencias a bloques, entonces queda un .tmp incompleto que se trata de convertir y después al leer causa un segmentation fault al faltarle información necesaria como que bloques tiene referenciados. Por último, ese mismo semáforo  funciona en ambas direcciones, si hay un dump en curso no va a poder renombrar hasta que no termine de hacer el dump. todo para no perder datos. Son milisegundos, si, Pero te pueden joder toda la ejecucion, como me pasó dos veces mientras lo ejecutaba por más que muchas otras corría bien.

**Comment by NaylaWinter** [comment]
@germanflighel, el proceso de dump consiste en bajar todos los datos que vos tengas en tus tablas en memtable a archivos .tmp. Los archivos .tmp, como te comentaron los chicos, contienen al igual que los .bin referencia a todos los bloques donde se encuentran los datos propiamente dichos, mantienen el mismo formato que se utiliza para las particiones "originales".

El dumpeo no funciona como una compactación, tiene una funcionalidad completamente distinta. Lo que nosotros buscamos en el file system es poder realizar inserciones rápidamente, es por esto que introducimos el área de memtable que nos permitirá realizar inserts sobre memoria mucho mas rápido que si lo hiciésemos propiamente dicho sobre los archivos en el árbol de directorios. El dump nos permite por un lado ir limpiando la memtable, y asimismo poder bajar los datos a archivos en el FS sin necesidad de bloquear las particiones originales para hacer inserciones o actualizaciones sobre los values de las keys. Si analizamos un poco el caso nos damos cuenta que mientras los datos son bajados mediante el dump desde memtable a los temporales, los originales siguen siendo completamente utilizables para realizar selects sobre ellos.

Cuando comentas lo siguiente: _"Sobre el dumpeo, en el caso que se haga sobre los bloques, que evita que yo filtre en ese momento y guarde la key con timestamp más alto? Sólo la consigna? No veo el beneficio de sólo dumpear, teniendo la posibilidad de filtrar en ese momento."_ 
Si te entendí bien, en ese caso estarías realizando al mismo tiempo un dump + una compactación, es decir, bajando los datos al fs y al mismo tiempo comparando los timestamps hasta conseguir el ultimo y escribirlo finalmente. Dentro de nuestro trabajo practico esas dos funcionalidades simplemente las tenemos separadas, en parte por lo que te comentaba arriba de los bloqueos sobre los archivos originales.

La compactación, como mencionas arriba, simplemente nos permitirá poder eliminar todos los temporales, realizando una comparación entre todas las keys existentes en el fs, quedandonos siempre con la que tenga el valor mas alto de timestamp.

Como decís arriba, los bloques utilizados para los .tmp una vez que ocurre el proceso de compactación simplemente son desechados, y pueden utilizarse nuevamente para otros temporales o para las particiones originales, según lo que se necesite.
 
Cualquier otra consulta que tengas sobre este tema, tanto técnica(como el contenido de los .tmp) como mas teórica(el por qué existe el dump / la compactación) te pido si nos la podes indicar

**Comment by rcomesan** [comment]
Gracias por tu respuesta Nay. Podrías confirmar si es aceptable bloquear la tabla (demorar todas las queries) durante todo el proceso de compactación entero? En tal caso, cuál sería el objetivo de 'definir el alcance de la compactación' renombrando archivos .tmp a .tmpc?

En caso de que el bloqueo sólo se permita durante el renombrado final, se te ocurre alguna forma de controlar [éste](https://github.com/sisoputnfrba/foro/issues/1364#issuecomment-495234713) caso? Es requisito que el nodo FS sea consistente o puede ser eventualmente consistente?

**Comment by germanflighel** [comment]
Muchas gracias @NaylaWinter por la respuesta! Ya quedó mucho más claro!
Igualmente, te molesto con una última consulta: al momento de dumpear, es necesario que se pueda seguir accediendo a la mem_table durante el dumpeo? 
Es decir, se debe bloquear la mem_table, por lo tanto bloqueando los inserts y los selects, durante el dumpeo? O hay que mantener la disponibilidad, por ejemplo, duplicando la mem_table y obteniendo los datos a dumpear desde esa mem_table duplicada?
Saludos!

**Comment by Dragonflares** [comment]
@germanflighel 

La que te puedo responder con total seguridad es la segunda, que está en el issue #1381 , que pregunté sobre el caso en el que el FS se llenara de datos.
Yo decidí bloquear la memtable hasta el final del dump y después tirar un list_clean, pero eso depende de mi implementación por supuesto.

**Comment by cmedrano** [comment]
Muchas gracias Nay!
A mi me sigue quedando dos dudas:
1) Ante un select se tiene que buscar también en los archivos .tmpc además de los .tmp .bin y memtable?

2)En la compactación se bloquea las tabla durante el proceso de la compactacion o unicamente en el momento de borrar y crear los nuevos .bin?

Muchas gracias nuevamente!

**Comment by iago64** [comment]
Buenas buenas!!

1.- Seria bueno que pudieras buscar en los tmpc (ya que los tmp los renombraste de tmp a tmpc)
2.- La idea es que en la compactación solo bloqueen la tabla al momento de borrar los archivos y crear los .bin ya que en ese momento tenes una minima inconsistencia.

Saludos.

**Comment by cmedrano** [comment]
Muchas gracias! Si, el sábado pregunte en el laboratorio y me dijeron lo mismo, lo repito capaz le ayude a otras personas
1.- En el select también hay que buscar en los .tmpc
2.- NO se puede bloquear las tablas durante el proceso de compactación, ya que la idea es que los archivos lql sean muy grandes tal que el proceso de compactación va a durar 1 0 2 minutos, si un select tarda ese tiempo en responder la consulta en la entrega final vuelven la semana que viene.
La idea es que en la compactación la tabla se bloqueé un instante pequeño al principio en el renombrado de .tmp a .tmpc
Luego también otro instante pequeño en el borrado y cración de los nuevos .bin.

Saludos

**Comment by iago64** [comment]
Para ampliar un poco mas el punto 2 que muy bien explico @cmedrano 
Es importante que se tenga en cuenta que el renombrado de archivos (o en su defecto el eliminar y crear) genera tiempos donde las referencias a los nombres de archivos no van a ser lógicas (piensen que tienen un 1.tmp y justo estan renombrándolo a 1.tmpc) y les va a generar minimo que rompa algo o en su defecto que digan que no existe el archivo y por consecuencia no busquen ahi.

Abrazo!

**Comment by rcomesan** [comment]
Sí, eso lo entendemos, de hecho lo planteé [acá](https://github.com/sisoputnfrba/foro/issues/1364#issuecomment-495234713) hace más de 2 semanas.

El probelma con todo esto es que no se sabe quién tiene la palabra final. Consulté con 2 ayudantes y la respuesta fué muy distinta a lo que estás planteando ahora. Te pido que minimamente aclares esto en el enunciado, página 35, para tener como respaldo ante una eventual discrepancia en el día de la entrega.

Esto incluye:

1. Especificar los 2 bloqueos de tabla (el enunciado sólo contempla el renombrado final).
2. Redefinir 'tiempo de bloqueo' de una tabla a informar (ahora hay 2 bloqueos).

@iago64

**Comment by nahuelm** [comment]
Buenaaas, creo que esto se esta haciendo demasiado extenso así que voy a resumir la totalidad (espero) de los temas tratados en este issue:

- Donde debo buscar cuando hago un select?
**En todos lados. Memtable, tmp, tmpc y binarios**

- Puedo bloquear la tabla durante todo el proceso de compactación?
**No! El objetivo del proceso de compactación para la entrega final es que dure por lo menos 30 segundos (siendo bondadoso) por lo que el sistema no podrá tener que estar esperando 30 segundos para resolver un select**

- Cuando debo bloquear la tabla?
**Cuando el sistema amerite hacerlo. Con esto me refiero a que esto debe pasar cuando el FileSystem quede en un estado "Incorrupto", osea, cuando este modificando archivos que impliquen que el Select puede fallar por temas de asincronismo. Si lo pensamos tenemos 3 posibles casos que pueden surgir.

1. Al finalizar el proceso de compactación cuando se eliminan los tmpc y los bin para crear los nuevos bin.
2. Al iniciar el proceso de compactación cuando se renombre los archivos tmp a tmpc
3. El proceso de dump cuando bajo los datos de la memtable a los archivos tmp.

Cabe aclarar que los últimos dos puntos como se dijo en varias partes de este issue, son casos muy particulares donde el bloqueo deberia (y TIENE) que ser mínimo. En la entrega NO se aceptara que una tabla este bloqueada durante TODO el proceso de compactación y merge de varios archivos.
**

**Comment by afilgueira** [comment]
Me sumo a la respuesta de Nahue, ya que la pregunta la escuche un par de veces en el checkpoint, y creo que la frase "bloquear la tabla" es demasiado ambigua, sin el contexto adecuado:

- Bloquear estructuras con un mutex, para evitar una condición de carrera, durante el tiempo que tardamos en escribir una variable/estructura --> :+1: 
- Bloquear el proceso completo --> :-1:

**Comment by Dragonflares** [comment]
Buenas!

Ahora, yo tengo una consulta. en mi implementación, en cuanto se hace el renombre de .tmp a .tmpc, inmediatamente leo los .tmpc y extraigo todo el contenido de sus bloques en variables locales y los borro a medida que leo. Hago algo parecido con los .bin, salvo que a estos no los borro ni borro lo que tienen escrito en sus bloques hasta último momento. Por ende, no llego nunca a leer de los .tmpc porque estos son eliminados al instante. En mis pruebas he llegado a tener alrededor de 50 bloques a compactar, y el proceso tardó 1 o 2 segundos aproximadamente. Cuando discutí de ésto presencialmente en soporte no me dijeron que fuera una mala idea. A esta altura, es como si me dijeran 6 cosas distintas a la vez. Entonces, prefiero quedar a una cosa: es válida mi implementación y mi motivo de bloquear toda la tabla desde el inicio? Salvo un mini intervalo en el medio (durante el parseo de las claves leídas así se hace más sencilla su lectura y comparación) y no leer los tmpc que no se llegan a ver?

Desde ya, gracias

**Comment by iago64** [comment]
@Dragonflares a ver si te sigo, en tu implementación tenes algo similar al siguiente pseudo código?
```
sem_wait(sem_tablaA);
compactar(tablaA);
sem_post(sem_tablaA);
```
Ahi mínimo estas contradiciendo lo que dijo @nahuelm y lo que dice el enunciado, independientemente de que tardes 1, 2 o 60 segundos.

Por otra, parte, ese tiempo de 1 o 2 segundos, es lo más relativo que existe, porque no sabes exactamente las condiciones que podes tener en el labo, podes tener una pc con discos infernalmente lentos porque están más que matados y ahi esos 2 segundos se te hacen 20 o 30 segundos (Sin ir mas lejos, fijate que el sábado en el checkpoint no teníamos internet en las VMs y no fue algo que pudimos prever hasta que no empezaron a intentar clonar los repos)

Por último, me parece que se te está olvidando un poco el objetivo final del trabajo práctico y es que apliquen cosas que ven en la teoría (si bien en algunos casos hay licencias _poéticas_ como por ej que en lugar de números de segmento tengan el path de la tabla para que no tengan que hacer una conversión innecesaria). Ahora, volviendo a la parte de semáforos y la teoría, como dije, el objetivo es que apliquen lo visto en la teoría, y por eso es que los profesores en clase les dicen siempre _que la región crítica debe ser lo más chica posible a fin de generar colas de espera_

**Comment by Dragonflares** [comment]
Al final terminé recortando el área de efecto de los semáforos para que no tenga una área critica enorme. Tenían razón con eso, gracias!

**Comment by iago64** [comment]
Dado que entiendo que quedo todo claro, cierro el issue, cualquier cosa para evitar que se extienda y se haga complicado de seguir, por favor abran uno nuevo con la consulta puntual.

Abrazo!
