### ISSUE TITLE
[LFS] Sobre el Insert y la Memtable

### ISSUE THREAD

**Issue by dpeccia** [sisoputnfrba/foro#1365]
Buenas!

Tenemos algunas dudas sobre los pasos que incluye la operación **_INSERT_** del _**LFS**_:

**Sobre el paso 2**: 

> Obtener la metadata asociada a dicha tabla

Para qué necesitamos obtener la _metadata_ en el **INSERT**? si la _memtable_ no tiene particiones, el tiempo entre compactaciones no nos cambia nada en este caso, así que: es por el tipo de consistencia?

**Sobre el paso 3**:

> Verificar si existe en memoria una lista de datos a dumpear. De no existir, alocar dicha memoria

Que le cambia al INSERT si hay una lista de datos a dumpear? No debemos alocar memoria del registro que queremos insertar en la _memtable_ siempre?
Y la _memtable_ en sí, no le reservamos memoria al iniciar el componente? Es decir una vez sola.

Esto último me lleva a otra consulta:

>  El área de _memtable_ deberá estar dividido por tablas

Con esto entiendo que existe una _memtable_ única con muchas tablas. O es que hay una por tabla?

Saludos!

**Comment by NaylaWinter** [comment]
Buenas,

Sobre la primer consulta sobre tener que consultar la metadata de la tabla al momento de hacer un insert: esta operación es innecesaria y la vamos a eliminar dentro de una próxima errata.

Sobre los inserts y la alocación de la memoria: el momento en donde debas reservar la memoria dependerá de tu implementación.

Finalmente: vas a tener una única memtable la cual va a tener "muchas tablas" incluidas.

**Comment by cmedrano** [comment]
Hola capaz te ayude contándote lo que yo entendi !
"Verificar si existe en memoria una lista de datos a dumpear. De no existir, alocar dicha memoria"

Yo entiendo que si existe una lista de datos a dumpear entonces existe la tabla en la memtable. por lo tanto solo agrego el registro.
Si no existen datos a dumpear entonces no existe la tabla en el memtable, por lo tanto aloco memoria para la estructura de la tabla sin registros, luego aloco memoria para el primer registro que viene con el insert.
Por lo tanto en el próximo insert solo aloco memoria para el registro y no para la estructura de la tabla.

Si todas las tablas están en la memtable.

Saludos!

**Comment by NaylaWinter** [comment]
Buenas @dpeccia, tenes alguna otra duda sobre este tema? Si es así te pido si nos la consultas, sino si podes cerrar el issue
