### ISSUE TITLE
Estructura de CMakeList

### ISSUE THREAD

**Issue by lucasnvp** [sisoputnfrba/foro#1366]
Hola, como estan? 

Quería consultar cual sería la correcta estructura de archivos CMakeList para usar todo el proyecto con CUnit.

En el root del proyecto tengo e CMakeListl principal

```
cmake_minimum_required(VERSION 3.5)

project(tp-2019-1c-Gank-mid)

add_subdirectory(Librerias)
add_subdirectory(Kernel)
add_subdirectory(Kernel/test)
add_subdirectory(Memoria)
add_subdirectory(FileSystem)
```

luego por ejemplo en el kernel

``` 
add_executable(Kernel
        src/Kernel.c
        src/Kernel.h
        src/config/Config_kernel.c
        src/config/Config_kernel.h
        src/comandos/comandos.c
        src/comandos/comandos.h
        src/memoria/memoria.c
        src/memoria/memoria.h
        src/api/api.c
        src/api/api.h
        src/tads/script.c
        src/tads/script.h src/criterios/criterios.c src/criterios/criterios.h)

target_link_libraries (Kernel PRIVATE Librerias)
target_link_libraries (Kernel PRIVATE pthread)
target_link_libraries (Kernel PRIVATE readline)
```

y luego en la carpeta de test

```
add_executable(KernelTests
        Run_Kernel_Tests.c
        Run_Kernel_Tests.h
        Test_Memoria/Test_Memoria.c
        Test_Memoria/Test_Memoria.h
        ../src/memoria/memoria.c
        ../src/memoria/memoria.h
        Test_Criterio/Test_Criterio.c
        Test_Criterio/Test_Criterio.h
        ../src/criterios/criterios.c
        ../src/criterios/criterios.h)

target_link_libraries (KernelTests PRIVATE cunit)
target_link_libraries (KernelTests PRIVATE Librerias)
```

lo que me gustaría hacer es no tener que agregar todos los scr del proyecto, existe una forma mejor para hacer esto? 

A demás no me funciono el macro para agregar multiples suites asi que lo solucione agregando los .h y .c de cada uno. 

Desde ya muchas gracias.

Saludos.

**Comment by fabfernandez** [comment]
Hola lucas como va? che pudiste hacer andar los test?
Te parecio util tener tests unitarios o fue una perdida de tiempo implementarlos?
Agradezco tu opinion, saludos

**Comment by lucasnvp** [comment]
Hola, todo bien y vos? Si si, así como mostré los cmakelist funcionan perfecto los test, mi pregunta es si hay una forma más eficiente porque vengo agregando varias cosas y tengo que duplicar todo lo que tengo en los src. 

Con respecto a la utilidad, lleva un ratito configurar todo, pero una vez que lo tenes todo andando, soluciona muchas cosas y te ahorra bastante tiempo de debugger. 
Al tener los test funcionando, también me permitió probar funciones cuando otros módulos no estaban listo, eso es una gran ventaja, ya que cuando se fueron terminando las otras funciones de los módulos, la comunicación entre ambos módulos no tuvieron errores. 

Espero haberte respondido tu pregunta, cualquier cosa decime. 

Saludos.

**Comment by lucasnvp** [comment]
Les dejo un [ejemplo](https://github.com/lucasnvp/CMakeListDirectoryStructure) que hice arreglando este problema.
