### ISSUE TITLE
Qué pasa si se desconecta lissandra?

### ISSUE THREAD

**Issue by GastiV** [sisoputnfrba/foro#1367]
Qué pasa si se me desconecta lissandra? Se deben terminar todos los procesos de memoria o deberían quedarse bloqueados esperando a que se vuelva a conectar/levantar?

**Comment by gastoncastineira** [comment]
Queda a decisión de ustedes. Lo importante es que sin importar lo que pase actué de manera acorde. Si se cierran, que notifiquen por qué y no rompan nada, y si se quedan bloqueados esperando que no permitan ninguna solicitud y avisen por qué

**Comment by GastiV** [comment]
Perfecto, cierro. Gracias!
