### ISSUE TITLE
Manejo de segmentos de memoria

### ISSUE THREAD

**Issue by GastiV** [sisoputnfrba/foro#1368]
Si tengo dos segmentos contiguos S1 y S2, y quiero agregar una página al segmento S1 que tiene todas sus marcos ocupados y sus respectivos flags de modificado en 1. Vamos a tener que reacomodar el primer segmento S1 a un hueco de memoria principal en donde quepa este segmento además de una página nueva?

**Comment by gastoncastineira** [comment]
En segmentación paginada los marcos de memoria que ocupen las páginas de los segmentos no necesitan estar de manera contigua, por lo que podés agregarle otra página al segmento sin grandes problemas si es que hay marcos libres

**Comment by GastiV** [comment]
Bárbaro, tengo que repasar la teoría entonces. Gracias!
