### ISSUE TITLE
Comando select en el proceso memoria

### ISSUE THREAD

**Issue by cmedrano** [sisoputnfrba/foro#1369]
Hola!
en el paso 3 cuando se hace un select en el proceso Memoria dice
"Una vez obtenido se debe solicitar una nueva página libre para almacenar el mismo. En caso de no disponer de una página libre, se debe ejecutar el algoritmo de reemplazo y, en caso de no poder efectuarlo por estar la memoria full, ejecutar el Journal de la memoria
"
Cuando dice "en caso de no disponer de una página libre , se debe ejecutar el algoritmo de reemplazo" 

Para nosotros siempre vamos a poder ir agregando páginas  al segmento(a la tabla) el único caso en que no vamos a poder agregar más páginas es cuando la memoria este full o completa, es decir no tenga marcos libres.

No tengo una limitación de páginas por segmento, donde mi segmento representa una tabla.

Esto esta bien? tengo que agregarlo una limitación?

**Comment by NaylaWinter** [comment]
Buenas,

No tenes una limitación de páginas por segmento, pero si vas a tener una cantidad máxima de páginas dentro del sistema, no podes ir agregando páginas ilimitadamente a tus segmentos porque la memoria tiene un tamaño máximo.

Vas a correr el algoritmo de reemplazo cuando necesites agregar una nueva pagina a un segmento y todas las páginas disponibles del sistema están siendo utilizadas por este o por otro segmento.

**Comment by cmedrano** [comment]
Hola Nayla,

Si te entiendo, hay un limite, ese limite lo define la cantidad de frames que tiene la memoria.
Mi consulta es si yo por ejmplo tengo una memoria de 5 frames y tengo 2 segmentos(tablas) que cada uno tiene dos pagínas(registros) que están en memoria por lo tanto tengo ocupado 4 frames de la memoria.
Ahora cuando viene un registro nuevo de la tabla A lo agrego al único frame que tengo disponible.
Ahora tengo todos los frames ocupados, la memoria esta a full. Tengo que hacer Journaling.
Mi duda es en que momento tengo que aplicar el algoritmo de reemplazo si siempre que tenga marcos libres voy a poder agregar paginas nuevas y en el caso que ya no tenga marcos libres entonces voy a ejecutar un Journaling?
Puede ser que se tenga que aplicar el reemplazo cuando no tengo marcos libres y tenga que insertar una pagina nueva pero no es el momento de hacer un Journal?


Muchas gracias

**Comment by NaylaWinter** [comment]
Dentro del ejemplo que me das me hacen ruido un par de cosas: Cuando llega un nuevo registro de la tabla A y lo agregas al único frame que tenes disponible **no tenes la memoria full**. La memoria full solo se da cuando todos los marcos están ocupados y **aparte** todos están con flag de modificado = 1. 
En el caso que me explicas cuando utilizas los 5 marcos que tenes, cuando llegue un sexto registro recién ahí vas a aplicar el algoritmo de reemplazo, reemplazando el ultimo de los marcos que haya sido  utilizado y que asimismo tenga el flag de modificado en 0. Recién vas a realizar journaling cuando el algoritmo de reemplazo te indique que no hay mas marcos disponibles para reemplazar, es decir, que están todos modificados, en tu ejemplo esto se daría si una vez que cargaste los cinco marcos realizas un INSERT para cada una de las claves que tenes en esos marcos.

La regla para saber que ejecutar en cada momento seria:
Tengo marcos libres?
     Si (hay libres) -> Uso uno de los libres
     No (están todos ocupados) -> Corro el algoritmo de reemplazo. Puedo reemplazar alguno?
                                                         Si (hay alguno con flag de modificado en 0) -> Lo reemplazo
                                                         No (están todos ocupados y con flag de modificado en 1) ->Memoria        full -> Debo realizar journaling

**Comment by janicead** [comment]
Yo tengo una consulta sobre este tema, si yo tengo mi tabla de paginas que tengo 2 registros dentro, y los dos estan con el flag modificado = 1, pero en mi memoria en otra tabla de pagina hay un registro con un flag en 0, q es lo que deberia hacer?? Lo tengo que sacar a ese registro de esa tabla de paginas que no era de mi segmento y poner al nuevo registro en la tabla de paginas original?? Es decir, cuando yo quiero realizar un nuevo registro, me tengo que fijar en mi tabla de paginas si hay alguna con el flag en modificado, y si todas estan en modificado, fijarme si en otra tabla de paginas hay alguno sin estar con el flag modificado?? Espero que se entienda la consulta, me es dificil explicar bien la duda

**Comment by NaylaWinter** [comment]
Buenas,

Si, los segmentos "se pueden robar páginas entre si". 
El algoritmo de reemplazo de páginas que estamos usando es dinámica y global, es decir, que para reemplazar no vamos a utilizar únicamente los marcos que ya fueron asignados a un segmento sino que también vamos a validar los marcos de los demás.

En tu ejemplo esta bien que si llega una nueva página a insertar de un segmento que ya tiene todos sus marcos con flag de modificado en 1 entonces vayas a reemplazar el de otro segmento. Esto último únicamente considerando que no hay marcos libres, sino se le asignará uno libre.
En caso de no encontrar un marco reemplazable en todo el sistema (todos los segmentos) diremos que la memoria esta full.

**Comment by janicead** [comment]
Gracias! Me quedo clarisimo!

**Comment by cmedrano** [comment]
Perfecto muy claro! 
Muchas gracias!
