### ISSUE TITLE
Consulta sobre consumo de CPU aceptable

### ISSUE THREAD

**Issue by Dragonflares** [sisoputnfrba/foro#1370]
Buenas!

Quisiera saber si el modulo de Lissandra del tp con éste nivel de consumo de CPU está aceptable, dentro de todo. Marco que solo le di 1 nucleo de un i5 de 5ta generación.

![imagen](https://user-images.githubusercontent.com/28828524/58437230-73a72500-809f-11e9-8118-60a3281f67f0.png)

Saludos y muchas gracias

**Comment by tferraro** [comment]
No hay chance que un tp use más el 100% de la CPU, no importa la cantidad de cores. Tenes tremenda espera activa che :/

**Comment by Dragonflares** [comment]
@tferraro El consumo de CPU es 39,5 por algun motivo el 100% de arriba no se mueve, esté apagado o no el proceso de Lissandra. Por ahí ya la maquina virtual no tiene suficiente de CPU para correr del todo bien (y eso explicaría por qué Eclipse anda siempre medio trabado), o htop lee mal ahí arriba

**Comment by iago64** [comment]
Buenas!

Ese consumo es sin hacer nada de nada? osea, el proceso solo esperando conexiones.
Porque eso huele a una espera activa de aca a la china.

Saludos.-

**Comment by Dragonflares** [comment]
Hola!

No, tiene 5 Tablas levantadas esperando a compactar en hilos paralelos, un hilo para los dumps de la memtable y el hilo del servidor esperando conexiones. También hay otro hilo para la consola.

Saludos

**Comment by Dragonflares** [comment]
Para ser más especifico, voy a explicar bien qué es lo que está haciendo en ese momento en mi sistema. Al menos en cantidad de hilos que tienen while(!deathProtocol)  que esperan con un usleep para ejecutarse una vez más :

- 4 Hilos que corren con un while(NULL != list_find(tablasEnEjecucion, tabla) que manejan las compactaciones de cada tabla.
- 1 Hilo del servidor que espera a que se conecte una memoria.
- 1 Hilo de la consola que corre hasta que se escriba "exit"
- 1 Hilo del gestor de dumps con un while (!lastDumpSituation) que se vuelve 0 cuando la consola tira un exit.

Cuando ejecuto una instrucción como máximo sube hasta 42%, más no.

**Comment by iago64** [comment]
Y no probaste cerrando la primer aplicación que te esta consumiendo 38.8%?
desde htop podes tirarle kill con F9... una vez que hagas eso decime a cuanto te sube el consumo de CPU :)

ese 42% es un claro signo de que no puede escalar mas porque no tiene recursos.

**Comment by Dragonflares** [comment]
Si le hago kill vuelve a aparecer al rato, si no hay ninguna otra, se sigue comiendo el 100% del CPU, estuve googleando y no pude encontrar hasta el momento.

**Comment by iago64** [comment]
Queres duplicar la apuesta? corre el LFS en la VM server, ahi no tenes gnome-do que te puede llegar a comer 30% de CPU.

Desde la china se ve la espera activa, controla como estas manejando esos hilos que tienen el while porque me huele a que te estas comiendo algo de sincro y/o algun semaforo y eso en la entrega es motivo de desaprobación directa.

**Comment by Dragonflares** [comment]
Bueno, acabo de conseguir un 87% de consumo de CPU, lo cual no es para nada divertido.
Hay alguna manera de saber que hilo es el que más CPU está consumiendo? Aparte de matarlos? Probe sacando las tablas y bajó un 1% nada más.

**Comment by Dragonflares** [comment]
![image](https://user-images.githubusercontent.com/28828524/58516351-0b7b4080-817e-11e9-85ed-f65aea353d71.png)

Bueno, encontré el desastre que estaba rompiendo todo. Sacando esto y cambiandolo por un pthread_mutex alcanzó para bajar del 89% a 1% de CPU o menos sin memorias conectadas.

**Comment by tferraro** [comment]
Para futuras referencias, ese extracto de código es lo que se denomina **espera activa** 🙂
