### ISSUE TITLE
Mantener info de tablas y Gossiping en Kernel

### ISSUE THREAD

**Issue by cmedrano** [sisoputnfrba/foro#1372]
Hola,!
En el Kernel, para realizar el mantenimientos de la metadata de las tablas y el mantenimiento de la tabla gossiping entiendo que el  pedido puedo realizarlo a cualquier memoria, verdad? o lo tengo que hacer a alguna memoria que este asociado a algún tipo de criterio?

Nosotros lo estábamos implementando con dos hilos, un hilo que actualice la tabla gossiping cada un determinado tiempo. Luego otro hilo que actualice la info de las tabla cada un determinado tiempo. Para ambos casos le pedíamos a la memoria que conoce por primera vez, esa que esta en el archivo de configuración.
Lo que pasa es que si se llega a desconectar dicha memoria, luego no podar seguir actualizando dicha información. Es posible que desconecten esta memoria? O no ?
O tenemos que ingresarlo en la cola de listo para luego el planificador lo tome?

Muchas gracias

**Comment by NaylaWinter** [comment]
Buenas,

La metadata de las tablas la podes actualizar contra cualquiera de las memorias que tengas conocidas desde el Kernel. Es posible que desconectemos la memoria principal que se conoce por archivo de configuración, así que te recomendaría que simplemente al momento de refrescar la metadata obtengas una random entre todas las que el Kernel conoce y a esta le consultes la metadata.

Por otro lado te consulto dos cosas que me hicieron ruido: 
1) Por qué el Kernel solo hace gossiping con la memoria principal que conoce por archivo de configuración?
2) A que te referís con: "tenemos que ingresarlo en la cola de listo para luego el planificador lo tome?" ?

**Comment by cmedrano** [comment]
Perfecto gracias!

Por otro lado te consulto dos cosas que me hicieron ruido:

1.Por qué el Kernel solo hace gossiping con la memoria principal que conoce por archivo de configuración?

Lo vamos a modificar para que pueda consultar al resultado del random entre las memorias.

2. A que te referís con: "tenemos que ingresarlo en la cola de listo para luego el planificador lo tome?" ?

Me refiero a que quizas esto pueda ejecutarse como si fuera una query que consulta 1 Quantum y lo puedo agregar a la cola de listos para que luego pueda ser ejecutado. Pero creo que no es así verdad?.

Muchas gracias

**Comment by NaylaWinter** [comment]
Con respecto al primer tema: el Kernel no hace gossiping solo con **una** memoria, lo hace con todas las que tenga en su lista de sedes, al igual que todo el resto de las memorias. No vas a tener que elegir una memoria random y consultarle todo el pool, sino que a todo el pool le vas a hacer gossiping.

Con respecto a utilizar la planificación para poder refrescar la metadata la idea es que lo hagas "en paralelo". No deberías ocupar un quantum de planificación para hacer el refresh de la metadata.

**Comment by cmedrano** [comment]
Muchas Gracias Nayla,
¿Quiere decir que el Kernel tiene que pedir la tabla de gossiping  a todas las memorias que él conoce? En primer instante solo pedira a la única que conoce y luego pedira a todas las que va conociendo? Entonces si esto es así luego tendra que hacer un merge de las memorias quitando las memorias repetidas, porque me imagino que cuando le den la tabla gossiping de todas las memorias van a existir repeticiones.
¿Esto mismo descrito anteriormente lo tiene que hacer cada memoria?
¿Cuando decís lista de sedes, te referis a las memorias que va conociendo con el proceso gossoping, verdad?

Con respecto a lo segundo quedo claro, lo estamos haciendo  en otro hilo para que simule que esta ejecutando en paralelo.

Muchas gracias nuevamente por tu ayuda!

**Comment by NaylaWinter** [comment]
Hola,

Si, la lista de seeds es la lista de memorias que conoce mediante gossiping.
Efectivamente el Kernel debe pedir la tabla de gossiping a todas las memorias que conoce, inicialmente se la consulta a la memoria que tiene configurada en el archivo de config y luego consultará con toda la tabla.

Tanto el Kernel como las memorias al realizar el gossiping deben realizar el merge que comentas.

**Comment by cmedrano** [comment]
Muchisimas gracias!

**Comment by chamenwais** [comment]
Hola @NaylaWinter 

Perdón, pero con respecto a lo que decís:

_el Kernel no hace gossiping solo con una memoria, lo hace con todas las que tenga en su lista de sedes, al igual que todo el resto de las memorias. No vas a tener que elegir una memoria random y consultarle todo el pool, sino que a todo el pool le vas a hacer gossiping._

_Si, la lista de seeds es la lista de memorias que conoce mediante gossiping.
Efectivamente el Kernel debe pedir la tabla de gossiping a todas las memorias que conoce, inicialmente se la consulta a la memoria que tiene configurada en el archivo de config y luego consultará con toda la tabla._

Lo que pide el enunciado es que el Kernel haga gossiping con **una** memoria: ¡la que tiene en el archivo de configuración!:

_Al momento de inicializarse el Kernel, **solicitará a una memoria (configurada por archivo de configuración)** cuáles son las memorias que componen el pool (cada memoria conocerá al pool por medio de la técnica de gossiping, Anexo III)._

Tiene sentido porque:
- Por un lado el kernel no tiene una lista de seeds como si tienen las memorias.
- Por otro lado el gossiping se hace 1 a N donde N es la cantidad de seeds del proceso, y el kernel solo conoce una memoria.
La memoria que el kernel conozca va a ir trayéndole la lista actualizada, porque las seeds de dicha memoria le van a ir dándo a conocer el resto.

Y me surge la siguiente duda, ¿Está bien que el kernel intercambie su lista de seeds a la memoria del archivo de conf (como sí debe hacerlo cada memoria) y sólo consuma la info, porque de hecho no tiene seeds?

Gracias.

**Comment by iago64** [comment]
@chamenwais Si, tiene sentido que el kernel solo consulte la lista de seeds de la memoria, pero que no mande la suya, por eso no te hagas drama, lo importante es que las memorias si intercambien porque a propósito van a tener memorias que el kernel solo las va a poder conocer después de que las conozca la primer memoria con la cual configuras el kernel ;)

**Comment by chamenwais** [comment]
Macanudo, cierren el issue que yo no puedo. Gracias
