### ISSUE TITLE
FS fragmentacion de bloques

### ISSUE THREAD

**Issue by AndresMarcovecchio** [sisoputnfrba/foro#1373]
Una consulta, si yo tengo que guardar en un bloque los siguientes datos:
key -> 123
value -> "valor"
timestap -> 567
tengo que guardar en el archivo de bloque algo así:
567;123;valor
El tamaño va a ser de 3(de567)+1(;)+3(de 123)+1(;)+5(de "valor")+1(\n)=14
La consulta es:
1) Que pasa si mi tamaño de bloque es menor a 14, ya que no entraría, tiro un error, o lo guardo particionado en 2 bloques, o nunca va a pasar?
2) Cuando ya guarde varios valores y quiero meter uno nuevo y no me entra, lleno hasta donde pueda, o genero fragmentación interna.
3) En caso de fragmentación interna el size del archivo va a ser incluyendo o sin incluir la fragmentación que se me genera.
Muchas gracias.

**Comment by Dragonflares** [comment]
Buenas!

1) Lo tenés que separar en dos bloques, te recomendaria que uses algo que chequee el tamaño total de todas las claves a impactar en el bloque asi podes ir viendo bien cuanto vas a tener que escribir. También para escribir, te recomiendo usar mmap dentro de los bloques.
2) Generá fragmentación interna.
3) Sin incluir, diriía yo. Cuando pregunté era simplemente cortar la clave hasta donde llegara y con eso alcanzaba.

Espero que te sirva

**Comment by AndresMarcovecchio** [comment]
> * s que separar en dos bloques, te recomendaria que uses algo que chequee el tamaño total de todas las claves a impactar en el bloque asi podes ir viendo bien cuanto vas a tener que escribir. También para escribir, te recomiendo usar mmap dentro de los bloques.
> * Generá fragmentación

Pero si voy por la opción que decís en el punto 1 de partirlo en 2 bloques, en el punto 2, para que voy a generar fragmentacion interna en cada bloque?, me convendría solamente tenerla en el bloque final, debería de seguir como venia trabajando en el punto uno como para seguir siempre la misma lógica de trabajo. Si en unos haces fragmentacion interna como en el punto 2 y en otro lo partís como en el punto uno, como sabes cuando esta partido y cuando esta completo? Podrías saberlo con el fin de archivo, o alguna otra cosa, pero seria algo mas rebuscado y no seguiría con la misma lógica.
Lo correcto creo q seria o usar una especie de "asignación contigua" a pesar de q no van numerados sucesivamente y tener fragmentacion interna solo en el ultimo bloque, o ir llenando de a bloques con fragmentacion interna en casi todos los bloques.
Esperemos a ver que dicen los ayudantes.
Saludos.

**Comment by Dragonflares** [comment]
Buenas

Me disculpo por la contestación medio dormida, no estaba en mis 10 a esa hora y eso que eran las 8.

Cuando hablé con uno de los ayudantes me dijo que hay que usar asignación contigua. Por ende, no hay fragmentación. No se para que te dije que usaras fragmentación. 
El tema de escribir en un bloque se trata de agarrar y sacar toda la información del bloque, vaciarlo, y escribir sobre el bloque vacío. Entonces cada vez que compactas estás limpiando tanto los bloques asignados a los temporales como a las particiones que tienen claves a compactar, así después cuando haces los chequeos por la clave más actualizada y escribís en el bloque no tenés ningún problema de espacio y los bloques siempre te quedan asignados en orden, permitiendo que cuando los levantas de vuelta puedas leer una clave de corrido sin preocuparte por escribir en un bloque anterior a los ya asignados.
Espero que se entienda.

Saludos

**Comment by Dragonflares** [comment]
Quizá para clarificar te dejo esto, como para ser un poco más explicativo con mi ejemplo.


![Ejemplo](https://user-images.githubusercontent.com/28828524/58707603-cc223f00-838b-11e9-99f6-8c57cbc71cda.png)


El archivo de la derecha es una de las particiones de mis tablas y los de la izquierda son los bloques que tiene asignados. Si yo hiciera otro insert más, se extendería a otro bloque más si el tamaño conjugado supera los 128 bytes.

**Comment by iago64** [comment]
Bueeenas y taardes!

Si si, tenemos hyper colgado el issue, mala nuestra :(
Respecto a la consulta, efectivamente es como comenta @Dragonflares la asignación va a ser contigua y no van a tener que sufrir calculando a ver si entra bien la key en su archivo o si tienen que mover todo hasta el que sigue y no saber posta posta donde termina su archivo.

La idea al final de cuentas es que si uds tienen por ej la tabla1 con la siguiente metadata (usando bloques de 100 bytes):

SIZE=112
BLOCKS=[45,5]

Uds puedan leer el bloque 45 completito y después solo los 12 bytes que les faltan del bloque 5, algo similar a lo que mostró @Dragonflares en la captura de pantalla.

Un abrazo!

**Comment by AndresMarcovecchio** [comment]
Ok joya, gracias a los 2.
Una ultima para cerrar el tema, los caracteres '\n' y ';' también los tenemos en cuenta para llegar a los 100 bytes, verdad? Osea dentro de los 100 bytes del bloque vamos a tener una parte que van a ser delimitadores, por lo que data posta quedaría menos.
Saludos.

**Comment by iago64** [comment]
Si señor, esos caracteres ocupan espacio :)

**Comment by AndresMarcovecchio** [comment]
Ok gracias
