### ISSUE TITLE
Criterios - Kernel

### ISSUE THREAD

**Issue by cmedrano** [sisoputnfrba/foro#1374]
Hola!
Perdón , quizás es una pregunta tonta pero la verdad esta parte no la entendí del todo.

Entiendo que una misma memoria puede ser asignada a distintos criterios y que el criterio SC solo tiene que tener asignada una sola memoria .
Entonces mi duda es, la memoria que esta asignada al criterio SC puede estar también asignada a otro criterio?

Muchas gracias

**Comment by NaylaWinter** [comment]
Hola,

Si, la memoria que esta asignada al criterio SC también puede estar asignada a los demás criterios

**Comment by NaylaWinter** [comment]
@cmedrano cómo venís con esto? Podemos cerrar el issue o querer consultar algo mas?

**Comment by cmedrano** [comment]
Buenísimo! Muy claro como siempre!

Muchas gracias!
