### ISSUE TITLE
Qué datos eliminar de Memoria al hacer Journal

### ISSUE THREAD

**Issue by Frilo** [sisoputnfrba/foro#1375]
Hola, tenía una duda sobre el Journaling

En el Anexo IV - Journaling dice:
> Este proceso consiste en encontrar todas aquellas páginas cuyas Key deben ser actualizadas dentro del FS y enviar por cada una de estas una petición de insert al FileSystem indicando los datos adecuados.
Una vez efectuados estos envíos se procederá a desactivar el Flag de Modificado de todas las páginas y eliminar los segmentos actuales.

Según entiendo, hay que eliminar todos los segmentos de la tabla de segmentos y dejar toda la memoria principal "vacía".
Al eliminar los segmentos (actuales?) de la tabla de segmentos también habría que borrar sus respectivas tablas de páginas porque al borrar los segmentos se pierden sus referencias.

No entiendo por qué habría que desactivar el Flag de Modificado de las páginas en la tabla de páginas si total se van a eliminar todas las tablas de páginas. Me parece que no estoy entendiendo qué datos se van a borrar de la Memoria al hacer el Journal.

**Comment by NaylaWinter** [comment]
Buenas, 

Estamos por sacar una errata en donde eliminamos la parte que indica que hay que desactivar el flag de modificado.

Como vos decís: una vez que se realiza el journal se eliminan todas las páginas y segmentos y se limpian todas las estructuras, es innecesario primero eliminar el flag.

**Comment by Frilo** [comment]
Ok, muchas gracias!

**Comment by cmedrano** [comment]
Hola, 
tengo una consulta respecto a este punto, entiendo que luego de hacer el journal tengo que vaciar los segmentos y las paginas de la memoria también limpiar la memoria y todas las estructuras.
Mi duda surge al problema de la inconsistencia que puede generarse al momento de hacer este proceso cuando lleguen otras solicitudes como insert, select,  drop etc sobre esta memoria, por lo cual estaba pensando si estaría bien hacer lo siguiente al momento que esta corriendo el proceso Journal.
1) Bloquear la memoria unicamente cuando llegue un Insert o Drop para no generar inconsistencias.
2)Al llegar un select no bloquear nada, ya que solo es de lectura. Solo bloquear un instante pequeño al momento final de limpiar la memoria.

Muchas gracias

**Comment by cmedrano** [comment]
Hola @NaylaWinter 
Creo que mi duda fue aclarada, en el enucniado dice lo siguiente:
"Cuando una memoria se encuentra procesando o realizando un Journal a Disco no se podrá operar ningún request que le llegue a la memoria, debiendo esperar a que el primero finalice."

Por lo tanto cuando se esta realizando un JOURNAL toda solicitud tanto por consola de Memoria o por el Kenel deben esperar hasta terminar la operacio JOURNAL.  ¿ Es correcto?

Muchas gracias
