### ISSUE TITLE
Resultado de ejecutar un Script

### ISSUE THREAD

**Issue by cmedrano** [sisoputnfrba/foro#1377]
Hola,

Cuando se ejecuta un run <path del script> desde la consola del Kernel, este debe devolver algo por consola? por ejemplo si dentro del script se encuentra un select, el resultado de ese select tiene que ser visto por consola?

Entiendo que para el caso donde se realiza un select directamente desde la consola(sin ningún archivo script) si te debería mostrar el resultado por consola, verdad?

Me parece que el resto de los comandos cuando es por un archivo script no son necesarios mostrar algún resultado por consola, pero me llamo la atención del select en ese caso.

Muchas gracias

**Comment by iago64** [comment]
Buenas!
Eso es comportamiento no definido, si te queda cómodo hacer un printf del resultado o simplemente lo dejas en el archivo de log, medio que no te cambia siempre y cuando se ejecute correctamente y tengamos al menos una manera fácil de identificar la ejecución (Los archivos de log si son prolijos son una manera super fácil).

Abrazo!

**Comment by cmedrano** [comment]
Perfecto! muy claro!

Muchas gracias!
