### ISSUE TITLE
Drop en memoria

### ISSUE THREAD

**Issue by mesaglio** [sisoputnfrba/foro#1378]
Haciendo el drop, nos dimos cuenta de que si tenemos registros guardados en memoria y dropeamos una tabla que tenga algunos registros en memoria. Quedarian huecos en memoria.
Por ejemplo:
 . Reg1 {TS: KEY: VALUE: } (Tabla 1)
 . Reg2 {TS: KEY: VALUE: } (Tabla 2)
 . Reg3 {TS: KEY: VALUE: }(Tabla 1)
Dropeando la tabla 2, eliminariamos las paginas de dicha tabla y perderiamos la referencia al Reg2.
Se nos ocurrio agregarle un bit de presencia al t_registro, el cual se analizara al aplicar el lru. 
Al ejecutar el lru, antes de fijarse el timpo de acceso de las paginas, tendria que revisar registro por registro y ver si hay alguno con el bit de presencia en 0.

@iago64

**Comment by iago64** [comment]
Buenas buenas!
No se a que viene el @ pero gracias por tenerme en cuenta :)

Respecto a la pregunta, estás tomando un camino complicado que no se te va a dar por el simple hecho de que la memoria esta basada en segmentación paginada, donde cada segmento es corresponde a 1 tabla y este segmento a su vez se divide en páginas, con lo cual, si hago DROP Tabla 2 por ej, las páginas de la tabla 2 van a quedar libres y las va a poder tomar otro "proceso", o mejor dicho, otra tabla :)

Abrazo!

**Comment by ncoen97** [comment]
Hola, amplío un poco mas sobre la consulta. Nuestra duda va orientada hacia el bloque de memoria (malloc de 2048) donde se guardan los Registros. En el DROP las paginas las podemos liberar bien por lo que nombras de la segmentación paginada, pero yendo a los registros, si eliminamos la pagina perdemos la referencia al registro de esa pagina y ahí es donde nos queda el "agujero".
Como dijo @mesaglio , una de nuestras ideas era agregar al registro un bit de presencia y utilizarlo para que cuando hagamos el LRU podamos retornar el puntero a ese registro que ya no esta en uso y así poder reutilizarlo. Otra opción que estuvimos hablando era la de hacer un BitArray para ir contabilizando los registros que están asignados a una pagina y los que quedaron en desuso.

**Comment by iago64** [comment]
Buenas!

Ahora si vamos por partes:

malloc de 2048? malloc de lo que diga el config, pueden ser 2048 como 65536, no se queden con una idea de tamaño fijo por favor.

Ahora bien, para saber que marcos estan en uso y que marcos no, pueden usar un bitarray, un vector de marcos, lo que uds quieran, no esta definido que tienen que usar una estructura puntual, con lo cual, la respuesta simple es: Usen lo que les sea mas facil.

Abrazo!

**Comment by mesaglio** [comment]
Gracias
