### ISSUE TITLE
Inicializacion de LFS y sus directorios

### ISSUE THREAD

**Issue by axelgrimb** [sisoputnfrba/foro#1379]
Cuando se inicializa LFS, nosotros entendemos que hay que crear los directorios [PUNTO_MONTAJE], al igual que: [PUNTO_MONTAJE]/Tables, [PUNTO_MONTAJE]/Bloques y [PUNTO_MONTAJE]/Metadata.
Ademas, consideramos que los archivos de los distintos bloques deberían ser creados también en el directorio Bloques basados en el valor de BLOCKS del Metadata.bin del directorio Metadata. 
Sabiendo que este Metadata.bin también lo estoy creando en la inicialización, este va a estar vacio (A menos que se hardcodee el contenido a través de un fwrite). 
Me comentaron que es muy probable que el Metadata.bin me lo den o lo tenga que crear a mano, por eso mi pregunta es:
A la hora de crear todos los directorios y archivos de mi FS, y al no contar con el contenido del Metadata.bin, como podría crear los bloques que estarían especificados en dicho archivo? Ya que al parecer que en este punto de la ejecución no cuento con dichos datos. Y en el caso de que me den dicho archivo, tengo que suponer que entonces ya existen los directorios que nombre antes?

**Comment by Dragonflares** [comment]
Buenas!

Un detalle que hable con un ayudante.  Todo el punto de montaje y los directorios que incluye, tienen que venir previamente creados a mano. No los crea el FS.
Lo que nos van a dar los ayudantes son los bloques dentro de MountFileSystem/Blocks y el bitmap.bin.
Todo lo demás... sea la carpeta Tables y la Metadata vienen previamente creadas. Al igual que el archivo Metadata.bin que va dentro de dicha carpeta Metadata. Sino, cuando ellos te den el File System y el bitmap, donde los vas a poner? Tendrias que hacer una movida a mano de los bloques dentro de la carpeta blocks (usar rename x cantidad de veces, donde x es la cantidad de bloques.), o haciendo ctrl+x ctrl+v para pegar los bloques en tiempo de ejecución, lo cual es muy mala idea.
Así que te recomiendo crear las carpetas a mano, nada mas.

Saludos!
Waise neiat

**Comment by NaylaWinter** [comment]
Buenas,

Para las pruebas les podemos dar o no un filesystem armado. En caso de que no es responsabilidad del grupo armarlo y crear las estructuras necesarias para esto.

En caso de que no este creado entonces les vamos a pasar los datos de la metadata del filesystem, con esto deben: inicializar los bloques, crear el bitarray, crear los directorios y escribir el archivo metadata.bin. Estos pasos se pueden realizar tanto dentro del proceso (codeándolos en C) o por fuera, utilizando la consola y comandos como mkdir, vi, nano, etc.

**Comment by Dragonflares** [comment]
Buenas

@NaylaWinter , entonces eso significa que tendría que cambiar la dirección del punto de montaje en el archivo de configuración para el caso en que nos den un FS completo, no?

**Comment by iago64** [comment]
@Dragonflares y por algo les dimos ese parametro configurable por archivo de config :)

**Comment by cmedrano** [comment]
Buenísimo! yo tenía esa duda también. Nosotros en el caso que no nos den un FS ya creado, vamos a crear las carpetas que están dentro del punto de montaje (Tables, Bloques,etc) por consola utilizando mkdir, etc.

Claro, el punto de montaje puede cambiar, pero eso se resuelve modificando el punto de montaje desde el .config

Muchas gracias

**Comment by YoelIbarra** [comment]
@NaylaWinter Una cosa que no me quedo muy clara, los bloques y el archivo metadata, nos los dan ustedes o los debemos crear cuando iniciamos LFS?

**Comment by NaylaWinter** [comment]
Buenas,

Tenes dos opciones: o que se los demos creados nosotros o que no se los demos. En el caso que se los demos entonces van a simplemente buscar el punto de montaje y utilizarlo, si no, van a tener que crear ustedes los directorios, archivos y estructuras correspondientes para su uso.

Por ejemplo: para las pruebas del checkpoint presencial no les estamos otorgando un FS armado, para las pruebas finales podemos o no darles el FS.

**Comment by iago64** [comment]
@axelgrimb se entendio todo? necesitas una mano con algo mas? 👮

**Comment by JaniceFassi** [comment]
Buenas! Me sumo a las consultas, porque todavía no nos quedan muy claras algunas cosas.
Entendemos que si nos dan el file system armado, simplemente tenemos que ir a buscar el punto de montaje y arrancar desde ahí sin crear nada, por lo tanto, el archivo config también nos lo darían armado en una ruta conocida? En cuál sería? (No tendría sentido modificar el código cada vez que pueda cambiar esa ruta).
Pero si no nos lo dan armado, todos los datos necesarios nos los van a dar ustedes? (nos referimos al punto de montaje, la cantidad de bloques, tamaño, etc). En dicho caso, deberíamos crear tanto el archivo config desde cero, como todo el directorio, incluidos los archivos de metadata. Acá nos encontramos en la misma situación de antes, había que tocar el código cada vez que se modifiquen los datos, y es sumamente inaceptable.
Para solucionar esto, estaría bien pedir todos los datos por consola al principio? (tanto para el archivo config como para el metadata.bin).
Espero respuesta, desde ya muchas gracias!

**Comment by Dragonflares** [comment]
La ruta del archivo de configuración de la metadata va a ser tal como está explicada en el enunciado:

![image](https://user-images.githubusercontent.com/28828524/59372973-0b06ac00-8d1f-11e9-815e-d493a31a7105.png)

Lo unico que tendrías que modificar sería el archivo de configuración que viene dentro de tu repo, para que conozca la nueva ruta del punto de montaje. 

Por otro lado, tenog mi propia duda:

Es aceptable configurar el FS para que pueda cambiar de punto de montaje durante el tiempo de ejecución? En el caso de modificar el DUMPTIME y el DELAY los puse como funciones de consola que luego hacen que se alerte al notify. Ahora bien, podría hacer eso para el punto de montaje del FS? Considerando eso que el FS tenga que dar de baja todas las tablas previas, y sacar del juego todo los datos innecesarios, para luego levantar las tablas existentes en el nuevo y reconfigurar su funcionamiento

Desde ya, muchas gracias

**Comment by iago64** [comment]
Buenas buenas!!
Otro tema medio olvidado, pero bueno, @JaniceFassi la respuesta de @Dragonflares no estaba muy errada, posiblemente nosotros solo les demos el Metadata.bin y uds tengan que crear el FS.

Ahora @Dragonflares no seria lo ideal que tengan el FS subido al repo ya que con el antecedente del checkpoint donde la red del labo no fue lo mas amigable con la entrega, por mas que el FS pese 200mb, son 200mb de NADA que tendrían que bajar, con lo cual, te recomiendo que si tenes el FS en el repo, lo hagas crema, prefiero que pierdan 5 o 10 minutos creando el FS de 0 a 30 bajandolo del repo :)

Volviendo nuevamente a la pregunta de @JaniceFassi, 100% seguro que el metadata.bin del FS se lo vamos a dar ya que si no, no van a tener forma de crear su FS desde la nada, con lo cual no sería necesario que pidan por consola cada campo de ese archivo.

Abrazo!

**Comment by JaniceFassi** [comment]
Gracias a ambos! Queda bastante más claro. Recapitulo por las dudas: desde un principio vamos a buscar el archivo config que tiene ip, puerto, etc, en la ruta conocida (que por el momento tenemos adentro del repo). Ahí ya podemos sacar el punto de montaje, crear todo el directorio y crear un nuevo Metadata.bin con los datos del Metadata.bin que nos dan ustedes, y el primero se va a crear adentro de la carpeta Metadata de nuestro directorio recién creado. Entendí bien?
Más allá de eso, mi duda sobre la ruta era a dónde voy a buscar los archivos config y Metadata.bin que nos dan ustedes para leer los datos que necesito, no en dónde los guardo una vez creado el directorio.
Saludos!!

**Comment by iago64** [comment]
@JaniceFassi El archivo de config, podes tenerlo en una ruta conocida o recibirlo como parámetro de tu programa, ahí ambas opciones son validas :D
Respecto al punto de montaje... ni, en realidad posiblemente nosotros les demos un punto de montaje que va a tener las carpetas de Metadata, Blocks y Tables y el archivo de Metadata.bin y uds van a terminar creando el resto del FS (los bloques en principio ya que va a ser un FS vacio)

Saludos

**Comment by iago64** [comment]
@axelgrimb damos por cerrado el tema o podemos ayudarte con algo mas? 👮

**Comment by iago64** [comment]
Cerramos el issue por inactividad
