### ISSUE TITLE
Duda con escritura de bloques FS

### ISSUE THREAD

**Issue by AxelFulop** [sisoputnfrba/foro#1380]
Hola buenas noches, tengo la siguiente duda:

Cuando se van escribiendo los bloques con datos, supongamos que se definen bloques de 64 y tengo estos bloques asignados libres [1,2,3]

voy escribiendo en el bloque 1 hasta que inserto 60 bytes por ejemplo, luego me llega un insert de datos de 6 bytes, inserto los primeros 4 bytes en el 1 y luego los dos restantes en el bloque 2,y asi con cada bloque que tenga, hasta que llego al bloque 3 (ultimo bloque disponible)
voy insertando datos hasta que llego a 60 bytes como en el caso anterior.Si me llega una solicitud de insert de 6 bytes, que se debe hacer? se insertan los 4 bytes y se lanza un mensaje de que no existen mas bloques disponibles o directamente no se insertan los 6 bytes y aviso que no quedan bloques disponibles en esa particion?

muchas gracias

**Comment by Dragonflares** [comment]
Buenas!

Para asginar un bloque a un partición o temporal tenés que estar por escribir en ese bloque(salvo cuando creas la tabla, que solo asignás un bloque vacío para cada partición, pero ese bloque se desasigna al momento de hacer la compactación). Entonces si te quedás sin espacio para escribir en ese bloque que acabás de pedir, pedís uno nuevo y se lo asignas. Las particiones no tienen bloques fijos,
Esto lo hable con Tomás, Maxi y Julian.

Espero que te sirva!

**Comment by iago64** [comment]
Buenas buenas!

Lo que comenta @Dragonflares no está del todo bien, porque falto aclarar el dato más importante, primero tenes que validar que tengas más bloques libres en el FS.
Si no hay bloques libres en el FS, ahi tenes que avisar que no se puede procesar por falta de espacio.

Slds.-

**Comment by AxelFulop** [comment]
Genial, gracias a los dos.Cierro issue

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________
