### ISSUE TITLE
Consulta sobre FileSystem FULL

### ISSUE THREAD

**Issue by Dragonflares** [sisoputnfrba/foro#1381]
Buenas!

Tengo una consulta sobre el caso en que tenga el FS en full cuando me llegan inserts (tanto por consola como por memoria) ya que tengo tres posibles implementaciones:
1) La primera es tratar de hacer un Dump y fallar, borrando todo el contenido de la memtable y no creando ningún temporal.
2) La segunda es seguir recibiendo inserts y testeando el si hay espacio suficiente para dumpear todo el contenido de la memtable dentro del FS con la espera entre dumps..
3) La tercera es poner que haya una variable global del FS que diga "FSFULL" (inicializada = false"), que se ponga en true cuando quiera hacer un dump y encuentre que no hay suficientes bloques para dumpear. Y luego, que cuando una memoria quiera hacer un insert, o la consola lo intente, la chequee y no les permita realizar el insert hasta que se haya podido dumpear.

Desde ya, muchas gracias

**Comment by NaylaWinter** [comment]
Buenas,

En primer lugar te comento lo siguiente: el caso que estas planteando es bastaaaante border, bajo ningún concepto es una condición mínima de aprobación tener considerado este caso dentro de lo que nosotros vamos a estar evaluando. Te recomendaría que plantees este problema si solo si tenes el file system andando perfectamente y queres mejorarlo, antes que plantearlo cuando hay otros puntos pendientes que si son importantes.

Finalmente: no tenemos una implementación definida de como se debería tratar este caso, quedará a decisión del grupo cual es la que van a optar. Por una cuestión de que el caso planteado es bastante complejo te diría que vayas por la opción que te resulte mas fácil de implementar para que le puedan dedicar mas desarrollo a otros issues que les pueden ir surgiendo.

**Comment by Dragonflares** [comment]
Muchas gracias por la respuesta!

Si, el FS ya está terminado y mientras espero a la entrega presencial estuve limando los errores que podían quedar. Y entre eso descubrí que si llenaba el FS y trataba de dumpear el FS creaba nuevos bloques, lo cual no tiene sentido, y no estuvo nunca en mi implementación, así que me pareció un poco extraño

**Comment by iago64** [comment]
Es un caso muy borde, la realidad es que si llenas el FS y nos informas de que esta lleno el FS y queda ahi esta bien.

En este caso tienen la libertad de implementarlo como consideren mejor, lo importante es que entiendan las consecuencias de su decision para despues discutirlas en el coloquio.

Saludos.-

**Comment by Dragonflares** [comment]
Muchas gracias! Cierro issue entonces
