### ISSUE TITLE
comandos - Memoria

### ISSUE THREAD

**Issue by cmedrano** [sisoputnfrba/foro#1382]
Hola, 
Tengo una duda sobre como manejar las querys que vienen por consola del Kernel.
Segun el enunciado en una parte dice:

API
La API responderá a los mismos comandos utilizados en la Memoria más dos propio:
SELECT
INSERT
CREATE
DESCRIBE
DROP
JOURNAL
ADD
RUN
METRICS
Los primeros cinco comandos cuando sean solicitados al Kernel serán directamente redireccionados a la memoria elegida por el criterio de la tabla en cuestión.

Mi primera duda es cuando se ejecuta un comando de los primeros cinco, estos  se tienen que planificar junto con los otros scripts que vienen con el comando RUN <path script> ? es decir si ejecutamos por consola del Kernel "SELECT POSTRES 3" esto lo tengo que tomar como un script de una sola linea y encolarlo luego a la cola de listos? o directamente se envía a memoria sin pasar por planificación? En algún momento escuche que había que tomarlo como un script de una sola línea y planificarlo también, pero no estoy seguro por eso es la pregunta.

Muchisimas gracias

**Comment by NaylaWinter** [comment]
Hola, 

Las request que se ejecutan en consola deben ser interpretadas como si fueran un script de una única línea, deben ser planificados como todo el resto de las operaciones que entran por scripts lql

**Comment by cmedrano** [comment]
Muchas gracias! 
Todos los comandos o solo los primeros cinco deben ser planificados?

En los scripts solo habra comandos de algunos de los primeros cinco? o puede que haya también alguno de los otros 3 comandos?


Cuando se ejecuta CREATE TABLA1 SC 4 60000
El criterio al que debe ir es al que se muestra en los parametros del create verdad? en este caso SC. Porque no tengo la info de esa tabla aún, ya que recién va ser creada.

Muchas gracias

**Comment by iago64** [comment]
Buenas buenas!!

Recien revisando los issues encontre este que lo teniamos abandonado.
A priori, las que no deberias planificar serian ADD, RUN y METRICS, pero para que no sea una respuesta vacía, te dejo una duda (que a mi gusto es candidata de ser pregunta de coloquio)
_Si las memorias ejecutan instrucciones cual CPU en la realidad... se te ocurre por que no tendrías que planificar un ADD, un RUN o un METRICS?_

Saludos.-

**Comment by cmedrano** [comment]
Muchas Gracias! 
Puede ser porque, si es como vos decís, si las memorias ejecutan instrucciones análogo a una cpu, estos comandos (ADD,RUN,METRICS) no llegan nunca a memoria/cpu  entonces no consumen quantum ? por esa razón nunca estarán en algún script.


Muchas gracias nuevamene!

**Comment by iago64** [comment]
@cmedrano efectivamente :) si no llegan a las memorias no te consumen Quantum

**Comment by cmedrano** [comment]
Muchas gracias Damian! @iago64
