### ISSUE TITLE
Transicion entre New y Ready

### ISSUE THREAD

**Issue by achani2497** [sisoputnfrba/foro#1383]
Buenas, tengo una duda con esta parte del enunciado 

> Al ingresar un nuevo script al sistema el mismo se ubicará en la cola de “New”, se crearán las estructuras administrativas necesarias para su ejecución y pasará al estado “Ready”.  

Apenas termine de crear las estructuras que menciona el enunciado el script tiene que pasar a Ready o hay que esperar algún evento? Con "evento" me refiero a por ejemplo, que la cantidad de scripts en estado Ready disminuya de 4 a 3 por ejemplo (en el enunciado no se menciona nada del grado de multiprogramacion, pero pregunto por las dudas).

**Comment by NaylaWinter** [comment]
Buenas,

Una vez que tengas creadas las estructuras para poder planificar el script simplemente lo vas a pasar a la cola de Ready. En este trabajo practico no contemplamos el concepto de grado de multiprogramación.

**Comment by achani2497** [comment]
Genial, gracias!
