### ISSUE TITLE
Memoria- Comando Select

### ISSUE THREAD

**Issue by cmedrano** [sisoputnfrba/foro#1384]
Hola!
Tengo una consulta, cuando se hace un select sobre la memoria en el caso que no exista el segmento. ¿Tengo que también enviar la solicitud al LFS y luego crear un segmento y una pagina para almacenar el nuevo valor?
Entiendo que si no existe la key pero el segmento si existe tengo que enviar la solicitud al LFS. Pero en el caso que no exista el segmento también? o debo retornar algún error?

En el enunciado dice lo siguiente

SELECT
La operación Select permite la obtención del valor de una key dentro de una tabla. Para esto, se utiliza la siguiente nomenclatura:
	SELECT [NOMBRE_TABLA] [KEY]
Ej: 
SELECT TABLA1 3
Esta operación incluye los siguientes pasos:
Verifica si existe el segmento de la tabla solicitada y busca en las páginas del mismo si contiene key solicitada. Si la contiene, devuelve su valor y finaliza el proceso.
Si no la contiene, envía la solicitud a FileSystem para obtener el valor solicitado y almacenarlo. 
Una vez obtenido se debe solicitar una nueva página libre para almacenar el mismo. En caso de no disponer de una página libre, se debe ejecutar el algoritmo de reemplazo y, en caso de no poder efectuarlo por estar la memoria full, ejecutar el Journal de la memoria.

Muchas gracias

**Comment by NaylaWinter** [comment]
Hola,

Si realizan una operación sobre una tabla cuyo segmento no tenes simplemente iras a buscar los datos al LFS y cargaras el segmento correspondiente.
Se realiza la misma lógica tanto con los segmentos que con las tablas: si no están, se van a buscar al file system y se cargan en memoria.

**Comment by cmedrano** [comment]
Perfecto! Muchísimas Gracias Nayla!
