### ISSUE TITLE
Multiples requests a una misma memoria

### ISSUE THREAD

**Issue by fakukpg** [sisoputnfrba/foro#1385]
Buenas tardes, 

Hoy charlando con mi grupo nos surgió una duda respecto a la planificación. Teniendo en cuenta que ya se le envió una linea de un LQL a una memoria, podría otro LQL enviarle su línea a esa misma memoria o la memoria solo puede atender una request a la vez?

Gracias,

**Comment by NaylaWinter** [comment]
Buenas,

Las memorias deben poder atender múltiples request en simultáneo. Dado que tenes varios scripts en estados de Exec al mismo tiempo completamente independientes entre si los mismos podrían enviarle las operaciones a la misma memoria sin conocer si el otro igualmente le mando una operación a esta última.

Dentro del enunciado figuran las dos alternativas que pueden plantear para poder atender las distintas request en la memoria: estas son multihilos o multiplexación.

**Comment by cmedrano** [comment]
Hola!
Tengo una duda respecto a este tema, primero estoy de acuerdo que se le pueden mandar múltiples requests a la misma memoria dato que tengo varios scripts en estado exec, lo que me gustaría validar es que una vez que tengo en la misma memoria por ejemplo 3 solicitudes estas se van a atender de a una si utilizo un select dentro de la memoria que esto sería multiplexación verdad? esta bien eso?

Implementando un select en la memoria, yo acepto varios requests y los voy atendiendo a medida que el select me devuelve el socket que tiene movimiento, entonces cuando recibo la solicitud la atiendo y le envío la respuesta al kernel, si la solicitud del kernel que llega a memoria requiere una operación del LFS entonces mando la solicitud al LFS y espero su respuesta, una vez que tengo la respuesta envío la respuesta al Kernel. Luego vuelvo a recibir otra operación que viene de un socket que sale del Select y vuelvo a repetir lo mismo.. Todo esto en una misma memoria.  Esto estaría bien?

Muchas gracias

**Comment by NaylaWinter** [comment]
Hola,

Si utilizas un select se van a atender de a una. 
Lo segundo que mencionas también es correcto.

**Comment by iago64** [comment]
Buenas @fakukpg y @cmedrano como vienen con este tema? se entendio la respuesta de nay o hace falta que los ayudemos con algo mas?

**Comment by cmedrano** [comment]
Muchas gracias Nay y iago64! 
Se entendio perfectamente!

**Comment by iago64** [comment]
@fakukpg vos como venis? podemos ayudarte con algo mas? 👮

**Comment by fakukpg** [comment]
Buenas! No,todo bien. Colgue en cerrar el issue.

Gracias
