### ISSUE TITLE
Consulta sobre Documento de Prueba

### ISSUE THREAD

**Issue by cmedrano** [sisoputnfrba/foro#1386]
Hola, 
En el documento de prueba dice
"
Asociar la Memoria 1 al criterio SC y una vez que el Kernel actualizó la metadata de las tablas creadas anteriormente ejecutar el script comidas.lql y animales.lql. Luego de que comience a correr el script comidas.lql, ejecutar misc_1.lql
"
Cuando dice "..tablas creadas anteriormente.. " entiendo que hay que crear tablas anteriormente de ejecutar el script comidas.lql y animales.lql. Esto es así? si es así en el documento creo que no aparece la descripción de la cración de las tablas que se deben crear antes de ejecutar los scripts. 

Muchas gracias

**Comment by NaylaWinter** [comment]
Hola,

Recién actualicé el documento de pruebas, nos había quedado inconsistente contra un cambio que hicimos. 
Una vez que asocian la memoria ya deben empezar a correr los scripts, no hace falta esperar ningún metadata refresh.

**Comment by rcomesan** [comment]
Aprovecho para avisar que

`INSERT FRUTAS 90001 "Mango"`

debería fallar (90001 no entra en uint16) y está listado en valores esperados página 4.

**Comment by NaylaWinter** [comment]
Ahi lo modifiqué! Gracias por el aviso :D

**Comment by cmedrano** [comment]
Muchas gracias Nayla!
