### ISSUE TITLE
Consulta sobre insert y dump FS

### ISSUE THREAD

**Issue by FrodriguezSandez** [sisoputnfrba/foro#1387]
Tengo una consulta sobre la interpretación del enunciado.

En el insert dice
Esta operación incluye los siguientes pasos:
Verificar si existe en memoria una lista de datos a dumpear. De no existir, alocar dicha memoria.

¿A qué "memoria" se refiere? 
Si es a la memtable, ¿Qué es lo que debería fijarme? Dice "Datos", se refiere a que con que haya un dato o cuántos. No entiendo el criterio. Además , no dice qué hacer si no pudiera ser alojado.
¿O se refiere a memoria , módulo memoria? Porque interpreté una idea de prioridad o semáforo, en el que el journaling que hace memoria (que son varios insert a fs) tiene prioridad sobre los insert propios de FS. En mi mente tiene sentido, sin embargo no me queda claro a qué apunta este punto.

La pregunta en sí es , ¿qué es lo que me está pidiendo que revise antes de terminar el insert propio de FS?

**Comment by NaylaWinter** [comment]
Buenas,

Lo que te esta indicando es que al intentar realizar un insert sobre el LFS primero valides si para esa tabla ya existen otros registros anteriores a dumpear, esto es dentro de la memtable.
Si ya existían registros anteriores entonces simplemente vas a agregar el nuevo al final de la lista de registros a dumpear para esa tabla, si no, debido a que es el primero, también deberías crear la estructura de la lista donde luego vas a seguir insertando los nuevos registros a dumpear.

**Comment by iago64** [comment]
@FrodriguezSandez Como va? esta resuelta la duda? 👮
