### ISSUE TITLE
Describe - Kernel

### ISSUE THREAD

**Issue by cmedrano** [sisoputnfrba/foro#1388]
Hola,
Tengo una duda cuando se hace un DESCRIBE / DESCRIBE <Nombre_tabla desde la consola del Kernel o desde una línea de algun script.

El enunciado por una parte dice:
"Para mantener la metadata de las tablas actualizada el kernel llevará registro de cuáles son las tablas creadas en el sistema en una estructura administrativa. Esta estructura se cargará luego de haberse conectado a alguna memoria haciendo un DESCRIBE global a la misma. Luego, esta estructura se actualizará cada un tiempo obtenido por archivo de configuración realizando nuevos DESCRIBE globales a cualquier memoria que tenga conectada."

Entiendo que cada determinado tiempo se van a actualizar las tablas de la estructura administrativa en el kernel.

En otra parte el enunciado dice 
"Los primeros cinco comandos cuando sean solicitados al Kernel serán directamente redireccionados a la memoria elegida por el criterio de la tabla en cuestión."

Dentro de los cuales esta el comando Describe

Mi pregunta es cuando hago un describe ya sea por consola o por algún archivo script tengo que actualizar también la estructura administrativa del las tablas en el kernel?

Cuando tengo atender desde el kernel una solicitud de Describe global, ya sea tanto por consola o por alguna línea de algún script, tengo que enviar ese describe a una sola memoria de cualquier criterio como el describe global que se ejecuta al inicio del proceso con la memoria que tiene por archivo de configuración? o tengo que enviar a distintas memorias según el criterio de cada una de las tablas.
 
Muchas gracias

**Comment by NaylaWinter** [comment]
Buenas,

Si, cuando realizas un describe también debes actualizar las estructuras administrativas de las tablas del Kernel.

Cuando realices un describe global, tanto por que sea para refrescar la metadata como si esa request vino desde un script, vas a poder realizarlo con cualquiera de las memorias que tengas conocidas del pool, es indistinto si es la del archivo de configuración o no.

**Comment by cmedrano** [comment]
Muchas gracias Nay!! Se entendió perfectamente!
