### ISSUE TITLE
Getline();

### ISSUE THREAD

**Issue by YamilaOrlando** [sisoputnfrba/foro#1389]
Buenas gente, estoy teniendo un problema con el Getline, soy uno de los dos qué está encargada del modulo FileSystem y se me presentó el siguiente problema:

(1)
![codes_y_resultado](https://user-images.githubusercontent.com/22182698/59068023-7a951b00-8889-11e9-8116-ffe0874f0f5c.JPG)

(2)
![archivoPrueba](https://user-images.githubusercontent.com/22182698/59068020-78cb5780-8889-11e9-862d-174dc13694d3.JPG)

El segundo es el archivo de prueba, que contiene 4 linea, PERO, cuando el getline(); trabaja en la imagen de arriba, solo nos devuelve dos de las 4... ¿Alguna idea?
¡Gracias desde ya!

**Comment by mgarciaisaia** [comment]
**Disclaimer**: programar el TP en Windows no suena a una buena idea.

------

Todo está funcionando como se lo pediste a la máquina, sólo que lo que le pediste no coincide del todo con lo que _realmente querés_ pedirle.

La condición del `while` se evalúa cada vez que tenga que decidir si repetir el bucle o no. Y `getline()` _consume_ la entrada - es decir, si tengo dos líneas disponibles en el buffer, al hacer `getline()` por primera vez leo la primer línea, y _la próxima vez que ejecute `getline()` voy a obtener la siguiente_.

Si revisás tu código, empieza en la línea 26 leyendo una línea para ver si ejecutar el bloque, encuentra que sí tiene (es decir, _lee la primer línea del archivo_), lo imprime (línea 27), _lee una nueva línea del archivo a la variable `read`_, y.... vuelve a evaluar si tiene que entrar al ciclo. Es decir, _lee una nueva línea del archivo_ - ¡la tercera!

¿Qué sobra ahí?

**Comment by YamilaOrlando** [comment]
¡YA LO VI! La linea 28 está de mas! ¡Muchísimas gracias! 
<hr>
PD; estoy en mi laptop (donde no tengo la maquina virtual no espacio para crearla) y para hacer pruebas cortas rápidas le doy en Windows. Sí, soy consciente no es la mejor opción, me lo dijeron como 5 personas ya, jaja.
