### ISSUE TITLE
Duda de C: consistencia en el valor de un semáforo

### ISSUE THREAD

**Issue by GastiV** [sisoputnfrba/foro#1390]
Buenas! En memoria tenemos sincronizada la ejecución de las request que llegan por consola o desde el kernel y nos interesa logear si en el momento de la ejecución esta puede esperar o ejecutarse directamente. La duda que nos surgió es si podría ocurrir una inconsistencia entre los valores que voy a loggear y consumir.
El código vendría a ser el siguiente:

```c
int value;
sem_t* unSemaforo;
t_log* logger;
sem_getvalue(unSemaforo, &value);
log_info(logger, "EL valor del semaforo es %i", value);
sem_wait(unSemaforo);
```

Podría darse el caso de que se loggee "El valor del semáforo es 1" y que al ejecutar la siguiente sentencia el mismo sea 0 y se bloquee la ejecución porque algún otro hilo hizo un sem_wait de ese semáforo antes?

**Comment by rcomesan** [comment]
Totalmente. Si el semáforo lo usás desde múltiples threads puede y va a pasar. 

[sem_getvalue](https://linux.die.net/man/3/sem_getvalue) devuelve el valor del semáforo en el instante que justo realizás la call, nada garantiza que el valor no cambie antes de ejecutar tu sem_wait.

> $ man sem_getvalue
> ..
> NOTES
>     The value of the semaphore may already have changed by the time sem_getvalue() returns.
> ..

Fijate si te sirve [sem_trywait](https://linux.die.net/man/3/sem_trywait) o directamente diseñá la ejecución de las tareas de forma que no dependa del valor del semáforo en un determinado instante.

**Comment by iago64** [comment]
Buenas buenas!! 
La respuesta de @rcomesan es correcta, el pedir un valor del semaforo (con sem_getvalue) te va a devolver el semaforo en el momento que lo solicites, pero no te asegura que al instante siguiente siga valiendo lo mismo.

Saludos.-

**Comment by GastiV** [comment]
Perfecto, gracias!
