### ISSUE TITLE
Consulta sobre documento de Prueba Kernel-Memoria

### ISSUE THREAD

**Issue by cmedrano** [sisoputnfrba/foro#1391]
Hola!
Una consulta, cuando ejecuto el  archivo comidas.lql
la primera linea que ejecuto es 
CREATE POSTRES SC 3 60000
Esto me va a crear un directorio en la maquina del LFS con toda la metadata, etc.
Luego inmediatamente ejecuta la siguiente línea que es la siguiente
INSERT POSTRES 100 "Flan"
En este punto esta mi pregunta, ya que al intentar ejecutar este insert no tengo la metadata de la tabla POSTRES en mi estructura en el Kernel, ya que antes debería hacer un DESCRIBE de esta tabla para tenerla. Necesito tener la metadata de esta tabla para saber que tipo de consistencia tiene.

Entonces quería preguntar cada vez que se hace un CREATE desde el kernel tengo que guardar la metadata de esta tabla en el Kernel para estos casos? 
Pregunto porque el enunciado dice que  al recibir un CREATE directamente se redirecciona a la memoria.

Muchas gracias

**Comment by NaylaWinter** [comment]
Hola,

Ahi modifiqué los scripts y les agregué los describes antes de los inserts, gracias!

**Comment by Dragonflares** [comment]
Hola, @NaylaWinter 

Sin embargo, no se suponía que el describe no era para ésta entrega? Ponerlo como parte de las pruebas en este momento sería poco congruente para los que no lo tengan levantado. A lo sumo se puede hacer como dijo @cmedrano de crear la tabla y que se agregue a la tabla de metadatas del Kernel, sino no queda.

**Comment by cmedrano** [comment]
En la línea 63 del mismo script se hace un SELECT FRUTAS 22, pero nunca se inserto en esa tabla con esa key, esta bien eso? esta así apropósito?

Muchas gracias

**Comment by NaylaWinter** [comment]
Si una key no existe simplemente podes informarlo por consola

**Comment by iago64** [comment]
@cmedrano como venis con este tema? podemos ayudarte con algo mas??

**Comment by cmedrano** [comment]
Muchas gracias!!!
Se resolvió la duda! :)

**Comment by cmedrano** [comment]
Hola.
tengo una duda con respecto al describe <tabla> en los archivos lql de prueba.
En el archivo misc_1.lql por ejemplo la primera linea hace un 
CREATE COLORES SC 2 35000
Luego en la segunda línea hace un describe de esa tabla, lo cual esta perfecto pero el problema es que al momento de hacer DESCRIBE COLORES no tengo aún la metadata de la tabla COLORES en el proceso KERNEL por lo cual cuando va a buscar la consistencia de la tabla para luego seleccionar una memoria esta no se encuentra por lo tanto no sé a que memoria enviar la solicitud en este caso.

Muchas gracias

**Comment by NaylaWinter** [comment]
Hola, enviala a cualquier memoria del pool.

**Comment by cmedrano** [comment]
Muchas gracias @NaylaWinter
