### ISSUE TITLE
Problemas con Eclipse

### ISSUE THREAD

**Issue by YamilaOrlando** [sisoputnfrba/foro#1392]
Buenas gentuza, 
Vuelvo otra vez a abrir una issue porque desde hace tres horas qué Eclipse no responde, y he intentando de todo. Les muestro con lo que me la paso encontrando cada vez que lo tengo qué ejecutar.
![image](https://user-images.githubusercontent.com/22182698/59140751-5a905500-8978-11e9-8ec2-39d7589a7b99.png)

Espero que alguno me sepa dar una mano, intenté instalar otro Eclipse bajandolo de GoogleChrome de la VM pero no me deja ejecutar el ejecutable de la instalación.

¡Gracias desde ya, saludos!

**Comment by mgarciaisaia** [comment]
👋 Dice [la internet](https://unix.stackexchange.com/q/230238) que los errores que se leen en la terminal son "comunes", y que no les des bola. Alguien sugiere que ejecutes `export NO_AT_BRIDGE=1` en la consola en que estás intentando ejecutar Eclipse, o que corras `dbus-uuidgen > /var/lib/dbus/machine-id` si tenés `dbus-uuidgen` disponible, pero probablemente eso evite el mensaje de error, pero no el problema de fondo.

Lo que nos va a ayudar a entender qué pasa (quizá) son los logs de Eclipse. Acá [el amigo Joe](https://javapapers.com/tips/eclipse-log-file-location/) dice que los logs están en `<workspace_location>/.metadata/.log`, donde `<workspace_location>` suele ser algo dentro de tu directorio Home (no recuerdo bien dónde teníamos instalado Eclipse en las VMs, busque, busque :) ).

Fijate si encontrás eso y lo subís, así vemos qué está pasando posta.

¡Éxitos!

**Comment by YamilaOrlando** [comment]
Al final terminé reinstalé la maquina virtual. Ando con falta de tiempo para poder chequear las cosas! Igual una vez tenga un espacio igual lo voy a chusmear! ¡Gracias!
