### ISSUE TITLE
Error en el malloc inicial de la memoria

### ISSUE THREAD

**Issue by micayeza** [sisoputnfrba/foro#1393]
Buen día! Estoy peleando hace un rato con el gran malloc de la memoria.

Tengo declarado un void* inicio, al que le asigno el resultado del gran malloc.
Luego dentro de un for, para ver el estado del gran malloc, casteo el puntero a mi tipo t_pag ( que contiene int, char* , int)

la operacion es: t_pag* memoria = inicio + ( tamaño(t_pag) * i) donde i es el contador del for.
Luego de 2 o 3 vueltas, el char* dice: 0xb3c36963 <error: Cannot access memory at address 0xb3c36963>
Se esta realizando mal el malloc? o estoy declarando algo mal??

Gracias!
@Zheoden

**Comment by iago64** [comment]
Buenas buenas!

A priori tenes un problema y es que estas teniendo:
int
_char*_
int

Ese char* lo que te dice es que estas apuntando el value afuera de tu gran malloc, con lo cual, ahí ya empezas un toque mal desde la parte teorica del TP.

Por otra parte, seria un golazo de media cancha, de chilena y con los ojos cerrados, que corrieras eso con valgrind y nos pasaras lo que te devuelve, ya que ahi vas a tener la data de que es lo que paso.

Saludos.-

**Comment by micayeza** [comment]
Hola! 
Te envió el valgrind con la operacion insert.
valgrind --leak-check=full ./MEMORIA
==6223== Memcheck, a memory error detector
==6223== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==6223== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==6223== Command: ./MEMORIA
==6223==


 CONSOLA MEMORIA

Comandos disponibles:

    1) SELECT [NOMBRE_TABLA] [KEY]
    2) INSERT [NOMBRE_TABLA] [KEY] “[VALUE]” [TIMESTAMP O VACIO]
    3) CREATE [TABLA] [TIPO_CONSISTENCIA] [NUMERO_PARTICIONES] [COMPACTION_TIME]
    4) DESCRIBE [NOMBRE_TABLA o VACIO]
    5) DROP [NOMBRE_TABLA]
    6) JOURNAL
    7) SALIR

Operación> INSERT MICA 1 CANDE

==6223== Thread 2:
==6223== Conditional jump or move depends on uninitialised value(s)
==6223==    at 0x4030CE9: memcpy (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==6223==    by 0x80498C1: nueva_pagina (memoria.c:197)
==6223==    by 0x8049A82: nuevo_segmento (memoria.c:245)
==6223==    by 0x804A3B3: operacion_insert (memoria.c:540)
==6223==    by 0x804ACBD: conexionConsola (memoria.c:777)
==6223==    by 0x4061294: start_thread (pthread_create.c:333)
==6223==    by 0x41A30AD: clone (clone.S:114)
==6223==
==6223== Conditional jump or move depends on uninitialised value(s)
==6223==    at 0x4030CEF: memcpy (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==6223==    by 0x80498C1: nueva_pagina (memoria.c:197)
==6223==    by 0x8049A82: nuevo_segmento (memoria.c:245)
==6223==    by 0x804A3B3: operacion_insert (memoria.c:540)
==6223==    by 0x804ACBD: conexionConsola (memoria.c:777)
==6223==    by 0x4061294: start_thread (pthread_create.c:333)
==6223==    by 0x41A30AD: clone (clone.S:114)
==6223==
==6223== Conditional jump or move depends on uninitialised value(s)
==6223==    at 0x4030CFE: memcpy (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==6223==    by 0x80498C1: nueva_pagina (memoria.c:197)
==6223==    by 0x8049A82: nuevo_segmento (memoria.c:245)
==6223==    by 0x804A3B3: operacion_insert (memoria.c:540)
==6223==    by 0x804ACBD: conexionConsola (memoria.c:777)

==6223==    by 0x4061294: start_thread (pthread_create.c:333)

==6223==    by 0x41A30AD: clone (clone.S:114)

==6223==

==6223== Conditional jump or move depends on uninitialised value(s)

==6223==    at 0x4030D45: memcpy (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)

==6223==    by 0x80498C1: nueva_pagina (memoria.c:197)

==6223==    by 0x8049A82: nuevo_segmento (memoria.c:245)

==6223==    by 0x804A3B3: operacion_insert (memoria.c:540)

==6223==    by 0x804ACBD: conexionConsola (memoria.c:777)

==6223==    by 0x4061294: start_thread (pthread_create.c:333)

==6223==    by 0x41A30AD: clone (clone.S:114)

==6223==

==6223== Conditional jump or move depends on uninitialised value(s)

==6223==    at 0x4030E88: memcpy (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)

==6223==    by 0x80498C1: nueva_pagina (memoria.c:197)

==6223==    by 0x8049A82: nuevo_segmento (memoria.c:245)

==6223==    by 0x804A3B3: operacion_insert (memoria.c:540)

==6223==    by 0x804ACBD: conexionConsola (memoria.c:777)

==6223==    by 0x4061294: start_thread (pthread_create.c:333)

==6223==    by 0x41A30AD: clone (clone.S:114)

==6223==

==6223== Use of uninitialised value of size 4

==6223==    at 0x4030ED2: memcpy (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)

==6223==    by 0x80498C1: nueva_pagina (memoria.c:197)

==6223==    by 0x8049A82: nuevo_segmento (memoria.c:245)

==6223==    by 0x804A3B3: operacion_insert (memoria.c:540)

==6223==    by 0x804ACBD: conexionConsola (memoria.c:777)

==6223==    by 0x4061294: start_thread (pthread_create.c:333)

==6223==    by 0x41A30AD: clone (clone.S:114)

==6223==

==6223== Invalid write of size 4

==6223==    at 0x4030ED2: memcpy (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)

==6223==    by 0x80498C1: nueva_pagina (memoria.c:197)

==6223==    by 0x8049A82: nuevo_segmento (memoria.c:245)

==6223==    by 0x804A3B3: operacion_insert (memoria.c:540)

==6223==    by 0x804ACBD: conexionConsola (memoria.c:777)

==6223==    by 0x4061294: start_thread (pthread_create.c:333)

==6223==    by 0x41A30AD: clone (clone.S:114)

==6223==  Address 0x0 is not stack'd, malloc'd or (recently) free'd

==6223==

==6223==

==6223== Process terminating with default action of signal 11 (SIGSEGV)

==6223==  Access not within mapped region at address 0x0

==6223==    at 0x4030ED2: memcpy (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)

==6223==    by 0x80498C1: nueva_pagina (memoria.c:197)

==6223==    by 0x8049A82: nuevo_segmento (memoria.c:245)

==6223==    by 0x804A3B3: operacion_insert (memoria.c:540)

==6223==    by 0x804ACBD: conexionConsola (memoria.c:777)

==6223==    by 0x4061294: start_thread (pthread_create.c:333)

==6223==    by 0x41A30AD: clone (clone.S:114)

==6223==  If you believe this happened as a result of a stack

==6223==  overflow in your program's main thread (unlikely but

==6223==  possible), you can try to increase the size of the

==6223==  main thread stack using the --main-stacksize= flag.

==6223==  The main thread stack size used in this run was 8388608.

==6223==

==6223== HEAP SUMMARY:

==6223==     in use at exit: 67,836 bytes in 257 blocks

==6223==   total heap usage: 521 allocs, 264 frees, 98,455 bytes allocated

==6223==

==6223== Thread 1:

==6223== 136 bytes in 1 blocks are possibly lost in loss record 46 of 73

==6223==    at 0x402E0B8: calloc (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)

==6223==    by 0x4011726: allocate_dtv (dl-tls.c:322)

==6223==    by 0x401214B: _dl_allocate_tls (dl-tls.c:539)

==6223==    by 0x4061CC3: allocate_stack (allocatestack.c:588)

==6223==    by 0x4061CC3: pthread_create@@GLIBC_2.1 (pthread_create.c:539)

==6223==    by 0x804B195: iniciarConsola (memoria.c:906)

==6223==    by 0x804BB82: main (memoria.c:1247)

==6223==

==6223== LEAK SUMMARY:

==6223==    definitely lost: 0 bytes in 0 blocks

==6223==    indirectly lost: 0 bytes in 0 blocks

==6223==      possibly lost: 136 bytes in 1 blocks

==6223==    still reachable: 67,700 bytes in 256 blocks

==6223==         suppressed: 0 bytes in 0 blocks

==6223== Reachable blocks (those to which a pointer was found) are not shown.

==6223== To see them, rerun with: --leak-check=full --show-leak-kinds=all

==6223==

==6223== For counts of detected and suppressed errors, rerun with: -v

==6223== Use --track-origins=yes to see where uninitialised values come from

==6223== ERROR SUMMARY: 8 errors from 8 contexts (suppressed: 0 from 0)

Killed

**Comment by IvanDL95** [comment]
Reabro un momento para la duda del char* afuera del *gran malloc*.

Yo había hecho esto:

>	memoria_principal = calloc(CANTIDAD_FRAMES,TAMANIO_PAGINA);
	for(int i=0;i<CANTIDAD_FRAMES;i++){
		&nbsp; &nbsp;memoria_principal[i].value = malloc(max_tamanio_value);
	}

Lo tengo literalmente así, ya que definí como macros lo que está en mayúscula y el máximo tamaño del value del LFS lo guardo en una variable global. A la memoria lo definí como un array de frames, con la estructura de frames:

>	typedef struct{
	&nbsp; &nbsp;int key;
	&nbsp; &nbsp;time_t timestamp;
	&nbsp; &nbsp;char* value;
	}t_frame;

Con lo cual evidentemente tuve que hacer el malloc para cada char* value, ya que sino había errores de acceso a memoria ya que no estaba reservado nada para es puntero. Hasta acá el TP nos corre bien (al menos en esta parte), hace lo que debe hacer con la memoria manipulando páginas sin romper y valgrind no me tira errores de acceso a los frames.

El problema es que, por lo que postearon en la página de la cátedra y lo que dijo @iago64, *"Ese char\* lo que te dice es que estas apuntando el value afuera de tu gran malloc, con lo cual, ahí ya empezas un toque mal desde la parte teorica del TP."*

Lo que me parece evidente hasta acá es que no puedo usar un puntero dentro del frame, eso inevitablemente me llevaría a hacer un malloc por fuera del gran malloc para la memoria. No sé bien si existe un algoritmo mágico que debería buscar, inventar uno, o alguna manera de hacer un malloc grande y que aun así pueda usar un puntero (aunque sea void*) sin tener que hacer otro malloc por fuera que no me haga perder ese requisito teórico que piden.
