### ISSUE TITLE
Consulta JOURNAL

### ISSUE THREAD

**Issue by ariel-** [sisoputnfrba/foro#1394]
👋 ¡Hola!

No me terminó de quedar claro cuándo realizar el Journal en uno de los puntos.
El anexo IV especifica 4 instancias diferentes del mismo:

1. El Journal automático realizado cada X unidades de tiempo (configurado por archivo de             configuración).
2. El Journal manual por medio de la API que dispone la Memoria (JOURNAL).
3. El Journal forzoso debido a que la Memoria entró en un estado FULL y requiere nuevas                páginas para asignar (realizado por pedido del Kernel)
4. El Journal manual por medio de la API que dispone el Kernel

En la parte de memoria se especifica:
```
API SELECT
(...) En caso de no disponer de una página libre, se debe ejecutar el algoritmo de reemplazo y, en caso de no poder efectuarlo por estar la memoria full, ejecutar el Journal de la memoria. 

API INSERT
(...) Se deberá tener en cuenta que si no se disponen de páginas libres aplicar el algoritmo de reemplazo y en caso de que la memoria se encuentre full iniciar el proceso Journal. 
```

De aquí las consultas:
1. El ítem 4 y el 2 vendrían siendo lo mismo pero con un nivel de indirección. ¿Eso es correcto?
2. El ítem 3 (Journal forzoso) no me queda claro si es por el Kernel o por la memoria. Ya que en el anexo dice que es por pedido del Kernel. Y en la memoria dice que es la propia memoria la que "se dá cuenta" de estar llena y decide iniciar por su cuenta el journal (ya que no tiene lugar para la nueva página)
    1. En caso de ser hecha por el módulo KERNEL, cual sería la semántica? La memoria debería darme error de llenado, KERNEL enviar el pedido de JOURNAL y repetir el query que falló? O la memoria debería continuar con el query luego del journal? O es otra cosa?
    2. En caso de ser por el módulo MEMORIA, me queda un poco más claro y tiene un poco más de sentido. Pero se contradice con el Anexo, y es lo que no me queda claro.

**Comment by NaylaWinter** [comment]
Hola,

1) El ítem 4 y 2 son el mismo: el journal se pediría a través de la API de la Memoria. La idea era poder diferenciar aquellos request de journal que llegan desde la consola de la memoria y los que son enviados por el kernel a través del socket. Igualmente es importante recordar que el Kernel dentro de su api tiene la request "journal" la cual le envía journal a todas las memorias que tenga conectadas en el pool.
2) La memoria no autorealiza journaling, alguien se lo debe indicar (salvo el caso donde se realiza cada X cantidad de tiempo). De lo que planteas es correcto el punto i: si el kernel le envía a la memoria una request, si la misma esta full le informará al kernel y este deberá enviar el pedido de journal. La request que genero el journal debe esperar hasta que este terminé para realizarse.
De igual manera: si en vez de realizarla el kernel la request la realizamos por consola entonces la memoria deberá imprimir su estado por pantalla, para que manualmente uno pueda solicitarle que haga journal. Asimismo la request que se envió originalmente debe esperar hasta que se termine el journal y luego ejecutarse.

**Comment by ariel-** [comment]
Perfecto, se me aclaró la duda. Gracias!

Cierro

**Comment by cmedrano** [comment]
Buenas!
Tengo una duda,  nosotros lo autogeneramos el journal dentro de la memoria una vez que el mismo estaba en full, ahora me doy cuneta que esta mal.
Mi duda es cuando se realiza un Select desde kernel o desde la consola de Memoria y el mismo no se encuentre en memoria y la misma este en estado FULL.  Tiene que devolver que la memoria esta FULL y el kernel / consola de memoria hacer un Journal.

Ante un insert esta claro que si, ante un select también? 
Muchas gracias

**Comment by cmedrano** [comment]
Cuando el kernel recibe ante un request que mando a memoria que la memoria esta full este inmediatamente tiene que mandar un Journal y luego volver a envíar el request original? todo esto en un mismo quantum del request original del kernel?

Kernel -> Memoria (Request original)
Memoria -> Kernel (Respuesta Memoria FULL)
Kernel -> Memoria (Journal)
Memoria -> Kernel (Fin del Journal ok)
Kernel -> Memoria (request original)
Memoria -> Kernel (request finalizo ok)

Todo esto se hace en un solo quantum del Kernel?

Muchas gracias

**Comment by damianKreuter** [comment]
Para, COMO que Memoria DEBE AVISAR A KERNEL 1* que esta full para que Kernle le envie la request de FULL? No deberia ser automatico? 

Que si memoria esta full, realiza si o si un JOURNAL automatico

**Comment by iago64** [comment]
Buenas!
Vamos a aclarar algunas cosas:

@cmedrano efectivamente, todo eso comprendería 1 solo quantum, ya que es parte de la "Sentencia original" y eso no tendría por que afectarte a nivel performance.

@damianKreuter efectivamente, las memorias no hacen journal por si solas, ya que a ellas medio que "les importa un rabanito" estar full y si estan full, simplemente contestan, no puedo hacer un insert porque estoy full, entonces es un poco de _responsabilidad_ del kernel, decirle, ok, como estas full hace un journal.

Abrazo!

**Comment by Frilo** [comment]
Pregunto por las dudas: cuando una Memoria contesta que está full, el Kernel tiene que enviarle JOURNAL a todas o solo a la que le contestó que está full? 

Más que nada por la parte que dice

> En el caso de recibir un JOURNAL, enviará un JOURNAL a cada una de las memorias que tiene
asociadas a sus criterios.

Gracias

**Comment by cmedrano** [comment]
@Frilo  tengo entendido que solo a esa memoria, porque solo  sabes en ese momento que esa memoria esta full.

**Comment by iago64** [comment]
@Frilo es como efectivamente dice @cmedrano, solo la memoria que dijo estar full es la que recibe el JOURNAL. Pensalo como si alguien desde la consola de la memoria ejecutara JOURNAL :)

Abrazo!

**Comment by Dragonflares** [comment]
@iago64 

Ahora pero que pasa en el caso de que la memoria esté FULL y llegue un insert por su consola? Debe tirar JOURNAL? Oh debe rebotar el insert?

Muchas gracias

**Comment by NaylaWinter** [comment]
Si por consola le realizan un insert y la memoria esta full simplemente deberá indicar esto por consola al igual que como lo haria si el insert viene del Kernel.
Luego manualmente por consola se deberá indicar el comando JOURNAL.
Para ejecutar la request de insert que se habia realizado inicialmente debe esperar hasta que se haga el journal, esta request se puede almacenar por un tiempo en la memoria o volver a escribirla en consola de la misma, dependiendo la implementacion que haya hecho el grupo

**Comment by MartinOlivv** [comment]
@iago64 @NaylaWinter 

Disculpen, pero lo que ustedes estan planteando no debería de ser una condición a tener en cuenta. Al realizar una request de SELECT/INSERT tanto por consola como por el Kernel, la memoria deberá realizar un JOURNAL forzoso en caso de que se encuentre FULL. En ninguna parte del enunciado aclara que el Kernel se debe enterar que la memoria se encuentra en dicho estado, la memoria simplemente deberá realizar el journal bloqueando el resto de las request.

**Comment by NaylaWinter** [comment]
Hola,

En el enunciado indica que el Journal forzoso se lo debe indicar el kernel a la memoria, ella misma no comienza sola este proceso.

Incluso en la descripción de este issue se encuentra la parte del enunciado que indica esto.

**Comment by Dragonflares** [comment]
Buenas,

Hoy hablé con Nahuel Mazzeo y Juli Schiffer en el soporte. Y una de las cosas que dijeron es que la idea de que el kernel no se involucre en la memoria cuando está full sino que la misma memoria haga automáticamente su JOURNAL no estaba mal implementado y que era aceptable. También si se piensa es bastante más lógico.
Ahora sí, otra vez son dos ayudantes con una idea y otros dos con otra. Se puede dejar en que simplemente ambas implementaciones son correctas y nada más. Porque caso contrario debería hacerse una errata donde una de las 2 sea completamente descartada, pero para eso ya casi que se diría que es bastante tarde para aclararlo. 

Saludos

**Comment by iago64** [comment]
Viendo que este tema, está generando muchas idas y vueltas al pedo (ya que al final de cuentas lo importante es que se haga el JOURNAL), compro la alternativa de que se implemente como quieran, siempre y cuando lo hagan *y lo informen en algún lado*

Saludos.-

**Comment by iago64** [comment]
@ariel- esta resuleta la duda? damos por cerrado el tema? 👮

**Comment by ariel-** [comment]
Sisi, por mi parte pueden cerrarlo, yo ya lo había hecho pero reabrió uno de los moderadores. A lo sumo le preguntaría a @damianKreuter o @cmedrano que son los que hijackearon el issue (?

**Comment by iago64** [comment]
Genial, en ese caso se cierra el issue y cualquier otra duda la vemos en otro issue aparte, asi este no termina en otro issue eterno :)
