### ISSUE TITLE
VALGRIND "Still  reachable"

### ISSUE THREAD

**Issue by damianKreuter** [sisoputnfrba/foro#1395]
Hola gente,

la pregunta es sencilla, debo preocuparme por corregir ese tipo de error? porque no tengo forma de saber donde podría estar a diferencia de los otros

**Comment by mgarciaisaia** [comment]
Nope.

Still reachable te cuenta cuánta memoria está reservada en bloques accesibles a la hora de cerrar el programa. Para que ese número fuera cero (o cercano a cero, no estoy seguro) tendrías que hacer `free` de absolutamente toda la memoria que pida tu programa. El tema es que, nada - el sistema operativo se va a ocupar de liberar todos los recursos asignados a tu programa cuando este termine, así que ni te calentés.

**Comment by Dragonflares** [comment]
Ya que estamos, cuánto sería un aceptable de memory leaks en el tp? En porcentaje

**Comment by iago64** [comment]
@Dragonflares si te digo 0 te gusta el número?

La realidad es que los memory leaks no son aceptables, pero como no vamos a estar corriendoles el TP con valgrind (ya que queremos que si tienen un segment fault / algún mal manejo de la memoria salte rápido) no vamos a poder ver los memory leaks hasta que el tp no está un rato corriendo, con lo cual, si tenes leaks de algunos bytes porque te falto liberar algún puntero o alguna variable chica no pasa nada. Ahora si por cada vez que haces un JOURNAL te comes 10mb... te aseguro que nos vamos a dar cuenta y ahi si _Siamo Fuori_

**Comment by Dragonflares** [comment]
Claro, ponele que yo lo tengo corriendo una media hora la FS en si, y después de tener lo haciendo multiples operaciones variadas de escritura y escritura, describes, creates, y etc, valgrind me inidica que le programa allocó unos 120mb pero tiene solo un memory leak total de alrededor de 4kb unicamente.

**Comment by iago64** [comment]
4kb con htop no lo vemos ni disfrazados de pingüino, para notarlo (con suerte) tenemos que empezar a hablar de al menos 1mb (porque es la mínima unidad que corta htop).
Igual, un sano consejo, trata de no querer encontrar el camino alternativo, porque eso termina generalmente mal (léase venir la próxima fecha / el próximo cuatri), procura limpiar la mayoría de leaks que encuentre rápido y de última, venite un sábado de soporte (que te quedan varios) y te damos una mano con lo que no te des cuenta.

**Comment by damianKreuter** [comment]
Bueno, el tema de las memory leaks fue un tema que en el apartado del modulo Memoria (donde estoy trabajando) me encargué de limpiar todo. Es tedioso pero no me gusta tener memory leaks que estén asociadas a los segmentos, tabla de paginas o las paginas que al principio son solo 1k cada 2 paginas, pero luego terminan creciendo de forma exponencial y no es agradable

**Comment by iago64** [comment]
@damianKreuter Justamente, por eso es que les decía que no se confíe en un % aceptable, porque en un mínimo cambio te hace crecer los leaks hasta la estratosfera y ahí no hay con que darle.
Es tedioso, si, es super tedioso, pero es la mejor forma de asegurarse, porque es una lastima ver tps que andan impecable pero se comen la memoria más rápido que el chrome :(

**Comment by cmedrano** [comment]
Hola,
Perdón por la ignorancia pero estaba leyendo el issue y me genero dudas si mi tp esta teniendo estos problemas y  quería preguntarles como hacen para saber cuanta memoria esta consumiendo y si tengo o no memory leaks.. ? usando valgrind u otra herramienta?

Muchas gracias

**Comment by iago64** [comment]
Buenas!

Cuanta memoria per se esta consumiendo el proceso no lo sabemos a ciencia cierta, pero es fácil de ver si tienen leaks si tienen abierto htop y ves que a medida que ejecuta crece el consumo de memoria sin bajar en ningún momento es un síntoma de que tenes un memory leak (similar al uso de CPU al  máximo es síntoma de una espera activa) 

Saludos.-

**Comment by cmedrano** [comment]
Muchas gracias Damian!
por ejemplo levantando los tres procesos (Una memoria, Kernel, LFS)esperando que le lleguen solicitudes tengo este panorama

![panorama_actual](https://user-images.githubusercontent.com/1707672/59441893-a22b3c80-8dcf-11e9-9f7e-abbb912c478d.png)

CPU varía de 10.5 a 13.8% subiendo y bajando
Memoria queda fijo en  491.
Me parece que estoy consumiendo mucha memoria puede ser? el valor queda fijo ahí.

Muchas gracias

**Comment by cmedrano** [comment]
Finalizando los tres procesos(Kernel, Memoria, LFS) tengo de consumo de memoria 487MB.

**Comment by iago64** [comment]
Nooo tranqui @cmedrano fijate que estas consumiendo solo 4mb de ram... estas joya, lo importante es que a medida que uses el sistema no empiece a consumir mas y mas memoria :)

**Comment by Dragonflares** [comment]
@iago64

**Comment by Dragonflares** [comment]
@iago64 

![image](https://user-images.githubusercontent.com/28828524/59470653-bfcbc680-8e0e-11e9-9c28-829f71ab948c.png)

Estuve revisando, y cada tanto me salta esto, siempre que un pthread tira esto sons iempre 136 bytes, alguan idea de por que? Supuestamente todos los hilos terminan su ejecución antes de que cierre el FS, por ende desconozco que lo causa

**Comment by cmedrano** [comment]
Muchas gracias @iago64

**Comment by iago64** [comment]
@Dragonflares estas haciendo que los hilos sean detachables?

**Comment by Dragonflares** [comment]
@iago64 en efecto

**Comment by iago64** [comment]
Es raro ese comportamiento, proba de poner: `pthread_detach( pthread_self());`

Al inicio de la función que le pasas al thread... mucho me temo que no te esta tomando el el detach (por algo que en el aire / imagen en el foro me cuesta mucho identificar)

Saludos.-

**Comment by Dragonflares** [comment]
![image](https://user-images.githubusercontent.com/28828524/59518622-5f836600-8e9c-11e9-99d5-4974cbf130f9.png)

No se si te sirva ver la declaracion del thread en el código

**Comment by iago64** [comment]
@Dragonflares por las dudas proba lo que te pase en el mensaje anterior.

Por desgracia (o por suerte) _todavia_ no soy un compilador de C humano como para adivinar sin sentarme y probar mas a detalle.

**Comment by Dragonflares** [comment]
Lo probé, y sigue igual, a veces aparece, y a veces no. No se de que funcion depende. Porque a veces no ejecuto ninguna request y aparece, y otras no. O a veces es el hilo que maneja el inotify, o el que maneja el compactador. Y como antes, aparece a veces, No sigue ningun patron como para seguirlo más o menos

**Comment by iago64** [comment]
De momento ese leak no seria problemático si no estas generando hilos bajo demanda, por las dudas si queres lo vemos en alguno de los sábados de soporte asi te quedas tranquilo.

Saludos.-

**Comment by damianKreuter** [comment]
Bueno, cierra la issue entonces ahora que las otras dudas fueron resueltas (mas o menos pero ya daria por finalizado)
