### ISSUE TITLE
Timestamp al momento de hacer un select en Memoria

### ISSUE THREAD

**Issue by cmedrano** [sisoputnfrba/foro#1396]
Hola!
Al momento de hacer por ejemplo un select frutas 22 en memoria, y la misma no se encuentre en memoria y tenga que envíar la solicitud al lfs y luego recibir y almacenar el valor recibido, también debería el lfs mandarle el timestamp por ejemplo 777 con el cual se grabo el valor en el lfs para que en memoria se guarde el valor con el timestamp 777  verdad? o en este caso se tiene que guardar con el tiemstamp del memento con que se graba en memoria.

En el enunciado dice que se obtiene del lfs solo el valor y no el timestamp por eso me genera la duda.

Esta operación incluye los siguientes pasos:
Verifica si existe el segmento de la tabla solicitada y busca en las páginas del mismo si contiene key solicitada. Si la contiene, devuelve su valor y finaliza el proceso.
Si no la contiene, envía la solicitud a FileSystem para obtener el valor solicitado y almacenarlo

Muchas gracias

**Comment by NaylaWinter** [comment]
Buenas,

Cuando traes el registro desde LFS tenes que traerte el registro completo, incluido el timestamp que esta en el file system. Es incorrecto volver a calcularle el timestamp al momento de escribirlo en una página de memoria.

**Comment by cmedrano** [comment]
Muchas gracias Nay! cierro issue!
