### ISSUE TITLE
Journal 

### ISSUE THREAD

**Issue by fernandosierra9** [sisoputnfrba/foro#1398]
Buenas gente.
Tengo varias preguntas:

        1-Tengo una duda con respecto a esto , cuando una memoria empieza a realizar el journal ya sea por pedido del kernel o de la consola , entonces bloque TODAS las request q le llegan y hasta haber terminado no atiende ninguna request ya sea por consola y del kernel?

         2-Cuando se mando un request de insert a memoria desde kernel y este le envia un journal para q libere espacio , todo este proceso cuenta como un QUANTUM? ya que voy a mandar 3 request a memoria por un insert :
                        A-Mandar  un insert
                        B-Mandar  un journal
                        C-Volver a mandar el Insert

         3- Despues del journal  libera las estructuras, sigo teniendo en cuenta el algoritmo LRU(este se guarda nada mas q las paginas no tienen el flag de modificado) o este tambien se libero/inicializo y empiezo a guardar en la pagina 0 antes un request , hasta llenar todas las paginas
Saludos

**Comment by chamenwais** [comment]
Buenas.

Tengo una duda similar a la 1ra de las que enumera @fernandosierra9:

En la sección de la Memoria del enunciado entiendo que hay una contradicción.
En una parte indica: 

_Una memoria en este estado (Journal) no responderá **ningún pedido que implique una operación que requiera el reemplazo de uno de los segmentos actuales**._
O sea que las operaciones que no requieran reemplazo de algún segmento, tales como CREATE y DESCRIBE que sólo hacen un pasamanos de pedidos desde el Kernel al LFS, pueden ser atendidas tranquilamente.
SELECT, INSERT y DROP si tienen efecto colateral en los segmentos de la Memoria y entonces no deben ser respondidos cuando se esté haciendo Journaling.

Sin embargo más abajo dice algo distinto:
_Cuando una memoria se encuentra procesando o realizando un Journal a Disco **no se podrá operar ningún request que le llegue a la memoria**, debiendo esperar a que el primero finalice._

¿Sólo permito requests que no requieran reemplazo en segmentos de la memoria o no opero ningún request?

Gracias.

**Comment by fernandosierra9** [comment]
@chamenwais 

justamente abri este issue por esto ,  gracias  por remarcar estas partes del enunciado.

**Comment by damianKreuter** [comment]
Mmm, tenia entendido que Select podria realizar su request hasta que llegue a pedir datos aFS que ahi se bloquea hasta que termine el Journal), mas que nada porque puede seguir usando los datos de la memoria para devolverselo a Kernel.

Para mi no se deberia realizar ningun Insert, Drop o LRU sobre el bloque de memoria

**Comment by cmedrano** [comment]
Gracias por crear el issue Fernando! tengo las mismas dudas!

**Comment by cmedrano** [comment]
También las consulte por acá #1375  y #1394

**Comment by cmedrano** [comment]
El hecho de generar una cosa como esta
Kernel -> Memoria (Request original)
Memoria -> Kernel (Respuesta Memoria FULL)
Kernel -> Memoria (Journal)
Memoria -> Kernel (Fin del Journal ok)
Kernel -> Memoria (request original)
Memoria -> Kernel (request finalizo ok)

Podría generar algo recursivio, ya que al momento de realizar el kernel el request original por segunda vez puede que la memoria este devuelta FULL y otra vez tenga que repetir los mismos pasos. Esto es poco probable pero podría llegar a pasar si hay otros hilos agregando en memoria y la memoria es pequeña.

**Comment by NaylaWinter** [comment]
Buen día,

1) Si pueden implementarlo de forma que las operaciones CREATE/DESCRIBE puedan seguir ejecutándose mientras hacen journal buenísimo, si no, no pasa nada.
2) No, no serán considerados como múltiples quantums. Cada quantum corresponde a una sola línea de un archivo LQL, en este caso las tres operaciones corresponden a la misma línea y están dentro del ciclo de ejecución de la misma.
Asimismo, cuantas operaciones tengas que hacer o no al intentar ejecutar una línea va a depender mucho de la implementación de tu grupo, por ejemplo: vos podrías realizar el paso C desde el Kernel a Memoria, o que mismo la Memoria se haya encargado de almacenar la request que no pudo ejecutar.
3) Una vez que vos realizas un journal deberías limpiar todas tus estructuras administrativas: las mismas deben comenzar limpias y el algoritmo LRU empezará a funcionar como si la Memoria hubiese recién empezado, sin tener en cuenta si antes hubo una ejecución o no.

**Comment by damianKreuter** [comment]
@NaylaWinter

Y que pasa con el SELECT? Tenia entendido que puede obtener los datos de la memoria pero no puede ir a buscar a LISANDRA los datos si no existen en memoria en ese momento.

**Comment by cmedrano** [comment]
Muchas gracias @NaylaWinter 
Voy a implementar que memoria recuerde la request original para que luego del journal la vuelva a ejecutar sin llamar de nuevo al Kernel.

**Comment by NaylaWinter** [comment]
@damianKreuter con respecto a tu comentario dos puntos:
1) De dónde interpretaste eso?
2) Desde mi punto de vista que se pueda realizar un select o no durante el journaling dependerá muchísimo de como lo implemento cada uno de los grupos, por ejemplo: si se bloquean todas las estructuras administrativas y las páginas durante el journal, si van borrando de a un segmento cuando envían las keys a actualizar o eliminan todos al final, etc. Es por esto que nosotros damos como pauta que no se puedan realizar inserts, mas que nada por un tema de simplificación para ustedes.

**Comment by iago64** [comment]
@damianKreuter queda alguna duda despues de la ultima respuesta de Nay? 👮

**Comment by damianKreuter** [comment]
@iago64 hola, ya no, gracias

**Comment by iago64** [comment]
Lo damos por cerrado entonces, cualquier cosa nos avisan 😁
