### ISSUE TITLE
Consulta disponibilidad de bloques

### ISSUE THREAD

**Issue by GravesGabriel** [sisoputnfrba/foro#1400]
Hola, tenemos un par de consultas:

1. Que hacemos en el caso que llegue un CREATE al LFS y no haya bloques disponibles para asignarle a cada partición? Ya que según el enunciado cuando se crea una tabla hay que asignarle un bloque a cada particón.

2. Que pasa con los registros de la memtable cuando hacemos un dump y no hay bloques suficientes? Es un criterio válido decidir que si no hay bloques disponibles perdamos los registros cargados en la memtable? 

3. Más de lo mismo, que pasa si cuando estamos compactando nos quedamos sin bloques, esa info se pierde?

Gracias!

**Comment by Dragonflares** [comment]
Buenos días @GravesGabriel !

Para todos los puntos , te recomiendo que te pases por éste issue que hice yo hace una semana #1381 que basicamente responde tu duda. El 3 sin embargo es un caso aún más limite, se supone que la compactación terminás teniendo menos bloques ocupados que antes ya que estás sacandolas claves repetidas y admás compactando en particiones que antes por ahí tenías bloques no llenos del todo. Dependerías de que justo te caiga un dump/create en el momento de la compactación, bastante justo, pero por ahí deberías considerárselo.
Yo para el caso del create puse para que rebote la solicitud desde el inicio y avise que no hay espacio. Por si te sirve.

**Comment by GravesGabriel** [comment]
Hola @Dragonflares 

Excelente, me saca muchas dudas el issue que me pasas. Se que que la 3 es un caso super border, pero ante la duda prefiero consultarlo.

Saludos!

**Comment by iago64** [comment]
Buenas buenas!!

@Dragonflares otra buena respuesta y haciendo gala de lo que siempre decimos que a veces no esta de mas revisar issues viejos.

@GravesGabriel Efectivamente es un caso super super border, peeero, no termino de encontrar el caso donde la compactación te haria quedarte sin bloques ya que mismo en el enunciado te dice que elimines los .tmpc una vez que terminaste de calcular que registros quedan y que registros se van, con lo cual una vez que eliminaste esos archivos y eliminaste los .bin previos, no hay forma de que tengas menos bloques de los que necesitas para crear os .bin nuevos.

Abrazo!

**Comment by GravesGabriel** [comment]
Holaa @iago64 

Perfecto! Bueno, considero que mis dudas fueron respondidas así que cierro el issue.

Muchas gracias a ambos!
Abrazo!
