### ISSUE TITLE
¿malloc para char[]?

### ISSUE THREAD

**Issue by YamilaOrlando** [sisoputnfrba/foro#1401]
¡Buenas tardes! Vengo esta vez con una pregunta cortita.
Estoy trabajando con char[], ex.: **char c_auxliar[60];**. Tengo en gran parte de mi código el uso de char[] de esta manera puesto qué el char* no me era útil al momento de usar fwrite y fread (Realmente no investigué mucho el porqué pero escribiendo en archivos .tmp/.bin, las cadenas de la forma char* me las hacía imposible de traducir cuando buscaba mostrar el contenido mediante el fread.).

Ya con mi código logrado, intentaba implementar el uso de malloc en mis cadenas y demás variables, pero no logré encontrar nada respecto a usar la "funcion" malloc con cadenas del tipo char[].
 
Si alguno me puede dar un empujón con esto, sería genial, ¡Gracias!

**Comment by Dragonflares** [comment]
Buenas!

El problema de un char[] es que no es un puntero en el sentido estricto, por ende, no podés hacerle un malloc, un char, es un int, entonces es como hacerle un malloc a un int, por ende falla. Te recomiendo que si te falla usar char* con fwrite, que uses mmap en vez de fwrite, es mucho mejor, más sencillo, y además te acepta cualquier tipo de escritura que quieras hacer, además de que lo que escriba va a ser fiel a lo que quieras poner.
(Igual, me parece raro que no te deje usar un char*, acá tenés un ejemplo de escritura en cualquier caso)

![image](https://user-images.githubusercontent.com/28828524/59724407-17e43d80-9200-11e9-807f-988eaeeec2f7.png)

Otro dato, para escribir en los .tmp/.bin... te estás refiriendo en escribir los bloques con las keys? O a escribir por ejemplo, el size del .bin?

**Comment by YamilaOrlando** [comment]
¡Holis, gracias por responderme! Para darte un ejemplo de char[] sería... te muestro un cacho de código para ubicarte en qué estoy haciendo, quizá tengo algunos conceptos mal, lo cuál puede llegar a ser porque lucho bastante con entender el funcionamiento del FS:
![image](https://user-images.githubusercontent.com/22182698/59724665-0ea7a080-9201-11e9-8f71-3691440fff64.png)
Acá estoy escribiendo el metadata de la tabla qué creo, pidiéndole(scanf) al creador los datos de los tres datos. ruta2 está definido de manera char ruta2[100]; & consistencia de forma char consistencia[10];

Ahora cuando yo quiero hacer, por ejemplo, DESCRIBE tablaA, me devuelve éste resultado:
![image](https://user-images.githubusercontent.com/22182698/59724832-b2914c00-9201-11e9-968d-9c5d097d1592.png)
PERO, si "escribo" en el archivo metadata.bin cómo vos me lo ejemplificaste, no tengo forma de leerlo en el DESCRIBE, me tira puros geográficos. :/

**Comment by Dragonflares** [comment]
Claro, pasa que vos estás abriendo el archivo como un wb, osea, en binario, en cambio, yo lo abrí con w+

![image](https://user-images.githubusercontent.com/28828524/59725188-208a4300-9203-11e9-8b40-87652ac8be73.png)

Que me permite en ese caso escribir y leerlo a mano del archivo (creo que eso es, que @iago64 me corrija sino)

**Comment by iago64** [comment]
Buenas Buenas!

@YamilaOrlando los jeroglíficos que te tira cuando intenta imprimir cosas grabadas como te dijo @Dragonflares, es porque estas levantando el archivo como binario (segundo parametro del fopen le decis escritura "w" y binario "b") Si vas a usar mmap, deberias usar la primitiva open solamente, que ahi es medio independiente del formato y podrias hacer strcpy() sin problemas al cachito de memoria que te genera.

Algo interesante es que los archivos de metadata para leerlos casuaaaaaaalmente tiene el mismo formato que os archivos de config, con lo cual, no seria muy loco usar las commons para leer el archivo ;)

P.D: @Dragonflares no vas a sumar puntos en el tp contestando dudas, espero que estes ayudando a tus compañeros a terminar el tp como charlamos el sabado, porque con tantas dudas contestadas imagino que ya estan esperando las pruebas finales del TP 😊 , así que voy afilando la guadaña para evaluar tu tp el 13/07  😈

**Comment by Dragonflares** [comment]
@iago64 tranquilo, justo estoy en llamada con ellos cerrando el gossip, así que tranqui.
Recomendé lo del mmap porque pensé que ella decía de escribir el bloque, no la config de la partición, son dos cosas muy diferentes. Mmap sirve para la escritura en bloques, pero es innecesario para la escritura de los metadatas y tales.

**Comment by YamilaOrlando** [comment]
¡Gracias a ambos dos!
Ah, eso tiene sentido. Si, si, probé varias maneras de abrir archivos y la verdad que wb/rb/ab me sirvieron muchísimo y se me hicieron ágiles de manejar.
El tema qué si no puedo usar malloc estoy perdiendo bastante memoria con mis cadenas. De lo qué ambos escribieron, saco en limpio qué me conviene pasar todo a char*, ¿verdad?

PD1: ¿metadata.cfg? ¿Para las tablas es .cfg u no .bin? /Cómo te digo, ando mareadísima, jaja. ¿Osea que el metadata de las distintas tablas es un .cfg y el de la tabla general sí es un .bin?

**Comment by iago64** [comment]
Aloha!!

Si, lo mejor seria que uses char*, especialmente porque cuando haces char[], ya reservaste la memoria en stack y no en heap :)

Ahora bien, los archivos siguen siendo metadata.bin, que puedas usar la biblioteca de config de las commons no te implica renombrar los archivos, pueden ser .cfg, .conf, .lala, la extensión no es obligatoriamente .cfg para poder usar las config :)

Abrazo!

**Comment by YamilaOrlando** [comment]
¡Genios! ¡Gracias! Igual este sábado me voy a dar una pasada para llevar las dudas. ¡Cierro y esperen más Issues de mi parte por seguro! :P

**Comment by YamilaOrlando** [comment]
¡Genios! ¡Gracias! Igual este sábado me voy a dar una pasada para llevar las dudas. ¡Cierro y esperen más Issues de mi parte por seguro! :P

**Comment by YamilaOrlando** [comment]
**RE-ABRO UN SECUNDO.**

Probé de escribir con un char* en lugar de un char[] pero me tira error (-1) cuál si hubiera fallado:
![image](https://user-images.githubusercontent.com/22182698/59727280-7236cb80-920b-11e9-879a-eb23d5775d19.png)

Usé la siguiente pequeña función de prueba para escribir:
![image](https://user-images.githubusercontent.com/22182698/59727346-b0cc8600-920b-11e9-8ec4-fd8d120ef518.png)

**Comment by gastoncastineira** [comment]
Buenas

El problema lo tenés en que el puntero que le pases a fread para que almacene el contenido que está levantando del archivo necesita tener memoria alocada (léase, haberle hecho un malloc antes con el tamaño de lo que vayas a guardarle)

**Comment by YamilaOrlando** [comment]
¡Buenas! ¿Osea hacerle un malloc a la variable st?

**Comment by Dragonflares** [comment]
Una serie de puntos a comentar:

No hace falta que declares un char* c="" para hacer el malloc, cada char equivale a 1 byte, por ende hacer el malloc de 80 bytes te da un string(char*) de 80 caracteres.
Siempre que habras un archivo, a nos er que lo vayas a usar global, cerralo, es por el tema de cuantos fid tenés en curso, genera leaks de memoria a la larga.
Como dijo @gastoncastineira , hay que hacerle un malloc(2) a st para que st pueda leer 2 bytes del archivo.
No se cual es la necesidad del iString ahí, por ahí es algo que desconozco, pero para concatenar en el char* a escribir en el archivo un int (que eso es lo que seria el blocks_size), primero tendrías que pasarlo por string_itoa(), que te devuelve el valor del int escrito en un char*.
También, no se si estás escribiendo el archivo antes de tratar de leerlo, pero por ahí es porque no se si ya creaste el archivo antes.

Espero que ayude un poco.
Saludos!

**Comment by gastoncastineira** [comment]
@Dragonflares, gracias por expandir más lo que quise decir y lo que dijiste está casi perfecto. Te hago la pequeña aclaración que no es necesario que use itoa (que igual es también una opción) porque está usando sprintf, que básicamente ya hace su magia negra por atrás para convertirte todo lo que le pases a un string y guardarlo en la variable que le pases, usando el formato que usan printf y los logs de la commons con el %algo 

Se podría haber hecho también con un sprintf sobre c_aux y pasarle %s%s%s%s... etc en vez de haber hecho 4 strcat también

**Comment by rcomesan** [comment]
Hola.

No sé qué tanto vaya a ayudarte esto pero hay 2 cosas que me parecen fundamentales.

**1. Si ya hay algo implementado que resuelve tu problema, usalo.** Para este caso el módulo config de las commons cumplen su función bastante bien. Te dejo un ejemplo:

_leer cantidad de bloques:_
```
t_config* meta = config_create(metadataPath);
if (NULL != meta)
{
    key = "blocksCount";
    if (config_has_property(meta, key))
    {
        // blocksCount es uint32_t
        m_fsCtx->meta.blocksCount = (uint32_t)config_get_int_value(meta, key);
    }
    else
    {
        goto key_missing;
    }
    
    ... // leer blocksSize, 
    ... // leer magicNumber
}

config_destroy(meta);

```
_escribir cantidad de bloques:_
```
const uint32_t blocksCount = 9999;
char temp[10 + 1]; // buffer preallocado (ver punto 2 más abajo)

t_config* meta = config_create(metadataPath);
if (NULL != meta)
{
    // convierte uint32_t a su representación en ascii y la guarda en el buffer pre-allocado temp 
    // seríá convertir de un número entero 9999, a string "9999"
    cx_str_from_uint32(blocksCount, temp, sizeof(temp));

    // guarda en la config la cantidad de bloques, pero config_set_value recibe string
    // por eso necesitamos la conversión previa
    config_set_value(meta, "blocksCount", temp);

    config_save(meta);
    config_destroy(meta);
}
```
_conversión de uint32 a string_
```
#include <inttypes.h>

int32_t cx_str_from_uint32(uint32_t _value, char* _buffer, uint32_t _bufferSize)
{
    return snprintf(_buffer, _bufferSize, "%" PRIu32, _value);
}
```

Podés hacer lo mismo para metadata de tabla, de filesystem y archivos de configuración. Por más que le hayan puesto la extensión (contra-intuitiva) .bin, no son archivos binarios, más bien son un subset de INI files (sólo guardan pares key-value) y lo hacen en texto plano.


**2. Pre-allocá tus buffers y evitá memoria dinámica.**

Varias de las funciones mencionadas en este issue, incluido el ejemplo que puse arriba cx_str_from_uint32, reciben un buffer pre-allocado. Un buffer no es ni más ni menos que un conjunto de bytes o espacio de memoria reservado de forma contigua. Las formas de hacerlo en C son 2:

A) Stack:  Reserva automática. Se reserva automáticamente al entrar al scope del que forma parte, y se libera automáticamente al salir del mismo.
B) Heap:   Reserva dinámica en memoria heap. Se reserva con malloc y obligatoriamente se libera con free.

```
void main()
{
    char temp[10 + 1];         // temp es un buffer de 11 bytes.
                               // se reserva automáticamente al entrar al scope de la función main

    ... // conversión uint32 a string

                               // y se libera automáticamente al salir de la misma.
}
```

```
void main()
{
    char* temp = NULL;         // temp es un puntero a un buffer. ese buffer es NULL (apunta a 
                               // la nada misma. no hay memoria reservada aún para él)


    temp = malloc(10 + 1);     // se reserva manualmente memoria dinámica para este buffer 
                               // ahora temp apunta a un buffer de 11 bytes reservados para él.

    ... // conversión uint32 a string

    free(temp);                // se tiene que liberar manualmente la memoria previamente reservada con malloc
                               // de lo contrario se pierde la referencia a ese buffer reservado con malloc,
                               // apuntado por temp, por ende leakeas memoria (perdés la ref al salir del scope, no podes liberarla ya)
}
```


Cuál es mejor? Depende del caso. Tienen sus pro y sus contras (podés googlearlas) pero, por regla general, es preferible evitar usar memoria dinámica por todos lados. En este caso es más que obvio que la mejor idea es la opción A) reservar memoria en stack. Cómo llegamos a esta conclusión? Conocemos los límites, sabemos que un buffer de 11 bytes es suficiente en todos los casos, nunca va a cambiar eso.

Estamos leyendo un uint32, sabemos que el máximo valor será UINT32_MAX, definido en limits.h, eso sería 4294967295, son exactamente 10 caracteres + 1 el null char final de toda string en C. En el peor de los casos (máximo valor) vamos a necesitar 11 caracteres para hacer la conversión y representar un uint32 como string, podemos simplemente reservar un buffer suficientemente grande para ese caso y olvidarnos cuánto, cómo y cuándo reservar/liberar memoria.

**Comment by YamilaOrlando** [comment]
Bien, bien, Ahora creo que va funcando la cosa. Ahora me surgió otro problema que estoy segura tiene que ver con todo esto, cuando tomo la ruta por teclado, me sale este problema:
/home/utnso/git/tp-2019-1c-Los-Raquelitos/LFS_prueba/Tables
![image](https://user-images.githubusercontent.com/22182698/59954953-e7014400-945d-11e9-8bb4-43c8b00a87a7.png)

**Comment by Dragonflares** [comment]
Buenas @YamilaOrlando !

Ahí tu problema es que cuando haces el malloc de rutaP, tu ruta (por mas que la hayas hecho de ruta[60]) cuando le pases el strlen va a devolver 0! Por ende solamente tenés un malloc de 20 bytes! Entonces cuando trate de escribir se va a dar cuenta que no tiene el espacio para escribirlo y va a romper.

Espero que te sirva de ayuda

**Comment by YamilaOrlando** [comment]
¡Bárbaro! ¡Me ayudaron banda todos! ¡Gracias! 
Ahora sí cierro, ¡Gracias a todos, genios!
