### ISSUE TITLE
Lectura y escirtura de bloques de un archivo

### ISSUE THREAD

**Issue by cmedrano** [sisoputnfrba/foro#1402]
Hola, 
estoy haciendo la parte de lectura de un archivo que contiene varios bloques, la psoibilidad de tener un campo partido en dos bloques dificulta un poco el saber donde empieza un campo y donde termina otro campo cuando el campo esta partido en dos bloques.
El caso por ejemplo si tenemos dos bloques
Bloque 1 
33;7777777;Manzada\n
44;8888888;Mandarina

Bloque  2
55;9999999;Frutilla\n
77;11111111;Pera

En este caso si yo junto estos dos bloques en memoria tengo algo asi
33;7777777;Manzada\n44;8888888;Mandarina55;9999999;Frutilla\n77;11111111;Pera

Se puede ver que hay una inconsistencia en Mandarina55 en medio de ellos tiene que existir un separador que puede ser "\n" ya que cuando termina manzana termina el registro y empieza otro.
Lo tengo que concatenar asi porque en el caso que tenga el campo partido lo tengo que concatenar asi como vienen.
por ejemplo
Bloque 1
33;7777777;Manzada\n
44;8888888;Manda

Bloque  2
rina\n
55;9999999;Frutilla\n
77;11111111;Pera

Si lo concateno en este caso quedaría bien
33;7777777;Manzada\n44;8888888;Mandarina\n55;9999999;Frutilla\n77;11111111;Pera

La dificultad radica cuando el campo termina justo cuando termina el bloque porque luego cuando se junta con el otro bloque no podemos diferenciar cuando empieza y terminan los registros.

Por eso pensamos ponermos de acuerdo en lo siguiente
1)cada vez que terminen un campo tiene que ir un ";" eso por enunciado
2)Cada vez que termine un registro poner "\n" . Si el registro termina justo al final del bloque y no hay mas lugar para el caracter '\n'  entonces lo agregamos en el otro bloque el '\n'  luego continuar grabando el siguiente registro.
 Por ejemplo
Bloque 1 
33;7777777;Manzada\n
44;8888888;Mandarina

En el bloque 1 supongamos que no queda mas lugar, entonces coloco el '\n' en el siguiente bloque

Bloque  2
\n55;9999999;Frutilla\n
77;11111111;Pera\n

es la forma que se nos ocurrio de resolver esto, estaría bien?

Muchas gracias

**Comment by Dragonflares** [comment]
Buenas !

Si, justamente la separación entre una key y otra en los bloques tiene que ser un \n, o al menos eso me tiraron en un issue que no recuerdo ahora mismo. Pero si, todas las keys se separan con \n.

Saludos!

**Comment by iago64** [comment]
Aloha!!

Que se divida en bloques no significa que tengan que olvidarse de poner los \n.
Como bien dice @Dragonflares, los \n separan cada registro en los archivos.

Abrazo!

**Comment by cmedrano** [comment]
Muchísimas gracias!! Queríamos validarlo por las dudas
