### ISSUE TITLE
Consulta de timestamps

### ISSUE THREAD

**Issue by ariel-** [sisoputnfrba/foro#1403]
Buenas buenas, con mi grupo estuvimos teniendo un debate y decidimos que lo mejor sería consultarlo.

En los ejemplos de uso de INSERT (Módulo FS) se encuentra el siguiente:
`INSERT TABLA1 3 “Mi nombre es Lissandra” 1548421507`
El cual _parece estar_ en **segundos** (exactamente el 25/01/2019 a las 13:05:07 UTC según https://www.epochconverter.com/)

Pero luego en la misma página (15) hay un pie de página que aclara
> Utilizaremos Unix EPOCH para calcular el Timestamp actual (y que sea una referencia única en todo el sistema). Para ver como calcularlo y obtenerlo, recomendamos leer: https://www.systutorials.com/241697/how-to-get-the-epoch-timestamp-in-c/ Aclaración: la función que se muestra en el link devuelve el timestamp en microsegundos, no en **milisegundos**

Esta es la única mención al tema de que está en milisegundos. Luego en la página referenciada, para agregar más confusión se mencionan 2 funciones: `time` que devuelve segundos y `gettimeofday` que como mencionan devuelve microsegundos. (Y también existen `timespec_get` y `clock_gettime`, con precisión en nanosegundos)

La pregunta del millón es: los timestamp... ¿deben ser en segundos, mili, micro, nano, días transcurridos desde el último accidente, vibraciones de cuarzo, minutos para la medianoche, o todas las anteriores? 🤣

**Comment by AxelFurlanF** [comment]
Es algo que también discutimos en nuestro grupo y consideramos una falla en las explicaciones. Como bien vos decís, si estamos hablando de EPOCH estamos hablando de segundos desde 1/1/1970. Y después leímos lo de “milisegundos”, debatimos y vimos en google cómo hacer algo en milisegundos de una función que devuelve segundos y no tiene mucho sentido ya que no podrías pasar a milisegundos algo que viene en segundos multiplicándolo por 1000, ya que termina siendo igual en términos de “delta” entre eventos.
Pero bueno, esperemos a ver que dicen los ayudantes.

**Comment by rcomesan** [comment]
> termina siendo igual en términos de “delta” entre eventos.

Cierto, la parte de segundos sigue siendo igual, pero la precisión se la da tv_usec que viene en microsegundos.

Acá dejo las 2 funciones implementadas:

```
uint32_t cx_time_epoch()
{
    struct timeval now;
    gettimeofday(&now, 0);

    uint32_t time = (uint32_t)(now.tv_sec) + (uint32_t)(now.tv_usec / INT64_C(1000000)); // convert to seconds
    return time;
}

uint64_t cx_time_epoch_ms()
{
    struct timeval now;
    gettimeofday(&now, 0);

    uint64_t time = (uint64_t)(now.tv_sec * INT64_C(1000)) + (uint64_t)(now.tv_usec / INT64_C(1000)); // convert to milliseconds
    return time;
}
```

De todas formas hay que esperar a que aclaren bien el tema de la precisión. Tengo entendido que habían pedido milisegundos, por lo cual el tipo de un timestamp debería ser uint64, pero los ejemplos generalmente estan en segundos. No digo que esté mal, por supuesto un timestamp en segundos puede interpretarse como un timestamp en milisegundos (los ms son 0), sólo que estaría bueno poder confirmar si usar 8 bytes (uint64) para guardar el timestamp con precisión de ms es realmente lo pedido.

**Comment by janicead** [comment]
A mi grupo y a mi nos dijeron que lo guardemos en un dato de tipo unsigned long int asi directamente como devolvia la funcion time()

**Comment by rcomesan** [comment]
> A mi grupo y a mi nos dijeron que lo guardemos en un dato de tipo unsigned long int asi directamente como devolvia la funcion time()

@janicead claro es un uint32 (4 bytes) y precisión de segundos. Yo también (por ahora) lo tengo implementado así. El tema es que el enunciado pide milisegundos (fijate en la pág 13).

`Timestamp: Tiempo en milisegundos en el cual se insertó el registro.`

En ese caso 4 bytes se quedan cortos para representar timestamps con precisión de ms, necesitamos uint64.

**Comment by Dragonflares** [comment]
Buenas buenas!

Les re comiendo pasarase porlos issues #1334 y #1313 , que más o menos se vió todo esto justamente. Y hasta hay un ejemplo de la función (dada por los ayudantes) que nos da los timestamps a usar.

Saludos!

**Comment by iago64** [comment]
Aloha!!

En el issue #1313 esta la funcion puntualmente, traten de guiarse de ahi que de yapa es una respuesta de un ayudante y pueden citarla como defensa :)

Abrazo.

P.D: Otra respuesta acertada @Dragonflares

**Comment by ariel-** [comment]
Es decir que necesito un double o un uint64 para almacenar el timestamp.
Y respecto al ejemplo dado en el TP. Por consola de FS pueden hacer inserts con y sin timestamp, en caso de ser sin se calcularía al momento de grabar el registro. Pero en el caso de que sí tenga timestamp el query, debería interpretarlo como un epoch en **segundos** (igual al ejemplo)?

**Comment by Dragonflares** [comment]
El recibido de consola lo tomo en milisegundos... así no pierdo exactitud de datos ponele
No se si eso te sirve

**Comment by ariel-** [comment]
El problema con tomarlo como milisegundos, es que en el caso de ejemplo:
> INSERT TABLA1 3 “Mi nombre es Lissandra” 1548421507

Tomaria que el timestamp es 1548421.507 lo cual en lugar de ser el 25/01/2019 es el 18/01/1970, un par de años de diferencia xD. La pregunta iba mas por saber si el input era segundos (en cuyo caso lo multiplico por 1000 y listo) o si me dan el input en milisegundos y en ese caso no haría ningun tipo de conversión.

**Comment by Dragonflares** [comment]
Te diría que tomes el imput directamente en milisegundos, te da más exactitud. Además, recordemos que en la primer charla de tp se preguntó si iba a poder haber un timestamp (por ejemplo) 123, y si, es una posibilidad, y eso no es ni 1 segundo después del 1/1/1970(? Así que no haría falta realizar una conversión

**Comment by iago64** [comment]
Efectivamente, no se la compliquen con los timestamps por consola, asumanlos como los que les devuelven las funciones del issue #1313, lo mas probable es que si tiramos algun timestamp bien bajo sea a proposito para ver que lo pisan por consola y si no sera problema nuestro usar alguna pagina como https://www.epochconverter.com/ o similares para tener las fechas que querramos :)

Abrazo!

**Comment by Dragonflares** [comment]
Y también, si en algún momento el timestamp les empieza a care medio raro cuando usan esa función, como me pasó  ami, prueben el fix que puse en el final del #1334 

Saludos!

**Comment by ariel-** [comment]
Gracias por los aportes! Cierro la consulta
