### ISSUE TITLE
Compactacion 

### ISSUE THREAD

**Issue by cmedrano** [sisoputnfrba/foro#1404]
Hola, tenemos una duda de cual de las dos formas es mas performante hacer el proceso de compactación debido a que la cantidad de registros serán muchos la forma de implementarlo  nos preocupa mucho.
Opción uno:
Por cada archivo temporal que subimos a memoria vamos agregando sus registros a una lista de listas ordenada por las keys donde la lista principal tiene la keys y las listas segundarías son los registros con sus timestamp correspondientes. Luego de tener armada la lista de listas ir recorriendo cada sublista  comparando cada nodo de esta para saber cual tiene mas grande timestamp con la cual nos quedaremos al final.

Segunda Opción
No tener una lista de lista ya que esto nos va a ocupar muchisima memoria, si no que primero levanto el archivo a memoria y luego desde ahí voy agregando a una lista simple si la key no existe. Si la Key existe comparo cual es la que tiene mayor timestamp  y en base a eso me quedo solo con una.

Esta última opción nos parece que es mejor para nosotros, ocupa menos memoria pero sin embargo creo que tiene mas procesamiento al ir comparando varias veces antes de agregar un nuevo registro, pero también es verdad que si usamos la segunda opción vamos a tener que comparar igualmente solo que en esta opción la comparación es al final.

Nos gustaría saber si alguna de las dos es mas performante que la otra o las dos son similares y no vale la pena ponerse a pensar cual es mas performante.

Muchisimas gracias

**Comment by iago64** [comment]
Buenas buenas!!

La verdad, que es la opcion 3: no vale la pena que se quemen la cabeza buscando la opción mas performante, mas teniendo en cuenta que van a estar laburando con relativamente pocos datos (no crean que van a tener un FS con gigas y gigas de datos porque no nos da la vida para crear tantos scripts :)

Abrazo!

**Comment by cmedrano** [comment]
Muchas gracias genio!! @iago64
