### ISSUE TITLE
Cambios en los tiempos de la configuracion - MEMORIA

### ISSUE THREAD

**Issue by mesaglio** [sisoputnfrba/foro#1405]
El enunciado dice:
“Los campos de retardo deberán poder ser modificados en tiempo de ejecución, actualizando la operatoria del sistema”

Eso quiere decir que tenemos que crear comando u otra solucion para cambiar los retardos de los configs. Como por ejemplo gossiping?
Se deberian hacer desde la consola no?

**Comment by iago64** [comment]
Buenas buenas!

Justo sobre ese punto hay una llamada que dice _investigar inotify()_
La idea es que puedan manejar los cambios de archivo de configuración, y para eso inotify lo que hace es alertarlos de los cambios para que puedan recargar la config.

Cualquier duda que tengas al respecto, create un issue y lo vemos :)

Abrazo.-

**Comment by mesaglio** [comment]
Gracias.
