### ISSUE TITLE
Fallo en archivo lql - Kernel

### ISSUE THREAD

**Issue by daianaszwimer** [sisoputnfrba/foro#1406]
Buenas! 

1. Cuando se hace un SELECT a una key inexistente, cuenta como un error y se debe cortar la ejecución del script? Porque en el documento de pruebas de `animales.lql` (script que no debe fallar) se hace un SELECT sobre la key 3105 y **luego** se hace un INSERT.
2. Cuando se hace un SELECT a una tabla inexistente cómo se trata? Como un error y se corta la ejecución de script o simplemente se informa que no existe la tabla y continua la ejecución?
3. Los fallos en los scripts es cuando se corre una query que está mal sintácticamente? Por ejemplo, usar una key que no es numérica, mandar una consistencia inválida, etc.
O los fallos pueden ser por mala sintaxis y/o query sin resultado?

**Comment by NaylaWinter** [comment]
Hola,

1) No se debe tomar como fallo esos casos, simplemente se informa que no existe ningún valor para esa key
2) Cualquier operación sobre una tabla inexistente (salvo un create) debe generar un fallo
3) De los ejemplos que mencionas: los scripts deben fallar por mala sintaxis, por una key no numérica, por una consistencia invalida. En cambio, por no tener un resultado cuando se hace un SELECT no deben fallar.

**Comment by daianaszwimer** [comment]
Muchas gracias! :)
