### ISSUE TITLE
Duda con valgrind

### ISSUE THREAD

**Issue by GonzaOrtega** [sisoputnfrba/foro#1407]
Tengo una duda con el resultado de valgrind. No me salta ningun error pero me tira que hay bytes que todavia son "reachable". No se si es un error. Esta mal??

Ademas, lo raro es que no me tire memory leak si en teoria tengo memoria sin liberar...

![image](https://user-images.githubusercontent.com/38133971/59886863-36c90800-9397-11e9-8c40-0d924a53be6a.png)

**Comment by Dragonflares** [comment]
Buenas!

Te recomiendo mirar el issue #1395 , ahí se hablo abstante sobre ésto justamente. Igual te aviso, still reachable no es Memory leak (hasta hice una key con ese value) un still reachable es memoria que el SO va a liberar sola cuando el programa se cierre, así que no es leak.
Y si, si buscás a fondo, con --leak-check=full --show-leak-kinds=all vas a ver que todos salen de dentro del readline, que es lo que creo que debés estar usando.

Espero que te sirva, saludos!

**Comment by GonzaOrtega** [comment]
O sea que lo deberia dejar así??

**Comment by Dragonflares** [comment]
Si, still reachable del readline no hay manera de evitarlo, por ahí otras funciones... pero en si no es un memory leak y no debería preocuparte. Pensá que son solo 60kb que se lleva, a lo sumo 100kb, no es casi nada.

**Comment by GonzaOrtega** [comment]
Claro, claro. Gracias!!!
