### ISSUE TITLE
En el tamaño del Bloque cuentan los ";" y los "\n"

### ISSUE THREAD

**Issue by cmedrano** [sisoputnfrba/foro#1408]
Hola referido al issue #1402  queríamos saber si para calcular el tamaño del stream a grabar en un archivo bloque tenemos que tener en cuenta tambien los ";"  y los "\n". Es decir si tenemos
33;3;Manzana\n44;8;Mandarina\n
Supongamos que esto mide 50 y sin los ; y \n mide 44
Si el tamaño de mi bloque es de 44 entonces lo puedo grabar todo en el otro caso no.
Se cuentan los ";" y "\n" ?

Muchas gracias

**Comment by Dragonflares** [comment]
Buenas!

Si, cuentan en el tamaño del bloque

Saludos

**Comment by iago64** [comment]
@cmedrano Si señor, hay que contarlos, ya que al final de dia, son bytes que grabas en el bloque.

Abrazo

**Comment by cmedrano** [comment]
Muchas gracias :)
