### ISSUE TITLE
particiones LFS

### ISSUE THREAD

**Issue by matiasBusco** [sisoputnfrba/foro#1409]
Que tipo de dato adopto para las particiones del LFS, porque en un ppio levantamos como uint8_t y eso nos limita ahora a 256 particiones  xD
Son necesarias mas?
Mil gracias!
@gianotti92 @matiastomasone @alejoUTN

**Comment by Dragonflares** [comment]
Buenas!

A que te referís con que tipo de dato adoptás? Y a que llamás particiones? A los bloques del FS o a las particiones de las tablas? En ambos casos son archivos .bin, así que no entiendo a que te referis con lo del uint8_t. Me interesaría saber un poco más de la implementación antes de poder dar una respuesta que por ahí se acerque a la correcta.

Saludos

**Comment by iago64** [comment]
@matiasBusco como va?
No creo que creemos una tabla con más de 10 particiones, pero si te deja tranquilo, usa un uint16_t para identificar las particiones, total entre ints en la memoria se llevan bien*

Abrazo!

*Promoción no válida para serialización

**Comment by matiasBusco** [comment]
@Dragonflares / @iago64 es exactamente eso, tenemos un uint8_t actualmente pero no se si vamos a tener más de 255 particiones, en caso de que sí, le subo la vara!
Nomas voy a poner un chequeo de que si te pasas de 255 te tire un "che te pasaste" xq sino te entra a contar de 0 nuevamente.
