### ISSUE TITLE
Formato archivo configuracion memoria

### ISSUE THREAD

**Issue by micayeza** [sisoputnfrba/foro#1410]
Hola ! abro uno nuevo porque lo cree en el lugar equivocado, perdón!
Quisiera saber si a la hora de las pruebas, en el archivo de configuración de la memoria el 
IP_SEEDS contendra comillas en cada IP o no.
En el tp el ejemplo es:  [“192.168.1.3”,“192.168.1.4”]

o vendrá:  [192.168.1.3,192.168.1.4]
ya que tengo el siguiente issue reportado en las commons:
https://github.com/sisoputnfrba/so-commons-library/issues/113 

Gracias!!!!

**Comment by Dragonflares** [comment]
Buenas!

Te recomiendo que uses get_string_as_array, es d elas commons, te soluciona la vida. Ah, y es sin comillas. Lo de las comillas es para simbolizar que son strings nada más, para que quede claro el formato
Dejo acá un ejemplo de la llamada y de lo que tiene que leer.

![image](https://user-images.githubusercontent.com/28828524/60037019-f0212980-9686-11e9-8b9a-3f0579f1bd9e.png)
![image](https://user-images.githubusercontent.com/28828524/60037048-ff07dc00-9686-11e9-997f-a8f41d3f7443.png)

Espero que te sirva!

**Comment by micayeza** [comment]
Genial! Mil gracias!
