### ISSUE TITLE
Modificar archivo en tiempo de ejecución

### ISSUE THREAD

**Issue by GonzaOrtega** [sisoputnfrba/foro#1411]
Hola, tenia una duda acerca de como van a hacer para cambiar los datos del archivo de configuración en tiempo de ejecución?? No me refiero a la implementacion sino a como se haría, creamos un nuevo comando que se ingrese por consola, o lo van a cambiar por Vim??

Gracias

**Comment by iago64** [comment]
Buenas buenas!!

El archivo lo vamos a cambiar desde Vim / Nano (según gustos del ayudante o alumnos)

Abrazo!

**Comment by Dragonflares** [comment]
@iago64 hacer una implementación para que eso funcione desde consola sirve de todas maneras?

Saludos

**Comment by iago64** [comment]
@Dragonflares mientras puedan capturar el cambio en el archivo de config, lo que hagan de mas no esta mal :)

**Comment by GonzaOrtega** [comment]
Buenisimo, gracias!!!
