### ISSUE TITLE
Duda Memoria

### ISSUE THREAD

**Issue by afondevilarevelli** [sisoputnfrba/foro#1413]
Buenas.
Tengo una consulta sobre como se inicializaría todo el bloque de memoria contiguo donde el proceso Memoria guardaría todos sus datos. Para reservar todo el bloque hicimos un malloc con el tamaño de la memoria; el bloque de memoria es de tipo char*. ¿Pero cómo sé cuál sería el tamaño de la página? Lo pensamos así:
    tamanioPagina = sizeof(unsigned long long) + sizeof(int) + sizeof(char)*tamanioValue;
Pues dentro de cada página guardaríamos el timestamp (unsigned long long), la key (int) y el value(char* de largo tamanioValue caractéres).
Y para acceder a cada campo dentro del marco donde se encuentre una página hacemos (bytes sería lo que se encuentra dentro de la página):
   timestamp = *(unsigned long long*) bytes;
   key = *(int*) (bytes + sizeof(unsigned long long));
   memcpy(value, (bytes + sizeof(unsigned long long) + sizeof(int)), sizeof(char)*tamanioValue);

El tema es que si nos dan determinado tamanioValue, el tamaño de la página podría no quedar múltiplo de dos y no se estaría utilizando toda la memoria
int cantidadFrames = tamañoMemoria / tamanioPagina;
Por ejemplo si tamañoMemoria = 4096 y tamanioValue = 9
tamañoPagina sería entonces 21 y no se ocuparía toda la memoria.

También pensamos en que cada página guarde los siguientes datos en formato char*
"timestamp;key;value", pero en este caso cómo haríamos para calcular el tamaño de la página, ya que dependería de las cifras de timestamp y key?

Sino podríamos hacer que cada pagina guarde una estructura? por ej:
typedef struct{
unsigned long long timestamp;
int key;
char* value;
} registro;

Y que cada marco guarde dicha estructura. Ahi el tamaño de cada página sería:
tamPag = sizeof(registro) ?

**Comment by iago64** [comment]
Bueeenas!!

Si no llegan a entrar todas las paginas, no les resulta más simple, descartar ese cachito que no les alcanza a cubrir una pagina? a los ayudantes no nos jode que si les damos por ej una memoria de 10000 bytes y les quedan marcos/páginas de 30 bytes nos digan que tienen 333 marcos disponibles y les sobra un pedacito que no pueden usar y además me juego que en la teoría lo vieron con un hermoso nombre 😉 

Abrazo!
