### ISSUE TITLE
cuando se crea una tabla se le asigna un bloque a cada partición?

### ISSUE THREAD

**Issue by cmedrano** [sisoputnfrba/foro#1414]
Hola quería validar si es correcto que al momento de crear una tabla se le tiene que asignar un bloque libre a cada partición, es correcto?

Muchas gracias

**Comment by dpeccia** [comment]
Me adhiero a la pregunta, y agrego: porqué deberiamos asignar un bloque a cada partición al momento de crear la tabla si después cuando compactamos los liberamos y pedimos nuevos?

**Comment by Dragonflares** [comment]
Buenas!

Cuando hice la misma pregunta la respuesta fue que se les asignaba un bloque a cada partición porque así funcionaba la idea del FS, después de buscar un poco, encontré que se les asigna un bloque para que la tabla tenga una representación dentro del FS en sí, Sino, podés tener infinitas tablas "etéreas" que es como si no existieran. En sí asignarles los bloques a las particiones es darles presencia a las tablas dentro del propio FS.

Espero que les sirva, suerte!

**Comment by iago64** [comment]
Buenas buenas!
Perdon la demora, efectivamente es como dice @Dragonflares, tienen que asignarle 1 bloque :)
Por suerte para que todos se queden tranquilos, esta en el enunciado: 
![image](https://user-images.githubusercontent.com/1622109/60285951-180dc880-98e5-11e9-8601-5dc9a1ad3784.png)
Abrazo!

**Comment by cmedrano** [comment]
Entendido! Muchas gracias Damian! @iago64

**Comment by cmedrano** [comment]
puedo cerrar el issue @dpeccia ??

**Comment by dpeccia** [comment]
Si! Quedó claro, gracias por preguntar
