### ISSUE TITLE
Pedido tabla gossiping memorias

### ISSUE THREAD

**Issue by NicoCives** [sisoputnfrba/foro#1415]
Buenas!
Queremos corroborar si esta bien el Diseño que estamos pensando hacer en el proceso de Gossiping, mas puntualmente a resolver cuando una respectiva memoria le pide a sus memorias Seeds su tabla de gossiping.
Lo que estamos pensando es armar un hilo escucha por socket, pendientes de recibir el pedido de su tabla gossiping, de otras memorias que lo soliciten. Este hilo estará respectivamente en cada Memoria que se conecte.
Sumado a esto haremos un hilo para la ejecución del proceso gossiping de cada memoria, buscando sus memorias seeds desde el archivo de config y realizando todas las solicitudes/pedidos de las tablas a las mismas (aqui es cuando se une el hilo escucha y el hilo de ejec de gossiping)
¿Esta bien?

Tambien me quedo una duda con respecto al enunciado:
El kernel cuando hace gossiping, solo lo realiza con la primer memoria (MemoriaA) que esta configurada, o lo puede realizar con cualquiera de las memorias que estén conectadas?

Gracias!
Slds.

**Comment by iago64** [comment]
Aloha!

Esta era una linda pregunta para sus ayudantes asignados ya que ellos posiblemente tengan mas contexto, pero, no hay drama, estamos todos para ayudar 😄 

Vamos en orden, el gossiping del Kernel, definanlo como les resulte más cómodo, yo personalmente de vago que soy, primero apuntaría a la memoria inicial que conozco y si esa esta caída le preguntaria a las demás de la tabla de memorias.

Respecto al gossiping de las memorias, puede ser que se estén complicando un toque de más, pero si así les resuelve el problema y **tienen bien identificados los puntos donde tienen que sincronizar**, la solución que plantean va. 
Tengan especial cuidado con los sockets, porque entiendo que tienen 1 solo socket donde van a aceptar conexiones y se les pueden mezclar las conexiones de gossiping con las de los de exec del kernel.

Abrazo.-

**Comment by NicoCives** [comment]
Gracias Damian!!
