### ISSUE TITLE
Instalación de commons en Mac OSX

### ISSUE THREAD

**Issue by AxelFurlanF** [sisoputnfrba/foro#1416]
Hola gente,
Vengo a traer el post hippie con OSDE del día. Me estoy yendo de viaje y tengo que llevar mi Mac para laburar. Yo hago el TP en una lenovo con linux y todo funca bien pero obvio no me puedo llevar las 2.
Mi pregunta es si hay una guía o ya alguien resolvió como instaler las commons en OSX. El problema surge al instalarlas, intenta compilarlas con `gcc`y de ahí va a copiar los binarios a las librerias correspondientes.
```bash
(base) ➜  src git:(master) ✗ sudo make install
mkdir -p build/commons/collections
gcc -c -fmessage-length=0 -fPIC -MMD -MP -MF"build/commons/log.d" -MT"build/commons/log.d" -o "build/commons/log.o" "commons/log.c"
gcc -c -fmessage-length=0 -fPIC -MMD -MP -MF"build/commons/process.d" -MT"build/commons/process.d" -o "build/commons/process.o" "commons/process.c"
commons/process.c:25:9: warning: 'syscall' is deprecated: first deprecated in macOS 10.12 - syscall(2) is unsupported; please switch to a supported interface. For SYS_kdebug_trace use kdebug_signpost(). [-Wdeprecated-declarations]
        return syscall(SYS_gettid);
               ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/unistd.h:745:6: note: 'syscall' has been explicitly marked deprecated here
int      syscall(int, ...);
         ^
1 warning generated.
gcc -c -fmessage-length=0 -fPIC -MMD -MP -MF"build/commons/memory.d" -MT"build/commons/memory.d" -o "build/commons/memory.o" "commons/memory.c"
gcc -c -fmessage-length=0 -fPIC -MMD -MP -MF"build/commons/temporal.d" -MT"build/commons/temporal.d" -o "build/commons/temporal.o" "commons/temporal.c"
gcc -c -fmessage-length=0 -fPIC -MMD -MP -MF"build/commons/txt.d" -MT"build/commons/txt.d" -o "build/commons/txt.o" "commons/txt.c"
gcc -c -fmessage-length=0 -fPIC -MMD -MP -MF"build/commons/string.d" -MT"build/commons/string.d" -o "build/commons/string.o" "commons/string.c"
commons/string.c:147:41: error: function definition is not allowed here
        bool _is_last_token(char* next, int _) {
                                               ^
commons/string.c:150:40: error: use of undeclared identifier '_is_last_token'
        return _string_split(text, separator, _is_last_token);
                                              ^
commons/string.c:154:45: error: function definition is not allowed here
        bool _is_last_token(char* next, int index) {
                                                   ^
commons/string.c:157:40: error: use of undeclared identifier '_is_last_token'
        return _string_split(text, separator, _is_last_token);
                                              ^
4 errors generated.
make: *** [build/commons/string.o] Error 1
```

Dejo tambien mi versión de `gcc`.
```bash
(base) ➜  src git:(master) ✗ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Si alguien a su vez tiene recomendaciones para instalar el eclipse en mac y ande todo como en linux, serán bienvenidas.

Gracias!

**Comment by mgarciaisaia** [comment]
¡Aloha!

Bajate las VMs y llevalas ahí :)

En sisoputnfrba/so-commons-library#48 estuvimos viendo cómo hacer andar las commons nativamente en macOS, pero para el TP no tiene sentido. _En teoría_ deberías poder hacer andar todo. Pero tenés que fijar qué compilador usar (que no es el default de macOS, si no el `gcc` de GNU), y no vas a conseguir _la misma_ versión de Eclipse - porque el que usamos depende de herramientas de Linux, y en macOS no vas a tener necesariamente las mismas. Y, qué se yo - no creo que valga la pena.

Laburar en la VM puede no ser lo más cómodo del universo - y, desde macOS, _menos_ - pero me parece que te vas a comprar más quilombos que soluciones instalando las cosas nativamente.

Si insistís, arrancá por ver el issue que te mencioné para poder compilar las commons, y seguimos viendo los errores que vayas encontrando.

¡Salute!

**Comment by AxelFurlanF** [comment]
Shit jaja no quería llegar a ese punto. Voy a ver de switchear al `gcc` de GNU tal cual hice con algunos binarios de utils. Si no sale o si me encuentro pasando mucho tiempo haciendo que ande, me rindo y bajo la VM.

Gracias!

**Comment by mgarciaisaia** [comment]
Contanos cómo te fue, después :)

**Comment by AxelFurlanF** [comment]
Ok estoy teniendo errores por todos lados ya jajaja estoy desistiendo. Me baje el gcc de GNU via `brew` y cambie el symlink del de apple a este nuevo en mi `/usr/local/bin`. Al parecer las commons las instaló correctamente, pero los TADs de las mismas no son reconocidos por el eclipse ni puedo compilar los proyectos del TP por cosas relacionadas a 2 recursos teniendo el mismo nombre, lo cual no hay mucha info de eso en Google.

Vi que tienen un `Dockerfile` en el root del repo y que el mismo parte de una imagen de ubuntu. Se te ocurre una forma para mi de levantar ese container y codear de ahí o attacheandole mi tp via volumen `-v` y que el container handlee la compilación?

**Comment by AxelFurlanF** [comment]
Lo que más tengo dudas es como correr los comandos que usa eclipse con `gcc` para compilar los proyectos, ya que se me ocurre no tener el eclipse en el container sino tenerlo abierto en una terminal y tirar yo el comando para que compile. A su vez, probar ahi el ejecutable junto con `valgrind` o alguna que otra boludez más

**Comment by iago64** [comment]
Sano consejo.... no te tortures mas tratando de hacer andar las commons, la virtual va a resolver tu problema (si usas virtualbox 5.x levanta al toque y no tenes ningun problema)

**Comment by AxelFurlanF** [comment]
Buen muchachos, desistí al reino del terror de la virtualización. Tuve que resolver un tema con las guest additions que no me resizeaba a la resolución, le meti 256Mb a la VRAM y habilite las aceleraciones y anduvo todo bien a partir de ahí.
Gracias!
