### ISSUE TITLE
Bit modificado - Memoria

### ISSUE THREAD

**Issue by afondevilarevelli** [sisoputnfrba/foro#1417]
Hola, una consulta:
Me podrían dar un ejemplo de en qué momento el bit Modificado de una página podría estar en 0/false?
Porque cuando se ingresa un valor a una página, ésta se crea y se le asigna el bit M a 1/true.
Gracias.

**Comment by gastoncastineira** [comment]
Si yo te hago select desde el kernel o la memoria, y la memoria no tiene la clave que le pedí, la va ir a buscar, asignarla en donde tenga que hacerlo y va a tener el bit 0 porque no hubo modificación

**Comment by NaylaWinter** [comment]
@afondevilarevelli buenas, quedo resuelta la duda? En ese caso te pido si podes cerrar el issue y sino repreguntar hasta que quede claro
