### ISSUE TITLE
Duda con METRICS enunciado!

### ISSUE THREAD

**Issue by NicolasGuidoBarbeito** [sisoputnfrba/foro#1418]
Hola como andan? Mi consulta es la siguiente. El enunciado dice que: "las métricas deben poder ser consultadas por consola y logueadas cada 30 segundos."

Esto implica que si yo hago un METRICS en el segundo 1 (por poner un ejemplo), el sistema no debe dejar hacer otro METRICS hasta que llegue al segundo 31 (osea cada 30 segundos de forma exclusiva) . O que el sistema debe realizar un METRICS automaticamente cada 30 segundos?

Gracias! Nico :D

**Comment by Dragonflares** [comment]
Buenas!

Lo que yo siempre entiendo es que las requests por consola tienen distinto comportamiento que las globales/automáticas. Las automáticas no están llamadas a mostrarse por consola (a no ser que tus funciones de loggers estén configuradas así (lo cual no te recomiendo ya que llenas la pantalla de cosas que no necesitas)), sino que solo a que las loggees en el archivo de logger. Las que pidas por consola están para que sean printeadas, de modo que la misma no influye sobre el tiempo de espera hasta la próxima global. Es aparte

Espero que te sirva, y si estoy equivocado que me corrijan. Suerte!

**Comment by NaylaWinter** [comment]
Buenas,

El comando METRICS es independiente del logueo automático que debe realizar el Kernel. Si se realiza un logueo automático a los 0 segundos, luego mediante consola se piden las métricas a los 1 segundos entonces igualmente se logueará automáticamente nuevamente a los 30 segundos mas allá de lo que haya pasado en el medio.

**Comment by NaylaWinter** [comment]
@NicolasGuidoBarbeito buenas, esta resuelto este tema? Si es asi te pido si podes cerrar el issue, si no, volver a preguntar hasta que quede claro

**Comment by NicolasGuidoBarbeito** [comment]
Perfecto todo! Gracias
