### ISSUE TITLE
Duda con Memory Load (Metrics)

### ISSUE THREAD

**Issue by matiastomasone** [sisoputnfrba/foro#1419]
Hola! Como están? Tengo una duda sobre el enunciado.
> **Memory Load (por cada memoria):**  Cantidad de INSERT / SELECT que se ejecutaron en esa memoria respecto de las operaciones totales. 

No entiendo bien a que se refiere con "operaciones totales" y veo estas opciones:

**1)** Se refiere a todas las operaciones que va a atender Kernel?
  **a)** Todas las operaciones literal? (INSERT/SELECT/DESCRIBE/CREATE/DROP)
  **b)** Todas las operaciones acotando INSERT/SELECT ? - Esto es basándome en que el resto de las métricas sólo tienen en cuenta a los INSERTs y SELECTs.

**2)** Se refiere a todas las operaciones que va a atender ESA memoria?

Espero haber sido claro! 
Gracias y saludos!

@matiasBusco @gianotti92 @alejoUTN

**Comment by Dragonflares** [comment]
Buenas!

En si, memory load solo tiene que registrar la cantidad de inserts y selects para cada memoria. Y con eso podes calcular el resto de las métricas de esa memoria. Así que la 1b, sería tu respuesta. Solo que te recuerdo, no tenés que tener la cantidad de inserts y selects en el mismo contador, tenes que contar aparte el tiempo de insert y el tiempo de select, al igual que su cantidad. De modo que puedas sacar la readlatency y la writelatency de la memoria en sí

Saludos!

**Comment by NaylaWinter** [comment]
Buenas,

A lo que se refiere el memory load es a la cantidad de INSERTS y SELECTS que realizó una memoria en partícular en comparación con la cantidad de INSERTS y SELECTS totales que se realizaron en el kernel, es decir, entre todas las memorias.

El calculo entonces sería: INSERTS y SELECTS de una memoria / INSERTS y SELECTS de todas las memorias

**Comment by matiastomasone** [comment]
Buenisimo! Quedo claro. Muchas gracias!
