### ISSUE TITLE
¿Se debe poder hacer ADD de la memoria del archivo de conf, antes de pedirle la tabla Gossip?

### ISSUE THREAD

**Issue by chamenwais** [sisoputnfrba/foro#1420]
_El **ADD** es utilizado manualmente por el usuario en la consola del Kernel para ir asociando memorias a los distintos criterios. Luego cuando el Kernel este en el ciclo de ejecución utilizará cada criterio con las memorias que ya previamente se asignaron, no se va agregando nuevas durante la ejecución de una linea._

_Originally posted by @NaylaWinter in https://github.com/sisoputnfrba/foro/issues/1303#issuecomment-483632590_

Buenas.

Me surge una duda con frases del enunciado acerca de agregar una memoria en el Kernel, y el proceso de gossiping como la siguiente:

_El Kernel eventualmente podrá ir agregando las memorias a los distintos criterios en tanto se vaya realizando el proceso de gossip._

Entonces por más de que el Kernel se haya conectado a la memoria del archivo de conf, si no se hizo el gossiping con la misma (pedirle la tabla Gossip):
- ¿No se puede permitir hacer ADD de la memoria del archivo de conf a ningún criterio?
- ¿Debemos dar un error en el Kernel cuando se haga ADD de la memoria del archivo de conf?
- ¿Da lo mismo si la agrega a algún criterio pero todavía no le pidió la tabla?

Gracias

**Comment by NaylaWinter** [comment]
Buenas,

A lo que se refiere el enunciado es que no vas a poder agregar una memoria a un criterio cuando no tengas conocimiento de la misma, es decir, te lo planteo: qué pasa si asocio una memoria de la cual el Kernel no tiene conocimiento a algún criterio? Cómo puede luego el Kernel mandarle una request a una memoria a la cual no conoce? 

Para poder agregar una Memoria a un criterio mediante el comando ADD entonces vas a deber tener esa memoria dentro de la lista de seeds, y para tenerla en la lista de seeds, la vas a tener que haber conocido mediante el proceso de gossiping.

Con respecto a la memoria del archivo de configuración: a partir de que la misma ya este agregada dentro de la lista de seeds del Kernel es que entonces es asociable a los criterios.

**Comment by chamenwais** [comment]
Ahh, buenísimo que ya sea asociable.

Cuando hablas de lista de seeds, querés decir tabla Gossip ¿no?. 
Son dos conceptos diferentes, el kernel no tiene lista de seeds como lo tienen las memorias. A lo sumo tiene una seed que es la memoria del archivo de conf, pero puede tener varias memorias en la tabla Gossip.

**Comment by iago64** [comment]
@chamenwais efectivamente, es la lista de memorias que conoce el kernel.
Es comun que a veces le digamos tabla de seeds porque muchos grupos terminaron usando las mismas tablas que en la memoria y ni les cambiaron el nombre y nos pegaron la referencia 😄
