### ISSUE TITLE
Kernel - Consulta sobre validacion de values.

### ISSUE THREAD

**Issue by Dragonflares** [sisoputnfrba/foro#1421]
Buenas! Como les va?

Estuve viendo que el Kernel en ningun momento sabe cual es el tamaño maximo de value posible de una key. De modo que si hago un insert, No se rebotaria hasta que llegue a la memoria. Un value demasiado largo es condicion de freno de un script? O solo se rechaza el insert y sigue el script? Le debo pasar a kernel la longitud maxima de value? 

Desde ya muchas gracias

**Comment by NaylaWinter** [comment]
Buenas,

Si, un value demasiado grande es un error y debe ser una condición de freno en la ejecución de un script.
No es necesario pasarle al kernel el tamaño máximo del value, esta bien que sea rechazado en puntos posteriores

**Comment by Dragonflares** [comment]
Muchas gracias!

**Comment by GonzaOrtega** [comment]
Perdón que me meta pero que tan grande tiene que ser el value para ser rechazado??

Gracias

**Comment by Dragonflares** [comment]
> Perdón que me meta pero que tan grande tiene que ser el value para ser rechazado??
> 
> Gracias

Tiene que ser más grande que el tamanio_value que tiene el FS en el archivo de configuracion.
