### ISSUE TITLE
Debug Problem ?

### ISSUE THREAD

**Issue by YamilaOrlando** [sisoputnfrba/foro#1422]
Hola gente, estoy desesperada, me senté a codear y pude estar como una hora hasta qué todo se me fue al pasto. Llegué hasta hacer la típica de desinstalar todo e instalar devuelta;; 
Este es el problema que tengo ahorita mismo:
(El makefile)

![image](https://user-images.githubusercontent.com/22182698/60763183-4c9c2580-a045-11e9-91ff-2dcaaacf5587.png)

A ver si alguno por fin me puede dar una solución xq sino no puedo continuar, no hace built, no compila, nada de nada... no puedo avanzar para nada y no quiero arriesgar a hacer un commit con lo poco que tengo hecho.
¡Gracias desde ya!

**Comment by mgarciaisaia** [comment]
Hola Yami :)

Bajale a la desesperación. Probablemente un TP no valga la pena ponerse así, y _encima_ la deseperación no ayuda en nada - más bien, todo lo contrario. Si no estás tranquila y concentrada, va a ser re jodido conseguir buenos resultados.

La imagen que compartís no nos da mucha info para ayudarte. Bah, _casi casi_ que no nos aporta nada de info más que esto que dijiste: algo anda mal cuando intentás compilar.

Así que tratá de mirarte [este video en el que cuento cómo reportar errores que aparecen en Eclipse](https://faq.utnso.com/errores-eclipse) y contanos qué encontraste, así te podemos empezar a tirar una mano.

¡Salute!

**Comment by YamilaOrlando** [comment]
¡Gracias por contestar! Es qué venía funcionando viento en popa y de la nada clavó, y bueno, hace como cuatros horas reloj estoy googleando en todos lados. 
Bien, siguiendo el vid, o intentando, jaja, saqué este error en particular:
(Antes qué nada, por lo que creo notar, es que son tres errores conectados? Donde las commons tienen algo que ver.)
![image](https://user-images.githubusercontent.com/22182698/60763399-14e3ac80-a04a-11e9-9972-34eb8e45972b.png)

El único me da información es el último al clickearlo. 
![image](https://user-images.githubusercontent.com/22182698/60763394-01384600-a04a-11e9-9321-973d16bc8492.png)

**Comment by mgarciaisaia** [comment]
¡Ahí está!

En esas últimas líneas rojas del log dice `cannot find -lCommons`. Eso significa que estás linkeando mal las commons. Si las tenés instaladas desde el makefile que les damos, tendría que decir `-lcommons` (con minúsculas).

Por lo que dice ahí, la configuración errónea está en el LFS. Para cambiarla, andá a las propiedades del proyecto, y buscá en las Settings esas kilométricas a ver dónde están las opciones de Build de C/C++. En alguna de esas estaba la opción de Libraries, y una de las dos listas que te van a aparecer va a tener un elemento `Commons` - cambialo por `commons` y ya.

**Comment by YamilaOrlando** [comment]
¡Arceus' sake, ahí funcionó! ¡Muchísimas gracias!
