### ISSUE TITLE
Problema con Compactacion en script final de prueba

### ISSUE THREAD

**Issue by Dragonflares** [sisoputnfrba/foro#1423]
Buenas a todos!

Estuve testeando el script de prueba que mandaron por mail de 5k lineas para la memoria de SC. Y estuvo corriendo durante una media hora. Al pasar una media hora, el fs de golpe devolvió que una key no existía y eso parece haber sido porquepisó bloques de la otra tabla al compactar una... pero el error de valgrind fue éste 

![image](https://user-images.githubusercontent.com/28828524/60774704-88d79080-a0ee-11e9-9a9a-e109f0128705.png)

Alguna idea de realmente quepudo haber causado ésto? Porque si pasa a la media hora de estar en el script estando con un retardo de 0,3 en todos los procesos. Y es aleatorio el tiempo si lo reduzco más.
@nahuelm @iago64 @tferraro 

Desde ya, muchas gracias

**Comment by gabriell24** [comment]
Consulta muy fuera de foco. El lql ¿se lo enviaron a todos, o cómo lo solicitaste?
Saludos

**Comment by Dragonflares** [comment]
@gabriell24 si vas a la pagina principal de la organizacion de sisoputnfrba está en "repositories"

**Comment by nahuelm** [comment]
Hola @Dragonflares. Que script estas ejecutando? 

Por otro lado, no entendí el problema. Estas ejecutando una tabla SC y devolvió que un Key no existe?
Dicho esto, el script esta armado para que los SELECT siempre sean sobre keys previamente ingresadas pero independientemente en caso que suceda esto creo que eso no debería ser un problema y debería informarse y continuar el script.

Saludos.

**Comment by Dragonflares** [comment]
Buenas! 

Estoy usando el de compactacionlarga.lql. El problema es que hasta que no pasó que devolvió por error una key que "no existía" pese a que hubo varios inserts antes de eso que si tenían la key, todo anduvo bien. Cuando pasó eso, el proceso de compactación quebró y piso bloques que no le pertenecian, dejando las tablas inutilizadas (cosa que no me pasó nunca antes) calculo que habrá sido en la linea 3200 del script, a juzgar por el tiempo transcurrido.
Y según me dijeron el decidir que hacer con las keys que no existían era preferible cortar el script si eso fallaba, aunque es bastante hipotético.
También, otro problema es que no es que es solo esa línea, es variable en donde aparece ese error.

Saludos

**Comment by nahuelm** [comment]
Vayamos por partes. No entiendo entonces porque me hablas de una tabla SC ya que las que se encuentran dicho del scritpt son EC. Dicho esto y dado que es EC por el principio de Eventual Consistency se puede dar que una memoria intente seleccionar un dato que realizo INSERT otra y aun no haya ido a disco. Por lo tanto el caso es correcto y el Script **_NO DEBE DARSE POR FINALIZADO_**. Solo debe informarse que no existe la Key y continuar su proceso.

Por otro lado, no entiendo que tiene que ver el proceso de compactación en el INSERT y SELECT de keys ya que es independiente a estos y mucho menos porque piso bloques que no le pertenecían. Creo que ahí estas pifiando en algo en el proceso de compactación ya que como dije ambos procesos que nombras son independientes. 

Por ultimo, la demora en el tiempo de ejecución del script se debe a los Sleep/Retardos configurados. La prueba esta orientada a que los retardos sean mínimos (o 0) y que la prueba no demore mas de 1 o 2 minutos.

Saludos.

**Comment by Dragonflares** [comment]
Ok, me equivoqué yo, ando por script1.lql. Osea que según cada criterio va a variar el criterio de rechazo del script? Fair enough.
Cuál sería entonces un timpo aceptable de retardo? 0,1 segundos? 0,01? Estoy viendo si puedo recrear el error con otra ejecución, pero estoy esperando a que pase hace como 40 minutos por el retardo para que el error sea otra vez el mismo.

Perdón por el error.

También, entre un detalle un poco medio extraño, pero el API de google que te da las palabras para el lql se fue un poco de las manos 
![image](https://user-images.githubusercontent.com/28828524/60777398-9732a600-a108-11e9-9497-e72fc06560d6.png)

Update: Puede ser que haya sido un tema de sincronizacion de request vs compactación ya que no está reproduciéndose el error, pero falta verlo.

**Comment by nahuelm** [comment]
@Dragonflares vamos de nuevo por partes. El criterio es único, si no encuentra una Key informa que no se encontró pero no para el script, sino que sigue leyéndolo. Por otro lado, el script1 por un lado tiene el error que los values no están entre comillas ("). No se si puede ser ese el error pero validalo. El script lo habíamos generado y descubrimos dicho error y no fue actualizado ya que las pruebas no fueron liberadas aun (guiño guiño).

Por otro lado, si usas el script de compactacion_larga los tiempos en el archivo de configuración en un 95% van a llevar el valor cero ("0"), osea, no vas a tener que hacer sleeps.

Por ultimo, para generar los scripts estamos usando una API que nos da topics sobre una palabra y eso no implica que esa palabra sea una "Animal" pero nos es muy util a la hora de generar cosas automagicamente y a su vez poder validar que el resultado sea correcto por medio de test unitarios.

Saludos.

**Comment by Dragonflares** [comment]
Bueno, doy por cerrador el issue ya que al final se pudo arreglar el problema, era un tema de sincronización, muchas gracias!
