### ISSUE TITLE
Consulta de pruebas lql con INSERT

### ISSUE THREAD

**Issue by Renkon** [sisoputnfrba/foro#1424]
Hola! Chusmeando los repos de sisoputnfrba vi que ya se está trabajando en los scripts .lql para algunas pruebas que podremos realizar antes de la entrega final.

El tema es el siguiente, el INSERT tiene la siguiente sintaxis:
INSERT [nombre_tabla] [key] [value] ([timestamp])

Ahora, para parsear esta solicitud tenemos un separador (el espacio). Lógicamente, el value, de ser de una sola palabra no necesita llevar comillas dobles, pero de lo contrario, es necesario.

Vi esto por ejemplo en un script LQL.
![image](https://user-images.githubusercontent.com/1048587/60777320-2b503d80-a108-11e9-89b7-2c0d66126434.png)

Esto, dado la lógica que nos asignaron en el TP, es posible que termine rompiendo. 
![image](https://user-images.githubusercontent.com/1048587/60777362-68b4cb00-a108-11e9-8df0-9b880fe843da.png)

¿Cómo sabemos cuando termina el valor, y empieza el timestamp? Esto no sería posible de parsear. Es un error de las pruebas que están todavía armándose, o es un caso que tenemos que atacar en nuestra implementación?
Si es así, y lo tenemos que atacar, como podemos saber cuando un número no sería parte del dato, y si del timestamp.

Un saludo

**Comment by nahuelm** [comment]
Hola @Renkon como andas? Te comento que el script que indicas tiene el error que indicas que le faltan las comillas (") ya que aun no subimos pruebas porque no están finalizadas.

Los scripts finales van a tener las comillas para indicar el value.

Saludos.

**Comment by Renkon** [comment]
Gracias! Cerré el issue entonces
