### ISSUE TITLE
mmap de archivo Bitmap

### ISSUE THREAD

**Issue by jsarrelli** [sisoputnfrba/foro#1425]
Buenas, estamos teniendo un problema a la hora de leer el archivo bit map,
El mmap que es lo que devuelve exactamente? El contenido del archivo en forma de caracteres?

```
void leerBitmap() {
	FILE *archivo = fopen(rutas.Bitmap, "rb");

	int fd = fileno(archivo);
	if (fd == -1) {
		log_error(loggerError, "No se pudo abrir el archivo de bitmap");
	}
	int cantidadBloques = metadata.BLOCKS / 8;

	char * bitarray = mmap(NULL, cantidadBloques, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);

	bitmap = bitarray_create_with_mode(bitarray, cantidadBloques, MSB_FIRST);

	log_info(logger, "El tamanio del bitmap es de %d bits", bitarray_get_max_bit(bitmap));

	close(fd);
	fclose(archivo);
}
```

**Comment by Dragonflares** [comment]
Buenas! Como te va?

Mmap te devuelve el contenido de un archivo mapeado en el formato que está escrito en el archivo. A simple vista ya veo tu problema igual, y no lo tiene el mmap en sí, sino tu archivo de bitarray.
mmap no puede leer más bytes que el tamaño total del archivo, Entonces, si el archivo pesa 1 byte y le estas pidiendo ahí que te lea 5192 bloques (o 650 bytes), mmap va a fallar porque el archivo es más chico que lo que le estás pidiendo leer. Una solución a este problema, es truncar el archivo como acá:

![image](https://user-images.githubusercontent.com/28828524/60830146-f0441d80-a18c-11e9-983e-0ba1a709f594.png)

donde bitarrayfd es el fd que aparece cuando hago open al archivo. Justamente debés haber tomado ésto de una foto que te dió un ayudante o de stackOverflow. En ambos casos, lo que te falta es ftruncate.

Otro detalle, si metadata.blocks no es múltiplo de 8 estás desperdiciando los últimos bloques, ponele un +1.

Espero que te sirva, suerte!

**Comment by jsarrelli** [comment]
Ahi le agregamos el ftruncate, pero cuando quiero ver el contenido de bitarray me dice que no puede acceder a esa direccion de memoria.
Details:0xffffffff <error: Cannot access memory at address 0xffffffff>

Y me queda la duda, si yo modifico la variable bitarray, estaria tambien modificando el archivo? 
Si esto, fuese asi, al ir modificando el bitmap estaria a su vez modifcando el contenido del archivo mismo hasta que no haga un munmap?
`void leerBitmap() {
	int cantidadBloques = (metadata.BLOCKS / 8)+1;
	FILE *archivo = fopen(rutas.Bitmap, "wb");

	int fd = fileno(archivo);
	ftruncate(fd,cantidadBloques);
	if (fd == -1) {
		log_error(loggerError, "No se pudo abrir el archivo de bitmap");
	}


	char * bitarray = mmap(NULL, cantidadBloques, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
	bitmap = bitarray_create_with_mode(bitarray, cantidadBloques, MSB_FIRST);

	log_info(logger, "El tamanio del bitmap es de %d bits", bitarray_get_max_bit(bitmap));

	close(fd);
	fclose(archivo);
}`

**Comment by Dragonflares** [comment]
Buenas

Lo unico que se me ocurre decirte es: 
Cambia el fopen por open tal como lo usé yo, y por otro lado, usá LSB_FIRST en vez de MSB_FIRST y fijate como funciona eso
Caso contrario avisa

Saludos

**Comment by jsarrelli** [comment]
Ahi lo cambie y ahora el bitarray me aparece como vacío.

Mi pregunta ahora es, que momento se escribe este archivo mapeado? Si el contenido yo lo guardo en la variable bitarray y bitarray la asocio al bitmap. Si yo hago un bitarray_set_bit(bitmap,20), estaría de alguna manera modificando el archivo mapeado?

**Comment by Dragonflares** [comment]
De hecho no se escribe hasta que no llamás a la función msync:

![image](https://user-images.githubusercontent.com/28828524/60834972-597d5e00-a198-11e9-9a6c-0a2abe7ace94.png)

Donde bitarraycontent es el char* donde guardé el mmap y bitarrayfd el fd del archivo. MS_SYNC es solo un flag basico para que entienda la accion. hasta que no hagas esto nunca va a actualizar el archivo que escribiste.

Por otro lado, tenés que inicializar el bitmap, pensá que es probable que el bitmap no exista, entonces el bitarray lo tenés que hacer de 0 y poner todos y cana uno de los 0's y 1's de dicho bitarray, pero eso se hace recorriendo con un for que revise que los bloques a los que referencia cada punto del bitmap marquen si ese bloque está ocupado o no.

**Comment by jsarrelli** [comment]
El msync deberia estar entre el mmap y munmap?

Esta podria ser una correcta configuracion? En el caso de que el archivo este vacio, setear bitarray en 0 y hacer y msync?

El problema que tenemos es que por mas que modifiquemos el bitmap con el bitarray_set y hagamos un msync, si despues hacemos el mmap nos sigue tirando como que el archivo estuviese vacio

`void leerBitmap() {
	int cantidadBloques = (metadata.BLOCKS / 8 +1) ;

	int fd = open(rutas.Bitmap, O_RDWR | O_CREAT, S_IRUSR | S_IWUSR);
	ftruncate(fd, cantidadBloques);
	if (fd == -1) {
		log_error(loggerError, "No se pudo abrir el archivo de bitmap");
	}

	char * bitarray = mmap(NULL, cantidadBloques, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
	if(strlen(bitarray)==0){
		memset(bitarray,0,cantidadBloques);

		msync(bitarray,cantidadBloques,MS_SYNC);
	}
	bitmap = bitarray_create(bitarray, cantidadBloques);

	log_info(logger, "El tamanio del bitmap es de %d bits", bitarray_get_max_bit(bitmap));

	munmap(bitarray,cantidadBloques);
	close(fd);

}`

**Comment by Dragonflares** [comment]
Detalle, le hicieron un deprecate a bitarray_create, tenés que pasarle el mode.

Por otro lado, el msync va despues del bitarray create. Acordate que la funcion de msync es guardar los cambios que hiciste en el archivo, si guardas y después cambias, obvio que cuando quiera saber que hay en el mmap no vas a tener nada porque nunca le hiciste nada.

**Comment by gastoncastineira** [comment]
A todo lo que @Dragonflares explicó a la perfección vengo a hacer una pequeñísima aclaración que puede ahorrarnos problemas a futuro. Mmap es por sí solo bidireccional. Todo cambio que se haga en lo mapeado se baja **eventualmente** a archivo solo. msync es para forzar esa sincronización en el momento. Si queremos hilar fino, conviene hacer msync solo cuando **realmente** queramos sincronizar los cambios al archivo (ej: ctrl+c al FS) para reducir al máximo el overhead que genere la entrada/salida de esa escritura a disco
Lo aclaro solamente para evitar posibles confusiones de gente que no haya usado msync y vea que el proceso les esté andando bien.

Ahora, en cuanto al problema de @jsarrelli, capaz te convenga usar el propio bitarray para setear todo en 0 en caso de que el bitmap acabes de crearlo, en vez de estar peleandote con el memset y el msync, sin contar que memset es en bytes y los bitmaps en bits. Además, mirando el último código que pasaste, pensá que después de un truncate le estás asignando un tamaño nuevo al archivo, y con el mmap estás levantando todo el contenido de ese archivo (el cual es basura porque nunca le seteaste nada), por lo que ese strlen==0 nunca te va a devolver true, y por lo tanto nunca vas a estar seteando todo en 0 para el bitarray.

A cualquier otra duda quedo pendiente! Saludos

**Comment by jsarrelli** [comment]
Perfecta la explicación, muchas gracias!
Cierro issue
