### ISSUE TITLE
Duda con memory leak

### ISSUE THREAD

**Issue by Dragonflares** [sisoputnfrba/foro#1426]
Buenas a todos!

Vengo hoy con una duda sobre un leak bastante molesto que me causa cuando creo un struct:

![image](https://user-images.githubusercontent.com/28828524/60830407-82e4bc80-a18d-11e9-976b-c7ee8e477512.png)

Éste struct se crea en la siguiente función:

![image](https://user-images.githubusercontent.com/28828524/60830436-98f27d00-a18d-11e9-9387-d9bf078457ab.png)

Que obtiene sus parámetros de la siguiente funcion:

![image](https://user-images.githubusercontent.com/28828524/60830475-ae67a700-a18d-11e9-849c-405a2f754337.png)

Y los parámetros una vez ya copiados a otra direccion de memoria, destruyo sus punteros (los de los char**) así:

![image](https://user-images.githubusercontent.com/28828524/60830530-cb03df00-a18d-11e9-9971-a4698357f94a.png)

Y en todos los demás lugares que llego a usarlos una vez que no son útiles los libero con la siguiente función:

![image](https://user-images.githubusercontent.com/28828524/60830572-e969da80-a18d-11e9-929b-c0de91a64ca2.png)

Una vez seteado éstas premisas, paso a explicar lo que creo que pasa y a solicitar alguna mano para evitarlo:

Croe que el problema no está en que no los esté liberando sino que estoy pisando memoria previamente allocada y por eso salta un memory leak, es como tratar de hacer un string_new() a un char* y luego tirarle malloc y strcpy, lo anterior se queja porque se perdió.

Alguna idea de como arreglarlo?

Desde ya muchas gracias

**Comment by rcomesan** [comment]
El código que mostraste está más o menos OK. Muy posiblemente te estés olvidando de destruir tu t_keysetter con "liberadorDeKeys". 

Revisá tu implementación de lista porque no debe estar destruyendo correctamente el contenido de los nodos (*t_keysetter).

**Comment by Dragonflares** [comment]
Estuve revisando la lista, y si, libero la lista correctamente usando list_destroy_and_destroy_elements(keysPostParsing, (void*)&liberadorDeKeys).
Por eso no considero que sea culpa de la lista sino de que estoy pisando memoria que ya consideró preallocada con el malloc al struct.

**Comment by gastoncastineira** [comment]
El código que mostraste está bien en cuanto a la liberación. Lo único que queda que puede ser es que en algún lado en el medio de todo eso haya otro malloc y pierdas la referencia al que hacés ahí, como muy bien estás diciendo. Tendrás que revisar el código hasta encontrarlo, o no y seguir revisando alternativas. 
Perdón que no te pueda ayudar más.

**Comment by Dragonflares** [comment]
@gastoncastineira el gran problema es que esto me consume entre 1.2mb y 3mb de memory leak cuando ejecuto el script de 5k lineas. Y ahi se va de las manos la cosa, a veces varia y baja a 340kb por motivos que no logro entender, pero es el único leak que genera más de 2kb de leak y aparece múltiples veces y por eso suma tanto

**Comment by gastoncastineira** [comment]
Eso apesta a condición de carrera. Corriste helgrind?

**Comment by Dragonflares** [comment]
helgrind? Eso de ahi salió con valgrind, helgrind no lo había escuchado mencionar.

**Comment by gastoncastineira** [comment]
helgrind lo dimos en la tercer charla. Es una herramienta de valgrind para detectar condiciones de carrera.
Me hace ruido que me digas "a veces son 3MB y a veces 340KB" y quiero descartar esa posibilidad nomás

valgrind --tool=helgrind ./proceso

**Comment by Dragonflares** [comment]
Como tengo un retardo de 0,5 el script todavía esta corriendo, pero no vi ningun tema de carrera que no fuera de algun lock esperando permiso para pedirun bloque del bitarray o para realizar un select mientras esta dumpeando, pero eso se encuentra debidamente sincronziado con mutex, ningun momento salto hasta ahora un race condition sobre construir keysetter

**Comment by gastoncastineira** [comment]
Ok. No tenés condiciones de carrera pero tenés algún mambo groso con el manejo de memoria entre los distintos hilos. No te va a quedar otra que sentarte con mucha paciencia a revisar el código con valgrind como guía a ver dónde están los mallocs y los frees que causen problemas y ver cómo arreglarlos si sincronizando o moviendo de lugar no alcanza. 
Lamento no poder ser más de ayuda pero parece ser un problema bastante profundo si salta de tantas formas diferentes

**Comment by Dragonflares** [comment]
Lo único que puedo agregar, es que es posible que varíe debido a que se realizó con distintas velocidaddes de ejecución, lo que significaria que la funcion terminaria habiendo movido una mayor cantidad de datos y explicaría el aumento o la reduccion del leak en si. La otra opción sería ver de encontrar una manera distinta de iniciar el struct, pero desconozco como, a no ser que haga un memcpy de cada variable, lo cual podría ser un poco excesivo

**Comment by iago64** [comment]
Aloha!

Si estás detectando que a mayor cantidad de movimientos de bloques tenes mayor leak, yo me fijaria como estas levantando los bloques.
Lo que me suena raro es el strdup, el char* de origen del cual haces strdup, como lo estas levantando? No te olvides que valgrind te tira el punto donde detecta el error, pero no donde empieza, tendrias que hacer el camino y ver si ese char* al cual le haces strdup no te esta faltando liberarlo.

Saludos.-

**Comment by rcomesan** [comment]
> Lo que me suena raro es el strdup, el char* de origen del cual haces strdup, como lo estas levantando? No te olvides que valgrind te tira el punto donde detecta el error, pero no donde empieza, tendrias que hacer el camino y ver si ese char* al cual le haces strdup no te esta faltando liberarlo.

Se libera en la call a liberadorDeArrays(key) justo después de construirKeysetter.

Te sugeriría que revises el uso de la lista esa. Tené en cuenta que ese list_add no es thread safe, tenés que sincronizarlo mediante alguna primitiva. Si estás calleando list_add a la misma lista desde distintos threads eso te va a pisar referencias y leakear memoria.

Valgrind en este caso marca en qué linea realizaste el malloc al cual perdiste la referencia y por ende leakeaste ese bloque de memoria. 

El problema es claro, no estás haciendo free de los 2 mallocs que hacés en construirKeySetter (linea 92 y 95). Ya sea al destruir la lista cuando terminás de usarla, al sacar un elemento de la lista o directamente al pisar referencias insertando elementos de forma desincronizada.

**Comment by Dragonflares** [comment]
Bueno, en sí la lista no tiene la culpa porque es local del thread, no global, ningún otro thread tiene acceso a esa lista salvo el thread que la crea.

Estuve revisando las listas donde va y trate de poner frees entodas las que lo usaban, obvio que al final tiro "invalid free" porque si borro los elementos de una lista más grande de la cual la segunda es resultado de un filter que es la siguiente en borrar estoy generando un double free. Así seguí probando hasta llegar a que solo quedara un unico list_destroy_and_destroy_elements en la lista más grande que abarcaba esas keys. Por eso mi teoría está no en un fallo del free sino en que está pisando memoria previamente allocada. Pareciese que las asignaciones y el char* estuvieran pisando el malloc original del puntero.

**Comment by mgarciaisaia** [comment]
Del mensaje de error original nunca me quedó en claro si se queja únicamente de los dos últimos bloques, o si pasa para los 56.

Subite un log completo, a ver qué más está pasando y no estamos viendo.

**Comment by Dragonflares** [comment]
@rcomesan me saco el sombrero, tenías razon pero la culpa no la tenía una list... sino que un elemento en particular que era el retorno del SelectKeyFs
Y así es como un único free mal puesto generó más de 3mb de pérdida.

Muchas gracias por las respuestas y la ayuda!
