### ISSUE TITLE
Duda con enunciado METRICS!

### ISSUE THREAD

**Issue by NicolasGuidoBarbeito** [sisoputnfrba/foro#1427]
Buenas! Les hago una consulta sobre el enunciado acerca del METRICS. Estamos en el dilema, de que al decir que: "se debe mantener una estadística interna de cada criterio" pensé dos opciones para desarrollar y no se cual es la correcta o si hay algún otro camino por el cual llegar al resultado esperado.
Opción 1: Que cada una de las métricas calculadas (read latency, write latency, reads, writes, memory leads) dependan de los diferentes criterios, es decir: Pedimos por consola METRICS y esto devuelve:
Read latency -> "Un número" por "Criterio: Strong Consistency"
                      ->"Un número" por "Criterio: Strong-Hash Consistency"
                      ->"Un número" por "Criterio: Eventual Consistency"

Y asi sucesivamente con cada una de las métricas o:

Opción 2: Cada una de las métricas calculadas (read latency, write latency, reads, writes) excepto memory load (que diferencia por memoria), no diferencian por criterio y para calcularse; toman en consideración todas las memorias sin importar su consistencia. Pedimos por consola METRICS y esto devuelve:

Read Latency -> "Un número" considerando todos los SELECT ejecutados en todas las memorias sin importar su criterio. Y asi sucesivamente con cada una de las métricas.

Memory Load -> "Memory 1" -> "Un número" por "Criterio: Strong Consistency"
                                                 -> "Un número" por "Criterio: Strong-Hash Consistency"
                                                 -> "Un número" por "Criterio: Eventual Consistency"
                        -> "Memory 2" -> "Un número" por "Criterio: Strong Consistency"
                                                 -> "Un número" por "Criterio: Strong-Hash Consistency"
                                                 -> "Un número" por "Criterio: Eventual Consistency"

Muchas Gracias!!

**Comment by iago64** [comment]
Buenas buenas!!

La idea de las métricas es que sean generales para todas las memorias (salvo la de Memory Load)

Saludos.-

**Comment by iago64** [comment]
@NicolasGuidoBarbeito Quedo resuelta la duda? 👮

**Comment by ariel-** [comment]
> La idea de las métricas es que sean generales para todas las memorias (salvo la de Memory Load)

No entendí esto. Mi comprensión del enunciado es la siguiente (en pseudo codigo)
```
foreach c in criterios
{
  reportarReadLatencyPromedio(c)
  reportarWriteLatencyPromedio(c)
  reportarCantidadSelect(c)
  reportarCantidadInsert(c)
  foreach m in criterio.memorias
  {
    print(m / (c.cantidadInsert+c.cantidadSelect))
  }
}
```

Es así?

**Comment by rcomesan** [comment]
Me sumo a la pregunta de ariel. El enunciado pide una "estadística interna de cada criterio". Según mi interpretación debería haber 3 "sets de estadísticas" uno para cada criterio y cada set debería incluir: 

- read latency (totalTimeElapsedOnReads / totalReads)
- write latency (totalTimeElapsedOnWrites / totalWrites)
- reads (totalReads)
- writes (totalWrites)
- memory load (uno por memoria asignada al criterio
   (totalReadsMem[i] + totalWritesMem[i]) / (totalReads + totalWrites)

Serían tan amables de confirmar @NaylaWinter @iago64. Gracias.

**Comment by NaylaWinter** [comment]
Buenas,

Es correcto lo que plantean en cuanto a read latency, write latency, reads y writes.

El único punto que levanto es el siguiente: la métrica de memory load es cross criterio porque es en función de la cantidad de request que hizo esa memoria sobre la cantidad de request totales que hizo el Kernel, mas allá del criterio que lo haya ejecutado.

Si plantean algo como foreach m in c.memorias puede ser que vayan a hacer print dos veces de las mismas métricas, debido a que una misma memoria esta asociada a dos criterios distintos. Esto no es un problema, solo les comento que sino podrían directamente imprimir por pantalla una vez el memory load por cada Memoria, mas allá de hacerlo dentro del "set de estadísticas" de un criterio en particular.

**Comment by ariel-** [comment]
Esto lo tenemos en cuenta, por lo menos en nuestro caso, cada memoria asociada mantiene estadísticas de operaciones atendidas del criterio al cual está asociada. Por lo que no habría problema en contarlos dos veces, ya que son independientes.

Gracias por la respuesta, ahora quedó más claro. No tenía mucho sentido por ejemplo para SC, ya que el uso de su única memoria sería 100% siempre.
