### ISSUE TITLE
Duda con Retardo

### ISSUE THREAD

**Issue by cmedrano** [sisoputnfrba/foro#1428]
Hola, 
tenemos una duda con la parte de retardo.
En LFS dice "Valor del Retardo de cada operación realizada."
Esto significa que por cada INSERT,SELECT,ETC todos los comando ya sea que vengan por consola o por Memoria van a tener un retarde de lo que se tiene por archivo de configuración?

En Memoria dice "Retardo de acceso a Memoria Principal" Esto similar cada operación que requiera acceso a la memoria principal como SELECT , INSERT etc tendra un retardo ya sea por consola o vía Kernel?

En Kernel lo mismo cada vez que se ejecute un comando por consola o por arcchivo scrip tendra un retardo?

Muchas gracias

**Comment by iago64** [comment]
Si señor!, la idea del retardo es poder hacer que las cosas pasen a un ritmo que lo podamos seguir en la evaluación, con lo cual cuando les decimos _en cada operación_  significa a que en cada cosa que se haga (SELECT, INSERT, ETC) tienen que agregar ese sleep() :)

Abrazo!

**Comment by cmedrano** [comment]
Muchas gracias Damian, @iago64 

Aprovecho para preguntar los scripts para la entrega fina que se encuentran en el repo ya estan listos para utilizarlos? o lo estan armando? si es así, habrá un documento como la anterior entrega de hace unas semanas atrás explicando como serán los pasos para los test en los tres procesos? 
Muchas gracias

**Comment by iago64** [comment]
Están en progreso, banca un par de horitas y ya sale el doc de pruebas y el listado de scripts ;)

Abrazo!

**Comment by cmedrano** [comment]
Muchas gracias Dami! @iago64
