### ISSUE TITLE
Duda Metricas

### ISSUE THREAD

**Issue by cmedrano** [sisoputnfrba/foro#1429]
Hola,
teniendo en cuenta lo que se hablo en el #1418 entiendo que el comando metrics por consola es independiente del que se ejecuta automáticamente.

Mi duda es la siguiente si en un momento se ejecuta METRICS  por consola entonces tengo que esperar 30 segundos para que en esos 30 segundos cuente las cantidades de select e insert que se hicieron para calcular las metricas?

Por ejemplo
Si en el intrante de 0 a 30 segundos se ejecutaron 
en t=10s se ejecuto 1 Select que duro  10ms
en t=11s se ejecuto 1 select que duro 14ms
en t=12s se ejecuto 1 insert que duro 5ms
en t=13s se ejecuto 1 insert que duro 7ms

Si alguien ejecuta el comando METRICS en t=11,5s entonces hasta ese momento tengo ejecutado 2 selects solamente entonces mis preguntas son

1), calculo mis metricas en base a eso para mostrar por consola o espero hasta t=41,5 segundos para mostrar por consola?

2)En t=30 voy a logear lo siguiente 
Read Latency= 12ms porque (24/2 = 12)
Write Latency = 6ms (porque 12/2=6)
Reads = 2
Writes = 2
Esto es correcto? 

3) La metrica Memory Load (por cada memoria): Entiendo que esta metrica no habla de los ultimos 30 segundos si no que se va ir logeando o mostrando por consola el valor obtenido teniendo en cuenta desde que inicio el kernel. Correcto?

Muchas gracias

**Comment by NaylaWinter** [comment]
Hola,

1) Calculas tus métricas en base a lo que estuviste ejecutando hasta ese instante y las imprimís en ese momento, no tenes que esperar hasta t=41,5s

2) Si, es correcto

3) También se tiene en cuenta los últimos 30 segundos: son las operaciones que resolvió esa memoria sobre las operaciones totales del Kernel en los últimos 30s.

**Comment by cmedrano** [comment]
Perfecto! Muchísimas gracias!
