### ISSUE TITLE
Duda pruebas

### ISSUE THREAD

**Issue by daianaszwimer** [sisoputnfrba/foro#1431]
Buenas!
En algunos scripts lql luego de los CREATE no se hace DESCRIBE, por lo tanto los requests sobre las tablas creadas no se podrán ejecutar ya que el kernel no tiene la metadata correspondiente a la tabla creada

Saludos!

**Comment by daianaszwimer** [comment]
Otra cosa, en las pruebas de kernel dice:
Antes de que finalicen los scripts anteriores, modificar el grado de multiprocesamiento a 4
El multiprocesamiento no es un valor que puede ser modificado durante la ejecución (según el enunciado)

**Comment by Renkon** [comment]
Te respondo en base a lo primero, yo supongo que cuando haces el create/drop, si sabés que se hicieron de forma exitosa, podés modificar la lista con tu metadata, y dar de alta una nueva entrada/borrar según si fue create o drop, creo.

Y adhiero a la segunda pregunta, según lo solicitado en el enunciado, no se requiere cambiar el nivel de multiprocesamiento.

**Comment by Dragonflares** [comment]
> Buenas!
> En algunos scripts lql luego de los CREATE no se hace DESCRIBE, por lo tanto los requests sobre las tablas creadas no se podrán ejecutar ya que el kernel no tiene la metadata correspondiente a la tabla creada
> 
> Saludos!

Buenas!

Respecto a ésto, te recuerdo dos cosas:

1) Se supone que tenés cada cierto tiempo que tirar un describe global que actualice la metadata de tablas 
2) Cuando una tabla se crea, vos agregás la tabla a la tabla de metadata una vez que te llega la confirmación o de que la tabla se creó o que la tabla ya existía.

Espero que te sirva

**Comment by nahuelm** [comment]
Buenas!! Veo que el primer tema esta resuelto y es como dicen sus compañeros, al crear una tabla satisfactoriamente, la misma se agrega a la metadata.

Por otro lado, el segundo punto tienen razon y es algo que no tuvimos en cuenta al hacer las pruebas. Vamos a analizar el tema y en el transcurso del dia vamos a avisar lo resuelto.

Saludos. Nahuel

**Comment by daianaszwimer** [comment]
@nahuelm ahh okey, entonces si el create o drop fue success se agrega o borra en la metadata?

**Comment by daianaszwimer** [comment]
@nahuelm igualmente en esta rta https://github.com/sisoputnfrba/foro/issues/1391#issuecomment-500065360 se da a entender que antes se tiene que hacer DESCRIBE luego de un CREATE, cuál de las dos implementaciones es la correcta?

**Comment by cmedrano** [comment]
Hola, nosotros también tenemos  entendido que para que el kernel tengo la metadata de la tabla recién creada tiene que realizarse un describe forzadamente ejecutando un describe o automáticamente pero tiene que realizarse el describe luego del create. Esto lo validamos para la primera entrega presencial en el issue #1391

**Comment by nahuelm** [comment]
Hola @cmedrano como andas? Si se les complica agregar dicha funcionalidad al create, modifiquen los scripts agregando el describe. Lo tendremos en cuenta para las metricas en la evaluacion

**Comment by cmedrano** [comment]
Hola @nahuelm ! Todo bien, vos? lo agregamos, no hay problema! 
Lo que tendría que hacer entonces luego de hacer un create desde el kernel sería guardar la metadata de dicha tabla en el kernel si dicha tabla fue creada exitosamente, correcto?

Si se crea la tabla desde Memoria o LFS se debe mandar la metadata a kernel también? o solo para el caso que se crea desde el kernel?

Mil gracias!

**Comment by nahuelm** [comment]
Hola @cmedrano. No, solo si la operación se ejecuta desde el Kernel.

Saludos.

**Comment by ariel-** [comment]
Buenas!

> Por otro lado, el segundo punto tienen razon y es algo que no tuvimos en cuenta al hacer las pruebas. Vamos a analizar el tema y en el transcurso del dia vamos a avisar lo resuelto.

Hay novedades de ésto? Me surgio exactamente la misma duda al leer las pruebas. El campo que es recargable es QUANTUM. Para modificar el Multiprocesamiento no se puede hacer con el kernel corriendo. Habria que esperar que terminen los script, cerrar el kernel. Modificar el campo y luego ejecutar y re-asociar memorias.
