### ISSUE TITLE
Consulta Kernel CREATE/DESCRIBE/DROP - asignación de memoria

### ISSUE THREAD

**Issue by Renkon** [sisoputnfrba/foro#1432]
Hola, tengo una consulta acerca de que memoria elegir para el create/describe y drop en el **kernel**.

Como sabemos, en base a la tabla que selecciono/inserto defino la memoria (por el criterio).
En el caso del journal, elijo a todas las memorias que estén asignadas a un criterio.

Pero, en el caso del create/describe y drop, puedo elegir cualquiera? (estén o no asociadas a un criterio?). Porque no lo vi especificado en el enunciado

Gracias

**Comment by Andy-chavez** [comment]
Buenas! 
Te comento que me respondieron cuando pregunte en soporte por el describe. Si es un describe [table] deberías de mandarlo a la memoria que corresponde con el criterio de la tabla, pero en caso de un describe sin tabla específica, debería de mandarse a la memoria principal, es decir la que esta en el archivo de configuración. Eso me dijeron a mí, espero te sirva!

**Comment by Renkon** [comment]
Hola, muchas gracias por la respuesta. Me hace un poco de ruido que el describe a una tabla individual también haya que hacerlo a una memoria según el criterio (debido a que todas conocen todas las tablas creadas/droppeadas).

De todas formas, entonces, que pasaría con el create/drop

**Comment by Dragonflares** [comment]
Buenas, te respondo lo que me dijeron a mi:

 Describe, Create y Drop pasan como dijo @Andy-chavez , van a la memoria correspondiente al criterio ( en caso de que el describe sea particular, y si es global a la de config(SC de origen)). Ahora, si no hay ninguna memoria del asignada al criterio para enviarle la request, se envía a la primer memoria(memoria de configuración.

Esprero que sirva, saludos

**Comment by Renkon** [comment]
Yo hablé con otro ayudante y me comentó que para CREATE/DESCRIBE/DROP es indistinto.. es importante más que nada en SELECT e INSERT.

**Comment by cmedrano** [comment]
Para el Describe global podes envíarlo a cualquier memoria, no solo a la del config porque esta puede estar dada de baja. Es lo que me dijeron.

**Comment by iago64** [comment]
Efectivamente como dice @Renkon CREATE, DESCRIBE y DROP pueden ir a cualquier memoria, idealmente si pueden apuntar a las memorias con el criterio correcto seria un golazo, pero no se quemen la cabeza, al final lo que importa es que creen, eliminen o conozcan la data de las memorias en cuestion ;)

**Comment by Renkon** [comment]
Solucionado entonces, lo cierro
