### ISSUE TITLE
Memoria -> ¿Qué pasa si memoria asignada a operación se cae?

### ISSUE THREAD

**Issue by Renkon** [sisoputnfrba/foro#1433]
Buenas, quería consultarles,

Como kernel, yo me puedo dar cuenta si una memoria está caida, mediante el gossiping (cuando recibo nueva información de las memorias), o cuando hago una petición y me doy cuenta que se cayó. 
En el caso de que una memoria se caiga durante esta petición, que hago con la operación que estaba ejecutando?

Para el SC -> obviamente NO la voy a poder hacer porque no tengo memoria asignada al criterio.
Para el SHC y para el EC, que hago? En el EC uso la siguiente memoria disponible EC? Y para SHC, fuerzo journaling y repito la operación?

Un saludo

**Comment by NaylaWinter** [comment]
Buenas,

En el caso de que se caiga una Memoria mientras se esta realizando una request simplemente informá por consola del Kernel que esa operación no se pudo realizar correctamente por una falla y seguí con la siguiente en el script (o si es la última finalizá el script)

**Comment by Renkon** [comment]
No se supone que si falla el script por un problema crítico hay que finalizar la ejecución? 

Me baso en el enunciado:

"Los scripts pasarán a estado “Exit” una vez que fueron ejecutadas todas sus request o *que haya fallado la ejecución en una de ellas, sin ejecutar las posteriores en caso de haberlas*. Es decir: Si consideramos un script de 10 request donde la request 3 falla el mismo entrará en estado “Exit” sin ejecutar las 7 líneas restantes."

**Comment by NaylaWinter** [comment]
Buenas,

El enunciado no esta tan enfocado en errores que se puedan dar entre los componentes, como puede ser que la Memoria se caiga, sino en errores propios de la ejecución de esa request, como pueden ser: error de sintaxis, la tabla donde se quiere insertar un registro no existe, el value supera el tamaño máximo permitido, se quiere hacer un select sobre una tabla a la que se le hizo drop previamente.

**Comment by janicead** [comment]
Hola! Me sumo a la consulta, como puedo hacer para que el kernel se entere que una memoria se cayo, sin hacer una requests? O con que el kernel se entere recien queriendo hacer una request es suficiente? Porque de la forma en la que lo tenemos hecho el gossip no hemos encontrado forma de que el Kernel se pueda llegar a enterar en el momento en que se cayo una memoria, y no recuerdo donde leimos que puede ser que bajen memorias en el medio de la ejecucion, con lo cual no sabriamos como enfrentarnos a esto. Desde ya, muchas gracias!
Janice

**Comment by iago64** [comment]
@janicead No hace falta que te enteres que se cayo una memoria justo en el momento que se cae, si vos te enteras al momento de pedirle algo, esta bien igual :)

**Comment by janicead** [comment]
Gracias! Ya lo resolvimos de esa forma 👍🏼

**Comment by tferraro** [comment]
@Renkon Vos como venis con este tema? Se resolvió? Si es así, se puede cerrar el issue?

**Comment by Renkon** [comment]
Ya está resuelto. Gracias!
