### ISSUE TITLE
Duda con memory load (metrics)

### ISSUE THREAD

**Issue by Renkon** [sisoputnfrba/foro#1434]
Buenas! Una consulta.

El memory load se basa en las operaciones de los últimos 30 segundos? O se basa en el histórico? Es decir, en el total de operaciones desde el inicio?

Muchas gracias

**Comment by cmedrano** [comment]
La respuesta esta aca #1429 
Tenes que tener en cuenta los últimos 30 segundos!

**Comment by cmedrano** [comment]
Me queda la duda si tengo que sumar los inserts y selects juntos  o los tengo que tomar por separado para cada memoria?

Otra duda es si el retardo que se agrega a los insert y select tiene que estar por afuera de las metricas? o las tengo que contar tambien el tiempo de retardo al tiempo en que tarda un select o un insert?

Muchas gracias

**Comment by Renkon** [comment]
Un ayudante a mi me dijo que es el total... entonces cual es la real respuesta? 🤔

**Comment by Renkon** [comment]
El retardo casi fija que se toma en cuenta btw, y se suman insert y selects juntos, o al menos eso hacemos porque es lo que dice el enunciado.

**Comment by iago64** [comment]
@Renkon es el total de las operaciones de los últimos 30 segundos :)
@cmedrano si si, tomen en cuenta el retardo, al final de cuenta el retardo simula las diferentes velocidades que se ven en la teoría (aunque a tiempo humano sean todos imperceptibles)
