### ISSUE TITLE
Commits ?

### ISSUE THREAD

**Issue by YamilaOrlando** [sisoputnfrba/foro#1435]
¡Buenas! Hola Gente, vengo con otra consulta. Ayer mis compas me avisaron estaba commiteando "mal", entré al repo y me encuentro con esto:

![Captura](https://user-images.githubusercontent.com/22182698/60997051-413e4800-a32c-11e9-9ead-6d4b24d47ba4.JPG)

Mi nombre está pero no linkea a mi perfil. Hoy me senté a configurar todo de vuelta y hice un commit minimo y arrancó: 

![Captura2](https://user-images.githubusercontent.com/22182698/60997133-7e0a3f00-a32c-11e9-9a06-29e166d55845.JPG)

Ahora con eso solucionado a un lado, mi problema es qué los cuatro commits hice con el otro nombre eran cosas heavies, grandes, tengo miedo de que para el Coloquio me digan algo xq está commiteado por esa "cuenta fantasma", ¿Alguna sugerencia? ¡Gracias desde ya! 

P.D.: Cuando commiteé esas cuatro veces, hasta me pedía la contraseña del Git y todo. :/

**Comment by tferraro** [comment]
No te preocupes y denle bola a que el tp sea robusto 🙂 

(Posta, ni te calientes, no le damos mucha bola a "cantidad de commits" linkeados a una cuenta)

**Comment by YamilaOrlando** [comment]
¡Muchas Gracias! Estaba preocupada por eso por algunos comentarios me habían tirado antes de cursar.
