### ISSUE TITLE
Comando Metrics - No es Panificable

### ISSUE THREAD

**Issue by cmedrano** [sisoputnfrba/foro#1436]
Cuando se ejecuta el comando Metrics desde la consola este no debe ser panificable, es decir como no requiere la intervención de una memoria no ingresa a la cola de listos, este comando no se planifica y se ejecuta directamente por el kernel. Correcto?

Mil gracias!

**Comment by iago64** [comment]
Tal cual, no hace falta que lo planifiquen, simplemente en ese momento buscan los datos, calculan las métricas y las muestran por pantalla y en un log.

Abrazo!

**Comment by cmedrano** [comment]
Muchas gracias @iago64
