### ISSUE TITLE
Consulta Gossiping

### ISSUE THREAD

**Issue by micayeza** [sisoputnfrba/foro#1437]
Hola! Tengo una consulta sobre el gossiping.
La memoria siempre va a conectarse con las memorias que posea en su seed? o una vez que conozca a una nueva, se conecta a ella para conocer su tabla de gossiping?

Por ejemplo, la memoria A contiene en su seed a la Memoria B, y ella contiene a la Memoria C.
Cuando A realiza el gossiping B le informa que existe C, entonces en la tabla de gossiping de A estarán B y C. Cuando A vuelva a realizar el Gossiping, le preguntará su tabla de Gossiping solo a B? o tambien a la memoria C?

Muchas Gracias!

**Comment by iago64** [comment]
Es un poco indistinto si hacen gossiping con todas o solo con las originales, eventualmente a la larga o a la corta, van a terminar conociendo todas las memorias, yo personalmente para no complicarme mucho, recorrería mi lista de memorias conocidas y les pediría la tabla de gossip y listo, un if menos, un punto menos donde puede reventar el tp.

**Comment by Dragonflares** [comment]
Segun lo que vi en el anexo de gossip del tp nunca se ve que la memoria A se conecte con la C para hacer gossip, así que por enunciado sería solo con las seeds. Además, permformance-wise es mucho mejor que sea solo con las seeds, ya que sino tendría que procesar las tablas de gossip de todas las demás memorias. Si, sería más rapido para obtener la desconexión de alguna, pero pensá que son intercambios de tablas, pasas en un esquema de 8 memorias donde una tiene 2 seeds a tener 2 intercambios por gossip a 8, además de que eventualmente esas 8 también se le van a conectar (en lo que asumo que vas a tener o un multihilo o un select). 
Es menos choclo ir solo a las seeds.
Y el enunciado medio lo respalda.

**Comment by micayeza** [comment]
Hola! Gracias por sus respuestas!
Tenia la misma duda respecto a la desconexión, la única forma que tengo de saber si una memoria se desconecto es, al momento de hacer un nuevo gossiping, limpiar mi tabla de gossiping verdad? porque aunque en la segunda vuelta B no me envíe en su tabla de Gossiping a C, yo la seguiría teniendo en mi tabla. Y el hecho de que B no la traiga no es motivo para sacarla, ya que quizas hay otra memoria que pudo haberme pasado a C.
Me explico? 
Bueno, voy a ver como sale jajaja espero su respuesta y cierro el issue, muchas gracias!

**Comment by iago64** [comment]
@Dragonflares performance meh, no va a cambiar tan notablemente en ese aspecto, porque si bien perdes mas tiempo haciendo gossiping, vas a tener mas rapido el mapa completo, son estrategias, pero a la larga o a la corta da igual para el tp.
Y de nuevo, puede que te sea menos laburo hacerlo en *tu implementación* pero no te olvides que por suerte _no todos piensan las soluciones de la misma forma_ 😉 

@micayeza Efectivamente, la única forma que vas a terminar teniendo de enterarte que una memoria esta caída es cuando intentes pedirle algo y te devuelva -1 el recv()

**Comment by cmedrano** [comment]
Hola, recuerdo que en algun issue hice una pregunta similar y la respuesta fue que se se hace gossiping con todas las memorias que tengas en un tabla de gossiping porque si solo haces con las seeds que pasa si se caen estas? por eso tenes que hacer con todos.

**Comment by micayeza** [comment]
Genial, Muchisimas gracias ! :D

**Comment by Dragonflares** [comment]
> Hola, recuerdo que en algun issue hice una pregunta similar y la respuesta fue que se se hace gossiping con todas las memorias que tengas en un tabla de gossiping porque si solo haces con las seeds que pasa si se caen estas? por eso tenes que hacer con todos.

Si se te caen las seeds nunca sabrías si las que eran seeds de esas se desconectaron (si sos memoria) si sos kernel el kernel deberia descartar la memoria de su lista de memorias cuando le quiera mandar una request y esta falle (Igual, esto fue mi implementación que hablé yo también hace como 2 o 3 semanas)

**Comment by iago64** [comment]
Dado que la duda de @micayeza quedo resuelta cierro el issue para evitar que sigan discutiendo sobre **implementaciones de cada grupo**
