### ISSUE TITLE
Retardo de acceso a Memoria Principal

### ISSUE THREAD

**Issue by ncoen97** [sisoputnfrba/foro#1438]
Hola, me quedó la duda de para que sirve el campo "Retardo de acceso a Memoria Principal". Se refiere al retardo para ejecutar cualquier operación? El Describe esta incluido? o con memoria principal se refiere a la memoria contigua donde se guardan los registros?

**Comment by NaylaWinter** [comment]
Buenas,

Con Memoria principal se refiere a la memoria contigua donde se encuentran los registros

**Comment by ncoen97** [comment]
Gracias!
