### ISSUE TITLE
Duda IPS 

### ISSUE THREAD

**Issue by micayeza** [sisoputnfrba/foro#1439]
Hola, perdón pero tengo una nueva consulta. Esta vez respecto a los IPS.
Para crear un socket servidor puedo simplemente pasar INADDR_ANY lo que toma directamente la IP de la máquina. 
 La pregunta es, si en realidad deberíamos pasar ese valor a "mano"?, podría ser por archivo de configuración? o asumo que el archivo de config va a ser consistente con el valor INADDR_ANY?

En caso de usar INADDR_ANY, hay alguna función por codigo que me permita saber el ip de mi proceso?

Gracias

**Comment by mgarciaisaia** [comment]
Hola Mica.

Al bindear un socket tenés la opción de especificar una dirección IP particular para limitar ese socket a una red en particular.

En una misma máquina vos podés tener varias interfaces de red, cada una con su IP.

Imaginate, por ejemplo, un router/modem hogareño. Seguro tiene, al menos, dos interfaces: la interfaz pública, conectada al proveedor de Internet, con una IP publica; y la interfaz privada en la que crea una LAN a la que se conectan las computadoras, teléfonos, y otros cachivaches hackeables del hogar.

Para administrar ese router suele haber disponible una interfaz web, desde la que configurás la conexión a tu proveedor, abrís puertos para hostear jueguitos online, actualizas el sistema operativo del router y lo reiniciás.

En general, esa configuración querés poder accederla vos cuando estás en la red de tu casa y se te corta Netflix, y querés que no la acceda un hacker ruso que quiere usar tu módem para minar bitcoins. Ese servidor web que te permite administrar tu módem suele estar (al menos por defecto) bindeado a escuchar en la IP privada, y no en la pública.

Para el caso del TP, aceptar conexiones de cualquier lado está bien.

**Comment by iago64** [comment]
@micayeza Te ayudo la respuesta de Mati? Podemos ayudarte con algo más?

**Comment by micayeza** [comment]
Hola! si , Muchisimas gracias!
