### ISSUE TITLE
Desconectar LFS 

### ISSUE THREAD

**Issue by Meliibe** [sisoputnfrba/foro#1440]
Hola, en los test de la entrega final, en un momento se pide desconectar file system y el resultado esperado es que mantenga las Keys y sus valores.

La pregunta es, si el Dump todavía no se hizo, entonces los datos no persisten y si mato el proceso, se van a perder ya que estan en memoria. 

Deberían no persistir o deberíamos matar el file system después del dump automático?  

Gracias!

**Comment by Dragonflares** [comment]
Buenas!

Hay varias posibles implementaciones:

1) Forzas un dump cuando le das exit desde la consola al FS (deathProtocol)
2) Ponés que cuando le das al fs que se cierre, que espere a tirar un dump (deathProtocol)

Hay ayudantes que dicen "No deberías pdoer persistir porque si yo cerré el FS es porque no quería guardar los cambios" Otros: "Es un golazo que hayas hecho que persista todo y no importa cuánto tarde en si"

Pero bueno, esas son dos maneras, y si el docu de prueba nos valida, venga la persistencia del DUMP.

Saludos!

**Comment by iago64** [comment]
@Meliibe Como va?
Cuando decimos que el resultado esperado es que mantenga las keys y sus valores, nos referimos a lo que esta en los archivos (lease, no inicies siempre desde un estado limpio)

@Dragonflares La estas complicando de mas, si bien es un golazo que puedan cachear la signal de SIGTERM, no es condición de aprobación ya que _no estaba especificado en el enunciado que asi sea_

**Comment by iago64** [comment]
@Meliibe Como va? pudiste resolver el inconveniete? podemos cerrar el issue? 👮

**Comment by janicead** [comment]
Una consulta sobre este tema, si se cae el LFS tenemos que avisar por consola de memoria que el LFS se cayo y si LFS vuelve a coenctarse, tener que reconectarlo?
