### ISSUE TITLE
Conexión entre dos VMs

### ISSUE THREAD

**Issue by jsarrelli** [sisoputnfrba/foro#1441]
Chicos tengo una duda a la hora de querer probar los procesos en distintas maquinas. 
Cuando tiro los ifconfig dentro de las maquina virtuales, todas me tiran el mismo IP (10.0.2.15). Que es lo que no estaría entendiendo?

**Comment by jsarrelli** [comment]
Cambie la configuracion de red la VM y en una anda pero en la otra queda colgada cuando inicia

<img width="654" alt="Screen Shot 2019-07-11 at 21 19 20" src="https://user-images.githubusercontent.com/18368538/61093636-d7a06580-a421-11e9-999b-52ab89937553.png">

<img width="802" alt="Screen Shot 2019-07-11 at 21 24 23" src="https://user-images.githubusercontent.com/18368538/61093765-88a70000-a422-11e9-8dc8-18122ffeed6b.png">

**Comment by mgarciaisaia** [comment]
Hola Juli.

Suena a que la interfaz de red de la máquina virtual está configurada en modo NAT - modo en el que cada computadora física crea una nueva red para cada máquina virtual.

Deberías poder cambiar (desde la configuración de cada VM en VirtualBox) la interfaz a modo Bridge (Puente), conectada a la interfaz de red que use tu máquina física (la placa wifi o lo que sea que uses para conectarte al router en el que estés laburando).

Si lo haces con la VM prendida, vas a tener que reiniciar la interfaz de red desde el Linux de la VM, o bien reiniciá el Linux y ya. Con esto, cada VM va a tomar una IP distinta, asignada por el router de tu red, y entonces van a poder hablarse entre sí.

Prestale atención a que, dado que ahora es el router el que maneja tu conectividad (En vez de tu máquina física), si cambiás de red vas a tener que reiniciar la interfaz de la VM.

**Comment by iago64** [comment]
@jsarrelli Seguis con el mismo inconveniente? podemos ayudarte con algo mas? 👮

**Comment by iago64** [comment]
Cerramos esto por falta de respuesta, cualquier cosa lo reabren / crean uno nuevo.
