### ISSUE TITLE
Error en comillas de caso de prueba [reemplazo1]

### ISSUE THREAD

**Issue by Fluzko** [sisoputnfrba/foro#1442]
Buenas, escribo para comentarles que el script nombrado tiene unas comillas diferentes a las usadas.
Más que nada es para saber si debemos tenerlas en cuenta o es un error.
Saludos

Link del script: https://github.com/sisoputnfrba/1C2019-Scripts-lql-entrega/blob/master/scripts/reemplazo1.lql

**Comment by NaylaWinter** [comment]
Buenas,

Es un error, ahí modifiqué tanto en ese script como en reemplazo2.lql esas comillas por las comillas habituales.

En cuanto me aprueben el pull request ya van a ver impactados los cambios.
