### ISSUE TITLE
No figura nuestra inscripción a la entrega

### ISSUE THREAD

**Issue by PabloPaglilla** [sisoputnfrba/foro#1443]
Buenas

Escribo porque ayer  (cerca de las 21hs) anoté a mi grupo a la entrega de mañana 13/07, pero hoy entré al sistema de inscripciones para ver si teniamos horario asignado y no figura que estemos inscriptos.

Quería consultar si ustedes nos tienen anotados como para entregar o si hay chance de que podamos ir.

El sistema me dejo solicitar horario otra vez para la fecha, así que por las dudas lo volví a mandar.

El nombre de mi grupo es "Los mallocos".

Muchas gracias,
Pablo Paglilla

**Comment by mgarciaisaia** [comment]
¡Aloha!

A veces... dormimos 🙃. No te voy a decir que siempre, _siempre, siempre_, pero por lo general sí.

En un rato arrancarán las gentes que se están encargando de repartir horarios, y... repartirán horarios. Tranca, palanca - la inscripción no cierra, ni se van a quedar afuera, ni esas cosas.

Abrazo lleno de nervios previos a la entrega, ¡che!

**Comment by PabloPaglilla** [comment]
Mil gracias por la respuesta! Ya nos asignaron horario. Cierro el issue!
