### ISSUE TITLE
ERROR SINTAXIS SCRIPTS

### ISSUE THREAD

**Issue by afondevilarevelli** [sisoputnfrba/foro#1444]
Hola, comento que el script misc_2.lql está mal sintacticamente.
Hay una linea que es: SERIES PELICULAS 3128
Supongo que ese SERIES debería ser SELECT.
Creo que dijeron que no iban a proveer scripts con error de sintaxis, no?

**Comment by NaylaWinter** [comment]
Hola,

Si, se trata de un error, debería ser un select.

Ya lo modifiqué, en cuanto me aprueben el pull request ya se veran impactados los cambios

**Comment by iago64** [comment]
Corregido el script, se cierra el issue.
