### ISSUE TITLE
Archivos de configuración

### ISSUE THREAD

**Issue by mesaglio** [sisoputnfrba/foro#1445]
👋 ¡Hola!
En la prueba de kernel, en el archivo de configuracion de la memoria1 en el campo de PUERTO_SEEDS=[IP_MEMORIA3], la idea es que por gossiping llegue la ip y el puerto bien?

**Comment by iago64** [comment]
Buenas!

Fue un typo, nada grave, la idea es que sea el puerto de la memoria 3.

Abrazo!

**Comment by mesaglio** [comment]
Gracias!
