### ISSUE TITLE
Issue prueba kernel

### ISSUE THREAD

**Issue by Renkon** [sisoputnfrba/foro#1446]
Hola! Buenas noches,

Estuvimos haciendo la prueba de PRUEBA KERNEL, y hay una parte donde hace

Ejecutar los scripts misc_1.lql, misc_2.lql y cosas_falla.lql

Al hacer esto, cosas_falla, termina creando la tabla 'COSAS' inicialmente. Y todo corre bien. El tema, es que el script misc_1.lql, termina fallando porque adentro tiene un CREATE COSAS también, que hace que falle (porque la tabla ya existe). 

El tema es que, despues, una prueba pide hacer un SELECT COSAS 332, el cual se hace a posteriori de este CREATE COSAS que falla. Cabe destacar, que luego cosas_falla también falla porque tiene otro CREATE COSAS más. En conclusión, nunca va a haber nada insertado en la fila 332, debido a que el script (por haber corrido con round robin de Q=2), no puede crear la tabla, porque ya existe.

¿Puede ser que esto indique un problema de las pruebas?
Un saludo

**Comment by NaylaWinter** [comment]
Buenas,

Resolvelo de la forma que consideres adecuada.

Si queres elimina el CREATE que falla del script misc_1.lql y sino simplemente no modifiques la línea y deja fallar el script, pasandolo a la cola de finalizados.
