### ISSUE TITLE
Prueba Memoria: Tamaño

### ISSUE THREAD

**Issue by jaks97** [sisoputnfrba/foro#1447]
Buenas,

Realizando la prueba de memoria, del documento de pruebas, nos surgió una duda respecto al tamaño de la memoria/cantidad de reemplazos:

El tamaño del value en esta prueba es de 60 bytes. Esto nos da que Tamaño de registro = 60 + 2 bytes de la key + 8 bytes que usamos para el timestamp = 70 bytes. Tamaño de memoria para esta prueba es de 340 bytes. Por lo que entran 4 paginas en la memoria (340 / 70 = 4).

Bajo estas premisas, luego de correr el script `reemplazo1.lql` y hacer un JOURNAL, de modo que la memoria quede vacía, corremos el script `reemplazo2.lql`.
Los resultados esperados indican que entonces solo 2 reemplazos ocurrirán, pero no ocurre así en nuestro caso: los primeros 4 SELECT del script llenan la memoria y luego el próximo SELECT ya obliga a que haya un reemplazo. Los siguientes 4 INSERT provocan reemplazos, y como son INSERT, quedó la memoria FULL. Entonces el INSERT de la key 120 ya provoca el JOURNAL, a diferencia de lo que dice el enunciado sobre ser el de la key 199.

Debido a esto, también es que en el primer script, si bien no hay reemplazos por ser todas operaciones INSERT, en el medio se realiza un JOURNAL porque la memoria se llena.

Pensamos que capaz estamos tomando un tamaño de registro muy grande, puesto que si lográsemos hacer entrar 5 registros en memoria principal el resultado seria perfectamente consistente con el esperado. Pero no podemos achicar por ningún lado. Las keys son de 2 bytes por enunciado, y el timestamp en milisegundos no hay manera que entre en 4 bytes (2^32 = 4.294.967.296 < 1.563.034.289.414 = timestamp al momento de escribir esto).
¿Que es lo que está mal? De todos modos los reemplazos se hacen en el orden que deberían, solo que se hacen mas reemplazos que los que se indican.

Saludos y gracias.

**Comment by diego-rz** [comment]
Me sumo a la consulta, tengo exactamente la misma situación.

**Comment by fighthawkarg** [comment]
Ami también los resultados no me dan...

**Comment by NaylaWinter** [comment]
Buenas,

Las diferencias tienen que ver con el tipo utilizado para el timestamp. 

La idea de la prueba es que tengan en la Memoria 5 marcos disponibles, teniendo cada página un tamaño de 64 Bytes.

Si con los números que hoy en día están en los archivos de configuración en su implementación les quedan 4 marcos simplemente bájenle el tamaño al value hasta que les entren 5 marcos en la memoria, no hay problema con eso.
