### ISSUE TITLE
Gossiping

### ISSUE THREAD

**Issue by cmedrano** [sisoputnfrba/foro#1449]
Hola, una consulta el puerto de escucha que va a tener una memoria para escuchar gossiping es el mismo que va a tener para escuchar los pedidos de kernel?
Es decir si tengo dos memorias A y B
Si la memoria A tiene como seed la memoria B entonces en el config de la memoria A voy a tener el puerto y la IP de B.  Este puerto es el mismo por el cual la memoria va a recibir solicitudes del Kernel?

Muchas gracias

**Comment by cmedrano** [comment]
Otra pregunta:
Tengo que hace siempre gossiping con las memorias seeds aun luego de que la  memoria seed haya estado en la tabla de gossiping y se haya desconectado,
Es decir por ejemplo
Cuando la memoria A hace gossiping con Memoria B( donde justamente B es una seed de A). Se agrega la memoria B a la tabla Gossiping de A. 
Pasado un tiempo la Tabla de Gossiping de A es : Memoria A, Memoria B, Memoria C (C es una seed de B)
Luego se cae la memoria B.
Cuando vuelvo a ejecutar el proceso gossiping del Proceso A tendría que envíar gossiping a memoria  C, mi pregunta es tengo que envíar de nuevo gossiping a B. 

Siempre envío gossiping a los que estan en mi tabla gossiping, si una memoria seed que esta en la tabla gossiping se cae, como ya no esta en mi tabla gossiping le tengo que mandar gossiping igual aunque ya no este?

Muchas gracias

**Comment by iago64** [comment]
Buenas buenas!

El puerto escucha es a donde se te van a conectar los procesos, pero despues de ahi vos vas a tener que hacer un handshake y saber si es otra memoria que quiere hacer gossiping o un kernel.

Respecto a tu segunda pregunta, si, la idea es que siempre intentes hacer gossiping, por más que se haya caído en algún momento, puede que se reconecte ;)

Abrazo!

**Comment by cmedrano** [comment]
Muchas gracias Dami!!

Abrazo!

**Comment by martinzuccotti** [comment]
Hola!

Yo tengo una duda relacionada al gossiping también. En nuestra implementación, la memoria incorpora a las seeds de otras memorias a medida que se va conectando y, en la siguiente ejecución, se intenta conectar a ellas también (como si todas fueran seeds).

Por un lado, la ventaja de hacerlo así es que se descubre el pool completo más rápido. Además, para que una memoria sea descubierta alcanza con que alguna otra la haya tenido como seed en algún momento, sin importar si esa memoria está activa o no ahora. Pero, por el otro, estoy teniendo más overhead y no estoy seguro de estar respetando al pie de la letra el enunciado, que es lo que me preocupa.

La pregunta es si nuestra implementación es válida también o si hay que adaptarla para la entrega.

Gracias!

**Comment by rcomesan** [comment]
@martinzuccotti yo lo tengo implementado de la misma forma. No es la mejor idea porque encima le hago retry a cada una en cada período de gossiping (N^2 + N conexiones en total sumando memorias y kernel). 

A fines prácticos para este tp académico se descubren los nodos mucho más rápido al costo de conexiones al pedo por todos lados. Igual para nuestra tranquilidad [acá](https://github.com/sisoputnfrba/foro/issues/1372#issuecomment-497481049) dijero que se hace así.

**Comment by martinzuccotti** [comment]
@rcomesan genial, gracias!
