### ISSUE TITLE
Problemas con printeo de un dato

### ISSUE THREAD

**Issue by janicead** [sisoputnfrba/foro#1450]
Hola!
Estamos intentando hacer printf/log_error/log_info del dato "op->argumentos.DROP.nombre_tabla" pero nos tira el error que voy a adjuntar en las fotos.  Lo que nos llama la atencion es que si entra por el if, no se genera el error, pero si entra por el "else" si.
![66646330_715922045581848_5330014350881062912_n](https://user-images.githubusercontent.com/31738186/61180501-98bf0b00-a5ed-11e9-9587-da82a6f416b9.jpg)
![66835667_366417887354421_4972169431103832064_n](https://user-images.githubusercontent.com/31738186/61180504-9e1c5580-a5ed-11e9-8ea1-091887298a59.jpg)
![67062109_2309517056033232_2672805783783079936_n](https://user-images.githubusercontent.com/31738186/61180505-a07eaf80-a5ed-11e9-9a30-c53b37c73a84.jpg)

**Comment by Dragonflares** [comment]
Buenas!

Se te está quejando de que le tiraste free al parámetro que querés mostrar en ese printf, en un free en la línea 162 de consolaKernel.c. Probablemente sea que en caso de error nunca tiraste free a ese parámetro, pero cuando funciona si lo hiciste, te recomiendo esperar a terminar de loggear, usar y guardar esa variable antes de tirarle free.

Saludos

**Comment by janicead** [comment]
Muchas gracias!!!!!!!!!!!!!!!!!! Lo solucio uno de mis compañeros de equipo por el comentario de @Dragonflares 
Saludos!
