### ISSUE TITLE
Kernel|Memorias|Consistencias

### ISSUE THREAD

**Issue by fighthawkarg** [sisoputnfrba/foro#1451]
Supongamos que le hago add a las memorias de esta forma.

Memoria 1 al criterio SC.
Memorias 2 y 4 al criterio SHC.
Memorias 3 y 4 al criterio EC.

Una vez que las memorias fueron asociadas, quedan para siempre asociadas a esa consistencias? 
O hay que contemplar el caso de que si una memoria se cayo (al querer enviarle algo me doy cuenta de esto) las **quito (LIST_REMOVE) de todos los criterios donde estaba asociada**?

**Comment by Dragonflares** [comment]
Te propongo el siguiente caso, pensá que SHC tiene la función HASH que va a buscar en la lista (o lo que sea que tengas armado) de memorias asignadas a SHC y va a elegir una memoria de ahí. Si nunca sacas a la memoria que se desconectó, todas las requests a esa memoria que se desconectó van a fallar. Por ende falla el script. Si se cae una memoria hay que sacarla de ahí para que las demás tiren JOURNAL y el criterio no falle de ahí en adelante.

**Comment by fighthawkarg** [comment]
Espero la Respuesta Oficial de un Ayudante...

**Comment by iago64** [comment]
Buenas buenas!!

TL/DR: Se cae la memoria, se caen los criterios que tenia

Explicación larga:
El objetivo de asignar una memoria a una consistencia es para determinar que operaciones va a realizar, ahora bien, ese criterio como bien se ve en las pruebas no es exclusivo, con lo cual, una memoria puede ser SC, SHC y hasta EC.
Si se te cae la memoria de SC y queres asignar ese criterio a otra para poder seguir operando con tablas SC deberías poder, ya que eventualmente si esa memoria SC es irrecuperable, tu kernel quedaria sin una consistencia for ever, con lo cual. Si se te cae una memoria, marcala como caida y limpiala de tus tablas / listas / lo que sea que tenes para administrar tus criterios.

Slds.-

**Comment by fighthawkarg** [comment]
Se Entendio Perfecto. Cierro Issue Gracias a los Dos.
