### ISSUE TITLE
Rutas Relativas!

### ISSUE THREAD

**Issue by micayeza** [sisoputnfrba/foro#1452]
Hola! Llevo una larga pelea con las rutas cuando intento abrir un directorio.
Resulta que si pongo la ruta absoluta "Harcodeada" anda bien. Pero cuando uso la relativa ( punto de montaje que viene en el archivo + carpeta que busco) el opendir siempre trae NULL.

Mi ejecutable esta en la carpeta fileSystem/src/fileSystem 
y quiero entrar a la carpeta fileSystem/Tables/ 
Deberia ser ../Tables/ pero trae NULL. También intente dandome permisos supremos y nada.
Gracias!

**Comment by mgarciaisaia** [comment]
Hola Mica.

Fijate si estás cayendo en el error típico de este post: [Rutas Argentinas](https://mgarciaisaia.github.io/tutorial-c/blog/2015/04/23/rutas-argentinas/).

Si no, compartinos los fragmentos de código que creas relevantes, así vemos qué está pasando. En el aire, complicado adivinar.

¡Éxitos!

**Comment by rcomesan** [comment]
Habría que revisar el código pero mirá que si tu current working directory (donde estás ejecutando tu binario) es /fileSystem/src/fileSystem/ y me decís que querés entrar a la carpeta /fileSystem/Tables/ tu path relativo es ../../Tables (subís 2 niveles y después te metes en Tables).

**Comment by Renkon** [comment]
El binario se genera en fileSystem/Debug si no me equivoco, entonces la ruta la tenes que generar sabiendo que el binario lo corres de fileSystem/Debug, o correlo desde la carpeta fileSystem con ./Debug/binario, de forma tal que tu PWD sea fileSystem.

**Comment by micayeza** [comment]
Hola! si ayer note que si corria el debug de eclipse inicia desde otra ruta, por ende para debugear tengo que usar absolutas.
Muchas gracias!
