### ISSUE TITLE
Consulta gossiping y caida de memoria

### ISSUE THREAD

**Issue by julian-0** [sisoputnfrba/foro#1453]
Hola en nuestro grupo nos surgió una duda corriendo la prueba del kernel en el que hay un esquema así: 

![gossiping](https://user-images.githubusercontent.com/42820126/61251199-26a30f00-a730-11e9-95f2-6617c8e7b382.jpeg)

En la prueba desconectan la memoria 2, el problema surge porque el pool de memorias nunca se va a enterar de la caída de esta, porque no es seed de ninguna otra memoria. La memoria 2 circularía por todas las tablas de gossiping sin que ninguna otra memoria la saque. El kernel solo se enteraría en caso de que le mande una request y esta falle.

Pensamos en la alternativa de que cada memoria en lugar de hacer gossiping solo con sus seeds lo haga con todas las que conoce, el problema de esta idea, ademas de que contradice el enunciado, ya que en este se muestra que solo se hace gossiping con las seeds, es que una memoria no sabría con que información quedarse ya que no sabe si su tabla es la correcta o la que le mandan.

Esta bien que el kernel solo se entere de la caida de la memoria al momento de enviar una request (si esto pasa podriamos mandar esa request a otra memoria asociada a la consistencia utilizada) y que en las tablas de gossiping esta memoria siga circulando como si estuviera conectada?

**Comment by Renkon** [comment]
En el caso de nuestra implementación, fue igual a la de ustedes, y solo te enterás en el momento que el Kernel elige comunicarse con esa memoria.

En las pruebas nos pasó de tener que esperar un poco de más, pero eventualmente siempre se detecta el cambio tarde o temprano.

**Comment by julian-0** [comment]
Gracias por tu respuesta, no me quedo claro esto: 
Cuando el kernel hace gossiping no le estarían mandando siempre que la memoria 2 sigue activa? Esto hace que en cada ciclo de gossiping el kernel intente conectarse a ella. No tenes forma de que las memorias se enteren y dejen de mandársela al kernel

**Comment by Renkon** [comment]
No. No tenés forma de que las memorias se enteren.
No obstante, lo que si podés hacer, es que el Kernel tambíén le envíe la información que él tiene de las memorias, a la memoria con la que hace gossiping. De esta forma, eventualmente todas las memorias podrían saber que se cayó la memoria 2.

**Comment by Dragonflares** [comment]
Una cosa que me dijeron los ayudantes es que el gossip se maneja con consistencia eventual, así que la idea de que el Kernel se entere a último momento que la memoria no existe (osea cuando se conecta) está perfecto, porque la idea de EC es que eventualmente se sepa el valor correcto

**Comment by afondevilarevelli** [comment]
Nosotros hicimos que una memoria al desconectarse, le avise de su desconexion a todas las memorias que conoce en ese momento, y que dichas memorias tambien le avisen a las que conocen que se desconectó tal memoria, y así recursivamente. Luego cuando se realice el aoguiente gossiping, no se conocerá a la memoria desconectada.

**Comment by iago64** [comment]
buenas buenas!!

Veo que en algún punto les gusta complicarse las cosas...
Muchachos **no hay ningún problema** con que el kernel se entere de que esta caída la memoria 2 recién cuando le va a hacer una petición.
Estamos en fechas de entregas, traten de no complicarse mucho (ni tirar soluciones que compliquen a sus compañeros que están mas justos de tiempo)

Saludos.-

**Comment by julian-0** [comment]
Gracias a todos por su respuestas, ya le encontramos la vuelta
Saludos!!
