### ISSUE TITLE
Datos corruptos cuando leo de un archivo

### ISSUE THREAD

**Issue by Dragonflares** [sisoputnfrba/foro#1454]
Buenas buenas!

Últimamente me estuve encontrando con un error que no se muy bien como afrontar, e involucra todos los criterios que tiene que manejar el FS.
Por algún motivo cada tanto el FS devuelve que una key a la que se trató de acceder no existe (que es condición de freno para SC y SHC) en scripts donde se supone que esa key ya existe. Sin embargo, si más tarde pido esa misma key por consola, a veces la devuelve y otras no. Hasta ahora mi única posible creencia es que la lectura(o la escritura) que hago en los archivos .tmp termina perdiendo alguna clave, pero sin embargo detecta que hay un dato y lo trata de levantar y convertir en una key cuando quiere compactar ese tmp, sin embargo, una búsqueda manual dentro de los bloques del tmp no da resultados en hallar datos corruptos la mayoría de las veces. Por ende, termino con errores como éste en valgrind:

![image](https://user-images.githubusercontent.com/28828524/61301176-c953a000-a7b9-11e9-8f32-1bcdab60470e.png)
![image](https://user-images.githubusercontent.com/28828524/61301206-d3759e80-a7b9-11e9-8fb0-9188c69f3c53.png)

Actualmente para la escritura y la lectura uso estas dos funciones:

ESCRITURA:
![image](https://user-images.githubusercontent.com/28828524/61301482-58f94e80-a7ba-11e9-90d6-1ac9c22d8911.png)

![image](https://user-images.githubusercontent.com/28828524/61301517-6b738800-a7ba-11e9-9891-f1829f4494c9.png)
![image](https://user-images.githubusercontent.com/28828524/61301638-a8d81580-a7ba-11e9-96b4-967262441d08.png)

LECTURA:
![image](https://user-images.githubusercontent.com/28828524/61301683-cb6a2e80-a7ba-11e9-9960-201ad1eda029.png)

Sin embargo estos errores surgen principalmente cuando la carga de procesamiento del FS es excesivamente alta (Manejos de alrededor de 100 bloques o más)

Tengo una posible solucion pero es un sobrediseño del mismo de proporciones astronómicas, que involucra alguna manera de validar que se encontró un campo corrupto o fallido y pedir una relectura del bloque al que pertenecía el campo (Ya que cuando leo la información la agrego en una lista que puedo usar el index para obtener el index del bloque en la particion/tmp a la que pertenezca) Pero me gustaría saber si tiene otro origen. Si pongo un retardo más grande que 0,1segundos el error prácticamente desaparece.

Desde ya muchas gracias con cualquier idea sobre por qué falla

Edit 1 y agregado: Las mínimas veces que encontré un dato corrupto en el .tmp aparecia como "0;0;"

**Comment by iago64** [comment]
Si agregando retardos el error desaparece me huele a una hermosísima condición de carrera.
Que te dice helgrind al respecto?

Saludos.-

**Comment by Dragonflares** [comment]
> Si agregando retardos el error desaparece me huele a una hermosísima condición de carrera.
> Que te dice helgrind al respecto?
> 
> Saludos.-

En el momento después de que salta ese mensaje? Nada, Helgrind no me tira condicion de carrera ahí

**Comment by iago64** [comment]
Ojo, que el árbol no te tape el bosque, no te tira condición de carrera ahí, pero te la tira en otro momento?

Fijate que los saltos que te dice son por una variable sin inicializar, el tema es que, que tenes en esa variable? que estas tratando de mover.
Nos diste la info de como grabas los bloques, pero no de donde te tira el error.

Como consejo de zorro viejo, los problemas de hilos nunca están en el lugar donde revientan, están bastante lejos.

Abrazo!

**Comment by Dragonflares** [comment]
Buenas!

Estuve mirando arriba, y no tuve ningun "possible data race" involucrado hasta hacia al menos 2 dumps atrás (Mucho antes del insert de las keys que fallan) y solamente estaba quejándose de que el readdir podía tener un posible conflicto con un read de strlen??? Pero ni siquiera está relacionado a la lectura de keys.

Como un agregado sumo mi parser de keys, parser inverso, constructor de keysetters, y su llamado en el dump (donde parece venir el problema) (O eso creo)

![image](https://user-images.githubusercontent.com/28828524/61421290-d61ce480-a8dc-11e9-92e5-435571b9bed9.png)

![image](https://user-images.githubusercontent.com/28828524/61421309-e8971e00-a8dc-11e9-8b07-eb81d8bc7bed.png)
![image](https://user-images.githubusercontent.com/28828524/61421316-f51b7680-a8dc-11e9-90af-83e2517b4131.png)
![image](https://user-images.githubusercontent.com/28828524/61421332-082e4680-a8dd-11e9-9d17-081489cdec83.png)
![image](https://user-images.githubusercontent.com/28828524/61421344-12504500-a8dd-11e9-85c9-f24de9f73302.png)

Nota: Si... parsear keys podría haber usado simplemente un string_split, no? Pero me encontré que ese string_split me generaba errores desconocidos, así que mantengo mi función manual

![image](https://user-images.githubusercontent.com/28828524/61421386-49265b00-a8dd-11e9-89e8-4ed03512bbab.png)

![image](https://user-images.githubusercontent.com/28828524/61421430-7b37bd00-a8dd-11e9-84d6-d5fbdaf4aa56.png)
![image](https://user-images.githubusercontent.com/28828524/61421443-87237f00-a8dd-11e9-91e6-12e1cb515618.png)
![image](https://user-images.githubusercontent.com/28828524/61421466-96a2c800-a8dd-11e9-8cb0-506a9cf4e3a7.png)
![image](https://user-images.githubusercontent.com/28828524/61421479-a28e8a00-a8dd-11e9-8741-e018db54716e.png)


Ya se que es un montón, pero sinceramente no se quién tiene la culpa. (Podría haber hecho un gist, pero supongo que ya está)

Saludos

**Comment by Dragonflares** [comment]
Bueno, al final terminó solucionándose la situacion. Coloque un par de mutex de lectura/escritura dentro de mis funciones de lectura y escritura, con lo cual solo un bloque se puede escribir a la vez o un bloque se puede leer a la vez, y el problema dejó de ocurrir.
Sin embargo, hacer eso generó otro problema medio raro:

![image](https://user-images.githubusercontent.com/28828524/61423057-b38ec980-a8e4-11e9-9f91-eb4306aadccd.png)

Sin embargo, revisando eso, el elemento que dice que yo le hice free yo lo removí de la lista:

![image](https://user-images.githubusercontent.com/28828524/61423108-eb960c80-a8e4-11e9-9516-b503582a7e88.png)

Estaría un poco confundido
