### ISSUE TITLE
Tamaño bloque

### ISSUE THREAD

**Issue by torresmanu** [sisoputnfrba/foro#1455]
Hola, que tal?
Tenemos una duda con el tamaño de los bloques en el LFS. Teníamos entendido que para guardar un registro en un bloque no era necesario partirlo, si no entra en un bloque lo pongo en el siguiente (aceptando la fragmentación interna que tendríamos en el bloque anterior). Pero si lo hacemos de esta forma no podríamos siquiera correr la prueba base, ya que el tamaño de bloque es menor que el tamaño de un registro. (por los tamaños que indican los config)
Por lo que asumimos que si o si en nuestra implementación debemos partir los registros y asignar todo el espacio contiguo aunque me quede una parte de un registro en un bloque y otra en otro. Es así?
Gracias, saludos!

**Comment by iago64** [comment]
Buenas buenas!!

**TL-DR:** 
Si, tienen que considerar como que el archivo esta todo continuo y grabar los registros aunque les quede un pedacito en un bloqueo y otro pedacito en otro.

**Explicación larga:**
Un poco la idea de tener un file system, es que vos del lado de aplicación le decís guardalo y no te importa como. 
Mientras que del lado del FS, vos ves si guardas todo junto (asignación contigua con posible fragmentación externa), si solo guardas si entra (aceptando fragmentación interna) o tenes un esquema de bloques donde vos guardas tus datos cortándolos al tamaño del bloque (teniendo solo fragmentación interna en el ultimo bloque).

Abrazo.-

**Comment by torresmanu** [comment]
Gracias, saludos!
