### ISSUE TITLE
Elección de semaforos

### ISSUE THREAD

**Issue by GonzaOrtega** [sisoputnfrba/foro#1456]
Una consulta rápida: que tipos de semáforos se tienen que utilizar en el tp?? Yo hasta ahora use las funciones sem_wait y sem_post pero me dijeron que algunos tuvieron problemas con ellas y que debería usar pthread_lock_wait y pthread_lock_unlock. Cual debería usar?? Hay alguna diferencia entre ambas??

Saludos

**Comment by gastoncastineira** [comment]
Buenas
Ustedes están autorizados, en principio, a utilizar la biblioteca semaphore.h y lo que venga dentro la propia pthread.h para resolver problemas de sincronización.
pthread_lock_wait y pthread_lock_unlock no existen, así que voy a asumir que te estás refiriendo a [pthread_mutex_lock](https://pubs.opengroup.org/onlinepubs/7908799/xsh/pthread_mutex_lock.html) y [pthread_mutex_unlock](https://linux.die.net/man/3/pthread_mutex_unlock). Podés usar cualquiera de las dos sin restricción alguna desde nuestra parte, y entre ellas hay una diferencia muy importante que seguro viste en la teoría, y seguro que mencioné en la charla de sincro.
Un semáforo puede ser un mutex, pero un mutex no es un semáforo. Un mutex es solamente algo que te garantiza la mutua exclusión entre hilos para esa sección crítica. Un semáforo también puede hacer eso, pero no necesariamente haga mutua exclusión porque también existen los semáforos contadores (osea, N pueden entrar a la sección crítica al mismo tiempo). Si yo le hago 5 veces post a mí sem_t, puedo hacer 5 veces wait sin quedar bloqueado. En cambio, si yo hago 5 veces unlock a mí mutex es comportamiento no definido.
Ahora, en lo que mencionás que hubo gente con problemas con semaphore, habría que ver los casos particulares, pero en principio es más probable que sea algún problema en la implementación del TP que de la propia biblioteca.
Espero haber esclarecido un poco. Sino, volvé a escribir sin miedos

**Comment by GonzaOrtega** [comment]
Buenisimo!!! Gracias!!
