### ISSUE TITLE
Log por hilo

### ISSUE THREAD

**Issue by GonzaOrtega** [sisoputnfrba/foro#1457]
Hola. Una consulta: es necesario hacer un log por hilo?? Más que nada por la parte de multiprocesamiento pregunto.

Gracias

**Comment by tferraro** [comment]
Buenas!

A qué le llamás "hacer un log por hilo"? Estás refiriendote a loggear información de cada hilo o a tener **más de ún logger** por cada hilo? 🙂

**Comment by GonzaOrtega** [comment]
Me refiero a que si cada hilo que se usa en el tp (más que nada me interesa los "procesadores") tiene que tener su propio archivo de log

**Comment by tferraro** [comment]
**Oh por dios no**, te imaginás lo complicado que sería leer esos logs?

Por lo general, los loggers tienen la capacidad de mostrar que proceso/hilo los está generando. En el caso de las commons, muestra el `pid` del proceso y el `thread_id`, mirá: https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/log.c#L133

**Comment by GonzaOrtega** [comment]
Gracias a dios!!! Yo pensaba lo mismo, que se me iba a armar un enchastre de logs!!! 

Gracias!!!

**Comment by GonzaOrtega** [comment]
Ahora que lo pienso, esto no va a ser que sea difícil testearlo para ustedes con todos los logs del multiprocesamiento juntos??

**Comment by GonzaOrtega** [comment]
Buenisimo!!!
