### ISSUE TITLE
Memory corruption en config create

### ISSUE THREAD

**Issue by leoguerberg** [sisoputnfrba/foro#1458]
Buenas. Tenemos un problema a la hora de abrir un config para leer y escribir una particicion (las trabajamos como config).

Ya recorrimos el código y en todos lados cerramos todos los config y file que abrimos.

Este error lo tira algúnas veces si y otras no y no podemos solucionarlo ya que es por algo interno de las commons y no entendemos que podemos estar haciendo mal.

Lo único que hacemos es config create, escribir en la partición, config save y destroy.

Gracias.
![15633874945505489642483711971453](https://user-images.githubusercontent.com/43414590/61400209-2a58a200-a8a6-11e9-8e0b-adda63e79461.jpg)

![15633875432313932306247219572496](https://user-images.githubusercontent.com/43414590/61400245-3e040880-a8a6-11e9-88f2-6e12ce1cd316.jpg)

**Comment by mgarciaisaia** [comment]
Hola.

¿Corrieron [`valgrind`](https://faq.utnso.com/valgrind)?

¿Vieron el video de [cómo reportar errores](https://faq.utnso.com/errores-eclipse)?

Nos falta (muchísima) información como para poder empezar a tirarles una soga.

**Comment by tferraro** [comment]
Hago un up a esto! @leoguerberg pudieron recavar más info? En que status estamos?

**Comment by leoguerberg** [comment]
Mil disculpas! Estuvimos muy concentrados y colgamos, pero pudimos resolverlo! Muchas gracias!

**Comment by torresmanu** [comment]
Buenas @leoguerberg , estamos teniendo un problema similar creo y no podemos encontrar como es que rompe, sabes que es lo que les pasaba o cómo lo solucionaron al final? 
Gracias, saludos!
