### ISSUE TITLE
Rompe consola

### ISSUE THREAD

**Issue by GonzaOrtega** [sisoputnfrba/foro#1459]
Por que si rompo el programa por la fuerza me pasa eso con la consola?? Apreté Enter 2 veces y si sigo apretando sigue pasando lo mismo

![15634048706936284147742966712247](https://user-images.githubusercontent.com/38133971/61417743-96e79700-a8ce-11e9-8c5c-cbf8509a415c.jpg)

**Comment by mgarciaisaia** [comment]
¡Aloha!

Para que se vean colorcitos en una terminal, el programa (en este caso, la biblioteca de log) usa lo que se llaman _caracteres de control_. Son unos bytes que se envían a la salida (digamos, "se imprimen por pantalla"), pero que, en vez de representar un caracter, la terminal sabe que tiene que interpretarlos de alguna manera especial - por ejemplo, cambiando el color de los caracteres que siguen.

Podés verlos, por ejemplo, redirigiendo la salida de tu programa a un archivo (`./KernelV2 > unarchivo.log`), y después inspeccionando ese archivo con `less`, `vim` o cualquier otro. Vas a ver que hay algunos caracteres raros (cosas como `\[\033[0;1;37m\]` o qué se yo).

Cuestión que, si tu programa termina de manera brusca, andá a saber cuál fue el último caracter de control que le llegó, y qué indicación tenía. Así que capaz te quedó la consola mambeada porque la terminal interpretó como caracter de control algo que capaz no era la idea.

Anyway, existe un programita llamado `reset` que tira los caracteres de control necesarios para que tu terminal vuelva a la vida. Cuando caigas en estos bardos, corré `reset` en la terminal (puede que no veas los caracteres mientras tipeás `reset`, pero seguí igual como si nada) y debería solucionarse.

**Comment by GonzaOrtega** [comment]
Gracias!!! Estábamos te asustados! Pensábamos que habíamos roto algo!!
