### ISSUE TITLE
Consulta Prueba Kernel

### ISSUE THREAD

**Issue by ariel-** [sisoputnfrba/foro#1460]
👋 ¡Hola!

Al efectuar las pruebas del apartado Kernel nos topamos con lo siguiente:

Resultado esperado por pruebas:
> Los scripts `animales`, `comidas`, `misc_1` y `misc_2` terminan correctamente, mientras que los `internet_browser_falla` y `cosas_falla` terminan debido a una falla.

Resultado obtenido:
En nuestras pruebas, el script `misc_1` fallaba primero, antes que el `cosas_falla`, esto es ya que se los hace correr a los 3:

> Ejecutar los scripts ​misc_1.lql​, ​misc_2.lql​ y ​cosas_falla​.lql

Lo que causa el fallo de `misc_1.lql` es que al llegar a la linea 7 (recordar que el q=2 asi que el 'backtrace' fue: 
misc_1 [1-2] ->
misc_2 [1-2] ->
cosas_falla[1*-2] ->
misc_1 [3-4] ->
misc_2 [3-4] ->
cosas_falla [3-4] ->
misc_1 [5-6] ->
misc_2 [5-6] ->
cosas_falla [5-6] ->
misc_1 [7*-8]

Las lineas con * son: 
cosas_falla.lql Linea 1: `CREATE COSAS EC 2 40000`
misc_1.lql Linea 7: `CREATE COSAS SC 9 35000`

Por lo tanto, el `misc_1.lql` siempre falla ya que el `cosas_falla.lql` había creado la tabla `COSAS` antes.

**Comment by iago64** [comment]
Buenas buenas!!

Mientras fallen por eso esta todo en orden, no te preocupes 😄 
Eventualmente el ayudante que los este evaluando cambiara un poco el orden de ejecución de los scripts para que termine misc_1 y después correrá cosas_falla para que efectivamente falle 😉 

Abrazo!

**Comment by ariel-** [comment]
Ah, excelente entonces! Gracias por la contención de crisis (?

Cierro
