### ISSUE TITLE
Salir de ejecución

### ISSUE THREAD

**Issue by GonzaOrtega** [sisoputnfrba/foro#1461]
Una duda, como se tiene que manejar la salida de los módulos?? Es decir, al finalizar toda la ejecución, como cierro las cosas?? Por un comando extra que mande un mensaje a los demás módulos?? De ser así, tiene que planificarse??

Gracias

**Comment by iago64** [comment]
Un fin de ejecución bonito para procesos que vamos a matar eventualmente con Ctrl + C?

![image](https://user-images.githubusercontent.com/1622109/61487622-bccb7500-a97c-11e9-8031-5edb1d953461.png)

Hablando en serio, no te preocupes, no hay necesidad de que capturen el Ctrl + C o armen un comando para bajar los procesos, eventualmente en la entrega les diremos _bajen todo_ y empezaran a tirar kill -9 o Ctrl + C a troche y moche :)
