### ISSUE TITLE
Duda con resultados en prueba memoria

### ISSUE THREAD

**Issue by julian-0** [sisoputnfrba/foro#1462]
Buenass estábamos corriendo la prueba de memoria en la que hay 5 frames en la memoria y nos surgió una duda, después de que se realiza el journal forzoso y se ejecutan los select a mano en el lfs.

Los 5 primeros select nos dan bien pero el ultimo, el de la key 999, no encuentra el registro porque todavía sigue en la memoria ya que el journal inserto los valores actualizados en el lfs para poder guardar el insert en memoria del value "Queso y dulce" .
No es eso lo que debería pasar? O estamos entendiendo mal los resultados esperados?

Estamos trabajando con tamaño de memoria 350 y tamaño de value 60 para que haya exactamente 5 frames (por lo que vimos en el issue #1447 esta bien modificar estos valores).

Saludos!! 👋

**Comment by NaylaWinter** [comment]
Buenas,

Perdona pero no te entendí el problema. La idea es que al querer insertar la key 999 debería dar que la memoria esta full, luego el kernel forzar el journal y luego recién una vez que la memoria esta vacía insertar la clave.

Me queres volver a explicar el inconveniente asi intento contestarte?

**Comment by NaylaWinter** [comment]
@julian-0 se resolvió la duda al final? Cómo te podemos ayudar?

**Comment by julian-0** [comment]
Uh si perdón me olvide del issue, ya aclaramos la duda. Gracias!
Cierro el issue.
