### ISSUE TITLE
Duda Prueba Lissandra

### ISSUE THREAD

**Issue by Dragonflares** [sisoputnfrba/foro#1463]
Buenas

Estuve viendo que en prueba Lissandra pide dar de baja a Lissandra y levantarlo y luego tirar consultas desde el kernel. Sin embargo, por la naturaleza de la conexión de las memorias hacia el FS (De conexión única) sucede que la conexión es irrecuperable sin levantar las memorias de nuevo. 
En ese caso, debería volver a levantarse a todas las memorias y el kernel para ejecutar las otras requests?

Desde ya, muchas gracias

**Comment by tferraro** [comment]
Si te referís al item: `Desconectar el proceso LFS y relevantarlo`, si su tp lo requiere, pueden relevantar las memorias también 🤙

**Comment by Dragonflares** [comment]
Buenísimo, gracias por la respuesta Tom!
