### ISSUE TITLE
Resultados en Prueba de STRESS

### ISSUE THREAD

**Issue by franferron07** [sisoputnfrba/foro#1464]
Hola

Realizando las pruebas de stress nos topamos con lo siguiente:

Cuando desconectamos la memoria 2 asociada al criterio EC y kernel esta ejecutando los script  quiere enviar una solicitud a esta memoria pero al estar offline falla por lo que el script con una peticion asociada a criterio ec se aborta.
En los resultados indica que los scripts se deben planificar correctamente.

Tenemos entendido que si enviamos una solicitud a una memoria desconectada el script debe fallar y se debe quitar de los criterios a la memoria. Esto ocurre con todos los criterios? Tanto para EC SHC y SC ? 

Es correcto lo que estamos haciendo?

Saludos

**Comment by gastoncastineira** [comment]
Buenas

Referencio al issue #1433 que explica lo que estás preguntando

Cualquier duda volvé a escribir!

**Comment by franferron07** [comment]
Genial, gracias. Al leer esa respuesta me queda claro que tengo que pasar a la proxima linea y no tengo que abortar el script.

En el caso de que no tengo ninguna memoria asociada al criterio solicitado en la request tambien debo pasar a la siguiente linea no?

**Comment by gastoncastineira** [comment]
Así es caballero

**Comment by franferron07** [comment]
Genial, gracias.
