### ISSUE TITLE
Consulta malloc de la memoria

### ISSUE THREAD

**Issue by micayeza** [sisoputnfrba/foro#1465]
Hola chicos!
Tengo una dudas sobre si encare bien la memoria. 
Luego del gran malloc tengo una estructura de tipo:
int timestamp, void* value e int key.
A traves del memmove guardo las values que me van llegando.
Esto es acorde a lo que dice el enunciado? Hace tiempo publique una duda similar https://github.com/sisoputnfrba/foro/issues/1393

Gracias!

**Comment by gastoncastineira** [comment]
Está medio en un limbo. Si bien el enunciado no te dice que no lo hagas así, dimos bastantes comentarios en el foro y hasta una publicación en el blog diciendo que eviten los punteros para el value.

Digo en un limbo y no un rotundo no porque depende de cómo lo hayas hecho. Supongamos que tenés un registro con los valores de ts 123, key 1 y value 0x456 (porque es un puntero y apunta a una dirección de memoria), y el contenido de esa dirección es "asd". En la duda similar explicabas que calculás el desplazamiento para acceder al marco y conseguir el registro, que está perfecto. Pero cuando vas a guardar el registro en el gran malloc, estás guardando el valor del puntero (osea, 0x456) o el valor de lo que está apuntando ("asd")? Si la respuesta es lo primero, está mal por algo que expliqué en #1352. Si la respuesta es la segunda, está bien aunque probablemente te estés matando con los memcpy para meter y sacar los value

**Comment by micayeza** [comment]
Hola! gracias gastin, sisi es la segunda. No habia encontrado ese issue, voy a ver si puedo adaptar mañana a un char* inicial con un gran malloc, e ir appendeando todo. De esta manera tengo un único puntero, manejo todo como string y vería como me muevo dentro de la memoria... 
correcto?

**Comment by Dragonflares** [comment]
Tengo una duda sobre esto, no?

> Hola! gracias gastin, sisi es la segunda. No habia encontrado ese issue, voy a ver si puedo adaptar mañana a un char* inicial con un gran malloc, e ir appendeando todo. De esta manera tengo un único puntero, manejo todo como string y vería como me muevo dentro de la memoria...
> correcto?

Si estás usando un char* para la memoria principal, y usas string_append, o strcat, no estás manteniendo la idea de frames, porque strcat y string_append te lo agregan al final del string anterior, entonces te quedarían frames de tamaño variable.
Entonces, ahí usar string_append o strcat no sería viable cuando memcpy si por el tema de que te permite elegir en dónde empezar a escribir

Por otro lado

> Luego del gran malloc tengo una estructura de tipo:
> int timestamp, void* value e int key.

Por qué value es un void*? Cuando un value en si es siempre un char*, si te llegara con números sigue teniendo que almacenarse como un char* (Por eso justamente las "comillas" que ponene en los scripts)

Me gustaría saber si mis razonamientos son correctos
Y espero que sirva

**Comment by gastoncastineira** [comment]
No. No dije eso pero ni remotamente xD
sumado a lo que dijo @Dragonflares , pensá que si tipás tu gran malloc a char* estaría incumpliendo el enunciado porque el TS y key no son strings y no debés convertirlos a eso tampoco. Además, seguís teniendo un puntero en tu t_registro que es lo que queremos evitar!

Te voy a decir como le dije a todos mis grupos que lo hicieran cuando se dieron cuenta que el puntero no se podía. Tomalo como referencia, no como una orden de hacerlo así :P 

Vos en estos momentos tenés lo siguiente (ponele):
```
struct t_registro{
 uint64_t ts
 uint32_t key
 char* value
};
```
Como ya quedamos todos de acuerdo que puntero ese no va (y decime si no lo estamos), tenemos un problema. Queremos que la estructura quede definida con un value de tamaño variable, el cual viene de LFS en runtime, por lo que queremos tener algo como lo que sigue:

```
int tam_max = LFS_dame_el_tamanio(); //variable global

struct t_registro{
 uint64_t ts
 uint32_t key
 char value[tam_max]
};
```
Esto no no compila. Te tira un error diciendo que tam_max cambió en el scope del archivo
Si bien creo que otros ayudantes están más capacitados para explicar esto, tengo entendido que es porque el código del programa que corras queda en un segmento de solo lectura, y los valores de las cosas globales tienen que entrar definidos de ahí. Las funciones por ejemplo son globales y su comportamiento viene definido del archivo fuente. Acá me tira el error porque estoy diciendo que la variable global al momento de iniciar el proceso vale algo que se consigue en runtime, y por lo tanto el compilador no me lo puede dejar pasar porque sabe que no se va a poder. setearlo en el main tampoco sirve porque entonces la estructura no está quedando definida en tiempo de compilación y también me rebota el compilador.

Entonces, ¿qué hacemos para salvar este naufragio? Bueno, yo propongo lo siguiente:

```
struct t_registro{
 uint64_t ts
 uint32_t key
 char value[]
};
```

Ese char[] es un array de dimensión cero (osea, sin elementos). Creo que tenía un nombre más formal pero no lo estaría recordando ahora.
La particularidad que da ese array es que cuando yo hago sizeof(char[]) me va a devolver cero porque, claro, ¡no tiene elementos!.
¿Por qué C me deja compilar algo que me va a tirar seg fault siempre que lo use entonces? Desglosemos un poco la idea.
Sabemos que los arrays por atrás compilan a punteros que apuntan a algo que queda definido en el stack del proceso en el mismo segmento que el array (o por lo menos ahora lo sabemos), motivo por el que no hay que hacerles free().
Si yo declaro una variable tipo t_registro, solo voy a poder utilizar ts y key porque mi value tiene largo 0 siempre. Peeeeeeeeeero, ¿qué pasa si hago lo siguiente?

`t_registro* reg = malloc(sizeof(t_registro) + max_value)`

el compilador va a acomodar la memoria para asignársela a ts y key, y va a ver que le sobra un cacho. Normalmente eso significa que tengo un array y puedo moverme con reg[0], reg[1], etc, pero acabámos de decir que los array apuntan a algo dentro de su mismo segmento ¿no? 
Entonces el compilador se va a dar cuenta de esto, y va a saber que los primeros 12 bytes (los 8 de ts y 4 de key) corresponden a los dos primeros registros de la estructura, mientras que todo el resto que le asignes va a corresponderle a ese array de dimensión cero.
Tiene ciertas limitaciones trabajar con esto, como por ejemplo no puedo tener un array de registros porque el value pisaría los ts y key de otros índices, o que si pongo primero el value la definición de esa estructura el compilador no se da cuenta y estaría pisando cosas dentro del mismo registro.

Creo que yo que para lo que necesitamos para este TP calza perfecto

**Comment by micayeza** [comment]
Hola! Gracias por toda esa explicación, quedo re claro :D
Ahora si se donde no estaba muy fino mi tp ajaja
muchas gracias!
