### ISSUE TITLE
Putty en MAC

### ISSUE THREAD

**Issue by jsarrelli** [sisoputnfrba/foro#1466]
Chicos tengo una duda a la hora de querer instalar el putty en la mac para poder testearlo. Seguí lo pasos de la pagina oficina de putty pero siempre termino en el mismo error.

Alguno sabe que puede ser?

<img width="571" alt="Screen Shot 2019-07-24 at 19 34 50" src="https://user-images.githubusercontent.com/18368538/61833307-49c57100-ae4a-11e9-97bf-3422ec5e42a0.png">

**Comment by mgarciaisaia** [comment]
¡Aloha!

En general, usamos `PuTTY` como forma de conseguir un `ssh`.

El comando "que querés" es `ssh utnso@${LA_IP_DE_LA_VM}` desde una Terminal, y ya.

PuTTY después te agrega eso de guardar las configuraciones y tener una ventanita de la que elegir a dónde conectarte, pero meh. Y, buen, eso lo podés hacer laburando con tu `~/.ssh/config`. Pero no creo que quieras meterte ahí por ahora.

Debe haber forma de hacer andar PuTTY, pero un poco nos excede, y bastante no hace falta.

**Comment by jsarrelli** [comment]
Perfecto! Muchas gracias
