### ISSUE TITLE
Duda con el SELECT en Memoria

### ISSUE THREAD

**Issue by IvanDL95** [sisoputnfrba/foro#1467]
Estoy teniedndo una duda con el enunciado, es algo relacionado con la API. En el apartado de Lissandra se hace la siguiente aclaración.

> Cuando la operación se realiza por consola, los valores que normalmente este módulo retorna por sockets deberá imprimirlos por pantalla.

En el caso del SELECT en el útlimo paso dice que se retorna el valor correspondiente. Esto sería, imprimir por consola si la request fue por consola o responder al cliente (la memoria que la realizó) que le envió la request.

El tema es que estoy con el apartado de Memoria y no hace esa aclaración. Sólo dice "Si la contiene, devuelve su valor y finaliza el proceso.". Fijandome en el apartado del Kernel acerca de la API sólo dice:

> Los primeros cinco comandos *(incluye al SELECT)* cuando sean solicitados al Kernel serán directamente redireccionados a la memoria elegida por el criterio de la tabla en cuestión.

El tema es que cuando el Kernel envía un SELECT se puede interpretar como:

A) Se repseta la misma aclaración hecha en Lissandra, **la memoria elegida no lo imprime por consola** y se devuelve al Kernel el valor para que este sí lo imprima. 

B) No se devuelve nada al Kernel, ya que todo lo redirige a una memoria según el respectivo criterio de la tabla sobre la cual se realiza la consulta, y **la memoria elegida** imprime el valor por consola (ya sea si existe en dicha memoria o si se hace la request a Lissandra para que le devuelva el valor como se aclara anteriormente).

Nosotros lo tenemos implementado de la forma B. Cuando hicimos el checkpoint presencial no surgió esta duda y no estoy seguro de si estaba bien o no. No fue algo que los ayudantes pusiesen énfasis o sí da lo mismo siempre y cuando se realizen los pedidos de forma correcta.

Esto me frena bastante ya que, si bien lo que estuvimos haciendo nosanda bien y al correr las pruebas nos funciona correctamente, tendriamos que cambiar un par de cosas con respecto a como responde la API y se comunican los procesos entre sí.

**Comment by gastoncastineira** [comment]
Lo lógico sería que si yo te hago una operación en un módulo pueda ver el resultado desde el mismo. Acá porque las computadoras están una al lado de la otra, pero sería muy incomodo tirar un select en el laboratorio azul y tener que ir al rojo a ver el resultado, en un caso hipotético.
Si ves que podés cambiarlo para la entrega perfecto. Si no llegan, vemos si nos la podemos arreglar

**Comment by IvanDL95** [comment]
Muy bien, lo trataremos de arreglar. Gracias por la respuesta.
