### ISSUE TITLE
Duda tamaño value

### ISSUE THREAD

**Issue by micayeza** [sisoputnfrba/foro#1468]
Hola! una duda rapida. 
Quisiera saber a que considerar parte del tamaño del value.
En caso de que venga "Perro"
a) El tamaño seria 5 (solo consideranlo las letras)
b) 7 (Letras mas comillas)
c) 6 (letras mas \0)
d) 8 (comillas letras + \0)

En los bloque es debe guardar con las comillas?
Gracias!

**Comment by gastoncastineira** [comment]
El tamaño es 5 y se guarda como perro (sin comillas) en el archivo, pero tené en cuenta que dentro de C necesitás el \0 al final porque sino no podés usarlo como string

**Comment by micayeza** [comment]
Perfecto muchas gracias!
