### ISSUE TITLE
Conexion entre dos VMs Mac

### ISSUE THREAD

**Issue by jsarrelli** [sisoputnfrba/foro#1469]
Chicos, tengo un problema a la hora de querer probar en mis computadoras.
Estoy teniendo tres macs conectadas bajo la misma red configuradas con Bridge Adapter (adaptador Puente) y en las tres corro el Lubuntu Server.
El problema esta en que la conexión entre ellas es increíblemente lenta, estuve buscando en internet y se ve que es un problema que tiene virtualBox, pero no encuentro ninguna solución.

Alguno sabe o le paso esto?
Gracias!

**Comment by iago64** [comment]
Buenas buenas!
Que version de virtual box estas usando? Si es la version 6.0, es posible que venga por ese lado, viene dándonos varios dolores de cabeza desde principio del cuatrimestre :(

Sobre que SO estas corriendo virtual box?

Abrazo!

**Comment by jsarrelli** [comment]
Estoy con la 5.2.26

**Comment by iago64** [comment]
Sigo con las preguntas a ver si encuentro algún denominador común, cuando estas poniendo de ram en la vm? Y cuanto tenes en la pc? Para evitar que estés teniendo una cantidad de swap enorme

**Comment by jsarrelli** [comment]
La pc tiene 16 de ram, le estoy dando 1GB al Lubuntu Server.

**Comment by mgarciaisaia** [comment]
Che, tampoco es que es la muerte 20ms. ¿O sí? Tu TP debería andar con 20ms de ping, eh.

¿Tenés algunos links para compartir de lo que encontraste en la internet?

Podés probar `iperf`, también, para ver cómo está el ancho de banda entre dos VMs, por si el mambo viene por ahí.

**Comment by iago64** [comment]
ah para... la lentitud era por 20ms de ping? pense que estabamos en ordenes de timeout... si es por eso, no te preocupes... posiblemente la red del laboratorio sea mucho mas lenta el dia de la entrega :)

**Comment by NaylaWinter** [comment]
@jsarrelli se resolvió el problema? Te podemos ayudar con algo mas?
Te pido sino si podes cerrar el issue, gracias!
