### ISSUE TITLE
Bloqueo LFS Memtable

### ISSUE THREAD

**Issue by martinzuccotti** [sisoputnfrba/foro#1470]
Buenas!

Estamos ajustando la sincro del FileSystem y tenemos la siguiente duda: 
Cuando vamos a hacer un dump necesitamos bloquear la memtable para que no se inserten nuevos registros. En nuestro caso, si no hacemos esto, al finalizar el dump y vaciar la memtable podríamos estar borrando registros que no se dumpearon.

La solución que se nos ocurre es poner un semáforo de lectura-escritura pero en el enunciado dice que "Dentro del sistema las tablas únicamente pueden quedar bloqueadas mientras se realiza el proceso de compactación". Podemos bloquear la memtable en este caso?

**Comment by Dragonflares** [comment]
Buenas!

A ver, voy a tirarte por ahí una lógica que cualquier ayudante puede llegar a contradecirme pero que es posiblemente la válida. La memtable no es una tabla particular, ni está involucrada en la compactación. Entonces "bloquear la memtable durante la lectura/escritura" es válido porque no es una tabla de las que habla el enunciado. Depende mucho también de como la hayas implementado; si fuera una lista, por ejemplo, lo lógico sería utilizar ese mutex para que nadie escriba hasta que termines de dumpear o hasta que escribas la key que te acaba de llegar, es más por el tema de no generar condiciones de carrera(si mal no estoy). Además, si no bloquearas, tendrías un milisegundo de inconsistencia donde una key por ahí llega durante el dump y no se dumpea porque ya dumpeaste las keys de la tabla a la que iba, y cuando limpias la memtable esa key deja de existir y de golpe el script tira que la key no existe! 
De vuelta, no soy ayudante, pero poner el mutex ese no me parece mal.

Saludos y espero que te sirva.

**Comment by SofiCortes** [comment]
Buenas!

Cualquier estructura que se pueda acceder concurrentemente debería estar sincronizada, porque puede derivar en condiciones de carrera. Como bien dice @Dragonflares, la memtable no la consideramos como una "tabla" y una posible solución es la que plantea.

Saludos!

**Comment by martinzuccotti** [comment]
Hola! 

Genial! Justamente esa inconsistencia que mencionás (@Dragonflares) de cuando haces el dump vs cuando vacias la memtable (y otras situaciones similares) era la razón de la consulta.

Lo que no tenía claro era a que se refería el enunciado cuando hablaba de que no había que bloquear las tablas excepto para compactación.

Gracias a los dos! Cierro el issue
