### ISSUE TITLE
Busqueda de Integrante - TP 2C 2019

### ISSUE THREAD

**Issue by pachecomariano** [sisoputnfrba/foro#1472]
Hola,

Se busca 1 integrante  para terminar de formar el grupo de TP de Operativos (hasta ahora somos 4 y cursamos sabado por la mañana) En lo posible que cumpla los siguientes requisitos:

Que este cursando pocasmaterias (si solo cursa operativos, mejor aun)
Que sepa programar
Que pueda reunirse en Campus los dias sabados a partir de las 13.
Si es recursante mejor

Gracias,
Mariano.

**Comment by norbersanabria** [comment]
hola Mariano, comunicate conmigo por mail nasanabria@gmail.com, curso los sabados a la tarde en campus, supongo que no debe haber problema en cambiar y cursar a la mañana, saludos

**Comment by gonza-utn** [comment]
Hola como estas! no sabia que cerraba.. les falta un integrante??
mi nro de Wpp 1166548389
(soy del curso de martes a la noche -Masoero)
Por favor contáctenme 

Gracias.
