### ISSUE TITLE
Buscamos 2 integrantes TP 2C 2019

### ISSUE THREAD

**Issue by benjamd** [sisoputnfrba/foro#1473]
Hola! aun nos faltan 2 integrantes, cursamos los sábados por la tarde en campus, queremos completar el equipo con gente tenga fluidez en la comunicación y que asuma el compromiso de juntarse en la semana en el laboratorio de Medrano y/o domingos por la zona.

**Comment by pacoDan** [comment]
Hola, curso los Martes a la mañana y dispongo para estar en medrano(ademas de todos los sábados todo el dia), mi mail:  jhondanielpaco@gmail.com , 
soy recu y en el anterior cuatri estaba más enganchado con el tema de file system

**Comment by norbersanabria** [comment]
Curso SO los sabados a la tarde en Campus, mi mail nasanabria@gmail.com enviame un mail asi nos ponemos en contacto
