### ISSUE TITLE
Buscando grupo - TP2C 2019

### ISSUE THREAD

**Issue by tuxtron1234** [sisoputnfrba/foro#1474]
Hola!

Somos 2 personas en busca de algun grupo.

Cursamos los sabados a la mañana.

Edit: Gracias ya creamos un grupo

**Comment by afviola** [comment]
Buenas,

tambien estoy buscando grupo. Curso los viernes a la noche y soy recursante. Si les parece nos juntamos

Dejo mail: fdviola93@gmail.com

**Comment by gfrey-utn** [comment]
Hola!
También estoy en búsqueda de un grupo. Curso sábados a la mañana.
Mail: reygastonf@yahoo.com.ar

**Comment by angelluisgo** [comment]
Hola!
Estoy en búsqueda de un grupo. Curso miércoles a la noche.
Mail: angelluisgo@gmail.com

**Comment by xyz-frba** [comment]
Buenas,
También somos dos personas en búsqueda de grupo y cursamos los sábados a la mañana.

**Comment by ospocarpa** [comment]
Buenas j
  junto a tuxtrom estamos buscando grupo. Cursamos sabado a la mañana mi mail es : oscarhinnojosa@gmail.com

**Comment by angelluisgo** [comment]
Buenas tardes, 
Estoy buscando grupo les dejo mi email: angelluisgo@gmail.com
Estoy cursando los miércoles a la noche (Adriano)
