### ISSUE TITLE
Búsqueda de 3 integrantes!

### ISSUE THREAD

**Issue by MicaFesta** [sisoputnfrba/foro#1475]
👋 ¡Hola!

Estamos buscando tres integrantes para el grupo de SO. Porfa dejen su mail o celu así podemos contactarlos.
No importa si es la primera vez que cursan, la idea es que sepan programar, y sean curiosos (ganas de romperse la cabeza hasta que ande jaja) y quieran aprobar sí o sí! Es cuestión de compromiso!

🙇 Gracias por leernos!

**Comment by hivarra** [comment]
Hola! No tengo grupo todavía, algo entiendo de programación aunque no soy experto. Curso los sabados a la mañana. 1131938524

**Comment by Mati-Jurado** [comment]
Buenas! Te mande un mail hace un rato! Somos 2.

El creo que labura programando y yo se java, y algo de c++ y ansi c de cursadas.

 Te dejo mi nro 11 6004 6715

Slds!

**Comment by ReggiardoJuan** [comment]
Buenas, todavía no tengo grupo y la estoy cursando los viernes a la noche. Entiendo de JS más lo que se ve en cursadas anteriores.

1162294914

**Comment by Maguirios** [comment]
Hola todavía no tengo grupo, Es mi primera cursada, curso los sábados a la tarde y se programar en JS 
1168194712

**Comment by jpvispo** [comment]
Estoy en la misma, había arreglado con dos más pero me dejaron de garpe por formar un grupo del mismo curso. Soy recursante y me desenvuelvo en c y me comprometo a mterle para aprobar el tp. Curso los viernes a la noche.  01158203950.

**Comment by Britanico10** [comment]
1130426096. Curso solo SO.

**Comment by FrancoMondu** [comment]
1123983358. Hola ando buscando grupo, curso los sabados a la mañana, y no tengo problemas en C.

**Comment by gonza-utn** [comment]
Hola como estas! no sabia que cerraba.. les falta un integrante??
mi nro de Wpp 1166548389
(soy del curso de martes a la noche -Masoero)
Por favor contáctenme 

Gracias.

**Comment by MicaFesta** [comment]
Chicos, ya estamos completos!
