### ISSUE TITLE
Búsqueda de integrantes para el TP - Faltan 2

### ISSUE THREAD

**Issue by clu3dfx** [sisoputnfrba/foro#1476]
Hola, buen día,

Estamos buscando 2 integrantes para el grupo.
Nosotros somos 3 recursantes.

La idea es integrar al grupo alguien comprometido con aprobar la materia, preferentemente recursantes también, así podemos avanzar más rápido.

Sobre nosotros:
Yo estoy cursando Sistemas Operativos los viernes a la noche.
Las otras 2 personas están cursando Sistemas Operativos los miércoles a la noche.

Dejo mi mail y teléfono así estamos en contacto (o pueden responder directamente este post):
claudiohluciano@gmail.com
1150496990

Saludos!
Claudio.

**Comment by gonza-utn** [comment]
Hola como estas! no sabia que cerraba.. les falta un integrante??
mi nro de Wpp 1166548389
(soy del curso de martes a la noche -Masoero)
Por favor contáctenme 

Gracias.
