### ISSUE TITLE
Nos falta el 5to miembro - equipo de recursantes

### ISSUE THREAD

**Issue by eabergese** [sisoputnfrba/foro#1477]
Buenas,

Estamos buscando un último integrante que ya haya cursado la materia y este cuatrimestre este cursando solo sisop o junto con alguna otra bien light. 

Los 4 cursamos los sábados a la mañana con Natasha y pensamos quedarnos dsps de clase todos los sábados para meterle desde el día cero y llegar a la primer entrega.

Somos todos recursantes de la materia y programadores en nuestro laburo.

Cualquier cosa me escriben a bergese.ezequiel@gmail.com

Muchas gracias.

Saludos.

**Comment by gonza-utn** [comment]
Hola como estas! no sabia que cerraba.. les falta un integrante??
mi nro de Wpp 1166548389
(soy del curso de martes a la noche -Masoero)
Por favor contáctenme 

Gracias.
