### ISSUE TITLE
Busco grupo

### ISSUE THREAD

**Issue by FrancoMondu** [sisoputnfrba/foro#1481]
Hola, busco grupo, soy recursante y curso los sabados a la mañana.
francomondu@gmail.com

**Comment by eabergese** [comment]
Buenas,

Nosotros cursamos a la mañana tambien y nos falta uno, te escribo al mail y hablamos por whatsapp.
Saludos.

**Comment by FrancoMondu** [comment]
Hola, mi numero es 1123983358, hablame ahi.



Enviado desde mi smartphone Samsung Galaxy.


-------- Mensaje original --------
De: eabergese <notifications@github.com>
Fecha: 7/9/19 17:41 (GMT-03:00)
A: sisoputnfrba/foro <foro@noreply.github.com>
CC: FrancoMondu <f_r_c_m@hotmail.com>, Author <author@noreply.github.com>
Asunto: Re: [sisoputnfrba/foro] Busco grupo (#1481)


Buenas,

Nosotros cursamos a la mañana tambien y nos falta uno, te escribo al mail y hablamos por whatsapp.
Saludos.

**Comment by gonza-utn** [comment]
Hola como estas! no sabia que cerraba.. les falta un integrante??
mi nro de Wpp 1166548389
Por favor contáctenme 

Gracias.

**Comment by gonza-utn** [comment]
Hola como estas! no sabia que cerraba.. les falta un integrante??
mi nro de Wpp 1166548389
(soy del curso de martes a la noche -Masoero)
Por favor contáctenme 

Gracias.
