### ISSUE TITLE
Reconocimiento de variable LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by Santiago-Lovelli** [sisoputnfrba/foro#1483]
Hola gente, tengo problemas al querer incorporar la variable LD_LIBRARY_PATH al .bashrc como se hace en el vídeo de youtube (https://youtu.be/s5ac8CPDkMg).
Lo agrego al .bashrc pero cuando lo quiero correr desde consola no me lo reconoce, pero si lo hago desde eclipse en el run config si.
Como podría solucionarlo?
Consola:
<img width="960" alt="Consola" src="https://user-images.githubusercontent.com/40477288/64874588-b7f40c00-d621-11e9-95b2-c23eaa7e5a5f.PNG">

Eclipse:
![image](https://user-images.githubusercontent.com/40477288/64874668-e96cd780-d621-11e9-8652-0c7f94d75491.png)

**Comment by mgarciaisaia** [comment]
¡Hola, @Santiago-Lovelli!

El `.bashrc` es un archivo con comandos bash que se ejecutan al abrir una terminal. De esto se desprenden dos cosas: 1) para que haga efecto, tenés que abrir una nueva terminal _después_ de haber actualizado el archivo; y 2) en las terminales que ya tengas abiertas podés ejecutar "a mano" esos mismos comandos, y debería surtir el mismo efecto.

En particular, acá te está interesando hacer el `export` de la variable de entorno `LD_LIBRRARY_PATH`. Podés ver el estado de esa variable en una terminal dada ejecutando el comando `env` (que lista todas las variables de entorno, con sus valores), o bien podés mirar esa específicamente haciendo `env | grep LD_LIBRARY_PATH` (para filtrar la lista anterior).

Contanos cómo anduvo.

**Comment by Santiago-Lovelli** [comment]
Perfecto, no sabia que tenia que abrir una nueva consola.
Una duda extra que no se si corresponde al alcance de lo pedido, si yo quisiera utilizar mas de una biblioteca compartida, puedo repetir la sentencia dando mas de un valor a la variable (repetir la linea del archivo pero con otro valor en la variable) o debo organizar las bibliotecas dentro de un mismo directorio y ese directorio dárselo como valor a la LD_LIBRARY_PATH?

**Comment by mgarciaisaia** [comment]
¿Probaste ejecutar varias sentencias parecidas?

Acordate que, en computación, muchas veces nos resulta re barato llevar a cabo un experimento para probar una idea que tengamos. En un caso chico como este, lo que más tiempo y esfuerzo te va a llevar es _diseñar_ el experimento - pero la ejecución va a ser bastante simple.

Probá, sacá tus conclusiones, y compartilas a ver qué aprendemos.

**Comment by Santiago-Lovelli** [comment]
Hola, estuve tocando cosas del .bashrc y con eclipse, creando otra shared library y me di cuenta que desde eclipse si quiero agregar otra LD_LIBRARY_PATH me dice que lo reescribe, pero aun asi lo toma, como si si alguna vez que se implemento ya sabe donde esta, lo mismo desde el .bashrc, si existe almenos un:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/utnso/workspace/tp-2019-2c-SuperandO/ComunParaTodos/Debug
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/utnso/workspace/MasDeUno/Debug
Como que registra ambos, mientras que si elimino ambos export no reconoce ninguno. No se que magia rara hace en el medio el .bashrc, pero con agregar los export o reescribir la variable en eclipse entiendo que ya funcionara para todo programa que quiera usarlo. 
Lo que si al hace el ldd nombreDePrograma sale la direccion del ultimo export realizado (o agregado al .bashrc)

**Comment by mgarciaisaia** [comment]
Je, el truco está en la parte de `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:[...]`.

Al hacer `LD_LIBRARY_PATH=` lo que estás haciendo es asignarle un nuevo valor a la variable de entorno `LD_LIBRARY_PATH`. ¿Qué valor? Buen, el resultado de computar lo que está a la derecha del `=`.

Asumamos que en una consola "limpia" ejecutás `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/utnso/workspace/tp-2019-2c-SuperandO/ComunParaTodos/Debug`.

La variable `LD_LIBRARY_PATH` por defecto no está declarada, entonces `$LD_LIBRARY_PATH` va a resolver a _vacío_. Entonces te queda el equivalente a `export LD_LIBRARY_PATH=:/home/utnso/workspace/tp-2019-2c-SuperandO/ComunParaTodos/Debug`.

En Linux, `:` es el caracter separador de listas. Entonces tu `LD_LIBRARY_PATH` termina siendo una lista con dos valores: _vacío_, y `/home/utnso/workspace/tp-2019-2c-SuperandO/ComunParaTodos/Debug`.

Cuando ejecutás la segunda línea (`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/utnso/workspace/MasDeUno/Debug`), ahora cambia la cosa: `$LD_LIBRARY_PATH` ya no resuelve a _vacío_, si no a una lista con vacío y un path. Y a eso se le concatena este otro path que agregás en el comando. Es decir, es el equivalente a hacer `export LD_LIBRARY_PATH=:/home/utnso/workspace/tp-2019-2c-SuperandO/ComunParaTodos/Debug:/home/utnso/workspace/MasDeUno/Debug` - una lista con _vacío_, y dos paths.

Por eso el linker sabe encontrar las dos bibliotecas (y de algún modo termina ignorando el path vacío, o intentará buscar en _vacío_ y no resuelve a nada 🤷‍♂

El corolario de todo esto es que tranquilamente podrías hacer un único `export` con ambas rutas: `export LD_LIBRARY_PATH:$LD_LIBRARY_PATH:/home/utnso/workspace/tp-2019-2c-SuperandO/ComunParaTodos/Debug:/home/utnso/workspace/MasDeUno/Debug`.

**Comment by Santiago-Lovelli** [comment]
Perfecto, gracias

**Comment by tmerchan** [comment]
Hola, vuelvo a abrir el issue para preguntar:
"El corolario de todo esto es que tranquilamente podrías hacer un único export con ambas rutas: export LD_LIBRARY_PATH:$LD_LIBRARY_PATH:/home/utnso/workspace/tp-2019-2c-SuperandO/ComunParaTodos/Debug:/home/utnso/workspace/MasDeUno/Debug."

Es posible hacer eso en eclipse? Porque no lo estoy logrando

**Comment by mgarciaisaia** [comment]
Es posible.

¿Qué estás intentando? ¿Qué error tenés?

**Comment by tmerchan** [comment]
Tengo un proyecto cliente de prueba que tiene un include "libMUSE.h" y un include "mi_biblioteca.h". Ambas son shared libraries, en la segunda pusimos funciones del protocolo de comunicación nuestro y algunas otras cosas comunes al resto de los procesos para no repetir código. El proyecto compila perfectamente y si además haces clic + ctrl a cualquiera de los includes, te lleva a sus ubicaciones. El problema está cuando quiero correr el proyecto, me tira "error while loading shared libraries: liblibMUSE.so: cannot open shared object file: No such file or directory". Si en el LD_LIBRARY_PATH pongo la ubicación, me dice lo mismo pero con mi otra libreria. Se pisan mutuamente, pero no me deja ponerlas juntas. Que debo hacer?

**Comment by mgarciaisaia** [comment]
Tendría que ver algo más preciso (por ejemplo, un `echo $LD_LIBRARY_PATH`, para ver qué valor tiene tu variable) para estar 100% seguro, pero en principio lo que tenés que hacer es esto que hablábamos arriba: que tu `LD_LIBRARY_PATH` tenga ambas rutas.

En Eclipse, en el Run Configuration que mostró Santi en el primer post (segunda captura de pantalla), donde define `LD_LIBRARY_PATH` tendrías que poner como valor `/directorio/de/libmuse:/directorio/de/tu/biblioteca`.

Cuando yo era joven había un video de ~20 minutos Gastón Prieto que ~susurraba~ contaba cómo configurar proyectos con shared libraries en Eclipse, usando la variable de Eclipse `${workspace_loc}` para definir la ruta a tu biblioteca, y rutas absolutas para la otra biblioteca. Capaz tu caso es similar.

Bah, no estoy seguro - ¿dónde está/va a estar la libmuse?
