### ISSUE TITLE
Extension de archivo config

### ISSUE THREAD

**Issue by lucasvalenzuela93** [sisoputnfrba/foro#1484]
Buenas, estamos en una duda con mi grupo, nosotros tenemos como extension de los config .txt, pero en tps anteriores se usaba .config, nuestra duda, cual usamos?

**Comment by tferraro** [comment]
Buenas!

Es indistinto, las extensiones solo son informativas en Linux 🙂

**Comment by lucasvalenzuela93** [comment]
Gracias!

**Comment by mgarciaisaia** [comment]
¡Aloha!

No solo, como dice Tom, en Linux _las extensiones de archivo son los padres_*, si no que, en el caso puntual de los archivos de configuración (hay otros casos, también) en Windows tampoco te importaría la extensión.

**¿Cómo sabe tu programa qué archivo de configuración leer?** Bueno, porque en algún momento llamás a la función `config_create`, diciéndole qué archivo leer.

Y, además, la función sólo soporta un único _formato de archivo_: siempre espera líneas con clave y valor separado por un signo igual. No podés elegir, ponele, pasarle la configuración en formato JSON, simplemente porque la función va a buscar líneas de clave-valor separadas por un igual.

Bah... _Podés_ pasarle un JSON. Pero la función va a buscar clave-valor separado por un igual.

Entonces, volviendo: ¿A quién le importa si la extensión del archivo es .txt, .conf, .config o .jpg? A tu programa seguro que no. Mientras le pases una ruta correcta a un archivo de líneas clave-valor separados por un signo igual, tu programa va a andar (asumiendo un montón de otras cosas más, obvio, aunque no tan relacionadas con el archivo de configuración).

Pero pero pero... A vos quizá sí te interese la extensión de tu archivo. Y a otros programas también.

Por ejemplo, si tu archivo de configuración tuviera extensión .jpg, hay un montón de expectativas al respecto. Un@ como usuari@ espera, en general, que un archivo .jpg contenga una imagen en formato JPEG. Es una convención, puede que incluso sea parte de algún estándar o especificación (no lo chequeé), pero ya que sea una convención alcanza para tener expectativas.

Más aún, los sistemas operativos (o sus interfaces gráficas) suelen tener mecanismos que asocian ciertos tipos de archivos conocidos con programas que pueden operar con ellos. Entonces, en general, un@ espera poder clickear el icono que representa a un archivo con extensión .jpg y que el sistema operativo (o su interfaz gráfica) ejecute el programa asociado (por lo general, un visor o editor de imágenes) y cargue el archivo seleccionado. Hoy en día no es muy frecuente (excepto en los celulares, que tienen usabilidad bastante distinta) abrir el visor de imágenes, y desde ahí adentro elegir qué archivo ver - se puede, sí, pero en general directamente "abrimos la imagen".

Entonces en esos archivos capaz sí importa un poco más la extensión. La diferencia entre esos y los archivos de configuración nuestros es, quizá, que el archivo de imagen suele ser el objetivo por el que abrimos el visor de imágenes, mientras que el archivo de configuración suele ser más de soporte - no es nuestro objetivo abrir un archivo de configuración, si no hacer andar el sistema (que necesita leer su configuración para funcionar como esperamos).
