### ISSUE TITLE
[PLANIFICACIÓN] Posible creación de semáforos

### ISSUE THREAD

**Issue by nicolaslazo** [sisoputnfrba/foro#1485]
Buenas,

Empezando con la implementación de SUSE me surgió una duda: la cantidad de semáforos que maneja es fija (siendo esta la especificada en el archivo de configuración)? Porque hasta donde se ve en la consigna no hay ninguna manera de instanciar uno nuevo, y si realmente se pudiese hacer a piacere la idea de crear un grupo de ellos en esta configuración no tendría mucho sentido.

**Comment by gastoncastineira** [comment]
Buenas

Efectivamente es así! La cantidad de semáforos es fija. Si mirás el ejemplo de archivo de configuración vas a ver que hay tres registros con toda la info de los semáforos que tendrá el sistema.

**Comment by nicolaslazo** [comment]
Perfecto, muchas gracias!

**Comment by gastoncastineira** [comment]
Perfecto! Si no tenés más dudas te pido por favor que cierres el issue
