### ISSUE TITLE
Duda sobre creación de proyecto Clion 

### ISSUE THREAD

**Issue by emiortiz** [sisoputnfrba/foro#1486]
Hola, como andan? 
Estuve creando el proyecto para el TP en Clion y me surgido una duda. En las opciones para la creación esta la opción del lenguaje standard que puede ser C11, C99 y C90. Alguno tiene idea de que opción  es la correcta para el TP? 

<img width="960" alt="VirtualBox_Operativos amigo_17_09_2019_16_54_24" src="https://user-images.githubusercontent.com/38117993/65075666-bd2cc000-d96d-11e9-8ccd-717922348cb2.png">

**Comment by iago64** [comment]
Aloha!!

El estándar es C99

Abrazo!

**Comment by emiortiz** [comment]
Buenísimo, muchas gracias!
