### ISSUE TITLE
Duda sobre asignación de memoria

### ISSUE THREAD

**Issue by Marrieta99** [sisoputnfrba/foro#1487]
Hola. nos surgió una duda leyendo el enunciado. Se explica que utilizaremos el esquema de segmentación paginada, con segmentos de tamaño variable dependiendo de cuantas páginas tenga. 
La cuestión es que en un momento dice _"En caso de que el segmento no pueda extenderse más (porque, por ejemplo, pisaría una dirección virtual de otro segmento), se deberá crear un segmento nuevo"._
¿Esto significa que los frames para un segmento se le asignan de forma continua? Porque es la única forma que se nos ocurrió para que un segmento pueda llegar a pisar la dirección virtual de otro. 
También dice _"Será responsabilidad de cada grupo elegir la disposición que le dará a los segmentos en el espacio de direcciones."_ ¿Esto nos habilita a elegir una estrategia de asignación de frames en la que nunca se choquen los segmentos?

**Comment by gastoncastineira** [comment]
Por lo primero, es así. Los marcos del proceso se asignan de manera contigua para un mismo segmento.

Por lo segundo, me gustaría que me contaras cuál sería esa estrategia

**Comment by Marrieta99** [comment]
Habíamos pensado en estrategias con asignación no contigua. Pero si debe ser contigua entonces los segmentos sí se chocarán entre sí en algún momento.

**Comment by ncoen97** [comment]
> Por lo primero, es así. Los marcos del proceso se asignan de manera contigua para un mismo segmento.
> 
> Por lo segundo, me gustaría que me contaras cuál sería esa estrategia

@gastoncastineira 
Perdón que me meta, me imagino que los marcos de un segmento se van asignando de manera contigua por orden, pero tenía entendido que en segmentación paginada justamente pueden no ser contiguos, total tenes la tabla de paginas para referenciarlos.

**Comment by tferraro** [comment]
Buenas! Creo que no quedó claro del todo la respuesta de Gas, por lo que dice @ncoen97.
Por un lado, los segmentos tienen una cantidad de memoria de tamaño variable, pero contígua. 
Pero hey! Eso solo vale si estamos mirando el segmento, dependerá de que haya abajo como para determinar si la memoria física va a estar contínua!

Los segmentos del tp, dado que están basados sobre la paginación, saben que tienen una asignación continua entre páginas. Sin embargo, esas páginas **no necesariamente se van a asociar a frames contínuos**. De hecho, gracias a eso tenemos swapping!

Como dice un poco el TP, lo que tiene posibilidades de colisionar **es el espacio de direcciones virtuales**, nunca habla de direcciones físicas, guarda ahí.

Ahora, esa conclusión sale de la problemática de "cuando van a colisionar las direcciones virtuales de los segmentos de un programa?". Sobre eso, tengo una re-pregunta, cuántos segmentos suele tener un proceso en la vida real? Y en nuestro TP?

Y particularmente la pregunta (2) que buscas referenciar es: Como se los suele acomodar entre sí en la realidad? Y ahí van a tener un abanico de posibilidades para jugar 🙂

**Comment by FredeHG** [comment]
La verdad me sigue sin quedar claro como pueden colisionar 2 direcciones virtuales. Teniendo en cuenta que en segmentación paginada la dirección virtual tiene el formato nro_segmento + nro_pagina + desplazamiento, y el desplazamiento nunca es mas grande al tamaño de la pagina y el numero de segmento nunca se va a repetir o al menos en nuestra implementación no pasa siguiendo esto tampoco nos pasa que un programa tenga más de un segmento.

**Comment by tferraro** [comment]
El secreto es que tu dirección virtual *es solo un puntero de 32bits*, no tiene "nro de segmento" y **aún menos número de página** (recordá como se componen esas capas de abstracción).

Ahora, estás seguro que un programa **no va a tener más de un segmento**? El TP, al igual que la vida real, implementa varios tipos de segmentos que se tienen que acomodar en el espacio de direccionamiento de un mismo programa. Si bien en la realidad existen muchos tipos de segmentos, en el TP tenemos una cantidad un poco más restringida 😛

**Comment by tferraro** [comment]
_Silencio de misa_ 😆 
@Marrieta99 @FredeHG como viene eso? Contiúan sus dudas sobre este issue?

**Comment by FredeHG** [comment]
Luego de un fin de semana de reflexión, lo de que un programa tiene 2 tipos de segmentos distintos no lo habíamos tomado en cuenta pero, no nos aclara nada es casi un detalle en nuestra duda. 

Primero esos 32 bits de la dirección de donde salen? No encontré nada en el enunciado que me de a entender eso.
 Pero aun con eso las ideas que tenemos son

 Una tabla de segmentos para todos los procesos, entonces asumiendo que solo tengo 32 bits de dirección y que a modo de ejemplo las paginas para el desplazamiento necesitarían 5 bits (En el enunciado la configuración dice 32 bytes, aunque se puede cambiar pero para explicar la idea lo tomamos) me quedarían 27 bits para repartir entre paginas y segmentos, lo cual me da un numero bastante grande, pero de esta forma eventualmente se podrían chocar los segmentos pero no porque el siguiente este en uso si no porque la dirección me obliga a cambiar de segmento. 

 Otra idea es saber de que programa viene la dirección entonces las direcciones se podrían repetir ya que discrimino por otro parámetro. entonces tendría que dar un solo bit para los tipos de segmentos (ya que son 2) y me quedan 26 bits para las paginas y si se me terminan todas esas millones de paginas ya puedo cerrar e irme a dormir porque con 32 bits se termino mí capacidad de direccionamiento

**Comment by tferraro** [comment]
Buenas!

Perdón que colgué un poco esto, me tomé un poco de tiempo para encontrar la mejor forma de formular la respuesta. Seguramente en una futura revisión del TP hagamos alguna aclaración dada las cantidad de dudas respecto de eso.

Ahora, a los bifes:
> Primero esos 32 bits de la dirección de donde salen? No encontré nada en el enunciado que me de a entender eso.

Las direcciones de libmuse, son de 32bits, _porque su interfaz define que los punteros son de tipo `uint32_t`_, es decir, **enteros de 32 bits sin signo**.

> Una tabla de segmentos para todos los procesos, entonces asumiendo que solo tengo 32 bits de dirección y que a modo de ejemplo las paginas para el desplazamiento necesitarían 5 bits (En el enunciado la configuración dice 32 bytes, aunque se puede cambiar pero para explicar la idea lo tomamos) me quedarían 27 bits para repartir entre paginas y segmentos, lo cual me da un numero bastante grande, pero de esta forma eventualmente se podrían chocar los segmentos pero no porque el siguiente este en uso si no porque la dirección me obliga a cambiar de segmento.

Acá hay una distinción entre la implementación real y la teoría de libro. En la realidad, se utilizan una N cantidad de bits para designar segmentos, dado que es la manera más performante de que la MMU pueda distinguir entre ellos; mientras que en la teoría solo se plantea que un segmento va a ser definido por una `base lógica` y un `limite de segmento`. Esta división es por un tema de hardware.
Por suerte, no tenemos las limitaciones de la MMU, por lo que podemos evitar separarnos bits para distinguir a un segmento, **porque nos podemos dar el lujo de hacer la cuenta**.
Veamos un ejemplo práctico:

Escenario de segmentación paginada: `Dirección Lógica -> Dirección Lineal -> Dirección Física`.
#### Tabla de Segmentos del Proceso
| Base | Limite |
| -----|--------|
|   0    |     64    |
|  256 |    4096|

Dado ese escenario, veamos como se ubicarían algunas direcciones de memoria:
35    --> Segmento 0
100   --> Seg Fault
1024 --> Segmento 1

Lo mismo pasa para las páginas, que van a necesitar utilizar esa Dirección Lineal para conseguir la  página asociada 🙂.

Saludos!

**Comment by FredeHG** [comment]
Justo hoy fuimos a soporte. Pero igual el esquema nos va a servir mucho y seguramente le sirva a otras almas en pena que hayan llegado acá. Aunque nos comentaron que van a hacer un anexo también para esté tema.

**Comment by IvanDL95** [comment]
Entonces... no hace falta implementarlo con bits?

El tema es que pregunté que onda eso ya que en todas las consultas al respecto querían implementarlo usando bits, si es que tenía que ser así o podíamos encontrar otra manera. Me dijeron que era lo que "más se apegaba a la teoría" y me acordé esta respuesta:

> Por suerte, no tenemos las limitaciones de la MMU, por lo que podemos evitar separarnos bits para distinguir a un segmento, porque nos podemos dar el lujo de hacer la cuenta.

Yo justamente había tenido la misma idea al respecto. Lo de operar con bits solo lo veía en los ejercicios prácticos, que se apega más a ejemplos de implementación reales, en la teoría solo se explica lo de base y límite. El enunciado nunca aclara cómo es que se debe gestionar, y me quedé con la idea de que, implícitamente, era el famoso gris de ***es responsabilidad del grupo...*** con lo cual dependía de nosotros buscarle la vuelta y poder justificar por qué lo hicimos así.

Hoy me llegaron noticias de que van a aclarar ciertos temas en el enunciado, probablemente entre esto ya que se armó mucho debate al respecto. No sé si querrán que la decisión sea libre o van a terminar "forzando" a que lo hagamos de cierta manera.

**Comment by tferraro** [comment]
Buenas!

Efectivamente como decís, no hay bits reservados para indices de segmento 🙂. No es una decisión forzada, es simplemente que hubo un cierto mal entendido a nivel terminos. 

Por otro lado, exactamente por eso que comentás es que vamos a generar una revisión del enunciado tratando de aclarar estas dudas. Si bien en la teoría solo tenés base y segmento, la pregunta terminó siendo **cual teoría? La del libro o la implementación de ejercicios de la clase de teoría**. Esa fue mala nuestra 😄

**Comment by afilgueira** [comment]
Hola, subimos una revisión que debería aclarar todo. Si no es el caso, siéntanse libres de subir un nuevo issue!
