### ISSUE TITLE
Consulta por biblioteca Hilolay

### ISSUE THREAD

**Issue by papa-caco** [sisoputnfrba/foro#1488]
Buenas tardes, 
Quería consultarles si tienen alguna novedad sobre la publicación de la biblioteca Hilolay. Según leímos en el enunciado aún está pendiente de publicación.
Hemos visto un repo de la cátedra que hace varios días no se actualiza: https://github.com/sisoputnfrba/hilolay  
Tenemos dudas de utilizar ese contenido para nuestro TP o esperar a que nos confirmen  cuál es la publicación definitiva.
Muchas gracias. Saludos,
Carlos.

**Comment by afilgueira** [comment]
Hola, esta biblioteca NO es la definitiva. En cuanto esté publicada lo haremos saber. Saludos!

**Comment by papa-caco** [comment]
Ok profe, aguardamos novedades entonces. Por mi parte pueden cerrar este issue. Muchas gracias.
Saludos,
Carlos.
