### ISSUE TITLE
Duda sobre interfaces de Hilolay

### ISSUE THREAD

**Issue by nancho81** [sisoputnfrba/foro#1489]
No encontramos en la biblioteca hilolay las interfaces de las funciones para la comunicación con SUSE que debemos escribir nosotros (_suse_init, _suse_create, _suse_schedule_next, _suse_wait, _suse_signal y _suse_join).

Sin estas interfaces si bien se pueden implementar funciones para comenzar a realizar tareas sobro SUSE y el cliente que lo utilizará, es imposible garantizar la compatibilidad con los programas de testeo del TP e incluso puede generar retrabajo al no tener contemplados formatos de datos con los cuales seran invocados.

**Comment by tferraro** [comment]
---> #1488

**Comment by AleGonez** [comment]
Buenas tardes, alguna novedad sobre la actualización de Hilolay?

Muchas gracias.

**Comment by afilgueira** [comment]
Hola, subimos una revisión que debería aclarar todo. Si no es el caso, siéntanse libres de subir un nuevo issue!
