### ISSUE TITLE
Pregunta sobre heap_metadata

### ISSUE THREAD

**Issue by ncoen97** [sisoputnfrba/foro#1490]
👋 ¡Hola!
> Para distinguir dentro de un segmento cuales porciones de memoria se encuentran libres, se
guardará ​metadata **dentro del mismo segmento**​, que indicará si el bloque está vacío y cuanto
tamaño tiene. Veamos un ejemplo utilizando esta metadata

Esto significa que la metadata tiene que estar dentro de la UPCM o dentro de cada segmento en la tabla de segmentos?

**Comment by tferraro** [comment]
La metadata de las "porciones" de los muse_allocs se almacena la UPCM! (A diferencia del resto de las estructuras administrativas, como las tablas de segmentos y páginas).

**Comment by ncoen97** [comment]
Gracias!

**Comment by IvanDL95** [comment]
Yo tengo una duda más encima de esto. En el enunciado marca claramente que se debe retornar *la primer posición del bloque de datos reservado disponible*. 

Hago "muse_alloc", guardo la metadata en una página, pero la metadata no ocupa toda la página (o la última de todas las páginas si deciden testear con paginas menores a 5 bytes). Tengo que retornar:

1. La base de la página + el offset que me ocupa la metadata? Es decir, la dirección inmediatamente contigua.
2. Comerme el resto como fragmentación interna y retornar la base de la página siguiente?

Creería que es el primer caso, pero no estoy del todo seguro, o si eso es ya decisión de implementación nuestra.
