### ISSUE TITLE
SUSE conectado a Fuse

### ISSUE THREAD

**Issue by agustinlk** [sisoputnfrba/foro#1491]
Buenas noches. Veo que en el diagrama general SUSE tiene conexión con Fuse. Entiendo que el programa se conecte con Fuse, también que MUSE se conecte con Fuse ya que trabaja con memoria virtual. Pero no me cierre la relaciṕon de SUSE con Fuse. Es por el archivo de log y config que se van a encontrar en el Filesystem propio?

Gracias

Agustín

**Comment by tferraro** [comment]
Buenas!
Es importante destacar algo: **Los módulos del TP no interactúan entre sí directamente y no son dependientes de la existencia de ningún otro**.
Es el programa de prueba quien se encargará de utilizar tanto _Hilolay_ como biblioteca de UTLs, como _libmuse_ como biblioteca de memoria dinámica, y elegirá trabajar sobre archivos en un filesystem cualesquiera, que pudiera o no estar implementado usando FUSE con la especificación del módulo de _SAC_.

**Comment by agustinlk** [comment]
Entonces que sería esa linea que une a SUSE con Fuse?

**Comment by tferraro** [comment]
Buenas!

El Filesystem definido por el SAC es **distribuido** puede estar en varias PCs, incluso en donde viva SUSE. Dependerá de SUSE si desea utilizar algín archivo en su ejecución o no; y en qué filesystem exista dicho archivo 🙂 .
Es un detalle, pero la línea es punteada por esa misma razón 😄

**Comment by agustinlk** [comment]
Perfecto. Gracias!
