### ISSUE TITLE
Duda sobre funciones de libmuse y Size_t

### ISSUE THREAD

**Issue by FrodriguezSandez** [sisoputnfrba/foro#1492]
Hola
Tengo una duda sobre una función. Muse_get tiene como parámetro "size_t" n, siendo n cantidad bytes a copiar.
¿Qué es size_t? En principio armamos las funciones siguientes como si size_t fuera un int/uitn32_t pero no sé si es lo mismo

**Comment by tferraro** [comment]
Si, eso que dice @IvanDL95 pega bastante en el palo.
Por lo general, está definido como un tipo que te permite indexar cosas (osea hacer `x[1]`). En la práctica, en el Ubuntu en conjunto con el compilador gcc, el `size_t` es equivalente a un entero sin signar. Dado que los enteros en tanto 32 como 64 bits de las distros de linux siempre tienen 4bytes de tamaño, es equivalente también a un `uint32_t`.

TL;DR: Pasale lo mismo que le pasarías a `malloc` para pedir el tamaño o a `memcpy` 😉 .

**Comment by FrodriguezSandez** [comment]
Genial, gracias!
