### ISSUE TITLE
Duda Memoria Virtual

### ISSUE THREAD

**Issue by ncoen97** [sisoputnfrba/foro#1493]
👋 ¡Hola!
Tenia entendido que cuando usamos el esquema de memoria virtual, en el área de swap tienen que estar cargadas TODAS las paginas del sistema. Entonces en nuestro caso, que usamos el algoritmo de clock modificado, si la pagina no fue modificada entonces no hay que volver a guardarla en memoria virtual porque ya está ahi. Si esto es así, por que en la configuración de ejemplo el área de swap es mas chica que la de memoria? Por ahí me estoy confundiendo algún concepto.

**Comment by ncoen97** [comment]
Estuve pensando un poco más esto y ordenando los conceptos porque tenia medio una ensalada, hay algunas cosas que me siguen confundiendo:
- Todas las paginas del sistema tienen que estar en el espacio de swap? si es así, para las paginas que en memoria no fueron modificadas no sería necesario copiarlas devuelta a swap cuando se saquen. Me confunde que en la configuración de ejemplo de muse tiene el espacio de swap mas chico que el de memoria.
@tferraro

**Comment by tferraro** [comment]
Buenas!

No necesariamente en el área de swap van a estar cargadas todas las páginas del sistema, es la gracia del Swapping, solo tenés lo que no está en memoria de tu espacio de direccionamiento 😄

**Comment by ncoen97** [comment]
Entonces cual sería la diferencia entre tener el bit de modificado en true o false? porque si no están todas en disco, cuando quiera sacar una pagina de memoria tendría que pasarla a memoria virtual esté modificada o no, porque sino perdería su contenido.

**Comment by afilgueira** [comment]
Buenas!

Tu área de swap puede tener dos configuraciones:
- swap incluye todo lo de memoria + algunas cosas que no están en memoria. Tu memoria es una especie de "cache" de swap
- swap + memoria incluyen todo, y nada se repite

En el primer caso, necesitás que tu swap sea más grande que la memoria. Lo bueno es que, ante un reemplazo en una página no modificada, simplemente "descartás" su contenido. Si está modificada, la escribís. El el segundo caso, cualquier reemplazo te implica una escritura, pero podrías tener un espacio de swap no tan grande.

Los sistemas operativos usaban mucho la alternativa 1 cuando las memorias no eran tan grandes, entonces existía esta recomendación de "ponele de swap el doble de la memoria". Hoy en día, con máquinas que tranquilamente tiene 8 o 16 GB de RAM, pierde un poco el sentido tener tanto swap, con lo cual es más común la alternativa 2.

Para este TP, la idea es que implementen la alternativa 2.

Saludos!

**Comment by ncoen97** [comment]
Perfecto! La única duda que me queda sería para que usamos el bit de modificado, porque en la alternativa 2 vamos a tener que copiar las paginas de memoria a swap y de swap a memoria estén modificadas o no.
Gracias.

**Comment by afilgueira** [comment]
Es una gran observación. A modo de "adelanto", piensen que el bit de modificado se usa para dos cosas. Una ya la descartamos, la otra está relacionada a la última parte de las clases de memoria virtual...

Saludos!

**Comment by afilgueira** [comment]
Hola, subimos una revisión que debería aclarar todo. Si no es el caso, siéntanse libres de subir un nuevo issue!

**Comment by ncoen97** [comment]
Buenas, estuve pensando y buscando sobre para que puedo usar el bit de modificado. Lo unico que se me ocurre es que te estes refiriendo a la prioridad en el clock modificado, pero no tendría mucho sentido ya que en clock modificado el objetivo es reducir la cantidad de escrituras en disco y en este caso vamos a tener que copiar todas las paginas igualmente... No se me ocurre otro motivo para usarlo.
