### ISSUE TITLE
Consulta FUSE - Problemas de Compilación -

### ISSUE THREAD

**Issue by AxelDellavechia** [sisoputnfrba/foro#1494]
Hola buenas tardes ¿Cómo están? 

Estoy teniendo problemas para compilar los ejemplos de Pokemon y Fuse Example.  Cuando compila genera lo siguiente:

```
15:36:36 **** Build of configuration Debug for project FuseExam ****
make all 
Building file: ../src/fuse_example.c
Invoking: Cross GCC Compiler
gcc -O0 -g3 -Wall -DFUSE_USE_VERSION=27 -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse -MMD -MP -MF"src/fuse_example.d" -MT"src/fuse_example.o" -o "src/fuse_example.o" "../src/fuse_example.c"
/tmp/ccHWY9fD.o: In function `main':
/home/utnso/workspace/FuseExam/Debug/../src/fuse_example.c:218: undefined reference to `fuse_opt_parse'
/home/utnso/workspace/FuseExam/Debug/../src/fuse_example.c:234: undefined reference to `fuse_main_real'
collect2: error: ld returned 1 exit status
src/subdir.mk:18: recipe for target 'src/fuse_example.o' failed
make: *** [src/fuse_example.o] Error 1

15:36:37 Build Finished (took 886ms)
```

Siempre me arroja ese error revise varias paginas y no estoy encontrando la solución ¿Podrán orientarme?

Una de las cosas que encontré que podía solucionar es agregar  `pkg-config fuse --cflags --libs` pero tampoco me funciono

**Comment by mgarciaisaia** [comment]
👋 Si hacés `ls -l /usr/include/fuse`, ¿tenés resultados? Si no, podría ser señal de que no tenés FUSE instalado, o sus headers de desarrollo. No recuerdo qué paquete es el que necesitás, seguramente lo hayan comentado por acá o el blog o algo.

**Comment by AxelDellavechia** [comment]
Hola buenas tardes, el resultado es :

utnso@ubuntu-server:~$ ls -l /usr/include/fuse
total 136
-rw-r--r-- 1 root root  2576 jul 12  2016 cuse_lowlevel.h
-rw-r--r-- 1 root root   714 jul 12  2016 fuse_common_compat.h
-rw-r--r-- 1 root root 12653 jul 12  2016 fuse_common.h
-rw-r--r-- 1 root root  8021 jul 12  2016 fuse_compat.h
-rw-r--r-- 1 root root 34589 jul 12  2016 fuse.h
-rw-r--r-- 1 root root  6925 jul 12  2016 fuse_lowlevel_compat.h
-rw-r--r-- 1 root root 52746 jul 12  2016 fuse_lowlevel.h
-rw-r--r-- 1 root root  7477 jul 12  2016 fuse_opt.h
utnso@ubuntu-server:~$

**Comment by mgarciaisaia** [comment]
Mmm... Ok, entonces está instalada, o eso parece.

¿Puede que te falte algún `#include` en ese `fuse_example.c`? Deberías tener _algún_ `#include` que referencie a FUSE. Algo como `#include <fuse.h>`, creo.

**Comment by AxelDellavechia** [comment]
[ejemplofuse.txt](https://github.com/sisoputnfrba/foro/files/3678483/ejemplofuse.txt)

Ese el código del ejemplo.

**Comment by mgarciaisaia** [comment]
¡Ahí está!

Probé el comando de `gcc` que pasaste en el primer post desde una VM con el archivo fuente que compartiste en el último, y obtuve el mismo fallo que vos.

En internet encontré [este issue](https://bugs.launchpad.net/ubuntu/+source/fuse/+bug/878612), que es muy probable que sea el que encontraste vos mencionando el `pkg-config`.

La solución que sugieren ahí es hacer:

```
gcc -Wall -o hello hello.c `pkg-config fuse --cflags --libs`
```

Es decir, agregar al final de un comando `gcc` más o menos estándar una invocación `pkg-config` que se interpola en la línea de comando.

<details>
<summary>Las comillitas invertidas en la consola significan algo así como "ejecutá esto como un comando, y reemplazalo en la línea de comandos original por su output".</summary>
Por poner un ejemplo más entendible, si hicieras

```
echo Hola `whoami`
```

La consola (bah, `bash`) ejecuta el comando `whoami`, que es un comando que imprime en su salida estándar el nombre del usuario que lo ejecuta (ponele, imprime `utnso`). Una vez ejecutado el `whoami`, bash reemplaza esa invocación por su salida, y ejecuta ese nuevo comando: `echo Hola utnso`. Y eso termina imprimiendo `Hola utnso` en pantalla.
</details>

`pkg-config` es un comando que te da info sobre las bibliotecas que tenés instaladas en el sistema. En particular, acá le estamos pidiendo los flags que necesitamos pasarle a `gcc` para compilar con esa biblioteca (`--cflags`), y cuáles necesitamos para linkear contra ella (`--libs`).

Si estás en un proyecto de software súper portable y ñañañá en que cada usuari@ puede tener sus bibliotecas instaladas en alguna ruta distinta, `pkg-config` te da una _re_ mano, porque te permite abstraer rutas del sistema en tus archivos de configuración/compilación del proyecto.

En el caso del TP, van a correr siempre en máquinas iguales (mismo sistema operativo, misma distribución, mismas bibliotecas), así que podemos hardcodear esos paths.

Si ejecutás en la consola ese `pkg-config fuse --cflags --libs`, vas a ver que te da algo como `-D_FILE_OFFSET_BITS=64 -I/usr/include/fuse -lfuse -pthread`. De todo eso, habías puesto casi todo - te faltó el `-lfuse`, nomás. Y, buen, el `-pthread`, que puede que lo necesites o no.

Así que agregá `fuse` en la parte de Libraries de Eclipse, y debería salir andando.

**Comment by AxelDellavechia** [comment]
Buenos días ¿Cómo estás?

Si justo en el ejemplo que puse se ve que entre todas las pruebas había borrado los flags -lfuse y -pthread. Lo que me había faltado era agregar como dijiste fuse en la parte librerias, si lo dejo así 

![image](https://user-images.githubusercontent.com/11680772/66055377-d7d56c00-e50b-11e9-8828-a6e444bdf0a2.png)

funciona todo de 10 no había entendido que debía hacerlo en el enlace que pasaste.

Gracias me solucionaste toda una semana de dolor de cabeza que estaba tratando de revisar

**Comment by mgarciaisaia** [comment]
No es que _moleste_, pero fijate que en tu captura agregaste `/usr/include/fuse` en el Library search path, que ahí te dice entre paréntesis que es el parámetro `-L` de `gcc`.

El `-L` especifica directorios en los que querés que el linker busque las bibliotecas compiladas (es decir, los `.so`), pero en `/usr/include/fuse` vas a tener, como su path indica, los headers para hacerle `#include`.

Funciona igual, porque _incluso sin ese parámetro_ va a encontrar el `.so` en las rutas de sistema. Pero es redundante, y potencialmente podría traerte problemas si, por ejemplo, en ese directorio `/usr/include/fuse` hubiera un `.so` que matchee con otra biblioteca que necesites (ponele, que haya un `libc.so` o alguna otra cosa así).

¡Éxitos, che!

**Comment by AxelDellavechia** [comment]
Entiendo, muchas gracias por las indicaciones :) nunca fue mi punto fuerte la programación.

Saludos

**Comment by melaibanez** [comment]
Hola, yo tengo un problema parecido con Suse. 
YA instale las commons y me fije si estaban instaladas.
Al importar el proyecto los hice con Export Project With Makefile.
Agregue las Library search path (-l) en el GCC C LINKER Librareries, agregue las commons.
Luego también configuré en Paths and Symbols las commons.
Entonces procedo a hacer un make y aparece el .o del  Suse pero al compilar el Suse.c no encuentra referencia a las commons (?)

`/tmp/ccpbUNQ3.o: In function `main':
Suse.c:(.text+0x2a): undefined reference to `log_info'
Suse.c:(.text+0x47): undefined reference to `log_info'
Suse.c:(.text+0x64): undefined reference to `log_info'
Suse.c:(.text+0x7a): undefined reference to `log_info'
Suse.c:(.text+0xa7): undefined reference to `iniciar_servidor'
Suse.c:(.text+0xc4): undefined reference to `esperar_cliente_con_accept'
Suse.c:(.text+0xe1): undefined reference to `enviar_mensaje'
/tmp/ccpbUNQ3.o: In function `crearLogger':
Suse.c:(.text+0x11b): undefined reference to `log_create'
Suse.c:(.text+0x136): undefined reference to `log_info'
/tmp/ccpbUNQ3.o: In function `leerArchivoDeConfiguracion':
Suse.c:(.text+0x154): undefined reference to `config_create'
Suse.c:(.text+0x199): undefined reference to `log_info'
Suse.c:(.text+0x1aa): undefined reference to `config_destroy'
/tmp/ccpbUNQ3.o: In function `setearValores':
Suse.c:(.text+0x1c6): undefined reference to `config_get_string_value'
Suse.c:(.text+0x1ea): undefined reference to `config_get_int_value'
Suse.c:(.text+0x202): undefined reference to `config_get_int_value'
collect2: error: ld returned 1 exit status
`

**Comment by mgarciaisaia** [comment]
@melaibanez no recortes el log de la compilación, porque así sólo vemos los errores - pero no el comando que se está intentando.

**Comment by melaibanez** [comment]
@mgarciaisaia ah perdón, esto es:

`utnso@ubuntu-server:~$ cd /home/utnso/workspace/tp-2019-2c-SuperandO/Suse/Debug/utnso@ubuntu-server:~/workspace/tp-2019-2c-SuperandO/Suse/Debug$ make
make: 'src/Suse.o' is up to date.
utnso@ubuntu-server:~/workspace/tp-2019-2c-SuperandO/Suse/Debug$ cd ..
utnso@ubuntu-server:~/workspace/tp-2019-2c-SuperandO/Suse$ cd src/
utnso@ubuntu-server:~/workspace/tp-2019-2c-SuperandO/Suse/src$ ls
Suse.c  SUSE.cfg  Suse.h  SUSE.log
utnso@ubuntu-server:~/workspace/tp-2019-2c-SuperandO/Suse/src$ gcc Suse.c
Suse.c:67:1: warning: parameter names (without types) in function declaration
 void suse_create(void(*fmain)(Paquete)){
 ^
/tmp/ccEXk5wf.o: In function `main':
Suse.c:(.text+0x2a): undefined reference to `log_info'
Suse.c:(.text+0x47): undefined reference to `log_info'
Suse.c:(.text+0x64): undefined reference to `log_info'
Suse.c:(.text+0x7a): undefined reference to `log_info'
Suse.c:(.text+0xa7): undefined reference to `iniciar_servidor'
Suse.c:(.text+0xc4): undefined reference to `esperar_cliente_con_accept'
Suse.c:(.text+0xe1): undefined reference to `enviar_mensaje'
/tmp/ccEXk5wf.o: In function `crearLogger':
Suse.c:(.text+0x11b): undefined reference to `log_create'
Suse.c:(.text+0x136): undefined reference to `log_info'
/tmp/ccEXk5wf.o: In function `leerArchivoDeConfiguracion':
Suse.c:(.text+0x154): undefined reference to `config_create'
Suse.c:(.text+0x199): undefined reference to `log_info'
Suse.c:(.text+0x1aa): undefined reference to `config_destroy'
/tmp/ccEXk5wf.o: In function `setearValores':
Suse.c:(.text+0x1c6): undefined reference to `config_get_string_value'
Suse.c:(.text+0x1ea): undefined reference to `config_get_int_value'
Suse.c:(.text+0x202): undefined reference to `config_get_int_value'
collect2: error: ld returned 1 exit status
`

**Comment by mgarciaisaia** [comment]
@melaibanez fijate que ahí estás ejecutando `gcc Suse.c`... ¡y nada más!

`gcc` te dice que no tiene definidas funciones que deben estar definidas en las commons porque, buen - jamás le dijiste que querías que use las commons para compilar.

Todos los parámetros que configurás en las Settings del proyecto en Eclipse terminan generando un `Makefile` (y algunos archivos más) en el directorio `Debug` del proyecto - el directorio en que arrancaste en lo que nos mostraste.

Y, de hecho, es probable que el `Makefile` esté ahí, porque cuando ejecutaste `make`, _algo pasó_. Lo que pasó es que `make` te dijo que se fijó y le parece que no hace falta hacer nada más - ya tenés `src/Suse.o` buildeado, y con eso le alcanza.

`make` trata de darse cuenta de si es necesario recompilar cosas o no. Un chequeo que hace (no estoy seguro de si es el único o no) es ver si los archivos fuentes fueron modificados más recientemente que el archivo a generar. En este caso, `make` determinó que `src/Suse.o` es más nuevo que los archivos que lo generan (presumiblemente, `src/Suse.c`, y quizá un `src/Suse.h`), y entonces no hace falta volver a compilarlo, porque daría el mismo resultado.

Pero igual huele medio raro todo. Capaz esté bueno ver el `Makefile` que tenés, a ver si es posta el que está generando Eclipse, o qué está pasando. Suele ser más verboso el Makefile que genera Eclipse, y suele compilar siempre el binario final, por más que nada más haya cambiado en los archivos intermedios. Así que compartinos eso a ver qué onda.

----

Por otro lado, es probable que tu `Makefile` incluya un _target_ (así es como se llaman las distintas cosas que le podés pedir a `make` que haga) llamado `clean`, que suele borrar todos los archivos generados por la compilación, para poder arrancar de cero. Fijate si, parada en el directorio `Debug`, podés hacer `make clean`, y después `make` seguramente haga _algo_. O, buen, capaz no, pero hay más chances.

Contanos qué onda :)
