### ISSUE TITLE
Duda Muse Init

### ISSUE THREAD

**Issue by micayeza** [sisoputnfrba/foro#1495]
Hola! Tengo una consulta sobre la funcion muse_init.

>      * @note Debido a la naturaleza centralizada de MUSE, esta función deberá definir
     *  el ID del proceso/hilo según "IP-ID".

La funcion recibe id - ip -puerto , según entiendo IP y puerto son de MUSE. Porque definiria el id de proceso como IP(muse)-ID?

Gracias!

**Comment by ncoen97** [comment]
Yo entendí que el id del proceso/hilo se arma con la IP propia del programa de prueba, que se puede conseguir con getpeername()

**Comment by tferraro** [comment]
Buenas!

Por lo general, los servidores suelen identificar a un "cliente" en particular mediante su socket. En este caso, como para darles más alternativas, la interfaz admite que le pases un ID por si quieren usarlo en vez del nro de socket. Ahora, dado que puede haber más de una máquina donde justo el id del proceso o el hilo sea el mismo, internamente habría que hacer una mezcla junto a la IP.

Nota: **no hay una solución mejor que la otra, es solo para que tengan alternativas**.
Nota2: Pueden obviarlo y directamente usar el socket id si tienen que es mas complicado

**Comment by micayeza** [comment]
Hola! Para que me quede claro, el IP que llega de la funcion es de MUSE.
Si quiero obtener el ip del programa que la llamo uso getpeername()? o algo similar?

Gracias!

**Comment by tferraro** [comment]
> Hola! Para que me quede claro, el IP que llega de la funcion es de MUSE.

Eso mismo!

> Si quiero obtener el ip del programa que la llamo uso getpeername()? o algo similar?

Del propio lado de MUSE podes usar esa función para obtener la ip del socket del cliente o usar directamente el file descriptor del socket. Ambas son completamente válidas 🙂

**Comment by micayeza** [comment]
Muchisimas Gracias!
