### ISSUE TITLE
Consulta SUSE- Estados

### ISSUE THREAD

**Issue by Fedryus** [sisoputnfrba/foro#1496]
Hola! ¿Cómo están?
Nos surgió una duda con el enunciado de SUSE.

No nos queda muy claro la parte que dice que los estados READY y EXEC son locales a cada uno de los programas. ¿Qué diferencia habría con los otros que son "comunes"?

La duda surge porque teníamos pensado hacer que SUSE al recibir un nuevo hilo (new) lo
metiese en una cola ready para, cuando sea el momento, evaluar desde allí el próximo hilo a ejecutar, pero si el enunciado me dice que READY es **local** a cada programa, entonces no puedo meter todos los hilos de todos los programas en una misma cola que maneje SUSE, ¿no? ¿o si?

¿A que se refiere con "locales" en cuanto a la planificación?

Gracias de antemano!

**Comment by tferraro** [comment]
Son locales al proceso 😄  Es decir, solo van a competir por el recurso de ejecución de ese proceso los hilos en estado READY de ese proceso solamente.

**Comment by Fedryus** [comment]
Hmm, ¿osea que el hecho de que sean locales solo va a afectar cuando planifique a corto plazo y decida que hilo se va a ejecutar?
Porque a largo plazo no me importa mucho, ¿verdad?

Me quedó claro que compiten por el recurso de su proceso, pero me pierdo cuando lo intento ver desde el punto de vista de SUSE

**Comment by tferraro** [comment]
> Hmm, ¿osea que el hecho de que sean locales solo va a afectar cuando planifique a corto plazo y decida que hilo se va a ejecutar?

Es una forma de verlo, si. Va a haber un PCP propio de cada proceso

**Comment by Fedryus** [comment]
Perfecto, vemos como lo encaramos. Gracias por la respuesta! 
Saludos.
