### ISSUE TITLE
Consulta de FUSE

### ISSUE THREAD

**Issue by fedebanca** [sisoputnfrba/foro#1497]
Hola.

Estuve investigando sobre FUSE para hacer la parte de Sac-Cli, y tengo un problema con los parámetros que debemos utilizar. Dependiendo de donde lo lea, las mismas funciones usan distintos parámetros. Por ejemplo, la función read:

**En el ejemplo de FUSE que esta en el github de utnso:**

static int sac_cli_read( const char *path, char *buffer, size_t size, off_t offset, struct fuse_file_info *fi );

**Lo que dice el puntero de las fuse_operations:**

ssize_t read(int filedes, void *buffer, size_t size);

**El ejemplo que encontré en Internet:**

int (*read) (const char *, char *, size_t, off_t, struct fuse_file_info *);

El que esta en el ejemplo se que funciona porque lo probé, pero el problema es que necesito saber los parámetros que debo usar para las demás funciones que no tiene implementadas, y no se de donde sacarlos.

Desde ya, muchas gracias.

**Comment by tferraro** [comment]
Buenas!
Las funciones 1 y 3 son la misma 🙂. Respecto a la segunda, nos das una referencia de donde sale? Porque la [docu](https://libfuse.github.io/doxygen/structfuse__operations.html#a2a1c6b4ce1845de56863f8b7939501b5) de `libfuse` dice lo mismo que 1 y 3 :/

**Comment by tferraro** [comment]
@fedebanca como venís con esto?
