### ISSUE TITLE
Linkear libreria a programa

### ISSUE THREAD

**Issue by micayeza** [sisoputnfrba/foro#1498]
Hola!
Seguí el video de Gastón para crear una libreria compartida y usarla en otro proyecto.
La libreria me compila OK. Cuando creo el programa para usarla, luego de configurar en preferencias--> symbols and path la incluyo como #include <libMuse/libMuse.h>
Pero cuando compilo mi programa me tira el error: 

> make all
> Building file: ../src/testMemoria.c
> Invoking: GCC C Compiler
> gcc -I"/home/utnso/workspace/tp-2019-2c-capitulo-2/libMuse" -O0 -g3 -Wall -c -fmessage-> > length=0 -MMD -MP -MF"src/testMemoria.d" -MT"src/testMemoria.o" -o "src/testMemoria.o" > "../src/testMemoria.c"
> ../src/testMemoria.c:13:29: fatal error: libMuse/libMuse.h: No such file or directory
> compilation terminated.
> src/subdir.mk:18: recipe for target 'src/testMemoria.o' failed
> make: *** [src/testMemoria.o] Error 1

Tambien probe con #include <libMuse.h> y agregue la variable LD_LIBRARY_PATH

¿Qué me falta? 
Gracias!

**Comment by mgarciaisaia** [comment]
¡Hola Mica!

Los `#include` tienen menos magia de la que parece. Si hacés `#include <libMuse/libMuse.h>`, `gcc` va a probar concatenando eso con cada una de las rutas que le pasaste en los `-I`, para ver si encuentra un archivo ahí. En tu caso, va a fijarse si `/home/utnso/workspace/tp-2019-2c-capitulo-2/libMuse/libMuse/libMuse.h` existe y es un archivo. ¿Capaz te esté sobrando un `libMuse/` en la ruta?

<details>
<summary>Sobre los #include</summary>
Para ser más preciso y correcto, `gcc` intenta los directorios listados con `-I`, pero también intenta algunos directorios default del sistema (`/usr/include`, ponele). Fijate que, ponele, podés hacer `#include <pthreads.h>`, sin pasarle un `-I`, y ese lo encuentra.

De hecho, también se puede hacer `#include "unArchivo.h"`, y la diferencia entre poner `< ... >` y `" ... "` en el `#include` es que con los `< >` va a empezar buscando en las rutas default, mientras que usando comillas va a empezar buscando en tus rutas de `-I`. En ambos casos, si no las encuentra en las ubicaciones preferidas, igual busca en las otras.

Así que, para este caso, tu `#include` del `libMuse.h` debería ir con comillas.
</details>

Otra cosa que podés chequear es que las mayúsculas y minúsculas estén bien puestas.

Probá y contanos :)

**Comment by micayeza** [comment]
Hola!
no , ya probe con:  #include <libMuse.h>,  #include </libMuse.h> casi con todas jaja
también en preferencias cambie la ruta del path por la absoluta y sigue tirándome el mismo error.

**Comment by mgarciaisaia** [comment]
Hacé `ls -lR /home/utnso/workspace/tp-2019-2c-capitulo-2/libMuse/` y compartinos la salida, a ver qué onda. Con ese comando, listás todo el contenido que hay en el directorio ese `libMuse`, a ver dónde está el `.h` que se te está escapando.

**Comment by micayeza** [comment]
ls -lR /home/utnso/workspace/tp-2019-2c-capitulo-2/libMuse/
/home/utnso/workspace/tp-2019-2c-capitulo-2/libMuse/:
total 16
drwxrwxr-x 2 utnso utnso 4096 oct  8 14:45 Debug
-rw-rw-r-- 1 utnso utnso  990 oct  8 10:08 libMuse.c
-rw-rw-r-- 1 utnso utnso 4799 oct  7 13:54 libmuse.h

/home/utnso/workspace/tp-2019-2c-capitulo-2/libMuse/Debug:
total 188
-rwxrwxr-x 1 utnso utnso 71484 oct  8 14:45 liblibMuse.so
-rw-rw-r-- 1 utnso utnso    90 oct  8 14:45 libMuse.d
-rw-rw-r-- 1 utnso utnso 96944 oct  8 14:45 libMuse.o
-rw-rw-r-- 1 utnso utnso   975 oct  8 15:33 makefile
-rw-rw-r-- 1 utnso utnso   231 oct  8 14:45 objects.mk
-rw-rw-r-- 1 utnso utnso   388 oct  8 15:33 sources.mk
-rw-rw-r-- 1 utnso utnso   651 oct  8 15:33 subdir.mk

**Comment by micayeza** [comment]
Tiene minuscula ahi lo vi!!! -.-
