### ISSUE TITLE
Cambios de grupo o integrantes? Entrá acá

### ISSUE THREAD

**Issue by afilgueira** [sisoputnfrba/foro#1499]
Para unificar la "oferta y demanda" creamos este issue. Aquellos que busquen grupo y aquellos que busquen integrantes pueden publicar acá. Al hacer esto, van a quedar suscritos automáticamente a las nuevas respuestas que lleguen y centralizamos la info. Cuando la búsqueda esté cerrada, pueden borrar / editar su mensaje y desuscribirse.

Les recomendamos respetar el siguiente formato:

Busco grupo / Buscamos N integrantes
Nombre de grupo / persona
Curso
Mail o datos de contacto (opcional, está en el perfil de github)
Comentarios

Un detalle a tener en cuenta a la hora de dejar info de contacto: este foro es público (para cualquiera con cuenta en github).

Éxitos con eso!

**Comment by tmerchan** [comment]
Busco grupo 
Tamara Merchan
Curso K3573
tamara.merchan.tm@gmail.com / Perfil de git: tmerchan / wpp: 1159753115
Tengo experiencia en la materia (4ta cursada) busco específicamente aprobar el trabajo práctico, en este momento es mi prioridad por lo que puedo juntarme en cualquier momento/lugar si fuera necesario y todos los días adelanto un poquito del contenido.
Estuve ya trabajando con MUSE pero puedo acoplarme a cualquier proceso.
Gracias y saludos.

**Comment by nicolaslazo** [comment]
Buscamos 1 integrante
Grupo Los Trapitos
Curso K3523
Contacto: nlazo@est.frba.utn.edu.ar

**Comment by ofasciolo** [comment]
Buscamos 2 integrantes
Grupo: A ver si me apruebas 
Curso: K3572
Contacto: ornella_sofia@hotmail.com

**Comment by enogueiras** [comment]
Somos 2, buscamos grupo de 3 integrantes en lo posible.

Mariano Boschini
boschini.mariano@gmail.com

Emilio Jose Nogueiras
emilio.nogueiras@gmail.com

Saludos.

**Comment by FaridUtn** [comment]
Busco grupo.
Farid Ahmed
Curso : K3574
Contacto: fariidahmed.fa@gmail.com
Busco grupo avanzado y compenetrado para meter la materia si o si

**Comment by clu3dfx** [comment]
Busco grupo.

Claudio Luciano Sonntag
Curso: K3572
Contacto: claudiohluciano@gmail.com
En mi grupo hice la primer entrega y parte de la segunda. Busco un grupo comprometido, con ganas de trabajar, de juntarse las veces que sea necesario y de sumar **todo** para aprobar el TP.

Saludos,
Claudio.

**Comment by ezelee** [comment]
Busco un integrante
Grupo: The Walking Thread
Curso K3623
Contacto ezequiel.ariel.lee@gmail.com

Buscamos una persona proactiva y sepa comprometerse con los desarrollos. Valoramos que sea una persona comprometida y si es posible, debido al tiempo que resta, con conocimiento en FUSE/SAC para cubrir la persona que no pudo seguir.

**Comment by IvanDL95** [comment]
Buscamos 2 personas para llenar el grupo.

Iván De Luca
Grupo: Lost in User Space
Curso : K3573
Mail: ivandeluca.95@gmail.com
Telegram: @iv4n_95

Preferentemente que sepa como integrar FUSE al trabajo y/o sepa como desarrollar la parte del SAC para ayudar más en esa parte.

**Comment by MicaFesta** [comment]
Buenas, busco grupo!

Estoy haciendo el módulo SUSE.

Dejo mi celu 1123740418 (:

**Comment by FaridUtn** [comment]
Buenas, buscamos un ultimo integrante para el grupo, buscamos alguien para terminar muse que estaba bastante avanzado.
Farid Ahmed.
Curso : K3574
Contacto : fariidahmed.fa@gmail.com

**Comment by BelenTripodi** [comment]
Buscamos un integrante para completar el grupo. Idealmente que sepa de memoria.

Mail: mbelentripodi@gmail.com
Telegram: @beltripo

**Comment by MacarenaPesce** [comment]
Busco grupo que esté activo y con ganas de aprobar la materia. Estaba trabajando en Muse/libMuse en mi grupo anterior.

Mail: maqarena.agostina.pesce@gmail.com

**Comment by emiortiz** [comment]
Hola, buscamos un integrante para el grupo. Se nos acaba de bajar una persona.
Mail: emiliano.ortiz@hotmail.com

**Comment by afilgueira** [comment]
Dado que cerraron los cambios, cierro el hilo. Saludos!
