### ISSUE TITLE
Dudas sobre los cambios en muse

### ISSUE THREAD

**Issue by FrodriguezSandez** [sisoputnfrba/foro#1500]
Buenas

Estuvimos revisando los cambios y tenemos algunas dudas al respecto de:

Sobre la tabla de segmentos, ¿qué es la base lógica? y además no me queda claro cómo funciona esto:
"Ante la llegada de un acceso a memoria, vamos a chequear que esa **dirección** sea parte de alguno de nuestros segmentos. Si no lo fuera, se considerará acceso inválido. Si lo fuera, se accede a ese segmento y se busca la página correspondiente restando la base y partiendo la dirección en página y offset"

Asumo que como nuestra configuración es por segmentación paginada, de esa dirección voy a poder calcular el segmento y encontrarlo en la tabla ¿no?

**Comment by afilgueira** [comment]
Hola, asumo para dar esta respuesta que ya conocen bastante bien segmentación paginada por sus propios medios (ya que todavía no dimos esa clase).

En segmentación tradicional, la tabla de segmentos habitualmente tiene una base física que indica dónde arranca un segmento en memoria. Cuando se combina con paginación, este valor pierde relevancia ya que el frame indica la base física de una página dentro de un segmento.

Usar una X cantidad de bits para el segmento, Y para la página y Z para el offset limita el tamaño de los segmentos. Imaginemos que usamos 2 bits para el segmento y 30 para el resto: podremos tener 4 segmentos de 2^30 (1 GB) pero ninguno podría ser usar toda la memoria. Para evitar este problema, hacemos algo _remotamente similar_ a lo que hacen algunas arquitecturas: nos guardamos la base *lógica* del segmento y permitimos que tenga el tamaño que sea necesario. Cuando llega un pedido, validamos a qué segmento pertenece en función de *esta base* y el límite, en lugar de partir la dirección. El resto del algoritmo está explicado en el anexo.

Saludos!

**Comment by mgarciaisaia** [comment]
> Hola, asumo para dar esta respuesta que ya conocen bastante bien segmentación paginada por sus propios medios (ya que todavía no dimos esa clase).

Lo más importante de esa frase es su corolario: si no conocen segmentación paginada, lean un poco, y otro tanto ténganse paciencia hasta que llegue la clase correspondiente.
