### ISSUE TITLE
Duda sobre hilolay

### ISSUE THREAD

**Issue by hernan-arga** [sisoputnfrba/foro#1501]
Buenas, tengo unas dudas bastante basica con respecto a hilolay.
La idea, segun entendi, es que yo cree un archivo como el de "example_alumnos.c" donde defina las funciones (suse_return, suse_create, suse_wait y demas), pero ¿Como vincularia este .c con mi archivo de prueba?¿tendria que crear una dependencia en este ultimo que sea una referencia a un proyecto "hilolay" donde estaria mi .c? de ser asi ¿tendria que incluir en este proyecto los hilolay.h, hilolay_alumnos.h y demas o estos se referencian aparte desde mi "example_alumnos.c" (yo creo que seria asi por el ej subido pero no estoy seguro)?.
Y otra noto que las funciones suse_return y suse_init no esta definida en las operaciones de "hilolay_alumnos.h" de la nueva version, ¿Esto lo suben mas adelante cuando lo vuelvan a actualizar con las implementaciones de semaforo?

Gracias.

**Comment by afilgueira** [comment]
Por partes:

- si, una biblioteca similar al example_alumnos.c
- en hilolay hacemos referencia a example_alumnos. Si implementás las funciones, la biblioteca las usa. Es algo similar al example_program.c
- sí, buen punto, falta info sobre return e init

Saludos!

**Comment by nicolaslazo** [comment]
Me sumo a la pregunta, hay alguna convención para marcar los huecos en código que los alumnos deberían llenar o los que están porque van a ser completados en los próximos commits del repositorio?

**Comment by jp-developer0** [comment]
hernan si ejecutas los makefile y haces include del proyecto hililay master al proyecto hilolay-example-master, deberia compilar sin problemas , asi como esta, sin tocarles el codigo.

tengo una duda con SUSE_INIT,   es un metodo trivial, ya que inicializa el servidor, para recibir y encolar los ults, entonces porque habrian de agregar codigo de el despues? si es un metodo "inicial" si se quiere, 
se supone que ya deberia codearlo? o espero a que desde la catedra indiquen que se haga? 
Saludos
JP

**Comment by tferraro** [comment]
Buenas!

Para hilolay_init, si bien en un inicio conceptual el objetivo se encuentra en inicializar suse y la conexión, también es necesario que inicialice los internals de la biblioteca, como por ejemplo, asegurarse que el hilo principal existe.

Como es necesario que, para eso, suse se encuentre inicializado, a diferencia del resto de los métodos, el init está pensado para ser implementado de forma inversa.

**Comment by jp-developer0** [comment]
Ah ok, entonces hilolay init es quien va a levantar suse y ejecutar un suse create con su primer hilo inicializado.

**Comment by afilgueira** [comment]
Buenas, quedó claro? Podemos cerrar?

**Comment by hernan-arga** [comment]
Si, gracias por responder.
