### ISSUE TITLE
Duda muse_free

### ISSUE THREAD

**Issue by ncoen97** [sisoputnfrba/foro#1502]
👋 ¡Hola!
> void muse_free(uint32_t dir)

Si la dirección sobre la cual se quiere hacer el free no es la posición inicial de ningún muse_alloc, tenemos que buscar la posición inicial de ese muse_alloc y liberarlo entero? O deberíamos retornar error?

**Comment by tferraro** [comment]
Buenas! Lo bueno que tiene de implementar interfaces comunes a la realidad es que podemos preguntarnos como free() lo resuelve (y no inventar, un poco el driven de este tp).

Si haces man free, entre toda la docu de malloc y amigos, hay una frase bastante copada que aplica a esto:

> The free() function frees the memory space pointed to by ptr, which must have been returned by a previous call to malloc(), calloc() or realloc(). Otherwise, or if free(ptr) has already been called before, undefined behavior occurs. If ptr is NULL, no operation is performed.

En otras palabras, si el puntero no es el devuelto por malloc, free no te asegura un comportamiento definido😁. ‘aka’ decidan ustedes 💪🏻

**Comment by ncoen97** [comment]
Buenas! tenemos otra duda con respecto al muse_free, hice un ejemplo para que quede mas claro.
Los cuadrados naranjas son los heap_metadata en uso y los azules son los liberados. 

![Consulta so](https://user-images.githubusercontent.com/7952790/68031998-83a0e180-fc9b-11e9-9956-56442dc75a89.jpg)

La pregunta puntualmente es si luego de haber hecho los 2 muse_free, que queda una pagina entera en "free", hay que liberar la pagina 2 (y cambiar el tamaño del heap a heap->size - pagesize)? o ese espacio queda tomado entero para un próximo muse_alloc?

**Comment by ncoen97** [comment]
Ya me respondieron presencialmente que no se liberan las paginas, quedan tomadas para próximos muse_alloc.
