### ISSUE TITLE
Duda sobre _suse_schedule_next

### ISSUE THREAD

**Issue by Darkonis13** [sisoputnfrba/foro#1503]
Buenas tardes! Tenía una consulta sobre el tiempo de ráfaga de las funciones con las que el planificador a corto plazo tiene que trabajar...

Para obtener el próximo hilo a ejecutar, se necesita simular un SJF con las funciones en Ready.

¿Cómo puedo saber la ráfaga de una función sin que tenga efecto? ¿La manda el usuario como parámetro?

**Comment by afilgueira** [comment]
Hola, lo más simple es medir el tiempo en el que arranca y el tiempo en el que termina. Saludos!

**Comment by Darkonis13** [comment]
Esa era una de las posibles soluciones, el problema sería entonces, cómo hacer para que al medir el tiempo, la función no tenga efecto sobre lo que deba hacer? Porque la idea es devolver el siguiente a ejecutar de la cola de Ready, pero si mido el tiempo de esa forma, ya lo estaría ejecutando

**Comment by tferraro** [comment]
Buenas! El overhead es relativamente menor y va a encontrarse por igual en todos los hilos por igual, por lo que terminaría haciendo que todos "sean más largos" un pelín más, no cambiando la utilidad del algoritmo 🙂

**Comment by hernan-arga** [comment]
> Buenas! El overhead es relativamente menor y va a encontrarse por igual en todos los hilos por igual, por lo que terminaría haciendo que todos "sean más largos" un pelín más, no cambiando la utilidad del algoritmo 🙂

Hola, igual me parece que la duda no iba por el lado del overhead sino por que si yo tengo una funcion que tiene que modificar una variable (ej asigno a una variable numero = 23) para medir su rafaga tengo que ejecutar la funcion y al ejecutarla ya estoy modificando la variable.

**Comment by Darkonis13** [comment]
> > Buenas! El overhead es relativamente menor y va a encontrarse por igual en todos los hilos por igual, por lo que terminaría haciendo que todos "sean más largos" un pelín más, no cambiando la utilidad del algoritmo 🙂
> 
> Hola, igual me parece que la duda no iba por el lado del overhead sino por que si yo tengo una funcion que tiene que modificar una variable (ej asigno a una variable numero = 23) para medir su rafaga tengo que ejecutar la funcion y al ejecutarla ya estoy modificando la variable.

Claro, este es el problema que tengo D:

**Comment by mgarciaisaia** [comment]
👋 ¡Hola!

¿Tuvieron ya las clases de planificación en la teoría?

El problema que describen es _exactamente el mismo_ que tiene un planificador real: tratar de predecir cuánto va a tardar una ejecución antes de realizarla.

Y, justamente, para eso es que se inventó esto de _estimar_: no sé cuánto va a tardar la operación, pero, en vez de simplemente decir "No sé", me invento una fórmula que intente predecir cuánto va a tardar.

En otras palabras: nunca **mido** cuánto _va a tardar_ una ejecución; nomás _la estimo_.

Lo que sí mido es la ejecución _que ya sucedió_; y esa, seguramente, sea alguna de las herramientas que vaya a aprovechar para mi estimación.

Teniendo esto en cuenta, reléanse la consigna y traten de ver si ahora parece un poco más realizable, o si tiene más sentido. Si se siguen sintiendo bastante igual, sigan contando qué entienden de la situación, qué entienden que tienen que hacer, y por qué les parece que no funciona. Teniendo eso escrito, capaz es más fácil encontrar y resaltar cuál es el preconcepto que tienen errado, y corregirlo :)

**Comment by Darkonis13** [comment]
Gracias por la respuesta, claro... Lo que pensaba entonces era que se le pase como parámetro al planificador, el tiempo estimado de cada función, pero entonces debería ser algo que el usuario tiene que pasarle junto con el programa que quiere encolar?

**Comment by mgarciaisaia** [comment]
Bueno, pedirle a el/la usuari@ la estimación de la tarea es _una opción_, pero no es muy user-friendly - ¿alguna vez tu sistema operativo te preguntó cuánto creés que va tardar la ejecución de algún programa?

Fijate que el mismo enunciado del TP te referencia a los capítulos relevantes del Silbertchatz. Pegale una repasada, que se te está escapando la base del asunto.

**Comment by hernan-arga** [comment]
Creo que entendi, lo unico que me hace ruido es en que momento tengo que medir el tiempo que tardo la ultima funcion, ya que yo lo que venia editando hasta ahora es en hilolay un archivo "implementaciones.c" donde solamente defino las funciones que se comunican con SUSE y el "suse.c"
¿Tendria que modificar tambien el hilolay_internal.c con las funciones que ya estaban hechas por la catedra? De ser asi ¿En que momento tendria que considerar que pasa a ejecutarse, cuando hace el swap_context?

**Comment by afilgueira** [comment]
Hola, bajo ningún concepto tienen que editar el internal. De hecho, más allá de que el código está disponible por si quieren mirarlo, no es necesario que lo hagan; podría ser una caja negra para uds.

Piensen dónde podrían medir cuándo arranca y cuándo termina una ráfaga. Si esto incluye un poquito de overhead extra, está bien también, siempre y cuando sea para todos los hilos. Al fin y al cabo, esto no va a cambiar la idea de la estimación.

Saludos!

**Comment by tferraro** [comment]
Buenas👋🏻 Como viene eso? Pudieron solucionar la duda?

**Comment by hernan-arga** [comment]
Hola, por mi parte si ya esta solucionada la duda.

**Comment by tferraro** [comment]
@Darkonis13 tu duda se resolvió también? 😄
