### ISSUE TITLE
Consulta sobre los heap_metadata en muse

### ISSUE THREAD

**Issue by FrodriguezSandez** [sisoputnfrba/foro#1504]
👋 ¡Hola!

Tengo una duda sobre el heap_metadata. qué pasa si queda entre dos páginas?
Es decir, cuando calculo la cantidad de páginas que necesita el segmento incluyo el espacio que voy a necesitar para los heap_metadata.. pero qué pasa si tengo una situación donde requiero una página más sólo para almacenar una parte de la estructura de heap_metadata. Estaría bien eso?

**Comment by afilgueira** [comment]
Sí, es una opción. Saludos!

**Comment by tferraro** [comment]
Me sumo a la respuesta! :D

Pensalo como capas de abstracción, el malloc, que en su implementación se para sobre un segmento y va guardando metadata junto a la info real, **no conoce nada sobre páginas**, ese es un nivel inferior que solo conoce el segmento.
Por lo tanto, tranquilamente te puede quedar un malloc o metadata entre 2 páginas y debería comportarse al igual que si no estuvieran 🙂 

El único caso que no es válido tomarlo de forma indistinta, es en el cual existen 2 segmentos, porque ahí la capa de segmentación está dividida y, si el segmento no se puede expandir y no entra el siguiente malloc, entonces es necesario pasarlo completo al siguiente segmento, asumiendo la fragmentación

**Comment by afilgueira** [comment]
@FrodriguezSandez esto responde tu pregunta? Saludos!

**Comment by tferraro** [comment]
Buenas! Cierro por inactividad😔 Cualquier cosa que la duda persista lo volvemos a abrir😁
