### ISSUE TITLE
SUSE_INIT

### ISSUE THREAD

**Issue by jp-developer0** [sisoputnfrba/foro#1505]
tengo una duda con SUSE_INIT, es un metodo trivial, ya que inicializa el servidor, para recibir y encolar los ults, entonces porque habrian de agregar codigo de el despues? si es un metodo "inicial" si se quiere,
se supone que ya deberia codearlo? o espero a que desde la catedra indiquen que se haga?
Saludos
JP

**Comment by tferraro** [comment]
No es la misma que esta pregunta https://github.com/sisoputnfrba/foro/issues/1501#issuecomment-541292166 ? 🤔

**Comment by afilgueira** [comment]
Buenas, cierro por duplicada. Si algo no quedó claro, por favor reportalo!
