### ISSUE TITLE
Consulta por el grado de multiprogramacion

### ISSUE THREAD

**Issue by hernan-arga** [sisoputnfrba/foro#1507]
Buenas, tengo una duda del enunciado. En una parte dice:

> Las transiciones de los hilos a READY serán según el grado de multiprogramación. El mismo será único y será compartido por todos los hilos.

Pero despues cuando habla de metricas dice:

> Por cada programa:
Grado actual de multiprogramación

Entonces, la multiprogramación es la misma para todos los hilos de todos los procesos o la misma para todos los hilos de 1 proceso independientemente de los demas procesos.

Gracias, saludos.

**Comment by NaylaWinter** [comment]
Buenas,

El grado de multiprogramación es global a todos los hilos de todos los procesos.
Esta incorrecta la métrica cuando dice que esto se debe mostrar por programa, se deberá mostrar a "nivel de sistema". En una próxima revisión ya estará corregido este punto.

**Comment by hernan-arga** [comment]
Ah buenisimo! esto me simplifica las cosas. Gracias, saludos.
