### ISSUE TITLE
levantar servidor 

### ISSUE THREAD

**Issue by jp-developer0** [sisoputnfrba/foro#1508]
Buenas, 
seguí el tutorial de creacion de servidor, dentro del suse.c , para levantar mi servidor suse que escuche hilos de ejecucion, y encole.
A la hora de querer probar mi servidor, si es que escucha, igual que como lo prueban en el video, noto que no tengo la carpeta "Debug", donde  estaria el archivo par hacer ./suse, y que ejecute el main.
**Como genero esa carpeta Debug ?**

**Comment by mgarciaisaia** [comment]
¿Cuál es el tuto que mencionás, che?

**Comment by jp-developer0** [comment]
estos 4 
https://www.youtube.com/watch?v=87gwfsJ_83o&feature=youtu.be

Igual ya lo resolvi, hice un proyecto nuevo,
antes no tenia la carpeta porque habia importado

**Comment by afilgueira** [comment]
@jp-developer0 podemos cerrar? quedó listo esto?

**Comment by jp-developer0** [comment]
Si cierre Gracias
