### ISSUE TITLE
Error indexer

### ISSUE THREAD

**Issue by jp-developer0** [sisoputnfrba/foro#1509]
Hola, tengo un proyecto que cada vez que lo compilo me tira esto, cada vez me tira mas, 
todos los errores tienen esamisma detalls

Allguien sabe que es?

![imagen](https://user-images.githubusercontent.com/50207809/66768906-1f53e480-ee8a-11e9-96b3-301c2ff48cbd.png)

**Comment by afilgueira** [comment]
Hola, te sigue pasando? Si es así: https://www.youtube.com/watch?v=18cN8Jk4WjQ

**Comment by jp-developer0** [comment]
Si cierre Gracias 
ya lo resolvi
