### ISSUE TITLE
Cliente hilolay

### ISSUE THREAD

**Issue by jp-developer0** [sisoputnfrba/foro#1510]
Hola, 
ustedes nos dieron hilolay-master que trae hilolay internal , tanto .c como .h, y a su vez trae hilolay alumnios .h

Lo que quieren es que desarrollemos el que sería "hilolay_alumnos.c" osea, el codigo de cada metodo? 
y , por otro lado, el que sería "suse_create", este seria el "socket cliente" si se quiere, que va a conectarse al servidor SUSE propiamente dicho, quien es el socket servidor que luego planificará?

Espero haberme explicado bien, cualquie duda consulte, saludos

**Comment by afilgueira** [comment]
Hola, en breve vamos a agregar más documentación para que quede más claro, pero la idea es que uds desarrollen hilolay_alumnos, sí sí. La segunda pregunta no me quedó clara. 

Saludos!

**Comment by jp-developer0** [comment]
Si cierre Gracias
