### ISSUE TITLE
Duda Memoria Virutal 2.0

### ISSUE THREAD

**Issue by ncoen97** [sisoputnfrba/foro#1511]
Hola! Abro un nuevo issue porque el anterior quedó cerrado, referencio la ultima duda para cerrar el tema.

Buenas, estuve pensando y buscando sobre para que puedo usar el bit de modificado. Lo único que se me ocurre es que te estés refiriendo a la prioridad en el clock modificado, pero no tendría mucho sentido ya que en clock modificado el objetivo es reducir la cantidad de escrituras en disco y en este caso vamos a tener que copiar todas las paginas igualmente... No se me ocurre otro motivo para usarlo.

_Originally posted by @ncoen97 in https://github.com/sisoputnfrba/foro/issues/1493#issuecomment-541325546_

**Comment by afilgueira** [comment]
Hola, sí. El bit lo necesitás para poder correr el algoritmo, aunque es cierto lo que mencionás de que pierde el sentido, porque de todas formas tenés que hacer escrituras.

**Comment by ncoen97** [comment]
Ah okay, gracias
