### ISSUE TITLE
problemas de visualizacion del g-code en UGS platform

### ISSUE THREAD

**Issue by karredpool** [sisoputnfrba/foro#1512]
👋 ¡Hola!
mi problema es el siguiente:
Usando el software para mecanizado UGS platform, al importar el g-code, la imagen  se deberia ver en el visualizador del mismo y no se ve , es como si estubiera a intermitencias aparece y desaparece todo el tiempo y me impide ver con claridad por donde se dirige el mecanizado. 
porque este problema ??
Gracias y un saludo..

**Comment by tferraro** [comment]
Buenas!

Este es un foro de la materia Sistemas Operativos de la Carrera Ing en Sistemas de Información de la Facultad BsAs de la UTN, no nos especializamos en software de Mecanica😛
