### ISSUE TITLE
Duda del enunciado en planificador

### ISSUE THREAD

**Issue by hernan-arga** [sisoputnfrba/foro#1513]
Hola, el enunciado en un momento dice:

> Un hilo puede transicionar a este estado (blocked) mediante un bloqueo por semáforo o esperando que termine otro thread.

La unica forma de que se bloquee esperando otro thread segun lo veo es que estuviera ya bloqueado por un semaforo, y haya pasado otro a ejecutar por lo que tendria que esperar que termine este ultimo o se bloquee. ¿Hay alguna otra forma?

**Comment by tferraro** [comment]
Si la hay😁
Al igual que en pthread, si llamas a la función del join de los hilos, el hilo que la invoque debe bloquearse hasta que el hilo a joinear termine😊

**Comment by hernan-arga** [comment]
Hola, cuando decis bloquearse te referis a que pasa de el estado actual (por ej exec) a bloqueado? Porque de ser así como podría terminar ese hilo si lo estoy bloqueando?

**Comment by tferraro** [comment]
👋🏻 
Una distinción nomas, hilolay_join es quien tiene ese comportamiento que mencione antes😊. Siempre en las bibliotecas se habla respecto a la interfaz que exponen.

Si vos estas pensando en suse_join, hace lo que decis, **marca** un hilo como bloqueado.

Recorda que ustedes no tienen ese control de como finalizar un hilo, eso lo tiene hilolay. La implementación que realicen como grupo solo debe responder a la interfaz, por de cierta manera, cuando hablamos de ‘terminar un hilo’, de su lado eso es marcarlo como terminado (EXIT) y para eso existe suse_close😉

Saludos!
Tom

**Comment by hernan-arga** [comment]
Ah ok entonces la idea es que cuando me invoquen a suse_join yo lo unico que tendria que hacer es transicionar el hilo actual en exec a blocked ¿Verdad?

**Comment by tferraro** [comment]
> yo lo unico que tendria que hacer es transicionar el hilo actual en exec a blocked 
Sip 😄 

Respecto a como transiciona de nuevo a READY, pues cuando el hilo sobre el cual se bloqueó haya finalizado! 😉

**Comment by hernan-arga** [comment]
> Respecto a como transiciona de nuevo a READY, pues cuando el hilo sobre el cual se bloqueó haya finalizado! 😉

O sea segun veo en la definicion a suse join se la llama como "suse_join(thread->tid);" este 
thread->tid segun entiendo es el que deberia bloquearse, pero cual es el que tiene que esperar que termine? el nuevo hilo que pasaria a ejecucion?

**Comment by tferraro** [comment]
Tiene mucho sentido eso que decis.
Voy a validar esto con otros ayudantes a ver que onda, cosa de no estar pifiando😅.

**Comment by tferraro** [comment]
Volví con buenas nuevas!😄 

Cuando llames a `suse_join` en realidad estás llamado a `suse_join(tid hilo a esperar)` (https://github.com/sisoputnfrba/hilolay/blob/master/hilolay_internal.c#L122 por si te interesa chusmear el código interno).
Esa diferencia no es trivial, porque de ahí vino nuestra confusión 😆 

Eso implica que, dado que vos sabés que el hilo actual es el que se va a bloquear, también podes dejartelo guardado para el momento que tengas que desbloquearlo 😉

**Comment by hernan-arga** [comment]
Ah ok, pero entonces me surge otra duda del enunciado.
Segun lo que me decis el que se bloquea es el hilo que esta actualmente en exec, pero entonces como funciona la parte del enunciado que dice:
> También es posible realizar un join a un thread ya finalizado.?

**Comment by afilgueira** [comment]
Gran pregunta! La idea es que el TID que pasás por parámetro podría ser el de un hilo que ya finalizó. A fines prácticos, el hilo que llama al join "ya lo esperó". 

Acá hay varias opciones para encarar. El resultado de esto depende un poco del criterio del grupo y una buena justificación al respecto (por ej, en el coloquio).

Saludos!

**Comment by hernan-arga** [comment]
Buenisimo, gracias a ambos por contestar.
