### ISSUE TITLE
Duda con primer hilo que se manda en init

### ISSUE THREAD

**Issue by hernan-arga** [sisoputnfrba/foro#1514]
Buenas! vengo con otra duda.
Segun veo en la definicion de init_internal se llama a 
`  current_ult = &ults[0]; main_ops->suse_create(current_ult->id);`
El tema es que cuando realizo mi implementacion de SUSE me pasa que ese hilo 0 es el primero que me llega a exec, pero en realidad el primero que ejecuta mi programa de prueba es el primer hilo que pidio un create:

![1](https://user-images.githubusercontent.com/37780035/67299849-8cd3c680-f4c3-11e9-9b6c-906017a37a09.png)

Fijense que el de la izq que es mi suse dice "tid en exec 0" o sea el que estoy planificando en exec es el tid 0 que se manda al principio en el init, pero el que ejecuta la prueba es el tid 1 (el que muestra los numeros). Ademas, por causa de esto, todo el tiempo cuando pide el siguiente a ejecutar dice que es el hilo 1 que en realidad tendria que ser el que esta ejecutandose ahora.

¿Para que es ese hilo 0 que se manda en el init?
¿Que es lo que estoy haciendo mal cuando mando a exec el primero que tenga mi programa, y por ende este tid 0?

Perdon si falta informacion de mi implementacion pero no estaba seguro que subir a este issue en cuanto a codigo de mi implementacion, para preguntar esto. Cualquier cosa me dicen que falta para analizar el problema y lo dejo en otro comentario.

Gracias, saludos

**Comment by afilgueira** [comment]
Hola, el TID 0 es el "hilo main". El hilo que arranca a ejecutar y crea a los otros hilos es también un ULT que se planifica! Por ende, lo tenés que considerar en todo el circuito que estás armando.

Aclara esto tu consulta? Saludos!

**Comment by hernan-arga** [comment]
Masomenos, mi duda ahora es ¿Como se cuando termino un hilo desde SUSE? porque creo que mi problema viene por ahi, ya que yo solo lo planifico pero de alguna manera tengo que saber que termino para que pase el siguiente a la CPU de mi programa.

**Comment by afilgueira** [comment]
Hola, para eso están la funciones "suse_schedule_next" y "suse_close"

**Comment by hernan-arga** [comment]
Ok, creo que ya veo lo que estoy haciendo mal.
Yo habia intentado para calcular la rafaga de cada hilo, ver cuantas veces se llamaba a schedule_next mientras estaba en ejecucion. Esto me lo habia sugerido un ayudante y me parecia que tenia sentido y no era dificil de hacer. El problema esta en que segun veo, cuando se llama a schedule_next, el internal.c lo que hace es pasar a ejecucion ese que le dije que seria el siguiente a ejecutar (yo asumi que el siguiente era el siguiente en ready).

Mi pregunta es: si me piden el siguiente a ejecutar con schedule next ¿Yo deberia pasarles siempre el que esta actualmente en ejecucion mientras no se bloquee ni termine? porque creo que eso es lo que estaba haciendo mal al pasarles el siguiente en ready.

**Comment by afilgueira** [comment]
`schedule_next` te pide el siguiente a ejecutar. No deberías pasar el que está en ejecución

**Comment by afilgueira** [comment]
El comportamiento esperado es ese. Si SUSE queda desactualizado, el arreglo debería ser ahí. Un problema tan puntual es medio difícil de seguir en un thread, arrimate a soporte y lo ves con cualquiera de los que estemos. Saludos!

**Comment by hernan-arga** [comment]
Listo gracias, ya me lo aclaro uno de los otros ayudantes que sumar la ráfaga  y seguir ejecutando el mismo esta mal sino que lo que debería hacer es contar con un timestamp y replanificar.

**Comment by hernan-arga** [comment]
Listo gracias, ya me lo aclaro uno de los otros ayudantes que sumar la ráfaga  y seguir ejecutando el mismo esta mal sino que lo que debería hacer es contar con un timestamp y replanificar.
