### ISSUE TITLE
Problemas con comando dd para crear el archivo del fs

### ISSUE THREAD

**Issue by mesaglio** [sisoputnfrba/foro#1515]
Buenas, estoy en fs y estuve como 2 semanas sin poder usar el comando dd. 
Copiaba muy lento usando el comando como lo hizo @MaximilianoFelice  en el video de la tercer charla.
```bash
 dd if=/dev/random of=fs.bin bs=1024 count=10240
```
A lo que me contesto por mail, que en vez de utilizar /dev/random use /dev/zero.
La diferencia esta que llena el archivo con '0' en vez de bytes randoms.
El comando seria:
```bash
 dd if=/dev/zero of=fs.bin bs=1024 count=10240
```
creando un archivo binario de 10Mb.
Espero que alguno le sirva.

**Comment by mgarciaisaia** [comment]
👋 Si quisieras/necesitaras llenar el archivo con información random, podés usar `/dev/urandom` en lugar de `/dev/random`.

No estoy seguro de qué diferencia hay entre ambos, pero creo que `/dev/random` te provee bytes random (por lo que se bloquea esperando conseguir entropía antes de seguir devolviéndote bytes), mientras que `/dev/urandom` usa la entropía que tiene (y que permanentemente se va actualizando) para generar bytes pseudorandom a partir de ella.

Pero capaz estoy re chamuyando, eh.

La posta sería leer todo [este post](https://www.2uo.de/myths-about-urandom#estimate). Y entenderlo. Yo dejé a mitad de camino lo primero, y ni hablar de lo segundo.

Pero `/dev/urandom` anduvo, y rápido.
