### ISSUE TITLE
Memoria - Tabla de segmentos por hilo?

### ISSUE THREAD

**Issue by ncoen97** [sisoputnfrba/foro#1516]
👋 ¡Hola!
En el tp hay una imagen que muestra las tablas de segmentos por hilo y no sabemos si fue un error de escritura o si es realmente asi.
![issueeeee](https://user-images.githubusercontent.com/7952790/67423431-a7349f80-f5aa-11e9-9343-2ff5ca9c5141.jpg)

Teniamos entendido que la tabla de segmentos es por programa, ya que en otra parte del tp dice:

> ### Espacio de direccionamiento virtual
> Esta estructura administrativa será definida a nivel de cada programa y en ella se podrán ver todos los segmentos que posee cada uno en memoria.

**Comment by tferraro** [comment]
Buenas!

Está puesto para evitar confundir que si lo hacés interactuar con Hilolay, pueden ser hilos y no necesariamente el proceso completo.

Claramente no termino de ayudar a simplificar 😆 

A efectos prácticos programa == hilo

**Comment by ncoen97** [comment]
Lo que me confunde es que hilo != programa porque el diagrama principal tiene varios programas con varios hilos cada uno y dice:

> la función que realiza el init de libMUSE debe estar llamada una única vez por programa y al inicio del mismo, no se debe realizar para cada uno de los hilos.

Yo tenia entendido que hay una tabla de segmentos por programa y que si varios hilos hacen muse_alloc van todos a la misma tabla de segmentos.

**Comment by fernandosierra9** [comment]
Hola. 
Nosotros tenemos la misma duda.
Nosotros lo q hicimos fue mandar el pid del hilo/programa siempre por sockets , asi q los hilos usan el mismo sockets, pero tuve q sincronizar para mandar las solicitudes una a la vez , lo q me pasa es q termina siendo sincronico. Y el pid te dice q a q programa hilo/pertence  en muse y despues buscamos/creamos el segmento q nos piden.
Saludos

**Comment by IvanDL95** [comment]
> Yo tenia entendido que hay una tabla de segmentos por programa y que si varios hilos hacen muse_alloc van todos a la misma tabla de segmentos.

Algo parecido me dijeron en las charlas. Pregunté si tenía que hacer métricas por cada hilo o por cada proceso y me respondieron que era por cada proceso. Además, que por la interfaz de libmuse no había forma de que sea hilos ya que no tiene forma de conocer los hilos. Hace muse_init una vez por proceso (también me dijeron esto), entonces hay un socket por proceso, y además ninguna función recibe como parámetro el ID del hilo, ni siquiera muse_init.

**Comment by afilgueira** [comment]
Las tablas de segmento son por proceso, al margen del ejemplo "raro" que comentaba Tom. Saludos
