### ISSUE TITLE
Consulta sobre las entradas de directorios del FS

### ISSUE THREAD

**Issue by ncoen97** [sisoputnfrba/foro#1517]
Buenas, tengo una duda respecto a las entradas de directorios del fs.
En la teoria, las entradas del UFS tienen numero de inodo, nombre del archivo y tipo de archivo. En el tp tenemos que mantener esa info, o hay algun requerimiento de cantidad de entradas de directorio por bloque de dato??

@mesaglio

**Comment by afilgueira** [comment]
Hola, en breve vamos a subir info al respecto, porque notamos que no está claro. Saludos!

**Comment by afilgueira** [comment]
@ncoen97 subimos esto. Avisá cualquier cosa!
