### ISSUE TITLE
Muse - Estructura heap

### ISSUE THREAD

**Issue by fernandosierra9** [sisoputnfrba/foro#1518]
Buenas! Nos surgió una duda con respecto a un caso particular de liberación de un bloque de bytes dentro de un segmento.
El caso sería el siguiente:
Siendo las estructuras administrativas de 5 bytes, supongamos que el diagrama inicial sería éste:

 5 bytes -> bool: true -  size: 22
 22 bytes -> datos
 5 bytes -> bool: true -  size: 95
 95 bytes -> datos
 5 bytes -> bool: true -  size: 46
 46 bytes -> datos

Luego, se solicita la liberación del bloque de 95 bytes por peticion de un free , quedaríamos en la situación siguiente:

 5 bytes -> bool: true -  size: 22
 22 bytes -> datos
 5 bytes -> bool: false -  size: 95
 95 bytes -> free mem
 5 bytes -> bool: true -  size: 46
 46 bytes -> datos
 
Acto seguido, llega un pedido para alocar 91 bytes. Recorriendo la tabla de segmentos, encontramos 95 bytes libres en el medio, por lo que devolvemos la posición inicial del bloque de 95 bytes libres, pasando a la siguiente situación:

 5 bytes -> bool: true -  size: 22
 22 bytes -> datos
 5 bytes -> bool: true -  size: 91
 91 bytes -> datos
 **4 bytes -> libres q sobraron**
 5 bytes -> bool: true -  size: 46
 46 bytes -> datos

 Esto representa un problema ya que al sobrar 4 bytes “en el medio”, no puedo utilizarlos para ubicar otra estructura y eso “rompe” la lectura secuencial.
Pero también si es entre 1 y 4 bytes va a pasar lo mismo , una forma de resolverlo se nos ocurrió q al momento de buscar un espacio , si nos llega 91 bytes como el ejemplo , entonces se le suma 5 bytes para la estructura ,q va a representar los bytes libres que sobraron después de reservar el espacio pedido por alloc (solo en caso de q el segmento ya exista y no q el proceso no tengo ningún segmento asociado) .
 Y existe otro caso cuando esos bytes q sobran están al final del segmento pero con un if y sabiendo el comienzo y limite del segmento puedo saber si estando casi al final existe o no otra estructura libres. 
Esto es importante también por q si sobraron 4 bytes y el segmento se puede agrandar , se deberia aprovechar esos 4 bytes y sumárselo a la pagina pedida .
 
Espero su respuesta.
Saludos

**Comment by afilgueira** [comment]
A fines prácticos, si no podés poner los bytes del malloc + su metadata, no tenés espacio suficiente en ese hueco. Saludos!

**Comment by cristianicolasuarez** [comment]
Continuando con un poco el tema de este issue me surgió la duda de que debería pasar cuando, suponiendo que todo un segmento esta lleno excepto los últimos 11 bytes. haciendo un muse_alloc(5), lo cual impactaría en el segmento como 5 bytes de metadata mas 5 bytes de datos, que debo hacer con ese byte restante? debería tener 5 bytes para una "ultima metada" cuyo tamaño sea cero? o simplemente dejarlo como fragmentacion interna al segmento?
