### ISSUE TITLE
Funciones de Fuse

### ISSUE THREAD

**Issue by camilamamani** [sisoputnfrba/foro#1519]
Hola, les hago una consulta sobre las funciones a implementar de Fuse, sobre las funciones en el enunciado dice que implementemos las necesarias para lo que nos piden pero a mi me surge la duda cuando para una operación especifica tengo más de una función 

Por ejemplo para lectura tenemos fread y read ¿Hay algún criterio que debamos tener en cuenta para elegir una u otra o ambas? Entiendo que fread por adentro hace un read ¿Deberíamos implementar la más genérica?

Gracias, saludos

**Comment by tferraro** [comment]
Buenas ! :wave:

Hay un issue ahí, `read` es la syscall 😆 y `fread` es solamente una función que se construye sobre esa syscall.

Ustedes tienen que implementar las primitivas de fuse. Todas las que soporta estan en la estructura `fuse_operations` (Chusmeate: https://github.com/libfuse/libfuse/blob/master/include/fuse.h#L299). Ahora, no necesariamente tienen que implementar todas, porque hay algunas que no vamos a usar en nuestra spec de Filesystem. Queda como tarea para la casa hacer ese análisis 🙂 

Saludos!

**Comment by camilamamani** [comment]
Si ya me parecía que fread no tenía sentido en fuse. Gracias!
