### ISSUE TITLE
Multithreading en FUSE

### ISSUE THREAD

**Issue by ntaboada** [sisoputnfrba/foro#1521]
Buenas, como va?

Ando teniendo un par de problemas al hacer transferencia de mensajes entre SAC-cli y SAC-server. Va, en realidad si levanto un unico sac-cli que se comunique con el sac-sever esta andando bien. El problema es cuando quiero levantar otra instancia de mi SAC-cli. El error que estoy teniendo es:

`fuse: bad mount point: /fuse_test: Input/output error`

Es decir, levanto una primera instancia de mi sac-cli y anda todo joya (se levanta bien FUSE, y cuando pruebo mandar una simple mensaje, en alguna de las funciones que defini para fuse al sac-server el mismo llega bien). Cuando levanto otra instancia, teniendo la primera corriendo, recibo ese error.

Investigando un poco, lei que por default FUSE levanta multithreading (salvo que le pases el flag -
s, cosa que no estoy haciendo). Para darles un poco mas de contexto les muestro un poco de codigo, y como estoy levantando mis sac-cli (los que tienen fuse implementado).

Asi levanto mis CLI:

```./sac_cli.exe -d -o direct_io --Disc-Path=RUTA_DISCO ./fuse_test```

Donde `:/sac_cli.exe` es el ejecutable, `-d` es el parametro para debugging, `-o direct_io` son los flags que indican en el tp que pasemos para deshabilitar la cache, `--Disc-Path=...` es un parametro que yo elijo pasar para definir donde va estar la ruta del disco y por ultimo `./fuse_test` donde monto fuse.

Este es el main de mis sac-cli:

```
int main(int argc, char *argv[]) {
	struct fuse_args args = FUSE_ARGS_INIT(argc, argv);

	// Limpio la estructura que va a contener los parametros
	memset(&runtime_options, 0, sizeof(struct t_runtime_options));

	// Esta funcion de FUSE lee los parametros recibidos y los intepreta
	if (fuse_opt_parse(&args, &runtime_options, fuse_options, NULL) == -1){
		perror("Invalid arguments!");
		return EXIT_FAILURE;
	}
        ....
	sac_cli_fd = socket_connect_to_server(ip_sac_server, puerto_sac);

	if (sac_cli_fd < 0) {
		printf("There was an error");
		socket_close_conection(sac_cli_fd);
		return -1;
	}
	// Esta es la funcion principal de FUSE
	return fuse_main(args.argc, args.argv, &sac_operations, NULL);
}
```

Alguna idea?

PD: Esta primera version tengo contenido todas las inicializaciones de FUSE dentro del main. A fines practicos, hice esto para poder testear las cosas mas facilmente. Luego, voy a refactorizar este main y definir una funcion que contenga todo esto (ya que como bien se hablo, todos los CLI van a ser libraries, osea no va haber main).

**Comment by tferraro** [comment]
Buenass :wave:, acá veo 2 particularidades que no creo que estés tomando en cuenta:
1. Por definición del tp, no necesitás más de un sac-cli por máquina donde estés ejecutando.
2. Por definición fuerte del SO, solamente podés tener un único filesystem montado en el mismo path. Podés tener varios que implementen FUSE, pero solo en diferentes mount points.

Masomenos se entiende porque encontraste ese error?

**Comment by ntaboada** [comment]
Primero que nada, gracias por la pronta respuesta @tferraro.

Entiendo lo que planteas (y es algo que me termine dando cuenta al final). Lo que si no sabria entonces es como poder probar tener multiples clientes (por ejemplo, diferentes sac-cli leyendo y escribiendo a la vez, por lo que imagino que haya que sincronizar con semaforos). O quiza es algo  que no van a probar/evaluar?

**Comment by afilgueira** [comment]
Hola, con varias máquinas pegándole como cliente al mismo server. Saludos!

**Comment by tferraro** [comment]
@ntaboada te sirvieron las respuestas? Como venís con eso?

Recordá de cerrar el issue si se resolvió :D

**Comment by ntaboada** [comment]
@tferraro perdon aca estoy. En parte si me ayudaron las respuestas, pero todavia sigo con una ultima duda (en base a lo que me respondio @afilgueira). 

Entiendo que pegandole con varios clientes (de distintas maquinas) voy a poder ver como el server handlea a estos multiples sac_cli.

El tema y la pregunta es como yo, en mi ambiente local, con 1 sola maquina (que es con la unica que cuento) y en la que solo puedo levantar 1 solo cliente por todo esto que venimos hablando... como hago para simular el mismo contexto de multiples clientes que ustedes van a evaluar en la entrega con todas estas condiciones?

**Comment by mesaglio** [comment]
Yo lo que hice para probar con multiples clientes, fue montando el sac-cli en otra carpeta.
Por ejemplo:
 mkdir fs
 mkdir fs2

./sac_cli.exe fs -d -o direct_io --Disc-Path=RUTA_DISCO
./sac_cli.exe fs2 -d -o direct_io --Disc-Path=RUTA_DISCO 
 
No se para que usas disc-path, si es el disco del SAC-Server creo no vas a poder referenciarlo porque esta en otra pc.

PD: el comando que yo uso para levantar el SAC-CLI es ./sac_cli fs -f -d -s 
que es el uso Maxi en la presentacion de fs

Saludos, espero que te sirva :grin:

**Comment by tferraro** [comment]
Colgamos un poco ese post😁
Particularmente porque la respuesta de arriba es una linda alternativa.
Te sirvio?

**Comment by iago64** [comment]
8 dias sin respuestas, asumimos que el tema esta ok.
Cualquier cosa pueden reabrir el tema :)
