### ISSUE TITLE
duda: error: #error Please add -D_FILE_OFFSET_BITS=64 to your compile flags!

### ISSUE THREAD

**Issue by mariekuric** [sisoputnfrba/foro#1522]
👋 ¡Hola!
Hola, tengo una duda. Instalé fuse, monté el file system, escribí en el filesystem. Y cuando quise ejecutar fuse-example.c para mostrar por pantalla me tiró este error: error: #error Please add -D_FILE_OFFSET_BITS=64 to your compile flags! 
Cómo podría solucionarlo, gracias!!

**Comment by tferraro** [comment]
👋 
Recordaba haber visto alguna vez en el pasado y resultó que, _ya le pasó a alguien 3 años antes_ 😆 
https://github.com/sisoputnfrba/so-fuse-pokemon-example/issues/1

Fijate si el intercambio de mensajes ahí te sirve 👍

**Comment by mariekuric** [comment]
Ok, muchas gracias!
