### ISSUE TITLE
Duda Sac-Cli y Interacción Sac-Cli y Sac-Server

### ISSUE THREAD

**Issue by AxelDellavechia** [sisoputnfrba/foro#1523]
Hola buenos días,

Sac-Cli va ser encargado de contener las definiciones de fuse y ejecutarlo (Esto lo vengo trabajando medio atrasado para mi gusto), adicionalmente se conectará por sockets al Sac-Server que hará uso normal del SO.

Me queda la duda entonces como se manejaría si llega un pedido de ls al Sac-Cli para fuse haría (momentáneamente hardcode) : 

static int accesoAlContenido(const char *path, char *buf, size_t size, off_t offset, struct fuse_file_info *fi) {
size_t len;
(void) fi;
if (strcmp(path, DEFAULT_FILE_PATH) != 0) // DEFAULT_FILE_PATH cambiar por una una función que devuelva el archivo creado
return -ENOENT;
len = strlen(DEFAULT_FILE_CONTENT);
if (offset < len) {
if (offset + size > len)
size = len - offset;
memcpy(buf, DEFAULT_FILE_CONTENT + offset, size); //Esta es la función que nos permite acceder al contenido de un archivo txt por ejemplo si la comentamos mostrará basura
} else
size = 0;
return size;
}

Ahora si llega una especificación de LS fuera del dominio de FUSE ¿No entiendo que debería hacerse?

Un ejemplo de interacción sería:
1) Inicia el FileSystem Vacio
2) Se crea un directorio o archivo 
3) Se le comunica al Sac-Server que se creo un archivo o directorio para que sea registrado en la tabla de nodos y bitmap

Otra consulta que me genera dudas:

Ejemplo mkdir -> fuse define el prototipo -> int crearDirectirio(const char *path, mode_t mode)  ¿Podemos terminar invocando mkdir para hacer la creación  o debemos hacer nuestra propia implementación de mkdir y posteriormente darle los permisos correspondientes?

Si tenemos que acceder a funciones de memoria ¿deberiamos usar las de libMuse?

Desde ya muchas gracias.

**Comment by tferraro** [comment]
👋 
>Ahora si llega una especificación de LS fuera del dominio de FUSE ¿No entiendo que debería hacerse?

No va a llegar, el SO solo te va mandar pedidos que son para el FS que está en el punto de montaje adecuado :). Eg, si estamos parados en `/mnt/sac`, que sería nuestro "/" y hacemos `ls ../otro/dir`, la petición no le va a llegar a la implementación de fuse 🙂 

> Ejemplo mkdir -> fuse define el prototipo -> int crearDirectirio(const char *path, mode_t mode) ¿Podemos terminar invocando mkdir para hacer la creación o debemos hacer nuestra propia implementación de mkdir y posteriormente darle los permisos correspondientes?

La creación de ese directorio va a ser dentro del FS de SAC 🤷‍♂ , no les va a servir el mkdir posta, porque ustedes manajean los directorios en la estructura de su filesystem.
Ahora, si es para probar, pos prueben 😉 

> Si tenemos que acceder a funciones de memoria ¿deberiamos usar las de libMuse?

![image](https://i.pinimg.com/originals/47/4b/02/474b02e59d9951fc9a57060e13338ed6.jpg)

**Comment by AxelDellavechia** [comment]
Perfecto estaba comprendiendo de forma incorrecta el alcance de lo que debería estar haciendo el Sac-Cli.  La idea central es por ejemplo es que interprete:

Listar archivos y directorios --> esto se traduce al comando "ls" 
Crear directorios -> esto se traduce al comando "mkdir"  
Eliminar directorios y archivos --> esto se traduce al comando "rm" // "rmdir" (si esta vació el directorio)
Crear archivos  --> esto se traduce al comando "cat > archivo.txt"
Leer y Escribir --> esto se traduce al comando "vi" (editor de texto) y que tenga los permisos de escritura cualquier usuario.
Describir directorios ¿A que se refiere? ¿El comando ls?

Entonces cada comando por ejemplo cuando me pidan un ls sobre mi FS contactare al Sac-Server que del archivo gigante me va a pasar la porción que corresponda con la consulta ¿Correcto?

Gracias y disculpa si la consulta parece muy atrasada para la epoca que nos encontramos.

**Comment by tferraro** [comment]
Buenas!

Particularmente los comandos de bash no se matchean 1 a 1 con las syscalls de Filesystems, no necesariamente un "ls" va a describir solamente la información de un directorio, ni viceversa. Lo único que hace el TP es describir casos de uso que mínimamente deben existir.

(De hecho, `rm` `cat` `vi` suelen hacer muchísimas más llamadas al FS que el matcheo que haces).

**Comment by AxelDellavechia** [comment]
Buenas tardes,

Entiendo lo que quiero hacer ahora para pruebas de comunicación entre sac-cli y sac-server es por ejemplo crear un directorio x sobre y le llegue el mensaje al sac server.

Pero al momento de definir mi operación:

int crearDirectirio(const char *path, mode_t mode)
{
    //char fpath[PATH_MAX];

    return mkdir(path, mode) ;
}

bastante tonta al principio siempre recibo el error  "Description	Resource	Path	Location	Type
multiple definition of `crearDirectirio'	funcionesFuse.c	/SAC_Cli/src	line 137	C/C++ Problem
"

¿Tendrás una idea de porque? 

Gracias

**Comment by AxelDellavechia** [comment]
Buenas noches ¿Cómo están?

Me esta surgiendo mas dudas de conectivad entre los componentes por ejemplo mi main es así:

int main(int argc, char *argv[]) {

	memset(&runtime_options, 0, sizeof(struct t_runtime_options));
	struct fuse_args args = FUSE_ARGS_INIT(argc, argv);
	crearLogger();
	leerArchivoDeConfiguracion(RUTA_CONFIG_MEM);
	if (	conectarConSacServer()	)	{
			handshake_cliente(fdSacServer, "SacCli");
	}
	if (fuse_opt_parse(&args, &runtime_options, fuse_options, NULL) == -1){
			/** error parsing options */
			perror("Invalid arguments!");
			return EXIT_FAILURE;
	}
	return fuse_main(args.argc, args.argv, &linuse_oper, NULL);
}

Yo me conectaría con el sac Server en primera instancia con el saludo pero por ejemplo si fuse ingresa a la función de mkdir que tiene un prototipo "int (*mkdir)	   (const char *, mode_t);"

Entiendo que debería poder conectarme con el servidor para decirle hace tal cosa mi pregunta es se le puede pasar a fuse un socket como parametro extra?  si es posible me podrían orientar porque sino en cada llamada tendría que abrir una conexión y cerrarla

Ahora mi código actual es :

int crearDirectirio(const char *path, mode_t mode )
{
    //char fpath[PATH_MAX];

	int socketServer , respuesta ;

	socketServer = conectarSocket(socketServer, configSacCli->ipSacServer, configSacCli->puertoSacServer);

    enviarPorSocket(socketServer,"Te envio un MKDIR",sizeof("Te envio un MKDIR"));

    cerrarSocket(socketServer);

    return respuesta ;
}

y el log de compilación esta en [compilacionSacCli.txt](https://github.com/sisoputnfrba/foro/files/3791836/compilacionSacCli.txt)

Desde ya muchas gracias y disculpen la molestia que les pueda ocasionar.

Atte Axel Dellavechia

**Comment by AxelDellavechia** [comment]
Bueno luego de sufrir un par de horas descubrí que el problema venia con el tema de la definiciones de las funciones, separé en un .h y un .c y eso me soluciono el problema. Solo me queda la duda del tema de sockets si hay una forma mas facil que abrir y cerrar siempre por metodo.

Desde ya muchas gracias.
