### ISSUE TITLE
Muse sin espacio en muse_alloc/map

### ISSUE THREAD

**Issue by ncoen97** [sisoputnfrba/foro#1526]
👋 ¡Hola!
Nos preguntamos que hay que hacer si no queda mas espacio en la UPCM cuando se hace un muse_alloc o un muse_map. Desde muse devolvemos un error a libmuse, pero en libmuse el muse_alloc retorna un uint32_t, por lo que no podemos devolver -1 y tampoco 0 porque es una dirección valida. Qué deberíamos hacer? No encontramos nada en la consigna con respecto a esto.

**Comment by tferraro** [comment]
Buenas!

La interfaz de muse_alloc y muse_map tiene que ser la misma que sus
contrapartes reales (capas sin tanto flags, pero se entiende).

Como hace malloc ante ese error?

**Comment by ncoen97** [comment]
Entonces retorno NULL, gracias.
