### ISSUE TITLE
Sockets en el planificador

### ISSUE THREAD

**Issue by hernan-arga** [sisoputnfrba/foro#1527]
Buenas, tengo una duda en el planificador:
¿Es necesario hacer multihilos para atender las peticiones a SUSE o con un select comun me alcanza? porque se que Sac-Server necesita multihilos pero no se si con el planificador es igual. ¿Deberia ser multihilos para que la peticion de un proceso no bloquee la otra? ¿Como deberia sincronizarlos?

**Comment by afilgueira** [comment]
Buenas, una petición de un proceso (con sus ULTs) no debería bloquear a las de los otros. Ahora, tenés varias formas de solucionar esto, sin la necesidad de hacerlo multihilo. Se te ocurren un par de opciones más? Saludos!

**Comment by hernan-arga** [comment]
Según lo que leo de select, este no es bloqueante por lo que no necesitaría multihilos y lo podría hacer con un select normal ¿está es una solución?

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by afilgueira** [comment]
Hola, perdón por la demora. Recién veo la repregunta. Es una opción!

**Comment by hernan-arga** [comment]
Buenísimo, gracias.
