### ISSUE TITLE
suse_close

### ISSUE THREAD

**Issue by Fedryus** [sisoputnfrba/foro#1528]
Hola, estaba trabajando con `suse_close` y me surgieron algunas dudas al leer el enunciado.

¿La función actúa sobre un hilo en estado EXEC al que da fin? ¿O dicho hilo que pasamos por parámetro y queremos finalizar puede estar, por ejemplo, en READY, NEW, etc?

Saludos!

**Comment by tferraro** [comment]
👋 Buenas!

Es así por 2 motivos:
1. Por lo general, las funciones de close suelen recibir por parámetro el recurso a cerrar, para evitar mantener un estado global.
2. Teóricamente, deberías poder transicionar desde cualquier estado a Close.

Si bien (2.) es bastante cierto, hilolay posiblemente solo lo llame desde el contexto EXEC -> CLOSE 😛 .

**Comment by Fedryus** [comment]
Ok, a eso quería llegar.
¿Entonces que ocurriría si a `suse_close` le pasó por parámetro un hilo que no está en EXEC?

Cito al enunciado: "Cada programa representará una CPU virtual. Eso implica que solo existirá un único ULT en estado EXEC por programa"

Supongamos que el programa 1 está ejecutando el hilo 4, y desde el mismo programa 1 hago suse_close(5). El hilo 5 no está en EXEC, ¿que ocurre entonces?

**Comment by afilgueira** [comment]
El hilo 5 pasaría al estado finalizado que estén modelando. Un poco lo que decía Tom en `2.`. Y como también decía, probablemente nuestras pruebas no lo incluyan.

Saludos!

**Comment by Fedryus** [comment]
Perfecto, gracias a ambos por la respuesta!
