### ISSUE TITLE
Consulta sobre muse_cpy

### ISSUE THREAD

**Issue by FrodriguezSandez** [sisoputnfrba/foro#1529]
👋 ¡Hola!

int muse_cpy(uint32_t dst, void* src, int n)

Tiene sentido que se quiera hacer un cpy de alguna parte de la memoria y pise datos en cualquier parte del segmento? porque correría riesgo de que me pise un heap_metadata, y me desacomode toda la estructura del segmento

**Comment by iago64** [comment]
Buenas buenas!

Si haces la analogia con el memcpy en C, te controla que no estes mandandote un cagadon monumental o simplemente hace la copia y si la pifias con suerte te tira un segment fault?

Abrazo!

**Comment by FrodriguezSandez** [comment]
Gracias!
