### ISSUE TITLE
Funcionamiento del hilo inicial en planificador

### ISSUE THREAD

**Issue by hernan-arga** [sisoputnfrba/foro#1530]
Buenas, haciendo pruebas me estoy dando cuenta de que en mi implementacion de suse debo estar haciendo algo mal porque si yo mando dos hilos a ejecutar y el segundo termina antes que el primero no hay problema pero si es al reves el segundo no se termina de ejecutar.
Mi pregunta es: cuando el hilo main (el hilo 0 de hilolay) se ejecuta ¿pide un join por cada hilo que se haya creado?. De ser asi ¿yo no tendria que liberar el hilo main hasta que hayan terminado todos los hilos que se hayan creados en mi programa? o,sea ¿podria tener un hilo que este bloqueado por mas de 1 hilo?

Gracias, saludos.

**Comment by tferraro** [comment]
👋 Buenas!

Los hilos de hilolay no tienen el concepto de hilos detachables de pthread. Todos los hilos son joineables, por lo que si un hilo lanza otro hilo, debe antes de terminar joinearlo 😄 (por buenas prácticas).
Si el programador no joinea, la api de hilolay no se asegura comportamiento determinístico.
