### ISSUE TITLE
Esperando en suse_join

### ISSUE THREAD

**Issue by Fedryus** [sisoputnfrba/foro#1531]
Buenas, tenemos una duda con `suse_join` desde hace varios días...

¿El hilo que pasamos por parámetro entra automáticamente en EXEC una vez se bloquea el que hizo el join?, y de ser así ¿nosotros dentro de `suse_join` lo pondríamos a ejecutar? (a traves de un schedule_next o forzándolo a salir de ready) ¿o de eso se encarga hilolay?

La pregunta surge porque entendemos que el hilo bloqueado se va a desbloquear una vez finalice el otro, pero no sabemos que ocurre en determinada "espera". 

Intentamos varias soluciones pero no terminamos de comprenderlo.

Gracias de antemano!

**Comment by tferraro** [comment]
Buenas! Voy a tratar de responderlo por partes:

> ¿El hilo que pasamos por parámetro entra automáticamente en EXEC una vez se bloquea el que hizo el join?, y de ser así ¿nosotros dentro de suse_join lo pondríamos a ejecutar? (a traves de un schedule_next o forzándolo a salir de ready) ¿o de eso se encarga hilolay?

Nay, la especificación que designa la lib es que debe marcar el hilo como bloqueado :D

> La pregunta surge porque entendemos que el hilo bloqueado se va a desbloquear una vez finalice el otro, pero no sabemos que ocurre en determinada "espera".

No te sigo, a que te referis con "que ocurre con determinada espera"? Recordá que SUSE no ejecuta realmente nada, solo es un planificador que por naturaleza almacena el estado de los hilos. Si un hilo está bloqueado, vos no lo usás para planificar, por ende, si nunca se ejecuta de nuevo, genera el efecto de estar bloqueado.

**Comment by Fedryus** [comment]
Perfecto, gracias por la aclaración!
