### ISSUE TITLE
Consulta muse_map

### ISSUE THREAD

**Issue by ncoen97** [sisoputnfrba/foro#1532]
👋 ¡Hola!
Supongamos que hago un muse_map para "archivo.txt", al principio se crean las paginas pero los datos quedan en archivo.txt. Cuando se haga un muse_get de alguna de esas paginas, se van a traer los datos necesarios a la UPCM. Una vez que el algoritmo de clock modificado elige alguna de estas paginas para sacarla de memoria, las paginas pasan a memoria virutal? o se "fuerza" un muse_sync para esas paginas y se escriben en archivo.txt? porque tenia entendido que la unica forma de bajar las paginas devuelta al archivo era que desde el programa usuario se haga un muse_sync.

**Comment by gastoncastineira** [comment]
Buenas

Basandonos en lo que dice [este muchacho](https://stackoverflow.com/questions/2226740/mmap-writes-to-file-on-disksynchronous-asynchronous), los cambios son a nivel página y no hay garantía que se persistan al archivo antes de un sync (pero pueden hacerlo). En la vida real hay otras cuestiones de hardware que permitan que eso tenga sentido (porque caché). Para este trabajo práctico vamos a asumir que los cambios se hacen solo cuando se haga un sync()

**Comment by ncoen97** [comment]
Gracias!
