### ISSUE TITLE
Consulta sobre Sac-tool

### ISSUE THREAD

**Issue by Santiago-Lovelli** [sisoputnfrba/foro#1533]
Hola, queria saber si el repo de las sac-tool esta incompleto o si es que hay que codiarlo cada uno a su forma. Como en la parte del enunciado dice "...la cátedra provee las SAC-Tools..." pero el repositorio esta en forma genérica (dump y format en blanco), no se si es que nos proveen la estructura o falta que suban los scripts al repositorio.

**Comment by tferraro** [comment]
Buenas!

Las SAC-Tools son 2 herramientas para poder probar el filesystem. Una para ya formatear uno y probar la implementacion para volver a inicializarlo; y otra para mostrar el contenido de los metadatos del FS 🙂

**Comment by Santiago-Lovelli** [comment]
No habia clonado el repo, solo lo habia visto en github. 👍
