### ISSUE TITLE
Tamaño bitmap SAC

### ISSUE THREAD

**Issue by Santiago-Lovelli** [sisoputnfrba/foro#1534]
Hola, buenos días, buenas tarde o buenas noches. En la ultima versión del enunciado (La v1.3) en la parte de calcular el tamaño del bitmap la cuenta dice: 
TamañoBitmap=(TamañoDelDisco/TamañoDelBloque/8)/TamañoDelBloque
Pero en el momento de la charla (y no me acuerdo hasta que versión del enunciado era:
TamañoBitmap=(TamañoDelDisco/TamañoDelBloque/8)

Quería consultar si esta bien el cambio y en ser así por que seria? tengo entendido que el bitmap es para direccionar cada bloque del disco así que con TamañoDelDisco/TamañoDelBloque ya tengo la cantidad de bloques en disco, lo que al dividirlo en 8 obtengo la cantidad de bytes que ocupara el bitmap (por que necesita solamente un bit para referenciar a un bloque). 
No entiendo el motivo de dividir todo por el TamañoDelBloque.

**Comment by tferraro** [comment]
👋 Buenas!

A lo que te estás refiriendo en el enunciado es a esta parte?
![image](https://user-images.githubusercontent.com/7110539/68172610-ed004900-ff56-11e9-819f-ee8095e4377c.png)

Porque si es así, revisá que está hablando de la **cantidad de bloques** que ocupa el bitmap, no del tamaño 😛 .
Para el tamaño en bytes del bitmap, si es el ejemplo que comentás 🙂

**Comment by Santiago-Lovelli** [comment]
Si, era eso, gracias 😋.
