### ISSUE TITLE
Consulta Fuse mkdir

### ISSUE THREAD

**Issue by AxelDellavechia** [sisoputnfrba/foro#1535]
Hola buenos días ¿Cómo están?

Les hago una pequeña consulta estoy implementando las funciones de fuse para la comunicación con el SAC-Server.

En primera instancia para ver como llegaban los parámetros de fuse implemente de la siguiente manera:

```c
int sac_mkdir(const char *path, mode_t mode) {

	mkdir(path, mode);

	log_info(logger,"el PATH que viene como parametro de sac_mkdir retorno: %s\n", path);

	log_info(logger,"el MODE que viene como parametro de sac_mkdir retorno: %d\n", mode);

	respuesta = enviarPorSocket(socketServer,"Te envio un MKDIR",sizeof("Te envio un MKDIR"));

	log_info(logger,"sac_mkdir retorno: %d\n", respuesta);
	
    return respuesta ;
}
```

Los pasos para probar son:

1. Levantar Fuse --> utnso@ubuntu-server:~/workspace/SAC_Cli/Debug/tmp$ valgrind ./SAC_Cli tmp -d -s -odirect_io
2. Ingresar al directorio donde esta Fuse ->utnso@ubuntu-server:~/workspace/SAC_Cli/Debug$ cd tmp
3. Ejecutar un mkdir --> utnso@ubuntu-server:~/workspace/SAC_Cli/Debug/tmp$ mkdir pepe
mkdir: cannot create directory ‘pepe’: Operation not permitted

FUSE LOG

```
LOOKUP /pepe
getattr /pepe
   unique: 162, error: -2 (No such file or directory), outsize: 16
unique: 163, opcode: MKDIR (9), nodeid: 1, insize: 53, pid: 2892
mkdir /pepe 0775 umask=0002
[SOCKETS] No se pudo enviar correctamente los datos.
   unique: 163, error: -1 (Operation not permitted), outsize: 16
unique: 164, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 15194
```

¿Tendrán idea porque?

Gracias

**Comment by mgarciaisaia** [comment]
👋 Ahí en el log hay un mensaje "tuyo" (de tu biblioteca de sockets, al menos) que dice "No se pudo enviar correctamente los datos". Si cruzás eso, con el dato de que tu función `sac_mkdir` devuelve lo que devuelva `enviarPorSocket`, parece probable que tu función le esté devolviendo un error a FUSE.

El tema es que no tenemos la implementación de `enviarPorSocket` acá a mano para ver, ni tenemos más info de qué falló con el envío. Así que vas a tener que averiguar eso.

Recapitulando: el comando `mkdir` en la consola _eventualmente_ ejecuta la syscall `mkdir`, pidiéndole al kernel que cree un directorio. El kernel nota que el directorio a crear está dentro del punto de montaje de tu FS, por lo que le envía el pedido de creación a FUSE. FUSE detecta que es tu proceso el que administra ese punto de montaje, por lo que ejecuta tu función `sac_mkdir`. Como tu función `return`ea un código de error (probablemente `0` sea éxito, y cualquier otro valor sea un error - chequealo en la doc de FUSE), FUSE le devuelve un fallo al kernel, quien le devuelve un fallo al comando `mkdir`, quien te muestra el error en la consola.

**Comment by AxelDellavechia** [comment]
Gracias por la pronta respuesta, efectivamente hay un error de comunicación porque casualmente lo tengo bajo al sac servidor pero si dejo todo comentado a solo :

int sac_mkdir(const char *path, mode_t mode) {

	// log_info(logger,"el PATH que viene como parametro de sac_mkdir retorno: %s\n", path);

	// log_info(logger,"el MODE que viene como parametro de sac_mkdir retorno: %d\n", mode);

	// respuesta = enviarPorSocket(socketServer,"Te envio un MKDIR",sizeof("Te envio un MKDIR"));

	// log_info(logger,"sac_mkdir retorno: %d\n", respuesta);

    return mkdir(path, mode); ;
}

Fuse muestra:

LOOKUP /pepe
getattr /pepe
   unique: 150, error: -2 (No such file or directory), outsize: 16
unique: 151, opcode: MKDIR (9), nodeid: 1, insize: 53, pid: 16136
mkdir /pepe 0775 umask=0002
   unique: 151, error: -1 (Operation not permitted), outsize: 16

Creo que el problema viene con los permisos con que se levanta la carpeta del FS de Fuse pero no estoy ubicando donde ver esa parte.

**Comment by mgarciaisaia** [comment]
Hay un tema de puntos de vista ahí.

Por lo que dicen tus logs, tu valor de `path` es `/pepe`. ¿Por qué? Porque tu proceso se encarga únicamente de tu punto de montaje (no de _todo_ el sistema de archivos de tu máquina), entonces la interfaz de FUSE dice "yo te voy a pasar los paths relativos a tu punto de montaje".

Vos en la consola hiciste `mkdir pepe`, con `~/workspace/SAC_Cli/Debug/tmp` como tu directorio actual. Entonces, el resultado es que hay que crear `/home/utnso/workspace/SAC_Cli/Debug/tmp/pepe`. El kernel se da cuenta de que en `/home/utnso/workspace/SAC_Cli/Debug/tmp/` está montado tu filesystem, entonces le dice a tu proceso que haga `mkdir` sobre `/pepe`.

Entonces tu código ejecuta `mkdir(path, mode)`, con `path` valiendo `/pepe`. Pero ese `mkdir` es el de Linux, y su interfaz dice _"si me pasás algo que arranca con `/` yo lo voy a interpretar como un path absoluto, desde la raíz del sistema de archivos"_. Entonces le estás pidiendo al kernel que te cree `/pepe` (y **no** `/home/utnso/workspace/SAC_Cli/Debug/tmp/pepe`). Y seguramente tu proceso no tenga permisos para tocar `/`, porque en general los procesos de usuario no tienen permisos sobre `/`.

----

La primer solución que se te puede ocurrir, entonces, es sacarle la `/` al path que forwardeás a `mkdir`. Si te piden `mkdir /pepe`, vos le decís al kernel `mkdir("pepe", mode)`, y como tu proceso está parado en `/home/utnso/workspace/SAC_Cli/Debug/tmp`, estás pidiendo crear el directorio correcto.

Pero el problema es que, justamente, ese directorio lo maneja tu proceso. Entonces si tu proceso pide crear un directorio _dentro_ de tu punto de montaje, el kernel, para crear ese directorio, le va a reenviar el pedido de creación a.... ¡tu proceso! 🙃

**Comment by AxelDellavechia** [comment]
Entiendo esa era una de mis dudas sobre el funcionamiento que pregunte el Sabado y había entendido que no necesitaba pasarle la ruta completa. Ahora corrijo el código para contemplar el path completo.
Muchas gracias.

**Comment by mgarciaisaia** [comment]
No, che, ojo, que eso no soluciona el problema. Leete el último párrafo.

Lo que es mucho muy importante que entiendas es que **tu proceso es responsable de un pedazo del sistema de archivos de tu sistema operativo**.

Si tu punto de montaje es, ponele `/mi/fs/`, el kernel **no sabe** cómo crear un archivo dentro de ese directorio - sólo sabe pedirle a tu proceso que cree un archivo en cierta ruta. Y el kernel espera/confía en que, si la creación del archivo fue exitosa, la próxima vez que te pida el contenido de ese directorio, ahora haya una entrada nueva - la que acaba de pedirte que crees.

**El contenido de tu filesystem es el que tu proceso diga.** Todo el tiempo.

¿Se entiende esta idea de que no tiene sentido que tu implementación de `mkdir` haga `mkdir` para la misma ruta?

**Comment by AxelDellavechia** [comment]
Buenos días,

La finalidad de hacer un mkdir dentro de sac_mkdir era para ver como llegaban los datos a la operación. por ejemplo path llegaba así "/pepe" y el mode llega como "509" ¿Cosa que aun no me queda clara?

Pero la idea central de todo esto si no entendí el objetivo es:

1.  Maquina 1 levanta el SAC-Cli sobre el directorio /tmp
2.  Al inicio del programa se conecta con SAC-Server , hacen un handshake 
3. Si piden por ejemplo un mdkir sobre tmp tomo los datos del la función sac_mkdir y se los paso a sac-Server que va estar generando el directorio dentro del disco.bin
4. Dependiendo de la respuesta del SAC-Server retorno si se realizo de forma correcta.

y así con cada una de las operaciones, no es que vamos a crear también sobre el tmp los mismos archivos que estarán en el SAC-Server.

Saludos

**Comment by mesaglio** [comment]
Claro, la idea es que desde el modulo SAC-CLI puedas mandarle al servidor las distintas operaciones.
Por lo que me dijeron en soporte, no manejamos los permisos de los archivos/directorios por lo que te llegue a la funcion mkdir en mode no te interesa.

> no es que vamos a crear también sobre el tmp los mismos archivos que estarán en el SAC-Server.

En relidad en tmp no tenes nada, solo es una carpeta donde montas el sac-cli. Cuando hagas un ls sobre la carpeta tmp va a ir al servidor y va a imprimir en consola(la de sac-cli), la informacion que tenga del servidor.

Espero que te sirva. :grin:

**Comment by AxelDellavechia** [comment]
Efectivamente ambos dijimos lo mismo solo que no sabía que no nos interesarían los permisos , de todas maneras estoy teniendo un problema que capaz @mgarciaisaia me pueda resolver para cerrar el issue.

Yo quiero levantar una consola para SAC-CLI con el con el siguiente código:

void consola(int argc, char *argv[]) {

	printf("Hola!este es el modulo SAC-Cli una interfaz de comunicación con SAC-Server "
			"para finalizar módulo ingrese \"SALIR\"\n");

	struct fuse_args args = FUSE_ARGS_INIT(argc, argv);

	fuse_main(args.argc, args.argv, &sacCli_oper,NULL);

	printf("Fuse se esta ejecutando en background y aquí visualizará la informacion de su FS\n");

	size_t buffer_size = 100;

	char* comando = (char *) calloc(1, buffer_size);

	while (!string_equals_ignore_case(comando, "salir\n")) {
		printf(">");
		int bytes_read = getline(&comando, &buffer_size, stdin);
		if (bytes_read == -1) {
			log_error(logger,"Error en getline");
			exit(0);
		}
		if (bytes_read == 1) {
			continue;
		}

	}

	free(comando);
}

Pero cuando ingresa el fuse main ignora todo el resto del código cerrando el programa si no se lo pone en debug ¿Se pueden tener los 2 a la vez?

Desde ya muchas gracias

**Comment by tferraro** [comment]
@AxelDellavechia cuando necesitas hacer 2 actividades en paralelo: fuse y leer de una consola; la respuesta que tiene todos nos número es hilos :wink:

**Comment by AxelDellavechia** [comment]
Gracias por sus respuestas.

Saludos
