### ISSUE TITLE
Ip y puerto de suse

### ISSUE THREAD

**Issue by ncoen97** [sisoputnfrba/foro#1536]
👋 ¡Hola!
La funcion void hilolay_init(void) no recibe la ip ni puerto de suse (como si lo hace muse_init), deberíamos cambiar la interfaz y agregarlo? levantar un archivo de configuración desde hilolay? o como lo deberíamos manejar?

**Comment by gastoncastineira** [comment]
Buenas

Esos datos no tienen que entrar por la interfaz. Si quieren manejarlo por archivo de configuración pueden hacerlo. También, si no los convence, pueden usar otros medios para obtener IP y puerto como variables de entorno. Seguramente haya otros igual

Saludos

**Comment by ncoen97** [comment]
Perfecto, gracias.
