### ISSUE TITLE
Consulta por el archivo de config en SUSE

### ISSUE THREAD

**Issue by hernan-arga** [sisoputnfrba/foro#1538]
Buenas, queria saber si en las pruebas nos pueden pedir cambiar en medio de la ejecucion de SUSE, el grado de multiprogramacion del archivo de configuracion (creeria que si por que una de las metricas es justamente el "Grado **actual** de multiprogramación"). En caso de que sea asi, ¿Como deberia tratar este cambio? ya que yo el grado de multiprogramacion para los hilos lo controlo a través de un semaforo que se inicializa con este valor del archivo de configuracion, y no podria cambiar el semaforo cada vez que lo uso porque estaria reiniciando su valor y no me serviria de nada.
Y ya que estamos ¿Que otros valores podrian cambiar en ejecucion?.
Gracias, Saludos.

**Comment by gastoncastineira** [comment]
Para este TP no hace falta cambiar en tiempo de ejecución los valores de la configuración, así que no te preocupes. Simplemente mostrá cuanto del grado de multiprogramación estás usando (ej: grado es 15 y tengo solo 12 hilos, muestro 12)

**Comment by hernan-arga** [comment]
Buenisimo, gracias.
