### ISSUE TITLE
grado de multiprogramacion SUSE

### ISSUE THREAD

**Issue by hernan-arga** [sisoputnfrba/foro#1539]
Hola, vengo con otra consulta sobre el grado de multiprogramacion para ver si lo estoy entendiendo bien.
Segun tengo entendido el mismo es compartido para todos los procesos por lo que si yo tengo que mi grado es 1, entre todos los programas solo puede haber un hilo en ready, pero entonces si yo tengo 1 hilo de 1 proceso en ready y despues lo paso a exec (haciendo un post pues tendria espacio para otro en ready) me podria venir otro hilo de otro proceso a ready y entonces yo al querer pasar el primero a exec no podria hasta que el segundo proceso ponga a ejecutar su hilo haciendo que unos hilos dependan de otros hilos de otro proceso.¿Esto esta bien o hay algo en lo que me la este sobrecomplicando?.
Ademas ¿esta bien solo hacer post cuando mi hilo salga de ready?.

Perdon si marea un poco mi pregunta pero queria saber bien como funciona esto.
Gracias, saludos.

**Comment by gastoncastineira** [comment]
No entendí muy bien lo que planteás. El grado de multiprogramación indica cuantos hilos puede haber corriendo en el sistema al mismo tiempo. Eso significa que la cantidad en ready, bloqueados y exec no puede exceder el grado. No veo en qué juega la transición de ready a exec ahí

**Comment by hernan-arga** [comment]
Ah ok, 2 cosas nomas. Cuando decis la cantidad en ready, exec y bloqueado son todos al mismo tiempo? O sea si el grado es 3 entre estos 3 estados al mismo tiempo solo puede haber 3 hilos como máximo entre todos los procesos?. Y segundo, vi que aclararon algo con respecto al hilo main por el grado de multiprogramacion en la pagina de utnso.com pero no lo entendi. Tengo que hacer algún tipo de distinción con los hilos main al momento de ver cuales hilos pueden entrar por el grado?

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by gastoncastineira** [comment]
Sisi, es como decís

Lo de utnso es básicamente que no va a ser un caso de prueba levantar un programa nuevo con el grade de multiprogramación lleno de antemano

**Comment by hernan-arga** [comment]
Ok listo, gracias.
