### ISSUE TITLE
Problemas al cargar la tabla de nodos (array_de_punteros)

### ISSUE THREAD

**Issue by Santiago-Lovelli** [sisoputnfrba/foro#1540]
Hola, estoy intentando de crear un un directorio. Como los directorios pesan un bloque ya que no guardan en el bloque ningun dato. El problema que tengo es que para cargar el bitmap no tengo problema, pero al querer cargar un numero de bloque en el array_de_punteros de la un nodo, cuando hago un ./sac-dump disck.bin me sale que tengo se encuentran ocupados todos lo bloques (carga con numeros randoms hasta el 1023), sin importar si le "harcodeo" un bloque (como el 1 o el 1125, que tengo libre por que el bitmap por como lo estoy haciendo ocupa 100)

```c
//Estructuras relevantes:
	ptrGBloque  array_de_punteros [1000];
} Nodo;

typedef struct {
	Nodo nodos[1024];
} Tabla_de_nodos;

//En el codigo "rompe" (no funciona como se espera, no rompe) en esta linea
tabla_de_nodos.nodos[numero_de_nodo].array_de_punteros[0] = numero_de_bloque;
```

Queria saber si esta bien que dentro del array guarde el numero numero de bloque (uint32_t = ptrGBloque) o si se espera guardar otro dato / referencia. 
PD: el numero_de_bloque lo obtengo al buscar el primer bit  del bitmap que este en cero (por lo que ese bloque no esta ocupado)

**Comment by mgarciaisaia** [comment]
Santi, mucho no entendí tu pregunta, che.

¿Avanzaste algo desde que preguntaste? ¿Tenés algo más de info para compartir?

¿Querés refrasear un poco cuál es el problema que estás teniendo?

**Comment by Santiago-Lovelli** [comment]
Hola, hoy vengo a soporte, mas tarde subo la resolución que obtenga.

**Comment by Santiago-Lovelli** [comment]
Hola, perdón la demora. El problema es que cuando queríamos cargar el array de punteros al crear un directorio nos quedaba basura en el disco entonces al dumpear nos creaba un archivo con basura (nos dimos cuenta por que el nombre eran rombos y símbolos raros) y si comentábamos la linea donde ocupábamos el array de punteros no nos registraba esa basura. 

```c
//así es como cargamos el array de punteros
	tabla_de_nodos->nodos[numero_de_nodo].array_de_punteros[0] = numero_de_bloque;
```
También, lo que cambiamos fue que nosotros para pasar a disco los cambios estábamos haciendo un memcpy de la tabla entera en el puntero que obtuvimos con el mmap. Lo cual cambiamos creando punteros que asignamos a la posición del disco correspondiente:
```c
/*
*si es como hacemos ahora
*inicio_de_disco es el puntero que obtuvimos del mmap
*/
tabla_de_nodos = inicio_de_disco + 1 + bloques_del_bitmap;
```
Igual lo que nos arreglo el problema fue el cargar los bloques de datos con '\0' por que leyendo el binario del disco con xxd vi que el sac-format deja basura en el disco; y cargando el '\0' ya no toma la basura.

Así que básicamente: el problema se arreglo al cambiar como cargábamos en disco y "formateando" el disco cuando inicia el sac-server.
