### ISSUE TITLE
suse_schedule_next

### ISSUE THREAD

**Issue by maticoto20** [sisoputnfrba/foro#1542]
Hola, tengo una duda sobre la funcion suse_schedule_next. Cuando se llama a esta funcion, deberia retornar el tid proximo a ejecutar y mandar a el hilo que se encontraba previamente en ejecucion a ready? o a exit? En caso de que pueda ser ambas, como distingo cada caso? Gracias.

**Comment by afilgueira** [comment]
La función debería darte el próximo a ejecutar. A nivel "hilolay" sólo hace eso. 
La función se va a llamar asociada a otro evento (un fin de proceso, una e/s, un bloqueo por semáforo), con lo cual, por atrás SUSE va a tener que bloquear, mandar a ready, mandar a exit, etc. Pero son dos pasos independientes.

Saludos!

**Comment by maticoto20** [comment]
Ah esta bien, o sea que siempre cuando se llama a esta funcion, no va a haber un hilo en ejecucion porque previamente ya se determino donde iria ese hilo con un suse_join, suse_wait etc?

**Comment by miguel-t** [comment]
En qué momento entonces pasa un hilo en suse a el estado ejecutando?

**Comment by maticoto20** [comment]
Cuando se llame a suse_schedule_next, elige el proximo tid y lo pasa estado ejecutando.

**Comment by tferraro** [comment]
@maticoto20 no segui un poco la conver, el issue está resuelto entonces? Si está resuelto, nos das una mano cerrándolo? 😄
