### ISSUE TITLE
Duda punteros dobles

### ISSUE THREAD

**Issue by AnelloJM** [sisoputnfrba/foro#1543]
Hola! 

tenia una duda a la hora de utilizar punteros dobles (en este caso tengo un char**), tengo entendido que para hacerle free a este tipo de puntero, tengo que primero recorrerlo todo y por ultimo hacerle free al puntero en si:

ejemplo si mi puntero se llama char **notas y tiene 2 posiciones debería hacer:
free(notas[0]);
free(notas[1]);
free(notas);

Para el TP estoy usando la función string_split de las commons, que me devuelve un char** en el cual la ultima posición es NULL

Ahora mi duda es, tengo que hacerle free también a esta ultima posición del null? no estoy seguro si eso seria correcto o no.

Desde ya muchísimas gracias

**Comment by gastoncastineira** [comment]
Buenas

El NULL está para poder poner la condición de corte en un bucle para recorrer ese char**, porque no sabés cuantos elementos vaya a tener. Llegados al caso, no hace falta liberarlo porque en realidad ese puntero no tiene asignada memoria, solo apunta a NULL (y si leemos el man del free, hacer free(NULL) no hace nada)

**Comment by AnelloJM** [comment]
Perfecto! Muchas gracias!
