### ISSUE TITLE
Tipos de prueba de grado de multiprogramacion en suse

### ISSUE THREAD

**Issue by hernan-arga** [sisoputnfrba/foro#1544]
Buenas, estaba tratando de testear casos de prueba para el grado de multiprogramacion y me esta pasando por ej de que si pongo grado maximo 5 y pongo a correr un programa que tiene 3 hilos (el main y 2 mas) y despues otro programa que tambien tiene 3 que es un productor consumidor, el hilo consumidor de este se queda afuera hasta que termine alguno que le permita entrar. El problema esta en que se ponen a ejecutar el main y el productor y cuando el productor se bloquea pasa a ejecutar el main pidiendo un join para el hilo consumidor, se bloquea tambien, y se rompe porque luego pide un schedule next cuando no hay ninguno mas para ejecutar (pues todavia no se lo permite el grado de multiprogramacion). La secuencia queda asi:

> Mandar create con tid:0
Mandar create con tid:1
Mandar create con tid:2
Llamaste a join para esperar al tid 2
Productor produciendo. cantidad acumulada 1 
Llamaste a join para esperar al tid 
Pide schedule next  -----------------> Aca se rompe (2 bloqueados, 1 en new, 0 en ready)

Mi pregunta es ¿Van a probar este tipo de pruebas o es muy rebuscado? En caso de que vayan a probar esto ¿Como deberia afrontar el caso donde no me quedo ningun hilo para ejecutar en ready?

Gracias, saludos

**Comment by tferraro** [comment]
Buenas!

Hablamos de un escenario parecido en el post de la revisión 3 del enunciado: https://www.utnso.com/linuse-v1-3/, se ajusta al escenario que comentas?

TL;DR: Me suena poco rebuscado igual el escenario jajaj

**Comment by hernan-arga** [comment]
No se hasta qhe punto se parece al escenario de la revisión. O sea para hacerla más corta:
¿Me puede pasar que en un test un proceso no pueda ejecutar ningún hilo al pedirme schedule next a causa de que el grado de programacion actual no permite meter otro en ready y los demas hilos están bloqueados?
Me parece que no tiene sentido pero lo quería confirmar.

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by afilgueira** [comment]
No tenemos en mente ese tipo de tests, pero si eso pasara y es el comportamiento esperado, está bien que funcione así. Saludos!
