### ISSUE TITLE
Duda sobre Borrar Directorios en sac-server

### ISSUE THREAD

**Issue by mari967** [sisoputnfrba/foro#1545]
Hola,
Tengo dudas sobre qué implica borrar un directorio en sac-server. Yo supuse que si un directorio contiene archivos, al borrarlo también tengo que borrar sus archivos. Ahora si un directorio tiene directorios, tendría que borrar sus correspondientes archivos?

¿Sería necesario revisar todos los subdirectorios y borrar sus correspondientes archivos?

Gracias.

**Comment by tferraro** [comment]
Buenas!
Que pasa cuando hacer `rm` a un directorio? Podés describir comportamiento tiene?
Como lo mappearías a la implementación del sac con fuse?

**Comment by mesaglio** [comment]
rm y rmdir te puede llegar a decir que el directorio no esta vacio.

Por si queres probar que pasa en el fs de las vm o en sac-server, podes usar el comando rm -r (recursivo) o rm -rf (recursivo y forzado).

**Comment by iago64** [comment]
@mari967 Podemos cerrar el tema? quedo claro lo que explicaron Tom y Juan?

**Comment by mari967** [comment]
Hola,
Gracias por contestar. Quedo claro y ya pude hacer la función borrar directorio.

Perdón por la demora en contestar. Me re colgué.

**Comment by iago64** [comment]
No problem! Lo importante era que solucionaras el problema.
Damos por cerrado entonces la duda.
