### ISSUE TITLE
SUSE semaforos

### ISSUE THREAD

**Issue by maticoto20** [sisoputnfrba/foro#1547]
Hola, tengo una duda con respecto a los semaforos de suse. Sabiendo que la cantidad de semaforos es fija, y que se instancian a traves del archivo de configuracion al correr el programa y que estos semaforos son compartidos por los distintos procesos que maneje SUSE, deberia conocer de antemano el nombre de todos los semaforos que se van a usar en cada uno de los procesos que usen SUSE para ponerlos en el archivo de configuracion?
Gracias

**Comment by ncoen97** [comment]
Si, sino cuando les vayas a hacer wait o signal desde el programa que los usa no los va a encontrar en suse.

**Comment by maticoto20** [comment]
ah perfecto, entonces antes de hacer las pruebas nos van a proveer con los nombres de cada semaforo para que llenemos el config?

**Comment by mesaglio** [comment]
Se supone, hay que esperar los tests.
