### ISSUE TITLE
Valgrind no detecta memory leaks de muse

### ISSUE THREAD

**Issue by hernan-arga** [sisoputnfrba/foro#1548]
Hola vengo a dejar otro problemilla que tengo con valgrind.
Tengo el proyecto de memoria que tiene un muse.c (donde se encuentra el main y toda la administracion de muse) y un utils.c (que tiene definiciones de funciones comunes como loguear info y demas), el tema esta en que cuando corro con valgrind el ejecutable por la terminal solo me detecta los memory leaks de utils.c y no los de muse.c

Aca esta el proyecto (noten que cree una variable k a la que le asigne un malloc de 500 y nunca libere)
![image](https://user-images.githubusercontent.com/37780035/69822259-a5cb4800-11e4-11ea-8d7a-4160ccf1336c.png)

Esta es la salida de valgrind (noten que no me marca lo de la variable k ni de ninguna otra solo algo de una llamada a utils.c)
![image](https://user-images.githubusercontent.com/37780035/69822325-da3f0400-11e4-11ea-80a5-a221c92a0cc1.png)

Uso el ejecutable que me crea automaticamente eclipse al compilar, no se donde podria llegar a estar el problema.

Gracias, saludos.

**Comment by mesaglio** [comment]
Al final de la foto de la terminal dice: “rerun with - -leak-check=full to see details of leaked memory”

Que comando estas usando para correr con valgrind?

Yo uso este https://github.com/sisoputnfrba/foro/issues/1546#issuecomment-558893757

**Comment by hernan-arga** [comment]
> Al final de la foto de la terminal dice: “rerun with - -leak-check=full to see details of leaked memory”
> 
> Que comando estas usando para correr con valgrind?
> 
> Yo uso este [#1546 (comment)](https://github.com/sisoputnfrba/foro/issues/1546#issuecomment-558893757)

Gracias, justo por ahi venia la mano me faltaba el flag de  --show-leak-kinds=all
