### ISSUE TITLE
Prueba planificador

### ISSUE THREAD

**Issue by hernan-arga** [sisoputnfrba/foro#1550]
Buenas, estaba probando la prueba del planificador y me estan pasando 2 cosas:
En primer lugar la prueba dice "Se debe verificar que los procesos <Audiencia> tengan prioridad a la hora de ser elegidos para ejecutarse por sobre el proceso productor inicial".
Sin embargo el productor inicial termina enseguida y no me da tiempo a correrlo con la audiencia
y viendo el codigo que hicieron veo que solo hay un for(i = 0;i<10000000;i++); antes del productor pero esto no me lo retarda lo suficiente y termina muy rapido. Yo supongo que la idea es que se ejecuten el productor y la audiencia a la vez porque despues dice "Se debe verificar que los procesos <Audiencia> tengan prioridad a la hora de ser elegidos para ejecutarse por sobre el proceso productor inicial".

En segunda dice "Se debe verificar que la cantidad de ejecuciones para los consumidores iniciales sea equitativa, es decir, si el proceso productor inicial finaliza dejando el semáforo en 420 instancias y levantamos 4 consumidores, cada uno debe realizar 105 wait."
Y a mi me pasa que no importa la cantidad de procesos siempre imprime 105, y pense que lo habia hecho mal yo
pero viendo lo que subieron:

![image](https://user-images.githubusercontent.com/37780035/69869718-6fe19e80-128c-11ea-9c33-a4287badbac9.png)

siempre va a dar 105 por proceso, entonces nose bien cual es la idea.

Gracias, saludos.

**Comment by afilgueira** [comment]
Hola, respecto al retardo, es bueno el comentario. Con la latencia de red del laboratorio, el enviar varios mensajes a SUSE debería agrandar el tiempo, pero ante la duda vamos a actualizar la prueba y ya. 

Respecto al 105, abajo se abren 4 hilos que consumen, esa es la idea.

Saludos!

**Comment by achani2497** [comment]
mientras deberiamos meter algun usleep por algun lugar para poder probar hasta que se haga el update de la prueba?

**Comment by afilgueira** [comment]
Buenas, sí. Es una opción válida.

**Comment by afilgueira** [comment]
Ahí quedó corregida. Saludos!
