### ISSUE TITLE
Prueba memoria

### ISSUE THREAD

**Issue by ncoen97** [sisoputnfrba/foro#1551]
👋 ¡Hola!
Haciendo el test de memoria, se pide ejecutar el programa "Recursiva" y como resultado esperado dice "Se debe verificar que inicialmente el programa recursivo imprima los valores del 1..10 y luego imprima los valores del 10..1".
Cuando nosotros lo ejecutamos nos imprime los valores del 1..10 pero luego hace el close.
Viendo el codigo del test recursiva(10):
void recursiva(int num){
	if(num == 0)
		return;
	uint32_t ptr = muse_alloc(4);
	muse_cpy(ptr, &num, 4);
	recursiva(num - 1);
	muse_get(&num, ptr, 4);
	printf("%d\n", num);
	muse_free(ptr);
}
Puede ser que esté bien que no haga del 10..1?

**Comment by nahuelm** [comment]
Hola Nico!! Efectivamente falta agregar un print al codigo. Es correcto lo que notaste. Lo vamos a arreglar para las pruebas de mañana. 

Buena observacion, sigan asi!!
