### ISSUE TITLE
Pids en prueba memoria

### ISSUE THREAD

**Issue by ncoen97** [sisoputnfrba/foro#1552]
👋 ¡Hola!
Quería avisar que cuando intentamos ejecutar varios programas en simultaneo nos rompía y nos dimos cuenta que era porque en todos los programas de prueba hace ``` muse_init( 1 ,ip,puerto)``` , por lo que todos los programas tienen el mismo pid y no se podían diferenciar.
Para solucionarlo hay que usar la funcion ```getpid() ``` en muse_init.

**Comment by afilgueira** [comment]
Arreglado, gracias!
