### ISSUE TITLE
Dudas con serializacion en SUSE

### ISSUE THREAD

**Issue by FedeMacias** [sisoputnfrba/foro#1553]
Buenas, segun estoy entendiendo tengo que codificar un .c de hilolay, lo que tengo que hacer es un .c de hilolay.h o de hilolay_alumnos.h ? estoy medio confudido.
En caso de que sea hilolay_alumnos.h, puedo modificar algo de struct hilolay_operations? o directamente hago un "suse_create" en hilolay_alumnos.c  y listo?

Gracias

**Comment by hernan-arga** [comment]
Hola, lo que tenes que hacer es un hilolay_alumnos.c que va a tener las funciones implementadas que te pide el tp, y en cuanto a la segunda pregunta no modifiques nada de struct hilolay_operations solo implementa el suse create en hilolay_alumnos.c

**Comment by FedeMacias** [comment]
Okay, muy claro, muchas gracias!
