### ISSUE TITLE
Suse en prueba de memoria

### ISSUE THREAD

**Issue by hernan-arga** [sisoputnfrba/foro#1554]
Buenas, estaba viendo que en la prueba de memoria piden que este levantado suse tambien pero en los archivos recursiva.c y archivo_de_swap_supermasivo.c no incluyen la libreria de hilolay, y ademas no levantan ningun hilo en estos archivos ¿Fue un error del enunciado o les falto agregar algo?

Gracias, saludos.

**Comment by iago64** [comment]
Buenas buenas!
Tranqui, no fue un error y no nos falto agregar algo, simplemente les pedimos que esté levantado ya que es muy común que en las entregas terminamos una prueba y pasemos directo a la siguiente sin tener que estar bajando todo el tp y volviendolo a levantar.
En otras situaciones también nos pasa que si saltan cosas raras (o comportamientos no deseados), solemos pedirles correr otro programa de prueba y bueno, si justo necesitamos suse, se nos complicaría.
Abrazo.-

**Comment by tferraro** [comment]
Buenas! Cierro esto dado que parece que la duda quedó resuelta 😆
