### ISSUE TITLE
Como implementar el hilolay_alumnos.c

### ISSUE THREAD

**Issue by FedeMacias** [sisoputnfrba/foro#1555]
Buenas, estoy teniendo algunos problemas.

creé el archivo de hilolay_alumnos.c y lo puse en mi carpeta del SUSE, yo tengo que incluir todo lo de la carpeta hilolay dentro de este archivo .c??

y como hago para modificar el hilolay_alumnos.h sin modificar el del repositorio que nos dieron? creo una copia y la incluyo en mi projecto? lo intenté asi pero no me funciona correctamente

En el foro lei que tengo que crear un projecto nuevo de hilolay_alumnos.c dentro de mi TP y hacerlo como shared library, está bien eso?

**Comment by eGoicoechea** [comment]
Hola! Me sumo a la pregunta de @FedeMacias considerando que pasa lo mismo con libmuse.h que en los tests lo incluyen localmente y al hacerlo nosotros en el proyecto del tp como una shared library lo tendriamos que instalar en las maquinas. Es asi? libmuse deberia ser una shared library instalada?

**Comment by iago64** [comment]
Buenas buenas!
Justo este tipo de preguntas las vimos bastantes veces por lo que les dejamos en el [repo de las pruebas](https://github.com/sisoputnfrba/linuse-tests-programs) 3 alternativas de solución:

![image](https://user-images.githubusercontent.com/1622109/69922783-02955f80-147e-11ea-9817-506a77e1746c.png)

La idea es que si tienen sus shared library, que las pueden crear siguiendo el [video de shared library del canal de youtube](https://www.youtube.com/watch?v=Aw9kXFqWu_I&ab_channel=UTNSO) despues las incluyan como parte de la compilación de las pruebas para que arranquen sin problemas :)

Cualquier cosa que no se entienda nos chiflan y lo vemos.
Abrazo

**Comment by ncoen97** [comment]
> Buenas, estoy teniendo algunos problemas.
> 
> creé el archivo de hilolay_alumnos.c y lo puse en mi carpeta del SUSE, yo tengo que incluir todo lo de la carpeta hilolay dentro de este archivo .c??
> 
> y como hago para modificar el hilolay_alumnos.h sin modificar el del repositorio que nos dieron? creo una copia y la incluyo en mi projecto? lo intenté asi pero no me funciona correctamente
> 
> En el foro lei que tengo que crear un projecto nuevo de hilolay_alumnos.c dentro de mi TP y hacerlo como shared library, está bien eso?

Hola! me sumo a la respuesta de @iago64 
Las cosas que están en el repo de hilolay no deberías tocarlas, lo que tenes que hacer es crear la shared library y que sea una extención de hilolay. En esta shared library vas a tener la implementación de hilolay_init, suse_create, suse_schedule_next, etc. y vas a necesitar un include de hilolay.h (que tiene que estar instalada en el sistema).

**Comment by FedeMacias** [comment]
Entonces en mi caso, yo ya tengo una libreria aparte que está incluida en SUSE,  si yo agrego dentro de mi libreria el "hilolay_alumno.c" con eso ya me alcanza para que funcione no? obviamente con hilolay instalado e incluido en ese archivo
