### ISSUE TITLE
Duda de conexion entre suse e hilolay

### ISSUE THREAD

**Issue by FedeMacias** [sisoputnfrba/foro#1556]
Buenas

Tengo una consulta, si no puedo modificar nada de hilolay, hay alguna funcion de hilolay que yo tenga que definir en el .c para la conexion??

Veo un "init_internal" en hilolay_alumnos.h, tengo que definir esa funcion en el .c y que esa funcion haga toda la conexion necesaria con suse??

Basicamente mi pregunta es como conectar hilolay con suse sin modificar lo del repositorio de hilolay

saludos

**Comment by mesaglio** [comment]
> Veo un "init_internal" en hilolay_alumnos.h, tengo que definir esa funcion en el .c y que esa funcion haga toda la conexion necesaria con suse??

Sip, nosotros hicimos eso.

**Comment by FedeMacias** [comment]
Claro, agregaron un hilolay_init en el .h y en el .c y que eso haga todo lo necesario.
Porque despues en las pruebas se llama a hilolay_init.
Perfecto, muchas gracias
