### ISSUE TITLE
Funciones de hilolay_alumnos.h

### ISSUE THREAD

**Issue by FedeMacias** [sisoputnfrba/foro#1558]
Buenas

Las funciones del hilolay_alumnos.h, las que estan dentro de la estructura hilolay_operations, son modificables? puedo cambiarles el tipo? o tienen que quedar si o si como estan ahi??

Otra consulta, estas funciones de la estructura operations, tienen que coincidir en lo que reciben y lo que devuelven con las que tengo en SUSE??

Saludos

**Comment by gastoncastineira** [comment]
Hola

Lo que está el .h de alumnos es la interfaz que tienen que implementar ustedes para que nosotros e hilolay_internal utilicen. El más mínimo cambio va a causar que las pruebas, y potencialmente el resto de hilolay, deje de andar
Después, la comunicación que manejen hilolay y SUSE queda del lado del alumno cómo hacerlo, siempre respetando el enunciado, las buenas prácticas y los conceptos que ven en la parte teórica de la materia -- más por su felicidad al programar que la nuestra :)

Suerte! Cualquier otra duda chiflá

**Comment by FedeMacias** [comment]
Okay, dejo todo como está entonces, muchas gracias!!
