### ISSUE TITLE
SUSE semaforos

### ISSUE THREAD

**Issue by maticoto20** [sisoputnfrba/foro#1559]
Hola, esta bien que suceda esto?: cuando un hilo de un proceso llama a hilolay_wait, se llama a suse_wait lo que lockea el semaforo, y luego se llama a hilolay_yield, lo que lo devuelve el proximo a ejecutar, y yo en SUSE mando al hilo actual de running a ready.
Ahora, si viene otro hilo del mismo proceso y vuelve a llamar a hilolay_wait, se va a quedar esperando a que este se libere, pero nunca se va a liberar porque el hilo que lo lockeo esta en ready y el hilo ejecutandose esta esperando una respuesta de suse_wait y nunca hace el hilolay_yield.

**Comment by ncoen97** [comment]
Buenas. Supongamos que ya se hizo el primer wait y el primer hilo quedó en ready. Cuando se haga el segundo wait, el segundo hilo va a pasar a bloqueado y ahí se debería hacer el hilolay_yield que va a devolver el próximo a ejecutar. Tené en cuenta que cuando el segundo hilo haga wait no se va a "quedar esperando", solo se pasa al estado Bloqueado y sigue la ejecución.

**Comment by maticoto20** [comment]
ah perfecto! gracias!
