### ISSUE TITLE
Duda sobre función escribir archivo 

### ISSUE THREAD

**Issue by mari967** [sisoputnfrba/foro#1560]
Hola,

Vi que write en fuse utiliza un parámetro offset y tenía dudas sobre cómo usarlo.
Si yo tuviera un archivo con, por ejemplo 50 bytes, y hago un write con un offset de 30 y un contenido de tamaño 10, significa que del bytes 30 al 40 tengo en nuevo contenido y del 40 en adelante perdí el que estaba antes?

Saludos.

**Comment by mesaglio** [comment]
Se supone que no, es un write.
Solo tenes que utilizar lo que tenes en los parametros de la opercion.
Si te dicen de 30 a 40, no tendrias que modificar lo que tengas del 40 al 50.

**Comment by mari967** [comment]
Entonces write debe poder hacer lo mismo que la función pwrite de c?

**Comment by mesaglio** [comment]
En cierta forma si, pero fijate que los errores de pwrite pueden venir de lseek o write.
El sac-write, o el nombre que le hayas dado, se comporta como la llamada al sistema `write`
Podes encontrar la documentacion en la terminal poniendo el comando: `man 2 write` o entrando [aca](https://linux.die.net/man/2/write)

**Comment by mari967** [comment]
Quedó claro. Muchas gracias por la ayuda :grinning:
