### ISSUE TITLE
Symbol lookup error al ejecutar programa de prueba de hilolay

### ISSUE THREAD

**Issue by micayeza** [sisoputnfrba/foro#1562]
Hola!! 
Quiero probar SUSE y para eso cree un programa, incluso copie el codigo de las pruebas. El programa corre, por consola y por debug, pero al llegar a la linea de hilolay_init tira lo siguiente:
`./programa_planif: symbol lookup error: ./programa_planif: undefined symbol: hilolay_init`

por otro lado cuado hago el install de hilolay  rompe ya que no reconoce mi biblioteca compartida. Debo agregarla al makefile para instalar hilolay? 

Gracias!!!!

**Comment by ncoen97** [comment]
Para poder buildear el programa de prueba primero tenes que hacer un install de hilolay como viene del repo de git. Luego tenes que buildear la shared library (tu proyecto que extiende las funcionalidades de hilolay) y recien ahi vas a poder buildear el programa de prueba con hilolay y la shared library

**Comment by mgarciaisaia** [comment]
¿Chusmeaste si #319 te ayuda?

**Comment by micayeza** [comment]
Hola a ambos! ncoen97 cuando decis buildear la shared library , es solo el alumnos.c y h? o todo hilolay ya editado por nosotros?
mgarciaisaia lei y vi el video para ver si podia pasarles el error de eclipse, el tema es que mi programa si compila y corre. Pero  sigue tirando ese error en la primer funcion de hilolay.

`
Finished building: ../programa_planif.c
 
Building target: programa_planif
Invoking: GCC C Linker
gcc -L"/home/utnso/workspace/tp-2019-2c-capitulo-2/libs/Debug" -L"/home/utnso/workspace/tp-2019-2c-capitulo-2/hilolay/Debug" -o "programa_planif"  ./programa_planif.o   -llibs -lcommons -lhilolay
Finished building target: programa_planif
`

**Comment by micayeza** [comment]
Descargue nuevamente hilolay, lo instale. Modifique los alumnos. c y h. Fui a eclipse y compile todo y ahora si rompe mi prigrama:

```
make all 
Building target: programa_planif
Invoking: GCC C Linker
gcc -L"/home/utnso/workspace/tp-2019-2c-capitulo-2/libs/Debug" -o "programa_planif"  ./programa_planif.o   -llibs -lcommons -lhilolay
./programa_planif.o: In function `main':
/home/utnso/workspace/tp-2019-2c-capitulo-2/programa_planif/Debug/../programa_planif.c:14: undefined reference to `hilolay_init'
makefile:32: recipe for target 'programa_planif' failed
collect2: error: ld returned 1 exit status
make: *** [programa_planif] Error 1
```

**Comment by afilgueira** [comment]
Hola, Hilolay **no** tiene que ser editado por ustedes. 

En [este ejemplo](https://github.com/sisoputnfrba/hilolay-example) y en los tests hay un archivo que hace de interfaz y que define las funciones que uds tienen que crear (init + las de suse). 

El readme de las pruebas tiene bastante detalle de cómo hacer correr todo. Avisen si algo no queda claro, pero les recomiendo seguir esos pasos.

Saludos!

**Comment by tferraro** [comment]
👋 Buenas! Me sumo al comment de adro. A hilolay hay que extenderla, no cambiarla o editarla, ojímetro ahí.
Como mucho, puede pasar que al momento de buildear su propia "extensión" tengan nombres diferentes al de hilolayext o usen dependencias de otras libs, por lo que van a tener que adaptar la compilación del makefile a su flavor de tp 🙂 (ej, agregando -lcommons, -lpthread, etc)

**Comment by micayeza** [comment]
Hola!
Estuve intentando pero no hay caso, no me llevo con la compilación. Consultas, efectivamente no edite hilolay, solo cree mi hilolay_alumnos.c , y lo puse en la carpeta de hilolay. Lo saco?
Por lo que entendi hilolay_alumnos.c debe quedar en la carpeta de los test.

Pero estoy peleando con el makefile de los test, en ese makefile que crearon, donde esta libMuse? o no esta y debo agregarla? El sabado habrá algun ayudante que pueda darme una mano con esto? 
Gracias!

**Comment by afilgueira** [comment]
Hola, no es necesario ponerlo en la misma carpeta. Si deberías poder compilarlo y vincularlo como biblioteca compartida. Algo similar hacen los tests y ejemplos que subimos.

En los tests hay un libmuse.h únicamente para que compile, pero lo podés reemplazar o borrar con la misma idea de hilolay.

Si no sale y necesitas una mano, venite mañana y lo revisas con quiénes estemos disponibles (más temprano -> más chances de que estemos disponibles)

Saludos!

**Comment by micayeza** [comment]
Gracias por la mano el sabado!
finalmente elimine las librerias compartidas ya que me traian problemas. Y agregue en el makefile que compartieron en los test el .h y .c de libmuse.

Saludos!
