### ISSUE TITLE
Openbts

### ISSUE THREAD

**Issue by Josejose12** [sisoputnfrba/foro#1563]
Hello, I am trying to install openbts but when I have to build the code in the guide this command appears to me.
. /build.sh B210 and when I enter it it appears that there is no file or direct. What I can do?

**Comment by Josejose12** [comment]
Porque cerraste esto?

**Comment by mgarciaisaia** [comment]
Sorry, we can't provide support to openbts here.

**Comment by ezecoen** [comment]
Gracias. Vuelva prontos :)

**Comment by Josejose12** [comment]
Entonces donde puedo encontrar ayuda?

**Comment by Josejose12** [comment]
Then where can i find help?

**Comment by ezecoen** [comment]
Gracias. Vuelva prontos :)

**Comment by mesaglio** [comment]
[Option 1](https://github.com/RangeNetworks/OpenBTS-UMTS)
[Option 2](https://github.com/RangeNetworks/openbts)

Bye
