### ISSUE TITLE
Metricas

### ISSUE THREAD

**Issue by maticoto20** [sisoputnfrba/foro#1564]
Hola, en el enunciado dice que hay que mostrar las metricas cada cierto tiempo y cuando un hilo finaliza. En este ultimo caso solo mostramos las metricas del hilo que finalizo, no? O habria que mostrar tambien las metricas de cada hilo, cada programa, y el sistema?

**Comment by afilgueira** [comment]
Las del hilo están bien. Saludos!

**Comment by tferraro** [comment]
@maticoto20 te quedó alguna duda que re abriste el issue?

**Comment by maticoto20** [comment]
si perdon, lo abri y me olvide de mandar la consulta. Queria saber si para las metricas que se loggean cada cierto tiempo hay que incluir los hilos que estan en exit. O solamente los que estan ejecutandose, en ready y en blocked. Gracias!

**Comment by afilgueira** [comment]
Hola, las que tengas y puedas explicar durante la entrega. Saludos!

**Comment by maticoto20** [comment]
gracias
