### ISSUE TITLE
Ayuda makefile pruebas

### ISSUE THREAD

**Issue by brianStremel** [sisoputnfrba/foro#1565]
Buenas gente, tengo muchas dudas para modificar el makefile de las pruebas, suponiendo que quiero agregar mi implementacion de hilolay, tengo que agregarlo acá:
LD_LIBRARY_PATH=$(LD_LIBRARY_PATH):./$(BUILD) ./$(BUILD)/audiencia

o acá:
$(CC) -L./$(BUILD)/ -Wall $(CFLAGS) -o $(BUILD)/audiencia audiencia.c -l$(NAME) -lhilolay

y si así fuese como se haría? Siendo que esta es la ubicación:
/home/utnso/workspace/tp-2019-2c-Vendo-FIAT-600/hilolay/Debug/libhilolay_pruebas.so

Ya anduve modificando uno que encontré en el foro, https://github.com/sisoputnfrba/foro/issues/1557,  y no hay caso, no lo puedo hacer funcionar.

Saludos!

**Comment by brianStremel** [comment]
Cómo "Update" me dijeron que lo agregue al LD_LIBRARY_PATH y no sé si lo estoy haciendo mal, pero tampoco me está andando
![image](https://user-images.githubusercontent.com/37552405/70265362-fc9ec780-1778-11ea-9537-744686bc1a2a.png)
![image (1)](https://user-images.githubusercontent.com/37552405/70265380-0294a880-1779-11ea-8e08-020e9dc2292b.png)

**Comment by papa-caco** [comment]
Hola Brian,
estás haciendo mal el export en la consola, lo que tenés que agregar como variable de entorno es un PATH y no debe incluir al archivo .so.  Sacale el nombre del archivo completo (libhilolayex.so) al comando y debería tomarte solo la ruta en la variable .
Para probar si te quedó bien probá el comando env:
**env | grep LD** y deberías ver la variable de entorno **LD_LIBRARY_PATH** con lo que le definiste.
Suerte, saludos,

Carlos.

**Comment by brianStremel** [comment]
Buenísimo, era eso, gracias!
