### ISSUE TITLE
Transicion New a Ready en SUSE

### ISSUE THREAD

**Issue by FedeMacias** [sisoputnfrba/foro#1566]
Buenas,

Para tomar metricas del tiempo de espera de un hilo, yo tomo el instante de tiempo en el que ingresa a READY, la preguntá es, quien maneja esa transicion (de NEW a READY) ? 

en el caso que sea SUSE, en que caso se produce?? agrego hilos a ready mientras el grado de multiprogramacion lo permita??

Saludos!

**Comment by gastoncastineira** [comment]
Habrás visto en la teoría que el que realiza las transiciones de new a ready es el planificador de largo plazo. Para este TP el algoritmo que maneja es FIFO
En lo de multiprogramación es así cómo lo decís

**Comment by FedeMacias** [comment]
Perfecto, mientras el grado de multiprogramacion lo permita sigo agregando, muchas gracias!
