### ISSUE TITLE
Prueba Planificacion

### ISSUE THREAD

**Issue by FaridUtn** [sisoputnfrba/foro#1567]
Buenas, tengo un inconveniente. Cuando levanto las pruebas (Estoy levantando por ejemplo dos audiencias, un Afinador y 3 Solos, aunque el problema pasa con 3 solos, 2,1 o mil). La cuestion es que el Solo hace muchos wait y entonces llega a tener sus 4 hilos bloqueados. Cuando me pide el next Id yo devuelvo -1 porque no hay threads para ejecutar y esto hace que ocurra un SegFautl. Esto lo probe tambien corriendo bastante tiempo antes el Afinador cosa de que haga varios signal, pero igual pasa. Mi pregunta es si esta mal que devuelva -1 y deberia hacer otra cosa, si es porque las pruebas corren muy rapido y no llegan los signal, o si hay otro problema propio de nuestro codigo. 

Gracias

**Comment by Fedryus** [comment]
Nosotros estamos en la misma situación. También intentamos devolver -1 pero no nos termina de cerrar porque sigue tirando SegFault.

**Comment by tferraro** [comment]
Buenas!

Veamos que pasa con esta "syscall" en particular. Imaginen que esta es la funcionalidad real de que si ustedes estuvieran implementando un sistema operativo completo en assembler.

Siendo el sistema operativo un proceso mas, que no forma parte de la "planificación normal" por así decirlo, te puede terminar pasando que no tengas programas a ejecutar. En cuanto te sucede eso, imaginemos si la syscall devolviera -1, **que haría ese sistema operativo**? A el solo le importa ejecutar el siguiente, no tiene otras cosas que hacer, está en un loop infinito ejecutando programas.
Eso quiere decir, que va a volver a consultar y así indefinidamente hasta que consiga un PID válido.

Estar todo el tiempo usando CPU para nada preguntando por información sin siquiera un delay, suele **ser el caso clásico de espera activa**.

Sin embargo, no vas a ver algo así en ningún SO (incluso Windows usa como pivot ese proceso conocido como "Proceso Inactivo del Sistema"). Entonces, **qué estrategia podría usar, tanto aplicable a este TP, para evitar generar una espera activa**? (acá falla con SIGSERV por la implementación de hilolay, pero sino seria lo mismo).

**Comment by tferraro** [comment]
Buenas! @FaridUtn @Fedryus les sirvió mi respuesta?

**Comment by Fedryus** [comment]
@tferraro En mi caso si, ya esta solucionado
