### ISSUE TITLE
Planificación -Suse -next

### ISSUE THREAD

**Issue by miguel-t** [sisoputnfrba/foro#1568]
Tenemos dudas con el comportamiento en suse cuando recibí suse-next.
Si llega el mensaje suse-next y en suse tenemos en exec a tid1 y en ready :tid2
suse retorna tid2 ? Que pasa con tid1?
Lo sacas de exec y lo envías a ready?

Y si en ready no hay nada lo volves a pasar a ese hilo que acabas de sacar de exec?

Gracias.

**Comment by emarcosgv** [comment]
Cual es el evento que te avisa el fin de ráfaga de cpu del hilo en ejec?suse close entiendo que es cuando finaliza el hilo, pero podría dejar de ejecutar por alguna razón que no sea la finalizacion del hilo? Sino no entenderia el tema de la estimación sjf.

**Comment by afilgueira** [comment]
Hola, el next debería poner el de exec en ready, correr el algoritmo y elegir el siguiente. Spoiler alert: podría ser el mismo (si está solo o si hay varios pero su estimación es la más baja). Saludos!

**Comment by miguel-t** [comment]
Ahora cierra .
Perfecto.

Gracias!
