### ISSUE TITLE
Mallocear estructuras de tamaño variable

### ISSUE THREAD

**Issue by FedeMacias** [sisoputnfrba/foro#1569]
Buenas

Si yo tengo una estructura con un campo que no puedo saber el tamaño porque es variable, supongamos una estructura de semaforo que adentro tiene una lista de procesos bloqueados por el.
 
De que manera puedo mallocearla cuando la creo? es posible?

Saludos!

**Comment by FedeMacias** [comment]
Otro ejemplo seria un proceso, que tiene su cola de ready (una lista o un array) dentro su estructura. Como malloceo eso?

**Comment by ncoen97** [comment]
Buenas, la forma mas sencilla de ocuparse de esto es usar las listas de las [commons](https://github.com/sisoputnfrba/so-commons-library/tree/master/src/commons) que tenes las funciones como list_create(), list_add(), etc. e ir reservando el espacio para cada elemento cuando los vayas agregando.
Saludos.

**Comment by FedeMacias** [comment]
Buenisimo, muchas gracias!
