### ISSUE TITLE
Duda con maps privados y compartidos

### ISSUE THREAD

**Issue by IvanDL95** [sisoputnfrba/foro#1570]
Buenas, tengo una duda con como funciona el swap dependiendo del tipo de mapeo.

Estuve investigando un poco y parece que, según el manual, el MAP_PRIVATE lo que hace es traerse los datos solicitados por el map desde archivo, que el mismo (el mapeo) no es visible a otros procesos y que además *los cambios no son llevados hacia el archivo*. Además, en [este issue](https://stackoverflow.com/questions/33034831/difference-between-map-private-and-map-shared-in-mmap-for-threads) la primera respuesta dice al final que se podría pensar "como  una alternativa a malloc()".

Esto me confunde ya que, si los cambios no deberían ser llevados al archivo, se supone que debería traer las páginas desde el archivo a memoria cuando estas son solicitadas y, cuando las swapeo, las debería mandar al archivo de swap en lugar de la página mappeada? O de todos modos copio la página hacia el mappeo del archivo ya que este flag (el MAP_PRIVATE, el que usa Linux cuando escribo mmap en el código) me asegura este comportamiento?  

También tengo otra duda más, es general sin importar el tipo de mappeo. En el enunciado, en el apartado de memoria compartida, explica que al hacer un map se crea una tabla de páginas y que cuando otro proceso mappea el mismo archivo reutiliza la tabla de páginas creada previamente.
Esto significa que:

1. Más allá de si es mappeo compartido o privado debo hacer esto? O si es privado se debe crear otra tabla de páginas? No iría en contra de lo que dice el manual respecto a que no es visible a otros procesos?

2. En caso de ser mappeo compartido y suponiendo que se quiere hacer un map por segunda (o tercera, cuarta...) vez sobre el archivo, que pasa si los mappeos son de tamaños distintos? Debo agrandar el mappeo que hice antes agregandole más páginas a la tabla?

Saludos!

**Comment by gastoncastineira** [comment]
Buenas.

1-En nuestro TP va a swap, no vuelve al archivo. Se sincroniza recién con el sync()

2-Se crean dos tablas de páginas distintas

3-No es ni va a ser un caso de prueba hacer eso

Saludos

**Comment by IvanDL95** [comment]
> 2-Se crean dos tablas de páginas distintas

Independientemente del tipo de mappeo?

**Comment by gastoncastineira** [comment]
No. Solo cuando es privado. Cuando el mapeo es compartido es la misma tabla

**Comment by IvanDL95** [comment]
Muchas gracias!
