### ISSUE TITLE
Ayuda Helgrind

### ISSUE THREAD

**Issue by micayeza** [sisoputnfrba/foro#1571]
Hola! Necesito una nueva ayudita. Estoy con un deadlock e intento correr helgrind para encontrarlo pero me salta: 
```
valgrind --tool=helgrind ./MUSE
valgrind: failed to start tool 'helgrind' for platform 'x86-linux': No such file or directory
```
en internet dice que deberia instalar valgrind de 32 bit, alguna idea?

**Comment by tferraro** [comment]
Que raro, estás en la VM? Porque ahí es todo de 32bits 🤔 

@iago64 vos viste este error en algun momento?

**Comment by iago64** [comment]
Gracias por el tag tom 😄 
Pregunta rapida, es la VM o es una instalación nativa? porque eso nos cambia el panorama.

**Comment by micayeza** [comment]
Es la vm de la catedra, y nunca la actualize. 
Me dijeron que la descargue de nuevo jaja algún otro intento rápido antes?

**Comment by mgarciaisaia** [comment]
@micayeza ¿nos copiás el resultado de ejecutar estos dos comandos? `lsb_release -a` y `uname -a`

**Comment by micayeza** [comment]
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```

```
uname -a
Linux ubuntu-server 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:22:43 UTC 2018 i686 i686 i686 GNU/Linux
```

**Comment by mgarciaisaia** [comment]
Otros dos tengo para pedir:

`ls -l /usr/lib/valgrind/hel*` y `file /usr/lib/valgrind/helgrind-x86-linux`.

Si ese último falla, corré `sudo apt install --reinstall valgrind` y fijate si "se soluciona".

**Comment by micayeza** [comment]
Ninguno de los tres funciono :( e incluso murio el memcheck que antes andaba ajaj

**Comment by mgarciaisaia** [comment]
¿Qué otra data tenés, che? Así, a ciegas, no te puedo colaborar mucho con nada :/

**Comment by mgarciaisaia** [comment]
Otra cosa que podés probar es editar el script que ejecuta `valgrind` (con, por ejemplo, `sudo vim $(which valgrind)`), y editar la última línea (la que hace `exec $0.bin "$@"`) para que ejecute `strace` en el medio: `exec strace "$0.bin" "$@"`).

Con eso, la próxima vez que ejecutes deberías poder ver _algo_ que te indique en qué ruta está buscando el binario de helgrind, a ver dónde busca - y después vemos por qué no lo encuentra.

También vale agregar una línea que ejecute `env` antes de pasar a correr el script, a ver qué onda.

**Comment by micayeza** [comment]
La apague y funciono ajaja supongo que sudo apt install --reinstall valgrind funciono y solo faltaba reiniciarla!!
Mil gracias
