### ISSUE TITLE
Consulta Valgrind - Commons

### ISSUE THREAD

**Issue by jdevergilio** [sisoputnfrba/foro#1572]
Buenas tardes,
Les hago una pequeña consultita, estaba testeando con Valgrind y me encontré con varios casos como los de la imagen, donde las funciones provenientes de las Commons retienen memoria sin liberarla. Como deberíamos proceder con estos casos? Los ignoramos o hay alguna manera de corregirlos?

![image](https://user-images.githubusercontent.com/48719022/70853946-cdccd380-1e93-11ea-8853-3433ce525095.png)

muchas gracias.
Saludos.

**Comment by gastoncastineira** [comment]
Ojo. Las commons están testeadas y no tienen ningún leak interno. Es responsabilidad del programador el liberar la memoria que usa

Valgrind no te dice en dónde está el leak, sino en dónde reservaste memoria que no estás liberando. En el caso de la imagen veo que estás usando string_split y string_duplicate, que sí, las commons y usan malloc por dentro para generarte todo eso devolviendote la referencia, pero vos nunca la liberaste y por eso te genera leaks. free() es tu amigo en este caso

**Comment by tferraro** [comment]
@jdevergilio pudiste encontrar el leak? 🙂
