### ISSUE TITLE
Hilos de exit se eliminan?

### ISSUE THREAD

**Issue by FedeMacias** [sisoputnfrba/foro#1573]
Buenas, una consulta rapida

En algun momento los hilos de exit se van a eliminar o siempre permanecen en la cola hasta que termine el programa?

Saludos!

**Comment by iago64** [comment]
Esta muy cara la ram para tenerlos ahi? 😄 
No te preocupes, dejalos ahi, no molestan a nadie, lo importante es que el tp funcione, después cuando aprueben y si algún dia tienen ganas revisan esos detalles 😉

**Comment by FedeMacias** [comment]
Dudas paranoicas que surgen, muchas gracias!!
