### ISSUE TITLE
Caso de error en schedule next

### ISSUE THREAD

**Issue by FedeMacias** [sisoputnfrba/foro#1575]
Buenas

Estamos probando suse (en un archivo de prueba propio) y nos encontramos en un caso donde se ejecuta un schedule pero ya existe un hilo que está corriendo en ese mismo proceso, por lo tanto el schedule no se puede hacer.

Entonces:

-Que deberiamos hacer para poder atajar ese caso de error correctamente? actualmente estamos devolviendo un -1 pero hilolay rompe si el schedule no devuelve un TID que ya exista.

-Tenemos que hacer algo? es un caso que se puede llegar a presentar en una de las pruebas? o siempre el schedule va a ejecutarse con la cola de exec vacia?

Saludos

**Comment by tferraro** [comment]
Buenas!

No termino de entender el problema, podes instanciarle un ejemplo? Gracias!!

**Comment by FedeMacias** [comment]
Si, te explico

-se hace un init
-despues se crea un hilo, este hilo pasa a ready por el planificador
-se hace un wait a un semaforo
-ese wait internamente hace un schedule next, pone a ejecutar el siguiente hilo
-actualmente tengo un hilo en ejecucion
-hago un signal del mismo semaforo
-ese signal internamente llama a otro schedule next pero como hay un hilo en ejecucion todavia, no puede completar la operacion (schedule next solo devuelve un TID cuando la cola de exec de ese proceso esta vacia), devuelve un -1 (mensaje de error)
-Al devolver -1 hilolay no sabe que hacer y tira seg fault

Basicamente esa es la prueba que hicimos

**Comment by tferraro** [comment]
Buenas!

La tarea del `schedule_next` es conseguir el próximo a ejecutar y "flaggearlo" como que está ejecutando (hacer el cambio de estado).
Eso implica que si hay un hilo ejecutando y al ejecutar el `schedule_next`, el algoritmo determina que hay otro hilo candidato, hay que hacer el cambio de estados para el hilo en ejecución y el hilo candidato.

**Comment by FedeMacias** [comment]
Clarisimo, muchas gracias!!
