### ISSUE TITLE
Consulta visibilidad de archivo mappeado

### ISSUE THREAD

**Issue by micayeza** [sisoputnfrba/foro#1576]
Hola! como estan?
En el contexto de la memoria y el musemap, el test lo primero que escribe en el archivo es un int. Mi programa escribe y lee bien el archivo luego del sync pero al abrir el archivo no hay nada que leer ya que ese primer int es 208="Đ   " al tener el numero \0 ya el resto el editor de texto no lo muestra. 
Es necesario que me las ingenie para que el editor muestre todo? o con que funcione el test alcanza?
gracias

**Comment by tferraro** [comment]
Buenas!

Cuando escribir archivos binarios, los editores de texto suelen hacer un poco agua justamente por lo que comentás 😥 .
Probá usando el comando `xxd <tu archivo>`, que te va a permitir ver los datos en hexa de lo que estás escribiendo (y como se ven en ASCII tambien). Ahí podes revisar de no estarla pifiando con el test para estar más segura 😉

Nota: Los procesadores intel usan Little Endian para representar los bits, por lo que, en la VM, el entero 8, va a estar representado como `00 08 00 00` en vez de `00 00 00 08`, por lo que puede ser que veas algunos números desordenados con xxd 😛

**Comment by micayeza** [comment]
Muchas Gracias!
Cierro el issue
