### ISSUE TITLE
Asignacion de semaforos

### ISSUE THREAD

**Issue by IvanDL95** [sisoputnfrba/foro#1577]
Buenas, tengo una duda con respecto a como se asignan los semáforos. 

Yo pensaba que, al igual que la teoría que vimos en la cursada, los semáforos (o recursos, como lo llamaban) se asignan al proceso y luego, en caso de querer liberarlos o de finalizacion, estos se desasignan y se liberan al sistema. Por lo que estuve viendo parece que la interfaz de hilolay permite hacer wait/signal independientemente de cuantos wait/signal previos se haya hecho.

Poniendolo en ejemplos separados. 

1. Se puede hacer "infinitos" signal sobre un semáforo por más que se hayan hecho menos/ningun wait y siempre se le va a sumar 1 (obviamente se va a capear en el valor del mismo en el valor máximo)?

2. Si un programa hace muchos wait (pongamosle que es una cantidad menor a la necesaria para que se bloquee el proceso), no hace falta que se "liberen" con la misma cantidad de signals, o que se liberen todos a la vez cuando finaliza el proceso, cierto? Es decir, el valor del semáforo queda igual en caso que se cierre el hilo más allá de que haya hecho varios wait y ningún signal, sin importarme si otro hilo lo solicita. Perdón por la redundancia pero quería dejar clara mi duda.

3. Extendiendo la pregunta 2, en caso de que un hilo 1 que haga wait sobre el semáforo "A", habiendo un hilo 2 que haya hecho muchos waits, al punto de no haber más de "A" disponible, bloqueando al hilo 1, Si ese hilo 2 finaliza sin hacer ningún signal, ¿el hilo 1 seguiría estando bloqueado hasta que otro hilo distinto haga signal sobre "A"?

Hasta ahora modelé el thread para que tenga semáforos asignados, por lo tanto sabe cuantos wait hizo liberando todos los wait en caso de entrar a EXIT, y estaba en la duda de esto, ya que sino no me haría falta hacerlo de esta manera.

**Comment by afilgueira** [comment]
1 - sí. Si son contadores, es posible.
2 - tal cual. Con contadores podrías tener diferentes cantidades y no es algo que esté mal, porque indican instancias. 
3 - sí, quedaŕía bloqueado.

El caso donde el sistema podría "acomodar" los semáforos si tu proceso no hizo suficientes waits o signals es el mutex. En los contadores, cada proceso incrementa y decrementa lo que considera.

Saludos!

**Comment by IvanDL95** [comment]
Sí me había hecho ruido porque vi los test y no había mucha correlación entre la cantidad de waits y signals. Duda resuelta. Muchas gracias!
