### ISSUE TITLE
Consulta revolucion privada y compartido

### ISSUE THREAD

**Issue by micayeza** [sisoputnfrba/foro#1578]
Hola! Tengo 2 consultas sobre el test general.
1) Sobre el test privado. En estres privado , copian al inicio del archivo, la proxima posición en la que se debería escribir(Por lo que entiendo y funciona bien) ejemplo: En la primer vuelta, se graba 4 (ya que inicia vacio el archivo) y se copia "JAJAJA" y el numero inicial del archivo para a ser 10 olvidandonos del \n y \0. Al finalizar el test el archivo queda formado por 208 mas todas las cadenas que se copiaron.
 Cuando corro el siguiente programa: revolucion privada. se lee ese numero:
`muse_get(&offset, arch, sizeof(uint32_t));`  y asignan a len "la cantidad que se va a leer"
`uint32_t len = offset - leido;` que seria 208 -4 que da 204. y realmente no hay para leer 204 en adelante. Cual de los dos test estoy entendiendo / corriendo mal?

2) Tanto en estres compartido como en revolucion compartido el codigo es:
```
       hilolay_wait(presion_recibida);
 .............................................
	hilolay_signal(presion_emitida);
```
Lo que me genera un deadlock ya que nadie hace signal de presion_recibida e inicia en 1. Esta bien si coloco en estres.c el wait y signal de presion_recibida y en revolucion.c el wait y signal de presion_emitida?

Muchas gracias!!!

**Comment by afilgueira** [comment]
Hola, no terminé de seguir tu primera pregunta. Sobre la otra pregunta, corregimos los tests. Saludos!

**Comment by micayeza** [comment]
Hola! gracias por la segunda. En la primer pregunta...
Quisiera saber como hace "revolucion" para saber que longitud leer del archivo mapeado

**Comment by iago64** [comment]
![image](https://user-images.githubusercontent.com/1622109/71019752-b0894680-20d9-11ea-9fe8-1dbebfc18a6d.png)

Perdon por la calidad del meme, pero al hacerlo a las apuradas no salio bien, pero creo que se entiende que simplemente triene un tamaño fijo no?

![image](https://user-images.githubusercontent.com/1622109/71019858-e0384e80-20d9-11ea-84ca-a2b533727793.png)

**Comment by micayeza** [comment]
jjajajaj hola Damian! luego de esas dos lineas hay un leer_archivo

//Guardan en offset los primeros bytes que hay en el archivo, en mi caso 208. Ultima posición escrita
	muse_get(&offset, arch, sizeof(uint32_t));
//hacen 208 -4 = 204 
	uint32_t len = offset - leido;
// Leen desde 208 , 204 bytes--> ya no hay nada
	muse_get(palabra, arch + offset, len);

Esta es mi duda, que estoy entendiendo mal? u haciendo mal? 
El primer offset que están levantando deberia ser donde empieza la ultima o primer cadena? pero sigo sin entender como len les va a dar exacto lo que mide la cadena.

No se si fui mas clara jeje
Gracias

**Comment by iago64** [comment]
Aaaaah ahora siii jajja

Por suerte eso es un toque mas facil de explicar, fijate que en el archivo lo que hace es primero grabarte el tamaño de los datos y despues los datos

![image](https://user-images.githubusercontent.com/1622109/71021136-766d7400-20dc-11ea-9107-01233f4b1a6b.png)

De ahí que sabe cuánto leer en la siguiente vuelta... capaaaz que suena parecido a los ejemplos de serialización que tenemos en la ppt jeje

Abrazo.-

**Comment by micayeza** [comment]
mmm No, ahi como me mostras estas grabando la cadena, en el cpy de abajo se graba el offset , pero no es la longitud de la cadena sino la suma de todas las longitudes hasta el momento y se graba delante de todo.  Me esta faltando esa parte de grabar la longitud de la cadena...

**Comment by iago64** [comment]
Mala mia, marque mal la parte jeje, 
Es justo abajo, porque claramente podemos hacer el código feo que hace llorar a los ayudantes de paradigmas...

![image](https://user-images.githubusercontent.com/1622109/71021671-a0736600-20dd-11ea-9066-1bea45125d00.png)

**Comment by micayeza** [comment]
jajaja perdón te estoy volviendo loco!
Ahora si. PERO. 
Primer vuelta copio HOLA --> offset = 5
Segunda vuelta        MICA --> offset = 10


Si viene otro a leer (revolución), lee offset = 10
len = 10 -4 
Lee desde 10 , 6 bytes. Pero luego de 10 no había nada.

 Yo no estoy manejando headers dentro del archivo mappeado, sera ese mi error?

**Comment by iago64** [comment]
Tranqui, no estas manejando nada mal a priori, lo que no estas capaz viendo es que cada registro del archivo esta compuesto por 2 partes:
1.- El tamaño del texto (los primeros 4 bytes)
2.- El texto per se (todo lo que sigue que mide lo que te dice lo anterior)

Después en las lecturas lo que haces es:
leer 4 bytes para obtener el tamaño y después lees la palabra:

![image](https://user-images.githubusercontent.com/1622109/71024763-60fc4800-20e4-11ea-9206-146ca9af3358.png)

Después te devuelve el offset de la siguiente "palabra" para que puedas leer a partir de ese offset y no vuelvas a leer la misma "palabra"

Slds.-

**Comment by micayeza** [comment]
Ultima y no te jodo más. 
 Lo que no se me esta grabando es el tamaño del texto, ya que siempre se guarda en la posicion 0 sel archivo, en esta linea no debería ser, arch + offset o algo por el estilo? 
![image](https://user-images.githubusercontent.com/11916894/71025063-129b7900-20e5-11ea-883c-950f32aac3ce.png)

**Comment by gastoncastineira** [comment]
Bueno, creo que va siendo hora de que ponga la cara por el código cochino que hice ahí. La prueba no pasó estándares de belleza y después de revisar lo que comentaste me doy cuenta que no hace lo que debería. Intentaré sentarme a arreglarla esta noche porque creo que estuve a un cpy de hacerlo bien jajaja
Puede fallar decía este señor
![image](https://user-images.githubusercontent.com/28161802/71024798-76717200-20e4-11ea-99bd-fa919d69fe22.png)

Para que quedemos claros, doy una (no muy) breve explicación de lo que debería hacer esa prueba.

Sucede que nosotros una de las tantas cosas que queremos que se lleven del TP es entender cómo funciona IPC (inter process communication) ya que es algo que un SO está haciendo todo el tiempo para poder hacer las muchas cosas que hace un SO. La memoria compartida es un método de IPC al igual que los sockets. ¿Y qué les decíamos que tenían que hacer para comunicar TADs complejos y/o de longitud variable entre dos procesos? ¡Serializar!
El modelo que plantea la prueba del muse_map privado es el mismo que les planteamos a ustedes durante las charlas (tamaño | contenido | tamaño | contenido | etc...). Pero hay una cosita más. En el TP0 hay una serialización resuelta utilizando realloc(), porque yo no sé cuánto va a medir (en bytes) lo que voy a enviar, así que me voy guardando en una variable "longitud" el total de lo que llevo guardando y lo voy redimensionando en base a la necesidad. En ese caso, el sistema operativo y C me están salvando de tener que, de alguna manera, saber cuál es el siguiente byte libre sobre el cuál tengo que escribir lo que estoy serializando porque no sabría cuanto llevo escrito ni tengo un centinela como \0 como pasa con los string. Sencillamente no tengo forma de descubrir donde tengo el final de lo que llevo serializando para saber donde tengo que agregar el siguiente contenido. Y ESO es lo que nos está pasando con el muse_map en este caso. El proceso que levanta el archivo ya grabado no tiene idea de cuantos bytes tiene que leer ni cuantos van a ser basura. Así que lo que hacemos para simplificar este lío gracias a que la RAM está barata, me grabo al principio del archivo el tamaño TOTAL de todo lo que es "contenido", y luego de esos 4 bytes empieza el paquete serializado con (tamaño | contenido). Véase la siguiente imagen de cómo quedaría.

![image](https://user-images.githubusercontent.com/28161802/71022757-fea14880-20df-11ea-8ac7-cedee45a55bc.png)

Cualquier otra duda gritá

**Comment by iago64** [comment]
@gastoncastineira me parece a mi o @micayeza acaba de marcar lo que mencionas que te faltó?

**Comment by gastoncastineira** [comment]
@iago64 Claro, no está grabando el tamaño de la cadena, y cuando el otro proceso quiere levantarlo está calculando mal el desplazamiento por eso

**Comment by micayeza** [comment]
Me gane un puntito extra! 💯

**Comment by afilgueira** [comment]
De hecho, sí 😀
