### ISSUE TITLE
Solos y Afinadores

### ISSUE THREAD

**Issue by FaridUtn** [sisoputnfrba/foro#1579]
Hola una consulta. Estamos probando las pruebas de Suse. Cuando levantamos Un Solo cada hilo toca 105 notas (420 afinadas / 4 hilos). Y si levantamos dos Solos, cada hilo toca 52 o 53, que es la mitad. Se tocan todas, y es bastante equitativo. El problema es que como cada hilo de Solo tiene un for de 105 iteraciones... Tanto cuando hay dos solos (que ninguno puede tocar 105 veces) y a veces cuando hay uno, Algun hilo nunca sale de ese for porque le quedan mas iteraciones pero ya no hay mas SIGNALS de semaforos, porque ya fueron consumidos los 420 y quizas a este hilo que no sale del for le falto una iteracion mas.

**Comment by gastoncastineira** [comment]
Ajá. Y la pregunta es... si eso está mal? Mientras tengan los resultados esperados para la prueba en las condiciones planteadas claramente la respuesta es no

**Comment by FaridUtn** [comment]
Perfecto, muchas gracias
