### ISSUE TITLE
Sincronizacion en SUSE

### ISSUE THREAD

**Issue by FaridUtn** [sisoputnfrba/foro#1580]
Consulta. Si tenemos un Mutex para los semáforos, el cual se lockea antes de Incrementar(y desbloquear proceso) o decrementar(y bloquear proceso) el semáforo que venga, y se deslockea después, Hay alguna posibilidad de que haya condición de carrera sobre los semáforos? No veo como podría, pero los resultados de las pruebas aparentan tenerla.

**Comment by gastoncastineira** [comment]
>condición de carrera sobre los semáforos
Voy a necesitar más contexto para entender qué pasó acá jajaja

**Comment by FaridUtn** [comment]
Porque cuando corremos la prueba de Afinador y Solo, a veces los hilos tocan notas dispares  (uno 105, otro 105, otro 104 y otro muere en 100 capaz) y queda ahi y como que no ejecuta más porque se bloquea en algún wait, cosa que no deberia, lo que me da a suponer una condicion de xarrera. Lo que no entiendo es como puede ser que haya una posible condición de carrera si antes de tocar algún semaforo se usa un mutex, el mismo para todos los semaforos que haya.

**Comment by FaridUtn** [comment]
Creo que nuestro problema proviene porque afinador quiere hacer más waits de lo que permite el semáforo por valor de archivo de configuración. Nosotros cuando pasa eso estamos devolviendo -1 pero al parecer, inutilmente. entonces para afinador el hizo 420 signals pero en realidad el contador del semáforo no llegó a ese valor. quisiéramos saber que hay que hacer con el proceso afinador cuando quiera hacer un Signal y el semáforo está al máximo

**Comment by IvanDL95** [comment]
Creo que cuando haces muchos signals hay que dejarlo en el valor máximo, al menos es lo que entendi.

También me está pasando algo similar, pero es cuando se me bloquea el solo. Corro el afinador, cuando hace signal termina desbloqueando los hilos de solo y, al parecer, al mensaje siguuente se "atasca", pero del lado del cliente. Hay veces que incluso se atasca el afinador en el medio. A veces finalizo el solo y el paquete se libera pero llega de forma anómala, haciendo que se caiga suse por querer procesarlo en lugar de descartarlo y cerrar esa conexión.

**Comment by afilgueira** [comment]
Hola, el límite de los semáforos es en su valor. Esto significa que si es 10 y ya vale 10, un signal no lo debería aumentar más. Esto no afecta en nada a los waits, porque si toman valores negativos bloquean al ULT y ya.

Los 20 segundos de delay que tiene el afinador están ahí para que puedan levantar los solos. Si la planificación está más o menos bien, los waits deberían dejar el semáforo en -4 y después el afinador ir subiéndolo y desbloqueando ULTs. Al ir ejecutando parejos, esperamos que nunca haya tantos signals como para llegar a 10, pero si sirve subir este valor a 50 no hay problema con eso.

El test es un productor consumidor clásico: un hilo genera 420 elementos, 4 hilos consumen esos 420 (de a 105 cada uno). Saludos!
