### ISSUE TITLE
Fuse recibe size mayor al que le envio

### ISSUE THREAD

**Issue by agustinlk** [sisoputnfrba/foro#1581]
Buenos días,

Luego de crear y probar el read y write en el SAC-Server, estoy probando enviar la petición desde Fuse. Desde un programa de ejemplo hago:
`fwrite(datos, sizeof(char), 5000, arch);`
`fread(buf,sizeof(char),` 5000, arch);`
Cuando SAC-Cli recibe la información de Fuse, en el primer caso le llega size=4096 (si envío un size menor a 4096 llega el valor correcto). En el segundo caso le llega size=16348 envíe lo que le envíe.
Se imaginan por qué puede estar pasando esto?
Gracias!

**Comment by mgarciaisaia** [comment]
¡Aloha!

Entre tu programa y FUSE se encuentra el kernel, cuya función es administrar todos los recursos del sistema de la manera más óptima posible.

Una de las formas de optimizar la velocidad general del sistema es cachear las lecturas a disco. Leer un dispositivo de I/O es lento, entonces el kernel, a la hora de mandar una lectura, suele pedir leer más bytes que los estrictamente necesarios, porque el principio de localidad indica que es _muy, muy probable_ que vayas a leer los bytes siguientes.

Entonces, por más que tu programa pida 4096 bytes, el kernel está decidiendo que le es más o menos el mismo laburo pedir 16348 (casi 16k) y guardárselos para la próxima vez que se los pidas.

Si tu archivo es más corto que eso, primero asegurate de estar devolviendo la longitud correcta en la llamada `getattrs`. No recuerdo si el kernel confía en ese valor o no.

Si aún así el kernel te está pidiendo más bytes de los que tenés, [FUSE dice que devuelvas cuántos bytes pudiste leer correctamente](https://libfuse.github.io/doxygen/structfuse__operations.html#a2a1c6b4ce1845de56863f8b7939501b5).

La alternativa es usar el flag `direct_io` al montar el FS, que le indica al kernel que haga las lecturas directo, sin cachear. Eso va a hacer que los requests a FUSE sean más equivalentes a los que tu programa hace.

Pero creo (chequeá el enunciado, por las dudas) que la mano va por el otro lado.

**Comment by agustinlk** [comment]
Gracias. Era como vos decías, por más que le pase x bytes el kernel va lee otra cantidad la cantidad que le convenga.
Y en el caso del write que el size era menor, era porque escribe por partes:
Si hago fwrite 5000bytes -> El kernel envia un write de 4096 bytes y luego otro de 904 bytes. Al programa le llegan todos juntos.

Muchas gracias
