### ISSUE TITLE
Consulta distinto md5 cuando son pcs diferentes

### ISSUE THREAD

**Issue by ignacioreyesfs** [sisoputnfrba/foro#1583]
Hola, tenemos el siguiente problema:
Corriendo el test de filesystem en una unica pc (levantando tanto sac_cliente como sac_server) cuando movemos el archivo de 10mb da el mismo md5 tanto afuera de fuse como adentro. El problema surge cuando se levanta sac_cliente en una pc y en la otra el sac_servidor ya que tira distinto md5 AVECES, es decir, escribe bien el archivo (ya que 3/5 tira mismo md5) pero lo lee mal a veces cuando se usan dos pc y no entendemos el porque.
No se ejecutan dos escribir de forma simultanea, se realiza lo mismo que levantando todo en una pc solo que en 2, y el md5 a veces da bien y a veces no (corremos varias veces el md5, no es que volvemos a mover el archivo, de 5 veces contiguas que lo tiramos, por ej 2 dan mal).
La cantidad de bytes leidos es el mismo ya sea que de bien o mal.

**Comment by gonzaloven** [comment]
Se solucionó, basicamente estabamos corriendo el sac_cliente de esta forma:

`./sac_cliente ./home -f `

Agregando `-s` para que FUSE corra single thread se arregla el problema.

**Comment by iago64** [comment]
Si las cosas les funcionan bien single thread y no multithread, claramente tienen alguna condición de carrera no resuelta, por las dudas corran el tp con helgrind, capaz les faltaron un par de mutex en el cliente :)

**Comment by gonzaloven** [comment]
Era efectivamente eso, teníamos mal los mutex del cliente.

**Comment by ignacioreyesfs** [comment]
Era eso, tomamos como dos secciones criticas separadas el send y el receive cuando teniamos que conformar una entre las dos
