### ISSUE TITLE
Filesystem - Tests

### ISSUE THREAD

**Issue by ntaboada** [sisoputnfrba/foro#1584]
Buenas.

Tengo el FS terminado. Todas las operaciones en general andan bien. Las mas importantes (read/write) cuando se tratan de no muchos bytes (menores a 1MB) tambien andan correctamente. Los problemas empiezan arrancan al correr los script de prueba...

Estoy viendo que al crear un file con 10mb de datos random, siempre me tira SEG.FAULT la funcion write despues de copiar entre 1.5mb y 2mb. Nunca pasa de los 2. La verdad estoy muy desorientado de donde esta el problema y pasan las horas y no le encuentro solucion. Y lo peor es que se hace muy dificil debuggear porque tengo que estar tocando infinidad de veces el F8 de eclipse hasta el momento exacto en que rompe (ya que las lecturas se van haciendo de a partes). Ahora mismo me rompe dentro de uno de los memcpy que hago en la funcion.

Lo unico que me esta haciendo ruido, es el valor que me esta llegando del offset al server !== del que me llega de la funcion de fuse (en el cliente). No se si el problema puede venir de ahi al serializar el valor. De todas formas no entiendo porque cuando hago pruebas de escribir pocos bytes anda todo bien (por mas que el offset este medio maquendo). 
Tambien es cierto que no se si lo estoy logeando bien el valor (no se que %X deberia ir ahi, ahora mismo tengo un lld) y quiza por eso veo distintos valores.

Alguien que me pueda tirar algo de luz? 

![image](https://user-images.githubusercontent.com/11520892/71222789-a1a8bc80-22b0-11ea-844f-cc01bd03a777.png)

PD: dejo adjunta una imagen del valor que me esta llegando que es muuy grande y es lo unico raro que veo.

Gracias!

**Comment by iago64** [comment]
Un segfault y no sabes de donde viene? la salida rapida es correr el proceso con valgrind a ver si no es que estas pisando la memoria y por eso te explota por los aires.

**Comment by ntaboada** [comment]
@iago64 valgrind me salvo las papas :p. Efectivamente, no estaba liberando memoria (los punteros dentro de las estructuras). Y la otra cosa era que eclipse es una m... que me hizo creer que venia por el lado del offset. Corriendo las cosas en terminal los valores del offset tienen sentido y me di cuenta que el problema no venia por ahi

**Comment by ntaboada** [comment]
este issue ya se puede cerrar, cree otro con otro problema. Gracias!

**Comment by iago64** [comment]
@ntaboada Al final, se cumple lo que digo en la ppt de valgrind, salva tps jeje.

Cierro el issue y ahi vemos el otro problema en el otro 😄
