### ISSUE TITLE
MUSE: reusar, paginas

### ISSUE THREAD

**Issue by Santiago-Lovelli** [sisoputnfrba/foro#1585]
Buenas, tengo un par de duda. 
1) Si un segmento libera justo la totalidad de su ultima pagina asignada dicha pagina esta disponible nuevamente? Tanto para el segmento como para Muse? 
Ejemplo: El segmento 1 (HEAP) tiene las paginas 0,1,2 y el segmento 2 (MAP) las 3 y 4. Si el uno libera totalmente la pagina 2, el tamanio del segmento se disminuye en una pagina automaticante, asiendo que si este quiere crecer en un futuro no pueda? o sigue con su asignacion pero con un heap que señale que esta vacia totalmente? En caso de liberarla se le puede asignar la pagina 2 a otro segmento? (este es mas alla de si es justo esa porcion de memoria que creeria que no, si de se el segmento 2 quiere crecer ahora tendria la pagino 3, 4 y 2).

Gracias

**Comment by gastoncastineira** [comment]
No hay política de borrado de páginas en este TP. Pueden encararlo como quieran siempre validando con sus ayudantes

**Comment by iago64** [comment]
Siendo que faltan 24hs para la entrega y sumando a lo que dice Gaston.
Hagan lo mas simple, no hay pruebas taaan especificas que validen al 100% ese comportamiento.
