### ISSUE TITLE
Deadlock en Tests

### ISSUE THREAD

**Issue by FedeMacias** [sisoputnfrba/foro#1587]
Buenas

Pensamos que podria existir un deadlock, en los tests de caballeros de sisOP, hay un caso en el que se blockean todos los hilos de "solo" entonces "afinador" comienza a ejecutar varias veces, llega un punto en el que "afinador" hace un wait(solo_hiper_mega_piola) que lo deja en 0 y un signal(afinador) que lo hace pasar de 0 a 1, cuando pasa eso, nosotros liberamos el primer hilo que este blockeado por ese semaforo y lo mandamos de vuelta a ready. Cuando termina el signal, inmediatamente se ejecuta un SJF, ese SJF nos devuelve el TID del hilo que recien se liberó,  entonces comienza a correr ese hilo de "solo" que se libero sin que "afinador" pueda hacer su signal(solo_hiper_mega_piola), ese hilo hace un wait(afinador) que lo deja en 0  y luego hace un wait(solo_hiper_mega_piola) que lo deja en -1, y eso hace que se bloquee ese hilo, entonces "afinador" queda bloqueado y el unico hilo de "solo" corriendo tambien se blockea, generando un deadlock.
Esto está pensado asi?? la prueba es asi??
Estan evaluando como nosotros manejamos ese deadlock o existe algun error en nuestra implementacion y esto no es un deadlock?

nota: la prueba la corrimos con una instancia de "afinador" y una instancia de "solo"   (esto podria afectar???)

Saludos!

**Comment by tferraro** [comment]
Buenas! No entiendo mucho esto que comentás:
>  llega un punto en el que "afinador" hace un wait(solo_hiper_mega_piola) que lo deja en 0 y un signal(afinador) que lo hace pasar de 0 a 1, cuando pasa eso, nosotros liberamos el primer hilo que este blockeado por ese semaforo y lo mandamos de vuelta a ready. Cuando termina el signal, inmediatamente se ejecuta un SJF, ese SJF nos devuelve el TID del hilo que recien se liberó, entonces comienza a correr ese hilo de "solo" que se libero sin que "afinador" pueda hacer su signal(solo_hiper_mega_piola)

Me resulta un poco incoherente, se hace un signal y dspués no se hizo? 🤔 

De todas revisé los programas de `caballeros_de_SisOp` y no me suena que venga por ahí. `solo_hiper_mega_piola` es simplemente un mutex entre ambos scripts y `afinado` actúa como un semáforo contador típico de productor-consumidor.

**Comment by FedeMacias** [comment]
voy a intentar hacerlo mas resumido.

_afinador (tid 1 de pid 0)_
**sem(solo)**   solo->0
SJF -> el siguiente a ejecutar es tid 1 de pid 0
**sem(afinador)** afinador-> 1
se desbloquea el tid 1 del pid 1
SJF -> el siguiente a ejecutar es tid 1 de pid 1
**sem(solo)** -> nunca entra aca

_solo (tid 1 de pid 1)_
**wait(afinador)**  afinador ->0
**wait(solo)**  solo-> -1  (se bloquea)
SJF -> el siguiente a ejecutar es tid 1 de pid 0
**signal(solo)** ->nunca ejecuta esto

_afinador (tid 1 de pid 0)_
**sem(solo)**   solo->-1 (se bloquea)
SJF-> no encuentra hilos para planificar, estan todos bloqueados

**Comment by tferraro** [comment]
Buenas! Sigo sin seguirte che :/

El código del afinador es el siguiente:
```
hilolay_wait(solo_hiper_mega_piola);
hilolay_signal(afinado);
hilolay_signal(solo_hiper_mega_piola);
```
No entiendo como cuando debería ejecutar tu "sem(solo)", osea `hilolay_signal(solo_hiper_mega_piola)`, podría ocurrir un bloqueo, debería activar el semáforo y triggerear una replanificación.

**Comment by FedeMacias** [comment]
si, disculpá, me confundi, el primero es un wait(solo)

claro, pasa que cuando hace el signal de afinador, en el caso que pase de 0 a 1, eso va a liberar un hilo.
Y cuando replanifica despues del signal de afinado, me devuelve que sigue ese hilo que fue liberado. entonces no llega a ejecutar ese ultimo sem(solo) del final. Me explico?

**Comment by FedeMacias** [comment]
todos los problemas surgen en base a que nunca se llega a ejecutar ese signal(solo) del final porque cuando replanifico despues del signal(afinador) no me devuelve al hilo del afinador, me devuelve un hilo de solo
