### ISSUE TITLE
IONIC 4, FACEBOOK PLUGIN -> THREAD WARNING: ['FacebookConnectPlugin'] took '19.589844' ms. Plugin should use a background thread

### ISSUE THREAD

**Issue by Siavichay7** [sisoputnfrba/foro#1588]
El plugin de facebook funciona perfecto en android pero tengo ese inconveniente en IOS, llevo dias buscando la solucion y no encuentro nada. Uso ionic 4, he instalado muchas veces el plugin y no funciona en ios ni en dispositivo tampoco en emulador

**Comment by iago64** [comment]
Me parece que te equivocaste de foro de consultas @Siavichay7
