### ISSUE TITLE
Busco grupo

### ISSUE THREAD

**Issue by fgiannotti** [sisoputnfrba/foro#1589]
Buenas, voy a cursar operativos martes/mierc a la noche + sab a la tarde, estoy buscando armar un grupo o incluirme con gente comprometida.
Si alguno ya esta manija buscando grupo: francogiannotti115@gmail.com

**Comment by iago64** [comment]
Buenas, si no te jode, podes publicar el msj en el issue #1590 ? Asi unificamos todos y no se pierde tu mensaje :smile: 

Abrazo!
