### ISSUE TITLE
El puntero no cambia su valor al salir de una función

### ISSUE THREAD

**Issue by leobz** [sisoputnfrba/foro#1591]
### Problema: El puntero no cambia su valor al salir de una función
 1) El puntero "patentes" inicia apuntando a NULL
![patentes_apunta_a_nada](https://user-images.githubusercontent.com/43507646/77204644-f3d8c400-6ad1-11ea-9be1-9535a799962b.png)

 2) Cuando se llama a la funcion agregarPatenteAVector(), "patentes"
     entra dentro de la funcion y termina apuntando "nuevaPatente".
![Debugg_agregarPatentesAVector](https://user-images.githubusercontent.com/43507646/77204877-6ea1df00-6ad2-11ea-9ed7-6fa605a099e6.png)

 3) Sin embargo al salir de la funcion agregarPatenteAVector(), "patentes"
     sigue apuntando NULL como al principio.
     (se desea que al salir de la funcion, siga apuntando a "nuevaPatente"
![patentes_sigue_sin_apuntar_a_nada](https://user-images.githubusercontent.com/43507646/77204693-0c48de80-6ad2-11ea-888b-f39f777ca49d.png)

**Código:**
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct{
	char* letras;
	unsigned short numero;
} t_patente;

struct nodo_t_patente{
    t_patente patente;
    struct nodo_t_patente *sig;
};
typedef struct nodo_t_patente nodo_t_patente;

nodo_t_patente* inizializarVectorPatentes(){
	nodo_t_patente *vectorPatentes = NULL;
	return vectorPatentes;
}

void agregarPatenteAVector(t_patente nuevaPatente, nodo_t_patente *vectorPatentes){
	nodo_t_patente *nuevoNodoPatente = malloc(sizeof(nodo_t_patente));
	nuevoNodoPatente->patente = nuevaPatente;
	if (vectorPatentes == NULL) {
		nuevoNodoPatente->sig = NULL;
		vectorPatentes  = nuevoNodoPatente;
	}
	else {
		nuevoNodoPatente->sig = vectorPatentes;
		vectorPatentes = nuevoNodoPatente;
	}
}

t_patente nuevaPatente(char* letras, unsigned short numero){
	t_patente patente;
	patente.letras = strdup(letras);
	patente.numero = numero;
	return patente;
}

int main(void){
	nodo_t_patente *patentes = inizializarVectorPatentes();

	agregarPatenteAVector(nuevaPatente("ABC", 123), patentes);
	agregarPatenteAVector(nuevaPatente("SQL", 35), patentes);
	agregarPatenteAVector(nuevaPatente("UTN", 999), patentes);
	return 0;
}
```
Muchas gracias por el tiempo, quizás es una tonteria, pero estuve intentando un buen rato y ya no se me ocurrió que podia ser.

**Comment by ncoen97** [comment]
Buenas! 
Este es un foro para consultas sobre la materia Sistemas Operativos de la UTN FRBA y es exclusivo para la materia.
Saludos.

**Comment by tferraro** [comment]
Buenas!
Me agarró curiosidad e igual le pegué una mirada 😛 y tengo un poco de feedback:
El main issue está en que **estás asignando el valor al puntero directamente en las líneas 26 y 30**. Por lógica, todas los reemplazos de "valores" del puntero que hagas, tienen que ser locales :). Sino tienen que ser a algo a lo que apunte el puntero que pasas por parámetro.
Acá estás pasando un puntero, pero pisando su referencia. O pasas un puntero al vector o haces algo más copad y la convertís en una función _pura_ y haces que retorne el vector con la nueva patente agregada y hacés la asignación en el main. Porqué digo que es pura? Porque _no tiene side effect_, no importa cuantas veces la ejecutes, el resultado va a ser el mismo. En el caso de que modifique al vector de patentes, el vector siempre va a crecer (y es una fiaca para tener fiabilidad en la misma).

Por otro lado, levanto un par de warnings que pueden servir:
- Como detalle, no estás creando un vector, sino una **lista enlazada**, son tipos de datos diferentes en su naturaleza 😉 
- El inicializarVectorPatentes() no tiene sentido de existencia si lo que hace es setear NULL al retorno. Un buen compilador sabría reducir esa funcion a una expressión, por lo que solo agrega ruido 🤷‍♂ 
- Tu t_patente es local a la función que lo estás llamando . Por lo general suele traer bugs cuando salis del contesto de esa función y mantenes variables locales guardadas en una lista dinámica. La  regla de oro es: Si vas a trabajar con una lista dinámica, los elementos también deben serlo.

Saludos!

**Comment by leobz** [comment]
Muchas Gracias @tferraro ! Ahí lo pude resolver!  
PD: @ncoen97 si, es un ejercicio que esta en la Guía de Debug con Eclipse de la Cátedra.
(https://docs.google.com/document/d/16vNTvgYpmojT9vNOLf9MOSEG-EcmozHIGyNx8h5JmoI/pub)
