### ISSUE TITLE
Error en vagrant al intentar descargar la caja

### ISSUE THREAD

**Issue by Mati-Jurado** [sisoputnfrba/foro#1592]
Buenas noches!

Intente instalar la VM desde [este repo](https://github.com/sisoputnfrba/sisop_vms)

Me baje VirtualBox, el vagrant, pero al ejecutar el comando vagrant up (para crear la VM grafica)

me tira el siguiente error: 

The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and that enough disk space
is available and then try again.
The output from attempting to unpackage (if any):

x box.ovf: Cannot extract through symlink \\\\?\\C:\\Users\\JuradoMatias
x Vagrantfile: Cannot extract through symlink \\\\?\\C:\\Users\\JuradoMatias
x metadata.json: Cannot extract through symlink \\\\?\\C:\\Users\\JuradoMatias
x ubuntu-bionic-18.04-cloudimg.mf: Cannot extract through symlink \\\\?\\C:\\Users\\JuradoMatias
x ubuntu-bionic-18.04-cloudimg.vmdk: Cannot extract through symlink \\\\?\\C:\\Users\\JuradoMatias
x ubuntu-bionic-18.04-cloudimg-configdrive.vmdk: Cannot extract through symlink \\\\?\\C:\\Users\\JuradoMatias
bsdtar.EXE: Error exit delayed from previous errors.
![image](https://user-images.githubusercontent.com/37599133/77838254-959e8780-7148-11ea-9b1d-11f8fd711ee5.png)

Lo corri bajo un windows 10, de 64bits.
Cualquier ayuda, será bienvenida!

Gracias de antemano!

**Comment by mgarciaisaia** [comment]
Qué... Situación extraña, che...

Parece que `vagrant` está ejecutando `bsdtar`, que sería un comando de los Unix BSD para extraer archivos `tar` - _portado a Windows_. Eso, o `vagrant` corre en un entorno Cygwin o similar.

Y ese `bsdtar` se está quejando de que está intentando extraer los archivos que se bajó a un directorio que intenta ser tu carpeta de usuario, pero parece que algo se rompió y tiene unas `\\` extra adelante. ¿Y eso lo hace creer que son enlaces simbólicos y por eso falla?

Arrancaría por mirar qué onda con tu directorio home (si la tenés en un disco/partición aparte montada con alguna cosa "nueva" de Windows), y después probaría de descargar una cajita chiquita con `vagrant` (onda, [`cylab/tiny-core`](https://app.vagrantup.com/cylab/boxes/tiny-core)) a ver si esa sí puede extraerla.

Y el chequeo de rutina de ver que tengas mucho espacio libre en disco.

Fijate todo eso, comentá qué resultados tuviste con cada cosa, y vemos cómo seguir chamuyando hasta que agarre viaje 🤔

**Comment by Mati-Jurado** [comment]
Espacio en el disco tengo, esta ubicado en una carpeta de la raíz... con el tema del usuario puede que haya un problema ubicación (porque se llama kjj el usuario pero con algo de "windows" le cambie el nombre por el que se ve en la imagen, pero físicamente sigue estando el viejo también, pero como otro usuario al cual le pega este, no se, es algo raro de windows)

La verdad que no me llevo bien con todo esto, por desconocimiento, claro está. Probé de esta forma porque había instalado de la forma tradicional hace un tiempo y se rompió al rato de que la use (salio error no se que y no había forma de repararlo y me dijeron ni idea, create otra) asi que lo borre y quise darle una oportunidad a este nuevo método que se veía prometedor.

Si queres -y tenes tiempo- , te doy control de la maquina (teamviewer o teams), porque entiendo muy poco como para ir tocando configuraciones, quise cambiar la ruta de descarga (para que descargue el que me pasaste) pero me tiro otro error.

me descargue externamente la caja que intentaba descargar e instalar vagrant y parece que se descargo bien, pero ni idea como ejecutar

Gracias! y lamento no poder seguirte

**Comment by mgarciaisaia** [comment]
La verdad es que no me llevo con Windows lo suficiente como para entender. Esto de que tenés el directorio home en un lugar distinto suena a _algo que alguna herramienta puede interpretar como un softlink_.

Mi consejo, si no querés volverte loco con este asunto, es que te bajes el disco de la VM desde la página, [crees la máquina siguiendo los pasos del video](https://faq.utnso.com.ar/setup-vm), y, ni bien tengas la máquina creada, crees un Snapshot. Con eso, si eventualmente se te rompe algo de la VM, la podés restaurar a ese punto, y es como deshacer todos los cambios que le habías hechos. Digamos, tenés un punto seguro al que volver, pase lo que pase.

Fijate si eso te resuelve. Si no, vemos de charlar un rato y tratar de resolver.

¡Un abrazo, che!

**Comment by iago64** [comment]
Buenas buenas!

Veo que encontraste el repo de las VM 6.0, bueno, por desgracia esas VMs todavia no estan listas en un 100%, es algo en lo que venimos trabajando desde el cuatri pasado, pero que aun no estamos 100% seguros de que funcionen a la perfección y para todos, con lo cual, te recomiendo que bajes las VMs que estan linkeadas en el [blog](https://www.utnso.com.ar/recursos/maquinas-virtuales/).

Cualquier cosa si queres pegarle una revisada por mera curiosidad, sos mas que bienvenido y cualquier cosita que encuentres que no funcione como lo decimos y/o tengamos que corregir esta mas que joya que nos tires un pase para ver si definimos :)

Abrazo.-

**Comment by Mati-Jurado** [comment]
Buenas! Gracias por la buena onda de los dos!

Si el otro dia ya a habia borrado e instalado de la manera vieja, pero tuve el mismo problema que tuvieron unos compañeros (otro issue) el cual radicaba en compartir el portapapeles entre el so y la vm, encontre la [issue](https://github.com/sisoputnfrba/foro/issues/1597) que habla sobre eso y también tenia instalada la version de 6.1 de VirtualBox.

Marcaré la issue como resuelta, ya que mi problema era que no podía usar la VM... y eso se solucionó.

Por otro lado, si un día encuentro la solución de lo que me sucedió con vagrant, se los haré saber para el mismo saber y al reportarlo, capaz le sería útil a otra persona.

Les agradezco a los dos!
