### ISSUE TITLE
Error instalacion Guest Additions

### ISSUE THREAD

**Issue by EmaSedlar** [sisoputnfrba/foro#1593]
Buenas, mi error surge cuando ingreso a DISPOSITIVOS --> INSERTAR IMAGEN DE CD DE LAS GUEST ADDITIONS y me tira este mensaje:

![error](https://user-images.githubusercontent.com/38228357/77863009-96412780-71f5-11ea-87f6-ed77059a0587.jpg)

por lo tanto cuando luego quiero seguir los pasos del vídeo para instalar, no funciona. 

Estuve viendo issues parecidos pero ninguno me pudo ayudar a solucionar el problema. 

Muchas gracias

**Comment by mgarciaisaia** [comment]
👋 Qué bizarro, che. Garrón toparse con estas cosas. =/

[Acá](https://askubuntu.com/questions/596998/unable-to-install-guest-additions-unknown-filesystem-type-iso9660) dicen que primero pruebes reiniciando el Linux, a ver si con eso safa.

Si eso no funciona, que ejecutes este comando: `sudo apt-get install --reinstall linux-image-$(uname -r)` (tipealo tal cual, con el `$(` y todo. Eso te va a reinstalar el kernel de Linux (si todavía no tenés tanta idea de qué es el kernel, tenés todo este cuatri para formarte la noción 😇), y cuando reinicies la máquina debería mejorar la cosa.

De todos modos, si todavía tenés los archivos que descargaste (las partes de la VM) y no habías laburado mucho en la VM, _quizá_ tenga sentido borrarla e instalarla de vuelta. No sé si sabrás qué hiciste en la VM para llegar a este error.

Anyway, probá eso y contá qué onda.

¡Éxitos!

**Comment by EmaSedlar** [comment]
Pude solucionarlo borrando todo y volviendo a instalar, en este caso instale una Virtual Box 5.2.12. Nose si fue eso u otra cosa.

Cerro el issue así no confundo a los demás. 

Gracias!
