### ISSUE TITLE
Dudas mensajes y Socket TP0 (1C2020)

### ISSUE THREAD

**Issue by Phiiliip** [sisoputnfrba/foro#1594]
1) El servidor que se nos da (Game-Watch-Server) solamente hay que hacerle MAKE y correr el Server y eso automáticamente queda a la escucha de nuestros mensajes enviados?

2) ¿Como puedo saber si la conexión se crea satisfactoriamente? ( Esta función ya está desarrollada en el tp0)

3) Me leí la guía de serializacion y esta muy buena y completa, pero mi duda es si hay que realizar todo el empaquetado, aun cuando quiero enviar únicamente un String (En la guía se envía un tipo de dato Persona con varios campos)

Perdón por adelantado si ya está respondido, pero busqué en los issues y solo encontré este (https://github.com/sisoputnfrba/foro/issues/1216) y no me fue de ayuda.

Gracias y saludos.

**Comment by dariokozicki** [comment]
Hola Philip, soy estudiante pero acá va:
1. Exactamente. El servidor espera en 127.0.0.1:4444 a que se conecten clientes. Vas a necesitar dos consolas, una para ejecutar el server y otra para el cliente. Te recomiendo que llenes de logs el server, a mí me ayudó.
2. En el cliente, cuando no se logre conectar ya está implementada una función que imprime "error" cuando éste no se logra conectar. De todas maneras te podés agregar un log_info de ambos lados para asegurarte.
3. [tl;dr: Sí, es necesario en este ejemplo. El servidor espera que lo envíes empaquetado y va a hacer cualquier verdura si enviás solo el string] La lógica de hacer el empaquetado pasa porque A. Como servidor, no tenés forma de saber el tamaño de lo que enviás y B. No sabés cómo interpretar la información que se te envía. Vos envías el String. Cómo sabe el servidor cuánto tiene que leer? Cómo sabe que le estás enviando un String y no una Persona? De ahí la burocracia de operación->tamaño->payload.

**Comment by Phiiliip** [comment]
Perfecto, muchas gracias por la ayuda.
Estuve probando y fijándome y la conexión es exitosa, parece ser que mi problema se encuentra en los tamaños de lo que estoy enviando debido a que lo que recibe el cliente son caracteres raros, sin sentido a lo que yo originalmente envío.

Si tenes alguna sugerencia para esto es bienvenida.

Saludos!

**Comment by mgarciaisaia** [comment]
@Phiiliip revisate el código del servidor para ver cómo interpreta los bytes que recibe (cuántos bytes para cada cosa lee), y chequeate del lado del cliente estar enviando lo mismo.

**Comment by Phiiliip** [comment]
@mgarciaisaia Buenas, gracias por la respuesta. Estuve mirando e intente replicar la lógica que utiliza, pero evidentemente estoy teniendo errores en el tamaño de lo que envío o mismo en el serializado del paquete.

Estuve releyendo el Doc de serializacion pero no logro encontrar el error.

Gracias

**Comment by mgarciaisaia** [comment]
Tratá de buscar el cacho de código que te parezca más relevante y pasalo por acá.

Digamos, sin saber qué estás haciendo, imposible saber qué es lo que está mal 😇

**Comment by Phiiliip** [comment]
Buenas @mgarciaisaia :

Logré que el Server reciba mi mensaje correctamente y lo imprima por pantalla, lo que no puedo resolver es la recepción del mensaje en el cliente:

Esta es la función del cliente, la cual esta copiada del Servidor:
```
char* recibir_mensaje(int socket_cliente) {


	int* size;
	void * buffer;

	recv(socket_cliente, size, sizeof(int), MSG_WAITALL);
	buffer = malloc(*size);
	recv(socket_cliente, buffer, *size, MSG_WAITALL);
	return buffer;
}
```
Cuando imprimo el tamaño, da un numero negativo (E.g: -1073802280) y el buffer unos caracteres que la consola no imprime

Disculpas por las molestias y gracias

**Comment by mgarciaisaia** [comment]
Nada de disculpá, bolas. Estamos acá para esto :)

Segundo, nada, no te creo una goma que eso esté copiado del server. Prestale atención a la variable `size`. ¿Qué _querrías_ que esté haciendo? Ahora prestale _más_ atención: ¿qué es lo que efectivamente está haciendo?

Pensá de qué tipo es la variable, que significa eso, qué valor tiene la variable, y qué valor te gustaría que tuviera antes de entrar al `recv`. Podés usar el debugger de Eclipse para inspeccionar, si gustás.

**Comment by Phiiliip** [comment]
Buenas @mgarciaisaia :

Te juro, la funcion `void* recibir_mensaje(int socket_cliente, int* size)` dentro de "Game-watch-server/utils.c" es idéntica

Con el tema del size, yo necesito esta variable para saber el tamaño del payload que voy a recibir, para así poderle asignar memoria y leer todos los caracteres que son enviados.

En cuanto a lo del valor previo al recv, no se si quisiera que tenga un valor en particular porque ese el dato que necesito para seguir.

Me tiene medio bloqueado el asunto :(

Gracias

**Comment by mgarciaisaia** [comment]
Prestale atención al código del Server:

https://github.com/sisoputnfrba/Game-watch-server/blob/4eda9e6f845cac177667bdfd0f6f2ae842091521/utils.c#L80-L89

En ese caso, `size` es un puntero (`int *`), y es responsabilidad de la función _que usa_ `recibir_mensaje` reservarle memoria y hacer que `size` apunte correctamente.

En tu ejemplo, `size` también es un puntero, pero no tiene memoria reservada. Si tiene un valor, apunta a cualquier lado. Por eso cuando intentás escribirle 4 bytes en `recv` te da cualquier cosa, y por eso el número que leés es negativo (**re** buen ejemplo de "cualquier cosa" 😛) y por eso después intentás hacer `malloc` de un número negativo y bue.

**Comment by Phiiliip** [comment]
Buenas @mgarciaisaia:

Entiendo lo que me explicaste y ahora me queda claro, pero lo que no logro ver es, dentro del código del servidor, en que momento le hace un malloc a ese puntero ya que:

```
void process_request(int cod_op, int cliente_fd) {
	int size;
	void* msg;
		switch (cod_op) {
		case MENSAJE:
			msg = recibir_mensaje(cliente_fd, &size);
```
y luego ya en la función **recibir_mensaje** lo toma como un int*

Gracias

**Comment by dariokozicki** [comment]
Como int size no es un puntero, no requiere malloc. De ahí lo único que hace es pasar a recibir_mensaje por referencia, que hace un recv que dice "sacá de este socket un pedazo de tamaño sizeof(int) y encajalo en el valor de la variable size".

recv(socket_cliente, size, sizeof(int), MSG_WAITALL);

**Comment by mgarciaisaia** [comment]
Exacto. Es lo que dice @dariokozicki.

Cuando declarás una variable en C, el compilador te reserva memoria para ella. El tema es que cuando declarás un puntero, lo que C te reserva es memoria _para el puntero_, y **no** para _la cosa apuntada_.

En el ejemplo del server, la memoria se reserva en `process_request` al hacer `int size;`, y a `recibir_mensaje` se le manda la dirección/el puntero.

En tu caso, sólo estabas declarando el puntero - pero no inicializabas _a dónde apunta_.

**Comment by Phiiliip** [comment]
Buenas @mgarciaisaia @dariokozicki, gracias a ambos por la atención.

Entendí su explicación y estuve debuggeando y logre encontrar un inconveniente.
A la hora de contar la cantidad de bytes que, desde el Cliente ,quiero enviar, hago lo siguiente:

```
int bytes = paquete->buffer->size + 2 * sizeof(int);
void* a_enviar = serializar_paquete(paquete,bytes);

send(socket_cliente, a_enviar, bytes, 0);
```
**_Printf de los bytes (previo a enviar) = 16_**

El resultado me da 16 y es correcto ya que mi mensaje elegido es "Mensaje\0" (8 bytes) + 2 veces los 4 bytes del int.

A la hora de serializar, se hace de forma correcta ya que luego de hacer el memcpy() a cada uno de los campos, el desplazamiento finaliza en la posición 16 (Mi función es copia de la del servidor):

```
void* serializar_paquete(t_paquete*, int bytes){
void* magic = malloc(bytes);
int desplazamiento = 0;

memcpy(magic + desplazamiento, &(paquete->codigo_operacion), sizeof(int);
desplazamiento += sizeof(int);

memcpy(magic + desplazamiento, &(paquete -> buffer -> size), sizeof(int));
desplazamiento + sizeof(int);
memcpy(magic + desplazamiento, (paquete->buffer->stream), paquete->buffer->size);
desplazamiento += paquete -> buffer -> size;

return magic;
}
```

Debuggeando el servidor, me doy cuenta que, cuando el servidor recibe el tamaño de lo que le voy a enviar, está recibiendo solo 8 bytes, por lo que el problema, previamente a mi error en la recepción de los bytes, es en el envío.


Gracias y saludos

**Comment by mgarciaisaia** [comment]
👋 Chequeate bien los mensajes que te da el compilador al (ouch) _compilar_. 

```c
int bytes = paquete->buffer->size + 2 * sizeof(int);
void* a_enviar = serializar_paquete(paquete,bytes); // <-- Acá *seguro* que te tira un warning

send(socket_cliente, a_enviar, bytes, 0);
```

Buscá en los mensajes del compilador. Si esta función está copiada _posta_ de lo que estásá compilando, **seguro** que tenés un warning en esa línea. ¿Cuál es el warning?

¿Qué parámetros le estás pasando a `serializar_paquete`? Y, ¿qué parámetros _espera_?

**Comment by Phiiliip** [comment]
Buenas @mgarciaisaia 

En esa linea particularmente no me tira ningun warning.

En todo el proyecto, en la parte del cliente, solo tengo 2 warning y es por printf.

`Serializar_paquete(t_paquete* paquete, int bytes)`

El paquete que le estoy pasando lo armo y envío de la siguiente manera:

```
mensaje = "Mensaje\0";
t_paquete* paquete = malloc(sizeof(paquete));
paquete->codigo_operacion = MENSAJE;
paquete->buffer = malloc(sizeof(t_buffer));
paquete->buffer->size = strlen(mensaje)+1;
paquete->buffer->stream = malloc(paquete->buffer->size);
memcpy(paquete->buffer->stream, mensaje, paquete->buffer->size);
int bytes = paquete->buffer->size + 2 * sizeof(int);
void* a_enviar = serializar_paquete(paquete,bytes);
send(socket_cliente, a_enviar, bytes, 0);
```

Gracias y saludos!

**Comment by mgarciaisaia** [comment]
@Phiiliip andás por [el Discord de la cátedra](https://discord.gg/6GHb8X)? Escribime por ahí así tratamos de ver qué está pasando.

**Comment by Phiiliip** [comment]
Buenas, luego de una ayuda intensiva de @mgarciaisaia logramos encontrar los errores:

1) Estaba utilizando un **int*** en lugar de un **int**
2) No estaba respetando el protocolo de envío y recepción de los mensajes, por lo que lo que yo estaba recibiendo era solamente una fracción del total que el servidor estaba enviando.

El código de enviar_mensaje() paso de :

```
char* recibir_mensaje(int socket_cliente) {
	int* size;
	void * buffer;
	recv(socket_cliente, size, sizeof(int), MSG_WAITALL);
	buffer = malloc(*size);
	recv(socket_cliente, buffer, *size, MSG_WAITALL);
	return buffer;
}
```

A esto, funcionando correctamente:

```
char* recibir_mensaje(int socket_cliente) {
	int codigo_operacion;
	int size_buffer;
	void * buffer;

	recv(socket_cliente, codigo_operacion, sizeof(int), MSG_WAITALL);

	recv(socket_cliente, size_buffer, sizeof(int), MSG_WAITALL);

	buffer = malloc(size);
	recv(socket_cliente, buffer, size, MSG_WAITALL);

	return (char*) buffer;
}
```

Como experiencia personal, recomiendo seguir el consejo de llenar todo de log_info() y printf(), ya que te salva la vida ver como va moviéndose el programa con los datos.

Cierro el issue, muchas gracias!
