### ISSUE TITLE
Problemas con maquina virtual

### ISSUE THREAD

**Issue by victoriaguillosson** [sisoputnfrba/foro#1595]
Hola a todos!
Me pasa que al crear la maquina virtual en VirtualBox me aparece esto(adjunto imágen):

![problema vm](https://user-images.githubusercontent.com/48684404/77926357-6ab55000-727c-11ea-9e13-55a5029c96dd.JPG)

Alguno sabe que puede ser?
Saludos!

**Comment by mgarciaisaia** [comment]
¡Hola!

Dicen [por acá](https://superuser.com/questions/1403346/error-message-when-i-try-to-run-a-virtual-computer/1403347) que el problema es que tu compu tiene deshabilitada en la BIOS (la configuración más base de la compu, antes de que arranque el sistema operativo) la virtualización.

Esto puede ser porque: a) está deshabilitada y hay que habilitarla; o b) tu compu no soporte virtualización.

Tendrías que averiguar para tu modelo específico de computadora cómo entrar a la BIOS (usualmente implica algo como mantener apretado F10 cuando prendés la compu, o tocar F2 o DELETE o algo así), y después ver en qué menú de todo eso está la opción para prender la virtualización. Si es que está.

Lo más divertido de esto en cuarentena es que no es algo con lo que te podamos ayudar compartiendo pantalla. Tratá de buscar un poco a ver si encontrás algo de info.

Si no, capaz podemos ver de hacer alguna videollamada para que me muestres la pantalla y vayamos buceando junt@s esas opciones. Pero arrancá por lo otro, así capaz no tenemos que inventar cosas 😛

Si no podés, pasanos el modelo de compu que tengas (en Propiedades de Equipo capaz aparecía, o en alguna etiqueta que tenga pegada tu computadora).

¡Éxitos!

**Comment by mgarciaisaia** [comment]
PD: otro chequeo que mencionaron, pero que no creo que sea, es que te fijes de no haberle asignado más de 3GB de RAM a la VM.

**Comment by victoriaguillosson** [comment]
Muchas gracias!

**Comment by mgarciaisaia** [comment]
¿Pudiste resolver, che? ¿Cuál fue la solución?

Cuente, cuente, que en algún momento le servirá a alguien :)

**Comment by victoriaguillosson** [comment]
Si! Entre a la bios, y en la sección "Advanced" estaba desactivada la
virtualización, entonces la activé y ahora funciona todo🤗🤗
