### ISSUE TITLE
MV- me aparece "no compatible" la virtualizacion

### ISSUE THREAD

**Issue by manupawlow** [sisoputnfrba/foro#1596]
Buenas, tuve un problema al instalar la mv. Hable con un ayudante y me dijo que era porque tenia deshabilitada la virtualización, y me dijo que tenia que entrar a la bios y habiltiarla desde ahi.
Pero cuando entre a la bios no aparecia por ningún lado nada de virtualización o algo relacionado.
Y me fije en el rendimiento y aparece en la parte de virtualización como "no compatible".
Tengo una notebook marca Asus X55A series, y el procesador es Intel Pentium.
No se si puede pasar que una notebook no admita virtualización, o que todas deban poder si o si realizar lo de la virtualización. 
Investigue mucho de este tema pero no encontré una solución.
Supongo que mi maquina no debe poder hacer lo de la virtualización, pero en tal caso me serviría si me pueden decir que hacer.
Muchas gracias.

**Comment by mgarciaisaia** [comment]
👋 Acá hay un video en el que más o menos muestran cómo activar la virtualización. No es garantía de que tu BIOS sea igual, pero fijate si colabora: https://youtu.be/OwNqlicoAu8?t=115

Si no, pasanos el modelo específico de procesador que tenés, a ver qué onda.

Si tu computadora no soportara virtualización, la otra opción es instalar un Lubuntu nativo. Es bastante más complejo que si lográs que te funcione la VM, así que sugeriría que intentes un poco más con lo de configurar la virtualización. Si llegáramos al caso en que confirmamos que no lo soporta, charlemos y te doy una mano para ver cómo seguir.

¡Éxitos!

**Comment by mgarciaisaia** [comment]
@manupawlow ¿pudiste avanzar algo?

**Comment by manupawlow** [comment]
Buenas, al final no pude hacer nada con el tema de la virtualizacion. Pero le pedi a mi hermano que intercambiemos maquinas. Asi que ahora estoy usando la de él, que si tiene habilitado lo de la virtualizacion. 
Perdon que me olvide de avisar y muchas gracias por ayudarme.
Un saludo
