### ISSUE TITLE
Problema para compartir el portapapeles entre la vm y el so

### ISSUE THREAD

**Issue by SebastianNLerner** [sisoputnfrba/foro#1597]
Vi el tutorial de cómo compartir el portapapeles desde el s.o. a la vm. Hice todo lo que me decía, se me guardo la configuración, pero no me funciona.
Vi que decía que podía ser un tema de actualizaciones, puse la opción de buscar actualizaciones y me aparece que está actualizado.
Tambien lei que podia ser un problema de guest additions, pero lo tengo instalado y anda bien.
Alguna idea de que puede estar fallando y como resolverlo?
Muchas gracias

**Comment by mgarciaisaia** [comment]
Seba, capaz te está faltando _habilitar_ el portapapeles compartido.

Teniendo la VM abierta, andá al menú de la ventana de VirtualBox de la VM (no a la ventana general, que lista las VMs que tenés, si no al de la VM en particular de Lubuntu), y tenés que tener un menú Devices/¿Dispositivos? con la opción de Shared Clipboard/¿Portapapeles compartido?, y ahí habilitarle Host to Guest (es decir, que lo que copiás en la compu host puedas pegarlo dentro de la VM) o Bidireccional (para que ambos portapapeles sean compartidos).

![image](https://user-images.githubusercontent.com/1190974/78066404-497f5d00-736b-11ea-8168-361099e54fb3.png)

<img width="735" alt="Screen Shot 2020-03-31 at 16 15 21" src="https://user-images.githubusercontent.com/1190974/78066363-2c4a8e80-736b-11ea-8ee4-86d2d3d8fc96.png">

![image](https://user-images.githubusercontent.com/1190974/78066390-41272200-736b-11ea-8dbc-3fe2bac5f775.png)

**Comment by SebastianNLerner** [comment]
Buenas

Ya tengo tanto el portapapeles compartido como el drag and drop, los dos en bidireccional, pero sigue sin funcionar. Ya probe reiniciando, apagando, cerrando sesion, etc.

**Comment by BautOtero** [comment]
Buenas

Tengo el mismo problema, tengo todo en bidireccional y nada...

**Comment by mgarciaisaia** [comment]
Changos =/

Me cuentan...
1) ¿Qué sistema operativo host tienen?
2) ¿Qué versión de VirtualBox tienen instalada?
3) ¿Qué versión de las Guest Additions tienen instalada en la VM? (pueden chequearlo haciendo `ls /opt` - les va a aparecer un directorio llamado algo como `VBoxGuestAdditions...`)

Capaz con eso podemos averiguar algo más 🤔

**Comment by Nachiten** [comment]
> Changos =/
> 
> Me cuentan...
> 
> 1. ¿Qué sistema operativo host tienen?
> 2. ¿Qué versión de VirtualBox tienen instalada?
> 3. ¿Qué versión de las Guest Additions tienen instalada en la VM? (pueden chequearlo haciendo `ls /opt` - les va a aparecer un directorio llamado algo como `VBoxGuestAdditions...`)
> 
> Capaz con eso podemos averiguar algo más

Tengo el mismo problema que ellos... te respondo tus preguntas para mi caso.

1. Windows 10 PRO 64-Bit
2. Oracle VM VirtualBox 6.1.4
3. VBoxGuestAdditions-6.1.4

No entiendo cual puede llegar a ser el problema por lo tanto tampoco se como googlearlo. Es bastante molesto no poder tener un portapapeles bidireccional... pero me voy acostumbrando.

**Comment by Forche** [comment]
Tuve el mismo problema, lo solucione instalando la versión 6.0.18 de VirtualBox, y reinstalando las GuestAdditions de esa versión en la maquina virtual (hacer los mismos pasos como si nunca las hubieses instalado, remueve las anteriores y carga las nuevas)

**Comment by SebastianNLerner** [comment]
1. Windows 10 home 64-Bit
2. Versión 6.1.4 r136177 (Qt5.6.2)
3. VBoxGuestAdditions-6.1.4

**Comment by mgarciaisaia** [comment]
👋 La verdad, la verdad... No tengo mucha idea de qué puede ser.

Algo que _podría_ también colaborar es saber qué versión del kernel tienen en la VM (lo consiguen haciendo `uname -a` en una consola de Linux).

Lo otro que sugieren en _la internet_ es que consigan un log de qué está pasando con el servicio de portapapeles de su VM. Para esto, primero hagan `ps aux | grep VBoxClient`. Eso les va a dar un listado de todos los procesos que están corriendo en su VM cuyo nombre incluya `VBoxClient`. Algo como este:

```
utnso@ubuntu-server:~$ ps aux | grep VBoxClient
utnso     3188  0.0  0.0  17324   260 ?        S    17:42   0:00 /usr/bin/VBoxClient --display
utnso     3189  0.0  0.1  17324  2680 ?        S    17:42   0:00 /usr/bin/VBoxClient --display
utnso     3190  0.0  0.0  17324   264 ?        S    17:42   0:00 /usr/bin/VBoxClient --clipboard
utnso     3191  0.0  0.1  19028  4052 ?        Sl   17:42   0:00 /usr/bin/VBoxClient --clipboard
utnso     3192  0.0  0.0  17324   260 ?        S    17:42   0:00 /usr/bin/VBoxClient --seamless
utnso     3195  0.0  0.1  19008  2156 ?        Sl   17:42   0:00 /usr/bin/VBoxClient --seamless
utnso     3201  0.0  0.0  17324   236 ?        S    17:42   0:00 /usr/bin/VBoxClient --draganddrop
utnso     3204  0.1  0.0  19524  2000 ?        Sl   17:42   0:09 /usr/bin/VBoxClient --draganddrop
utnso    25878  0.0  0.0   6328   832 pts/5    S+   19:52   0:00 grep --color=auto VBoxClient
```

Si prestan atención, hay 2 filas (la tercera y cuarta fila) que dicen `VBoxClient --clipboard`. Esos dos procesos son _el servicio de portapapeles compartido_ de VirtualBox en su VM.

La segunda columna de esa tabla (la primer columna numérica) indica el PID (process ID) de cada uno de los procesos. En este caso, mis dos procesos relativos al clipboard tienen los PIDs `3190` y `3191`. **En su máquina probablemente sean distintos**.

Lo que vamos a hacer es _terminar_ esos procesos, ejecutando el comando `kill` con los PIDs que vimos antes. Entonces, en mi caso voy a hacer `kill 3190 3191` - ustedes tienen que cambiar esos números por los que correspondan.

Hecho esto, vuelvan a correr el `ps aux | grep VBoxClient`, y deberían ver _el mismo listado_, pero con dos entradas menos - los dos procesos que acabamos de matar. Si siguen apareciendo los procesos, vuelvan a chequear los PID y vuelvan a probar el `kill`.

Cuando estén libres de `VBoxClient --clipboard`, vamos a volver a ejecutar el servicio, pero _con los logs activados_, para ver qué está pasando.

Para hacer esto, en una terminal ejecuten este comando:

```
VBOX_RELEASE_LOG_DEST='file=/home/utnso/clipboard.log' VBOX_RELEASE_LOG=all.e.l.l2.f VBoxClient --clipboard --nodaemon --foreground
```

Lo que estamos haciendo es ejecutar `VBoxClient --clipboard` (es decir, el servicio de portapapeles compartido), pero pidiéndole que quede ejecutando en la terminal activa en vez de hacerlo en segundo plano para poder cerrarlo fácil (`--nodaemon --foreground`), y pidiéndole que loggee su información en el archivo `/home/utnso/clipboard.log` (las dos variables de entorno que escribimos antes).

Hecho eso, debería quedarles esa consola sin imprimir nada (no les devuelve la línea de comandos), y el servicio está iniciado. Si abren una nueva consola podrán hacer `tail -f /home/utnso/clipboard.log` para ver el log del servicio, actualizándose cada vez que el proceso escriba ahí.

Y ahí, nada - o les va a aparecer algún error, o prueben de copiar y tratar de pegar algo desde/hacia la VM, y después de probar un par de veces compartan acá el log que consiguieron, así vemos qué onda.

Mucho más no sabría decirles, por ahora 🤷‍♂

Éxitos, che.

**Comment by Nachiten** [comment]
> wave La verdad, la verdad... No tengo mucha idea de qué puede ser.
> 
> Algo que _podría_ también colaborar es saber qué versión del kernel tienen en la VM (lo consiguen haciendo `uname -a` en una consola de Linux).
> 
> Lo otro que sugieren en _la internet_ es que consigan un log de qué está pasando con el servicio de portapapeles de su VM. Para esto, primero hagan `ps aux | grep VBoxClient`. Eso les va a dar un listado de todos los procesos que están corriendo en su VM cuyo nombre incluya `VBoxClient`. Algo como este:
> 
> ```
> utnso@ubuntu-server:~$ ps aux | grep VBoxClient
> utnso     3188  0.0  0.0  17324   260 ?        S    17:42   0:00 /usr/bin/VBoxClient --display
> utnso     3189  0.0  0.1  17324  2680 ?        S    17:42   0:00 /usr/bin/VBoxClient --display
> utnso     3190  0.0  0.0  17324   264 ?        S    17:42   0:00 /usr/bin/VBoxClient --clipboard
> utnso     3191  0.0  0.1  19028  4052 ?        Sl   17:42   0:00 /usr/bin/VBoxClient --clipboard
> utnso     3192  0.0  0.0  17324   260 ?        S    17:42   0:00 /usr/bin/VBoxClient --seamless
> utnso     3195  0.0  0.1  19008  2156 ?        Sl   17:42   0:00 /usr/bin/VBoxClient --seamless
> utnso     3201  0.0  0.0  17324   236 ?        S    17:42   0:00 /usr/bin/VBoxClient --draganddrop
> utnso     3204  0.1  0.0  19524  2000 ?        Sl   17:42   0:09 /usr/bin/VBoxClient --draganddrop
> utnso    25878  0.0  0.0   6328   832 pts/5    S+   19:52   0:00 grep --color=auto VBoxClient
> ```
> 
> Si prestan atención, hay 2 filas (la tercera y cuarta fila) que dicen `VBoxClient --clipboard`. Esos dos procesos son _el servicio de portapapeles compartido_ de VirtualBox en su VM.
> 
> La segunda columna de esa tabla (la primer columna numérica) indica el PID (process ID) de cada uno de los procesos. En este caso, mis dos procesos relativos al clipboard tienen los PIDs `3190` y `3191`. **En su máquina probablemente sean distintos**.
> 
> Lo que vamos a hacer es _terminar_ esos procesos, ejecutando el comando `kill` con los PIDs que vimos antes. Entonces, en mi caso voy a hacer `kill 3190 3191` - ustedes tienen que cambiar esos números por los que correspondan.
> 
> Hecho esto, vuelvan a correr el `ps aux | grep VBoxClient`, y deberían ver _el mismo listado_, pero con dos entradas menos - los dos procesos que acabamos de matar. Si siguen apareciendo los procesos, vuelvan a chequear los PID y vuelvan a probar el `kill`.
> 
> Cuando estén libres de `VBoxClient --clipboard`, vamos a volver a ejecutar el servicio, pero _con los logs activados_, para ver qué está pasando.
> 
> Para hacer esto, en una terminal ejecuten este comando:
> 
> ```
> VBOX_RELEASE_LOG_DEST='file=/home/utnso/clipboard.log' VBOX_RELEASE_LOG=all.e.l.l2.f VBoxClient --clipboard --nodaemon --foreground
> ```
> 
> Lo que estamos haciendo es ejecutar `VBoxClient --clipboard` (es decir, el servicio de portapapeles compartido), pero pidiéndole que quede ejecutando en la terminal activa en vez de hacerlo en segundo plano para poder cerrarlo fácil (`--nodaemon --foreground`), y pidiéndole que loggee su información en el archivo `/home/utnso/clipboard.log` (las dos variables de entorno que escribimos antes).
> 
> Hecho eso, debería quedarles esa consola sin imprimir nada (no les devuelve la línea de comandos), y el servicio está iniciado. Si abren una nueva consola podrán hacer `tail -f /home/utnso/clipboard.log` para ver el log del servicio, actualizándose cada vez que el proceso escriba ahí.
> 
> Y ahí, nada - o les va a aparecer algún error, o prueben de copiar y tratar de pegar algo desde/hacia la VM, y después de probar un par de veces compartan acá el log que consiguieron, así vemos qué onda.
> 
> Mucho más no sabría decirles, por ahora man_shrugging
> 
> Éxitos, che.

Bien. Primero que nada gracias por toda tu ayuda...

Ahora te voy a tirar todaa la info de lo que yo hice:


```
utnso@ubuntu-server:~$ uname -a
Linux ubuntu-server 4.4.0-176-generic #206-Ubuntu SMP Fri Feb 28 05:00:50 UTC 2020 i686 i686 i686 GNU/Linux
```
Aca podes ver como tire para saber la version de kernel.

```
utnso@ubuntu-server:~$ ps aux | grep VBoxClient
utnso     2710  0.0  0.0  17368   316 ?        S    10:00   0:00 /usr/bin/VBoxClient --display
utnso     2712  0.0  0.2  17512  2824 ?        S    10:00   0:00 /usr/bin/VBoxClient --display
utnso     2715  0.0  0.0  17368   316 ?        S    10:00   0:00 /usr/bin/VBoxClient --seamless
utnso     2717  0.0  0.2  20592  2856 ?        Sl   10:00   0:00 /usr/bin/VBoxClient --seamless
utnso     2720  0.0  0.0  17368   320 ?        S    10:00   0:00 /usr/bin/VBoxClient --draganddrop
utnso     2721  0.2  0.2  21108  2988 ?        Sl   10:00   0:02 /usr/bin/VBoxClient --draganddrop
utnso     2725  0.0  0.0  17368   316 ?        S    10:00   0:00 /usr/bin/VBoxClient --vmsvga-x11
utnso     2726  0.0  0.3  17500  3272 ?        S    10:00   0:00 /usr/bin/VBoxClient --vmsvga-x11
utnso     4175  0.0  0.0   6324   812 pts/1    S+   10:16   0:00 grep --color=auto VBoxClient
```

Luego tire el `ps aux | grep VBoxClient` y podemos notar que en ningun momento aparece el famoso `--clipboard` que a vos si te aparecio. Mi sentido comun me dijo mm si no puedo matar el proceso porque no está entonces lo inicio directamente ya que supongo que algo mistico pasó que realmente no está en ejecución.

Aca viene la parte mas loca :O el proceso falló con un segmentation fault D:

```
utnso@ubuntu-server:~$ VBOX_RELEASE_LOG_DEST='file=/home/utnso/clipboard.log' VBOX_RELEASE_LOG=all.e.l.l2.f VBoxClient --clipboard --nodaemon --foreground
vboxClientSetSignalHandlers: ENTER
vboxClientSetSignalHandlers: LEAVE

// (unas 15 lineas vacias que las corté por obvias razones)

Segmentation fault (core dumped)
utnso@ubuntu-server:~$ 
```
Me dijo "core dumped" claramente no tengo ni la mas pálida idea de que significa esto.

Acá está toda la info ojala alguien me pueda dar una manito. Muchas gracias :)

**Comment by Nachiten** [comment]
Ajunto un log que me dio recien despues de probar un par de veces de prender el servicio y que siempre crasheara:

```
utnso@ubuntu-server:~$ ps aux | grep VBoxClient
utnso     2882  0.0  0.0  17368     8 ?        S    10:41   0:00 /usr/bin/VBoxClient --display
utnso     2883  0.0  0.2  17512  2456 ?        S    10:41   0:00 /usr/bin/VBoxClient --display
utnso     2889  0.0  0.0  17368   100 ?        S    10:41   0:00 /usr/bin/VBoxClient --seamless
utnso     2891  0.0  0.2  20592  2412 ?        Sl   10:41   0:00 /usr/bin/VBoxClient --seamless
utnso     2896  0.0  0.0  17368     4 ?        S    10:41   0:00 /usr/bin/VBoxClient --draganddrop
utnso     2899  0.2  0.2  21108  2996 ?        Sl   10:41   0:00 /usr/bin/VBoxClient --draganddrop
utnso     2903  0.0  0.0  17368     0 ?        S    10:41   0:00 /usr/bin/VBoxClient --vmsvga-x11
utnso     2905  0.0  0.2  17500  2996 ?        S    10:41   0:00 /usr/bin/VBoxClient --vmsvga-x11
utnso     4173  0.0  0.0   6324   824 ?        D    10:49   0:00 grep -F -lxm 1 -- /opt/VBoxGuestAdditions-6.1.4/bin/VBoxClient /var/lib/dpkg/info/usbutils.list /var/lib/dpkg/info/libxcb-glx0:i386.list /var/lib/dpkg/info/libpopt0:i386.list /var/lib/dpkg/info/libgme0:i386.list /var/lib/dpkg/info/libebook-contacts-1.2-2:i386.list /var/lib/dpkg/info/system-tools-backends.list /var/lib/dpkg/info/libmircommon7:i386.list /var/lib/dpkg/info/libxatracker2:i386.list /var/lib/dpkg/info/network-manager.list /var/lib/dpkg/info/libgmlib1:i386.list /var/lib/dpkg/info/policykit-1.list /var/lib/dpkg/info/tk.list /var/lib/dpkg/info/cups-browsed.list /var/lib/dpkg/info/python3-software-properties.list /var/lib/dpkg/info/libxcb-present0:i386.list /var/lib/dpkg/info/libtie-ixhash-perl.list /var/lib/dpkg/info/libdirectfb-1.2-9:i386.list /var/lib/dpkg/info/libutempter0:i386.list /var/lib/dpkg/info/libxcb-shape0:i386.list /var/lib/dpkg/info/gvfs-backends.list /var/lib/dpkg/info/vim-tiny.list /var/lib/dpkg/info/libgnomekbd8:i386.list /var/lib/dpkg/info/libspectre1:i386.list /var/lib/dpkg/info/libxrender1:i386.list /var/lib/dpkg/info/evolution-data-server-online-accounts.list /var/lib/dpkg/info/vbetool.list /var/lib/dpkg/info/libsodium18:i386.list /var/lib/dpkg/info/libatkmm-1.6-1v5:i386.list /var/lib/dpkg/info/ubuntu-drivers-common.list /var/lib/dpkg/info/fonts-tlwg-laksaman-ttf.list /var/lib/dpkg/info/python-pyorbit.list /var/lib/dpkg/info/open-iscsi.list /var/lib/dpkg/info/transmission.list /var/lib/dpkg/info/libsigsegv2:i386.list /var/lib/dpkg/info/libtbb2:i386.list /var/lib/dpkg/info/libmono-sqlite4.0-cil.list /var/lib/dpkg/info/gir1.2-dbusmenu-glib-0.4:i386.list /var/lib/dpkg/info/libexo-helpers.list /var/lib/dpkg/info/gdb.list /var/lib/dpkg/info/liboobs-1-5.list /var/lib/dpkg/info/squashfs-tools.list /var/lib/dpkg/info/python3-problem-report.list /var/lib/dpkg/info/gnome-screenshot.list /var/lib/dpkg/info/ubuntu-advantage-tools.list /var/lib/dpkg/info/python-yaml.list /var/lib/dpkg/info/libaccount-plugin-google.list /var/lib/dpkg/info/libsqlite3-0:i386.list /var/lib/dpkg/info/cloud-initramfs-dyn-netconf.list /var/lib/dpkg/info/dosfstools.list /var/lib/dpkg/info/indicator-application.list /var/lib/dpkg/info/xorg.list /var/lib/dpkg/info/libbonoboui2-0:i386.list /var/lib/dpkg/info/ubuntu-release-upgrader-gtk.list /var/lib/dpkg/info/libfltk1.1:i386.list /var/lib/dpkg/info/mount.list /var/lib/dpkg/info/obconf.list /var/lib/dpkg/info/libgoa-1.0-common.list /var/lib/dpkg/info/libasound2:i386.list /var/lib/dpkg/info/pidgin-data.list /var/lib/dpkg/info/libblkid1:i386.list /var/lib/dpkg/info/libmspack0:i386.list /var/lib/dpkg/info/libhttp-parser2.1:i386.list /var/lib/dpkg/info/libmagickcore-6.q16-2:i386.list /var/lib/dpkg/info/grub-gfxpayload-lists.list /var/lib/dpkg/info/libdrm-common.list /var/lib/dpkg/info/libindicator3-7.list /var/lib/dpkg/info/libffi-dev:i386.list /var/lib/dpkg/info/libgdbm-dev.list /var/lib/dpkg/info/libmono-corlib4.5-cil.list /var/lib/dpkg/info/libhyphen0:i386.list /var/lib/dpkg/info/libxft2:i386.list /var/lib/dpkg/info/signon-ui.list /var/lib/dpkg/info/libdebconfclient0:i386.list /var/lib/dpkg/info/sylpheed-i18n.list /var/lib/dpkg/info/libgit2-24:i386.list /var/lib/dpkg/info/linux-headers-4.4.0-116.list /var/lib/dpkg/info/libappindicator3-1.list /var/lib/dpkg/info/libgstreamer1.0-0:i386.list /var/lib/dpkg/info/rsync.list /var/lib/dpkg/info/libcue1.list /var/lib/dpkg/info/fonts-tlwg-umpush.list /var/lib/dpkg/info/libieee1284-3:i386.list /var/lib/dpkg/info/libexo-1-0:i386.list /var/lib/dpkg/info/python3-distupgrade.list /var/lib/dpkg/info/ed.list /var/lib/dpkg/info/netpbm.list /var/lib/dpkg/info/python-dockerpty.list /var/lib/dpkg/info/libroken18-heimdal:i386.list /var/lib/dpkg/info/fwupdate.list /var/lib/dpkg/info/usb-modeswitch.list /var/lib/dpkg/info/cups.list /var/lib/dpkg/info/ttf-ancient-fonts-symbola.list /var/lib/dpkg/info/libgnome-keyring-common.list /var/lib/dpkg/info/libgsf-1-common.list /var/lib/dpkg/info/libxcb1-dev:i386.list /var/lib/dpkg/info/libcheese8:i386.list /var/lib/dpkg/info/evolution-data-server-common.list /var/lib/dpkg/info/terminator.list /var/lib/dpkg/info/libwww-robotrules-perl.list /var/lib/dpkg/info/libdrm-amdgpu1:i386.list
```
No es hermoso? Yo la verdad no se si esto sirve de algo o es basura pero lo dejo por si acaso.

Un saludo :) Por otra parte seria muy practico que yo en algun momento pueda entrar a discord y ahi compartir pantalla para solucionarlo seguramente de manera mas rapida y facil.

**Comment by mgarciaisaia** [comment]
¡Hey, aloha!

Bien ahí con la info. Esa conclusión de "No tengo que matarte si ya estás muerto 😏👈" fue, definitivamente, el punto alto de todo el razonamiento 💯

Que el servicio no esté corriendo _es un muy buen motivo_ para que no funcione. No lo había pensado antes.

El tema es, mi estimad@, que hicimos todo este quilombo para conseguir el log del servicio (para ver por qué no funciona), y cuando conseguís arrancar el servicio y que deje de funcionar... ¡me cortaste el log!

Lo que leí por ahí es que parece ser [un bug más o menos conocido](https://forums.virtualbox.org/viewtopic.php?f=3&t=96957) de algunas versiones de VirtualBox 6.1 (o, en particular, de las GuestAdditions). Algun@s incluso recomiendan downgradear las GuestAdditions de 6.1.4 a 6.1.2 - dejando el host como está -, aunque no tengo idea de cómo hacer eso 🤔

----

Lo que encontré es que yo estaba corriendo una versión vieja de Virtualbox (6.0.algo), y que ahora la actualicé a la más nueva. Reinstalé las guest additions y reinicié, y arrancó con el servicio levantado - pero eventualmente, crashearon los procesos.

Probé el comando que les dejé arriba, y anduvo relativamente bien (no funcionaba, pero no crasheaba) hasta que desde la ventana de la VM le cambié el `Shared Clipboard` a `Disabled`, y después nuevamente a `Bidirectional`. _Ahí crasheó el proceso con un segfault._

Así que el bug parece seguir estando en VirtualBox 6.1.4r136177 (la versión precisa la consiguen con `VBoxClient --version` dentro de la VM).

----

Mientras la gente de VirtualBox se fija qué onda (bah, pueden ir y meterse en el issue tracker y aportar su info, obvio), una opción es _esquivar_ el quilombo bajando alguna versión de [VirtualBox 6.0](https://www.virtualbox.org/wiki/Download_Old_Builds_6_0). Yo creo que tenía la 6.0.8, pero capaz la última 6.0 (6.0.18) ande bien también. Prueba y error, y comenten después :)

Por lo pronto, voy a des-romper mis VMs 😛

**Comment by Nachiten** [comment]
> ¡Hey, aloha!
> 
> Bien ahí con la info. Esa conclusión de "No tengo que matarte si ya estás muerto 😏👈" fue, definitivamente, el punto alto de todo el razonamiento 💯
> 
> Que el servicio no esté corriendo _es un muy buen motivo_ para que no funcione. No lo había pensado antes.
> 
> El tema es, mi estimad@, que hicimos todo este quilombo para conseguir el log del servicio (para ver por qué no funciona), y cuando conseguís arrancar el servicio y que deje de funcionar... ¡me cortaste el log!
> 
> Lo que leí por ahí es que parece ser [un bug más o menos conocido](https://forums.virtualbox.org/viewtopic.php?f=3&t=96957) de algunas versiones de VirtualBox 6.1 (o, en particular, de las GuestAdditions). Algun@s incluso recomiendan downgradear las GuestAdditions de 6.1.4 a 6.1.2 - dejando el host como está -, aunque no tengo idea de cómo hacer eso 🤔
> 
> Lo que encontré es que yo estaba corriendo una versión vieja de Virtualbox (6.0.algo), y que ahora la actualicé a la más nueva. Reinstalé las guest additions y reinicié, y arrancó con el servicio levantado - pero eventualmente, crashearon los procesos.
> 
> Probé el comando que les dejé arriba, y anduvo relativamente bien (no funcionaba, pero no crasheaba) hasta que desde la ventana de la VM le cambié el `Shared Clipboard` a `Disabled`, y después nuevamente a `Bidirectional`. _Ahí crasheó el proceso con un segfault._
> 
> Así que el bug parece seguir estando en VirtualBox 6.1.4r136177 (la versión precisa la consiguen con `VBoxClient --version` dentro de la VM).
> 
> Mientras la gente de VirtualBox se fija qué onda (bah, pueden ir y meterse en el issue tracker y aportar su info, obvio), una opción es _esquivar_ el quilombo bajando alguna versión de [VirtualBox 6.0](https://www.virtualbox.org/wiki/Download_Old_Builds_6_0). Yo creo que tenía la 6.0.8, pero capaz la última 6.0 (6.0.18) ande bien también. Prueba y error, y comenten después :)
> 
> Por lo pronto, voy a des-romper mis VMs 😛

Wait. Entonces me muevo basicamente a la ultima version 6.0 de VirtualBox? Y despues las GA supongo que bajo las correspondientes a esa version de VirtualBox no?

**Comment by iago64** [comment]
Considerando que la gente de VirtualBox suele tener algunos known issues en los nuevos releases siempre es bueno estar un par de versiones atras donde tenemos las chances de saber estos known issues.
Como dice Mati, la mejor salida en estos casos para no complicarse es levantar VBox 6.0 (en alguna version previa) que las puedan encontrar en los [Older Downloads de Virtual Box](https://www.virtualbox.org/wiki/Download_Old_Builds_6_0) y se ahorran un par de dolores de cabeza :)

Abrazo!

**Comment by mesaglio** [comment]
Buenas como digo Dami, el año pasado tuvimos un par de problemas con las Guest Additionts. 
Lo solucionamos instalando una versión mas vieja(5.2). 
Les dejo el [link](https://www.virtualbox.org/wiki/Download_Old_Builds_5_2) por si les sirve.
Si alguno encuentra una versión en la cual le ande bien, agréguenle un comentario al issue detallando la versión.

**Comment by mgarciaisaia** [comment]
Bueno, efectivamente, después de actualizar a la 6.1.4 y que falle el portapapeles compartido, **volví a bajar la 6.0.18 y funciona**.

Tuve que instalar VirtualBox + el Extension Pack, levantar la VM, instalar las Guest Additions nuevamente (me tiró algún comentario sobre que estaba downgradeando las Guest Additions, que si estaba seguro de que quería seguir - la respuesta es sí), y cuando reinicié anduvo joya.

Qué se yo ¯\\\_(ツ)\_/¯

**Comment by Nachiten** [comment]
> Bueno, efectivamente, después de actualizar a la 6.1.4 y que falle el portapapeles compartido, **volví a bajar la 6.0.18 y funciona**.
> 
> Tuve que instalar VirtualBox + el Extension Pack, levantar la VM, instalar las Guest Additions nuevamente (me tiró algún comentario sobre que estaba downgradeando las Guest Additions, que si estaba seguro de que quería seguir - la respuesta es sí), y cuando reinicié anduvo joya.
> 
> Qué se yo ¯\_(ツ)_/¯

Voy a hacer exatamente eso y luego informo por aca las noticias. Muchas gracias

**Comment by Nachiten** [comment]
PROBLEMA: Tengo otro problema mas (que raro yo) D:

Hice lo siguiente: https://www.virtualbox.org/wiki/Download_Old_Builds_6_0 Aca instalé esto: VirtualBox-6.0.18-136238-Win.exe

Luego lo instalé (noto en el Panel de Control de windows que la version esta reemplazó a la anterior segun parece, no estoy seguro)

Y luego instalé las GA version 6.0.18 (la consola me dijo que desinstaló la version mas nueva para instalar esa pero no me dio ningún y/n sobre hacerlo solo lo hizo sin quejarse de nada)

Obvio despues de esto reinicié la VM. Tendré que reiniciar la maquina host?¿

Ahora el único drama que tengo es que estoy ... distinto a como estaba.... básicamente porque ahora ni siquiera se redimensiona la resolución de la VM.

Datos últimos que obtuve entonces simplificando:
1) La pantalla no se me redimensiona la resolucion está fija en 800x600 (no recuerdo que hacer para fixear esto si es que tengo que hacer algo mas que no hice)
2) El portapapeles compartido anda bidireccional :D :D :D 
3) El drag & drop anda de la VM hacia afuera (maq host) pero NO de la host a la VM.
4) La Shared Folder que había creado por suerte también funciona en ambas direcciones.

Básicamente necesito fixear solo el punto 1 y me quedo mas que satisfecho. Que se pueda redimensionar la pantalla (que antes si funcionaba y ahora no)

Muchas Gracias 👍

**Comment by SebastianNLerner** [comment]
Buenas. Me pasa lo mismo, ya puedo copiar y pegar pero no me anda el tema de redimensionamiento de la pantalla

**Comment by mgarciaisaia** [comment]
Bueno, pueden usar la 6.1.4 todo el tiempo, y cuando necesitan copypastear algo instalan temporalmente la 6.0.18... 😛


OK, no. ¿Me chequean que tengan instaladas las GuestAdditions 6.0.18 con `VBoxClient --version` en la VM?

A mí lo que me suele pasar es que para que funcione lo de redimensionar la pantalla tengo que primero agrandar/achicar la ventana de la VM, y después cerrar sesión en Lubuntu y volver a iniciar sesión. ¿Probaron eso? Más fluido que eso _creo_ que no conseguí por ahora.

**Comment by Nachiten** [comment]
utnso@ubuntu-server:~$ VBoxClient --version
6.0.18r136238

@mgarciaisaia

**Comment by SebastianNLerner** [comment]
Si pones el tamaño que queres, cerras secion y volves a entrar funciona.
Ya estoy bastante confundido de como funciona esto

**Comment by Nachiten** [comment]
> Si pones el tamaño que queres, cerras secion y volves a entrar funciona.
> Ya estoy bastante confundido de como funciona esto

No sos el unico... Yo probe de cambiar la resolucion y ahora la VM no me enciende :D Ya no se que hacer

**Comment by Nachiten** [comment]
Para cerrar esto quiero decir que yo al final instalé tanto VirtualBox como Gust Additions versión 6.0.18 y ahí pude hacer andar el portapapeles sin problemas. Luego hice también el cambio que dijiste @iago64 .

Con esto pude hacer andar todo lo que quería 👍 
- La shared folder
- El clipboard compartido
- Y tambien redimensionar la pantalla sin mayores problemas

**Comment by CamiMargni** [comment]
> Hola, si que tal?
> 
> Por suerte el problema que estan teniendo tanto @SebastianNLerner como @Nachiten es algo que ya ~sufrimos~ vimos en otros cuatrimestres y la solucion es tan simple como cambiar el adaptador de pantalla de la VM:
> 
> ![image](https://user-images.githubusercontent.com/1622109/78392126-108af680-75be-11ea-925b-70f95c43457f.png)
> 
> Me juego a decir que muchos lo tienen con el adaptador VMSVGA (que es el que viene por defecto y bastante mala leche y no deja actualizar el tamaño en tiempo real) y la posta esta en tenerlo en VBoxVGA (que es mas copado y te acomoda la pantalla en tiempo real)
> 
> Abrazo!


Hola traté de hacer eso pero me rompió todo eclipse y tampoco me anduvo lo del portapapeles.

**Comment by mgarciaisaia** [comment]
@CamiMargni fijate que a lo largo del thread hay varias recomendaciones de cosas a probar y comandos que nos pueden conseguir información útil para entender qué te puede estar pasando en la VM. Con "me rompió y no anda" no tenemos mucho para hacer más que acompañarte en el sentimiento =/

Fijate si podés revisar eso y darnos algo más de info, así vemos qué puede estar ocurriendo.

**Comment by CamiMargni** [comment]
> @CamiMargni fijate que a lo largo del thread hay varias recomendaciones de cosas a probar y comandos que nos pueden conseguir información útil para entender qué te puede estar pasando en la VM. Con "me rompió y no anda" no tenemos mucho para hacer más que acompañarte en el sentimiento =/
> 
> Fijate si podés revisar eso y darnos algo más de info, así vemos qué puede estar ocurriendo.

No me pasó a mí, sino a un amigo cuando le dije que haga lo del comentario. con romper me referí a que no iniciaba eclipse, o abría pero funcionaba extraño.  Pero optó por volver a la configuración inicial, y se corrigió el error. De todas formas gracias.

**Comment by mapo60** [comment]
A mi se me corrigio el problema de copiar y pegar texto y archivos entre la maquina virtual y mi computador iniciando virtual box como administrador (suena raro pero funciona). Tambien instalando la nueva version y reinstalando las GuestAdditions de esa versión en la maquina virtual.
