### ISSUE TITLE
Guia de Ejercicios C: Punto 1 Parte 2

### ISSUE THREAD

**Issue by Nachiten** [sisoputnfrba/foro#1598]
```
void string_concat_dynamic(char* plb1, char* plb2, char** plbConcat){

	char* punteroTmp;
	punteroTmp = *plbConcat; // saludo 2
	*punteroTmp = *plb1;
}
```
Básicamente no podemos lograr terminar este ejercicio... adjunto también la función main:

```
int main(void){

	char* nombre2 = "Ritchie";
	char* saludo2;

	string_concat_dynamic("Hola ", nombre2, &saludo2);

	printf("El saludo2 es: %s", saludo2);

	return 0;
}
```

Leimos toda la teria sobre punteros y manejo de memoria dinamica. Pero no podemos llegar a que saludo2 valga al menos la plb1 que vale "Hola "

**Comment by mgarciaisaia** [comment]
👋 ¡Hola!

Si están lidiando con memoria dinámica y punteros, lo mejor que pueden hacer es enfocarse en qué hace cada una de sus líneas de código en términos de memoria y punteros. Es decir, para cada declaración e instrucción que tienen, piensen cuánta memoria, en qué posición y con qué valor están declarando/reservando/asignando/referenciando en cada cachito de código que tienen.

Por ejemplo, pensar que `char* punteroTemp;` declara una variable de tipo puntero, por lo que `punteroTemp` es una variable de 4 bytes que guarda una dirección, y que, al menos con esa declaración únicamente, no tiene ningún valor en particular ("no está inicializada", "tiene basura", "apunta a cualquier lado").

Piensen y definan eso para cada uno de los valores, y, después, aprovechen las herramientas que tienen: en Eclipse pueden ver los tipos y direcciones de cada variable declarada usando el Debugger, en la View de `Memory` casi seguro (¿o era `Variables`?).

Si quieren no depender del IDE, pueden abusar de `printf`, imprimiendo la dirección de memoria de una variable (`printf("dir mi_variable: %p\n", &mi_variable)`), su contenido (ahí tienen que ver ustedes el tipo de la variable para ver cómo imprimirlo), su tamaño, y, si es un puntero, ver qué valor tiene la cosa apuntada.


Prueben esas cosas, repasen el material que leyeron, traten de encontrar qué había diferente entre lo que habían entendido y lo que sucede, y vuelvan a iterar todo el proceso desde el principio.

Cuando estén un poco más cómodos, vuelvan a intentar escribir esta función. Y, si sigue sin andar y no se les ocurre cómo seguir, pasen la nueva versión de la función, cuenten más detalladamente por qué es que pusieron cada cosa (es decir, qué esperan ustedes que aporte cada una de las declaraciones e instrucciones que escriben a la resolución total del problema), y con eso tratamos de identificar mejor la diferencia entre expectativa y realidad, y vemos cómo colaborarles para fijar mejor las ideas.
