### ISSUE TITLE
Existe alguna manera de que la VM me ande mejor?

### ISSUE THREAD

**Issue by Nachiten** [sisoputnfrba/foro#1599]
A mi se me rompió la PC original de escritorio que tengo.... no anda el CPU D: Por obvias razones no puedo reponer el hardware que se rompió por ahora.

Bueno, básicamente estoy usando una notebook la única que tengo que tiene lo siguiente:

CPU: Intel Core i3-3120M
RAM: 6GB (no se exactamente cual)
GPU: No tiene :(

Existe alguna manera de que la VM me ocupe menos en mi sistema para que no me ande tan extremadamente lenta?

Soluciones que se me ocurrieron:
1) Usar el explorador de internet mas liviano posible tanto dentro como fuera de la VM. (no se cual sería)
2) Bajarle la resolución para que no ocupe todo mi monitor de 1080p.
3) Asignarle mas RAM a la VM. (tiene puesta 1gb)

Acepto cualquier otro consejo u idea que me puedan ayudar...

Muchas gracias :D

**Comment by gastoncastineira** [comment]
Definí "lenta"

La VM con 1GB de RAM anda perfecta. A priori lo que se me ocurre es que "lenta" sea falta de movimiento fluido e impacto inmediato cuando moves el cursor o escribís algo con el teclado. Eso no tiene que ver con la RAM ni con el SO host, sino con la cantidad de GRAM (Graphic RAM) que le pongas, porque el mambo viene porque eso lo tiene que renderizar para que te lo muestre y si tiene pocos megas puestos va a ir lento. Por más que no tengas GPU instalada, ALGO tiene que tener porque sino no tendrías imagen en el monitor :P 

Probá metiéndole un par de megas de video más desde la opción de pantalla y contanos qué onda. Yo tengo 16MB y me anda decente. Tené en cuenta que si la GPU nativa que tenga tu mother es medio medio, sí puede llegar a levantar bastante temperatura porque básicamente tiene que renderizar tu SO host y la VM, así que llegados al caso tratá de buscar el equilibrio entre lo que le puedas destinar y lo que tu máquina permita

**Comment by FranciscoDumont** [comment]
Hola @Nachiten yo estoy usando una maquina peor que la tuya, a la vm le cambie el window manager por uno llamado "i3wm" y con eso me anda muchisimo mejor. Fijate si esta solución te sirve. Te dejo el video con el que arranqué [https://www.youtube.com/watch?v=j1I63wGcvU4](url)
Suerte !

**Comment by mgarciaisaia** [comment]
Fijate de asignarle (si podés/tenés) más de un procesador en la pestaña de System > Processor.

Y usar una resolución no tan gigante también ayuda.

Si tu pantalla es de alta densidad (Retina o esas cosas), quizá en `View -> Virtual Screen 1` (en la ventana de la VM, no en la general de VirtualBox) tengas una opción de `Scale to 200% (autoscaled output)` o algo así, para que la VM no se te vea chiquitísima, pero que tampoco le suba infinito la resolución.

**Comment by Nachiten** [comment]
> Definí "lenta"
> 
> La VM con 1GB de RAM anda perfecta. A priori lo que se me ocurre es que "lenta" sea falta de movimiento fluido e impacto inmediato cuando moves el cursor o escribís algo con el teclado. Eso no tiene que ver con la RAM ni con el SO host, sino con la cantidad de GRAM (Graphic RAM) que le pongas, porque el mambo viene porque eso lo tiene que renderizar para que te lo muestre y si tiene pocos megas puestos va a ir lento. Por más que no tengas GPU instalada, ALGO tiene que tener porque sino no tendrías imagen en el monitor :P
> 
> Probá metiéndole un par de megas de video más desde la opción de pantalla y contanos qué onda. Yo tengo 16MB y me anda decente (pero ojo, porque 16MB de una GPU externa son mejores que los de una onboard de mother por chimichurris de eléctrónica que le meten). Tené en cuenta que si la GPU nativa que tenga tu mother es medio medio, sí puede llegar a levantar bastante temperatura porque básicamente tiene que renderizar tu SO host y la VM, así que llegados al caso tratá de buscar el equilibrio entre lo que le puedas destinar y lo que tu máquina permita

Según el hardware que yo tengo la verdad no se cuanto le podria asignar de Vram sin que explote o recaliente demasiado.... en vez de 16mb a cuanto deberia subirlo?

**Comment by Nachiten** [comment]
> Fijate de asignarle (si podés/tenés) más de un procesador en la pestaña de System > Processor.
> 
> Y usar una resolución no tan gigante también ayuda.
> 
> Si tu pantalla es de alta densidad (Retina o esas cosas), quizá en `View -> Virtual Screen 1` (en la ventana de la VM, no en la general de VirtualBox) tengas una opción de `Scale to 200% (autoscaled output)` o algo así, para que la VM no se te vea chiquitísima, pero que tampoco le suba infinito la resolución.

Voy a probar eso... tiene solo 2 nucleos este CPU

**Comment by iago64** [comment]
@Nachiten generalmente los problema de que la VM anda como "en fotos" es porque no te da la memoria de video, eso por suerte podes subirlo al mango (que es 128Mb).
Sobre el tema de calentar o demas, no te preocupes, en su momento yo corria la VM con 512mb de ram y 128 de video en una lenovo con un pentium dual core y 2gb de ram. 
Lo importante es que la VM crea que tiene el disponible, ademas no vas a ponerte a correr el crysis full graficos en la vm, simplemente vas a abrir un eclipse / vs code y un par de terminales 😉

**Comment by Nachiten** [comment]
> @Nachiten generalmente los problema de que la VM anda como "en fotos" es porque no te da la memoria de video, eso por suerte podes subirlo al mango (que es 128Mb).
> Sobre el tema de calentar o demas, no te preocupes, en su momento yo corria la VM con 512mb de ram y 128 de video en una lenovo con un pentium dual core y 2gb de ram.
> Lo importante es que la VM crea que tiene el disponible, ademas no vas a ponerte a correr el crysis full graficos en la vm, simplemente vas a abrir un eclipse / vs code y un par de terminales 😉

Bueno. Quiero avisar que ya le puse 64mb de video solamente y no 128. Esto genera un cambio notorio de respuesta de las cosas que toco en la vm sin basicamente realentizarme toda la pc host. Si lo subo a 128 (supongo) va a hacer demasiado lenta mi pc o exigir demasiado al CPU.

Gracias por los consejos cierro esto.
