### ISSUE TITLE
Problemas con la Maquina Virtual

### ISSUE THREAD

**Issue by Sol-gomez** [sisoputnfrba/foro#1600]
Hola gente! Me instale VirtualBox y los archivos de lubuntu como aparecia en la pag. Al levantarlo con la mv me tira este error:

VMMR0_DO_NEM_INIT_VM failed: VERR_NEM_MISSING_KERNEL_API (VERR_NEM_MISSING_KERNEL_API).
VT-x is not available (VERR_VMX_NO_VMX)

Result Code: | E_FAIL (0x80004005)
-- | --
Component: | ConsoleWrap
Interface: | IConsole {872da645-4a9b-1727-bee2-5585105b9eed}

vi que otros compañer@s tuvieron problemas similares con la maquina virtual. Busque este error en google y segui algunos pasos, como fijarme en la bios que este activada la virtualizacion, y desactivar el archivo HyperV. Peero sigue tirandome el mismo error. 
¿Podrian ayudarme con este error?? otro dato que les puede resultar mi computadora es una dell latitude 5400 ( tengo windows 10 pro, 256gb de disco,procesador intel i5 8va generacion, 8ram).

Muchas Gracias, espero comentarios !!! 
Saludos
Sol

**Comment by gastoncastineira** [comment]
Si tenés la virtualización prendida en la BIOS y desactivaste todo lo relacionado a Hyper-V, entonces lo que te recomiendo es que te descargues una versión más vieja de VBox. Estoy viendo en sus foros muchos problemas con Windows 10 y windows defender desde la versión de diciembre mientras busco tu error.
Probá con la 5.2 o 5.4, que son las que usamos en ambos cuatrimestres el año pasado y está checkeado que andan.

Contanos qué onda después

**Comment by Sol-gomez** [comment]
Ya instale la version 5.2 pero aun asi me tira este error!! y tengo la virtualizacion activada y el HyperV desactivado, nose si tendre q activar o desactivar algo mas!! estuve mirando en google que por lo general hacen esto y listo. 
Se les ocurre otra cosa?.
Muchas Gracias,
Saludos
Sol


![errorVm](https://user-images.githubusercontent.com/48770634/78099570-afde9c80-73b8-11ea-8519-e376f1af42a2.jpg)

**Comment by gastoncastineira** [comment]
Mmmm, pero el error cambió o me parece a mí? Eso sería un avance

Fijate si lo que dicen [acá](https://stackoverflow.com/questions/50053255/virtualbox-raw-mode-is-unavailable-courtesy-of-hyper-v-windows-10) te sirve. Las dos primeras respuestas junto con sus comentarios

**Comment by mgarciaisaia** [comment]
Es el error que la buena de @pyritewolf había mencionado en sisoputnfrba/issues#55. Lo que no tengo en claro es por qué, si tenés HyperV deshabilitado ahí, te seguiría estando prendido 🤔

¿Usás Hyper-V para algo que sepas, o simplemente _estaba ahí_?

**Comment by Sol-gomez** [comment]
@gastoncastineira  si,cambio el error!!! algo es algo jajaja 

@mgarciaisaia yo tmpoco entiendo bien, pero cuando desactive el hyperV me tiro error Docker!!, puede ser por eso?. (Tipo estoy usando la compu del laburo!! pq la mia personal se le rompio el disco hace poquito D:) Decis q tengo q desabilitar de alguna forma esa app tmb? .

Desde ya muchas gracias!!
Saludos.

**Comment by mgarciaisaia** [comment]
Ahí va la cosa: Docker en Windows usa Hyper-V.

[En este thread](https://forums.docker.com/t/running-docker-and-virtualbox-on-the-same-machine/23578) hablan de esto. Dicen que Docker en Windows usa Hyper-V para hacerlo lo más nativo posible, y que, sí: eso significa que no podés tener VirtualBox en paralelo.

Las opciones que ofrecen son cambiar Docker por Docker Toolbox (parece que es el mismo Docker, pero corriendo en una VM de VirtualBox en vez de una de Hyper-V), o, buen - que levantes las VMs nuestras con Hyper-V (sigo con la misma ignorancia que antes sobre si tiene algún front-end o cómo es que se usa Hyper-V).

Fijate si podés convertir el disco al formato que usa Hyper-V [como dice en este tuto](https://metalop.com/2015/12/07/converting-virtualbox-vdi-diskfiles-to-hyper-v-vhd-files/). _Quizá_ esa parte del funcionamiento de VirtualBox la puedas hacer, incluso teniendo este problema de no poder virtualizar.

Si eso funciona, tratá de levantar ese disco con Hyper-V y ver si anda. Ahí ganaste.

Si no, trato de armarte un disco desde acá y probamos.

Contanos cómo sigue :)

**Comment by afilgueira** [comment]
@Sol-gomez sirvío esto que te contaba Mati? Pudiste resolverlo?
