### ISSUE TITLE
link lubuntu dañado [PROBLEMA]

### ISSUE THREAD

**Issue by MariaTrinidad** [sisoputnfrba/foro#1601]
Hola, buen día, quería consultar porque hay un link de lubuntu que no puedo extraer, lo descargo y siempre que lo intento extraer esta dañado.
Probé con varios navegadores pero en todos me da el mismo resultado, también probé descargarlo desde el celular y extraerlo con otro programa pero me da el mismo error. 
El link en cuestion es el primero " utnso-lubuntu-5.0.1.7z.001 ", con los demás links  pude extraer todo perfecto. 
¿Que puedo hacer para solucionarlo?

**Comment by iago64** [comment]
Buenas! como va?

Las VMs (Tanto lubuntu o ubuntu server) estan divididas en partes, lo que tenes que hacer es tener todas las partes en la misma carpeta y ahi extraerlas, eso te va a generar un archivo 7z (si no me falla la memoria) que vas a tener que volver a extraer para por fin tener el archivo vdi (o Virtual Disk Image) que es el que vas a poder abrir con Virtual Box.

Saludos.-

**Comment by MariaTrinidad** [comment]
Hay un unico archivo que no me deja abrir


<img width="957" alt="CapturaPagMvs" src="https://user-images.githubusercontent.com/36057941/78304921-22b15a00-7516-11ea-9a17-62d3feec9fc9.PNG">
<img width="745" alt="vms" src="https://user-images.githubusercontent.com/36057941/78304926-2644e100-7516-11ea-8ea3-4d226852d657.PNG">
<img width="490" alt="extraer" src="https://user-images.githubusercontent.com/36057941/78304934-2a70fe80-7516-11ea-8bc8-e2db0bce8a1d.PNG">
<img width="725" alt="resultado" src="https://user-images.githubusercontent.com/36057941/78304944-3066df80-7516-11ea-83bf-5c6cd877a2c5.PNG">
<img width="567" alt="intentoabrir" src="https://user-images.githubusercontent.com/36057941/78304963-3957b100-7516-11ea-891d-161629206b24.PNG">
<img width="714" alt="CapturaResultado" src="https://user-images.githubusercontent.com/36057941/78304986-4379af80-7516-11ea-8bc0-10697960f250.PNG">

**Comment by mgarciaisaia** [comment]
¡Ahhh, ahí está la cosa!

Fijate que el nombre del archivo que intentás descomprimir termina con ` (2)`. Seguramente sea porque en los reintentos de bajarlo, el browser le puso ese nombre para que no sobreescriba una descarga previa de ese mismo archivo.

El tema es que tu WinRar está intentando buscar la parte 2 del archivo (el que termina con `.002`) basándose en el nombre de este - es decir, busca el `utnso-lubuntu-5.0.1.7z (2).002`, pero lo que vos descargaste se llama `utnso-lubuntu-5.0.1.7z.002`.

Borraale el ` (2)` a tu archivo original, y debería funcionar.

**Comment by MariaTrinidad** [comment]
ahi funciono, graciasss!
