### ISSUE TITLE
Problema con la pagina de consignas 

### ISSUE THREAD

**Issue by victoriagarciaa** [sisoputnfrba/foro#1603]
Hola!
Queria consultar sobre la pagina donde estan las consignas de los ejercicio porque no se me esta cargando. El link es http://faq.utnso.com/ejercicios 
A todos les pasa igual?
Saludos

**Comment by ncoen97** [comment]
Buenas!
La pagina es http://faq.utnso.com.ar/ejercicios, ese link de donde lo sacaste?
Así lo actualizamos con el .com.ar

**Comment by victoriagarciaa** [comment]
Ahi esta! Muchas gracias! El link lo saque de aca: https://github.com/sisoputnfrba/so-exercises

**Comment by mgarciaisaia** [comment]
Gracias por el aviso, [ahí lo corregí](https://github.com/sisoputnfrba/so-exercises/commit/9b8d7cfd656a6ff8fc7576155c4508ab18e75055) :)
