### ISSUE TITLE
Problemas con Eclipse y las commons en la VM

### ISSUE THREAD

**Issue by jcastagno99** [sisoputnfrba/foro#1604]
Buenas! estuve siguiendo los tutoriales para instalar la VM (todo ok) las guest additions (funciona todo) y las commons (he aquí el problema)

Sigue el vídeo paso a paso, metí las commons y hasta ahi va todo bien.
El problema surge que cuando creo un proyecto en C/C++ (el típico hello world) este compila sin ningun error, pero cuando lo voy a ejecutar salta el siguiente error : "Launch failed. Binary not found"
![8c22b30f-8781-4159-9ac6-c48d221b43dd](https://user-images.githubusercontent.com/49038828/78391763-6317e300-75bd-11ea-8bc6-1f73ed3d9fc3.jpg)

Para esto busque soluciones en foros de Eclipse y en StackOverflow lo pude solucionar cambiando la configuración del "run" modificando el archivo al que apunta el proyecto, tenia como ruta predeterminada : Debug/nombreDelProyecto.
Lo cambie por : Home/utnso/workspace/nombreDelProyecto/Debug/(ejecutable con nombre del proyecto)
![8eb4221b-389d-4eb8-8b12-48343acfbef9](https://user-images.githubusercontent.com/49038828/78392235-462fdf80-75be-11ea-8b72-b6e9c1fc5c15.jpg)

Con eso, el "hello world" funcionaba perfectamente.

Ahora, cuando seguí con el tutorial, al poner la referencia de las commons en las propiedades del proyecto 
![0e191c6e-d797-42f5-8f98-8a77c5354a1b](https://user-images.githubusercontent.com/49038828/78392606-e5ed6d80-75be-11ea-9bc9-0b8cfd385a93.jpg)

y al usar una función de la librería temporal.h, compila todo perfecto, pero cuando lo quiero ejecutar pasa lo siguiente : 
![c5bb036d-ec12-4b58-873b-a7be503b9d13](https://user-images.githubusercontent.com/49038828/78392741-1df4b080-75bf-11ea-86b9-b98a6bd4fef0.jpg)

Me dice que el archivo no existe, cuando voy al directorio que habia configurado para solucionar el error anterior el archivo ejecutable que tiene el nombre del proyecto se borró y no tengo forma de hacer que esto funcione.

No se si es por la solución que implemente al principio o es otro error, tambien probe con otras soluciones para el primer problema que tuve como seleccionar otros parsers binarios en las opciones de C/C++ Build pero no funciono.

Perdon si fue mucha explicación pero queria que quede detallado el paso a paso que hice por si el problema viene de algo que hice al principio.

**Comment by mesaglio** [comment]
El primer fix, no deberias que tener que hacer. Eclipse deberia resolver internamente la referencia donde esta el proyecto.

Por lo que veo en la primer foto, en el nombre del archivo tenes un (*), lo que quiere decir que el archivo no esta guardado.

**Comment by jcastagno99** [comment]
Aun guardando el archivo, si no toco nada del directorio del proyecto, sigo teniendo el problema que se ve en la primer foto "Launched Failed: Binary not found" o sea que puedo compilar pero no levantarlo

**Comment by mesaglio** [comment]
Estuvimos un tiempo en discord y lo solucionamos modificando la build configuration (Foto 2)
Select Automatically por Use Active.

Me mostro el video de las commons que vio para instalaras, el cual era la version vieja. Les recuedo que el video de instalacion de commons, creacion de proyectos e importacion del mismo es el siguiente. https://www.youtube.com/watch?v=Q8wfpu38PMc&t=3s
