### ISSUE TITLE
[Aporte] Como configurar la shared folder (carpeta compartida)

### ISSUE THREAD

**Issue by Nachiten** [sisoputnfrba/foro#1605]
Resulta que yo no pude hacer andar la carpeta compartida con el tutorial otorgado por la cátedra. Razón por la cual escribo esto especificando lo que pude hacer que si funcionó para tenerla.

La carpeta compartida es una carpeta que es accesible tanto de la maquina Host como de la VM y se puede leer/escribir de ambas los mismos archivos. Bastante útil a mi parecer. 

### **Pasos para crear la carpeta:**
1. Abrir **VirtualBox** (Sin tener la VM abierta).
2. Click Derecho sobre la VM (Lubuntu) y clickear **Configuracion...**
3. Ir a la seccion **Carpetas compartidas**
4. Clickear la carpeta azul con un simbolo de **+ Verde**.
5. Especificar lo siguiente:
- _Ruta carpeta:_ La ruta que deseen (de la maquina host) que será la carpeta a compartir con la VM
- _Nombre de carpeta:_ Dejar TAL CUAL: **shared** (caso contrario los comandos explicitados posteriormente deberás modificarlos para coincidir con ese nombre)
- Desmarcar tanto _Sólo lectura_ como _Automontar_.
- Si aparece un CheckBox llamado "Dejar Permanente" NO clickearlo. Esto lo configuraremos mas adelante desde adentro de la VM.
Imagen de [como deberia verse la ventana](https://i.imgur.com/wYTrDcV.png).
6. Clickear aceptar a todas las ventanas y ejecutar la VM.
7. Asegurarse de tener las **Guest Additions** correspondientes a tu versión de **OracleVM VirtualBox** correctamente instaladas.
--- Apartir de ahora hay que abrir una terminal (Cntrl + Shift + T) y empezar a tirar los siguientes comandos: ---
8. Crear la carpeta shared en el directorio /home/utnso de la VM:
`mkdir ~/shared`
9. Montar la carpeta para que sea compartida:
`sudo mount -t vboxsf shared ~/shared`
10. Para configurar grupo personalizado usuario id owner:
`sudo mount -t vboxsf -o  uid=1000,gid=1000 shared ~/shared`
--- La carpeta ahora deberia ser accesible desde la VM con `cd ~/shared` ---

### **Importante: Como hacer la carpeta permanente**
1. Editar archivo `fstab`  en directorio `/etc` **| Leer mas abajo como usar el editor de la consola |**
`sudo nano /etc/fstab`
2. Agregar la siguiente linea en una nueva linea abajo de la ultima en el archivo:
`shared  /home/utnso/shared vboxsf  defaults    0   0`
3. Editar este otro archivo (luego de haber cerrado y guardado el anterior)
`sudo nano /etc/modules`
4. Agregar este texto idem el anterior archivo:
`vboxsf`
5. Asegurarse de guardar el archivo antes de salir.
6. Reiniciar la VM con el siguiente comando:
`shutdown -r now`

Por ultimo cuando la VM encienda deberían poder tirar un `ls` y ver a la carpeta con un color verde. Eso significa que funcionó :D Ahora tienen una carpeta que es accesible tanto de la VM como de la maquina host. Se debería ver [de esta manera](https://i.imgur.com/ohnSdGx.png).

**Aclaraciones importantes sobre este editor feo usado para editar los archivos en la VM:**
- Desplazarse por el archivo es tan simple como usar las flechas del teclado.
- Para insertar las nuevas lineas explicitadas arriba debes pararte en la linea SIGUIENTE a la ultima linea del archivo. Esto quiere decir escribir sobre una nueva linea vacía [tal como se ve acá](https://i.imgur.com/ohnSdGx.png).
- Para salir del archivo tocar `Cntrl + X`.
- Luego de hacer lo anterior debes escribir `Y (mayuscula, no minuscula)` para decirle de guardar los cambios que hiciste.
- Luego te preguntará donde guardarlo y solo tocar `Enter` para elegir la misma ubicación donde estabas editando.

**NOTA:** Mis compañeros de grupo y yo hicimos estos pasos con la versión *6.0.18* de Oracle VM VirtualBox y la misma versión de las Guest Adittions. Si llegan a tener algún problema con este tutorial por favor aclarar que versión están usando que eso podría llegar a hacer una diferencia.
**NOTA 2:** El 99% de estos pasos son traducciones de [esta pagina](http://devnotes.geega.net/note.php?note=mount-shared-directory-virtual-box) mas aclaraciones que yo hago de precisamente como lo hice.

**Comment by tferraro** [comment]
Che, re bueno esto!  ~Seguro~ Posiblemente, lo vamos a volver un docu por si en el foro se pierde 😁

**Comment by Nachiten** [comment]
> Che, re bueno esto!  ~Seguro~ Posiblemente, lo vamos a volver un docu por si en el foro se pierde 😁

Dale buenisimo, gracias :D

**Comment by Nachiten** [comment]
@tferraro Link al issue con text formatting y todo para que lo copien mas facil:

https://pastebin.com/E0U2i0tv

**Comment by francofresno** [comment]
Hola, gracias por el tutorial.
Tengo un problema. Al montar (paso 8 en la creación de carpeta) me tira este error:
`/sbin/mount.vboxsf: mounting failed with the error: No such device`

Tengo instaladas las guest additions. Estuve googleando antes de preguntar pero no encontré ninguna solución que me funcione. Seguí todos los pasos tal cual.

**Comment by Nachiten** [comment]
> Hola, gracias por el tutorial.
> Tengo un problema. Al montar (paso 8 en la creación de carpeta) me tira este error:
> `/sbin/mount.vboxsf: mounting failed with the error: No such device`
> 
> Tengo instaladas las guest additions. Estuve googleando antes de preguntar pero no encontré ninguna solución que me funcione. Seguí todos los pasos tal cual.
> 
> **Edit:** tampoco puedo utilizar el cortapapeles, quizás esté relacionado.
> 
> **Edit 2:**
> **Solución:** al parecer en la versión 6.0.18 tanto de VirtualBox como de Gust Additions funciona bien. Por alguna razón no anda en la mas actual. Así que si tienen el mismo problema, instalen esa versión que ahí funciona bien.

Efectivamente yo hice esto con la version 6.0.18. La cual tiene 0 problema con el tema de portapapeles compartido. Esa fue la razon por la que la instalé.

**Comment by enogueiras** [comment]
El shutdown -r now me rompio la VM :(

**Comment by mgarciaisaia** [comment]
@enogueiras `shutdown -r` _reinicia_ la VM.

Si se te rompió algo, vas a tener que contarnos un poco más, porque no era esperado.

**Comment by enogueiras** [comment]
> @enogueiras `shutdown -r` _reinicia_ la VM.
> 
> Si se te rompió algo, vas a tener que contarnos un poco más, porque no era esperado.

al reiniciar no booteaba y obtuve un mensaje así:

![jFxw6](https://user-images.githubusercontent.com/11813141/79586895-257c8500-80a8-11ea-96da-e1f16120d453.png)

Probé algunas cosas y como no lo pude solucionar, reinstale la VM.

**Comment by Pedro-Dalvit** [comment]
Me paso lo mismo que a @enogueiras. Alguna solución en ese caso?

**Comment by Nachiten** [comment]
> Me paso lo mismo que a @enogueiras. Alguna solución en ese caso?

Yo seguramente se lo mismo que vos sobre ese error (no mucho). Te recomiendo le preguntes a algún ayudante o reinstales la VM en caso de que hayas hecho algo raro previamente para que rompa.

Creo entender según lo que dijo que @enogueiras lo solucionó de esa manera... Reinstalando la VM.

Yo hice este procedimiento yo mismo y con los 6 compañeros en total que fueron pasando por mi grupo y nunca tuvimos ningún problema. Todos ellos usando la misma version que tengo yo de OracleVM.

Lo ultimo que te pregunto @Pedro-Dalvit es que me digas que versión de Oracle VM estas usando. Quizá eso genera problemas. Por eso yo me moví a una versión anterior (6.0.18) porque la versión 6.1 me fallaba y no me andaba el shared clipboard.

**Comment by jqnsantosr** [comment]
Buenas, me pasa lo mismo. Logro ingresar a cd ~/shared y ver los archivos, pero luego del shutdown -r se me rompe la VM. La versión del Virtual Box es 6.0.24 r139119.

**Comment by Nachiten** [comment]
> Buenas, me pasa lo mismo. Logro ingresar a cd ~/shared y ver los archivos, pero luego del shutdown -r se me rompe la VM. La versión del Virtual Box es 6.0.24 r139119.

Buenas! No sé bien que será ese problema y si no será causado por otra cosa.

Lo maximo que te puedo decir es que yo lo hice con oracleVM version 6.0.18 y me anda perfecto.

**Comment by mgarciaisaia** [comment]
@jqnsantosr algún otro problema habíamos detectado el cuatri pasado que sucedía con versiones de VirtualBox posteriores a la 6.0.18. Fijate si eso te "soluciona" el problema.

**Comment by jqnsantosr** [comment]
@mgarciaisaia @Nachiten me instalé la 6.0.18 y me pasó lo mismo!

**Comment by mgarciaisaia** [comment]
Vamos a necesitar más datos, entonces. Un mensaje de error, una descripción más completa de lo que falla, algún log si llegaras a conseguir...

**Comment by jqnsantosr** [comment]
[LogsYError.zip](https://github.com/sisoputnfrba/foro/files/5106653/LogsYError.zip)
Adjunto lo que pude sacar. Está la imagen del error por consola al intentar reiniciar, y los logs de la vm.
Gracias!

**Comment by RaniAgus** [comment]
@Nachiten Una última cosa que se puede agregar: si en el guest hay problemas con los permisos al estilo `mkdir: cannot create directory ‘build’: Permission denied`, hay hacer como dice [acá](https://stackoverflow.com/a/28459731/14089741):
```
$ sudo adduser utnso vboxsf
```
