### ISSUE TITLE
Problema Memory Leak

### ISSUE THREAD

**Issue by NicoMadd** [sisoputnfrba/foro#1606]
Buenas, estoy teniendo problemas con un codigo al tratar de resolver una correccion de memoria con el valgrind. El problema que tengo es que no encuentro como solucionar el leak que me marca valgrind. Adjunto imagenes con las funciones para inicializar y destruir las estructuras. No se me ocurre que hacer, hay algo que no debo estar viendo.

---------------------------------------------------------------------------------------------------------------
![1](https://user-images.githubusercontent.com/49067443/78416876-d0019c00-7602-11ea-915f-2672fc8c94c0.png)
---------------------------------------------------------------------------------------------------------------
![2](https://user-images.githubusercontent.com/49067443/78416877-d42db980-7602-11ea-9d29-ef83d10154be.png)

**Comment by mgarciaisaia** [comment]
👋 ¡Hola!

No posteamos screenshots :)

Si posteamos un screenshot, quien lee el issue y quiere colaborar tiene que tomarse el laburo de interpretar la imagen y copiar _a mano_ las porciones de texto relevantes. Eso hace que una buena parte de la gente predispuesta a ayudar termine no haciéndolo (por fiaca, o por no tener el rato). Así que, nada - no posteemos screenshots :). Mejor copiar y pegar los cachos de código relevantes + los mensajes de error que den las herramientas. Puntos extra si copiás la salida de consola en vez de la de una ventana gráfica - porque suele tener muuuucha más info.

Tan relevante es esto de no postear screenshots, que hace un tiempo grabé un video al respecto: https://faq.utnso.com.ar/errores-eclipse

Respecto a Valgrind, tenemos un documento _re sarpado_ que escribieron los chicos hace un tiempo explicando cómo usar `valgrind`, y cómo interpretar qué quieren decir sus distintos mensajes de error. Podés leerlo acá: https://faq.utnso.com.ar/valgrind

Pegale una revisada a eso, y, sumado a lo otro, fijate si se entiende mejor la situación. Después contanos qué más entendiste, y vemos cómo seguir :)

Un abrazo, o un codo, o coso.

**Comment by NicoMadd** [comment]
Dale, disculpa, mala mía. Sisi, el documento de Valgrind lo leí, y también vi la charla que esta en el canal de la cátedra. Lo que entiendo hasta ahora es que a los punteros, en este caso char*, le tengo que asignar con malloc el espacio necesario en el heap para usarlo. Y después una vez que termina el programa liberar el o los punteros que use. Aun así, a lo que entendí hasta ahora como hacerlo, no estaría funcionando. Estuve investigando también en el manual de usuario de Valgrind, y me dice que use delete pero probé y tampoco funca. Valgrind tira que quedan 2000 bytes en still reachable, yo me puse a ver si podía arreglarlo, tengo que preocuparme? pregunto porque en la charla de Valgrind creo que menciona que no le demos bola a eso.

Antes no pase el reporte de Valgrind porque no me dejaba usarlo en la consola. Me tiraba permiso denegado, pero lo arregle con esto **_chmod a+x./file_**

Probé con varias cosas pero me quede sin ideas, por eso acudo acá que son los expertos jaja, abrazo y gracias! 

Dejo el codigo relevante aca:
```
#include <stdio.h>
#include <stdlib.h>
#include <commons/string.h>
#include <commons/collections/list.h>


typedef struct {
	char* Region;
	char* NomYApe;
	int Edad;
	int NroTel;
	int DNI;
	int saldo;
}t_usuario;

t_usuario* linea_a_usuario(char* linea){
	char** ls = string_split(linea, ";"); //ls = linea spliteada

	t_usuario* usuario = malloc(sizeof(t_usuario));
	usuario->Region = malloc(strlen(ls[0])+1);
	usuario->NomYApe = malloc(31);
	strcpy(usuario->Region,ls[0]);
	strcpy(usuario->NomYApe,ls[1]);
	usuario->Edad=atoi(ls[2]);
	usuario->NroTel=atoi(ls[3]);
	usuario->DNI=atoi(ls[4]);
	usuario->saldo=atoi(ls[5]);
	free(ls[0]);
	free(ls[1]);
	free(ls[2]);
	free(ls[3]);
	free(ls[4]);
	free(ls[5]);
	free(ls[6]);
	free(ls);
	return usuario;};

void eliminar_usuario(t_usuario* usuario){
	free(usuario->Region);
	free(usuario->NomYApe);
	free(usuario);
};

int main(void) {

	FILE* archivo=fopen("src/Personas.txt", "r+");
	t_list* lista_usuarios = archivo_a_lista(archivo);
	print_lista(lista_usuarios);

	t_list* lista_filtrada = list_filter(lista_usuarios, mayor_de_edad);

	ordenar_lista(lista_filtrada);

	//t_list* lista_final = list_filter(lista_filtrada, _saldo_menor_a_100);

	puts("------------------------------------");
	print_lista(lista_filtrada);

	//list_destroy_and_destroy_elements(lista_final, eliminar_usuario);
	list_destroy_and_destroy_elements(lista_filtrada, eliminar_usuario);
	list_destroy_and_destroy_elements(lista_usuarios, eliminar_usuario);

	fclose(archivo);
	puts("\nFIN");
	return EXIT_SUCCESS;
};
```
y lo que tira valgrind :
```
==7619== Memcheck, a memory error detector
==7619== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==7619== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==7619== Command: src/Ej3.c
==7619== 
src/Ej3.c: 1: src/Ej3.c: /VBox.log: Permission denied
==7620== 
==7620== HEAP SUMMARY:
==7620==     in use at exit: 2,013 bytes in 88 blocks
==7620==   total heap usage: 93 allocs, 5 frees, 37,881 bytes allocated
==7620== 
==7620== LEAK SUMMARY:
==7620==    definitely lost: 0 bytes in 0 blocks
==7620==    indirectly lost: 0 bytes in 0 blocks
==7620==      possibly lost: 0 bytes in 0 blocks
==7620==    still reachable: 2,013 bytes in 88 blocks
==7620==         suppressed: 0 bytes in 0 blocks
==7620== Reachable blocks (those to which a pointer was found) are not shown.
==7620== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==7620== 
==7620== For counts of detected and suppressed errors, rerun with: -v
==7620== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
src/Ej3.c: 2: src/Ej3.c: ============================================================================: not found
src/Ej3.c: 3: src/Ej3.c: Name: not found
src/Ej3.c: 4: src/Ej3.c: Author: not found
src/Ej3.c: 5: src/Ej3.c: Version: not found
src/Ej3.c: 6: src/Ej3.c: Copyright: not found
src/Ej3.c: 7: src/Ej3.c: Description: not found
src/Ej3.c: 8: src/Ej3.c: ============================================================================: not found
src/Ej3.c: 9: src/Ej3.c: Debug/: Permission denied
==7621== 
==7621== HEAP SUMMARY:
==7621==     in use at exit: 1,505 bytes in 87 blocks
==7621==   total heap usage: 117 allocs, 30 frees, 79,901 bytes allocated
==7621== 
==7621== LEAK SUMMARY:
==7621==    definitely lost: 0 bytes in 0 blocks
==7621==    indirectly lost: 0 bytes in 0 blocks
==7621==      possibly lost: 0 bytes in 0 blocks
==7621==    still reachable: 1,505 bytes in 87 blocks
==7621==         suppressed: 0 bytes in 0 blocks
==7621== Reachable blocks (those to which a pointer was found) are not shown.
==7621== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==7621== 
==7621== For counts of detected and suppressed errors, rerun with: -v
==7621== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
src/Ej3.c: 14: src/Ej3.c: Syntax error: "(" unexpected
==7619== 
==7619== HEAP SUMMARY:
==7619==     in use at exit: 1,505 bytes in 87 blocks
==7619==   total heap usage: 117 allocs, 30 frees, 79,901 bytes allocated
==7619== 
==7619== LEAK SUMMARY:
==7619==    definitely lost: 0 bytes in 0 blocks
==7619==    indirectly lost: 0 bytes in 0 blocks
==7619==      possibly lost: 0 bytes in 0 blocks
==7619==    still reachable: 1,505 bytes in 87 blocks
==7619==         suppressed: 0 bytes in 0 blocks
==7619== Reachable blocks (those to which a pointer was found) are not shown.
==7619== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==7619== 
==7619== For counts of detected and suppressed errors, rerun with: -v
==7619== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Comment by ncoen97** [comment]
Buenas!
Los still reachable cuentan los bytes/bloques de memoria reservada que todavía esta accesible. El sistema operativo se ocupa de liberar todos los recursos tomados, así que mientras no tengas definitely lost ni indirectly lost no hagas problema.
Saludos.

**Comment by NicoMadd** [comment]
Genial Gracias!
