### ISSUE TITLE
Distribucion Sugerida - Delibird

### ISSUE THREAD

**Issue by eGoicoechea** [sisoputnfrba/foro#1607]
Hola! 
Con mi grupo leímos la consigna del nuevo TP Delibird y queríamos consultarles alguna distribución que nos recomienden con respecto a la cantidad de integrantes del grupo y los modulos. 
Cuatrimestres anteriores nos han recomendado la cantidad de integrantes que deberian ocuparse de cada modulo. 
Agradezco su respuesta.
Saludos. 
Emilia.

**Comment by tferraro** [comment]
👋 Alo!
Doy vuelta un poco la pregunta 😁, ¿Que distribución les parece correcta a ustedes como grupo?

**Comment by eGoicoechea** [comment]
Teniamos pensado hacer: 
2 personas que se encarguen del Proceso Team 
2 Personas para el Broker
1 Persona para el Game Card
Y todos hacer en conjunto el Game Boy.

**Comment by nahuemazzeo** [comment]
Hola!!

En grandes rasgos la distribución es correcta. Recuerden que esa distribución esta bien si las tareas dentro de cada modulo se distribuyen de manera equitativa. No sirve decir que dos personas hacen un modulo si el 80% de ese modulo lo hace la Persona A y el otro 20% la Persona B.

Dicho esto, capaz estaría bueno dejar de pensar esto de distribuir personas a partir de módulos y mejor distribuir personas a partir de tareas y funcionalidades. De esta ultima manera capaz todas las personas pueden participar en mas de un modulo para mejorar mas la comunicación y el nivel del trabajo practico (Como dije antes, esta es mi forma de verlo, pueden seguir la distribución que decidieron que a grandes rasgos es correcta).

Saludos.

**Comment by eGoicoechea** [comment]
Genial gracias!
