### ISSUE TITLE
Problema VM que no inicia.

### ISSUE THREAD

**Issue by Nachiten** [sisoputnfrba/foro#1609]
Basicamente la VM de Lubuntu de mi compañero no enciende y se queda congelada en esto
![Screen Error Erik](https://user-images.githubusercontent.com/39410888/78458470-fc133080-7687-11ea-8b4a-eb10560066fa.png)

No se bien que hacer y si existe algun log o algo que pueda pasar no tengo idea como obtenerlo.

Muchas gracias 👍

**Comment by mgarciaisaia** [comment]
Puff. ¿Qué le hacen a las VMs en ese grupo, viejo? 😛

Eso es un kernel panic. Es decir, hubo el equivalente a un segmentation fault _dentro del kernel_. Fiesta.

Es medio indicador de algún problema de drivers, o de la virtualización, o de _andá a saber qué cosa mucho muy mal configurada_. Pero es uno de esos problemas en que lo primero que querés dedicar un buen rato a considerar es - ¿vale la pena?

Ahí arriba hay un stacktrace. El kernel, al detectar el fallo, te imprime la lista de llamadas a funciones que fue haciendo hasta el momento en que detecto el fallo. Eso ayuda a la gente a poder debuggear, entender, reproducir y solucionar el problema. Con CTRL+SHIFT+Flecha Arriba creo que podés ver la página anterior de log. Pero, nada - de curioso, nomás. No creo que vayas a encontrar mucha solución a partir de ese log. Prueben, pero meh.


Si no tenían _muchísimo laburo_ metido en esa VM que no esté disponible en otro lado, lo más sencillo probablemente sea tirarla y arrancar de nuevo.

Pero traten de pensar, posta, qué cambio gede habrán metido recientemente que hizo que se rompa así. Para evitar que vuelva a pasar, digo.

Y, como consejazo, usen los snapshots de VirtualBox. Ni bien instalan la VM, hagan un snapshot, así _cuando la vuelvan a prender fuego_ pueden recuperarla rápido.

**Comment by Nachiten** [comment]
> Puff. ¿Qué le hacen a las VMs en ese grupo, viejo? 😛
> 
> Eso es un kernel panic. Es decir, hubo el equivalente a un segmentation fault _dentro del kernel_. Fiesta.
> 
> Es medio indicador de algún problema de drivers, o de la virtualización, o de _andá a saber qué cosa mucho muy mal configurada_. Pero es uno de esos problemas en que lo primero que querés dedicar un buen rato a considerar es - ¿vale la pena?
> 
> Ahí arriba hay un stacktrace. El kernel, al detectar el fallo, te imprime la lista de llamadas a funciones que fue haciendo hasta el momento en que detecto el fallo. Eso ayuda a la gente a poder debuggear, entender, reproducir y solucionar el problema. Con CTRL+SHIFT+Flecha Arriba creo que podés ver la página anterior de log. Pero, nada - de curioso, nomás. No creo que vayas a encontrar mucha solución a partir de ese log. Prueben, pero meh.
> 
> Si no tenían _muchísimo laburo_ metido en esa VM que no esté disponible en otro lado, lo más sencillo probablemente sea tirarla y arrancar de nuevo.
> 
> Pero traten de pensar, posta, qué cambio gede habrán metido recientemente que hizo que se rompa así. Para evitar que vuelva a pasar, digo.
> 
> Y, como consejazo, usen los snapshots de VirtualBox. Ni bien instalan la VM, hagan un snapshot, así _cuando la vuelvan a prender fuego_ pueden recuperarla rápido.

Primero y principal quiero aclarar que esa VM era una fresh install..... La habiamos acabado de borrar y volver a instalar... Tanto oracle VM virtualBox como la VM de lubuntu a la cual le chequeamos todos los hashes md5 tanto de la version comprimida como descomprimida.

Por lo tanto me parece practicamente imposible que sea uno de esos "bugs temporales" ya que literalmente no habiamos hecho nada con esa VM.

Entonces.. suponiendo que sea tema con drivers dejo varias preguntas:
1. Cuales son esos drivers.
2. Como revisar dichos drivers y ver cual será el problema
3. Como solucionar el problema ya que instalar y volver a instalar NO funcionó para nada.

Aclaración importante: 4 de nosotros menos el ya pudimos hacer andar todo bien. O sea que por descarte digamos yo llego a la conclusión de que tiene algún problemita raro en su PC.

**Comment by tferraro** [comment]
👋 Alo,
De los drivers _en la vm_ , dudaría, porque estás en un entorno virtualizado y es virtualbox el que se encarga de disponibilizarte periféricos virtuales. Sobretodo si chequearon el md5 del disco de la vm y no cambio, descartaría la vm como causante.

Dado que es un caso particular de una pc, lo más probable es que sea alguna config que tenga esa pc particular, por lo que ahí les recomiendo que le peguen una buena googleada al error y vean que cosas pueden llegar a ser y hacer proceso por eliminación 💪🏻

**Comment by mgarciaisaia** [comment]
¡Ahhh mirá, che!

Acá en [POSTS INTERESANTES](https://github.com/sisoputnfrba/foro/blob/9cc7f7958e200d8d67aff0e6832d21100f379cb7/POSTS%20INTERESANTES.md) tenemos un link al #1010 que menciona precisamente este error. ¿Probaron eso?

**Comment by Nachiten** [comment]
Estamos en proceso de solucionar.. en cuanto lo hayamos hecho cierro aca. Gracias

**Comment by Nachiten** [comment]
Ya resolvimos
