### ISSUE TITLE
Problema con la VM y eclipse

### ISSUE THREAD

**Issue by MariKevorkyan** [sisoputnfrba/foro#1610]
Buenas! Tengo dos temitas.
El primero me aparece apenas prendo la VM: 
![Error](https://user-images.githubusercontent.com/49453001/78459888-b60f9a00-7692-11ea-89e8-36e4ccb1ed33.jpg)

Y el otro cuando quiero ejecutar mi proyecto:
![Error 1](https://user-images.githubusercontent.com/49453001/78459893-c6c01000-7692-11ea-879c-55b48b041506.jpg)

**Comment by jcastagno99** [comment]
Buenas! , yo tuve el mismo problema hace unos días y lo pudimos solucionar. Te dejo el issue (ya cerrado) por si te sirve esa solución
 https://github.com/sisoputnfrba/foro/issues/1604

**Comment by MariKevorkyan** [comment]
Muchas gracias!! Ahi lo miro y veo si se resuelve
