### ISSUE TITLE
Problema con VM y el BIOS

### ISSUE THREAD

**Issue by Nacho986** [sisoputnfrba/foro#1611]
Hola
Tengo una consulta que ya no se como resolverla, Tengo el tipico problema que tengo que solucionar entrando al BIOS y activar el modo virtualizacion de la pc (Lo se porque ayude a un compañero de equipo a solucionarlo).

El problema es que por algun motivo tiene el BIOS tiene contraseña y no puedo sacarla, ni cambiarla ni borrarla.
Lo digo porque ya intente todo: 

- Usar el codigo que me da cuando pongo 3 veces la contraseña mal para que la web me de el codigo de mi maquina y no funciono.
- Desarmar la pc para sacarle la pila y la bateria para poder reiniciar el CMOS tan poco me funciono.
- Hacer un recovery de la version anterior del BIOS tan poco dio resultado.
- Me baje el hirens boot's para poder hacer algo pero no se como utilizarlo.

Esta es la foto del error que tengo a ver si alguno tiene una solucion para esto:
![Captura](https://user-images.githubusercontent.com/40006975/78461182-4521af80-769d-11ea-966c-d4e59b0b0f93.PNG)

Alguno sabe que puedo hacer?

Desde ya muchas gracias

**Comment by gastoncastineira** [comment]
Si no podés prender la virtualización del CPU estás bastante jodido para virtualizar. Pregunta medio boluda la mía quizá, pero ¿probaste buscando la contraseña en internet? Si vino por defecto con la mother no puede ser una excesivamente complicada.

La única alternativa que te quedaría si no podés virtualizar sería hacer una instalación limpia de algún Linux en otra partición del disco y meterle un dual boot para tener windows (o lo que sea que tengas ahora) junto con ese Linux

**Comment by dariokozicki** [comment]
Dato curioso: VirtualBox y Docker son incompatibles. Comiquísimo.
Lo que yo hice para resolver eso, porque necesito ambos, es hacer un dual boot, una con la BIOS con Virtualization y otra sin.

https://www.jasoft.org/Blog/post/como-utilizar-hyper-v-y-virtualbox-en-el-mismo-equipo-con-windows-10.aspx

Fijate si eso te es de ayuda.

**Comment by Nacho986** [comment]
> 
> 
> Si no podés prender la virtualización del CPU estás bastante jodido para virtualizar. Pregunta medio boluda la mía quizá, pero ¿probaste buscando la contraseña en internet? Si vino por defecto con la mother no puede ser una excesivamente complicada.
> 
> La única alternativa que te quedaría si no podés virtualizar sería hacer una instalación limpia de algún Linux en otra partición del disco y meterle un dual boot para tener windows (o lo que sea que tengas ahora) junto con ese Linux

El problema es que no estoy seguro de haber sido yo el Bol.... Se que no vino de fabrica porque ya hice esto una vez de activar la virtualizacion (antes de un formateo) entonces dudo que haya no sido yo el que puso la contraseña (el tema es que si fui yo estoy seguro de que le puse una contraseña que la puedo sacar intentando, y ya intente 43 diferentes posibilidades).
Estuve pensando en instalar un linux y hacer un dual boot (tendria que aprender como se hace, si tenes un link que me ayude seria muy apreciado). 
Mi pregunta en ese caso es, para poder acceder a la maquina virtual para hacer el TP y presentarlo ¿No estaria con el mismo problema pero desde el Linux? O sea si el BIOS no me deja Virtualizar desde windows, me va a dejar Virtualizar desde Linux la maquina para hacer el TP? 
En caso de que no vaya a tener ese problema me podrias pasar alguna pagina que me explique como hacer el dual boot de manera confiable? (o for Dummies jaja)

Dario lei el articulo y no me queda claro lo de hyper-v. Por lo que entendi hyper-v es lo que usa VMbox en windows para hacer la virtualizacion y que tiene 2 valores no (apagado) y auto (que imagino que hace lo que le dice el BIOS).
Les pido disculpas si mis preguntas son muy basicas, no soy experto en el tema y no trabajo con nada relacionado con esto como para saber, y de hecho estoy aprendiendo mucho con este tema. A los palos y utilizando un monton de tiempo que siento que no puedo usar en el TP0
Desde ya muchisimas gracias!

**Comment by gastoncastineira** [comment]
Tendrías el Linux en dual boot para trabajar como si fuera la vm, no para ponérsela. Lo que tiene la vm es que viene con todo lo que necesitan para hacer el TP instalado, pero no tiene ninguna magia especial que otro Linux no tenga. Obviamente sí. vas a tener que instalar todo de cero vos, y sí, tiene que ser Linux por razones que en las próximas semanas te vas a estar enterando.

Lo del link te recomiendo que te busques vos uno porque no sé cómo te lleves con el inglés y lo que es fácil para mí tal vez no lo sea para vos, y viceversa. Cualquier video que parezca que funcione con tu SO actual tiene que servir.

**Comment by mgarciaisaia** [comment]
👋 Calculo que _EL_ problema a solucionar es el de conseguir el password de tu BIOS.

En [esta página](https://www.askvg.com/how-to-reset-remove-bypass-a-bios-or-cmos-password/) listan, al final de todo, un montón de passwords "backdoor" de los BIOS de distintos fabricantes, que _en teoría_ deberían funcionar indistintamente del password que hayas elegido vos. Fijate si andan.

Si no, también dice que podés cambiar el jumper del CMOS para resetear los datos - se pone un poco más picante la cosa, pero quizá también funcione.

También dice que desde una consola de Windows podés correr un par de comandos que resetean la configuración de la BIOS. ¿Probaste eso ya?

Nos puede llegar a servir saber el modelo de tu mother, también, para buscar algo más específico.

-----

La alternativa que menciona Gastón es instalar un Linux nativo y hacerlo andar. No es la más recomendada, pero capaz, si no te queda mucha opción, vale hacerlo. Chiflá cualquier cosa que necesites con eso.

**Comment by Nacho986** [comment]
Bueno, ya le di mi ultima tarde y no pude hacer mucho mas, Ya se que resetear el CMOS no me sirve, ya que haciendo lo de la pila, y otros metodos que no modificaron en nada el password. Mañana defino si me quedo sin chances y hago el dual boot como me sugiere @gastoncastineira como "mi unica esperanza" (No hay problema con el ingles si tenes algun tutorial para recomendar)
@mgarciaisaia entre en la consola y puse debug pero no me reconocionnada. Sabes si me equivoque con algo?
Muchas gracias!

**Comment by Nacho986** [comment]
Bueno, hoy voy a instalar Linux en mi pc. 
@gastoncastineira @mgarciaisaia Da igual cual Linux instale? Hay algun standard o algo que tenga que tener en cuenta para instalar y que sea todo compatible con el TP?
Disculpen si la pregunta es muy basica. 

Saludos!

**Comment by iago64** [comment]
@Nacho986 bienvenido al mundo feliz de Linux :)
Respecto a la distro (o alternativa de Linux) si queres charlamos aparte y te doy una mano. 
A priori cualquier distro te va a servir, pero lo mejor seria que empieces con algo simple (como para que el salto de windows a linux no sea muy duro), pero bueno ahi depende de la pc que tengas capaz podes empezar con el clasico Ubuntu o alguna de sus variantes segun cual veas que te gusta mas (o te da la pc para ello)

Abrazo.-

**Comment by Nacho986** [comment]
@iago64 
La verdad es que no tengo problemas de adaptacion jaja. Me acostumbro rapido a lo nuevo asi que sin miedo de intentar cosas diferentes.
Es mas estaba mirando como hacer para pasar de VM a SO nativo haciendo una copia de la VM de mis compañeros: https://www.youtube.com/watch?v=2tUkmeDdXjM (en el video lo hace desde la VM lo cual tendria que pedir a un compañero que lo haga)
Crees que esto es posible? 
Mi objetivo principal es estar en las mismas condiciones que mis compañeros de equipo asi evitamos cosas que nos puedan generar confusion o errores por diferentes configuraciones.
Te parece que esto es posible? Si no que distro me recomendas que descargue?

**Comment by iago64** [comment]
Sinceramente? es complicarte la vida un poco por de mas.
Si queres saber que tienen instaladas las VMs, podes hacerlo directamente en la pagina de donde las bajas https://www.utnso.com.ar/recursos/maquinas-virtuales/

Puntualmente los comandos que estan abajo son para correrlos en Ubuntu (o cualquier derivado de debian) por lo que si optas por instalar un ubuntu server y despues instalar encima todo lo demas tenes que correr ambas opciones (la primera que dice ubuntu server te instala los paquetes para poder codear tranquilo) y la segunda te instala el entorno grafico.
Si vas por alguna opcion con entorno grafico (Ubuntu, Kubuntu, Lubuntu, Xubuntu, etc) solo tendrias que correr lo que esta en la casillita de Ubuntu Server (ya que el entorno grafico ya lo tenes)

Abrazo.-

P.D> Cualquier duda buscame en el quienes somos de la catedra y mandame un mail y te doy una mano en la instalación.

**Comment by mgarciaisaia** [comment]
¡Aloha!

Vengo a bajar un poco más de línea.

Con este plan de ahorrarse dolores de cabeza, lo mejor sería que tengas tu instalación de Linux lo más parecida posible a la de tus compañeros. Para eso, bajate [el Ubuntu Server 16.04.4 de 32 bits](http://old-releases.ubuntu.com/releases/16.04.4/ubuntu-16.04.4-server-i386.iso), instalalo, y agregale los paquetes que listamos en la página del blog que linkeó Dami.

**Comment by Nacho986** [comment]
Queria comentar que este Issue quedo resuelto! 
Hicimos todo lo posible con @iago64 para poder entrar a la BIOS y no fue posible. 
Asi que ya tengo instalado el Linux en mi pc! 
Muchas gracias por la ayuda! cierro el Issue
