### ISSUE TITLE
Problema con las Guest Additions

### ISSUE THREAD

**Issue by TomasM99** [sisoputnfrba/foro#1612]
Holaa
Tengo un problema con el tema de las Guest Additions, pude iniciar mi maquina virtual y configurar la parte del eclipse, pero previo a eso quise instalar las guest additions siguiendo los pasos del video y cuando finalice me saltaron muchos errores (carteles blancos) por toda la pantalla. Lo cerre y lo volvi a abrir un par de veces y cuando le doy a "Dispositivos" => "Insertar imagen de CD de las Guest Additions" me salta el error de la foto
![Guest addtions](https://user-images.githubusercontent.com/49131848/78462469-b450d100-76a8-11ea-812f-5d1434553d1c.png)

El problema con esto es que nunca me queda en pantalla completa y demas, si alguien sabe como resolverlo, o si tengo que instalar todo de vuelta en otra maquina virtual nueva me seria de gran ayuda. 

Gracias un saludo.

**Comment by karengrams** [comment]
¡Buenas Tomas! 
¿Como va? Esto mismo paso en el issue #1293. Cualquier otra consulta, o si no podes solucionarlo, avisa de nuevo por acá :).

¡Saludos!

**Comment by TomasM99** [comment]
Gracias! Si, pude leer bastante y por ahora la pantalla se me acomoda bien y parece funcionar, gracias y saludos!
