### ISSUE TITLE
Problema ejecucion server tp0

### ISSUE THREAD

**Issue by MarcosInfantino** [sisoputnfrba/foro#1613]
Hola! Estoy haciendo el tp0 y cuando quiero ejecutar el server me tira este error. 
![JPEG_20200404_225308](https://user-images.githubusercontent.com/49456888/78465620-a0b86100-76ce-11ea-8cda-be5a1e69fd4a.jpg)

**Comment by MarcosInfantino** [comment]
Obviamente antes lo compile, y no tuve problema al compilar, pero cuando lo ejecuto me tira segmentation fault.

**Comment by gastoncastineira** [comment]
"segmentation fault" en algo que sabemos que anda es muy poca información :(

2 preguntas. 

¿Desde dónde lo estás ejecutando? Ruta completa (con pwd la sacás)
¿Cúal es el comando que estás tirando en consola para ejecutarlo?

**Comment by MarcosInfantino** [comment]
Abro la consola desde el escritorio y, luego de clonarlo hago:
cd home/utnso/Game-watch-server
make
home/utnso/Game-watch-server/Server

**Comment by MarcosInfantino** [comment]
Ahora ya no me tira mas segmentation fault, pero despues de tipear esos comandos la consola se queda colgada como pensando, ni si quiera escucha nada de lo que escribo y tengo que cerrarla y abrirla para volver a tipear comandos

**Comment by dariokozicki** [comment]
Marcos,
El Server del tp0 no tiene logs: escucha pero no te avisa que recibió ni nada. Te recomiendo loggearlo internamente para ver cómo es el proceso que hace. Eso que 'se queda colgado' es la escucha.

**Comment by gastoncastineira** [comment]
Te gana la ansiedad! 

Que no escriba nada por consola quiere decir que el servidor está corriendo. Podés corroborarlo tirando htop (una suerte de administrador de tareas de Linux pero con más power)

Me la juego a que en un primer momento también se te quedó colgado así, lo tiraste abajo y después empezó a tirar segfault. Básicamente no le diste tiempo al SO a desocupar los recursos que te tomó el servidor al levantar, y cuando lo volviste a levantar y este lo pidió de nuevo el SO y este le dijo "está ocupado" y lo mató. Nada, te va a pasar mucho en el TP, así que tenete y tenenos paciencia

**Comment by afilgueira** [comment]
@MarcosInfantino para issues futuros, por favor lee https://github.com/sisoputnfrba/foro/blob/master/README.md. Nos va a ayudar a ayudarte. 

Éxitos con eso!

**Comment by achoquemamani** [comment]
Que significa "compilarlo con make", para el servidor?
![TP duda](https://user-images.githubusercontent.com/43005891/78828564-46175180-79bb-11ea-908d-a0fab400ddc8.png)

**Comment by mgarciaisaia** [comment]
@achoquemamani `make` es un comando ejecutable que compila proyectos. Lo que significa "compilá el proyecto con `make`" es que abras una consola, hagas `cd` al directorio correspondiente, y ahí ejecutes el comando `make`. Eso te va a compilar el programa, generándote un binario `Server` que vas a poder ejecutar tipeando `./Server`.

**Comment by achoquemamani** [comment]
Hacer el make dentro del path correspondiente, puede ser que sea equivalente a cargar el proyecto en Eclipse por medio del makefile (como en el proyecto cliente), y compilarlo?

**Comment by mgarciaisaia** [comment]
Sí, totalmente. De hecho, en la vista de Output te muestra que ejecuta `make`, y toda la salida que éste da.

**Comment by achoquemamani** [comment]
Muchas gracias!

**Comment by mgarciaisaia** [comment]
@MarcosInfantino ¿Cómo quedó esto? ¿Qué avanzaste/aprendiste/averiguaste/lograste en estos días que pasaron?

**Comment by MarcosInfantino** [comment]
Pude solucionar este problema en específico, pero sigo peleándome con el tp0 para hacerlo funcionar jajaja
