### ISSUE TITLE
Problema con Eclipse

### ISSUE THREAD

**Issue by manupawlow** [sisoputnfrba/foro#1614]
Buenas, para probar eclipse me guie de un video de utnso en el cual imprime por pantalla "Hola mundo!". Trate de hacer eso por mi cuenta pero me tiraba errores que no sabia lo que significaban. Asi que copie exactamente como lo hizo en el video, pero cuando lo intento compilar me sigue tirando errores que no entiendo. No se que puede ser lo que le hace fallar, o si es algun problema relacionado con la instalacion de la mv.
Un saludo y gracias.
![WhatsApp Image 2020-04-05 at 18 49 57](https://user-images.githubusercontent.com/49321841/78510871-bd0bda80-776e-11ea-9e86-058a8731e9dd.jpeg)

**Comment by mgarciaisaia** [comment]
¡Hola!

¿Qué intentaste?

¿Qué entendés que está sucediendo? ¿Qué averiguaste de los mensajes de error que tenés? ¿Cuáles son esos mensajes de error? ¿Qué se te ocurre que puede tener que ver con tu proyecto?

Un mensaje en el foro diciendo "No anda" no aporta mucho. Ponele que te podamos ayudar a resolverlo (ni siquiera estoy seguro de si nos alcanza la info que tenemos), ¿de qué te serviría?

Algo **fundamental** en la carrera es aprender a aprender. A investigar. A tratar de entender qué está pasando.

Postear esto y esperar que te resolvamos no te aporta nada.

Tratá de identificar cuál es el mensaje de error importante que tenés ahí, investigá un poco qué puede estar significando, tratá de pensar qué herramientas, configuraciones y cachos de código pueden ser relevantes. Pensá cómo podrían estar interactuando las distintas cosas para llegar a este error. Cómo podrías solucionarlo. Cómo te gustaría que se solucione.

Y contanos.

Recién ahí vamos a poder ayudarte =/

**Comment by afilgueira** [comment]
Hola @manupawlow, para issues futuros, por favor lee https://github.com/sisoputnfrba/foro/blob/master/README.md. Nos va a ayudar a ayudarte. 

Éxitos con eso!

**Comment by manupawlow** [comment]
Investigue un poco como recomendas, pero la verdad no encontre nada. En una pagina hablaban de que puede ser un error de las librerias. Pero despues borre el printf y solo deje la funcion main con un return 0, y aun asi me seguia tirando el mismo error. 
Lo que yo entiendo de los errores es que capaz de alguna forma la funcion main devuelve el estado de error, pero no encontre por que lo hace.
Pero lo que no entiendo es porque el codigo en el video que mencione funciona y exactamente el mismo codigo en mi maquina virtual no lo hace.
La verdad no se donde mas buscar de este tema ni que hacer para encontrar cual es el error y solucionarlo.

**Comment by mgarciaisaia** [comment]
¿Te sirvieron [estos issues](https://github.com/sisoputnfrba/foro/search?q=undefined+reference+to+%60main%27&type=Issues)?

**Comment by manupawlow** [comment]
Si, ya pude solucionar el problema. Gracias.

**Comment by mgarciaisaia** [comment]
¿Cuál fue la solución, che? ¿Qué estaba pasando?
