### ISSUE TITLE
Problema - Guest Additions

### ISSUE THREAD

**Issue by nubevi** [sisoputnfrba/foro#1615]
Trate de instalar las Guest Additions y en la Shell me aparecio el seguiente mensaje:

"Running kernel modules will not be replaced until system is restarted"

¿Que tengo que hacer? Ya reinicie el lubuntu y me sugie tirando el msj

Desde ya, muchas gracias

**Comment by gastoncastineira** [comment]
comentarios para futuras generaciones?
