### ISSUE TITLE
Eclipse no crea binarios

### ISSUE THREAD

**Issue by micapucci** [sisoputnfrba/foro#1616]
Buenas noches!

Estoy teniendo problemas para compilar programas ya que no se me genera el binario correspondiente y por lo tanto tampoco puedo ejecutar.
En el video que habla sobre crear un primer programa en C, al incluir las bibliotecas y compilar el binario se genera pero en mi caso no funciona y no sé que puede estar mal. Googleé pero no encontré una respuesta que solucione el problema. 
Hice varias pruebas creando diferentes proyectos pero ninguno funciona, adjunto una foto de la pantalla con el error, es el programa más básico posible por eso no entiendo que puede estar mal. 

Desde ya muchas gracias, saludos!
![Anotación 2020-04-06 000623](https://user-images.githubusercontent.com/48954967/78520047-96b06400-779b-11ea-9469-8c04e5fd730c.png)

**Comment by gastoncastineira** [comment]
Muy poca info :'(

¿Cómo creaste el proyecto? ¿Guardaste antes de compilar? ¿Compilaste antes de ejecutar? ¿Cuál es el video del que estás hablando? ¿Probaste compilando en consola en vez de Eclipse para ver si el problema es efectivamente Eclipse?

**Comment by micapucci** [comment]
Buenas!
El video es este https://www.youtube.com/watch?v=2X9vfLSeB6A&feature=youtu.be. El proyecto lo creé igual que ahí y también trate creando un proyecto con la opción de "hello world ANSI c project" guardando y compilando de ahí y el problema persiste. Siempre guardo y compilo antes y por lo que entiendo los binarios se generan al compilar. 
En la parte de "problemas" no me aparece nada pero no puedo ejecutarlo y me sale el mensaje que aparece en la captura. Busqué en issues viejos pero no encontré nada similar y por lo que leí en internet se soluciona recompilando pero no es mi caso.
Cuando lo corro por consola no me muestra errores pero tampoco imprime nada. Reinstalé la VM con las guest y las commons para ver si se solucionaba pero sigue igual, se me ocurrió que tal vez tenga que configurar algo de eclipse pero que tampoco corra por consola me hace dudar y no tengo mucha idea de que más hacer.
Otra cosa es que cuando intento correr el tp0 tampoco puedo y me da errores que al resto de mis compañeros no teniendo exactamente el mismo código, así que supongo que esto tiene que ver con lo anterior.

**Comment by gastoncastineira** [comment]
Mmmmm, me gustaría verlo en vivo para ver qué estás haciendo, porque así a ciegas me estaría costando. Te puedo agendar para esta noche a última hora una call?

**Comment by micapucci** [comment]
Dale sí perfecto! Cuando te quede cómodo. Decime si necesitas mi mail o algo y te paso. Muchas gracias

**Comment by gastoncastineira** [comment]
Buscate mi mail en el quienes somos y mandame un calendar con una invitación a meet o hangouts, la que prefieras (discord yo por ahora no por problemas de hardware TnT )

**Comment by mesaglio** [comment]
Fijate si esto te puede ayudar [issue](https://github.com/sisoputnfrba/foro/issues/1604).
Capaz te sirve. 👍

**Comment by micapucci** [comment]
Probé lo anterior pero el error persiste con la diferencia de que ahora sí me crea la carpeta "Binary" aunque cuando trato de correrlo me dice "Lauched failed, binary not found."

**Comment by gastoncastineira** [comment]
Después de dos horas de debuggeo encontramos que _**por razones**_ los binarios que eclipse le genera se están generando sin permiso de ejecución para ningún usuario. Si lo corrés con sudo o le cambiás los permisos, falla porque encuentra algo roto en el binario.

Me comentó que no prendió la virtualización en la BIOS. He visto VMs que prenden a pesar de eso y tienen comportamiento errático. Quedamos que va a probar de prender la virtualización y si sigue sin andarle probar en otra computadora que tenga en su casa para ver cómo evoluciona el problema. Quede en contacto para seguirlo con ella

**Comment by micapucci** [comment]
No fue necesario prender la virtualización porque me fijé y ya estaba prendida, bajé una versión más vieja de VirtualBox y siguió teniendo el mismo problema así que voy a instalar todo en otra computadora a ver si funciona.
A pesar de eso igualmente muchas gracias! Saludos

**Comment by mgarciaisaia** [comment]
@micapucci dudo muchísimo que la versión de VirtualBox te cambie algo. Más bien apostaría a que es algún problema de la configuración del proyecto.

Mirate el video de [Reportar errores usando Eclipse](https://faq.utnso.com.ar/errores-eclipse) y pasá los logs a ver qué está pasando.

También puede servir que pases el resultado de ejecutar `ls -l` en el directorio del proyecto `holaMundo.c`.

**Comment by micapucci** [comment]
Ya lo arreglamos (Gastón lo arregló). Teóricamente una configuración de eclipse estaba mal y por eso no compilaba las cosas.
Muchas gracias por la ayuda! Saludos

**Comment by GastonMGrecco** [comment]
una lastima que nunca explicaste qué error de configuracion te generó eclipse. Me habría ayudado a mí que lo explicaras la rcdtm, hdp
