### ISSUE TITLE
Consulta: Cuándo y cómo detener un server

### ISSUE THREAD

**Issue by dariokozicki** [sisoputnfrba/foro#1617]
Buenas,

Estoy empezando a setear el servidor de Broker. La estructura a grandes rasgos es la siguiente:
```
int main(int argc, char ** argv){
    initialize();
    start_server(cfg_values.ip_broker, cfg_values.puerto_broker);
    finalize();
    return EXIT_SUCCESS;
}
```
En finalize(); se libera la memoria de forma muy similar a como está en el game-watch-client 
(logs, configuración, sockets). El problema es que nunca llega a esa instancia porque start_server
escucha indefinidamente. Normalmente hago un Ctrl+C para detenerlo, pero en valgrind me
aparecen memory leaks por no haber llegado a finalize();

Probé haciendo `signal(SIGINT, finalize)` pero el programa no logra finalizar.
Haciendo `atexit(finalize);` para llamar a la función antes de salir pareciera funcionar, 
pero sigue dándome la duda de **cómo debe saber el servidor que tiene que finalizar**.
Alguna de las conexiones tiene que decirle que se detenga?

Gracias!
```

**Comment by gastoncastineira** [comment]
Antes que todo vale la aclaración que tener que tirar el proceso en una entrega con ctrl+C no es un problema.
Más allá de eso, normalmente lo que se tiene es algún proceso con alguna consola interactiva con un comando tipo "exit" que le diga a tu while(1) "che, es hora de terminar". 
Acá lo que podrías hacer es que tu sighandler cambie ese flag para que salga del while. Las signals son una herramienta poderosa pero peligrosa también ya que cuando le llegue una a tu proceso este va a parar todo para atenderla y va a ignorar todo lo que pase alrededor (como otras señales, que bien podría haber un segfault dentro de finalize), y después va a volver a su ejecución normal. No es buena práctica usar las señales para cosas mucha más complejas que setear flags

**Comment by ncoen97** [comment]
Teniendo en cuenta lo que dijo @gastoncastineira, seguramente siempre que termines el server con ctrl+C vas a tener memory leaks, ya que algo de memoria tomada te va a quedar tomada. Lo que tenes que fijarte es qué tipo de memory leaks te tira valgrind, ahí te vas a dar cuenta si realmente estas perdiendo bloques/bytes que no liberaste (definitely lost, indirectly lost) o si es memoria a la que todavía tenes acceso (still reachable).

**Comment by dariokozicki** [comment]
Gracias a ambos por los comentarios! Seguí el consejo de @gastoncastineira y usé un flag para que el servidor deje de iterar después de Ctrl+C.
La única memoria (possibly lost) que me queda es la del thread que estaba atendiendo al cliente.

![2020-04-06-130447_1360x768_scrot](https://user-images.githubusercontent.com/38699660/78579650-a06fb100-7807-11ea-8e7e-0370d1db1c52.png)

Con eso alcanzaría para la entrega? No estoy del todo seguro por qué queda el residuo del pthread, pero leí que no aumenta con la cantidad de threads.

**Comment by gastoncastineira** [comment]
Eso es por algo que vamos a estar hablando cuando publiquemos el video sobre hilos. Básicamente

**Comment by dariokozicki** [comment]
Sí, me refería a final de cuatrimestre para que no se nos vaya escapando nada 😄 

Gracias por la ayuda!

**Comment by mgarciaisaia** [comment]
👋 ¡Hola!

Dos cosas:

1) incluso en el estadío original estabas bien. No sé si ya lo habrás visto en clase o no, pero cuando un proceso finaliza, el sistema operativo se encarga de liberar todos los recursos que ese proceso tenía asignados. Esto significa que esa memoria que te quedaba como Still Reacheable no _se pierde_ - el SO la libera. `valgrind` te lo avisa para que lo sepas, pero no es un error _per se_.

Los leaks reales son la memoria a la que dejás de tener acceso _durante la ejecución de tu proceso_. Eso es problemático porque mientras que el proceso siga en ejecución, es memoria que tu proceso va a tener asignada pero sin poder aprovechar. Si la ejecución de tu proceso durara lo suficiente, podrías superar el límite de memoria que el sistema permite para tu proceso, y entonces el sistema operativo podría terminar tu proceso abruptamente.

Pero, de nuevo: la memoria que está sin liberar al final del proceso no es problemática.

2) No subas capturas de pantalla, porfa. Mejor copiá y pegá el cacho de código, así la próxima vez que alguien se cruza con un possibly lost en un `calloc` dentro de `allocate_dtv` dentro de un `pthread_create` puede usar el buscador de Github y encontrar este issue. Si dejamos el screenshot, este thread se pierde en la nebulosa.

¡Salute!

**Comment by dariokozicki** [comment]
Buenas! Dejo el copypasta del screen así ya queda:

==14242== HEAP SUMMARY:
==14242==     in use at exit: 272 bytes in 2 blocks
==14242==   total heap usage: 401 allocs, 399 frees, 28,076 bytes allocated
==14242==
==14242== Thread 1:
==14242== 272 bytes in 2 blocks are possibly lost in loss record 1 of 1
==14242==    at 0x402E0B8: calloc (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==14242==    by 0x4011726: allocate_dtv (dl-tls.c:322)
==14242==    by 0x401214B: _dl_allocate_tls (dl-tls.c:539)
==14242==    by 0x4061CC3: allocate_stack (allocatestack.c:588)
==14242==    by 0x4061CC3: pthread_create@@GLIBC_2.1 (pthread_create.c:539)
==14242==    by 0x8049154: receive_new_connections (common_connections.c:51)
==14242==    by 0x804909D: start_server (common_connections.c:35)
==14242==    by 0x8048BE0: main (broker.c:7)
==14242==
==14242== LEAK SUMMARY:
==14242==    definitely lost: 0 bytes in 0 blocks
==14242==    indirectly lost: 0 bytes in 0 blocks
==14242==      possibly lost: 272 bytes in 2 blocks
==14242==    still reachable: 0 bytes in 0 blocks
==14242==         suppressed: 0 bytes in 0 blocks
