### ISSUE TITLE
[Consulta] Tutorial sobre common libraries

### ISSUE THREAD

**Issue by Nachiten** [sisoputnfrba/foro#1618]
Existe algún tutorial de como usar los _common libraries_ o al menos una lista de qué funciones hay y como se usan?
Perdón si mi pregunta es estúpida pero sinceramente busque en la pagina de SO también en el repo de github de dichas bibliotecas y no encontré un lugar donde entender o aprender a como explotarlas al máximo para lo que sea que necesite hacer en el TP.

Gracias :) Y pido disculpas por ser pesado haciendo 38 issues aca. (3 solo hasta ahora jiji mas el tutorial)

Edit: Ya que estoy quiero hacer una pregunta mas y es que yo decidí (porque lo creía conveniente) clonar estas common libraries en la carpeta mas afuera de nuestro repo del TP. Si hay que clonararla en algún lugar especifico por favor aclararme porque no tengo ni idea. 👍

**Comment by iago64** [comment]
Buenas buenas! 

No por nada solemos decir que las commons son un ejemplo de como codear bonito en C, y parte de ello es que si entras al [repo de las commons](https://github.com/sisoputnfrba/so-commons-library)

vas a ver que primero tenes en el README.md una guia de como instalarlas (Como para que no tengas que andar complicándote copiando carpetas y demas yerbas)
Y después por otro lado si revisas el código vas a ver que los .h tienen la descripción de las funciones (para que sirven y que parámetros reciben)

Ahora saliendo un toque de la pregunta, muchas veces nos pasa (Y si a los ayudantes también nos paso y mas de una vez) que nos gana la ansiedad, los nervios o la necesidad de resolver y justamente estos momentos son los mas importantes, donde hay que frenar la pelota y pensar para no terminar diciendo ~era por abajo Palacio~ _"uuuh no lo vi seguro van a pensar que soy re denso"_ 

Un abrazo!

**Comment by Nachiten** [comment]
> Buenas buenas!
> 
> No por nada solemos decir que las commons son un ejemplo de como codear bonito en C, y parte de ello es que si entras al [repo de las commons](https://github.com/sisoputnfrba/so-commons-library)
> 
> vas a ver que primero tenes en el README.md una guia de como instalarlas (Como para que no tengas que andar complicándote copiando carpetas y demas yerbas)
> Y después por otro lado si revisas el código vas a ver que los .h tienen la descripción de las funciones (para que sirven y que parámetros reciben)
> 
> Ahora saliendo un toque de la pregunta, muchas veces nos pasa (Y si a los ayudantes también nos paso y mas de una vez) que nos gana la ansiedad, los nervios o la necesidad de resolver y justamente estos momentos son los mas importantes, donde hay que frenar la pelota y pensar para no terminar diciendo ~era por abajo Palacio~ _"uuuh no lo vi seguro van a pensar que soy re denso"_
> 
> Un abrazo!

Igual gracias porque no sabia que era esa la rta.

**Comment by mgarciaisaia** [comment]
Las commons tienen booooooocha de tests, también. Por más que estén escritas en un modo _no tan C_, quizá, el código de los tests es bastante descriptivo. Son una buena fuente para entender cómo se usa cada una de las funciones (la enorme mayoría están testeadas, si no es que todas).
