### ISSUE TITLE
Duda con serializacion de paquetes, sizeof , malloc y memcpy

### ISSUE THREAD

**Issue by guidoenr4** [sisoputnfrba/foro#1619]
Que tal, tengo una consulta acerca del punto 3 del tp0.
por lo que entendi, la funcion `void* serializar_paquete(t_paquete* paquete, int *bytes)` retorna un puntero generico a lo que sea, en este caso supongo que es a todo el payload incluyendo el header.. hasta ahi estoy.
En el momento de codear, no se si estoy haciendo las cosas bien.. porque vi mas abajo que hay una funcion  `void enviar_mensaje(char* mensaje, int socket_cliente)` que recibe un char*.. entonces ahi me trabe, la funcion `enviar_mensaje` recibe un string? (array de chars) para enviarlo mediante el socket al otro proceso? si fuera asi, como lo adapto al paquete que serializo en la funcion de arriba? o debo crear un paquete en la funcion `enviar_mensaje` que contenga el string a enviar, aplicarle la funcion `serializar_paquete` y ahi enviarlo?

Les adjunto una imagen del codigo para que entiendan mejor, y de paso si es posible, guiarme un poco sobre si estoy manejando bien la memoria, malloc y demas. Gracias de antemano y perdon por la consulta larga!

![preguntaParaForo](https://user-images.githubusercontent.com/47611900/78604286-f48e8b80-782f-11ea-9aab-09f7064ea821.png)

**Comment by gastoncastineira** [comment]
> o debo crear un paquete en la funcion enviar_mensaje que contenga el string a enviar, aplicarle la funcion serializar_paquete y ahi enviarlo?

Eso! Eso de ahí! por ahí viene la mano. 
Podés revisar el código del servidor para ver qué es lo que está esperando recibir
