### ISSUE TITLE
problema con <string.h>

### ISSUE THREAD

**Issue by flamas472** [sisoputnfrba/foro#1620]
Hola, estoy tratando de hacer los ejercicios de C, para poder leer el apunte de sockets y empezar con el TP0 con una base más fuerte.
Como dice en el enunciado del ejercicio que busquemos que funcioens de ANSI-C podemos usar, decidi usar strcat(char*,char*) para el primero de todos.
use el  #include<string.h> y el programa compila.
Pero no funciona, y al debuggear veo que se detiene en la funcion strcat.
![image](https://user-images.githubusercontent.com/38506952/78610317-f578ea80-783a-11ea-8acd-aaa4c9d8fa40.png)
si sigo debugeando primero aparece lo siguiente:
![image](https://user-images.githubusercontent.com/38506952/78610500-51437380-783b-11ea-91e8-307eefeac776.png)
y finalmente termina el proceso.
![image](https://user-images.githubusercontent.com/38506952/78610526-66b89d80-783b-11ea-8153-51580ddefdeb.png)

PD: el codigo fuente que se ve no es el que usaría en el ejercicio, es el que use para debuggear, en realidad había usado una funcion como indica en el ejercicio.

**Comment by flamas472** [comment]
pude solucionarlo, lei en otro issue cerrado que el primer parámetro de strcat debe tener tamaño suficiente para concatenarse con el segundo.
sin embargo, sigo con un problema, el programa compila y funciona, pero no puedo debugearlo, me tira un error parecido en el malloc.
![image](https://user-images.githubusercontent.com/38506952/78611900-56ee8880-783e-11ea-89be-be471eb995a4.png)

**Comment by iago64** [comment]
Buenas buenas!

El que no puedas "debuguearlo" es porque simplemente de la biblioteca string.h no tenes el código per se, solo tenes los binarios, entonces eclipse no puede entrar a verlo y mostrarte ese código (que creeme aunque lo puedas ver es feo como patear la pata de la cama descalzo)

Abrazo.-

**Comment by flamas472** [comment]
hola, gracias.
es posible que pase así también con print f? o con un int i;?

**Comment by iago64** [comment]
Si señor! Cualquier funcion que uses de cualquier biblioteca que ya venga instalada (stdio, stdlib, string, etc) te va a pasar lo mismo :)

Abrazo.-

**Comment by flamas472** [comment]
y como puedo hacer para debuggear cómodamente? veo que malloc, printf, todas las de string.h y demás no andan, pero no siempre lo veo a tiempo para poder saltearlo con el step over.

**Comment by mgarciaisaia** [comment]
No se del todo cómo estarás usando el debugger, pero estimo que le estás dando siempre al botón de `Step Into` (F5, o la flechita que apunta para abajo, parecida a esta: ⤵️), cuya función es _entrar a la próxima sentencia_.

Lo que querés en los casos de funciones de las que no tenés el código fuente disponible es la siguiente, `Step Over` (F6, con un dibujito parecido, pero con la flecha más a la derecha aún). Eso lo que hace es _avanzar hasta la próxima sentencia_.

La diferencia es que, si la sentencia actual es una llamada a función, Step Into se mete a la definición de la función y ejecuta sentencia por sentencia, mientras que Step Over sigue al mismo nivel que estás ahora y ejecuta todo el llamado a función de una.

Respecto a por qué no te funcionaba el primer ejemplo de código, creo que [este post](https://gist.github.com/mgarciaisaia/fd5e97ad36d7ff018aa4) aplica muchísimo. Y puede que siga aplicando al caso que tengas ahora.

**Comment by afilgueira** [comment]
@flamas472 te sirvió esta info? Pudiste solucionar tu consulta?

**Comment by flamas472** [comment]
si, excelente gracias
