### ISSUE TITLE
Logger no muestra en pantalla el mensaje recibido

### ISSUE THREAD

**Issue by SwaXTech** [sisoputnfrba/foro#1621]
👋 ¡Hola!

Estoy terminando el TP0 propuesto y todo marcha bien, excepto por el hecho de que cuando recibo el mensaje que me envía [Game Watch Server](https://github.com/sisoputnfrba/Game-watch-server), el logger no es capaz de mostrarlo en pantalla.

¿Cómo se que el logger está funcionando?

- Responde bien al indicar que loguee "Soy un Log".
- Responde bien al testear con otros punteros como el de ip o puerto.

¿Cómo se que el server está respondiendo correctamente?

- Una línea antes de la instrucción log_info() envié el puntero a la función puts() y es capaz de mostrar el mensaje en pantalla de manera correcta.

Supongo que mi problema está en el uso del puntero. Adjunto código y error que podría ser util.

**Porción del código de main()**
![image](https://user-images.githubusercontent.com/43499966/78629629-faa35d00-786d-11ea-81c3-0267b78cb8ce.png)

**Porción de código de la función recibir_mensaje()**
![image](https://user-images.githubusercontent.com/43499966/78629715-38a08100-786e-11ea-8f2f-7051e37b7a03.png)

**Consola: (El string impreso proviene de la función puts())**
![image](https://user-images.githubusercontent.com/43499966/78629757-5968d680-786e-11ea-8fbe-1a4a324a7159.png)

**Debug: (Parados en la instrucción log_info(logger, mensaje))**
![image](https://user-images.githubusercontent.com/43499966/78629789-769da500-786e-11ea-9836-b96396c03b4b.png)

Gracias de antemano!

**Comment by iago64** [comment]
Buenas buenas!

Vamos en orden de cosas para que sea mas facil de seguir:

1.- Los screenshots de codigo son algo molestitos de ver porque no podemos llevarnos el codigo a un eclipse y poder ver que es lo que esta pasando, con lo cual, por favor traten de copiar el codigo aprovechando que github tiene markdown tambien aca en el foro :)

2.- El supuesto error que estas viendo en el debuger, si lo lees un poco en detale te dice algo asi como:
"Can't find a source file at /build/glibc.... bla bla bla"
Que puesto en criollo es:
"Fiera no tengo los fuentes de malloc, pasa de largo porque no vas a poder ver codigo" (Y que aunque puedas verlo debe ser feo como patear la pata de la cama descalzo)

Con lo cual, el problema en si lo resolves haciendo un stepover (Creo que es F7 en eclipse) y seguis adelante.
De ahi a que puedas tener algun problema de un segment fault u otro tipo de problema es distinto, pero eso lo podes validar rapidamente al momento de ver el contenido de la variable desde la ventana del debug.

Abrazo!

**Comment by mgarciaisaia** [comment]
Para poner en contexto lo que dice Dami de copiar y pegar los textos en lugar de pegar un screenshot, fijate [cuántos resultados hay buscando `Can't find a source file`](https://github.com/sisoputnfrba/foro/search?q=can%27t+find+a+source+file&type=Issues) en el foro - y cuántos de esos tienen exactamente la misma respuesta que te dio Dami.

**Comment by afilgueira** [comment]
@SwaXTech  te sirvió esta info? Pudiste solucionar tu consulta?

**Comment by SwaXTech** [comment]
mmmm... si antes no funcionaba y no sabía por qué, ahora funciona y tampoco se por qué. Me refiero a que con ayuda de la solución subida a youtube hice algunos cambios en el código y pasó a funcionar (con otros errores pero el error del post había desaparecido). Ahora bien, tenía la version vieja del proyecto e implementé los cambios uno a uno para ver cuál es el que me soluciona el error y ahora estoy en la situación de que ambos proyectos son iguales, pero uno anda y el otro no. En fin voy a seguir investigando y consultando todos los post que me pasó @mgarciaisaia a ver si logro descubrir cuál es mi error. Saludos.

**Comment by SwaXTech** [comment]
Si, puntualmente la línea que me daba error era:

`log_info(logger, mensaje);`

que la cambié por:

`log_info(logger, "El mensaje recibido es: %s", mensaje);`

**Comment by mgarciaisaia** [comment]
¿Cuál era el error, che?

Tratá de encontrar bien qué estaba pasando, porque así nomás no estoy muy seguro de que [ese haya sido el problema](https://gist.github.com/mgarciaisaia/57fcca5849f3dbbef0a7d8ae5318793b).
