### ISSUE TITLE
tp0 dudas varias: funcionamiento servidor, qué hay que codear, memcpy, send, char*

### ISSUE THREAD

**Issue by foviedo** [sisoputnfrba/foro#1622]
Buenas! Tengo un par de consultas, voy en orden:
1_ Lo más importante. Cómo sé que lo que le envio al server le llegó correctamente? En otro lugar vi que dicen que revise lo que hace el server, pero me dejó bastante confundido, vi que hay un recibir_mensaje, que recibe de parámetros el socket_cliente y un size, que asumo que es el de mi mensaje empaquetado, pero no estoy seguro de cómo llamarlo o en dónde se está llamando antes como para poder saber dónde loguear o printear el contenido que está recibiendo. Lo que sé que al menos está pasando es que cuando compilo con el servidor abierto el programa finaliza con 0 así que calculo que algo estará llegando bue

2_Tengo que codear algo en servidor? O las 4 funciones son de cliente? Digo, se supone que el cliente tanto recibe como envía mensajes? 

3_Vamos al código
![image](https://user-images.githubusercontent.com/48896107/78637846-95f1fd80-7881-11ea-99e8-ba6e4b88495b.png)
Línea 54: Para confirmar, de segundo parámetro en memcpy, va la dirección del contenido que voy a copiar, no? En este caso, mensaje al ser de tipo char*, pongo solo mensaje porque eso ya es un puntero, no &mensaje, y eso debería ser igual para cualquier cosa que sea puntero?
4_
Línea 74: Cuando envío, pongo de parámetros para el tamaño de los datos del paquete, sizeof(char) (que es el header) y buffer->size (que es el tamaño del mensaje), los mismos que están en la guía de serialización. PERO: no faltaría un sizeof(int)? Digo, porque también voy a estar enviando el tamaño del mensaje como variable (línea 69), si bien en la guía lo hizo clavado a como lo codee yo, me hace bastante ruido.

5__Respecto a reservar memoria para un char*, esto siempre lo hice así:
![image](https://user-images.githubusercontent.com/48896107/78638579-e3229f00-7882-11ea-94fb-9a03ae87ce8b.png)
Y funciona, pero ahora tengo entendido que tengo que reservar memoria para ese char*, cómo debería hacerlo correctamente? O está bien que sea así? Dicho sea de paso, si quiero hacer free(mensaje) tengo el siguiente error el cual es bastante feo, si no hago free no pasa nada, pero calculo que voy a tener un par de memory leaks: 
![image](https://user-images.githubusercontent.com/48896107/78638738-2aa92b00-7883-11ea-8562-8440b430ca78.png)

6_en utils.c tengo para usar la función serializar_paquete() que recibe un paquete y un int*size, qué es este int* size? Por ahora estoy haciéndolo todo en una misma función.
Algo que noté es que en el utils.c de server, se envío a int size, el size de mi mensaje + 2*sizeof(int), no debería ser size de mi mensaje + sizeof(int) + sizeof(char)? Digo, porque el opcode es un char no un int 

Estoy probando varias cosas pero la verdad es que en la función recibir_mensaje() no recibo ni el opcode
Espero puedan ayudarme, gracias!

**Comment by gastoncastineira** [comment]
Primero y antes que todo, para futuros issues evitemos los pantallazos de código para ayudarnos a ayudarte mejor. Vos pensá que si yo eso lo quiero llevar a un editor de texto para verlo mejor o probarlo no puedo, y ponerme a copiar todo eso a mano hace complicado que nos den ganas de responderte pronto

Gorra off, te comento:

1. Hoy por hoy no podés porque el servidor no logea. Sentite lbre de abrirle el código y meterle logs donde lo creas necesario.
1. Creo que eso está bien explicado en el enunciado. Ustedes tienen que hacer solo el cliente

1. Sí. Te recomiendo que leas la guía de manejo de punteros del foro si te sentís flojo con eso y aprendas a usar el comando man de linux (o buscar la firma en internet) para no tener que esperar a que te contestemos dudas del estilo _"che, ¿qué este parámetro de esta función?"_ El tiempo apremia en un TP cuatrimestral y no da tener que esperar a que nosotros te podamos contestar un mail para poder seguir laburando cuando era algo que podías verlo solo
1. ¿De dónde sacás que el header es un char? Más allá de eso no estaría entendiendo bien la duda acá. Podés refrasear?

1. Justo ese es un caso particular que se ve en sintaxis. el sugar syntax de
`char * algo = "hola"`
No es memoria dinámica, es un array de chars que se define en tiempo de compilación dentro del stack del proceso. Como el stack es de solo lectura para el usuario, al tirarle free te tira ese error enorme que es básicamente el kernel del SO diciéndote "quisiste borrarme esto pero no tenés permiso. Lo-la". La regla de oro es; para todo malloc, un free. El opuesto también es cierto.

1. Ese int size podría no estar, es completamente cierto. Estaba ahí para tirarles una pista de por dónde va la mano de qué hay que hacer. Por otro lado si querés hacer todo en la misma función no pasa nada, va a andar igual. Pero recordemos las buenas prácticas que nos enseñaron en algoritmos y paradigmas. Toda función debe ser modular y atómica (osea, hacer una sola tarea que pueda ser reutilizable a lo largo del proyecto). Te parece que la función enviar_mensaje, que crea un paquete, lo llena, lo serializa y al final lo manda es atómica? o tiene más sentido que sea responsabilidad de serializar_paquete() parte de todo lo que hace? Además , hoy es solo un mensaje. Si mañana tenés que enviar un entero también, copiarías y pegarías el código para serializar el paquete también? Faltaría modularidad

**Comment by foviedo** [comment]
Entendido lo primero, extiendo más allá:

4_En la guía de serialización, cuando hace memcpy para el header, dice esto 
`memcpy(stream + offset, &persona.edad, sizeof(uint8_t));
offset += sizeof(uint8_t);`

Reserva un uint8_t, si no me equivoco, eso sería un char? O al menos tiene el tamaño de uno
Respecto al resto de la pregunta, tratando de replantearla me di cuenta de qué no entendía (era que en el size del buffer ya está incluida la longitud del mensaje)

5_GRACIAS no sabía

6_Acá hay un punto importante que es donde tengo más conflicto. en el server, cuando llama a esa función, le envía a la función en el lugar de size strlen(mensaje)+1 + 2*sizeof(int)
Esto se me contradice con lo de la guía de serialización que es a partir del que lo estoy haciendo yo, en la que el header mide sizeof(uint8_t) o lo que es lo mismo, sizeof(char). En este caso, mi conflicto pasa por lo mismo que el punto 4. La otra parte:

int size creo que sería el tamaño del paquete, en el caso de servidor está así 

`int size` 
y en el cliente dice
`int* size`
Me hizo ruido eso, asumo que voy a tener que declararlo como puntero para mandarlo, pero la diferencia capaz era que había algún mensaje oculto o forma "correcta" de usar esa función que no estaba viendo, porque en este caso voy a tener que crear una variable temporal
`int* tamanio = mensajeLength + sizeof(char)+sizeof(int)`
e invocar serializar con ese tamanio que es puntero

Más tarde voy a revisar de nuevo e ir cambiando cosas a ver si funcionan. Gracias!

**Comment by gastoncastineira** [comment]
4_ La guía de serialización no es más que eso, una guía. No tiene por qué contrastarse con la realidad ni del TP0 ni de su TP cuatrimestral. La diferencia entre un uint(8|16|32|64)_t te la dejo de tarea, pero fijate bien cuál es el tipo que tienen los códigos de operación que tiene el TP0, porque al serailizar lo que más importa es el tamaño en bytes que estos tienen

6_ #1594 aborda el mismo problema

**Comment by foviedo** [comment]
Gracias, cierro issue!
