### ISSUE TITLE
Problema con la función bind() - sockets

### ISSUE THREAD

**Issue by esanchezventurini** [sisoputnfrba/foro#1624]
Buenas. Estuve haciendo un socket que funcione como servidor guiándome con los videos de YouTube de la cátedra, pero cada vez que quiero correrlo tengo que cambiar el puerto porque al parecer queda abierto. Pensé que se iba a solucionar con la función setsockopt() pero sigue ocurriendo lo mismo. Desde Netcat, me deja conectarme al puerto. Adjunto screenshot y dejo el código. 

```
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netdb.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <string.h>
int main(void) {
	struct sockaddr_in direccionServidor;

	direccionServidor.sin_family = AF_INET;
	direccionServidor.sin_addr.s_addr = inet_addr("127.0.0.1");
	direccionServidor.sin_port = htons(8074);


	int servidor = socket(AF_INET ,SOCK_STREAM,0);

	int verdadero = 1;
	setsockopt(servidor, SOL_SOCKET, SO_REUSEADDR, &verdadero, sizeof(verdadero));

	if(bind(servidor,(void*)&direccionServidor,sizeof(direccionServidor)) != 0){
		perror("Falla en bind");
		return -1;
	}

	if(listen(servidor, 10) == -1){
		perror("Falla en listen");
		return -1;
	}

	struct sockaddr_in direccionCliente;
	unsigned int tamanioDireccion;

	int cliente = accept(servidor, (void*) &direccionCliente, &tamanioDireccion);
    printf("Conectado con: %d",cliente);

	while(1){
			char mensaje[1000];
			scanf("\n %s", mensaje);
			send(cliente, mensaje, strlen(mensaje), 0);
		}

}
```

![Screenshot from 2020-04-07 18-58-48](https://user-images.githubusercontent.com/49238030/78709034-637beb00-78e9-11ea-82d6-aa7ced1605e8.png)

**Comment by gastoncastineira** [comment]
No veo que le estés haciendo un close() al socket en ningún lado, así que es normal que el puerto quede ocupado un rato hasta que el SO lo limpie

**Comment by esanchezventurini** [comment]
Entonces siempre que corte la conexión desde Netcat con "ctrl + c" me va a quedar el puerto abierto? Si estoy haciendo un chat por ejemplo, entre un servidor y un cliente, cómo podría hacer para cortarlo de una forma adecuada? Es decir, alguna condición para salir del while que me permita luego usar la función close

**Comment by gastoncastineira** [comment]
Justo los servicio de mensajería son un mal ejemplo porque suelen ser P2P (par a par). No es un esquema en el que uno sea un servidor que está pensado para estar levantado 24/7 para servir a múltiples clientes, y bajo la eventualidad de que se te caiga el servicio, es poco probable que tardes menos que los 15 segundos (+- unos pares de segundos si la memoria no me falla) que se toma el SO en liberar ese puerto a salir corriendo a volver a levantar el servicio de nuevo.

Más allá de eso, está bien el planteo de controlar ese error, y es posible hacerlo. Te invito a pensar cómo #1617 se puede ajustar para lo que planteás

**Comment by esanchezventurini** [comment]
Buenísimo, muchas gracias. Voy a leer ese issue e intentar resolverlo, cuando pueda lo comparto por acá por si le sirve a alguien

**Comment by mgarciaisaia** [comment]
@esanchezventurini El problema real que estás teniendo es, como dijo al principio Gastón, que no estás haciendo `close()` en el socket. Eso hace que, al finalizar tu proceso, el sistema operativo deje ese socket en un estado de "cerrando" (`CLOSE_WAIT`) durante un tiempo. Esto ocurre por un tema de seguridad: si yo estoy corriendo un servidor escuchando en un socket, no quiero que otr@ usuari@ malicios@ pueda hacerle `kill -9` a mi proceso y levantar otro servidor escuchando en ese mismo puerto e "impersonando" a mi proceso original. Para evitar esto, el sistema operativo espera que tu proceso haga un `close()` del socket (avisándole al proceso remoto que esa conexión se terminó, y entonces ya sabe que si sigue mandando mensajes a ese puerto no vas a ser vos quien lo atienda), o, si termina el proceso antes de hacer `close()`, esperando unos 30 segundos para dar tiempo al proceso remoto a darse cuenta de que ese socket se cayó y que entonces deje de mandarte mensajes porque _andá a saber quién lo va a estar atendiendo_.

Entonces, la solución a tu problema es alguna de estas dos: o garantizás hacer `close()` al socket, o _esperás los 30 segundos hasta volver a levantar_.

En un programa "real", lo que suelen hacer es una de dos o tres opciones: 1) tienen un comando especial para cerrarse de manera controlada (por ejemplo, una consola en la que tipeás `exit` para "salir de ese `while`" y ejecutar todo lo que quieras cerrar/limpiar; o 2) manejás la señal de "tu proceso se va a cerrar" (`SIGTERM` es la que se envía cuando tocás CTRL+C en la consola), y ahí hacés que se corte tu ciclo `while`; o 3) usás alguna herramienta como `atexit` para registrar cosas que querés que pasen cuando cierre tu proceso - en este caso, hacerle `close()` al socket.

O, de nuevo: esperás los 30 segundos 🤷

**Comment by afilgueira** [comment]
@esanchezventurini te sirvió esta info? Pudiste solucionar tu consulta?

**Comment by esanchezventurini** [comment]
Si! Disculpen que no respondí, pero me sirvió toda la información que me brindaron. Lo que hice finalmente es hacer close() una vez que el cliente se haya desconectado (la cantidad de bytes recibidos es menor o igual a 0). Es como la segunda solución que dijo @mgarciaisaia pero en una versión "trucha", así que después voy a buscar cómo recibir la señal SIGTERM para poder mejorarlo. Les dejo la solución y si encuentran algún error o algo medio raro, por favor díganmelo. Muchas gracias por la ayuda 

```
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netdb.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <string.h>
#include <pthread.h>

struct cliente_y_servidor{
	int cliente;
	int servidor;
};

void recibirMensajes(struct cliente_y_servidor* datosDeConexion){
	int cliente = datosDeConexion->cliente;
	int servidor = datosDeConexion->servidor;
	char* buffer = malloc(30);
	int conectado = 1;
	while(conectado){
	    	int bytesRecibidos = recv(cliente, buffer, 30, 0);
	    	buffer[bytesRecibidos] = '\0';
	    	if(bytesRecibidos <= 0){
	    		perror("El cliente se ha desconectado");
	      		close(servidor);
	    		close(cliente);
	    		free(buffer);
	    		conectado = 0;
	    	}
	    	else{
	    		printf("Mensaje recibido: %s", buffer);
	    	}
	    }
}

void enviarMensajes(int* cliente){
	while(1){
			char mensaje[1000];
			scanf("\n %s", mensaje);
			send(*cliente, mensaje, strlen(mensaje), 0);
		}
}

int main(void) {
	pthread_t llegadaDeMensajes;
	pthread_t envioDeMensajes;

	struct sockaddr_in direccionServidor;

	direccionServidor.sin_family = AF_INET;
	direccionServidor.sin_addr.s_addr = inet_addr("127.0.0.1");
	direccionServidor.sin_port = htons(8115);


	int servidor = socket(AF_INET ,SOCK_STREAM, 0);

	int verdadero = 1;
	setsockopt(servidor, SOL_SOCKET, SO_REUSEADDR, &verdadero, sizeof(verdadero));

	if(bind(servidor,(void*)&direccionServidor,sizeof(direccionServidor)) != 0){
		perror("Falla en bind");
		return -1;
	}

	if(listen(servidor, 10) == -1){
		perror("Falla en listen");
		return -1;
	}

	struct sockaddr_in direccionCliente;
	unsigned int tamanioDireccion = sizeof(struct sockaddr_in);

	int cliente = accept(servidor, (void*) &direccionCliente, &tamanioDireccion);
    printf("Conectado con: %d \n",cliente);

    struct cliente_y_servidor infoConexion;
    infoConexion.cliente = cliente;
    infoConexion.servidor = servidor;

    pthread_create(&llegadaDeMensajes , NULL , (void*)recibirMensajes , (void*)&infoConexion);
    pthread_create(&envioDeMensajes, NULL, (void*)enviarMensajes, (void*)&cliente);

	while(1);
}
```

**Comment by afilgueira** [comment]
Buenas! Está subida la solución propuesta al TP0. Esto imagino que te va a ayudar a chequear tu código. Saludos!

**Comment by tferraro** [comment]
Buenas! Con la solución propuesta del TP0, se resolvó el problema que tenías @esanchezventurini ? Se puede cerrar el issuue 👮‍♂️

**Comment by esanchezventurini** [comment]
Buenas! Si, perdón, pensaba que ya lo habían cerrado

**Comment by mgarciaisaia** [comment]
¿Encontraste el problema? ¿Qué era?

**Comment by esanchezventurini** [comment]
El problema era que estaba cortando la conexión con ctrl+c pero no estaba agarrando ese corte adecuadamente. Lo que hice fue que una vez que el cliente se desconecta, el servidor recibe eso y así pueda desconectarse adecuadamente del puerto mediante close()
