### ISSUE TITLE
Arquitectura: clientes y servidores

### ISSUE THREAD

**Issue by EzeDiaz** [sisoputnfrba/foro#1626]
Hola! Pensando en al arquitectura del TP nos surgió la duda de quién es cliente y quién es servidor. Queremos saber si estas consideraciones son correctas y si hay algo más a tener en cuenta. Por una cuestión de que nos resulta más fácil pensarlo en términos de clientes y servidores es que lo planteamos de dicha forma, pero quizás ustedes consideren que es mejor hacerlo de otra manera; insisto, cualquier encaminamiento o apreciación que tengan será fuertemente valorada. Gracias!

## Broker
_**Cliente:**_ cuando sale a avisar de un evento que ocurrió en una cola, es cliente de los suscriptores. Por ejemplo, cuando la Game Boy le manda NEW_POKEMON e inmediatamente informa a los procesos Game Card de dicho evento. 
_**Servidor:**_ para poder recepcionar los eventos, por ejemplo como mencioné arriba un NEW_POKEMON.

## Game card
_**Cliente:**_ cuando manda por ejemplo un APPEARED_POKEMON.
**Servidor:** al estar suscripto a ciertas colas, es servidor del Broker (y también de la Game Boy al poder recibir mensajes de ella).
 
## Teams
_**Cliente:**_ cuando manda por ejemplo un GET_POKEMON.
_**Servidor:**_ para poder recibir mensajes como APPEARED_POKEMON.

## Game Boy
_**Cliente:**_ al trabajar como publisher (ingresa mensajes al sistema) es cliente de los demás módulos, según a quién le mande un mensaje.
_**Servidor:**_ NUNCA.

**Comment by papa-caco** [comment]
Hola Ezequiel, cómo estás?

Fuimos compañeros en de cursada en DDS el año pasado y ahora acá recursando S.O.
A mi modesto entender, el Broker cumple el rol de Servidor todo el tiempo. Comparto el párrafo de   Lineamiento e Implementación de la página 11 del enunciado, un poco resumido:

"Broker: Esperará las solicitudes de los distintos módulos para asociarse a las colas que él administra. Cada uno de los clientes/módulos se deberá comunicar con él indicando la cola a la que se desea suscribir. El Broker dispondrá de una lista de suscriptores por cada cola que administre. En otra instancia de tiempo, un mensaje llegará con el destino a dicha cola de mensajes. El Broker distribuirá dicho mensaje a los suscriptores."

En resumen, si bien el Broker distribuye mensajes a sus suscriptores, estos han establecido una conexión con el Broker previamente (como clientes) indicándole, Voy a suscribirme a la Cola QueueX.
Esa es mi apreciación, espero no confundirlos...
Éxitos!!

Carlos Comesaña.

**Comment by EzeDiaz** [comment]
Hola Carlos! Espero que estés bien. Tiene sentido lo que decís, lo que me hace ruido es el tema del asincronismo. Porque si es de un instante a otro sí me resulta familiar la idea de que sólo es servidor. En cambio, como los suscriptores reciben notificaciones a futuro y varias, la idea de pedido-respuesta me resulta más difusa. Quizás es una confusión meramente lingüística y nuestros corazones están en el lugar correcto.

**Comment by afilgueira** [comment]
Buenas Ezequiel! esta es una excelente excelente excelente pregunta para arrancar la charla con l@s ayudantes que les vamos a asignar en un par de días, y hablar un rato en discord o algún medio que les resulte mejor.

El tema de cliente - servidor es circunstancial. Pensalo por el lado de quién se queda escuchando sin hacer nada y quien inicia conversaciones.

**Comment by Nachiten** [comment]
> Buenas Ezequiel! esta es una excelente excelente excelente pregunta para arrancar la charla con l@s ayudantes que les vamos a asignar en un par de días, y hablar un rato en discord o algún medio que les resulte mejor.
> 
> El tema de cliente - servidor es circunstancial. Pensalo por el lado de quién se queda escuchando sin hacer nada y quien inicia conversaciones.

Quiero hacer una apreciacion/consulta con respecto a ese comentario.

Si o si cada modulo de este TP tendria que ser o cliente o servidor? Existe la posibilidad de que se cambie de roles?

Lo que mas entiendo hasta ahora con todo lo que leí es que el señor BROKER centraliza un monton de cosas que tiene que hacer internamente (tiene muchisimas responsabilidades). Y entabla "conversaciones" directas tanto con gamecards como con teams. Los cuales basicamente se comunican indirectamente a travez de él.

**Comment by afilgueira** [comment]
Buena consulta. Cada módulo hace de cliente o servidor en diferentes momentos. Probablemente encuentren que alguno es solo cliente y que alguno es solo servidor, pero es totalmente factible cambiar de roles.

**Comment by nahuemazzeo** [comment]
Hola!! Me sumo un poco a @afilgueira dando una mano en la conceptualizacion de esto.

@Nachiten @EzeDiaz 
Tengan en cuenta que para definir quien es servidor y quien es cliente deben pensar quien es el que inicia la conexión con quien, no quien es el que envía el primer mensaje en determinado momento. El servidor es aquel que va a estar esperando que alguien se conecte a el mientras que el cliente es el que sabe a donde se tiene que comunicar y con quien.
En base a esto y a los archivos de configuracion de ejemplo muchas cosas pueden entenderse rapidamente.

**Comment by afilgueira** [comment]
@EzeDiaz te sirvió esta info? Pudiste solucionar tu consulta?

**Comment by EzeDiaz** [comment]
Sí! Quedó más claro. Ya podemos cerrar el issue; cualquier cosa lo volvemos a abrir ☺️.
