### ISSUE TITLE
El servidor no muestra en pantalla el mensaje

### ISSUE THREAD

**Issue by guidoenr4** [sisoputnfrba/foro#1628]
Ya hice todos los pasos para seralizar un string y cuando levanto el servidor del gameWatch-server y ejecuto el main, no me da respuesta. Simplemente eso, les muestro mis funciones por si lo quieren probar; no se en que me estoy confundiendo , no me da ningun error la consola ni ningun warning.

**serializar_paquete**
```
void* serializar_paquete(t_paquete* paquete, int *bytes) // 
{
	t_buffer* buffer = malloc(sizeof(t_buffer));
	buffer->size = sizeof(paquete->buffer->stream);

	void* stream = malloc(buffer->size);
	int offset = 0;

	memcpy(stream + offset, &(paquete->buffer->stream), sizeof(paquete->buffer->stream));
	offset += sizeof(paquete->buffer->stream);

	buffer->stream = stream;

	paquete = malloc(sizeof(paquete));
	paquete->codigo_operacion = MENSAJE;
	paquete->buffer = buffer;

	void* a_enviar = malloc(buffer->size + sizeof(op_code));
	int sndoffset = 0;
        memcpy(a_enviar + sndoffset, &(paquete->codigo_operacion), sizeof(op_code));
	sndoffset += sizeof(op_code);
	memcpy(a_enviar + sndoffset, &(paquete->buffer->size), sizeof(int));
	sndoffset += sizeof(int);
	memcpy(a_enviar + sndoffset, paquete->buffer->stream, paquete->buffer->size);
	return a_enviar;

	free(a_enviar);
	free(paquete->buffer->stream);
	free(paquete->buffer);
	free(paquete);
}
```

**deserializar_mensaje**
```
typedef struct {
    int mensaje_lenght;
    char* mensaje;
} t_mensaje;

t_mensaje* deserializar_mensaje(t_buffer* buffer){
    t_mensaje* mensaje= malloc(sizeof(mensaje));

    void* stream = buffer->stream;
    memcpy(&(mensaje->mensaje_lenght), stream ,sizeof(int));
    stream += sizeof(int);
    memcpy(&(mensaje->mensaje), stream, mensaje->mensaje_lenght);
    stream += mensaje->mensaje_lenght;


    return mensaje;
}

```
**enviar_mensaje** 
```
void enviar_mensaje(char* mensaje, int socket_cliente)
{
	t_paquete* unPaquete = malloc(sizeof(t_paquete*));
	unPaquete->codigo_operacion = 1;
	unPaquete->buffer->size=sizeof(mensaje);
	unPaquete->buffer->stream = mensaje;

	void* a_enviar = serializar_paquete(unPaquete,unPaquete->buffer->size);
	send(socket_cliente,a_enviar, unPaquete->buffer->size + sizeof(int), 0);

	free(a_enviar);
	free(unPaquete->buffer->stream);
	free(unPaquete->buffer);
	free(unPaquete);

}

```

**recibir_mensaje**
```
char* recibir_mensaje(int socket_cliente)
{
	t_paquete* paquete = malloc(sizeof(paquete));
	recv(socket_cliente,&(paquete->codigo_operacion),sizeof(op_code),0);
	recv(socket_cliente, &(paquete->buffer->size), sizeof(int), 0);
	recv(socket_cliente, &(paquete->buffer->stream), paquete->buffer->size, 0);

	op_code CODIGO = paquete->codigo_operacion;
	t_mensaje* unMensaje = deserializar_mensaje(paquete->buffer);

	printf("%d",unMensaje->mensaje);
	return unMensaje->mensaje;

	free(paquete->buffer->stream);
	free(paquete->buffer);
	free(paquete);

}
```

**Comment by mgarciaisaia** [comment]
👋 ¡Aloha!

> no se en que me estoy confundiendo , no me da ningun error la consola ni ningun warning.

_Creo entender_ que tu problema es que el server no imprime ningún mensaje por pantalla, ¿verdad?

Si ese es el caso, el error está en la expectativa: el código del server _en ningún momento intenta imprimir_ el mensaje que recibe. Por cómo está planteado el TP0, es responsabilidad de tu programa cliente imprimir por pantalla el mensaje que recibió desde el server.

Si el problema está por el lado del cliente, hay varios errores ahí a mano en `recibir_mensaje`. Si el compilador no te está dando ningún warning, quizá sea que no le estás pidiendo que te avise. Al compilar con `gcc`, deberías pasarle el parámetro `-Wall` para que notifique TODOS los warnings, y probablemente también te sirva agregar `-Werror`, para que los warnings se traten como errores _y entonces directamente falle la compilación_ en lugar de compilarte algo con warnings. El comando terminaría siendo algo como `gcc -Wall -Werror tp0.c -o tp0`.

Algo que [`gcc` no te avisa](https://stackoverflow.com/a/21240321) pero igual estás haciendo mal es ejecutar cosas después de un `return`. Los `free` que hacés después de un `return` **no se van a ejecutar**, justamente porque el programa sale de la función al hacer `return`, y entonces nunca ejecuta las líneas que le siguen.

Pero, antes de eso, cuando hacés `recv(socket_cliente, &(paquete->buffer->size), sizeof(int), 0);`, por ejemplo, `paquete->buffer` está apuntando _a cualquier lado_. Sólo reservaste lugar para `paquete` con tu `malloc`, y nunca inicializaste el valor de `paquete->buffer`. Eso va a hacer que el programa se comporte de maneras aleatorias, porque vas a estar escribiendo memoria que no reservaste (`paquete->buffer` va a tener _cualquier valor_, entonces cuando escribas `paquete->buffer->size` vas a estar escribiendo en cualquier lado, pisando memoria).

Pegale una revisada a los warnings y fijate qué está pasando. El video de [reportar errores de Eclipse](https://faq.utnso.com.ar/errores-eclipse) te puede ayudar, también.

**Comment by mgarciaisaia** [comment]
¿Cuál era, che? No me mates de intriga.
