### ISSUE TITLE
Duda C, common lista y scanf

### ISSUE THREAD

**Issue by foviedo** [sisoputnfrba/foro#1629]
Buenas! Estuve intentando hacer unos ejercicios de la guía de C que está en utnso, así aprendo a usar algunas commons. 
Ejercicio 1.1 (Manejo de listas)
Una librería necesita conocer los libros que tiene disponibles. Para ello, lleva cargados en memoria los títulos de las diferentes obras que tiene disponible (no existen dos libros con el mismo nombre).
Mediante el comando: “ListarLibros” se debe imprimir en pantalla los datos de cada obra.
Mediante el comando: “CargarLibro [Nombre]” se debe agregar a la lista de obras a [Nombre]

```
#include<stdio.h>

#include <stdlib.h>
#include <commons/collections/list.h>
void list_mostrar(t_list* lista){
	int i = 0;
	char* elemento;

	for(i=0;i<lista->elements_count;i++){
		elemento = list_get(lista,i);
		puts(elemento);
	}
}

int main(void) {
	int input;
	t_list* libros = list_create();
	//list_add(libros,"a");
	//list_add(libros,"b");
	//list_add(libros,"c");
	//list_add(libros,"d");
	//list_add(libros,"e");
	puts("Ponga 1 para mostrar los libros, 2 para cargar");
	while(true){
	scanf("%i",&input);
	if(input == 1){
		list_mostrar(libros);
	} else if(input == 2){
		puts("Ingrese nombre: ");
		char* s1;
		scanf("%s",s1);
		list_add(libros, s1);
	}
	}
	return EXIT_SUCCESS;
}

```
Ahora mi problema: cuando hago list_add, por separado, funciona perfectamente, ahora, si trato de hacerlo desde el while, noto que, habiendo debugeado, cada vez que hago un list_add, se me añade el último elemento que ingrese a s1 en toda la lista, osea, si añado un "libro1", la lista queda: ["libro1"], si añado otro elemento "libro2", la lista me queda ["libro2","libro2"] y así sucesivamente, no estoy seguro de qué es lo que puede estar andando mal pero calculo que tiene que ver mucho con el scanf. La ayuda será agradecida!

**Comment by mgarciaisaia** [comment]
@foviedo el tema es que acá nos estás mostrando el código que _sí_ funciona :)

¿Nos mostrás el otro?

**Comment by foviedo** [comment]
Ahí comenté las líneas hardcodeadas

**Comment by mgarciaisaia** [comment]
Ahí entendí.

Le pegaste a un error súper común de cuando estamos aprendiendo a manejar memoria manualmente.

Tan común, que hice un video para la posteridad: https://youtu.be/k1ctm9TcmVE

Gracias por la inspiración, y ojalá sirva :)

**Comment by foviedo** [comment]
Clarísimo! Muchas gracias
