### ISSUE TITLE
lectura erronea al leer el string después de serializar

### ISSUE THREAD

**Issue by flamas472** [sisoputnfrba/foro#1630]
buenas, pude avanzar bastante con el TP0 y llego a un punto en que tengo el siguiente problema:
para empezar, lo que pude comprobar que si anda:
el string que envio (se recibe por consola), llega correctamente hasta el empacetado, es decir, despues de empaquetar los datos en "t_paquete paquete" sigo pudiendo leerlo.
tengo un printf de la siguiente manera
- printf("\nse empaqueto el stream: %s\n", (char*)paquete->buffer->stream); -
para que se muestre correctamente lo castie como un (char*), y muestra el texto escrito con el mensaje que se ingrese por consola al inicio.
sin embargo, noté que tras enviar el paquete, y recibirlo, se leia mal, puse logs por varios lados (servidor incluido) y llegué a la conclusión de que el error está en la zona del memcpy(3) que uso al momento de serializar, concretamente al copiar la seccion del stream, porque el size del buffer y el código de operación se copian correctamente.
intenté inyectar manualmente el centinela '\0' sin resultados.
dejo un repositorio donde lo subi así es más facil revisarlo a quien pueda ayudarme ;D

https://github.com/flamas472/utnsoTP0

el error, confio que está concretamente en utils.c:
https://github.com/flamas472/utnsoTP0/blob/master/utils.c

además, puede observarse que al final del main del archivo principal, la funcion para finalizar y limpiar la tengo comentada, me tiraba unos errores en rojo medio raros, por eso está así, todavía no lo investigué del todo, estoy concentrado en poder enviar el mensaje correctamente y así poder revisar si larecepcion la estoy haciendo bien.

PD: puede ser que esté medio feucho el código, cualquier sugerencia acerca de buenas prácticas es bienvenida :D
intenté abstraer un par de funciones y me dio errores asique de apurado, termine no abstrayendo nada y usando solo las provistas por el TP, las que tienen el //TODO

Saludos
Muchas gracias

**Comment by mesaglio** [comment]
Buenas, revisando un poco el codigo pude encontrar lo siguiente: 
`memcpy(aEnviar + offset, &paquete->buffer->stream, paquete->buffer->size);`
Recordando un poco la funcion memcpy `void *memcpy(void *dest, const void * src, size_t n)`, copia los primeros `n` bytes del contenido del puntero `src` en el contenido del puntero `dest`.
Entonces volviendo a tu codigo en el segundo parametro del memcpy tu variable 
`paquete->buffer->stream` ya es un puntero. Al agregarle & a un puntero, hacemos referecia al puntero del puntero.
Creo que viene por aca. Cualquier duda podes comentar abajo.
Saludosss

**Comment by flamas472** [comment]
ahi anda!
muchas gracias, en ningún momento se me ocurrió eso, y tiene un motivo.
ese memcpy es el tercero dentro de esa función, y lo que me confunde, que si me pueden aclarar sería genial es que:
en el primer memecpy, si no pongo el & me tira error en el segundo parámetro,

y en el segundo memcpy, si no pongo el & me tira un warning. . .

en el primero - memcpy(aEnviar + offset, &paquete->codigo_operacion, sizeof(op_code)) -
el código de operación es un size of sin (*), es por esto que no es un puntero? a pesar de que paquete y buffer si lo sean?
el segundo sin el &, rompe en ejecución, compila, pero no anda.
y el tercero va sin el &, algo me queda por terminar de entender de punteros 😄 

gracias por la ayuda, ahora tengo el TP0 terminado 🥳 (salvo el logger que lo estoy haciendo)

**Comment by nahuelPascual** [comment]
En el primero, `codigo_operacion` es un dato. Vos necesitás desreferenciarlo, escribiendo `&codigo_operacion`, para obtener la dirección de memoria (puntero) a ese dato.
Y, acá no estoy tan seguro pero, creo que el comportamiento del segundo y tercero va a ser aleatorio por estar trabajando con punteros que no son los que querías. Al hacer `&puntero` estás trabajando con la dirección del puntero (puntero del puntero), así que estás trabajando en una porción de memoria que no es la que vos querías; entiendo que mientras escribas menos 4 bytes (tamaño del puntero en arquitectura de 32bits) no va a explotar pero vas a estar teniendo un comportamiento poco feliz porque nunca guardaste el dato donde vos creés que lo guardaste. En caso de querer escribir más, podés tener un memory leak por pisar espacio de memoria que no te corresponde.
Espero haber sido claro, y que alguien me corrija si dijo algo mal.

**Comment by mgarciaisaia** [comment]
Fijate si esta obra de arte te termina de ilustrar lo que comenta el bueno de @nahuelPascual:

![Esquema de las estructuras en memoria, mostrando cómo paquete y buffer son punteros a datos, mientras que codigo_operacion es el dato en sí mismo](https://user-images.githubusercontent.com/1190974/79007707-176fb700-7b32-11ea-9919-1dc16f541b8e.png)

`memcpy` espera que le pases el puntero a los bytes que tiene que copiar.

Si le pasás `codigo_operacion`, le estás pasando un `1` - lo interpreta como puntero e intenta leer la posición de memoria `0x1`. Si le pasás `&codigo_operacion`, le das `0xbba5ad` (o _el que sea_ el puntero a `codigo_operacion` en tu ejecución), y puede acceder a esa dirección de memoria para encontrar el `1`.

Si le pasás `buffer`, le estás dando un puntero a dónde encontrar la `h` de `"hola"`. Si le pasás `&buffer` le estás dando el puntero al primer byte de `buffer`, y `memcpy` va a leer el valor `0x75ab5`.

**Comment by flamas472** [comment]
Excelente, clarísimo.
Pero soy medio duro, creo haberlo entendido, pero me surgió otra cosita, espero que la última jaja.
en el final del programa, en la función de limpieza, si no le pongo el & al config_destroy me tira unos errores en rojo
![image](https://user-images.githubusercontent.com/38506952/79032674-b91cf580-7b7e-11ea-9ff0-79ccf1ac631e.png)
(no me anda el portapapeles compartido asique lo pego como imagen).
la funcion terminar_programa, para que no me tire errores me quedó así, probé uno por uno cual funcionaba sin &.
void terminar_programa(int conexion, t_log* logger, t_config* config)
{
	liberar_conexion(conexion);
	printf("Conexion liberada.\n");

	log_destroy(logger);
	printf("Logger destruido.\n");

	config_destroy(&config);
	printf("Config destruido");
	//Y por ultimo, para cerrar, hay que liberar lo que utilizamos (conexion, log y config) con las funciones de las commons y del TP mencionadas en el enunciado
}

está correcto así?
tanto config como logger están declarados como vectores (con el *), en ambas funciones el parámetro a recibir está declarado como puntero con *.

ya tengo el TP fubncionando, pero no me vendría mal entender un poco más sobre los punteros.
entiendo que con &config estoy pasando la dirección donde está guardada la direccion del struct config que declare, es decir, puntero del puntero 🤔? por lo que no me esperaba necesitar poner el &.
perdón por las molestias, gracias, me ayudaron mucho conlo anterior!

**Comment by mgarciaisaia** [comment]
No debería hacer falta pasarle el `&config` 🤔

Pegale una pasadita con [`valgrind`](https://faq.utnso.com.ar/valgrind), a ver qué onda.

**Comment by afilgueira** [comment]
Sirvió esto @flamas472? Saludos!

**Comment by tferraro** [comment]
Si el error todavía persiste, plz @flamas472 abrilo de nuevo, ahí ni dudes.
Pero para que no se acumulen issues en el foro y generen ruido, cierro el issue por inactividad 👮‍♂️
