### ISSUE TITLE
Can´t find sourcefile

### ISSUE THREAD

**Issue by MarcosInfantino** [sisoputnfrba/foro#1631]
Hola! El Eclipse me está tirando este error, alguien con una idea de a qué se debe?
![git1](https://user-images.githubusercontent.com/49456888/79016904-7dfed000-7b46-11ea-9995-4564563252d8.png)

**Comment by mgarciaisaia** [comment]
[Busque, busque](https://github.com/sisoputnfrba/foro/search?q=can%27t+find+source+file&unscoped_q=can%27t+find+source+file&type=Issues).
