### ISSUE TITLE
uso de select con socket

### ISSUE THREAD

**Issue by trictor** [sisoputnfrba/foro#1632]
Hola cuando utilizo select para monitoriar los socket, el programa sigue bloqueado a pesar que le mande datos  
![WhatsApp Image 2020-04-11 at 12 39 27](https://user-images.githubusercontent.com/37601029/79048186-a4c61080-7bf1-11ea-943f-c80ff3ffaab9.jpeg)

**Comment by tferraro** [comment]
👋 Buenas!
Dos cosillas que veo a primera vista.
Como primera instancia, el tp **no usa select** en ninguna de las implementaciones de los módulos, así que...problema...solucionado?

Por el otro, voy a ser _assertivo_ en pedirte que seas **lo más expresivo que puedas en los issues del foro**. Desde cosas que intentaste, mensajes de error, explicación de funciones intermedias, código en texto y no como solamente imágen (ahí podes aprovechar el modo código con las <> del editor), etc.
Toda info que esté dada de antenamo ayuda banda a evitar "idas y vueltas" de información, intentar cosas que ya no van a tener sentido y, más importante, indexar bien los probemas en el buscador del foro 🙂


--------------------------------------------
PD: Si a alguien le interesa la naturaleza del issue, pueden mirar en la docu del [select](http://man7.org/linux/man-pages/man2/select.2.html) y ver el primer parámetro que estamos usando allí: nfds = "3".
En la docu, el nfds nos da el _máximo nro de File Descriptor que vamos a tener en los sets_ del select, más uno. La ironía es que los primeros 3 file descriptors están ocupados por stdin: el input del teclado (0), stdout: la pantalla (1), stderr: canal para mostrar errores (2). Por lo que setearlo en 3, podría generar un comportamiento de "bloqueo" como el que estás viendo 😉

**Comment by trictor** [comment]
hola entonces debería poner en el primer parámetro del select (cliente2 +1) donde cliente2 es el numero de file descriptor mas grande?
y luego como continuo el codigo para el servidor pueda manejar multiples mensajes de distintos clientes
ej
el cliente1 le manda al servidor el mensaje hola luego casa luego el cliente2 le manda el mensaje utn al servidor luego vuelve el cliente1 a mandarle hola

como puedo lograr ese comportamiento

en cuanto a su uso en el tp tenia pensado usar select en el proceso broker para manejar los mensajes entrantes de los otros dos procesos

**Comment by afilgueira** [comment]
Hola, deberías guardarte una lista de los clientes que tenés abiertos y ya.

Respecto al uso del select para el TP, pensalo de esta forma: si el broker recibe N mensajes, el primero muy muy muy largo de contestar, y el resto muy muy cortos pero importantes... que pasa con esos últimos mensajes? De ahí la idea de que no usen select.

Por esto que el enunciado del broker dice:
```
Esta funcionalidad deberá ser implementada por medio de multi-hilos. Esta arquitectura permitirá al Broker poder enviar y transaccionar mensajes en simultáneo a los distintos suscriptores
```

Saludos!

**Comment by trictor** [comment]
gracias entonces lo intento con hilos
