### ISSUE TITLE
consulta sobre archivo de configuracion.

### ISSUE THREAD

**Issue by emarcosgv** [sisoputnfrba/foro#1633]
hice una estructura que tiene como atributos los campos que tengo que levantar del archivo de config.

Si declaro campo por campo globalmente me funciona, pero si uso la estructura no.

```c
typedef struct{
    int *puertoBroker;
} t_configBroker
t_configBroker *config
```

en el .c escribo `config->puertoBroker = config_get_int_value(configTBROKER, "PUERTO_BROKER");`

hago esto y no va. Donde esta el error?

Si yo declaro una variable global y hago `configPuertoBroker = config_get_int_value(configTBROKER, "PUERTO_BROKER");` y hago esto si funciona. Gracias.

**Comment by mgarciaisaia** [comment]
Hola @emarcosgv.

¿Qué cosas ves que te dan la pauta de que "no va" o que "sí funciona"? ¿Qué mensaje de error o resultado no esperado te da el programa? ¿En qué momento? Toda esa información es súper necesaria para entender qué te está pasando. Con lo que contás, lo único que podemos hacer es _adivinar_ qué está pasando. Que, en este caso, es relativamente trivial de entender (creo), pero que en otro caso podría ser más complejo. Y, de nuevo: en este caso, _creo_ que puedo saber qué pasa. Capaz me paso media hora como un boludo escribiendo la solución al problema incorrecto. Tratá de mejorar el reporte la próxima, porfa.

---

En tu código, ¿qué es `config`? ¿De qué tipo de datos es?

En C, las variables globales, los parámetros, y las variables locales a una función son casos de _memoria automática_: el compilador se encarga de reservar la memoria necesaria para usarlas.

Como tu variable `configPuertoBroker` es, estimo, una variable global que declaraste como `int configPuertoBroker;` en una línea de código fuera de toda función (_fuera del `main`_, digamos), el compilador te reserva los (seguramente 4) bytes de memoria que necesita para poder guardar un `int`.

Ahora bien, ¿qué pasa con `config`? ¿De qué tipo de datos es? ¿Y `puertoBroker`?

`puertoBroker`, ¿es una variable local? ¿Es local? ¿Es un parámetro? _¿Qué es `puertoBroker`? ¿Qué relación tiene con `config`?_

**Comment by emarcosgv** [comment]
Ya lo solucione, me faltaba hacerle un Malloc a la estructura, gracias. Era algo puntual mío, por eso intenté por discord antes. Igualmente voy a leer la manera de cosultar para la próxima. Gracias

**Comment by mgarciaisaia** [comment]
Ni tanto, eh. "Me olvidé de reservarle memoria a la estructura que quiero apuntar" es lo suficientemente común como para tirarlo por acá :)
