### ISSUE TITLE
Consulta enunciado, archivo de configuración.

### ISSUE THREAD

**Issue by Santiago-Lovelli** [sisoputnfrba/foro#1634]
Buenas, en el enunciado dice que el GameBoy se deberá conectar con todos los otros procesos, por lo que entiendo que todos deben ser servidores para el GameBoy, por lo tanto:
¿No tendrian que tener todos un puerto e ip de servidor; por lo que le tendriamos que agregar al GameCard y al Team un PUERTO_GAMECARD, IP_GAMECARD y un PUERTO_TEAM, IP_TEAM; respectivamente?

**Comment by iago64** [comment]
Buenas buenas!
Buena pregunta che, si me permitís, te contesto con otra pregunta. 

Alguna vez les dijimos que no pueden agregar cosas a los archivos de config? 😉 😉  

Abrazo.-

**Comment by Santiago-Lovelli** [comment]
Otra buena pregunta. Y no, nunca nos dijeron que no, así que me voy a tomar la libertad de agregarlo jajaja, gracias caballero :wink: :wink: :wink:
