### ISSUE TITLE
dudas proceso team

### ISSUE THREAD

**Issue by trictor** [sisoputnfrba/foro#1635]
hola tengo dudas con algunas partes de enunciado
1)Al iniciar el proceso, se deberá crear un hilo por cada entrenador existente. esos hilos se refrieren a hilos de pthread.h o una estructura que nosotros creamos para simular el comportamiento de un hilo? siguiendo con eso los estados new ready blocked y exit son estados que deben ser representados por listas para decir " en este momento hay estos entrenadores bloqueados y estos entrenadores en ready" o no requiere ser representado
2) si un entrenador no puede capturar mas pokemon pero no cumplió con su objetivo en que estado debe estar?
3)el mensaje appeard pokemon debe traer a todos los pokemon que el proceso team necesita o solo uno?
4)que tan grande es el mapa de dos coordenadas? hay un espacio maximo o puede ser infinito
5) que diferencia hay entre appeard pokemon y get pokemon?
6) como se tratan cuando hay múltiples procesos team? todos los procesos team trabajan sobre un mismo mapa o cada team sobre un mapa distinto?

**Comment by ncoen97** [comment]
Buenas! Vamos por partes.
Los hilos que representan a cada entrenador son los de pthread, cada uno de estos va a "representar" a cada entrenador y ejecutar cuando esté en el estado exec. Los estados son la forma que tenemos de planificar nuestros procesos (en este caso entrenadores) por lo tanto si, tenes que saber cuales están en cada estado.
Si un entrenador no puede capturar mas pokemon pero no cumplió con su objetivo, quiere decir que fue a atrapar un pokemon de otro entrenador de ese team. Si tenes dudas sobre esto podes buscar en el enunciado donde se habla de los intercambios.
Con respecto a el appeard pokemon y get pokemon, fijate qué modulo los envía y con qué objetivo.
El mapa de coordenadas no tiene un "espacio", no es algo que vos creas o instancias, sino que vas a "simularlo" mediante tus teams y game card. Con respecto a esto, teams trabajan todos sobre el mismo mapa.
Cualquier cosa que no te cierre podés seguir preguntando.
Saludos.

**Comment by trictor** [comment]
hola
 si son hilos de pthread, como yo puedo planificarlos ya que el propio SO tiene su algoritmo de planificacion?
ademas cuando yo creo muchos hilos todos empiezan a ejecutar simultáneamente y no solo uno como dice el enunciado. como puedo lograr ese comportamiento? con semáforos?
si los estados son listas de hilos siguiendo el mismo problema de arriba como puedo mantenerlos en espera?

**Comment by afilgueira** [comment]
Hola, esa es una EXCELENTE pregunta! 

Pensá que como programador podés hacer que ciertos hilos ejecuten y que otros queden en espera (usando algunas syscalls bloqueantes). Además podrías tener alguna estructura tuya que se parezca a un TCB y te permita saber en qué estado está cada uno. De esta forma podes emular un algoritmo de planificación.

Saludos!

**Comment by trictor** [comment]
como haría eso que me decís?(cuales son esas syscall ) porque en el momento que los creo empiezan a ejecutar todos.
otra duda que tengo cual es el beneficio de trabajar con hilos si solo un hilo de todos va a estar ejecutando se pierde el sentido por el cual fueron creados no seria mejor trabajar con estructuras que se parezcan a hilos como vos decís?

**Comment by afilgueira** [comment]
Las sycalls pueden variar, dependiendo de lo que estés haciendo en ese momento, pero en principio pueden ser reads por socket, semáforos y seguro alguna más que me olvido.

Lo de trabajar con hilos, si bien es cierto que uno va a estar "en ejecución", los otros pueden estar haciendo cosas (por ej, simulando entradas salidas).

**Comment by trictor** [comment]
con lo que leí en la documentación de team los entrenadores que no están en ejecución no hacen nada por lo tanto sigo teniendo hilos que esperan a ser ejecutados

**Comment by afilgueira** [comment]
Excelente. En este caso en particular vos (técnicamente, el enunciado dice que no lo hagas) podrías manejar todos los entrenadores con un mismo hilo. Pero esto te implicaría tener que programar un montón de funciones que te permitan cambiar el contexto de entrenador en entrenador. 

Lo bueno de usar un hilo por cada entrenador es que te simplifica: cada hilo sólo necesita "ejecutar" sin preocuparse por nada más y tu planificación consiste únicamente en bloquear y desbloquear hilos para que esto ocurra.

Por otro lado, vos podés crear hilos a los que le pasas una función y parámetros. En base a eso podés crear diferentes hilos que hagan lo que necesites.

Saludos!

**Comment by trictor** [comment]
hola si yo tengo una variable pthread_t puedo usar esa misma variable para crear muchos hilos?
otra pregunta cuando te referís usar hilos te referís a una variable usar una variable pthread_t o usar pthread_create?

**Comment by tferraro** [comment]
@trictor depende mucho de como configures tus hilos. Si son hilos que _tienen que ser "joineados"_, entonces necesitás la referencia para joinearlos.

En otros casos, como los hilos "detachables", los hilos se autogestionan por sí solos, así que no habría necesidad de mantener la referencia; a menos que quieras hacer algun estilo de gestión sobre los hilos activos.

Si estas palabras en comillas no dijeron mucho 😛 , pegue una buscada rápida en google y encontré este post bastante bueno explicando las diferencias entre estas 2 clases de hilos: https://thispointer.com/posix-detached-vs-joinable-threads-pthread_join-pthread_detach-examples/

**Comment by FedeMacias** [comment]
Hola, entonces si mal no entiendo un entrenador es un hilo, que no hace ninguna funcion (talves sea solo una variable pthread_t) hasta que pasa a exec. Cuando pasa a exec vos le asignas una funcion (ponele, capturarPokemon), y cuando sale de exec vos bloqueas el hilo para que no siga ejecutando? Lo estoy pensando masomenos bien?

**Comment by trictor** [comment]
en definitiva el proceso team es un proceso multihilo donde cada entrenador va a ser un hilo y todos esos hilos solo uno va a estar en ejecución y los demás van a estar trabados con alguna syscall que todavía no se. aun no comprendo porque se plantea la utilización de muchos hilos cuando solo cuando solo uno va estar activo, una implementacion mas  fácil no seria como dice fede
dejando de lado los hilos el enunciado dice que se planificara el entrenador mas cercano al pokemon que apareció pero luego habla que hay que planificar con FIFO RR o SJF pero puede llegar a ocurrir que el entrenador primero en la lista de ready no sea el mas cercano entonces como hago ?

**Comment by afilgueira** [comment]
Hola, la syscall que todavía no conoces son básicamente semáforos. Podés investigar un poco sobre los de pthread y similares. Lo de una implementación más fácil o difícil, obviamente es subjetivo. Por ahora confía en nosotros y pensá cómo hubiese sido si lo implementabas "a tu manera". Es una gran charla de coloquio 😄 

Si el entrenador que esta primero en la lista no es el que dice tu algoritmo, tu lista no está ordenada. Podés ordenarla, o bien recorrerla completa y elegir el siguiente en base al algoritmo. Esta es la parte que queremos que programen.

Saludos!

**Comment by trictor** [comment]
lo segundo que me pusiste no resuelve mi duda el enunciado dice que el entrenador a planificar, es decir, a mover es el mas cercano al pokemon que apareció, luego dice que tengo que planificar según los algoritmos vistos en la cátedra ahora puede ocurrir que con el algoritmo FIFO el siguiente a ejecutar no sea el mas cercano al pokemon que apareció

**Comment by afilgueira** [comment]
Hola, hagamos una cosa, porque este hilo se está volviendo difícil de seguir. Las dudas que aún te quedan, subilas por favor en preguntas separadas (de a una por issue), así podemos ir viéndolas en paralelo y no se pierde nada. Porfa lee https://github.com/sisoputnfrba/foro#c%C3%B3mo-usarlo, así nos organizamos y te contestamos todo lo que no cierre.

@FedeMacias lo mismo aplica para tu caso. 

Cierro mientras tanto, pero esperamos sus issues. Saludos!

**Comment by afilgueira** [comment]
@trictor @FedeMacias esperamos sus issues si todavía estas dudas siguen ahí! Saludos!
