### ISSUE TITLE
[GAMECARD] Metadata.bin

### ISSUE THREAD

**Issue by cesarmateos** [sisoputnfrba/foro#1636]
Tengo dudas en como tratar los archivos Metadata.bin  . La extensión bin me indica que debería tratarlo como un binario,  pero al ver los ejemplos parecieran ser archivos de texto, muy parecido (o igual) al formato .config.

**Preguntas:**

1. ¿ Los tratamos como binarios, o como de texto ?
2. ¿ Cuando hagan los tests, ustedes van a tener su propio [Punto_Montaje]/Metadata/Bitmap.bin con un FS particular configurado, o sea que el GAMECARD que programemos deberá poder leer las etiquitas y sus valores y actuar en consecuencia ? 
3. Interpreto que antes de arrancar GAMECARD el Bitmap.bin ya tiene que estar creado, o crear uno vacío si es que no existe.

**Comment by ncoen97** [comment]
Buenas.
1. Lo pueden tomar como quieran, ya que la extensión no los limita en nada, les recomiendo que lo hagan como texto.
2. No se a que te referís con "etiquetas" y "valores", pero el filesystem tiene que poder levantarse "desde cero" para cuando sea la primera vez que se ejecuta el proceso game card o también levantar un filesystem ya inicializado, siempre con el formato indicado en la consigna del TP.
3.  Ni, si el bitmap no esta creado se inicializa "vacío" pero realmente no está vacío, ya que va a haber algunos bloques tomados por el filesystem desde el inicio .
Saludos!

**Comment by cesarmateos** [comment]
Gracias por tu respuesta.
Me quedan dudas con la tercera respuesta.  De leer el enunciado, yo interpretaba que en la estructura 1.bin, 2.bin....n.bin,  íban solo los datos de los pokemones, y los n bloques que especifica el FS eran solo para ese tipo de archivos.
¿ Debo tomar en cuenta en el Bitmap los Metadata.bin y resto de archivos del FS ?

**Comment by ncoen97** [comment]
Claro, yo ya me iba a la teoría. En este caso al tener la metadata y el bitmap dentro de la carpeta `[Punto_Montaje]/Metadata/`, los bloques referenciados por el bitmap serían únicamente bloques de datos. Disculpá la confusión.

**Comment by cesarmateos** [comment]
Ah perfecto.  Entonces el bitmap solo hará referencia a los bloques de datos de pokemones.  Bastante más sencillito que un FS real.
Gracias!

**Comment by ncoen97** [comment]
Si no tenes más dudas sobre esto te invito a que cierres el issue :)

**Comment by tferraro** [comment]
@cesarmateos que suecedió que reabriste el issue? 😊

**Comment by cesarmateos** [comment]
Perdón que reabra el Issue, pero me surgió una duda con respecto a la Metadata del FS.

Siento que hay algo poco claro, entre el momento de leer el config y de leer la metadata del FS. Me parece que sería mejor el Block_Size y el Blocks estuvieran seteados en el archivo config. 
Si yo voy a instalar un FS de cero ,leo el nuevo punto de montaje desde el config, pero ¿ De dónde saco las especificaciones del FS si la ruta/archivo "/PuntodeMontaje/Metadata/Metadata.bin" todavía no existe ?  
Tendría que poner los valores del Metadata desde mi código en el momento de compilación.

Creo que es obvio, pero por las dudas consulto ¿ ¨Blocks¨ es la cantidad de bloques máximos del FS, por lo tanto el tamaño del bitmamp ?


Gracias.

**Comment by ncoen97** [comment]
Buenas, te diría que por ahora no le des mucha bola a cómo les va a llegar la configuración del FS, seguramente mas adelante lo definamos bien y les hagamos llegar la información. Les recomiendo que mientras tanto (mas que nada para que puedan empezar a desarrollar) creen a mano el archivo de metadata con el ejemplo que está en el enunciado. Con respecto a los blocks, sí es la cantidad de bloques de datos maximos del FS y es el tamaño del bitmap.
Saludos!

**Comment by afilgueira** [comment]
Agrego una cosita: la razón por la que esto es así es porque _así lo hacen los File Systems de verdad_ (no exactamente igual, pero es una buena aproximación), y lo que buscamos es que simulen eso en este módulo.

Saludos!

**Comment by cesarmateos** [comment]
Perfecto.  Cierro, y espero que esta vez sea para siempre!
Gracias.
