### ISSUE TITLE
Consulta Pokemons atrapados y objetivo 

### ISSUE THREAD

**Issue by eGoicoechea** [sisoputnfrba/foro#1637]
Hola!
Estamos haciendo las funciones que reciben los mensajes del Team, y lo que nos surge la duda es con respecto a los pokemones atrapados y los objetivo. 
Cuando creamos un entrenador que tiene (por ejemplo) como objetivo 2 Pikachu y 1 Bulbasaur y atrapados 1 Pikachu y 1 Bulbasour. Cuando inicia el team,¿Necesita atrapar 1 Pikachu o 2 Pikachu y 1 Bulbasaur? ¿Tiene sentido volver a buscar los que ya tiene atrapados?
Muchas gracias
Emilia

**Comment by ncoen97** [comment]
Buenas.
Te respondo con una pregunta, cuándo van a crear un entrenador que ya tiene pokemons atrapados?

**Comment by eGoicoechea** [comment]
No se deberian inicializar cuando se crea el team?
Cuando empieza el team, creamos las estructuras entrenadores con los objetivos, la posicion de los entrendores y los objetivos de los entrenadores, entre otros valores. 
Si no no se me ocurre cuando voy a crear un entrenador, o como es el uso de Pokemones atrapados

**Comment by cristianicolasuarez** [comment]
Añado a la consulta de Emi, en el tp, en uno de los ejemplos de configuracion:
POSICIONES_ENTRENADORES=[ [1, 2], [3, 7], [5, 5] ]
POKEMON_ENTRENADORES=[[Pikachu, Squirtle, Pidgey], [Squirtle, Charmander],
[Bulbasaur]]
OBJETIVOS_ENTRENADORES=[[Pikachu, Pikachu, Squirtle, Pidgey], [Pikachu,
Charmander, Charmander], [Squirtle, Bulbasaur]]
Da a entender como que el primer entrenador, tiene en su poder un pikachu, un squirtle y un pidgey (se puede inferir que si los tiene es porque los atrapo en algun momento) si en sus objetivos tienen pokemons que ya tiene, tenemos que dar por hecho que esos que ya tienen sirven para cumplir los objetivos,  o que además de esos que tiene debe cumplir con los objetivos? Porque otra opción seria que esos que tiene los pueda intercambiar por los que necesita, pero no tiene mucho sentido cambiar un pikachu por otro pikachu :c 
Gracias!
Nico

**Comment by ncoen97** [comment]
Gracias @cristianicolasuarez, no recordaba la configuración.  Es así como vos planteas, si un entrenador ya posee un pokemon no tiene que volver a capturarlo (excepto que necesite más cantidad del mismo que ya tiene).

**Comment by cristianicolasuarez** [comment]
Muchas gracias!! @ncoen97 👍

**Comment by eGoicoechea** [comment]
Muchas gracias@ncoen97 @cristianicolasuarez

**Comment by eGoicoechea** [comment]
Buenas! Reabro el issue para consultar una cosa que mencionaste @ncoen97 mas arriba. 
Me habias preguntado cuando creamos los entrenadores que ya tienen pokemones atrapados. Esta bien si los inicializamos cuando comienza el team? En que casos no nos convendría no inicializarlo al comienzo? 

> Buenas.
> Te respondo con una pregunta, cuándo van a crear un entrenador que ya tiene pokemons atrapados?

**Comment by ncoen97** [comment]
Piensen que para que el Team empiece a trabajar tiene que saber qué/cuántos pokemones necesita, y esa información la sacan de los entrenadores :)

**Comment by eGoicoechea** [comment]
Genial, vamos bien entonces. Gracias!
