### ISSUE TITLE
Consulta sobre como importar la info del archivo de configuración, proceso Team

### ISSUE THREAD

**Issue by franpassa** [sisoputnfrba/foro#1639]
Hola a todos, subo este issue porque creo que a todos (o la mayoría) les pasa o les va a pasar lo mismo.
El problema es al querer leer el archivo de configuración (en mi caso, del proceso Team). Nosotros contamos en las commons con"char* config_get_string_value(t_config*, char *key)". Pero luego no encuentro una forma de separar las listas dentro de la lista que hay en la key ([[1,2],[3,7],[2,8]] o [[Pikachu,Charmander],[Bulbasaur]]).
Trate de usar "char  string_split(char * text, char * separator)",tambien de las commons, pero no me es de mucha ayuda ya que TODO esta separado por comas (tanto los elementos dentro de las listas como las listas en si). 
Se me facilitaria muchisimo poder modificar el archivo de configuracion poniendo simbolos distintos en la separacion de la key, por ejemplo [[Pikachu,Charmander]**;**[Bulbasaur]], de esa forma, uso string_split 2 veces y extraigo cada lista individualmente, esto se puede hacer?.
Programar una funcion que extraiga la lista dentro de la lista es bastante engorroso, espero que puedan ayudarme o que alguno lo haya solucionado y me de una mano, gracias!.

**Comment by mgarciaisaia** [comment]
Es muy buena la pregunta.

_Juraría_ que no vale la pena que se pongan a codear esa funcionalidad. Pero bancanos un toque que decidamos cómo solucionarlo.

Estimo que iremos por algo como `[1|2, 3|7, 2|8]`, o `[Pikachu|Charmander, Bulbasaur]`. Pero tenemos que decidirlo, aún.

¿Encontraste algún caso más complejo que esos?

**Comment by franpassa** [comment]
Por ahora no, solo me tope con que no tenia forma de sacar las listas de las listas. Específicamente de las keys siguientes:

POSICIONES_ENTRENADORES=[ [1, 2], [3, 7], [5, 5] ]
POKEMON_ENTRENADORES=[[Pikachu, Squirtle, Pidgey], [Squirtle, Charmander], [Bulbasaur]]
OBJETIVOS_ENTRENADORES=[[Pikachu, Pikachu, Squirtle, Pidgey], [Pikachu, Charmander, Charmander], [Squirtle, Bulbasaur]].

Gracias, espero alguna novedad al respecto.

**Comment by mgarciaisaia** [comment]
👋 Vamos a actualizar el enunciado en breve.

Por lo pronto, acá pueden ver cómo lo vamos a cambiar, y el _cacho'e código_ para parsearlo: https://gist.github.com/mgarciaisaia/8d1fe32cebdc16a3651a1a6e61364bef

**Comment by afilgueira** [comment]
@franpassa con la v1.1 del enunciado esto debería estar resuelto. Lo está? Saludos!

**Comment by franpassa** [comment]
Si, ya esta resuelto! 😄

**Comment by afilgueira** [comment]
Excelente, gracias por subir la consulta
