### ISSUE TITLE
No se puede encontrar so-commons-library

### ISSUE THREAD

**Issue by francofresno** [sisoputnfrba/foro#1640]
Hola, estoy teniendo problemas con las commons. En el TP0 no hizo falta hacer nada que ya andaban solitas siguiendo lo que está en el readme del repo de las commons. Ahora, al crear el proceso Broker, cuando las quiero utilizar, Eclipse no las encuentra al compilar. 
Creé también una shared library llamada nuestras-commons donde tengo algunas funciones repetitivas como las conexiones a sockets y demás que están siendo reconocidas por Eclipse.
Como no me funcionaban las so-commons, intenté linkearlas de igual manera que hice con nuestras-commons pero, _SPOILER_, obviamente no iba a ser tan fácil.

> Antes de continuar, paso a citar los issues que estuve revisando antes de hacer este.
> #1209 #1026 #634 #632

**Output de consola (es el mismo tanto en Eclipse como en la terminal):**

![image](https://user-images.githubusercontent.com/48844698/79491961-a75fa600-7ff5-11ea-8e29-85e23563ac2b.png)

> Se que tengo un precioso warning de una función ahí, pero es de nuestras-commons.

**Hice mil cosas pero así es como están las props del proyecto ahora:**

![image](https://user-images.githubusercontent.com/48844698/79492078-dbd36200-7ff5-11ea-96a2-9f1020e301b3.png)

![image](https://user-images.githubusercontent.com/48844698/79492141-f60d4000-7ff5-11ea-8c29-939ce8c06e25.png)

> En estas settings en particular, en la parte del path para las so-commons probé tanto el workspace (como en nuestras-commons) como ese path que tengo entendido que es donde se guarda el .so pero sigue sin encontrarlas

![image](https://user-images.githubusercontent.com/48844698/79492580-906d8380-7ff6-11ea-8156-97ea4700770d.png)

Algunas cosas que fui haciendo (ya ni me acuerdo todo):
1. Volver a clonar las so-commons en el workspace donde busca Eclipse.
2. Setear la variable de entorno que mencionan en todos esos issues.
3. La configuración que mostré en las imágenes que es la que me funcionó con nuestras-commons.
4. Cambiarle el path en la config del punto 3 de las so-commons por cualquier lugar donde encontrace un libcommons.so.
5. No hacer nada, como hice con el tp0 donde si funcionaba todo felizmente.
6. Ver los videos que se mencionan en esos issues.

Perdón por lo extenso del tema, son las imágenes (?

**Comment by afilgueira** [comment]
Hola, viste este video: https://www.youtube.com/watch?v=Q8wfpu38PMc&t=1s ?

Saludos!

**Comment by francofresno** [comment]
> Hola, viste este video: https://www.youtube.com/watch?v=Q8wfpu38PMc&t=1s ?
> 
> Saludos!

Hola. No, no había visto ese video. Pero sí había hecho lo que dice que hagamos. La diferencia es que yo en el Linker ponía "so-commons-library". Acabo de probar poniendo "commons" como hace en el video pero tengo el mismo resultado, no funciona.

Me surgen algunas preguntas.
1. En el video clona so-commons-library en la carpeta _Documentos_ donde también tiene el proyecto prueba-commons. Es necesario que estén bajo el mismo directorio? Es importante que este directorio sea específicamente _Documentos_?
2. Por qué pondría en el Linker commons y no so-commons-library siendo este último el nombre de las commons? en el Linker cuando linkee la shared library nuestras-commons que creé yo le puse de nuestras-commons.

Gracias!
Saludos!
