### ISSUE TITLE
Problemas para incluir librerias propias

### ISSUE THREAD

**Issue by FedeMacias** [sisoputnfrba/foro#1641]
Buenas

Creamos una libreria de serializacion en base al video que está en utnso, ya está linkeada al proyecto y está agregada en el LD_LIBRARY_PATH, pero cuando la quiero incluir en el .h de mi proyecto no me lo toma ("no such file or directory") y no me doy idea porque, probé con el path entero y tampoco funciona, alguna idea de porque puede ser??

Saludos!

**Comment by FedeMacias** [comment]
como referencia, la library está en la misma carpeta del tp, osea  TP-xxxxxx/Serializacion/Serializacion.h

**Comment by Santiago-Lovelli** [comment]
Hola Fede, no se bien que path estas incluyendo, pero tiene que ser en el cual se encuentre el archivo .so, que 99% seguro que debe estar en la carpeta de Debug:
TP-xxxxxx/Serializacion/Debug (o algo por el estilo)
Si queres tenes el video de las shared library para ver  https://youtu.be/Aw9kXFqWu_I

**Comment by FedeMacias** [comment]
Hola santi, eso me suena como para agregarlo al run configurations que ya esta hecho, pero para el #include???
Literal hago #include <Serializacion/Serializacion.h> dentro de team.h y no me lo reconoce

**Comment by afilgueira** [comment]
Hola, lo primero que veo ahí es que estás haciéndolo con `<>`. Deberías probarlo con comillas dobles. 

A partir de ahí contanos como te fue. Porqué comillas y no `<>`? Pegale una googleada y avisanos si no se entiende.

Saludos!

**Comment by FedeMacias** [comment]
Si, es verdad, me habia olvidado la diferencia, gracias!

De igual forma me sigue tomando el mismo error con el " ", que podria ser???

**Comment by mgarciaisaia** [comment]
https://faq.utnso.com.ar/errores-eclipse

**Comment by mgarciaisaia** [comment]
¿Qué era, che?

**Comment by FedeMacias** [comment]
Algunos problemas de makefile que no estaba tomando bien las librerias y un problema de la inclusion que tenia que ser  #include ".../Serializacion/Serializacion.h".
Disculpá que lo cerré medio abruptamente

**Comment by Kvothe838** [comment]
Tengo el mismo problema @FedeMacias . ¿Exactamente cómo lo solucionaste? Mi makefile parece estar bien, y ese include que mencionaste en tu último comentario no me funciona. Encima a un compañero le funciona perfecto con el workspace_project_locations y tampoco me funciona con eso a mi.
