### ISSUE TITLE
Error al adjuntar imagen/avatar

### ISSUE THREAD

**Issue by velonna** [sisoputnfrba/foro#1645]
Hola, tenemos problemas al adjuntar una imagen en el grupo. El sistema se queda colgado. Esperamos que nos confirme para luego adjuntar las fotos. Saludos

**Comment by afilgueira** [comment]
Hola, no te seguí completamente. Pero nos podrás pasar alguna captura de pantalla o algo similar? Saludos!

**Comment by velonna** [comment]
si, lo adjunto.
![WhatsApp Image 2020-04-18 at 17 19 37](https://user-images.githubusercontent.com/21964130/79673991-50083400-81b5-11ea-8e42-bcce27bc5792.jpeg)

**Comment by afilgueira** [comment]
Hola, mándenos las fotos de l@s integrantes con problemas a inscripciones.utnso@gmail.com, con toda la data que necesitemos para identificarl@s. Saludos!

**Comment by afilgueira** [comment]
@velonna por favor no se olviden de esto, así cerramos su grupo y les asignamos ayudantes. Saludos!

**Comment by afilgueira** [comment]
@velonna cierro este issue pero todavía nos falta una foto. No se olviden por favor.
