### ISSUE TITLE
Problema al iniciar VM

### ISSUE THREAD

**Issue by FacuBazzi** [sisoputnfrba/foro#1646]
Hola, hoy quise abrir la VM y se me queda acá:
![image](https://user-images.githubusercontent.com/48867809/79671681-a029cb00-81a2-11ea-80bb-c72af01bac89.png)
Me resulta raro porque la había usado lo más bien hace poco, pero ahora se me ponen esos items en FAILED y no pasa de ahí, sin que yo haya tocado nada relacionado a esto desde la última vez. Probé reiniciando la pc, creando otra VM y reinstalando el Virtual Box pero me sigue pasando lo mismo en todas.
Alguna idea?

**Comment by enogueiras** [comment]
Hola Facu, a mi me paso eso siguiendo el instructivo de la carpeta compartida, le mande el **shutdown -r now**, y cuando booteo, llego hasta ahi, por lo que lei parece que fue un tema con el disco como que se hubiera desmontado, yo no lo pude solucionar y me tuve que reinstalar la VM. Ojala lo puedas arreglar. Saludos.

**Comment by tferraro** [comment]
👋 
Antes que todo, porfa siempre escriban los contenido de los errores en texto, no en una imagen. Eso no permite indexar al buscador y ayudar a que otros encuentren el issue 😞 

Respecto del issue, nos estás dando poca info sobre el issue para darte una mano, podés ampliar un poco?
Ej, que dice el comando que cuenta el mensaje de error para ver los detalles? Que cambios tiene el disco de la VM? Está limpìo? Cual es la config de la vm en Virtualbox? Probaste buscando el error en google? Que links probaste y que resultados lograste?

**Comment by afilgueira** [comment]
@FacuBazzi te sirvió esto que comentaba Tom? Pudiste avanzar? Seguís bloqueado? Saludos!

**Comment by FacuBazzi** [comment]
Hola, colgué en actualizar la situación, perdón. No encontré forma de hacerlo andar y en Google no vi nada que me ayude, así que para no perder tiempo borré todos los archivos de la vm y los descargué de nuevo y ahí anduvo. Imagino que tal vez había alguna solución menos drástica pero como no tenía nada importante en la vm preferí hacerla corta. Gracias por las respuestas.
