### ISSUE TITLE
GAMECARD - Creación de directorios

### ISSUE THREAD

**Issue by MauroSantander** [sisoputnfrba/foro#1647]
Hola quería consultar si cada Gamecard debe tener su propio árbol de directorios?, Es decir si se levanta un Gamecard crea toda la estructura, y si luego se levanta otro Gamecard debería usar esa estructura ya creada? o crear otra para su propio uso?.

Gracias!

**Comment by iago64** [comment]
Buenas buenas!
Es una buena pregunta, por suerte, la respuesta es simple y radica en que el punto de montaje es un parámetro de la config, con lo cual tenes 2 caminos:
1.- Si te dan un punto de montaje con la estructura creada, la usas y ya
2.- Si no tenes estructura creada, la creas :)

Abrazo.-

**Comment by MauroSantander** [comment]
Hola, puede haber más de un GameCard al mismo tiempo?

**Comment by afilgueira** [comment]
Si, podría haber varios, y no, no van a usar el mismo punto de montaje, al mismo tiempo. Una cosa que podría pasarte (y va a pasar todo el tiempo de hecho), y debería ser transparente, es que un GameCard use un punto de montaje, lo finalices y levantes otro con el mismo punto. 

 Saludos!
