### ISSUE TITLE
Cómo manejar correctamente los errores

### ISSUE THREAD

**Issue by Kvothe838** [sisoputnfrba/foro#1648]
Intentando manejar todo posible error que pueda en el TP0, me surgió la duda de cómo manejarlos correctamente. Y me refiero a lo siguiente. 

En iniciar_logger, por ejemplo, podemos poner algo como esto:

```
t_log* logger;

if((logger = log_create("tp0.log", "client", true, LOG_LEVEL_INFO)) == NULL){
	printf("Error al crear el logger.");
	exit(1);
}

return logger;
```
Por otro lado, leer_config es algo así:

```
t_config* config;

if((config = config_create("tp0.config")) == NULL){
	printf("Error leyendo configuración.");
	exit(2);
}

return config;
```

Ahora bien, en esto me surgen dos cuestiones:

1. Si creo el logger correctamente pero no puedo levantar la configuración, tengo memory leak porque el logger no le estoy haciendo free.
2. Por cada error tendría un número diferente para mandarle al exit, eso me suena a que no está tan bueno.

Se me ocurre la alternativa de que tanto leer_config como todas las funciones en adelante, devuelva diferentes códigos de error según qué pase, y el main se encargue de que si recibe error, limpie toda la memoria que fue creada hasta entonces. El problema con esto es que es un tanto asqueroso todo el tiempo estar preguntando por el error y estar mandando 20 free.

Otro ejemplo un toque más complejo: recibir_mensaje. Al principio tengo esto:

```
op_code codigo_operacion;
int resultado_recv = recv(socket_cliente, &codigo_operacion, sizeof(int), 0);

switch(resultado_recv){
	case 0:
		printf("Desconexión.\n");
		return mensaje;
	case -1:
		printf("Error al recibir codigo_operacion.\n");
		return mensaje;
}
```

En este caso quiero que si devuelve 0 o -1, también del lado del main se encargue de limpiar la memoria pero evidentemente así no lo puedo hacer. Si tiro un exit, no libero nada. Podría pasarle como parámetro un int* que represente el posible error y si está todo bien, guardarlo en 0. No sé si es muy bueno que digamos...

¿Cómo sería la mejor forma de manejar los errores de manera tal que podamos ante cada error limpiar toda la memoria?

**Comment by enogueiras** [comment]
Hola, una consulta, ¿esos if te funcionan bien? yo tenia los mismos y me trajeron problemas.

**Comment by Kvothe838** [comment]
> Hola, una consulta, ¿esos if te funcionan bien? yo tenia los mismos y me trajeron problemas.

Sí, funcionan perfecto.

**Comment by iago64** [comment]
buenas buenas!

Vamos en orden:

1.- El manejo de errores es necesario porque si te falla algo que te impide avanzar tenes que frenar las cosas (por ej no poder levantar la config)

2.- Los numeros de error para finalizar, tampoco es taaan importante que sean diferentes, con que por ej imprimas: Error al crear el Log o Error al levantar la config y retornes un -1 por ej, ya esta todo en orden

3.- Los memory leak los salvas checkeando como decís un valor de retorno de la función y listo

4.- Volviendo sobre los memory leaks, tene en cuenta que si el proceso termina de una, medio que la memoria la va a limpiar el SO, lo importante es que si tu proceso continua ejecutando no empiece a comer mas y mas memoria a medida que pasa el tiempo, eso si es un leak grave.
La forma fácil de checkear eso es con valgrind y por suerte tenemos una [charla de algún cuatri pasado donde se explica mas o menos de que la va](https://www.youtube.com/watch?v=knRei6OBU4Q&ab_channel=UTNSO)

Saludos.-

**Comment by mgarciaisaia** [comment]
Los valores que se le pasan a `exit` se suelen usar para que, si alguien usa nuestro programa en un script, pueda decidir qué hacer dependiendo el error que devolvamos. Algunos programas, por ejemplo (podés hacer `man ls` y bajar a `Exit status`) te devuelven `0` si anduvo todo bien, `1` si hubo problemas "menores" (no tuve acceso a algún subdirectorio, pero te listé un montón), y `2` si anduvo todo mal (me pasaste flags que no entendí).

En el caso del TP, el programa debería finalizar cuando encuentres errores irrecuperables (falló el log o la config, ponele), y debería informar y seguir ejecutando cuando sea posible (un servidor al que se le desconecta abruptamente un cliente).

**Comment by afilgueira** [comment]
Hola acá también @Kvothe838 👋 . Te sirvió lo que comentaban los chicos?

**Comment by Kvothe838** [comment]
@afilgueira a medias. Por un lado, entendemos mejor la diferencia entre simplemente loguear un warning y tirar exit, sobre todo con la respuesta de @mgarciaisaia . El tema es que a nivel código seguimos teniendo algo visualmente horrible. Llevándolo un poco al ejemplo del TP0, en cada llamada desde el main del cliente.c al utils.c, tenemos que chequear si algo falló, y si es así, tirar unos free. A veces esos free se pueden generalizar en una función de manera tal de no tener que repetir todo el tiempo el mismo código, a veces no, porque a medida que se va ejecutando el programa, van apareciendo nuevos punteros. En ese sentido, seguimos sin saber si la manera correcta es la manera fea que estamos aplicando, o hay alguna mejor.

**Comment by afilgueira** [comment]
Les tiro un tip. El SO libera memoria automáticamente cuando el proceso finaliza. Esto hace que no necesiten hacer free de nada en ese caso. El free es importante cuando tu proceso va a seguir ejecutando (un poco el punto 4 que comentaba Dami). Quizás ya lo habían entendido antes, por si no lo aclaro.

Por otro lado, a la hora de manejar errores, chequeen cuales son esperados y cuales son casos excepcionales. En los casos excepcionales podrían (previo chequeeo con sus ayudantes por las dudas) abortar el programa y ya. Por ejemplo, no poder levantar el archivo de configuración es algo excepcional. Intentar conectarse a un módulo de TP y que esto no funcione en un 90% de los casos también. Estas consideraciones van a ayudar a que sólo manejen free en los errores importantes (que créanme que van a ser pocos respecto al resto).

Saludos!

**Comment by Kvothe838** [comment]
@afilgueira ahora está más claro, muchas gracias!
