### ISSUE TITLE
Biblioteca para primer entrega

### ISSUE THREAD

**Issue by Kvothe838** [sisoputnfrba/foro#1649]
La biblioteca que pide en la primer entrega, ¿la idea es que sea un archivo utils.c con su correspondiente utils.h idénticos por cada proyecto, o crearnos un quinto proyecto que funcione como biblioteca?

**Comment by iago64** [comment]
Buenas buenas!

No necesariamente tiene que llamarse utils, la idea es que uds tengan unificado el envio de mensajes para no estar matandose despues a mitad o fin del cuatrimestre para saber como se mandaba tal o cual tipo de mensaje, con lo cual, como la hagan es mas a criterio de cada grupo, lo que si, por favor, no copien y peguen el codigo de la biblioteca en cada proyecto.

Saludos.-

**Comment by afilgueira** [comment]
Hola @Kvothe838, te sirvió esto que comentaba Dami?

**Comment by Kvothe838** [comment]
@afilgueira buenas! Esta respuesta sirvió. Hicimos un proyecto a parte con el utils y lo compartimos en cada módulo. Aunque la verdad seguimos un poco perdidos en lo que respecta a qué se requiere de este checkpoint. Entendemos la idea general pero a nivel código tampoco comprendemos muy bien cuando nos dicen de probar una comunicación entre dos módulos (nos respondieron algo así por Discord). De todos modos les vamos a consultar mejor a los ayudantes.

Resumiendo, este issue se puede cerrar, está bastante clara la respuesta.

**Comment by afilgueira** [comment]
Excelente. Siéntanse libres de cerrar issues cuando estén resueltos. Saludos!
