### ISSUE TITLE
Serializar estructuras dinámicas

### ISSUE THREAD

**Issue by francofresno** [sisoputnfrba/foro#1650]
Hola, estuve viendo este [video](https://www.youtube.com/watch?v=GnuurOt8yqE), pero no entendí muy bien cómo hacer para enviar estructuras dinámicas.

Yo tengo en este momento algo de este estilo (es provisorio, probablemente esto no termine siendo EXACTAMENTE así pero no nos paremos ahora en esto):
```
	typedef struct New_Message {
		t_nombre nombre_pokemon;
		t_coords coords;
		uint32_t cantidad;
	} t_new_message;

	typedef struct  Nombre_Pokemon {
		uint32_t nombre_lenght;
		char* nombre;
	} t_nombre;

	typedef struct Coordenadas {
		uint32_t posx;
		uint32_t posy;
	} t_coords;
```
Send quiere que le digamos el tamaño de lo que le vamos a enviar. 
Cuando enviamos char*, todo bien, en el send le mandás strlen del char y listo. 
La pregunta es cuál es el tamaño de todo eso, digamos de algo de tipo t_new_message. Porque yo puedo sacar individualmente el tamaño de cada una de las variables que están dentro de la struct (y de las structs que están dentro). Esto último me daría _16 + strlen del char* nombre_ si no estoy haciendo mal los cálculos. El tema es que acá creería yo que juega un papel importante el padding que agrega el compilador. Por lo que si yo le digo que _16 + strlen del char*_ es el tamaño de lo que le envío, le estaría mintiendo y es probable que no ande bien siempre. No podría usar ___attribute__((packed))_ porque esta struct nunca va a tener un tamaño fijo, sino que va a depender de cuan largo sea el nombre del pokemon. Todas las soluciones que pude encontrar googleando prácticamente decían que use ese atributo o que meta todo en un char* y después vea como lo saco del otro lado.

Cómo debería manejar esto? No entiendo cómo sacar el tamaño de lo que necesito mandar. Quiero meter todo mi mensaje en un buffer como en el tp0
```
	typedef struct
	{
		int size;
		void* stream;
	} t_buffer;
```

Gracias!

**Comment by gastoncastineira** [comment]
Buenas,

La mecánica para manejar eso es exactamente la misma que usamos para serializar el paquete en el TP0 y cómo se explicó en el documento de serialización. Vos lo que tenés que mandar son los atributos primitivos junto con su tamaño. Osea, tu stream debería tener más o menos la forma de 
(nombre_lenght|nombre|posy|posx|cantidad) y su tamaño sería (nombre_lenght + sizeof(posy) + sizeof(posx) + sizeof(cantidad))

¿Es esa la duda? Si no, te pido que reformules porque no entendí

**Comment by francofresno** [comment]
> Buenas,
> 
> La mecánica para manejar eso es exactamente la misma que usamos para serializar el paquete en el TP0 y cómo se explicó en el documento de serialización. Vos lo que tenés que mandar son los atributos primitivos junto con su tamaño. Osea, tu stream debería tener más o menos la forma de
> (nombre_lenght|nombre|posy|posx|cantidad) y su tamaño sería (nombre_lenght + sizeof(posy) + sizeof(posx) + sizeof(cantidad))
> 
> ¿Es esa la duda? Si no, te pido que reformules porque no entendí

Ah okei, yo no tengo que mandar la estructura en sí sino los elementos que están dentro de la estructura y del otro lado mapearlos con una nueva instancia de la estructura. Si es así ahora me cierra todo. 

En cuanto al tamaño, puede ser que te faltó sumar también sizeof(nombre_lenght)?

Ahora, teniendo en cuenta esto me surge una pregunta que quizás me respondo solo:
recv maneja algún puntero internamente o algo así que sabe que lo que ya leyó, no? como cuando leemos de un archivo. Por eso si hago:
```
	recv(socket,&(paquete_recibido->codigo_operacion),sizeof(int),0);
	recv(socket,&(paquete_recibido->buffer->size),sizeof(int),0);
```
Extrae del stream los primeros 4 bytes (sizeof(int)) y después con el segundo recv sabe que los primeros ya los leyó y pasa los siguientes.

Gracias!

**Comment by gastoncastineira** [comment]
> En cuanto al tamaño, puede ser que te faltó sumar también sizeof(nombre_lenght)?

Sí. Buen ojo

> recv maneja algún puntero internamente o algo así que sabe que lo que ya leyó, no? como cuando leemos de un archivo

Sí

**Comment by francofresno** [comment]
Genial, cierro el issue, gracias!

**Comment by mgarciaisaia** [comment]
@francofresno acordate que lo que estás haciendo acá es _definir un protocolo de red_. Cuando definís un protocolo de red, probablemente te interese independizarte de tu plataforma actual. Para el TP, ponele, estás programando en C, porque nosotros se los pedimos. Pero la idea de un protocolo de red bien definido es que, por ejemplo, alguien pueda leer la especificación de tu protocolo y escribir un programa en Java, Pascal o Smalltalk que implemente el mismo protocolo de red y se comunique con tu programa igual. Entonces, _el padding del compilador_ seguramente sea algo que no quieras incluir en tu protocolo - porque en general no querés asumir nada sobre el compilador que usen l@s demás.

**Comment by francofresno** [comment]
> @francofresno acordate que lo que estás haciendo acá es _definir un protocolo de red_. Cuando definís un protocolo de red, probablemente te interese independizarte de tu plataforma actual. Para el TP, ponele, estás programando en C, porque nosotros se los pedimos. Pero la idea de un protocolo de red bien definido es que, por ejemplo, alguien pueda leer la especificación de tu protocolo y escribir un programa en Java, Pascal o Smalltalk que implemente el mismo protocolo de red y se comunique con tu programa igual. Entonces, _el padding del compilador_ seguramente sea algo que no quieras incluir en tu protocolo - porque en general no querés asumir nada sobre el compilador que usen l@s demás.

Sí, claro, justamente mi duda era cómo hacer para sacar el padding del envío.
