### ISSUE TITLE
consulta mensajes pokemon get y localized

### ISSUE THREAD

**Issue by enogueiras** [sisoputnfrba/foro#1651]
Hola, recien termine de ver el video de planificacion que subieron al canal de YT y me surgieron 2 dudas:

1) Mensaje GET, en la especificación solo da como parámetro el nombre del Pokemon, ¿no faltaría también la cantidad?

2) Mensaje LOCALIZED, en el video llega sin la cantidad de pares de coordenadas, ¿esto cambió o fue solo un error al momento de hacer el video?

Muchas gracias.
Emilio.

**Comment by ncoen97** [comment]
Buenas,
En el mensaje GET no es necesario especificar la cantidad, ya que como dice el enunciado,

> El objetivo del mismo es obtener todas las locaciones de una especie de Pokemon.

que es el resultado del LOCALIZED. 
Con respecto al LOCALIZED, sí recibe la cantidad de pares de coordenadas, en el ejemplo del video sería 1.
Saludos.
