### ISSUE TITLE
 [Broker] Dudas Enunciado - Diseño y aspectos técnicos planteados

### ISSUE THREAD

**Issue by EliasReuter** [sisoputnfrba/foro#1653]
Buenas,
Tenemos dudas respecto a como diseñar el Broker dados los requerimientos planteados en el enunciado (y los videos que van agregando información).

### Extracto del enunciado
Dichas colas de mensajes deben cumplir con los siguientes aspectos técnicos:
| Aspecto técnico |  Descripcion |
| ------------- |-------------| 
|Durabilidad | Todo mensaje debe permanecer en la cola de mensajes hasta que todos los Suscribers lo reciban.|
|Notificación de recepción |Todo mensaje entregado debe ser confirmado por cada Suscriptor para marcarlo y no enviarse nuevamente al mismo.|
|Mantenibilidad |Cada cola de mensaje debe mantener su estado y borrar aquellos mensajes que ya fueron entregados a todos sus suscriptores.|
|Asincronismo| La recepción y notificación de mensajes pueden diferir en el tiempo. No deben notificarse inmediatamente a los componentes suscritos a dicha cola.|

Además:
|#|Consideraciones|
|---| --- |
|1|Todo mensaje debe ser cacheado dentro de la memoria interna del Bróker.|
|2|Todo mensaje debe saber a cuáles suscriptores fue enviado y si el mismo fue recibido (confirmación, ACK o acknowledgement).|
|3|Todo mensaje debe tener un identificador unívoco generado por el Bróker que debe ser informado al módulo que generó el mismo.|

### Alternativas de diseño que se nos ocurrieron
1) Se saca el mensaje, se envía a todos los suscriptores y se manda a una estructura auxiliar (por ejemplo, una lista de mensajes pendientes de confirmación) y queda allí hasta que todos los suscriptores lo confirmen (cuando se confirma se elimina o manda a otro lado). Queda pendiente definir una política de reenvío (analizando esta estructura auxiliar propuesta) si no se reciben las confirmaciones en un periodo de tiempo X.

>Contras:
>- No se cumple textualmente con el requerimiento de “**mantenerlo en la cola** hasta que todos lo reciban (y confirmen???)”
>- Contradicciones con otras indicaciones, como la referencia a la notificación de recepción y al ACK.

2) Se saca el mensaje de la cola, se envía a todos los suscriptores flageados como “no confirmado” y se vuelve a meter en la cola. Otro proceso se encarga de recibir confirmaciones y actualizar el estado del mensaje. (Todo esto para seguir el "mantenerlo en la cola...")

>Contras:
>- En cada iteración se reenvía el mensaje a los suscriptores no confirmados, pudiendo generar
>conflictos si el usuario ya lo había recibido.
>- Al ser una cola, para cambiar el estado de un mensaje el modulo receptor de confirmaciones
>tendría que sacar todos los mensajes hasta encontrar el correspondiente, modificarlo, y volverlos a meter.
>- No tendria sentido usar una cola. Quizas una lista es mas acorde a esto.

La dudas estarían en entender cual de estas alternativas van con lo esperado, porque ambas presentan ideas que siguen lo descrito en el enunciado pero a la vez cuestiones que lo contradicen (items). Destacamos la duda del primer aspecto técnico "Durabilidad", en el que se dice que el mensaje tiene que quedar **en la cola** hasta que todos los Suscribers lo reciban. Quizás es referencia a que debería quedar en el Broker, no especificamente en la cola.

**Comment by afilgueira** [comment]
Buenas, no se aten a la implementación "teórica" de una cola. Pueden leer mensajes sin tener que sacarlos y ponerlos nuevamente. Y si los sacan y los vuelven a poner, a fines prácticos siguen en la cola, no se enreden con esto que no es la idea. El objetivo es que los mensajes sigan hasta que hayan sido entregados, pero no vamos a monitorear cada milisegundo sus estructuras.

Como sugerencia, cada cierto tiempo / evento podrían leer toda la lista, enviarlo a quienes aún no lo recibieron, editar algún tipo de estructura donde uds saben a quienes se lo enviaron, quienes lo recibieron, etc. De esa forma se evitan sacar y poner elementos.

Saludos!

**Comment by Gonzalo-Avila** [comment]
Buenas!

Me sumo al thread para consultar si hay alguna política establecida de reenvío a suscriptores que no confirman un mensaje, o si esto queda a nuestro criterio. Por ejemplo, ¿cuando dejamos de intentar reenviar? 

Por otro lado, entiendo por la respuesta que nos podemos desentender del uso literal de colas como estructuras, ¿no? Buenísimo.

Saludos.

**Comment by afilgueira** [comment]
Hola, por lo general preferimos que no se sumen a lo threads, sino que creen un issue aparte linkeando la pregunta. Así no desvirtuamos la pregunta original. Al margen de esto:

- Porqué no confirmarían?
- Sobre las colas, a lo que iba es a que no lo piensen en el sentido literal (saco el primero y agrego al final, y esta es mi única interfase) sino como listas que tienen un orden, sobre las cuales pueden operar.

Saludos!

**Comment by iago64** [comment]
@EliasReuter como va? la respuesta de Adro te sirvio? podemos cerrar el issue?

**Comment by EliasReuter** [comment]
Si. Lo habiamos seguido con Gonzalo en otro issue y este quedo abierto. Muchas gracias.
