### ISSUE TITLE
Consulta de conexion entre Proceso Team y Broker

### ISSUE THREAD

**Issue by rodrisanz** [sisoputnfrba/foro#1654]
Hola, buenas tardes.

Tenia un par de dudas acerca del video de planificación. El mismo hace referencia sobre conectarme y desconectarme cada vez que quiero enviar un mensaje de Team a Broker. Por ejemplo el CATCH.¿Esto quiere decir que tengo que usar un connect() de la biblioteca de sockets cada vez que necesito enviarle un mensaje?
Y la otra duda es ¿El broker tiene varios servidores una por cada cola?

Muchas gracias!
Saludos.

**Comment by nahuemazzeo** [comment]
Hola @rodrisanz 

Con respecto a la primer pregunta, si. Cada vez que requieras enviarle un mensaje al Broker vas a tener que conectarte a él, enviarle el mensaje y cerrar dicha conexión. 

Con respecto a la segunda pregunta, es mas compleja porque la pregunta no esta bien definida. El Broker funciona como servidor, esto quiere decir que expone un socket para que los distintos procesos se comuniquen a el. Cuando se conecten a este socket los distintos clientes van a tener que definir el porque se comunican a el (si es por una suscripción a una de sus colas o para enviarle un mensaje).
Si la pregunta iba referida a si tenes que tener un Socket de escucha para cada cola, la respuesta es NO. El broker solo maneja un socket de escucha y luego dependiendo el mensaje que reciba es a la cola que se suscribirá o el mensaje que recibirá. 

Saludos.

**Comment by ezeveliz** [comment]
Hola @nahuemazzeo , 

Si el proceso Team tiene que abrir una conexion por cada mensaje y despues cerrarla, como hace para enterarse si el Broker le respondio algo, porque si el cleinte cierra la conexion, el servidor ya no va a tener referencia a la cual responder hasta donde tenia entendido. Que tendria uqe hacer el proceso Team, volverse a conectar despues de x tiempo para ver si hay alguna respuesta?

**Comment by nahuemazzeo** [comment]
Hola @ezeveliz 

El Team al iniciarse realiza tres conexiones contra el broker, una por cada cola a la que se va a suscribir. El broker al recibir un mensaje a una de esas colas le enviara el mensaje al socket correspondiente a la misma. 

Cuando vos envías un mensaje lo haces por otro socket diferente por lo que este ultimo lo cerras.

Te recomiendo mirar el vídeo de Planificación, ahí explicamos un poco mas el manejo de los mismos.

Saludos.

**Comment by afilgueira** [comment]
@rodrisanz quedó resuelta tu pregunta? Saludos

**Comment by afilgueira** [comment]
Cierro. Si falta algo, por favor reporten un nuevo issue

**Comment by rodrisanz** [comment]
@afilgueira Nos pusimos en contacto con uno de los ayudantes! Muchas gracias!
