### ISSUE TITLE
Duda "mapa de memoria" de Team.

### ISSUE THREAD

**Issue by franpassa** [sisoputnfrba/foro#1655]
Gente, no estaria entendiendo bien lo de los entrenadores para localizarlos. Yo cuando importo la posicion de un entrenador, la dejo asi como 2 ints para operar? O tengo que asignarle algun puntero al entrenador? Porque en el ultimo video habla de un "mapa en memoria"

**Comment by afilgueira** [comment]
Imaginate que la ubicacion es un "mapa" / matriz. Los dos valores son sus coordenadas x e y. Solo eso.

Saludos!

**Comment by iago64** [comment]
@franpassa como va? la respuesta de Adro te sirvio? podemos cerrar el issue?

**Comment by franpassa** [comment]
Asi es, ya pude progresar con eso 😄

**Comment by iago64** [comment]
Buenisimo 😄 lo cerramos entonces.
