### ISSUE TITLE
Mensaje del Game boy (¿Team o Teams?)

### ISSUE THREAD

**Issue by francorojo** [sisoputnfrba/foro#1656]
Hola buenas noches, estuvimos pensando en un concepto que no estamos seguros de como resolver. En el mensaje ./gameboy TEAM APPEARED_POKEMON [POKEMON] [POSX] [POSY] la palabra TEAM remite a un equipo o a todos los equipos? En consecuencia, en el caso de que remita a un solo equipo, como sabría el Game Boy a que Team comunicarse?

**Comment by mesaglio** [comment]
Buenas, como va??
Fijate que en el enunciado dice explicitamente: Enviar un mensaje al Broker, a **un** Proceso Team o a un Proceso Game Card.
Revisa la configuracion de Game Boy.

**Comment by francorojo** [comment]
Aaa listo gracias, y con respecto a eso, cada vez que queremos mandar un mensaje a un team diferente, deberiamos cambiar de forma manual o de alguna forma automatica ese archivo de configuracion, para poner el puerto correspondiente?

**Comment by mesaglio** [comment]
Como ustedes quieran.
Si lo quieren automatizar lo pueden hacer. Si no, a mano.

**Comment by francorojo** [comment]
Graciaaas!
