### ISSUE TITLE
ID en los tipos de mensajes

### ISSUE THREAD

**Issue by francofresno** [sisoputnfrba/foro#1657]
Buenas, tengo una consulta sobre los tipos de mensajes.

Los mensajes tienen que tener dos IDs (ID único e ID correlativo). Yo considero que esos IDs deben estar en la estructura de cada mensaje. Pero el anexo II especifica lo que deben tener estos mensajes no dejando margen para agregar algo mas. 

_Cito dos partes del enunciado:_
> Tipos de Suscribers
Todo mensaje en una implementación real tiene dos atributos claves: Su identificador y su identificador correlacional (o correlation id).

> Tipos de datos
Dado que el trabajo práctico mantendrá seis tipos de mensajes distintos (uno por cada cola de mensajes) se normalizarán los tipos de datos a utilizar para que el tamaño que ocupe cada uno dentro de la memoria principal sea homogéneo a todos los grupos. El objetivo de esto es otorgar una manera rápida de verificación y validación de lo desarrollado por los alumnos. [...] Para ejemplificar cada tipo de mensaje les recomendamos leer el Anexo II.

**Cómo manejamos los IDs si el mensaje no puede tener su propio ID incluido?**

1. Podemos incluirlo de todas maneras?
2. Tienen que viajar en el paquete sin ser parte del mensaje en sí guardándose en la cola de mensajes como parte del nodo?

En el punto 2 me refiero a algo como esto:
```
struct Message_queue {
    int id;
    int id_correlativo;
    void* message;
    struct Message_queue *sig;
} new_pokemon, appeared_pokemon, etcetc...;
```

Gracias!
Saludos,

**EDIT:**
Agrego una mini pregunta que me acabo de acordar:
Además de los 6 tipos de mensajes por colas tiene que haber un 7mo mensaje con cod_op SUSCRIBIRSE o algo así, no?

**Comment by Zheoden** [comment]
Buenas franco!

1) Lo que indica el anexo II es la forma de almacenar los mensajes en memoria, no la forma que tienen que tener para enviarse a otro proceso. Dicho esto, **NO** pueden agregar mas información de la que se indica en dicho anexo. Para hacer el manejo de los ids, vas a tener que hacerlo a través de estructuras administrativas.
2) Si y no, los ids van a tener que viajar en todos los mensajes entre procesos, pero no se tienen que almacenar en la memoria del broker, para esto se utilizan estructuras administrativas.

Respecto a la pregunta que agregaste después, no termino de entender a que te referís con séptimo mensaje. Pero solamente hay 6 tipos de mensajes.

Saludos,

**Comment by francofresno** [comment]
> Buenas franco!
> 
> 1. Lo que indica el anexo II es la forma de almacenar los mensajes en memoria, no la forma que tienen que tener para enviarse a otro proceso. Dicho esto, **NO** pueden agregar mas información de la que se indica en dicho anexo. Para hacer el manejo de los ids, vas a tener que hacerlo a través de estructuras administrativas.
> 2. Si y no, los ids van a tener que viajar en todos los mensajes entre procesos, pero no se tienen que almacenar en la memoria del broker, para esto se utilizan estructuras administrativas.
> 
> Respecto a la pregunta que agregaste después, no termino de entender a que te referís con séptimo mensaje. Pero solamente hay 6 tipos de mensajes.
> 
> Saludos,
Buenas, cómo estás?

Cuando te referís a "memoria" no estás hablando de la memoria interna del Broker, no? porque esta especifica que lo que se guarda es:
1. Identificador único del mensaje dentro del sistema.
2. El tipo de mensaje (a que cola de mensajes pertenece).
3. Los suscriptores a los cuales ya se envió el mensaje.
4. Los suscriptores que retornaron el ACK del mismo.

Si esto es así, lo que me estás diciendo básicamente es que haga una struct que maneje al mensaje con los datos del anexo II (sería una por cada mensaje). Y que el ID viaje en el socket pero no como parte de esta estructura?

Respecto a la última pregunta... cómo le dice Team a Broker que se quiere suscribir a la cola de appeared? a través de un mensaje por un socket. O sea que yo tengo que definir otro mensaje mas que tenga como cod de operación SUSCRIBIRSE por ejemplo para que Broker pueda saber qué hacer... si le mandaron un NEW o si alguien se quiere suscribir a una cola.

Saludos!

**Comment by Zheoden** [comment]
Buenas!!

Los puntos que indicas son cosas que el broker tiene que tener un registro, pero no se van a guardar en la memoria que ustedes tienen que hacer. Cuando hablo de memoria me refiero a la memoria interna del broker que ustedes tienen que hacer.

Para la implementacion de esto, hay varias formas de resolverlo, pero por lo que planteas, podrías tener 2 estructuras distintas, una que tenga el id del mensaje, la lista de subscriptores, etc. Los datos que están en el anexo II se guardan en la memoria del broker, lo demas lo va a administrar el broker, pero utilizando memoria del sistema.

En cuanto a la ultima dado que las colas son fijas y no puede cancelar la subscripcion, no es necesario un mensaje para indicar que se quiere subscribir, sino simplemente cuando se conecta, pueden ver si es un team, y en ese caso lo subscriben automaticamente a las colas correspondientes.

Saludos!

**Comment by francofresno** [comment]
Okei, entonces no estoy comprendiendo bien el enunciado. Te cito una parte del enunciado:

> Administración de mensajes
> Como dijimos anteriormente, el Broker mantendrá una memoria interna en la cual se cachean los últimos mensajes recibidos de las distintas colas de mensajes. En el mismo deberá registrar:
> 1. Identificador único del mensaje dentro del sistema.
> 2. El tipo de mensaje (a que cola de mensajes pertenece).
> 3. Los suscriptores a los cuales ya se envió el mensaje.
> 4. Los suscriptores que retornaron el ACK del mismo.
> Se implementarán dos esquemas de Administración de Memoria [...]

Acá dice que mande a la memoria del Broker esos puntos. Pero después hay una parte que valida lo que decís vos:

> Solo se deberá guardar en la porción de datos el contenido del mensaje dejando el tipo, identificador y demás flags del mismo en estructuras auxiliares.

Entonces le doy bola a lo segundo nomás?

En cuanto a la última pregunta, me queda un poco más claro ahora.

Gracias por responder!
Saludos
