### ISSUE TITLE
Duda Lista de posiciones

### ISSUE THREAD

**Issue by MatiasRosales** [sisoputnfrba/foro#1658]
Hola,
tengo una duda acerca de como serializar  y deserializar las listas de posiciones para el proceso de Localized_Pokemon. Precisamente en como reservaria memoria cuando lo empiece a almacenar en un stream

Saludos
La estructura de posiciones es la siguiente:
typedef struct{
	uint32_t x;
	uint32_t y;
        uint32_t cantidad;
}t_posicion;
typedef struct{
	t_posicion posicion;
	uint32_t cantidad_total;
	t_nodo* siguiente;
}t_nodo;

**Comment by ncoen97** [comment]
Buenas! Ya le echaste una mirada al video de [serializacion](https://www.youtube.com/watch?v=GnuurOt8yqE)?
