### ISSUE TITLE
Identificación de roles en los módulos

### ISSUE THREAD

**Issue by achoquemamani** [sisoputnfrba/foro#1659]
Hola buenas noches, en el grupo tenemos una duda en lo siguiente.
El broker, team y card game son servidores? Y el GameBoy cliente?
Saludos!

**Comment by ncoen97** [comment]
Buenas noches! Primero que todo, buscaron en los [issues](https://github.com/sisoputnfrba/foro/issues)? me suena que discutimos varias veces sobre este tema.

**Comment by achoquemamani** [comment]
Hola buenas noches, sí encontramos un tema relacionado en el https://github.com/sisoputnfrba/foro/issues/1654, pero no lo dice de forma explícita, por eso decidí hacer la pregunta más directa. Según el link, el broker es servidor, y habla de las colas(imagino que es Team y Card Game). Pero en cuanto a GameBoy, realicé la búsqueda y no encontré nada.

**Comment by afilgueira** [comment]
Hola, en #1638 y en #1626 hablamos justo del tema. Un tip a la hora de buscar, fíjense de incluir los issues cerrados. Si algo no cierra, cuéntenos por acá.

Saludos!

**Comment by achoquemamani** [comment]
Dale, muchas gracias! Quedó claro.
