### ISSUE TITLE
Consultas varias, proceso broker

### ISSUE THREAD

**Issue by foviedo** [sisoputnfrba/foro#1660]
Hola! Pregunto algunas cosas:
1) Tomando en cuenta que Broker es servidor de gamecard y de team, se supone que, por ejemplo, un hilo de team se conecta a Broker, le pide los mensajes, el Broker se los manda todos uno atrás del otro? 
2)Extendiendo la anterior, se supone que cada vez que el team quiera enviar un mensaje a broker, este abre su conexión, lo envía, y cierra la conexión, luego de eso si broker quiere enviar un mensaje de team, cómo se lo envía? Tomando en cuenta que Broker es servidor y solamente escucha, no crea conexiones nuevas
3) Se dice que son multihilos, puede ser que cada cola sea un hilo? Cómo administro los subscriptores? Guarda en una lista los sockets de estos? 
4) Bien dijimos, una vez que todos los subscriptores hagan ACK a un mensaje de la cola, este mensaje se elimina, entonces, cuando venga un nuevo subscriptor, sólo va a recibir los mensajes que los otros subscriptores no hicieron ACK, porque los que sí, ya fueron eliminados? 
5) Encontré una library que hace algunas cosas de message queue http://cryptomex.org/Apuntes/artipcs.pdf
en la p29, es legal que la use? El include dice sys, así que creo que es una library que viene incluída el el sistema
Proceso team:
6) No termino de entender esto del video y  del enunciado, yo entiendo que cada hilo de team es UN entrenador y todos están en un mismo mapa, no es así?
7)El mapa: lo almacena el Gamecard, cada uno de los entrenadores, no conocen cómo está compuesto este, no?

Gracias de antemano!

**Comment by Kvothe838** [comment]
@foviedo en qué quedó esto? Sería útil que compartieras las respuestas si las resolviste. Me interesan particularmente la 1 y la 4.
