### ISSUE TITLE
Memory Leak en String_split

### ISSUE THREAD

**Issue by Phiiliip** [sisoputnfrba/foro#1661]
Buenas:

Luego de completar un requerimiento (y que funcione) decidí correr Valgrind para verificar si había Leaks de memoria y me encontré con el siguiente:

![foto 1](https://user-images.githubusercontent.com/28789578/80252522-cb526580-864d-11ea-83e0-7ef2b66b03d3.png)

El leak sucede en esta parte del código:

```
                FILE* posiciones = fopen(path, "r"); 
                char* line = NULL;
		size_t len = 0;
		ssize_t read = getline(&line, &len, posiciones);
			while ((read = getline(&line, &len, posiciones)) != -1) {
				char** keyValue = string_split(line, "=");  //Linea 539

				char* key = keyValue[0];

				int cantidad = atoi(keyValue[1]);

				char** posiciones = string_split(key, "-");

				int posicionX = atoi(posiciones[0]);
				int posicionY = atoi(posiciones[1]);
```

Le intente dar la vuelta pero no consigo entender de donde sale y leer la función privada que utiliza "_spring_split" tampoco me ayudó en nada.

Gracias y saludos!

**Comment by ncoen97** [comment]
Buenas, la funcion string_split es una función de las [commons](https://github.com/sisoputnfrba/so-commons-library/tree/master/src/commons), ahí pueden encontrar las definiciones e implementaciones. En este caso, el string_split lo que hace es devolverte un char ** (que sería una lista de char *), cada uno de estos char * tiene memoria asignada, por lo que tienen que liberarla para que no quede tomada.
Conclusión: Intenten hacer alguna función que les libere los char **, si no lo logran nos avisan y les damos una mano.
Saludos!

**Comment by Phiiliip** [comment]
Buenas:

Gracias por la aclaración. Lo que hice fue lo siguiente:

Como las commons especifican que al final deja un NULL, hice esto:


```
void liberar_lista(char** lista){
int contador = 0;
while(lista[contador] != null){
        free(lista[contador]);
        contador++;
}

free(lista);

```

Gracias por la ayuda, cierro el issue.
