### ISSUE TITLE
Problemas al instalar la Guest Additions.

### ISSUE THREAD

**Issue by juanff22** [sisoputnfrba/foro#1662]
Hola cuando instalo, las GuestAdditions, no se me instalan correctamente adjunto las imágenes de lo que sale:

![error 1 000](https://user-images.githubusercontent.com/62486237/80256371-04da9f00-8655-11ea-88b1-1b9231a44e1c.jpg)

Y al salir, para cambiar de usuario y volver a ingresar sale esto:

![error VM](https://user-images.githubusercontent.com/62486237/80256762-c1ccfb80-8655-11ea-91da-4a6f5b093a6b.jpg)

**Comment by afilgueira** [comment]
Hola, por favor lee https://github.com/sisoputnfrba/foro#foro-de-consultas-del-trabajo-pr%C3%A1ctico (y seguí los lineamientos!). Ayudanos a ayudarte. 

Por otro lado, este mismo problema está mencionado varias veces, por ejemplo acá: https://github.com/sisoputnfrba/foro/issues/1293

Saludos!

**Comment by juanff22** [comment]
Hola, gracias por contestar, ya lo pude solucionar, pido disculpas por duplicar el tema, soy nuevo con esto de github y lo busque mal.

Saludos

**Comment by afilgueira** [comment]
Ningún problema! Me alegra que lo hayas solucionado!
