### ISSUE TITLE
Cambios en versión 1.1 - Suscripciones del proceso Team

### ISSUE THREAD

**Issue by Gonzalo-Avila** [sisoputnfrba/foro#1663]
Buenas!

A raíz de los cambios en la versión 1.1 nos surgieron nuevas dudas, particularmente a partir de lo siguiente:

>*"Aclaramos que todos los tipos de mensaje del team son por suscripción global en lugar de suscripción por id correlativo".*

Para empezar aclaro que, según lo que entendemos, la diferencia entre ambos tipos de suscripción radica en que al estar un proceso suscrito por ID correlativo, filtrará los mensajes que no le interesen. O sea, esto **es una lógica del suscriptor**, y no del broker, ya que este enviará todos los mensajes indistintamente. Me gustaría que me corrijan si estoy equivocado. 
 
Respecto a las dudas particulares:

1) Cuando un team recibe el mensaje CAUGHT, este debe validar si le corresponde mediante el ID correlativo. ¿Esto no es básicamente una suscripción por ID correlativo? ¿O entendimos mal el concepto?
Cito el requerimiento: 
>*"Localized Pokémon 
El proceso Team se suscribirá de manera global a esta cola de mensajes. Al recibir uno de los 
mismos deberá realizar los siguientes pasos:
1- Verificar si ya recibió en algún momento un mensaje de la especie del Pokémon asociado al mensaje. Si es así, descarta el mensaje (ya sea Appeared o Localized).
..."*

2) Cuando un team envía el mensaje GET, busca obtener las posiciones respectivas de los pokemons que necesita, para lo cual recibe la respuesta con el mensaje LOCALIZED. 
¿Qué sentido tiene recibir los LOCALIZED correspondientes a otros teams si no le serviría de nada conocer las posiciones de pokemons ajenos a su objetivo? Tengo entendido que los objetivos de cada team no pueden variar en tiempo de ejecución.
¿Esto no podría ser otro caso de suscripción por ID correlativo? 

Desde ya muchas gracias.
Saludos

**Comment by CMauro96** [comment]
Buenas buenas!

El cambio hecho en la versión V1.1 fue más que nada aclaratorio y a fin de deprecar algo que había quedado de la primer idea del TP (inlcuso antes de que fuera lanzado oficialmente).

A fin de alinearnos lo más posible con las implementaciones reales de MQ, todos los procesos deberán suscribirse de forma global a las colas y luego aplicar el filtro correspondiente sobre los mensajes que reciban.

Saludos,
Mauro

**Comment by Gonzalo-Avila** [comment]
Hola!

Perfecto, ahora si, gracias!

Saludos.
