### ISSUE TITLE
[Consulta] Se pueden desactivar los multiples escritorios?

### ISSUE THREAD

**Issue by Nachiten** [sisoputnfrba/foro#1664]
La pregunta es muy corta y es la misma del titulo.. yo no estoy acostumbrado a usar múltiples escritorios y me vuelve loco que a veces de manera automática y porque sí mis ventanas se mueven al escritorio dos.

Estoy hablando de la VM de lubuntu especificamente. Y queria saber si existe manera de matar los multiples escritorios (O ocultarlos de manera suficiente que no los use sin querer 🤕 )

Espero respuestas, muchas gracias :D

**Comment by mgarciaisaia** [comment]
[Acá](https://askubuntu.com/a/616533) menciona unos pasos para deshabilitarlo. Está en inglés, pero si le das bola a los nombres que están en mayúscula creo que deberías poder llegar. Avisá si no.

**Comment by enogueiras** [comment]
> [Acá](https://askubuntu.com/a/616533) menciona unos pasos para deshabilitarlo. Está en inglés, pero si le das bola a los nombres que están en mayúscula creo que deberías poder llegar. Avisá si no.

Lo probe y va perfecto!

**Comment by Nachiten** [comment]
> [Acá](https://askubuntu.com/a/616533) menciona unos pasos para deshabilitarlo. Está en inglés, pero si le das bola a los nombres que están en mayúscula creo que deberías poder llegar. Avisá si no.

Funciona perfecto. Gracias!!!
