### ISSUE TITLE
Duda - Conexiones para suscripción y envío de mensajes

### ISSUE THREAD

**Issue by lscolombo** [sisoputnfrba/foro#1665]
Buenas tardes!
Leimos la duda del [issue 1654](https://github.com/sisoputnfrba/foro/issues/1654) y no nos quedó del todo claro. 

Por eso queríamos consultar, para terminar de aclarar, si vamos a tener que mantener una **conexión abierta por cada suscripción a una cola de respuesta de mensajes**. 

Es decir, en el caso por ejemplo del Team, si vamos a mantener 3 sockets diferentes abiertos durante toda la ejecución (uno por **APPEARED**, uno por **CAUGHT** y otro por **LOCALIZED**) que esperen dichos mensajes. 

A diferencia de las colas de envío de mensajes, para los cuales entendemos que los procesos van a tener que abrir un socket y cerrarlo cada vez que envían un mensaje.
Gracias de antemano.
Saludos!

**Comment by FranciscoDumont** [comment]
Adhiero a la pregunta, tampoco me quedó claro la respuesta del #1654

**Comment by iago64** [comment]
Buenas buenas!

No se si llegaron a ver el [video](https://www.youtube.com/watch?v=gg03TNxz560&ab_channel=UTNSO) donde Nahue explica el funcionamiento de los procesos, si no lo vieron les recomiendo que lo hagan porque les puede responder esta y algunas otras futuras dudas :)

Respecto a esta duda puntual, la idea es que uds tengan una conexión por cada cola a la que se suscriben, como esta en el video de Nahue (minuto [3:38](https://www.youtube.com/watch?v=gg03TNxz560&feature=youtu.be&t=218&ab_channel=UTNSO))

Saludos.-

**Comment by javiermontivero** [comment]
Buenas! 
Me sumo a la pregunta, hay algun motivo para que sean 3 conexiones distintas o es solamente un tema de implementacion? Puede ser un problema tener una sola conexion para las 3 colas si el proceso entiendo los distintos mensajes correctamente?

Saludos!

**Comment by nahuemazzeo** [comment]
Hola @javiermontivero 

Es una definición de implementacion del trabajo practico y de adaptar el mismo lo mas cercano a como funciona realmente en la vida real el sistema de Message Queue.

Saludos.

**Comment by iago64** [comment]
@lscolombo quedo resuelta la duda? cerramos el issue?

**Comment by gatosantos9** [comment]
Hola! aprovecho el hilo para otra consulta! 
En el video habla de reintentar conectar con el broker cada cierto tiempo. Esto es en general o tambien debe reintentar por cada suscripcion?

**Comment by lscolombo** [comment]
Hola! Disculpen la demora en contestar. Sí, quedó resuelta la duda, muchas gracias!
