### ISSUE TITLE
Algoritmos de planificacion

### ISSUE THREAD

**Issue by FedeMacias** [sisoputnfrba/foro#1666]
Buenas, tengo una consulta

Como es la dinamica entre lo que dice el TP de "se activa el hilo del entrenador que esté mas cercano al pokemon" y los algoritmos en si? porque confunde un poco, yo lo pensaria como que hay que mandar al entrenador que quede primero en la cola de ready segun cada algoritmo, pero por ahi me equivoco.

Saludos!

**Comment by iago64** [comment]
Buenas buenas!

Parodiando un poco a un conductor de la tv argentina podria decir que:
_Esta mal... pero no tan mal..._

Efectivamente, vos vas a tener una serie de entrenadores en Ready, ahora bien, el algoritmo de ordenamiento que vas a tener para ordenar esa cola de ready no va a responder a un simple fifo, si no que en su lugar vas a tener que calcular la distancia de cada entrenador al siguiente pokemon que van a atrapar y de ahí que vas a ordenar del mas cercano al mas lejano.
Yo se que a simple vista bastante complejo, pero cuando llegues a la parte de Entrada / Salida y Disco vas a ver que hay ciertos algoritmos de planificación de disco que hacen justamente eso y van atendiendo las peticiones que están mas cerca (Perdon a los profes de teoria que les estoy spoileando una parte)

Cualquier cosa si no se entendió la explicación avisa.
Un abrazo.-

**Comment by FedeMacias** [comment]
En los SJF tiene sentido porque el que tiene menos ciclos de CPU va a ser tambien el que está mas cerca.

Pero en el caso del FIFO y del RR, ahi es donde entro un poco en conflicto, porque si el algoritmo es FIFO pero tengo que poner primero al que está mas cerca del pokemon, entonces estoy haciendo un SJF y no un FIFO.

Basicamente tendria sentido para mi no calcular las distancias en FIFO Y RR y poner el primero que esté en ready y en el caso de los SJF si calcularlas porque eso determina el uso de la CPU que van a tener. Lo estoy pensando bien?

**Comment by iago64** [comment]
Y si te digo que levantaste un issue de esos polémicos y super divertidos que van a hacer que los ayudantes peleemos a muerte en un battle royale de ideas?
Posta que nos dimos cuenta que decimos 2 cosas bastante contrapuestas en 2 partes del enunciado y no, no esta bueno, con lo cual, vamos a ver bien que es lo que quisimos definir y en base a eso les damos una respuesta mas clara :)

Abrazo y gracias, ahora se viene la parte divertida 😄

**Comment by FedeMacias** [comment]
Ah genial, lo que tiene mas logica para mi seria lo que dije en el post anterior, espero que gane esa opcion.

Bueno, dejo esto abierto entonces para alguna actualizacion??

**Comment by iago64** [comment]
Si si, que quede abierto el issue asi lo tenemos presente 😃

**Comment by iago64** [comment]
Aloha!
El battle royale de ideas termino, y claramente el problema es que nos comunicamos mal 😞 
En resumen (posiblemente se aclare en una v1.2 del enunciado) la cosa es asi:

Ready --> Exec 
Va por SJF, FIFO o RR (segun config)

Block --> Ready
Va por cercanía del entrenador, entonces en este caso el algoritmo de desbloqueo es el que calcula las distancias y no el de planificación de ready a exec.

Abrazo.-

**Comment by FedeMacias** [comment]
Buenisimo, muchas gracias!

**Comment by leobz** [comment]
Entendí  lo de Ready-->Exec, pero no me queda claro como seria lo de Block -->Ready.
Si tengo a entrenador1 y entrenador2 en estado bloqueado esperando un mensaje de confirmación CAUGTH para ponerse otra vez en Ready. Ahí ya están en la posición del pokemon.  Para que les serviría calcular la distancia?

**Comment by nahuemazzeo** [comment]
Hola @leobz !!

Entiendo la duda y es correcto lo que planteas pero tenemos que tener en cuenta que un entrenador puede estar en Block por varias razones:

1. Tiene la cantidad máxima posible de pokemon en su poder y no cumplió su objetivo
2. Esta esperando la respuesta de un mensaje Caught
3. Esta esperando la resolución de un Deadlock
4. No tiene la cantidad máxima de pokemon, no esta esperando una respuesta de Caught y el proceso Team no tiene pokemon disponibles en el mapa para que vaya a atrapar.

En este contexto, si un entrenador se encuentra en la casuistica 4 y llega un Appreared o Localized Pokemon que añada un Pokemon al mapa ese entrenador es un objetivo para que vaya a atraparlo (siempre usando la logica de que sea el mas cercano).

Saludos.

**Comment by iago64** [comment]
@FedeMacias quedo todo claro? cerramos el issue?

**Comment by FedeMacias** [comment]
cerramos nomas, gracias!!
