### ISSUE TITLE
Implementacion FS

### ISSUE THREAD

**Issue by enogueiras** [sisoputnfrba/foro#1668]
Hola buenas tardes, estoy tratando de avanzar la parte de Filesystem en Game-Card, quería consultarles si es factible utilizar FUSE para ello.

Desde ya, muchas gracias.
Saludos,
Emilio.

**Comment by iago64** [comment]
Buenas?

Que ventaja le encontras a usar FUSE en este tp?
Medio que la gracia de FUSE es que yo pueda tirar comandos como ls para listar un directorio, tirarle un cat a un archivo para ver el contenido... y en este tp me da la sensación que eso no va a pasar pero ni por cerca ;)

Abrazo.-

**Comment by enogueiras** [comment]
Si, entiendo, tendre que ir armando a mano las funciones dependiendo que
que vaya llegando y tenga que ir haciendo.

Aprovecho y consulto una más de FS, cuando el mismo levanta, ¿los pokemones
que tiene serían los que poseen los entrenadores originalmente, o arranca
vacio y despues se agregan por ejemplo a través de game-boy?

Muchas gracias.

Saludos,
Emilio.

**Comment by iago64** [comment]
Y... si, la idea es que veas que podes llegar a necesitar de todo lo que tiene un FS y que lo implementes siguiendo la estructura que les pasamos en el enunciado, justamente porque hay 2 alternativas:

1.- Que tengan que iniciar con un FS vacio y que les creemos los pokes desde un game-boy
2.- Que les demos un FS con algunos pokes como para que arranquen desde ahi (como para poder armar el escenario para alguna prueba sin tener que hacer 70 llamados con el gameboy para crear todos los pokes)

Abrazo.-

**Comment by enogueiras** [comment]
muchas gracias @iago64 me sirve la info.

Cierro.

**Comment by Santiago-Lovelli** [comment]
Buenas, consulta (o aclaración) sobre esto, en el soporte entendí que no darán las carpetas de los pokemones creadas, a lo sumo sin archivos de bloques de datos.

Ejemplo: si me llega un NEW PIKACHU, puede ser que no tenga el pikachu en ninguna posición, pero la carpeta [Montaje]/FILES/PIKACHU/ si existiría. En este caso si no existe la carpeta [Montaje]/FILES/PIKACHU, entonces no me tendría que llegar el mensaje de NEW POKEMON

Lo comento tanto como por si te ayuda como por si entendí mal la consulta que hice.

**Comment by enogueiras** [comment]
> Buenas, consulta (o aclaración) sobre esto, en el soporte entendí que no darán las carpetas de los pokemones creadas, a lo sumo sin archivos de bloques de datos.
> 
> Ejemplo: si me llega un NEW PIKACHU, puede ser que no tenga el pikachu en ninguna posición, pero la carpeta [Montaje]/FILES/PIKACHU/ si existiría. En este caso si no existe la carpeta [Montaje]/FILES/PIKACHU, entonces no me tendría que llegar el mensaje de NEW POKEMON
> 
> Lo comento tanto como por si te ayuda como por si entendí mal la consulta que hice.
> 
> (No puedo re abrir el issue)

Yo entenderia que si te llega uno nuevo creas todo, carpeta y archivos .bin que van dentro del directorio..

**Comment by iago64** [comment]
@Santiago-Lovelli Efectivamente como dice @enogueiras si te llega el NEW POKEMON, creas todo lo que haga falta.

Abrazo.-

**Comment by enogueiras** [comment]
> @Santiago-Lovelli Efectivamente como dice @enogueiras si te llega el NEW POKEMON, creas todo lo que haga falta.
> 
> Abrazo.-

Una mas y no jodemos mas!! jajaja, la implementacion habla de que los pokemones tienen su .bin (metadata) y tambien las posiciones, ¿dichas posiciones las manejamos como un archivo, por ej "txt" aparte? ¿deberia tener algun nombre especial este archivo?

Muchas gracias.
Saludos,
Emilio.

**Comment by iago64** [comment]
Ojo ahi, el metadata lo que te dice es el tamaño del archivo y el orden de los bloques que lo componen.
Despues la data con el formato que esta especificado en el enunciado (pagina 19):

![image](https://user-images.githubusercontent.com/1622109/80500158-364cb680-8944-11ea-9e40-bbe7c7ec456e.png)

Lo tienen que ir armando en los diferentes bloques que van a tenerlos en la carpeta [Punto_Montaje]/Blocks/

**Comment by enogueiras** [comment]
> Ojo ahi, el metadata lo que te dice es el tamaño del archivo y el orden de los bloques que lo componen.
> Despues la data con el formato que esta especificado en el enunciado (pagina 19):
> 
> ![image](https://user-images.githubusercontent.com/1622109/80500158-364cb680-8944-11ea-9e40-bbe7c7ec456e.png)
> 
> Lo tienen que ir armando en los diferentes bloques que van a tenerlos en la carpeta [Punto_Montaje]/Blocks/

mmmm lo de los bloques lo entendí, yo tengo la duda con las posiciones en cada fila, si eso debería ser un archivo aparte y si debería tener algún nombre o formato especial.

**Comment by Santiago-Lovelli** [comment]
@iago64 Okay, gracias

**Comment by iago64** [comment]
@enogueiras al contrario, es todo el mismo archivo, que vos lo vas a partir en bloques.

Por ejemplo si nos quedamos con lo que dice el ejemplo del enunciado:
1-1=10
1-5=1
3-1=2
7-6=1000

si tus bloques fueran de 10 bytes por ejemplo en el primer bloque tendrias:
1-1=10
1-5
en el segundo bloque tendrias:
=1
3-1=2
7
y en el 3er bloque tendrias:
-6=1000

Eso es porque vos tomas el contenido del archivo propiamente dicho y lo desparramas en los bloques de datos :)

Abrazo.-

**Comment by enogueiras** [comment]
@iago64 o sea que yo al archivo no lo tengo visible normalmente, ¿sino que tendría que seguir los bloques con alguna función para obtenerlo no? pregunto para saber si al momento de levantar el filesystem lo tengo que incluir en su carpeta respectiva.

**Comment by ncoen97** [comment]
Permiso, teniendo en cuenta que en teoría todavía no vieron Filesystem, dejo una imagen que por ahí te sirve a entender mejor como funciona el hecho de tener un archivo separado en bloques que se encuentran en distintos lugares:

![fs](https://user-images.githubusercontent.com/7952790/80609895-08807400-8a0f-11ea-8573-5a89b5c1f6b7.png)

El archivo lo vas a poder leer teniendo la metadata de cada pokemon y siguiendo la lista de bloques.
Saludos!

**Comment by enogueiras** [comment]
Que buena imagen @ncoen97 , sirve para entender mejor.

Abrazo,
Emilio.
