### ISSUE TITLE
Consultas varias del Broker

### ISSUE THREAD

**Issue by Kvothe838** [sisoputnfrba/foro#1669]
Con el grupo nos pusimos a leer toda la parte del Broker del TP y tenemos algunas dudas varias que ya busqué en el foro y no encontré. Las listo a continuación:

1. ¿El Buddy System entra en esta entrega? Pareciera que sí, pero preguntamos porque la clase que da ese tema está todavía unas 3 o 4 semanas por delante, y en 3 se hace el segundo checkpoint.
2. Página 13, Dump de la Caché: “Se enviará una señal SIGUSR1 que deberá ser manejada e inicializada”. ¿A qué se refiere con una señal?
3. Página 14, Tipos de Subscribers. El tercer item a tener en cuenta, dice "Esto quiere decir que si hay varios suscriptores en la cola de mensajes inicial puede haber varias respuestas al mismo (que productivamente deberían ser la misma respuesta) por lo que (...)". ¿A qué se refiere con que productivamente deberían ser la misma respuesta? No veo cómo las respuestas separadas que van llegando vayan a ser todas una misma respuesta. ¿No son respuestas asíncronas, cada una con su id?
4. Suscriptor Global de la misma página del 3: "Es responsabilidad del grupo interiorizarse y resolver cómo se identifica a un proceso específico frente a una caída y recuperación.". ¿A qué se refiere acá? Entiendo que el proceso está identificado siempre con un id, ¿por qué habría que volver a identificarlo? Capaz estamos pasando algo por alto.
5. Página 10, de Administración de Mensajes: "Uno de los requerimientos obligatorios que va a tener el Broker es que una vez inicializado ya no se podrá reservar más memoria dinámica para guardar los datos.". ¿Eso significa que desde que se inicia el Broker, no podemos usar funciones como malloc o realloc?¿o se refiere a la memoria Memoria Principal?

Disculpen si algunas preguntas son obvias o si salen leyendo alguna otra cosa, pero todavía no leimos los capítulos recomendados de los libros y lo vemos todo medio abstracto.

**Comment by AxelDellavechia** [comment]
Me sumo a la duda de la señal, la teoria dice SIGUSR1: ... el programador lo decide. Esta señal es para uso del programador.No la utiliza el sistema operativo.

**Comment by EzeDiaz** [comment]
Buenas! Vengo a colaborar un poco con algunas cosas que ya @nahuemazzeo contesto en el repo de mi grupo y con otras experiencias de recursante :grimacing:.

1. No se calienten mucho con el tema de las entregas, es más bien orientativo para saber qué progresos debería haber. Igual según entiendo, el próximo checkpoint habla de conexiones y eso con lo cual todavía nos podemos abstraer del asunto del Buddy System.


2. Te dejo las respuestas de Nahue:

> Es una señal que puede ser configurada para ejecutarse. Para enviar la señal simplemente se hace con kill [numero de señal] [proceso]. En este caso es kill -SIGUSR1 [proceso].
> 
> A nivel de codigo tienen que hacer una funcion que atrape dicha señal.
> 
> Con respecto al ID, es el ID del mensaje que se encuentra dentro de dicha particion. El ID del mensaje es el ID unico que genera el Broker a la hora de recibir el mensaje.

...y sobre el kill en especial...

> El kill se envía desde consola. Ustedes deben implementar la función que maneje esa señal en el código. Estamos en tratativas de armar un vídeo explicando señales. De base pueden usar esta presentación vieja que se entiende bastante el funcionamiento de la función.
> 
> http://faq.utnso.com.ar/signals


3. En esta también se me oscureció el panorama así que quedo a la espera de respuestas junto a ustedes.


4. Idem 3.


5. Básicamente se refiere a que vos al principio de todo haces un "malloc gigante" sobre el cual laburás siempre. Si después tenés que hacer un malloc para manejar un char* obvio que lo hacés, pero la "cache del broker" sobre la que vas a guardar el contenido de los mensajes y sobre la cual vas a aplicar los algoritmos (buddy y particiones), es ese malloc que hiciste al principio; del tamaño que dijera el archivo de configuración.

Espero haber tirado un centro y no un balazo, si algo de lo que dije no es tan así seguro me corregirán pero creo que mi corazón está en el lugar indicado. Saludos!

**Comment by Kvothe838** [comment]
@EzeDiaz mil gracias por la respuesta. El único que todavía me queda en el aire es el 5, no veo bien cómo se implementaría una cache con un malloc jaja, pero supongo que es ir viendo. También te recontra agradezco el link de signals, súper útil.

No cierro el issue porque quedaron la 3 y la 4.

**Comment by iago64** [comment]
Buenas buenas!
Vamos en orden, quedaron la 3 y la 4 o la 5?

Eventualmente no hay drama, vamos en orden inverso:

5.- Lo que te dice es que si por ej inicias el broker con 12mb para guardar datos del broker (porque te viene en el config en TAMANO_MEMORIA), no vas a poder reservar mas para **datos del broker**, nada te impide que hagas malloc por ejemplo para poder serializar un mensaje o para alguna estructura administrativa del broker.

4.- Un suscriptor va a recibir todos los mensajes que lleguen a la cola el problema de global o global por id es completamente del cliente, del lado del broker, lo que llega a esa cola se lo mandan y listo :)

3.- Lo que quiere decir es que uds tienen que saber que mensajes de los almacenados ya le mandaron a un cliente y cuales no, pero independientemente de eso, siempre tienen que mandar el mismo mensaje (o misma respuesta), no es que cambia según el cliente, el contenido es el mismo.

Saludos.-

**Comment by EzeDiaz** [comment]
4.- Perfecto, pero en cuanto a "cómo se identifica a un proceso específico frente a una caída y recuperación". Se supone que yo debo ser capaz de, si se me baja alguien, luego poder saber que ese tipo se volvió a conectar? A mi parecer, a los efectos del funcionamiento de la message queue, me importa poco si un tipo que estaba antes se volvió a conectar; a todos los trato como gente nueva y punto. No sé si es una decisión de diseño válida.

3.- No me termina de cerrar. Vamos con un ejemplo: Team A manda un GET Pikachu, Team B manda otro GET Pikachu. Para cada uno de ellos, Broker genera un id y se los informa. Luego dichos mensajes llegan a Game Card para lo cual genera una respuesta LOCALIZED cada una con el id correspondiente dependiendo de a qué GET contesta. Broker entonces recibe dos LOCALIZED Pikachu. Debe guardar uno solo? O los dos? Antes, me hubiese jugado a full que guardaba los dos y eso no me parece redundante, porque el id que tienen los vuelve inequívocos y es crucial para que cada uno interprete el mensaje que le corresponde cuando se los mande; pero ahora (v1.1 del enunciado) Team se suscribe siempre global con lo cual con mandar uno solo alcanza, independientemente del id y en tal caso quizás sí sería "redundante". No quiero seguir empantanando, eventualmente este inciso 3 podría merecer su propio issue.

Gracias!!

**Comment by karengrams** [comment]
¡Buenas!

¿Como va? Vamos de a poco, respecto al 3.

Primero, antes de tomar tu ejemplo @EzeDiaz, cuando se habla de que el Team se subscribe globalmente, quiere decir que el proceso Team quiere escuchar todos los mensajes de una cola especifica, es decir, va a recibir todos los mensajes de la cola a la cual se subscribió, por ende, cuando Dami dijo:

> Lo que quiere decir es que uds tienen que **saber que mensajes de los almacenados ya le mandaron a un cliente y cuales no**, pero independientemente de eso, siempre tienen que mandar el mismo mensaje (o misma respuesta), no es que cambia según el cliente, el contenido es el mismo.

Se refería a que el Broker debe saber que mensajes le mando a un Team especifico, para no volver a mandarle el mismo mensaje, dado que no estaría bien que el proceso reciba dos veces el mismo mensaje.

Pongo un ejemplo: supongamos que tenemos dos team's (Team nro. 1 y Team nro. 2), ambos se subscriben globalmente a las seis colas que maneja el Broker; cuando se inician mandan un GET para obtener todos los Pokemon's que necesitan. Ahí vamos bien, después el Game Card le mandara al Broker una X cantidad de LOCALIZED, con los respectivos Pokemon's que encontró. Estos mensajes, _van a guardarse todos en la memoria_, a pesar de, como dijo Eze en su ejemplo, sean iguales, _¿por que? Porque son respuestas distintas a mensajes distintos_. 

Bien, sigamos con el ejemplo: el Broker ahora, tiene que informarle a todos los Team's estos mensajes LOCALIZED que recibió por parte del Game Card; tomara a los subscriptores de la cola, y le mandara todos los mensajes que corresponda, y acá es donde viene lo que dijo Dami: _el Broker debe saber que mensajes mando a cada Team para no volver a mandárselos_, en este caso, como anteriormente no le mandamos ninguno, le informamos a ambos Team's los mensajes LOCALIZED que llegaron. Pero en caso de haberselos mandado al Team nro. 1, pero no al nro. 2, entonces se debe identificar que al Team nro. 1 no se le debe mandar esos mensajes dado que ya se los mando ¿Se entendió? Respecto a la pregunta inicial, ¿quedo claro lo que quiso decir Dami?

¡Saludos!

**Comment by EzeDiaz** [comment]
Por mi clarísimo. Queda pendiente entonces el inciso 4 o alguna otra duda de los chicos que venían siguiendo este issue. Mil gracias Karen!

**Comment by karengrams** [comment]
¡Perfecto! Respecto a la cuatro, fíjense que todo el párrafo se esta hablando del manejo de mensajes, por ende, si se llega a caer un proceso, y lo vuelvo a levantar, tengo que poder identificar a ese proceso, es decir, si yo lo estoy manejando con un cierto ID, saber que ese nuevo proceso que se acaba de subscribir, era el mismo que antes y asignarle el mismo ID, y luego proceder a mandarle los mensajes que correspondan.

¡Saludos!

**Comment by EzeDiaz** [comment]
Entonces debería incorporar alguna especie de handshake entre el proceso que se quiere conectar y el Broker, donde dicho proceso me proporcione algo de información mediante la cual yo lo pueda identificar unívocamente. Correcto? O no conviene complicarnos en ese sentido? Porque si no, honestamente, no se me ocurre cómo identificar a un proceso para poder diferenciarlo de otro. Gracias!

**Comment by ncoen97** [comment]
La opción que planteas es correcta, saludos!

**Comment by Kvothe838** [comment]
Clarísimo todo. Gracias a todos!
