### ISSUE TITLE
Error al incluir librerias propias

### ISSUE THREAD

**Issue by gaboalvarez** [sisoputnfrba/foro#1670]
Comento el problema: sigo paso a paso la creacion e inclusión de librerias propias dentro del proyecto (video de la catedra: https://www.youtube.com/watch?v=Aw9kXFqWu_I ), para que los otros proyectos dentro del mismo puedan tener acceso, pero cuando escribo el include, eclipse no encuentra el archivo al cual quiero referenciar.
Ejemplo:
Nosotros tenemos el proyecto Shared, y dentro de él tenemos la carpeta src, y dentro de éste algunos archivos .c y .h

Dentro del proyecto GameBoy escribimos #include <src/utils.h> y nos tira un error "no such file or directory", intentamos tambien #include "src/utils.h" pero tampoco funciona
( tp-xxx/Shared/src/utils.h  seria nuestro directorio )

Alguien tiene alguna idea de cual puede ser el problema ? seguimos paso a paso el video y no entendemos.

Aclaramos: tambien vimos el issue #1641 pero no soluciona nuestro problema.

**Comment by mgarciaisaia** [comment]
👋 ¡Hola!

Justamente este es el problema de no darle bola al video de [reporte de errores](https://faq.utnso.com.ar/errores-eclipse): seguramente estés teniendo _exactamente el mismo problema_ que el issue que viste, pero como no podés comparar el log de la compilación tuyo con el del otro issue, ni ver qué cambió cuando la compilación le anduvo al otro grupo, estamos de vuelta repitiendo este esfuerzo.

Apostaría, incluso, a que hay al menos 2 issues de otros grupos de cuatris anteriores con el mismo problema. Y con la explicación y la solución ya escrita.

Así que, dale - mirate el video, subinos las cosas que ayudan, y busquemos issues anteriores con la solución al problema :)

**Comment by gaboalvarez** [comment]
Ya lo arregló un compañero del equipo, teniamos unos problemas con los makefiles de cada proyecto, y re-haciendo todo devuelta pudimos.
