### ISSUE TITLE
Problema para entrar al Discord de los sabados de soporte

### ISSUE THREAD

**Issue by TheLucasPrada** [sisoputnfrba/foro#1671]
Buenas! abro este Issue porque no estoy podiendo entrar al Discord de SO, cuando entro al link, me sale que la invitacion no es válida:

![problema (1)](https://user-images.githubusercontent.com/31250511/80550462-90766780-8996-11ea-9153-7c57f3dd7ef2.png)

Me comunique con los ayudantes por este tema y me pasaron este otro link: https://discordapp.com/channels/687634725270978560/687634725270978564 pero tampoco estoy podiendo llegar a nada, termino en un limbo.

![problema](https://user-images.githubusercontent.com/31250511/80550468-92d8c180-8996-11ea-9e8e-c7fd8f75f5bf.png)

Entiendo que no estaría teniendo permisos para unirme? algún consejo?

**Comment by mgarciaisaia** [comment]
👋 ¡Hola @TheLucasPrada!

Ahí ví que el código de invitación había expirado. Agregué uno nuevo (que no expira) en https://faq.utnso.com.ar/discord-invite

¿Te acordás dónde estaba publicado el link anterior? Así lo corregimos.

Gracias por el chifle, y avisá si te funciona este 👍

**Comment by TheLucasPrada** [comment]
Listo, genial! ahí me pude unir, muchas gracias!

El link anterior que use, fue el del mail de bienvenida de los ayudantes:
Saludos!
