### ISSUE TITLE
[Gameboy] Logs al enviar mensaje APPEARED_POKEMON

### ISSUE THREAD

**Issue by leobz** [sisoputnfrba/foro#1672]
Las acciones a loguear en este archivo son:
Buenas! En el enunciado dice "Las acciones a loguear en este archivo son:
1.Conexión a cualquier proceso.
2.Suscripción a una cola de mensajes.
3.Llegada de un nuevo mensaje a una cola de mensajes.
4.Envío de un mensaje a un suscriptor específico."

Cuando ejecute en consola el siguiente comando(enviar mensaje a Team):
~~~
> ./gameboy  TEAM  APPEARED_POKEMON  pikachu  1  1
~~~

Debería loggear solo le 1? Estaba pensando en poner también el 4, pero no se si Team es suscriptor del Gameboy, ya que no hay ninguna Queue de por medio.

**Comment by iago64** [comment]
Aloha!

Efectivamente, si no tenes una suscripción o no te llegan mensajes de un cola a la que estas subscripta no vas a poder loguear eso.
Ahora el 1 y el 4 son acciones que generalmente vas a hacer, con lo cual, ahi no tenes mucho para evitar.

Abrazo.-

**Comment by leobz** [comment]
Dale gracias!
