### ISSUE TITLE
Duda - ID_MENSAJE

### ISSUE THREAD

**Issue by thomykut** [sisoputnfrba/foro#1673]
Buenas, estuvimos charlando con el equipo y llegamos a la conclusión que de poder elegir los campos que van a tener los distintos structs, correspondientes a cada tipo de mensaje, los haríamos distinto a como se encuentran en el TP:

Hay alguna razón para que estos 2 mensajes tengan un ID_MENSAJE?
1. ./gameboy BROKER APPEARED_POKEMON [POKEMON] [POSX] [POSY] [ID_MENSAJE]
2. ./gameboy GAMECARD NEW_POKEMON [POKEMON] [POSX] [POSY] [CANTIDAD] [ID_MENSAJE]

Por otro lado, de qué manera podemos generar este ID_MENSAJE sin que se pise con los generados por el Broker (todos los otros):
./gameboy GAMECARD CATCH_POKEMON [POKEMON] [POSX] [POSY] [ID_MENSAJE]
Además, este tipo de mensaje tiene como única intención robarle pokemons a los teams no? Ya que a nadie le deberia "servir" ese ID_MENSAJE. De ser así, proponemos como solución a nuestra pregunta original en cuanto al mismo, enviar este mensaje con ID_MENSAJE=0, con el objetivo de que todos los teams descarten la respuesta del mismo (CAUGHT_POKEMON).

**Comment by MaSosa314** [comment]
Aprobecho el issue para hacer una pregunta mas. Esos ID_MENSAJE ¿Hacen referencia al id correlativo o al id especifico de ese mensaje ?

**Comment by tferraro** [comment]
Es el id correlativo! 😎
El id específico del mensaje siempre lo va a autogenerar el Broker 😉 
Capas llamarlo ID_MENSAJE no es del todo expresivo. Me llevo iterar esa parte del enunciado para que esté aclarado 😄

**Comment by FacuTadic** [comment]
Hay algun tipo de dato particular de ID_MENSAJE? Porque no lo vi en el Anexo 2

**Comment by ncoen97** [comment]
Buenas, el ID de los mensajes queda a definir por ustedes, saludos.

**Comment by EzeDiaz** [comment]
Hola! No quiero ser muy disruptivo, pero en principio no había pensado en un ID específico del mensaje, sólo en el ID que uso como correlativo. Por qué? La generación de IDs, generalmente, tiene por objetivo identificar unívocamente a algo; en este caso un mensaje. El tema es que con el ID correlativo que le genero ya logro una identificación unívoca del mensaje: no va a existir otro mensaje del mismo tipo con el mismo ID correlativo. Es decir, no va a haber otro GET Pikachu 6. Sí puede haber un LOCALIZED Pikachu 6, pero el hecho de que cambie el tipo de mensaje me ayuda a diferenciarlo.

Por esto, no veo la necesidad de tener un ID específico del mensaje además del ID correlativo. Distinto sería si cumple otra funcionalidad que no estoy identificando, que es lo que más me preocupa y el motivo de por qué hago el planteo. Gracias!

**Comment by tferraro** [comment]
Maso, el ID correlativo es una referencia al anterior mensaje, el ID del mensaje actual te sirve para que puedas referenciar este mensaje a futuro.

Me voy a robar un ejemplo de @Zheoden :
```
Asumí que tenes un GET pokemon y el broket te va a decir,
"el mensaje que mandaste es el ID1".
Cuando Gamecard responde, le va a decir 
"este es correlativo al 1" y el broker le va a generar un id único.
Esto hace que al team le llegue el ID del mensaje 2 y ID correlativo 1
```

**Comment by ncoen97** [comment]
Buenas, esto quedó resuelto? Si es así les pido que cierren, sino pueden seguir consultando.

**Comment by karengrams** [comment]
¡Buenas! 
Cierro el issue por inactividad, en caso de que haya otra duda, no duden de reabrirlo.
¡Saludos!

**Comment by Frank115** [comment]
Buenas, perdón por re-abrirlo, pero leyendo el ejemplo que pusieron tengo una duda:

Ese ID de mensaje 2, le sirve de algo al Team? No logro encontre la utilidad para el mismo. ( A menos que sea la parte de los logs del TEAM (item 7): "Llegada de un mensaje (indicando el tipo del mismo y sus datos)."

Además en el mensaje APPEARED_POKEMON que puedo mandar del gameboy al team no hay ningun id en sus argumentos.

**Comment by ncoen97** [comment]
@Frank115 Recién veo esto, no reabriste el issue. Seguimos con esta duda en el #1719. Saludos!
