### ISSUE TITLE
Flujo de suscripción a las colas del Broker

### ISSUE THREAD

**Issue by nburza** [sisoputnfrba/foro#1674]
Buenas, no nos quedo claro como hacen los procesos para suscribirse a las colas del Broker. Nosotros imaginábamos que seria mediante un mensaje adicional con un `codigo_operacion` que indique a que cola me quiero suscribir, similar al que puede enviar el GameBoy. Nos parece que la respuesta del issue #1654 esta en sintonía con lo que estábamos pensando.

> (...) Cuando se conecten a este socket los distintos clientes van a tener que definir el porque se comunican a el (si es por una suscripción a una de sus colas o para enviarle un mensaje). Si la pregunta iba referida a si tenes que tener un Socket de escucha para cada cola, la respuesta es NO. El broker solo maneja un socket de escucha y luego **DEPENDIENDO EL MENSAJE QUE RECIBA ES A LA COLA QUE SE SUSCRIBIRÁ O EL MENSAJE QUE RECIBIRÁ.**

Pero en el issue #1657, se da a entender que al saber que un proceso (por ejemplo un Team) se quiere conectar al Broker ya podemos suscribirlo a las colas que corresponda sin necesidad de recibir un mensaje

> En cuanto a la ultima dado que las colas son fijas y no puede cancelar la subscripcion, no es necesario un mensaje para indicar que se quiere subscribir, sino simplemente cuando se conecta, pueden ver si es un team, y en ese caso lo subscriben automaticamente a las colas correspondientes.

Con esta opción no entendemos como podrías informar que sos un Team antes de que el Broker haga un `recv` de un mensaje.

**Comment by iago64** [comment]
Buenas buenas!
No se quemen la cabeza con esto que no es lo mas grave :)
Si uds en su solución lo que plantean es que tienen que si o si mandar a que cola se suscriben porque asi tienen planteado el flujo en el broker no hay problema. Lo importante del issue #1657 es que el team no puede cancelar la suscripción  :)

Abrazo.-

**Comment by nburza** [comment]
Ok, entendemos que nuestra propuesta de flujo sería válida. Igualmente, sin querer enroscarnos, nos queda la duda de cómo se encararía  la alternativa. Osea, ¿podríamos saber si un proceso que se quiere conectar al Broker es un Team o un GameCard sin recibir ningún mensaje?

**Comment by tgullon** [comment]
Me adhiero a esa consulta. Con el equipo, de primeras llegamos a la conclusión de que sería organizado y coherente identificar un código de operación preliminar a todo lo demás que delate una de dos opciones: que el cliente se conecta _con la intención de que lo identifiquen y lo suscriban globalmente_, o que el cliente esta _mandando un mensaje_ (caso en el cual el cliente no le interesa que se lo identifique a él sino que identifique **el tipo de mensaje** que esta enviando para que el broker le conteste inmediatamente el id correlativo correcto para que lo reciba por alguna de las colas en las cuales ya esta suscripto).

Sin embargo, si hubiera una forma de que solo con el hecho de recibir la conexión (y con ello, únicamente descubrir un nuevo socket/fileDescriptor) el broker pueda darse cuenta de que tipo de cliente se trata (un Team, una Gamecard o la Gameboy) sin hacer ningún recv(), nos gustaría saberlo para tenerlo en cuenta en el manejo de estructuras y protocolos. 

Saludos!

**Comment by ncoen97** [comment]
Chicos, no hay forma de saber de que modulo se te están conectando sin hacer ningún recv(), lo que se me ocurre es que deben tener algún "código de modulo" o algo por el estilo. Igualmente no está mal la manera que están planteando ustedes y no es un problema manejar códigos de mensaje mientras los tengan ordenados en un enum en común.

**Comment by iago64** [comment]
Aloha!

Como dice bien Nico, es imposible que sepan que se les esta conectando sin hacer un recv(), de hecho, podría ser incluso cualquier otra cosa que se les quiera conectar (por ej un telnet) con lo cual, si o si van a estar obligados a hacer un recv(), para esto, lo que van a terminar implementando va a ser un mínimo intercambio de mensajes que va a ser algo así como una especie de presentación (o hanshake) entre ambos procesos como para saber que se les esta conectando a su broker.

De todas formas, el planteo que hicieron uds no esta mal y es completamente valido :)

Abrazo.-

**Comment by nburza** [comment]
Muchas gracias por todas las respuestas. Con esto nos queda más claro el concepto de la suscripción.
