### ISSUE TITLE
Problema con GIT

### ISSUE THREAD

**Issue by Samuel0023** [sisoputnfrba/foro#1675]
Hola!

El dia de hoy quise entrar al repo de mi grupo [Los Socketes] , pero me figura que no tengo los permisos para acceder. No se si toque algo que no debia por boludo o que? ,  tambien mande esta consulta a mis ayudantes asignados pero no me respondieron aun. En fin quisiera que me pudieran agregar nuevamente. Un saludo y disculpen las molestias...

**Comment by mgarciaisaia** [comment]
¡Hola!

Parece que nunca aceptaste la invitación al team que te mandó el sistema al confirmar el grupo. Ahí le dí resend, te debería haber llegado un mail de Github. Aceptalo y deberías poder entrar.

Chiflá cualquier cosa.

**Comment by Samuel0023** [comment]
Dale , muchísimas gracias!!!
