### ISSUE TITLE
Algoritmo elección de victima - Particiones

### ISSUE THREAD

**Issue by NicoCives** [sisoputnfrba/foro#1676]
Buenas!
Tengo la siguiente duda sobre los algoritmos de eliminación de partición cuando luego de la compactación no se haya podido encontrado una partición libre...
Se cual sea el algoritmo (FIFO o LRU), precisaría de la partición una referencia del ultimo uso, algo así como un Timestamp y ademas un puntero que me indique la siguiente victima.
Estoy en lo correcto?

Slds.

**Comment by iago64** [comment]
Buenas buenas!
Efectivamente vas a necesitar alguna estructura administrativa que te permita saber el orden en el que utilizaste las particiones o en que momento fueron utilizadas.
El tema de manejarlo con un timestamp o con un contador ya queda a criterio de cada grupo, piensen que les resulta mas simple, si estar haciendo operaciones de tiempo o estar viendo cual es el el numero mas bajo dentro de la lista (ya que si tenes un contador que incrementas con cada acceso a memoria podes saber cual fue el que se uso hace mas tiempo buscando el numero mas chico)

Abrazo.-

**Comment by NicoCives** [comment]
Genial.
Muchas Gracias!
