### ISSUE TITLE
Algoritmos de Planificación y Distancia al pokemon

### ISSUE THREAD

**Issue by Ramiro-luengo** [sisoputnfrba/foro#1677]
Hola quería preguntar unas cosas:

1. No me quedo claro lo que explicaron en este issue [Algoritmos de Planificacion](https://github.com/sisoputnfrba/foro/issues/1666) e hice uno nuevo para no mezclarlo con la otra pregunta. En el caso que yo tenga 2 entrenadores con la misma distancia, yo paso a ready **SOLO** el primero o tengo que pasar los dos y ya en la cola de ready me rige el algoritmo de planificacion?
2. Cual es el criterio para pasar los entrenadores que tengo en **NEW** a **READY**? solo el/los que este/n mas cercano/s al pokemon??

Me gustaría tener bien definido cuando es que tengo que utilizar la distancia al pokemon y cuando el Algoritmo de Planificación.

**Comment by iago64** [comment]
Aloha! creo que ese issue tiene algunas respuestas mías, así que aprovecho y las aclaro por aquí también 😄 

1.1- El método de elección en un desempate (por convención mas que por otra cosa) es siempre FIFO, con lo cual, si pasarías al primer entrenador. 
1.2.- Una vez que estas en **READY** ya dependes del _algoritmo de planificación_ definido (SJF, RR o FIFO)

2.- Efectivamente, la entrada a **READY**, ya sea desde **NEW** o **BLOCK**, va a darse por el que esta mas cerca del pokemon.

Abrazo.-

**Comment by Ramiro-luengo** [comment]
Gracias por el pikachu!! me quedo todo claro!!
