### ISSUE TITLE
Error makeflie (Resubido por error de imagen)

### ISSUE THREAD

**Issue by FacuTadic** [sisoputnfrba/foro#1679]
Hola estuve tratando de hacer pruebas de GameBoy ustilizando el proyecto de Game & Watch para poder compilarlo usando el makefile pero me tira errores a la hora de compilar y no son errores de sintaxis sino del makefile. Me estaria complicando poder codear y compilar en paz. Adjunto la imagen (ya probe limpiar el buffer y todo lo del video)

Link a la imagen por las dudas
https://drive.google.com/file/d/19BtX-5SMQh04M9oN06wz_Y7GqmNwjkVS/view?usp=sharing

![Captura de pantalla de 2020-04-27 21-12-15](https://user-images.githubusercontent.com/31359419/80662413-91c39500-8a67-11ea-9392-8003154b8df7.png)

**Comment by iago64** [comment]
Lindo mambo se estan pegando con el makefile.
Por esas casualidades no pasaste por los videos que tenemos de makefile en el canal no?
Parte 1: https://www.youtube.com/watch?v=OHfMNqe-Fdw&ab_channel=UTNSO
Parte2: https://www.youtube.com/watch?v=JafEOsYEdVI&ab_channel=UTNSO

Aun asi, para evitarse dolores de cabeza pueden usar los makefile que les genera automaticamente eclipse al crear un proyecto nuevo como para que no esten perdiendo tiempo ya que con el gameboy no es tanto, pero con otros proyectos como el broker o el gamecard puede que se les haga pesado el manejo del makefile a mano.

Saludos.-

**Comment by mgarciaisaia** [comment]
El error no es del `Makefile`.

La línea que se ejecuta (al menos _la única que se ve ahí_) para compilar parece ser correcta: compilar varios archivos `.o`, linkeados con un par de bibliotecas, en un binario `tp0`. El comando es sintácticamente correcto, y probablemente sea correcto, incluso.

El problema está en que parece que tenés `definiciones múltiples de 'modulos'`, que desconozco si es una variable, una función, o qué.

¿Qué chances habrá de que en `tp0.c` hagas un `#include "utils.c"`? Y, si no, ¿puede que haya alguna variable/función _definida_ (no _declarada_) en `utils.h`? En ese caso, si `tp0.c` hace `#include "utils.h"`, y `utils.h` define una variable o función, esa definición pasaría a estar tanto en `tp0.o` como en `utils.o`, y, al compilarlos juntos, `gcc` se queja de la doble definición.

**Comment by afilgueira** [comment]
@FacuTadic POR FAVOR no suban capturas de pantalla como esta. Nosotr@s nos tomamos el tiempo de leer y contestar cada uno de los issues; tómense el tiempo de reportarlo correctamente.

**Comment by FacuTadic** [comment]
@mgarciaisaia me solucionaste el problemon que tenia y lo peor de todo es que era algo tonto y ni cuenta me di. Mil gracias
@iago64 No los vi! Igual me vienen bien para cuando haya que ir preparando gamecard y para mis compañeros que estan con broker. Gracias
@afilgueira Perdon profe, no sabia bien como reportar, me vi el video pero muchas formas no tenia. Estaba codeando en un proyecto piloto

**Comment by afilgueira** [comment]
Facundo: ayer te pasamos este video por discord. Mirá este instante (https://youtu.be/18cN8Jk4WjQ?t=287). Cierro nomás.
