### ISSUE TITLE
error al cargar una archivo. config

### ISSUE THREAD

**Issue by emarcosgv** [sisoputnfrba/foro#1680]
👋 ¡Hola!

Ojalá el foro te sea de ayuda. Para agilizar las cosas para tod@s, te pedimos un par de
cosas antes de que hagas una nueva pregunta:

- [ ] 🔍 ¡Buscá! Acá arriba hay un "Search" que te permite buscar consultas que hayan
hecho antes tus compañer@s. Quizá ya encontrás la respuesta servida.
- [ ] 📝 ¡Se detallad@! Si no encontraste tu respuesta, se tan clar@ y detallad@ en tu
pregunta como puedas. Tratá de contar qué hacés, qué observás, y qué entendés a partir
de eso - ¡pero sin mezclarlas!. Si subís capturas de pantalla, de todas formas escribí el problema/error que estás teniendo. Eso nos ayuda a usar el buscador a futuro.
- [ ] 📹 ¡Mirá cómo reportar desde Eclipse! Si tu problema es con código en Eclipse,
mirá el video [Cómo reportar errores desde Eclipse](https://youtu.be/18cN8Jk4WjQ) para
tener todos los detalles que necesitamos.

🙇 Gracias por leernos, y ¡éxitos!

**Comment by emarcosgv** [comment]
Hola, tengo este mensaje al levantar el archivo de configuración. 
../src/broker.c: In function ‘main’:
../src/broker.c:10:2: warning: implicit declaration of function ‘cargarConfigBROKER’ [-Wimplicit-function-declaration]
  cargarConfigBROKER();
 tengo una estructura global que tiene los campos del archivo broker.config.
despues uso las commons para cargar mi estructura.
hice un malloc(sizeof(miEstructura); me funciona bien, carga el archivo de configuracion perfectamente, pero ese mensaje aparece y no tengo nada raro. No entiendo porque me aparece ese error.

**Comment by afilgueira** [comment]
Hola, en el primer mensaje (que asumo que subiste por error) hay un link que explica cómo reportar errores desde eclipse. Con la info que nos estás pasando no te podemos decir absolutamente nada, más allá de intentar adivinar y con un poco de suerte, pegarle. 

Mirate el video, danos esa info, y vemos qué problema tenés.

Saludos!

**Comment by emarcosgv** [comment]
Hola Adriano, mire el video y te adjunto el error que me tira al compilar.

19:07:51 **** Build of configuration Debug for project broker ****
make all 
Building file: ../src/broker.c
Invoking: GCC C Compiler
gcc -I"/home/utnso/workspace/tp-2020-1c-Omnidata/MiLibreria" -O0 -g3 -Wall -c -fmessage-length=0 -fPIC -MMD -MP -MF"src/broker.d" -MT"src/broker.o" -o "src/broker.o" "../src/broker.c"
../src/broker.c: In function ‘main’:
../src/broker.c:8:2: warning: implicit declaration of function ‘cargarConfigBROKER’ [-Wimplicit-function-declaration]
  cargarConfigBROKER();
  ^
Finished building: ../src/broker.c
 
Building file: ../src/funcionesBroker.c
Invoking: GCC C Compiler
gcc -I"/home/utnso/workspace/tp-2020-1c-Omnidata/MiLibreria" -O0 -g3 -Wall -c -fmessage-length=0 -fPIC -MMD -MP -MF"src/funcionesBroker.d" -MT"src/funcionesBroker.o" -o "src/funcionesBroker.o" "../src/funcionesBroker.c"
Finished building: ../src/funcionesBroker.c
 
Building target: broker
Invoking: GCC C Linker
gcc -L"/home/utnso/workspace/tp-2020-1c-Omnidata/MiLibreria/Debug" -o "broker"  ./src/broker.o ./src/funcionesBroker.o   -lcommons -lpthread -lMiLibreria
Finished building target: broker
 

19:07:52 Build Finished (took 445ms)

**Comment by afilgueira** [comment]
Buenísimo. Fijate que lo que te tira no es un error, sino un warning. 

El warning te dice "Ojo, estás usando una función cuya firma/prototipo no declaraste". Una buena práctica es hacerlo, pero como te pasa a vos _es perfectamente normal_ que igual ande.

Tenés un .h para las firmas? Si es así, está la función en cuestión? Tené en cuenta que las mayúsculas importan para estos casos.

Saludos!

**Comment by emarcosgv** [comment]
tengo un .h para las firmas, efectivamente el problema estaba ahi, en la firma estaba asi;
void cargarConfigBROKER(void);
no se porque le pasamos void como argumentos a una funcion que no quiero pasarle nada cuando la invoco. Borré ese void y se fue el warning, en que caso deberia pasar ese void como argumento. Esta bien que te consulte por aca o te mando mail para aclarar esto? ya que la issue que abri ya se soluciono
.Gracias y me da bastante tranquilidad que no me aparezca mas ese mensaje horrible.

**Comment by emarcosgv** [comment]
Description	Resource	Path	Location	Type
Invalid project path: Include path not found (commons).	broker		pathentry	Path Entry Problem

Description	Resource	Path	Location	Type
Invalid project path: Referenced project is not accessible.	broker		pathentry	Path Entry Problem
este es otro warning que encontre en problems

**Comment by afilgueira** [comment]
Sobre tu 1er, entré a tu repo (aprovechando que tengo las rutas en el log que pasaste) y vi que en el .h tenés "void cargarConfigBroker(void)"  (Broker != BROKER). Me parece que el warning viene por ese lado.

Sobre el 2do, lo mismo que te decía arriba. Con esta info que me das no puedo ni intentar adivinar 🤷‍♂️. Subilo porfa con más detalle (y si es algo separado en otro issue y lo vemos).

Saludos!

**Comment by emarcosgv** [comment]
voy a buscar algo más, pero ahora al compilar no me tira errores solo si toco en la parte de problems me tira ese warning, lo que te copie antes me salia al compilar. Abro otro issue igualmente. Gracias por la ayuda.

**Comment by iago64** [comment]
@emarcosgv Si vas a abrir otro issue este lo cerramos?

Por otro lado, a modo de comentario, los warnings no necesariamente son errores per se, con lo cual tenelos en cuenta pero no te vuelvas loco por arreglarlos todos.

Abrazo.-

**Comment by emarcosgv** [comment]
Cierro el issue, pero la verdad es que los warnings me molestan. Gracias igualmente, me ayudaron un montón, pude avanzar bastante.
