### ISSUE TITLE
Eclipse se cierra solo a los 10 segundos de abrirlo

### ISSUE THREAD

**Issue by julchat** [sisoputnfrba/foro#1681]
Hola, como el título dice, cuando abro quiero usar eclipse se abre y aprox  a los 10 segundos se cierra, escribiendo en un archivo de error en /home/utnso , uno por cada vez que lo abro y se crashea.

Lo que estaba haciendo despues del primer crash era intentar crear un build target para ver si le podia decir "compilame esta carpeta/subproyecto nada mas", salio a la derecha abajo una notif de actualización, y cuando la quise quitar eclipse dejo de responder y lo tuve que finalizar a la fuerza.
Mando el primer archivo y el último archivo de todos
Gracias!
[hs_err_pid6516.log](https://github.com/sisoputnfrba/foro/files/4561583/hs_err_pid6516.log) (primero)
[hs_err_pid10156.log](https://github.com/sisoputnfrba/foro/files/4561584/hs_err_pid10156.log) (ultimo)

**Comment by iago64** [comment]
Una consulta rapida, probaste cambiando el workspace de eclipse? 
De base los errores son diferentes, con lo cual de entrada quisiera validar a ver si es algun problema de los archivos del workspace de eclipse.-

Saludos.-

**Comment by mgarciaisaia** [comment]
Probablemente se jodió Eclipse mientras intentaba guardar las settings del workspace. Es decir, le pegaste a un bug de Eclipse. Felicitaciones (?).

Cambiá/borrá el workspace, como dice Dami, y probablemente salga andando. La cagada es que vas a tener que volver a importar tus proyectos.

**Comment by thomykut** [comment]
Ya que veo este issue les comento, a mí se me cierra el eclipse cada 2/3hs de estar laburando en la VM, ni idea porqué

**Comment by afilgueira** [comment]
@thomykut con la info que nos diste no podemos hacer mucho más que adivinar 🤷. Reportá un issue con las caracteristicas de tu VM, el log como nos dejaron arriba y podemos ver de que se trata. Saludos!

**Comment by julchat** [comment]
Ahi se solucionó! Muchas gracias!

**Comment by SofiCortes** [comment]
@julchat reabriste el issue. Alguna otra duda relacionada con este problema?
