### ISSUE TITLE
Duda administración de mensajes [Broker]

### ISSUE THREAD

**Issue by ggallici** [sisoputnfrba/foro#1683]
Dado que solo el Broker necesita saber a quienes fueron enviados los mensajes y quienes lo recibieron, se nos ocurrió que internamente éste maneje una estructura administrativa que wrappee el mensaje propiamente dicho, agregándole esta información adicional. 

De ésto nos surgió la siguiente alternativa de estructura administrativa:

```
t_wrapper_mensaje {
    t_list* suscriptores;
    t_list* suscriptores_a_los_que_fue_enviado;
    t_list* suscriptores_que_lo_recibieron;
    t_mensaje* mensaje;
}
```

Nuestros problemas vienen de la mano de mantener la consistencia entre `cola->suscriptores` y `wrapper_mensaje->suscriptores`

Identificamos 2 momentos en los que se podría ver afectada la misma:
* al recibir una nueva suscripción: Acá debería iterar todos los `wrapper_mensaje` de la cola a la cual pertenece esta suscripción y agregarles el suscriptor a la lista de suscriptores. 
* al recibir un nuevo mensaje: Acá debería copiar la lista de suscriptores de la cola a la cual fue dirigido el mensaje en la lista de suscriptores del `wrapper_mensaje`

También se nos pasó por la mente que `wrapper_mensaje->suscriptores` apunte a la misma posición de memoria donde se encuentra `cola->suscriptores`, en vez de ser una copia.

Ambas alternativas nos hacen ruido y estamos medio perdidos en cuanto a que camino seguir.

**Comment by ggallici** [comment]
Respondido en soporte

**Comment by afilgueira** [comment]
Golazo! @ggallici nos hacés un breve resumen así le queda al resto? Gracias!

**Comment by ggallici** [comment]
Si, cómo no! Básicamente definimos mantener la estructura planteada pero sin la `t_list* suscriptores` y que, al momento de despachar un msj, éste se envíe a todos los suscriptores que existan en ése momento en la cola (sin tener en cuenta la caché, en principio).
