### ISSUE TITLE
Algoritmo SJF

### ISSUE THREAD

**Issue by FedeMacias** [sisoputnfrba/foro#1685]
Buenas, una consulta

El TP para el SJF dice: "Para este último algoritmo se desconoce la próxima rafaga, por lo que se deberá utilizar la fórmula de la media exponencial." Para eso no necesitariamos un valor de alpha pasado por archivo de configuracion?? En el TP no aparece.

Por ahi me estoy confundiendo de formula pero otra formula de SJF no conozco

Saludos!

**Comment by ncoen97** [comment]
Buenas, yo tampoco encontré el alpha en el enunciado así que debe estar faltando, gracias por la aclaración! Para que no queden dudas, sí la formula es la de alfa y seguro mas adelante les indiquemos si se pasa por archivo de config o si es fijo.
Saludos.

**Comment by FedeMacias** [comment]
Dale buenisimo, muchas gracias!!

Saludos

**Comment by franpassa** [comment]
Hola, alguna novedad al respecto?

**Comment by FedeMacias** [comment]
ya está el alpha en el enunciado
