### ISSUE TITLE
[Team] Planificacion: Varias dudas

### ISSUE THREAD

**Issue by leobz** [sisoputnfrba/foro#1686]
Hola! acabo de ver otros issues sobre planificacion y llegue a armar este diagrama (Solo para confirmar si entendí bien lo que se termino definiendo, si algo esta mal por favor avísenme)

![planificador_fifo_v1](https://user-images.githubusercontent.com/43507646/81028134-9a94dc00-8e56-11ea-9a61-f421d1b5189c.png)

Por otro lado tengo otras consultas:  
Preguntas:  
1) Cuando se ordena por **cercanía**, se deben reordenar todos los entrenadores de la lista ready? O solo a los entrenadores que entraron, poniéndolos entre medio de los que ya estaban formados?
Notas:
El problema de la primer opcion es que destruye el FIFO.
El problema de ir por la segunda opción es que la cola por ser FIFO no va a estar ordenada por cercanía, es decir que puede que el entrenador mas cercano este formado al final de la cola y el mas lejano primero. A la hora de que se "cole" el nuevo entrenador (que podría no ser ni el mas cercano ni el mas lejano de todos los que estaban formados), debería ponerse adelante del que estaba primero en la fila(que era el mas alejado del pokemon) o  atrás del ultimo (que era el mas cercano a la posición del pokemon)?  

2) Cuando me llega una confirmación CAUGHT, el entrenador que estaba esperando dicha confirmación, debe ponerse en ready para poder efectuar la captura? O directamente puedo asignarle el pokemon desde Blocked?  

3) Cuando se planifica el siguiente entrenador a ejecutar, se actualiza la lista dinamicamente? Es decir, cada vez que se ejecuta un entrenador, debo reordenar toda la lista en ready? (Creo que esto solo aplica para SJF)

**Comment by maurodgiraldez** [comment]
Hola!
Tuve la misma duda que vos y encontré en los issues que ya se disctutió esto: https://github.com/sisoputnfrba/foro/issues/1666

Dicen que se va a arreglar en la V1.2 del enunciado. Lo que yo entendí es que de los entrenadores en New o bloqueados esperando que aparezca un pokemon (o a la espera de deadlock) se va a decidir por cercanía cual pasa a la lista de Ready. Entiendo que esa lista Ready la tenes que ordenar por FIFO, RR o SJF depende lo que tengas en la config para saber que entrenador pasa a Exec (y con que criterio).

**Comment by leobz** [comment]
Hola mauro! Si lo vi al issue y las preguntas que puse están basadas en esa información, por eso no resolverían las dudas de este.
(Fijate que en el diagrama puse que cuando pasa de New y Blocked a Ready entra por cercania).

**Comment by maurodgiraldez** [comment]
Disculpa, entendí que esa era tu duda en el punto 1 que hablas de reordenar la lista ready por cercanía y por eso te respondía que la lista de ready se reordena por el algoritmo definido en el config (Por lo que yo entendí). Pero me sumo al issue para estar al tanto de lo que responda algún ayudante.

**Comment by leobz** [comment]
Mauro, recién entendí! Claro, yo había pensado que cuando aparecía un nuevo pokemon todos los que estaban en NEW/BLOCKED disponibles pasaban a READY. Pero, solo pasaría uno a READY, y por el criterio de la cercanía verdad?

**Comment by maurodgiraldez** [comment]
Yo entendí que sí, usas el planificador de cercanía justamente para definir que entrenador es el que pasa a la lista de Ready para ir a buscar el pokemon que apareció. Después por FIFO, RR o el algoritmo que sea, definís cual de todos los entrenadores que tenes en la lista de Ready sale primero a buscar el pokemon por el cual pasó a Ready. Yo lo entendí así y lo estoy planificando así.

**Comment by leobz** [comment]
Genial, me quedo bastante claro! Gracias!

**Comment by ncoen97** [comment]
Buenas, lo que plantearon de la pregunta 1 es correcto, gracias @maurodgiraldez .

Con respecto a la 2, piensen que el hecho de que pase un entrenador a ready quiere decir que va a utilizar el cpu. 

> cada acción de movimiento o envío de mensaje al Broker consumirá un ciclo de CPU

En nuestro caso el envio del mensaje CATCH consume 1 ciclo de CPU pero la recepcion del COUGHT no.

Y con respecto al punto 3, es análogo a la teoría, solo deberían reordenar la cola de ready cuando haya una replanificacion.

Saludos!

**Comment by karengrams** [comment]
¡Buenas!

¿Quedaron resultas todas las preguntas?

Saludos :)
