### ISSUE TITLE
[BROKER] Envio de Mensajes

### ISSUE THREAD

**Issue by SfaraLucas** [sisoputnfrba/foro#1687]
Hola, tengo una duda. No se como darle forma a la señal de recibido (ACK) del mensaje.
¿Me quedo esperando al subscriptor hasta que me responda antes de enviarle al siguiente subscriptor?
¿Si no me responde tomo alguna medida? (Como cancelar la subscripcion o algo así) Porque sino me quedaría el mensaje ahí trabado esperando a ser respondido para poder borrarse y así tomar el siguiente
¿Envio a todos el mensaje, paso al siguiente de la cola y mientras aguardo confirmaciones? (En caso de ser asi ¿De que me serviria la lista de recibidos?)

Muchas Gracias

**Comment by ncoen97** [comment]
Buenas, por ahí esta parte sobre la implementación del Gameboy les sirve para guiarse sobre como actuar desde el Broker:
> Al suscribirse a cada una de las colas deberá quedarse a la espera de recibir un mensaje del Broker. Al recibir un mensaje de cualquier hilo se deberá:
Informar al Broker la recepción del mismo (ACK).
Crear un hilo que atienda dicha solicitud.
Volver a estar a la escucha de nuevos mensajes de la cola de mensajes en cuestión.

También tengan en cuenta que si el Broker manda un mensaje a un suscriptor, cuando se quede esperando a que le contesten el recv() va a devolver -1 si hubo un error.

Por ahí también sirve destacar esta parte del apartado Abstract - Message Queue (MQ) del Broker:

> Notificación de recepción: Todo mensaje entregado debe ser confirmado por cada Suscriptor para marcarlo y no enviarse nuevamente al mismo.

Intenten plantearse devuelta las mismas preguntas y ver si esto les ayuda a encontrar las respuestas, cualquier cosa no duden en volver a consultar.
Saludos!

**Comment by SfaraLucas** [comment]
No la verdad es que sigo con dudas.
¿Que pasa si tarda mucho en responder? ¿Hay un timeout?
¿En caso de error o timeout, doy de baja el subscriptor?

**Comment by tferraro** [comment]
👋Tiene sentido tener un timeout al recibir datos? Me imagino que podrías armar uno, como hacen los browsers, pero no es requerimiento del TP🙂
Lo que te puede pasar es necesitar reconectar y por lo que chusmeo leyendo en `man recv` viene por el lado que dice Nico 😉

**Comment by ncoen97** [comment]
Buenas, esto quedó resuelto? Si es así les pido que cierren, sino pueden seguir consultando.
