### ISSUE TITLE
Serializacion de Mensajes broker/gamecard

### ISSUE THREAD

**Issue by FedeMacias** [sisoputnfrba/foro#1688]
Buenas,

Estamos teniendo problemas con la serializacion de mensajes entre broker y gamecard.

El formato de los mensajes es el mismo que está en el anexo (que es el que usamos para comunicar a team y broker) pero con el agregado del ID al principio, la pregunta es: Habria que agregar una parte de serializacion aparte solo para el envio de mensajes entre ellos dos?? o hay que hacerlo de otra manera??

Saludos

**Comment by ncoen97** [comment]
Buenas, eso me parece que ya queda sujeto a su implementación, si quieren hacer una serialización aparte con el ID agregado o si quieren armar una sola serialización que contemple que puede tener ID o no (mientras sean consistentes en todos los envíos de mensajes). 
Saludos!

**Comment by FedeMacias** [comment]
Si, esa fue la conclusión a la que llegamos al final. Muchas gracias!
