### ISSUE TITLE
Modo Suscriptor GameBoy 

### ISSUE THREAD

**Issue by FacuTadic** [sisoputnfrba/foro#1689]
Buenas tengo una consulta con la variable tiempo en el modo suscriptor, al terminar el tiempo de suscripción la responsabilidad de dejar de escuchar es del broker o del GameBoy. Porque con mi grupo pensamos tres alternativas posibles.

1. El broker me elimina/deja de mandar
2. El game boy le pide al broker que deje de mandar
3. El game boy ignora los mensajes que le manda el broker (el broker nunca deja de enviar)

Gracias!

**Comment by ncoen97** [comment]
Buenas, cual les parece la mas adecuada? pensaron en los pros y contras de cada una? o cómo quedaría el sistema en cada caso?

**Comment by ncoen97** [comment]
Buenas! Pudieron resolver esto? a que conclusión llegaron?

**Comment by iago64** [comment]
Cerramos por inactividad.
