### ISSUE TITLE
DUDA: como manejar el deadlock

### ISSUE THREAD

**Issue by trictor** [sisoputnfrba/foro#1690]
HOLA me quede trabado, no se como manejar la lógica del deadlock, no se si ponerla en el hilo del entrenador o en un hilo a parte. en el primer caso no me parece correcto que el entrenador tenga que manejar el deadlock, en el segundo caso el hilo estaría preguntando todo el tiempo si ocuure un deadlock y no hace nada si no hay deadlock

**Comment by ncoen97** [comment]
Buenas, está bien tu razonamiento de que el entrenador no debería manejar su propio deadlock ya que se supone que estaría bloqueado. Por ahí es tarea del planificador o de otro hilo aparte como vos planteas. Personalmente me parece que en cuanto vayas avanzando con la implementación lo vas a poder ubicar mejor ya que también va a depender de cómo está implementado tu tp, por ahí lo mas importante a esta altura es que entiendas bien los conceptos y cómo proceder cuando encuentres el deadlock.
Igualmente si te parece que seguís trabado con estas cuestiones particulares de diseño por ahí lo mas conveniente es que lo plantees con tus ayudantes por mail o en algún soporte vía discord para poder hablar un poco más sobre tu propia solución.
Saludos!

**Comment by trictor** [comment]
gracias
