### ISSUE TITLE
Diagrama de estados de Team

### ISSUE THREAD

**Issue by maurodgiraldez** [sisoputnfrba/foro#1691]
Hola,
Estoy con el proceso Team y me surgen un par de dudas respecto al diagrama de estados. Puntualmente, mi duda es si es obligatorio seguir esa misma lista o podríamos agregar algún estado más?
Me parece más fácil de implementar, por como lo estoy armando, que de New y Block se arme una nueva lista, por ejemplo, disponibles, donde de ahí salga el entrenador para Ready

![image](https://user-images.githubusercontent.com/8745618/81223842-13ae4380-8fbd-11ea-83e9-c659f2ab526a.png)

**Comment by maurodgiraldez** [comment]
Aclaro que no es por un tema de "estado" propiamente dicho, sino del manejo de las listas (Sacar un elemento, re-ordenar la lista, realocar memoria, etc.) Me pareció más fácil aplicar el algoritmo directamente sobre una lista que estar trabajando con algo temporal que junte los disponibles bloqueados y los new.

**Comment by afilgueira** [comment]
Bueno, que sean dos listas no significa que no puedan ser un único estado. En algoritmos de colas multinivel manejas N colas y el estado ready es uno solo.
Saludos!

**Comment by maurodgiraldez** [comment]
Clarisimo, muchas gracias!
