### ISSUE TITLE
Duda: broker, guardar datos en memoria dinámica

### ISSUE THREAD

**Issue by Marrieta99** [sisoputnfrba/foro#1692]
Hola, con mi grupo tenemos la siguiente duda:

![Untitled](https://user-images.githubusercontent.com/37588840/81247997-c7c9c180-8ff1-11ea-9fbd-8d4ec0217b93.png)

en el paso 3 dice "... y luego se volverá al paso 2 o 3, según corresponda".
¿No tendría sentido volver al paso 1, empezar por buscar de nuevo una partición que me sirva, si no la encuentro compactar en caso que corresponda, y después recién ahí caer de nuevo en el paso 3?
Más que nada no entendemos cuándo correspondería hacer una cosa u otra.

**Comment by ncoen97** [comment]
Buenas, me parece que en el punto 3 faltaría aclarar que si no se encuentra una partición libre con suficiente memoria, ahí se pasa al paso 2 o 3 según corresponda. Igualmente lo chequeamos y cualquier cosa avisamos y se corrige para la próxima versión del tp.
Muchas gracias por la advertencia!

**Comment by ncoen97** [comment]
Buenas! En la nueva versión del tp aclaramos un poco esto. Si la duda quedó resuelta les pido que cierren, sino pueden seguir consultando.

**Comment by karengrams** [comment]
¡Buenas!

Cierro el issue por inactividad, pero si quedo alguna duda, ábranlo sin problema.

¡Saludos!
