### ISSUE TITLE
Problema con la shared library

### ISSUE THREAD

**Issue by tomasCasa** [sisoputnfrba/foro#1693]
Buenas,

Tenemos un problema en la compilación de un proceso con una shared library. Nosotros ya creamos la shared library como indica el video de la cátedra, incluso la incluimos en un proyecto de prueba y la biblioteca funciona, pero al compilar el proceso Gameboy falla.

Por consola nos tira esto:

```
make all 
gcc  -g -Wall  -c gameboy.c -o gameboy.o # Creamos los objects sin linkear
In file included from gameboy.h:18:0,
                 from gameboy.c:11:
utils_Gameboy.h:18:28: fatal error: utils_en_comun.h: No such file or directory
makefile:31: recipe for target 'gameboy.o' failed
compilation terminated.
make: *** [gameboy.o] Error 1
```

y en Gameboy renemos declarada la biblioteca como:

```
#include "utils_en_comun.h"
```

Tenemos idea de que pueda ser un problema del makefile, que lo declaramos así:

```
TARGET = gameboy 
LIBS = -lreadline -lcommons -lutils 
CC = gcc 
CFLAGS = -g -Wall 

.PHONY: default all clean

default: $(TARGET) 
all: default 

OBJECTS = $(patsubst %.c, %.o, $(wildcard *.c))
HEADERS = $(wildcard *.h)

%.o: %.c $(HEADERS) 
	$(CC) $(CFLAGS) -c $< -o $@ 

.PRECIOUS: $(TARGET) $(OBJECTS) 

$(TARGET): $(OBJECTS) 
	$(CC) $(OBJECTS) $(CFLAGS) $(LIBS) -o $@ 

clean: 
	-rm -f *.o
	-rm -f $(TARGET)
```

**Comment by mgarciaisaia** [comment]
¡Hola!

Ahí dice que el que falla es el `#include` hecho desde `utils_Gameboy.h`. Parece que `gameboy.c`, en la línea 11, hace `#include` de `gameboy.h` (y eso funciona). Y `gameboy.h`, en su línea 18, hace `#include` de `utils_Gameboy.h` (que también parece funcionar). Pero `utils_Gameboy.h`, en la 18, hace `#include` de `utils_en_comun.h` - y ahí falla.

¿Están todos esos archivos en el mismo directorio? Quizá te falte agregar algún parámetro `-I` (i mayúscula) para decirle a `gcc` en qué otros directorios buscar los headers que le falten.

**Comment by tomasCasa** [comment]
Claro, la parte que falla es en utils_Gameboy.h porque quiero incluir la shared library que llamé como "utils", dentro de esta carpeta esta "utils_en_comun.h". La shared library, esta separado del directorio donde estan las cosas de Gameboy. 

Lo que si, donde puedo agregar el parametro -I en eclipse ?

**Comment by mgarciaisaia** [comment]
En _alguna parte_ de todas las properties del proyecto hay un tab para los Headers/Includes, y en algún lado de todo eso está el Search Directories o algo así (te muestra un `-I` entre paréntesis).

Pero eso funciona sólo si están dejando que Eclipse genere sus `Makefile`s. Si lo están haciendo a mano, tienen que agregar ustedes el `-I` en los comandos del `Makefile`.

**Comment by tomasCasa** [comment]
Lo agregue en el `Makefile`  pero sigue sin agregarla (Las commons las agregaba igual aunque no tuviera el `-I` )

```
make all 
gcc  -I -g -Wall  -c gameboy.c -o gameboy.o 
In file included from gameboy.h:18:0,
                 from gameboy.c:11:
utils_Gameboy.h:18:28: fatal error: utils_en_comun.h: No such file or directory
compilation terminated.
makefile:15: recipe for target 'gameboy.o' failed
make: *** [gameboy.o] Error 1
```

paso el `Makefile` por si hay algo mal

```
TARGET = gameboy 
LIBS = -lreadline -lcommons -lutils 
CC = gcc 
CFLAGS = -I -g -Wall 

.PHONY: default all clean

default: $(TARGET) 
all: default 

OBJECTS = $(patsubst %.c, %.o, $(wildcard *.c))
HEADERS = $(wildcard *.h)

%.o: %.c $(HEADERS) 
	$(CC) $(CFLAGS) -c $< -o $@ 

.PRECIOUS: $(TARGET) $(OBJECTS) 

$(TARGET): $(OBJECTS) 
	$(CC) $(OBJECTS) $(CFLAGS) $(LIBS) -o $@ 

clean: 
	-rm -f *.o
	-rm -f $(TARGET)

```

**Comment by mgarciaisaia** [comment]
Je, no, perdón, fue más escueta de lo que debía mi explicación.

`-I` es un parámetro que se le puede pasar varias veces a `gcc`, seguido de un path en el que queremos que busque los archivos a los que nuestro código haga `#include`. Entonces, si tengo un `#include "un/path/a/mi_archivo.loco"` y quiero que eso resuelva al archivo `/home/utnso/proyecto/un/path/a/mi_archivo.loco`, hago `gcc -I /home/utnso/proyecto ...`. El compilador (o, bah, el preprocesador) va a encontrar el `#include`, y va a buscar en las rutas que le dije si existe un ese archivo. Como dentro de `/home/utnso/proyecto` existe un directorio `un` con un directorio `path` y un subdirectorio `a` con el archivo `mi_archivo.loco`, resuelve bien, y hace el `#include` como espero.

Si le especificás varios `-I`, busca en el primer path, y, si no encuentra, sigue por el segundo, y así.

Si no le especificás ningún directorio, o si no lo encuentra en los directorios en que le especificaste con `-I`, busca en una lista de directorios predefinidos por el sistema. Por eso con las commons te funciona: porque el `make install` de las commons copia los `.h` a uno de esos directorios en que se busca por default.

¿A qué voy con todo esto? A que en al `-I` que pusiste tenés que agregarle la ruta al directorio que contenga el path que hay en tu `#include`.

**Comment by tomasCasa** [comment]
Perfecto, haciendo eso me funciona. El único problema que veo es que si otro de mis compañeros tiene el repo en otro lado, esta dirección cambia y fallaría.

**Comment by mgarciaisaia** [comment]
¡Claro!

Pero podés aprovechar el hecho de que tu proyecto se distribuye _todo junto_ y hacer que esas rutas sean relativas al propio proyecto.

No estoy seguro de la estructura de tu repo, pero es probable que en la raíz del repo tengas un directorio para cada proceso, y uno extra para tu biblioteca. Si el `Makefile` está en `TU_REPO/gameboy/Makefile` (al lado de `TU_REPO/gameboy/gameboy.c`, ponele), y tu `utils_en_comun.h` está en `TU_REPO/utils/utils_en_comun.h`, podés hacer que el `Makefile` diga `-I ../utils/`, y ahí un `#include "utils_en_comun.h"` funcionaría.

**Comment by tomasCasa** [comment]
Perfecto, con eso esta funcionando! Gracias
