### ISSUE TITLE
Broker - Identificación de procesos

### ISSUE THREAD

**Issue by badialeo96** [sisoputnfrba/foro#1694]
Buenas, con mi grupo tenemos un interrogante acerca de la identificación de procesos por parte del Broker. Cito lo que dice en el enunciado:

> Para esto, el Broker manejara una lista de procesos dentro de cada mensaje en memoria indicando a qué procesos ya fue enviado el mismo. Es responsabilidad del grupo interiorizarse y resolver cómo se identifica a un proceso específico frente a una caída y recuperación.

En el caso de que un proceso haya establecido una conexión con el broker y se caiga, en qué casos debería  consideradarse como una reconexión del mismo proceso?  Si se conecta desde la misma IP y puerto, desde la misma IP simplemente, o deberíamos identificar al proceso de alguna manera independiente, como por ejemplo con un Identificador que envíe el proceso al iniciar?

**Comment by ncoen97** [comment]
Buenas, les pido que se acostumbren a hacer la búsqueda en el foro antes de levantar un nuevo issue. Me parece que esto queda totalmente respondido en el #1669, igualmente si tienen más dudas pueden reabrir y seguir consultando.
Saludos.
