### ISSUE TITLE
BROKER- validar integridad de los mensajes

### ISSUE THREAD

**Issue by bochita** [sisoputnfrba/foro#1695]
buenas!, quería saber si es necesario chequear que lo enviado en un mensaje sea correcto, por ejemplo,que el dato que me mandan tenga el formato esperado, como que el nombre de un pokemon no tenga números, o que el tamaño sea positivo.

**Comment by ncoen97** [comment]
Buenas, teniendo en cuenta que los paquetes que se van a estar mandando entre los módulos son creados por nosotros mismos, te diría que en este caso "confiamos" en que lo que se manda es lo que se tiene que mandar para el código de operación asignado. Los chequeos que sí tendrían que hacer son con respecto al input que se recibe desde la consola (por ejemplo en el gameboy, que el nombre de modulo que te pasan exista, lo mismo para el tipo de mensaje). Por ahí el tema del tamaño positivo lo podrías chequear pero solo en los casos que lo levantes del gameboy, pero hasta ahí (a lo que voy es: no te vamos a poner una config del Team con un numero de pokemons negativo).
Saludos!

**Comment by ncoen97** [comment]
Buenas, la duda quedó resuelta?

**Comment by bochita** [comment]
sisi, todo perfecto!!

**Comment by karengrams** [comment]
¡Perfecto! Cierro el issue entonces :)
