### ISSUE TITLE
Consulta modelado de estructuras

### ISSUE THREAD

**Issue by jcastagno99** [sisoputnfrba/foro#1696]
Buenas! espero no estar repitiendo pregunta pero no encontré ningún issue con mi duda, tengo un tema con el modelado de las estructuras de los mensajes y varias consultas 

1)  La estructura que modelamos inicialmente para Localized_Pokemon era la siguiente:

```
typedef struct{
	 uint32_t posicion_X;
	 uint32_t posicion_Y;
}t_posicion;

/*typedef struct{
	t_posicion posicion;
	t_nodo_posicion* siguiente;
}t_nodo_posicion;*/
```

y nos comimos una buena cagada a pedos cuando vieron que teníamos un puntero adentro de la estructura, así que lo que se me ocurrió fue declararla de la siguiente forma:

```
typedef struct{
	t_nombre_pokemon nombre;
	uint32_t cantidad_coordenadas;
	t_posicion posiciones[cantidad_coordenadas];

}Localized_Pokemon;

```

Pensaba en declarar un array basado cuyo tamaño es igual a la cantidad de coordenadas y ahi guardar mis struct coordenadas,lo cual no funciona (Symbol "cantidad_coordenadas" could not resolved - perdón si esto llega a ser algun error basico de C pero sinceramente no se me ocurre porque no puedo) y es ahí donde me quede sin ideas, el tema de la cantidad de posiciones puede variar de un localized a otro no consigo moldearlo para poder serializarlo

2) Había pensado en reutilizar la estructura t_paquete del TP0 para los mensajes, donde el código de operación es el código que me identifica el tipo de mensaje, lo que seria el t_buffer tendría el size como tamaño de mi struct y el propio struct seria el stream (que tengo entendido que esto es posible porque es un void*) ahora, cada mensaje debe tener un "cliente" que lo envíe y ahí es donde surge mi consulta, debería agregar otro valor que sea el identificador del cliente? es algo que debería estar ya de por si en la estructura o algo que no está y luego el broker asigna (esto no se como lo haría porque no tendría forma de identificarlo), sería mas o menos así 

```
typedef enum {
       ID1 = 1,
       ID2 = 2,
}msj_id;

typedef enum {
	MENSAJE = 1,
}op_code;

typedef struct {
	int size;
	void* stream;
} t_buffer;

typedef struct {
        msj_id codigo_mensaje;
	op_code codigo_operacion;
	t_buffer* buffer;
} t_paquete;

```

Pido disculpas de antemano por la calidad de las fotos y espero no estar diciendo alguna burrada (poco probable).

**Comment by gastoncastineira** [comment]
Buenas!

Antes que todo me voy a poner un poco firme y pedirte el favor de que edites el post sacando esas fotos y poniendo el código junto con los errores que mecionaste. Tal como explica Mati [en este video](https://www.youtube.com/watch?v=18cN8Jk4WjQ) y decimos en el [issue template](https://github.com/sisoputnfrba/foro/blob/master/ISSUE_TEMPLATE.md) las fotos no nos sirven porque por un lado si queremos probarlo no podemos (salvo que empecemos a copiar todo a mano), y por otro lado si uno de tus compañeros tiene el mismo problema y quiere buscar, por ejemplo, el código de error que te tira, no va a poder porque está en una foto y el buscador de github no lo va a poder encontrar. No lo digo de mala onda, solo quiero que podamos reutilizar la mayor cantidad de estos posts interesantes para que tus compañeros los puedan aprovechar también.

Ya pasando a las dudas puntuales:

1. Si bien era otro TP creo que el concepto lo expliqué de una manera potable por allá en #1465. Fijate si te sirve para aclarar un poco las ideas sobre lo que querés hacer y sino lo revisamos

2. Acá no te entiendo muy bien. La pregunta es cómo asignarle un ID al cliente desde el broker?

**Comment by jcastagno99** [comment]
Buenas, ahí lo corregí mala mía, perdón por la tardanza (me cortaron internet ayer y no pude responder)

Si, con lo del problema 1 ese issue me resuelve bastante, muchas gracias!

Con el tema del problema 2 voy a intentar aclararlo, yo entiendo que mis mensajes van a tener un ID que me permite saber quien es el que lo envía, la cuestión es: yo broker, se quien me envía estos mensajes? si esto es así entonces entiendo que debe haber un atributo en la estructura del mensaje que me diga "te lo manda fulanito", en mi caso seria el "codigo_mensaje", o por el otro lado, a mi broker me llegan mensajes a los cuales yo asigno un ID de remitente y los administro, lo que decía es que si este fuera el caso no sabría como responder a aquellos que envían los mensajes porque no los conozco, no se si me explico.

**Comment by ncoen97** [comment]
Buenas, teniendo en cuenta que ese mismo día hubo soporte te pido que nos digas si la duda quedó resuelta o si quedó algo pendiente.

**Comment by jcastagno99** [comment]
SI! perdón por colgarla, lo ultimo lo resolvimos en el sábado de soporte y fue la segunda opción de lo que escribí antes, lo aclaro para que ya quede en el issue, broker asigna en el momento de recibir el mensaje el ID del cliente y lo administra a partir de ese ID, gracias por la ayuda!

**Comment by iago64** [comment]
@jcastagno99 joya, cerramos entonces 😄
