### ISSUE TITLE
Duda de estructura de un file de Pokemon

### ISSUE THREAD

**Issue by guidoenr4** [sisoputnfrba/foro#1697]
Que tal, tengo una consulta.. en el trabajo practico cuando habla de la implementacion de los pokemons como directorios/archivos dice:

> _Archivos Pokemon
> Cada archivo de tipo pokemon tendra internamente (por cada fila) la lista de posiciones en el mapa que se encuentra con la cantidad en dicha posición. De esta manera un posible archivo de pokemon puede ser:
>     1-1=10
>     1-5=1
>     3-1=2
>     7-6=1000_

estoy viendo que hacer cuando atiendo un mensaje `NEW POKEMON` actualmente estoy trabado en el punto 3 digamos..

>3.  _Verificar si las posiciones ya existen dentro del archivo. En caso de existir se deben agregar la cantidad pasada por parámetro a la actual. En caso de no existir se debe agregar al final del archivo una nueva línea indicando la cantidad de pokémon pasadas._

suponiendo que me llega un `NEW PIKACHU ` en cierta posicion, entiendo que esa informacion esta dentro de `PUNTO_MONTAJE/Pokemon/Pikachu` porque lo dice el enunciado, eso de las posiciones no lo termino de entender, que tipo de archivo es? va dentro del metadata.bin del pokemon? o como es la manera de implementarlo?

**Comment by ncoen97** [comment]
Buenas! Como especifica en el apartado Files metadata del proceso Gamecard del tp, en la metadata de cada archivo (/mnt/TALL_GRASS/Files/Pikachu/Metadata.bin) vas a tener los números de bloque que componen a tu archivo. De este archivo vas a tener que leer con el formato que especificaste al principio de tu issue y después actuar dependiendo de si ya hay un pikachu en la posición indicada o no.
También te invito a leer el issue #1668, que por ahí te sirve para entender un poco más como funcionan los bloques del FS.
Saludos!

**Comment by guidoenr4** [comment]
Que tal, vi el issue.. entiendo el funcionamiento de los blocks del file, me lo habian explicado un sabado de soporte.
Se que un file esta en distintos bloques y el array de blocks que esta dentro del metadata me dice en cuales blocks.

Lo que no estoy entiendo aun es la posicion de un pokemon especifico, en que parte esta?

`1 -1 = 10` 

esto aun no lo entiendo.

**Comment by ncoen97** [comment]
> Se que un file esta en distintos bloques y el array de blocks que esta dentro del metadata me dice en cuales blocks.

El 1-1=10 estaría justamente adentro de este file que estas nombrando.

**Comment by guidoenr4** [comment]
Bien, pero que representa ese 1-1 = 10 ?
que en la posicion (x,y) = (1,1) hay 10 pokemons?

**Comment by enogueiras** [comment]
> Bien, pero que representa ese 1-1 = 10 ?
> que en la posicion (x,y) = (1,1) hay 10 pokemons?

(perdon que me meta) Hola Guido, si justamente eso.
Abrazo.

**Comment by guidoenr4** [comment]
Genial, gracias a todos. Cierro el issue.
