### ISSUE TITLE
Manejo de threads en Team

### ISSUE THREAD

**Issue by Charlyd96** [sisoputnfrba/foro#1698]
Buenas a todos!
Estuve leyendo el Issue #1635, y al menos a mí como lector me quedaron algunas dudas.
1) Los n hilos que maneje el Team, consonantes a los n entrenadores seteados por archivo de configuración, ¿tienen que crearse todos al momento de inicializarse? ¿O se debe ir creando cada hilo en función de los pokemons que vayan  apareciendo mediante LOCALIZED y APPEARED?
2) Supongamos que se van creando a medida que aparecen los pokemones, y aparece uno necesario a nivel global. Team recorre su lista de entrenadores, determina cuál está más cerca y lo planifica. Seguidamente delega en otro algoritmo (en principio FIFO) el momento en que pase a Exec. En todo este proceso que narré recién, ¿en qué momento se debería crear propiamente el hilo? Esto me hace desembocar en otra duda quizás más bien filosófica: 

     2.a. ¿Crear un hilo implica necesariamente ejecutarlo inmediatamente? ¿O podría crearse y 
     mantenerse en espera hasta ejecutar?

3) Suponiendo que se crean todos al iniciarse el Team (independiente de que existan o no pokemones para atrapar), sospecho que la respuesta a 2.a) es que claramente los hilos permanecerán creados pero bloqueados. En ese caso, cada hilo correspondiente a cada entrenador ¿permanece abierto hasta que llegue a exit por cumplir su objetivo particular? Es decir, ¿el hilo se crea y recién se cierra cuando terminó de atrapar sus pokemons requeridos? 
4) Lo otro que se me ocurría es que el hilo se cree y se cierre continuamente, controlando el estado de manera abstracta de cada entrenador en estructuras administrativas. Por ejemplo, planifico a un entrenador para atrapar a un Pikachu, pasa a la cola de Ready hasta que el algoritmo lo manda a Exec. Ejecuta, atrapa al Pikachu y a través de la estructura recibida en el hilo por parámetro, cambio los estados que correspondan (un pokemon menos en el objetivo, la nueva posición, etc.), cierro el hilo y fin, se abrirá nuevamente cuando aparezca otro pokemon cercano a esa nueva posición. De esta manera el “hilo de cada entrenador” estará creándose y cerrándose continuamente hasta que atrape a todos sus pokemones. 

Espero haber sido claro, y si consideran que correspondería hacer varios issues por esto, háganmelo saber. 
Saludos!

**Comment by ncoen97** [comment]
Buenas!

1. "Al iniciar el proceso, se deberá crear un hilo por cada entrenador existente...", el entrenador existe más allá de si hay pokemons disponibles para atrapar.

2. Si con crear un hilo te referís a `pthread_create()`, sí se empieza a ejecutar la función que le pasas por parámetro en ese momento. Igualmente más allá de eso, adentro de esa función podrías tener alguna syscall bloqueante que no lo deje ejecutar si es que lo necesitas.

3. Pensá que no podes cerrarlo antes de que tenga todos sus objetivos cumplidos porque sino no tendría como cumplirlos.

4. Ojo con el tema de "crear y cerrar continuamente un hilo", si te referís a utilizar el  `pthread_create()` y  `pthread_cancel()`, no va por ahí. Lo que si podes hacer es lo que te mencioné mas arriba de usar syscalls bloqueantes (como semáforos) para "activar" y "desactivar" la ejecución de tus funciones.

Te recomiendo que ya que es sábado, si les quedan más dudas se pueden pasar por el soporte de discord :)

Saludos.

**Comment by Charlyd96** [comment]
Hola, gracias por responder!

1) Mi pregunta era por los hilos, no por el entrenador. Está claro que el entrenador una vez que se lee de las configs, empieza a existir a través de una estructura o lo que fuera. El tema es si se debe crear un hilo para ese entrenador.

3) Esto es cierto en el caso de que se piense en la arquitectura de que cada entrenador va a ser atendido por un hilo en particular, que va a subsistir desde que inicia el proceso Team hasta que el entrenador alcanzó sus objetivos (cuando pasaría a Exit, termina el hilo).

Pero si pienso en la arquitectura que planteé en 4), los entrenadores se manejan a través de estructuras, y planificarlo sería transferir su estructura al algoritmo que maneje la cola Ready, y cuando ese algoritmo decida que es tiempo de ejecutarlo, que lance un hilo (y sólo uno) para atender a ese entrenador a través de su estructura administrativa. Una vez que termine su ejecución, el hilo se cierra, y los cambios que haya hecho (su nuevo estado, atrapar un pokemon, cambiar su posición en el mapa, etc.) quedan registrados en su estructura. Seguidamente, la cola Ready se prepara para lanzar un nuevo hilo con otro entrenador (en caso de corresponder). Esta secuencialidad de atender los hilos y no concurrencia va en cosonancia a lo que dice el enunciado.
En este último caso manejo un solo hilo, que atiende a cada entrenador acorde el algoritmo de planificación (FIFO, SJF, RR) y a eso me refería que los hilos se van abriendo y cerrando (terminando), ejecutan lo que tienen que hacer, y termina su ejecución (aunque no haya pasado a Exit).

Ahora voy a Discord de todas formas, pero quería dejar esto expresado por si otro lee el Issue, para que no quede inconcluso.
Saludos

**Comment by iago64** [comment]
Buenas!

La idea de 1 entrenador por hilo hace que vos tengas que si o si iniciar un hilo para cada entrenador una vez que levantas la config y estableces los objetivos para cada entrenador.
De todas formas no vas a poder independizarte de una estructura donde tengas toda la info del entrenador porque al final del día el pthread_t que representa al entrenador lo vas a tener que guardar en algún lado y por otro lado vas a tener que poder resolver los deadlocks de alguna forma y para eso necesitas saber que entrenadores tenes y que atrapo cada uno.

Saludos.-

**Comment by ncoen97** [comment]
Buenas, teniendo en cuenta que ese día hubo soporte te pido que nos digas si la duda quedó resuelta o si quedó algo pendiente.

**Comment by Charlyd96** [comment]
Hola, sí quedó resuelta. Me gustaría aclarar de todas formas por si alguno lee este Issue, que el sábado de soporte anterior (02/05), a algunos grupos nos dijeron que no era necesario crear un hilo por cada entrenador, pero este sábado me confirmaron que sí. Se crearán todos los hilos cuando se ejecuta el programa, y se van bloqueando y desbloqueando acorde se van planificando.

Saludos
