### ISSUE TITLE
diferencia entre mensaje appeard pokemon y localized pokemon

### ISSUE THREAD

**Issue by trictor** [sisoputnfrba/foro#1699]
hola no estoy entendiendo la diferencia entre esos dos mensajes. por el mensaje appeard pokemon me llegarían los pokemon que pedí con el mensaje get pokemon ahora sito lo que dice el mensaje localized pokemon

> El proceso Team se suscribirá de manera global a esta cola de mensajes. Al recibir uno de los mismos deberá realizar los siguientes pasos:
1)Verificar si ya recibió en algún momento un mensaje de la especie del Pokémon asociado al mensaje. Si es así, descarta el mensaje (ya sea Appeared o Localized).
2)En caso de que nunca lo haya recibido, realiza las mismas operatorias que para APPEARED_POKEMON por cada coordenada del pokemon

el mensaje localized estaría haciendo el mismo procedimiento que appeard, entonces en que caso uso appeard y cuando uso localized

otra duda que tengo es cuando tengo que recibir a los pokemon porque puede ser el caso que me lleguen mas pokemon y no tenga entrenadores para ejecutar porque se estan moviendo a buscar otro pokemon. se me ocurriron dos soluciones guardar todos los pokemon en una lista y voy sacando del primero o bloquear la llegada de pokemon hasta que tenga entrenadores esperando
cual solucion es mejor para este tp?

**Comment by ncoen97** [comment]
Buenas, la primera afirmación que hiciste al principio de tu issue no es correcta. El Appeared Pokemon es el mensaje que se manda al broker cuando al gamecard le llega el mensaje New Pokemon, por lo tanto te pido que releas el enunciado teniendo eso en mente y si seguís con dudas podes volver a consultar.
Con respecto a la llegada de los pokemons, te diría que lo mas conveniente es que tengas los pokemons guardados, ya que en este caso bloquear la recepción de los mensajes no me parece para nada viable. 
Saludos!

**Comment by trictor** [comment]
entonces me podrías explicar que es lo que hace el mensaje appeard pokemon y cual es la diferencia con localized? 
con lo que entendí los dos mensajes incluyen pokemon en el mapa ¿me equivoco?

**Comment by ncoen97** [comment]
El Appeared Pokemon es el mensaje que se manda al broker cuando al Game Card le llega el mensaje New Pokemon, que ocurre cuando un justamente se "agrega un pokemon nuevo al mapa", involucra a un solo Pokemon. En cambio el Localized Pokemon es el mensaje que se manda al broker cuando al gamecard le llega el mensaje Get Pokemon, osea que sería la consecuencia de un Team pidiendo al GameCard todas las posiciones en las que hay al menos un Pokemon de la especie indicada.

**Comment by trictor** [comment]
entonces estos dos mensajes son dos formas distintas de que me lleguen pokemon, la diferencia seria que appeared pokemon me llega un pokemon cualquiera que el proceso team pueda necesitar o no y el localized me vendría todos los pokemon que pedi por el mensaje get
es asi?

**Comment by ncoen97** [comment]
Si, pero tené en cuenta que los mensajes Localized que te lleguen van a ser los de TODOS los Teams, por lo tanto vas a tener que filtrar los que tengan como ID_CORRELATIVO el ID que tenía tu mensaje Get original.

**Comment by trictor** [comment]
la ultima consulta la llegada de los dos mensajes seria al iniciar team o puede ocurrir que me lleguen estos mensajes en cualquier momento?

**Comment by ncoen97** [comment]
Ambos van a llegar como respuesta a sus respectivos mensajes (Get y New), por lo tanto los Localized serían cuando un Team se conecte y pida las ubicaciones de los Pokemon y los Appeared en cualquier momento que mandemos un New vía Game Boy.
Saludos!

**Comment by trictor** [comment]
en el caso del localized puedo terminar la conexión con ese socket si ya recibí todos los pokemon que pedi con el mensaje get?

**Comment by iago64** [comment]
Buenas! 
Las conexiones para las suscripciones nunca tenes que cerrarlas.

Saludos.-

**Comment by iago64** [comment]
@trictor Como va? Quedo respondida la duda? cerramos el issue?

**Comment by trictor** [comment]
si gracias
