### ISSUE TITLE
Gameboy - Envío de mensajes a procesos

### ISSUE THREAD

**Issue by maurodgiraldez** [sisoputnfrba/foro#1700]
Hola, tenemos una duda con el enunciado del proceso Gameboy. Al principio dice esto:

> El objetivo del proceso Game Boy es poder probar independientemente todos los otros procesos. De esta manera, el mismo podrá enviar cualquier mensaje a cualquier cola que el proceso Broker conozca y enviar por socket al proceso Team el mensaje de aparición de un nuevo Pokemon.

Pero en los mensajes que le envía al Team, por ejemplo, dice esto: 

> Team - Appeared Pokemon
> Permitirá enviar un mensaje al Team a la cola de mensajes APPEARED_POKEMON. Para esto, el formato del mensaje será:

Entendiendo que le debería enviar de manera independiente al Team, cuando, por ejemplo, el broker no funcione, no entiendo como podría enviar el mensaje a la cola que crea y administra el broker. No debería enviarle directo por socket los mensajes?

Gracias
Saludos

**Comment by Guernik** [comment]
Suscribo a la duda de mauro

**Comment by ncoen97** [comment]
Buenas!
Fijate que en el apartado del gameboy tenes por un lado el mensaje "Broker - Appeared Pokemon" y por otro lado el "Team - Appeared Pokemon". El primero manda el mensaje al broker (para que luego el broker lo mande a los teams suscriptos a la cola de Appeared), y el segundo manda un mensaje directo al team.
Justamente como vos citaste en tu issue, "El objetivo del proceso GameBoy es poder probar independientemente todos los otros procesos", por lo tanto tienen que poder mandar ambos mensajes para poder probar ambos módulos.
Saludos.

**Comment by maurodgiraldez** [comment]
Nicolas, gracias por tu respuesta! Entendí exactamente lo mismo que me decís, pero no me queda claro esto:
En el enunciado, cómo vos decís, están los mensajes al broker, los cuales deberían ir a las colas para que les llegue a todos los demás procesos.
Sin embargo, donde están los mensajes directo a los Teams o a las GameCards, las cuales entiendo que deberían poder enviarse sin que funcione el broker, específica que también se deben enviar a colas de mensajes; por lo que no entiendo como enviar un mensaje directo al proceso Team enviándoselo a una cola de mensajes.

> Broker - Get Pokemon
> Permitirá enviar un mensaje al Broker a la cola de mensajes GET_POKEMON. Para esto, el formato del mensaje será:
> 	./gameboy BROKER GET_POKEMON [POKEMON]
> Team - Appeared Pokemon
> Permitirá enviar un mensaje al Team a la cola de mensajes APPEARED_POKEMON. Para esto, el formato del mensaje será:
> 	./gameboy TEAM APPEARED_POKEMON [POKEMON] [POSX] [POSY]

Saludos

**Comment by ncoen97** [comment]
Claro, entiendo tu duda. Por ahí es un tema de redacción, la idea es que el mensaje Team - Appeared Pokemon va directamente al Team (no pasa por el Broker). Lo dejo como sugerencia para cambiar la redacción y por ahí en una nueva versión del tp actualizamos esa descripción.
Saludos!

**Comment by iago64** [comment]
@maurodgiraldez Como va? Quedo respondida la duda? cerramos el issue?

**Comment by maurodgiraldez** [comment]
Si, resuelta! 
Muchas gracias @ncoen97 

Saludos
Cierro
