### ISSUE TITLE
Duda Logs GameBoy

### ISSUE THREAD

**Issue by MaSosa314** [sisoputnfrba/foro#1701]
Buenas. Tenemos una duda con el tema de los logs en el modulo GameBoy. Una de las cosas que se tienen que loggear cuando estamos en modo suscriptor en el GameBoy es la recepcion de los mensajes que llegan de la cola de mensajes a la que nos suscribimos. La duda es ¿Tenemos que loggear solamente que se recibio un nuevo mensaje de esa cola o tenemos que loggear tambien el contenido del mensaje?

Saludos.

**Comment by iago64** [comment]
Buenas!
Muy linda pregunta 😄 
**Respuesta corta**: Logueen el contenido del mensaje tambien

** Un poco mas de contexto **
Los logs tienen el objetivo de representar el estado del sistema y de servirle a cualquiera que necesite saber que esta pasando la información suficiente (ya sea en el TP de SO o en cualquier sistema). Dicho esto, si loguean el contenido del mensaje del lado del broker **y** del lado del gameboy, no tendrían la facilidad de checkear que lo que envían llego bien?

Abrazo.-

**Comment by iago64** [comment]
@MaSosa314 Como va? Quedo respondida la duda? cerramos el issue?

**Comment by MaSosa314** [comment]
Si si. Perdon por no avisar. Muchas gracias.
