### ISSUE TITLE
Proceso Team - Desalojo de recursos

### ISSUE THREAD

**Issue by MartinezAlexander** [sisoputnfrba/foro#1702]
Buenas tenemos una duda con esta parte del enunciado:
         "Se dice que un proceso Team cumplió su objetivo global cuando todos sus entrenadores
           obtuvieron los Pokémon que requieren. Al realizarse esto, se debe informar, desalojar los 
           recursos obtenidos y finalizar el proceso."
Según lo que tenemos entendido los recursos son los pokemones, por lo que el proceso team lo que hace es utilizar estos recursos para cumplir su objetivo global, entonces una vez que un entrenador captura un pokemon el game card los borra del filesystem de ese pokemon (En caso que la cantidad del Pokémon sea “1”, se debe eliminar la línea. En caso contrario
se debe decrementar la cantidad en uno.). 
Por lo cual el hecho de desalojar los recursos seria que en ese filesystem del pokemon vuelvan a aparecer todos los pokemones que ahora tiene en su poder el team para que puedan ser utilizados por otros team o se refiere a otra cosa?

Saludos.

**Comment by ncoen97** [comment]
Buenas! Ahí subimos una nueva versión del tp aclarando un poquito mas sobre esto, así que échenle una mirada y si siguen con dudas nos avisan.
Saludos.

**Comment by karengrams** [comment]
¡Buenas! ¿Como va? ¿Se aclararon sus dudas con la nueva versión? :)

**Comment by MartinezAlexander** [comment]
Buenas!!
Si ahi leimos la nueva version y quedo mas claro, entonces cuando un proceso team usa los recursos (pokemones) estos se pierden ya que al no desalojarlos cuando cumple su objetivo global, esos pokemones no van a poder volver a ser utilizados por otro team no?

**Comment by iago64** [comment]
Exacto, la idea era ser consistentes y no decirles que el team mandara mensajes que no debía mandar :)
Por eso les aclaramos que es una diferencia con respecto a la teoria.

**Comment by MartinezAlexander** [comment]
Dale buenisimo, muchas gracias!

**Comment by karengrams** [comment]
¡De nada! Cierro el issue, cualquier cosa, no duden en abrirlo :)
