### ISSUE TITLE
Broker, emisión de mensajes a subscriptores

### ISSUE THREAD

**Issue by etienne95** [sisoputnfrba/foro#1703]
Hola!!

Con el equipo estabamos analizando la logica del **broker** para emitir los mensajes recibidos por los publicadores, a los subscriptores, y nos surgieron algunas dudas:

1.  En el TP se habla de que cuando se publica un mensaje al broker, el mismo no tiene que ser inmediatamente enviado a los subscriptores de la cola. Pero que pasa si el mensaje se envia a una cola que esta vacia? en ese caso deberiamos enviar el mensaje inmediatamente no? y cuando la cola no esta vacia suponemos que el mensaje debe ser pusheado en la cola para su posterior procesamiento. Esta correcto esto?
2. Por cada hilo que creemos para emitir el mensaje hacia cada subscriptor de la cola X, debemos enviarlo primero, pero luego hacer un `recv` para obtener el `ACK` deseado del subscriptor, dicho `recv` nos va a bloquear el hilo y todo el proceso broker en si? o solo va a bloquear ese hilo y el resto se van a continuar ejecutando con normalidad?

Desde ya muchas gracias!

**Comment by ncoen97** [comment]
Buenas.
Lo que escribieron del punto 1 me parece correcto. 
Con respecto al 2, las operaciones bloqueantes no les van a bloquear todo el programa. Para este tipo de cosas pueden intentar testearlo a mano (por ej. creando un hilo y clavandolo en un recv) que suele ser mas rápido que esperar a que les respondamos el foro ;)
Saludos!

**Comment by iago64** [comment]
@etienne95 Como va? quedo respondida la duda? cerramos el issue?

**Comment by etienne95** [comment]
Buenas, si si completamente, muchas gracias!!

**Comment by ncoen97** [comment]
Cuando queda resuelto pueden directamente cerrar ustedes el issue. Saludos!
