### ISSUE TITLE
[Duda Enunciado] - Config Team

### ISSUE THREAD

**Issue by thomykut** [sisoputnfrba/foro#1704]
La verdad no había sido una duda hasta que nos dimos cuenta que las 2 personas que trabajamos en este módulo principalmente teníamos visiones distintas sobre lo mismo.

A partir de estas 2 constantes de la config:
POKEMON_ENTRENADORES=[Pikachu|Squirtle|Pidgey,Squirtle|Charmander,Bulbasaur]
OBJETIVOS_ENTRENADORES=[Pikachu|Pikachu|Squirtle|Pidgey,Pikachu|Charmander|Charmander,Squirtle|Bulbasaur]

Por un lado, yo interpreté que, por ejemplo, Pikachu|Pikachu|Squirtle|Pidgey son los 4 pokemons que tiene que obtener el entrenador 1 digamos. Pero ya tiene Pikachu|Squirtle|Pidgey, por lo que solo le faltaría un Pikachu para terminar su objetivo personal.
Por el otro, mi compañera de equipo interpretó, para el mismo caso, que esos 4 pokemons son los que le falta juntar, mientras que los 3 que ya posee en su inventario no tienen que ver con su objetivo.

**Comment by ncoen97** [comment]
Buenas chicos, sigo repitiendo: por favor antes de abrir un issue busquen en el foro si ya está hecha la pregunta. Me parece que en el #1637 queda bastante claro, cualquier duda pueden reabrir.
Saludos.
