### ISSUE TITLE
Duda planificación, cambio de contexto.

### ISSUE THREAD

**Issue by francorojo** [sisoputnfrba/foro#1705]
Buen dia, tengo una pregunta, en el caso de un algoritmo RR, si un proceso nuevo cae justo en el momento donde termina el proceso anterior. Sigue ejecutando el proceso que estaba, porque una interrupcion tiene mas prioridad que una syscall. Pero ademas, hay cambio de contexto en ese caso? El proceso es el mismo, pero cuando lo agrega a lista de ready y lo vuelve a ejecutar habria?

![image](https://user-images.githubusercontent.com/49093389/81604895-03c0a600-93a7-11ea-8449-f50a3818ef21.png)

(En el instante 4 quise decir el ejemplo)

**Comment by iago64** [comment]
Bueeenas!
Muy linda pregunta. Como bien decís, la interrupción tiene mas prioridad de la syscall, y si tenes un cambio de contexto porque tuviste la interrupción que te saco el proceso de exec, por mas que sea para volver a mandar el mismo proceso :)

Abrazo.-

**Comment by francorojo** [comment]
Muchas Graciaaaaas!

**Comment by francorojo** [comment]
Perdon una duda mas, en ese cambio de contexto, a q proceso pasamos cuando sacamos al proceso A? Al sistema operativo que maneja el algoritmo? Osea hay 2 cambios de contexto, uno para desalojar al proceso A y luego otro para planificar al proceso A? Graciaas

**Comment by iago64** [comment]
Buena pregunta de nuevo 😄 
Por suerte en el silberschatz si buscas la parte de cambio de contexto (Capitulo 3 en la 7ma edicion) te cuenta que el cambio de contexto consta de los siguientes pasos:

1. Guardar el estado del proceso que esta ejecutando
2. Seleccionar el siguiente programa a ejecutar
3. Restaurar el estado del proceso que tiene que reanudar su ejecución

Con lo cual, solo tendrías 1 cambio de contexto (ya sea que continuas ejecutando el mismo o elegís otro entrenador para que ejecute)

Abrazo.-

**Comment by francorojo** [comment]
Ah buenisimooo, muchas gracias!!!
