### ISSUE TITLE
Problema al correr Lubuntu en virtualBox 6.1.6 y 5.2

### ISSUE THREAD

**Issue by guidoenr4** [sisoputnfrba/foro#1706]
Que tal, estoy teniendo un problema con la maquina virtual.
Tengo una nueva pc para correrla que tiene Windows 7 Ultimate 64b.
El problema es que cuando pongo iniciar a la imagen virtual de lubuntu ya cargada y configurada, carga todo lo que carga normalmente cualquier linux al inicio, y despues de llegar al paso de 
`lubuntu: login`
se queda en negro y no me aparece para logear el usuario ni la pw.. probe dos versiones, la 6.1.6 y la 5.2 (que era la que me andaba en mi antigua pc con windows10) y a ambas le pasa lo mismo.

**Comment by mgarciaisaia** [comment]
¿Pudiste resolver?

¿Qué era?
