### ISSUE TITLE
Manejo de la caida de una conexion con send()

### ISSUE THREAD

**Issue by MaSosa314** [sisoputnfrba/foro#1707]
Buenas. 

Hace poco terminamos de armar la función de suscripcin del módulo **GameBoy**. Hicimos un pequeño codigo a modo de **Fake Broker** para probar el **GameBoy**. Basicamente, dentro de un bucle, el **Broker** arma un mensaje New Pockemon con datos random, se lo envia al **GameBoy**, y hace un `sleep` de 10 segundos.

Mientras lo probabamos, vimos que, cuando el **GameBoy** alcanza el _time out_, el modulo finaliza normalmente cerrando el socket, y el **Broker** pareciera terminar normal. Pero cuando revisamos el valor de retorno que devolvia,  vimos que retornaba 141. Nos pusimos a debugear, y vimos que estaba saltando un `SIGPIPE` cuando haciamos `send()` desde el **Broker** al **GameBoy** cuando **GameBoy** ya habia cerrado su lado de la conexion. El problema es que esta señal aborta la ejecucion del programa. Estuvimos viendo y se puede evitar que el programa aborte, seteando un callback con la funcion `signal` para que no aborte. La pregunta es si deberiamos hacerlo de esta manera o hay alguna otra manera de sortear la situacion. Pensamos en mandar un mensaje desde los modulos antes de cerrar el socket, informando al Broker de que ese modulo va a desconectarse, pero estariamos con el mismo problema en caso de que alguno de los modulos se "__caiga__" abruptamente.

Saludos.

**Comment by iago64** [comment]
Buenas buenas!

Puntualmente desde los procesos no deberían estar avisando que se van a cerrar, porque de hecho podrías simplemente tirar un Ctrl + C en la consola o un sigkill y ahí no tendrían forma de avisar.

Con lo cual el manejo de SIGPIPE podrian hacerlo mediante una signal o mediante algun flag en send() que les frene el comportamiento de SIGPIPE 

Saludos.-

**Comment by MaSosa314** [comment]
Cuando te referis a algun flag en send() ¿Te referis a algun valor que devuevla send cuando se desconecte el otro lado? Nosotros en un momento pensamos que send() devolvia 0 como hace recv(), indicando que se corto la conexion. De hecho, estabamos comprobando, por cada send que haciamos, si devolvia 0 para cortar el loop. Pero no devuelve 0 en caso de desconexion. Y por lo que anduvimos viendo, send no avisa en caso de que el otro lado de la conexion se haya cerrado. No si te referias a eso, o si te referis a que implementemos algo ahí para que no salte el SIGPIPE.

**Comment by iago64** [comment]
Aloha!
Efectivamente un flag en el send(), aunque parezca algo trivial, el man de linux es nuestro mejor mejor amigo para entender algunas cosas:

1.- en recv por ejemplo tienen que checkear que no sea -1, ya que el 0 representa el EOF (end-of-file) y esto lo ven en la parte de return value del man.
2.- En send() tienen un flag muy copado que es MSG_NOSIGNAL, mas adelante les dejo el man para que lo revisen y entiendan para que sirve :)

En ambos casos no tienen que creerme a mi, pueden checkearlo por uds mismos (y en serio, nunca crean a ciegas en lo que les dicen, siempre traten de confirmar lo que les dicen)

recv() - http://man7.org/linux/man-pages/man2/recv.2.html
send() - http://man7.org/linux/man-pages/man2/send.2.html

Abrazo.-

**Comment by MaSosa314** [comment]
Ahhhh oka oka. Claro, cuando leimos lo de los flags pensamos que eran valores con los que se seteaban errno en caso de que ocurriera el error. Que despistado jajaja. Ahi esta entonces. Muchas gracias :). Pueden cerrar el issue.
