### ISSUE TITLE
Duda mensajes APPEARED_POKEMON y LOCALIZED_POKEMON

### ISSUE THREAD

**Issue by JuanCarassai** [sisoputnfrba/foro#1708]
Buenas,
Estuve tratando de definir la estructura de los mensajes que se envían los distintos procesos y me surgieron las siguientes dudas:

1. 
El proceso Gamecard envía el mensaje APPEARED_POKEMON con los siguientes datos:
 
   - ID del mensaje recibido.
   - Pokemon.
   - Posición del mapa.

Mi duda es: El "ID del mensaje recibido", ¿Es el que recibe en NEW_POKEMON? ¿Por qué enviaría este id? ¿Este id lo recibe el proceso Team?

2. 
Ocurre lo mismo cuando el proceso Gamecard responde a un mensaje GET_POKEMON. Este responde enviando el mensaje LOCALIZED_POKEMON que contiene los siguientes datos:

   - ID del mensaje recibido originalmente.
   - El Pokémon solicitado.
   - La lista de posiciones y la cantidad de posiciones X e Y de cada una de ellas en el mapa.

Me surgen las mismas dudas que en el punto anterior: El "ID del mensaje recibido originalmente", ¿Es el que recibe en GET_POKEMON? ¿Por qué enviaría este id? ¿Este id lo recibe el proceso Team?

**Comment by iago64** [comment]
Buenas!
La idea del ID del mensaje recibido es porque justamente tanto los mensajes de APPEARED y LOCALIZED son respuestas a NEW y GET respectivamente, entonces tenes que avisar de alguna manera a que mensaje estas contestando y eso lo haces por medio del ID del mensaje recibido (o ID_MENSAJE_CORRELATIVO que vas a ver en los ejemplos del gameboy)

Saludos.-

**Comment by juan061099** [comment]
Buenas, 
Muchas gracias por responder, me surgen dudas nuevas:
1. Teniendo el id correlativo del mensaje LOCALIZED, ¿El proceso Team puede decidir si descartar o procesar el mensaje?
2. El id correlativo del mensaje APPEARED, ¿Le es de alguna utilidad al proceso Team?

**Comment by ncoen97** [comment]
Buenas.
1. Si, justamente ese es objetivo de que haya un id correlacional.
2. No lo vas a usar para procesar, pero tiene que estar igual porque los procesos se comunican a través de la Message Queue y en ese sentido es obligatorio que esté.
Saludos.

**Comment by karengrams** [comment]
¡Buenas @juan061099!

¿Como va? ¿Quedo resuelta la duda?

Saludos :).

**Comment by juan061099** [comment]
Buenas,
Quedo resuelta la duda. Muchas gracias por responder!!

**Comment by juan061099** [comment]
Buenas,
Perdón que reabra el issue pero estoy haciendo el Gameboy y me di cuenta que el mensaje APPEARED que llega a la cola de mensajes es distinto al que recibe el proceso Team.

./gameboy BROKER APPEARED_POKEMON [POKEMON] [POSX] [POSY] [ID_MENSAJE_CORRELATIVO]
./gameboy TEAM APPEARED_POKEMON [POKEMON] [POSX] [POSY]

¿No le estaría faltando los argumentos [ID_MENSAJE_CORRELATIVO] y [ID_MENSAJE] al mensaje que se le envía al proceso Team?

Saludos.

**Comment by MarianoPessina** [comment]
Yo creo que es porque el proceso Team no puede hacer un NEWPOKEMON, mientras que el gameboy si, por eso es que al gameboy se le responde con el ID_MENSAJE_CORRELATIVO que va a ser igual al ID del mensaje de  NEW que hizo, el team simplemente se entera cuando hay nuevos pokemones, no se le está respondiendo a un mensaje suyo

**Comment by JuanCarassai** [comment]
Entiendo lo que decís pero si a la cola está entrando el mensaje con el id correlativo, porque cuando sale de la misma, no le envías al proceso Team el id.

**Comment by iago64** [comment]
Buenas,

Recién me percato que este issue llegaba un par de días pendiente.
Por eso no esta bueno que se reabran temas.

La idea de que el APPEARED que le llega al team no tenga id correlativo es simplemente porque no le importa 😄 
Pueden serializar el campo y mandarle un 0 o cualquier cosa? Si
Sirve de algo? No

Saludos.-

**Comment by JuanCarassai** [comment]
Buenas,
Ya me queda claro, muchas gracias. Ahora si, cierro el issue.
