### ISSUE TITLE
Consulta sobre enunciado gamecard

### ISSUE THREAD

**Issue by gebonora** [sisoputnfrba/foro#1709]
Buenas!

Una consulta sobre el enunciado, específicamente la parte de GameCard.

En la parte de "Lineamiento e Implementación" (página 19) se menciona lo siguiente:

> "Todo archivo dentro del file system tendrá un valor “OPEN” dentro de su metadata que indicará si actualmente hay algún proceso que se encuentra utilizando el mismo. Bajo ningún concepto se permitirá a dos procesos abrir el mismo archivo en simultáneo. **En caso que suceda esto se deberá informar el error pertinente por archivo de log o consola.**"

No me queda claro cómo encaja esto con el tiempo de reintento de operación definido en el config (página 20):

> "Verificar si se puede abrir el archivo (si no hay otro proceso que lo esté abriendo). **En caso que el archivo se encuentre abierto se deberá finalizar el hilo y reintentar la operación luego de un tiempo definido por configuración.**"

La primer definición me da a entender que tengo que logear un error y terminar, la segunda a que sólo reintente la operación.
Como pregunta sobre el reintento: hace falta cerrar el hilo? No puedo poner un sleep en ese hilo y que reintente abrir el archivo?

Muchas gracias!

**Comment by ncoen97** [comment]
Por las dudas te comento, no te estamos dejando colgado sin responder, estamos ajustado el enunciado para que queden bien los requerimientos. Gracias por el comentario!

**Comment by Zheoden** [comment]
Buenas!!

Primero que nada perdon por la demora. Terminamos de revisar bien todo y hay un error entre esos 2 puntos. Lo co1rrecto es informar por archivo de log que no se puede abrir el archivo y reintentar la operacion despues del tiempo definido por archivo de configuracion.
Para el tema del reintento, si quieren poner un sleep o finalizar el hilo y volverlo a crear, depende de ustedes. Pueden hacer un sleep del hilo por el tiempo, no hay problema!

En los proximos dias vamos a estar haciendo este cambio en el enunciado del trabajo practico.
Muchas Gracias!

**Comment by gebonora** [comment]
Buenísimo, muchas gracias! Cierro el issue.
