### ISSUE TITLE
Duda de teoria sobre cuando actua el planificador

### ISSUE THREAD

**Issue by francorojo** [sisoputnfrba/foro#1710]
Buen diaa, tenia una consulta sobre un problema de detectar momentos donde actua el planificador. En este caso era un ejercicio de KLT y ULT. El planificador en teoria actuaria cada vez que se planifica un proceso. Osea que podria poner cualquier instante donde se eliga con el criterio del algoritmo un nuevo KLT por ejemplo. Pero ademas, tambien se puede considerar un instante donde se planifique un ULT (teniendo su propio algoritmo por ejemplo)? O en este caso el planificador no conoce a los ULT? Pero entonces quien planifica a los mismos?
Y si la respuesta es no, en el caso de jacketing, el planificador tiene que tener alguna vinculacion o no? Digo para reconocer que la entrada/salida no bloquea, el KLT informa cuando se bloquea solo y el planificador solo conoce a los mismos o tiene una vinculacion con los ULT? Graciaaas!

**Comment by iago64** [comment]
Buenas!
Las preguntas de los ejercicios de teoría por favor velas por los medios que te indicaron los profes / ayudantes de teoría :)
Este foro es solo para las dudas del trabajo practico :)

Saludos.-

**Comment by francorojo** [comment]
Ah bueno perdon, el otro dia hice una pregunta similar en discord y me dijeron que la mande al foro, esta podria ir a discord mejor no?

**Comment by karengrams** [comment]
¡Buenas!
Nos refieramos al foro del [campus virtual](https://www.campusvirtual.frba.utn.edu.ar/especialidad/mod/forum/view.php?f=730). 
Publicala ahi y algun ayudante/profesor te va a responder,
¡Saludos!
