### ISSUE TITLE
Pruebas con ngrok

### ISSUE THREAD

**Issue by EzeDiaz** [sisoputnfrba/foro#1711]
Buenas!

Estuvimos corriendo nuestro TP con ngrok y surgieron algunos inconvenientes:

- CASO BROKER: al levantar Broker, abrimos el túnel de ngrok y, sin que ningún otro módulo se conecte, llegan solicitudes/mensajes de vaya a saber quién. Entendemos que no hay nada local porque cuando lo corrimos local nunca tuvimos dicho problema.
- CASO GAME CARD: cuando Game Card se suscribe a Broker queda a la espera de mensajes y no llega nada raro. Sin embargo, una vez que llega un NEW_POKEMON, y Game Card devuelve el APPEARED_POKEMON correspondiente a partir de ese momento empieza a llegar basura. Para tomar dimensión, se termina armando un log de 23Mb de "Código inválido".
Estamos fuertemente inclinados a que los problemas surgen por el uso de ngrok, quizás hay algo que no estamos considerando y deberíamos.

Los invito a que, si alguien más tuvo problemas similares, colabore acá 😄.

PD: durante todas las pruebas locales que hicimos **nunca** pasó algo similar.

Gracias! Saludos!

**Comment by mgarciaisaia** [comment]
¡Hola!

Bienvenid@s a la internet pública, lo más parecido a _tierra de nadie_ que tenemos ahí afuera.

---

Que lleguen conexiones nuevas y no-solicitadas es, cuanto menos, _esperable_. Si bien Internet es grande _[citation needed]_, tampoco es **TAN** grande _[citation needed]_.

Hoy en día existen miles de bots y programas automatizados que se dedican a intentar conectarse constantemente a toda posible combinación de IP/puerto existente en Internet para, o bien _saber qué servidor está atendiendo del otro lado_, o bien _intentar abusar del servidor que atienda para conseguir acceso a esa máquina_. Sucede. Es un hecho.

Por eso, entre otras cosas, inventamos los handshakes en los protocolos: de algún modo, quiero chequear _rápido_ que quien se me conecta a mi servidor sepa jugar el mismo juego que yo, y descartarlo pronto si es un bot ruso intentando hackear mi máquina para minar Bitcoins (o si es un web browser que se conectó por error, da igual).

Entonces, para las conexiones nuevas que llegan al Broker, eso: hacer un handshake para chequear que el proceso que se me conecta efectivamente sea un cliente que espero, y cerrarle la conexión al toque si no lo es.

---

Eso sólo aplica, claro, para conexiones nuevas. Para conexiones existentes de procesos que chequearon que son de ustedes (ie, un GameCoso de ustedes que se conectó a su Broker) el problema probablemente sea otro (por esto de que ya tengo la conexión establecida usando un par de puertos distintos).

Habría que mirar más cosas/tener más info, pero yo arrancaría chequeando los valores de retorno de la función `send`. La función devuelve la cantidad de bytes que me garantiza que pudo enviar en esa invocación, que no es necesariamente la misma que la que yo le pedí que mande: por _cuestiones de redes_, puede que yo le pida que mande 100 bytes, pero `send` sólo logre garantizar el envío de 20. En ese caso, la función me devuelve un `20`, y es mi responsabilidad encargarme de reintentar el envío de los 80 que faltan.

Si pasara eso, y del otro lado tienen un proceso leyendo 100 bytes, ese proceso va a leer los 20 del `send` que hicieron recién, y después va a esperar 80 más. Que capaz son los primeros 80 de un `send` subsiguiente que hizo el cliente, intentando mandar unos 200 más. Y ahí, buen, ya los datos que llegan no tienen nada que ver con los que pretendían que lleguen, y _eventualmente_ van a interpretar como el campo "longitud del mensaje" 4 bytes que no eran la longitud del mensaje (si no cualquier otra cosa de otro mensaje), y ahí van a leer como parte de un mensaje bytes que nada que ver. Y, buen - el comportamiento no va a ser el esperado.

---

Todo esto son conjeturas fuertemente fundadas en la realidad y la experiencia. Ahora hay que ir y probarlas. Un buen primer paso es loggear (en modo debug, porque no es info relevante para una ejecución normal) cuántos bytes envían y cuántos reciben, para chequear si viene por acá el problema.

**Comment by mgarciaisaia** [comment]
@EzeDiaz ¿pudieron ver algo de esto?

**Comment by EzeDiaz** [comment]
Hola Mati, perdón que te colgué! Nos ganó la emoción de la solución jaja. Sip, implementar un handshake nos solucionó el problema y, en principio, no tuvimos otras complicaciones. Gracias por la respuesta tan detallada sobre el tenebroso mundo de internet 👻.

**Comment by mgarciaisaia** [comment]
¡Maravilla, che!

Cierro, entonces. Chiflen cualquier cosa. Y, como dicen por ahí, _quedate en localhost_.
