### ISSUE TITLE
[Duda de enunciado][Broker] - Procedimiento para almacenar en cache

### ISSUE THREAD

**Issue by Gonzalo-Avila** [sisoputnfrba/foro#1712]
Buenas! 

No estaríamos entendiendo el procedimiento que se aclara en el enunciado para almacenar nuevos mensajes en la cache. Cito: 

>1. Se buscará una partición libre que tenga suficiente memoria continua como para contener el valor. En caso de no encontrarla, se pasará al paso siguiente (si corresponde, en caso contrario se pasará al paso 3 directamente).
>2. Se compactará la memoria y se realizará una nueva búsqueda. En caso de no encontrarla, se pasará al paso siguiente.
>3. Se procederá a eliminar una partición de datos. Luego, si no se pudo encontrar una partición con suficiente memoria como para contener el valor, se volverá al paso 2 o al 3 según corresponda

Y una aclaración, que dice:

> Se deberá poder configurar la frecuencia de compactación (en la unidad “cantidad de búsquedas fallidas”). El valor -1 indicará compactar solamente cuando se hayan eliminado todas las particiones.

¿Compactar cuando se hayan eliminado todas las particiones? ¿A que se refiere con esto? ¿Qué sería una "búsqueda fallida"?

A nuestra forma de entender, todo mensaje nuevo DEBE ser almacenado en cache, de una forma u otra. Entonces, el procedimiento sería: 
1. Buscar un espacio libre suficientemente grande.
2. Si no existiera, compactar la memoria.
3. Volver a buscar. 
4. Si aún no se pudiese encontrar espacio, eliminar algún mensaje segun LRU o FIFO.
5. Repetir el proceso hasta que el mensaje nuevo pueda ser guardado. 

Pero no entendemos los casos alternos que plantea el enunciado.

Gracias, saludos!

**Comment by ncoen97** [comment]
Buenas.
Con respecto a los pasos que describieron ustedes, no están tan lejos de lo que pide el enunciado. Lo que les está faltando es el tema de los intentos fallidos, que básicamente lo que pide es que suponiendo que el valor de "cantidad de búsquedas fallidas" de la configuración sea 2, la primera "vuelta" de los pasos que describieron solo debería tener los pasos 1,4 y 5. En la segunda vuelta lo mismo, y en la tercera ya excedimos la cantidad de búsquedas fallidas antes de compactación, por lo tanto en esta tercera antes de eliminar una partición compactamos. Por eso en los pasos del enunciado dice "si corresponde".
Saludos!

**Comment by EliasReuter** [comment]
Hola
Gracias por la respuesta. >
Quedo claro eso de los pasos que mencionaste.

Lo único que no nos cierra bien es la parte:
>El valor -1 indicará compactar solamente cuando se hayan eliminado todas las particiones.

¿Como sería esto?

Saludos

**Comment by ncoen97** [comment]
Que sería lo que les genera duda? Básicamente si el valor de la config es -1, se compacta solamente cuando todas las particiones estén libres. Puede ser que en las próximas clases teóricas cuando ya vean memoria les queden mas claros estos conceptos.
Saludos!

**Comment by Gonzalo-Avila** [comment]
Buenas!

Es cierto, aún no lo vimos en la teoría, pero siempre tuvimos de referencia el libro de Stallings.

Cito el libro (_7ma edición, pág 314_):
> One technique for overcoming external fragmentation is compaction: From time to time, the OS shifts the processes so that they are contiguous and so that all of the free memory is together in one block.

Captura del libro:

![image](https://user-images.githubusercontent.com/44387608/82937911-571a2300-9f67-11ea-9ea3-de39ce5314d8.png)

En nuestro caso, en lugar de procesos, tenemos mensajes. 
Si todas las particiones están libres como en la imagen (a) de la captura de Stallings (o sea, se eliminaron todos los mensajes), ¿qué habría para compactar? 

Saludos!

**Comment by ncoen97** [comment]
Bien, si todas las particiones están libres como en la imagen (a), no van a tener que compactar porque el mensaje les va a entrar (ya que tienen toda la memoria disponible). El tema está cuando después de la imagen (h) se empiecen a liberar las distintas particiones ocupadas. Cuando pase eso, la memoria va a quedar con 6 particiones (14M, 6M, 8M, 6M, 18M, 4M) todas vacías y si yo quisiera poner algo en mi memoria de 20M no podría mas allá de que la memoria está vacía. Para esto esta la compactacion, para "juntar" las particiones libres.
Saludos!

**Comment by EliasReuter** [comment]
Hola
Coincidimos en como funciona la compactación.
Nuestra duda es esto que mencionaste y es como el enunciado:
>Básicamente si el valor de la config es -1, se **_compacta_** solamente cuando **_todas las particiones estén libres_**.

Y esto que mencionaste ahora y tambien entendemos conceptualmente:
>si todas las **_particiones están libres_** como en la imagen (a), **_no_** van a tener que compactar porque el mensaje les va a entrar

**Comment by ncoen97** [comment]
En la primera cita se hace referencia a múltiples particiones libres. En la segunda cita me refiero a una partición libre que ocupa toda la memoria (este seria el estado en el que quedaría si estando en el caso de la primera cita se compacta).

**Comment by Gonzalo-Avila** [comment]
Me parece que nos confundimos por el significado erróneo que le atribuimos a algunas palabras/expresiones. Creería que ya le agarramos la vuelta, pero te pido una confirmación así nos quedamos tranquilos 😄 

Al querer agregar un nuevo mensaje a la cache por PD:
1. Se busca alguna partición libre de tamaño suficiente. 
2. Si no la hay, se **vacía** una partición (según LRU o FIFO).
3. Se busca nuevamente alguna partición libre de tamaño suficiente. 
Los pasos 2 y 3 se repiten tantas veces como indique el valor de config. Si es -1, solo al vaciarse todas las particiones se procede al paso 4.
4. Si aun no hay lugar, se compacta la memoria. Compactar implica dos cosas:
    - Poner todas las particiones ocupadas de forma contigua, al principio de la memoria. 
    - **Eliminar** particiones vacías contiguas, o sea convertirlas en una misma partición de mayor tamaño.  

Y los pasos se repetirían hasta que el mensaje se pueda almacenar. 

¿Eso sería correcto?

**Comment by ncoen97** [comment]
Es correcto, es verdad que por ahí confunde un poco que usemos el termino "eliminar la partición" y dependiendo del contexto significa eliminarla o liberarla. Puede ser también que el hecho de que no hayan visto memoria también ayude a confusión, igualmente voy a tenerlo en cuenta.
Saludos!

**Comment by Gonzalo-Avila** [comment]
Perfecto! Quedó claro.

Muchas gracias! Saludos
