### ISSUE TITLE
esperar_cliente() bloquea la recepcion de otros mensajes

### ISSUE THREAD

**Issue by FedeMacias** [sisoputnfrba/foro#1713]
Buenas
Estamos teniendo un problema con las conexiones del team.
En una forma simplificada tenemos un hilo que se conecta al broker y un hilo que atiende a los clientes (gameboy)
La funcion esperar_cliente() nos está bloqueando el hilo de conexion con el broker, entonces no podemos recibir mensajes del broker,  y solamente recibimos del gameboy correctamente.
Como hacemos para mantener el esperar_cliente() en un while sin que nos bloquee el hilo que atiende al broker??

Saludos

**Comment by SofiCortes** [comment]
Les respondí en el mail pero va por acá también
Consulten #1665  #1654
