### ISSUE TITLE
Team: ¿El mapa tiene solo un cuadrante o los cuatro?

### ISSUE THREAD

**Issue by leobz** [sisoputnfrba/foro#1714]
Hola! La consulta es:

¿Sólo van a aparecer pokemones en posiciones positivas (1er cuadrante)?,  ¿Puede aparecer un pokemon en la posición (-1,1)?

**Comment by afilgueira** [comment]
Hola, nos estás dando grandes ideas... para el próximo cuatrimestre... ya me imagino entrenadores cazando un [Uhcakip](https://i.ytimg.com/vi/l7G4iZP_Nqo/maxresdefault.jpg).

Para este, nos quedamos en ~casa~ el primer cuadrante (ambas posiciones positivas). 

Saludos!

**Comment by leobz** [comment]
JAJAJAJJA. Dale, gracias!
