### ISSUE TITLE
Duda con ids correlativos

### ISSUE THREAD

**Issue by MarcosInfantino** [sisoputnfrba/foro#1715]
Hola! Tengo una duda sobre el enunciado: hasta ahora yo venía usando id normal e id correlativo para TODOS los mensajes. Sin embargo, a raíz de la última modificación del enunciado del tp, me surgio la siguiente duda: me va a interesar que todos los mensajes tengan un id correlativo? o solo algunos? (appeared, localized)
Gracias!

**Comment by iago64** [comment]
Aloha!

Vos tenes en total 6 mensajes de los cuales 3 mensajes son respuestas, en estos es necesario el id_correlativo, en los otros es un dato que no tiene sentido de que este, ahora si lo estas mandando en los mensajes porque lo tenes serializado de esa forma o porque queres ser polimorfico a la hora de guardarlos, no hay problema.
Lo importante es que los que no lo necesitan no fuerces que alguien tenga que insertarlo.

Saludos.-

**Comment by karengrams** [comment]
¡Buenas!
¿Quedo resulta la duda?
Saludos :)

**Comment by MarcosInfantino** [comment]
Si! Gracias!
