### ISSUE TITLE
Semaforos para manejar el acceso a archivos pokemon

### ISSUE THREAD

**Issue by guidoenr4** [sisoputnfrba/foro#1716]
en una parte del enunciado dice :
> Todo archivo dentro del file system tendrá un valor “OPEN” dentro de su metadata, que indicará si actualmente hay algún proceso que se encuentra utilizando el mismo. **Bajo ningún concepto se permitirá a dos procesos abrir el mismo archivo en simultáne**o, en caso que suceda esto se deberá informar el error pertinente por archivo de log o consola.

creo que estoy en lo correcto al momento de pensar que hay que usar un semaforo mutex para garantizar la mutua exclusion por cada pokemon distinto.

un ejemplo seria tener un `new_pokemon Pikachu 3 2` y otro `new_pokemon Pikachu 4 1`.
Supongase que un hilo del gamecard ya esta realizando operaciones con el primer pikachu que le llego (verificando el metadata, viendo el archivo, etc) significaria que estaria trabajando con ese `pikachu` y mi pregunta es:
debo crear un `mutex` por cada tipo de pokemon distinto verdad? porque en el ejemplo de arriba, por mas que tenga dos mensajes distintos, el pokemon es el mismo, y no voy a tener otra carpeta en mi punto de pontaje que se llame _"pikachu2"_ . 
entonces, esos semaforos para garantizar que no accedan al mismo archivo se crean al inicio uno por cada tipo de pokemon distinto? o van dentro de la estructura pokemon? porque si es uno distinto por cada pokemon, tendria que hacer **n** semaforos siendo **n** la cantidad de tipos de pokemones.

**Comment by guidoenr4** [comment]
aunque lo pense tambien, y cada pokemon tiene un valor `OPEN` que es `YES/NO` tambien podria manejarlo por ahi.. preguntando si actualmente esta abierto o no y descartando los semaforos.

**Comment by IvanArnaudo** [comment]
Lo que entendí yo del enunciado es que, cuando quieran hacerse cambios en un pokemon, primero verificas si existe, y después lees el archivo de metadata para saber si alguna otra instancia de gamecard lo tiene abierto. En caso de que esté en OPEN=Y, esperás el tiempo que diga en el archivo de config y volvés a intentar hasta que esté en OPEN=N.
De esta manera, los mismos archivos te servirían de semáforos.

**Comment by guidoenr4** [comment]
claro, fue lo que pense. Si es asi genial

**Comment by iago64** [comment]
Buenas buenas!

Es tal cual dice @IvanArnaudo, con el flag de OPEN se resuelven el problema, a lo mucho les diría que cuando checkeen si algún archivo esta abierto aseguren que solo de a 1 hilo pueda hacerlo ;)

Saludos.-

**Comment by guidoenr4** [comment]
Buenas tardes, quedo clarisimo eso.. 
pero me surgio otra duda, en que momento pasaria un pokemon a `OPEN`?, porque si te pones a pensar en profundidad vos al estar leyendo el archivo ya estas "accediendo" de cierta manera al archivo pokemon, por lo tanto una vez que lo estes verificando pasaria a `OPEN`.

**Comment by ncoen97** [comment]
Buenas, el archivo de metadata del Pokemon no hay problema que lo abran múltiples hilos si es solo en modo lectura. El valor de OPEN de la metadata se refiere al contenido del archivo del Pokemon en sí.
Saludos!
