### ISSUE TITLE
Consulta sobre partición dinámica

### ISSUE THREAD

**Issue by ariel-sng** [sisoputnfrba/foro#1718]
Hola tenía una consulta sobre la consigna. 
En el broker, al almacenar los datos en la caché, la consigna dice que la partición tiene un tamaño que puede ser entre un mínimo (digamos 32) y un máximo, el tamaño de la memoria (digamos 2048).
La pregunta es si las particiones deben ser múltiplos del mínimo o no necesariamente.
Por ejemplo si quiero almacenar 80 bytes
a) genero una partición de tamaño exacto (80)
o bien
b) genero una partición de 96 bytes (3 slots de tamaño mínimo (32) que puede almacenar esa data).

Si bien estoy implementando esto, todavía no vi ese tema en la cursada, por lo que tengo esta duda sobre la flexibilidad de la partición dinámica.
Gracias!

**Comment by iago64** [comment]
Buenas buenas!

Justamente la idea de que sean dinámicas es que no los queremos atar a múltiplos de nada, con lo cual, por favor no se la compliquen con ideas rebuscadas :)

Abrazo.-

**Comment by ariel-sng** [comment]
Perfecto, muchas gracias!
