### ISSUE TITLE
TEAM - mensaje appeared pokemon

### ISSUE THREAD

**Issue by fgiannotti** [sisoputnfrba/foro#1719]
Buenas pero leyendo este [issue ](https://github.com/sisoputnfrba/foro/issues/1673) tengo una duda:

Se comenta un ejemplo rápido: 

> Asumí que tenes un GET pokemon y el broket te va a decir,
> "el mensaje que mandaste es el ID1".
> Cuando Gamecard responde, le va a decir 
> "este es correlativo al 1" y el broker le va a generar un id único.
> Esto hace que al team le llegue el ID del mensaje 2 y ID correlativo 1

Ese ID de mensaje 2, le sirve de algo al Team? No logro encontrarle la utilidad para el mismo. ( A menos que sea la parte de los logs del TEAM (item 7): "Llegada de un mensaje (indicando el tipo del mismo y sus datos)."

Además en el mensaje "APPEARED_POKEMON" del gameboy al team no hay ningun id en sus argumentos.

> ./gameboy TEAM APPEARED_POKEMON [POKEMON] [POSX] [POSY] 
(pagina 31 enunciado v1.3)

**Comment by ncoen97** [comment]
Buenas!
En el caso del GET que planteas al principio, la idea del id 2 es que el Team lo use para filtrar los Localized que le van llegando. Esto lo necesitas porque al estar suscrito a la cola de Localized, le van a llegar los mensajes que sean para otros Teams también.
Con respecto a la interfaz del gameboy, en el caso del Appeared no pusimos ID porque en este caso no nos pareció necesario, pero si quieren agregarlo internamente por un tema de consistencia pueden.
Saludos.

**Comment by fgiannotti** [comment]
Hola Nico,
Perdon, no me termina de quedar claro.

No usaría en ese caso el ID 1 para filtrar los localized? Porque es el ID que me devolvieron en GET para referenciar a un futuro Localized. Pensaba que ese id 2 era mas algo interno del broker de ponerle un id a todos los mensajes si o si

**Comment by iago64** [comment]
Buenas!

Vamos en orden:
El broker SIEMPRE va a generarle un ID a los mensajes y de hecho va a ser lo que debería informarle al que le mando el mensaje a modo de ACK.
El Team va a recibir localized de TODOS los teams (no se olviden que no van a tener 1 solo team, posiblemente tengan 3 o 4) y solo le van a importar los que sean respuesta al GET que el genero.

Saludos.-

**Comment by ncoen97** [comment]
@fgiannotti Perdón, error de tipeo. Como bien decís va a usar el ID 1 para filtrar el Localized.

**Comment by fgiannotti** [comment]
Joya, muchas gracias chicos!!

**Comment by iago64** [comment]
Listo, vamos cerrando el issue entonces, cualquier cosa lo pueden reabrir.
