### ISSUE TITLE
Duda sobre un párrafo del enunciado sobre BROKER

### ISSUE THREAD

**Issue by CamiMargni** [sisoputnfrba/foro#1720]
Hola! leyendo nuevamente el enunciado del tp no comprendí por completo una sección del broker, la enlazo:

_**"El administrador de colas de mensajes debe mantener una lógica de conocer qué mensajes con correlativos ya fueron informados en una cola para no generar redundancia en la misma. Esto quiere decir que si hay varios suscriptores en la cola de mensajes inicial puede haber varias respuestas al mismo (las cuales deberían ser la misma respuesta) por lo que es el administrador de cola de mensajes el que sabe que ese mensaje ya fue agregado a la cola destino y  debe ignorarlo."**_

No comprendo a qué hace referencia con "las cuales deberían ser la misma respuesta" , eso no se contemplá ya en el apartado de memoria donde indica que un mensaje almacenado debe tener una lista de suscriptores a los cuales ya se les envió un mensaje?

**Comment by danielAlderete93** [comment]
Hola! Me sumo a la duda.

Nosotros lo interpretamos que tanto los mensajes Appeared, Caught y Localized que tienen id correlativos, solo pueden estar una vez en la mq según el valor de la id correlativa. 

_**Ejemplo**_: **Team#1** y **Team#2** mandan ambos un mensaje Appeared al Broker. Ambos mensajes tienen _diferentes parametros_ pero con el _mismo id correlativo_. Supongamos que el mensaje de **Team#2** llega primero al Broker. Este lo cachea (ya que reconoce la id correlativa como única) y cuando llega el mensaje del Team#1, el Broker lo ignora y no lo cachea ya que existe otro mensaje Appeared con el mismo id correlativo. 

Seria correcta esa logica?

**Comment by ncoen97** [comment]
Buenas, es correcto lo que plantea @danielAlderete93, la idea de esto es que no pueda haber más de una respuesta al mismo mensaje.
Me parece que con lo que escribieron arriba queda bastante claro, cualquier duda que siga quedando pueden volver a consultar.
Saludos!

**Comment by karengrams** [comment]
¡Buenas buenas! 
¿Como va? Espero que bien ¿Quedo resulta la duda?
Saludos :)

**Comment by CamiMargni** [comment]
Buenas! sí, muchas gracias!
