### ISSUE TITLE
[TEAM] Respuesta del Broker después de mandarle un GET 

### ISSUE THREAD

**Issue by julchat** [sisoputnfrba/foro#1723]
Hola, según el enunciado del tp, luego de que yo mande un mensaje de GET POKEMON en la inicialización del estado Team, debo obtener el ID de dicho mensaje desde el broker, lo que implicaría que despúes de hacer el send, haga un recv para conseguir el ID que quiero.
El tema es, como sincronizo eso? Podría pasar que hago el send e inmediatamente después hago el receive tan rápido que pedí el ID antes de que el broker lo tenga listo(lo procese), y esto puede pasar tanto con el broker caído como andando.
Por la respuesta que consigo interpretaría que el broker está caído, aunque podría no estarlo.

Lo que  se me ocurrió es meter un semaforo después del send, y tener un hilo adicional que de alguna forma se esté fijando activamente si el resultado está listo, el problema de esto sería que tampoco podría diferenciar de si el servidor está tardando mucho o si está caído, a menos que haga algo feo como un sleep(t), y bueno, hay una espera activa.

**Comment by ncoen97** [comment]
Buenas! La función recv() es bloqueante, y en el caso que nombras se quedaría esperando que se llene el buffer con la cantidad de bytes que vos le especificaste, así que se va a quedar esperando unos segundos hasta que responda el Broker y no va a haber problema.
En el caso de que se caiga el Broker, vas a tener que tener en cuenta el valor de retorno de la función. Si usas el comando `man recv` desde la consola de linux, te especifica el retorno que tiene la función en caso de error.
Saludos!
