### ISSUE TITLE
Duda de Cola de Mensajes [Broker]

### ISSUE THREAD

**Issue by Aeiroa** [sisoputnfrba/foro#1724]
Buen día! 
Quería saber si cuando yo envío un mje a todos los suscriptores, luego este se borra o tiene que permanecer en la cola para lograr mandárselos a los siguientes suscriptores.. Tendría, a la larga, una cola de infinitos mjes?

**Comment by ncoen97** [comment]
Buenas, en el enunciado hay dos casos especificados en los que se borran los mensajes. Uno es cuando el mismo ya fue entregado a todos los suscriptores y la otra es cuando se necesite mas espacio para mensajes nuevos.
Saludos!
