### ISSUE TITLE
TEAM - Archivo de configuración v1.3

### ISSUE THREAD

**Issue by ezeBalsamo** [sisoputnfrba/foro#1725]
Buenaas! Cómo andan? Espero que re bien! 
Viendo los ejemplos del archivo de configuración del proceso Team en la versión 1.3 me surgió una duda con el primer entrenador del primer ejemplo, en el cual figura que:

- Tiene: Pikachu|Squirtle|Pidgey
- Necesita: Pikachu|Piky

Dado a que este entrenador entra al sistema con más pokemones de los que necesita atrapar y dado a que no se podría generar un intercambio, ya que quedaría de todas formas con más pokemones de los que necesita, este caso me sonó raro.

Cómo sería el caso de uso para proceder en una situación así?

Muchas gracias, saludos!

**Comment by iago64** [comment]
Buenas buenas!

Error de tipeo, no te preocupes, no va a pasar y de paso lo vamos a estar corrigiendo en el enunciado :)

Saludos.-

**Comment by ezeBalsamo** [comment]
Dalee, muchas gracias!!
