### ISSUE TITLE
Duda - Caught Pokemon 

### ISSUE THREAD

**Issue by Frank115** [sisoputnfrba/foro#1726]
Buenas noches, en el grupo tenemos un par de dudas:

1. Que pasaría cuando el TEAM recibe un mensaje `CAUGHT [ID] NO` (teniendo un entrenador a la espera de ese ID) ? 
El entrenador quedaría en estado blockeado a la espera de ser planificado?

Nosotros pensamos lo siguiente:

Aceptamos los `APPEARED/LOCALIZED` de las especies que necesitamos **hasta que** ubiquemos en el mapa todos los pokemones que necesitariamos para cumplir mi objetivo. (El mapa lo "actualizamos" cuando recibo uno estos mensajes y **decido procesarlo**)

A partir de ese momento el resto de los `APPEARED/LOCALIZED` que se reciban sobre las mismas especies se "descartan" (aceptamos pero no procesamos nada).

Paso un ejemplo que me genera dudas:

> Supongamos que tengo un proceso team, con 2 entrenadores, y sus objetivos son 1 pikachu y 1 squirtle.
> Llega un pikachu, planifico a un entrenador, eventualmente hace un catch y **antes de recibir respuesta de ese catch**, llega otro pikachu.

En este caso, por la logica que detallamos más arriba, decidimos no procesar ese mensaje.

Si la cantidad de pokemones (supongamos, en un test) sea justa para completar el objetivo global de mi team, pero dado a esta lógica _pierdo algun mensaje_ (como se ve en el ejemplo), el proceso team no podria terminar nunca. 

Esto nos hace ruido, estamos pensando algo mal?

**Comment by iago64** [comment]
Buenas!!
Perdón la demora en contestar el issue.

Justo la situación que están planteando podrían resolverla de una forma copada que es manteniendo todas las posiciones que se enteren de cada especie de pokemon, entonces si por esas quieren hacer un catch y les dicen que no lo pusieron capturar, siempre pueden moverse a la siguiente ubicación a ver si ahí tienen algún pokemon 😄 

Abrazo.-

**Comment by karengrams** [comment]
¡Buenas!

@Frank115  ¿Quedo resulta la duda?

¡Saludos!

**Comment by Frank115** [comment]
Sii, muchas gracias
