### ISSUE TITLE
Caída de un suscriptor

### ISSUE THREAD

**Issue by nburza** [sisoputnfrba/foro#1728]
Hola estábamos teniendo algunas dudas.

En el caso del Broker: 
Tenemos entendido que un mensaje debe ser eliminado de la cola cuando todos  los suscriptores de la misma enviaron el ack. En caso, de que un suscriptor nunca lo envíe, ¿Qué debería pasar? Como por ejemplo si ese proceso suscriptor se cae, o esa suscripción termina porque era por un tiempo determinado.

En el caso del Team:
Ante una caída y recuperación, ¿este debería volver a empezar con su estado inicial o tendría que ir persistiendo su estado a medida que pasa el tiempo? Porque si empieza de cero no vemos la necesidad de diferenciar un proceso nuevo de uno que se cayó previamente.

**Comment by iago64** [comment]
Buenas buenas!

Respecto al Broker, cuando un suscriptor se cae, eventualmente, el mensaje puede que lo tengas que eliminar de la cache si te quedas sin espacio y el algoritmo te dice que le llego el turno, con lo cual no se compliquen tanto con eso.

Team: Si se cae... arranca de 0, pero es importante que sepan cual es porque es posible que haya mensajes del broker que a propósito no quieren que les lleguen porque "ya les llegaron"

Saludos.-

**Comment by nburza** [comment]
Ok, la parte de los acks la entendimos. Pero la de los mensajes que ya le habían llegado no.
Hay una parte del enunciado que dice:

"Cada vez que un proceso se suscriba globalmente a una cola de mensajes, el Broker deberá validar en su memoria principal: si tiene algún mensaje de dicha cola de mensajes y enviarles los mismos."

Nosotros lo tomamos como que si un proceso nuevo se suscribe a una cola y tengo mensajes cacheados de esa cola, yo le envío todos los que tengo, y si no le sirven los ignora por su correlation_id. Si un team caído y recuperado arranca de 0, este pierde conocimiento de cuales son los correlation_id que está esperando. Entonces es como si fuera un proceso nuevo. Por eso no entendemos por qué tendríamos que tratarlo distinto teniendo en cuenta que a los procesos nuevos les estaríamos mandando varios mensajes que no le sirven.

**Comment by iago64** [comment]
Aloha!
Si, justamente el Team no sabe que correlation_id espera por lo tanto vas a tener muchos mensajes descartados.
Peeero, desde el broker si te importa saber que mensajes le mandaste a ese team_id porque puede ser que justamente como no hubo mas appeared el team se quede clavado esperando mensajes que como "ya le llegaron" no le vuelvan a llegar :)

Saludos.-

**Comment by nburza** [comment]
Te voy a ser sincero. No logro entenderlo, no me queda claro cual es el flujo que planteas en el ejemplo. Disculpa que siga preguntando, pero me sigue quedando la duda.

**Comment by iago64** [comment]
No vuelvas a pedir disculpas por seguir preguntando porque ahí si dejo de contestarte 😃. El foro esta para que consulten todo lo que necesiten para el TP 😄 

A ver si planteando los escenarios se entiende:
**Escenario 1**: Se levanta un team nuevo
Al momento que el team nuevo (TeamZ) se suscriba a las diferentes queues del broker, lo que va a hacer este es enviarle todos los mensajes que tenga cacheados y los va a marcar como enviados.

**Escenario 2**: Un team que estaba conectado se cayo y lo reconectas (y vamos a basarnos solo en la queue de APPEARED para hacerlo corto)
Acá pasan 2 cosas:
1.- El team pierde todo lo que tenia de avance, inicia de nuevo y lo único que tiene en común con su ejecución anterior es el ID de team (TeamX).
2.- El broker tiene cacheados 3 mensajes en la queue de APPEARED (Ids 1, 2 y 3) de los cuales solo el id 1 se lo habías mandado al team en la ejecución anterior.
En el momento que subas el team nuevamente cuando barres la lista de mensajes de la queue APPEARED vas a encontrar que al TeamX le mandaste el msj 1 pero no el 2 y el 3, por lo tanto lo que tenes que hacer es mandarles el msj 2 y 3.

Espero que ahora si se entienda un poco mas la idea, cualquier cosa avisa y veo de hacerlo en algún diagrama :)

Saludos.-

**Comment by nburza** [comment]
Ok, con esta última explicación nos queda bastante más claro como debería comportarse el broker en estos casos. Ya puedo dar por cerrado el issue.

Muchas gracias por las respuestas :)
Saludos
