### ISSUE TITLE
Consulta sobre send y recv de un mensaje.

### ISSUE THREAD

**Issue by emarcosgv** [sisoputnfrba/foro#1729]
Estoy implementado los envíos de mensajes para el tp. En mi grupo solucionamos el envío con 2 sends, el primero envía el tamaño total del paquete y el segundo manda el paquete. Al principio enviabamos un solo send y recibiamos con 3 recv como vimos en el video del tp0. Consultamos con nuestro ayudante por este tema , no voy a decir el nombre porque es un genio y nos ayuda muchisimo , él nos dijo que hagamos un solo send y un solo recv, al no saber el tamaño del paquete, en el momento de recibir creamos un buffer lo suficientemente grande y recibamos ahi. 
void* buffer = malloc(100);
int bytesRecibidos=recv(socketCliente, buffer, 100 * sizeof(void), 0);

Hicimos esto, resulta que el mensaje new del broker, ocupaba 44 bytes en mi caso puntual, y los otros 56 eran basura, y eso me trababa todo el broker. Entonces la consulta en si es : como hago para hacer un solo send y un solo recv si no se el tamaño total variable que tengo que esperar?

**Comment by gastoncastineira** [comment]
La versión corta: No podés. Por algo estaba de esa forma en el TP0.
Te recomiendo que re-leas el doc de serialización que subimos con el TP0 y también que te veas el video de la charla se serialización que compartimos hace un tiempo. Ahí explicamos todo con el mayor detalle posible

**Comment by emarcosgv** [comment]
Mirá, la verdad es que me gustaría saber ese "algo", por eso pregunté, ya había visto la guía, el tp0, el video de serializacion y todo lo que me mandaste a ver. Abrí el issue porque me dijeron por telegram que lo habra, pero para que me contesten así y no es la primera vez, me corto los dedos antes de volver a escribir algo acá.

**Comment by iago64** [comment]
Buenas buenas!!

1.- No nos olvidemos que el grupo de telegram al que haces referencia es para la parte teórica de la materia y no para la practica. De hecho tuvimos ciertas discusiones al respecto en el pasado y por eso que te pedí que abras el issue ya que la idea del foro es justamente canalizar las dudas del tp.

2.- Ese algo que te dice Gaston es una cuestión de manejo de paquetes, que posiblemente en el issue sea complicado de explicar y que quede claro, pero bueno, let's try!

En tu TP, cuantos tipos diferentes de mensajes tenes? 1, 2, 3... 50? 
Exacto, tenes varios tipos de mensajes y vos a priori, no tenes una forma de saber que mensaje te esta llegando, entonces lo primero que haces es recibir una cabecera de tamaño fijo donde vos vas a saber que mandas en tu mensaje:
Entonces aca es donde se te empieza a complicar la cosa, porque si vos tenes un mensaje que por ejemplo recibe un **payload fijo**, simplemente haces el recv() del payload y listo, resolviste tu problema con **2 recv()**
Un ejemplo de payload fijo seria por ej si en el siguiente mensaje tenes un tipo de dato como el siguiente:
```
typedef struct {
	uint32_t dni;
	uint8_t edad;
	uint32_t pasaporte;
	char nombre[14]; //Donde el nombre es de tamaño fijo
} t_persona;
```
![image](https://user-images.githubusercontent.com/1622109/83778852-9defd300-a661-11ea-974d-5c3cc11b5240.png)


Ahora que pasa si por ejemplo tenes que mandar cosas variables? Por ejemplo un nombre y un mensaje que pueden variar en el largo? Usando un tipo de dato generado podría ser:
```
typedef struct {
	char* username;
	uint32_t username_long;
	char* message;
	uint32_t message_long;
} t_package;
```

Ahí tenes que empezar mínimo a hacer algo que me diga el size de lo que envió y atrás el mensaje entonces te empieza a quedar un paquete con la siguiente forma:

![image](https://user-images.githubusercontent.com/1622109/83779159-fb841f80-a661-11ea-8335-d3c94d7dde6b.png)

Donde vos antes de cada cosa variable mandas el tamaño y al momento de recibirlo tendrias:
recv() - Para la cabecera
recv() - Para el size del username
recv() - Del username con el size que recibiste justo antes
recv() - Para el size del message
recv() - Del message con el size que recibiste justo antes
Con lo cual hiciste **5 recv()** para obtener **1 mensaje**.

Respecto al tema del **send()** es necesario que hagan **1 y solo 1 send()** ya que si haces varios send puede que empieces a tener condiciones de carrera con otros procesos que tambien estan mandando información al mismo socket y por lo tanto te escriben en el mismo buffer.
No te olvides que al final del día todo cae al buffer del SO que gestiona las conexiones de red y si justo se te da la casualidad que 2 procesos estan enviando cosas al mismo socket, el quilmobo que se puede armar no lo vas a poder debuguear (creeme que llegas a querer tirar el tp mas de 4 veces cuando pasa y ahí incluso valgrind te deja de salvar porque es un problema mas allá de un puntero).
Lo bueno de que si haces **1 solo send()** el SO se encarga de dejarte el mensaje completito seguido en el buffer ya que eso es un poco parte de la magia del protocolo TCP que lo van a ver mejor en Redes en 4to y van a entender todas las capas que intervienen a nivel de SO y placa de red para que nosotros desde C podamos hacer send() y recv() lo mas panchos.

Espero que la duda haya quedado resuelta, cualquier cosa avisa.
Saludos.-

**Comment by emarcosgv** [comment]
Gracias Damian.
