### ISSUE TITLE
Duda del Deadlock (sincrono o asincrono)

### ISSUE THREAD

**Issue by francorojo** [sisoputnfrba/foro#1730]
Buen diaa, teniamos una consulta con respecto al deadlock. Al principio del diseño del tp se nos ocurrio plantear el deadlock como un algortimo que se corria luego de que todos los entrenadores tenian su cantidad necesitada, para solucionar aquellas situaciones donde los pokemons estaban mal ubicados. Pero luego decidimos que es mejor que el mismo sea un hilo aparte, que este preguntando y atento a solucionar este problema sin necesidad de esperar hasta el final para ahorrar tiempo.
Pero esto no puede causar espera activa, es correcto si lo hacemos por tiempo? por ejemplo cada 30 segundos? es poco o mucho?
(Y ademas durante se mueve entrenadores para solucionar el intercambio, el planificador no puede tambien mover a otros, porque seria monoprocesador, o ejecuta uno u ejecuta otro no?)
Gracias!

**Comment by iago64** [comment]
Buenas!

Por que se quieren complicar las cosas antes de tiempo?
Si lo resuelven al final no hay problema :)

Abrazo.-

**Comment by francorojo** [comment]
Ah buenisimo, sisi seria mas simple, podriamos correr el algoritmo elegido en la config hasta q todos los hilos de entrenadores hayan alcanzado su cantidad maxima, y luego viene el algoritmo, donde a aquellos q se quedaron trabados sin finalizar su ejecucion por tener pokemones no deseados, los soluciona y termina el team. Nos habian dicho un sabado que tenia q ser con deteccion para que cuando tal vez haya un pequeño tiempo donde el planificador no actua y ya hay pokemones q estan mal se vayan arreglando (por ejemplo ya pueden venir mal de la config y hasta q llegue un localized o appeared tal vez tambien ya se podia empezar a correr). Pero si se puede asi al final joya, muchas gracias por responder!

**Comment by karengrams** [comment]
¡Alo!

Ayer lo hablamos en soporte y respondo por aca: si. No es requerimiento que lo hagan asincrónico. 

Cierro issue, cualquier duda que se les presente lo vuelve a abrir.

¡Saludos!
