### ISSUE TITLE
[BROKER] hilos del broker y comunicación con Team

### ISSUE THREAD

**Issue by SebastianNLerner** [sisoputnfrba/foro#1731]
Buenas, teníamos un par de dudas con respecto al envió de mensajes entre procesos:
1. En la comunicación entre el BROKER y el TEAM, para cada envío de mensajes por colas de suscripción, hay que quedarse esperando en el mismo socket para la confirmación o hay que mandar la confirmación por otro socket? Podría haber problemas de sincronización si se usa el mismo socket?
2. cuando le llegue un mensaje al BROKER, en ese mismo momento debe enviarlo hacia los suscriptores, o agregarlo a la lista y que otra función se encargue de enviarlo

**Comment by iago64** [comment]
Aloha!
Que felicidad cuando las preguntas son así de puntuales y enumeradas 😃 
1.- Pueden usar el mismo socket para recibir el ACK del mensaje que acaban de enviar, no hay ningún problema con eso, no te olvides que si se cae la conexión vas a recibir un -1 😉 

2.- Sinceramente? Da igual, manejenlo como les resulte mas comodo, siempre y cuando hagan lo que tienen que hacer 😃 

Abrazo.-

**Comment by foviedo** [comment]
Una pregunta Iago, respecto a lo del -1, consulta:
1_Si yo hago recv(conexion, &variableDondeVoyARecibir, sizeof(unit32_t),MSG_WAITALL)
Si se cae la conexión, te referís a que variableDondeVoyARecibir va a quedar -1? 
2_Si se cae la conexión y se me intentan volver a conectar (de forma exitosa), yo voy a intentar mandarle el mensaje de vuelta? No estoy seguro de si esta es una situación que puede ocurrir

**Comment by karengrams** [comment]
¡Buenas buenas!

¿Como va? @foviedo 

Vamos de a poco:

> 1_ Si yo hago recv(conexion, &variableDondeVoyARecibir, sizeof(unit32_t),MSG_WAITALL). Si se cae la conexión, ¿te referís a que variableDondeVoyARecibir va a quedar -1?

Con nuestro gran amigo [```man recv```](https://linux.die.net/man/3/recv), podemos ver que el ```-1``` no lo coloca en el segundo parámetro, sino que la función devuelve ciertos valores dependiendo del resultado obtenido; como decís vos, la función devolverá ```-1``` en caso de desconexión, pero el buffer va a estar lleno de basura. 

>2_ Si se cae la conexión y se me intentan volver a conectar (de forma exitosa), ¿yo voy a intentar mandarle el mensaje de vuelta? No estoy seguro de si esta es una situación que puede ocurrir

La respuesta es no, no tiene que volver a mandarlo, ¿por qué? En la próxima pregunta lo voy a explicar.

> 3_ Añadiendo a la anterior, ¿puede llegar a ocurrir la situación de que me quede esperando para siempre incluso con la conexión no caída? O si pasa eso, ¿es un error de código mío?

La respuesta es no, no se quedara esperando a enviar el mensaje al Broker. Voy a citar una partecita el enunciado lo explica mejor: 

_"(...) si el broker se encuentra sin funcionar o se cae durante la ejecución, el proceso Team debe seguir procesando sus funciones sin el mismo. Para esto, se contarán con funciones default para aquellos mensajes que el Proceso Team envíe directamente al Broker."_

Por ende, con el Broker caído (o nunca levantado), el Team deberá seguir un comportamiento default que definimos cuando se estableció cada flujo del envió de mensajes por parte del Team, siguiendo su ejecución a pesar de no habérselo mandado.

Cualquier cosita, no duden en volver a preguntar.

¡Saludos!

**Comment by foviedo** [comment]
1)Lo testee hace un rato y me devolvió 0, hice algo mal?  
Respecto a las otras respuestas, mis preguntas eran paradas en broker, vuelvo a plantear la pregunta
2)Va a existir la situación en la que el proceso team se caiga? (y no el broker, el broker siga levantado)
3)En caso de que sí ocurra esto, cómo debería yo, desde broker, reaccionar a ello? Tengo que volver a intentar enviar un mensaje ya enviado? 
4)El team va a reconectarse a mí? Cuando se reconecte, tengo que reconocer que es el mismo que era antes y voy a tener que validar qué mensajes le envié y qué mensajes no?
5)La tercer pregunta (de mi comentario anterior), me preguntaba si al hacer el intercambio de mensajes una "conversación" 
A_Team me pide la subscripcion a, por ejemplo, localized
B_le mando el tamaño de localized a team, luego de eso, le mando el primer localized
C_Team lo recibe y luego de eso, me envia el ACK
En caso de que haga esta estructura, va a ocurrir en alguna situación (por cuestiones de sockets que desconozco y que no puedo testear cómo funcionaría en computadoras por separado como se hace en el labo de sistemas por ejemplo) que yo desde el broker me quede infinito tiempo esperando, por ejemplo, el ACK que me va a enviar team en el paso C? Probándolo en dos consolitas una al lado de la otra en un entorno seguro no parece ser el caso, pero en un momento me lo plantearon y quedé con miedo diría

**Comment by iago64** [comment]
Buenas @foviedo 
1.- El 0 es que te cerraron la conexion (fijate en el [man de recv()](https://www.man7.org/linux/man-pages/man2/recv.2.html) que puede devolverte -1, 0 o el size de lo que recibio)

2.- Si, de hecho es un escenario mas que posible, por algo el team tiene que enviar el ack de que recibio el msj para que el broker tenga registro de eso y en caso de que se vuelva a lavantar el team no le mande de nuevo ese mensaje.

3.- Cuando se cae el Team, del lado del broker simplemente es un: _Gracias vuelva prontos_.

4.- Efectivamente, el team se puede reconectar y tenes que saber que mensajes le enviaste (bien puede que el team te envie cual es su id) y mandarle los que no le enviaste.

5.- Olvidate, no hay timeouts infinitos, en la red del labo (o en general entre 2 pcs) es muy muy muy poco probable que la red te quede for ever esperando, es mas posible que te llegue un -1 y ahi es el tipo: _Se venia cayendo.... y se cayo_

Saludos.-

**Comment by karengrams** [comment]
¡Buenas!

¿Quedan resueltas las dudas?

**Comment by foviedo** [comment]
De mi parte sí, gracias
