### ISSUE TITLE
Algoritmo SJF con desalojo

### ISSUE THREAD

**Issue by Charlyd96** [sisoputnfrba/foro#1733]
Hola!
Estoy tratando de diseñar el modelo para implementar el algoritmo SJF con desalojo y no se me ocurre una manera eficiente de interrumpir y bloquear al proceso. En lo único que pensé que podría llegar a funcionar, es estar verificando cada vez que se ejecuta una instrucción (de las que consumen CPU para el contexto del TP) el valor de un contador que se vaya incrementando, y comparando continuamente con el resto de los procesos en la cola Ready. Pero me parece poco eficiente el hecho de estar continuamente en cada instrucción incrementando y verificando el valor de ese contador.

¿Alguna sugerencia? 
Gracias y saludos

**Comment by ncoen97** [comment]
Buenas!
El SJF con desalojo es un algoritmo que tiene más overhead que otros y no se si hay mucho que hacer al respecto por el hecho de vas a tener que estar evaluando si alguien tiene mas prioridad que el proceso que está en excec. Lo único que te puedo recomendar que tengas en cuenta es que si el entrenador A es el seleccionado para ejecutar (ya que tiene menos ráfaga que el B y el C), vos ya sabes que entre el A, B y C siempre el A va a ser el que tenga mas prioridad. Por lo tanto vas a tener que hacer la comparación de ráfagas solo en el caso de que entre un nuevo entrenador a ready.
Suerte!

**Comment by Charlyd96** [comment]
Gracias, ya con esa sugerencia me acotaste bastante el rango de comparación!

Saludos
