### ISSUE TITLE
[Gamecard] Duda con los Archivos Pokemon

### ISSUE THREAD

**Issue by santisanchez0** [sisoputnfrba/foro#1735]
Buenas noches, estoy con una duda respecto a la estructura de los archivos del gamecard.

1-¿_Estas partes se están contradiciendo_? Porque en la foto A mencionan al pokemon Pikachu como un directorio que tiene adentro su correspondiente archivo Metadata, y en la foto B hace referencia a Pikachu (En realidad seria el tipo de pokemon) como un archivo (incluso el titulo se llama archivos pokemon, no directorios pokemon) _¿Un pokemon entonces seria un archivo o un directorio?_

2- En la foto A muestra al directorio Files que adentro tiene a los pokemones y mas adelante en el enunciado (foto C, en la parte de la implementacion de New Pokemon) habla de buscar al pokemon en el directorio Pokemon. ¿_Este directorio Pokemon y Files, son los mismos_?. Si no son los mismos ¿_Donde estaria ubicado el directorio Pokemon_?

**FOTO A:**
![image](https://user-images.githubusercontent.com/48868506/83956938-79e6ea00-a839-11ea-888d-fb61e9a477f4.png)

**FOTO B:**
![image](https://user-images.githubusercontent.com/48868506/83956924-5459e080-a839-11ea-9c2d-2faf12b43c99.png)

**FOTO C:**
![image](https://user-images.githubusercontent.com/48868506/83957033-62f4c780-a83a-11ea-9c16-0927bf132ad4.png)

**Comment by lglu92** [comment]
Buenas noches 👋 , yo hice una consulta parecida, y la idea sería la siguiente:
En Game Card:
- el directorio /Files sólo posee el metadata.bin de cada archivo o directorio.
- el directorio /Blocks sólo tienen los archivos 1.bin, 2.bin, 3.bin (uno por cada bloque).
Entonces no existe un archivo picachu.txt, eevee.txt, charmander.txt
Existen solamente los archivos 1.bin , 2.bin , 3.bin y cada uno de ellos guarda la pox-posy=cantidad hasta donde su tamaño lo permita.
Por lo tanto, si me llega un mensaje de la cola NEW_POKEMON  con el nombre del pikachu (y todos los datos que me indica el enunciado), se buscaría en el directorio /Files un archivo con dicho nombre y así podría acceder a metadata.bin del pokemon (si es que existe) , y seguir el recorrido de los bloques. Con recorrido de los bloques me imagino a que si tiene  Blocks= [40,21,82], en el metadata.bin , significa que se debe acceder a 40.bin , 21.bin y 82.bin del directorio /Blocks para obtener los datos. 

Ojala sirva! Saludos!

**Comment by santisanchez0** [comment]
Excelente, muchas gracias!
