### ISSUE TITLE
[Team] [Planificación] Duda prioridad

### ISSUE THREAD

**Issue by matiasanz** [sisoputnfrba/foro#1736]
Buenas,
Quería consultar en caso de que no tuviera pokemones en mapa y me llegara un mensaje CAUGHT confirmado, pero por criterio le corresponda ejecutar a un entrenador que quiere ir a buscar un pokemon (que quedó despierto por un mensaje APPEARED anterior); debería aceptar el overhead hasta que llegue otro pokemon o habría algún tipo de prioridad para el que tiene que capturar?

Gracias, saludos

**Comment by iago64** [comment]
Buenas!

Como podria quedarte un entrenador despierto si no tenes nada en el mapa?

No te olvides que vos vas a empezar a mover entrenadores cuando tengas pokemones en el mapa que forman parte de tus objetivos y no tendrías motivo para despertar a un entrenador si no tiene algo que ir a atrapar.
Si lo despertaste por un APPEARED entonces significa que va a ir hasta esa posición y va a buscar de capturar algo ahi.

Saludos.-

**Comment by matiasanz** [comment]
Hola! Gracias por responder
Yo tenía entendido que cuando llegaba un pokemon había despertar (pasar a ready) a todos los entrenadores que estuvieran a la espera de uno y ejecutar solamente al que estuviera mas cerca. Ahora que lo pienso, no tiene mucho sentido que los demás queden colgados. ¿La idea sería solamente pasar a ready al entrenador que está mas cerca?

**Comment by iago64** [comment]
Buenas!

No, justamente uds van a ir despertando a medida que necesiten capturar, de ahi a que pueda darse que les tiremos varios APPEARED a proposito para que tengan que despertar a mas de 1 es un tema meramente de las pruebas 😉 

Saludos.-

**Comment by matiasanz** [comment]
Listo, muchísimas gracias!!
