### ISSUE TITLE
Socket cambia el comportamiento al usar log_info

### ISSUE THREAD

**Issue by Kvothe838** [sisoputnfrba/foro#1737]
Desde el Broker, obtengo la configuración y llamo a iniciar_servidor que está definido de la siguiente manera:

```
void iniciar_servidor(char *ip, char* puerto){
	int socket_servidor;

    struct addrinfo hints, *servinfo, *p;

    memset(&hints, 0, sizeof(hints));
    hints.ai_family = AF_UNSPEC;
    hints.ai_socktype = SOCK_STREAM;
    hints.ai_flags = AI_PASSIVE;

    getaddrinfo(ip, puerto, &hints, &servinfo);

    for (p=servinfo; p != NULL; p = p->ai_next)
    {
        if ((socket_servidor = socket(p->ai_family, p->ai_socktype, p->ai_protocol)) == -1)
            continue;

        if (bind(socket_servidor, p->ai_addr, p->ai_addrlen) == -1) {
            close(socket_servidor);
            continue;
        }
        break;
    }

	listen(socket_servidor, SOMAXCONN);

    freeaddrinfo(servinfo);

    while(1){
    	log_info(logger, "Socket servidor: %d", socket_servidor);
    	esperarCliente(socket_servidor);
    }

}
```

esperarCliente está definida como:

```
void esperarCliente(int socket_servidor)
{
	struct sockaddr_in dir_cliente;
	socklen_t tam_direccion;
	int socket_cliente;

	tam_direccion = sizeof(struct sockaddr_in);
	socket_cliente = accept(socket_servidor, (void*)&dir_cliente, &tam_direccion);

        log_info(logger, "Nuevo cliente: %d", socket_cliente);

	pthread_create(&thread,NULL,(void*)serveClient,&socket_cliente);
	pthread_detach(thread);
}
```

Y serveClient está definido como:

```
void serveClient(int* socketCliente){
	int cod_op;

	if(recv(*socketCliente, &cod_op, sizeof(int), MSG_WAITALL) == -1){
		log_info(logger, "RECIBÍ MAL EL COD_OP");
		cod_op = -1;
	} else {
		log_info(logger, "RECIBÍ BIEN EL COD_OP: %d", cod_op);
	}

	processRequest(cod_op, *socketCliente);
}
```

Finalmente, processRequest es así:

```
void processRequest(int codOp, int socketCliente){
	log_info(logger, "Llegó algo. Cliente: %d", socketCliente);
	log_info(logger, "COD OP: %d", codOp);
	int size;
	void* msg;

	switch (codOp) {
		case SUSCRIBER:
			log_info(logger, "Llegó un Suscriber");
			msg = recibirMensajeServidor(socketCliente, &size);
			log_info(logger, "Payload: %d", size);
			manejarSuscriptor(msg, socketCliente);

			break;
		case PUBLISHER:
			log_info(logger, "Llegó un Publisher");
			msg = recibirMensajeServidor(socketCliente, &size);
			log_info(logger, "Payload: %d", size, socketCliente);
			manejarPublisher(msg, socketCliente);

			break;
		case ACK:
			log_info(logger, "Llegó un ACK");
			msg = recibirMensajeServidor(socketCliente, &size);
			log_info(logger, "Payload: %d", size);
			manejarACK(msg, socketCliente);

			break;
		case 0:
			pthread_exit(NULL);
		case -1:
			pthread_exit(NULL);
	}
}
```

El tema acá es que desde GameCard envío una suscripción a Broker, y si le comento el log_info dentro del while de iniciar_servidor, todo funciona joya:

![image](https://user-images.githubusercontent.com/35804584/83974644-5073a000-a8c5-11ea-989a-057e862df295.png)

Ahora bien, si descomento ese log_info, sucede lo siguiente:

![image](https://user-images.githubusercontent.com/35804584/83974677-7e58e480-a8c5-11ea-9be9-888adb7d621a.png)

Es como que haciendo ese log termina cambiando el comportamiento del socket de manera tal que el primer cliente que llega nunca ejecuta su serveClient y de una forma mística se dispara un segundo cliente con un id random que genera un error en el recv.

Del lado de GameCard, no subo el código porque me parece medio al pe, pero hace un sólo send con el cod_op como el primer elemento. 

¿Por qué puede estar pasando esto?¿es error de la implementación del log_info o estaré olvidandome de setear algo o llamar a alguna función?

**Comment by Kvothe838** [comment]
@iago64

**Comment by mgarciaisaia** [comment]
¡Aloha!

¿Probaste ejecutar el broker con [`valgrind`](https://faq.utnso.com.ar/valgrind)? No veo nada _raro_ en esa llamada a `log_info`, y esa función no debería modificar mucho nada (no escribe en las variables que le pasás por parámetro).

Así que probablemente haya algún problema de memoria que moleste. Si estás usando memoria que no es tuya, quizá cuando `log_info` reserva memoria para preparar los strings que tiene que imprimir lo hace sobre una porción que el sistema operativo le asigna, pero que coincide con memoria que vos estabas usando sin reservar. Y entonces cuando sigue la ejecución, buen, te pisaron valores de memoria, porque nunca le habías pedido al SO que ese pedacito de memoria lo querías para otra cosa.

**Comment by iago64** [comment]
Sumado a lo que dice Mati, una prueba rápida para ver que es lo que esta pasando es que hagas un printf tal cual lo que esta haciendo el logger como para validar si el comportamiento es el mismo.

Saludos.-

**Comment by iago64** [comment]
@Kvothe838 pudiste resolver el problema? encontraste algo con valgrind?

**Comment by karengrams** [comment]
¡Cierro el issue por inactividad! Cualquier cosa, no duden en re-abrirlo.
