### ISSUE TITLE
Git status problem

### ISSUE THREAD

**Issue by victoriaguillosson** [sisoputnfrba/foro#1738]
Hola a todos!
Estoy tratando de actualizar el proyecto en git pero me tira el siguiente error:
![Captura](https://user-images.githubusercontent.com/48684404/83980355-62683980-a8eb-11ea-847c-0de0ab7a2599.PNG)

Nunca me pasó la verdad.. si alguno sabe que puede ser me daría una mano?
Gracias y saludos!

**Comment by mgarciaisaia** [comment]
Uy, qué error más raro. Bajón, che =/

Parece que se te apagó la VM mientras estabas haciendo operaciones de git o algo así. Y quedaron archivos corruptos.

¿Tenías mucho laburo sin pushear? Te recomiendo hacer una copia de las carpetas de los proyectos que tenés en el repo (es decir, si tu repo lo clonaste en `/home/utnso/tp`, copiate las carpetas `/home/utnso/tp/broker` y sus hermanas a otro lado) para tener de """"backup"""". Y si te acordás en qué archivos estabas laburando y no llegaste a commitear/pushear, mejor aún.

Después, desde la consola, parada en el directorio del repo, ejecutá [estos tres comandos](https://stackoverflow.com/a/31110176):

```
find .git/objects/ -type f -empty | xargs rm
git fetch -p
git fsck --full
```

Eso va a empezar por borrar todos los objetos estos que están "corruptos", después va a volver a bajarlos del repo remoto, y por último va a tratar de chequear que hayan quedado en orden todos los objetos del repo.

Si todo funciona, nada - ganaste.

Si el último paso falla, probablemente sea más fácil volver a clonar el repo, y pegarle encima los archivos que backupeaste, para no perder el laburo que habías hecho.

-----

Además, también vale que _antes de empezar_ a probar estas cosas, hagas un zip con todo el directorio del repo y me lo mandes por privado para examinar mejor qué se rompió y si había cosas perdibles y blah. Pero con lo anterior deberías estar bien.

**Comment by victoriaguillosson** [comment]
Bueno hice un "backup" de los archivos en dónde estaba trabajando -por las dudas- y ejecuté los 3 comandos que se explicitaron mas arriba y me solucionaron el problema!
Asi que muchas gracias :)

pd: cierro el issue
