### ISSUE TITLE
[Gamecard] Size y tamaño de bloques

### ISSUE THREAD

**Issue by olsztajn** [sisoputnfrba/foro#1739]
En el caso del tamaño de los bloques, en el ejemplo tenemos que el SIZE=250 y tenemos 4 bloques. Debería ser 4*64= 256 o lo estamos pensando mal?
Los 64 bits salen de la página 17.
El ejemplo dado en el enunciado es el siguiente:

Ej Archivo: 
DIRECTORY=N
	SIZE=250 
	BLOCKS=[40,21,82,3]
	OPEN=Y

**Comment by iago64** [comment]
Buenas buenas!

Efectivamente, si el size de tu archivo dice 250, vas a estar ocupando 4 bloques de los cuales en el ultimo vas a tener un segmento sin utilizar de 6 bytes 

Saludos.-

**Comment by karengrams** [comment]
¡Alo!

¿Quedo clara la duda? ¿Podemos cerrar el issue?

Saludos :)

**Comment by olsztajn** [comment]
Quedó clara. Gracias!
