### ISSUE TITLE
Broker - Duda sobre tamaño minimo de particion

### ISSUE THREAD

**Issue by MartinezAlexander** [sisoputnfrba/foro#1740]
Buenas!
Tenia un consulta con respecto sobre el campo TAMANO_MINIMO_PARTICION del archivo de configuración del broker, hay que usarlo siempre? Porque en particiones dinámicas la idea es darle una partición del tamaño exacto que necesita no darle de mas.
Por ejemplo si me llega un mensaje que tiene un tamaño menor al tamaño mínimo indicado en el config que debería hacer? Porque si sigo la teoría le debería dar el tamaño exacto que necesita, pero si me baso en ese dato que me da el config le debería dar el tamaño mínimo de partición aunque no necesite todo ese espacio, generando una fragmentacion interna que nunca podría utilizar hasta que se elimine esa partición.
Saludos.

**Comment by plbruniard** [comment]
En caso de usar el tamaño_minimo_particion en la implementación de memoria dinámica, impactaría en el volumen de la tabla de particiones. Ya que el mensaje mínimo es caught_pokemon de cuatro bytes y habria que dimensionar la tabla como memoria_maxima / 4 en lugar de memoria_maxima/tamaño_minimo_particion para que se pudiesen guardar exactamente la cantidad de bytes del mensaje.

**Comment by iago64** [comment]
Buenas buenas!

La idea del tamaño mínimo de partición es para que lo tengan en cuenta en ambos algoritmos, tanto en buddy system como en particiones dinámicas, ya que esto nos sirve para estandarizar las pruebas aun mas y por ejemplo asegurarnos exactamente que mensaje se tiene que ir y que mensaje no a la hora de ejecutar los algoritmos.
Difiere un poco de la teoría? Si, como también difiere que cuando los teams terminan no devuelven los recursos, pero son algunas "licencias poéticas" que tenemos que tomarnos de la teoría para que el TP sea realizable y no se vuelvan locos a la hora de implementarlo.

Por ultimo, el tamaño mínimo de partición tengan en cuenta que puede ser 1 y ahí medio que van a tener ambos algoritmos en su estado mas puro 😉 

Saludos.-

**Comment by MartinezAlexander** [comment]
Genial, con respecto a eso que ustedes con eso se aseguran que mensaje se tiene que ir, significa que van a saber que tamaño tiene cada mensaje entonces ese tamaño va a ser el que se indica en el anexo de mensajes en memoria y además le debo sumar el tamaño de los ids que posea? 
Básicamente sería que guardar en la caché y que no.

**Comment by ncoen97** [comment]
En la caché solo se guarda la información detallada en el anexo mensajes en memoria.
Saludos!

**Comment by MartinezAlexander** [comment]
Dale muchas gracias!

**Comment by foviedo** [comment]
> Buenas buenas!
> 
> La idea del tamaño mínimo de partición es para que lo tengan en cuenta en ambos algoritmos, tanto en buddy system como en particiones dinámicas, ya que esto nos sirve para estandarizar las pruebas aun mas y por ejemplo asegurarnos exactamente que mensaje se tiene que ir y que mensaje no a la hora de ejecutar los algoritmos.
> Difiere un poco de la teoría? Si, como también difiere que cuando los teams terminan no devuelven los recursos, pero son algunas "licencias poéticas" que tenemos que tomarnos de la teoría para que el TP sea realizable y no se vuelvan locos a la hora de implementarlo.
> 
> Por ultimo, el tamaño mínimo de partición tengan en cuenta que puede ser 1 y ahí medio que van a tener ambos algoritmos en su estado mas puro 
> 
> Saludos.-

Consulta, cómo enfrentamos el tema de tener un tamaño mínimo en lo de particiones dinámicas? Si tengo de tamaño mínimo 15 bytes (por ejemplo) y me llega un mensaje de 10 bytes, hago que entre en el de 15 bytes y que aparezca como que está ocupando todo?

**Comment by plbruniard** [comment]
> > Buenas buenas!
> > La idea del tamaño mínimo de partición es para que lo tengan en cuenta en ambos algoritmos, tanto en buddy system como en particiones dinámicas, ya que esto nos sirve para estandarizar las pruebas aun mas y por ejemplo asegurarnos exactamente que mensaje se tiene que ir y que mensaje no a la hora de ejecutar los algoritmos.
> > Difiere un poco de la teoría? Si, como también difiere que cuando los teams terminan no devuelven los recursos, pero son algunas "licencias poéticas" que tenemos que tomarnos de la teoría para que el TP sea realizable y no se vuelvan locos a la hora de implementarlo.
> > Por ultimo, el tamaño mínimo de partición tengan en cuenta que puede ser 1 y ahí medio que van a tener ambos algoritmos en su estado mas puro
> > Saludos.-
> 
> Consulta, cómo enfrentamos el tema de tener un tamaño mínimo en lo de particiones dinámicas? Si tengo de tamaño mínimo 15 bytes (por ejemplo) y me llega un mensaje de 10 bytes, hago que entre en el de 15 bytes y que aparezca como que está ocupando todo?

Si el mensaje es de 10 bytes y el tamaño minimo de particion es 15 vas a tener fragmentación interna.
La particion va a tener 15 de largo y esa cantidad de memoria va a estar alojada por la misma pero, el mensaje tomará solo los diez primeros bytes para guardar su información.  Hay cinco bytes de almacenamiento desperdiciados. Esa fragmentación es inevitable a menos que no haya mensajes de menor tamaño que la partición mínima. 

Hay que manejar dos largos distintos: largoParticion = finParticion - inicioParticion + 1   y  largoMensaje que será menor o igual a largoParticion.

Hay que evitar propagar la basura final que no pertenecerá al mensaje.

**Comment by iago64** [comment]
@foviedo efectivamente vas a tener fragmentación y no te preocupes, es la idea y es una linda pregunta de coloquio ;)

Saludos.-

**Comment by RodrigoLista** [comment]
Hola. Una consulta. El tamaño minimo de particion, lo van a indicar ustedes cuando hagamos las pruebas o el valor lo indicamos nosotros? 

Porque si es esta ultima opcion, como dijeron anteriormente, ponemos como valor minimo 4 bytes,y no tendrias que preocuparnos de esta implementacion en las particione dinamicas, y solo necesitariamos conocer el inicio del bloque y el tamaño del mensaje.

 En cambio, si el valor de tamaño minimo lo determinan siempre ustedes, si o si, tendriamos que contemplar esta situacion en memoria dinamica, y por ende, para poder administrarla, no solo tendriamos que conocer el inicio del bloque y el tamaño de mensaje, sino tambien el fin del bloque o tamaño del bloque, como tambien mencionaron anteriormente.

Saludos.

**Comment by ncoen97** [comment]
Buenas. 
El tamaño mínimo de partición es uno de los valores que viene por archivo de configuración del Broker, por lo tanto va a estar definido por nosotros y en cada test puede tener valores distintos.
Saludos!

**Comment by MartinezAlexander** [comment]
Muchas gracias por las respuestas, ya nos quedó más claro, cierro el issue, saludos!
