### ISSUE TITLE
Kill no manda SIGUSR1

### ISSUE THREAD

**Issue by EzeDiaz** [sisoputnfrba/foro#1741]
Hola! Atentos al requerimiento del archivo de dump, estuvimos jugando con el tema de las señales. Por lo que entendimos, necesito un `signal(SIGUSR1, controlador_de_seniales);` para "cachear" la señal. Luego, la implementación de `controlador_de_seniales` será la encargada de, en este caso, escribir el archivo de dump (dejo la implementación más abajo). El asunto es que si bien yo puedo hacer que esa función se dispare a través de un `raise(SIGUSR1)`, no logro hacerlo mediante un `kill -SIGUSR1 [pid]` por consola. Probé las otras variantes de escribir el comando, como por ejemplo poner el número de la señal en lugar del nombre y tampoco hay caso.

El `controlador_de_seniales` lo probé tirando `raise` y funciona con lo cual no es que rompa la función. Lo único que se me ocurre es que como `controlador_de_seniales` llama a otra función (revisar implementación), quizás eso no es legal cuando la señal que se recibe es un kill. Es una hipótesis que pensé pero igual me parecería raro.

Gracias!

## Implementación `controlador_de_seniales`
La mayoría del código no lo puse porque me parece que no aporta nada, si hubiese algo que fuera interesante revisar, lo agrego.
```
char* dos_cifras_maker(int num) {
	...
}

char* fecha_actual(){
	...
}

void dump_cache(){
	FILE* archivo_dump;
	char* fecha_y_hora_dump = fecha_actual();

	archivo_dump = fopen("archivo_dump.txt", "a");

        ...
	fclose(archivo_dump);
}

void controlador_de_seniales(int num_senial){
	if(num_senial == SIGUSR1){
		dump_cache();
	}
}
```

**Comment by mgarciaisaia** [comment]
Se me ocurren dos cosas:

1) chequear que el PID al que estás enviando la señal con `kill` sea el correcto.
2) que chequees que el `signal` se ejecuta (el registro del handler, digo), y que metas algún `printf` o breakpoint en el manejador para chequear si se está ejecutando o no. Si esto no da info nueva, compartí esos pedacitos de código.

La otra es ver bien en los logs de compilación, por si hay algo que esté fallando (estoy pensando en alguna constante que esté mal definida o algún galerazo así, pero sólo como "tiremos fruta por si algo pica").

**Comment by EzeDiaz** [comment]
Quirúrgico! Efectivamente estaba tomando el PID incorrecto (el que me muestra htop es del Eclipse, no del proceso que puse a correr. Entonces mataba al Eclipse entero). Hice un `getpid()` de entrada para saberlo y listo. Gracias!
