### ISSUE TITLE
[BROKER] Duda informacion almacenada en cache

### ISSUE THREAD

**Issue by MaSosa314** [sisoputnfrba/foro#1743]
Tengo una duda con respecto a que informacion se almacena en la cache del BROKER. En un principio, nos habian dicho que lo unico que se guardaba en cache era el contenido del mensaje en si. Pero leyendo un poco el enunciado, esta esto:

![imagen](https://user-images.githubusercontent.com/48865731/84178621-16d49d80-aa5b-11ea-9c8e-9e4b580e963c.png)

Da a entender que esa informacion tambien debe estar almacenada en cache. Mi duda es si esa informacion tambien la tendriamos que almacenar con el mensaje. En caso de ser asi, cuando un suscriptor devuelve el ACK, ¿Habria que actualizar la informacion en cache de ese mensaje?

Saludos.

**Comment by karengrams** [comment]
¡Buenas!

¿Como va? Espero que bien. Primero, antes que nada, respecto a que se debe almacenar en la cache se hablo un poco en el issue #1657. 

Segundo, la respuesta es no,  todo lo que se guarda en la cache esta en el Anexo II del [enunciado](https://docs.google.com/document/d/1be91Gn93O2Vp8frZoV1i5CmtOG0scE1PS8dMHsCP314/edit?usp=drive_web&ouid=118277960966911101529). Para el manejo de la información que se habla en la parte que citaste, se debe tener estructuras administrativas. Una vez dicho esto, respondiendo a tu pregunta:

>  ¿Habría que actualizar la información en cache de ese mensaje?

Cada vez que recibas un ACK de un mensaje, no vas a actualizar la información que se encuentra en la cache, sino que la estructura administrativa.

¡Saludos!

**Comment by MaSosa314** [comment]
Buenisimo, muchas gracias por responder. Cierro el issue.
