### ISSUE TITLE
Duda con el tad list de las commons

### ISSUE THREAD

**Issue by MarcosInfantino** [sisoputnfrba/foro#1744]
Hola! Revisando el código me surgió la siguiente duda: cuando yo hago un lista_add(lista, punteroAElemento), dentro de la lista se agrega exactamente el puntero que yo le paso? o se hace una copia de los datos contenidos en el mismo a otro puntero y luego se lo agrega? La duda viene por el lado de que me da miedo que si le hago free a un puntero que recien añadi a la lista me corrompa la lista.

**Comment by mgarciaisaia** [comment]
¿Cómo podrías averiguarlo?

**Comment by MarcosInfantino** [comment]
Hola! Obviamente antes de venir a preguntar por aca me meti al log.c de las commons, pero como no termine de entender el código del todo pregunté por acá para ver si alguien me podía despejar la duda. Gracias y saludos!

**Comment by MarcosInfantino** [comment]
Buenisimo! Estuve revisando las commons y además hice pruebas como me dijeron y pude llegar a una conclusión. Gracias y saludos!
