### ISSUE TITLE
Reconexión de subscriptores en el Broker.

### ISSUE THREAD

**Issue by gebonora** [sisoputnfrba/foro#1746]
Buenas! Estuve viendo el foro y me gustaría ampliar sobre el issue #1728, ya que la duda inicial es la misma.

En el caso de que se cae un subscriptor de Broker.

1) Para el caso de un Team que se cae y levanta de nuevo, el Broker tiene que mandarle los mensajes "pendientes" (en la explicación del issue 1728 quedó claro). Ahora, no se nos ocurre cómo identificar al Team dentro de Broker, pensamos en usar el socket, pero si se cae la conexión el socket va a ser otro. Podría ir la ID del team en el config? Porque de alguna forma el Team tiene que identificarse ante el Broker, o sea que el Team debería saber su propia ID?

2) Para el caso de un Gamecard que se cae y levanta de nuevo, el Broker también tiene que mandarle los pendientes? En este caso también haría falta una ID para el Gamecard?

Gracias!

Saludos!

**Comment by karengrams** [comment]
¡Buenas!

¿Como va? Espero que bien 😸 

> 1. Para el caso de un Team que se cae y levanta de nuevo, el Broker tiene que mandarle los mensajes "pendientes" (en la explicación del issue 1728 quedó claro). Ahora, no se nos ocurre cómo identificar al Team dentro de Broker, pensamos en usar el socket, pero si se cae la conexión el socket va a ser otro. Podría ir la ID del team en el config? Porque de alguna forma el Team tiene que identificarse ante el Broker, o sea que el Team debería saber su propia ID?

Si, el ID lo pueden poner en el archivo config del Team, de esa manera lo van a poder identificar, y al tenerlo en su config, el Team sabe tu propio ID.

> 2. Para el caso de un Gamecard que se cae y levanta de nuevo, el Broker también tiene que mandarle los pendientes? En este caso también haría falta una ID para el Gamecard?

Exacto, fijate que dicho requerimiento es para los suscriptores globales, siendo el Game Card y el Team, los dos subscriptores globales.

Cualquier cosita que no quedo clara, no dudes en preguntar.

¡Saludos!

**Comment by gebonora** [comment]
Buenísimo! Le agregamos ese parámetro al config de ambos módulos entonces.

Gracias! Cierro el issue.
