### ISSUE TITLE
Duda sobre bloqueo de entrenadores y "uso de la CPU" ficticia del TP

### ISSUE THREAD

**Issue by Charlyd96** [sisoputnfrba/foro#1748]
Buenas! Tengo una duda con respecto al Team, precisamente al instante en el cual se debe bloquear al entrenador. Hay varias formas de resolverlo, pero mi duda es si hay alguna restricción a nivel cátedra con la duda que planteo. 

Para el contexto del TP, las acciones que consumen ciclos de CPU y que deberían ejecutarse en estado EXEC son: cada desplazamiento del entrenador, cada vez que se efectúe un intercambio por deadlocks, y cada vez que se envíe un mensaje al Broker (entiendo que sólo los mensajes tipo CATCH que pueden ejecutar los entrenadores, por favor aclarar eso si pueden también).

Ahora bien, la duda es qué tan estricto y qué tanto a la realidad hay que asemejar esta situación en el TP. Por ejemplo, un entrenador llega al pokemon objetivo, y tiene que ejecutar un CATCH. Si uno lo llevara a la realidad absoluta, ese hilo está haciendo una syscall bloqueante, por lo tanto, inmediatamente sale de EXEC y la CPU pasa a ejecutar a otro entrenador. Pero en este contexto del TP, ¿es necesario bloquear el hilo al instante? O es suficiente con cambiarle su flag de estado a “bloqueado” y utilizar ese mismo hilo del entrenador para enviar el mensaje, esperar el ID, y con ese ID ir a esperar un CAUGHT con el correlativo correspondiente? Y por supuesto asegurarse de que no vuelva a desplazarse (usar la CPU). Obviamente mientras sucede todo esto, ya debería haber otro entrenador ejecutando en la CPU.

En resumen, la consulta precisa es si el hilo de cada entrenador debe bloquearse necesariamente después de mandar un CATCH, o puede seguir ejecutando operaciones como esperar el ID del broker, enviarlo a alguna otra estructura para buscar un mensaje CAUGHT asociado, etc, todas estas, operaciones que para el contexto del TP no utilizan ciclos de CPU.

Espero haber sido claro, gracias y saludos!

**Comment by iago64** [comment]
Aloha!
Tranqui, no hace falta que te apegues taaanto a la teoría.
Dicho esto, es importante tengas en cuenta que una vez que el hilo entrenador:

1. Cree la conexión 
2. Envíe el catch
3. Reciba el ID 
4. Cierre la conexión

Se bloquee para no estar en una espera activa (ya que eso si esta mal)

Saludos.-

**Comment by Charlyd96** [comment]
Gracias!
