### ISSUE TITLE
¿Filtrado de mensajes LOCALIZED por ID correlativo o por especie de pokemon?

### ISSUE THREAD

**Issue by Charlyd96** [sisoputnfrba/foro#1749]
Buenas!
En el Issue #1719 se dice que los mensajes LOCALIZED que recibe el Team, deben ser filtrados por el ID correlativo generado por los GETs enviados previamente.
Sin embargo el enunciado dice en la página 26: 

_Localized Pokémon 
El proceso Team se suscribirá de manera global a esta cola de mensajes. Al recibir uno de los mismos deberá realizar los siguientes pasos:
Verificar si ya recibió en algún momento un mensaje de la especie del Pokémon asociado al mensaje. Si es así, descarta el mensaje (ya sea Appeared o Localized)._

Sólamente habla de la especie, nunca menciona que deberá verificar según ID correlativo. Por otro lado, en el video de planificación subido al canal de la cátedra, del minuto 09:00 al 10:30 se explica el procedimiento al recibir los LOCALIZED, y parecería que tampoco se tiene en cuenta el ID correlativo, y esto es distinto a lo que se menciona en el issue antes citado.

¿Cuál sería la operatoria entonces para filtrar los mensajes LOCALIZED? 

Gracias y saludos

**Comment by Charlyd96** [comment]
Gracias!

**Comment by alanzhag** [comment]
> Si es respuesta a un GET que hiciste, recien ahí recién te fijas si no te llego un appeared antes para esa especie (Ya que puede ser que ni bien levantes el Team te lleguen varios appeared cacheados en el broker

No me quedó claro el racional atrás de filtrar localized repetidos que tengan mi ID correlativo. 
Si ya recibi el localized de una especie, ¿Voy a seguir queriendo procesar más _LOCALIZED_ de esa especie hasta que termine el proceso? ¿Es por única vez al levantar Team? 
En caso contrario, ¿Cómo sé cuándo volver a procesar los _LOCALIZED_ de la misma especie?

**Comment by Charlyd96** [comment]
> No me quedó claro el racional atrás de filtrar localized repetidos que tengan mi ID correlativo.
> Si ya recibi el localized de una especie, ¿Voy a seguir queriendo procesar más _LOCALIZED_ de esa especie hasta que termine el proceso? ¿Es por única vez al levantar Team?
> En caso contrario, ¿Cómo sé cuándo volver a procesar los _LOCALIZED_ de la misma especie?

Entiendo que el hecho de recibir los LOCALIZED se realiza sólo una vez, después de enviar tus mensajes GET. No deberías poder procesas más de un LOCALIZED por especie dirigido al proceso (con tu ID correlativo) ya que tampoco nunca deberías haber mandado más de un GET de la misma especie.

La duda que tengo ahora es que el mensaje LOCALIZED puede traer información sobre más de un pokemon, o sea te trae todos los pokemones de esa especie que están en el mapa global. Sin embargo el APPEARED sólo trae información de un solo pokemon. Entonces, si ya recibí un APPEARED cacheado en Broker apenas levanto el Team, y descarto el LOCALIZED que me va a llegar luego de los GET que se envían al principio, ¿no estaría perdiendo información sobre esos pokemones que venían en en LOCALIZED que descarté? @iago64

**Comment by iago64** [comment]
Buenas!
Vamos en orden:
@alanzhag Repetidos no vas a tener (o no deberías tenerlos si el broker implemento todo correctamente) con lo cual la idea de filtrar por el id correlativo es que no proceses mensajes que como estas suscrito a la queue de LOCALIZED te van a llegar los LOCALIZED de tu team y los del resto de los teams, entonces ahí filtras por ID :)
P.D> En estos casos donde alguna cosa no quede del todo clara, por favor no comenten sobre los issues cerrados, creen uno nuevo y referencien el issue donde estuvo la duda porque al quedar cerrado puede que no lo veamos.

@Charlyd96 Si, vas a perder info... y bueno, que le vamos a hacer, el team dependera de que le llegue APPEARED para completar su objetivo (y si, eso es a proposito para forzar algunas situaciones)

Saludos.-

**Comment by miguel-t** [comment]
Buenas,
Quedo claro que cuando  llegue mensajes la queue de **LOCALIZED** se debe filtrar por id correlativo.

Me surge una duda relacionado con los  mensaje en este cola , suponiedo que el id correlativo es de un  **GET** que envie al inicar el proceso team y no me llego nada en cola cola **APPEARED**
Si mi  objetivo global es **PIKACHU** : 1(cantidad que necesito )
y me llegua un  mensaje LOCALIZED PIKACHU 1 2  3  4 .

Dejo ingresar al mapa de team , solo una instancia => **LOCALIZED PIKACHU** 1 2?
o ingresan al mapa dos instancias **LOCALIZED PIKACHU** 1 2  3  4  ?  
 
Saludos.

**Comment by iago64** [comment]
@miguel-t Guardas todas las instancias, ya que eventualmente en 1-2 puede que cuando llegues ya lo haya atrapado otro entrenador y bueno... te toque ir a buscarlo a la otra posicion :)

Saludos.-

**Comment by karengrams** [comment]
¡Buenas!

¿Quedaron todas las dudas resueltas? ¿Podemos cerrar el issue?

¡Saludos!

**Comment by Charlyd96** [comment]
Todo claro! Gracias!
