### ISSUE TITLE
Duda funciones bitarray

### ISSUE THREAD

**Issue by guidoenr4** [sisoputnfrba/foro#1752]
Tengo una duda con la funcion para crear un bitarray de las commons, entiendo que este array de bits es usado para identificar el uso de mis bloques de mi filesystem.

![imagen](https://user-images.githubusercontent.com/47611900/84305476-82d50580-ab30-11ea-883c-543901d25290.png)

Yo la uso de esta manera, dividiendo la cantidad de blocks que hay en el metadata de mi filesystem por 8, para que me de el tamaño real y poder iniciarlo.

```
int blocks = fileSystemMetadata.blocks;
int bitarraySize = blocks/8; //porque es en bits, no bytes 5192/8 = 649.
					// el array quedaria de 5192 posiciones , pero de tamaño 649

t_bitarray* bitarray = bitarray_create_with_mode(bitarray, bitarraySize , LSB_FIRST);

```
La uso exactamente como en el ejemplo de las commons, pero cuando quiero ver el contenido del bitarray, me dice cualquier cosa:

![imagen](https://user-images.githubusercontent.com/47611900/84305736-eeb76e00-ab30-11ea-9f0a-2697833beb64.png)

**_(el size esta bien , porque probe con un metadata de 10blocks para no hacer 5192 syscalls al crearlos)_**

pero el puntero me apunta al directorio donde estoy parado actualmente, y el `*char` me da el primer valor de ese directorio `'/'` . 

no estoy entendiendo como es su uso entonces, yo pense que esto me iba a devolver un array del tipo 

`bitarray = [0,0,0,0,0,0,0,0,0,0,0...n]` siendo  _**n**_ los blocks de mi filesystem y todos en 0 porque al incializarlos no estan en uso, y que yo vaya actualizando eso (en un` Bitmap.bin`) a medida que voy trabajando.

**Comment by guidoenr4** [comment]
Genial, gracias a ambos.. ya lo pude hacer andar, pero tengo una duda.. porque es necesario grabar este bitarray a un Bitmap.bin? no seria mas facil manejarlo sin subirlo?

**Comment by MatiCoarasa** [comment]
Imagino que es porque podes tener varios modulos de Gamecard ejecutando a la vez

**Comment by guidoenr4** [comment]
De eso dude en un principio, pero el filesystem no es uno solo? de que me serviria tener otro mapa de pokemons mas cuando puedo usar el mismo?

**Comment by mgarciaisaia** [comment]
> porque si solamente es un puntero y el array lo debo crear yo, para que esta la funcion? podria yo mismo crear un `array[metadata.blocks/8]` y manejarlo yo mismo en la funcion, accediendo al mismo como `array[pos]`. El puntero ese no me serviria de nada

Creo que esta es la pregunta más jugosa. Es que, claro: en todos los otros TADs de las commons, las funciones se encargan de reservar su propia memoria.

El tema es que el TAD este lo creamos pensando en poder aplicarlo en distintas zonas de memoria. En particular, las creamos para un TP en que había un FS que incluía un bitarray, que se almacenaba en un archivo que simulaba ser un disco rígido. Entonces, en vez de _reservar memoria para almacenar el bitarray_, la función recibe un cacho de memoria que operar como bitarray.

Si querés usarla con memoria "común", reservás vos la memoria en el heap con un `malloc` o similar, y le pasás un puntero a la función.

Si querés que el bitarray sea un pedazo de un archivo, hacés un `mmap` de ese archivo para mapear ese archivo en memoria, y le pasás a la función un puntero al pedazo dentro de ese mapeo de memoria que corresponda.

----

Cómo aplica todo esto al TP de este cuatri, no tengo idea - eso lo siguen charlando acá entre ustedes, y con Dami y el resto de la gente que sabe el enunciado.

**Comment by iago64** [comment]
@guidoenr4 Si el FS es uno solo, pero vos que forma tenes para saber que bloque de datos esta ocupado y que bloque esta libre? vas a recorrer todos los archivos de todos los pokemones puestos en el FS? La respuesta a eso es NO.
Ademas la idea de persistir en un archivo el bitmap es que por ejemplo nosotros podemos darles un FS ya con algunos pokemon o mismo podemos bajarles su GameCard y volverlo a levantar y tendrían que levantar como estaba antes de bajar.

Saludos.-
