### ISSUE TITLE
[Consulta] GameCard implementacion

### ISSUE THREAD

**Issue by Nachiten** [sisoputnfrba/foro#1754]
Estuve leyendo la parte de gamecard de la consigna varias veces, incluso me pegue una leída por varios issues que se hicieron acá sobre el tema como me recomendó un ayudante.

Voy a tratar de ser lo mas especifico posible sobre un par de cosas que no me cierran del todo.

1) Que significa que el path del archivo incluye el archivo metadata? Para propósitos de yo entender el archivo metadata **es** mi archivo o no? Y luego ese archivo estaría apuntando a los distintos bloques que son realmente los datos que yo necesito. Es así o estoy entendiendo mal?
![image](https://user-images.githubusercontent.com/39410888/84391025-c5e5b600-abce-11ea-8004-bf05ba4a1fa0.png)

2) No tiene sentido que yo marque un directorio como abierto no? Eso es solo si no es un directorio supongo. Yo se porque está en negrita cursiva que no puedo permitir que se ingrese a un mismo archivo mas de una vez en paralelo. Pero supongo que no habría drama en que dos procesos entren a la misma carpeta no? (Mientras no toquen un mismo archivo obvio)

3) Entonces... cada archivo dentro de la carpeta "/Files" se compone de un solo archivo o de dos? Esto me tiene bastante confundido.

4) Si hay algo que no entiendo es esta parte de la consigna:
![image](https://user-images.githubusercontent.com/39410888/84392441-c2532e80-abd0-11ea-962b-3da710911a99.png)
Menciona al directorio Pokemon pero luego en los dos paths de ejemplo no se especifica eso. 

Estas son mis consultas. Perdon si no soy muy claro en lo que quiero preguntar es que me encuentro muy desorientado actualmente.

Cualquier palo sobre estos temas me va a ayudar un monton, gracias.

**Comment by ncoen97** [comment]
Buenas.
1. Para entender esto tenes que tener en cuenta dos puntos de vista. Primero si miras desde el lado del filesystem de tu vm, Files y Pikachu son dos directorios que cada uno tiene un Metadata.bin adentro (hasta ahora es simple la cosa). Por otro lado, vos estas desarrollando el filesystem Tall Grass. Desde el lado de Tall Grass los archivos/carpetas representan distintas cosas, Files es un directorio (ya que su Metadata.bin contiene un DIRECTORY=Y) que adentro tiene un archivo llamado Pokemon (ya que su Metadata.bin contiene un DIRECTORY=N). Y como vos bien dijiste, el **contenido** de tu archivo Pokemon va a estar en realidad en los bloques (1.bin, 2.bin, ..., n.bin).
2.  El tema de la restricción de acceso al archivo es solo con respecto al **contenido** de los archivos Pokemon.
3. Me parece que quedó respondida con la 1.
4. Donde menciona el directorio Pokemon es un error, ahí debería decir el directorio Files. Gracias por el warning.
Si hay algo que no quedó claro no dudes en seguir consultado.
Saludos!

**Comment by karengrams** [comment]
¡Buenas!

¿Como va? ¿Quedaron resultas las dudas?

Saludos.

**Comment by Nachiten** [comment]
Por ahora creo estoy bien. Cierro y si tengo alguna otra duda hago otro issue nuevo. Gracias
