### ISSUE TITLE
[BROKER - CACHE] - Dudas sobre las pruebas

### ISSUE THREAD

**Issue by Gonzalo-Avila** [sisoputnfrba/foro#1755]
Buenas! 

Viendo las pruebas subidas nos surgieron las siguientes dudas/inconvenientes:

* Los mensajes que tienen una cadena con el nombre del pokemon, tienen a su vez una variable de tipo uint32_t con la longitud de dicha cadena, para fines prácticos. Nosotros en dicho valor contemplamos el caracter de fin de cadena, o sea: por ejemplo, para el mensaje GET_POKEMON Pikachu, el size para nosotros va a ser 12 bytes, pero para las pruebas es 11 bytes. ¿Esto es un problema? ¿O podemos adaptar las pruebas a nuestra situación? Más que nada para saber si nos podemos evitar revisar todo el código para cambiar esto.  

* Notamos que se tiene en cuenta el tamaño mínimo de partición para el algoritmo de particiones dinámicas. ¿Qué sentido tiene esto? De acuerdo a la teoría, este algoritmo asigna una partición del tamaño justo y necesario, ¿por que asignaríamos más? Nosotros solo contemplamos dicho parámetro para el algoritmo Buddy System, ¿cómo lo interpretamos en particiones dinámicas?

* El orden de las pruebas sugerido es: 
./gameboy BROKER GET_POKEMON Pikachu
./gameboy BROKER GET_POKEMON Charmander
./gameboy BROKER CATCH_POKEMON Pikachu 9 3 #19b
./gameboy BROKER CATCH_POKEMON Squirtle 9 3 #20b
./gameboy BROKER CAUGHT_POKEMON 10 OK
./gameboy BROKER CAUGHT_POKEMON 11 FAIL
./gameboy BROKER CATCH_POKEMON Bulbasaur 1 7 #21
./gameboy BROKER CATCH_POKEMON Charmander 1 7 #22
./gameboy BROKER GET_POKEMON Pichu #9
./gameboy BROKER GET_POKEMON Raichu #10

    Y el resultado esperado: posiciones 0, 11, 25, 44, 64, 68, 72, 89, 111, 120 
¿No debería ser: 0, 11, 25, 44, 64, 68, 72, 93, 115, 124? 
Pareciera que en el CATCH Bulbasaur no contemplaron algún uint32_t, ¿puede ser?

Gracias! Saludos.

**Comment by EliasReuter** [comment]
Hola
Me sumo para aclarar que en el enunciado la única parte en la que se menciona "tamaño mínimo de partición" es en el contenido del **config**, por lo que no esta especificado en donde se debería usar (y por la teoría de clase+libro tenemos entendido que el concepto de partición mínima solo aplica a Buddy System). 
De ahí nuestra duda.
Saludos

**Comment by Frank115** [comment]
Me sumo al issue para ver el primer punto que comentan los chicos, en el Anexo II no se está incluyendo el caracter fin de cadena (por lo que se comenta en los ejemplos, guardar 'pikachu' pienso que deberia ser en 12 bytes).

Elias, fijate que en este [issue](https://github.com/sisoputnfrba/foro/issues/1740) se comenta un ejemplo que seguro te ayuda. Básicamente si el tamaño minimo de particion es mayor a lo que necesitas exactamente, vas a tener fragmentacion interna.

**Comment by papa-caco** [comment]
Hola Muchachos,

Con mis compañeros de equipo nos sumamos a las dudas sobre los resultados de estas pruebas y sus comentarios. Estuvimos haciendo en una planilla excel las cuentas de las direcciones de comienzo de cada partición y también notamos **la diferencia de 4 bytes** en la 1° prueba con el **tamaño mínimo de particiones dinámicas = 4 Bytes** 

![image](https://user-images.githubusercontent.com/35772622/84579381-b8355980-ada3-11ea-8d30-e5386f7d9a5c.png)

El ayudante que nos asistió en el checkpoint esta tarde nos dijo que podría ser que el documento de Pruebas tuviera un error.  En la 2° prueba con **tamaño mínimo de particiones dinámicas = 16 Bytes** estaría bien el documento, no notamos diferencia.

Con respecto a lo que indican en el **Anexo II** del enunciado, que un mensaje **"./gameboy BROKER GET_POKEMON Pikachu"** debería ocupar  en Cache  son **11 Bytes**, interpretamos que No tenemos que guardar el último caracter **\0** de cada String. Implementamos una forma de serializar este tipo de datos, excluyendo al caracter mencionado de guardarlo en la Cache. Al momento de leer de la Cache ese tipo de dato y deserializarlo para reconstruir el mismo mensaje, esto sería cuando el Broker le envía el mensaje a un suscriptor, en la deserializacion le appendeamos el caracter '\0' que no había sido guardado en la cache.
Saludos,

**Comment by Gonzalo-Avila** [comment]
Hola, 
Creo que ya tenemos una linea para seguir.

En resumen: 
* Vamos a quitar el '\0' para adaptarnos a las pruebas y al anexo. 
* Vamos a contemplar la partición mínima en el algoritmo de particiones dinámicas también. 
* En la descripción de las pruebas, aparentemente hay un error de tipeo.

Gracias a todos por las respuestas! Saludos.
