### ISSUE TITLE
[PROBLEMA][HELGRIND] concurrencia logs

### ISSUE THREAD

**Issue by matiasanz** [sisoputnfrba/foro#1756]
Buenas,

Desde que arrancamos con sincro, empecé a ponerle mutex a los logs. Si bien nunca había tenido quejas de helgrind, supuse que tendría sentido pensarlo como sección crítica. Hace poco juntamos lo mío con lo de un compañero que no usaba semaforos para esto y encontramos este issue https://github.com/sisoputnfrba/foro/issues/370 que explican que los t_log no deberían verse afectados por la condición de carrera.

Sin embargo, ahora cuando pruebo con helgrind me tira varios errores de este estilo:
==3695== ----------------------------------------------------------------
==3695== 
==3695== Possible data race during read of size 1 at 0x4242FCE by thread #2
==3695== Locks held: none
==3695==    at 0x4036E33: __GI___rawmemchr (in /usr/lib/valgrind/vgpreload_helgrind-x86-linux.so)
==3695==    by 0x40F37B5: _IO_str_init_static_internal (strops.c:41)
==3695==    by 0x40E76F0: vsscanf (iovsscanf.c:40)
==3695==    by 0x40E23C3: sscanf (sscanf.c:32)
==3695==    by 0x4128DCF: parse_offset (tzset.c:236)
==3695==    by 0x41291EC: __tzset_parse_tz (tzset.c:357)
==3695==    by 0x412A98E: __tzfile_compute (tzfile.c:691)
==3695==    by 0x4129735: __tz_convert (tzset.c:624)
==3695==    by 0x4127D2D: localtime_r (localtime.c:30)
==3695==    by 0x40818F5: temporal_get_string_time (in /usr/lib/libcommons.so)
==3695==    by 0x407EF17: _log_write_in_level (in /usr/lib/libcommons.so)
==3695==    by 0x407ED8D: log_info (in /usr/lib/libcommons.so)
==3695==  Address 0x4242fce is 14 bytes inside a block of size 15 alloc'd
==3695==    at 0x402D36C: malloc (in /usr/lib/valgrind/vgpreload_helgrind-x86-linux.so)
==3695==    by 0x4128C51: __tzstring_len (tzset.c:106)
==3695==    by 0x412A075: __tzfile_read (tzfile.c:454)
==3695==    by 0x41293AA: tzset_internal (tzset.c:441)
==3695==    by 0x4129699: __tz_convert (tzset.c:621)
==3695==    by 0x4127D2D: localtime_r (localtime.c:30)
==3695==    by 0x40818F5: temporal_get_string_time (in /usr/lib/libcommons.so)
==3695==    by 0x407EF17: _log_write_in_level (in /usr/lib/libcommons.so)
==3695==    by 0x407ED8D: log_info (in /usr/lib/libcommons.so)
==3695==    by 0x804E5E0: main (Team.c:20)
==3695==  Block was alloc'd by thread #1

Aclaro que al único módulo que afecta es al team. Para el resto, que no usan mutex cuando loggean, no tiene ninguna queja relacionada.

Gracias y Saludos

**Comment by iago64** [comment]
Buenas!
La condición de carrera es normal que exista si no tienen semaforos.
Ahora que no importe realmente que hilo loguea primero y que hilo loguea segundo es otro tema.
Tengan en cuenta que las condiciones de carrera en un log son realmente poco importantes porque no deberian cambiar el comportamiento de su programa, de todas formas si los deja mas tranquilo agregarle un semaforo no esta mal.

Saludos.-

**Comment by matiasanz** [comment]
Gracias!
