### ISSUE TITLE
Team: Reintentar conexiones al enviar un Catch

### ISSUE THREAD

**Issue by leobz** [sisoputnfrba/foro#1757]
Team:
Si yo creo una nueva conexión por cada mensaje Catch que envió. Entonces...
¿Qué sentido tiene re-intentar la conexión, si a la primera vez que falla, por comportamiento default le entrego el pokemon al entrenador? 
Es decir, si después re-intento y retomo esa conexión, ¿De que me sirve si ya le asigné el pokemon al entrenador?

**Comment by iago64** [comment]
Buenas!
El tema de reintentar conexiones es para las suscripciones, el mensaje de catch si falla tiene el comportamiento por default y fue, no hace falta reintentarlo.

Abrazo.-

**Comment by leobz** [comment]
Gracias!
