### ISSUE TITLE
Broker: Asumismos que la memoria  caché de la config es un valor de 2 a la n?

### ISSUE THREAD

**Issue by leobz** [sisoputnfrba/foro#1758]
¿El tamaño de la memoria caché definida en el archivo de configuración es siempre de 2^n? 
Ésta duda surge al momento de tener que ir dividiendo (particionando) la memoria caché para agregar un nuevo mensaje a la misma.  Más que nada en el esquema de Buddy System.

**Comment by iago64** [comment]
No es necesario que sea 2^N ya que particiones dinámicas no es necesario que sea 2^N, con lo cual podrian validarlo para buddy system solamente.

Saludos.-

**Comment by leobz** [comment]
Gracias!
