### ISSUE TITLE
[Pruebas - Scripts] Diferencias con los requerimientos del enunciado

### ISSUE THREAD

**Issue by papa-caco** [sisoputnfrba/foro#1759]
Buenas!!

Estoy probando los scripts para las pruebas del Checkpoint de mañana que descargué de 

> https://github.com/sisoputnfrba/delibird-pruebas

y he notado que en los scripts de las pruebas del Gamecard en cada mensaje:

>  **./gameboy GAMECARD NEW_POKEMON @@ ## ## ##** 

no le estarían pasando el **Id del mensaje**.  Por ejemplo, esto es lo que veo en el script **new_pokemons_varios.sh** 

> ./gameboy GAMECARD NEW_POKEMON Pikachu 1 9 3
> ./gameboy GAMECARD NEW_POKEMON Charmander 4 1 101
> ./gameboy GAMECARD NEW_POKEMON Charmander 517 2046 15
> ./gameboy GAMECARD NEW_POKEMON Charmander 413 17 1
> ./gameboy GAMECARD NEW_POKEMON Charmander 723 97 29
> ./gameboy GAMECARD NEW_POKEMON Charmander 65 93 3001
> ./gameboy GAMECARD NEW_POKEMON Charmander 12 17 34
> ./gameboy GAMECARD NEW_POKEMON Charmander 129 547 11
> 

En la última versión del enunciado del TP, **página 31**, nos piden que el último argumento de este tipo de mensaje le pasemos al GameCard el Id del mensaje:

> **./gameboy GAMECARD NEW_POKEMON [POKEMON] [POSX] [POSY] [CANTIDAD] [ID_MENSAJE]**

¿Estoy equivocado o deberíamos corregir los scripts del GameCard agregándole un "**Id**" al final de cada mensaje?

Muchas Gracias!  Saludos,

**Comment by iago64** [comment]
Buenas buenas!

Si, fue un pifie, eventualmente ese parametro podria ir en 0, pero bueno, lo vamos a estar corrigiendo en estos dias porque ademas tenemos que revisar algunos datos extra de los tamaños de los mensajes asi que hacemos un combo y publicamos los ajustes :)

Saludos.-

**Comment by papa-caco** [comment]
Ok Damian. Muchas Gracias! Caso cerrado.
Saludos.
