### ISSUE TITLE
Nuevos videos para el TP

### ISSUE THREAD

**Issue by enogueiras** [sisoputnfrba/foro#1760]
Hola, pregunto por acá, había preguntado en Discord pero no me respondieron, ¿tienen pensando hacer algún video mas para el TP, por ejemplo de memoria?

Muchas gracias.
Saludos,
Emilio.

**Comment by BelenTripodi** [comment]
same :-D

**Comment by iago64** [comment]
Buenas buenas! De momento esta en proceso lo que comento Nahue en el video de presentación del TP.
Tengan en cuenta que hasta hoy veniamos enfocados en guiar grupos para el checkpoint, con lo cual a partir de hoy en cuanto tengamos algo lo vamos a ir publicando.

Saludos.-

**Comment by enogueiras** [comment]
Muchas gracias, ya vimos el nuevo video.
Saludos,
Emilio.
