### ISSUE TITLE
Segmentation Fault en compilador al incluir biblioteca stdio.h

### ISSUE THREAD

**Issue by julchat** [sisoputnfrba/foro#1761]
Buenas, estaba tratando de compilar el programa despues de agregar bastantes nuevas funcionalidades y me tira esto:

```
`21:03:07` **** Incremental Build of configuration Default for project Team ****
make all 
Building file: ../src/Team.c
Invoking: GCC C Compiler
gcc -Icommons -O2 -g -Wall -c -fmessage-length=0 -pthread -MMD -MP -MF"src/Team.d" -MT"src/Team.o" -o "src/Team.o" "../src/Team.c"
In file included from /usr/include/stdio.h:933:0,
                 from ../src/Team.c:2:
/usr/include/i386-linux-gnu/bits/stdio.h: In function ‘fputc_unlocked’:
/usr/include/i386-linux-gnu/bits/stdio.h:89:1: internal compiler error: Segmentation fault
 {
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
make: *** [src/Team.o] Error 1
src/subdir.mk:24: recipe for target 'src/Team.o' failed

21:03:08 Build Finished (took 982ms)`
```

Lo raro es que stdio.h esta incluido desde hace meses en el codigo de mi modulo.
Aiuda no se que hacer, reinstalo eclipse?
gracias

**Comment by tferraro** [comment]
Dificil entender que fue lo que pasó con el compiler si no nos contás si pudiste reproducirlo con un snippet o info sobre el código que estás compilando😬

Si no podés generar un [snippet](https://es.wikipedia.org/wiki/Snippet) del código que genere ese error, en una versión anterior compiló? que diferencias existieron entre esas versiones? Que intentaste para solucionar el issue? Encontraste algo en internet o probaste algo?

**Comment by mgarciaisaia** [comment]
Che, qué garrón. Qué puntería, pegarle a un bug del compilador, eh.

Antes que nada, sí: es un bug del compilador. El compilador _no debería_ darte un segmentation fault. Hagas lo que hagas con tu código. Así que, nada: garrón haberle pegado _justo_ a un bug del compilador.

Anyway, _es muy probable_ que el bug pase porque hay algún error raro en tu código que el compilador no está sabiendo manejar. Hablo de probabilidades porque, buen - es un bug, no es comportamiento esperado que falle así.

Así que ahí entra un poco lo que dice @tferraro de ver qué onda el código que estás compilando. Si conseguís un cacho de código mínimo que reproduzca el problema, puede servir para reportarle el bug a quienes hacen `gcc`. Pero la otra es probar de cambiar el orden de los `#include`s o ver qué se le puede cambiar al código para ver si evitás caer en la condición que hace que el compilador falle.

Muy raro, che, y no sé mucho cómo colaborarte. Si querés/podés, hacé un branch del repo con el código que hace generar el segfault, y pushealo (y pasame el hash del commit) así lo chusmeamos.

La otra es preguntarte si recientemente actualizaste `gcc` por algún motivo, o si al resto de tu grupo le pasa lo mismo, o si estuviste tocando "algo raro" en la VM que pueda haber hecho que empiece a fallar.

**Comment by iago64** [comment]
@julchat como va? pudiste avanzar con algo de lo que te preguntaron tom y mati?

**Comment by julchat** [comment]
Sisi el error despues escalo mas grande, sin dejarme guardar el codigo del modulo porque estaba en solo lectura supuestamente, y quise reiniciar la vm pero nunca arrancaba. Bueno en fin reinstale la vm y clone el repo. Cosas que pasan 🤷‍♂️
