### ISSUE TITLE
Logs obligatorios Gamecard

### ISSUE THREAD

**Issue by MatiCoarasa** [sisoputnfrba/foro#1762]
Buenas, puede ser que se haya eliminado la sección de Logs obligatorios del Gamecard del enunciado?

![image](https://user-images.githubusercontent.com/22768831/84581444-4ebf4600-adb7-11ea-839d-7d67be7cedae.png)

**Comment by iago64** [comment]
Buenas!

Revisando un poco el historial de versiones no lo encontre, es posible que se nos haya recontra pasado, igual tranqui que en un par de dias sale la v1.4 con algunas aclaraciones y lo sumamos 😉 

Saludos.-

**Comment by MatiCoarasa** [comment]
Ah ok, gracias!

**Comment by MatiCoarasa** [comment]
Perdón que moleste de nuevo con esto pero vi que no están en la v1.4, podrían revisarlo pls?

Gracias

**Comment by iago64** [comment]
Buenas!

Efectivamente, no lo sumamos porque en lineas generales los "logs" del gamecard los podemos inferir por los cambios en los archivos (tanto metadata como bloques, con lo cual, pueden tomarse las libertades que quieran con los logs tratando de que los mismos reflejen lo que va ocurriendo en el sistema y que permitan hacer un seguimiento de lo que pasa.

Saludos.-

**Comment by MatiCoarasa** [comment]
Perfecto, tiene sentido. Graciasss
