### ISSUE TITLE
Broker - Duda sobre desuscribir a un proceso de una cola de mensajes

### ISSUE THREAD

**Issue by NicoVillar98** [sisoputnfrba/foro#1763]
Buenas! 
En el checkpoint de ayer me surgió la duda sobre desuscribir a un proceso de una cola, yo hice una función de desuscribir para que fuera mas fácil para el gameboy, en la que si te queres desuscribir de una cola le mandas un mensaje al broker y este te elimina de la cola de mensajes.
La duda que me surgió es: si esta bien que yo elimine a un proceso de la cola de mensajes, ya que en caso de que se suscriba de nuevo le debería mandar todos los mensajes otra vez, incluso si ya los haya recibido. O si debería hacer que le lleguen solo los mensajes que no recibió.
Saludos.

**Comment by ncoen97** [comment]
Buenas.
La idea es que si un cliente se desconecta y se vuelve a suscribir a una cola, tenes que reenviarle solamente los mensajes que NO recibió anteriormente. Con respecto a cómo hacen el desarrollo ustedes (ya sea eliminandolo de la cola y añadiendolo a otra auxiliar o dejandolo en esa cola pero especificar si esta conectado/desconectado, etc.) ya queda a su criterio y va a depender de su propia solución.
Saludos!

**Comment by iago64** [comment]
Buenas, como va? 
La duda esta resuelta @NicoVillar98 ?
Saludos.-

**Comment by NicoVillar98** [comment]
si ya esta resuelta colgue en cerrar la issue
