### ISSUE TITLE
BROKER - Dudas sobre buddy system y algoritmos BEST FIT y FIRST FIT

### ISSUE THREAD

**Issue by BelenTripodi** [sisoputnfrba/foro#1764]
Buenas! 
Para buddy system hay que implementar first fit y best fit también? O siempre voy a buscar la partición potencia de 2 más cercana a lo que quiero guardar y si no está la que el sigue y empiezo a romper en bloquecitos más chicos (recorriendo 1 vez x potencia de 2 recorriendo finalmente n veces hasta encontrar algo? Podría tener la lista de particiones ordenadas por tamaño y agarro la más chica que sea mayor a la potencia de 2 que quiero guardar (BF), o podría agarrar la primera que encuentre sin tener la lista ordenada (FF).

**Comment by afilgueira** [comment]
Hola, es una excelente pregunta. Entiendo que Buddy System no impone de por sí una manera, pero que lo ideal es evitar la fragmentación innecesaria. Te recomendaría usar la partición más chica que te sirva (e inclusive partirla si fuese necesario) y pensar para el coloquio qué problemas/soluciones te traería la otra variante.

Saludos!

**Comment by iago64** [comment]
Buenas, como va? 
La duda esta resuelta @BelenTripodi ?
Saludos.-

**Comment by BelenTripodi** [comment]
Buenisimo adro. Gracias. 

Cierro el issue
