### ISSUE TITLE
BROKER - Dudas particiones 

### ISSUE THREAD

**Issue by BelenTripodi** [sisoputnfrba/foro#1765]
Buenas!
Si después de crear la partición con tamaño del que yo quiero, el excedente de memoria libre es menor al tamaño mínimo de partición qué hago? Disparo una eliminación de víctima? o me banco esa fragmentación interna? O me va a quedar una partición con tamaño menor a mínimo? 

Ej: tengo libre 30k quiero guardar 20k y el tamaño mínimo es 15k, me van a sobrar 10k que es < al mínimo

**Comment by ncoen97** [comment]
Buenas.
Tendiendo en cuenta que en las particiones dinámicas no se debe asignar más memoria de la necesaria (excepto en el caso de que se solicite menos del tamaño mínimo de partición), me parece que lo más correcto sería liberar otras particiones hasta que consigas tener una que cumpla con todos los requisitos necesarios (no ser mas chica que el mínimo de partición y ajustarse al tamaño pedido).
Saludos!

**Comment by EliasReuter** [comment]
Hola 
Me sumo al issue porque tenemos la misma duda y aun no lo tenemos claro.

Cuando implementamos particiones mínimas en Buddy System, no corremos riesgo de crear particiones de tamaño menor por la propia lógica del algoritmo, ya que solo se crean particiones de, a lo sumo, el mismo tamaño que la partición en la que guardamos el dato entrante (nunca menor).

En cambio, en particiones dinámicas, cuando yo quiero guardar un dato nuevo en la memoria, en muchos casos termino creando 2 particiones de tamaños diferentes.

Por ejemplo, si mi memoria es de 8 bytes, y tengo que guardar 3 bytes, crearía una partición de 3 bytes (donde guardaría el valor) y otra de 5 bytes vacía. Ahora, si se impone una partición mínima, por ejemplo 5 bytes, yo tendría que crear una partición de 5 bytes para el valor que quiero guardar, y me quedaría otra partición libre de 3 bytes, lo cual contradice la idea. Mismo sucedería si por ejemplo quisiera guardar un valor de 7 bytes: me generaría una partición de 1 byte, lo cual es menor al tamaño mínimo de partición definido.

Nuestra duda es si tenemos que contemplar esto, o si solo tenemos que asegurarnos de que las particiones ocupadas sean las que tienen que cumplir el criterio de partición mínima (pudiendo quedar particiones inutilizadas de tamaño menor al indicado por config), porque sino se nos complicaría bastante el algoritmo.

Saludos

**Comment by ncoen97** [comment]
Buenas, lo que vos planteas en el ultima párrafo es justamente lo que mencioné en la respuesta anterior (si tenes que asignar una nueva partición y la que te queda es demasiado chica, tenes que disparar una eliminación de alguna otra partición para poder cumplir con ambos requisitos).

**Comment by BelenTripodi** [comment]
Buenisimo (gracias @EliasReuter por linkear esto en el otro issue, con eso nos termino de cerrar). Saludos. 

Cierro el issue.
