### ISSUE TITLE
BROKER - IDs de mensajes para emisores

### ISSUE THREAD

**Issue by BelenTripodi** [sisoputnfrba/foro#1767]
Buenas! 
Entendemos que solo para el CATCH y el GET necesitamos enviar el id generado a los  emisores (El enunciado dice que hay que enviarlo en todos los tipos de mensajes a todos los emisores, pero no todos necesitan saberlo). En todos los demás casos, no le encontramos sentido el enviárselo. 

Ej: el gameboy arranca haciendo un new, para qué le devuelvo el id que le generé a ese NEW? Luego ese NEW va a ser propagado a todos los gamecards, las que me van a responder con un APPEARED (tampoco vemos necesario volverle a mandar el id que le generé a ese APPEARED).

Podrían aclararnos esto?

**Comment by ncoen97** [comment]
Buenas, para ser consistentes en todos los envíos de mensajes y a su vez apegarnos a los aspectos técnicos de las Message Queue, lo correcto sería que sigan esta parte del enunciado (Broker - Lineamiento e Implementación):

> Todo mensaje debe tener un identificador unívoco generado por el Broker que debe ser informado al módulo que generó el mismo.

Saludos!

**Comment by iago64** [comment]
Buenas, como va? 
La duda esta resuelta @BelenTripodi ?
Saludos.-

**Comment by BelenTripodi** [comment]
Gracias. Quedo claro. 

Perdon por la demora. Cierro el issue.
