### ISSUE TITLE
GAMEBOY - ID para reconexion

### ISSUE THREAD

**Issue by BelenTripodi** [sisoputnfrba/foro#1768]
Buenas!

Cuando arranco con el modo suscriptor de gameboy, voy a necesitar enviarle el id del mismo como con los gamecards y teams?  Tiene que tratarse siempre como un suscriptor nuevo o como uno que se reconecta?

**Comment by ncoen97** [comment]
Buenas!
Si es un mismo gameboy que se cae y vuelve a levantar y tiene la misma configuración, debería seguir las mismas reglas que los otros módulos y sólo recibir los mensajes que no recibió previamente.
Saludos.

**Comment by iago64** [comment]
Buenas, como va? 
La duda esta resuelta @BelenTripodi ?
Saludos.-

**Comment by BelenTripodi** [comment]
Buenisimo!

Si, perdon por la demora. Cierro el issue.
