### ISSUE TITLE
TEAM -  DEADLOCK ->CANTIDAD DE INTERCAMBIO DE POKEMONS ?

### ISSUE THREAD

**Issue by miguel-t** [sisoputnfrba/foro#1769]
Buenas.
En el video Planificacion(**minuto 25:54**) menciona  que cuando el entrenador E1 se mueve 
a la posicion de E2, se intercambia 1 pokemon de E1 y 1pokemon E2(se puede repertir   2 de cada uno ) .
Mi pregunta es : ¿en un intercambio participan dos pokemon , 1 de cada entrenador?

Por ejemplo si tengo estos 3 entrenadores en cola de bloqueados y todos los demas estan el cola de exit.
**E1**:  [atrapados: P1 , objetivos:C1 ]
**E2**:  [atrapados: C1 , objetivos:S1 ]
**E3:**  [atrapados: S1 , objetivos:P1 ]
A quien tendria que mover ? cuantos pokemons van a participar en el intercambio ? entiendo que 1.

Gracias!
Saludos,

**Comment by ncoen97** [comment]
Buenas, te cito esta parte del enunciado que me parece bastante clara:

> Cada intercambio ocupara 5 ciclos de CPU. Cada intercambio solo involucra a dos Pokémon.

Teniendo esto en cuenta, en el ejemplo que planteas se necesitarían 2 intercambios.
Saludos!

**Comment by iago64** [comment]
Buenas, como va? 
La duda esta resuelta @miguel-t ?
Saludos.-

**Comment by miguel-t** [comment]
Si.
Saludos.
