### ISSUE TITLE
[TEAM] Dudas varias planificacion

### ISSUE THREAD

**Issue by SebastianNLerner** [sisoputnfrba/foro#1770]
Buenas,
1. Teniamos la consulta con mi grupo de si podiamos tratar el mensaje localized como varios mensaje appeared (uno por cada posicion que nos llega)
2. Podria pasar que me llegue un mensaje appeared de un pokemon que me interesa, del cual necesitamos dos, pero como me llega un appeared solo puedo atrapar uno (porque no admitiria mas mensajes de localized ni appeared relacionados a ese pokemon), por lo que no podria nunca cumplir el objetivo global de mi team?

**Comment by ncoen97** [comment]
Buenas.
1. A que se refieren con "tratar"? Necesitaría un poco mas de contexto.
2. Debe haber algo que no les quedó claro del enunciado. Por qué no admitirías otro mensaje Appeared?  Me parece que la confusión está por el comportamiento del Localized que no es el mismo que el del Appeared.
Saludos!

**Comment by SebastianNLerner** [comment]
1. Con tratar nos referimos a que adentro de la cola de mensajes (implementamos una cola global de mensajes) cuando recibimos un localized lo guardamos como varios mensajes de tipo appeared  (uno por cada posicion del mensaje localized).
2. Creo que fue una mala interpretación nuestra del enunciado. Si me llega un mensaje localized solo puedo recibirlo si nunca recibí un mensaje appeared de ese tipo de Pokémon, en cambio si me llega un appeared lo puedo recibir sin importar si me llegó un localized anteriormente o no. Estaría en lo correcto?

**Comment by ncoen97** [comment]
1. Si se refieren a una estructura interna del Team donde manejan los mensajes recibidos, sí pueden desarrollarlo como crean conveniente. Mientras no se contradiga con ningún punto del enunciado es correcto.
2. Es casi correcto, "Si me llega un mensaje localized solo puedo recibirlo si nunca recibí un mensaje appeared O LOCALIZED de ese tipo de Pokémon".

**Comment by iago64** [comment]
Buenas, como va? 
La duda esta resuelta @SebastianNLerner ?
Saludos.-

**Comment by SebastianNLerner** [comment]
Si si

**Comment by iago64** [comment]
Buenisimo, cerramos el issue entonces 😄
