### ISSUE TITLE
Gamecard - Sincronizacion

### ISSUE THREAD

**Issue by ntaboada** [sisoputnfrba/foro#1771]
Buenas gente,

Tengo una duda con respecto a como encarar la sincronizacion del FS y tambien una duda sobre la implementacion del mismo. Vamos con las dudas:

1) En el TP se habla de que para el NEW/CATCH/GET hay que verificar que el archivo este abierto, y si lo esta reintentar luego de X segundos (por config). Mira pregunta aca seria si cuando se habla del archivo se habla unicamente **Metadata.bin** o del **Metadata.bin + los bloques**. Porque puede pasar que  un mismo proceso quiera escribir/leer los bloques pero el TP habla de archivo y eso me confunde (no se si esta implicito que archivo sea Metadata+Bloques para ese pokemon)

2) No logro entender para que tener una key dentro del Metadata.bin de cada Pokemon file para determinar si esta abierto/cerrado. De la forma que estoy pensando armar la manera de sincronizar a los procesos es tener una lista global (compartida por los procesos) donde la tengamos es el pokemonFileNames (una lista de strings). Encerrar las lecturas/escrituras (relacionado al punto 1, asumiendo que con archivo nos referimos a Metadata+Bloques) obteniendo el pokemonFileName y llamando a un mutex. Algo como:

```
void lockReadOrWriteFile(char* pokemonfilename) {
  pthread_mutex_lock(&SEM1); --> por ser var global compartida
 file = lista_get(pokemonfilename);
  pthread_mutex_lock(&SEM1); --> por ser var global compartida
if (file != null)
 pthread_mutex_lock(&SEM2); --> bloqueo
}

void unlockReadOrWriteFile(char* pokemonfilename) {
  pthread_mutex_lock(&SEM1); --> por ser var global compartida
 file = lista_get(pokemonfilename);
  pthread_mutex_lock(&SEM1); --> por ser var global compartida
if (file != null)
 pthread_mutex_unlock(&SEM2); --> desbloqueo
}

```
Tener esas dos funciones al principio y final de cada escritura lectura. Dicho esto, no entiendo que hacer con el valor de OPEN del Metadata.bin si encerrando en algo asi puedo bloquear a un 2do proceso (aparte de que no estoy seguro de si produciria espera activa al leer ese valor).

3) No estoy seguro de que tipo de semaforo usar. Investigando vi que tambien existen las funciones de: 
**pthread_rwlock_rdlock** y **pthread_rwlock_wrlock**. No entiendo muy bien su funcionamiento y si tendria que usarlos aca.

4) Relacionado con el pto 2). Asumiendo que lo que arme puede tener sentido. Ahora tengo que pensar de que forma implementar lo de "reintentar luego de X segundos". No se me ocurre como implementarlo ya que al tener 2 procesos, si el primero esta abriendo el archivo (leer/escribir), el 2do proceso se va bloquear que es lo que queremos pero donde meto la logica de "reintentar abrirlo" si el 2do esta totalmente bloqueado?

Desde ya muchas gracias

**Comment by guidoenr4** [comment]
Yo tuve la misma duda en su momento, pero la idea de ese valor en tu metadata actua como semaforo. Vos al leer un archivo tenes que fijarte si lo podes acceder preguntando si ese valor de OPEN esta en `N` , obviamente lo podes leer cuando quieras.. y quien quiera, pero cuando vayas a modificarlo tenes que asegurarte que tu archivo no este en **lock**

**Comment by ntaboada** [comment]
Justito encontre tu issue jaja @guidoenr4. Genial, uso el Open/Close como semaforo y puedo leer el metadata por varios procesos. Entonces me quedan otras dos preguntas:

1) Asumo que con "verificar si el archivo esta abierto" se refieren a los "bloques" que estan siendo ocupados por ese pokemon (y descritos en el metadata.bin del pokemon)?
2) Si la respuesta de 1) es SI Hago el update de OPEN=YES al leer/escribir los bloques? 
3) No entendi lo de asegurarme que mi archivo no este en **lock**. Entiendo que te referis a usar un semaforo al hacer un update del Metadata. Pero para que haria eso si un 2do proceso va estar bloqueado al leer que OPEN = Y, por ende un solo proceso va entrar al bloque del if (open = "N") (aca hago lecturas y escrituras).
Salvo que... tenga que hacer un update del metadata al leer y al escribir onda:

```
if (open = "N") {
updateMetadata() -> updateo de Open = Y
readBlocks()
updateMetadata() --> updateo el metadata de Open = N ya que deje leer
processBlocks() 
updateMetadata() -> updateo de Open = Y
writeBlocks ()
updateMetadata() -> updateo de Open = N
}
```

Lo que implica, que te puede caer un 2do proceso que esta reintentando leer y tendrias dos procesos dentro del if, entonces habria que poner un semaforo encerrando los update?

**Comment by jdevergilio** [comment]
Personalmente, fuí por la segunda, ya que considero que un Pokemon es un conjunto de partes (Metadata + Bloques), y si haces la primera opción, entre la lectura y escritura de bloques, se te puede meter otro proceso y modificar tanto el metadata, como los bloques.

if (open = "N") {
updateMetadata() -> updateo de Open = Y
readBlocks()
updateMetadata() --> updateo el metadata de Open = N ya que deje leer
**Aca se puede meter algún otro proceso y modificarte la sección crítica **
processBlocks() 
updateMetadata() -> updateo de Open = Y
writeBlocks ()
updateMetadata() -> updateo de Open = N
}

En cambio, con esta otra manera, te aseguras de que nadie te modifique, ni lea, los datos mientras algún otro proceso esté trabajando en la sección crítica.

if (open = "N") {
updateMetadata() -> updateo de Open = Y
readBlocks()
processBlocks() 
writeBlocks ()
updateMetadata() -> updateo de Open = N
}

**Comment by ntaboada** [comment]
@Nachiten @jdevergilio En base a lo que dijo javi, haciendo algo como:
_En cambio, usando el OPEN + un solo semáforo que impidan que dos o mas procesos accedan a archivos del tipo metadata al mismo tiempo, podrías gestionar todos los pokemones que desees._

Si tenes un proceso 1 haciendo NEW Pikachu, otro proceso 2 haciendo NEW Pikachu, y un tercer proceso haciendo NEW Charmander, los dos primeros van a estar bien sincronizados (1 solo open) el tema es que al tercer proceso lo bloquearias cuando no hay ningun proceso abriendo a ese file.

**Comment by Nachiten** [comment]
> @Nachiten @jdevergilio En base a lo que dijo javi, haciendo algo como:
> _En cambio, usando el OPEN + un solo semáforo que impidan que dos o mas procesos accedan a archivos del tipo metadata al mismo tiempo, podrías gestionar todos los pokemones que desees._
> 
> Si tenes un proceso 1 haciendo NEW Pikachu, otro proceso 2 haciendo NEW Pikachu, y un tercer proceso haciendo NEW Charmander, los dos primeros van a estar bien sincronizados (1 solo open) el tema es que al tercer proceso lo bloquearias cuando no hay ningun proceso abriendo a ese file.

Tener 1 semaforo dios para todos los metadata.bin está re mal por lo que acabas de decir. Cuando yo abro un pokemon no puedo bloquear a que todo el universo toque cualquier metadata.bin...

Deberias tener 1 semaforo por cada metadata.bin asociado a cada pokemon.

Si yo por ejemplo tengo 4 pokemones voy a tener sus cuatro metadata mas 4 semaforos.

Es otra discusion como levantar un semaforo por cada pokemon y que es un bardo llevar control de tantos semaforos. Pero poder si que se puede. Y creo es lo que debemos hacer.

Espero la rta de algun ayudantes para tirarnos algun palo :p

**Comment by jdevergilio** [comment]
Solo lo bloqueo en el instante que me le cambio el estado a Pikachu a OPEN=Y, y luego lo libero, no lo bloqueo a lo largo de todo el Proceso de Pikachu.
Sería algo así:

W(mx_files)
VerificarSiExiste(POKEMON) ---> (Acá adentro si cambia el estado a OPEN Y si existe)
S(mx_files)
...
Continuar con el proceso

**Comment by Nachiten** [comment]
> Solo lo bloqueo en el instante que me le cambio el estado a Pikachu a OPEN=Y, y luego lo libero, no lo bloqueo a lo largo de todo el Proceso de Pikachu.
> Sería algo así:
> 
> W(mx_files)
> VerificarSiExiste(POKEMON) ---> (Acá adentro si cambia el estado a OPEN Y si existe)
> S(mx_files)
> ...
> Continuar con el proceso

Si, solo lo usas para escribir el open=y o open=n segun corresponda. Pero me sigue pareciendo mal que tengas un mutex para TODOS los metadata.bin y no uno para cada uno.

**Comment by ntaboada** [comment]
Yo coincido con @nachiten, la manera de resolver esto seria con una lista de semaforos, uno para cada pokemon. Pero volvemos a lo mismo, el Open = Y/N te queda re colgado... Como llamamos algun ayudante?

**Comment by jdevergilio** [comment]
Entiendo lo que decis, pero si manejamos semáforos individuales por cada Pokemon, que sentido tiene tener el OPEN en el Metadata? 
Me parece que lo pusieron precisamente con esa intención, de simplificar el uso de los semaforos y no nos volvamos locos.

**Comment by Nachiten** [comment]
@ntaboada @jdevergilio 
Yo lo pienso de esta manera (no estoy seguro que esté bien):
Una vez que marcas un archivo como open=y vas a estar bloqueando a que todo proceso que venga de ahora en mas (hasta que yo lo cierre) lea el open=y por lo tanto va a entrar en tiempo de espera fijado por archivo de config. Cuando vuelva a consultar obviamente puede seguir como open=y o puede ser que en el medio yo lo haya cambiado por lo que entre y lo modifique para ahora usarlo el. Nadie mas va a poder usarlo hasta que el termine. Y asi sucesivamente.

Por eso para mi tiene sentido tener ambas cosas asi lo veo. No se si se me entiende.

El mutex como dijeron antes yo lo uso solamente para escribir el archivo metadata.bin y luego lo libero.
Hago lo siguiente:

leo archivo para ver si está open=n (en este caso lo está)
wait(mutex)
escribo el open=y
signal(mutex)

hago todo lo q necesite con los bloques. Mientras tanto nadie va a poder tocar este archivo ya que al leerlo encuentran open=y.

ahora lo termino de utilizar
wait(mutex)
escribo open=n
signal(mutex)

listorta.

**Comment by jdevergilio** [comment]
Claro, fue lo que propuse, 1 solo semáforo mutex para todos los Pokemones + el status de OPEN del metadata.
O estoy entendiendo mal?

**Comment by ntaboada** [comment]
Puede andar esa solucion, me hace ruido no mas que dos archivos diferentes (pokemons diferentes) no puedan actualizar su Metadata al mismo tiempo. Pero es la unica solucion que veo... Estaria bueno que algun ayudante nos confirme asi voy por esa opcion.

Quedaria asi entonces?

```
if (open = "N") {
wait(sem)
updateMetadata() -> updateo de Open = Y
signal(sem)
readBlocks()
processBlocks() 
writeBlocks ()
wait(sem)
updateMetadata() -> updateo de Open = N
signal(sem)
} else {
  reintentarLuegoDeXSegundos()
}
```

**Comment by jdevergilio** [comment]
Encontré esto en  #1716 , entiendo que ese usuario es uno de los ayudantes.
![image](https://user-images.githubusercontent.com/48719022/84792587-6884a700-afca-11ea-994b-11839b1f4054.png)

**Comment by iago64** [comment]
Buenas buenas!
Siento que es un dejavu del issue que acabo de contestar, pero no problem :)
Efectivamente, la idea de meter un mutex a la hora de tocar el metadata.bin esta perfecto, lo que estaría mal seria que ese mutex incluya la operatoria con los bloques.
Es un poco la idea del bitmap, varios hilos pueden querer accederlos al mismo tiempo y eso no esta bien, entonces solo sobre esa mínima porción de código esta bien que lo tengan sincronizado. Después la operación sobre los bloques, como los mismos van a estar relacionados a un archivo que va a tener el flag de OPEN en Y, solo 1 hilo va a estar operando ahí.

Saludos.-

**Comment by ntaboada** [comment]
@iago64 entiendo entonces  que a la solucion que llegamos entre los 3 seria la correcta. Pero para confirmar, esta bien entonces que dos procesos diferentes haciendo:
NEW POKEMON  PIKACHU
NEW POKEMON  CHARMANDER

Se bloqueen al leer sus metadata? Osea que hasta que el proceso 1 no termine de leer su metadata, el proceso 2 no pueda leer la suya?

**Comment by ntaboada** [comment]
Dejo una consultita mas: 
El semaforo mutex seria global para las 3 operaciones no? (new, catch, get)

**Comment by jdevergilio** [comment]
Entiendo que si, dado que la sección crítica es la misma.

**Comment by Nachiten** [comment]
> Dejo una consultita mas:
> El semaforo mutex seria global para las 3 operaciones no? (new, catch, get)

Pensa en que vos queres poder permitir que 5 hilos si quieren (por ejemplo new) escriban a la vez si es en archivos distintos no? Idem para el resto de colas. Por lo cual me parece que lo mejor es tener un semaforo por cada archivo pokemon. No por cada cola y tampoco uno solo para todo el sistema.

**Comment by ntaboada** [comment]
pero como, no quedamos que con el Open=Y/N actua como semaforo para cada file?

**Comment by jdevergilio** [comment]
Ayer el ayudante nos indicó que sería correcto utilizar un solo semáforo. 
De hecho, si vamos al caso, para el bitmap, también usas un solo semáforo, no tenes un semáforo por cada bloque, y si consideras los metadatas de los files como una unidad, al igual que el bitmap, estamos en la misma.
Creo que utilizar un semáforo por cada Pokemon, no traería grandes beneficios ya que solo se bloquearían los hilos por un instante, ni otorgaría ninguna protección adicional, además de que implicaría varias horas mas de desarrollo. 
Obviamente cada uno va con la opción que considere mas acertada. Personalmente voy con usar un solo mutex, me parece menos engorroso y el efecto deseado es prácticamente el mismo.

**Comment by iago64** [comment]
@ntaboada De hecho usar 1 solo semáforo por cada metadata es la solución correcta, ya que usar 1 semáforo por operación, medio que puede hacer que termines pegándote de frente contra el concreto porque justamente un new te puede estar agregando pokemones una posición mientras que un get puede no encontrarlos o peor, un catch puede estar descontandotelos y si vos no bloqueas el metadata para que solo 1 entre con el flag de OPEN... nos vemos en disney ;)

Ahora si por tenes un NEW PIKACHU y un NEW CHARMANDER, esos pueden correr completamente en paralelo porque justamente son archivos diferentes, de pokemones diferentes y lo que vos **no queres** es que 2 hilos jueguen en los mismos bloques.

Abrazo.-

**Comment by Nachiten** [comment]
> @ntaboada De hecho usar 1 solo semáforo por cada metadata es la solución correcta, ya que usar 1 semáforo por operación, medio que puede hacer que termines pegándote de frente contra el concreto porque justamente un new te puede estar agregando pokemones una posición mientras que un get puede no encontrarlos o peor, un catch puede estar descontandotelos y si vos no bloqueas el metadata para que solo 1 entre con el flag de OPEN... nos vemos en disney ;)
> 
> Ahora si por tenes un NEW PIKACHU y un NEW CHARMANDER, esos pueden correr completamente en paralelo porque justamente son archivos diferentes, de pokemones diferentes y lo que vos **no queres** es que 2 hilos jueguen en los mismos bloques.
> 
> Abrazo.-

Por mi parte clarisimo, gracias!

**Comment by iago64** [comment]
@ntaboada Alguna duda mas o esta todo ok?

**Comment by karengrams** [comment]
¡Cierro el issue por inactividad! Cualquier duda que les surja, vuelvan a abrirlo. 

¡Saludos!
