### ISSUE TITLE
[BROKER - CACHE] - Dudas con el video/enunciado

### ISSUE THREAD

**Issue by Gonzalo-Avila** [sisoputnfrba/foro#1772]
Buenas!

Salió un nuevo video y nos trajo algunas dudas:

**1 -** En el video se dice que al liberarse una partición, se debe consolidar la misma, cosa completamente lógica que pensamos en un primer momento, pero que se contradice con otra parte del enunciado que es la frecuencia de compactación. Cito: 

> "Se deberá poder configurar la frecuencia de compactación (en la unidad “cantidad de búsquedas fallidas”). El valor -1 indicará compactar solamente cuando se hayan eliminado todas las particiones. 

O sea, que con este esquema, no tendría sentido compactar cuando se eliminen todas las particiones, porque si se consolidara cada vez que se elimina una partición, al final quedaría una sola partición y no habría nada que compactar. Lo preguntamos en el foro, y nos dijeron que las particiones permanecen aun cuando se vacía su contenido, consolidándose solo al momento de compactar. Link del issue donde nos respondieron esto: https://github.com/sisoputnfrba/foro/issues/1712

Esto lleva a otro punto, y es que en el video dice:

> Si el valor es -1, 0, o 1 se compacta siempre que se LIBERA una partición. 

Esto es completamente opuesto a lo que dice el enunciado. ¿Cual versión tomamos como referencia?

**2 -** En el video se dice que el algoritmo de Buddy System NO tiene compactación. Nuevamente, cito el enunciado: 

>El procedimiento de almacenamiento de datos será similar al de las particiones dinámicas, con la salvedad que la compactación se realizará de acuerdo a las reglas del propio algoritmo Buddy System. 

Según lo que vimos en la teoría, el algoritmo de Buddy System realiza compactación siendo que presenta fragmentación externa, solo que con menor frecuencia, por lo cual nosotros la implementamos. Nuevamente, ¿qué tomamos cómo referencia? ¿el video o el enunciado?

Gracias, saludos.

**Comment by nahuemazzeo** [comment]
Hola @Gonzalo-Avila. Como andas?

Con respecto al punto (1). Es correcto lo que nos marcas, es un error del vídeo por lo que deberías tomar lo que dice el trabajo practico. Vamos a liberar un post aclarando esto.
De todas maneras y pensando un poco esto en nuestra implementación, si un grupo hace caso a lo que dice el vídeo no es muy grabe ya que para el test que hagamos con el valor -1 podemos cambiar ese -1 por un valor super grande y debería tener el mismo funcionamiento.

Con respecto al punto (2). Entiendo que el issue lo liberaste pre confirmación de la errata del trabajo practico (versión 1.4). La idea fue sacar compactación ya que no tenia sentido realizarla en BuddySystem y dado a un análisis que hicimos post checkpoint ningun  grupo tenia un avance significativo que pudiera "molestar" quitarlo.

Saludos. Nahuel

**Comment by Gonzalo-Avila** [comment]
Buenas! Como va? 

Lo del punto 1: genial! Igual es como decís, no es muy grave porque cambiando el config se puede contemplar tranquilamente un comportamiento u otro. Nuestro mayor inconveniente es el tema consolidación: como en su momento esa aclaración del -1 nos hizo ruido, lo preguntamos en el foro y quedamos en que la consolidación se hace solo al compactar. O sea, que en un momento dado puedo tener muchas particiones contiguas vacías, y solo las juntaría al ejecutarse la compactación (está todo en el issue linkeado). ¿Qué hacemos con esto? ¿Lo cambiamos? ¿-1 implica no compactar nunca entonces?

Lo del punto 2: es cierto, lo cargamos antes de la versión. Y también es cierto que realmente no afecta mucho, en nuestro Buddy System la no compactación está contemplada poniendo -1 en la frecuencia de compactación (espero que esto no sea un problema). Nos dimos cuenta más tarde 😅 

Gracias! Saludos.

**Comment by nahuemazzeo** [comment]
Hola @Gonzalo-Avila 

Si, deberíamos ajustarlo. El objetivo de esto es que se consoliden cada vez que se libera una partición. Perdón si hubo alguna confusión en algún issue anterior. :pray:

Para probar el funcionamiento ya subimos algunos test para verificarlo con particiones dinamicas. El próximo Martes tendremos algunas para Buddy :muscle:

Saludos!!

**Comment by Gonzalo-Avila** [comment]
Ok! Entonces lo rehacemos. Un último check y no molesto más: 

1) Llega un mensaje.
2) Si no entra, vacío una partición según (LRU/FIFO) y consolido (si corresponde).
3) Veo si ahora entra. 

2) y 3) se ejecutan tantas veces como diga la frecuencia de compactación. Si es -1, se ejecutan hasta que el mensaje entre (o sea, nunca se pasa al paso 4), no se compacta)

4) Compacto la memoria y me fijo si ahora entra. Si no, vuelvo a 2)

¿Estaría bien?

**Comment by nahuemazzeo** [comment]
> Ok! Entonces lo rehacemos. Un último check y no molesto más:
> 
> Llega un mensaje.
> Si no entra, vacío una partición según (LRU/FIFO) y consolido (si corresponde).
> Veo si ahora entra.
> Los pasos 2) y 3) se ejecutan tantas veces como diga la frecuencia de compactación. Si es -1, se ejecutan hasta que el mensaje entre (o sea, nunca se pasa al paso 4), no se compacta)
> 
> Compacto la memoria y me fijo si ahora entra. Si no, vuelvo a 2)

Correcto

> Y otra cosa: si hay un tamaño mínimo de partición definido, y mi mensaje tiene un tamaño menor al mismo, yo tendría que crear una partición del tamaño mínimo definido y guardarlo ahí, ¿correcto? ¿Tengo que tener en cuenta el tamaño de las particiones vacías que puedan generarse al hacer esto? O sea:

Correcto

> Si tengo definida por config una partición mínima de 10 bytes, en una memoria de 15 bytes, y llega un mensaje de 5 bytes (por ejemplo), se va a crear una partición de 10 bytes para guardar el mensaje, y otra de 5 bytes, al final. Esta última nunca podrá usarse, y quedará inutilizada, pero no cumpliría ser igual o mayor al tamaño de partición mínima. ¿Ésto lo tenemos que contemplar? ¿O la consideramos como fragmentación externa y la aceptamos?

Se considera fragmentacion externa ya que nunca la vas a poder usar.

**Comment by EliasReuter** [comment]
Hola @nahuemazzeo 
Queríamos ver si se podría chequear esto ultimo con el issue #1765 porque no sabemos si considerar o no en nuestro algoritmo el tamaño de las particiones libres creadas cuando guardamos un mensaje nuevo.

**Comment by SofiCortes** [comment]
Hola @EliasReuter! Cuando guardan un mensaje nuevo debe alojarse en una partición que tenga por lo menos el tamaño mínimo que dice el archivo de configuración. La memoria que tengas libre, si es menor al tamaño mínimo de partición, la perdés por la fragmentación (no la podés asignar a ninguna partición).

**Comment by Gonzalo-Avila** [comment]
Perfecto! Ya nos quedó claro (a @EliasReuter y a mi), cerramos el issue. 

Muchas gracias! Saludos.
