### ISSUE TITLE
[GameCard] - Escritura de posiciones en bloques.

### ISSUE THREAD

**Issue by jdevergilio** [sisoputnfrba/foro#1773]
Buenas tardes,
Les hago una consulta, ya que si bien no encontré ningún requerimiento en el enunciado, entiendo que no es la manera mas eficiente a nivel manejo de archivos, pero creo que se estaría cumpliendo con el enunciado y no implicaría una carga muy mayor para este tipo de sistemas académicos. De todas manera me gustaría validarlo con ustedes.

Habría algún inconveniente si cada vez que agrego/elimino/actualizo alguna posición reescribo todos los bloques (archivos .bin de la carpeta Blocks) del Pokemon afectado? Siempre reutilizando los mismos bloques que el Pokemon tiene asignados (para evitar liberar y pedir nuevos bloques), y agregando en caso de que necesite mas bloques, o quitando en caso de que necesite menos bloques. 
De esta manera, me aseguro que los bloques no excedan nunca del tamaño máximo, y también me aseguro de no que no exista fragmentación interna en los bloques, quedando espacios sin utilizar.

Gracias,
Saludos.

**Comment by ntaboada** [comment]
Javier,

Creo que esa es la manera de encararlo. Al menos yo lo hice asi. Primero lees todos los bloques para ese pokemon, procesas la data, agregas/eliminas bloques (si la data no te entra en los bloques que tenes, pedis otro bloque, y si te sobra liberas el ultimo bloque ocupado por ese pokemon) y por ultimo escribis nuevamente todo.

**Comment by Nachiten** [comment]
Yo con lo que me dijo uno de los ayudantes de mi grupo voy a hacer lo siguiente que ya me dijeron esta bien:

Ponele que yo tengo que agregarle una linea a un pokemon q usa los bloques [1,4,610]. No importa que pokemon es para este ejemplo, cualquiera.

Entonces hago lo siguiente:
1) Abro el archivo (lo marco como open=Y) Leo cada uno de esos bloques y los appendeo(los pego juntos) en memoria.
2) Leo el archivo para entender lo que tengo q hacer. Hago las modificaciones necesarias. (borro o escribo lo q necesite).
3) Mido cuanto me quedó pesando todo el archivo (acordate que el metadata.bin te dice el tamaño real en bytes) entonces me fijo si necesito agregar o quitarle bloques a ese archivo en base a lo que hice.
4) Si necesito agregarle le agrego los bloques y si necesito quitarle tmb lo hago y los marco como libres u ocupados (en el bitmap) segun corresponda.
5) Pego todos los datos en los bloques que corresponda y cierro el archivo. (lo marco como open = N)

Espero te sirva esto. Saludos!

**Comment by jdevergilio** [comment]
Hola, si, lo tengo exactamente igual, y funcionando correctamente.
Veo que todos masomenos seguimos el mismo camino.
Gracias por sus comentarios.

slds.

**Comment by ntaboada** [comment]
Perdon que spammee este thread pero alguno puede chequear el otro thread que cree para lo del manejo del Open = Y y como sincronizar los procesos? Queria confirmar mas o menos si todos lo tienen armado como @jdevergilio me contesto.

**Comment by jdevergilio** [comment]
Creo que ayer puse un comentado en ese Issue.
Yo uso el campo OPEN del Metadata como semáforo del Pokemon.
Apenas se verifica la existencia del mismo, pongo OPEN en Y y con esto lo bloqueo para que nadie mas lo pueda utilizar, hago todas las modificaciones/lecturas de las posiciones necesarias, actualizo los bloques y el Size en el Metadata, y una vez que termino con todos los cambios, vuelvo a poner a OPEN en N, y con esto ya lo libero para que lo pueda tomar otro proceso que necesite hacer uso de ese Pokemon.

Espero te sirva.

**Comment by Nachiten** [comment]
> Creo que ayer puse un comentado en ese Issue.
> Yo uso el campo OPEN del Metadata como semáforo del Pokemon.
> Apenas se verifica la existencia del mismo, pongo OPEN en Y y con esto lo bloqueo para que nadie mas lo pueda utilizar, hago todas las modificaciones/lecturas de las posiciones necesarias, actualizo los bloques y el Size en el Metadata, y una vez que termino con todos los cambios, vuelvo a poner a OPEN en N, y con esto ya lo libero para que lo pueda tomar otro proceso que necesite hacer uso de ese Pokemon.
> 
> Espero te sirva.
> 

Ojo con eso. Recomiendo ampliamente que hagan sincronizacion con semaforos para justamente tocar ese metadata.bin. Porque solo usar ese open=y piensen el siguiente ejemplo:

Dos procesos llegan casi a la vez y ambos ven el open=n. Por lo tanto ambos ponen open=y. Ahi no solo que rompes la consigna hay dos procesos tocando el mismo archivo a la vez sino que generas condicion de carrera y eso es gravisimo.

Al usar semaforos mutex para tocar los archivos metadata.bin ahi te aseguras que dos procesos nunca puedan tocar el mismo a la vez. 
Entonces yo hago wait, toco el archivo metadata, signal. Y ahi me aseguro que cualquier otro que venga y lo toque despues lo va a ver como open=y y va a entrar en tiempo de espera configurado por config.
Hago todo lo que tenga que hacer con los bloques todas las modificaciones que necesito.
Cuando termino y voy a cerrar el archivo hago lo mismo. Wait mutex, toco el archivo marco open = n luego signal. Para cerrar el ciclo cuando cualquier otro proceso que venga de ahora en mas lo verá como que no está abierto y repetirá todos estos mismos pasos. 

Espero esto sirva, saludos

**Comment by jdevergilio** [comment]
Tenés razón, no me había dado cuenta de esa posibilidad.
Gracias por el aporte!

**Comment by ntaboada** [comment]
@nachiten en otro issue viejo yo lei que decian de usar los ayudantes el open como un semaforo. No entiendo que utilidad entonces tiene hacer la validacion de chequear si OPEN = Y, directamente pones un semaforo y listo. Entiendo y estoy de acuerdo en lo que decis, pero me parece al dope entonces hacer esa validacion

**Comment by ntaboada** [comment]
El issue en cuestion es este:

https://github.com/sisoputnfrba/foro/issues/1716

**Comment by Nachiten** [comment]
> @nachiten en otro issue viejo yo lei que decian de usar los ayudantes el open como un semaforo. No entiendo que utilidad entonces tiene hacer la validacion de chequear si OPEN = Y, directamente pones un semaforo y listo. Entiendo y estoy de acuerdo en lo que decis, pero me parece al dope entonces hacer esa validacion

Habria que preguntar a algun ayudante. Sinceramente ahora me hiciste entrar en la duda.

**Comment by ntaboada** [comment]
@jdevergilio no, porque de otro modo se puede plantear lo que yo puse en mi otro issue. Armar una lista/mapa de semaforos, donde la key sea el pokemon y el value el semaforo. Buscas el pokemon que estas por procesar y obtenes el semaforo. Osea se puede implementar de esa manera (en mi otro issue lo explico mejor). El tema es que si haces eso, para que tenes el OPEN? para que lo evaluarias? esta re colgado

**Comment by ntaboada** [comment]
el issue que cree ayer preguntando justamente todo esto: 

https://github.com/sisoputnfrba/foro/issues/1771

**Comment by jdevergilio** [comment]
Por lo que ví (no lo leí en profundidad), es lo que te comenté, tendrías que tener un semáforo por cada Pokemon que tengas en tu Tall Grass.
En cambio, usando el OPEN + un solo semáforo que impidan que dos o mas procesos accedan a archivos del tipo metadata al mismo tiempo, podrías gestionar todos los pokemones que desees.

**Comment by Nachiten** [comment]
> el issue que cree ayer preguntando justamente todo esto: 
> 
> https://github.com/sisoputnfrba/foro/issues/1771

Podrias re abrir el hilo asi lo seguimos ahi? Gracias

**Comment by ntaboada** [comment]
Esta abierto, sigamosla ahi si quieren @Nachiten @jdevergilio

**Comment by iago64** [comment]
Buenas buenas!
Veo que se divirtieron bastante charlando sobre el tema de los files en Tall-grass
Vamos en orden:
1.- El hecho de levantar el archivo completo a memoria, calcular todo lo que tengan que calcular y después bajarlo a los archivos de bloques (agregando o eliminando si hace falta) esta perfecto 😄 
2.- El tema del flag de Open, si, eso les puede dar un flag claro, el tema como bien comentaron es la posible condición de carrera al tocar ese mismo archivo de metadata (que no es lo mismo que operar con todos los bloques)
Ahí esta bien la idea de agregar un semáforo del metadata para que 2 hilos no hagan cambios sobre el metadata al mismo tiempo, una vez cambiado el metadata no deberían tener mas problemas ya que 2 hilos no van a ir a modificar el mismo set de bloques 😉 

Saludos.-

**Comment by iago64** [comment]
Buenas? Si yo de nuevo por aca, como venimos con las dudas @jdevergilio quedo algo pendiente?

**Comment by jdevergilio** [comment]
@iago64 , como estas?
Estuve releyendo tus comentarios, y con el último comentario del issue #1771, no me termina de quedar claro si debemos usar un Mutex global para acceder al metadata, o si cada Pokemon debe tener su propio mutex.
Yo entiendo que es uno global, para que dos hilos no puedan acceder a los metadatas en simultaneo (sin importar si son del mismo o de distinto Pokemon). Me lo podrías confirmar?

Te pongo un ejemplo de la solución que propongo:

Supongo que entra un NEW Pikachu y un NEW Charmander en simultaneo.

Entra Pikachu, bloquea el mutex mientras accede su Metadata (cambia a OPEN si es necesario), en este instante Charmander quiere leer su Metadata también, pero está bloqueado esperando que Pikachu termine de leer su metadata.
Pikachu termina de leer su metadata, libera el Mutex  (Si está OPEN=Y, igual libera el semáforo y va a la espera hasta volver a consultar), y ahí Charmander se desbloquea para seguir su ejecución (bloquear mutex, leer metadata, desbloquear mutex).

En resumen, 2 o mas hilos no pueden acceder a los metadatas al mismo tiempo, independientemente de si quieren tratar al mismo Pokemon, o a Pokemones distintos.

Es correcta mi interpretación?

Mil gracias por la paciencia!

**Comment by ntaboada** [comment]
Sabes que el ultimo comment de a mi tambien me confundio mas jaja. Pense que era el unico.
Pero exacto queria confirmar lo mismo que publico recien @jdevergilio. Esa es la ultima duda que tengo.

Muchas gracias @iago64

**Comment by iago64** [comment]
Aloha!
Chicos por favor **avisen que algo no quedo claro** así veo de explicarlo de otra forma 😄 

Voy a tratar de explicarlo con un ejemplo, vamos a tener
/pikachu/metadata.bin
/charmander/metadata.bin

Idealmente 2 hilos no deberían poder acceder al **mismo** archivo a la vez (ya sea /pikachu/metadata.bin o /charmander/metadata.bin), con lo cual si llegan 2 NEW PIKACHU por ejemplo, deberia entrar 1, setear OPEN en Y y salir y despues el otro al entrar se encuentra con OPEN en Y, lo informa y espera el tiempo necesario.

Ahora si tienen 2 hilos y uno quiere acceder a /pikachu/metadata.bin y el otro a /charmander/metadata.bin ahi no debería haber inconvenientes, ya que son archivos distintos y por lo tanto deberían poder entrar los 2 a la par.

Saludos.-

**Comment by jdevergilio** [comment]
O sea, debemos ir incorporando semáforos a medida que se agreguen a nuestro Tall Grass Pokemones.
Gracias!

**Comment by iago64** [comment]
Si, o pueden ir agregándolos a medida que les llegan operaciones (NEW, GET o CATCH) contra esos archivos

**Comment by ntaboada** [comment]
Ok, eso confirma que un mutex global no serviria. Un mutex por metadata/pokemon seria la solucion. 
Lo que no entiendo entonces es para que tenemos el flag open/closed en un metadata... no estariamos haciendo dos chequeos? Primero para ver si el metadata de ese esta open/closed (por ende si esta open va a bloquear el hilo) y despues con el semaforo mutex..

**Comment by iago64** [comment]
@ntaboada Tienen el flag de Open porque la idea es que pueda llegar un hilo nuevo, haga la consulta y se encuentre que el archivo esta abierto (si tienen 1 solo semaforo gigante se van a clavar esperando y nunca van a informar que estaba abierto el archivo).

**Comment by Phiiliip** [comment]
@iago64 Buenas noches, releyendo el thread nos surgió la duda:

Utilizar unicamente la consulta hacia el flag OPEN puede llegar a dar un caso o es lo suficientemente improbable como para no tomarlo en cuenta? 

Saludos

**Comment by iago64** [comment]
@Phiiliip como va?
Utilizar únicamente el flag de OPEN tiene como contra que podes llegar a tener una condición de carrera al momento de trabajar sobre el archivo, puede que nunca pase nada, como puede que al momento de las pruebas justo 2 hilos quieran operar sobre el archivo y bueno... las cosas no salgan del todo bien.
Si me preguntas las probabilidades, tengo que citar algo que siempre digo en la intro del TP, testeandolo nunca les pasa hasta que están en la entrega, ahí todo lo que puede fallar va a fallar. Es algo así como la Ley de Murphy en su máxima expresión 😢 

Saludos.-

**Comment by enogueiras** [comment]
Que buen hilo este, aprovecho para hacer una consulta, en los casos que me llega para misma posicion otro new_pokemon, habria que sumar la cantidad a la actual, ¿eso con el tema de los bloques ya ocupados como seria?

**Comment by iago64** [comment]
Buenas @enogueiras !
A que te referis con el tema de los bloques ocupados? el ejemplo rápido que se me ocurre es que si por ejemplo tenes:
1-1=50
2-2=9
3-3=1457
y te llega por ej un new con 2-2 y 1000 de cantidad pasas a tener:
1-1=50
2-2=1009
3-3=1457
Lo que puede hacer que tengas que reservar algún bloque nuevo y tengas que reescribirlos todos para guardar la info, pero a priori no debería complicarles mas que eso.

Saludos.-

**Comment by enogueiras** [comment]
es valido reescribir los bloques ya ocupados si el pokemon no los libero?

**Comment by iago64** [comment]
Son los bloques del mismo archivo, podes reescribirlos siempre que lo necesites, y como tenes el flag de OPEN, nadie mas debería ir a meter los garfios hasta que vos termines 😉

**Comment by karengrams** [comment]
¡Alo!

¿Quedo la duda resuelta? ¿Cerramos el issue? 

¡Saludos!

**Comment by Phiiliip** [comment]
Buenas, por mi parte si, ya estamos viendo de implementar una lista global de semáforos para leer/escribir archivos

Gracias!

**Comment by karengrams** [comment]
Cierro el issue por inactividad, cualquier cosa que haya quedado suelta, reabranlo sin problema. ¡Saludos! :)
