### ISSUE TITLE
Sobre Particiones Dinámicas con compactación y la reserva de la porcion de memoria.

### ISSUE THREAD

**Issue by plbruniard** [sisoputnfrba/foro#1774]
En esta nueva versión del enunciado persiste el mandato inicial que dice textualmente que, en el "agente", cuando se trate de Particiones Dinámicas con compactación:

"**...se reservará una porción de memoria por cada valor almacenado, del **tamaño exacto** de dicho valor.**"

Esta frase del enunciado denotaría que nunca habría **fragmentación** interna ya que hay que reservar **exactamente** la misma cantidad de memoria que el dato a guardar. 

Me resultaría imposible cumplir con este **mandato** cuando la longitud del valor a almacenar fuera **inferior** al **tamaño mínimo de la partición** ya que, si tenemos un mensaje de longitud cuatro y no podemos reservar menos de dieciséis bytes, por ejemplo, no podríamos nunca reservar "una porción de memoria del **tamaño exacto** de dicho valor (cuatro)".

Me parece ver una cierta contradicción ahí, que solo podríamos resolver con fragmentación interna, reservando un tamaño de memoria igual al de la partición_mínima y que no sería **...el valor exacto de dicho valor...**.

Por supuesto que, si el tamaño de la partición mínima fuera cuatro o menor, creo que no habría ninguna posibilidad de violar el mandato referido ya que no hay ningún mensaje en el TP que sea de longitud inferior a cuatro pero, en varios issues que he leído se dice claramente que el tamaño de la partición mínima puede llegar a ser configurado con **cualquier número entero**, empezando por uno hasta el tamaño total de la memoria.

Quizás me estuviera equivocando en mi análisis pero me parece que, teniendo en cuenta, además, el parrafo que dice, refiriéndose a los dos esquemas a implementar: 

"...Para **ambos**, se definirá por parámetro del Broker el **tamaño mínimo de partición** y un tamaño máximo (que será el de toda la memoria)..."

Creo que sería imposible **evitar** la fragmentación interna de las particiones dinámicas cuando el dato a grabar **sea** inferior al tamaño de la partición mínima.

¿Sería posible que estuviéramos frente a una excepción?

En varios issues comenté este tema intentando que se me respondiera sobre el mismo pero no he recibido ninguna mención al mismo.

Muchas gracias por su atención y saludos.

**Comment by ncoen97** [comment]
Buenas.
Me parece que quedó contestado [acá](https://github.com/sisoputnfrba/foro/issues/1740#issuecomment-643700230).
Teniendo esa respuesta en mente, que dudas te siguen quedando?

**Comment by plbruniard** [comment]
> Buenas.
> Me parece que quedó contestado [acá](https://github.com/sisoputnfrba/foro/issues/1740#issuecomment-643700230).
> Teniendo esa respuesta en mente, que dudas te siguen quedando?

Digo que la directiva del enunciado que reza:  "...**se reservará una porción de memoria por cada valor almacenado, del tamaño exacto de dicho valor**." , sería imposible de cumplir y no estaría siendo coherente con lo que el TP está pidiendo sino que estaría fuera de lugar.

Esa sola linea, es la que ha generado casi todas las controversias en la modelación de la caché con el esquema de particiones dinámicas y no reflejaría lo que están pidiendo que deberíamos hacer.

Por ejemplo, si el tamaño mínimo de las particiones fuera sesenta, creo que ningún mensaje podría cumplir esa directiva porque no habría mensajes de igual o mayor longitud que sesenta.

Me parece que siendo todos aspirantes a ingenieros, es importante intentar corregir una directiva de un enunciado que no se corresponde con lo que se tiene que hacer,  para ayudar a los que están llevando a cabo el TP, junto con otras varias materias, de forma que no tenga que perder el tiempo recorriendo todos los issues para comprender lo que el enunciado quizás debiera dejar claro desde su texto. 

Saludos y muchas gracias por la atención.

**Comment by iago64** [comment]
@plbruniard Como siempre decimos, los TPs no pueden reflejar 100% la teoría, ya que en muchos casos los mismos requieren que tengamos ciertas "licencias" para poder hacer que los mismos sean
- Mas simples de implementar
- Mas fáciles de probar
- Mas exactos a la hora de documentar las pruebas.
- etc, etc

No te olvides que si quisiéramos reflejar la teoría al 100% tendrías también por ejemplo que hacer que el team libere los pokemons que atrapa luego de finalizar la ejecución, o tendríamos que implementar FUSE y manejar un archivo binario para el FS, tendríamos que agregar un "Sistema Operativo" que consuma ciclos de CPU para planificar y podríamos seguir con una larga lista de etc que no vienen al caso.

El objetivo puntual que perseguimos al poner el tamaño mínimo de partición es hacer mas uniformes las pruebas y de hecho fue puesto un par de lineas antes en el enunciado:
"Se implementarán dos esquemas de Administración de Memoria: Particiones dinámicas con compactación, y Buddy System (descritos más adelante). Se elegirá por archivo de configuración cual estará activa al iniciar la caché. **Para ambos, se definirá por parámetro del Broker el tamaño mínimo de partición y un tamaño máximo (que será el de toda la memoria).**"

Por ultimo (aunque este punto es mas para una charla de café que para el issue), es la capacidad de cualquier ingeniero el poder resolver los inconvenientes con los que se topa lo que lo distingue del resto. Esta capacidad generalmente involucra el poder recolectar la información necesaria para resolver el inconveniente, con lo cual, no consideraría el buscar en otros issues una perdida de tiempo o mismo, que como fue el caso alguien cite una fuente donde esta la respuesta a la duda.

Saludos.-

**Comment by plbruniard** [comment]
> @plbruniard Como siempre decimos, los TPs no pueden reflejar 100% la teoría, ya que en muchos casos los mismos requieren que tengamos ciertas "licencias" para poder hacer que los mismos sean
> 
> * Mas simples de implementar
> * Mas fáciles de probar
> * Mas exactos a la hora de documentar las pruebas.
> * etc, etc
> 
> No te olvides que si quisiéramos reflejar la teoría al 100% tendrías también por ejemplo que hacer que el team libere los pokemons que atrapa luego de finalizar la ejecución, o tendríamos que implementar FUSE y manejar un archivo binario para el FS, tendríamos que agregar un "Sistema Operativo" que consuma ciclos de CPU para planificar y podríamos seguir con una larga lista de etc que no vienen al caso.
> 
> El objetivo puntual que perseguimos al poner el tamaño mínimo de partición es hacer mas uniformes las pruebas y de hecho fue puesto un par de lineas antes en el enunciado:
> "Se implementarán dos esquemas de Administración de Memoria: Particiones dinámicas con compactación, y Buddy System (descritos más adelante). Se elegirá por archivo de configuración cual estará activa al iniciar la caché. **Para ambos, se definirá por parámetro del Broker el tamaño mínimo de partición y un tamaño máximo (que será el de toda la memoria).**"
> 
> Por ultimo (aunque este punto es mas para una charla de café que para el issue), es la capacidad de cualquier ingeniero el poder resolver los inconvenientes con los que se topa lo que lo distingue del resto. Esta capacidad generalmente involucra el poder recolectar la información necesaria para resolver el inconveniente, con lo cual, no consideraría el buscar en otros issues una perdida de tiempo o mismo, que como fue el caso alguien cite una fuente donde esta la respuesta a la duda.
> 
> Saludos.-

Hola @iago64.

Me doy cuenta de que no hay una sintonía entre la naturaleza de mi issue y lo que amablemente y muy cordialmente me contestas.  Coincido con la mayoría de lo que expresas y, si bien con algunos matices, lo encuentro muy razonable pero, no responde a lo que estoy comentando ni le da solución. Voy a cerrar el issue y desistiré de intentar obtener una respuesta acorde porque me doy cuenta de que es inútil.  Esto es parte del aprendizaje.

La educación es un fenómeno instantáneo, continuo e inevitable. El problema suele radicar en que no siempre va en la dirección en la que se cree que debe ir sino en la que va.

Saludos y muchas gracias por todo.

**Comment by iago64** [comment]
@plbruniard Aunque cierres el issue no quería dejar pasar el punto en cuestión, ya que tu pregunta inicial es mas que válida y mi mensaje fue en pos de explicar el por que lo que es estricto en la teoría no necesariamente tiene por que serlo en el TP (por ejemplo decir que el esquema de particiones dinámicas no posee fragmentación reserva el tamaño exacto).
Justamente la fragmentación interna va a estar presente (o no) y es parte de las cosas _con las que queremos que se topen_ para que lo charlemos en el coloquio y por lo que a priori puede terminar sonando como una contradicción, pero persigue un objetivo de análisis y comprensión. 

_Un ejemplo_ para explicar por que la fragmentación interna puede darse o no en particiones dinámicas es tan simple como si para todos las pruebas donde tengamos particiones dinámicas les digamos que el tamaño mínimo de partición sea 1, ahí podrías cumple con el no reservar de mas ya que reservarías lo justo para el mensaje y ahí no existiría la contradicción que citas, mientras que si por ejemplo como citas, ponemos 60 bytes, posiblemente salvo algún caso muy especifico de LOCALIZED, todos los demás mensajes si sufrirían de fragmentación.

Aunque parezca algo bastante trivial, el hecho de manejar particiones dinámicas (como también a veces pasa en segmentación) no es algo tan fácil de aplicar en la practica ya que requiere que se maneje aritmética de punteros y no es algo que todos los alumnos dominen bien a la hora de cursar la materia, por lo que a veces son necesarias este tipo de aclaraciones.

Lamento mucho que sientas que es inútil el obtener una respuesta acorde, ya que es parte del intercambio de ideas el buscar las respuestas, y es nuestra meta como ayudantes el brindarles las respuestas necesarias para que puedan completar el trabajo practico, puede que no siempre sean las adecuadas y por lo tanto tendremos como veras en otros issues varios idas y vueltas, pero eso forma parte de la necesidad de explicar los conceptos, aclarar las ideas y por consiguiente brindar la ayuda necesaria, claro esta que nuestras respuestas tienen ciertos limites y que entiendo pueda ser este el caso y que la respuesta que consideres acorde este fuera de lo académico.

Saludos.-

**Comment by plbruniard** [comment]
Estimado @iago64 , ya que te has tomado el trabajo de escribirme tan larga respuesta, me tomaré el trabajo de responderte el motivo de mi sentimiento de inutilidad sobre el issue.

Si hablamos en términos absolutos, 'la **única forma** de que, en el esquema de particiones dinámicas **no** existiese la **fragmentación interna** sería cuando el **tamaño mínimo de partición** fuera **uno** o cuando el **tamaño mínimo de partición** fuera **igual o menor** al tamaño del **menor mensaje** que sería cacheado. En el TP la longitud del menor mensaje es cuatro. O sea que si 1, 2, 3 o 4 fueran los unicos valores permitidos para el  tamaño mínimo de partición en el esquema de particiones dinámicas del TP, nunca habría fragmentación interna y se podría cumplir con la directiva del 'tamaño exacto'.

Estas dos características las vengo mencionando en todos mis comentarios anteriores en los que intervengo debido a las preguntas que se formulan sobre **como resolver** la dicotomía que manifiesto entre "reservar exactamente la cantidad de memoria necesaria"  y "respetar el tamaño mínimo de partición". Son varias mis intervenciones al respecto lo que debería servir para que, sin coloquio de por medio, quedara claro que entiendo el problema.

No veo ninguna propuesta del Enunciado que se contradiga con la teoría. El uso de longitudes de particiones mínimas es una técnica teórica que parte del presupuesto de que habrá una distribucion de longitudes diferentes de los mensajes cacheados y, la variación de la longitud de la partición mínima, si bien introduce fragmentación interna, permite variar el overhead de la consolidación y de la compactación. En este tipo de esquemas de almacenamiento, hay una relación entre 'el tamaño total de la memoria', el 'tamaño mínimo de la partición' y el 'promedio ponderado de las longitudes de los datos a cachear' que permite determinar cual es el 'tamaño de la partición mínima' que optimizará el overhead de los servicios de consolidación y compactación.

Me llama la atención que en tus respuestas utilices exactamente los mismos argumentos que yo expreso en todas mis intervenciones, (que te invito a leerlas) para justificar que la frase: "**...se reservará una porción de memoria por cada valor almacenado, del tamaño exacto de dicho valor.**" no estaría **de más** cuando yo  los uso para lo contrario. Es como que estamos hablando de lo mismo pero, increíblemente, llegamos a conclusiones diametralmente opuestas. Tu dices que esa frase fue incluida para que: 'aprendamos'. Yo digo que, sin aseverar que pudiese existir alguna otra intención distinta a la de que 'aprendamos' lo que se consigue es: 'distraer y perturbar'. Como si el TP no tuviera ya grandes niveles de dificultad que no fueran suficientes como para no poder evaluar nuestra capacidad de resolverlo.

Para desarrollar un trabajo práctico de la envergadura del que estamos hablando, en un contexto de tercer año de la carrera, cuando al mismo tiempo estamos cursando otras materias que nos consumen mucho tiempo (lo más valioso de la tierra ya que el tiempo está limitado y no se puede recuperar), la idea es que los enunciados debieran 'ayudarnos' a resolver el TP.

Puedo entender que, en un principio, cuando se formuló el TP, esa frase haya podido resultar coherente y sana para ayudarnos a resolverlo pero, a esta altura, en la versión cuatro del enunciado, aspiraba a que se la suprimiera por perturbadora y no conducente o que se la reemplazara por otra quizás menos disruptiva, como por ejemplo:

"...se reservará una porción de memoria por cada valor almacenado, del tamaño exacto de dicho valor **siempre que su longitud no fuera menor que el tamaño mínimo de la partición, en cuyo caso se reservará _ese valor_**..."

Podría seguir comentando sobre los "off-topic" que tiene  tu respuesta ya que en varios de ellos tengo matices aunque, como ya te dije, en la mayoría coincido ampliamente contigo.

La respuesta que se me dió y que cito textualmente: **"Teniendo esa respuesta en mente, que dudas te siguen quedando?"** no me parece del tono adecuado a una relación 'educador -> educando'.  Yo me pregunto si quien me respondió eso, entendió lo que mi issue está planteando. Es evidente que al problema lo entiendo perfectamente, lo analizo correctamente y mi planteo está basado en eso y no en una duda.

No sigo escribiendo porque mañana tengo un parcial y no creo que el tema sea tan importante como para que sigamos utilizando nuestro valioso tiempo en conversar sobre el mismo.

Saludos y gracias por todo.

**Comment by iago64** [comment]
Estimado @plbruniard como no puedo dejar pasar el hecho de que invirtiera tiempo en contestarme y por lo tanto me veo en la obligación de responder algunos aspectos.

La respuesta que dio Nicolas no me parece que sea en un tono inadecuado, de hecho es muy comun el hecho de citar otros issues donde se resolvió una duda similar (o a veces la misma duda), pero entiendo que aca el punto no radicaba en una duda per se.

Respecto al punto del enunciado y del desarrollo del trabajo practico, es interesante lo que planteas, ya que en una media de 400 alumnos por cuatrimestre, es casi imposible hacer un enunciado que abarque todas las posibles variantes de consultas, por eso que tratamos de asegurarnos de que el mismo sea lo mas claro para la mayoria y de ahi que siempre tenemos las mejores intenciones. Algunos cuatrimestres es mas facil y los enunciados son mas claros, otros no tanto, te invito a que cuando gustes pases por la sección de [TPs anteriores](https://www.utnso.com.ar/recursos/tps-anteriores/) del blog donde tenemos trabajos prácticos desde el año 2004.
No obstante en todos los cuatrimestres nos encontramos con situaciones de alumnos que se frustran, se confunden e incluso se enojan con los ayudantes y llegan a increparnos por motivo del trabajo pratico, porque asumen que nuestro objetivo es confundirlos y hacer que no aprueben, cuando todos los que formamos parte de la catedra lo unico que queremos es que adquieran los conocimientos y la integración de los mismos que se requieren para aprobar la materia.

Entiendo que todo el objetivo de este issue fue el de proponer una mejora en la redacción del enunciado, lo cual ciertamente es muy noble, pero que se vio opacada por la forma poco clara de expresar dicha solicitud, ya que la diferencia entre comentar el cambio con un mensaje del estilo de:
- En base a lo que vimos en los siguiente issues (listado de issues) me parece que la frase se podria corregir de la siguiente manera "...se reservará una porción de memoria por cada valor almacenado, del tamaño exacto de dicho valor siempre que su longitud no fuera menor que el tamaño mínimo de la partición, en cuyo caso se reservará ese valor..."

A decir
- Yo me pregunto si quien me respondió eso, entendió lo que mi issue está planteando

Ya que en la primera frase queda claro el planteo y el objetivo de la idea, mientras que en la segunda no solo no expresa con claridad la idea si no que ademas se puede llegar a tomar como un ataque hacia el ayudante ya que se pone en duda su capacidad de entendimiento y no asumiento que la idea pudo no ser expresada de forma clara.
Durante todo el tiempo que fui alumno, siempre busque tener un gesto de humildad y siempre asumi que los ayudantes tienen las mejores intenciones y cuando no tuve las respuestas que resolvian mis inquietudes siempre pense que podia estar expresandome de una forma poco clara y que por ello los ayudantes no estuvieran entendiendo mi planteo.

Por ultimo, para mi el invertir tiempo en aclarar las dudas de los alumnos con respecto a la materia es la mejor utilización que le puedo dar al tiempo, ya que por algo decidi seguir formando parte de la comunidad educativa aun luego de mas de 5 años de haberme graduado.

Saludos.-

**Comment by ncoen97** [comment]
Buenas @plbruniard, quiero hacerte una aclaración con respecto a lo siguiente:

> Yo me pregunto si quien me respondió eso, entendió lo que mi issue está planteando. Es evidente que al problema lo entiendo perfectamente, lo analizo correctamente y mi planteo está basado en eso y no en una duda.

Me parece que en tu pregunta inicial del issue en ningún momento llegas a hacer un planteo con respecto a tu aspiración a que se "suprimiera/reemplazara el requerimiento por perturbador/no conducente". Como ayudante de la materia, para poder intentar encontrar las respuestas que los alumnos requieren, es sumamente importante poder entender a fondo cuál es el concepto que no se está entendiendo, por lo tanto yo no puedo asumir que entendiste y analizaste correctamente el problema si lo único que tengo a mi disposición es una pregunta en texto (tengamos en cuenta que el 93% de la comunicación entre personas es no verbal) en la que solamente se repite el hecho de que es imposible cumplir al 100% ambos requerimientos.
Si realmente esa era tu intención, por qué no plantearlo directamente? Así te podes asegurar de que "el que responde entendió lo que tu issue está planteando".
Para cerrar (porque yo también tengo que trabajar y estudiar para parciales), quiero aclarar que como dice dami, nuestro objetivo acá no es imponer un trabajo practico confuso y complejo porque somos malvados. De hecho durante el cuatrimestre (y me pasó también como alumno) hubo distintos planteos con respecto a la redacción o a los requerimientos del trabajo practico que fueron tomados como válidos y se hicieron los cambios necesarios.
Dicho esto espero que los planteos que vengan a futuro sean claros y objetivos y que también tengan en cuenta que los ayudantes podemos equivocarnos, no entenderlos, o pifiarla de vez en cuando (esperemos que sea la menor cantidad de veces posible).
Saludos!

**Comment by plbruniard** [comment]
Estimado Nicolás, he leído tu respuesta. @ncoen97 

Es mi opinión que estamos agregando off-topics al issue y no voy a aburrir a quienes nos leen por temas que se podrían resolver en otro lado, dejando este foro para temas más técnicos.

Pero no puedo dejar sin aclarar que siempre me limito a 'decir lo que digo', y nunca 'digo lo que no he dicho'. 

Hay varios adjetivos agregados en tu respuesta que nunca han estado en mis respuestas. Por ejemplo, **'malvados'** es algo que no sé el porqué lo traes a colación ya que nunca he, ni siquiera sugerido, que los ayudantes lo fueran. 

Te invito a leer mis issues y verás que son todas muy cuidadosas y respetuosas con respecto a las personas. No tengo ninguna intención de ofender a nadie sino todo lo contrario. Soy un defensor del respeto por las personas. Trato siempre de hacerle honor al dicho: **Lo cortés no quita lo valiente**. Creo que el plantear un tema no puede ser interpretado como una falta de respeto sino como que se puede ver un tema desde distinto aspecto o enfoque, aunque haya quienes crean que, el solo planteo de una diferencia implica un ataque personal. A veces cuestiono cosas que tienen que ver con cierta actitud o acción de alguna persona pero, nunca adjetivo o coloco en alguna 'bolsa' a nadie. 

También te invito a que leas mi comentario que se encuentra 'inmediatamente encima' del lugar al que me envías a leer en tu contestación para que notes que yo había leído todo ese comentario, al que estoy suscrito y del que soy participante.

Dices también que: "**-Me parece que en tu pregunta inicial del issue en ningún momento llegas a hacer un planteo con respecto a tu aspiración a que se "suprimiera/reemplazara el requerimiento por perturbador/no conducente"...**"

Es que por lo general, cuando participo en un foro como alumno nunca planteo la supresión o reemplazo de nada puesto que, como soy el que está aprendiendo, es muy factible que me pueda encontrar en un error de apreciación debido a mi desconocimiento o ignorancia sobre el tema específico por lo que suelo utilizar el **modo potencial** y expresiones adverbiales como:  "**¿es posible..?**, **me parece ver...**, **creo que...**, ¿Sería posible...?

Si, es posible que no lo dijera directamente pero, si ahora lo vuelves a leer, creo que podrás ver que, si bien no lo denoto "directamente", la connotación es clara cuando digo: **¿Sería posible que estuviéramos frente a una excepción?**, por ejemplo.

Te mando mis respetos.

**Comment by plbruniard** [comment]
> Estimado @plbruniard como no puedo dejar pasar el hecho de que invirtiera tiempo en contestarme y por lo tanto me veo en la obligación de responder algunos aspectos.
> 
> La respuesta que dio Nicolas no me parece que se...

Estimado Damián, @iago64 

Voy a contestar dos puntos de tu respuesta ya que, a pesar de que son off-topic, se me ocurre pensar que pudiera haber alguna malinterpretación de lo que he escrito.

Hay una gran diferencia entre decir que:  "**algo no se entendió**" y decir que: "**a quien no entendió se le pone en duda su capacidad de entendimiento**".  Con ese criterio, cuando un profesor pregunta en clase: ¿Alguien no entendió o tiene alguna duda?, ¿estaría poniendo en duda la capacidad de entendimiento de los alumnos?; ¿los estaría atacando...? Seguramente que no.

Yo no he atacado a nadie, sino que he puesto de manifiesto mi opinión de que **no se entiende lo que he manifestado en el issue**.  Te pido que vuelvas a leer lo que he escrito, seguramente verás que lo que hago es una pregunta, a la cual se le puede responder por si, por no o por lo que se quiera responder. No se afirma nada. 

A veces, ciertas circunstancias por las que uno está pasando en el momento en que se leen las comunicaciones, tiñen de distinta forma expresiones que pudieran ser neutras vistas desde un lado imparcial y animosas vistas desde un lado subjetivo.

Vuelvo a leer la respuesta de Nicolás @ncoen97  y me pregunto ¿por qué me pareció de un tono inadecuado?

La cito textualmente: "**Teniendo esa respuesta en mente, que dudas te siguen quedando?**"

Ahora que la releo, le encuentro que pudiera significar algo así como: 

**Te cito una explicación en otro issue que pudiera resolver tus dudas y, si aún te queda alguna otra, no dudes en preguntarme.** 

En ese momento que la leí, me pareció que tenía otro tono y no me gustó. Lo siento. Mala mía.

Es posible que Nicolas no se hubiera dado cuenta de que yo había participado en ese issue y que estaba suscrito por lo que ya '**tenía esa respuesta en mente**'.

Creo también que estamos todos muy susceptibles, en especial yo, debido a que esta situación en las que nos ha metido esta pandemia, siendo trabajador esencial, me obliga a viajar todos los días hasta el domicilio de mi trabajo, sorteando todos los impedimentos que los controles de transito imponen, con la perdida del irrecuperable tiempo y, al mismo tiempo, me impide (nos impide) concurrir a la facultad para tomar clases de soporte presenciales, debiendo tomar estos medios como la prácticamente única fuente de información oficial a la hora de plantear una duda.

Si alguno de ustedes se ha sentido ofendido o molesto, por algo de lo que yo he escrito, les pido disculpas a pesar de no haber sido esa mi intención.

Ahora, finalmente, me gustaría, ya que hemos escrito tanto, que me dieran alguna opinión personal sobre **si la frase del enunciado debiera ser suprimida** o **modificada de acuerdo con mi sugerencia** u **otra**.

Saludos a los dos y lamento lo ocurrido.

Pedro Luis Bruniard
