### ISSUE TITLE
La VM no me toma el layout de mi teclado USA 

### ISSUE THREAD

**Issue by plbruniard** [sisoputnfrba/foro#1775]
Hola:

Si bien he buscado en estos issues y en Internet la forma de configurar Ubuntu para que me tome el layout del teclado de mi notebook, no he hallado ninguna mención a esto en el git de SisOp y, todo lo que leí en Internet no se corresponde con la versión de Ubuntu instalada en la VM y no quiero instalarle ni actualizarle nada para no correr el riesgo de que pudiera dejar de funcionar lo que preciso para desarrollar el TP.

El que no me tome las teclas correspondientes es una dificultad que me está retrasando mucho a la hora de programar puesto que el teclado responde de una forma cuando estoy en Windows y de otra cuando estoy en Linux por lo que se me hace muy complicado trabajar en forma productiva y eficiente.

Quisiera saber si alguien pudiera darme una mano para configurar correctamente el Ubuntu, de la VM, de forma tal que cuando oprima en mi teclado una tecla que tiene dibujado un corchete, el sistema me tomara un corchete y no un ñuflo.

Muchas gracias y saludos.

**Comment by papa-caco** [comment]
Hola Pedro, yo también tuve ese problema cuando tuve que cambiar de compu. Comparto este instructivo para cambiar la distribución del teclado en la VM con interfaz gráfica. Espero te sirva de ayuda,
[Agregar Agente de distribución de teclado en Configuración de Panel.pdf](https://github.com/sisoputnfrba/foro/files/4792752/Agregar.Agente.de.distribucion.de.teclado.en.Configuracion.de.Panel.pdf)
Saludos,

**Comment by mgarciaisaia** [comment]
A mí lo que me funciona en la Server (no recuerdo qué onda en la Desktop) es [este comando](https://askubuntu.com/a/765062):

```
sudo dpkg-reconfigure keyboard-configuration
```

Ahí te muestra una ventanita para elegir qué distribución usar. Lo que _creo_ que no tiene es una forma de auto-detectar tu configuración (onda, necesitás saber cuál es la que tenés).

**Comment by plbruniard** [comment]
> Hola Pedro, yo también tuve ese problema cuando tuve que cambiar de compu. Comparto este instructivo para cambiar la distribución del teclado en la VM con interfaz gráfica. Espero te sirva de ayuda,
> [Agregar Agente de distribución de teclado en Configuración de Panel.pdf](https://github.com/sisoputnfrba/foro/files/4792752/Agregar.Agente.de.distribucion.de.teclado.en.Configuracion.de.Panel.pdf)
> Saludos,

Voy a probar esto y te cuento.

Muchas gracias.

**Comment by plbruniard** [comment]
> A mí lo que me funciona en la Server (no recuerdo qué onda en la Desktop) es [este comando](https://askubuntu.com/a/765062):
> 
> ```
> sudo dpkg-reconfigure keyboard-configuration
> ```
> 
> Ahí te muestra una ventanita para elegir qué distribución usar. Lo que _creo_ que no tiene es una forma de auto-detectar tu configuración (onda, necesitás saber cuál es la que tenés).

Voy a probar primero el de @papa-caco y, si no me funciona, pruebo el tuyo.

Muchísimas gracias. @mgarciaisaia

**Comment by plbruniard** [comment]
> > Hola Pedro, yo también tuve ese problema cuando tuve que cambiar de compu. Comparto este instructivo para cambiar la distribución del teclado en la VM con interfaz gráfica. Espero te sirva de ayuda,
> > [Agregar Agente de distribución de teclado en Configuración de Panel.pdf](https://github.com/sisoputnfrba/foro/files/4792752/Agregar.Agente.de.distribucion.de.teclado.en.Configuracion.de.Panel.pdf)
> > Saludos,
> 
> Voy a probar esto y te cuento. @papa-caco
> 
> Muchas gracias.

@papa-caco, ya hice la prueba y funcionó perfectamente. Muchísimas gracias.
