### ISSUE TITLE
[TEAM] Deadlock, dudas varias

### ISSUE THREAD

**Issue by FedeMacias** [sisoputnfrba/foro#1776]
Buenas, tengo varias consultas de deadlock:

1- El algoritmo tiene que correrse cada vez que no haya entrenadores en ready, exec o new?? o solamente tiene que correrse una vez luego de que se termine de planificar a todos los entrenadores (osea, cuando ya todos los entrenadores atraparon todos los pokemones disponibles)?

2- Tiene que ser un hilo que verifique constantemente si hay DL?

3- Mientras se solucionan los deadlocks, puede seguir planificandose entrenadores que tengan que atrapar pokemones en caso de que ocurra esa situacion?

Por ahora es eso, si se me ocurren mas hago otro issue

Saludos!

**Comment by iago64** [comment]
Aloha!!
Preguntas cortitas y al pie hacen ayudantes felices 😄 

1.- Cuando quieran / puedan, mientras informen bien los deadlocks y los resuelvan, sean felices :)
2.- Depende muchisimo de como lo implementen, mientras no tengan esperas activas háganlo como _mas fácil les resulte_ 
3.- Si, igual depende de cuando los detecten, pero no habría problema :)

Saludos.-

**Comment by FedeMacias** [comment]
Osea que es valido dejar que primero se atrapen todos los pokemons y despues resolver los deadlocks que se hayan generado? talves es medio redundante en base a lo que pregunté, pero solo para estar seguro

**Comment by iago64** [comment]
Si señor es valido hacer eso

**Comment by ncoen97** [comment]
Mientras lo defiendan bien en el coloquio :wink:

**Comment by FedeMacias** [comment]
lo voy a defender a muerte porque me parece lo mas sencillo!!

Muchas gracias, voy cerrando aca
