### ISSUE TITLE
[BROKER] - Buddy System

### ISSUE THREAD

**Issue by Marrieta99** [sisoputnfrba/foro#1778]
Hola de nuevo.

Viendo el video de memoria de broker subido hace poco me surgió una duda sobre la implementación esperada por la cátedra del buddy system.
Varias veces en el video cuando se habla de la memoria principal, se recalca que en la misma sólo debe guardarse la información de los mensajes, dejando fuera de la misma cualquier estructura administrativa que usemos.
En la teoría de Buddy System, yo tengo particiones dentro de las cuales guardo no sólo el dato en sí sino tambien un header al principio de la misma. Por lo tanto no me queda claro si esperan que guardemos el header de cada buddy (o particion) dentro de la misma, que seria en memoria principal, o por fuera de esta.

**Comment by iago64** [comment]
Aloha!
Como siempre decimos, a veces tenemos que tomarnos algunas licencias poéticas de la teoría (para que no sea tan difícil de implementar) con lo cual, lo que va en la memoria es lo que esta en el [Anexo II](https://docs.google.com/document/d/1be91Gn93O2Vp8frZoV1i5CmtOG0scE1PS8dMHsCP314/edit#heading=h.3hv69ve) el resto de cosas van en una estructura administrativa que uds pueden crear como quieran (spoiler, las listas de las commons son ideales para eso 😉)

Saludos.-

**Comment by Marrieta99** [comment]
Bueno listo cierro issue
