### ISSUE TITLE
[TEAM] Capturas.

### ISSUE THREAD

**Issue by FredeHG** [sisoputnfrba/foro#1779]
Buenas!!!1uno

Me surgio una duda sobre un issue anterior que no me cierra el funcionamiento, especificamente esta [aclaracion.](https://github.com/sisoputnfrba/foro/issues/1722#issuecomment-638334600)

   Suponiendo que un team tiene como objetivo 2 pikachu. Y la gamecard contiene 2 pikachu's en la misma posición de antemano, cuando el team se levante, se lanza un get pikachu, y solo obtengo conocimiento de una posición. En este caso por lo que dice la aclaración solo puedo tirar un catch en esa posición y ya después borro la posición, ahora el team va a tener que esperar a un Appeared o no terminar nunca cuando tiene un pikachu bailando en su cara.
![a21847eabf81adc5400bdea1a3a0f9ff](https://user-images.githubusercontent.com/38965532/84979474-e7322f00-b105-11ea-9e42-7a3498a3715b.gif)
 

Siendo que realmente con los pokemon's que tiene la gamecard considero que debería poder terminar sin problemas. 

Saludos!

**Comment by iago64** [comment]
Buenas!
Si, justamente el team no va a saber la cantidad de pokemones en una posición, simplemente va a saber que "hay" un pokemon en esa posición, aunque puede que llegue tarde y cuando tire el catch le digan que no va mas...
Y si puede que se queden esperando hasta el final de la cuarentena, pero eso tiene un nombre copado en la teoría y es un lindo aspecto para charlar en el coloquio 😄 

Saludos.-

**Comment by FredeHG** [comment]
Buenísimo, muchas gracias! Saludos
