### ISSUE TITLE
Pruebas Team: espera_circular_basico manda NEW_POKEMON

### ISSUE THREAD

**Issue by ezeBalsamo** [sisoputnfrba/foro#1780]
Buenaas! Cómo andan? Espero que muy bien!

Perdón si me repito un poco con el título! Estaba viendo el script de pruebas _**espera_circular_basico.sh**_ y noté que al TEAM se le está enviando NEW_POKEMON.

Lo correcto sería APPEARED_POKEMON?

Muchas gracias, saludos!

**Comment by iago64** [comment]
Buenas!
Efectivamente debería ser un APPEARED y no NEW 😄 
En el transcurso del día lo vamos a estar fixeando.

Abrazo.-

**Comment by ezeBalsamo** [comment]
Genial! Muchas gracias!
Abrazoo!
