### ISSUE TITLE
[BROKER] Dump de la Caché

### ISSUE THREAD

**Issue by FranciscoDumont** [sisoputnfrba/foro#1781]
Hola, como va ? :wave: 

Me surgieron dos preguntas cortitas del tema Dump de la Cache:

- **1. Muestro las direcciones en hexa ?**
El enunciado nos da un ejemplo de como realizar el dump y las direcciones las muestra en hexadecimal.
Esto es necesario o puedo hacer el Desde-Hasta en decimal ?
  ``` 
  Dump: 14/07/2012 10:11:12
  Partición 1: 0x000 - 0x3FF.	[X]	Size: 1024b	LRU:<VALOR>	Cola:<COLA>   ID:<ID>
  Partición 2: 0x400 - 0x409. 	[L]	Size: 9b
  Partición 3: 0x40A - 0x40B. 	[L] 	Size: 1b
  ```

- **2. No se pretende ver el contenido de la información almacenada ?**
El enunciado dice que no se pretende ver el contenido de la información almacenada.
Esto me da a entender que no hay razón de linkear un mensaje con una partición dentro de mis estructuras administrativas. 

  Más adelante dice que tengo que mostrar el id y la cola a la que pertenece el mensaje.
Lo que me da a entender que tengo que linkear un mensaje con una partición.

  La pregunta concretamente es si esto es un error del enunciado o si quieren que muestre id y cola junto con los datos de la partición.

Desde ya les agradezco a los ayudantes que usen su tiempo para responder a esta o a cualquier otra de las consultas del foro.
Gracias !! :pray:

**Comment by iago64** [comment]
Aloha!
Respecto a las posiciones de memoria, les pusimos direcciones hexa porque son mas amigables de leer, igual si te sirve de dato, `printf` tiene el formato `%p` que te imprime cosas como punteros (Hexa) 😉 
Respecto al contenido del mensaje, no les pedimos que lo impriman porque si no va a ser un bardo el dump y queremos que sea rápido de ver, pero eso no los libera de tener que linkear la estructura administrativa con el contenido de la memoria (de hecho me gustaria saber como harían por ejemplo la compactación sin linkear...)
La idea del ID y la queue a la que están asociados los mensajes lo necesitamos como para tener el alcance completo de lo que están mostrando, si no nos faltaría la mitad de la info y por ej si un mensaje no le llega a algún suscriptor nuevo bien puede ser porque ya lo fletaron de la cache por falta de espacio 😉 

Saludos.-

**Comment by FranciscoDumont** [comment]
Hola!
Muchas gracias por el consejo para printear hexa y por la muy clara explicación.

Agrego como comentario por si alguien más ve este issue después de cerrarlo que:
Si pones `%06p` te printea con ceros adelante del numero.
El `6` vendría a ser la cantidad de dígitos que queres mostrar.
Ej: en vez de mostrar `0x18` te muestra `0x0018` 

Y de paso que también una forma rápida de tirarle signal `USR1` al broker sin saber el PID es:
Poniendo esto en la terminal `killall -s USR1 broker`
`killall` es como el `kill` pero en vez de pid recibe el nombre del proceso
Si al compilar el broker le pusieron de nombre "batata" tendran que correr `killall -s USR1 batata` y así

Cierro el issue, un saludoo
