### ISSUE TITLE
[BROKER] FRECUENCIA_DE_COMPACTACION

### ISSUE THREAD

**Issue by sebastiangilberto** [sisoputnfrba/foro#1782]
Buenas, cómo están?

En el video dicen comentan que FRECUENCIA_DE_COMPACTACION es la cantidad de particiones libres que tiene que haber, para realizar una compactación. 

Sin embargo en el enunciado nombran lo siguiente:

>Se deberá poder configurar la frecuencia de compactación (en la unidad “cantidad de búsquedas fallidas”). El valor -1 indicará compactar solamente cuando se hayan eliminado todas las particiones.

Esto nos da a entender que una búsqueda es fallida, cuando fallamos al buscar una partición libre que cumpla lo siguiente:

- Suficiente tamaño para almacenar el dato
- Mayor al tamaño mínimo de partición configurado

Nosotros lo pensamos como una suerte de contador, que se incrementa al fallar al buscar esa partición libre; y cuando se alcanza el valor igual a FRECUENCIA_DE_COMPACTACION, ahí disparamos una compactación.

Otra cosa que vimos es que según el enunciado, el orden para almacenamiento de datos es:

1. Se busca una partición libre
2. Si no hay
2.1 Se compacta (si se llega al max de búsquedas fallidas). Vuelvo al paso 1 y si no hay de nuevo, voy al paso 3
2.2 No se compacta (no se llegó al max de búsquedas fallidas, o la configuración está en -1)
3. Se elige víctima y libera partición. Vuelvo al paso 1

Pero según el video el orden es:

1. Se busca una partición libre
2. Si no hay se elige víctima y libera la partición. Se dispara la consolidación
3. Si es necesario se compacta

Las preguntas son:

1. Cuál sería la forma correcta de interpretar FRECUENCIA_DE_COMPACTACION?
2. Cuál es el orden correcto de de almacenamiento de datos?
3. La consolidación en particiones dinámicas es recursiva? Es decir si consolido 2 particiones contiguas, y hay otra contigua a esa consolidada, que también está libre, tengo que volver a consolidar? (Sería como lo que hace buddy system)

Vimos este issue #1772 pero no termina de quedarnos claro.

También nos surgen las mismas dudas con los valores de configuración (-1, 0, 1) en este issue #1777

**Comment by nahuemazzeo** [comment]
Hola @sebastiangilberto!! Como andas?

Vamos por partes.

Por un lado la frecuencia de compactacion es la cantidad de particiones liberadas requeridas para compactar. Esto se usa ya que un sistema en la que por cada partición que se libere se compacte no es productivo. De esta manera poder jugar con este valor va a cambiar la performance del sistema en general. 

Dicho esto, hay un error en el vídeo en el cual dice que con el valor -1 se debe compactar siempre. Esto esta mal, se **_Debe tomar lo que dice el TP_**. Fue un error mio en el vídeo que vamos a aclarar en un post. De todas maneras y como buenos estudiantes vamos a pensar un ppoco mas esto:

- Si un alumno desarrolla el -1 compactando siempre, simplemente cambio el archivo de configuración y le pongo un valor ultra grande de manera de representar lo que hacia el -1

- Si un alumno desarrolla el -1 sin compactar no tengo que hacer nada (Wiip).

Por otro lado veo una duda de que pasos seguir, expliquemos un poco esto. La **Consolidación** se hace **SIEMPRE**. Cada vez que realizo un reemplazo siempre debo consolidar de la manera que explica cada algoritmo. La compactación funciona bajo el concepto anterior.

Resumiendo:

1. Reemplazo una pagina. 
2. Consolido
3. Verifico si debo Compactar (por medio de la frecuencia de compactación). Si no es así, actualizo mi valor actual de la frecuencia de compactación.
3. Veo si puedo almacenar la partición deseada. Si no entra, vuelvo al paso 1
4. Guardo la partición.

Cualquier duda avisame y lo revisamos :)

**Comment by Marrieta99** [comment]
@nahuemazzeo Hola, a mí me quedó una duda sobre la parte de consolidar siempre.. y es que en ese caso cuando me viene FRECUENCIA DE COMPACTACIÓN = -1 yo jamás llegaría a compactar, porque el enunciado dice que compacte solamente cuando se hayan liberado todas las participaciones de la memoria. Sin embargo si las fui consolidando a medida que las liberaba, cuando haya liberado la última la memoria ya se va a hallar unificada, por lo que compactar ahí no haría nada

**Comment by ncoen97** [comment]
@Marrieta99 Es así como planteas y es el comportamiento esperado :+1:

**Comment by papa-caco** [comment]
Buenas noches, cómo están?

Sumo mi pregunta a este issue justamente porque tengo una duda con la frecuencia de compactación y el valor valor '0'. ¿Cuál sería el comportamiento esperado?  ¿Sería el mismo que si el valor fuera '1'? Es decir, luego de hacer el reemplazo de una partición y  consolidar esta nueva partición libre, ¿debo correr la compactación de todas particiones del cache? 
Gracias!  Saludos

**Comment by sebastiangilberto** [comment]
Buenas, @nahuemazzeo vamos a hacerle caso al post que sacaron en utnso que dice que sigamos el enunciado, porque alguno de los pasos que nombras no tienen el mismo orden, y preferimos atenernos al enunciado ante la duda.

Básicamente la diferencia que vemos es en el orden de liberación y compactación, siendo las opciones:

a) Elimino partición y después veo si debo compactar
b) Veo si debo compactar y después si aún no entra, elimino partición

También vimos este issue #1787 donde los pasos que comenta Damián coinciden con el enunciado, que sería la opción b)

**Comment by Nico-0** [comment]
> Buenas, @nahuemazzeo vamos a hacerle caso al post que sacaron en utnso que dice que sigamos el enunciado, porque alguno de los pasos que nombras no tienen el mismo orden, y preferimos atenernos al enunciado ante la duda.
> 
> Básicamente la diferencia que vemos es en el orden de liberación y compactación, siendo las opciones:
> 
> a) Elimino partición y después veo si debo compactar
> b) Veo si debo compactar y después si aún no entra, elimino partición
> 
> También vimos este issue #1787 donde los pasos que comenta Damián coinciden con el enunciado, que sería la opción b)

Tengo la misma duda, ese orden puede cambiar el resultado, y vi en varios issues que lo toman como algo equivalente

**Comment by foviedo** [comment]
@sebastiangilberto y @Nico-0 hablé con otros ayudantes aparte de eso y me confirmaron que primero compactás, ahí chequeás si puede entrar y si no, borrás, osea la opción b, que es lo que dice el enunciado al final del día

>La consolidación en particiones dinámicas es recursiva? Es decir si consolido 2 particiones contiguas, y hay otra contigua a esa consolidada, que también está libre, tengo que volver a consolidar? (Sería algo así como lo que hace buddy system)

Respecto a esto, la conclusión que llegué yo es que nunca te va a pasar eso de tener que consolidar recursivamente si consolidás cada vez que borrás una partición

**Comment by iago64** [comment]
Buenas!
Recién me percato que el issue llevaba un par de días pendiente
@papa-caco como dice @foviedo 0 y 1 se resumen en compacta siempre.
@sebastiangilberto y @Nico-0 les confirmo lo que dice @foviedo primero compactan y después checkean.
Respecto a la consolidación, solo deberían hacer 1 a la derecha y 1 a la izquierda, ya que no podrían tener 2 espacios libres para cualquiera de los lados ya que deberían haberse consolidado cuando se liberaron.

Saludos.-

**Comment by papa-caco** [comment]
Gracias por las respuestas! 👍 Saludos!

**Comment by karengrams** [comment]
@papa-caco ¡perfecto!

@sebastiangilberto @Nico-0  @foviedo ¿Podemos ir cerrando el issue? ¿O quedo alguna duda?

**Comment by Nico-0** [comment]
Si, ya me cerró, gracias.
Una sola cosita, la frecuencia de compactación es global? o se resetea para cada nuevo mensaje que vas a guardar?

**Comment by karengrams** [comment]
¡Buenas @Nico-0!

Nop, la frecuencia de compactación no es global. Si se tiene una frecuencia de 4, entonces, cada mensaje tendrá que compactar 4 veces, independientemente si a algún mensaje le sobro una "frecuencia". 

¡Saludos!

**Comment by sebastiangilberto** [comment]
Buenas, @karengrams respecto al issue original ya fueron contestadas las preguntas.

Ahora nos surgió la duda respecto a lo que comentas de la frecuencia de compactación. Por lo que entendemos, al representar la cantidad de particiones libres necesarias para compactar, nosotros deberíamos llevar un conteo o suerte de trackeo de cuántas particiones tenemos libres cada vez que liberamos una partición.

Como la administración de las particiones es general y no por mensaje, por qué entonces se tiene que compactar 4 veces?

Saludos!

**Comment by karengrams** [comment]
¡Buenas @sebastiangilberto!

¿Como va? Espero que bien. Me exprese mal, mala mia, vuelvo con un ejemplo.

Si tenemos la siguiente situación:
- Mensaje nro. 1
- Mensaje nro. 2
- Frecuencia de compactación = 3

Supongamos que tenemos el mensaje nro. 1 que tenemos que guardar en memoria.
1. Se buscará una partición libre que tenga suficiente memoria continua como para contener el mensaje. 
              El caso feliz: hay espacio, termina el flujo. 
              El caso triste: no hay espacio, pasemos al siguiente paso.
2. Se procederá a eliminar una partición y pasamos al siguiente paso.
3. Nos fijamos, ¿cual es la frecuencia de compactación? tres, perfecto, no tenemos que compactar. Se disminuye a dos y *no compacto* ¿por qué? Porque tengo que, como dijiste Sebas, *eliminar* cuatro particiones (de ser necesario) antes de compactar.
4. Volvemos al paso nro. 1: buscamos una partición: ¿hay? No. 
5. Se procederá a eliminar una partición y pasamos al siguiente paso.
6. ¿Cual es la frecuencia de compactación? dos, perfecto, no tenemos que compactar. Se disminuye a uno y *no compacto* 
7. ¿Hay espacio después de haber eliminado dos particiones? ¡Si! Perfecto. Guardamos el mensaje.

Ahora, queremos almacenar el mensaje nro. 2, ¿debemos tomar la frecuencia de compactación anterior? Es decir, ¿el flujo debería ser el siguiente?

1. Se buscará una partición libre que tenga suficiente memoria continua como para contener el mensaje. Caso feliz: hay espacio, termina el flujo. Caso triste: no hay espacio, pasemos al siguiente paso.
2. Se procederá a eliminar una partición y pasamos al siguiente paso.
3. Nos fijamos, ¿cual es la frecuencia de compactación? ***¿es uno?* No**. Es tres, ¿por qué? Porque la frecuencia de compactación no se comparte, es por mensaje. 

Ahí estaría. Reitero, disculpen por el error anterior. ¿Aclare un poquito?

**Comment by sebastiangilberto** [comment]
Aloha! Me quedaron varias dudas. Voy a seguir tu ejemplo para nombrarlas.

La frecuencia de compactación entiendo que no es variable. Es decir la determinas por archivo de configuración, y cuando levanta el proceso queda fijado ese valor, ya sea -1, 2, 3, 10, etc. Mientras el proceso siga vivo ese dato sigue igual, sería una constante global al proceso.

Por eso te decía que internamente nosotros manejamos un contador o similar, para ir comparando contra esa frecuencia.
Este contador lo vamos incrementando cada vez que eliminamos una partición, y decrementando a medida que asignamos particiones libres y las llenamos.

`
Porque tengo que, como dijiste Sebas, eliminar cuatro particiones (de ser necesario) antes de compactar.
`

Acá no sería eliminar 3? Si parto con que tengo 0 libres, y eliminé 3 seguidas voy a cumplir la condición de Libres == Frecuencia, y ahí compacto, no llegaría a eliminar una cuarta, no?

`
Nos fijamos, ¿cual es la frecuencia de compactación? ¿es uno? No. Es tres, ¿por qué? Porque la frecuencia de compactación no se comparte, es por mensaje.
`

Si para almacenar el mensaje 1 tuve que eliminar 2 particiones, la cantidad libre va a ser igual a 1 (eliminé 2 y llené 1 = me quedó 1 libre).

Cuando llega el mensaje 2 la cantidad de libres sigue siendo 1, no cambió eso, y cuando elimino otra partición paso a tener 2 libres. Todavía no compacto porque la Frecuencia es 3 y no se alcanzó.

Si eliminase una tercera, se alcanzó la frecuencia (libres == frecuencia == 3), entonces compacto, y reinicio mi contador a 1 (ya que se termina formando 1 grande libre al final).

Lo de tener frecuencia por mensaje me hace bastante ruido, porque nosotros manejamos particiones a nivel general, no discriminamos por mensaje.

Nosotros a la hora de buscar particiones libres (first fit, best fit) y a la hora de eliminar (fifo, lru), no nos fijamos que las particiones sean del mismo tipo de mensaje, que el dato que quiero guardar. Tratamos a todos los mensajes por igual, porque justamente nos manejamos con particiones independientemente del dato que guarden.

Podrías aclararnos esto por favor?

Desde ya gracias!

**Comment by Zheoden** [comment]
Buenas Seba!

El problema que estas teniendo es decir que particiones libres == frecuencia significa compactar y esto no es asi, porque yo puedo tener una frecuencia de 2, y tener 2 partiones libres en las cuales mi mensaje no entra y no por eso voy a compactar. En este caso compactaria cuando tenga 4 particiones libres, 2 que ya estaban y las 2 que liberé. Para que quede claro el concepto, la frecuencia de compactacion es la cantidad de particiones maxima que tenes que eliminar antes de compactar (siguiendo la logica que explico karen antes).

A modo de resumen, de lo que estas planteando, te estas confundiendo en decir que si la cantidad de partciones libres es igual a la frecuencia, entonces compacto.

Saludos!

**Comment by sebastiangilberto** [comment]
Buenas!

Creo que ahora entendí lo que querían decir. Como para chequear que estemos en la misma página:

Básicamente la frecuencia de compactación la "seteas" a nivel global, pero el contador que vas incrementando/decrementando para comparar es por mensaje que vas a guardar.

Ese contador sería "cantidad de particiones que eliminé para guardar este mensaje", y con el próximo mensaje lo reinicias a 0 y volves a empezar.

Perdón por tantos chequeos, pero se armó una mezcla de interpretaciones posibles, entre lo que habíamos entendido del enunciado, y lo que fuimos sacando de los issues que leímos/creamos.

Saludos!

**Comment by iago64** [comment]
@sebastiangilberto Tranqui que esta perfecto que preguntes, es el objetivo del foro 😄 

En respuesta a tu validación, _Si_, el contador vos lo vas a tener que reiniciar para el próximo mensaje.

Saludos.-

**Comment by sebastiangilberto** [comment]
Perfecto @iago64!

De nuestro lado ya pueden cerrar el issue,

Muchas gracias a todos!

**Comment by iago64** [comment]
Perfecto, lo cerramos entonces 😄
