### ISSUE TITLE
[BROKER] Pruebas memoria

### ISSUE THREAD

**Issue by BelenTripodi** [sisoputnfrba/foro#1783]
Buenas! 

En las pruebas de memoria muestran cómo deberían quedar las posiciones de los resultados esperados, pero eso asume que la cache arranca en 0. Nuestro malloc gigante nos devuelve un puntero que puede ser a cualquier dirección de la ram, entonces tendríamos que tener algo más administrativo para reflejar la posición "dentro" de la cache?

Para las pruebas, van a usar el dump de la cache? Mas que nada por lo que esta en el issue #1781  (tenemos la misma duda).

**Comment by iago64** [comment]
Aloha!
Si tranqui, las pruebas siempre asumen que parten de 0 para que sean mas fáciles de explicar (y porque no podemos fijar justo una posición de memoria)
Con lo cual si en el enunciado decimos que la primer partición esta en 0 y la segunda en 12 y tu memoria arranca en 0x4857 entonces la primer partición debería estar en 0x4857 y la segunda en 0x4869, mientras lo podamos ver en el dump estamos de 10 😃 

Saludos.-

**Comment by BelenTripodi** [comment]
Gracias dami. 

Cierro el issue.
