### ISSUE TITLE
[Team] Métricas

### ISSUE THREAD

**Issue by leobz** [sisoputnfrba/foro#1784]
Hola! Una consulta ¿Cuáles serían las métricas a las que se refiere el TP que hay que hacer para el hito 4?.  Un saludo!

**Comment by iago64** [comment]
Buenas!!
Las metricas son del team (aunque no esta muy claro), lo que tendrían que informar es lo que esta en la parte de [Competición y Deadlock](https://docs.google.com/document/d/1be91Gn93O2Vp8frZoV1i5CmtOG0scE1PS8dMHsCP314/edit#heading=h.3tbugp1)
 
- Cantidad de ciclos de CPU totales.
- Cantidad de cambios de contexto realizados.
- Cantidad de ciclos de CPU realizados por entrenador.
- Deadlocks producidos y resueltos (Spoiler Alert).

Saludos.-

**Comment by karengrams** [comment]
¡Buenas!

¿Quedo resuelta la duda? ¿Podemos cerrar el issue?

Saludos.

**Comment by leobz** [comment]
Si gracias!

**Comment by francorojo** [comment]
Hola buenas tardes, nos surgio una duda con el ultimo item:

- Deadlocks producidos y resueltos (Spoiler Alert).

Los deadlocks producidos y los resueltos, no son lo mismo? Puede diferir la cantidad? Por que el Spoiler Alert, nos da miedo xd.
El team adquiere los pokemones que necesita por los entrenadores que lo componen, por lo tanto los pokemones del team son los que necesita como objetivo global y estos son la suma de los que necesitan los entrenadores. Hay un caso donde no se pueda resolver el deadlock?
Gracias, saludos!
