### ISSUE TITLE
[GAMECARD] Consulta sobre datos en bloque.

### ISSUE THREAD

**Issue by gebonora** [sisoputnfrba/foro#1785]
Buenas!
Tengo una consulta sobre cómo guardar la información en los bloques.
Entiendo que el formato pedido es:

1-1=10
1-5=1
3-1=2
coordenadaX-coordenadaY=cantidad

Y el enunciado menciona que se guarda fila a fila. 

1) Puedo guardar la información como texto? 
2) Debería tener un \n al final de cada línea? Lo tengo en cuenta para el size del archivo? El size por ejemplo de una línea 1-1=10 sería 7, 6 del texto + 1 del \n?

Gracias!

**Comment by iago64** [comment]
Buenas!
Perguntas claras y concisas son todo lo que esta bien, sabelo 😄 
1.- Si, no hay drama, pueden guardar lo como texto.
2.- Los \n forman parte del archivo y por lo tanto tenes que contarlos en el size, si vos por ejemplo tuvieras lo mismo que pusiste en el ejemplo del formato:
1-1=10
1-5=1
3-1=2
Y no contas los /n en el size, al momento de intentar leerlo como te van a falta 2 /n te va a quedar un string mas o menos asi: 1-1=10\n1-5=1\n3-1 y ahi te queda en claro que te falta el =2 de la ultima fila :)

Saludos.-

**Comment by gebonora** [comment]
Gracias, quedó clarísimo! 
Cierro el issue.
