### ISSUE TITLE
[Broker] Mensaje más grande que memoria/duda compactación/consolidación

### ISSUE THREAD

**Issue by foviedo** [sisoputnfrba/foro#1787]
Hola! Preguntas: 
1_Puede llegar a presentarse la ocasión en la que en un test tenga una memoria muy chica (10B por ejemplo) y me manden un mensaje más grande que ella (12B por ej)? 

Respecto a la parte de consolidación/compactación, vi que hubo varios issues en diferentes momentos + video + enunciado y me hice una ensalada de contradicciones, puedo preguntar si mi interpretación es la correcta?
2_Respecto a la consolidación, el video manda: Se consolida SIEMPRE que elimino una partición

3_Si la frecuencia de compactación es 2, tengo el siguiente esquema
3.1_Busco partición, no encuentro, borro una vez
3.2_Busco partición, no encuentro, borro de nuevo, se me presentan dos situaciones posibles:
3.3.1_Busco partición. sí encuentro, grabo en memoria (A)
3.3.2_Busco partición, no encuentro, compacto, reinicio el contador a 2 y vuelvo a buscar
3.4_ (continuación de A) busco partición, no encuentro, compacto, reinicio el contador a 2

4_Si la frecuencia de compactación es 1
4.1_Busco partición, no encuentro, borro una vez, se me presenta la misma situación que antes
4.2.1_Busco partición. sí encuentro, grabo en memoria (B)
4.2.2_Busco partición, no encuentro, compacto, reinicio el contador a 1 y vuelvo a buscar
4.3_ (continuación de B) busco partición, no encuentro, compacto, reinicio el contador a 1

5_Si la frecuencia de compactación es 0: Manda el video, en este caso el esquema que está en el tp que cito:

> 1_Se buscará una partición libre que tenga suficiente memoria continua como para contener el >valor. En caso de no encontrarla, se pasará al paso siguiente (si corresponde, en caso contrario se >pasará al paso 3 directamente).
>2_Se compactará la memoria y se realizará una nueva búsqueda. En caso de no encontrarla, se >pasará al paso siguiente.
>3_Se procederá a eliminar una partición de datos. Luego, si no se pudo encontrar una partición con >suficiente memoria como para contener el valor, se volverá al paso 2 o al 3 según corresponda.

Los pasos 2 y 3 se invertirían, primero elimino y después compacto, o en realidad tengo que seguir respetando el esquema y primero compacto y después elimino?
6_Si la frecuencia de compactación es -1: manda el video, es idéntico al caso anterior, pues si bien el tp dice

> Se deberá poder configurar la frecuencia de compactación (en la unidad “cantidad de búsquedas >fallidas”). El valor -1 indicará compactar solamente cuando se hayan eliminado todas las particiones

Si el punto 4 que escribí arriba es verdadero, debido a la consolidación, nunca se me va a presentar una situación en la que vaya a compactar una memoria vacía pues acá compactación y consolidación son prácticamente sinónimos y yo venía consolidando siempre

**Comment by iago64** [comment]
Aloha!
Vamos a responder esas dudas

1. No vamos a ser tan mala leche de darte una memoria mas chica que los mensajes, a lo mucho les daremos una memoria de 512 bytes y los recontra cascotearemos para que tengan que reemplazar particiones pero no mas que eso.
2. Si señor, la consolidación es siempre que se libere una partición y tenga alguna al lado vacía
3. En este es un lindo caso porque vos primero tenes que eliminar 2 (porque lo dice la frecuencia de compactación) y después compactar, con lo cual seria:
Busco, como no encuentro elimino
Busco de nuevo si encuentro joya aca termina, si no encuentro elimino, compacto y busco de nuevo (y ahí reinicias el contador)
4. Este caso es mas fácil porque como la frecuencia es 1 si no encontrás: eliminas, compactas y buscas siempre en ese orden
5. Si es 0 compactas siempre.
6. Si es -1 solo compactas cuando eliminaste todas las particiones (osea nunca porque como bien decís ya la consolidaste por limpiar toda la memoria)

Saludos.-

**Comment by foviedo** [comment]
Gracias Dami! Para terminar de cerrar:

> 3.En este es un lindo caso porque vos primero tenes que eliminar 2 (porque lo dice la frecuencia de compactación) y después compactar, con lo cual seria:
> Busco, como no encuentro elimino
> Busco de nuevo si encuentro joya aca termina, si no encuentro elimino, compacto y busco de nuevo (y ahí reinicias el contador)

Tomando en cuenta lo que dijiste acá, yendo a un caso general, debería replantear esta sección del tp:
>1_Se buscará una partición libre que tenga suficiente memoria continua como para contener el valor. En caso de no encontrarla, se pasará al paso siguiente (si corresponde, en caso contrario se pasará al paso 3 directamente).
>2_Se compactará la memoria y se realizará una nueva búsqueda. En caso de no encontrarla, se pasará al paso siguiente.
>3_Se procederá a eliminar una partición de datos. Luego, si no se pudo encontrar una partición con suficiente memoria como para contener el valor, se volverá al paso 2 o al 3 según corresponda.
Como:
1_Se buscará una partición libre que tenga suficiente memoria continua como para contener el valor. En caso de no encontrarla, se pasará al paso siguiente 
2_Se procederá a eliminar una partición de datos. //nota que acá no vuelvo a buscar
Y tengo dos posibilidades:
3.1_ Se compactará la memoria **(Si corresponde)**, incluyendo reiniciar el contador, y se realizará una nueva búsqueda. En caso de no encontrarla, se vuelve al paso 2
3.2_Si no corresponde compactar memoria, se realizará una nueva búsqueda (reduciendo el contador en este momento). En caso de no encontrarla, se vuelve al paso 2

>4.Este caso es mas fácil porque como la frecuencia es 1 si no encontrás: eliminas, compactas y buscas siempre en ese orden
Esto sería idéntico a compactar siempre no?

**Comment by iago64** [comment]
Facu, como va?

Efectivamente, tu planteo es el correcto:
1. Se busca una partición libre
2. Si no hay
    2.1 Se compacta (si se llega al max de búsquedas fallidas). Vuelvo al paso 1 y si no hay de nuevo, voy al paso 3
    2.2 No se compacta (no se llegó al max de búsquedas fallidas, o la configuración está en -1)
3. Se elige víctima y libera partición. Vuelvo al paso 1

Si señor, si el valor es 1 siempre compactas 😄 

Saludos.-

**Comment by foviedo** [comment]
Gracias por todo, cierro issue
