### ISSUE TITLE
duda con bitmap y mmap

### ISSUE THREAD

**Issue by enogueiras** [sisoputnfrba/foro#1788]
Hola buenas tardes, busque en issues anteriores pero no vi respuesta a mi duda, actualmente tengo una funcion que me crea en disco el bitmap con el tamaño necesario:

```
t_bitarray* crear_bitmap_en_disco(char* archivo, size_t size){

	int fd = open(archivo, O_CREAT | O_RDWR, 0664);

	if (fd == -1) {
		perror("open file");
		exit(1);
	}

	ftruncate(fd, size);

	void* bmap = mmap(NULL, size, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);

	if (bmap == MAP_FAILED) {
		perror("mmap");
		close(fd);
		exit(1);
	}

	t_bitarray* bitmap = bitarray_create_with_mode((char*) bmap, size, LSB_FIRST);

	size_t tope = bitarray_get_max_bit(bitmap);

	for(int i = 0; i < tope; i++){

		 bitarray_clean_bit(bitmap, i);
	}

	close(fd);
	munmap(bmap, size);
	return bitmap;
}
```
Ahí puedo ver bien la asociación del bmap con el bitmap, pero lo que no logro entender es después cuando quiera mapear el bitmap ya creado, por ejemplo para buscar un bit en 0, como debería pensarlo. De momento solo veo volver a crear el bitmap y hacer las operaciones que necesite, pero se que esta mal esa forma.

Muchas gracias.
Saludos,
Emilio.

**Comment by iago64** [comment]
Buenas!

Fijate que en las funciones de las commons tenes una función re copada que te devuelve el estado del bit en el indice que vos le pasas (`bitarray_test_bit()`) y ahi vos podrias hacer un for y recorrer desde el principio hasta el ultimo bloque preguntando por el valor del bit y encontrar el primero en 0 :)

Saludos.-

**Comment by enogueiras** [comment]
@iago64 como va? si, mi duda era con el tema del mmap puntualmente, pero creo que ya encontre el problema, yo en mi funcion de creacion al final le hago un munmap, y de esa manera estaba perdiendo el mapeo, deberia no hacerlo hasta el final de la ejecucion de gamecard, donde libero toda la memoria, lo probe recien y me esta funcionando de esa manera, cualquier cambio en bits que hago, lo veo reflejado en el disco con xxd -b.

Si esto es correcto, se puede cerrar.

Saludos,
Emilio.

**Comment by iago64** [comment]
Buenas!
Revisando la función veo que lo que te falto es el [msync()](https://www.man7.org/linux/man-pages/man2/msync.2.html) para forzar que se actualice el archivo :)

La idea de munmap() es la de terminar el mapeo del archivo en memoria, con lo cual, efectivamente no deberías ejecutarlo hasta el final del gamecard 😉 

Cualquier cosa que no se entienda, avisa.
Saludos.-
