### ISSUE TITLE
Modelo dump cache.

### ISSUE THREAD

**Issue by plbruniard** [sisoputnfrba/foro#1789]
En el Enunciado 1.4 aparece este texto como modelo del vuelco de memoria.

**Dump: 14/07/2012 10:11:12
Partición 1: 0x000 - 0x3FF. [X] Size: 1024b LRU:<VALOR> Cola:<COLA> ID:<ID>
Partición 2: 0x400 - 0x409. [L] Size: 9b
Partición 3: 0x40A - 0x40B. [L] Size: 1b**

Habría que corregir los tamaños de las particiones 2 y 3 que serían 10 y 2 bytes respectivamente.

Gracias y saludos.

**Comment by nahuemazzeo** [comment]
Hola @plbruniard!! Muchas gracias por tu comentario y tu apreciación. La misma es correcta.

Vamos a analizar si esta apreciación vale la pena para realizar una nueva subversión del trabajo practico.

Saludos.

**Comment by plbruniard** [comment]
![image](https://user-images.githubusercontent.com/50252902/85215472-9877d580-b34f-11ea-8860-737fb77b870f.png)

Se podría decir que en este diagrama habría una **incongruencia** con el informe de vuelco de memoria de arriba.

A la hora de **numerar las particiones**, en este, solo se numeran las particiones ocupadas y, en el de arriba, se numeran también las libres.

Convengamos en que, el **número de partición** sería una abstracción no muy relevante y, si además, usamos distintos esquemas para determinar **si se numeran** no parecería ser un dato a tener en cuenta.

Si como resultado de una consolidación, cinco particiones libres contiguas terminan siendo una sola partición, habría que modificar el numero de partición de todas las particiones subsigui ¿ entes. 

Parecería que, el numero de partición sería un simple número que indicaría un orden momentáneo  y efímero de las particiones en el instante en que se las vuelca pero nada relevante.

Y, en el esquema de particiones amigas, ¿cuál sería la forma de numerarlas? ¿A derecha, a izquierda o por el centro del arbol?

**Comment by nahuemazzeo** [comment]
Hola @plbruniard. Como andas?

No termine de comprender cual es la duda o inconveniente. Tampoco veo una incongruencia en el trabajo practico.

El dump es una manera de listar el orden de las particiones como se encuentran en memoria. El numerado es decision de cada grupo como hacerlo

Saludos.

**Comment by plbruniard** [comment]
> Hola @plbruniard. Como andas?
> 
> No termine de comprender cual es la duda o inconveniente. Tampoco veo una incongruencia en el trabajo practico.
> 
> El dump es una manera de listar el orden de las particiones como se encuentran en memoria. El numerado es decision de cada grupo como hacerlo
> 
> Saludos.

En el "dump" están numeradas las particiones libres y en el esquema están salteadas las particiones libres a la hora de numerarlas.  

Eso me parecería una incongruencia. Y, te comento que dicha diferencia de trato con el trato de las particiones libres hace que, en el grupo alguno sostenga que las 'libres' no son particiones propiamente dichas basándose en ese gráfico.

Luego, también, gracias a ese gráfico en que las particiones libres no están numeradas, me dicen que el 'tamaño minimo de particion, solo vale para las ocupadas y no para las libres, a lo que yo sostengo que 'vale para las dos'. 

En fin, como nosotros no sabemos nada de esto, nos hacemos preguntas y miramos todos los diagramas para encontrar respuestas.  En este caso, yo veo una incongruencia que conduce a malinterpretar el problema a resolver. 

Saludos. @nahuemazzeo

**Comment by nahuemazzeo** [comment]
Hola @plbruniard.

Como te dije, la numeracion del dump es solo para marcar un orden en el cual estan dentro de la memoria. Como dice 1, 2 o 3 podria ser A, B, C. 

Y en la imagen de ejemplo podrian ser pepe, carla y martin en vez de 1, 2 y 3.

Cada grupo puede identificar las particiones de distintas maneras y mientras cumplas con hacer el dump progresivo de todo el espacio y puedas administrar la memoria de manera correcta va a estar correcto.

Creo q te estas tomando demasiado tiempo en buscar incongruencias cuando esto lo podrias resolver rapido a nivel codigo 😜

Mi recomendación para que termine bien la cursada y que lleguemos bien a la entrega es bajar un poco con estas busquedas exhaustivas y hacerlo.

La duda creo q esta resuelta y sino pingueame por privado y coordinamos para hacer una call y lo charlamos

Saludos

**Comment by plbruniard** [comment]
Estimado Nahuel @nahuemazzeo 

Su respuesta resuelve que, el **número de partición**  es poco importante y podría usarse con cualquier criterio de órden y numeración, hasta podrían **bautizarse** las particiones. Gracias por el dato que no figura en el enunciado.

Me queda la duda de si ¿las particiones libres, se numeran, no se numeran, a veces si, a veces no?

Y si, las particiones libres deben respetar el 'tamaño mínimo de partición'.

Voy a copiar de nuevo su recomendación para que la vuelva a leer: 

**Mi recomendación para que termine bien la cursada y que lleguemos bien a la entrega es bajar un poco con estas busquedas exhaustivas y hacerlo.**

Lo que se lee es algo muy parecido a una amenaza seguida de una moción de censura, dos cosas que no son muy agradables provenientes de un docente de una universidad pública.

La voy a tomar como un exabrupto y la voy a dejar pasar.

Tengo la plena seguridad de que, a la hora de evaluar mi trabajo, lo harán en el coloquio, de acuerdo con el grado de conocimientos que pueda demostrar y mi grado de participación en el TP.

Le comento que este tipo de respuestas son las que desalientan a muchos alumnos a usar el foro para consultar. 

Le mando cordiales saludos.

PD no veo la forma de pinguearlo  por privado. Quizás, esta forma de comunicarse, por escrito deja lugar a malas interpretaciones.

**Comment by nahuemazzeo** [comment]
Hola @plbruniard como andas?

La particion minima es solo para particiones ocupadas, no libres. Puede quedarte una fragmentacion de 1 byte siendo el minimo de 4 bytes. 

Con respecto a como ubicarme podes hacerlo via email o por discord. En el mismo figuro con minnombre y apellido.

Por ultimo, siempre aboco al respeto hacia los alumnos y no evaluo su manera de expresarse tanto por texto como por entregas finales y parciales. Pero como vos dijiste siempre hay que mantener un lineamiento de respeto que creo que estamos tambaleando desde el checkpoint a hoy.

Nuevamente recomiendo que bajemos la intensidad y busquemos resolver las dudas para terminar el cuatrimestre con el trabajo practico. Si queres buscame por Discord y lo charlamos.

Saludos. Nahuel Mazzeo

**Comment by plbruniard** [comment]
Muchas gracias por toda la información. Me sirve para seguir adelante.
