### ISSUE TITLE
[Broker] Pruebas Consolidación

### ISSUE THREAD

**Issue by leguizamonrocio** [sisoputnfrba/foro#1790]
Hola! 

Corriendo el script **consolidacion_basico.sh** nos surgió una duda:

`./gameboy BROKER CAUGHT_POKEMON 1 OK` → 4 bytes → posición 0
`./gameboy BROKER CAUGHT_POKEMON 1 FAIL` → 4 bytes → posición 4
 
`./gameboy BROKER CATCH_POKEMON Pikachu 2 3` → 19 bytes → posición 8
`./gameboy BROKER CATCH_POKEMON Squirtle 5 2` → 20 bytes → posición 27

Hasta acá tenemos 47 bytes ocupados de una memoria de 64 bytes.

`./gameboy BROKER NEW_POKEMON Onyx 4 5 1` → Ocupa 20 bytes que no podemos guardar en la memoria, ya que la partición que queda disponible es de 17 bytes. 

Entonces, nuestro Sistema procede a buscar particiones según FF, y con el algoritmo FIFO elimina las primeras 3 particiones, dejando una partición con posición 0 y tamaño 27 en la que entraría el mensaje NEW_POKEMON Onyx 4 5 1 de 20 bytes.

Finalmente, luego de la suscripción y del mensaje:

`./gameboy BROKER NEW_POKEMON Charmander 4 5 2` 

Este último mensaje NO se guardaría en la posición 0, lo haría en la posición 20. 

Adjuntamos una imagen para ver de manera más gráfica lo que planteamos. En Soporte nos comentaron que tal vez, no fue contemplado un uint32_t correspondiente al _largo del mensaje_ del NEW_POKEMON. Probamos agrandando el tamaño de la memoria en el config, y el script nos da los resultados esperados.

Gracias!

![consolidacion_basico](https://user-images.githubusercontent.com/48370992/85207636-4196df80-b300-11ea-93ff-a4283c8218d1.png)

**Comment by karengrams** [comment]
¡Buenas!

¿Como va? Espero que bien. Se nos re paso che, en estos dias lo vamos a corregir.

¡Gracias por avisarnos! 
¡Saludos! Y buen finde 😸

**Comment by leguizamonrocio** [comment]
@karengrams buenísimo, gracias!

**Comment by iago64** [comment]
Aloha, que el issue esta cerrado pero pasaba a avisar nomas que ya están actualizados los scripts 😄 

Saludos.-
