### ISSUE TITLE
Fragmentacion interna en clusters con posiciones de pokemons

### ISSUE THREAD

**Issue by guidoenr4** [sisoputnfrba/foro#1791]
Que tal, buenas tardes.

Tengo una pequeña consulta, que lo explico mejor con este grafico (antes que nada, obviamente esto esta de ejemplo, nunca dos posiciones van a ocupar los 64 bytes de un block, pero lo hago para que se entienda.

![imagen](https://user-images.githubusercontent.com/47611900/85211718-4d939900-b322-11ea-9386-473fec6a54ed.png)

> los **'.'** al final de cada posicion representan el `/0` que se graba en los archivos binarios
> y cada color representa una posicion distinta para no marear

Supongase que esos 2 blocks pertenecen a un pokemon en especifico, ej pikachu.
En el cual tenemos las posiciones `1-1=50` , **`22-15`**  y `1-1=5`.
Marco en negrita la segunda porque es donde me trae el problema.

Por lo que tengo entendido, se puede dar el caso que mostre en el grafico, de que tenemos que aprovechar todo el tamaño de un cluster, entonces grabamos solamente lo que podemos grabar, que en este caso solamente entro '**`22-15=`**' en el **block1**.

Mi pregunta es, este problema como lo soluciona un filesystem? tuve una larga charla con Matias y Damian de que no hace falta complicarse con el tratado de archivos, peeeero en este caso, las funciones de las **config** no me van a servir para nada, pensa que si hago un 

`int value` = `config_get_int_value(config,"22-15")`

no va a funcionar, puesto que voy a estar leyendo de la config del `block1.bin` que no tiene value , por lo tanto rompe.

a todo esto, este es el caso "bonito" digamos, porque si me trae basura la funcion, yo sabria de antemano que la posicion esta en el cluster siguiente, leeria hasta un '/0' y listo, solved..
peeero puede pasar otro caso no tan bonito en el que tenga que grabar algo asi : 

![imagen](https://user-images.githubusercontent.com/47611900/85211871-bd565380-b323-11ea-8dac-427a1689484d.png)

en el que solo puedo grabar el **`4-`** y ahi listo, no existe el concepto ni de **"key"** ahora mismo porque le faltaria el igual.

Tenia pensado tal vez leer todos los blocks y armarme una especie de archivo temporal para modificarlo y luego re-escribir en los blocks que estaba usando el pokemon, (que creo que va en contra de como trabaja un filesystem).
De todas formas, suponganse que hago esto... leo todo ,lo acomodo y hago ese archivo temporal del espacio que quiera, (total despues lo borro), vuelve el formato de config normal digamos y me servirian las funciones, podria obtener el value de una key sin problemas.
peeero surge otro problema, si se me da el caso de que tengo que actualizar una posicion de un pokemon.. como se *en que block actualizarlo?* pensa que yo obtengo todo de una y seria complicado usar un `fwrite` por ejemplo en la posicion 0 de el block que le seguia o algo asi.
 
Nose si me entendieron, capaz esta no es la idea, capaz el caso este no va a pasar y vamos a tener banda de fragmentacion interna, o capaz pasa y no se soluciona asi.

Muchas gracias de antemano

**Comment by guidoenr4** [comment]
el caso hermoso seria este:

![imagen](https://user-images.githubusercontent.com/47611900/85212091-bc262600-b325-11ea-8a84-cf0063b02301.png)

**Comment by iago64** [comment]
Buenas guido! como va?
En los FS que manejan este concepto de bloques (ya que hay algunos que no y que no nos importan en la charla), el fenómeno de fragmentación interna siempre esta en el ultimo bloque.
Idealmente la idea del uso de las configs estaba pensado para los archivos de metadata (tanto el global del FS como los de los pokemones)
Ahora bien, si no tenes las commons de las config para resolver tu inconveniente (ya que pueden caerte cortadas las lineas) no se te ocurre alguna forma por ejemplo de resolverlo sin crear un archivo nuevo? por ejemplo usando algo en memoria? Por suerte el código de las commons no es la formula de la coca cola y podes checkear como es que funciona internamente el [config_create](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/config.c) y como es que hace para reconocer esos pares clave-valor del archivo (pequeño spoiler, lo hace en memoria 😉)

Fijate si la idea que te planteo de sirve y cualquier cosa avisa y vemos si hace falta algo mas de ayuda.

Saludos.-

**Comment by guidoenr4** [comment]
Si, lei algo sobre archivos mapeados a memoria  y lo vimos un poco en la cursada ( `mmap` )

Pero de que me serviria? no estaria entendiedo mas o menos el uso

**Comment by iago64** [comment]
`mmap()` puede ser una gran ayuda (igual tené cuidado porque no te libera del trabajo de juntar todas las partes en un solo lugar para trabajarlas)
Otra alternativa es levantar los datos a un buffer en memoria con `fread()` y despues de trabajar irlos grabando con `fwrite()`

Fijate de ambas cual te resulta mas practica y avisa si necesitas ayuda.

**Comment by enogueiras** [comment]
buenas, vengo siguiendo el hilo, una consulta, estaría mal armar todos los bloques en un archivo temporal procesar lo que tengo que hacer y luego borrar ese temp?

**Comment by guidoenr4** [comment]
Pense lo mismo, total los blocks que le corresponden al pokemon ya los se, nose si va en contra de un filesystem pero tmb es buena.

**Comment by iago64** [comment]
Buenas!
@enogueiras a priori el problema que tiene esa solución es que tenes mas pasos, pero bueno, si prefieren pelear con archivos que con memoria es decisión de uds, después tendremos para charlar en el coloquio cuando aprueben a ver que otras alternativas tienen 😄

**Comment by guidoenr4** [comment]
De todas formas terminarias haciendo lo mismo verdad? Se que trae ventajas trae mapear archivos a memoria, como el uso de menos syscalls, mejor rendimiento en lectura/escritura, etc..

pero el algoritmo terminaria siendo el mismo, suponete que en los ejemplos de arriba , al tratar algo con un pokemon (eliminar, agregar) tendria el mismo problema, el block que estaria mapeado en memoria no tendria las cantidades de los posiciones , o si miramos el ejemplo 2, tendria cualquier cosa en cualquiera de los dos bloques.

**Comment by iago64** [comment]
Si, en ambos casos la lógica es mas o menos la misma, solo que llevándolo a un archivo agregas mas pasos.

**Comment by guidoenr4** [comment]
Genial! gracias por responder Damian.

Mi idea va a ser generar archivos temporales con nombres random estilo hash `48fiq1jr.bin` (para evitar que justo se creen uno igual) grabo todo en ese archivo temporal, y lo re-escribo en los blocks que ya estaba usando mi pokemon, luego lo borro.

pero UNICAMENTE en el caso de que tenga que grabar asi la ultima posicion y me quede desacomodada, porque ya tengo resuelto los casos en que se graban bien, y los uso como config y andan bien.

Cierro el issue.
