### ISSUE TITLE
[BROKER] cuándo considero que un mensaje fue "usado"

### ISSUE THREAD

**Issue by foviedo** [sisoputnfrba/foro#1792]
Buenas, consulta rápida sobre LRU:
Cuándo considero que un mensaje fue "usado"? Yo solamente consideré en el caso cuando lo recibo y cuando envío la cola completa
No consideré el caso en el que envío a cada suscriptor después de recibirlo, pues ocurre inmediatamente luego de, justamente, recibirlo. Debería considerar este caso? Hay otra situación en la que voy a tener que actualizar el timestamp? (osea, considerar que ese mensaje fue "usado")
Gracias de antemano!

**Comment by iago64** [comment]
Buenas buenas!

Una consulta rápida, el envío de la queue completa, es cuando llega un nuevo suscriptor? o también consideraste el tema de las reconexiones y el envío de mensajes de los cuales no tuviste el ACK?

Idealmente los momentos en los cuales "usas" el mensaje es:
- Cuando te llega
- Cuando lo envías (no importa a quien)

Saludos.-

**Comment by foviedo** [comment]
Gracias!
Sí, consideré las reconexiones (que serían los que no devolvieron ACK, lo que hago es checkear si ese mensaje tiene o no ACK del suscriptor en cuestión)
Pregunto sólo para asegurarme que entendí:
>Cuando lo envías (no importa a quien)
Supongo que entonces tendré que actualizarlo con cada send por más que haga send 30 veces seguidas de ese mensaje?

**Comment by iago64** [comment]
Si, idealmente cuando accedas al mensaje para enviarlo tenes que actualizar el ultimo acceso.

**Comment by foviedo** [comment]
Buenísimo Dami, cierro el issue
