### ISSUE TITLE
[Broker] Pruebas Compactación

### ISSUE THREAD

**Issue by gonzalemi** [sisoputnfrba/foro#1793]
Hola!

Estuve trabajando con el caso de prueba **compactacion_basico.sh** particularmente con el algoritno FIFO y encuentro algunas diferencias con respecto al documento de prueba.
Llego a la conclusión de que el último mensaje `./gameboy BROKER NEW_POKEMON Vaporeon 4 5 2 `debe guardarse en la posición 40 (en el documento figura que debe guardarse en la 36).

Comparto el desglose de cada paso para que podamos revisarlo y entender si hay algún error en el análisis:
![image](https://user-images.githubusercontent.com/6686730/85231365-c0f1e500-b3cc-11ea-8d34-aaaa5003ef16.png)

Tamaño de los mensajes:
- `./gameboy BROKER CAUGHT_POKEMON 1 OK` 4 bytes
- `./gameboy BROKER CAUGHT_POKEMON 1 FAIL` 4 bytes
- `./gameboy BROKER CATCH_POKEMON Pikachu 2 3` 19 bytes
- `./gameboy BROKER CATCH_POKEMON Squirtle 5 2` 20 bytes
- `./gameboy BROKER NEW_POKEMON Onyx 4 5 1` 20 bytes
- `./gameboy BROKER NEW_POKEMON Vaporeon 4 5 2` 24 bytes

Gracias

**Comment by iago64** [comment]
Buenas!!!

Justo hoy nos vamos a juntar a repasar un poco las pruebas y hacer nuevamente los calculos porque como nos comentaron en el issue #1790 algunos mensajes no quedan en el orden que pensamos y nos dimos cuenta que le pifiamos al calcular los totales, asi que tranqui, en cuanto los repasemos bien les subimos las correcciones 😄 

Gracias por estar atentos y tomarse el tiempo de postear estas dudas con tanto detalle nos dan mas material para pulir los tests

Abrazo a la distancia!

**Comment by JuanCarassai** [comment]
Buenas, 

El test consolidacion_basica creo que también tiene un error.
El mensaje:

- ./gameboy SUSCRIPTOR CAUGHT_POKEMON 10

Debería ir antes que el mensaje:

- ./gameboy BROKER NEW_POKEMON Onyx 4 5 1

Si lo que se quiere es eliminar los mensajes CATCH y no los mensajes CAUGHT

Saludos

**Comment by iago64** [comment]
@JuanCarassai como va?
No, el orden estaba bien, la que nos mandamos fue que pusimos New en lugar de Catch, igual tranqui que ya están actualizados y deberían reemplazar bien jeje
Saludos.-

**Comment by karengrams** [comment]
¡Buenas! 

¿Como va todo? Espero que bien.
¿Funcionan bien las pruebas? ¿Hubo algún inconveniente? ¿O podemos cerrar el issue? 

¡Saludos!

**Comment by gonzalemi** [comment]
Hola,
Volviendo a la consulta original. Me sigue quedando la duda sobre la posición en la que debe salvarse el último mensaje.

Gracias!

**Comment by iago64** [comment]
Buenas Gonza!
El ultimo mensaje ahora si debería caer en la primer posición, ya que ahora al corregir el NEW Onyx por Catch Onyx este se reduce a 16 bytes en lugar de 20 y debería entrar en el hueco libre al final

Saludos.-

**Comment by gonzalemi** [comment]
Perfecto, Dami. No me había dado cuenta de que estaba actualizado el caso de prueba, cierro entonces.

Va otro abrazo, Emi.
