### ISSUE TITLE
Planificación de los entrenadores durante un intercambio

### ISSUE THREAD

**Issue by esanchezventurini** [sisoputnfrba/foro#1794]
Buenas tardes. Tengo una duda sobre cómo deben planificarse los intercambios. Una vez que ya todos los entrenadores capturaron la cantidad de pokemon que podían, se corre el algoritmo de detección de Deadlock y se pasa a realizar los intercambios. Éstos deberían realizarse siempre de forma FIFO? Es decir, supongamos que existen 3 entrenadores que se encuentran en deadlock: el primero necesita un pokemon del segundo, el segundo uno del tercero y el tercero uno del primero. Lo que se me ocurre es que el primero debe ir a la posición del segundo, intercambiar y recién una vez hecho esto, el segundo podría ir a la posición del tercero. Es decir, hasta que el primer entrenador no realiza el intercambio con el primero, el segundo no puede moverse hasta la posición del tercero. Esto es correcto?

**Comment by iago64** [comment]
Buenas buenas!
No tendrías que cambiar de algoritmo, pero tampoco tendrías que complicarte en mandar a todos a resolver los deadlocks de 1, podrías por ejemplo primero resolver el deadlock entre A y B, y después el deadlock entre B y C y asi hasta terminar de resolver todos los que tengas.
Lo importante es que los detecten bien a todos y que los resuelvan, despues si es mas optimo resolver todo de 1 o resolverlos de a poco, lo charlamos en el coloquio que es un tema interesante 😄 

Saludos.-

**Comment by esanchezventurini** [comment]
Buenísimo. Entonces no habría problema en dar ciertas "prioridades"? Por ejemplo, que primero realice los intercambios que necesite el entrenador A, después el entrenador B y así hasta que todos cumplan su objetivo?

**Comment by iago64** [comment]
Para nada, elijan uds la forma de resolver los deadlocks que mas fácil les resulte.
Después para charlar si había algo mas optimo para hacerse tenemos tiempo :)

**Comment by esanchezventurini** [comment]
Entonces lo haremos así, excepto que se nos ocurra algo un poco mejor. Muchas gracias!!
