### ISSUE TITLE
[GameCard] Manejo de archivos pokemon

### ISSUE THREAD

**Issue by jftierno** [sisoputnfrba/foro#1795]
¡Buenas!

Estamos teniendo un problema en la implementación del FileSystem.
Uno de los campos del archivo "Metadata.bin" de un pokemon es "OPEN", al que se le asigna el valor 'Y' o 'N' según si el archivo está abierto o no.
El problema es el siguiente: ¿cómo podemos respetar la mutua exclusión sobre este campo *?

*Teniendo en cuenta que se nos informó que los procesos no pueden quedar en espera activa (while(OPEN != Y){}).

¡Muchas gracias de antemano!

**Comment by iago64** [comment]
Buenas! como va?

No te olvides que tienen un el TIEMPO_DE_REINTENTO_OPERACION que eso va a hacer que ese while no sea una espera activa como tal 😉 

Saludos.-

**Comment by jftierno** [comment]
Tenés razón... Nos olvidamos completamente de eso, muchas gracias por la pronta respuesta!
