### ISSUE TITLE
Pruebas Team: espera_circular_basico

### ISSUE THREAD

**Issue by miguel-t** [sisoputnfrba/foro#1796]
Buenas,
En el punto 4 de esta prueba menciona :
` 4. El entrenador D se mueve a atrapar a Espeon en posición 7-1.`
Pero el entrenador E es el mas cercano a Espeon en posición 7-1,segun el archivo de configuracion
para esta prueba .

¿Esta bien el punto 4 ?
Saludos.

**Comment by iago64** [comment]
Buenas!

Lo vamos a estar fixeando, porque si, al parecer se nos cruzaron D y E cuando escribimos las pruebas (2-9 y 9-2 son parecidos)

El mapa inicial debería quedar:
![image](https://user-images.githubusercontent.com/1622109/85243284-e3f5b680-b417-11ea-83a1-2e550fe34328.png)

Posiblemente salga en la v1.3, así agregamos algún test mas 😃 

Saludos.-

**Comment by iago64** [comment]
Bueno, cambio de planes, los nuevos tests se van a demorar un poco (porque vamos a ver de armar algo un toque mas similar a la entrega final)
Con lo cual el mapa ahora va a tener que quedar:
![image](https://user-images.githubusercontent.com/1622109/85244179-4cde2e00-b41a-11ea-9801-24e7cec42f73.png)

Gracias por el aviso!
Abrazo a la distancia!

**Comment by miguel-t** [comment]
Ya entiendo porque no terminaba team :boom: 
Probamos con esta nueva configuracion entonces.

Gracias.
Saludos.

**Comment by iago64** [comment]
Perdon, se nos cruzaron los entrenadores 😿 

Porfa avisa si con esta nueva config todo funciona ok (estamos 99,9% seguros que si)

Saludos.-

**Comment by miguel-t** [comment]
@iago64 con esta nueva config **funciona ok**.
Hay una  espera circular entre los 5 entrenadores y despues se resuelve el deadlock y finalizan los entrenadores.

El problema era, como comentabas, con las posiciones de **D y E** .

Gracias.
Saludos.

**Comment by karengrams** [comment]
Alo,

¡Perfecto! Voy cerrando el issue entonces. Cualquier cosa que vean que no este bien, no duden en reabrirlo. Gracias por el aviso 😸 

¡Saludos!

**Comment by brianUtn98** [comment]
Paso el Config corregido para el que le sirva!
```config
POSICIONES_ENTRENADORES=[3|2,6|4,9|9,9|2,2|9]
POKEMON_ENTRENADORES=[]
OBJETIVOS_ENTRENADORES=[Vaporeon,Jolteon,Flareon,Umbreon,Espeon]
TIEMPO_RECONEXION=30
RETARDO_CICLO_CPU=5
ALGORITMO_PLANIFICACION=RR
QUANTUM=1
ESTIMACION_INICIAL=5
IP_BROKER=[A definir por el grupo]
PUERTO_BROKER=[A definir por el grupo]
LOG_FILE=[A definir por el grupo]
```
Si hay algún error me avisan porfa.
