### ISSUE TITLE
[Broker] First fit y best fit en buddy system

### ISSUE THREAD

**Issue by foviedo** [sisoputnfrba/foro#1798]
Hola! Consulta, en el video mencionan que buddy system utiliza tanto el sistema first fit como el best fit, pero tomando en cuenta los ejemplos + lo que dice el tp + la teoría, el buddy system siempre va a usar best fit
Es un error en el video o hay algo que no estoy entendiendo yo?
Gracias de antemano!

**Comment by nahuemazzeo** [comment]
hola @foviedo!! Como andas?

Entiendo lo que decís y es correcto. Tene en cuenta que el trabajo practico tiene algunas licencias poéticas que sirven en parte para no complejizar tanto el trabajo practico y por el otro agregarle un poco de complejidad a un tema.

Dicho esto y parandonos en el ejemplo puntual que indicas de Buddy System, se decidió que el mismo no tenga compactación ya que es un algoritmo relativamente complejo que no vemos que sume a la hora de desarrollarlo ni educativamente pero dejamos ambos algoritmos de elección de partición libre ya que entendimos que eran muy similares a los ya desarrollados para el otro algoritmo y nos servia para "compensar" en parte la falta de la compactación (ya que el best fit debería atacar en una mayor medida el tema de fragmentación).

Dicho esto, en algún momento ves que el TP y el vídeo se contradicen en esto o es simplemente estos dos contra la teoría?

Saludos. Nahuel

**Comment by BelenTripodi** [comment]
Holis @foviedo 
Te dejo esto por aca, capaz te sirve #1764

**Comment by foviedo** [comment]
Hola Nahue. Estoy bien! Gracias, y vos?
Yendo al punto:

> Dicho esto, en algún momento ves que el TP y el vídeo se contradicen en esto o es simplemente estos dos contra la teoría?
Hay varias cosas que me llevan a pensar esto
-En el mismo video, se da un ejemplo, este ejemplo se adapta al sistema best fit (que es como funciona un buddy system normalmente)
-En el TP no menciona directamente si se va a usar first fit o best fit o los dos
-Y ahora que lo veo, lo que mencionó Belén, ahí también pareciera que best fit es la que va (por el motivo anterior, el tp no dice nada al respecto)
Y también como menciona Adro, ocurre que implementar un first fit es medio inviable, primero, como no está bien definido cómo sería un first fit en Buddy System (a diferencia de tener particiones fijas o dinámicas), puedo asumir dos posibilidades:
1_Cada mensaje ocupa la memoria completa (obviamente no)
2_Un mensaje (de por ej 4 bytes) que sea el primero en enviarse, en una memoria de, por ejemplo, 2048 bytes, ocuparía los primeros 1024 bytes de memoria incluso pesando solo 4
3? Si trato de partir la memoria tantas veces como para que entre el mensaje y no le sobre estos 1024 bytes y al mismo tiempo estoy tratando de respetar el esquema de Buddy System, voy a estar cayendo efectivamente en un best fit

**Comment by nahuemazzeo** [comment]
Hola @foviedo como andas? (perdón por la demora)

Supongamos que tenemos en nuestro buddy system en un determinado instante las particiones en el siguiente estado:

32(L) 4(O) 4(L) 8(L) 16(L)

Supongamos que queremos guardar un mensaje de 4 Bytes en nuestra memoria. De alguna manera nosotros tenemos que hacer una búsqueda binaria para determinar en donde se guarda dicha partición. Por lo general en las memorias se recorren desde la posición 0 hasta la N (siendo el N el total de la memoria).

Suponiendo que estemos bajo el algoritmo Best Fit deberíamos guardar dicho dato en la particion 4(L) mientras que si usamos un algoritmos de First Fit deberíamos guardarlo en la primer Libre que encontremos por lo que deberíamos dividir la partición 32(L) en varios buddy's hasta llegar a un 4(L) y guardarla en el.

Como te explique, entiendo lo que decís y es correcto. Tene en cuenta que el trabajo practico tiene algunas licencias poéticas que sirven en parte para no complejizar tanto el trabajo practico y por el otro agregarle un poco de complejidad a un tema.

Si nos ponemos a pensar a nivel lógico que implican ambas alternativas, en la primera estoy haciendo mas performante el manejo de las particiones y sus buddy's. Mientras que en la segunda estoy partiendo un buddy cuando tendría ya otro que podría guardarlo. Si al instante siguiente debo guardar un mensaje de 32 Bytes en el primer caso no tendría problema mientras que en el segundo debería aplicar un algoritmo de reemplazo.

Saludos. Nahuel

**Comment by foviedo** [comment]
Buenas @nahuemazzeo creo que ya voy entendiendo! Cualquier cosa volveré a abrir el issue
Gracias!
