### ISSUE TITLE
[GAMECARD] - armar estructura de posiciones

### ISSUE THREAD

**Issue by enogueiras** [sisoputnfrba/foro#1799]
Buenas, estoy teniendo un problema para armar las posiciones cuando están separadas en bloques y no respetan el orden de la linea, o sea van bytes copiados en cada bloque:

mi función de prueba:

```
void copiar_archivo_en_temp(char* path_arch_original, char* path_temp){

	char c;

	FILE* file_original = fopen(path_arch_original, "r");

	if(file_original == NULL){
		perror("open file");
		exit(1);
	}

	FILE* file_temp = fopen(path_temp, "a+");

	if(file_temp == NULL){
			perror("open file temp");
			exit(1);
		}

	while((c = fgetc(file_original)) != EOF){

		fputc(c, file_temp);
	}

	printf("Se copio satisfactoriamente...\n");

	fclose(file_original);
	fclose(file_temp);
}
```
Mis archivos

```
utnso@ubuntu-server:~/workspace/practica_config$ cat blocks/0.bin 
2
utnso@ubuntu-server:~/workspace/practica_config$ cat blocks/1.bin 
-7
utnso@ubuntu-server:~/workspace/practica_config$ cat blocks/2.bin 
=800
```
El resultado:

```
utnso@ubuntu-server:~/workspace/practica_config$ cat temp.txt 
2
-7
=800

utnso@ubuntu-server:~/workspace/practica_config$ 
```
Le agrega siempre un salto de linea al final de cada archivo, lo probe con bloques que tienen la posicion completa y hace lo mismo.

Probe tambien:

```
while((c = fgetc(file_original)) != EOF){

		if(c != '\n'){

			fputc(c, file_temp);
		}
	}
```

Pero me une las lineas y no me sirve para distinguirlas.

¿Alguna ayuda?

Muchas gracias.
Saludos,
Emilio.

**Comment by iago64** [comment]
Buenas!
Si estas teniendo un problema con los saltos de linea, y eliminarlos por completo no te sirve, no podrías por ejemplo separar tu string por esos \n? 
Después de eso sabes que vas a tener:
posicion x
posicion y
cantidad
Teniendo en cuenta que podes tener los caracteres - o = que tendrías que sacarlos, podrías hacer alguna lógica con eso capaz.

Otra alternativa seria por ejemplo eliminar el ultimo \n del archivo o ver si tenes 2 \n seguidos para validar que justo termino el archivo en un salto de linea.

Igual el problema final de los \n se reduce a que es importante saber como estas grabando el archivo original, porque ese \n de algún lado sale (algo o alguien lo escribe)

Saludos.-

**Comment by enogueiras** [comment]
Sabes que parece que era el vi (editor), lo probé modificar con el editor del eclipse y me lo arma bien la función. Me respeta donde queda el cursor.

Esos bloques los arme a mano para simular el comportamiento, es la fase previa a probarlo en la realidad.

Gracias!
Emilio.
