### ISSUE TITLE
[BROKER] Signal dump cache

### ISSUE THREAD

**Issue by foviedo** [sisoputnfrba/foro#1800]
Buenas! 
Una consulta, en el enunciado dice que tengo que enviar una señal SIGUSR1 para poder hacer la dump de la cache
Mi duda, en qué circunstancias se manda esta señal? Hay alguna guía que explique cómo cazarlas? Una googleada me muestra que para ejecutarla tengo que poner en el código algo tipo
signal(SIGNOMBRE, funcionQueLaRecibe); 
Pero mi duda es si tengo que poner esto en alguna sección específica del código o si tengo que mandarla por algún medio
Gracias de antemano!

**Comment by iago64** [comment]
Buenas como va?

Como guia, asi que digas, que genialidad de guia... no tenemos (deberíamos hacer una), pero te puedo facilitar la [Presentación de señales](https://docs.google.com/presentation/d/16vml3EWLEV6OByTC3o-ObKCMA7m2zd-Uw6O2qu-VNuQ/edit#slide=id.p1) donde se ve que no hay muuucha magia a la hora de manejar las señales, si no que simplemente definís adentro del main el signal() y despues en otro lado fuera de main creas la función que maneja la señal (hay justo un ejemplo en el slide 6)

Respecto a cuando se manda, la podes mandar de 2 formas faciles:
1.- Usando el comando kill en bash que es `kill SIGUSR1 <PID de tu broker>`
2.- Usando htop, donde tenes que pararte arriba del broker en el listado de procesos, apretar F9 y buscar la signal SIGUSR1 para mandarsela al broker :)

Cualquier otra duda avisa.
Saludos.-

**Comment by foviedo** [comment]
Genial, gracias!

**Comment by foviedo** [comment]
![image](https://user-images.githubusercontent.com/48896107/85345028-b700dc80-b4c7-11ea-918f-8d5f5a895d27.png)
Reabro el issue, cuando tiro kill, efectivamente, me hace kill del proceso y no dumpea, nos falta algo?

**Comment by pacoDan** [comment]
si no recibe la señal , puede que falto el guión  *-* medio antes de SIGUSR1
kill -<señal> <pid>

**Comment by karengrams** [comment]
¡Buenas @foviedo !

Deberíamos ver un poco el código a ver como lo implementaste. Asi por arriba diria que hay un problema con el handler, pero nada seguro 😕 . 

¡Saludos!

**Comment by foviedo** [comment]
Era lo que dijo @pacoDan 
Gracias!

**Comment by karengrams** [comment]
¡Perfecto! :)
