### ISSUE TITLE
[Broker] Diferencia bytes en scripts de pruebas

### ISSUE THREAD

**Issue by dariokozicki** [sisoputnfrba/foro#1801]
Buenas!

Estaba probando el script de cargar_memoria_simple.sh y vi que termina habiendo una diferencia de un byte cuando lo ejecuto, a diferencia de correr los comandos por terminal. 

**El script:**
> ./gameboy BROKER GET_POKEMON Pikachu
> ./gameboy BROKER GET_POKEMON Charmander

Pikachu llega a gameboy con 8 bytes en vez de 7. Creo que esto es porque interpreta el `\n` como parte del nombre en el script. Probé agregando un espacio después de Pikachu en el script y se solucionó.

**Mis logs:**

> [INFO] 23:57:39:77 optional/(12727:12727): size of pokemon: 8 Pikachu
> [INFO] 23:57:39:80 optional/(12729:12729): size of pokemon: 10 Charmander

**Con espacio agregado:**

> [INFO] 23:58:40:324 optional/(12765:12765): size of pokemon: 7 Pikachu
> [INFO] 23:58:40:329 optional/(12767:12767): size of pokemon: 10 Charmander

Esto genera que en broker me lleguen 12 bytes en vez de 11 y no sé qué tan crítico sería que coincida. Debería filtrar cualquier \n posible en gameboy? Strlen parece incluirlo a la hora de decidir el tamaño.

Muchas gracias!

**Comment by dariokozicki** [comment]
Update: Resolví el problema implementando esta función y usándola en vez de strlen:

`int strlenNewLine (const char *str){
    const char *char_ptr;
    for (char_ptr = str; *char_ptr != '\n' && *char_ptr != '\0' && *char_ptr != 13 ;++char_ptr);
    return char_ptr - str;
}`

Igualmente dejo el thread abierto por si hay comentarios sobre el tema.

Saludos.

**Comment by iago64** [comment]
Buenas buenas!

Es posible que tenga que ver con que les toma el \n al momento de llegarles el comando (ya que si no me equivoco los escribieron en windows y el fin de linea es diferente del de linux), lo vamos a estar revisando por las dudas :)

Gracias por el aviso
Abrazo a la distancia!

**Comment by papa-caco** [comment]
Hola Darío, Damián, cómo están?
Les cuento (tarde) que había notado el mismo inconveniente.
En nuestro caso lo solucionamos agregando un espacio más el caracter '#' al final de cada línea.
Debe ser por lo que vos decís Damian, porque con los .sh que armamos  en la VM Ubuntu con el editor de texto de Linux no tuvimos ese problema. Me quedo tranquilo entonces que si es por eso, nuestro gameboy estaría funcionando normalmente.
Gracias, Saludos!

**Comment by iago64** [comment]
Buenas!

Estoy corriendo un par de test locales y tiene toda la pinta de ser eso, con lo cual no hay problema si durante estas etapas previas ajustan los scripts agregandoles un espacio o un '#'
De todas formas esto para la entrega final lo vamos a estar fixeando para que no se encuentren con estos problemas, les pido mil disculpas, en el apuro por sacar los tests se nos paso el temita del famoso salto de linea de windows vs el de linux.

Abrazo a la distancia!

**Comment by dariokozicki** [comment]
Muchas gracias por la buena onda!
