### ISSUE TITLE
Duda Pruebas Broker

### ISSUE THREAD

**Issue by NicoMadd** [sisoputnfrba/foro#1802]
Hola!! 
Tengo una duda sobre los testeos de las pruebas, ya que los pasos indicados en el word especifican la llegada de un mensaje NEW luego de la suscripcion. Y en el script, vemos que luego de la suscripcion llega un mensaje CATCH. Es posible que en el commit anterior al haber modificado el NEW antes de la suscripcion tambien modificaron sin querer el NEW que se enviaba luego de la suscripcion. De lo contrario como deberia ser la ejecucion?

Adjunto fotos:

![image](https://user-images.githubusercontent.com/49067443/85454538-6941ae00-b573-11ea-9266-27a4047cb88e.png)

----------------------------------------

![image](https://user-images.githubusercontent.com/49067443/85454593-76f73380-b573-11ea-9bcb-6a1066169f0f.png)

Gracias, Saludos!

**Comment by iago64** [comment]
Buenas buenas!

Perdón la demora en contestar, si señor, fue un error que lo arreglamos en los scripts pero se nos paso cambiarlo en el doc.
Mil gracias por avisar :)

Abrazo a la distancia!

**Comment by NicoMadd** [comment]
Buenisimo, Gracias!!
