### ISSUE TITLE
[TEAM] Duda sobre finalización del proceso.

### ISSUE THREAD

**Issue by gebonora** [sisoputnfrba/foro#1803]
Buenas!

Con mi grupo tenemos una duda sobre Team.

Tenemos entendido que cuando un equipo finaliza su objetivo, el proceso debe finalizar. 

- Hasta qué punto tenemos que encargarnos dentro de Team de la liberación de memoria pedida? Podemos mandar un exit(0) o no es lo ideal? (Suponiendo que esa memoria va a ser liberada por Linux cuando termina el programa).

Más que nada la duda viene por el lado de que tenemos varios hilos abiertos para el servidor, en espera bloqueante por recv y accept, y no se nos ocurre cómo cancelarlo. Para la memoria pedida por la parte de planificación/deadlock no hay problemas.

Gracias!

**Comment by iago64** [comment]
Buenas buenas!

TL-DR: Mientras no tengan leaks en la ejecución no hay mayores inconvenientes.

Explicación larga:
En el mundo ideal, deberían encargarse de limpiar la memoria, para matar los threads podrían fijarse como funcionan pthread_cancel() o pthread_kill(), pero en ambos casos no es algo tan critico, ya que una vez finalizado el proceso el SO se encarga de liberar todo lo que les quede dando vueltas.
Ahora si la duda viene del lado de los memory leaks, lo mas importante es que su proceso no tenga leaks mientras ejecuta (ya que eso si por ej el broker esta corriendo constantemente en algún momento les va a detonar la memoria y el SO se los puede llegar a matar por Out of Memory, pero de nuevo, es importante mientras ejecuta y es el famoso definitively lost de valgrind, lo de still reachable no es un leak per se, ya que al momento de finalizar tenían las referencias para eliminarlo :)

Abrazo.-

**Comment by gebonora** [comment]
Gracias, lo tenemos en cuenta!

Saludos!
