### ISSUE TITLE
[GameBoy][GameCard]  ¿ A quién le manda APPEARED GameCard cuando recibe el NEW desde GameBoy?

### ISSUE THREAD

**Issue by cesarmateos** [sisoputnfrba/foro#1804]
Estimados, 
Una consulta.

¿ Cuando GameCard recibe un New_Pokemon desde GameBoy, el Appeared_Pokemon se lo manda a GameBoy o a Broker ?   Yo hasta ahora hacía que se lo mande a Broker.  Van quedando todos los procesos en espera hasta que haya una conexion abierta con Broker que les permita enviar sus Appeared.

**Comment by karengrams** [comment]
¡Buenas!

Al parecer tuviste un problema para crear el issue, lo cierro así podes abrir uno con la consulta especifica

Saludos :)

**Comment by karengrams** [comment]
¡Ahi vi que lo modificaste! Asi que lo reabro y te respondo. 

Cuando se recibe el NEW por parte del Game Boy (es como si lo hubiera recibido por parte del Broker), la respuesta que deba dar el Game Card deberá ser enviada al Broker (el Game Boy lo único que va a hacer es mandar mensajes, y cuando se subscriba, recibir específicamente en ese caso).

En el [anexo I](https://docs.google.com/document/d/1be91Gn93O2Vp8frZoV1i5CmtOG0scE1PS8dMHsCP314/edit#heading=h.1jlao46) se especifican todos los flujos de mensajes.

¡Saludos!

**Comment by cesarmateos** [comment]
Perdón Karen, buscando los corchetes, apreté un shortcut desconocido por mi y se envió antes de terminar.

**Comment by cesarmateos** [comment]
Perfecto Gracias!

**Comment by karengrams** [comment]
No pasa nada, ¡cualquier cosa estamos por acá!
Saludos 😸
