### ISSUE TITLE
[Broker] FRECUENCIA_DE_COMPACTACION, busquedas fallidas o particiones eliminadas?

### ISSUE THREAD

**Issue by Frank115** [sisoputnfrba/foro#1806]
Buenas noches, tengo una consulta, en este #1782 issue (quise comentarlo pero no lo podia abrir)  se dijo que el "contador" significa: _"cantidad de particiones que eliminé para guardar este mensaje"_, y además se dijo que _"primero compacto, luego elimino"_. 

Me lleva a pensar que si FRECUENCIA_DE_COMPACTACION es 1 va a tener un comportamiento distinto que si fuera 0.

Si es 1, en la primer corrida busco (no encuentro), (no compacto), elimino. En la segunda, busco (no encuentro) y ahi compacto.
No es lo mismo que compactar siempre (como lei en algunos comentarios).

Básicamente: El contador lo incremento cuando eliminé una particion como dijimos, o cuando se falló al buscar una partición ? (pienso que la segunda esta mas cerca a lo que dice el enunciado)

**Comment by foviedo** [comment]
Hablando con mis ayudantes asignados, y a partir de explorar issues y leer el enunciado, llegamos a la conclusión de que el contador lo incrementás cuando se falló al buscar la partición, además de ajustarse mejor a lo que dice el enunciado, también hace que se te cumpla lo de que 1 es compactar siempre (porque si no te va a pasar que compactás, volvés a buscar, compactás volvés a buscar... en loop infinito)

**Comment by fgiannotti** [comment]
Si ese fuera el caso, habría que revisar el test de compactacion_basico. Porque hasta donde tengo entendido, se asume que se van a eliminar particiones.

**Comment by sebastiangilberto** [comment]
Buenas, nosotros entendimos lo mismo que vos @Frank115 .

Lo paso en resumen a ver si aclara algo, o si nos corrigen así ya hacemos las modificaciones en el TP.

La **FRECUENCIA_COMPACTACION** es la cantidad de particiones que tuviste que liberar/eliminar para poder guardar tu mensaje.

Por cada mensaje nuevo vas a tener que tener un contador o algo local a ese mensaje, llamémoslo `cantidadQueMateParaEsteMsj`, y que arranca en 0 por mensaje.

Con eso en mente y entendiendo que la condición de compactación es: `cantidadQueMateParaEsteMsj == FRECUENCIA_COMPACTACION`, nos quedaron estos escenarios:

**F = FRECUENCIA_COMPACTACION**

- F(-1): no compacto nunca porque `cantidadQueMateParaEsteMsj` nunca va a poder ser -1 (arranca en 0)
- F(0): compacto antes de intentar matar ya que `cantidadQueMateParaEsteMsj` arranca en 0 y ya se cumple la comparación
- F(1): tengo que matar 1 sola partición y si aún no hay lugar para el dato, ya tengo que compactar, porque la `cantidadQueMateParaEsteMsj` ya va a ser 1
- F(>1): tengo que matar hasta `n` particiones antes de poder compactar, siendo `n` la `F`

Al menos esto es lo que sacamos, entre los issues que vimos/cargamos y el enunciado.

Saludos!

**Comment by Nico-0** [comment]
Yo lo tome como que si la frecuencia esta en 0 en el config, la cambio a 1. Esta bien esto?

**Comment by nahuemazzeo** [comment]
Hola Chicos!! Como andan? 

Paso a resumir el flujo:

1. Reemplazo una partición.
2. Consolido
3. Verifico si debo Compactar (por medio de la frecuencia de compactación).
4. Veo si puedo almacenar la partición deseada. Si no entra, vuelvo al paso 1
5. Guardo la partición.

Si la frecuencia de compactación es 0 o 1 en el punto 3 siempre voy a compactar. 
Si la frecuencia es 0 siempre en este paso 1 va a ser mayor que 0
Si la frecuencia es 1 acabo de reemplazar una partición por lo que mi valor actual es 1, entonces compacto.

De esta manera el valor se actualiza siempre que reemplazo una partición.

Saludos.

**Comment by Frank115** [comment]
Hola Nahue, si con reemplazar una particion te referis a liberarla/eliminarla, entonces no estoy de acuerdo con el flujo que mencionas. El enunciado dice que primero chequea si hay que compactar(paso 2) antes de liberar alguna particion (paso 3).
Por ende pienso que tus paso 1 y 2 irian luego del paso 3. 

Y si fuera así, y el valor se actualiza cuando reemplazo una particion como dicen, frec=1 y frec=0 no es lo mismo porque el chequeo de compactacion se haria antes de eliminar (para el caso frec = 1 primero tendria que eliminar una particion es decir en la primer vuelta ignoraria compactar)

Gracias! 👌🏼

**Comment by nahuemazzeo** [comment]
Hola @Frank115 

Entiendo tu punto y lo que dice el TP y creo que mi ciclo indicado arriba es un resumen de lo que dice el TP sin incluir el "vuelvo a buscar en los pasos indicados. Pensemos y cambiemos el orden de los puntos:

1. Veo si puedo almacenar la partición deseada. Si puedo hacerlo paso al paso 6.
2. Verifico si debo Compactar (por medio de la frecuencia de compactación). Si compacte, vuelvo a verificar si puedo almacenar la partición deseada. Si puedo hacerlo paso al paso 6.
3. Reemplazo/Elimino una partición.
4. Consolido
5. Veo si puedo almacenar la partición deseada. Si no puedo hacerlo, vuelvo al paso 2
6. Guardo la partición.

Entras por primera vez, no podes. Compactas, reemplazas una pagina, Consolidas. Si podes almacenar lo haces. Esto seria frecuencia 0.
Entras por primera vez, no podes. Compacto, reemplazo una pagina y consolido. No puedo, vuelvo a compactar, busco y encuentro para almacenar. Esto seria frecuencia 1

Si ves, es el mismo ciclo que explica el TP pero yo lo explique reducido en el punto anterior. Cito al TP para que vean que no estoy diciendo nada contrario al mismo.

> Procedimiento para almacenamiento de datos
>1. Se buscará una partición libre que tenga suficiente memoria continua como para contener el valor. En caso de no encontrarla, se pasará al paso siguiente (si corresponde, en caso contrario se pasará al paso 3 directamente).
>2. Se compactará la memoria y se realizará una nueva búsqueda. En caso de no encontrarla, se pasará al paso siguiente.
>3. Se procederá a eliminar una partición de datos. Luego, si no se pudo encontrar una partición con suficiente memoria como para contener el valor, se volverá al paso 2 o al 3 según corresponda.


Saludos.

**Comment by Frank115** [comment]
Hola Nahue. Gracias por ir respondiendo. (Y detalladamente con el flujo y los casos de uso, sirve muchisimo para resolver esto)

Ahora quedo claro el flujo. Lo que no me sigue quedando claro es el mismisimo titulo del issue.

Porque me mencionaste que: 

> el valor se actualiza siempre que reemplazo una partición.

(No es exactamente lo que dice el enunciado, pero no va al caso)
Ok, de acuerdo.  Si esto es así, aca hay un problema:

> Entras por primera vez, no podes. Compacto, reemplazo una pagina y consolido. No puedo, vuelvo a compactar, busco y encuentro para almacenar. Esto seria frecuencia 1

Dentro de lo que entendí de lo que fuimos diciendo, no compactarías en la primer vuelta. Porque `el valor se actualiza siempre que reemplazo una partición.` Pero si compactarías en la segunda vuelta. Lo cual no es lo mismo si actualizarias el contador cuando `buscaste y no encontraste`.

Espero poder haberme dado a entender.
Sinceramente, no estoy de ninguno de los dos lados. Simplemente quiero entender cual sería el comportamiento esperado.

Gracias

**Comment by nahuemazzeo** [comment]
Hola @Frank115. 

Es correcto lo que decis. Esta mal escrito de mi parte. Si el valor es 1 es correcto que la primera vez cuando levantas el proceso broker no se compacte pero en caulquier siguiente iteracion deberia hacerlo

Digamos que la diferencia entre el 0 y el 1 seria la primera iteracion global del proceso broker en el cual no se compactaria pero luego siempre si.

A fines practicos, del tp y los test no afecta entiendo.

Saludos.

**Comment by Frank115** [comment]
Genial Nahue, aunque no logro entender por qué seria solo para la primera vez globalmente hablando y no para todos los casos. 
Que es lo que cambia para que solo ocurra esa vez?

Gracias!

**Comment by RodrigoLista** [comment]
Buenas. Nosotros despues de leer todos los issues respectivos a este tema, con todas las explicaciones y aclaraciones que hubo,  entendimos lo mismo que @sebastiangilberto. Y lo terminamos implementando de esa manera.

**Comment by iago64** [comment]
Buenas!
Cuando compactas reseteas el contador ya que podrías tener mas de una compactación para un mismo mensaje

Saludos.-

**Comment by BelenTripodi** [comment]
Una pregunta mas: no termino de entender el tema del flujo para el caso 0.
Segun lo que recopilé seria: 
1) busco una particion
2) Si hay, guardo. Si no hay como mi contador y frecuencia de compactacion son iguales (=0) voy a compactar. (Ahi se restartearia el contador?)
3) Vuelvo a buscar. Si no encuentro, debo eliminar una particion y consolidar. 
4) Vuelvo al paso 1.

No le encuentro mucha logica a restartear el contador luego de una compactacion... no representaba particiones eliminadas? En el caso que describí recien, no habria particiones eliminadas en el paso dos que es donde entendi que se restarteaba el contador de particiones liberadas. Ademas si paso al paso 3 y elimino, cuando vuelvo a buscar ya mi contador esta en 1 y no volveria a compactar....

Para los casos que no son 0, tambien hay que restartear el contador luego de la compactacion?

**Comment by iago64** [comment]
Buenas!
El flujo con 0 es que siempre: 
compactas 
buscas
eliminas
volvés a compactar

El contador de particiones eliminadas, cada grupo lo puede implementar de formas diferentes, por eso es que es importante que entiendan el flujo en lo teórico y no asociándolo a cada caso particular, porque puede ser que el contador empiece en 0 y lo aumenten hasta llegar al numero de particiones o que lo empiecen en el número de particiones y le descuenten hasta llegar a 0 para compactar.

Saludos.-

**Comment by karengrams** [comment]
¡Alo!

¿Como estan? Espero que bien. ¿Podemos cerrar el issue?

¡Saludos!

**Comment by Frank115** [comment]
Hola, me quedo una pregunta colgada respecto a la última respuesta de @nahuemazzeo , con eso creo que ya estoy

**Comment by nahuemazzeo** [comment]
Hola @Frank115. Mil disculpas, entendí que @iago64 había respondido la misma en su momento.

La frecuencia de compactación indica "cada cuantas particiones liberadas se debe compactar". Dicho esto, dependiendo la implementación esta frecuencia puede ser global o no. 

Es decir, se puede implementar como que es global para todas las particiones, que en ese caso solo una vez iniciaría en 0 ya que después siempre se sumaria uno por cada iteración y se compactaría siempre o puede hacerse a nivel de pagina a almacenar por lo que siempre que quiera almacenar una partición empezaría en 0.

En esta diferencia de implementación radica la frase de "solo la primera vez".

Saludos.

**Comment by Frank115** [comment]
Perfecto, quedo claro, gracias @nahuemazzeo .

Cierro el issue.

Abrazo!
