### ISSUE TITLE
[TEAM] Dudas acerca de LOCALIZED_POKEMON

### ISSUE THREAD

**Issue by julchat** [sisoputnfrba/foro#1807]
Hola, buenas tardes, vengo de leer el issue #1749 y venía entendiendo todo bien hasta que lei algo que me llamo mucho la atención

![Screenshot_10](https://user-images.githubusercontent.com/48997230/85930272-60ade800-b891-11ea-9178-c9f2c3e10e1a.png)

> Guardas todas las instancias, ya que eventualmente en 1-2 puede que cuando llegues ya lo haya atrapado otro entrenador y bueno... te toque ir a buscarlo a la otra posicion :)

No estaría mal hacer eso? Digo, ando necesitando 1 solo pokemon de esa especie, acepto dos dentro del mapa, va un entrenador y atrapa al que esta en 1-2 y despues el otro que estaba va a ir a capturar al que quedaba, y voy a tener un problema a gran escala porque me va a sobrar 1 pokemon que no necesitaba, y me va a faltar 1 "slot" para un pokemon que si necesitaba.
Yo hubiera intuido que si recibia 2 y solo necesitaba 1, agarraba el primero y el segundo lo descartaba.

Y ya que estamos, 

> Localized Pokémon: el proceso Team se suscribirá de manera global a esta cola de mensajes. Al recibir uno de los mismos deberá realizar los siguientes pasos: verificar si ya recibió en algún momento un mensaje de la especie del Pokémon asociado al mensaje. Si es así, descarta el mensaje (ya sea Appeared o Localized).

Los mensajes appeared / localized que descarte, también los voy a registrar como recibidos y como motivo de descarte de un localized? O solo los que acepto? O para los localized, los registro apenas pasan el filtrado por ID o también registro aquellos que no lo pasan?

Gracias y saludos

**Comment by julchat** [comment]
Adicionalmente, como realizo el filtrado por el ID?
Digo por el tema de que tengo entendido de que los gets no se mandan 1 vez por especie, sino 1 vez por cada pokemon que necesito, independientemente de la especie.

Entonces si me llegara 1 mensaje localized con 2 pokemones, habiendo hecho yo 2 GET de ese pokemon, tengo 2 ID (uno por cada get) y del lado del localized, uno solo, por el mensaje. Con que uno coincida es condicion suficiente para que el localized pase el filtrado de ID?

**Comment by miguel-t** [comment]
Hola @julchat  te comento lo que entendi.

Los mensajes get que envias cuando el proceso team inicia son por **especie**,en el video de planificacion (5:28) te explica . Despues cuando broker te responda el mensaje GET que  enviaste te devuelve el id_correlativo .lo guardas, y despues vas usar este id_correlativo  para filtrar los mensajes que te lleguen en la **cola localized**.

Saludos.

**Comment by iago64** [comment]
Buenas
Vamos en orden:
En el mapa pueden tener todo lo que gusten, mientras que vos tengas en claro que necesitas uno, suponete el caso de que tu objetico es conseguir solo 1 Zigzagoon y en el localized te llegan 3 posiciones, tu situación seria mas o menos como la siguiente imagen:
![image](https://user-images.githubusercontent.com/1622109/85955324-1b9eba00-b954-11ea-8942-9a5e69c2ce71.png)

Ahora esto no seria problema ya que vos atrapas 1 y listo, las demas posiciones podes olvidarlas ya que simplemente no te importan.

Respecto al GET / LOCALIZED, el enunciado dice lo siguiente:

> El objetivo del mismo es obtener todas las locaciones de una especie de Pokemon. De esta manera, al iniciar el proceso, por cada especie de Pokémon requerido se debe enviar un mensaje a la cola de mensajes GET_POKEMON del Broker.

Con lo cual, como bien dice @miguel-t cuando tengas la respuesta del GET con el ID del mismo, después todos los LOCALIZED que te lleguen solo van a importarte los que tengan como ID correlativo alguno de los ID de los GET que enviaste.

Saludos.-

**Comment by julchat** [comment]
Ok, suponiendo lo que acabas de decir entonces,
Tengo 2 zigzagoons en el mapa (y ningún otro pokemon), y 2 entrenadores libres, y solo necesito 1 zigzagoon.
Mando a 1 de los entrenadores a capturar el primer zigzagoon, mientras que el otro entrenador va a estar esperando a que haya un nuevo pokemon para atrapar, o, el primer entrenador fracase en capturar al zigzagoon. Es así?
O debería mandar a los dos a capturar a 1 cada uno y cuando uno de ellos atrape a un zigzagoon, "aborto" de alguna manera la operación de moverse y capturar del otro entrenador?

Y otra cosa que quedo en el post arriba,

>  Los mensajes appeared / localized que descarte, también los voy a registrar como recibidos y como motivo de descarte de un localized? O solo los que acepto? O para los localized, los registro apenas pasan el filtrado por ID o también registro aquellos que no lo pasan?

Gracias y saludos

**Comment by iago64** [comment]
Buenas!
Solo vas a mandar a 1 entrenador a atrapar y el otro se va a quedar esperando a ver que pasa con el primero.

Saludos.-

**Comment by julchat** [comment]
Buenisimo gracias, me quedó bien entendido
Y de lo último que comente sabés algo?
De 

> Localized Pokémon: el proceso Team se suscribirá de manera global a esta cola de mensajes. Al recibir uno de los mismos deberá realizar los siguientes pasos: verificar si ya recibió en algún momento un mensaje de la especie del Pokémon asociado al mensaje. Si es así, descarta el mensaje (ya sea Appeared o Localized).

Registro que recibí un mensaje de esa especie del pokemon, para luego rechazar localized que sean de esa especie si me llegan,  si:

- Descarto un mensaje appeared (no necesito el pokemon)?

- Descarto un mensaje localized (no necesito esa especie de pokemon)?

-Descarto un mensaje localized por ID incorrecto (no coincide con ninguno de mis GET_POKEMON)?

Gracias y saludos

**Comment by iago64** [comment]
Buenas!
Se me paso esa parte, mil disculpas.
Si ya tienen info de la especie (ya sea por localized o appeared) descartan todo lo demás sin importar si necesitan mas de ese pokémon (es medio raro este comportamiento pero es algo que les agregamos para poder forzar algunos comportamientos, por ejemplo que un team quede en starvation porque no puede capturar algún pokémon)

Saludos.-

**Comment by julchat** [comment]
Claro pero si tengo este escenario:

Mando GET_POKEMON especie A, consigo ID 1

Recibo LOCALIZED_POKEMON especie A, con ID 3 (Lo descarto por ID equivocado)
Recibo LOCALIZED_POKEMON especie A, con ID 1
Descarto ese ultimo mensaje porque ya recibi un LOCALIZED de esa especie? O en este caso, lo acepto?

**Comment by iago64** [comment]
Los filtros en orden de aplicación deberían ser:

1. ID Correlativo (solo para LOCALIZED)
2. Especie (LOCALIZED y APPEARED)

Lo importante es que si te llega un APPEARED justo antes de que te llegue la respuesta del GET (LOCALIZED) te quedas con el APPEARED en lugar del LOCALIZED.

Abrazo.-

**Comment by julchat** [comment]
Claro claro pero si ese APPEARED hubiera sido descartado, acepto el LOCALIZED o lo rechazo?
Y si, en otro caso, antes me llego un LOCALIZED con ID erroneo de la misma especie, y luego me llega el LOCALIZED correcto de esa especie, lo descarto por haber recibido un LOCALIZED de esa especie anteriormente, o lo acepto porque el mensaje ese viejo fue descartado?

Gracias

**Comment by ncoen97** [comment]
Buenas.
Si el primer Localized lo rechazaste por id erróneo no cuenta como que te llegó un Localized de esa especie. Tené en cuenta que:
> verificar si ya recibió en algún momento un mensaje de la especie del Pokémon asociado al mensaje. Si es así, descarta el mensaje (ya sea Appeared o Localized*).

*Solo cuenta para los Appeared y Localized de esa especie que sí aceptaste.

Saludos!

**Comment by julchat** [comment]
Buenísimo era eso lo que me faltaba saber, muchas gracias
