### ISSUE TITLE
[Broker] Tamaño strlen

### ISSUE THREAD

**Issue by FranciscoDumont** [sisoputnfrba/foro#1808]
Hola, nos surgió una duda con respecto a como guardamos el tamaño de las estructuras. 

Nosotros estamos guardando, por ejemplo, un get pokemon de esta forma:

``` c
get_pokemon->nombre_pokemon_length = strlen(nombre_pokemon) + 1;
get_pokemon->nombre_pokemon = nombre_pokemon; //nombre_pokemon es un char*
```

Donde un "GET_POKEMON Pikachu" ocuparía **12 bytes** (4 del uint32_t + las 7 letras de "Pikachu" + 1 por el \0)

 En el enunciado dice:

> Tamaño de Get Pokemon
> Este mensaje tendrá el nombre del pokemon. Un ejemplo del mensaje es: 
> ‘Pikachu’
> Viéndolo a nivel tipo de dato vamos a tener un uint_32 para saber el largo del nombre del pokemon y luego el nombre del pokemon. Este ejemplo tendrá un tamaño de **11 bytes** en memoria principal (lo que ocupa un uint_32 más el largo del nombre del pokemon).

Lo que nos genera una diferencia de un byte, que notamos cuando corremos las pruebas.

  **En resumen:**
  Está bien que guardemos con strlen **+ 1** o no debemos tener en cuenta el último \0 del string ?

**Comment by foviedo** [comment]
Qué coincidencia, venía a escribir este mismo issue
De parte de mi grupo, tenemos todo el tp basado en que el length es strlen(nombrePokemon) + 1
Cuando fue el checkpoint presencial, aparentemente varios grupos hicieron esto mismo y quien nos corrigió dijo que iban a hablar sobre esto y por ahí sacaban una errata
Pasó el tiempo y todavía no salió la errata, así que me pegó el miedo de que en realidad está mal esto y que sea un motivo de desaprobación
Hace un rato traté de sacar los +1 y de primeras, me tira seg fault
En fin: Podemos dejar el strlen+1?

**Comment by julchat** [comment]
Con mi grupo tambien lo hicimos así, y no es raro que muchos lo hayamos hecho asi porque los que no sabiamos bien como empezarlo nos guiamos por como estaba en el tp0.

A ver, sentido tiene, cada caracter del stream es un byte, y te falta un byte mas por el \0.

Pero bueno me sumo a la nocion para ver si esta bien como lo hicimos o si necesitamos hacer un cambio groso a la estructura de serializacion
Gracias

**Comment by jcastagno99** [comment]
Me sumo a lo que comparten los chicos.

**Comment by RodrigoLista** [comment]
De nuestra parte tambien, lo desarrollamos de esta misma forma, sumandole un byte al nombre del pokemon.

**Comment by mgarciaisaia** [comment]
¡Aloha!

No vengo a dar una respuesta sobre si se va a erratear o no porque no estoy participando de esas decisiones este cuatri, pero sí quiero aclarar esta idea (que la escribió una persona acá, pero está implícita en todos los mensajes).

> A ver, sentido tiene, cada caracter del stream es un byte, y te falta un byte mas por el \0.

Agregar un caracter `\0` al final de cada string es la forma que tiene _el lenguaje C_ de representar strings internamente, y es la forma en que la biblioteca estándar del lenguaje lo realiza. Pero eso no significa que el universo todo tenga que representarlo del mismo modo.

Por ejemplo, habrán visto en la charla de serialización que una forma válida de representar un campo de tamaño variable (como bien podría ser un campo de tipo string) es poner primero una cantidad fija de bytes que representen la longitud de ese mensaje, y luego el mensaje.

Ponele que decidimos en nuestro protocolo que vamos a usar un único byte para determinar la longitud del mensaje con un entero sin signo, y luego va el mensaje.

```
| 4 | H | O | L | A | N | D | A | 0
```

Si encuentro estos bytes en memoria (dale, que acá los interpreté, pero podríamos decir que son los bytes `0x04 0x72 0x79 ...`), ¿alguien necesita un `\0` para saber que el string es "HOLA" y no "HOLANDA"?

Que C diga lo que quiera: nuestro protocolo dice que el string que hay ahí es "HOLA". ¿Qué hacen los bytes de `NDA\0` ahí? Ni la menor idea. No definimos tanto el protocolo aún. Pero lo que definimos me alcanza para saber que el mensaje es HOLA.

----

¿A qué apunto con todo esto? A que puedo tener representaciones de strings sin un `\0` al final. En particular, esto es cierto si _en algún otro lado_ tengo guardada la longitud de ese string.[1]

No tengo en claro qué dice el enunciado sobre esto, pero apostaría a que _en algún lado_ tienen alguna estructura que guarda la longitud de ese mensaje que están guardando. Si ese fuera el caso, entonces **no necesitan** guardar el terminador de string. Por lo que sería viable guardar los mensajes haciendo únicamente `strlen`, respetando lo que dice el enunciado.

Obviamente, para después leer esos strings van a tener que hacer un poquito más de laburo si quieren usar funciones de strings: van a tener que leer esos bytes a un cacho de memoria suyo que _además_ tenga un `\0` al final. Pero es realizable.

----

Sobre si pueden o no hacerlo de una u otra manera, lo que dije antes: no seré yo el que responda.

¡Éxitos!

[1] _Ustedes son muy jóvenes_, pero antes veíamos Pascal en Algoritmos, y en Pascal los strings se guardan en memoria prefijándoles un byte que indica el tamaño. Es decir, el ejemplo que mostré acá arriba bien podría ser un string válido de Pascal.

**Comment by iago64** [comment]
Buenas buenas!

Recién me percato que Mati dejo la posta para el tema del enunciado
Efectivamente en la memoria del broker no deberían guardar los \0, lo que no quita que después en todo el resto de la operatoria se lo puedan agregar y manejarlo con las funciones de string que tienen en C o en las commons.

Saludos.-

**Comment by FranciscoDumont** [comment]
Gracias a todos por responder, quedó super claro.
Cierro el issue, un saludoo!
