### ISSUE TITLE
Duda team - cambios de contexto y ciclos de cpu.

### ISSUE THREAD

**Issue by brianUtn98** [sisoputnfrba/foro#1809]
Hola! Cómo va? Tengo una duda sobre el módulo team ya que lo estoy terminando de cerrar y estoy haciendo los reportes finales. Pido disculpas de antemano porque estuve leyendo issues y no encontré concretamente lo que buscaba, pero quizás repita pregunta.

1. A qué se refiere con cambios de contexto? ¿Es cuando un entrenador empieza a ejecutar o cuando un entrenador cambia de cola de ejecución? (O quizás ninguna de las anteriores).
2. Cuando hablamos de la cantidad de ciclos de CPU no me quedó claro una cosa. Cuando se produce un intercambio, los 5 ciclos de cpu que se consumen son para ambos entrenadores o para el que se movió hasta la posición?

Gracias!

**Comment by ncoen97** [comment]
Buenas!
- En el contexto de nuestro trabajo práctico, los cambios de contexto ocurren cuando cambia el entrenador que está en el estado Exec.
- Los 5 ciclos de cpu representan el intercambio entre los dos entrenadores, por lo tanto se tienen que consumir una única vez.

Saludos.

**Comment by brianUtn98** [comment]
Hola @ncoen97 ! Gracias por responder tan rápido. 
1. Quedó clarísimo, gracias.
2. Me queda todavía la duda sobre que se consuman una única vez. Porque en definitiva a mi contador global de ciclos sumo sólo 5, pero también tengo que contar los ciclos que ejecutó cada entrenador y es ahí donde se me planta la confusión. Entonces solo cuento los ciclos para el entrenador que se movió?

**Comment by ncoen97** [comment]
Claro, el entrenador que se mueve hacia el otro es el único que consume ciclos de cpu en este caso (n de movimiento + 5 de intercambio).
Saludos!

**Comment by brianUtn98** [comment]
Gracias @ncoen97 ! Cierro issue.
