### ISSUE TITLE
Duda mensaje LOCALIZED con más de un pokemon en una posición

### ISSUE THREAD

**Issue by NicoCollazo** [sisoputnfrba/foro#1810]
Hola:

Supongamos que tengo 2 pikachus en la posición 1 2.

Al Broker, ¿le mando LOCALIZED pikachu 1 1 2, o le mando LOCALIZED pikachu 2 1 2 1 2 ?

**Comment by iago64** [comment]
Buenas buenas!

TL-DR: 
El LOCALIZED en ese caso va a ser `LOCALIZED pikachu 1 1 2`

Explicación:
La idea del Localized es la de informar en que posiciones hay pokemones, la cantidad propiamente dicha es algo que **solo** conoce el gamecard.

Saludos.-

**Comment by NicoCollazo** [comment]
Perfecto, muchas gracias!
