### ISSUE TITLE
[Broker] Algoritmo LRU - Ordenamiento de las particiones.

### ISSUE THREAD

**Issue by papa-caco** [sisoputnfrba/foro#1811]
Buenas tardes!

Esta mañana estuve consultando para poder ordenar correctamente las particiones mediante el algoritmo **LRU**.
Nosotros en nuestra estructura administrativa, para controlar los tiempos de acceso a las particiones, habíamos incluído el campo **"last_used"** de tipo **time_t**. Cuando ejecutábamos los scripts de prueba del broker: **compactacion_basico.sh** y **consolidacion_basico.sh** notamos que los valores registrados de "last_used" resultaban ser el mismo para todas las particiones que se creaban, ya que estos scripts, antes de hacer la suscripción, tardan menos de un segundo en ejecutarse. Estuvimos averiguando para cambiar el tipo de variable para que tuviera mayor resolución, del orden de los microsegundos.    

Juan Mesaglio (@mesaglio), en este post esta la función que nos recomendaste ver:  **https://stackoverflow.com/a/1444440**
la aplicamos y funcionó, solo que modifiqué la parte que divide los milisegundos por 1000. Le quité esa división y ahora sí a cada partición le deja un valor diferente y secuencial en mSeg.  Comparto por acá la función como quedó, por si alguien más se traba con este problema:

**uint64_t timestamp(void) {
    struct timeval valor;
    gettimeofday(&valor, NULL);
    unsigned long long result = (((unsigned long long )valor.tv_sec) * 1000 + ((unsigned long) valor.tv_usec));
    uint64_t tiempo = result;
    return tiempo;
}**

En nuestro **typedef struct: t_particion_dinamica** incluímos **uint64_t last_used;** y para registrar los valores hacemos referencia a la función de arriba:  **particion->last_used = timestamp();**

Bueno, agradecido Juan por el soporte de hoy. Saludos, buen finde!

**Comment by enogueiras** [comment]
Buenisima esta info, consulta, ¿esta bien que lo declaren como uint64_t? la VM es de 32 bits..

**Comment by papa-caco** [comment]
Hola Emilio, cómo andás?

Nosotros usamos la VM de la cátedra de 32 bits y está funcionando sin problemas.

![image](https://user-images.githubusercontent.com/35772622/85934843-425ee100-b8bf-11ea-8f3f-bf1f106179b0.png)
Pero los ayudantes tienen la posta. Esperemos ver qué dicen.
Saludos,

**Comment by iago64** [comment]
Aloha!

Antes que nada, @papa-caco mil gracias por compartir lo que validaste con @mesaglio 😄 

Respecto a tu pregunta @enogueiras efectivamente, no tiene nada que ver que sea una vm de 32 bits con un tipo de dato prefijado, la idea de que sea un `uint64_t` lo único que te dice es que es un entero que va a ocupar 64 bits (u 8 bytes), es miembro de la familia de enteros de tamaño fijo que tiene ademas:
- `uint8_t`
- `uint16_t`
- `uint32_t`
- `uint64_t`

El objetivo de esos tipos de datos es simplemente asegurar el tamaño del dato y nada mas, que eso muy útil cuando se tienen que trabar entre arquitecturas diferentes.

Saludos.-

**Comment by papa-caco** [comment]
Gracias Damian! Saludos!
