### ISSUE TITLE
[BROKER] consolidación en Buddy System

### ISSUE THREAD

**Issue by foviedo** [sisoputnfrba/foro#1812]
Buenas! como va? De antemano: disculpas por el issue tan largo, pero estamos hace un par de horas comiéndonos la cabeza con esto.
1)Problema en sí:
Tenemos un problema en lo que respecta a la consolidación recursiva (o en un while, el punto es que hay que no necesariamente se consolida una vez) que tenemos que hacer cuando se nos libera una partición en el esquema buddy system
La cuestión, no sabemos cómo hacer el algoritmo para detectar qué tengo que consolidar con qué, puesto que, a diferencia de con particiones, acá no puedo consolidar dos posiciones que simplemente estén contiguas
Nosotros tenemos dos listas, una de posiciones ocupadas, y otra de posiciones libres:
>typedef struct{
	void* posicion;
	int tamanio;
}PosicionLibre;

>typedef struct{
	int tamanio;
	void* posicion;
	int colaALaQuePertenece;
	int ID;
	int timestamp;
}PosicionOcupada;

2)Soluciones que se nos ocurrieron pero que no sirven
a)En un inicio lo que pensamos es, consolidamos las posiciones (libres obvio) que estén contiguas + tengan el mismo tamaño
Serviría en casi todas las situaciones, pero si se me llega a presentar, por ejemplo, que tengo 4 posiciones del mismo tamaño contiguas
pos1(O)(32)pos2(O)(32)pos3(O)(32)pos4(O)(32)
el grupo de buddys sería pos1-pos2 y pos3-pos4
Si en algún momento, libero pos2 y pos3, con el algoritmo que tengo se me van a consolidar esas, así que este método me queda descartado
b)
Necesitaría reconocer cuáles son buddys de cuales, en un inicio pensamos en ponerle un ID de buddy o algún flag que indique es una posición izquierda o una derecha
Pero ocurre el problema que cuando yo divido en 2, la posición que tenía originalmente desaparece, vease, tengo una memoria de 256
(nótese que el número de posicion es sólo el subindice en la lista y nada más, tengo el puntero obviamente para saber cuál va en qué posición)
posicionesLibres = {pos0(256)}
* Inserto una de 63
posicionesLibres = {pos0(128)(izquierda),pos1(128)(derecha)}
vuelvo a dividir porque todavía me sobra
posicionesLibres = (pos0(64)(izquierda),pos1(64)(derecha),pos2(128)(derecha))
inserto 
posicionesLibres = (pos0(64)(derecha),pos1(128)(derecha))
posicionesOcupadas = (pos0(64)(izquierda))
* Ahora, borro la de 64
PosicionesLibres = (pos0(64)(izquierda),pos1(64)(derecha),pos2(128)(derecha))
* Tengo que consolidar y acá se me presenta el problema 
posicionesLibres = {pos0(128)(izquierda? derecha? tengo forma de saberlo?),pos1(128)(derecha)}
En este caso particular, podría ver que a mi derecha tengo un 128 derecho y sabría que yo soy su izquierda, pero si esta posición en vez de ser de 128 fuera de 64 o de 256, no tendría nada para tomar de referencia

3) Posible solución?
Se nos ocurrió tener una estructura paralela a nuestras listas de posicionLibre y posicionOcupada
Sería un árbol binario, como vendría a ser parecido al es buddy system realmente. estaría compuesto así:
>struct posicionBuddy{
int tamanio;
int izquierdaODerecha;
void* posicionEnMemoria;
struct posicionBuddy* izq;
struct posicionBuddy* der;
}

El árbol completo lo armaría apenas se inicia el broker, desde la raiz hasta las hojas del TAMANIO_MINIMO_PARTICION, cuando tenga que consolidar, hago una búsqueda a través del árbol, buscando por la posicionEnMemoria y retornando izquierdaODerecha y así poder saber en qué dirección consolidar si tengo el conflicto que describí en el punto 2a)
Pros: funciona? Creo
Contras: todas

4) Aceptar la recursada:
Hay una forma más simple de hacer esto? 
Gracias y saludos!

**Comment by iago64** [comment]
Buenas!
La solución de aceptar la recursada te diría que por ahora la descartes ya que como soluciones hay varias para el caso de buddy system y depende mucho de como les guste codearlas.
Algo importante que tienen que tener en cuenta es que buddy system, trabaja bajo el concepto de árboles donde los nodos se van dividiendo, con lo cual, si piensan alguna forma "copada" de escribir _el árbol en una lista o en una lista de listas, o en una listas de listas de listas_ o _en una estructura donde cada padre tenga 2 hijos (ya que son arboles binarios)_, su problema se pueda resolver un poco mas simple 😉 

Saludos.-

**Comment by ncoen97** [comment]
Buenas, otra recomendación que les puede servir si es que van a armar una estructura tipo árbol es añadirle un atributo que sea el id de la partición padre, luego para ver si dos particiones son buddys simplemente comparan los padres.
Suerte!

**Comment by afilgueira** [comment]
Hay otra solución, pero es demasiado mágica... tanto, que está sólo explicada en dos lugares:

![image](https://user-images.githubusercontent.com/1786754/85959853-506f3900-b975-11ea-9c1b-8451cf22f085.png)
y las PPTs de Nati 😄 

Si querés saber si dos particiones son buddy tomás los inicios de ambas particiones (les voy a llamar B1 y B2) y haces `B1 = B2 XOR tamaño de la particion`?. Si la respuesta es sí, son buddies.

Tomemos un ejemplo, con 32 y particiones de tamaño 8

Las particiones que arrancan en 0 y 8 son buddies, pero 16 no. Ahora, 16, es buddy de 24.
En binario: 0 -> 00000 | 8 -> 01000 | 16 -> 10000 | 24 -> 11000

```
Probemos 0 y 8
8 -> 01000 XOR 01000 = 00000 -> 0 => Son buddies
Probemos 16 y 8
16 -> 10000 XOR 01000 = 11000 -> != 0 => No son buddies
```
Si lo implementan bien, se evitan ids, arboles, etc etc etc... pero es todo un desafío!

Saludos!

**Comment by MatiMon** [comment]
Buenas @afilgueira , antes que nada gracias por tu aporte.
Una duda: 
Tengo tres bloques contiguos con inicio en A (de 512), B (de 512) y C (de 1024).
Puede ser que al hacer B = (C xor 1024) me retorne 0 (son buddies) cuando debería retornar !=0 (no son buddies)?

Saludos!

**Comment by afilgueira** [comment]
Es que tenés que hacerlo con particiones del mismo tamaño. Si no tienen el mismo tamaño, no son buddies por definición. Saludos!

**Comment by karengrams** [comment]
¡Buenas buenas!

¿Todo bien? Espero que si. ¿Cerramos el issue? ¿Quedo algo suelto?

¡Saludos!

**Comment by karengrams** [comment]
¡Alo @foviedo!

Cierro el issue por inactividad, cualquier cosa que no haya quedado resuelta, no dudes en volver a abrirlo y lo vemos.

Saludos.

**Comment by foviedo** [comment]
MIl disculpas @karengrams por algún motivo al mail se le ocurrió mandarme estos mails a spam y como estaba concentrado con los parciales no me estuve fijando directamente.
Al punto @afilgueira : esta técnica me está funcionando de forma MUY rara, detallo situaciones con las que me encuentro. Situación 1-> memoria de 128B, le mando 4 mensajes de 32B para llenarla, se llenan correctamente
Luego, envio un 5to mensaje de 64B, el algoritmo al ser FIFO, debería eliminar los mensajes 0 y 1, consolidar a izquierda (osea, cuando borro el 1, noto que tengo un buddy a izquierda).
Realidad-> Me elimina el mensaje 0, 1 y 2 y entonces, consolida a izquierda, el 1 y 2 y yo quedo ¿?

Traté de probar algo parecido, en la que en vez de hacer B1 == B2 XOR tamaño de la particion hago !(B1 == B2 XOR tamaño de la particion) y negando así (aunque con altas probabilidades de que lo que esté adentro de 0 por cualquier cosa y al negarlo me da 1) funciona en la situación 1 y también en:
Situacion2 -> inserto 5 mensajes, de forma que el mensaje de posicion 0 sea el último que entró
Luego, envío un 6to mensaje, nuevamente algoritmo FIFO, lo que va a hacer es eliminar la posicion 1, luego la 2 y luego la 3 para consolidar a izquierda, la 2 con la 3 y efectivamente, funciona!
Genial digo, a Adro se le habrá escapado el ! y era así en realidad

Hago una segunda prueba seguida de la situación 2-> inserto un mensaje que ocupe 128B, la memoria entera. Debería consolidar 2 veces hasta llegar a una sola posición de 128
Realidad->borra todas las particiones, mi if no detecta ningún buddy así que no consolida nada y mi algoritmo al sólo encontrar 4 particiones de 32 y ninguna de 128, me tira un hermoso Seg Fault
Viene mi duda, qué estoy haciendo mal? D:
Acá detallo la función que hace la parte importante, sin las negaciones:

`void consolidarBS(int posicion){
	PosicionLibre* posicionBase = list_get(listaPosicionesLibres,posicion);
	int tamanioPosicionesLibres = list_size(listaPosicionesLibres);
	printf("\n llego a esta funcion? la posicion es %i",posicion);

	if(posicion>0){ //primero va posicion a izquierda
		puts("tengo algo a izquierda");
		PosicionLibre* posicionAIzquierda = list_get(listaPosicionesLibres,posicion-1);
		printf("\nLa posicion de la izquierda arranca en %p y termina en %p. la posicion base empieza en %p",posicionAIzquierda->posicion,posicionAIzquierda->posicion + posicionAIzquierda->tamanio,posicionBase->posicion);
		if((posicionAIzquierda->posicion + posicionAIzquierda->tamanio) == ((posicionBase->posicion)) && (posicionAIzquierda->tamanio == posicionBase->tamanio) && !((int)posicionAIzquierda->posicion == ((int)posicionBase->posicion^posicionAIzquierda->tamanio))){
						puts("efectivamente puedo consolidar a izquierda");
						posicionAIzquierda->tamanio+= posicionBase->tamanio;
						free(posicionBase);
						list_remove(listaPosicionesLibres,posicion);
						puts("acabo de consolidar a izquierda en BS");
						consolidarBS(posicion-1);
		}
	}
	if(posicion != tamanioPosicionesLibres-1){ //me fijo si tengo algo a la derecha
		puts("\ntengo algo a derecha");
		PosicionLibre* posicionADerecha = list_get(listaPosicionesLibres,posicion);
		if(((posicionBase->posicion + posicionBase->tamanio) == posicionADerecha->posicion) && posicionBase->tamanio == posicionADerecha->tamanio && !((int)posicionADerecha->posicion == ((int)posicionBase->posicion^posicionADerecha->tamanio))){
			puts("\nvoy a consolidar a derecha");
			posicionBase->tamanio+= posicionADerecha->tamanio;
			free(posicionADerecha);
			list_remove(listaPosicionesLibres,posicion+1);
			puts("\nacabo de consolidar a derecha en BS");
			consolidarBS(posicion);
		}
	}
}`

**Comment by afilgueira** [comment]
Buenas! El algoritmo en sí es sencillo y entiendo que "a mano" funciona para tu caso también.

Te aconsejo mirar esta linea con atención. Es posible que los diferentes parámetros que pasás no tengan los valores exactos que esperás y eso esté influyéndote.

`if((posicionAIzquierda->posicion + posicionAIzquierda->tamanio) == ((posicionBase->posicion)) && (posicionAIzquierda->tamanio == posicionBase->tamanio) && ((int)posicionAIzquierda->posicion == ((int)posicionBase->posicion^posicionAIzquierda->tamanio)))`

(si podés sacar esas condiciones a variables te va a ser más fácil de ver inclusive)

Saludos!

**Comment by foviedo** [comment]
Buenas buenas, para el que le sirva: Al final el problema era que yo estoy trabajando con posiciones reales de memoria (esa posicionBase->posicion me devolvía un 0xHHHHHHHH) y aparentemente tenían que ser posiciones relativas (como en el ejemplo de Adro, 0, 32 y así)
Gracias @afilgueira, cierro esto :)
