### ISSUE TITLE
[Broker] Caída y recuperación de un proceso

### ISSUE THREAD

**Issue by Kvothe838** [sisoputnfrba/foro#1813]
Buenas. Con mi equipo leímos los issues que hay en el foro acerca de la caída y recuperación de un proceso, y entendemos que la identificación por parte de Broker del proceso se realiza justo para que cuando pasa algo así, no se envíen los mensajes de la caché que ya se enviaron a este proceso.
Nos inventamos que cada módulo le envíe un ID a Broker en la suscripción, de tal manera que si Broker ya tenía guardado el socket 12345 para el id 1 (Broker), y recibe una suscripción de un id 1 y el socket es diferente, lo actualice, entonces todo lo que ya se le había enviado no se le va a volver a enviar.
El problema es cuando pensamos que se pueden tener varios procesos del mismo módulo ejecutando, como es el caso de Team. Ahí el inconveniente es que todos le van a enviar id 2 (Team), entonces si se cae un equipo, cuando se reconecte va a provocar que los mensajes se envíen sólo a ese equipo. Pensamos diferenciar cada proceso generando algún tipo de id y enviándoselo a Broker, pero si se cae, no va a poder recuperar ese id nunca. Entonces...

1. Cuando se habla de que un proceso se pueda caer, en el caso de Team, ¿sería que un proceso sólo se caiga o lo estamos interpretando mal y vendría a ser que todo el módulo se caiga?
2. En caso de haber interpretado bien el 1, y dado que lo que planteamos no funcionaría, ¿se podría agregar a la configuración de Team un id por cada equipo? Es lo único que se me ocurre, ya que así es un dato guardado en un archivo (siempre va a estar, por más que se caiga un proceso) y es un id para cada equipo, por ende no hay confusión.

Y si nada de esto está bien, ¿podrían tirar alguna pista? Jaja.

Gracias.

**Comment by iago64** [comment]
Buenas buenas!

1.- La idea es que se puedan caer de a 1 los procesos, por ejemplo, si tenes 3 teams, que solo se caiga 1.
2.- Si les resulta mas cómodo el config, pónganlo en el config, si les resulta mas fácil recibirlo por parámetro al inciar el team, háganlo de esa forma, no hay ningún problema

Saludos.-

**Comment by iago64** [comment]
@Kvothe838 Quedo algo pendiente? se entiende la respuesta?

Saludos.-

**Comment by Kvothe838** [comment]
Perdón, colgué en responder. Se entiende perfecto, muchas gracias!
