### ISSUE TITLE
Dudas del Team de Appeared Pokemon y cambios de contexto

### ISSUE THREAD

**Issue by MariKevorkyan** [sisoputnfrba/foro#1814]
Buenas!
Teníamos dos dudas:
1) Cuando se suman los cambios de contexto, se debe tener en cuenta cuando se pone un entrenador en Ready en SJFCD, o solo cuando cambiamos de entrenador en EXEC.
2) Cuando nos llega un Appeared que nos interesa, se planifica un entrenador, que manda el Catch pokemon. Pero puede pasar que mientras esta a la espera del Caught (para ver si lo atrapo o no), nos llegue otro Appeared para la misma especie. ¿Que se tiene que hacer con ese Appeared? Considerando que si la respuesta al primer caught es negativa, lo vamos a necesitar usar, pero si es positiva no.
Actualmente nosotros estamos rechazando ese Appeared porque el mismo pokemon tiene un Catch pendiente de respuesta. Sin embargo, si la respuesta al Catch es negativa, estamos aceptando todos los Appeared que lleguen a partir de este momento que lleguen para ese pokemon. Es decir, no estamos tomando en consideración los Appeared que llegaron mientras estabamos a la espera de la respuesta. ¿Eso seria correcto?

**Comment by iago64** [comment]
Buenas!

1.- Sobre el tema de cambios de contexto, justo se charlo en el issue #1809, solo te importa cuando lo que esta en EXEC cambia, los demás pasajes no cuentan :)

2.- Lo ideal sería que se guarden la info del appeared en el "mapa", cosa de que si el catch falla pueden planificar a ir a buscar al pokemon a la nueva ubicación que les llego.

Saludos.-

**Comment by MariKevorkyan** [comment]
Disculpa! Lo habia leido el otro dia y me olvide de responder. Super claro!
Gracias, saludos
