### ISSUE TITLE
Duda Metricas

### ISSUE THREAD

**Issue by francorojo** [sisoputnfrba/foro#1815]
Hola buenas tardes, nos surgio una duda con el ultimo item de este issue #1784 :

- Deadlocks producidos y resueltos (Spoiler Alert).

Los deadlocks producidos y los resueltos, no son lo mismo? Puede diferir la cantidad? Por que el Spoiler Alert, nos da miedo xd.
El team adquiere los pokemones que necesita por los entrenadores que lo componen, por lo tanto los pokemones del team son los que necesita como objetivo global y estos son la suma de los que necesitan los entrenadores. Hay un caso donde no se pueda resolver el deadlock?
Gracias, saludos!

**Comment by iago64** [comment]
Buenas buenas!

La jodita esta en que uds pueden por ejemplo encontrar 1 solo deadlock entre 5 entrenadores, como por ejemplo la prueba de espera circular.
Peeero pueden ir resolviéndolos de a 1 trade a la vez, entonces, uds detectaron 1 deadlock, pero lo resolvieron en 4 trades 😉 

Saludos.-

**Comment by francorojo** [comment]
Aaaaa buenismo, graciaas!

**Comment by iago64** [comment]
Nada que agradecer, si te queda alguna otra duda avisa nomas, si no cerra el issue 😉

**Comment by francorojo** [comment]
Uh sisi, perdon, gracias!

**Comment by nahuelPascual** [comment]
> Peeero pueden ir resolviéndolos de a 1 trade a la vez, entonces, uds detectaron 1 deadlock, pero lo resolvieron en 4 trades 😉

Entonces, para confirmar @iago64, ¿son dos contadores distintos? ¿en este caso deberían quedar `deadlocks = 1` y `resoluciones = 4`?

**Comment by iago64** [comment]
@nahuelPascual Nope, es 1 deadlock, 1 resolución, pero que les ocupo 4 trades :)

**Comment by nahuelPascual** [comment]
O sea que el contador que tengo hoy (trades) no me sirve de nada jajajaja bárbaro, gracias por la aclaración! 😄
