### ISSUE TITLE
Problema al escribir archivos

### ISSUE THREAD

**Issue by GuLusin** [sisoputnfrba/foro#1816]
Hola! estoy haciendo la parte del gamecard que ahora se está encargando de escribir en los archivos block y estoy teniendo un problema en el cual el proceso segmentea al hacer cualquier operación de escritura, sea fwritef, fputs, fwrite. el archivo lo abro en modo "w" y si no se encuentra disponible se crea correctamente pero falla al escribirlo.
Lo extraño es que al correr el programa con valgrind funciona correctamente y realiza todas las escrituras que intento hacer.
Probé asignándole al archivo todos los permisos por si era un tema relacionado a eso pero tampoco funciona.
Alguno tiene una idea de que puedo hacer?
Gracias, saludos!

**Comment by mgarciaisaia** [comment]
¿Qué valores te retornan las funciones `fwrite` y similares cuando no escribe los bytes?

Probá llamar a la función [`perror`](https://man7.org/linux/man-pages/man3/perror.3.html) después de ejecutar `fwrite`, también, a ver qué está ocurriendo.

También puede servir ver un cachito de código con las llamadas y de dónde salen los parámetros que le estás pasando.

**Comment by GuLusin** [comment]
El tema es que rompe en el propio fwrite y no puedo hacer nada despues,
Para descartar que los problemas sean de codigo reemplaze las escrituras que queria hacer por otras mas simples y con todas las variables ahi para testear de la siguiente manera:

```
FILE* file_stream = fopen("../mnt/TALL_GRASS/Blocks/14.bin","w");
int unEntero = 5;
printf("Se esta por realizar la escritura...\n");
int retorno_fwrite = fwrite(&unEntero,sizeof(int),1,file_stream);
printf("fwrite retorna %d\n",retorno_fwrite);
fclose(file_stream);
```
Ese mismo codigo si lo corro directamente no llega a printear el valor de retorno de fwrite sino que segmentea antes.

Sin embargo, si yo ese codigo lo corro con valgrind funciona perfecto y fwrite en ese caso retorna 1.

Otro detalle que note que no me sirvio para debuggearlo pero lo comento igual, por las dudas, es que si voy a las propiedades del archivo creado cuando es sin valgrind, mi VM dice que es un "documento de texto sencillo". Mientras que, si el documento fue creado usando valgrind mi VM dice que es de tipo "desconocido". No creo que eso sirva de nada pero me llama la atencion tambien.

**Comment by GuLusin** [comment]
Lo que acabo de notar es que si ese mismo fragmento lo meto en el main, y todos los demás llamados a funciones los comento, el proceso se ejecuta bien. Antes estaba mentiendo ese fragmento dentro de otra funcion que se encargaba en parte de la escritura. Voy a estar revisando si está por ahi el problema. Pero no se bien que fijarme porque, según entiendo, las otras cosas que hacia en la funcion no deberian afectar la escritura que intento hacer. Ademas sigue estando el tema de que con valgrind no ocurre el problema.

**Comment by iago64** [comment]
Buenas!

Revisaste lo que dijo Mati? que puede hacer que un fwrite no escriba en el archivo? Capaz pegarle una leída a la parte de return values del [man de fwrite](https://linux.die.net/man/3/fwrite) te de una idea.

Saludos.-

**Comment by GuLusin** [comment]
Hola! el tema es que no me llega a retornar nada porque segmentea directamente, por el momento no pude solucionarlo y lo sigo desarrollando, ejecutandolo con valgrind. Espero hasta el sabado asi veo si por discord me pueden dar una mano.
Cierro el issue o lo dejo?

**Comment by iago64** [comment]
Antes de is al sabado de soporte, y perder 4 días, cual es el error que te esta tirando? Podes subir un screen del error? porque no es lo mismo un segfault que un ENOENT por ejemplo

**Comment by pacoDan** [comment]
intenta con fputc() , luego el entero que te de , llamémosle X, fijate en
stdio.h ese X , te avisara el tipo de error

**Comment by GuLusin** [comment]
Si, como dije antes, el proceso tira "Segmentation fault (core dumped)" al momento de ejecutar la instrucción fwrite, (o cualquier otro tipo de escritura). 
Intenté fijarme que valor me retorna la función (también me fijé con fputc()) pero como segmentea antes no puedo verlo.
Intenté tambien con perror pero el resultado es el mismo, no puedo ver el error porque el programa segmentea.
Intenté fijarme con valgrind a ver que errores detecta, pero al ejecutarlo con valgrind el archivo se escribe sin ningun problema y fwrite devuelve correctamente la cantidad de bytes escritos.

**Comment by iago64** [comment]
Genial, si te tira un segment fault, podrias subir las capturas de lo que dice valgrind? capaz que eso nos da una idea de cual es el origen del error :)

**Comment by GuLusin** [comment]
Hola, ya salio andando :o
No entiendo muy bien cual era la causa del error porque hasta el momento no tengo más de un hilo trabajando en el gamecard a la vez, pero puse un mutex desde que abre el bloque con el fopen hasta que lo cierra y se solucionó, ademas super raro que ese problema no me aparezca cuando ejecuto con valgrind. Me voy a basar en el mutex ese para fijarme si encuentro bien la causa así no queda medio atado con alambre. Muchas gracias :D

**Comment by iago64** [comment]
Momeeento, un mutex te soluciono el problema?? ahi es cuando te recomiendo que revises con helgrind, capaz que el origen de todo fue una hermosisima condición de carrera :)

**Comment by karengrams** [comment]
¡Buenas buenas!

¿Como va? ¿Alguna noticia de la condición de carrera? ¿Le encontraron sentido al mutex mágico?

¡Saludos!

**Comment by GuLusin** [comment]
Holaa!
La verdad que pausamos un poco con el TP por las semanas de parciales así que quedó ahí :$
Igual ya anda bien, seguro nos arreglamos para determinar bien la razón de la condición de carrera cuando tengamos tiempo.
Quieren que cierre el issue y si no lo conseguimos determinar lo vuelvo a abrir?

**Comment by karengrams** [comment]
¡Holi!

Dale, no se cuelguen con eso, capaz esa condición de carrera la esten tapando con una ~~curita~~ mutex y puede que más adelante sea algo mucho más jodido 😕 .
Recuerden que estamos por aca cualquier cosa que necesiten y en los sábados de soporte.

¡Saludos!
