### ISSUE TITLE
[Gamecard] Semáforo para acceder a diccionario global

### ISSUE THREAD

**Issue by MatiCoarasa** [sisoputnfrba/foro#1818]
Buenas!

Después de leer el issue #1771 se me ocurrió utilizar diccionarios de semáforos donde la key sería el nombre del pokemon. Noté que para implementar esto, tendría que crear un diccionario global y que para leer y agregar nuevos semáforos a éste tengo que utilizar un semáforo (por ser variable global). Me llevó a plantear dos dudas:

1. Al bloquear la lectura de ese diccionario global con semáforos, no pierde velocidad la aplicación? Estaría bloqueando cualquier hilo que quiera acceder al semáforo de un metadata.
2. Es realmente necesario utilizar un semáforo para este acceso?

Gracias!

**Comment by iago64** [comment]
Buenas buenas!
Muy buena idea de solución para los semáforos, ahora respecto a tus consultas:
1.- Si lo ves a velocidad maquina si, si, un semáforo agrega un montón de tiempo, ahora, a nivel humano, ni por asomo va a ralentizar la aplicación. Ademas es preferible perder un par de milisegundos en la entrega por un semáforo que 1 cuatrimestre haciendo otro tp no?
2.- Por buenas practicas cualquier variable global la tenes que sincronizar, con lo cual, tratemos de apegarnos a las buenas practicas :wink:

Espero que las respuestas se entiendan, cualquier cosa no dudes en avisar 😄 
Abrazo a la distancia!

**Comment by MatiCoarasa** [comment]
Quedó claro, muchas gracias!
