### ISSUE TITLE
[GameCard] Dudas eliminación de bloques

### ISSUE THREAD

**Issue by MarianoPessina** [sisoputnfrba/foro#1819]
Hola buenas, tengo un par de dudas con respecto al estado inicial del filesystem.
1- Podrían dármelo iniciado con, por ejemplo, varios bloques de un mismo pokemon con una sola linea cada uno? tendría que poder liberar más de un bloque con un solo pedido? Este estado sería uno al que no podría llegar ejecutando mi programa, sólo si cuando inicio el filesystem ya se encuentra en este estado.
ej: pikachu tiene los bloques [1,2,3] y estos tienen una linea cada uno, me llega un new, y al volver a escribir los bloques entra todo en el 1, debería liberar los bloques 2 y 3?.
2- Si un pokemon tiene está en un solo lugar y hay 1 de si mismo ahí, ej: squirtle 2-5=1 y me hacen un catch, tengo que borrar la metadata de Squirtle de mi file system o debo dejarla con los bloques así [] ?
Desde ya, muchas gracias :)

**Comment by ncoen97** [comment]
Buenas.
1- En el caso de que un Tall Grass se encuentre en el estado que comentas, sería un estado inconsistente (excepto que justo, por el tamaño de bloque, en cada uno entre solo 1 linea de cada posición). No vamos a darles estados inconsistentes para que ejecuten las pruebas, así que es un caso que no deben contemplar.
2- En este caso pueden dejar el archivo Squirtle con 0 bytes (sin bloques asignados).
Saludos!

**Comment by karengrams** [comment]
¡Buenas!

¿Todo bien? Espero que bien. ¿Quedo resuelta la duda?

Saludos 😸

**Comment by karengrams** [comment]
@MarianoPessina ¿como va? Cierro el issue por inactividad, pero cualquier cosa, no dudes en volver abrirlo. Saludos :)

**Comment by MarianoPessina** [comment]
Perdón ví el mensaje ayer antes del parcial y me olvidé de cerrar el issue
después, disculpas
