### ISSUE TITLE
[TEAM, MENSAJES] id correlativo Catch

### ISSUE THREAD

**Issue by matiasanz** [sisoputnfrba/foro#1820]
Buenas!
Quería consultar si el mensaje catch debe ser correlativo al appeared/localized que me trajo al pokemon. El motivo por el cual yo querría que esto sea asi es que le llegue solamente al gamecard que me lo mandó y evitar a futuro tener varios caught ok/fail de todos los demas, teniendo en cuenta el efecto que produciría en ellos.
Gracias y saludos!

Edit: Lo estuve pensando y me di cuenta que de ser así, los entrenadores que hagan catch de un pokemon que envía el gameboy quedarían en el limbo.

**Comment by iago64** [comment]
Buenas!
Perdón por la demora, fue una semana complicada 😢 

El CATCH no tiene necesidad de tener Id Correlativo, ya que es el mensaje que inicia la transacción en si, el que es correlativo del CATCH es el CAUGHT.

Puede ser que le tires CATCH a un pokemon inexistente en el GameCard ? Por su puesto que si, pero en ese caso el GameCard te va a contestar con un FAIL en el CAUGHT y listo el problema :)

Saludos.-

**Comment by matiasanz** [comment]
Hola, gracias por responder!
Entiendo. Yo pensaba, por ejemplo, qué pasaría si tuviera 5 Pikachu en una misma posicion y trabajara con 5 gamecards. Con que un solo team diga Catch Pikachu, ya se estarían consumiendo todos siendo que se generarían 5 mensajes Caught OK por esa sola transacción. Se esperaría que esto fuera asi?

**Comment by iago64** [comment]
Buenas!

Me parece que ahí te estas confundiendo, si tenes 5 Pickachus en una misma posición, cada GameCard va a tener una copia de esos 5 Pickachus, la idea es que como los mensajes les llegan a todos los GameCard, todas tienen la misma información y por lo tanto, cuando envies el catch, le va a llegar a los 5, los 5 te van a contestar ok y todos van a terminar con 4. 

Lo que **no tiene que pasar** es que si tenes 1 pikachu en una posición y tenes 5 GameCard, asumas que tenes 5 Pikachus en esa posición.

Saludos.-

**Comment by matiasanz** [comment]
Ah listo, muchísimas gracias!
