### ISSUE TITLE
[Gamecard] Consulta acerca del punto de montaje 

### ISSUE THREAD

**Issue by JuanFerro** [sisoputnfrba/foro#1821]
Buenas!
Quería consultar por un tema con la ruta del punto de montaje del Gamecard:
Tenemos un punto de montaje donde van a estar el directorio Metadata (con el bitmap y el metadata general), un directorio Blocks con los bloques y un directorio más, ejemplo "TALL_GRASS" que contenga los files con sus files Metadata.
Eso es lo que yo entendí. Estoy en lo correcto?

Para ser mas especifico...
![image](https://user-images.githubusercontent.com/62355595/86544428-1b2a9400-befd-11ea-8313-b6555ef48ab8.png)

Gracias!! Saludos

**Comment by iago64** [comment]
Buenas!

No vas a tener el directorio TALL_GRASS, eso nos quedo a modo de ejemplo en el enunciado, vos deberías tener:
[Punto_Montaje]/Files/[Pokemon]/metadata.bin

Los de Blocks y Metadata estan perfecto 😄 

Saludos.-

**Comment by JuanFerro** [comment]
Gracias!!
