### ISSUE TITLE
[Broker] Fragmentación Interna - Post Compactación

### ISSUE THREAD

**Issue by SwaXTech** [sisoputnfrba/foro#1822]
Hola!.  ¿Cómo están?

Estamos puliendo la funcionalidad de la administración de memoria de nuestro broker y ahora nos surgió una duda.

He visto por el foro más de una vez que se dice "Nos tomamos licencias de la teoría [...]" en cuanto a que en teoría las particiones dinámicas no tienen fragmentación interna, pero en nuestro tp se asigna un tamaño mínimo de partición con lo cual es inevitable para todo mensaje que sea menor al tamaño mínimo de partición.

De la misma manera me pregunto. Ya que en teoría la compactación se usa efectivamente para eliminar el problema de la fragmentación externa. Al compactar en nuestro tp, ¿se elimina también la fragmentación interna?.

¿Cuál de los casos es el esperado?

![Compact2](https://user-images.githubusercontent.com/43499966/86544760-08658e80-bf00-11ea-90f2-d794ca297d76.png)

**Comment by MatiMon** [comment]
Debería quedarte como en el caso 2.
La fragmentación interna es la memoria que te sobra dentro del bloque que asignaste, para poder utilizar eso tendrías que mover a otro bloque de memoria o particionar y que te quede ese pequeñito bloque sólo.
Compactar sólo soluciona la fragmentación externa.

**Comment by iago64** [comment]
Buenas!

Efectivamente es como dice @MatiMon 
La fragmentacion interna esta y va a seguir estando for ever, la externa es la que atacas con la compactación.

Saludos.-

**Comment by SwaXTech** [comment]
Entendido. Muchas gracias!
