### ISSUE TITLE
[Broker] Prueba Algoritmos Partición Dinámica Libre FF y BF

### ISSUE THREAD

**Issue by papa-caco** [sisoputnfrba/foro#1824]
Hola, cómo andan?

Queríamos validar con Uds. si estaría correcto cómo entendimos que debe funcionar el Broker ante las distintas configuraciones del algoritmo para encontrar una partición dinámica libre: **First_Fit** y **Best_Fit**.
Para poder generar un hueco entre las particiones dinámicas del Cache consideramos que hay que combinar con el Algoritmo de reemplazo **LRU** y **No** se tiene que realizar **compactación**.

La configuración apropiada para las pruebas sería la siguiente:

TAMANO_MEMORIA=**64**
TAMANO_MINIMO_PARTICION=**4**
ALGORITMO_MEMORIA=**PARTICIONES**
ALGORITMO_REEMPLAZO=**LRU**
ALGORITMO_PARTICION_LIBRE=**AMBOS**
FRECUENCIA_COMPACTACION=**-1** 

Y este sería el Script propuesto:

 ./gameboy BROKER CATCH_POKEMON Charmander 23 87 **# 22 Bytes**
 ./gameboy BROKER CATCH_POKEMON Bulbasaur 14 62 # **21 Bytes**
 ./gameboy BROKER APPEARED_POKEMON Bulbasaur 14 62 3  **# 21 Bytes**
 ./gameboy BROKER GET_POKEMON Venusaur  **# 12 Bytes**
 ./gameboy SUSCRIPTOR CATCH_POKEMON 1
 ./gameboy BROKER GET_POKEMON Charizard  **# 13 Bytes**
 ./gameboy BROKER GET_POKEMON Onix **# 8 Bytes**

Estos son los resultados que obtuvimos:
![image](https://user-images.githubusercontent.com/35772622/86856058-ee5bb580-c091-11ea-9330-c4288d20ada4.png)
¿Podrán confirmarnos si está bien así?  Muchas gracias!

Saludos,

**Comment by iago64** [comment]
Buenas!

Los resultados estan perfectos.
No te olvides que Best Fit trata de minimizar al maximo la Fragmentación Externa, mientras que First Fit solo lo tira en el primer hueco donde entre.

Saludos.-

**Comment by papa-caco** [comment]
Buenísimo Damián! Muchas gracias. Saludos,
