### ISSUE TITLE
[BROKER] duda sobre resultado prueba Buddy system

### ISSUE THREAD

**Issue by CamiMargni** [sisoputnfrba/foro#1825]
Hola! teníamos una duda mientras ejecutabamos el script buddy_basico.sh
Enlazo lo de dentro:
./gameboy BROKER CAUGHT_POKEMON 1 OK
./gameboy BROKER CAUGHT_POKEMON 1 FAIL
./gameboy BROKER NEW_POKEMON Pikachu 2 3 1
./gameboy BROKER CATCH_POKEMON Onyx 4 5
./gameboy SUSCRIPTOR NEW_POKEMON 10
./gameboy BROKER CATCH_POKEMON Charmander 4 5

---------
Siguiendo la lógica de tamaños de cada mensaje por orden, ambos caught tienen tamaño 4, el new tiene tamaño 24 y el catch tamaño 17. (acá estaría el problema).
Enlazo imagen con como quedarían almacenados los primeros 3 mensajes.
![Captura](https://user-images.githubusercontent.com/48899516/86872655-34754100-c0b3-11ea-8af6-f6b6dd473ee3.PNG)

Al llegar el mensaje catch, el cuarto, el árbol va a empezar a eliminar particiones, el primer caught, luego el segundo, luego a consolidar al padre de tamaño 8, luego consolidar al padre de tamaño 16 y ese al de tamaño 32 y recién ahí va a asignar el cuarto catch. En los resultados del test dice que al llegar este cuarto catch se asigna en la posición 16, correspondiente a este lugar que marco en la foto:
![image](https://user-images.githubusercontent.com/48899516/86872860-88802580-c0b3-11ea-9723-71f707aae07d.png)
pero no sería posible ya que su tamaño no es 16 (3 ints + tamaño de onyx + /0 = 17). 
No sé si en el desarrollo nuestro grupo tuvo un error o se contempló mal en los resultados del test.
Saludos

**Comment by jmuhsisoglu** [comment]
Buenas! No soy ayudante, aclaro por las dudas, pero quería comentar que el NEW Pikachu es de tamaño 23 y el CATCH Onyx es de 16. Seguramente por eso no te anden las pruebas.
Nosotros al principio guardábamos en memoria el centinela (el \0) al final del nombre del pokemon pero no hay que guardarlo (está en el anexo 2 del enunciado), quizás por esto te da 1 byte más el tamaño de cada mensaje.

**Comment by CamiMargni** [comment]
Sabés que sí! guaardamos el /0. Gracias por el aporte!

**Comment by iago64** [comment]
Buenas!

Como comenta @jmuhsisoglu el '\0' no tiene que estar.

Abrazo.-
