### ISSUE TITLE
[GAMECARD] duda condiciones iniciales para pruebas.

### ISSUE THREAD

**Issue by JuanFerro** [sisoputnfrba/foro#1826]
Buenas, tengo una duda con el tema de las pruebas del gamecard. 
Cuales serian las posibles condiciones iniciales que nos podrían llegar a plantear?. Es decir, se podría dar la posibilidad de que ustedes nos proporcionen ya un archivo de un pokemon X, y si se da el caso, nos darían ademas los bloques ya ocupados con las posiciones y cantidades que le quisieran asignar?. 

Saludos!

**Comment by iago64** [comment]
Buenas!

Si para una prueba les damos un FS inicializado, van a tener los archivos metadata de los pokemones y ademas los bloques tanto libres como ocupados correspondientes.

De todas formas, no te olvides que puede ser que uds mismos bajen su GameCard y lo vuelvan a levantar y tengan que mantener los mismos archivos que tenían previamente :)

Saludos.-

**Comment by JuanFerro** [comment]
Perdon por el delay. Muchas gracias! Cierro issue.
