### ISSUE TITLE
[TEAM] - Consulta Deadlock

### ISSUE THREAD

**Issue by Gonzalo-Avila** [sisoputnfrba/foro#1827]
Buenas! Tenemos algunas dudas sobre lo que se pide para resolver el deadlock.

En el enunciado dice lo siguiente:

> Cuando se detecte situaciones de Deadlock deberán estar ambos en estado bloqueado. En este momento, uno de ellos se pasa a estado Ready con el objetivo que se lo planifique hasta la posición del otro. Al llegar a la misma posición, se deberá realizar el intercambio. Cada intercambio ocupara 5 ciclos de CPU. Cada intercambio solo involucra a dos Pokémon.
Al finalizar el intercambio se verificará si alguno está en condiciones de ir a Exit y de no ser así  irán nuevamente a estado bloqueado. A su vez, cada acción de movimiento o envío de mensaje al Broker consumirá un ciclo de CPU.

Pero más abajo dice esto otro sobre los casos donde hay Deadlock: 

>Cuando se detecte dichos casos, se deberá bloquear uno de los entrenadores y planificar al/los otro/s a la posición del primero para generar un “intercambio” (cada intercambio implica que cada entrenador entregue un Pokémon al otro uno de ellos).

Lo que entendemos nosotros es que al haber una situación de deadlock todos los entrenadores que participen del mismo van a estar bloqueados: entonces, para solucionar el problema, se va a mover alguno de ellos (cualquiera sea) hacia la posición de otro  que tenga un Pokemon que necesite, y se va a realizar un intercambio, repitiendo esta operación hasta que todos estén en FIN.  ¿Esto está bien? ¿O entendimos mal algo?

Gracias, saludos!

**Comment by iago64** [comment]
Buenas buenas!

En el enunciado medio que pecamos de redundantes, pero para que tengas deadlock van a estar bloqueados porque es por definición 😄 
La idea es que como bien dijiste, desbloquees a uno y lo planifiques hasta la posición del otro y ah hagan el intercambio.

Saludos.-

**Comment by Gonzalo-Avila** [comment]
Joya! 😃 

Perfecto entonces, muchas gracias.
