### ISSUE TITLE
[Broker] IDs Correlativos Repetidos

### ISSUE THREAD

**Issue by dariokozicki** [sisoputnfrba/foro#1828]
Buenas!

Ando en las últimas etapas de broker con los tests andando.
En las charlas y con ayudantes me quedó que si a Broker le llegan dos mensajes que tienen el mismo id correlativo, sólo el primero debería tenerse en cuenta, y el segundo debería ignorarse.

Estaba agregando esta funcionalidad y vi que en los tests hay lineas como:

> ./gameboy BROKER CAUGHT_POKEMON 1 OK
> ./gameboy BROKER CAUGHT_POKEMON 1 FAIL

Si le termino de agregar esto, no me romperían los tests? Porque el segundo caught sería ignorado y daría resultados distintos en las posiciones.

Gracias y saludos!

**Comment by papa-caco** [comment]
Hola Darío,  cómo estás?
Los mensajes que CAUGHT_POKEMON que mencionaste son ejemplos para las pruebas de consolidación y compactación del cache del BROKER, fijate que los estás enviando desde el GAMEBOY.
Pero los mensajes CAUGHT_POKEMON **de verdad** los envía el GAMECARD en respuesta a los mensajes CATCH_POKEMON que el GAMECARD recibe del BROKER.  Y como cada mensaje que envía el BROKER a sus suscriptores tienen un ID_Mensaje único y diferente (en este caso GAMECARD es suscriptor de los mensajes CATCH_POKEMON) , el mensaje CAUGHT_POKEMON que devuelve GAMECARD al BROKER debería tener un ID_Correlativo correspondiente al CATCH_POKEMON que recibió. Por consiguiente GAMECARD no debería enviar dos mensajes CAUGHT_POKEMON con el mismo ID_Correlativo. A mi entender no deberían complicarse con esa funcionalidad de filtrar mensajes del mismo tipo con Id_Correlativo repetido porque no debería suceder. Igual esperá ver qué te recomiendan los ayudantes.
Saludos, suerte!

**Comment by dariokozicki** [comment]
Hola Carlos, gracias por la pronta respuesta!
El tema es que según el TP hay N gamecards, no sólo uno. Entonces pueden haber múltiples Gamecards suscritos a Caught que reciban el mensaje, y todos van a responder al mismo con el id correlativo.

**Comment by papa-caco** [comment]
Hola Darío, gracias a vos por la pregunta!  Porque es correcto lo que decís. No contemplamos el caso de múltiples GameCards.
Y en ese caso sí, podría pasar que los GameCards envíen diferentes respuestas para un mismo ID Correlativo. Y entiendo que pasaría lo mismo con los otros dos tipos de mensaje que GameCard responde: APPEARED y LOCALIZED. Vamos a ver qué nos responden. 
Saludos!

**Comment by RaniAgus** [comment]
Hola Darío, tengo entendido que eso estaría hecho para poder testear que el BROKER acepte el primer mensaje y luego rechace el segundo. Igual el test es medio raro porque no envía un mensaje CATCH_POKEMON en la primera línea como para que tenga ID=1 y así, después, sea respondido con un CAUGHT_POKEMON con ID_CORRELATIVO=1. No sé si me explico bien.

De todas formas, en la implementación REAL tengo entendido que todos los GAMECARD deben estar sincronizados, es decir, todos deben devolver la misma respuesta. Por eso el BROKER solo toma la primera, porque son respuestas repetidas. Quizás, en el test, esté hecho "mal" a propósito para probar (de nuevo) que el BROKER acepta solo la primera respuesta y no la segunda. Pero bueno, veamos qué dicen los ayudantes.

**Comment by dariokozicki** [comment]
Hola Agustín, cómo estás?

No es así. Cito de la prueba de buddy system: (Pag 10)

> Se debe cargar los mensajes en las siguientes posiciones de memoria:
Caught 0
Caught 4
[...]

Saludos!

**Comment by Nico-0** [comment]
Nosotros tampoco hicimos la funcionalidad de rechazar mensajes.
Quizás es que se tiene que guardar igual en la memoria pero no enviarlo? ya seria demasiada complicación

**Comment by RaniAgus** [comment]
> Se debe cargar los mensajes en las siguientes posiciones de memoria:
> Caught 0
> Caught 4
> [...]

Ahhh, tenés razón @dariokozicki ! No me había puesto a mirar el documento de pruebas más en detalle. Cito esto:

> Esta prueba tiene como objetivo verificar el funcionamiento de la compactación de particiones dinámicas del proceso broker independiente de los demás.

Ya sé que cuando habla de "los demás" se refiere a "los demás procesos" (team y gamecard). Pero bueno, entiendo que este test no se encarga de verificar que funcione lo de los ID, sino que se enfoca nada más en que se carguen los mensajes en memoria y se realice la compactación cuando corresponda. Por eso, lo que yo voy a hacer es deshabilitar la funcionalidad de rechazar mensajes por ID correlativo **solamente para que funcione ese test**.

Igual capaz estoy inventando, por las dudas preferiría que un ayudante confirme si esto que estoy haciendo está bien o no. De estar en lo cierto, estaría bueno que se aclare en el documento para no dar lugar a confusiones.

**Comment by iago64** [comment]
Aloha!

TL/DR: Viendo que el tema se esta tornando algo trambolico, vamos a ir por la salida rápida y cambiar el ID correlativo del mensaje.

Explicación larga: La idea es que el broker no rechaza los mensajes, simplemente los recibe y los guarda y después se fija de enviarlos, pero visto y considerando que el enunciado puede prestar un poco a confusión y el objetivo de la prueba es ver como manejan la memoria, no vamos a entrar en una pelea eterna de como debe funcionar un administrador de colas de mensajes porque mismo ni los productos comerciales se ponen de acuerdo en como es "la mejor manera" entonces, vamos a ser prácticos y vamos a acomodar para que la prueba sea especifica de lo que queremos evaluar y no una discusión filosófica (que esas las dejamos para que el coloquio 😉 )

Saludos.-

**Comment by dariokozicki** [comment]
Gracias por la respuesta! Nos quedamos tranquilos entonces 👍

**Comment by RaniAgus** [comment]
> La idea es que el broker no rechaza los mensajes, simplemente los recibe y los guarda y después se fija de enviarlos

¿Entonces debo cambiar eso?

> El administrador de colas de mensajes debe mantener una lógica de conocer qué mensajes con correlativos ya fueron informados en una cola para no generar redundancia en la misma. Esto quiere decir que si hay varios suscriptores en la cola de mensajes inicial puede haber varias respuestas al mismo (las cuales deberían ser la misma respuesta) por lo que es el administrador de cola de mensajes el que sabe que ese mensaje ya fue agregado a la cola destino y debe ignorarlo.

En la consigna, por "ignorar" interpreté que se ignora lo que se recibe, no que se guarda y luego se ignora a la hora de enviarlo. Además, ¿qué sentido tiene guardar un mensaje en memoria que nunca voy a usar?

Pregunto porque, más allá de si "es la mejor manera" o no, a la hora de evaluar los tests me van a dar todos mal si dejo la implementación que tengo como está.

**Comment by Zheoden** [comment]
Buenas!

A lo que se refiere el broker es que tenes que ignorarlos una ves que ya los informaste, no cuando los recibiste. De todas formas, como dijo @iago64, no es algo que nos cambie mucho a la hora de evaluar si estan ignorando los mensajes cuando los reciben o cuando los envian. Si ustedes ignoran los mensajes (ya sea cuando los envian o cuando los reciben) todos los tests les van a dar bien, es mas un tema para charlar en el coloquio.

PD: Ya quedaron cambiados los IDs de los scripts!
