### ISSUE TITLE
Duda localized

### ISSUE THREAD

**Issue by MarcosInfantino** [sisoputnfrba/foro#1829]
Hola! Terminando de programar todos los módulos nos sugrió la siguiente duda:
Según lo que se entiende el enunciado, cuando al gamecard le llega un get, el mismo debe mandar un localized con cada una de las posiciones de la especie del pokemon y la cantidad de esos pokemones que estan allí. Esto tiene sentido, ya que cuando este localized le llega al team el team tratará cada pokemon que esta en la misma posicion como un appeared diferente.
Por otro lado, en el anexo 2 para el manejo de la memoria caché del broker, se nos pide que guardemos de los localized solo las posiciones y la cantidad de posiciones. Esto difiere con lo otro y hace mucho ruido, ya que a la hora que se suscriba alguien nuevo a la cola localized y le queramos mandar todos los mensajes nuevos que tenemos en caché no podremos enviarselos porque nos faltaría información: la cantidad de pokemones que hay en cada una de las posiciones.
De tal manera, la solución tiene que se común a ambos, entonces, en el localized yo solo mando el nombre del pokemon, la cantidad de posiciones y las posiciones en si? O debo enviar tambien la cantidad de pokemones que hay en cada posicion?
Gracias y saludos!

**Comment by ncoen97** [comment]
Buenas.
En el Localized no se envía la cantidad de Pokemons que hay en cada posición. Por ahí en la parte del enunciado del Gamecard haya un tema de redacción que haga que quede confuso, pero el ejemplo del anexo 2 es correcto y es así como funciona el Localized para todos los módulos.
Saludos!

**Comment by MarcosInfantino** [comment]
Gracias!
