### ISSUE TITLE
[TEAM] - Scripts de pruebas envian NEW_POKEMON (posible error)

### ISSUE THREAD

**Issue by nahuelPascual** [sisoputnfrba/foro#1830]
Buenas, hay algunos test que envian mensajes `NEW_POKEMON` al TEAM, lo cual no me parecía correcto.
Lo planteé hoy en el Sábado de Soporte y, en principio, los ayudantes estuvieron de acuerdo conmigo en que se trataría de un error. Me pidieron abrir este issue. 
Saludos!

**Comment by ncoen97** [comment]
Buenas, ya fue fixeado.
Gracias por los comentarios!
