### ISSUE TITLE
[BROKER] Error en pruebas

### ISSUE THREAD

**Issue by foviedo** [sisoputnfrba/foro#1831]
Buenas! Noté un detalle en el doc de pruebas, en la prueba base broker, en la sección que pide tamanio minimo de particion=4, dice lo siguiente
Tamaño mínimo de partición 4: Posiciones 0, 11, 25, 44, 64, 68, 72, 93, 115, 124 
Esto no se puede cumplir, pues, por ejemplo, el primer mensaje ./gameboy BROKER CATCH_POKEMON Pikachu 9 3 #19b
Ocupa 19 bytes, 7 del nombre, 4 del tamanioNombre y 8 de las coordenadas, esto fue corregido en el de tamanio minimo 16
Gracias y saludos!
Facundo
pd: haciendo una búsqueda rápida en los issues cerrados, no vi si ya comentaron esto. Mil disculpas si así fue

**Comment by iago64** [comment]
Aloha!

Las pruebas finales ya están publicadas, son las que valen de ahora en adelante: https://www.utnso.com.ar/1c2020-pruebas-finales/ 
Las anteriores ya quedaron fuera de soporte 😉 

Saludos.-

**Comment by foviedo** [comment]
Entendido, gracias Dami!
