### ISSUE TITLE
Pruebas: comandos funcionan, pero script falla

### ISSUE THREAD

**Issue by RaniAgus** [sisoputnfrba/foro#1832]
Buenas! 
Estamos teniendo problemas para ejecutar los tests con el gameboy, por ejemplo, el script `cargar_memoria_complejo.sh`:
```
./gameboy BROKER CATCH_POKEMON Pikachu 9 3 #19b
./gameboy BROKER CATCH_POKEMON Squirtle 9 3 #20b

./gameboy BROKER CAUGHT_POKEMON 10 OK
./gameboy BROKER CAUGHT_POKEMON 11 FAIL

./gameboy BROKER CATCH_POKEMON Bulbasaur 1 7 #21
./gameboy BROKER CATCH_POKEMON Charmander 1 7 #22

./gameboy BROKER GET_POKEMON Pichu #9
./gameboy BROKER GET_POKEMON Raichu #10
```
Si yo ejecuto los comandos uno a uno en el gameboy, funciona perfectamente.
![imagen](https://user-images.githubusercontent.com/39303639/87259166-b08ad280-c47f-11ea-8007-77aaf6124289.png)

Pero si corro el script, el gameboy no me parsea algunos comandos (como si el script ejecutara algo distinto).
![imagen](https://user-images.githubusercontent.com/39303639/87259125-50942c00-c47f-11ea-9c12-2d9e19007e32.png)

No estaría entendiendo por qué pasa esto, si en realidad, según tengo entendido, el script lo único que hace es ejecutar una sucesión de comandos, debería hacer lo mismo. Como dato de color, tampoco estaría entendiendo por qué hay líneas en las que aparece `command not found`.

Perdón si hay alguna otra issue que trate sobre este tema, estuve buscando un rato y no encontré nada parecido al respecto.

**Comment by mgarciaisaia** [comment]
¡Buenas!

Fijate que se está quejando de `\r`.

En los sistemas Unix-like (Linux entre ellos), el caracter para el salto de línea ("el Enter") es `\n` ("newline feed", alimentar una línea nueva). Pero las viejas Macs (antes de MacOS X) usaban `\r` ("carriage return", retorno de carro), y Windows usa `\r\n` (retorno de carro, luego línea nueva).

Esto viene de las épocas en que la salida a pantalla estaba mucho más cerca al modo de funcionamiento de una máquina de escribir, en la que saltar de línea implicaba las dos acciones: volver el cursor horizontalmente al inicio de la página, y mover el papel verticalmente para ir a la línea siguiente.

Así que, nada: seguramente copiaste y pegaste el texto de los scripts en un archivo txt en Windows (guardando los saltos de línea como `\r\n`, y cuando los parseás en Linux (que separa por `\n`) te aparecen unos `\r` de más.

Juraría que las VMs incluyen un comando `dos2unix` que te recibe un archivo con saltos de línea de Windows y te los convierte al formato Unix. Con eso deberías poder corregir fácil tus scripts. O podés copiarlos directamente desde Linux, que no te va a meter los `\r` de más.

**Comment by ncoen97** [comment]
A veces nos matamos buscando el problema en los issues y nos olvidamos del viejo y confiable google 😄

**Comment by RaniAgus** [comment]
> ¡Buenas!
> 
> Fijate que se está quejando de `\r`.
> 
> En los sistemas Unix-like (Linux entre ellos), el caracter para el salto de línea ("el Enter") es `\n` ("newline feed", alimentar una línea nueva). Pero las viejas Macs (antes de MacOS X) usaban `\r` ("carriage return", retorno de carro), y Windows usa `\r\n` (retorno de carro, luego línea nueva).
> 
> Esto viene de las épocas en que la salida a pantalla estaba mucho más cerca al modo de funcionamiento de una máquina de escribir, en la que saltar de línea implicaba las dos acciones: volver el cursor horizontalmente al inicio de la página, y mover el papel verticalmente para ir a la línea siguiente.

Interesante!

> Así que, nada: seguramente copiaste y pegaste el texto de los scripts en un archivo txt en Windows (guardando los saltos de línea como `\r\n`, y cuando los parseás en Linux (que separa por `\n`) te aparecen unos `\r` de más.

Nono, lo que hice fue clonarme el repo https://github.com/sisoputnfrba/delibird-pruebas directamente en la VM y ejecutar este comando que encontré en google hace tiempo, porque sino me tiraba `./cargar_memoria_complejo.sh: Permission denied`:
```
chmod +x ./cargar_memoria_complejo.sh 
```
Pero ya he usado este comando antes para otros scripts y nunca tuve problemas con que me aparezcan `\r` (uso Linux), así que no creo que hayan aparecido de ahí. Muy extraño.

> Juraría que las VMs incluyen un comando `dos2unix` que te recibe un archivo con saltos de línea de Windows y te los convierte al formato Unix. Con eso deberías poder corregir fácil tus scripts. O podés copiarlos directamente desde Linux, que no te va a meter los `\r` de más.

Ahí me instalé `dos2unix`, los convertí y me funcionó! Muchas gracias por la rápida respuesta! Ya pueden cerrar el issue

**Comment by foviedo** [comment]
Rani, dato que capaz te sirva, yo uso bash cargar_memoria_complejo.sh y funciona piola, sin tener que usar ese dos2unix

**Comment by mgarciaisaia** [comment]
Gracias por el aviso, che.

Sí, definitivamente eran dos bugs del repo de las pruebas.

Ahí subí la versión corregida. Ahora todos los scripts son ejecutables (es cierto, como dice @foviedo, que podías hacer `bash un_script.sh` y eso funciona, pero ahora también vale ejecutar `./un_script.sh`). Además, ya están bien los saltos de línea de todos los archivos (había [5 archivos](https://github.com/sisoputnfrba/delibird-pruebas/commit/5b618bbd1ca8289d99a6656b963e42af189dd91e) que tenían los saltos mal).

Gracias por el aviso una vez más :)

**Comment by RaniAgus** [comment]
Menos mal! Qué bueno que se hayan podido encontrar los bugs a tiempo :+1: 

Noo, por favor, gracias por corregirlos enseguida!
