### ISSUE TITLE
[BROKER] - Mensaje más grande que la cache

### ISSUE THREAD

**Issue by josebruzzoni** [sisoputnfrba/foro#1833]
Buenas! Teníamos una duda con respecto al broker y al almacenamiento de los mensajes en la cache.

La duda era qué hacer cuando llega un mensaje cuyo tamaño es más grande que el tamaño de memoria cache asignada en el config. Esto pasa cuando el tamaño en la cache del config es relativamente chico. Particularmente nos paso que el gamecard le mando un localized de tamaño 78B y justo lo estábamos probando al broker con una memoria cache de 64 (para chequear que anden bien los reemplazos), y como resultado termino eliminando todo lo de la cache y no pudo guardarlo.

Esto tenemos que contemplarlo o se supone que nunca se va a enviar un mensaje mas grande que la cache? En caso de que sí, estaría bien que ese mensaje se "saltee" el cacheo, para evitar que se eliminen todas los mensajes guardados anteriormente?

Gracias!

**Comment by ncoen97** [comment]
Buenas.
Más allá de si va a pasar o no en las pruebas, lo correcto es que si el mensaje excede el tamaño de la memoria no sea guardado y muestren algún error en el log.
Sobre todo les recomiendo que no dejen errores sin logear porque después llega el dia de la entrega y si por algún error de tipeo (por ejemplo) salta algún error que no esperaban, no van a estar en eclipse como para debugear y ver qué está pasando, sino que van a estar solos con la consola, posiblemente un segmentation fault y ninguna idea de cual fue el error.
Suerte!

**Comment by josebruzzoni** [comment]
Gracias!!
