### ISSUE TITLE
Error en prueba final team

### ISSUE THREAD

**Issue by nahuelPascual** [sisoputnfrba/foro#1834]
Buenas, acabamos de ejecutar la prueba final de team y al llegar a la prueba con Round Robin encontramos un error.

El documento aclara:
> Como C finaliza antes que la primer captura de A, el mismo se dirige a atrapar a Gengar generando así un deadlock triple

El tema es que cuando C captura en (5,2) y queda libre para ser replanificado, Gengar está en la posición (6,6) pero existe un Squirtle en (5,5). Por cercanía, C se replanflica para atrapar al Squirtle y no al Gengar.

Saludos!

**Comment by charlyd96** [comment]
Buenas, me sumo a este issue para decirles también que en mi caso, el Team no quedaba Deadlock para la prueba con FIFO (las otras ni las corrí todavía), y mirando un poquito me di cuenta que es porque cuando se reciben los mensajes y se planifican los entrenadores, el entrenador A y C están a la misma distancia que el Squirtle. Entonces depende cómo haya implementado cada grupo qué entrenador va a buscar al pokemon ya que están empatados en distancia.
Agrego un gráfico para expresar mejor la situación. Entre paréntesis en el nombre de cada pokemon, hay un número que indica el orden en el que van ingresando los pokemones.

![Delibird](https://user-images.githubusercontent.com/62087635/87504002-f8565900-c63b-11ea-80ab-e56a911465c8.png)

**Comment by iago64** [comment]
Buenas!

Me encanta que con las mismas coordenadas tenemos el plano traspuesto:

![image](https://user-images.githubusercontent.com/1622109/87544269-8d794200-c67c-11ea-9d23-b08a1c227f3d.png)

Aun así, tenes razón @charlyd96 la distancia de A y C es la misma a squirtle, vamos a estar viendo la forma de fixear la prueba para generar el menor impacto posible (_spoiler:_ puede que la salida mas rápida sea que entra primero el appeared de Onix y después el de squirtle para forzarles que A sea el primero en planificarse).

Igual lo analizamos bien y les avisamos.

Saludos.-

**Comment by miguel-t** [comment]
Buenas ,
Tambien me pasa lo mismo  que @charlyd96  , luego de varias pruebas , **Team no quedaba Deadlock para la prueba con FIFO**

Saludos

Saludos.

**Comment by nahuelPascual** [comment]
Además ese bug es nuevo. Cuando yo publiqué el issue, el primero squirtle estaba en (5,2) y ahora lo movieron a (7,6)

**Comment by miguel-t** [comment]
Buenas,
Para RR team finalizo, pero no coincide con lo pedido.

1.Despues de atrapar  C  el pokemon onix ,se planifica  y  disctancia a gengar(6,6) y quirtel(5,5) es igual, cual tomamos?en nuestro caso lo enviamos a atrapar gengar .
2.A atrapo un pikachu y un squirtle y paso a exit.
3. B atrapo pikachu

4 Al final tenemos un deadlock  y pariticipan  B y C
5.Se resuelve y finaliza team

**Comment by tmerchan** [comment]
Hola, a nosotros con queda lo mismo que a @miguel-t, A finaliza y quedan en deadlock B y C. El deadlock triple no aparece.

**Comment by iago64** [comment]
Buenas!
Se nos había pasado modificar en el documento la posición inicial de C, la cual debe ser 3|2 en lugar de 2|2.

![image](https://user-images.githubusercontent.com/1622109/87701420-57b48600-c76e-11ea-9fc7-3a6af58ae643.png)

**Comment by miguel-t** [comment]
Buenas!
Con esta nueva confi, para el caso de FIFO ->se detecta un deadlock entre A y C, luego se resuelve y finaliza team. 

Saludos.

**Comment by iago64** [comment]
Buenisimo @miguel-t , ahora la pregunta importante, con RR, se genera el deadlock triple? 

Saludos.-

**Comment by miguel-t** [comment]
Hola @iago64 , con RR si genera el deadlock triple.
Paso la info del log para validar por lo demas:

**===========COLA ACTUAL DE BLOQUEADOS================**
**TCB_ID:1(A)** [POSICION:[2 ,8] |**POKEMON**:[ Pikachu : 1 Onix : 1]      |**OBJECTIVOS** :[ Pikachu : 1 Squirtle : 1]
**TCB_ID:3(C)** [POSICION:[6 ,6] |**POKEMON** :[ Squirtle : 1 Gengar : 1] |**OBJECTIVOS** :[ Squirtle : 1 Onix : 1]
**TCB_ID:2(B)** [POSICION:[5 ,5] |**POKEMON** :[ Pikachu : 1 Squirtle : 1] |**OBJECTIVOS** :[ Pikachu : 1 Gengar : 1]


Despues se corre el algoritmo de deteccion dos veces y finaliza team.

Saludos.

**Comment by miguel-t** [comment]
Buenas!
¿Cual es el valor del alpha para SJF? ¿y que metricas tendria que cambiar si o si  respecto de FIFO?
Tome alpha =0.5 , hay deadlock (A y C) igual que en FIFO y las metricas son iguales!

Saludos.

**Comment by martirolon** [comment]
Hola! a nosotros nos paso lo mismo que a @miguel-t, con alpha = 0.5, las metricas de FIFO y SJF son iguales. En este caso, que alpha deberiamos considerar?
Gracias, saludos.

**Comment by maurodgiraldez** [comment]
Hola, me sumo a la consulta de que hacemos con Alpha, porque entiendo que dependiendo del mismo los resultados pueden ser muy diverso y el mismo debería ser ingresado por config; y no se encuentra en la config que debemos usar. En mi proceso actual, pincha el proceso por no poder levantar todas las configs necesarias para funcionar, debería hacer función default con un alpha default en caso que no esté en la config?
Gracias
Saludos

**Comment by iago64** [comment]
Buenas, 

El alpha es 0.5, no se preocupen por los resultados si se "parecen" a FIFO, capaz que lo pensamos parecido para que sea fácil de corregir.

Saludos.-

**Comment by matiasimartin** [comment]
Buenas, me sumo al issue porque probando FIFO no logro un deadlock entre A y C, pero según como esta planteado en nuestro tp, no debería haber. El proceso termina pero detecta deadlocks entre A - C y también B-C. 
Básicamente porque al aparecer pikachu inicia B y se mueve al pikachu (9;9), lo agarra (por default, sin ir a E/S) , se bloquea y espera junto a los otros procesos otra aparición. El segundo en aparecer es squirtle (7;6) y el mas cercano para atraparlo es B que quedo en (9;9). Ya con esto, necesariamente, B va a quedar en deadlock con otro proceso porque agarro a squirtle que no es de su objetivo. Estoy pasando algo por alto?

**Comment by nahuelPascual** [comment]
> Buenas, me sumo al issue porque probando FIFO no logro un deadlock entre A y C, pero según como esta planteado en nuestro tp, no debería haber. El proceso termina pero detecta deadlocks entre A - C y también B-C.
> Básicamente porque al aparecer pikachu inicia B y se mueve al pikachu (9;9), lo agarra (por default, sin ir a E/S) , se bloquea y espera junto a los otros procesos otra aparición. El segundo en aparecer es squirtle (7;6) y el mas cercano para atraparlo es B que quedo en (9;9). Ya con esto, necesariamente, B va a quedar en deadlock con otro proceso porque agarro a squirtle que no es de su objetivo. Estoy pasando algo por alto?

Tenés que mandar todo el script junto, no esperar a que los capturen!
Entonces llega Pikachu y planificas al B. Atrás llega Squirtle y planificás al C (creo, lo estoy diciendo de memoria). Después cae un Onix me parece y lo toma el A. 
B ejecuta primero y cuando atrapa se replanifica para ir al Gengar....

Pude haberle errado en el orden de llegada de algún pókemon, pero fijate eso

**Comment by franpassa** [comment]
> > Buenas, me sumo al issue porque probando FIFO no logro un deadlock entre A y C, pero según como esta planteado en nuestro tp, no debería haber. El proceso termina pero detecta deadlocks entre A - C y también B-C.
> > Básicamente porque al aparecer pikachu inicia B y se mueve al pikachu (9;9), lo agarra (por default, sin ir a E/S) , se bloquea y espera junto a los otros procesos otra aparición. El segundo en aparecer es squirtle (7;6) y el mas cercano para atraparlo es B que quedo en (9;9). Ya con esto, necesariamente, B va a quedar en deadlock con otro proceso porque agarro a squirtle que no es de su objetivo. Estoy pasando algo por alto?
> 
> Tenés que mandar todo el script junto, no esperar a que los capturen!
> Entonces llega Pikachu y planificas al B. Atrás llega Squirtle y planificás al C (creo, lo estoy diciendo de memoria). Después cae un Onix me parece y lo toma el A.
> B ejecuta primero y cuando atrapa se replanifica para ir al Gengar....
> 
> Pude haberle errado en el orden de llegada de algún pókemon, pero fijate eso

Hola, yo tengo un problema al ejecutar el script. A veces me pasa que llegan 2 appeared seguidos antes de que se planifique el primer entrenador, eso hace que el entrenador B se planifique al squirtle. Ya meti mutex por todos lados, pensando que era un problema de sincronizacion, pero ya no se como solucionarlo, el 70% de las veces el resultado me da, pero en otras al planificarse mal el primero afecta al resto de la planificacion. Esto me pasa en el caso FIFO. Alguno le paso lo mismo o me puede dar una pista de como solucionarlo? No logro tener el 100% de las pruebas bien.

**Comment by nahuelPascual** [comment]
> Hola, yo tengo un problema al ejecutar el script. A veces me pasa que llegan 2 appeared seguidos antes de que se planifique el primer entrenador, eso hace que el entrenador B se planifique al squirtle. Ya meti mutex por todos lados, pensando que era un problema de sincronizacion, pero ya no se como solucionarlo, el 70% de las veces el resultado me da, pero en otras al planificarse mal el primero afecta al resto de la planificacion. Esto me pasa en el caso FIFO. Alguno le paso lo mismo o me puede dar una pista de como solucionarlo? No logro tener el 100% de las pruebas bien.

Buenas, no soy ayudante... pero a ver si puedo ayudarte! 😆 

Me parece raro lo que comentas, porque cuando llega el primer mensaje ahí levantas un hilo para procesarlo y, después de unas mínimas validaciones (ver si necesitas el pokemon), al toque deberías buscar el entrenador que está cerca del pokemon para planificarlo. Mientras tanto, el hilo "suscriptor" (el que recibió el mensaje y levantó otro hilo para procesarlo) envía un ACK y vuelve a revisar el socket a ver si hay más mensajes.
Yo entiendo que todo el tema de comunicación debería ser más lento que la búsqueda del entrenador, así que me parece difícil que no llegues a elegir entrenador mientras el otro hilo ya envío ACK, recibió appeared y creó un nuevo hilo para procesar.

Por otro lado (asumiendo que no tuviera razón en suponer que enviar/recibir es más lento):
Para agregar el pokemon al mapa tomás el mutex del mapa. Para elegir al entrenador, tomás también un mutex. Por lo que, aunque por algún extraño motivo el segundo hilo "procesador" ejecutara mucho más rápido que el primero, el primero siempre llevaría la delantera porque ya tomó primero el primer mutex y a partir de ahí el otro tendría que esperarlo a que libere.

Contame si estás haciendo algo distinto a lo que comenté a ver si así podemos hacernos una mejor idea de qué puede estar pasando 😉

**Comment by franpassa** [comment]
> > Hola, yo tengo un problema al ejecutar el script. A veces me pasa que llegan 2 appeared seguidos antes de que se planifique el primer entrenador, eso hace que el entrenador B se planifique al squirtle. Ya meti mutex por todos lados, pensando que era un problema de sincronizacion, pero ya no se como solucionarlo, el 70% de las veces el resultado me da, pero en otras al planificarse mal el primero afecta al resto de la planificacion. Esto me pasa en el caso FIFO. Alguno le paso lo mismo o me puede dar una pista de como solucionarlo? No logro tener el 100% de las pruebas bien.
> 
> Buenas, no soy ayudante... pero a ver si puedo ayudarte! 😆 
> 
> Me parece raro lo que comentas, porque cuando llega el primer mensaje ahí levantas un hilo para procesarlo y, después de unas mínimas validaciones (ver si necesitas el pokemon), al toque deberías buscar el entrenador que está cerca del pokemon para planificarlo. Mientras tanto, el hilo "suscriptor" (el que recibió el mensaje y levantó otro hilo para procesarlo) envía un ACK y vuelve a revisar el socket a ver si hay más mensajes.
> Yo entiendo que todo el tema de comunicación debería ser más lento que la búsqueda del entrenador, así que me parece difícil que no llegues a elegir entrenador mientras el otro hilo ya envío ACK, recibió appeared y creó un nuevo hilo para procesar.
> 
> Por otro lado (asumiendo que no tuviera razón en suponer que enviar/recibir es más lento):
> Para agregar el pokemon al mapa tomás el mutex del mapa. Para elegir al entrenador, tomás también un mutex. Por lo que, aunque por algún extraño motivo el segundo hilo "procesador" ejecutara mucho más rápido que el primero, el primero siempre llevaría la delantera porque ya tomó primero el primer mutex y a partir de ahí el otro tendría que esperarlo a que libere.
> 
> Contame si estás haciendo algo distinto a lo que comenté a ver si así podemos hacernos una mejor idea de qué puede estar pasando 😉 
> 

Gracias genio!! Me sirvio tu explicacion 👍

**Comment by ncoen97** [comment]
Buenas, me parece que todas las dudas quedaron resueltas.
Gracias a los que aportaron y cualquier cosa no duden en seguir consultado.
Saludos!
