### ISSUE TITLE
[GameCard] Dudas con la lectura y escritura de bloques

### ISSUE THREAD

**Issue by jftierno** [sisoputnfrba/foro#1835]
¡Buenas!

Estando bastante avanzados con la implementación del FileSystem, nos dimos cuenta que estabamos pasando por alto un punto muy importante: incrementar/decrementar la cantidad de pokemones que hay en cierta coordenada implica, en ciertos casos, un cambio en el tamaño de bytes escritos en el bloque; es decir, si la cantidad de pokemones es 9 y debo incrementarla, tener un 10 sumaría 1 byte al archivo, que significaría correr todo 1 byte a la derecha. Suponiendo que el bloque a modificar se encontraba lleno, esto ocasionaría un comportamiento no deseado.
Nuestro FileSystem **actual**, realiza los siguientes procedimientos:
1. Llega un NEW_POKEMON.
2. Chequeo de existencia del pokemon (con sus respectiva creación si no existe).
3. Se obtienen las  coordenadas del NEW_POKEMON y la cantidad
4. Verificación de bloques asignados
4.1. Si lo que se desea escribir entra en el archivo, entonces se escribe al final del mismo (NO incrementamos la cantidad previa como deberíamos hacerlo, escribimos nuevas coordenadas aunque estén repetidas)
4.2. Si lo que se desea escribir entra en el archivo, entonces se le asigna un bloque nuevo para luego poder escribir lo que no haya entrado (NO buscamos la coordenada como tal, escribimos siempre al final del archivo).
5. Etcétera.

Respecto a lo explicado anteriormente, pensamos una posible solución respecto al paso 4. Explicada paso por paso:
4. Verificar si las posiciones ya existen dentro del archivo. 
4.1. En caso de existir, se debe agregar la cantidad pasada por parámetro a la actual. 
**Solución propuesta:** 
4.1.1. Mapear los bloques asignados a memoria (en un buffer)
4.1.2. Borrar todos los bloques previamente asignados al pokemon en cuestión (a nivel FileSystem)
4.1.3. Modificar los bloques mapeados en memoria (con la nueva cantidad)
4.1.4. Volver a asignar bloques disponibles y escribirlos con el buffer modificado.

4.2. En caso de no existir se debe agregar al final del archivo una nueva línea indicando la cantidad de pokemon pasadas (como lo veníamos haciendo).

Entendemos que si se tratase de un FileSystem real, la solución sería muy ineficiente dada la cantidad bestial de accesos a disco ocasionados, pero no encontramos otra solución posible.
¿Podría alguien darnos una mano para encaminarnos a una solución "más correcta"?

¡Muchas gracias!
      Fran&Co.

**Comment by iago64** [comment]
Buenas!

A ver si entiendo, la idea es mapear los bloques a memoria con mmap(), de eso llevarlo a un buffer para hacer todas las operaciones con strings para dejar el nuevo archivo y después volver a guardar los datos en los distintos bloques?

Si eso te mantiene el FS de manera correcta, no hay problema :wink:
Después si estas matando una mosca con un [Panzerkampfwagen](https://es.wikipedia.org/wiki/Panzer) o no lo podemos charlar en el coloquio y eventualmente podremos charlar como lo hacen un SO posta posta, eso es parte del objetivo del TP, que puedan ver la diferencia entre la implementación posta y lo que terminan haciendo dentro de lo posible en 1 cuatrimestre.

Abrazo.-

**Comment by jftierno** [comment]
Bueno, al final llevamos a cabo la implementación propuesta con éxito!

Muchas gracias por la pronta respuesta, cualquier cosa re abro el issue.
