### ISSUE TITLE
[Broker] Duda respecto a Multihilos para prueba final

### ISSUE THREAD

**Issue by federicosolomonovici** [sisoputnfrba/foro#1836]
Hola!

Estamos realizando las pruebas para la entrega final y tenemos una duda respecto al comportamiento del broker:

Según lo que se especifica en el enunciado el broker debe trabajar utilizando una arquitectura de multihilos:

![image](https://user-images.githubusercontent.com/18030751/87491521-bff45200-c61e-11ea-9af1-7d1ea3dcab75.png)

Dado esto, nosotros creamos un hilo nuevo por cada mensaje que se recibe para luego procesarlo. La cuestión es que al momento de realizar las pruebas, por lo que vemos según el documento de pruebas, el resultado debería ser 'secuencial' ya que te va a guiando con lo que debería suceder. Por ejemplo:

![image](https://user-images.githubusercontent.com/18030751/87491696-34c78c00-c61f-11ea-9c4a-1ce8a8769d9b.png)

Si aplicamos estas pruebas, con la implementacion de multihilos que planteamos, el resultado que obtenemos es no deterministico. Siempre obtenemos resultados diferentes.

Entonces consulto, estamos teniendo algún error en el concepto de multihilos o en la implementacion en si? Puede que haya que sincronizar estos hilos de alguna forma?

Gracias!

**Comment by iago64** [comment]
Buenas!

Si, efectivamente el broker **debe ser multihilo**, pero en el caso de la prueba dado que el script corre secuencial los mensajes deben llegarles secuencial. Tengan en cuenta que un gameboy va a iniciar después de que finaliza el anterior.

Imagino que al gameboy le estan confirmando la recepción del mensaje no? 

Saludos.-

**Comment by pacoDan** [comment]
Hola,
pero la cuestión es la siguiente,
el script si se va a ejecutar secuencialmente, ahora cuando llegue  a
broker no, por que cuando para cada línea del script (el .sh) se  empaqueta
y se lo envía al broker *son de distintos tiempos*, empaquetar y enviar
para una línea puede consumir menos tiempo y para alguna otra linea del
.sh mas tiempo, para el caso de esta última  es el caso que le llega como
último mensaje a broker (es más probable),
y cuando mencionás el ack , en mi grupo ya tenemos eso contemplado (y tengo
entendido que esto me sirve para cuando matemos un team o un GCard para no
mandarle mensajes que ya enviamos/procesaron etc), ¿ como tiene que ver
esta última para asegurar el orden cuando procesa broker?¿por ser
multihilos como se pretende asegurar el orden?

**Comment by iago64** [comment]
Buenas @pacoDan 

La idea del script es que un gameboy no inicia hasta que termina el anterior, con lo cual, al broker le deberian llegar de a 1 los mensajes independientemente de que sea multihilo o no.
La parte de multihilo la van a testear mas en la prueba completa :wink:

Saludos.-

**Comment by charlyd96** [comment]
Buenas, yo también tengo el mismo problema con el Team. Como cada mensaje se atiende con un hilo separado, los APPEARED por ejemplo no siempre se procesan en el mismo orden, y es lógico, porque apenas se recibe se lanza un hilo, y luego ese hilo procesa la recepción del resto del mensaje (que implica la deserialización) y luego los agrega (o no) al mapa. Asimismo ya hay otro hilo procesado otro mensaje. Siempre arroja resultados no determinísticos y concluí que es porque los hilos que se lanzan para tratar cada mensaje, los planifica el planificador de la VM como se lo antoja, y a veces termina primero uno antes que otro. Si bien el Team finaliza igual, este comportamiento podría afectar la ocurrencia de los deadlocks, ya que al llegar primero un mensaje que otro, se pueden planificar entrenadores en distinto orden, ocasionando distintos deadlocks.

**Comment by iago64** [comment]
Buenas!

Vuelvo sobre la pregunta previa, al momento de que el gameboy envía el mensaje, están recibiendo la confirmación de que el broker recibió el mensaje y les envió el id del mismo?
Justamente ese es el punto en el cual nosotros basamos la prueba ya que en un script de bash es todo secuencial y un gameboy no debería empezar hasta que termina el anterior.

Saludos.-

**Comment by pacoDan** [comment]
Hola Damian,  disculpa la demora (con esta situación y parciales m demora,
lo que decis lo probare  bien devuelta mañana o quizás hoy en la noche)
te voy comentando, ahora con el tema de multihilos, en broker lo tengo asi
(cuando cacheo el mensaje)  :  cuando llega un paquete abre un hilo
(llamémosle hilo1), llega otro y abre otro hilo2 etc, un hilo puede
desempaquetar (deserializar etc) , tengo el mensaje (el appeared o
localized etc), asignó id , luego envió id al emisor correspondiente,
después hago el cacheo ,pero antes de cachear el mensaje , el hilo2 (de la
segunda conexión puede desempaquetar y asignar id más rápido ) puede llegar
a usar la función ,llamémosle cachear_mensaje() , antes que hilo1  de la
primera conexión ,en  esa función  cachear_mensaje ()  tengo un semáforo
para que se use de uno a la vez... eso del ack simplemente lo procesa otro
hilo de otra conexión ... y con todo eso , no me aseguro el orden del
script .sh

Saludos

**Comment by ncoen97** [comment]
Buenas, lo que quiere decir dami con el tema del ack es que como el script de consola es secuencial, un gameboy no puede empezar antes de que termine el otro. Teniendo eso en cuenta, si enviamos el "mensaje 1", no vamos a poder mandar el "mensaje 2" hasta que el id de "mensaje 1" no llegue como respuesta al gameboy y ahí este finalice (y para que eso pase ya el Broker tuvo que haber asignado el id a "mensaje 1"), por lo tanto no debería dar el tiempo para que proceses el "mensaje 2" antes del "mensaje 1" si respetamos la respuesta de ack al cliente.
Saludos!

**Comment by benjamd** [comment]
> Buenas, lo que quiere decir dami con el tema del ack es que como el script de consola es secuencial, un gameboy no puede empezar antes de que termine el otro. Teniendo eso en cuenta, si enviamos el "mensaje 1", no vamos a poder mandar el "mensaje 2" hasta que el id de "mensaje 1" no llegue como respuesta al gameboy y ahí este finalice (y para que eso pase ya el Broker tuvo que haber asignado el id a "mensaje 1"), por lo tanto no debería dar el tiempo para que proceses el "mensaje 2" antes del "mensaje 1" si respetamos la respuesta de ack al cliente.
> Saludos!

Hola, me surgieron dudas con a partir de tu comentario:

1. Entonces desde el punto de vista de gameboy la secuencia de ejecución de envío de mensaje seria así?:

conectar(socket_broker)
enviarMensaje(mensaje, socket_broker)  
recibirACKdeBroker(socket_broker);
cerrarConexion(socket_broker);
exit 0 //finaliza programa gameboy 

2. De igual manera tiene que pasar lo mismo si el mensaje va para Team y Gamecard? 

3. Cuando Gamecard envía mensajes Appeared, Caught, Localized generados a partir de los mensajes new, catch y get correspondientes, posteriormente debe quedarse a la espera de recibir un ACK del broker?

Saludos!

**Comment by iago64** [comment]
Buenas!

Efectivamente, la secuencia del Gameboy debería ser:
```
conectar()
enviarMensaje(mensaje)
recibirACK();
cerrarConexion();
```
Independientemente del módulo, porque en el `recibirACK()` te aseguraste de que el mensaje llego, después si te manda un id de mensaje random o te manda siempre 0 no importa, pero vos como cliente queres asegurarte que el mensaje llego.

De esa ultima frase desprende el hecho de que si, el GameCard debería recibir un ACK de que el mensaje fue recibidoy nuevamente no le importa al GameCard lo que el broker haga después, solo le importa asegurarse que el mensaje llego.

Saludos.-
