### ISSUE TITLE
[Pruebas] Error en uno de los scripts de la prueba final

### ISSUE THREAD

**Issue by wade98** [sisoputnfrba/foro#1837]
Buenas noches, una pregunta que dejamos por acá en esta noche de fuerte testeo. En la prueba completa dice que ejecutemos new_pokemon_antes_team.sh
```
#!/bin/sh
./gameboy TEAM APPEARED_POKEMON Pikachu 9 9
./gameboy TEAM APPEARED_POKEMON Squirtle 5 2

./gameboy TEAM APPEARED_POKEMON Jolteon 2 2
./gameboy TEAM APPEARED_POKEMON Flareon 4 6
```
Pero team no está levantado todavía, asi que claramente a Team no van esos mensajes. Los mandamos a Broker o a GameCard?

**Comment by wade98** [comment]
Otro detalle que nos dimos cuenta más tarde ¿Puede ser que sean NEWs en vez de APPEAREDs? El nombre del script parece intentar de indicar eso.

**Comment by iago64** [comment]
Buenas!

Ya estan fixeados los scripts.
Los mensajes son APPEARED y van al BROKER, ya estan actualizados en el [ultimo commit](https://github.com/sisoputnfrba/delibird-pruebas/commit/bcdfd14fd4b7468cf29e56696735262036ee1d21) del [repo de las pruebas](https://github.com/sisoputnfrba/delibird-pruebas)

Saludos.-

**Comment by wade98** [comment]
Buenos días! Gracias por contestar tan rápido. Hay algo que no nos sigue cerrando:
Mandamos los primeros cuatro APPEARED a Broker, una vez arriba los Teams planifican a sus entrenadores para ir a atraparlos. Pero, como Game Card no está suscrito a APPEARED nunca se entera de estos cuatro pokemon que entraron al sistema. Entonces, cuando cada Team manda sus CATCH, a no ser que justo en ese momento pierda conexión con el Broker, va a esperar una respuesta en vez de asumir el comportamiento default. Cuando Broker le hace llegar un CATCH, Game Card contesta con un CAUGHT diciendo que no lo atrapó, porque ese pokemon no existe en FS. Es decir, nunca se va a atrapar ningún pokemon.

Sin embargo, la idea acá pareciera ser que de alguna manera Broker se comunique con Game Card para persistir estos Pokemon. Cambiando todos los APPEARED por NEW (cuyo flujo si avisa a Game Card) nos funcionó todo bien.

Las únicas dos cosas que se nos ocurrieron son:

1- Que no hayamos implementado bien el comportamiento default, pero según enunciado esto es solo en caso de fallo de conexión con el Broker.
```En caso que el Broker no se encuentre funcionando o la conexión inicial falle, se deberá tomar como comportamiento Default que el Pokémon ha sido atrapado con éxito.```

2 - Que el flujo de los APPEARED que entran a Broker no sea el correcto, pero no vemos la manera de hacer que Game Card se entere sin usar NEW.

**Comment by iago64** [comment]
Buenas!

Justamente Gamecard no esta suscrito a APPEARED porque es un mensaje que el genera, con lo cual el Broker no tiene NADA que informarle.
La idea de mandar appeared justamente es que los entrenadores del team se muevan pero no atrapen nada, para ver como se van moviendo y planificando los entrenadores en un entorno "no tan controlado" como en la prueba de planificación.
Después todos los temas de los pokemones que no existen, tienen una solución simple que es ir mandando los NEW al broker desde un gameboy y viendo que pasa. No pierdan de vista que la prueba final tiene objetivo ver el comportamiento **completo** del sistema y ver, por ejemplo, que pasa si quieren atrapar algo que no existe (porque nunca fue creado) y que pasa si después lo creamos en una posición random.

Saludos.-

**Comment by wade98** [comment]
Buenas noches. Primero que nada, entendemos que a lo que va el test es probar que las cosas que deberían funcionar funcionen, que las que no deberían no funcionen y que todo quede loggeado apropiadamente. 

Nuestra duda es la siguiente ¿Qué NEWs hay que mandarle a broker? Porque los dos scripts que tenemos tienen solo APPEARED, sobre los que coincidimos que no logran ningún cambio en los pokemon de los entrenadores. 

Como el test pide que los entrenadores cumplan sus objetivos, asumimos que la idea era que el resultado sea que justamente cumplan sus objetivos. Lo que pasa es que las actividades no incluyen los pasos necesarios para que eso ocurra.

![](https://cdn.discordapp.com/attachments/695268549794725910/733469272252219402/Cap.png)

¿Estaríamos modificando la prueba al incluir NEWs? ¿Los tenemos que hacer por afuera del test? ¿O el correcto funcionamiento sería que todos los entrenadores sufran de inanición por la incapacidad de atrapar pokemones?

Desde ya, gracias por tomarse el timepo de leer y contestar.

**Comment by iago64** [comment]
@wade98 despreocupate que eso lo va a ver el ayudante segun lo que necesite validar el ayudante 😊 

Saludos.-

**Comment by iago64** [comment]
@wade98 Despues de la primer entrega, nos dimos cuenta que era una patada ir escribiendo los new y que perdíamos bastante tiempo, así que terminamos cambiando los appeared por new 😉 

Abrazo.-
