### ISSUE TITLE
Consulta sobre logs en Gamecard y documento de pruebas.

### ISSUE THREAD

**Issue by gebonora** [sisoputnfrba/foro#1838]
Buenas! Una consulta sobre el nivel de detalle de logs en Gamecard.

En el documento de pruebas pide:
- Ante cambios en las estructuras del FileSystem el sistema informa correctamente cuáles son las operaciones realizadas (bloques que cambiaron, metadatas, archivos)

Actualmente estoy logeando recepción/procesamiento/envío de mensajes, falla en envíos a Broker porque no se pudo establecer conexión, reintento de conexión a Broker y reintento de operaciones por archivo abierto. Mirando el enunciado no encontré que se especifiquen más cosas a logear.

Entonces, para ver los cambios en bloques, archivos y metadatas, hace falta agregar logs que los muestren, o con verificarlo en el file system de Linux alcanza?

Gracias!

**Comment by iago64** [comment]
Buenas!
Deberias tener en algun log que tenga la info, no al detalle de decir que hiciste pero si que fue lo que hiciste, por ejemplo:

- Asignar un bloque a un archivo
- Eliminar un archivo
- Liberar un bloque
- etc

La idea de un log (y esto es una regla general mas alla de sisop) es que permita entender que esta pasando en el sistema a medida que este ejecuta, cuanto mas claro y prolijo sea, mucho mejor :wink:

Saludos.-

**Comment by gebonora** [comment]
Genial, gracias!
