### ISSUE TITLE
[Team] Duda en valor de configuración para las pruebas

### ISSUE THREAD

**Issue by alanzhag** [sisoputnfrba/foro#1839]
¡Buenas!

Segun el [doc](https://docs.google.com/document/d/1_MHl52R-wPyL4SaWYok4Crf47dVwlqZOQn1MWouo3T8/edit?usp=sharing) para las pruebas, el campo POKEMON_ENTRENADORES=[Pikachu] consiste en una lista de un solo elemento.  
Ya que POSICIONES_ENTRENADORES=[1|3,2|3,2|2] indica 3 entrenadores, ¿No deberia POKEMON_ENTRENADORES ser [Pikachu,,] o [Pikachu,None,None]?

Nota: config_get_array_value devuelve un char **

**Comment by iago64** [comment]
Buenas!

El config solo lo especificamos para decir que el entrenador A tiene un pikachu, y los demás empiezan sin nada. Si necesitan que estén las , para los otros espacios vacíos para levantarlo pueden agregarlo no hay problema, mientras no cambie que solo A tiene 1 pikachu.

Saludos.-

**Comment by alanzhag** [comment]
Genial, lo acomodamos a nuestro código.

¡Saludos!
