### ISSUE TITLE
[Team] Consulta enunciado de logs

### ISSUE THREAD

**Issue by ezeveliz** [sisoputnfrba/foro#1841]
En la sección de Logs obligatorios del Team dice: "Dado que el log será el medio de validación del trabajo práctico **<ins>se exige no utilizar la consola como medio de loggeo</ins>**" y en el segundo párrafo de la sección de Planificación dice: "Una vez alcanzado el objetivo se deberá informar por archivo de log **<ins>y por pantalla el resultado alcanzado</ins>** y finalizar el proceso.", cuál de las dos seria la correcta?

**Comment by iago64** [comment]
Buenas!

Respuesta Corta: La idea es que todos los logs a archivo, pero el resultado final que si este en archivo y pantalla.

Explicación:
El enunciado nos quedo un toque, ambiguo, pero la idea de no usar la pantalla como medio de log es que no estén imprimiendo todos los mensajes de logs ahí porque si no lo importante (como el resultado del proceso) se nos pierde porque es imposible estar siguiendo todos los mensajes que se imprimen, mientras que en un archivo de log los podemos revisar con tranqui.

Saludos.-

**Comment by ezeveliz** [comment]
ok, genial!
