### ISSUE TITLE
Duda entrega final

### ISSUE THREAD

**Issue by MarianoPessina** [sisoputnfrba/foro#1842]
Buenas, en uno de los puntos sobre lo que se espera en la entrega final dice lo siguiente:
El sistema continúa su funcionamiento ante comandos erróneos o paths inexistentes (informando al usuario el error)
Cuando habla de paths inexistentes, a qué se refiere? que el config no esté donde debe estar? o que se nos de un punto de montaje erróneo?
O simplemente se refiere a que llegue un get o un catch de un pokemon que no existe?

**Comment by iago64** [comment]
Buenas buenas!

A lo que nos referimos es por ejemplo que les pidamos un CATCH de Onix y Onix nunca fue creado en el FS 😄 

Abrazo.-

**Comment by MarianoPessina** [comment]
ahhh eso si lo manejamos, cierro el issue, gracias :)
