### ISSUE TITLE
Script para cargar biblioteca compartida

### ISSUE THREAD

**Issue by MarcosInfantino** [sisoputnfrba/foro#1843]
Hola! Estamos tratando de crear un script para cargar un biblioteca que desarrollamos para el tp, pero el mismo la exporta correctamente.
El archivo se llama "export.sh" y tiene la siguiente línea:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/home/utnso/tp-2020-1c-Programadores-en-Fuga/messages_lib/Debug

Siendo "/home/utnso/tp-2020-1c-Programadores-en-Fuga/messages_lib/Debug" el path de la biblioteca. Lo ejecutamos desde consola con ./export.sh y no nos exporta la lib correctamente, ya que al hace ldd nos dice que no la encuentra. Alguna idea? Está algo mal en la línea? Hay que hacer algo más? Le estuve dando mil vueltas e investigando pero no se cómo hacerlo funcionar. Gracias!

**Comment by iago64** [comment]
Buenas buenas!
Respuesta rápida: si hacen `. ./export.sh` deberia funcionarles 😄 

Respuesta Extensa:
La cuestión no es que este mal el script, ni que uds estén metiendo la pata, es una cuestión de que nunca les contaron que cuando uds corren un script en Bash por atras sucede una serie de magias bastante oscuras que consisten en:
1.- Bash crea una nueva sesión por atrás
2.- Bash ejecuta el script que uds le pasaron en la nueva sesión (Algo así como si abrieran una nueva consola)
3.- Al finalizar el script esa sesión que se creo para correr su script termina y se lleva los cambios
4.- Como el export se hizo en la sesion que acaba de morir uds al consultarla desde la sesión nueva no lo ven.
5.- Creen que metieron la pata cuando el script esta bien

Espero que la duda haya quedado resuelta, cualquier cosita avisen.

Saludos.-

**Comment by MarcosInfantino** [comment]
Espectacular! Todo andando! Gracias!

**Comment by MarcosInfantino** [comment]
Hola! En la vm ubuntu con entorno gráfico me funcionó de lo más bien, pero en el ubuntu server no anda. Qué podría ser? Todo está puesto en un path idéntico.

**Comment by mgarciaisaia** [comment]
En `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/home/utnso/tp-2020-1c-Programadores-en-Fuga/messages_lib/Debug` te sobra algo.

`~` es equivalente a decir `/home/EL_USUARIO_ACTUAL`. Entonces `~/home/utnso` es como decir `/home/utnso/home/utnso`. Casi seguro que eso no sea lo que quieren/necesitan.

Después de ejecutar ese `export`, podés hacer `echo $LD_LIBRARY_PATH` para ver cómo quedó la variable. Y le deberías poder hacer `ls -l` a cada path que aparezca ahí, para ver si existen o no esos paths.

**Comment by MarcosInfantino** [comment]
Le borré el ~ y sigue sin funcionar, también corroboré si existía el directorio y está. No sé qué más podría ser. Gracias!

**Comment by mgarciaisaia** [comment]
¿Cómo chequeaste que existía el directorio?

**Comment by mgarciaisaia** [comment]
Si estás `export`ando bien la variable, y los paths que están en la variable existen, y tienen las cosas que tiene que tener - entonces tu programa funciona.

Si no funciona, alguna de esas condiciones no se está dando. Si no puedo ver qué valor tiene la variable, ni cómo chequeaste que existen los directorios, ni si existen las bibliotecas correspondientes, ni el error que te está mostrando al ejecutar, no tengo forma de saber cuál de todas las condiciones falla. Y, menos que menos, cómo solucionarla.

**Comment by MarcosInfantino** [comment]
![image](https://user-images.githubusercontent.com/49456888/87731833-cd861500-c7a1-11ea-8f55-3973ac2edf83.png)
Eso es lo que estoy haciendo

**Comment by mgarciaisaia** [comment]
¡Eso es! Falta compilar.

Fijate que, cuando hacés el `ls -l`, _el directorio_ existe, pero no tiene ningún `libmessages_lib.so`.

Tenés que compilar la biblioteca. Parece que hay un `makefile` ahí, ¿supongo que haciendo `make` en ese directorio compilará?

El `LD_LIBRARY_PATH` tiene que apuntar al directorio que contenga el `libmessages_lib.so`.

**Comment by MarcosInfantino** [comment]
Uff es verdad. 2 hs buscandole la vuelta y me olvida de compilar, gracias!
