### ISSUE TITLE
[Pruebas] Error falta de id en Appeared_Pokemon

### ISSUE THREAD

**Issue by GustavoChoque** [sisoputnfrba/foro#1844]
Buenas Noches, queríamos saber si falta un parámetro en las pruebas, new_pokemon_antes_team.sh y new_pokemon_post_team.sh

`#!/bin/sh`
`./gameboy BROKER APPEARED_POKEMON Pikachu 9 9`
`./gameboy BROKER APPEARED_POKEMON Squirtle 5 2`
` `
`./gameboy BROKER APPEARED_POKEMON Jolteon 2 2`
`./gameboy BROKER APPEARED_POKEMON Flareon 4 6`

En el enunciado pagina 30 en mensajes que envia el GameBoy dice lo siguiente

**Broker - Appeared Pokemon**
Permitirá enviar un mensaje al Broker a la cola de mensajes APPEARED_POKEMON. Para esto, el
formato del mensaje será:
`./gameboy BROKER APPEARED_POKEMON [POKEMON] [POSX] [POSY] [ID_MENSAJE_CORRELATIVO]`

Cabe aclarar que el ID_MENSAJE será un valor definido tanto por la cátedra como por los alumnos al
realizar sus propios test. Este ID dentro de un script o entorno de ejecución deberá ser ÚNICO.

¿Se deberian corregir los scripts y agregarle un idCorrelativo?

#1759 

saludos y gracias

**Comment by iago64** [comment]
Buenas!

Si, eso lo pueden agregar, a priori se nos paso y como muchos grupos lo resolvieron poniendo un ID correlativo random en el gameboy se nos paso, pero para correr los tests pueden ponerle los valores al script, no hay problema con eso.

Saludos.-

**Comment by GustavoChoque** [comment]
Gracias por la respuesta, eso haremos.
Saludos
