### ISSUE TITLE
Programacion: mmap me agrega caracteres que no estan en el arcihvo

### ISSUE THREAD

**Issue by leobz** [sisoputnfrba/foro#1845]
Buenas! Estoy usando mmap para leer archivos, el problema es que quiero pasar el contenido del archivo a un char*, pero si bien logro obtener el contenido, tambien se me agregan saltos de linea(o espacios) al char*. Queria saber si hay algo que estoy haciendo mal.

**archivo.txt**
```
Soy un texto!
```

**codigo.c**
```c
#include <stdio.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/stat.h>

int main(){
	char* file_name = "archivo.txt";

	struct stat s;
	int fd = open(file_name, O_RDWR | O_CREAT, (mode_t) 0600);
	int status = fstat(fd, &s);
	int size = s.st_size;

	char* buffer_leido = mmap(0, size, PROT_READ, MAP_PRIVATE, fd, 0);

	printf("Buffer:%sEOF\n", buffer_leido);	
}

```

**Salida obtenida:** 
```
Buffer:Soy un texto!
EOF
```

**Comment by mgarciaisaia** [comment]
¡Hola @leobz!

Está buena la pregunta :)

Suena raro que `mmap` agregue saltos de línea, ¿no? Sobretodo porque `mmap` dice trabajar con _bytes_ (o, si querés, _páginas de memoria_), que no necesariamente son strings imprimibles. Entonces, buen - es raro que agregue información arbitraria.

Probé lo que decís, y pude reproducirlo*. El `*` es porque no contás cómo creaste tu `archivo.txt`, y ahí está el meollo del asunto.

Arranqué haciendo `vim archivo.txt` y escribiendo el texto que pusiste: `Soy un texto!`. Escape, `:wq!`, y entonces sí pasa todo eso que decís. Incluso pasa _exactamente lo mismo_ si el archivo lo creo haciendo `echo 'Soy un texto!' > archivo.txt`. Mirá:

```
utnso@ubuntu-server:~$ echo 'Soy un texto!' > archivo.txt 
utnso@ubuntu-server:~$ ./codigo 
Buffer:Soy un texto!
EOF
```

Habiendo chequeado esto, quise ver qué había en el archivo:

```
utnso@ubuntu-server:~$ cat archivo.txt 
Soy un texto!
utnso@ubuntu-server:~$ hexdump -C archivo.txt 
00000000  53 6f 79 20 75 6e 20 74  65 78 74 6f 21 0a        |Soy un texto!.|
0000000e
utnso@ubuntu-server:~$ ls -l archivo.txt 
-rw-rw-r-- 1 utnso utnso 14 jul 17 03:08 archivo.txt
```

De abajo para arriba, sorpresas: el archivo pesa `14` bytes - pero el string `Soy un texto!` tiene sólo 13 caracteres. `hexdump` es un comando que muestra la representación hexadecimal de cada byte que compone al archivo, y a la derecha trata de mostrar los caracteres imprimibles. Después del `!` hay un `.` (es decir, _un caracter no imprimible_). Si miramos en la columna del medio, después del byte `0x21` hay un `0x0a`. Si mirás en [la tabla ASCII](https://es.wikipedia.org/wiki/ASCII#Los_caracteres_de_control_ASCII), el **hex** `0a` corresponde al caracter `LF` (line feed - salto de línea). Es decir ¡hay un salto de línea en el archivo! Y el primer comando nos lo re-confirma: cuando le pedimos a `cat` que imprima en pantalla todo el contenido del archivo, metió un salto de línea al final.

Es que, _por defecto_, `echo` agrega un salto de línea al final. Gratis. Porque, en general, queremos que el prompt de la consola (o el siguiente mensaje que se imprima) empiece en una línea nueva después de un `echo`. _Pero no siempre_. Para evitarlo, `echo` soporta un flag `-n`, que evita que se escriba ese salto de línea al final:

```
utnso@ubuntu-server:~$ echo -n 'Soy un texto!' > archivo.txt 
utnso@ubuntu-server:~$ cat archivo.txt 
Soy un texto!utnso@ubuntu-server:~$ 
utnso@ubuntu-server:~$ ./codigo 
Buffer:Soy un texto!EOF
utnso@ubuntu-server:~$ 
```

Fijate cómo acá `cat` imprimió el texto, y _pegadito al lado_ salió el prompt que seguía. Yo metí un Enter a propósito para ejecutar un comando vacío y tener el prompt al inicio de la línea siguiente - y ahí ejecuté tu código, que efectivamente mostró el `EOF` sin el salto de línea, _porque el archivo ya no contiene el salto de línea_.

Así que la conclusión es que no era `mmap` el que agregaba el salto de línea, si no que _el archivo ya lo tenía_.

----

Más arriba conté que empecé haciendo `vim archivo.txt`, y el resultado fue el mismo, por más que en `vim` veamos una única línea de texto.

Lo que pasa, _en el fondo_, es que [para el estándar POSIX una línea es un montón de caracteres terminados en un caracter newline](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206). Es decir, para el estándar que define qué es un sistema operativo de tipo UNIX, las líneas de texto terminan en un `\n`. Como `vim` escribe líneas de texto, agrega el `\n` al final. Y por eso la mayoría de las herramientas que trabajan con texto tienden a terminar los archivos en un `\n` - porque manejan _líneas_.

**Comment by enogueiras** [comment]
hola @mgarciaisaia excelente la explicación, a mi me pasaba eso justamente en mis pruebas de bloques con filesystem, cuando armaba los archivos de bloques con el editor del eclipse, el valor del size era el correcto, pero si lo hacia con vi agregaba ese salto de linea y sumaba un 1 byte mas, y me jodía todo en mis pruebas (que estaban bien codeadas jajaja).

**Comment by leobz** [comment]
Muchisimas gracias!!!! Si, justamente estaba usando Vim. Ahi lo pude solucionar!!!!
