### ISSUE TITLE
Alta utilización de cpu con el recv

### ISSUE THREAD

**Issue by MarcosInfantino** [sisoputnfrba/foro#1846]
Buenas! Probando todos los módulos con htop corriendo de fondo nos dimos cuenta de que tanto el team como el gamecard poseen una utilización de cpu relativamente alta. Con relativamente alta me refiero a que, teniendo asignada a la VM 3 cores, el gamecard por ejemplo puede llegar  utilizar uno completo (1 core), o sea un 33% del total de cpu.
Probando diferentes cosas nos dimos cuenta que esto es a causa de que nosotros tenemos tanto al team como al gamecard esperando, para recibir los mensajes de las suscripciones, con algo del estilo:
while(1)
      recv(paquete, ... ,MSG_WAITALL);
Y esto nos estaría originando ese consumo de CPU. Ahora bien, las preguntas serían:
1-Por qué consume tantos recursos si no es una espera activa? Se supone que el recv debería bloquear el while(1)
2-Es realmente un consumo muy alto de recursos? O es aceptable?
Muchas gracias y saludos!

**Comment by CamiMargni** [comment]
Dejo centinela para ver respuesta.

**Comment by mgarciaisaia** [comment]
Tener una CPU completa tomada por un proceso _probablemente_ sea señal de que hay una espera activa.

¿Tienen mensajes _constantemente_ yendo y viniendo entre dos procesos? Si no es ese el caso, probablemente estén teniendo una espera activa. ¿Algo raro en la inicialización de los sockets? (onda, _¿marcar a los sockets como no bloqueantes?_)

En la vista del debugger de Eclipse, mientras tu proceso está ejecutando, tenés un botón con un icono de Pausa que le manda una señal a tu proceso para frenar la ejecución (igual que si frenara en un breakpoint). Podés probar eso para ver qué código está ejecutando tu proceso, por ejemplo.

Otras versiones menos felices incluyen meter un `printf` o algo así en el ciclo que creas que puede estar ejecutándose infinito.

Cuando tengas seguridad de dónde se está haciendo el ciclo ese manija, ahí podés empezar a mirar _por qué_.

**Comment by MarcosInfantino** [comment]
Encontre el problema! Ahora no consume casi nada asi que bien, gracias!

**Comment by enogueiras** [comment]
> Encontre el problema! Ahora no consume casi nada asi que bien, gracias!

Hola @MarcosInfantino ¿como va? ¿podras contar que era? estamos teniendo un problema similar con nuestro Gamecard, capaz nos ayuda.

Abrazo,
Emilio.

**Comment by MarcosInfantino** [comment]
Buenas! Te comento: mirando htop nos dimos cuenta en ese momento que tanto nuestro Team como nuestro Gamecard estaban usando muchisimo cpu. Al principio pensamos que eran unos recv dentro de un while(1) que nos estaban generando una espera activa, pero no era eso, ya que el recv espera hasta que le llegue un mensaje si se lo configura de manera correcta (el socket tiene que ser bloqueante). La solucion esta en revisar todo el codigo buscando algún while que genere un ciclo infinito (un while(1) que no tenga dentro de si nada que lo bloquee por ejemplo, o cualquier otro que itere hasta que se de una condicion y esta nunca sea alcanzada). En nuestro caso teniamos dos funciones similares en el gamecard y el team que tenian un while(1) escondido que nunca habiamos divisado. Eliminando todos estos ciclos deberías bajar tranquilamente el uso del cpu. Saludos y suerte!

**Comment by mgarciaisaia** [comment]
¡Aloha!

Si pueden reproducir su 100% de uso de CPU debuggeando desde Eclipse, siempre pueden darle "pausa" al debugger para que frene la ejecución del proceso y ver en qué está cada hilo en ese momento. Capaz eso los ayude a entender en qué parte están ciclando de más.

Y lo que dice @MarcosInfantino de **no usar sockets no-bloqueantes** es mucho muy importante. No lo aprendan como yo, que me costó una recursada la genial idea de "ah, hagamos sockets no bloqueantes así se nos deja de bloquear el proceso".

Bah, apréndanlo como puedan, pero ojalá les cueste menos que a mí 😇
