### ISSUE TITLE
NEW en prueba Broker

### ISSUE THREAD

**Issue by melaibanez** [sisoputnfrba/foro#1847]
Hola! Tengo una duda acerca de las pruebas de Broker -> consolidacion_basica.h
"_Se debe llenar la memoria y luego realizar una suscripción. Finalizada la misma se realiza un nuevo mensaje NEW_.."
Puede ser cualquiera? Porque no lo estaría visualizando en el repositorio de las pruebas.

**Comment by dariokozicki** [comment]
https://github.com/sisoputnfrba/foro/issues/1802
Sí, el .sh es el correcto y el doc está mal.
Saludos!

**Comment by iago64** [comment]
Aloha!

Efectivamente, lo importante es ver los mensajes que llegan a la suscripción y después que pasa post con el CATCH (el mensaje da lo mismo 😄).

Saludos.-

**Comment by melaibanez** [comment]
Genial. Muchas gracias!

**Comment by iago64** [comment]
@melaibanez Cerramos entonces o quedo alguna duda?
