### ISSUE TITLE
[BROKER] Diferencia FIFO y LRU

### ISSUE THREAD

**Issue by enogueiras** [sisoputnfrba/foro#1848]
Buenas noches, estoy terminando los algoritmos para memoria y no veo la diferencia entre FIFO y LRU en nuestro escenario del TP, yo utilizo una función de timestamp que al ser incremental, ya sea por FIFO o por LRU funcionaria de la misma manera al momento de elegir la victima para reemplazar (el primero que se ocupo).

Si me pueden orientar en caso de estar viendolo mal, muy agradecido.

Saludos,
Emilio.

**Comment by RodrigoLista** [comment]
Buenas. Te comento de la forma que lo hicimos nosotros. Tenemos una lista que maneja los punteros a la memoria (Que apuntan a cada mensaje). Cuando utilizamos FIFO, el primer puntero que fue agregado a la lista, seria el q se selecciona para eliminar. Y cuando usamos LRU, tenemos en cuenta el valor de timestamp. Obviamente, este valor, mientras no se llene la memoria, y solamente se agregen mensajes, va a funcionar de la misma forma que FIFO. La diferencia se ve, por lo menos en nuestro caso, cuando hay una suscripcion a una cola, ya que a todos los mensajes que le enviamos al suscriptor, le actualizamos el valor de LRU. Entonces, como ejemplo, si yo le envio a un suscriptor un mensaje, que su puntero se encuentrael primero en la lista, el valor de timestamp se actualizara. Si estamos en FIFO, lo seleccionariamos, pero en LRU, pasaria a ser el ultimo a eliminar, ya que fue el ultimo que se uso.

**Comment by papa-caco** [comment]
Hola Emilio y Rodrigo,

Emilio, la solución que utilizamos nosotros hace lo mismo que comenta Rodrigo, cuando el broker atiende una suscripción al momento de enviar un mensaje a un suscriptor, a la partición de datos correspondiente a ese mensaje le actualizamos el campito "valor_lru" con el timestamp() de ese mismo instante, mientras que al campito "orden_fifo" no lo modificamos. Al momento de elegir la partición víctima, se hace el ordenamiento de las particiones de acuerdo al algoritmo indicado en la configuración:  por "orden_fifo" o  "valor_lru".   Espero se haya entendido.

Suerte con la entrega!!
Saludos!

**Comment by enogueiras** [comment]
Buen día @RodrigoLista y @papa-caco , muchas gracias a ambos por la info, si, ahora si puedo ver la diferencia, y tengo claro como implementarlo.

Un abrazo,
Emilio.
