### ISSUE TITLE
[ENTREGA FINAL] Exposición de VMs Remotas 

### ISSUE THREAD

**Issue by benjamd** [sisoputnfrba/foro#1849]
Hola, tenemos dudas sobre las VMs en la nube para la entrega final. 
Quisiéramos saber si van a estar expuestas de forma publica o con ngrok, o bien si se encuentran conectadas entre si en un entorno de red local o vpn simulando la red del laboratorio de sistemas? La consulta viene porque estamos metiendo ngrok para pruebas remotas y aveces nos llegaban conexiones ajenas generando algunos inconvenientes. Dependiendo del grado de exposición sabremos si seguimos mejorando el handshake actual o nos enfocamos de lleno en las pruebas.   

Saludos!

**Comment by iago64** [comment]
Buenas buenas!

Las vms van a estar configuradas dentro de una VPC con lo cual las condiciones deberian ser lo mas similares a lo que pasa en el labo de medrano que puede caerles algo pero nada del otro mundo que con un handshake de 3 msjs no se resuelva.

Saludos.-

**Comment by benjamd** [comment]
OK, Gracias!!

**Comment by mgarciaisaia** [comment]
¡Aloha!

Vengo a aclarar un poco más.

A cada grupo le vamos a dar 4 VMs que están configuradas en una VPC propia. Eso significa que las 4 máquinas van a compartir una "red local" virtual - como si estuvieran las 4 máquinas conectadas al mismo router en una casa.

**Pero** además cada máquina va a tener una IP pública, que es a través de la cual ustedes van a poder conectarse a las mismas. Y donde se conecta un@, nos conectamos todos. Es decir, _dependiendo de cómo esté configurado su socket servidor_, puede que igual acepten conexiones externas (como en el caso de ngrok, digamos). Por eso la mención de Dami es importante: hagan un handshake, porque nunca se sabe quién está del otro lado.

¡Saludos!
