### ISSUE TITLE
ayuda ayuda con ack no me funciona multithreading

### ISSUE THREAD

**Issue by benjamd** [sisoputnfrba/foro#1850]
Multihilos, Secuencialidad y ACKs

Hola, a partir del comentario que me respondieron en https://github.com/sisoputnfrba/foro/issues/1836#issuecomment-658919533 modificamos Gameboy, Gamecard y los otros procesos para que envían ACK a Gameboy en respuesta al mensaje recibido. 
Nuestro proceso Gamecard tiene un hilo por cada cola a la que se suscribe (a Broker) y otro de servidor multihilos, abriendo un hilo de conexión por cada accept().
Si bien un script en si es una ejecución secuencial de comandos ahora Gameboy se queda esperando con un recv() hasta recibir ACK de Gamecard (después hace un close() y finaliza el proceso). Por su parte Gamecard que  recibió el mensaje, hace la operación  correspondiente (new/catch/get) y durante esta operación aplica el tiempo de retardo para simular la E/S. Una vez finalizada la operación Gamecard Responde ACK del mensaje a Gameboy. Cuando Gameboy recibe ACK cierra la conexión y finaliza, para dar lugar a la ejecución de la siguiente linea del script.

1. Antes del cambio Gameboy finalizaba sin esperar un ACK e inmediatamente se ejecutaba otra instancia que enviaba un nuevo mensaje, generando condiciones de carrera y compitiendo por varios recursos (más si son el mismo Pokemon) que resolvímos con sincro de semáforos (una lista global con un semáforo para cada Pokemon del FS). Ahora no va a pasar nunca que se encuentre abierto el archivo, salvo en el caso que llegue un mensaje por cola subscripta desde Broker a la vez que llega otro mensaje de Gameboy para le mismo Pokemon. 
Es este el comportamiento esperado?

2. Esta bien responder el ACK luego de la operación (new/catch/get) o debería ser antes?

Siento que este issue se resume en mejor con el meme del perro musculoso y el que llora "ayuda ayuda con ack no me funciona multithreading"  

Saludos!

**Comment by iago64** [comment]
Buenas!

De cara a una prueba simple es posible que no tengas el tan ansiado multithreading, ahora bien, que va a pasar cuando por ejemplo tengas 2 teams y el broker y mientras tanto les tiremos mensajes desde gameboys? Ahí como va a responder? 49.780as a tener el multithreding?

Que el árbol no te tape el bosque, una prueba especifica te limite el multithreading porque te llegan peticiones especificas es una cosa esperada, la gracia viene cuando se de rienda suelta al esquema completo y le tiren con de todo al gamecard 😉 

Saludos.-

**Comment by benjamd** [comment]
Entendido, gracias!!

Saludos!
