### ISSUE TITLE
Duda como planificar Deadlocks en Team

### ISSUE THREAD

**Issue by AnelloJM** [sisoputnfrba/foro#1851]
Hola! tengo una duda en el modulo Team como manejamos los deadlocks
Básicamente mi duda es la siguiente: Yo al detectar los entrenadores en deadlock, ¿tengo que seguir respetando el algoritmo de planificación? es decir, si mi algoritmo es por ejemplo round robin podria darse que tenga 2 entrenadores moviéndose al mismo tiempo en el mapa. Lo tengo que resolver siguiendo el algoritmo o se resuelven homogéneamente en todos los algoritmos

Desde ya muchas gracias

**Comment by iago64** [comment]
Buenas!

Si, el algoritmo deberías respetarlo, lo que tiene es que como vas a mover de a un entrenador, simplemente va a contar para las estadísticas porque solo uno va a pasar de ready a exec (y volver a ready virtualmente en el caso de RR)

Saludos.-

**Comment by AnelloJM** [comment]
Perfecto así lo tenia hecho pero nos surgió la duda a ultimo momento, muchas gracias!
