### ISSUE TITLE
Appeared de scripts incompletos

### ISSUE THREAD

**Issue by MariKevorkyan** [sisoputnfrba/foro#1853]
Buenas noches, 
Estuvimos probando los scripts, pero los que tienen el mensaje appeared están incompletos ya que les falta el id mensaje correlativo. Eso asi como esta no haría nada, por lo que nosotros para probarlo les agregamos un id, debe ser así para mañana o nos los dicen ustedes?

**Comment by iago64** [comment]
Buenas!

La misma duda se respondió en el issue #1844 😄 

Saludos.-

**Comment by MariKevorkyan** [comment]
Disculpasss, no lo vi! Graciaas!
