### ISSUE TITLE
[TEAM] Posible error en prueba inicial

### ISSUE THREAD

**Issue by FedeMacias** [sisoputnfrba/foro#1854]
Buenas, una consulta

En la prueba inicial de team dice:
El entrenador A se mueve a atrapar a Pikachu en posición 1-1.
El entrenador C se mueve a atrapar a Squirtle en posición 9-7.
El entrenador B se mueve a atrapar a Onix en posición 2-2.
El entrenador B se mueve a atrapar a Squirtle en posición 3-5.
El entrenador C se mueve a atrapar a Gengar en posición 7-5.

En las pruebas no tiene sentido, porque el orden de ejecucion al usar FIFO, deberia ser:
A->C->B->C->B

Hay algo que no estoy considerando o hay un error en el script???
En mi caso el entrenador C se mueve a atrapar al squirtle y el entrenador B a gengar, lo cual segun el test está mal, pero es la forma correcta en la que deberia correr el FIFO.

Pero repito, segun la logica de FIFO no tiene sentido que el orden sea A C B B C

**Comment by iago64** [comment]
@FedeMacias Como va?

Esas pruebas ya están fuera de soporte, tenemos el doc con las [pruebas finales](https://docs.google.com/document/d/1_MHl52R-wPyL4SaWYok4Crf47dVwlqZOQn1MWouo3T8) por las dudas, basate en este doc.

Saludos.-

**Comment by FedeMacias** [comment]
Okay, gracias!
