### ISSUE TITLE
Duda sobre la última fecha de entrega

### ISSUE THREAD

**Issue by RaniAgus** [sisoputnfrba/foro#1855]
Buenas! En nuestro grupo hay preocupación por un anuncio que hizo Franja Morada ayer sobre las inscripciones para el próximo cuatrimestre: resulta que la fecha de cierre coincide con la última entrega del TP. 

![Screenshot_1595292247226.jpg](https://user-images.githubusercontent.com/39303639/88000066-1bb55400-cad3-11ea-9179-5b4ea3ee4e67.jpg)

![Screenshot_1595292370388.jpg](https://user-images.githubusercontent.com/39303639/88000076-2374f880-cad3-11ea-9731-23456425765a.jpg)

Por lo tanto, no sabríamos si inscribirnos a la materia para el próximo cuatrimestre, y tampoco podríamos anotarnos a las correlativas en caso de aprobar.

Quisiéramos saber si se puede adelantar un día la entrega para tener tiempo de tomar la determinación correcta. Saludos!

**Comment by afilgueira** [comment]
Hola, nos es imposible tomar la entrega completa un viernes (tenemos gente que rinde otras materias, gente trabajando, y cuando digo gente hablo de alumn@s y docentes). La opción más cercana es que se inscriban a la entrega del sábado, en el primer horario disponible (9 am).

En líneas generales esto mismo pasa todos los años y la opción que suelo recomendar es que se pre-inscriban a todo lo que tienen certeza y se inscriban "presencialmente" (esta vez virtual) después a lo que no. Entiendo que la inscripción cierra el 14, pero déjenme chequearlo y confirmarles.

![image](https://user-images.githubusercontent.com/1786754/88004187-e6156880-cadc-11ea-8938-2e9a26f8046e.png)

Saludos!

**Comment by RaniAgus** [comment]
Entiendo, haremos eso entonces. Gracias!

**Comment by afilgueira** [comment]
Buenas, me confirmaron _recién_ que es así. Saludos!
