### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by aitorulz1** [sisoputnfrba/foro#1856]
👋 ¡Hola!

Tengo un repositorio 'Toysland' y otro 'Toysland api'. Uno es el back y otro el front. El caso es que lo he intentado subir a Heroku y me sube la parte del front, pero no la parte de la base de datos.No sé si tengo bien configurados los .env.

Conocéis a alguien que pueda echarme una mano con esto?

**Comment by karengrams** [comment]
¡Buenas!

¿Como va? Creeeeo que te equivocaste de github, cierro el issue. Espero que lo puedas solucionar :)

¡Saludos!

**Comment by mesaglio** [comment]
@aitorulz1 como dijo @karengrams no es el repo correcto para postear.
Peeeeeeeero creo que te puedo dar una mano `juan.mesaglio@gmail.com`
