### ISSUE TITLE
[Team] Duda con formula SJF

### ISSUE THREAD

**Issue by enogueiras** [sisoputnfrba/foro#1857]
Buenas noches, estamos teniendo dudas con el parámetro de **Real Ant**. que vemos en los ejercicios, para hacer la implementacion en el TP (un ejercicio de ejemplo):

![image](https://user-images.githubusercontent.com/11813141/88132898-0d406880-cbb7-11ea-9c0b-a694a00fe7ce.png)

![image](https://user-images.githubusercontent.com/11813141/88133104-a8394280-cbb7-11ea-9aca-ce7530dfdce4.png)

Según entendemos los valores de Alfa y Est. Ant. los tenemos por archivo de configuración, pero nos faltaría ese valor para arrancar y poder calcular la estimacion inicial.

Muchas gracias.
Saludos,

Emilo.

**Comment by ncoen97** [comment]
Buenas, el valor que reciben por archivo de configuración no es la estimación anterior, es la estimación inicial "ya calculada". Con ese valor y el cpu real, van a poder sacar la siguiente estimación.
Suerte!

**Comment by enogueiras** [comment]
@ncoen97 muchas gracias!
