### ISSUE TITLE
[BROKER] Segmentation fault al reenviar un mensaje

### ISSUE THREAD

**Issue by MatiMon** [sisoputnfrba/foro#1858]
Buenas!
Hace varios días estoy con un segmentation fault que a pesar de darle mil vueltas no puedo resolver.
La cuestión es:
Levanto Broker y le envio un New Pokemon que es guardado en memoria.
Levanto Game Card y solicita suscribirse a la cola New.
Desde Broker obtengo la lista de mensajes New (en este momento habrá 1 solo) e intento reenviarselo y acá empieza el problema.
Tenemos una función "enviar_new_pokemon" que recibe los parámetros como char *, genera las estructuras, le pasa todo a una función de serialización específica y lo envía. 
El problema es que en la serialización, al intentar hacer un memcopy del nombre del pokemon tira un segmentation fault de una posición de memoria que es anterior a las que estoy manejando en ese momento (la posición de memoria es siempre la misma: 0x77610, no se cuán relevante es esto pero me resultó raro).

No se bien cómo reportar este error ya que todo compila y de hecho la función de envío de mensajes funciona (al menos desde Game-Boy a Broker). Pero paso a mostrarles algo del código:

Funcion de envio:
`
void enviar_new_pokemon(char* pokemon, char* x, char* y, char* cantidad, char* id_mensaje, int32_t socket_cliente)
{
	t_paquete * paquete = malloc(sizeof(t_paquete));
	paquete->codigo_operacion = NEW_POKEMON;
	paquete->buffer = malloc(sizeof(t_buffer));

	t_posicion  posicion;
	posicion.X = (int32_t) atoi (x);
	posicion.Y = (int32_t) atoi (y);

	t_pokemon p_pokemon;
	p_pokemon.size_Nombre = string_length(pokemon) +1;
	p_pokemon.nombre = pokemon;

	t_New new;
	new.cant = (int32_t) atoi (cantidad);
	new.posicion = posicion;
	new.pokemon = p_pokemon;

	paquete->buffer->size = tamanio_new (&new);
	paquete->buffer->id_Mensaje = (double) atoi (id_mensaje);
	paquete->buffer->stream = &new;

	int32_t bytes_a_enviar;
	void *paqueteSerializado = serializar_paquete_new (paquete, &bytes_a_enviar, &new);

	send(socket_cliente, paqueteSerializado, bytes_a_enviar, 0);

	free(paqueteSerializado);
	free(paquete->buffer);
	free(paquete);
`

Serializacion:
`void* serializar_paquete_new (t_paquete* paquete, int32_t* bytes, t_New* new){

	*bytes = sizeof(paquete->codigo_operacion) + sizeof(paquete->buffer->size) + sizeof(paquete->buffer->id_Mensaje) + paquete->buffer->size;
	void *stream = malloc(*bytes);
	int32_t desplazamiento = 0;

	memcpy(stream, &(paquete->codigo_operacion), sizeof(paquete->codigo_operacion));
	desplazamiento+= sizeof(paquete->codigo_operacion);

	memcpy(stream + desplazamiento, &(paquete->buffer->size), sizeof(paquete->buffer->size));
	desplazamiento+= sizeof(paquete->buffer->size);
	memcpy(stream + desplazamiento, &(paquete->buffer->id_Mensaje), sizeof(paquete->buffer->id_Mensaje));
	desplazamiento+= sizeof(paquete->buffer->id_Mensaje);

	memcpy(stream + desplazamiento, &(new->pokemon.size_Nombre), sizeof(new->pokemon.size_Nombre));
	desplazamiento+= sizeof(new->pokemon.size_Nombre);
	memcpy(stream + desplazamiento, new->pokemon.nombre, new->pokemon.size_Nombre);
	desplazamiento+= new->pokemon.size_Nombre;
	memcpy(stream + desplazamiento, &(new->posicion.X), sizeof(new->posicion.X));
	desplazamiento+= sizeof(new->posicion.X);
	memcpy(stream + desplazamiento, &(new->posicion.Y), sizeof(new->posicion.Y));
	desplazamiento+= sizeof(new->posicion.Y);
	memcpy(stream + desplazamiento, &(new->cant), sizeof(new->cant));

	return stream;`

**Comment by iago64** [comment]
Buenas!

Como no se si cerraste el issue por error o por solucion, paso a comentarte que para reportar estos errores es siempre recomendable que nos pases una captura de lo que te devuelve Valgrind como para tener una idea de que es lo que pasa :)

Saludos.-

**Comment by MatiMon** [comment]
> Buenas!
> 
> Como no se si cerraste el issue por error o por solucion, paso a comentarte que para reportar estos errores es siempre recomendable que nos pases una captura de lo que te devuelve Valgrind como para tener una idea de que es lo que pasa :)
> 
> Saludos.-

Estaba escribiendo el issue, se me escapó un enter y sin querer lo subí. Lo cerré para terminar de escribirlo!

**Comment by iago64** [comment]
Buenisimo, fijate que ahi te dice que le estas apuntando a algo que lo liberaste previamente o que nunca le hiciste malloc().

Fijate que vos estas usando sizeof() por todos lados y a veces esos sizeof() si por ejemplo es de algo que tenes un puntero, lo que te devuelve es el tamaño del puntero y no del objeto, con lo cual, capaaaz que la idea del size lo tengas que repensar de alguna forma que te permita saber exactamente que esas mandando.

Saludos.-

**Comment by MatiMon** [comment]
Lo que me desconcierta es que si debugeo, la posición de memoria que estoy queriendo copiar es otra.
![image](https://user-images.githubusercontent.com/22034313/88209555-40bbdb00-cc29-11ea-905e-c7c500087f12.png)

**Comment by MatiMon** [comment]
Teníamos un double dentro de las estructuras que enviabamos que estaba generando el problema.
Lo cambiamos a int32_t y problem solved.

Cierro issue!
