### ISSUE TITLE
[BROKER] Broker se cuelga a los 377 mensajes exactactos

### ISSUE THREAD

**Issue by floppylive** [sisoputnfrba/foro#1859]
Buenas, estamos con un problema en el broker. Probamos estresarlo y por alguna razón sólo es capaz de enviar y recibir un total de 377 mensajes. Al llegar a esa cantidad de frizzea el programa. Sin arrojar ningún error o algo por el estilo. Probamos con valgrind y no hay errores, no tenemos memory leaks y con helgrind no encontramos nada.
No sabemos cómo solucionarlo o si esto supone un problema.

Desde ya muchas gracias!

**Comment by Nico-0** [comment]
Hola, tuve el mismo problema, lo solucione agregando pthread_detach a todos los hilos.
Despues se me colgaba a los 1000 mensajes, y lo solucione agregando close() a todos los socket que se dejaban de usar.
Estuve con eso mas de dos semanas jaja

**Comment by floppylive** [comment]
> Hola, tuve el mismo problema, lo solucione agregando pthread_detach a todos los hilos.
> Despues se me colgaba a los 1000 mensajes, y lo solucione agregando close() a todos los socket que se dejaban de usar.
> Estuve con eso mas de dos semanas jaja

Sos un genio!!!!!!!!!!!! Graciaas!
