### ISSUE TITLE
[TEAM] Resultados test SJF

### ISSUE THREAD

**Issue by FedeMacias** [sisoputnfrba/foro#1861]
Buenas,

Estamos teniendo una duda con los resultados que nos da SJF sin desalojo
El documento dice tiene que dar "similar" a FIFO pero con metricas distintas.

FIFO ejecuta asi:
A -> pikachu
C -> squirtle
B -> onix
A -> gengar
C -> squirtle
Esto genera un deadlock doble entre A y C

En el caso de SJF sin desalojo nos da asi:
A -> pikachu
C -> squirtle
B -> onix
C -> gengar
A -> squirtle
Esto genera un deadlock triple entre A B y C
Revisamos las estimaciones y esto tiene sentido que ocurra.

La pregunta es, esto está bien? deberia generar el mismo deadlock que en FIFO o no?? 
El concepto de "similar" en este caso nos confunde un poco.

Saludos!

**Comment by iago64** [comment]
Buenas!

El concepto de similar es que van a tener maaas o menos los mismos cambios de contexto y van a tardar bastante parecido en cuanto a rafagas de CPU. 
La idea mas que nada es para que si les da algo muy diferente (por ej que no tienen deadlocks) es porque algo raro hicieron en la planificación de SJF.

Saludos.-

**Comment by FedeMacias** [comment]
Hay un cambio en el orden que atrapan un pokemon nomas, las metricas dan masomenos parecidas, no se si deberia preocuparme o no

**Comment by iago64** [comment]
Para nada, por eso les dijimos parecidos y no iguales 😉

**Comment by FedeMacias** [comment]
Ah genial, ahora puedo dormir mas tranquilo, voy cerrando, muchas gracias!!
