### ISSUE TITLE
[Broker] Dump de la caché

### ISSUE THREAD

**Issue by RaniAgus** [sisoputnfrba/foro#1862]
Citando rápido el texto sobre el dump de la caché:

> Será requerimiento del motor de administración de memoria que éste pueda **depositar en un archivo** el estado actual de la memoria en la caché según el esquema seleccionado. Para solicitar dicho dump, se enviará una señal SIGUSR1 que deberá ser manejada e inicializada.
> No se pretende ver el contenido de la información almacenada, sino las particiones asignadas/libres, indicando su dirección de comienzo y fin, su tamaño en bytes, **tiempos de LRU**, el tipo de cola de mensajes que pertenece y su identificador.

Ya implementamos los signals y funcionan bárbaro, (de hecho, hice un script para que busque solo el pid y envie el kill), pero tengo 2 dudas muy cortitas en cuanto al archivo que se genera:

1. ¿De qué forma se tiene que guardar? Pensé 3 opciones: 
    a. Por cada señal se sobreescribe un único archivo "dump.txt".
    b. Por cada señal se recorre hasta el final de ese archivo "dump.txt" y se escribe desde ahí (como en los logs).
    c. Por cada señal se crea un nuevo archivo ("dump1.txt", "dump2.txt", ...), contando desde que arrancó el broker.

2. Si está configurado el reemplazo FIFO, ¿hay que escribir los tiempos de LRU?

Perdón si ya se dijo en algún otro issue, estuve buscando y casi todo lo que encontré eran preguntas sobre cómo manejar las señales.

**Comment by ncoen97** [comment]
Buenas.
1. La b me parece la mas correcta.
2. Si lo implementaron con un timestamp pueden ponerlo, caso contrario no lo pongan.
Saludos!

**Comment by RaniAgus** [comment]
Genial, gracias!
