### ISSUE TITLE
Problema con la VM. "Failed to start iSCSI"

### ISSUE THREAD

**Issue by Nachiten** [sisoputnfrba/foro#1863]
Básicamente publico esto para saber si alguien tendrá alguna idea de que puede ser que me haya pasado.

Anoche cerré la VM sin apagarla a la fuerza ni hacerle nada raro y es la cuarta vez en este cuatrimestre aprox ya que la VM de la nada se rompe solita y no me deja bootear.

Dejo un screenshot de lo que me salta:

![image](https://user-images.githubusercontent.com/39410888/88457861-1d2ea580-ce60-11ea-91e4-11269bef2b7b.png)

**Comment by mgarciaisaia** [comment]
Che, qué cagada esto =/

¿Te pasa en la server o en la Lubuntu?

¿Probaste de correr ese `journalctl -xb` a ver qué dice? Igual imagino que serán chorros y chorros de mensajes de log que no te van a aportar mucho.

No se me ocurre cómo debuggear esto, la verdad. O siquiera si vale la pena ponerse a pelear con eso _a esta altura del cuatrimestre_.

**Comment by Nachiten** [comment]
> Che, qué cagada esto =/
> 
> ¿Te pasa en la server o en la Lubuntu?
> 
> ¿Probaste de correr ese `journalctl -xb` a ver qué dice? Igual imagino que serán chorros y chorros de mensajes de log que no te van a aportar mucho.
> 
> No se me ocurre cómo debuggear esto, la verdad. O siquiera si vale la pena ponerse a pelear con eso _a esta altura del cuatrimestre_.

Es la VM de lubuntu.

La realidad es que la reinstalé directamente y fue mucho mas facil que quemarme con eso. 

Pero ya como me pasó varias veces no se si habré hecho algo yo o solo se rompe sola.

Si queres cierro total ya lo solucioné de la manera mas facil.
