### ISSUE TITLE
[Pruebas Finales] Finalización de team1 y 2

### ISSUE THREAD

**Issue by dariokozicki** [sisoputnfrba/foro#1864]
Buenas!

Estamos revisando las pruebas finales para la próxima entrega, y algo que nos llamó es que la memoria de broker es muy pequeña (64b) para la cantidad de mensajes que se van enviando. Además al levantar team1, éste enviaría más mensajes generando que se eliminen algunos anteriores, y éstos no llegarían a team2.

Tienen que poder finalizar sí o sí ambos Teams? Cómo tendría que ir quedando la memoria de broker?

Gracias!

**Comment by tomasCasa** [comment]
Yo me sumo a la consulta, pero a nosotros nos pasa desde la primer prueba de new_pokemon_antes_team. Porque los primeros 2 mensajes de NEW se guardan pero cuando llega el 3ro y 4to, eliminan estos 2 primeros. Y como resultado al Gamecard solo le llegan estos 2 ultimos. Ademas, cuando Gamecard responde a estos NEW con un APPEARED, elimina a los NEW(con esto no habría problema porque son mensajes que solo el Gamecard necesita, y ya los esta contestando), pero basicamente al Team le llegarian solo 2 APPEARED de los ultimos 2 NEW.

Para agregar la shell de new_pokemon_post_team tiene 6 mensajes de NEW, entonces devuelta solo se usaran los ultimos 2 de esa shell.

Saludos!

**Comment by papa-caco** [comment]
Hola muchachos buenas tardes,

A nosotros hasta hace un rato nos había surgido la misma duda, ayer la prueba final no nos pasaba si seteábamos la memoria del BROKER en 64 bytes porque no le alcanzaba para cachear los mensajes APPEARED para los dos TEAM, ni siquiera para uno solo. (quedaba el APPEARED Squirtle 5 2, y al APPEARED Pikachu lo elimina en el reemplazo).  Probamos seteando al BROKER con 128 bytes y así Sí funcionaba porque le alcanzaba para mantener en caché a todos los mensajes APPEARED que precisaban  los dos TEAM para iniciar.

Pero finalmente le encontramos la vuelta y la **clave** está en que tienen que _iniciar las suscripciones_ **antes** de _enviar los mensajes GET_POKEMON_ que se envían al iniciar el TEAM, uno por cada clase de Pokemon del objetivo global. De esta forma los Pokemones que no reciben por los mensajes APPEARED los reciben desde los mensajes LOCALIZED.
Denle una vuelta más de rosca que tiene que salir!!

Saludos y éxitos!

**Comment by iago64** [comment]
Buenas!

Como dice @papa-caco la gracia de la prueba final es que con poca memoria (realmente muy poca) uds resuelven el problema y es que ademas la mitad de los pokemones ya existen en el FS al momento de que inician los teams, entonces tienen la info de los primeros porque reciben los LOCALIZED y despues el resto si se enteran por APPEARED 😉 

Saludos.-

**Comment by dariokozicki** [comment]
Buenas!

Estamos tratando de ver cómo encararlo,
Habría que garantizar enviar un mensaje antes de borrarlo? (p. ej usar semáforos para no ingresar más mensajes hasta que no se envíen)

Saludos!

**Comment by iago64** [comment]
Buenas!

Mínimo un poco de sincro deberían tener ya que uds reciben algo, lo guardan y lo reenvían a los suscriptores, en ese lapso al menos no deberían estar 2 hilos modificando las mismas estructuras.

Saludos.-
