### ISSUE TITLE
[Pruebas BROKER]

### ISSUE THREAD

**Issue by cristianicolasuarez** [sisoputnfrba/foro#1865]
Buenas!

Estamos con el equipo realizando las pruebas de Broker, y en la prueba de "Consolidación - Particiones Dinámicas" encontramos algo que nos hace algo de ruido.

Se enuncia en el paso 5:
Al ejecutar la suscripción se actualizan los tiempos de LRU de los primeros dos mensajes por lo que se deben borrar los dos siguientes (3-4) (Catch Pikachu y Catch Squirtle), guardándose posteriormente el nuevo mensaje en la posición 8.

Pero los 2 primeros mensajes son CAUGHT -> cuando el suscriptor recibe dichos mensajes estos son eliminados, porque son enviados a todos los suscriptores de dicha cola. Entonces nos sucede que el el nuevo mensaje se guarda en la posición 0-21. En vez de la posición 8.

De todas maneras los mensajes Catch Pikachu y Catch Squirtle son eliminados.

Nos basamos en esto, por el apartado del enunciado del Broker, que dice: "Durabilidad: Todo mensaje debe permanecer en la cola de mensajes hasta que todos los Suscribers lo reciban."

**Comment by cristianicolasuarez** [comment]
PD: Nos sucede esto con todas las pruebas. Tratamos a la suscripción de gameboy como el único suscriptor de la cola. Por ende cuando le enviamos los mensajes los eliminamos. Nuestros resultados difieren del documento de pruebas solo por esto, si esto no sucediera correrían bien. Podemos solucionarlo distinguiendo un suscriptor gameboy del resto de suscriptores, pero queremos estar seguros de que esto sea lo correcto. Saludos y gracias de antemano.

**Comment by iago64** [comment]
Buenas!

Ojo, no deberían eliminar los mensajes de la cache, por eso les difiere con los resultados esperados. Solo eliminan un mensaje de la cache al momento de que tienen que elegir una victima para el reemplazo porque la memoria esta llena.

Saludos.-

**Comment by cristianicolasuarez** [comment]
Entiendo, entonces ese apartado de la durabilidad hay que tenerlo en cuenta a la hora de elegir victima?
