### ISSUE TITLE
Gamecard = Uso del cpu para un caso especial 

### ISSUE THREAD

**Issue by leobz** [sisoputnfrba/foro#1866]
Estaba viendo este [issue](https://github.com/sisoputnfrba/foro/issues/1716) (manejar archivos abiertos con semaforos o metadata), y la solución mas sencilla es no usar mutex para los archivos abiertos, sino comprobar mediante el metadata del mismo.

El problema que surge con la siguiente configuración seria que existiría una espera activa, en la cual mientras no este abierto el archivo (ya que dura 10 segundos el uso del mismo), se pregunta constantemente si lo sigue estando
```
TIEMPO_DE_REINTENTO_OPERACION=0
TIEMPO_RETARDO_OPERACION=10
```

Se que es un caso muy particular, no se si lo tomarán, pero se me complicaría bastante manejar eso ahora.

**Comment by ncoen97** [comment]
Buenas.
Te recomiendo leer [este issue](#1771 ) y cualquier duda que te quede nos consultas nuevamente.
Saludos!

**Comment by enogueiras** [comment]
> Buenas.
> Te recomiendo leer [este issue](#1771) y cualquier duda que te quede nos consultas nuevamente.
> Saludos!

Hola Nico, no direcciona.

**Comment by RodrigoLista** [comment]
> > Buenas.
> > Te recomiendo leer [este issue](#1771) y cualquier duda que te quede nos consultas nuevamente.
> > Saludos!
> 
> Hola Nico, no direcciona.

Si no me equivoco, hizo referencia al Issue #1771.

**Comment by gebonora** [comment]
Buenas aprovecho este issue para preguntar:

Es esperable como un valor correcto de config un tiempo de reintento igual a 0? 

Por lo que entiendo el TP pide consultar si el archivo está abierto (acá en el issue mencionado arriba se discute bien este asunto), y si no está abierto hay que logear y reintentar la operación cada X segundos determinado por config. Ahora si permito poner un 0 desde config, estoy forzando al programa a intentar continuamente el acceso al archivo, lo que me lleva a una espera activa de la que no veo forma de zafar manteniendo el reintento de operación.

Gracias.

**Comment by iago64** [comment]
Buenas!

Podríamos ponerle un 0 en el tiempo de reintento, pero en ese caso no habría problema con una espera activa, ya que es algo que se haría a propósito, el caso es cuando por ejemplo hay un tiempo por ejemplo de 10 segundos.

Saludos.-

**Comment by leobz** [comment]
Muchas gracias!!!
