### ISSUE TITLE
[TEAM] Pasaje entre colas Ready y Blocked

### ISSUE THREAD

**Issue by agusboster** [sisoputnfrba/foro#1867]
Buenas!

En otro issue (el #1666 ) vimos y entendimos que de cola Blocked a Ready se pasan los entrenadores según cuál es el que menos tiene que moverse, y que luego en la cola de Ready se ordena según algoritmo de planificación. 
Nuestra duda surge sobre en qué momento deberíamos pasar los entrenadores de blockeado a ready. Nosotros de entrada tenemos a todos en blocked, y tenemos pensado pasar a todos a ready ordenados por cercanía. En la medida que ejecuta cada entrenador se lo pasa a blocked por defecto. Luego pensamos tres opciones:

- 1. Esperamos a que Ready se vacíe para volver a cargar desde Blocked? 
- 2. Apenas termina de ejecutar, lo pasamos a blocked, y debemos ya verificar si puede pasar a ready y lo pasamos de una? 
- 3. Esperamos a que hayan al menos dos en blocked (que puedan ejecutar) y entre ellos verificar la cercanía para pasarlo a ready?

Espero se haya entendido la consulta, aguardamos su respuesta. Muchas gracias!

**Comment by ncoen97** [comment]
Buenas.
La opción correcta es la ii. La idea es que siempre que puedan pasar un entrenador de new/block a ready lo hagan (comparando por distancia).
Saludos!

**Comment by agusboster** [comment]
Ok buenisimo! Entonces para asegurarme que entendí: cuando un entrenador termina de ejecutar pasa a blocked, y si quiere moverse, hay pokemones y no hay nadie mas en blocked porque el resto sigue en ready, lo paso a ready de una sin comparar con ningun entrenador por distancia?

**Comment by ncoen97** [comment]
En realidad sería: "cuando un entrenador termina de ejecutar pasa a blocked, y si quiere moverse, hay pokemones y no hay nadie mas en blocked **-ni en new-** porque el resto sigue en ready, lo paso a ready de una sin comparar con ningun entrenador por distancia".
Saludos!

**Comment by agusboster** [comment]
Quedó clarísimo. Muchas gracias!
Saludos.
