### ISSUE TITLE
Bug in libpthread: sem_wait succeeded on semaphore without sem_post

### ISSUE THREAD

**Issue by maurodgiraldez** [sisoputnfrba/foro#1868]
Hola,
el día Sábado hicimos la entrega de nuestro TP, luego de hacer todas las pruebas satisfactorias en nuestros equipos. Durante la entrega, las pruebas integrales fueron correctas, pero tuvimos fallas en las unitarias, particularmente en las del gamecard.

Luego de eso, continuamos probando y notamos que a nosotros en Lubuntu funcionaba correctamente siempre, y en Ubuntu Server a veces si y a veces no. Pensamos que era un tema de condición de carrera, por lo que revisamos y agregamos semáforos en múltiples lugares, pero al correrlo con helgrind, notamos que un "warning" aparecía a veces:

"Bug in libpthread: sem_wait succeeded on semaphore without prior sem_post"

![image](https://user-images.githubusercontent.com/8745618/88751006-18eadc80-d12d-11ea-9fd7-6ce6463eaad8.png)

Buscamos pero encontramos posts de hasta 12 años atrás donde la gente reporta este tema, pero no llegamos a entender que significa ni como solucionarlo. Nos podrán dar una mano? No llegamos a entender si tenemos algo mal y donde, o si es un tema de la librería.

**Comment by maurodgiraldez** [comment]
Agrego que de todas las veces que lo estamos probando en el server, 60% de las veces aproximadamente falla. En cambio, cuando lo corremos con valgrind no falla casi nunca (nos costó bastante reproducir el error).

**Comment by maurodgiraldez** [comment]
Ya lo solucionamos, en un sem_wait, en vez de pasarle un puntero a un semaforo, le estabamos pasando la dirección de memoria del puntero a un semaforo. Lo que nos confundió fue que el mensaje de Valgrind daba a entender que era un problema de la librería.

Cierro.

**Comment by mgarciaisaia** [comment]
Uff.. Suerte que lo encontraron, che. Iba a estar complicado de debuggear.

Gracias por compartir la solución :)
