### ISSUE TITLE
Team - Duda sobre los cambios de contexto 

### ISSUE THREAD

**Issue by GastonGonzalezS** [sisoputnfrba/foro#1869]
Buenas estoy viendo el tema de métricas en el proceso Team, específicamente la parte de llevar la cuenta de los cambios de contexto y pese a ver los issues que hay sobre el tema me quedan las siguientes dudas: 

1) En el caso de desalojar un entrenador y meter a otro a exec esto contaría como 1 cambio de contexto o 2 (uno por el desalojo del entrenador anterior y uno por el paso a exec del nuevo entrenador) ? 

2) En el caso de SJF-CD, si esta ejecutando un entrenador  y se luego de completar, por ejemplo, una ráfaga de cpu se frena su ejecución para chequear cual es el entrenador que posee la próxima ráfaga mas corta y se determina que tiene que seguir el mismo en ejecución, esto contaría como un cambio de contexto o mientras se mantenga el mismo no habría que contabilizarlo?

Saludos

**Comment by afilgueira** [comment]
Buenas! 

1- es uno, porque acá no interviene el SO para manejar el cambio, sino que es directo.
2- está buena la pregunta. Siguiéndo la mísma lógica, te diría que no tenés ninguno, porque el chequeo se hace en otro lado (en un SO de verdad, sería en otra CPU por ej).

De todas formas, al margen de los números, es importante la justificación de porqué cada cosa en la entrega/coloquio.

Saludos!

**Comment by GastonGonzalezS** [comment]
Buenísimo, que claro, muchas gracias
