### ISSUE TITLE
Pruebas: Cambiar el path del gameboy en los scripts de la cátedra

### ISSUE THREAD

**Issue by leobz** [sisoputnfrba/foro#1871]
Hola! Tenemos una carpeta llamada "test-de-integracion" en la cual automatizamos todos los tests con scripts (levantan los módulos y ejecutan las consultas del gameboy.), y **corremos los scripts desde esta misma carpeta**

El tema es que al ejecutar los scripts de la catedra en vez de correr las consultas del gameboy de esta manera:  
buddy_basico.sh
```
../gameboy BROKER CAUGHT_POKEMON 1 OK
```

Las corremos de esta manera (es decir, tenemos que **modificar el path que vienen en el repo** de la catedra):  
buddy_basico.sh (path modificado)
```
../gameboy/Debug/gameboy BROKER CAUGHT_POKEMON 1 OK
```

Este es el arbol del tp
```
/root_tp
    /test-de-integracion
           /delibird-pruebas
                  buddy_basico.sh
                  ...
    /gameboy
            /Debug
                   /gameboy (ejecutable)
    /otros-modulos
```

¿Podemos usar el path modificado que tenemos para el día de la entrega? Sino, cambio los scripts. Desde ya muchas gracias

**Comment by iago64** [comment]
Aloha!

Si, no hay drama, la otra que pueden hacer es copiarse los scripts a la carpeta donde tienen el ejecutable del gameboy para evitarse el replace en todos los scripts 😉 

Saludos.-

**Comment by leobz** [comment]
Gracias!
