### ISSUE TITLE
Log en pantalla

### ISSUE THREAD

**Issue by brianUtn98** [sisoputnfrba/foro#1872]
Hola! Estuve mirando Issues y no encontré exactamente esta duda, así que abro otro.
Mi duda es simple, a la hora de loguear las cosas obligatorias que están en el enunciado, particularmente en el team que tiene bastante información que loguear, estaba viendo una forma de discriminar las cosas que muestro por pantalla y las cosas que solo irán por log. Se me ocurrieron un par de opciones y quisera saber cual es la correcta.

1. Tener dos t_log * que apunten al mismo archivo .log, uno tenga el log_create(...,...,0,...) para que no loguee en pantalla, y otro log_create(...,...,1,...) para que sí. Y los voy alternando mientras los voy necesitando.
2. Usar el mínimo nivel de detalle en LOG_LEVEL_INFO, por ejemplo, y  loguear lo que quiero por pantalla con log_info y lo que no con log_trace.
3. Ambas están bien.
4. Ninguna de las anteriores.

La duda me surgió más que nada al leer el #1841 , ya que dice que los logs importantes como el resultado del team, se querría ver claro en pantalla, pero lo demás se puede revisar en el archivo log.

Aprovecho para otra dudita.
Se espera que usemos cierto LOG_LEVEL para loguear, o es indistinto y podemos usarlo a nuestro gusto? Por ejemplo:  Las fallas al conectarse con el broker con log_error y los reintentos con log_debug? 

Desde ya gracias por leerme.

**Comment by iago64** [comment]
Buenas!

En pantalla no deberías tener logs directamente, todo debería ir a un archivo de log y lo consultas con tail -f del archivo de log.

Saludos.-

**Comment by brianUtn98** [comment]
Gracias @iago64 . Cierro!
