### ISSUE TITLE
Problema Sockets muertos

### ISSUE THREAD

**Issue by tomasCasa** [sisoputnfrba/foro#1873]
Hola!

Estamos teniendo un problema cuando probamos las cosas en las Puttys. Cuando corremos las pruebas completas por primera vez, corre todo perfecto. Ahora cuando hacemos CTRL+C para matar cada uno de los Procesos, y lo volvemos a levantar vemos que la CPU sube al 100% cuando activamos el Broker. Esto hace que el Broker no pueda recibir ningún tipo de mensaje, porque le llegan muchos sockets viejos, y el servidor de Broker empieza a crear Hilos a lo loco. Nos dimos cuenta que son sockets viejos porque cuando dejamos pasar un tiempo entre Prueba y Prueba, el Broker vuelve a funcionar con normalidad.

Les dejamos como seteamos el servidor de Broker, entendemos que la linea de setsockopt, limpia los sockets viejos(en realidad nos dejan volver a usar esos viejos). Pero, se ve que no esta haciendo correctamente.

```c
void iniciar_servidor(void)
{
	int socket_servidor;

    struct addrinfo hints, *servinfo, *p;



    memset(&hints, 0, sizeof(hints));
    hints.ai_family = AF_UNSPEC;
    hints.ai_socktype = SOCK_STREAM;
    hints.ai_flags = AI_PASSIVE;

    getaddrinfo(ip_broker, puerto_broker, &hints, &servinfo);

    int activado = 1;

    for (p=servinfo; p != NULL; p = p->ai_next)
    {
        if ((socket_servidor = socket(p->ai_family, p->ai_socktype, p->ai_protocol)) == -1)
            continue;
        setsockopt(socket_servidor,SOL_SOCKET,SO_REUSEADDR,&activado,sizeof(activado));
        if (bind(socket_servidor, p->ai_addr, p->ai_addrlen) == -1) {
            close(socket_servidor);
            continue;
        }
        break;
    }

    

	listen(socket_servidor, SOMAXCONN);

    freeaddrinfo(servinfo);

    while(1){
    	esperar_cliente(socket_servidor);

    }

}
```

Saludos,
Desde ya, muchas gracias.

**Comment by mgarciaisaia** [comment]
¿Chequearon si `setsockopt` está devolviendo algún error?

**Comment by tomasCasa** [comment]
Si ahí lo arreglamos, pusimos el printf y vimos que no lo estaba haciendo en las puttys, porque las shell no había agregado los cambios. Modificamos algo de la shell y esta funcionando con el mismo servidor que puse ahi arriba
