### ISSUE TITLE
[MAKEFILE] Cómo guardar el makefile que genera eclipse?

### ISSUE THREAD

**Issue by SebastianNLerner** [sisoputnfrba/foro#1874]
Buenas!
Con mi grupo habíamos creado un makefile a manopla que funcionaba dentro de todo bien, pero la última vez empezó a tirar errores con algunos archivos en particular. 
Cuando hacemos el make en la vm nos corre todo perfecto, pero cuando lo intentamos hacer en las vms de las pruebas no.
Teniamos entendido que se podia generar el makefile directamente desde eclipse, pero no sabemos como.
Alguien sabe como se hace? 🤔

**Comment by mgarciaisaia** [comment]
Les debo un video, sí.

**En principio**, Eclipse crea en el directorio `Debug/` de cada proyecto un archivo `Makefile`, y varios archivos (dos por cada directorio en que tengan código, creo) `sources.mk` y `objects.mk`. **Tienen que commitear todos esos archivos.**

En principio, les diría que desde Eclipse hagan un Clean de todos los proyectos, y que luego hagan `git add` de todos los `Makefile`s y los `.mk` que tengan por ahí. _Puede ser_ que tengan que hacer `git add -f` de esos archivos si es que los tienen en el `.gitignore`.

Habiéndolos agregado a git, los `commit`ean, `push`ean y deberían poder usarlos en la VM server. Hacen `cd` hasta el directorio donde está el Makefile, y ahí hacen `make`.

**Comment by SebastianNLerner** [comment]
Buenas,
Hicimos eso pero nos tira problema por una libreria compartida que tenemos.
Que podemos hacer?

**Comment by mgarciaisaia** [comment]
Compartir con algo más de detalle qué está pasando :)

¿Qué hicieron? ¿Cómo quedó? ¿Qué error tienen? ¿Qué se les ocurre que puede estar relacionado con eso?

**Comment by SebastianNLerner** [comment]
Creamos una libreria compartida sin las commons y cuando queremos hacer el make en Putty, el make de algun proceso, no nos encuentra el .h de nuestra libreria compartida

**Comment by SebastianNLerner** [comment]
ya esta arreglado, era un tema de paths que teniamos mal
