### ISSUE TITLE
Consulta por Memory Leaks

### ISSUE THREAD

**Issue by lmendoza01** [sisoputnfrba/foro#1876]
Buenas chicos,

Con mi grupo tenemos una duda con el tema de los memory leaks. La situación es esta, las pruebas finales e individuales nos están corriendo perfecto y controlado. Mientras tenemos estas pruebas corriendo, dejamos un htop en todas las VMs. Por ejemplo, en broker empezamos con una memoria(según htop) de 100MB de uso, y cuando terminan las pruebas queda en 103MB.

En los otros procesos pasa algo similar.

Nuestra duda sería si esta bien esta cantidad de memoria que estamos utilizando o si tenemos Memory Leaks para preocuparnos.

Saludos y mil gracias desde ya!!!

**Comment by mgarciaisaia** [comment]
La forma de saber si tienen leaks es, sencillamente, _correr con valgrind_. Después podrán charlar con el resto de l@s ayudantes (yo no sé) si 100mb es una cantidad razonable de memoria o no para su proceso (me suena a que no, pero no quiero asegurar nada).

Pero prueben con `valgrind` que contesta mucho más rápido y preciso que nosotr@s.

**Comment by brianUtn98** [comment]
Agrego de metido a lo que dijo Mati correr valgrind así:
valgrind --tool=memcheck --leak-check=full ./broker (por ejemplo).

**Comment by enogueiras** [comment]
> 
> 
> Agrego de metido a lo que dijo Mati correr valgrind así:
> valgrind --tool=memcheck --leak-check=full ./broker (por ejemplo).

Redoblo la apuesta jajaja:

**valgrind --leak-check=full --show-leak-kinds=all --log-file=leaks-memoria-broker.log ./broker** (por ejemplo)

Con eso lo tiras a un archivo y lo vas viendo tranqui, asi estamos liquidando nuestros "chorreos de memoria".

Abrazo,
Emilio.

**Comment by lmendoza01** [comment]
Buenas! Me sirvió bastante la ayuda que me dieron! Pude eliminar bastantes leaks que había. Muchas gracias!!!!
