### ISSUE TITLE
Pasar un script a las VMs

### ISSUE THREAD

**Issue by AlejandroDeheza** [sisoputnfrba/foro#1877]
Buenas, según algunos issues podemos (o deberiamos) hacer un script para hacer el deploy en menos tiempo. Mi duda era la siguiente: Para pasar este script a las VMs que nos van a asignar en la entrega, ¿Se puede pasar directamente desde nuestras PCs? o tenemos que descargarlo junto con el TP cuando clonamos el repo?

Como uso windows, pensaba usar Git Bash y usar el comando scp para enviar el archivo a cada VM. Esto seria correcto?

Saludos!

**Comment by mgarciaisaia** [comment]
No hay drama con que hagan o no script, ni en cómo lo hacen llegar a las VMs.

Lo que les funcione, por nosotr@s está OK.

**Comment by AlejandroDeheza** [comment]
Buenísimo, Gracias!
