### ISSUE TITLE
[Aporte] Cómo hacer el TP entero en VSCode

### ISSUE THREAD

**Issue by dariokozicki** [sisoputnfrba/foro#1878]
Hola!

Habiendo aprobado con mi grupo ayer y después de sufrir bastante cuatrimestres anteriores, armé una guía de [cómo armar el proyecto entero en VSCode.](https://github.com/dariokozicki/utnso-vscode). Este cuatri lo hicimos 100% VSC y es completamente posible llegar tranquilo a las entregas.

Próximamente tengo pensado hacer un video siguiendo estos mismos pasos, pero por ahora les dejo esto para ver qué les parece.

Saludos!

**Comment by mgarciaisaia** [comment]
Antes de seguir colgándola, _gracias_. Lindo laburo :)

**Comment by nubevi** [comment]
Realmente eres el rey de reyes. Muchas gracias Dario! Estaría muy copado que puedas hacer el vídeo para mayor didáctica.

Saludos!

PD: Buen meme el de Capusotto ;)

**Comment by dariokozicki** [comment]
@nubevi Gracias!

Habemus video [![UTNSO: Cómo hacer el TP en VSCode](http://i3.ytimg.com/vi/B_15qKMA1Fc/maxresdefault.jpg)](https://youtu.be/B_15qKMA1Fc)

**Comment by SantiagoIvan** [comment]
Holaa! Doy certificado de que funciona perfecto todo, incluso lo probe añadiendo al workspace el tp0 y me funciona perfecto. Ya armé el proyecto del tp para usarlo con mi grupo y a todos les funciona perfecto.
El unico problema que tengo yo y solamente yo es que (no se si a alguno le pasó) por más que tenga instalado el pluggin de INtellSense, no me autocompleta las cosas Alguna sugerencia?

**Comment by dariokozicki** [comment]
Gracias por tanto!
A nosotros nos pasaba eso cada tanto, __creo__ que tiene que ver con qué tan pesado está siendo VSC para tu compu, entonces si tenes 10 pestañas abiertas de repente ya no lo hacía. 
Lo que hacíamos para arreglarlo (al mejor estilo de Sistemas) era cerrar y volver a abrir VSC, y el autocompletado volvía.

**Comment by nico-abram** [comment]
Muchisimas gracias! 

Yo tuve algunos problemas, pero con hacer dos cosas parece que me anda todo joya ahora:

- Actualizar el vscode a la version mas reciente (La mas mas reciente no se puede porque ya no soporta 32bit, la que paso es la ultima de 32bit) https://code.visualstudio.com/updates/v1_35 (Es el .deb, es nomas abrirlo con el package manager y se actualiza)
 - Cambiar "intelliSenseMode": "clang-x64" por clang-86 (Para que sea de 32bits en vez de 64) en los archivos c_cpp_properties.json de las carpetas .vscode

Tuve que cerrarlo y abrirlo un par de veces y me parece que actualizo unas cosas de la extension de C++

Otra cosa es que pueden hacer que compile automaticamente cuando debugean, es nada mas agregar esta linea en los launch.json 

```
"preLaunchTask": "Make",
```

Y este objeto en el array en los archivos tasks.json:

```json
        {
            "label": "Make",
            "type": "shell",
            "command": "make",
            "problemMatcher": [
                "$gcc"
            ]
        },
```

Y un tip mas: Si quieren que se formatien automaticamente los archivos cuando los guardan, pueden apretar ctrl+shift+p, se abre una barra, buscan preferences UI
![imagen](https://user-images.githubusercontent.com/24706838/92335796-d93edb00-f070-11ea-969e-d2f4c66d5608.png)
se abre una ventana, ahi buscan "format" y tildan "format on save"
![imagen](https://user-images.githubusercontent.com/24706838/92335809-f5db1300-f070-11ea-8903-f8f78d888153.png)
O pueden abrir el JSON de preferences y agregar esta linea:

```
"editor.formatOnSave": true
```

**Comment by dariokozicki** [comment]
@nico-abram Genio! Te animas a hacer un pull request y te lo mergeo? 😃

**Comment by alejo0998** [comment]
Buenas! Con mi grupo estamos utilizando esta herramienta pero estamos teniendo un inconveniente a la hora de debuggear, cuando debuggeamos y entramos a la carpeta SHARED, y entramos al archivo en cuestion y ejecutamos paso por paso, nos tira este error, no sabemos bien a que se debe y en internet no encontramos informacion al respecto, alguien tiene idea porque puede ser? Desde ya, muchas gracias 

![Captura](https://user-images.githubusercontent.com/37853240/92475260-7e61cc80-f1b3-11ea-9129-0af9a417c414.PNG)

**Comment by nico-abram** [comment]
Buenas!

A mi tambien me estuvo tirando errores simialres pero no tuve problema ignorandolos, me parece que es que el intellisense/debugger buscan el codigo fuente de las bibliotecas estandar (especificamente glibc) de C y no lo encuentran

Capaz se puede hacer algo parecido a lo que recomienda este comentario: https://github.com/microsoft/vscode-cpptools/issues/811#issuecomment-521187568
Pero con la version y el path que te muestra. Pero no lo probe

**Comment by nico-abram** [comment]
Me parece que lo que comente arriba me anduvo, fue esto lo que hice:

```
sudo apt install glibc-source
cd /usr/src/glibc
sudo tar xvf glibc-2.23.tar.xz
```

Y en el launch.json de cada modulo:

```
            "sourceFileMap": {
                "/build/glibc-ViVLyQ": "/usr/src/glibc"
            },
```

No se si el hash y la version seran los mismos para todos, me imagino que si al usar la misma vm, si no la actualizaron

Tampoco estoy seguro de que me lo arreglo, pero ya debugie y modifique archivos y no vi el cartelito que veia antes

**Comment by FlorAldonatti** [comment]
@dariokozicki Muchas gracias! La verdad que tanto el post como el video super detallados. Sin conocer ninguna de las herramientas pude configurar todo de 10 👍

**Comment by nico-abram** [comment]
Buenas!

Queria dejar comentado que el intellisense me da un error cuando uso extensiones de GCC como ["nested functions"](https://gcc.gnu.org/onlinedocs/gcc/Nested-Functions.html) que estan buenas para algunas cosas (Especialmente para las funciones de iterar/etc de las common para colecciones que reciben punteros a funcion, no solo para tenerlas en el lugar de uso sino tambien por el "lexical scoping")

Entiendo que incluso con el vscode mas reciente no hay solucion (Por lo que vi en este issue https://github.com/Microsoft/vscode-cpptools/issues/1035 ), pero capaz alguien sabia algo

Por ahora me estuve manejando usando C estandar sin la extension porque son muy molestos los errores

**Comment by dariokozicki** [comment]
@nico-abram Es como vos decís, las nested functions son válidas para gcc pero no son del estándar de C, por eso no te las entiende VSCode; y hasta el momento no hay un fix, así que si las usás te va a quedar rojito (vas a poder debuggear dentro de ellas y todo, es solo visual)
De todas formas yo para amagar eso (en algunos lugares si, en otros no) directamente declaré las funciones de manera normal y las pasé por parámetro. Ej:

```
void* list_find_with_args(t_list *self, bool(*condition)(void*, void*), void* args) {
	t_link_element *element = self->head;
	int position = 0;

	while (element != NULL && !condition(element->data, args)) {
		element = element->next;
		position++;
	}

	return element != NULL ? element->data : NULL;
}

bool has_connection_id(void* data, void* id){
    return ((t_connection*) data)->id_connection == (uint32_t) id;
}

void handle_reconnect(uint32_t client_fd, reconnect* reconn){
    t_connection* conn = (t_connection*) 
        list_find_with_args(
            connections, 
            has_connection_id, 
            (void*) reconn->id_connection
        );
   [etc...]
}
```

(list_find_with_args es el list_find de la commons que además recibe argumentos extra, se lo cambié a manopla)
Haciendo esto te evitas repetir la nested function en varios lugares.
