### ISSUE TITLE
Consulta sobre VMs

### ISSUE THREAD

**Issue by fzappaandthem** [sisoputnfrba/foro#1880]
Estuve leyendo bastante respecto de las VMs y mi consulta (se debe haber hecho mil veces, pero busqué y no la vi) es: "Usar las VMs es mi mejor opción?"

Entiendo que podría en muchos casos ser más práctico, aunque vi varios issues con gente que tuvo problemas de inicio, etc... y prefiero sentarme a programar cada día sabiendo que la dificultad va a estar en escribir buen código, legible para mis compañeros de grupo.

En mi caso tengo dual boot Ubuntu + w10 y no me genera ningún tipo de problema! Podría incluso hacer un triple boot (podría ser innecesario), ya que tengo una notebook viejita que podría usar para correr un ubuntu server, o incluso correr la vm de ubuntu server sobre mi Ubuntu nativo, o un ubuntu server "limpio" sobre mi ubuntu nativo, en fin...

¿Alguien que haya cursado y/o tenga más experiencia que yo me puede dar su honesta opinión? 

GRACIAS!

**Comment by mgarciaisaia** [comment]
¡Aloha!

Confío en que hayas leído [este post](https://www.utnso.com.ar/sobre-no-usar-las-vms-para-el-desarrollo-del-tp/) linkeado desde la página de descarga de las VMs. Cinco años más tarde, lo único que cambiaría de ese post es que, buen, _estamos teniendo inconvenientes para hacer las entregas en el labo de Medrano_.

Mi consejo más fuerte a quienes cursen la materia sigue siendo "No se compren más complejidad accidental que la necesaria". De ese mantra salen (o deberían salir) todas las recomendaciones que hago/hacemos.

En noviembre/diciembre, cuando vayas a presentar tu TP, los procesitos van a tener que ejecutar correctamente en 3 o 4 VMs _muy muy iguales_ a la VM Server que tenés ahí para bajar (la única diferencia es que tienen disco más chico, pero, en serio: son **la misma** VM, a la que le achiqué el disco y la subí a Digital Ocean para poder crear máquinas ahí a partir de esa imagen).

A un grupo de gente que se maneje cómoda con todas las herramientas de desarrollo les diría _"desarrollen como quieran, pero prueben siempre en la VM server"_.

No sé si tenés grupo o no, y no sé qué nivel de comodidad tengan vos ni tus [potenciales] compañer@s de grupo. Por eso el consejo _por default_ es "Usen las máquinas que les damos, así no se chocan con problemas boludos".

Como siempre, ustedes eligen. No me calienta cómo desarrollen - hagan lo que mejor les funcione. Lo que me corresponde decirte es que hay un camino que _sabemos que funciona_, para el cual tenemos documentación y experiencia para darles soporte, y que, con sus problemas, consideramos que sigue siendo el camino de menos fricción para que un grupo de cinco personas relativamente random labure durante un cuatrimestre.

Hagan lo que quieran, pero sepan que nosotr@s podemos garantizarles una mano únicamente con este camino. Los desvíos van a quedar a cuesta suya: no podemos garantizar entender todos los setups y configuraciones que existen.

Midan como grupo qué ganas de comprarse la responsabilidad de manejar cosas extra tienen, y elijan.

**Comment by fzappaandthem** [comment]
Aloha!

👌

**Comment by fzappaandthem** [comment]
> ¡Aloha!
> 
> Confío en que hayas leído [este post](https://www.utnso.com.ar/sobre-no-usar-las-vms-para-el-desarrollo-del-tp/) linkeado desde la página de descarga de las VMs. Cinco años más tarde, lo único que cambiaría de ese post es que, buen, _estamos teniendo inconvenientes para hacer las entregas en el labo de Medrano_.
> 
> Mi consejo más fuerte a quienes cursen la materia sigue siendo "No se compren más complejidad accidental que la necesaria". De ese mantra salen (o deberían salir) todas las recomendaciones que hago/hacemos.
> 
> En noviembre/diciembre, cuando vayas a presentar tu TP, los procesitos van a tener que ejecutar correctamente en 3 o 4 VMs _muy muy iguales_ a la VM Server que tenés ahí para bajar (la única diferencia es que tienen disco más chico, pero, en serio: son **la misma** VM, a la que le achiqué el disco y la subí a Digital Ocean para poder crear máquinas ahí a partir de esa imagen).
> 
> A un grupo de gente que se maneje cómoda con todas las herramientas de desarrollo les diría _"desarrollen como quieran, pero prueben siempre en la VM server"_.
> 
> No sé si tenés grupo o no, y no sé qué nivel de comodidad tengan vos ni tus [potenciales] compañer@s de grupo. Por eso el consejo _por default_ es "Usen las máquinas que les damos, así no se chocan con problemas boludos".
> 
> Como siempre, ustedes eligen. No me calienta cómo desarrollen - hagan lo que mejor les funcione. Lo que me corresponde decirte es que hay un camino que _sabemos que funciona_, para el cual tenemos documentación y experiencia para darles soporte, y que, con sus problemas, consideramos que sigue siendo el camino de menos fricción para que un grupo de cinco personas relativamente random labure durante un cuatrimestre.
> 
> Hagan lo que quieran, pero sepan que nosotr@s podemos garantizarles una mano únicamente con este camino. Los desvíos van a quedar a cuesta suya: no podemos garantizar entender todos los setups y configuraciones que existen.
> 
> Midan como grupo qué ganas de comprarse la responsabilidad de manejar cosas extra tienen, y elijan.
