### ISSUE TITLE
Busco grupo

### ISSUE THREAD

**Issue by AlexanderRubin** [sisoputnfrba/foro#1882]
Hola buenas tardes, mi nombre es Alexander y estoy buscando gente para armar grupo. 
mi Email: alexander_rubin_29@hotmail.com

Soy del curso de los miercoles a la noche y sabados a la tarde. K3574.
Gracias
Saludos

**Comment by BelenTripodi** [comment]
Buenas! Hay un issue especifico para las personas que buscan grupo #1879 :-D
