### ISSUE TITLE
[Consulta] Cspec testing como importar mi .h

### ISSUE THREAD

**Issue by Nachiten** [sisoputnfrba/foro#1883]
Resulta que estoy queriendo usar cspec testing para mi (segundo) tp este cuatri. No para todo solo para cosas importantes tampoco quiero perder demasiado tiempo.

El punto es... me generé mi proyecto de cspec testing con el tutorial y luego me generé otro proyecto de prueba que seria un moduloX del cual querria testear las funciones.

Creo que con este screenshot alcanza para mostrar que lo que no estoy pudiendo básicamente es hacer el include del .h de mi proyecto en el proyecto de testing. No me toma el path y no se que me estaré comiendo.

![image](https://user-images.githubusercontent.com/39410888/90928840-04b59a80-e3ce-11ea-94b2-f83dae53ae9d.png)

Los dos proyectos que se ven en el proyect explorer estan en la misma carpeta. (/home/utnso/workspace) pero lo que quiero hayar y no pude entender es el path relativo para llegar desde un proyecto hasta el otro.

Gracias :)

**Comment by iago64** [comment]
@Nachiten como va?

Justo con respecto a tu pregunta, el cuatri pasado Tom se puso la 10 y armo un video de como linkear dependencias entre proyectos y la joda esta de -l y -L en eclipse: https://www.youtube.com/watch?v=A6dhc9cCI18

Como somos medio de madera para organizar la info capaz el video se perdio en el ether de información, chifla si te sirve y si no vemos que mas te puede estar faltando :)

Abrazo a la distancia!

**Comment by mesaglio** [comment]
Buenas @Nachiten como va?
Pudiste solucionar el problema?

Saludos

**Comment by Nachiten** [comment]
> Buenas @Nachiten como va?
> Pudiste solucionar el problema?
> 
> Saludos

No, no pude entender bien como hacer que mi proyecto de cspecTesting pueda depender de mas de un otro proyecto.

O sea poder usar el proyecto de testing para testear todo el resto de modulos del TP.

**Comment by karengrams** [comment]
¡Buenas!

@Nachiten ¿te parece venir el próximo sábado para solucionarlo en soporte? Dado que no lo pudimos solucionar por acá 😕 .

¡Saludos!

**Comment by Nachiten** [comment]
> ¡Buenas!
> 
> @Nachiten ¿te parece venir el próximo sábado para solucionarlo en soporte? Dado que no lo pudimos solucionar por acá 😕 .
> 
> ¡Saludos! 

Dale, la proxima lo pregunto. Cierro gracias
