### ISSUE TITLE
problema con la instalacion de guest additions

### ISSUE THREAD

**Issue by iancrespiok** [sisoputnfrba/foro#1884]
Hola instalo las guest additions tal cual muestra [este ](https://www.youtube.com/watch?v=uMoO58tPc5c)video y me da distintos mensajes. aun asi reinicio la maquina virtual. Cuando prende me tira este error (imagen 1) despues vuelvo a reiniciar y intento ver si puedo agrandar la imagen junto con la ventana y nada... no funciona. Trato de ver lo de la carpeta compartida como indican en el mismo video y tampoco... Selecciono la carpeta y no me deja ver el contenido (imagen 2).
Como lo puedo solucionar? gracias..
![error](https://user-images.githubusercontent.com/30092896/90944325-76084400-e3f4-11ea-9193-9d4c957c0171.png)
![Screenshot_5](https://user-images.githubusercontent.com/30092896/90944339-802a4280-e3f4-11ea-8a7f-5a449ba27449.png)

**Comment by lcerliani** [comment]
Buenas, uso Ubuntu 20.04 como sistema operativo anfitrión y me esta pasando esto mismo. Probé con la versión 6.0.18 de VirtualBox pero me sigue pasando. Desde la versión 5.2.54 para atrás no cuentan con instalador para Ubuntu 20.04.
Estoy trabado acá, si alguien me puede dar una mano lo agradecería mucho.

Saludos y gracias!
Lucas.

**Comment by chelyx** [comment]
Buenas, tampoco las pude instalar correctamente. Primero tenia la vBox 6.1 y como vi que podía ser un tema de versiones baje la 5.2.42, pero en la consola me tira esto
![image](https://user-images.githubusercontent.com/34224902/91511866-14921a80-e8b7-11ea-891b-76b9aac3a4db.png)
Si alguien sabe como puedo seguirlo seria de mucha ayuda.
Saludos

**Comment by ncoen97** [comment]
@chelyx Buenas, por el mensaje que te está saliendo parece algo parecido a [esto](https://github.com/sisoputnfrba/foro/issues/1275#issuecomment-476356566), así que fijate si te ayuda esa respuesta.
Y para que tengas en cuenta en próximos issues, no está bueno que suban capturas de pantalla. Sobre todo porque si por ejemplo en el issue que referencié recién hubieran hecho lo mismo, no podría haberlo encontrado poniendo "modprobe" en el buscador de issues.
Saludos!

**Comment by chelyx** [comment]
@ncoen97 hola, muchas gracias ahora lo reviso!

**Comment by karengrams** [comment]
¡Buenas!

Agregando a Nico, en caso de no encontrar otro el issue que corresponde al problem, traten de crear su propio issue y no comentar otros, así de esa forma podemos mantener los problemas separados. 

@iancrespiok ¿pudiste solucionar tu problema? ¿Podemos cerrar el issue?

¡Saludos!

**Comment by lcerliani** [comment]
Buenas, para los que tengan el mismo problema que @iancrespiok y no pudieron solucionarlo instalando una versión más vieja de VirtualBox, les comento lo que hice para solucionarlo. En la configuración de la VM, en Pantalla dejé la memoria de video en 128MB y el controlador gráfico en VBoxSVGA (por predeterminado lo tenía en VMSVGA). Haciendo eso me funcionó, puedo agrandar la pantalla junto con la ventana, copiar y pegar bidireccional, etc.

Saludos!
Lucas.

**Comment by karengrams** [comment]
@lcerliani ¡gracias por la info!

Cierro el issue dado que @iancrespiok no respondió. Cualquier cosa, lo re-abren.

¡Saludos!
