### ISSUE TITLE
¿Pequeño error en el enunciado del TP?

### ISSUE THREAD

**Issue by MaSosa314** [sisoputnfrba/foro#1887]
Hola. Estuve leyendo el TP y me encontre con esto en el modulo Comanda, en la descripción del mensaje `Guardar Plato` _(pag 22)_:

![image](https://user-images.githubusercontent.com/48865731/91641317-e5d08d00-e9f9-11ea-94c3-b9cf00ebc107.png)

En el punto 2, cuando dice _"Verificar si existe el pedido que existe dentro de la tabla de **páginas** de dicho Restaurante_". ¿No debería decir en la tabla de **segmento**? Tengo entendido que cada **segmento** en la tabla de segmentos del restaurante corresponde a un pedido _(pag 20)_:
![image](https://user-images.githubusercontent.com/48865731/91641424-a5254380-e9fa-11ea-9617-03adb6118663.png)

 Esto se repite en los otros mensajes tambien, diciendo que se debe verificar que el pedido exista en la tabla de páginas. Capaz estoy interpretando mal yo.

Saludos.

**Comment by karengrams** [comment]
¡Buenas buenas!

¿Como va? Espero que bien. El esquema que va a seguir este trabajo practico es segmentación paginada, donde cada restaurante tiene su tabla de segmentos y cada segmento tiene su tabla de paginas. A lo que nos referimos específicamente respecto a lo marcado, es que se debe verificar que la información que esta dentro de la tabla de paginas del pedido exista; en caso contrario, se deberá informar la situación, es decir, dentro del conjunto de paginas se van a guardar los items del pedido, y allí se debe verificar que se este guardando correctamente. 

Capaz no se logra comprender completamente lo que marcaste, y te agradezco por avisarlo, lo vamos a tener en consideración.

¡Saludos!

**Comment by karengrams** [comment]
¡Alo! 

Traigo buenas noticias, ahí lo modificamos apartado, te agradezco el aviso. Cualquier otra cosita, estamos por acá. Cierro el issue, pero no dudes en re-abrirlo en caso de ser necesario.

¡Saludos!

**Comment by MaSosa314** [comment]
Dale, buenisimo. Si si, quedo todo aclaradisimo.

Saludos.
