### ISSUE TITLE
Duda sobre el hito 1

### ISSUE THREAD

**Issue by AgustinDeCesare** [sisoputnfrba/foro#1889]
¿A que se refiere con definir el protocolo de comunicación?
--------------------------------------------

Hola, tenemos una duda sobre que seria definir el protocolo de comunicación, si se refiere a la serialización o los tipos de mensajes o si tiene que ver con otra cosa.

Gracias

**Comment by karengrams** [comment]
¡Buenas!

¿Como va? Espero que bien. Nos referimos a establecer como van a mandarse los mensajes entre los procesos, en donde, spoiler alert, van a tener que usar sockets. En el tp 0 se explica esto.

¡Saludos!

**Comment by mesaglio** [comment]
Hola @AgustinDeCesare, seguro [esto](https://www.youtube.com/watch?v=GnuurOt8yqE) te ayude bastante.
Saludos!!

**Comment by karengrams** [comment]
¡Buenas Agus!

¿Cómo va? Si quedo resuelta la duda, te voy a pedir que cierre el issue. Gracias 😸 

¡Saludos!
