### ISSUE TITLE
Problemas con el enunciado

### ISSUE THREAD

**Issue by Nahuelgp** [sisoputnfrba/foro#1890]
Buenas, tenemos 2 problemas despues de haber leido el enunciado. 

(1) Cuando dice que el Cliente se puede comunicar con todos los modulos, en particular cuando dice que puede crear un pedido directamente al restaurante (sin pasar por la app). Como se entregan esos pedidos? Por lo que entendimos el restaurante no maneja repartidores por lo que no comprendemos como se entregarian esos pedidos al Cliente. El restaurante le manda el pedido a la app y le dice que lo reparta aunque el cliente no se haya comunicado con ellos, el cliente va a buscarlo o de que forma se entrega?

(2) En el video que subieron acerca del tp cuando habla de la funcion finalizar pedido, dice que la app le puede mandar esta funcion a el Cliente 
![image](https://user-images.githubusercontent.com/49205232/91671230-5a3f2500-eafb-11ea-9685-5bb9285283cc.png)

Pero en el anexo I dice que esa funcion solo la manda la App a la Comanda

![image](https://user-images.githubusercontent.com/49205232/91671260-9bcfd000-eafb-11ea-88c3-dfb995328692.png)

Es un error en el enunciado, en el video o en nuestra interpretacion?

**Comment by karengrams** [comment]
¡Buenas!

¿Cómo va? Voy por puntos:

> (1) Cuando dice que el Cliente se puede comunicar con todos los modulos, en particular cuando dice que puede crear un pedido directamente al restaurante (sin pasar por la app). Como se entregan esos pedidos? Por lo que entendimos el restaurante no maneja repartidores por lo que no comprendemos como se entregarian esos pedidos al Cliente. El restaurante le manda el pedido a la app y le dice que lo reparta aunque el cliente no se haya comunicado con ellos, el cliente va a buscarlo o de que forma se entrega?

La finalidad del envió de dichos mensajes, no es seguir un flujo especifico, sino testear los módulos independientemente. En ese caso, se busca que se planifiquen bien los platos y se guarden bien en el modulo Sindicato.

> (2) En el video que subieron acerca del tp cuando habla de la función finalizar pedido, dice que la app le puede mandar esta función a el Cliente
> Pero en el anexo I dice que esa funcion solo la manda la App a la Comanda
> Es un error en el enunciado, en el video o en nuestra interpretacion?

No es un error de enunciado, simplemente no lo pusimos en el anexo por cuestiones que pensábamos que se sobre-entendia, sin embargo, ahora lo agregamos para evitar futuros malentendidos. Gracias por señalarlo.

¡Saludos!

**Comment by karengrams** [comment]
¡Buenas Nahuel!

¿Cómo va? Espero que bien. Si quedo resuelta la duda, te voy a pedir que cierres el issue. Gracias.

¡Saludos! 😸

**Comment by Nahuelgp** [comment]
Sisi quedo resuelto, gracias!
