### ISSUE TITLE
Preguntas sobre la consigna del TP

### ISSUE THREAD

**Issue by RaniAgus** [sisoputnfrba/foro#1891]
Buenas! Tenemos varias preguntas sobre el enunciado del TP: 

1) En varios módulos vemos que, dentro de los archivos de configuración, los valores de POSICION están escritos como POCISION, ¿es un error ortográfico, cierto?

2) ¿El módulo App no debería reconocer también el mensaje "Plato Listo"? En el video aparece ese mensaje como parte del flujo de "Finalizar Pedido", pero en el documento no se especifica qué hace la App al recibir ese mensaje, de hecho, no aparece:

> El módulo APP reconocerá los siguientes mensajes que le lleguen por sockets:
> - Consultar Restaurantes
> - Seleccionar Restaurante
> - Consultar Platos
> - Crear Pedido
> - Añadir Plato
> - Confirmar Pedido
> - Consultar Pedido

Igual, se puede llegar a sobreentender que, en realidad, lo único que hace este módulo es lo mismo que hace Restaurante (cito), pero aún así, al no aparecer como especificado, no es cómodo de interpretar al tener que leerse desde otro módulo:

> Cuando un Plato haya sido finalizado (cuando alcance la cola de Exit) se deberá informar al Módulo Sindicato para que actualice el estado del pedido y luego al módulo que solicitó el pedido.

3) En el módulo App, acerca del mensaje Añadir Plato, como primer paso dice lo siguiente:

> **Obtener el Pedido desde el Módulo Comanda.** Enviar al Restaurante dueño de dicho Pedido el mensaje que nos llegó. En caso que se trate del “Restaurante Default” pasar al punto 3.

Y en el módulo CoMAnda, en el mensaje Obtener Pedido, figura lo siguiente (dando a entender que en este caso solo se retornaría la existencia de dicho pedido, ya que no correspondería recibir la información del mismo):

> Responder el mensaje indicando si se pudo realizar **en conjunto con la información del pedido si correspondiera**.

Pero, en el Anexo I figura que Obtener Pedido retorna lo siguiente:

Retorna: [{comida1, cantTotal1, cantLista1}, {comida2, cantTotal2, cantLista2}, ...]

Entonces, ¿siempre se retorna la misma información y en este caso no se utiliza? ¿O tiene distintos retornos? Supongo que, en el segundo caso, el emisor debería avisar si necesita esos datos o solo una confirmación.

4) En el Anexo I aparecen 2 mensajes: Finalizar Pedido y Terminar Pedido, que ambos reciben y devuelven exactamente lo mismo, solo que uno es para Comanda y el otro es para Sindicato. ¿No debería aplicar el polimorfismo al igual que con otros mensajes?

Por otro lado, en el video se menciona que este mensaje es enviado por el Restaurante cuando este se da cuenta de que todos los platos de un pedido están listos, pero esto no aparece en ninguna parte del documento (solo aparece cuando un plato está listo), y en el módulo Sindicato no aparece "Terminar Pedido" como uno de los mensajes que acepta:

> El módulo Sindicato reconocerá los siguientes mensajes que le lleguen por sockets:
> - Consultar Platos
> - Guardar Pedido
> - Guardar Plato
> - Confirmar Pedido
> - Obtener Pedido
> - Obtener Restaurante
> - Plato Listo

Esperamos su respuesta!
Saludos!

**Comment by ncoen97** [comment]
Buenas.
1. Si, es un error ortográfico.
2. Si! De hecho en el anexo I está el mensaje Plato Listo, se ve que se nos pasó en el modulo App. Como bien decís, cuando la App reciba este mensaje deberá informarle a la Comanda (como también se explica en el video).
3. El mensaje siempre retorna la información del pedido. En la Comanda donde dice "si correspondiera" se refiere a que retorna esa información en caso de que la operación sea exitosa, si no lo es no la devuelve.
4. En este caso no elegimos usar el mismo nombre del mensaje porque ambos tienen distinto significado en nuestro sistema. El Terminar pedido se utiliza para informar que un Restaurante terminó de preparar un pedido, mientras que el Finalizar pedido se usa para eliminar la información de la memoria una vez que el pedido ya fue entregado. Como bien señalas, está faltando la especificación del mensaje Terminar pedido en el Sindicato, spoiler: actualiza el estado del pedido a Terminado.

Todas esos puntos vamos a tenerlos en cuenta para ir actualizando el enunciado para una próxima errata, así que te agradezco las recomendaciones/dudas.
Saludos!

**Comment by RaniAgus** [comment]
Buenísimo! Gracias por la rápida respuesta, saludos!

**Comment by mesaglio** [comment]
Buenas agus, si ya no tenes mas dudas respecto a este issue te pido que lo cierres.
De lo contrario volve a comentar.
Gracias, saludos.
