### ISSUE TITLE
string_get_string_as_array tiene un comportamiento erróneo si no recibe una lista

### ISSUE THREAD

**Issue by RaniAgus** [sisoputnfrba/foro#1892]
Buenas! Acabo de subir este posible problema como issue en las commons: https://github.com/sisoputnfrba/so-commons-library/issues/118, pero me dí cuenta que como alumno debí haber subido todo acá, perdón. 

Si prefieren, copio todo el texto y lo dejo editado en este comentario.

Saludos

**Comment by iago64** [comment]
Buenas! como va?

Justamente lo que comentas en el issue de las commons, es que justamente es comportamiento "no definido" ya que no estas respetando la **interfaz** definida para la función, la cual define que la lista tiene que estar entre [ ] y no debe tener elementos vacíos (o eventualmente los va a omitir).

Algo importante de las interfaces (mas allá de las funciones de las commons) es que si no las respetas, a veces te devuelven un error de una (el mundo mas feliz 😄) y otras hacen cosas que no tenes ni idea (el mundo menos feliz), por lo que lo mejor es tratar de respetarlas lo mas posible o si no, preguntar que onda como hiciste vos 😃 

Cualquier cosa que encuentres algo sin mucho sentido en los config de ejemplo del enunciado es muchisimo mas probable que sea un dedazo nuestro al momento de escribirlos que algo que tengan que interpretar.

Saludos.-

**Comment by RaniAgus** [comment]
Buenísimo, me quedo tranquilo en cuanto a chequear eso para los config. 

Lo que sí, en la consola del Sindicato de __este TP__ hay comandos que reciben strings en "formato lista" (en el cuatri pasado no había nada de eso más allá de los configs), así que servirá para chequear que se cumpla ese formato y que no nos mandemos un dedazo en ejecución :laughing: . Aunque supongo que más bien sería un "extra" que va más allá de la consigna (no especifica que deba haber sí o sí algún chequeo).

¡Gracias! Cierro ambos issues.
