### ISSUE TITLE
Consulta sobre sindicato

### ISSUE THREAD

**Issue by utnfd** [sisoputnfrba/foro#1893]
Queria consultar sobre el contenido y la estructura de los archivos en si:
1- El contenido de los archivos (los que van en los bloques) son de texto clave valor?
2- El archivo Metadata.afip es de texto o binario?
3- El contenido del archivo Metadata.afip se guarda directamente en ese archivo o bien, tiene que haber una referencia a algun bloque como en otros archivos?
4- Estos archivos .bin que indican el tamaño y hacen referencia al primer bloque son binarios o de texto con clave valor?
5- Los archivos que se guardan en los bloques, por ejemplo una receta, ese si es un archivo de texto con clave valor (al menos entendi eso)?

Gracias y disculpen la molestia.

![consulta](https://user-images.githubusercontent.com/70114777/91788145-d318ac80-ebe1-11ea-97ef-14d54ec9410e.png)

**Comment by karengrams** [comment]
Buenas buenas,

¿Como va? Espero que bien, hay un punto que se repite bastante, asi que las voy a responder adjuntando un par:

> 1- El contenido de los archivos (los que van en los bloques) son de texto clave valor?
> 2- El archivo Metadata.afip es de texto o binario?
> 4- Estos archivos .bin que indican el tamaño y hacen referencia al primer bloque son binarios o de texto con clave valor?
> 5- Los archivos que se guardan en los bloques, por ejemplo una receta, ese si es un archivo de texto con clave valor (al menos entendi eso)?

Los archivos no son ni de texto, ni binarios, son archivos .AFIP, donde, como dijiste vos, vamos a guardar clave-valor. Sin embargo, tal y como adjuntaste en ese ejemplo, vas a tener que tener cuidado a la hora de guardarlos, dado que puede que se presenta la situación donde el tamaño del bloque no es suficiente para almacenar la información. 

>3- El contenido del archivo Metadata.afip se guarda directamente en ese archivo o bien, tiene que haber una referencia a algun bloque como en otros archivos?

Se guarda directamente. Este archivo se utiliza para poder armar tu FS, por ende, se lo debe colocar en el directorio especificado en el enunciado, tu proceso debe leerlo, y a partir de la información leída, armar tu FS.

Cualquier cosita que haya quedado suelta, no dudes en volver a comentar. Si quedo todo resuelto, cerra el issue por favor.

¡Saludos!

**Comment by utnfd** [comment]
Bien, a lo mejor ya lo tienen planeado, pero les quería pedir si podrán proveer comprimido un filesystem de ejemplo para ver si es compatible lo que estamos haciendo.
Mas que nada porque no se si al momento de la evaluación nos van a proveer un filesystem pre-armado.
Muchas gracias.

**Comment by karengrams** [comment]
¡Buenas!

Perdón por la tardanza. Lamentablemente no 😕 , más acercadas a las fechas de la entrega, vamos a estar publicando las pruebas en cuestión donde se les dara una configuración especifica del FS. Sin embargo, si tenes duda sobre tu implementación, podes venir cualquier sábado de soporte, comentarnos tus dudas y con gusto te vamos a decir si estas bien encaminado o no.

¡Saludos!

**Comment by ncoen97** [comment]
@utnfd Buenas, quedaron todas las dudas resueltas?
Si es así te pido que cierres el issue. Saludos!

**Comment by utnfd** [comment]
Listo, muchas gracias!
