### ISSUE TITLE
Consultas - Sindicato

### ISSUE THREAD

**Issue by Nachiten** [sisoputnfrba/foro#1894]
Dos preguntas sobre la consigna respecto a la asignación de bloques enlazada.

1 - Yo tengo por ejemplo un tamaño de bloque de 64 bytes. Luego mi "puntero" (mi numero) que apunta al siguiente bloque deben ser 4 bytes extra además de esos 64? Haciendo que este bloque lleno pese 68 en total? O de mis 64 bytes solo puedo utilizar realmente 60 ya que reservo los últimos 4 para este numero que apunta al siguiente.

2 - Esta pregunta es sobre la forma de escribir el numero que apunta al siguiente bloque en el archivo. Si yo quiero escribir el numero de manera binaria y que pese exactamente 4 bytes puedo hacerlo, pero hacerlo de esta manera no quedará legible al abrir el archivo de texto. La otra alternativa es escribir el numero como un string pero de esta manera no va a pesar necesariamente 4 bytes. Va a pesar 1 byte * cant de caracteres (que ocupe el numero).

Gracias :)

**Comment by karengrams** [comment]
¡Alo!

¿Cómo va? Voy por puntos:

> 1 - Yo tengo por ejemplo un tamaño de bloque de 64 bytes. Luego mi "puntero" (mi numero) que apunta al siguiente bloque deben ser 4 bytes extra además de esos 64? Haciendo que este bloque lleno pese 68 en total? O de mis 64 bytes solo puedo utilizar realmente 60 ya que reservo los últimos 4 para este numero que apunta al siguiente.

De tus 64 bytes, solamente se van a utilizar 60 bytes para guardar lo que corresponde en ese bloque. En el anexo II, hay varios ejemplos donde se ven esos casos.

> 2 - Esta pregunta es sobre la forma de escribir el numero que apunta al siguiente bloque en el archivo. Si yo quiero escribir el numero de manera binaria y que pese exactamente 4 bytes puedo hacerlo, pero hacerlo de esta manera no quedará legible al abrir el archivo de texto. La otra alternativa es escribir el numero como un string pero de esta manera no va a pesar necesariamente 4 bytes. Va a pesar 1 byte * cant de caracteres (que ocupe el numero).

Primero, antes que nada, **no es un archivo binario**, es un archivo .AFIP; una vez dicho esto, no deberias tener el problema donde "no seria legible". Lo vas a guardar como un int, y a la hora de "levantarlo", lo vas a leer como un int, y sabes cual es el siguiente bloque

Cualquier cosa que no haya quedado clara, no dudes en volver a consultas.

¡Saludos!

**Comment by Nachiten** [comment]
> ¡Alo!
> 
> ¿Cómo va? Voy por puntos:
> 
> > 1 - Yo tengo por ejemplo un tamaño de bloque de 64 bytes. Luego mi "puntero" (mi numero) que apunta al siguiente bloque deben ser 4 bytes extra además de esos 64? Haciendo que este bloque lleno pese 68 en total? O de mis 64 bytes solo puedo utilizar realmente 60 ya que reservo los últimos 4 para este numero que apunta al siguiente.
> 
> De tus 64 bytes, solamente se van a utilizar 60 bytes para guardar lo que corresponde en ese bloque. En el anexo II, hay varios ejemplos donde se ven esos casos.
> 
> > 2 - Esta pregunta es sobre la forma de escribir el numero que apunta al siguiente bloque en el archivo. Si yo quiero escribir el numero de manera binaria y que pese exactamente 4 bytes puedo hacerlo, pero hacerlo de esta manera no quedará legible al abrir el archivo de texto. La otra alternativa es escribir el numero como un string pero de esta manera no va a pesar necesariamente 4 bytes. Va a pesar 1 byte * cant de caracteres (que ocupe el numero).
> 
> Primero, antes que nada, **no es un archivo binario**, es un archivo .AFIP; una vez dicho esto, no deberias tener el problema donde "no seria legible". Lo vas a guardar como un int, y a la hora de "levantarlo", lo vas a leer como un int, y sabes cual es el siguiente bloque
> 
> Cualquier cosa que no haya quedado clara, no dudes en volver a consultas.
> 
> ¡Saludos!

En la pregunta dos yo me referia con "no seria legible" a que al hacerle cat al archivo en la consola para leerlo todo el contendido del bloque si seria legible como texto, pero no el entero ya que lo escribi como 4 bytes de int y no como una cadena de char.

No es un problema entonces no poder ver el valor del int al abrir el archivo?

**Comment by karengrams** [comment]
¡Buenas!

Perdón por la tardanza. Nope, no es un problema _(incluso lo [especificamos así en el enunciado](https://docs.google.com/document/d/13JCJawPWfL2y6wGTBYykUTvQY5Uso0iYpXSFDAQFbFw/edit#bookmark=id.ha9cjki15jwz) a propósito 👀 )_.

¡Saludos!

**Comment by ncoen97** [comment]
@Nachiten Buenas, esto quedó resulto?

**Comment by Nachiten** [comment]
Sep. Cierro
