### ISSUE TITLE
Preguntas sobre el enunciado del TP -2-

### ISSUE THREAD

**Issue by RaniAgus** [sisoputnfrba/foro#1895]
Buenas! Haciendo otra lectura del enunciado, me surgieron las siguientes dudas:

1. **Módulo Cliente.** Sobre la inicialización del módulo, dice lo siguiente:
> Al momento de su inicialización, el módulo se intentará conectar al IP/Puerto definido por archivo de configuración. En caso de que la conexión no sea exitosa, finalizará informando por pantalla dicho error.

Pero, a su vez, en el archivo de configuración aparece la IP/Puerto de todos los módulos, separados:

> | Campo | Tipo | Descripción |
> | ------------- | ------------- | ------------- |
> | IP_COMANDA  | [Cadena]  | El IP del servidor del proceso Comanda. |
> | PUERTO_COMANDA | [Numérico] | El puerto del servidor del proceso Comanda. |
> | IP_RESTAURANTE  | [Cadena]  | El IP del servidor del proceso Restaurante. |
> | PUERTO_RESTAURANTE | [Numérico] | El puerto del servidor del proceso Restaurante. |
> | IP_SINDICATO | [Cadena]  | El IP del servidor del proceso Sindicato. |
> | PUERTO_SINDICATO | [Numérico] | El puerto del servidor del proceso Sindicato. |
> | IP_APP  | [Cadena]  | El IP del servidor del proceso App. |
> | PUERTO_APP | [Numérico] | El puerto del servidor del proceso App. |

¿De qué forma puedo avisarle al Cliente a qué módulo debe conectarse, teniendo a todos en su config? En ninguna parte se especifica si es a través de un menú de opciones, por argumento u otro.

2. **Módulo App.** En varias partes aparece la frase "en caso que no exista ningún Restaurante conectado..."

En Consultar Platos:
>  Cabe aclarar que **en caso que no exista ningún Restaurante conectado** se retornarán la lista de platos por default informado en el archivo de configuración.

En Crear Pedido:
> **En caso que no exista ningún restaurante conectado** se generará un ID arbitrario que defina al pedido (tener en cuenta que debe ser ÚNICO).

Esto me daría a entender que, al conectarse un Restaurante a la App, deja de estar disponible el "Resto Default" para Consultar Platos o Crear Pedido. Entonces, cuando esto pasa, la única forma de que el Cliente envíe estos mensajes a la App y obtenga una respuesta que no dé error sería si se envió antes un Seleccionar Restaurante (para que así la App pueda asociar el Cliente con el Restaurante), ¿entendí bien?

3. **Módulo App.** ¿Ocurre lo mismo que en el punto 2. para Consultar Pedido? ¿Debería primero Seleccionar Restaurante para luego enviar este mensaje? Si no hay ningún Restaurante conectado, ¿debo asumir que se trata de "Resto Default"? Esto es lo que dice el enunciado:

> Este mensaje permitirá obtener el estado de un pedido previamente confirmado. Para esto se obtendrán los datos desde el Módulo Comanda y se retornarán:
> 1. El Restaurante
> 2. Repartidor Seleccionado
> 3. El estado del pedido
> 4. La lista de platos con sus estados

4. **Módulo Restaurante.** Según el Anexo I, Consultar Pedido debería retornar el repartidor seleccionado, ¿cómo obtiene esa información, si es de la App? Esto es lo que dice el enunciado:

> Se le enviará al Módulo Sindicato el mensaje Obtener Pedido especificando un pedido del Restaurante, con la finalidad de obtener información actualizada del mismo, como por ejemplo, la cantidad lista.

5. **Módulo Comanda.** Entre los logs obligatorios y el config de ejemplo aparecen campos referidos a la ejecución de compactación:

> Las acciones a loguear en este archivo son: [...]
> 3. Ejecución de compactación.

> | Campo | Tipo | Descripción |
> | ------------- | ------------- | ------------- |
> | FRECUENCIA_COMPACTACION  | [Numérico] | Cantidad de pedidos eliminados previa compactación |

Pero entre los pasos a ejecutar al recibir un mensaje Terminar Pedido (en donde se eliminan los pedidos de la memoria) no se menciona dicha compactación. Supondría que se evalúa esto en el paso 4, después de eliminar las páginas de dicho segmento:

> 3. Se deberá proceder a eliminar las páginas correspondientes a dicho segmento. 
> 4. Por último, se procederá a eliminar el segmento correspondiente.

6. **Módulo Restaurante.** Al recibir el mensaje Confirmar Pedido, entre los pasos a seguir habla sobre un mensaje "Obtener Receta":

> 1. Obtener el Pedido desde el Módulo Sindicato.
> 2. Generar el PCB (Plato Control Block) de cada plato del pedido en cuestión y dejarlo en el ciclo de planificación (que se explicará a continuación en el módulo de Planificación de Platos). **Para esto, se deberá ejecutar el mensaje Obtener Receta al Módulo Sindicato** para saber la trazabilidad que deberá tener al momento de su ejecución. Cabe aclarar que el número de pedido se deberá guardar dentro del PCB para su futuro uso.
> 3. Informar al Módulo que lo invocó que su pedido fue confirmado.

Pero ese mensaje no aparece especificado ni en el Anexo I, ni en el Sindicato:

> El módulo Sindicato reconocerá los siguientes mensajes que le lleguen por sockets:
> 1. Consultar Platos
> 2. Guardar Pedido
> 3. Guardar Plato
> 4. Confirmar Pedido
> 5. Obtener Pedido
> 6. Obtener Restaurante
> 7. Plato Listo

Gracias de antemano!

**Comment by ncoen97** [comment]
Buenass.
1. La forma en la que seleccionen el módulo al que se va a conectar el cliente queda a libre implementación, las opciones que nombraste son validas.
2. Entendiste bien 👍 
3. Correcto.
4. Para el caso del Restaurante no se debe retornar el repartidor.
5. Ese campo quedó traspapelado, no hay compactación en la Comanda.
6. Es correcto lo que decís, faltó especificar ese flujo.

Devuelta, gracias por los comentarios. Todos estos puntos los vamos a tener en cuenta para sacar una errata próximamente.
Saludos!

**Comment by RaniAgus** [comment]
Genial! Gracias por la rápida respuesta (y por la paciencia, sé que son muchas preguntas jajaj)

Una cosita sobre el punto 4: supongo que por "no retornar el repartidor" te referís a que el Restaurante debe devolver siempre algún valor por default, ¿no? Esto lo digo pensando en lo que dice el Cliente sobre el polimorfismo:

> El objetivo del polimorfismo en nuestro trabajo práctico se debe a que los mensajes que cada módulo use serán polimórficos entre ellos. Esto quiere decir que las interfaces de los mensajes deben ser iguales, es decir, recibirán lo mismo y  retornar lo mismo. Por ejemplo, si el módulo A y el módulo B usan el mensaje “Crear pedido”, ambos deben recibir y retornar el/los mismos tipos de datos.

Es decir, no es que el Restaurante -no devuelve- el campo "repartidor", sino que para este caso (por más que lo devuelva) no nos interesaría su valor. Pero supongo que debería cumplirse con la interfaz del anexo I:

> - Interfaz:
>    - Recibe:
>        - ID de pedido
>    - Retorna: [Restaurante, repartidorSeleccionado,estado,[plato1,plato2,...,platoN]]

También, ahora que me doy cuenta, agrego una pregunta sobre este mensaje: 

7. **En el módulo App** dice que Consultar Pedido debe retornar "la lista de platos **con sus estados**" (como cité antes en la pregunta 3), pero en el Anexo I no aparece cantidad total y cantidad lista de cada plato, solo aparece el estado del pedido.

Igual no habría problema para obtener esa información (se sacaría de Obtener Pedido), pero supongo que, para que se cumpla lo que dice en la App, la interfaz de Consultar Pedido debería retornar algo así, ¿no?:

> [Restaurante, repartidorSeleccionado,estado,[{comida1, cantTotal1, cantLista1},{comida2, cantTotal2, cantLista2},...]] 

Sino, quizás la opción correcta sea que en la App solo diga que retorna "la lista de platos", sin sus estados.

De nuevo, gracias de antemano!

**Comment by ncoen97** [comment]
Buenas @RaniAgus , me imagino que con la nueva versión que sacamos estas dudas ya quedan resultas 😀

**Comment by RaniAgus** [comment]
Así es jajajaj, buenísimo! 
Gracias, cierro el issue
