### ISSUE TITLE
Multiple declarations of main

### ISSUE THREAD

**Issue by AgustinDeCesare** [sisoputnfrba/foro#1896]
Hola. tengo un problema al compilar el proyecto en Eclipse.
--------------------------------------------

Cuando le doy a make y compila me dice que hay múltiples declaraciones de la función main y me marca error en el código en el main de cada uno de los procesos
![image](https://user-images.githubusercontent.com/49216087/92180087-8ff64d80-ee1c-11ea-9646-6046d04f9e61.png)

Y ademas me marca que no están definidas las funciones de log, pero sí están incluidas en un archivo de utils en común que esta referenciado en el código del proceso

**Comment by tferraro** [comment]
👋 Holis,

El [primer link que apareció en google](https://stackoverflow.com/questions/12871157/multiple-definitions-of-main) me dice que estás definiendo 2 veces la función main.

A raiz eso y de lo que dice el comandito de compilación, `gcc -o "...." ...`, veo palabras claves con nombres de carpetas "Sindicato" "Restaurante" y me da la sensación de que armaste un único proyecto de eclipse, sobre lo que se crearon como varios 😛

Aunque es una teoría nomás. Aquí nos falta en un principio (y debería ser algo **constante en los próximos issues**), que nos cuentes la estructura de tu proyecto, como está compuesto, que pasos hiciste para crearlo e incluso **el error en texto para que otra alma perdida que en un futuro pueda llegar a este post usando el buscador**.
Porfa, ayudanos -*a ayudarte*- agregando esa información que hace al contexto en la creación del issue (y aprovechando [el template que ya habla sobre esto](https://github.com/sisoputnfrba/foro/blob/master/ISSUE_TEMPLATE.md)).

Espero que haya sido de ayudas 🙂 
Saludos!

**Comment by AgustinDeCesare** [comment]
Nosotros lo que hicimos fue crear un proyecto en el Eclipse y ahí adentro creamos una carpeta para cada proceso y en esa carpetas creamos los archivos .c y pusimos que el main se cree por defecto en cada uno de esos archivos.

Por otro lado en lo de los logs el error es undefined reference to log_create o log_info

**Comment by iago64** [comment]
Aloha!

De ahí viene el problema, 1 solo proyecto con muchos main.
Lo que deberían hacer sería tener 1 proyecto por cada proceso 😄 

Saludos.-

**Comment by tferraro** [comment]
Eso que dice Dami.
Hagamos un poco de retrospectiva de poruqe "1 proyecto por proceso".

La forma de trabajar de eclipse es crear un "proyecto" que representa un compilado final. En el caso de crear un proyecto normal (no lib), el output va a ser un binario ejecutable, que fue cumpliendo todas las diferentes parte del proceso de compilación que vieron en Sintaxis 🙂 

Ahora, si su tp va a tener multiples **procesos**, quiere decir que van a tener **múltiples binarios en ejecución**, porque un proceso no es más que un programa ejecutándose. Estoy medio perdido con esto de la cuarentena, peeero es una distinción que van a ver (o ya vieron) en la clase 1/2 de la cursada.
Por ende, la logíca indica que es un proyecot por cada proceso del tp.

Como **bonus**:
Cuando vemos un undefined reference..., (de nuevo) el primer link de google me llevó [acá](https://stackoverflow.com/a/5293199) diciendome que significa que te faltaron referencias en los #includes. Siendo funciones de las commons, una lib, no las hayas instalado/importado/linkeado a los proyectos. Porque deberías verlas en tu comando de compilación: `gcc ....`. Si no están en ese output del make del eclipse, muy probablemente pifiaste en crear bien tu proyecto 😉

**Comment by ncoen97** [comment]
@AgustinDeCesare  Buenas, pudiste resolver el problema? Te quedó alguna duda sobre lo que te comentaron tom y dami?

**Comment by AgustinDeCesare** [comment]
Si ya lo pude resolver, muchas gracias por la ayuda
