### ISSUE TITLE
Configuración Sindicato

### ISSUE THREAD

**Issue by kamipalomino** [sisoputnfrba/foro#1897]
Hola, estaba haciendo las conexiones del sindicato y me di cuenta que falta el IP en la configuración, o se obtiene de algún otro lado?
Saludos

**Comment by iago64** [comment]
Buenas!

Teniendo en cuenta que el sindicato es puramente servidor, podes llegar a no necesitar la ip al momento de crearlo, igual como regla base para todo el tp, lo que vean que necesitan agregar a su config, pueden hacerlo, nosotros solo les damos lo mínimo que nos interesa que sea configurable, lo demás queda a criterio del grupo.

Saludos.-

**Comment by kamipalomino** [comment]
perfecto gracias!
