### ISSUE TITLE
Consulta Restaurante

### ISSUE THREAD

**Issue by vivasjm** [sisoputnfrba/foro#1899]
En la definicion del tp modulo Application dice que este debe levantar un puerto  para que el restaurante se conecte, pero en el archivo de configuration del restaurante no hay definición de IP/port referente al modulo app, solo de sindicato. Lo agregamos? Es un error de definicion? o la ip/port del modulo app viene de otro lado (ejemplo metadata tomada del sindicato donde si hay conexion explicita)

**Comment by iago64** [comment]
Buenas! como va?

Como somos humanos, a veces nos equivocamos, tardamos un toque en contestar porque justo este punto lo agregamos en la V1.1 del enunciado que acaba de salir del horno: http://faq.utnso.com.ar/enunciado 

De todas formas, las cosas que vean que faltan en el config y uds las necesiten si o si, no se preocupen, pueden agregarlas, nosotros les pasamos lo mínimo que queremos configurar en "runtime", pero nada les prohíbe agregar mas cosas si su tp lo necesita 😉 

Abrazo a la distancia.-

**Comment by vivasjm** [comment]
Excelente, muchas gracias por la pronta respuesta y la aclaración
