### ISSUE TITLE
Consulta Cliente

### ISSUE THREAD

**Issue by nico-abram** [sisoputnfrba/foro#1900]
1) Habria 1 solo cliente en el sistema? Nunca va a haber mas de uno? Esto es lo que me dio a entender el enunciado pero me parecio raro que haya un solo "cliente"

2) En la configuracion del modulo cliente veo solo 1 ip/puerto de restaurante. Pero segun entiendo habria N procesos restaurantes en el sistema. Como seria la conexion?

**Comment by iago64** [comment]
Buenas! Como va?

_TL-DR_:
1.- Hay 1 solo **módulo** cliente, pero nada te impide tener varias ejecuciones de ese módulo.
2.- La idea es que un cliente solo le pegue a 1 restaurante por ejecución ya que es para hacer las pruebas especificas.

_Explicación_:
La idea del módulo cliente es ser digamos la aplicación básica para correr las pruebas (Por algo Nahue en el video de intro al TP aclaro que quien haga solo Cliente no aprueba el tp 😞), con lo cual, lo que termina pasando es que en las pruebas le pegamos a 1 solo restaurante a la vez, no nos interesa que el cliente conozca muchos restaurantes.

Preguntas numeradas hacen mas feliz la vida de los ayudantes 😄 

Abrazo a la distancia.-

**Comment by nico-abram** [comment]
Buenas!

Muchas gracias Dami, abrazo
