### ISSUE TITLE
Consulta App

### ISSUE THREAD

**Issue by nico-abram** [sisoputnfrba/foro#1901]
1) Que tan unico debe ser el id de pedido generado cuando no hay restaurantes? Osea, solo debe ser unico durante una ejecucion o tiene que mantenerse unico a traves de multiples ejecuciones? De necesitar mantenerse unico a traves de multiples ejecuciones, donde tendriamos permitido almacenar algo de estado para hacerlo?

2) Estaria permitido que Consultar Pedido del modulo App reciba el id de pedido?

3) En el ejemplo de archivo de configuracion de este modulo me resulto raro lo siguiente: ejemplo configuracion app: PLATOS_DEFAULT, TIEMPO_DE_DESCANSO, FRECUENCIA_DE_DESCANSO, REPARTIDORES figuran como listas en los tipos pero no son listas en el ejemplo. Porque seria esto?

**Comment by iago64** [comment]
Aloha, como va?

1.- No hace falta que sea único a través de todas las ejecuciones, con que sea único mientras todo esta levantado no hay problema :)

2.- Por que no estaría permitido algo que les dejamos en el [Anexo I](https://docs.google.com/document/d/13JCJawPWfL2y6wGTBYykUTvQY5Uso0iYpXSFDAQFbFw/edit#heading=h.iu4rtpr917kz)? 😉  Se nos pueden pasar cosas, pero bueno, el tema mensajes tratamos de dejarlo claro para que no se compliquen haciendo diseños monstruosos.

3.- Especialmente porque los ayudantes somos humanos y a veces las pifiamos, gracias por el aviso ahora lo corregimos de cara a la v1.1 que se publica en unas horitas con ajustes de manqueadas nuestras 😄 

Abrazo a la distancia.-
