### ISSUE TITLE
Conexion bidireccional

### ISSUE THREAD

**Issue by SantiagoIvan** [sisoputnfrba/foro#1902]
Hola! Tenía una consulta. El enunciado recomienda que utilicemos 2 sockets para una comunicación bidireccional (por ejemplo entre la App y el Restaurante). Sin embargo, yo con un socket puedo tanto recibir como enviar mensajes al otro proceso (usando hilos para cada acción). Queda a elección de cada grupo la manera de modelar las conexiones?

Fuente: https://www.codeproject.com/Questions/156575/Socket-Send-receive-simultaneously

**Comment by iago64** [comment]
Buenas! como va?

Efectivamente es una recomendación, pueden hacerlo como mas les guste.

Solo como spoiler: pensá como resolver la problematica de que la App va a estar mandando cosas constantemente (creación de pedidos, agregado de platos, etc) y puede que en algún momento le interese recibir algo, como por ejemplo el aviso de que un pedido esta listo. :wink:

Abrazo a la distancia.-

**Comment by vivasjm** [comment]
> Buenas! como va?
> 
> Efectivamente es una recomendación, pueden hacerlo como mas les guste.
> 
> Solo como spoiler: pensá como resolver la problematica de que la App va a estar mandando cosas constantemente (creación de pedidos, agregado de platos, etc) y puede que en algún momento le interese recibir algo, como por ejemplo el aviso de que un pedido esta listo. 😉
> 
> Abrazo a la distancia.-

Iago64 de hecho para la app si o si tenes que levantar 2 sockets, porque tenes un puerto de escucha y otro para conectar a la comanda. En el puerto de escucha por lo que vi se pueden recibir mensajes del restaurante y del cliente, pero la app va a iniciar conexion UNICAMENTE con la comanda (o estoy equivocado?). 

La app no conecta con el resto sino que el resto conecta con la app y dicho socket tambien puede ser usado para las nuevas conexiones que vienen del cliente.

en este caso manejando simplemente 1 socket para todos los incoming (resto/cliente) y otro para comanda deberia ser suficiente

**Comment by iago64** [comment]
> > Buenas! como va?
> > Efectivamente es una recomendación, pueden hacerlo como mas les guste.
> > Solo como spoiler: pensá como resolver la problematica de que la App va a estar mandando cosas constantemente (creación de pedidos, agregado de platos, etc) y puede que en algún momento le interese recibir algo, como por ejemplo el aviso de que un pedido esta listo. 😉
> > Abrazo a la distancia.-
> 
> Iago64 de hecho para la app si o si tenes que levantar 2 sockets, porque tenes un puerto de escucha y otro para conectar a la comanda. En el puerto de escucha por lo que vi se pueden recibir mensajes del restaurante y del cliente, pero la app va a iniciar conexion UNICAMENTE con la comanda (o estoy equivocado?).
> 
> La app no conecta con el resto sino que el resto conecta con la app y dicho socket tambien puede ser usado para las nuevas conexiones que vienen del cliente.
> 
> en este caso manejando simplemente 1 socket para todos los incoming (resto/cliente) y otro para comanda deberia ser suficiente

Ojo que la pregunta que hizo @SantiagoIvan creo que viene asociada a la recomendación de usar 2 sockets (Pagina 12 del enunciado) en el cliente y pusimos como ejemplo la app, que aparte de que tiene que hablar mínimo con 2 procesos diferentes (Restaurante y Comanda) tiene que poder enviar cosas y recibir de forma asincronica, pensa el ejemplo donde vos estas desde la app mandandole a un restaurante la info para crear un nuevo pedido con varios platos y en el medio el restaurante te tiene que confirmar que termino un pedido previo, como podes establecer el orden correcto de mensajes.
De todas formas como dije antes, es una recomendación, si pueden encontrar una forma de resolverlo con 1 solo socket pueden hacerlo, simplemente quisimos dejarles la puerta abierta para que puedan tomar decisiones de diseño sin preocuparse con 

Abrazo a la distancia!

**Comment by iago64** [comment]
@SantiagoIvan Como va? queda alguna duda por resolver?

**Comment by SantiagoIvan** [comment]
Tengo una duda mas, no se si es para un issue nuevo porque esta relacionado con lo mismo.
Por lo que entiendo, para una consulta de restaurantes voy a tener un codigo de operacion que acompañara al paquete, para obtener un pedido voy a tener otro codigo de operacion y así. Mi pregunta es la siguiente: cada vez que se envia un mensaje, como por ejemplo 'consultar restaurante', o cualquer otro, siempre hay otro mensaje que se envia despues desde el receptor como respuesta. ¿ El codigo de operacion de esa respuesta será un nuevo codigo de operacion? ( siguiendo con  el caso de Consulta_Restaurante seria RTA_Consulta_Restaurante ) ¿ o tal vez es mejor un campo extra que diga es_respuesta ? . Pregunto esto porque ( por lo que entendi ) dado un codigo de operacion, tengo 2 formas de serializar y deserializar, o al menos eso creo.

**Comment by iago64** [comment]
Buenas!
Recontra va para este issue tu duda 😄 
Las formas de serializar los mensajes son infinitas, cada grupo puede plantear su forma, pero es verdad que siempre vas a tener que identificar tu tipo de mensaje (Ya sea una Consulta, la respuesta a una consulta) y ahí es donde entra en juego la coordinación del equipo para hacerlo de la forma que menos código les tome cuando tienen varios procesos que envían y reciben los mismos mensajes (spoiler: polimorfismo 😉 😉)

Abrazo.-

**Comment by SantiagoIvan** [comment]
Muchas gracias ! :D

**Comment by ncoen97** [comment]
@SantiagoIvan Buenas, para la próxima cuando no quedan más dudas directamente pueden cerrar el issue.
Saludos!
