### ISSUE TITLE
Repositorio TP

### ISSUE THREAD

**Issue by Nahuehernandez** [sisoputnfrba/foro#1903]
Hola, no estaría pudiendo entrar al repositorio de mi grupo, creo que es porque no me dieron acceso. 
Repo del grupo: https://github.com/sisoputnfrba/tp-2020-2c-Incre-ble-pero-lo-romp-todo
Mi mail: nahueldahernandez@gmail.com

**Comment by iago64** [comment]
Buenas!

Eso posiblemente sea porque nunca aceptaste la invitación a la organización de sisoputnfrba, ahi volvi a generarte la invitación y deberías tener un mail (revisa por si las moscas en spam) y confirmame que pudiste acceder.

Abrazo a la distancia.-

**Comment by Nahuehernandez** [comment]
Ahí pude acceder, muchas gracias.

**Comment by iago64** [comment]
Buenisimo cerramos el issue entonces :)
