### ISSUE TITLE
Preguntas sobre la última versión del enunciado

### ISSUE THREAD

**Issue by RaniAgus** [sisoputnfrba/foro#1904]
¡Hola de nuevo! (perdón por molestarlos tanto por esta vía, agradezco la paciencia jajaj)

Tengo un par de dudas cortitas sobre el nuevo enunciado:

1. **Anexo I - Consultar Platos:** Cambiaron el retorno de "Consultar Platos", antes devolvía una lista de platos, y ahora devuelve lo siguiente:

> - Retorna: [{comida1, cantTotal1, cantLista1}, {comida2, cantTotal2, cantLista2}, ...]

El tema es que no tendría mucho sentido que devuelva el estado de cada plato, si el mensaje "Consultar Platos" estaría en una instancia previa a "Confirmar Pedido" ("Consultar Pedido" y "Obtener Pedido" son los que sirven para obtener cada plato con su estado durante un determinado pedido). ¿Quizás habría que revertir ese cambio?

2. **Restaurante - Planificación de los platos:** En esta sección, tenía entendido que iban a agregar cómo hace el módulo para Terminar Pedido. 

No se especifica si:
a) Se enviará un mensaje Obtener Pedido cada vez que tenga un Plato Listo (al igual que la App cuando recibe este mensaje);
b) Ya se cuenta con toda la información necesaria para determinar que un pedido esté terminado; o
c) Ambas implementaciones son válidas.

Por lógica, creería que la opción correcta es la a), pero el primer video da a entender que la opción correcta es la b).

3. **Comanda - Logs Mínimos y Obligatorios:** No es una duda, solo quería avisar que creo que se les olvidó quitar este log:

> 3. Ejecución de compactación.

Saludos!

**Comment by Nachiten** [comment]
Me meto para agregar algo sobre tu consulta 1.
Resulta que si yo le mando a sindicato el mensaje "Consultar Platos" se supone que quiero saber todos los platos que puede realizar cierto restaurant no? Pero estos platos pueden o no estar asociados a pedidos. Y para poder obtener los otros datos (cantTotal y cantLista) deberia si o si asociar este plato a un pedido (sabiendo que tranquilamente pueden estar asociados a mas de un pedido).

O sea que básicamente opino lo mismo que vos que si me pedis todos los platos que hace un restaurant solo te puedo responder los nombres, despues si me consultas un pedido especifico con el id de pedido (obtener pedido) ahi si tiene sentido que puedo darte los 3 datos (nombreComida, cantTotal, cantLista).

Espero respuestas sobre eso porque yo pensé exactamente lo mismo. Gracias

**Comment by ncoen97** [comment]
Buenas.
1. Correcto, consultar platos solo retorna el nombre de las comidas que puede preparar un Restaurante.
2. En este caso la opción b me parece la más correcta, pero va a depender de qué información del pedido guarden en el Restaurante.
3. 👌 

Saludos!
