### ISSUE TITLE
Consulta sobre algunos campos de los mensajes

### ISSUE THREAD

**Issue by RaniAgus** [sisoputnfrba/foro#1905]
Buenas! Un par de consultas:

Hay campos de mensajes que figuran en el Anexo I y no entendemos bien por qué están ahí, o no sabemos bien qué contienen:

1. **Seleccionar Restaurante:** Cliente
¿El Cliente tiene un nombre? ¿Acá se enviaría la posición del Cliente? Si la posición se envía acá, ¿qué pasa con Restaurante Default, para el cual no se envía este mensaje y se pasa directo a Crear Pedido? Si no se envía la posición acá, ¿cuándo se envía? ¿Al conectarse a la App?

2. **Guardar Plato:** Cantidad
El mensaje "Añadir Plato" no tiene este campo, por lo que cada vez que querramos Guardar Plato siempre estaríamos sumando uno, no necesitaríamos un campo Cantidad. Es más, hay una parte del enunciado del Sindicato que dice que es él el que hace la suma de la cantidad de platos al pedido.

> 4. Verificar si ese plato ya existe dentro del archivo. En caso de existir, se deberán **agregar la cantidad pasada por parámetro a la actual**.

3. **Obtener Restaurante:** [Receta1, Receta2, ..., RecetaN]
Para obtener las recetas, existe el mensaje "Obtener Receta". Quizás sea un typo y se refiera a [{Comida1,Precio1}, ...], pero, en ese caso, ¿de qué serviría que el Restaurante reenvíe el mensaje "Consultar Platos" al Sindicato, si de hecho ya cuenta con esa información? Hasta nos ahorraríamos el problema de que ese mensaje no es polimórfico, ya que el Sindicato necesita un campo más (Restaurante).

También hay otros campos que se mencionan a lo largo del TP pero no en el Anexo I:

4. **Precio (de cada Plato y total del Pedido):** Se menciona tanto en el Restaurante como en el Sindicato. 

> Metadata del restaurante
> Se ejecutará el mensaje Obtener Restaurante al módulo Sindicato obteniendo todos los datos del mismo, siendo algunos de ellos: Cantidad de cocineros y sus afinidades, posición del restaurante en el mapa, **recetas disponibles con sus precios** y la cantidad de hornos.

> (En Sindicato) 4. [...] En caso de no existir se deberá agregar el plato a la lista de Platos y anexar la cantidad que se tiene que cocinar de dicho plato y **aumentar el precio total del pedido**.

¿Deberían poder devolverse al enviar Obtener Restaurante (por lo que dice el enunciado), Consultar Platos (para ver cuánto vale cada uno), Añadir Plato y Guardar Plato (para ver cuánto vale el total de nuesto Pedido) y Confirmar Pedido (para ver el valor total final del Pedido)?

Saludos!

**Comment by RaniAgus** [comment]
Perdón por hacer tantas preguntas xd

**Comment by iago64** [comment]
Aloha!

Se me re paso el issue, solo lo taguee y me re colgue en contestarlo, mil disculpas, paso a contestarte:

1.- Pueden agregarle un ID por config o pueden generarlo al momento de establecer la comunicacion (en el handshake) eso tienen libertad de elegir, siempre y cuando el cliente sea polimorfico y pueda hablar independientemente con los procesos :)

2.- Buena observación, lo tomamos para analizarlo en la proxima errata que ya encontramos algunos detalles a corregir que nos quedaron un poco ambiguos.

3 y 4.- Están bastante relacionadas, vamos a analizarlo bien de cara a pulir una errata en estos días porque es muy cierto lo que planteas y vamos a tratar de dejarlo todo bien claro :)

Saludos.-

**Comment by RaniAgus** [comment]
Oki, estaremos atentos, gracias!
