### ISSUE TITLE
Restaurante: hilos & afinidades

### ISSUE THREAD

**Issue by vivasjm** [sisoputnfrba/foro#1906]
Dos consultas distintas sobre el modulo restaurante:

**1) Hilos**
En el tp (pagina 25) para la parte de restaurante dice que es condición necesaria para la aprobación la implementation de hilos. Mi pregunta es si la condición de hilos la exigen en algún componente en especial del modulo o simplemente exigen la utilización de los mismos en lo que nosotros consideremos necesario y suficiente? Mi pregunta viene porque la solución se puede pensar de varias formas y quisiera estar seguro como van a evaluar que la implementación de hilos sea correcta

**2) Afinidad de cocineros**
Como bien aclaran hay cocineros sin afinidades que pueden procesar cualquier plato. Podemos tener restaurantes con cocineros que por ejemplo solo procesen milanesas? o restaurantes cuyos cocineros no tengan ninguna afinidad y por lo tanto puedan cocinar cualquier cosa? Siempre los cocineros deben poder procesar algo no? no existe la posibilidad de un cocinero "deshabilitado"?

**Comment by iago64** [comment]
Buenas, como va?

Las preguntas numeradas son un éxito rotundo (y si, van a leer esa frase muy seguido)
1.- La idea de que usen hilos es que tengan cosas que puedan trabajar de manera concurrente y no secuencial (como si implementaran los servidores con select(). 
A términos prácticos, esto persigue 2 objetivos, el primero que todo lo que vean en la teoría respecto a la sincro de procesos / hilos lo puedan llevar a la practica en algo un poco mas "real" y vean realmente los problemas que representa sincronizar cosas y por que los profes de la teoria son tan detallistas con las correciones. Y el segundo objetivo, como dije antes, es un poco mas practico de implementación y que puedan aprovechar realmente los recursos del sistema (ya que si tienen muchos hilos y muchos procesadores, bueno, pueden escalar horizontalmente la capacidad de procesar cosas)

2.- No tenemos un escenario tan rebuscado donde tengamos cocineros "deshabilitados", siempre van a tener algo, respecto a los restaurantes con una sola afinidad, es posible que existan, pero a términos prácticos, eso solo va a hacer que a ese restaurant solo lleguen pedidos de esos platos y no de otros :)

Abrazo a la distancia!

**Comment by vivasjm** [comment]
gracias, me quedo claro

no entendí lo de las preguntas numeradas. Cuando levantamos un issue las tenemos que numerar nosotros?

**Comment by iago64** [comment]
Buenas! Nadaque agradecer 😄 
Lo de las preguntas numeradas era por lo de:
1) Hilos
2) Afinidad de cocineros

Aunque parezca trivial, las preguntas así tan puntuales y bien planteadas ayudan un montón tanto a nosotros a contestarlas como a sus compañeros que están buscando capaz una respuesta.

**Comment by vivasjm** [comment]
ahh jaja no habia entendido, muchas gracias. Cierro el tema

**Comment by vivasjm** [comment]
respondido
