### ISSUE TITLE
Restaurante: Metadata

### ISSUE THREAD

**Issue by vivasjm** [sisoputnfrba/foro#1907]
Consulta noto una diferencia entre la definición de la pagina 25 y la implementación de la api en la pagina 37. En la API falta la cantidad de hornos que se indica previamente en la pagina 25 cuando se define que se obtiene durante la inicialización, lo mismo con el precio de las recetas. Por lo tanto son 2 consultas:

1) Podemos agregar la cantidad de pedidos existentes a dicha API?
2) En la API tampoco aparece la referencia al precio de la receta, lo agregamos también no?

Pagina 25 (Metadata del restaurante)

Se ejecutará el mensaje Obtener Restaurante al módulo Sindicato 

1) Cantidad de cocineros y sus afinidades
2) posición del restaurante en el mapa, 
3) recetas disponibles con sus precios 
4) cantidad de hornos
5) cantidad de pedidos que ya disponga 

Pagina 37 (API)
○	Recibe:	Restaurante
○	Retorna: 
[
  [{cocinero1, afinidad},...,{cocineroN, afinidad}],
  posX,
  poxY,
  [receta1, …, recetaN], 
  cantHornos
]

**Comment by vivasjm** [comment]
consulta cuando dicen " [{cocinero1, afinidad},...,{cocineroN, afinidad}]" 

que sería "cocinero1,... ,cocineroN" un nombre, un ID numerico? porque si no es un nombre creo que es innecesario. Yo lo habia pensado de esta forma a la metadata:

{
     cantConcineros,
     {afinidad1,...,afinidadN},
     posX,
     poxY,
     [{receta1,precio1},...,{recetaN,precioN}],
     cantPedidos, 
     cantHornos
}

puesto que lo unico que me interesa es la cantidad de cocineros que tengo, las afinidades se asignan 1 a 1 y si tengo mas cocineros que afinidades los que sobran procesan todo. No encontré motivo para identificar a un cocinero con un nombre en particular

**Comment by mesaglio** [comment]
Si capaz no es necesario el id del cocinero, lo vemos para la próxima errata gracias

**Comment by vivasjm** [comment]
gracias! pregunto nomas para estar seguro de que no estoy yendo hacia una solución que luego tengo que cambiar. Muchas gracias por la ayuda
