### ISSUE TITLE
Error con las ¿Commons?

### ISSUE THREAD

**Issue by nubevi** [sisoputnfrba/foro#1908]
Tenemos el siguiente problema: nosotros tenemos en una carpeta los archivos "Restaurante.c", "utils_restaurante.c" 
y sus respectivos headers; y en otra carpeta (Utils) tenemos "utils_en_comun.c" y su header para las utils que
queremos compartir entre los distintos modulos. La dependencia de los archivo es la siguiente:
Restaurante.h includes utils_restaurante.h y esta utlima includes utils_en_comun.h. El problema es que nosotros 
queremos usar en Restaurante.c una funcion de las utils compartidas y por alguna razon nos tira error de que no 
conoce a esa funcion, pero si nosotros incluimos directamente las utils_en_comun.h en el Restaurante.h se soluciona
pero si las volvemos a incluir en las utils_de_restaurante.h tira error otra vez. 
¿Cual podria ser el error?

Aqui lo que muestra la consola a la hora de compilar:

```
_15:30:16 **** Incremental Build of configuration Debug for project App ****
make all 
make: Nothing to be done for 'all'.

15:30:17 Build Finished (took 237ms)

15:30:17 **** Incremental Build of configuration Debug for project Cliente ****
make all 
make: Nothing to be done for 'all'.

15:30:17 Build Finished (took 171ms)

15:30:17 **** Incremental Build of configuration Debug for project Comanda ****
make all 
make: Nothing to be done for 'all'.

15:30:17 Build Finished (took 112ms)

15:30:17 **** Incremental Build of configuration Debug for project Restaurante ****
make all 
Building target: Restaurante
Invoking: GCC C Linker
gcc  -o "Restaurante"  ./src/Restaurante.o ./src/datos_restaurante.o ./src/utils_Restaurante.o   
./src/Restaurante.o: In function `main':
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:8: undefined reference to `crear_conexion'
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:10: undefined reference to `log_info'
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:13: undefined reference to `log_info'
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:16: undefined reference to `pthread_create'
./src/Restaurante.o: In function `iniciar_logger':
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:31: undefined reference to `log_create'
./src/Restaurante.o: In function `leer_config':
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:35: undefined reference to `config_create'
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:37: undefined reference to `config_get_string_value'
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:38: undefined reference to `config_get_string_value'
makefile:30: recipe for target 'Restaurante' failed
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:39: undefined reference to `config_get_string_value'
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:40: undefined reference to `config_get_string_value'
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:41: undefined reference to `config_get_string_value'
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:42: undefined reference to `config_get_int_value'
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:43: undefined reference to `config_get_string_value'
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:44: undefined reference to `config_get_string_value'
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:45: undefined reference to `config_get_string_value'
./src/Restaurante.o: In function `terminar_programa':
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:49: undefined reference to `log_destroy'
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:51: undefined reference to `config_destroy'
./src/datos_restaurante.o: In function `enviar_sindicato_consultar_platos':
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/datos_restaurante.c:14: undefined reference to `serializar_paquete'
./src/utils_Restaurante.o: In function `esperar_cliente':
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/utils_Restaurante.c:48: undefined reference to `pthread_create'
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/utils_Restaurante.c:49: undefined reference to `pthread_detach'
./src/utils_Restaurante.o: In function `serve_client':
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/utils_Restaurante.c:58: undefined reference to `liberar_conexion'
./src/utils_Restaurante.o: In function `procesar_mensaje_recibido':
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/utils_Restaurante.c:66: undefined reference to `log_info'
collect2: error: ld returned 1 exit status
make: *** [Restaurante] Error 1

15:30:17 Build Finished (took 282ms)

15:30:17 **** Incremental Build of configuration Debug for project Sindicato ****
make all 
Building target: Sindicato
Invoking: GCC C Linker
gcc  -o "Sindicato"  ./src/Sindicato.o ./src/datos_sindicato.o ./src/utils_Sindicato.o   
./src/Sindicato.o: In function `main':
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/Sindicato.c:31: undefined reference to `pthread_create'
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/Sindicato.c:43: undefined reference to `crear_path_recetas'
./src/Sindicato.o: In function `iniciar_logger':
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/Sindicato.c:61: undefined reference to `log_create'
./src/Sindicato.o: In function `leer_config':
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/Sindicato.c:65: undefined reference to `config_create'
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/Sindicato.c:67: undefined reference to `config_get_string_value'
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/Sindicato.c:68: undefined reference to `config_get_string_value'
makefile:30: recipe for target 'Sindicato' failed
./src/Sindicato.o: In function `terminar_programa':
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/Sindicato.c:72: undefined reference to `log_destroy'
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/Sindicato.c:74: undefined reference to `config_destroy'
./src/datos_sindicato.o: In function `inicializar_paths_aux':
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/datos_sindicato.c:4: undefined reference to `string_append_with_format'
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/datos_sindicato.c:5: undefined reference to `string_append_with_format'
./src/datos_sindicato.o: In function `crear_path_restaurante':
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/datos_sindicato.c:9: undefined reference to `string_new'
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/datos_sindicato.c:11: undefined reference to `string_append_with_format'
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/datos_sindicato.c:13: undefined reference to `directorioExiste'
./src/datos_sindicato.o: In function `crear_path_receta':
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/datos_sindicato.c:21: undefined reference to `string_new'
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/datos_sindicato.c:23: undefined reference to `string_append_with_format'
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/datos_sindicato.c:25: undefined reference to `directorioExiste'
./src/datos_sindicato.o: In function `crear_archivo_info':
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/datos_sindicato.c:33: undefined reference to `string_new'
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/datos_sindicato.c:35: undefined reference to `string_append_with_format'
./src/datos_sindicato.o: In function `crear_archivo_receta':
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/datos_sindicato.c:44: undefined reference to `string_new'
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/datos_sindicato.c:45: undefined reference to `string_new'
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/datos_sindicato.c:47: undefined reference to `string_append_with_format'
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/datos_sindicato.c:48: undefined reference to `string_append_with_format'
./src/utils_Sindicato.o: In function `esperar_cliente':
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/utils_Sindicato.c:50: undefined reference to `pthread_create'
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/utils_Sindicato.c:51: undefined reference to `pthread_detach'
./src/utils_Sindicato.o: In function `serve_client':
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/utils_Sindicato.c:60: undefined reference to `liberar_conexion'
./src/utils_Sindicato.o: In function `procesar_mensaje_recibido':
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/utils_Sindicato.c:69: undefined reference to `log_info'
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/utils_Sindicato.c:72: undefined reference to `deserializar_consultar_platos'
collect2: error: ld returned 1 exit status
make: *** [Sindicato] Error 1

15:30:18 Build Finished (took 278ms)

15:30:18 **** Incremental Build of configuration Debug for project Utils ****
make all 
Building target: Utils
Invoking: GCC C Linker
gcc  -o "Utils"  ./utils_en_comun.o   
makefile:29: recipe for target 'Utils' failed
/usr/lib/gcc/i686-linux-gnu/5/../../../i386-linux-gnu/crt1.o: In function `_start':
(.text+0x18): undefined reference to `main'
collect2: error: ld returned 1 exit status
make: *** [Utils] Error 1

15:30:18 Build Finished (took 432ms)

15:30:18 **** Incremental Build of configuration Default for project tp-2020-2c-breakfastClub ****
make all 
make: *** No rule to make target 'all'.  Stop.

15:30:18 Build Finished (took 227ms)_
```

@karengrams @iago64

**Comment by mgarciaisaia** [comment]
¡Buenas!

Va a ayudar un toque más ver cómo se están compilando los `.o` por separado. Para que te muestre eso, deberías hacer un Clean de los proyectos antes de volver a compilar - fijate que las primeras líneas de tu log dicen `make: Nothing to be done for 'all'`, porque ya habías compilado los archivos previamente.

Cuando hacés `gcc  -o "Restaurante"  ./src/Restaurante.o ./src/datos_restaurante.o ./src/utils_Restaurante.o` está faltando _al menos_ el `-lcommons` y `-pthreads` para linkear dinámicamente contra las commons y pthreads. Además, hay algunas funciones que faltan que parecen ser de ustedes (estimo que las funciones compartidas, como `crear_conexion`), que tendría que ver cómo están declaradas para ver cómo deberías compilarlas (si están generando una biblioteca dinámica, o si faltan archivos fuentes en la compilación).

Probá de agregar esos dos parámetros que te digo y compilar con un Clean así vemos lo que falte :)

**Comment by nubevi** [comment]
Todas las funciones estan definidas en el .c y la "firma" en el .h. ¿Como y dondeagrego el -lcommons y el -pthreads? Antes no pasaba eso :/

Le tiré un clean all y volví a buildear, esto es lo que muestra por consola:

18:55:50 **** Build of configuration Debug for project App ****
make all 
Building file: ../src/App.c
Invoking: GCC C Compiler
gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/App.d" -MT"src/App.o" -o "src/App.o" "../src/App.c"
Finished building: ../src/App.c
 
Building target: App
Invoking: GCC C Linker
gcc  -o "App"  ./src/App.o   
Finished building target: App
 

18:55:50 Build Finished (took 767ms)

18:55:50 **** Build of configuration Debug for project Cliente ****
make all 
Building file: ../src/Cliente.c
Invoking: GCC C Compiler
gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/Cliente.d" -MT"src/Cliente.o" -o "src/Cliente.o" "../src/Cliente.c"
Finished building: ../src/Cliente.c
 
Building file: ../src/utils_cliente.c
Invoking: GCC C Compiler
gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/utils_cliente.d" -MT"src/utils_cliente.o" -o "src/utils_cliente.o" "../src/utils_cliente.c"
Finished building: ../src/utils_cliente.c
 
Building target: Cliente
Invoking: GCC C Linker
gcc  -o "Cliente"  ./src/Cliente.o ./src/utils_cliente.o   
Finished building target: Cliente
 

18:55:51 Build Finished (took 581ms)

18:55:51 **** Build of configuration Debug for project Comanda ****
make all 
Building file: ../src/Comanda.c
Invoking: GCC C Compiler
gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/Comanda.d" -MT"src/Comanda.o" -o "src/Comanda.o" "../src/Comanda.c"
Finished building: ../src/Comanda.c
 
Building target: Comanda
Invoking: GCC C Linker
gcc  -o "Comanda"  ./src/Comanda.o   
Finished building target: Comanda
 

18:55:51 Build Finished (took 275ms)

18:55:52 **** Build of configuration Debug for project Restaurante ****
make all 
Building file: ../src/Restaurante.c
Invoking: GCC C Compiler
gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/Restaurante.d" -MT"src/Restaurante.o" -o "src/Restaurante.o" "../src/Restaurante.c"
Finished building: ../src/Restaurante.c
 
Building file: ../src/datos_restaurante.c
Invoking: GCC C Compiler
gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/datos_restaurante.d" -MT"src/datos_restaurante.o" -o "src/datos_restaurante.o" "../src/datos_restaurante.c"
Finished building: ../src/datos_restaurante.c
 
Building file: ../src/utils_Restaurante.c
Invoking: GCC C Compiler
gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/utils_Restaurante.d" -MT"src/utils_Restaurante.o" -o "src/utils_Restaurante.o" "../src/utils_Restaurante.c"
../src/utils_Restaurante.c: In function ‘serve_client’:
../src/utils_Restaurante.c:58:2: warning: implicit declaration of function ‘liberar_conexion’ [-Wimplicit-function-declaration]
  liberar_conexion(*socket);
  ^
../src/utils_Restaurante.c: In function ‘procesar_mensaje_recibido’:
../src/utils_Restaurante.c:73:4: warning: implicit declaration of function ‘enviar_sindicato_consultar_platos’ [-Wimplicit-function-declaration]
    enviar_sindicato_consultar_platos(msg, socketConexionSindicato);
    ^
../src/utils_Restaurante.c: In function ‘iniciar_servidor’:
../src/utils_Restaurante.c:18:2: warning: ‘socket_servidor’ is used uninitialized in this function [-Wuninitialized]
  setsockopt(socket_servidor, SOL_SOCKET, SO_REUSEADDR, &activado, sizeof(activado));
  ^
Finished building: ../src/utils_Restaurante.c
 
Building target: Restaurante
Invoking: GCC C Linker
gcc  -o "Restaurante"  ./src/Restaurante.o ./src/datos_restaurante.o ./src/utils_Restaurante.o   
./src/Restaurante.o: In function `main':
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:8: undefined reference to `crear_conexion'
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:10: undefined reference to `log_info'
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:13: undefined reference to `log_info'
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:16: undefined reference to `pthread_create'
./src/Restaurante.o: In function `iniciar_logger':
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:31: undefined reference to `log_create'
./src/Restaurante.o: In function `leer_config':
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:35: undefined reference to `config_create'
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:37: undefined reference to `config_get_string_value'
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:38: undefined reference to `config_get_string_value'
makefile:30: recipe for target 'Restaurante' failed
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:39: undefined reference to `config_get_string_value'
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:40: undefined reference to `config_get_string_value'
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:41: undefined reference to `config_get_string_value'
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:42: undefined reference to `config_get_int_value'
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:43: undefined reference to `config_get_string_value'
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:44: undefined reference to `config_get_string_value'
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:45: undefined reference to `config_get_string_value'
./src/Restaurante.o: In function `terminar_programa':
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:49: undefined reference to `log_destroy'
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/Restaurante.c:51: undefined reference to `config_destroy'
./src/datos_restaurante.o: In function `enviar_sindicato_consultar_platos':
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/datos_restaurante.c:14: undefined reference to `serializar_paquete'
./src/utils_Restaurante.o: In function `esperar_cliente':
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/utils_Restaurante.c:48: undefined reference to `pthread_create'
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/utils_Restaurante.c:49: undefined reference to `pthread_detach'
./src/utils_Restaurante.o: In function `serve_client':
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/utils_Restaurante.c:58: undefined reference to `liberar_conexion'
./src/utils_Restaurante.o: In function `procesar_mensaje_recibido':
/home/utnso/tp-2020-2c-breakfastClub/Restaurante/Debug/../src/utils_Restaurante.c:66: undefined reference to `log_info'
collect2: error: ld returned 1 exit status
make: *** [Restaurante] Error 1

18:55:52 Build Finished (took 631ms)

18:55:52 **** Build of configuration Debug for project Sindicato ****
make all 
Building file: ../src/Sindicato.c
Invoking: GCC C Compiler
gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/Sindicato.d" -MT"src/Sindicato.o" -o "src/Sindicato.o" "../src/Sindicato.c"
../src/Sindicato.c: In function ‘main’:
../src/Sindicato.c:27:2: warning: implicit declaration of function ‘crear_punto_de_montaje’ [-Wimplicit-function-declaration]
  crear_punto_de_montaje();
  ^
../src/Sindicato.c:29:2: warning: implicit declaration of function ‘inicializar_paths_aux’ [-Wimplicit-function-declaration]
  inicializar_paths_aux();
  ^
../src/Sindicato.c:35:16: warning: implicit declaration of function ‘crear_path_restaurante’ [-Wimplicit-function-declaration]
   char* path = crear_path_restaurante(argv[2]);
                ^
../src/Sindicato.c:35:16: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
../src/Sindicato.c:37:3: warning: implicit declaration of function ‘crear_archivo_info’ [-Wimplicit-function-declaration]
   crear_archivo_info(path);
   ^
../src/Sindicato.c:43:16: warning: implicit declaration of function ‘crear_path_recetas’ [-Wimplicit-function-declaration]
   char* path = crear_path_recetas(argv[2]);
                ^
../src/Sindicato.c:43:16: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
../src/Sindicato.c:45:3: warning: implicit declaration of function ‘crear_archivo_receta’ [-Wimplicit-function-declaration]
   crear_archivo_receta(path, argv[2]); //¿Falta un & a la izq del path?
   ^
../src/Sindicato.c: At top level:
../src/Sindicato.c:53:6: warning: conflicting types for ‘crear_punto_de_montaje’
 void crear_punto_de_montaje(void){
      ^
../src/Sindicato.c:27:2: note: previous implicit declaration of ‘crear_punto_de_montaje’ was here
  crear_punto_de_montaje();
  ^
../src/Sindicato.c: In function ‘leer_config’:
../src/Sindicato.c:67:17: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
  puerto_escucha = config_get_string_value(config, "PUERTO_ESCUCHA");
                 ^
Finished building: ../src/Sindicato.c
 
Building file: ../src/datos_sindicato.c
Invoking: GCC C Compiler
gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/datos_sindicato.d" -MT"src/datos_sindicato.o" -o "src/datos_sindicato.o" "../src/datos_sindicato.c"
../src/datos_sindicato.c: In function ‘crear_path_restaurante’:
../src/datos_sindicato.c:13:7: warning: implicit declaration of function ‘directorioExiste’ [-Wimplicit-function-declaration]
  if (!directorioExiste(path)) {
       ^
../src/datos_sindicato.c:14:3: warning: implicit declaration of function ‘mkdir’ [-Wimplicit-function-declaration]
   mkdir(path, 0700);
   ^
Finished building: ../src/datos_sindicato.c
 
Building file: ../src/utils_Sindicato.c
Invoking: GCC C Compiler
gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/utils_Sindicato.d" -MT"src/utils_Sindicato.o" -o "src/utils_Sindicato.o" "../src/utils_Sindicato.c"
../src/utils_Sindicato.c: In function ‘iniciar_servidor’:
../src/utils_Sindicato.c:17:28: warning: passing argument 2 of ‘getaddrinfo’ makes pointer from integer without a cast [-Wint-conversion]
  getaddrinfo(ip_sindicato, puerto_escucha, &hints, &servinfo);
                            ^
In file included from ../src/utils_Sindicato.h:13:0,
                 from ../src/utils_Sindicato.c:1:
/usr/include/netdb.h:662:12: note: expected ‘const char * restrict’ but argument is of type ‘uint32_t {aka unsigned int}’
 extern int getaddrinfo (const char *__restrict __name,
            ^
../src/utils_Sindicato.c: In function ‘serve_client’:
../src/utils_Sindicato.c:60:2: warning: implicit declaration of function ‘liberar_conexion’ [-Wimplicit-function-declaration]
  liberar_conexion(*socket);
  ^
../src/utils_Sindicato.c: In function ‘procesar_mensaje_recibido’:
../src/utils_Sindicato.c:72:30: warning: implicit declaration of function ‘deserializar_consultar_platos’ [-Wimplicit-function-declaration]
    consultarPlatosRecibido = deserializar_consultar_platos(cliente_fd);
                              ^
../src/utils_Sindicato.c:72:28: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
    consultarPlatosRecibido = deserializar_consultar_platos(cliente_fd);
                            ^
../src/utils_Sindicato.c:71:22: warning: variable ‘consultarPlatosRecibido’ set but not used [-Wunused-but-set-variable]
    consultar_platos* consultarPlatosRecibido;
                      ^
../src/utils_Sindicato.c: In function ‘iniciar_servidor’:
../src/utils_Sindicato.c:20:2: warning: ‘socket_servidor’ is used uninitialized in this function [-Wuninitialized]
  setsockopt(socket_servidor, SOL_SOCKET, SO_REUSEADDR, &activado, sizeof(activado));
  ^
Finished building: ../src/utils_Sindicato.c
 
Building target: Sindicato
Invoking: GCC C Linker
gcc  -o "Sindicato"  ./src/Sindicato.o ./src/datos_sindicato.o ./src/utils_Sindicato.o   
./src/Sindicato.o: In function `main':
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/Sindicato.c:31: undefined reference to `pthread_create'
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/Sindicato.c:43: undefined reference to `crear_path_recetas'
./src/Sindicato.o: In function `iniciar_logger':
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/Sindicato.c:61: undefined reference to `log_create'
./src/Sindicato.o: In function `leer_config':
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/Sindicato.c:65: undefined reference to `config_create'
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/Sindicato.c:67: undefined reference to `config_get_string_value'
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/Sindicato.c:68: undefined reference to `config_get_string_value'
./src/Sindicato.o: In function `terminar_programa':
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/Sindicato.c:72: undefined reference to `log_destroy'
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/Sindicato.c:74: undefined reference to `config_destroy'
./src/datos_sindicato.o: In function `inicializar_paths_aux':
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/datos_sindicato.c:4: undefined reference to `string_append_with_format'
makefile:30: recipe for target 'Sindicato' failed
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/datos_sindicato.c:5: undefined reference to `string_append_with_format'
./src/datos_sindicato.o: In function `crear_path_restaurante':
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/datos_sindicato.c:9: undefined reference to `string_new'
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/datos_sindicato.c:11: undefined reference to `string_append_with_format'
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/datos_sindicato.c:13: undefined reference to `directorioExiste'
./src/datos_sindicato.o: In function `crear_path_receta':
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/datos_sindicato.c:21: undefined reference to `string_new'
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/datos_sindicato.c:23: undefined reference to `string_append_with_format'
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/datos_sindicato.c:25: undefined reference to `directorioExiste'
./src/datos_sindicato.o: In function `crear_archivo_info':
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/datos_sindicato.c:33: undefined reference to `string_new'
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/datos_sindicato.c:35: undefined reference to `string_append_with_format'
./src/datos_sindicato.o: In function `crear_archivo_receta':
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/datos_sindicato.c:44: undefined reference to `string_new'
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/datos_sindicato.c:45: undefined reference to `string_new'
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/datos_sindicato.c:47: undefined reference to `string_append_with_format'
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/datos_sindicato.c:48: undefined reference to `string_append_with_format'
./src/utils_Sindicato.o: In function `esperar_cliente':
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/utils_Sindicato.c:50: undefined reference to `pthread_create'
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/utils_Sindicato.c:51: undefined reference to `pthread_detach'
./src/utils_Sindicato.o: In function `serve_client':
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/utils_Sindicato.c:60: undefined reference to `liberar_conexion'
./src/utils_Sindicato.o: In function `procesar_mensaje_recibido':
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/utils_Sindicato.c:69: undefined reference to `log_info'
/home/utnso/tp-2020-2c-breakfastClub/Sindicato/Debug/../src/utils_Sindicato.c:72: undefined reference to `deserializar_consultar_platos'
collect2: error: ld returned 1 exit status
make: *** [Sindicato] Error 1

18:55:53 Build Finished (took 699ms)

18:55:53 **** Build of configuration Debug for project Utils ****
make all 
Building file: ../utils_en_comun.c
Invoking: GCC C Compiler
gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"utils_en_comun.d" -MT"utils_en_comun.o" -o "utils_en_comun.o" "../utils_en_comun.c"
../utils_en_comun.c: In function ‘enviar_paquete’:
../utils_en_comun.c:43:47: warning: passing argument 2 of ‘serializar_paquete’ makes pointer from integer without a cast [-Wint-conversion]
  void* a_enviar = serializar_paquete(paquete, bytes);
                                               ^
../utils_en_comun.c:3:7: note: expected ‘int *’ but argument is of type ‘int’
 void* serializar_paquete(t_paquete* paquete, int* bytes){
       ^
Finished building: ../utils_en_comun.c
 
Building target: Utils
Invoking: GCC C Linker
gcc  -o "Utils"  ./utils_en_comun.o   
/usr/lib/gcc/i686-linux-gnu/5/../../../i386-linux-gnu/crt1.o: In function `_start':
(.text+0x18): undefined reference to `main'
collect2: error: ld returned 1 exit status
makefile:29: recipe for target 'Utils' failed
make: *** [Utils] Error 1

18:55:53 Build Finished (took 224ms)

18:55:53 **** Build of configuration Default for project tp-2020-2c-breakfastClub ****
make all 
make: *** No rule to make target 'all'.  Stop.

18:55:54 Build Finished (took 180ms)

**Comment by iago64** [comment]
Buenas! como va? 

La respuesta a tu pregunta de como linkear las commons (y otras libs) justo esta en un video que armo Tom el cuatri pasado: https://www.youtube.com/watch?v=A6dhc9cCI18&ab_channel=UTNSO

Si seguís con alguna duda respecto a como linkear las commons, avisa y lo vemos :)

Abrazo a la distancia!

**Comment by mesaglio** [comment]
Buenas @nubevi agrego tambien otro link de como linkear las [commons a un proyecto](https://www.youtube.com/watch?v=Q8wfpu38PMc&t=3s&ab_channel=UTNSO).
Pd: cuando quieras agregar código, es más fácil para nosotros de leer si lo pones en este formato.
```
Ejemplo:
Building target: Utils
Invoking: GCC C Linker
gcc -o "Utils" ./utils_en_comun.o
/usr/lib/gcc/i686-linux-gnu/5/../../../i386-linux-gnu/crt1.o: In function _start': (.text+0x18): undefined reference to main'
collect2: error: ld returned 1 exit status
makefile:29: recipe for target 'Utils' failed
make: *** [Utils] Error 1
```

Como se hace esto??
\`\`\`
Ejemplo:
Building target: Utils
Invoking: GCC C Linker
gcc -o "Utils" ./utils_en_comun.o
/usr/lib/gcc/i686-linux-gnu/5/../../../i386-linux-gnu/crt1.o: In function _start': (.text+0x18): undefined reference to main'
collect2: error: ld returned 1 exit status
makefile:29: recipe for target 'Utils' failed
make: *** [Utils] Error 1
\`\`\`

[Aca hay un poco de documentacion de la sintaxis.](https://www.markdownguide.org/basic-syntax/)

**Comment by iago64** [comment]
@nubevi Pudiste resolver el inconveniente? Necesitas algo mas de ayuda?

**Comment by nubevi** [comment]
Sisi, recien lo pudimos arreglar. Era linkear las commons y hacer la Shared Library.

¡Muchas gracias por la ayuda!
