### ISSUE TITLE
Problema con las respuestas al modulo APP

### ISSUE THREAD

**Issue by NicoVillar98** [sisoputnfrba/foro#1910]
Hola buenas, estoy teniendo problemas para saber a que mensajes me están respondiendo los otros módulos, por ejemplo si un cliente me manda un mensaje de Crear Pedido y yo le mando a dicho Restaurante se supone que me tiene que responder con una id de pedido, pero como hace la APP para saber a que pedido le están respondiendo?. Si yo tengo dos pedidos del mismo cliente para el mismo restaurante como sabría que id es para que pedido?
Podría hacer que el restaurante me respondiera ademas de con el id de pedido con una forma de identificar a que cliente se esta refiriendo? o tengo que hacer que la APP se quede esperando la respuesta del mensaje que mando?
Desde ya muchas gracias.

**Comment by iago64** [comment]
Aloha! Como va?

Pueden hacer que tengan alguna forma de identificar a cada cliente? Si pueden y de hecho es parte de los desafíos que se les plantean.
Les vamos a decir cual? No, la idea un poco es que uds tomen esas decisiones de diseño y sepan explicarnos que los llevo a tomar esa decisión, siempre tratando de mantener el polimorfismo :)

Abrazo a la distancia!
