### ISSUE TITLE
Restaurante: Planificación CPU (cocineros)

### ISSUE THREAD

**Issue by vivasjm** [sisoputnfrba/foro#1911]
Consulta simple. Supongamos que tenemos  3 cocineros con estas afinidades (milanesa, pizza, general), el general no tiene afinidad, puede procesar todo.

En un momento dado la carga de procesamiento es

CPU  Tipo            Enqueued
 0      Milanesa             4
 1      Pizza                   4 
 2      General               3

y me llega un nuevo pedido de milanesa. Teniendo en cuenta la carga actual, en lugar de asignarlo a la cpu 0 (milanesa) no sería mejor asignado a la cpu 2 (general) para distribuir la carga de forma homogena entre todos los procesadores? o de acuerdo a la definición tenemos que asignarlos al cpu 0 que solo procesa ese plato?

**Comment by ncoen97** [comment]
Buenas, en el caso de que un plato tenga afinidad a un cocinero, siempre va a ser preparado por ese cocinero. En este ejemplo se asignaría al cpu 0.
Saludos!

**Comment by vivasjm** [comment]
muchas gracias

**Comment by vivasjm** [comment]
cierro el tema
