### ISSUE TITLE
Consulta multihilos en Sindicato

### ISSUE THREAD

**Issue by victoriaguillosson** [sisoputnfrba/foro#1912]
Buenas!
Vengo a hacer una consulta, tal vez tonta, pero no me terminó de quedar claro si en el módulo Sindicato la administración de mensajes, es decir, cada vez que recibimos un mensaje de otro módulo (sea cual sea) hay que usar multihilos o no.

Si alguno lo entendió mejor y me da una mano se agradece!

Saludos :)

**Comment by ncoen97** [comment]
Buenas.
Para poder darnos cuenta si el sindicato debe ser multihilo o no, deberíamos pensar qué pasaría en cada caso.
Si hacemos un sindicato monohilo, quiere decir que vamos a poder atender un único cliente a la vez; por lo tanto en el caso de que ya haya un Restaurante haciendo una consulta, cualquier otro intento de conexión de otro proceso fallaría. Ahora, si el Sindicato fuera multihilo, varios Restaurantes podrían hacer consultas concurrentemente.
Me parece que haciendo esa comparación ya se puede llegar a una respuesta, pero cualquier cosa no dudes en seguir consultando. Como siempre decimos, no hay preguntas tontas, o las únicas preguntas tontas son las que no se hacen 😄
Saludos!

**Comment by iago64** [comment]
@victoriaguillosson Se entendió la respuesta de Nico? Necesitas que aclaremos algo mas?

**Comment by victoriaguillosson** [comment]
Buenas, sisi se entendio perfecto! Colgué en cerrar el issue. Muchas gracias!
