### ISSUE TITLE
Consulta GUARDAR PEDIDO en CoMAnda (duda de enunciado)

### ISSUE THREAD

**Issue by TheLucasPrada** [sisoputnfrba/foro#1913]
Buenas! en base a una consulta que hice el sábado de soporte, el ayudante me solicitó que cree este Issue, porque no está claro el funcionamiento cuando debería fallar esta solicitud.

La consulta surge básicamente por el enunciado: cuándo debería fallar el intento de crear un nuevo pedido?

Entre las opciones que discutimos el sábado deducimos que bien podría pasar si no quedaba espacio en memoria, que CoMAnda rechace el nuevo pedido, pero teniendo en cuenta que los pedidos en si no ocupan espacio en memoria, sino los platos del pedido, no nos parecía muy lógico.

Por otro lado, se nos ocurrió que podía darse el caso de que la ID del pedido para ese restaurante ya exista, en ese caso, debería devolverse un FAIL por no poder crearse? pero en ese caso desde el otro lado se podría entender que no se pueden agregar platos a ese pedido por no haberse podido crear (aunque si existe) o debería devolverse un OK? puesto que aunque no se creó en si un nuevo pedido, este ya existe y es posible agregarle platos por ejemplo.

Dicho esto, PUEDE darse siquiera el caso en que llegue una ID de pedido repetida? tengo entendido que cada restaurante maneja sus propias IDs por lo que no deberían pisarse nunca, o es parte de algún testing tratar de pisar una ID desde el Cliente para ver si hace agua el modulo? en ese caso habría que agregar un control extra cuando llegue el mensaje de GUARDAR PEDIDO, cosa que no está contemplada en los pasos a seguir del enunciado.

Así que bueno, el Issue es para aclarar esto :P
Saludos!

**Comment by ncoen97** [comment]
Buenas, el hecho de que los pedidos no ocupan lugar en la memoria principal si están vacíos es cierto, por lo tanto deberían dejar que se creen pedidos nuevos aunque no haya espacio en memoria (podría pasar que entre que se crea el pedido y se le agregan platos, hay otro pedido que finaliza y libera el espacio por ejemplo). Y yendo al caso de ids repetidos, como bien decís, en principio no debería ocurrir; igualmente por las dudas te diría que si te llega un Crear Pedido con un id ya existente, deberían retornar un error porque ese pedido ya debería ser de otro cliente y no deberían agregarse platos de uno nuevo.
Saludos!

**Comment by TheLucasPrada** [comment]
Genial, clarisimo, muchísimas gracias.

Saludos!
