### ISSUE TITLE
Consulta Consola Cliente

### ISSUE THREAD

**Issue by ignaciostellino** [sisoputnfrba/foro#1914]
Buenas,
Para la consola de cliente:
1) tenemos que dejar al usuario que tipee libremente el mensaje que quiere enviar con todos los parametros necesarios o tenemos que listarle por ejemplo todas las opciones de mensajes que puede enviar?
2) Si dejamos que tipee libremente, deberiamos validar si es un mensaje que no existe dentro de las APIs y tambien si es que existe que ingrese todos los parametros requeridos?

Desde ya muchas gracias.

**Comment by ncoen97** [comment]
Buenas,
1. Esto es a libre implementación, total las pruebas las corren ustedes mismos así que van a saber como ingresar los comandos.
2. No es requisito que validen los inputs, pero se los recomiendo muy fuertemente por la siguiente razón: Cuando estén corriendo las pruebas el día de la entrega, van a estar usando la vm server (donde no se puede debugear). Si por alguna razón le pifian en algún comando, la consola muy posiblemente tire un segmentation fault, y ahí ustedes van a entrar en pánico porque no saben cual es el error ni por qué rompe algo que pensaban que funcionaba. Por lo tanto lo mejor es logear algún mensaje de error y se ahorran ese mal momento.
Saludos!

**Comment by JoseStellino** [comment]
> Buenas,
> 
> 1. Esto es a libre implementación, total las pruebas las corren ustedes mismos así que van a saber como ingresar los comandos.
> 2. No es requisito que validen los inputs, pero se los recomiendo muy fuertemente por la siguiente razón: Cuando estén corriendo las pruebas el día de la entrega, van a estar usando la vm server (donde no se puede debugear). Si por alguna razón le pifian en algún comando, la consola muy posiblemente tire un segmentation fault, y ahí ustedes van a entrar en pánico porque no saben cual es el error ni por qué rompe algo que pensaban que funcionaba. Por lo tanto lo mejor es logear algún mensaje de error y se ahorran ese mal momento.
>    Saludos!

Muchas gracias!

**Comment by ignaciostellino** [comment]
> Buenas,
> 
> 1. Esto es a libre implementación, total las pruebas las corren ustedes mismos así que van a saber como ingresar los comandos.
> 2. No es requisito que validen los inputs, pero se los recomiendo muy fuertemente por la siguiente razón: Cuando estén corriendo las pruebas el día de la entrega, van a estar usando la vm server (donde no se puede debugear). Si por alguna razón le pifian en algún comando, la consola muy posiblemente tire un segmentation fault, y ahí ustedes van a entrar en pánico porque no saben cual es el error ni por qué rompe algo que pensaban que funcionaba. Por lo tanto lo mejor es logear algún mensaje de error y se ahorran ese mal momento.
>    Saludos!

Muchas gracias!
