### ISSUE TITLE
Debería la consola de cliente soportar lecturas de mensajes multidestinatarios?

### ISSUE THREAD

**Issue by julchat** [sisoputnfrba/foro#1915]
Debería incluir como funcionalidad la posibilidad de mandar a 2 módulos distintos el mismo mensaje en una sola línea de consola? O puedo darme el lujo de que el destinatario sea solo 1?

Ej: Quiero mandar enviarPlato(unPlato) a Sindicato y Restaurante,
Sería válido que para hacerlo tenga que mandar enviarPlato(unPlato) Sindicato, enviarPlato(unPlato) Restaurante, o tendría que poder hacerlo con una sola escritura de consola? Por ej: enviarPlato(unPlato) Sindicato;Restaurante

**Comment by ncoen97** [comment]
Buenas, los mensajes en el cliente deben ser a un solo módulo a la vez. Saludos!
