### ISSUE TITLE
Sindicato: logs minimos

### ISSUE THREAD

**Issue by utnfd** [sisoputnfrba/foro#1916]
Una consulta entre los logs minimos esta:
6- Desasignación de un bloque y su respectivo número.

Por lo que entiendo, en este TP no hay desasignacion de bloques, pq la info siempre queda almacenada.
Hay que desestimar este requerimiento?

Gracias

**Comment by ncoen97** [comment]
Buenas, tengan en cuenta que cuando hacen una edición de algún campo y el nuevo valor es más chico que el viejo, ahí puede ser que tengan que desasignar algún bloque si justo se vacía el último. Ahora el único caso que recuerdo en el que aplica esto es el de cambiar el estado del pedido entre Confirmado y Terminado, pero puede ser que haya alguno más dando vueltas.
Saludos!

**Comment by utnfd** [comment]
Dale, perfecto. Gracias por el dato.
