### ISSUE TITLE
Restaurante: obtener restaurante #2

### ISSUE THREAD

**Issue by vivasjm** [sisoputnfrba/foro#1917]
Una consulta, el formato de la cadena que recibimos en cada modulo lo definimos en cada grupo? o tenemos que apegarnos estrictamente al formato definido en anexo del tp?

Por ejemplo para el mensaje "obtener restaurante" en el anexo dice que debemos devolver del sindicato al restaurante:

_[{cocinero1, afinidad},...,{cocineroN, afinidad}],
posX,
poxY,
[receta1, …, recetaN], 
cantHornos
]_
por lo que un ejemplo de una cadena basado en ese formato podria ser

"[{1,Milanesa},{2,Ensalada},{3,Tarta}],4,5,[Milanesa,Ensalada,Tarta],10" 

pero tambien podria ser
"1,Milanesa,2,Ensalada,3,Tarta@4,5@Milanesa,Ensalada,Tarta@10"

o cualquier otra implementación que pase la misma información con otro formato. Esto lo podemos definir nosotros mientras pasemos toda la información necesaria?

Por último queria ver si ya tenian una definición sobre pasar o no el "numero" o nombre del cocinero en dicho mensaje, ya que no se usa para nada, solo necesitamos saber la cantidad de cocineros disponibles. En una pregunta anterior que hice me dijeron que seguramente lo actualizaban en la proxima version del tp.

gracias

**Comment by ncoen97** [comment]
Buenas, para el formato especificado en el anexo intentamos acercarnos lo más posible a JSON para que se entienda mejor la estructura de arrays, pero ese formato no es lo que ustedes van a mandar por sockets. Recuerden que para eso tenemos la serialización (recontra recomendado leerse [esta guía](https://docs.google.com/document/d/190LLBTzHkFmD_yS8OWcUsJoIOQVKxJkUxIFtcnChr-g/edit#heading=h.3znysh7)), si hay alguna duda con respecto a esto no duden en consultar.
Con respecto a la errata lamento decirte que todavía no tengo noticias, pero cuando vaya a salir la nueva versión vamos a estar avisando por utnso.
Saludos!

**Comment by vivasjm** [comment]
Claro, si no hay dudas respecto a la serialización y como empaquetar/desempaquetar los mensajes. Mi pregunta es si el protocolo por el cual vamos a enviar los distintos datos los podemos definir nosotros de acuerdo a nuestra conveniencia y criterio o si es obligatorio respectar algun formato en el payload

Básicamente estamos haciendo lo que dice la guia de serialización, enviando header + payload (en el caso que exista payload) y en el header indicamos claramente el tamaño en bytes del payload. Antes de enviar empaquetamos el header, lo enviamos y lo desempaquetamos cuando nos llega. Al payload lo tratamos como un vector de chrs (no string, sin en \0) , cuando tenemos varios campos o listas los separamos por una caracter y al recibir todo lo separamos en tokens y armamos la estrucutra y completamos las variables  que sean necesarias.

Esto lo resolvemos para todos los modulos usando las mismas funciones, nos permite controlar, enviar/recibir exactamente los bytes que queremos con suma exactitud y sin problemas.

Pongo esta pregunta no porque tengamos un problema sino porque quiero evitar cualquier contratiempo en el momento de la corrección y estar seguros que estamos alineados con lo que se pide

Muchas gracias como siempre

**Comment by ncoen97** [comment]
Okay, ahí entendí por donde viene la consulta. El tema de tener todo el payload como un char* es que no es seguro por el hecho de que si en tus datos tenes por alguna razón un carácter centinela, les va a romper todo cuando intenten leerlo. Por ejemplo, si a los cocineros les pusiéramos como nombre su usuario de instagram con el @ (cosa que no va a pasar), o tuvieran que enviar una imagen o cualquier dato tipo binario que pueda llegar a contener una combinación que se interprete como tu centinela en ASCII, fuiste. Por lo tanto si vamos a un ámbito más profesional no deberían hacerlo.
Finalmente, contestando a tu pregunta, si lo pueden hacer mientras tengan en cuenta todas estas consideraciones.
Saludos!

**Comment by ncoen97** [comment]
Buenas @vivasjm, si no quedan más dudas te pido que cierres el issue 😃
