### ISSUE TITLE
Comanda - Guardar Pedido

### ISSUE THREAD

**Issue by RodrigoLista** [sisoputnfrba/foro#1918]
Buenas. Tengo una duda respecto al mensaje guardar pedido que recibe la comanda.

Por lo que entiendo del enunciado:
-Cada restaurante va a tener una tabla de segmentos propia.
-Cada segmento de esa tabla va a ser un pedido, y a su vez, va a contener paginas.
- Cada pagina, va a hacer referencia a una comida (nombre, cantidad total y cantidad ya preparada).

En cuanto al mensaje guardar pedido, seguria los siguientes pasos:
1- Comanda recibe el nombre del restaurante y el id del pedido.
2-Busca si ese restaurante ya existe y tiene su tabla de segmentos ya creada.
3_a - En caso de que no existe ese restaurante, se crea la tabla de segmentos.
3_b - En caso de que ya existe, se empezara a trabajar directamente sobre la misma.
4 - Busca si en la tabla de segmentos, hay un pedido (segmento) con el mismo ID.
5_a - En caso de que ya existe, informara el error.
5_b - En caso de no existir, crea el segmento y lo agrega a la tabla con su respectivo ID.
6 - Se responde que se logro realizar la operacion. 

Esto es lo que considero como los pasos que se deberian seguir, pero hay partes del enunciado que no coindicen con esta idea, y a su vez se contradicen entre si. 

> "Cada restaurante tiene su propia tabla de segmentos, donde **cada segmento es un pedido**. Este último, tiene un conjunto de páginas asociadas al pedido donde se guardaran los ítems del mismo."

> "1.Verificar si existe la tabla de segmentos de dicho Restaurante. Si la tabla de segmentos no existe, deberá ser creada. En caso de no poder crearla, se deberá informar dicha situación. 
2.Luego, se procederá a acceder a la tabla de páginas del segmento seleccionado previamente, y **se agregara en la última página disponible de la misma el nuevo pedido**."

En la primer parte referenciada del enunciado indica que cada segmento es un pedido, y que cada uno de esos pedidos va a tener paginas asociadas. Mientras que en la segunda parte, me indica, o por lo menos asi lo entiendo yo, que para guardar el nuevo pedido, tengo que agregarlo en una pagina. 
Calculo que debe ser un error del enunciado.

Espero haber podido explicar en forma entendible mis dudas. Gracas

**Comment by ncoen97** [comment]
Buenas.
El flujo que describiste vos es correcto, solo le faltaría en el paso 5_b crear la tabla de páginas de ese segmento. Con respecto al enunciado, la parte que dice "y se agregara en la última página disponible de la misma el nuevo pedido" no está bien y vamos a arreglarlo para la próxima errata.
Gracias y saludos!

**Comment by RodrigoLista** [comment]
Muchas Gracias. Cierro el Issue
