### ISSUE TITLE
Mensaje "consultar restaurantes" - trayecto desde App hasta Restaurante.

### ISSUE THREAD

**Issue by fedexenrrique** [sisoputnfrba/foro#1919]
👋 ¡Hola!

Tengo una duda respecto del mensaje de "consultar restaurantes", debido a que no vi ningún mensaje desde Restaurante hacia App en el que el Restaurante avise su nombre para que App lo incorpore a su listado de restaurantes presentes.

¿Esta bien si en la conexión inicial del Restaurante a la App incluyo toda la metadata del Restaurante, desde ubicación hasta nombre?

Espero su respuesta, saludos utnianos.

**Comment by ncoen97** [comment]
Buenas @fedexenrrique !
A que respuesta llegaste? Te parece dejar tu conclusión así si alguien tiene la misma consulta puede tener una respuesta?
Gracias y saludos :)

**Comment by nico-abram** [comment]
Buenas!

Venia a hacer la misma consulta, abro otro issue ya que este esta cerrado?

**Comment by ncoen97** [comment]
Buenas, para estos casos donde se necesita información inicial y no hay ningún mensaje para obtenerla, pueden enviarla al iniciar la conexión. Saludos!

**Comment by MaSosa314** [comment]
Con respecto a esto. Cuando un restaurante le manda su info a la App. ¿Es necesario que mantengamos abierta la conexión entre el Restaurante y la App?¿O podemos mandarle en la info el host y puerto de escucha del restaurante a la App y cerrar la conexion?

Saludos

**Comment by iago64** [comment]
@MaSosa314 lo importante es que los mensajes puedan ir y venir sin problemas, si a uds les resulta mas facil ir creando y cerrando sockets pueden hacerlo.
En el caso de la comunicación Restaurante - App les dimos la recomendación de 2 sockets como para que se sientan libres de pensar como hacerlo sin limarse las neuronas pensando en como hacerlo con 1 solo socket 😉 

Abrazo a la distancia.-
