### ISSUE TITLE
Comanda - Guardar Plato

### ISSUE THREAD

**Issue by RodrigoLista** [sisoputnfrba/foro#1920]
Buenas. Tengo una duda respecto a la recepción del mensaje guardar plato.

> "1.Verificar si existe la tabla de segmentos de dicho Restaurante. En caso de no existir se deberá informar dicha situación.
2.Verificar que exista el segmento de dicho pedido dentro de la tabla de segmentos del Restaurante. En caso de no existir se deberá informar dicha situación.
3.Verificar si existe el plato dentro de la tabla de páginas del pedido. En caso contrario, se deberá asignar una nueva página al segmento. 
4.En caso de que la página que corresponde al pedido no se encuentre cargada en memoria principal, se deberá cargar la misma desde swap (iniciando la elección de víctima de ser necesario). En caso contrario, proceder al paso  número 4.
5.Se deberá agregar el plato y anexar la cantidad que se tiene que cocinar de dicho plato.
6.Responder el mensaje indicando si se pudo realizar la operación correctamente (Ok/Fail)."

Quería consultar, respecto al punto 3. En caso de que ya exista el plato en el pedido. Que es lo que tendria que hacer?
-Informar error.
-Unir el plato existente con el nuevo (sumar la cantidad existente del plato, a la cantidad que se esta recibiendo).

Muchas gracias

**Comment by ncoen97** [comment]
Buenas, en el caso de que el plato ya exista se debe sumar la cantidad a la que ya se encuentra en memoria. Saludos!

**Comment by RodrigoLista** [comment]
Muchas gracias. Cierro Issue.
