### ISSUE TITLE
Consultas mensajes anexo 1 obtener/consultar pedido y seleccionar restaurante

### ISSUE THREAD

**Issue by nico-abram** [sisoputnfrba/foro#1921]
Buenas!

Tenia un par de dudas sobre algunos mensajes

1) Seleccionar restaurante: Que seria el "cliente" que recibe? Se podria identificar a un cliente como la conexion por la que llega el mensaje y no tener ese campo?
2) Consultar pedido: Que seria "estado"? Pendiente (Agregando platos), Confirmado (En progeso) y Terminado (Todos los platos listos)? Para estar seguro porque tambien hay "estados" de la planificación
3) Obtener Pedido: No deberia retornar el estado? Creo que la app podria inferir si esta cocinado el pedido con las cantidades, pero no tendria manera de saber si esta Pendiente o Confirmado si no lo recibe de comanda, si es que entendi bien

Gracias y que tengan un buen domingo!

**Comment by ncoen97** [comment]
Buenas.

1. En este punto el tema de identificar al cliente por la conexión creo que dependería un poco de cómo ustedes hagan sus conexiones, pero lo que me parece mejor es que le asignen algún id, nombre o algo que lo identifique al cliente.
2. El estado es el del pedido, tengan en cuenta que el estado de planificación no debería interesarle al cliente que use la app.
3. Si, está anotado para que quede arreglado para la siguiente errata.

Saludos y buena semana!

**Comment by nico-abram** [comment]
Muchas gracias!
Cierro issue, buena semana!
