### ISSUE TITLE
archivo configuración repartidores

### ISSUE THREAD

**Issue by lisandro-iraguen** [sisoputnfrba/foro#1922]
una consulta
el archivo de configuración para el modulo APP da como ejemplo esto

REPARTIDORES=[1|1,5|2,1|4]
FRECUENCIA_DE_DESCANSO=[8,5,10]
TIEMPO_DE_DESCANSO=[2,1,4]

supongo que levanto del archivo los repartidores y sus tiempos, la pregunta es
REPARTIDORES=[1|1,5|2,1|4], esto son coordenadas X,Y? 

 repartidor 1: (1,0)-> frecuencia de descanso 8 -> tiempo de descanso ->2
 repartidor 2: (1,5)-> frecuencia de descanso 5 -> tiempo de descanso ->1
 repartidor 3: (2,1)-> frecuencia de descanso 10 -> tiempo de descanso ->4
 repartidor 4: (4,0)-> acá no se que va? 0? el repartidor ese va?

saludos y gracias

**Comment by ncoen97** [comment]
Buenas, como bien decís son coordenadas (X,Y), pero me parece que no las leíste de forma correcta porque tenés un repartidor demás 🤔. Las comas separan a los repartidores y los pipes los valores de X|Y, quedarían de la siguiente forma:

repartidor 1: (1,1)-> frecuencia de descanso 8 -> tiempo de descanso ->2
repartidor 2: (5,2)-> frecuencia de descanso 5 -> tiempo de descanso ->1
repartidor 3: (1,4)-> frecuencia de descanso 10 -> tiempo de descanso ->4

Saludos!

**Comment by lisandro-iraguen** [comment]
ahh es verdad, tenes razón. saludos!

**Comment by ncoen97** [comment]
Para la próxima cuando ya no tengas mas consultas podes también cerrar el issue 😉

**Comment by lisandro-iraguen** [comment]
si perdon, queria estar seguro!
