### ISSUE TITLE
⚽ ⚽ Mercado de Pases - Busca completar tu equipo ⚽ ⚽ 

### ISSUE THREAD

**Issue by iago64** [sisoputnfrba/foro#1923]
Buenas! 
La idea de este post es canalizar todas las búsquedas de integrantes / grupos en los casos de bajas que sucedan durante el cuatrimestre.

📆 Recuerden que la fecha limite es el Sábado 24/10 📆 

🕙 Por favor recuerden que las bajas / cambios demoran 72Hs en aplicarse 🕙 

Saludos.-

**Comment by costaelias** [comment]
buenas, busco un integrante para el tp, si alguno anda sin grupo que me avise eliazcost@gmail.com
saludos.

**Comment by maurolaurenzi** [comment]
Hola! Estamos buscando un integrante para el TP. Cualquier cosa avisen a maurodlaurenzi@gmail.com

**Comment by jloffredo** [comment]
Buenas! Buscamos 1 integrante para el grupo, estamos haciendo el proyecto en vscode, trabajando el git con branches y pull requests. Usamos slack y trello para organización, con eventuales calls algún sábado si hace falta. Estamos trabajando ya tareas para el hito 2. Interesados manden mail a jloffredo@gmail.com

**Comment by jloffredo** [comment]
Buenas! Buscamos 2 integrantes para el grupo, estamos haciendo el proyecto en vscode, trabajando el git con branches y pull requests. Usamos slack y trello para organización, con eventuales calls algún sábado si hace falta. Estamos trabajando ya tareas para el hito 2. Interesados manden mail a jloffredo@gmail.com

**Comment by carotiferes** [comment]
Hola! Buscamos un/a integrante para el TP, estamos usando vscode. Si te interesa avisame a carotiferes@gmail.com

**Comment by fd95i** [comment]
Buenas tardes, buscamos integrante para el TP. En este momento estamos con tareas del hito 2 y 3. Dejo mi mail: federicon35@gmail.com

**Comment by FeroMateo** [comment]
Hola buscamos 1 integrante del TP, estamos empezando el hito 3 y desarrollamos en eclipse. Cualquier cosa feromateo@gmail.com

**Comment by GasparAdragna** [comment]
Hola buscamos 1 integrante el TP. Estamos usando eclipse. Cualquier cosa gaspar.jac@hotmail.com

**Comment by ezchain** [comment]
Buenas, buscamos un integrante para el tp, estamos empezando las tareas de la entrega 3 y tenemos el sindicato casi terminado. Estamos usando VS Code. Mi mail es ezequielechain@gmail.com

**Comment by hugoguarneri** [comment]
Hola, estamos buscando un integrante para el TP. Estamos empezando el hito 3 y tenemos casi terminado el sindicato.
Mi mail es hugoguarneri@gmail.com

**Comment by andresparada** [comment]
Hola, necesitamos 2 integranes tp, ya estamos liquidando el hito 3, mi mail es: aparada@est.frba.utn.edu.ar

**Comment by foviedo** [comment]
Buenas, necesitamos un integrante, tenemos el hito 3 en desarrollo. Mi mail es oviedoee@yahoo.com

**Comment by nubevi** [comment]
¡Buenas tardes gente!
Andamos buscando 1 integrante que quiera participar en el desarrollo del TP. Actualmente estamos finalizando el Hito 3.
Cualquier duda, me pueden contactar en: guido.n.b@outlook.com.ar :)

**Comment by cecicollazo** [comment]
Buenas! Somos dos chicas y buscamos grupo. Tenemos intenciones de meterle al TP! Dejo mi mail: ceciliacollazo8@gmail.com

**Comment by Aeiroa** [comment]
Hola! Necesitamos a un integrante por bajas. Estamos a mediados del hito 3. Cualquier cosa mandame un mail: eiroa.ailen@gmail.com 

Queremos aprobarla si o si.

**Comment by SantiagoIvan** [comment]
Hola ! Se nos fue uno. Vamos por el hito 3. Cualquier cosa mandenme un mail a santiago.feijoo96@gmail.com

**Comment by ericvilladeza** [comment]
Hola, me estoy dando de baja por temas personales y busco un reemplazo, con ganas de meterle al tp, una vez arreglado la integración al equipo le voy a estar explicando todo lo hecho por mi para que me reemplace y pueda trabajar inmediatamente, cualquier cosa manden un mail a ericvilladeza@gmail.com brianarielrosenbolt@gmail.com; rochabelardinellic@gmail.com; ronidiam16@gmail.com lucasarias2@hotmail.com, o un wpp 1535936854

**Comment by NicolasEZD** [comment]
Buenas, estoy solo buscando un grupo, curso los sábados a la mañana, curso K3521. Mi mail es nicolasezequieldiaz@gmail.com

**Comment by IESTomasAraujo** [comment]
hola, estamos buscando 1 integrante mas para mi grupo, estamos por el hito 3. cualquier inquietud por favor comunicarse a mi mail: tomasaraujo1999@hotmail.com

**Comment by nramrezmoreale** [comment]
Buenas, somos 2 chicos y buscamos armar grupo, ya tenemos parte del tp avanzado. + Info: nicolasrm97@gmail.com

**Comment by Rama054** [comment]
Hola gente, andamos buscando un integrante para completar el grupo. Estamos avanzados en la mayoria de modulos, excepto por restaurante. Llegamos comodos al checkpoint pasado. 
Cualquier persona que este sin grupo y tenga ganas de trabajar es bienvenido. Cualquier consulta, mandar un whatsapp al 11-3006-5772

**Comment by kamipalomino** [comment]
Buen día ando buscando grupo, me encontraba desarrollando el Sindicato pero me puedo poner con cualquier otro módulo que necesiten, la cursé hace unos años así que algo de experiencia tengo programando.
Cualquier consulta, mandar un mail cpalomino@est.frba.utn.edu.ar  o Whatsapp 01133394036

**Comment by facufl23** [comment]
Buen dia. Estamos buscando un integrante para completar el grupo. Estamos ya bastante avanzados. Cualquier consulta, mandar un whatsapp al 1161132312

**Comment by Yamil2017** [comment]
Buenas, estoy buscando algún grupo con vacante disponible. lopezyamil1983@gmail.com. Saludos.

**Comment by JuaniPS** [comment]
Buenas. Estoy buscando grupo. Es la primera vez que curso la asignatura, y hay varias cosas que aún no entiendo. Pero es por eso que quiero aprender y trabajar el tiempo necesario. No busco que me regalen el TP.
Mi mail es: juanips.jips@gmail.com.
¡Saludos!

**Comment by nicolascalle** [comment]
Buenas, estoy buscando grupo. Si alguno tiene vacante puede enviarme un mail a: callenicolasg@gmail.com. Estoy recursando la materia y tengo el primer parcial aprobado.

**Comment by iago64** [comment]
Cerrado oficialmente el mercado de pases, a partir de este momento solo se permitiran bajas de integrantes en los grupos.
