### ISSUE TITLE
Duda mensaje Crear Pedido

### ISSUE THREAD

**Issue by MaSosa314** [sisoputnfrba/foro#1925]
Buenas. Tengo una duda con el mensaje Crear Pedido.

En el Anexo la especificación de este mensaje muestra que no tiene payload. Pero mi duda es. Si desde un modulo Cliente mando este mensaje a la App. ¿Como se a que restaurante tengo que mandar el mensaje Crear Pedido si no le indico en el mensaje que cliente soy?

Saludos.

**Comment by MaSosa314** [comment]
Hola de nuevo.

Esta duda tambien me surge con otros mensajes. Como por ejemplo **AñadirPlato** o **ConfirmarPedido**. Se me ocurre que esto se puede resolver identificando a un cliente por la conexion que se encuentra abierta. Pero en ese caso, no entenderia cual es el objetivo de que **SeleccionarRestaurante** reciba el nombre del cliente si ya lo identificamos por la conexion que se encuentra abierta entre la App y el Cliente.

Saludos.

**Comment by RaniAgus** [comment]
Buenas! Me sumo a la duda con una interpretación que, de todas formas, me genera interrogantes:

a) Supongo que para el momento en el que el Cliente envía el mensaje "Consultar Restaurantes" (sería al inicio de todo), no tiene mucho sentido que la App ya sepa de antemano los datos del Cliente, ya que por ahora no le sirven de nada (no se crearon pedidos, no hay repartidores que planificar, ni nada).

b) Supongo que cuando el Cliente envía "Seleccionar Restaurante", ahí sí envía sus datos (como se explica en el Anexo I), para que la App vincule Cliente con Restaurante y que, de esa forma, se puedan enviar los siguientes mensajes.

c) El mensaje "Crear Pedido" se usa con la vinculación previa mediante "Seleccionar Restaurante", y devuelve un ID que sirve para enviar los siguientes 3 mensajes.

d) Los mensajes "Añadir Plato", "Confirmar Pedido" y "Consultar Pedido" se envían con el ID recibido en "Crear Pedido", y la App internamente aprovecha la vinculación previa mediante "Seleccionar Restaurante".

A raíz de esta interpretación, me surjen un par de dudas:

1) ¿El Cliente tiene que "Seleccionar Restaurante" para el restaurante default? ¿O se tiene que deducir que, como no hay ningún Restaurante conectado, todas las solicitudes/consultas que entren a la App son hacia este "Restaurante"?

2) Nosotros estaríamos abriendo un socket por cada solicitud/consulta en donde se espera una respuesta sincrónica, entonces, ¿cómo le pasamos a la App la información de "quién soy" si cada mensaje tiene una interfaz definida? Además de que ese "quién soy" solo sirve para la App, porque al resto de módulos no les interesa, por lo que estaríamos rompiendo el polimorfismo al tratar a cada módulo en forma distinta.

3) ¿Cómo enviamos ese "quién soy" a través del primer socket de todos, el que abrimos para recibir notificaciones asincrónicas, como "Finalizar Pedido"?

Saludos!

**Comment by ncoen97** [comment]
Buenas, me parece que estas consultas quedan respondidas con el hanshake inicial que se le agregó a los mensajes.
@RaniAgus No entendí la pregunta 3 🤔
Ya saben que si les quedan más dudas pueden seguir consultando.
Saludos!

**Comment by MaSosa314** [comment]
Buenas. Creo que lo que @RaniAgus quizo decir (y si no es esto lo que preguntaba, es una duda mia) es: en el TP se sugiere que usemos dos sockets en el cliente. Uno que sea para enviar las solicitudes y otro que sea de escucha (un socket servidor) donde recibimos las notificaciones de la actualización de un pedido. El problema es que no tengo manera de decirles a los otros modulosa en que ip y puerto esta escuchando el cliente. Y en el handshake que agregaron solo estariamos mandando el id de cliente y la posicion.

Saludos.

**Comment by MaSosa314** [comment]
Luego, siguiendo con la tematica original, me sigue quedando la misma duda que puse al principio. **AñadirPlato**, **ConfirmarPedido**, **ConsultarPedido** y **CrearPedido** no tienen ni el nombre del restaurante ni el id del cliente como parametros, por lo que la **App** no tiene forma de saber a que restaurante enviar el mensaje.

De igual manera, si lo que estoy mencionando no es un error y esta duda está mas ligada a que yo no estoy viendo como implementar el tema de estos mensajes, haganmelo saber. Solo quiero asegurarme de que no falta info en esos mensajes.

Saludos.

**Comment by RaniAgus** [comment]
> Buenas. Creo que lo que @RaniAgus quizo decir (y si no es esto lo que preguntaba, es una duda mia) es: en el TP se sugiere que usemos dos sockets en el cliente. Uno que sea para enviar las solicitudes y otro que sea de escucha (un socket servidor) donde recibimos las notificaciones de la actualización de un pedido. El problema es que no tengo manera de decirles a los otros modulosa en que ip y puerto esta escuchando el cliente. Y en el handshake que agregaron solo estariamos mandando el id de cliente y la posicion.

En realidad sí se podría, si no me equivoco la función se llama `gethostbyname()` (o parecido, estaba en el Beej). Y la App debería hacer `getpeerbyname()` con cada cliente que tenga conectado. Para obtener IP y Puerto se usaría `getaddrinfo()`.

De todas formas, utilizar el ID de Cliente en el handshake como se propone hace que el proceso de identificación sea muuuuuucho menos engorroso jajaj

> Luego, siguiendo con la tematica original, me sigue quedando la misma duda que puse al principio. **AñadirPlato**, **ConfirmarPedido**, **ConsultarPedido** y **CrearPedido** no tienen ni el nombre del restaurante ni el id del cliente como parametros, por lo que la **App** no tiene forma de saber a que restaurante enviar el mensaje.
> 
> De igual manera, si lo que estoy mencionando no es un error y esta duda está mas ligada a que yo no estoy viendo como implementar el tema de estos mensajes, haganmelo saber. Solo quiero asegurarme de que no falta info en esos mensajes.

Creo que no tienen nombre de restaurante ni ID de cliente porque el restaurante se selecciona enviando "Seleccionar Restaurante". Entonces, cuando se envíe uno de estos 3 mensajes, la App se debe fijar qué restaurante se seleccionó antes, y enviarle el mensaje a ese.

> Buenas, me parece que estas consultas quedan respondidas con el hanshake inicial que se le agregó a los mensajes.
> @RaniAgus No entendí la pregunta 3 thinking
> Ya saben que si les quedan más dudas pueden seguir consultando.
> Saludos!

@ncoen97 Era porque en ese momento no habíamos pensado muy bien el tema de identificar cada cliente, con el handshake se resuelve ya que (si mi interpretación no es errónea) debemos enviarlo después de cada `connect()` y antes de cada consulta (igual que para el primer socket que recibe notificaciones).

Gracias y saludos!

**Comment by ncoen97** [comment]
> Buenas. Creo que lo que RaniAgus quizo decir (y si no es esto lo que preguntaba, es una duda mia) es: en el TP se sugiere que usemos dos sockets en el cliente. Uno que sea para enviar las solicitudes y otro que sea de escucha (un socket servidor) donde recibimos las notificaciones de la actualización de un pedido. El problema es que no tengo manera de decirles a los otros modulosa en que ip y puerto esta escuchando el cliente. Y en el handshake que agregaron solo estariamos mandando el id de cliente y la posicion.

@MaSosa314 Ojo que el hecho de que tengan un socket de escucha no implica que tengan que levantar un servidor en el cliente. Lo que deberían hacer es iniciar una conexión desde el cliente y de alguna forma (por ejemplo con un código de operación) informarle al servidor que ese socket va a ser de escucha.

@RaniAgus Perfecto!

**Comment by RaniAgus** [comment]
Vuelvo porque tengo la misma duda que planteó al principio @MaSosa314 sobre los campos del mensaje Seleccionar Restaurante, que al parecer no los cambiaron con la nueva versión: ¿hace falta que reciba _de nuevo_ el Cliente? ¿No se resolvería ya con el hanshake previo a cada `connect()`?

**Comment by wormeno** [comment]
Hola,
   Con respecto a la siguiente respuesta:
> 
> @MaSosa314 Ojo que el hecho de que tengan un socket de escucha no implica que tengan que levantar un servidor en el cliente. Lo que deberían hacer es iniciar una conexión desde el cliente y de alguna forma (por ejemplo con un código de operación) informarle al servidor que ese socket va a ser de escucha.
> 

  Cuando dice "... No implica que tengan que levantar un servidor en el cliente." Entonces ¿El cliente debe quedarse esperando la respuesta al mensaje que envió?

**Comment by ncoen97** [comment]
Buenas.

@wormeno Exacto, con "esperando" me imagino que te referís a un `recv()`, dependiendo de cada implementación puede ser sobre el mismo socket por el cual se envió la consulta o sobre un socket especifico para las respuestas.

@RaniAgus Lo tenemos en cuenta para la próxima errata 👍 

Saludos!

**Comment by RaniAgus** [comment]
Buenísimo, por mí pueden cerrar el issue
