### ISSUE TITLE
Problema con list create

### ISSUE THREAD

**Issue by AgustinDeCesare** [sisoputnfrba/foro#1926]
Tenemos una lista declarada en un archivo utils_app.h que esta incluido en el archivo main y en un archivo de planificacion, hacemos un list_create en el main con la funcion inicializar_modulo, con el debugger vemos que en ese momento la lista se crea con 0 elementos.

Pero el problema es cuando creamos el pcb en el archivo de planificacion y queremos agregarlo a la lista, rompe la funcion list_add y viendo el debbug aparece que la lista no esta inicializada en ese momento

App.c

```
void inicializar_modulo(void) {

	logger = iniciar_logger();	//Carga el logger
	leer_config();	//Carga las config
	id_pcb = 0;

	restaurantes_conectados = list_create();
	lista_pcbs = NULL;
	lista_pcbs = list_create();
	cola_block = queue_create();
	cola_new = queue_create();
	cola_ready = queue_create();
	cola_exec = queue_create();
	cola_exit = queue_create();
```

Ahi la inicializamos

planificacion_app.c

```
void crear_pcb(int id_pedido, posicion posicion_restaurante){
	printf("CREANDO PCB");
	t_pcb* nuevo_pcb = malloc(sizeof(t_pcb));
	nuevo_pcb->estado = NEW;
	nuevo_pcb->id_pedido = id_pedido;
	nuevo_pcb->id_pcb = id_pcb++;
	nuevo_pcb->posicion_restaurante = posicion_restaurante;
	nuevo_pcb->repartidor = NULL;

	list_add(lista_pcbs, nuevo_pcb);
	// agregar semaforos
	queue_push(cola_new, nuevo_pcb);
}
```

Y ahi cuando hacemos el list add ya no aparece inicializada

Puede ser algun problema con el .h donde esta declarada?

**Comment by nico-abram** [comment]
Puede ser que al declarar la variable en el .h incluido de ambos archivos se esten declarando 2 variables globales separadas con el mismo nombre?

Capaz hay que declararla como "extern list_t* lista_pbcs;" y en un solo .c definir la variable "list_t* lista_pcbs;"

No estoy seguro igual, disculpa si estoy diciendo cualquiera

Suerte!

**Comment by iago64** [comment]
Aloha! como va?

Una pregunta importante, tienen el `#ifndef` al principio del .h? porque capaz se te están pisando las declaraciones con otro .h y bueno, ahí es cuando el compilador se pone realmente mala leche :(

Abrazo a la distancia!

P.D: En lugar de printf usen los loggers que son mas copados y pueden imprimir tanto por pantalla como por archivo 😉

**Comment by AgustinDeCesare** [comment]
Si tenemos el ifndef

#ifndef SRC_UTILS_APP_H_
#define SRC_UTILS_APP_H_

Y los printf ya los cambiamos por loggers
