### ISSUE TITLE
añadir plato

### ISSUE THREAD

**Issue by vivasjm** [sisoputnfrba/foro#1927]
Vi que ya preguntaron esto y que esta en revision... pero quiero saber si hay algun update al respecto. 

Mi duda vienen en relación a la cantidad del plato que debemos enviar del restaurante al sindicato cuando ejecutamos el mensaje GUARDAR PLATO en consecuencia de la recepción de AÑADIR PLATO, este ultimo no trae como parámetro la cantidad de comida, dato que si requiere el mensaje GUARDAR PLATO pero no esta especificado en ningún lugar.

Simplemente incrementamos en 1 la cantidad del plato en cuestión?

muchas gracias.

**Comment by iago64** [comment]
Buenas! como va?

Mañana tarde / noche posiblemente estemos publicando la errata al respecto, estamos viendo la mejor forma de hacerlo para que sea mas facil para uds testearlo.

Abrazo a la distancia!

**Comment by vivasjm** [comment]
gracias espero la nueva version entonces
