### ISSUE TITLE
Consultar Platos

### ISSUE THREAD

**Issue by vivasjm** [sisoputnfrba/foro#1930]
Una consulta respecto a este mensaje. Por lo que entiendo lo envia la APP al Restaurante, este ultimo le pide al Sindicato todos las comidas con sus cantidades totales/listas.

cuando el restaurante recibe dicha informaciòn del sindicato, que hace con ese mensaje? se lo pasa a la APP? en el enunciado dicen que el modulo app servira de "pasamanos" pero a mi me parece que el pasamanos es el restaurante en este caso

Entiendo que el restaurante no hace nada ma que pedirle las comidas al sindicato y devolverselos tal y cual se lo paso el sindicato al modulo app

**Comment by ncoen97** [comment]
Buenas.
En realidad el rol de la App y del Restaurante en este caso es bastante similar, ambos reciben una consulta que envían a otro modulo y responden la respuesta recibida (independientemente si se lo pidió la app, el cliente o quien fuere).
Saludos.

**Comment by vivasjm** [comment]
gracias
