### ISSUE TITLE
Conexiones modulo APP & Restaurante

### ISSUE THREAD

**Issue by vivasjm** [sisoputnfrba/foro#1931]
Consulta, por cada restaurante solo se va a conectar 1 solo modulo APP no? es decir hay una relacion 1:1 en app:restaurante?

gracias

**Comment by ncoen97** [comment]
Buenas, en realidad la relación App:Restaurante es 1:n, siendo n la cantidad de instancias de restaurante que tengan levantadas.
Saludos.

**Comment by vivasjm** [comment]
Gracias
