### ISSUE TITLE
Duda Consultar Platos

### ISSUE THREAD

**Issue by MaSosa314** [sisoputnfrba/foro#1932]
Buenas.

Tengo una duda con este mensaje. En el anexo dice:

```
Descripción: la App consultara los platos de un Restaurante específico, quien obtendrá los
mismos enviando el mensaje ‘ConsultarPlatos’ al módulo Sindicato, encargado de consultar
en sus archivos la información actualizada de los platos.
```
La descripción en un momento me dio a entender que lo que hacia este mensaje era devolverme los platos disponibles del restaurante. Pero en lo que retorna el mensaje esta esto:

```
Retorna: [{comida1, cantTotal1, cantLista1}, {comida2, cantTotal2, cantLista2}, ...]
```

Esto querría decir que en verdad el mensaje consulta sobre los estados actuales de los platos de un pedido en específico. Si esto es asi. ¿No debería **ConsultarPlatos** recibir tambien el id del pedido? Ya que en los parametros que recibe este mensaje solo se especifica el Restaurante.

Saludos.

**Comment by vivasjm** [comment]
Yo creo que tambien es otro error, si te pones a mirar el mensaje CONSULTAR PLATOS es similar a OBTENER PEDIDO, ambos retornan una cadena como

[{comida1, cantTotal1, cantLista1}, {comida2, cantTotal2, cantLista2}, ...]

tal vez la diferencia es que consultar platos se obtenien el  detalle del 100% de los platos, de todos los pedidos (con su cantidad total y lista) de lo que esta activo en el restaurante en cuestion y obtener pedido solo el detalle de un pedido particular

creo yo que lo mejor hubiese sido que consultar plato solamente devuelva el nombre del plato (milanesas, pizzas, etc) sin el detalle de la cantidad total y lista. Y obtener pedido deberia tener el detalle de cantidad lista y total de un pedido en particular

**Comment by ncoen97** [comment]
Buenas, arreglamos el retorno de consultar platos en la última errata, me parece que con eso la duda queda resulta.
Cualquier cosa no duden en seguir consultando.
Saludos!

**Comment by MaSosa314** [comment]
Si. Perfecto. Por mi parte pueden cerrar el issue.

Saludos.

**Comment by iago64** [comment]
@MaSosa314 no te olvides que vos también podes cerrar los issues :)
