### ISSUE TITLE
Cambio de valor de una posición de memoria del heap por motivo desconocido

### ISSUE THREAD

**Issue by julchat** [sisoputnfrba/foro#1933]
Hola, me pasa algo que no se como solucionar:

Tengo el siguiente código:

t_list* modulosCompatibles = list_create();

obtenerModulosCompatiblesYCantParametrosRequerida(codigoOperacion, moduloDestino, &modulosCompatibles, &cantParametros);

mientras hago debug para ver que partes funcionan como esperado y cuales no, veo que modulosCompatibles fue cargado correctamente y, el puntero del head apunta a 0xb7d772d0, con el valor SINDICATO

Luego, llamo a la función  validarSemanticaMensaje(modulosCompatibles, cantParametros, moduloDestino, parametros), para que valide que moduloDestino, que en este caso será SINDICATO, está incluido en la lista de modulosCompatibles.

El tema, es que cuando entro a la función 

```
bool validarSemanticaMensaje(t_list* modulosCompatibles, int cantParametros, t_dest destinatario, t_list* parametros){
	if(!(cantParametros == parametros->elements_count)){
		printf("SE ESPERABA QUE EL MENSAJE TENGA %d PARAMETROS, Y TUVO %d PARAMETROS", cantParametros,parametros->elements_count);
		return 0;
	}
	bool estaElDestEnLosCompatibles(t_dest* unModuloDeLaLista){
		return *unModuloDeLaLista == destinatario;
	}

	if(!(list_any_satisfy(modulosCompatibles, (bool*) estaElDestEnLosCompatibles))){
		printf("EL MENSAJE NO SE PUEDE MANDAR AL MODULO ESPECIFICADO");
		return 0;
	}
		return 1;

}
```

Cuando entro a dicha función, el valor de 0xb7d772d0 cambia a un número cualquiera (probablemente basura)
Curioso que si borro la linea de list_any_satisfy(modulosCompatibles, (bool*) estaElDestEnLosCompatibles, 0xb7d772d0 sigue apuntando a SINDICATO.

Pense que era una cuestión de que estaba apuntando a una posición del stack, y que el stack al cambiar de función es distinto. Pero esa información debería estar en el heap no? Puesto que list_add hace un malloc del elemento.

Nada, si tienen idea me avisan.

Saludos, gracias
Cristian

**Comment by ncoen97** [comment]
Buenas, como bien decís list_add reserva el espacio necesario para esa lista, por lo tanto está en el heap. Lo que no llego a ver en el código si están teniendo en cuenta es que list_add reserva el espacio para la lista pero no para los elementos, por lo que a cada elemento deberían hacerle primero un malloc.
Fíjense eso y cualquier cosa lo seguimos viendo.
Saludos!

**Comment by iago64** [comment]
Solo para sumar algo sobre lo que dice Nico, capaz si le pasas Valgrind te encuentres con alguna lectura / escritura invalida de memoria y que puede venir asociada al error que estas teniendo, por las dudas revisate el video de valgrind que tenemos en el canal de youtube.

Abrazo a la distancia!

**Comment by julchat** [comment]
está! gracias! de paso después de corregir lo que estaba mal corrí el valgrind y respecto a eso no mostraba nada, gracias!
