### ISSUE TITLE
Consultar Plato

### ISSUE THREAD

**Issue by SantiagoIvan** [sisoputnfrba/foro#1934]
Se que había issues sobre ésto pero no me quedaron claras las respuestas y ya fueron cerrados.

Cuando un cliente consulta un plato a la App, hace de pasamano y le envía el mensaje consultar platos al Restaurante seleccionado.
Luego el Restaurante le envía el mensaje Consultar Platos al Sindicato y éste  (según lo que dice el enunciado) le devuelve los platos que sabe hacer.
Por otro lado, En el Anexo dice que devuelve una lista de { comida 1 , cant Total1 , Cant Lista 1}. Mi duda es la siguiente. En ningún lado estamos devolviendo el precio del plato. Supuestamente en un issue ( https://github.com/sisoputnfrba/foro/issues/1905 ) que preguntaban lo mismo un ayudante dijo que iba a subir una 'errata' (que no se qué es y no se si se subió) con esas consideraciones, pero no veo ninguna errata ni nada. Yo lo que tengo es la versión 1.1 del enunciado y no está nada respecto a eso.
También es raro devolver un cant Total y cant Lista cuando simplemente estoy consultando los platos que sabe hacer el restaurante y sus precios para ver cual comprar, o mejor dicho cuál añadir al pedido más adelante. Yo pensaba que se retornaba el 'Platos' y 'Precio_Platos' que está en el info.afip, eso me parece que tiene más sentido. ¿Qué hago?

**Comment by ncoen97** [comment]
Buenas, una errata le llamamos a una nueva versión del TP donde arreglamos distintos puntos del enunciado que quedaron con errores/mal redactados/etc. Ayer por la tarde actualizamos a la versión 1.2 donde una de las cosas que arreglamos es el retorno de la función consultar platos. Me parece que el tema del precio del pedido en la app nos quedó pendiente 😕

**Comment by ncoen97** [comment]
Cierro el issue, el tema del precio que quedó pendiente queda centralizado en el #1929
