### ISSUE TITLE
Guardar Pedido

### ISSUE THREAD

**Issue by SantiagoIvan** [sisoputnfrba/foro#1935]
El enunciado dice que el id del pedido lo genera el Restaurante y debe ser único para cada uno de ellos. La interfaz, en el Anexo I dice que la firma de Guardar pedido es Guardar_Pedido ( restaurante, id_pedido ). El tema es que con ese ID, el Sindicato no hace nada. Es más, en la sección del Sindicato dice lo siguiente respecto a qué guardar de cada pedido:
"Pedidos
Dentro del archivo de cada pedido se deben almacenar los siguientes campos:
● Estado_Pedido: Indica el estado del pedido. Puede ser Pendiente/Confirmado/Terminado.
●Lista_Platos : es un array que indica las recetas que se deben preparar.
●Cantidad_Platos : es un array que indica la cantidad la cantidad de cada receta que se deben preparar.
●Cantidad_Lista : es un array que indica la cantidad de cada receta que ya se encuentra lista.
●Precio_Total : indica el precio total del pedido
."
No veo un campo id_pedido, lo recibe por parámetro y no hace nada, lo más cercano a un id es crear un Archivo Pedido{i} siendo i contador de pedidos para un restaurante dado. Ejemplo, si el último pedido guardado es el Pedido4, crea un archivo Pedido5. Pero ese contador de pedidos no es el id_pedido, o si? En dicho caso no lo estaría generando el restaurante sino el Sindicato. Qué hago con el id que le envía el restaurante al Sindicato? El sindicato tiene el historial de pedidos de cada restaurante, como sabe el Restaurante que el id_pedido generado es único?

**Comment by iago64** [comment]
Buenas! como va?

Estas seguro seguro que no hace nada? Que no lo tengas en los campos del archivo, no significa que no sirva de nada, acordate que los archivos de pedidos se guardan dentro del restaurante en el FS, capaz nos falto aclarar que los archivos de los pedidos van a responder a la logica:

`[Punto_Montaje]/Files/Restaurantes/Pedido[ID_Pedido]`

Por lo que el ejemplo del enunciado tienen guardados los pedidos 1 y 2 del Resturante 1

```
[Punto_Montaje]/Files/Restaurantes/Restaurante1/Info.AFIP
[Punto_Montaje]/Files/Restaurantes/Restaurante1/Pedido**1**.AFIP
[Punto_Montaje]/Files/Restaurantes/Restaurante1/Pedido**2**.AFIP
```

Abrazo a la distancia.-

**Comment by SantiagoIvan** [comment]
Perdón pero sigo sin entender una cosa. En **Restaurante** dice lo siguiente

**Metadata**
[...] A su vez, deberá retornar la cantidad de pedidos que ya disponga para no pisar los ID con los nuevos generados.

**Crear Pedido**
El Restaurante enviará Guardar Pedido al Módulo Sindicato para la creación de un pedido. Para esto, el restaurante generará un ID de pedido nuevo ÚNICO que permitirá identificarlo dentro de dicho restaurante.

Y luego en **Sindicato** dice lo siguiente:
**Guardar Pedido**
[...]
2 - Verificar cuál fue el último pedido y crear un nuevo archivo Pedido incrementando en uno el contador de pedidos. En caso de ser el primer pedido, se creará un nuevo archivo llamado Pedido1. 

No entiendo por qué el Sindicato verifica cuál fue el último pedido creado para ver el id ( que como bien dijiste será Pedido**id** ). Si supuestamente lo calcula el Restaurante y se lo manda por parámetro, para qué lo va a recalcular? Supongamos que cuando el Restaurante carga su metadata, la cantidad de pedidos realizados es de 30. Entonces la próxima vez que genere un pedido, le pondrá el ID 31 y lo usa para enviar el mensaje Guardar Pedido. El Sindicato cuando recibe éste mensaje verifica cual fue el ultimo pedido creado para ese Restaurante ( que será el Pedido30 ) y aumenta ese valor en uno, y le va a dar 31. A lo que voy es que lo está generando el Restaurante, se lo manda por parámetro, pero después el Sindicato lo termina calculando por su cuenta verificando la cantidad de Pedidos que tiene guardado, me explico? No entiendo por qué se resuelve de esta manera. Se estaría calculando en el Restaurante, se envía por parámetro y ese valor no se usa porque el Sindicato lo calcula de nuevo.

**Comment by iago64** [comment]
Es un buen punto lo que decís del Sindicato, lo charlamos entre los ayudantes y lo dejamos anotado para una próxima errata, porque no tiene sentido andar recalculando IDs en varios módulos, gracias por notarlo.

**Comment by iago64** [comment]
Buenas! con la nueva versión del enunciado (v1.3), queda alguna duda?

Saludos.-

**Comment by SantiagoIvan** [comment]
Perfecto, cierro issue :D
