### ISSUE TITLE
Añadir Plato:

### ISSUE THREAD

**Issue by SantiagoIvan** [sisoputnfrba/foro#1936]
El enunciado dice dentro de la sección App "Este mensaje permitirá añadir un plato a un determinado pedido." Nunca dice que le pasa una cantidad solicitada algo asi. Yo si me pido empanadas no me pido de a una, sino que si quiero me pido 5 (re gordo era, con 4 igual estoy bien). Siguiendo con la lectura, dice que le envía el mensaje Guardar_Plato. Ahora si voy a la sección Comanda, en el subtítulo 'Guardar Plato' dice que recibe por parámetro "La cantidad del plato a agregar". Entonces creo que está mal el enunciado y la firma de añadir plato debería ser Añadir_Plato ( id_pedido, plato , cantidad )  porque sino es imposible que la comanda sepa cuántos platos pidió un cliente de cada plato. Lo mismo va para el restaurante, dice que le envía el mensaje al Sindicato Guardar plato para que agregue UN plato, pero yendo al Sindicato, dice que recibe por parámetro la cantidad de cada plato. ¿Cómo es entonces? ¿Agrego la cantidad de platos a la firma de Añadir Plato?.

**Comment by iago64** [comment]
Buenas! como va?

Justo ayer sacamos la V1.2 donde aclaramos (porque se nos había recontra pasado) de que Añadir plato, va sumando de a 1 plato a la vez.
Justamente esta idea responde a que si en un pedido de empanadas queres hacer 2 de carne, 2 de pollo, 1 de cantimpalo y 1 de queso y cebolla, sea algo asi como:
```
Añadir Empanada_carne pedido1
Añadir Empanada_carne pedido1
Añadir Empanada_pollo pedido1
Añadir Empanada_pollo pedido1
Añadir Empanada_cantimpalo pedido1
Añadir Empanada_quesoycebolla pedido1
```

Saludos.-

**Comment by RaniAgus** [comment]
Buenas! Entonces si para Añadir Plato se agrega de a uno, y por cada Añadir Plato se hace un Guardar Plato, ¿por qué Guardar Plato tiene cantidad como campo? Sin la cantidad, la Comanda y el Sindicato podrían tranquilamente hacer +1 al plato que tienen con la info que reciben.

Era lo que quería plantear acá  https://github.com/sisoputnfrba/foro/issues/1905 (en el punto 2), creo que no lo expliqué muy bien

Saludos

**Comment by RaniAgus** [comment]
Acabo de leer el nuevo texto que agregaron, eso aclara mis dudas jajaj

> Descripción: dado un plato y un ID de pedido, el módulo App le informará al Restaurante la adhesión de un plato. **En caso de que el plato exista se le deberá sumar 1 a la cantidad de platos existentes.** Una vez almacenado, se deberá informar si se pudo concretar la operación.

Entonces la App y el Restaurante hacen el +1, y lo único que hacen la Comanda y Sindicato es reemplazar el valor anterior, o crear el plato en caso de que sea la primera adición.

Retiro mi duda!

**Comment by iago64** [comment]
Buenas! como va?

Añadir Plato tiene como idea que sumen de a 1 a la cantidad del plato, si no existe lo crean con 1, si existe le suman 1 a lo que ya tienen.

En el caso de guardar plato depende de como lo mires puede darse esa contradicción o no, eventualmente puede habernos quedado medio flojo de redacción (le ponemos onda pero teniendo la idea del tp en la cabeza a veces se nos pasan estas cosas), la idea es identica que en añadir plato, si no existe, lo crean, si existe solo le suman.

Abrazo a la distancia!

**Comment by SantiagoIvan** [comment]
Perdon, una cosita mas, hago una cita:
"
**Guardar Plato**

Descripción: el módulo App le informará al módulo Comanda la adhesión de un plato a un pedido, siendo este último el encargado de almacenar en memoria el nuevo plato; mientras que el modulo Restaurante es quien le informará al módulo Sindicato la adhesión del plato al pedido, siendo este último el encargado de actualizar el archivo del pedido.

Módulos que reciben el mensaje: 
    Comanda
    Sindicato

Interfaz:
    Recibe
              Restaurante
              ID de pedido
             Comida
            Cantidad
Retorna:
            Ok/Fail
"
Si vamos a sumar de a 1, y el mensaje Guardar plato se envía cada vez que añadimos un plato, podemos eliminar de la interfaz el parámetro "cantidad"?

**Comment by iago64** [comment]
@SantiagoIvan No, porque por ejemplo podemos desde el cliente mandarle el mensaje directo a la comanda y ahí si queremos la cantidad para generar ciertas pruebas especificas.
No se olviden que hay 2 formas de testear los módulos, en el conjunto general y desde el cliente, esta ultima es la que va a hacer las pruebas mas complicadas de los limites de cada módulo y la primera con todos los módulos levantados es para probar estabilidad general 😉 

Abrazo a la distancia!

**Comment by SantiagoIvan** [comment]
ahhh okok muchas gracias entendido. No tengo otra duda entonces respecto a esto. Si @RaniAgus  no tiene nada mas que preguntar, cierro el issue

**Comment by RaniAgus** [comment]
> @SantiagoIvan No, porque por ejemplo podemos desde el cliente mandarle el mensaje directo a la comanda y ahí si queremos la cantidad para generar ciertas pruebas especificas.
> No se olviden que hay 2 formas de testear los módulos, en el conjunto general y desde el cliente, esta ultima es la que va a hacer las pruebas mas complicadas de los limites de cada módulo y la primera con todos los módulos levantados es para probar estabilidad general wink

Ahhhh! Ya con eso se me clarificó todo! Entonces siempre que se reciba el mensaje desde App o Restaurante la cantidad es 1 pero si se recibe de Cliente puede ser más que 1.

Entonces la App y el Restaurante tampoco necesitan levantar el pedido (por eso quitaron el paso 1 de la especificación de la App), sino que solo le pasan el Guardar Plato a quien corresponda para que cree, haga la suma y guarde la info. Si no la pueden guardar, retornan un error para que se informe.

Por otro lado, Comanda y Sindicato tienen que poder hacer la suma cantidadActual += cantidadRecibida, así que está mal lo que dije antes sobre la contradicción.

¿Entendí bien? Si es así, por mí pueden cerrar el issue.

**Comment by RaniAgus** [comment]
> En el caso de guardar plato depende de como lo mires puede darse esa contradicción o no, eventualmente puede habernos quedado medio flojo de redacción (le ponemos onda pero teniendo la idea del tp en la cabeza a veces se nos pasan estas cosas), la idea es identifica que en añadir plato, si no existe, lo crean, si existe solo le suman.

Está bien! Entendí mal yo, no es una contradicción sino que en el Anexo I ahora aparece una acción que se hace al recibir Guardar Plato (según entendí), pero que sirve para entender el mensaje en una forma más "global".

Gracias!
