### ISSUE TITLE
Consultas Sindicato

### ISSUE THREAD

**Issue by maguitoon** [sisoputnfrba/foro#1937]
Hola, estuve mirando el video del sindicato y queria consultar respecto a algunas cosas que encontre.

1 - Archivos iniciales (size y initial_block) . No se porque (creo que por la extension .bin que figura en el Anexo II) pero en ese archivo estoy guardando dos uint_32 uno para el size y otro para el numero del primer bloque. Deberia cambiarlo a un archivo de texto SIZE=64\nINITIAL_BLOCK=5192 
Me confirman, asi ya hago el cambio antes de seguir avanzando con algo que por ahi esta mal.

2 - En el video muestran que todos los archivos tienen la extension .AFIP y en el anexo hay varios archivos con la extension .bin 
Cual seria la especificación correcta, que todos tengan extension AFIP?

Muchas gracias.

**Comment by ncoen97** [comment]
Buenas.
1. Los datos de size e initial_block tienen que ser guardados en texto. Los ejemplos del anexo 2 deberían tener todos extensión .AFIP.
2. Todos los archivos deben tener extensión .AFIP menos el bitmap.

Igualmente tengan en cuenta que en linux las extensiones son solamente para el uso "humano", a nivel archivo no influye mas que para saber con qué programa abrir un archivo.

Saludos!

**Comment by maguitoon** [comment]
Buenisimo, gracias.
