### ISSUE TITLE
Obtener Pedido: "estado"

### ISSUE THREAD

**Issue by vivasjm** [sisoputnfrba/foro#1938]
Veo que cambiaron el restorno de OBTENER PEDIDO de 

[{comida1, cantTotal1, cantLista1}, {comida2, cantTotal2, cantLista2}, ...]
a
{estado, [{comida1, cantTotal1, cantLista1}, {comida2, cantTotal2, cantLista2}, ...]}

mi duda es para que es el nuevo campo "estado", entiendo que es el estado del pedido que puede ser "confirmado" o "pendiente", lo que no veo es para que lo usaríamos, ya que la validación simplemente se hace en el modulo que recibe el mensaje, pero la recepción del estado no se consume por ningún modulo

**Comment by RaniAgus** [comment]
Buenas! Creo que es para facilitar el retorno de Consultar Pedido:
```
{Restaurante, estado,[{comida1, cantTotal1, cantLista1}, {comida2, cantTotal2, cantLista2}, …}
```
Creo que para el Restaurante sería imposible retornar si un pedido está confirmado o pendiente por sus propios medios, ya que solo "sabe" de platos (el Sindicato se encarga de almacenarlos como parte de un pedido). Y para la App lo simplifica, ya que no habría que andar buscando si existe algún PCB con el pedido (hasta se podría consultar un pedido que haya finalizado y no se haya borrado de la Comanda).

Entiendo que es por eso, capaz un ayudante podría dar una mejor respuesta

**Comment by ncoen97** [comment]
Buenas, lo que menciona @RaniAgus es correcto.
Sumando un poco más a la respuesta, el estado es un dato importante del pedido que la comanda tiene que tener. Teniendo en cuenta que Obtener pedido retorna toda la información del pedido que se encuentre en la comanda, ese campo debe estar.
Saludos!

**Comment by iago64** [comment]
Cerramos el issue por inactividad :) 
Cualquier cosa pueden abrir uno nuevo o reabrir este mismo.
