### ISSUE TITLE
Sobre el Cliente y los mensajes no polimórficos

### ISSUE THREAD

**Issue by RaniAgus** [sisoputnfrba/foro#1939]
Buenas! Vi que en la última versión actualizaron el config del Cliente, y está re copado que en ningún momento se indique a qué módulo éste se está conectando (es más rápido de iniciar y todo).

El problema es que hay 2 mensajes que NO son polimórficos, por lo que no podríamos testearlos:
- Confirmar Pedido (recibe Restaurante si se solicita a Sindicato)
- Consultar Platos (recibe Restaurante para Comanda y Sindicato)

En el caso de Consultar Platos, había comentado algo de esto muuuy por encima: https://github.com/sisoputnfrba/foro/issues/1905 El asunto es que, como el Restaurante ya cuenta con la información sobre qué platos puede cocinar (la obtiene en Obtener Restaurante), se podría evitar mandar este mensaje al Sindicato, y sería un golazo porque ese mensaje pasaría a ser polimórfico, entonces el Cliente lo podría testear :+1: 

Saludos!

**Comment by iago64** [comment]
Buenas!

Justamente la idea de que no tengan muchas ips / puertos fue para simplificar un poco el caos que podían tener.
Respecto a los mensajes no polimórficos, la solución mas simple es siempre pedir el dato desde el cliente y después como mínimo tendrías que tener un handshake para poder saber a que modulo te estas conectando y de ahi ves si mandas el dato o no 😉 

Abrazo a la distancia!

**Comment by RaniAgus** [comment]
Clarísimo! Eso resuelve todo! _(Igual sigo pensando que Consultar Platos podría ser polimórfico jajaja)_

Gracias de nuevo! Saludos

**Comment by ncoen97** [comment]
Buenas, quería agregar que también está la opción de recibir mensajes con distinta cantidad de parámetros. En el caso de que esté el Restaurante lo agregan en la serializacion y en el caso de que no esté no (en ese caso deberían agregar alguna restricción en el módulo que reciba el mensaje para que chequee que tiene la cantidad de parámetros que necesita ese módulo en particular).
Saludos!

**Comment by RaniAgus** [comment]
Así es! De hecho, por cómo lo habíamos diseñado, la función que serializa las consultas es una sola y chequea qué parámetros tiene la misma según su tipo (siempre es una combinación de comida, cantidad, restaurante e id_pedido). Hay una matriz y una función que devuelven el boolean.
Ahora se agrega la complejidad de que esa última funcion tiene que recibir como parámetro el módulo que recibe la consulta.

Saludos!
