### ISSUE TITLE
Cambios en el cliente y otras dudas del enunciado de cliente

### ISSUE THREAD

**Issue by julchat** [sisoputnfrba/foro#1940]
Hola!
Veo que en la última actualización del tp hicieron algunos cambios al enunciado del módulo cliente.

1- El archivo config, ahora en vez de tener la IP y puerto de cada módulo, ahora tiene uno solo. Supongo que la idea, como vi en el issue #1939, es levantar, sea el servidor un restaurante, la app o ninguno, una instancia o "consola" de cliente por cada restaurante, para la app, y para probar los demás módulos. Y la idea es que lo que varíe en cada archivo de config sea el ID del cliente y su posición, y, si el servidor varía, los datos.
Pero entonces, a) no tengo forma para distinguir, sin acordarme de memoria cada ip y puerto de cada módulo a con quién va a estar interactuando mi módulo cliente, no?
b) 
```
IP | [String] | El IP del servidor al cual se conectará.
PUERTO | [Numérico] | El puerto del servidor al cual se conectará.
PUERTO_APP | [Numérico] | El puerto del servidor del proceso App.
```
Esta parte me confunde, si bien es verdad que el app es un módulo único y todos los clientes usan la misma app, "IP y PUERTO" van o a pertenecer al restaurante que el cliente eligió, o a SINDICATO, COMANDA o CLIENTE si quiero probar por consola alguna funcionalidad. Entonces, cómo puedo saber la IP del APP?

2- Toda actualización recibida o enviada deberá ser almacenada en un archivo de LOG **con el formato que el grupo determine.** Teniendo en cuenta que el cliente va a aceptar mensajes por consola de forma continua, estos logs no deberán ser mostrados por pantalla.  A diferencia de los demás módulos donde dice implícitamente que se debe logear y que no, lo de negrita me confunde un poco. Corrijanme si me equivoco, hay que logear:

-Actualizaciones sobre pedidos
-Los handshakes que hago con los módulos distintos de APP (ID de cliente, posición X, posición Y)
-Handshake con APP (posición X, posición Y). Aunque acá también estaría muy bueno pasarle el ID de cliente, o eso no formaría parte del handshake de la inicialización?
-Resultados del handshake. (todo bien o todo mal)
-Cada mensaje envíado por consola escrito de una forma que el que lea el log lo entienda, detallando destinatario y parámetros, así como también el retorno de dicho mensaje
- Fallos de envío por tema de comunicaciones?
- Comunicaciones exitosas.

3- Tenía entendido que, por cada mensaje que escriba y envíe por consola, se crearía un hilo para procesar esa entrada, y se abrirían 2 sockets (uno de habla y uno de escucha) para comunicarse con el servidor.
Se supone, por lo que leí, que con el handshake se debe hacer lo mismo. Podría ser que estos dos sockets no conviene cerrarlos porque a través de ellos, me van a informar sobre actualizaciones de pedido?
Eso puedo entender del handshake con el módulo app, pero que sentido tendría tenerlos abiertos para los handshakes con los otros módulos?

4- Referente a lo último, según el anexo I de mensajes, solo el mensaje Finalizar Pedido puede ser mandado al módulo cliente.
Existe algún otro más? Quizás no tendría mucho sentido modificar el pedido (por como funcionan las apps de pedir comida), pero no podría, por ej, un cliente, "cancelar" un pedido, mandandose a si mismo Finalizar Pedido?

5- Por último, en el issue #1939 se hablaba de la existencia de 2 mensajes no polimórficos. Sin embargo, tengo entendido, nada me impide armar un mensaje determinado como codOp Destinatario char* param1, char* param2; y si el módulo al que le quiero mandar el mensaje en realidad solo necesitaba el segundo parámetro, podría escribirle cualquier cosa en param1

Gracias!

**Comment by ncoen97** [comment]
Buenas.

1. a. No tenés forma de saberlo de antemano, lo que sí se puede hacer es que envíen alguna información (por ejemplo si el modulo que recibe la conexión necesita un socket de escucha o no) mediante el handshake.
b. El puerto de la App quedó demás, la idea es que el cliente se conecte a un ip/puerto único.

2. Los logs que nombraste están bien (por ahí el handshake no es necesario logearlo, pero no estaría mal). El id del cliente es correcto que forme parte del handshake. Los errores siempre logeenlos porque les sirve mucho para entender qué está pasando  cuando tienen solo la consola.

3. Me parece que acá plantearon algunos sockets demás. Para lo primero que mencionas de abrir 2 sockets por cada consulta, no es para nada necesario si tenemos en cuenta que los sockets son bidireccionales, por lo tanto van a poder enviar el mensaje y quedarse esperando una respuesta con 1 solo socket (y de hecho me parece que hasta sería mas simple de desarrollar). Las actualizaciones del pedido quedarían en un socket aparte, que esté siempre escuchando (con un `recv()`) y lo van a necesitar solo en el caso que se conecten a la app (como les decía en el punto 1a esto pueden saberlo mediante el handshake inicial).

4. No hay ninguno más. No entendí la parte del cliente enviándose un mensaje a sí mismo, pero no contemplamos el caso de cancelar el pedido.

5. Nada te lo impide, igualmente la mejor practica sería crear un mensaje que no reciba ese parámetro, pero queda a decisión suya.

Saludos!

**Comment by RaniAgus** [comment]
Buenas, tenía entendido que el Cliente también podría recibir Plato Listo si se conecta al Restaurante, ¿cierto?

**Comment by julchat** [comment]
4. Me refería a si yo quisiera probar por consola (asi como lo hacia con comanda y sindicato) mandarle a Cliente un Finalizar Mensaje

**Comment by iago64** [comment]
Buenas!

Esto quedo re colgado, mil disculpas.

@RaniAgus Efectivamente, cuando el cliente interactúa directo contra el Restaurante "es como si fuera una app".

@julchat La idea del cliente es testear a los demas módulos, no testearse a si mismo.

Saludos.-

**Comment by julchat** [comment]
Gracias! cierro issue
