### ISSUE TITLE
Multiples Pedidios y Finalización Cliente

### ISSUE THREAD

**Issue by MaSosa314** [sisoputnfrba/foro#1941]
Buenas. Consultas rapidas:

1. ¿Una instancia de Cliente puede realizar multiples pedidos?

2. En caso de que solo pueda administrar un pedido ¿Al llegar un Finalizar Pedido, finalizamos la instancia?

3. En caso de perderse la conexion ¿Finalizamos la instancia?

Gracias y saludos.

**Comment by iago64** [comment]
Buenas!

Perdón que colgué el issue, estuve con un par de quilombos por mails de spam (el problema de tenerlo publico en el blog) y se me pasaron las notificaciones de github, respecto a las preguntas:

1.- Si, el cliente maneja multiples hilos para poder manejar multiples pedidos.

2.- Puede administrar varios, con lo cual, el finalizar solo va a hacer que logueen que finalizo y nada mas 😄 

3.- Si pierden la conexión, tienen que loguear que paso y cerrar.

Saludos.-

**Comment by MaSosa314** [comment]
Perfecto. Muchas gracias!
