### ISSUE TITLE
Consulta Restaurante Default

### ISSUE THREAD

**Issue by MaSosa314** [sisoputnfrba/foro#1942]
Buenas. Consulta rapida. ¿Faltaria en el archivo de configuración de la App los precios de los platos del Restaurante Default?

Saludos.

**Comment by iago64** [comment]
Buenas! como va?
Perdón que colgamos este issue, no lo tuvimos en cuenta y dado que ahora no importa mucho ya que se elimino la necesidad de sumar 5% por repartidor pueden ponerle un precio por default a todos los platos y listo :)

Abrazo a la distancia!

**Comment by MaSosa314** [comment]
Genial. Gracias!
