### ISSUE TITLE
Tiempo de retardo de ciclo de CPU en Restaurante

### ISSUE THREAD

**Issue by RaniAgus** [sisoputnfrba/foro#1943]
Buenas! 
Tengo la duda de si en el Restaurante hay algún retardo por ciclo de CPU (por config o fijo), al igual que en la App. Este parámetro no aparece mencionado en el archivo config de ejemplo, ni en algún otro lado.

Saludos!

**Comment by SantiagoIvan** [comment]
retardo por ciclo = sleep?

**Comment by ncoen97** [comment]
Buenas,

@RaniAgus Si, no está en el enunciado pero vamos a considerar agregarlo para la próxima así se puede ver la planificación del Restaurante a una velocidad mas "humana". Gracias!

@SantiagoIvan Si, el retardo es correcto implementarlo con un `sleep()`.

Saludos!
