### ISSUE TITLE
[Comanda] memoria direccionable

### ISSUE THREAD

**Issue by foviedo** [sisoputnfrba/foro#1944]
Buenas! Una consulta rápida, la memoria direccionable es la suma entre la memoria virtual y la memoria interna? 
Saludos!

**Comment by foviedo** [comment]
Otra consulta: La cantidad de páginas en memoria que asigno, es que mientras tengo libres, todas las que necesite el pedido o voy a tener un número fijo?

**Comment by ncoen97** [comment]
Buenas, si con "memoria interna" te referís a la memoria principal la respuesta es no. En la implementación particular de memoria virtual de este TP, todas las paginas que están en memoria principal tienen que también estar en memoria virtual, por lo tanto el espacio direccionable está dado por el tamaño del área de swap.
La segunda pregunta no estoy seguro si la entendí bien, pero intento responder igual :p. La cantidad de páginas que tenga asignado un pedido está dada por la cantidad de platos que tenga el mismo, la única limitación de espacio viene por el lado de la pregunta anterior (espacio direccionable).
Saludos!

**Comment by foviedo** [comment]
@ncoen97 entendidas ambas, gracias. Una pregunta más,
En guardar plato, dice
3_Verificar si existe el plato dentro de la tabla de páginas del pedido. En caso contrario, se deberá asignar una nueva página al segmento. 
De primeras pienso que voy a tener que levantar los datos de swap (o al menos de memoria principal) y leer el string que dice el nombre del plato a ver si coincide con el que yo estoy insertado, pero el hecho de que hable de la tabla de páginas me da la idea de que hay una forma más amable de hacerlo y yo no la estoy viendo. Viene por ahí la mano?

**Comment by iago64** [comment]
@foviedo como va?
Formas se me ocurren al menos 3 o 4, algunas "mas performantes" otras "menos performantes", pero lo que importa es que resuelvan lo pedido, con lo cual, sentite libre de implementarlo de la forma que sea, no vamos a estar con un cronometro midiendo a ver si tarda 2 o 3 segundos mas.
Lo que nos importa es que entiendan e implementen el manejo de la memoria con swap 😉 

Abrazo a la distancia!

**Comment by foviedo** [comment]
@iago64 Me va piola, como te va a vos?
Respecto a la respuesta: Buenísimo, te agradezco mil
