### ISSUE TITLE
[Comanda] tamaño de los strings de nombre de pláto

### ISSUE THREAD

**Issue by foviedo** [sisoputnfrba/foro#1945]
Consulta que Nico me dijo hace banda que haga un issue y colgué. 
Puede llegar a pasar que algún string del nombre del plato mida exactamente 24 caracteres? Porque mi idea era almacenar el \0 de fin de string, pero si hay uno que mida 24 exacto, no voy a tener espacio para él
Gracias de antemano!

**Comment by iago64** [comment]
Aloha!

Perdon la demora... no vamos a ser tan jodidos, con 23 caracteres alcanza para todas las comidas que tenemos en mente, con lo cual al tener 24 pueden guardar el '\0' tranquilos 😄 

Abrazo a la distancia!

**Comment by foviedo** [comment]
Gracias!
https://www.youtube.com/watch?v=KLFQb8uOWGU
