### ISSUE TITLE
Error config de App con el valor de ALPHA usando commons

### ISSUE THREAD

**Issue by brunotello** [sisoputnfrba/foro#1946]
Hola!

Si bien es super trivial, hay un error en el ejemplo del config de la App en la key ALPHA

<img src="https://user-images.githubusercontent.com/9848247/95932797-2ebe8400-0da3-11eb-8deb-cb8eb39fff58.png" width="350" />

Si se usa `config_get_double_value` devuelve 0 porque el valor que se espera es con . y no con , el separador de decimales

Saludos

**Comment by iago64** [comment]
Aloha! como va?

Si, tranqui, es simplmente a titulo del enunciado, si el config_get_double_value necesita . pueden ponerle un . y todo esta mas que perfecto 😄 

Abrazo a la distancia!
