### ISSUE TITLE
[Confirmar Pedido] Pedidos sin platos añadidos

### ISSUE THREAD

**Issue by RaniAgus** [sisoputnfrba/foro#1947]
Buenas! Una pregunta: ¿se debe poder obtener una respuesta OK si se envía Confirmar Pedido sobre un pedido que no tiene ningún plato? 
- De poderse hacer, ¿Restaurante debe enviar "Terminar Pedido" a Sindicato entre el paso 1 y 2 y omitir el 2? ¿Comanda debería evaluar la cantidad de platos entre el paso 3 y 4 y pasarlo a "Terminado" en vez de "Confirmado"?
- De NO poderse hacer, ¿dónde se debería evaluar e informar esto? ¿Entre el paso 3 y 4 de Sindicato?

Les cito lo que dice el enunciado en Comanda, Restaurante y Sindicato al recibir este mensaje:

#### Restaurante

> 1. Obtener el Pedido desde el Módulo Sindicato.
> 2. Generar el PCB (Plato Control Block) de cada plato del pedido en cuestión y dejarlo en el ciclo de planificación (que se explicará a continuación en el módulo de Planificación de Platos). Para esto, se deberá ejecutar el mensaje Obtener Receta al Módulo Sindicato para saber la trazabilidad que deberá tener al momento de su ejecución. Cabe aclarar que el número de pedido se deberá guardar dentro del PCB para su futuro uso.
> 3. Informar al Módulo que lo invocó que su pedido fue confirmado.

#### Comanda

> 1. Verificar si existe la tabla de segmentos de dicho Restaurante. En caso de no existir se deberá informar dicha situación.
> 2. Verificar que exista el segmento de dicho pedido dentro de la tabla de segmentos del Restaurante. En caso de no existir se deberá informar dicha situación.
> 3. Verificar que el pedido esté en estado “Pendiente”. En caso contrario se deberá informar dicha situación.
> 4. Cambiar el estado del pedido de “Pendiente” a “Confirmado”.
> 5. Responder el mensaje indicando si se pudo realizar la operación correctamente (Ok/Fail).

#### Sindicato

> 1. Verificar si el Restaurante existe dentro del File System. Para esto se deberá buscar dentro del directorio Restaurantes si existe un subdirectorio con el nombre del Restaurante. En caso de no existir se deberá informar dicha situación.
> 2. Verificar si el Pedido existe dentro del File System. Para esto se deberá buscar dentro del directorio del Restaurante si existe dicho pedido. En caso de no existir se deberá informar dicha situación.
> 3. Verificar que el pedido esté en estado “Pendiente”. En caso contrario se deberá informar dicha situación.
> 4. Cambiar el estado del pedido de “Pendiente” a “Confirmado” (se debe truncar el archivo en caso de ser necesario).
> 5. Responder el mensaje indicando si se pudo realizar la operación correctamente (Ok/Fail).

Saludos!

**Comment by iago64** [comment]
Bueeenas! como va?
Tan malas personas parecemos?

Es un caso muy borde y no tiene sentido académico que lo testeemos, con lo cual, la respuesta mas simple es: manéjenlo como quieran (a.k.a: Como mas cómodo les sea) por si algún ayudante/alumno la pifia en las pruebas y manda el Confirmar antes de añadir algún plato, pero no mas que eso :)

Abrazo a la distancia!

**Comment by RaniAgus** [comment]
Jajajajaj buenísimo, entonces supongo que lo más sencillo sería hacer un "comportamiento indefinido" y sino, para evitar alguna pifia, habría que hacer que el Sindicato haga el chequeo y devuelva FAIL cuando se intente Confirmar Pedido.

Gracias!
