### ISSUE TITLE
Consulta enunciado del sindicato (truncar)

### ISSUE THREAD

**Issue by utnfd** [sisoputnfrba/foro#1948]
Una consulta sencilla en el detalle del enunciado del sindicato, mas precisamente cuando detalla el confirmar pedido, aparece: 

Cambiar el estado del pedido de “Pendiente” a “Confirmado” (**se debe truncar el archivo en caso de ser necesario**).

No entiendo a que se refiere con se debe truncar el archivo... 

Gracias, saludos

**Comment by iago64** [comment]
Buenas! como va?

El truncar se refiere a ajustar el tamaño del archivo para que este marque el tamaño real en bytes del archivo.

Por ejemplo si tu archivo tiene el siguiente texto:

```
hola
```
Tu archivo va a pesar 4 bytes (por los caracteres), pero esto no lo sabes hasta que no le diste guardar (lo que en el TP esta representado por el confirmar pedido)

Saludos.-

**Comment by utnfd** [comment]
Listo, gracias.
