### ISSUE TITLE
[Consulta] Version recomendada de Oracle VM

### ISSUE THREAD

**Issue by Nachiten** [sisoputnfrba/foro#1949]
Resulta que yo estuve usando la versión 6.0.18 de oracle VM ya que eso me recomendaron el cuatri pasado.

Y lo que ahora me empezó a pasar (magicamente de la nada sin que yo haga nada) es que me tiraba [este error](https://i.imgur.com/iOQtAXI.png) y ninguna VM ni prendía. Según google no tenia nada que ver con la VM en si el problema sino con ciertas funcionalidades opcionales de windows que supuestamente deshabilitando me resolvía. Toqué de todo con lo que encontré en google y nada me resolvió. (Por ejemplo hablaba de desactivar el Sandbox de Windows pero esa opción ni me aparece)

Decidí updatear oracle vm a la ultima versión 6.1.14 y ahora si prendió la VM pero se rompió mágicamente por otra cosa. Ahí si dije voy a reinstalar todo a ver si queda bien.

La pregunta clave que quiero hacer es si tienen una versión 6.1.X recomendada que me genere la menor cantidad de problemas posibles. Dado que tengo entendido que la ultima puede tener mas bugs que una un poco anterior.

Gracias :)

Edit:
Ahora luego de instalar nuevamente la VM si enciende pero me tira cierto error me dice que hay un problema (no crashea), y no se redimensiona correctamente por mas que ya instale las guest adittions y todo. Anda medio bugeado.

**Comment by iago64** [comment]
Buenas!

Estas cosas suelen pasar por algún parche de windows que ajusta alguna vulnerabilidad y bueno... de yapa se llevan puestas las soluciones que no se actualizan (y teniendo en cuenta que VBox estábamos en una versión vieja, es posible que pasara algo de ese estilo)

De momento no tenemos ninguna 6.1.X como para recomendar, pero vamos a estar testeandolo un toque mas como para empezar a pegar el salto a lo mas nuevo y asegurarnos que funca sin muchos drama :)

El tema de las guest, es mas complicado, si podes pasarte el sábado de soporte para verlo con algún ayudante seria un golaso así podemos de paso encontrar el problema y publicar algo de info al respecto 😄 

Abrazo a la distancia!

**Comment by Nachiten** [comment]
> Buenas!
> 
> Estas cosas suelen pasar por algún parche de windows que ajusta alguna vulnerabilidad y bueno... de yapa se llevan puestas las soluciones que no se actualizan (y teniendo en cuenta que VBox estábamos en una versión vieja, es posible que pasara algo de ese estilo)
> 
> De momento no tenemos ninguna 6.1.X como para recomendar, pero vamos a estar testeandolo un toque mas como para empezar a pegar el salto a lo mas nuevo y asegurarnos que funca sin muchos drama :)
> 
> El tema de las guest, es mas complicado, si podes pasarte el sábado de soporte para verlo con algún ayudante seria un golaso así podemos de paso encontrar el problema y publicar algo de info al respecto 😄 
> 
> Abrazo a la distancia!

Bueno dale gracias. Por ahora safo con esta que como decia funciona... mal comparado con como me funcionad antes. No se redimensiona bien o lo deja de hacer. Mañana me paso por soporte para verlo. Gracias
