### ISSUE TITLE
[App] Recepción del mensaje Plato Listo

### ISSUE THREAD

**Issue by RaniAgus** [sisoputnfrba/foro#1950]
Buenas! En el apartado donde dice cómo la App debe manejar Plato Listo dice lo siguiente:

> 1. Enviar el mensaje Plato Listo a la Comanda.
> 2. Se deberá ejecutar el mensaje Obtener Pedido a la Comanda **con el fin de comparar la cantidad con la cantidad lista. En el caso de que sean iguales**, significará que el repartidor ya puede retirar el pedido del Restaurante, desencadenando los eventos necesarios en la planificación.

Pero el mensaje también retorna el estado del pedido (lo agregaron hace poco si mal no recuerdo). ¿Hace falta calcular la cantidad lista y total o podemos hacer que simplemente verifique que el estado obtenido sea "Terminado"?

Saludos!

**Comment by iago64** [comment]
Buenas! como va?

Esto lo charlamos en el sábado de soporte, pero lo dejo por acá escrito:

Es importante que tengan en cuenta que la mayoría de los checkeos están por las dudas de que si en las pruebas mandan algún mensaje equivocado y queremos ver el error nomas.
Dicho esto, seria buenísimo que lo agreguen por las dudas.

Abrazo a la distancia!
