### ISSUE TITLE
[Comanda] Consultas swap

### ISSUE THREAD

**Issue by foviedo** [sisoputnfrba/foro#1951]
Una consulta, a ver si entiendo bien
1. Cuando creo una página nueva, esta debería crearla en swap y además en memoria principal, acá ambas están sincronizadas
Cuando modifico algo de mi página, lo modifico en memoria principal, también debería modificarlo en swap? O modifico swap recién cuando voy a sacar a mi página de memoria principal? 
2. Está bien que me traiga todo lo que es SWAP a memoria? De forma que pueda direccionarla como el resto de la memoria
Gracias de antemano y saludos,
Facundo

**Comment by foviedo** [comment]
Respondido en sábado de consulta. Para el que le interese
1: la segunda opción
2: está mal

**Comment by ncoen97** [comment]
Buenas, por las dudas quería aclarar que el uso de mmap es una opción valida para el punto 2. Saludos!
