### ISSUE TITLE
[Programación C] Entendiendo mmap

### ISSUE THREAD

**Issue by foviedo** [sisoputnfrba/foro#1952]
Bueno, tras leer codigo de internet y no entenderlo, vengo acá, estoy tratando de crear un archivo para que sea swap, tras varios intentos de que no rompa, llegué a esto:

``` 	int fd;
	fd= open("swap.bin",O_CREAT | O_RDWR);
	if(fd==-1){
		CS_LOG_TRACE("error abriendo swap.bin");
	}
	areaSwap= mmap(NULL, cs_config_get_int("TAMANIO_SWAP"),PROT_WRITE | PROT_READ,MAP_SHARED,fd,0);
	if(areaSwap==MAP_FAILED){
		CS_LOG_TRACE("error mapeando");
	}
	int a = 3;
	memcpy(areaSwap,&a,4); 
```

Arranco por acá:
`	fd= open("swap.bin",O_CREAT | O_RDWR);
`
O_CREAT es necesario para crear el archivo si no existe
O_RDWR entiendo que estoy indicando que me abra el archivo para leer o escribir
Detalle curioso, si el archivo SÍ existe, el open retorna `-1`

Esto:
`	areaSwap= mmap(NULL, cs_config_get_int("TAMANIO_SWAP"),PROT_WRITE | PROT_READ,MAP_SHARED,fd,0);
`
areaSwap es una variable global de tipo void* no inicializada
Ese NULL pareciera que lo tengo que poner siempre? O Eso vi en tutoriales
Lo segundo es el tamaño del archivo, tengo la idea de que ahí en realidad va el tamaño que ya tiene (visto a partir de tutoriales), pero si pongo 0, el mmap retorna un error `MAP_FAILED`
lo tercero son flags para que lea y escriba, lo cuarto es para que la puedan usar varios
FInalmente el file descriptor y 0 para que empiece a trabajar desde el principio

Esta combianación hace que tanto el open como el mmap no me rompan, pero la momento de hacer memcpy en la consola me aparece `bus error`

Otra combinación que probé fue usando fopen, eso hace que se me cree el archivo y no rompa si ya existe, no obstante, el mmap retorna un error `MAP_FAILED`,  la única forma que pude hacerlo funcionar es dandole un archivo que ya está escrito con algo, pero mi idea es crear el archivo en ese momento

En fin, no tengo idea de cómo usar mmap
Agradezco toda ayuda, gracias de antemano y saludos!

**Comment by mesaglio** [comment]
Buenas Facu, como va?
En este issue creo que vamos a poder aprender ambos.
Para iniciar, ya que mencionas errores podrias commentar (con formato en markdown) los mismos? Seria de gran ayuda
Revisando el man de open pude enconrtrar esto que te puede ayudar para mostrar el error del open.
```
RETURN VALUE
       open(), openat(), and creat() return the new file descriptor (a
       nonnegative integer), or -1 if an error occurred (in which case,
       errno is set appropriately).
```

**Comment by foviedo** [comment]
Me va bien. Cómo te va a vos?
Ahí traté de aclarar qué error es cada uno!

**Comment by mesaglio** [comment]
Buenas.

El principal problema lo estas teniendo con la función open.

Al usar el flag `O_CREAT`, es necesario pasarle el parámetro `mode_t`. Estos son los permisos que va a tener el archivo al ser creado.

Acá esta la documentación para los [permisos](https://jameshfisher.com/2017/02/24/what-is-mode_t/) y acá el man de [open](https://man7.org/linux/man-pages/man2/open.2.html).

Te debe estar generando un archivo con permisos medio rotos y al entrar al mmap tirar error.

Una manera de ver los permisos de los archivos es con el comando `ls -la`.

Respecto a los parámetros del `mmap`, en el primer parámetro al pasarle `NULL`, delegas sobre el kernel el lugar en memoria donde va a estar la pagina del archivo mapeado. Como bien mencionas en el segundo parámetro `size_t` tiene que estar el tamaño del archivo.

Ojo con querer escribir mas bytes de lo que el archivo pesa.

Si hay algo que no claro, volve a comer sin problema 😄

**Comment by foviedo** [comment]
Efectivamente, me faltaba el mode_t
Also, el problema del bus error prevalecia y era por esto 

> Ojo con querer escribir mas bytes de lo que el archivo pesa.

La solución fue usar [fallocate](https://man7.org/linux/man-pages/man2/fallocate.2.html)
