### ISSUE TITLE
Multiprocesamiento, descanso y ciclos de CPU

### ISSUE THREAD

**Issue by esanchezventurini** [sisoputnfrba/foro#1953]
Buenas! Estuve trabajando en la planificación del módulo APP y me surgió una duda en cuanto al descanso de los repartidores. La consigna indica que el repartidor deberá descansar determinada cantidad de ciclos indicada por el archivo de configuración. Mi duda es: cuanto mayor sea el grado de multiprogramación, más rápido descansará un repartidor? Es decir, al haber más procesadores, se ejecutarán más ciclos en X cantidad de tiempo haciendo así el descanso más corto. La otra opción sería que el descanso se cuente como los ciclos producidos por un solo procesador, por lo que no influiría el grado de multiprocesamiento. La misma duda me surge al calcular la tasa de respuesta en el algoritmo HRRN, ya que en el cálculo se incluye la cantidad de ciclos que el proceso está esperando en estado READY. No se si fui muy claro, pero espero que se entienda. Saludos!

**Comment by iago64** [comment]
Buenas! como va?

No tiene nada que ver el grado de multiprocesamiento con la velocidad de descanso de los repartidores. El Grado de Multiprocesamiento te dice cuantos repartidores se van a mover al mismo tiempo.

Por otra parte, la cantidad de ciclos de CPU en el descanso, sumado a que tenes un algoritmo como HRRN que toma como input el tiempo de espera del proceso, te lleva a tener que implementar alguna especie de clock o algún control de ejecución para que todos ejecuten sus ciclos "al mismo tiempo*"

Saludos.-

* El al mismo tiempo es relativo ya que las VMs solo tiene 1 core con lo cual, el al mismo tiempo es visto a nivel humano y no a nivel maquina.

**Comment by esanchezventurini** [comment]
Buenísimo, entonces creo que lo mejor será implementar un hilo específico que funcione como clock y se sincronice con el planificador. Muy clara la respuesta, muchas gracias. Saludos!
