### ISSUE TITLE
Error en la VM de lubuntu al iniciar

### ISSUE THREAD

**Issue by Nachiten** [sisoputnfrba/foro#1954]
Estoy con la version de oracle VM 6.1.14 la ultima que hay hasta ahora. Y tuve que reinstalar toda la VM de lubuntu dado que me movi de 6.0.18 (por un problema con el windows el cual aclaré aca #1949 )

Entonces ahora casi siempre cuando prendo la VM me tira este error que ahora si pude obtener un poco mas de información (se los comente a damian y juan el sabado pasado en soporte pero no habia podido sacar info)

![image](https://user-images.githubusercontent.com/39410888/96489591-fe993a00-1215-11eb-97a0-1a7a92ac5eeb.png)

Luego de cerrar todos estos mensajes de error por ahora la vm funciona pero se traba un poco que antes no me pasaba y no se redimensiona bien.

La pregunta es si tienen idea que será el error y si me conviene cambiarme a una version anterior de oracle VM sea 6.X o 5.X. Gracias.

**Comment by iago64** [comment]
Buenas! como va? 
Perdon que no hay respuestas, estoy haciendo un testeo intenso de varias versiones de virtualbox (desde la 5.2, pasando por la 6.0 y llegando a la 6.1) y probando diferentes configuraciones para ver de que arranque sin problemas, en cuanto tenga algo seguro armo un post como debe ser para explicar si hay que instalar algo :)

Abrazo.-

**Comment by Nachiten** [comment]
> Buenas! como va?
> Perdon que no hay respuestas, estoy haciendo un testeo intenso de varias versiones de virtualbox (desde la 5.2, pasando por la 6.0 y llegando a la 6.1) y probando diferentes configuraciones para ver de que arranque sin problemas, en cuanto tenga algo seguro armo un post como debe ser para explicar si hay que instalar algo :)
> 
> Abrazo.-

Hay alguna noticia sobre eso? Gracias

**Comment by iago64** [comment]
Aloha! como va?

Voy a serte totalmente sincero, no estoy 100% seguro que sea la mejor config posible, pero es la que vine usando estos días para y no tuve mayores inconvenientes:
Versión de VirtualBox 6.0.24 y con el controlador gráfico es el VBoxSVGA.
![image](https://user-images.githubusercontent.com/1622109/98302220-c5452600-1f9a-11eb-805f-380bef5ca257.png)
![image](https://user-images.githubusercontent.com/1622109/98302729-b448e480-1f9b-11eb-81d0-b7b38553fd8d.png)


Al momento de instalar las guest adittions, lo hice con una imagen limpia de la VM y al "insertar el cd" de las guest adittions para correrlo fue el comando `sudo ./VBoxLinuxAdditions.run`

De momento mucha mas info no tengo pero asi con la Vm de lubuntu y otra vm estilo la server que tengo para cosas del laburo estuve sin mayores inconvenientes durante la ultima semana.

Lo que si traten de evitar:
- Version 6.1 de VirtualBox
- Usar una imagen de la vm que paso por otras versiones de VirtualBox (especialmente si tiene instaladas las guest adittions) porque me trajo un par de kernel panics.

Abrazo a la distancia.-

**Comment by iago64** [comment]
@Nachiten te resulto util la config que te pase para virtualbox? Yo por ahora sigo usándola así para el soporte y cero dramas, pero confirmame así veo si damos por cerrado el tema o si buscamos otra config 😄

**Comment by Nachiten** [comment]
> @Nachiten te resulto util la config que te pase para virtualbox? Yo por ahora sigo usándola así para el soporte y cero dramas, pero confirmame así veo si damos por cerrado el tema o si buscamos otra config 😄 

Dale despues pruebo bien eso y si llega a funcionar muy mal aviso. Gracias!

**Comment by Nachiten** [comment]
@iago64 Resulta que la versión que me dijiste que baje me tira este error D:
![image](https://user-images.githubusercontent.com/39410888/99832318-20e8e500-2b3f-11eb-91fb-d3863ff763a1.png)

**Comment by iago64** [comment]
Tenes habilitado Hyper-V? porque recuerdo haber tenido ese problema cuando tenia Hyper-V de windows habilitado.

**Comment by Nachiten** [comment]
> Tenes habilitado Hyper-V? porque recuerdo haber tenido ese problema cuando tenia Hyper-V de windows habilitado.

![image](https://user-images.githubusercontent.com/39410888/99834078-c604bd00-2b41-11eb-897b-fb3e1bf2718e.png)
No me aparece la opcion de hyperv en optional features :( 
No estoy seguro ni siquiera si lo tengo o no. Pero ahora estoy viendo si por comando lo puedo ver.

**Comment by Nachiten** [comment]
![image](https://user-images.githubusercontent.com/39410888/99838503-ffd8c200-2b47-11eb-9dcc-34cba34a89f4.png)
Traté de desactivar la característica pero dice que no existe. Es decir supongo que no la tengo.

**Comment by mesaglio** [comment]
Lo cerramos y si alguien tiene mas info, se reabre.
