### ISSUE TITLE
Añadir Plato

### ISSUE THREAD

**Issue by hugoguarneri** [sisoputnfrba/foro#1955]
Buenas, Tengo una duda con el mensaje Añadir Plato:
```
- Módulos que reciben el mensaje: 
    - App 
    - Restaurante
- Recibe:
    - Plato
    - ID de pedido
- Retorna:
     - Ok/Fail
```

En el apartado donde dice como la APP debe manejar este mensaje dice lo siguiente:
```
Este mensaje permitirá añadir un plato a un determinado pedido. Para esto se recibirá tanto el plato como el ID de Pedido destino. La funcionalidad de este mensaje se descompone en los siguientes pasos:

1.  Enviar al Restaurante dueño de dicho Pedido el mensaje que nos llegó. En caso que se trate del “Restaurante Default” pasar al punto 3.
2. Si el Restaurante dueño de dicho pedido retorna un error, se debe informar el rechazo al Cliente solicitado
3. Informar al Módulo Comanda la adhesión de un nuevo Plato a dicho Pedido. Si el módulo informa un error deberá informarse el rechazo del mismo (la casuística para que esto pase se explica en dicho módulo).
4. Retornar OK al cliente que lo solicitó.

```

En base al id_pedido como se cual es el restaurante al que le tengo que reenviar el mensaje?
En la Api no hay definido ningun mensaje que reciba la comanda y que en base al id_pedido me devuelva el restaurante que maneja ese pedido.
La App tiene que guardar a que restaurante corresponde cada id de pedido?

**Comment by ncoen97** [comment]
Buenas.
Tengan en cuenta que está el mensaje Seleccionar Restaurante justo por este motivo, antes de enviar los mensajes se debe seleccionar el restaurante para que quede registrado en la app.
Saludos!

**Comment by hugoguarneri** [comment]
En el mensaje Seleccionar Restaurante asocio al cliente con un restaurante, pero en Añadir Plano no me llega el cliente como para poder obtener el restaurante.

**Comment by ncoen97** [comment]
Cita de la pagina 13 del tp:

> Para las conexiones con los distintos módulos, se deberá implementar un handshake en el que se informen los datos necesarios para reconocer al Cliente (Id y posición).

Saludos!

**Comment by ncoen97** [comment]
Claro, si no hacen el handshake en cada `connect()` no tendrían forma de saber de qué cliente es esa nueva conexión. Y este handshake si lo van a tener que implementar para todos los módulos porque el cliente tiene que poder conectarse a cualquier módulo indistintamente teniendo un único ip/puerto.
Saludos!

**Comment by karengrams** [comment]
¡Aloooo @hugoguarneri !

¿Como va? Espero que bien. ¿Quedo resuelta la duda?

Saludos 😺 .

**Comment by hugoguarneri** [comment]
Quedo resuelta, muchas gracias!
