### ISSUE TITLE
[Sockets] Averiguar si un socket fue cerrado del otro lado

### ISSUE THREAD

**Issue by RaniAgus** [sisoputnfrba/foro#1956]
Buenas! Tengo una duda en cuanto a sockets:

Resulta que para conectar Clientes a la App tengo una lista de Clientes en la que se almacenan structs `t_cliente`, los cuales tienen el socket file descriptor que corresponde para enviar notificaciones.

Entonces, cuando se conecta un nuevo Cliente, me fijo si ya fue conectado o no y me baso en eso para saber si el socket es para notificaciones o para enviar una consulta y hacer `close()`.

El problema de esto es que, si el Cliente se desconecta, a menos que haya alguna forma de detectar que ese socket esté desconectado y quitarlo de la lista a tiempo, cuando vuelvo a reconectar me queda la lista de Clientes inconsistente.

Y no puedo hacer `recv()` porque si SÍ está conectado se va a quedar bloqueado ahí hasta recibir algo. Aparte, si justo en ese momento estoy a punto de recibir una respuesta a una notificación, me va a terminar cayendo ahí en vez de en el otro `recv()` que andará por algún otro hilo esperando recibir la respuesta.

Incluso intenté hacer `recv()` de cero bytes y `getpeerinfo()`, pero no retorna ningún error.

Hay alguna forma no-bloqueante de consultar si un socket fue cerrado desde el otro lado?

**Comment by mesaglio** [comment]
Buenas Agus, como va?
Estuve probando un par de cosas, creo que [esto](https://man7.org/linux/man-pages/man2/getpeername.2.html) te puede venir bien.

Aca tenes un [ejemplo](https://support.sas.com/documentation/onlinedoc/sasc/doc750/html/lr2/zeername.htm) de una posible implementacion.

**Comment by RaniAgus** [comment]
Todo bien Juan! Y vos?
Me confundí de nombre! En vez de getpeerinfo era esa misma, `getpeername()`
Tenía ya armada una función que usa esa para obtener IP y Puerto en formato string, y probé esto:
```
bool esta_conectado;
/*
...
*/
app_cliente_t* encontrado = list_find(lista_clientes, (void*) _find_cliente_by_name);
if(encontrado != NULL) {
	char *ip, *puerto;
	if(cs_get_peer_info(encontrado->conexion, &ip, &puerto) != 0) {
		CS_LOG_WARNING("SE ENCONTRÓ EL CLIENTE PERO ESTÁ DESCONECTADO!!!");
		list_remove_and_destroy_by_condition(lista_clientes, (void*) _find_cliente_by_name, (void*) app_cliente_destroy);
		esta_conectado = false;
	} else {
		CS_LOG_WARNING("SE ENCONTRÓ EL CLIENTE!!! %s:%s", ip, puerto);
		esta_conectado = true;
	}
} else {
	CS_LOG_WARNING("NO SE ENCONTRÓ EL CLIENTE!!!");
	esta_conectado = false;
}
```
Y lo que hice después de levantar la App fue:
1. Levantar el Cliente. Hace handshake, no lo encuentra y lo agrega
2. Envío un mensaje desde el Cliente. Hace handshake, lo encuentra y recibe mensaje
3. Cierro y vuelvo a levantar Cliente. Hace handshake, lo encuentra y espera un mensaje que nunca llega (porque ese socket es el que recibiría notificaciones).
```
[TRACE] 00:44:44:206 APP/(9481:9481): Iniciado correctamente
[TRACE] 00:44:44:240 APP/(9481:9481): Conectado correctamente con Comanda {IP: 127.0.0.1} {PUERTO: 4444}
[TRACE] 00:44:44:349 APP/(9481:9484): Se abrió un servidor: {PUERTO_ESCUCHA: 5004}
[TRACE] 00:44:51:689 APP/(9481:9502): (9)Se recibió el mensaje: HANDSHAKE_CLIENTE {NOMBRE: Cliente1} {POSX: 1} {POSY: 2}
[WARNING] 00:44:51:692 APP/(9481:9502): NO SE ENCONTRÓ EL CLIENTE!!!
[TRACE] 00:44:51:693 APP/(9481:9502): (9)No se encontró a Cliente1 entre la lista de Clientes, se agregará a la misma.
[TRACE] 00:44:51:695 APP/(9481:9502): Se agregó el Cliente: { Cliente1, (1:2) } 
[TRACE] 00:44:51:702 APP/(9481:9502): Se envió la respuesta: HANDSHAKE_CLIENTE {MODULO: App}
[TRACE] 00:44:58:950 APP/(9481:9520): (10)Se recibió el mensaje: HANDSHAKE_CLIENTE {NOMBRE: Cliente1} {POSX: 1} {POSY: 2}
[WARNING] 00:44:58:986 APP/(9481:9520): SE ENCONTRÓ EL CLIENTE!!! localhost:54892
[TRACE] 00:44:58:987 APP/(9481:9520): (10)Se encontró a Cliente1 entre la lista de Clientes, se recibirá la consulta.
[TRACE] 00:44:58:988 APP/(9481:9520): Se envió la respuesta: HANDSHAKE_CLIENTE {MODULO: App}
[TRACE] 00:44:58:998 APP/(9481:9520): (10)Se recibió el mensaje: CONSULTAR_PLATOS
[TRACE] 00:44:58:999 APP/(9481:9520): Buscando al Restaurante vinculado con Cliente1...
[TRACE] 00:44:58:1 APP/(9481:9520): No hay restaurantes conectados, se vinculó con Default
[TRACE] 00:44:59:8 APP/(9481:9520): Se envió la respuesta: CONSULTAR_PLATOS {PLATOS: [Plato1,Plato2,Plato3]}
[TRACE] 00:44:59:9 APP/(9481:9520): (10)Se atendió CONSULTAR PLATOS, se cerrará la conexión.
[TRACE] 00:44:59:12 APP/(9481:9520): (10)Se cerró la conexión.
[TRACE] 00:45:03:608 APP/(9481:9537): (11)Se recibió el mensaje: HANDSHAKE_CLIENTE {NOMBRE: Cliente1} {POSX: 1} {POSY: 2}
[WARNING] 00:45:03:615 APP/(9481:9537): SE ENCONTRÓ EL CLIENTE!!! localhost:54892
[TRACE] 00:45:03:615 APP/(9481:9537): (11)Se encontró a Cliente1 entre la lista de Clientes, se recibirá la consulta.
[TRACE] 00:45:03:616 APP/(9481:9537): Se envió la respuesta: HANDSHAKE_CLIENTE {MODULO: App}
```
Es como si obtuviera la info del peer a pesar de haberse desconectado y vuelto a conectar :thinking: 

Lo que me sorprendió ahora es que leyendo el man dice como que sí debería retornar error. Probé copiando y pegando el código reemplazando `s` por el socket del Cliente porque capaz habría algún problema con el retorno de la función, pero me sigue pasando lo mismo :disappointed:

**Comment by RaniAgus** [comment]
Dejo lo que vimos por Discord por si a alguien más le interesa:
1. El `getpeername()` obtiene IP y Puerto, incluso aunque se haya cerrado la conexión y se haya intentado recibir algo de ese buffer.
2. Parece que la única forma de hacer que funcione este chequeo es haciendo un `recv()` con `MSG_DONTWAIT` para hacerlo no bloqueante y `MSG_PEEK` para que no retire del buffer lo que recibe:
```
void* algo = malloc(1);
if(recv(socket, algo, 1, MSG_PEEK | MSG_DONTWAIT) == 0) {
    /* el socket no está conectado */
}
free(algo);
```
De todas formas esto se sale completamente del scope del TP, no hace falta hacer que una instancia de Cliente se pueda cerrar y volver a abrir.
