### ISSUE TITLE
[Restaurante] Consulta test

### ISSUE THREAD

**Issue by RaniAgus** [sisoputnfrba/foro#1958]
La prueba del Restaurante dice que el pedido 2 debe terminar antes que el 1, pero en las pruebas me resultó que terminan al mismo tiempo. Hice el Gantt y me dio lo mismo:

![image](https://user-images.githubusercontent.com/39303639/96769353-66d25200-13b5-11eb-9e11-e0b981d1cbaa.png)

**Comment by karengrams** [comment]
¡Buenas buenas! 

¿Cómo va? Espero que bien. Antes de hablar del Gantt en si, te hago la una pregunta: ¿tuviste en consideración el "confirmar Pedido"? Dado que, si consideramos que es una consola interactiva, posiblemente lo que pase es que no empiecen a planificarse los pedidos al mismo tiempo. ¿A qué me refiero? A que no vamos a poder escribir automáticamente uno atrás de otro el ```confirmarPedido (...) ```. Posiblemente haya un quantum de tiempo en el medio donde va a quedar sin hacer nada hasta que le envíes el otro ```confirmarPedido (...) ```. Por si no se entendió hice un Gantt para ver si se ve mejor.

![image](https://user-images.githubusercontent.com/32707822/97051602-cff0cb80-1555-11eb-8717-5804f0e9caf8.png)

¡Saludos!

**Comment by RaniAgus** [comment]
Hola, Karen! Todo bien y vos?

Así es, lo tuve en cuenta, lo que pasa es que el documento dice:

> - Crear un pedido con ID 1 y añadirle 1 AsadoCompleto y **2 Choripan**.
> - Crear un pedido con ID 2 y añadirle 5 Choripan.

Es decir que no importaría mucho el tiempo que se tardaría en escribir `confirmar_pedido(...)`, porque los 3 cocineros empiezan a estar ocupados ya con el primer pedido que se confirma.

Igual, por lo que veo al parecer en su Gantt tenían pensado que el primer pedido tenga 1 Choripan y no 2 :eyes:

**Comment by karengrams** [comment]
Aloha,

Antes que nada:

>Igual, por lo que veo al parecer en su Gantt tenían pensado que el primer pedido tenga 1 Choripan y no 2 👀

Esto fue mala mia, mil disculpas 😥 . Pero, habiendo señalado eso, ahora veo el problema. Gracias por el aviso, lo vamos a estar chusmeando/corrigiendo.

¡Saludos!

**Comment by RaniAgus** [comment]
Buenísimo, no hay drama, gracias por la ayuda

Saludos!

**Comment by RaniAgus** [comment]
¡Buenas! ¿Pudieron revisar esto?

**Comment by iago64** [comment]
@RaniAgus estamos ajustando para las pruebas finales 😉
