### ISSUE TITLE
[APP]Dudas ciclos

### ISSUE THREAD

**Issue by Matiasarapura** [sisoputnfrba/foro#1961]
Buenas, ayer en el checkpoint me nombraron que el ciclo tiene que ser comun entre todos los hilos que se estan ejecutando.
No se me ocurre muy bien como lograr esto, ya que tengo PCBS que tambien dependen del ciclo y pueden estar en el hilos de blockeados y al no saber cuantas tengo. No podria usar un semaforo (o si?)

tambien el PCB, deberia contener la cantidad de ciclos que lleva desde que esta en ready?

Mil gracias 
espero q se entienda mi duda.

**Comment by ncoen97** [comment]
Buenas.
Este problema si se puede resolver con semaforos! Tengan en cuenta que la cantidad de hilos que consuman los ciclos no va a depender de los PCBs que tengan sino del grado de multiprogramación (sumando uno o dos más para contar los descansos y el HRRN/SJF). Es correcto que tengan en el PCB la cantidad de ciclos para el caso de HRRN y SJF.
Saludos!

**Comment by Matiasarapura** [comment]
Claro, los descansos los tengo que ir tratando de a uno o con el grado de multiprogramacion?

**Comment by ncoen97** [comment]
Pueden ocurrir múltiples descansos en paralelo, no dependen del grado de multiprogramación.

**Comment by Matiasarapura** [comment]
Oka genial gracias
