### ISSUE TITLE
Memoria - Asignación de Frames

### ISSUE THREAD

**Issue by SantiagoIvan** [sisoputnfrba/foro#1962]
Esta pregunta es mitad teorica mitad practica.

En un principio yo voy a tener la memoria vacia digamos, sin ningun plato cargado. A medida que yo vaya guardando platos, voy a ir guardando los mismos inicialmente en memoria virtual, (como dice la teoria). Mi pregunta es: 
1) Qué frame de memoria virtual le asigno? pienso yo que  en un principio van a estar todos vacíos.¿ Voy en orden buscando un Frame libre? ¿o tengo que implementar una función hash para acceder aleatoriamente a un frame?

2) La misma duda me surge cuando tengo que pasar un plato a memoria principal, es decir,si quiero modificar un plato que no esta en memoria principal, tengo que buscarlo en la memoria virtual y pasarlo a la memoria principal. Si yo tengo la memoria casi vacia y no hace falta realizar un swapeo, en cual frame lo meto? en el primero que encuentre?

Espero que se haya entendido la pregunta, cualquier cosa reformulo

**Comment by ncoen97** [comment]
Buenas, te dejo un pedacito del Stallings que responde esto.

![image](https://user-images.githubusercontent.com/7952790/97177727-5505fb80-1775-11eb-9c14-565d0989b514.png)

Saludos!

**Comment by SantiagoIvan** [comment]
Muchisimas gracias !
