### ISSUE TITLE
Problema con Eclipse

### ISSUE THREAD

**Issue by AgustinBer** [sisoputnfrba/foro#1963]
Hola. Estoy teniendo un problema con Eclipse, y es que me aparece este cartel al correr el proyecto (luego de compilarlo.). Vi que en el foro a una chica le ocurrió algo parecido al principios del cuatrimestre pasado, pero no vi nunca solución específica publicada. Adjunto imagen de lo que me aparece.

Gracias,
Agustin

![9ccb8a6e6cb9efcfb04fe0f2206c81d3](https://user-images.githubusercontent.com/61425485/97470328-2bd89d00-1926-11eb-8f2e-1701ad386f8f.png)

**Comment by iago64** [comment]
Buenas!

Eso lo que te dice es que no encuentra el binario para ejecutar, eso lo podes configurar desde las Run / Debug Configurations (según lo que quieras hacer) y tenes que especificarle la ruta donde tenes el archivo ejecutable (Generalmente esta en la carpeta Debug).

Saludos.-

**Comment by RaniAgus** [comment]
Lo vimos con Agus por Discord, dejo la solución acá para el que tenga el mismo problema a futuro:

En el apartado de `Run > Run Configurations` hay que asegurarse que el apartado `C/C++ Application` apunte hacia el archivo ejecutable del proyecto (normalmente es `Debug/<nombreDelProyecto>`):

![image](https://user-images.githubusercontent.com/39303639/97611706-462d7c00-19f5-11eb-8b30-42d30a2aaf14.png)
![image](https://user-images.githubusercontent.com/39303639/97611877-7f65ec00-19f5-11eb-9883-eef63f548c8c.png)

También, en caso de que esté eso configurado, puede pasar que tire el error porque hay un error previo al buildear, en ese caso el archivo nunca fue generado

**Comment by RaniAgus** [comment]
Uy Dami justo acabamos de ver ese tema por Discord, ahí redacté la respuesta (aunque la marqué como duplicado) :sweat_smile:

**Comment by iago64** [comment]
No problem, que quede visible, que justamente tiene las capturas que yo ahora no puedo poner (porque estoy en la pc del laburo y  no tengo la vm a mano) 😄

**Comment by ncoen97** [comment]
Buenas @AgustinBer .
Friendly reminder de que cuando suben imagenes con errores tambien tienen que subir el texto `Launch failed. Binary not found.` para que cuando alguien tenga un problema similar lo pueda encontrar con el buscador de issues.
Saludos!

**Comment by karengrams** [comment]
Buenas @AgustinBer  

Otro friendly reminder, cuando los problemas queden resueltos, no olviden de cerrar el issue, asi mantenemos todo ordenado.

¡Saludoss!
