### ISSUE TITLE
[App] Pedidos pueden pasar de Block a Exit?

### ISSUE THREAD

**Issue by RaniAgus** [sisoputnfrba/foro#1965]
Buenas! Recuerdo que varios sábados de soporte atrás había preguntado qué pasaba cuando a un repartidor le llegaba su tiempo de descanso justo en el mismo ciclo en el que llega a la posición del Cliente y me habían contestado que se iba a Block antes de cumplir con la finalización del Pedido. Sin embargo, en el diagrama de estados no aparece ninguna flecha que vaya de Block a Exit, ¿debemos pasar el repartidor a Ready a pesar de que no le queden ciclos por ejecutar? 

![image](https://user-images.githubusercontent.com/39303639/97522854-84885400-197f-11eb-8b08-036c2b6a3cea.png)

Saludos!

**Comment by RaniAgus** [comment]
Cierto! Me había olvidado eso de que en la teoría no poníamos todas las flechas que van a Exit para que el diagrama sea fácil de leer :sweat_smile:

**Comment by karengrams** [comment]
Buueeenas.

No llegue a responder, pero si, es asi como dijo Tom. 

¡Saludos!
