### ISSUE TITLE
[Comanda] Duda Guardar Plato y algoritmos reemplazo

### ISSUE THREAD

**Issue by hivarra** [sisoputnfrba/foro#1966]
Hola! vengo a plantear dos dudas que tengo sobre el modulo Comanda:

1) El enunciado dice "Toda página debe existir inicialmente en SWAP moviéndose a Memoria solo en el caso que sea
necesario", pero cuando llega un plato nuevo, y tengo que buscar "un marco" libre en swap para guardar este plato, en la teoria vimos que los datos se modifican y leen en memoria principal. Acoplandolo con la teoria, primero deberiamos reservar ese "marco" en swap, luego pedir un marco en memoria principal, escribir en memoria principal, y llevar el plato al "marco" de swap recien cuando halla que reemplazar la pagina. Pero el enunciado da a entender que al llegar un plato nuevo debo escribirlo directamente en swap, o sea copiar la info del plato directamente a swap sin haber pasado por MP. Entonces, ¿Sigo lo que dice el enunciado y voy por la ultima opcion que mencione?

2) Al ejecutar un algoritmo de reemplazo, es valido "lockear" con dos semaforos todas las entradas de paginas (no se podria acceder a ninguna pagina mientras ejecuta el algoritmo) hasta encontrar la pagina a reemplazar? Porque en caso contrario, deberia crear un semaforo para cada pagina (para evitar inconsistencias), y lo veo un poco mas complejo.
Agrego otra duda...

3)Cuando busco un plato, por ejemplo en un Guardar Plato, que tengo que buscar en todas las paginas del pedido el nombre del plato. Se puede buscar primero en las paginas que estan en Memoria Principal, y si no la encuentro en MP, recien ahí buscarla en swap? O debo buscar secuencialmente tando en MP como en swap?
Gracias! Hernan

**Comment by ncoen97** [comment]
Buenas.

1.  "Acoplandolo con la teoria, primero deberiamos reservar ese "marco" en swap, luego pedir un marco en memoria principal, escribir en memoria principal, y llevar el plato al "marco" de swap recien cuando halla que reemplazar la pagina."
Esto es correcto, pero tengan en cuenta que en la teoría se asume que cuando se crea un nuevo proceso se carga todo en swap inicialmente.

2. Es valido lockear las tablas mientras se ejecuta el algoritmo.

3. En el enunciado no está definido el orden de búsqueda porque cualquier orden debería dar el mismo resultado, por lo tanto elijan (siempre teniendo alguna justificación) cual les parece mas conveniente a desarrollar.

Saludos!

**Comment by hivarra** [comment]
Genial! Gracias por contestar, saludos!
