### ISSUE TITLE
Platos Comanda

### ISSUE THREAD

**Issue by SantiagoIvan** [sisoputnfrba/foro#1968]
Buenas! Tengo un par de consultas con respecto a los platos en la Comanda

1)**Guardar_Plato**

En la secuencia de pasos a realizar no dice nada sobre chequear el estado del pedido.
¿No deberia fijarse que el pedido este en Pendiente tambien? Porque por lo que entiendo, si tengo un pedido confirmado y mando un guardar_plato, va a poder hacer sin ningun problema, y yo creo que no deberia poderse. 
En el mensaje de **plato_listo** sí se chequea que esté confirmado, por eso surgió la duda. Además me hace ruido que a pesar de tener el pedido confirmado pueda seguir agregando platos como si nada

2)**Plato_Listo** 

1 - Verificar si existe la tabla de segmentos de dicho Restaurante. En caso de no existir se deberá informar dicha situación.
2 - Verificar que exista el segmento de dicho pedido dentro de la tabla de segmentos del Restaurante. En caso de no existir se deberá informar dicha situación.
3 - Verificar si existe el plato dentro de la tabla de páginas del pedido. En caso contrario, se deberá informar dicha situación.
4 - En caso de que las páginas que corresponden al pedido no se encuentren cargadas en memoria principal, se deberán cargar las mismas desde swap (iniciando la elección de víctimas de ser necesario). En caso contrario, proceder al paso  número 4.
5 - Verificar que el pedido esté en estado “Confirmado”. En caso contrario se deberá informar dicha situación.
6 - Se deberá aumentar en uno la cantidad lista de ese plato. En caso de que todos los platos estén listos, se deberá cambiar el estado del pedido a “Terminado”.
7 - Responder el mensaje indicando si se pudo realizar la operación correctamente (Ok/Fail).

Si o si hay que respetar esa secuencia de pasos en ese orden? Porque me hace ruido tener que cargar todas las páginas y luego fijarme si el estado del pedido esta confirmado, cuando podría hacerlo al revés y así evitar cargar páginas que no voy a utilizar cuando el pedido no está confirmado

**Comment by ncoen97** [comment]
Buenas.
1. Es correcto que chequeen si el pedido está en estado pendiente.
2. Pueden verificar primero el estado para ahorrarse esos reemplazos.

Saludos!
