### ISSUE TITLE
[Sindicato] Consulta sobre bitmap

### ISSUE THREAD

**Issue by SantiagoAspres** [sisoputnfrba/foro#1969]
Buenas, quería consultar sobre la forma que trabaja el bitmap:

Dentro de cada [nombre_pedido].AFIP tengo mi **tamaño de bloque** y el **bloque inicial**.
El **bloque inicial** debería ser el primer bloque libre que encuentre o un bloque libre que tome de forma aleatoria dentro del bitmap?
Por otro lado, el **tamaño del bloque** es un tamaño fijo que seria el que leo del metadata?

**Comment by iago64** [comment]
Buenas! como va?

Si te referís a por ejemplo `/Files/Restaurantes/Restaurante1/Info.AFIP` o `/Files/Recetas/Milanesa.AFIP` tenes 2 campos
SIZE que te indica el tamaño en bytes **del archivo**
y el INITIAL_BLOCK o bloque inicial que efectivamente es el bloque donde empieza el archivo, el cual tenes que buscarlo en el bitmap como bloque libre y marcarlo como ocupado al momento de asignarselo a un archivo (como lo hagas si es el primero, el ultimo o uno random del medio, no pasa nada, haganlo de la forma mas simple)

El _tamaño de los bloques_ lo levantas del archivo `/Metadata/Metadata.AFIP`

Saludos.-

**Comment by SantiagoAspres** [comment]
Perfecto, entonces todos los archivos de mi file system van a tener el tamaño fijo que lo saco del metadata?

**Comment by iago64** [comment]
Solo los archivos que estan dentro del directorio `/Blocks` que son los bloques de datos, los demas como los de restaurantes, pedidos y recetas van a ser variables y el tamaño lo vas a tener que tener guardado en la variable SIZE.
