### ISSUE TITLE
[Cliente] Consulta sobre archivo configuración

### ISSUE THREAD

**Issue by Roman-Petru** [sisoputnfrba/foro#1970]
Buenas! Releyendo el enunciado me di cuenta que el config del cliente cambió y me quedó la duda de cómo sabría ahora a donde mandar sus mensajes, antes estaba de esta forma:

IP_COMANDA=127.0.0.1
PUERTO_COMANDA=5001
IP_RESTAURANTE=127.0.0.1
PUERTO_RESTAURANTE=5002
IP_SINDICATO=127.0.0.1
PUERTO_SINDICATO=5003
IP_APP=127.0.0.1
PUERTO_APP=5004

y ahora ya no están ninguno de estos datos. Se pueden seguir manteniendo en el config, hay que meterlos en el codigo directamente o hay que hacer alguna otra cosa?

**Comment by iago64** [comment]
Buenas! como va?

Este cambio esta desde el 26/09 y la idea es que el cliente se conecte a un solo proceso a la vez, por lo tanto, solo vas a necesitar una IP y un puerto para conectarte.
Para saber a que proceso te estas conectando vas a tener que hacer un handshake y que el proceso del otro lado te confirme que es (si es App, Restaurante, Comanda o Sindicato).

Saludos.-

**Comment by Roman-Petru** [comment]
Gracias por la pronta respuesta! Es decir que esta IP y Puerto en el config son del módulo al que te quieras conectar en ese momento?

Ejemplo de Archivo de Configuración
IP=127.0.0.1
PUERTO=5001
ARCHIVO_LOG=/utnso/logs/cliente.log
POSICION_X=1
POSICION_Y=2
ID_CLIENTE=Cliente1

En nuestro grupo la idea sugerida la implementamos preguntando por consola a qué modulo se desea conectar, y luego utilizando los datos en el config hacer la conexión y el handshake con el módulo seleccionado. Se puede mantener de esta manera para no tener que cambiar el config cada vez que te quieras conectar a un módulo distinto?

**Comment by ncoen97** [comment]
Buenas.
En la configuración solo se debe tener un conjunto de ip-puerto, y el handshake debe ser utilizado para que el cliente pueda definir con qué módulo se está conectado (o qué protocolo/comportamiento se debe seguir).
Saludos!

**Comment by Roman-Petru** [comment]
Ok joya, muchas gracias!
