### ISSUE TITLE
[Comanda] Estructura de un bloque en SWAP, funcionamiento de finalizar plato y duda del principio del enunciado

### ISSUE THREAD

**Issue by julchat** [sisoputnfrba/foro#1971]
Buenas, 3 preguntas.

1- "En el caso de que no haya más espacio direccionable en la memoria, no se debe permitir realizar ninguna operación de adición."
No entendemos muy bien a que se refiere esto. Si la memoria principal se llena no debemos hacer malloc()? O habla de que si no hay espacio inicial para la memoria para reservar o en disco para el area de swap el proceso debe finalizar?

2- Se puede tener información admistrativa en el area de swap? Si se viera desde un punto de vista de memoria, algo asi como que cada bloque sea un elemento de un t_list*, con un ID y despues toda la informacion del plato. Esto nos permitiria saber mas facil en que fila de la tabla de paginas se habla del plato que buscamos.

3- finalizar pedido menciona borrar la tabla de paginas para el pedido (segmento) y la información correspondiente en SWAP. Pero es necesario quitar las paginas que esten en frames de memoria? Digo, naturalmente por como funcionan los algoritmos de LRU y Clock van a ser removidas con el flujo de ejecución normal del proceso

**Comment by foviedo** [comment]
Te respondo yo y que me corrijan si digo algo mal
1_ La memoria principal no la podés agrandar, queda el espacio que queda cuando hacés el malloc grande al principio, also, la que se te va a llenar es la de swap (porque tiene todo lo que tiene la principal y más)
2_ te vas a volver mono serializando un t_list* para ponerla en swap, además de que creo que va contra la consigna (no estoy seguro de esto), creo que en swap tenés que tener el mismo tipo de contenido que hay en memoria principal
3_ No entiendo bien a qué te referís con esta(? Puedo decir que en sí no tenés que borrar el contenido, si no que dejás de referenciarlo como si ahí hubiera contenido, o al menos así es en la teoría

**Comment by TheLucasPrada** [comment]
Buenas! aporto mi entendimiento de CoMAnda, pero básicamente todo lo que te dijo foviedo esta bien:

1- Se refiere a que si se te copa el área de SWAP, que no hagas nada, osea, te llega una solicitud de meter una pagina nueva? no lo haces, porque tenes SWAP llena y respondes que falló la solicitud

2- Tanto en SWAP como en MP, solo podes tener los datos de las páginas, osea los 32 bytes que te dice la consigna (cantidad pedida, cantidad lista y nombre del plato) todas las estructuras administrativas las tenes por fuera del area de SWAP y MP, estos 2 son solo para poner y sacar datos de los platos, nada mas

3- No hace falta quitar nada, básicamente los marcas como "libres" y el algoritmo ya los agarra para pisarlos con la data que necesite. Quizás me equivoco pero la verdad que sería re al pedo, si no te cambia nada, en cualquier caso, si hay que hacer eso si o si, basta con un memcpy de 32 bytes con basura, tipo pegarle un "********************************", pero como dije, con solo marcar los marcos como libres ya te tendría que alcanzar y sobrar.

Saludos!

**Comment by ncoen97** [comment]
Buenas, entre ambas respuestas de los compañeros me parece que quedaron bien respondidas las preguntas, cualquier cosa no duden en seguir consultado.
Saludos y gracias!

**Comment by julchat** [comment]
Gracias! todo claro!
