### ISSUE TITLE
[Sindicato] Consulta sobre la cantidad_pedidos

### ISSUE THREAD

**Issue by LeoCubelli** [sisoputnfrba/foro#1973]
Buenas, tengo una consulta con el último parámetro que agregaron en los restaurantes, cantidad_pedidos se refiere a la cantidad de pedidos que tiene el restaurante pendientes, confirmados, terminados o no importa. Lo estoy sumando cuando se crea el pedido y restando cuando se termina el pedido pero no se si esto estaría bien. Desde ya muchas gracias.

**Comment by ncoen97** [comment]
Buenas.
Esta es la cantidad total de pedidos que hay en un Restaurante, recuerden que en Sindicato los pedidos no se eliminan, sino que quedan a modo de "historico". Cito pagina 26 del TP:

> **Metadata del restaurante**
Se ejecutará el mensaje Obtener Restaurante al módulo Sindicato obteniendo todos los datos del mismo, siendo algunos de ellos: Cantidad de cocineros y sus afinidades, posición del restaurante en el mapa, recetas disponibles con sus precios y la cantidad de hornos. A su vez, deberá retornar la cantidad de pedidos que ya disponga para no pisar los ID con los nuevos generados.

Saludos!

**Comment by LeoCubelli** [comment]
Joya Nico, gracias
