### ISSUE TITLE
Valgrind -- Still reachable

### ISSUE THREAD

**Issue by SantiagoIvan** [sisoputnfrba/foro#1974]
Hola buenas noches ! Estoy corrigiendo memory leaks en la Comanda y tengo lo siguiente:

Contexto: Cree un pedido con 2 platos. Y al hacer ctrl+c tengo una funcion que catchea esa señal y usa los dictionary_Destroy_and_destroy_element para limpiar las tablas de segmentos y todo eso.

HEAP SUMMARY:
==9739==     in use at exit: 195,781 bytes in 215 blocks
==9739==   total heap usage: 753 allocs, 538 frees, 240,406 bytes allocated
==9739== 
==9739== LEAK SUMMARY:
==9739==    definitely lost: 0 bytes in 0 blocks
==9739==    indirectly lost: 0 bytes in 0 blocks
==9739==      possibly lost: 1,360 bytes in 5 blocks
==9739==    still reachable: 194,421 bytes in 210 blocks
==9739==         suppressed: 0 bytes in 0 blocks
==9739== Reachable blocks (those to which a pointer was found) are not shown.
==9739== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==9739== 
==9739== For lists of detected and suppressed errors, rerun with: -s
==9739== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)

Es lo unico que me salta. Por que es tan grande el 'still reachable' ?  no entiendo ni lo que es :(

**Comment by ncoen97** [comment]
Buenas, recuerden que además de hacer consultas a través del foro también deben usarlo como fuente de búsqueda de información. Dejo acá un ejemplo de esta consulta ya respondida https://github.com/sisoputnfrba/foro/issues/1606#issuecomment-609045706.
Saludos!

**Comment by SantiagoIvan** [comment]
Perdon! gracias :D
