### ISSUE TITLE
[Sindicato] Chequeo en la función guardar pedido

### ISSUE THREAD

**Issue by LeoCubelli** [sisoputnfrba/foro#1975]
Buenas, una consulta con la función guardar pedido, actualmente estoy verificando que el restaurante exista y que el pedido no exista para crearlo, también tengo que chequear que los platos del pedido estén en el menú del restaurante? Porque el enunciado no dice nada de eso. Saludos.

**Comment by mesaglio** [comment]
No hace falta, pero si queres hacer el chequeo lo podes hacer.

Saludos

**Comment by iago64** [comment]
@LeoCubelli Como va? Te quedo alguna duda?

**Comment by LeoCubelli** [comment]
No no, me olvidé de contestar nomás, gracias por la respuesta
