### ISSUE TITLE
Confirmar Pedido por parte de la APP

### ISSUE THREAD

**Issue by brunotello** [sisoputnfrba/foro#1976]
Hola!

Estabamos viendo con el equipo este mensaje y no entendemos para qué en el punto 1 mandar a la **Comanda** **Obtener Pedido** ya que no devuelve el Restaurante, sino el estado del Pedido y los platos. 
En la API directamente no dice nada que la App debe consultarle y no le vemos sentido. 

## App
![image](https://user-images.githubusercontent.com/9848247/99157993-ae928380-26ac-11eb-9eb4-4df24e719981.png)

## API
![image](https://user-images.githubusercontent.com/9848247/99158036-2496ea80-26ad-11eb-8b71-6409e84453d1.png)

# Edit:
Sería **Consultar Pedido** ?
![image](https://user-images.githubusercontent.com/9848247/99158137-696f5100-26ae-11eb-9f61-04512f804ec9.png)

**Comment by SantiagoIvan** [comment]
Me sumo a la primer consulta! No entiendo el propósito de obtener el pedido de la Comanda si luego  el mismo no lo utiliza. Es decir, obtiene el pedido de la comanda, y luego le manda el mensaje Confirmar Pedido, donde en la misma Comanda se realiza la verificación de que el pedido esté en estado PENDIENTE. Entiendo yo que el mensaje de obtener pedido en este caso estaría de más, podría directamente reenviar el mensaje "confirmar pedido"

**Comment by iago64** [comment]
Buenas!

La idea del Obtener Pedido a la comanda al momento de confirmarlo es que tienen que mandárselo al restaurante. No se olviden que _hasta este punto el restaurante no debería ni haberse enterado que hay un pedido en curso para el_, por lo que necesitan toda la info del restaurante para poder mandarle los platos que tiene que cocinar.
El tema de conocer el restaurante, no se olviden que ya el confirmar les viene de un cliente que _previamente selecciono un restaurante_.

Abrazo a la distancia!

**Comment by Roman-Petru** [comment]
Buenas! Me sumo a la consulta, esto no sería suficiente con mandar el mensaje "Confirmar pedido" al restaurante? Que de todas maneras hay que hacerlo, y la respuesta del restaurante a este mensaje es esta según el enunciado:

Confirmar Pedido
Siguientes pasos:
1. Obtener el Pedido desde el Módulo Sindicato.

Por lo que no veo la razón por la que le llegue dos veces por diferentes lados el Obtener Pedido al restaurante.

**Comment by RaniAgus** [comment]
Buenas! Me sumo a la duda, ¿no se supone que lo que se envía de App a Restaurante es solamente el mensaje "Confirmar Pedido"? Después el Restaurante obtendría el pedido desde el Sindicato, no necesita que la App se lo envíe.

Esto se puede hacer porque para los mensajes "Crear Pedido" y "Añadir Plato" la App los envía como "pasamanos" al Restaurante para que éste envíe "Guardar Pedido" y "Guardar Plato" respectivamente al Sindicato.

Por otro lado, en cuanto a la pregunta original, tenía entendido que el "Obtener Pedido" a la Comanda en el primer paso servía para verificar que ésta no lo haya borrado de la memoria.

Saludos!

**Comment by iago64** [comment]
Buenas! como va?

Acá tienen 2 cosas a considerar (porque el enunciado nos quedo algo flojo de papeles acá) y es que el obtener pedido puede responder a 2 problemáticas diferentes:

1.- Que el restaurante nunca se entero de que tenia un pedido (caso visto en algunos soportes)
2.- Confirmar que el pedido este tal cual creen que esta (No se olviden que un cliente puede conectarse a la comanda y mandarle fruta y agregarle platos nuevos) y desde el restaurante nunca les va a llegar la misma cantidad de platos listos que van a tener en la comanda por lo que el pedido jamás se va a completar.

Eventualmente, si no hacen el checkeo, van a tener una condición donde si alguien desde un cliente les agrega un pedido mas directo a la comanda, el repartidor de ese proceso va a morir por starvation esperando que se termine el pedido (del cual el restaurante cocino lo que se entero por el camino normal)

Abrazo a la distancia!

**Comment by RaniAgus** [comment]
> 1.- Que el restaurante nunca se entero de que tenia un pedido (caso visto en algunos soportes)

¿Podrías explicar más en detalle qué significa esto? O sea, sí, la planificación del Restaurante nunca crea ninguna estructura administrativa hasta que se confirme el pedido (recién ahí se crea el PCB). Pero, hasta ese momento, SÍ le llegaron los mensajes "Crear Pedido" y "Añadir Plato", por lo que SÍ se genera un ID nuevo, incrementando el contador y guardando todos los datos en el Sindicato a medida que se van cargando.

> 2.- Confirmar que el pedido este tal cual creen que esta (No se olviden que un cliente puede conectarse a la comanda y mandarle fruta y agregarle platos nuevos) y desde el restaurante nunca les va a llegar la misma cantidad de platos listos que van a tener en la comanda por lo que el pedido jamás se va a completar.

No es algo del flujo de ejecución normal, ¿tan malos van a ser de evaluar eso? :disappointed: 

> Eventualmente, si no hacen el checkeo, van a tener una condición donde si alguien desde un cliente les agrega un pedido mas directo a la comanda, el repartidor de ese proceso va a morir por starvation esperando que se termine el pedido (del cual el restaurante cocino lo que se entero por el camino normal)

Si el flujo de ejecución "normal" se vio alterado ya de antemano al haber cargado un "Guardar Plato" que no debimos haber cargado, ¿no se resolvería cargando uno o varios "Plato Listo" desde un Cliente conectado a App también para no causar esta starvation?

Igual lo que más me preocupa es esto:

> La idea del Obtener Pedido a la comanda al momento de confirmarlo es que tienen que mandárselo al restaurante.

¿Te referís a enviar estos campos desde App a Restaurante?: 
```
{estado, [{comida1, cantTotal1, cantLista1}, {comida2, cantTotal2, cantLista2}, ...]}
```
¿Sería un nuevo mensaje? Porque en el Anexo I no hay ninguno que envíe estos datos en este sentido ni viceversa. Solo se envían en "Consultar Pedido" y "Obtener Pedido", y el flujo es siempre Cliente-App-Comanda o Cliente-Restaurante-Sindicato.

**Comment by iago64** [comment]
Vamos en orden:
1.- Si hicieron el tp siguiendo las reglas al 100% de lo que esta detallado en el documento, en el crear pedido metimos la pata y en la V1 no decía que teníamos que avisarle al restaurante (fixeado a posteriori, pero nunca falta el caso donde algun grupo no se entero de que había una errata y se lo codeo como en la V1 y cayeron al checkpoint con eso mal) Y para no ser mala leche dijimos, ok, teniamos el consultar al inicio igual, que pase y fue.

2.- Los _casos borde_ como ese, generalmente los usamos cuando encontramos _algo raro_ en el código que tengamos que forzar, ejemplo, que pasa si iniciaron la planificación y de buenas a primeras, todo se queda frenado? la cpu les vuela al 100% o que pasa si por ejemplo en un momento tienen a todos los repartidores esperando cosas en restaurantes? son cosas que si hicieron las cosas bien y a conciencia no pasa nada, ahora si esta todo atado con alambre, te aseguro que explota (por eso les decimos que testeen a matar)

3.- Si, el mandar mensajes por fuera son alteraciones del "flujo normal" pero como dije antes, nos reservamos esas cosas para validar que estén haciendo las cosas de manera prolija y no sin haber corrido ni una sola vez valgrind o metiendo emparche tras emparche para "pasar la prueba"

4.- La info del pedido al restaurante _**SOLO** lo tienen que implementar si no están pasándole los mensajes de crear pedido / añadir plato al restaurante al momento de que le llegan a la App_, si eso esta hecho, pueden omitir el reenvio y solo lo consultan y lo loguean como:  Confirmamos este pedido que tiene estos platos y listo (Personalmente optaría por el pasamanos que es mas fácil, pero bueno, cada uno se complica la vida como quiere)

Por último, tengan en cuenta que ya hay pruebas subidas, no son las finales, pero les pueden dar una buena idea de como vamos a probar el TP, y si, falta una prueba completa donde tengamos todo conectado pero pueden imaginársela sin drama uds o esperar unos días a que terminemos de escribirlas 

Abrazo a la distancia.-

**Comment by RaniAgus** [comment]
Ahhhh ok! Entonces, si entendí bien, ese Obtener Pedido sirve para (dependiendo lo que diseñó cada grupo):
- Opción a (feliz): loguear que se confirmó un pedido con X platos, ya que al Restaurante ya se le pasó los mensajes Añadir Plato (Crear Pedido creo que sí sería obligatorio porque es el que retorna el ID, ¿cierto?)
- Opción b (rebuscado): Sirve para mandarle al Restaurante toda la info de los platos que no se le había mandado de antemano.

En cuanto a los chequeos, como ustedes digan, estaremos testeando esos casos entonces. :+1: 

Saludos!

**Comment by SantiagoIvan** [comment]
No entiendo algo, cuando se envia confirmar_pedido a la Comanda, se hace una serie de verificaciones que justamente cubririan el caso de que el pedido esté o no cargado en memoria, o exista la tabla de segmentos en memoria del restaurante, si por ejemplo no existe en memoria el pedido o el restaurante se envia ese detalle del error de la comanda (segun nuestra implementacion) por eso no me termina de cerrar el hecho de enviar el Obtener_pedido a la COMANDA desde la APP antes de enviarle el Confirmar_Pedido

**Comment by iago64** [comment]
@SantiagoIvan la idea es que las comprobaciones (y logs) las haga el módulo app, la comanda tiene sus validaciones despues que las va a manejar despues, pero minimo la app tiene que saber que esta confirmando ;)

**Comment by RaniAgus** [comment]
@iago64 igual, en los logs obligatorios de la App no veo que sí o sí haya que mostrar los platos del pedido confirmado, de hecho, no dice de loguear nada al confirmarse el pedido:

> 1. Cambio de un repartidor de cola de planificación (indicando la razón del porqué).
> 2. Movimiento de un repartidor (indicando la ubicación a la que se movió).
> 3. Operación de asignación de pedido (indicando la ubicación del mismo y el Restaurante correspondiente).
> 4. Operación de entrega de pedido (indicando el repartidor involucrado).

Lo más cercano sería el 3. que habla de "asignación de pedido". Igual tenía entendido que sería recién para cuando al pedido le es asignado un repartidor. Si no hay disponibles en ese momento, ese pedido quedaría a la espera, por lo que el log no aparecería al confirmar, sino un rato después.

@SantiagoIvan Ahora que lo decís, se me ocurre un caso en el que sí sería importante que la Comanda haga ese chequeo **antes** de enviar el Confirmar Pedido al Restaurante:
1. Creo un pedido desde un Cliente conectado directamente al Restaurante
2. Intento confirmar ese pedido desde otro Cliente conectado a App y que haya seleccionado al mismo Restaurante
3. App envía el mensaje al Restaurante, éste se lo manda al Sindicato y devuelve que está todo OK
4. App recibe ese "OK", crea el PCB y le manda la confirmación a la Comanda
5. La Comanda retorna "FAIL" recién **acá**

Entonces mientras el Restaurante se pone a preparar platos y enviar mensajes "Plato Listo" la App, ésta va a fallar cada vez que se lo reenvíe a Comanda. Mismo, cuando el repartidor llegue y envíe "Obtener Pedido", también va a fallar, y así.

**Comment by iago64** [comment]
@RaniAgus Si, que el log demore un toque no es taaan grave, lo importante es que este el log de que repartidor lleva que pedido 😄 
Respecto al caso que planteas en base al comentario de @SantiagoIvan sinceramente no teníamos pensada una prueba así de rebuscada. Gracias por la idea 😋 Igual tranqui, si no contemplaron un caso tan rebuscado tampoco se pongan a contemplarlo ahora, preocúpense por **todos** los mensajes y no solo por el confirmar, con que el confirmar haga que restaurante empiece a cocinar el plato vamos bastante bien 😉 

Abrazo a la distancia.-

**Comment by RaniAgus** [comment]
> Gracias por la idea :yum:

![image](https://user-images.githubusercontent.com/39303639/99260802-a5173180-27fa-11eb-9c47-ac390d4844f7.png)

**Comment by SantiagoIvan** [comment]
jajajajajajaja toda la comunidad sisop te agradece agus(?. Por mi parte ya no tengo dudas, asi que queda en bruno cerrar el issue

**Comment by iago64** [comment]
Tranqui, tenemos tantas cosas del camino feliz para testear que la prueba de agus no va a dar el tiempo a menos que necesitemos validar alguna situación muy muy especial como dije antes, por ejemplo una sincronización con sleep() en lugar de usar semaforos 😉 

Respecto a las dudas @brunotello si quedo algo pendiente por favor no te olvides de avisar.

**Comment by mesaglio** [comment]
Cierro por inactividad.
