### ISSUE TITLE
Sindicato - Guardar pedido

### ISSUE THREAD

**Issue by achoquemamani** [sisoputnfrba/foro#1977]
Buenas noches, una consulta con la función guardar pedido. En el anexo 2 y en el video "PedidOS Ya! File System" se muestra que la información de un pedido es la siguiente:
        ESTADO_PEDIDO=Confirmado
	LISTA_PLATOS=[Milanesa,Empanadas,Ensalada]
	CANTIDAD_PLATOS=[2,12,1]
	CANTIDAD_LISTA=[1,6,0]
	PRECIO_TOTAL=1150
Sin embargo, en el anexo 1 y en el enunciado de sindicato informa que "guardar pedido" está compuesto por el nombre del Restaurante y el ID de pedido.
Puedo pensar que en el anexo 1 hace referencia a la acción de "guardar pedido" y que el anexo 2 hace referencia al pedido como una entidad, si fuese así el caso como sindicato recibe la información presentada del anexo 2 del pedido?

**Comment by iago64** [comment]
Buenas!

Vamos por partes:
1.- El guardar pedido en la comanda lo que hace es crear la "base" del pedido, es decir, crear el archivo de metadata y no mas que eso.
2.- Los platos los va a ir incorporando de a poco con la llegada de los Guardar Plato.

La estructura final que se ve en el caso del video (y en los anexos) lo que busca es mostrar como quedaría el final del archivo del pedido una vez que llegaron el Guardar Pedido y algunos Guardar Plato.

Abrazo a la distancia!

**Comment by achoquemamani** [comment]
Ahh perfecto, cuando hablamos de crear el archivo de metadata del pedido:
1. nos referimos al archivo "[Punto_Montaje]/Files/Restaurantes/restaurante_generico/Pedido**n**.AFIP"?
2. Si fuese así, cómo creo el metadata y los bloques del pedido en sindicato:
       Propuesta A: pedido**n**.AFIP tendría la siguiente información
        SIZE=0
        INITIAL_BLOCK=_
        En este caso como su size es 0 initial_block no tiene ningún valor y por ende no se usa ningún bloque.
    
      Propuesta B: el pedido tendría la siguiente información por defecto que posteriormente se guardan en bloques 
        pedido**n**.AFIP tendría la siguiente información
        SIZE=84
        INITIAL_BLOCK= x
        En este caso como su size es mayor a 0, initial_block tendrá un dato número del primer bloque y se guardarán en 2 bloques. 
        Información del pedido al momento de crearse
        ESTADO_PEDIDO=""
	LISTA_PLATOS=[]
	CANTIDAD_PLATOS=[]
	CANTIDAD_LISTA=[]
	PRECIO_TOTAL=0

Saludos.

**Comment by iago64** [comment]
Buenas! 

Efectivamente es el archivo [Punto_Montaje]/Files/Restaurantes/restaurante_generico/Pedido**N**.AFIP

Respecto a como crearlos (en si asignarles o no bloques de entrada) mucho no nos metimos a definirles porque les vamos a tirar el guardar pedido y atras un par de guardar plato y vamos a ver la foto final, con lo cual, ambas opciones serían validas, fijate cual te resulta mas cómoda de implementar de entrada.

Abrazo a la distancia.

**Comment by achoquemamani** [comment]
Muchas gracias ;).
