### ISSUE TITLE
Sindicato - Modificar bloques

### ISSUE THREAD

**Issue by Nahuehernandez** [sisoputnfrba/foro#1978]
Buenas, tengo una duda a la hora de sobrescribir los bloques:

Cuando modifico un bloque (moviendo el puntero a donde quiero escribir y agregando los datos) y lo abro, éste me dice que no se puede leer, como si fuese binario. Entiendo entonces que no se debería modificar de esa manera.
Lo que se me ocurrió fue vaciar el bloque que contenga los datos a modificar y los bloques siguientes, y luego, volver a escribirlos todos y en caso de necesitar un nuevo bloque pedirlo normalmente.
Tiene sentido resolverlo de esa forma?

**Comment by iago64** [comment]
Buenas! 

Es raro el error que estas describiendo, tenes al menos el mensaje que te devuelve? Porque me huele mas a que es un tema de permisos, que un tema de como tenes escrito el bloque, ya que incluso por mas que sea un binario ejecutable, en linux si tenes permisos podes escribirle cosas en el medio (y si, somper el ejecutable).
Como pregunta rapida para descartar, al momento de crear los archivos de los bloques, los estan creando con `sudo` por casualidad?

Abrazo a la distancia.-

**Comment by Nahuehernandez** [comment]
Cuando abro el archivo desde el IDE me aparece esto: "El archivo no se mostrara en el editor porque es binario, muy grande o usa una codificación de texto no compatible". 
Para modificar los archivos de texto hago: fopen("", "w"), uso fseek para moverme y luego fprintf() para escribir.
Por otro lado respondiendo la ultima pregunta, no uso sudo, los creo directamente desde el código.

**Comment by iago64** [comment]
Ooook, ahora que decis el error tiene otro sentido diferente.
Lo que te dice ahi es que no lo puede interpretar nomas, eso puede venir por varios lados:
1.- Efectivamente se grabo mal, lo cual viene posiblemente asociado a `fprintf` por lo que te diría que veas de usar `fwrite` ya que `fprintf` al igual que printf va a tratar de interpretar la información que le pasas y vos como tenes parte texto y parte un numero en binario, queres que no interprete nada y lo grabe tal cual vos se lo decis.
2.- No estas teniendo espacio reservado en el archivo, esto lo podes checkear rapido tirando en una terminal un `ls -l` en la carpeta donde tenes los archivos con los bloques y ahi si no tienen el tamaño del bloque puede que por ahi venga el otro problema.

Por otra parte, si queres ver el contenido del archivo "sin interpretar" lo que podes hacer es tirar en una terminal el comando `hexdump -C` esto lo que va a hacer es devolverte el contenido del archivo en hexadecimal y al lado de cada linea en hexa la interpretación en ASCII (y eventualmente algún caracter medio falopa que son los caracteres no imprimibles que derivan del puntero al siguiente bloque)

Cualquier otra cosa que encuentres o si no te resuelve el problema lo que te comente avisa.

Abrazo a la distancia!

**Comment by mesaglio** [comment]
Buenas @Nahuehernandez, quedo solucionado este tema?

**Comment by Nahuehernandez** [comment]
Buenas, sisi ya está solucionado, me re olvide en responder.
