### ISSUE TITLE
[Comanda] Almacenar datos en TP 

### ISSUE THREAD

**Issue by faacumoral** [sisoputnfrba/foro#1980]
Hola! 
Quería consultar si es posible almacenar el nombre del plato en la Tabla de Páginas, como puntero al dato almacenado en el frame. 
Consulto puntualmente por el método guardar plato. La dude surge para localizar si el plato ya existe dentro de las tablas de páginas. Si no almaceno el nombre del plato (aunque sea como puntero al dato en el frame), debería recorrer todos los frames de la tabla de páginas para saber si el plato ya existe, lo que sería posible pero no sé si estaría correcto.
Gracias!

**Comment by ncoen97** [comment]
Buenas, el nombre del plato no se puede guardar en la tabla de páginas, lamentablemente la única forma de acceder al contenido de los platos es leyendo de memoria principal. Saludos!

**Comment by faacumoral** [comment]
Gracias por la respuesta, entonces la única forma de saber si un plato ya tiene su página sería ir recorriendo todos los frames asociados a ese pedido?

**Comment by iago64** [comment]
Exacto, la idea es que las estructuras de segmentos y paginas te ayuden a acotar la búsqueda, pero la información si o si tiene que estas en la memoria y no en las estructuras administrativas.

**Comment by faacumoral** [comment]
Perfecto, muchas gracias a ambos!
Cierro
