### ISSUE TITLE
[Restaurante] Campos ObtenerRestaurante

### ISSUE THREAD

**Issue by MaSosa314** [sisoputnfrba/foro#1981]
Buenas. Tengo un par de dudas con los campos del mensaje **ObtenerRestaurante**:

1) En los test se especifica una cantidad de cocineros y una lista de afinidades, que no necesariamente tienen que coincidir. Es decir, la cantidad de cocineros no necesariamente coincide con la cantidad de afinidades que hay en la lista. Dicho esto, ¿No le faltaria un campo `cantCocineros` al mensaje **ObtenerRestaurante**?
![image](https://user-images.githubusercontent.com/48865731/99531629-c7878700-2981-11eb-9a01-9f554c3a7a70.png)

2) No estaria entendiendo para que nos serviría la lista de recetas, ya que cada vez que un cliente consulta los platos de un restaurante, este se los solicita a la comanda:
![image](https://user-images.githubusercontent.com/48865731/99531892-31079580-2982-11eb-8457-4c2145db534d.png)

Y al momento de crear el PCB de un plato, para obtener la receta tambien se lo consulta al Sindicato:
![image](https://user-images.githubusercontent.com/48865731/99531998-5ac0bc80-2982-11eb-9ede-11eb1624ff7e.png)

Saludos.

**Comment by iago64** [comment]
Buenas! como va?

Si, efectivamente se nos escapo la cantidad de cocineros, agréguenlo :)

Principalmente porque queremos tener una forma de validar la información desde otro módulo (por ejemplo un cliente conectado directo al sindicato) para ver que crearon bien el restaurante según lo que ingresaron por consola.

Saludos.-

**Comment by MaSosa314** [comment]
Genial. Gracias por la respuesta rapida. Cierro el issue.
