### ISSUE TITLE
[App] Dudas sobre algoritmos

### ISSUE THREAD

**Issue by RaniAgus** [sisoputnfrba/foro#1982]
Buenas! Tengo un par de dudas cortitas sobre la planificación en la App:

1. ¿La información sobre la `estimacion_anterior` y la `ultima_rafaga` pertenecen al repartidor o al PCB? Por lógica diría que al repartidor, ya que es más interesante contar con un historial más largo a la hora de estimar, pero quiero asegurarme por las dudas ya que no encontré nada aclarado al respecto en el enunciado.

2. Si mi repartidor está en EXEC y llega al Restaurante, ¿debe salir de EXEC sí o sí independientemente de si el pedido está listo al "Obtener Pedido"? O sea, si está listo que vuelva a READY, y si no lo está que vaya a BLOCKED hasta que esté.

**Comment by iago64** [comment]
Buenas! como va?

1.- La idea es que la app planifica pedidos y los repartidores simplemente "ejecutan" (vendrían a ser algo así como las CPU)

2.- Siempre vas a desalojarlo de EXEC, idealmente pasa por "BLOCK", el tema es que si el pedido esta listo, se desbloquea instantáneamente (al igual que cuando haces un wait de un semáforo que esta disponible para ser tomado), con lo cual si esta listo, volvería a READY :wink:

Saludos.-

**Comment by RaniAgus** [comment]
1.- Ahhh okok, entonces obtenemos desde config la estimación inicial cada vez que querramos crear un PCB, tiene sentido.

Me marea un poco que los repartidores no son *tan* como una CPU porque en este caso tengo un límite en el grado de multiprocesamiento (los cocineros en el Restaurante sí serían CPUs). Hasta ahora lo estaba pensando como una especie de estructura intermedia entre el proceso y la CPU que limita el grado de multiprogramación (no me acuerdo si en la teoría había algo como eso :thinking: ).

2.- ¡Buenísimo! Me viene perfecto entonces

¡Saludos!

**Comment by RaniAgus** [comment]
Ah, me surgió otra duda respecto a esto. Con mi grupo estábamos pensando que en la cola de READY y BLOCKED lo que hay son repartidores en vez de PCBs. ¿Es válido hacer eso?

**Comment by iago64** [comment]
Aloha! Perdon la demora, estar hasta las manos de laburo no ayuda 😞 

1.- Si, el caso del repartidor es medio el gris que no nos gusta mucho, pero no te olvides que vos vas a tener el grado de multiprocesamiento definido por la cantidad de repartidores que vas a tener en la config de la app (no se los pusimos explicito como un parametro numérico nomas)

2.- Si, es valido, tene en cuenta que los PCBs se asocian a un repartidor en el momento que salen del restaurante.

Saludos.-

**Comment by RaniAgus** [comment]
> Aloha! Perdon la demora, estar hasta las manos de laburo no ayuda disappointed

No hay problema, tampoco era una duda muy urgente :+1:

> 1.- Si, el caso del repartidor es medio el gris que no nos gusta mucho, pero no te olvides que vos vas a tener el grado de multiprocesamiento definido por la cantidad de repartidores que vas a tener en la config de la app (no se los pusimos explicito como un parametro numérico nomas)

¿Puede ser que te estés refiriendo a los cocineros en el Restaurante?, porque en la App sí está:

*"Dado que nuestra aplicación tiene algunas limitaciones, se definirá por archivo de configuración el máximo de repartidores que podremos administrar simultáneamente (grado de multiprocesamiento); lo que definirá cuántos de nuestros repartidores podrán estar en el estado Exec al mismo tiempo."* (p.18)

![image](https://user-images.githubusercontent.com/39303639/99845871-1dac2400-2b54-11eb-96d7-a2da3961ef49.png)

> 2.- Si, es valido, tene en cuenta que los PCBs se asocian a un repartidor en el momento que salen del restaurante.

¡Buenísimo, gracias! Cierro issue

**Comment by iago64** [comment]
@RaniAgus Sabes que si, estaba 99% seguro que en app también teníamos "Cantidad de repartidores" en lugar de Grado de multiprocesamiento jaja
