### ISSUE TITLE
[Pruebas] Dudas pruebas avanzadas

### ISSUE THREAD

**Issue by RaniAgus** [sisoputnfrba/foro#1983]
Buenas! Tengo un par de dudas sobre la prueba completa:

1. Solo hay un único set de valores para los descansos en esta prueba, pero en el último paso dice esto:

> Volver a configurar FIFO en App y cambiar los descansos al segundo set de valores

2. Los restaurantes no tienen definido un `RETARDO_CICLO_CPU`. ¿Asumimos que es el mismo que la App o debe tener alguno en particular?

3. La Comanda y el Sindicato no tienen configs definidos. ¿Cualquier configuración es válida?

4. Veo que en simultáneo se están gestionando pedidos del Restaurante Default a la vez que hay otros restaurantes conectados. Tenía entendido que no se podía: https://github.com/sisoputnfrba/foro/issues/1895 (punto 2).

Saludos!

**Comment by iago64** [comment]
Buenas!!! Como va?

1.- Si tranqui, fue un pifie, la prueba completa originalmente era mas heavy pero me bajaron el pulgar y dijeron que para eso estaba la prueba de App y bueno, se nos escapo esa parte del enunciado

2.- Hablando de dedasos, nos quedamos con los algoritmos y se nos pasaron los retardos, eventualmente van en 5 (para que sean un cachito mas lentos) pero al final de cuentas si ven que las pruebas demoran mucho se pueden ajustar (la idea es que no esten mas de 30 min corriendo las pruebas el día de la entrega)

3.- Agregados en la V1.1, el sindicato solo tiene un puerto escucha que definen uds y un punto de montaje que tambien definen uds con lo cual, no nos cambia, solo pusimos en los configs los valores que necesitamos que estén seteados. En la comanda si, la idea es que sea una memoria grande que no se llene, como para probar que todo ande antes de pasar a medir cada módulo por separado.

4.- Un pifie a las apuradas, queriamos poner otro restaurante y nos quedo el default de la prueba de App, ya lo ajustamos en la V1.1 😄 

Abrazo y gracias por las observaciones :)

**Comment by RaniAgus** [comment]
Buenísimo! Gracias a ustedes por la rápida respuesta!
