### ISSUE TITLE
Duda con pruebas de CoMAnda

### ISSUE THREAD

**Issue by TheLucasPrada** [sisoputnfrba/foro#1984]
Buenas, estaba haciendo las pruebas de CoMAnda y me di cuenta que puede haber un error en las pruebas: para cuando llega la tanda de los 20 y pico de mensajes de PLATO LISTO, van a fallar todos porque en ningún momento se confirman los pedidos, asi que CoMAnda solo responde que no se pudo cumplir la solicitud. Medio raro, pero me imagino que no es eso lo que están queriendo probar una y otra vez.

Saludos!

**Comment by iago64** [comment]
Buenas! como va?

Efectivamente fue un pifie al redactar el enunciado, veniamos tan cebados haciendo el analisis de los reemplazos de paginas que nos comimos de lleno los mensajes que no accedian propiamente a los frames.
Ahi esta publicada la V1.1 de las pruebas donde lo agregamos :wink: 

Saludos.-

**Comment by SantiagoIvan** [comment]
es correcto que la cantidad de swapeos con ambos algortimos es la misma? Me está dando diferente por 1 :(

**Comment by iago64** [comment]
@SantiagoIvan Se te complica mucho subir el log de los reemplazos que hacen? capaz tiene que ver con la posición del puntero de clock_mejorado

**Comment by SantiagoIvan** [comment]
Dale, supongo que puedo subir el archivo por aca, lo que puedo hacer el filtrarlo y dejar todos los que estén relacionados con el swapeo

**Comment by iago64** [comment]
Si, por favor solo que quede lo relacionado a swap, porque nos vamos a volver changos y la idea es constatar esto para quedarnos tranquilos de cuales son las cuentas correctas 😉

**Comment by TheLucasPrada** [comment]
genial, gracias! ahí le echo un ojo a la nueva versión.

Saludos!
