### ISSUE TITLE
[Restaurante] Cantidad de cocineros y cantidad de afinidades

### ISSUE THREAD

**Issue by Maldonado-J** [sisoputnfrba/foro#1986]
Buenos días. Partiendo del hecho que la cantidad_cocineros no necesariamente se corresponde con la cantidad de afinidades de un restaurante. Suponiendo que tenemos ```cantidad_cocineros = 5, afinidades=[Empanar, Fritar]```

<ol>
<li> Estría bien asumir que hay que asignar un cocinero por afinidad y los cocineros "sobrantes" deberian cocinar platos sin afinidad, cierto? #1958</li>
<li> Nosotros teníamos definido una correlación entre la cantidad de colas de Ready y la cantidad de hilos de Ejecución, pero si es como se plantea en el punto 1, </li>
<ol>
<li>Deberíamos tener más hilos de Ejecución, sin hacer una correlación de 1:1? Es decir, un hilo_empanar, hilo_fritar y otras tres hilos_ejecucion_sin_afinidad para los cocineros extras?</li>
<li>O estaría bien simplemente tomar tantos platos de la cola_ready_sin_afinidad como cocineros tenga libre? Entonces, si tengo 3 cocineros sin afinidad, tomo 3 platos de esta cola y los mando al mismo hilo_sin_afinidad. Esto me parece más simple y se ajusta a lo que tenemos pero me preocupa que no sea tan "paralelo" </li>
</ol>
</ol>

**Comment by iago64** [comment]
Buenas!

Efectivamente, la cantidad de afinidades no siempre va a ser la misma que la cantidad de cocineros, con lo cual, la forma de implementarlo ahí queda a criterio de uds. 
Yo personalmente les recomendaría tener 1 cola por afinidad y una general para todos los demás platos porque si no después sincronizar y mandar correctamente los platos sin afinidad, me parece que va a ser un caos.

Abrazo a la distancia!

**Comment by Maldonado-J** [comment]
Entiendo.
Entonces para hilos puedo plantear la misma idea y hacer una correlación 1:1, no? hilo por afinidad + hilo sin afinidad (donde corre la función de planificacion

**Comment by iago64** [comment]
Ahí la idea sería que cada hilo represente un cocinero y te haria sincronizar la cola de ready de los que no tienen afinidad.

**Comment by Maldonado-J** [comment]
listo, entonces! cierro el issue. muchas gracias :)
