### ISSUE TITLE
[Sindicato] Por bloques FS

### ISSUE THREAD

**Issue by AgustinBer** [sisoputnfrba/foro#1987]
Hola! Quería consultar una duda sobre los bloques del FileSystem. En la consigna dice que no se utiliza un nuevo bloque hasta completarse el anterior. Pero no aclara lo siguiente, si tenemos un pedido 1 que ocupa 1 bloque y medio, el pedido 2, debe comenzar en la mitad del segundo bloque (a continuacion del Pedido 1) o en el tercer bloque? Podria tambien haber almacenada una receta y un pedido (por partes) en un mismo bloque? 

Desde ya muchas gracias,
Agustin

PD: Perdón por no ponerle label al issue, no sé como hacerlo

**Comment by iago64** [comment]
Buenas!
Una contrapregunta rapida, los archivos en cualquier FS (EXT, NTFS, FAT, BTRFS) comparten bloques?

No te olvides que al final del día los pedidos son archivos diferentes y que la aclaración de que ocupen todo el bloque viene dada para que no corten los archivos por `\n` y que respeten mas a la teoría.

Saludos.-
