### ISSUE TITLE
[Comanda] Puntero de CM tras finalizar pedidos

### ISSUE THREAD

**Issue by foviedo** [sisoputnfrba/foro#1988]
Buenas! Una consulta. Cómo se comporta el puntero del algoritmo de clock mejorado después de que se finaliza un pedido? No estoy seguro de haberlo visto en la teoría
Gracias de antemano

**Comment by ncoen97** [comment]
Buenas, el puntero es independiente de lo que pase con los segmentos/paginas, mientras lo vayan moviendo cuando buscan una victima y lo dejen en la posición siguiente cuando realizan el reemplazo no van a tener problema.
Saludos!

**Comment by foviedo** [comment]
Gracias!
