### ISSUE TITLE
Problemas con Finalizar Pedido

### ISSUE THREAD

**Issue by Roman-Petru** [sisoputnfrba/foro#1989]
Buenas! Estamos teniendo problemas con este mensaje, que según el anexo del enunciado es:

"Descripción: el módulo App, una vez que finalice un pedido, se lo deberá informar al módulo Comanda a través del mensaje ‘Finalizar Pedido’, indicando el ID del pedido y el Restaurante correspondiente. 
Módulos que reciben el mensaje: 
Comanda
Cliente"

Este mensaje lo recibe el cliente, sin embargo el cliente no puede tener servidor, y además en nuestra implementación elegimos abrir un socket para cada mensaje-respuesta y luego cerrarlo, por lo tanto para este mensaje creamos un hilo nuevo en el cliente que mande el mensaje y se quede esperando la respuesta hasta que terminen las planificaciones. Hasta acá todo muy bien, pero cuando la app termina su plani, le manda la finalizacion a la comanda, y luego devuelve la respuesta al Cliente, al cliente nunca le llega (el hilo que estaba esperando no hace nunca el "recv" y no puede avanzar). 

Lo más raro de todo esto es que cuando se hace con el Restaurante_Default anda perfecto, y cuando el cliente se conecta directamente al Restaurante que usa la misma lógica, y los mismos mensajes para finalizar el pedido también anda perfecto.

Como no lo podíamos solucionar probé otras variantes como usar señales (con las syscalls de get thread id y thread kill), en donde anduvo correctamente, y también estaba la idea de directamente hacerle un servidor al cliente y agregarlo en el archivo de configuración, pero no sé si eran soluciones válidas así que lo quería preguntar por acá.

Y si no quería consultar si hay alguna manera de hacer algún error handling dentro del propio "recv" (perror no funcionaria porque nada da error, simplemente el hilo queda bloqueante en el recv), para al menos poder tener una idea de que puede estar fallando, si por algún motivo X se rompió el socket en medio de la planificación o algo. Del lado de la app que hace el send tampoco muestra ningún error.

Perdón por la pregunta tan larga y tanto texto, fueron muchas horas debuggeando y ya no sé a dónde acudir.

**Comment by iago64** [comment]
Buenas!

No me termina de quedar claro el problema, lo que entiendo es que cuando el cliente se conecta directo al restaurante no hay problema porque es todo sincrónico, pero cuando tienen que pasar por la app no?

Eventualmente no te olvides que el enunciado les permite crear mas de una conexión entre los módulos y dejar una en un recv a la espera de eventos asincrónicos.

Saludos.-

**Comment by Roman-Petru** [comment]
> Buenas!
> 
> No me termina de quedar claro el problema, lo que entiendo es que cuando el cliente se conecta directo al restaurante no hay problema porque es todo sincrónico, pero cuando tienen que pasar por la app no?
> 
> Eventualmente no te olvides que el enunciado les permite crear mas de una conexión entre los módulos y dejar una en un recv a la espera de eventos asincrónicos.
> 
> Saludos.-

Perdón no lo expliqué muy bien, estamos creando mas de una conexión entre los módulos (entre la app y el cliente) dejando una en un recv a la espera, el problema es que después del send del otro lado (el cual ya lo chequie y el perror del send da "succes"), el hilo que estaba con el recv a la espera no se entera de nada y sigue bloqueado.

Pero en otros casos, por ejemplo cuando probamos con el Resto_Default anda todo correctamente.
O el otro caso, en el que el Cliente se conecte directamente al Restaurante, en donde el mensaje también es asincrónico (ya que tiene que esperar a que termine la planificación de todos los platos para devolverle Finalizar Pedido al cliente) funciona correctamente.

Por eso la consulta viene más por el lado de como debuggear o como hacer algún tipo de error handling con el recv, o si alguna de las otras opciones que había planteado para solucionarlo eran "legales" de usar en el tp.

**Comment by iago64** [comment]
Mmm lo que decís me da que pensar a que del lado que envías no estas enviando todo lo que el recv() espera recibir o que tenes algún semáforo medio extraño bloqueando las cosas, eso ultimo lo podes checkear relativamente rápido con helgrind (como usarlo esta en el video de valgrind que esta en el [canal de youtube](https://www.youtube.com/c/utnso)).

Saludos.-

**Comment by Roman-Petru** [comment]
Bueno gracias, vamos a seguir tratando de descubrir cuál es el inconveniente!

**Comment by iago64** [comment]
@Roman-Petru Pudiste encontrar el inconveniente?

**Comment by Roman-Petru** [comment]
No pude, pero igual utilicé un método alternativo.
Gracias y cierro el issue!
