### ISSUE TITLE
Problemas con el deploy

### ISSUE THREAD

**Issue by RaniAgus** [sisoputnfrba/foro#1991]
Buenas! Estamos probando deployar el TP en la Ubuntu Server y nos surgieron varios problemas que no sabemos cómo resolver. Aclaro que estamos usando el script provisto por la cátedra (https://github.com/sisoputnfrba/so-deploy), e hicimos los makefiles que compilan bien (si necesitan más contexto despúes se los paso). Tiramos estos comandos:
```
git clone https://github.com/sisoputnfrba/so-deploy
cd so-deploy
sudo ./deploy.sh -d=cshared -p=app -p=comanda -p=cliente -p=restaurante -p=sindicato tp-2020-2c-Segundo-Saque
```

El problema es que necesito hacer `sudo` para todo lo que quiera hacer:

1) Quiero crear un log y abrirlo para escritura y me aparece esto:
```
Cannot create/open log file: Permission denied
```
2) También tengo scripts para configurar en forma automática cada test usando el comando `sed`, que me funcionan en la VM con entorno gráfico pero en la server me aparece:
```
sed: couldn't open temporary file app/sedUYwjzC: Permission denied

```

Un detalle: Si quiero crear un archivo haciendo `touch` adentro de la carpeta "tp-2020-2c-Segundo-Saque" no me deja, pero fuera de ella sí, ¿cómo puedo corregir esto?

Saludos!

**Comment by mgarciaisaia** [comment]
Agus, hacé `ls -l` del directorio de tu repo.

Lo más probable es que lo hayas clonado con `sudo` (es decir, hiciste `sudo git clone https://github.com/sisoputnfrba/TU_REPO`), y, entonces, el directorio lo creó el usuario `root` (porque hiciste `sudo` a ese usuario). Como el owner del directorio es `root`, el usuario `utnso` no tiene permisos para escribir en ese directorio - y por eso tenés que seguir metiendo `sudo` en todos lados.

La forma de evitar este problema es clonar el repo **sin** `sudo`. Es decir, hacer `git clone https://github.com/sisoputnfrba/TU_REPO` y ya.

La forma de _solucionarlo_ es hacer `sudo chown -R utnso:utnso /path/a/tu/directorio`, para que el directorio (y todo su contenido) pase a ser del usuario `utnso`. Acá sí necesitás meter `sudo` porque, como el directorio _actualmente pertenece a `root`_, el usuario `utnso` no tiene permisos para modificarlo (justamente, el origen de todo esto).

**Comment by RaniAgus** [comment]
Ahhh, ¡genial Mati! Más sencillo: lo que hicimos fue ejecutar `deploy.sh` sin sudo, o sea:
```
git clone https://github.com/sisoputnfrba/so-deploy
cd so-deploy
./deploy.sh -d=cshared -p=app -p=comanda -p=cliente -p=restaurante -p=sindicato tp-2020-2c-Segundo-Saque
```
Por lo que ahora sí el repo se clona correctamente y se pueden ejecutar todos los archivos sin requerir permisos de root. 

El nuevo problema que estamos teniendo es que para instalar la dependencia `cshared` (nuestra shared library), [el script hace make install sin sudo](https://github.com/sisoputnfrba/so-deploy/blob/1c4087c2a5325ba65849502b7f22d2c28b25439d/deploy.sh#L117), y nosotros dentro de la regla install pusimos que se copiara la library a `usr/lib` y los headers a `usr/include` (igual que hacen las commons), y no tenemos permiso para hacerlo.

¿Es un problema del script o nuestro? ¡Saludos!

**Comment by mgarciaisaia** [comment]
Ahh qué gil, no vi que pusiste explícitamente el `sudo ./deploy.sh` ahí arriba. Sí, como regla general: las cosas sin `sudo` hasta que se demuestre lo contrario.

Respecto al `make install`, ese sí debería ser con `sudo`, en general, porque solés querer escribir en `/usr/lib` y otros directorios compartidos. Digamos, haría primero un `make` (para que, con el usuario común, genere los binarios y blah), y después un `sudo make install` (para que copie esos archivos a las rutas de sistema).

Llamarlo "bug" le queda grande. Diría que es, nomás, una incompatibilidad entre los dos scripts. Cuál tiene razón, ni idea - depende de qué tomes como "verdad".

Pero buen, sí, en algún lado tenés que resolverlo. Forkeate el script, o cambialo en tu código - o ambas.

Si el `so-deploy` debiera o no hacer `sudo make install`, charlalo con Fede o quienes estén manteniendo ese repo 😇

**Comment by RaniAgus** [comment]
Oki, lo que haré por ahora (y lo dejo por si a alguien le sirve) es usar el comando `sed` para editar esa línea del script en el momento:
```
sed -i "117s/.*/  sudo make install/" deploy.sh
```
Entonces los pasos a seguir que me quedaron serían:
```
git clone https://github.com/sisoputnfrba/so-deploy
cd so-deploy
sed -i "117s/.*/  sudo make install/" deploy.sh
./deploy.sh -d=cshared -p=app -p=comanda -p=cliente -p=restaurante -p=sindicato tp-2020-2c-Segundo-Saque
```

En un rato subo el issue en aquel repo para charlar sobre si el `deploy.sh` debe hacer `sudo make install` o no

Gracias por la *rapidísima* respuesta!

**Comment by RaniAgus** [comment]
Comento otra forma mucho mejor y menos rebuscada de hacerlo: agregando el `sudo` dentro de la regla install:
```
install: all
	sudo cp -u lib$(LIBRARY_NAME).so /usr/lib
	sudo cp --parents -u $(DEPS) /usr/include
```
