### ISSUE TITLE
[Pruebas] Posible error en la prueba de App

### ISSUE THREAD

**Issue by RaniAgus** [sisoputnfrba/foro#1992]
¡Buenas! Perdón por la hora :sweat_smile: pero acabamos de hacer el test de App con los repartidores y nos dimos cuenta de algo:

- Un detalle menor: el mapa no se condice al 100% con lo que dice el config, ya que el repartidor C es el segundo [7,8] y el repartidor B es el tercero [1,4].
- Un detalle no tan menor: en los resultados esperados dice que 

> _En la segunda etapa con las frecuencias de descanso bajas, los repartidores deberían al menos descansar 1 vez en toda la ejecución._

Pero si uno se pone a analizar los movimientos, los repartidores B y C no llegan a completar los pasos suficientes para entrar en descanso:

C) Arranca en [7,8] -> Se mueve a RD [5,5] (5 pasos) -> Se mueve a C2 [4,4] (2 pasos) -> Total 7 pasos (descansa cada 8)
B) Arranca en [1,4] -> Se mueve a RD [5,5] (5 pasos) -> Se mueve a C3 [2,1] (7 pasos) -> Total 12 pasos (descansa cada 13)

¿Efectivamente es un error o no estamos teniendo en cuenta algo?

¡Saludos!

**Comment by iago64** [comment]
Holis!

Las pruebas tienen chances de estar erradas, y este es el caso, nos quedamos con el mapa de la prueba completa 😢 
Ahora vamos a estar bajando las frecuencias de descanso para que si descansen al menos una vez 😉 
Mil gracias por el aviso.

Abrazo a la distancia!

**Comment by RaniAgus** [comment]
Oki, ¡gracias!
