### ISSUE TITLE
Guardar_plato Comanda + clock modificado

### ISSUE THREAD

**Issue by SantiagoIvan** [sisoputnfrba/foro#1993]
Buenas noches. Me encuentro con el siguiente problema, la cantidad de swaps del LRU me da 10, pero la del clock me da 12.
Llegué a la conclusión de que es por una parte del enunciado que la interpreté de otra forma y es por eso que me da ligeramente diferente, asi que voy a citar una parte del enunciado:

**Guardar_plato**:
1_ Verificar si existe la tabla de segmentos de dicho Restaurante. En caso de no existir se deberá informar dicha situación.
2_ Verificar que exista el segmento de dicho pedido dentro de la tabla de segmentos del Restaurante. En caso de no existir se deberá informar dicha situación.
3_ Verificar si existe el plato dentro de la tabla de páginas del pedido. En caso contrario, se deberá asignar una nueva página al segmento. 
4_ En caso de que la página que corresponde al pedido no se encuentre cargada en memoria principal, se deberá cargar la misma desde swap (iniciando la elección de víctima de ser necesario). En caso contrario, proceder al paso  número 5.
5_ Se deberá agregar el plato y anexar la cantidad que se tiene que cocinar de dicho plato.
Responder el mensaje indicando si se pudo realizar la operación correctamente (Ok/Fail).

El paso 4 me indica que si no hay espacio en memoria principal para cargarla directamente tengo que iniciar el proceso de Swap, en caso contrario, procedo al paso número 5.
El tema viene ahora:
"Se deberá agregar el plato y anexar la cantidad que se tiene que cocinar de dicho plato."
Lo que yo interpeto de ésto es que primero lo cargo en memoria principal y LUEGO le sumo la cantidad pedida al plato, ya que me dice que agregue el plato y que anexe la cantidad, que sería diferente a "agregar el plato con la cantidad ya anexada"
Debido a esta interpretación que tuve yo, y para seguir la secuencia de pasos del enunciado, primero cargo los platos con cantidad 0 y luego le sumo la cantidad pedida. Por lo tanto, cada vez que guardo un plato, al finalizar el proceso, termina con el bit de modificación en 1 y no en 0 como tienen algunos compañeros mios. 
En fin, la suma me da 12 swaps por clock si no me equivoqué en ninguna cuenta.

**Comment by TheLucasPrada** [comment]
Es una buena pregunta, yo ni lo tuve en cuenta ese caso, pero si, entiendo que si ya tenias una cantidad X en un plato que ya existe en memoria, y te piden aumentar la cantidad de platos pedidos, esa pagina tendría que tener el bit de modificación en 1.

A menos que algún ayudante diga lo contrario, cambio mi código.
Gracias por el post, que sino lo iba a tener mal jaja

**Comment by iago64** [comment]
Buenas! como va?

No hace falta que lo hagas en 2 momentos por separado, porque la idea del Guardar_plato es que se haga todo de una (cargar la pagina y sumar), por lo que el resultado es el mismo, swap (si hace falta) y dejas la pagina marcada como usada y modificada en la memoria.

Saludos.-

**Comment by iago64** [comment]
Buenas!

Gracias a @ncoen97 que me tiro un centro impecable me hizo darme cuenta que la pifie y que tenemos que separar el análisis en 2 partes:
1.- Pagina completamente nueva -> Tiene que quedar como modificada en 0 ya que se cargaría modificada directo en swap y en memoria principal
2.- Pagina que esta en swap y no en memoria principal, al momento de cargarla, la traes tal cual esta en swap y ahí si le incrementas y ahí si te quedaría modificada la página.

Saludos y perdón por el pifie :)

**Comment by ncoen97** [comment]
Buenas, para la próxima cuando la duda queda resulta ya pueden cerrar el issue. Saludos!
