### ISSUE TITLE
Arquitectura Cliente-Usuario para cada módulo

### ISSUE THREAD

**Issue by julchat** [sisoputnfrba/foro#1994]
Hola, queremos probar nuestras cosas y queríamos ver si la arquitectura con la que estamos trabajando ahora es válida para las consignas del tp, y de paso confirmar a que se refiere cada proceso con que sea multihilo.

Módulo cliente:
Se conecta al módulo que tiene en la config, y utiliza un único socket con este para iniciar conversaciones (una conversacion es el ciclo de mandar mensajes y conseguir una respuesta) y otro para esperar conversaciones. Entonces, cada vez que yo mande un mensaje por consola, bloqueo un mutex para ese socket para que no me interrumpan la conversación, y hasta que no reciba respuesta para esa conversacion, no finalizo el hilo del mensaje ni libero el mutex del socket

Módulo comanda: levanta un servidor para la app, y por cada conexion que llegue, tengo un socket distinto. El otro modulo, por otro lado, tendrá un único socket para comunicarse conmigo. comanda estará escuchando en bucle recibiendo mensajes, hasta que llegue uno erroneo donde procedera a cerrar ese socket.

Módulo app: levanta un servidor para los distintos clientes y para los distintos restaurantes, y por cada conexion que llegue, tengo un socket distinto. Tengo un socket único para comanda

Módulo restaurante: levanta servidor para los distintos clientes. Tiene un único socket por ser cliente con restaurante y con sindicato.

Módulo sindicato: Debe ser capaz de atender, como comanda, varias conexiones, por lo que levanto un servidor que funcionará idénticamente al de comanda.

Ahora bien, cual es el sentido de que cliente sea un proceso multihilo, si solo voy a tener un socket para iniciar conversaciones en el que solo puedo llevar a cabo una conversación (con un hilo) al mismo tiempo?

Como cierro la ejecución normal de restaurante, comanda, y app?

EXTRA: hay alguna forma de probar restaurante sin que ande sindicato?

**Comment by ncoen97** [comment]
Buenas!

Módulo cliente: Acá me parece que el problema es que si yo envío un comando al cliente, voy a tener la consola bloqueada hasta que se realice todo el flujo de ese mensaje. Lo correcto sería que cuando "inician conversaciones" lo hagan a demanda y vayan abriendo nuevos sockets con las nuevas consultas, así van a tener la consola sin bloqueo. Respondiendo a la pregunta que viene mas adelante, los hilos que tendrían son: uno para la consola, otro para escuchar conversaciones y varios para iniciar conversaciones,

Modulo Comanda/App: Bastante parecido al anterior, acá deben aprovechar el hecho de que la comanda es multihilo y abrir conexiones a demanda para tener consultas paralelas.

Modulo Restaurante/Sindicato: Lo mismo al caso de Comanda/App, el servidor de Sindicato es multihilo por lo que pueden tener consultas paralelas.

El tema de cerrar las conexiones no es del todo necesario porque los módulos que tengan servidor mientras estén activos van a estar escuchando conexiones. Si quieren pueden agregar alguna lógica para cortarlo (o más simple, usar el famoso `ctrl c`).

EXTRA: No hay forma de probar Restaurante sin sindicato porque necesita la metadata inicial.

Saludos!

**Comment by julchat** [comment]
Buenisimo! Todo claro y listo para corregir
