### ISSUE TITLE
Config de conexiones

### ISSUE THREAD

**Issue by Maldonado-J** [sisoputnfrba/foro#1995]
Hola! Tenemos una consultilla sobre las configs de los modulos.

Hoy nos presentamos a la entrega final y fue un poco un lio cambiar todos los IPs a los de las máquinas virtuales. Una solcuión que se nos ocurrió es crear un archivo config nuevo donde tengamos todos los datos de conexión y que cada modulo levante dos config, uno de conexión (ips y puertos) y otro propio del módulo.

La pregunta es, tenemos permitido modificar los archivos de config de cada módulo para hacer esto? O no podemos modificar los campos dados en el enunciado?

**Comment by iago64** [comment]
Buenas!

En cuanto a los configs, pueden hacer lo que necesiten, de todas formas, para editarlos pueden usar `nano` que es un editor bastante simple que ejecuta en terminal (y así se evitan tener 90 archivos diferentes).

Saludos.-

**Comment by Maldonado-J** [comment]
Dale, gracias! Cierro
