### ISSUE TITLE
Consulta de recorrido no contemplado con Obtener Pedido en CoMAnda

### ISSUE THREAD

**Issue by TheLucasPrada** [sisoputnfrba/foro#1996]
Buenas! una consulta: mientras estábamos haciendo testeos se me ocurrió mandar un Obtener Pedido, de un pedido que no tenia ningún plato cargado todavía, lo que obviamente devolvió basura porque nunca lo contemplé.

Porque las únicas verificaciones que hacemos son: si existe el restaurante y si existe el pedido. El enunciado no dice nada sobre que haya o no haya platos ya cargados al pedido, por lo que la pregunta es: Que tendría que devolver? cantidades pedidas y preparadas en 0 y los nombres de platos vacío?

Saludos,
Lucas

**Comment by iago64** [comment]
Buenas! como va?

Eventualmente si nunca agregaron ningún plato, no deberían devolver nada, ya que ni tienen paginas asignadas.
De todas formas es un caso super borde que no esta ni contemplado en las pruebas :)

Abrazo.-

**Comment by TheLucasPrada** [comment]
Genial, gracias!
