### ISSUE TITLE
[Sindicato] Consulta guardar plato

### ISSUE THREAD

**Issue by RaniAgus** [sisoputnfrba/foro#1997]
¡Buenas! Tenemos una duda sobre el mensaje `guardar_plato(...)` y los chequeos que hay que hacer.
La consigna dice lo siguiente:

> 1. Verificar si el Restaurante existe dentro del File System. Para esto se deberá buscar dentro del directorio Restaurantes si existe un subdirectorio con el nombre del Restaurante. En caso de no existir se deberá informar dicha situación.
> 2. Verificar si el Pedido existe dentro del File System. Para esto se deberá buscar dentro del directorio del Restaurante si existe dicho pedido. En caso de no existir se deberá informar dicha situación.
> 3. Verificar que el pedido esté en estado “Pendiente”. En caso contrario se deberá informar dicha situación.
> 4. Verificar si ese plato ya existe dentro del archivo. En caso de existir, se deberán agregar la cantidad pasada por parámetro a la actual. En caso de no existir se deberá agregar el plato a la lista de Platos y anexar la cantidad que se tiene que cocinar de dicho plato y **aumentar el precio total del pedido.**
> 5. Responder el mensaje indicando si se pudo realizar la operación correctamente (Ok/Fail).

En el paso 4 dice que se debe "aumentar el precio total del pedido". ¿Eso significa que hay que levantar el archivo "Info.AFIP" de ese Restaurante? De paso, ¿no se debería haber verificado antes (entre el paso 3 y 4) que el Restaurante pueda planificar ese plato, y ahí obtener su precio para luego sumarlo?

¡Saludos!

**Comment by ncoen97** [comment]
Buenas.
El chequeo de si el Restaurante tiene ese plato no lo exigimos en el enunciado, no vamos a ingresar platos que no pueda cocinar ese Restaurante, pero si quieren hacer esa validación buenísimo. Al archivo de metadata del restaurante van a tener que acceder de todos modos para leer el precio del plato, si les parece mejor hacerlo en el paso anterior y ya traerse ese precio no hay problema.
Saludos!

**Comment by RaniAgus** [comment]
Buenísimo, gracias!
