### ISSUE TITLE
[Comanda] Plato Listo

### ISSUE THREAD

**Issue by damianmasi** [sisoputnfrba/foro#1998]
Buenas, mi consulta es sobre la función plato listo, en el enunciado dice lo siguiente:

4. En caso de que las páginas que corresponden al pedido no se encuentren cargadas en memoria principal, se deberán cargar las mismas desde swap (iniciando la elección de víctimas de ser necesario). En caso contrario, proceder al paso  número 5.

Nuestra duda es que teniendo en cuenta que tenemos una estructura administrativa (la tabla de segmentos) donde podemos verificar cual es la pagina que queremos modificar, no podemos traer únicamente esa pagina, en vez de traer todas las paginas del pedido

**Comment by iago64** [comment]
Buenas!

Tienen que traer todo porque la estructura administrativa no sabe (**o no debería saber**) cuales son los datos que contiene cada página, simplemente debería saber de índices y posiciones.

Saludos.-

**Comment by damianmasi** [comment]
Gracias
