### ISSUE TITLE
[COMMONS] Duda sobre una funcion de listas.

### ISSUE THREAD

**Issue by iancrespiok** [sisoputnfrba/foro#1999]
Hola como estan? Teniamos esta duda sobre la funcion list_remove_by_condition(2) que no sabemos como pasar un parámetro extra. En el test que hay en github de la library de list unicamente muestran un ejemplo donde el nombre de la funcion _is_gaston() esta hardcodeado, la modificamos para ver si funcionaba agragando un parametro al final y cuando compilamos nos dice que le estamos pasando pocos parametros a la funcion, como si no entendiese que el primer parametro es el de cada elemento de la lista. 

![Screenshot_1](https://user-images.githubusercontent.com/30092896/101097683-63c7a580-35a0-11eb-8da3-5cbaaa02d2b0.png)
.githubusercontent.com/30092896/101097481-fd428780-359f-11eb-892e-a51e5b3a4ec1.png)

**Comment by ncoen97** [comment]
Buenas.
Lo que les recomiendo hacer es definir la función `_is_gaston` adentro del scope de la función en donde la estén llamando. Así van a poder hacer referencia al `char* nombre` desde adentro de `_is_gaston` sin tener que recibirla por parámetro.
Saludos!

**Comment by iancrespiok** [comment]
Genial, se me habia ocurrido pero no sabia que se podia. Seria tan facil como hacer una funcion "dentro" de otra usando una variable como "global" dentro de esa funcion contenedora o hay alguna otra cosa a tener en cuenta?

**Comment by mgarciaisaia** [comment]
Acá está [la doc sobre nested functions](https://gcc.gnu.org/onlinedocs/gcc/Nested-Functions.html). Son una extensión de `gcc`, [no son parte del estándar de C](http://stackoverflow.com/a/2608167/641451). Pero, sí, es la forma en que las commons esperan que interactúes con ellas.

**Comment by mesaglio** [comment]
Quedo resuleto el tema @iancrespiok
