### ISSUE TITLE
[Sockets] Duda getaddrinfo()

### ISSUE THREAD

**Issue by RaniAgus** [sisoputnfrba/foro#2000]
¡Buenas!
El sábado pasado nos hicimos algo de lío con el tema de crear un server en las VMs y conectarnos en red, ya que en un sábado de soporte surgió la pregunta sobre por qué los configs no tienen la IP propia de los servers que crean, y la respuesta (que tiene sentido) es que no la necesitan, ya que los servidores se `bind()`ean a un puerto local y `accept()`an a los clientes que se `connect()`en a él. El tema es que no profundizamos mucho en el tema y dejamos hardcodeado "localhost":
```
struct addrinfo hints;
struct addrinfo* serverInfo;

memset(&hints, 0, sizeof(hints));
hints.ai_family   = AF_UNSPEC;
hints.ai_socktype = SOCK_STREAM;
hints.ai_flags    = AI_PASSIVE; // Siempre estamos pasando el flag AI_PASSIVE

int err = getaddrinfo("localhost", port, &hints, &serverInfo);

/* socket(), setsockopt(), bind() y listen() */
```
Esto al uno hacer pruebas localmente funcionaba, pero al intentarse conectar en red no.

Entonces, haciendo una leída rápida al [man](https://man7.org/linux/man-pages/man3/getaddrinfo.3.html) de `getaddrinfo(4)` hay un párrafo que menciona la que parecería ser la solución correcta para crear un server:

> **If the AI_PASSIVE flag is specified in hints.ai_flags, and node is
>        NULL, then the returned socket addresses will be suitable for
>        bind(2)ing a socket that will accept(2) connections.**  The returned
>        socket address will contain the "wildcard address" (INADDR_ANY for
>        IPv4 addresses, IN6ADDR_ANY_INIT for IPv6 address).  The wildcard ad‐
>        dress is used by applications (typically servers) that intend to ac‐
>        cept connections on any of the host's network addresses.  **If node is
>        not NULL, then the AI_PASSIVE flag is ignored.**

El problema es que intentamos probar esto y *nunca* nos funcionó (ni siquiera al intentar hacer una prueba local):
```
struct addrinfo hints;
struct addrinfo* serverInfo;

memset(&hints, 0, sizeof(hints));
hints.ai_family   = AF_UNSPEC;
hints.ai_socktype = SOCK_STREAM;
hints.ai_flags    = AI_PASSIVE;
int err = getaddrinfo(NULL, port, &hints, &serverInfo);
```
_(El error que retorna `gai_strerror(err)` es "Connection refused")_

Por el contrario, lo que también me suena raro es que si uno **sí** especifica la IP en el primer parámetro **sí** funciona _(lo cual parece suficiente, pero igual pregunto para saber...)_. ¿Hay algo de la otra solución (la que usa NULL en el primer parámetro) que pasé por alto y por eso no funcionó?

**Comment by iago64** [comment]
Aloha! como va?

Justo revisando el código que subiste, veo que están usando AF_UNSPEC en el flag de ai_family, esto esta buenísimo si no sabes si estas laburando en IPv4 o IPv6, pero tengo mis dudas respecto a como funcionan con getaddrinfo(), por lo que primero capaz haría la prueba de setearlo como AF_INET que esto los limita a IPv4, pero que por suerte es el tipo de IP que tienen en las VMs que les damos para que realicen la entrega del TP 😉 

Abrazo a la distancia!

**Comment by RaniAgus** [comment]
Hola @iago64 !
Estuve probando con lo que vos me dijiste y obtuve el mismo resultado: no funciona. Me fijé con todas las combinaciones posibles tanto para el server como para el cliente entre AF_UNSPEC y AF_INET.

Lo que sí es cierto es que el comportamiento cambia. Investigando un poco me di cuenta que lo que `getaddrinfo()` devuelve es una *lista* de direcciones, y para AF_INET esa lista tiene un elemento y para AF_UNSPEC devuelve dos. 

En varios ejemplos en StackOverflow vi que la gente itera esa lista para hacer connect() en todas las direcciones que aparecen hasta que `connect()` no devuelva error, así que probé hacer eso para ver si poniendo AF_UNSPEC me podía conectar. Pero no, `connect()` siempre retorna "connection refused" :disappointed: 

Este es el código que cambié para la parte de socket() y connect():
```
struct addrinfo *p;
for(p = clientInfo; p != NULL; p = p->ai_next)
{
	*conn = socket(p->ai_family, p->ai_socktype, p->ai_protocol);
	if(*conn == -1)
		continue; //Si socket() falla, pasa al siguiente
	
	err = connect(*conn, p->ai_addr, p->ai_addrlen);
	if(err != -1)
		break; //Si connect() funciona, deja de iterar
	
	close(*conn); //Si connect() falla, cierra el socket que se abrió recién
}
```

**Comment by RaniAgus** [comment]
Hola de nuevo! Dejo oculto el otro comentario porque las pruebas que hice hoy tenían el puerto mal configurado :man_facepalming:  :man_facepalming:  :man_facepalming:  

Efectivamente, con el flag AF_INET el comportamiento de `getaddrinfo()` cambia, ya que devuelve una *lista* de direcciones, entonces para AF_INET devuelve un elemento mientras que para AF_UNSPEC devuelve dos (supongo que la dirección en IPv4 e IPv6).

En varios ejemplos en StackOverflow vi que la gente itera esa lista para hacer connect() en todas las direcciones hasta que no devuelva error, así que probé hacer eso para ver si poniendo AF_UNSPEC me podía conectar, y esa solución también me funcionó.

Este es el código que cambié para el cliente en la parte de `socket()` y `connect()` para que funcione con AF_UNSPEC. En vez de intentar una vez, lo hago para cada elemento de la lista hasta que la conexión sea exitosa o llegue al final:
```
int conn;
for(p = clientInfo; p != NULL; p = p->ai_next)
{
	conn = socket(p->ai_family, p->ai_socktype, p->ai_protocol);
	//Si socket() falla, pasa al siguiente
	if(conn == -1)
		continue;
	
	//Si connect() funciona, deja de iterar
	if(connect(conn, p->ai_addr, p->ai_addrlen) != -1)
		break;

	//Si socket() funciona pero connect() falla, cierra el socket y pasa al siguiente
	close(conn); 
}
```
La otra opción es dejar todo como está y usar AF_INET. Funciona, pero no sé si será tan seguro, porque de todas formas `getaddrinfo()` siempre retorna una lista así que por lo menos yo no confiaría en que siempre devuelva un único elemento jajaj

Gracias @iago64 ! Saludos
