### ISSUE TITLE
[Comanda] Dudas con swap 

### ISSUE THREAD

**Issue by FlorAldonatti** [sisoputnfrba/foro#2001]
Hola!
Quería hacer un par de preguntas que si bien las vi en el foro, no me quedaron 100% claras como proceder.
1. Releyendo el TP me encontré con el siguiente texto: _"Toda página debe existir inicialmente en SWAP moviéndose a Memoria solo en el caso que sea necesario, quedando dicha página tanto en memoria real como en SWAP hasta que sea reemplazada"_ Había leido en un issue anteriormente que estaba bien que cuando creo el plato lo cree tanto en memoria virtual como en memoria principal. Me podrán confirmar cual de las dos opciones va?

2.  Luego, estaba haciendo pruebas con el LRU y mirando este issue: [(https://github.com/sisoputnfrba/foro/issues/1967)] me generó una duda:
Teniendo en cuenta que antes de crear un plato primero me tengo que fijar si el mismo ya existe en el pedido recorriendo secuencialmente la tabla de páginas del pedido.
- Si la pagina está en memorial principal, leo el plato (le actualizo el timestamp y el bit de uso) y si no matchea, sigo con el siguiente
-  Si no está en memoria principal, hago swap, selecciono mi víctima haciendo LRU y continuo como en el punto anterior.

Mi duda está que cuando voy recorriendo la tabla de páginas para ver si el plato existe o no, cada vez que leo una página voy actualizando el timestamp y el bit de uso. Entonces, si el plato finalmente no existe el plato, tengo que volver a correr LRU y seleccionar una víctima pero todos los valores me quedaron actualizados secuencialmente. Esto que mencione es correcto?

Muchas gracias de antemano,  Flor :)

**Comment by iago64** [comment]
Aloha! como va?

1.- Las creas en ambos lados, porque _tiene que existir en ambos lados_

2.- Esta perfecto que actualices el timestamp a medida que los lees, y si, eventualmente puede dárse el caso de que actualices todos los frames del pedido en orden, pero eso no te evita que por LRU tengas que reemplazar un frame de otro pedido (acordate que el reemplazo es global)

Saludos.-

**Comment by FlorAldonatti** [comment]
Buenísimo, creo que se notó mucho mas porque estaba probando con un solo pedido. Mil gracias!!!!
