### ISSUE TITLE
Duda Obtener pedido

### ISSUE THREAD

**Issue by lcerliani** [sisoputnfrba/foro#2002]
Buenas, tenemos una duda acerca del enunciado con la API. En el enunciado dice que el mensaje obtener pedido retorna algo con el siguiente formato: {estado, [{comida1, cantTotal1, cantLista1}, {comida2, cantTotal2, cantLista2}, ...]}. La duda es: tenemos que devolver un string con ese formato o un struct que contenga el estado y una lista con los platos y sus cantidades?

Muchas gracias!

**Comment by iago64** [comment]
Buenas!

Tienen que devolver los datos, si los serializan como string o si pasan la estructura serializada da lo mismo mientras el módulo que recibe los datos sepa interpretarlos.
El formato fue para darles una notación mas o menos facil de interpretar donde las llaves { } denotan un objeto y los corchetes [ ] denotan listas / arrays similar a como es en JSON.

Saludos.-

**Comment by lcerliani** [comment]
Muchas gracias!
Cierro el issue.
