### ISSUE TITLE
Problema al hacer bind

### ISSUE THREAD

**Issue by Roman-Petru** [sisoputnfrba/foro#2003]
Buenas! Haciendo las pruebas en las VM notamos que de pronto un módulo al intentar restartearlo dejó de funcionar bien, tirando, "error de bind: Addres already in use", investigando pusimos que antes del bind se haga SO_REUSEADDR y REUSEPORT de esta manera:

	if (setsockopt(socket_servidor, SOL_SOCKET, SO_REUSEADDR | SO_REUSEPORT | SO_LINGER , &option, sizeof(option)) == -1)
		{perror("Error de setsockopt: ");
		abort();}

Sin embargo sigue tirando el mismo error, hasta que para probar cambiamos el puerto del módulo y anduvo lo más bien. Qué se puede hacer para no tener que cambiar el puerto y no ocurran estos errores al reiniciar un módulo?

Estos son los flags de los hints y como creamos el socket:

	hints.ai_family = AF_INET;
	hints.ai_socktype = SOCK_STREAM;
	hints.ai_flags = AI_PASSIVE;

	socket_servidor = socket(servinfo->ai_family, servinfo->ai_socktype, servinfo->ai_protocol);
	if(socket_servidor == -1)
		{perror("Error de socket:");
		abort();}

**Comment by RaniAgus** [comment]
Buenas! Nosotros tenemos casi lo mismo (solo que con menos flags), y nos funciona bien:
```
int yes = 1;
if(setsockopt(*conn, SOL_SOCKET, SO_REUSEADDR, &yes, sizeof(yes)) == -1) {
              /* error */
}
```
Lo único que no se llega a ver en el código que copy-pasteaste es que "option" debe ser inicializado en 1 para que funcione.

**Comment by Roman-Petru** [comment]
Buenas! Gracias por la respuesta, si me olvidé de agregarlo justo antes del setsockopt tenemos el int option = 1, también probamos con menos flags (solo el SO_REUSEADDR o solo el SO_REUSEPORT) y tampoco funcionaba :/

**Comment by RaniAgus** [comment]
Hmm :thinking: 
¿Probaste ver qué te devuelve el comando `netstat -tulpn`? Si hay algún proceso bindeado a ese puerto te debe aparecer algo como esto (tengo la comanda en el puerto 5002):
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:5002            0.0.0.0:*               LISTEN      2284/comanda    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -               
tcp6       0      0 :::22                   :::*                    LISTEN      -   
```
Capaz puede ser que hayan perdido la conexión con la VM (probablemente por inactividad) pero el proceso sigue corriendo por detrás y hay que tirarle un `kill` antes de levantar otro. Sino, la otra opción que se me ocurre es que hayan levantado n instancias de un proceso y les haya quedado el config de otro que sí está levantado.

**Comment by iago64** [comment]
Buenas! pregunta importante, que numero de puerto están usando? tienen otro server de otro proceso levantado en el mismo puerto porque en ese sentido lo que dice @RaniAgus de checkear con `netstat -tulpn` les puede dar una mano en elegir puertos que no estén ocupados por otras app.

Saludos.-

**Comment by Roman-Petru** [comment]
Habíamos tirado ese comando pero increíblemente no me acuerdo que decía, y ahora ya cerramos todo jaja, pero puede ser que no se haya cerrado bien el módulo por algún motivo y quedó el puerto abierto (era el 5004 el que estábamos usando, el default del módulo App), de todas maneras me parecía raro que con el SO_REUSEADDR y el SO_REUSEPORT no reemplace al que había quedado "colgado".
Como ya terminamos las pruebas, cierro el issue, gracias por las respuestas.
