### ISSUE TITLE
[Cliente/Sindicato] Duda sobre las consolas

### ISSUE THREAD

**Issue by RaniAgus** [sisoputnfrba/foro#2004]
Buenas! Cerrando el TP nos surgió la siguiente duda: ¿es obligatorio que tanto el Cliente como el Sindicato abran un nuevo hilo ni bien se ingresa un comando? ¿O podemos hacer ingresar los comandos secuencialmente?

Pregunto esto porque en el caso del Cliente es poco cómodo hacer una prueba, ya que no podemos copiar y pegar todos los comandos juntos, por ejemplo:
```
CONSULTAR_RESTAURANTES
SELECCIONAR_RESTAURANTE LaParri
CONSULTAR_PLATOS
CREAR_PEDIDO
ANIADIR_PLATO AsadoJugoso 1
ANIADIR_PLATO AsadoSeco 1
ANIADIR_PLATO Choripan 1
ANIADIR_PLATO Choripan 1
ANIADIR_PLATO Choripan 1
ANIADIR_PLATO Choripan 1
```
Esto ocurre ya que sí o sí tengo que haber seleccionado un restaurante antes de crear un pedido, o crear un pedido antes de añadir un plato.

**Comment by iago64** [comment]
Buenas!

Pregunta del millon, quien los apura para correr las pruebas? sabemos que las pruebas tardan, por eso no se hagan mala sangre :)

Saludos.-

**Comment by foviedo** [comment]
Dami te adoro

**Comment by foviedo** [comment]
Es porque queremos hacerlo de la forma más óptima posible

**Comment by RaniAgus** [comment]
Jajajaj ta bien, dejamos lo de un hilo por cada comando entonces, ¡saludos!
