### ISSUE TITLE
[Restaurante] [Prueba] Encolamiento

### ISSUE THREAD

**Issue by Maldonado-J** [sisoputnfrba/foro#2005]
Buenas! Teniamos unas dudas rápida con las pruebas de restaurante.

1. En el doc de pruebas con algoritmo RR dice:
>los únicos que van a llegar **directo al horno van a ser los choripan** y los demás platos van a tener que al menos consumir 2 quantum antes de llegar al horno.

Nosotros hicimos el Gantt y vemos que esto pasa porque el restaurante solo tiene un Horno entonces siempre terminan encolados por al menos 1 quantum (excepto el primero)
![unknown](https://user-images.githubusercontent.com/38119998/101964219-699c3700-3bef-11eb-82be-d8e4621d3eea.png)
Es posible que sea un error de redacción o hay algo que no estamos teniendo en cuenta?

2. No tenemos claro a qué se refiere con esta parte de los resultados esperados (algoritmo FIFO)
>hay encolamiento de los platos en el horno y al **finalizar los pedidos**

A qué se refiere con encolamiento al finalizar pedidos?
Nosotros en el módulo restaurante verificamos si un pedido esta completo y en ese instante se le manda el mensaje correspondiente a Sindicato. No entiendo qué es lo que se puede encolar.

**Comment by Maldonado-J** [comment]
PD: Notamos un pequeño error en el Gantt, el AsadoJugoso son 4 cpus en lugar de 5 y AsadoJugoso1 deberia ejecutar antes que el Choripan3 por fin de quantum, lo que cambiaria un poco el Gantt pero la duda (1) con los Choripanes sigue en pie porque esto ocurre al principio

**Comment by iago64** [comment]
Buenas!

Lo que quiere decir que llegan directo al horno es que están llegando antes al paso de hornear que cualquier otro plato, esta bien que queden encolados en el horno, pero lo que debería pasar es que lleguen todos los choripanes antes de que tengan una interrupción por quantum.

Saludos.-
