### ISSUE TITLE
Sindicato - Modificación archivo Metadata.AFIP

### ISSUE THREAD

**Issue by lcerliani** [sisoputnfrba/foro#2006]
Buenas, cómo va?
Leyendo el documento de pruebas finales nos dimos cuenta de una referencia en Sindicato que dice que el tamaño del bloque puede cambiar. Esto quiere decir que cuando esto pase se tienen que reordenar los bloques ya escritos? O deberíamos borrar el filesystem y volverlo a levantar con el nuevo tamaño de bloques?

Gracias!

**Comment by ncoen97** [comment]
Buenas, el cambio del tamaño de bloque se hace con el sistema "limpio", por lo tanto se va a borrar todo el FS e iniciar de nuevo con esa configuración (no es necesario que lo borren mediante código, pueden simplemente hacer `rm -rf` desde consola).
Saludos!

**Comment by lcerliani** [comment]
Muchas gracias! Cierro el issue.
