### ISSUE TITLE
[Aporte] Template para hacer y deployar el TP

### ISSUE THREAD

**Issue by RaniAgus** [sisoputnfrba/foro#2007]
¡Buenas!

Este cuatri con mi grupo arrancamos haciendo el TP con la estructura de proyecto que genera Eclipse, y a la hora de pensar una manera de deployar encontramos [este script provisto por la cátedra](https://github.com/sisoputnfrba/so-deploy), que está buenísimo pero (al igual que vi que pasó con varios grupos) no nos servía ya que Eclipse genera sus makefiles en la subcarpeta `Debug/` o `Release/` con algunas cosas difíciles de descifrar, no se pueden copiar y pegar así nomás.

Había aprendido un poco de makefiles con la [excelente explicación](https://github.com/dariokozicki/utnso-vscode#explicaci%C3%B3n) de @dariokozicki a principio de cuatri, así que me puse a investigar cómo adaptarlos a lo que teníamos y lo logramos, promocionamos el TP deployándolo rapidísimo y sin ningún dolor de cabeza. Por lo tanto, me pareció buena idea armar un [template](https://github.com/RaniAgus/utnso-project) con esos makefiles para crear proyectos en C (incluyendo una shared library real) y deployar el repo con so-deploy, así cualquiera puede usarlos :)

También incluyo un script para correr los módulos desde consola (con valgrind memcheck, helgrind y gdb) configurando `LD_LIBRARY_PATH` automáticamente. Gran parte del mérito es de @MaSosa314 que lo hizo el cuatri pasado cuando compartimos grupo y me quedó para reusarlo. Le agregué un par de cositas y la verdad que con mi grupo lo usamos una bocha.

Lo curioso es que me puse con el VSCode a adaptar una resolución del TP0 para hacer un [repo de ejemplo](https://github.com/RaniAgus/utnso-project-example) y el autocompletado me funcionó perfectamente sin ninguna configuración extra, aunque aún no llegué a configurarlo para debugear desde el editor. 

También abrí los proyectos en Eclipse :rage: y CLion :smiling_face_with_three_hearts: con las configuraciones básicas para importar cualquier proyecto y anduvo todo perfecto.

Si les copa pienso después agregar al readme una guía de cómo importarlo en cada uno de los tres IDEs. También son bienvenidos a dejar un issue por cualquier consulta o forkear el repo si quieren agregar alguna funcionalidad.

¡Espero que sea útil!

Saludos, y ¡felices fiestas!

**Comment by RaniAgus** [comment]
Recientemente hice varios cambios en el repo para que sea más sencillo de configurar y usar:

- Cambié el uso de una shared library por el de una static library. Explicación rápida: las static libraries funcionan mejor para compartir código generado por el usuario que es específico del proyecto, mientras que las shared están más hechas para ser distribuidas en general (gracias @tferraro por hacerme notar este detalle). Además, como el código compartido queda en el ejecutable final, no hay que configurar `LD_LIBRARY_PATH` 🎉 

- Como no hay shared library y no hace falta configurar `LD_LIBRARY_PATH`, entonces no hace falta tener un script que la configure antes de ejecutar. Moví el "Run with Valgrind" hacia dentro del makefile para que si alguien quiere ejecutar desde consola sin pasar por un IDE pueda mantener esa "profiling tool" (?)

- Hice que la interfaz para agregar una library o un path sea más sencilla. También, el makefile está más organizado y es más cómodo de leer por si a alguien le interesa investigar cómo funciona 👀 

- En cuanto a cómo importar y configurar el repo en cada IDE, empecé por Eclipse, se puede acceder a la guía acá: https://github.com/RaniAgus/utnso-project/wiki/Eclipse

**Comment by Caruso-Martin** [comment]
Buenas @RaniAgus, quería comentarte un problema que tuve siguiendo la guía de la plantilla. En la sección **Pasar argumentos a main() - Desde Eclipse**, se indica que se puede ingresar un archivo de configuración (`project.config`).

En mi caso, cree dicho archivo y lo guarde dentro de la carpeta principal del proyecto; el mismo tiene este formato:
```
argc=1
argv=3
```

Posteriormente, construyo y ejecuto el proyecto; el mismo tiene un archivo `main.c` de este formato:
```
int main(int argc, char *argv[]){
   printf("%d", argc);
   return 1;
} 
```
El output siempre me da "2", independientemente del valor que le de a mi `argc`- ¿Sabes la causa de este problema?

**Comment by RaniAgus** [comment]
¡Buenas @Caruso-Martin! El output da 2 porque, al igual que como menciona la [guía de argumentos para el main](https://docs.google.com/document/d/1lgJkujN9kBlsFcYyp9aEkNvmoWVFKCajceh84R8s2KQ/edit#), el vector de argumentos (`argv`) siempre incluye como primer valor el comando que se ingresa para ejecutar:

> El motivo por el que el segundo elemento del array es la ruta que ingresamos es porque el primer elemento es siempre el comando en sí mismo (en este caso, ./Debug/client).

En este caso, podés probar de ver qué te imprime `argv[0]` y `argv[1]`, probablemente sea algo parecido a `./bin/proyecto.out` y `proyecto.config` respectivamente.

Aclaro que en este caso el archivo `proyecto.config` que creaste no está influyendo en tu programa. Para crear un config te recomiendo chequear la definición de `config_create()` en el [header de las commons](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/config.h).

Saludos
