### ISSUE TITLE
Problema al debugear con los archivos

### ISSUE THREAD

**Issue by Franpanozzo** [sisoputnfrba/foro#2008]
Buenas, estoy haciendo los ejercicios de operativos de C y no me esta saliendo el 3, compila todo pero no me muestra lo que tendria que ser por pantalla, y al momento de usar el debug cuando hago step into sobre la linea en la que abro el archivo para leerlo: 
FILE* archivo = fopen("/home/utnso/workspace/prueba-commons/archivin","r"); 
Me aparece el siguiente error en el debug: 
Can't find a source file at "/build/glibc-mUak1Y/glibc-2.23/libio/iofopen.c" 
Locate the file or edit the source lookup path to include its location.
Trate de debugear el ejercicio 2 que tambien era con archivos que salio bien pero cuando llega a la linea del archivo pasa lo mismo, y no puedo hacer step over tampoco y no puedo seguir.
Si alguno me puede dar una mano buenisimo asi encuentro despues el problema, si necesitan mas detalle con captura asi capaz se entiende mas diganme. Saludos!

**Comment by iago64** [comment]
Buenas! como va?

Ese error lo que te dice simplemente es que intentaste entrar a una función para la cual no tenes el archivo fuente, solo tenes el archivo compilado.
Esto te va a pasar siempre con las funciones de las bibliotecas estándar de C (por ejemplo las de stdio.h o stdlib.h).
Fijate que en eclipse vas a tener 2 botones a la hora de debuguear, uno que es para ingresar a la funcion:
![image](https://user-images.githubusercontent.com/1622109/108201969-3ac6a380-70ff-11eb-94a0-ae92b2fd9821.png)
 y otro que es para saltar la función:
![image](https://user-images.githubusercontent.com/1622109/108202024-4b771980-70ff-11eb-9227-f738643dff18.png)

Si haces click en el de entrar a la función te va a devolver ese error raro, ahora si le das al de saltar la función debería continuar sin problemas.

Saludos.-

**Comment by Franpanozzo** [comment]
Buenas, ahi me salio, trataba de hacer step over sobre la linea pero una vez que ya habia hecho step into, ahi me tiraba el error y hay que hacer terminate y volver a debugear. Y ahi si hay que hacer step over como bien me dijiste sobre cada linea que se interactua sobre el archivo, sino tira ese error raro, tambien cuando se hace malloc me paso. Muchas gracias y saludos!

**Comment by ncoen97** [comment]
Buenas!
Para la próxima recordá que mediante el [buscador de issues](https://github.com/sisoputnfrba/foro/issues?q=Can%27t+find+a+source+file+at) por ahí podes encontrar info de issues anteriores que te sirva para resolver tus dudas.
Ya que estoy también te comento que una vez que no tengan mas consultas pueden cerrar el issue uds mism@s.
Saludos!
