### ISSUE TITLE
[TP0] Definiciones múltiples de `logger'

### ISSUE THREAD

**Issue by jlsuh** [sisoputnfrba/foro#2009]
Muy buenas a todos.
Probé en hacer el `make` del Servidor en mi distribución personal y me encontré con el siguiente inconveniente:
![image](https://user-images.githubusercontent.com/38252227/112744575-a9591580-8f77-11eb-82f6-2d2dbddcba0c.png)
Cada vez que ejecuto el `make` hace referencia a un `.o` distinto:
![image](https://user-images.githubusercontent.com/38252227/112745288-90536300-8f7d-11eb-94a4-215c6c8b8256.png)

La distribución es arch-linux. Actualmente tengo instalado la versión 10.2.0 del gcc.
Pude hacerlo andar en la máquina virtual de la cátedra, pero opté en probarlo localmente para ver si podía mejorar la experiencia y performance de poder programar a lo largo del cuatrimestre.
Muchas gracias 🙏🏻

**Comment by RaniAgus** [comment]
¡Buenas!
Antes que nada, ¿podrías pasarnos en qué archivos tenés declarado `logger` así podemos contar con más contexto para poder ayudarte a encontrar el error?

**Comment by jlsuh** [comment]
Muy buenas @RaniAgus 
Pude solucionarlo con los siguientes pasos.

Originalmente `Servidor/utils.h` se encontraba como:
![image](https://user-images.githubusercontent.com/38252227/112772105-6e052800-9005-11eb-9b5b-c784cdeacabc.png)

Lo que opté en hacer es sacar la declaración del logger hacia `Server/servidor.c`:
![image](https://user-images.githubusercontent.com/38252227/112772163-bcb2c200-9005-11eb-865f-af95a7be165a.png)
y dejé en `Servidor/utils.h` el extern del mismo:
![image](https://user-images.githubusercontent.com/38252227/112772207-f257ab00-9005-11eb-9df0-a01e49c7e55f.png)

**Comment by iago64** [comment]
Buenas!

Consulta rápida, en la vm de la catedra no te hizo falta agregar la variable en el .h para que salga andando de una? 
Instalaste las commons en tu base de arch? Porque capaz por ahí arranca el problema.

Saludos.-

**Comment by jlsuh** [comment]
Muy buenas @iago64
Efectivamente, no me hizo falta. Hice el tp0 por primera vez en la vm y me anduvo a la primera 👍🏻
Sí, me aseguré de que las commons estén instaladas. De hecho probé el workflow del tp0 varias veces desinstalando/instalando las commons.
Saludos

**Comment by iago64** [comment]
Buenas!
Ahora con un poco mas de cafeina en el cuerpo se me ocurren algunas alternativas:
1. La versión de GCC es abismalmente diferente, en la VM esta instalado GCC 5.4.0, lo cual tambien puede ser que sea un factor que teniendo en cuenta como esta armado el repo este dándote problemas, lo que podrías hacer seria hacer un downgrade de la versión a la 5.4.0 y checkear si eso funciona.
2. Como el problema es que te dice que tenes múltiples definiciones de logger, eso puede venir de la mano de que vos tenes por un lado el logger en utils.h de la carpeta Servidor y por otro lado en tp0.c también tenes la variable logger y como estamos en versiones distintas de GCC, capaz que hay algún cambio relacionado a como compila los archivos que no estamos viendo y bueno, genera que encuentre 2 veces la definición de logger.
3. Como última opción, podes pasarte el detalle de un git diff a ver que cambio respecto al tp0

Por último, recién (de nuevo gracias a que estoy un poco mas despierto) me percato de que subiste *screenshots de tu código* y es algo que **les pedimos en el template de issue que no lo hagan**.
En este tipo de situaciones lo que tenés que hacer es hacer simple copy-paste de tu código y agregar el markdown para que sea código (si te interesa que se vea resaltado) ya que si no cualquiera que quiera usar el buscador no va a encontrar nada porque no busca en el texto en imágenes.

Saludos.-

**Comment by jlsuh** [comment]
Muchas gracias por las ideas.
No tuve éxito llevando a cabo el downgrade😢
Tendré presente para la próxima los requisitos del foro, pido disculpas.
Muchas gracias nuevamente 👍🏻
