### ISSUE TITLE
Buscamos 1 integrante para TP

### ISSUE THREAD

**Issue by yairtele** [sisoputnfrba/foro#2010]
Buenas! Busco último integrante para grupo de 4 personas. Fundamental estar predispuesto y bien comprometido a sacarlo adelante. Se valoran conocimientos de C. Comunicarse por favor al mail: yairtele@yahoo.com.ar

Gracias!

**Comment by ncoen97** [comment]
Buenas! Gracias por hacernos acordar. Ahí cree [el issue](https://github.com/sisoputnfrba/foro/issues/2011) para que puedan buscar grupo/integrantes, te pido si podes copiar tu mensaje ahí y cierro este issue para estar mas ordenad@s.
Saludos!
