### ISSUE TITLE
Error al intentar abrir el archivo de Ubuntu Server v5.0.1 decargado 

### ISSUE THREAD

**Issue by GRodriguezPardo** [sisoputnfrba/foro#2012]
Hola, mi problema es que al intentar abrir el segundo archivo descargado de Ubuntu Server v5.0.1 llamado "ubuntu-server-5.0.1.7z.002" el programa 7zip me dice que no puede abrirlo como archivador. Intente descargarlo varias veces y el error persiste.
Si a alguien se le ocurre porque puede ser desde ya muchas gracias.

**Comment by RaniAgus** [comment]
Buenas! Esto pasa porque, al ser un archivo comprimido en varias partes, no se puede abrir *solo la parte 001* o *solo la parte 002* (de hecho, si movés la parte 002 a otro lado, lo más probable es que te tire error al abrir la 001).

La forma correcta de abrir el archivo comprimido es tener ambas partes en el mismo directorio y abrir la 001, de esa forma vas a poder descomprimir lo que se encuentra en todas las partes.

Saludos!

**Comment by GRodriguezPardo** [comment]
Ahhh claro, no sabia que funcionaba asi, probe sacando el .002 y el archivador .001 aparece con el archivo incompleto. En realidad mi problema era otro pero pense que era por esto, ahora abro otro issue con el problema.
Muchas Gracias!
