### ISSUE TITLE
Error al tratar de abrir la VM en el virtual box

### ISSUE THREAD

**Issue by Brunolombardozzi** [sisoputnfrba/foro#2013]
Hola buenas noches, al intentar abrir la vm en el virtual box versión 6.1.18 que seria la ultima, me tira este error.
Busque en las consultas que habían hecho anteriormente y no era ninguna.
El error que tira es :

 **VT-x is disabled in the bios for all CPU modes
(VERR_VMX_MSX_ALL_VMX_DISABLED).**

**Comment by iago64** [comment]
Buenas! como va?
Ese error si le prestas atención dice: **VT-x is disabled in the bios for all CPU modes.**

Básicamente lo que te falta es habilitar la virtualización desde el bios, ahora, el como hacerlo, ya depende del modelo de tu pc.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Quisiera agregar que, no sé si leíste nuestro [issue template](https://github.com/sisoputnfrba/foro/blob/master/ISSUE_TEMPLATE.md), pero la idea es no subir capturas de pantalla, ya que si otro alumno busca, por ejemplo, `VERR_MEM_NOT_AVAILABLE`, no va a poder encontrar esta respuesta porque GitHub no reconoce el texto de la captura.
Si podés quitarla y poner en su lugar el texto dentro de "detalles", probablemente un futuro alumno te lo agradecería :P

¡Saludos!

**Comment by Brunolombardozzi** [comment]
Muchas gracias Damian! Problema resuelto. Corregido @RaniAgus

**Comment by iago64** [comment]
Buenisimo! Por favor no te olvides a futuro a cerrar los issues si quedan resueltos :)
