### ISSUE TITLE
Escritorio lubuntu vacío/congelado

### ISSUE THREAD

**Issue by marciondg** [sisoputnfrba/foro#2014]
Estimadxs, cómo están?

Estoy teniendo el siguiente problema con la VM de lubuntu.
La VM me funcionaba perfecto hasta anoche, quise abrirla en otro monitor y al reajustar la pantalla (cerrando sesión y volviendo a entrar) desapareció todo. Apagué la maquina y la encendí de nuevo y sigue igual.
Intenté abrir la consola haciendo ctrl + alt + t y no sucede nada

**Esto sucede una vez que ingreso la contraseña del usuario utnso**

![image](https://user-images.githubusercontent.com/53331055/114255689-385c2980-998b-11eb-9688-7bd894847504.png)
_Al no tener ningun codigo de error en pantalla se me dificultó encontrar una consulta similar, y debo hacer la excepción a la regla de no subir captura de pantalla._

Desde ya gracias
Saludos

_Edit: La versión de VirtualBox que estoy utilizando es la 5.2.44_

**Comment by iago64** [comment]
Buenas! como va?

En este caso la captura de pantalla esta bien, generalmente esa regla la tenemos para cuando son errores con texto o código.
Como para poder entender mas la situación, cuanto tiene asignada de vram la VM? Le instalaste las guest adittions?

Ya con esa info vamos a poder tener una mejor idea.
Abrazo!

**Comment by mgarciaisaia** [comment]
¿Recomendamos por algún motivo en algún lado una versión tan vieja de VirtualBox?

Por lo que dicen [acá](https://askubuntu.com/a/1222), arrancaría revisando si los logs del display manager dicen algo raro. Cuando estás en ese estado colgado, tocá `CTRL + ALT + F1` para ir a otra consola de Linux, y ahí iniciá sesión y ejecutá `systemctl status display-manager`. No creo que te vaya a aportar muchísimo, pero en una de esas te grita un error grande y feo y ayuda a descular qué pasa.

En el muy probable caso en que eso no funcione, probá de hacer `sudo systemctl restart display-manager` para reiniciar el servicio gráfico. Eso te debería volver a mostrar la ventana de login gráfica (si no lo hace, tocá `CTRL + ALT + F7` para volver a la consola gráfica, y ver si cambió algo.

Si nada de esto funciona, contanos qué onda los logs y vemos si se nos ocurre algo más.

**Comment by marciondg** [comment]
Hola chicos, cómo andan? gracias por sus respuestas
@iago64:
Perdón si es media tonta la pregunta, con vram te referís a memoria de video? si es sí lo dejé en 16mb.
Las Guest additions en esta versión de virtualBox las pude instalar ok (No así en la más reciente).

@mgarciaisaia:
Lo de la versión vieja de VirtualBox lo tomé porque en su primer momento bajé la versión 6.1.18 (la más reciente) y no pude hacer instalar bajo ninguna forma los Guest Additions. (Se quedaba en _running kernel modules will not be replaced until the system is restarted_  como en el issue #1662)
y en la página de utn so solo menciona que debe ser superior a la versión 4.3.

Respecto al primer comando que me indicaste este es el resultado. 

![image](https://user-images.githubusercontent.com/53331055/114259311-559cf200-99a3-11eb-9c62-4e8818b9a0e6.png)

Luego recargo la ventana de login grafico

![image](https://user-images.githubusercontent.com/53331055/114259355-c0e6c400-99a3-11eb-9078-9ad09012d3f5.png)

Pero al reloguear sucede lo mismo

![image](https://user-images.githubusercontent.com/53331055/114259376-d1973a00-99a3-11eb-9e2b-4b98256dab1e.png)

Saludos!

**Comment by mgarciaisaia** [comment]
Mmm.. Acá tengo exactamente el mismo log del `display-manager`, así que no aportó mucho eso.

Fijate si en `/var/log/lightdm/lightdm.log` ves algo más.

También podés probar de subirle la memoria de video (algo que medio que estaba sugiriendo Dami). Mi VM tiene 16MB también, pero cuando intento agrandarle mucho la ventana medio que no me da bola (estimo que cuando no le da la memoria de video para bancar tantos píxeles, pero no lo chequeé). Quizá te esté pasando algo así, pero falla distinto (porque es distinta versión de VirtualBox, o por tener distinto OS Host, o andá a saber). Subile a 64 o 128MB si te da la memoria, para descartar que venga por acá.

(La otra respuesta - poco académica, quizá, pero pragmática - es sugerirte que, si no hiciste muchas cosas en la VM esa, la borres y la instales de nuevo, a ver si la máquina se jodió por algo en particular que hayas hecho)

**Comment by marciondg** [comment]
No me deja subir la memoria de video
![image](https://user-images.githubusercontent.com/53331055/114278431-38e5d600-9a06-11eb-963b-86fc980bb85c.png)

No hice casi nada en la VM, pero si al segundo día de uso ya se "rompió todo"... me preocupa que vuelva a ocurrir.

**Comment by mgarciaisaia** [comment]
Je, sí, entiendo el miedo. Pero no creo que sea tan así, tampoco. Las VMs estas tienen varios años ya. Y, nadie jamás dijo "Ay, qué linda la experiencia de programar adentro de una VM", pero tampoco se rompen día por medio.

Lo de no poder subirle la memoria de video _estimo_ que será porque tenés la VM andando. Apagala (desde Linux), y cuando esté apagada deberías poder subirle eso.

Podés hacer `sudo halt -p` desde la terminal que conseguís haciendo `CTRL + ALT + F1`, o tenés el botón de apagado en la ventana de inicio de sesión creo. O, buen, le forzás el apagado físico desde VirtualBox.

**Comment by marciondg** [comment]
Novedades:

Me bajé de nuevo la versión de VirtualBox más reciente (6.1.18)

Al instalar las GA no se me ajusta la pantalla completa. Buscando soluciones de la comunidad, encontré que recomiendan cambiar el controlador grafico de la VM al VBoxVGA.

Cuestión que ahora al loguearme el escritorio queda completamente en negro:
_Configuración gráfica_
![image](https://user-images.githubusercontent.com/53331055/114280163-6c2c6300-9a0e-11eb-9cac-151d13934d3a.png)

_Pantalla Lubuntu_ (queda negra)
![image](https://user-images.githubusercontent.com/53331055/114280182-7e0e0600-9a0e-11eb-9723-34c4e69f4e8a.png)

Me están saliendo canas con esto..




_Cuando pongo el controlador por defecto se ve ok el escritorio, pero no en pantalla completa_
![image](https://user-images.githubusercontent.com/53331055/114280284-ebba3200-9a0e-11eb-8613-8fc6b57c2d08.png)

**Comment by mgarciaisaia** [comment]
Ah, capaz la mencioné en otro issue. Yo estoy corriendo VirtualBox 6.0.18, porque en algún cuatri encontramos con un puñadito de personas que tenían diversos quilombos que esa era la versión menos problemática en general.

Si no encontraste nada mejor hasta ahora y todavía te quedan ganas de pelear un poco más, fijate si instalando esa mejora. Si anda, capaz podríamos actualizar la página de descarga de las VMs para ser un poco más específicos.

**Comment by marciondg** [comment]
Perfecto, con la 6.0.18 me funcionó.

Muchas gracias
saludos!
