### ISSUE TITLE
Guest Additions en Virtual Box 6.1.18.

### ISSUE THREAD

**Issue by amanuele** [sisoputnfrba/foro#2015]
Hola, no hay caso que pueda hacer funcionar las Guest Additions en la vm de lubuntu. Estoy con la ultima versión de **VBox (6.1.18) sobre un Windows 10.** 
O sea, puedo cargar el addition en /media, corro el sudo ./VBoxLinuxAdditions.run, corre hasta el final (nunca me dice el "done", pero tampoco tira ningun error como que no haya terminado bien).
Quede de de esta forma:

![image](https://user-images.githubusercontent.com/18357329/114276106-9fb1c200-99fb-11eb-9b6d-4edf23997b6a.png)

Me lei creo que todos los issues de este foro pero no encontre ninguno igual a esto.. Estoy pensando en bajar la versión de VBox como para probar, pero si se puede hacer funcionar con la ultima y alguien pudo hacerlo se agradecen tips de como!..

Muchas gracias
Saludos!

**Comment by mgarciaisaia** [comment]
👋 ¡Aloha!

Mirá, recién volví a instalar las Guest Additions en _mi_ VM, y no dice nada distinto a lo que te dijo a vos (excepto, je, que yo estoy con la versión 6.0.18 de VirtualBox, pero todo lo demás está igualito).

Si cerrás sesión y volvés a loggear (o si reiniciás la VM, no recuerdo cuál de ambas), ¿siguen sin andarte las guest additions?

Hace un tiempo que las versiones de VirtualBox vienen generando algunos problemitas raros con algunas máquinas en particular. La que menos problemática encontramos hasta ahora creo que fue la 6.0.18 (que medio que, una vez que la encontramos, dejé mi VirtualBox clavado ahí). Si sigue sin funcionar la cosa, probá bajar a esa versión a ver si mejora.

**Comment by amanuele** [comment]
Hola Mati, muchas gracias por la respuesta!
Probe con la versión que me decis y funciona.. raro, pero funciona. O sea, si arrancas la sesión en tamaño ventana, no se puede resizear.. pero, si lo pones en fullscreen, o la ventana maximizada, y ahi cerras sesión y volves a iniciar, ya la sesión arranca con la pantalla completa, despues si podes achicar, el problema es que de una ventana chica, no te permite agrandar.

Muchas gracias por el rapidisimo soporte!
Saludos!

**Comment by mgarciaisaia** [comment]
Ah, sí, eso... _Creo_ que eso es limitación de Lubuntu (bah, del LXDE, digamos). Creo. Lo de que no ande tan fluido como en Ubuntu que resizeás la ventana y _al toque_ actualiza la resolución.

Pero nunca lo investigué mucho, la verdad.

Pero, buen, me alegro de que haya funcionado :)

**Comment by dimoulasLucas** [comment]
Hola, que tal? Ya se que el issue esta cerrado pero encontre una solucion sin tener que "downgradear" VBox. Tienen que ir a la VM, "Settings -> Display -> Screen -> Graphics Controller:" y cambiar "VMSVGA" por "VBoxVGA". La solucion la encontre en el siguiente link por si quieren ver: https://askubuntu.com/questions/452979/resolution-doesnt-change-when-resizing-virtualbox-window.

**Comment by dimoulasLucas** [comment]
Me olvide de agregar que una vez que inicien la VM, van a la solapa de arriba a la izquierda, entran a "View -> Virtual Screen 1" y seleccionan la opcion de "Resize to 1920x1080" en caso de que tengan esa resolucion. Luego ya podran tener la VM fullscreen con buena resolucion.
