### ISSUE TITLE
Problemas con la VM una vez modificada mi BIOS

### ISSUE THREAD

**Issue by ezecastiglione18** [sisoputnfrba/foro#2018]
Buenas! Estoy teniendo un problema para arrancar la VM de la catedra. Yo tuve que modificar algo en la BIOS para que arranque la VM y eso lo pude hacer bien. Ahora, el problema esta en que no se muestra por pantalla la ventana para poner la password "utnso". En cambio, me aparece una ventana de la consola de la VM. Me pide un usuario y contraseña (en ambos es utnso). Pero despues no puedo salir de la consola. No se si pasa esto seguido pero es la primera vez que uso maquinas virtuales jajajaja

Saludos!

EDIT: Me decia de ingresar el comando "do-release-update", no se que onda...

**Comment by iago64** [comment]
Buenas! como va?

Consulta rápida para orientarnos, cual de las 2 vms estas levantando? 
Porque la vm server es literalmente una consola y nada mas, mientras que la de lubuntu es la que tiene interfaz gráfica.

Saludos.-

**Comment by Nachiten** [comment]
Buenas! Consultas, que version de Oracle VM estas utilizando? Y luego, cual es el SO de tu maquina host? Gracias!

**Comment by ezecastiglione18** [comment]
Estoy usando la version de Oracle 6.1.18 y el SO de mi compu es la 10.0.18363 de Windows

**Comment by ezecastiglione18** [comment]
> Buenas! como va?
> 
> Consulta rápida para orientarnos, cual de las 2 vms estas levantando?
> Porque la vm server es literalmente una consola y nada mas, mientras que la de lubuntu es la que tiene interfaz gráfica.
> 
> Saludos.-

La de Lubuntu estoy levantando, es la que descargue de utnso.com.ar

**Comment by ezecastiglione18** [comment]
Ya esta, pude solucionar el error jeje. Perdonen!

**Comment by gastoncastineira** [comment]
¿Te podré molestar con que lo expliques por si le pasa a generaciones futuras mandarlos acá? :)

**Comment by ezecastiglione18** [comment]
Habia descargado mal los zip que componen la interfaz. Habia bajado el .vmi pero me olvide de los zip. Un amigo me paso el .vmi ya con la interfaz y todo
