### ISSUE TITLE
[Trello] herramienta para organizacion de tareas del proyecto

### ISSUE THREAD

**Issue by iguardines** [sisoputnfrba/foro#202]
Buenas gente, les dejo el link a una herramienta que uso en el dia a dia laboral 
https://trello.com/
Es de registro gratuito, tiene una funcionalidad acotada, pero muy copada para el desarrollo diario de tareas, es un tablero online donde creas columnas y en cada columna pones tarjetas.
Las tarjetas las creas, las asignas, las vas pasando de columna y las archivas
en un sentido similar a ciertas metodologías de laburo, podes poner una columna que sea "backlog" con las tareas a definir, cuando realizarlas, una columna "to do" con tareas priorizadas y necesarias para hacer dentro del periodo de laburo corto (llámese periodo, sprint a una cantidad no muy grande de días) otra "doing" que son las que se estan haciendo actualmente, "testing" y "done" a aquellas que pasaron por todas las otras instancias previas.
a las tarjetas se les podes agregar checklist, algo que esta muy copado, para uno entender que tiene que hacer y facilitarse el laburo y poder identificar en que parte uno esta trabado,

La idea de esto es poder colaborar, ver visualmente el estado de las tareas y si hay alguien con inconvenientes, que no llega/"sabe como hacer"... poder ayudarlo.

**Comment by JGG477** [comment]
Trello es un gran gestor de proyectos.

En [Trellodescargar](https://www.trellodescargar.com/) podrás encontrar videotutoriales y muchas información en Español de como utilizar esta fantástica herramienta
