### ISSUE TITLE
Inconvenientes en MAC OSX con Imagen VDI de Maquina virtual

### ISSUE THREAD

**Issue by nicogonzalezok** [sisoputnfrba/foro#2020]
Hola a todos, posteo esta duda ya que no vi en el foro alguna similar. 

Intentando descargar la máquina virtual en una mac con sistema operativo OSX 2020, tuve varios inconvenientes para descomprimir la .VDI que se utiliza para la cátedra, utilizando cualquier tipo de SW para descomprimir el primero de los archivos comprimidos adjuntos (1er 7z).

En Windows me anduvo perfecto (al descargarse el rar, automáticamente la primera versión se convirtió a un archivo de imagen de disco de VB), pero quería saber si es por la versión de mi SO que no puedo descomprimir la imagen.
No se si alguno tuvo alguna dificultad, dado que el tutorial en video está hecho en SO de Mac (una versión anterior supongo)
Gracias.

### :mag_right: Búsqueda en foros
[[Contanos si investigaste sobre el tema en Google o en foros, y si encontraste algún post que sea de utilidad para darnos más contexto sobre el problema.]]

### 📦 Especificaciones de la VM
- Versión de VirtualBox: VB 6.0
- Memoria RAM asignada: 1024 mb
VM y guest additions subidas a sitio utnso.com.ar/recursos

### 🖥️ Especificaciones del host
- Sistema Operativo y versión: Mac OSX 2020
- Memoria RAM: 8GB
- Procesador: Intel I3
- [[Podés enumerar más configuraciones como la versión de BIOS, la motherboard, etc acá]]

### :computer: Logs
```
[[Si obtuviste por consola o por pantalla algo que pueda ayudar a darnos 
más contexto, no subas capturas de pantalla, copiá el texto y pegalo acá. 
Si el output es muy extenso, sentite libre de adjuntar un archivo 
de texto en su lugar.]]
```

**Comment by mgarciaisaia** [comment]
¿Con qué programa intentaste descomprimir?

La herramienta nativa de macOS para descomprimir tiene problemas con archivos relativamente grandes (no recuerdo qué tamaño). Yo uso [The Unarchiver](https://theunarchiver.com/), pero probablemente también funcionen algunos otros (7zip, o, buen, [acá dicen](https://superuser.com/a/855636) que viene built-in un commando `ditto` que podés usar con `ditto -x -k el-archivo.zip directorio-destino/` (aunque no chequeé si soporta el formato en que están comprimidas las partes de la VM).

**Comment by nicogonzalezok** [comment]
@mgarciaisaia muchas gracias por el tiempo! Pude usando el Unarchiver, asi que lo cierro el bug. Slds :D
