### ISSUE TITLE
Guest Additions no me funcionan Version 6.1.18 de Virtual Box (tampoco con la 6.0)

### ISSUE THREAD

**Issue by federiver91** [sisoputnfrba/foro#2021]
Buenas!
Como dice el título del Issue, la Guest Addition se instala correctamente según el tutorial pero no surte ningún efecto. Nada.

No se qué otra info agregar. La versión de Virtual Box es la de referencia y la VM es la version de Lubuntu.. No hice mucho más que intentar instalar las Guest.

Algún tip por ahí?

### 📦 Especificaciones de la VM
- Versión de VirtualBox: 6.1.18
- Memoria RAM asignada: 1024
- Guest Addition: VBox_Gas_6.1.18

### 🖥️ Especificaciones del host
- Sistema Operativo y versión: Windows 10
- Memoria RAM: 6GB
- Procesador: I5

```

**Comment by RaniAgus** [comment]
Buenas, ¿cómo va?
Como se menciona en #2015, si no te funcionó la feature de ajustar la pantalla al tamaño de la ventana podés probar entrar con la VM apagada a `Settings > Display > Screen > Graphics Controller` y cambiar la opción a `VBoxVGA`. 
Si no te funciona, la otra opción es hacer un downgrade a la versión 6.0.18 (hace un tiempo que las versiones de VirtualBox vienen generando problemas con algunas máquinas).
¡Saludos!

**Comment by RaniAgus** [comment]
Disculpá, recién me doy cuenta de que en el título mencionabas que probaste la 6.0 (asumo que con una versión 6.0 de las Guest Additions, ¿cierto?).
De todas formas, en cualquier versión la opción de cambiar el controlador gráfico a `VBoxVGA` debería solucionar ese problema del ajuste de la pantalla. También me olvidé de mencionar que, en cuanto al portapapeles y las carpetas compartidas, en nuestros [posts interesantes](https://github.com/sisoputnfrba/foro/blob/master/POSTS%20INTERESANTES.md) hay un par de threads que mencionan cómo hacer que funcionen.

**Comment by federiver91** [comment]
Instalé la version 5.2 de Virtual Box y ahí pude hacerlas andar. Cierro el Issue.
