### ISSUE TITLE
Problema al iniciar la vm

### ISSUE THREAD

**Issue by MilenaGarro** [sisoputnfrba/foro#2022]
[[Contanos cuál es el contexto de tu duda o problema. No olvides buscar primero en el buscador de issues por si la duda ya fue resuelta antes. Si no se resuelve tu duda pero creés que el issue está relacionado, podés citarlo con un #. ¿Hiciste algún cambio reciente en la configuración? De ser así, ¿cuál?]]

### :mag_right: Búsqueda en foros
[[Contanos si investigaste sobre el tema en Google o en foros, y si encontraste algún post que sea de utilidad para darnos más contexto sobre el problema.]]

### 📦 Especificaciones de la VM
- Versión de VirtualBox: 6.1.18
- Memoria RAM asignada: 1024mb
- [[Podés enumerar más configuraciones como la versión de Guest Additions, el controlador gráfico, etc acá]]

### 🖥️ Especificaciones del host
- Sistema Operativo y versión: windows 10
- Memoria RAM:
- Procesador: intel core i3
- [[Podés enumerar más configuraciones como la versión de BIOS, la motherboard, etc acá]]

### :computer: Logs
```
[[Si obtuviste por consola o por pantalla algo que pueda ayudar a darnos 
más contexto, no subas capturas de pantalla, copiá el texto y pegalo acá. 
Si el output es muy extenso, sentite libre de adjuntar un archivo 
de texto en su lugar.]]
```
al intentar iniciar la vm me aparece este error 

Not in a hypervisor partition (HVP=0) (VERR_NEM_NOT_AVAILABLE).
VT-x is disabled in the BIOS for all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED).

Código resultado: | E_FAIL (0x80004005)
-- | --
Componente: | ConsoleWrap
Interfaz: | IConsole {872da645-4a9b-1727-bee2-5585105b9eed}

**Comment by MilenaGarro** [comment]
bueno olvidemonos de ese error ahora me aparece otro :) 

Código resultado: | E_FAIL (0x80004005)
-- | --
Componente: | MediumWrap
Interfaz: | IMedium {ad47ad09-787b-44ab-b343-a082a3f2dfb1}

**Comment by RaniAgus** [comment]
Buenas, ¿cómo va?
Me parece que este otro issue te puede servir de ayuda: #1600. Revisalo y avisanos si te funcionó.
¡Saludos!

**Comment by NazarenoLopez** [comment]
Estimados, muy buenas noches. Perdonen la molestia. Estuve con algunos problemas con las librerias readline que no me las abría correctamente. Baje VirtualBox 5.4 y anduvieron, el tema es que no funciona las guest adittions. Alguno me podría ayudar? No realicé ningún cambio ni actualziación del ubunty ni nada.

**Comment by mgarciaisaia** [comment]
@NazarenoLopez ¿el problema con readline lo tenías _dentro de la VM_ (es decir, en el sistema operativo guest; el Ubuntu que les damos nosotr@s) o en el host (tu Windows/Linux/macOS que usás siempre)?

Si es dentro de la VM, readline no debería tener problemas dependiendo de la versión de VirtualBox que uses para virtualizar. Puede existir un bug muy extraño por el que suceda tal cosa, pero es _muy, muy, muy_ improbable. Digamos, poder o no instalar readline en la VM no es motivo que amerite cambiar la versión de VirtualBox. Así que, qué se yo - en una de esas quieras volver a la versión de VirtualBox que tenías antes.

En la versión que tenés ahora, ¿volviste a instalar las Guest Additions? ¿Tenés algún reporte de error o síntoma o algo más que "no andan"? A ver si podemos buscar algo más.

**Comment by gastoncastineira** [comment]
@MilenaGarro ¿pudiste resolverlo? ¿Necesitás ayuda con algo más?

**Comment by velonna** [comment]
Buenas.  En sintesis  no puedo levantar la MV.
 probe  varias versiones de la vb y solo la  ultima  logra  levantarlo pero  no  funcionan las  GAdd.

**Comment by gastoncastineira** [comment]
Cierro issue por falta de actividad. Cualquier cosa volvelo a abrir

@velonna por favor abrí otro issue con la plantilla propuesta explicando el caso y lo revisamos si todavía necesitás ayuda
