### ISSUE TITLE
Problema con el Makefile

### ISSUE THREAD

**Issue by ezecastiglione18** [sisoputnfrba/foro#2025]
Buenas! Tengo un problema con el makefile. En el video, le aparece la opcion de crear un nuevo proyecto con "Makefile project with existing code" pero en el Eclipse que ya vino con mi MV no me aparece esa opcion. Queria saber si tengo que descargar Eclipse en mi maquina host o hay un problema con la VM. Saludos!

**Comment by RaniAgus** [comment]
Buenas, ¿cómo va?
¿Te referís a [este video](https://www.youtube.com/watch?v=PgrORWmUxkI), no? Esta opción está disponible en cualquier versión de Eclipse ya que es muy común, se me hace muy raro que no te apareciera. Se debería poder acceder de 2 formas distintas:

1. `File > New > Makefile Project with Existing code` (como se muestra en el video).
2. `File > Import...`. Luego, buscás "make" y te debe aparecer en la carpeta `C/C++` una opción que diga `Existing Code as Makefile Project`.

¡Saludos!

**Comment by ezecastiglione18** [comment]
Genial, con la segunda aparecio.

Gracias!

**Comment by ezecastiglione18** [comment]
Una ultima consulta antes de cerrar el issue: hay que seguir el ejemplo del video tambien o con que carpeta/proyecto hacemos esta parte?

**Comment by RaniAgus** [comment]
El ejemplo sirve para cualquier proyecto con makefile (digamos, cualquier carpeta que tenga un makefile adentro :P). 
En este caso, si estás haciendo el [TP0](https://faq.utnso.com.ar/tp0-enunciado), sería la carpeta del repo que recién te clonaste.

**Comment by ezecastiglione18** [comment]
Claro, yo esa parte la pude hacer. Y hasta ahi todo bien. Pero el tema es que no se porque no me aparece. Hay alguna chance de que te pueda mostrar compartiendo pantalla porque posta me esta volviendo loco jajajaj

**Comment by RaniAgus** [comment]
Disculpá, es que justo editaste el comentario y yo te estaba respondiendo al de antes jajaj. Si ya resolviste algo que comentaste es preferible editar abajo antes que en él, o marcarlo como outdated y dejar un comentario nuevo.

Me parece que estás confundiendo el video con el TP0: en el video se explica cómo correr el proceso Cliente en [otro proyecto](https://github.com/sisoputnfrba/so-test-sockets) que no es el TP0, y justo está hecho para que, en vez de levantar el proceso Servidor, se puedan enviar los mensajes y recibirlos con netcat.

En el caso del TP0, una forma de correr el server es, desde consola, entrar a la carpeta Servidor, compilar el proyecto con el comando `make` y ejecutándolo con `./server` (no hay netcat involucrado).

**Comment by ezecastiglione18** [comment]
Ah, bueno. Me confundio un monton ese video entonces jajaja

Y todo lo que se hace en el video una vez que haces lo del Makefile, no se tiene que hacer para el tp0? Porque posta estoy re confundido y perdido

**Comment by RaniAgus** [comment]
Claro, es otro ejemplo distinto, el video es para importar _cualquier_ proyecto, y muestra con _otro_ ejemplo (que no es el TP0) que también funciona compilar con el martillito y ejecutar con `Run As > Local C/C++ Application`.

Siento que te haya confundido 😞 
¿Probaste ejecutar el servidor como te mencioné arriba?

**Comment by ezecastiglione18** [comment]
Ahi pruebo con lo que pusiste en el Edit. 
Pero el tema es que yo segui tal cual el video, y por lo que entiendo no habia que hacer todo... Una vez que ya le hice Import al makefile, todo lo que sigue al video NO se tiene que hacer en este tp?

**Comment by gastoncastineira** [comment]
Buenas

Este sábado inauguramos el sábado de soporte por discord. Te parece si lo vemos entonces? 
Me parece que va a ser más práctico para todos tener media hora de conversación para evacuar todas las dudas que tengas y puedan surgir, y ver en vivo tus problemas que tener un issue con 50 mensajes

**Comment by ezecastiglione18** [comment]
Perdon por la tardanza!

Dale, mejor lo dejamos para el sabado. Aunque ya creeeeo que pude solucionar el problema, mejor lo dejamos para el sabado. Gracias!

**Comment by gastoncastineira** [comment]
@ezecastiglione18 ¿pudiste resolverlo? ¿Podemos cerrar el issue?

**Comment by ezecastiglione18** [comment]
Si! Perdón por responder tarde, lo pude resolver

**Comment by RaniAgus** [comment]
Para la próxima, te cuento que no hay problema con que cierren el issue una vez logren resolver el problema :P
