### ISSUE TITLE
Problema al iniciar la vm

### ISSUE THREAD

**Issue by celeslvp** [sisoputnfrba/foro#2026]
Instale el virtual box y configuré la VM todo bien, pero cuando quiero iniciarla me tira este error: Kernel driver not installed (rc=-1908)
En el mismo mensaje de error dice que corra "/sbin/rcvboxdrv setup" y me dice:

vboxdrv.sh: Failed to enroll secure boot key..
vboxdrv.sh: failed: modprobe vboxdrv failed. Please use 'dmesg' to find out why.

Pongo dmesg y me tira 50 mil lineas que no entiendo nada

Después había encontrado un foro que decía que corra
sudo apt-get remove virtualbox-dkms
sudo apt-get install virtualbox-dkms

Cuando corro el primero en consola me tira esto:
Se encontraron errores al procesar:
 libpam-systemd:amd64
 libssl1.1:amd64
 openssl
 sbsigntool
 libcurl4:amd64
 linux-headers-5.4.0-70-generic
 linux-headers-generic-hwe-18.04
 curl
 steam-launcher
 linux-generic-hwe-18.04
E: Sub-process /usr/bin/dpkg returned an error code (1)

y no elimina la virtualbox

### 📦 Especificaciones de la VM
- Versión de VirtualBox: 6.1.18 para linux
- Memoria RAM asignada: 1024

### 🖥️ Especificaciones del host
- Sistema Operativo y versión: Linux 18.04

**Comment by gastoncastineira** [comment]
Consulta, tenés la virtualización activada en la BIOS?

**Comment by celeslvp** [comment]
Si si, ayer un compañero me lo había dicho y me fijé, y si estaba activada

**Comment by gastoncastineira** [comment]
Está raro esto che. 
Entiendo cuando decís que tenés un host de Linux 18.04 es un Ubuntu (o flavor), ¿pero es un SO que uses normalmente en tu día a día? Porque te está fallando porque te faltan herramientas que VBox aparentemente necesita, que deberías tener instaladas porque vienen por defecto con paquetes base para desarrolladores. Eso también me levanta otra duda, ¿el paquete de VBox lo instalaste con apt o cómo hiciste? Porque sea apt o dpkg te lo tendría que haber instalado todos los paquetes que necesita para levantar

Me da la sensación que hay algo que se instaló mal ahí
¿Te copás en darte un vuelta el sábado al soporte así lo vemos? Creo que va a ser más rápido si lo vemos en vivo y me explicás todo lo que hiciste

**Comment by celeslvp** [comment]
Hola gastón, perdón por contestar tan tarde, al final me cansé y el finde saqué ubuntu y me pasé a windows 10 jajaja, ahora con windows me anda bien, gracias igualmente
