### ISSUE TITLE
como saber si logre resolver de forma correcta el TP0

### ISSUE THREAD

**Issue by santisilva** [sisoputnfrba/foro#2028]
Hola a todos,  como dice el titulo, con mis compañeros estamos en duda de si resolvimos bien el tp0 ya que el enunciado no te provee funciones para verificarlo y el video del tp0 ya quedo un poco viejo.

gracias, saludos.

**Comment by RaniAgus** [comment]
¡Buenas!
Como verán, el TP0 es _bastante_ introductorio, sirve como guía para configurar un entorno sencillo y como una primera aproximación a conocer el lenguaje C, las funciones más básicas de las commons y las de la API de Linux.
Es cierto que se quedó un poco viejo, la idea original de éste era, en la presencialidad, organizar un workshop en el aula magna para resolverlo en el momento. Aún así, se pueden hacer un par de verificaciones útiles:

1. Comprobar que se envíen bien los mensajes logueando por consola toda la información que necesiten. No hace falta que usen [`printf()`](https://man7.org/linux/man-pages/man3/printf.3.html)s, ya que el TAD [`log.h`](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/log.h) de las commons provee distintos niveles de log para poder elegir ocultarlos o mostrarlos dependiendo de si estás debugeando o en una versión más definitiva como una entrega. También, en el server podrán ver cómo se reciben estos mensajes.

De hecho, un consejo para el TP: les recomiendo ir jugando con los distintos niveles de log según la necesidad que tengan. Por ejemplo, pueden para el día a día codear en nivel `LOG_LEVEL_DEBUG` usando `log_debug()`s. Una vez que vean que lo que loguean es lo esperado ir pasando esos `log_debug()` a `log_trace()`, ya que si más adelante hacen un cambio que rompe algo anterior pueden elegir cambiar el nivel a `LOG_LEVEL_TRACE` y ver en detalle qué está pasando. Otra ventaja que tiene esto es que en la entrega pueden decidir subir el nivel a `LOG_LEVEL_INFO` y ocultar todos esos mensajes en una sola línea de código y sin tener que quitarlos.

2. Verificar que van entendiendo [cómo manejar la memoria](https://docs.google.com/document/d/1v6eKBOSDc17bUjbw8SziuyqGqkzonBwkFUq5nvhYbyk/edit). Es decir, chequear que no estén perdiendo las referencias a memoria dinámica que reservaron con `malloc()`, que no utilicen variables sin inicializar, entre otros errores muy comunes. Para eso, pueden correr su cliente con una herramienta salva-tps: Valgrind. La cual, digamos que, se "mete" en el medio entre el proceso y el SO y detecta estos errores. Tenemos una [guía](https://docs.google.com/document/d/1flOJ2P2g9UGVRiruuA4OCF6nucbN_BWVI0WDlYTJNf4/) y un [video](https://www.youtube.com/watch?v=knRei6OBU4Q) hablando sobre esta herramienta, muy recomendados los dos.

¡Saludos!

**Comment by gastoncastineira** [comment]
@santisilva ¿Te sirvió el comentario? ¿Podemos cerrar el issue?

**Comment by santisilva** [comment]
@gastoncastineira @RaniAgus  si, me sirvio bastante, muchas gracias y disculpas por tardar en responder. saludos

**Comment by RaniAgus** [comment]
¡Buenísimo! Comentario para la próxima: nuestra idea es dejar que los alumnos cierren los issues una vez que tengan su duda resuelta. Saludos :)
