### ISSUE TITLE
Problema al iniciar la vm

### ISSUE THREAD

**Issue by lewislee0920** [sisoputnfrba/foro#2029]
### 📦 Especificaciones de la VM
- Versión de VirtualBox: 
- Memoria RAM asignada:

### 🖥️ Especificaciones del host
- Sistema Operativo y versión:
- Memoria RAM:
- Procesador:

**Comment by lewislee0920** [comment]
Buenas, instale el VM pero cuando trato de iniciarlo dice: "Fallo al abrir una sesion para la maquina virtual" "The virtual machine 'lubunut' has terminated unexpectedly during startup with exit code -1073741819 (0xc0000005). More details may be available in 'C:\Users\HP\VirtualBox VMs\lubunut\Logs\VBoxHardening.log'."

**Comment by mgarciaisaia** [comment]
¡Buenas!

¿Podrás subir acá ese archivo `C:\Users\HP\VirtualBox VMs\lubunut\Logs\VBoxHardening.log`?

**Comment by lewislee0920** [comment]
![Uploading image.jpg…]()

**Comment by lewislee0920** [comment]
Entre al bios

**Comment by lewislee0920** [comment]
Y en parte de virtualization technology dice disabled

**Comment by ncoen97** [comment]
Estamos viendolo en soporte, dejo el log acá.
[VBoxHardening.log](https://github.com/sisoputnfrba/foro/files/6329587/VBoxHardening.log)

**Comment by lewislee0920** [comment]
[Uploading VBoxHardening.log…]()

**Comment by lewislee0920** [comment]
[VBoxHardening.log](https://github.com/sisoputnfrba/foro/files/6329617/VBoxHardening.log)

**Comment by lewislee0920** [comment]
![image](https://user-images.githubusercontent.com/62365146/115120229-c71c0800-9f82-11eb-9aa0-06ba08e2b11c.png)

**Comment by lewislee0920** [comment]
baje el 5.4 y me sale asi

**Comment by iago64** [comment]
Ahi lo que te esta diciendo es que esta tratando de levantar una vm existente, eliminala y volvela a crearla.

**Comment by mgarciaisaia** [comment]
El archivo de log que attacheaste dice que en tu máquina hay un _coso_ llamado `Fasoo DRM`, y en [este thread](https://forums.virtualbox.org/viewtopic.php?f=6&t=97164) de los foros de VirtualBox dicen que eso puede estar interfiriendo con el arranque de la VM.

Ojalá sea viable pausar/apagar/desinstalar ese coso de DRM. ¿Le pegás una probada, si podés?

**Comment by lewislee0920** [comment]
recien desinstale al fasoo drm y bajo de nuevo el version 6.018 y provee pero no sirve igualmente

**Comment by lewislee0920** [comment]
![image](https://user-images.githubusercontent.com/62365146/115132423-5e5e7b00-9fd6-11eb-83bc-718b053c5e11.png)

**Comment by lewislee0920** [comment]
[VBoxHardening.log](https://github.com/sisoputnfrba/foro/files/6330403/VBoxHardening.log)

**Comment by RaniAgus** [comment]
¡Buenas! Veo que la última línea dice:
```
281c.1ffc: supR3HardNtChildWaitFor[1]: Quitting: ExitCode=0xc0000005 (rcNtWait=0x0, rcNt1=0x0, rcNt2=0x103, rcNt3=0x103, 131 ms, CloseEvents);
```

Me fui a la docu de VirtualBox, hay un post que se llama [Diagnosing VirtualBox Hardening Issues](https://forums.virtualbox.org/viewtopic.php?f=25&t=82106) y, en resumen, dice que es un problema al cargar una DLL. Arriba de esa línea veo dos DLLs: `kernelbase.dll` y `kernel32.dll`. Para esta última, tira `[lacks WinVerifyTrust]`, así que puede que sea esa:
```
1308.2890: supHardenedWinVerifyImageByHandle: -> 0 (\Device\HarddiskVolume4\Windows\System32\kernel32.dll)
1308.2890: supR3HardenedWinVerifyCacheInsert: \Device\HarddiskVolume4\Windows\System32\kernel32.dll
1308.2890: supR3HardenedMonitor_LdrLoadDll: pName=C:\WINDOWS\System32\KERNEL32.DLL (Input=KERNEL32.DLL, rcNtResolve=0xc0150008) *pfFlags=0xffffffff pwszSearchPath=0000000000004001:<flags> [calling]
1308.2890: supR3HardenedDllNotificationCallback: load   00007ffdbc020000 LB 0x002a5000 C:\WINDOWS\System32\KERNELBASE.dll [fFlags=0x0]
1308.2890: supHardenedWinVerifyImageByHandle: -> 0 (\Device\HarddiskVolume4\Windows\System32\KernelBase.dll)
1308.2890: supR3HardenedWinVerifyCacheInsert: \Device\HarddiskVolume4\Windows\System32\KernelBase.dll
1308.2890: supR3HardenedDllNotificationCallback: load   00007ffdbda50000 LB 0x000b2000 C:\WINDOWS\System32\KERNEL32.DLL [fFlags=0x0]
1308.2890: supR3HardenedScreenImage/LdrLoadDll: cache hit (VINF_SUCCESS) on \Device\HarddiskVolume4\Windows\System32\kernel32.dll [lacks WinVerifyTrust]
1308.2890: supR3HardenedMonitor_LdrLoadDll: returns rcNt=0x0 hMod=00007ffdbda50000 'C:\WINDOWS\System32\KERNEL32.DLL'
```
Según [este post](https://forums.virtualbox.org/viewtopic.php?f=6&t=86950), podés probar de abrir un Powershell como administrador y tirar este comando para usar la [herramienta de Windows para comprobar los archivos del sistema](https://support.microsoft.com/es-es/topic/use-la-herramienta-comprobador-de-archivos-de-sistema-para-reparar-los-archivos-de-sistema-que-faltan-o-est%C3%A1n-da%C3%B1ados-79aa86cb-ca52-166a-92a3-966e85d4094e) y ver qué mensaje devuelve:
```
sfc /scannow
```
Después de eso, asegurate de [hacer un safe boot](https://support.microsoft.com/en-us/windows/start-your-pc-in-safe-mode-in-windows-10-92c27cff-db89-8644-1ce4-b3e5e56fe234).

Espero que te funcione, no se me ocurren muchas más alternativas 😓

**Comment by lewislee0920** [comment]
prove el de powershell y me sale "Protección de recursos de Windows no detectó ninguna violación de la integridad." y tambien prove de hacer safe boot pero en modo safe boot ni puedo abrir el VM. Dice que hay un error fatal y no me hace abrirlo

**Comment by iago64** [comment]
Buenas! 
Un par de consultas rápidas:
1.- Tenes algun antivirus andando? Si es asi cual?
2.- Cuando eliminaste virtualbox y lo volviste a instalar, reiniciaste en el medio? Despues de reinstalar, volviste a eliminar el vdi y lo volviste a crear?

Capaz con esto podemos darnos alguna idea extra.
Abrazo.-

**Comment by lewislee0920** [comment]
no tengo antivirus y cuando volvi a instalar VB elimine el file 
![image](https://user-images.githubusercontent.com/62365146/115270259-82bf7200-a112-11eb-92b1-e36a01bc3d15.png)
este

**Comment by lewislee0920** [comment]
Buenas, estube tratando de solucionar el errore pero ahora me sale esto:
![image](https://user-images.githubusercontent.com/62365146/115588686-5f78fc00-a2a5-11eb-91ec-7a44201a6967.png)

**Comment by lewislee0920** [comment]
[VBoxHardening.log](https://github.com/sisoputnfrba/foro/files/6352517/VBoxHardening.log)
[VBox.log](https://github.com/sisoputnfrba/foro/files/6352518/VBox.log)
Por caso dejo los documentos de VM

**Comment by lewislee0920** [comment]
Lo podia resolver al problema de inicio pero no se que tengo que poner para la contrasena 
![image](https://user-images.githubusercontent.com/62365146/115602510-6871c980-a2b5-11eb-9d1e-05b22410134c.png)

**Comment by mgarciaisaia** [comment]
¿Anduvo al final, che?

**Comment by lewislee0920** [comment]
Lo probe todos lo que podia y en fin podia iniciarla pero no se instala bien el guest addition

**Comment by velonna** [comment]
> 
> 
> Lo probe todos lo que podia y en fin podia iniciarla pero no se instala bien el guest addition

Avisame si lograste resolverlo, porque  estoy  en la  misma

**Comment by lewislee0920** [comment]
no no podia solucionarla

**Comment by Nachiten** [comment]
Cerrado por inactividad. Si necesitan algo abren este issue o crean otro. Saludos!
