### ISSUE TITLE
Me quedé trabado en la Etapa 4 (Debugger)

### ISSUE THREAD

**Issue by solasantiago** [sisoputnfrba/foro#2030]
Al debuggear estoy teniendo este error.
![image](https://user-images.githubusercontent.com/46433778/115101136-1f69f000-9f18-11eb-933e-c7709cfc7c35.png)
Esto es indistinto a la función que use, tanto crear_paquete() como crear_super_paquete() es el mismo error.

Adjunto mi resolución del tp0 por si estoy invocando algo mal, pero estimo por el error que no tiene que ver con el código.
[tp0.txt](https://github.com/sisoputnfrba/foro/files/6328612/tp0.txt)

**Comment by mgarciaisaia** [comment]
De todo lo que hay ahí, ¿cuál es el error que estás teniendo?

**Comment by solasantiago** [comment]
> De todo lo que hay ahí, ¿cuál es el error que estás teniendo?
El cartel que dice:
No source available for "__kernel_vsyscall() at 0xb7fdac31"
No me deja avanzar con el debug.

**Comment by mgarciaisaia** [comment]
👌

Bueno, eso... Faltó leer, me parece 🙃

En el template de los issues dice que antes de preguntar uses el buscador del foro. Y hay [4 issues más](https://github.com/sisoputnfrba/foro/search?q=No+source+available&type=issues) que mencionan el problema de `No source available`.

Pegales una mirada, fijate qué entendés, si alcanza para solucionar tu problema/duda, o seguí consultando a partir de lo que hayas entendido :)

**Comment by solasantiago** [comment]
> Bueno, eso... Faltó leer, me parece 🙃

Disiento, lo busqué en el foro: lo busqué como <etapa 4>, también como <kernel>, y realmente no encontré algo relacionado. Al buscar <No source available>, encontré los 4 issues que citás, donde el único que compartía mi "error" completo (junto a "__kernel_vsyscall()") era el autor del issue #968, el cual cito:

> me dijeron que esto lo tira porque en debug no esta el flag entonces no encuentra las syscall del kernel. aca tengo dos problemas uno no entiendo porque no lo encuentra porque pruebo debuguear un write con pipes y anda bien sin explotar. dos si sigo pasando las lineas cuando hago el read para leer lo que me mando el proceso hijo en este no hay nada.

A continuación, ese mismo issue es cerrado por el autor, y en un comentario al día siguiente puedo ver un meme que expresa la misma cara que puse yo al querer entender lo que estaba leyendo.

Lo que no noté fue que "__kernel_vsyscall()" _era un llamado a una función_, y no un error de kernel, o de una syscall, por lo cual ahora que estoy un poco más en contexto, puedo comprender que el "error" se relacionaba con un llamado a una función y también, que puedo relacionarlo con los otros 3 issues, en donde lo cito a usted [en uno de ellos](https://github.com/sisoputnfrba/foro/issues/246#issuecomment-216056670), por si alguien se topa con este issue con la misma duda que yo:

> No source available no es un error de la ejecución - es un mensaje de Eclipse diciendo que no puede mostrarte el código fuente.

(Esto lo resolví por discord con un ayudante que me aclaró todas las dudas que tenía y que se me despertaron en el momento).

Saludos.

**Comment by mgarciaisaia** [comment]
Che, perdón - mi mensaje se lee más mala onda de lo que pretendía escribirlo. Ojalá no te haya jodido mucho.

En efecto, lo importante era eso: `No source available` es un error de vista.

Estas consultas aparecen todos los cuatris, y por eso en vez de contestar quería empujar un poco el buscar otras respuestas.

Y, buen - también quizá no se encuentren tantos issues como creía por esto de que la mayoría tendrá screenshots de los mensajes de error en lugar de los errores escritos en texto buscable. Con algo de suerte, este thread ayuda a terminar con esa racha :)

**Comment by solasantiago** [comment]
No pasa nada, yo también fui medio susceptible al leerlo.
¡Saludos!
