### ISSUE TITLE
Consulta Release 18.04.5 LTS

### ISSUE THREAD

**Issue by jasanchezutn** [sisoputnfrba/foro#2031]
Hola, buenas noches.
Quería consultarles si era recomendable actualizar ambos servidores al release 18.04.5 LTS, dado que lo está recomendando. Pero no se si puede afectar en algo al ambiente para realizar los trabajos y pruebas. 
*Con los pasos de la materia, para la configuración y actualización de las VMs, no tuve problemas.
Muchas gracias!

**Comment by gastoncastineira** [comment]
Buenas,
En general es recomendable tener todo actualizado pero en este caso nosotros lo desaconsejamos. Se podría dar el caso que alguna biblioteca del se actualice y tenga un comportamiento distinto en tu máquina que en la de tus compañeros que no actualizaron

**Comment by mgarciaisaia** [comment]
Si me preguntás, esta respuesta creo que es una de las mayores "deudas" que tenemos como cátedra.

Las buenas prácticas de seguridad informática dicen que deberías mantener tu software siempre actualizado, para tener los últimos parches a vulnerabilidades de seguridad. Hay distintos modelos de versionado que usan los distintos paquetes de software (algunos te permiten hacer actualizaciones que sólo incluyen correcciones, sin incluir funcionalidades nuevas, mientras que otros no), pero el consenso es que en general siempre actualices.

Pero, pero, pero... Acá (al menos por ahora) estamos haciendo las cosas distinto.

En pos de evitar que una actualización de algún paquete de la VM meta alguna modificación a último momento que termine impactando el sistema que desarrollan ustedes para su TP, por ahora elegimos recomendar que mantengan la VM como se las damos, porque _exactamente esa_ VM es la que van a tener en las máquinas en que van a probar su TP en el laboratorio [virtual] el día de la entrega.

De nuevo: es mala práctica de seguridad usar software desactualizado. En el caso del TP elegimos hacer la excepción priorizando la estabilidad del ambiente de prueba, y un poco también entendiendo que las VMs están _más o menos_ aisladas, por lo que un eventual problema de seguridad quizá no tenga un impacto tan alto (_ponele_).

Pero, sí, eso: no actualicen.

**Comment by jasanchezutn** [comment]
Gracias por la aclaración. Saludos!
