### ISSUE TITLE
Guest additions

### ISSUE THREAD

**Issue by NazarenoLopez** [sisoputnfrba/foro#2032]
Estimados, muy buenas noches. Perdonen la molestia. Estuve con algunos problemas con las librerias readline que no me las abría correctamente. Baje VirtualBox 5.4 y anduvieron, el tema es que no funciona las guest adittions. Alguno me podría ayudar? No realicé ningún cambio ni actualziación del ubunty ni nada.

**Comment by mgarciaisaia** [comment]
@NazarenoLopez ¿el problema con readline lo tenías _dentro de la VM_ (es decir, en el sistema operativo guest; el Ubuntu que les damos nosotr@s) o en el host (tu Windows/Linux/macOS que usás siempre)?

Si es dentro de la VM, readline no debería tener problemas dependiendo de la versión de VirtualBox que uses para virtualizar. Puede existir un bug muy extraño por el que suceda tal cosa, pero es _muy, muy, muy_ improbable. Digamos, poder o no instalar readline en la VM no es motivo que amerite cambiar la versión de VirtualBox. Así que, qué se yo - en una de esas quieras volver a la versión de VirtualBox que tenías antes.

En la versión que tenés ahora, ¿volviste a instalar las Guest Additions? ¿Tenés algún reporte de error o síntoma o algo más que "no andan"? A ver si podemos buscar algo más.

**Comment by NazarenoLopez** [comment]
Si está dentro de la VM. utilizo windows. Volví a instalar las guest additions y lo que no funciona es que se pueda ver en pantalla completa. Actualizando ubuntu si funciona, pero dejan de acerlo las guesto additions

**Comment by mgarciaisaia** [comment]
Si en este momento tenés un VirtualBox 5 _porque andaba mal readline en la máquina virtual_, sugeriría que upgradees de vuelta VirtualBox a La Versión Que Nos Gusta™ (6.0.18 venía siendo la que menos problemas venía trayendo), instales las guest additions, y, asumiendo que ahí funcionen bien, recién ahí veamos de solucionar el problema con readline.

Un poco para no usar un VirtualBox tan viejo (que capaz directamente es incompatible con algo de la VM esta, no sé), pero también bastante porque el problema de readline seguramente tenga logs más fáciles de encontrar, entender, y solucionar 😇

¿Te parece?

Probá qué onda, y contame.

**Comment by Nachiten** [comment]
Buenas! @NazarenoLopez quedó solucionado tu problema? Para saber si podemos cerrar, gracias!

**Comment by Nachiten** [comment]
Cerrado por inactividad. Si necesitan algo abren este issue o crean otro. Saludos!
