### ISSUE TITLE
problema con logging y errores

### ISSUE THREAD

**Issue by MilenaGarro** [sisoputnfrba/foro#2033]
<!--
haciendo el tp0 no me aparece en la consola el "soy un log" ni se creó el tp0.log, segui todos los pasos como muestra en el video de youtube del 1c2020. También me aparecieron muchos errores en el makefile que no se de qué son, lo menciono porque quizas puede ser el problema de lo anterior

(les pongo una foto para que tengan una idea de estos errores medio raros que me marco en el makefile en la parte de project explorer) 

![WhatsApp Image 2021-04-19 at 17 53 05](https://user-images.githubusercontent.com/82156686/115301993-4dc61600-a138-11eb-9266-b88f9875bebe.jpeg)

--!>

**Comment by MilenaGarro** [comment]
haciendo el tp0 no me aparece en la consola el "soy un log" ni se creó el tp0.log, segui todos los pasos como muestra en el video de youtube del 1c2020. También me aparecieron muchos errores en el makefile que no se de qué son, lo menciono porque quizas puede ser el problema de lo anterior

(les pongo una foto para que tengan una idea de estos errores medio raros que me marco en el makefile en la parte de project explorer) 

![WhatsApp Image 2021-04-19 at 17 53 05](https://user-images.githubusercontent.com/82156686/115301993-4dc61600-a138-11eb-9266-b88f9875bebe.jpeg)

**Comment by RaniAgus** [comment]
¡Buenas! Quizás el problema esté en que importaste el repo de las commons y dejaste en él el repo del TP0. En tu situación lo que haría sería:
1- Quitar el proyecto de las commons: `Click derecho en so-commons-library > Delete > Ok`. Asegurate de tener desmarcada la opción "de eliminar los archivos en disco".
2- Mover la carpeta `tp0` fuera de la carpeta commons (preferentemente en `workspace`, ya que esa es el área de trabajo por default en Eclipse).
3- Importar de nuevo la carpeta `tp0` de nuevo como indica el video.

Un ejemplo de cómo debería quedarte:
![image](https://user-images.githubusercontent.com/39303639/115307957-5f132080-a140-11eb-940c-598b927fdb4c.png)

Recordá que en Eclipse podés tener importados varios proyectos en simultáneo, no hace falta que estén todos en una única carpeta, por ejemplo, si me quiero importar los proyectos en el repo de las commons (las carpetas `src` y `tests/unit-tests`) me quedarían todos así:
![image](https://user-images.githubusercontent.com/39303639/115308744-946c3e00-a141-11eb-9fa8-e2098dfaba09.png)

¡Saludos!

**Comment by Nachiten** [comment]
Buenas! @MilenaGarro como vas? Pudiste solucionar ya este problema? Para poder cerrar el issue, gracias!

**Comment by MilenaGarro** [comment]
Hola! Perdon por no avisarte! Hice lo que me dijiste y se solucionó! Muchas
gracias
