### ISSUE TITLE
Dudas módulo Discordiador

### ISSUE THREAD

**Issue by matiasfdevecchi** [sisoputnfrba/foro#2034]
Buenas, leyendo el módulo Discordiador me surgieron algunas dudas:

**DUDA 1: Módulo Discordiador / Lineamiento e Implementación / Administración de los sabotajes**

> Una vez solucionado el sabotaje, es decir, que termine su tiempo de duración (definido por archivo de configuración), todos los tripulantes deberán ser desbloqueados en el orden en el cual fueron bloqueados.

Si tengo a los tripulantes 6 y 8 bloqueados por I/O y ocurre la siguiente secuencia:
1. Tripulante 8 termina su tarea
2. Bloqueo por emergencia a Tripulante 8
3. Tripulante 6 termina su tarea
4. Bloqueo por emergencia a Tripulante 6

¿Entonces debería desbloquear primero a tripulante 8 y luego a tripulante 6? (me parece lógico por el enunciado pero es para despejar dudas)

___

**DUDA 2: Módulo Discordiador / Lineamiento e Implementación y Módulo Discordiador / Consola**

> Cuando reciba por la consola del discordiador el mensaje "iniciar planificación", dará comienzo a la administración de los tripulantes, la cual debe poder ser pausada ("pausar planificación") y reanudada en cualquier momento para poder revisar el estado de los mismos en forma ordenada.

La descripción del lineamiento menciona que la planificación puede renaudarse, sin embargo en consola no hay un comando específico para eso e _INICIAR_PLANIFICACIÓN_ no hace mención a que puede utilizado para renaudar.

¿Se reanuda con un comando que no fue descripto o con _INICIAR_PLANIFICACIÓN_?

___

**DUDA 3: Módulo Discordiador**

Se menciona las patotas en varios casos. La duda que me surgió con esto es:
1. ¿Un tripulante puede no estar en una patota y realizar tareas o debe estar en una patota de un miembro?
2. ¿Un tripulante dentro de una patota puede salir de alguna manera de esa patota o quedará hasta el fin de la ejecución?
3. Si se quiere iniciar una patota con un tripulante que está en otra patota, ¿Se cambia el tripulante de patota, se cancela la petición de iniciar una nueva patota o se realiza igualmente la petición ignorando a ese tripulante?

___

**DUDA 4: Módulo Discordiador**

¿Cuántos tripulantes pueden haber? ¿Esta relacionado con _GRADO_MULTITAREA_ o es indistinto?

Gracias, saludos.

**Comment by Nachiten** [comment]
Buenas!! Como estas?

Paso a responderte las dudas que sé contestarte hasta el momento.

**DUDA 1:**
La respuesta es si. Si yo bloquee a 6, 8, 10, 12. Luego voy a desbloquear en el orden: 6, 8, 10, 12.

**DUDA 4:**
La respuesta también es sí. La cantidad de tripulantes que pueden haber es literalmente el grado de multitarea. Dado que este numero te dice cuantos tripulantes pueden estar trabajando a la vez (grado de multiprocesamiento).

Dejo el resto de dudas para que te las responda otro ayudante, dado que yo no estoy seguro todavia.

Un saludo 😄

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va? Me sumo para contestarte:

### Duda 2
Es buena la pregunta porque puede ser que no esté tan bien aclarado, podemos revisarlo. Está pensado para que `INICIAR_PLANIFICACION` también sirva para reanudarla, ya que, citando más abajo, la idea sigue siendo _"que hasta este punto no hayan movimientos entre las colas de planificación ni de los tripulantes"_. Esta situación se da tanto al inicio del proceso como luego de enviar un `PAUSAR_PLANIFICACION`, así que no tendría mucho sentido hacerlos codear un mensaje de más :)

### Duda 4
Me sumo al comentario de Nacho para aclarar algo que creo que te va a ayudar a entender mi respuesta en la duda 3, cito la "Administración de los tripulantes":
> Mientras la planificación esté activada, a medida que vaya recibiendo la confirmación de los tripulantes, el Discordiador moverá la cantidad necesaria de los mismos hacia el estado “trabajando” (exec). **Para ello, se tendrá en cuenta un límite de tripulantes permitidos para trabajar en simultáneo dictado por archivo de configuración (también conocido como grado de multiprocesamiento).**

Es decir, si nos referimos a la cantidad de tripulantes que puede haber **en simultáneo, en estado EXEC** sí se define mediante el `GRADO_MULTITAREA` y, haciendo una analogía con la teoría, se refiere al grado de multiprocesamiento.

Ahora, si te referías a la cantidad de tripulantes en todo el sistema, en cualquier estado, (que en la teoría sería el "grado de **multiprogramación**"), no está definido un límite, sino que va a arrancar el proceso en 0 y, a medida que los vayas iniciando mediante `INICIAR_PATOTA`, se irán creando en el sistema.

Habiendo aclarado esto, contesto tu duda:

### Duda 3

1. Un tripulante debe sí o sí estar dentro de una patota, de hecho, no existe otra forma de iniciarlos que no sea desde consola mediante `INICIAR_PATOTA`.
2. Tampoco se menciona que exista la posibilidad de cambiar tripulantes entre patotas, en consecuencia podemos asegurar que pertenecen a la misma de principio a fin.
3. Cada vez que se inicie una patota, los tripulantes que se crean en ella son nuevos (recordemos, no hay definido un grado de multiprogramación), así que no es posible iniciar una patota con un tripulante que ya esté creado y, por ende, pertenezca a otra.

Gracias por tomarte el tiempo de redactarnos tus inquietudes y con citas al enunciado, es muy valioso porque en ocasiones se puede encontrar algo que no está muy bien detallado y que amerite a una corrección de nuestra parte :)

¡Saludos!

**Comment by matiasfdevecchi** [comment]
¡Muchas gracias por sus respuestas! Aclararon todas mis dudas y apareció una nueva.
A modo de feedback, en el enunciado no aclara explicitamente como se instancian los tripulantes según lo que leí y me parece importante aclarar que al iniciar una patota, se instancian los tripulantes pertenecientes a esa patota.
Esto me generó una nueva duda: ¿Una vez que la patota termina su listado de tareas, esta se destruye y sus tripulantes también (similar a expulsión)?

**Comment by RaniAgus** [comment]
> ¿Una vez que la patota termina su listado de tareas, esta se destruye y sus tripulantes también (similar a expulsión)? 

Creo que es un tema que se explica mejor desde la teoría, pero para darte una respuesta espero explicarme bien: una vez que **un tripulante** termine **sus tareas**, cuando pida su siguiente tarea a Mi-RAM HQ ésta va a retornar que no hay ninguna. Luego, lo que decidan implementar sobre lo que ocurre a partir de ahí (y si es una analogía fiel a lo que se explica en la teoría) se charlará en su momento cuando toque el coloquio 😉
