### ISSUE TITLE
Duda resolución de sabotaje en Módulo Discordia

### ISSUE THREAD

**Issue by int0x80-sys** [sisoputnfrba/foro#2035]
Buenas. Estuve leyendo el enunciado y tengo unas duda sobre el módulo Discordia.

En el enunciado se menciona que, ante un sabotaje, se debe buscar al tripulante mas cercano y moverlo hasta la posición del sabotaje. Mi dudas son:

1. En caso de que se este usando RR en el planificador ¿Se debe gastar el quantum del tripulante para moverlo hasta la posición del sabotaje?

2. Una vez que el tripulante llega al lugar del sabotaje, antes de bloquearlo ¿Se lo debe devolver a la posición original o cuando sea replanificado tiene que iniciar desde la posición del sabotaje?

Saludos 👋 .

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va?

En la administración de los sabotajes se menciona que:
> En momentos aleatorios llegará un aviso de sabotaje en una región (posición X e Y). Todos los tripulantes deberán dejar sus tareas en ese momento, **pasando a estado bloqueado** [...]

> Por último, **el sistema deberá buscar al tripulante más cercano a la ubicación del sabotaje y planificarlo** para que se mueva a dicha ubicación y resuelva el sabotaje **invocando al FSCK del i-Mongo-Store**, pasándolo al final de la cola de bloqueados de emergencias.

Es decir que:
1. **Todos** los tripulantes pasan a BLOCKED, lo que significa que los que estén haciendo tareas salen de EXEC. Cuando se seleccione a uno y se lo planifique para moverlo a la posición del sabotaje, como el resto está bloqueado da lo mismo si es FIFO o RR porque READY está vacía.

2. El tripulante llega al lugar del sabotaje y se bloquea porque el FSCK es una solicitud al i-Mongo Store, solo que en este caso se especifica que se pasa al final de la cola de bloqueados por emergencias. No se especifica que haya que moverlo hacia donde estaba antes de la emergencia, así que quedaría en la posición del sabotaje.

¡Saludos!

**Comment by int0x80-sys** [comment]
Hola de nuevo. Gracias por la rápida respuesta.

Con respecto a lo primero, si bien es verdad que daría lo mismo, el problema estaría que, si yo lo muevo al tripulante usando su quantum, puede que al llegar al lugar de sabotaje quede con un quatum distinto al que tenía. Por eso preguntaba si al mover el tripulante tendríamos que gastar su quantum o si solo debemos modificar su posición.

En cuanto a lo segundo, quedo todo claro 👍 .

Saludos.

**Comment by ncoen97** [comment]
Buenas!
Afirmo la respuesta de Agus de que sería lo mismo, tené en cuenta que igualmente cuando este tripulante llegue al lugar de sabotaje se va a bloquear. Por lo tanto cuando vuelva a iniciar la planificación todos van a empezar con todo el quantum disponible (y en este caso no tenemos un quantum remanente como en el caso de VRR).
Saludos!

**Comment by int0x80-sys** [comment]
Ah. Perdón, es verdad. Estaba pensando en VRR. Mala mía.

Gracias por las resupestas 🚀
