### ISSUE TITLE
Problema de delay con la MV

### ISSUE THREAD

**Issue by andreavgomez** [sisoputnfrba/foro#2036]
Hola, buenas tardes !!
Tengo problema de delay en mi MV . Que puedo hacer ?
Gracias

**Comment by karengrams** [comment]
¡Buenas buenas!

¿Cómo va? Espero que bien. Andaríamos necesitando un poco más de información para poder darte una mano con tu problema. ¿Podrías indicar la información que estaba en el template? 

¡Saludos! 😸 .

**Comment by andreavgomez** [comment]
Hola !!
Configure todo tal cual está en la página de sistemas operativos, todo perfecto salvo que tarda mucho en levantar todo (varios minutos) cada cosa que abro tarda bastante 
Levantar la MV Lubuntu , eclipse. Tarda un montón, 4 o 5 minutos en levantar cada cosa.
Mi notebook tiene procesador intel i5, 12GB de memoria, disco sólido 400 GB
Si necesitan algún dato más por favor avísenme 
Gracias

**Comment by RaniAgus** [comment]
¡Buenas! Karen te preguntaba por el [template](https://raw.githubusercontent.com/sisoputnfrba/foro/master/.github/ISSUE_TEMPLATE/02-necesito-ayuda-para-configurar-las-vms-de-la-c-tedra.md) que aparece al [crear un issue](https://github.com/sisoputnfrba/foro/issues/new/choose) porque, entre otras cosas, incluye la memoria RAM que tiene asignada la VM. 
Lo único que te puedo decir con esa info es que si tiene asignado menos de 2GB puede que se note que tarda un toque en cargar; y que, teniendo 12GB en el host, seguro no habrá problema con asignarle esos 2GB al guest (la VM).

¡Saludos!

**Comment by andreavgomez** [comment]
Esta es la configuración de la MV

[image: image.png]


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mgarciaisaia** [comment]
No se adjuntó bien la imagen en Github =/

Dado lo genérico que es todo el problema (digamos, no hay un mensaje de error o alguna configuración puntual que decirte que toques), diría que lo mejor es que te metas un rato en Discord con alguien para compartir pantalla y tratar de ver qué estará pasando.

¿En qué horario te quedará más o menos cómodo de lo que queda de hoy, o mañana, o estos próximos días? A ver si conseguimos algun@ ayudante que coincida en horarios y lo puedas ver en vivo con alguien.

**Comment by andreavgomez** [comment]
Mañana a la tarde puedo !!

**Comment by mgarciaisaia** [comment]
@andreavgomez ¿Podés pasarte ahora a las 3pm por #el-labo en Discord?

**Comment by andreavgomez** [comment]
Si si puedo !!

**Comment by andreavgomez** [comment]
Listo !! solucionado !!
En la configuracion de la MV Lubunto en:
 - Sistemas/procesadores, seleccione 2 procesadores
 - Pantalla/memoria de video selecciones 64 MB
 Con eso funciono mas rapido !!
Tambien volvi a instalar las Guest Additions, porque la pantalla no se habia agrandado del todo y pude agrandar la pantalla en la MV, tambien configure dentro de la MV en el menu (arriba) dispositivos/Portapapeles compartidos, seleccione Bidireccional y pude hacer copy paste.
Muchas Gracias !!
