### ISSUE TITLE
Dudas sobre cuando o como se crea un tripulante y sobre las tareas asignadas al mismo

### ISSUE THREAD

**Issue by arielsarchioni** [sisoputnfrba/foro#2037]
Leyendo el enunciado y teniendo en cuenta la definición del mismo de que Las Patotas representan a los procesos y los Tripulantes representan a los hilos que pertenecen a esa Patota-Proceso, nos surgen las siguientes dudas que enumeramos en el orden en que aparecen en el enunciado, mencionando la hoja en la que se encuentran (NOTA: La última hoja del enunciado dice 28 de 29, ¿falta 1 hoja o en realidad son 28 en total?). 
 
Todas las dudas están relacionadas a lo mismo:
•	Cuando o como se crea un tripulante y sobre las tareas asignadas al mismo:
 
**Hoja 8:** 
 
ENUNCIADO: "Administración de los tripulantes
Cada tripulante, al iniciarse, se conectará al Discordiador y comenzará sus tareas de preparación. Una vez que se encuentre listo, le informará al mismo dicha situación."
 
DUDAS: Como o cuando se crea un tripulante? leímos todo el enunciado y no nos queda claro cuando o como se crea el mismo (el momento en que comienza a existir, osea momento en que se le asigna su TID)
Mas adelante está la función INICIAR_TRIPULANTE del módulo MI-RAM HQ pero entendemos que no es ese método quien lo crea. También está el método/función INICIAR_PATOTA de la consola del modulo Discordiador, a la cual se le pasa la cantidad de Tripulantes pero no sus TIDs y nos surgen mas dudas que planteamos en el siguiente punto.
 
Otras dudas son:
¿Cuáles son las tareas de preparación del Tripulante? Ya que no se vuelven a mencionar en el enunciado. 
¿Qué determina que un tripulante esté "Listo"?
 
**Hoja 9:** 
 
ENUNCIADO: "Iniciar patota 
 
Recibirá como parámetro la cantidad de tripulantes que tendrá la patota, un archivo de tareas que deberán ejecutar los tripulantes de la patota y una lista de posiciones iniciales de los tripulantes."
 
DUDAS: ¿Acá se crean los tripulantes?
INICIAR_PATOTA no recibe los TIDs de los Tripulantes, entonces como sabe cuales son sus tripulantes y a quien posicionar? Y visto de otro modo como sabe un Tripulante a que Patota pertenece?
 
Dado que no recibe TIDs de sus Tripulantes, pensamos que INICIAR_PATOTA podría ser el encargado de "crear" sus tripulantes, pero en la definición del método INICIAR_TRIPULANTE del módulo MI-RAM HQ(ver mas adelante) dice que "…En caso de que NO se encuentre creada la patota a la que pertenece…" entonces nos preguntamos ¿Pueden existir Tripulantes sin Patotas? Y eso nuevamente nos lleva a preguntar como o cuando se crean los tripulantes.
 
Por otro lado entendemos que éste método crea las patotas ¿es así?

ENUNCIADO: "Listar tripulantes
Este mensaje devolverá el listado de tripulantes con su estado actual y la patota a la que pertenecen (incluso si son parte de una patota unipersonal)"
 
DUDAS: "patota unipersonal" entendemos que quiere decir que es una patota con un único Tripulante, 
Esto nos lleva a pensar que al crearse un tripulante si o si tiene que pertenecer a una patota, nuevamente pensamos que el INICIAR_PATOTA debería ser quien crea a los Tripulantes y en éste caso imaginamos que esto quiere decir que se ejecutó INICIAR PATOTA con 1 solo tripulante como cantidad y se creó ese único tripulante, pero al igual que antes la definición de INICIAR_TRIPULANTE nos vuelve a generar inconsistencia.
 
**Hoja 10:**

ENUNCIADO: "Sub-módulo Tripulante
El sub-módulo Tripulante es el encargado de obtener y ejecutar todas las tareas que se le definan"

DUDAS: Las tareas que tiene que ejecutar el Tripulante son las tareas que están en el archivo de tareas de su Patota? todos los tripulantes de una patota tienen que ejecutar cada una de las tareas de su patota?
Porque por ejemplo no vimos en la estructura del TCB que el Tripulante tenga un listado de tareas propias, el listado de Tareas lo tiene el PCB de la Patota y por otra parte si no existe su patota que tareas ejecuta?
 
**Hoja 11:**
 
ENUNCIADO: "Al momento de iniciar sus operaciones, el tripulante deberá hacer una serie de comprobaciones básicas:
1.	Informar al módulo Mi-RAM HQ que desea iniciar, indicando a qué patota pertenece.
a.	En caso de que Mi-RAM HQ no tenga las tareas de la patota, enviarle al módulo de memoria el listado de tareas que va a realizar."
 
DUDAS: En que caso puede pasar que MI-RAM HQ no tenga las tareas de la patota? y de donde saca el tripulante ese listado de tareas que le tiene que enviar a la memoria si pasa ésto?
"Tareas
Las tareas que realizará un tripulante estarán determinadas en el archivo de tareas que obtendrá como parámetro al momento de recibir el mensaje INICIAR_PATOTA en la consola del discordiador."
 
Mismas dudas anteriores ¿Qué pasa si no tiene patota?
 
**Hoja 17:**

ENUNCIADO: "Servidor
El módulo de Mi-RAM HQ al ser el encargado de atender las peticiones de los tripulantes, es por esto que el módulo va a tener que responder al menos a los siguientes métodos:
Iniciar tripulante: será el encargado de crear la o las estructuras administrativas necesarias para que un tripulante pueda ejecutar. En caso de que no se encuentre creada la patota a la que pertenece, deberá solicitar el listado de tareas."
  
DUDAS: Esta es la definición que nos hace ruido y que creemos que genera inconsistencia, dice que puede no estar creada la patota a la que pertenece el Tripulante, es decir que según esta definición, el Tripulante puede estar creado antes que su patota y dice que éste método va a crear las estructuras administrativas para que el tripulante pueda ejecutar y no al tripulante en si mismo.
Lo cual sigue causándonos dudas de cuando se crea un tripulante y tira abajo nuestra creencia de que el método INICIAR_PATOTA sea el encargado de crear a los Tripulantes ya que según ésta definición pueden existir los tripulantes antes que la patota.
 
Otro punto es que dice que si no se encuentra creada la patota a la que el Tripulante pertenece,  el módulo MI-RAM HQ le deberá solicitar el listado de tareas al mismo, pero si el listado de tareas lo tiene la patota en su PCB y el Tripulante no tiene un listado de tareas propio, entonces que listado le debe va a informar?

**Comment by gastoncastineira** [comment]
> La última hoja del enunciado dice 28 de 29, ¿falta 1 hoja o en realidad son 28 en total?

Creo que es porque el contador empieza desde el índice y no la carátula, pero en cualquier caso es un bug de google más que nuestro 

> Como o cuando se crea un tripulante?

Los tripulantes se crean con la función de INICIAR_PATOTA en la consola del del discordiador. Ojo al piojo, porque no hay una función de INICIAR_TRIPULANTE en nuestro TP. Lo de Mi-RAM HQ es un abstract diciendo que operaciones debe soportar el módulo, pero no es algo que nosotros como usuarios podamos realizar, sino que es el TP el que va a estar iniciando esas solicitudes

> ¿Cuáles son las tareas de preparación del Tripulante? ¿Qué determina que un tripulante esté "Listo"?

Todo lo que consideres necesario para iniciar un tripulante (ej: Crear su TCB en Mi-RAM, ponerlo en cola de planificación, etc)

>INICIAR_PATOTA no recibe los TIDs de los Tripulantes, entonces como sabe cuales son sus tripulantes y a quien posicionar? Y visto de otro modo como sabe un Tripulante a que Patota pertenece?

No termino de entender esto. ¿Por qué habría que pasarle los TIDs? Cuando iniciás a la Patota no le estás pasando los PIDs, o análogamente a levantar un proceso en tu PC tampoco tengo que decirle cuál es su PID/TID. Es el SO el que se encarga de asignar los IDs de lo que maneja
Por otro lado, tampoco entiendo por qué no sabés qué tripulante es de qué patota. Si vos estás levantando 5 tripulantes en la patota 3, ¿no sabrías ya que esos 5 tripulantes son de esa patota?

> "patota unipersonal" entendemos que quiere decir que es una patota con un único Tripulante ¿Pueden existir Tripulantes sin Patotas?

Es así, **NO** puede haber tripulantes que no estén asignados a una patota. No entiendo muy bien qué inconsistencia te genera eso contra Mi-RAM. ¿Quizá estés sobreentendiendo algo mal del enunciado que no me estés comentando? Reitero por si acaso, Mi-RAM no tiene consola.

> Las tareas que tiene que ejecutar el Tripulante son las tareas que están en el archivo de tareas de su Patota? todos los tripulantes de una patota tienen que ejecutar cada una de las tareas de su patota?

Sí a ambos

> En que caso puede pasar que MI-RAM HQ no tenga las tareas de la patota? y de donde saca el tripulante ese listado de tareas que le tiene que enviar a la memoria si pasa ésto?

Podría ser por ejemplo algo como
```
Discordiador -> CREAR_PATOTA 2 -> Crear tripulante 1
Mi-RAM -> Crear tripulante -> Verificar PCB (ponele) -> no existe -> notificar
Discordiador -> enviartareasamiram
Mi-RAM -> Crear PCB 
Discordiador -> Crear Tripulante 1
Mi-RAM-> Verificar PCB (ponele) -> existe -> Crear TCB 1 
Discordiador -> Crear tripulante 2
Mi-RAM-> Verificar PCB (ponele) -> existe -> Crear TCB 2
```
No es más que un ejemplo, pueden encararlo como ustedes gusten, incluso creando primero la patota y luego los tripulantes. Estas cuestiones de diseño están para que ustedes las piensen y luego nos las expliquen y defiendas en los coloquios

> Hoja 17

Esto desde ya te digo lo vamos a estar corrigiendo en una futura errata. La verdad releyendolo ahora es poco claro el tema del "crear tripulante" y entiendo por qué presta a confusiones.
Pequeño spoiler, falta un puntero al PCB en los TCB, por eso no te cierra lo de las instrucciones. ¡Gracias por aclararlo!

**Comment by arielsarchioni** [comment]
Hola @gastoncastineira, gracias por las respuestas!. Si presta confusión, con tus definiciones nos queda mucho mas claro pero genial que haya servido para que puedan revisar el enunciado y ajustarlo. Gracias y Saludos!
