### ISSUE TITLE
Consultas de enunciado más que nada relacionadas a responsabilidades y comunicaciones entre los módulos

### ISSUE THREAD

**Issue by julchat** [sisoputnfrba/foro#2038]
Hola, estuvimos discutiendo el tp en grupo y nos surgieron algunos problemas con el enunciado sobre los cuales no tenemos certeza sobre que es lo que se plantea.
Aclaro primero que quería usar la plantilla que alguno de ustedes diseñó, pero por esta vez que son dudas muy generales del tp y capaz la primera relacionada con alguna de las últimas, dividirlo en secciones iba a ser bastante confuso. Aún así, se aprecia el esfuerzo.

1- El módulo discordiador será un proceso multihilo. Una pregunta que nos surgió acá es si, primero, se piensan correr varios discordiadores al mismo tiempo, para que interactúen con los mismos módulos de MI-RAM-HQ y i-Mongo-Store. Las patotas, representan también hilos del proceso? 

2- 

> Cada tripulante, al iniciarse, se conectará al Discordiador y comenzará sus tareas de preparación. Una vez que se encuentre listo, le informará al mismo dicha situación.

> Este submódulo se implementará mediante hilos creados bajo demanda en el Módulo Discordiador.

Acá no nos quedo bien en claro lo primero. ¿Cómo hace el tripulante para conectarse a su módulo padre? En sí no es que tenga el ip y puerto del mismo, o es algo que, considerando que el ip de uno mismo estaba definido con el 127.0.0.0, podríamos definir dentro del mismo proceso? Lo raro es que después en el sub modulo del tripulante no menciona nada de que se debe conectar al modulo discordiador

3- ¿Quién manda la señal SIGUSR1 a i-Mongo-Store? ¿Cómo la envía? ¿Por consola de afuera, o es otro módulo el que envía la señal a través del sistema operativo?

4- 

> En algún momento, un tripulante (designado por el discordiador) solicitará que se controle el status del File System y dará inicio al proceso de fsck.

¿Esto indica que esa espera para que un tripulante inicie la reparación es asincrónica? Osea que, mientras tanto, el i-Mongo-Store debería poder realizar sus otras funciones normalmente?

5- ¿Todas las patotas conviven en el mismo mapa? Si es así, el sabotaje lo arreglaría el tripulante de todas las patotas que esté más cercano para atender el sabotaje?

6- El discordiador tiene alguna especie de estructura similar a un TCB/PCB? Porque por ejemplo, debería tener registro de los estados en los que se encuentra cada tripulante, y, para imprimir la respuesta del mensaje LISTAR_TRIPULANTES debería tener cierta información de ellos. Debería solicitar tal información a memoria o mantener cierta parte en el discordiador?

7- Si quiero mandar un mensaje a otro módulo desde discordiador, debería abrir un hilo exclusivo para el mismo y su respuesta, no?

8- Ahora bien, si es el sub módulo tripulante el que quiere envíar un mensaje, ¿es necesario?

9- Al iniciar una patota con el mensaje, INICIAR_PATOTA <cant tripulantes> <ruta archivo de tareas> <[posicionx|posiciony]>, puedo cargar la configuración directamente desde el discordiador, o debo utilizar al i-Mongo-Store para leer el archivo?

10- En el caso de MI-RAM-HQ, yo no cuento ni en los PCB ni en los TCB con ninguna información sobre el ID del otro, como hago entonces, para saber a que patota pertenece un tripulante? Calculo que como en el trabajo anterior, no se puede tener una estructura administrativa, así que, para saber que próxima tarea va a ejecutar un tripulante (que si no me equivoco, se la debería asignar el discordiador), como sé de que segmento de tareas tomar las tareas que corresponden a la patota del tripulante? 

11 - Cuando es que el módulo de MI-RAM-HQ, recibe las tareas? Debería el discordiador decirle a memoria que se creó una nueva patota, o sería mas sensato que cuando cada tripulante quiera avisar a MI-RAM-HQ que este se creó, el módulo de memoria, al verificar que la patota correspondiente al tripulante no existe, crearía el PCB y solicitaría al módulo discordiador las tareas correspondientes a dicha patota. Si es así, está permitido que lo que reciba MI-RAM-HQ sea un conjunto de bytes en donde los bytes correspondientes a cada tarea, adelante suyo, tienen un entero que representa la longitud en bytes de la tarea? O sería trampa porque podría ser considerado una estructura administrativa?
 
Ej: para las tareas de la patota25 que tiene una tarea de 20 bytes, otra de 16 bytes, y otra de 21, podría hacer que MI-RAM-HQ reciba

size_t con valor = 20 bytes -- 20 bytes de primera tarea -- size_t con valor = 16 bytes -- 16 bytes de segunda tarea -- size_t con valor = 21 bytes -- 21 bytes de tercera tarea.

De esta forma puedo saber cuando termina la secuencia que describa a una tarea en especifico

12-

> Además, se deberá interactuar con el módulo de Mi-RAM HQ ante las siguientes situaciones:
> Informar cada movimiento dentro de la nave.
> Luego de realizar cada tarea, solicitar la próxima.

¿Hay alguna prioridad sobre que tarea debería realizar cada uno o la memoria debería llevar un registro de cual fue la última tarea asignada para asignar la siguiente? O capaz la memoria debería, por ejemplo, en el caso de segmentación, cambiar la base del inicio del segmento de tareas para liberar lo que correspondía a la tarea realizada anteriormente?

Gracias!

**Comment by gastoncastineira** [comment]
1- No vamos a correr múltiples discordiadores (aunque gracias por la idea)
2- El Tripulante no es un módulo como tal, sino que son sub-módulos (léase hilos) del discordiador
3- La señas la vamos a estar enviando nosotros desde fuera del programa
4- Creo que es indistinto, porque durante un sabotaje de todas formas todos los tripulantes están bloqueados, por lo que no hay nadie haciendo nada contra el FS
5- Sí a ambos, pero recordá que todos los tripulantes se tienen que dirigir al punto de sabotaje
6- Vas a necesitar algún mínimo para poder hacer la relación entre el tripulante ejecutando en el discordiador y su data en Mi-RAM. Qué es ese algo es decisión tuya, en lo posible una decisión sustentada por la teoría
8- Creo que te respondiste la 7 y la 8 solo
9- No sé a qué le llamás "directamente", pero los archivos de configuración no van almacenados en el i-mongo-store
10- Vamos a hacer una errata al respecto. Falta un puntero al PCB en el TCB.
11- Tema de diseño a decisión de ustedes que tendrán que explicarnos y defendernos en el coloquio :)
12- No a todo, tampoco me queda claro de dónde sale la idea (que dicho sea de paso, no te funcionaría por razones que no importan ahora). El TCB mantiene un índice para saber cual es la siguiente. ¿Le encontrás algún problema a esto?

**Comment by matiasimartin** [comment]
> 5- Sí a ambos, pero recordá que todos los tripulantes se tienen que dirigir al punto de sabotaje

Pregunta, si todos tienen que moverse al punto de sabotaje al mismo tiempo, entonces obviamente el que este mas cerca llega primero, es ese el que resuelve el sabotaje y los demás se bloquean en la posición que quedaron?

> Por último, el sistema deberá buscar al tripulante más cercano a la ubicación del sabotaje y planificarlo para que se mueva a dicha ubicación y resuelva el sabotaje...

Como dice que solo planifica al mas cercano me surgió esa confusión. A parte, si fuera que todos se mueven al mismo tiempo y como pueden haber dos o mas ejecutando simultáneamente, que pasa si llegan dos al mismo tiempo?

**Comment by RaniAgus** [comment]
¡Buenas! Corrijo la respuesta en cuanto a esa parte: efectivamente, el enunciado dice que solo el tripulante más cercano se debe mover hacia el sabotaje, consideren eso. Saludos.

**Comment by gastoncastineira** [comment]
![image](https://user-images.githubusercontent.com/28161802/115979816-80b84180-a55e-11eb-8f40-05da08c5708c.png)

Una tasa de acierto del 92% no está tan mal, ¿no? :P

**Comment by julchat** [comment]
> 12- No a todo, tampoco me queda claro de dónde sale la idea (que dicho sea de paso, no te funcionaría por razones que no importan ahora). El TCB mantiene un índice para saber cual es la siguiente. ¿Le encontrás algún problema a esto?

Claro, pero ¿cuándo cambia la tarea próxima que el TCB describe? ¿Al asignarle una al tripulante, o cuando este la finaliza? ¿Estaría permitido que la "estructura" de tarea en memoria incluya 4 bytes describiendo si está terminada o no?

**Comment by gastoncastineira** [comment]
¿Te cambia algo realmente el orden? El resultado esperado es el mismo en cualquiera de los dos casos, pero si necesitás para una de esas alternativas agregar campos a la estructura, eso es algo que definitivamente no está permitido para este TP

**Comment by RaniAgus** [comment]
Sobre esto:

> ¿Estaría permitido que la "estructura" de tarea en memoria incluya 4 bytes describiendo si está terminada o no?

Tené en cuenta que el que un tripulante haya terminado una tarea no significa que haya que "marcarla" para que los otros no deban hacerla. Por eso con un "puntero al siguiente" alcanza y sobra.

Es como que vos abras varios hilos en la misma función y éstos se repartan entre sí las instrucciones a ejecutar. Esto no es así (y no querrías que lo fuera :P)

Saludos.

**Comment by heinHertz** [comment]
1. Hola que es "nosotros" en la respuesta 3 
```
3- La señas la vamos a estar enviando nosotros desde fuera del programa
```

el usuario ?   directo al modulo imongo  por consola?

**Comment by RaniAgus** [comment]
Sobre el manejo de señales y cómo se lanzan, no hay mucho misterio, creo que lo que se menciona en #1800 les puede servir. ¡Saludos!

**Comment by julchat** [comment]
> Tené en cuenta que el que un tripulante haya terminado una tarea no significa que haya que "marcarla" para que los otros no deban hacerla. Por eso con un "puntero al siguiente" alcanza y sobra.
 Aaah entonces todos los tripulantes de la misma patota deben realizar las mismas tareas? Había entendido mal

**Comment by ncoen97** [comment]
Confirmo, todos los tripulantes de la misma patota deben realizar las mismas tareas 👍

**Comment by julchat** [comment]
Buenisimo! Todo claro! Muchas gracias a todos por participar ;)!
