### ISSUE TITLE
No me deja crear un archivo .c

### ISSUE THREAD

**Issue by ezecastiglione18** [sisoputnfrba/foro#2039]
Buenas! Probablemente vaya a hacer una pregunta ya respondida en otro issue, pero no encuentro ni eso ni algun apunte en utnso. 

El problema basicamente es que en Eclipse, una vez clonado el repo del tp, quiero crear las carpetas y los archivos .c correspondientes. El tema es que cuando quiero crear un archivo .c en una determinada carpeta me aparece esto: 

/home/utnso/tp-2021-(...)-mongoStore overlaps the location of another project: 'mongoStore.c'

El tema es que yo ya habia creado un mongoStore.c, pero como lo cree mal lo tuve que borrar. Y para crear otro me tira eso, como se podria solucionar?

**Comment by mgarciaisaia** [comment]
Abrite una consola, hacé `cd` hasta el directorio de tu repo (`cd tp-2021....`), y ejecutá `tree -a -I .git` para ver bien cómo te quedaron los directorios y proyectos.

Hay que ver si lo que tenés que hacer es borrar un `.project` (y/o un `.cproject`) viejo, o qué onda.

**Comment by ezecastiglione18** [comment]
El tema es que no te puedo mandar screen ni copiar codigo porque tuve problema con las Guest Additions... No sabria bien que hacer. Pero por lo que puedo leer de la consola es que no hay ningun archivo en la carpeta /mongoStore

**Comment by mgarciaisaia** [comment]
Desde adentro de la VM podés pegar el archivo en pastebin.com o algún sitio similar, estimo. O directamente iniciar sesión en Github y postear desde ahí. O copiarte el archivo a tu host via una carpeta compartida por red.

Bah, ¿probaste alguna opción para subir ese listado?

**Comment by ezecastiglione18** [comment]
Sisi, estuve intentando de todo... Vos decis que si borro la VM y creo todo de vuelta no tendria problema?

**Comment by ezecastiglione18** [comment]
No me preguntes como, pero lo hice jeje. Borre el directorio que habia clonado y puse la opcion para borrar tambien en disco. Volvi a crear el archivo .c y me lo acepto

Gracias por la ayuda igual!
