### ISSUE TITLE
Vm Lenta al correr ecplipse

### ISSUE THREAD

**Issue by gastonharari** [sisoputnfrba/foro#2040]
Hola, como estan?

Al usar ecplise, la maquina virutal se vuelve muy lenta, no reconociendo clicks del mouse o teniendo mucho delay con el mismo.
Ademas no me llega a mostrar las "ayudas" que muestran el prototipo de una funcion al momento de pararme sobre una funcion.
Intente subirle la cantidad de ram(de 1 a 2, de 2 a 4 y de 4 a 8GB de Ram) y vi que lo maximo que me consumia eran 3.80 GB (segun mi SO real).

### 🔎 Búsqueda en foros

No se si esta relacionado con este [Issue](https://github.com/sisoputnfrba/foro/issues/2036) pero no le estoy encontrando solucion

### 📦 Especificaciones de la VM
- Versión de VirtualBox: 6.1.18
- Memoria RAM asignada: 4GB/8GB
- Procesadores: 2
- Memoria de Video Asignada: 64MB
- Scale factor: 2.0
- Graphic Controller: VMSVGA

### 🖥️ Especificaciones del host
- Sistema Operativo y versión: macOS Big Sur 11.2.3
- Memoria RAM: 16GB
- Procesador: Intel core i7

No se por donde mas poder avazar para que quede bien configurada, me podrian ayudar con esto?

Muchas gracias de antemano!

**Comment by Nachiten** [comment]
Buenas! Como estas?
Bien, vamos por lo primero y mas importante.

Dado que las VMs que estamos utilizando por ahora son de 32 bits, te digo que no podes asignarles mas de 4GB dado que no lo soporta (no lo va a reconocer). Lo que siempre recomendamos de igual manera dado que son muy livianas es asignarle 2GB. Yo tengo 16GB en mi pc sin embargo con asignarle solo 2 a la VM me anda de maravilla.

Siguiendo con lo que le asignaste a tu VM. Te recomiendo que le asignes un solo Core dado que es suficiente (no debería haber problema en asignarle 2). Y luego, lo mas importante es que le asignes el máximo permitido de memoria de video (128mb) dado que esto debería hacer que funcione mas fluida en general.

Probate todas esas recomendaciones que te di y contanos como vas, saludos!

**Comment by Nachiten** [comment]
Buenas! @gastonharari . Pudiste resolver tu temita? Si es así avisa como fue y vemos si podemos cerrar. Gracias!

**Comment by gastonharari** [comment]
Hola, como estas?

Muchas gracias por tu respuesta.
Mejoro pero tampoco mucho, sigue pasando que cuando corro el eclipse, le cuesta hacer tareas basicas, como por ejemplo seleccionar unas lineas de codigo o moverse dentro de un archivo
Pero mejoro en lineas generales, se pueden previzualizar las las "ayudas" cuando me paro sobre una funcion

**Comment by Nachiten** [comment]
> Hola, como estas?
> 
> Muchas gracias por tu respuesta.
> Mejoro pero tampoco mucho, sigue pasando que cuando corro el eclipse, le cuesta hacer tareas basicas, como por ejemplo seleccionar unas lineas de codigo o moverse dentro de un archivo
> Pero mejoro en lineas generales, se pueden previzualizar las las "ayudas" cuando me paro sobre una funcion

Es raro, a mi me anda bien y practicamente no tengo lag (a veces un poco).

No habrá alguna otra configuracion rara que pusiste?

Si ya quedó resuelto avisá asi cerramos el issue, gracias!

**Comment by gastonharari** [comment]
Creo que no veo nada raro en las configuraciones, ves algo raro? estas son:

![image](https://user-images.githubusercontent.com/22179865/116760341-0ae32880-a9eb-11eb-84b1-abff1dddef97.png)

**Comment by Nachiten** [comment]
> Creo que no veo nada raro en las configuraciones, ves algo raro? estas son:
> 
> ![image](https://user-images.githubusercontent.com/22179865/116760341-0ae32880-a9eb-11eb-84b1-abff1dddef97.png)
> 

No creo! El adaptador de video (VMSVGA) que estás utilizando, es el que te recomienda Oracle VM usar? 
Te fijas esto editando la configuración. Si abajo a la izquierda del cuadro donde editas la config aparce un cartelito de warning diciendo "configuracion invalida detectada" significa q es otro (y te va a decir cual es), si no aparece nada, entonces es ese.

Es lo unico que se me ocurre decirte, fijate y avisá que onda!

**Comment by iago64** [comment]
@gastonharari pudiste probar lo que comento @Nachiten?

**Comment by gastonharari** [comment]
Si, pude realizarlo y mejoro.

Muchas gracias por su ayuda!
