### ISSUE TITLE
Duda Enunciado: Listar Tripulantes y comandos por consola

### ISSUE THREAD

**Issue by DamoFernandez** [sisoputnfrba/foro#2041]
Buenas encarando el TP nos encontramos con algunas situaciones y decidimos consultar que approach tomar

Duda 1:

Cuando ingresamos un comando por consola con varios " " (espacios), ya sea entre los parametros o al comienzo de la linea deberiamos ejecutar igualmente dichas acciones?

Ejemplos:

```
INICIAR_PATOTA 5            /home/utnso/tareas/tareasPatota5.txt              1|1               3|4
              INICIAR_PATOTA 5 /home/utnso/tareas/tareasPatota5.txt  1|1         3|4
```

---

Duda 2:

> Iniciar patota 
> Recibirá como parámetro la cantidad de tripulantes que tendrá la patota, un archivo de tareas que deberán ejecutar los tripulantes de la patota (se indica el formato en la siguiente sección)  y una lista de posiciones iniciales de los tripulantes. Por defecto, si no se especifica la posición de la totalidad de los tripulantes, se asume que los restantes inician en 0|0.
>
> Ejemplo,
> INICIAR_PATOTA 5 /home/utnso/tareas/tareasPatota5.txt 1|1 3|4 

Si yo ejecuto el siguiente comando, el cual contiene mas posiciones que cantidad de tripulares
`INICIAR_PATOTA 5 /home/utnso/tareas/tareasPatota5.txt 1|1 2|2 3|3 4|4 5|5 6|6`

Llegado este comando, que deberíamos hacer?
1. Indicar que el comando es invalido y no hacer nada
2. Indicar que el comando es invalido ya que hay mas posiciones que tripulantes, y no hacer nada
3. Iniciar igualmente a los tripulantes y solo tomar las posiciones necesarias (en este ejemplo seria hasta la 5|5 y se descartaría las 6|6)
4. Otro approach

Duda 3:

> Iniciar patota 
> Recibirá como parámetro la cantidad de tripulantes que tendrá la patota, un archivo de tareas que deberán ejecutar los tripulantes de la patota (se indica el formato en la siguiente sección)  y una lista de posiciones iniciales de los tripulantes. Por defecto, si no se especifica la posición de la totalidad de los tripulantes, se asume que los restantes inician en 0|0.
>
> Ejemplo,
> INICIAR_PATOTA 5 /home/utnso/tareas/tareasPatota5.txt 1|1 3|4 

Si yo ejecuto el siguiente comando, pero el archivo "tareasPatota5.txt" no existe
`INICIAR_PATOTA 5 /home/utnso/tareas/tareasPatota5.txt 1|1 2|2 `

Llegado este comando, que deberíamos hacer?
1. Indicar que el comando es invalido y no hacer nada
2. Indicar que el comando es invalido ya que el archivo no existe, y no hacer nada
3. Otro approach

Muchas gracias!

Saludos.

**Comment by RaniAgus** [comment]
¡Buenas! 

No hace falta considerar inputs inconsistentes tanto en la consola como en los config. Como dijo Dami en #1892, si encuentran algo sin mucho sentido en alguna prueba es más probable que sea un dedazo nuestro que algo que tengan que considerar. 

Si ustedes quieren por su cuenta agregar alguno de los chequeos que mencionaste para evitar alguna inconsistencia al pifiar una tecla lo pueden hacer, pero sepan que no es estrictamente necesario y no es algo en lo que haya que dedicarle demasiado tiempo. 

Saludos

**Comment by ncoen97** [comment]
Buenas, quería agregar que (por experiencia propia), les recomiendo que tengan chequeos de los datos ingresados. Sobre todo porque si por error durante una prueba escriben algo mal, pueden llegar a pensar que tienen algún error en su código y gastarse tiempo buscando el por qué; mientras que si tienen un log que les dice "Pifiaste el comando" y se finaliza el programa, ya saben cual fue el problema. Igualmente como dice Agus, no es prioridad ni tampoco es la idea que se maten chequeando todas las posibilidades.
Saludos!

**Comment by DamoFernandez** [comment]
Perfecto, muchas gracias!
