### ISSUE TITLE
Problemas con la guest addition.

### ISSUE THREAD

**Issue by velonna** [sisoputnfrba/foro#2042]
### 📦 Especificaciones de la VM
- Versión de VirtualBox: 
- Memoria RAM asignada:

### 🖥️ Especificaciones del host
- Sistema Operativo y versión:
- Memoria RAM:
- Procesador:

**Comment by velonna** [comment]
Tenia  problemas al crear la mv.  sucede que la tenia andando  bien hasta hace tres semanas, terminando un curso  instale doker. Cuando  quiero  empezar con el tp, empieza todo roto. Nada di vueltas y  encontre  ayuda  en la web y luego aca,  No sabia  que  el docker me  bloqueaba  la maqiuna virtual.
Bueno funciona la maquina  virtual pero  no puedo agregar las  GAdd. tengo el siguiente  mensaje  cuand o intento  motar otro cd:
[](url)

**Comment by ncoen97** [comment]
Buenas @velonna!
Te pido que si tenías algún problema que lograste solucionar por tu cuenta, igualmente comentes cuál era y cómo lo solucionaste, así otr@s alumn@s pueden tener la solución si les pasa algo similar.
Saludos!
