### ISSUE TITLE
Consulta sobre la conexion

### ISSUE THREAD

**Issue by ezecastiglione18** [sisoputnfrba/foro#2043]
Buenas! Con mi grupo tenemos una duda sobre el File System. Como todavia no lo vimos en la cursada, no sabemos muy bien que hacer. Y cuando lo preguntamos en el sabado de soporte nos dijeron que podiamos ir creando el servidor y que el cliente mande mensajes. 

Nuestra duda es que en el TP0 hay una carpeta que es Servidor. Tenemos que "copiar" el codigo que esta en esa carpeta y despues lo guardamos dentro de la carpeta que creamos para todo relacionado al Mongo Store? Porque tenemos dudas sobre que hacer y como hacerlo. Saludos!

EDIT: me olvide de aclarar. Pregunto esto porque para el hito 1, uno de los objetivos dice: "Comenzar el desarrollo del módulo discordiador como cliente de Mi-RAM HQ y de i-Mongo-Store" y pense yo que la carpeta del i-Mongo-Store contenia todo lo relacionado con la creacion del servidor

**Comment by RaniAgus** [comment]
¡Buenas! 

Les recomiendo para empezar esta [guía de Introducción a IPC y Sockets](https://docs.google.com/document/d/11CH_a-Uw5CRXWgscKvrUuGQsiaqy_hE3_njJ4YXv5cI/edit) que se encuentra linkeada desde la [sección de guías del blog](https://www.utnso.com.ar/recursos/guias/) para familiarizarse con el concepto de Cliente y Servidor que les será útil para orientarse en el TP.

Luego, pueden echarle un vistazo al [repo ejemplo de paso de mensajes Cliente-Servidor](https://github.com/sisoputnfrba/so-test-sockets) y al [post con una compilación de charlas de años anteriores](https://www.utnso.com.ar/1c2020-recopilando-otras-charlas/) que les pueden servir de gran ayuda. 

Saludos.

**Comment by ezecastiglione18** [comment]
Consulta, se puede usar el repo de ejemplo para el servidor o vamos a tener que hacer de 0? Porque ese es mi punto, no se directamente como hacerlo (ni que archivos usar, ni que codear). Ese es mi punto

**Comment by Nachiten** [comment]
> Consulta, se puede usar el repo de ejemplo para el servidor o vamos a tener que hacer de 0? Porque ese es mi punto, no se directamente como hacerlo (ni que archivos crear, ni que codear). Ese es mi punto

Buenas! Todo el TP0 es un punto de arranque para el TP en serio. No te va a servir copy pastear nada de ahí tal cual dado que estaría incompletísimo. Podes tomarlo como punto de partida para ir expandiéndolo, pero imposible que sirva por completo.

Si tienen demasiadas dudas pueden venir el sábado de soporte y tratamos de darles una mano. Pero traten de no venir con cero idea de nada porque va a ser muy difícil. Peguen una leída a las cosas que les pasó @RaniAgus y traten de hacerse una idea de las cosas.

Saludos!

**Comment by ezecastiglione18** [comment]
Pero hacia referencia al repo de ejemplo (https://github.com/sisoputnfrba/so-test-sockets), no al TP0. Obviamente que tenemos que configurar ciertas cosas entre todos (por ejemplo los protocolos), pero como para poder tener una base mas que nada para tener la conexion

Pd: puse "ese es mi punto" dos veces seguidas, mala mia jajaja

**Comment by Nachiten** [comment]
> Pero hacia referencia al repo de ejemplo (https://github.com/sisoputnfrba/so-test-sockets), no al TP0. Obviamente que tenemos que configurar ciertas cosas entre todos (por ejemplo los protocolos), pero como para poder tener una base mas que nada para tener la conexion
> 
> Pd: puse "ese es mi punto" dos veces seguidas, mala mia jajaja

Bien.

Bueno, sí es este un buen ejemplo para arrancar. Pero como bien te respondiste vos recién, ustedes tienen que poner el laburo para expandirlo desde ahí y llegar a cumplir con los requerimientos de la consigna. Traten de ir entendiendo lo que van haciendo y no hacer cosas porque sí.

Suerte!!

**Comment by ezecastiglione18** [comment]
Dale, veo que puedo hacer y el sabado hay soporte normal? Pregunto porque como es feriado, puede no haber

**Comment by Nachiten** [comment]
> Dale, veo que puedo hacer y el sabado hay soporte normal? Pregunto porque como es feriado, puede no haber
> 
> Ah, una consulta mas: vamos a tener que crear una conexión al servidor por modulo? O con generarlo una sola vez y que después cada modulo lo use cuando corresponda ya esta?

No, no hay soporte este sábado oficialmente. Disculpá que creo me expresé mal si te di a entender que si.
Igual estate atento a un posible anuncio de que (quizá) haya gente en el labo haciendolo. No es seguro.

**Comment by ezecastiglione18** [comment]
Dale, ahí lo cierro. Gracias chicos!
