### ISSUE TITLE
Rutas generación archivos - Eclipse

### ISSUE THREAD

**Issue by eguiggiaro** [sisoputnfrba/foro#2044]
Hola,

¿Cómo están?

Estamos usando para la estructura del proyecto, el template armado por @RaniAgus y todo iba perfecto hasta que quisimos generar el archivo de log, para el logger, usando las commons.

El problema es el siguiente:

- Si ejecutamos desde Eclipse, le ruta que toma es:
.
│  
└─── <project1>/
|     └─── src/
|     └─── makefile
└─── <staticLib>/
      └─── <staticLib>/
      └─── makefile
└─  ARCHIVO.LOG
 

- Si ejecutamos desde consola, le ruta que toma es:
.
│  
└─── <project1>/
|     └─── bin/
└───────── ARCHIVO.LOG 
|     └─── src/
|     └─── makefile
└─── <staticLib>/
      └─── <staticLib>/
      └─── makefile

Estuvimos investigando si desde Eclipse existe alguna configuración puntual que nos esté pisando el "app path" y de alguna manera setee la raíz desde el root del proyecto pero no estamos dando con la solución.

**NOTA**: estamos usando un make armado por nosotros, para poder ejecutar el make de cada proyecto, porque no entendíamos 100% cómo darle ejecutar desde Eclipse y que se llame al make de cada proyecto, sin usar el so-deploy.

```
all: 
	-cd discordiador && $(MAKE) all
	-cd miram && $(MAKE) all
	-cd store && $(MAKE) all
	-cd utils && $(MAKE) all

clean:
	-cd discordiador && $(MAKE) clean
	-cd miram && $(MAKE) clean
	-cd store && $(MAKE) clean
	-cd utils && $(MAKE) clean

```

Saludos!!

**Comment by RaniAgus** [comment]
¡Buenas!

1. Sobre su duda:

El archivo de log se genera en distintos paths porque el directorio desde el que se ejecuta es distinto: seguramente están generando el archivo de log desde un path relativo (lo cual no está mal), pero lo que ocurre es que desde consola muy probablemente estén haciendo:
```
cd <path_al repo>/<modulo>/bin
./<ejecutable>
```
Mientras que, desde Eclipse, lo que hace es ejecutar desde la carpeta que hayan importado como proyecto. En este caso sería como hacer:
```
cd <path_al_repo>
./<modulo>/<bin>/<ejecutable>
```
En consecuencia, como el log se genera en un path relativo a la carpeta desde la que se ejecuta, se está generando en distintos lados.

2. En cuanto al make y a cómo importar los proyectos:

Disculpen, les re debo un video o guía bien detallada explicando cómo importar los proyectos y configurarlos en cada IDE, pero estoy muy complicado de tiempos entre el laburo y las materias que estoy cursando. De todas formas, recién les armé una mini-guía en la wiki del repo explicándolo, justo en Eclipse es bastante simple: https://github.com/RaniAgus/utnso-project/wiki/Eclipse

Cualquier consulta que tengan sobre el template no duden en dejar un comentario en este thread #2007 así unificamos todas las dudas ahí.

¡Saludos!

**Comment by eguiggiaro** [comment]
Gracias por la mini guía!!! Super úitil!
