### ISSUE TITLE
[Enunciado] Creación de una tarea

### ISSUE THREAD

**Issue by SantiagoAspres** [sisoputnfrba/foro#2046]
### 📔 Cita del enunciado

> Iniciar patota 
> Recibirá como parámetro la cantidad de tripulantes que tendrá la patota, un archivo de tareas que deberán ejecutar los tripulantes de la patota (se indica el formato en la siguiente sección)  y una lista de posiciones iniciales de los tripulantes. Por defecto, si no se especifica la posición de la totalidad de los tripulantes, se asume que los restantes inician en 0|0.
> 
> Ejemplo,
> INICIAR_PATOTA 5 /home/utnso/tareas/tareasPatota5.txt 1|1 3|4 

> Tareas
> Las tareas que realizará un tripulante estarán determinadas en el archivo de tareas que obtendrá como parámetro al momento de recibir el mensaje INICIAR_PATOTA en la consola del discordiador. 
> Este archivo de tareas tendrá una sola tarea por línea y cada línea tendrá los siguientes parámetros separados por punto y coma (;)

### 💭 Dudas

Al decir que llega como parámetro el path con la tarea a ejecutar, estuvimos tratando de buscar en el enunciado donde, cuando y quién crea el archivo de tarea. En base a esto queríamos saber:

- /home/utnso/tareas/tareasPatota5.txt  Qué modulo se encarga de crear el archivo y armar el path? El archivo se crea por consola?
- tareasPatota5: el 5 seria el numero de identificación de la patota, o es la cantidad de integrantes? En caso de ser la cantidad de integrantes habría inconsistencia ya que puede haber varias patotas con la misma cantidad de integrantes.

Saludos.

**Comment by gastoncastineira** [comment]
> /home/utnso/tareas/tareasPatota5.txt Qué modulo se encarga de crear el archivo y armar el path? El archivo se crea por consola?

Ninguno. Lo hacemos nosotros, los usuarios, con nuestro editor de texto favorito

> tareasPatota5: el 5 seria el numero de identificación de la patota, o es la cantidad de integrantes? En caso de ser la cantidad de integrantes habría inconsistencia ya que puede haber varias patotas con la misma cantidad de integrantes.

tareasPatota5 es el nombre del archivo :p 
Si le puse ese nombre es porque probablemente sea la quinta patota que voy a levantar, pero no pretendo que el sistema (léase, el TP) me saque ese número y lo asigne como pid, ni que sea la cantidad de tripulantes que tenga la patota

**Comment by SantiagoAspres** [comment]
y entonces en Listar tripulantes como se el numero de patota a la que pertenecen para mostrar en el output?

**Comment by gastoncastineira** [comment]
Como dije, sé que es la quinta patota que voy a levantar, con lo cual sé que su ID va a ser el 5.

Igual entiendo el punto. Vamos a revisar si vale la pena hacer alguna aclaración sobre el tema en una futura errata

**Comment by SantiagoAspres** [comment]
Buenisimo, muchas gracias. Abrazo.
