### ISSUE TITLE
Inscripción al repositorio del TP en GIT-HUB

### ISSUE THREAD

**Issue by Brunolombardozzi** [sisoputnfrba/foro#2047]
Buenas! Pasaron ya casi dos semanas que me anote en el sistema de inscripciones con mi grupo, pero tdvía no puedo encontrar el repositorio del tp ya que me tira el erorr 404 Page not found, buscando un poco, pude encontrar que ese error seguramente lo tire por que no tengo permiso para poder verlo. Quisiera saber que tengo que hacer.
Muchas gracias! :)

**Comment by mgarciaisaia** [comment]
Hola Bruno.

Cuando venció la invitación original a la organización en Github, venció también la invitación al Team de tu grupo.

Ahí te agregué a mano; ya deberías tener acceso al repo.

Avisame si no.

**Comment by Brunolombardozzi** [comment]
Listo, ya lo puedo ver. Muchas gracias @mgarciaisaia ! Saludos.
