### ISSUE TITLE
Consulta  patota-tripulante y administracion de tareas entrada y salida.

### ISSUE THREAD

**Issue by andresbulgheroni** [sisoputnfrba/foro#2048]
1-cada tripulante tiene distintas tareas dependiendo de la patota a la que pertenece? ¿Para que sirve saber a que patota pertenece un tripulante?

2-ENUNCIADO:" Administración de las entrada/salida
Dentro de las tareas que pueda ejecutar un tripulante, habrá algunas que requieren de un acceso al módulo de File System, y lo que estas harán será bloquear al tripulante a la espera de que se concrete la tarea en cuestión. 
Para poder darle un control más claro a dicho cambio de estado, este vendrá dado como un parámetro de dicha tarea (lo veremos más adelante en el submódulo tripulante). Por lo tanto, tendrá que considerarse que, a fines prácticos, hay dos tipos de colas de bloqueados: uno que es para las tareas de Entrada/Salida y otro para los casos de los sabotajes o emergencias."

¿Cómo reconozco si es una tarea de entrada y salida?

ya que la tarea dice: Duración de la tarea (expresada en ciclos de CPU; en caso de que sea una tarea de Entrada Salida, este tiempo deberá transcurrir en la cola de bloqueados)

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va?
1. Respondo al revés: la patota del tripulante serviría para saber qué tareas tiene que hacer (es uno de los parámetros de INICIAR_PATOTA), por lo que la primera pregunta creo que se responde sola :P
2. Vamos a hacer una revisión de las tareas para la próxima errata. Como bien mencionás, ahora mismo no es posible distinguir si son de entrada/salida o no.

Saludos

**Comment by karengrams** [comment]
¡Buenas buenas @andresbulgheroni! 

¿Cómo va? ¿Quedo resuelta tu duda? ¿Podemos cerrar el issue? 

¡Saludos! 😸
