### ISSUE TITLE
No pushea correctamente desde la VM

### ISSUE THREAD

**Issue by ezecastiglione18** [sisoputnfrba/foro#2049]
Buenas! Recien estuve agregando unas carpetas al tp para que este mas organizado. Cuando pusheo, veo que solamente una carpeta sola se subio correctamente. Las otras dos no estan en nuestro repo. Alguna idea de como se puede solucionar esto?

**Comment by iago64** [comment]
Buenas! como va?

Eso es porque básicamente git no pushea directorios, solo pushea archivos, con lo cual, si no tenes archivos adentro de las carpetas, no las vas a ver en el repo.

Saludos.-

**Comment by ezecastiglione18** [comment]
Puede ser por eso jajajaj, la realidad es que antes con Windows podia hacer eso. No se si es un tema de Linux pero bueno

Gracias y perdon!
