### ISSUE TITLE
Dudas sobre conexiones y referentes a enunciado

### ISSUE THREAD

**Issue by LeoMorsella** [sisoputnfrba/foro#2050]
Hola, leyendo el enunciado y viendo sobre todo el Hito 1 nos surgieron alguna dudas:
Nosotros para empezar tomamos el TP0 a modo de modelo con la idea de reutilizar el código para luego adaptarlo a las conexiones requeridas del TP, ahora bien nuestra duda es si justamente encaramos correctamente tomando como modelo el TP0, ya que a su vez encontramos una serie de videos (https://www.youtube.com/watch?v=87gwfsJ_83o) los cuales nos guían en la creación de servidor y cliente. 

Inicialmente seria conveniente que en vez de reutilizar el código del TP0 utilicemos lo explicado de estos videos como guía para generar los módulos de servidor y cliente sobre el tp?

Ahora a continuación de esta duda sobre las conexiones, nos surgieron algunas dudas de enunciado las cuales queremos saber si entendimos de forma correcta:

1. El modulo discordiador tendrá comportamiento de cliente, mientras que Memoria y File System tendrán comportamiento de Servidor específicamente?  o todos los módulos podrán actuar tanto como cliente como servidor teniendo que plantear una situación de cambio de rol durante la ejecución?

2. El servidor debe de estar preparado para recibir varios clientes? o solo recibirá de a un cliente? (esto basado en los videos de tutorial de Socket para generar servidores y clientes referidos a la duda inicial del issue)
 
3. Tomando el punto anterior. ¿Es valido que usemos dichos videos (adjuntamos link mas arriba) para la creación del servidor y cliente para el TP y generar las conexiones o que material podrías utilizar como guía? para justamente generar estas conexiones?

Desde ya muchísimas gracias

**Comment by Nachiten** [comment]
> Hola, leyendo el enunciado y viendo sobre todo el Hito 1 nos surgieron alguna dudas:
> Nosotros para empezar tomamos el TP0 a modo de modelo con la idea de reutilizar el código para luego adaptarlo a las conexiones requeridas del TP, ahora bien nuestra duda es si justamente encaramos correctamente tomando como modelo el TP0, ya que a su vez encontramos una serie de videos (https://www.youtube.com/watch?v=87gwfsJ_83o) los cuales nos guían en la creación de servidor y cliente.
> 
> Inicialmente seria conveniente que en vez de reutilizar el código del TP0 utilicemos lo explicado de estos videos como guía para generar los módulos de servidor y cliente sobre el tp?
> 
> Ahora a continuación de esta duda sobre las conexiones, nos surgieron algunas dudas de enunciado las cuales queremos saber si entendimos de forma correcta:
> 
> 1. El modulo discordiador tendrá comportamiento de cliente, mientras que Memoria y File System tendrán comportamiento de Servidor específicamente?  o todos los módulos podrán actuar tanto como cliente como servidor teniendo que plantear una situación de cambio de rol durante la ejecución?
> 2. El servidor debe de estar preparado para recibir varios clientes? o solo recibirá de a un cliente? (esto basado en los videos de tutorial de Socket para generar servidores y clientes referidos a la duda inicial del issue)
> 3. Tomando el punto anterior. ¿Es valido que usemos dichos videos (adjuntamos link mas arriba) para la creación del servidor y cliente para el TP y generar las conexiones o que material podrías utilizar como guía? para justamente generar estas conexiones?
> 
> Desde ya muchísimas gracias

Buenas, como estas? Vamos a ir de a poco respondiendo todo.

Sobre tu primer pregunta:

> Inicialmente seria conveniente que en vez de reutilizar el código del TP0 utilicemos lo explicado de estos videos como guía para generar los módulos de servidor y cliente sobre el tp?

La respuesta seria ni. En otras palabras, es decisión de ustedes como encarar este tipo de cosas. Y no hay una respuesta definitiva o mejor. Mientras logren cumplir con la consigna respecto al tema conexiones (y a todo el resto obviamente) estará bien. Lo mas recomendable siempre es tener la mayor cantidad de información y entendimiento posible sobre el tema. Dado que según mi experiencia las conexiones es lo que muchas veces explota y deja un TP imposible de ser aprobado, por mas que todos los módulos funcionen excelente por dentro.

Seguimos:

> El modulo discordiador tendrá comportamiento de cliente, mientras que Memoria y File System tendrán comportamiento de Servidor específicamente? o todos los módulos podrán actuar tanto como cliente como servidor teniendo que plantear una situación de cambio de rol durante la ejecución?

Perdón si suena como que no tengo ganas de darte la respuesta, es solo que está bueno que puedan pensarlo ustedes. Para razonar si algo es cliente o servidor (si, puede ser ambos también) tenés que pensar lo siguiente.
- Yo como servidor, me quedo en [idle](https://dictionary.cambridge.org/es/diccionario/ingles/idle) esperando a que alguien se me conecte y no hago nada hasta que eso pase, luego proceso lo que necesite y obviamente respondo. No muero nunca y siempre espero conexiones nuevas.
- Mientas que yo como cliente, sé exactamente a donde conectarme y qué necesito enviarle al servidor al que me conecto. Luego espero su respuesta y cuando tenga lo que necesito me desconecto (y depende del caso muero o no).

Espero que estos consejos te sean mas que suficiente para determinar cuando quien es uno, el otro, o ambos.

> El servidor debe de estar preparado para recibir varios clientes? o solo recibirá de a un cliente? (esto basado en los videos de tutorial de Socket para generar servidores y clientes referidos a la duda inicial del issue)

Según lo que tenemos pensado, solo existirá una instancia tanto de discordiador, como de memoria, como de FS. Pero, podrías llegar a tomar los distintos hilos (tripulantes) como conexiones distintos quizá. No creo que sea algo conveniente pero lo veo posible.

> Tomando el punto anterior. ¿Es valido que usemos dichos videos (adjuntamos link mas arriba) para la creación del servidor y cliente para el TP y generar las conexiones o que material podrías utilizar como guía? para justamente generar estas conexiones?

Si, es valido. Explayándome un poco mas vuelvo a lo que dije antes. La manera que tengan ustedes de encararlo es decisión de ustedes. No es sano que copy pasteen sin tener ni idea lo que hacen (sobre todo en conexiones que es complejo). Van a tener que juntarse (recomiendo un finde con tiempo en Discord) y armar entre todos un buen protocolo que les sirva para enviar/recibir todos los mensajes existentes del sistema entre todos los módulos donde corresponda cada uno.

Espero con esto haber respondido tus dudas, no dudes en repreguntar lo que necesites.

Saludos!! :D

**Comment by LeoMorsella** [comment]
Genial, en ese caso guiándonos con los videos y apuntes vamos a encarar la conexión.
Muchísimas gracias por la orientación.

**Comment by Nachiten** [comment]
> Genial, en ese caso guiándonos con los videos y apuntes vamos a encarar la conexión.
> Muchísimas gracias por la orientación.
> 

No hay problema, si tu duda quedó resuelta te pido si podemos cerrar el issue. Gracias!
