### ISSUE TITLE
Problema de eclipse no encuentra el archivo config

### ISSUE THREAD

**Issue by Franpanozzo** [sisoputnfrba/foro#2051]
Buenas, estaria teniendo un problema con el eclipse ya que no me encuentra el archivo .config en ningun proyecto, me pasa exactamente lo que tiene este issue #1734 , con los mismos mensajes de error, pero en este issue no dieron una solucion especifica. Dijieron algo de que habia caracteres no reconocibles en el .config, Pero yo al correr vim y cat en el .config no veo esos caracteres la verdad. Por las fechas que veo de los comentarios veo que tardo y eso me preocupa. Si me pueden dar una mano buenisimo! Saludos!

**Comment by Nachiten** [comment]
> Buenas, estaria teniendo un problema con el eclipse ya que no me encuentra el archivo .config en ningun proyecto, me pasa exactamente lo que tiene este issue #1734 , con los mismos mensajes de error, pero en este issue no dieron una solucion especifica. Dijieron algo de que habia caracteres no reconocibles en el .config, Pero yo al correr vim y cat en el .config no veo esos caracteres la verdad. Por las fechas que veo de los comentarios veo que tardo y eso me preocupa. Si me pueden dar una mano buenisimo! Saludos!
> 
> 

Buenas!

Dos recomendaciones te dejo para que puedas resolver tu problema.

Primero, para evitar errores de la forma "no puedo abrir el archivo" por el path estar mal. Te recomiendo que uses un path absoluto. Para que sea absoluto dicho path debe empezar con "/" y contener todas las carpetas desde el root del filesystem hacia donde estará el proyecto. (Solo deben asegurarse de cargar el proyecto en las VMs durante la entrega exactamente en el mismo lugar donde lo esten teniendo ahora)
Entonces en vez de tener algo de la forma "../../carpeta1/carpeta2..." tendrian algo como "/home/utnso/Desktop/carpetaRepo/algo.config"

Luego, el segundo consejo es utlizar el comando "hexdump -C archivo.config" esto te dejará ver en hexadecimal representado cada caracter que tiene este archivo. Donde ver 0 significaria que no hay nada, y cualquier otro valor significa que algun caracter hay ahí. Fijate como vas a ver todo el decimal, y a la derecha un intento de representarlo en ASCII siempre que se pueda.

Espero que esto te sirva, avisa si podes resolver.

Saludos!!

**Comment by RaniAgus** [comment]
¡Buenas! Para poderte ayudar, ¿podrías darnos más contexto?
Necesitaría que copies y pegues el config que estás usando y el código que estaría rompiendo (no solo la línea exacta sino las que creas relevantes).
También, como extra, si podés correrlo con [Valgrind](https://docs.google.com/document/d/1flOJ2P2g9UGVRiruuA4OCF6nucbN_BWVI0WDlYTJNf4/edit) con la opción `--log-file="valgrind.log"` y dejarnos el log que genera sería un golazo 🙏🏻

**Comment by RaniAgus** [comment]
¡Me olvidaba! Otro consejo, si querés saber un poco más sobre cómo funcionan las rutas relativas y absolutas (y no solo quedarte con el "usá absolutos por las dudas") te recomiendo este post: [Rutas Argentinas](https://mgarciaisaia.github.io/tutorial-c/blog/2015/04/23/rutas-argentinas/).

**Comment by Franpanozzo** [comment]
Lo pude solucionar!! Alfinal poniendo la ruta absoluta anda perfecto. Muchas gracias!! muy buen post el de rutas argentinas, ahora entendi mas como funciona, la duda que me surge ahora es si todos los integrantes vamos a tener que tener el mismo path para el proyecto asi coincide con el path absoluto. O se podria solucionar con el relativo poniendo como ruta Debug/algo.congif ??

**Comment by RaniAgus** [comment]
¡Buenísimo! 
En este caso, la solución "fácil" sería la que vos mencionás: que trabajen todos en la misma carpeta.
Por otro lado, la solución "elegante" sería aplicar el concepto de cwd (Current Working Directory) y trabajar con rutas relativas. A mí personalmente me gusta más porque les da más de libertad. Para tener en cuenta: en Eclipse el cwd por default es siempre la carpeta del proyecto que importaron (en criollo, donde está el `.project` y `.cproject`).

También, otra cosa a tener en cuenta es que los archivos que genera Eclipse (`.cproject`, `.project`, `/.settings/` ...) trabajan con paths absolutos, entonces es muy común que vengan grupos diciendo que se "rompieron" al pasárselos entre ellos ya que no están trabajando todos en la misma carpeta.
En ese caso, también, la solución "fácil" es trabajar todos en la misma carpeta; y la solución "elegante" sería eliminarlos del repo y tener un `.gitignore` que ignore cuando cada integrante se cree los suyos con `New > C/C++ Project > Empty Project, etc`. De esta forma, cada uno labura donde quiere y también el repo queda más "limpio" al tener solo los archivos fuente (que son lo importante, digamos).

**Comment by Nachiten** [comment]
Chicoss, antes que cierren te dejo el ultimo consejo relacionado @Franpanozzo .
Te recomiendo el [mario bash](https://mariobash.utnso.com.ar) es un lugar muy bueno para aprender a moverse por las rutas, y si mal no recuerdo te enseña rutas absolutas vs relativas.

Saludos! Y si no hay mas consultas no olvides cerrar el issue.

**Comment by Franpanozzo** [comment]
Joyaa, muchas gracias por los consejos genios!! Saludos!!
