### ISSUE TITLE
[I-Mongo-Store] Duda inicialización del File System "en limpio"

### ISSUE THREAD

**Issue by int0x80-sys** [sisoputnfrba/foro#2053]
Buenas.

Tenemos dudas sobre algo que se menciona en la inicialización del módulo I-Mongo-Store. El enunciado dice:

```
Al momento de inicializar el proceso se realizarán las siguientes operaciones:
1. Controlar si se va a trabajar con un File System (FS) limpio o si se debe recuperar el FS
existente.
2. En caso de tener que inicializar un FS limpio tendrá que generar todos los archivos de
bloques según indique la metadata.
3. Iniciar el servidor al cual se conectarán los tripulantes para comenzar a ejecutar
```
Nuestras dudas son:
1. Al pié de página se menciona que lo del punto 1 _... se hará verificando una serie de archivos que se detallan mas abajo._. Estos archivos creemos que serían el **SuperBloque** y el **Blocks.ims** ¿Estamos en lo correcto?

2. ¿Cual sería el archivo de _metadata_?

Saludos.

**Comment by Nachiten** [comment]
> Buenas.
> 
> Tenemos dudas sobre algo que se menciona en la inicialización del módulo I-Mongo-Store. El enunciado dice:
> 
> ```
> Al momento de inicializar el proceso se realizarán las siguientes operaciones:
> 1. Controlar si se va a trabajar con un File System (FS) limpio o si se debe recuperar el FS
> existente.
> 2. En caso de tener que inicializar un FS limpio tendrá que generar todos los archivos de
> bloques según indique la metadata.
> 3. Iniciar el servidor al cual se conectarán los tripulantes para comenzar a ejecutar
> ```
> 
> Nuestras dudas son:
> 
> 1. Al pié de página se menciona que lo del punto 1 _... se hará verificando una serie de archivos que se detallan mas abajo._. Estos archivos creemos que serían el **SuperBloque** y el **Blocks.ims** ¿Estamos en lo correcto?
> 2. ¿Cual sería el archivo de _metadata_?
> 
> Saludos.

Buenas! Vamos por partes.

> Al pié de página se menciona que lo del punto 1 ... se hará verificando una serie de archivos que se detallan mas abajo.. Estos archivos creemos que serían el SuperBloque y el Blocks.ims ¿Estamos en lo correcto?

Si, esos son dos buenos candidatos a archivos que si los checkeas podes asegurarte que tu FS exista o no de manera indiscutible. Luego debes decidir si creas todo de cero o usas algo existente.

> ¿Cual sería el archivo de metadata?

**Comment by Nachiten** [comment]
Sigo, perdon que el mensaje anterior se envio incompleto:
> ¿Cual sería el archivo de metadata?
La metadata (**del filesystem, no de un archivo**) es la siguiente (cito la consigna):

> Block_size: Indica el tamaño en bytes de cada bloque, este dato será de tipo uint32_t
> Blocks: Indica la cantidad de bloques del File System, este dato será de tipo uint32_t

Por lo tanto el procedimiento para crear un filesystem nuevo seria:
1 - Abro el SuperBloque (debe existir y no contener errores)
2 - Leo block_size y blocks
3 - Inicializo el archivo Blocks como corresponde y como dice la consigna.

Espero con esto haberte ayudado, saludos!

**Comment by int0x80-sys** [comment]
Buenas de nuevo.

Gracias por contestar tan rápido. Entonces, por lo que me comentas tendría que existir siempre un archivo SuperBloque para poder generar el File System.

> Al pié de página se menciona que lo del punto 1 ... se hará verificando una serie de archivos que se detallan mas abajo.. Estos archivos creemos que serían el SuperBloque y el Blocks.ims ¿Estamos en lo correcto?

Por lo que no deberíamos chequear contra el SuperBloque, sino solamente deberíamos chequear el **Blocks.ims**. Si no existiera el SuperBloque, ni siquiera deberiamos inicializar el módulo supongo. ¿Verdad?

Gracias de nuevo y saludos.

**Comment by Nachiten** [comment]
> Buenas de nuevo.
> 
> Gracias por contestar tan rápido. Entonces, por lo que me comentas tendría que existir siempre un archivo SuperBloque para poder generar el File System.
> 
> > Al pié de página se menciona que lo del punto 1 ... se hará verificando una serie de archivos que se detallan mas abajo.. Estos archivos creemos que serían el SuperBloque y el Blocks.ims ¿Estamos en lo correcto?
> 
> Por lo que no deberíamos chequear contra el SuperBloque, sino solamente deberíamos chequear el **Blocks.ims**. Si no existiera el SuperBloque, ni siquiera deberiamos inicializar el módulo supongo. ¿Verdad?
> 
> Gracias de nuevo y saludos.

Si, basicamente si no tenes la metadata necesaria tiras un exit code -3 por ejeplo, procedo a no iniciar y listo.

Luego, la matadata no te sirve para saber si existe o no un FS es cierto tambien. Podes checkeae existencia de bitmap y/o de Blocks correcto.

Acordate que no se debe lidiar con info faltante ni inconsistente (en cuanto a la metadata por lo menos)

**Comment by int0x80-sys** [comment]
Buenas. Perfecto. Gracias por todas las respuestas.

Saludos 🚀
