### ISSUE TITLE
[Tareas] funcionamiento de DESCARTAR_BASURA y cuando se ejecuta el TIEMPO para las demás tareas.

### ISSUE THREAD

**Issue by julchat** [sisoputnfrba/foro#2054]
Leyendo el anexo de tareas del sistema, estaba lo siguiente
> Teniendo en cuenta que en nuestro archivo de tareas va a estar separado por punto y coma (;) los parámetros que reciban nuestras tareas van a estar en el primer elemento y van a estar separados por espacios.
> 
> TAREA PARAMETROS;POS X;POS Y;TIEMPO
> 
Donde, repasando lo leído en el módulo de discordiador, cada segundo transcurrido de movimiento hasta la posición X|Y es una acción de CPU, y el número indicado en TIEMPO se refiere a la cantidad de espera que se debe realizar para la tarea (ciclos de cpu tambien)

La primera duda surge con las tareas que utilizan el FileSystem, por ejemplo:

> Tarea | GENERAR_OXÍGENO
> -- | --
> Parámetros | CANTIDAD: Cantidad de Oxígeno a Generar (Número)
> Pasos | Verificar que exista un archivo llamado Oxigeno.ims en el i-Mongo-Store. Si existe saltar al paso. Si no existe el archivo, crearlo y asignarle el carácter de llenado O. Agregar tantos caracteres de llenado del archivo como indique el parámetro CANTIDAD
> Ejemplo | GENERAR_OXIGENO 12;2;3;5

Si un tripulante quisiera ejecutar una tarea, lo primero que debe hacer es moverse hacia la posición, donde cada movimiento implica mandar un mensaje al fs para que pueda escribir un registro en la bitácora.
Ahora bien, si la tarea implica un bloqueo de FS, ¿cuando se ejecuta la "espera"?
1) La que SEGURO no es: desde que arranco a ejecutar la tarea y sigo contando si me voy a bloqueado
2) Ejecuto la espera antes de bloquearme para acceder a un recurso del fs
3) Ejecuto la espera luego de completar el bloqueo y volver a exec por decisión del planificador
4) Como querramos, pudiendo hasta (debe ser muy complicado igual) optimizar en el caso del RR irme al bloqueo una vez se me acaba el quantum, y luego cuando vuelva con mas quantum ejecutar parte de la espera restante.

Y lo segundo, la tarea DESCARTAR_BASURA es un poco especial

> Tarea | DESCARTAR_BASURA
> -- | --
> Parámetros | -
> Pasos | Verificar que exista un archivo llamado Basura.ims en el i-Mongo-Store. Si el archivo existe, Eliminarlo. Si el archivo NO existe, notificar por el log
> Ejemplo | DESCARTAR_BASURA
> 

Desde el punto de vista de la planificación, esta tarea se ejecuta por 0 segundos (no me tengo que mover, no tengo que hacer espera). Sin embargo, desde el FS si hago algo: escribir en la bitácora que el tripulante fulanito descartó la basura.

Me suena medio raro pero capaz si es así y ya está.

Lo que si no entiendo es, tanto si el archivo existe o no existe, ¿la tarea se finaliza de todas formas? ¿Con notificar por el log se refiere a escribir sobre la bitácora que no existía? (el módulo i-Mongo-Store no menciona nada de un log)

Suerte y saludos!
Cristian

**Comment by gastoncastineira** [comment]
Vamos a estar revisando lo de descartar basura y otras cuestiones con las tareas por ambigüedades que fuimos notando con el tema en una futura errata, pero me perdiste por completo con esto:

> Ahora bien, si la tarea implica un bloqueo de FS

¿Qué querés decir con un bloqueo de FS? El FS nunca se bloquea

**Comment by julchat** [comment]
Sisi me expresé mal, me refería a un bloqueo de E/S

**Comment by gastoncastineira** [comment]
Eso es una de las cosas que estamos revisando. Todo apunta a que nos comimos el parámetro de demora de E/S. En estos días nos vamos a estar juntando para revisar todas las notas que tenemos y armar una errata, así que estate atento ;)

**Comment by RaniAgus** [comment]
¡Buenas! Hoy salió una nueva revisión del enunciado, ¿quedó alguna duda en cuanto a lo que nos planteabas?
> ¿Con notificar por el log se refiere a escribir sobre la bitácora que no existía? (el módulo i-Mongo-Store no menciona nada de un log)

Ojo con esto, no se menciona que hayan logs obligatorios como en anteriores TP, pero sí es altísimamente recomendable que tengan uno para informar el estado del sistema en todo momento y que se pueda corroborar que funciona como se espera.

¡Saludos!

**Comment by julchat** [comment]
¡Buenas!
Ahí leí los cambios que realizaron.
Acerca de este tema, lo único que me quedó colgando es esto

> Si un tripulante quisiera ejecutar una tarea, lo primero que debe hacer es moverse hacia la posición, donde cada movimiento implica mandar un mensaje al fs para que pueda escribir un registro en la bitácora.
> Ahora bien, si la tarea implica un bloqueo de FS, ¿cuando se ejecuta la "espera"?
> 
> 1. La que SEGURO no es: desde que arranco a ejecutar la tarea y sigo contando si me voy a bloqueado
> 2. Ejecuto la espera antes de bloquearme para acceder a un recurso del fs
> 3. Ejecuto la espera luego de completar el bloqueo y volver a exec por decisión del planificador
> 4. Como querramos, pudiendo hasta (debe ser muy complicado igual) optimizar en el caso del RR irme al bloqueo una vez se me acaba el quantum, y luego cuando vuelva con mas quantum ejecutar parte de la espera restante.

Básicamente mi duda es si la espera en el discordiador se ejecuta completamente antes de atender a un posible llamado de E/S si es necesario, luego del mismo en caso de que exista dicho llamado, o si puedo en el caso del RR hacer una optimización que en caso de que sea necesario hacer una llamada de E/S, que la haga cuando se me esta por acabar el quantum (porque ahora los llamados a E/S consumen 1 ciclo)

Gracias!

**Comment by RaniAgus** [comment]
Cito la sección de "Tareas" en Submódulo Tripulante:
> Este archivo de tareas tendrá una sola tarea por línea y cada línea tendrá los siguientes parámetros separados por punto y coma (;)
> - Nombre y parámetros de la tarea
> - Ubicación en X
> - Ubicación en Y
> - **Duración de la tarea (expresada en ciclos de CPU; en caso de que sea una tarea de Entrada Salida, este tiempo deberá transcurrir en la cola de bloqueados)**

Teniendo este último punto en cuenta, en el caso de que la tarea sea de E/S, el tripulante va a ejecutar un solo ciclo de CPU para realizar la solicitud y luego se va a bloquear por la cantidad de tiempo especificada. El hecho de que la escritura se realice al principio o al final es indistinto.

Por otro lado, no se olviden de que entre los esquemas de trabajo no se incluye VRR, por lo que no hay ninguna optimización para los procesos I/O bound (aunque gracias por la idea):

> Los tripulantes podrán planificarse bajo uno de los dos esquemas de trabajo diferentes soportados (elegido por archivo de configuración):
> - Primero en llegar, primero en trabajar (FIFO).
> - Turnos Rotativos (RR).

¡Saludos!

**Comment by julchat** [comment]
Perfecto y clarísimo!
Muchísimas gracias!
Cierro el issue
