### ISSUE TITLE
VM No me permite iniciar sesión

### ISSUE THREAD

**Issue by octavioramirez12** [sisoputnfrba/foro#2055]
Cuando trato de iniciar sesión en la VM con el usuario y contraseña utnso, intenta iniciar sesión y me vuelve a mostrar la página de login, y no me deja avanzar más de ahí. No me muestra ningún mensaje.
La máquina me estaba funcionando hasta que instalé las guest additions. Le aumenté la memoría, reinicié y volví a probar y nada.

**Comment by iago64** [comment]
Buenas! como va? 
Un toque las preguntas del template nos ayudan a entender mejor el contexto, te podes copar y comentarnos:

## Sobre la VM
- Versión de VirtualBox: 
- Memoria RAM asignada:
- Memoria de video asignada:
## Sobre el Host
- Sistema Operativo y versión:
- Memoria RAM:
- Procesador:

Ya con esa info podemos tener una mejor idea de como viene la mano.

**Comment by octavioramirez12** [comment]
**Sobre la VM**
Versión de VirtualBox: 6.1.20
Memoria RAM asignada: 2048
Memoria de video asignada: 16MB
**Sobre el Host**
Sistema Operativo y versión: Windows 10 20H2
Memoria RAM: 8GB
Procesador: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz   2.70 GHz

**Comment by octavioramirez12** [comment]
Cuando inicio en modo invitado me aparece un mensaje de error: No session for pid 3037

**Comment by Nachiten** [comment]
> Cuando inicio en modo invitado me aparece un mensaje de error: No session for pid 3037

Buenas! Como estas?

Me parece bastante extraño el problema que estás teniendo...

Yo te doy esta recomendacion que es la mas ""vaga"" pero la que seguro mejor funciona.

Te diria que te reinstales la VM usando el vdi que te damos nosotros. Si guardaste los comprimidos que sería lo mejor, lo descomprimis directo. En caso que no, tendrias que volver a bajar todo.

Pero por favor antes de reinstalar la VM con el vdi asegurate de usar [este tutorial](https://youtu.be/0CL9Os8IUcY) para corroborar que los archivos que bajaste están correctos. Luego te aseguras que no vas a tener ningun problema al instalar.

**Comment by iago64** [comment]
Otra cosa para sumar aparte de lo que comenta Nacho, es que 16mb para el video es muy poco, generalmente recomendamos que lo suban a 64 o incluso 128 mb (que es el máximo) como para que pueda levantar bien la VM.

**Comment by octavioramirez12** [comment]
Volvi a reinstalar la máquina y ahora funciona bien. No se porque habra sido el error
