### ISSUE TITLE
[I-Mongo-Store] Duda sobre comunicación con los tripulantes(logs de bitácora)

### ISSUE THREAD

**Issue by nicolascalle** [sisoputnfrba/foro#2056]
Buenas!
El enunciado menciona que los tripulantes deben informar al iMongoStore los movimientos y tareas que van realizando para que los almacene en la bitácora en el filesystem. Mi pregunta es si el tripulante, una vez que envía el mensaje, se queda esperando a que el ImongoStore le responda si tuvo éxito la operacion o simplemente sigue haciendo sus tareas . Esa respuesta sería con algun código de estado para indicar si se almacenó correctamente o no.

### 📔 Citas del enunciado/videos

![image](https://user-images.githubusercontent.com/28161787/116580383-b441f580-a8e9-11eb-9d49-4210bea2f88d.png)

**Comment by RaniAgus** [comment]
¡Buenas! No hace falta que el discordiador se quede esperando para handlear el error en caso de que ocurra, sería uno de esos casos border que pueden no contemplarse. Estaría bien con simplemente loguear desde el ims que "no se pudo guardar", para estar al tanto del error. ¡Saludos!

**Comment by nicolascalle** [comment]
A raiz de esto me surje la misma duda pero para los mensajes GENERAR_OXIGENO, CONSUMIR_OXIGENO, etc. Este caso es igual al anterior? 
Porque entiendo que los tripulantes le estan solicitando un recurso y esperan a que el iMongo le responda. Por otro lado, la duracion de la tarea viene dada y el planificador la conoce, entonces, en este caso no sería necesario que el iMongo responda.
Gracias, Saludos!

**Comment by Nachiten** [comment]
> A raiz de esto me surje la misma duda pero para los mensajes GENERAR_OXIGENO, CONSUMIR_OXIGENO, etc. Este caso es igual al anterior? 
> Porque entiendo que los tripulantes le estan solicitando un recurso y esperan a que el iMongo le responda. Por otro lado, la duracion de la tarea viene dada y el planificador la conoce, entonces, en este caso no sería necesario que el iMongo responda.
> Gracias, Saludos!
> 

Buenas!

Segun mi opinion, siempre que tengas que esperar una rta del FS vas a quedar obviamente esperandola de manera sincronica, dado que no podes continuar hasta tener dicha respuesta.

Luego, cuando lo unico que haces es decirle "che FS, logueame esto que hice" me parece lo mejor que sea de manera asincronica. Es decir, como tripulante le mandas el msg y seguis con tu vida, sabiendo que en algun momento lo guardará.

Yo tendría la siguiente precaucion igual, cuando voy a mandar un msg asincronico levantaria un hilo q lo haga. Esto serviria para que, mientras el modulo sigue con lo suyo, este hilo enviaria el msg y se quedaria esperando un ACK. En caso que el ACK no llegue o retorne error, podria volver a enviar el mensaje cada cierto tiempo. Aunque esto que te estoy diciendo no sería necesario segun la consigna, sería algo muy lindo de agregar dado que vuelve el sistema mas robusto.

**Comment by nicolascalle** [comment]
Perfecto! Muchas gracias por la respuesta.
