### ISSUE TITLE
Path tareas discordiador

### ISSUE THREAD

**Issue by andresbulgheroni** [sisoputnfrba/foro#2057]
Tengo una consulta del modulo discordiador:
iniciar_patota tiene como argumento el path de archivo tarea y lo lee el discordiador.
Entonces, este archivo de tareas tiene que ser enviado hacia mi ram hq(para que luego el procese las tareas tiene que hacer el tripulante).
Se me ocurren dos maneras de hacer esto:

1: Leo el archivo y le envió a memoria el contenido de este.

2: Le paso el path y memoria lo lee.

Saludos

**Comment by ncoen97** [comment]
Buenas, tengan en cuenta que los distintos módulos pueden estar en distintas maquinas, así que la opción 2 quedaría descartada. Saludos!
