### ISSUE TITLE
Dudas sobre tripulantes en Discordiador y sobre Blocks.ims del i-Mongo Store

### ISSUE THREAD

**Issue by yairtele** [sisoputnfrba/foro#2058]
Buenas,

Con mi grupo leímos el enunciado y nos están quedando las siguientes dudas:

1. Para el Discordiador, qué ocurre con los tripulantes que quedan "sobrando" porque exceden el grado de multiprogramación? Inician y quedan en estado NEW o ni siquiera deben iniciar?

2. Entendemos que la planificación se realiza en torno a los tripulantes y no a la patota, la cual sirve más que nada como un identificador para el módulo de memoria y poder asociarlo con las tareas. Está bien pensado de esta forma?

3. Respecto al i-Mongo Store, entendemos que el archivo Blocks.ims debe ser mapeado a memoria (mmap()), luego en torno a este mapeo se realiza la copia (memcpy()) sobre la que se estará trabajando y cada cierto tiempo, el archivo original se sincronizará con esta copia (msync()). Es correcto dicho enfoque?

**Comment by iago64** [comment]
Buenas! como va?
Esto de tener las preguntas en puntos es una genialidad, paso a contestarlas :)

1. Ojo que el grado es de _multiprocesamiento_, eso quiere decir que van a entrar todos y eventualmente se quedan en READY, pero vas a tener una cantidad limitada en EXEC.

2. Si, uds planifican los tripulantes, la patota nomas les sirven a modo de agrupador para compartir memoria.

3. Efectivamente, la idea es que con _mmap()_ a uds les va a quedar una dirección de memoria sobre la cual van a poder operar con _memcpy()_ y luego eso se sincroniza (cuando al SO le pinta) y por las dudas, ademas les agregamos que lo tengan que forzar con _msync()_

Saludos.-

**Comment by yairtele** [comment]
Fundamental tener las consultas ordenadas para que se entiendan!

Excelente todo, gracias por las respuestas!!

Cierro el issue. Saludos!
