### ISSUE TITLE
Responsabilidades sobre archivos

### ISSUE THREAD

**Issue by FlorTorreg** [sisoputnfrba/foro#2059]
Encarando la tarea de OBTENER_BITACORA nos surgió dudas sobre la responsabilidad en archivos:

1. El Discordiador puede acceder a archivos que crea y modifica el i-MongoStore (bitacora por ejemplo)?
2. El Discordiador y Mi-RAM HQ pueden leer archivos (como las tareas) o deben hacerlo a través de i-MongoStore?

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va?
1. No, no puede, recuerden que el TP está hecho para que funcione en máquinas distintas, así que no habría forma de que el Discordiador acceda a los archivos que se crean en la máquina donde se encuentra el IMS sin pasar por él.
2. Justamente, siguiendo con la idea del punto 1, tenemos esta limitación de tener todos los módulos en red por lo que a fines prácticos sería imposible que les pidiéramos que el i-Mongo Store leyera _todos_ los archivos (por más que sea "el File System"). Es por esto que en cada módulo se especifica qué archivos puede abrir, y en el caso de las tareas, lo abre el Discordiador. _El contenido que se lee en ese momento_ se pasa (creación de tripulantes mediante) por sockets a Mi-RAM HQ para que éste sea el encargado de mantenerlo en memoria.
¡Saludos!

**Comment by ncoen97** [comment]
Buenas, quedó alguna duda con la respuesta de Agus?
Si ya quedó resulto les pido que cierren el issue.
Saludos!
