### ISSUE TITLE
No me queda del todo claro es cada cosa del diagrama,

### ISSUE THREAD

**Issue by urieeel19** [sisoputnfrba/foro#2060]
Buenas.
Leyendo el enunciado, la parte del diagrama no me queda del todo clara.
 Si cada modulo que aparece ahi es un proceso, hilo y como es su comunicacion entre si, osea las flechas no entiendo, como se tienen que comunciar.
Muchas gracias.
![imagen](https://user-images.githubusercontent.com/38087767/116786582-c781cc00-aa75-11eb-9b9e-9778bf5c38e1.png)

**Comment by iago64** [comment]
Buenas! como va?

Los procesos se tienen que comunicar mediante **sockets**. Mi-RAM HQ e i-Mongo-Store son procesos que va a recibir las conexiones de los tripulantes, estos tripulantes van a ser _hilos_ dentro del módulo Discordiador (por eso que tanto Discordiador como Tripulante están enmarcados por un cuadrado).

De todas formas ese diagrama es un mero esquema a modo de presentación, dentro del detalle de cada módulo vas a tener mas especificado como y cuando se dan las conexiones.

Saludos.-

**Comment by ncoen97** [comment]
Buenas, se entendió la respuesta de dami? les surgieron más dudas?
Si ya quedó resuelto les pido que cierren el issue.
Saludos!

**Comment by urieeel19** [comment]
Si, se entendió. Perdon por la tardanza y muchas gracias. Cierro issue
