### ISSUE TITLE
Duda sobre la implementacion de los estados exec, block y ready

### ISSUE THREAD

**Issue by damianmasi** [sisoputnfrba/foro#2061]
Tenemos dudas sobre la implementación del proceso de planificación, nuestra idea era asignar un hilo para exec, uno para ready y uno para block y mediante semáforos sincronizarlos de manera secuencial, para que no haya desfasaje entre los procesamientos de los estados. 
Tendríamos una cola (lista a la hora de implementar) por estado y los hilos de la planificación sabrían bajo que contexto mover los tripulantes de una cola a otra.
Podemos hacer la implementación de esta manera o hay alguna limitación que tengamos que tomar en cuenta.

Equipo-MAGI

**Comment by iago64** [comment]
Buenas! como va?

Respecto a las limitaciones, si el enunciado no contradice no hay problema, es la regla base.
Ahora bien, respecto a lo que planteas en la página 11 del enunciado dice: 

> El sub-módulo Tripulante es el encargado de obtener y ejecutar todas las tareas que se le definan, y mostrar los resultados de estas al usuario. Este submódulo se implementará mediante hilos creados bajo demanda en el Módulo Discordiador.

Esto se traduce en que tu solución esta incompleta, te faltan los hilos de los tripulantes :)

Saludos.-

**Comment by damianmasi** [comment]
Sisi, estábamos pensando lo de los hilos, tenemos dos planteamientos sobre la implementación y teníamos la duda de si estaban bien pensados

La idea principal de estas colas de planificación es mover una estructuras con los datos necesarios del tripulante en el discordiador como podría ser alguna flag (lo mínimo indispensable para no repetir la información que tiene la memoria).
A raíz de lo de "hilos creados bajo demanda" pensamos en que cada vez que realiza una acción, ya sea avisar a la memoria que se movió o realizar un I/O se generaría un hilo para atender esta acción, de esta manera pensamos el crear los hilos bajo demanda, ya que no sabíamos si se puede modificar la función que ejecuta un hilo cuando ya esta iniciado.
Como segunda opción ya que quizá con la anterior no estábamos "planificando los hilos" puntualmente pensamos en que en el momento de que un tripulante inicia su planificación da creación a un hilo con la lista de tareas que realizara, en el momento en el que el tripulante esta apto para realizar la siguiente tarea de la lista (ya sea porque entro en exec o en block por un I/O) mediante semáforos le daría paso al hilo para realizar la siguiente tarea de su lista.

**Comment by ncoen97** [comment]
Buenas, un par de cosas para que tengan en cuenta.
Con respecto a los hilos de los tripulantes (los creados a demanda), piensen que el tripulante solo ejecuta cuando está en estado EXEC, por lo tanto todo lo que sea I/O o envío de mensajes del modulo Discordiador no debería hacerse dentro de esos hilos, entonces todo lo que sean "tareas del SO" las van a tener que manejar aparte.
Otra cosa a tener en cuenta es que no van a poder pasarle al hilo del tripulante una lista de tareas porque las tareas se van solicitando de a una.
Saludos!

**Comment by damianmasi** [comment]
buenas, gracias por la respuesta, con esto pregunto para que me quede claro, esta bien pensar en que cada vez que el tripulante ejecuta (estando en estado exec) creo el hilo para atender esa tarea?

Equipo-MAGI

**Comment by iago64** [comment]
@damianmasi como va? Te quedo alguna duda o estamos para cerrar el issue?

**Comment by damianmasi** [comment]
Si, muchas gracias
