### ISSUE TITLE
consulta sabotaje relacion estado exit

### ISSUE THREAD

**Issue by andresbulgheroni** [sisoputnfrba/foro#2062]
Buenas noches una consulta sobre el sabotaje.
A mi entender cuando un tripulante finaliza sus tareas pasa al estado exit.
Si un tripulante finaliza sus tareas, por ende se encontraría en estado exit, pero otros tripulantes siguen realizando tareas y surge un sabotaje.

1-Este tripulante si llega a ser el mas cercano podría resolver el sabotaje sin pasar por el estado bloqueado?  
2-O es que los tripulantes que se encuentren en estado exit no pueden resolver los futuros sabotaje.

Desde ya muchas gracias.

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va?
Es una muy buena pregunta, efectivamente el tripulante pasa al estado Exit, y eso hace que en ningún momento forme parte de los tripulantes que pasan a bloqueado, cito la "Administración de los Sabotajes":

> Todos los tripulantes deberán dejar sus tareas en ese momento, pasando a estado bloqueado en el siguiente orden:
> 1. Los tripulantes que se encontraban en EXEC
> 2. Los tripulantes que se encontraban en Ready
> 3. Los tripulantes que finalicen sus Bloqueos por I/O a medida que vayan concluyendo.

Esto hace que tampoco forme parte de los tripulantes seleccionables para resolver el sabotaje. También, en el diagrama de estados vas a ver que no hay flechas partiendo desde Exit hacia otros estados (en la teoría se explica que lo único que sí está implícito es lo contrario: todos los estados tienen una "flechita" a Exit, que no se grafica para que sea más amigable a la lectura).

¡Saludos!
