### ISSUE TITLE
Estructuras de Mi Ram - TCB

### ISSUE THREAD

**Issue by RodrigoLista** [sisoputnfrba/foro#2066]
Buenas tardes. Estaba leyendo las correcciones en las estructuras, y creo que hay un error en la parte del TCB. El ultimo elemento agregado, que es el Puntero_PCB, tiene como descripción "Dirección lógica del PCB del tripulante", y creo que seria "Dirección lógica del PCB de la patota". Así se podría conocer desde tripulante, a que patota pertenece. Muchas gracias

**Comment by ncoen97** [comment]
Buenas, no es un error. Cuando decimos "del tripulante" nos referimos al tripulante al que pertenece el TCB que se está leyendo en la memoria. Justamente esto lo agregamos para que se conozca la patota (PCB) desde un tripulante (TCB).
Igualmente gracias por el comentario, saludos!

**Comment by RodrigoLista** [comment]
No me estaría quedando claro. El enunciado dice lo siguiente:

> Dado que en el tp siempre buscamos tener ciertas analogías con la realidad, nuestros Tripulantes van a tener su bloque de control (TCB) y nuestras Patotas van a tener su propio bloque de control (PCB).

Por lo que interpreto, el PCB pertenece a la Patota y no a un Tripulante. De todas formas, ese puntero me daría la dirección de memoria a donde se encuentra el PCB que contiene el ID de patota y las tareas. Esa seria la función?


Y tengo **_otra consulta_** respecto al elemento del TCB "Próxima instrucción". Acá debería guardar un valor numérico. Entonces yo debería buscar en el PCB donde se encuentran todas las tareas, y con ese identificador lograr determinar a que tarea se corresponde?
Muchas gracias.

**Comment by ncoen97** [comment]
Voy a numerar así queda mas lindo.

1. Claro, es que en este caso "tener su bloque de control" o "tener su propio bloque de control" es más una relación uno a uno, donde intentamos decir que un tripulante corresponde con un TCB y una patota con un PCB. Igualmente está bien lo que planteas, esa sería la función del campo.
2. Si, el mecanismo es el que indicas, lo único te hago un mini fix de lo ultimo que mencionas: con ese identificador van a poder determinar **cual es la próxima tarea del tripulante**.

Saludos!

**Comment by RodrigoLista** [comment]
Muchas gracias. Me quedo mas claro. Cierro Issue. Saludos
