### ISSUE TITLE
Error al iniciar VM

### ISSUE THREAD

**Issue by everlizarraga** [sisoputnfrba/foro#2067]
Hola. Me aparece un error raro al iniciar la VM, esto paso luego de que instalara otra versión del VirtualBox. Lo que pasa es que decidí cambiar de versión porque la versión 6.1 que tenía antes, no me permetía compartir el portapapeles entre mi notebook y la VM y eso me dificultaba al momento de compartir o debatir algo de cófigo con el grupo. Cabe resaltar que segui los pasos de los videos para configurar correctamente lo de compartir el portapapeles de la VM, pero no funcionaron en la version del virtualBox 6.1
Como ya había probado en otra compu la versión de virtualBox 5.2.44 y en esa andaba todo OK lo de compartir el portapapeles y eso. Decidí desinstalar la versión que tenía en mi notebook  e instalar la 5.2.44
EL tema es que cuando quice iniciar la VM me saltaban errores. Para mas concreto, solo me aparecio la [ventana en DOS](https://s3.gifyu.com/images/Error-de-carga.jpg) por 2 segundos, como si estuviera apunto de cargar la VM, pero luego de esos 2 segundos, aparecen los errores.

Ya intenté descargar la VM devueta desde cero. E incluso probe en reinstalar otras versiones de Virtual Box, pero ahora no me deja iniciar en ninguna version la VM y me saltan [estos errores](https://s3.gifyu.com/images/Error-de-carga-Lubuntu.jpg).
Incluso volví a la versión 6.1, como para poder avanzar el TP, pero ahora ni siquiera en esa me permite iniciar la VM.

### 🔎 Búsqueda en foros

Intente buscar algo sobre estos errores, pero no encontré nada puntual respecto a esto.

### 📦 Especificaciones de la VM
- Versión de VirtualBox: 5.2.44
- Memoria RAM asignada: 1024 MB

### 🖥️ Especificaciones del host
- Sistema Operativo y versión: Windows 10 Pro  (Siempre lo mantengo actualizado)
- Memoria RAM: 16GB
- Procesador: i7-8550U 1.8GHz
- Notebook: DELL inspiron 7573 - 4K tactil

### 💻 Logs

Aca comparto los mensajes que aparecen y tambien la [Foto](https://s3.gifyu.com/images/Error-de-carga-Lubuntu.jpg)

Raw-mode is unavailable courtesy of Hyper-V. 
(VERR_SUPDRV_NO_RAW_MODE_HYPER_V_ROOT).

Código resultado: 
E_FAIL (0x80004005)

Componente: 
ConsoleWrap

Interfaz: 
IConsole {872da645-4a9b-1727-bee2-5585105b9eed}

El otro error que me aparece es el siguiente:
==================================

The instruction at 0x00007FFA90D19B2C referenced memory at 0X00007FFA90D19BC. The memory could not be written.

Click on OK to terminate the program
Click on CANCEL to debug the program

**Comment by gastoncastineira** [comment]
Fijate si lo que está en #1954 o #1600 te sirve

**Comment by RaniAgus** [comment]
¡Buenas! Como se comenta en los issues que citó Gasti, probablemente sea un problema con HyperV, asegurate de tenerlo desactivado como se explica en [este comentario](https://stackoverflow.com/a/59039532).
También otro detalle a tener en cuenta es que es muy común que la 6.1 tenga problemas con las Guest Additions, para lo cual recomendamos usar la 6.0.18 en su lugar. Saludos

**Comment by everlizarraga** [comment]
Hola. Hice todo lo que sugerian en las issues, pero nada de eso me funcionó. 
Sin embargo tengo el agrado de contarles que pude solucionar el problema. Y les cuento como:
- Me di cuenta que en los windows 10 que estan al dia con sus actualizaciones, generalmente tenían este problema (Me fije en varias compus), me refiero a las versiones de VirtualBox 5.2 y 6.0 
- Además también observé que los que instalaban la última version del VirtualBox (6.1.22), si podian levantar la VM, pero tenían problemas con el Guest Additions.

Con esto deduje que las versiones 6.1 si podían ejecutar la VM, así que para confirmar esta hipótesis, instale otra version de la 6.1 (instalé la 6.1.4) y efectivamente pudo levantar la VM sin problemas y además le andaba bien el Guest Additions (la resolución de la pantalla se adaptaba sin problemas a la ventana). Sin embargo, esta versión tenía problemas con compartir el portapapeles de la VM con la compu.

Conclusión:
========
Buscando y probando versiones de la 6.1 de VirtualBox, logré dar con una que le anda todo, todito.
- Levantar la VM
- No tirar ningun error durante la ejecución de la VM
- Llevarse bien con la Guest Additions.
- Compartir el portapapeles sin problemas

La versión es la [6.1.6](https://www.virtualbox.org/wiki/Download_Old_Builds_6_1).
Dejo el [link](https://download.virtualbox.org/virtualbox/6.1.6/VirtualBox-6.1.6-137129-Win.exe) para que lo descarguen.

![image](https://user-images.githubusercontent.com/49339761/117407154-89a4fd80-aee4-11eb-909f-a36f04baaf02.png)

A mi me funcionó. Espero les sirva.

**Comment by iago64** [comment]
Che muy buena data @everlizarraga !
Generalmente veníamos recomendado versiones viejas de Virtual Box porque la 6 solía traer algunos dolores de cabeza, ahora con esta info nueva que aportas, vamos a tenerlo en cuenta!
Abrazo!

**Comment by everlizarraga** [comment]
Hay gente que les sirvio la 6.1.6 pero hay otros que se les presentó algún inconveniente cuando cierran mal la VM o suspenden la notebook con la VM andando. Si te paso esto o alguna otra cosa que hizo que la VM te empezara andar mal. Hay una versión anterior que es la [6.1.4](https://download.virtualbox.org/virtualbox/6.1.4/VirtualBox-6.1.4-136177-Win.exe) que anda más estable y hasta hora no ha presentado problemas.

El único inconveniente que tiene es que no se puede compartir el portapapeles en forma bidireccional, pero por lo menos vas a poder hacer el TP sin ningun otro inconveniente.
