### ISSUE TITLE
Dudas sobre multihilos

### ISSUE THREAD

**Issue by heinHertz** [sisoputnfrba/foro#2068]
Hola  tengo  dudas puntuales sobre el servidor imongo:

1.  No tengo muy en claro el tema de servidor multihilos,   si por ejemplo cada tripulante del discordiador es un hilo,  entonces imongo tiene que crear un hilo de escucha  por cada hilo ?  y apartir de ahi procesa ese hilo una respuesta si hace falta?

gracias.

**Comment by RaniAgus** [comment]
¡Buenas! 
Antes que nada, para entender mejor mi respuesta te recomiendo haber leído primero la [guía de introducción a sockets](https://docs.google.com/document/d/11CH_a-Uw5CRXWgscKvrUuGQsiaqy_hE3_njJ4YXv5cI/edit), _(y [la parte de sockets de la charla de 2019](https://www.youtube.com/watch?v=V0KFn9w62sY) también puede ser muy útil, es corta, dura 10 min)_.

La idea del servidor multihilo que los crea bajo demanda es que haya un único socket (en un único hilo) que se `bind()`ea a un puerto y, a partir de ahí, por cada conexión que acepte con `accept()` se crea un hilo para atenderla (así se pueden ir aceptando y atendiendo otras conexiones en simultáneo). 
Para poder crear una nueva conexión con Mi-RAM (servidor), el Discordiador (cliente) tiene que conocer dos datos (que se obtienen del archivo de configuración): 
1. la IP de la computadora en donde está coriendo Mi-RAM
2. el puerto a donde Mi-RAM se bindeó para poder hacer el `connect()` (este dato simplemente tiene que coincidir con el que está en el config de Mi-RAM). 

En base a esto, tené en cuenta que si quisieras que Mi-RAM se bindee a varios puertos (uno por cada tripulante), éstos tendrían que ser todos distintos y el Discordiador tendría que conocerlos a todos de antemano, lo cual sería un caos y no lo recomendamos para nada. 

Acerca del cuándo un tripulante tiene que abrir una nueva conexión: eso depende de cómo lo quieran implementar, pueden abrir una al principio y mandar todo por ahí o pueden ir abriéndola al momento de enviar el mensaje y cerrarla cuando llegue (incluso, dependiendo de qué quieran hacer con esa conexión puede que les quede más cómodo usar una forma u otra).

¡Saludos!

**Comment by heinHertz** [comment]
gracias !!
