### ISSUE TITLE
🚀🚀 Cambios de Grupo - Busca para completar tu tripulación 🚀🚀

### ISSUE THREAD

**Issue by iago64** [sisoputnfrba/foro#2069]
Buenas! 
Habiendo cerrado la inscripción de grupos, damos paso al inicio de los cambios de grupo. 

En este thread van a poder buscar integrantes para completar su grupo o grupo en caso de haberse quedado solos.

Por favor, traten de *NO* publicar números de celular, tengan en cuenta que el foro es publico y cualquier persona incluso fuera de la UTN FRBA puede llegar a ver su número.

Como siempre, cualquier inconveniente con los cambios de grupos envíen un mail a inscripciones@utnso.com.ar

Recuerden que los cambios de grupos cierran 1 semana después del _Checkpoint Presencial Virtual_

Saludos.-

**Comment by fedesz** [comment]
Buenas, en mi grupo una persona abandono la materia y estamos en busqueda de 1 persona más para completar los 5. Si alguien está buscando grupo, que responda este mensaje y le paso un medio para contactarme!

**Comment by matiasBendayan** [comment]
buenas, en nuestro grupo se fueron varias personas, actualmente estamos trabajando en MiRam asi que si a alguien le falta ese modulo contacteme.

**Comment by rpages2020** [comment]
Buenas, una persona de nuestro grupo dejo la materia, si alguien quedo solo o quiere cambiarse es bienvenido.

**Comment by nramrezmoreale** [comment]
Buenas, una persona de nuestro equipo se dió de baja en la materia. Si buscas un grupo nuevo esta es tu oportunidad. Contactame.

**Comment by matiasferrerovilas** [comment]
Un miembro del grupo se dio de baja, asi que si alguno busca grupo es bienvenido. Le dejo mi email: matigfv@gmail.com

**Comment by mateorobaina** [comment]
Buenas, una persona de nuestro grupo se dio de baja, si alguien quiere unirse es bienvenido, mi mail es: mateorobainaa@gmail.com

**Comment by rocioveloso** [comment]
Buenas, estoy buscando grupo para unirme!!! Mi mail es rociobelenveloso@gmail.com

**Comment by AgustinTejera** [comment]
Buenas noches, en nuestro grupo una persona abandono la materia y buscamos a uno más.
Si alguien está buscando grupo, mándeme un mail al siguiente correo: atejera@frba.utn.edu.ar

Saludos!

**Comment by gonzalogarcia2318** [comment]
Buenas, un integrante de nuestro grupo se dio de baja. Si alguien esta buscando grupo, mi mail es: gonzalogarcia2318@gmail.com

Saludos!

**Comment by HappelJavier** [comment]
Buenas, busco grupo para unirme, mi mail es happeljavierleonardo@gmail.com
Saludos.

**Comment by fergam01** [comment]
Buenas, busco grupo para unirme, mi mail es fernandogam@hotmail.com.ar y es mi primera vez cursando la materia.
Saludos.

**Comment by kevinl129** [comment]
Buenas, me encuentro buscando grupo para unirme, mi mail es cazonleonel@gmail.com 
Saludos.

**Comment by victoriaguillosson** [comment]
Buenas, buscamos 1 integrante que se sume a nuestro grupo, somos 4. Preferentemente que este laburando en Discordiador.
Dejo mi mail vickyguillosson@gmail.com
Saludos

**Comment by RodrigoLista** [comment]
Hola. Estamos buscando un integrante para completar el grupo. No tenemos preferencia con ningun modulo. Venimos con el tp a termino. Cualquier cosa, manden mail a rodrigo_lista@hotmail.com. Saludos

**Comment by AgustinTejera** [comment]
Buenas noches, en nuestro grupo una persona abandono la materia y buscamos a uno más.
Si alguien está buscando grupo, mándeme un mail al siguiente correo: atejera@frba.utn.edu.ar

Saludos!

**Comment by juan-nisimura** [comment]
Buenas, en nuestro grupo una persona dejó la materia y estamos buscando un nuevo integrante.
Dejo mi mail: junisimura@frba.utn.edu.ar
Saludos.

**Comment by rpages2020** [comment]
Buenas, de nuestro grupo 2 personas se dieron de baja. Estamos buscando integrantes. 
Acá esta mi mail, rpages@frba.utn.edu.ar. Salu2.

**Comment by Maurorossi68** [comment]
Buenas, se bajó un compañero por lo que tenemos lugar para una persona más en el grupo, si te interesa, dejo mi mail: mrossi@frba.utn.edu.ar

**Comment by Schmidt-mat** [comment]
Buenas, en nuestro grupo se bajaron 2 personas. Si alguien está buscando mi email es: mschmidt@frba.utn.edu.ar

**Comment by brunotello** [comment]
Hola!

Estamos buscando un integrante porque se bajó un chico. Tenemos varias cosas ya avanzadas y se encargaría del filesystem con alguien más del equipo

**Comment by martinmereles** [comment]
Hola! en nuestro grupo una persona dejó la materia y estamos buscando un nuevo integrante.
Mi mail: jmereles@frba.utn.edu.ar
Saludos.

**Comment by facundosofo** [comment]
Hola! 

Dos personas de nuestro grupo abandonaron la materia y estamos buscando nuevos integrantes. Preferentemente uno que haya laburando en miramhq.
Mi mail es : facusofia@frba.utn.edu.ar

**Comment by Maurorossi68** [comment]
Buenas, se bajó un compañero por lo que tenemos lugar para una persona más en el grupo, si te interesa, dejo mi mail: mrossi@frba.utn.edu.ar

**Comment by JuradoMatias** [comment]
### Buuenas! genios y genias!

Bueno, estamos en búsqueda de una persona más en le grupo ya que una se bajo, lamentablemente.
La persona que entre, **se tendría que encargar de** la parte de **_File System_** (i mongo store) con la ayuda de un compañero, de igual manera, solemos preguntarnos cosas, si uno se traba, el otro (ya sea de su modulo o de otro) **les damos una mano**.

¿El estado del grupo?
           - Discordiador: bien pero falta meter un poco mas de mano
           - Mi Ram: bueno
           - i mongo store: *phantom* 💨


Les dejo mi **mail**: matijurado@frba.utn.edu.ar

**Comment by Lucassiturrioz** [comment]
Hola, estamos en búsqueda de una persona mas en el grupo ya que uno se bajo, lamentablemente. 
La persona que entraría, se tendría que encargar en la parte de File System ( i mongo store ) con la ayuda de otro compañero

Estado del TP
-Discordiador : Casi terminado 
-Mi Ram : Maso menos
-File System : Maso menos

Mi numero es 1124634937 y mi correo es: lucasiturrioz212@gmail.com

**Comment by SfaraLucas** [comment]
TE NECESITO!!! JOIN THE NAVY!!!

Estamos buscando una persona que este dispuesta a hacer un pacto de sangre para terminar este Tp y asi reemplazar al desertor de nuestro team.

El trabajo que le tocaria a dicha persona es el modulo de filesystem.

El resto esta encaminado.

Numero: +54 9 11 34465806

**Comment by lucaslago16** [comment]
Hola! estamos buscando un integrante para terminar el tp, que pueda ayudar en el modulo que prefiera sea el discordiador o el mi-ramHQ, estan todos los modulos encaminados.
Cualquier cosa mandenme un mail a: lucaslagen@gmail.com

**Comment by sofiabarreneche** [comment]
Buenas! Estamos buscando alguien para sumarse a nuestro grupo! 
Les dejo mi mail sofiabarreneche8@gmail.com

**Comment by juanff22** [comment]
Hola, se nos bajaron 2 integrantes, así que estamos buscando nuevos integrantes, que puedan ayudar en el discordiador y mi ram.

Dejo mi mail para contacto: jferchero@frba.utn.edu.ar

**Comment by rpages2020** [comment]
CERVEZA GRATIS!!!!
Ahora que tenemos su atención, seguimos en búsqueda de integrantes. Somos 3 en el grupo y estamos muy comprometidos con el TP, por eso estamos buscando 2  integrantes que tengan ganas de aprobar y puedan dedicarle tiempo así poder llegar a las entregas holgadamente. Las tareas siempre intentamos repartirlas de manera equitativa, y estamos siempre en contacto por whatsapp.
rpages@frba.utn.edu.ar es mi e-mail.
PD: las bebidas después de aprobar.

**Comment by eguiggiaro** [comment]
Hola,

¿Cómo están?

Tenemos una baja en nuestro grupo, con lo cual, estamos buscando un nuevo integrante! Nos presentamos al checkpoint presencial y venimos encaminados.

Si están buscando grupo, pueden escribirnos a emiliano.guiggiaro@gmail.com

Gracias!!

**Comment by DanielBareiro** [comment]
Hola,  se nos acaban de bajar dos integrantes en nuestro grupo  y estamos buscando nuevos integrantes, les dejo mi mail si alguien esta interesado: danielbarei@hotmail.com.

Muchas gracias!

**Comment by JulianMartinez2797** [comment]
Buenas! Se nos bajo un integrante por lo que vengo a buscar una persona. Dejo el estado del tp:
- Discordiador: esta encaminado, aunque en el ultimo checkpoint nos dimos cuenta por los comentarios del ayudante que vamos a tener un poco de refactor porque casi ni pensamos en los semaforos.
- miRamHQ: es el modulo mas atrasado, pero si tenemos bien organizada la base como para separar tareas.
- iMongoStore: la persona que se nos fue lo dejo practicamente terminado (nos dijo que iba a darnos soporte siempre que haga falta). Pero obviamente vamos a tener mucho laburo ahi a la hora de conectar las cosas con los demas modulos y/o entender el codigo para hacerle cambios.

Les dejo mi mail: julianmartinez2797@gmail.com

Saludos!

**Comment by SantiagoOrlando29** [comment]
Buenass!
Se nos bajó un integrante del grupo así que estamos en busca de otro.
Fuimos el sábado al checkpoint y nos dijo Damián que estamos bien encaminados. La integrante que se bajó estaba con el mongostore y dejó una base ya armada. Probablemente si te sumas al grupo ayudarías más con el mongo junto a otro chico que se está encargando de eso ahora, pero todo es charlable obvio.

Dejo mi mail: sorlando@frba.utn.edu.ar

Saludos!

**Comment by KaterinaCejas** [comment]
Holiss
Estamos buscando 2 personas que se quieran sumar, les dejo mi mail: kcejas@frba.utn.edu.ar

**Comment by MatiasRosales** [comment]
Buenas, estamos buscando 2 integrantes para nuestro grupo
Discordiador: casi terminado, solo falta implementar los sabotajes
Mi-RAMHQ: segmentacion pura sin compactacion. falta la implementacion de paginacion y dump de memoria 
Mongo Store:  falta MD5, ultimos 2 sabotajes de files y la señal SIGUSR1

Necesitariamos gente que ayuden en la paginacion y mongo store. Es posible que el discordiador ya se termine para esta semana

Mi mail: matias.rosales97@hotmail.com

saludos

**Comment by Ignacio-Ferrante** [comment]
Hola, se nos bajaron 2 integrantes y buscamos gente que quiera trabajar. El estado del TP es:
- Discordiador: casi terminado con protocolo de comunicación con ram ya establecido. Falta definir los sabotajes. La planificación funciona
- Mi-Ram-HQ: comunicación con discordiador funcionando. Segmentación casi terminada. Falta la paginación.
- Mongo: falta definir.

**Comment by mpuyol** [comment]
Buenas! Estamos buscando a una persona para completar el equipo, ya que un compañero se nos bajo.
Ya tenemos el discordiador cocinado y la Store encaminada, estamos buscando a alguien que se sume para trabajar en Mi-Ram-HQ, junto con 2 compañeros mas que ya estan empezando el trabajo.
Mi mail de contacto es matipuyol123@gmail.com 
Esperamos que alguien se pueda sumar!

**Comment by DanielBareiro** [comment]
Buenas seguimos buscando dos personas mas para nuestro grupo, tenemos el Discordiador casi listo, le falta la parte de sabotajes, del Mi-Ram-Hq ya esta empezada la paginación y de la segmentación falta compactación, el I-Mongo-Store a definir. Mi mail de contacto es danielbarei@hotmail.com.

**Comment by marciondg** [comment]
Buenas, cómo andan?
Buscamos un integrante para nuestro grupo. Mi mail de contacto es mgarozzo@frba.utn.edu.ar
Saludos!

**Comment by FeroMateo** [comment]
Buenas! Buscamos un integrante para nuestro grupo, cualquier cosa feromateo@gmail.com

**Comment by paulorouss** [comment]
Hola busco grupo , dejo mi mail pavasquez@frba.utn.edu.ar

**Comment by iago64** [comment]
Oficialmente se cierran los cambios en la tripulación. La nave despega en 3... 2... 1...
