### ISSUE TITLE
[Discordiador] Planificación de Tripulantes o Patotas? Conexiones con MiRamHQ

### ISSUE THREAD

**Issue by federiver91** [sisoputnfrba/foro#2071]
Buenas, antes que nada perdón por no respetar el template pero entiendo que es una guía para mantener un orden de consulta, el cual pienso implementar de todas formas.

En general, no me queda claro el ecosistema de Patotas y Tripulantes y cómo juega la planificación de estas dos entidades. Además, no logro ver con claridad como comunicarme con la Memoria. Voy a las preguntas concretas:

Partiendo de la premisa de analogía Patota=Proceso y Tripulante=Hilo...

1) A través de la consola del Discordiador se podrá iniciar más de una Patota? Es decir, van a existir en el sistema más de un Proceso a la vez? Cómo hago para no Hardcodear los IDs de Patotas y Tripulantes (pid y tid, respectivamente) al crearlos?
2) Qué debemos planificar? Tripulantes o Patotas? Puede haber más de una Patota en el mapa / sistema?
3) Cómo se implementa o se lleva a cabo la planificación? Desconozco cómo llevar a la práctica la teoría de Planificación de Procesos y Diagrama de Estados. Son arrays con nombres tipo "READY", "NEW", "EXEC", etc? Es así tan "a mano"? En caso afirmativo, qué estructuras van en esos arrays? Tripulantes? Patotas? Ambas?
4) Cuando inicio una patota y genero los tripulantes, tengo que generar un hilo distinto por cada tripulante indicado por consola? Cómo se generan hilos a demanda en tiempo de ejecución? Qué hago despues con esos hilos? Dónde los guardo? Cómo los administro y qué es lo que tengo que administrar de ellos?
5) Respecto al punto anterior, cada hilo tiene que abrir su propia conexión con MiRamHQ para darse a conocer?
6) Quién le da "vida" a todo el sistema una vez creadas las patotas? Qué módulo comienza la ejecución de las tareas? Discordiador? MiRamHQ? Qué implica dicha ejecución? Es el comando INICIAR_PLANIFICACION el que hace que comiencen a ejecutarse las tareas?
7) La cantidad de tripulantes (hilos) que pueden estar en Ejecución es el grado de multiprocesamiento o grado de multiprogramación? Cuál es el dato que representa el "GRADO_MULTITAREA" del archivo de configuración de Discordiador?
8) Concretamente qué significa que un tripulante (hilo) esté en Ejecución, Ready, New, etc? Cómo se baja ese concepto teórico a tierra? (Similar a pregunta 3)

Por ahora, creo que resolviendo esas dudas tengo un buen punto de partida para, seguramente, próximas dudas que iré tratando.

Sepan disculpar si algunos de los ítems que pregunto son algo básicos, pero realmente (podría tomarse como feedback) me parece que la materia (especialmente el TP, que tiene entidad de materia aparte) asume que el alumnado tiene los conocimientos, capacidades y preparación para llevar a la implementación los conceptos teóricos de la materia y, en realidad, muchos no los tenemos. Y en sí, la búsqueda de la capacitación de esa mera implementación (que debería ser un complemento o una manera de afianzar los conceptos de la cursada, a mi juicio) termina siendo INFINITAMENTE más complejo que la materia en sí y, a la luz de las estadísticas, un filtro de la carrera y una gran desmotivación para los que no tenemos un perfil tan técnico dentro del palo de Sistemas. 

Espero que el último párrafo se pueda tomar constructivamente porque se de todo el empeño y esfuerzo que hace el cuerpo de ayudantes. Está a la vista dado todo el material y el soporte. Pero quizás, tal vez, haya un espacio retrospectivo para analizar si el TP en algún punto no se va de mambo.

Gracias por adelantado!!

**Comment by federiver91** [comment]
Muchas gracias!

En cuanto al punto 3 y 8, sigo en la misma situación que antes de realizar las preguntas. Algo más de info que me pueda orientar? Se implementa con arrays las distintas colas (new, ready, exec, etc) o a qué se refiere esa planificación?

Necesito entender esa parte para tener el punto de partida desde donde los tripulantes van a ejecutar las tareas. Que por cierto, no tengo claro tampoco cómo representar o simular los "tiempos de CPU" que cada tarea conlleva.

Es decir, la ejecución real del programa va a darle un orden a lo que ejecuta y el tiempo que tarda. Pero es tarea nuestra SIMULAR una planificación (orden de ejecución) y además simular el tiempo que tarda cada tarea de cada hilo? Cómo se hace eso? Cómo se simulan esos "tiempos de CPU"? Lo veo en varias partes del enunciado pero no me queda claro, de nuevo, la implementación.

Saludos!

**Comment by iago64** [comment]
Buenas!

Respecto a como implementar las colas de los diferentes estados, puede ser un array (el problema capaz es de que tamaño lo armarías), puede ser una cola, una pila o puede ser la estructura que mas simple te resulte manejar. Te recomiendo que revises las commons para ver si alguna de las estructuras pre armadas no pueden ayudarte a desentenderte de los problemas de por ejemplo crear un array o una cola y simplemente te tengas que enfocar en la lógica de como ordenar por ejemplo los que estan en ready o en la lógica de como saber si le toca seguir ejecutando a uno en exec o si tiene que ser desalojado (por ejemplo por que se le termino el quantum de RR)

Para simular los tiempos de CPU, lo que tenes que hacer es que tu proceso se quede esperando esa cantidad de tiempo para, como bien dice la palabra, _simular_ el tiempo que tardaría una CPU (ya que a velocidad maquina pasaría todo de una y no tendríamos chances de ver nada). Para eso, podes investigar como funciona la función _sleep()_.

Saludos.-

**Comment by lrouillet** [comment]
Buenas! Me sumo a la consulta, particularmente el punto 4.
Por favor corríjanme si me equivoco en alguno de los supuestos. Al momento de iniciar patotas, se consulta a memoria si es posible almacenar las estructuras correspondientes a los procesos (PCB/TCB), y de ser así, estos se generan y entran a la cola de listos. Caso contrario, quedan como un job en la cola de nuevos. Mi pregunta es: La creación del proceso o hilo como tal, es trabajo del discordiador? O pueden crearse procesos desde RAM?
Gracias!

**Comment by iago64** [comment]
Buenas @lrouillet 
1.- Los datos de los estados los tenes en los TCBs que están almacenados en Mi-RAM, pero nada te impide tener una replica en discordiador para simplificar el manejo de las diferentes colas, solo tienen que tener especial cuidado al momento de mantener los datos actualizados en ambos lados.
2.- Si por proceso / hilo te referís a los tripulantes, los mismos viven en el módulo discordiador y se crean mediante el comando CREAR_PATOTA donde le decís la cantidad de tripulantes de la patota.

Saludos.-

**Comment by erangelortega** [comment]
buenas, consulta, los ID de la patota y de los tripulantes se crean en el modulo discordiador y esa info se manda a mi RAM para guardar?

**Comment by iago64** [comment]
@erangelortega como va? 
Hubiera estado genial que esa consulta la hagas en un issue aparte... pero bueno, eso pueden definirlo como quieran, si quieren que mi-ram cree los IDs al momento de guardarlos en sus estructuras y se las avise al discordiador o si quieren que el discordiador los genere y se los diga a Mi-RAM es indistinto.
Lo único que nos importa es que los ids sea diferentes.

Saludos.-

**Comment by iago64** [comment]
@federiver91 te quedo alguna duda o podemos dar por cerrado el post?

**Comment by federiver91** [comment]
Si si, perdon. Lo cierro. 

Saludos y gracias.

**Comment by federiver91** [comment]
Si si, perdon. Lo cierro.

Saludos y gracias.
