### ISSUE TITLE
Dudas sobre Blocks.ims 

### ISSUE THREAD

**Issue by heinHertz** [sisoputnfrba/foro#2072]
Tengo unas dudas sobre el archivo Blocks.ims
En el enunciado, en la hoja 23: 
```
Este archivo será el encargado de almacenar todos los bloques de nuestro File System. Al inicializar el File System, si el mismo no está formateado, deberá crearse el archivo con el tamaño de la cantidad de bloques por el tamaño del bloque.
```
1. que significa que el mismo no este formateado?   

2. que estructura seria conveniente para crearlo al Blocks.ims ? un t_bitarray (porque contiene un char *  y funciones para manipular bits)    o un void *  ?  se que contiene los bloques n, pero tengo dudas de como crearlo. 

3.   si tengo que "inicializar" de cero el Blocks.ims, estaria bien que pusiera todos los bites en 0(cero) con memset o algo parecido ? para como dejarlo en cero todos los bites.

**Comment by iago64** [comment]
Aloha! como va?

1.- Significa que si inician el FS desde 0 van a tener que crear ese archivo blocks.ims, caso contrario si levantan un Fs existente (porque por ejemplo bajan el FS y lo vuelven a levantar) deberian mantenerlo.

2.- Tené en cuenta que en el blocks.ims vas a ir guardando info de los archivos, que bien pueden ser texto como el de las bitácoras o una misma letra, por ejemplo la letra en el caso de los archivos de recursos. Con esto último creo que ya descartas el bitarray no? después si tenes un void* o un char* medio que da lo mismo, total es un puntero a memoria y lo que importa es que puedas hacer los memcpy() correspondientes al espacio que te reservo mmap().

3.- No hace falta, no te olvides que en la realidad los datos de los bloques de un disco no se sobrescriben, si no que simplemente se marcan como vacío y listo.

Saludos.-

**Comment by heinHertz** [comment]
Gracias!
