### ISSUE TITLE
[i-Mongo-Store] Funcionamiento de block.ims y de los demás archivos

### ISSUE THREAD

**Issue by julchat** [sisoputnfrba/foro#2073]
Hola, estaba leyendo la parte del enunciado de i-mongo que se debería contemplar y implementar para la próxima entrega. Revise los issues #2072 y #2056 , que preguntaban algunas cosas del mismo. Pero, lo que me interesaba preguntar acá, es cual es la idea atrás de memcopiar block.ims y como eso produciria distintos efectos a la hora de sincronizar

### 📔 Citas del enunciado/videos

> Internamente, este archivo deberá ser mapeado a memoria y se le realizará una copia sobre la cual se trabajará para lograr simular la concurrencia y asincronismo en las bajadas a disco de los sistemas operativos reales. El tiempo de sincronización hacia el archivo físico de Blocks.ims será especificado por archivo de configuración. Cualquier otra implementación es motivo de desaprobación directa.

### 💭 Mi interpretación

Ok, la idea de hacer mmap() es poder mapear el archivo a memoria porque no esta bueno trabajar reservando la memoria entera para algo como un archivo que puede ocupar mucho, y solo trabajar sobre las partes que necesitamos.
A fin práctico al final lo que tengo es un void* así que medio la magia la hacen por atrás open() y más que nada mmap(), y ya de por si el sistema operativo (linux) sincroniza los cambios que se produzcan en la memoria mapeada que modifiquen el archivo con el archivo en el filesystem en si, pero nosotros, queremos asegurarnos que pase cada cierto tiempo, entonces, con la función msync(), a ese mismo void* que nos dio mmap, le hacemos msync() cada cierto tiempo establecido en el archivo de configuracion.

1) Bien, ahora supongamos que yo en realidad lo que modifique fue a partir del byte número 700 del archivo, podría hacer msync(mapeado + 700)? Conseguiría lo mismo? Ganaría en eficiencia?

Siguiendo, la idea es, para trabajar asincronicamente sobre el archivo, utilizar memcpy(). Haciendo memcpy() cada vez que yo tenga que modificar el archivo me hago una copia la cual **no se sincroniza, y no podría usar el void* destinatario del memcpy para msync()**.

2) Acá no se si tengo que confiar en la magia de msync(), porque, si yo no puedo sincronizar el void* del memcpy(), lo que debería hacer en algun momento es pisar lo del void* original con el que le hice memcpy y le hice cambios. El tema es que esto traería problemas: 
a) antes de pisar, hubo otro acceso que implicó hacer otro memcpy(), entonces ahora, piso el contenido del void* del mmap() con el del primer memcpy(), sincronizo, y que va a pasar si el otro acceso modificó parte de lo que el primer acceso cambió en lo que quedo del mmap()? Al sincronizar podría entender que lo mas nuevo es lo que va a pisar lo demás. Pero supongamos que dividimos lo del mmap() en 3 partes, a las que tanto el acceso A como el B les hicieron memcpy()

Parte 1: Acceso A la escribió, acceso B la leyó
Parte 2: Acceso A la escribió, acceso B la escribió
Parte 3: Acceso A la leyó, acceso B la escribió.

Al querer sincronizar, pegando sobre el primer memcpy() o sin hacerlo (eso no me quedo claro si se hace o no), dependiendo el orden, ¿no podría pasar esto?
Si sincronizo primero la parte del acceso A y luego la del B, lo que me va a quedar va a ser: 
-La parte 1 vieja (porque B fue el ultimo en sincronizar, con datos de un memcpy viejos)
-La parte 2 versión modificación hecha por B (porque B escribió en la misma parte que A escribió, y debería valer lo del último)
-La parte 3 nueva (porque B fue el unico que la modificó)

Y si sincronizo primero B, y luego A

-La parte 1 nueva(porque A fue el unico que la modificó)
-La parte 2 versión modificación hecha por A (porque A escribió en la misma parte que B escribió, y debería valer lo del último)
-La parte 3 vieja (porque A fue el ultimo en sincronizar, con datos de un memcpy viejos)

b) incluso si yo pudiera hacerle msync() a lo del memcpy() (devuelta, no se si lo que está copiado también esta mapeado) se podrían dar estos problemas de sincronización. 

Entonces, esa sincronización y darnos cuenta de que cambió (no solo desde la ultima sincronizacion), es algo que deberiamos manejar nosotros?

Y como duda extra, el enunciado no lo menciona, pero yo no debería seguir la misma lógica de hacer mmap, memcpy, y msync a fines de funcionar con asincronismo tanto para cualquier modificación en superblocks.ims y files.ims? En el caso de la bitácora que es medio como un log capaz se podría simplemente escribir después de un salto de línea y no modificar lo ya establecido

**Comment by iago64** [comment]
Buenas!

En muchas ocasiones, el sobre pensar las cosas lleva a caminos oscuros y siniestros y este es uno de ellos :(
La posta de la posta es que uds nunca van a entender como funciona _mmap()_ o _msync()_ por abajo y nosotros en la cantidad de años que llevamos usandolo (en mi caso desde 2012) jamás nos preocupamos en saber como funciona al detalle, simplemente porque funciona y ya.

La idea principal de levantar el archivo de bloques con mmap() es justamente la de simplificar la administración del mismo y que puedan simplemente jugar con punteros de memoria en lugar de tener que hacer fseek y fwrite como si no hubiera un mañana.
Ahora bien, la joda atras de todo esto es que mmap() cuando haces el cambio no lo baja instantáneamente al archivo (como uno esperaría que pase) si no que lo hace cuando le pinta (o dicho mas académicamente, cuando el sistema operativo le permite realizar la escritura del archivo). 

Ahí es donde aparece nuestra función amiga msync() que lo que hace simplemente es decirle a nuestro programa, yo te hice y yo quiero que te quedes esperando hasta que esto se guarde, cosa que eventualmente puede demorar fracciones de segundo (actualidad) o un par de minutos (como pasaba en los tiempos en los que a los SO les costaba realmente muchisimo tiempo escribir cosas a disco ya que los discos eran infernalmente lentos). 
Algo importante acá, es que msync() te permite tanto decirle *graba este pedacito que acabo de escribir*, como también decirle: sincroniza todo (básicamente pasándole el puntero al inicio del bloque devuelto por mmap() y el size del archivo), entonces esto último es lo que les pedimos en esa sincronización "forzada" que tienen que correr cada cierto tiempo.

Ahora bien, por último, veo que lo que mas te preocupa es el tema de la sincronización, pero ahi es donde viene la parte linda del TP y es que i-mongo Store vas a tener 1 solo y los hilos van a ver el mismo mapeo a memoria (o deberían ver el mismo mapeo a memoria) entonces ahí es donde desaparecen tus problemas de tiempos entre que realiza acciones un tripulante y realiza acciones otro tripulante.

Creo que el issue quedo largo y la respuesta esta por el mismo camino, pero espero que se entienda que la problemática no busca ser tan compleja como la pensaste, de todas formas si hay algo que no te termino de quedar claro por favor no dudes en seguir preguntando.

Abrazo a la distancia!

**Comment by julchat** [comment]
> Ahora bien, por último, veo que lo que mas te preocupa es el tema de la sincronización, pero ahi es donde viene la parte linda del TP y es que i-mongo Store vas a tener 1 solo y los hilos van a ver el mismo mapeo a memoria (o deberían ver el mismo mapeo a memoria) entonces ahí es donde desaparecen tus problemas de tiempos entre que realiza acciones un tripulante y realiza acciones otro tripulante.

Claro, pero entonces cual seria el objetivo de utilizar memcpy()?

**Comment by iago64** [comment]
Basicamente *memcpy()* en esta ecuación entra para leer y escribir en el archivo porque *mmap()* te devuelve tu archivo en "memoria".

Extra: Memoria esta entre comillas porque no trae el archivo completo y lo carga en memoria ram, si no que trae de a partes a medida que se lo vas pidiendo, ya que como dije antes, lo que busca es optimizar (o reducir) los accesos a disco porque es un recurso muchisimo mas lento.

**Comment by julchat** [comment]
Claro sisi eso lo entiendo, pero
1)En el enunciado solo lo menciona para block.ims, no deberia usarlo para los demás archivos también?
2)Siendo A el puntero que me dio mmap(), y B el puntero al que le hice malloc() para usarlo como destinatario en el memcpy:
Andaría bien que yo haga msync() al puntero B? O si o si lo debería hacer en el A, luego de otro memcpy para "escribir" el archivo en el caso de una escritura?

**Comment by iago64** [comment]
1.- Se recomienda para blocks.ims, pero pueden usarlo para todos los archivos, de hecho para el soperblock tambien es buena idea.
2.- Ojo ahí, todas las operaciones de lectura y escritura tienen que ser sobre el puntero que te devolvió *mmap()*, y eventualmente si tenes otro puntero es para por ejemplo unir los bloques o para operar sobre los datos, pero todas las operaciones que afecten al archivo van sobre lo que te devolvio *msync()*, de hecho si vos si le haces *msync()* a un puntero que no sea uno devuelto por *mmap()* va a fallar.

**Comment by julchat** [comment]
Ok gracias! A trabajar entonces
![a trabajar](https://user-images.githubusercontent.com/48997230/118324012-d5086e80-b4d7-11eb-9f82-bc50454e524d.gif)
