### ISSUE TITLE
Dudas sobre Mi-RAM HQ

### ISSUE THREAD

**Issue by Eruizmagliano** [sisoputnfrba/foro#2074]
Hola, leyendo el enunciado, mas concretamente la parte de Mi-RAM HQ me surgieron las siguientes dudas:

1. En la sección donde se explica como implementar la segmentación dice que el espacio de memoria se asigna según los criterios "Best Fit" y "First Fit" y que este criterio esta especificado en el archivo de configuración. Sin embargo, en la parte donde se especifican los campos del archivo de configuración, no hay un campo que corresponda al criterio.
2. No me queda claro si la tabla de segmentos es por Patota o por Tripulante, ya que, si me guío por lo que dice el enunciado entiendo que es uno por Patota, sin embargo, en la ilustración dice "Tabla de segmentos del Trip 1".

### 📔 Citas del enunciado/videos

1.Pags 16 y 21
Para la elección del lugar en el que se va a guardar un nuevo segmento, se deberá verificar si hay algún hueco libre con el tamaño suficiente para almacenar nuestro segmento. En el caso de que haya más de uno, se utilizará uno de los siguientes criterios (definido por archivo de configuración): 

- Mejor ajuste (Best Fit): se coloca el segmento dentro del hueco libre en el que se desperdicie el menor espacio.
- Primer ajuste (First Fit): se coloca el segmento en el primer hueco libre que se encuentre.

Ejemplo de Archivo de Configuración
TAMANIO_MEMORIA=2048
ESQUEMA_MEMORIA=PAGINACION
TAMANIO_PAGINA=64
TAMANIO_SWAP=4096
PATH_SWAP=/home/utnso/swapFile.bin
ALGORITMO_REEMPLAZO=LRU
PUERTO=5001

2. Pag 16.

**Comment by iago64** [comment]
Aloha! Como va?

1.- Si... nos re comimos ese campo, pueden ir agregándolo, eventualmente si lo llaman no se... ALGORITMO_ESPACIO_LIBRE o CRITERIO_SELECCION, no pasa nada, es un cambio mínimo al levantar el archivo de config :)

2.- Es de la **patota**, fue otro pifie nuestro.

Mil gracias por leer el enunciado tan a detalle nos encontraste 2 lindas metidas de pata para la errata 
Abrazo a la distancia!

**Comment by Eruizmagliano** [comment]
Buenísimo, muchas gracias.

Saludos!

**Comment by iago64** [comment]
No se olviden que si la duda queda resuelta pueden cerrar el issue 😉
