### ISSUE TITLE
Consulta enunciado tamaño TCB

### ISSUE THREAD

**Issue by totomolino** [sisoputnfrba/foro#2075]
Buenas, tenia una consulta sobre el enunciado en la parte de Mi-RAM-HQ. 

### 📔 Citas del enunciado/videos

En la pagina 19, dice: 
>El tamaño total de un TCB en memoria es de 17 bytes.

y por lo que tengo entendido uint32_t pesa 4 bytes. Nos dan 5 uint32_t y 1 char, por lo tanto me da 21 bytes. Es asi o el puntero no se suma?

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va? 
Efectivamente, nos quedó viejo de cuando no había dirección lógica del PCB del Tripulante (fue un agregado que hicimos en la última revisión). El tamaño correcto sería 21 bytes. 
Saludos

**Comment by totomolino** [comment]
Buenisimo, gracias por la rapida respuesta.

Saludos
