### ISSUE TITLE
Problemas con código sacado de issues

### ISSUE THREAD

**Issue by heinHertz** [sisoputnfrba/foro#2076]
Hola tengo un problema con un código copiado de los issues,  el problema es que no lo puedo encontrar el  issue , creo que lamentablemente estaba en una imagen, o tenia algún formato,  creo que no estoy seguro.
acá va el codigo:
```
int	string_array_lines_count(char** str_arr)
{
	int lines = 0;
	if(!str_arr) return lines;

	void _accumulate_lines(char* element)
	{
		lines++;
	}
	string_iterate_lines(str_arr, _accumulate_lines);

	return lines;
}
```

el problema es que Vscode, donde estoy haciendo el tp me tira error "SE ESPERABA ;" lo marca justo abajo de
 "void _accumulate_lines(char* element)"
probé moviendo la función de varias formas pero sigue el error.

![image](https://user-images.githubusercontent.com/37560557/118166566-00b62680-b3fc-11eb-9340-0b13452985a0.png)

1. ¿Que podria hacer para resolverlo?

Igualmente esta función puede ser reemplazada por otra, la estoy usando para leer la cantidad de "numero-barra-numero" que tiene POSICIONES_SABOTAJE=[1|1, 2|2, 3|3, 4|4, 5|5, 6|6, 7|7]  del ARCHIVO de Configuración de Imongo del TP en un char**   que esta dentro de una estructura que cree imongo_config

char** list_posiciones_sabotaje;     

lo estoy leyendo asi:  
imongo_config->list_posiciones_sabotaje = config_get_array_value(config, "POSICIONES_SABOTAJE");
lo que intento hacer es a) leer la cantidad de "números con barrita vertical"  y
b) separar esos números de alguna forma de la barrita

2 . ¿Qué otra forma podría utilizar para leer POSICIONES DE SABOTAJES ? convirtiendo a int? el tema es que tengo la barrita esa que esta en el medio,

gracias.

**Comment by RaniAgus** [comment]
¡Buenas! Como se menciona en [este comentario](https://github.com/sisoputnfrba/foro/issues/1878#issuecomment-695127301) del thread de Visual Studio Code, el editor no reconoce las nested functions (las funciones que se definen en el contexto de otra función), ya que no es una feature del estándar de C, sino que es un agregado de gcc. De todas formas, al compilar con gcc el código no tira error al usarlas, eso es lo importante.

Para más info sobre cómo funcionan las nested functions (son muy útiles para pasárselas a varias funciones de las commons), te recomiendo este video: https://www.youtube.com/watch?v=1kYyxZXGjp0

Ojo con este mínimo detalle:
```c
int lines = 0;
if(!str_arr) return lines;
```
Ese `if` hace que la función no rompa si recibe NULL (un valor no válido), y probablemente no quieras ocultar ese error en caso de que ocurra teniendo en cuenta que `config_get_array_value()` devuelve NULL si no se encuentra la key, pero devuelve array vacío si la key es `"[]"`.

¡Saludos!

**Comment by iago64** [comment]
Buenas!

Algo extra sobre el tema de VS Code, nosotros temporalmente no tenemos tanto soporte para vs code, básicamente porque fue un ex-alumno el que armo el post de como usarlo, nos pareció útil y lo dejamos como alternativa, pero la posta al final del día la tiene GCC, si al compilar anda, es como lo que comento Agus, un problema del editor que no reconoce algo.

Abrazo a la distancia!

**Comment by RaniAgus** [comment]
PD: El código es de https://github.com/sisoputnfrba/foro/issues/1892 y https://github.com/sisoputnfrba/so-commons-library/issues/118 
Ya me parecía que lo había visto antes (?)

**Comment by heinHertz** [comment]
Gracias!
