### ISSUE TITLE
No nos deja compilar los proyectos en eclipse

### ISSUE THREAD

**Issue by octavioramirez12** [sisoputnfrba/foro#2077]
Buenas, teníamos una duda con nuestro grupo porque teníamos los tres módulos dentro del mismo proyecto, y al separarlos en proyectos diferentes ya no nos deja compilar.
Lo hicimos desde File->Open Projects from File System
Cambiamos el workspace, hicimos refresh, rebuild index, clean, y ninguno funcionó. Investigamos en google pero hasta ahora no pudimos encontrar la solución.

**Comment by iago64** [comment]
Buenas! como va?

Que error les esta dando? 
Porque así en el aire podemos estar tirando alternativas hasta que termine la pandemia del covid y seguir sin adivinar.

Saludos.-

**Comment by sofiabarreneche** [comment]
![2021-05-15 (2)](https://user-images.githubusercontent.com/62484268/118374381-2e34d880-b592-11eb-8b37-719875326d2d.png)
este error nos tira!

**Comment by iago64** [comment]
Ahí el error es que no esta encontrando el binario para ejecutarlo, lo que necesitaría es saber que error les da al momento de compilar.

**Comment by iago64** [comment]
@octavioramirez12 @sofiabarreneche alguna novedad? pudieron probar algo? pasaron por soporte y lo resolvieron?

**Comment by iago64** [comment]
Buenísimo cerramos entonces el tema 😄
