### ISSUE TITLE
Inicialización de file system

### ISSUE THREAD

**Issue by gchimento** [sisoputnfrba/foro#2078]
Hola, qué tal? Tengo una consulta sobre el enunciado.

Al momento de iniciar por primera vez el i-Mongo-Store voy a tener que crear todos los archivos correspondientes al file system? O puede suceder que me den archivos que ya tienen algún contenido y necesito leerlo (como si estuviese cargando una partida ya empezada). En relación a esto, no me queda muy claro cuándo es que se levanta un FS ya existente.

Gracias!

**Comment by iago64** [comment]
Buenas! como va?

Lo que deberían hacer al iniciar el i-Mongo Store es verificar si tienen los archivos de superblock.ims y blocks.ims y si existen asumen que el FS esta creado previamente, si no existen, tienen que agarrar y crearlos.
Para crear un FS desde cero tienen que pedir los datos del tamaño del bloque y la cantidad de bloques, eso pueden hacerlo como mas les guste.

Dato extra, nosotros de entrada no les vamos a dar ningún FS creado al momento de la entrega pero si les vamos a pedir que bajen el FS y lo vuelvan a levantar y todos los archivos sigan estando.

Saludos.-

**Comment by heinHertz** [comment]
Hola 
``` 
Dato extra, nosotros de entrada no les vamos a dar ningún FS creado al momento de la entrega pero si les vamos a pedir que bajen el FS y lo vuelvan a levantar y todos los archivos sigan estando.
```
1 Hola que significa "que bajen el FS y vuelvan a levantar"  ?   Bajen de "descargar" ?

**Comment by RaniAgus** [comment]
Buenas, @heinHertz 
> 1 Hola que significa "que bajen el FS y vuelvan a levantar" ? Bajen de "descargar" ?

Se refería a la persistencia: que se tiene que poder cortar la ejecución del módulo con Ctrl+C y después volverla a iniciar sin perder los datos guardados (como en un File System real). Saludos

**Comment by heinHertz** [comment]
Ah Gracias. 
Tengo dudas sobre este tema:

 1 la idea de cortar el programa con CTRL + C en realidad es buscar si se "recupera" el sistema con un archivo corrupto ? pero no importa si no los datos están bien guardados?

2 si a prioridad es que estén bien guardados; ¿hay alguna forma de ejecutar una "rutina de código " justo despues de cuando se hace CRTL +C  ?,  o sea si alguien corta el programa y justo se esta haciendo un mapeo,  tengo dudas acerca de la seguridad de los datos con este tipo de test, tampoco se que sucede con algún proceso en ejecución al cortarlo.

Muchas gracias.

**Comment by gchimento** [comment]
Gracias por las respuestas! Tengo una duda con lo siguiente:

> Lo que deberían hacer al iniciar el i-Mongo Store es verificar si tienen los archivos de superblock.ims y blocks.ims y si existen asumen que el FS esta creado previamente, si no existen, tienen que agarrar y crearlos.
> Para crear un FS desde cero tienen que pedir los datos del tamaño del bloque y la cantidad de bloques, eso pueden hacerlo como mas les guste.

El archivo de superbloque no debería venir dado siempre? Y yo asumir que ya existe, porque de no ser así no tengo de donde sacar la cantidad ni el tamaño de los bloques para crear el blocks.ims.

> Dato extra, nosotros de entrada no les vamos a dar ningún FS creado al momento de la entrega pero si les vamos a pedir que bajen el FS y lo vuelvan a levantar y todos los archivos sigan estando.

Y por otro lado, el caso en el que daríamos de baja el FS para volver a levantarlo es solamente con los sabotajes? O el Ctrl + C y volver a iniciar el módulo para ver si recupera los datos es algo que puede suceder en cualquier momento?

Gracias nuevamente!

**Comment by iago64** [comment]
@heinHertz 
1- Cortarlo con Ctrl + C simplemente lo cierra, y despues cuando vuelve a iniciar checkea si tiene los archivos y levanta sin hacer ninguna comprobación, los datos están como quedaron al momento de cerrarse.
2-  Eventualmente si quieren cerrar su programa de forma "bonita" pueden capturar la señal SIGTERM que es la que envía Ctrl + C, pero no es necesario.

@gchimento 
El archivo de superbloque no va a venir siempre, eventualmente como te comente antes, pueden pedirlos por consola o pueden agregar esos valores en el archivo de config.
Para los sabotajes justamente no les vamos a bajar el FS, el bajarlo y volverlo a levantar va a ser con Ctrl + C, ya que la idea es que si por ejemplo vienen ejecutando pruebas con RR y queremos cambiar a FIFO, no queremos capaz recrear todo el FS desde cero si no que queremos aprovechar por ejemplo los archivos de recursos. El tema de la recuperación de errores es SOLO cuando se lo pide un tripulante luego de que se envía la señal de sabotaje.

Abrazo a la distancia!

**Comment by gchimento** [comment]
Buenísimo, por mi parte está aclarado así que muchas gracias! No cierro por si la otra persona tiene dudas todavía.

**Comment by heinHertz** [comment]
Aclararon mis dudas.  
Gracias !!!!
