### ISSUE TITLE
Duda sobre el Quantum en RR y cuando interrumpir al hilo

### ISSUE THREAD

**Issue by matiasfdevecchi** [sisoputnfrba/foro#2079]
Buenas, surgió en el equipo un debate sobre RR y el Quantum.

La pregunta general sería: Cuando interrumpir al hilo? En el momento exacto que se le acaba el Quantum o cuando termina de realizar la instrucción?

En el equipo tenemos dos opiniones:
1. Un hilo no puede ser interrumpido hasta que termina de ejecutar una instrucción. Por ende el tripulante no puede ser interrumpido hasta que no termina la tarea
2. Un hilo puede ser interrumpido en cualquier momento, incluso en mitad de una instrucción y este luego retomará donde se quedó. Por ende, el tripulante es interrumpido apenas se acaba el Quantum, y si la tarea era de 15s y le quedan 10s, los continuará luego

**Comment by iago64** [comment]
Buenas!

Amíguense con el concepto de *Keep It Simple*, controlen el quantum después de ejecutar cada tarea, si llega a 0 desalojan, si están con un valor mayor a cero ejecutan otra tarea 😄 

Saludos.-

**Comment by matiasfdevecchi** [comment]
Perfecto, quedó clarísimo respecto al quantum.
Si hay un sabotaje, tenemos que cortarlo apenas se inicia el sabotaje o tenemos que esperar a que termine la tarea?
Si hay que cortarlo apenas inicia el sabotaje, debe retomar su tarea como estaba o iniciarla de cero?
Siguiendo el KISS, sería mejor esperar que termine la tarea

**Comment by iago64** [comment]
Buenas!

Con los sabotajes tienen que esperar a que termine el ciclo de CPU y ahí bloquear. La tarea completa no tiene sentido ya que puede que sea por ejemplo que llego al lugar y esta esperando a que termine la tarea y pueden ser varios ciclos de CPU.

Saludos.-

**Comment by matiasfdevecchi** [comment]
Ok gracias. Fuimos a soporte y también nos dijeron que la tarea hay que continuarla como quedó. Si eran 15 ciclos de CPU y resolviste 10, cuando se desbloquea resuelve los 5 restantes.

**Comment by mauriciomartin92** [comment]
Buenas!!!

Perdón que active el issue, pero no me queda del todo claro el consumo del QUANTUM en  RR y cuando devolverlo a READY  al tripulante (si corresponde).

Caso ejemplo, bien explicito; (RR de Q=5)
tripulante 1 en posición (0,0) en READY.
tripulante 2 en posición (0,0) en READY.

tarea 1 --> JUGAR;3;3;5
tarea 2 --> CORRER;3;3;1

tripulante 1 realiza tarea 1;
debe consumir 6 ráfagas de CPU (por movimiento) +  5 ráfagas de CPU (por realización de tarea) = 11 ráfagas de CPU. 

Entonces:
En EXEC consume los 11 ciclos de CPU(5+5+1), y como no le sobró  Q para la próxima tarea lo envío a READY.
Y luego sigue ejecutando el tripulante 2.

Esta secuencia está correcta? Gracias.

Saludos.
Mauricio.

**Comment by RaniAgus** [comment]
¡Buenas! Es _igual_ que como se explica en la teoría: cuando ocurre el fin de quantum, se devuelve al proceso a la cola de READY y luego se extrae el siguiente. Si no hay procesos en READY, ocurre lo que explicó Dami en #2215 .

Por lo tanto, en este caso vos tenés dos tripulantes: uno en EXEC (T1) y uno en READY (T2). Luego de ejecutar **5** de los 11 ciclos que tiene para completar la tarea, T1 es desalojado por fin de quantum. Luego de eso, como READY es una cola FIFO, T2 tiene más prioridad, por lo que pasa a EXEC y ejecuta hasta ser desalojado por fin de quantum y así.

Recordá que el planificador solo planifica el uso de CPU, no "conoce" lo que ese proceso vaya a ejecutar.

Saludos

**Comment by RaniAgus** [comment]
En definitiva, para que quede más claro, desde el punto de vista del planificador el ejemplo que vos diste debería tener el mismo comportamiento que un ejercicio así:
| Tripulante | CPU |
|-|-|
| T1 | 12 |
| T2 | 12 |

**Comment by mauriciomartin92** [comment]
Buenas @RaniAgus! Primero gracias por responder.

Segundo, sinceramente es así como lo venía pensando, pero me desorientó (seguramente porque no lo entendí bien) un poco el comentario de @iago64 de este mismo issue, que me llevó a cambiar la forma de verlo.

**Capaz debí empezar por acá:**
Cito:
"Amíguense con el concepto de Keep It Simple, controlen el quantum después de ejecutar cada tarea, si llega a 0 desalojan, si están con un valor mayor a cero ejecutan otra tarea 😄"

Si controlo el quantum después de ejecutar me pierdo de cortar al tripulante en su ultima ráfaga disponible de QUANTUM (en caso de que Q<Rafagas de tarea).

Pero a su vez considero que hay algo "valioso" en ese comentario que me estoy perdiendo.

Saludos.

**Comment by iago64** [comment]
Buenas! Mi comentario venia asociado a que estaban hablando de tiempos en segundos y acá nosotros establecimos la marca de quantums, donde 1 quantum = 1 ciclo de CPU, por eso decía que controlen las cosas después de ejecutar el ciclo de CPU.
1 quantum al final de cuentas es:
El desplazamiento de 1 "casillero"
El completar 1 ciclo de CPU de 1 tarea en exec.

Lo valioso es que no tienen que complicarsela con intentar cortar cosas en el medio de esas acciones (no hace falta cortar un movimiento a la mitad o cortar el ciclo de CPU para expulsar el tripulante)
Saludos.-

**Comment by mauriciomartin92** [comment]
Buenas Dami,

claro, entiendo, el quantum sería lo más "atómico". Gracias.

Saludos!

**Comment by iago64** [comment]
Bueno, resueltas las dudas, volvemos a cerrar el issue :)
