### ISSUE TITLE
Dudas sobre el mapa

### ISSUE THREAD

**Issue by matiasfdevecchi** [sisoputnfrba/foro#2080]
Buenas, como va?
Respecto al mapa, tenemos que imprimir el ID de cada tripulante para reconocerlo o podemos poner un caracter aleatorio? Esto surge debido a que con la librería sugerida no podemos repetir caracteres. Entonces si tenemos el ID 1 y 10, estamos repitiendo el 1.

Saludos

**Comment by iago64** [comment]
Buenas! como va?

Puede ser un caracter aleatorio, de ultima cuando se listan los tripulantes pueden agregar extra el caracter que lo representa en el mapa.

Como consejo teniendo en cuenta que tenemos 26 letras (sin contar la Ñ) y podemos contar además con las mayúsculas tendríamos 52 posibles caracteres para los tripulantes... no quiero hacer spoiler de algo que no va a venir hasta dentro de 2 meses, pero ni en pedo nos da la vista para seguir 56 letritas en pantalla 😉 

Abrazo a la distancia!
