### ISSUE TITLE
Tabla de segmentos y páginas

### ISSUE THREAD

**Issue by matiasimartin** [sisoputnfrba/foro#2081]
Tengo una duda, la tabla de segmentos o de páginas va en la memoria? O las tenemos como una estructura administrativa en el módulo?

>Para Mi-RAM HQ, se almacenarán los PCB’s, los TCB’s y sus respectivas instrucciones, es decir, solamente se utilizaran dos segmentos por patota (uno para el PCB y otro para las tareas) y uno para el tripulante (para almacenar el TCB). Para las instrucciones, las cuales no tendrán un tamaño fijo, se almacenarán en memoria principal cuando sean recibidas.

Mas que nada para confirmar. Porque dice que son solo esos 2 segmentos mas n segmentos de tripulantes.

**Comment by iago64** [comment]
Aloha!

Las Tablas de segmentos y/o tablas de páginas van en una estructura aparte, la memoria que reservan es solo para los datos.

Abrazo a la distancia!

**Comment by matiasimartin** [comment]
Muchas gracias!
