### ISSUE TITLE
Archivo de configuracion del modulo Mi-RAM incompleto

### ISSUE THREAD

**Issue by tbosnic** [sisoputnfrba/foro#2082]
El enunciado indica que en caso de que la administración de memoria del modulo sea con segmentación, el criterio utilizado será Mejor Ajuste o Primer Ajuste, el cual se pasara por archivo de configuración. Sin embargo, en el ejemplo de archivo de configuración no esta incluido el criterio de administración de memoria. 

### 📔 Citas del enunciado/videos

ENUNCIADO:
Para la elección del lugar en el que se va a guardar un nuevo segmento, se deberá verificar si hay algún hueco libre con el tamaño suficiente para almacenar nuestro segmento. En el caso de que haya más de uno, se utilizará uno de los siguientes criterios (definido por archivo de configuración): 

- Mejor ajuste (Best Fit): se coloca el segmento dentro del hueco libre en el que se desperdicie el menor espacio.
- Primer ajuste (First Fit): se coloca el segmento en el primer hueco libre que se encuentre.

EJEMPLO ACTUAL DE ARCHIVO DE CONFIGURACION:

TAMANIO_MEMORIA=2048
ESQUEMA_MEMORIA=PAGINACION
TAMANIO_PAGINA=64
TAMANIO_SWAP=4096
PATH_SWAP=/home/utnso/swapFile.bin
ALGORITMO_REEMPLAZO=LRU
PUERTO=5001

### 💭 Soluciones posibles

Agregar el campo, tipo y descripción del criterio en el ejemplo de archivo de configuración.

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va? Como comentamos en #2074, nos faltó agregar ese campo, para la próxima errata ya estará corregido. Mientras tanto, pueden irlo agregando si lo necesitan. Saludos.

**Comment by ncoen97** [comment]
Cierro por duplicado
