### ISSUE TITLE
Dudas sobre I/O

### ISSUE THREAD

**Issue by SantiagoIvan** [sisoputnfrba/foro#2083]
Buenas ! No me queda muy claro el tema de las Entrada/Salida. 

1- Si es una tarea de entrada/salida la que tiene que realizar el tripulante, se queda en la cola de bloqueados tantos ciclos por más que ya haya otros tripulantes alli? Es decir, no sucede que tengo a la cola de bloqueados y se van desbloqueando de a 1 comenzando por el que llegó primero sino que todos los que están en esta cola, permanecen allí x ciclos de cpu, entendi bien?

2- La posición de cada tripulante tengo que solicitarla a Memoria antes de realizar algun movimiento o puedo guardarla en una estructura administrativa? Porque sino tengo que realizar primero una llamada a memoria para pedir la posicion, hacer algunas cosas y dsp otra llamada a memoria mas para actualizar el valor.

3- Si hay varios tripulantes en una misma posición realizando justo la misma entrada/salida no importa, o si? Porque en ese caso voy a tener una cola de E/S por cada tipo de E/S que tenga. O tal vez Imongo se encarga de la sincronizacion de eso para que no se terminen pisando con la misma tarea.

**Comment by gastoncastineira** [comment]
1- No sé si entendiste bien porque yo no te entendí bien. Si es como creo que es, está bien lo que decís, Los tripulantes tienen tiempos de entrada/salida que son independientes de los tiempos de entrada/salida de otros tripulantes
2- Pensá lo que pasa en la teoría. El planificador te planifica los procesos que tienen asociados su PCB y TCBs, que es donde guardan toda la información necesaria. ¿Dónde se almacenan esas estructuras y a quién se las va a pedir el planificador? El resultado esperado en el TP es el mismo :P
3- No debería importar, no. El File system no se tiene que bloquear para la escritura de un único archivo

**Comment by iago64** [comment]
@SantiagoIvan te quedo alguna duda después de la respuesta de Gaston?

**Comment by SantiagoIvan** [comment]
Nop, perdon, cierro issue
