### ISSUE TITLE
Duda con las tareas

### ISSUE THREAD

**Issue by matiasimartin** [sisoputnfrba/foro#2084]
>Las tareas deberán respetar el utilizar un delimitador para los strings y no deberán utilizar formatos numéricos para los tiempos, posiciones, etc, quedando todo como un string. Tampoco está permitido agregar tamaños ni parámetros adicionales a las tareas.

No entiendo bien esta parte del enunciado.
Las tareas tienen que almacenarse **todas** como un solo string, separando cada tarea con algún símbolo?
Ej: tengo 3 tareas, las guardaría así: 
"GENERAR_OXIGENO 12;2;3;5|CONSUMIR_OXIGENO 120;2;3;1|GENERAR_COMIDA 4;2;3;1" 
Siendo el delimitador "|"

**Comment by gastoncastineira** [comment]
Es exactamente eso, sí. Importante que el delimitador sea un único carácter porque vamos a hacer las pruebas con eso en mente

**Comment by matiasimartin** [comment]
Gracias!
