### ISSUE TITLE
Dudas sobre como empezar a modelar discordiador

### ISSUE THREAD

**Issue by CeciliaSangineto** [sisoputnfrba/foro#2085]
Hola! Estuve leyendo el enunciado y quería consultar si esta bien como pensar el inicio de este modulo en base a lo que dice. Con dudas también sobre como hacer algunas cosas.

1_  **Al iniciar el proceso, el mismo realizará las conexiones necesarias para su funcionamiento** 
Es necesario levantar un servidor también? Entiendo que el Discordiador es cliente de MiRamHQ Y IMongo pero no me queda claro si es necesario un servidor en el mismo.
 **y generar las estructuras administrativas necesarias para poder planificar los estados de los diferentes tripulantes** (colas new, ready, exec, block y exit). Las puedo definir de manera global como listas? (t_list)

2_ **Administración de los tripulantes. Cada tripulante, al iniciarse, comenzará sus tareas de preparación.**
Cada vez que se crea un tripulante se crea un hilo por tripulante? Sobre la implementación de estos hilos a demanda, lo pensé agarrando la cantidad de tripulantes ingresada por consola en iniciar_patota, y hacer un for creando esa cantidad de hilos, esto es correcto, serían hilos a demanda? No me queda del todo claro como implementar estos hilos a demanda. 
El tripulante se crea en el momento que mando un iniciar_patota a la consola del discordiador? Entiendo que cuando se crea el hilo de tripulante, el mismo estaría en estado new, hasta que finalice sus tareas de preparación.
**Una vez que se encuentre listo, le informará al discordiador de dicha situación.**
Como le avisas a discordiador que te encentras listo? No entiendo que es lo que hay que hacer.

3_ Un tripulante pasa de estado new a ready cuando se terminan esas tareas de inicializacion?

desde ya gracias y saludos!

**Comment by gastoncastineira** [comment]
> Es necesario levantar un servidor también?

Ojo al piojo. En la charla de servidores y sockets que tenemos en el canal comentamos los requisitos que tiene que cumplir un módulo del TP para ser considerado un servidor:
- Atender muchas conexiones
- Seguir vivo ante una eventual caída de los clientes
- **NO** ser el responsable de iniciar la conexión
Como recordatorio también, las conexiones son bidireccionales, por lo que no debería conectarse un servidor a su cliente para darle la respuesta de su solicitud
Con esas cosas en mente, bajo mi criterio, no debería ser necesario iniciar un servidor ahí.

> Las puedo definir de manera global como listas? 

Pueden manejarlo como gusten

> Cada vez que se crea un tripulante se crea un hilo por tripulante?

Sí

> serían hilos a demanda?

Sí * 2

> El tripulante se crea en el momento que mando un iniciar_patota a la consola del discordiador? Entiendo que cuando se crea el hilo de tripulante, el mismo estaría en estado new, hasta que finalice sus tareas de preparación.

Sí * 3, vamos en racha

> Un tripulante pasa de estado new a ready cuando se terminan esas tareas de inicializacion?

Sí * 4

Cualquier duda que te surja volvé a preguntar. Al quinto 'sí' te ganás un premio
