### ISSUE TITLE
[I-Mongo-Store] Almacenamiento en files y bitácora

### ISSUE THREAD

**Issue by julchat** [sisoputnfrba/foro#2086]
Hola, duda de como van a estar almacenados files y bitácoras

> Files
> En esta carpeta se almacenará la metadata para la reconstrucción de los distintos archivos que se crearán en el sistema. Estos archivos simularán ser un contenedor de recursos, se llenarán con un mismo caracter.
> Para esto se almacenará un archivo de metadata por cada archivo existente en el sistema que contendrá:
> El tamaño del archivo expresado en bytes
> La cantidad de bloques del archivo
> La lista de bloques que lo conforman
> El caracter con el cual se llena el archivo
> MD5 del archivo, deberá actualizarse cada vez que se realicen modificaciones en el mismo.
> La File metadata de los archivos deberá encontrarse en: [Punto_Montaje]/Files
> 

En nuestro filesystem y en la carpeta de Files, vamos a tener muchos de estos archivos que representan la metadata de un archivo.

Mi primera pregunta sería: ¿Puedo almacenar los campos de la siguiente forma?

Tamaño del archivo: entero sin signo de 4 bytes
Cantidad de bloques del archivo: entero sin signo de 4 bytes
Que bloques la conforman: char* limitado con \0 al final
El caracter que contiene el archivo: char
MD5: char* limitado con \0 al final
 
Y obviamente, al leer el archivo, interpretarlo en ese formato
O debería almacenar todo en formato ASCII?

Segundo, las bitácoras.ims también son muchos archivos de metadata de otros archivos, puedo implementar la siguiente estructura?:

Tamaño del archivo: entero sin signo de 4 bytes
Cantidad de bloques del archivo: entero sin signo de 4 bytes
Que bloques la conforman: char* limitado con \0 al final
**ID del tripulante: entero sin signo de 4 bytes**

Y como última cosa, entonces quedaría claro que hay dos tipos de bloques: aquellos que pertenecen a un archivo de recursos (oxígeno, comida) y aquellos que pertenecen a un archivo de bitácoras (de un tripulante). Los primeros en su metadata tienen un MD5 porque interesa recuperarlos, mientras los segundos como probablemente sea algo viejo no. Los archivos de bitácoras sería bastante cómodos llenarlos en ASCII como si fueran un log. En cambio, en los archivos de recursos, lo que voy a tener es ocasionalmente el caracter de llenado y el resto del archivo con caracter nulo, o debería ir modificando el tamaño del archivo en base a cuantas unidades del recurso hay actualmente?

Gracias

**Comment by iago64** [comment]
Buenas! como va?

1.- El formato es el definido en el enunciado, y justamente les definimos la metadata de esa forma para poder llegar a automatizar si es necesario el tema de los sabotajes. Como comentario al pasar, por si no lo notaste, esos archivos se parecen a los archivos de config 😉 

2.- las bitácoras son igual que los files pero con menos campos, lo diferente es el contenido 😉 

3 (y último si no le pifie).- Los bloques tienen contenido independientemente de a quien pertenezcan, la diferencia es que los bloques de los recursos van a estar todos llenos con un caracter único y los de las bitácoras van a tener texto variado, en ambos casos los van a poder llenar con texto. Lo importante es que no te olvides que el blocks.ims tiene el tamaño de CANTIDAD_BLOQUESxTAMAÑO_BLOQUES.

Saludos.-

**Comment by julchat** [comment]
> 1.- El formato es el definido en el enunciado, y justamente les definimos la metadata de esa forma para poder llegar a automatizar si es necesario el tema de los sabotajes. Como comentario al pasar, por si no lo notaste, esos archivos se parecen a los archivos de config 😉

Claro, a lo que voy: ¿se tienen que si o si plantear como archivos de texto o podría representar a, por ejemplo, un tamaño de 120000 como si fuera un entero (en vez de los 6 caracteres que me ocuparía usar el protocolo ASCII, necesitaría bastantes menos). 

> 2.- las bitácoras son igual que los files pero con menos campos, lo diferente es el contenido 😉

> Asimismo, la bitácora de cada uno de los tripulantes del sistema será guardada dentro del File System en una carpeta aparte pero siguiendo el mismo formato de los archivos comunes, esto quiere decir que cada bitácora tendrá un valor de SIZE y la lista de BLOCKS que la conforman y estos archivos se encontraran dentro de un path específico dentro de nuestro file system.

Claro, como plantee en la tercera pregunta, no tendrían ni caracter de llenado ni MD5 no?

> 3 (y último si no le pifie).- Los bloques tienen contenido independientemente de a quien pertenezcan, la diferencia es que los bloques de los recursos van a estar todos llenos con un caracter único y los de las bitácoras van a tener texto variado, en ambos casos los van a poder llenar con texto. Lo importante es que no te olvides que el blocks.ims tiene el tamaño de CANTIDAD_BLOQUESxTAMAÑO_BLOQUES.

Claro, pero en el último bloque de recursos podría pasar que tenga menos caracteres de llenado del carácter único que el tamaño del bloque, debido a que logicamente (no fisicamente, debido a que TODO el bloque es del archivo), los contenidos del mismo terminan antes del fin del bloque. Si es así, que pasa con el resto de los bytes que quedaron en el bloque? No los podría poner como caracter de llenado. ¿Les asigno un valor especial? ¿Los dejo con el que ya tengan? (esta opción me podría traer un problema si justo uno de los bytes que ya estaban de antes justamente corresponde al de un caracter de llenado) ¿Agrego un separador que indique el final del archivo?

**Comment by iago64** [comment]
Buenas!
Claramente estaba mas en automático de lo que pensaba 😢 

> se tienen que si o si plantear como archivos de texto o podría representar a, por ejemplo, un tamaño de 120000 como si fuera un entero
Si, justamente la idea de que sean archivos de texto y tan similares a los configs de las commons es para que podamos automatizar las cosas sin tener que entender que cosas hizo cada grupo por separado.

Bitacoras:
>no tendrían ni caracter de llenado ni MD5 no?
Efectivamente, solo tienen size y la lista de blocks :)

>Claro, pero en el último bloque de recursos podría pasar que tenga menos caracteres de llenado del carácter único que el tamaño del bloque, debido a que logicamente (no fisicamente, debido a que TODO el bloque es del archivo), los contenidos del mismo terminan antes del fin del bloque. Si es así, que pasa con el resto de los bytes que quedaron en el bloque? No los podría poner como caracter de llenado. ¿Les asigno un valor especial? ¿Los dejo con el que ya tengan? (esta opción me podría traer un problema si justo uno de los bytes que ya estaban de antes justamente corresponde al de un caracter de llenado) ¿Agrego un separador que indique el final del archivo?
Se te va a dar el caso de que vas a tener por ejemplo de un bloque de 100 bytes ocupados 50 y esta bien, vas a poder saber hasta donde leer por el campo size del archivo que tiene la metadata.

Saludos.-

**Comment by julchat** [comment]
Joya! Gracias y saludos!
