### ISSUE TITLE
Duda sobre descripción de las tareas ConsumirOxígeno y ConsumirComida del Anexo 2

### ISSUE THREAD

**Issue by int0x80-sys** [sisoputnfrba/foro#2087]
Buenas.

Tengo una duda respecto sobre uno de los pasos que se especifica en el Anexo 2 en las tareas de _Consumir_Oxígeno_ y _Consumir_Comida_:

_En Consumir_Oxígeno_

>1. Verificar que exista un archivo llamado Oxigeno.ims en el i-Mongo-Store.

>2. _**Si no existe informar que no existe el archivo y finalizar la tarea.**_

>3. Eliminar tantos caracteres de llenado del archivo como indique el
parámetro CANTIDAD. En caso de que intenten eliminarse de más, dejar
el archivo completamente vacío e informar por log que se quisieron
eliminar más caracteres de los existentes.

_En Consumir_Comida_

>1. Verificar que exista un archivo llamado Comida.ims en el i-Mongo-Store.

>2. _**Si no existe informar que no existe el archivo y finalizar la tarea.**_

>3. Eliminar tantos caracteres de llenado del archivo como indique el
parámetro CANTIDAD. En caso de que intenten eliminarse de más, dejar
el archivo completamente vacío e informar por log que se quisieron
eliminar más caracteres de los existentes.

Cuando se menciona en el paso 2 tanto de _Consumir_Oxígeno_ como de _Consumir_Comida_ que se debe informar y  finalizar la tarea. ¿Quiere decir que tenemos que informarle al tripulante que el archivo no existe y que, por lo tanto, no debería bloquearse?¿O solo informamos con un log en el I-Mongo-Store?

Gracias y saludos 👋

**Comment by iago64** [comment]
Buenas! como va?
Muy buena pregunta che! Se tienen que bloquear igual, ya que el tiempo simula la entrada salida completa (independientemente de si existe el archivo o no)
El informarlo lo tienen que hacer por el log del i-Mongo Store.

Saludos.-

**Comment by int0x80-sys** [comment]
Genial. Gracias por la respuesta.

Saludos 🚀
