### ISSUE TITLE
Duda con Primer Ajuste en Segmentacion Pura

### ISSUE THREAD

**Issue by RodrigoLista** [sisoputnfrba/foro#2090]
Buenas. Tengo una consulta respecto al criterio First Fit o primer ajuste. El enunciado dice lo siguiente:

> Primer ajuste (First Fit): se coloca el segmento en el primer hueco libre que se encuentre.

Me surgen dos formas de resolución:

1) Si me baso en lo que dice explicitamente, podría seleccionar cualquier segmento que se encuentre libre.
2) Ahora, si me baso en lo teórico, según el libro Stallings, dice que comienza a analizar la memoria desde el **_principio_** y escoge el primer segmento disponible que sea suficientemente grande.

Entonces, a la hora de la implementacion en el tp, podemos hacerlo según el razonamiento 1, o si o si hay que llevar un control para por cumplir exactamente con el razonamiento 2.

Muchas gracias

**Comment by iago64** [comment]
Buenas! como va?
La idea es que implementen lo mas apegado a la teoría, con lo cual mi primera contra pregunta seria: *Como tenían pensado recorrer la lista de segmentos?*.
Si por ejemplo tenían como idea recorrer una lista de segmentos ordenada por las posiciones de memoria, básicamente van a estar cumpliendo con esa condición teórica y de paso, les sería mucho mas simple saber si por ejemplo tienen 2 segmentos contiguos vacíos para la hora de compactar y hacen un 2x1 😉 
Saludos.-

**Comment by RodrigoLista** [comment]
Bueno, muchas gracias. Quedo claro. Saludos
