### ISSUE TITLE
Duda sobre la división del Blocks.ims

### ISSUE THREAD

**Issue by danimontesano** [sisoputnfrba/foro#2091]
Hola buenas. Tenemos una duda sobre como plantear los blocks y los files dentro del iMongoStore en la página 23. ¿Nosotros deberíamos crear un **_ÚNICO_** archivo Blocks.ims que contenga todos los caracteres de llenado de **_todas las tareas_**, el cual debe estar dividido en secciones (cada bloque con su respectivo carácter). 
Nosotros buscaríamos un bloque libre o disponible para ese determinado carácter en el SuperBloque y lo llenaríamos o eliminaríamos a medida que se ejecutan las tareas
Dejo a continuación un ejemplo de lo que me imagino:
![image](https://user-images.githubusercontent.com/62483675/118717869-fbdae380-b7fc-11eb-85ab-76a3b6c0ff2a.png)
En la imagen de recién separé los bloques con \n para que se entienda mas fácilmente mi punto.

Si no es de esta forma, ¿nosotros deberíamos también agregar datos de las bitácoras? si es así ¿Cómo y qué las agregaría? ¿un string?

Muchas gracias, 
saludos

**Comment by julchat** [comment]
No soy ayudante, pero creo que te puedo dar una mano y a la vez verificar si lo que yo planteé está bien.

> ¿Nosotros deberíamos crear un ÚNICO archivo Blocks.ims que contenga todos los caracteres de llenado de todas las tareas, el cual debe estar dividido en secciones (cada bloque con su respectivo carácter)?.

El archivo Block.ims abstractamente sería una lista/array de todos los bloques del filesystem, cada uno con cantidad block_size definida  en el superbloque.ims
Ahora bien, en lo que vos tenes, no hay una división que diga "acá termina un bloque, acá comienza otro", sino que están todos los bytes pegados (tengan contenido o sean nulos), ocupando todo el archivo con tamaño = cant bytes * tamaño de bytes.

Un archivo puede ser de dos tipos: de recursos, o de bitácoras. Ambos tienen un archivo de metadata específico (en la carpeta files, y en la carpeta bitacoras respectivamente), que muestran **que bloques** conforman al archivo. Si ya sabés la teoría de antes, sería como un filesystem indexado. 
No necesariamente el segundo bloque de un archivo va a ser el siguiente físicamente en el conjunto de bytes del block.ims al primer bloque del archivo, puede estar en cualquier lugar. Entonces, no tendrías los recursos dividos en secciones, solo sabrías que, si buscas tal recurso, podes ir al archivo de metadata de tal recurso, y saber que bloques tienen ese recurso.
Y lo mismo con la bitácora, puede estar físicamente en el archivo entre 2 bloques de recursos distintos, y no va a haber problema porque vos vas a tener la metadata de la bitacora del tripulantex en la carpeta bitacoras, diciendote donde están los bloques correspondientes a esa bitacora de ese tripulante.

Y de esto no estoy seguro, pero supongo que la idea sea que si vos tenés un archivo de, por ejemplo, recursos (pero podría ser de bitácoras también), y el mismo está conformado por los bloques C,A,F, en ese orden, los bloques C y A deberían estar llenos, completamente aprovechados, mientras que el último, el F, pueden tener desperdicio al no aprovechar el tamaño del bloque (tengo menos caracteres de llenado en el ultimo bloque que el tamaño del bloque, y no puedo meter parte de otro archivo en lo que me sobró).

**Comment by danimontesano** [comment]
Claro, comprendo y concuerdo en casi todo. Por lo que tengo entendido todos los bloques tienen el mismo tamaño, puede ser que estén completos o no pero de todas formas tienen el mismo tamaño. Y por eso yo debería reservar el tamaño del archivo blocks.ims (cant bloques * tamaño en bytes del bloque), ¿alguna idea de como reservar ese espacio?

Y por ultimo con lo de C,A,F eso seria por cada recurso en particular, es decir, los recursos no comparten bloques entre si.

**Comment by iago64** [comment]
Buenas buenas!

Che muy bien @julchat entendiste la idea del blocks.ims, es clave lo que comentas de que no hay una división entre un bloque y el siguiente, si no que es algo que se define lógicamente por el tamaño de los mismos.

@danimontesano para reservar el tamaño, es tan simple como buscar alguna alternativa que te permita crear y ampliar el tamaño de un archivo (puede ser algo hecho en C o algo que ejecutes como si fuera en la consola mediante system(), no hay restricciones al respecto 😉), alternativas hay de sobra, trata de ver de lo que encuentres cual te resulta mas simple.

Saludos.-

**Comment by danimontesano** [comment]
Genial! Muchas gracias! me pongo a investigar alternativas 😀👍
