### ISSUE TITLE
Error al levantar la VM en Mac OS

### ISSUE THREAD

**Issue by gastonharari** [sisoputnfrba/foro#2092]
Hola, como estan?
Yo habia instalado de forma correcta la VM sin embargo, desde la semana pasada que no puedo levantar la misma, los errores que me dice son los siguientes:

![image](https://user-images.githubusercontent.com/22179865/118730854-a27bb000-b80e-11eb-8f02-8488d22e9ca3.png)

![image](https://user-images.githubusercontent.com/22179865/118730877-aad3eb00-b80e-11eb-8d70-f679cf74c478.png)

### 🔎 Búsqueda en foros

Probe en lo que dijieron muchos foros, sin exito, la mayoria decia de hacer algo asi:
[(https://medium.com/@Aenon/mac-virtualbox-kernel-driver-error-df39e7e10cd8)]
Pero lo realice sin exito ya que en la parte de `Security & Privacy` no me aparece para darle allow a virtualbox (incluso despues de reinstalarla varias veces, probando con versiones de Virtual Box 6.** y 5.**)
)
### 📦 Especificaciones de la VM
- Versión de VirtualBox: 6.1.22
- Memoria RAM asignada:1024

### 🖥️ Especificaciones del host
- Sistema Operativo y versión: macOS Big Sur 11.3.1
- Memoria RAM: 16GB
- Procesador: Intel Core i7

### 💻 Logs

Dejo aca los logs de las capturas:
Result Code: 
NS_ERROR_FAILURE (0x80004005)
Component: 
MachineWrap
Interface: 
IMachine {85632c68-b5bb-4316-a900-5eb28d3413df}

Kernel driver not installed (rc=-1908)

Make sure the kernel module has been loaded successfully.

where: suplibOsInit what: 3 VERR_VM_DRIVER_NOT_INSTALLED (-1908) - The support driver is not installed. On linux, open returned ENOENT. 

Que mas podria hacer?
Desde ya muchas gracias por su ayuda!!!

**Comment by mgarciaisaia** [comment]
¡Buenas!

Lo que dicen [por acá](https://apple.stackexchange.com/a/410739) es que tenés que deshabilitar un par de protecciones que agregó Big Sur, con intención de que l@s desarrolladores dejen de implementar extensiones del kernel. El tema es que VirtualBox (al menos por ahora) las necesita, así que ahí tiran dos comanditos para correr (dice que en Recovery Mode) para deshabilitar esto.

La verdad es que no tengo una compu con Big Sur (y, buen, con esto, medio que tampoco quiero upgradear por ahora 😇), así que no lo puedo probar.

Acá [el changelog](https://www.virtualbox.org/wiki/Changelog-6.1) de VirtualBox 6.1 habla de fixes y cambios específicos que metieron para Big Sur, así que todo indica que es un sistema operativo host soportado.

Si no te aparece (más) en System & Privacy, [acá](https://superuser.com/a/1497375) dicen que corras `sudo kextcache --clear-staging` para resetear los cositos por los que te pregunte (después de 30 minutos deja de insistirte con cada extensión o app). Algunos dicen que tenés que reiniciar, otros que no (y la respuesta era para Mojave, pero probablemente aplique), y después vuelvas a instalar.

Si no, [en otra respuesta](https://superuser.com/a/1436822) de la misma pregunta, alguien dice que apruebes "a mano" a VirtualBox, booteando en modo Recovery, y ejecutando `spctl kext-consent add VB5E2TV963`.

**Comment by gastonharari** [comment]
Hola, como estas?

Muchas gracias por tu ayuda, entre todos los posts pude volver a instalar la VM de forma correcta!!!
No se exatamente cual de todos los comandos termino funcionando, pero creo que fue `sudo kextcache --clear-staging` y esperar como 1hs entre correr el comando y volver a instalar Virtual Box

Nuevamente, muchisimas gracias por tu ayuda!!!!
