### ISSUE TITLE
[I-Mongo-Store] Duda sobre MD5 del archivo

### ISSUE THREAD

**Issue by snouthill** [sisoputnfrba/foro#2093]
Hola, me surgió una duda sobre el cálculo del MD5. 

**¿Cuál es el input para generarlo? ¿El string que se guardará en los bloques?**

Por ejemplo, si yo grabo en los bloques del archivo Oxigeno.ims el string `OOOOOO`,
 uso esa cadena para generar el MD5 `bf53d82e718e602b3048f15781abae0f`?

### 📔 Cita del enunciado:

> Files:
>
>En esta carpeta se almacenará la metadata para la reconstrucción de los distintos archivos que se crearán en el sistema. Estos archivos simularán ser un contenedor de recursos, se llenarán con un mismo caracter.
>Para esto se almacenará un archivo de metadata por cada archivo existente en el sistema que contendrá:
>- El tamaño del archivo expresado en bytes
>- La cantidad de bloques del archivo
>- La lista de bloques que lo conforman
>- El caracter con el cual se llena el archivo
>- MD5 del archivo, deberá actualizarse cada vez que se realicen modificaciones en el mismo.

**Comment by iago64** [comment]
Buenas! como va?

El MD5 es del contenido de **todo** el archivo, con lo cual antes cada escritura tienen que levantar todos los bloques y calcular el md5.

Saludos.-

**Comment by iago64** [comment]
Buenas! como va?

El MD5 es del contenido de **todo** el archivo, con lo cual antes cada escritura tienen que levantar todos los bloques y calcular el md5.

Saludos.-

**Comment by snouthill** [comment]
Perfecto, muchas gracias! Cierro el issue.
