### ISSUE TITLE
Consulta sobre pasos discordiador

### ISSUE THREAD

**Issue by heinHertz** [sisoputnfrba/foro#2094]
Hola en la hoja 29:
```
Todas las listadas a continuación consumirán 1 ciclo de CPU para realizar la petición de E/S.

Tarea | GENERAR_OXÍGENO
Parámetros | CANTIDAD: Cantidad de Oxígeno a Generar (Número)
Pasos  1 Verificar que exista un archivo llamado Oxigeno.ims en el i-Mongo-Store
2 Si existe saltar al paso 4. 
3 Si no existe el archivo, crearlo y asignarle el carácter de llenado O
4 Agregar tantos caracteres de llenado del archivo como indique el parámetro CANTIDAD
Ejemplo | GENERAR_OXIGENO 12;2;3;5
```
Mi consulta pasa por el tema de la comunicación entre discordiador e imongo, estoy tratando de entender esto:
1.  en cada paso se van comunicando  ?( por ej  el discordiador le manda la consulta de si existe "oxigeno.ims" y el imongo responde  y después le da la orden llena el archivo con O y imongo hace y responde )
ó como dice que consume 1 ciclo de CPU, hay que hacer todo de una( en ese caso el discordiador le manda una orden GENERAR OXIGENO a imongo y imongo hace todo de una(  y cuando termina le responde a discordiador ) ?

Muchas gracias.

**Comment by iago64** [comment]
Buenas! como va?

La idea de que consuman 1 ciclo de CPU en el discordiador es que ejecuten la llamada al sistema (el pedido a i-mongo store) y que este resuelva todo, lo que va a pasar en el medio es que van a tener que tener al tripulante bloqueado en I/O por un tiempo (lo que diga la tarea + si tuvo que esperar).

Saludos.-

**Comment by heinHertz** [comment]
gracias!
