### ISSUE TITLE
Segmentación Pura : Rechazo de solicitud al no haber espacio luego de compactar

### ISSUE THREAD

**Issue by jcastagno99** [sisoputnfrba/foro#2095]
Buenas, tengo una consulta respecto a esto: 

>Cuando se quiera escribir en la memoria y se detecte que no hay espacio para el segmento necesario. Tener en cuenta que si luego de realizar la compactación se sigue sin poder guardar, se deberá denegar la solicitud.

Que pasa si por ejemplo, al iniciar una patota, tengo el suficiente espacio para agregar el segmento del TCB pero no el de las tareas (ya habiendo compactado), descarto ambos segmentos? descarto solo aquel para el que no tengo espacio? creo que se rechazaría la solicitud enteramente para no dejar algo inconsistente pero por las dudas pregunto.

**Comment by jcastagno99** [comment]
Tambien me pasa con los TCB, que pasa si los N-1 tripulantes tienen espacio pero el N tripulante NO, se rechaza el ultimo? todos? se da de baja la patota? se que por ahi es medio border case pero me sirve para saber si cuando voy a pedir espacio para guardar un segmento, de aceptarse TODO o RECHAZARSE puedo pedir directamente espacio para ambos (en el caso de iniciar patota)

**Comment by ncoen97** [comment]
Buenas, este tipo de manejo de errores lo dejamos para que lo desarrollen de la manera que crean más conveniente (siempre basándose en alguna justificación, claramente), de hecho también puede depender de cómo diseñen ustedes el flujo de mensajes.
Yendo a la respuesta, por ahí yo lo encararía teniendo en cuenta las _solicitudes_ que entran a su módulo. Si la solicitud se puede completar en su totalidad está ok, si no hay lugar suficiente para completarla no está ok.
Igualmente como decías, puede ser un poco border y no es a lo que solemos apuntar en las pruebas, pero siempre está bueno tener los módulos más robustos y a prueba de errores así que está bueno tenerlo en cuenta.
Saludos!

**Comment by jcastagno99** [comment]
Buenisimo, quedo claro, gracias!
