### ISSUE TITLE
Consulta segmentación - Identificar el segmento para una patota

### ISSUE THREAD

**Issue by eguiggiaro** [sisoputnfrba/foro#2096]
Hola!

¿Cómo están?

Estamos avanzando en MiRAM con segmentación pura. Ya tenemos las estructuras creadas, reservamos la memoria y alocamos según First Fit o Best Fit. El problema es que no estamos entendiendo exactamente cómo identificar un segmento a la hora de buscar, por ejemplo, una patota.

Las preguntas son:

1) ¿Puedo tener varias tablas de segmentos? Por ejemplo, una tabla ordenada que me permita aplicar los algoritmos para encontrar espacio. Otra tabla de segmentos de Patotas que me indique los segmentos de las patota 1, etc.

2) En caso de tener que armar una sola tabla, ¿puedo agregarle a la tabla de segmentos, qué estructura se está guardando (TCB, PCB, tarea), o algún código identificador para buscarlo luego?

Espero se entienda, gracias!!

**Comment by iago64** [comment]
Buenas! como va?

La única restricción que tienen es que los datos de los PCB, TCB y Tareas van en la memoria que tienen que reservar al principio. Después las estructuras administrativas que creen para manejar esa memoria quedan a criterio de uds. Lo lindo de que encaren las estructuras de una u otra forma es que nos da lugar a preguntar en el coloquio como lo resolvieron y que hagan la relación entre lo que hacen en su TP y lo que dice la teoría😉 

Saludos.-

**Comment by eguiggiaro** [comment]
Gracias!!
