### ISSUE TITLE
[Discordia] Duda rutina de sabotaje.

### ISSUE THREAD

**Issue by int0x80-sys** [sisoputnfrba/foro#2097]
Nos surgio una duda. Cuando se inicia la rutina para atender un sabotaje en el planificador:

¿Debemos esperar a que todos los tripulantes que estan haciendo I/O por tareas terminen de desbloquearse para luego poder seleccionar entre todos los tripulantes en la cola de bloqueados por sabotaje al encargado de resolver el sabotaje?¿O debemos seleccionar a los tripulantes que hay en la cola de bloqueados por Sabotaje, sin tener el cuenta los que están bloqueados por I/O?

**Comment by iago64** [comment]
Buenas! como va?

Muy buena pregunta!, claramente no nos quedo claro en el enunciado, vamos a revisar la redacción para que sea un toque mas claro (igual lo vamos a aclarar en el video).

Los que están bloqueados por I/O no entran en juego para resolver el sabotaje porque ya están bloqueados (ya sea porque esta justo resolviendo la petición de I/O o esta esperando que termine uno anterior). Por lo tanto, los únicos que entran en juego para la selección de quien resuelve el sabotaje son los que están bloqueados por el sabotaje.

Saludos.-

**Comment by int0x80-sys** [comment]
Buenas. Clarisimo. Gracias por la respuesta.

Saludos 🚀
