### ISSUE TITLE
Tiempo en entrada/salida en que modulo lo contamos

### ISSUE THREAD

**Issue by julchat** [sisoputnfrba/foro#2098]
Buenas, estuvimos charlando con mi grupo como distribuir algunas funcionalidades entre discordiador (tripulante) y i-Mongo-Store, y no surgió una duda.

En tripulante
> 4.Duración de la tarea (expresada en ciclos de CPU; en caso de que sea una tarea de Entrada Salida, este tiempo deberá transcurrir en la cola de bloqueados)

Ahora la pregunta, simple, ese tiempo de la tarea, lo contamos en tripulante? O lo contamos desde I-Mongo?
Tendría más sentido que sea el FS el que cuente y diga cuando termina, y es algo que se pueda pasar como parametro al fs. Eso si, también le deberíamos pasar el tiempo de un ciclo y, obviamente, el tiempo de la tarea

**Comment by iago64** [comment]
Buenas! como va?

Quien conoce los retardos de los ciclos de CPU? Ahí tenes la respuesta de quien tiene que contarlos. 
En el caso de i-Mongo Store, hace lo que tenga que hacer y le contesta al tripulante que la tarea fue realizada.

Saludos.-

**Comment by julchat** [comment]
Okey! Gracias
