### ISSUE TITLE
Eclipse no me deja abrir los modulos

### ISSUE THREAD

**Issue by ezecastiglione18** [sisoputnfrba/foro#2099]
Buenas! Quise entrar al tp para modificar algo y no me deja abrir ni la carpeta con la biblioteca compartida, ni los modulos que hacen los otros chicos (yo hago el file system y si me deja abrirlo en mi VM). En todos los casos, me salta el error de:

"The project description file (.project) for 'el_nombre_de_la_carpeta' is missing."

Ya pullie el proyecto y lo borre y volvi a clonar y todavia sigue igual. Y esto a mi no me pasaba antes. Como se puede solucionar?

EDIT: no se si tiene que ver, pero encima dentro de la carpeta del file system tambien me tira error en el makefile

**Comment by tferraro** [comment]
👋 Esta fue literalmente la primera respuesta de google 🙂 
https://stackoverflow.com/a/17343327

Fijate si es el mismo caso, y si no, porfa subí una forma de reproducirlo de forma aislado, un ejemplo de proyecto con la misma estructura de archivos y los pasos que hiciste para que podamos reproducirlo y darte una mano más que dar manotazos en el aire.

**Comment by ezecastiglione18** [comment]
Que raro, no me aparece el .location que dicen en stackoverflow. Igual te comento que ayer, el chico que me ayudaba en soporte se dio cuenta que en la libreria compartida estaba la carpeta Default en vez de Debug (no se por que). Eso lo resolvimos con los chicos haciendo una libreria de cero. 

Y a que te referis cuando decis que suba una "forma de reproducirlo"? A que suba un proyecto aparte al del repo que nos dieron?

**Comment by iago64** [comment]
@ezecastiglione18 como va? a lo que hace referencia Tom, es que si nos decis que tienen un inconveniente y no tenemos forma de reproducirlo posiblemente sea muy difícil que podamos ayudarlos. 
Una cosa es una duda de enunciado que si, podemos contestarla porque es básicamente explicar de otra forma lo que esta redactado y otra muy distinta es un error de código o de eclipse que puede darse por muchisimas otras variables y que si empezamos a tirar posibles soluciones al aire podes llegar a estar hasta julio probando hasta que demos en la solución correcta.

Por otro lado, si la duda esta resuelta, cerramos el issue?
Saludos.-

**Comment by ezecastiglione18** [comment]
El problema sigue, pero voy a ver si creando el proyecto de cero de vuelta soluciona. Pero bueno ahí cierro el issue

**Comment by RaniAgus** [comment]
¡Buenas, @ezecastiglione18 ! Tranqui, nunca te vamos a pedir que cierres un issue si la duda no se resolvió, al contrario, pedimos que lo hagan _solo en caso de que **sí** se haya resuelto_.

1. En cuanto a lo que se referían Tom y Dami es que no contamos con el contexto suficiente para entender cómo ocurrió el error. Repito con otras palabras lo mismo que dijeron: necesitaríamos que nos muestres al menos una forma de reproducir el error, o sea, la serie de pasos que hayan hecho vos y tu compañero/a a la hora de crear los proyectos, importarlos, pushear los cambios al repo y pullearlos hasta que ocurrió lo que comentabas.

2. Por otro lado, la respuesta que citaba Tom en StackOverflow comenta lo siguiente:
> My mistake was to put a project in other location out of the workspace, and share this workspace between several computers, where the paths difer.

¿Ese es su caso? ¿Vos y tu compañero/a tienen el proyecto importado en distintos workspaces?

¡Saludos!

**Comment by ezecastiglione18** [comment]
Haciendo un poco de prueba y error descubrí que el problema está más que nada en la librería compartida. Si yo invoco a una función de manera indirecta (es decir, que está en esta lib compartida) no me lo reconoce el programa. En cambio si meto todo en un mismo archivo, se soluciona ese problema. La realidad es que es una solución parcial al problema

Pero bueno, por lo menos algo es algo

Y los pasos que hicimos fue literalmente igual que en el vídeo: creamos la librería compartida con sus flags, creamos el módulo, linkeamos a la librería y pusheamos. Pero bueno, por lo menos se puede avanzar con el proyecto jajaja

**Comment by iago64** [comment]
Buenas! 
cuando decís que no te lo reconoce, es que no te lo reconoce eclipse o que si lo compilas rompe? 
Porque capaz el problema viene por el lado de que te falto el paso de decirle donde están los fuentes y eclipse básicamente te dice: *No tengo idea de que me estas hablando*.

Saludos.-

**Comment by ezecastiglione18** [comment]
Me parece a mí que no me la reconoce porque cuando hago ctrl + click sobre una función para ir a la definición no me lleva ahi

**Comment by iago64** [comment]
Buenas! Justo se dio la casualidad que entre a ver un issue raro que no era para este foro y contestaste 😄 

Si no te reconoce el Ctrl + click es justamente que no te esta encontrando los fuentes de la lib, para resolver eso tenes que incluir los headers como esta en el video que hizo Tom el año pasado: https://www.youtube.com/watch?v=A6dhc9cCI18&t=301s

Abrazo!

**Comment by ezecastiglione18** [comment]
Ahi sale. Sorry que lo lea ahora, gracias chicos!
