### ISSUE TITLE
Libreria para file system

### ISSUE THREAD

**Issue by lautaropetronacci** [sisoputnfrba/foro#2100]
Hola, como estan?

Les queria hacer una consulta relacionada al file system. Encontramos la libreria FCNTL_H para el manejo de archivos y la verdad que es bastante util. ¿Esta libreria esta permitada para el tp?

Muchas gracias y saludos!

**Comment by tferraro** [comment]
👋 Holiss, fcntl es parte del package build-essentials creo y ya viene instalado en las vms :)

Pueden usarlo sin drama, es parte del estándard de POXIS, como pthread :)

**Comment by FranciscoAnnoni** [comment]
Disculpa que consulte por acá, pero como hablaban del filesystem me pareció lo mas practico preguntar acá, estoy teniendo muchas dudas en la creación de los bloques y del bitmap, y como hacer para manejar el bitmap dependiendo de los bloques que se llenaron, hay alguna lectura recomendada para comprender mejor este tema y el manejo de archivos del fileSystem? He estado leyendo la bibliografía recomendada en el tp, pero no me queda claro, hay algo mas a nivel de código como el beej sobre filesystem?  Muchas gracias, saludos francsico.

**Comment by iago64** [comment]
@FranciscoAnnoni Como va?
Sería buenísimo que armes otro issue y detalles un poco mas las dudas que tenes porque como lo planteas creo que lo que hace falta es una explicación super general y además la consulta de este issue fue especifica de usar una biblioteca y nada mas.

Saludos.-

**Comment by iago64** [comment]
@lautaropetronacci queda alguna duda o podemos cerrar el issue?

**Comment by lautaropetronacci** [comment]
Hola! mil perdones, me olvide de avisar, todo claro! muchas gracias, pueden cerrarlo.
