### ISSUE TITLE
Inconsistencias en DESCARTAR_BASURA

### ISSUE THREAD

**Issue by matiasfdevecchi** [sisoputnfrba/foro#2101]
Buenas tardes, quería notificar que el comando DESCARTAR BASURA tiene inconsistencias en su explicación. Según leí en este issue https://github.com/sisoputnfrba/foro/issues/2054#issuecomment-830717945 irían a revisarlo porque quizás faltó el tiempo de espera, pero lo comento porque este issue fue de hace varias semanas.

Si el tiempo de espera no faltara hay una inconsistencia entre el formato de las tareas y esta en particular.

Formato de tareas:
`TAREA PARAMETROS;POS X;POS Y;TIEMPO`

Esta tarea no tiene parametros según menciona el documento, sin embargo el comando de ejemplo es:
`DESCARTAR_BASURA 3;1;7` 
El cual inidica que "3" es un parametro según el formato. ¿El ejemplo correcto sería el siguiente?
`DESCARTAR_BASURA;3;1;7` 

¿Van a añadir un tiempo de espera como lo menciona el issue citado o permanecerá sin parametros?

**Comment by RaniAgus** [comment]
¡Buenas!
1. Así es, efectivamente falta un `;` ahí, lo vamos a corregir en la próxima errata
2. Ojo que el tiempo de espera es el último parámetro de la tarea, cito el enunciado en Discordiador (pág. 13):

> Este archivo de tareas tendrá una sola tarea por línea y cada línea tendrá los siguientes parámetros separados por punto y coma (;)
> - Nombre y parámetros de la tarea
> - Ubicación en X
> - Ubicación en Y
> - Duración de la tarea (expresada en ciclos de CPU; **en caso de que sea una tarea de Entrada Salida, este tiempo deberá transcurrir en la cola de bloqueados**)

Lo cual va en línea con el Anexo II, que en la primera página dice lo siguiente:
> Las tareas que no se encuentren en este anexo consistirán en llegar a la ubicación y esperar que pase el tiempo solicitado en el estado EXEC y no tienen que hacer ninguna operación sobre archivos de recursos.
> Todas las listadas a continuación consumirán 1 ciclo de CPU para realizar la petición de E/S.

¡Saludos!
