### ISSUE TITLE
Dudas con el File System

### ISSUE THREAD

**Issue by ezecastiglione18** [sisoputnfrba/foro#2102]
Buenas! Hay un par de cosas del enunciado que no entiendo:

1) Suponiendo que el unico archivo del File System es el Superbloque, como genero ese archivo? Como dice que algunos atributos deben ser de tipo uint32_t es un .c, no?
2) Tanto Files como Blocks no se bien el tipo de archivo. Son .txt?
3) La carpeta del punto de montaje tiene que estar tambien dentro del proyecto? Osea, que tenga que crear una sub-carpeta dentro del modulo del FS que sea para el punto de montaje

Saludos!

**Comment by iago64** [comment]
Buenas! como va?

1.- El superbloque es un archivo binario que tiene los campos en el orden que se los pasamos. Ya para crearlo te conviene guiarte con la guia / videos de serialización e investigar un poco sobre la función mmap(), ya que eso te va a simplificar bastante las cosas.

2.- La extensión de un archivo es totalmente irrelevante, puede ser .txt, .asd o .lol y da lo mismo, lo importante es como los interepretes vos, para el caso de los files, son archivos con el formato que les pasamos que casualmente se parecen MUCHISIMO a los archivos de config ;). En el caso de Blocks, es un archivo que va a tener todos los bloques de datos uno al lado del otro sin separar y por lo tanto van a tener que uds ver donde empieza un bloque y donde termina (nuevamente super recomendado que investiguen sobre mmap()).

3.- No, puede ser una carpeta en cualquier parte, lo importante es que sea una carpeta donde tengan permisos de lectura y escritura por eso por ejemplo pueden crearse una carpeta en `/home/utnso/fstp` y ahi adentro tener su file system.

Saludos.-

**Comment by ezecastiglione18** [comment]
Perdón pero no entendí bien lo del superbloque, más que nada porque nos pide que guardemos el tamaño (y cantidad) de los bloques si eso lo especificamos en el config del mongostore. Puede ser que me estés diciendo indirectamente que el .config del módulo es el superbloque jajajajaj, pero sino no entendí.

**Comment by iago64** [comment]
Buenas! como va?

No hay ninguna indirecta oculta, vos en tu punto de montaje tenés que tener 1 archivo que tenga serializados los datos que les pasamos en el enunciado:

![image](https://user-images.githubusercontent.com/1622109/119394919-2c14fd00-bca9-11eb-8265-68201b037e66.png)

Los tipos de dato son para que puedan determinar el tamaño que van a necesitar y nada mas.

Saludos.-

**Comment by ezecastiglione18** [comment]
Ah osea no se hace ninguna operación de escritura en ese archivo? Solamente sirve para leer la info de los bloques y el bitmap?

**Comment by ncoen97** [comment]
Buenas, si van a tener que hacer escrituras, primero cuando creen el superbloque (cuando inicialicen el FS) y luego cuando vayan modificando el bitmap.
El archivo tiene que tener el formato que mostró dami, los primeros 4 bytes para indicar el block size, los segundos 4 bytes para indicar la cantidad de blocks y lo que sigue va a depender de cuantos bits tenga el bitmap.
Spoiler: Para este escribir y leer este archivo también pueden usar `mmap()`.
Saludos!

**Comment by ezecastiglione18** [comment]
Buenas! Sorry que no haya respondido. Entre lo de hoy de soporte y lo que me dijeron creo que va. Igual hay dos ultimas consultitas:

1) Para saber bien cuantas bitacoras generar, me tiene que pasar el discordiador por parametro esa cantidad? O a medida que se crea un tripulante se crea una bitacora?

2) no entendi muy bien el contenido del MD5. Para que sirve?

**Comment by iago64** [comment]
Buenas!

1. Respecto a las bitácoras, van a tener 1 por cada tripulante que se les conecte, con lo cual van a tener que irlas creando bajo demanda.

2. Básicamente para corroborar que el contenido del archivo esta bien, el contenido no es mas que el resultado de aplicarle la función md5 al archivo *completo*, con lo cual ante cualquier escritura o lectura van a tener que levantar todos los bloques del archivo y calcular el md5.

Saludos.-

**Comment by iago64** [comment]
@ezecastiglione18 te queda alguna duda? hay algo mas en lo que podamos ayudarte?

**Comment by ezecastiglione18** [comment]
Ay perdon, todo claro me quedo
Gracias! Ahí cierro
