### ISSUE TITLE
Problema al levantar el Filesystem existente

### ISSUE THREAD

**Issue by dbibe** [sisoputnfrba/foro#2103]
Buenas!

Tenemos un problema a la hora de guardar los datos en el archivo `SuperBloque.ims`. En un principio guardamos 2 enteros que serian `cantidadBloques` y `tamanioBloques`, al cerrar el archivo y volverlo a levantar, los dos valores se cargan tal cual se guardaron.
El problema viene cuando agregamos el bitmap seguido de estos dos valores, usando la funcion `fseek(superBloque, sizeof(int) * 2, SEEK_SET);`
Al hacer esto, una vez que cerramos el archivo y lo volvemos a levantar, los valores de `cantidadBloques` y `tamanioBloques` aparecen en cero o con basura.

Para contexto asi es como estamos escribiendo en el archivo para guardar espacio para el bitmap en `SuperBloque.ims` (Acá es donde creemos que es el problema)
``` c
void* bitmap_p = calloc(cantidadBloques / 8, 1);
fwrite(bitmap_p, 1, cantidadBloques / 8, superBloque);
```
Luego de esto mapeamos a memoria con `mmap` y se lo pasamos al `bitarray_create_with_mode`

Y esto es lo que usamos para leer los enteros
```c
fread(&tamanioBloque, sizeof(int), 1, superBloque);
fseek(superBloque, sizeof(int), SEEK_SET);
fread(&cantidadBloques, sizeof(int), 1, superBloque);
```

Saludos.

**Comment by iago64** [comment]
Buenas! como va?

Creo que el problema viene porque por un lado estan usando FILE * y funciones de archivos como fseek() o fwrite() y por otro lado estan usando mmap().

Si quieren ir por la vía de mmap() lo que pueden hacer directamente es levantar todo el superbloque con mmap() y despues saben que a partir del puntero que les devuelve mmap():
1. En la posición 0 van a tener el block_size
2. En la posición 4 van a tener el block_count 
3. A partir de la posición 8 van a tener el bitmap.

Si quieren ir por la opción de usar un FILE *, lo que les conviene hacer es leer los datos del bitarray y guardarlos en memoria para después apuntar el bitmap ahi.

Saludos.-

P.D: No se olviden que los datos son uint23_t no tienen signo porque no van a tener tamaños o cantidades de bloques negativos 😉

**Comment by dbibe** [comment]
Buenas!

Muchas gracias por la respuesta, ya pudimos resolver el problema utilizando mmap y memcpy.

Saludos!
