### ISSUE TITLE
Patotas y tripulantes a eliminar

### ISSUE THREAD

**Issue by jfloresmaquera** [sisoputnfrba/foro#2104]
Estabamos viendo que hacer con las Patotas y los tripulantes a la hora en que una patota termina todas sus tareas asociadas.

### 💭 Soluciones posibles
Teniamos pensado hacer una lista de Exit donde se acumulaban los tripulantes de una patota la cual no tenia tareas a realizar. Una vez que se acumulaban todos los tripulantes de la patota sin tareas decirle al MI-RAM-HQ que libere a la patota junto con sus tripulantes.
Otra solucion podria ser que a la vez que los tripulantes se liberen haciendo el pop de la lista de Ready, ir eliminandolos.

**Comment by iago64** [comment]
Buenas! Como va?

Me encanta que plantearon 2 soluciones 😄 
La cola de Exit esta para que se acumulen ahí los tripulantes que van terminando su ejecución (en criollo se quedan sin nada para hacer) y que una vez que llegue el último de los tripulantes le puedan decir a la memoria que libere los recursos que tenia asignada esa patota.

Saludos.-

**Comment by jfloresmaquera** [comment]
Genial, muy claro, se entendio perfectamente.

¡¡Gracias y saludos!!
