### ISSUE TITLE
Dudas con la creacion de FileSystem

### ISSUE THREAD

**Issue by FranciscoAnnoni** [sisoputnfrba/foro#2105]
Hola, como estan?
Estoy teniendo muchos problemas con la creación del fileSystem,
1. Al crear el superBloque con los campos adecuados no comprendo como seguir creando los blocks del siguiente file ya que el mmap solo sirve para leerlos y modificarlos, pero no comprendo como crearlos ya que no se puede usar un FILE * ,
2. Tampoco se como asociar el bitarray con los bloques, ya que no comprendo como crear bloques con un tamaño determinado, supongo que eso se hace con el mmap¿?.
(me gustaría saber si hay alguna guía con el manejo de archivos o bloques, alguna lectura recomendada, o videos de la catedra que me puedan servir.)
Muchas gracias.

**Comment by iago64** [comment]
Buenas! como va?

1.- Me parece que te estas mezclando 2 archivos distintos, por un lado vas a tener 1 archivo que va a ser el superbloque que va a tener la estructura que tenemos en el enunciado:
![image](https://user-images.githubusercontent.com/1622109/119395502-fa506600-bca9-11eb-8943-9f7d246a4192.png)
Esto idealmente les recomendamos que lo vean con mmap() ya que es muy simple para serializarlo porque vas a tener primero 2 números que te indican la cantidad de bloques y el tamaño de los mismos y luego el bitmap. El enunciado no les impide usar un FILE *, pero puede que se les complique un poco mas implementarlo nomas.

Respecto al tema del archivo Blocks la idea es que sea un único archivo que tenga un tamaño igual al resultado de multiplicar tamaño de bloques por cantidad de bloques. Por ejemplo si tenes 1024 bloques de 64 bytes cada uno el archivo Blocks.ims debería pesar 65536 bytes, ahora bien, esto va a tener todos los bloques uno al lado del otro, por lo que vos de alguna forma vas a tener que saber donde empieza y donde termina cada bloque, como hacerlo justamente es lo que buscamos que se las ingenien ya que un sistema operativo real tiene que lidiar con esta problemática.

Por último, la parte del bitarray, tene en cuenta que el bitarray solamente sirve para saber si un bloque esta libre u ocupado, en este punto lo unico que les interesa es poder tener la info que tienen guardada en el superbloque en memoria para poder usar el bitarray de las commons. Como levantarlo ya depende de si quieren usar mmap() o si quieren abrir el archivo con un FILE *, leerlo y copiar esos datos.

Saludos.-

**Comment by iago64** [comment]
@FranciscoAnnoni como va? Te queda alguna duda? Necesitas alguna explicación extra?

**Comment by FranciscoAnnoni** [comment]
No no, muchísimas gracias por la explicación, con eso nos vamos arreglando, saludos Francisco!!
