### ISSUE TITLE
[Discordiador] Planificador y tripulantes en última tarea

### ISSUE THREAD

**Issue by Nan0t** [sisoputnfrba/foro#2106]
Buenas! Tenemos una duda respecto a tripulante y el manejo de tareas. El hilo tripulante en nuestra implementación ejecuta cuando está en CPU y tiene como parte de su comportamiento pedir la próxima tarea a memoria.
El caso que me genera dudas de nuestro diseño es cuando se bloquea por E/S y estaba ejecutando su última tarea(es decir, no tendrá más tareas a ejecutar después).
Nuestra implementación : tripulante sale de E/S de la última tarea y pasa a ready, luego entra a running, se ejecuta en un CPU y recién ahí busca la proxima tarea. Dado que no tiene otra tarea para ejecutar pasa a exit. 
El flujo quedaría como:
* bloqueado por E/S -> Ready -> Running -> Exit.

Sé que en la teoría el planificador puede pasar un PCB de estado de blocked a exit (E/S ->Exit) y por eso me queda la duda de si podemos dejar el diseño como lo tenemos o deberíamos cómo podemos hacer para obtener la próxima tarea justo antes de que salga de bloqueados y verificar si tenemos que finalizar el tripulante.

**Comment by iago64** [comment]
Buenas! como va?

Ya de base están arrancando con un diseño que contradice al enunciado, el tripulante es 1 hilo que vive siempre desde que inicia el tripulante, independientemente de si esta en ready, exec o bloq.

Por otro lado, la transición de bloq a exit tiene que estar ya que pueden tener que expulsar un tripulante en cualquier momento.

Saludos.-

**Comment by int0x80-sys** [comment]
Buenas. Soy compañero de equipo de @Nan0t.

En cuanto a lo primero, sí. Tenemos en cuenta que el tripulante es un hilo. Cuando mencionamos CPUs básicamente sería los encargados de desbloquear los hilos de los tripulantes que esten en exec.

En cuanto a lo segundo, también tenemos en cuenta que debe existir esa transición de blocked a exit, o de ready a exit.

La duda que planteamos viene mas por el lado de una ejecución normal de un tripulante. Por ejemplo, cuando un tripulante termina una tarea, en el siguiente ciclo de CPU pediría una nueva tarea. Si la memoria le responde con una nueva tarea, en ese mismo ciclo empieza a desplazarse hasta la posición. Pero en caso contrario, finalizaría. El tema es que, para poder finalizar un tripulante, se tiene que ejecutar un último ciclo de CPU para pedir una nueva tarea a la memoria y que este le responda que no hay mas tareas. Por ejemplo:

```
[Trip_1] ||   CPU   |   CPU   |   CPU   |     I/O   |    I/O   |   CPU    |   CPU   |    I/O   |   CPU   |
----------------------------------------------------------------------------------------------------------
         ||     0   |    1    |    2    |     3     |     4    |     5    |    6    |    7     |    8    |

```
En el ejemplo, la última tarea se empieza a ejecutar en el ciclo 6 y que dura 1 ciclo. Por lo que en teoría en el ciclo 7 el tripulante finalizaría (ya que no le quedarían mas tareas por ejecutar). Pero, en nuestra implementación haría falta un ciclo mas de CPU, que vendría a ser el ciclo donde el tripulante pide una nueva tarea y la memoria le notifica que no hay mas tareas por realizar.

¿Estaría bien este comportamiento?

Saludos.

**Comment by iago64** [comment]
Buenas! como va?

_TL-DR_: No, ese comportamiento esta mal.

Ahora me queda una duda a mi de cual fue el disparador del enunciado que les hizo pensar que el ir a buscar una tarea tiene que consumir un ciclo de CPU.
El solicitar las tareas a Mi-RAM no es parte ni de la planificación ni de la ejecución, es algo que uds hacen extra ya que tienen en 2 módulos separados lo que es la ejecución de lo que es la memoria (en la realidad todo de cierta forma convive en el mismo espacio)

Saludos.-

**Comment by int0x80-sys** [comment]
Buenas.

Nosotros lo tomamos del instructivo del sub-modulo tripulante. Específicamente de esta parte:

```
Además, se deberá interactuar con el módulo de Mi-RAM HQ antes las siguientes situaciones:

1. Informar cada movimiento dentro de la nave.
2. Luego de realizar una tarea, solicitar la próxima.
```
Como es parte de la especificación del sub-modulo del tripulante el solicitar la próxima tarea, tomamos como que esa acción esta dentro de la ejecución del tripulante, y el mismo ejecuta acciones utilizando ciclos de CPU. Por lo que deducimos que debería ir ahí la solicitud.

Pero en caso de que no tenga que ser el tripulante el que solicite la proxima tarea, veremos de solicitarla en otro lado. ¿Supongo que el tripulante debe ejecutar pensando que tiene tareas disponibles todo el tiempo?

Gracias por las respuestas y saludos 👋

**Comment by iago64** [comment]
Buenas!

Gracias por citar el fragmento del enunciado, vamos a ver si es necesario aclarar algo extra en la próxima errata porque si presta a confusión no esta bueno.

Respecto al tripulante, el mismo va a ejecutar mientras tenga tareas pendientes, por lo que en el caso de que este con una tarea de I/O al finalizar la misma y al consultar la siguiente Mi-RAM, este le dice que no tiene nada pasaría directamente de BLOQ a EXIT.

Saludos.-

**Comment by Nan0t** [comment]
Buenísimo, gracias por las respuestas!
