### ISSUE TITLE
Duda almacenamiento de tareas en memoria con paginacion simple.

### ISSUE THREAD

**Issue by tomytinez** [sisoputnfrba/foro#2108]
Hola, tenia mi duda sobre como almacenar las tareas en memoria ya que segun tengo entendido hay que sacarlas de un archivo en la que hay una tarea por linea y concatenar todas las tareas en un string separadas con un delimitador por ej:
Tengo 3 tareas, las guardaría así:
"GENERAR_OXIGENO 12;2;3;5|CONSUMIR_OXIGENO 120;2;3;1|GENERAR_COMIDA 4;2;3;1"
Siendo el delimitador "|" (esto es robadisimo de otro issue, perdon)
Mi duda es que pasa si el UNICO string con TODAS las tareas no entra en un unico frame, por ejemplo si tengo frames de 32 bytes no me entrarian en un frame todas las tareas.
### 📔 Citas del enunciado/videos

>Las tareas deberán respetar el utilizar un delimitador para los strings y no deberán utilizar formatos numéricos para los tiempos, posiciones, etc, quedando todo como un string. Tampoco está permitido agregar tamaños ni parámetros adicionales a las tareas.

### 💭 Soluciones posibles

Volver a separar cada tarea por el delimitador y guardar una tarea por cada frame en el caso de tener frames de 32 bytes.
Esto seria asi, o entendi algo mal / me estoy perdiendo algo?

**Comment by iago64** [comment]
Buenas! como va?

Ya te aseguro que el listado de tareas de un tripulante no va a entrar en un único frame. Justamente la problemática que tienen que resolver en la parte de paginación es como hacer para obtener un dato que empieza en una página y sigue en otra. 

Lo que **no** tienen que hacer es justamente separar las cosas, si tienen que guardar un string de 100 bytes en páginas de 32 bytes, van a tener que ocupar 3 paginas completas y un poco de la cuarta.

Simplemente tene en cuenta que vos en algún momento eso lo vas a tener que guardar en un *buffer* para mandárselo al tripulante, capaz que ese *buffer* te sirve para lo que estas necesitando 😉 

Saludos.-

**Comment by tomytinez** [comment]
Joya, gracias.
