### ISSUE TITLE
[i-Mongo-Store] Duda con sabotajes en el superbloque

### ISSUE THREAD

**Issue by nicolascallectl** [sisoputnfrba/foro#2109]
Buenas, respecto a la parte del enunciado que dice:
> Sabotajes en el superbloque
Cantidad de bloques: Se debe garantizar que la cantidad de bloques que hay en el sistema sea igual a la cantidad que dice haber en el superbloque. Reparación: sobreescribir “cantidad de bloques” del superbloque con la cantidad de bloques real en el disco.

Sería correcto considerar "la cantidad de bloques  que hay en el sistema"  como la cantidad de bits que hay en el bitmap?

**Comment by gastoncastineira** [comment]
Buenas,

Pensá que la mínima unidad de asignación que entienden las computadoras es el byte (ocho bits), por lo que si tu FS tiene 95 bloques, tu bitmap en realidad va a necesitar 95 bits, 11,875 bytes, por lo que voy a tener que redondearlo a 12 y no utilizar el último bit. Si lo restaurás de esa forma te daría que tenés 96 bloques en lugar de 95
