### ISSUE TITLE
Entrada/Salida en las tareas

### ISSUE THREAD

**Issue by IanMartin94** [sisoputnfrba/foro#2110]
Buenos días,

Nos surgió una duda al momento de realizar la entrada/salida para las tareas.

Por ejemplo en GENERAR_OXIGENO 12;2;3;5. Entendemos que primero tenemos que movernos hasta la posición 2|3 y luego ejecutar 5 ráfagas de CPU. La duda que tenemos es en que momento tenemos que comunicarnos con el mongoStore para realizar la escritura del archivo. 

Tiene que hacerse una vez ejecutadas las 5 ráfagas de CPU o primero realizar la escritura del archivo (en estado bloqueado) y luego ejecutar las 5 ráfagas.

Desde ya muchas gracias.

Saludos.

**Comment by iago64** [comment]
Buenas! Como va?

Ojo que las 5 ráfagas de CPU las va a pasar en la cola de BLOQ y solo van a tener que ejecutar 1 "extra" al momento de llegar a 2-3 para solicitar la operación de I/O y es en ese momento en el que deberían pedirle al i-Mongo Store que haga lo que corresponda.

Saludos.-

**Comment by iago64** [comment]
@IanMartin94 Como va? Te sirvió la respuesta? te queda alguna duda?

**Comment by IanMartin94** [comment]
@iago64 sisi perdon, me olvide de cerrar el issue. Muchas gracias !!
