### ISSUE TITLE
Problemas con mi version de VM

### ISSUE THREAD

**Issue by ezecastiglione18** [sisoputnfrba/foro#2111]
Buenas! Soy el mismo chico que tuvo [este](https://github.com/sisoputnfrba/foro/issues/2099) problema. A uno de mis compañeros le compila de 10 su modulo. Pero cuando yo quiero invocar a una funcion de la misma libreria compartida, no me compila. Y estamos usando la misma libreria. Llegue a la conclusion de que es un tema mio de mi VM. Pero la verdad ni idea porque puede pasar... Si a alguno se le ocurre alguna alternativa me vendria de lujo jajajaja

Saludos!

**Comment by RaniAgus** [comment]
Cierro por duplicado #2099
