### ISSUE TITLE
Dudas sobre la planificación

### ISSUE THREAD

**Issue by MartinTroncoso** [sisoputnfrba/foro#2112]
Buenas! Acabo de ver el video del Discordiador y me surgieron algunas dudas

1) Supongamos que creamos una patota con 4 tripulantes, con 1 tarea sola (de I/O) y con grado de multiprocesamiento = 2.
Los 4 están en estado NEW, después iniciamos la planificación, solicitan la tarea a MI-RAM y pasan a READY. Para empezar, esto está bien modelado así?
Después 2 tripulantes pasan a EXEC (con algoritmo FIFO), y suponiendo que no se pause la planificación en ningún momento, llegan a la posición de la tarea, hacen la petición de I/O y se bloquean el tiempo que dure la tarea (uno después del otro).
Cuando estos 2 comienzan a realizar la entrada/salida, los otros 2 que estaban en READY, pasan a EXEC ¿no?.

Eso por un lado, por el otro
 
2) Si creo otra patota solo con 2 tareas comunes (por ejemplo), los tripulantes una vez que llegan a la posición de la primera tarea y están en EXEC el tiempo que dure la tarea, ¿después pasan a la cola de READY nuevamente o solicitan ahí mismo la siguiente tarea para ejecutarla?.
En otras palabras, ¿los tripulantes ejecutan todas las tareas seguidas o van ejecutando de a una, pasando a READY una vez terminada y dejándole lugar a otro?

Gracias y un abrazo!

**Comment by iago64** [comment]
Buenas! como va?

1.- Respecto al paso de New a Ready debería ser en el momento en el que el tripulante ya puede pedir tareas.
Después al momento de entrar a I/O como salen de EXEC para pasar a BLOCK, pueden entrar los otros 2 que estaban en READY. 

2.- Si la tarea no es de I/O siguen ejecutando, incluso cuando piden la nueva tarea ya que no se bloquearon.

Saludos.-

**Comment by MartinTroncoso** [comment]
Ok, con respecto a la primera, para pedir las tareas tiene que estar la planificación activada o pueden solicitarlas aunque todavía no haya empezado? Pregunto porque el enunciado dice que si se pausa la planificación y se crea una patota nueva, los tripulantes quedarían en NEW hasta que se reanude, pero al crear la primera patota de todas, antes de escribir el comando INICIAR_PLANIFICACION, ¿también habría que esperar a que se inicie la planificación o ya podrían solicitar las tareas?

**Comment by iago64** [comment]
Buenas! como va?

Justamente el pedir tareas *no forma parte de la planificación ni de la ejecución en si misma*, es algo extra que tienen que hacer porque tienen la parte de ejecución en un módulo y la parte de la memoria en otro.
El pausar planificación lo que busca evitar es que se cuenten ciclos de CPU (en BLOQ o EXEC) o se muevan procesos entre las diferentes colas (ya que es un comando pensado en su totalidad para fines de evaluación)

Saludos.-

**Comment by MartinTroncoso** [comment]
Genial, muchas gracias!!
