### ISSUE TITLE
coridial saludo, escane la pc con el programa HIJACK THIS para verificar porque cuando enciendo el computador se apaga y luego lo vuelvo a encender y comienza funcionar bien envio el diagnostico del escaner para que me ayuden a solucionar el inconveniente gracias 

### ISSUE THREAD

**Issue by ASL26** [sisoputnfrba/foro#2113]

**Comment by ASL26** [comment]
Logfile of HiJackThis Fork by Alex Dragokas v.2.9.0.26

Platform:  x32 Windows 10 (Enterprise LTSB), 10.0.14393.0 (ReleaseId: 1607), Service Pack: 0
Time:      26.05.2021 - 09:38 (UTC-05:00)
Language:  OS: Spanish (0x80A). Display: Spanish (0x80A). Non-Unicode: Spanish (0x240A)
Elevated:  Yes
Ran by:    User	(group: Administrator) on DESKTOP-4122012, FirstRun: no

Chrome:  90.0.4430.212
Internet Explorer: 11.0.14393.0
Default: "C:\Program Files\Google\Chrome\Application\chrome.exe" --single-argument %1 (Google Chrome)

Boot mode: Normal

Processus en cours:
Nombre | Chemin
   3  C:\Program Files\Adobe\Acrobat Reader DC\Reader\AcroCEF\RdrCEF.exe
   2  C:\Program Files\Adobe\Acrobat Reader DC\Reader\AcroRd32.exe
   1  C:\Program Files\CCleaner\CCleaner.exe
   1  C:\Program Files\Classic Shell\ClassicStartMenu.exe
   1  C:\Program Files\Common Files\Adobe\ARM\1.0\armsvc.exe
  23  C:\Program Files\Google\Chrome\Application\chrome.exe
   1  C:\Program Files\Google\Update\1.3.36.82\GoogleCrashHandler.exe
   1  C:\Windows\System32\RuntimeBroker.exe
   1  C:\Windows\System32\audiodg.exe
   2  C:\Windows\System32\csrss.exe
   1  C:\Windows\System32\dwm.exe
   1  C:\Windows\System32\lsass.exe
   1  C:\Windows\System32\services.exe
   1  C:\Windows\System32\sihost.exe
   1  C:\Windows\System32\smss.exe
   1  C:\Windows\System32\spoolsv.exe
  16  C:\Windows\System32\svchost.exe
   1  C:\Windows\System32\taskhostw.exe
   1  C:\Windows\System32\wininit.exe
   1  C:\Windows\System32\winlogon.exe
   1  C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy\ShellExperienceHost.exe
   1  C:\Windows\explorer.exe
   1  D:\Andres\Downloads\HiJackThis.exe

R0 - HKCU\Software\Microsoft\Internet Explorer\Main: [Start Page] = https://www.facebook.com/groups/1640637376194852/
R0 - HKU\.DEFAULT\Software\Microsoft\Internet Explorer\Main: [Start Page] = https://www.facebook.com/groups/1640637376194852/
R0 - HKU\S-1-5-19\Software\Microsoft\Internet Explorer\Main: [Start Page] = https://www.facebook.com/groups/1640637376194852/
R0 - HKU\S-1-5-20\Software\Microsoft\Internet Explorer\Main: [Start Page] = https://www.facebook.com/groups/1640637376194852/
O4 - HKCU\..\Run: [CCleaner Smart Cleaning] = C:\Program Files\CCleaner\ccleaner.exe /MONITOR
O4 - HKLM\..\Run: [Classic Start Menu] = C:\Program Files\Classic Shell\ClassicStartMenu.exe -autorun
O4 - HKLM\..\StartupApproved\Run: [SynTPEnh] = C:\Program Files\Synaptics\SynTP\SynTPEnh.exe (2020/12/04)
O17 - DHCP DNS 1: 192.168.1.1
O22 - Task: (telemetry) \Microsoft\Office\Office 15 Subscription Heartbeat - C:\Program Files\Common Files\Microsoft Shared\Office16\OLicenseHeartbeat.exe (Microsoft)
O22 - Task: (telemetry) \Microsoft\Office\OfficeTelemetryAgentFallBack2016 - C:\Program Files\Microsoft Office\Office16\msoia.exe scan upload mininterval:2880 (Microsoft)
O22 - Task: (telemetry) \Microsoft\Office\OfficeTelemetryAgentLogOn2016 - C:\Program Files\Microsoft Office\Office16\msoia.exe scan upload (Microsoft)
O22 - Task: (telemetry) \Microsoft\Windows\Customer Experience Improvement Program\KernelCeipTask - {E7ED314F-2816-4C26-AEB5-54A34D02404C} - C:\Windows\System32\kernelceip.dll (Microsoft)
O22 - Task: Adobe Acrobat Update Task - C:\Program Files\Common Files\Adobe\ARM\1.0\AdobeARM.exe
O22 - Task: CCleaner Update - C:\Program Files\CCleaner\CCUpdate.exe
O22 - Task: CCleanerSkipUAC - C:\Program Files\CCleaner\CCleaner.exe $(Arg0)
O22 - Task: GoogleUpdateTaskMachineCore - C:\Program Files\Google\Update\GoogleUpdate.exe /c
O22 - Task: GoogleUpdateTaskMachineUA - C:\Program Files\Google\Update\GoogleUpdate.exe /ua /installsource scheduler
O22 - Task: \Microsoft\Windows\EDP\EDP App Launch Task - {35EF4182-F900-4632-B072-8639E4478A61},AppLaunch - (no file)
O22 - Task: \Microsoft\Windows\EDP\EDP Auth Task - {35EF4182-F900-4632-B072-8639E4478A61},ReAuth - (no file)
O23 - Service R2: Adobe Acrobat Update Service - (AdobeARMservice) - C:\Program Files\Common Files\Adobe\ARM\1.0\armsvc.exe
O23 - Service S2: Google Update Servicio (gupdate) - (gupdate) - C:\Program Files\Google\Update\GoogleUpdate.exe /svc
O23 - Service S3: Extensiones y notificaciones de impresora - (PrintNotify) - C:\Windows\system32\svchost.exe -k print; "ServiceDll" = C:\Windows\system32\spool\drivers\W32X86\3\PrintConfig.dll
O23 - Service S3: Google Chrome Elevation Service - (GoogleChromeElevationService) - C:\Program Files\Google\Chrome\Application\90.0.4430.212\elevation_service.exe
O23 - Service S3: Google Update Servicio (gupdatem) - (gupdatem) - C:\Program Files\Google\Update\GoogleUpdate.exe /medsvc
O26 - Debugger: HKLM\..\SppExtComObj.Exe: [VerifierDlls] = C:\Windows\system32\SppExtComObjHook.dll
O26 - Debugger: HKLM\..\osppsvc.exe: [VerifierDlls] = C:\Windows\system32\SppExtComObjHook.dll


--
End of file - Time spent: 9,4 sec. - 9832 bytes, CRC32: FFFFFFFF. Sign: ᛺

**Comment by mesaglio** [comment]
Buenassss, como va?
Primero que nada, te comento que este foro es para alumnos/ex-alumnos de UTN FRBA para la materia Sistemas Operativos de Ingenieria en Sistemas de Informacion.

Despues, ojo con lo que analisas. Entiendo que ese programa te esta analizando lo que tenes ahora corriendo, pero tu crash fue con otros programas (**supongo**).

Intentaria buscar [logs de windows en caso de que se rompa](https://www.google.com/search?q=windows+crash+log+location&ei=3HquYJLIOrDW5OUP9oOagAE&oq=windows+crash+log+&gs_lcp=Cgdnd3Mtd2l6EAMYADIECAAQEzIECAAQEzIECAAQEzIICAAQFhAeEBMyCAgAEBYQHhATMggIABAWEB4QEzIICAAQFhAeEBMyCAgAEBYQHhATMggIABAWEB4QEzILCAAQFhAeEBMQiwM6BwgAEEcQsAM6BwgAELADEENQpg1Ypg1g9xJoAnACeACAAWuIAcABkgEDMS4xmAEAoAEBqgEHZ3dzLXdpesgBCrgBA8ABAQ&sclient=gws-wiz) y arrancaria por [aca](https://www.supereasy.com/how-to-view-crash-logs-in-windows-10/).
Tambien podrias instalarte [MalwareBytes](https://es.malwarebytes.com/) y pegarle un scan 👍 
Ya que estamos tambien podrias revisar los programas que se ejecutan al inicio de windows.

PD:  Medio turbina el hash `C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy\ShellExperienceHost.exe`

Cierro el issue ya que no corresponde con la finalidad del repo.
Exitos!!
