### ISSUE TITLE
Duda sobre planificacion y cuando pide tarea el tripulante

### ISSUE THREAD

**Issue by SantiagoOrlando29** [sisoputnfrba/foro#2114]
Buenas!
1. Con mi grupo nos surgió la duda de en que cola se tiene que encontrar el tripulante al momento de pedir la próxima tarea.
Por ejemplo: un tripulante recibe la primer tarea al escribir en consola INICIAR_PATOTA, estando en la cola de New. Luego de recibir la tarea pasa a la cola de READY. Y suponiendo que es el primer tripulante entra a ejecutar y va a la cola EXEC. Si esa tarea no era de I/O la próxima tarea la pide siguiendo en la cola de EXEC? Y en caso de que esa tarea si fuera de I/O va a la cola de BLOQ, y cuando termina el tiempo de esa tarea, la próxima tarea la pide siguiendo en la cola de BLOQ? 

2. También queremos asegurarnos de hacer lo correcto en la planificación FIFO. Por ejemplo, si el tripulante 1 va de la cola EXEC a BLOQ, y un instante después llegan 10 tripulantes a la cola de READY. Cuando el tripulante 1 salga de BLOQ y entre a READY, se va a tener que ubicar después de los 10 tripulantes que llegaron?

Saludos!

**Comment by iago64** [comment]
Buenas! como va?

1.- Tengan en cuenta que el "pedir la siguiente tarea" no forma parte de la ejecución, simplemente es algo extra que tienen que hacerlo porque la memoria no esta en el mismo lugar que el planificador, con lo cual, si terminan una tarea, en el instante que terminan piden la siguiente y en base al resultado, seguirán ejecutando, se moverán hacia la nueva ubicación o en caso de que no tengan mas tareas tendrá que finalizar.

2.- Si señor, son colas, cuando algo llega, va al final de la misma.

Saludos.-

**Comment by SantiagoOrlando29** [comment]
Perdón pero el punto 1 no me cierra. Decís que en el instante que terminan una tarea piden la siguiente tarea. O sea que tienen que esperar a recibir la siguiente tarea y mientras tanto no va a poder entrar otro tripulante a ejecutar a la CPU? Y en caso de que la tarea que estuviera realizando fuera de I/O, o sea que está en BLOQ, también va a pasar que cuando termina la tarea y pide la siguiente otro tripulante no pueda empezar a ejecutar sus tareas de I/O hasta que la reciba y salga de BLOQ?

Saludos.-

**Comment by ncoen97** [comment]
Buenas, creo que no estaría taan mal que no pueda entrar otro tripulante a ejecutar a la CPU, tengan en cuenta que estas tareas administrativas (como enviar mensajes a memoria, hacer cambios de colas, etc) le corresponderían al tiempo en el que el sistema operativo (en este caso el discordiador) se mete en la cpu para poder administrar el sistema. En nuestro TP no les pedimos representar al sistema operativo dentro de colas ni planificarlo, pero este sería la "respuesta teórica" a tu consulta. Yendo a la implementación, no dejaría a los tripulantes en el estado en el que estaban mientras reciben la respuesta de Mi-RAM para que no frenen a los otros procesos que quieren seguir ejecutando o haciendo I/O, sobre todo teniendo en cuenta que son todas colas fifo en las que siempre el proceso que sale queda último para volver a entrar.
Piénsenlo un poquito más teniendo estas cosas en cuenta y cualquier cosa nos vuelven a consultar.
Saludos!

**Comment by SantiagoOrlando29** [comment]
Perfecto. Quedó más claro!
Muchas gracias!
