### ISSUE TITLE
Dudas sobre bitacora y tripulantes ims

### ISSUE THREAD

**Issue by heinHertz** [sisoputnfrba/foro#2115]
Hola tengo varias dudas del modulo I-mongo-Store: 

1. cuando un tripulante yo este mas dentro del sistema, ya sea expulsado u cualquier motivo, tengo que eliminar su Bitacora? por ejemplo Tripulante12.ims  borro todo el archivo? 

2. a) Estos archivos TripulanteXX.ims son simples logs? 
b) OBTENER_BITACORA 1  hay que serializar TODO el TripulanteXX.ims y pasarlo a discordiador?

**Comment by iago64** [comment]
Buenas! como va?

1.- Las bitácoras no se borran

2.a.- Los tripulante .ims son iguales que los files pero con menos campos (solo tienen Size y la lista de bloques que los componen).

2.b.- Si, tienen que mandarle los datos.

Saludos.-

**Comment by heinHertz** [comment]
Ah Gracias. Me va quedando claro. Sobre la respuesta 2a:   
1 . Entonces los datos se guardan en realidad en el Blocks.ims ?

2. sobre estos datos:  teniendo en cuenta que el enunciado dice que  esos datos "será información relevante a las acciones que realice cada tripulante"  esas acciones pueden ser:
```
Se mueve de X|Y a X’|Y’
Comienza ejecución de tarea X
Se finaliza la tarea X
Se corre en pánico hacia la ubicación del sabotaje
Se resuelve el sabotaje

```
mi consulta es sobre el formato de guardado que pueden tener en Blocks.ims esas acciones de tripulantes, o sea QUE se guarda:
a)es como dice en la hoja 29 del anexo 2:   TAREA PARAMETROS;POS X;POS Y;TIEMPO
 ¿ Habria que poner algo parecido a   SE_MUEVE;20;20;50;30   (un string sin o con '\0'  para finalizar)     ? 

gracias!

**Comment by iago64** [comment]
Buenas!

1.- Si, los datos se guardan en el Block.ims, justo agregamos un ejemplo en la errata de hoy.

2.- El formato de las lineas de la bitácora tienen que ser el que les pasamos en el enunciado, justamente porque es un "log" amigable.

Saludos.-
