### ISSUE TITLE
Duda discordiador tareas IO

### ISSUE THREAD

**Issue by andresbulgheroni** [sisoputnfrba/foro#2116]
Buenas, tengo una duda sobre que un tripulante a la vez puede ejecutar los ciclos de bloqueado a la vez.

inicie dos tripulante de una misma patota en default, es decir los dos tienen la misma posición y llegarían a la tarea al mismo tiempo
cuando llegan a la tarea que es una IO me paso que el segundo tripulante entro primero a ejecutar los ciclos de bloqueado antes que el primero.

quería consultar si es una obligación que el tripulante uno, realice los ciclos de bloqueado antes que el tripulante dos.

A la segunda vuelta que lo corrí , el tripulante uno ejecuto primero los ciclos de bloqueado.
Saludos

**Comment by iago64** [comment]
Buenas! como va? 

Eso de que cambien el orden es una condición de carrera de libro. 
En el caso que estas planteando es una diferencia bastante irrelevante, ya que ambos salen al "mismo tiempo" y del "mismo lugar", al final de cuentas lo importante es que después de ese momento donde se ordenan por I/O, ese orden no cambie.

Saludos.-
