### ISSUE TITLE
Segmentación Pura : "Fusión" de segmentos libres 

### ISSUE THREAD

**Issue by jcastagno99** [sisoputnfrba/foro#2117]
Basandome lo que pregunté en un issue anterior, cuando en miriam (mi-ram-hq) me llegue una solicitud de iniciar patota y yo tengo lugar SOLO para guardar el PCB y no el segmento de tareas, se debería rechazar la solicitud, con esto como base mi duda es la siguiente:

Cuando me llega la solicitud, lo primero que hago es buscar un segmento para guardar el pcb y ocuparlo, luego busco un segmento para las tareas y en el caso de no encontrar ninguno (ya habiendo compactado) y de rechazar la solicitud yo puedo simplemente marcar como "libre" el segmento que ocupé con el PCB en primera instancia y que luego cuando se compacte se junte con otros libres.
El otro caso es que yo debería juntar en ese momento el segmento libre con otro libre contiguo (si lo hubiera).

Esto lo pregunto porque puede pasar en el primer caso que se trigeree una compactación más rapido (porque por ejemplo me quedaron mas segmentos libres pero de un tamaño similar al del pcb dependiendo el algoritmo), el enunciado no específica que hacer en este caso (y no se si es un caso border o no)

De todas formas lo que cambia es que una siguiente petición podría pedir compactar de usarse el primer caso (y de ahí todo funciona igual) o que con el segundo caso se pueda ahorrar una compactación (o no dependiendo los tamaños)

**Comment by iago64** [comment]
Buenas! Como va?

Fijate que en la errata que publicamos hoy actualizamos un toque el enunciado y unificamos la creación de las patotas, con lo cual, podrías calcular previamente el tamaño de lo que vas a guardar (entre PCB, TCBs y el listado de tareas) y ahí vas a poder decidir si compactas o si simplemente rechazas por falta de espacio.

Saludos.-

**Comment by jcastagno99** [comment]
Buenas, estuve viendo el cambio, pero sigo con la misma duda (que creo que no la exprese muy bien antes), en terminos mas sencillos, cuando me llega una solicitud (nueva patota) ¿puedo dejar los segmentos creados (por ejemplo el creado por el best fit) aunque despues rechaze la solicitud? cuando se compacte va a volver a como estaba antes, pero mientras, cree un segmento que va a estar libre

**Comment by iago64** [comment]
Buenas!

Justamente ahora la idea es que antes de compactar o crear un segmento, controles si entra todo (TCB, Tareas y PCBs) y si entra hagas lo que sea necesario (crear segmentos, compactar, etc) y si no no cambie la memoria. 
Justamente este cambio es porque necesitamos que estemos todos alineados al momento de las pruebas ya que queremos que las pruebas sean totalmente determinísticas y podamos saber cuando hay una compactación, como se reservan los segmentos o cuando hay un fallo de página (en el caso del esquema de paginación)

Saludos.-

**Comment by jcastagno99** [comment]
Bien, entonces me surge una duda ya un poco particular a como tenemos modelado el tema de los segmentos, yo trato a la memoria en un principio como un unico segmento libre, si yo calculo que entre todo (TCB, Tareas y PCBs) voy a buscar un cacho de memoria que permita esto (o sea, un segmento libre del tamaño requerido) y una vez lo encuentre, separo ese segmento grande en pequeños segmentos (de acuerdo al algoritmo enrealidad) uno para el PCB otro para las Tareas y N de tripulantes, pero entonces siempre me quedarian los datos de forma contigua, porque busco un cacho de memoria entero que pueda almacenar todos esos datos y luego lo separo.

De la otra forma (busco un segmento para solo una cosa, lo guardo, actualizo la memoria y paso a buscar otro para el siguiente dato a guardar) podia tener segmentos de manera no contigua (que creo que es mas acorde a la teoría).  

Entonces, ¿esta bien entonces que siempre queden contiguos?

Perdón si se hace muy pesado o si me estoy confundiendo en algo, le doy muchas vueltas a esto porque al bajar la idea a codigo siempre me aparecen estos casos y no se como seguir.

**Comment by gastoncastineira** [comment]
Buenas,

Medio que tener que obligatoriamente todo contiguo choca un poco con el concepto de segmentación ¿no? 
Ya para eso hacemos una asignación dinámica de memoria y listo, porque total tampoco podemos sacarle jugo a los criterios de asignación de segmentos que les pusimos en el TP porque siempre vas a tener que estar compactando.

Lamento tener que decírtelo, pero vas a tener que replantearte un poco la memoria. Cualquier cosa que necesites ya sabés dónde encontrarnos :)

**Comment by iago64** [comment]
@jcastagno99 te queda alguna duda? hay algo mas en lo que podamos ayudarte?

**Comment by jcastagno99** [comment]
Buenas, perdon la demora, sisi ya quedo resuelto cierro el issue
