### ISSUE TITLE
Consulta sobre la ejecución de los tripulantes en cada ciclo de CPU

### ISSUE THREAD

**Issue by danimontesano** [sisoputnfrba/foro#2118]
Hola, buenos días.

Con mi compañero tenemos una consulta sobre la planificación de los ciclos de reloj. Como el TP plantea que debe llevarse un modelo de multiprogramación con mi grupo planteamos un modelo de semáforos en el que se le permite a un único tripulante realizar una _acción_ (moverse, esperar o realizar tarea) durante un ciclo de reloj de forma rotativa para dar la sensación de multiprogramación. De esta forma nos aseguramos que todos los tripulantes realicen una acción, luego que todos realicen una segunda acción y así cíclicamente hasta que terminen todas sus tareas.

Acabamos de ver el video y notamos que se plantea un modelo con sleeps y nos surgió la siguiente duda:
¿Al pasar, por ejemplo, 5 segundos de un sleep debería realizarse la primera acción de todos los tripulantes en ejecución o únicamente de un único tripulante y luego de otros 5 segundos el siguiente tripulante y así sucesivamente?

Por si no nos expresamos bien dejamos un ejemplo:
Supongamos que tenemos 3 tripulantes (A, B, C) que inicialmente deben moverse una posición. 
Primera opción: Luego del sleep los 3 tripulantes quedas desplazados una unidad.

Segunda opción: Luego del sleep únicamente el tripulante A quedaría desplazado una unidad y se necesitarían 2 ciclos mas para que los 3 tripulantes se hayan desplazado.

Nosotros teníamos planificado hacerlo de la segunda forma, pero ahora no estamos seguros.

Esperamos su respuesta
Muchas gracias

**Comment by iago64** [comment]
Buenas! Como va?

Tengan en cuenta que el grado de **multiprocesamiento** que tiene el TP lo que indica la cantidad de tripulantes que van a estar ejecutando **a la par**, por lo que si tienen un grado de multiprocesamiento de 3 y tienen 3 tripulantes que tienen que moverse, los 3 se van a mover (antes o después del _sleep()_, eso da igual ya que el _sleep()_ es meramente para dar tiempo a que se vean las cosas).

Respecto al punto extra de los tripulantes, no hay drama con eso, mientras uds puedan identificarlos sin error no hay drama 😄

Saludos.-

**Comment by danimontesano** [comment]
Hola, buenos días nuevamente.
Respecto al tema de identificar a los tripulantes, genial!

Sin embargo creo que nuestra primera consulta no quedo del todo clara.
Nuestra consulta no se trata de si los tripulantes deben moverse antes o después del sleep, sino que con el concepto de "multiprogramación" y de "ejecución a la par" como mencionaste. 

Nuestra consulta está enfocada mas en como organizar los ciclos de reloj de cada tripulante. Lo que tenemos pensado es que si queremos lograr multiprogramación lo que deberíamos hacer es que, primero, todos los tripulantes cumplan el primer ciclo de reloj, luego todos los tripulantes cumplan su segundo ciclo de reloj, luego el tercero y así sucesivamente. Para poder llevar a cabo este planteamiento estábamos pensando en hacer es que cada tripulante vaya realizando de a un único ciclo de reloj. Digamos primero un ciclo del tripulante A, luego un ciclo del tripulante B, luego un ciclo del tripulante C, ya que como sabemos los threads se manejan por tiempo de ejecución y si no ponemos esta restricción puede ser que se ejecuten 15 ciclos del A, luego 13 del B, después 23 del C.

La otra opción sería que los threads corran por detrás desincronizados los unos con los otros, de esta forma se completarían los cilcos y sleeps de todos los tripulantes al mismo tiempo, pero si en vez de tener sleeps tendría otro tipo de ejecución es probable que algunos avancen mas rápidos en términos de cilos de reloj que otros.

Es decir, si yo no tuviera los sleeps:
Con la primera forma planteada los logs quedarían en orden (primer ciclo de A, primer ciclo de B, primer ciclo de C, segundo ciclo de A, segundo ciclo de B, segundo ciclo de C, tercer cilco de A....)
Mientras que en la segunda forma los logs quedarían (primer ciclo de A, segundo ciclo de A, tercer ciclo de A, primer ciclo de B, segundo ciclo de B....)

No se si quedó mas clara la explicación o si solo confundió mas. Quizá me estoy complicando mucho, y como total con los sleeps no pasa este problema debería dejarlo como la segunda opción y que los sleeps de todos los tripulantes se realicen al mismo tiempo.

**Comment by gastoncastineira** [comment]
Ojo, el TP no tiene multiprogramación, tiene multiprocesamiento y no es lo mismo

En tanto al problema, entiendo que básicamente viene la mano de querer sincronizar o no los ciclos de CPU que maneja la multitarea del TP

Yo te pregunto, ¿Te cambia algo realmente para los algoritmos que manejamos? Total, si estamos en FIFO o RR, el proceso A va a ejecutar y desalojar y darle lugar a otro indistintamente del estado de los otros procesos. A fin de cuentas, queremos ver que los tripulantes se estén planificando según FIFO y RR y eso nos vamos a dar cuenta viendo los estados de los tripulantes con la planificación pausada, por lo que no debería ser un problema en ningún caso que planteás

Si se te ocurre algo que a nosotros no al respecto lo charlamos, pero este tema de conversación salió cuando armamos la errata que salió ayer y después de muchas idas y vueltas no se nos ocurrió ningún problema de diseño grave ni para el armado de pruebas

**Comment by danimontesano** [comment]
Oka, genial, vamos viendo con lo del multiprocesamiento y cualquier cosa consultamos.
Muchas gracias.
