### ISSUE TITLE
Consulta sobre el hilo de la consola

### ISSUE THREAD

**Issue by Camila1401** [sisoputnfrba/foro#2119]
Buenas! 

Nos surgió una duda con respecto a como se maneja la consola. En un principio creamos un hilo para cada una de las acciones de la consola. Es decir teníamos un hilo principal de la consola y después se creaba un hilo por cada una de las acciones que se querían ejecutar. De esta manera se podían ejecutar varias acciones de la consola concurrentemente. La duda que tenemos es si esta bien hacerlo de esta manera o nos estamos complicando sin necesidad, y simplemente con que se ejecute una de las acciones a la vez es suficiente, y que solamente se pueda hacer otra acción una vez que se termine la actual. 

Saludos!

**Comment by gastoncastineira** [comment]
Hola!

No sé vos, pero te aseguro que yo no puedo tipear lo suficientemente rápido como para tirar un comando de consola antes que haya terminado el anterior :P
Si quieren mantenerlo así no tiene nada de malo, pero tratá de no matar hormigas con una escopeta cuando podamos volver a salir, que es bastante peligroso

**Comment by gastoncastineira** [comment]
@Camila1401 quedó resuelta la duda? podemos cerrar?

**Comment by Camila1401** [comment]
Sisi, muchas gracias!
