### ISSUE TITLE
[Mi-RAM HQ] Duda sobre dirección lógica del PCB en el TCB.

### ISSUE THREAD

**Issue by int0x80-sys** [sisoputnfrba/foro#2120]
Buenas.

Me surgio una duda respecto del uso de la dirección lógica del PCB que se tiene dentro del TCB. Mi idea principal con el manejo de la memoria es que vamos a tener que manejar un espacio de direcciones lógico. Es decir que por ejemplo, el espacio de direcciones para una patota se vería mas o menos de la siguiente manera:

```
------------------------- 0
|         PCB           |
------------------------- 8
|         TCB1          |
------------------------- 29
|         TCB2          |
------------------------- 40
|         TCB3          |
------------------------- 61
|                       |
|        TAREAS         |
|                       |
------------------------- N
```

Como el PCB siempre va a estar al inicio de mi espacio de direcciones lógica ¿Es necesario almacenar en los TCB la dirección del PCB?¿Esta mal tener el PCB al inicio del espacio de direcciones? En nuestro caso, lo que almacenariamos siempre sería un 0 en el campo PCB del TCB.

Saludos 👋

**Comment by gastoncastineira** [comment]
Buenas,

No hay ninguna restricción para que lo manejes así al iniciar, pero tomá en cuenta que a medida que se vaya liberando la memoria porque se eliminó o terminó un tripulante o patota, es memoria que vas a poder (y tener) que asignar según el criterio de asignación, por lo que no se va a cumplir siempre ese orden que proponés

**Comment by int0x80-sys** [comment]
Buenas.

Entiendo lo que queres decir.

A lo que me refiero es que esa vendría a ser mi distribución del espacio lógico de la patota (no serían direcciones física). Por lo que la distribución dentro del espacio lógico de la patota seria siempre ese. Obviamente, despues el PCB de esta patota puede estar en la posición 0x32414FABXD (bueno, el XD no). Quedara en nosotros traducir la posición 0 del PCB a su correspondiente dirección física dependiendo del esquema de la memoria.

Pero en el espacio lógico, mi PCB siempre se mantendría al inicio. Y como el campo PCB del TCB es la dirección lógica del PCB, entonces siempre lo tendría seteado en 0 para todos los TCB.

Gracias por la respuesta y saludos 👋 .

**Comment by int0x80-sys** [comment]
Buenas de nuevo.

Ya hablamos sobre este tema en soporte. Básicamente es una cuestión de diseño el que nosotros distribuyamos el espacio lógico de esta manera. Pero el campo PCB tiene que estar si o si incluido en el TCB para que las estructuras del TCB se mantengan iguales en todos los TPs, aunque nostros simplemente lo setiemos en 0.

De todas maneras, vamos a hacer la lectura correspondiente de la dirección del PCB a la hora de querer acceder al segmento PCB de manera que, si en algun momento decidimos cambiar la distribución de nuestro espacio lógico, no haya inconvenientes.

Gracias de nuevo y saludos 👋 🚀
