### ISSUE TITLE
Duda sobre tareas sin primer parametro

### ISSUE THREAD

**Issue by nickbenve** [sisoputnfrba/foro#2122]
Buenas, perdonen pero en el anterior habia dejado unas cosas que pense que eran necesarias y hacian que no se vea nada de lo escrito. Con el grupo nos surgio un problema sobre como almacenar todas las tareas de cierta patota juntas, ya que unas tienen cierta estructura (la mayoria tiene la cantidad) y otras no.

Nuestra idea es guardar las distintas tareas en una misma estructura, asi la podemos almacenar en una lista o cola en memoria. De esta forma tenemos un mejor control para obtener la tarea siguiente a ejecutar (solicitada por un tripulante).

💭 Soluciones posibles

Hacer dos estructas distintas, dado que contienen mas o menos datos. Esta solucion piede el orden de las tareas a ejecutar.

A pesar de que nos venga una tarea sin el parametro cantidad, setearle en memoria 0. Con esto lograriamos tener ambos tipos de tarea en un mismo array (y que sean el mismo tipo). Intentamos realizar esta solucion, pero nos surgen problemas a nivel memoria porque intenta escribir o leer 4 byts que no le pertenecen.

**Comment by iago64** [comment]
Buenas! como va?

Es importante que tengan en cuenta que en memoria tienen que guardar las tareas tal cual las tienen en el archivo de tareas y que después armen alguna lógica para ir obteniendo las diferentes tareas una a una.

Saludos.-
