### ISSUE TITLE
Dudas sobre los mensajes de Discordiador a Memoria

### ISSUE THREAD

**Issue by SantiagoIvan** [sisoputnfrba/foro#2123]
Buenas ! 

Veo que con la nueva versión, elminaron el mensaje INICIAR_TRIPULANTE de Memoria. Eso me generó la siguiente duda:

1- Si se elimina ese mensaje, desde Discordiador solamente le enviamos el mensaje de INICIAR_PATOTA con toda la info que Memoria necesite. Si puede crear todo, me manda un ok y sino me manda un FAIL y en discordiador no debería crear ningún tripulante ni nada relacionado con esa patota. Es asi?

2- Cito al sumodulo Tripulante
"El submódulo tripulante será una pieza clave dentro de la planificación de nuestro sistema, ya que será el encargado de recorrer la nave y realizar una serie de tareas detalladas para lograr el objetivo de llegar a salvo.
Al momento de iniciar sus operaciones, el tripulante deberá hacer una serie de comprobaciones básicas:
1- Informar al módulo Mi-RAM HQ que desea iniciar, indicando a qué patota pertenece
"
Ese mensaje que envía Tripulante a Memoria ya no debería existir entonces no?

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Efectivamente, la idea es que controlen de una si entran el PCB, las tareas y los TCBs y recien ahi hagan lo que sea necesario (compactar, reservar segmentos, etc)

2.- Ese mensaje lo que busca básicamente es que hagan un handshake como para que establezcan la conexión entre Mi-RAM y el tripulante y tienen que poder identificar de manera unívoca que tripulante y de que patota es (para ubicar mínimamente el TCB correspondiente)

Saludos.-

**Comment by SantiagoIvan** [comment]
Hola de nuevo!

Entonces no me termina de cerrar lo siguiente: En el enunciado , en la Sección Historial de Cambios dice
 "Se elimina el mensaje Iniciar Tripulante de Mi-RAM HQ ya que deben crearse en el Iniciar Patota."? 

Si yo saco de la interfaz de Memoria el mensaje Iniciar_tripulante, debería en el discordiador crear primero todos los tripulantes, pedirle a Memoria la confirmación para ver si hay lugar en memoria (y enviarle las tareas, los tripulantes id, todo lo que necesita) y si me dice Fail, tendría que borrar lo creado en Discordiador. No termino de entender

**Comment by gastoncastineira** [comment]
Buenas

Históricamente en esta cátedra siempre nos manejamos bajo el concepto de "hagan los mensajes que quieran y  necesarios

**Comment by gastoncastineira** [comment]
Buenas

Históricamente en esta cátedra nos manejamos bajo el concepto de "hagan y manejen los mensajes que quieran y sean necesarios". 2020 fue el año que probamos con interfaces definidas para los módulos y no nos gustó mucho el resultado, por lo que volvimos a como nos manejamos siempre. 
El tema con iniciar tripulante es que estaba trayendo muchísimas confusiones (sobre todo a recursantes de este modelo definido de TP) porque pensaban que era un mensaje que tenía que estar sí o sí cuando capaz por como lo estaban pensando se podía resolver todo en un iniciar patota. Si para tu TP es indispensable mantener un "crear_tripulante", podés. A fin de cuentas, cómo se creen las patotas y tripulantes no es algo que me vaya a dar cuenta cómo lo hiciste durante una entrega

**Comment by iago64** [comment]
@SantiagoIvan te queda alguna duda? hay algo mas en lo que podamos ayudarte?

**Comment by iago64** [comment]
Bueno, vamos cerrando el issue por inactividad, cualquier cosita lo pueden volver a abrir :)
