### ISSUE TITLE
Iniciar_patota durante planificación

### ISSUE THREAD

**Issue by ailengonzalezperez** [sisoputnfrba/foro#2124]
¡Hola a todos!
Tenemos dudas respecto a en qué momentos se puede inicializar una patota.

> INICIAR_PATOTA
Recibirá como parámetro la cantidad de tripulantes que tendrá la patota, un archivo de tareas que deberá ejecutar cada tripulante de la patota (se indica el formato en la siguiente sección)  y una lista de posiciones iniciales de los tripulantes. Por defecto, si no se especifica la posición de la totalidad de los tripulantes, se asume que los restantes inician en 0|0. Lo que hará será iniciar la patota en el módulo Mi-RAM HQ y luego instanciar a cada tripulante.

De acuerdo con el enunciado existe esa opción iniciar_patota a través de la consola del discordiador que implica también la inicialización de cada uno de sus tripulantes (tanto a nivel discordiador como en miRam) pero no se especifica cuándo se pueden iniciar esas patotas.
¿Se puede iniciar una patota una vez que la planificación de tripulantes ya se inició? ¿O todas las patotas se iniciarán antes de comenzar el juego, que sería con el primer iniciar_planificación?
Si lo pensamos en "modo juego" entendemos que no se puede porque sería sumar jugadores en el medio de la partida pero no sabemos si en el TP estaría aceptado.
Además, en el enunciado se habla de "pausar y reanudar planificación" pero para poder ver las cosas ordenadas y no como parte del juego en sí mismo.

¡¡Gracias!!

**Comment by gastoncastineira** [comment]
Ojo con eso. La planificación es algo activo que está siendo ejecutado en todo momento. Yo no tengo que poner en la consola "iniciar_planificacion" para que los tripulantes comiencen a planificarse de la misma manera que vos no tenés que abrir una consola que diga "iniciar_planificacion" cuando abrís cualquier programa en tu computadora. iniciar_planificacion va de la mano con pausarla

Y para responder la pregunta, sí, se pueden iniciar patotas en cualquier momento

**Comment by ailengonzalezperez** [comment]
Ahhh, eso no lo habíamos interpretado así. Como el enunciado dice: 

> Lineamiento e Implementación
> - Será un proceso multihilo que tendrá las siguientes funciones:
> - Atenderá de forma paralela a los diferentes tripulantes, coordinando sus tiempos de trabajo (ciclos).
> - Mantendrá el nivel de multiprocesamiento de acuerdo a lo indicado.
> - **Cuando reciba por la consola del discordiador el mensaje "iniciar planificación", dará comienzo a la administración de los tripulantes, la cual debe poder ser pausada ("pausar planificación") y reanudada en cualquier momento para poder revisar el estado de los mismos en forma ordenada.**
> - Organizará la ejecución de las reparaciones ante situaciones de sabotaje dentro del i-Mongo-Store.

y también menciona 

> Iniciar Planificación
> **Con este comando se dará inicio a la planificación** y reanudará la misma en caso de que se encuentre pausada. Este mensaje no contiene ningún parámetro. Para más información sobre el comportamiento de una planificación iniciada, ver Administración de los tripulantes.

entendimos que siempre estaba el primer iniciar_planificación (que sería como "iniciar juego"), lo que permitiría poder ver a los tripulantes dispuestos en el mapa antes de comenzar por ejemplo, y luego las pausas-reinicios se iban a relacionar con poder ver distintas "fotos" del sistema a lo largo del tiempo.

Saludos!

**Comment by RaniAgus** [comment]
¡Buenas! Recuerden que el TP tiene la intención de proveer una analogía a lo que haría un SO real, la temática de Among-Us es solo una "skin" por lo que el comportamiento de los mensajes está orientado en el sentido de "lo que el SO haría" y no en "hacer un juego". Por eso que todo lo que comentaba Gastón iba por ese lado: se pueden iniciar patotas en cualquier momento, al igual que en un SO real se pueden iniciar procesos en cualquier momento. 

En cuanto a los mensajes "iniciar_planificacion" y "pausar_planificación", éstos están hechos para poder testear el estado de la planificación de forma más sencilla, por lo que se deberá poder pausar y reanudar varias veces. Repito, no se trata de "sumar jugadores" ni de "iniciar juego", sino que son procesos multihilo que cargan sus instrucciones y registros en memoria y se "turnan" en el uso de los recursos que necesitan para poder ejecutarlas (CPU, I/O).

Por otro lado, tienen razón en que el enunciado dice que la planificación arranca pausada, quédense con eso. Pero recuerden que es con fines de testing, no para hacer un juego.

Saludos

**Comment by gastoncastineira** [comment]
Sumando a lo que dice Agus, el tema es que todo eso apunta a que justamente la planificación arranca pausada. Yo lo que entendí de tu primer mensaje es que para planificar debería hacer

`iniciar patota -> iniciar planificación -> iniciar patota -> iniciar patota -> iniciar planificacion ...`

Ese ultimo `iniciar planificacion` estaría de más porque la planificación ya está iniciada

**Comment by ailengonzalezperez** [comment]
Hola! Perfecto, ya nos quedó claro.
Muchas gracias a ambos!!
