### ISSUE TITLE
Que hacer con el sobrante de bit_array

### ISSUE THREAD

**Issue by julchat** [sisoputnfrba/foro#2126]
Buenas, tenía entendido que el bit_array era mejor para usar en el tp que un vector de booleanos/caracteres porque en el primer caso para cada verdadero/falso estaba ocupando un bit, mientras que en el segundo caso, ocupaba 1 byte (8 veces más).
Al investigar un poco la función, descubrí la función de creación, la cual, a partir de un char*, proporciona un t_bit_array*
Si la afirmación del principio era correcta, entonces, si en este contexto de tp tuviera 100 bloques, lo que me ocuparía 100 bytes con un vector de booleanos, me ocuparía 100 bits.
Pero entendería que en realidad no es así, que en realidad, C sigue almacenando de todas formas en bytes, aunque yo lo engañe. Dicho de otra forma, como 100 al dividirlo por 8 da un resto distinto de 0, lo que en realidad voy a tener son 13 bytes, (13*8 = 104 bits).
Ahora, si yo quisiera buscar un bloque libre en fs, me debería encargar de que esos 4 bloques "falsos" que se agregaron siempre estén ocupados, porque se suponía que mi FS tenía 100 bloques, no 104, no es así?

**Comment by ncoen97** [comment]
Buenas, para las pruebas siempre les vamos a dar valores iguales a 2^n (tanto para blocks como para block_size), así que no se hagan problema.
Saludos!

**Comment by julchat** [comment]
joya
