### ISSUE TITLE
Usar config para archivo de files y bitacoras.

### ISSUE THREAD

**Issue by julchat** [sisoputnfrba/foro#2127]
Buenas, consulta rápida:
Me serviria config.h para crear un archivo de tipo diccionario para la metadata de files y bitácoras?
En particular, config_set_value modifica el valor de una key, y si no existe, la agrega?
Y luego tendría que usar la función de config_save_in_file para persistir los cambios.
Básicamente:
1) fopen para crear el archivo en modo escritura si no existe.
2) config_create con la ruta del archivo
3) config_set_value para agregar keys y modificar los valores asociadas a las mismas, config_get_value para leer los valores
4) config_save_in_file para guardar los cambios
5) config_destroy para no tener leaks

**Comment by ncoen97** [comment]
Buenas!

Si, justamente los archivos de metadata los hicimos similares a las config para que puedan usar las commons y se ahorren un poco de lógica.

> En particular, config_set_value modifica el valor de una key, y si no existe, la agrega?

Si, de hecho pueden fijarse en [el .c repo](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/config.c) todo lo que hace. La otra cosa que deberían tener en cuenta es que config_save_in_file ya hace un `fopen()`.

Saludos!

**Comment by julchat** [comment]
gracias!
