### ISSUE TITLE
Discordiador: Consultas varias y la incógnica del Planificador

### ISSUE THREAD

**Issue by federiver91** [sisoputnfrba/foro#2128]
Buenas, 

Sigo con muchas dificultades con el nivel de conocimientos en programación que requiere este TP, con lo cual se me hace dificil, incluso, ordenarme y plantear una serie de dudas "puntuales", abstrayéndome de la sensación general de perplejidad ante cada requerimiento que el enunciado plantea. Paso las dudas que identifiqué en esta ocasión:

1) En el enunciado, el PCB (Patota) tiene una estructura con 2 ints. Sin embargo, desde Discordiador se indica que 
cuando se le pasa a la Memoria la Patota creada en INICIAR_PATOTA no debe viajar el path del archivo sino el contenido.
Que guardo entonces en el PCB? Teniendo el path informado por consola, como obtengo el contenido y lo guardo 
en la estructura del PCB para enviarlo a MiRam?

2) En el puntero PCB de la estructura del TCB que se guarda? El puntero a la Patota a la que pertecene el tripulante?

3) Ciclo de vida del tripulante: Una vez que creo la instancia (en un hilo específico desde Discordiador) y se la paso a MiRam, que debe suceder luego? Como obtengo las tareas del Tripulante? Las solicito a MiRAM desde el mismo hilo del tripulante? O es tarea del hilo del planificador?

4) EXPULSAR_TRIPULANTE. El encargado de borrar al tripulante de las colas de planificación debería ser el 
Discordiador o la Memoria? Personalmente, asumiría que es el Discordiador, pero el enunciado hace entender que MiRam gestiona completamente la acción.

5) OBTENER_BITACORA. Que se debe realizar en el Discordiador? Le enviamos un mensaje al MongoStore con el tripulante
como parámetro para obtener la bitácora. Y luego? Una vez que se tiene el enunciado no indica si se debe imprimir o que
acción puntual realizar.

Por otro lado, y bastante más importante, quisiera entender específicamente qué se espera que suceda cuando se ingresa el comando "INICIAR_PLANIFICACION" y "PAUSAR_PLANIFICACION". El enunciado es muy liviano en ese sentido y no me queda claro. Qué debe suceder, paso a paso,  funcionalmente hablando?

Gracias,
Federico Gonzalez

**Comment by iago64** [comment]
Buenas! como va?

1.- Creo que estas mezclando las cosas, por un lado tenes los datos del PCB que son como bien decís 2 valores numéricos que representan el PID y la dirección donde inician las tareas de la patota, y por otro lado las tareas de la patota que van a guardarse aparte. La aclaración viene de la mano de que hubo algunos grupos que en lugar de enviar el contenido del archivo de tareas a la memoria para que este lo guarde, le enviaban el path y justamente el Discordiador y Mi-RAM no van a estar corriendo en la misma pc.

2.- Exacto, guardas la dirección del PCB correspondiente a la patota a la cual pertenece el tripulante, ya que despues vas a necesitar las tareas de la patota y la dirección de las mismas se guardan en el PCB.

3.- El ciclo de vida del tripulante podemos resumirlo en conectarse a Mi-RAM y solicitarle las tareas.

4.- Este comando va a tener efecto en ambos módulos. En el Discordiador va a hacer que el tripulante tenga que moverse a estado Exit y despues va a tener que notificarle a Mi-RAM, para que este lo elimine del mapa y elimine el TCB que representa al tripulante.

5.- Simplemente imprímanlo por el archivo de log del Discordiador, vamos a estar agregándolo en una próxima errata, asumimos que era clara la idea de obtenerlo para imprimirlo.

Por último, respecto a los comandos de INICIAR_PLANIFICACION y DETENER_PLANIFICACION, como su nombre lo indica lo que se pide es que ningún tripulante ejecute, ni que pasen los ciclos de CPU, eso se dijo en el video del módulo de Discordiador, que si no lo viste el mismo esta linkeado en el último post de utnso.com.ar relacionado con la versión 1.2 del enunciado.

Saludos.-

**Comment by iago64** [comment]
@federiver91 te queda alguna duda? hay algo mas en lo que podamos ayudarte?

**Comment by federiver91** [comment]
Hola! Gracias por la respuesta. Sí, sinceramente me siguen quedando dudas.

Voy punto a punto, tal cual lo fui escribiendo así es más organizado.

1) No termino de entender. El segundo entero que guarda el PCB qué es? ES un puntero? Hacia donde? Por otro lado, todavia no tengo en claro teniendo el path informado por consola, como obtengo el contenido y se lo envío a Mi RAM? Además, se lo enviaría en un mensaje aparte del PCB, verdad?

2) OK

3) Y una vez que solicita las tareas? Las tiene cada tripulante en su hilo de ejecución y qué hace con ellas? Cómo ejecuta? O ejecuta el planificador al poner el TCB en Exec?

4) OK

5) OK

Por otro lado, me sigue sin quedar claro qué debería pasar especifica y puntualmente en el sistema cuando se ingresa el comando INICIAR_PLANIFICACION. 

Gracias,
Federico

**Comment by ncoen97** [comment]
Buenas.
1. El segundo entero es un puntero, pero no un puntero a la memoria de tu maquina local como obtendrías haciendo un `malloc()` (que sería un void *, algo como `0xbffd8`), sino que es un puntero dentro de la memoria que maneja el proceso Mi-RAM HQ. Por eso decimos particularmente que es la dirección lógica al inicio de las tareas (que sería algo como `8`), pero que significa esta dirección lógica? Bueno para esto necesitamos primero saber qué esquema de memoria estamos usando, en el caso de que estemos usando paginación con paginas de 32 bytes por ejemplo, la dirección 8 nos diría que estamos accediendo a la pagina 0 de nuestro proceso y dentro de la pagina cero al byte 8. Esto es lo que van a ver en la teoría (o que ya vieron, dependiendo del curso), lo mismo para el caso de segmentación.
2.  OK
3. Las tareas se van solicitando de una, y una vez que se tiene la tarea se va a poder pasar el tripulante a READY para que eventualmente pase a EXEC y se mueva hacia la ubicación indicada para realizar esta nueva tarea.
4. OK
5. OK
6. Con el comando INICIAR_PLANIFICACION se da comienzo a la planificacion que hasta el momento se encontraba pausada. Esto va a hacer que los tripulantes que estén en EXEC ejecuten y que el planificador ( que a fin de cuentas es su discordiador) haga todas las tareas que vieron en la teoría, como por ejemplo hacer los cambios de estado que considere necesarios entre las distintas colas.

Saludos!

**Comment by federiver91** [comment]
Sinceramente sigo sin entender ninguno de los 3 puntos.

Y particularmente para el punto 1 hay más preguntas hechas. El discordiador recibe un PATH por consola. Cómo obtiene el contenido de ese archivo, dónde lo guarda y qué le transmite a MiRamHQ y en qué mensaje debe enviarselo?

Para los puntos 3 y 6, es lo mismo. Sigo sin entender el ciclo de vida normal del sistema. Un diagrama de flujo con las tareas detalladas que se suceden entre los casos de uso de "INICIAR_PATOTA" e "INICIAR_PLANIFICACION" sería revelador, me parece.

**Comment by iago64** [comment]
Buenas!

Respecto al punto 1, la cuestión es relativamente simple, al recibir el path tenés que abrir y leer el archivo. Una vez que leíste los datos del archivo se los mandas a Mi-RAM HQ en el ida y vuelta de mensajes del iniciar patota (ya en mensaje exacto es algo que tienen que definir uds como grupo, no hay una única forma correcta de resolver eso)

Respecto al ciclo de vida:
1.- iniciar una patota lo cual conlleva:
- Pedirle a Mi-RAM HQ que cree las estructuras (que desde discordiador no te importa cuales ni como las crea)
- Enviarle el contenido del archivo de tareas 
- Crear los threads de los tripulantes y conectarlos a la memoria.

2.- Una vez que hiciste el paso 1 si tenes habilitada la planificación tenes que:
- Solicitarle desde el tripulante a Mi-RAM HQ la próxima tarea.
- Mover el tripulante de NEW a READY, el quien lo hace depende del diseño que tengas en tu aplicación, puede ser un hilo de planificación, puede ser el mismo tripulante que se mueve, lo importante es que pase de NEW a READY.
- Si el grado de multiprocesamiento te lo permite al llegar a READY tenes que empezar a pasar tripulantes a EXEC (mismo caso que el anterior, depende del diseño que tengan de aplicación)
- Al momento de llegar a EXEC el tripulante tiene que ver su posición actual y ver a la posición que tiene que llegar para así calcular cuantos desplazamientos sobre el eje X y cuantos sobre el eje Y, los cuales va a ir haciendo 1 por cada ciclo de CPU.

2.1.- Si NO tenes la planificación habilitada el tripulante se queda en NEW ya que no hay movimiento entre las colas de planificación.

Creo que ahí esta bastante paso a paso lo que tiene que pasar (No es un diagrama pero se acerca bastante), de todas formas hay cosas que como no tienen una única respuesta correcta no puedo decirte hace rojo o verde, porque básicamente depende de como estén diagramando el resto de componentes del TP en el grupo es como van a interactuar con el discordiador (por ejemplo los mensajes que reciben del discordiador para iniciar una patota y recibir el contenido del archivo de tareas)
De todas formas si no hay algo claro avisa y vemos como le damos una vuelta de tuerca mas.
Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @federiver91 ! ¿Quedó alguna duda con las respuestas de Dami?

**Comment by federiver91** [comment]
Buenas! Lo cierro y cualquier cosa armo otro.

Gracias por las respuestas.
