### ISSUE TITLE
[i-Mongo-Store] Uso del MD5

### ISSUE THREAD

**Issue by julchat** [sisoputnfrba/foro#2129]
Buenas, estuve avanzando un poco con el tp, y despues de haber entendido el enunciado y trazado una linea con los requerimientos, no hallo ningún uso que se describa para el MD5 que está en los Files.ims

> Para esto se almacenará un archivo de metadata por cada archivo existente en el sistema que contendrá:
> El tamaño del archivo expresado en bytes
> La cantidad de bloques del archivo
> La lista de bloques que lo conforman
> El caracter con el cual se llena el archivo
> MD5 del archivo, deberá actualizarse cada vez que se realicen modificaciones en el mismo.
> 

Pensé que tenía sentido usarlo para los sabotajes, pero no se menciona en esa sección.

> Sabotajes en Files:
> Size: Se debe asegurar que el tamaño del archivo sea el correcto, validando con el contenido de sus bloques. Reparación: Asumir correcto lo encontrado en los bloques.
> Block_count y blocks: Al encontrar una diferencia entre estos dos se debe restaurar la consistencia. Reparación: Actualizar el valor de Block_count en base a lo que está en la lista de Blocks.
> Blocks: Se debe validar que los números de bloques en la lista sean válidos dentro del FS. Reparación: Restaurar archivo.
> 
> El proceso de restauración de archivos consiste en tomar como referencia el size del archivo y el caracter de llenado e ir llenando los bloques hasta completar el size del archivo, en caso de que falten bloques, los mismos se deberán agregar al final del mismo.
> 

Capaz está un poco implícito donde dice _"Blocks: Se debe validar que los números de bloques en la lista sean válidos dentro del FS. Reparación: Restaurar archivo."_ ?
Investigué un poco que es el MD5 también, alguna biblioteca que facilite la función de hash?
Si en si es parte de la consigna implementar el MD5 para la recuperación o algo investigo más de como conseguirlo, donde almacenar los valores (porque lo que está en la metadata se tiene que comparar con algo), o debería hacer como un mapeo a memoria del archivo files y utilizarlo para saber si el archivo en fs está actualizado con lo que tengo en "memoria"?

Saludos

**Comment by iago64** [comment]
Buenas! como va?

La idea del MD5 es que puedas controlar la integridad de tu archivo y ver que efectivamente lo que tenes en los bloques, coincida, por ejemplo si decimos:
Controlen los bloques y originalmente tenían [2,3,5] con un size que dejaba la mitad del último bloque afuera y nosotros les ponemos [5,3,2] en el sabotaje vas a asumir que el contenido del 5 ahora es todo y el del 2 no, entonces al calcular el MD5 te va a dar diferente y ahí es donde te das cuenta que tenes que Restaurar el archivo.

Sobre como calcularlo, hay varias formas de hacerlo, como recomendación te diría que investigues que onda *system()*, capaz que podes "ensamblar" el archivo afuera de tu FS y tirarle el MD5 como si se lo tiraras por linea de comandos 😉 

Saludos.-

**Comment by julchat** [comment]
Debería tener una lista o estructura similar para ir almacenando los MD5 de cada archivo de recursos? La cual le actualizaría el valor del MD5 cada vez que se realiza un cambio en el archivo.

**Comment by iago64** [comment]
Buenas! Como va?

Los MD5 fijate que van en el archivo de metadata de los archivos, con lo cual no te haría falta nada extra para guardarlo 😉 

Saludos.-

**Comment by julchat** [comment]
Claro, pero lo que restauro no es el archivo de metadata (Files)?
Osea para comparar necesito dos MD5
Uno que va a estar en el files.ims, que, o se escribió naturalmente después de modificar el archivo, momento en el cual se recalculó, o el que va a estar en el files.ims en caso de que se haya modificado el archivo en un sabotaje.

Osea, 🤔, en sí lo que va a pasar es que cuando manden el SIGUSR1 se pudo estar en el medio de una operación en la que, al ser interrumpida y no ser atómica, te llevaría a un estado inconsistente del FS. Calculo que lo último que se hace es calcular el MD5, por lo cual si el MD5 que tengo en, por ejemplo, Oxigeno.ims no corresponde al que debería dar la función para el estado actual del archivo de metadata, puedo identificar que hay una inconsistencia y tengo que restaurar Oxigeno.ims a un estado anterior.

Ahora bien, si yo si puedo calcular cuál debería ser el MD5, no tengo forma a partir del MD5 de saber que parte debería modificar.

Hay algo que no debo estar entendiendo :/

**Comment by iago64** [comment]
Buenas!

Lo que restauras son los datos que están en blocks.ims, el metadata no va a fallar, de hecho fijate que una de las cosas que no se va a modificar en los sabotajes son los MD5 😉 

Saludos.-

**Comment by Nachiten** [comment]
Buenas! @julchat quedaron resueltas todas tus dudas? Así podemos cerrar, gracias!

**Comment by julchat** [comment]
sisi listo gracias
