### ISSUE TITLE
Duda con los bloqueos por emergencia

### ISSUE THREAD

**Issue by MartinTroncoso** [sisoputnfrba/foro#2130]
Buenas! Dejo dos cuestiones de los sabotajes y bloqueos por emergencia que no me quedan del todo claras.

### 📔 Citas del enunciado/videos
------------------------------------------------------------------------------------------------------------------------------------------
_En momentos aleatorios llegará un aviso de sabotaje en una región (posición X e Y). Todos los tripulantes deberán dejar sus_ _tareas en ese momento, pasando a estado bloqueado en el siguiente orden:_

_1) Los tripulantes que se encontraban en EXEC_
_2) Los tripulantes que se encontraban en Ready_
_**3) Los tripulantes que finalicen sus Bloqueos por I/O a medida que vayan concluyendo.**_

------------------------------------------------------------------------------------------------------------------------------------------
Y en el video del discordiador **(minuto 15:38)** se menciona que cuando llegue la notificación de que hubo un sabotaje, los que están bloqueados por entrada/salida tienen que dejar de ejecutar las ráfagas de I/O y quedarse como están. 

1. La duda entonces es, cuando llega el aviso del iMongo ¿los que están bloqueados por I/O siguen ejecutando hasta terminar (pasando después a la cola de bloqueados por emergencia), o se quedan como están esperando a que se resuelva el sabotaje?

2. Por otro lado, si en el archivo de configuración del iMongo tenemos una lista con 5 posiciones de sabotajes, ¿tenemos que mandar 5 señales en diferentes momentos o mandamos una y se resuelven los 5 sabotajes juntos?

Saludos!

**Comment by ncoen97** [comment]
Buenas.
1. Los que están en block por I/O se queda ahí hasta que terminan, luego se quedan en block pero pasan a estar bloqueados por emergencia.
2. Las señales las vamos a enviar nosotros de a una (mediante la consola o htop) cada vez que hagamos un sabotaje, después de haber hecho los cambios en los archivos del FS. Luego cuando el iMS reciba esa señal, va a avisar al discordiador que ocurrió un sabotaje (para la primera señal se envía la primera posición, para la segunda la segunda y así).

Saludos!

**Comment by MartinTroncoso** [comment]
Ok gracias!

**Comment by matiasfdevecchi** [comment]
Disculpen que hable sobre un issue cerrado pero iba a comentar lo mismo. En soporte me dijeron que hagamos como dice el video, los tripulantes en blockIO no trabajarán y quedarán bloqueados ahi mismo.
Según comentan en este issue, entonces si tenemos que hacer que siga ejecutando rafagas de I/O el primero que esté en BlockIO durante una emergencia?

**Comment by MartinTroncoso** [comment]
Buenas! Agrego un par de dudas mas (si quieren abro otro issue)

1. Se podría expulsar al tripulante que está resolviendo el sabotaje? En ese caso, el siguiente que se elija tiene que empezar a resolverlo de cero o solo completa los ciclos de cpu que le hayan faltado al primero?
2. El fsck se invoca antes o después de que el tripulante esté 'X' ciclos de cpu (los que diga el archivo de config) resolviendo el sabotaje?
3. Si el tripulante que se elige para resolver el sabotaje estaba en EXEC, cuando termina ¿tiene que seguir ejecutando o como se lo pasó al final de la cola de bloqueados por emergencia, pasaría a exec el primero que estaba en ready?

**Comment by iago64** [comment]
Buenas! como va?

@matiasfdevecchi la idea es que cuando tengan un sabotaje toda la planifnicación de todos los tripulantes este pausada salvo para el que fue a resolver el sabotaje, esto incluye el que no "ejecuten" ciclos de CPU en Block por I/O.

@MartinTroncoso 
1.- No, es muy rebuscado ese caso, no lo vamos a tener en cuenta.
2.- Antes, lo hacen primero y cuando les contestan ahí se van a block.
3.- Respetan el orden de salida, es un caso muy muy borde también.

Saludos.-

**Comment by matiasfdevecchi** [comment]
@iago64 entonces, si los tripulantes de BlockIO no reciben quantum y no terminan su ciclo, nunca concluirán su quantum y el item 3 es innecesario, no?

3) Los tripulantes que finalicen sus Bloqueos por I/O a medida que vayan concluyendo.

Creo que en este issue se dijeron dos cosas distintas:
"Los que están en block por I/O se queda ahí hasta que terminan, luego se quedan en block pero pasan a estar bloqueados por emergencia"
"la idea es que cuando tengan un sabotaje toda la planifnicación de todos los tripulantes este pausada salvo para el que fue a resolver el sabotaje, esto incluye el que no "ejecuten" ciclos de CPU en Block por I/O."

En la primer cita se hace referencia a cuando terminan, por lo tanto siguen trabajando, y en la segunda cita se dice que no trabajan si hay sabotaje.

No quiero ser denso, pero no queremos cometer un error el cual puede ser motivo de desaprobación en el coloquio

**Comment by iago64** [comment]
Buenas!

@matiasfdevecchi Si, básicamente lo que queríamos decir (y no quedo claro pero lo anotamos para una próxima errata) es que justamente van a entrar después de los que estaban en EXEC y READY porque no se ejecutaban ciclos de CPU en I/O.

Por otra parte, en el coloquio solo van a desaprobar si no hicieron nada durante el cuatri y sus compañeros les carrearon el TP, el mismo es un cierre teórico de lo que hicieron y justamente algo que va a salir en el coloquio es que cuando i-mongo tiene un sabotaje es como cuando una impresora se queda sin tinta o sin papel, no puede seguir con las operaciones de I/O hasta que alguien lo arregle, por ejemplo recargue papel o cambie la tinta/tóner de la impresora o en el caso del TP alguien ejecute el FSCK.

Saludos.-

**Comment by matiasfdevecchi** [comment]
Buenas @iago64, genial! Muchas gracias por aclarar las cosas
