### ISSUE TITLE
[i-Mongo-Store] Duda sobre sabotaje "Blocks"

### ISSUE THREAD

**Issue by snouthill** [sisoputnfrba/foro#2131]
Buenas, tengo una duda sobre el siguiente sabotaje. ¿Contra qué se debería hacer esta validación?
Pensé en verificar que los números de bloque estén comprendidos en el bitmap.

### 📔 Cita del enunciado

> **Blocks:** Se debe validar que los números de bloques en la lista sean válidos dentro del FS. 
> **Reparación:** Restaurar archivo.

**Comment by julchat** [comment]
Calculo que tenés que comparar el tamaño entero del block.ims contra el block_size y la cantidad de bloques en el superbloque, de tal forma que tamaño block.ims = block_size de superbloque.ims * blocks de superbloque.ims, pero esperemos a la respuesta de un ayudante

**Comment by iago64** [comment]
Buenas! como va?

Mil disculpas se me paso este mail :(

Si el sabotaje es del archivo blocks.ims es como dice @julchat, tienen que validar que el tamaño cuadre con la multiplicación del tamaño de los bloques * la cantidad de bloques.

Si el sabotaje es en la propiedad Blocks de la metadata de los archivos, ahí tienen 3 checkeos:
1.- Ver si algún bloque se pasa de la cantidad máxima (por ejemplo les ponemos el bloque 1024 y en el FS solo tienen 512 bloques)
2.- Validar que los bloques estén ocupados en el bitmap (ya que capaz les seteamos un bloque vacío)
3.- Ver si el orden de los bloques esta bien y para eso tienen que validar con el MD5 para ver que el orden de los bloque este ok (posiblemente solo falle si cambian el último bloque)

Saludos.-

**Comment by snouthill** [comment]
Muchas gracias a los dos!
