### ISSUE TITLE
Conflicto en enunciado

### ISSUE THREAD

**Issue by matiasfdevecchi** [sisoputnfrba/foro#2133]
Buenas, encontramos dos cosas en conflicto dentro del enunciado con la v1.2 (va a explotar la nave):

Página 4 - v1.2 
Se elimina el mensaje Iniciar Tripulante de Mi-RAM HQ ya que deben crearse en el Iniciar Patota.

Página 13 - Submódulo Tripulante - Instructivo
Informar al módulo Mi-RAM HQ que desea iniciar, indicando a qué patota pertenece.

Por un lado se informa que el INICIAR_PATOTA creará los TCBs pero por el otro el tripulante debe informarle a la Ram que cree su TCB según entiendo.

Consultamos en el labo para verificar (ya tenemos implementado INICIAR_TRIPULANTE en Mi-RAM HQ) y nos dijeron que podemos dejarlo así. Es correcto o aplicamos los cambios?

**Comment by iago64** [comment]
Buenas! Como va?

Eliminamos el mensaje de Iniciar Tripulante porque hubo varias consultas acerca de que pasa si inician el PCB, cargan las tareas y recién se dan cuenta en el tripulante 4 (de 6) que no tienen espacio.
La idea es que el iniciar patota calcule si hay espacio suficiente en memoria para cargar el PCB, los TCBs y las tareas.

Si ya tienen algo implementado, pero respeta lo de revisar antes de hacer cualquier cambio en la memoria si tienen espacio suficiente no hay problema.

Saludos.-

**Comment by frandom00** [comment]
Buenas, disculpen que me meta, pero me surge una consulta de esta respuesta, el discordiador que deberia hacer con los tripulantes si no hay espacio en memoria para crearlos?, no los crea?

**Comment by iago64** [comment]
Buenas! como va?

Simplemente no los crean y devuelven un mensajito que diga: *No hay mas espacio.*

Saludos.-

**Comment by matiasfdevecchi** [comment]
Ok, gracias. Entonces sería una fe de errata para modificar el ciclo del tripulante, no? Cierro el issue, saludos
