### ISSUE TITLE
Como bloquear un dropdown si otro esta en active?

### ISSUE THREAD

**Issue by AgustinHDS** [sisoputnfrba/foro#2134]
Hola, estoy creando mi primera pagina web por reto personal, y quiero hacer algo simple para un test con javascript.
He tratado de hacerlo de varias maneras pero no logro el resultado que quiero. Alguien podria tomarse la molestia de armar la estructura asi puedo revisarla y aprender como se hace?

Objetivo:

Tengo dos dropdown, quiero que cuando seleccione Active en el primero, el segundo dropdown se ponga automaticamente en Active y se bloquee, para que el usuario no pueda interactuar con este.

Como podria hacerlo usando solo javascript?

**Comment by iago64** [comment]
Hola, que tal? Este es un foro de consultas para la cátedra de Sistemas Operativos de la UTN FRBA.

Saludos.-
