### ISSUE TITLE
Eliminar TCBs con Memoria Paginada

### ISSUE THREAD

**Issue by Cande175** [sisoputnfrba/foro#2136]
Buenas tardes, les cuento la duda que nos surgió con mis compañeros respecto a memoria con paginación simple.

Escenario: Tenemos contiguos 1 PCB tamaño fijo, 1 Tareas (tamaño varia según el pcb), N TCBs tamaño fijo.
Qué ocurre si un TCB pasa a "EXIT", ¿Hay que eliminarlo de la memoria? En ese caso, ¿habria que "compactar" en paginación? ¿o podríamos dejarlo como fragmentación interna y simplemente liberar todo (PCB, Tareas, TCBs) cuando el proceso finalice.
Porque si yo tuviera que eliminar un tcb probablemente esté compartiendo la página con otros datos, así que no puedo borrar el marco en el que está la página porque todavía puede tener información útil.

PD: En el caso de segmentación es simple porque solo hay que liberar el segmento del TCB a eliminar.

### 📔 Citas del enunciado/videos
En nuestra implementación se deberá mantener la información (PCB, Instrucciones y TCBs) en forma contigua a lo largo de las páginas asignadas. Hay que tener en cuenta que las páginas no se separan entre las que contienen un campo u otro, sino que puede darse el caso donde, por ejemplo, el TCB llene la mitad de una página y el resto se complete con las instrucciones.

**Comment by ncoen97** [comment]
Buenas.

> ¿habría que "compactar" en paginación?

Esta no sería una solución posible, en paginación no hay compactación, y como nos manejamos con direcciones lógicas si mueven los datos de lugar van a generar inconsistencias.

> ¿o podríamos dejarlo como fragmentación interna y simplemente liberar todo (PCB, Tareas, TCBs) cuando el proceso finalice.

Podría quedar como fragmentación, pero tengan en cuenta que cuando esa pagina quede totalmente libre (si por ejemplo se eliminan varios TCBs), ahí si van a tener que liberar el frame ocupado.
Saludos!

**Comment by Cande175** [comment]
Muchas gracias por la respuesta, lo implementaremos de esa forma.

**Comment by Franpanozzo** [comment]
Buenas, nos surgió una duda que tiene que ver con este tema. Cuando nico dice: 

> Podría quedar como fragmentación, pero tengan en cuenta que cuando esa pagina quede totalmente libre (si por ejemplo se eliminan varios TCBs), ahí si van a tener que liberar el frame ocupado.

Ese frame liberado, podría después ser tomado por otro PCB?? Lo cual tendría sentido pero no tendría sentido con la parte del enunciado que dice:

> En nuestra implementación se deberá mantener la información (PCB, Instrucciones y TCBs) en forma contigua a lo largo de las páginas asignadas

Ya que el dato del proceso nuevo que entra quedaría entre paginas del proceso que libero esa pagina, no quedando contigua la información. Saludos!

**Comment by RaniAgus** [comment]
¡Buenas @Franpanozzo ! Antes que nada, te recuerdo esta parte del [readme del foro](https://github.com/sisoputnfrba/foro/blob/master/README.md):
> Si la pregunta sigue abierta y vos tenés la misma duda, podés suscribirte a la duda con el botón de Subscribe bajo Notifications. **Si la pregunta se encuentra cerrada y no resuelve completamente tu duda, no escribas en esa misma pregunta: anotá el número de issue para referirlo en tu nueva pregunta.**

Volviendo a tu pregunta, el enunciado se refiere **al contenido de las páginas asignadas**, el cual en un principio debe ser contiguo. Esto quiere decir que, por ejemplo, si eligen guardar en páginas de 32 bytes:
- PCB de 8 bytes
- Tareas de 32 bytes
- 2 TCBs de 21 bytes c/u

Si tienen implementado almacenarlos en ese orden, lo correcto sería:

- Página 1: 8 bytes del PCB + 24 bytes de las Tareas
- Página 2: Los 8 bytes que faltaban de las Tareas + 24 bytes de los TCBs
- Página 3: Los 18 bytes que faltaban de los TCBs

Por otro lado, por supuesto que (al igual que como se ve en teoría) **las páginas asignadas** per sé pueden no necesariamente ser contiguas: en el ejemplo anterior las páginas 1, 2 y 3 de la patota pueden estar físicamente repartidas en cualquier lugar de la memoria.

Saludos

**Comment by Franpanozzo** [comment]
U discúlpame, con tantas cosas colgué. Se entendió perfectamente muchas gracias por contestar agus!
