### ISSUE TITLE
Espacio de direcciones

### ISSUE THREAD

**Issue by alejcha** [sisoputnfrba/foro#2137]
Hola, consulta, entiendo que ni en el PCB ni en TCB no tenemos permitido agregar campos que nos indique que tamaño tiene el proceso o cual va a ser el espacio de direcciones, entonces, podríamos agregar un caracter especial al final de la ultima tarea, por ejemplo, para indicar que allí finalizan?

**Comment by iago64** [comment]
Buenas! como va?

Una cosa son las estructuras de PCB y/o TCB que les dimos el detalle, peeero, por otro lado tienen las estructuras que uds van a tener para administrar la memoria, en esas estructuras podrían por ejemplo tener el tamaño en bytes del segmento de tareas o tener el tamaño ocupado de la última página de las tareas 😉 

Saludos.-

**Comment by PabloOrtiz07** [comment]
Buenas noches, perdon por interrumpir en este issue pero en nuestro grupo estamos teniendo la misma problematica.  Y al leer este issue creemos que podemos solucionar el inconveniente que estamos teniendo. Pero al leer el issue reiteradas veces no estariamos entendiendo la ultima parte  donde dicen "tener el tamaño ocupado de la ultima pagina de las tareas" no se si podran dar algun otro ejemplo para despegar esta duda, gracias!

**Comment by iago64** [comment]
Buenas @PabloOrtiz07, cómo va?

Que se les ocurrió para solucionarlo a uds?

Saludos.-

**Comment by Nachiten** [comment]
> Buenas noches, perdon por interrumpir en este issue pero en nuestro grupo estamos teniendo la misma problematica. Y al leer este issue creemos que podemos solucionar el inconveniente que estamos teniendo. Pero al leer el issue reiteradas veces no estariamos entendiendo la ultima parte donde dicen "tener el tamaño ocupado de la ultima pagina de las tareas" no se si podran dar algun otro ejemplo para despegar esta duda, gracias!

Buenas! Te hago un ejemplo cortito de segmentación. De como podrías estar teniendo un segmento de un TCB por ejemplo.
Tu memoria por ejemplo tiene un total de 1024 bytes. Y tenés una tabla de segmentos de la patota 1.

Esta tabla dice lo siguiente:

| Nro Segmento | Inicio | Tamaño |
|--------------|--------|--------|
| 0            | 342    | 38     |
| 1            | 523    | 27     |

Y supongamos que el segmento 0 en este caso contiene un TCB.

Entonces, como se manejaría esta situación a nivel código?

Bueno, básicamente por un lado tendrías una estructura administrativa (seguramente un struct) que contenga la tabla de segmentos. O sea, seria una lista de segmentos donde cada segmento sabe su inicio y tamaño.

Por otro lado, tendrías dentro del malloc enorme inicial que hiciste (la memoria principal) el contenido que tiene cada uno de estos segmentos.

Ahora, cuidado. No está permitido que dentro de la memoria principal haya ningún tipo de atajo que te permita saber cuanto mide el segmento, donde termina, etc. SI podes (y debes) tener en tus estructuras administrativas (el struct mencionado anteriormente) estos datos, lo cual te permite manejar correctamente la memoria.

Espero se haya entendido, ante cualquier duda consulten. Saludos!

**Comment by alejcha** [comment]
Gracias, ya veo como podríamos implementarlo,
Ahora luego del video de la ram, me surge la siguiente duda, los tcb se
guardan en páginas o segmentos aparte?
O se debe guardar pcb y tcb contiguos en la misma página (si caben) o en el
mismo segmento, y luego las tareas
O es pcb+tareas por un lado y tcb en otro
En resumen, cual sería correcto?

Paginación:
a) Pcb+tcb+tareas
b) Pcb+tareas+tcb
c) Pcb+tareas y tcb en otra página

Segmentación:
a)
Seg0 Pcb+tcb
Seg1 tareas
b)
Seg0 Pcb
Seg1 tareas
Seg0 tcb


Gracias!

**Comment by iago64** [comment]
Buenas! como va?

Para paginación te diria que es recomendable la opción A, porque el PCB t los TCBs tienen tamaño fijo y es mas fácil después saber donde empiezan las tareas.

En segmentación la opción mas amigable es la B, ya que tenes un segmento para el PCB, uno para cada TCB y otro para las tareas, tene en cuenta que al momento de liberar un tcb tenes que marcar ese pedacito de memoria como libre y si es un segmento es mucho mas fácil de resolver ese problema 😉 

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @alejcha ! ¿Quedó alguna duda o se puede cerrar el issue?

**Comment by RaniAgus** [comment]
Bueno, cierro el issue por inactividad, si quedó alguna duda no duden en abrirlo de nuevo 👍🏻
