### ISSUE TITLE
Duda con algoritmo de Paginación

### ISSUE THREAD

**Issue by pablov23** [sisoputnfrba/foro#2138]
Buenas, tenemos una consulta sobre el módulo MiRam. Específicamente sobre el diseño del método de paginación.
 Ya tenemos armados los algoritmos para generar los marcos y conocer su dirección física. Nuestra duda es cómo guardar/acceder a los datos contenidos de cada patota en las páginas. Se nos ocurrió lo siguiente, generar otra estructura que contenga la siguiente info: 

- Cantidad de tareas 
- Cantidad de tripulantes.

Y movernos en base a esas cantidades. Pongo un ejemplo para que se entienda:

|PID | Frames |
|  1   | 1,2,3    |

La patota 1 utiliza 3 marcos. Necesito conocer info del tripulante 4, para ello debemos realizar el siguiente cálculo:

Conociendo que se guardó la estructura del PCB y de 10 tareas por ejemplo. Para calcular el desplazamiento haríamos

Tamanio_PCB + Tamanio_tarea x 10 + Tamanio_Tripulante x 3 

Conociendo cuanto se desplazó (Y sabiendo de que tamaño es el marco) puedo calcular en que marco está lo que necesito (Ya tenemos una estructura para ello) y cuánto me falta recorrer para llegar a la misma.

Cuando tengo esa información (N° Marco + desplazamiento), puedo conocer que dirección física tiene dicho marco y acceder a la información del tripulante sumando el desplazamiento.

Queríamos saber si está bien planteado, o si hay otra forma de encarar esto. Es la única que se nos ocurrió por el momento y estamos con dudas si es la mejor forma.

Muchas gracias de antemano.

**Comment by iago64** [comment]
Buenas!

Te contesto con una pregunta rapida: como sabes cuanto mide cada tarea? y como estas seguro que todas las tareas miden lo mismo?
A priori tu idea se me cae un poco por las 2 preguntas que te hice, igual no se olviden que pueden tener estructuras auxiliares.

Saludos.-

**Comment by PabloOrtiz07** [comment]
@iago64 Te habia comentado este issue #2137, pero con Pablo veron somos del mismo grupo y estamos trabajando este mismo modulo. Otra forma que estabamos pensando con lo que comentaron en  el  Issue nombrado. Seria con la estructura administrativa de cada PCB con sus respectivos TCB y las tareas. Sumando el identificador (esta estructura auxiliar nos dira en que frame esta cada patota)  Entonces si queremos saber en donde esta el tripulante 4 de la patota 2, seria algo como recorro la estructura administrativa, por poner un ejemplo el tripulante se encuentra en la pagina 2 desplazamiento 2 . Y tenemos una memoria de 32 bytes con paginas de 4 bytes cada una. Entonces sabemos por el identificador que la pagina 2 se encuentra en el frame 1 y me debo desplazar 2. Vendria por este lado? gracias!

**Comment by iago64** [comment]
Buenas @PabloOrtiz07!

Justamente las 2 preguntas que le deje a tu compañero era para que le den una vuelta de tuerca sobre que pueden hacer, a priori uds en la memoria tienen las estructuras obligatorias que nosotros les damos (PCB, TCBs y Tareas) y por lo que me contas al menos una estructura mas que les dice que pagina del proceso (o patota) esta en que frame.
Ahora bien, si uds por ejemplo al momento de crear la patota ordenan los datos de una forma en la cual puedan calcular rápido las posiciones (por ejemplo primero el PCB, después los TCB y por último las tareas? 
Que tan difícil les puede ser decir en el espacio de direcciones de la patota donde esta el TCB 3? 
Si pueden identificar dentro de su espacio de memoria (que en teoría la patota lo ve contiguo) y saben el tamaño de página, que tan difícil se les hace saber a que página tienen que ir?
Y teniendo la página, por lo que me dijiste, cuanto te cuesta encontrarla en memoria principal y/o swap?
Es importante que entiendan que nosotros como ayudantes los intentamos guiar, pero la solución la tienen que pensar uds, porque justamente en el pensar y desarrollar la solución es cuando van a realmente afianzar y entender los temas.

Saludos.-

**Comment by pablov23** [comment]
Gracias por las aclaraciones. Ya tenemos una mejor de idea cómo para seguir encarando el tema. Muchas gracias!
