### ISSUE TITLE
Datos para completar el super bloque

### ISSUE THREAD

**Issue by gastonharari** [sisoputnfrba/foro#2139]
### 📔 Citas del enunciado/videos

En el encunciado se refiere al archivo del super bloque que debe tener los siguientes campos:

- Block_size: Indica el tamaño en bytes de cada bloque, este dato será de tipo uint32_t
- Blocks: Indica la cantidad de bloques del File System, este dato será de tipo uint32_t
- Bitmap: Será un bitmap donde estará el estado de los bloques del FileSystem, donde un 0 indica un bloque vacío y un 1 indica un bloque ocupado.

Pero no especifica de donde se deben obtener dichos datos para completarlos (en el momento de la creación del mismo), de donde se debe obtener el tamaño de bloque y la cantidad de bloques?

Desde ya, muchas gracias!

**Comment by RaniAgus** [comment]
¡Buenas! Cualquier implementación para configurar ese superbloque es válida, ya sea mediante archivo config, preguntando por consola, haciendo otro mini-programita en C, a mano (?¿), etc. Escojan la solución que les parezca más cómoda. Saludos

**Comment by mauriciomartin92** [comment]
Buenas, como va?
justo me surgió la misma duda que a @gastonharari, pero no terminó de comprender tu respuesta @RaniAgus.
Si entiendo que nosotros elegimos el método de creación del archivo a piachere, pero de donde obtenemos el contenido del mismo cuando iniciamos IMongoStore?

Gracias.

**Comment by RaniAgus** [comment]
¡Buenas @mauriciomartin92 ! Para leer el superbloque (y también para escribirlo) les recomendamos investigar sobre el uso de `mmap()`, ya que pueden mapear el archivo a memoria y usar `memcpy()` para traerse o guardarse los datos de forma sencilla. Igual, el enunciado no les impide usar un `FILE*`, pero puede que se les complique más el implementarlo.

Recuerden que los datos se guardan serializados en dos `uint32_t` (de 4 bytes cada uno) y un bitmap (de `cantidad de bloques / 8` bytes):

![image](https://user-images.githubusercontent.com/39303639/121835131-d7144780-cca6-11eb-8211-a64d5c485c01.png)

En cuanto a cómo implementar un bitmap, les recomendamos usar las funciones del [TAD bitarray de las commons](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/bitarray.h).

¡Saludos!

**Comment by iago64** [comment]
Holis!

Algo para sumar a la respuesta de Agus, es que en caso de que no tengan los datos como pregunta @mauriciomartin92 por ejemplo se pueden agregar 2 líneas en el config que sean BLOCK_SIZE y BLOCK_COUNT para tener los datos para generar el superbloque (y bueno el bitmap de entrada debería estar completamente vacío) o pueden pedir los datos por consola, no les vamos a restringir eso porque sinceramente no nos preocupa como obtengan los datos, lo que nos importa es que si bajamos en FS en una prueba, en la siguiente podamos levantarlo tal cual estaba 😉 

Abrazo a la distancia!

**Comment by gastonharari** [comment]
Perfecto! Quedo clarisima la respuesta

Muchisimas gracias!
