### ISSUE TITLE
Tengo problemas para abrir el super bloque existente

### ISSUE THREAD

**Issue by Nicolas-Russo** [sisoputnfrba/foro#2140]
Buenas, cuando quiero abrir el super bloque existente con la función open me retorna -1 por lo tanto no puedo mapearla a memoria. Pero cuando no existe me lo crea bien. Así es como tengo el código:

```c
void iniciarSuperBloque(char* path){

	char* superBloquePath = string_duplicate(path);
	string_append(&superBloquePath,"/SuperBloque.ims");

	int flag = 0;
	int superBFile = open(superBloquePath, O_CREAT|O_RDWR);

	chmod(superBloquePath,777);

	struct stat infoSuperB;
	stat(superBloquePath, &infoSuperB);
	sizeSuperBloque = infoSuperB.st_size;

	if(sizeSuperBloque == 0){
		sizeSuperBloque = sizeof(int)*2+sizeof(char)*valoresIniciales.Blocks;
		ftruncate(superBFile, sizeSuperBloque);
		flag = 1;
	}

	superBlockPointer = mmap(NULL, sizeSuperBloque, PROT_READ|PROT_WRITE, MAP_SHARED, superBFile, 0);

	close(superBFile);

	if(flag == 1){
		memcpy(superBlockPointer, &(valoresIniciales.Block_Size), sizeof(uint32_t));
		memcpy(superBlockPointer+sizeof(uint32_t), &(valoresIniciales.Blocks), sizeof(uint32_t));
		memcpy(superBlockPointer+sizeof(uint32_t)*2, iniciarBitmap(), sizeof(char)*valoresIniciales.Blocks);
	}
}
```

Estuve haciendo pruebas pero no entiendo que es lo que esta fallando.

**Comment by RaniAgus** [comment]
¡Buenas! 

Como regla general, te aconsejo chequear los valores de retorno de funciones como `open()` o `mmap()`. Por ejemplo, según [el manual de `open(2)`](https://man7.org/linux/man-pages/man2/open.2.html), esta función puede retornar lo siguiente:
> On success, open(), openat(), and creat() return the new file
       descriptor (a nonnegative integer).  On error, -1 is returned and
       errno is set to indicate the error.

[`errno`](https://man7.org/linux/man-pages/man3/errno.3.html) es _algo como_ una variable global que indica el número del último error. La forma más sencilla de interpretar ese número es mediante la función `perror()` que lo lee por nosotros y nos imprime por pantalla un string con su significado:
```c
	int superBFile = open(superBloquePath, O_CREAT|O_RDWR);
	if(superBFile == -1) {
		perror("Error al abrir el superbloque");
		exit(-1);
	}
```
Entonces, por ejemplo, si `superBloquePath` es un archivo para el que no se cuenta con los permisos suficientes para abrirlo `perror()` nos va a devolver un string con ese error:
```
Error al abrir el superbloque: Permission denied
```

Agregá este chequeo y contanos qué te devuelve así te podremos ayudar mejor :)
Saludos

**Comment by Nicolas-Russo** [comment]
Agrege el chequeo y me devolvio permission denied. Lo pude arreglar sacando la funcion chmod y abriendo el archivo de la siguiente manera:
`int superBFile = open(superBloquePath, O_CREAT|O_RDWR, S_IRUSR|S_IWUSR);`
Muchas gracias, cierro el issue.
