### ISSUE TITLE
[Mi-RAM-HQ] Duda sobre el dump

### ISSUE THREAD

**Issue by totomolino** [sisoputnfrba/foro#2141]
Buenas, tenia una duda sobre el nombre del archivo donde se guarda el dump. Mi duda es, que ponemos en la parte que dice timestamp. 

### 📔 Citas del enunciado/videos

El enunciado dice que es Dump_timestamp.dmp

### 💭 Soluciones posibles

Busque tipos de timestamp y no encuentro forma de calcularlo o algo. Se agradece la ayuda!

**Comment by RaniAgus** [comment]
¡Buenas! En el enunciado dejamos como nota al pie como consejo ver la función que está en las commons en [temporal.h](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/temporal.h), la cual devuelve un string con el formato que ustedes indiquen. Por ejemplo:
```c
temporal_get_string_time("MiArchivo_%y%m%d%H%M%S.txt"); // => "MiArchivo_210614124815.txt"
```

Saludos

**Comment by totomolino** [comment]
Buenas, si eso lo habia visto, no me exprese bien, con ponerlo asi como en el ejemplo ya esta bien? Porque por ahi habia un formato especifico para el timestamp. 
Saludos!

**Comment by RaniAgus** [comment]
No hay ningún formato específico, con que sea único para cada archivo que se genere en la entrega está bien (o sea, con que indique desde hora hasta segundos es suficiente). Si quieren pueden tomarse la libertad de cambiarlo poniéndole algún guión en el medio para que sea más legible también 👍🏻 

El truco de poner la fecha (y en ese orden) es un detalle, es para que si están ordenados por nombre siempre te queden los últimos al final no importa el día o mes, ej:
```python
"MiArchivo_210614235915.txt" # 14/06/2021 a las 23:59:15
"MiArchivo_210615000332.txt" # 15/06/2021 a las 00:03:32
"MiArchivo_210704113102.txt" # 04/07/2021 a las 11:31:02
``` 

¡Saludos!

**Comment by totomolino** [comment]
Muchas gracias!!
