### ISSUE TITLE
[Mi-RAM HQ]: Duda liberación de frames al expulsar tripulante.

### ISSUE THREAD

**Issue by int0x80-sys** [sisoputnfrba/foro#2143]
Hola.

Con nuestro grupo nos surgió una duda con el tema de la expulsión de un tripulante de la memoria. En la pág 19 del enunciado, cuando se explica lo que hace el servidor de Mi-RAM HQ, se dice lo siguiente:

>**Expulsar tripulante:** eliminará un tripulante tanto de las estructuras administrativas de la
>memoria, como también del mapa. Puede incluir liberar algunos frames de la memoria y del
>swap.

Nuestra duda es: nosotros no sabemos si las páginas de los tripulantes (y por lo tanto, los frames que ocupen) son solamente de ese tripulante o si tenemos el comienzo de otro tripulante o de la sección de tareas, por ejemplo. Entonces, no podríamos liberar los frames de ese tripulante ni de la memoria ni del área de swap.

¿Deberíamos tener algun mecanismo para saber si un frame en particular pertenece solamente a un tripulante?

Saludos 👋 .

**Comment by int0x80-sys** [comment]
Encontramos [este issue](https://github.com/sisoputnfrba/foro/issues/2143) donde se habla un poco sobre este tema. Pero nos sigue quedando la duda.

¿Tenemos que tener un mecanismo para poder identificar cuantas secciones ocupan una página (es decir, saber si en una página hay info de dos tripulantes, un tripulante y parte de la sección de tareas, etc)?

**Comment by iago64** [comment]
Buenas! ¿Cómo va?
Es posible que hayas linkeado a este mismo issue? Capaz que estas haciendo refefrencia al issue #2136?

Mas allá del issue de referencia, ojo porque los datos son de las patotas, con lo cual si por ejemplo vos tenes una patota con 10 tripulantes y eliminaste 9 de esos tripulantes, es posible que estes liberando páginas que no tienen datos de tu aplicación, con lo cual, ahí si deberías liberarlas porque ya no forman parte del espacio de memoria de tu proceso.
El como saber si tenes o no la página ocupada, pueden apoyarse en alguna estructura administrativa extra :wink:

Saludos.-

**Comment by int0x80-sys** [comment]
Buenas. Me había olvidado de cerrar este issue. Quedo claro.

Saludos 👋
