### ISSUE TITLE
[Duda FS] Log de informar movimiento de Bitácora

### ISSUE THREAD

**Issue by SantiagoAspres** [sisoputnfrba/foro#2144]
### 📔 Duda Bitácora

Llegamos a la parte de hacer la bitácora de los tripulantes, y nos surgió una duda con el siguiente mensaje:
>Se mueve de X|Y a X’|Y’

Cuando se informa el movimiento de un tripulante ¿Qué es lo que interesa loguear, la posición final o también las posiciones intermedias?

**Ej:** Si mi tripulante se tiene que mover de 0|0 a 3|3

Lo que se va a escribir en mi archivo Blocks.ims va a ser:

**alternativa 1:** 
>Se mueve de 0|0 a 3|3

**alternativa 2:**
>Se mueve de 0|0 a 0|1
>Se mueve de 0|1 a 0|2
>Se mueve de 0|2 a 0|3
>Se mueve de 0|3 a 1|3
>Se mueve de 1|3 a 2|3
>Se mueve de 2|3 a 3|3

**Comment by gastoncastineira** [comment]
> alternativa 2:
Se mueve de 0|0 a 0|1
Se mueve de 0|1 a 0|2
Se mueve de 0|2 a 0|3
Se mueve de 0|3 a 1|3
Se mueve de 1|3 a 2|3
Se mueve de 2|3 a 3|3

![image](https://user-images.githubusercontent.com/28161802/122141703-42cfef00-ce24-11eb-82bf-fc746086f584.png)

**Comment by SantiagoAspres** [comment]
Gracias :)
