### ISSUE TITLE
Duda sobre el uso de bitarray

### ISSUE THREAD

**Issue by Nicolas-Russo** [sisoputnfrba/foro#2145]
Buenas, quiero implimentar el uso de bitarray pero hay algunas cosas que no termino de entender:

1) La funcion ` bool bitarray_test_bit(t_bitarray*, off_t bit_index);` devuelve true si el bit en esa posicion es 1 y false si es 0?

2) La funcion `void bitarray_set_bit(t_bitarray*, off_t bit_index);` cambia de 1 a 0 el bit en la posicion inidicada?

Gracias.

**Comment by gastoncastineira** [comment]
Buenas

Si te fijás en [el header de las commons de bitarray](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/bitarray.h) vas a ver que:

1. > Devuelve el valor del bit de la posicion indicada

Por lo cual, podríamos decir que sí

2. > Setea el valor del bit de la posicion indicada

Con lo cual, lo único que hace es "darle valor" al bit. Osea, ponerlo en 1

Saludos

**Comment by Nicolas-Russo** [comment]
Oka, gracias
