### ISSUE TITLE
Duda sobre escritura en blocks

### ISSUE THREAD

**Issue by gchimento** [sisoputnfrba/foro#2146]
Hola, cómo va?

Tengo una duda sobre la escritura en el archivo blocks.ims. Suponiendo que ya tengo escrituras previas de instancias de un recurso o bitácora de tripulante y ahora quiero realizar una nueva para ese mismo recurso/tripulante, debería ver en la lista de blocks de su metadata cuál fue el último en el que se escribió y tratar de escribir en ese mismo o directamente debería empezar en uno nuevo?
En caso de ser la primera opción, estaría bien poner un `\0` al final de cada escritura para que al momento de volver a escribir en ese recurso/tripulante yo pueda hacer una lectura que me cuente los caracteres ocupados y así saber a partir de donde tengo que empezar a escribir?

Espero que se haya entendido, gracias!

**Comment by RaniAgus** [comment]
¡Buenas! 

La primera opción es la correcta, y sería erróneo contar con un caracter centinela para saber dónde termina, ya que se puede calcular en base al size del archivo y al tamaño de bloque. Creo que con un ejemplo práctico va a quedar más claro cómo sería:

Si tienen un archivo de bitácora de `100 bytes` en un FS con bloques de `32 bytes`, en su archivo `TripulanteN.ims` van a tener, por ejemplo, lo siguiente:
```cfg
SIZE=100
BLOCKS=[4,8,9,11]
```
O sea, los bloques 4, 8 y 9 van a estar completos y el bloque 11 va a tener `100 % 32 = 4 bytes` ocupados, por lo que si necesitan agregar más info adelante deben partir desde el byte 4 del bloque 11 para continuar (y pedir más bloques de ser necesario, por supuesto).

Saludos

**Comment by gchimento** [comment]
Perfecto, quedó clarísimo.

Muchas gracias, saludos!

**Comment by danimontesano** [comment]
Buenas noches, me surgió una consulta mientras leía este issue. 

En nuestro código tenemos a cada uno de los registros en la bitácora separados con un \n para que quede más prolijo a la hora de imprimirlos y de diferenciarlos unos con otros. 
Sin embargo, para localizar la ultima posición en la que tengo que escribir utilizamos el método que mencionaste previamente (100 % 32 = 4 bytes). ¿Esto es correcto o debo modificarlo? ya que de ser el caso no se me ocurriría como poder diferenciar una actividad de otra.

**Comment by RaniAgus** [comment]
¡Buenas @danimontesano ! Está perfecto. Saludos

**Comment by danimontesano** [comment]
Genial Gracias!
