### ISSUE TITLE
[Discordiador] Grado de multiprogramación

### ISSUE THREAD

**Issue by brunotello** [sisoputnfrba/foro#2147]
Hola!

El enunciado habla que el Discordiador tiene un grado de multiprocesamiento (habria N procesadores?) pero no habla de nada de multiprogramación.

En el caso que inicie patotas y la planificación este activa, todos los tripulantes pasarian de NEW a READY en el mismo momento y sin ninguna escala? (con una pausa segun el retardo)

Teniendo en cuenta que el grado de multiprogramacion es READY+EXEC+BLOCK.

Saludos!

**Comment by RaniAgus** [comment]
¡Buenas! Exactamente, en el Discordiador no hay límite en cuanto a multiprogramación. Igual, recordá que antes de pasar al tripulante a READY hay que cargar las estructuras necesarias en Mi-RAM (PCB, TCB, Tareas), por lo que puede pasar que la memoria se quede sin espacio disponible y se rechace la solicitud.

Saludos

**Comment by brunotello** [comment]
Excelente gracias!!
