### ISSUE TITLE
Dudas varias sobre imongo

### ISSUE THREAD

**Issue by heinHertz** [sisoputnfrba/foro#2148]
Hola, tengo varias dudas sobre imongo: 

1) estoy pensando en poner un productor -consumidor usando semáforos en la recepción de tareas por parte de imongo con discordiador, estaría valido ? la idea es que reciba una tarea E/S y la procese imongo una a una.

2) se puede poner el msync ( y por lo tanto mmap) en algun otro void * que no sea de blocks.ims ? por ejemplo el que tiene los bits del superbloque?  la idea es meter en una funcion sicro varias msync en una funcion sola , y hacer todo el sicro de varios archivos. 

3) un tiempo de sincronizacion para imongo i-mongo-store.config de 150000 serian un equivalente en segundos a 41 hrs, ? esto lo ley en en enunciado. hoja 4 "Aclaramos que el tiempo entre sincronizaciones en el FS es en segundos." tengo la duda de si esto es correcto.

**Comment by iago64** [comment]
Buenas! como va?

1.- No, justamente la idea es que el i-mongo store sea capaz de atender peticiones en paralelo (para la escritura de las bitácoras) y ademas que en el medio realice las operaciones de E/S de las tareas, con lo cual el producto consumidor no seria valido.

2.- Si, no hay problema con eso, lo único que importa es que no le tires msync() a algo que no sea un puntero devuelto por mmap()

3.- Si el tiempo es en segundo, igual la configuración se cambia para las pruebas, les pusimos un valor irrisoriamente alto como ejemplo, pero en las pruebas posiblemente les seteemos 30 o 60 segundos 😉 

Saludos.-

**Comment by heinHertz** [comment]
Ah gracias:
```
1) - No, justamente la idea es que el i-mongo store sea capaz de atender peticiones en paralelo (para la escritura de las bitácoras) y ademas que en el medio realice las operaciones de E/S de las tareas, con lo cual el producto consumidor no seria valido.
```
creo que voy entendiendo, lo que seria que cada hilo ( porque es multihilo )cuando recibe y almacene de los distintos tripulantes,  va escribiendo la bitacora.  ¿estaria valido poner un mutex en una funcion tipo   escribir_bitacora(mensaje) o leerla ? eso porque de la hoja 12 "Obtener Bitacora Este comando obtendrá la bitácora del tripulante pasado por parámetro a través de una consulta a i-Mongo-Store. " estoy entendiendo que esto seria concurrente con atender un tripulante?

**Comment by iago64** [comment]
Buenas! Como va?

La idea es que todo el i-mongo store sea concurrente con las diferentes peticiones de **todos** los tripulantes, entonces vos vas a tener que sincronizar el acceso a tus estructuras administrativas, pero no hacer que sean pedidos secuenciales (ya que si no medio que al pedo hacer un servidor multihilo)

Saludos.-

**Comment by heinHertz** [comment]
AH entiendo, dale que los pedidos no sean secuenciales. gracias.

Tengo otra duda, estuve buscando en los issues pero esta duda creo que no está sobre DESCARTAR_BASURA:
```
1. Verificar que exista un archivo llamado Basura.ims en el i-Mongo-Store
2. Si el archivo existe, Eliminarlo
3. Si el archivo NO existe, notificar por el log
--

Mi duda es como descartar_basura trabaja eliminando el archivo o logeando, entonces teniendo en cuenta que GENERAR_BASURA genera "B" repetidas almacenadas en los bloques del file system de imongo, existe la posibilidad de que los bloques estén llenos de B que no se estén eliminadas  ?  o directamente si se ponen B  no se pueden eliminar ? es correcto esto?

**Comment by iago64** [comment]
Buenas! cómo va?

Perdón pero no entiendo tu inconveniente al momento de eliminar el archivo, la idea de eliminar el archivo (si existe) es que marques los bloques del archivo de basura como libres para que otro archivo pueda ocuparlos. 
Ahora que lo leo de nuevo medio quemado del check, me parece que no quedo muy claro eso en el enunciado 😞 

Saludos.-

**Comment by heinHertz** [comment]
Gracias. Y en el Enunciado no aclara eso. Bueno, espero que el issue sea de ayuda a los que necesiten. gracias!!!
