### ISSUE TITLE
[Pruebas]: Duda FIFO Base

### ISSUE THREAD

**Issue by int0x80-sys** [sisoputnfrba/foro#2149]
Hola.

Estuve leyendo las pruebas que postearon. Tengo una duda con la prueba FIFO Base del Discordiador. El orden en el que se tienen que ejecutar las patotas en esta prueba es de la siguiente forma:

> \>INICIAR_PATOTA 2 plantas.txt 1|1 3|4
> \>INICIAR_PLANIFICACION
> \>INICIAR_PATOTA 1 oxigeno.txt 5|5

El resultado esperado que mencionan es:

> 1.El tripulante que se encuentra en la patota oxígeno empieza a ejecutar cuando el primer tripulante de la patota plantas pasa a realizar una E/S.
> 2.Al llegar a la posición donde genera oxígeno el tripulante 1 tiene que esperar a que terminen de trabajar los tripulantes de la patota plantas.

El problema es que el archivo de **plantas.txt** no tiene ninguna tarea de E/S, por lo que los tripulantes de la patota 1 nunca se bloquearían:

```
DESCARGAR_ITINERARIO;1;1;1
REGAR_PLANTAS;3;3;2
VER_PUBLICIDAD;5;5;1
REGAR_PLANTAS;7;7;2
IRSE_A_DORMIR;9;9;1
```

¿Es un error con el archivo?¿Agregamos alguna tarea bloqueante?

Saludos 👋 .

**Comment by ncoen97** [comment]
Buenas, era un error del documento, gracias por la advertencia!

**Comment by int0x80-sys** [comment]
Buenas.

Genial. Me alegro que haya sido de ayuda.

Saludos 👋 .
