### ISSUE TITLE
[COMMONS] Duda rapida con funcion list_find

### ISSUE THREAD

**Issue by TomasR264** [sisoputnfrba/foro#2150]
Hola! Estamos trabajando con la funcion **list_find** y para encontrar el tripulante que queremos en una lista precisamos la posicion del mismo, pero no nos queda claro como se usa la funcion _condition_ para encontrarla. Entendemos que tenemo que pasarle el idTripulante para que vaya comparando con todos los elemenros en la lista y devolver un 0 si no lo encuentra o algo distinto a 0 si lo encontro, pero como se maneja exactamente eso?

**Comment by RaniAgus** [comment]
¡Buenas! Para pasarle el ID a la función que recibe `list_find` podes utilizar una inner function. Tenemos un video acerca de cómo funcionan que les puede servir: https://youtu.be/1kYyxZXGjp0

Saludos
