### ISSUE TITLE
[Tripulante] Duda al realizar tarea

### ISSUE THREAD

**Issue by brunotello** [sisoputnfrba/foro#2152]
Hola!

Tengo las siguientes dudas sobre la realización de tareas

1) 
> Las tareas que no se encuentren en este anexo consistirán en llegar a la ubicación y esperar que pase el tiempo solicitado en el estado EXEC y no tienen qué hacer ninguna operación sobre archivos de recursos.

Las tareas que no estén en el listado basicamente haría un sleep(duración_tarea) y se mantendría en EXEC, pero qué pasa cuando se despierte el hilo del tripulante? 
Lo dejo en EXEC o lo mando a READY? Si lo dejo en EXEC y el grado de multiprocesamiento es 1, no habría starvation en una patota si todas las tareas no están en el listado? (las haría todas un solo tripulante porque monopolizaria la CPU).

2)
Con las tareas de listado, los pasos serian estos? :
 

-  le aviso a I-MONGO-STORE de la realización de esa tarea
 - lo paso a BLOCK 
 - sleep(duracion_tarea) 
 - lo paso a READY 

 
3)
Cuando le pido una tarea nueva a la RAM y ya se realizaron todas, paso el tripulante a EXIT?

Gracias!

**Comment by iago64** [comment]
Buenas! como va?

1.- Las tareas que no son de E/S lo que tienen que hacer es consumir tantos ciclos de CPU en EXEC (y como son ciclos de CPU como los de movimiento van a tener que tener su sleep de retardo de CPU) como lo que indique la duración de la tarea (y por consecuencia como son ciclos de CPU van a poder ser desalojados por RR)
Respecto al starvation, mucho cuidado porque ni FIFO ni RR tienen ese problema ya que no puede llegar un proceso nuevo que ejecute antes que otro que ya estaba y por lo tanto en algún momento todos van a ejecutar.

2.- Para las tareas de E/S los pasos son:
- Ejecutar 1 ciclo de CPU para simular la petición (con su sleep correspondiente)
- Avisarle a i-mongo store que tiene que hacer algo (este paso se puede hacer antes del sleep del ciclo de cpu, no hay drama)
- Mover el tripulante a bloqueado
- Cuando le toque hacer los ciclos de CPU de bloqueado (tantos como indique la tarea y ojo porque no tiene que hacerlos todos de una ya que se pueden interrumpir ante un sabotaje) 

Saludos.-

**Comment by brunotello** [comment]
Gracias! 

Habia entendido mal entonces, los que no son E/S cuando termina la tarea ahi lo mando a READY, entendi que seguia siempre en EXEC (por eso lo de starvation)

Cierro el issue!

Gracias!!
