### ISSUE TITLE
[Sockets] Conectarse a un proceso desde multiples hilos

### ISSUE THREAD

**Issue by brunotello** [sisoputnfrba/foro#2153]
Hola!

Tengo una duda en cuanto al manejo de sockets.

Cuando creo multiples hilos (tripulantes) debería conectarme a la RAM y pedirle una tarea y luego por cada movimiento avisarle del movimiento.

Debería tener multiples sockets (1 por cada tripulante) que se conecten a puertos distintos?
 Si la respuesta es si, primero siempre me conectaria al mismo puerto de la RAM para avisarle que el tripulante esta "vivo", la RAM responderle un puerto y luego que el tripulante se conecte a ese otro puerto?

Estoy un poco perdido en este caso :/

Gracias!

**Comment by matiasfdevecchi** [comment]
Podes tener multiples conexiones en el mismo puerto. Lo importante es que puedas aceptar más de una conexión y que cada vez que aceptas una nueva conexión, crees un hilo que se encargue de atender a esa conexión en específico

**Comment by RaniAgus** [comment]
¡Buenas! Los tripulantes deben poder comunicarse en paralelo con Mi-RAM así que es correcto tener un socket por tripulante, pero veo que están un poco mareados con el tema puertos así que paso a explicar:

Antes que nada, asumo que ya leyeron la [guía de introducción a sockets](https://docs.google.com/document/d/11CH_a-Uw5CRXWgscKvrUuGQsiaqy_hE3_njJ4YXv5cI/edit), por lo que tienen nociones sobre la arquitectura cliente-servidor.

### Desde el lado del servidor
El servidor crea un `socket()`, lo vincula a un puerto (o sea, se `bind()`ea) y se queda escuchando (`listen()`) posibles conexiones.

Con `accept()` se queda bloqueado hasta que aparezca una nueva conexión y, cuando aparezca, la acepta creando **otro socket** que es vinculado a otro puerto que estaba disponible en ese momento para que se realice la comunicación. O sea, no es que pasan muchas conexiones por el mismo puerto ni el mismo socket, sino que en el momento se crea uno nuevo. Este socket que se retorna se dice que está "conectado" ya que se puede enviar (`send()`) y recibir (`recv()`) información a través de él (o sea, a partir de acá no hace falta hacer nada más).

Por otro lado, el primer socket al que le hicimos `bind()` y `listen()` puede seguir aceptando nuevas conexiones con `accept()`, por lo que lo más común en el caso de un servidor multihilo es contar con un bucle `while` que se quede siempre bloqueado en `accept()`.

### Desde el lado del cliente
El cliente crea un `socket()` y se conecta (`connect()`) a la IP y puerto a la que el servidor está escuchando. Esa función se queda bloqueada hasta que el servidor acepte la conexión con `accept()`. Cuando eso ocurre, **ese mismo socket** queda asociado a un puerto por el que se envía y recibe información y pasa a estar "conectado".

### ¿Qué es lo importante a saber?
- El único dato que necesita el servidor para poder crear un socket de escucha es el puerto al que se va a vincular y a quedar escuchando.
- Los únicos datos que necesita el cliente para poder conectarse al servidor son la IP de la máquina en donde se encuentra y el puerto en donde está escuchando. Cuando hagan pruebas localmente pueden usar `127.0.0.1` como IP, pero en las pruebas finales hay que configurarla.
- No te preocupes por el puerto en el que se va a abrir la comunicación entre el cliente y el servidor: `connect()` y `accept()` respectivamente hacen el trabajo por nosotros :)
- El servidor devuelve un socket "conectado" después de un `accept()` y el cliente, después de un `connect()`.

Otra cosa, para poder parsear el puerto (y la IP en el caso del cliente) les aconsejo usar `getaddrinfo()` ya que es la forma más sencilla. Veo que en la guía no se entra mucho en detalle así que les paso una traducción de la sección que habla de esa función en la guía Beej: https://github.com/mgarciaisaia/bgnet-spanish/blob/spanish/src/bgnet.md#getaddrinfo---prepar%C3%A1ndose-para-arrancar

Saludos

**Comment by brunotello** [comment]
Gracias @RaniAgus !

Lo voy a leer mas detenidamente y cualquier pregunta la mando por acá1
