### ISSUE TITLE
Dudas memoria (Mapa, Dump, Swap bloqueante)

### ISSUE THREAD

**Issue by Cande175** [sisoputnfrba/foro#2154]
Buenas noches, me había guardado estas dudas para el sábado pero lo publico por si le sirve a otro.

**- Mapa:**
-- Las entidades del mapa deben ser deben ser únicas y de tipo CHAR (Por lo que no podemos usar el id del tripulante). ¿Qué caracter va a ser el tripulante? ¿Cómo lo definimos? Pensamos hacer una lista de caracteres ASCII y asignar cada tripulante a uno de esos, pero no se si nos estamos volando mucho con la solución.
-- ¿Hay que poner el archivo de tareas y la cantidad de tareas restantes? Si la respuesta es afirmativa, ¿podemos manejar la cantidad de tareas restantes con una función diferente en vez de "choque" de la librería (para evitar errores si otro tripulante pasa sin querer por ahí)?

**- Dump**
-- ¿Vamos a tener 1 solo archivo DUMP que contenga VARIOS estados de la memoria en diferentes momentos?

**- Memoria Virtual**
-- Cuando hacemos el swap de memoria virtual a memoria física, ¿podemos no tratar esto como IO bloqueante? Por ejemplo, si tengo que poner a ejecutar una página que está en MV, en vez de bloquearlo y luego pasar la página a MP, simplemente paso la página a MP y le digo TODO OK sin bloquearlo en ningún momento.

Muchas gracias! 😄

**Comment by RaniAgus** [comment]
¡Buenas!
1. Recuerden que los char al ser valores ASCII en el fondo son números, por lo que mirando la [tabla](https://www.rapidtables.com/code/text/ascii-table.html) pueden decidir arrancar por la `'A'` (o sea, el 65) e ir sumando de uno en uno a medida que se generen tripulantes. Dudo que nos quedemos cortos con las letras del abecedario en las pruebas :P
2. Asumo que te referís a imprimir por pantalla los archivos de tareas y la cantidad de tareas restantes, ¿no? No hace falta, solo con mantener actualizadas las posiciones de los tripulantes alcanza.

3. Van a tener múltiples archivos cada vez que se haga un dump, por eso el formato es `Dump_<Timestamp>.dmp`, ya que ese timestamp (que es un string se genera en base a la hora en la que fue creado) permite que cada archivo dump tenga un nombre distinto. En una cita al pie les dejamos como consejo la función de `temporal.h` de las commons para generar ese timestamp.

4. En ninguna parte del enunciado les pedimos que contemplen los page faults a la hora de planificar los tripulantes en Discordiador (aunque es buena la idea (?)), así que la respuesta es sí, pueden, y de hecho háganlo así porfa.

Saludos

**Comment by Cande175** [comment]
Todo muy claro, muchas gracias!
