### ISSUE TITLE
[Mi-Ram-HQ][Mapa] Problemas con el mapa y logs

### ISSUE THREAD

**Issue by TomasBerrojalviz** [sisoputnfrba/foro#2155]
El problema que venimos teniendo con el mapa es que cuando logeamos algo por pantalla el mapa se va moviendo y luego de varios medio que se bugea junto con los logs, viendo detalladamente los tripulantes que se crean siguen estando y si se mueven tambien lo haran correctamente pero como hay varios logs luego dejan de verse ya que se "corre". Me di cuenta que este "problemita" estaba ya desde el "nivel-gui-test" que nos dieron para poder hacerlo, ya que si se logea algo pasa exactamente lo mismo, debemos no logear nada a menos que haya errores o algo super necesario? O hay alguna solucion?

**Comment by ncoen97** [comment]
Buenas.
Lo que pueden hacer que los logs vayan todos a un archivo excepto que sean de errores o cosas muy importantes (el logger de las commons tiene la opción de que salga por un archivo).
Saludos!

**Comment by TomasBerrojalviz** [comment]
Perfecto gracias, por si alguno mas lo necesitaba solo hay que cambiar el **bool is_active_console** de la funcion **t_log* log_create(char* file, char *program_name, bool is_active_console, t_log_level level);**. Para que los logs salgan por pantalla poner un true o 1, y para que solo vayan al archivo 0 o false.
