### ISSUE TITLE
[NivelGUI] Duda sobre ids

### ISSUE THREAD

**Issue by int0x80-sys** [sisoputnfrba/foro#2156]
Buenas.

Tengo una duda sobre la biblioteca de GUI que nos estan dando.

Por lo que estoy viendo, cada entidad del mapa se identifica por un id (que es de tipo char). Pero a la vez, este es el caracter con el que se va a dibujar en el mapa.

El problema que estoy teniendo es que tendría que ver como seleccionar un caracter que sea legible en el mapa y que me permita representar al tripulante.

Lo ideal a mi forma de ver es que pueda seleccionar un único caracter que se use para representar a todos los tripulantes en el mapa. Y tener el id de las entidades del mapa por separado (es decir, que el id del tripulante no sea el mismo que se usa para dibujarlo en el mapa).

¿Se puede hacer eso con la biblioteca? En caso que no ¿Cual sería la mejor forma de seleccionar el id del tripulante en el mapa? Se me ocurre que podría usar los caracteres a partir del 33 (donde empiezan los caracteres que se pueden "ver") y sumarle el id del tripulante para obtener un caracter único para cada tripulante (calculo que no vamos a tener demasiados tripulantes corriendo en las pruebas, ni que vamos a generar tantos ids).

Espero que se haya entendido mi duda. Sino cualquier cosa, avisen.

Saludos 👋 .

**Comment by iago64** [comment]
Buenas! como va?

No es necesario que el id del tripulante sea el mismo con el que lo dibujan en el mapa, por lo que pueden armarse una tablita que como bien decís arranque en el ASCII 33 y llegue al 127 y listo, problema resuelto, total, no vamos a lanzar tantos tripulantes, no nos dan los ojos para seguirlos 😄 

Saludos.-

**Comment by int0x80-sys** [comment]
Genial. Clarisimo.

Saludos 👋
