### ISSUE TITLE
Consultas i-MongoStore

### ISSUE THREAD

**Issue by matiasfdevecchi** [sisoputnfrba/foro#2157]
Buenas, repasando todos los issues del FS me surgió una duda con este https://github.com/sisoputnfrba/foro/issues/2110

Nosotros desarrollamos el tripulante de la siguiente manera:
1. Tripulante llega a su tarea consumiendo los quantums necesarios (1 por paso)
2. Solicita entrar a IO consumiendo 1 quantum
3. Cuando ya sea el proximo a ejecutar IO, envía mensaje al mongo y espera los quantums necesarios

Pero según la respuesta de ese issue, en el punto 2 ya tendríamos que mandarle al mongo que realice la tarea? Es decir, se ejecuta aunque ya haya un tripulante que este usando IO? (se que en realidad la tarea el mongo la hace mucho más rapida de lo que se queda esperando el tripulante anterior, pero me hace ruido que un tripulante use el file system cuando lo está usando otro)

**Comment by iago64** [comment]
Buenas! como va?

Si, la idea es que manden el mensaje a i-mongo antes de ir a la cola de bloqueados, simplemente porque ese quantum simula la "petición al sistema", entonces ahí es donde debería enviarse el pedido a i-mongo, por mas que después se agregue la simulación de que tiene que esperar para "ejecutarse" y que va a tomarle un tiempo X (expresado en ciclos de CPU).

Saludos.-
