### ISSUE TITLE
Dudas Mi-RAM y Discordiador

### ISSUE THREAD

**Issue by MatiasRosales** [sisoputnfrba/foro#2158]
Buenas, tengo las siguientes dudas en relación a Discordiador y Mi-RAM
Discordiador: 
1)PREGUNTA EJECUCIÓN DE TRIPULANTES: En el video dice que se ejecuta el primer tripulante de cada patota a ejecutar de manera de cola, de forma paralela pero en el pdf no aclara como es y se puede interpretar como si los tripulantes que se van instanciando se añaden a una cola y ejecutan uno por uno (de esta forma, se ejecutarían primero los de la patota 1, patota 2, etc)
NOTA MENSAJES DE ESTADO: En el video habla de mandar mensaje para cambio de estado y en el pdf no lo dice (se toma el caso de avisar, pero como detalle para que este mas completa la especificaciones en el trabajo)

MI-RAM:
1)Manejo del envio de la proxima tarea: Cada vez que recibo ese mensaje del discordiador, busco del bloque de memoria la lista de tareas que previamente se guardó del archivo, le envío una y la elimino del registro de memoria, quedando las pendientes por hacer. Esta bien planteado asi?, de esta manera las tareas se reparten entre los tripulantes de una patota.
2)El manejo del borrado de tripulantes de memoria: En el enunciado no se detalla las condiciones en las que se deben liberar del bloque de memoria a las patotas y sus respectivas tareas.

Saludos

**Comment by RaniAgus** [comment]
¡Buenas!
#### Discordiador
1. No encontré la parte del video a la que hacés referencia (estaría bueno que nos marques el minuto para así poder entender mejor), pero en la sección "Administración de los tripulantes" (pág. 10) está todo lo relacionado a la planificación de los mismos (los algoritmos, el grado de multiprocesamiento, etc).
2. En cuanto al mensaje de cambios de estado, lo vamos a tener en cuenta para revisar la próxima errata, pero si vinieron de cursadas anteriores recuerden que este cuatrimestre no les especificamos qué mensajes deben enviar (lo cual sí ocurrió en los TPs de 2020), por lo que si leyendo el enunciado asumen que ese mensaje debe enviarse no se preocupen y avancen tranquilos.

#### Mi-RAM
1. Recordá que todos los tripulantes deben realizar todas las tareas (cito el enunciado de "iniciar patota" en la consola del discordiador), por lo que no es correcto borrarlas si solo uno la pidió. 
> Recibirá como parámetro la cantidad de tripulantes que tendrá la patota, un archivo de tareas que deberá ejecutar **cada tripulante de la patota** y una lista de posiciones iniciales de los tripulantes.

2. Para paginación simple no vamos a borrar tripulantes, y en el caso de que termine sus tareas pueden simplemente marcarlo como EXIT y dejar de mostrarlo por pantalla (no hace falta que lo borren). Para segmentación, es sencillo, marcan el segmento que contiene el TCB como libre y lo consolidan de haber otros segmentos libres alrededor.

Saludos

**Comment by brunotello** [comment]
Hola, @RaniAgus perdón que me meta...

> Recibirá como parámetro la cantidad de tripulantes que tendrá la patota, un archivo de tareas que deberá ejecutar cada tripulante de la patota y una lista de posiciones iniciales de los tripulantes.

Esto no estaba muy claro, si hubiera sido por ej 

> Recibirá como parámetro la cantidad de tripulantes que tendrá la patota, un archivo de tareas en la que **todos los tripulantes tendrán que ejecutar todas las tareas** y una lista de posiciones iniciales de los tripulantes.

Creo que tal vez se hubiera entendido mejor, en nuestro equipo planteamos como lo dijo @MatiasRosales,  del listado de tareas de la patota, se van asignando a distintos tripulantes.

Se podría reveer esto en el enunciado?

**Comment by Cande175** [comment]
Perdón, metida X2 (suelo revisar los issues para no repetir dudas).

https://github.com/sisoputnfrba/foro/issues/2136
¿No hay que borrarlos de memoria? Creo que se están cruzando las definiciones con este otro issue, o tal vez entendí mal.

**Comment by RaniAgus** [comment]
¡Buenas!

@MatiasRosales 
1. Recordá tener en cuenta el `GRADO_MULTITAREA`, que en esta prueba seteado por config como "2". Es por eso que los 2 tripulantes de la patota plantas deberían arrancar en EXEC a la vez, uno en cada "CPU" digamos. Al ser FIFO y no tener E/S, permanecen en EXEC hasta finalizar. Haciendo un cálculo de cuántos ciclos le llevan a ambos tripulantes, verán que el primero debe terminar antes que el segundo.

2. En ninguna parte del enunciado dice que se debe pausar la planificación para iniciar patotas. Haciendo una analogía con un SO real sería como que habría que pausarla para abrir un programa, y eso no es así (de hecho, en ningún momento se pausa la planificación, esos comandos los agregamos nosotros con fines de testear el estado del sistema en ese momento).

Lo que dice el enunciado es lo siguiente: 
> Por otra parte, mientras la planificación esté detenida no habrá cambios de estado entre las colas de planificación. Solamente se podrán iniciar patotas, pero todos sus tripulantes quedarán en estado NEW. Aquellos que estén en EXEC deberán detener sus acciones y sus Quantum dejarán de correr.

Lo que intentamos aclarar acá es que _en el caso de que se inicien patotas y la planificación está pausada_ no deben haber cambios de estado, por lo que los tripulantes se quedan en NEW hasta que se reanude, pero si la planificación está iniciada sí deben continuar una vez se haya cargado el tripulante en Mi-RAM y se haya recibido la próxima tarea a ejecutar. Podemos revisar ese párrafo por si generó dudas.

@brunotello 
3. Piensen a la lista de tareas como el segmento de código de un programa: si uno crea varios hilos que arranquen a ejecutar la misma función, uno querría que todos los hilos ejecuten todas las líneas de código (es por eso que en memoria se carga el indicador de la próxima tarea a ejecutar, que sería como nuestro Program Counter). Mil disculpas si no quedó claro, vamos a tener en cuenta la sugerencia para la próxima errata.

@Cande175 
4. Perdón, mala mía, me corrijo: como mencionaba Nico en #2136, se elimina el TCB de la memoria y queda una fragmentación interna. Cuando esa página quede totalmente libre van a tener que liberarla.

Saludos

**Comment by gastoncastineira** [comment]
@todosalosqueagusrepondio

¿Quedaron dudas pendientes? ¿Podemos cerrar el issue?

**Comment by MatiasRosales** [comment]
Buenas, 
Me esta entrando una duda sobre la implementacion de paginacion
![image](https://user-images.githubusercontent.com/37908304/123843616-7dd42700-d8e8-11eb-99c5-ab011f42d6e0.png)

Esto quiere decir que los frames que haran referencia a cada estrucutra (PCB,TCB y tareas) de una patota serán si o si continuas y la separacion sera solo entre procesos? ejemplo, del frame 1 al 10 guardo un PCB de la patota 1 , en el 11 al 20 un PCB de patota 2 y del 21 al 59 son las instrucciones de la patota 1.

**Comment by ncoen97** [comment]
Buenas, la información está contigua si miras las páginas (espacio lógico), pero no si miras los frames de la memoria (espacio físico).
Saludos!

**Comment by MatiasRosales** [comment]
Perfecto, entonces la informacion solo sera continua en la representacion de la tabla de paginas perteneciente al proceso
