### ISSUE TITLE
[Discordiador] Duda sabotaje

### ISSUE THREAD

**Issue by int0x80-sys** [sisoputnfrba/foro#2159]
Hola.

Tenemos una duda con respecto al sabotaje. Cuando se informa de un nuevo sabotaje al Discordiador, se selecciona a un tripulante de entre los disponibles para resolver el sabotaje. Nuestra duda es:

* Una vez que el tripulante que atiende el sabotaje llega a la posición ¿Debe notificar al File System que inicie el FSCK y esperar X cantidad de ciclos en Bloqueados por sabotaje(los que nos dan por archivo de configuración)?¿Y una vez que los finalice reanudar la planificación del Discordiador normalmente?
* En caso que lo anterior sea correcto ¿Para que sirve la notificación que le manda el File System al Discordiador cuando finaliza la rutina de FSCK?

**Comment by Nan0t** [comment]
Agrego una preguntita más respecto al manejo de sabotaje : cuando llega un tripulante a new, tenemos que aceptarlo y moverlo directo a bloqueados por sabotaje, o podemos mantenerlo en new hasta que termine la rutina de sabotaje?

**Comment by ncoen97** [comment]
Buenas.
1. Si, es correcto.
2. Estaba demás, la sacamos para la versión 1.3
3. (pregunta bonus de Nan0t) No vamos a iniciar patotas en medio de un sabotaje, pero pueden contamplar el caso de la manera que les parezca mejor.

Saludos!

**Comment by int0x80-sys** [comment]
Buenaa.

Genial. Quedó todo clarisimo.

Saludos 🚀
