### ISSUE TITLE
[miRamHQ] Paginación - Dividir un INT a la mitad

### ISSUE THREAD

**Issue by Cande175** [sisoputnfrba/foro#2160]
Buenas noches!

Escenario: Quiero guardar el ID de un tripulate. No entra todo el uint32 en la pagina 2, así que guardo lo que entra y el resto lo guardo en la pagina 3.

Para guardar en la página dos puedo usar: memcpy(int guardar_dato_aca, int quiero_guardar_este_dato, size_t bytes_a_copiar)
La pregunta es. Ahora que tengo que guardar el restante en página 3, ¿Cómo obtengo el "resto" a guardar?

Gracias 😄

**Comment by RaniAgus** [comment]
¡Buenas! Podés castear el puntero que apunta a la memoria del uint32 destino a void* y usar la aritmética de punteros para desplazarte "lo que te faltó". Sin castear a `void*` no funcionaría porque un `uin32_t*` se desplaza de a 4 bytes y no de a uno. Ejemplo:

```c
void* pag1 = calloc(2, 1);
void* pag2 = calloc(2, 1);

uint32_t numero = 0x12345678; // es un número en hexadecimal

memcpy(pag1,  (void*) &numero     , 2);
memcpy(pag2, ((void*) &numero) + 2, 2);
```
Esto si yo lo imprimo con `mem_hexdump()` (una función de memory.h de las commons):
```c
puts("Lo que quería copiar:");
mem_hexdump(&numero, sizeof(uint32_t));

puts("Dónde lo copié:");
mem_hexdump(pag1, 2);
mem_hexdump(pag2, 2);
```
Me devuelve:
```
Lo que quería copiar:
0x00000000: 78 56 34 12 00 00 00 00  00 00 00 00 00 00 00 00  |xV4.............|

Dónde lo copié:
0x00000000: 78 56 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |xV..............|

0x00000000: 34 12 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |4...............|
```

Saludos

**Comment by Cande175** [comment]
Muy Claro @RaniAgus ! Habíamos pensado hacer aritmética de punteros pero no encontramos nada de como sumar X bytes en especifico. Mil gracias :)

Veo de implementarlo y luego cierro el issue.

**Comment by Cande175** [comment]
Todo bieeen, muchas gracias ❤️
