### ISSUE TITLE
Dudas Planificacion y sabotaje

### ISSUE THREAD

**Issue by SantiagoCarnezis** [sisoputnfrba/foro#2161]
Buenas, tengo unas dudas de la planificacion y del sabotaje.

Dudas Planificacion:

1. Por lo que mi grupo tenia entendido, cuando un tripulante termina su estado New, pasa a Ready y queda esperando en una cola hasta el momento en el que se libere un espacio en Exec y en ese momento cambia de estado. Nuestro problema es que en el ejemplo que hay en las pruebas, cuando termina el tripulante A de la patota 1, pasa a Exec el tripulante A de la patota 2, pero eso no esta mal? Ya que el tripulante B de la patota 1 estaba en Ready desde antes.
 ![image](https://user-images.githubusercontent.com/62964148/122658767-732acc80-d147-11eb-9cc1-98e2b775e679.png)

2. Nosotros cada vez que queremos comunicarnos con mi Ram, iniciamos una conexion, enviamos el paquete que tenemos que enviar y luego cerramos el socket. Dado que un tripulante se comunica varias veces con mi Ram, el mismo tripulante inicia varias conexiones (y las cierra apenas termina de enviar el paquete). Esta bien hacer esto? o tendriamos que iniciar la conexion una unica vez por tripulante y si ese tripulante queire comunicarse con mi Ram debe usar el mismo socket? Sería como que cada tripulante tiene un unico socket.

Dudas Sabotaje:

1. Mientras hay un sabotaje, si se inicia una patota que se hace? Se los pone a ejecutar o van a la cola de sabotaje y esperan a que se termine el sabotaje para empezar?
2. Cuando termina el sabotaje, si el tripulante que estaba resolviendo estaba ejecutando una tarea, tiene que recalcular sus ciclos? Se tiene que volver a desplazar? Si ya habia ejecutado algunos ciclos de la tarea, los tiene que volver a ejecutar?
3. Cuando dice que “todos los tripulantes deberán ser desbloqueados en el orden en el cual fueron bloqueados” que significa? Osea los desbloqueo en ese orden pero al mismo tiempo? Es decir que me puede afectar en los tripulantes en exec, ya que si yo los tenia en ready en un cierto orden, ahora los puedo tener en otro y eso hace que uno se le pueda adelantar a otro. La otra alternativa es que los vaya desbloqueando en tiempos diferentes, osea en t0 libero al primero, en t1al segundo, etc

No sabia si tenia que separar las dudas en dos issues distintos porque son de distintos temas o si dejarlas juntas porque son del mismo modulo, por las dudas las deje todas en un mismo issue. Desde ya, muchas gracias

**Comment by gastoncastineira** [comment]
Buenas

1. Lo vamos a revisar, puede que esa o RR esté mal redactada
2. Eso es una decisión de diseño que el día del coloquio nos tendrán que explicar y justificar
3. Mientras hay sabotaje no se debería poder ejecutar ninguna instrucción de la consola
4. Sí, sí, no - El comportamiento debería ser el mismo que el de los cambios de contexto por interrupción que ven en la teoría
5. No me queda claro por donde viene esta duda. En el enunciado dice un orden en el que los tripulantes deben entrar a bloqueado por sabotaje. Básicamente hay que respetar ese orden para salir

**Comment by SantiagoCarnezis** [comment]
Muchas gracias! volvi a leer el tp y viendo lo que me respondieron ya me quedo todo claro
