### ISSUE TITLE
[Memoria] DUMP 

### ISSUE THREAD

**Issue by Cande175** [sisoputnfrba/foro#2162]
Buenas, una duda muy chiquita por acá.

Tema DUMP de memoria. ¿Tiene que ser tanto de memoria virtual como principal? ¿Qué necesitan ver ustedes?

### 📔 Citas del enunciado/videos
Para cada esquema se pide lo siguiente:
[Segmentacion: ...]
Paginación:
- nro de Frame
- Estado (Libre u Ocupado)
- Id del proceso (patota)
- nro de página

**Comment by RaniAgus** [comment]
¡Buenas! El dump es solamente de la memoria principal (la memoria virtual no tiene número de frame). Quizás asumimos que con el ejemplo se vería que se iteran los frames mostrando el estado de cada uno, pero podemos revisarlo para que no queden dudas al respecto. Saludos.

**Comment by Cande175** [comment]
Entonces me parece que estoy perdida.

Yo pensaba que cuando inicio Tripulantes/Patota tengo que guardar todas las páginas del proceso en la MV, ya que nada está siendo ejecutado (Todos los tripulantes estarían en Ready y no hay nada consumiendose).

Luego en el archivo de pruebas dice "Controlar los reemplazos de páginas al momento de guardar los datos mientras se inicia la patota y sus tripulantes.". ¿Cómo van a controlar como guardamos la inicialización de patotas/tripulantes si no les mostramos la VM? ¿O me estoy salteando algo?

Archivo de pruebas: https://docs.google.com/document/d/1RVXZn5TePp9IB53Aae4inOGEpwc9Fi9PKy_vEJBNilA/edit#
Imagen de archivo de pruebas: ![image](https://user-images.githubusercontent.com/37709479/122844641-799c7e00-d2d8-11eb-8d55-a270cd0dd0e3.png)

**Comment by ncoen97** [comment]
Buenas, las páginas se cargan directamente en memoria principal, solo se cargan en swap cuando no hay más espacio en memoria principal. Esto quiere decir que cada página va a estar una sola vez en toda la memoria (no tiene una copia en MP y otra en MV). Dejo un fragmento la pagina 18 del enunciado:

> Y el proceso de swap comenzará una vez que se encuentre llena la memoria principal 

Saludos!

**Comment by Cande175** [comment]
@ncoen97 Siguiendo esa lógica, si no vamos a tenerlos nunca duplicados (solo hay que moverlos de una memoria a otra), no vamos a necesitar bit de modificado, ¿cierto?

- Gracias por la paciencia -

**Comment by ncoen97** [comment]
Correcto
