### ISSUE TITLE
[DISCORDIADOR] Sabotajes y duración

### ISSUE THREAD

**Issue by brunotello** [sisoputnfrba/foro#2163]
Hola!

Estoy implementando la resolucion de los sabotajes y me quedaron algunas dudas, estuve revisando los issues creados y me sigo mareando...

Cuando recibo del FS el mensaje de sabotaje
1) Muevo los TCBS en EXEC y READY a BLOCK_EMERGENCIA (que pasa con los que estan en BLOCK_IO ? Sigue ejecutando el IO y a medida que termina va a la cola de BLOCK_EMERGENCIA?).
2) Busco el tripulante mas cercano y lo pongo a que se mueva hasta la posicion del sabotaje. (si el tcb estaba en EXEC, dejaria la tarea pausada hasta que se solucione el sabotaje).
3) Cuando el tripulante llega a la posicion, la duracion del sabotaje cuenta como rafaga de CPU o de IO?
4) Cuando termina de solucionar el sabotaje, Paso los tripulantes en BLOCK_EMERGENCIA a READY, pero que pasa con el que fue seleccionado? va ultimo o primero a READY?

Va a haber una prueba que con la planificación pausada, que el FS reciba un sabotaje?

Gracias!

**Comment by ncoen97** [comment]
Buenas, algunas cosas las aclaramos en la version 1.3, pero paso a contestar.
1. Los que estaban en BLOCK_IO frenan y continúan una vez terminado el sabotaje.
2. Si la tarea es de ejecución de CPU van a tener que iniciarla denuevo.
3. Cuenta como rafaga de IO.
4. Esto está en el enunciado en la parte de sabotajes: "pasándolo al final de la cola de bloqueados de emergencias".
5. No.

Saludos!

**Comment by brunotello** [comment]
Excelente graciassssss!!!

Cierro el issue!

**Comment by brunotello** [comment]
Vuelvo a abrir el issue, me surgió otra pregunta, y creo que es obvia pero para confirmar..

Cuando el tripulante seleccionado para solucionar el sabotaje empieza a moverse hasta el lugar del sabotaje, cuenta como rafaga de CPU?

**Comment by ncoen97** [comment]
Exacto.

**Comment by brunotello** [comment]
Ahora si mil gracias!!!!

Cierro el issue!
