### ISSUE TITLE
Guardar, buscar y eliminar datos en Paginacion

### ISSUE THREAD

**Issue by marianopoll** [sisoputnfrba/foro#2165]
Hola, Básicamente tengo una duda en cuanto a como guardar la data en las paginas sin caer en segmentación. Por ejemplo, se da el caso de que tengamos 2 TCB en el frame 1 y 2 TCB en el frame 2. Si borras el segundo TCB del frame 1, vas a tener fragmentación interna ahí, porque te sobra un espacio entre el primer TCB y los 2 TCB del otro frame ¿Cómo podríamos validar que hay un espacio en el medio debido a que se elimino un TCB? ¿Cómo podríamos realizar una búsqueda en el siguiente caso? Otro caso seria ¿Cómo podemos saber en que posición terminan las tareas y empieza el primer TCB en un mismo frame?

### 📔 Citas del enunciado/videos
Hay que tener en cuenta que las páginas no se separan entre las que contienen un campo u otro, sino que puede darse el caso donde, por ejemplo, el TCB llene la mitad de una página y el resto se complete con las instrucciones.

**Comment by ncoen97** [comment]
Buenas.
Para el caso de eliminar un TCB, no debería afectarles que no exista porque nadie va a intentar acceder a esa dirección lógica. Lo único que deben tener en cuenta es que si una pagina queda totalmente vacía, ahí tienen que liberar el frame que ya no se usa.
Para saber donde terminan las tareas pueden guardarse en alguna estructura administrativa el tamanio total de las tareas y simplemente se lo suman a la dirección lógica del inicio de las tareas.
Saludos!

**Comment by iago64** [comment]
@marianopoll Te quedo alguna duda con la respuesta de Nico? Hay algo mas que podamos aclarar?

**Comment by marianopoll** [comment]
No, gracias
