### ISSUE TITLE
Conexión Discordiador - Mi RAM HQ

### ISSUE THREAD

**Issue by matiasfdevecchi** [sisoputnfrba/foro#2166]
Buenas, tenemos una duda respecto a la conexión de los dos módulos mencionados. 

@Nachiten menciona en el issue #2050 

> Según lo que tenemos pensado, solo existirá una instancia tanto de discordiador, como de memoria, como de FS. Pero, podrías llegar a tomar los distintos hilos (tripulantes) como conexiones distintos quizá. No creo que sea algo conveniente pero lo veo posible.

Y en base a esto tomamos que tenemos dos maneras de realizar la conexión
1. Abriendo una conexion entre los dos modulos y que todos usen esa conexión
2. Abriendo una conexión entre los dos modulos y otra entre cada tripulante y el modulo Mi-RAM HQ

Optamos por la primera por su simplicidad y ya terminamos el módulo discordiador (salvo por pequenios ajustes). Pero viendo un issue reciente de @RaniAgus esta solución podría ser incorrecta? #2153

**Comment by RaniAgus** [comment]
¡Buenas! La idea de tener un servidor multihilo en Mi-RAM es poder atender las peticiones de los tripulantes en paralelo y que haya concurrencia en la memoria, así que si tienen un único socket para la conexión se pierde esa concurrencia y, por lo tanto, no sería válido. 
Por otro lado, desde mi punto de vista la opción 2 es incluso más sencilla, ya que en la 1 (por más que no sea correcta) hay varios hilos "compitiendo" por leer y escribir en ese socket a la vez, por lo que deben haber garantizado la mutua exclusión de alguna forma para que eso funcione. En cambio, con la 2 se ahorrarían ese trabajo ya que estarían enviando y recibiendo info por sockets distintos.

Saludos

**Comment by matiasfdevecchi** [comment]
Si, usabamos mutex para garantizar la mutua exclusión, lo cual obviamente nos favorecía con el paralelismo en la ram. Lo vamos a cambiar, gracias
