### ISSUE TITLE
Duda Listar_tripulantes y sabotajes

### ISSUE THREAD

**Issue by SantiagoOrlando29** [sisoputnfrba/foro#2167]
Hola
1. Para empezar, tengo una duda cortita con el LISTAR_TRIPULANTES: El listado que tengo que devolver lo tengo que devolver en la consola del Discordiador o en la terminal de Miram?

Y ahora dudas de sabotaje:
2. Los tripulantes que están en BLOQ I/O, ya sea haciendo I/O o esperando para hacer la I/O, no participan de la selección de quien va a atender el sabotaje no? 
3. A la cola de BLOQ EMERGENCIA va solo el tripulante que resuelve el sabotaje o entendí mal el enunciado? Y todo el resto se iría a BLOQ I/O?
4. Y los tripulantes que estaban haciendo I/O o esperando para hacer I/O y justo cayó el sabotaje, pueden terminar de hacer sus I/O mientras otro tripulante resuelve el sabotaje, o tiene que esperar a que termine el sabotaje para poder continuar con sus I/O?

Gracias!!

**Comment by iago64** [comment]
Buenas! cómo va?

1.- El listado lo tienen que poner en el log y eventualmente en la consola del discordiador. En Mi-RAM no deberían imprimir nada ya que tienen el mapa.

2.- Exacto, si esta bloqueado no juega para resolver el sabotaje.

3.- Todos los que estan en EXEC / READY van a la cola de BLOQ por Emergencia.

4.- Tienen que esperar, la idea del sabotaje es análoga a cuando por ejemplo se te queda sin papel una impresora, hasta que no le cargues papel de nuevo, ningún trabajo puede continuar.

Saludos.-

**Comment by SantiagoOrlando29** [comment]
Buenísimo. Quedó todo claro
Muchas gracias!
Saludos
