### ISSUE TITLE
¿Serializar?

### ISSUE THREAD

**Issue by matiasfdevecchi** [sisoputnfrba/foro#2168]
Buenas, veo que en varios issues como el #2115 o en la página 8 del enunciado se menciona la serialización

> Por último, se recuerda que desarrollar únicamente temas de conectividad, serialización y sincronización es insuficiente para poder entender y aprender los distintos conceptos de la materia por lo que será un motivo de desaprobación.

A que se refiere con esto? Hay que serializar algo? No se vuelve a nombrar la palabra "serializar" en ninguna otra parte del enunciado

**Comment by RaniAgus** [comment]
Buenas, una definición de serialización es la siguiente:
> La serialización es el proceso de convertir un objeto en una secuencia de bytes para almacenarlo o transmitirlo a la memoria, a una base de datos o a un archivo. Su propósito principal es guardar el estado de un objeto para poder volver a crearlo cuando sea necesario.

Un ejemplo de serialización es cuando deben enviar un mensaje entre módulos y hay que guardar en un único "stream" toda la información que se va a enviar por sockets (si quieren saber más pueden ver [la parte de serialización de la charla del 1c2019](https://www.youtube.com/watch?v=GnuurOt8yqE) o la [guía de serialización](https://docs.google.com/document/d/190LLBTzHkFmD_yS8OWcUsJoIOQVKxJkUxIFtcnChr-g/edit))

Saludos

**Comment by matiasfdevecchi** [comment]
Ah buenisimo. Nosotros usamos los sockets del tp0, por ende la serialización ya está implicita (nosotros lo unico que hacemos es enviar mensaje o crear el paquete). Por ejemplo en SuperBloque.ims, ahí estamos serializando al definir los primeros 4 bytes como block size, los siguientes 4 como blocks y los demás como bitarray, no?

**Comment by ncoen97** [comment]
Buenas, a qué se refieren con que "está implícita"? Los paquetes que manden tienen que tener una serializacion similar a la del paquete del tp0 pero tienen que armarla ustedes para cada estructura que quieran enviar.

**Comment by matiasfdevecchi** [comment]
Buenas @ncoen97, me refiero a que por ejemplo para INICIAR_PATOTA del discordiador a la ram, pasamos un paquete todo en string, primero el pid, despues cantidad de tareas, despues todas las tareas una por una, y despues todos los tripulante (sequencia de tid, pos x, pos y).
Despues la ram los lee en ese orden, respetando como se envían. A eso me refiero a que lo hacemos implícitamente, quizás no era la palabra correcta
