### ISSUE TITLE
[IMongoStore] - Metadata  y actualización

### ISSUE THREAD

**Issue by alexisdona** [sisoputnfrba/foro#2169]
Buenas!

Tengo una duda en cómo manejar la información que se loguea de los tripulantes en el archivo blocks.ims. Pensamos armarlo así para oxígeno, comida y basura.

Por ejemplo:
Tenemos 10 bloques de 4 bytes cada uno, entonces tenemos un bitmap con 10 posiciones para indicar si cada uno de los 10 bloques está ocupado.

Bloques :XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX
Array bitmap : {0,0,0,0,0,0,0,0,0,0}

1. Llega el primer tripulante y pide escribir una C en el archivo de comida.ims
Bloques :CXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX
Array bitmap : {1,0,0,0,0,0,0,0,0,0} 

**Metadata de comida.ims**
tamaño : 1
bloques : 1
qué bloques ocupa : {1}
Caracter de lenado : C
MD5 : ??

Para los demás archivos de oxigeno y basura entendemos que sigue la misma lógica, pero por ejemplo si tengo que loguear en tripulante1.ims la oración "Se movió de (1,1) a (1,2)" ¿cómo lo registro en blocks.ims, cáracter a caracter? ¿Esta oración ocuparía 25 caracteres y tendría que buscar 7 bloques vacíos para poder registrarlo en blocks.ims?

Por otro lado, dentro de la carpeta [PUNTO_MONTAJE]/files/ van los archivos de metadata de oxigeno, basura y comida, pero los archivos donde vamos a agregar o quitar los caracteres dónde irían? elegimos un directorio aparte que sea  [PUNTO_MONTAJE]/files/info por ejemplo? La misma duda aplica para tripulantes.

Saludos!
Alexis

**Comment by ncoen97** [comment]
Buenas.
1. En la metadata de comida.ims, el campo "qué bloques ocupa" sería {0}
2. Si, la bitacora se guarda caracter a caracter, es como un log, y ocuparía esos 7 bloques que mencionas.
3. El contenido de los archivos se guarda en los bloques, que están en blocks.ims todos contiguos.

Saludos!

**Comment by alexisdona** [comment]
Graicas por los comentarios! Cierro el issue
