### ISSUE TITLE
[i-MongoStore] Consulta sobre Sabjotaje del Bitmap - Protocolo fsck

### ISSUE THREAD

**Issue by SantiagoAspres** [sisoputnfrba/foro#2170]
### 📔 Citas del enunciado

> Bitmap: Se debe garantizar que los bloques libres y ocupados marcados en el bitmap sean los que dicen ser. Reparación: corregir el bitmap con lo que se halle en la metadata de los archivos.

### 💭 Consulta de mi posible resolución

Para resolver esta parte nosotros lo que pensamos fue en ir abriendo todos los archivos, y viendo si leyendo los números de bloque del Blocks = [1,2,3] y usando el bitarray_test_bit, coindice con el bitmap del archivo superBloque, ósea que este efectivamente marcado como ocupado.

El gran problema que tenemos es armar el Path de los archivos que están en Bitácora, ya que el nombre de los archivos son formados por el id del tripulante.

Tratamos de usar una función para listar los nombres de los archivos pasándole el path del directorio pero el inconveniente es que el dir->name es de tipo char[ ] y no podemos convertirlo a char*.

```
t_list* listaArchivosDeBitacora(char* directorio) {

	DIR *d;
	t_list* listaArchivos = list_create();
	struct dirent *dir;
	d = opendir(directorio);
	if (d) {
		while ((dir = readdir(d)) != NULL) {
			if( strcmp( dir->d_name, "." ) != 0 &&
					strcmp( dir->d_name, ".." ) != 0 ){

				list_add(listaArchivos,dir->d_name);

			}
		}
		closedir(d);
	}
	return listaArchivos;

}
```

Cuando lo corrimos funciono bien, el problema es que al usar Valgrind nos marca que tenemos lecturas invalidas.

Hace falta resolver este sabotaje viendo también los archivos de tripulantes, o solo tengo que ver los archivos de recursos (Oxigeno, Comida, Basura) ? En el caso que tenga que accederlos, como resuelvo este tema de armar el path de los archivos tripulantes sin entrar en problemas de lecturas invalidas con Valgrind?

Muchas gracias!

**Comment by ncoen97** [comment]
Buenas, no va a haber sabotajes en los archivos de bitácoras. Saludos!

**Comment by SantiagoAspres** [comment]
Buenisimo, muchas gracias!

**Comment by SantiagoAspres** [comment]
Vengo a aportar la solución definitiva a este problema gracias a la ayuda de @mesaglio 

Ahora con esta función obtenemos una lista de char* que son los nombres de los archivos que hay en el directorio Bitacoras, y con esta lista ya se pueden armar fácilmente los paths de los archivos.
```
t_list* listaArchivosDeBitacora() {

	DIR *d;
	t_list* listaArchivos = list_create();
	struct dirent *dir;
	d = opendir("/home/utnso/polus/Files/Bitacoras");
	if (d) {
		while ((dir = readdir(d)) != NULL) {
			if( strcmp( dir->d_name, "." ) != 0 &&
					strcmp( dir->d_name, ".." ) != 0 ){

				char* cadena = arrayToChar(dir->d_name);
				list_add(listaArchivos,cadena);

			}
		}
		closedir(d);
	}

	return listaArchivos;

}
```

```
char* arrayToChar(char cadena[]){

	char* a = string_new();
	for(int i=0; cadena[i]!='\0';i++){
		char caracter = cadena[i];
		char* aux = malloc(1);
		memcpy(aux,&caracter,1);
		string_append(&a,aux);
		free(aux);
	}

return a;

}
```
Saludos!

**Comment by RaniAgus** [comment]
¡Gracias por el aporte, @SantiagoAspres ! Un dato a tener en cuenta: podés encontrar en las commons la función `arrayToChar` como [`string_duplicate()`](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/string.h#L91:L96) 😉
