### ISSUE TITLE
[IMongoStore] Duda con mapeo a memoria y copia de blocks

### ISSUE THREAD

**Issue by alexisdona** [sisoputnfrba/foro#2171]
Buenas!

Tenemos otras dudas con el enunciado 

1. cuando dice que hay que mapear a memoria el contenido del archivo de bloques y hacerle una copia con memcpy, lo que no entendemos es para qué realizar esta copia adicional y no trabajar directamente con el contenido del  archivo que previamente se copió a memoria usando mmap(). 

2. Entendemos que hay que mapear los bloques, pero el superbloque (sobre todo por el bitmap)  y los demás archivos que contienen la metadata de oxígeno, basura, comida y bitácora es necesario llevarlos a memoria para trabajarlos?

3. Qué tamaño de bloque y cantidad es prudente setear al iniciar el FS y qué ocurre (o debe ocurrir) si tenemos todos los bloques ocupados con datos y nos sigue llegando información para agregar ya sea de oxigeno, comida, basura o de movimientos de los tripulantes a informar en sus respectivas bitácoras?

**Comment by ncoen97** [comment]
Buenas.
1. Es un requerimiento del enunciado, van a tener que sincronizar cada x tiempo determinado por el TIEMPO_SINCRONIZACION de la configuración.

> ... sobre la cual se trabajará para lograr simular la concurrencia y asincronismo en las bajadas a disco de los sistemas operativos reales.

2. El único caso en el que es obligatorio es en el archivo de blocks.ims, así que los otros pueden manejarlos como les parezca mejor. Igualmente les recomiendo que usen `mmap()` para el superbloque para que sea mas fácil interactuar con el bitmap.
3. Esos parametros se los vamos a dar para cada prueba que tengan que correr, así que deberían tener alguna forma de setearlo (ya sea mediante la config, como parametros cuando se inicia el proceso, o como gusten). En el caso de que tengan que guardar algo en el FS y no haya más lugar, pueden informar mediante consola y devolver algún código de error como respuesta.

Saludos!

**Comment by matiasfdevecchi** [comment]
Buenas @alexisdona, en el issue #2164 consulté algo parecido a lo tuyo respecto al punto 1, quizás te sirve como complemento a lo que mencionaron arriba

**Comment by alexisdona** [comment]
Gracias por los aportes! cierro el issue
