### ISSUE TITLE
Tipos de sabotaje y files bitacora

### ISSUE THREAD

**Issue by matiasfdevecchi** [sisoputnfrba/foro#2172]
Buenas, dejo dos consultas:
1. El sabotaje dice que será sobre SuperBloque.ims y Files. Por lo tanto Blocks no será saboteado, y con. respecto a Files, también incluye la bitacora?

2. Con respecto a la bitacora, me llama la atención dos cosas:
   1. No tiene MD5, por lo tanto supongo que no se sabotea
   2. Tiene SIZE y BLOCKS, por lo tanto no tienen una metada "similar" a los files de recursos. Falta BLOCKS_COUNT o es solo para los files de recursos?

**Comment by ncoen97** [comment]
Buenas.
1. No incluye a bitácoras.
2. En realidad la BLOCK_COUNT está medio implícita en el tamanio de la lista de BLOCKS, igualmente para este tp el BLOCK_COUNT es solo para los files de recursos.

Saludos!
