### ISSUE TITLE
Formato de tareas en script

### ISSUE THREAD

**Issue by brunotello** [sisoputnfrba/foro#2173]
Hola!

Haciendo la serializacion de las tareas, vi que las que son de  IO y las que son de CPU, tienen un formato distinto, ej:

IO: **GENERAR_OXIGENO 1;1;1;1**

CPU: **AFILAR_LANZAS;1;1;1**

La diferencia está en el espacio que tiene la de IO entre el nombre y los parametros... si fuera **GENERAR_OXIGENO;1;1;1;1** (con un ; separando el nombre de los parametros como las de CPU)
A la hora de hacer un split  del string que se recibe, solo habria que checkear el string_split[0] y se puede generar la misma logica tanto para tareas de IO como de CPU, la diferencia es el parametro extra

Saludos!

**Comment by ncoen97** [comment]
Buenas, en realidad para simplificarlo, el formato está pensado para hacer 2 split. Uno por `;`, que generaría siempre 4 elementos, y otro por ` ` (espacio en blanco), que generaría 1 elemento + la cantidad de parámetros que tenga la tarea.
Saludos!

**Comment by iago64** [comment]
@brunotello Te quedo alguna duda? Hay algo mas que podamos aclarar?

**Comment by brunotello** [comment]
@ncoen97 Mmm pero no crees que es complicarla de esa forma ? Si se mantiene el formato de ; para ambos tipos de tareas, y el formato seria

nombre_tarea;duracion;pos_x;pos_y;cantidad (opcional si es de IO) 

lo unico que tenes que hacer es hacer 1 split por **;** y fijarte si tu array resultante es de 4 o 5 parámetros, si es de 5 es de IO y listo

**Comment by ncoen97** [comment]
Me parece que complicarla sería hacer que los 30/40/50 grupos que ya tienen eso codeado se tengan que poner a modificarlo. A esta altura es un cambio que no vale la pena realizar. Saludos!

**Comment by RaniAgus** [comment]
¡Buenas! Quizás este dato te pueda servir: `string_split` usa una función llamada [`strsep()`](https://man7.org/linux/man-pages/man3/strsep.3.html), la cual en segundo parámetro recibe todos los delimitadores que vos quieras. O sea, podés poner ambos y te los va a dividir así:
```c
string_split("GENERAR_OXIGENO 1;2;3;4", "; "); // => [ "GENERAR_OXIGENO", "1", 2", "3", "4"]
```
Por si alguien en un futuro se encuentra este issue, este comportamiento lo vamos a cambiar para el cuatri que viene (ver https://github.com/sisoputnfrba/so-commons-library/issues/141), pero para este cuatri vamos a mantener la función como está :)

Saludos

**Comment by RaniAgus** [comment]
¡Buenas @brunotello! ¿Quedó alguna duda?

**Comment by RaniAgus** [comment]
Cerramos por inactividad, si quedó alguna duda no duden en reabrirlo 😉
