### ISSUE TITLE
Duda con memoria e INICIAR_PATOTA

### ISSUE THREAD

**Issue by SantiagoOrlando29** [sisoputnfrba/foro#2174]
Buenas tardes

Tengo una duda con el tema memoria e INICIAR_PATOTA. 
Si yo hago por ejemplo INICIAR_PATOTA 5 ... pero cuando Miram va a asignar la memoria para el PCB, tareas y TCBs, tiene espacio para el PCB, para las tareas, y para solamente 2 TCBs. Suponiendo que ya se hizo la compactación o ya se llenó la memoria virtual, que tiene que pasar? Tiene que denegarse la solicitud de todo el INICIAR_PATOTA? O tiene que cargar solo 2 TCBs y avisarle a discoridador que solo cargó 2 en memoria?

Saludos!

**Comment by ncoen97** [comment]
duplicado de #2095

**Comment by SantiagoOrlando29** [comment]
Graciasss!
