### ISSUE TITLE
Dudas varias con md5

### ISSUE THREAD

**Issue by heinHertz** [sisoputnfrba/foro#2175]
Hola, necesito ayuda con md5 ,  no estaría entendiendo bien varias cosas:

1) primero como se genera, lei este issue https://github.com/sisoputnfrba/foro/issues/2129  y hablan de usar system para generarlo, segun entiendo hasta ahora necesito para almacenarlo dentro del files, en el md5.
si uso este codigo:
```
unsigned int md5;        
char * system_command = string_new();
string_append_with_format(&system_command, "md5sum %s ", path_file);   
md5 = system(system_command); 
```
el md5 siempre es 0, no me devuelve el hash del archivo, se que funciona porque en la salida se muestra el print del hash junto con path del file, pero no pasa a md5 sino que se muestra. la idea mia es agarrar el md5 y guardarlo en el md5 del file.

2) SI esta no es la forma debería haber otra forma? lei otros issue pero tienen partes que no logro tener una idea clara de que función usar.

3)  el tema de la comparacion estoy entendiendo esto:  
a)  la idea es crear el archivo ponerle los datos( los blocks, el size y los otros datos, menos un md5 porque no lo calcule todavia) , guardarlo y calcularle el md5 al archivo y abrirlo del archivo y guardar otra vez pero solamente el md5 faltante.  esto algo asi lo que hay que hacer?
b) el md5 en realidad me sirve para confirmar que el File.ims( basura oxigeno o comida) ha sido saboteado, pero no me dice exactamente qué ( el size o los blocks o count blocks) ? es correcto esto?

gracias.

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Ojo con system(), porque si bien es re practico, tiene el detalle de que no devuelve el resultado 😉 por eso es bueno siempre pegarle una leida al [manual](https://man7.org/linux/man-pages/man3/system.3.html).

Si te sirve de idea, vos podes siempre en bash direccionar la salida de un programa o comando a un archivo por ejemplo, entonces vos podrias hacer:

md5sum hola.txt > chau.txt y en chau.txt te queda el resultado del md5sum, capaz que por ahi viene la solución 😉 

Saludos.-

**Comment by heinHertz** [comment]
ah gracias!!  la parte de como obtener el md5 ya creo tenerla solucionada, justo son las respuestas 1 y 2.
son tan amables de revisar una posible respuesta a las dudas que tengo en la pregunta 3?
```
3). el tema de la comparación estoy entendiendo esto:
a) la idea es crear el archivo ponerle los datos( los blocks, el size y los otros datos, menos un md5 porque no lo calcule todavia) , guardarlo y calcularle el md5 al archivo y abrirlo del archivo y guardar otra vez pero solamente el md5 faltante. esto algo asi lo que hay que hacer?
b) el md5 en realidad me sirve para confirmar que el File.ims( basura oxigeno o comida) ha sido saboteado, pero no me dice exactamente qué ( el size o los blocks o count blocks) ? es correcto esto?
```
y mil gracias!

**Comment by gastoncastineira** [comment]
Buenas

1. No terminé de entender si esto es en runtime o al crear el archivo por primera vez. No sé su apuntás a esto; el MD5 es sobre el contenido del archivo y por lo tanto se va a estar actualizando cada vez que el contenido del archivo se modifique
2. Es correcto

**Comment by heinHertz** [comment]
gracias!
