### ISSUE TITLE
Sobre el sabotaje

### ISSUE THREAD

**Issue by ospocarpa** [sisoputnfrba/foro#2176]
Buenas mi consulta es sobre la respuesta a la pregunta 2 del issue #2163 
cito la pregunta  a continuacion :
>Cuando recibo del FS el mensaje de sabotaje
 > Busco el tripulante mas cercano y lo pongo a que se mueva hasta la posicion del sabotaje. (si el tcb estaba en EXEC, dejaria la tarea pausada hasta que se solucione el sabotaje).

La respuesta que dieron es 

>Si la tarea es de ejecución de CPU van a tener que iniciarla denuevo.

La pregunta es si la respuesta  aplica solo al tripulante que resuelve el sabotaje o a todos los tripulantes que estaban cosumiento tiempo de CPU en exec y  pasan a la cola de bloqueados de emergencia . 

Entiendo que van a ser planificados denuevo pero en caso de respuesta negativa,voy a tener que guardar cuanto tiempo de CPU ya consumio ese/esos tripulantes en dicha tarea

Gracias!!

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Perdón por la demora en contestar. El reiniciar solo aplica al tripulante que resuelve el sabotaje porque se tiene que mover, los demás simplemente se van a bloquear y al momento de desbloquearse reanudan la tarea ya que están en la posición.

Saludos.-

**Comment by ospocarpa** [comment]
Mejor tarde que nunca 
Graciass por la respuesta ,
Cierro el issue!!
