### ISSUE TITLE
Asignación de pagina al ser expulsado un tripulante

### ISSUE THREAD

**Issue by Franpanozzo** [sisoputnfrba/foro#2177]
Buenas, el enunciado dice: 
> En nuestra implementación se deberá mantener la información (PCB, Instrucciones y TCBs) en forma contigua a lo largo de las páginas asignadas. 

Ahora, si se libera una pagina de un proceso1. ya que se expulso un tripulante, y viene otro proceso2 nuevo, podria utilizar esa pagina que esta liberada en el medio del proceso1 ??? Si es asi la informacion en memoria fisica no quedaria contigua.

Y ademas, si es que la puede aprovechar, la puede aprovechar una vez que se libera toda, o cuando esta parcialmente libre (Que se expulse un tripulante, pero tambien en esa pagina habia parte de las tareas) tambien??

**Comment by ncoen97** [comment]
Buenas, si buscan el termino fragmentacion en el foro les salen mínimo 3 issues donde ya contestamos esa pregunta, así que les pido que se acuerden siempre de buscar antes de abrir un nuevo issue.
Saludos!

**Comment by Franpanozzo** [comment]
Buenas nico, buscamos pero supongo q los salteamos, gracias
