### ISSUE TITLE
[i-MongoStore] Dudas varia sobre sabotajes

### ISSUE THREAD

**Issue by Nicolas-Russo** [sisoputnfrba/foro#2178]
Buenas, despues de leer varios issues me quedan algunas dudas sobre como se va a llevar a cabo el sabotaje para poder resolverlo:

1- De donde recive la signal SIGUSR1 el iMongoStore?
2- Quien es el que modifica algo del FS que se va a tener que reparar?
3- Lo que tiene que hacer el protocolo fsck es chequear todo, ya sea un sabotaje en el superbloque Files o bloques? o si encuentra que se realizo un sabotaje en el superbloque no chequea si hubo un sabotaje en Files o bloques?

Gracias.

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Lo tienen que atrapar con *signal()* te dejo una ppt de la presentación que dabamos originalmente

2.- Lo hacen uds en base a lo que les digamos en el documento de pruebas.

3.- Idealmente debería checkear todo, lo importante es que los sabotajes no van a tener mas de 1 a la vez.

Saludos.-

**Comment by Nicolas-Russo** [comment]
Gracias
