### ISSUE TITLE
Sabotajes 

### ISSUE THREAD

**Issue by SantiagoIvan** [sisoputnfrba/foro#2179]
Hola! Puede haber varios sabotajes a la vez? Supongamos que mientras se está solucionando un sabotaje, ocurre otro. Qué pasa en ese caso? Se van encolando para ser solucionados de a 1?

**Comment by Nicolas-Russo** [comment]
Hola santi, fijate que en el primer parrafo donde empieza a hablar sobre sabotajes dice:
`Cabe aclarar que los sabotajes se van a hacer de a un tipo a la vez.`

Saludos.

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

No somos tan mala leche, solo vamos a tirarles de a 1 sabotaje a la vez :)

Saludos.-

**Comment by SantiagoIvan** [comment]
jajaajaja gracias ! cierro issue
