### ISSUE TITLE
[Mi-RAM-HQ] Paginacion: dudas con tareas, y con expulsar tripulante

### ISSUE THREAD

**Issue by MartinGongora** [sisoputnfrba/foro#2180]
Buenas, dos consultas:

1 - En el checkpoint hablamos del msj de próxima tarea, en la cual nos dijeron que se deberían traer todas las tareas a memoria real (no solo la que busca el tripulante), y que por ende se deben traer todas las paginas correspondientes a las tareas. 
La duda es, estas paginas se deben traer todas juntas a memoria real? o se pueden traer de a una mientras se va recorriendo la sección de tareas? 

2 - Respecto a expulsar tripulante, cuando se expulsa el tripulante, la pagina donde se encuentra el tripulante a expulsar se debería a traer a memoria real? o se lo puede expulsar directamente en memoria virtual? Asumo que no habría problema con esto ultimo ya que no se hace nada sobre los datos del tripulante en si, sino que seria simplemente una modificación en las estructuras administrativas.

**Comment by iago64** [comment]
Buenas! Como va?

1.- Solo para sentar una base por si alguien cae desde la estratosfera al issue, hablamos de paginación :) Ahora idealmente deberían traer solamente la / las paginas asociadas a la tarea que estan buscando, pero por las dudas nos sirve el warning para tenerlo en cuenta para las pruebas, asi que nos llevamos el laburo interno para ver como lo aclaramos bien a la hora de las pruebas :)

2.- Buena pregunta, es un caso bastante gris, vamos a consensuarla internamente ya que como decis, si limpian estructuras administrativas alcanza.

Por las dudas no cierres el issue ya que nos sirve de flag para saber que tenemos que sentarnos un buen rato a ver esto :)

Saludos.-

**Comment by MartinGongora** [comment]
Buenas, hubo alguna definicion respecto al punto 2 al expulsar un tripulante?

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Justo es algo que se estuvo charlando hoy y no encontramos motivos para que sea un problema que lo eliminen directamente de la memoria virtual, así que pueden hacerlo.

Saludos.-

**Comment by iago64** [comment]
@MartinGongora cómo va? te quedo alguna duda?

**Comment by MartinGongora** [comment]
Buenas, no, ya quedo todo claro, cierro?

**Comment by iago64** [comment]
Tranqui, lo cerramos 😄
