### ISSUE TITLE
[Mi-RAM-HQ] Paginacion: cantidad de frames necesarios para iniciar patota

### ISSUE THREAD

**Issue by MartinGongora** [sisoputnfrba/foro#2181]
Leyendo el issue #2162 , respecto al tema de que no hay paginas iguales en mv y mr, en el caso de inicializar una patota, para ver si entra la patota, tendríamos que chequear con la sumatoria de frames de swap y real, pero deberíamos ver q nos quede un frame libre en virtual para poder swapear? o ese frame libre no tendría que ser necesario y se debería usar un buffer temporal a la hora de hacer el swap? El segundo caso nos complica bastante nuestro diseño actual.

**Comment by alejcha** [comment]
Buenas tardes, me sumo a la consulta, con respecto a la respuesta del issue mencionado:

> Buenas, las páginas se cargan directamente en memoria principal, solo se cargan en swap cuando no hay más espacio en memoria principal. Esto quiere decir que cada página va a estar una sola vez en toda la memoria (no tiene una copia en MP y otra en MV). Dejo un fragmento la pagina 18 del enunciado: Y el proceso de swap comenzará una vez que se encuentre llena la memoria principal



en la teoria nos dijeron justamente lo contrario, que en Virtual existe una copia de la RAM, y hace swap cuando no hay ram libre o se produce pagination fault, en este caso el tamaño maximo posible ocupado seria de la memoria virtual.
entonces para el tp no se considera asi?
el tamaño "total" de la memoria para las patotas y tripulantes sería ram + virtual?

**Comment by ncoen97** [comment]
Exacto, en teoría se ve una de las posibles implementaciones de memoria virtual, pero hay varias.

**Comment by MartinGongora** [comment]
Entendido, cierro.
