### ISSUE TITLE
[i-MongoStore] Consulta sobre Sabjotaje del Bitmap

### ISSUE THREAD

**Issue by Nicolas-Russo** [sisoputnfrba/foro#2182]
Buenas, me queda una duda relacionado a lo que se pregunto en el issue #2170. En una parte del enunciado dice:

>Bitmap: Se debe garantizar que los bloques libres y ocupados marcados en el bitmap
sean los que dicen ser. Reparación: corregir el bitmap con lo que se halle en la
metadata de los archivos.

Por lo que entiendo se va a cambiar algunos bits del bitmap y nosotros lo que tendriamos que hacer es chequear en la metadata y en las bitacoras si esos bloques que ocupan estan seteados en el bitmap. No es asi? o solo se van a sabotear los bits que no pertenescan a una bitacora?

Saludos.

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Efectivamente tienen que checkear todos los archivos (recursos y bitácoras) para ver que bloques están usando.

Saludos.-

**Comment by SantiagoAspres** [comment]
Me sumo a la consulta por la respuesta que recibi en el issue #2170, entiendo que no debería chequear los archivos de Bitácoras. Los **nombres** de los archivos de Bitácoras están dados como tripulante + idTripulante, por lo que no encontré forma de listar los nombres de los archivos del directorio Bitacoras como char* para formar el path y poder hacerle fopen a eso (Con valgrind falla siempre).
Por lo que los únicos archivos que si puedo abrir y comparar con el bitmap son los de recursos (Oxigeno, Basura, Comida).

Saludos.

**Comment by iago64** [comment]
Buenas! Cómo va?

No te olvides que en C todo es memoria, con lo que si vos por ejemplo agarras si decis: che tengo un char [] eso no es muy muy diferente a un char *, vos podes por ejemplo pedirle la dirección al char [] con el & y de ahi hacerte una copia y trabajarlo como char * en lugar de char [] 😉 

En el issue #2170 creo que lo que quiso decir Nico y es que no vamos a romperles la metadata de las bitácoras durante los sabotajes, esos archivos van a quedar siempre seguros, con lo cual podrías armarte alguna estructura extra en memoria que tenga los bloques asignados a las bitácoras.
Lo único que me queda la duda es: Como están haciendo para levantar un FS existente?

Saludos.-

**Comment by SantiagoAspres** [comment]
Dami, ya pude hacerlo funcionar con test en valgrind y todo paso bien. Para levantar el FS existente leo del archivo superbloque el block_size y blocks, y lo cargo en memoria, lo mismo con el blocksMap y SuperBloqueMap y el bitmap. NO LEO el size ni la cantidad de bloques desde el config!

**Comment by iago64** [comment]
Buenas! 
@SantiagoAspres buenísimo!
@Nicolas-Russo tenes alguna duda mas?

Saludos.-
