### ISSUE TITLE
[Mi-Ram-HQ] Swapping ↔️ 

### ISSUE THREAD

**Issue by Cande175** [sisoputnfrba/foro#2183]
Buenas! Venimos con algunas dudas, más que nada para orientarnos con lo que quieren que hagamos, así después matchean las pruebas bien bonito 😋 

-----------------------

**Duda 1: Mensaje Proxima Tarea en Memoria con Paginación**
Ante el mensaje enviado por el discordiador, planeabamos traer todas las páginas del proceso que contengan alguna parte del string tareas, ya que de esa forma vamos a poder leer el string completo y devolver la próxima tarea a ejecutar al discordiador (otro string). ¿Es correcto?

**Duda 1.5: Al actualizar info de Patota/Tripulante**
Planeabamos traer todas las páginas que contienen datos de la estructura (simil Duda 1). Por ejemplo, si queremos actualizar la posición del tripulante, vamos a traer todas las paginas que tengan alguna parte del tripulante. ¿O prefieren traer todas las páginas que contengan alguna parte de su dirección?

**Duda 2: Bit de uso**
El bit de uso va a ponerse en 1 siempre que traigamos algo de M. Swap a M. Principal, ya que lo traemos para usarlo.
¿Qué quieren que hagamos en el caso de tener espacio libre en M. Principal y haya que iniciar una patota? ¿Bit de uso en 1 o 0?  (La patota se guardaría en M. Principal pero nosotros no lo necesitamos, entonces técnicamente no estaría siendo usada... ¿o si?)

**Duda 3: Escenarios de Swapping**
¿Qué escenarios se incluyen en las pruebas que impliquen hacer swapping?
Hago lista de lo que me imagino que entra:
* Cambiar posición Tripulante
* Cambiar estado de Tripulante
* Obtener tarea
* Listar tripulantes

Supongo que borrar tripulante y borrar patota no van ¿No?

-----------------------

¡Muchas gracias!

**Comment by Cande175** [comment]
Estuve codeando y me di cuenta que las siguientes dudas no hay otra forma de hacerlo desde la práctica. No edito el issue por si a alguien le sirve y por si me dicen que estoy equivocada.

**Duda 1:** Mensaje Proxima Tarea en Memoria con Paginación
Traemos todas las páginas del proceso que contengan alguna parte del string tareas, ya que de esa forma vamos a poder leer el string completo y devolver la próxima tarea a ejecutar al discordiador (otro string).

**Duda 1.5:** Al actualizar info de Patota/Tripulante
Traemos sólo las páginas que contienen datos a actualizar, no todo el tcb/pcb porque es innecesario.

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Perdon la demora, se me re paso el mail :(

Respecto a tus consultas:

1.- A priori tienen que tener una indicación de la próxima tarea a ejecutar, con lo cual en principio no deberían traer todas las páginas si no las referentes a la tarea.

1.5.- Deberían traer el TCB o PCB completos (si ocupan mas de 1 página deberían traer todas las páginas), en el caso de tareas como en el punto 1, deberían traer solo lo asociado a la tarea.

2.- De entrada uds tienen que guardar todo en Swap y después traer a memoria principal bajo demanda.

3.- Los escenarios que listas están bien, en el caso de borrar un tripulante puede ser si justo el TCB comparte con otro TCB.

Saludos.-

**Comment by Cande175** [comment]
Bueno, parece que vamos a tener que cambiar muchas cosas con el tema de las tareas jeje 

1.5 ¿Cuál es la razón de traer todas las páginas del TCB si por ejemplo sólo necesito la pos x e y? Osea ¿por qué traería solo lo necesario para buscar la tarea pero todo en otra situación?

2 Al principio lo habíamos hecho así, pero luego de una duda del foro (y debido a eso tmb una consulta en el labo) cambiamos la implementación ( https://github.com/sisoputnfrba/foro/issues/2162 ). Como guardamos primero en memoria principal las patotas hasta que se llena, estaba la duda de si se quiere el bit de uso en 1 o 0 en ese primer caso.

3 ¿Cuál sería la razón teórica/practica de esto? Cuando eliminamos patotas (o un TCB que deja el frame sin nada más guardado allí), enrealidad no estamos tocando nada de lo guardado en sí, simplemente actualizamos nuestra info de las tablas avisando que X frames están libres, y la info "basura" queda ahí hasta que alguien más la pise. En el caso de borrar un TCB que comparte memoria con otro TCB estamos dejando fragmentación interna y sólo avisamos que el frame está libre una vez que lo ocupado del frame sea 0 bytes.

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

1.- La razón es simplemente que tenemos que ser justos con todos los grupos al momento de definir las pruebas (que tienen que ser determinísticas) y dado que no todos tienen armadas las estructuras para traerse solo algunos campos del TCB tienen que traerse el PCB completo. 
Por el otro lado el identificador de la próxima tarea a ejecutar si es un indicador claro de la siguiente tarea por lo cual no tiene sentido que traigan a memoria todas las tareas.

2.- Ok, en ese caso, si esta validado en el issue #2162, esta bien, puede quedar de esa manera. Ahora respecto al bit de uso, el mismo se debe setear cada vez que se accede a una página y esto incluye lecturas y escrituras y la primer escritura cuenta como tal.

3.- Es un caso borde y pasa un poco como en el punto 1, no todos los grupos pueden acceder directamente a los TCB, ya que a diferencia de segmentación donde cada TCB es un segmento, acá pueden compartir páginas y deben recorrerlas para encontrarlos y ver si el TCB existe.

Saludos.-

**Comment by Cande175** [comment]
Perfecto Damián! Muchas gracias por la paciencia 😃

**Comment by Cande175** [comment]
Sorry, no se si está permitido volver a abrir los issues. Hoy quise ir a modificar todo lo que nos indicaste pero me agarró una duda con lo de la tarea de nuevo y prefiero no seguir haciendo por hacer de nuevo que me lleva por mal camino así que consulto de nuevo sobre respuesta de la duda 1. 

En el struct del tcb del enunciado dice "Próxima tarea | Identificador de la próxima tarea a ejecutar | uint32_t" nosotros lo teníamos como la cantidad de tareas que había ejecutado el tcb. Entonces íbamos a buscar todas las tareas, dividiamos el string con el caracter de separación (\n) y luego tomábamos la tarea que indicaba nuestro "próxima tarea" (con ese approach no hay forma de buscar la tarea en un lugar en especifico ya que es necesario reconstruir el string entero para poder hacer el split luego, así que nos traíamos todas las páginas).

Entonces, imagino que en realidad lo que planteas Damian es que el  "Próxima tarea | Identificador de la próxima tarea a ejecutar | uint32_t" sea la dirección lógica de la tarea ¿no? (simil a Tareas | Dirección lógica del inicio de las Tareas | uint32_t
del pcb pero por cada tarea en vez de la inicial)
En ese caso cada vez que nos pidan una tarea le deberíamos sumar la cantidad de caracteres de nuestra tarea obtenida a la dirección de la tarea (1 char = 1 byte).
Pregunto porque no se me ocurren muchas más formas de saber dónde está la tarea buscada 🤔

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Si tranqui, los issues son de quien los crea, así que si necesitabas reabrirlo no hay drama 😄 

Respecto al identificador de la próxima tarea, es verdad, nos quedo un poco floja de papeles la redacción, pero la idea es que sea algo que a uds les indique como encontrar la siguiente tarea, esto abarca desde un número de tarea, pasando por el indice en una lista de tareas que puedan tener en sus estructuras administrativas hasta la dirección exacta con página y marco (haciendo alguna magia matemática en el medio para que entre todo en un uint32_t). Con lo cual, ese valor pueden usarlo a gusto, básicamente les tuvimos que restringir el tamaño porque al momento de hacer las cuentas de memoria libre y ocupada necesitábamos saber exacto cuanto va a ocupar el PCB, los TCB y la lista de tareas (por eso que esto último les dijimos que tienen que guardarlas como esta en el archivo que leen en discordiador)

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @Cande175 ! ¿Alguna duda con la respuesta de Dami?

**Comment by Cande175** [comment]
Venía a romper las bolas, pero me terminé inspirando en esta media hora y se me ocurrió algo. Agrego el comentario que iba a poner con mi problema que al final me termine respondiendo sola, así no queda el reopened/closed fantasma sin comentario de por medio, tal vez le sirve a alguien.

-----------------------------------------------------------------------------------------------------------

Espero no me hayan extrañado, estaba estudiando para el parcial :) y fue el motivo por el que no había cerrado el issue (no pude tocar el tp).

Ahora estoy de vuelta y la buena noticia es que ya implementé el 1.5 como me dijo Damian. La mala noticia es que no consigo idear nada lindo para hacer el 1. como pidió Damian.

La cosa es esta... Ustedes nos piden que traigamos SOLO la página de la tarea pedida (o LAS si justo esa tarea está en +1 página). El problema con esto, es que nosotros tendríamos que tener:
1- Donde empieza la tarea
2- Donde termina la tarea

El primero es fácil, podemos (como había dicho antes) usar un "indicador" que tenga en qué byte de la imagen del proceso comienza esa tarea. Con este approach cada vez que leemos una tarea nueva, le sumamos el tamaño de esa tarea (1char=1byte)
¿Pero el segundo? **-aca se suponia que no se me ocurría como hacerlo pero la siguiente es una posible solución-** Estaba pensando en hacer tamanio_total_tareas - indicador_tarea lo que me daría el tamaño restante a leer. Con ese tamaño a leer puedo leer todas las tareas guardadas en esa página y luego chequear si tengo algún /n (indicador de fin de tarea) en el string traído, si no lo tengo, leo de la siguiente página el "nuevo tamaño restante a leer de la tarea" y repito el proceso hasta encontrar el /n
