### ISSUE TITLE
[Duda rapida] Enunciado MiRamHQ

### ISSUE THREAD

**Issue by TomasR264** [sisoputnfrba/foro#2185]
Hola, queriamos consultar para estar seguros, ya hasta ahora trabajamos pero no lo teniamos en claro... La memoria debe administrar mediante el esquema de **Segmentacion con Compactacion** O  **Paginacion con Swap**, o ambos? Osea, debemos realizar los dos o elegir uno solo?

Muchas gracias 😄

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Tienen que implementar ambos esquemas.

Saludos.-
