### ISSUE TITLE
Obtener tarea en segmentación y paginación

### ISSUE THREAD

**Issue by matiasfdevecchi** [sisoputnfrba/foro#2186]
Buenas, tenemos una consulta respecto al TCB:
Próxima_tarea dice "Identificador de la próxima tarea a ejecutar". Con esto se refiere al index? Es decir, si tengo 3 tareas, iría de 0 a 2? O es una dirección lógica dentro de la memoria?

En caso de que sea el index, puede existir la posibilidad de usarlo como dirección logica manteniendo que sea uint32_t? Ya que con eso podemos apuntar directamente al número de pagina / segmento y su offset, evitando leer todas las tareas innecesariamente

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Puede ser la dirección lógica o puede ser el número de tarea, la idea de que sea un "indicador" hace referencia a que a uds les indique como encontrar la siguiente tarea, después es tema de coloquio que nos cuente como y por que tenia la forma que tenia :)

Saludos.-

**Comment by matiasfdevecchi** [comment]
Muchas gracias!
