### ISSUE TITLE
Dudas i-MongoStore

### ISSUE THREAD

**Issue by matiasfdevecchi** [sisoputnfrba/foro#2187]
Buenas, nos surgieron algunas dudas con este módulo:
1. Que pasa si levantamos un FS existente y tiene bitácoras? Deberíamos borrarlas ya que el tripulante 1 de una instancia del Discordiador sería disnto al de otra instancia? O las mantenemos y las seguimos completando a medida que trabajan, como si el Tripulante 3 de una instancia de Discordiador fuese el mismo que el de otra instancia?

2. Como asignamos los bloques en el FS? Estamos utilizando "el primero en encontrarse libre" ya que no vimos ninguna aclaración al respecto en el enunciado, pero por las dudas preguntamos

3. Qué pasa si no hay más bloques libres y tenemos que escribir en la bitácora?

4. Idem anterior, que pasa si no hay más bloques libres y tenemos que escribir más recursos?

En el caso 3 y 4, el tripulante estamos haciendo que no espere respuesta de ESCRIBIR_BITACORA y REALIZAR_TAREA, por lo tanto no tenemos control de eso en el discordiador, pero podemos loguearlo e imprimirlo en consola en el i-MongoStore. También podríamos esperar respuesta del lado del tripulante si así es el requerimiento

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

1.- Da igual, si quieren borrarlas do it, si quieren mantenerlas háganlo, básicamente no nos cambia los resultados.

2.- Esta bien, no hay definición en el enunciado, definen uds 😉 

3.- No va a pasar, no tenemos pensado hacer alguna prueba de llenarles el FS.

4.- Idem 3, no vamos a probarles de llenarles el FS.

Saludos.-

**Comment by matiasfdevecchi** [comment]
Ok, gracias!
