### ISSUE TITLE
Sobre el sabotaje en Files

### ISSUE THREAD

**Issue by frandom00** [sisoputnfrba/foro#2188]
Acabo de ver el video del FS y me surgio una duda con respecto al sabotaje en el SIZE y de BLOCKS. 
Lo que habia pensado para el sabotaje en el valor del SIZE era recorrer todos los bloques que me aparezcan en blocks y contar, por ejemplo, la cantidad de "O" que tiene escrita cada uno para reestablecer el size.
Yo con esta logica para reestablecer el size ya me estaria dando cuenta si uno de los bloques fue cambiado de posicion, ya que al leerlo no estaria 100% lleno, con lo cual no necesitaria sacar un nuevo md5 y comparar el valor y podria solucionar el sabotaje en blocks devolviendo el orden a los bloques
Mi pregunta es si puedo hacer esto o si o si tengo que calcular un nuevo md5, compararlo con el que tengo y reescribir todos los bloques

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

El planteo esta bien, ahora la pregunta que se me ocurre es: ¿Cómo sabes que sabotaje ocurrió si simplemente les cambio el orden de los archivos? 
Porque a priori si te guias solo por el size todos los sabotajes van a ser de size y nunca del orden de los bloques, mientras que si de ultima contracheckeas el MD5 con el archivo generado con todas las O en orden vas a darte cuenta que en realidad cambio el orden de los bloques y no el size.

Saludos.-

**Comment by frandom00** [comment]
Me daría cuenta porque el único bloque que no estaría 100% lleno de "O" es el último, entonces si me meten el último bloque a la mitad de la lista, cuando lo este leyendo para contar el SIZE voy a ver qué a mitad de camino tiene algo que no es una "O" y lo volvería a meter al final de la lista

**Comment by gastoncastineira** [comment]
Buenas

El problema de hacerlo así es que estás asumiendo que el último bloque nunca va a estar lleno también. Si tenés bloques de 64 bytes, no existe la posibilidad de que tu archivo sea de 256?

**Comment by frandom00** [comment]
Okay, entonces hay un problema en como calculo el md5, porque yo para calcularlo le paso lo que hay adentro de los bloques a la función que lo calcula, osea en el ejemplo que diste serían 256 letras "O" y para ese cálculo me da igual el orden de las letras "O" porque son todas la misma letra.
Cómo se debería  calcular el md5?

**Comment by gastoncastineira** [comment]
Ja, tenía tan en la cabeza el orden de los bloques para archivos genéricos que me olvidé por completo que los archivos del TP tienen un solo caracter muchas veces XD. Si te fuera a rotar bloques llenos supongo que no te va a cambiar ni cambiar la integridad de los archivos, no. Buen ojo
La idea que comentaste la veo bien, nomás ojo con como manejás el borrado/consumir recursos para "deshacerte" de esas (por ejemplo) 'O's

**Comment by frandom00** [comment]
genial!, si cuando borro una letra la estoy cambiando por una W por las dudas que dsps no lea algo que no es. Muchas gracias!
