### ISSUE TITLE
Dudas i-MongoStore

### ISSUE THREAD

**Issue by matiasfdevecchi** [sisoputnfrba/foro#2189]
Buenas, dejo algunas dudas que surgieron a partir del video:

1. Puede haber cant de bloques que no sea multiplo de 8?
En el issue #2164 me dijeron que nunca habría bits innecesarios pero en el video si

2. MD5 es para el contenido del archivo que se encuentra en Blocks.ims?
Nosotros calculamos el MD5 de Oxigeno.ims, pero al parecer según el video, lo que tenemos que hacer es obtener el contenido del archivo, que está dentro de Blocks.ims y calcular el MD5 a eso?

3. Que pasa cuando borras un recurso y tenés que chequear el size?
Para chequear el size de un archivo de recurso, hay que recorrer los bloques en orden que están según blocks, y ver las veces que se repite el caracter.
En nuestro caso, al consumir recursos o descartar basura, no borramos el contenido dentro de blocks.ims sino que solamente modificamos el size (y también block_count y blocks si es necesario porque quedó algun bloque libre), análogo a los FS reales.
El problema es que si yo tenia 10 óxigenos, y consumo 4, el size es 6 pero en blocks.ims sigo teniendo 10 'O' continuas, por lo tanto cuando chequeo el size, va a dar que es incorrecto. Las tendríamos que borrar, no?

4. El orden de como se chequea el archivo de recurso importa, no?
Digo esto porque si primero chequeamos SIZE, y lo que está saboteado es BLOCKS, puede darnos cualquier información en SIZE, por ende es importante primero choquear que esté bien BLOCKS y si eso está bien, chequear SIZE

5. Hay que poner limite en la cantidad de caracteres o es solo para pruebas nuestras internas? Video min 15:24
En el video se menciona algo de un limite a la cantidad de caracteres a escribir en un archivo de recurso. Eso es solo para nosotros para cuando probemos nuestro sistema, o hay que definir un limite también en la entrega del TP?

6. En el video dan ejemplo de sabotaje block_count+blocks, cuando block_count es menor al tamaño de blocks, pero que pasa si el tamaño de blocks es mayor? Siempre asumimos que el correcto es blocks y el que se modifica es block_count?

7. En el issue #2131 se menciona que puede sabotearse el Blocks.ims, sin embargo eso no está en los lineamientos del enunciado. Según el enunciado solo se sabotea SuperBloque.ims y los archivos de recursos. Nos basamos en lo que dice el enunciado?

Aclaración: en el issue #2131 hay formas de sabotaje al metadata blocks que no fueron explicados en el enunciado (en el video si)

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

1.- Seguramente fue un error interno de comunicación, pueden tener una cantidad de bloques que no sean potencia de 2 y por eso es que les damos también el valor de block_count, para que sepan uds hasta que valor del bitmap tienen que considerar como válido.

2.- Efectivamente, el MD5 es del contenido que tienen en los bloques que se encuentran dentro del block.ims.

3.- Buen punto, la pregunta que tengo para hacerte es: que pasa si por ejemplo tienen que liberar un bloque? Si tienen bloques de 32 bytes y tienen por size 33 oxígenos y en la prueba dice que consuman 5, liberan el último bloque?.
Medio que en este caso no es necesario que borren todo, pero sería bueno que se dejen alguna marca (por ejemplo un caracter diferente).

4.- Para nada, el orden de control de los sabotajes lo definen uds, lo que importa es que controlen todo.

5.- El caracter limite es una de las alternativas, pueden usar lo que guten, pero es un poco mas de lo anterior, si borras pero después controlas el sabotaje del size, como sabes hasta donde estabas realmente y cuando se te esta escapando por no tener un limite?

6.- Siempre tomen como valido lo que dice blocks, asi lo dejamos en el enunciado 😉 

7.- No aplican mas, se eliminaron en la errata 1.2 porque no aportaban mucho académicamente hablando.

Saludos.-

**Comment by matiasfdevecchi** [comment]
Hola @iago64 , muchas gracias por las respuestas!

3. Lo que hacemos es primero disminuir el size, y luego hacemos algunas operaciones matemáticas para saber la cantidad minima de blocks necesaria. Si la cantidad de bloques es mayor a los necesarios, vamos removiendo los últimos hasta alcanzar los necesarios.

5. Creo que me expresé muy mal, me refería a si existe un limite en las cantidad de 'O' (por ejemplo) que puede escribirse en el archivo de oxígeno? Quizás entendi mal el video y no se refería a eso.

Saludos!

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

3.- Ok, buen punto, capaz ahí lo que les faltaría seria simplemente agregar algún caracter "delimitador" en la posición de Size +1 (salvo que justo sea que el último bloque esta lleno) como para poder saber donde termina posta posta su archivo.

4.- No, se puede generar tanto oxigeno, comida o basura como se quiera, por eso que justamente tienen que ir asignando bloques al archivo 😉 

Saludos.-

**Comment by matiasfdevecchi** [comment]
Gracias, cierro issue!
