### ISSUE TITLE
[I-Mongo-Store] Dudas inicialización File System

### ISSUE THREAD

**Issue by int0x80-sys** [sisoputnfrba/foro#2190]
Buenas.

Tengo unas dudas con la inicialización del I-Mongo-Store:

* ¿Tenemos que persitir las bitacoras de los tripulantes cuando se inicializa un FS ya existente? Si el sistema esta iniciando nuevamente, el id de los tripulantes va a reiniciarse. Por lo que los nuevos tripulantes tendrían bitacoras de instancias de tripulantes de una sesion anterior.

* Esta duda esta media relacionada con un issue anterior, pero me expando un toque mas. ¿Tienen definidos que archivos se deben chequear para conciderar una inicialización del FS "en limpio"?¿O van a tener en cuenta el criterio que nosotros hayamos escogido? Por poner un ejemplo, estamos pensando en considerar que un File System es nuevo cuando la carpeta del punto de montaje que nos pasaron no existe.

Espero que se hayan entendido las dudas.

Saludos 👋

**Comment by ezecastiglione18** [comment]
Buenas! Yo tengo la misma duda con tu primer consulta. Con la segunda, lo que hice fue verificar que existen los archivos del superbloque y de blocks. Pienso que son como los "mas importantes" de chequear de que verdaderamente ya haya un FS activo. Saludos!

**Comment by iago64** [comment]
Buenas ¿Cómo va?

Muy buena pregunta la primera y la respuesta es que básicamente nos da lo mismo lo que hagan, las bitácoras son un log forzado que pierden un poco de sentido al momento de cambiar de ejecución.
Como solución rápida, lo que pueden hacer es renombrar los archivos y que en lugar de ser BitacoraTripulante1.ims sean BitacoraTripulante1_old.ims para que eventualmente sean archivos que tengan referencia para poder controlar si no liberan los bloques del bitmap y demás a la hora de hacer los chequeos de los sabotajes.

Sobre este punto es un poco mas de lo mismo que la anterior, la idea de un FS limpio para nosotros es que no tengan ni un superbloque ni el blocks.ims, pero si para uds se les agrega que no tengan la carpeta del punto de montaje no hay drama, hacen un `rm -rf <punto_de_montaje>` y listo 😄, lo que nos importa mas que nada es el tema de recuperar un FS existente ya que es 99.9% posible que de una prueba a la siguiente necesitemos mantener algunos de los archivos de recursos para hacer mas fácil (especialmente las especificas del módulo i-mongo Store).

Saludos.-

**Comment by int0x80-sys** [comment]
Buenas.

Genial entonces. Gracias por las respuestas se nuevo.

Saludos 🚀
