### ISSUE TITLE
No puedo debuggear correctamente en mi VM

### ISSUE THREAD

**Issue by ezecastiglione18** [sisoputnfrba/foro#2191]
Buenas! Tengo algo muy raro con mi VM que hasta ahora no me paso nunca: cuando pongo un breakpoint en una cierta linea (en mi caso es la primer linea del main() ) y quiero debuggear, la linea donde empieza el debuggeo es otra linea totalmente distinta, me manda a una linea dentro de una funcion y no se porque. Ya probe pulleando lo del repo, pusheando y pulleando, reiniciando la VM, reiniciando la maquina fisica, todo. Y ya van dos dias asi en que no puedo "probar" el proyecto. Y se me acabaron las ideas jajajajja

Si se les ocurre algo que pueda intentar, estaria recontra agradecido! Saludos!

**Comment by int0x80-sys** [comment]
Buenas!

Ahora me meto yo en tu post jajajaja. Creo que nos paso una vez ese error. Y lo solucionamos haciendo Clean del proyecto y dandole a Build otra vez.

Espero que se te resuelva el problema.

Saludos 👋

**Comment by ezecastiglione18** [comment]
Recien probe lo que me dijiste y sigue sin andar bien :(

Igual tranqui, no te preocupes, gracias igual!

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Es una situación bastante rara y basicamente estoy teorizando en el aire, pero posiblemente tenga que ver con el hecho de que el debug para detenerse tiene que tener un breakpoint que tiene que estar sobre una linea de código que tenga una acción (por ejemplo un if o asignar una variable)

Saludos.-

**Comment by ezecastiglione18** [comment]
Claro, setee el debug en la primera asignación del main(), que le asignó a un t_config el resultado de leer_config(la ruta del config del iMongo)

Probé haciéndolo en otra asignación o en un if y pasa lo mismo

**Comment by iago64** [comment]
Buenas ¿Cómo va?

Estaríamos teniendo poca info al respecto y resolver este inconveniente lo veo bastante complejo vía mensajes del foro. 
Si podes conectarse el sábado al soporte (o al soporte entre semana) para verlo con un ayudante en vivo y en directo va a ser mucho mas directa la resolución porque se me ocurren varias alternativas pero entre mensaje y mensaje pueden pasar varias horas y no siento que sea eficiente.

A priori como validación rápida, fijate si el breakpoint esta marcado como habilitado (generalmente es azul claro) o si te lo deja como deshabilitado (generalmente en gris o con un signo de 🚫 dependiendo del tema o los plugins que tengas instalados en eclipse)

Saludos.-

**Comment by ezecastiglione18** [comment]
Sisi, tenía en mente preguntar en soporte. Pasa que si pregunto entre semana le saco todo el tiempo al que este jajajajaja, no es algo fácil de solucionar o que lleve tiempo. Pero bueno, dejo abierto este issue hasta que pueda hacer algo al respecto

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Al final en sábado de soporte  encontramos que el problema venia por una cuestión de incompatibilidad de versiones:

En primer lugar eclipse admite mas de 1 configuración de Build
![image](https://user-images.githubusercontent.com/1622109/124364159-ffdc8c80-dc15-11eb-83e7-60547b4c9a11.png)

Sumado a esto estaban subiendo los archivos ejecutables por lo que al modificar el código seguían compilando la versión Default.

Ahora al momento de debuguear la versión que se estaba ejecutando era la de Debug
![image](https://user-images.githubusercontent.com/1622109/124364208-521dad80-dc16-11eb-8fe3-ff496fcdcd16.png)

Es por esto que para GDB la función `main()` se encontraba en la línea 200 en el ejecutable de Default mientras que en la nueva compilación de Debug se encontraba en la línea 40 (por ejemplo).

@ezecastiglione18 primero que nada, gracias por los prints y por favor si falto algo de lo que charlamos avisa.

Saludos.-

**Comment by ezecastiglione18** [comment]
Que onda Dami? Muchas gracias a vos y a los chicos que vinieron a ver qué pasaba! Creo que no quedó nada, está todo bien explicado, así que pasó a cerrar el issue.

Saludos!
