### ISSUE TITLE
Sobre los tripulantes en block

### ISSUE THREAD

**Issue by frandom00** [sisoputnfrba/foro#2192]
Buenas, tengo una consulta rapida sobre los tripulantes cuando estan en block.  Si yo tengo por ejemplo 3 tripulantes en block, por cada ciclo de cpu se les va a sumar un tiempo en block a todos o solo al primero?

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Antes que nada perdon por la demora, se me paso de largo el mail de este issue.
Respecto a tu pregunta, no me termina de quedar claro, pero si tu pregunta viene por el lado de a quien le cuentan los tiempos de bloqueado solo le cuentan al primero, una vez que ese termina sus "ciclos" de bloqueado se pasa a ready y le empieza a contar al que estaba segundo y asi sucesivamente.

Saludos.-

**Comment by frandom00** [comment]
si, era esa la pregunta, genial, muchas gracias!
