### ISSUE TITLE
El tripulante termina sus tareas

### ISSUE THREAD

**Issue by SantiagoCarnezis** [sisoputnfrba/foro#2193]
Buenas, tengo una duda de que pasa cuando un tripulante termina sus tareas.
Nosotros a la fehca ya tenemos terminado el discordiador y la memoria (faltan realizar algunas pruebas de integracion de ambos modulos), pero nos entro una duda que el enunciado no especifica.
Cuando un tripulante termina sus tareas ¿Que se debe hacer? Habiamos interpretado que cuando termina el tripulante, del lado del discordiador, hay que liberar todas las estrucutras administrativas que tenemos y hacer que no este en ninguna cola (igual que hacemos cuando se ejecuta el comando expulsar tripulante), tambien se le notifica a miram que ese tripulante debe ser expulsado. Por el lado de ram se elimina de la memoria al tripulante. 
Pero ahora tenemos la duda de que lo que estamos haciendo esta mal, ya que al terminar sus tareas el tripulante seria completamente eliminado, esto incluye eliminarlo del mapa.

### 💭 Soluciones posibles

¿Puede ser que en vez de eliminarlo completamente lo pasemos a una lista/cola de eliminados? De esta forma el tripulante del lado de discordiador ya no haria mas nada (terminaria su hilo) y en ram quedaria el tripulante sin ser actualizado (osea en el mapa quedaria quieto).

Otra opcion seria eliminar al tripulante de discordiador (las estructuras administrativas) y en ram hacer lo mismo que en la opcion de arriba.

Por ultimo, sinceramente nos hacen ruido todas las opciones presentadas (la que estamos haciendo y las dos posibles soluciones) ya que en ningun momento estariamos liberando la memoria q ocupan los tripulantes ni la patota, es decir, en la teoria, cuando un hilo termina todas sus rafagas ¿El tcb no deberia ser eliminado de ram? LLevandolo al tp, cuando el tripulante termina sus tareas ¿No debria eliminarse de Ram? Si es asi, volvemos a la situacion que se presenta al inicio.
Desde ya muchas gracias

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Del lado Discordiador, al terminar un tripulante, el mismo debería quedar en la cola de EXIT.
Ahora en Mi-RAM, si lo que están haciendo es eliminar el TCB y por lo tanto volarlo del mapa esta bien, ya que justamente es un tripulante que no tiene mas nada que hacer.

Saludos.-

**Comment by SantiagoCarnezis** [comment]
Osea al momento de terminar su ultima tarea se borra de ram? como cuando se expulsa un tripulante?
Por otro lado, hay algun momento en el que se libere las estructuras de EXIT? Porque nosotros usamos una estructura para administrar al tripulante en discordiador y necesitamos hacerle free

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Efectivamente, cuando termine lo sacan de la RAM porque no tiene mas nada que hacer.
La cola de EXIT se limpia cuando termina el proceso, no creo que tengan algo que pese tanto en memoria que les traiga problemas por tenerlo en EXIT o si?

Saludos.-

**Comment by SantiagoCarnezis** [comment]
Claro no es tan pesado, lo podemos liberar cuando termina la patota. Muchas gracias!
Saludos
