### ISSUE TITLE
Duda Sabotaje

### ISSUE THREAD

**Issue by SantiagoOrlando29** [sisoputnfrba/foro#2194]
Buenas!

Tengo una duda con los Sabotajes.
Cuando discordiador recibe la señal del sabotaje de mongostore, que tiene que hacer?
Lo que estoy pensando es que le tiene que avisar a miram que se fije cuales tripulantes están en EXEC o READY, y de ellos fijarse cual está más cerca de la posición del sabotaje. Cuando encuentre ese tripulante más cercano, se lo manda a discordiador para que ahí ese tripulante resuelva el sabotaje. Estoy en lo correcto o la estoy flasheando?

Saludos.

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

La respuesta a tu pregunta esta en el [enunciado](faq.utnso.com.ar/enunciado) en la sección de Discordiador -> Administración de los sabotajes y además lo aclaramos un poco mas en el [video sobre discordiador](https://www.youtube.com/watch?v=_2jvwPBXSzo&ab_channel=UTNSO).

A priori Mi-RAM no juega de nada en los sabotajes y es algo que resuelven entre i-Mongo Store y Discordiador, pero por las dudas fijate el enunciado y el video a ver si termina de cerrar un poco la idea.

Saludos.-

**Comment by SantiagoOrlando29** [comment]
Muchas gracias!
