### ISSUE TITLE
Duda al retirar datos de Blocks para generar MD5

### ISSUE THREAD

**Issue by franciscoidalgo** [sisoputnfrba/foro#2195]
Buenas! Tenía una duda a la hora de generar el md5 de una File con los datos de Blocks.
Antes que nada, para generar el md5 uso una pipe en modo lectura a la que le paso la cadena de texto con los datos que rescato de blocks y guardo su respuesta en un char*. Hasta ahi funciona perfecto y está probado... Excepto por el hecho de que al generar esta cadena y pasarsela a mi función generarmd5() justamente me complican los 0 en Blocks (y sí... son '\0'). 

Pensé en generar un archivo temporal solo con los datos de la File (en el orden que indica su array BLOCKS) y usarla para generar el md5 pero no estoy seguro de esta implementación. Tambien podria remplazar los 0 por cualquier otro caracter a la hora de generar el md5 y sería más eficiente que crear una file, escribirla, usarla y destruirla peeeeeero me parece una solucion un poco barata porque no tengo certeza de que ese caracter nunca va a ser un caracter de relleno.

**Comment by iago64** [comment]
Buenas! Cómo va?

La idea de un archivo auxiliar es perfectamente válida, la idea del MD5 es que obtengan la suma de comprobación del contenido de su archivo, si para uds es mas fácil bajarlo a un archivo que tenga el contenido de los bloques en orden esta perfecto, medio que ahí no les dijimos como hacerlo porque hay varias formas y queremos que después nos cuenten que forma eligieron y que cosas buenas o malas le encontraron 😉 

Saludos.-

**Comment by franciscoidalgo** [comment]
Ooooook, voy a pensar un poco más en otra alternativa porque la del archivo era la que menos me gustaba pero, de última, voy por ahí.

**Comment by iago64** [comment]
Tranqui, la del archivo es una alternativa que plantearon algunos grupos en soporte, otra opción sería concatenar el contenido de los bloques, tene en cuenta que no tendrías que tener ningún '\0' (ni otro caracter) entre tus caracteres de recursos y no deberías sacar el MD5 mas allá del size de tu archivo.

Saludos.-

**Comment by franciscoidalgo** [comment]
Claro, con los '\0' me refiero a los bytes con valor 0 que le paso cuando, por ejemplo, arranque a leer por el último bloque de la lista que puede no estar completo. Al querer formatear la cadena que le paso a mi función md5 (que luego ésta usa en la terminal) genera un md5 engañoso. Igualmente, me acabo de dar cuenta de que, si bien ni siquiera van a llegar todos los caracteres a la terminal porque se cortaría en el primer byte en 0, el md5 definitivamente sería diferente... Solo que de una forma un poco cuestionable jajaja. Igualmente no sé cuán relevante sea, puede que lo intenté comentar mañana en el sábado de soporte.

**Comment by RaniAgus** [comment]
¡Buenas! ¿Alguna novedad desde soporte?
Una alternativa que te puede interesar para no crear un archivo intermedio es formar todo el string con solamente el contenido que te interesa y calcular su MD5 en base a él: https://askubuntu.com/questions/53846/how-to-get-the-md5-hash-of-a-string-directly-in-the-terminal

Lo que no llegué a probar es si alguno de estos métodos considera al `'\0'` del final del string, yo probaría lo siguiente: crear un archivo a mano, calcular el MD5 y fijarme el primero de todos los métodos cuyo MD5 coinicida. Recordá que la función que lo calcula es caótica (o sea, con el más mínimo cambio el resultado es completamente distinto) por lo que uno puede darse cuenta  a simple vista que ambos resultados son distintos.

Saludos

**Comment by franciscoidalgo** [comment]
Buenas! Justamente eso es lo que hago usando pipes. Primero genero el char* con los datos de blocks hasta donde dice el size del archivo y después uso la función de las commons de la catedra para armar eso mismo que pasaste ahí (la combinación de echo y md5sum). A fines prácticos funciona pero no debugee para ver qué string armá el string_from_format. Pero bueno, la función detecta la diferencia  y luego es capaz de corregirla y generar el md5 nuevo así que creo que va. Gracias!

**Comment by RaniAgus** [comment]
¡Buenísimo! No olvides debugear eso, quizás logueando por consola tanto el string que genera string_from_format como el MD5 que se obtiene, para estar seguro de que anda todo ok (cualquier cosa no dudes en consultar 😉) 
Si no quedó ninguna duda recordá que podés tomarte la libertad de cerrar el issue 👍🏻
