### ISSUE TITLE
Dudas sobre imongo y files

### ISSUE THREAD

**Issue by heinHertz** [sisoputnfrba/foro#2196]
Hola, después de leer el issue   https://github.com/sisoputnfrba/foro/issues/2189    me quedó una duda sobre el tema de la forma en que se borran/reducen los datos en imongo, en ese issue dicen en el punto 3:
```
En nuestro caso, al consumir recursos o descartar basura, no borramos el contenido dentro de blocks.ims sino que solamente modificamos el size (y también block_count y blocks si es necesario porque quedó algun bloque libre), análogo a los FS reales.
```
yo desde el principio cuando programé asumí que se borraban en forma "efectiva" los caracteres de Recursos( las O, B, ó C ).
 lo que digo con forma efectiva es tener por ejemplo almacenado en blocks.ims  por ejemplo: ( con longitud del bloque 5 bytes)
CCCCCBBB00CCCC0OOOO0     ---------> cuando lo reduzco/borro 'C' 5 unidades ----->  CCCC0BBB0000000OOOO0
siendo '0' (cero) el caracter que representa en mi sistema el ausente de dato ( tengo O que puede confundir con 0).
o sea basicamente directamente borrarlos( reemplazandolos por algun caracter 0 u otro).
mis dudas son las siguientes:
a)primero, ¿ esta bien hacerlo asi, borrar en forma "efectiva" los recursos( los caracteres O, B, C)  en el tp ?   o hay que hacerlo tipo sistemas "reales" de FS, donde de dejan los datos y se modifica solamente el size por ej?
b)  tambien lo del md5 asumi otra cosa :(  era sobre el archivo 🤕 ,  ahora voy entendiendo que hashear, serian los caracteres por ejemplo  del file Basura , agarro los datos directamente  ------->  hay   "BBBB" ( 4 B´S)  ----> ese string de B hash ?

bueno y gracias

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

1.- Esta bien, la idea es que uds implementen una forma y de ultima despues en el coloquio nos cuentan que ventajas o desventajas tiene la forma que implementaron.

2.- Efectivamente, el MD5 es sobre los datos que estan guardados en Blocks.ims.

Saludos.-

**Comment by heinHertz** [comment]
gracias!
