### ISSUE TITLE
Duda para encarar última tarea de un tripulante

### ISSUE THREAD

**Issue by NicolasWallovits** [sisoputnfrba/foro#2197]
Hola, quería consultar por el caso particular en que los tripulantes estén ejecutando y sea la última tarea que les queda. Particularmente si además esa tarea es de I/O, porque después de mandar su solicitud irían a bloqueados.

Entonces en estos casos cual sería la idea? 

Gracias!

### 💭 Soluciones posibles

a. Que al terminar el bloqueo pasen directamente a un estado de finalizado? 
b. Que se desbloqueen y vuelvan a una cola de Ready para después ejecutar aunque sea un ciclo de CPU que no haga nada? 
c. Que en esos casos soliciten una I/O pero no se bloqueen y pasen directamente a finalizado?

**Comment by iago64** [comment]
Buenas ¿Cómo va?

La solución correcta es la A, no esta el diagrama pero teniendo en cuenta que se puede expulsar un tripulante en cualquier momento cualquier tripulante podría pasar de su estado (READY, EXEC o BLOQ) a EXIT :)

Saludos.-

**Comment by NicolasWallovits** [comment]
Buenísimo. Gracias por la aclaración!
