### ISSUE TITLE
[MI-RAM HQ] Duda manejo memoria principal con un array

### ISSUE THREAD

**Issue by nicolasviegas** [sisoputnfrba/foro#2199]
Buenas, estamos modelando la memoria principal para trabajarla en la parte de segmentacion con un array, y nos surgio la duda respecto a la fragmentacion, se supone que en primer lugar estariamos ubicando un segmento al lado del otro, y la fragmentacion ocurriria una vez que removemos uno y quedaria un espacio libre el cual podria ser muy chico para otro segmento que quisieramos ubicar en su lugar? o en primer lugar tendriamos que dividir nuestro array memoria en espacios libres de distinto tamaño? teniendo asi que usar los algoritmos de ajuste(first fit, best fit) para empezar a ubicar las cosas desde el primer momento

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

La idea del array sinceramente no me resulta del todo atractiva para algo que va a tener tamaños variables y que va a cambiar constantemente, capaz una lista dinámica tenga mas sentido 😉 
Respecto a la fragmentación es como decís, tenes el espacio para guardar algo pero no lo tenes contiguo.
En un principio con la memoria completamente vacía best fit y first fit te van a dar los mismos resultados, ya que solo tenes un espacio vacío y el mismo se va reduciendo a medida que guardas cosas. Cualquiera de los 2 algoritmos empieza a tener sentido en el momento en el que se te generan los huecos porque se te van liberando segmentos.

Saludos.-

**Comment by TomasR264** [comment]
> Buenas! ¿Cómo va?
> 
> La idea del array sinceramente no me resulta del todo atractiva para algo que va a tener tamaños variables y que va a cambiar constantemente, capaz una lista dinámica tenga mas sentido 😉
> Respecto a la fragmentación es como decís, tenes el espacio para guardar algo pero no lo tenes contiguo.
> En un principio con la memoria completamente vacía best fit y first fit te van a dar los mismos resultados, ya que solo tenes un espacio vacío y el mismo se va reduciendo a medida que guardas cosas. Cualquiera de los 2 algoritmos empieza a tener sentido en el momento en el que se te generan los huecos porque se te van liberando segmentos.
> 
> Saludos.-

Hola, entonces si lo hacemos con una lista dinamica, la fragmentacion seria mas bien una simulacion, y no una fragmentacion real como se produciria en un array o en una MP por ejemplo, correcto?

**Comment by RaniAgus** [comment]
¡Buenas @TomasR264 ! En algún lado vas a tener tu `malloc()` del tamaño recibido por archivo de configuración, en el cual se van a guardar los datos "posta" (PCB, TCB y Tareas) y ahí sí se va a notar que hay fragmentación a la hora de liberar un segmento ya que esa parte está "libre" entre dos partes "ocupadas" (en cierto modo, a la memoria la podemos considerar como un array gigante de bytes).

A lo que se refiere Dami es que es conveniente que la estructura administrativa para manejar la tabla de segmentos (que en el caso del TP debe estar por fuera de ese `malloc()` con fines de hacerlo más simple) sea dinámica, y las listas cumplen con esa característica 😌

Saludos

**Comment by TomasR264** [comment]
@RaniAgus Disculpame, pero no me quedo del todo claro, entonces tendriamos que tener una lista dinamica con las cosas guardadas y a su vez un array donde simulamos que estamos guardando dichas cosas, pero en realidad solo estamos reflenando el tamaño y la posicion en la que estan guardadas dichas cosas en la memoria.

**Comment by RaniAgus** [comment]
@TomasR264 Cito el enunciado, en la sección "Administración de la memoria":
> En Mi-RAM HQ, al momento de inicializar, se reservará **un único bloque de memoria**, el cual será administrado bajo uno de dos esquemas de manejo distintos soportados (elegido por archivo de configuración)

O sea, al iniciar Mi-RAM vas a hacer un `malloc()` que va a ser ese "único bloque de memoria" en donde se van a guardar los segmentos de PCB, TCB y Tareas. Su tamaño también se encuentra definido por archivo de configuración en el campo `TAMANIO_MEMORIA` y como se menciona en el [video de Mi-RAM](https://www.youtube.com/watch?v=yP-NdU3bSa4) éste debe quedar fijo.

Por otro lado, vas a tener una estructura administrativa que te permita **interpretar qué tiene ese bloque de memoria**, o sea, si por ejemplo vos tenés un bloque de memoria de 128 bytes con el siguiente contenido:
```
+----+------------+------------+-------+-------------------------+----+-------+
| S0 | Segmento 1 | Segmento 2 | Seg.3 |       Segmento 4        | S5 | Seg.6 |
| 8B |    21 B    |    21 B    |  11B  |          46 B           | 8B |  13B  |
+----+------------+------------+-------+-------------------------+----+-------+
```
Cuando quieras ir a buscar la información que se encuentra en el segmento 2 (que supongamos que es un TCB), una implementación posible es que en tu estructura administrativa cuentes con el dato de que el segmento 2 arranca en el byte 29, por lo que ya con ese dato sabés que el TCB está en `punteroQueDevuelveElMallocInicial + 29`. 

Pero, muy importante, los datos van a estar guardados **únicamente en ese gran bloque de memoria** (en otras palabras, la estructura administrativa solo te ayuda a saber dónde ir a buscarlos, no los tiene repetidos). 

Saludos
