### ISSUE TITLE
[Caso de prueba] Memoria Segmentación Base - Consulta

### ISSUE THREAD

**Issue by eguiggiaro** [sisoputnfrba/foro#2200]
Hola,

¿Cómo están?

Tenemos una duda con el caso de prueba **"Memoria Segmentación Base"**.

Se indica que la configuración del caso para MiRAM es:

 **Mi-RAM-HQ.config**
- TAMANIO_MEMORIA=256
- ESQUEMA_MEMORIA=SEGMENTACION

Lo que se pide es iniciar una patota de 10 tripulantes con un archivo de tareas que tiene 60 caracteres.

Haciendo las cuentas tendríamos:

- 8 bytes -> PCB
- 21 bytes x 10 tripulantes = 210 bytes -> TCBs
- 60 bytes = Tareas

Total = 278 bytes

En lugar del resultado esperado, ¿no debería generarse un error de denegación de espacio en memoria? ¿O estamos entendiendo algo mal?

Gracias por la ayuda!!

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Claramente fue un pifie de nuestra parte, lo vamos a estar arreglando en estos días.
Por cierto, ojo que las tareas pesan 63 bytes, faltan los '\n' 😉 

Saludos.-

**Comment by eguiggiaro** [comment]
Genial gracias!!!

Ahí les dejamos uno más por si les sirve:

Caso: **Memoria Paginación Base**
Corrección: en el config de la memoria debería decir "ESQUEMA_MEMORIA=PAGINACION" en lugar de "SEGMENTACION".

Cierro el issue.
