### ISSUE TITLE
2 fwrite consecutivos

### ISSUE THREAD

**Issue by Javo656** [sisoputnfrba/foro#2201]
Buenas, estamos con escribiendo los archivos del mongo, el tema es que hacemos múltiples fwrites consecutivos pero por alguna razón solo nos escribe el primero. Probamos usando fflush intercalados, 1 al final de todos los fwrites, cerrando y abriendo el archivo de vuelta.... Nada nos funcionó. El código es el siguiente:
```c
void iniciar_superbloque(FILE* archivo) {
    uint32_t block_size = 64;
    uint32_t size = 64;
    void* puntero_a_bits = malloc(size);
    t_bitarray* bitmap = bitarray_create_with_mode(puntero_a_bits, size , LSB_FIRST);

    for(int i = 0; i < size ; i++) {
        bitarray_clean_bit(bitmap, i);
    }

    fwrite(&block_size, sizeof(uint32_t), 1, archivo);
    fwrite(&size, sizeof(uint32_t), 1, archivo);
    fwrite(bitmap, sizeof(bitmap), 1, archivo);

    fflush(archivo);
}
```

**Comment by RaniAgus** [comment]
¡Buenas!
1. Ojo con el tamaño del bitarray, porque como pueden ver en la firma de [`bitarray_create_with_mode(3)`](https://github.com/sisoputnfrba/so-commons-library/blob/834e821204f3e0a54f7e70b40250047e65d2a493/src/commons/bitarray.h#L65-L77), el size que se indica es en __bytes__ y no _bits_. Por lo tanto, lo que está haciendo el código es crear un bitarray de 512 bits y setear en cero solamente los primeros 64.

2. Ojo con el puntero que le están pasando en el último `fwrite()`, ya que lo que contiene un [`t_bitarray`](https://github.com/sisoputnfrba/so-commons-library/blob/834e821204f3e0a54f7e70b40250047e65d2a493/src/commons/bitarray.h#L43-L47) es un struct con varios atributos adentro, entre ellos un _"puntero al bitarray posta"_, por lo que se estaría escribiendo ahí en el archivo es ese mismo struct.

3. ¿Están seguros que solo se escribe el primer `fwrite()`? Yo revisaría la forma con la que están abriendo el archivo, les dejo a mano el link al manual de `fopen()`: https://man7.org/linux/man-pages/man3/fopen.3.html
Por otro lado, pueden ejecutar el comando `hexdump -C [nombre_de_archivo]` para chequear su contenido para estar seguros de que su diagnóstico es el correcto.

Saludos

**Comment by matiasfdevecchi** [comment]
Buenas, dejo un pequeño aporte porque nos pasó algo relacionado a lo que comenta Agus que puede ser tu problema:

El editor de texto que viene por defecto en Linux lee en ascii y lee hasta el primer '\0' por lo que nos estuvimos encontrando, asi que seguramente ese sea el motivo por el cual te aparece uno solo ya que al guardar 64 estás guardando un byte que contiene 64 ('@') y tres bytes que contienen 0 (que es '\0')

Como dijo Agus, podes usar ese comando. También tenes `xxd -b path_al_archivo` el cual les va a dar el contenido en bits (viene muy util para el bitarray), agrupados en bytes, y además el contenido en ascii (poniendo '.' donde hay '\0')

Y por último hay un programa que trae Linux en el Menu > Programación, que no recuerdo el nombre ahora mismo pero era uno de los primeros, y permite ver el cotenido de un archivo en hexa y modificarlo (medio poco intuitiva de usar al principio pero sirve si necesitas modificar los bits para probar sabotajes)

**Comment by Javo656** [comment]
Genial. hoy lo reveo con todo esto que dicen. Muchas gracias!
