### ISSUE TITLE
[Mi-Ram-HQ] Paginación : varias dudas de enunciado y programación

### ISSUE THREAD

**Issue by jcastagno99** [sisoputnfrba/foro#2202]
Buenas! estoy peleandome con este esquema y  a medida que me iba leyendo los issues (que voy a referenciar mas adelante) relacionados y con algunas respuestas del labo, se me terminaron mezclando conceptos y al final me stuckee, son varias preguntas (pido perdón de antemano al ayudante que tenga que leerse esta biblia) así que voy a ir por orden y tratando de que se entienda lo mejor posible : 

**1) Dirección lógica:**
Varios de mis problemas vienen con la bendita **dirección lógica** que guardo en memoria (tanto la de las tareas de la patota, como la de la proxima tarea de un tripulante y la direccion logica del pcb del tripulante), despues de leerme varias veces el issue #2183 entiendo que mas o menos lo que yo guardo es algo que me ayude a no tener que iterar páginas y que puede ser mas o menos lo que yo quiera (siempre y cuando entre en un uint32_t), ahora desde este contexto se me quedaron varias dudas:

**A)** Tanto para la dirección lógica del segmento de tareas (la que va en el PCB) y para cada una de las direcciones que apuntan de cada tripulante al inicio del PCB, yo las había pensado como si fuera teoría, N° página | offset, el tema de esto es que no tiene mucho sentido, yo se que siempre el PCB es lo primero que guardo y que lo guardo en el siguiente orden : 

  **(uint32_t) PID | (uint32_t) Dir.log.tareas**

Es decir, que para toda patota, sin importar cual, el inicio del PCB de cualquier tripulante de la misma, es Pagina 0, offset 0, (dentro de su tabla de páginas) entonces no le doy ningun uso.
Lo mismo me pasa con el inicio de las tareas, yo se que siempre guardo las tareas luego del PCB, entonces siempre puedo decir, "Arranca en la página que viene luego de 4bytes (los 2 uint32_t del PCB)" y como me guardo el tamaño de todas las tareas en una estructura administrativa (esto lo dicen en el issue #2165) , yo puedo saber donde termina y en que página arrancan los tripulantes, por lo que tampoco le doy uso.. entonces (suponiendo que este razonamiento es válido) ¿Para que la uso o como?

**B)**  Con la dirección de la próxima tarea, yo pensaba una solución similar de reconstruir el string (como la que se menciona en el issue #2183) pero viendo la respuesta pensé en 2 posibles soluciones: 

**B1)** Guardarme la cantidad total de tareas, y que ese uint32_t de la proxima tarea me diga : "Voy por la tarea 1" y cuando lo actualizo simplemente le sumo 1 y ya esta, PERO ... yo no tengo forma de saber  donde arranca mi tarea número N (sacando el caso de la primera que podría hacerlo como menciono en la pregunta A), por lo que para identificar donde empieza mi tarea N, o me traigo todo el string de tareas, lo spliteo y con ese número (y asumo un centinela) puedo saber cuantos bytes debo moverme desde el inicio del string.
**B2)** Me guardo el tamaño de cada tarea en una estructura administrativa (además del tamaño total), con el número que me indica por cual tarea voy, identifico cuantos bytes ya leí (por los tamaños que guarde antes) y eso lo usaría como offset, entonces podría hacer: La página N a partir de 4bytes y luego el offset, (tambien el tamaño me ayudaría a saber donde corta la tarea). 

¿Es valida alguna de estas? no se hasta que punto puedo guardarme info en estructuras administrativas.

A partir de aca son preguntas mas cortitas, lo juro.

**2) Tareas con unos caracteres de más en memoria:**
En el mismo (issue #2183) mencionan que van a controlar las páginas en RAM, ¿Agregar centinelas al string de tareas y luego guardarlo en memoria se podría? porque esto haría que tal vez por tamaño tenga que traerme otra página y los resultados difieran de otros grupos, el porque de un centinela es para poder leer desde memoria una tarea hasta llegar al mismo y saber que ahí se temina (esto es sin guardar tamaños de cada tarea, es algo que va mas a como implementamos segmentación, pero me surgio la duda tambien leyendo el issue).

**3) Bit de uso cuando se guarda en SWAP:**
Entiendo que todo el tiempo que me traigo una página a RAM, lo seteo a 1|true|estaSiendoUsado, supongamos que ahora, no entra toda la patota en RAM y guardo parte en RAM y parte en SWAP, la parte que va a Swap, por descarte su bit de uso es 0|false|noLoUsaNadie ¿No? y bueno al traer la página a RAM mediante el algoritmo, se pondría nuevamente en 1|true|estaSiendoUsado.

**3.5) Momento de inicializar SWAP:**
Entiendo que cuando el enunciado dice:
>Y el proceso de swap comenzará una vez que se encuentre llena la memoria principal.

No se refiere a que el mapeo (mmap) lo haga cuando se llene la memoria, sino que empiece a guardar en SWAP cuando no queden páginas libres, PERO el levantar el área de SWAP debería ser ni bien arranca el módulo. 

**4) Como saber si un frame esta totalmente o parcialmente libre:** 
Esto viene al caso de que en un frame tenga la mitad de algo (creo que solo podría ser una parte del segmento de tareas u otro TCB para este caso) y un TCB, me expulsan dicho TCB y queda fragmentación interna, yo para poder marcar el frame como libre debo tener el 100% libre, entonces ¿podría llevar un contador de bytes en uso dentro de un frame? que inicializado seria igual al tamaño del frame (esto mas que pregunta es querer validar mi propuesta) 

**5) Dump de paginación:**
En otro issue (#2162) se daba a entender que el dump se hacia a partir de recorrer los frames (algo que yo tengo como un t_list* y que me es facil de recorrer) pero el problema viene cuando me piden el proceso del frame, yo desde un frame no tengo forma de saber que proceso lo ocupa. Tengo una doble referencia (un frame saque que PÁGINA lo ocupa y a su vez una página sabe donde empieza su frame en memoria) pero para poder identificar el proceso tendria que hacer muchas iteraciones muy muy feas, ¿podría guardarme en el frame (la estructura administrativa de frames) el proceso al que pertenece?
esto lo solucionaría rápido, capaz la respuesta es : "Hace lo que quieras con las estructuras administrativas" pero a veces me han dicho que ciertas cosas no las puedo guardar y menos cuando son cosas que van memcpyadas (este verbo lo acabo de inventar) directamente a memoria, en este caso seria el PID.

Perdón por el mucho texto, pero venía acumulando dudas hasta que exploté, para el ayudante que lo vaya a responder le dejo un meme en compensación:

![14ea4734-a08c-4e37-ba4d-4c7e467519df](https://user-images.githubusercontent.com/49038828/124369194-78a40e80-dc3f-11eb-977c-0806ba74bb9d.jpg)

**Comment by iago64** [comment]
![image](https://user-images.githubusercontent.com/1622109/124371173-8e243300-dc55-11eb-991d-7857943b45a9.png)

1-A.- Básicamente la idea de una dirección lógica es que a uds les sirva, bien puede ser pagina 0 - offset 0, pero en segmentación por simpleza puede ser el número de segmento dentro de su tabla de segmentos, no se olviden que las estructuras sirven para *ambos* esquemas de administración de memoria.

1-B.- La opción B1 es válida, con lo cual, la dirección lógica de la próxima tarea bien puede ser un program counter y que les indique el índice de su lista de tareas (donde tienen la dirección en pagina - offset o el puntero a su memoria dentro del segmento de tareas).

2.- Cuantos más centinelas mas tenes pensado agregarle? Las tareas están bastante bien claras, con `\n` se delimitan las tareas y todas terminan con ese caracter (ya que al final de cuentas son los saltos de línea del archivo). Eventualmente pueden tener una estructura como planteaste en el punto 1-B1.

3.- Afirmativo, si tenes algo en swap digamos que el bit de uso tiene el mismo sentido que un cenicero en una moto. 

3.5.- Exacto, uds crean el archivo de swap de entrada pero empiezan a tirarle cosas solo cuando se llene la memoria.

4.- Estructuras administrativas, queremos que se las ingenien y piensen soluciones que podría implementar Linus Thorvalds en el kernel 6.0 de Linux... bueno capaz no tanto, pero si queremos que resuelvan ese tipo de problemáticas y por eso la única restricción que les pusimos fue que los datos van en la memoria cuyo tamaño les definimos por archivo de config pero después las estructuras administrativas son totalmente libres.

5.- No hay problema con las estructuras administrativas, agregar campos como ser el proceso que es "dueño" de ese frame:
![image](https://user-images.githubusercontent.com/1622109/124371313-ef98d180-dc56-11eb-97a8-dfa15bd69f0d.png)

Últimas palabras para cerrar la respuesta y en lo que podría haber resuelto todo el issue (pero como yo tuve que leer todas las preguntas les hice leer todas las respuestas 😛)
Las estructuras administrativa son libres, pueden agregar toda la info relacionada a los segmentos / frames que necesiten ya que queremos que entiendan que lo que se ve en la teoría es el modelo ideal (por eso, por ejemplo, se habla de algoritmos óptimos que no se pueden implementar en la realidad)

Saludos.-
![WdcSZbf](https://user-images.githubusercontent.com/1622109/124371448-2fac8400-dc58-11eb-81b5-a46b0e2c7be8.gif)

**Comment by jcastagno99** [comment]
Perfecto!!!
Quedo todo claro, ahora me toca ponerme a implementarlo todo, muchas gracias! 

Frente a tal velocidad y tanta respuesta solo me queda decir:
![61d64acf-3c41-4e7e-b558-e1a75f85b08f](https://user-images.githubusercontent.com/49038828/124375994-313b7380-dc7b-11eb-975a-fbb99f8a0aef.jpg)

**Comment by jcastagno99** [comment]
![image](https://user-images.githubusercontent.com/49038828/126082741-c8d4921f-2767-4d23-acc9-5f6ba62559e1.png)


Reabro el issue con dudas que puse en otro post, pero no iban con el título así que las dejo en ese que es mucho mas generico.


**1) Caso borde de tamaño de pagina:**
Yo entiendo que entre mas robusto el codigo mejor, pero tiene sentido modelar pensando en tener paginas de 2 bytes o menos? pregunto esto especifico porque es el unico caso que encontre en el que rompe mi codigo, me puede caer algo asi en las pruebas? por lo que vi en el documento de pruebas, los tamaños van de 32 a 64 bytes, igualmente mi unico problema es con 2 o menos.

**2) Sobre cuando se elimina un tripulante en paginación:**
A) Cuando se borra a un tripulante, el unico caso en el que se modifica algo (paginación) es si al liberarlo el frame quedara 100% libre? en dicho caso deberia marcar al frame como libre y borrar al tripulante del mapa, en cualquier otro caso realmente no hago nada, porque entiendo que todos los tripulantes ya vienen en el INICIAR_PATOTA y que no puede haber 2 procesos compartiendo frames (en teoría sí, para compartir memoria, pero creo que no es lo que se busca aca no?, espero que la respuesta sea no) 
B) ¿Debería borrarlo de memoria virtual? por borrarlo me refiero a marcar que ese espacio esta libre para poder "compactar" la memoria virtual y tal vez meter otra patota? no se me ocurre otra utilidad. 

Leí estas preguntas en otros post pero no me quedaron claro, pero eso lo repregunto.

**Comment by iago64** [comment]
![image](https://user-images.githubusercontent.com/1622109/126163496-d1394f63-67da-406b-8ea4-b8fda221754f.png)

1.- Acaso tenemos fama de ser tan mala leche? don't worry, es demasiado rebuscado, una página de 2 bytes es literalmente mas grande el desperdicio de espacio que el beneficio de tenerlo... con lo cual no se compliquen para tanto.

2.A- Cuando achuren a un tripulante, como bien decís, marcan la página vacía si no tienen nada mas, pero es algo que solo les afecta a sus estructuras administrativas.

2.B.- En la memoria virtual están las cosas que bajaron de la principal por falta de espacio, con lo cual, si justo se dio la casualidad de que mandamos a funar un tripulante que estaba justo en virtual... si, marcalo como libre (si se libera toda la página) y ya.

Saludos.-

**Comment by jcastagno99** [comment]
1.-  ![image](https://user-images.githubusercontent.com/49038828/126230785-7dfa43bb-a60c-442f-aa8b-a75c76cc08ea.png)
Na mentira jajaja, pregunte por las dudas y porque si explota durante las pruebas finales me va a dar algo, prefiero atajarme todos los angulos posibles.

2.- Algo que no me quedo claro, no debería tambien marcar el frame como libre si cuando mato al tripulante ya no hay mas nada en ese frame?

2,2.- Me resulta raro que solo afecte estructuras administrativas, podria no borrarlo (porque uso el espacio de las paginas para hacer calculos con punteros) y solo marcar en otra estructura que el tripulante fue achurado? aunque eso no se consulta en ningun lado por lo que no se como hacer que se vea reflejado (mas allá de sacarlo del mapa)

**Comment by iago64** [comment]
1.- Resumo en 1 meme
![image](https://user-images.githubusercontent.com/1622109/126251991-2c083db3-bea1-432c-983e-be76f64fca1e.png)

2.- Si no hay mas nada en el frame, si, ahi si lo marcan como libre

2.2.- Pueden marcarlo como funado y listo, la joda es que solo les va a impactar al momento de que se libere un frame completo, pero si juuusto se da que al funar a un tripulante queda un cachito de otro tripulante en el frame, el frame sigue vivo :)

Saludos.-

**Comment by jcastagno99** [comment]
En mi cabeza era mas del estilo (y para seguir el hilo de memes)
![f64fc708-3fae-4a82-868e-05aa11b7c208](https://user-images.githubusercontent.com/49038828/126392959-0bc7b52e-53cc-493e-a47e-8d6c430c9301.jpg)

2.- Perfecto, todo claro, gracias!
