### ISSUE TITLE
[Mi-RAM-HQ] Duda sobre segmentos y dirección lógica - antes de que sea demasiado tarde

### ISSUE THREAD

**Issue by GuidoDipietro** [sisoputnfrba/foro#2203]
Hola.
Tenemos segmentación funcionando al 100% y correctamente, pero a raíz de unas dudas sobre el _dump_, surgen **dudas existenciales** y un poco de **terror**.

Agradecería un 👍 sobre lo ya hecho, o bien una _bofetada_ 👊 para cambiar esto mientras todavía tengamos tiempo.
### Tiempo estimado de lectura: 2 minutos.

---

Por ahora, yo consideré, dado el enunciado:

> "Para Mi-RAM HQ, se almacenarán los PCB’s, los TCB’s y sus respectivas instrucciones, es decir, solamente se **utilizaran _dos segmentos_ por patota** (uno para el PCB y otro para las tareas) **y _uno_ para cada tripulante** (para almacenar el TCB)."

- **Patotas** - tienen 2 segmentos: PCB y Tareas
- **Tripulantes** - tienen 1 segmento: TCB

Sin embargo, los tripulantes, al ser el equivalente a hilos de un proceso, están asociados a un PCB (guardan su dirección en el TCB), y por ende están asociados a una Patota, aunque los administro como si fueran entidades separadas (tengo como estructuras administrativas una **tabla de patotas**, y una **tabla de tripulantes**, para manejar estos segmentos).

Ahora bien. Resulta que en el Dump, necesito mostrar algo como:
```
Patota 1 - Segmento 0 - etc (PCB)
Patota 1 - Segmento 1 - etc (Tareas)
Patota 1 - Segmento 2 - etc (un TCB)
Patota 1 - Segmento 3 - etc (un TCB)
...
```
Por lo que entiendo.

En otras palabras,

¿los segmentos de los TCB deben considerarse **parte de la Patota**?

Y la duda relacionada:
¿Cómo queda la dirección *lógica* de todo esto?
¿Qué se guarda en cada TCB en el campo `dl_tareas`, por ejemplo? ¿Algo como `segmento 1 | offset 0`, o la dirección de inicio del segmento en nuestra RAM inventada (p. ej., `500` si es que el segmento se cargó en el inicio `500` de nuestro `void* memoria_principal`)?

Por ahora está guardado ese `500`, porque los segmentos de TCB solamente están relacionados a la patota mediante la dirección del PCB (que también estaba guardada como inicio del segmento en RAM).

mmmmmmmmm

:thinking:

~inserte plegarias a todos los dioses~

---

### Gracias por la lectura,

grupo **...undefined**

**Comment by iago64** [comment]
Buenas ¿Cómo va?

1.- Si, los TCBs son parte de una patota, de hecho por eso tienen el puntero al PCB 😉.

2.- Lo que sea que guarden en la dirección lógica del TCB para el segmento de tareas depende mucho de como tengan sus estructuras administrativas, pueden tener por ejemplo el índice de su lista de segmentos global, pueden tener el puntero a la memoria posta posta o pueden tener algo que les indique como decís `segmento 1 - offset 0`. Lo que buscamos ahí es que uds se las ingenien para armar un sistema de direcciones lógicas y que no necesariamente sea igual a como se ve en la teoria.

Saludos.-

**Comment by GuidoDipietro** [comment]
Me alegraste el día por segunda vez (aunque contesto hoy 2am).
No tengo que rehacer Segmentación, hurra. 🥳 
Solo cabe agregar número de segmento dentro de la patota a los segmentos de TCB, y ajustar el dump.

Gracias por la respuesta,
Un saludo
