### ISSUE TITLE
[Mi-RAM HQ] ACTUALIZAR_ESTADO

### ISSUE THREAD

**Issue by matiasfdevecchi** [sisoputnfrba/foro#2204]
Buenas, anterior a la versión 1.3 del enunciado ya habíamos realizado un comando en el servidor de Mi-RAM HQ llamado ACTUALIZAR_ESTADOS, el cual le pasamos una lista de TID+Nuevo estado y los actualiza en la memoria. Podemos mantenerlo así o tenemos que cambiarlo para cumplir con lo nuevo?

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

No hay problema con que mantengan ese mensaje, de hecho lo que nosotros les definimos en la parte del servidor de Mi-RAM fue lo básico, pero tampoco les definimos mensajes de handshake o tipos de respuestas.

Saludos.-
