### ISSUE TITLE
[i-MongoStore] Sabotaje a la lista de blocks

### ISSUE THREAD

**Issue by matiasfdevecchi** [sisoputnfrba/foro#2205]
Buenas, el MD5 es sobre el contenido de la lista de blocks, por lo tanto si tengo el resource file de Oxigeno con la lista [1,2,3,4,5], el MD5 va a ser el mismo siempre y cuando cambie el orden manteniendo 5 como último. En otras palabras, el MD5 solo va a notar que se alteró el file, si el último bloque está incompleto y se cambió su posición.

Es correcto esto? En el caso que nos cambién los bloques [1,2,3,4,5] por [2,1,3,4,5] no tendríamos que corregirlo, no?

**Comment by ncoen97** [comment]
Buenas, es como decís, a fin de cuentas si modificamos el orden de los primeros dos bloques no estaríamos modificando el contenido del archivo así que no habría sabotaje.
Saludos!
