### ISSUE TITLE
Dudas, un poco rebuscadas (tamaño del mapa, casos extremos de sabotaje, mapa de MI_RAM, tamaño de la cola de BLOQ).

### ISSUE THREAD

**Issue by SForlizzi** [sisoputnfrba/foro#2206]
Buenas noches, tengo unas dudas muy puntuales:  

1. Hay que contemplar el caso de que el mapa pueda contener posiciones mayores a la 9|9? Dado que, de momento, en ninguna prueba, o en el enunciado hubo ningún ejemplo de una posición de dos dígitos. Es algo que se tomará en cuenta, o es un caso que se puede desestimar por cuestiones de diseño?
2. Hay que contemplar el caso de que, al momento que le llegue la señal de sabotaje al Discordiador, estén todos los tripulantes en New (siendo que, ninguno podría resolver el sabotaje ya que los únicos que podrían sean los que estarían en EXEC/BLOQ en el momento en que llega la señal) ? O no se toman en cuenta casos tan rebuscados.
3. En el mapa de MI_RAM_HQ, hay que dibujar únicamente a los tripulantes y su movimiento por el mapa, no? Sin tener en cuenta por ejemplo, los recursos.
4. En el video de la cátedra de Discordiador (minuto 3:17), comentan que solo hay un dispositivo de I/O, por lo cual no se atienden pedidos en paralelo. Esto desemboca en que, la cola de BLOQ solo pueda tener un tripulante por vez? O que, pueda tener muchos tripulantes, pero solo el primero pueda ejecutar su I/O y los demás estén esperando a que el mismo termine su espera.

**Comment by ncoen97** [comment]
Buenas, paso a responder:

1. Con que el mapa llegue hasta 9|9 están bien.
2. Pueden no contemplarlo.
3. Correcto.
4. La segunda opción es la correcta.

Saludos!

**Comment by SForlizzi** [comment]
Mil gracias, cierro issue.
