### ISSUE TITLE
Duda sobre lista de sabotajes en imongo

### ISSUE THREAD

**Issue by heinHertz** [sisoputnfrba/foro#2207]
Hola, tengo una duda sobre la lista de sabotajes en imongo, exactamente como se usa:
En la hoja 24: 

> La forma de corromper la información del File System es simple; a mano, alguien con intenciones de verificar que el file system sea capaz de recuperarse, modificará un archivo y enviará la señal SIGUSR1 al proceso i-Mongo-Store para que éste notifique al módulo Discordiador.

segun entiendo cuando hay un sabotaje, imongo tiene alguna modificación de archivo al resolver el fsck:
a) cuando termina le manda una posición de sabotaje que tiene en la lista, no todas o es todas? es correcto esto?

**Comment by RaniAgus** [comment]
¡Buenas! Veo que hay una pequeña confusión en cuanto al orden, el cual sería:
1. Alguien desde afuera modificará un archivo
2. Ese alguien envía la señal `SIGUSR1` a IMS
3. IMS envía a Discordiador el aviso de que hubo un sabotaje indicando su posición y espera a que éste responda
4. Discordiador hace lo suyo (bloquear a todos, mover al más cercano, etc) y termina avisándole a IMS que un tripulante quiere iniciar el fsck
5. IMS inicia el fsck

En cuanto a la posición, es una sola y digamos que se van iterando, o sea, si yo recibo 4 sabotajes y en el archivo config tenemos `[1|1, 3|2, 3|3, 4|5] ` esto significa que el primer sabotaje va a ser en `1|1`, el segundo en `3|2` y así sucesivamente.

Saludos

PD: Edité el formato de la cita en markdown para poder leerlo mejor ya que en una sola línea se me complicaba un poco :P, se puede hacer con un ">" adelante 😌

**Comment by heinHertz** [comment]
Gracias!

**Comment by SantiagoIvan** [comment]
Hola! 
Citando a Agus:
"si recibimos 4 sabotajes"
Podemos recibir a la vez varias señales de sabotaje? No se si en las pruebas finales van a hacer sabotajes al mismo tiempo tocando los archivos de superbloque o Files, o van a producir un sabotaje, esperan pacientemente a que termine  y despues generan otro sabotaje

**Comment by RaniAgus** [comment]
¡Buenas @SantiagoIvan ! Me refería a segunda: _"van a producir un sabotaje, esperan pacientemente a que termine y despues generan otro sabotaje"_

En otras palabras, se van a producir varios sabotajes mientras esté levantada una única instancia de IMS (por eso hay varias posiciones en el config), pero solo uno a la vez.

Saludos

**Comment by SantiagoIvan** [comment]
Gracias!
