### ISSUE TITLE
Multiprogramacion MI-RAM-HQ

### ISSUE THREAD

**Issue by totomolino** [sisoputnfrba/foro#2208]
Buenas, tenia una consulta sobre mi ram que no sabia bien que template usar jeje. Bueno es la siguiente:

- Tenemos que poder dejar a los tripulantes manipular la memoria al mismo tiempo, o tenemos que dejar pasar de a un tripulante?

**Comment by iago64** [comment]
Buenas! Cómo va?

La idea de un servidor multihilo es que múltiples clientes puedan operar al mismo tiempo, pero sincronizando el acceso a los recursos críticos (memoria, swap si lo tenes, etc)

Saludos.-

**Comment by totomolino** [comment]
Buenisimo, entonces sincronizo donde sea critico el acceso de los tripulantes aunque sea multihilo.

Muchas gracias!!!

**Comment by iago64** [comment]
Buenísimo, cerramos el issue entonces 😄
