### ISSUE TITLE
Paginación con swap y límite de la memoria

### ISSUE THREAD

**Issue by matiasfdevecchi** [sisoputnfrba/foro#2209]
Buenas, en la teoría de paginación con swap, si tu area de swap tiene espacio hasta 1024 páginas y en tu memoria principal tenés 128 frames, tu sistema solo puede tener 1024 páginas porque las que están ocupando frames siguen estando en el area de swap.
Quería confirmar si en el tp es de la misma manera o si en el caso anterior, tenemos en total espacio para 1152 páginas (me pareció haber leído un issue que iba por esta opción).

Saludos!

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Tienen que sumar las paginas de swap y de memoria principal.

Saludos.-
