### ISSUE TITLE
[Casos de prueba] dudas generales

### ISSUE THREAD

**Issue by eguiggiaro** [sisoputnfrba/foro#2210]
Hola, ¿cómo están?

Les comparto algunas dudas que nos surgieron revisando el nuevo doc de pruebas. Disculpen por la longitud!!

1. **Comando EXPULSAR_TRIPULANTE A1**: En nuestra implementación, el EXPULSAR_TRIPULANTE sólo recibe un tripulante. La numeración del tripulantes es única para el sistema. ¿Sería correcto en este caso?

2. **Relacionado al anterior:** nuestras patotas se identifican con números y no con letras. Si hacemos la analogía con el sentido de la prueba, ¿estaría correcto?

2. ¿**DETENER_PLANIFICACION** es equivalente al PAUSAR_PLANIFICACION que desarrollamos?

4. **Memoria - Segmentación**: en el doc se menciona un punto en el cual la patota finaliza, y se liberan todos sus segmentos. Esto debería suceder cuando todos los tripulantes de una patota llegan a estado finalizado, ¿correcto?

5. **Memoria - Segmentación**: respecto a los bloques libres, en nuestra implementación, si dos tripulantes aledaños liberan su segmento, no se generan 2 segmentos libres, sino que ese segmento libre se fusiona, pero esto no es parte de la compactación. ¿Deberíamos dejar dos segmentos libres, y sólo fusionar en la compactación?

6. En el checklist de MiRAM indican "**Se mantiene actualizado el Mapa ***".  Tiene un asterisco pero no encontramos alguna nota relacionada. ¿Hay alguna nota sobre este punto?

7. Última!: para los **memory leaks** estamos usando Valgrind ¿Se espera 0 absoluto en ambos contadores? Estamos en 600 bytes por proceso. Y para las **esperas activas**, no sabemos exactamente cómo controlarlas. ¿Deberíamos mirar el uso de CPU? 

Gracias y disculpas de nuevo!!

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

1.- La idea es que eliminen al tripulante 1 de la patota A, eventualmente si sus números son únicos en todo el sistema, calculen que sea el primero y el tercero de la patota A (la idea es que quede un tripulante ocupado entre esos 2)

2.- Si, de hecho esta aclarado en el enunciado, así que no te preocupes:
> Por un tema de simplicidad en el enunciado de las pruebas, a las patotas se las va a nombrar por el nombre del archivo de tareas que deban realizar.

3.- Si, es el mismo comando 😄 

4.- Si, es como esta en el enunciado, simplemente lo agregamos como reminder en el enunciado de las pruebas

5.- Por eso en la prueba pedimos que los 2 tripulantes no sean aledaños (A1 y A3), para contemplar estos casos donde hicieron laburo de mas 😉 

6.- Error de tipeo nomas después lo fixeamos.

7.- Hermosa pregunta: Las esperas activas y los leaks se controlan con htop y se verifica que el consumo de memoria no crezca indefinidamente (puede aumentar pero tiene que disminuir en consecuencia) o que el uso de CPU sea racional (una cpu al 100% constantemente es una señal muy muy clara de espera activa).

Saludos.-

**Comment by eguiggiaro** [comment]
Gracias!! Clarísimo.
