### ISSUE TITLE
Errores: recipe for target "XXXX" failed & make:*** [XXXXX] Error 1 al buildear el proyecto

### ISSUE THREAD

**Issue by matiasrizzatobusta** [sisoputnfrba/foro#2211]
Cuando hacemos un build del tp nos saltan los siguientes 2 errores:
make: *** [src/planificacion/planificaion.o] Error 1
recipe for target 'src/planificacion/planificaion.o' failed

y no sabemos como solucionarlos.Cuando consultamos por discord nos dijeron que ese tipo de errores se iban a solucionar cuando terminemos de corregir los otros errores que teniamos pero no fue el caso y no sabemos como hacer para arreglarlo y que compile

### 🔎 Búsqueda en foros
encontre en google pero no logro solucionar el proplema

### 🐛 Cómo reproducir el error
buildear el tp

### 💻 Logs
Errors:
make: *** [src/planificacion/planificaion.o] Error 1
recipe for target 'src/planificacion/planificaion.o' failed

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Es posible que tengas algunos errores o mas texto en la consola antes de ese último? porque ahi lo único que te dice es que no puede compilar el archivo discordiador.o.

Si podes tirar el make en una consola te va a ser mas facil hacer copy-paste del output.

Saludos.-

**Comment by iago64** [comment]
@matiasrizzatobusta pudieron solucionar el problema? siguen trabados? hay algo con lo que podamos ayudar?

**Comment by facundocarrizo99** [comment]
Si, lo pudimos resolver. El probelma era que no teniamos creadas las librerias compartidas correctamente, entonces no podiamos importar las mismas. Entonces nunca compilaba, por lo tanto nos tiraba ese error. 
Para aclarar por las dudas, ese era el unico error que nos tiraba la consola. 
Muchas gracias por la ayuda.

**Comment by karengrams** [comment]
¡Buenas @facundocarrizo99! ¿Podemos cerrar este issue? ¡Saludos!
