### ISSUE TITLE
Error en inclusión de biblioteca propia en los módulos

### ISSUE THREAD

**Issue by ailengonzalezperez** [sisoputnfrba/foro#2212]
Hola! Tenemos un tema con la compilación de los módulos en las VM que usaremos el día de la entrega.
Estuvimos investigando y creemos que puede ser un tema de rutas pero no encontramos cómo corregirlo ni la combinación que haga que funcione.
Dejo a continuación los pasos y porciones de código y, en caso que se necesite más, lo sumamos (no quisimos mandarnos de una con el código completo). 

El primer paso es ejecutar un archivo .sh que se encarga de bajar e instalar las bibliotecas, así como también setear la variable LIBRARY_PATH. En particular para nuestra biblioteca hace esto: 

```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/tp-2021-1c-MAGI/magi-library/Debug
sleep 1
cd magi-library/Debug
echo Paso 5: Compilación de la magi-library
sleep 1
make clean
make all
sleep 1
sudo cp libmagi-library.so /usr/lib
```

Luego de eso, ya tenemos magi-library.so en la carpeta debug. Hasta acá todo perfecto, compila bien.

```
Paso 7: Compilación de la magi-library
rm -rf  ./magi-library.o  ./magi-library.d  libmagi-library.so

Building file: ../magi-library.c
Invoking: GCC C Compiler
gcc -Icommons -Ireadline -Ipthread -O0 -g3 -Wall -c -fmessage-length=0 -fPIC -MMD -MP -MF"magi-library.d" -MT"magi-library.o" -o "magi-library.o" "../magi-library.c"

Finished building: ../magi-library.c

Building target: libmagi-library.so
Invoking: GCC C++ Linker
g++ -shared -o "libmagi-library.so"  ./magi-library.o
Finished building target: libmagi-library.so
```

Cuando queremos ejecutar el segundo .sh que compila los proyectos carpeta a carpeta, empezamos a obtener este error (pongo solo el de imongo pero pasa en todos los módulos igual):

```
utnso@fila-01-vm-01:~/tp-2021-1c-MAGI$ bash compilador.sh
Compilando: I-Mongo-Store
rm -rf  ./comunicacion.o ./hash.o ./i-mongo-store.o ./lectorMetadata.o ./operacionesFS.o ./preparacion-ims.o ./sabotaje.o  ./comunicacion.d ./hash.d ./i-mongo-store.d ./lectorMetadata.d ./operacionesFS.d ./preparacion-ims.d ./sabotaje.d  i-mongo-store

Building file: ../comunicacion.c
Invoking: GCC C Compiler
gcc -I"~/tp-2021-1c-MAGI/magi-library/Debug" -Imagi-library -Icommons -Ireadline -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"comunicacion.d" -MT"comunicacion.o" -o "comunicacion.o" "../comunicacion.c"
In file included from ../sabotaje.h:3:0,
                 from ../comunicacion.h:12,
                 from ../comunicacion.c:7:
../i-mongo-store.h:23:25: fatal error: magi-library.h: No such file or directory compilation terminated.
subdir.mk:36: recipe for target 'comunicacion.o' failed
make: *** [comunicacion.o] Error 1
```
Para hacer la compilación, nosotros cargamos al repo nuestros archivos makefile, sources.mk, subdir.mk y objects.mk tal cual lo teníamos en la VM con entorno gráfico y como nos lo arrojó eclipse. Ahí nos dimos cuenta que, probablemente, tuviera que ver con rutas porque en la VM teníamos por ejemplo "/home/utnso/workspace/tp..." y acá pusimos todo en la carpeta inicial. Por lo tanto, ajustamos los archivos como creeríamos que tienen que quedar pero no hubo caso.

Dejo cómo los pusimos (además probamos variantes con y sin ~ adelante pero nada lo arregla).

**Archivo makefile**

```
# All Target
all: i-mongo-store

dependents:
	-cd ~/tp-2021-1c-MAGI/magi-library/Debug && $(MAKE) clean all

# Tool invocations
i-mongo-store: $(OBJS) $(USER_OBJS) ~/tp-2021-1c-MAGI/magi-library/Debug/libmagi-library.so
	@echo 'Building target: $@'
	@echo 'Invoking: GCC C Linker'
	gcc -L"~/tp-2021-1c-MAGI/magi-library/Debug" -o "i-mongo-store" $(OBJS) $(USER_OBJS) $(LIBS)
	@echo 'Finished building target: $@'
	@echo ' '

# Other Targets
clean:
	-$(RM) $(EXECUTABLES)$(OBJS)$(C_DEPS) i-mongo-store
	-@echo ' '

.PHONY: all clean dependents
~/tp-2021-1c-MAGI/magi-library/Debug/libmagi-library.so:

-include ../makefile.targets
```

**Archivo subdir.mk**

```# Each subdirectory must supply rules for building sources it contributes
%.o: ../%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -I"~/tp-2021-1c-MAGI/magi-library/Debug" -Imagi-library -Icommons -Ireadline -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' ''
```

¿Podrían ayudarnos a encontrar qué sucede?
Gracias! Grupo MAGI.

**Comment by iago64** [comment]
Buenas! Cómo va?

Antes que nada, gracias por el detalle del error 😄 

Respecto al error, el problema que estan teniendo es que uds estan haciendo el export adentro del .sh, entonces lo que pasa es que al terminar de correr el .sh ese export desaparece y no tienen referencia de las libs, de hecho si hacen `echo $LD_LIBRARY_PATH` se van a encontrar que no tienen nada del export que hicieron en el primer sh, la forma de solventar eso es simplemente haciendo el export antes 😃 

_Explicación express_: Esto pasa porque al momento de ejecutar un script en cualquier shell (bash, zsh, fish, etc) lo que termina pasando es que estos programas hacen un `fork()` de si mismos y después un `execv()` para reemplazar su código con el programa que les pedimos que ejecuten, entonces como en su caso es bash nuevamente, el export queda dentro de ese segundo bash.

Cualquier cosa si la solución no se corrigió avisen y lo vemos mas en detalle.
Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Para sumar a lo que dijo Dami, cada vez que se inicializa cualquier consola bash se ejecuta primero un script que pueden encontrar en el path `~/.bashrc`, así que una buena forma de "hacer el export antes" es agregarlo al final del mismo 😉 

Saludos

**Comment by ailengonzalezperez** [comment]
Hola!
Cambiando lo del export afuera del .sh y cambiando un detalle de las rutas que nos estaba faltando al clonar, se solucionó.
Muchas gracias a ambos! 😄😄
