### ISSUE TITLE
Planificacion en Discordiador - Semaforos

### ISSUE THREAD

**Issue by federiver91** [sisoputnfrba/foro#2213]
Bueno, básicamente la duda es que **no tengo idea como implementar los semáforos para hacer la planificación** de los hilos y toda la gestión que se debe hacer cuando se inicia o se pausa la misma.

**No soy desarollador.**

Estaría bueno tener un video, un taller, o un ejemplo de tps anteriores para el uso de semáforos porque es el núcleo del proceso Discordiador y no tengo idea cómo implementarlo.

Casi tenemos todas las funciones de creación de estructuras, solicitud de tareas por parte de los tripulantes y demás.. Pero bueno, a la hora de ejecutarlas de manera ordenada con la sincronización estamos pelados.

Gracias,
Federico

**Comment by iago64** [comment]
Federico, cómo va?

Si tu problema es que no sabes como incluir la biblioteca para utilizar los semáforos, esta disponible en el [canal de youtube](https://www.youtube.com/channel/UCPv858YLpdTylSrxsLM4DJA) una [charla que dio Mauro](https://www.youtube.com/watch?v=G8PD6wauMeY&ab_channel=UTNSO) hace unos años en el aula magna donde cuenta un poco como crear hilos y como usar los semáforos.

Ahora si tu problema es que no estas pudiendo encontrar en tu código donde van los semáforos, te recomiendo que repases el tema de sincronización como lo vieron en la teoría y trates de hacer el paralelismo de los ejercicios que vieron en clase con lo que tenes que poner en tu código.

Por último, no entiendo a que viene tu frase de **No soy desarrollador** ya que así como vos no sos dev, tenes compañeros que no trabajan, otros que trabajan como funcionales, infraestructura, DevOps, Analistas de BI, etc y aun así todos se toman el tiempo de buscar las cosas, investigar y plantear dudas del estilo: _Encontré esto o pensé que esto podía resolverse así y no se si esta bien_ y no están pidiéndonos que les resolvamos el problema. 
No te olvides que la carrera es Ingeniería en Sistemas, el perfil al que apunta el graduado en algún momento de su vida sea líder de equipo, jefe, gerente, director, etc y ahí vas a tener que tomar decisiones basándote en tus conocimientos previos, en tu experiencia o en tu capacidad de investigar y resolver problemas y vas a tener que lidiar con problemas que están fuera de tus conocimientos y eso conlleva desde decidir si un proyecto es viable o no hasta tener que ponerte a codear porque el proyecto esta atrasado y te estas jugando el laburo y ahí salir con un **Yo no hago esto** no va a ser una opción viable porque el cliente va a querer resultados.

Saludos.-

**Comment by federiver91** [comment]
OK, gracias por la info!

Saludos.
