### ISSUE TITLE
[Mi-RAM] Inicialización diferente - Consulta

### ISSUE THREAD

**Issue by Cande175** [sisoputnfrba/foro#2214]
**DATOS**

PAG_PatotaA.txt: 8 bytes de patota + 30 bytes tareas + 21 bytes tripulante = 59 bytes (1 página entera y 27 bytes de otra)
PAG_PatotaB.txt: 8 bytes de patota + 30 bytes tareas + 21 bytes tripulante = 59 bytes (1 página entera y 27 bytes de otra)
PAG_PatotaC.txt: 8 bytes de patota + 90 bytes tareas + 21 bytes tripulante = 119 bytes (3 páginas enteras y 23 bytes de otra)

Tenemos sólo 4 páginas en MP

**En nuestra implementación CLOCK:**
- Iniciamos Patota A en MP
- Agregamos Patota A a cola de NEW (no hay swapping pues está en MP)
- Iniciamos Patota B en MP
- Agregamos Patota B a cola de NEW (no hay swapping pues está en MP)
- Iniciamos Patota C en MV (No entra en MP)
- Agregamos Patota C a cola de NEW. Hay swapping pues está en MV. Tenemos que traer el TCB a MP, así que haríamos swapping de la cuarta página de la patota. Intercambiamos el frame 0 de MP (que tiene patota A). El clock queda: FRAME 0 bit de uso 1 y FRAME 1,2,3 con bit de uso 0
- Agregamos Patota A a cola de READY (no hay swapping pues está en MP). El clock queda: FRAME 0,1 bit de uso 1 y FRAME 2,3 con bit de uso 0
- Agregamos Patota A a cola de EXEC (no hay swapping pues está en MP)
- Agregamos Patota B a cola de READY (no hay swapping pues está en MP) El clock queda: FRAME 0,1,3 bit de uso 1 y FRAME 2 con bit de uso 0
- Patota A pide tarea (Hay swapping pues está en MP). Tenemos que traer la primer página que contiene la tarea a MP, así que haríamos swapping de la primer página de la patota. Intercambiamos el frame 2 de MP (que tiene patota B). El clock queda: FRAME 0,2,3 con bit de uso 1 y FRAME 1 con bit de uso 0.
- Agregamos Patota C a cola de READY (no hay swapping pues está en MP). El clock queda: FRAME 0,2,3 con bit de uso 1 y FRAME 1 con bit de uso 0.

**Resultados obtenidos:** 
- MP Tiene:
--- frame 0 = Pagina 4 del proceso C
--- frame 1 = Pagina 1 del proceso A
--- frame 2 = Pagina 0 del proceso A
--- frame 3 = Pagina 1 del proceso B

**Resultados esperados según las pruebas**
- MP tiene todas las páginas del proceso C

Nuestra inicialización la hicimos según esta instrucción https://github.com/sisoputnfrba/foro/issues/2162#issuecomment-865466903 y el swapping (no swappeamos toda la imágen, sino solo el TCB) según esta: https://github.com/sisoputnfrba/foro/issues/2183#issuecomment-869229074

No se si me perdí de algo, o qué tan flexibles son con las pruebas, pero cualquier dato ayuda jaja. Gracias!

**Comment by Cande175** [comment]
**Nota** Con LRU daria lo mismo.

- Iniciamos Patota A en MP
- Agregamos Patota A a cola de NEW (no hay swapping pues está en MP) LRU: 0, 1
- Iniciamos Patota B en MP
- Agregamos Patota B a cola de NEW (no hay swapping pues está en MP) LRU: 0, 1, 2, 3
- Iniciamos Patota C en MV (No entra en MP)
- Agregamos Patota C a cola de NEW. Hay swapping pues está en MV. Tenemos que traer el TCB a MP, así que haríamos swapping de la cuarta página de la patota. Intercambiamos el frame 0 de MP (que tiene patota A). LRU: 1, 2, 3 ,0
- Agregamos Patota A a cola de READY (no hay swapping pues está en MP). LRU: 2, 3, 0, 1
- Agregamos Patota A a cola de EXEC (no hay swapping pues está en MP)
- Agregamos Patota B a cola de READY (no hay swapping pues está en MP) LRU: 2, 0, 1, 3
- Patota A pide tarea (Hay swapping pues está en MP). Tenemos que traer la primer página que contiene la tarea a MP, así que haríamos swapping de la primer página de la patota. Intercambiamos el frame 2 de MP (que tiene patota B). LRU: 0, 1, 3, 2
- Agregamos Patota C a cola de READY (no hay swapping pues está en MP). LRU: 1, 3, 2, 0

**Resultados obtenidos:**

MP Tiene:
--- frame 0 = Pagina 4 del proceso C
--- frame 1 = Pagina 1 del proceso A
--- frame 2 = Pagina 0 del proceso A
--- frame 3 = Pagina 1 del proceso B

**Resultados esperados según las pruebas**

MP tiene todas las páginas del proceso C

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Creo que en el tema de la implementación metieron un toque la pata y de ahi viene el tema de la diferencia en los resultados, ya lo que quiso decir Nico en el issue #2162 es que a diferencia de la teoría, donde uds cargan todo en swap y después traen a memoria principal a medida que necesitan, en el TP uds primero tienen que cargar en memoria principal y cuando se llena empiezan a mandar cosas que tenían en memoria principal a swap para hacer lugar a lo nuevo que necesitan cargar.
Acá no se trata tanto de que tan flexibles somos con las pruebas, si no que básicamente parten de una base distinta porque el enunciado dice marrón y uds implementaron naranja, ambos comparten la misma base (memoria principal y swap), pero derivan para lados distintos (como cargan las cosas).

Saludos.-

**Comment by Cande175** [comment]
Okey, yo pensaba que tenían que ser sí o sí esos resultados. Pero como dijiste marrón y naranja en vez de blanco y negro asumo que no está tan mal 🤣
Igualmente no me quiero arriesgar a modificar el core para mañana cuando está funcionando bien actualmente y tenemos que ver otras cosas aún. Cualquier cosa imagino que podremos charlar bien en la entrega.

Muchas gracias una vez más :)
