### ISSUE TITLE
Duda Planificador y menos tripulantes que el grado de multiprocesamiento

### ISSUE THREAD

**Issue by SantiagoOrlando29** [sisoputnfrba/foro#2215]
Buenas
Ahora estudiando para el recu del primer parcial me surgió una duda muy chiquita y específica. 
Con el planificador RR, supongamos que queda solo 1 tripulante ejecutando y el resto ya terminó de ejecutar y no hay nadie en Ready. Tengo que hacer que cuando se le cumple el quantum vaya a Ready, para luego volver a Exec casi inmediatamente? O puedo hacer que ya que no hay nadie más en Ready, ni salga de Exec por fin de quantum y ejecute tranquilo?

Saludos!

**Comment by iago64** [comment]
Buenas ¿Cómo va?

Hermosa la duda teórica 😃 
En el caso del TP, deberían tener el cambio de estado, porque el algoritmo no distingue si tiene o no algo en ready, primero desaloja y después busca en la cola de ready y va a levantar al único que tenes que es el que acabas de desalojar. 
En los ejercicios no siempre se ve porque no siempre se tiene en cuenta el tiempo de ejecución del sistema operativo.

Saludos.-

**Comment by SantiagoOrlando29** [comment]
Perfecto. Muchas gracias!!!
