### ISSUE TITLE
Pasar struct con puntero por parametro a funcion definida en otro c file

### ISSUE THREAD

**Issue by federiver91** [sisoputnfrba/foro#2216]
Buenas, como dice el título, estoy queriendo pasar por parámetro una tarea (definida como struct), la cual tiene un char*, en una función definida en otro archivo c distinto al de donde estoy invocando la función.

Sospecho que no está pudiendo acceder a esa porción de memoria. Cómo puedo resolverlo? 

Van los extractos del código.

1.- En `/tp-2021-1c-SisOpado/miRamHQ/miRamHQ.c` tengo esto:
```C
// Logger
logger = log_create("../logs/miRamHQ.log", "MI_RAM_HQ", true, LOG_LEVEL_INFO);
loggear_tarea(logger, tarea);
```

2.- La variable "tarea" es un struct definido en `/home/utnso/tp-2021-1c-SisOpado/shared/include/estructuras.h`

```C
typedef struct{	
    char* descripcion;
    uint32_t parametros;
    uint32_t posicion_x;
    uint32_t posicion_y;
    uint32_t tiempo;	
} t_tarea;
```

3.- Y la función loggear_tarea está definida en `/home/utnso/tp-2021-1c-SisOpado/shared/src/shared_utils.c`

```C
void loggear_tarea(t_log* un_logger, t_tarea* una_tarea){
	log_info(un_logger, "Descripcion: %s", una_tarea->descripcion);
    ...

```

Cuando debuggeo la función loggear_tarea veo que se pasan todos los atributos del struct t_tarea EXCEPTO el char* descripcion. Con lo cual, me hace pensar que al tratarse de un puntero, no está pudiendo acceder a esa dirección de memoria por tratarse de otro archivo distinto al de donde se definió la variable "tarea" pasada como argumento.

Lo flashero es que algunas veces anduvo y pudo acceder y logear la variable correcta, pero sospecho que fue por una circunstancia no determinística. 

Cómo hago para resolver esto?? Gracias!

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Antes que nada, espero no te joda que acomode un poco el markdown del issue como para que sea mas simple de leer (el formateo de github es bastante rebuscado hasta que le agarras la mano)

Respecto a tu pregunta, si algunas veces falla y otras no, en las que falla, te tira segment fault o simplemente imprime cualquier cosa? Porque lo que puede ser que te este pasando es que al momento de guardar el texto en lugar de estar reservando la memoria y pasándole un puntero a la dirección de memoria, estés guardando ahí derecho el string (y por consecuencia pisando memoria de otras variables).
Otra cosa que se me ocurre que puede ser, al momento de obtener esta tarea, estas teniendo en cuenta de si usas `strlen()` para calcular el tamaño sumarle 1 byte por el '\0'?
Por último si estas usando la [biblioteca de strings de las commons](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/string.h), tenes una funcion que es `string_duplicate()` que a partir de 1 string modelo te genera una copia y te devuelve el puntero a la dirección de memoria sin que tengas que complicarte reservándola vos 😉 

Saludos.-

**Comment by federiver91** [comment]
Amplío un poco más el código de miRamHQ.c 

int desc_size = strlen(descripcion);
tarea->descripcion = malloc(desc_size + 1);
memcpy(tarea->descripcion, descripcion, desc_size + 1);
loggear_tarea(logger, tarea);

Ya te digo... Cuando hago el debuggeo, dentro de miRamHQ.c la estructura "tarea" tiene todos los datos correctos e impacables... Pero cuando viaja en esa función loggear_tarea no recibe bien ese string de tarea->descripción.
![image](https://user-images.githubusercontent.com/49326422/125883055-0befdf06-0b26-47ef-8991-1f86ebcb90f5.png)


Y ahora que te quiero responder y lo debuggeo resulta que me funciona, insólito
![image](https://user-images.githubusercontent.com/49326422/125883394-6c6cac62-10ef-47a0-869e-4c02c7cf856b.png)


Pero ahí a la izquierda, donde dice "GENERAR OXIGENO" decía algo asi como Cannot access memory... bla bla...

**Comment by RaniAgus** [comment]
¡Buenas! Sinceramente no veo ningún problema en esta parte del código, el string parece copiarse bien.

En cuanto al hecho de que sean archivos distintos, no te preocupes ya que el compilador por detrás junta todos los archivos .c como si estuvieran en uno solo antes de realizar la compilación, así que en caso de que falte la definición de alguna función te aparecería un warning diciendo: 
```
implicit declaration of loggear_tarea()
```
y debería fallar siempre.

Retomando la pregunta de Dami: ¿falla imprimiendo cualquier cosa o con segmentation fault?

Una posibilidad es que otro hilo que se esté ejecutando en paralelo tenga memoria asignada justo antes del string y lo esté pisando. Para chequear que esto no ocurra te recomiendo correr el programa con Valgrind, una herramienta que sirve para diagnosticar errores de manejo de memoria (pasarnos del límite, leer una variable sin haberla inicializado, no hacer `free()` de memoria reservada con `malloc()`, etc). Te dejo links a la guía y a una charla sobre su uso:
- Guía: https://faq.utnso.com.ar/guia-valgrind
- Charla:  https://www.youtube.com/watch?v=knRei6OBU4Q

También en el video de la charla se menciona a Helgrind, que es una herramienta de Valgrind para chequear posibles condiciones de carrera, por ejemplo, al tener dos hilos queriendo acceder a una misma variable global sin ningún semáforo mutex.

Espero que sirva de ayuda,
Saludos

**Comment by federiver91** [comment]
Buenas!

Por ahora no me volvió a tirar el error (que no era Segmentation Fault). 

Gracias por la info, voy a investigar un poco. Si se vuelve a presentar abro otro thread. Este lo cierro. 

Saludos
