### ISSUE TITLE
[Casos de pruebas] Espera activa, memory leaks y VM

### ISSUE THREAD

**Issue by matiasfdevecchi** [sisoputnfrba/foro#2217]
Buenas, quería consultarles un par de cosas sobre los casos de pruebas

1. Como van a fijarse los memory leaks y esperas activas? Para poder replicarlo y analizar nuestro código. Ya que el doc no especifica como, si con valgrind o algun otro

2. Con respecto a la VM, por qué tendríamos que solicitar una VM a ustedes para probar? Usar la que aparece como Ubuntu Server localmente no sirve?

Gracias, saludos!

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Respecto a como controlamos las esperas activas y los memory leaks, simplemente con el comando `htop` que es similar al task manager de windows, linux o mac pero que corre en la terminal. La idea es ver, el uso de CPU (que no sea excesivo) y en el caso de los memory leaks simplemente que la memoria no empiece a ocuparse indefinidamente (es decir, si por momentos aumenta el consumo pero despues se libera no hay drama)

Por la parte de las VMs, en el momento de la entrega les vamos a dar 3 vms completamente limpias tal cual viene la ubuntu server que esta en la página. La idea es que cada prueba corra en un ambiente completamente limpio y aislado (por eso las maquinas van a estar en una red privada)

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Para sumar a lo que dijo Dami, el hecho de que nosotros en las pruebas revisemos con `htop` no anula que ustedes puedan chequearlo con Valgrind para así estar seguros de que no están leakeando memoria, de hecho, se los súper recomiendo.

También, si bien lo ideal es contar con las VMs, si se las llegamos a quitar por mucha demanda pueden usar ngrok en la VM Ubuntu Server: https://www.youtube.com/watch?v=vFkmdQVn4Ug
Para esto les aconsejo haber redirigido los puertos de la VM para conectarse por ssh, para así poder aprovechar, por ejemplo, el portapapeles: https://www.youtube.com/watch?v=SDeqYSxFd10

Saludos

**Comment by karengrams** [comment]
¡Buenas @matiasfdevecchi! ¿Podemos cerrar este issue? ¡Saludos!

**Comment by iago64** [comment]
Cerramos por inactividad, cualquier cosa lo pueden reabrir 😄
