### ISSUE TITLE
Mapeo de bloques a memoria

### ISSUE THREAD

**Issue by nicolascalle** [sisoputnfrba/foro#2218]
Buenas, estoy teniendo un problema con el tamaño de los bloques de mi filesystem. Reduje el codigo a lo minimo posible para replicar el problema que tengo en el tp y para que sea mas sencillo de leer.  

### 📝 Código relevante

```
int main(int argc, char ** argv){
    mkdir("/home/utnso/imongoFS", 0700);
    char* PATH_BLOCKS = "/home/utnso/imongoFS/Blocks.ims";

    uint32_t BLOQUES = 240;
    uint32_t TAMANIO_BLOQUE = 32;
    uint32_t TAMANIO_DISCO = BLOQUES * TAMANIO_BLOQUE;

    typedef struct{
        char* bytes;
    } t_block;

    char* command = string_from_format("dd if=/dev/urandom of=%s bs=%lu count=1", PATH_BLOCKS, TAMANIO_DISCO);
    system(command);
    free(command);

    int fd_blocks = open(PATH_BLOCKS, O_RDWR);

    t_block** blocks = (t_block**) malloc(sizeof(t_block)*BLOQUES );
    for(int i = 0; i < BLOQUES; i++){
        blocks[i] = (t_block*) malloc(sizeof(t_block));
        blocks[i]->bytes = (char*)mmap(0, TAMANIO_BLOQUE, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_SHARED, fd_blocks, i * TAMANIO_BLOQUE);
    }
}
```
### 🐛 Cómo reproducir el error

Con tamaño de bloque de 4096 bytes o superior logro mapear los bloques correctamente a memoria.
Con tamaño inferior a 4096 bytes se mapea correctamente el bloque 0, pero en los siguientes bloques falla el mapeo. A contunuacion se observa en el debugger.

### 💻 Logs

blocks[0]->bytes: 0x7fd5000 "252J\016@<DWYE\227\371\214|*\223i!\362\310[k}qE6\... etc"  => lee contenido basura, lo cual es correcto

blocks[1]->bytes: 0xffffffff <error: Cannot access memory at address 0xffffffff>  =>he aqui el problema

blocks[2]->bytes: 0xffffffff <error: Cannot access memory at address 0xffffffff>  =>he aqui el problema

El tamaño de bloque usado para esta prueba fue de 32 bytes, y con tamaños menores a 4096 el resultado es el mismo.

**Comment by RaniAgus** [comment]
¡Buenas! Leyendo la docu de mmap (https://man7.org/linux/man-pages/man2/mmap.2.html) nos dice lo siguiente sobre el último parámetro:
> The contents of a file mapping (as opposed to an anonymous
       mapping; see MAP_ANONYMOUS below), are initialized using length
       bytes starting at offset offset in the file (or other object)
       referred to by the file descriptor fd.  **offset must be a multiple
       of the page size as returned by sysconf(_SC_PAGE_SIZE).**

Es decir que el offset debe ser un múltiplo del tamaño de página de la memoria real (el cual se puede obtener haciendo `sysconf(_SC_PAGE_SIZE);`), por lo que no se puede usar como "offset" para mapear cada pedacito del archivo por separado.

Lo bueno que tiene `mmap()` es que, al trabajar al contenido del archivo de la misma forma que se haría con cualquier porción de memoria, podés hacer un único mapeo que contenga todos los bloques y luego hacer que cada `block->bytes` apunte al principio de cada uno calculando el offset mediante aritmética de punteros 😄  

Saludos

**Comment by nicolascalle** [comment]
En principio habia descartado esa posibilidad porque si mi disco llegaba a tener una capacidad muy alta (1TB por ejemplo), no iba a poder mapear todos los bloques. Pero viendo los datos de pruebas el tamaño maximo de filesystem es 8mb, con lo cual no habria problema. Gracias, saludos
