### ISSUE TITLE
Duda Iniciar_planificacion

### ISSUE THREAD

**Issue by SantiagoOrlando29** [sisoputnfrba/foro#2219]
Buen día!
Antes que nada pido disculpas porque se que este tema se ha hablado mucho. Sin embargo estoy MUY confundido con el tema de Iniciar planificación.
Ahora viendo los tests veo que después de Iniciar patota hacen siempre el Iniciar planificación. Yo leyendo issues y yendo a soporte había entendido que eso no era necesario, que podía iniciar patota e iban a comenzar a ejecutar tranquilamente sin el Iniciar planificación. Ya estoy perdidísimo jajaj.
Entonces que tengo que hacer? :
A. iniciar patota y luego Iniciar planificación si o si, sino no empiezan a ejecutar.
B. iniciar patota y no es necesario el Iniciar planificación.

Y en caso de que sea la A, los tripulantes tienen que quedar "trabados" en Ready o en New hasta que haga el Iniciar planificación?

Gracias
Saludos!

**Comment by ncoen97** [comment]
Buenas, la opción correcta es la A. Cuando se inician los tripulantes deberían quedar en new ya que al estar pausada la planificación no debería haber cambios entre colas. Saludos!

**Comment by SantiagoOrlando29** [comment]
Genial. Graciass!
