### ISSUE TITLE
MiRam-Discordiador: Servidor acepta conexion y luego recibe peticiones

### ISSUE THREAD

**Issue by federiver91** [sisoputnfrba/foro#2220]
Buenas!

Ya van varias horas que paso tratando de investigar cómo implementar el servidor del lado de la Memoria para que se conecten los tripulantes.

El tema de levantar el Servidor y que se conecte el Discordiador para Iniciar la patota ya está resuelto, como así también la primera conexión que hago desde cada Tripulante para darse a conocer frente a la Memoria y que esta cree las estructuras necesarias.

El problema lo tengo cuando quiero empezar a solicitar tareas a la Memoria desde cada Tripulante, reutilizando la conexión ya abierta. No lo puedo hacer porque desde la Memoria tengo un ciclo infinito que espera clientes con la función "ACCEPT" y no con RECV. La verdad que lo pienso y no se me ocurre como implementarlo.

Algún centro??

Copio el código que tengo en la función main de la Memoria:
![image](https://user-images.githubusercontent.com/49326422/125989555-67cb9d6b-bea0-42f3-aac5-6426c01612dc.png)

Copio la función "esperar_cliente"
![image](https://user-images.githubusercontent.com/49326422/125989649-1be32075-5e3b-4f95-a0ca-d5ccb49b89e1.png)

Entiendo yo que por ahí viene el error. Yo estoy queriendo, desde Tripulante, reutilizar una conexión abierta previamente y la memoria no lo está interpretando así.

Copio el código de Tripulante también, por las dudas.
Acá me conecto por primera vez con la Memoria para dar a conocer el tripulante
![image](https://user-images.githubusercontent.com/49326422/125989843-552a2842-1427-4ae9-8986-a345e63455a9.png)

Y acá estoy intentando reutilizar esa conexión para pedirle la próxima tarea
![image](https://user-images.githubusercontent.com/49326422/125989947-c41414ff-3d47-4530-b233-77869b11c27b.png)

La función la defino en el mismo archivo tripulante.c
![image](https://user-images.githubusercontent.com/49326422/125989993-6f41d557-5a4e-47c8-8174-e6acff8ae071.png)

Esa función solicitar_proxima_tarea termina invocando un "send" finalmente.

Espero que se entienda la consulta!

Gracias,
Federico

**Comment by RaniAgus** [comment]
️¡Buenas! Si nos pudieras pasar el código como texto sería un golazo porque de esa forma lo podría copiar y probar, pero a simple vista parece estar bien. Con markdown podés darle formato con color usando tres comillas invertidas arriba y abajo + una "c", así:

<img src="https://user-images.githubusercontent.com/39303639/125994157-e624b220-1b6c-46a7-a64b-dac602249a37.png" height="75">

```c
printf("¡Hola mundo!\n");
```

> El problema lo tengo cuando quiero empezar a solicitar tareas a la Memoria desde cada Tripulante, reutilizando la conexión ya abierta. No lo puedo hacer porque desde la Memoria tengo un ciclo infinito que espera clientes con la función "ACCEPT" y no con RECV.

No hay drama con eso, desde el lado del servidor siempre vas a tener un socket de escucha en un puerto (`server_fd`) y luego N sockets (`cliente_fd`) que esos sí están conectados al socket del cliente (`conexion_tripulante_con_memoria`). `accept()` siempre devuelve un _nuevo_ socket que no esté siendo utilizado.

Por cada socket que quieras hacer `send()` y/o `recv()`, sí o sí debe previamente estar conectado, ya sea mediante `connect()` desde el lado del cliente, o `accept()` desde el lado del servidor. El socket de escucha del servidor _no está conectado a ningún cliente_, sino que solo escucha posibles conexiones a un puerto (`bind()` y `listen()`).

Yo revisaría si la función `nueva_consulta()` después de cargar en memoria al tripulante conectado se queda esperando a recibir futuros mensajes o no.

Saludos

**Comment by federiver91** [comment]
Mmmm, el tema es que la Memoria genera un hilo nuevo por cada consulta que recibe (dicho sea de paso te pregunto donde hacer el pthread_join. Sería después del "i++" dentro del while(1)??

El código de la función "nueva_consulta" es este:

```c
void nueva_consulta(int cliente_fd){
    op_code cod_op = recibir_codigo_operacion(cliente_fd);
    
    t_buffer* buffer = recibir_buffer(cliente_fd);

    switch (cod_op)
    {
        case INICIAR_PATOTA:;
            t_patota* patota = deserializar_patota(buffer);

            tareas_para_pruebas = parsear_listado_tareas(patota->listado_tareas);
            
            guardar_patota(patota);
            //TODO: Responder al Discordiador con OK o ERROR (1 o 0) para que sepa si avanza con la creación de tripulantes o no
            enviar_respuesta_patota(cliente_fd, 1);
            break;
        case INICIAR_TRIPULANTE:;
            t_tripulante *tripulante = deserializar_tripulante(buffer);
            iniciar_tripulante(tripulante);
            break;
        case UBICACION_TRIPULANTE:;
            t_posicion_tripulante *posicion_tripulante = deserializar_ubicacion_tripulante(buffer);
            actualizar_ubicacion_tripulante(posicion_tripulante);
            break;
        case PROXIMA_TAREA:;
            uint32_t id_tripulante_solicitante = deserializar_id_tripulante(buffer);
            t_tarea *tarea = obtener_proxima_tarea(id_tripulante_solicitante);
            enviar_proxima_tarea_tripulante(cliente_fd, tarea);
            break;
        case EXPULSAR_TRIPULANTE:;
            uint32_t id_tripulante_a_expulsar = deserializar_id_tripulante(buffer);
            expulsar_tripulante(id_tripulante_a_expulsar);
            break;
        case -1:
            log_error(logger, "el cliente se desconecto. Terminando servidor");
            return EXIT_FAILURE;
        default:
            log_warning(logger, "Operacion desconocida. No quieras meter la pata");
            break;
    }
}
```

**Comment by federiver91** [comment]
Estuve viendo de nuevo los videos del canal de Youtube de la catedra y capaz que podría servirme la función select desde el lado de la Memoria, no? 

Hay algún ejemplo o me podrán tirar algún centro de cómo aplicarlo en este caso? Si aplicase...

**Comment by iago64** [comment]
Buenas ¿Cómo va?

Vamos en orden porque creo que se esta armando un nudo bastante grande.

1.- Conexiones que se quedan esperando, el problema que tenes ahí de que se te traba en el `esperar_cliente` es porque estas llamando a la función `accept()` y esta función lo que hace es bloquear tu programa hasta que alguien haga `connect()` del otro lado, con lo cual, ahi tu problema es que tu tripulante no se esta volviendo a conectar. Si lo que hace el tripulante es mandar un mensaje con `send()` lo que vos tenes que hacer es esperar ese mensaje con `recv()`

2.- pthread_join, aca tenes la opción de hacerle join en algún lugar del hilo que lo crea, pero vas a tener el problema de que tu programa se va a bloquear ahí esperando a que termine el hilo, o podes hacer un `pthread_detach()` y dejar que cuando termine la funcion del hilo, este finalice y ya.

3.- `select()` escapale a esa solución, ya que `select()` lo que te permite es atender a varios clientes al mismo tiempo, que es lo mismo que haces con los hilos, pero de una forma mucho menos performante ya que con `select()` vos atendés de a 1 y en el enunciado les pedimos explícitamente que sea un servidor multihilo y que atienda a los clientes de manera concurrente.

Saludos.-

**Comment by federiver91** [comment]
Gracias Damián!

Respecto al punto 1, me confirmás que falla por lo que yo pensaba. Desde Memoria me quedo esperando un connect ya que llama accept y no recv.

Me podrán dar una mano con la implementación, en mi código de la Memoria para usar accept cuando es la primera vez y recv cuando la conexión ya está creada? Siendo que la solución tiene que ser polimórfica ya sea una consulta (primera o siguientes) de un Tripulante, o alguna del Discordiador, etc...

Lo pensé varias horas y no se me ocurre. Algún ejemplo que haya dando vueltas y me pueda servir? 

Gracias y saludos!

**Comment by iago64** [comment]
Fede, ¿Cómo va?

Un buen ejemplo que ya esta bastante completito es el [TP0](https://github.com/sisoputnfrba/tp0) donde tenes por cada resolución un branch, la que mas te puede servir es la solución 3 que es de donde la mayoría de los grupos termina tomando el código para hacer sus conexiones (y por lo que veo en el caso de tu grupo con la funcion `esperar_cliente()` también paso 😄)

Cualquier cosa si no te termina de aclarar las cosas, fijate de correr un poco el Tp0 y con el enunciado que esta linkeado en el repo y sumándole el video de la [Charla de Sockets de 2019](https://www.youtube.com/watch?v=V0KFn9w62sY&ab_channel=UTNSO), seguramente termines de tener el panorama completo.

Saludos.-

**Comment by federiver91** [comment]
Buenas,

No hay caso, no lo puedo hacer andar. No se por qué, desde el "servidor" no sigue iterando en el while(1) para atender una consulta sobre una conexión ya existente. Te copio el código de la función nueva_consulta corregido (es la función que ejecuta el hilo que se crea para atender una nueva conexión desde MiRam).

```c
void nueva_consulta(int cliente_fd){
    while(1){
        op_code cod_op = recibir_codigo_operacion(cliente_fd);
        
        t_buffer* buffer = recibir_buffer(cliente_fd);

        switch (cod_op)
        {
            case INICIAR_PATOTA:;
                t_patota* patota = deserializar_patota(buffer);

                tareas_para_pruebas = parsear_listado_tareas(patota->listado_tareas);
                
                guardar_patota(patota);
                //TODO: Responder al Discordiador con OK o ERROR (1 o 0) para que sepa si avanza con la creación de tripulantes o no
                enviar_respuesta_patota(cliente_fd, 1);
                break;
            case INICIAR_TRIPULANTE:;
                t_tripulante *tripulante = deserializar_tripulante(buffer);
                iniciar_tripulante(tripulante);
                break;
            case UBICACION_TRIPULANTE:;
                t_posicion_tripulante *posicion_tripulante = deserializar_ubicacion_tripulante(buffer);
                actualizar_ubicacion_tripulante(posicion_tripulante);
                break;
            case PROXIMA_TAREA:;
                uint32_t id_tripulante_solicitante = deserializar_id_tripulante(buffer);
                t_tarea *tarea = obtener_proxima_tarea(id_tripulante_solicitante);
                enviar_proxima_tarea_tripulante(cliente_fd, tarea);
                break;
            case EXPULSAR_TRIPULANTE:;
                uint32_t id_tripulante_a_expulsar = deserializar_id_tripulante(buffer);
                expulsar_tripulante(id_tripulante_a_expulsar);
                break;
            case -1:
                log_error(logger, "el cliente se desconecto. Terminando servidor");
                return EXIT_FAILURE;
            default:
                log_warning(logger, "Operacion desconocida. No quieras meter la pata");
                break;
        }
    }
}
```

Al debuggearlo, no me doy cuenta dónde falla porque no me marca bien el error. Solo se me frena y me aparece el cartelito este abajo a la derecha.
![image](https://user-images.githubusercontent.com/49326422/126079318-8df86b53-d4ab-45ea-bf27-050736ac5cb5.png)


Me conecto en la semana para verlo en "Soporte" de última.

**Comment by iago64** [comment]
Buenas!

Consulta, en cual de los 2 recibir se te queda? en el del código de operación o en el del buffer?
Por otro lado, el debug ahí lo que te dice es que no puede encontrar los fuentes de pthread_create(), por eso no te deja entrar a ver el código, si saltas de esa función deberías podes debuguear el resto de tus funciones.

Saludos.-

**Comment by federiver91** [comment]
Hola!

No lo estoy pudiendo ver dónde se queda. Yo le puse un breakpoint en la linea del "while(1)" pero ni siquiera entra a esa línea. Me tira ese error que te digo y como que se frena la ejecución del código y no puedo ver donde. 

Debería entrar de nuevo al while y entrar por el case de "PROXIMA_TAREA" porque desde el Tripulante la estoy solicitando inmediatamente despues de que se inicia. Pero no lo hace y se frena.

**Comment by iago64** [comment]
Buenas!

Si no esta frenandose en el breakpoint en la primer línea del while(1) me suena a que es porque no estas llamando a la función, por las dudas proba de poner un breakpoint justo antes de donde estas llamando a la función.

Saludos.-

**Comment by federiver91** [comment]
Ahí debuggeé del lado del "cliente" digamos. 

Se queda frenado en el "recv" de la función "recibir_buffer" que corre del lado del tripulante

```c
t_buffer* recibir_buffer(int cliente_fd){

	uint32_t size;
	recv(cliente_fd, &size, sizeof(uint32_t), MSG_WAITALL);
	void* stream = malloc(size);
	recv(cliente_fd, stream, size, MSG_WAITALL);

	t_buffer* buffer = malloc(sizeof(t_buffer));
	buffer->size = size;
	buffer->stream = malloc(size);
	memcpy(buffer->stream, stream, size);
	free(stream);
	return buffer;
}
```

**Comment by iago64** [comment]
Buenas!

Solo para entender un poco porque ya medio que me perdí, lo que te esta pasando es que el tripulante se bloquea y por lo tanto no le envía el mensaje a Mi-RAM?
Por otro lado, ese `recv()` del tripulante, que es lo que espera? quien debería mandarle algo?

Saludos.-

**Comment by federiver91** [comment]
Y mira... Como no me tira ningún error no se donde está fallando o dónde se bloquea.

Como son dos procesos distintos, me parece que no puedo debuggearlos juntos. 

Cuando debuggeo Mi-RAM, se me frena cuando intenta "esperar el cliente" que es lo primero que copié. Se frena ahí en el paso del "accept".

Y cuando debuggeo el proceso Discordiador (que es donde está el Tripulante que le envía el mensaje de PROXIMA TAREA), obviamente le envía correctamente el mensaje y despues se frena en ese "recibir_buffer" que adentro tiene el recv.

Volviendo al inicio de todo, sospecho que el problema lo tiene el servidor (MiRam en este caso) porque para mí está queriendo abrir una conexión nueva (usando accept) y en realidad el Tripulante le está solicitando la PROXIMA TAREA mediante la conexión ya existente que estableció cuando se inició. Con lo cual, creo que MiRam debería usar un send. 

Pero no se como llevarlo a la práctica como para probar que sea eso, digamos

**Comment by RaniAgus** [comment]
Si crees que el problema está en Mi-RAM, una posibilidad es armar en un proyectito aparte a modo de prueba que se conecte a Mi-RAM y envíe los dos mensajes con la información que vos esperás que se reciba. De esa forma, vas a estar más seguro de que la información se envía correctamente.

En cuanto al hecho de que sean dos procesos distintos, eso no te limita a poder debuggearlos juntos: se pueden abrir dos instancias de VSCode y debuggear en ellas.

**Comment by federiver91** [comment]
Buenas!

Ahí pude debuggear los dos procesos.

En MiRam aparentemente se está enviando todo ok. Me llama la atención que en Mi-Ram el fd del socket sea "16" y el del Discordiador sea "5". Eso está bien? No debería ser el mismo?

El que falla, finalmente, es el Tripulante cuando recibe el buffer. Se queda frenado en el 2do recv. Copio los códigos.

Mi RAM
![image](https://user-images.githubusercontent.com/49326422/126336107-c61eaf1e-9ee3-4000-86e8-9f80b6be8634.png)


Tripulante/Discordiador
![image](https://user-images.githubusercontent.com/49326422/126336575-cbc55b33-7cf7-409c-9695-f50097499d70.png)

Como te digo, avanzo y se queda ahí clavado en la linea 104. Ese recv está esperando algo y no se qué. Me llama la atención porque la función recibir_buffer está sacada del TP0 y la utilizo en todos los otros comandos (INICIAR_PATOTA, INICIAR_TRIPULANTE) y no genera este problema.

**Comment by iago64** [comment]
Cerramos el issue por falta de actividad. 
Cualquier cosa el creador lo puede volver a abrir.
