### ISSUE TITLE
Ayuda con memory leak de pthread_detach

### ISSUE THREAD

**Issue by belenbrinso** [sisoputnfrba/foro#2222]
Buenas tardes, disculpen la molestia, queríamos preguntar cómo podemos liberar la memoria que ocupan los hilos. Nosotros tenemos n hilos de planificación, con pthread_detach, y adentro de cada uno tenemos un while(validador) que los mantiene corriendo, hasta que al salir de la consola ponemos validador en 0, pero no se libera la memoria de los hilos propiamente dichos, finaliza bien el programa pero quedan aproximadamente 1KB sin liberar. Si hacemos pthread_join, se traba el programa. Qué podemos hacer? Muchas gracias!

**Comment by RaniAgus** [comment]
¡Buenas! ¿Te referís a que Valgrind devuelve algo parecido a lo siguiente al cortar la ejecución del programa con Ctrl+C?:
```
136 bytes in 1 blocks are possibly lost in loss record 15 of 41
==5672== at 0x402E0B8: calloc (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==5672== by 0x4011726: allocate_dtv (dl-tls.c:322)
==5672== by 0x401214B: _dl_allocate_tls (dl-tls.c:539)
==5672== by 0x40A5CC3: allocate_stack (allocatestack.c:588)
==5672== by 0x40A5CC3: pthread_create@@GLIBC_2.1 (pthread_create.c:539)
==5672== by 0x8049A7B: main (SAFA.c:72)
```

Creo que lo que se menciona en este comentario te puede ayudar: https://github.com/sisoputnfrba/foro/issues/1617#issuecomment-610735218

Saludos

**Comment by belenbrinso** [comment]
Nos re sirvió, muchas gracias! Saludos!
