### ISSUE TITLE
verificación de creación del bitmap - filesystem

### ISSUE THREAD

**Issue by lautaropetronacci** [sisoputnfrba/foro#2223]
Hola, como están?
Estabamos terminando de codear la creación del bitmap del superbloque y nos entro una duda sobre si estabamos pensandolo bien.

Esta es la estructura del superbloque que contiene el bitmap:
```
typedef struct {
    uint32_t Block_size;
    uint32_t Blocks;
    char* Bitmap;
}superBloque;
```
Y esto es lo que codeamos hasta ahora:

```
void generarSuperBloque(){ // crea el archivo solicitado
    char * path = string_new();
    string_append(&path, PUNTO_MONTAJE);
    string_append(&path, "/SuperBloque.ims");

    int cantidadDeBloques = (CANTIDAD_BLOQUES/8)+1;
    superBloque* supBloq;

    int fd;
    fd = shm_open(path, O_CREAT | O_RDWR, 00600);
    if (fd == -1){
        printf("error con shared memory");
        exit(1);
    }
    supBloq = mmap(NULL, sizeof(superBloque), PROT_WRITE, MAP_SHARED, fd, 0);
    t_bitarray* bitmap = bitarray_create_with_mode(supBloq->Bitmap, cantidadDeBloques, LSB_FIRST);
    
    msync(supBloq->Bitmap , cantidadDeBloques,MS_SYNC);

    munmap(supBloq,cantidadDeBloques);
    close(fd);} 
```

Nosotros tenemos pensado mapear todo el superbloque y luego extraer o sacar la variable bitmap y crearlo con el
bitarray_create_with_mode. La duda que tenemos es como sincronizar la creacion del bitmap con lo que esta escrito en el
archivo superbloque. Nosotros deberiamos inicializarlo luego de hacer el mmap y el bitarray_create_with_mode, y luego hacer
un msync en el archivo superBloque?

Lo pensamos asi pero sinceramente estamos un poco bloqueados con este tema, no terminamos de
entender las funciones mmap/memcpy/msync.

EDIT: otra duda que nos surgio es relacionada a la funcion: 
```
bitarray_create_with_mode(supBloq->Bitmap, cantidadDeBloques, LSB_FIRST); . 
```
En la declaración de la función dice esto:

```
/**
    * @NAME: bitarray_create_with_mode
    * @DESC: Crea y devuelve un puntero a una estructura t_bitarray
    * @PARAMS:
    *         bitarray - el bloque de memoria que contiene los bits a leer/escribir
    *        size - la cantidad de bits del bitarray, expresada en bytes (1 byte = 8 bits)
    *        mode - LSB_FIRST ó MSB_FIRST
    *
    *        ejemplo: bitarray de 8 posiciones (bits) con LSB_FIRST, 
    *            void* puntero_a_bits = //un byte de memoria, como por ejemplo malloc(1)
    *            bitarray_create_with_mode(puntero_a_bits, 1, LSB_FIRST)
    */
    t_bitarray    *bitarray_create_with_mode(char *bitarray, size_t size, bit_numbering_t mode);
``` 

Nosotros no entendemos que tendriamos que pasar en el primer parametro. Si nosotros al principio no vamos a tener ninguna información sobre supBloq->bitmap pero queremos que esta funcion nos genere un bitmap para despues incluirlo en ese parametro del superbloque, que deberiamos poner en el primer parametro? porque ese bloque de memoria no tiene cargado, porque recien estamos creando el archivo.

Saludos.

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Algo importante (y divertido) es que uds no tienen por que complicarse teniendo una estructura, por que al levantar con `mmap()` el archivo pueden hacer algo tan super simple como:

```C
void * superbloque = mmap(...) //Con todos los parametros que va
uint32_t* block_size = superbloque;
uint32_t* block_count = superbloque + sizeof(uint32_t);
void* bitarray_mem = superbloque + 2*sizeof(uint32_t);
t_bitarray* bitmap = bitarray_create_with_mode(bitarray_mem , block_count , LSB_FIRST); //LSB o MSB da igual, eso lo gestionan uds
```

Y básicamente se evitan la estructura, el primer parámetro del `bitarray_create()` lo que recibe es el cacho de memoria que uds quieren manejar como un bitarray, el create_with_mode lo unico que hace es decir como lo va a tratar, si contando los bits desde el mas significativo o desde el menos signiticativo, pero si esos bits los levantan en 0 van a estar en 1 y si los levantan en 1 los van a tener en 1, no les cambia el valor :)

Saludos.-

**Comment by danimontesano** [comment]
Ahh! Genial, buen truco. 
Y con respecto a lo del bitarray, es decir que siempre que instanciemos un bitarray va a tener todos los bits en 1? o fue un error de tipeo? si nosotros queremos que todos estén en 0 o como venían previamente como tenemos que hacer? manualmente uno por uno?
Y digamos, entonces... el primer parametro que recibe (bitarray_mem) es la memoria que queremos manejar, y entonces nosotros al aplicar funciones a la variable bitmap estamos cambiando el lugar de memoria que definimos en un primer lugar, correcto?
Gracias.

**Comment by Nachiten** [comment]
Buenas, respondo entre lineas porque lo veo mas facil.

> Ahh! Genial, buen truco.
> Y con respecto a lo del bitarray, es decir que siempre que instanciemos un bitarray va a tener todos los bits en 1? o fue un error de tipeo? si nosotros queremos que todos estén en 0 o como venían previamente como tenemos que hacer? manualmente uno por uno?

Lo que yo recomendaria es siempre una vez que lo creas de cero, recorrer cada bit uno por uno (obviamente con un for) y fijarlos a cero. Porque inicialmente esa memoria que le hiciste malloc va a estar llena de basura, y eso te puede generar problemas.

> Y digamos, entonces... el primer parametro que recibe (bitarray_mem) es la memoria que queremos manejar, y entonces nosotros al aplicar funciones a la variable bitmap estamos cambiando el lugar de memoria que definimos en un primer lugar, correcto?

Exactamente. Luego eso que malloqueas tendrás que dumpearlo en el archivo manualmente si no utilizaste mmap, o no necesitarías hacerlo si lo usaste.

> Ademas eln bitarray_create() en el segundo parametro deberia ir el block_count pero divido por 8 y sumandole 1, verdad? ya que estaría en bytes.
> Gracias.

No se para que querés sumarle el +1, supongo te referirás al famoso '\0'. No es necesario sumarlo en el malloc, pero si es necesario que cuando escribas hacia el archivo lo hagas con un fwrite de (lo que pesa + 1) y lo mismo cuando lo leas. Esto garantizará que ese \0 que si esta sea correctamente escrito y leído del archivo, de esta manera no tendrías problema.

Espero esto te sirva, saludos!

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

@danimontanaro cuando decía lo de los 1 y 0 era para el caso donde vos ya tenias algo creado en el archivo del superbloque de una ejecución anterior. Si tu problema era iniciarlo ahi si podes optar por la solución de ignacio de iterar todos los bits y setearlos en 0 o usar la función `memset()` antes de crear el bitarray.

Después lo del create, el sumarle 1, puede ser si llegas a tener un número que no es múltiplo de 8, no esta mal, podrias hacer el doble check de ver si el resto de dividir el block_count por 8 te da algo y en ese caso sumar 1, o sumar 1 siempre y tener cuidado de controlar de no buscar bits mas allá de tu block_count. es indistinto eso, no nos vamos a poner tan densos por 1 byte 😃 

Saludos.-

**Comment by danimontesano** [comment]
Genial! muchas gracias a ambos. 

Con lo del \0 yo tenia pensado no poner ningun caracter de corte y hacerlo directamente con el size, digamos si tengo 76 de size y mi bloque es de 50 ya se que tengo que leer los 50 bytes del primero y luego 26 bytes del segundo.

Saludos.

**Comment by RaniAgus** [comment]
¡Buenas! No hay ningún problema con calcular el final directamente con el size, está perfecto 👍🏻 
Saludos

**Comment by lautaropetronacci** [comment]
Muchas gracias @RaniAgus @iago64 @Nachiten !! 

Ahora el bitmap nos funciona perfecto, pero estuvimos pensando mucho tiempo que teniamos errores porque no lo podiamos visualizar en el notepad (leafpad en la VM). Pero al momento de agregar, modificar y leer,  mostrandolo en consola, nos aparece todo perfecto. :D

**Comment by Nachiten** [comment]
> Muchas gracias @RaniAgus @iago64 @Nachiten !! 
> 
> Ahora el bitmap nos funciona perfecto, pero estuvimos pensando mucho tiempo que teniamos errores porque no lo podiamos visualizar en el notepad (leafpad en la VM). Pero al momento de agregar, modificar y leer,  mostrandolo en consola, nos aparece todo perfecto. :D 
> 
> 

Buenisimo! Si ya quedo todo resuelto podemos cerrar el issue?

Gracias!

**Comment by RaniAgus** [comment]
¡Buenísimo! Para leer el archivo pueden usar el comando `hexdump -C` (para hacerlo desde el código, contamos en las commons con la función `mem_hexdump()`) y para editarlo pueden usar `hexedit`.

**Comment by lautaropetronacci** [comment]
Claro, comprendo. Esa era la unica duda que teniamos, como visualizar correctamente el bitmap, ya que es medio engorroso con el tema bit/byte. 
Tomo los consejos del hexdump y hexedit y cierro issue!

Gracias nuevamente, saludos
