### ISSUE TITLE
Estructura t_list: Buscar un tripulante en la estructura (uso de list_find)

### ISSUE THREAD

**Issue by federiver91** [sisoputnfrba/foro#2224]
Hola,

Como dice el título, no estaría sabiendo cómo usar la función de list_find.

Utilicé la estructura de las commons "T_LIST" para las distintas colas de los Tripulantes. Para ir cambiando los estados de estos, necesito ir gestionando esas listas.

Necesitaría un ejemplo de cómo buscar en alguna de esas listas un tripulante en particular. Les paso el struct con mi tripulante en cuestión que son los que guardo en las distintas listas.

```c
typedef struct 
{
    uint32_t tid;
    char estado;
    uint32_t posicion_x;
    uint32_t posicion_y;
    uint32_t proxima_instruccion;
    uint32_t quantum;
    t_patota* puntero_pcb;
    t_tarea* tarea;
} t_tripulante_a_planificar;

```

Y acá estan declaradas las colas
![image](https://user-images.githubusercontent.com/49326422/126020092-79572e20-5c9a-4221-a69f-92b699396c9c.png)

**Por otro lado (duda 2)**, en las t_list si yo hago un remove de un index en particular, la lista se reordena automáticamente o en esa posición (la del index removido) queda con un "hueco"?

Gracias!

**Comment by Nachiten** [comment]
Buenas, como estas?

Básicamente si te fijas los parámetros que toma list_find, esta toma dos parámetros, la lista en cuestión, y una función la cual va a aplicarse a cada elemento de la lista. Luego, la funcion va a devolver el primer elemento que cumpla la condicion (es decir que al aplicarle la funcion devuelva! 0) como bien dice la descripcion si te fijas en list.h

Pongamos un ejemplo:
Supongamos que quiero encontar un tripulante cuyo tid sea X.

En primer lugar, genero una funcion que me devuelva si el tid es el que busco:
```
int tripulanteTieneTid(uint32_t unTid, tripulante* unTripulante) {
return unTripulante->tid == unTid;
} 
```

Luego, usas list_find con la funcion y un parametro ya aplicado, la funcion deberia aplicarle el otro y deberia funcionar.

```
list_find(laLista, tripulanteTieneTid(3)
```

Avisa si con esto funciona, saludos!

**Comment by federiver91** [comment]
Hola! Gracias por la respuesta! 

Lo probé y no funciona porque debería invocar a la función tripulanteTieneTid con el TID buscado y el tripulante también, me parece.

Me tira este error
![image](https://user-images.githubusercontent.com/49326422/126037100-e4bdde96-da58-4ed5-8235-0aefb968eb60.png)

**Comment by RaniAgus** [comment]
¡Buenas! Para pasarle el ID a la función que recibe `list_find` podes utilizar una inner function. Tenemos un video acerca de cómo hacer una que les puede servir: https://youtu.be/1kYyxZXGjp0

Saludos

**Comment by federiver91** [comment]
Buenas!

Me rompe el "elemento->tid". Cómo hago para comparar en este contexto?? Gracias!!

Copio el código de la función que hice en base al video que mencionaron:

```c
t_tripulante_a_planificar* buscar_tripulante_en_lista(t_list* tripulantes_new, uint32_t tripulante_tid){
	t_tripulante_a_planificar* tripulante_buscado = malloc(sizeof(t_tripulante_a_planificar)));
	bool _el_tripulante_tiene_este_tid(void* elemento){
		return (elemento->tid == tripulante_tid);
	}

	tripulante_buscado = list_find(tripulantes_new, _el_tripulante_tiene_este_tid);
	return tripulante_buscado;
}
```

**Comment by iago64** [comment]
Buenas!

Como es que te rompe? te tira un segment fault, no funciona como esperas? o que error tenes, porque en el aire se nos complica, no somos compiladores humanos :)

Saludos.-

**Comment by federiver91** [comment]
Sí, perdón.

Rompe con este mensaje. La línea 244 es la de "return (elemento->tid == tripulante_tid);

![image](https://user-images.githubusercontent.com/49326422/126161588-5c15c5d4-0ee2-4aac-ac10-903cb4329d35.png)

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Ahora si, el error es de esas cosas rebuscadas que tiene C, basicamente lo que te esta diciendo ahi es que no encuentra el elemento `tid`, la forma de resolverlo es utilizando la forma clásica de obtener el contenido de un puntero y sería algo asi como:

```C
t_tripulante_a_planificar* buscar_tripulante_en_lista(t_list* lista_tripulantes, uint32_t tripulante_tid){
	t_tripulante_a_planificar* tripulante_buscado = malloc(sizeof(t_tripulante_a_planificar)));
	bool _el_tripulante_tiene_este_tid(void* elemento){
		return (*(elemento)->tid == tripulante_tid);
	}

	tripulante_buscado = list_find(lista_tripulantes, _el_tripulante_tiene_este_tid);
	return tripulante_buscado;
}
```

No lo probe porque me falta el resto del código, pero básicamente ahí lo que hace es que al poner el `*` antes de `(elemento)` devuelve el contenido de elemento, y a eso que te devolvió le pide el componente o la propiedad tid :)

Saludos.-

**Comment by federiver91** [comment]
Hola! 

Lo probé y me tira el mismo error.

![image](https://user-images.githubusercontent.com/49326422/126198551-3aa61c74-49a3-4c00-a6eb-84d201454bca.png)

**Comment by iago64** [comment]
Buenas!

Acabo de revisar de nuevo y no me percate de que dice void* y bueno... un void* no tiene ni la mas remota idea de que es o con que se come un tid. 
Tendrias que castearlo a tu estructura `t_tripulante_a_planificar` (o hacer que la función reciba un puntero a tu estructura y no leer el warning que tira el compilador)

Saludos.-

**Comment by federiver91** [comment]
El casteo sería algo así? Debería funcionar? Por lo menos ahora compila...

```c
t_tripulante_a_planificar* buscar_tripulante_en_lista(t_list* lista_tripulantes, uint32_t tripulante_tid){
	t_tripulante_a_planificar* tripulante_buscado = malloc(sizeof(t_tripulante_a_planificar));
	bool _el_tripulante_tiene_este_tid(void* elemento){
		return (((t_tripulante_a_planificar*)elemento)->tid == tripulante_tid);
	}

	tripulante_buscado = list_find(lista_tripulantes, _el_tripulante_tiene_este_tid);
	return tripulante_buscado;
}
```

**Comment by RaniAgus** [comment]
¡Buenas! Sí, debería funcionar

Para agregar, estás teniendo un memory leak al declarar el `tripulante_buscado`, ya que primero estás reservando memoria mediante un `malloc(sizeof(t_tripulante_a_planificar)))`, y luego a la variable en donde se almacena ese puntero la estás pisando con el puntero que retorna `list_find()`.

Creo que se puede ver más gráfico si separo la declaración de la variable con la asignación:
```c
t_tripulante_a_planificar* tripulante_buscado;

tripulante_buscado = malloc(sizeof(t_tripulante_a_planificar)));

// ...

tripulante_buscado = list_find(lista_tripulantes, _el_tripulante_tiene_este_tid);

return tripulante_buscado;
```

**Comment by federiver91** [comment]
Buenas!

Efectivamente lo probé y funcionó OK.

Respecto a lo que me comentás, Agus, si hubieras escrito en japonés me era lo mismo. Qué es lo que estaría mal? Yo declaro el tripulante buscado, le hago un solo malloc y despues lo relleno con lo devuelto por list_find.

Eso está mal de alguna manera?

**Comment by ncoen97** [comment]
Fijate que no estás "rellenando" el malloc que hiciste, sino que como dice agus, estás **pisando** (踏む) la variable en donde se almacena el puntero que te dió malloc con el puntero que te retorna `list_find()`. Te recomiendo que leas un poco más sobre programación en C en [utnso](https://www.utnso.com.ar/recursos/guias/), una manera de solucionar esto es con la función [memcpy](https://man7.org/linux/man-pages/man3/memcpy.3.html).
Saludos

**Comment by federiver91** [comment]
A ver si entiendo..

Yo básicamente lo que quiero es guardarme el tripulante que está en la lista y que list_find me encontró.

Vos decís que el malloc es innecesario entonces? Puedo guardarme el tripulante directamente haciendo esto?
```c
t_tripulante_a_planificar* tripulante_buscado = list_find(lista_tripulantes, _el_tripulante_tiene_este_tid);
```

**Comment by ncoen97** [comment]
Podes, pero tenes que tener cuidado porque si haces eso, el tripulante_buscado y el tripulante_buscado que está adentro de la lista apuntarían a la misma estructura (no se si es lo que necesitas en este caso o no). Esto quiere decir que si por ejemplo liberas la memoria de ese tripulante_buscado que te dio `list_find()`, vas a liberar el que te quedó adentro de la lista (y va a quedar en su lugar un puntero invalido).

**Comment by federiver91** [comment]
Ah no no, está bien. 

Yo quiero que sea el mismo en este contexto. No quiero hacerme una copia. Quiero apuntar al que está guardado en la lista para cambiarle los atributos y, eventualmente también, removerlo de esa lista y pasarlo a otra por ejemplo.

En ese caso que quiero manipular siempre la misma instancia, no tengo que hacer nunca un malloc nuevo entonces?

Y si hiciera un malloc estoy haciendo una copia y debería rellenarlo con memcpy?

**Comment by ncoen97** [comment]
Correcto

**Comment by federiver91** [comment]
LIsto, perfecto. Con esto estamos entonces.

Gracias a todos. Lo cierro

**Comment by RaniAgus** [comment]
¡Oops! Justo quería explicarte a qué me refería con "pisar" 😅 

Veamos el siguiente ejemplo:
```c
int a = 0;
a = 1;
```
En este caso, yo estoy declarando una variable en 0 y luego "piso" ese valor a 1.

Entonces, tengamos las siguientes consideraciones:

- Un puntero es básicamente un número entero como cualquier otro, solo que tiene la particularidad de que indica una dirección en memoria (normalmente lo representamos en hexa xq es más cómodo: `0x1234`, `0x4567`, etc).
- `malloc()` reserva memoria en el heap (a.k.a memoria dinámica) y devuelve **un puntero hacia** el primer byte en donde empieza, o sea, no es que devuelve el cacho de memoria que reservó, sino que devuelve solo un número entero que indica en dónde ir a buscarlo.
- `list_find()` también devuelve **un puntero**, en este caso, **hacia** el primer byte del struct `t_tripulante_a_planificar` que esté guardado en la lista y cumpla con la condición que recibe por parámetro (si no lo encuentra, devuelve `NULL`, o sea, `0x0`).

Entonces, volviendo al ejemplo, si asumimos que `malloc()` devuelve `0x1234` y `list_find()` devuelve `0x4567`, estarías haciendo lo siguiente:

```c
t_tripulante_a_planificar* tripulante_buscado = 0x1234;
// ...
tripulante_buscado = 0x4567;
```
Que sería lo mismo que vimos arriba con el `int`.

Entonces, (por más que no sea el caso) si quisieras "rellenar" **lo que está en** `0x4567` **dentro de** `0x1234` como mencionaba Nico, lo adecuado sería hacer un `memcpy`:

```c
t_tripulante_a_planificar* tripulante_buscado = malloc(...); // devuelve 0x1234

// ...

t_tripulante_a_planificar* tripulante_en_lista = list_find(...); // devuelve 0x4567

memcpy(tripulante_buscado, tripulante_en_lista, sizeof(t_tripulante_a_planificar)); 
// sería hacer memcpy(0x1234, 0x4567, sizeof(t_tripulante_a_planificar));
// o sea, rellenar dentro de 0x1234 una copia de lo que está en 0x4567

return tripulante_buscado; // retornamos la copia
```
