### ISSUE TITLE
Planificación: Implementar Semáforo para darle play/pause a los tripulantes

### ISSUE THREAD

**Issue by federiver91** [sisoputnfrba/foro#2225]
Buenas! 

Hay algún ejemplo o tutorial que recomienden para resolver esta implementación? Hace varios días que lo pienso y no llego a nada.

Quizás el approach de diseño esté incorrecto, pero lo que yo pensé es tener un "semáforo" que actúe como una especie de botón play/pause, gestionado desde un hilo único "Planificador", cuyas únicas funcionalidades son habilitar o deshabilitar ese semáforo y gestionar las colas de Ready y Exec. Después cada tripulante, de acuerdo al estado que tenga y a si está habilitada la planificación, se autogestiona.

Pero acá tengo un problema porque los Tripulantes son de una cantidad indefinida, dinámica en tiempo de ejecución. Y yo quisiera que se detengan en algún punto de su código (sin espera activa) esperando que se "levante la barrera" para poder ejecutar. Es decir, que la variable/semáforo/señal de planificación esté prendida.

Me ayudan un poco validando este "diseño" o bien corrigiéndolo para ver qué es lo más conveniente?

Y por otro lado, yendo al núcleo del issue, a cómo implementar esta "barrera"/semáforo/señal/variable???

Gracias y saludos!

**Comment by Nachiten** [comment]
Buenas, todo bien? 

Vamos parte por parte. 

Lo primero, este semáforo que actúa como una especie de play/pause no entiendo muy bien como lo harías? Pero yo te tiro un palo de como podría ser (es una de varias posibilidades). 
Podrías tener una lista de semáforos, uno para cada tripulante, generada a demanda (ahora te explico eso en detalle) y luego cada tripulante en su hilo simplemente haría un wait antes de hacer un ciclo, y luego de realizarlo haría un signal (para habilitarse a si mismo el siguiente ciclo). 
Pensá que cada semáforo debería iniciarse en UNO no en cero, dado que en en primera instancia todos los tripulantes si están habilitados para ejecutar. 
Luego, en el momento que quieras por ejemplo pausar planif, necesitas tener referencia a cada uno de esos semáforos desde afuera de los hilos (una lista) y simplemente le haces wait a todos. Entonces cuando cada hilo haga el primer wait que te mencione, se queda ahí esperando. 
En el caso de despausar, volvés a recorrer la lista de semáforos haciendo signal. 

Para explicar un poco mas el tema lista de semáforos que a algunos los asusta mucho, simplemente pensá que vos podes crear la cantidad de semáforos que quieras a demanda (por ejemplo cada vez que creas un nuevo tripulante) como un puntero (por ejemplo adentro de un for) y dsp meterlos en algo como una lista de las commons. 

Y eso es todo, luego solo recorres esta lista de semaforos con un for para hacerle lo que quieras.

Espero que esto te sirva, saludos!

**Comment by federiver91** [comment]
Buenas!

Estoy viendo cómo armo y le doy vida a esta solución.

Consulta: Con este planteo, los semáforos deberían estar como un atributo más de mi estructura tripulante no? Como para que cada tripulante sepa cuál es su semáforo para hacerle los correspondientes wait y signals.

Estoy en lo correcto?

Gracias!

**Comment by RaniAgus** [comment]
¡Buenas! Sí, sin entrar mucho a detalle me suena a que es una forma válida de implementarlo. Recordá que el único lineamiento que les damos es que se cree un hilo por tripulante, pero más allá de eso cualquier forma que les sea cómodo de implementar va a estar bien. Saludos

**Comment by federiver91** [comment]
Buenas,

Vuelvo con esto porque no me cierra la solución.

DUDAS:

1) Cómo implementar o cual es la mejor forma de tener esa "lista de semáforos"? Cómo puede acceder cada tripulante a su semáforo en cuestión?

2) Duda principal. Para PAUSAR la planificación, por ejemplo, desde dónde hago la recorrida de esa lista para hacerles "sem_wait"? Pregunto porque entiendo que sem_wait es bloqueante. O sea que desde donde haga esa recorrida+llamada se va a bloquear mi proceso. O no? Cómo se implementaría?

Gracias!

**Comment by RaniAgus** [comment]
1. Existen múltiples formas de implementarlo, recordá que un puntero puede ser referenciado desde varios hilos para poder acceder a ese fragmento de memoria desde distintos lados, así que podés hacer uso de eso para que un hilo sea productor y otro sea consumidor.
2. Para poder determinar cómo sincronizar los hilos te aconsejo hacer una tabla similar a las que se utilizan para resolver los ejercicios de la parte práctica de la cursada: en cada columna un hilo y dentro el código a sincronizar. A mí en su día me ayudó mucho, ya que permite tener una visión más global de cómo sincronizar el módulo.

**Comment by iago64** [comment]
Cerramos el issue por falta de actividad. 
Cualquier cosa el creador lo puede volver a abrir.
