### ISSUE TITLE
Caso de prueba - Memoria - Segmentación

### ISSUE THREAD

**Issue by eguiggiaro** [sisoputnfrba/foro#2226]
Hola, ¿cómo están?

Tengo una consulta sobre el caso de prueba **Memoria - Segmentación, de la entrega final.**

El caso de prueba indica:

> - Al momento de iniciar la patota B:
> - Con FF debe quedar un hueco libre al lado del PCB ya que debería ocupar el espacio del tripulante A1.
> - Con BF el PCB de la patota B ocupará el espacio del PCB de la patota C por lo que no habrá un hueco en ese lugar

Y más abajo indica:

> - Al momento de cargar las tareas se debe compactar la memoria para generar el hueco libre para las tareas de la patota B.

El problema que encontramos en nuestra implementación es que nuestro algoritmo de detección de compactación se hace al recibir la patota. Validamos que haya espacio total en principio, y después, para tareas / patotas / tripulantes, que haya al menos un segmento en el que puedan alocarse, considerando si es FF o BF.

Por este motivo, no podemos mostrar en la prueba que realmente se cumple BF o FF porque se compacta la memoria para cargar la patota B. Si aumentamos el tamaño de la memoria para que no sea necesario compactar, se ve ok el comportamiento.

¿Es incorrecta la implementación? ¿O estamos entendiendo algo mal de la prueba?

Gracias!

**Comment by gastoncastineira** [comment]
Buenas,

Corregime si te entendí mal, pero por ejemplo (e invento y redondeo números por simpleza):
- PCB 10
- 1 TCB 10
- Tareas 20

Tenés exactamente 40 bytes libres en tu memoria, pero los tenés libres en las posiciones:
- 15-25
- 40-50
- 70-90

En tu TP por lo que te entendí, como no tenés 40 bytes contiguos se compacta? O hay algo que estoy entendiendo mal?

**Comment by eguiggiaro** [comment]
Hola Gastón,

Gracias por la respuesta!! Comparto el caso real y capaz es más fácil verlo:

![image](https://user-images.githubusercontent.com/26398054/126053397-c0c16d90-bcad-4948-be84-da62291c2caf.png)

En la imagen se ve el estado previo a que ingrese una nueva patota que tiene los siguientes valores:

PCB: 8B / 3 TCBs de 21B / Tareas 30B

- ¿Tengo lugar en memoria? Sí
- ¿Tengo bloques libres que se adecúen a la necesidad? No. Por ejemplo, las tareas no entran en ninguno.

Por eso en nuestra implementación, cuando llega un INICIAR_PATOTA a memoria, se evalúan los dos puntos: si entra el total, y si voy a tener problemas para ubicar a todos los segmentos. Si hay espacio pero la disposición de segmentos no alcanza, se compacta. No evaluamos bloques contiguos, los segmentos se pueden ubicar en distintos lugares.

El problema es que el resultado esperado de la prueba es que MiRAM vaya ubicando con FF o BF y se vean los huecos en el medio, etc, Nosotros estamos compactando antes de ubicar la patota B (que es la del problema) porque sabemos de antemano que se requiere compactar. Entonces no van a poder visualizar que usé los algoritmos en la prueba. ¿Estamos haciéndolo mal?

Si no estoy siendo claro, avisame y me acerco al soporte en la semana.

Gracias de nuevo!!

**Comment by ncoen97** [comment]
Buenas, el comportamiento en sí no es el esperado (porque en las pruebas compactamos cuando se va a guardar el segmento en particular que no tiene espacio disponible), pero no es un comportamiento erróneo porque en el enunciado no aclaramos cual de las dos opciones se debe utilizar. Por lo tanto el día de las pruebas si siguen teniendo el comportamiento que tienen ahora, el/la ayudante que esté evaluando va a tener que indagar un poco más en cómo están haciendo los reemplazos y van a tener que explicar esto mismo que explicaste recién de por qué no dan las pruebas. Si quieren igualmente pueden modificar el comportamiento (que no parece ser algo muy complicado de modificar, sería mover la función de compactar a otro lugar del código).
Saludos!

**Comment by eguiggiaro** [comment]
Gracias Nico! lo evaluamos para ver qué conviene!
