### ISSUE TITLE
[Mi-Ram-HQ] Paginación : Cuando traer páginas a memoria y cuando no / duda del dump

### ISSUE THREAD

**Issue by jcastagno99** [sisoputnfrba/foro#2227]
Buenas! tengo una pregunta sobre cuando las páginas deben estar en memoria.

Internamente entre los flujos de mensajes siempre voy controlando la existencia de mis patotas o de los tripulantes, para eso voy iterando listas y copiando datos (pid/tid) para comprobar esa existencia y devolver error de no encontrase nada, ahora. ¿cuando yo voy iterando y leyendo esas páginas me las tengo que traer a memoria? es una lectura secundaria, entiendo que para los mensajes principales al modulo (cuando actualizo datos, o proveo datos) si hay que traerlas, pero ¿para estas iteraciones es necesario? 
Es muy probable que los resultados de las pruebas cambien bastante de si hay que traerlas o no.

La otra consulta es ya de otro tema, actualmente tengo una función de DUMP que arroja :

Dump: 17/07/21 16:44:55 
Marco: 0         Estado: 0       Proceso: 1      Pagina: 0 
Marco: 1         Estado: 0       Proceso: 1      Pagina: 1 
Marco: 2         Estado: 0       Proceso: 1      Pagina: 2 
Marco: 3         Estado: 1       Proceso: 0      Pagina: 0 
Marco: 4         Estado: 1       Proceso: 0      Pagina: 0 

El estado se muestra como un boleano, 0 ocupado 1 libre, y en el proceso al que se pertenece cuando es 0 es porque no hay ningun proceso, (nuestros PIDS arrancan en 1, por lo que nunca va a haber un Proceso con Pid 0 que confunda), es valido dejarlo asi? o necesariamente el estado tiene que ser LIBRE/OCUPADO y cuando no exista en ese marco mostrar un "-"?

**Comment by Franpanozzo** [comment]
Buenas, tenemos las mismas dudas sobre cuando traer las paginas a memoria, no sabia si abrir otro issue pero como es la misma duda, almenos la primer parte comento acá, cualquier cosa diganme y abro otro, así que dejo nuestras preguntas que van un poco mas especificas en los casos: 
DUDAS:

 1) Cuando toco la estructura administrativa de la pagina, no a la pagina en si. Hay que traer la pagina a memoria principal si es que esta en virtual?? O solo me la traigo si es que voy a modificar o necesitar lo que esta adentro de la pagina
 (Ejemplo: agarrarProxTarea o actualizarTripulante)? Cuando serian bien los casos cuando hay que traerla?? En el issue #2183 dicen pero no me termina de cerrar.

 2) Cuando se borran contenidos dentro de las paginas, también hay que traerlas a memoria principal?? Si hacemos esto, primero la traemos después la borramos y quedaría el frame libre no? Dice algo damian también en el issue #2183 pero no lo entendí.

3) Después cuando guardo cosas en el espacio que sobra de la pagina, en ese caso me la traigo a principal si esta en virtual no?

**Comment by iago64** [comment]
Buenas ¿Cómo va?

Todo lo referente a sus estructuras administrativas no debería reflejarse en las referencias a los accesos a las páginas porque son cosas que están por fuera.
Ahora si por ejemplo si tienen que:

- Actualizar el estado de un tripulante
- Actualizar la posición de un tripulante
- Leer una tarea

Ahí si tienen que actualizar el estado porque están haciendo algo sobre los datos.

@Franpanozzo 
A que te referis con borrar contenido? Porque justo se da la situación de que se borra algo cuando termina y ahí ya te alcanzaría con marcar como libre las páginas y ya :)

Saludos.-

**Comment by jcastagno99** [comment]
Buenisimo, y con el tema del dump que menciono arriba?

Y ya que lo dicen iba a preguntar tambien, cuando se borra a un tripulante, el unico caso en el que se modifica algo (paginación) es si al liberarlo el frame quedara 100% libre? en dicho caso deberia marcar al frame como libre y borrar al tripulante del mapa, en cualquier otro caso realmente no hago nada, debería borrarlo de memoria virtual?

**Comment by jcastagno99** [comment]
Añado una duda sobre un caso borde, yo entiendo que entre mas robusto el codigo mejor, pero tiene sentido modelar pensando en tener paginas de 2 bytes o menos? pregunto esto especifico porque es el unico caso que encontre en el que rompe mi codigo, me puede caer algo asi en las pruebas?

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Mil disculpas, se me paso el tema del dump, como lo tienen esta bien, mientras lo puedan explicar durante la evaluación para que lo entendamos estamos joya :)

Saludos.-

**Comment by jcastagno99** [comment]
Joya, por mi parte ya estaría, gracias!
dejo el issue abierto por si el otro chico quiere responder.

**Comment by Franpanozzo** [comment]
Se entendió perfecto ,muchas gracias!!

**Comment by tferraro** [comment]
Piola, cierro el issue nomá :D
