### ISSUE TITLE
[I-Mongo-Store] Sabotaje al Superbloque.ims

### ISSUE THREAD

**Issue by amanuele** [sisoputnfrba/foro#2228]
Hola buenas! tengo una consulta acerca de como serán los sabotajes al Superbloques.

¿Quién es el encargado de modificar los datos del archivo en cuestión? es decir, para hacer un sabotaje al bitmap, por ejemplo, tengo que alterar los bits del mismo, ¿Eso cómo se hace efectivo? ¿Lo realizan ustedes mediante algun editor de binario? Nosotros para probarlos hicimos unos tests internos, pero me gustaría saber como se va a hacer el día de la entrega para poder probarlo de la misma manera.

Desde ya muchas gracias.
Saludos!

Ariel.

**Comment by Nachiten** [comment]
> Hola buenas! tengo una consulta acerca de como serán los sabotajes al Superbloques.
> 
> ¿Quién es el encargado de modificar los datos del archivo en cuestión? es decir, para hacer un sabotaje al bitmap, por ejemplo, tengo que alterar los bits del mismo, ¿Eso cómo se hace efectivo? ¿Lo realizan ustedes mediante algun editor de binario? Nosotros para probarlos hicimos unos tests internos, pero me gustaría saber como se va a hacer el día de la entrega para poder probarlo de la misma manera.
> 
> Desde ya muchas gracias.
> Saludos!
> 
> Ariel.

Buenas, como estas?

Basicamente los archivos que tengan que ser modificados se hará de maneja externa. Pueden tomarlo como algo que es ajeno a ustedes y que no deben preocuparse digamos por hacerlo.

Pero para que tengas la info nosotros vamos a modificar estos archivos si con un progama. Si lo quieren hacer ustedes mismos para probar está perfecto que lo hagan, y es la idea tambien.

Delego a otro que lea que te tire el nombre del programa que no lo tengo en este momento, disculpa. 

Espero esto te sirva, saludos!

**Comment by amanuele** [comment]
Hola Ignacio, gracias por la respuesta! Quedo claro. Espero si alguno de los otros ayudantes me puede decir el nombre del programa para hacer la modificacion del archivo, antes de cerrar el issue.

Saludos!

**Comment by iago64** [comment]
Buenas ¿Cómo va?

Una de las alternativas que pueden usar es utilizar `hexedit`, que en las vms creo que no esta instalado pero lo pueden instalar rapidamente tirando el comando `sudo apt install hexedit` y ya lo tienen.

Para guardar / salir usa los mismos atajos de teclado que el `nano` (Ctrl + X para salir y ahi les va a preguntar si quieren guardar los cambios)

Saludos.-

**Comment by amanuele** [comment]
Hola Damian, geniaaal! muchisimas gracias!! 
Saludos!
