### ISSUE TITLE
[Mi-RAM HQ] Duda sobre el funcionamiento del mapa en paginación.

### ISSUE THREAD

**Issue by int0x80-sys** [sisoputnfrba/foro#2229]
Buenas.

Recientemente nos surgió una duda sobre el mapa. Nosotros lo que hacemos actualmente es que cuando el mapa dibuja a los tripulantes, este le tiene que pedir a la memoria las posiciones de los mapas. El problema es que al hacer esto en paginación, estaríamos alterando el orden en que se traer de swap a memoria real las páginas (ya que el mapa pediría todas las posiciones de todos los tripulantes del sistema, y se deberían traer todas las páginas de todos los TCB). ¿Estaría bien ese comportamiento? Lo otro que se me ocurre es que el mapa tenga una estructura a parte con las posiciones de los tripulantes y que esta se vaya actualizando en paralelo a los TCBs (es decir, con cada mensaje de movimiento de un tripulante, se actualizaría los TCBs y las estructuras del mapa).

Saludos 👋

**Comment by ncoen97** [comment]
Buenas, la alternativa correcta es la de ir modificando las estructuras propias del mapa mientras vayan llegando los mensajes de actualización de movimiento del tripulante. La otra opción además de ser más costosa en cuanto a recursos les va a modificar los resultados esperados en las pruebas. Saludos!

**Comment by int0x80-sys** [comment]
Clarisimo. Gracias.

Saludos 🚀
