### ISSUE TITLE
Dudas varias sobre Enunciado de MIRAM

### ISSUE THREAD

**Issue by study64** [sisoputnfrba/foro#2230]
Hola que tal, tengo las siguientes dudas que me surgieron durante la implementación de MIRam respecto al enunciado:

¿Las tablas de segmentos y de páginas pueden tener la información de a que patota/tripulante pertenecen?

¿Las tablas de segmentos y de páginas ocupan lugar dentro de la memoria reservada de acuerdo al archivo de configuración o puedo usar memoria aparte para contenerlas?

Y una mas general ¿todos los tripulantes ejecutan todas las tareas o si tengo 10 tareas para una patota con dos tripulantes, cada tripulante ejecuta 5?

**Comment by Nachiten** [comment]
Buenas! Te voy respondiendo parte por parte.

> ¿Las tablas de segmentos y de páginas pueden tener la información de a que patota/tripulante pertenecen?

Si, las tablas deben tener este tipo de informacion para que sepas cual es cual. 

> ¿Las tablas de segmentos y de páginas ocupan lugar dentro de la memoria reservada de acuerdo al archivo de configuración o puedo usar memoria aparte para contenerlas?

No, ningun tipo de estructura administrativa que no sea la memoria misma utiliza el tamaño asignado por config. Solo los datos que nosotros te dijimos cuentan (tcb, pcb, tarea) 

> Y una mas general ¿todos los tripulantes ejecutan todas las tareas o si tengo 10 tareas para una patota con dos tripulantes, cada tripulante ejecuta 5?

La primera. Si hay 3 triuplantes y las tareas A, B, C, D. Entonces tripulante 1 hace ABCD, 2 hace ABCD y los tres lo mismo. 

Saludos!

**Comment by study64** [comment]
Perfecto, gracias por tu ayuda.
