### ISSUE TITLE
Parámetros de la expulsión de la patota 

### ISSUE THREAD

**Issue by mercedesmagnelli** [sisoputnfrba/foro#2232]
Buenas tardes, estábamos con mi grupo leyendo el archivo de las [pruebas finales ](https://docs.google.com/document/d/1rorLRNnwpM9kKxeuHAwM0mmNN20X0Mb20Q-I66y6sdc/edit#) y nos llamó la atención lo siguiente. Cuando vamos a hacer la expulsión de un tripulante, por parámetro tienen que venir el id del tripulante que queremos eliminar, junto con la patota a la cual pertenecería (imagino, igual, que si se pusiera alguna patota incorrecta, MIRAM debería hacer algún tipo de validación, pero excede a mi duda). 

![image](https://user-images.githubusercontent.com/62451237/126189802-e38936a9-fbc6-4c25-8045-643054e29bdd.png)

Ahora entra mi duda: en el [enunciado](https://docs.google.com/document/d/1u54jk7uKaa6BOAXgLuNVfeYN_mwPBje94iX_6KqvqJo/edit), se puede ver que cuando entramos por consola al comando EXPULSAR_TRIPULANTE, se haría de la siguiente forma: 

![image](https://user-images.githubusercontent.com/62451237/126190070-5efaaf2d-cdd7-44e2-a0fd-c346dff193bc.png)

entonces, ¿a cual le damos más importancia? 

Además, otra duda a raíz de esto es la forma en la que guardamos el PCB porque en la estructura de PCB, dice que el identificador de la patota es un uint32_t. ¿Deberíamos guardar, entonces, como un valor ascii esa patota que podría ser alfanumérica?

![image](https://user-images.githubusercontent.com/62451237/126190372-99aecda8-bdfb-42b9-b001-d2c3c204d02b.png)

Espero haber sido clara con la duda :)

Gracias!

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

La idea del documento de pruebas es cubrir las posibles variantes de interfaz que hayan creado los grupos, por eso es que se puso A1 y A3, para aclarar que eran el tripulante 1 y 3 de la patota A, ahora si uds tienen un tripulante autoincremental global para todas las patotas simplemente van a tener que poner por ejemplo EXPULSAR_TRIPULANTE 1 y EXPULSAR_TRIPULANTE 3, o el número que correspondan a esos tripulantes de esa patota en particular.

Saludos.-

**Comment by mercedesmagnelli** [comment]
Perfecto, entendido. Gracias :)

**Comment by SantiagoOrlando29** [comment]
Hola
Me surgió una duda leyendo esto. Nosotros tenemos tripulantes autoincrementales globales para todas las patotas (o sea que en toda la ejecución va a haber un solo TID 1, un solo TID 2 y así, no se repiten los TIDs). Podemos igualmente mandar algo como EXPULSAR_TRIPULANTE 3 5 refiriéndonos por ejemplo al tripulante 3 de la patota 5? O como lo hacemos con tripulantes autoincrementales globales, si o si tenemos que mandarle solo EXPULSAR_TRIPULANTE 3 (sin el número de patota)?

Saludos!
