### ISSUE TITLE
Consulta tarde por planificacion FIFO o RR

### ISSUE THREAD

**Issue by heinHertz** [sisoputnfrba/foro#2234]
Tengo una consulta tarde, el tema es que en mi grupo estamos tratando de ver hasta donde llegamos con el tp:
estamos en la parte de FIFO o ROUND ROBIN y el tema del archivo:
```Recibirá como parámetro la cantidad de tripulantes que tendrá la patota, un archivo de tareas que contendrá el listado de todas las tareas que deberán ejecutar todos los tripulantes de la patota(se indica el formato en la siguiente sección)  y una lista de posiciones iniciales de los tripulantes. 
```
a) es decir que si el archivo tiene una lista de tareas en el archivo, a una tarea por linea, los tripulantes deben hacer todas, es decir cada uno, por ejemplo si el archivo tiene 3 lineas , los tripulantes deben copiar y hacer cada uno 3 tareas ? 
b)el tema de que si por ejemplo una patota tiene varios tripulantes, si fifo seria primero se ejecuta este tripulante ( y hace todas las tareas del archivo ) y despues otro (y hace lo mismo) es correcto ?
c) en caso de que se creen varios INICIAR_PATOTA con sus tripulantes y despues INICIAR_PLANIFICACION.  la planificación actúa como si cada patota tuviera su propia planificación o es el fifo o rr se planifica por patota ? Y si la patota tiene varios tripulantes ? es correcto este razonamiento?

muchas gracias.

**Comment by gastoncastineira** [comment]
1. Correcto
2. Correcto, ojo las tareas IO nomás
3. Como dice el enunciado, lo que planifica son los tripulantes, haciendo analogía a la parte teórica de la materia y la planificaciones de hilos kernel

**Comment by heinHertz** [comment]
Ah Gracias. 
con respecto  a la pregunta 2 que significa IO nomas ? es decir que  se descartan las "comunes" y se planifica fifo con las que tenga IO ? lo mismo pasa con Round Robin?

**Comment by iago64** [comment]
Buenas!

IO, I/O, E/S, Entrada Salida o también conocidas como las tareas que están detalladas en el [Anexo II - Descripción de las tareas del tripulante](https://docs.google.com/document/d/1u54jk7uKaa6BOAXgLuNVfeYN_mwPBje94iX_6KqvqJo/edit#heading=h.ogalug6n8axj).

Saludos.-

**Comment by heinHertz** [comment]
Mil disculpas, hice mal la pregunta. me respondieron en la  2 que " las tareas IO nomas" , ¿ si un tripulante tiene por ejemplo una mezcla de tareas io y normales en el archivo, entonces asumo que al iniciar la planificación se descartan las "normales"  y se ejecutan solamente las que tienen IO.   ?
entonces las "normales" sirven solamente cuando por ejemplo hago iniciar patota y estos de alguna manera se desplazan hasta llegar a la ubicacion ? este razonamiento esta bien?

**Comment by gastoncastineira** [comment]
No. 
Tu planteo fue que en planificación FIFO el tripulante no sale de exec nunca, y eso no es así. Cuando un tripulante tiene una tarea de IO, pasa a bloqueado y cuando termina su ráfaga IO vuelve a READY

**Comment by heinHertz** [comment]
gracias
