### ISSUE TITLE
Semáforos: Habilitar hilo Planificador desde Discordiador

### ISSUE THREAD

**Issue by federiver91** [sisoputnfrba/foro#2235]
Buenas!

Se me está frenando el programa en un wait que implemento para un semáforo y no se qué estoy haciendo mal. Algún centro, por favor??

Básicamente, desde Discordiador.c (al iniciar su main) genero un UNICO hilo Planificador. El mismo tiene un while(1) con un sem_wait inmediatamente después. La idea es que, desde el Discordiador, cuando se ingresa por consola INICIAR_PLANIFICACION, yo pueda hacer un sem_post y ahí el Planificador se "destrabe". Sin embargo, lo que me está pasando es que el hilo Planificador se bloquea con el sem_wait inicial (como efectivamente espero) pero sin embargo no continúa la ejecución del proceso Discordiador. Queda TODO bloqueado. Tenía entendido que esto no es lo que pasaba con el uso de semáforos e hilos cuya ejecución era independiente, con lo cual sospecho estar haciendo algo mal.

Acá van los códigos, resumidos...

Discordiador.c
```c
int main(int argc, char ** argv){

    //Inicializo semáforo para Hilo Planificador
    sem_init(&planificador_semaforo, 0, 0);

    //Inicio hilo Planificador que moverá tripulantes si se encuentra habilitado su semáforo, gestionado desde Discordiador por ingreso desde Consola        
    pthread_t hilo_planificacion;
    if(pthread_create(&hilo_planificacion, NULL, (void*)planificador, NULL) != 0){
        return -1;
    }
    pthread_join(hilo_planificacion, NULL);

    int consola_run = 1;
    while (consola_run) {
.
.
.
        switch(operacion_recibida) {
                ...
            case INICIAR_PLANIFICACION:
                {
                    //TODO: Hacer Signal al Semáforo del Hilo Planificador
                    sem_post(&planificador_semaforo);
                    //TODO: Hacer Signal a todos los semáforos de los tripulantes
                    break;
                }
                case PAUSAR_PLANIFICACION:
                {
                    //TODO: Hacer Wait al Semáforo del Hilo Planificador
                    sem_wait(&planificador_semaforo);
                    //TODO: Hacer Wait a todos los semáforos de los tripulantes
                    break;
                    
                }

```

Planificador.c (el hilo)
```c
void planificador()
{
    while(1){

        sem_wait(&planificador_semaforo);    
        printf("INICIO PLANIFICACION!");

        sem_post(&planificador_semaforo);

```

Y ahora que lo estoy copiando, me surge una nueva duda. Es correcto este diseño en su concepto? Porque, además de lo que estoy planteando en el issue (que el Discordiador no continúa su ejecución), no se me frenaría todo el programa también si se PAUSA LA PLANIFICACION? Ese "sem_wait(&planificador_semaforo)" no me bloquearía todo el proceso también?

Me ayudan a implementar esto, por favor? 
Gracias totales!

**Comment by federiver91** [comment]
Me di cuenta que se solucionaba poniendo el pthread_join al final del main del Discordiador.

Sigo con la duda del final igual. No se como hacer para que PAUSAR_PLANIFICACION no haga que se me frene todo el código del Discordiador.

**Comment by iago64** [comment]
Buenas! 

El PAUSAR_PLANIFICACION, lo que debería frenarte es solamente a los tripulantes, con lo cual, un poco la idea es que cada tripulante tenga una forma _única_ de ser pausado, por lo que puede ser que en lugar de tener 1 solo semáforo para todo, tengas que poner varios (por ejemplo 1 por tripulante) que te permita pausar la planificación y reanudarla (haciéndoles post para frenarla y wait para reanudarla por ejemplo), ya que los tripulantes por definición del enunciado tienen que ser hilos independientes.

Saludos.-

**Comment by federiver91** [comment]
Mmm está mal entonces como yo lo pensé? 

A ver, el INICIAR_PLANIFICACION y el PAUSAR_PLANIFICACION pensé hacerlo como habilitadores y deshabilitadores de dos tipos de semáforos a la vez.

Obviamente, uno de ellos, sería para recorrer esa lista de semaforos de tripulantes y hacerles post o wait según corresponda (como dicen los To-Do de los comentarios al final).

Pero el otro semáforo, por el que abro el issue, es por el Planificador. Yo tengo un hilo único planificador en el que pienso delegar la responsabilidad de mover tripulantes de una cola a la otra para que después los tripulantes se autogestionen consultando el estado en el que están.
Pero este hilo planificador también va a depender su ejecución de que la planificación esté activada o no. Por eso pensé un semáforo dedicado para ese hilo.

Sin embargo, al tener el wait de ese semáforo del hilo planificador en el Discordiador mismo, me termina pasando que me bloquea todo el Discordiador (consola incluida) y no es lo que quiero en este caso.

**Comment by federiver91** [comment]
Igual ahora que lo pienso, olvidate del hilo planificador. Lo voy a volar y hacer que los tripulantes se autogestionen 100% de acuerdo a si la planificación está activada o no.

Pero entonces quedo en la misma. Cómo hago para que cuando en la consola del Discordiador ingrese PAUSAR_PLANIFICACION y recorra la lista de SEMAFOROS_TRIPULANTES (ponele) haciendoles un wait a todos y que no se me bloquee el proceso entero de Discordiador?

**Comment by RaniAgus** [comment]
Veo que el issue está duplicado en #2225 . Seguimos las dudas por aquel para unificar
