### ISSUE TITLE
Parámetros de EXPULSAR_TRIPULANTE 

### ISSUE THREAD

**Issue by SantiagoOrlando29** [sisoputnfrba/foro#2236]
Hola
Me surgió una duda leyendo el issue #2232 . Nosotros tenemos tripulantes autoincrementales globales para todas las patotas (o sea que en toda la ejecución va a haber un solo TID 1, un solo TID 2 y así, no se repiten los TIDs). Podemos igualmente mandar algo como EXPULSAR_TRIPULANTE 3 5 refiriéndonos por ejemplo al tripulante 3 de la patota 5? O como lo hacemos con tripulantes autoincrementales globales, si o si tenemos que mandarle solo EXPULSAR_TRIPULANTE 3 (sin el número de patota)?

Saludos!

**Comment by gastoncastineira** [comment]
#2232

**Comment by SantiagoOrlando29** [comment]
Excelente! muchas gracias
