### ISSUE TITLE
Problema con Memory Leak

### ISSUE THREAD

**Issue by belenbrinso** [sisoputnfrba/foro#2238]
Buenas tardes, perdón por la molestia, queríamos preguntar si still reachable y possibly lost cuentan como memory leak, porque la mayoría son del readline y de hilos detacheados que al salir de la consola no se liberar bien, aunque también tenemos un par que son de nuestro código.
Otra pregunta relacionada, los únicos 6 bytes de memory leak en definitely lost son también del readline, y no sabemos cómo solucionarlo, adjunto fotos. Muchas gracias!

![](https://cdn.discordapp.com/attachments/829434733862846508/867119003280605194/memLeak2.PNG)

![](https://cdn.discordapp.com/attachments/829434733862846508/867119007327977492/memLeakReadline.PNG)

Lo que aparece con readline:
![](https://cdn.discordapp.com/attachments/829434733862846508/867120584068431882/unknown.png)

Lo que aparece con los hilos:
![](https://cdn.discordapp.com/attachments/829434733862846508/867120732751921172/unknown.png)

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

El sill reachable, lo que te dice es que al momento de cerrar tu programa tenias referenciada toda esa memoria (que podrías haber liberado) así que no te preocupes.
Lo que deberia preocuparte es el definitely lost, pero en tu caso son 6 bytes, si eso es despues de completar las pruebas esta joya, el 0 absoluto es ideal, pero 6 bytes tampoco los vamos a andar contando :)

Saludos.-

**Comment by ncoen97** [comment]
Ya que dami hizo de policía bueno, yo me pongo la gorra y les dejo para que revisen [este comment](https://github.com/sisoputnfrba/foro/issues/1974#issuecomment-724458502). Saludos!

**Comment by RaniAgus** [comment]
¡Buenas @belenbrinso ! Paso a patrullar para saber si quedó alguna duda con las respuestas de Dami y Nico o si ya podemos cerrar el issue 👮🏻‍♂️

**Comment by belenbrinso** [comment]
Buenas! Quedó clarísimo, mil disculpas que no cerré el issue! Muchas gracias y saludos!
