### ISSUE TITLE
¿Qué se espera de Segmentación?

### ISSUE THREAD

**Issue by GuidoDipietro** [sisoputnfrba/foro#2239]
### Tiempo estimado de lectura: 2 minutos + 6 minutos de planilla externa
Issue relacionado: #2210 
---
Buenas.

Al simular la prueba de Segmentación, con el esquema que implementamos (en el que se introducen en memoria los segmentos en este orden: TAREAS / PCB / TCBs), llego a la conclusión de que es **imposible** determinar si el algoritmo de FF o BF está funcionando correctamente, ya que en ambos casos se produce el mismo resultado, en este ejemplo en particular.

Por otro lado, luego de charlar con algunos grupos que presentaron el sábado pasado y llegaron a probar esta prueba (a diferencia de mi grupo que no tuvo tiempo de hacerlo), me comentaron que al eliminar segmentos de memoria y generar 2 o más huecos contiguos, se espera que los mismos *NO* se unifiquen de forma automática, sino que suceda solamente al compactar ❓ ❔ 

No voy a negar que esta extraña compartimentación de los huecos me trajo recuerdos del famoso chiste/acertijo:

> Un albañil tarda una hora en hacer un agujero en la pared. ¿Cuánto tarda en hacer medio agujero? :trollface:

De todas formas, quedando poco para la entrega ya, actualizamos en una nueva branch el esquema de segmentación para que funcione de esta forma.  
_Me gustaría saber cuál de los dos esquemas es realmente el que consideran como válido._

Dejo a continuación una serie de simulaciones que realicé, con la prueba propuesta en el enunciado, y otras variantes de la misma que sí permiten mostrar el correcto funcionamiento de FF/BF/Compactación con nuestro orden de segmentos.

## [Simulaciones](https://docs.google.com/spreadsheets/d/14L3RE_0WnMNefVDlfHr3s6hI-bhGClUQg2zGU-qtM6g/edit?usp=sharing) (usar mail @frba)

Espero que mostrar estas pruebas el día de la entrega sea suficiente para demostrar el funcionamiento del módulo.

---

Gracias por tu tiempo, un saludo.

**Comment by gastoncastineira** [comment]
Buenas

Te dejo la prueba de segmentación como la estamos evaluando

![image](https://user-images.githubusercontent.com/28161802/126396087-012cc005-12f3-455f-ab3f-6f67aedc6d90.png)

**Comment by GuidoDipietro** [comment]
Okey, la única diferencia es que guardamos los segmentos en otro orden y la prueba queda diferente a la de tu imagen. Por lo demás quedó claro qué esperan de los segmentos libres.

Lo que sí, no entiendo por qué no se cargan las tareas de la patota B. Veo solo 3 segmentos: uno de 8 (PCB?) y dos de 21 (TCBs?). ¿Me estoy perdiendo algo?

**Comment by iago64** [comment]
Buenas!

Las tareas de la Patota B las ves después de compactar, el cuadradito de 29 bytes en verde, decimos fin en esa línea porque ahí termina lo que nos importa de esta prueba 😉

Saludos.-

**Comment by GuidoDipietro** [comment]
Listo todo entonces, gracias y saludos
