### ISSUE TITLE
Consulta - Caracter fin de tareas

### ISSUE THREAD

**Issue by eguiggiaro** [sisoputnfrba/foro#2241]
Hola,

¿Cómo están?

A raíz del issue #2239 notamos una diferencia con el resultado esperado que puede complicarnos.

Nosotros usamos un caracter para separar tareas ( | ), y un caracter para el fin de tareas ( $ ) de la patota. Por ejemplo:

CEBAR_MATES;7;9;3
CEBAR_MATES;8;9;2
SALUDAR;9;9;1

En nuestra memoria se guarda como:

CEBAR_MATES;7;9;3|CEBAR_MATES;8;9;2|SALUDAR;9;9;1$

Eso nos da, por lo que veo, un caracter más de lo que están esperando. Liberar toda la lógica de estructuras administrativas para paginación y segmentación, para refactorizar este caracter nos genera un impacto grande y tenemos las pruebas relativamente estables.

¿Es un problema grave para la entrega final?

Gracias!!

**Comment by gastoncastineira** [comment]
A priori no se me ocurre cómo un byte más en segmentación ni paginación podría cambiarte el resultado de las pruebas? Corriste las pruebas y te dio distinto?

**Comment by eguiggiaro** [comment]
Hola Gastón,

En la imagen que subieron de cómo lo están evaluando (en el issue), vimos que, por ejemplo, consideran 99 como el tamaño de las tareas de una patota (SEG_PatotaA.txt). A nosotros nos da 100.

Saludos.

**Comment by gastoncastineira** [comment]
Sí, pero a lo que voy es que por ese byte extra no te rompe la memoria, ni te cambia el resultado de las pruebas porque la asignación FF o BF se sigue haciendo en los segmentos que dicen.
Mismo paginación, en la última página de los 3 procesos sobran unos bytes, por lo que tampoco tendría que ser un problema

**Comment by eguiggiaro** [comment]
Ok, genial entonces! seguimos por esta vía sin modificar este comportamiento. Es cierto, no modifica el resultado de las pruebas.
Muchas gracias!
