### ISSUE TITLE
Duda sobre SwapFile

### ISSUE THREAD

**Issue by jfloresmaquera** [sisoputnfrba/foro#2242]
Buenas noches, estamos con la parte de paginacion y teniamos un tema con el SwapFile, actualmente estamos guardando las cosas  en el archivo ya que lo vinculamos a un espacio de Memoria, pero a la hora de leerlo (por afuera del programa, ya que por dentro si lo podemos leer y cargar los datos guardados) nos aparece lo siguiente:

![image](https://user-images.githubusercontent.com/27295049/126413364-4e248e97-ad8b-41b0-bea1-23abf37b6c23.png)

Es entendible porque con paginacion algunos datos se van a romper a la hora de previsualizar,por ejemplo un int de 4 bytes se puede ver  repartido en 2 paginas diferentes, pero queria saber si a la hora de evaluacion se tendria en cuenta o si estamos implementando mal esta parte.

**Comment by iago64** [comment]
Buenas! Cómo va?

La forma que tienen de checkear el contenido de los archivos tanto el swap file, como tambien el superbloque del FS es utilizando el comando `hexdump` este comando lo que les facilita es ver en formato hexadecimal el contenido, y si ademas le agregan el parámetro `-C` si tienen algo que sea ASCII se los va a imprimir.

Saludos.-

**Comment by jfloresmaquera** [comment]
perfecto, muchas gacias!
