### ISSUE TITLE
Duda comunicacion discordiador-mongo

### ISSUE THREAD

**Issue by SantiagoOrlando29** [sisoputnfrba/foro#2243]
Buenas
Tengo dos preguntas simples: 
1. Cuando un tripulante le dice a mongo que agregue algo en la bitácora (por ejemplo un movimiento), tiene que recibir la confirmación de que se agregó a bitácora luego de que esto suceda o no es necesario?
2. Lo mismo pero con las tareas de E/S. Cuando mongo termina la tarea de E/S que le pidió el tripulante, le tiene que avisar que la termino?

Graciasss

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

1.- No es obligatorio, pero estaría bueno como para que se queden tranquilos que todo esta ok.

2.- En el discordiador uds van a bloquear al tripulante por mucho mas tiempo de lo que le va a llevar a i-Mongo procesar la petición, pero esto lo van a hacer después de tener el ACK de que esta todo ok.

Saludos.-

**Comment by SantiagoOrlando29** [comment]
Perdón Damian pero con la 2 me perdí. Decís que el bloquear tripulante se va a hacer después del ACK ? O sea que iría a bloqueado pero con la tarea de E/S ya terminada en i-Mongo?
Saludos

**Comment by iago64** [comment]
Buenas!

Efectivamente, de hecho lo comentamos en el video, uds tienen un ciclo de CPU que simula la petición al sistema (y por simpleza también es cuando le mandan el mensaje a i-Mongo que hace lo que tenga que hacer en el momento)

Saludos.-

**Comment by SantiagoOrlando29** [comment]
Ahhhhhhhhhh nunca lo había entendido así jajaja.
Genial quedó claro me parece. Mil gracias! Hasta el sábado creo!
