### ISSUE TITLE
Comportamiento de tripulantes en I/O durante sabotaje

### ISSUE THREAD

**Issue by HappelJavier** [sisoputnfrba/foro#2244]
Releyendo el enunciado, veo que aclararon que durante sabotaje los procesos en I/O dejan de ejecutar ciclos, 
1) Esos procesos quedan en la cola de I/O frenados hasta que se termine el sabotaje?
2) Puedo suponer que no se va a dar el caso que ocurra un sabotaje y no haya tripulantes disponibles? es decir, que justo estén todos en I/O.

Ya tendría implementado un sistema que manejaba esos casos, esperando a que finalice algún tripulante de I/O solo si no había otros disponibles, y después enviándolo a bloqueo por emergencia. 
3)Puede afectar a los test que realicen en las entregas, el hecho de no detener las I/O?

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

1.- Efectivamente, cuando arranca un sabotaje, se frenan todos los procesos de I/O que haya en curso, similar a cuando ~los esbirros del mal~ las impresoras se quedan sin tinta.

2.- Olvidate, las pruebas ya están publicadas, no somos tan jodidos para buscar esos casos.

Saludos.-

**Comment by HappelJavier** [comment]
ok,  gracias, cierro el issue.
