### ISSUE TITLE
[i-Mongo-Store] Distintos tipos de sincronización entre mensajes concurrentes

### ISSUE THREAD

**Issue by julchat** [sisoputnfrba/foro#2245]
Buenas, acá puliendo el código para las pruebas en i-mongo me topé con algunos problemas de sincronización, y después de haber leído el issue #2148, vengo acá para preguntar si los mutex que tengo pensado poner son válidos y que problemas pueden existir en la sincronización. 

### 📔 Citas del enunciado/videos

> Internamente, este archivo deberá ser mapeado a memoria y se le realizará una copia sobre la cual se trabajará para lograr simular la concurrencia y asincronismo en las bajadas a disco de los sistemas operativos reales. El tiempo de sincronización hacia el archivo físico de Blocks.ims será especificado por archivo de configuración. Cualquier otra implementación es motivo de desaprobación directa.

### 💭 Soluciones posibles
Bien, teniendo en cuenta lo del issue #2148 , y la noción de asincronismo y concurrencia que se menciona, queda más que claro que sería inválido hacer un mutex gigante cada vez que me pidan algo, entonces, a ver, de a pasos, que necesitaría sincronizar?
1) Para evitarme que dos hilos distintos que quieran pedir un nuevo bloque ocupen el mismo, acá creo que es fácil: sería necesario tener un mutex para el bitarray de superbloque
2) Podría pasar, en un entorno de multiprogramación de discordiador, que, por ejemplo, dos tripulantes distintos me quieran generar el mismo recurso simultáneamente. Esto podría llevar a varios problemas, entre ellos:
       a) Si uno tiene que generar 4 unidades del recurso, y el otro 2, antes de que llene el cuarto caracter y después del tercero, podría venir el segundo mensaje a pedirme generar esas 2 unidades, al darse cuenta que la última posición válida en el bloque es el tercer byte, comenzaría a escribir desde el cuarto byte, escribiendo dicha posición y también la quinta. Entonces en vez de terminar con 6 unidades como debería pasar, terminaste con 5.
      b) Alternativamente, podría tener un archivo de metadata de comida que me dice que tengo los bloques 1 y 2. El bloque 2 tiene 2 caracteres libres, y llegan dos mensajes de generar comida, uno con 3 unidades, y el otro con 5. Si yo no sincronizo bien la lectura del archivo de metadata, y no espero completamente a que el otro termine dde hacer la operación tanto sobre los bloques que aparecían en el archivo de metadata, y los nuevos ocupados, terminaría ocupando otro bloque nuevo para el otro mensaje, y hasta sobreescribiendo lo que el otro me escriba sobre el archivo de metadata.
Y acá se me complica un poco más, porque, ¿debería tener un mutex para cada tipo de "objeto" que involucre un archivo de metadata? (Inicialmente pensé en un mutex por cada bloque, lo que solucionaría los problemas del caso a), pero no los del b)) Que sepa la bitácora no podría tener esos problemas, porque no estarías ejecutando desde discordiador en 2 procesadores el mismo tripulante, y para no evitar una inconsistencia del tipo "Discordiador me dijo que loguee que me moví e inicié una tarea, pero como mi hilo de iniciar tarea se resolvió más rapido que el de moverse, en el log el orden está al revés", estarías tratando con una línea de log del tripulante al mismo tiempo, cosa que no se puede asegurar con los recursos. Entonces debería tener un mutex para comida, para oxígeno y para basura?

Y no sé, una foto. 
![image](https://user-images.githubusercontent.com/48997230/126437501-393e60ce-df29-4172-a3cf-89dddfdc57e3.png)

Gracias!

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Estaba por mandar el meme de mucho texto, pero esta bien, fuiste detallado en la explicación y eso esta bueno 😸 

1.- Si, esta bien, un mutex que te permita hacer operaciones de a 1 sobre el superbloque es completamente válido.

2.- Acá tus problemas de los archivos de recursos medio que no van a dársete porque acordate que a E/S entran de a 1, igual si queres asegurarte podes meter algún semáforo para hacer que las operaciones sobre los recursos se hagan de a 1.
El principal problema que tenes en el i-Mongo es la sincro del bitarray porque es por el que pelean archivos de recursos y las bitácoras que son las que mas van a estar ligando peticiones porque ante cada cosita que hacen los tripulantes lo escriben.

Saludos.-

**Comment by julchat** [comment]
clarisimo! Gracias!
