### ISSUE TITLE
Duda sobre traer información a memoria principal

### ISSUE THREAD

**Issue by mercedesmagnelli** [sisoputnfrba/foro#2246]
Buenas! Cómo va? Tenemos una duda en cuanto a la información a tratar cuando esta en Swap.

Sabemos que cada vez que necesitamos un bloque de información que no esta cargado en MP, traemos la pagina a la misma y la pagina que estaba cargada en MP pasa a "swapearse" en el frame donde estaba el anterior.
El problema que estamos teniendo cuando hacemos este swapeo es que tenemos que actualizar también la tabla de paginas que esta dentro de nuestra estructura administrativa de patotasPaginadas(es el nombre que le dimos a nuestro struct). Para este punto tenemos el PID y la pagina que tenemos que cambiar, pero para buscar la patotaPaginada en la lista de patotasPaginadas necesitamos comprar con el PID que ya tenemos en mano y asi acceder a la pagina en concreto del proceso. Pero qué pasaría si cuando queremos leer el PID del proceso no esta en MP sino en MV, tendríamos que hacer:

A. Traer la pagina a la memoria principal y actualizar los datos acorde a este cambio también en la tabla de paginas?
B. Leer directamente de memoria virtual el PID así evitamos cambiar los frames que estan dentro de la MP (seguramente esto no esta contemplado en las pruebas y nunca llegaríamos a tener los resultados esperados, más que nada porque es una problemática que surge en función de un diseño propio)
C. Tener un campo en la estructura de patotasPaginada en el cual tengamos el PID que está guardado en el pedazo de memoria que le corresponde a esa patota. Lo que pensamos que es medio raro de esto es que nunca se terminaría de acceder a la información del PID guardado en memoria (sea virtual o real) y el dato quedaría duplicado (en una estructura administrativa y en memoria) pero nos evitaría traer cosas a memoria que quizás no son necesarias de traer

Muchas gracias :)

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Sus estructuras administrativas pueden tener datos extra que les sirvan para buscar, por ejemplo el PID, con lo cual la opción C es válida.

Saludos.-

**Comment by mercedesmagnelli** [comment]
Genial, muchas gracias, agregaremos lo necesario. Saludos!
