### ISSUE TITLE
[Memoria - Paginación] Nuestra prueba no se adapta a los resultados esperados

### ISSUE THREAD

**Issue by matiasfdevecchi** [sisoputnfrba/foro#2247]
Buenas, realizando la prueba Memoria - Paginación tenes algo que difiere de lo esperado.

Partimos de lo siguiente:

Al iniciar el tripulante pide la primer tarea.

Paginas de la patota 1:
Pagina 0: Tareas + parte de PCB
Pagina 1: parte de PCB + TCB

Paginas de la patota 2:
Pagina 0: Tareas + parte de PCB
Pagina 1: parte de PCB + TCB

Paginas de la patota 3:
Pagina 0: Tareas
Pagina 1: Tareas
Pagina 2: Tareas + parte de PCB
Pagina 3: parte de PCB + TCB

Resultados esperados:
1. Al llegar las 3 patotas a Ready, Patota A y Patota B deberían estar en swap, y patota C ocupar la totalidad de los marcos
2. Ejecuta el tripulante de la patota A, reemplazando dos páginas de C
3. Ejecuta el tripulante de la patota B, reemplazando dos páginas de C
4. Ejecuta el tripulante de la patota C, reemplazando dos páginas de A
5. Esto continua hasta terminar la patota A
6. B no swapea más
7. C swapea la página de sus tareas por otra página con tareas

El primer punto, lo cumplimos, pero nuestro TP actua distinto del punto 2 al punto 4. Cuando ejecuta PA y ya tiene la tarea asignada, No cambia dos páginas sino que cambia una sola, para actualizar su estado, que sería la página 1 del proceso 1. Lo mismo ocurre con los demás.

Esto podría cambiar de dos maneras:
1. Que el tripulante pida todas sus paginas por más que quiera modificar una sola, lo cual no nos parece correcto porque es overhead innecesario para el sistema operativo.
2. Pidiendo la tarea al inicio del Quantum si no tiene una asignada, en vez de pedirla en la inicialización del tripulante. Sin embargo si pedimos al principio del inicio del Quantum, no va a finalizar cuando termine su ultima tarea, sino cuando le asignen un quantum más, va a pedir la tarea y se va a enterar que no tiene más tareas, desperdiciendo un quantum. A esta solución tendríamos que agregar la manera de saber si es la última tarea para no desperdiciar el quantum

Cual es el approach correcto, el que hicimos o el segundo?

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

La primer tarea deberían pedirla al momento de pasar a READY y no cuando se inicializan, con ese solo cambio ya resolverían el problema.
Después el resto de cambios se va dando solo porque casualmente cuadran el fin de Quantum con el fin de la tarea 😉 

Saludos.-

**Comment by matiasfdevecchi** [comment]
Buenas, gracias por la respuesta. No me queda del todo claro igualmente. Nosotros hacemos lo siguiente:
1. Inicia tripulante en new
2. Pasa a ready
3. Pedimos tarea
4. Ejecuta cuando le toque
5. Si termina tarea con este quantum dado, pide la siguiente. Si no tiene tarea, se va a exit
6. Vuelve al paso 4

Hay algun error en esto? Cuando tendría que pedir su segunda tarea?

**Comment by iago64** [comment]
Buenas!

El paso a ready en que momento se da, antes o después del iniciar la planificación? Porque creo que acá tenemos la diferencia.

Saludos.-

**Comment by matiasfdevecchi** [comment]
Lo hacemos antes. Tenemos que hacerlo despues?

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Ahora si me cierra todo.
Justamente la idea de que no este iniciada la planificación es que no hay movimientos entre las diferentes colas de planificación ni se ejecutan ciclos de CPU.

Saludos.-

**Comment by matiasfdevecchi** [comment]
Genial, y Expulsar tripulante tiene que esperar a iniciar la planificacion?

**Comment by ncoen97** [comment]
Creo que en ese caso no cambiaría mucho, pero al ser un pasaje entre colas de planificación hacia exit, deberían esperar al iniciar planificación.

**Comment by matiasfdevecchi** [comment]
Gracias! Lo tenemos así
