### ISSUE TITLE
Prueba Segmentación no obtengo mismo resultado

### ISSUE THREAD

**Issue by SantiagoOrlando29** [sisoputnfrba/foro#2249]
Buenas!
Yo de nuevo, perdonen la intensidad de esta semana jaja.
Me surgió la siguiente cuestión con la prueba de Segmentación. En nuestra implementación si hay 2 segmentos contiguos libres en memoria se unen automáticamente. Entonces en la prueba nunca se llega a hacer la compactación, nunca es necesaria, porque las patotas siempre tienen espacio disponible suficiente para guardar sus segmentos. En este issue #2210 un poco hablan de eso en el ítem 5, pero al menos en nuestro caso igualmente no se va a ver el funcionamiento de compactación (que igual estoy seguro que anda por mis pruebas caseras).
No se si está bien igual y lo hablaremos el sábado mismo, o si me recomiendan que elimine mi función de unir_espacios_contiguos_libres (que no debería ser difícil pero uno nunca sabe ajja).

Saludoss!

**Comment by SantiagoOrlando29** [comment]
Además me acabo de dar cuenta que en la prueba de Best Fit tampoco se nota ahi el funcionamiento de best fit, asi que supongo que voy a tener que eliminar mi función de unir_espacios_contiguos_libres. No queda otra creo.

**Comment by iago64** [comment]
Buenas! Cómo va?

Creo que este issue se parece mucho al issue #2239 donde incluso esta el Excel de lo que debería pasar en la prueba de segmentación en el TP, la diferencia es mínima entre los 2 algoritmos.

Por otro lado, los segmentos libres contiguos *no se tienen que consolidar cuando se liberan, solo se consolidan cuando se compacta la memoria*.

Saludos.-

**Comment by SantiagoOrlando29** [comment]
Okkk lo cambio entonces, no debería ser tanto problema.
Mil gracias por la ayuda de siempre!
Saludos
