### ISSUE TITLE
[i-Mongo-Store] Dudas sobre protocolo FSCK

### ISSUE THREAD

**Issue by julchat** [sisoputnfrba/foro#2250]
Buenas! Estamos desarrollando el FSCK para cerrar i-mongo, y nos surgieron algunas dudas del enunciado.
### 📔 Citas del enunciado/videos
Primero algo que quedó viejo de los sabotajes, por las dudas
> Cabe aclarar que los sabotajes se van a hacer de a un tipo a la vez.
1) De a un tipo involucra un sabotaje al mismo tiempo? O un tipo significa que podrían haber 3 sabotajes de bitmap al mismo tiempo, por ejemplo?

> Cantidad de bloques: Se debe garantizar que la cantidad de bloques que hay en el sistema sea igual a la cantidad que dice haber en el superbloque. Reparación: sobreescribir “cantidad de bloques” del superbloque con la cantidad de bloques real en el disco.
2) Lo que se va a modificar o corromper, va a ser lo que está en memoria que se utiliza en el módulo para obtener el tamaño del bloque? (En nuestro caso, un void*, el mismo que se utiliza para bajar a Superbloque.ims llamado superbloque tiene en el byte nro 4 la cantidad de bloques) O va a ser lo que está en el archivo? Porque si lo que se cambia es lo del disco, y por lo que dice en reparación debería tomar a ese tamaño como el posta, no significaría que debería modificar también las dimensiones del bitarray? Lo que implicaría que tenga que hacer un nuevo void* en el cual reserve la cantidad correspondiente en este caso nuevo.

Saludos y gracias!

**Comment by iago64** [comment]
Buenas! ¿Cómo va? (Juro que lo escribo cada vez que lo leen en los issues)

1.- 1 solo sabotaje a la vez, nos da demasiada paja sabotear las cosas, con lo cual, hacemos 1 y tiramos la signal 😄 

2.- Nosotros vamos a modificar el archivo de superbloque y les vamos a tirar la signal. Aca depende muchísimo de su implementación, si lo tienen levantado con `mmap()` (que entre nos es la forma mas facil de tener el bitmap tambien) ese cambio se les va a reflejar en la memoria, con lo cual no van a safar de tener que usar el tamaño del archivo `Blocks.ims`. Si no lo tienen con `mmap()` es mas fácil porque ahí, pueden abrir el archivo, ver que les mandamos fruta y lo pisan con lo que tienen en memoria y nos mandan a arrancar otro lobby :sunglasses:.

Saludos.-

**Comment by julchat** [comment]
>  si lo tienen levantado con mmap() (que entre nos es la forma mas facil de tener el bitmap tambien) ese cambio se les va a reflejar en la memoria, con lo cual no van a safar de tener que usar el tamaño del archivo Blocks.ims
Entonces escribiríamos en la posición de la cant de bloques en el mmap el valor nuevo del archivo y usaria como nueva cantidad de bloques el tamaño del blocks.ims / block_size? O también tendría que acortar / alargar el bitarray y generar un nuevo block.ims con la nueva cantidad especificada?

**Comment by iago64** [comment]
Aloha!

Ojo, el FSCK lo que busca es corregir el sabotaje, la "cagada" nos la vamos a mandar nosotros (o uds en representación nuestra) al modificar el archivo desde la terminal con `hexedit` o algún otro programa de esos medio flasheros que tiene linux que conozca el ayudante que los evalue.

Respecto al de la cantidad de bloques, vamos a cambiarles el Block_count del superbloque, no se, de un 100 que tenian originalmente le vamos a mandar un 40 y como el block_size no cambia van a tener que calcular basándose en Blocks.ims la cantidad de bloques que tenían originalmente, por ejemplo, si originalmente tenian 100 bloques de 128 bytes cada uno, el size de blocks.ims va a tener que ser de 12800, con lo cual, si dividen el size de blocks.ims por el tamaño de bloques, les va a dar que el valor original de block_count es de 100 y no 40 como esta figurando.

Saludos.-
