### ISSUE TITLE
[Memoria - Segmentación] Bloques libres

### ISSUE THREAD

**Issue by matiasfdevecchi** [sisoputnfrba/foro#2251]
Buenas, realizando las pruebas de segmentación encontramos que según lo descripto en las pruebas, si se liberan dos segmentos contiguos, siguen siendo dos segmentos distintos y no se podrán utilizar juntos, hasta que se compacte.

Ejemplo: (memoria de 16b)
Segmento 1 - Libre - Address: 0x00 - Size: 5b
Segmento 2 - Libre Address 0x05 - Size 5b
Segmento 3 - Ocupado - Address 0x0A - Size 5b

Si quiero agregar un segmento de 9b, según las pruebas, voy a tener que compactar porque no puedo utilizar Segmento 1 y 2, ya que aunque estén libres, esta segmentado.

Como resolvimos el tp nosotros (si se libera un segmento contiguo a un espacio libre de la memoria, estos se unificarian generando un unico bloque libre, tomando el ejemplo anterior, desde 0x00 hasta 0x09 tendriamos un espacio de 10b libre). No funcionaría así segun lo explicado en la teoría?

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Ojo, porque el consolidar no es 100% obligatorio en segmentación, es algo que se puede habilitar o no y de hecho en este TP optamos por no usarla, asique deberían comentar esa parte de consolidar la memoria 😄 .
En donde es obligatorio es en buddy system, pero por suerte ese esquema de memoria no entro en este TP.

Saludos.-

**Comment by matiasfdevecchi** [comment]
Hola, como estas? Gracias por la respuesta.

Una consulta más, en el dump tiene que ponerse también los bloques libres? Como en el ejemplo no estaban, no lo hicimos. Pero pareciera que si segun las pruebas

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Seria un re punto si lo hacen porque así es mas fácil y no tenemos que andar calculando en el momento las posiciones libres 😉 , pero no lo pusimos en el enunciado para segmentación, así que de ultima tardamos mas en corregirles el tp 😞 

Saludos.-

**Comment by matiasfdevecchi** [comment]
Dale, lo agregamos. Gracias!

**Comment by matiasfdevecchi** [comment]
Hola @iago64, como estas? Abro el issue porque es sobre la misma prueba. 
Por lo que vemos, la aprueba asume que primero se guarda el PCB y luego las tareas. Sin embargo nosotros por comodidad para el manejo de la dirección lógica decidimos que el segmento 0 (el primero en ser cargado) es el de tareas (ya que no vimos ninguna lineamiento al respecto), y por ende, las pruebas no evaluan adecuadamente el comportamiento de First Fit y Best Fit. Podemos dejarlo de esa manera y realizar otro tipo de prueba para mostrarles el correcto funcionamiento o está mal como lo hicimos?

**Comment by ncoen97** [comment]
Buenas, teniendo en cuenta que eso no está especificado en el enunciado, lo pueden dejar así. Lo único tengan en cuenta que van a tener que explicarlo en la entrega para poder verificar que funciona correctamente.
Saludos!
