### ISSUE TITLE
[i-MongoStore] Duda sobre sabotaje Blocks

### ISSUE THREAD

**Issue by SantiagoAspres** [sisoputnfrba/foro#2252]
### 📔 Duda Sabotaje

Viendo el Issue #2205, nosotros lo implementamos solo teniendo en cuenta que nos mueven los elementos de la lista y hacemos la recuperación del archivo tal cual como ahí decían Nicolas y Matias, pero.. ¿Hay que también tener en cuenta el caso de que me agreguen un bloque que no pertenece a mi lista de bloques o que me eliminen algún bloque?

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Por suerte es algo que dijimos en el [video del módulo i-mongo store](https://www.youtube.com/watch?v=ve2kUJu9cRs&ab_channel=UTNSO) y no, simplemente les vamos a cambiar el orden.
Si agregamos o sacamos bloques, va a ser un sabotaje de BLOCK_COUNT 😉 

Saludos.-

**Comment by SantiagoAspres** [comment]
> Buenas! ¿Cómo va?
> 
> Por suerte es algo que dijimos en el [video del módulo i-mongo store](https://www.youtube.com/watch?v=ve2kUJu9cRs&ab_channel=UTNSO) y no, simplemente les vamos a cambiar el orden.
> Si agregamos o sacamos bloques, va a ser un sabotaje de BLOCK_COUNT 😉
> 
> Saludos.-

Perfecto entonces, pero en el sabotaje de block_count justamente me sabotean el valor de block_count, no la lista de bloques, correcto?

**Comment by iago64** [comment]
Buenas ¿Cómo va?

Si señor, así de sencillito, cambiamos el valor de Block_Count y uds tienen que actualizarlo con lo que diga BLOCKS 😄 

Saludos.-

**Comment by SantiagoAspres** [comment]
Estamos ready entonces! gracias
