### ISSUE TITLE
Problemas para retornar cosas por conexión

### ISSUE THREAD

**Issue by matiaspar2000** [sisoputnfrba/foro#2253]
Buenas, estamos teniendo un problema a la hora de retornar información por conexión. En ningún caso lo hicimos andar pero tomo el ejemplo del INICIAR_PATOTA. De discordiador se envían a memoria los datos de la patota, esperamos que el HQ retorne si hay o no lugar en memoria en forma de un uint32_t.

Hasta ahora la patota se envía correctamente, HQ recibe y deserializa los datos, consulta si hay lugar, serializa la respuesta y la envía sin problemas. Del lado de discordiador se recibe el paquete, se lee el código de operación bien y luego se llama a la función para deserializar.  En deserializar se hace un recv para obtener el size del buffer el cual lee bien.

El problema está cuando se hace el recv para obtener el contenido del buffer. Lo que sucede es que se bloquea el proceso y permanece así hasta que uno finaliza el programa. Cuando ingresamos el comando para finalizar el programa recién ahí continúa la deserialización pero devolviendo un valor cualquiera en vez del int32 enviado desde HQ y luego tira un segmentation fault cuando quiere leer el siguiente código de operación (el cual no tendría por qué leer ya que no se envió nada). 

### 📝 Código relevante

```c
uint32_t recibir_hay_lugar(int socket_cliente){
	void* nrecibir_buffer(int* size, int socket_cliente){
		void* buffer;

		recv(socket_cliente, size, sizeof(int), MSG_WAITALL);
		buffer = malloc(*size); //aca si hago un printf de buffer size me da 4 lo cual estaría bien
		recv(socket_cliente, buffer, *size, MSG_WAITALL);
		return buffer;
	}

	int size;
	int desplazamiento = 0;
	void* buffer;
	uint32_t dato;

	buffer = nrecibir_buffer(&size, socket_cliente);
	memcpy(&(dato), (buffer+desplazamiento), sizeof(uint32_t));
	desplazamiento += sizeof(uint32_t);

	printf("VALOR RECIBIDO: %d\n", (uint32_t)(dato));
	free(buffer);
	return dato;
}
```
		
Cosas que testeamos y vimos que andan bien: 

1. Lo enviado y el buffer size del lado de HQ son los que corresponden
2. La conexión suponemos que estará bien ya que el código de operación llega sin problemas
3. nrecibir_buffer se usa también en mi-ram-hq y anda sin problemas

Otra cosa que nos dimos cuesta es que si en recv del contenido del buffer ponemos sizeof(buffer) en lugar de *size el error es distinto. En este caso no se bloquea en el segundo recv y continúa la deserialización también devolviendo un valor cualquiera y tirando un segmentation fault cuando uno quiere finalizar el programa
 
```c
void* nrecibir_buffer(int* size, int socket_cliente){
		void* buffer;

		recv(socket_cliente, size, sizeof(int), MSG_WAITALL);
		buffer = malloc(*size); 
		recv(socket_cliente, buffer, sizeof(buffer), MSG_WAITALL);
		return buffer;
	}
```

**Comment by RaniAgus** [comment]
¡Buenas! Dos cuestiones:

1)
```c
recv(socket_cliente, size, sizeof(int), MSG_WAITALL);
```
En vez de _rellenar_ el contenido al que apunta `int* size`, están _pisando_ ese puntero con lo que devuelve `recv()`. En consecuencia, luego al hacer `malloc(*size)` están leyendo una dirección de memoria que probablemente no exista. Para más info les recomiendo leer este comment: https://github.com/sisoputnfrba/foro/issues/2224#issuecomment-882803512

2)
```c
recv(socket_cliente, buffer, sizeof(buffer), MSG_WAITALL);
```
El operador `sizeof` opera con tipos de dato (no con punteros), o sea que no devuelve el tamaño de un bloque de memoria reservado con `malloc()`, sino el tipo de dato de la variable en cuestión (o sea, un puntero). Por lo tanto, en las VMs de 32 bits siempre va a retornar `4`. Esa es otra de las razones por las cuales nosotros recibimos el tamaño del buffer: para luego saber hasta dónde recibir :)

Saludos

**Comment by matiaspar2000** [comment]
Ok, entendido el punto 2. 
Sobre el 1, entendido que devuelve malloc y entendido que devuelve recv. Ahora, el problema sigue siendo que no se que tengo que hacer, porque del lado de HQ ese recibir_buffer tal y como está funciona bien al recibir cosas como patotas o cambios de estado, mientras que del lado de discordiador sigue bloqueándose en el segundo recv hasta que uno finaliza el proceso y recién ahí devuelve basura. 

El size del buffer lo recibe correctamente, asigna un malloc del tamaño que corresponde que en este caso es 4 y después se bloquea, mas allá de si hubiera o no un error en malloc(*size) no debería igual devovler algo del recv ya que quedan cosas por leer? 
Y finalmente lo que devuelve, que tampoco estaría entendiendo por que no lee correctamente el int32 que se envía.

```c
void* recibir_buffer(int* size, int socket_cliente)
{
	void* buffer;

	recv(socket_cliente, size, sizeof(int), MSG_WAITALL);
	buffer = malloc(*size);
	recv(socket_cliente, buffer, *size, MSG_WAITALL); //aca se bloquea

	return buffer;
}
```

```
>INICIAR_PATOTA 1 tareas.txt
[INFO] 17:19:33:877 discordiador/(5862:5862): 0 - Iniciando patota 
CODIGO: 1 - LLEGADA
 //despues de leer el codigo se bloquea el hilo de la conexión
[INFO] 17:19:35:878 discordiador/(5862:5862): 0 - Patota iniciada 
FIN
[INFO] 17:19:42:244 discordiador/(5862:5862): Discordiador finalizado correctamente
Buffer recibido
VALOR RECIBIDO: 117440512
Segmentation fault (core dumped)
```

**Comment by RaniAgus** [comment]
Sobre el 1, revisándolo bien, me equivoqué (mil disculpas, mala mía): recv() tiene como segundo parámetro el puntero hacia dónde _rellenar_ el stream que se recibe por red (se estaría pisando si recibieras `&size`, pero no es el caso). Lo edito para no confundir a alguien que se encuentre con el issue.

Necesitaría ver el código de Mi-RAM desde el cual se está haciendo el `send()` para contar con más contexto y poder probarlo, quizás nos estemos perdiendo de algo.

De paso, si podés agregarle un `mem_hexdump()` de lo que se está enviando con `send()` para asegurarnos de que se esté enviando bien sería un golazo.

**Comment by matiaspar2000** [comment]
Buenas, mientras te estaba pasando el código descubrí el error, igualmente lo paso por si quieren hacer algún comentario o para alguien que lea el issue

```c
uint32_t a = 1; //1 si hay lugar 0 si no
t_buffer* buffer = serializar_test(a);
t_paquete* paquete = crear_mensaje(buffer, 1);
enviar_paquete(paquete, conexion);
```

Serialización
```c
t_buffer* serializar_test(uint32_t dato){
	t_buffer* buffer = malloc(sizeof(t_buffer));
	void* stream = malloc(sizeof(uint32_t));
	int desplazamiento = 0;

	memcpy(stream + desplazamiento, &dato, sizeof(uint32_t));
	desplazamiento += sizeof(uint32_t);

	buffer->size = desplazamiento;
	buffer->stream = stream;
	return buffer;
}
```
El armado del paquete
```c
t_paquete* crear_mensaje(t_buffer* buffer, op_code codigo){
	t_paquete* paquete = malloc(sizeof(t_paquete));
	paquete->codigo_operacion = codigo;
	paquete->buffer = buffer;
	return paquete;
}
```
Enviar
```c
void enviar_paquete(t_paquete* paquete, int socket_cliente){
	int bytes = paquete->buffer->size + 2*sizeof(int);
	void* a_enviar = serializar_paquete(paquete, bytes);
	send(socket_cliente, a_enviar, bytes, 0);
	free(a_enviar);
}
```
Serialización de paquete
El error estaba acá en el primer memcpy, ya que estabamos poniendo sizeof(int) para el código de operación lo cual hacía que la cantidad de bytes sea distinta a la que esperaba recibir. 
```c
void* serializar_paquete(t_paquete* paquete, int bytes)
{
	void * msg = malloc(bytes);
	int desplazamiento = 0;

	memcpy(msg + desplazamiento, &(paquete->codigo_operacion), sizeof(uint8_t));
	desplazamiento+= sizeof(uint8_t);
	memcpy(msg + desplazamiento, &(paquete->buffer->size), sizeof(int));
	desplazamiento+= sizeof(int);
	memcpy(msg + desplazamiento, paquete->buffer->stream, paquete->buffer->size);
	desplazamiento+= paquete->buffer->size;

	return msg;
}
```
Muchas gracias por la ayuda

**Comment by iago64** [comment]
Aloha! ¿Cómo va?

Solo para quedarme tranquilo en la recorrida, el problema esta resuelto? 
Quedo algo pendiente o podemos cerrar el issue y que cualquiera que tenga un problema similar lo encuentre por el buscador?

Saludos.-

**Comment by matiaspar2000** [comment]
Problema resuelto, muchas gracias y cierro el issue
