### ISSUE TITLE
Duda informar sabotaje a discordiador

### ISSUE THREAD

**Issue by SantiagoOrlando29** [sisoputnfrba/foro#2254]
Holaa.
Nos surgió la siguiente cuestión:
La información del sabotaje, mongo se la puede enviar en cualquier momento a discordiador. Entonces del lado de discordiador no sabemos como recibirla porque si tenemos un recv() para recibir el sabotaje se nos superpone con el recv() del OBTENER_BITACORA (o sea si hago OBTENER_BITACORA lo que reciba puede ir al recv() del sabotaje y no al del OBTENER_BITACORA ). Se nos ocurren estas opciones:
1. Usar 2 sockets distintos entre discordiador y mongo, uno para sabotaje, otro para OBTENER_BITACORA (pero nos suena raro).
2. Hacer de alguna manera (que tendríamos que investigar) el recv() del sabotaje no bloqueante. Entonces que esté siempre esperando un sabotaje (no se si generaría espera activa), pero que si pongo OBTENER_BITACORA de alguna manera decirle que hasta que el OBTENER_BITACORA no reciba lo que quiere en su recv(), el recv() del sabotaje no esté "activo" (que no quiera recibir nada digamos).

Espero que se haya entendido porque se que puedo ser bastante choto explicando jaja.
Saludos!

**Comment by RaniAgus** [comment]
¡Buenas! 
a. ¿Por qué les suena raro la opción 1? Al ser dos flujos de mensajes distintos es súper aconsejable utilizar sockets distintos.
b. ¿Necesitan tener un socket abierto constantemente para OBTENER_BITACORA? Si lo que buscan es ser más eficientes en el uso de recursos, pueden considerar abrir uno cada vez que se reciba ese mensaje por consola y luego de recibir la info cerrarlo.

Saludos

**Comment by SantiagoOrlando29** [comment]
Sorry colgué en responder. Mil gracias ya pudimos solucionarlo me parece.
Saludos!
