### ISSUE TITLE
Problemas de estabilidad general

### ISSUE THREAD

**Issue by tostrovsky** [sisoputnfrba/foro#2255]
Buenas. Nos encontramos con un inconveniente con mi grupo al correr las pruebas de estabilidad general.
Cada vez que un tripulante se comunica con miRam, abre un socket, le envia un paquete y lo cierra. MiRam lo recibe, levanta un hilo, ejecuta la instrucción pertinente y este finaliza con EXIT_SUCCESS. 
Aclaro que esto lo preguntamos una vez a algun ayudante, e implementamos 1 peticion == 1 socket con su aval.
Va todo bien pero llegado un punto, después de aproximadamente 380 requests, miRam deja de levantar hilos para atender las peticiones. Esto lo logramos trackear despues de arduos dias de debbuging y loggeo.
Mi teoría es que los algoritmos de miRam que ejecutan las instrucciones son bastante imperformantes, generan mucha información que los pthread_create() no soportan, protesta y deja de levantarlos. Es posible esto, o es que pthread tiene un limite para levantar hilos pesados? Puede ser? Nos conviene hacer 1 tripulante == 1 socket? Se puede levantar el límite de informacion que procesan los thread? 
Aclaracion: con el resto de las pruebas estamos bien, andan, porque no involucran tantos requests. abrazo

**Comment by ncoen97** [comment]
Buenas, primero estaría bueno algo más de información. Como están creando los hilos para las requests? les están haciendo detach? Qué pasa cuando "deja de levantar hilos"? Devuelve algún código de error? Tira seg fault? Intentaron correrlo con valgrind?

**Comment by tostrovsky** [comment]
cada vez que un tripulante hace una peticion, envia un mensaje a mi ram. él lo escucha, y crea un hilo instantaneamente(dentro de un while) atendiendo la instruccion.

no hacemos detach, los hilos terminan automatandose al llegar al return EXIT_SUCCESS;.
cuando deja de levantar hilos, no atiende las peticiones, el discordiador sigue su vida hasta que los tripulantes piden la proxima tarea. como no levanta hilos para buscar la proxima tarea, no le contesta. el tripulante se queda en deadlock esperando la respuesta que nunca llega.

no devolvian codigos de error, que nosotros sepamos. no tira ningun error, ni segfault ni nada. simplemente deja de levantar hilos. Recibe las peticiones pero ignora al pthread_create().

ya mismo estamos intentando correrlo con valgrind, en el comentario de abajo te digo lo que pasa

**Comment by tostrovsky** [comment]
bueno, recien lo testeamos con valgrind y no nos da mas informacion. Pasa lo mismo siempre

**Comment by gastoncastineira** [comment]
2 cosas

> los hilos terminan automatandose al llegar al return EXIT_SUCCESS;.
1. Eso no funciona así. Para nada. Si bien es cierto que el hilo la funcionalidad de un hilo termina al llegar al return al final de su main (osea, la función que le pasas al create), el sistema operativo no limpia solito ese hilo, porque justamente _tiene un valor de retorno, el cual podrías querer_. Como comenta Mauro en [la charla de hilos](https://www.youtube.com/watch?v=G8PD6wauMeY), join espera a que termine ese hilo y te asigna a la variable que le digas lo que sea que retorne. Detach dice "ok, no me interesa ese valor. Matame el hilo en paz cuando acabe". Cualquier otra cosa es leak
2. Algo relacionado conceptualmente con lo anterior. A todos esos sockets de Mi-RAM, ¿les están haciendo close? Los sockets no son infinitos, y si llegan a un límite y nunca manejan los errores de la función `socket`, es probable que no se enteren nunca si llegaron al límite de file descriptos del SO

**Comment by tomi-iglesias** [comment]
Buenas, estuvimos probando y logramos algunos avances agregando los detach/join (probamos con ambas), sin embargo volvemos a un "deadlock", pero al cerrar mi ram nos tira este error: Linux: libgcc_s.so.1 must be installed for pthread_cancel to work..., Alguna sugerencia?

**Comment by iago64** [comment]
Buenas, ¿Cómo va?

Corrieron su TP con Helgrind? Si lo hicieron, que les devolvió?
Porque si están sincronizando mal y quedan en un deadlock, va a ser mas fácil que lo vean con Helgrind que haciendo pruebas a ciegas.

Saludos.-

**Comment by tostrovsky** [comment]
buenas, ya pudimos solucionar el problema. abrazo a todos los involucrados

**Comment by ncoen97** [comment]
Buenas, estaría bueno si pueden dejar una mini descripción del problema que identificaron y cómo lo solucionaron por si alguien en el futuro tiene un problema similar.
Saludos!

**Comment by tomi-iglesias** [comment]
Luego de ver el video de Threads que compartio gaston, nos dimos cuenta que no estabamos detacheando/eliminando recursos de los threads. A raiz de eso, hicimos un pthread_detach luego del create, cosa que cuando termine, elimine los recursos. Saludos y muchas gracias!
