### ISSUE TITLE
Duda a la hora de realizar un sabotaje

### ISSUE THREAD

**Issue by FranciscoAnnoni** [sisoputnfrba/foro#2256]
Buenas tardes, mi duda surge a la hora de simular un sabotaje porque como los tripulantes están escribiendo todo el tiempo sobre el archivo Oxigeno.ims, al modificar el size del mismo en plena ejecución hay un seg fault, por lo cual para poder realizar el sabotaje necesariamente hay que pausar planificación para que ningún tripulante utilice dicho archivo, con la planificación pausada y habiendo nidificado el size, ahí si activamos el protocolo de recuperación de sabotaje y luego de esto, volvemos a ejecuta la planificación para que sigan ejecutando, es correcto esto??
O como deberían ser los sabotajes, tendría que poder modificar el archivo en plena ejecución??.

**Comment by iago64** [comment]
Buenas ¿Cómo va?

¿Leíste el documento y los scripts de pruebas?
Justamente las pruebas de FSCK, no tocan los archivos de recursos para poder hacer los sabotajes, son todas tareas de CPU.

Saludos.-

**Comment by iago64** [comment]
@FranciscoAnnoni Te quedo alguna duda? hay algo que podamos aclarar al respecto?

Saludos.-
