### ISSUE TITLE
Duda prueba segmentacion - compactacion 

### ISSUE THREAD

**Issue by sazcoaga** [sisoputnfrba/foro#2257]
![image](https://user-images.githubusercontent.com/62355034/126715689-95d74a6d-14e9-4c8b-9709-816f677f4b89.png)

Buenas, tenía una duda con la prueba de segmentación. Dice como se muestra en la foto "dejar que todos los tripulantes terminen las tareas y despues mandar un signal para compactacion". Había preguntado una vez si cunado un tripulante terminaba su tarea debía sacarlo de memoria y me respondieron que sí (lo mismo con la patota si ya todos terminaron). Tendría entonces sentido hacer una compactación? Si espero que todos los tripulantes terminen sus tareas ya no tendría nada en memoria. O estoy entendiendo mal el enunciado? 
Muchas gracias

**Comment by Nachiten** [comment]
Buenas, como estas?

Me parece que el problema que estas teniendo es que estas suponiendo que al liberarse dos segmentos de memoria contiguos estos se consolidan (juntan en uno solo) automáticamente. Esto NO pasa. Por lo tanto, al terminar y haber liberado toda la memoria lo que en realidad te va a pasar es que vas a tener varios segmentos libres en la memoria (pueden estar contiguos o no), pero no vas a tener un solo cacho de memoria todo junto. Vas a tener segmentos libres que estarán fragmentados en base a donde estaban los segmentos que se liberaron.

El único momento en el que se "modifican" (cambian de lugar o cambian su tamaño) los segmentos en este TP es cuando se compacta. Esto quiere decir que sí tendría un efecto esta ultima compactación, ya que básicamente juntaría todos los segmentos libres en uno solo. Y este efecto se debería poder ver en el Dump (razón por la cual se pide este Dump antes y después de este proceso).

Espero esto te sirva, saludos!

**Comment by sazcoaga** [comment]
Hola nacho, gracias por la respuesta. Entiendo lo que me decís. El unico problema es que en el momento en que pregunte como hacerlo, un ayudante me sugiio tener una estructura auxiliar con todos los segmentos ocupados. De modo que cuando necesito saber que segmento esta libre, lo calculo a partir de los ocupados (no lo almaceno en una tabla de segmentos libres). Por ende, si sigo borrando tripulantes hasta que ya no queda ninguno, me quedara como que tengo un solo segmento libre del tamaño de la memoria. Tenés alguna sugerencia sobre como seguir desde aca? Si eso es invalido o como corregir.

**Comment by sazcoaga** [comment]
![image](https://user-images.githubusercontent.com/62355034/126719331-7c56bc7a-2bc7-479d-8830-5b34367568ab.png)
 Ademas, tengo la duda de como se veria en el dump. Ya que por lo que pusieron en el archivo tengo entendio que tienen que imprimirse los segmentos que sí fueron asignados a alguna información.

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

La idea de tirar el DUMP antes y después de compactar es primero ver todos los segmentos vacíos y después de compactar tener 1 solo vacío.

Saludos.-

**Comment by iago64** [comment]
@sazcoaga Te quedo alguna duda? Hay algo en lo que tengamos que afinar detalles?

Saludos.-

**Comment by RaniAgus** [comment]
Cerramos por inactividad, cualquier cosa pueden reabrir el issue 🚀

**Comment by sazcoaga** [comment]
Si, vi lo que pusieron y lo pude entender. Gracias (recien veo la mencion)
