### ISSUE TITLE
Resolución 800x600 no se puede cambiar

### ISSUE THREAD

**Issue by gchimento** [sisoputnfrba/foro#2258]
Buenas, desde hace unos días estoy teniendo un problema con la VM. Se me puso la resolución en 800x600 y no me deja cambiarlo. Probé reinstalar las Guest Additions y me tiraba este error. Así que borré la VM para instalar todo de 0 y me sigue diciendo lo mismo.

![image](https://user-images.githubusercontent.com/28161872/126716479-04510697-dc77-4a9b-842f-c05779ad4e20.png)

No sé si el problema será de las GA, aclaro por las dudas. Lo último que hice antes de que me empezara a salir el error fue intentar compartir una carpeta con el host, desconozco si influye en algo.

Alguna idea? Gracias.

**Comment by iago64** [comment]
Buenas ¿Cómo va?

Podrías pasar la config que tenes del adaptador de video? Porque no tengo mucha info para poder ayudarte 😞 y solo puedo decirte que intentes si desde el menu de ver tenes en la part de pantalla virtual para cambiar la resolución.

![image](https://user-images.githubusercontent.com/1622109/126722196-4031d902-d101-4a5f-a4fd-73fe37128300.png)

Saludos.-

**Comment by gchimento** [comment]
Buenas. Creo que te referís a esto (las otras dos pestañas tienen "Habilitar servidor" sin el tick)

![image](https://user-images.githubusercontent.com/28161872/126725380-77089386-4858-4dec-a330-d6b2a2c5758a.png)

Y en Ver -> Pantalla virtual 1 me aparece marcado 800x600 y todos los demás en gris, como bloqueados. Antes tenía habilitados los otros pero cuando los seleccionaba no cambiaba nada, y si volvía a entrar al menú seguía marcado 800x600.

Gracias!

**Comment by iago64** [comment]
Buenas!
Esa misma! 😃 
Fijate que tenes 16mb asignados, subilo al mango y ahí debería dejarte expandirlo sin problemas.

Saludos.-

**Comment by gchimento** [comment]
El tema es que sigo sin tener las GA, porque nunca pude volver a instalarlas. Ya probé reinstalando VirtualBox, borrando y descargando de nuevo la VM de Lubuntu desde utnso y siempre me tira el mismo error.

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cuál es el error? Lo que leo ahí es que dice:
```
VirtualBox Guest Additions: Running kernel
modules will not be replaced until the system is
restarted
```
Por lo que deberían estar instaladas, solo que hace falta reiniciar para aplicar los cambios.

Si sigue sin funcionar el ajuste de pantalla, podés probar cambiar el controlador de video a VBoxVGA, o fijar un tamaño de pantalla mayor a mano como se explica en #2015

Saludos

**Comment by gchimento** [comment]
Buenas. No me deja cerrando sesión y volviendo a iniciar. Probé usando el modo fullscren (host + F) y también modo ventana maximizado, ambos con el downgrade a la versión 6.0.18.

Por las dudas, cuando inicio la VM me tira estos errores:

![1](https://user-images.githubusercontent.com/28161872/126807566-9fde83f8-c6fd-4c84-a19e-2d12aa388a34.png)
![2](https://user-images.githubusercontent.com/28161872/126807575-bda17a0e-009f-4ea7-bcf7-7fc784fae03a.png)

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Consulta respecto al tema del disco, como lo tenes configurado? porque ese error de iSCSI me suena un toque raro.

Saludos.-

**Comment by gchimento** [comment]
Buenas, el disco lo descargué y extraje a una carpeta en mi sistema y puse esto al crearla

![image](https://user-images.githubusercontent.com/28161872/126909761-6f698590-b5ba-442f-aef7-9dbfa08477f3.png)

Esto es desde configuración

![image](https://user-images.githubusercontent.com/28161872/126909785-fb5a79a8-a561-4e9e-8f92-07bbd3f4ff51.png)

No pude solucionarlo pero instalé VBox 5.2 y pude instalar todo desde 0 sin errores al menos, así que si quieren cerrarlo está bien.

**Comment by iago64** [comment]
Buenisimo, entonces nos quedamos tranquilos que pudiste tener la VM funcionando bien.
