### ISSUE TITLE
Dumpear al recibir un signal

### ISSUE THREAD

**Issue by int0x80-sys** [sisoputnfrba/foro#2259]
Buenas.

Tenemos un problema con el tema del Dump.

Básicamente cuando queremos dumpear, mandamos un `SIGUSR2` a la memoria. Al recibir el signal, se llama a una función que crea un t_log para logear la info que se pide.

El problema es que no se puede crear el archivo. El error que tira es:

`Cannot create/open log file: No such file or directory`

¿Puede ser que haya inconvenientes al intentar crear un archivo desde un sighandler?

Saludos.

**Comment by int0x80-sys** [comment]
Buenas. Descubrí el error. Comento que es lo que pasaba por si a alguien mas le ocurre.

Básicamente, nosotros al crear el Dump, le seteamos el nombre de la siguiente manera:

```C
        char* timestamp = temporal_get_string_time("%d/%m/%y-%H:%M:%S");
        char* dump_path = string_from_format("Dump_<%s>.dmp", timestamp);

        t_log* dumper = log_create("Dump.dmp", "DUMP", false, LOG_LEVEL_INFO);
```

El problema parece estar con los */* que pusimos. Cambiamos los */* por *|* y funciono.

Saludos 🚀

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va?

Justo estaba revisando el problema, así que ahora con esa info les paso los pasos que seguí para que poder diagnosticar por qué ocurrió así ya queda :P

- `log_create()` [usa `txt_open_for_append()`](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/log.c#L64-L70), el cual [usa `fopen()`](https://github.com/sisoputnfrba/so-commons-library/blob/834e821204f3e0a54f7e70b40250047e65d2a493/src/commons/txt.c#L23).
- Ahí en `log_create()` también hay un `perror("Cannot create/open log file")`, por lo que lo que se imprime es un código de error de [`errno`](https://man7.org/linux/man-pages/man3/errno.3.html) convertido a string con [`strerror()`](https://man7.org/linux/man-pages/man3/strerror.3.html).
- Buscando la [tabla de códigos de error de errno](https://www.thegeekstuff.com/2010/10/linux-error-codes/), "No such file directory" tiene como código de error `ENOENT`.
- `fopen()`, según el [manual](https://man7.org/linux/man-pages/man3/fopen.3.html), dice, entre otras cosas, lo siguiente:

> ENOENT The mode string begins with 'w' or 'a' and **a component of the path prefix of
              pathname does not name an existing file**, or pathname is an empty string.

Al parecer, `fopen()` puede crear un archivo si no existe pero no puede crear todos los directorios hasta llegar a él. Como el path, por ejemplo, `~/Dump_23/07/` no existe, entonces arroja este error.

¡Saludos!
