### ISSUE TITLE
[MEMORIA - PAGINACIÓN] ¿Cuando solicitar proxima tarea?

### ISSUE THREAD

**Issue by matiasfdevecchi** [sisoputnfrba/foro#2260]
Buenas, continuando con el issue #2247 , ya hicimos los cambios sugeridos, pero aún no tenemos el mismo resultado porque nuestros tripulantes piden las tareas siguientes al terminar de ejecutar su tarea, no al principio cuando lo mandan a ready. 

Cuando hay que pedir la proxima tarea para los casos posteriores al primero? 

Si lo hacemos al principio, tendríamos que buscar la manera de saber si va a haber una proxima tarea luego de esa, para no perder un quantum de procesador chequeando una tarea que no va a haber

Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

El pedir la próxima tarea tendría que ser al final del último ciclo de tu tarea actual, cosa de que si tiene una próxima tarea sigue en exec o va a ready si el quantum lo corta o si no tiene nada se va para exit.

Saludos.-
