### ISSUE TITLE
Hexedit

### ISSUE THREAD

**Issue by SantiagoIvan** [sisoputnfrba/foro#2261]
Buenas! Estaría teniendo problemas con el Hexedit, no puedo modificar el archivo de Superbloque.
Si me manejo con la interfaz gráfica y abro el Superbloque.ims con el Bless editor, cuando hago click en la opcion "Save as" no me deja sobrescribir al Superbloque ya existente, por lo que tengo que guardarlo si o si en otro lado (Por ejemplo, en Documentos). Para que tenga efecto el sabotaje tengo que dar apagar I-mongo y volverlo a prender cambiando los archivos Superbloque "nuevo" por el Superbloque "viejo" y recien ahi toma efecto. Me descargué el package de hexedit para usarlo por la consola y tampoco me deja editarlo. Ni bien lo modifico, lo guardo y me vuelve al estado anterior. Probé aumentando el tiempo de sincronización a 100 y me pasa lo mismo. Alguna sugerencia?

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Un par de consultas al respecto como para tener mas contexto y no tirar fruta al aire.
1.- Estas corriendo tu proceso con sudo?
2.- Como estas abriendo el archivo?
3.- Solo te pasa con hexedit o si por ejemplo abrís el archivo con `vim` o `nano` te pasa lo mismo?

Saludos.-

**Comment by SantiagoIvan** [comment]
Hola!

1) Si por 'proceso' te referis a alguno de los modulos del tp, la respuesta es que los corremos a todos sin el sudo. Si te referis a correr el 'hexedit' con sudo, no me funciona de ninguna de las 2 formas
2) El archivo de Superbloque lo estaba abriendo de 2 formas:
a) Click derecho -> Abrir con Bless Hex Editor. Ahi es donde me sucede el bug ese de que no me deja sobrescribirlo y tengo que guardarlo con 'Save as' en otra carpeta, y hacer el reemplazo manualmente. Ademas tengo que apagar los modulos del tp y volverlos a arrancar.
b) Me descargué el paquete de hexedit, para editarlo desde la consola. Para abrirlo tengo que hacer hexedit Superbloque.ims. Haciendolo con sudo o sin sudo, es lo mismo. El archivo se guarda, o mejor dicho, se "guarda". Porque en realidad lo que sucede  lo siguiente: Con todos los módulos corriendo (sin ejecutar tripulantes) edito el Superbloque.ims, lo guardo, y lo que hago es abrirlo un par de veces mas para ver si se guardó correctamente. Y aparentemente sí, se guardó correctamente. NI bien le doy a iniciar planificación, vuelvo a abrir el archivo de Superbloque.ims para ver que hay y se volvió al estado anterior, solito, por lo tanto mando el signal a imongo para ver si hay sabotaje y no, no encuentra nada.
También intenté lo siguiente: apago todos los procesos, abro el archivo de Superbloque.ims (usando hexedit con y sin sudo) y lo modifico. Luego arranco todos los modulos y mando el signal para ver si me detecta algun sabotaje. No me detecta nada y es porque magicamente se volvio a modificar el archivo solo al estado anterior.
Es como que me deja "guardarlo". De hecho me pide que le ponga nombre,  le pongo el mismo nombre (o sea, Superbloque.ims) y me lo guarda, lo vuelvo a abrir y veo el cambio, pero cuando arranco los modulos y mando el signal, vuelve al estado anterior, como si nada hubiera pasado.
Espero que se haya entendido sino lo hablamos el sabado y te muestro compartiendo pantalla

**Comment by SantiagoIvan** [comment]
Agrego una cosita de un compañero: 
  1) Al archivo lo estamos mapeando a memoria con mode 777. Eso puede llegar a ser un problema? El código que tenemos respecto a eso es el siguiente:
  
  - fd_superbloques = open(ruta_superbloque, O_RDWR, (mode_t)0777);
  - superbloque = mmap(NULL, 2 * sizeof(uint32_t) + (*block_amount_ref)/8 + 1, PROT_WRITE | PROT_READ, MAP_SHARED, fd_superbloques, 0)

**Comment by gastoncastineira** [comment]
Consultas

Abrís hexedit, editás, y después cómo guardás y cerrás? Con qué combinación de teclas? Cual es el comando que corrés para abrir el hexedit?

**Comment by SantiagoIvan** [comment]
Cierro el issue porque ya me di cuenta del error. Estaba realizando mal la prueba. Estaba saboteando el bitmap mientras un tripulante se estaba moviendo. Yo siempre marcaba como libre el primer bloque de todos y claro, como habia un tripulante moviendose, al querer logear un movimiento, me tomaba ese primer bloque libre. Y entre que saboteaba el bitmap y mandaba el SIGUSR1 pasaban unos cuantos segundos asi que no me daba cuenta de que era ese el error. Perdón y gracias por las respuestas !
