### ISSUE TITLE
Dump Segmentación Prueba - segmentos no ocupados

### ISSUE THREAD

**Issue by SantiagoOrlando29** [sisoputnfrba/foro#2264]
Hola!
Hago este issue ya que queda solo la última entrega y no me quiero arriesgar a absolutamente NADA.
Sabiendo que ya hablaron de esto en #2257 , les pido disculpas, pero igualmente quiero estar seguro con que hacer.
En cuanto al dump en segmentación, ustedes pusieron que se tiene que ver algo así:

![image](https://user-images.githubusercontent.com/81048243/127163857-2a991cd1-cc68-4c80-9f85-b5772686d007.png)

Viendo eso yo entiendo que se ven solo los segmentos ocupados. Pero hacia el final de la prueba de segmentación piden hacer un dump cuando la memoria tiene muchos segmentos libres. El "problema" es que, por como yo entendí el dump, en ese dump no imprime nada, porque no hay segmentos ocupados. Sabiendo que igualmente en el log de MiRam yo imprimo esto divino que es el estado de la memoria, y en el que se ve eso mismo que quieren ver en la prueba:

![image](https://user-images.githubusercontent.com/81048243/127170013-7369baf6-0eb7-42a0-b2c6-99f3fb3f7914.png)

Consideran necesario que cambie algo en el dump o les puedo mostrar el log en ese caso y estaría bien?

Saludos!

**Comment by gastoncastineira** [comment]
Santiago, como va?

En las entregas nos dimos cuenta que estuvimos medio flojos con el tema del dump para poder testear, no solo por lo que decís, sino también porque la dirección la pusimos en hexa pero el tamaño en decimal, y eso nos fuerza a empezar a usar calculadoras para ver que todo esté en orden.

**NO** es condición de aprobación que traigas un dump más bonito como el que tenés, pero personalmente si veo un dump así el día de la entrega te besaría (con los respectivos protocolos de por medio)

![image](https://user-images.githubusercontent.com/28161802/127172951-c77a34b8-2dc1-49a4-bfe9-1ce439df45af.png)

**Comment by SantiagoOrlando29** [comment]
jsjjssjj bueno, voy a ver si puedo hacerlo así lindo pero no garantizo nada jajaj. Pero entonces en cuanto a este tema me quedo tranquilo no? Aunque el ultimo y anteúltimo dump no muestren nada está bien no?
Y en cuanto a lo de la calculadora eso si se los arreglo en un toque. Supongo que prefieren todo en decimal no?

**Comment by gastoncastineira** [comment]
Me perdiste. ¿Por qué los últimos dos dump no muestran nada? Los dumps durante la prueba los hacemos mientras aun hay patotas en memoria

> Y en cuanto a lo de la calculadora eso si se los arreglo en un toque. Supongo que prefieren todo en decimal no?

Decimal o hexa, pero que esté todo en uno solo

**Comment by SantiagoOrlando29** [comment]
Los últimos dos dumps de la prueba de segmentacion se hacen después de que terminan todos los tripulantes por lo que dice acá:
![image](https://user-images.githubusercontent.com/81048243/127180952-5870177f-2762-402d-88cc-987db66af14e.png)

O sea que ya no habría patotas en memoria. O si?

**Comment by gastoncastineira** [comment]
ups, me había olvidado de esos dos. Mala mía

Sí, es como decís. Ter terminaría quedando un único segmente gigante todo libre, igualito que cuando arrancó miram

**Comment by SantiagoOrlando29** [comment]
Claro. Pero lo que te decía es que en mis dos últimos dumps, todos los segmentos libres antes de la compactación, y el segmento gigante después de la compactación, no se ven, porque solo imprimo los ocupados en los dumps. Eso es lo que me da miedito, aunque igual en el log de MiRam si se ven esos segmentos libres.

**Comment by gastoncastineira** [comment]
Tranca, es lo mismo de antes. Estuvimos pobres con el dump. Si podés agregar que te muestre los libres estaremos muy agradecidos, pero no es algo necesario

**Comment by SantiagoOrlando29** [comment]
Genial
Mil graciasss!
