### ISSUE TITLE
[Paginación] Son validos resultados distintos a los del documento?

### ISSUE THREAD

**Issue by lumelamed** [sisoputnfrba/foro#2265]
Buenas! Estábamos haciendo la prueba de paginación y vemos que ahora los resultados están muy detallados, y los nuestros no cumplen tal cual lo que dice ahí. Se nos ocurren algunas ideas de por qué:

- En el Discordiador, el orden en que pasan los tripulantes es algo como: "T1 -> R", "T2->R", "T3->R", "T1->E" ...(T1 pide tarea)... "T1->R"(se le termina el quantum) y ese mismo ciclo con todos. Al final, para terminar las tareas, el ciclo es: ..."Tx->R", "Tx->E"...(Tx pide tarea y recibe un "FIN")... "Tx->expulsado". Creemos que no habría ningún problema con esta implementación, pero lo aclaramos porque tal vez no era lo que se pensó en la prueba
- El orden en que terminan los tripulantes en el Discordiador es A - B - C, pero en RAM terminamos primero a la B, luego A, luego C. Esto esta mal?
- En Mi-RAM, guardamos las cosas en el siguiente orden: TAREAS - PCB - TCBs

### 📔 Citas del documento de pruebas
Resultados Esperados
Al llegar las 3 patotas a Ready, Patota A y Patota B deberían estar en swap, y patota C ocupar la totalidad de los marcos
Ejecuta el tripulante de la patota A, reemplazando dos páginas de C
Ejecuta el tripulante de la patota B, reemplazando dos páginas de C
Ejecuta el tripulante de la patota C, reemplazando dos páginas de A
Ejecuta el tripulante de la patota A, reemplazando dos páginas de B
Ejecuta el tripulante de la patota B, reemplazando dos páginas de C
Ejecuta el tripulante de la patota C, reemplazando dos páginas de A
Ejecuta el tripulante de la patota A, reemplazando dos páginas de B
Finaliza A
Ejecuta el tripulante de la patota B, aprovechando los frames dejados por A
Finaliza B
C utiliza todas las páginas de memoria hasta finalizar.

###  Comportamiento obtenido
Lo que nos ocurre:
Habíamos considerado que cuando no había lugar en RAM, directamente se guardaba en MV. Pero como las pruebas dicen "_Al llegar las 3 patotas a Ready, Patota A y Patota B deberían estar en swap, y patota C ocupar la totalidad de los marcos_" hacemos eso mismo pero inmediatamente luego de guardar en MV, hacemos swap, y ahí si se llega a este resultado. Luego:
- Se reemplaza la pagina 0 de la patota C por la 1 de la patota A (allí está el TCB a actualizar)
- Se reemplaza la pagina 1 de la patota C por la 1 de la patota B (allí está el TCB a actualizar)
- Se reemplaza la pagina 2 de la patota C por la 0 de la patota A (allí están las tareas)
- Se reemplaza la pagina 3 de la patota C por la 0 de la patota B (allí están las tareas)
- Se reemplaza la pagina 0 de la patota A por la 3 de la patota C (allí está el TCB a actualizar)
- Se reemplaza la pagina 1 de la patota A por la 0 de la patota C (allí está la primera tarea)
- Se reemplaza la pagina 0 de la patota B por la 1 de la patota A (allí está el TCB a actualizar)
- Se reemplaza la pagina 1 de la patota B por la 0 de la patota A (allí están las tareas)
- Se reemplaza la pagina 0 de la patota C por la 1 de la patota B (allí está el TCB a actualizar)
- Se reemplaza la pagina 3 de la patota C por la 0 de la patota B (allí están las tareas)
- Se reemplaza la pagina 0 de la patota A por la 3 de la patota C (allí está el TCB a actualizar)
- Se reemplaza la pagina 1 de la patota A por la 0 de la patota C (allí está la tarea C01)
- Se reemplaza la pagina 0 de la patota B por la 1 de la patota A (allí está el TCB a actualizar)
- Se reemplaza la pagina 1 de la patota B por la 0 de la patota A (allí están las tareas)
- Se reemplaza la pagina 0 de la patota C por la 1 de la patota B (allí está el TCB a actualizar)
- Se reemplaza la pagina 3 de la patota C por la 0 de la patota B (allí están las tareas)
- Se reemplaza la pagina 0 de la patota A por la 3 de la patota C (allí está el TCB a actualizar)
- Se reemplaza la pagina 1 de la patota A por la 0 de la patota C (allí está la tarea C02)
- Se reemplaza la pagina 0 de la patota B por la 1 de la patota A (allí está el TCB a actualizar)
- Acá es cuando digo que antes de saber que no tenia mas tareas, la patota paso a R, luego a E, luego pide la tarea, y recién ahí sabe que ha finalizado porque no tiene mas tareas
- Finaliza B
- La pagina 1 de la patota C se guarda en RAM, aprovechando un frame libre
- Finaliza A
- La patota C aprovecha los frames libres para lo que resta de sus tareas
- Finaliza C
- La memoria queda con todos los frames libres

Todos estos reemplazos se ven claramente en los logs.

Creemos que los resultados están acordes a nuestra solución, pero queríamos preguntar en caso de que haya algún problema que se nos este pasando por alto.

Muchas gracias!

**Comment by iago64** [comment]
Buenas, Cómo va?

Revisando los resultados y por lo que dicen estan medio forzando el resultado de la prueba, si cambia algo en el medio y por ejemplo C solo ocupara 3 páginas, como respondería el sistema?
El punto de guardar en MP y después mover las cosas a MV es justamente lo que hace que se den los reemplazos, si lo fuerzan pueden estar teniendo algún bardo.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! ¿Pudieron revisar el caso que les planteó Dami? Saludos

**Comment by lumelamed** [comment]
Hola! Perdón por la demora. Entre la respuesta de Dami y lo que pregunté en soporte, tengo entendido que mientras se justifique correctamente la diferencia con lo esperado, estaría bien. Respecto al caso de que “si C ocupara 3 páginas” es un código que teníamos contemplado pero al enfocarnos mas en el documento de pruebas, no pasaba nunca por ahí. Si no les molesta, preferiría hacer más pruebas antes de cerrar el issue. Lo que deberíamos cambiar sería que siempre siempre se guarde una página en MP, y si no hubiera lugar, dejar un frame libre swappeando lo que había allí a MV, asi se ocupa con esta nueva página, no?
Muchas gracias!

**Comment by iago64** [comment]
Buenas!

Es tal cual decís: Siempre a MP y si no hay lugar, bajas algo de MP a MV y guardas lo nuevo en MP 😄 

Saludos.-

**Comment by lumelamed** [comment]
Buenísimo!
Ahí estuve probando y se ve bien. 

Muchas gracias!
Saludos
