### ISSUE TITLE
Duda sobre expulsión de tripulantes

### ISSUE THREAD

**Issue by FacaHerrera** [sisoputnfrba/foro#2267]
Buenas, tenemos una duda en el expulsar el tripulante o pausar la planificación. Nuestra duda es en caso de que el/los tripulantes se encuentren realizando algún movimiento, tarea, E/S, si deberíamos esperar a que terminen para expulsarlo o bloquearlo. O bloquearlo/expulsarlo en ese instante.

**Comment by iago64** [comment]
Buenas! Cómo va?

Deberían esperar a que termine el ciclo de CPU y recién ahí lo expulsan.

Saludos.-

**Comment by FacaHerrera** [comment]
Buenas, entendido, muchas gracias por la respuesta, saludos!
