### ISSUE TITLE
Algo raro con el tamaño del tipo char y los structs

### ISSUE THREAD

**Issue by study64** [sisoputnfrba/foro#2268]
Hola que tal, cuando implementé el dump de ram me di cuenta de que mi TCB no ocupaba 21 bytes sino 24 pero no logro entender el porque, hice las siguientes pruebas y obtuve estos resultados:

//Mis structs (el TCB y otros para pruebas)
```
typedef struct {
	uint32_t TID;
	uint32_t posX;
	uint32_t posY;
	uint32_t proximaTarea;
	uint32_t punteroPCB;
} tcb_sin_estado_t;

typedef struct {
	char estado;
} tcb_solo_estado_t;

typedef struct {
	uint32_t TID;
	char estado;
	uint32_t posX;
	uint32_t posY;
	uint32_t proximaTarea;
	uint32_t punteroPCB;
} tcb_t;
```
```
printf("Tam char %i \n", sizeof(char));//Me fijo el tam de un char
printf("Tam TCB sin estado %i \n", sizeof(tcb_sin_estado_t));//Me fijo el tam de un tcb pero sin el tipo char
printf("Tam TCB solo estado %i \n", sizeof(tcb_solo_estado_t));//Me fijo el tamaño de un struct solo con el char
printf("Tam TCB %i \n", sizeof(tcb_t));//Ahora me fijo el tamaño del tcb posta y la suma no cierra

//La salida que me da
Tam char 1 
Tam TCB sin estado 20 
Tam TCB solo estado 1 
Tam TCB 24 
```
Agradecería mucho cualquier orientación que puedan darme.

**Comment by RaniAgus** [comment]
¡Buenas! Lo que ocurre (y se explica mejor en la [guía de serialización](https://docs.google.com/document/u/0/d/190LLBTzHkFmD_yS8OWcUsJoIOQVKxJkUxIFtcnChr-g/mobilebasic)) es el **padding**: a la hora de declarar un struct, el compilador asigna un espacio extra a cada variable si ésta no tiene un tamaño múltiplo de la palabra del procesador. 

En este caso, en un procesador de 32 bits (4 bytes) cada variable del struct va a tener asignado un tamaño múltiplo de 4. Como un `char` tiene tamaño 1, el padding va a ser de 3 para completar esos 4 bytes.

Para avisarle al compilador que no agregue padding, hay que setearlo como `__attribute__((packed))` al final como en este ejemplo que saqué de la guia:

```c
typedef struct {
   uint32_t dni;
   uint8_t edad;
   uint32_t pasaporte;
   char nombre[14];
} __attribute__((packed))
t_persona;
```

Saludos

**Comment by study64** [comment]
Ok, muchas gracias funcionó perfecto. Igual me quedo una duda, si siempre completa a 4 bytes ¿porque el struct que solo tenia el char si tiene un tamaño de 1 byte?

**Comment by gastoncastineira** [comment]
Buenas

gcc (el compilador) no es una cosa exactamente tan lineal como decir "tiene esto, le corresponde este código máquina". Muchas veces intenta ser más inteligente y optimizar de distintas formas el código máquina que resulte de tu compilación haciendo y asumiendo cosas que quizá no reflejen tu código (como por ejemplo, funciones de pocas líneas en lugar de compilarla como una función, copia y pega el código en el lugar del llamado para reducir accesos a memoria al ejecutar). 

Si tuviera que adivinar, apostaría a que se está dando cuenta que ese struct tiene solo un char y lo esté compilando como eso

**Comment by study64** [comment]
Perfecto, gracias por la alcración.
