### ISSUE TITLE
Pruebas con Valgrind y uso de SWAP en paginación

### ISSUE THREAD

**Issue by jcastagno99** [sisoputnfrba/foro#2271]
Buenas! tengo 2 consultas puntuales y que nada tienen que ver entre sí.

1) Hay algo muy raro en querer hacer la prueba de estabilidad con paginación corriendo el modulo de mi-ram-hq con valgrind, el flujo se queda trabado, el mapa hace cosas raras y la ejecución no termina, no se si tiene que ver con algo de que estoy al borde de la memoria, pero solo me pasa con valgrind y en la prueba de estabilidad (solo con esta combinación), no hay semaforos sin liberar ni nada, corro la misma prueba con la misma configuración (que es la misma que se dice en el documento de pruebas pero con el ciclo de CPU en 0.1 y RAM con paginación) pasa perfecto. Alguna idea del porque? deberia pasar? tengo entendido que no se pide evaluar con valgrind
Dejo una foto de lo que hace el mapa (no se si suma pero la dejo) :
![image](https://user-images.githubusercontent.com/49038828/127599494-e616ed89-cc92-48da-9413-7db483573348.png)

La consola queda como bloqueada y no tira ningun error (ninguno de los 3 modulos)

2) Me gustaría saber si esta bien como estoy tratando el Swap : 
 Yo voy cargando procesos en memoria principal y cuando no hay lugar empiezo a Swapear, les asigno a cada página un "inicio en swap" y cuando hay que traer dicha pagina a memoria, copio desde swap a un frame, pero como que siempre una vez guardada en swap queda residualmente una "copia", lo que se me ocurre de ultima es cuando me la traigo, copiarle basura por encima, pero me parece innecesario, estaria bien dejarlo asi? no es que hago un duplicado de entrada, cuando necesito swapear una pagina por primera vez, la mando a swap, y cuando la quiero traer, leo esa posicion N bytes del tamaño de las paginas y la copio a un frame que apunta a la memoria principal, es correcto?

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

1.- No es que no se pida, directamente esta prohibido levantar los procesos con valgrind en la entrega final. Igual sería bueno saber que output tira valgrind como para ver si efectivamente no es que te esta pasando que tenes algún manejo medio raro de la memoria.

2.- La pagina tiene que estar en memoria principal o en swap, no puede estar en ambos lados al mismo tiempo, por mas que sea una versión desactualizada.

Saludos.-

**Comment by jcastagno99** [comment]
Buenas, creo que la respuesta 2 me dejo mal parado, voy a detallar un poco mejor como vengo haciendo el tema de swap (que creo que ahí esta el problema)

2) Yo hasta ahora al inicio del modulo hago MMAP para levantar el area de swap, cuando me van llegando paginas para guardarlas en swap voy asignandoles un lugar en el mismo: hago un memcpy a inicio_swap + offset_swap de N bytes y corro el puntero de offset_swap para no pisar otra pagina y le asigno ese lugar con un puntero, para luego si ya tenia un lugar en swap no volver a cargar la pagina en otro, yo no estoy manejando estructuras que me digan que lugar de swap esta libre o no, simplemente voy escribiendo con un offset, entiendo entonces que deberia hacer un analogo a los frames de memoria para administrar lugares libres / ocupados en swap?
Así cuando me traigo algo de swap a memoria, lo copio de un "frame_swap" a un "frame_posta" y marco el de swap como libre para que alguien lo pise de ser necesario, asi no tengo "duplicados" , bueno tendria el duplicado hasta que alguien pise el dato pero en esencia no estaria duplicado. Este es el enfoque correcto? con esto cumplo lo de no duplicados?
De otra forma no se me ocurre como poder manejar lugares libres/ocupados con mi implementacion actual.

Si ese enfoque estaba bien, hay algun criterio para elegir un "frame_swap" libre? o es el primero que encuentro? 

1) Me olvide de agregarlo antes, perdon deja este mensaje cuando corto el modulo (porque se queda bloqueado) y apreto cualquier tecla en la consola de Mi-Ram-HQ

![image](https://user-images.githubusercontent.com/49038828/127702644-76321557-7682-4b4b-b168-388ce9e7537a.png)

**Comment by dteplitz** [comment]
Aca dejo el .log que genera el valgrind cuando tira este error.

Me llama mucho la atencion porque en el mapa se mueven letras afuera del cuadrado pintado y hasta repite algunos caracteres cosa que entiendo no deberia poder pasar.
Y encima sin valgrind esta funcionando correctamente.
[valgrind.log](https://github.com/sisoputnfrba/foro/files/6909996/valgrind.log)

**Comment by iago64** [comment]
Buenas, cómo va?

Al parecer el problema lo tenes en tu función `buscar_patota_con_tid_paginacion (mi-ram-hq-lib.c:798)`, estas buscando algo que no esta reservado o que le hiciste `free()` previamente.
Por eso con segmentación te anda y con paginación no.

Saludos.-

**Comment by jcastagno99** [comment]
Si creo que estaba mal sincronizado esa funcion con la de expulsar tripulante, me llegaban cosas concurrentes y buscaba iterando listas que no existian, ya agregué unos semaforos y CREO que no hay problema.

Sobre el tema del swap, estaría bien lo que digo arriba?

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Mientras otro proceso pueda ocupar ese "frame" de swap esta bien :)

Saludos.-

**Comment by jcastagno99** [comment]
Perfecto, cierro eso de swap.

Ahora el tema este de valgrind... no puedo ubicar cual es el problema, corrí la prueba de estabilidad con paginación SIN VALGRIND y lo mire con htop (las corrí desde mi vm local) para ver si estaba teniendo un leak o algo


![00d8ce51-d356-4714-a513-0d1fa33bde45](https://user-images.githubusercontent.com/49038828/127752837-343c5551-cc29-462d-a249-68b1d30a6b2f.jpg)
Así arranca cuando inicio los 3 modulos

![f66de6e7-6a62-4b0e-9973-2b511f36f57a](https://user-images.githubusercontent.com/49038828/127752843-efc97f2c-6696-4d2e-b4bb-69b12dffa153.jpg)
Así queda cuando le cargo todas las patotas, inicio planificación y espero a que termine

![d5bc1dc7-1f92-47aa-8151-a8f6df5334b2](https://user-images.githubusercontent.com/49038828/127752846-4cd7561b-4161-4601-97b6-8f2f9358536d.jpg)
Y así es cuando termina y cierro los 3 modulos, cuando cierro esos modulos libero todo lo que me reserve, creo que no hay un leak como tal, el inicio y el final es aproximado porque la VM hace cosas en el medio y a veces suma o resta cosas.

Ahora, cuando levanto Mi-Ram-HQ con valgrind cambia.

![c59f5049-1b63-46a2-a133-7503898f0322](https://user-images.githubusercontent.com/49038828/127752908-7b13b735-c8cd-4957-abf3-e9a34577c3fe.jpg)
Así arranca

![63b96156-6470-4063-aab8-59c24105f49b](https://user-images.githubusercontent.com/49038828/127752911-7d4a547f-7f05-4c4e-ac75-27ef1d5ee660.jpg)
Llega un punto en el que los modulos se congelan, Ram solo queda logeando, discordiador se traba y el flujo no termina, cuando llega a este punto corto los modulos y me tira un Seg Fault en una función de cierre (que libera listas globales y eso que la llamo con el SIG INT) pero es que en sí el modulo se traba antes de tirarle el Ctrl + C y no puedo saber porque.

Dejo el log de valgrind (que dice lo que menciono arriba de la función de cierre)
y el log del modulo

[valgrind-log.txt](https://github.com/sisoputnfrba/foro/files/6911854/valgrind-log.txt)

[mi-ram-log.txt](https://github.com/sisoputnfrba/foro/files/6911855/mi-ram-log.txt)

Es medio dificil de verlo así capaz por el labo lo pueda replicar mejor

**Comment by RaniAgus** [comment]
¡Buenas! Antes que nada, quisiera hacer el mismo comentario que acá: https://github.com/sisoputnfrba/foro/issues/2221#issuecomment-881960522 . Es por esto que no existe ningún motivo para handlear `SIGINT`.

De hecho, esto altera las estadísticas que tira Valgrind, ya que quizás en ese handler estén liberando alguna estructura administrativa que no estén usando y deban haberla liberado en ejecución. Quizás sea la razón por la cual por más que Valgrind les tire que solo tienen 8 bytes en "definitely lost", a hora de probar el módulo sin Valgrind éste crezca 21 MB (lo cual es un montonazo).

Saludos

**Comment by jcastagno99** [comment]
Buenas! ahí estuve haciendo eso que me dijiste, simplemente saque el handler y no libero ninguna estructura administrativa, el log de valgrind no me dice mucho a mi pero paso todos los datos nuevos:

Estado cuando solamente abri htop : 
![efb702f7-e7a4-4d24-a27c-6beb4a42df5a](https://user-images.githubusercontent.com/49038828/127762785-c487097f-fec6-4581-9e80-227c97c2be2d.jpg)

Estado cuando levanto los 3 modulos, levantar RAM con valgrind me ocupo algo de 130 M (no se como funcióna internamente valgrind y si esto es normal)
![de204549-d3c1-4b81-8444-ed6cc307f972](https://user-images.githubusercontent.com/49038828/127762815-7e7a81f5-28b6-433a-b802-b557969f3f3f.jpg)

Estado cuando inicio todas las patotas (todavía no planifico nada) : 
![2980684d-1fc9-40c2-9684-90df89ed6271](https://user-images.githubusercontent.com/49038828/127762836-0600e413-41b7-4f99-8975-a3fb5e8c3a6c.jpg)

En un punto los 3 modulos se traban, ninguno explota ni tira seg fault, parecieria "un semaforo sin liberar" pero cuando la corro sin valgrind (misma configuración y todo) termina sin problemas por eso no me cierra... 
Estado cuando se traba todo antes de que lo cierre:
![207d25f8-b468-4ae8-ace6-aacd0d90c56a](https://user-images.githubusercontent.com/49038828/127762898-3a4366df-7578-4e57-8aef-b089233481aa.jpg)

El log de valgrind : 
[Valgrind-log.txt](https://github.com/sisoputnfrba/foro/files/6912294/Valgrind-log.txt)
(perdón no se si les gusta que les pase el log en txt o preferirían que lo copie directamente aca no se que les es mas comodo)

Todos los still reachables son los que yo antes liberaba con la función de cierre y los definitely lost siguen siendo 8 bytes =/ 

//-------------------- Para corroborar corro la misma prueba pero sin valgrind -----------

Recuerdo es la prueba de estabilidad del documento de pruebas finales pero con paginación y con ciclo de CPU 0, el resto sigue siendo la misma configuración

Así arranca: 
![75a51935-a88d-4c2b-a891-fd3db84b403e](https://user-images.githubusercontent.com/49038828/127763240-4a9ce991-0a70-49fe-a6c0-5856a7319c4c.jpg)

Cuando levante los 3 modulos:
![1a6065dc-9b78-4636-b71a-b15e881fb145](https://user-images.githubusercontent.com/49038828/127763260-79f25256-5c34-4743-a41b-49bab768d682.jpg)
(quedo igual)

Cuando cargue todas las patotas con iniciar patota: 
![2e82fb49-ec69-4602-9733-ca5167b509b2](https://user-images.githubusercontent.com/49038828/127763279-d708a8d8-8923-442f-9e9c-486709a822ad.jpg)

Y cuando finalizo la planificación (si que crecio alrededor de 20M)
![2e681b32-553c-4392-872b-b94a00a33579](https://user-images.githubusercontent.com/49038828/127763289-0b55fcc6-8536-42b3-bcde-2035e9e7600c.jpg)

Puede ser un leak entonces? no estaría pudiendo ubicarlo

**Comment by iago64** [comment]
Buenas! Cómo va?

OJO porque _still reachable_, lo que significa es que todavía lo podías recuperar, simplemente que como lo funaste con Ctrl + C quedo ahí en el limbo.
De valgrind lo que SI es leak son: _definitely lost_ y _indirectly lost_

Respecto al problema de lo que te queda bloqueado, probaste con helgrind a ver si te detecta algún deadlock?

Saludos.-

**Comment by jcastagno99** [comment]
Buenas, intente usar helgrind con la prueba de estabilidad y me comio toda la memoria y el swap, la VM se colgó y tuve que cerrar todo, el log tiraba muchisimas cosas, corrí la prueba de paginación (que no explota) y fui arreglando de a poco, me quedó uno que no entiendo el porque (y que se repite bastante), es sobre el orden de como se toman unos semaforos y todas las funciones tienen problema con lo mismo, no entiendo mucho de como leer helgrind igual parece que me dice que no se puede tomar un semaforo antes que otro, pero se toma y se libera en el momento, dejo el Log y uno de los conflictos (son de todas las funciones con una en especifico practicamente)

[Helgrind-log.txt](https://github.com/sisoputnfrba/foro/files/6918657/Helgrind-log.txt)

El conflicto lo tiene por ejemplo el primer mutex dentro del while (el auxiliar_pagina->mutex_pagina)

```
	tarea_ram* tarea_contador;
	tarea_ram* tarea_especifica = list_get(patota->tareas,indice_proxima_tarea);
	proxima_tarea = malloc(tarea_especifica->tamanio);
	t_pagina* auxiliar_pagina;
	double tamanio_hasta_tarea = 2*(sizeof(uint32_t));
	for(int i=0; i<indice_proxima_tarea; i++){
		tarea_contador = list_get(patota->tareas,i);
		tamanio_hasta_tarea += tarea_contador->tamanio;
	}

	double indice_de_tarea = tamanio_hasta_tarea / mi_ram_hq_configuracion->TAMANIO_PAGINA;
	double offset_hasta_tarea = modf(indice_de_tarea,&indice_de_tarea);
	int offset_hasta_tarea_entero = offset_hasta_tarea * mi_ram_hq_configuracion->TAMANIO_PAGINA;

	int bytes_de_tarea = tarea_especifica->tamanio;
	int bytes_leidos_tarea = 0;
	int indice_auxiliar_tarea = indice_de_tarea;
	int espacio_disponible_en_pagina = mi_ram_hq_configuracion->TAMANIO_PAGINA - offset_hasta_tarea_entero;
	int offset_pagina_entero = offset_hasta_tarea_entero;

	while(bytes_leidos_tarea < bytes_de_tarea){
		auxiliar_pagina = list_get(patota->paginas,indice_auxiliar_tarea);
		pthread_mutex_lock(auxiliar_pagina->mutex_pagina);
		if(!auxiliar_pagina->presente){
			frame = buscar_frame_libre();
			if(!frame){
				if(!strcmp(mi_ram_hq_configuracion->ALGORITMO_REEMPLAZO,"LRU")){
					frame = sustituir_LRU();
				}
				if(!strcmp(mi_ram_hq_configuracion->ALGORITMO_REEMPLAZO,"CLOCK")){
					frame = sustituir_CLOCK();
				}
			}
			pthread_mutex_lock(frame->mutex);
			auxiliar_pagina->presente = 1;
			auxiliar_pagina->inicio_memoria = frame->inicio;
			auxiliar_pagina->uso = 1;
			frame->pagina_a_la_que_pertenece = auxiliar_pagina;
			frame->indice_pagina = auxiliar_pagina->id_pagina;
			frame->pid_duenio = patota->id_patota;
			frame->libre = 0;
			pthread_mutex_lock(auxiliar_pagina->frame_swap->mutex);
			memcpy(frame->inicio,auxiliar_pagina->frame_swap->inicio,mi_ram_hq_configuracion->TAMANIO_PAGINA);
			auxiliar_pagina->frame_swap->libre = 1;
			pthread_mutex_unlock(auxiliar_pagina->frame_swap->mutex);
			t_pagina_y_frame* frame_y_pagina = malloc(sizeof(t_pagina_y_frame));
			frame_y_pagina->frame = frame;
			frame_y_pagina->pagina = auxiliar_pagina;
			
			pthread_mutex_lock(&mutex_lru);
			list_add(historial_uso_paginas,frame_y_pagina);
			pthread_mutex_unlock(&mutex_lru);
		}
		else if(auxiliar_pagina->presente){
			int indice = buscar_frame_y_pagina_con_tid_pid(auxiliar_pagina->id_pagina,patota->id_patota);

			pthread_mutex_lock(&mutex_lru);
			t_pagina_y_frame* frame_y_pagina = list_remove(historial_uso_paginas,indice);
			pthread_mutex_unlock(&mutex_lru);
			
			frame = frame_y_pagina->frame;
			pthread_mutex_lock(frame->mutex);

			pthread_mutex_lock(&mutex_lru);
			list_add(historial_uso_paginas,frame_y_pagina);
			pthread_mutex_unlock(&mutex_lru);
		}
		if((bytes_de_tarea - bytes_leidos_tarea) > espacio_disponible_en_pagina){
			memcpy(proxima_tarea + bytes_leidos_tarea,auxiliar_pagina->inicio_memoria + offset_pagina_entero,espacio_disponible_en_pagina);
			bytes_leidos_tarea += espacio_disponible_en_pagina;
			espacio_disponible_en_pagina =  mi_ram_hq_configuracion->TAMANIO_PAGINA;
			offset_pagina_entero = 0;
			auxiliar_pagina->uso = 1;
			pthread_mutex_unlock(auxiliar_pagina->mutex_pagina);
			indice_auxiliar_tarea++;
		}
		else{
		memcpy(proxima_tarea + bytes_leidos_tarea,auxiliar_pagina->inicio_memoria + offset_pagina_entero,bytes_de_tarea - bytes_leidos_tarea);
		bytes_leidos_tarea = bytes_de_tarea;
		auxiliar_pagina->uso = 1;
		pthread_mutex_unlock(auxiliar_pagina->mutex_pagina);
		}
	 pthread_mutex_unlock(frame->mutex);
	} 
```
con esta función que es la que se repite en todos los conflictos del log: 

En actualizar pagina es el mutex de pagina->mutex_pagina;
```
 t_frame_en_memoria* sustituir_LRU(){
	log_info(logger_ram_hq,"inicio algoritmo de sustitucion LRU");
	pthread_mutex_lock(&mutex_lru);
	t_pagina_y_frame* pagina_a_quitar_con_su_frame = list_remove(historial_uso_paginas,0);
	pthread_mutex_unlock(&mutex_lru);
	actualizar_pagina(pagina_a_quitar_con_su_frame->pagina);
	//pagina_a_quitar_con_su_frame->pagina->presente = 0;
	log_info(logger_ram_hq, "se ha elegido como victima a la pagina %i del proceso %i", pagina_a_quitar_con_su_frame->pagina->id_pagina,pagina_a_quitar_con_su_frame->frame->pid_duenio);
	t_frame_en_memoria* a_retornar;
	a_retornar = pagina_a_quitar_con_su_frame->frame;
	free(pagina_a_quitar_con_su_frame);
	return a_retornar;
}


void actualizar_pagina(t_pagina* pagina){

	//pthread_mutex_lock(&mutex_swap);
	pthread_mutex_lock(pagina->mutex_pagina);
	t_frame_en_swap* auxiliar = buscar_frame_swap_libre();
	if(!auxiliar){
		log_error(logger_ram_hq,"Se pidio buscar un frame en swap pero no habia ninguno disponible");
		pthread_mutex_unlock(pagina->mutex_pagina);
		//pthread_mutex_unlock(&mutex_swap);
		exit -1;
	}
	pthread_mutex_lock(auxiliar->mutex);
	pagina->frame_swap = auxiliar;
	memcpy(pagina->frame_swap->inicio,pagina->inicio_memoria,mi_ram_hq_configuracion->TAMANIO_PAGINA);
	pagina->frame_swap->libre = 0;
	pagina->presente = 0;
	pagina->inicio_memoria = NULL;
	pthread_mutex_unlock(auxiliar->mutex);
	pthread_mutex_unlock(pagina->mutex_pagina);
	//pthread_mutex_unlock(&mutex_swap);

}
```

Pareciera que se lockea una pagina y luego se la vuelve a lockear, pero no es ese el tema, la primer función es parte de obtener tarea, toma una pagina y la blockea, pregunta si esta en memoria o no y de no estarlo llama al algortimo de sustitucion (en este caso el LRU que llama al actualizar pagina) pero la pagina que se actualiza en actualizar_pagina es una pagina que estaba presente en memoria, es decir, que ocupaba un frame, por lo que nunca van a ser la misma pagina

**Comment by iago64** [comment]
Buenas!

Ojo, el "problema" que tenes ahi es que helgrind asume que vos estas tomando mal los semáforos, pero no puede asegurarlo, lo importante es que no te esta detectando deadlocks, lo que si estaría bueno es ver si con estos cambios que hiciste gracias a helgrind, que esta devolviendo valgrind, porque capaz tengas algo de memoria que se esta sobrescribiendo y por eso se le tranca el paty a tu proceso.

Saludos.-

**Comment by jcastagno99** [comment]
Buenas! no lo mencione en ese momento porque me habia roto todo y estuve todo el día tratando de hacer que ande, logre hacer que funcione la prueba de estabilidad pero sin valgrind, ya con las correcciones de helgrind hechas (menos esas de ahí arriba) valgrind sigue rompiendo, se traba en algun punto y ningun modulo avanza (igual que antes), lo termino con un control + c y el log es el mismo, todos bytes still reachable y 8 definitely lost que son del hilo que yo mato con el control + c, de todas formas hoy probe tambien esta prueba en las VM de la nube  (creo que se les dice asi) SIN VALGRIND  y la memoria no aumenta mas de 1M  (tengo estructuras que no libero porque saque la funcion de cierre, creo que eso influye un poco en ese crecimiento), creo que para lo que se pide en las pruebas esta bien, pero sigue siendo raro que valgrind no me lo corra.
 
Habia pensado en un punto que podia ser porque me capea la memoria de la VM, siempre que se traba llega a 881 aprox y ahi cuelga todo, nunca se el log completo porque lo tengo que cerrar a mano, pero es una teoría nada mas, perdón por el choclo de texto, dejo el log de valgrind con los cambios de helgrind ya hechos :

[Nuevo valgrind log.txt](https://github.com/sisoputnfrba/foro/files/6921064/Nuevo.valgrind.log.txt)
 
Ya como dato, helgrind en la misma prueba me capea la memoria, el swap y la cpu vuela al 100% y ahí mueren gatitos

**Comment by iago64** [comment]
Buenas! Una consulta, como estan ejecutando valgrind? que parametros le estan pasando? porque de todo el bruto choclo que tienen solo importa 1 cosa:

```
==28507== Thread 53:
==28507== Conditional jump or move depends on uninitialised value(s)
==28507==    at 0x8051EED: obtener_direccion_movimiento_mapa (mi-ram-hq-lib.c:2953)
==28507==    by 0x804B7DA: actualizar_ubicacion_paginacion (mi-ram-hq-lib.c:732)
==28507==    by 0x804A32D: manejar_suscripciones_mi_ram_hq (mi-ram-hq-lib.c:298)
==28507==    by 0x4062294: start_thread (pthread_create.c:333)
==28507==    by 0x41E10AD: clone (clone.S:114)
==28507==  Uninitialised value was created by a stack allocation
==28507==    at 0x804B82C: leer_un_uint32_a_partir_de_indice (mi-ram-hq-lib.c:739)
```

Pero despues de eso, no dice nada de memoria pisada ni de conflictos de memoria, con lo cual no habría mayores inconvenientes. Por otro lado, el LEAK SUMMARY, esta perfecto, despues de toda la ejecución perdieron 8 bytes nomas:

```
==28507== LEAK SUMMARY:
==28507==    definitely lost: 8 bytes in 2 blocks
==28507==    indirectly lost: 0 bytes in 0 blocks
==28507==      possibly lost: 0 bytes in 0 blocks
==28507==    still reachable: 176,646 bytes in 2,342 blocks
==28507==         suppressed: 0 bytes in 0 blocks
```

Saludos.-

**Comment by jcastagno99** [comment]
Buenas, valgrind lo ejecutamos con un comando que se llama "vexec" (hicimos el tp en visual) el comando esta configurado así : 

```
#!/bin/bash
FILE=mi-ram-hq
make $FILE
if test -f "./$FILE"; then
    valgrind --tool=memcheck --track-origins=yes --leak-check=full --show-leak-kinds=all --show-possibly-lost=no --show-reachable=yes --num-callers=20 --log-file="cfg/valgrind.log" ./$FILE cfg/mi-ram-hq.config cfg/mi-ram-hq.log
fi
```
Hay varios flags para valgrind, el --log-file es el path donde guardamos el log de valgrind a parte y despues los parametros del $FILE (que seria el ejecutable del modulo) el primero es el path al archivo de configuracion y el segundo es el path a donde queremos guardar el log general del modulo

Sobre de que no hay leaks, nunca pude terminar toda la ejecución con valgrind siempre se traba y lo tengo que terminar yo, por lo que no se al 100% si no hay algo raro mas adelante desde que se traba (aunque lo lógico seria que lo que hace que se traba este antes de que se trabe) pero por las dudas corrimos simulaciones con htop y no vimos un crecimiento excesivo como antes así que la verdad que nose porque lo hace.

Y sobre el salto condicional, lo voy a revisar ahora y updateo pero no me cierra que sin valgrind funcione todo y con valgrind se cuelguen los modulos de la nada, o por lo menos no lo entiendo.

**Comment by iago64** [comment]
Buenas!

Definitivamente siento que el haber dejado ese issue pineado que explica como usar VSCode hizo mas daño de lo que ayudo.
Paso a comentarte que esta de mas y/o podrían sacarlo
```bash
--tool=memcheck  # Te dice basicamente que uses valgrind, solo tiene sentido si usas helgrind
--track-origins=yes # Esta bien, podes dejarlo-
--leak-check=full # Justamente esto te sirve, queres todos los leaks
--show-leak-kinds=all # Tambien dejalo, te dice todos los tipos de leaks.
--show-possibly-lost=no # Bien que este en "no", ya que no te interesa lo posiblemente perdido, te lo sumariza abajo.
--show-reachable=yes # Podes sacarlo, no te interesa saber que memoria podes recuerar todavia
--num-callers=20 # Podes sacarlo, no te interesa decirle a valgrind hasta cuantas lineas del stack queres leer, por defecto te trae casi siempre todo lo que necesitas
```

De todas formas, teniendo en cuenta que no tenes grandes leaks segun lo que se ve en el último log, no me preocuparía mucho mas por valgrind.

Saludos-

**Comment by jcastagno99** [comment]
Perfecto, si por las dudas corrimos varias veces con HTOP y no vimos nada raro, pero bueno corroborar no venia mal. Cierro issue entonces, gracias!
