### ISSUE TITLE
[I-Mongo-Store] Medidas para asegurarme de no caer en el "es motivo de desaprobación directa"

### ISSUE THREAD

**Issue by julchat** [sisoputnfrba/foro#2272]
Buenas, ya con el TP andando entero y pasando las pruebas, abro este issue para preguntar si la forma en la que desarrollé I-Mongo en el aspecto de 

> Internamente, este archivo deberá ser mapeado a memoria y se le realizará una copia sobre la cual se trabajará para lograr simular la concurrencia y asincronismo en las bajadas a disco de los sistemas operativos reales. El tiempo de sincronización hacia el archivo físico de Blocks.ims será especificado por archivo de configuración. Cualquier otra implementación es motivo de desaprobación directa.

Lo que tenemos en nuestro módulo, es un void* como resultado del mapeo a memoria. Dicho void* (blocks) se sincroniza así:

```
void *sincronizar(void *tamanio)
{ //como si fuera un array
	uint32_t *tamanios = (uint32_t *)tamanio;
	while (1)
	{	
		msync(superbloque, tamanios[0], 0);
		msync(blocks, tamanios[1], 0);
		log_info(logger_i_mongo_store, "Se sincronizaron Blocks y SUperbloques");
		sleep(i_mongo_store_configuracion->TIEMPO_SINCRONIZACION);
	}
}

```

Para leer info de un bloque, simplemente por comodidad hacemos

```
char *bloque = malloc(block_size);
memcpy(bloque, blocks + (nro_bloque * block_size), block_size);
```

Para escribir 

```
char* bloque = malloc(block_size);
*lleno el bloque con bytes*
memcpy(blocks + (nro_ultimo_bloque * block_size), bloque, block_size);
```
Está bien eso?
Capaz es medio obvio pero quería preguntar porque el **es motivo de desaprobación directa** llegados a estas instancias impone mucho miedo y mas vale asegurarse

Relacionado a eso, el documento de pruebas menciona como uno de los elementos a evaluar:

> El sistema no requiere permisos de superuser (sudo/root) para ejecutar correctamente.

La forma nuestra de mapear el archivo de blocks es 

```
fd_bloques = open(ruta_blocks, O_CREAT | O_RDWR, (mode_t)0777);
if (fd_bloques == -1)
	{
		no_pude_abrir_archivo(ruta_blocks);
	}
	fallocate(fd_bloques, 0, 0, block_size * block_amount);
	blocks = mmap(NULL, block_size * block_amount, PROT_WRITE | PROT_READ, MAP_SHARED, fd_bloques, 0);
	if (blocks == MAP_FAILED)
	{
		no_pude_mapear_archivo(ruta_blocks);
		exit(-1);
	}

```
Pregunta: hay algún problema con usar (mode_t)0777 en el open()?

Muchas gracias!

**Comment by RaniAgus** [comment]
¡Buenas!

1. Ojo, porque `msync()` sirve para _forzar_ la sincronización entre el archivo real y la memoria mapeada (pueden chequear el [manpage](https://man7.org/linux/man-pages/man2/msync.2.html) para más info). Digo "forzar" porque el SO bajo ciertos criterios actualiza la memoria mapeada con `mmap()` sin necesidad de hacer `msync()`. Es por eso que sugerimos hacer una copia (`memcpy()`) y trabajamos sobre ella en vez de trabajar directamente con la memoria mapeada.

También, es por eso que cuando se cumpla el tiempo de sincronización la idea es actualizar el contenido de la memoria mapeada con el de la copia (otro `memcpy()` pero en sentido opuesto) e inmediatamente forzar esa sincronización con `msync()`.

2. Si, de hecho, está bien garantizarle permisos a ese archivo para que sea escrito y leído por todos, ya que es lo que luego te permite mapearlo a memoria (aunque quedaría más lindo y más seguro si lo dejan en `rw-rw-r--`, o sea, `664` :P). 

Lo que se menciona en el doc de pruebas es que sería erróneo tener que hacer, por ejemplo, `sudo ./imongostore` para ejecutar el programa correctamente (en la teoría se explica cómo funcionan los permisos en FS tipo UNIX).

**Comment by julchat** [comment]
Listo! Implementada la copia del puntero mapeado, con todo funcando. Gracias!
Saludos

**Comment by julchat** [comment]
a

**Comment by julchat** [comment]
Cierro issue

**Comment by julchat** [comment]
Bueno, perdón pero no me deja cerrarlo jajaja

**Comment by RaniAgus** [comment]
¡Cerrado! :P
