### ISSUE TITLE
[Discordiador] Problema con el orden de los tripulantes

### ISSUE THREAD

**Issue by matiaspar2000** [sisoputnfrba/foro#2273]
Buenas, estoy teniendo un problema a la hora de iniciar la planificación desde discordiador y que los tripulantes ejecuten en el orden correcto. 
Yo inicio una patota, inicia sin problemas y llegan a listo en el orden que deberían llegar (en este caso la patota es de 5 pero sucede lo mismo con cualquier número)

Para el ejemplo estamos haciendo que todos los tripulantes hagan la misma única tarea

```c
[0m>INICIAR_PATOTA 5 tareas.txt
[INFO] 14:00:18:668 discordiador/(10118:10118): 0 - Patota iniciada 
[0m>LISTAR_TRIPULANTES
---------------------------------------------------------------------------- 
Estado de la nave al día 30 del mes 07 del año 2021 a las 14:00:25 
Tripulante:   0    Patota:   0    Estado: Listo    Posición: (0,0) 
Tripulante:   1    Patota:   0    Estado: Listo    Posición: (0,0) 
Tripulante:   2    Patota:   0    Estado: Listo    Posición: (0,0) 
Tripulante:   3    Patota:   0    Estado: Listo    Posición: (0,0) 
Tripulante:   4    Patota:   0    Estado: Listo    Posición: (0,0) 
---------------------------------------------------------------------------- 
```

El tema está cuando le doy ```INICIAR_PLANIFICACION```, lo que pasa es que en vez de tomar el primer tripulante de la lista de ready (estamos manejando cada estado como una t_list*) toma el que está en la posición del grado de multitarea, es decir en este caso que es 2 toma el segundo (TID 1), si pongo multitarea en 3 toma el TID = 2 y asi. 

Realizando mas pruebas veo que

- Con multitarea 2 y 2 tripulantes el orden es 1-0
- Con multitarea 2 y 3 tripulantes el orden es 1-0-2
- Con multitarea 2 y 4 tripulantes el orden es 1-0-2-3
- Con multitarea 3 y 2 tripulantes el orden es 1-0
- Con multitarea 3 y 3 tripulantes el orden es 2-1-0
- Con multitarea 3 y 4 tripulantes el orden es 2-1-0-3 
- Con multitarea 3 y 5 tripulantes el orden es 2-0-1-4-3  (aca dio vuelta la 0 y la 1)
- Con multitarea 3 y 6 tripulantes el orden es 2-1-0-4-3-5

### 📝 Código relevante

Esta es la función que se dedica a mover los tripulantes de ready a trabajando
```c
void planificador(void* args) {
	int multitarea = config_get_int_value(config, "GRADO_MULTITAREA");

	while(1){
		sem_wait(&listo_para_trabajar);
		while(list_size(listo) > 0 && list_size(trabajando) < multitarea) {
			sem_wait(&planif);
			sem_wait(&multiprog);
			if(list_size(listo) != 0){
				t_tripulante* tripulante = (t_tripulante*) list_get(listo, 0);
				cambiar_estado(tripulante->estado, e_trabajando, tripulante);
				sem_post(&tripulante->semaforo);
				sem_post(&tripulante->semaforo);
				sem_post(&planif);
			}
		}
	}
}
```

Esto es el cambio de estado 
```c
void cambiar_estado(int estado_anterior, int estado_nuevo, t_tripulante* tripulante) {
   bool es_el_tripulante(void* tripulante_en_lista) {
		return ((t_tripulante*)tripulante_en_lista)->TID == tripulante->TID;
	}
   pthread_mutex_lock(&estados[estado_anterior]);
   switch(estado_anterior){
    case e_llegada:
        list_remove_by_condition(llegada, es_el_tripulante);
        break;
    case e_listo:
        list_remove_by_condition(listo, es_el_tripulante);
        break;
...
   }
   pthread_mutex_unlock(&estados[estado_anterior]);
   tripulante->estado = estado_nuevo;
   pthread_mutex_lock(&estados[estado_nuevo]);
   switch(estado_nuevo){
    case e_llegada:
        list_add(llegada, tripulante);
        break;
    case e_listo:
        list_add(listo, tripulante);
        sem_post(&listo_para_trabajar);
        break;
...
    }
   pthread_mutex_unlock(&estados[estado_nuevo]);
   enviar_cambio_estado_hq(tripulante);
}
```

Y el iniciar planificación es esto, que recibe la instrucción por readline y compara
```c
	} else if (strcmp(instruccion[0], "INICIAR_PLANIFICACION") == 0) {
		logear(INICIANDO_PLANIF,0);
		sem_post(&planif);
```

**Comment by iago64** [comment]
Buenas! Cómo va?

Una pregunta, están bien ordenados en la lista? Porque es posible que tenga que ver con eso.
Mas allá de eso, si te fijas las pruebas que están publicadas, que tanto difieren los resultados? porque también un poco estando a 1 semana de la entrega final, sería bueno que no se enrosquen en pruebas fuera de las publicadas.

Saludos.-

**Comment by matiaspar2000** [comment]
Ordenados en la lista están bien, el listar tripulante usa un list_iterate(estado,listar); que tengo entendido que los muestra empezando por el primero.
Sobre el tema de las pruebas, con los resultados así como quedan no estaría cumpliendo el punto de "Se respeta la planificación bajo el algoritmo FIFO" tengo entendido, ya que el primero en salir de listo no es el primero en llegar

**Comment by iago64** [comment]
Buenas! Cómo va?

A lo que nos referíamos en el resultado de: _El primero en salir es el primero en llegar_ es porque basicamente no se bloquean ni dejan de moverse en ningún momento, si sale primero en tripulante 1 y llega primero el tripulante 1, esta todo bien 😄 

Saludos.-

**Comment by matiaspar2000** [comment]
Ahhh perfecto entonces, muchas gracias y cierro issue
