### ISSUE TITLE
Tarea E/S - flujo de ejecución

### ISSUE THREAD

**Issue by SantiagoOrlando29** [sisoputnfrba/foro#2274]
Buenas
Releyendo para estar tranquilo para el sábado me surgen nuevamente dudas con este tema de las tareas de E/S en discordiador. Me surgen en base a la respuesta de @iago64 en el issue #2094 que no entiendo si tengo que pasarlo a bloqueado en el medio del flujo que explico a continuación o no. Y algunas duditas más con las bitácoras.
El flujo sería así ??? :
1.0. Avisarle a mongo que tiene que hacer una tarea (lo hago antes del sleep del ciclo de CPU del paso 2, que por lo que dice en #2152  estaría bien)
1.1. Recibir de mongo confirmación de que ya realizó todo lo relacionado a esa tarea y la finalizó en mongo (entiendo q es opcional pero en #2243 me sugieren que lo haga y me gusta esa idea).
2. Ejecutar 1 ciclo de CPU para simular la petición a mongo (con su sleep correspondiente).
3. Mover el tripulante a bloqueado.
4. Cuando le toque hacer los ciclos de CPU de bloqueado (tantos como indique la tarea), o sea, cuando no haya nadie más en bloqueado, recién ahí manda a mongo el mensaje para que agregue a la bitácora "Comienza ejecución de tarea X" (está bien eso? o tendría que hacerlo luego del paso 1? ).
5. Realiza los ciclos de CPU que indique la tarea.
6. Manda a mongo el mensaje para que agregue a la bitácora "Se finaliza la tarea X".

Perdón por la insistencia en cuanto a este tema.

Mil gracias! Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

Pregunta técnica, solo te preocupa el tema de cuando graba la bitácora? 
Porque el flujo que estas planteando esta perfecto y si nos dicen en la entrega: _Mandamos el grabar bitácora cuando empezamos a ejecutar los ciclos de I/O_ esta perfecto.

Saludos.-

**Comment by SantiagoOrlando29** [comment]
Ah genial. Si, mi duda era con lo de las bitácoras y con cuando iba a bloqueado (si era con tarea finalizada en mongo o no). Pero si decís que el flujo está bien me quedo tranquilo.
Graciasssss
