### ISSUE TITLE
Sabotaje - posición en Ready del tripulante que lo resuelve

### ISSUE THREAD

**Issue by SantiagoOrlando29** [sisoputnfrba/foro#2275]
Buenas buenas, yo de nuevo.
Acabo de leer un issue de sabotaje y me quiero matar jajaj. 

En la página 11 del enunciado dice:
> El sistema deberá buscar al tripulante más cercano a la ubicación del sabotaje (dentro de los que se encontraban en READY o EXEC) y planificarlo para que se mueva a dicha ubicación y resuelva el sabotaje invocando al FSCK del i-Mongo-Store, **pasándolo al final de la cola de bloqueados de emergencias.**
>
Pero también dice:
> Una vez solucionado el sabotaje, es decir, que termine su tiempo de duración (definido por archivo de configuración), **todos los tripulantes deberán ser desbloqueados en el orden en el cual fueron bloqueados.**

Honestamente yo la primer cita ni la había leído parece jaja.
Pero entonces, para pasar a los tripulantes de BLOCK_EMERGENCIA a READY: 
1. el tripulante seleccionado va a quedar último en READY ? ;
2. o va a quedar en la posición en la que fue bloqueado como dice la segunda cita ?
Siento que o un poco se contradicen esas dos citas, o no estoy entendiendo para que tengo que pasar el tripu seleccionado al final de la cola de bloqueados de emergencias.

Ojalá sea la segunda opción que es como ya lo hice jsjsj. 
Saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

La opción correcta es la 2, el tripulante que resuelve el sabotaje vuelve a ready en la posición en la que resolvió el sabotaje.

Saludos.-

**Comment by SantiagoOrlando29** [comment]
Ay buenísimo que alivio.
Mil gracias nuevamente. Buen finde!

**Comment by SantiagoOrlando29** [comment]
Ya me lo respondieron en discord. Gracias!
