### ISSUE TITLE
Duda general de IMongoStore

### ISSUE THREAD

**Issue by dbibe** [sisoputnfrba/foro#2276]
Buenas!, Como estan?. 

Queria hacerles una consulta para ver si efectivamente implementé bien ims. Ya habiendo pasado las pruebas decidí volver a leer el enunciado del tp para verificar si estaba bien hecho y llegué a esta parte.

"Será capaz de permitir lecturas y escrituras concurrentes de los diferentes archivos."

Lo que hice yo es que cada vez que discordiador mande un mensaje/petición se cree un nuevo hilo y se detachee, llamando a una funcion que se encarga de evaluar que peticion es y que hace.

Mi duda llega en que yo utilizo solo un mutex para todo el filesystem y sus estructuras administrativas (metadatas de bitacora/files) porque lo habia pensado como que tenia que asegurar la coherencia/integridad de mi filesystem, es decir, que cada cambio en metadata-blocks-bitmap sea ""atómica"" ya que no quería que un tripulante en su metadata aparezca que tenga el bloque X cuando efectivamente no esta ni en blocks ni en el bitmap. 

Pero ahora me entró la duda al leer esta parte del enunciado y leyendo otros issues de gente que habia implementado como una lista de mutex para manejarlo, ya que creo que no está tan bien justificado mi diseño como pensé.

**Comment by iago64** [comment]
Buenas! cómo va?

Ya arrancaste de 10 pensando en crear hilos para atender las peticiones 😄

Idealmente lo que deberían asegurarse es de no pisar las estructuras administrativas que en este caso van a ser los archivos de metadata y el superbloque, después una vez que aseguraste que vas a ir a bloques distintos (porque un mismo bloque no se comparte entre varios archivos) simplemente podes dejarlos ser a todos los hilos, ya que no deberías tener operaciones que se pisen entre si 😉 

Saludos.-

**Comment by dbibe** [comment]
Buenas,

Perfecto voy a tratar de mejorarlo como decís vos, cualquier duda reabro el issue. Muchas gracias!
