### ISSUE TITLE
Dudas sobre sabotajes

### ISSUE THREAD

**Issue by Nicolas-Russo** [sisoputnfrba/foro#2277]
Buenas tengo 2 dudas a la hora de realizar un sabotaje:

1. Las posiciones siempre van a ser de unDigito|unDigito(5|1) o pueden ser como por ej 12|34?
2. Los sabotajes se van a realizar siempre cuando el FS este ejecutando o en algun momento se va a parar el FS realizar un saboatje y cuando se levante de vuelta se tira la signal?

Gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Las posiciones van de 0 a 9.

2.- Siempre con el FS funcionando, de hecho las pruebas de sabotaje están publicadas 😉 

Saludos.-

**Comment by Nicolas-Russo** [comment]
Gracias!
