### ISSUE TITLE
Duda en Compactacion

### ISSUE THREAD

**Issue by AgustinCarabajal** [sisoputnfrba/foro#2278]
Buenas!

Estoy realizando las pruebas de segmentacion y me encontre con el siguiente caso: 

### Resultados Esperados

- Al momento de finalizar la patota C quedan varios segmentos libres correspondientes a las tareas, TCB y PCB. 👍
- Al momento de iniciar la patota B:
- - Con FF debe quedar un hueco libre al lado del PCB ya que debería ocupar el espacio del tripulante A1. 👍
- - Con BF el PCB de la patota B ocupará el espacio del PCB de la patota C por lo que no habrá un hueco en ese lugar 👍
- Al momento de cargar las tareas se debe compactar la memoria para generar el hueco libre para las tareas de la patota B. 👎
- Los tripulantes finalizan su ejecución y quedan todos los segmentos libres. 👍
- Al compactar la memoria los segmentos se unifican y se pueden validar al ver el log del dump de la memoria. 👍

El problema que encontre es que una vez realizada la compactacion las direcciones de los segmentos ocupados me quedan diferentes, debido a que utilizo una tabla de segmentos por proceso y al compactar ubico todos los segmentos de cada proceso al principio de la memoria, quedandome la memoria de esta forma:

Todos los segmentos de A - Todos los segmentos de B - Espacio Libre

Mi duda es si esta bien que compacte de esta manera o deberia modificarlo para que se adapte a las pruebas.

Saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

Consulta importante, en que orden están guardando las cosas? Porque las pruebas están escritas para el caso de que guarden PCB, TCBs y Tareas, en el caso de que guarden en otro orden puede variar un poco el momento en el que compactan.

Saludos.-

**Comment by AgustinCarabajal** [comment]
Buenas!

Nosotros estamos guardando los datos como PCB - TCBs - Tareas

La consulta venia ya que vi esta imagen en un issue
![126396087-012cc005-12f3-455f-ab3f-6f67aedc6d90](https://user-images.githubusercontent.com/22131218/127789766-911160af-173e-4b40-8906-e669f7a08164.png)

Para el caso de FF al iniciar la patota B el segmento de PCB ocupa una parte del TCB eliminado, dejando los 13 bytes libres y los TCBs ocupan los seguientes segmentos disponibles. El problema es que al compactar la memoria para generar un espacio para las tareas, lo que hago es recorrer las tablas de segmentos de cada proceso y moverlos al principio de la memoria. Por lo que me quedan ubicados como mencione arriba:

Memoria:
Segmentos de A - Segmentos de B - Espacio Libre

Estaria bien que compactemos de esta manera o habria que modificarlo para que se adapte al resultado de la imagen?

**Comment by iago64** [comment]
Buenas! Cómo va?

Creo que acá tenemos un problema no menor y es que estas pasándote por alto que en la teoría se ve que los segmentos se juntan de un lado, pero ese juntarse no implica reordenarlos.

Dicho lo anterior, como lo estas haciendo estaría mal porque lo que estas haciendo no es compactar, si no reordenar.

Saludos.-

**Comment by AgustinCarabajal** [comment]
Buenas!

Modifique el proceso para que funcione como mencionas y ya me dan las pruebas.

Gracias!
