### ISSUE TITLE
Paginacion - resultados pruebas

### ISSUE THREAD

**Issue by MartinGongora** [sisoputnfrba/foro#2279]
Buenas, revisando las pruebas de paginacion tuvimos resultados distintos en los siguientes puntos: 

"1- Al llegar las 3 patotas a Ready, Patota A y Patota B deberían estar en swap, y patota C ocupar la totalidad de los marcos"

3 en new, estado memoria principal : CCCC
A pasa a ready, estado memoria principal : AACC
B pasa a ready, estado memoria principal : AABB
C pasa a ready, estado memoria principal: CCBB

En este caso, se cumple que la patota C ocupa la totalidad de los marcos cuando las 3 patotas estan en NEW, cuando pasan a ready tanto A y B realizan reemplazos de pagina (cuando pasan a ready se cambia el estado en el tcb y se pide la proxima tarea), haciendo que C tenga que hacer reemplazos cuando llega a ready (1 pagina de TCB y 1 pagina donde esta el string de la proxima tarea), quedando en memoria 2 paginas de B y 2 de C al estar los 3 en ready. Este comportamiento estaría correcto? 

"2- Ejecuta el tripulante de la patota A, reemplazando dos páginas de C"

Aca, como consecuencia de lo que menciono en el punto 1, las dos paginas reemplazadas son de B, no de C. Es el comportamiento esperado? 
Los siguientes resultados continuan con normalidad, hasta llegado el punto 8

"8- Ejecuta el tripulante de la patota A, reemplazando dos páginas de B"

En este caso A ejecuta la tarea actual, se reemplaza una pagina (donde se encuentra el TCB) para cambiar el estado y traer el valor de la proxima tarea(la tarea que se ejecuta es la ultima, por ende no hay mas tareas), se chequea con las estructuras administrativas si existe la tarea, al no existir, no se trae la segunda pagina (que seria la que tiene el string de la próxima tarea). Resumiendo se reemplaza solo una pagina de B. Seria un comportamiento correcto? 

Por ahora eso es todo.

**Comment by gastoncastineira** [comment]
Buenas

Creo que tus problemas vienen por el lado que estás haciendo dos cositas que difieren de la teoría y lo que pide el TP

Por un lado, esto
> las 3 patotas estan en NEW, cuando pasan a ready tanto A y B realizan reemplazos de pagina (cuando pasan a ready se cambia el estado en el tcb y se pide la proxima tarea

Estás cargando las patotas a memoria cuando aún están en NEW cuando deberían estar cargándose cuando pasan a READY ( y por lo tanto no tendrías ese acceso que actualiza el estado porque ya se crea en READY)

Por otro lado, una cosa que interpreto de esto (y decime si no es así)
>En este caso A ejecuta la tarea actual, se reemplaza una pagina (donde se encuentra el TCB) para cambiar el estado y traer el valor de la proxima tarea(la tarea que se ejecuta es la ultima, por ende no hay mas tareas), se chequea con las estructuras administrativas si existe la tarea, al no existir, no se trae la segunda pagina (que seria la que tiene el string de la próxima tarea). Resumiendo se reemplaza solo una pagina de B

Estás pidiendo la próxima tarea recién cuando el tripulante vuelve a READY. En el enunciado pedimos que la tarea se pida cuando esta se termine, aún sin salir de ese estado. Eso te puede estar generando que los accesos sean distintos y entre solo una página en vez de las dos

**Comment by int0x80-sys** [comment]
Buenas. Soy compañero de Martín. Paso a responder.

>Estás cargando las patotas a memoria cuando aún están en NEW cuando deberían estar cargándose cuando pasan a READY ( y por lo tanto no tendrías ese acceso que actualiza el estado porque ya se crea en READY)

Claro. Cuando lanzamos el comando **INICIAR_PATOTA** primero inicializamos la memoria de la patota en la memoria y luego creamos las estructuras en el Discordiador. En este momento estarían en New. Luego, si la planificación no está pausada, se mueven a Ready y actualizan sus estados y piden la primera tarea.

Creo que por lo que decís, la memoria de la patota ¿Tendría que inicializarce cuando todos entren a Ready? Si es así, entonces el estado 'N' que aparece en la descripción del TCB en el TP ¿Estaría de mas?

> Estás pidiendo la próxima tarea recién cuando el tripulante vuelve a READY. En el enunciado pedimos que la tarea se pida cuando esta se termine, aún sin salir de ese estado. Eso te puede estar generando que los accesos sean distintos y entre solo una página en vez de las dos

Las tareas las pedimos al terminar el tiempo en la cola de bloqueados, o bien si es una tarea de CPU, apenas termina la tarea. Lo que menciona Martín es que tenemos en unas estructuras administrativas la cantidad total de tareas que tiene la patota. Si el índice de la prox tarea es mayor o igual a la cantidad de tareas, se finaliza ese tripulante. Por eso no estaríamos teniendo ese último acceso a memoria. Avisanos si no esta correcto.

Gracias y saludos 👋

**Comment by gastoncastineira** [comment]
> Creo que por lo que decís, la memoria de la patota ¿Tendría que inicializarce cuando todos entren a Ready? Si es así, entonces el estado 'N' que aparece en la descripción del TCB en el TP ¿Estaría de mas?

Es que vuelvo a lo mismo. En la teoría ustedes ven que un proceso se carga a memoria al salir de NEW. Y sin embargo acá, con planificación pausada, los procesos ya están cargados en memoria estando en NEW. Está como raro eso

>Las tareas las pedimos al terminar el tiempo en la cola de bloqueados, o bien si es una tarea de CPU, apenas termina la tarea. Lo que menciona Martín es que tenemos en unas estructuras administrativas la cantidad total de tareas que tiene la patota. Si el índice de la prox tarea es mayor o igual a la cantidad de tareas, se finaliza ese tripulante. Por eso no estaríamos teniendo ese último acceso a memoria. Avisanos si no esta correcto.

No es lo que pide el enunciado, pero viendo que es un caso que se da solo para la última tarea no nos quema tanto mientras puedan explicar esto el día de la entrega

**Comment by int0x80-sys** [comment]
Buenas de nuevo.

> Es que vuelvo a lo mismo. En la teoría ustedes ven que un proceso se carga a memoria al salir de NEW. Y sin embargo acá, con planificación pausada, los procesos ya están cargados en memoria estando en NEW. Está como raro eso

No se si esto es que esta raro en el TP o en nuestro caso. En la teoría dice que cuando los procesos llegan a New, el proceso no es cargado en memoria, pero que sus pcb son creados (y calculo que residen en memoria). Pero bueno, entonces queda hacer que se inicien las memorias de los tripulantes cuando pasen a NEW.

Saludos :wave:

**Comment by tomytinez** [comment]
> Estás pidiendo la próxima tarea recién cuando el tripulante vuelve a READY. En el enunciado pedimos que la tarea se pida cuando esta se termine, aún sin salir de ese estado. Eso te puede estar generando que los accesos sean distintos y entre solo una página en vez de las dos

Hola, aprovecho el issue ya que tenemos un problema similar con los resultados esperados de los tests. Considerando que pasa a memoria principal unicamente la pagina que contiene la tarea dentro del string de tareas. Cuando el tripulante pide la siguiente tarea al terminar la actual, sin abandonar el estado de EXEC, se le asigna su siguiente tarea, si es nula se manda a exit. Al no ser nula, se pasa el tripulante a ready por fin de quantum. Al momento de ejecutar esa tarea, no la necesitaria dentro de la memoria fisica, ya que ya la tengo asignada al tripulante, entonces no me pasaria 2 paginas a memoria principal sino solo la del tripulante que ejecuta la tarea. Dandonos una incongruencia con los tests.

**Comment by tomytinez** [comment]
> Estás pidiendo la próxima tarea recién cuando el tripulante vuelve a READY. En el enunciado pedimos que la tarea se pida cuando esta se termine, aún sin salir de ese estado. Eso te puede estar generando que los accesos sean distintos y entre solo una página en vez de las dos

Hola, aprovecho el issue ya que tenemos un problema similar. Al terminar la ultima tarea, el tripulante pide la siguiente a memoria estando en exec, considerando que memoria me va a decir que no hay siguiente, se pasa a exit. Pero para la busqueda de esa ultima tarea en memoria, no necesito pasar ninguna pagina a memoria principal, ya que la proxima tarea es NULL. A menos que consideren que para buscar una tarea se deben pasar todo el string y sus paginas a memoria principal, lo cual estaria mal, considerando que cuando se obtiene una tarea especifica del tripulante C, solo se pasa la pagina donde este esa tarea y no todas las paginas segun los tests que piden.

**Comment by iago64** [comment]
Buenas! Cómo va?

Para hacerlo mas simple y no dar muchas vueltas a menos de 24 del comienzo de las pruebas:
@int0x80-sys Si pueden explicarnos la decisión de diseño y justificarla con lo que dice el libro no hay drama.

@tomytinez Parecido a la respuesta anterior, en ese caso lo único que nos gustaría saber es como saben que una tarea es la última sin estar buscando en la página.

Saludos.-
