### ISSUE TITLE
Duda sobre tiempo de prueba

### ISSUE THREAD

**Issue by falpuy** [sisoputnfrba/foro#2280]
Buenas tardes, cómo están? Perdón por la molestia, tenemos un problema grande con la prueba de estabilidad general, tarda 25 minutos en terminar. Queríamos preguntar qué podemos hacer para que funcione más rápido. Muchas gracias!

**Comment by iago64** [comment]
Buena como va?

Se nos paso actualizar el doc, en las pruebas lo que estamos haciendo es correrla con retardo 0, ya que esa prueba nos sirve para detectar esperas activas y/o memory leaks.

Saludos.-

**Comment by falpuy** [comment]
Acabamos de checkear que era por una compu, disculpen.
