### ISSUE TITLE
Duda Sabotaje bitmap y blocks

### ISSUE THREAD

**Issue by SantiagoOrlando29** [sisoputnfrba/foro#2281]
Buenas
1. Con mi grupo nos encontramos con un tema. Para hacer el sabotaje de bitmap nosotros modificamos el bitmap y luego mandamos el signal de sabotaje. El problema es que luego de mandar ese signal, discordiador nos va a enviar cosas para cargar en la bitácora del tripulante que resuelve el sabotaje, por ejemplo: Se corre en pánico hacia X|Y, Se mueve de X|Y a X’|Y’, Se resuelve el sabotaje. Y todas esas cosas para cargar en bitácora se harían antes de arreglar el bitmap con el fsck. Entonces el bitmap que modificamos nosotros no va a ser el bitmap a arreglar digamos, porque a ese se le agregan los nuevos bloques de esas bitácoras. No sabemos bien que tendríamos que hacer la verdad en este caso.

2. Además, tengo una duda con el sabotaje en blocks:
Ese sabotaje pueden ser 3 opciones no? Como dice el #2131 
A. nos agregan un nuevo bloque que es mayor a la cantidad de bloques de todo el FS.
B. nos agregan un nuevo bloque que en el bitmap se encuentre vacio (o sea en 0).
C. nos cambian el orden del blocks.
Son esas 3, o hay alguna de más o falta alguna?

Saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Los sabotajes de bitmap, para evitar justamente que se pidan bloques que están asignados a otros archivos, lo que hacemos es marcar mas bloques como llenos de los que deberían estar entonces y así nos aseguramos de no pisar nada.

2.- Son esos 3 casos, tampoco es que podemos ponernos muy creativos en una lista de bloques y todos llenos con el mismo caracter.

Saludos.-

**Comment by SantiagoOrlando29** [comment]
Buenass
1. OK, tiene sentido.
2.
A. Pensándolo con mis compañeros, no nos cierra. Si agregan un nuevo bloque que es mayor a la cantidad de bloques de todo el FS, cuando se haga la verificación del sabotaje de bitmap ya va a saltar un error (o explotar quizás nose), ya que ese valor mayor no es válido como número de bloque.
B. Pensándolo con mis compañeros, no nos cierra. Porque si setean un bloque vacío en el Blocks, antes de eso ya se hizo la verificación del sabotaje de bitmap, y justamente en esa verificación del bitmap tomamos como ocupados los bloques que aparecen en el Blocks de cada metadata de los archivos. Entonces si setean un bloque vacío en el Blocks, se va a tomar como sabotaje de bitmap y no de blocks.
C. OK.

Gracias. Saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

A.- Ojo porque la idea sería ponerles onda si el Fs tiene 500 bloques, un bloque 2000, ahi no tendria sentido alguno y deberian fletarlo.
B.- Acá el problema va a pasar porque no les va a cuadrar el size con la cantidad de bloques, si tienen 4 bloques de 100 bytes y un size de 250... claramente hay 1 bloque que sobra, igual sobre este punto planteen una resolución y se charla en la entrega.

Saludos.-

**Comment by SantiagoOrlando29** [comment]
Perdón que insista.
Entiendo ambas cosas que me decís, y creo que la solución más fácil que se me ocurre para lo que te comentaba yo de que saltaría sabotaje de bitmap en esos 2 casos es realizar la verificación de sabotaje en este orden:
1. Sabotaje de la cantidad de bloques en el superbloque.
2. Sabotajes de files.
3. Sabotaje de bitmap en superbloque.

Creo que así no tendría problema. Es válido eso? O sea, es válido separar las verificaciones de los dos sabotajes del superbloque que hay?

Graciasss

**Comment by iago64** [comment]
Buenas!

No tenes nada de que pedir perdón, las dudas están para ser respondidas 😃 

Por como lo planteas y teniendo en cuenta que después de correr la reparación el FS quedaría en un estado utilizable, no veo mayores inconvenientes.

Saludos.-

**Comment by SantiagoCarnezis** [comment]
Buenas, perdon que me meta, pero leyendo el issue me quedo una duda.
Los sabotajes en blocks serian entonces los siguientes?
Por ejemplo tengo originalmente [0, 1, 2, 4] y me ponen [0, 1, 2, 3, 4] en este caso tendria que cambiar la lista de blocks que esta en el config por la que estaba originalmente? ya q me agregaron un bloque y ese bloque o no esta en el bitmap o esta ocupado pero pertenece a otro file. O la otra solucion seria, escribir el bloque 3 con el caracter de llenado del file (el problema de esto es q si el bloque 3 ya lo ocupaba otro file ese bloque, se estaria sobreescribiendo y me meteria en un problema mayor). Yo creo que la solucion correcta seria la primera pero lo pregunto para confirmar.

El otro sabotaje en blocks no estoy seguro de que forma seria:
A. Originalmente tengo [0, 1, 2] y me ponen [0, 1, 2, 1000] siendo en blocks (cant bloques del super bloque) 500.
B.  Originalmente tengo [0, 1, 2] y me ponen [0, 1, 1000] siendo en blocks (cant bloques del super bloque) 500.
En el segundo caso ademas de agregarme un bloque no valido, tambien me borro el bloque 2, de que forma serian entonces este tipo de sabotaje de blocks? o hay que considerar ambos casos?

Por ultimo del sabotaje en blocks que se cambia el orden de los bloques no tengo dudas.

Saludos

**Comment by SantiagoOrlando29** [comment]
Bueno pruebo con eso. Cierro el issue y cualquier cosa lo abro de nuevo.
MIL gracias Damian, sos crack.
![image](https://user-images.githubusercontent.com/81048243/128383321-2252d6c3-3b98-43c0-9c75-31a2c5e01099.png)

**Comment by iago64** [comment]
@SantiagoCarnezis es un caso borde, pero es como dije previamente, les va a sobrar un bloque, pero de ultima mientras lo resuelvan de una forma lógica, estamos bien.
Si les agregamos un bloque que esta fuera del limite de los bloques del FS (por ej tienen 500 y ponemos un 1000) lo tienen que voletear y de ultima si les falta para restaurar el archivo, lo restauran asignandole los bloques faltantes y ya :)
El caso de sacarles uno asignado y poner uno inexistente, podrían contrastar con el bitmap a ver que bloque esta usado que no lo tienen ningún archivo y ya. Tengan en cuenta que solo vamos a aplicar de a 1 sabotaje a la vez :)

Saludos.-

**Comment by SantiagoCarnezis** [comment]
Ok muchas gracias Damian. Por mi ya no tengo mas dudas

**Comment by SantiagoOrlando29** [comment]
Nosotros tampoco. Ya lo pudimos resolver. Gracias Dami!!
