### ISSUE TITLE
Duda prueba memory leak - htop

### ISSUE THREAD

**Issue by SantiagoOrlando29** [sisoputnfrba/foro#2282]
Hola
Estoy en duda de si mi tp tiene memory leaks o no. Paso a explicar la situación:
Corro valgrind en los 3 módulos y me tira lo siguiente:
Discordiador:
```
==21348== LEAK SUMMARY:
==21348==    definitely lost: 0 bytes in 0 blocks
==21348==    indirectly lost: 0 bytes in 0 blocks
==21348==      possibly lost: 680 bytes in 5 blocks
==21348==    still reachable: 66,982 bytes in 231 blocks
==21348==         suppressed: 0 bytes in 0 blocks
```

Miram:
```
==21333== LEAK SUMMARY:
==21333==    definitely lost: 8 bytes in 1 blocks
==21333==    indirectly lost: 0 bytes in 0 blocks
==21333==      possibly lost: 136 bytes in 1 blocks
==21333==    still reachable: 1,490 bytes in 89 blocks
==21333==         suppressed: 0 bytes in 0 blocks

```
Mongo:
```
==21340== LEAK SUMMARY:
==21340==    definitely lost: 151 bytes in 6 blocks
==21340==    indirectly lost: 0 bytes in 0 blocks
==21340==      possibly lost: 2,312 bytes in 17 blocks
==21340==    still reachable: 5,273 bytes in 29 blocks
==21340==         suppressed: 0 bytes in 0 blocks
```

Por lo que entiendo de haber leído issues, tengo pocos definitely e indirectly lost, así que no me tendría que hacer problema. Y los still reachable entiendo que tampoco son un problema. 
Con esto parecería que tengo muy poco memory leak en el tp, no?

Pero si corro con htop, apenas inicio los 3 módulos empieza por ejemplo ocupando 780 M. Después de hacer todos los INICIAR_PATOTA y el INICIAR_PLANIFICACION me dice htop que ocupa 804 M. Y a partir de ahí va cambiando la memoria. Me tira ponele: 804 - 806 - 808 - 803- 790 - 795 - 802 - 808 - 813 - 826. 
Ejecutando nuevamente con todo exactamente igual, me tira por ejemplo: 744 - 750 - 756 - 759 - 763 - 765. (no tengo idea porque es tan distinto a la ejecución anterior). Y luego del ctrl+c, 638, como se ve en la imagen. 
![image](https://user-images.githubusercontent.com/81048243/128261674-e5a1e0a3-f0c5-4883-8caa-405204d5f961.png)

Aclaración por las dudas: dejo terminar a todos los tripulantes, y cuando terminan todos hago ctrl+c en miram y mongo para cortar. 

Entonces, esto pasa la primer prueba el sábado o no? 

Gracias.

**Comment by iago64** [comment]
Buenas! como va?

Con los valores de definitely lost que tenes, si son despues de correr las pruebas no tenes de que preocuparte.

Saludos.-

**Comment by SantiagoOrlando29** [comment]
EXCELENTEEE.
Muchas gracias. Hasta el sábado!
