### ISSUE TITLE
Bitacoras viejas

### ISSUE THREAD

**Issue by SantiagoCarnezis** [sisoputnfrba/foro#2283]
Buenas

Tengo una duda sobre las bitacoras cuando ya hay un fs existente. En ese caso tienen que persistir los datos que ya estaban en el fs, pero mi problema es que ahora voy a tener en la bitacora del tripulante 1, las cosas que hizo el tripulante que ahora esta haciendo sus tareas, pero tambien las cosas que hicieron los anteriores tripulantes 1. 
A nosotros se nos ocurrio para no tener este problema, que cuando ya existe fs, se persistan los datos del oxigeno, basura y comida, pero se borren los datos de las bitacoras (los archivos, lo escrito en el blocks.ims y los bloques ocupados en el bitmap). Esto esta bien??
Lo implementamos de esta forma porque creemos que el tp apunta mas a que se persistan los datos de los files mas que de las bitacoras, pero por la dudas preguntamos

**Comment by iago64** [comment]
Buenas! Cómo va?

A riesgo de que se lea un poco fuerte, no nos importa lo que hagan con las bitácoras de ejecuciones anteriores.
La prueba de FS busca ver que se graben y después en la de sabotajes las bitácoras no las podemos sabotear, asi que siéntanse libres de hacer lo que les de la gana 😄 

Abrazo!

**Comment by SantiagoCarnezis** [comment]
Ok muchas gracias, entonces las borramos cuando ya existe un fs.

Saludos
