### ISSUE TITLE
Duda con la prueba de sabotaje

### ISSUE THREAD

**Issue by dbibe** [sisoputnfrba/foro#2285]
Hola! Como están?

Vengo a hacerles una consulta super rápida sobre el tiempo de sincronización en la prueba de sabotaje (que dice que es 1). Mi problema, que recien ahora me estoy dando cuenta, es que yo, además de mapear el blocks.ims y copiarselo a una "copia" para manejarlo, también mapeo superbloque.ims y se lo paso a una copia. Por lo tanto, en cada sincronizacion a disco sincronizaba el blocks y el superbloque (por el bitmap).

Como en las pruebas el tiempo de sincronización es 1, no me da el tiempo para cambiar con hexedit el superbloque.ims y mandarle el kill a imongo, por lo tanto se me autocorrige solo con la versión que esta en memoria. Si yo le aumento un poco el tiempo de sincronización como para llegar a que levante el superbloque modificado, el protocolo fsck me lo detecta, me lo corrige y me lo sincroniza a disco bien.

Mi pregunta es, cuando tenga que correr en imongo los sabotajes, podría aumentarle el tiempo de sincro como para mostrar el sabotaje de cantidad de bloques y bitmap bien? O ya voy cambiando lo que tengo, cambiando la forma que uso el superbloque en mi código?

Saludos!!

**Comment by RaniAgus** [comment]
¡Buenas! No hace falta tener el superbloque en una copia y sincronizarlo: pueden simplemente trabajar con el superbloque mapeado e ir actualizando el bitmap directamente. De esa forma, usando hexedit se deberían poder reflejar los cambios ni bien se guarden. Saludos

**Comment by dbibe** [comment]
Listo, ahi lo arreglé.
Muchas gracias !
