### ISSUE TITLE
[iMongo] Duda Superbloque.ims

### ISSUE THREAD

**Issue by rocioveloso** [sisoputnfrba/foro#2286]
Estábamos revisando el enunciado y a pesar de que tenemos todo lo necesario, nos surguió una duda. El enunciado en si no lo dice pero para el Superbloque.ims es necesario hacer una copia cuando se crea??? Porque sino la agregamos a la estructura.

**Comment by RaniAgus** [comment]
¡Buenas! No es necesario. De hecho, no recomiendo hacerlo ya que, como se comenta en #2285, esto nos lleva al problema de tener que elevar mucho el tiempo de sincronización para poder realizar los sabotajes. Saludos

**Comment by rocioveloso** [comment]
Ahh, genial!!! Gracias
