### ISSUE TITLE
ME FUNCIONA EN LOCAL PERO EN LA VM NO :C 

### ISSUE THREAD

**Issue by SantiagoIvan** [sisoputnfrba/foro#2287]
Buenas noches/dias/tardes!

Estamos con un problema. Después de muchas pruebas donde no rompía nada, ahora de la nada se rompen las Vms y no podemos testear ningún sabotaje. En local funciona todo perfecto, pero en las Vms obtenemos un error al enviar mensajes. ¿Como hacemos para debugear el error, cuando en local no rompe nada? Con valgrind nos rompe y no podemos hacer nada como ya mencionamos en otro issue #2271

**Comment by RaniAgus** [comment]
¡Buenas! Me re suena a que es un problema de networking... ¿Qué funciones están usando para iniciar el server y para conectarse como cliente? 

Me anticipo con un par de problemas comunes:

1- Tener hardcodeado "localhost" en algún lado (no importa si es client o server):
```c
int status = getaddrinfo("127.0.0.1", puerto, ...);
```
2- No iterar toda la lista de direcciones que devuelve `getaddrinfo` desde el lado del cliente (el struct tiene un parámetro llamado `ai_next` que te devuelve el siguiente elemento en la lista): https://github.com/sisoputnfrba/foro/issues/2000#issuecomment-739450264
```c
struct addrinfo *info, *p;

// getaddrinfo(...)

for(p = info; p != NULL; p = p->ai_next) {

    // socket() y connect()

}
```

Saludos

**Comment by SantiagoIvan** [comment]
Hola ! Paso a contestarte asi ya cierro el issue. El problema al final era otro. De tan quemados que estabamos no nos dimos cuenta y estabamos cerrando 2 veces un socket y bueno. Muchas gracias !!
