### ISSUE TITLE
[Tareas] Duda sobre el parámetro en 0 

### ISSUE THREAD

**Issue by IgnacioGomezL** [sisoputnfrba/foro#2288]
Buenas tardes, tengo una duda cuando las tareas de E/S tienen el parámetro en 0.
![IMG_20210806_152623](https://user-images.githubusercontent.com/62355244/128555659-4d631716-8229-4b1a-b972-10ca0eec5a3a.jpg)
Según este ejemplo si el parámetro es 0, se borra el archivo. ¿Se elimina sin borrar su contenido en blocks o primero se debería borrar todo el contenido y luego eliminar el archivo?

**Comment by iago64** [comment]
Buenas! Cómo va?

Simplemente marcan los bloques como libres en el bitmap y eliminan el archivo de metadata :)

Saludos.-

**Comment by IgnacioGomezL** [comment]
Genial, gracias!
