### ISSUE TITLE
Falla la conexion entre las vms de prueba

### ISSUE THREAD

**Issue by MartinSchvartz** [sisoputnfrba/foro#2290]
Buenas estamos probando con las vms de prueba que nos mandaron y nunca se nos logran conectar los módulos. En la misma pc nos funcionan las conexiones y andan bien los módulos. También cuando usamos ngrok y nos conectamos anda todo bien el tema esta cuando nos conectamos entre las vms de prueba de forma local.
No se si tiene algo que ver pero solo tenemos 2 vms para hacer las pruebas quizás un problema esta en que no todas las vms se conectan de forma local y una usa ngrok.

### 👍 Comportamiento esperado
Que todos los módulos se conecten correctamente de forma local

### 👎 Comportamiento obtenido
Los módulos solo pueden conectarse mediante ngrok

**Comment by iago64** [comment]
Buenas!

Consulta, cual de las 2 IPs que les pasamos están usando? la que dice local/privada o la pública? Porque si están usando la pública no se van a conectar jamás.

Saludos.-

**Comment by MartinSchvartz** [comment]
Estamos usando la local/privada

**Comment by iago64** [comment]
Otra consulta, si tiras un ping desde una maquina a la IP de la otra funciona? porque si se ven por ping entonces el problema puede ser que este en como están configurando los procesos.

Saludos.-

**Comment by MartinSchvartz** [comment]
Si tiramos ping a la ip local funciona bien , si tiramos ping a la ip publica no lllega nada. Pero seria raro que sea un problema de como estan configurados los procesos porque con ngrok las 3 vms se conectan sin problemas.

**Comment by RaniAgus** [comment]
¡Buenas! Ahí estuve viendo cómo están iniciando la conexión y por lo que veo están seteando el primer parámetro como NULL (lo cual está bien):
```c
	  if (getaddrinfo(NULL, puerto, &mi_info, &resultado) != 0) {
//	    printf("Error al parsear la direccion del socket\n");
	    exit(EXIT_FAILURE);
	  }
```
Pero les está faltando el flag `AI_PASSIVE`, que permite que `getaddrinfo` devuelva una dirección "wildcard" que se utiliza normalmente en servidores:
> If the AI_PASSIVE flag is specified in hints.ai_flags, and node
       is NULL, then the returned socket addresses will be suitable for
       bind(2)ing a socket that will accept(2) connections.  The
       returned socket address will contain the "wildcard address"
       (INADDR_ANY for IPv4 addresses, IN6ADDR_ANY_INIT for IPv6
       address).  The wildcard address is used by applications
       (typically servers) that intend to accept connections on any of
       the host's network addresses.  If node is not NULL, then the
       AI_PASSIVE flag is ignored.

Prueben si se resuelve agregando la siguiente línea:
```c
	  mi_info->ai_flags = AI_PASSIVE;
```

Saludos

**Comment by MartinSchvartz** [comment]
La verdad muchisimas gracias por meterte al codigo y fijarte, era eso el problema. 
Nos salvaste la vida realmente no lo habriamos encontrado nunca. 
Te amamos mucho 
atte: Cebollitas
