### ISSUE TITLE
Buscamos integrante para grupo de TP

### ISSUE THREAD

**Issue by yairtele** [sisoputnfrba/foro#2292]
Buenas, buscamos al último integrante para conformar el grupo. Actualmente somos 4 recursantes, con bastante conocimiento y un modelo de partida a seguir para hacer el TP. Consideramos fundamental el compromiso y clara comunicación con el grupo, así como también darle prioridad a la materia. Se valoran conocimientos de C.

Cualquier cosa comunicarse a ytelezon@frba.utn.edu.ar

Saludos!

**Comment by iago64** [comment]
Buenas! Vamos a estar centralizando (como de costumbre) las búsquedas de grupos e integrantes en un solo issue así nadie se pierde, este cuatri es el #2293 

Saludos.-

**Comment by yairtele** [comment]
Buenísimo, comento por ahí entonces y cierro este issue. Gracias!!
