### ISSUE TITLE
👩‍💻 Buscas Grupo / Integrantes para el 2c2021? Postea ACA! 👨‍💻

### ISSUE THREAD

**Issue by iago64** [sisoputnfrba/foro#2293]
Buenas!

Con el objetivo de unificar todos los post de búsqueda de grupos / integrantes, vamos a todo en este post.
_Les recomendamos encarecidamente que traten de **NO** publicar números de celular_ y limítense solo a los mails, tengan en cuenta que el foro es publico y pueden llegar a quedar en alguna lista de spam o que les hable gente que no quieran.

Saludos.-

**Comment by yairtele** [comment]
Buenas, buscamos al último integrante para conformar el grupo. Actualmente somos 4 recursantes, con bastante conocimiento y un modelo de partida a seguir para hacer el TP. Consideramos fundamental el compromiso y clara comunicación con el grupo, así como también darle prioridad a la materia. Se valoran conocimientos de C.

Cualquier cosa comunicarse a ytelezon@frba.utn.edu.ar

Saludos!

**Comment by victoriaguillosson** [comment]
Buenas, buscamos 2 integrantes para completar grupo. Somos 3 recursantes que ya tenemos bastante aceitada la dinamica del TP. Nos parece importante la comunicacion y compromiso con el grupo/tp. 

Dejo mi celular: 1121638701
Saludos!!

**Comment by SfaraLucas** [comment]
Buenas.

Buscamos a dos personas que esten dispuestas a un contrato de esclavitud con esta materia

Somos tres recursantes los cuales estan podridos de esta materia y este cuatrimestre vamos a promocionar si o si. El cuatri pasado nos dejaron dos personas, teniamos dos modulos funcionando al 100% con valgrind tirando 0kb de memoria perdida y recursamos porque no nos funco la sincro en uno de los modulos.

El objetivo es llegar al checkpoint presencial con el tp terminado.
Si estas dispuesto a laburar a ese nivel de intensidad hablame lucassfara@gmail.com

**Comment by Nicolas-Russo** [comment]
Buenas, estamos buscando a un integrante para el grupo. Es importante el compromiso con el tp y la materia.
Dejo mi celu: 1135200216
Gracias!

**Comment by DankyB** [comment]
Buenas, con @brunomassaccese y @armaldini buscamos 2 integrantes más. 
- Somos recursantes
- Tenemos conocimientos de C
- Estamos comprometidos con la materia, cursamos esta y no mucho mas.

Buscamos gente en la misma, preferentemente que tenga experiencia en TPs anteriores.

Si les interesa me pueden escribir a dbrosio@frba.utn.edu.ar
Saludos!

**Comment by TomasR264** [comment]
Hola, estamos buscando dos integrantes para completar el grupo, somos tres recursantes, dos trabajamos en memoria y una en file system en TPs pasados y nos vendria bien si tienen experiencia en planificacion a la hora de hacer el tp para poder aprobarlo de una vez.

Si alguno esta interesado, manden un mail a trossi@frba.utn.edu.ar
Saludos 🚀

**Comment by munetakakun** [comment]
Buenas, estoy buscando grupo, el cuatri pasado estuve con el módulo de planificación. Estoy cursando esta materia y otra más y laburo. Curso los lunes a la noche y cualquier cosa mi mail es dyamada@frba.utn.edu.ar
Saludos!

**Comment by GerrMunoz** [comment]
Buenas

Busco grupo. Estoy cursando esta y Teoría de Control. Laburo como programador backend hace dos años. Curso martes y jueves en la noche. Dejo mi correo: gmunoznieto@frba.utn.edu.ar

Saludos

**Comment by ayllon89** [comment]
Buenas,
Somos dos recursantes del cuatri pasado que buscamos completar el grupo, si alguno esta libre me escribe a layllonzelaya@frba.utn.edu.ar
Un saludo

**Comment by TBarbierii** [comment]
Buenas, estamos buscando **dos integrantes** para el grupo, ya la cursamos el cuatri pasado y buscamos personas que la hayan cursado anteriormente. En el TP anterior trabajamos en los módulos de Planificación y FileSystem, por lo tanto nuestra preferencia sería que tengan experiencia en el módulo de Memoria, aunque no tendríamos problemas en variar la organización de los módulos. Otra cosa que también nos interesaría es si disponen de disponibilidad horaria para realizar reuniones acerca del TP y dedicarle a la materia (ya que nuestra idea es sacarla este cuatrimestre **si o si**). Cualquier cosa les dejo mi mail tbarbieribedini@frba.utn.edu.ar  

Saludos!

**Comment by MatiasRosales** [comment]
Buenas
Con mi grupo estamos buscando 2 personas más para el tp. Somos 3 recusantes. El cuatri anterior cada uno se encargó de un modulo (File System, Planificación y Memoria) donde 2 personas no aportaron y no decidieron bajarse sino hasta pasado el 1er parcial haciendo la cursada y el tp mucho más dificil.
Necesitamos gente con compromiso para que desde el 1er momento de tener la consigna arrancar hasta llegar al checkpoint presencial con la grán mayoría de la implementacion terminada. Así nos enfocamos de forma mas tranquila a los parciales
Dejo mi mail: matias.rosales97@hotmail.com

Saludos

**Comment by abuergo** [comment]
Buenas! Soy recursante del cuatri pasado y estoy buscando un grupo **muy comprometido con la materia**, en preferencia gente que ya la haya cursado y sea activo/a en lo que respecta a la comunicación para trabajar en equipo y así **terminar el TP cuanto antes**. Curso miércoles noche/sábados tarde y cuento con las ganas y la suficiente disponibilidad horaria para liquidar la materia este cuatri si o si. 
Cualquier duda siéntanse libres: abuergo@frba.utn.edu.ar

Saludos!

**Comment by Damuchi99** [comment]
Propicios días!

Busco grupo. Estoy cursando esta materia y tres mas. Es la primera vez que voy a cursar esta materia y quiero llevarme de esta primera vez una buena experiencia, aprender mucho y por qué no, aprobarla. Curso sábados a la mañana.

Cualquier consulta tienen mi mail: daalvarez@frba.utn.edu.ar

Un saludo y tengan buen día!

**Comment by Matias-Balboa** [comment]
Buenas! Nos faltan dos integrantes para nuestro grupo, los tres somos recursantes. Buscamos gente comprometida con la materia, que tenga ganas de aprobarla y que sea activo con lo que respecta a la comunicación en equipo.
Saludos!

les dejo mi mail: matiasbp98@gmail.com

**Comment by ayllon89** [comment]
Buenas, nos faltan dos integrantes. Nosotros tres somos recursantes y buscamos gente con amplia disponibilidad horaria para tener reuniones de avance de como van llevando el proyecto.
Dejo mi email: layllonzelaya@frba.utn.edu.ar
Un saludo

**Comment by federiver91** [comment]
Buenas!! Busco grupo para el TP.

Soy recursante y el cuatri pasado estuve bastante con el módulo DISCORDIADOR (Planificación). Tengo el foco y la prioridad 100% en Sistemas Operativos. Tuve que recursar porque mi grupo abandonó las últimas dos semanas por el resultado obtenido en los parciales/recuperatorios. Con lo cual, personalmente la cursada la tengo bastante fresca y sabida. Toda mi atención va a ir al Trabajo Práctico.
Busco un grupo, fundamentalmente, que no se cuelgue. Que nos juntemos constantemente y tengamos avances (aunque sea pequeños) y haya una comunicación fluida. Me parece que ahí está la clave para aprobar. Que no pase ni 1 semana sin que haya habido reuniones, dailys, avances, commits, puestas en común, etc. De mi lado, voy a contribuir a que ello pase, pero si el grupo está conformada por gente que se conoce entre sí, mucho mejor y más fácil.
Voy a seguir hasta el final de la cursada sí o sí. Ya estoy grande y necesito meter este censurable y polémico TP de una vez por todas.

**Comment by dariolayme** [comment]
Buenas, 
Nos faltan dos integrantes. Buscamos gente con disponibilidad para tener reuniones de apoyo, revisión del TP, cosas de la materia, etc. Para ayudarnos entre todos.

Dejo mi email: dariolayme@gmail.com
Saludos,
DL.

**Comment by amendezkar** [comment]
Buenas

Somos un grupo de 4 recursantes, cursamos el cuatri pasado, por lo que la teoría de la materia practicamente la tenemos, por lo que la idea es enfocar en el tp, obvio sin olvidar la teoría y práctica.

Buscamos un 5º integrante, si está en una situación similar a la nuestra mejor, pero con que tenga la misma dedicación que nosotros nos alcanza.

Me pueden hablar por discord, me encuentran en el server de la cátedra (Agustín Méndez, con rol Alumn@ 1C2021).
Saludos

**Comment by nespada** [comment]
Hola!!

Soy recursante, estoy buscando grupo para el TP. Es la ultima materia de 3ro que me queda, así que con ganas de meterla si o si.
Tengo conocimientos básicos de C, Linux, Git y de los conceptos del TP (Conexion Cliente-Sv, Serializacion, Planificacion, Memoria, etc).
Dejo mi mail: nespada@frba.utn.edu.ar

Saludos, Mariano!!

**Comment by Dylanhurtado1** [comment]
Buenas,
Somos un grupo de 2 recursantes, y estamos buscando integrantes que quieran aprobar la materia y dedicarle tiempo al tp, nos faltan 3 integrantes y la idea es empezar  haciendo pequeñas tareas para ir avanzando lo más rapido que podamos, gracias.
mail :dylanhurtado2404@gmail.com

**Comment by lucianoj77052012** [comment]
Buenas!
Cómo están? Espero que estén todos muy bien.

Me introduzco brevemente:

Mi nombre es Luciano. Tengo conocimientos generales de programación y sistemas operativos, tengo experiencia en hacer front-end de páginas web y también estoy aprendiendo Angular y SQL para la parte de backend. Por otra parte, trabajo en el área de sistemas desde hace 3 años, por lo cual estoy familiarizado con el vocabulario y la terminología que se usan en el área.

Actualmente en mi grupo somos dos miembros. Lo único que buscamos es gente con muchas ganas de meterle a la materia. No buscamos necesariamente gente con experiencia o conocimientos previos.

Si les interesa formar parte de nuestro grupo, por favor manden mail a: lpaolini@frba.utn.edu.ar

Espero su respuesta!

Saludos y que tengan todos un muy buen día,
Luciano.

**Comment by Britanico10** [comment]
Buenas,
Busco grupo. Es la única materia que curso y debo de 3ero.
Dejo mi mail: myoo@frba.utn.edu.ar

**Comment by LucasK237** [comment]
Buenas! Ando buscando grupo para el TP. Me llamo Lucas es la primera vez que estoy cursandola.
Dejo mi mail: lkoch@frba.utn.edu.ar

**Comment by GreenGeer** [comment]
Buenas Gente ! ! !
Estamos buscando dos integrantes mas para nuestro equipo , somos la mayoría recusantes con mucho tiempo que quieren ir por todo .
 En  lo posible buscamos compañeros que ya hayan experimentado antes la dificultad e importancia de esta materia , que tenga tiempo libre y si es mucho pedir que sepan C.
Mandar mail a : germanvautier@hotmail.com
Desde ya , suerte a todos este cuatri : )

**Comment by boltin544** [comment]
Buenas! somos 3 chicos ya, estamos buscando a los restantes 2. La estamos cursando todos por primera vez. Buscamos gente comprometida y dedicada para lograr la promoción de esta materia. dejo mi mail: tboltin@frba.utn.edu.ar

**Comment by NicolasWallovits** [comment]
Hola gente! 

Estamos buscando un último integrante para completar el grupo para el TP. Hasta ahora somos 4 algo vejetes con más de una recursada encima, de los cuales algunos incluso han aprobado TPs anteriores y se quedaron por la bendita teoría, o viceversa también. Para todos es la única materia que vamos a estar cursando, y la idea que tenemos es comprometerse y dedicarle el tiempo necesario para poder llegar a término con las entregas.

Si a alguno le interesa me escribe: nicowallovits@frba.utn.edu.ar

Saludos,
Nico

**Comment by victork95** [comment]
Buenas
Busco grupo para el TP. Me llamo Victor y es la primera vez que estoy cursandola.
Dejo mi mail: kim.victor95@gmail.com

**Comment by danimontesano** [comment]
Hola, Buenas tardes!
Buscamos a un integrante para nuestro grupo. El año pasado recursamos debido al TP, ya que nos confiamos un poco con las fechas, pero los 4 promocionamos ambos parciales.
Estamos buscando principalmente a alguien que haya recursado y trabajado en el planificador, que sea responsable, esté dispuesto a trabajar bastante durante este cuatri y sobre todo esté atento a los canales de comunicación.
Cualquier duda no duden en contactarse: mecsafonso@gmail.com

Saludos

**Comment by adrianquispe** [comment]
Buenas ando buscando grupo, primera ves cursando si alguien le falta llenar me uno.
mail: adrianq.de.floresta@gmail.com

**Comment by rpages2020** [comment]
Hola, somo tres recursantes y estamos en búsqueda de dos mas.  Estuvimos muy cerca de completar el tp y todos teníamos los parciales como para promoción o firma. Si hay recursantes que quieran volver a darlo todo este cuatri chiflen.

**Comment by iribs97** [comment]
Buenas! Estoy buscando grupo. La cursé el cuatri pasado así que la teoría la tengo fresca y mi idea es dedicarle a full al TP.
Mi mail es istorozuk@frba.utn.edu.ar

**Comment by adrielaranaa** [comment]
Buenas a todos! Es la primera vez que curso esta materia y espero llevarme una linda experiencia.
Si a alguien le falta un integrante avíseme por email: adrielaranaa@gmail.com

**Comment by facu777** [comment]
Hola somos 3 chicos ya todos hicimos el tp antes. Nos conocemos los 3 y la idea es meterle de forma constante hasta el final
contacto :
facundofranco2008@gmail.com

**Comment by rodrigomc1** [comment]
Buenas, busco grupo de TP, curso los miércoles a la noche. Dejo email: rodrigomt.cl@gmail.com

**Comment by faustofusse** [comment]
Holaa, estamos buscando grupo. Somos 2 (un recursante y uno no) que ya nos conocemos y estamos con muchas ganas de sacar la materia en este cuatri. Si alguien tiene 2 lugares o esta solo y se quiere sumar mande mail a faustofusse@gmail.com.

**Comment by ganchipi** [comment]
Hola, estamos buscando un integrante para nuestro grupo. Somos 4 recursantes y queremos incorporar un 5to que tenga disponibilidad horaria, al menos 3 días con 4hs en la semana para programar, con conocimientos de C y priorice esta materia. Les dejo mi mail ganchipi@frba.utn.edu.ar. Saludos.

**Comment by tselvaggi** [comment]
Buenas! Estamos buscando un último integrante para terminar de conformar el grupo de TP. 

selvaggitomas@gmail.com

**Comment by gabiquintana** [comment]
Hola estamos buscando 3 integrantes, somos 2 ambos recursantes, logramos terminar el tp del cuatri anterior pero recursamos por los parciales...pensamos aprobarla siosi este cuatrimestre.  mi mail gabrielqtemoche@hotmail.com

**Comment by leandrodf** [comment]
Buenas, estoy buscando grupo todavía, soy uno solo, estoy cursando viernes a la noche K3073, mi mail es leandrofasanelli@gmail.com

**Comment by Batrex90** [comment]
Buenas! Estamos buscando al último integrante para conformar nuestro grupo. Algunos somos recursantes, por lo que buscamos gente que tenga ganas de sacar el TP adelante e intentar promocionar la materia. Les dejo mi mail:
[feraduriz@frba.utn.edu.ar](url)
Éxitos para todos!

**Comment by WalterJeronimoCabrera** [comment]
Buenas noches! Estamos buscando 3 integrantes para completar el grupo de TP.
Email: jeronimo.cabrera.jc@gmail.com

**Comment by alexargb** [comment]
Buenas! Estamos buscando un último integrante para realizar el TP, somos 4 desarrolladores, uno de nosotros recursante.
Dejo mi mail por si hay algún interesado: alexarguellobueno@gmail.com

**Comment by frosimanuel** [comment]
Buenas, estoy buscando grupo, soy recursante llegué a encarar una buena parte del tp el cuatri pasado y la idea es cerrar esta materia si o si este año. Dejo mi mail: frosimanuel@gmail.com

**Comment by IESTomasAraujo** [comment]
Buenas tardes, Mi nombre es Tomas Araujo. Soy recursante y busco grupo para el TP con ganas de meterle al código y bien predispuesta con la materia. Tengo conocimientos en C , en el uso de eclipse y Commons Library, Tengo pensado en aprobar la materia en esta cursada. Mi mail es : tomasaraujo1999@hotmail.com

**Comment by SamuelLedezma** [comment]
Hola que tal estoy buscando grupo si alguien le falta aviseme por favor
samuelrodrigoledezmajaldin@gmail.com

**Comment by iago64** [comment]
Buenas! Cómo va?

Como se dijo en el post https://www.utnso.com.ar/2c2021-cierre-de-inscripciones-de-grupos/ Ya se encuentra cerrada la inscripción de grupos y se conformaron / confirmaron los grupos.

Ya se encuentran abiertos los cambios de grupos 😸 
Saludos.-
