### ISSUE TITLE
Notificaciones limitadas

### ISSUE THREAD

**Issue by perum10** [sisoputnfrba/foro#2295]
Hola, tengo este programa, es para un sensor ultrasónico conectado con Blynk, que si detecta una distancia mayor a la debida se envía una notificación y un E-mail. Funciona bien, todo se cumple, pero en la parte de if, se envían notificaciones ilimitadas, ¿hay alguna manera de hacer que solo envíe una y pasado un tiempo vulva a notificarme si la distancia sigue siendo mayor a la indicada?, todo esto mientras sigue mostrando en la pantalla de Blynk la distancia en tiempo real. Muchas gracias!, aquí mi código.

#define BLYNK_PRINT Serial
#include <ESP8266WiFi.h>
#include <BlynkSimpleEsp8266.h>
const int triggerPin = 5;
const int echo = 4;

long duration;
int distance;

char auth[] = "";
char ssid[] = "";
char pass[] = "";
void setup(){
  Serial.begin(9600);
  Blynk.begin(auth, ssid, pass);
  pinMode(triggerPin, OUTPUT); // Sets the trigPin as an Output
  pinMode(echo, INPUT); // Sets the echoPin as an Input
}

void loop(){
  Blynk.run();
  digitalWrite(triggerPin, LOW);
  delayMicroseconds(2);
  digitalWrite(triggerPin, HIGH);
  delayMicroseconds(10);
  digitalWrite(triggerPin, LOW);
  duration = pulseIn(echo, HIGH);
  distance= duration*0.034/2;
  Blynk.virtualWrite(V5, distance);

  if (distance >= 20){
    Blynk.notify("ESP8266 Alert -> distance >= 20");
    Blynk.email("***************", "***************", "");
  }

   
  Serial.print("Distance: ");
  Serial.println(distance);
}

**Comment by RaniAgus** [comment]
Hola, ¿qué tal? Este es un foro de consultas para la cátedra de Sistemas Operativos de la UTN FRBA. Saludos.

**Comment by sciciliani** [comment]
Hola @perum10. Es importante que tengas en cuenta que las opciones que te da un arduino son poderosas pero algo limitadas. Concretamente una función de setup() y luego el loop() que simplemente itera de forma infinita.

Tu código perfectamente activa el sensor calcula el tiempo de rebote de la señal ultrasonica para obtener la distancia. Luego si esta es mayor o igual a 20 manda la notificación.

A continuación vuelve a ejecutar exactamente el mismo código una y otra vez, generando (si aplicara) mas y mas notificaciones.

Cosas que podrias hacer:

1) Poné una demora entre medición y medición usando delay() (en milisegundos). Entiendo que no necesitas algo tan frecuente, sobre todo si vas a mandar un mail.

2) En cada iteración incrementa una variable (i = i + 1). Por ejemplo si iterás cada un segundo, ponés un if para que solo mande el mail si pasaron mas de 300 segundos desde la ultima notificación.
