### ISSUE TITLE
Problemas compilando el proyecto

### ISSUE THREAD

**Issue by joseZudaire** [sisoputnfrba/foro#2296]
Buenas tardes! No se si lo estoy haciendo correctamente, pero no logro compilar el proyecto. Seguí el video que pusieron en el doc (https://www.youtube.com/watch?v=PgrORWmUxkI&ab_channel=UTNSO), pero me aparece el siguiente error:
make all
make: ***No rule to make target 'all'. Stop.

Alguna idea de qué hice mal?

**Comment by gastoncastineira** [comment]
Buenas

Ese error lo único que me dice es que falló la compilación. Me podrás dar un poco más de información y contexto de qué hiciste? Qué ves en Eclipse y qué importaste después del clone por ejemplo

**Comment by RaniAgus** [comment]
¡Buenas! Ahí estuvimos revisando y mil disculpas, para este cuatrimestre hicimos un rework a la estructura de los proyectos del TP0 para que los puedan importar directamente como proyectos de Eclipse pero se nos olvidó actualizar ese link. 

Debía apuntar hacia [este video](https://www.youtube.com/watch?v=Q8wfpu38PMc), ahí lo corregimos :)

Saludos

**Comment by joseZudaire** [comment]
Muchas gracias! Ahí lo reviso entonces

**Comment by joseZudaire** [comment]
Buenas! Ahí miré el video y lo seguí tal cual. Después abrí el client y el server por separado haciendo File->Open Projects from File System... Los compilé y anduvieron perfecto. Saludos!!

**Comment by gastoncastineira** [comment]
¡Buenísimo!

Si ya no te quedan dudas, ¿podés cerrar el issue?

**Comment by joseZudaire** [comment]
Dale!
