### ISSUE TITLE
Problemas con el alta de alumno

### ISSUE THREAD

**Issue by Nicolas-Russo** [sisoputnfrba/foro#2297]
Buenas, me quise dar de alta en el sistema de inscripciones pero me dice que mi legajo ya esta en la base de datos. Como hago?
Gracias.

**Comment by gastoncastineira** [comment]
Buenas

![image](https://user-images.githubusercontent.com/28161802/130530717-a2408f2d-7d8c-439b-b795-11418eb189ce.png)

Ese no sos vos? Te veo bien anotado y con esta misma cuenta de Github. Te aparece el error si intentás logearte ahora?

**Comment by Nicolas-Russo** [comment]
Ahi volvi a entrar y no me tiro ningun error. Nose que paso.
Gracias!
