### ISSUE TITLE
Problema al compilar el tp0

### ISSUE THREAD

**Issue by ezequielmalfonso** [sisoputnfrba/foro#2298]
Buenas, cuando quiero compilar le tp0, sin haber agregado nada, me arroja el siguient error:
![imagen](https://user-images.githubusercontent.com/14969101/131230347-8e3199e4-1bfe-4eb9-8d3f-59125426bb31.png)

Cuando hago clic sobre MENSAJE, me da la opcion para ir a dos archivos utils.h uno ubicado en client y otro en server, puede ser que esten repetidas las variables?

Saludos.-

**Comment by MatiasRosales** [comment]
Buenas.
Me pasó lo mismo. El problema fue importar el projecto en eclipse todo el tp0
Lo solucioné importando a client y server de forma separada
Saludos

**Comment by ezequielmalfonso** [comment]
Hola, ah ok voy a probar.
Muchas gracias.-

**Comment by tferraro** [comment]
Buenas!

Seguramente viene por lo que dice Mati 😁
--------------
Dejo un comment de algo que me pareció copado remarcar. Para la próxima, **muy importante**, fijate que en los templates de Issues hay uno que dice `Issue: Necesito ayuda de programación en C` y adentro habla de algo mucho muy impotante:
```
No subas capturas de pantalla, copiá el código relevante a tu problema y pegalo acá. Podés darle formato código con (Ctrl + 'e').
```

Esto no es trivial (y no persé para nosotros), sino para que cualquier otro compañero que esté capáz dando vuelta con le mismo error, *pueda usar el buscador de issues y encontrar este issue*.

Las imágenes son una cagada porque son in-indexables y con un título genérico de "Problema al compilar el tp0" capas queda inadvertido.

Mis dos centavos en esta es, recordemos siempre usar los templates y de llenar la mayor parte de información que podamos, mejora la velocidad de resolución, ayuda a simplificar las cosas, ayuda a futuros compañeros; todo un win-win con poco esfuerzo (? 😜 
------------
Dicho eso, contanos si te sirvió. 👋

**Comment by ezequielmalfonso** [comment]
Buenas, gracias  por la aclaracion de las imagenes.
Por otro lado me sigue sin funcionar, exporte el cliente y el server por separado, cuando los compilo me arroja el mismo error, no se si me falta hacer algo despues de importar el proyecto.
Dejo el error que me marca eclipse:

12:59:30 **** Build of configuration Default for project server ****
make all 
make: *** No rule to make target 'all'.  Stop.

12:59:31 Build Finished (took 948ms)

Y cuando corro el server desde consola me tira lo siguiente:
WARNING] 13:02:25:992 Servidor/(5359:5359): Operacion desconocida. No quieras meter la pata

Todavia no hice ningun paso del pdf, no se si vendra por ahi?

Gracias.-

**Comment by ezequielmalfonso** [comment]
Solucionado!!
Dejo la solución por si a alguien le sirve:

You need to change your project settings so that Eclipse-CDT manages your Makefiles for you.

    Select Project->Properties from the menu bar.
    Click C/C++ Build on the left in the dialog that comes up.
    Under the Builder Settings tab on the right, select "Generate Makefiles automatically" under the Makefile generation section.
    Hit OK and build again.

NOTA: Encontre la solución en Stackoverflow.

Saludos.-

**Comment by tferraro** [comment]
Ohhh, si!
El issue persé, para dar un poco más de dato, viene por el lado de *quien maneja el Makefile*, que es el archivo que ser corre con el comando `make` que tiene las directivas para compilar (ejecutando el compiler gcc con todos los flags y demaces).

Eclipse funciona de 2 formas, o usa tu pripio Makefile, o autogenera uno. Posiblemente al importar el proyecto hayas seleccionado "Usar mi propio makefile" (te debo las exactas palabras 😛 ) y por eso necesitaste decirselo a mano. Capas también Eclipse se haya mambeado y como detecta que hay proyecto, pero no hay Makefile autogenerado por el "asuma", que así lo queres.
Todo es posible (?

**Comment by tferraro** [comment]
> By the way, si el issue anda solucionado, pegado un close al issue 💪
