### ISSUE TITLE
Problema al levantar VMs en MacOS Chip M1

### ISSUE THREAD

**Issue by ccalvoromero** [sisoputnfrba/foro#2299]
Hola, como están?

Estuve teniendo problemas para levantar VMs con cualquier software. 
Investigando, entiendo que el problema radica en mi computadora con chip M1, que por la arquitectura con la que cuenta aún no hay forma de levantar máquinas con VirtualBox, VMware, etc.. aunque leí que están camino a que eso se pueda hacer. 
Para llegar a esta conclusión me ayudó esto #2092 (el error que tenemos es el mismo), a un compañero con el mismo SO pero con procesador Intel, probar lo indicado en ese issue sí le funcionó pero a mi no, por lo que fuimos descartando distintas posibilidades.

### 📦 Especificaciones de la VM
- Versión de VirtualBox: 6.1.26
- Memoria RAM asignada: 2GB

### 🖥️ Especificaciones del host
- Sistema Operativo y versión: MacOS Big Sur 11.5.2
- Memoria RAM: 16GB
- Procesador: Apple M1 (ARM)

Encontramos un approach, pero no estamos seguros que sea el mas indicado y es el siguiente:
Instalé Parallels para Mac, lo cual a priori funciona para chips ARM. Hasta ahí ok. El punto acá es que solamente me permite levantar o crear imágenes basadas en esa arquitectura (lógico) y la de la cátedra por lo que vi, dista bastante de eso.
Finalmente, para probar, pude levantar una [VM con Ubuntu Server pero de tipo ARM](https://ubuntu.com/download/server/arm) con ese soft y hasta ahora funciona sin problemas. El tema es que imagino que puede haber problemas de compatibilidad a la hora de compilar y probar (más a bajo nivel)  con mis compañeros de equipo que tienen instalada otra VM.

En este punto, que me recomiendan hacer? Hago este post para ver si a alguien se le ocurre algo que no este teniendo en cuenta.
Seguir con esta solución y terminar de instalarle todo lo necesario para la materia, corriendo el riesgo antes mencionado? 
Llorar en posición fetal?
Mandarle algún malware a Apple?

Desde ya, muchas gracias.
Saludos,
Cris

**Comment by iago64** [comment]
Buenas! Cómo va?

Es medio un bardo usar los chips con M1 porque como bien decis es una arquitectura diferente, lo bueno es que si tenes ubuntu server instalado y corriendo en parallels, la cantidad de problemas se deberian reducir a casi 0 :)

Como primera medida, fijate en la [sección de las VMs del blog](https://www.utnso.com.ar/recursos/maquinas-virtuales/) que justo están los paquetes que tienen instaladas ambas VMs (en principio son la misma vm server solo que la de lubuntu le tiramos un par de paquetes extra para que tenga entorno gráfico).

Después, el único que puede ponerse medio goma y "chillar" es gcc que es el compilador de C, por lo que después de instalar los paquetes si te copas y tiras un `gcc -v` en la terminal y pasas el resultado podemos checkear que no este muy desfasado y que genere algún bardo 😄 

Saludos.-

**Comment by ccalvoromero** [comment]
Hola Dami, como estás?

Antes que nada gracias por la ayuda. 
Ahí tire los comandos para instalar tanto los paquetes de Ubuntu Server como los de Lubuntu.

De Ubuntu Server:

> Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libreadline-dev' instead of 'libreadline6-dev'
E: Unable to locate package libevent1-dev
E: Unable to locate package libreadline6

De Lubuntu:

> Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package gnome-do

Esto es normal?

Finalmente, si tiro gcc -v me da:

> Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/9/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-17ubuntu1 20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)

Saludos,
Cris

**Comment by tferraro** [comment]
El análisis de gcc te lo debo 😆 

Peeeero, lo que si te puedo confirmar, es uqe libreadline6 ya no está más como paquete.
Posiblemente no haya mucha diferencia contra la actual, libreadline8, peeero si la vás a usar durante el TP, le haría doble check de que en una VM funcione (para que no haya cambiado ningún metodo, fija que no, pero probar sobre al final del cuatri esto no cuesta nada (?)).

**Comment by iago64** [comment]
Aloha!

Paso a confirmar que la versión de gcc (9.3.0) esta bien, al menos hasta esa testeamos algunas cosas y no hay problema 😄 
De todas formas denle bola a lo que dijo Tom, testeen en alguna vm x86.

Saludos.-

**Comment by tferraro** [comment]
Holiss @ccalvoromero como fue eso? Si anduvo joya no te olvides de cerrar el issue! :D

**Comment by ccalvoromero** [comment]
Hola chicos,

Perdón que colgué el issue. Tuve que instalar cosita más cosita menos, pero parece que ya quedó. Cualquier otro inconveniente que me surja, creo otro nuevo que corresponda con el problema en cuestión.

Muchas gracias,
Cris

**Comment by dlopezjoffreutn** [comment]
Buenas! Yo estoy con una M1 y me paso algo parecido! Con [UTM](https://mac.getutm.app/) pude setupear todo de 0 con mucha tranquilidad e instalar todos los paquetes listados en https://www.utnso.com.ar/recursos/maquinas-virtuales/ pero la instalacion de ruby falla 😞

**Comment by dlopezjoffreutn** [comment]
Buenas! Yo estoy con una M1 y me paso algo parecido!

Con [UTM](https://mac.getutm.app/) pude levantar una [iso de Ubuntu con arq ARM](https://ubuntu.com/download/server/arm), setupear todo de 0 con mucha tranquilidad e instalar todos los paquetes listados en https://www.utnso.com.ar/recursos/maquinas-virtuales/ pero la instalacion de ruby falla 😞

Con el ultimo comando `rvm install --default ruby-head` tira estos errores: 

<img width="765" alt="image" src="https://user-images.githubusercontent.com/82044090/162767218-332267d7-3d7e-45f1-9f08-ca183e118547.png">

Parece que no esta supporteado TruffleRuby todavia para la arquitectura de Apple Sillicon (arm64) pero yo estoy dentro de la VM, no deberia tener amd64? Me pasa lo mismo instalando el .deb file de Google Chrome y VSCode. 

Si alguno conoce del tema desde ya agradezco ideas para probar cositas! Saludos 👋

**Comment by RaniAgus** [comment]
¡Buenas @dlopezjoffreutn! ¿Podrías abrir un nuevo issue con tu duda como se especifica en las [reglas del foro](https://github.com/sisoputnfrba/foro/blob/master/README.md)? También recordá copiar el texto con el error en lugar de pasar una captura. Saludos
