### ISSUE TITLE
Buenas noches, estoy intentando instalar las guest additions en la VM pero me arroja el siguiente error

### ISSUE THREAD

**Issue by FedeFuente77** [sisoputnfrba/foro#2300]
### 📦 Especificaciones de la VM
- Versión de VirtualBox: 
- Memoria RAM asignada:

### 🖥️ Especificaciones del host
- Sistema Operativo y versión:
- Memoria RAM:
- Procesador:

**Comment by iago64** [comment]
No hay detalle del error, cerramos el issue.

Saludos.-
