### ISSUE TITLE
Issue al intentar instalar las guest additions en  VM

### ISSUE THREAD

**Issue by FedeFuente77** [sisoputnfrba/foro#2301]
Buenas noches, estoy intentando instalar las guest additions en la VM pero me arroja el siguiente error

![Issue VM](https://user-images.githubusercontent.com/29346625/131234305-0157e8ce-8c0c-46a9-aee0-2778e0beae87.png)

**Comment by iago64** [comment]
Buenas! Cómo va?

Creo que posteaste sin leer algo importante del template y es que: 
**Si obtuviste por consola o por pantalla algo que pueda ayudar a darnos más contexto, no subas capturas de pantalla, copiá y pegá el texto.** 
Esto que vas a ver a lo largo del cuatrimestre que nos ponemos recontra gedes es porque alguien mas puede estar teniendo el mismo problema y con el buscador no puede buscar en capturas de pantalla.

Ahora si, habiendo terminado el headsup, lo que te dice ahí llevado al argentino: _Che no puedo hacer cambios en el kernel hasta que no reinices_ la VM, con lo cual si reinicias la VM ya van a estar instaladas las Guest Additions 😄 

Saludos.-

**Comment by GonzaloMartinezSa** [comment]
Buenas. Seguí las instrucciones al pie de la letra, como aparece en el video, y llegué a lo mismo. También quise copiar y pegar lo que me apareció en consola, pero no me deja porque lo estoy copiando desde la máquina virtual.

Como dije, lo hice tal cual, pero llegué a lo mismo que el compañero. Cerré sesión y volví a iniciar para ver si cambiaba y nada, le di a apagar y la volví a prender y nada. No toqué nada más después de eso, pero no sé que está mal.

Comparando con el video, hasta "Installing additional modules ..." todo básicamente igual. 

@FedeFuente77 lo solucionaste?

Estoy en Windows 10.

**Comment by GonzaloMartinezSa** [comment]
Como actualización, lo que no funciona es lo de que se ajuste sola la pantalla. Lo de directorio bidireccional y carpetas compartidas sí me funciona.

**Comment by FedeFuente77** [comment]
Despues de ese mensaje de error, actualice la versión del SO desde la VM y se soluciono. Saludos

**Comment by GonzaloMartinezSa** [comment]
Buenas, confirmo que hice eso, actualicé la versión del SO desde la VM y funcionó. Gracias!

**Comment by iago64** [comment]
Perfecto, si ambos pudieron solucionar el inconveniente damos por cerrado el issue 😄
