### ISSUE TITLE
Problemas para instalar los GuestAdditions en la VM

### ISSUE THREAD

**Issue by AndresBettinelli** [sisoputnfrba/foro#2302]
Buenas!

Issues:
1. No puedo copiar-pegar desde fuera de la vm hacia adentro, ni a la inversa. (solucionado)
2. Tras instalar la los GuestAdditions y reiniciar la virtual, me figura mensajes de error detallados más abajo.

Descripción de como ocurrió el problema:

- Descargué la versión Lubuntu v5.0.1 para desarrollo con entorno gráfico liviano del siguente link:
https://www.utnso.com.ar/recursos/maquinas-virtuales/
- Instalé la virtual box v. 6.1.26, también lo probé con la v. 5.2.44 pero pareciese ocurrir el mismo problema.
- Creé una nueva maquina virtual seleccionando tipo Linux, versión Ubuntu (32-bit). Le puse 2048 mb de memoria.
- Siguiendo las instrucciones del [video Instalar las Guest Additions de VirtualBox en Lubuntu](https://www.youtube.com/watch?v=G3rFKfyoQEs), fui a Dispositivos -> Insertar imagen de CD de las "Guest Additions"
![image](https://user-images.githubusercontent.com/11705986/131261189-3d568205-9a51-45d6-b967-7b2a6de03413.png)
- Selecciono la opción de abrir y me abre una carpeta en /media/utnso/VBox_GAs_5.2.44 
![image](https://user-images.githubusercontent.com/11705986/131261302-11b9a505-38fb-4e88-9ec7-89fe64016646.png)
- Siguiendo el video, abro una consola con Ctrl + Alt + t y ejecutó los sig. comandos:
`cd /media/utnso/VBox_GAs_5.2.44`
`sudo ./VBoxLinusAdditions.run`
- Me aparece el sig. mensaje (esto es en el v5.2.44)
![image](https://user-images.githubusercontent.com/11705986/131261397-82470c20-39c2-4412-a9a1-ced32d913b8f.png)
Detalle del texto (notese el inconveniente del issue 1)

> Verifyng archive integrity... All good.
Uncompressing VirtualBox 5.2.44 Guest Additions for Linux........
VirtualBox Guest Additions installer
Copying additions installer modules ...
Installing additional modules ...
VirtualBox Guest Additions: Building the VirtualBox Guest Addition kernel modules. This may take a while.
VirtualBox Guest Additions: To build modules for other installed kernels, run
VirtualBox Guest Additions:  /sbin/rcvboxadd quicksetup <version>
VirtualBox Guest Additions: Building the modules for kernel 4.4.0-116-generic.
update-initramfs: Generating /boot/initrd.img-4.4.0-116 generic
VirtualBox Guest Additions: Running kernel modules will not be replaced until the system is restarted
VirtualBox Guest Additions: Starting
VirtualBox Guest Additions: modprobe vboxsf failed

En la v6 me aparece lo sig:
![image](https://user-images.githubusercontent.com/11705986/131262082-c03a75f2-af81-48cf-a161-c1e46882aa3d.png)

En esta no me figura un fail pero tampoco afirma que haya salido todo bien

En el video figura un mensaje final conm un done, como me tira ese failed creo que algo salió mal.
- Cierro la sesión y vuelvo a abrirla y me salen varias notificaciones al iniciarla.
![image](https://user-images.githubusercontent.com/11705986/131262211-d51fabd4-0b84-4caf-b571-78ca105c74b8.png)
El primer mensaje dice
VBoxClient: Failed to connect to the VirtualBox kernsel service, rc=VERR_ACCESS_DENIED
El último dice
VBoxClient: Dnd: Failed to connect to the VirtualBox kernsel service, rc=VERR_ACCESS_DENIED

Tras hacer la instalación de los Guest Additions, la pantalla se autoajusta (al menos en la v 5). Por lo que creo que algo debió haber instalado correctamente, pero debido al mensaje de fail y al no poder copiar-pegar quería consultar cual puede ser el problema.

Desde ya muchas gracias. Disculpen si esto ya esta consultado, no lo encontré pero me imagino que debe ser una consulta común.

Edit: Por si sirve, encontré que lo del copiar-pegar se debía a no tener la opción habilitada en las configuraciones de la maquina virtual.
![image](https://user-images.githubusercontent.com/11705986/131262871-54a8d0ac-88d3-4ba4-88d2-9ded7c9aac1f.png)

**Comment by tferraro** [comment]
👋 Buenas!

Fijate si hacer lo que dicen por aquí te sirve https://stackoverflow.com/a/54825733

Por otro lado, desde que SO host lo estás corriendo? (Porque algo que dice `VERR_ACCESS_DENIED ` me da la sensación que es un problema de permisos con el SO host, tipo, faltando algún "ejecutar como administrador" o alguna huevada del estilo)

Contanos que onda :)

**Comment by tferraro** [comment]
De hechoooo, me dicen por la cuca que hay unos cuantos threads en el foro ya resueltos, por ejemplo este #1662.
