### ISSUE TITLE
Corriendo en Eclipse y por terminal

### ISSUE THREAD

**Issue by joseZudaire** [sisoputnfrba/foro#2303]
Este fin de semana estuve adelantando con el TP0, encarando la etapa 3, y me encontré que si yo corría client.c en Eclipse, se ejecutaba perfectamente, mostrandome todos los log_info que había programado y pidiéndome el input por consola. Ahora, si yo corría el server.c por Eclipse y por terminal corría el makefile de client.c, se generaba un error en la ejecución del makefile (segmentation fault).
El error parece estar cuando hago config = config_create("tp0.config"). Hice un if() para evaluar si el config_create me devolvía un valor nulo, con un log_info adentro para ver si entraba o no.
En el primer caso no entraba, en el segundo sí.
¿Qué estoy haciendo mal (o ejecutando mal)?
Adelanto que para ejecutar el makefile entro en la carpeta Debug del client... Aviso porque algunos compañeros al parecer tienen el makefile dentro del src y en mi caso no se generó.
Otra cosa que también adelanto es que estoy muy verde, así que si tienen material o videos que me ayuden, por favor, denme los links.
Saludos y muchas gracias!

**Comment by gastoncastineira** [comment]
Buenas!

Eso pasa porque no está encontrando el archivo de config en la ruta que le estás pasando. Cuando no le especificas la ruta completa, toma la ruta relativa de la misma carpeta de donde sea que lo estés corriendo.

**Comment by gastoncastineira** [comment]
Buenas!

Eso pasa porque no está encontrando el archivo de config en la ruta que le estás pasando. Cuando no le especificas la ruta completa, toma la ruta relativa de la misma carpeta de donde sea que lo estés corriendo. 

El tema es que las rutas relativas en Linux son en función de donde estés ejecutando, y no de donde esté el ejecutable (y capaz por eso te esté fallando también)
Si yo hago ./Degug/tp0.o y el config está en /Debug/to0.config, no va a encontrar el config porque la ruta que estás pasando es ./tp0.config

Si te dejé más confundido, capaz [este post](https://mgarciaisaia.github.io/tutorial-c/blog/2015/04/23/rutas-argentinas/) de otro ayudante tiene varios ejemplos que capaz te ayuden
Si algo no queda claro, volvé a preguntar y lo seguimos viendo :)

**Comment by RaniAgus** [comment]
¡Buenas! Para agregar, el rol que cumple el makefile es únicamente el de compilar el proyecto. En el fondo, si mirás los comandos que ejecuta al tirar un `make`, vas a ver que lo único que hace es correr `gcc` varias veces: 
- Primero, para "traducir" los archivos de código C a código assembly (genera los `*.o` en `Debug/`)
- Luego, los junta para generar el ejecutable final en código máquina. 

Lo que hace Eclipse al darle al martillito de "Build" es ejecutar `make` al igual que puede hacer uno desde consola (el resultado termina siendo el mismo), así que no te preocupes por eso, da lo mismo en donde lo ejecutes.

Dicho esto, el makefile que genera Eclipse siempre se guarda dentro de `Debug/` o `Release/` (depende de la configuración que le pongas). Quizás tus compañeros estén usando el TP0 de algún cuatri anterior y por eso lo tengan en otro lado.

Saludos

**Comment by joseZudaire** [comment]
Muchas gracias por las respuestas! :) Esta tarde-noche me leo el post y me pongo a ver lo de la ruta para ver como arreglarlo.
También lo del makefile tiene sentido, ellos lo estaban haciendo en Visual Code, y por eso debe ser.
Dejo el issue abierto hasta la noche.
Saludos!!

**Comment by joseZudaire** [comment]
Muchas gracias por todo! Lo pude resolver colocando el archivo junto al makefile de ejecución, así lo encontraba.
Saludos!!
