### ISSUE TITLE
Problema con la instalacion de las Guest Additions

### ISSUE THREAD

**Issue by FrancoDalessio25** [sisoputnfrba/foro#2304]
Hola, estoy teniendo problema con la instalación de las guest additions.

Hice exactamente todos los pasos que marcaba el video recomendado por la pagina y no tuve ningún tipo de problema, pero una vez que cierro sesión, apago o reinicio la VM no me aparece en Fullscreen. Ya reinstale la VM y todo pero el problema sigue.

Foto de que ya descargue las guest additions y no esta en fullscreen:

![image](https://user-images.githubusercontent.com/63592792/131400812-5c471f9f-9fa9-4023-9d84-b777fa6970e4.png)

Ya no sé que hacer.

**Comment by tferraro** [comment]
👋 Alo Fijate que para poder reportar problemas de este tipo, *tenemos un formato de issue particular*.
Porfa respetá el formato, porque hay mucha información valuable para entender el problema y  que fuiste buscando y probando 🙂
