### ISSUE TITLE
Problemas con la instalacion de guest addition

### ISSUE THREAD

**Issue by FrancoDalessio25** [sisoputnfrba/foro#2305]
- Hola, Seguí al pie de la letra las instrucciones que dieron para realizar la instalación de los guest additions en la VM. No me tiro ningun error ni nada, pero cuando cierro sesión, reinicio o apago la VM no se me pone nunca en Fullscreen, pero me aparece que ya tengo descargado las guest additions. Entonces no entiendo si no tengo ningun problema ni nada al seguir los pasos, no se me pone en fullscreen

### 🔎 Búsqueda en foros

- No encontre nada, aca en git habian 2 consultas de los guest additions pero son cosas que a mi no me pasaron.

### 📦 Especificaciones de la VM
- Versión de VirtualBox: Antes lo tenia en la version 6.1.26 y lo borre para descargar la 6.1.18 (version de un amigo que si le anduvo) Pero a mi en las 2 versiones me pasa lo mismo.
- Memoria RAM asignada: 2048 mb.

En la seccion de Configuracion -> Pantalla tengo puesto en controlador grafico (VMSVGA)

### 🖥️ Especificaciones del host
- Sistema Operativo y versión: Windows 10
- Memoria RAM: 8gb
- Procesador: Intel Golden Pentium

Ya no se que hacer

**Comment by RaniAgus** [comment]
¡Buenas! Podés probar cambiar el controlador gráfico a `VBoxVGA` como se menciona en https://github.com/sisoputnfrba/foro/issues/2015#issuecomment-817364054

Si esto no funciona, para descartar posibilidades: ¿probaste alguna otra feature de las Guest Additions como el portapapeles bidireccional?

Saludos

**Comment by FrancoDalessio25** [comment]
Holaa, muchas gracias por resopnder!! Lo de cambiar de "VMSVGA" lo probe pero directamente se me queda en una pantalla en negro despues de poner la contraseña "utnso". Y las opciones de "Compartir Portapapeles" y "Arrastrar y soltar" las tengo ambas en "Bidireccional", aún asi sigo teniendo el mismo problema que no me aparece la pantalla en fullscreen

**Comment by Zachmoist** [comment]
Buenas! yo tenia el mismo problema y lo arregle haciendo masomenos lo que dice aca:

https://kb.teevee.asia/tips-and-tricks/how-to-fix-error-this-system-is-currently-not-set-up-to-build-kernel-module-ubuntu-virtualbox/

Digo maso menos por que en lugar de hacer apt install virtualbox-guest-additions iso -y hice apt install virtualbox-guest-additions-iso -y que es lo que me  recomendó un log en la consola.

Luego no pude hacer mkdir -p /mnt/cdrom mount VBoxGuestAdditions.iso /mnt/cdrom, peeeero como esta linea es para montar la iso simplemente busque la iso que descargo el comando anterior y la monte a mano, a partir de ahí es es volver a correr el VBoxLinuxblabla.run 

Fíjate si te sirve! un saludo!

**Comment by FrancoDalessio25** [comment]
Hola!! Muchas gracias por la ayuda!! Estoy haciendo lo que dice el video y llegue a la parte de mount VBoxGuestAdditions.iso y tmpoco pude, vos dijiste que lo montaste a mano con la iso q descargo el comando anterior. Yo estoy buscando que iso descargo pero no lo encuentro, vos por casualidad te acordas q iso descargo? porque literalmente me falta hacer eso y dsp sigue con lo de siempre

**Comment by FrancoDalessio25** [comment]
Esto es lo que me descargo, no encuentro el iso.

![image](https://user-images.githubusercontent.com/63592792/131694273-547ed12a-79cd-4ee4-820f-600aad622fd1.png)

**Comment by Zachmoist** [comment]
te fijaste si tenes la carpeta /usr/share/virtualbox? ahi es donde a mi me dejo el iso, literalmente el file se llama VBoxGuestAdditions.iso

**Comment by FrancoDalessio25** [comment]
Ahi lo encontre, pregunta. Cuando hago el mount tengo que montarlo a la carpeta que me dice ? (mnt/cdrom).


O tengo que pasarla a la carpeta donde yo tengo mi VBoxLinuxAdditions.run??

**Comment by Zachmoist** [comment]
Si la carpeta donde tenes el VBoxLinuxAdditions.run se llama algo asi de VBox_GA_6.1.... es que aun tenes montadas las guest additions que vinieron con la imagen de la VM y que no funcionaron.

Tenes que desmontar esa y y hacer el mount de la que descargaste, entonces deberías ver la carpeta de las guest additions que descargaste.

No se si lo tenes que mandar a mnt/cdrom por que yo monte la iso desde la interfaz del file system, muy linda la consola pero ya estaba hinchado con las guest additions.... xd

**Comment by RaniAgus** [comment]
¡Wowow! Paremos el carro por un momento...
@FrancoDalessio25 ¿Estás seguro que tuviste el mismo error que @Zachmoist ? En el video dice que al intentar instalar las Guest Additions debería aparecer el mensaje:
```
This system is currently not set up to build kernel modules.
```
Pero en ningún momento mencionaste si tuviste ese error, de hecho, habías dicho que no te apareción ninguno 🤔 

Siguiendo lo que habías mencionado al principio, puede haber ocurrido que las Guest Additions se hayan instalado bien, pero que solamente no funcione el ajuste del tamaño de la pantalla. 

Es por eso que preguntaba si te funciona el portapapeles bidireccional: para asegurarme de que es un problema de la pantalla y no de la instalación de las Guest Additions. Aclaro que el portapapeles bidireccional no tiene nada que ver con la pantalla, sino que es la feature de poder hacer Ctrl+C fuera de la VM y Ctrl+V dentro de ella, y viceversa.

@Zachmoist ¡Gracias por el aporte! Un detalle a tener en cuenta: Al parecer los comandos que aparecen en el artículo no coinciden con lo que se menciona en el video😞: El `apt install` del video era el correcto, y para ejecutar todos los comandos se necesita primero contar con permisos de root. Para hacerlo, el flaco del video arranca ejecutando `sudo -s`, pero otra opción era agregar el `sudo` delante de cada comando.

**Comment by FrancoDalessio25** [comment]
Sisi, el portapapeles bidireccional me funciona correctamente. Y cuando hice la instalacion no tuve ningun error.

Igual, algo que hice ahora fue ir a "Preferencias -> Ajustes Del Monitor" y ahí cambie la resolución de 800x600 a 1440x900. No es fullscreen pero por lo menos se ve mas grande ajaj

**Comment by RaniAgus** [comment]
Genial, entonces me quedo tranquilo de que las Guest Additions están instaladas y que por el momento podés trabajar en un tamaño de pantalla razonable 👍🏻 

En general, cuando hay problemas con las VMs el foro suele ser útil para tener una respuesta rápida en cualquier momento de la semana, pero para estos casos donde el problema es más complejo y requiere de _ir probando_ muchas veces termina quedando un issue con muchos comentarios y pocas soluciones 😞 

Sin embargo, si querés hacerlo andar no te preocupes, ¿te copa pegarte una vuelta por el sábado de soporte mañana? Creo que sería más cómodo ya que nos podés compartir pantalla y te vamos a poder dar feedback en el momento

**Comment by tferraro** [comment]
Buenas! Como fue eso? Quedo solucionado el tema?
No te olvidesd de cerrar el thread si ya quedo listo :)

**Comment by FrancoDalessio25** [comment]
Hola!! al final nunca pude lo de fullscreen pero como pude ponerlo en 1440x900 con eso me conformo jajajaj

**Comment by iago64** [comment]
No fue el mejor resultado, pero al menos fue algo mas aceptable, cualquier cosa si ves que en algún momento se te vuelve incomodo pasate por un sábado de soporte y lo vemos ao vivo que seguramente sea mas facil :)

Mientras tanto damos por cerrado el issue 😸
