### ISSUE TITLE
El enlace a MateLib es inválido (404)

### ISSUE THREAD

**Issue by lalvarez-utn-frba** [sisoputnfrba/foro#2306]
### 📔 Citas del enunciado/videos
![imagen](https://user-images.githubusercontent.com/89167525/132343191-4c5e284f-e552-461d-b747-d65df3c8b177.png)

El enlace apunta a https://github.com/sisoputnfrba/xmaslib
Mismo el enlace con el ejemplo, también responde 404.

Imagino que les faltó hacer público ese repo. Gracias!

**Comment by tferraro** [comment]
Alo! No no, el nombre está mal, es como dice el link explícito 😂
https://github.com/sisoputnfrba/matelib.git
Hubo un rebranding en el medio y el link quedó como el original.

Buen catch 🎣

**Comment by mecsafonso** [comment]
Buenas!
Al menos a mi todavía no me deja acceder al repositorio, mismo 404

**Comment by tferraro** [comment]
Ufff, tené toda la razón.

Había efectivamente quedado privado. Fijate ahora si podés verlo

**Comment by mecsafonso** [comment]
Ahora si,
Gracias!

**Comment by lalvarez-utn-frba** [comment]
Me pareció raro porque recordaba haberlo probado jaja
Ahora sí, gracias!

**Comment by tferraro** [comment]
Geniall, gracias a ustedes 🚀
