### ISSUE TITLE
SWAMP Duda

### ISSUE THREAD

**Issue by SfaraLucas** [sisoputnfrba/foro#2307]
Hola Buenas, tengo una duda

 ¿Cuándo se usa el otro archivo de mi memoria swap? Realmente no me queda claro esa parte

**Comment by iago64** [comment]
Buenas! Cómo va?

La idea de tener múltiples archivos de SWAP es para que en caso de que uno este lleno puedan utilizar el siguiente archivo y así sucesivamente con todos los archivos de la lista.

Explicación extensa y solo anecdótica:
Esto es de los tiempos en los que se usaban discos para swap en lugar de archivos, entonces como no se tenia pensado guardar mucha info se usaban los discos mas chicos que se tenían en una pc y/o servidor y para facilitarte la vida linux te deja decir donde vas a tener tus "espacios de swap" y setear prioridades para saber a cual vas a llenar primero. 
Hoy por hoy el mismo swap con lo barata que es la ram esta medio que de adorno y muchas veces cuando instalas una distribución de linux te dan la chance de elegir si queres una partición de disco (método bastante old school) para swap o usar un archivo (parecido a como viene en windows o el por default de muchas distros que se mantienen activas hoy en día) que tiene la ventaja de que lo podes acomodar (agrandar o achicar) sin tener que andar metiendo mano en la tabla de particiones del disco donde si te mandas un moco vas a tener un par de horas hasta arreglarlo.

Saludos.-

**Comment by tferraro** [comment]
Un poco esto que comenta Dami 😁

En la teoría muchas veces se habla de forma "abstracta" del espacio de Swap; pero si le pegas un par de leidas al libro de los dinosaurios, hay muchas formas en la que ese espacio aparece, a veces como una única particion en disco..y otras veces como múltiples archivos de swap.

El feedback está buenisimo, porque al ser uno caso no-tan teórico, está buenisimo agregar esta data a modo de aclaración del esquema 💪 
Me lo llevo para sumarlo en la fé de erratas como una aclaración sí queda más claro, te parece @SfaraLucas?

**Comment by SfaraLucas** [comment]
Si, quedo clarisimo muchas gracias

**Comment by iago64** [comment]
Bueno, cerramos el issue, ya que lo tenemos registrado para aclararlo en la v1.1 del enunciado 😸
