### ISSUE TITLE
Debugger en Visual Studio Code

### ISSUE THREAD

**Issue by achoquemamani** [sisoputnfrba/foro#2308]
Tenemos un problema con el uso debugger en el visual studio code, usamos como referencia esta página https://github.com/dariokozicki/utnso-vscode. Seguimos los pasos que se menciona pero cuando se debuggea y llega a la línea "char* ip = config_get_string_value(g_config,"IP_MODULO");' donde se utiliza el método de las commons se produce un segmentation fault, cuando se ejecuta de forma normal no se produce segmentation fault.

Código: 

```
> int main(void)
> {
>     messages = list_create();
>     /*---------------------------------------------------PARTE 2-------------------------------------------------------------*/
>     int conexion;
> 
>     t_log* logger = iniciar_logger("/home/utnso/tp0/client/client.log", "Cliente");
>     // Usando el logger creado previamente
>     log_info(logger, "Hola! Soy un log");
>     
>     // Usando el config creado previamente
>     // Lee las variables de IP, Puerto y Valor
>     t_config *g_config = leer_config_file("./cfg/client.config");
>     char* ip = config_get_string_value(g_config,"IP_MODULO");
>     char* puerto = config_get_string_value(g_config,"PUERTO_MODULO");
> 
> ...
> }
```

**Comment by tferraro** [comment]
Buenas!

No se mucho debuggear sobre VSCode, la verdad 😅 Está incluido en la VM como un chiche extra por si lo quieren usar, pero veamos que tul.

Por lo que contás que falla en el `config_get_string_value`. La única dirección que veo que le estás pasando es `g_config`, que valor tiene?

Me suena que en realidad el `leer_config_file` te está devolviendo un puntero inválido (NULL o algo simil) y cuando quiere acceder, falla.

**Comment by achoquemamani** [comment]
Gracias, pudimos resolver el problema, para debuggear el visual studio code usamos el path absoluto del config, por alguna razón con el path relativo no funciona.

**Comment by RaniAgus** [comment]
¡Buenas! Es probable que esté mal el CWD (Current Working Directory) que usa VSCode para debugear (para más info sobre qué es el cwd y cómo influye sobre los paths relativos, podés ver [este artículo](https://mgarciaisaia.github.io/tutorial-c/blog/2015/04/23/rutas-argentinas/)).

Quizás viendo el `launch.json` podamos encontrar qué es lo que puede estar ocurriendo ([recordá que matelib requiere de paths relativos para su funcionamiento](https://github.com/sisoputnfrba/matelib#uso-y-funcionamiento-esperado-de-la-lib-implementada)).

Saludos
