### ISSUE TITLE
Dudas sobre modulo SWamP

### ISSUE THREAD

**Issue by Nicolas-Russo** [sisoputnfrba/foro#2309]
Buenas, hay algo que no termine de entender del modulo.

1) El tamaño de las particiones es para todas igual? Si es asi ese valor se puede obtener por archivo config?

2) Las paginas se van guardando en una particion y cuando se llena se empieza a llenar otra?

3) Aunque la memoria tenga espacio suficiente, se la tiene que mandar a SWamP igual para que la guarde o no?

Gracias!

**Comment by ncoen97** [comment]
Buenas.

1. Si, son todas iguales y el tamaño se obtiene mediante el campo TAMANIO_SWAP del archivo config.
2. Esta parte nos faltó definirla mejor en el documento, así que la dejamos pendiente pero queda anotado para especificarlo mejor para la próxima versión del TP.
3. No, la memoria swap se va a ir llenando cuando no haya más espacio en memoria principal

Saludos!

**Comment by Nicolas-Russo** [comment]
Okey Gracias!

**Comment by Nicolas-Russo** [comment]
Hola, reabro el issue porque tengo una duda con el tema del uso de las particiones.

Antes me dijeron que no estaba definido, en este issue #2307 veo que responideron esto: 

`La idea de tener múltiples archivos de SWAP es para que en caso de que uno este lleno puedan utilizar el siguiente archivo y así sucesivamente con todos los archivos de la lista.`

y el otro dia en soporte me dijeron que la idea es que va a haber un archivo SWAP por cada proceso que exista por eso que en cada archivo se van a guardar solo paginas de un solo proceso.

Nose a quien creerle jaja. Lo pueden aclarar porfavor?

Gracias.

**Comment by iago64** [comment]
Buenas! Cómo va?

La posta es lo del enunciado, en resumen:

Podes tener 2 procesos en el mismo archivo de swap, pero **no** podes tener 1 proceso en 2 archivos de swap diferentes. 

Me juego a que lo segundo es lo que te quisieron comentar en le pifiaron en las palabras (a todos nos pasa)

Saludos.-
