### ISSUE TITLE
Consulta error enunciando memwrite

### ISSUE THREAD

**Issue by danimontesano** [sisoputnfrba/foro#2310]
Hola buenas tardes. Estaba leyendo el enunciado en la sección de _Asignación de memoria_ y vi que en la parte de memwrite detalla el valor que se debe retornar ante la reserva de memoria. Sin embargo ya habian aclarado esto en la parte memalloc.

### 📔 Citas del enunciado
![image](https://user-images.githubusercontent.com/62483675/132762937-64a15ca1-3867-4ca8-836d-6a5fd5f1deb0.png)

### 💭 Soluciones posibles
Creo que debe ser un error y que en realidad quisieron decir _"el valor a retornar ante una escritura en memoria es ..."_.

Muchas gracias.

**Comment by ncoen97** [comment]
Buenas.
La aclaración del enunciado es correcta (aunque si está repetida). Ante una escritura en memoria se podría retornar si fue una escritura válida o invalida, igual vamos a ver si hacemos alguna aclaración más con respecto a estos casos.
Saludos!

**Comment by danimontesano** [comment]
claro, lo mencionaba por la diferencia entre reservar y escribir la memoria. Ya que en el caso de reservar lo que devolvería sería siempre el primer espacio de memoria mientras que, al escribir ahí si seria el primer espacio de memoria disponible en el espacio que ya se había reservado con anterioridad.

**Comment by iago64** [comment]
@danimontesano Ese párrafo esta por fuera del memwrite(), a lo que apunta es a que teniendo la estructura de la página 15:
![image](https://user-images.githubusercontent.com/1622109/133014819-b6f54ec1-030d-4a13-8a20-83a81e84ad0a.png)

Es que tienen que devolver lo que apunta la flecha roja y no lo que apunta la flecha negra.

Saludos.-

**Comment by danimontesano** [comment]
claro pero por lo que tengo entendido ese puntero se va a mover únicamente con el memwrite, ya que si hago un memalloc siempre va a estar al inicio ya que justamente acabo de reservar, la memoria. ¿O sigo comprendiendo algo mal?

**Comment by tferraro** [comment]
Maso, es un poco lo que comenta Dami, el memwrite no juega en este partido, vino solo a la tribuna circunstancialmente 😛 . El comment va para el reservar memoria.

Fijate las interfaces reales de las mismas funciones. Cuando vos haces `malloc(un_tamaño)`, malloc te devuelve una posición de memoria. Sin embargo, reserva un poco más, porque en la práctica hace algo similar a lo que dice el TP. Reserva más memoria pero te da apartir de donde vos podes referenciar como datos posta.

Memwrite, por otro lado, como su equivalente memcpy es un poco más compleja; es más sencillo devolver un -1 o 0 ante success o no (en la posta...te explota con un SegFault 😆 y podría generar problemas al detectar si es la implementación o un caso real, y por eso son más simplistas).

**Comment by danimontesano** [comment]
Genial, muchas gracias!
Cierro el issue
