### ISSUE TITLE
no me funciona list_iterate

### ISSUE THREAD

**Issue by heinHertz** [sisoputnfrba/foro#2311]
Hola, revisando el tp0 y me quiero sacar una duda. no me funciona del tp0 el list iterate que viene con el tp0 en la parte del server, no se porque quizá puedan darme una mano, estoy codeando en vs code :
en el server.c del tp0:

case PAQUETE:
	lista = recibir_paquete(cliente_fd);
	log_info(logger, "Me llegaron los siguientes valores:\n");

	list_iterate(lista, (void*) iterator);    //---->No me funciona

acá la función iterator:
```c
void iterator(t_log* logger, char* value) {
	printf("Valor :  %s \n", value);
	log_info(logger,"%s\n", value);
}
```
con que no me funciona quiero decir que los valores no llegan ( se muestran como null al usar la funcion iterator).
aclaro que debbugee hasta log_info y tambien list_iterate para ver si llegaba bien la lista que viene del cliente, en lista=recibir_paquete ,  esa es una lista de strings y funciona bien , es decir la lista creo que no es el problema, quizás el problema es otro, cual creen que podría ser ?
gracias.

**Comment by lrocampo** [comment]
Tuve el mismo el problema. Básicamente si ves la implementación de list_iterate, recibe como segundo parametro una función de un único parámetro. Sin embargo, iterator recibe dos argumentos. Creo que viene por ahí el problema.

void list_iterate(t_list* self, void(*closure)(void*)) {
	t_link_element *element = self->head;
	t_link_element *aux = NULL;
	while (element != NULL) {
		aux = element->next;
		closure(element->data); // acá se usaría el iterator, pero faltaría el parámetro del logger
		element = aux;
	}
}

**Comment by RaniAgus** [comment]
¡Buenas!
Como bien dicen, está mal la función `iterator`, debería recibir un solo parámetro y no dos:
```c
// logger está definido como variable global, por lo que en este caso no hace falta pasarlo

void iterator(char* value) {
	printf("Valor: %s\n", value);
	log_info(logger,"%s\n", value);
}
```
También otro workaround válido puede ser cambiar un toque el código para pasarle una [nested function](https://www.youtube.com/watch?v=1kYyxZXGjp0) a `list_iterate`:
```c
void iterar_lista(t_list* lista, t_log* logger) {
    void iterator(char* value) {
	printf("Valor: %s\n", value);
	log_info(logger,"%s\n", value);
    }
    list_iterate(lista, (void*) iterator);
}
```
Mil disculpas, lo vamos a corregir en la próxima revisión del enunciado del tp0.

Saludos

**Comment by heinHertz** [comment]
Gracias  @lrocampo   y @RaniAgus   !   Me funcionó con un parametro y anda joya.
Un comentario especial para @RaniAgus, asumo que ayudante(?):
Como estoy codeando en VS Code, que la versión que uso actualmente me la provee la catedra, las listas de funciones  anidadas me muestran un mensajito que yo anteriormente consulte en issues y segun entiendo es "inofensivo":

![image](https://user-images.githubusercontent.com/37560557/132781500-a6ec21a0-326b-4ea6-840a-799c098f30d5.png)

el tema es que por una cuestión de  comodidad para el tp de operativos no meto el código para evitar este mensaje, si que nada
y gracias!

**Comment by RaniAgus** [comment]
Exactamente, como comentaba en https://github.com/sisoputnfrba/foro/issues/2076#issuecomment-840840884 ese error es solamente del editor. Los warnings y errores que realmente deben importarte son los que se muestran al compilar con `gcc` (que, de hecho, en VSCode no se resaltan en la pestaña de "problemas", así que te aconsejo ignorar esa pestaña). 

El IDE o editor de texto que uses solamente va a intentar detectar errores de antemano, pero no influye en la compilación. O sea, no va a evitar que compiles si te aparecen errores en la pestaña de "problemas", sino que si eventualmente llegás a tener alguno, te va a aparecer de nuevo al intentar compilar con `gcc`.

Un ejemplo claro es [CSpec](https://github.com/mumuki/cspec) que, como utiliza macros con nested functions, el VSCode no las reconoce pero al compilar funciona todo perfecto :P

**Comment by heinHertz** [comment]
gracias!
