### ISSUE TITLE
Duda sobre dispositivos IO y su llamado con mateLib (mate_call_io)

### ISSUE THREAD

**Issue by MarcoPiatti** [sisoputnfrba/foro#2312]
Buenas! leyendo la descripción de los dispositivos entrada-salida en el apartado de kernel del TP, se encuentra lo siguiente:
>Pedir I/O: Dentro del sistema existen dispositivos de entrada-salida, cada uno con su propia duración. Un proceso puede pedir realizar una entrada salida a un determinado dispositivo con `mate_call_io`, generando que se bloquee por el tiempo que dure esa ráfaga I/O. Los dispositivos no pueden ser usados por dos procesos al mismo tiempo, los procesos bloqueados pueden estar a la espera de que se libere un dispositivo si este está en uso.

De esto entiendo que los dispositivos I/O van a tener una funcionalidad de simplemente bloquear procesos por un tiempo determinado (y su logica para ir encolandolos). pero revisando la firma de la funcion [`mate_call_io`](https://github.com/sisoputnfrba/matelib/blob/4079ccf8c3458ffd7d526c59bd01ad585e3600c8/matelib.h#L36) en el apartado de mateLib:
```c
int mate_call_io(mate_instance *lib_ref, mate_io_resource io, void *msg);
```
veo que además de una referencia al nombre del dispositivo I/O se desea acceder, hay un parametro extra `void *msg`, que imagino supondría un mensaje a enviar al dispositivo entrada-salida, pero no logro entender en donde entraría su uso, ya que no se menciona en ninguna parte algo al respecto de que el dispositivo I/O reciba o procese un mensaje (el `void *msg`), solamente que bloquea al proceso que lo llamó.

Además, viendo [el ejemplo de implementación de la funcion](https://github.com/sisoputnfrba/matelib/blob/4079ccf8c3458ffd7d526c59bd01ad585e3600c8/examples/lib_implementation/matelib.c#L68-L78):
```c
int mate_call_io(mate_instance *lib_ref, mate_io_resource io, void *msg)
{
  printf("Doing IO %s...\n", io);
  usleep(10 * 1000);
  if (!strncmp(io, "PRINTER", 7))
  {
    printf("Printing content: %s\n", (char *)msg);
  }
  printf("Done with IO %s\n", io);
  return 0;
}
```
Entiendo que emula la recepción de ese mensaje por parte de una impresora ficticia, y que esta "imprime" al mensaje, pero devuelta, en lo que la consigna del tp especifica acerca de estos dispositivos no se menciona nada sobre recibir mensajes.

No sé si es algo que quizás se da por sentado y me estoy confundiendo innecesariamente, o es que hay algún tipo de mismatch en la consigna en sí. 
En caso de que sea lo primero, hay algún motivo por el cual el tipo de dato del mensaje es `void *`, en lugar de simplemente un `char*`?

Muchas gracias desde ya :slightly_smiling_face:

**Comment by tferraro** [comment]
👋 Alo!

Voy a ir por partes 🙂 , pero primero antes que nada: en la práctica no tiene utilidad ese parámetro `msg`, no te calentés 😉 .

Quedó de una posible funcionalidad que se recortó del TP por diseño (sino quedaba muy grande  😛 ).

Ahora, no la eliminamos, porque en realidad la interfaz de los dispositivos de IO es así y sacarla quedaba medio contradictorio.
**Porqué?** Porque en la posta, las I/O tienen un espacio de memoria donde van a interactuar con los procesos; normalmente mediante un par de features de hardware que se llaman DMA (ya lo van a ver en la teoría).

Y limitar la interfaz de la lib por la implementación del "backend" era medio una picardía....y quedó así 😅

Finalmente, porqué `void*`? Es una buena pregunta! Como dije antes, tienen un pedacito de memoria que usan para interactuar con los procesos, pero es eso, memoria.
La dinámica de un `char*` indica explicitamente que es un conjunto de bytes; mientras que los `void*` es la forma en C para decir "memoria generica", porque no necesariamente va a ser un literal (como era en el ejemplo, por simplicidad).

---------------------

Más allá de todo, lo dejo anotado para dejar alguna aclaración en el enunciado/repo de la lib para que nadie más se persiga con ese parámetro 💪

**Comment by MarcoPiatti** [comment]
Gracias! no sabía por donde mecharlo. Cierro el Issue

**Comment by iago64** [comment]
@MarcoPiatti Siempre que todo quede claro, si sos el creador del issue cerralo, igual de momento no hay drama, lo cerramos nosotros 😄
