### ISSUE TITLE
Dudas varias

### ISSUE THREAD

**Issue by jlsuh** [sisoputnfrba/foro#2313]
¡Buenas!

Kernel:
> "Este módulo será el encargado de gestionar y planificar todas las solicitudes que los procesos harán mediante la lib para solicitar recursos de nuestro sistema".
> "Todos los procesos al conectarse se iniciarán en NEW, y una vez que todas sus estructuras estén creadas exitosamente se pasarán a READY..."

1) En caso de que planifiquemos procesos carpinchos, ¿solamente estaríamos planificando sus peticiones?
Se nos ocurre que los carpinchos son solamente "consolas activas" que ejecutan el main.c -como en el ejemplo dado en lib_usage- y según lo que vayan haciendo en dicho código, nosotros solamente debamos planificar TADs con la motivación de la forma t_peticion, que dependiendo el tipo de petición que sean cumplirán distintos propósitos.

Conexiones:
> "La interfaz esperada de la Biblioteca ante el Kernel debe ser polimórfica contra la memoria; permitiendo que en ausencia del mismo, pueda configurarse la IP y Puerto de la misma; anulando las funcionalidades de planificación, pero permitiendo las de memoria"
2) ¿El kernel puede posteriormente conectarse a la memoria, dado un caso en donde inicialmente el kernel esté apagado?
Esta duda surgió debido a la necesidad de definir en qué módulo almacenar un ID al proceso carpincho. Se nos ocurrió que la memoria sería el lugar ideal para manejar los IDs debido a que si la conexión polimórfica falla contra el Kernel en primer lugar, pasaría a conectarse con la memoria; en su defecto, en caso de que el Kernel esté a la escucha, le pediría a la memoria el siguiente ID asignarle al carpincho entrante.

3) Los ejemplos brindados en los archivos de configuración son en todas las ocasiones mediante el uso del puerto 5001. No obstante, en la guía de sockets menciona que no es posible que más de 1 proceso esté a la escucha de un mismo puerto. Queríamos consultar si se podría agregar un puerto más, en el caso del _carpincho_, para distinguir el puerto del Kernel del puerto de la Memoria. Planteamos el siguiente caso de uso:
![image](https://user-images.githubusercontent.com/38252227/132962394-8d50b9b9-8bef-43b4-bbb9-3e3acb3e78be.png)

Semáforos:

4) ¿Los semáforos que utilizan los _carpinchos_ son para qué fines? No entendemos si éstos semáforos deben ser con fines de planificación e interferir en los planificadores.

¿Los semáforos de la matelib son administrados por el Kernel, por lo tanto el carpincho estaría abstraído en la lógica del semáforo? En caso de que así sea con la presente biblioteca, ¿estaríamos haciendo una simulación de un semáforo mediante el Kernel? Una solución que pensamos es hacer un while(1) con el sem_wait y un break con el sem_post. Esto pierde lógica, puesto que ¿por qué el _carpincho_ no controlaría a sus propios semáforos?

Saludos y gracias de antemano

**Comment by gastoncastineira** [comment]
Buenas!

> En caso de que planifiquemos procesos carpinchos, ¿solamente estaríamos planificando sus peticiones?

No entendí muy bien esto. Podés re frasearlo o darme un ejemplo de qué fue lo que entendiste y te disparó la duda?

> ¿El kernel puede posteriormente conectarse a la memoria, dado un caso en donde inicialmente el kernel esté apagado?

Nop. La prueba la vamos a hacer cambiando los archivos de configuración y bajando y levantando todo de nuevo. Lo que queremos validar acá es que el comportamiento de la memoria sea el mismo con o sin kernel de por medio

> Los ejemplos brindados en los archivos de configuración son en todas las ocasiones mediante el uso del puerto 5001. No obstante, en la guía de sockets menciona que no es posible que más de 1 proceso esté a la escucha de un mismo puerto. Queríamos consultar si se podría agregar un puerto más, en el caso del carpincho, para distinguir el puerto del Kernel del puerto de la Memoria. Planteamos el siguiente caso de uso:

Los ejemplos de los archivos de config no son más que eso, ejemplos. Están ahí para que vean qué valores pueden tomar, no porque sean los valores que esperamos que tengan el día de la entrega.
Más allá de eso, ojo. El TP está pensado para que el día de la entrega lo corran en distintas VMs, y la guía de sockets dice que lo que no se puede es escuchar en un puerto tomado. Si los módulos corren en 3 computadoras distintas, el puerto tomado es el de una sola.
Otro tema; por qué querés agregar otro puerto a la config del carpincho? El carpincho siempre se va a conectar a un solo módulo, sea memoria o kernel, pero para él es transparente porque los mensajes que se envíen tienen que ser los mismos para ambos módulos

> ¿Los semáforos que utilizan los carpinchos son para qué fines? No entendemos si éstos semáforos deben ser con fines de planificación e interferir en los planificadores.

Perdón si hoy estoy muy lento pero no termino de entender por dónde vienen las dudas con los semáforos. Página 12 del enunciado, en la sección de bloqueos dice:
> Si un proceso hace, mediante uso de la lib, un mate_sem_wait a un semáforo con valor menor a 1, este deberá pasar a bloqueado hasta que el semáforo se libere con mate_sem_post. Los procesos en espera se irán pasando a READY en el orden en el que fueron bloqueados uno a la vez. Es decir, por cada post se desbloqueará un único proceso en BLOCKED, respetando el orden de la cola de espera.

Creo que ahí queda claro que hay transición entre estados y por lo tanto tiene que intervenir el kernel. Hay algo ahí que esté despertando dudas?
