### ISSUE TITLE
Problemas de autentificación Git/Token 

### ISSUE THREAD

**Issue by kamipalomino** [sisoputnfrba/foro#2314]
Buenas tardes,  estoy intentando clonar el repo desde la vm Server y al ingresar los datos me sale un erro sobre la generación de un token 

![image](https://user-images.githubusercontent.com/28968341/132965893-832ce0d8-b322-4f87-815c-9d00573eb162.png)

Generé el token desde github pero no sé como hacer que funcione 
![image](https://user-images.githubusercontent.com/28968341/132965920-bf314131-25fc-4247-b952-bd6a4f63bf1f.png)

Y si sigo los pasos que dice la documentación de git  me sale el siguiente erro:
![Untitled](https://user-images.githubusercontent.com/39303639/132966456-a7be6142-83e2-47f0-8249-65774495a7d4.png)

Alguna idea de como lo puedo solucionar?

**Comment by RaniAgus** [comment]
¡Buenas! Primero que nada te pido que si no revocaste ese token vayas corriendo ya mismo a hacerlo (también censuré la imagen). Recordá que este foro es público y cualquiera puede hacer desastres con tu cuenta de GitHub con eso, es como publicar una contraseña 😅 

Dicho esto, para hacer funcionar el token simplemente alcanza con clonarse el repo como siempre:
```
$ git clone https://www.github.com/sisoputnfrba/tp-2021-1c-[migrupo]
```
Y luego, cuando te pida la password, ingresar el token en su lugar:
```
Password for 'https://[micuenta]@github.com':
```

De todas formas, para empezar a trabajar te aconsejo usar la Lubuntu, ya que tiene interfaz gráfica por lo que es mucho más amigable para codear.

Saludos

**Comment by iago64** [comment]
@kamipalomino te sirvió la respuesta de Agus? Necesitas una mano con algo mas?

Saludos.-

**Comment by RaniAgus** [comment]
@kamipalomino cierro por inactividad, ante cualquier consulta sobre el tema no dudes en reabrir el issue 👍🏻
