### ISSUE TITLE
Serializacion - Paquete

### ISSUE THREAD

**Issue by rjmbelen** [sisoputnfrba/foro#2315]
Buenas tardes, tengo la siguiente consulta con respecto a la parte 3 del TP0. En el cliente.c invocamos a paquete(conexion).

Armamos la función Paquete, fuimos agregando lo que se lee por consola con la funcion agregar_paquete. (al enviar el valor leido de la consola, utilizamos el (strlen(leido) +1). Finalmente enviamos el paquete ya serializado con la funcion enviar_paquete. El problema esta en consola cuando queremos ver lo que el servidor recibe, no nos muestra nada, es decir, no llega el Paquete.

**[INFO] 16:03:36:756 Servidor/(26225:26225): Me llegaron los siguientes valores:**

Alguna idea de que podría ser? o como podemos resolver esto? 

muchas gracias!

**Comment by gastoncastineira** [comment]
Puede ser lo mismo de #2311?

**Comment by rjmbelen** [comment]
Buenas, estuvimos revisando ese otro issue y seguimos en la misma.
![image](https://user-images.githubusercontent.com/38320379/133008044-52f8aeb3-249e-46a4-aa39-bae099bf0b17.png)

![image](https://user-images.githubusercontent.com/38320379/133008058-8bd38fb2-6bde-46df-9fa8-18b5e96ba973.png)

![image](https://user-images.githubusercontent.com/38320379/133008116-2bbaf7d6-dfcc-47da-891d-3281171c2797.png)

Hay algo que no estamos viendo??
Duda adicional, por que la funcion recibir_paquete retorna un NULL además de los valores??

**Comment by gastoncastineira** [comment]
Buenas de nuevo!

Tratemos de evitar pantallazos de código porque:
1. Si lo quiero probar, no lo puedo copiar
2. Si un compañero tiene un problema similar y quiere buscar por el nombre de alguna función, el buscados de github no lo va a encontrar

Te hago dos preguntas:
1. Quien esta llamando a `iterar_lista`
2. Por qué estás definiendo dos veces la función `iterator`, una afuera de `iterar_lista` con código para ejecutar, y otra adentro pero sin código para ejecutar?

**Comment by tferraro** [comment]
Sumo mis 🪙 🪙  a este issue.

Fijate que los cambios en el código base del TP podrían ser mucho más simples y capas por eso no te está andando (un poco lo que comentaba Gasti en el punto 2):

`logger`, es una variable global, podes llamarla directamente sin pasarla por parámetro. Por lo que solo tendrias que modificar el `iterator` para que reciba solo un único argumento `char*`.

> Also, creo que ese `return NULL;` quedó de más, no tendría mucha utilidad con un return de otro dato de forma anterior 🙂

**Comment by kamipalomino** [comment]
Buenas, estoy en el grupo con Belén y respondiendo a lo que dice @tferraro primero lo hicimos de esa manera y tampoco funcionaba.
 Cómo en el issue anterior uno de los chicos mostró que así solucionó el problema lo intentamos de ésta manera.
Igualmente después de hacer otras pruebas puede ser que o no se está enviando el paquete o no se está recibiendo

**Comment by gastoncastineira** [comment]
Buenas!

Las serializaciones del TP0 están resueltas y probadas, así que por ese lado seguro que no viene el problema :/

Les hago una consulta. El paso anterior al envío del paquete en el que tienen que enviar un mensaje que levantan del config, ese les está llegando bien? Porque sino, el problema viene por cómo están creando el servidor.
Otro detalle que se me ocurre, este cuatrimestre cambiamos el TP0 y hay que tocar cosas para poder recibir conexiones de clientes en el servidor. Si capaz tienen una versión anterior del TP0 descargada es posible que no les funcione.
Una última cosa para revisar, fíjense si están pasando bien la IP (localhost o 127.0.0,1) y puerto del servidor en el cliente. Capaz están levantando el servidor en otro puerto por equivocación y el cliente no se pueda conectar por eso, porque el el puerto que le dicen no hay nada escuchando

**Comment by kamipalomino** [comment]
Eso funciona todo perfecto, el primer mensaje se recibe bien.
El problema es con el envio del paquete

**Comment by kamipalomino** [comment]
```c
#include "server.h"

int main(void) {
	logger = log_create("log.log", "Servidor", 1, LOG_LEVEL_DEBUG);

	int server_fd = iniciar_servidor();
	log_info(logger, "Servidor listo para recibir al cliente");
	int cliente_fd = esperar_cliente(server_fd);
	int x;

	t_list* lista = list_create();
	while (1) {
		int cod_op = recibir_operacion(cliente_fd);
		switch (cod_op) {
		case MENSAJE:
			recibir_mensaje(cliente_fd);
			break;
		case PAQUETE:
			lista = recibir_paquete(cliente_fd);
			x = list_size(lista);
			log_info(logger, "Me llegaron los siguientes valores:\n");
			log_info(logger, "%d\n", x);
			iterar_lista(lista, (void*) iterator);
//			x = list_size(lista);
//			log_info(logger, "%d\n", x);
			break;
		case -1:
			log_error(logger, "el cliente se desconecto. Terminando servidor");
			return EXIT_FAILURE;
		default:
			log_warning(logger,
					"Operacion desconocida. No quieras meter la pata");
			break;
		}
	}
	return EXIT_SUCCESS;
}
```

Pusimos este log_info(logger, "%d\n", x) para ver el size de la lista y nos da 0

**Comment by gastoncastineira** [comment]
Podés subir el TP0 a un repo así lo revisamos? Siento que estamos medio probando cosas por tanteo y no quiero hacerlos esperar 20 respuestas a un issue

**Comment by kamipalomino** [comment]
Si si , lo tenemos en un branch TP0 del repo [tp-2021-2c-Increible-pero-Compila](https://github.com/sisoputnfrba/tp-2021-2c-Increible-pero-Compila)

**Comment by GonzaloMartinezSa** [comment]
Buenas, a mí y a mi grupo nos pasa lo mismo. Dejando todo como vino y cambiando solo lo que pide, llegamos a que funcione todo excepto lo de enviar las lineas por consola. La función paquete la hicimos básicamente igual a la del otro grupo. Así que me sumo a ver si alguien lo resuelve.

**Comment by RaniAgus** [comment]
︎¡Buenas @kamipalomino! Ahí probé lo que está en https://github.com/sisoputnfrba/tp-2021-2c-Increible-pero-Compila/tree/TP0 y los paquetes se enviaron bien 🤔 

### Client
```
[INFO] 13:53:56:329 TP0/(5126:5126): Hola! Soy un log
[INFO] 13:53:56:331 TP0/(5126:5126): Valor de coniguración: Hola, soy un valor      
>hola
[INFO] 13:54:01:886 TP0/(5126:5126): hola
>mundo
[INFO] 13:54:03:695 TP0/(5126:5126): mundo
>
>hello
valor hello
>world
valor world
>
free(): double free detected in tcache 2
Aborted
```

### Server
```
[INFO] 13:53:53:368 Servidor/(5125:5125): Servidor listo para recibir al cliente
[INFO] 13:54:04:269 Servidor/(5125:5125): Se conecto un cliente!
[INFO] 13:54:04:269 Servidor/(5125:5125): Me llego el mensaje Hola, soy un valor
[INFO] 13:54:09:444 Servidor/(5125:5125): Me llegaron los siguientes valores:

[INFO] 13:54:09:444 Servidor/(5125:5125): 2

valor: hello
[INFO] 13:54:09:444 Servidor/(5125:5125): hello

valor: world
[INFO] 13:54:09:444 Servidor/(5125:5125): world

[INFO] 13:54:09:444 Servidor/(5125:5125): 2

[ERROR] 13:54:09:444 Servidor/(5125:5125): el cliente se desconecto. Terminando servidor

```

Igual tengo otras observaciones:
1- Guarda con los parámetros que le pasan a `log_create`, les aconsejo revisar el [header de las commons](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/log.h#L40-L46).
2- En Client les aparece un double free al final porque `config_get_string_value` devuelve directamente el string que está en el config (no devuelve una copia), por lo que al hacer primero `free` y luego `config_destroy` estarían liberando los mismos strings 2 veces.

Saludos

**Comment by RaniAgus** [comment]
Buenas, @GonzaloMartinezSa ¿El repo que están usando ustedes es este, no? https://github.com/nfernandezsanz/TP0-SO-ProbasteReiniciando

Si es así, mil disculpas, la función `iterator` debía recibir un parámetro y no dos (ya que `logger` es global) como se comenta acá: https://github.com/sisoputnfrba/foro/issues/2311#issuecomment-916520429

Saludos

**Comment by gastoncastineira** [comment]
Otra cosa que notamos con agus @kamipalomino @rjmbelen es que tienen el TP0 desactualizado. El makefile (el archivo que ejecuta eclipse para compilar el proyecto) que tienen es el del cuatrimestre pasado y en las carpetas de cliente y server solo subieron los archivos fuente. https://github.com/sisoputnfrba/tp-2021-2c-Increible-pero-Compila/blob/TP0/makefile
Ese makefile compila solo el cliente, así que se me ocurre que capaz al correr el server están ejecutando un binario viejo que no tiene ninguno de los cambios que hicieron con el tema del iterator y por eso no les muestra nada.
Lo que les recomiendo probar es actualizar el TP0 para tener dos proyectos separados en eclipse, cliente y servidor, cada uno con su makefile, reemplazar solo los archivos fuente para no perder el código que hicieron y probar compilando y corriéndolo así. Avísennos si por ese lado les funciona y sino lo seguimos revisando

**Comment by kamipalomino** [comment]
Hola lo probamos también en una server nueva  sin utilizar el makefile compilando manualmente. Es más desde eclipse no lo pudimos hacer funcionar asi que también se compiló desde la terminal. Compilar compilan, se crean los archivos desde cero pero sigue ese error

**Comment by kamipalomino** [comment]
Gracias, ya Pudimos hacer que funcionara.

**Comment by RaniAgus** [comment]
¡Buenísimo! Recuerden que también pueden cerrar el issue ustedes una vez que la duda haya sido resuelta 😄
