### ISSUE TITLE
Duda Swap/Fragmentacion externa:

### ISSUE THREAD

**Issue by gastonharari** [sisoputnfrba/foro#2316]
Hola, como estan?

Leyendo y analizando el enunciado, no nos quedo claro que debe ocurrir en el siguiente caso:

Guardo pagina 1 del proceso 1 en archivo A.
Se llena el archivo A (Con paginas de otros procesos)

El archivo B esta vacio.
Se pide guardar una pagina mas del proceso 1.
Que debe ocurrir en este caso?

### 📔 Citas del enunciado/videos

Indistintamente del caso, ante la llegada a swap de nuevos procesos, el módulo siempre debe guardar las páginas de ese proceso en un único archivo de swap. Esto quiere decir que no puede haber dos páginas de A, una en el archivo 1 y otra en el archivo 2, ambas páginas deben estar en un único archivo.

### 💭 Soluciones posibles

Que se pase la pagina 1 del proceso 1 al archivo B y que se guarde la pagina 2 en el archivo B.

**Comment by ncoen97** [comment]
Buenas.
Siguiendo la linea de lo que comentaron los chicos en #2307, ese caso nos queda por aclarar mejor en una próxima versión del enunciado.
Saludos!

**Comment by gastonharari** [comment]
Perfecto! Gracias
