### ISSUE TITLE
Problema al realizar un commit 

### ISSUE THREAD

**Issue by gabycosta04** [sisoputnfrba/foro#2317]
Hola buenas que tal?

Queria consultar porque estoy teniendo un problema que a la hora de commitear algo en la repo desde la terminal de Linux, no me toma bien el usuario. Se realizan los commits pero en la repo no me figura como que contribui en el proyecto y me aparece como que no tengo foto en los commits...
![image](https://user-images.githubusercontent.com/62992579/133122993-db5c321f-69ef-4c49-857b-33ba991871fd.png)

Investigue pero no se muy bien como solucionar este problema...

**Comment by RaniAgus** [comment]
¡Buenas! Tenés que configurar tu nombre y mail de git antes de commitear:
```
git config --global user.email "tumail@gmail.com"
git config --global user.name "Tu Nombre"
```

Saludos

**Comment by gabycosta04** [comment]
Gracias Agus, ahora si que no tengo problemas.
Te hago otra consulta... ahora para commitear siempre te pide un token y no una contraseña como antes, tenes idea como puedo hacer para que no tenga que poner el token a cada rato para realizar un push y que quede como guardado? 

Desde ya muchas gracias y saludos

**Comment by RaniAgus** [comment]
¡Buenísimo! Para que te almacene el token y no te lo vuelva a pedir podés hacer lo siguiente:
```
git config --global credential.helper store
```
Luego, la primera vez que hagas `git pull` o `git push` te va a pedir el token de vuelta, pero una vez que lo ingreses ya va a quedar almacenado y no te lo va a volver a pedir 👍🏻 

Saludos

**Comment by gabycosta04** [comment]
Dale perfecto Agus, ahi me funciono.

Saludos y gracias por todo!
