### ISSUE TITLE
Duda Memoria

### ISSUE THREAD

**Issue by SfaraLucas** [sisoputnfrba/foro#2318]
Hola, en el archivo de configuracion de memoria no hay un campo tal como TAMANIO_PAGINA.  ¿Asumo que es 32 por el dibujito o asumo tamaño variable y agrego el campo en el archivo config?

**Comment by ncoen97** [comment]
Buenas! Efectivamente nos comimos ese parámetro de la config. Lo dejo anotado para agregar nomas, gracias por el aviso.

**Comment by SfaraLucas** [comment]
Agrego una duda mas.

¿Por que en la config del modulo de memoria tengo campos como MARCOS_MAXIMOS y TIPO_ASIGNACION?

¿No es la swap la que se encarga de eso?

En el caso de que no ¿Hay marcos maximos en memoria y en swap tambien?

**Comment by SfaraLucas** [comment]
Y en el caso de que la respuesta sea sí. En memoria tambien rige la asignacion contigua o solo con limitar los marcos maximos alcanza?

**Comment by iago64** [comment]
Buenas! Cómo va?

TIPO_ASIGNACION: refiere a la forma en la cual van a asignar los frames de memoria a los procesos, podes asignar siempre una cantidad fija o la misma puede ir variando y ser dinámica. En caso de la asignación fija, siempre vas a reemplazar una pagina de tu mismo proceso, mientras que en asignación dinámica un proceso le puede robar frames a otro (Esto fue una explicación SUPER resumida, ya lo van a ver bien en la teoría)

MARCOS_MAXIMOS: es un parámetro que va a limitar la cantidad máxima de frames que puede tener un proceso, es decir: si es asignación fija, va a tener esa cantidad y ya, pero en caso de asignación dinámica te va a decir hasta cuantos podes tener (eventualmente puede que la cantidad de marcos máximos sea literalmente toda la memoria 😉)

Swap se encarga de otras cosas diferentes, pero tienen también el limite de memoria que puede tener el proceso para el caso de asignación contigua (esto quiere decir que si tenes esquema de asignación contigua en swap, como mucho vas a tener esa cantidad máxima de frames contiguos)

Saludos.-

**Comment by tferraro** [comment]
Cierro el thread por inactividad :) Cualquier cosa lo volvemos a abrir 💪🏻
