### ISSUE TITLE
Duda TP0 enviar paquete

### ISSUE THREAD

**Issue by GonzaloMartinezSa** [sisoputnfrba/foro#2319]
Como está en #2315 , me estaría pasando lo mismo o algo parecido. Este es el repo que estamos usando: https://github.com/nfernandezsanz/TP0-SO-ProbasteReiniciando

Puse un log info para ver si llega una lista y sí, confirmé que llega una lista con la cantidad de elementos de lo que mandé por el client. Por lo tanto, también pensaría que tengo un problema con el _iterator_. Dijeron, en el otro issue, que cambiara la función iterator para que lleve solo un valor, porque no hacía falta pasarle el logger, pero cuando saco de parametro el logger da el error "conflicting types for ´iterator´".

Así está el server actualmente:
```c
#include "server.h"

int main(void) {
	logger = log_create("log.log", "Servidor", 1, LOG_LEVEL_DEBUG);

	int server_fd = iniciar_servidor();
	log_info(logger, "Servidor listo para recibir al cliente");
	int cliente_fd = esperar_cliente(server_fd);

	t_list* lista;
	while (1) {
		int cod_op = recibir_operacion(cliente_fd);
		switch (cod_op) {
		case MENSAJE:
			recibir_mensaje(cliente_fd);
			break;
		case PAQUETE:
			lista = recibir_paquete(cliente_fd);
			int x = list_size(lista);
			log_info(logger, "%d",x);
			log_info(logger, "Me llegaron los siguientes valores:\n");
			list_iterate(lista, (void*) iterator);
			break;
		case -1:
			log_error(logger, "el cliente se desconecto. Terminando servidor");
			return EXIT_FAILURE;
		default:
			log_warning(logger,
					"Operacion desconocida. No quieras meter la pata");
			break;
		}
	}
	return EXIT_SUCCESS;
}

void iterator(t_log* logger, char* value) {
	log_info(logger,"%s\n", value);
}
```

Y así está la parte del paquete en el cliente:

```c
void paquete(int conexion)
{
	//Ahora toca lo divertido!
	char* leido;
	t_paquete* paquete_mandar = crear_paquete();
	while(strcmp(leido = readline("Ingrese para mandar al servidor: "),"")){
		agregar_a_paquete(paquete_mandar, leido, (strlen(leido)+1));
		free(leido);
	}
	enviar_paquete(paquete_mandar, conexion);
	eliminar_paquete(paquete_mandar);
	free(leido);

}
```

También aclaro que lo probé usando la consola de eclipse (la que aparece abajo cuando corrés el programa en eclipse) en los dos escritorios, uno con el servidor y el otro con el cliente. Tal vez el error está por ahí? Seguro como debía ser era compilar para armar un ejecutable de cada uno y correrlos en dos terminales distintas (puede ser?), pero como no la tengo muy clara con eso todavía no lo hice.

Si no es eso, debe ser lo que dijeron de modificar _iterator_, pero ,como dije, cuando saqué `t_log* logger` de los parámetros me dio error. Saludos.

**Comment by RaniAgus** [comment]
¡Buenas!

> Dijeron, en el otro issue, que cambiara la función iterator para que lleve solo un valor, porque no hacía falta pasarle el logger, pero cuando saco de parametro el logger da el error "conflicting types for ´iterator´".

Recordá también cambiar el prototipo que está en server.h: https://github.com/nfernandezsanz/TP0-SO-ProbasteReiniciando/blob/main/server/src/server.h#L10

Como habrán visto en Algoritmos en C++, también en C para poder llamar una función primero hay que haber definido, al menos, qué parámetros recibe y devuelve.

Saludos

**Comment by GonzaloMartinezSa** [comment]
Ufff, es verdad, no lo había cambiado en el .h. Se me pasó completamente jaja. Bueno, ahora sí lo cambié bien y funcionó, gracias. Puedo aprovechar esta oportunidad para preguntar sobre cómo es la entrega?

**Comment by GonzaloMartinezSa** [comment]
Ya que estamos otra pregunta, cuando abro una terminal y ejecuto el programa _client_, cuando llega a `ip = config_get_string_value(config, "IP");` da el siguiente error: Segmentation fault (core dumped). Corriéndolo desde eclipse no daba error. El ejecutable que corrí es el que aparece en la carpeta "Debug" después de compilar desde eclipse (en este caso, hablo siempre del client). Alguna idea de cual puede ser el error?

**Comment by RaniAgus** [comment]
> Ya que estamos otra pregunta, cuando abro una terminal y ejecuto el programa _client_, cuando llega a `ip = config_get_string_value(config, "IP");` da el siguiente error: Segmentation fault (core dumped). Corriéndolo desde eclipse no daba error. El ejecutable que corrí es el que aparece en la carpeta "Debug" después de compilar desde eclipse (en este caso, hablo siempre del client). Alguna idea de cual puede ser el error?

Tranqui, probablemente esté ocurriendo lo que se detalla en este post (te aconsejo leerlo antes de seguir con la respuesta): [Rutas Argentinas](https://mgarciaisaia.github.io/tutorial-c/blog/2015/04/23/rutas-argentinas/)

Entonces, como `config_create()` recibe una ruta relativa, mientras Eclipse ejecuta con el `$CWD` en `client`, vos al hacer...
```
cd client/Debug
./client
```
... estarías ejecutando con el  `$CWD` en `client/Debug`. Por lo tanto, como el config está en la carpeta `client` y el cálculo de rutas relativas inicia en `client/Debug`, el proceso no encuentra ningún archivo config ahí.

Fijate que `config_create()` debe estar devolviendo `NULL`, y luego, al intentar llamar a `config_get_string_value`, se está queriendo usar un puntero inválido, lo cual produce el segfault. Te recomiendo enormemente que hagas chequeos de errores para que el proceso falle ni bien éstos ocurren. En este caso sería algo como:

```c
t_config* config = config_create(...);
if (config == NULL) {
    // podés hacer un printf, log_error, puts, etc...
   exit(-1);
}

```

Volviendo al punto, en definitiva, una solución es simplemente ejecutar el proceso análogamente a como lo hace Eclipse:
```
cd client
./Debug/client
```

Saludos
