### ISSUE TITLE
Cambios de grupos? Encontrá un carpincho amigo en este issue!

### ISSUE THREAD

**Issue by iago64** [sisoputnfrba/foro#2320]
Buenas!

Habiendo cerrada la inscripción de grupos, habilitamos los cambios de grupos!

Por favor tengan en cuenta que los cambios no son para andar probando suerte si no para unificar a aquellos grupos que sufrieron bajas.

Como en el post de búsqueda de grupos inicial, por favor eviten postear números de celular ya que el foro es público 😉

Saludos.-

**Comment by NicolasPabloW** [comment]
Hola , en mi grupo somos 3 , si alguno anda sin grupo o hay un grupo de 2 , avisenme asi nos juntamos.

**Comment by dfjar** [comment]
Buen dia!, no me inscribi a ningun grupo, queria saber si aun hay tiempo para ingresar a alguno, gracias.

**Comment by iago64** [comment]
@dfjar Como va? 
Justo había un grupo que confirmamos que habían quedado 4 integrantes asique te asociamos a ese grupo como para que puedas arrancar con el tp.

Cualquier duda o inconveniente no dudes en mandar un mail a inscripciones@utnso.com.ar

Saludos.-

**Comment by dfjar** [comment]
ok, gracias!

**Comment by alejodilluvio** [comment]
Buenas tardes, no estoy con ningún grupo, quería saber si es posible unirse a alguno o ya no hay tiempo. Saludos.

**Comment by Damuchi99** [comment]
Buenas a todos, somos un grupo de 4 integrantes. Recien se nos bajo uno. Si alguno anda sin grupo avisen.

Un saludo!

**Comment by MaiiCardenas** [comment]
Hola, estoy sin grupo, quisiera saber si a algún grupo le falta uno...

**Comment by alejodilluvio** [comment]
> Buenas a todos, somos un grupo de 4 integrantes. Recien se nos bajo uno. Si alguno anda sin grupo avisen.
> 
> Un saludo!

Buenas, yo estoy solo, me puedo unir con ustedes o ya consiguieron? saludos.

**Comment by Damuchi99** [comment]
> > Buenas a todos, somos un grupo de 4 integrantes. Recien se nos bajo uno. Si alguno anda sin grupo avisen.
> > Un saludo!
> 
> Buenas, yo estoy solo, me puedo unir con ustedes o ya consiguieron? saludos.
Sin problema, avisame a mi mail daalvarez@frba.utn.edu.ar y te paso el link de grupo

**Comment by danimontesano** [comment]
Buenas, somos un grupo de 4 recursantes, estamos buscando a un integrante más ya que uno de nuestros compañeros se bajó. Buscamos a alguien que esté comprometido con la materia que tenga pensado aprobar el TP si o si.

Para comunicarse con nosotros les dejo mi mail: dmontesano@frba.utn.edu.ar

**Comment by JuaniPS** [comment]
Hola,

El sistema no me reunió con otros integrante y estoy buscando grupo. Curso los miércoles a la noche (K3674). Tengo una noción de C++, pero puedo seguir aprendiendo y me encantaría hacerlo.

Éste es mi mail: juanips.jips@gmail.com

Gracias.

**Comment by Danymmereles** [comment]
Buenas, somos un grupo de 4 personas. Nos falta un integrante para poder completarlo. Si alguien le falta grupo, con gusto se puede integrar. 
Mi mail es mmereles@frba.utn.edu.ar

**Comment by gnfigueroa** [comment]
Buenas, nos falta un integrante! el que tenga ganas de meterle al TP bienvenido sea!

mi mail es gafigueroa@frba.utn.edu.ar

Saludos!

**Comment by NicolasPabloW** [comment]
Buenas , en mi grupo sufrimos 2 bajas.
De los 3 que quedamos  , 2 somos recursantes con la teoria bastante fresca.
No importa que seas recrusante o no , solo te pedimos que estes dedid@ a cursar la materia hasta el final y aportar en el TP.

**Comment by Damuchi99** [comment]
Buenas de nuevo, recién se nos bajó otro integrante, nos falta uno. Si alguno anda sin grupo avisen por mi mail daalvarez@frba.utn.edu.ar

Un saludo!

**Comment by TomasAMolinari** [comment]
Buenas, somos 4 recursantes del cuatri pasado buscando a alguien que se haya quedado sin grupo. El que se quiera sumar me puede escribir a mi mail: tmolinari@frba.utn.edu.ar

Saludos!

**Comment by NicolasPabloW** [comment]
Buenas , en mi grupo nos falte falta un solo integrante.
De los que estamos , 2 somos recursantes con la teoria bastante fresca.
No importa que seas recursante o no , solo te pedimos que estes dedid@ a cursar la materia hasta el final y aportar en el TP.

Mi mail es nicokido2011@gmail.com

**Comment by federiver91** [comment]
Buenas!!

Si alguno está sin grupo o si siente que no están alineadas las ganas/disponibilidad propias con las del grupo en el que está y tiene la **necesidad** de aprobar el TP este cuatrimestre sí o sí, les comento que nos está faltando un integrante en el grupo.

Somos 4 recursantes (algunos de varias recursadas e, incluso, habiendo aprobado el TP y desaprobado la cursada) de más de 30 años con la carrera bastante frenada por esta materia. Con lo cual, la prioridad absoluta es meter el TP. Nos estamos juntando fijo entre 2 y 3 veces por semana. Incluso cuando cada uno está avanzando con lo suyo, dedicamos espacios para estar online todos al mismo tiempo.

Puntualmente, el integrante que dejó el grupo se ocupaba (o había empezado a ocuparse) del módulo de SWAMP. Sería un plus alguien que haya tenido contacto o haya iniciado el desarrollo de este módulo.

Por favor, avisen a mi mail y hablamos: federigonzalez@frba.utn.edu.ar

Saludos!
Federico

**Comment by silgch** [comment]
Buenas! 
Se nos bajo 1 integrante, Interesado en meterle al tp  escribir a sil.gch@gmail.com
En el grupo somos 3 recursantes con ganas de aprobar si o si.

**Comment by facundosofo** [comment]
Buenas tardes, 
Nos encontramos en búsqueda de un integrante(Kernel-MateLib). Venimos encaminados, completando el hito 3.
Les dejo mi mail: facusofia@frba.utn.edu.ar

**Comment by DanielBareiro** [comment]
Buenas, se nos bajaron dos integrantes del grupo y estamos en busqueda de nuevos integrantes para hacer el tp. Si alguien esta interesado que me mande un mail: danielbarei@hotmail.com.

**Comment by fdavinsonegoavil** [comment]
Buenas tardes, estamos buscando un carpin-amiguero para el modulo de Kernel. Si alguien esta interesado que me mande un mail fdavinsonegoavil@frba.utn.edu.ar
Saludos

**Comment by rpages2020** [comment]
Hola, estamos bucanando un integrante. Somos 4 recursantes que estamos al dia con el tp y la teoria. Queremos maximizar las posibilidades de promocion por eso buscamos alguien con ganas de trabajar. 
ruben_pages@hotmail.com.ar

**Comment by NazarenoLopez** [comment]
Hola buenas tardes, estamos buscando 2 integrantes, en el grupo estamos trabajando 3 recursantes de la materia. Queremos buscar gente con ganas para seguir adelante con el TP hasta el final y lograr aprovar la materia.

**Comment by larasnr** [comment]
Buenas tardes! Somos un grupo de 3 recursantes y estamos buscando 2 integrantes para meterle y aprobar la materia. Si quieren unirse me pueden escribir a larasnr@frba.utn.edu.ar
Gracias!

**Comment by Champa123** [comment]
Buenas estoy buscando grupo ya que el mio se disolvio, cualquier cosa dejo el mail para que nos pongamos en contacto afernandezbina@frba.utn.edu.ar
Saludos!

**Comment by mateorobaina** [comment]
Buenas, estoy buscando grupo porque el mio se disolvió, tengo el primer parcial aprobado y quiero meterle hasta el final, cualquier cosa mi mail es:
jrobaina@frba.utn.edu.ar
Gracias

**Comment by silgch** [comment]
Buenas! Se nos bajo un estudiante, estamos buscando un compañero para terminar el tp:  sil.gch@gmail.com.ar 
Gracias

**Comment by yairtele** [comment]
Buenas! Somos un grupo de 4 recursantes, se nos bajó recientemente un integrante y estamos buscando a alguien que tenga tiempo y voluntad para dedicarle y meter la materia. Cualquier cosa me pueden contactar a ytelezon@frba.utn.edu.ar

**Comment by matiaspar2000** [comment]
Buenas! Somos un grupo de 4 recursantes, se nos bajó uno recientemente y andamos buscando un reemplazo. Con el TP venimos bien de momento pero este último mes va a requerir de voluntad y tiempo.  
Contacto: mpartarri@frba.utn.edu.ar

**Comment by ganchipi** [comment]
Hola a todos! Les cuento que también somos un grupo de 4 recursantes, la 5ta persona que teníamos en el equipo se bajó y estamos buscando un reemplazo.
El que tenga interés en sumarse, dedicarle tiempo a full a hacer el tp escribir a: ganchipi@frba.utn.edu.ar
Saludos.

**Comment by Tomas83** [comment]
Buenos dias. Mi grupo se termino desaciendo y estaba buscando algun grupo para juntarme. Estoy dispuesto a trabajar ya que no quiero tener que recursar la materia.
Si llegan a tener lugar y quieren un quinto integrante, escribanme a: tomasrosman@frba.utn.edu.ar

**Comment by ezequielmalfonso** [comment]
Buenas, estoy buscando grupo, soy recursante y esta vez quiero aprobarla. Mi correo ealfonso@frba.utn.edu.ar
