### ISSUE TITLE
Problema al intentar descargar el tp0

### ISSUE THREAD

**Issue by NicolasMolina99** [sisoputnfrba/foro#2321]
Hola, tengo un problema a la hora de bajar el proyecto tp0, seguis las instrucciones y pude instalar el commons sin problemas. Pero con el tp0, me tira "No rule to make target install".
![tp0](https://user-images.githubusercontent.com/89660158/133365637-802e789d-35e1-4916-82c5-a49c584a18f2.png)

### 📦 Especificaciones de la VM
- Versión de VirtualBox: 
- Memoria RAM asignada:

### 🖥️ Especificaciones del host
- Sistema Operativo y versión:
- Memoria RAM:
- Procesador:

**Comment by RaniAgus** [comment]
¡Buenas! Fijate que en el enunciado dice que para descargar el repo simplemente hay que hacer `git clone`. De hecho, vas a ver que ya está descargado en la carpeta `/home/utnso/tp0` y por eso te aparece el mensaje `destination path already exists and is not an empty directory` 😉 

De todas formas, te aconsejo usar la Lubuntu para arrancar el TP0, ya que tiene entorno gráfico y se pueden levantar los proyectos con Eclipse ya configurado.

Saludos

**Comment by NicolasMolina99** [comment]
Gracias, resolvio ni duda. Igual, yo descargue el Lubuntu con entorno grafico, lo unico que a la hora de crear y configurar la VM no me deja elejir Lubuntu como sistemas operativo, pero si Ubuntu.

**Comment by iago64** [comment]
Buenas! Si tranqui, Lubuntu es el nombre que le ponen a Ubuntu pero con otro entorno de escritorio, es uno de los tantos ["sabores"](https://ubuntu.com/download/flavours) en los que viene ubuntu.

Saludos.-

**Comment by RaniAgus** [comment]
Perdón, mala mía, me confundí porque en la consola al principio dice `utnso@ubuntu-server` pero me había olvidado de que las Lubuntu tienen configurado el mismo nombre del equipo 😅

**Comment by NicolasMolina99** [comment]
Estoy teniendo problemas al instalar el Guest Additions, reiniciar la VM y reinstalar el VirtualBox no ayudaron.
![tpP0](https://user-images.githubusercontent.com/89660158/133479838-8b7601e6-e9c8-4784-a979-8946146e2a80.png)

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

1.- **No suban capturas de pantalla**, sus compañeros no pueden usar el buscador en esos casos.
2.- El mensaje:
`VirtualBox Guest Additions: Running kernel modules will not be replaced 
until the system is restarted`
Lo que te dice básicamente es que no va a cambiar nada mientras la VM esta corriendo, tenes que reiniciarla para que termine de aplicar los cambios (Es mas o menos como cuando metes un update de windows / linux o mac).

Saludos.-

**Comment by NicolasMolina99** [comment]
Hola, estuve intentando buscar una solucion pero nada, probe con instalar deferentes versiones de VB, pero siempre tengo el mismo resultado. Ademas, en el eclipse, cuando intento correr un proyecto de "Hello World" siempre en la consola sale : "make: all; make: Nothing to be done for all"

**Comment by RaniAgus** [comment]
Buenas, en el [post de bienvenida](https://www.utnso.com.ar/2c2021-bienvenidos/) hay linkeado un [video](https://www.youtube.com/watch?v=Q8wfpu38PMc) que explica cómo crear, compilar y ejecutar un proyecto en Eclipse.

El mensaje `make: Nothing to be done for all` aparece luego de apretar el martillito de `Build` cuando el proyecto ya fue previamente compilado y no hubo cambios. Para ejecutar hay que tocar el botón de `Run` como se puede apreciar en el video.

En cuanto a las Guest Additions, ¿solo no funciona redimensionar el tamaño de la pantalla, o tampoco [compartir el portapapeles entre guest y host](https://www.youtube.com/watch?v=xJ52dDTfCHo)? ¿Podrías completar el template que aparece al crear un issue para que contemos con más información y te podamos ayudar a entender cuál es el motivo del problema?:

```markdown
### 📦 Especificaciones de la VM
- Versión de VirtualBox: 
- Memoria RAM asignada:
<!--
Podés enumerar más configuraciones que creas que están relacionadas como la versión 
de Guest Additions, el controlador gráfico, etc
-->

### 🖥️ Especificaciones del host
- Sistema Operativo y versión:
- Memoria RAM:
- Procesador:
<!--
Podés enumerar más configuraciones que creas que están relacionadas como la versión 
de BIOS, la motherboard, etc
-->

### 💻 Logs
<!--
Si obtuviste por consola o por pantalla algo que pueda ayudar a darnos más contexto, no 
subas capturas de pantalla, copiá y pegá el texto. Podés darle formato código con (Ctrl + 'e'). 
Si el output es muy extenso, sentite libre de adjuntar un archivo de texto en su lugar.
-->
```

Saludos

**Comment by RaniAgus** [comment]
Buenas @NicolasMolina99, ¿alguna novedad?

**Comment by NicolasMolina99** [comment]
Ya lo solucione, Gracias
