### ISSUE TITLE
TP0 Entrega "precencial"

### ISSUE THREAD

**Issue by alexargb** [sisoputnfrba/foro#2322]
Buen día, quería consultar sobre la supuesta entrega "presencial" del TP0, de la cual no se nos había informado.

![image](https://user-images.githubusercontent.com/44444415/133447530-21107fff-5902-41cc-a614-bc653bdb732d.png)

Queríamos validar si esta entrega es efectivamente presencial en una sede FRBA o si se nos va a proponer una link de meet/zoom/etc para presentar la entrega.

**Comment by iago64** [comment]
Buenas! Cómo va?

Por este cuatrimestre todavía las entregas son por Discord, a menos que la facultad comunique lo contrario.

Saludos.-

**Comment by alexargb** [comment]
Qué alivio jajaj muchas gracias!
