### ISSUE TITLE
Dudas del enunciado

### ISSUE THREAD

**Issue by gabycosta04** [sisoputnfrba/foro#2323]
Hola buenas, teníamos algunas dudas de algunos modulos:

MateLib:
1- ¿Para que sería útil el uso de la estructura "group_info"  ? O sea, que tiene que tener? O nosotros en base a la interacción con los demas modulos tenemos que establecer que info ponerle y sacar ese void* group_info (que parece como algo genérico)?
2- ¿En un proceso que ejecute varias funciones de la matelib, deberíamos crear una conexión y cerrarla (con el backend) por cada una de esas funciones que se ejecutan secuencialmente?

Kernel:
1- Para planificar los procesos con el algoritmo SJF necesitaríamos las ráfagas de duración de los procesos y en el tp no dice nada de eso. ¿ Cómo lo calculamos?

SWAmP:
1-  Asignación global: "No existe cantidad máxima de marcos por proceso." Se pueden guardar mas de la cantidad establecida por el config? O se pasaría de la memoria? en caso de que se pueda que se guarden mas marcos por proceso, habria otros procesos que tendrían que poder tener menos marcos?
2-  "Habrá dos esquemas de gestión para la gestión de las páginas en swap, los cuales irán en función del esquema de asignación de páginas que haya en la memoria." Como se maneja? En un mismo archivo de swap se pueden dar asignación fija y dinámica?. En caso de que se maneje uno solo, como sabemos cual de los dos? Esta info la sacamos del config de SWAmP o nos debería decir memoria cual es el que usa?
3- "Caso asignación global" hace referencia a asignación dinámica?

**Comment by tferraro** [comment]
👋 Alo! Tengo parte de las respuestas; y puedo ayudar a ir agotando la queue 😛 

Respecto a la **matelib**🧉, el `group_info` es cualquier tipo de info que necesiten mechar. La estructura, forma, datos, los definen ustedes :). El `void*` como tipo es hiper necesario porque no hay definido una estructura, más allá de la que declaren ustedes. Porqué persé está adentro de una estructura y no afuera? Porque los prototipos de las funciones tienen que ser lo más definidos posibles, tener un void* en la def de tu lib fuerza a tus usuarios a siempre "castear" el tipado, cosa que en realidad es algo interno de la lib. Cuando mejor es tu abstracción, más libertad tenes :)

Es una forma de encararlo al tema de las conexiones, aunque le veo un poco burdo, porque está haciendo mal uso de recursos (abrir y cerrar sockets fuerza a constantemente tener el overhead del hanshake tcp y un montón de problemas extras) y por el otro, porque perdés la referencia unequívoca de un init "gratis" y tenes que manejarla de forma extra.

Sobre el Kernel, siendo que el SJF estima por ráfagas de duración como decis, que duración de tiempo podrías usar? Como hace el SO en la realidad para medir cuando no es expropiativo?

**Comment by gabycosta04** [comment]
> Es una forma de encararlo al tema de las conexiones, aunque le veo un poco burdo, porque está haciendo mal uso de recursos (abrir y cerrar sockets fuerza a constantemente tener el overhead del hanshake tcp y un montón de problemas extras) y por el otro, porque perdés la referencia unequívoca de un init "gratis" y tenes que manejarla de forma extra.

Con respecto a eso, el tema que me da duda es que entonces cuando pongamos un proceso en exec en el Kernel, va a ejecutar todas las funciones que tenga que ejecutar en ese instante? Porque según el diagrama de los estados de planificación, no podria hacer que ejecute una función y ponerlo en ready nuevamente, sino solo en exit (a no ser que esta función sea bloqueante)....

**Comment by gabycosta04** [comment]
Otra pregunta con respecto a las conexiones, yo podria hacer entre un proceso y otro constantes send y recv, para no tener que abrir y cerrar la conexión varias veces?

**Comment by tferraro** [comment]
> Con respecto a eso, el tema que me da duda es que entonces cuando pongamos un proceso en exec en el Kernel, va a ejecutar todas las funciones que tenga que ejecutar en ese instante? Porque según el diagrama de los estados de planificación, no podria hacer que ejecute una función y ponerlo en ready nuevamente, sino solo en exit (a no ser que esta función sea bloqueante)....

Eso funciona si y solo si la planificación es mediante algoritmos expropiativos :) Cosa que el TP no tiene, por eso es que va el caso que decis, ante funciones bloqueantes.

**Comment by tferraro** [comment]
> Otra pregunta con respecto a las conexiones, yo podria hacer entre un proceso y otro constantes send y recv, para no tener que abrir y cerrar la conexión varias veces?

Si! Totalmente :) Solo tenes que mantener el socket en algun lugar....spoiler, con esa idea está el group_info jaja

**Comment by gabycosta04** [comment]
> Eso funciona si y solo si la planificación es mediante algoritmos expropiativos :) Cosa que el TP no tiene, por eso es que va el caso que decis, ante funciones bloqueantes.

Entonces con esto te referis a que si el proceso tiene que ejecutar 3 funciones no bloqueantes seguidas, todo ese tiempo va a estar en estado exec, y no haria que pase de ready a exec, y de exec a ready constantemente no?

**Comment by tferraro** [comment]
Guarda, el pase de ready a exec si pasa 🙂  Lo que no sucede es el paso de exec->ready de los algoritmos expropiativos.

Por las dudas, no confundas el estado bloqueado del proceso en tu planificación con el estado bloqueado del proceso de linux del carpincho que corre por lo bajo 😉 Podes considerar que ese bloqueo es "cualquier estado en el que el proceso no esté ejecutando", a efectos de tu planif

**Comment by tferraro** [comment]
Te debía respuestas sobre
> SWAmP:
1- Asignación global: "No existe cantidad máxima de marcos por proceso." Se pueden guardar mas de la cantidad establecida por el config? O se pasaría de la memoria? en caso de que se pueda que se guarden mas marcos por proceso, habria otros procesos que tendrían que poder tener menos marcos?
2- "Habrá dos esquemas de gestión para la gestión de las páginas en swap, los cuales irán en función del esquema de asignación de páginas que haya en la memoria." Como se maneja? En un mismo archivo de swap se pueden dar asignación fija y dinámica?. En caso de que se maneje uno solo, como sabemos cual de los dos? Esta info la sacamos del config de SWAmP o nos debería decir memoria cual es el que usa?
3- "Caso asignación global" hace referencia a asignación dinámica?

1. Para esto, te pido que le pegues una leida al Silbers o al Stallings (o lo banques a verlo en la teoría 😉 para verlo en detalle ) Pero en overall, la asignación global hace un free-4-all, el que llega primero se queda el espacio. Si ya se llenó el swap, ahí es donde la cosa se les complica a todos. La asignación fija trata de evitar que haya procesos que se pasen de listos.

2. Va por config! Lo podes ver en la de la config de la memoria, dado que (acá viene el pt3), es el mismo tipo de asignación de la memoria y del swap.

**Comment by gabycosta04** [comment]
Buenas, quedo todo entendido, desde ya muchas gracias
