### ISSUE TITLE
Dudas MateLib

### ISSUE THREAD

**Issue by Eruizmagliano** [sisoputnfrba/foro#2324]
Hola! Tengo algunas dudas con respecto a la MateLib.

1.    Manejo de la mate lib: ¿Se clona el proyecto y se pasa al tp como módulo?
2.    ¿Hay una instancia de mate_instance y esta conserva referencia a todos los procesos? O ¿Habrá múltiples instancias de mate_instance? ¿Qué es una instancia de mate_instance? ¿Qué representan?
3.    ¿Para qué son las direcciones de memoria de la lib?

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Lo único que necesitan de la matelib es el .h, el resto del repo es simplemente ejemplos de como implementarlo o de como usarlo en los carpinchos 

2.- mate_instance van a tener 1 por cada instancia de la lib y la idea es que les sirva para tener la info que necesiten para que la lib funcione (por ejemplo algo rápido que se me ocurre que podrían tener es la info de IP y puerto del kernel)

3.- A cuales de las direcciones de memoria te referis? a los mate_pointer?

Saludos.-

**Comment by Eruizmagliano** [comment]
Hola!

La duda 3 surgió de esta parte del README:

"Las direcciones de memoria de la lib a utilizar, van a ser definidas como int32_t (Enteros de 32bits con signo), para evitar problemas de tipado contra punteros locales."

Este es el último ítem de los requerimientos no funcionales

**Comment by iago64** [comment]
Buenas!

Ahora si! Muchísima mas clara la duda 😄 la joda de eso viene porque si bien les recomendamos que usen las VMs para hacer el TP, las mismas no son obligatorias y cada alumno puede optar por usar las vms de la cátedra, una vm propia o si usa linux nativo puede usar su instalación de linux nativo.
Entonces lo que termina pasando si alguien usa un SO de 64 bits los punteros van a ocupar 64 bits, mientras que si alguien usa un SO de 32 bits los punteros van a ocupar 32 bits, entonces para estandarizar eso, las direcciones de memoria que va a devolver la lib van a estar estandarizadas en "32 bits" o un int32_t que es el tipo de dato que justo pesa 32 bits 😉 

Saludos.-

**Comment by tferraro** [comment]
Detalle importante:
Si tu lib de manejo de memoria fuera con memoria local posta posta, la lib podria devolver un puntero y podrías operarlo tal cual como harías como uno de malloc, *porque en la práctica tienen un funcionamiento análogo tras-babalinas*.
Pero no son punteros porque no son direcciones **reales** de memoria y para evitar "confundir", dado que no las podés operar como punteros, porque la memoria no existe de forma local, necesitás que sea un entero que haga de puntero a la memoria "no local" :).

**Comment by gastoncastineira** [comment]
Buenas @Eruizmagliano 

Quedó alguna duda más? Podemos cerrar el issue?

**Comment by Eruizmagliano** [comment]
Perdón, colgué y nunca mas contesté. Muchas gracias por sus respuestas! Ya me aclararon las dudas. También caí que la MateLib sería básicamente un biblioteca de ULTs y eso me clarificó bastante las cosas.
