### ISSUE TITLE
Tamaño de página en el módulo memoria

### ISSUE THREAD

**Issue by rnsavinelli** [sisoputnfrba/foro#2325]
Buenos días, el tamaño de las páginas en el módulo memoria como se obtiene?
Lo levantamos por configuración?
Hay que hacer alguna operación que no estaría interpretando?

**Comment by RaniAgus** [comment]
¡Buenas! Efectivamente nos comimos ese parámetro de la config como comentaba Nico acá: https://github.com/sisoputnfrba/foro/issues/2318#issuecomment-918528207. Ya lo dejamos anotado para agregarlo en la próxima revisión del enunciado.

Saludos

**Comment by RaniAgus** [comment]
Buenas @rnsavinelli, ¿quedó alguna duda sobre el issue?

**Comment by rnsavinelli** [comment]
No no, implementé en el archivo de configuración lo siguiente, de manera provisoria:
```c
TAMANIO_PAGINA=10
```
Y lo levanto como el resto de las configuraciones...

Espero a la espera de versión 1.1 del documento, igualmente, para hacer una implementación final. 
Acorde a lo que ustedes definan.

**Comment by iago64** [comment]
Tranqui que un mini spoiler del draft de la v1.1 tiene el campo con ese nombre 😄 

![image](https://user-images.githubusercontent.com/1622109/134382052-955686b9-3046-44fe-907c-f86093fe7515.png)

Saludos.-

**Comment by iago64** [comment]
Buenas! Ya quedo el cambio en la errata 😄 
Cerramos el issue, cualquier cosa lo pueden volver a abrir.
