### ISSUE TITLE
Entrega TP0

### ISSUE THREAD

**Issue by GonzaloMartinezSa** [sisoputnfrba/foro#2326]
Buenas, quiero saber cómo es la entrega del tp0. Actualmente tengo un repo con todo hecho, los ejecutables, y makefiles para compilar/borrar. Es suficiente? Mi duda surge de que antes habían dicho que para probar lo que hacíamos iban a usar la máquina virtual de Ubuntu, y medio que la cosa ahí es diferente. Sé que no lleva nota ni nada, pero es una entrega obligatoria, así que pregunto por las dudas.

**Comment by iago64** [comment]
Buenas! cómo va?

No hay problema con la entrega, pueden mostrarnos el tp0 desde su pc, como bien dijiste es una entrega sin nota, simplemente para validar que lo hicieron y despejarles cualquier duda que pueda surgir 😉 

Saludos.-
