### ISSUE TITLE
Parte final de la etapa 1

### ISSUE THREAD

**Issue by NicolasPabloW** [sisoputnfrba/foro#2327]
Llege hasta esta parte: -(cita del enunciado)
______________________________________________________________________________________________
"Recuerden bien la ubicación donde se está bajando, ¡porque la vamos a necesitar para
configurar Eclipse!
De la misma manera que las Guest Additions, tenemos un video para saber como Importar
un Proyecto con “makefile”.
¿Por qué con makefile? Porque make es una herramienta de gestión de dependencias y
compilación que vamos a estar usando en la materia y nos permite distribuirles un proyecto
ya armado, sin necesidad de usar el Eclipse de antemano. "
_________________________________________________________________________________________________

Me confunde que el video linkeado no habla de makefile (aunque talvez lo que se hace en el mismo usa makefile por atras).
Lo que termine haceiendo es abrir desde eclipse el proyecto  tp0 descargado (osea importarlo con la opcion "comun"  de "Open Projects from File System" , aclaro porque hay una en new que lo importa con makefile)

Y cuando le doy a compilar (con el boton del martillo en la barra de elclipse) me sale:
_______________________________________________________________________________________-
17:47:10 **** Incremental Build of configuration Default for project TP0 ****
make all 
make: *** No rule to make target 'all'.  Stop.

17:47:11 Build Finished (took 209ms)
_________________________________________

Y no me sale el la opcion en project ->properties->C/C++Build-> settings para importar las commnos , me salen solo 2 pestañas
en esa ventana.  
Creando un proyecto de 0 , sin importar nada , me salen mas pestañas ahi y una tiene la opcion de linkear las commons.

Por eso , no se lo que tengo que hacer.

Creo que se supone que debo importar el TP0 porque para eso se descarga , pero no entiendo porque no compila ni porque no 
me sale la opcion de linkear librerias.
Esa opcion la vi en el video linkeado.

**Comment by NicolasPabloW** [comment]
El proyecto del tp0 lo tengo descargado en una carpeta diferente del de commons , en la carpeta utnso , me pregunto si el tp0 debe estar entro de commons , o al revez , e importarlo como un solo proyecto. 
Despues voy a probarlo.

**Comment by iago64** [comment]
Buenas! Cómo va?

Lo vemos en la entrega del tp0 directamente porque por texto va a ser mas complicado de explicar y creo que le vas a sacar mas jugo a las explicaciones :)

Saludos.-

**Comment by rjmbelen** [comment]
Estaria bueno que hagan un post con esta misma duda que plantearon en este issue. Porque la verdad nos paso igual y me queda la duda todavía. Opte por crear un propio makefile y se genera en una carpeta default y los importe por separado. Vi varios issues con la misma problematica y aun no queda claro.

**Comment by iago64** [comment]
@rjmbelen Para levantar el tp0 deberian haberlo abierto con la opción de "Open projects from File System"

![image](https://user-images.githubusercontent.com/1622109/133913173-da0166e8-5b40-42d0-a38f-f20fb634551d.png)

Una vez ahi adentro seleccionan los proyectos de Cliente y Server:

![image](https://user-images.githubusercontent.com/1622109/133913190-64235db8-db5b-4d70-b098-398a10498282.png)

Una vez que importan los proyectos hacen click derecho en alguno de los proyectos (en este caso el cliente) y centro de C / C++ Build deberían poder ver lo mismo que se ve en la siguiente imagen:

![image](https://user-images.githubusercontent.com/1622109/133913197-b8d68556-4da2-434c-9b42-740f62ce4797.png)

Saludos.-

**Comment by NicolasPabloW** [comment]
Aaa  , esa era la forma entonces , con el import normal , no el de makefile.
Explicado asi para mi se entiende perfecto.
Mil gracias , ahora lo hago.

**Comment by NicolasPabloW** [comment]
En mi grupo pudieron avanzar pero no lo hicieron asi , y no se si esta bien lo que hicieron , pero de esa forma pudieron avanzar con las otras partes. Ahora me fijo esto y les digo , gracias de nuevo.

**Comment by iago64** [comment]
Buenas! 

No hay una única forma correcta de importar el proyecto, por ejemplo pueden haber creado un proyecto desde 0 e importado los archivos a mano y hubiera estado bien de todas formas, la anterior es la mas "directa" que tienen, pero de nuevo, no es la única.

Saludos.-

**Comment by tferraro** [comment]
@NicolasPabloW pudieron con esa? Se puede cerrar el issue? 👮‍♂️

**Comment by NicolasPabloW** [comment]
Todavia no la pude ver pprque tuve que arrancar a estudiar para los 2 finales que rindo esta semana.
El sabado sin falta lo verifico.

**Comment by NicolasPabloW** [comment]
Hola , ya lo verifique y funciona , pude compilar los 2 proyectos asi. 

Ya se puede cerrar este issue.Pero creo que puedo hacerlo yo xq veo un boton que dice eso , ahi lo cierro.
