### ISSUE TITLE
Falta el header de UUIDs?

### ISSUE THREAD

**Issue by MarcoPiatti** [sisoputnfrba/foro#2328]
Buenas, en el TP vi que en el repo de la mateLib se menciona el posible uso de UUIDs a modo de pid para los carpinchos.
>Para identificar una instanciación, cada grupo deberá elegir alguna forma de identificar cada una de estas instancias mediante algún medio (sean UUIDv4, combinaciones de IPs, pids, números autogenerados, etc).

Cuestión de que estuve chusmeando un poco y cuando fui a buscar la man page resulta que no había ninguna en la VM, tuve que ir a buscarla a internet ([link](https://man7.org/linux/man-pages/man3/uuid_generate.3.html)). 

Luego tratando de hacer el include no figuraba el header por ningún lado, que se supone se encuentra alrededor de `usr/include`, pero lo loco es que la biblioteca como tal sí existe:
```
utnso@ubuntu-server:~$ ldconfig -p | grep libuuid
	libuuid.so.1 (libc6) => /lib/i386-linux-gnu/libuuid.so.1
```
El tema es que me sigue faltando un `uuid.h` ¿Como podría solucionar? No quise instalar ningún paquete ni nada raro para no interferir mucho con la VM como nos la entregaron.

Gracias de antemano.

Edit: Perdón si está mal el tag del issue, no sabía realmente donde ponerlo.

**Comment by iago64** [comment]
Buenas! Como va?

Lo que dice el enunciado es que pueden usar cualquiera de esas cosas, un UUID, IP y puerto, o un número autogenerado, etc. Como regla de oro traten de no complicársela de mas.

Saludos.-

**Comment by MarcoPiatti** [comment]
Bárbaro, vamos por otro lado entonces! cierro hilo
