### ISSUE TITLE
Dudas sobre Swamp

### ISSUE THREAD

**Issue by heinHertz** [sisoputnfrba/foro#2329]
Hola tengo varias dudas sobre el modulo Swamp:

a) mi duda pasa por varias cosas: la memoria le manda directo los datos a Swamp? o sea yo tengo que programar una serialización de los datos  de que Proceso, numero de pagina,  que acción(borrar o almacenar por ej) y que datos(si almacena) y todo junto le manda a swamp?

b) Según entiendo,  hay una partición "logica" de las paginas de los files del swap, entonces,  si la memoria quiere trabajar  una pagina, yo tengo que hacer el calculo de almacenar desde numero_de_pagina x tamanio_de_pagina  y apartir de ahi hasta tamanio_de_pagina(bytes) ?  

c) Que sucede si los datos que tengo que persistir no son igual al tamanio_de_pagina o sea por ejemplo unos pocos, los datos que estaban se sobreescriben con \0 ?

gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

a.- Si, entre memoria y swap van a tener una conxión vía socket y van a tener que pasar la información que esta en las páginas, lo bueno es que no les va a importar que hay ahi adentro, simplemente van a pasar los datos de la página y lo que sea que necesiten para administrar las direcciones.

b.- Al igual que la memoria principal, uds van a tener archivos de un tamaño definido (en memoria uds tienen un solo malloc de un tamaño definido), con lo cual, van a tener que como bien decis, poder ubicar el número de hueco tanto en memoria princpal (frame) como en swap.

c.- Uds entre swap y memoria deberían mover páginas enteras, no deberían complicarse moviendo porciones de página 😉 

Saludos.-

**Comment by ncoen97** [comment]
Buenas!
Sumando a lo que dice dami sobre la c, tengan en cuenta que en memoria se van a guardar los allocs que vayan haciendo los procesos. Por lo tanto si se hace por ejemplo un `mate_memalloc(1)` con páginas de 32B, van a quedar dos allocs (el de 1B y uno libre de 13B).
Saludos.

**Comment by heinHertz** [comment]
Ah gracias.   Tengo otras dudas:
a)  solo para confirmar, la conexión entre memoria y swap NO es multihilo ? 
b) hay una parte que dice RETARDO_SWAP   = Tiempo expresado en  milisegundos que deberá tener de retardo ante cada operación (Puede ser 0).    ese retardo es de que el swap cumple con un tarea que le piden (obtener o almacenar una pagina) y cuando termina esa operacion empieza el retardo y ahi responde a la memoria ? entendi bien ?

gracias

**Comment by iago64** [comment]
Buenas!

A.- Solo va a tener un único socket el swamp y que no va a tener que ser multiplexado, esto quiere decir, el swamp no tiene ni hilos ni select().
Un poquito mas de info: la idea es que los hilos de la memoria tengan que sincronizar los accesos al socket con el swamp.

B.- La idea del retardo es mostrar la penalización que va a tener el sistema por acceder a swap, con lo cual si hacen todas las operaciones y tiran el retardo justo antes de contestarle a memoria o hacen primero el retardo y después la operación da lo mismo (Recordando matemáticas: el orden de los factores no altera el producto 😉).

Saludos.-

P.D: Dije alguna vez que las dudas asi numeradas son de las cosas que nos hacen felices a los ayudantes porque es mas facil de enfocar la respuesta? 😃

**Comment by heinHertz** [comment]
gracias
