### ISSUE TITLE
Inicio de la planificación. Mate_lib🧉 

### ISSUE THREAD

**Issue by ChavoMaiolo** [sisoputnfrba/foro#2330]
Buenas tardes, estábamos leyendo el enunciado y nos confunde bastante el uso de la `mate_lib` y su respectiva planificación:

1. `Mate_lib` solo comunica al kernel y memoria lo que se le pida (Ejemplo: `sem_init`) por parte del proceso ejecutable (Carpincho) y son estos módulos los encargados de planificar y hacer posible su ejecución?
2. Los tiempos de ejecución de cada función de la librería son definidos por nosotros? Es decir, un `mate_sem_post` podría por ejemplo requerir que el proceso pase 2 ciclos de cpu en EXEC?
3. Cada `mate_init` da lugar a un nuevo PCB (Solo para hacerme entender uso ese nombre) en el kernel? 

Particularmente nos esta costando entender el flujo de inicio de la planificación. Si nos podrían dar un ejemplo estaríamos mas que agradecidos. 🤗 🚀

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Efectivamente, la matelib no es mas que un "cliente" que va a comunicar las cosas que necesita al servidor el cual se va a encargar de ejecutar la lógica correspondiente para los pedidos, por ejemplo bloquear el proceso por una entrada salida o reservar memoria (En este caso puede que incluso el kernel solo sea un pasamanos a la memoria 😉)

2.- Te contesto con 2 preguntas:
2.1.- Para que les sirve asignar ciclos de CPU solo a las acciones de la lib?
2.2.- De que forma se diferenciaría un proceso que haga `mate_init` y atras `mate_sem_post` de uno que hiciera lo mismo pero entre las funciones estuviera haciendo mil cosas distintas? (Capaz que esta pregunta te contesta la primera)

3.- Efectivamente, el `mate_init` entre otras cosas debería "crear" un PCB en el kernel

Saludos.-

**Comment by gastoncastineira** [comment]
Buenas @ChavoMaiolo 

Quedó todo más claro ahora? Podemos cerrar issue?

**Comment by ChavoMaiolo** [comment]
Buenas, aún no nos queda en claro respecto al punto dos como deberíamos encarar la planificación. Solo cuando el proceso utilice una función de la  `matelib` es que el Kernel recibirá información para comenzar a planificar.
Nuestras dudas son:
1. Entonces debemos planificar las funciones que serán utilizadas por los procesos Carpinchos pertenecientes a la matelib?
2. Como sabemos cuanto tiempo va a tardar cada proceso a planificar, ya que el algoritmo del planificador de corto plazo es SJF ?

Perdón extender el issue y gracias por responder

**Comment by gastoncastineira** [comment]
Buenas de nuevo!

En realidad, me parece que el mambo viene porque entienden que lo que se planifica son las instrucciones de la lib. Creo que lo que le respondí a otro compañero en #2338 te va a servir
