### ISSUE TITLE
Dudas sobre RAM

### ISSUE THREAD

**Issue by jfloresmaquera** [sisoputnfrba/foro#2331]
Cosas a preguntar:
- La estructura de HeapMetaData tiene que estar dentro de las páginas?
- Cuando guardamos páginas en Memoria, estas van a MP y dsps a MV, o van a MV directamente?
- Algoritmo de reemplazo de paginas: no se van a poder combinar las configuraciones: dinamico y global O fijo local, es decir que son solo estas dos configuraciones y no podria haber una configuración que sea por ejemplo fijo global.

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Si, el HeapMetadata tienen que estar dentro de las páginas ya que si no van a poder saber donde empieza y donde termina una asignación de memoria. De hecho por eso esta en el diagrama donde el celeste es la página 0 y el naranja es la página 1:

![image](https://user-images.githubusercontent.com/1622109/133915891-b33891a4-592f-4783-81ee-e37b6fce0795.png)

2.- Esto va a depender del esquema que tengan en swap, si es asignación global van a ir bajando a medida que lo necesiten, mientras que si es asignación fija van a reservar X "páginas" de swap de entrada.

3.- No te termino de seguir en este caso, estas hablando de combinaciones de memoria principal y swap?

Saludos.-

**Comment by jfloresmaquera** [comment]
Buenas! Leyendo las respuestas nos volvieron a surgir dudas. 
1. Todo bien, entendido. 
2. Okey, esta es la que nos genero más dudas. Para que sea más entendible iría con un ejemplo, con 5 marcos en MP y 10 en MV.
Por lo que entendimos con el grupo en función a la respuesta es lo siguiente:

Asignacion: dinámica y global.
Los procesos van a ir requiriendo marcos de la MP a medida que los necesiten y cuando ya se acaben esos 5 marcos (es decir, queden todos en ocupado), se comenzará a pedir en memoria virtual. O sea, podría tenerse lo siguiente
1.Proceso 1 pide 3 marcos en MP.
MP: 1|1|1|X|X
2. Proceso 2 pide 1 marco en MP.
MP: 1|1|1|2|X
3. Proceso 3 pide 3 marcos en MP
MP: 1|1|1|2|3
Como la MP no puede completar esta demanda, entonces van a pedirse en MV los 2 marcos que faltan, por lo que finalmente querían las memorias:
MP: 1|1|1|2|3
MV: 3|3|...| 

Asignacion: fija y local con 3 marcos por proceso.
1.Llega P1
MP: 1|1|1|X|X
2. Llega P2
MP:1|1|1|2|2
MV: 2|....|
3.Llega P3
MP: 1|1|1|2|2
MV:2|3|3|3|...|

ES DECIR: 
SIEMPRE pido primero cosas en MP y LUEGO cuando ya no tenga espacio ahí, pido lo restante en MV?
¿Esto sería correcto?

![image](https://user-images.githubusercontent.com/27295049/134095934-15ae0560-c555-4cc0-8f55-c8e2192f8629.png)

SIEMPRE pido primero cosas en MP y LUEGO cuando ya no tenga espacio ahí, escribo lo restante en MV? O voy "bajando" a memoria virtual cosas de memoria principal cuando llega un nuevo proceso que me requiere una cantidad X de marcos con la memoria llena? Los algoritmos de intercambio arrancarían una vez que MV y MP esten AMBOS llenos en simultáneo? Amplio esta última pregunta: 
a) se baja a MV una pagina que fue seleccionada por el algoritmo de reemplazo, es decir, mando una pagina de un proceso ya cargado en MP
b) se baja a MV la pagina con la informacion nueva del proceso que estoy tratando en ese momento, salteandome la parte de seleccion de frame dentro de la MP ya que no se reemplazaria.

3. Sí, igual ya nos respondimos releyendo el enunciado un par de veces más.

4. Otra duda que nos surgio fue en la configuración de Asignacion fija y local:
SI tuvieramos el siguiente caso:

MP: 1|1|1|2|2
MV:2|3|3|3|...|

y me solicitan una pagina del proceso 3, como hago para elegir un marco a Swapear de la MP si no tengo ninguna asignada para el Proceso 3? Me tendría que traer todo el proceso a memoria? Haría un swap entre procesos?

5. Una preguntita plus: la memoria virtual a la cual se referencia en la RAM es el modulo SWAmP o la memoria principal tmbn tiene una parte de memoria virtual aparte?

**Comment by iago64** [comment]
Buenas!

- Memoria principal: 
    - *Asignación Fija*: cada proceso va a tener N frames y no va a poder pedir mas, es decir si tiene 3 listo, no va a poder asignar mas nada y va a tener que mandar cosas a SWAP. Tu algoritmo de reemplazo va a correr SOLO contra las páginas de tu proceso, por lo que los procesos que _no estén suspendidos_ van a tener al menos los frames reservados en memoria.
    - *Asignación Variable*: todos los procesos se pueden ir robando frames entre ellos, entonces tu algoritmo de reemplazo va a seleccionar una victima de entre *todos* los frames.

Cuando se llena la memoria principal, recién ahí vas a ir a SWAP (o MV) y ahí es donde entran en juego los tipos de asignaciones de memoria, donde si tenes:
- *Asignación fija*: todas las páginas del proceso van a quedar juntas, por ej: 1-1-1-1-1-2-2-2-2-2-5-5-5-5-5-3-3-3-3
- *Asignación variable o global*: Las páginas pueden intercalarse, por ej: 1-2-1-2-1-1-1-5-5-3-5-1-2

*Pregunta bonus*: la memoria virtual es el proceso SWAmP.

Saludos.-

**Comment by MarcoPiatti** [comment]
Buenas @iago64 ! Justo leí tu ultima respuesta y me entró una duda
> por lo que los procesos que no estén suspendidos van a tener al menos los frames reservados en memoria.

Significa que la suspensión de procesos por el planificador de mediano plazo repercute en la memoria que se les fue asignada? Tenía entendido por la consigna que la suspensión a nivel del TP era solo interna a la planificación del kernel

**Comment by jfloresmaquera** [comment]
Hola! En función de la respuesta me surgió una duda más: 
En la asignación fija, entonces, puede tener esas N páginas en memoria principal pero podría tener más frames asignados que estén en memoria virtual? Es decir, el N es limitante de la cantidad de páginas en MP pero no limitante a cuánto puede crecer el proceso?

Por lo que entendimos hay una correlación entre los procesos en MP y en MV: si el proceso este suspendido está en MV, si no esta suspendido está en MP.
Teniendo esto en cuenta tenemos una duda respecto a los procesos:
- Asignación fija: el planificador a mediano plazo indica que procesos van a suspendido. El algoritmo de reemplazo es local, por lo tanto no hay ningun problema aca. ¿El planificador nos dice que proceso va  a suspendido y diciendonos cual pasa a no suspendido, haciendo el switch?
- Asignación variable o global:  ACA es nuestra duda, como es de reemplazo global se nos puede dar el caso que reemplazemos todos los marcos de un proceso que estaba en MP, terminando completamente en MV ergo quedando dicho proceso en suspendido. ¿Esto puede ocurrir o tenemos que dejar que solamente el planificador permita que un proceso pase a un estado suspendido? ¿en caso de que se pueda dar este caso, tenemos que avisarle a el planificador que pusimos en suspendido un proceso, no es asi?

**Comment by iago64** [comment]
Buenas!

@MarcoPiatti Tu duda la tenemos marcada para errata (Por eso la tardanza en responder)

@jfloresmaquera En memoria principal el máximo es lo maximo que puede tener asignado al mismo tiempo, pero nada te impide que tengas mas frames en swap :)
La correlación entre MP y MV es que un proceso puede tener páginas en ambos lados (esto lo van a terminar de ver bien en la teoría). En el caso de los procesos suspendidos, están en su totalidad en swap.
En asignación fija, el algoritmo de reemplazo corre de forma local a los frames de tu proceso.
En asignación global, el algoritmo de reemplazo corre de forma global a todos los frames.

La parte de suspensión como comente antes lo tenemos marcado para errata y lo van a poder checkear mejor en cuanto se libere la v1.1 del enunciado que estamos trabajando para liberarla esta semana.

Saludos.-

**Comment by matiasimartin** [comment]
Buenas me surgió una duda con respecto a 
> Asignación fija: todas las páginas del proceso van a quedar juntas, por ej: 1-1-1-1-1-2-2-2-2-2-5-5-5-5-5-3-3-3-3

En donde y por qué, quedarían juntas las paginas? En MP o MV? 

Si es en MP,  ¿Es porque en asignación fija voy a reservar n frames por cada proceso aunque no estén en uso? Ejemplo, el proceso 1 solo pidió un alloc que ocupa una página (por el momento), pero igualmente le reservo n frames en MP a ese proceso? (Y siempre ese proceso se manejaría sustituyendo pags en esos n frames continuos)

**Comment by iago64** [comment]
Cerramos el issue por inactividad, cualquier cosa lo pueden volver a abrir.
