### ISSUE TITLE
Memoria. Duda al dividir un alloc

### ISSUE THREAD

**Issue by matiasimartin** [sisoputnfrba/foro#2332]
![image](https://user-images.githubusercontent.com/49007855/133943479-086ab896-ba76-4c72-93a3-c0ca627c66aa.png)

Tengo un par de dudas.
a) Que pasaría si, en este ejemplo, llega un memalloc de 9bytes donde el primero esta libre y el segundo ocupado. Entra perfectamente en el de 11 y sobran 2bytes. Que pasa con esos 2bytes que quedaron? No puedo hacer otro alloc porque no entra ni un heap.

b) Sé que este es un ejemplo y podría quedar así en algún momento. Pero asumiendo que solo se hizo un memalloc de 11bytes, el segundo no debería haberse creado solamente con 3 bytes hasta el fin de la página 0? 
Si la respuesta es no, entonces cuando llegue otro memalloc (de 20 por ej), como el siguiente apunta a null. Puedo "agrandar" esos 3 bytes hasta completar (con 17) lo que me están pidiendo? (Siempre que sea el último alloc).

**Comment by ncoen97** [comment]
Buenas!
 
a. En ese caso no podrías usar el primer alloc porque te quedaría inconsistente, por eso cuando hagan la busqueda van a tener que seleccionar un alloc que tenga exactamente 9B o que sea mayor a 18B (9 para el nuevo alloc + 9 para el siguiente HeapMetadata libre).

b. En este caso hay otra página reservada porque el 2do alloc no está libre. En el caso que describís (que sería el del ejemplo), primero se hizo primero un `mate_memalloc(11)` (donde quedó un 2do alloc libre de 3) y luego un `mate_memalloc(20)` (y por eso se agregó la página 2).

Saludos.

**Comment by matiasimartin** [comment]
Ah perfecto.
No me quedo claro la b), entonces si se podría juntar el espacio del último alloc para completar el tamaño que te piden?

**Comment by ncoen97** [comment]
Creo que no te estoy siguiendo la consulta. Qué allocs decís de juntar? En el ejemplo hay solo uno libre (que es el último).

**Comment by matiasimartin** [comment]
"(donde quedó un 2do alloc libre de 3)" acá me perdí. Con el primer mate_memalloc(11) quedo un segundo libre de 3B. Luego llego un mate_memalloc(20), en el ejemplo no está el de 3B, entonces pensé que esos 3B libres que habían quedado (como estarían libres) se "fusionaron" para hacer el de 20B, porque si no entre el de 11B y 20B tendría que haber uno de 3B o no?

**Comment by ncoen97** [comment]
Okay, ahí entendí a lo que vas. Lo podes pensar como que al agregar la 2da página, el espacio libre de 3 pasa a ser un "espacio libre de 35" donde ahí reservas uno de 20.

**Comment by iago64** [comment]
@matiasimartin  Si no hay mas dudas, no te olvides de que podes cerrar el issue 😉
