### ISSUE TITLE
Duda sobre ineraccion proceso carpincho y MateLib

### ISSUE THREAD

**Issue by gustavosrey** [sisoputnfrba/foro#2333]
Supone que el proceso carpincho hace sem_wait y se bloquea en ese caso se lo comunica al kernel, entoces suspendemos el proceso en el kernel (su PCB), pero además tenemos que suspender el proceso carpincho como si fuera un semáforo real lo que ejecuto pero implementado por CarpinchOS. o cuando le pedís memoria a la librería además de asignar pagina devuelve un puntero al proceso carpincho para que pueda usar esa memoria?. Lo que pregunto es si el proceso carpincho tiene que ser un espejo o reflejar todo lo que sucede en el kernel y en la memoria, es decir si el proceso carpincho pide IO, este se bloquea hasta que termine la IO?

**Comment by iago64** [comment]
Buenas!

Justamente el carpincho no va a poder ejecutar mas porque se va a quedar a la espera de que el kernel le conteste que pudo tomar el semáforo, entonces se queda ahi bloqueado en el recv "for ever" (las comillas son porque en realidad ni bien pueda tomar el semáforo le contestan que esta todo joya y salen andando)
Este comportamiento (detalle mas, detalle menos) es el que ocurre cuando un programa de C llama a un semáforo y no lo puede tomar, su ejecución queda "congelada" en ese punto hasta que pueda tomar el semáforo y de ahí retoma.
De forma similar va a pasar con las peticiones de IO, la lib manda el mensaje y se va a quedar esperando a que le contesten desde el kernel que termino la IO (después lo que haga el kernel es problema del kernel)

No se si termine de explicar bien el comportamiento, pero cualquier cosa chifla y vemos de agregar algún diagrama como para ser mas claros :)

Saludos.-

**Comment by gustavosrey** [comment]
Muchas Gracias por responder! si entendi bastante mas , tengo un par de inquietudes mas

1) La cantidad de semaforos SEM1 SEM2 etc, la seteamos en el archivo de configuracion?

2) mate_inner_structure tenes dos miembros memory y sem_instance de tipo semaforo no termino de entender bien para que lo usarias, evidentemente el semaforo esta para protejer la memoria, pero no puedo relacionarlo de que memoria se trata ya que en el ejemplo no se le da ningun valor a memory 

3) en el ejemplo de matelib usas un archivo de configuracion mate_init(&mate_ref, "./config.json");,  pero ni en el enunciado ni en el ejemplo lo usas

4) Se necesitaria distinguir entre los distintos procesos carpinchos, lo cual puede hacerse con su PID, con esa informacion alcanzaria para distinguir los procesos y la instanciacion de la libreria?

Gracias

**Comment by iago64** [comment]
Buenas!

1.- No, justamente la idea es que se puedan crear mediante la función mate_sem_init que te pide el nombre del semáforo

2.- La estructura mate_inner_structure, simplemente esta para ejemplificar que es una estructura que van a tener que definir uds que les va a servir para poder hacer funcionar su lib, por ejemplo puede tener IP y Puerto del kernel

3.- La idea del config es que de algun lado tienen que poder obtener los datos de por ejemplo IP y puerto del kernel para poder hacer las interacciones de la lib y en el ejemplo de uso se puso ese path a un archivo "config.json". 
En el ejemplo de implementación no se usa porque es una implementación "local" de la lib, pero si esta en la interafaz es porque uds tienen que hacer uso de un archivo de configuración para poder configurar su lib y poder como dije antes, mandar los mensajes al kernel.

4.- Pueden usar lo que gusten, el PID es una buena idea, otras pueden ser un id autoincremental o algo que le pasen por config. Lo bueno de que no les forcemos un archivo de config de la lib es que uds pueden tomar lo que les resulte mas cómodo, mientras puedan identificar unívocamente a un carpincho, esta todo bien 😉 

Saludos.-

**Comment by Mdavicino** [comment]
Buenas! Tengo una consulta sobre lo siguiente:

> 2.- La estructura mate_inner_structure, simplemente esta para ejemplificar que es una estructura que van a tener que definir uds que les va a servir para poder hacer funcionar su lib, por ejemplo puede tener IP y Puerto del kernel

Se sugiere guardar IP y Puerto de kernel/memoria en mate_inner_structure. Esto es porque cada vez que se requiera comunicar nos tenemos que conectar nuevamente? Con mi grupo habíamos entendido que dentro del mate_init nos conectábamos y esos datos ya no nos serían de utilidad.

Saludos!

**Comment by iago64** [comment]
@Mdavicino es una idea solamente, por ejemplo en esa estructura si uds crean una conexión y jamás la cierran pueden guardar el puerto en esa estructura 😉 
Un poco la idea de fondo fue no cortarles caminos de ideas posibles y que uds nos digan: _Che se nos ocurrió esto para manejar la conexión con el kernel, como lo ven?_ y ahí nosotros podamos ayudarlos a que camine por un buen sendero.

**Comment by Mdavicino** [comment]
Genial, muchas gracias!!

**Comment by iago64** [comment]
Cerramos el issue por inactividad, cualquier cosa lo puede reabrir el creador :)
