### ISSUE TITLE
Consulta enunciado - archivos swap

### ISSUE THREAD

**Issue by danimontesano** [sisoputnfrba/foro#2334]
Hola buenas noches, nos surgió una duda en el módulo de SWAmP. La pregunta principal es si nosotros debemos crear un único archivo swap para cada proceso o un único archivo swap para todos los procesos que nos lleguen. Es decir, ¿yo tendría un archivo por proceso o un archivo con todos los procesos?

### 📔 Citas del enunciado/videos
>Indistintamente del caso, ante la llegada a swap de nuevos procesos, el módulo siempre debe guardar las páginas de ese proceso en un único archivo de swap. Esto quiere decir que no puede haber dos páginas de A, una en el archivo 1 y otra en el archivo 2, ambas páginas deben estar en un único archivo.

Página 20 del enunciado.

**Comment by gastoncastineira** [comment]
Buenas

Puede ser lo mismo que https://github.com/sisoputnfrba/foro/issues/2309#issuecomment-918705276?

**Comment by danimontesano** [comment]
No lo había visto. Pero por lo que tengo entendido, luego de ver ese issue, no habría problema con hacer 1 archivo por proceso. ¿Correcto?

**Comment by gastoncastineira** [comment]
Sí habría problema.

Como dice Dami en la respuesta: 

> Podes tener 2 procesos en el mismo archivo de swap, pero no podes tener 1 proceso en 2 archivos de swap diferentes.

A vos se te ingresa por archivo de configuración una lista de archivos con su tamaño, y esos son todos los archivos que tenés para todo el swap. Cada uno de esos archivos puede haber más de un proceso, pero un proceso no puede estar en dos archivos al mismo tiempo. El enunciado **NO** pide que se creen archivos bajo demanda

**Comment by ncoen97** [comment]
Buenas!
Acuérdense que cuando las dudas quedan resueltas ya pueden cerrar el issue.
Saludos.
