### ISSUE TITLE
Dudas con MateLib

### ISSUE THREAD

**Issue by victoriaguillosson** [sisoputnfrba/foro#2335]
Buenas! estuvimos viendo el enunciado de MateLib y el ejemplo de implementación de la misma y surgieron dudas. Acudimos al foro y encontramos este issue #2330 que nos hizo dudar aun mas sobre el rol de este modulo.

1.  Cual es el objetivo del ejemplo de implementación de la matelib que tenemos disponible en el repo? No nos queda claro si las funciones desarrolladas son las bases para que nosotros a partir de esas, sigamos completando o no tiene nada que ver? 
2.  En el issue citado se menciona que la matelib es una especie de "cliente" cuando nosotros pensamos que era solamente una sharedlib que los otros módulos van  a hacer uso de la misma, como deberíamos considerarla? es una sharedlib o es un cliente?
3.  La estructura mate_instance representa al proceso no implementado que nos va a llegar (carpincho)?

Muchas gracias!

**Comment by alejcha** [comment]
lo que entiendo es que es una libreria que el carpincho va a usar en su #include
mate_init conectaría con kernel/memoria y despues hace lo que necesita hacer (usar semaforos, pedir memoria, etc)
mate_instance  va a ser un "identificador" de esa conexion

**Comment by ncoen97** [comment]
Buenas.

1. El ejemplo de implementación intenta mostrar como sería la implementación de la lib si se tuviera que resolver en forma local (por ejemplo el `mate_memalloc` sería un `malloc()`). Ahora, para la resolución del TP esas funciones no van a correr locales sino que van a funcionar en el sistema distribuido que forman los otros módulos. Por lo tanto la lib pasa a ser más un manejador de conexiones/mensajes con el kernel. 
2. Es una biblioteca compartida, solo que se menciona como cliente porque va a correr con el carpincho que va a ser cliente del kernel/memoria a través de la lib.
3. `mate_instance` adentro tiene un `void* group_info` donde cada grupo va a guardar la info que necesite. Por ejemplo la info que les pasan en `mate_init()` se la pueden guardar ahí para poder accederla cuando se llamen las otras funciones de la lib.

Saludos!

**Comment by ncoen97** [comment]
Buenas! @victoriaguillosson Quedaron resueltas las dudas? Podemos cerrar el issue?

**Comment by victoriaguillosson** [comment]
Todo super claro, gracias!
