### ISSUE TITLE
Consultas funcionamiento matelib

### ISSUE THREAD

**Issue by matiaspar2000** [sisoputnfrba/foro#2336]
Buenas, tengo algunas preguntas sobre como tendría que funcionar la lib y sobre que puedo y no hacer

1.  Tema config; por lo que veo en mate_init y en el enuciado se recibe la ruta de una config la cual tiene como mínimo un puerto y una ip. Mi duda era, esta config es propia de cada carpincho (es decir no la conozco y no la tengo que tocar) o es algo de la lib y puedo agregarle cosas si necesito? 

2.  En los requerimientos no funcionales cuando habla de "Permitir un nivel de loggeo a modo de "debug", dado por config, de las acciones de la biblioteca." A que se refiere con "dado por config"? Cambia algo de como veníamos haciendo el logeo de cosas por ejemplo en el tp0 con la función de log_info y un archivo .log? 

3.  Puedo incluir en la matelib una shared library? Puedo incluir las commons en matelib? Y otros .c y .h con funcionalidad extra?

**Comment by ncoen97** [comment]
Buenas!

1. Como dice en el enunciado, "el archivo de configuración a utilizar por la lib será de especificación libre". Entonces cuando se inicie un carpincho se le va a pasar ese path (ya sea hardcodeado en el código o por algún parametro) para que lo ponga en el `mate_init()`.
2. La idea es que en la config se les diga el nivel del error (info/debug/etc) y ese parametro se lo pasen al `log_init()`. Tengan en cuenta que cuando se le pasa un nivel de log lo que hace el logger es mostrar todos los logs de ese nivel o más prioritarios (los niveles los pueden ver en [el enum t_log_level](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/log.h)). Por ejemplo si se le pasa el nivel LOG_LEVEL_INFO se van a mostrar todos los log_info, log_warning y log_error.
3. Si, mientras sigan la interfaz de la lib no debería haber problema.

Saludos.

**Comment by matiaspar2000** [comment]
Entendido, muchas gracias. Cierro hilo
