### ISSUE TITLE
Consultas varias 

### ISSUE THREAD

**Issue by alejcha** [sisoputnfrba/foro#2337]
Buenas tardes tengo algunas dudas
1) En memoria, en caso de que un carpincho finalice sin liberar la memoria reservada, hay que liberarla de forma "forzada"? mismo si quedan recursos tomados en kernel

2) la dirección lógica que devuelve al asignar el primer bloque de memoria para cada carpincho, seria 0 (o un numero arbitrario), no? porque no tenemos forma de saber la dirección lógica del heap real

3) en caso de no haber lugar en memoria para una nueva alocación y se utilice swap, al usar paginación bajo demanda se alocaría en swap directamente, y recién cuando quiera escribir/leer en el espacio alocado movería de swap a memoria?

gracias

**Comment by tferraro** [comment]
1. A gusto y piachere 🙂 Pueden asumir que los carpinchos van a ser buenos ciudadanos de Nordelta y cerrar los tachos de basura que abran 😛 

2. Por las dudas, la dirección logica es lo que después se va, con la tabla de páginas, a convertir en la data posta a buscar. Sobre eso, se para la implementación de reserva de memoria (parece un segmento, pero cuasi no lo es). Por lo que tu dirección logica va a ser donde arrancó tu pedacito de malloc :), no 0.

3. Antes de responder alguna huevada con esto, te lo dejo pending, consulto y te digo 😅

**Comment by tferraro** [comment]
Te debía la (3). Efectivamente es un sí, tal cual como hacen los S.O.s en la posta :)

**Comment by alejcha** [comment]
Perfecto! muchas gracias!!
