### ISSUE TITLE
Duda sobre carpinchos sin peticiones & algoritmo SJF sin desalojo

### ISSUE THREAD

**Issue by jlsuh** [sisoputnfrba/foro#2338]
Muy buenas a todos :)

Teníamos un par de consultas.

1. Nuestro actual modelo: posterior a la creación del pcb del proceso-carpincho entrante, lo agregamos a la lista new y hacemos el `sem_post` para indicar que hay un nuevo carpincho en new. El planificador de largo plazo toma dicha instancia del semáforo new y transiciona el pcb del carpincho de new->ready. La disyuntiva se da cuando el pcb del carpincho es tomado por el planificador de corto plazo, haciendo la transición de ready->exec. Nos planteamos el caso de que el proceso carpincho podría solamente tener en main:
```c
mate_init(...);
// nada en el medio
mate_close(...);
return 0;
```
Al momento de que el hilo-cpu (1 instancia de multiprocesamiento) se comunique con el carpincho, no tendría peticiones disponibles para mandárselos a kernel. Para este caso nos planteamos que el `mate_close` podría ser un centinela que indique la finalización de dicho hilo que representa la cpu. No obstante, teniendo otro caso como el siguiente:
```c
mate_init(...);
// nada en el medio
return 0;
```
No se podría tomar al `mate_close` como un centinela para cerrar dicho hilo-cpu y el kernel nunca se daría cuenta de que el carpincho, ya ocupando una instancia de multiProgramación y una instancia de multiProcesamiento, finalizó sin aviso. De esta forma y ante eventuales casos repetidos colmaría completamente el grado de multiprocesamiento, imposibilitando la planificación.
Se nos ocurrió, para el último caso, transicionar el pcb del carpincho de new->ready solamente en caso de que llegue una petición inmediatamente luego del `mate_init`, pero ésto no sería posible debido al último párrafo del planificador de largo plazo:
> "Este planificador usará el algoritmo FIFO."

En caso de que algún proceso carpincho, que no sea el `head` de la cola de new, sea el que reciba una petición inmediatamente luego del `mate_init`, no se estaría respetando el algoritmo fifo (podría ser alguno que esté por mediados de la cola o en su defecto el último).
Honestamente no se nos ocurre cómo apalear el presente problema y queríamos saber si podríamos recibir algunas directivas para saber hacia dónde tirar.

2. En caso de que el planificador deba planificar mediante SJF sin desalojo, nosotros planteamos de que la estimación actual para cada carpincho es siempre la misma para todos los carpinchos debido al valor dado por config (el resultado de la media exponencial sería la misma). Como no se sabe cuántas unidades de cpu efectivamente ejecutará un cierto carpincho, planteamos un sistema de obtener la variación de tiempo como: marcar el tiempo inicial al momento de la creación del hilo-cpu y obtener el tiempo final al momento de alguna petición bloqueante. De ésta forma conseguiríamos la variación de tiempo, sirviendo como dato para la siguiente estimación y semánticamente siendo la ráfaga de cpu efectivamente ejecutada.
Teníamos la duda de si todos los carpinchos inician su estimación actual en base al valor dado por config (resultado de la media exponencial y que en caso de empate elija por fifo) o debería de alguna forma la matelib "adelantarse en el barrido del código del main del proceso carpincho" como para poder saber cuántas peticiones va a realizar el carpincho y en base a ello calcular la estimación actual.

Muchas gracias de antemano!
Saludos :)

**Comment by gastoncastineira** [comment]
Buenas!

1. Honestamente no creo que no poner un `mate_close` vaya a ser una prueba. Más allá de eso, yo interpretaría eso como lo mismo que no hacerle un free a un malloc. Es un leak en tu sistema que corre por el lado del desarrollador solucionar y usar bien las herramientas que le brindan para que no aparezcan esos problemas, así que no me quemaría mucho la cabeza con eso si estuviera en su lugar
2. Es correcto, la estimación inicial de todos los procesos en SJF va a dar la misma porque comparten alfa, estimación anterior y ráfaga anterior (cero para la primera). Donde va a empezar a divergir es cuando los procesos empiecen a bloquearse, porque ahí la estimación y ráfagas anteriores sí van a dar distinto.

Otra cuestión, hay dos cositas que quería remarcar que medio sobreentiendo por ciertos fraseos en lo que preguntás. Perdón si entiendo mal

1. Lo que se planifica en el sistema no son las solicitudes de la lib, sino el proceso en sí. Cuando hagas init, o cualquiera de las syscalls que generan un bloqueo, el proceso se va a quedar ahí trabado hasta que llegue a exec, y el proceso va a quedarse en exec y ejecutar hasta que se bloquee o termine
2. Los hilos de la CPU no se crean bajo demanda, sino que están ahí desde que inicia el kernel y no terminan nunca. Haciendo un poco de analogía a un SO real, es como que me digas que este puede materializar mágicamente una CPU, cuando obviamente eso no es así porque son componentes hardware. Es parte de lo que tienen que resolver para el TP cómo le llega a ese hilo el carpincho que le toca ejecutar. Si confunde un poco, capaz con una charla un sábado de soporte sea más dinámico que por un issue del foro :)

**Comment by jlsuh** [comment]
Quedó todo claro. Muchas gracias por las aclaraciones!

Saludos :)
