### ISSUE TITLE
Sobre el fork -safe 

### ISSUE THREAD

**Issue by ospocarpa** [sisoputnfrba/foro#2339]
Buenas 
Sobre el texto citado mas adelante de las limitaciones de matelib 
No me queda claro cual serian esas limitaciones . 

    Esta lib puede no ser fork-safe, porque se permiten File Descriptors abiertos y no se espera que se realice un manejo de los mismos ante un escenario de fork.

    Sin embargo, cada grupo puede optar por evitar esta limitación mediante su propia implementación. Pero no es un requerimiento obligatorio.

-->

Tendra que ver cuando un proceso hace fork , el proceso hijo hereda los file descriptor del padre tal cual como estan ,y podria llegar a tener permisos que quizas no deberia tener ?

**Comment by tferraro** [comment]
👋 Viene por ahí, pero no es por un tema de permisos, sino de que mantiene los archivos abiertos.
Y...como en linux **todo es un archivo**, hay que tener especial cuidado, por ejemplo, al levantar threads y hacer fork.
> Porque al quedar los archivos abiertos, es una potencial región crítica que no taaaan solucionable con semáforos.

_Long Story short_: Como un proceso puede querer hacer uso de fork + hilos; las dependencias como una lib, tienen que tener especial cuidado de contemplar esos casos. A efectos del TP, para no cranear por demás, no es necesario :)

**Comment by ospocarpa** [comment]
Gracias por la explicacion!!!
