### ISSUE TITLE
Ayuda con git push- fatal: Repository '' not found

### ISSUE THREAD

**Issue by EKC-21** [sisoputnfrba/foro#2340]
Necesito ayuda con GITHUB tengo un repositorio en el cual subo cambios periódicamente, pero hace dos días me pidió actualizar el token por que ya había caducado,  resulta que despues de actualizarlo quise hacer un push para mandar mis cambios y dio este error: 
remote: Repository not found.
fatal: repository: 'https://github.com/shisai01/sigesP_EX-2021.git/'not found

### 🔎 Búsqueda en foros
ya intenté varios pasos pero no he podido solucionarlo, ya borre las  credenciales de windows, intenté ya revisé los permisos de lectura y escritura y están habilitados, al ejecutar el comando:
git remote -v me dice;
origin https://github.com/shisai01/sigesP_EX-2021.git <fetch>
origin https://github.com/shisai01/sigesP_EX-2021.git <push>

si intento agregar la ruta con git remote add origin https://github.com/shisai01/sigesP_EX-2021.git me dice que ya existe,
pero al hacer push me dice que no la encuentra

soy nuevo en usando GIT, la verdad no se de que manera se podría resolver o que mas intentar, muchas gracias de antemano

**Comment by RaniAgus** [comment]
Hola, ¿qué tal?
Primero que nada, te comento que este foro es para alumnos/ex-alumnos de UTN FRBA para la materia Sistemas Operativos de Ingenieria en Sistemas de Información.

Dicho esto, ¿probaste con hacer `git pull`? Eso te va a pedir las credenciales, le ingresás el token como contraseña y listo.

Si eso no funciona, fijate de revisar en tu perfil de github si el repo sigue estando, es posible que lo hayas archivado o borrado accidentalmente (yo no puedo verlo porque es privado :P): https://github.com/shisai01?tab=repositories

¡Saludos!
