### ISSUE TITLE
Algunas consultas sobre matelib y Kernel

### ISSUE THREAD

**Issue by matiaspar2000** [sisoputnfrba/foro#2342]
Buenas tardes, tengo varias consultas poco relacionadas, algunas de kernel y otras de la interacción kernel-lib: 

1. En la lib en mate_call_io la función recibe como parámetro un `void* msg. Ahora, ese msg del lado de kernel nunca se usa, mi pregunta es si ese void* es algo simbólico entonces no hay que enviarlo por socket y solo queda del lado de la lib o estoy entendiendo algo mal? Y si hay que pasarselo al kernel dónde se usaría, porque del lado de pedir I/O la consigna no lo menciona
2.  Puede haber una cola de peticiones de la lib para el mismo proceso? Si todavía no se terminó de atender una petición de un proceso es posible que llegue al kernel una segunda petición para el mismo proceso y que esta deba a ir a una cola de espera? 
3.  El estado `EXIT` es para procesos que terminaron su tarea y no tienen nada mas por hacer o para los que se llamó a `mate_close()`? 
4.  Entiendo que la duración de un mate_call_io está dada por la config pero la duración de los pedidos de semáforo y los llamados a memoria de donde la obtengo? Porque por lo que entiendo es necesario saber el tiempo de ráfaga para los algoritmos de planificación. Se supone que hay que calcularla según cuanto tiempo está el proceso en exec o de que manera?

**Comment by gastoncastineira** [comment]
Buenas!

1. Eso creo que está por acá #2312
3. A priori, el EXIT es para todos los procesos que hayan llamado mate_close. Estamos viendo para la errata de agregarlo para los que terminen también, así que estate atento si agregamos alguna aclaración al respecto.
2 y 4. En realidad creo que en ambos el problema es el mismo y es que entendés que lo que se planifica son las llamadas de la biblioteca. Te recomiendo #2338 

Saludos!

**Comment by matiaspar2000** [comment]
Con la 1 y la 3 muchas gracias, quedó claro, muchas gracias

Sobre la 2 medio que todavía no me quedó claro, no hay forma de que un proceso carpincho use una función de biblioteca y antes de recibir la respuesta de la primera use otra? 

Y después por de la 4, se planifique de la manera que sea para los algoritmos voy a necesitar ciertos valores
- La el valor real de la ráfaga anterior para SJF (que será 0 al principio pero después hay q calcularlo)
- El Wait y Service para HRRN

Para el Wait y el valor de la ráfaga anterior ahora pensándola supongo que se puede usar alguna suerte de timestamp, pero para  el service cómo calculo cuanto va a durar una petición que no sea de IO? 

Saludos

**Comment by gastoncastineira** [comment]
> no hay forma de que un proceso carpincho use una función de biblioteca y antes de recibir la respuesta de la primera use otra?

Te devuelvo la pregunta: ¿Se te ocurre alguna manera de que sí? Quiero entender por donde viene la confusión para encaminarte mejor 🤔

> Para el Wait y el valor de la ráfaga anterior ahora pensándola supongo que se puede usar alguna suerte de timestamp, pero para el service cómo calculo cuanto va a durar una petición que no sea de IO?

Tal cual, tienen que usar timestamps para calcular cuanto tiempo estuvo un proceso ejecutando y cuanto lleva esperando. Para el service, te cito la definición de mis apuntes:
>  service time: Duración estimada de la próxima ráfaga CPU

Medio que para el TP ya tienen que usar una fórmula que les estima la duración de la próxima ráfaga, ¿no? 😛

**Comment by matiaspar2000** [comment]
Ok lo de las ráfagas lo entendí. Lo del proceso usando funciones mientras espera la respuesta de otra no se, con hilos en algún escenario particular tal vez?

**Comment by matiaspar2000** [comment]
Ahhh ok entendido, muchas gracias. Cierro hilo
