### ISSUE TITLE
Duda IP y puerto de Kernel

### ISSUE THREAD

**Issue by CarolinaSeoane** [sisoputnfrba/foro#2343]
Hola, tenemos una duda con los archivos de configuración. El enunciado dice que en el archivo config que lee la matelib le tenemos que indicar el puerto e IP de los módulos kernel y memoria. Cuando arranca el kernel, debería obtener el puerto de ese archivo config cargado por nosotros? porque en su propio config no está. Gracias!

**Comment by tferraro** [comment]
Alo!

Sip, la info del puerto e ip del "backend", es info que seguramente para mantener una conexión, la matelib necesite que se le provea por config 🙂
Ahora, la config del Kernel es más orientativa, no es estricta. Pueden agregarlo ahí :)

> El puerto es justo una config que es medio polémica tenerla "configurable" por archivo de configuracion, porque no es algo que quieras cambiar en runtime por lo general y suele ser algo fijo. Por eso no está en la config :)
