### ISSUE TITLE
Consulta semáforos y carpinchos

### ISSUE THREAD

**Issue by danimontesano** [sisoputnfrba/foro#2344]
Hola buenas tardes. 
Tenemos una duda al plantear matelib, ¿es posible que varios procesos puedan compartir un mismo semáforo? ya que en el ejemplo dado se hace un `mate_init(&mate_ref, ...);`, es decir que se crea una instancia de un mate_ref y luego los semáforos se crean justamente utilizando ese `mate_ref `con `mate_sem_init(&mate_ref, "SEM1", 0);` por lo que nosotros intuimos que los semaforos son propios de los `mate_ref`.

Otra duda que tenemos es si un carpincho (proceso) puede generar mas de un `mate_ref` durante su ejecución.

Por ultimo, queríamos pedir si nos podrían explicar a que se refiere la frase "Los procesos en espera se irán pasando a READY en el orden en el que fueron bloqueados uno a la vez. Es decir, por cada post se desbloqueará un único proceso en BLOCKED, respetando el orden de la cola de espera.". Si los `mate_ref` son creados dentro de un proceso, no entendemos como un proceso podría liberar el semáforo de otro proceso. Dejamos un ejemplo de lo que interpretamos:
Tenemos 2 carpinchos. El carpincho 1 crea el semáforo 1 y el carpincho 2 crea el semáforo 2, luego ambos carpinchos se bloquea el carpincho 1 y posteriormente el carpincho 2 (es decir que el carpincho 1 se bloquea antes que el 2) finalmente se hace un post al semáforo 2. Nosotros interpretamos que el enunciado dice que deberíamos desbloquear al carpincho 1, sin embargo creemos que esto no tiene sentido ya que el post fue realizado al semáforo del carpincho 2.
Creemos que en todo caso lo único que tendría sentido seria que ambos carpincho se bloqueen por el mismo semáforo. Y luego al hacerse un post se desbloquee el 1. Sin embargo, por lo que vimos en el ejemplo el semáforo está ligado al `mate_ref` y el `mate_ref` es creado por un proceso en particular, por lo que no sabríamos como hacer para que los carpinchos compartan un semáforo.

### 📔 Citas del enunciado/videos

> Si un proceso hace, mediante uso de la lib, un mate_sem_wait a un semáforo con valor menor a 1, este deberá pasar a bloqueado hasta que el semáforo se libere con mate_sem_post. Los procesos en espera se irán pasando a READY en el orden en el que fueron bloqueados uno a la vez. Es decir, por cada post se desbloqueará un único proceso en BLOCKED, respetando el orden de la cola de espera.

**Comment by ncoen97** [comment]
Buenas! Paso a enumerar las dudas así queda más ordenado.
1. Es posible que se puedan compartir porque los semaforos, a fin de cuentas "viven" en el modulo kernel. La `mate_ref` es meramente una estructura interna de la lib que uds van a usar para guardar la información que necesiten (como por ejemplo info sobre las conexiones).
2. La verdad no veo ninguna razón por la que no se pueda. Mientras por cada `mate_ref` se haga un `mate_init()` no debería haber problema.
3. Si, el bloqueo aparecería si se hace un `mate_sem_wait()` del mismo semáforo. Lo que uds vieron en el ejemplo de implementación de la lib es más que nada una "implementación local" que dejamos para que se entienda a que apunta cada función, pero en realidad uds van a tener que desarrollar esas funciones a nivel sistema (por ejemplo las funciones de semaforos las atiende el kernel, las de memoria se pasan al módulo de memoria, etc). En conclusión, la matelib quedaría más que nada como un manejador de conexiones con el sistema que van a desarrollar. 

Saludos.

**Comment by danimontesano** [comment]
Entonces los semáforos **no** estarían ligados a un `mate_ref`? es decir, yo podría hacer un `mate_sem_init(&mate_ref, "SEM1", 0);` y luego un `mate_sem_post(&mate_ref2, "SEM1");` (en un caso se usa `mate_ref` y en el otro `mate_ref2`) y los dos estarían usando el mismo semáforo?

Porque nosotros habíamos pensado que cada `mate_ref` tenga en su estructura una lista de semáforos a la que está asociado. Pero por lo que puedo entender ahora el `mate_ref` se usaría mas que nada para poder establecer las conexiones.

Nosotros habiamos planteado que cuando se hace un `mate_init(3)` el kernel lo tomaría como que se estuviera creando un nuevo proceso a administrar (un proceso llegando a _new_). Pero por lo que vemos ahora un proceso puede tener varios `mate_init(3)`. Entonces... como deberíamos interpretar a los `mate_init(3)`? Porque en el enunciado dice que cuando se realiza uno debemos generar las estructuras necesarias y eso. Como que los procesos que quedan bloqueados estarían ligados con el `mate_ref` generado con el `mate_init(3)`.

Disculpen si los mareé un poco, espero que se haya entendido mi duda.
Muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

Justo eso de que los semáforos no están ligados a un proceso, si no que son globales lo aclaramos en la v1.1 del enunciado 😉 
Gracias por la pregunta que nos hizo darnos cuenta que no habíamos sido claros en ese punto 😄 

Saludos.-

**Comment by ncoen97** [comment]
Buenas @danimontesano! Quedaron resueltas las dudas? Podemos cerrar el issue?

**Comment by danimontesano** [comment]
Disculpen la demora.
Leyendo el enunciado v1.1 ahora veo que los semáforos se ven de forma "global" para matelib ya que serán definidos dentro de kernel. Sin embargo, no me termina de quedar claro porque debemos pasarle un `&mate_ref` a la hora de inicializarlos con `mate_sem_init(3)`. ¿Es para poder administrarlo con el planificador de corto plazo? es decir, que le llega como una tarea que se debe planificar, estoy en lo correcto?

**Comment by tferraro** [comment]
👋 Alo!
Pensá que en realidad, lo que estás planificando no es el proceso carpincho, sino la instanciación y habilitando al proceso que tiene la instancia a correr o no.

Podrías, tranquilamente tener un mismo proceso haciendo uso de 2 semaforos en 2 instancias distintas de la init de la matelib (por ejemplo, en distintos threads).
Si no le pasas la instanciación de esa lib, como sabrias a cual "PCB" bloquear desde la planficación? Al init1 o init2?

**Comment by danimontesano** [comment]
Genial! muchísimas gracias. Nos quedó más claro. 
Cierro el issue.

**Comment by iago64** [comment]
Creo que le pifiaste al botón, igual tranqui, ya lo cerramos 😉
