### ISSUE TITLE
Duda HeapMetadata

### ISSUE THREAD

**Issue by MatiasRosales** [sisoputnfrba/foro#2345]
Buenas, tengo un par de dudas sobre el heapMetadata
![image](https://user-images.githubusercontent.com/37908304/134825901-366b2c3a-5394-4e64-be6c-7ad353da0049.png)

Siguiendo este ejemplo, primero se realiza un alloc de 11B para un proceso A, entonces se enlista una nueva pagina (la primera) en la tabla de paginas de A donde se almacenara 9B por el heapMetadata nuevo + los 11B allocados.
1) ¿El heapMetadata creado tendra como prev_alloc y next_alloc en null al tratarse de un unico alloc o se deberia crear otro para que apunte a un alloc del espacio sobrante (quedando un 2do alloc y 3B libres )?
2) Al recorrer los allocs de un proceso, como podria saber de cuanto es el alloc encontrado? Lo que tenia pensado hacer es agregar un campo auxiliar para determinar el tamanio del alloc al que se analizara en una iteracion de una lista de heaps de un proceso y procedo a dividirlo

Gracias 

Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- En el primer ​`HeapMetadata​` de todo tu proceso vas a tener el prev_alloc en null (porque no tenes ninguno previo) y el next_alloc en la posición final de tu reserva donde vas a tener _otro_ `​HeapMetadata​` que va a representar todo el espacio vacío restante y lo va a marcar como libre. Después cuando llegue el siguiente ahí si vas a tener que completar el valor del segundo ​`HeapMetadata`​ y crear un 3ro (para que te quede como el del ejemplo)

2.- Es parte del problema que uds tienen que resolver, pero una pista que podes tener es que la posición de tu alloc y el del next_alloc para hacer la cuenta.

Saludos.-

**Comment by MatiasRosales** [comment]
perfecto!

Muchas gracias!
