### ISSUE TITLE
Duda representacion Memoria

### ISSUE THREAD

**Issue by TomasR264** [sisoputnfrba/foro#2346]
Buenas!

Estamos en duda de como representar la memoria principal que va a estar dividida en paginas, por que no sabemos cual seria el correcto, o si ambos son validos

Por un lado pensamos hacer de la memoria principal un vector del tamaño que especifique el .config, y dividirlo a su vez en vectores mas pequeños de igual tamaño para representar las paginas. Quedandonos asi un vector grande con varios vectores mas pequeños dentro.

Y por otro lado pensabamos en una lista doblemente enlazada para representar la memoria principal, compuesta por vectores del tamaño que especifique el .config

Gracias y saludos 🚀

**Comment by iago64** [comment]
Buenas! Cómo va?

La forma correcta de hacer el tema de la memoria principal es haciendo 1 solo `malloc()` del tamaño de la memoria definida por config y luego valiéndose de aritmética de punteros van a poder desplazarse dentro de ese espacio de memoria que reservaron al principio.

Después para administrar ese espacio de memoria pueden tener estructuras que contengan *información administrativa*, no los datos.

Saludos.-

**Comment by TomasR264** [comment]
Ahh, listo muchas gracias!
