### ISSUE TITLE
duda sobre los contadores y memfree

### ISSUE THREAD

**Issue by alejcha** [sisoputnfrba/foro#2347]
1) en la parte del enunciado donde pide mostrar

> Cantidad de TLB Hit totales
Cantidad de TLB Hit por proceso indicando proceso y cantidad.
Cantidad de TLB Miss totales.
Cantidad de TLB Miss por proceso indicando proceso y cantidad.

Hit/miss totales es desde que inicio el sistema? o solo de los procesos en ejecución en el momento (la sumatoria de hit/miss de todos los procesos)?
mismo por proceso, hay que guardar el historico de procesos, o es solo los en ejecucion?

2) El carpincho siempre enviara un memfree de toda la memoria alocada? o puede mandar liberar por ejemplo desde la mitad?
o sea, por ejemplo solicita alocar 10 bytes, y se le devuelve la direccion 20, no va a mandar memfree (25) ni debemos considerar ese escenario

gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Si, los totales son desde que inició la memoria hasta que finalizo esa ejecución, idem para los Hit / Miss por proceso.

2.- Vamos por partes acá:
- El free no recibe el tamaño, recibe un "puntero", es parte de su solución cambiar el 
- Puede ser que les lleguen direcciones erróneas (por ej un free de una dirección inválida) y uds van a tener que responder en consecuencia (esto igual lo vamos a aclarar un poco mas en la próxima errata)

Saludos.-

**Comment by alejcha** [comment]
Buenas, gracias!
Aclarado el punto 1

En el 2 cuando me refería a
memfree(25) me refería a un puntero que apunta a 25
O sea que pide liberar no desde el principio del alloc sino, supongamos, en
"la mitad"

Si se puede hacer eso, y deberíamos "dividir" el espacio ya alocado podria
no haber espacio para otro heapmetadata, y tampoco se podría mover a otro
lugar porque cambiaría la dirección

Entonces, la duda es, si el carpincho siempre va a liberar el puntero
alocado Y no una otra dirección (dentro de esa alocación)

Muchas gracias

**Comment by alejcha** [comment]
otra duda "de yapa"
la lectura/escritura del heapmetadata en la memoria creada, por ejemplo, lectura durante el recorrido para buscar un hueco, o en la actualizacion de estado, o alocacion, pasa por la TLB tambien?
o los accesos "administrativos" de memoria se hacen por fuera (y sin delay) y la TLB se utiliza exclusivamente para peticiones hechas por los carpinchos
y en caso que la pagina donde este un heapmetadata necesario para recorrerlo este en swamp, tengo que cargar/swapear el frame a memoria para poder leerlo, contando como un fallo de pagina verdad?

**Comment by iago64** [comment]
Buenas! Cómo va?

Respecto al tema del memfree(), la idea es que funcione de la misma forma que si haces un free() tradicional de C, si el puntero no es un puntero válido que se queje, igual vamos a estar ajustando eso para una próxima errata como para estandarizar los mensajes de error :)

Duda de yapa 1: Mucho cuidado con eso, porque los heapMetadata están dentro de los datos, no deberían estar en estructuras administrativas, por lo que, es un acceso a las páginas siempre.

Duda de yapa 2: Efectivamente, si tenes algo en TLB y no sale nunca es porque le están lloviendo pedidos, no deberías reemplazarlo.

Saludos.-

**Comment by alejcha** [comment]
Gracias, aguardo entonces la proxima errata para ver el tema de las respuestas
sisi, entiendo que todo se lee de la "memoria" directamente, perfecto, gracias por las aclaraciones
