### ISSUE TITLE
Dudas envió de datos al modulo swamp

### ISSUE THREAD

**Issue by heinHertz** [sisoputnfrba/foro#2348]
Hola mando mis dudas actuales un poco sobre la dinámica de swamp y memoria:

1) estoy entendiendo que la  memoria trabaja con paginas que tienen el formato:
![image](https://user-images.githubusercontent.com/37560557/134994905-505f5ac2-8916-4f2a-b014-0f591665d839.png)

como pide memoria una pagina a swamp ?  por ejemplo estoy pensando en armar ( en el modulo swamp) una lista de estructuras donde  tiene un entero (seria el numero de pagina) y un puntero a los datos en los archivos ? ( estos no se persisten están en la RAM "de apuntadores" pero los files no tienen estos datos. solamente las paginas
 otra forma seria persistir de alguna manera la pagina en los archivos( es decir un entero junto con los datos de las paginas y cada vez recorrerlos para determinar que pagina es, para eso hay también hay que almacenar el nro de pagina y el proceso también( por ej, con otro entero )  junto con la pagina.

2) en la hoja 20 del enunciado hablan de mmap, según entiendo mapea datos que están un sector (de un puntero) de la memoria RAM y los almacena en un archivo. estoy seria conveniente para por ejemplo cuando memoria manda la pagina a swam( y la recibe en la RAM) y mmap la pasa al archivo ?

gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Ojo con "el formato de las páginas" porque si vos tenes páginas de 32 bytes y yo te hago un `memalloc()` de 150 bytes, vas a tener páginas que no van a tener nada mas que bytes que no sabes (ni te interesa) lo que son. Por lo tanto **el intercambio de datos entre memoria principal y SWAP es siempre por páginas enteras**.

2.- `mmap()` funciona al revés de como lo estas diciendo, toma un archivo y lo "mapea" a memoria y te devuelve un puntero al cual vos podes hacerle `memcpy()` y de alguna manera que _no te importa_ hace que lleguen tus datos al archivo.

Saludos.-

**Comment by heinHertz** [comment]
estoy viendo el issue  #2331  y me dio la duda : 
´´´
 Asignación fija: todas las páginas del proceso van a quedar juntas, por ej: 1-1-1-1-1-2-2-2-2-2-5-5-5-5-5-3-3-3-3
Asignación variable o global: Las páginas pueden intercalarse, por ej: 1-2-1-2-1-1-1-5-5-3-5-1-2
´´´
a) En el caso de Asignación Fija, si por ejemplo en un momento Swamp tiene almacenadas la paginas asi: 1-1-2-2 , si hacen falta agregarle 2 paginas de un proceso 1, entonces Swamp tiene que mover  2 -2 "al fondo" para agregar una pagina del proceso 1 para quedar 1-1-1-1-2-2  ?   con al fondo me refiero a mover las paginas 2 -2 al siguiente marco continuo  una vez colocadas 1 -1 , dentro de mi bloque de bytes que representa el bin ?
b) En el caso de Asignación variable simplemente agrego la pagina al primera pagina libre en el Swamp ?

**Comment by iago64** [comment]
Buenas! Cómo va?

A.- No hace falta, en el ejemplo la manquie con los 3 del final y me falto uno, la idea es que uds reserven de una todos los frames que puede almacenar su proceso en swap de una, por eso cambiamos el nombre del parámetro para dejarlo mas claro 😉 

B.- Si, la idea es que en asignación variable el swamp sea una mera extensión de la memoria, con un poco de delay extra :)

Saludos.-

**Comment by heinHertz** [comment]
a) Ahora entiendo, simplemente pide de una  cantidad fija MARCOS_POR_PROCESO ( parámetro configurado en swamp ),  OK. 
b) me quedo claro

otra duda, estuve leyendo 
´´´
Habrá dos esquemas de gestión para la gestión de las páginas en swap, los cuales irán en función del esquema de asignación de páginas que haya en la memoria.
´´´
asumo que la memoria tiene se lo tiene que pasar al Swamp para trabajar el dato de la asignación, eso seria algo  que se haga de una vez, ?o sea,  la asignación fija o global es algo que queda como permanente de una vez asignada, queda asi en todo el ciclo del funcionamiento del sistema?

gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

Efectivamente, la memoria se lo va a tener que notificar al Swamp en algún momento, idealmente eso puede ser cuando se conectan inicialmente :)
Después quédense tranqui que no va a cambiar hasta que se bajen las aplicaciones y se vuelvan a levantar 😄 

Saludos.-

**Comment by dhuallpa** [comment]
Hola buenas me surgio una duda, segun tengo entendido en asignacion fija en swap: si tengo MARCOS_POR_PROCESO=5 y mi archivo swap tiene para almacenar 64 paginas entonces: 11111222223333344444 y asi sucesivamente pero que pasa con
las 4 paginas que quedan dado que use 60/64, las dejo y uso el siguiente archivo swap  o los MARCOS_POR_PROCESO tiene que ser un nro divisor de la cantidad de paginas?
