### ISSUE TITLE
Algunas dudas sobre el Kernel

### ISSUE THREAD

**Issue by gabycosta04** [sisoputnfrba/foro#2349]
Hola buenas teníamos algunas dudas con respecto al modulo Kernel:

- 1 ¿En caso de que un proceso haga un sem_destroy, que deberíamos hacer si hay varios procesos que quedaron bloqueados en el semáforo por realizar sem_wait y todavía no hicieron sem_post para liberarlos? Deberíamos sacarlos de la lista de bloqueados y ponerlos en ready y eliminar el semáforo o que otra alternativa podríamos plantear?
- 2 ¿Conviene tener una lista de procesos en EXIT, onda para tener alguna referencia histórica de ellos, o con eliminarlos ya estaríamos?
- 3 ¿ El tema de la suspensión de un proceso, entendemos que se deben dar las condiciones en las colas de ready, blocked y new.... pero se debe analizar suspender un proceso solo si el grado de multiprogramación esta lleno? o en que casos conviene mandarle una señal al planificador de mediano plazo para que analice tales condiciones de suspender un proceso? O este planificador podria analizar todo el tiempo si se cumplen tales condiciones?
- 4 ¿Desde Kernel, por cada proceso que tengamos, necesitaríamos ademas tener también una conexión abierta con memoria en caso de que el proceso solicite algo en memoria? o en este caso podríamos abrir una conexión en el momento y cerrarla despues de pedir lo que necesitábamos a memoria?
- 5 ¿ El tema de deadlock, el algoritmo de detección y recuperacion en la teoría menciona que se ejecuta con cierta frecuencia, con cuanta frecuencia debería ejecutarse en el caso del TP?
- 6 ¿En el config no lo vimos, pero debemos suponer que el puerto al que se conectan los carpinchos va a venir directo en el config?

**Comment by gastoncastineira** [comment]
Buenas! 

1. Creo que esto quedó claro con la nueva errata. Los semáforos son globales y compartidos por todos los carpinchos
2. Para este TP creo que es indistinto, total no hay forma de consultar las colas
3. Es que, justamente, si tenés cosas en BLOCKED, nada en READY y otras cosas en NEW, quiere decir que los procesos en BLOCKED te están comiendo todo el grado de multiprogramación y el overhead de las CPUs en 100%. EL proceso de planificación debería ser lo más sincrónico posible, eso de "analizar todo el tiempo" me huele a espera activa y eso estaría mal
4. Tema de diseño a definir por cada grupo, y a explicar y justificar en sus coloquios. Ambas alternativas son válidas
5.  Eso lo corregimos en la errata
6. Esto también lo corregimos en la errata

PD: Gracias por enumerar las preguntas y hacer nuestro trabajo más fácil

**Comment by gabycosta04** [comment]
> Creo que esto quedó claro con la nueva errata. Los semáforos son globales y compartidos por todos los carpinchos

Si eso lo teníamos entendido, pero el tema que nos surge duda es que supongamos que hay varios carpinchos bloqueados en un semaforo1. Y luego otro proceso que ejecuta hace un sem_Destroy del semaforo ese, deberíamos:
- Esperar a que se hagan sem_post y eliminar el semáforo cuando no haya nadie en la lista de bloqueados del semáforo?
- O deberíamos eliminar el semáforo y poner a todos los procesos que estaban en esa lista de bloqueados en ready??

**Comment by gastoncastineira** [comment]
Buenas!

Si miramos el man de semaphore

>Destroying a semaphore that other processes or threads are currently blocked on (in sem_wait(3)) produces undefined behavior.

No tiene mucho sentido definirles algo que ni el propio kernel de Linux pudo definir, así que no va a ser una prueba. Con que el TP no explote por los aires cuando pase nos alcanza

**Comment by gabycosta04** [comment]
Dale perfecto me quedo entendido y gracias!
