### ISSUE TITLE
Atributos de Struct mate_instance

### ISSUE THREAD

**Issue by lalvarez-utn-frba** [sisoputnfrba/foro#2350]
Hola!
Queríamos saber si los procesos carpincho van a acceder a alguno de los datos dentro de este struct (mate_instance) o es libre de implementación por cada grupo. 
¿tenemos que respetar el atributo `void* group_info` (poner todo lo que necesitemos ahí) o directamente podemos poner los datos como parte del struct?

**Comment by tferraro** [comment]
Buenas!

Es un `void*` porque "puede ser lo que quieran", así que pueden referenciar a un puntero a una estructura propia, hacer un type casting y presto!

La posta de porque no va en la estructura original, es porque si la "redefinis" dependes del orden que lo tome el compilador para ver cual elije primero. Y les puede traer varios problemas de compilación en momentos no tan copados.
La idea de la estructura anterior era porque las libs por lo general proveen un type "wrapper" que evita romper el encapsulamiento del comportamiento de la lib contra sus users 😉
