### ISSUE TITLE
Múltiples mate_init en un mismo proceso carpincho

### ISSUE THREAD

**Issue by jlsuh** [sisoputnfrba/foro#2351]
Muy buenas a todos :)

Según el [apartado de la consigna](https://github.com/sisoputnfrba/matelib#mate_instance):
> "La instancia será útil para referenciar distintos inits que se pueda hacer en un mismo proceso".

Estimamos que un mismo proceso carpincho podría hacer algo como:
```c
int main(void) {
    mate_instance mateRef1;    // carpincho 1
    mate_instance mateRef2;    // carpincho 2
    mate_init(&mateRef1, "cfg/carpincho.cfg");
    mate_init(&mateRef2, "cfg/carpincho.cfg");

    mate_sem_init(&mateRef1, "SEM1", 0);
    // ...
    // Otras wrappers que sean invocadas solamente por mateRef1
    // ...
    mate_sem_init(&mateRef2, "SEM2", 0);

    // ...

    return 0;
}
```
### Nuestro modelo actual
Consideramos hasta el momento que un "módulo carpincho" se relaciona 1:1 con un pcb que ronda por el sistema (habiendo solamente un `mate_init` en el main). Al momento en que un proceso carpincho establece una conexión con el backend pasa a ser un nuevo pcb del sistema en estado new.

#### Cómo nos comunicamos con un carpincho
Suponiendo que el carpincho se encuentra en exec:
1. Kernel le envía un `ok_continue` al carpincho para que el carpincho se desbloquee.
2. El carpincho le envía la siguiente petición a procesar.
3. Kernel retorna un resultado

Este ciclo ocurre hasta que llegue una petición bloqueante o en su defecto un `mate_close`.

### Dudas
En caso de que un `mate_instance` se relacione 1:1 con un `pcb` (visto desde el lado del sistema), entonces puede llegar a pasar que un mismo main posea 2 carpinchos como en el ejemplo antemencionado (debido a que se crea 1 pcb por cada `mate_instance`).
En base al ejemplo dado: se nos ocurre que cuando mateRef1 (carpincho 1) y mateRef2 (carpincho 2) pasen de ready->exec (siempre y cuando el grado de multiprocesamiento lo permita), el mateRef1 (carpincho 1) puede sin problemas desbloquearse (debido a que recibió un código de operación del estilo `ok_continue` por parte del servidor), enviando la siguiente petición a procesar al backend (siendo el mismo un `mate_sem_init`). No obstante, debido a que solamente hay 1 flujo de ejecución (el hilo principal), el mateRef2 no podría recibir su `ok_continue` (en forma paralela, en caso de que el grado de multiprocesamiento sea mayor estricto a 1) para que se pueda desbloquear del recv bloqueante y posteriormente enviarle la siguiente petición a procesar al backend (siendo el mismo un `mate_sem_init`).

En este caso no se nos ocurre cómo podría hacer que el mateRef1 (carpincho 1) y mateRef2 (carpincho 2) tengan ejecuciones diferidas (para que la ida (backend->carpincho: permisos para continuar su ejecución) y vuelta (carpincho->backend: peticiones a procesar) sea posible), salvo que tengamos un contrato débil de emplear a cada mateRef en un flujo de ejecución distinto a cualquier otro mateRef del mismo proceso carpincho.

La otra alternativa que se nos ocurrió es que solamente puedan haber casos en donde se "balanceen" los `mate_init` con los `mate_close`, siendo el mismo:
```c
int main(void) {
    mate_instance mateRef1;    // carpincho 1
    mate_instance mateRef2;    // carpincho 2

    mate_init(&mateRef1, "cfg/carpincho.cfg");
    mate_sem_init(&mateRef1, "SEM1", 0);
    // ...
    // Otras wrappers que sean invocadas solamente por mateRef1
    // ...
    mate_close(&mateRef1);

    mate_init(&mateRef2, "cfg/carpincho.cfg");
    mate_sem_init(&mateRef2, "SEM2", 0);
    // ...
    // Otras wrappers que sean invocadas solamente por mateRef2
    // ...
    mate_close(&mateRef2);

    // ...

    return 0;
}
```
pero no sabríamos si realmente esto pasará en las pruebas que se nos aporte.

Queríamos saber si será posible recibir algunas indicaciones para saber hacia dónde ir apuntando desde el vamos.

Muchas gracias de antemano :)
Saludos!

**Comment by gastoncastineira** [comment]
Buenas!

No va a ser una prueba poner varios mate_init dentro de un mismo hilo. Sí podría ser una prueba (y de hecho, es un requerimiento de matelib soportarlo) el hacer un init por cada hilo que decidan abrir los procesos

Saludos!
