### ISSUE TITLE
[MateLib-Procesos Carpinchos] Dudas sobre ejecutables y semáforos que manejan

### ISSUE THREAD

**Issue by federiver91** [sisoputnfrba/foro#2352]
Buenas! Genero el issue por unas consultas que nos surgen en relación a los ejecutables (carpinchos) externos a nuestra implementación.

1) Un Carpincho es un ejecutable? Es una relación uno a uno? O un ejecutable tiene la posibilidad de generar múltiples hilos de Carpinchos?

2) En cuanto a los semáforos que los Carpinchos inicializan mediante las funciones de la libreria, se deben guardar en memoria como alguna variable propia del carpincho? El Carpincho puede crear "infinitos" semáforos mediante las funciones correspondientes, si quisiera?

Por ahora, sólo eso saqué en limpio.

Saludos,
Federico

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- No necesariamente, pueden tener el caso de un ejecutable que haga un pthread_create() y dentro de ese hilo se haga otro mate_init() para tener "otro carpincho", pero eso esta la recomendación de que usen un identificador único para cada carpincho.

2.- Los semáforos viven en el kernel, con lo cual ahí pueden guardarlos como gusten (por ejemplo una lista o un diccionario), no tienen que guardarlos en la memoria. Respecto a la cantidad, si, un carpincho puede crear infinitos semáforos.

Saludos.-

**Comment by federiver91** [comment]
Ok, gracias!
