### ISSUE TITLE
Posibilidad de sobrepasar el valor inicial del semáforo

### ISSUE THREAD

**Issue by neverkas** [sisoputnfrba/foro#2356]
Muy buenas,
teníamos una consulta sobre los valores iniciales de los semáforos y los posibles casos en donde se sobrepase el valor inicial.

Suponiendo que tenemos un caso en donde un carpincho invoca `mate_sem_init(mateRef, "SEM1", 10)`.
En caso de que otros carpinchos hagan el `mate_sem_post(mateRef, "SEM1")` tal que sobrepase al valor inicial del semáforo (> 10): ¿habría que restringir dichos `mate_sem_post` de los N - 1 carpinchos debido a que no es un comportamiento que desee el carpincho que inicializó el semáforo? ¿O no habría restricciones sobre el valor que puede llegar a tomar un semáforo respecto de su valor inicial?
Vimos por la teoría que tanto `sem_post` como `sem_wait` incrementan y decrementan el valor respectivamente, en donde se hace la validación del valor en que quedó luego de dicho efecto. No obstante, queríamos saber si habría que respetar el valor inicial en el cual fue inicializado por el carpincho y no sobrepasar de dicho valor.

**Comment by gastoncastineira** [comment]
Creo que te respondiste solo
Si el enunciado no lo pide, no hace falta contemplarlo. No somos tan enroscados

**Comment by neverkas** [comment]
Perfecto, gracias por confirmar
