### ISSUE TITLE
Duda conceptual de memoria

### ISSUE THREAD

**Issue by JuradoMatias** [sisoputnfrba/foro#2357]
Bueenas! como va? quería consultarle una cosita.

-Status
Me toco una parte del modulo de memoria.

-Cosas que hacer
desarrollar las funciones de los headers de las funciones de memoria (mate_lib)
guardar los heap_metada DENTRO de la memoria, como así los DATOS que interesan

-Hipótesis
soy libre de crear las estructuras administrativas (y funciones para manejarlas) que se me ocurran, mientras que cumpla lo de guardar esa info dentro de memoria puedo tener una estructura general administrativa que me indique que cosa se encuentra en tal lado de la memoria SIN guardar DATOS en dicha estructura, pero si ubicaciones (Direcciones lógicas). Como por ejemplo, saber responder que bytes estan libres dentro de las paginas de tal carpincho (proceso)

estoy en lo correcto, o hay alguna limitante?

Saludos!

**Comment by gastoncastineira** [comment]
Buenas

La hipótesis queda demostrada por el método de "ayudante respondiendo issue". La inducción te la dejo de tarea

**Comment by JuradoMatias** [comment]
jajaja perfecto. Era lo que necesitaba por el momento. Ya volveré con mas dudas puntuales. Gracias. Cierro el issue.
