### ISSUE TITLE
Duda con memfree y acceso a TLB

### ISSUE THREAD

**Issue by alejcha** [sisoputnfrba/foro#2359]
Buenas tardes
tengo una duda sobre como se realizaran las pruebas y resultados esperados al presentar el tp, ya que para resolver memfree(puntero) las opciones que tengo para garantizar que sea un puntero valido son recorrer los heapmetadata desde la estructura de memoria (generando accesos a TLB y posibles swap) lo que puede resultar en diferencias con respecto a lo esperado en las pruebas. Alternativa guardar las direcciones logicas alocadas en un vector/lista, lo que haría que el heapmetadata casi que no tenga propósito.

En caso de la cuenta de TLB Hit, yo pensé en traducir de a un byte, o sea si manda a leer un int "que está" en TLB serian 4 hits, mismo, no se si en las pruebas esperan un cierto valor de hit/miss, y si coincide o no con mi estrategia.

Puedo elegir la que me parezca mas adecuada y luego justificar las diferencias entre lo esperado en las pruebas con la estrategia de la implementación?

Gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

Creo que estas dándole una vuelta de rosca de mas y no es la idea, nosotros nos vamos a tomar todo el tiempo del mundo de hacer las cuentas para saber que reemplazos se tienen que dar en que momento, por es que en el enunciado les pusimos que para la elección de huecos en caso de los `memalloc()` usen el primero libre 😉 
Por otro lado, no te preocupes que las pruebas se van a publicar con tiempo para que las puedan revisar, correrlas y en todo caso si notan algo raro nos avisen 😄 

Abrazo a la distancia!

**Comment by alejcha** [comment]
gracias!
Abrazo
