### ISSUE TITLE
Primer intento de integración conceptual - mate_init

### ISSUE THREAD

**Issue by JuradoMatias** [sisoputnfrba/foro#2361]
Buenas, como va?

Por lo que entiendo la funcion `mate_init()` lo ejecutará el **carpincho X** y éste (mediante la biblioteca) lo recibirá **kernel** (únicamente, no puede ser iniciado un carpincho si el **kernel** esta muerto). Pero mi duda es, el **kernel** despues de administrarlo/planificarlo(LP), debe mandar a **memoria** su `pid`, no?

luego, si esta pregunta es un si. Debo o, mas bien puedo, asignarle una **pagina vacía** al carpincho? ese nro de pagina inicial lo puedo poner como una variable del _arch de config_?

> `abrazo!`

**Comment by JuradoMatias** [comment]
ah okey, a la memoria lo tomé como un recurso. Y un proceso no podría pasar de ready a exe (el memalloc() ) sin tener sus recursos listos. Además me sonó rara la posibilidad de que inicie un carpincho y se finalice sin haber pedido ni una pagina de memoria (o un byte, pero no le puedo dar menos de una pagina), con lo que le ahorraría el tiempo cuando lo solicite de verdad.

Igual no me cambia hacer una cosa o la otra, asi que voy por la de reservar memoria solamente si se hace un llamado a memalloc().

Perfecto, tenia esa duda porque el tp dice que memoria no entiende el mensaje de mate_init() y me hacia ruido que memoria no sepa de la creación de un carpincho, por eso me tenté a guardarle una pagina al menos para que se encuentre presente.

Genial, una pregunta para después. Si tengo una duda especifica dentro de mi resolución del tp, comparto un pedazo del codigo para que sepan de que linea estoy hablando y ustedes lo ven desde el github no? digo para no esperar para los sábados y acostumbrarme a utilizar mas esto (el foro).

Gracias!
Saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

El tema del pid es algo que pueden manejar en el handshake al momento de conectarse, la idea es que el kernel sea el que les de el pid, pero si en el handshake "se dan cuenta" que están hablando con la memoria, pueden hacer que les "genere" un pid, es una licencia poética que se pueden dar ya que es algo que no especificamos en el tp y por lo tanto tienen de libertad para pensar una solución que les sea **fácil de implementar** (Por favor, no queremos que se quemen con eso)

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @JuradoMatias ! ¿Quedó alguna duda con la respuesta de Dami? De no ser así, recuerden que pueden cerrar el issue. Saludos

**Comment by JuradoMatias** [comment]
Buenas! sisi todo perfecto! En realidad estaba esperando que Luis que comento después que yo aclare que tambien esta todo bien. Bueno lo cierro y de última hace referencia a este issue.
Gracias!
