### ISSUE TITLE
Concurrencia en el módulo Memoria

### ISSUE THREAD

**Issue by Patricio-Galli** [sisoputnfrba/foro#2363]
Tengo dos preguntas en este tema:
1. ¿El acceso a la TLB puede realizarse por más de un carpincho a la vez?
El problema podría surgir ante un TLB miss, ya que entonces aparecería una actividad de escritura, o cuando se haga un swap out de una de las páginas mencionadas en las entradas de la TLB.

2. ¿El sistema debería permitir que los carpinchos accedan a la memoria a la vez? Suponiendo que sí:
¿Estoy en lo correcto si digo que las acciones de asignar página, liberar página, swap in y swap out deberían tener mutua exclusión?
Problemas de condición de carrera que se me ocurren:
Cumpliendo la asignación de memoria, decido que voy a utilizar cierto marco a la vez que un proceso decide hacer swap in al mismo marco.
De la misma manera, podría ocurrir al tratar de asignar un marco de la swap y que se esté haciendo un swap out en el mismo marco.
Respecto de la liberación de páginas, no lo veo necesario aunque conveniente.
Y sobre los swaps entre sí, eso es forzado al haber un solo socket de comunicación entre la SWAP y la MEMORIA.

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Si, puede darse y por eso uds tienen que sincronizar los accesos a la TLB.

2.- Si, la memoria al manejar múltiples hilos tiene que poder atender a todos los carpinchos de manera concurrente, ya que hay partes en las cuales como bien decís, tienen que tener mutua exclusión para no hacer cagadas.

Bonus track: Los accesos a SWAP los tienen que sincronizar porque swap puede atender de a 1 pedido a la vez 😉 

Saludos.-
