### ISSUE TITLE
[MateLib] Funcion memwrite

### ISSUE THREAD

**Issue by federiver91** [sisoputnfrba/foro#2364]
Buenas!! Cómo andan??

Estoy viendo tanto la declaración como el ejemplo de implementación y uso de la función de mate_lib "mate_memwrite".

**_int mate_memwrite(mate_instance *lib_ref, void *origin, mate_pointer dest, int size);_**

La consulta es la siguiente:

Cuando nos llamen con esa función, debemos tomar el argumento "size" SIEMPRE E INDEFECTIBLEMENTE como el size real (en bytes) que ocupa la variable apuntada por el puntero origin? 

Gracias,
Federico

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, aunque si quedó alguna duda por supuesto pueden reabrirlo o abrir uno nuevo. Saludos
