### ISSUE TITLE
Suspensión Planificador de Mediano Plazo

### ISSUE THREAD

**Issue by neverkas** [sisoputnfrba/foro#2373]
### Referencias al enunciado
Referencia sobre los planificadores
> Este módulo tendrá tres planificadores distintos. Uno de largo plazo, uno de corto y uno de mediano
> plazo. Cada planificador correrá de manera independiente a los otros con su propio algoritmo.

Referencia del Planificador de Mediano Plazo
> Para que un proceso entre en suspensión se deben cumplir simultáneamente las siguientes condiciones:
>  ● Que haya procesos en BLOCKED
>  ● Que no haya procesos en READY
>  ● Que haya procesos en NEW

### Nuestro planteo
Estamos planteando la suspensión de los procesos del planificador de Mediano Plazo, pero nos topamos con 
dos escenarios de en que momento deberíamos analizar la suspensión de los procesos
1. Desde el hilo del planificador_largo_plazo notificarle al planificador_mediano_plazo que analice (suponemos que quizás se pierde la "independencia" entre planificadores)
2.  Un loop infinito que provoca espera activa para chequear las condiciones dadas (hay_procesos_bloqueados, no_hay_procesos_en_ready, hay_procesos_en_new)
3. en el  código que presentamos abajo

### Código de referencia

```C
for(;;) {
  // 1er escenario donde el planificador de largo plazo, le notifica al de mediano plano
  sem_post(&despertar_mediano_plazo);
  sem_wait(&suspension_concluida);

  // Planificador a la espera de nuevos proceso en new ó bien en suspended/ready para pasarlos a ready
  sem_wait(&hay_pcbs_para_agregar_al_sistema);
  log_info(kernelLogger, "Largo Plazo: Se toma una instancia de PCBs disponibles para agregar al sistema");

 // 3er escenario si no hay procesos para agregar al sistema, pero hay procesos bloqueados para ser suspendidos
// sem_post(&despertar_mediano_plazo);
// sem_wait(&suspension_concluida);

  sem_wait(&gradoMultiprog);
  log_info(kernelLogger, "Largo Plazo: Se toma una instancia de Grado Multiprogramación");

// ...
}
```

**Comment by Mdavicino** [comment]
Buenas! 

Estoy teniendo la misma duda y quería saber si estaría bien ejecutar el planificador de mediano plazo cada vez que un carpincho entre a new, ya que si lo corro cuando algo entra a block podría ocurrir que después algo entre a new y se quede sin poder pasar a ready

Saludos!

**Comment by iago64** [comment]
Buenas @Mdavicino!
Esta muy bien tu planteo, si solo lo ejecutas cuando algo para a BLOCK, podes no ver las llegadas a NEW, pero tambien tené en cuenta que si lo ejecutas cuando algo llega a NEW puede que no veas cuando algo para a BLOCK y no tenes nada en READY. Por lo que, quizas tenes que hacer la unión de los 2 mundos y ejecutar tu planificador de mediano plazo siempre que un carpincho llegue a BLOCK, llegue a NEW 😉 

Saludos.-

**Comment by Mdavicino** [comment]
Genial, gracias!

**Comment by iago64** [comment]
@neverkas Te quedo alguna duda porque siento que nos fuimos por otro camino en las respuestas 😅

**Comment by iago64** [comment]
Cerramos el issue por inactividad, cualquier cosita nos avisan y/o reabren el issue.
