### ISSUE TITLE
Proyecto explota con referencias indefinidas

### ISSUE THREAD

**Issue by JoseFZudaire** [sisoputnfrba/foro#2376]
Buenas! Estamos teniendo un problema desde el martes que no le sacamos la vuelta, sobre referencias indefinidas. A la tarde entramos a soporte y nos recomendaron juntar los archivos de kernel y planificadores en uno solo, para facilitar la importación de librerías y evitar referencias circulares. Ahora bien, seguimos teniendo problemas con estas referencias. Adjunto a continuación lo que nos tira la terminal:

También pego a continuación nuestro Makefile, por las dudas que sea eso:
```makefile
sources = kernel.c lib.c utils.c
pathLibraries =  -lcommons -lpthread -lm

default: Kernel
all: default

Kernel: $(sources)
	gcc -g -o Kernel $(sources) $(pathLibraries)

clean: 
	rm Kernel || true

.PHONY:
	Kernel
```
Y finalmente, las librerías que agregamos en el kernel.h:
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <commons/log.h>
#include <pthread.h>
#include <commons/collections/queue.h>
#include <commons/collections/list.h>
#include <unistd.h>
#include <semaphore.h>
#include <commons/config.h>
#include <signal.h>
#include <sys/socket.h>
#include <netdb.h>
```

**Comment by RaniAgus** [comment]
¡Buenas! ¿Están seguros de que no están usando una versión anterior del makefile? Veo que al principio el comando `make kernel` hace:
```
$ make kernel
cc     kernel.c   -o kernel
```
Pero en el makefile que pasaste veo esta parte:
```
gcc -g -o Kernel $(sources) $(pathLibraries)
```
Que al expandir las variables `sources` y `pathLibraries` quedaría:

```
gcc -g -o Kernel kernel.c lib.c utils.c -lcommons -lpthread -lm
```
El error de "undefined reference" ocurre porque no se está compilando usando el Fiat `-lcommons`.

Saludos
