### ISSUE TITLE
CONSULTA MODULO MEMORIA

### ISSUE THREAD

**Issue by matiasferrerovilas** [sisoputnfrba/foro#2379]
Buenas tardes,

1. Tenia duda respecto al heap_metadata. Este esta contiguo en memoria?. Ejemplo: Tengo la pagina 0 (vacia), 1(totalmente ocupada) y 2 (vacia). Cuando hago un alloc, ocupo todo el 0 y necesito ocupar mas memoria, este tiene que ser de la pagina 2 porque de la 1 no se puede. Como quedaria el heap_metadata?
  Pagina 0:
    prevAlloc:Null
    NextAlloc: 20
    isFree false
  Pagina 0: 
    prevAlloc:0
    NextAlloc: ?? -> Aca que iria? 
    isFree false
2. Siguiendo el ejemplo del enunciado de paginas:
   
![imagen](https://user-images.githubusercontent.com/27780879/138783535-21b9e53d-cc4c-4203-9724-6966f83238d3.png)
 Y teniendo en cuenta que mi tabla de paginas tiene una lista de heap_metadata. como sabe la pagina 1 que sus primeros 20B son parte de la metadata que se encuentra en la pagina 0?.
 
 3.  Cuando hago un alloc este que retornaria exactamente? basandome en la imagen anterior, el segundo alloc que retornaria el    20 o 0(dado que es la pagina 0)?
 
4. Por ultimo las paginas son asignables a un unico carpincho? o una misma pagina puedo tener informacion del carpincho 1 y del carpincho 4?

**Comment by iago64** [comment]
Buenas @matiasferrerovilas como va? Te queda alguna duda respecto al issue? o lo podemos ir cerrando?

**Comment by matiasferrerovilas** [comment]
@iago64 una ultima duda:
Como se el tamaño del ultimo alloc?.
![imagen](https://user-images.githubusercontent.com/27780879/139602211-6a14f229-97ea-4797-b373-c5ac454a1d20.png)

**Comment by RaniAgus** [comment]
Buenas, @matiasferrerovilas 

Para cada alloc que tengan, siempre debe haber un `heapMetadata` "header" al principio y uno "footer" al final, por lo que siempre el último alloc va a tener un `heapMetadata` al final con `nextAlloc = NULL` y `isFree = true`. 
Por ejemplo, si hacen 3 allocs de X, Y y Z Bytes, la memoria del carpincho va a ser: 
```
0         9        9+X      18+X     18+X+Y    27+X+Y   27+X+Y+Z  36+X+Y+Z      
+---------+---------+---------+---------+---------+---------+---------+
| 9 Bytes | X Bytes | 9 Bytes | Y Bytes | 9 Bytes | Z Bytes | 9 Bytes |
+---------+---------+---------+---------+---------+---------+---------+
```
y el último heapMetadata va a tener:
```config
  prevAlloc: 18+X+Y
  nextAlloc: NULL
  isFree: true
```
Saludos

**Comment by matiasferrerovilas** [comment]
@RaniAgus  ahh muchas gracias, Entonces por cada alloc que hago este genera 2 heap_metadata

**Comment by iago64** [comment]
@matiasferrerovilas si, cada alloc tiene 2 heap_metadata, uno al principio y uno al final, lo importante es que tengan en cuenta que al momento de crear un alloc a continuación de uno existente, actualicen bien los valores si no se van a volver locos para recorrerlos y lo mismo cuando se empiecen a liberar tengan en cuenta controlar también los heap_metadata aledaños por si tienen que consolidar los espacios libres.

**Comment by RodrigoLista** [comment]
> @matiasimartin como va?
> 
> Justamente es necesario que traigan las páginas a MP, ya que si no, no van a cerrar los reemplazos porque van a existir accesos a memoria que no van a existir en su implementación.
> 
> Saludos.-

Para que me quede bien claro. Cada vez que necesite conocer el tamaño de un alloc necesitaría tener acceso a memoria. Cuantos accesos a memoria debería tener? 
- Se estipula uno solo. En este caso, solo leeria el heap del bloque que quiero averiguar el tamaño. Tomaria el valor de nextAlloc, y haria una resta con el valor donde inicia dicho bloque, el cual lo tendria guardado en una estructura administrativa. 
- Deberían existir dos accesos. Tendría que traer el Heap del bloque anterior, para leer el "nextAlloc" para conocer la ubicación del alloc que quiero averiguar el tamaño. Y después otro acceso para leer propiamente el heap que quiero conocer el tamaño, en particular el "nextAlloc". De esta forma, haciendo una resta entre los valores obtenidos de cada next Alloc, calcularía el tamaño de dicho bloque. 

Muchas gracias

**Comment by JuradoMatias** [comment]
Buenas @RaniAgus, perdón pero me vino una duda con lo que dijiste, el "footer" final es necesario? porque lo entiendo como una solución a la pregunta: ¿Cuándo termino? pero es una implementación, no? O sea, puedo implementar otra cosa que pensé? Ya que de esa forma estoy perdiendo los últimos 9B. Y no lo creí necesario.

Por ejemplo para el principio, si quiero malloquear X bytes, creo un heap inicial, y otro al final del bloque de datos (como se muestra primero en el ejemplo) o requiero fijar uno al final si o si?
Si la respuesta es si. Podrían por favor aclarar esas cosas como requerimientos (si quieren como no funcionales)? Ya que a la hora de malloquear X bytes podría tener dos posibilidades de implementación:



```
yo pensé esto (imité la lógica planteada en el ejemplo del enunciado)
+---------+---------+---------+---------+---------+---------+---------+
| 9 Bytes | X Bytes | 9 Bytes |                                       |
+---------+---------+---------+---------+---------+---------+---------+


esto es lo del ejemplo anterior
+---------+---------+---------+---------+---------+---------+---------+
| 9 Bytes | X Bytes | 9 Bytes |                             | 9 Bytes |
+---------+---------+---------+---------+---------+---------+---------+
```

gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

La idea de los heapMetadata es simplemente delimitar las porciones de memoria que se piden por `mate_memalloc()`, por lo que si lo ponemos en términos de allocs sucesivos quedaría de la primer forma:
Respondiendo a la pregunta de @RodrigoLista, tenes que traer los heapMetadata que tenes que modificar.
```
Primer alloc de X bytes
+---------+---------+---------+---------+---------+---------+---------+
| 9 Bytes | X Bytes | 9 Bytes |                                       |
+---------+---------+---------+---------+---------+---------+---------+

Segundo alloc de Y bytes, se modifica el ultimo heapMetadata para actualizarle el nextAlloc y el isFree y se agrega el espacio de los Y bytes y el nuevo heapMetadata al final para marcar el fin
+---------+---------+---------+---------+---------+---------+---------+
| 9 Bytes | X Bytes | 9 Bytes*| Y Bytes | 9 Bytes |                   |
+---------+---------+---------+---------+---------+---------+---------+

Tercer alloc de Z bytes, se modifica el ultimo heapMetadata para actualizarle el nextAlloc y el isFree y se agrega el espacio de los Z bytes y el nuevo heapMetadata al final para marcar el fin
+---------+---------+---------+---------+---------+---------+---------+
| 9 Bytes | X Bytes | 9 Bytes | Y Bytes | 9 Bytes* | Z Bytes | 9 Bytes| 
+---------+---------+---------+---------+---------+---------+---------+
```

El que planteas @JuradoMatias del final suelto no tiene sentido ya que no esta anexo a ningún alloc (independiente de si el alloc esta libre u ocupado).
El header y el footer de _cada alloc_ es justamente esa memoria que podes romper si te pasas un poco de mas con un memcpy o un strcpy y que valgrind te lo marca como `invalid read/write of size X` y que después de un tiempo dependiendo de la suerte que tengas te revienta con un error de `double free or corruption`, son las estructuras administrativas que tiene malloc que a fines del tp las simplificamos porque tienen un par de cosas mas que son un bardo

Saludos.-

**Comment by JuradoMatias** [comment]
Perfecto! me había confundido con que debíamos meter uno al final de la memoria del carpincho. Genial! No tengo mas dudas. Muchas gracias!

**Comment by iago64** [comment]
Buenisimo!

@matiasferrerovilas @RodrigoLista les queda alguna duda de todo lo que se hablo en el issue?

Saludos.-

**Comment by matiasferrerovilas** [comment]
@iago64  por mi esta todo perfecto ya.

**Comment by RodrigoLista** [comment]
@iago64 mi pregunta iba mas relacionado a una iteracion de la lista de allocs, en donde tenga que buscar un alloc libre. Por ejemplo, tengo 5 allocs de un carpincho, estando libres el alloc numero 1 con un tamaño de 10 bytes, y el alloc numero 3, con un tamaño de 24 bytes. Entonces, el carpincho solicita un nuevo memalloc de 15 bytes. 
Ante esta situacion, cuantos accesos de memoria deberian existir, segun las pruebas que va a tener que realizar el modulo?
En este caso, serian 3 accesos? 

En el primero, leo el alloc numero 1, veo que esta libre, pero no tiene el tamaño requerido.
En el segundo acceso a memoria, leo el alloc numero 2, y veo que se encuentra ocupado.
En el tercer acceso, leo el alloc numero 3, y veo que esta libre y tiene un tamaño adecuado, por lo tanto, lo selecciono para guardar el nuevo alloc. 

Hasta aqui, que haya habido 3 accesos a memorias, seria correcto?

Despues deberia modificar el heap del alloc seleccionado, con lo cual no me deberia llevar otro acceso a memoria, ya que anteriormente traje la pagina a memoria para leer el heap.

En este ejemplo, consideramos que cada uno de los heap, se encuentran totalmente incluidos en una pagina. (Si alguno se encontrara dividido en dos, deberia realizar dos accesos a memoria, para leer el heap completo).

**Comment by RaniAgus** [comment]
Buenas @RodrigoLista 
> Hasta aqui, que haya habido 3 accesos a memorias, seria correcto?

¡Correcto! Se iteran los heapMetadata desde el primero hasta encontrar uno libre del tamaño adecuado (first fit).

> Despues deberia modificar el heap del alloc seleccionado, con lo cual no me deberia llevar otro acceso a memoria, ya que anteriormente traje la pagina a memoria para leer el heap.

El hecho de que la página ya estaba en memoria porque recientemente hubo un acceso de **lectura** para leer los heapMetadata **no** evita que tengas que volver a hacer otro acceso (en este caso, de **escritura**) para modificar ese heapMetadata. 

Este acceso también es muy importante ya que el bit de modificado de esa página cambia, lo cual eventualmente hará que se realice un pedido de escritura en Swamp cuando esa página sea seleccionada por el algoritmo de reemplazo.

Saludos

**Comment by RodrigoLista** [comment]
Muchas gracias

**Comment by iago64** [comment]
Gracias a Agus por el aporte y con todas las dudas resueltas, cerramos el issue 🥳
