### ISSUE TITLE
Duda direcciones logicas y fisicas con paginacion

### ISSUE THREAD

**Issue by TomasR264** [sisoputnfrba/foro#2380]
Buenas! Estamos confundidos respecto a la parte del enunciado en la que dice:

>Por otro lado, sobre a las estructuras administrativas externas a la memoria principal, como ya fue mencionado, vamos a tener un esquema de paginación, donde la memoria va a estar dividida lógicamente en páginas de igual tamaño. Por lo tanto, cada carpincho va a tener su propia tabla de páginas, donde vamos a tener las referencias a los marcos donde se encuentra la información de cada página.

>memalloc
Consideremos que un carpincho p quiere reservar el espacio size. Lo primero que debemos hacer es buscar si ya hay algún alloc libre en el espacio de direcciones de p donde quepa el size solicitado. El algoritmo a utilizar para esta búsqueda será First Fit.
En caso de que se encuentre, se deberá asignar a p, considerando que si el espacio es más grande que el necesario, se deberá dividir en 2 allocs (el nuevo, ocupado, y uno libre con el resto).
 En caso de que no se encuentre, se deberá generar un nuevo alloc al final del espacio de direcciones, teniendo en cuenta que si no cabe en las páginas ya reservadas se deberá solicitar más.
 Recordar que el método debe retornar la dirección lógica al inicio de la reserva de espacio; y en caso de que no haya más espacio (tanto memoria como en swap), se denegará la operación haciendo que la biblioteca devuelva la dirección NULL.

![image](https://user-images.githubusercontent.com/62635603/138965406-ff026b7e-7857-4239-afad-dc10125b52b6.png)

No entedemos de donde provienen las direcciones logicas. No se supone que serian direcciones fisicas las que debe devolver memoria? Y que las logicas las debe proveer el proceso? O estamos entendiendo mal?

Y aparte, por lo que entendemos de la teoria, la memoria deberia de estar dividida en marcos y no en paginas. Ya que en el libro dice que "con la paginacion la memoria de divide en muchos marcos pequeños de igual tamaño y cada proceso es el que divide en paginas de igual tamaño". Es asi, o estamos confundidos?

**Comment by kamipalomino** [comment]
Si ahora esa parte se entendió.
Nosotros comprendemos que obviamente no se puede hacer todo como la teoría, pero particularmente en este cuatrimestre no tenemos asignado un ayudarnte para cada grupo para que nos oriente, y la verdad los sábado de soporte es muy poco tiempo además muchas veces las dudas aparecen durante la semana, también a diferencia de otras cursadas virtuales, tampoco tenemos videos, que al principio nos habían dicho que si iban a estar,  entonces a nosotros como alumnos, después de revisar los issues por si tenemos suerte no nos queda otra que aferrarnos a la parte teórica ya sea lo visto en clases o en los libros.
Si el tp quiere reflejar de forma diferente la teoria, lo que no nos parece mal, 
por ahí debería estar un poco más desarrollado, o mejor expresado, o tener algún gráfico de secuencia, (se nos está complicando mucho el inicio del ciclo), información más concreta.
Es más hasta este issue pensabamos que ese gráfico de las páginas era de memoria y no de los carpinchos en memoria 

Otro tema que no nos queda muy claro es cuando recién llega por pimera vez un carpincho. 
Nosotros habíamos planteado tener una lista de "carpinchos" cada una con su correspondiente tabla de paginas, en el caso de la asignación fija, podemos calcular cuántos frames/pág le tenemos que reservar a cada uno, ahora lo que no entendemos muy bien en qué momento hacerlo. 
Porque según el Memalloc, el espacio libre lo buscamos en lo que ya le reservamos, y como sería la secuencia.

Planteo A:

1. Llega el pedido de alloc a memoria -> memoria completamente vacia. (Puedo hacer el alloc)
2. Miro la TLB -> Miss (proceso nuevo no cargado) 
3. Miro en memoria -> no tengo su tabla de pagina por se proceso nuevo
4. Memoria consulta a Swap -> Swap 
5. Se busaca en Swap a Memoria -> No hay info.

Recién ahi Memoria crea la tabla de paginas? y le pasa toda la info a Swap?
volviendose a ejecutar el ciclo
1. Asigno el espacio
2. mando la direccion lógica al carpincho
3. Actualizo su tabla de página 
4. Cargo las paginas en la TLB 

está muy mal lo planteado?

![imagen](https://user-images.githubusercontent.com/28968341/139488906-a3aa723f-aac4-43c6-8d77-41e1ce8380d1.png)

Disculpen que esto se haya hecho tan largo el issue. :confounded: 
Les agradecemos la buena onda que siempre tienen. :smile_cat: 
Saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

El planteo que estas haciendo @kamipalomino es correcto salvo por el único hecho de que no es la única alternativa correcta de implementación (lo aclaro para otros grupos que puedan haber creado la tabla de procesos vacía al momento de recibir el `mate_init()`)

Un solo detalle que te esta faltando es que al momento de crear la página en memoria principal también tenes que crearla en swap ya que la memoria principal es una **copia** de swap.

Saludos.-

**Comment by BDIPAULO** [comment]
Buenas tardes, Me sumo al issue con otra consulta referida al mismo. 

Caso 1er ALLOC

Nosotros en este caso para saber si es la primera vez que alloca el proceso lo corroboramos contra una lista global de todos los procesos que tenemos en memoria ? Si no esta ahí cargamos todas las estructuras admnistrativas necesarias ej la tabla de paginas con una sola pagina vacia de principio. 

En este caso no "observo la tlb" para saber si esta en memoria. Lo cual los miss me van a dar distintos.  

Es valida esta implementación ? O tengo que contemplar de ver la TLB primero para saber si esta en memoria?

**Comment by kamipalomino** [comment]
@iago64 Perfecto todo entendido!!! 
Muchas gracias :smile_cat:

**Comment by iago64** [comment]
@BDIPAULO Tengan mucho cuidado con el tema de desviarse de los diagramas de la teoría, justamente la idea es que respeten el ciclo de:
- Buscar en la TLB 
- Si es un miss buscar en la tabla de páginas
- Si no esta en MP pedirlo a swap

Por otro lado el tema del primer alloc, deberian crear los 2 heapmetadata, el del inicio y el del final del primer hueco como esta en el [comentario](https://github.com/sisoputnfrba/foro/issues/2379#issuecomment-957460581) del issue #2379.

Saludos.-

**Comment by BDIPAULO** [comment]
Gracias @iago64 ! Quedo claro. Ahora me fijo lo de los comentarios del issue que mencionaste. 
Saludos.

**Comment by iago64** [comment]
Buenas @TomasR264 cómo va? Te quedo alguna duda?

**Comment by TomasR264** [comment]
> Buenas @TomasR264 cómo va? Te quedo alguna duda?

No no, todo claro, ya iba a cerrar el issue

Gracias por todo!
