### ISSUE TITLE
[Planificador Corto Plazo] Cálculo de estimaciones (SJF y HRN)

### ISSUE THREAD

**Issue by federiver91** [sisoputnfrba/foro#2382]
Buenas!!

Cada carpincho que se encuentre en la cola de Ready tendrá un cálculo de "estimación de siguiente ráfaga" ante cada ciclo que ejecute y planifique el Planificador, no?

Ejemplo:
-Cola Ready: C1, C2 y C3
-Planificador estima ráfagas (supongamos SJF) y las guarda en un atributo del struct del Carpincho. Ejemplo: 4, 2, 3 respectivamente.
-El proceso que pasa a Exec es el C2 porque tiene la menor rafaga estimada.
-**Cuando el Planificador de Corto Plazo vuelva a ejecutar y estime las rafagas y tenga, por ejemplo, en la Cola de Ready: C3, C1 y C4, va a volver a calcular una "Estimación de rafaga siguiente" para TODOS los Carpinchos de la cola (incluso de C3 y C1 que ya había calculado y las pisará con valores nuevos), verdad?**

De esta manera, el valor que viene por configuración "ESTIMACION_INICIAL" se usará una única vez por cada Carpincho y luego, ante cada ejecución del planificador de corto plazo se volverán a calcular estimaciones nuevas para cada carpincho de la cola de Ready (sean primeras estimaciones o las subsecuentes).

Espero haber sido claro.

Saludos,
Federico

**Comment by LeandroCarbajales** [comment]
De hecho no tenés por qué estimar cuando ejecuta el planificador de corto plazo, podrías asignarle siempre el estimado inicial al crear su PCB y luego actualizarlo o reestimar en los eventos en que vuelve a ready, por ejemplo en la transición (exec -> ready) simplemente restarle lo que ya ejecutó, o en la transición (blocked -> ready) reestimar con la fórmula ya que podemos asumir que comenzará una nueva ráfaga.
De esta manera, el planificador de corto plazo siempre hace lo mismo y te queda la base para luego con HRRN solamente tener que calcular los Response Ratio.
De alguna manera, es lo mismo que se haría para resolver sistemáticamente un ejercicio de planificación.
Espero que ayude a la implementación 😄 

Saludos!
          Lean

**Comment by federiver91** [comment]
Mmm me perdí con lo que decis de exec->ready.

Ahí no tendría que restar nada de acuerdo a SJF (ya que no es VRR). En ambos casos que vuelva a Ready (de Blocked o de Exec), tengo que reestimar con la fórmula.

Igual ya tengo implementado el cálculo de las estimaciones en el planificador de corto plazo, antes de ordenar la lista de Ready por menor rafaga. 

Para SJF, lo que hago, simplemente, es tener un IF que revisa si el campito "rafaga_estimada" del struct del carpincho es DISTINTO de CERO, no calculo nada porque entiendo que es un carpincho que ya estaba en la cola y ya fue calculado previamente. Si es CERO, lo calculo.

Y ese campito, cada vez que el carpincho sale de Ready a Exec, lo pongo en CERO.

**Comment by LeandroCarbajales** [comment]
Buenas!
De (exec -> ready) tendrías que restar lo ejecutado de la misma manera que lo harías en un ejercicio SJF con desalojo, en el caso del tp ambos algoritmos son sin desalojo por lo que esa transición ni existiría.
Con respecto a la implementación, más allá de que funcionaría, te dejo mis recomendaciones:
Ordenar la lista puede hacer que se pierda el orden original, por lo que al agarrar al primero luego de ordenar podría no estar desempatando por FIFO si hubiera más de uno con el mismo estimado (que con el inicial puede pasar), lo veo más simple buscar el de menor ráfaga directamente que no tiene ese problema.
Con respecto a tener un IF en el planificador, no veo necesario cambiarlo pero es una de esas cosas que en Diseño te dirían que "no escala".

Igualmente ya lo hablamos en soporte, pero capaz le sirve a alguien más 😄 
Saludos!
       Lean

**Comment by federiver91** [comment]
Buenas! Podrán pasarme un ejemplo de utilización de las funciones list_get_minimum y list_get_maximum para utilizarlas en el refactor que propone Lean?

Gracias!!

**Comment by LeandroCarbajales** [comment]
Buenas!
list_get_minimum y list_get_maximum en si son iguales, toman una función que toma como parámetro 2 elementos y devuelve uno de los dos.
En este caso podría ser algo tipo
```
Carpincho* menorRafaga (Carpincho* carpincho1, Carpincho* carpincho2) {
        if (carpincho1->rafaga <= carpincho2->rafaga) return carpincho1;
        return carpincho2;
}
```

Luego llamarias:
`Carpincho* carpinchoConMenorRafaga = list_get_minimum(listaCarpinchos, menorRafaga)`

**Comment by federiver91** [comment]
Joooya, gracias Lean!

Ahora, una consulta.. Viendo la declaración de list_get_minimum veo que recibe 2 void* y devuelve un void*

Hice el intento de hacerlo, me podrías decir si así está bien o no hace falta y lo hago directo como hiciste vos?

Definición
![image](https://user-images.githubusercontent.com/49326422/139761366-7084b878-5c42-4888-b5ab-96bc5b04db6b.png)



Llamada
![image](https://user-images.githubusercontent.com/49326422/139761655-617b4552-ce4f-4f42-89f5-695e6dbc8d53.png)

**Comment by iago64** [comment]
Buenas! Cómo va?

La parte linda del código es que lo podes testear y no dependes de que una persona te diga que funciona o no.
A priori lo que tiene C es que _la memoria es memoria_ y un void* es una simplificación de un puntero a algo, ya sea un int, un t_datos_académidos o un t_carpincho, con lo cual, a priori estaría bien lo que planteas, pero podes probalo y verificar que no nos estamos equivocando.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas! Lo veo bien así con el casteo, lo único importante que me hace ruido es la comparación con "<" en vez de "<=", ante elementos iguales entiendo que te quedaría un LIFO en vez de FIFO, es decir, te estarías quedando con el último en vez de con el primero. Como bien dice Dami, podés probarlo para ver que se esté quedando siempre con el carpincho correcto.

Saludos!
           Lean
