### ISSUE TITLE
liberar semaforo en mateclose/deadlock

### ISSUE THREAD

**Issue by alejcha** [sisoputnfrba/foro#2384]
Buenas tardes
una duda que tengo, ya que un carpincho puede hacer mate_semwait y ejecutar, nunca hacer mate_sempost, y finalizar con mate_close
por defecto deberiamos "simular" un sempost en kernel para que el recurso no quede tomado al hacer mate_close?
o deberiamos hacer eso solo en el detector de deadlock? (finalizar un carpincho y hacer mate_sempost(en kernel) del/los semaforos tomados por el carpincho a finalizar)

gracias

**Comment by alejcha** [comment]
jaja dale, por lo que pude probar, las funciones de semaforo posta no hacen nada, pensando algunos casos quiza tenga sentido, porque no podemos adivinar que quiso hacer el programador con la sincronizacion, y puede que en algun caso tenga sentido que haga sem_wait y salga sin sem_post

**Comment by tferraro** [comment]
Claro. La posta en estos casos es "usame bien brodi porque sino es un comportamiento indefinido" que es un poco como se suelen manejar la mayoria de las libs más cercanas al kernel.
