### ISSUE TITLE
Dudas en cuanto a memfree

### ISSUE THREAD

**Issue by marianopoll** [sisoputnfrba/foro#2386]
Dado que el memfree por enunciado debe "`chequear si hay páginas que quedaron totalmente libres y liberarlas.`", si se presentara la situación en donde un carpincho tiene 5 paginas y se debe eliminar la pagina 4 
1-¿los heapmetadata de la pagina 5 deben ser reescritos con la dirección lógica de la pagina 4 o el next alloc final de la pagina 3 seria una dirección lógica de la pagina 5? 
2-¿Qué pasaría en el caso de que se libere la pagina pero en el final de la pagina esta ubicado la mitad de un alloc y queda un espacio restante en la pagina siguiente? 
![image](https://user-images.githubusercontent.com/30994138/139541484-071bdf34-fd14-41f6-80e5-57843d1507b3.png)

3-¿deberíamos ir liberando paginas a medida que vamos analizando si sus heapmetadatas estan vacios o una vez liberados deberiamos correr algo que las libere?
### 📔 Citas del enunciado/videos

`Luego debemos usar el prevAlloc y el nextAlloc para revisar si hay allocs a derecha o izquierda que ya estén libres, en caso de que los haya debemos consolidarlos. También hay que chequear si hay páginas que quedaron totalmente libres y liberarlas.`

**Comment by iago64** [comment]
Buenas! Cómo va?

De base algo que nos quedo un poco flojo en la redacción es que solamente pueden eliminar una página si estan al final, las páginas intermedias las dejan como están.
Dicho lo anterior:

1.- No, esos heapMetadata quedan igual porque no tienen que eliminar la página 4
2.- Si tenes una parte de un alloc de la página anterior, no esta libre esa página 😉.
3.- Pueden hacerlo al momento de liberar el heapMetadata, ahi no hay problema.

Saludos.-

**Comment by iago64** [comment]
@marianopoll Cómo va? te quedo alguna duda?

**Comment by TomasR264** [comment]
Aprovecho que no se cerro el issue todavia para consultar algo @iago64 

Situacion antes del memfree
![image](https://user-images.githubusercontent.com/62635603/140576037-f4cc75a4-bd15-46a8-b17d-ef9f47b769c8.png)

Tenemos tres heaps ocupados (los rojos), uno libre (verde), nos piden hacer un memfree de la info que apunta el heap 1, nosotros habiamos pensado que al buscar en el prev alloc del heap 1 y en el next alloc del heap 1, encontrabamos en isFree = true, el heap 2, entonces eliminabamos el heap 2, consolidabamos los espacios libres y del heap 1, la direccion del next pasaba a ser la del heap 3, en el heap 3, la direccion del prev alloc pasaba a ser la del heap 1

Situacion despues del memfree
![image](https://user-images.githubusercontent.com/62635603/140576169-76677874-6433-4a0a-883f-6a5fb5f9fc5b.png)

No entendemos bien en estas situacion la relacion entre los heaps y las paginas, por que pensabamos que al darnos el size cuando hacen un memalloc, nosotros calculabamos las paginas y los marcos que teniamos que setearle al carpincho en la tabla de paginas, independientemente de los heaps y las direcciones de los mismos (lo unico que tomabamos en cuenta era que la direccion logica correspondia al inicio de la ubicacion del heap del alloc realizado).

Gracias y saludos!

**Comment by iago64** [comment]
Buenas! Cómo va @TomasR264?

Entendieron joya como tiene que funcionar el `memfree()` 😄 
La relación entre los heap y las páginas es relativamente simple:
Heap (heapMetadata y datos) son el espacio usuario y como tal uds si leen algo o escriben algo lo tienen que recorrer de alguna forma, por eso tienen los punetos que devuelven en el `memalloc()` y despues los nextAlloc y prevAlloc de los heapMetadata que están usando bien al momento del `memfree()`

Páginas es el espacio del sistema operativo, por eso que pueden tener sus tablas de páginas y acceder directamente a una página.

Espero que se entienda un poco la explicación.

Saludos.-

P.D: La explicación de la diferencia entre heap y páginas es una hermosa pregunta de coloquio 😉

**Comment by TomasR264** [comment]
> Buenas! Cómo va @TomasR264?
> 
> Entendieron joya como tiene que funcionar el `memfree()` 😄 La relación entre los heap y las páginas es relativamente simple: Heap (heapMetadata y datos) son el espacio usuario y como tal uds si leen algo o escriben algo lo tienen que recorrer de alguna forma, por eso tienen los punetos que devuelven en el `memalloc()` y despues los nextAlloc y prevAlloc de los heapMetadata que están usando bien al momento del `memfree()`
> 
> Páginas es el espacio del sistema operativo, por eso que pueden tener sus tablas de páginas y acceder directamente a una página.
> 
> Espero que se entienda un poco la explicación.
> 
> Saludos.-
> 
> P.D: La explicación de la diferencia entre heap y páginas es una hermosa pregunta de coloquio 😉

Buenisimo, muchas gracias!

**Comment by iago64** [comment]
Buenisimo, entonces resuelta la duda nueva, y por inactividad de la duda original del issue, lo vamos cerrando, cualquier cosa lo pueden reabrir :)
