### ISSUE TITLE
Suspended-Redy a Ready

### ISSUE THREAD

**Issue by gastonharari** [sisoputnfrba/foro#2387]
### 📔 Citas del enunciado/videos

> volverá a READY siguiendo el algoritmo FIFO cuando el grado de multiprogramación lo permita, teniendo mayor precedencia los carpinchos esperando en suspendido que los carpinchos esperando en NEW.
> 
> 
> Cuando un carpincho sea suspendido, todas sus páginas que se encuentren en memoria principal deben ser bajadas a swap. En el caso de la asignación fija, los marcos reservados serán liberados para dar entrada a nuevos carpinchos.

La consulta es que debería pasar en el caso que tengamos un grado de multiprogramacion que acepte el proceso, pero no tengamos espacio en la memoria principal.
Tambien surge la pregunta con lo que debe pasar cuando un carpincho pasa de New a ready (y hay grado de multiprogramacion), pero tampoco hay memoria.
### 💭 Soluciones posibles

Una posible solucion es que los carpinchos queden en la cola anterior (osea en suspended-ready o new)

**Comment by iago64** [comment]
Buenas! Cómo va?

Es un caso borde que no estábamos contemplando, lo vamos a analizar y les damos una respuesta mas concreta, de momento no es una feature que es necesario que tengan que soportar ya que la suspensión esta planteada desde el lado planificación y la CPU ociosa y no desde el lado de quedarse sin memoria.

Saludos.-

**Comment by alejcha** [comment]
Buenas tardes, perdón la intromisión
por lo que entiendo de la teoría, el grado de multiprogramación esta relacionado estrechamente con lo que seria asignación fija en memoria, o sea que dependiendo el numero fijo de paginas que ocupe cada proceso en memoria y la cantidad trames que tenga la memoria es el grado máximo que podes tener, y nunca te vas a quedar sin memoria porque suspendes un proceso y liberas memoria para tener otro proceso, finaliza uno y libera memoria para otro.
en caso de que sea dinámico no hay problema tampoco porque la "memoria llena" se resuelve "automaticamente" desde memoria cuando quiera un proceso que estaba suspendido leer la pagina que esta en swamp, hace un reemplazo global y listo

**Comment by iago64** [comment]
Buenas! Cómo va?

Como bien dice @alejcha el problema solo se va a dar con asignación fija y para simplificar las cosas no vamos a cambiarles a menos de 1 mes de la entrega una definición tan critica, no va a ser testeado, las pruebas de suspensión van a ir con asignación dinámica o con asignación fija y espacio suficiente para todos los carpinchos para que no estén pensando casos tan borde 😄 

Saludos.-

**Comment by gastonharari** [comment]
Perfecto, muchsimas gracias por las respuestas
