### ISSUE TITLE
Memoria - liberar páginas con memfree

### ISSUE THREAD

**Issue by Camila1401** [sisoputnfrba/foro#2388]
Buenas tardes! 

Haciendo referencia al issue #2369, me surgió una duda con respecto a la siguiente oración:

"Efectivamente, es solo el último hueco libre y eventualmente **van a tener que ajustar el último heapMetadata para que refleje las páginas que se liberan**."

Tenía entendido que el último heapMetadata del espacio de direcciones del proceso tenía la siguiente información:
(el nextAlloc y el isFree siempre es igual para el último heapMetadata del proceso)

prevAlloc = 49 (ejemplo)
nextAlloc = NULL
isFree = TRUE

Por lo tanto, si mis páginas son de 32Bytes y mi proceso tiene las siguientes páginas: [0,1,2], esto quiere decir que la página 2 se tendría que liberar ya que es el último hueco libre. Mi duda surge en la parte de tener que ajustar el último heapMetadata ya que no sería necesario modificar ningún dato (suponiendo que en este punto ya se hicieron todas las modificaciones previas de los pasos del memfree: el modificar el flag del heap y unificar de ser necesario).

Quisiera saber si estoy pensando algo mal o me estoy olvidando de alguna cuestión.

**Comment by iago64** [comment]
Buenas! Cómo va?

Si si, fue un lapso mental que me agarro contestando el issue, en ese momento estaba pensando en los tamaños de los alloc y se me paso que el heapMetadata no tiene el tamaño si no el nextAlloc y como bien decis, queda en NULL.

Saludos.-

**Comment by Camila1401** [comment]
Genial, muchas gracias! Saludos!
