### ISSUE TITLE
Duda primer memalloc() de un proceso

### ISSUE THREAD

**Issue by moresisro** [sisoputnfrba/foro#2389]
Buenas, tengo una consulta con respecto al primer memalloc() que hace un proceso: entiendo que, a partir de ese primer alloc, tendremos que chequear si hay espacio en swap para poder asignarle memoria al proceso y, de haber lugar en swap, crear la tabla de paginas correspondiente a dicho proceso. La primera pregunta es, esa página o páginas que voy a crear con los heaps (el inicial y el final), ¿tengo que ponerla/s en memoria principal, marcarles el bit de modificado y pasarlas a swap solo cuando sea necesario (es decir, cuando por ejemplo se corra el algoritmo de reemplazo y esa/s página/s sean víctimas) o bien alojo directamente las paginas en swap? Yo entendía que la primera forma estaba bien (de hecho lo confirmé hoy en soporte con un ayudante aunque me gustaría re-confirmar que lo estoy entendiendo bien) pero después me surgió la duda de: si hay asignación fija con reemplazo local, ¿qué páginas debería mover de la memoria principal para escribir las primeras páginas de este proceso?
Espero haber sido clara, 
Muchas gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

La idea de que todo lo que tengan en memoria principal sea una copia de lo que esta en swap hace que uds al momento de crear una página en memoria principal, también la copien a swap.
Después la van a tener que marcar como modificada si escriben algo o cambia algún heapMetadata y a partir de ahí si les toca reemplazarla la tendrán que actualizar en SWAP, caso contrario, simplemente la sobrescriben y ya, un acceso menos a swap 😄 
Si hay asignación fija con reemplazo local, no me queda clara tu duda pero eventualmente lo que va a pasar es que van a tener de entrada un grupo de frames para ese proceso y ya, al momento de que se llene recién ahí van a tener que empezar a reemplazar.

Saludos.-

**Comment by BDIPAULO** [comment]
Buenas tardes, Como están ? Disculpen pero me sumo al issue dado que me surgió una duda con respecto a tu respuesta. 

Convención: HPM = heap_metadata 

En el caso que alloco tenia entendido que:

1)  Le solicito espacio a Swamp y dependiendo de la respuesta comienzo la rutina de allocar. No tiene espacio devuelvo NULL a la matelib. 
      - Ahora cuando alloco en memoria principal 
               1.1-  Tengo que darle un marco a todas las paginas que me esta solicitando allocar o solo le doy marcos a las que voy a escribir el HPM ?  - Entiendo que serian a todas las paginas asignarle un marco en memoria principal por la variación de acceso a memoria que leí en otros issues. Esto es así? 

              1.2 - Según lo que entiendo cuando allocas en este caso las paginas que tengo q allocar que van a tener un marco asignado en memoria principal y cada una la marco como modificada. Cuando soliciten hacer un memwrite ahí me tengo que fijar si la tengo que reemplazar y si corresponde actualizo Swamp.   Esto es correcto ?  

             1.3 En el caso de asignación fija con reemplazo local  cuando vos quieras allocar el proceso que SI entra en Swamp pero NO entra en memoria principal,  no porque haya usado el grupo de frames que tiene  sino porque la memoria principal esta ocupada por otros procesos? Que sucede ahí porque no puedo reemplazar paginas que le pertenecen a otro proceso, tengo entendido.  Es muy rebuscado lo analizado o no lo tengo en cuenta esta posibilidad ?? 

En nuestro grupo estamos analizando estas posibilidades a la hora de allocar 
- Que entre en memoria principal
- Que no sobrepase la cantidad max de marcos que pueden tener un proceso en mem ppal (este caso toca reemplazar hasta que cargue todo lo que tengo q allocar) 
- Chequear marcos ocupados por el proceso en mem ppal  dado que puede ser que previamente ya haya marcos del proceso en la mem principal.  (este caso cargo los q tengo disponible si tengo y sino tengo empiezo a reemplazar) 

Es correcto o estamos siendo muy rebuscados? 


            1.4 La ultima lo prometo (por ahora) ... cuando allocas seteas la tabla de pagina de tu proceso con toda la info etc, ahora lo que alloque lo tengo que ingresar a la TLB ? 

Gracias. Saludos.
