### ISSUE TITLE
Consulta serializacion entre modulos

### ISSUE THREAD

**Issue by heinHertz** [sisoputnfrba/foro#2390]
Hola estuve leyendo el issue #2365  y me surgieron duda:
´´´
No es necesario que implementen la mate_lib en el kernel, ya que el Kernel es servidor de la mate_lib, pero si pueden hacer que el Kernel y la memoria implementen de la misma forma la serialización y deserialización de los mensajes cosa de codearlo 1 vez y reutilizarlo en 2 módulos distintos
´´´
por la conexión polimórfica, el kernel y la memoria deberían recibir los mismo datos ?    por ejemplo si kernel recibiera un  1 (int) +"capincho"(char*)( por ejemplo) ,  memoria los mismos datos y tambien  1(int)+"carpincho"?

b)   eso implica que Swamp también tiene con implementar la misma serialización pero con datos diferentes?

**Comment by iago64** [comment]
Buenas! Cómo va?

Idealmente si, lo que se busca es que trabajen de forma "polimórfica", si quieren romperse el bocho haciendo 2 serializaciones diferentes nadie se los prohíbe pero van a desperdiciar tiempo.

Swap nunca habla con la matelib, solo habla con memoria, con lo cual ahí pueden mandarse los mensajes como mas les guste, obviamente la recomendación siempre es que se la compliquen lo menos posible.

Saludos.-

**Comment by heinHertz** [comment]
OK. nos quedamos con una serialización para todos,includo Swamp,  gracias.
