### ISSUE TITLE
Compilacion de la MateLib

### ISSUE THREAD

**Issue by franciscoidalgo** [sisoputnfrba/foro#2391]
Buenas! Queria saber si, como alternativa a correr cada modulo setteando la variable LD_LIBRARY_PATH previamente, podiamos mover los headers y el binario a /usr/include/matelib y /usr/lib respectivamente para agilizarlo un poco y no depender del makefile a la hora de correr cada modulo (o tener que settear la variable). Se que es un detalle pero nunca esta de mas intentar y preguntar. 
Gracias por adelantado!

**Comment by iago64** [comment]
Buenas! Cómo va?

Veo que alguien estuvo leyendo los makefile de las commons 😄 
No hay problema, simplemente el usar el LD_LIBRARY_PATH es por comodidad ya que muchos grupos suelen implementar sus propias shared de manejo de sockets entonces están seteando esa variable indefectiblemente.

Saludos.-

**Comment by franciscoidalgo** [comment]
Me estuve intentando amigar con Makefile y Linux en general, sí 😅
Ahora me dejás con una duda extra. En nuestro caso también armamos nuestras "shared" para las conexiones pero las incluímos como archivos aparte en la Matelib (me refiero a que son un .c y un .h en ese mismo módulo) y compilamos todo junto. Supongo que no hay problema, no?
Saludos!

**Comment by iago64** [comment]
Buenas! 

Si estas metiendo los .c y .h dentro del proyecto de la matelib y compilan todo junto... lamento pincharte la ilusión pero no es una shared library como la idea de la matelib, simplemente están importando archivos de otro proyecto.
Igual no pasa nada, pueden hacerlo, solo recuerden que al momento de entregar el tp tienen que clonar el repo en la vm que les vamos a dar y compilar todo, por si las dudas tienen algún paso extra no se lo olviden asi es mas rápido 😄 

Saludos.-

**Comment by iago64** [comment]
@franciscoidalgo Cómo va? te quedo alguna duda?

**Comment by franciscoidalgo** [comment]
No, colgué con cerrar el issue jajajaja. Muchas gracias!
