### ISSUE TITLE
Planificador mediano plazo

### ISSUE THREAD

**Issue by alejcha** [sisoputnfrba/foro#2392]
Buenas tardes
estaba haciendo unas pruebas, y se da el caso que si sigo las condiciones para suspensión:

> Suspensión - Mediano plazo
> Por último, este planificador se encargará de gestionar las transiciones de suspendido-bloqueado y suspendido-listo. 
> Para que un carpincho entre en suspensión se deben cumplir simultáneamente las siguientes condiciones:
> Que haya carpinchos en BLOCKED
> Que no haya carpinchos en READY
> Que haya carpinchos en NEW
>
supongamos por ejemplo que el grado de multiprocesamiento sea 1(seria lo mismo si es mayor), y grado de multiprogramación n
puedo tener el caso que haya carpinchos suspended/ready, y n carpinchos bloqueados, y no haya carpinchos en new
entonces la condición necesaria no se cumple y no puedo suspender, y no quito de suspensión, porque el grado de multiprogramación no lo permite
supongo que habría que agregar una condición extra de que haya carpinchos en new o carpinchos suspended-ready para poder dejar uno en ready y poder ejecutar inmediatamente, de lo contrario puede quedar bloqueado indefinidamente

**Comment by alejcha** [comment]
también se puede dar el caso que no queden todos bloqueados, sino por ejemplo tenga 4 carpinchos
A, B, C y D grado multiprog. 3, grado multiproc. 1
el carpincho C quedo en suspender/ready
A, B y D ejecutan, se bloquean y desbloquean entre ellos y C nunca puede ejecutar, solo por haberse bloqueado en un momento en que habia un carpincho en new
o incluso puede quedar D bloqueado esperando un semaforo que tiene C, y que nunca va a ejecutar hasta que no finalice uno o ingrese uno nuevo
creo que la solución seria que al bloquearse un carpincho, si hay carpinchos en suspended/ready suspender el bloqueado y dessuspender el suspended/ready (teniendo en cuenta el grado de multiprogramación)

**Comment by gastoncastineira** [comment]
Buenas

El caso que mencionás es uno que se puede dar perfectamente, y si pasa, pasa, fin de la historia.

Más allá de eso, ojo acá

> de lo contrario puede quedar bloqueado indefinidamente

Eso no es así porque:

- Si están bloqueados por I/O, eventualmente van a salir
- Si están todos bloqueados por semáforos, hay deadlock y eventualmente el algoritmo que tienen que implementar lo va a resolver

**Comment by NicolasWallovits** [comment]
Hola! Perdón que me cuelgue a este issue, pero es exactamente la misma duda que tenía yo... el si no deberíamos considerar también a los que están como READY SUSPENDED a la hora de decidir si mandamos a suspender un carpincho bloqueado.

Me quería terminar de sacar la duda con algo nomás, y es que si no vamos a tener en cuenta a los que están como READY SUSPENDED a la hora de decidir suspender un carpincho... pasa por un tema de diseño del TP o porque así se da también en la teoría y este tipo de situación se puede dar?

Gracias!

**Comment by alejcha** [comment]
si, pero quedaría el sistema sin hacer nada teniendo carpinchos en ready/suspended, no parece optimo ni "justo" (mas aun utilizando hrrn) con los carpinchos que tuvieron la mala suerte de bloquearse en el momento inoportuno, ya que no pasarían a ready hasta que ingrese un carpincho nuevo o finalice uno de los que están, mientras los que están "no suspendidos" se bloquean, desbloquean y ejecutan tranquilamente. pero aun no importando eso (que se joda el carpincho suspendido), podría darse el caso que queden esperando todos un semáforo que lo tiene un proceso suspendido

ejemplo simple
CPU= 1 Multiprog=2
sem1=0
ingresan en orden los carpincho A,B,C
A se bloquea por io: B pasa a ready->exec 
B se bloquea por semwait (sem1)
A continua en IO: se suspende B y entra C
C hace sempost(sem1) B pasa a suspended ready
C en algún momento hace semwait(sem1) pasa a blocked
A en algún momento hace semwait(sem1) pasa a blocked

(hay mas formas en las que podria darse)
no hay deadlock porque B tiene el semáforo sem1 y no espera otro semáforo, pero no puede ejecutar hasta que ingrese otro carpincho(WTF?)

Aclaro, no me estoy "quejando" ni tengo problema en dejarlo así, y si pasa pasa y que pase lo que pase, menos cosas para retocar y seguramente en los casos de prueba no se de, porque no estarán pensados para que sucedan
entiendo es una simplificación del planificador de un sistema operativo que es mucho mas complejo que un par de if's
pero a nivel de pensar como haría un planificador "robusto y optimo", como que no cierra del todo

**Comment by gastoncastineira** [comment]
El algoritmo del planificador de mediano plazo de este TP es una simplificación de los casos que pueden encontrar en el libro de Stallings (págs. 120-124 aprox., por si les interesa ver la implementación completa). Hay muchas transiciones que quedaron fuera e incluso algunas condiciones dentro las que hay que también no consideramos para que la suspensión no se nos fuera tanto de mambo esta parte del TP. 
Coincido que el algoritmo no es el mejor, pero es el que pide el enunciado y no podemos pedirle a 50 grupos a menos de un mes de la primera entrega que lo cambien

**Comment by alejcha** [comment]
perfecto, muchas gracias
