### ISSUE TITLE
Duda con swapeo de paginas

### ISSUE THREAD

**Issue by IanStratico** [sisoputnfrba/foro#2393]
Hola, estamos teniendo una duda con respecto a el swapeo de paginas, si por ejemplo tenemos una situacion como la del ejemplo del enunciado en la cual hay 2 paginas que comparten un mismo alloc, cuando querramos swapear una de esas paginas, vamos a estar obligados a swapear la otra con la cual comparte un alloc tambien? porque sino a donde quedaria apuntando el heapMetaData de ese alloc compartido.

### 📔 Citas del enunciado/videos

![image](https://user-images.githubusercontent.com/63462753/139597522-6deb3726-2986-4610-bedc-ab6fcdac457e.png)

### 💭 Soluciones posibles

Como solucion se nos ocurrio swapear solo una de las paginas ya que es lo mismo que quede cortado el alloc porque no lo vamos a utilizar y en caso de tener que usarlo volveriamos a traer a memoria principal la pagina necesaria. Pero en esta solucion nos surge el problema de a donde queda apuntado el heapMetaData que quedo del pedazo de alloc que quedo en memoria principal.

**Comment by iago64** [comment]
Buenas! Cómo va?

El heapMetadata va a seguir diciendo, siguiendo el ejemplo, 49, que siguen siendo el byte 49 dentro del espacio de direcciones del carpincho, es importante que no pierdan de vista que los campos de nextAlloc y prevAlloc, son relativos a las páginas del carpincho, y cuentan el desplazamiento dentro de su espacio de direcciones, con lo cual swapear una página no representaría ningún problema.

Saludos.-

**Comment by IanStratico** [comment]
Gracias!!
