### ISSUE TITLE
Consulta sobre bloqueo de IO

### ISSUE THREAD

**Issue by matiaspar2000** [sisoputnfrba/foro#2394]
Teníamos una consulta en el caso de los llamados a IO y los bloqueos cuando el dispositivo está en uso. En el caso de los semáforos nos habían comentado en soporte que lo que debería pasar cuando un carpincho se bloquea es que pase a estado _BLOCKED_ y luego cuando otro proceso haga el post y se desbloquee se pasará a la cola de _READY_. Allí en _READY_ debe esperar a ser seleccionado por el planificador de corto plazo y responderá a la matelib según corresponda.

La consulta es, en caso de que el bloqueo se deba a esperar un IO, tendría que hacer el mismo camino (pasa a blocked, espera que esté libre el dispositivo, se desbloquea, es seleccionado de nuevo por el planificador de corto plazo, entra a ejecutar, realiza la ráfaga de IO, responde) o debería quedarse bloqueado (literal bloqueado por un semáforo, no solo en estado BLOCKED) mientras espera la liberación del dispositivo? 

Es decir, tiene que hacer toda ese paso de nuevo por READY, ser seleccionado otra vez, etc.?  Desde ya muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

La parte de IO es tal cual como ven en los ejercicios de planificación, el proceso hace la petición de IO y el sistema operativo lo bloquea hasta que la misma finaliza y lo manda a READY, con lo cual el circuito queda armado de la siguiente manera:

READY -> EXEC -> `mate_call_io()` -> BLOCKED -> Espera a que finalice la IO -> READY -> EXEC (y contesta a la matelib la peticion de `mate_call_io()`)

Algo importante es que en caso de que tengan ya un proceso utilizando el dispositivo de IO, van a tener que encolarlo al igual que en los semáforos, ya que los dispositivos de IO solo los puede estar "usando" de a un carpincho a la vez.

Saludos.-

**Comment by matiaspar2000** [comment]
No termino de entender bien cual sería el camino en el caso de q el dispositivo IO esté en uso: 

La secuencia arrancaría así: READY -> (planif corto plazo lo selecciona) -> EXEC -> mate_call_io() -> BLOCKED 

> Ve que el dispositivo IO está siendo utilizado por otro proceso

OPCION 1: 
-> Espera que se termine de usar -> toma el IO -> ejecuta IO -> EXEC (contesta) 

OPCIÓN 2: 
-> Espera que se termine de usar **-> READY -> (corto plazo lo selecciona) -> EXEC -> BLOCKED  ->** toma el IO -> Ejecuta IO -> READY -> EXEC (contesta) 

Hasta ahora nosotros habíamos implementado la opción 1 usando un semáforo que bloquea el carpincho y se hace post recién cuando se libera el dispositivo, pero no sé exactamente que se pide en la consigna.

**Comment by iago64** [comment]
Buenas! Cómo va?

Por suerte puedo volver al mismo punto anterior y decir que es igual que los ejercicios de planificación de la teoría:

READY -> EXEC -> llega un llamado a mate_call_io() -> BLOCKED -> Espera que liberen el dispositivo de IO (Es decir terminen los que llegaron antes) -> Espera a que finalice la IO del carpincho -> READY -> EXEC (donde el kernel le contesta a la matelib que termino la IO y lo deja seguir)

Saludos.-

**Comment by matiaspar2000** [comment]
Entendido, muchas gracias. Cierro hilo.
