### ISSUE TITLE
DeadLock - Semáforos

### ISSUE THREAD

**Issue by Mdavicino** [sisoputnfrba/foro#2395]
Buenas!
Estamos intentando encarar el algoritmo de detección de deadlock y nos surgió una duda con respecto a como saber quien es el que está usando cierto recurso. 
Lo que se nos ocurrió fue guardar que carpinchos son los que hicieron wait en un semáforo y están usándolo, y después cuando le hacen post lo sacamos de esa lista (indicando que ya no usa más dicho recurso).

Estaría bien encarado de esa forma? Ya que no se nos ocurre otra alternativa

**Comment by iago64** [comment]
Buenas! Cómo va?

No veo que contradiga ninguna parte del enunciado, con lo cual es válido tener una matriz (representada por una lista) de asignación de los semáforos 😉 

Saludos.-

**Comment by Mdavicino** [comment]
Genial, gracias!

**Comment by federiver91** [comment]
Buenas!! Aprovecho este thread!

Tengo una lista de carpinchos que le hicieron WAIT a un semaforo guardada en cada estructura de semaforo que se inicia (con SEM_INIT).

Pregunta clave que me complica bastante la implementación: **Un carpincho podría hacer varias veces wait al mismo semaforo?** (De la misma manera con post). Esto haría que me tenga que guardar, además, la cantidad de recursos de un semaforo que determinado carpincho (de esa lista) está solicitando.

Gracias
