### ISSUE TITLE
Dudas sobre memalloc 

### ISSUE THREAD

**Issue by BDIPAULO** [sisoputnfrba/foro#2396]
Buenas tardes, 

Les comento mi duda es muy puntual. En soporte yo comprendí que no podían haber dos heap_metadata juntos y leyendo el issue #2372  expresan que si.  Por favor me podrán confirmar cual es la opción valida ?  

![image](https://user-images.githubusercontent.com/82339389/139914640-4db3b254-20b2-4af1-96cc-42c78f4e5fbd.png)

Muchas gracias. Saludos.

**Comment by iago64** [comment]
Buenas! Cómo va?

Antes que nada, trata de no subir screenshots, es mucho mas útil tus compañeros el tema de tener texto así pueden usar el buscador 😄 

Respecto a la pregunta, pueden quedar 2 heapMetadata pegados? si, pueden quedar 2 pegados, es un caso recontra borde pero se puede llegar a dar en las pruebas donde no tenemos tanto control sobre las peticiones de memoria.

Saludos.-

**Comment by BDIPAULO** [comment]
Disculpa. Puse el screen para que veas directamente el issue que esta referenciado mas arriba.  Lo voy a tener en cuenta tu comentario. 

Comprendido. Gracias por tu respuesta. 
Pd: Cierro el issue no me quedan mas dudas. 
Saludos
