### ISSUE TITLE
Dudas  memalloc  - casos posibles analizados - TLB

### ISSUE THREAD

**Issue by BDIPAULO** [sisoputnfrba/foro#2397]
Buenas tardes,   

CONVENCION: memoria principal = MP

1.  En nuestro grupo estamos analizando estas posibilidades a la hora de allocar 

CASO ASIGNACION FIJA - SUSTITUCION LOCAL

a) Que entre en MP , es decir, que tengo espacio disponible en memoria para asignar. Duda puntual de esto en issue #2389 

b)Que no sobrepase la cantidad máxima de marcos que pueden tener un proceso en MP (este caso toca reemplazar hasta que cargue todo lo que tengo q asignar teniendo en cuenta si ya tengo marcos asignados en MP) 

c)Chequear marcos ocupados por el proceso en MP dado que puede ser que previamente ya haya marcos del proceso cargados en MP (este caso cargo los q tengo disponible si tengo y sino tengo empiezo a reemplazar) 

Es correcto o estamos siendo muy rebuscados? 

2. La ultima lo prometo (por ahora) cuando allocas seteas la tabla de pagina de tu proceso con toda la info etc, ahora lo que asigne agrego la entrada en la TLB ? Esta relacionada con la consulta en el issue #2380.

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- No me termina de quedar clara la duda, pero por las dudas rescato que:
a.- Validar que entre en MP esta perfecto
b.- Validar que no se pase del tamaño de lo que puede tener el proceso en MP esta mal, porque si por ejemplo podes tener 1 solo frame en MP pero podes tener 5000 en swap, es problema de la memoria ir obteniendo de a 1 los frames y reconstruir lo que le pidieron.
c.- Esta bien este checkeo porque van a tener que validar si tienen todo el espacio máximo solicitado y en ese caso tendran que reemplazar según lo que diga el algoritmo.

2.- Van a agregar las entradas a la TLB a medida que las referencian, siempre hasta lo que permita la TLB (no se olviden que tienen un limite de entradas)

Saludos.-

**Comment by BDIPAULO** [comment]
Buenas @iago64

1b) Ok, estaba pensando algo rebuscado pero que básicamente era un error porque directamente tengo el chequeo del espacio máximo solicitado.  Lo que respondiste si lo había entendido que era así. 

2) Comprendido. 


Gracias. Saludos
