### ISSUE TITLE
Duda- Dirección lógica del Heap metadata 

### ISSUE THREAD

**Issue by BDIPAULO** [sisoputnfrba/foro#2398]
Buenas tardes, Me ha surgido otra duda con respecto a que tengo que devolver si te me piden leer o escribir en las direcciones lógicas correspondientes a un heap_metadata???
Eso es visible por el usuario?

Dado que nosotros la validación de direcciones la hacemos por si tenemos la pagina correspondiente a esa dirección lógica que nos manda la matelib en la tabla de paginas. 

### 📔 Citas del enunciado/videos

>memread
Se usa para obtener información de la memoria. Con la dirección lógica que nos proveen y  la tabla de páginas hacemos la traducción a direcciones físicas y retornamos el contenido. 
En caso de que se quiera leer una posición de memoria errónea, se deberá devolver el error MATE_READ_FAULT definido en el enum mate_errors de la matelib correspondiente con el valor -6.

>memwrite
Se usa para escribir en la memoria. Con la dirección lógica que nos proveen y  la tabla de páginas hacemos la traducción a direcciones físicas y guardamos el contenido en el alloc correspondiente.  
En caso de que se quiera escribir en una posición de memoria errónea, se deberá devolver el error MATE_WRITE_FAULT definido en el enum mate_errors de la matelib correspondiente con el valor -7.

### 💭 Soluciones posibles

Dar un error de lectura o escritura en estos casos con los errores ya expuestos en la matelib teniendo en cuenta cada vez que alloque guardarme en una estructura adm las direcciones lógicas de contenidos validos de cada proceso.  

Gracias. Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

Esta perfecto lo que validan uds, es básicamente como funciona en la realidad, si justo le pegan a una porción de memoria de su proceso, no pasa nada, escriben lo que tengan que escribir y no revienta (a lo mucho después rompe en mil pedazos mas adelante porque corrompieron algo, pero no es problema de la memoria si no del programa / carpincho)

Saludos.-

**Comment by BDIPAULO** [comment]
Buenas @iago64 ... Comprendido. 

Gracias por la respuesta. 

Saludos.
