### ISSUE TITLE
Dudas con respecto al Kernel

### ISSUE THREAD

**Issue by gabycosta04** [sisoputnfrba/foro#2399]
Buenas teníamos una duda con respecto a lo que se realiza en Kernel:

1-El enunciado dice que cuando un proceso pasa a suspendido, todas las paginas se deben suspender.... Entonces cuando pasa a ready nuevamente... tenemos que solicitar a memoria que ponga todas las paginas en memoria devuelta?

2- ¿Cómo podriamos arrancar a realizar lo que seria lo de deadlock? Alguna recomendación de algun libro o algo? Ya que no entendemos como podriamos implementarlo, ya que los algoritmos teóricos que utilizamos tendriamos que realizar simulaciones y ver si hay un camino posible para ver si no esta en Deadlock (lo cual lo vemos demasiado complejo de realizar)....

3- ¿Cuándo el proceso esta en deadlock, tenemos que ponerlo como en exit??? El tema es que si el proceso todavía le falta ejecutar el mate_Close, (pero se supone que como estaba en deadlock lo teníamos que cerrar antes), que hacemos?

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- No, solamente van a traer las páginas a medida que les lleguen las peticiones.

2.- Hay algunas condiciones del deadlock que les vienen dadas directamente por enunciado, por ejemplo la retención y espera, pero dentro de las condiciones hay 1 que podes checkear fácilmente, va por ese lado 😉 

3.- Si, simplemente lo mandan a EXIT y asumen el mate_close(), es decir, hacen todo lo que tendrían que hacer como si les hubiera mandado el mate_close()

Saludos.-

**Comment by iago64** [comment]
Buenas! Cómo va?

Respecto a la parte de las condiciones de deadlock, no estan explicitas en el enunciado, es justamente lo que uds tienen que asumir de la teoría 😉 
Igual te tiro un centro a ver si descubris cual falta: Los semáforos son compartidos por todos los carpinchos, y cuando uno lo toma, nadie mas lo puede tomar y de yapa, cuando alguien toma un recurso, no se lo puede expropiar.

Respecto a la implementación que tiene de IO, solo me queda una duda, cuando le contestan el mensaje al carpincho de que termino la IO? cuando vuelven a EXEC? porque la joda viene que cuando uds le contestan que termino la IO al carpincho, la matelib finaliza la funcion y sigue con el resto de lineas y no debería pasar hasta que vuelvan a exec.

Saludos.-

**Comment by gabycosta04** [comment]
> Igual te tiro un centro a ver si descubris cual falta: Los semáforos son compartidos por todos los carpinchos, y cuando uno lo toma, nadie mas lo puede tomar y de yapa, cuando alguien toma un recurso, no se lo puede expropiar.

Una pregunta con respecto a esto, onda nosotros teniamos entendido que los semaforos se podian inicializar en valores mayores a 1, por lo tanto podria pasar que varios hagan sem_wait y puedan utilizarlo al semaforo de manera paralela.... entonces podrian tomarlos dos procesos al semaforo o estoy mal?


> Respecto a la implementación que tiene de IO, solo me queda una duda, cuando le contestan el mensaje al carpincho de que termino la IO? cuando vuelven a EXEC? porque la joda viene que cuando uds le contestan que termino la IO al carpincho, la matelib finaliza la funcion y sigue con el resto de lineas y no debería pasar hasta que vuelvan a exec.

Nosotros lo que hacíamos es enviarle al carpincho antes de ponerlo en bloqueado, que encontramos el dispositivo y que vamos a ejecutar el bloqueo. Despues cuando vuelve a exec ejecuta otra funcion digamos..... entonces lo que vos decis es que en realidad al carpincho deberiamos avisarle de que se ejecuto la IO (y me imagino que de la misma forma, para semaforos seria que ejecuto el SEM_wait también) en el momento que vuelve a entrar a exec no?

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Si, los semáforos se van a poder inicializar en valores mayores a 1, pero esto no te evita de que al momento de pedir un semáforo el mismo ya este en 0 (o un valor negativo) y por lo tanto ese carpincho se bloquee esperando ese semáforo y pueda retener otros semáforos.
Por eso es que ya les dimos planteada la estrategia de resolución de deadlock que es ir mandando a exit a los carpinchos en orden descendente segun los ID.

2.- Efectivamente, tene en cuenta que cuando uds le contesten a la lib, esta deberia finalizar la función y por lo tanto el carpincho sigue ejecutando cuando debería estar bloqueado.

Saludos.-

**Comment by gabycosta04** [comment]
> 1.- Si, los semáforos se van a poder inicializar en valores mayores a 1, pero esto no te evita de que al momento de pedir un semáforo el mismo ya este en 0 (o un valor negativo) y por lo tanto ese carpincho se bloquee esperando ese semáforo y pueda retener otros semáforos.
Por eso es que ya les dimos planteada la estrategia de resolución de deadlock que es ir mandando a exit a los carpinchos en orden descendente según los ID.

Ok, medio voy entendiendo, entonces digamos que primero los procesos que estén reteniendo y no pidan recursos, o los que estén pidiendo pero no reteniendo, deberia no considerarlos porque no cumplen con la condicion de retención y espera?. Y en ese caso deberíamos analizar si hay una espera circular o algo asi entre los demas procesos y ir sacando de a uno, hasta que no haya mas deadlock??

El tema es que me cuesta entender como hallar que hay un deadlock en el sistema en si, porque como es detección y recuperacion yo me quede con la teoría donde ejecutábamos un algoritmo que realizaba una simulación de asignación de recursos,  para ver si puede satisfacer todas las peticiones actuales de los semaforos. Tendria que ser asi como en la teoría también donde teníamos: Matriz de asignación, Matriz de peticiones, Vectores de recursos totales y disponibles o no seria como se menciona en la teoría?

Perdón que sigo preguntando, es que no me termina de quedar del todo claro

**Comment by iago64** [comment]
Buenas!

Acá la joda es que no van a poder prevenirlo porque no van a saber que recursos va a pedir un carpincho hasta que lo pide, entonces van a tener que detectarlo en el momento que ya tengan los carpinchos bloqueados entre si
Por eso les importan solamente los procesos que estén bloqueados y que además tengan semáforos retenidos 😉 

Saludos.-

**Comment by gabycosta04** [comment]
> Por eso les importan solamente los procesos que estén bloqueados y que además tengan semáforos retenidos 😉

Dami y una ultima pregunta, nosotros hay tendriamos que analizar que si hay una espera circular entre estos procesos para ver si hay deadlock? Nosotros nos habíamos planteado de que si había procesos cruzados entre si, pero creo que deberia analizarse si hay una espera circular no? 

Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

Exacto! La espera circular es lo único que tienen que controlar, las otras 3 condiciones vienen dadas por la naturaleza del enunciado 😄 

Saludos.-

**Comment by gabycosta04** [comment]
Dami y una pregunta mas con lo de deadlock, esto se analiza para semaforos que son de tipo mutex digamos, o podria ver también los que son contadores(que se inicializan en mas de 1), el tema es que hay se cumple lo de mutua exclusión? porque en ese caso podria pasar que varios estén reteniendo el mismo semáforo?

**Comment by iago64** [comment]
Buenas! Cómo va?

Los semáforos van a ser todos de tipo contador, por lo cual, si, puede dárseles el caso de que un semáforo puedan tenerlo tomado mas de un carpincho, pero ahí a uds lo que les importa son aquellos semáforos que van a tener carpinchos bloqueados esperando por ellos y de esos carpinchos bloqueados, aquellos que tienen además semáforos retenidos, con esa premisa si parten de un semáforo "X" y dando la vuelta entre carpinchos bloqueados y que retienen semáforos, vuelven al mismo semáforo "X", entonces ahí es donde van a tener el deadlock 😉 

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @gabycosta04 ! ¿Quedó alguna duda con la respuesta de Dami? Saludos

**Comment by gabycosta04** [comment]
Dale perfecto, no me quedaron mas dudas...
Saludos y cierro issue
