### ISSUE TITLE
Validacion de datos en operaciones de memoria

### ISSUE THREAD

**Issue by alejcha** [sisoputnfrba/foro#2400]
Buenas tardes, se que hay varios issues ya, pero un poco como que me perdi en tanto, quería confirmar el tema de validar los datos ante operaciones de memoria, ya que según como se tome cambia el acceso a las paginas del carpincho

-en memalloc tengo que recorrer los heapmetadata del carpincho (leyéndolos desde la memoria) hasta encontrar el hueco o el fin y crear uno nuevo.

-en memfree el carpincho me va a enviar un "puntero" (un numero entero). dado que no tengo idea si me manda un puntero al inicio de un alloc ocupado (o sea un hueco valido a liberar) tengo dos opciones :
 -confió que el carpincho no hace lio, y libero ciegamente el heapmetadata que comienza en la posición "punteroRecibido-9" 
 -o no confío y la única forma que tengo de asegurarme que no me mando fruta es recorrer todos los heapmetadata (accesos a paginas) hasta que encuentre el que le corresponde (o no lo encuentre y le devuelvo error)

-mismo caso en memwrite, voy a recibir un puntero y un size, y aqui se suma que si el puntero no es el inicio, sino una dirección dentro del alloc (tipo ptr + 4) seria valido, porque un programa podría escribir en cualquier lugar de la memoria reservada. así que confió que lo que me manda es todo legal y bonito, o no, y no tengo otra forma de asegurarme que lo que mandó es correcto sino es recorriendo todos los heapmetadata, si no, puedo escribir cualquier cosa y pisar un heapmetadata y queda todo inconsistente

en memread lo mismo, peeeero, si manda fruta no se rompe nada, así que no necesitaría recorrer los heapmetadata, (solo validaría que lo que quiere leer este dentro de la memoria que el carpincho tiene asignada) y si lee memoria liberada, datos de un heap, o datos de otro alloc, no me importa, total no pasa nada.
O también debería validar todos los heapmetadata para encontrar si es correcto

para redondear
para asegurarme la consistencia:
recorro los heapmetadata (con acceso a las paginas) en memalloc, memfree y memwrite
no necesito recorrer (o si) en memread

Gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

`memalloc()`: es correcto, tienen que recorrer todas las páginas hasta encontrar el primer lugar donde entre el alloc.

`memfree()`: Pueden confiar, eventualmente lo único que deberían checkear es que no les pase una dirección cualquiera y que por ejemplo después de decodificarla les diga que es de la página 256 y su carpincho tiene 10 páginas nomas, ahi tienen que devolver el error de MATE_FREE_FAULT

`memread()` y `memwrite()`: misma validación que `memfree()` que la dirección que les pasen sea de su carpincho, el resto es problema del que codeo el carpincho (osea problema de los ayudantes 😉).

Saludos.-

**Comment by alejcha** [comment]
perfecto, muchas gracias :)
