### ISSUE TITLE
Dudas varias con LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by heinHertz** [sisoputnfrba/foro#2401]
Hola, tengo varias dudas relacionadas con LD_LIBRARY_PATH  y con librerías, en mi grupo estamos haciendo el TP con VSCode, 
que la base la sacamos de aca   https://github.com/dariokozicki/utnso-vscode  , tengo varias dudas relacionadas

a) tenemos carpeta Shared, con Include y src, el tema es que en VS Code aparece un mensaje a pesar de que tenemos todos los files:
en server.c
´´´
Se han detectado errores de #include. Actualice el valor de includePath. El subrayado ondulado está deshabilitado para esta unidad de traducción (/home/utnso/Escritorio/tp-2021-2c-Nordelta.add-carpinchos-/shared/src/server.c).
no se puede abrir el archivo origen (código de error "sys/cdefs.h"). (dependency of "server.h")
´´´ 
![image](https://user-images.githubusercontent.com/37560557/140246989-ca1a83b5-2b53-41bb-938e-0ebcd366ef4e.png)

lo que parece raro, porque porque muchos includes que están en server.h están en ondulados en rojo,  los módulos se ejecutan sin problemas y en sus respectivos módulos hay referencias a esos files  en ccp_properties.json en  includePath con "../shared/include" , aunque según entendimos este file ccp properties json ni ningun json es necesario poner en la shared, asi que no se que puede estar pasando. que podría faltarme para arreglar ese mensaje?

b) con el tema de LD_LIBRARY_PATH , estoy entendiendo que es una variable de entorno, como un path, pero no mucho mas, quizás lo anterior este causado por esa variable no?  estuve viendo videos  https://www.youtube.com/watch?v=Aw9kXFqWu_I    sobre librerias pero VSCode no tiene una configuración así.  y tambien #2007 no lo entendí mucho, el tema de esta variable viene de que según voy entendiendo en el TP actual haría falta settear esta variable, el tema es que uso VScode y repase issues como   #2007 en la que entiendo que para settearla hay que hacerlo a través de un script y creo que también antes de correr los makefiles, es así ?

muchas gracias.

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Lo que es VSCode es una alternativa de la cual no tenemos mucha documentación y justamente el post fue de un ex alumno que se puso la 10 y aporto la alternativa de como usar VSCode, pero si te tengo que dar la respuesta oficial es: _El soporte lo damos para eclipse_
De todas formas el archivo `sys/cdefs.h` es algo que debería venir estandar, por lo que te pregunto, estan usando una vm de la cátedra o estan usando una instalación de uds? Porque me suena a que les falta un paquete.

2.- Efectivamente la variable LD_LIBRARY_PATH, es una variable de entorno que lo que te indica es donde buscar los archivos .so de las shared libraries. Como setearlo va a depender del entorno, si por ejemplo estas corriendo el proceso en una consola vas a tener que ejecutar antes de correr el programa el comando `export LD_LIBRARY_PATH=...` y reemplazar los puntos suspensivos por el path a donde este el .so de tu shared library.

Saludos.-

**Comment by heinHertz** [comment]
1-  Estamos usando la VM de la catedra, la descargamos de los links que ustedes nos proveyeron.

2-  ok, voy viendo como setteo. gracias.

**Comment by iago64** [comment]
Buenas!

1.- Ahora si que se me complico la cosa, podes desde una terminal tirar un `ls /usr/include/x86_64-linux-gnu/sys` y ver si te aparece el archivo cdefs.h? Si te aparece lo que te faltaría agregar es en el archivo `c_cpp_properties.json` una línea que tenga `/usr/include/x86_64-linux-gnu/` y otra que tenga `/usr/include/x86_64-linux-gnu/sys` dentro del objeto `includePath` y dentro del `browse.path`

2.- Por las dudas como comentario extra, para setearlo en los archivos de VSCode, pueden probar de agregar la linea del export justo antes de que ejecute 😉 

Saludos.-

**Comment by heinHertz** [comment]
Hola, 
1-ahi se me salió, lo que hice fue ponerle una carpeta .vscode   y el c cpp properties.son con includePath similar al que tienen los demás files. Se puso en verde, así que se solucionó.

![image](https://user-images.githubusercontent.com/37560557/140611334-59d62b0e-ead4-427a-bbaf-11120cfafc49.png)

2- ok.
gracias.

**Comment by iago64** [comment]
Buenas!

Eso de que este verde el archivo es simplemente que tiene cambios sin commitear al repo 😄 

Saludos.-

**Comment by heinHertz** [comment]
creo que se me arregló, cualquier cosa sigo consultando. gracias.
