### ISSUE TITLE
Planificador de mediano plazo - Transición de suspendido-listo a listo

### ISSUE THREAD

**Issue by lucianoj77052012** [sisoputnfrba/foro#2402]
Buenas! Qué tal?

Tengo una pregunta con respecto a esta sección del enunciado del planificador de mediano plazo:

> Una vez que haya terminado el bloqueo de este carpincho, este pasará a suspendido-listo, y volverá a READY siguiendo el algoritmo FIFO cuando el grado de multiprogramación lo permita, teniendo mayor precedencia los carpinchos esperando en suspendido que los carpinchos esperando en NEW.

Mi pregunta es: si yo tengo carpinchos en suspendido-listo y carpinchos en NEW, y el grado de multiprogramación permite que un carpincho sea pasado a READY, según el enunciado, primero deberían pasarse a READY los carpinchos en suspendido-listo (ordenados de acuerdo con el algoritmo FIFO), y después los carpinchos en NEW, o los carpinchos que están en suspendido-listo deberían sumarse "atrás de todo" de los carpinchos en NEW, y ser pasados a READY sólo después de que todos los carpinchos en NEW ya hayan pasado a READY y el grado de multiprogramación aún lo permita?

**Comment by iago64** [comment]
Buenas! Cómo va?

Primero van los que estan en suspendido y despues los que estan en NEW.
Es al igual a como se hace en los ejercicios de planificación de la teoría 😄 

Saludos.-

**Comment by lucianoj77052012** [comment]
Buenísimo, muchas gracias!! 😉
