### ISSUE TITLE
Consultas sobre el heapMetaData

### ISSUE THREAD

**Issue by Patricio-Galli** [sisoputnfrba/foro#2403]
Buenas tardes. Tenemos dos dudas principales:
1- ¿Al inicio de una asignación de carpincho, cuando no tengo ningún alloc hecho, puedo tener simplemente un heapMetaData con prevAlloc = NULL y nextAlloc = NULL? Nos parece la solución más sencilla, pero queremos confirmar que se puede, sobretodo después de leer el issue #2345.

2- ¿Es necesario tener una estructura t_heap con los tres atributos ya conocidos para hacer el memcpy a y desde la memoria? Es decir que pensamos copiar y pegar los atributos directamente.

Gracias y saludos.

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- No, justamente el primer heap_metadata lo van a crear al momento de que les llegue el primer alloc

2.- No hay problema siempre y cuando respeten los tipos de dato, porque las cuentas de las pruebas las hicimos para que los heap_metadata ocupen 9 bytes. 

Saludos.-

**Comment by tferraro** [comment]
@Patricio-Galli buenas! Como va? Te sirvieron las respuestas de Dami? Seguis con dudas? Contanos :)

**Comment by marianopoll** [comment]
Buenas!
Aprovecho que el issue esta abierto para hacer otra consulta sobre los HeapMetaData.

En cuanto a la primer pregunta de patricio ¿Eso implicaría que al inicio de una asignación de carpincho, no se debería escribir nada en memoria, solamente se debería crear la tabla de paginas?

Otra Pregunta ¿se puede dar una situación en la que el heapmetadata comience y termine en 2 paginas diferentes?

desde ya muchas gracias.

**Comment by iago64** [comment]
Buenas!

Efectivamente, de entrada como mucho tienen que crear sus estructuras administrativas en la memoria.

Si, un heapMetadata puede ser que justo empiece en una página y termine en la siguiente.

Saludos.-

**Comment by iago64** [comment]
Buenas! 

Por inactividad vamos cerrando el issue, cualquier cosa lo pueden reabrir o crear uno nuevo si alguien tiene mas dudas sobre lo charlado aca.
