### ISSUE TITLE
Dudas deadlock

### ISSUE THREAD

**Issue by AlexanderArmua** [sisoputnfrba/foro#2404]
Buenas, 
En mi equipo ya terminamos el planificador, pero en la parte de Deadlocks no pudimos avanzar casi nada, asi que luego de leer la teoria, parciales, libro y el foro terminamos concretando las dudas:

1. Leímos el issue #2399 y entendímos cual es la condición faltante, pero igualmente esto solo garantiza que no ocurra el deadlock. Si esta condición se cumple, igualmente deberíamos checkear las otras 3 condiciones. ¿Es correcto?

2. Siguiendo con el enunciado, si detectamos un deadlock ```se terminarán siempre uno a uno los carpinchos iniciando por el de mayor ID hasta que se haya solucionado el interbloqueo```. Se que en una aplicación real seria solo el involucrado en el deadlock, pero esto me pareció mucho mas complejo y por eso quise consultarlo. ¿Finalizo el carpincho de mayor ID en todo el sistema o solo de los que estan en deadlock?

3.  ```se terminarán siempre uno a uno``` ¿Qué significa esto? Al seleccionar el carpincho a terminar ¿Debería moverlo a finalizado? ó ¿Debería desalojarle todos sus recursos, dejarlo bloqueado y que los otros carpinchos continuen para luego devolverselos?

**Comment by LeandroCarbajales** [comment]
Buenas!
1.- Para chequear deadlock simplemente tendrías que buscar entre los carpinchos que están bloqueados por semáforos y ver que estén bloqueados de manera "cruzada".
2.- El de mayor ID de los que están en el deadlock :)
3.- Sí, debería finalizar completamente.

Espero que te sirva mi respuesta :D
Saludos!
          Lean

**Comment by AlexanderArmua** [comment]
Si, ahora me queda mucho mas claro. 

Entiendo que solo debería buscar los que están bloqueados y luego de los bloqueados los que están de manera cruzada. 

Muchas gracias.
