### ISSUE TITLE
Duda sobre asignación fija

### ISSUE THREAD

**Issue by mercedesmagnelli** [sisoputnfrba/foro#2405]
Buenas noches! 
Nos surgió una duda mientras estábamos definiendo el tema de los procesos en caso de asignación fija. Si bien  el enunciado dice que en SWAmP tienen que estar contiguos los frames de un proceso, esto implica que en memoria principal también tengan que estar continuos los N frames que tiene permitido? Esto implicaría que  tendríamos que reservarle la máxima cantidad de frames posibles en RAM al proceso y  usar estos frames a la hora de traer una página de SWAP (haciendo su posible reemplazo entre estos frames)?
Dejo una foto más ilustrativa para que se visualice mejor: 

![unknown](https://user-images.githubusercontent.com/62451237/140449369-2af440e5-b0d4-4bd5-b8a8-864d63502ed1.png)

Es decir, un proceso NO debería tener repartidos sus frames libremente en la memoria ram sino que tendrían que estar todos contiguos (en ram) también? Asumo que en asignación dinámica, no tienen que estar contiguos sino que van ocupando frames a demanda. 

¡Gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

La idea de la asignación fija es que al momento de ingresar un carpincho a memoria ya tenga reservados sus frames y que disponga de esos frames para usarlos a lo largo de su ejecución.
Si tienen que estar juntos o no, da igual, pero medio que si van a reservar N frames cada vez que un carpincho entre a memoria, me parece que seria demasiado rebuscado que en lugar de seleccionar por ejemplo los frames 0, 1 y 2 (siguiendo tu ejemplo de 3 frames por carpincho) elijas 0, 5 y 8.

Saludos.-

**Comment by mercedesmagnelli** [comment]
Clarísimo, muchas gracias!
