### ISSUE TITLE
Duda sobre el memwrite en memoria

### ISSUE THREAD

**Issue by RodrigoLista** [sisoputnfrba/foro#2406]
Estuve buscando algún issue, pero no encontré ninguno que me saque la duda. La consulta es la siguiente: cuando yo envio un memwrite, va a estar destinado para un solo alloc?

Es decir, por ejemplo, yo tengo dos bloques allocados de un mismo carpincho, el primero con dirección lógica de 0 a 100 y el segundo de 100 a 150.
 
- Entonces, primer caso, si yo recibo memwrite con los parámetros puntero=30 size=50. Entonces debería escribir el primer alloc desde el byte 30 hasta el 80.
- Segundo ejemplo, recibo un memwrite con parámetros puntero=30 size=80. Entonces, ante esta situación, debería escribir los primeros 70 bites en el primer alloc y los últimos 10 bytes en el alloc numero dos. Esto deberia darme un error, ya que en teoria yo mando a escribir una porción de un bloque de memoria especifico que yo solicite con anterioridad, o me estoy confundiendo y esto debería estar contemplado.

Respecto al enunciado, no me deja bien claro esta situación

> Es menester aclarar que es posible escribir los datos en cualquier parte de la memoria, por lo tanto la información (incluido el HeapMetadata) puede quedar dividida en múltiples páginas, dado que el tamaño máximo no está limitado por el tamaño de las páginas. Este comportamiento es esperado y es responsabilidad del grupo manejarlo.

Muchas gracias.

**Comment by gastoncastineira** [comment]
> Entonces, primer caso, si yo recibo memwrite con los parámetros puntero=30 size=50. Entonces debería escribir el primer alloc desde el byte 30 hasta el 80.

Es correcto

> Segundo ejemplo, recibo un memwrite con parámetros puntero=30 size=80. Entonces, ante esta situación, debería escribir los primeros 70 bites en el primer alloc y los últimos 10 bytes en el alloc numero dos. Esto deberia darme un error, ya que en teoria yo mando a escribir una porción de un bloque de memoria especifico que yo solicite con anterioridad, o me estoy confundiendo y esto debería estar contemplado.

No. En ese caso vas a escribir los 70 bytes, pisar los 9 del siguiente metadata y escribir un byte más. Sí, en el proceso vas a estar rompiendo la consistencia de los allocs, pero aunque no lo creas es el mismo comportamiento que tiene malloc. Más allá de eso, no creo que vaya a ser una prueba. El error de escritura apunta a acceder a marcos/páginas que no sean de tu carpincho (error mejor conocido como segmentation fault quizá)

**Comment by RodrigoLista** [comment]
Perfecto. Entonces no se daria un caso asi. Unicamente el ya comentado, en el que por ejemplo el carpincho tiene 5 paginas, y se envie una direccion que se corresponderia con una pagina numero 10. Me quedo claro, muchas gracias.
