### ISSUE TITLE
Consulta sobre NULL como posible valor de retorno para mate_memalloc

### ISSUE THREAD

**Issue by NicolasWallovits** [sisoputnfrba/foro#2407]
Hola, tengo una consulta particularmente para lo que sería el valor de retorno NULL para la función de mate_memalloc. Siendo que el encabezado de la función especifica que retorne un valor del tipo mate_pointer (que en realidad es un int32_t), ¿qué es lo que se espera cuando se pide que el valor de retorno sea NULL? Lo pregunto en realidad porque al dar un return NULL se levanta un warning, y no estoy seguro que NULL sea siempre = 0.

Gracias!

### 📔 Citas del enunciado/videos

> Recordar que el método debe retornar la dirección lógica al inicio de la reserva de espacio; y en caso de que no haya más espacio (tanto memoria como en swap), se denegará la operación haciendo que la biblioteca devuelva la dirección NULL.

Encabezado en matelib.h:

typedef int32_t mate_pointer;
mate_pointer mate_memalloc (mate_instance *lib_ref, int size);

### 💭 Soluciones posibles

a. Lo dejamos como return NULL; con un hermoso warning de "return makes integer from pointer without a cast..."
b. Lo tratamos como un 0, entonces interpretamos que return 0; es devolver NULL
c. Se agrega como un código más en el enum mate_errors

**Comment by iago64** [comment]
Buenas! Cómo va?

NULL es la representación de la dirección 0x0 (0 en Hexa), con lo cual, devolver 0 o NULL es exactamente lo mismo 😄  

Saludos.-

**Comment by NicolasWallovits** [comment]
Buenísimo. Gracias!
