### ISSUE TITLE
Memoria: exceso del tamaño del marco

### ISSUE THREAD

**Issue by joseZudaire** [sisoputnfrba/foro#2408]
Buenas! Quería consultarles que pasaría en el caso de que se cumpla lo que sucede en el diagrama del TP:
![image](https://user-images.githubusercontent.com/38169207/140810170-321a608e-c084-4c5d-bdf4-5b11d3fac194.png)

Acá tenemos un alloc que excede el tamaño del marco, entre el Marco 0 y 1. Ahora, supongamos que se hace un swapeo del marco 0 y lo pasamos a Swamp. Después supongamos que hacemos otro swapeo del marco 1 y también lo pasemos a Swamp. En el caso de que necesite hacer un memread, y traiga de vuelta el marco 0, ¿cómo haría para leer toda la información? Dado que el marco 1 lo tengo en Swamp.

**Comment by ncoen97** [comment]
Buenas!
Si en el `memread()` el offset + tamaño es mayor a 3 (o en otras palabras, se está queriendo leer algo de la pag 1), van a tener que también traer de swap la página 1.
Saludos.

**Comment by ncoen97** [comment]
Y para estar seguro de que no la están pifiando, quería aclarar que cuando decís "pasamos la página a swamp", en realidad lo único que se hace es sacarla de memoria principal.

**Comment by joseZudaire** [comment]
Buenísimo, muchas gracias!
