### ISSUE TITLE
duda con reemplazo LRU

### ISSUE THREAD

**Issue by alejcha** [sisoputnfrba/foro#2409]
Buenas tardes, surgio una duda al aplicar el metodo de reemplazo LRU, este considera que los marcos hayan sido modificados para enviar o no la pagina a swamp (solamente no lo tiene en cuenta al momento de elegir victima)?
o sea supongamos que la victima no fue modificada, no necesitaria mandarla a swamp, simplemente la marco como invalida y reemplazo el frame

gracias

**Comment by LeandroCarbajales** [comment]
Buenas!
Así es, la página solamente se necesita escribir en SWAP si la misma tiene el bit de modificado en 1, esto es indiferente al algoritmo de sustitución.

Saludos!
         Lean

**Comment by alejcha** [comment]
perfecto, muchas gracias
