### ISSUE TITLE
[Deadlock] Dudas varias

### ISSUE THREAD

**Issue by federiver91** [sisoputnfrba/foro#2410]
Buenas, intentando implementar el módulo (hilo) checker de Deadlock me surgen algunas consultas:

1) Qué pasa con los recursos que un carpincho tomó (semaforos a los que les hizo wait) al momento de finalizarse a sí mismo o que los mate el algoritmo de recuperación de Deadlock? Deberían reponerse dichos semáforos? Quién lo haría?

2) Podrían tirarme un centro de dónde me conviene resguardar la información de ejecución para que me sea más fácil manejar los carpinchos bloqueados y los recursos que tienen tomados?
Supongamos el siguiente caso de uso
C1 hace wait del Sem1 --> OK
C2 hace wait del Sem2 --> OK
C1 hace wait de Sem2 --> Se bloquea C1
C2 hace wait de Sem1 --> Se bloquea C2

Conviene guardar una lista de carpinchos bloqueados en las estructuras de cada semaforo para saber qué semaforo es el que bloqueó a cada carpincho? O conviene guardar en una lista que tenga (ID carpincho, Id Semaforo, Cant Solicitadas)? Pero en esta segunda opcion, cómo se qué Semáforo hace que se bloquee el Carpincho?

Basicamente no puedo darme cuenta la mejor manera de tener ambas informaciones disponibles (los recursos que retiene y el recurso que bloquea a un carpincho).

Y al margen de cómo tener toda la info disponible en una lista/matriz, mi cabeza no llega a tanto como para que se me ocurra el ALGORITMO a desarrollar para detectar la espera circular.

Un ayudin?

Gracias!

**Comment by gastoncastineira** [comment]
Buenas!

> Qué pasa con los recursos que un carpincho tomó (semaforos a los que les hizo wait) al momento de finalizarse a sí mismo o que los mate el algoritmo de recuperación de Deadlock? Deberían reponerse dichos semáforos? Quién lo haría?

Desde lo que ven en la teoría, cuando un proceso termina, indistintamente del motivo, el SO recupera todos los recursos que ese tuviera ocupados. Cuando algún carpincho termine, el kernel debería tener un comportamiento similar

> Conviene guardar una lista de carpinchos bloqueados en las estructuras de cada semaforo para saber qué semaforo es el que bloqueó a cada carpincho? O conviene guardar en una lista que tenga (ID carpincho, Id Semaforo, Cant Solicitadas)? Pero en esta segunda opcion, cómo se qué Semáforo hace que se bloquee el Carpincho?

No veo por qué no puedan ser ambas. Para detectar la espera circular no te queda otra que, por cada carpincho bloqueado fijarse si en alguno de sus recursos, alguno de los carpinchos que lo están esperados tiene tomado un recurso que ese primer carpincho esté esperando. Es mucho más sencillo recorrer todas esas listas si la relación carpincho-semáforo es bidireccional

**Comment by federiver91** [comment]
Buenas! GRacias por la respuesta!

Y en cuanto al tamaño o alcance de los Deadlocks, tenemos que hacerlo y pensarlo genérico considerando la posibilidad de que hayan N carpinchos en deadlock con espera circular? O podemos limitarlo a deadlocks cruzados de solo 2 carpinchos?

Esta definición cambia mucho lo que pensamos inicialmente como algoritmo.

**Comment by iago64** [comment]
Buenas! Cómo va?

Tienen que pensarlo para el caso genérico de que tengan N carpinchos en deadlock.

Saludos.-

**Comment by LeandroCarbajales** [comment]
> Y al margen de cómo tener toda la info disponible en una lista/matriz, mi cabeza no llega a tanto como para que se me ocurra el ALGORITMO a desarrollar para detectar la espera circular.

Para agregar algo a esto, les tiro un par de tips conceptuales para que no se sobrecompliquen el algoritmo, a diferencia de los recursos genéricos que vemos en la teoría donde se puede tener instancias disponibles y peticiones pendientes de distintos recursos, en este caso un carpincho podría estar bloqueado (y por lo tanto con peticiones pendientes) de 1 sola instancia de 1 solo recurso (el semáforo por el que se bloqueó), además, evidentemente en este caso no tendrían instancias disponibles de ese semáforo (sino no tendría carpinchos bloqueados). Por lo tanto, para el caso acotado del tp, es suficiente encontrar un "ciclo" entre los carpinchos bloqueados y sus peticiones para que haya deadlock.
Una primera iteración podría ser agarrar cualquier semáforo con carpinchos bloqueados, agarrar uno de esos y ver qué semáforos tiene "asignados" (es decir, que hizo wait() y pasó), ir a esos semáforos y ver quienes están bloqueados e ir haciendo la cadena, si por alguna de esas cadenas volvés al semáforo por el que arrancaste, esos carpinchos en la cadena están en deadlock. Para visualizarlo mejor podés pensarlo como lo vemos en la teoría como un digrafo con recursos y procesos.

Espero que te ayude a empezar a implementarlo, si necesitás alguna mano más con eso capaz te conviene pasarte por soporte mañana para verlo más en detalle :)

Saludos!
          Lean

**Comment by federiver91** [comment]
Buenas!

Gracias por el input. Estuve envejeciendo estas últimas horas con este último approach pero realmente me es imposible de codear esa "cadena".

Es sencillo de explicar, pero implementarlo de manera genérica para N semaforos, con M procesos bloqueados, con P semaforos asignados a ellos, con Q procesos bloqueados cada uno de esos P semaforos, con R semaforos asignados a esos Q procesos y así seguir e iterar cada lista hasta que cerras un ciclo **encontrando que un semaforo** de esas cantidades INCIERTAS en las que vas entrando en cada nivel (porque cada iteración es un nivel de profundidad tipo Inception) **es igual al original** por el que arrancaste es REALMENTE algo que escapa a mis neuronas (y creería que a los fines y contenidos de la materia tambien, pero buen... esa será otra discusión).

No hay alguna alternativa o algoritmo pre-fabricado que detecte deadlocks?

Repito, lo que complica es la relacion uno a muchos de cada entidad, lo que hace que tengas que ir iterando listas con distintos niveles de profundidad.
![image](https://user-images.githubusercontent.com/49326422/141540145-1fa76e67-94c1-4213-b614-787b44aa153f.png)


Si fuera acotado a un deadlock cruzado de 2 semaforos y 2 procesos, ya lo tengo resuelto. Aunque es un choclo de logica inentendible.

Hacerlo extensivo ya me es imposible porque desconoces hasta qué nivel de profundidad iterar.

**Comment by LeandroCarbajales** [comment]
Buenas!
Capaz fui muy literal con lo de la cadena, digamos, al menos a mi me sirve para visualizar las distintas posibilidades como digrafo. Pero acordate que en definitiva vos tenés una cantidad fija de carpinchos bloqueados, y una igual (o menor) cantidad de semáforos involucrados (ya que no podés estar bloqueado por más de 1) que se pueden determinar iterando 1 vez sola tus listas, no tenés por qué hacer una implementación recursiva ni nada por el estilo que pueda exceder los objetivos del trabajo práctico.
Igual genial que lo hayas podido plantear aunque sea para 2 semáforos y 2 procesos, pero que extrapolarlo a 3 semáforos y 3 procesos (por ejemplo) se te haga imposible me suena a que capaz algún dato o concepto teórico no estás teniendo en cuenta al plantear el algoritmo o tus estructuras y que eso te lo sobrecomplique.
Creo que lo más práctico sería que te pases mañana por Discord así podemos tener más ida y vuelta, a veces estas cosas es difícil plasmarlas bien por texto.

Saludos!
         Lean

**Comment by federiver91** [comment]
Gracias Lean!
