### ISSUE TITLE
Duda bloqueo de procesos con semáforos

### ISSUE THREAD

**Issue by ivanscardaoni1** [sisoputnfrba/foro#2411]
Hola! Va mi consulta, se que hay algo parecido a la consulta que voy a hacer en este hilo https://github.com/sisoputnfrba/foro/issues/2395 , pero todavía tengo dudas:

Los mate_sem (estructura que creamos en el sistema que tiene un nombre y un valor y esta en una lista de semáforos inicializados) tienen su propia cola de bloqueados (o sea un campo que sea una lista que tiene aquellos PCBs que hacen uso de ese semáforo en orden por cual fue el que se bloqueo primero)?

O los procesos pasan a la cola de bloqueados general? 

La pregunta va porque si se le hace signal y wait a un semáforo desde un proceso u otro, hay que desbloquear en relacion a ese semáforo en particular.

Otra cosa que se me ocurre es que tal vez podrían estar en ambas colas de bloqueados (la del semáforo y la de blocked general), ya que además de saber cual desbloquear cuando se hace un signal a un semáforo en especifico, también debería dejar trabajar al planificador de mediano plazo (que trabaja con la cola de blocked suspendiendo aquellos procesos bloqueados tanto por call_io como por un wait a un semáforo en cero).

Quisiera saber si estoy muy errado con la ultima alternativa!

Muchas gracias!

**Comment by mesaglio** [comment]
Buenas, creo que tu última alternativa es válida ya que los proceso que fueron bloqueados por hacer waits a semáforos con valor 0 o negativo, se van a tener que ir desbloqueado en orden. 

Creo que sería muy difícil mantener este orden entre todos los semáforos y todos los proceso.

Salu2!

**Comment by ivanscardaoni1** [comment]
Perfecto, muchas gracias!
