### ISSUE TITLE
Duda sobre direcciones lógicas en ram

### ISSUE THREAD

**Issue by study64** [sisoputnfrba/foro#2412]
Hola que tal, tengo una duda que creo que es mas de teoría que del tp pero me ayudaría mucho si me contestan. ¿Las direcciones lógicas       son exclusivas de cada carpincho/proceso o son únicas en toda la ram? 

O sea ¿cada carpincho puede tener una dirección  00000001 o esa dirección solo se asigna al primer alloc que llegue?

No se si me explique. Gracias

**Comment by mesaglio** [comment]
Las direcciones lógicas en paginacion vienen dadas por numero de pagina + offset.

Como cada carpincho tiene su propia tabla de paginas lo que vos planteas es correcto, cada carpincho puede tener una dirección 00000001.

**Comment by study64** [comment]
perfecto gracias
