### ISSUE TITLE
Duda sobre el alloc en swamp

### ISSUE THREAD

**Issue by joaquinipar** [sisoputnfrba/foro#2413]
Hola, ¿Cómo están?

Quiero hacer una consulta acerca del ALLOC de SWAMP.

Cuando hago un alloc en swamp, yo pense que recibe un ID de proceso y la cantidad de bytes a allocar. La pregunta es, debería hacer un alloc genérico como lo estoy pensando yo? ( y que luego el proceso pueda escribir CUALQUIER pagina en ese marco)

o el alloc tiene que estar reservado para una pagina X?.

O sea, en ese caso recibiría un ID de proceso, cantidad de bytes y una pagina en particular.

Saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

Todo lo referente a datos (si, incluso los heap metadata son parte de los datos del usuario) dentro de la memoria esta dentro de las páginas, por algo aclaramos que el tp va a usar un esquema de _paginación_ y por lo tanto cada carpincho va a tener sus páginas propias y estas van a estar en los frames correspondientes.

Saludos.-

**Comment by joaquinipar** [comment]
Hola @iago64 ,

No se si no entendi bien la respuesta, pero la pregunta iba mas por el lado de la selección del marco a la hora de escribir en swamp.

A mi no me quedo claro si al allocar un marco, ese marco va a ser para el proceso y una pagina en particular, o para cualquier pagina de ese proceso.

Saludos!

**Comment by iago64** [comment]
Buenas!

Ahora si, pense que venia por el lado del memalloc() y los heapMetadata 😄 

Los "frames" en swap, los vas a asignar al igual que los asignas en memoria principal, un "frame" de swap va a ser para una página de un proceso, ya que después vos lo que llevas a memoria principal es una copia de esa página, pero nunca la borras de swap hasta que termina el proceso.

Saludos.-

**Comment by joaquinipar** [comment]
Genial entonces, muchas gracias!

Cierro.
