### ISSUE TITLE
Duda Allocs Memoria

### ISSUE THREAD

**Issue by matiasferrerovilas** [sisoputnfrba/foro#2414]
Me surgió una duda, avanzando en memoria, ¿los allocs son contiguos?
Ejemplo.
En el enunciado tengo que mi 2do alloc está en la página 0 y la 1. ¿Es posible que justo la pagina 1 este ocupada, y tenga que ir a la página 2?
quedando mi "header" y un poco del contenido en la página 0, y de ahí salte a la página 2?

![imagen](https://user-images.githubusercontent.com/27780879/141375479-5706b0bd-a495-4a57-8a6a-13d48b75126c.png)

**Comment by ncoen97** [comment]
Buenas.
Los allocs son contiguos en las páginas (vista lógica del carpicho), pero pueden no ser contiguos en los frames de la memoria. Por ejemplo, puede ser que la página 0 esté en el marco 5 y la página 1 en el marco 2, o que alguna no esté y haya que irla a buscar a swamp.
Saludos!

**Comment by matiasferrerovilas** [comment]
ok ok, entonces esta bien el pensamiento siguiente:
Teniendo una pagina de tamaño 32.
Mi carpincho hace un alloc de 5.
Yo creo una pagina y cargo los heap metadata correspondiente.
Esto me deja la pagina 1 con 9 de espacio libre
A) Si hago otro alloc de 10
   Deberia generar un alloc que ocupe 9 bytes en la pagina 1 y otro que ocupe 1 en la pagina 2, verdad?
B) Si tengo la pagina 1 y 2. siendo la pagina 1 como el ejemplo de A. Entonces cuando me haga un alloc de 10 no deberia poder poner en la pagina 1, porque la pagina 2 esta ocupada, deberia generar una pagina nueva, no?

**Comment by ncoen97** [comment]
Disculpá pero no entendí del todo las opciones., igualmente quedaría algo así:

![image](https://user-images.githubusercontent.com/7952790/141405549-d0a22ee7-850b-4b3f-96e7-ac28979e878d.png)

**Comment by matiasferrerovilas** [comment]
ok perfecto gracias nico!.
A una ultima duda yo guardo la direccion verdadera de memoria? o pongo la direccion respecto a la que me da.
ej:
al hacer void* memoria -> esto me da la direccion 134542256
Entonces cuando hago mi alloc tiene que apuntar el prev alloc al inicio, en este caso es 134542256, aca pongo ese 134542256 o pongo 0?.

**Comment by iago64** [comment]
Buenas!

Idealmente las direcciones que van a manejar en nextAlloc y prevAlloc son direcciones lógicas, tene en cuenta que si la página la mandas a swap, puede no volver en el mismo lugar físico que estaba al momento de crearse 😉 

Saludos.-

**Comment by matiasferrerovilas** [comment]
Perfecto. Una ultima duda,
Al iniciar mi carpincho, y este no tiene ninguna pagina, y necesita pedir una pagina, esta debe pedirla a swap y swap me la retorna una pagina vacia con el numero de marco correspondiente?.
Porque no se cuando o como obtener el frame de la pagina en cuestion.

**Comment by iago64** [comment]
Buenas!

El frame en cuestión lo va a decidir la memoria principal, ahora cual va a ser, dependerá mucho del esquema de asignación, ya que si es asignación fija, tu carpincho va a tener un set de frames pre fijados para elegir y a lo mucho va a tener que reemplazar sobre ese set de frames. Si es asignación global, va a ser cualquiera de la memoria principal que se va a determinar como el primero libre o el que resulte de la elección de victima por el algoritmo de reemplazo.

Saludos.-

**Comment by matiasferrerovilas** [comment]
ahh entonces, algo que no me queda claro. 
Yo en memoria genero los marcos y los asigno a las paginas una vez solicitadas?

**Comment by iago64** [comment]
Buenas! Cómo va?

La memoria inicia con N marcos libres (donde N sale de dividir el tamaño de la memoria por el tamaño del marco) y despues vos vas asignando esos marcos a las páginas a medida que lo vas necesitando.

Saludos.-

**Comment by matiasferrerovilas** [comment]
Muchas gracias por la respuesta. El flujo seria masomenos asi entonces?.

1. inicializo mi tabla con todos los marcos libres.
2. Cuando se conecte un carpincho y haga un alloc, este primero se fija si no supero la cantidad maxima de marcos permitidos y si no supero ahi le asigna la pagina en el primer marco disponible. Si tiene la cantidad maxima ahi deberia llamar a swa y ahi usar Clock o LRU.

**Comment by iago64** [comment]
Buenas!

Si señor, ese sería el flujo de la memoria, solo te falto el punto de que cuando se cree una página nueva tenes que crearla tanto en swap como en memoria principal, porque lo que tenes en memoria principal es una copia de swap.

Saludos.-

**Comment by matiasferrerovilas** [comment]
Excelente, y una ultima duda. Los marcos que yo cree en memoria coinciden con los marcos que se hacen en swap?

**Comment by iago64** [comment]
Buenas!

Los marcos en memoria principal y en swap van a ocupar el mismo tamaño, en cuanto a la correlación numérica, no, acordate que la idea teórica de swap es ampliar el espacio para alojar procesos reduciendo los "costos" de tener que poner mas ram.

Saludos.-

**Comment by matiasferrerovilas** [comment]
Perfecto muchas gracias.  No tengo mas dudas por ahora.

**Comment by iago64** [comment]
Buenisimo! cerramos el issue entonces :)
