### ISSUE TITLE
Punteros

### ISSUE THREAD

**Issue by ivanscardaoni1** [sisoputnfrba/foro#2415]
Hola! Estoy teniendo un problema con un manejo de punteros. Les comento:

Estamos haciendo unas funciones que lo que hacen es, desde la mateLib "pedir permiso para continuar" y "recibir permiso para continuar".
Y desde el planificador "recibir petición de continuación" y "dar permiso de continuación".

Ambas "dar permiso de continuación" y "pedir permiso para continuar" son idénticas.
Y "recibir petición de continuación" y "recibir permiso para continuar" también lo son.

La idea es con estas funciones manejar el flujo de ejecución de los carpinchos. Pero debido a un mal manejo de punteros me esta tirando un seg fault en una sección.

Necesito ayuda para poder asegurarme de que estoy enviando bien el mensaje y que esta siendo bien recibido.

Desde ya muchas gracias!

### 📝 Código relevante

Les dejo las 2 funciones y el lugar donde tira el Seg Fault

    void dar_permiso_para_continuar(int conexion){

	    t_paquete* paquete = malloc(sizeof(t_paquete));

	    int* permiso = malloc(sizeof(int));

	    (*permiso) = 1;

	    paquete->codigo_operacion = PERMISO_CONTINUACION;
	    paquete->buffer = malloc(sizeof(t_buffer));
	    paquete->buffer->size = sizeof(int);
	    paquete->buffer->stream = malloc(paquete->buffer->size);
	    memcpy(paquete->buffer->stream, permiso, paquete->buffer->size);

	    int bytes;

	    void* a_enviar = serializar_paquete(paquete, &bytes);

	    send(conexion, a_enviar, bytes, 0);

	    free(a_enviar);
	    free(permiso);
	    eliminar_paquete(paquete);

    }

     void recibir_peticion_para_continuar(int conexion) {

	    recibir_operacion(conexion);

	    void* buffer;
	    int size;

	    recv(conexion, &size, sizeof(int), MSG_WAITALL);
	    buffer = malloc(size);
	    recv(conexion, buffer, size, MSG_WAITALL);

	    int* mensaje = malloc(size);

	    printf("Llegoooooo\n");

            ACA TIRA SEGMENTATION FAULT, TANTO EN EL LADO DEL CARPINCHO COMO DEL KERNEL

	    memcpy((void*)mensaje, buffer, size);

	    printf("Permiso para continuar: %d\n", (*mensaje));

    	    free(mensaje);

    }

### 💻 Logs
Del lado del kernel

    Listo para escuchar a mi cliente
    Cree un procesador
    Cree un procesador
    Ya cree el planificador de largo plazo
    Ya cree el planificador de corto plazo
    Se conecto un carpincho usando la mateLib
    Llegoooooo
    Violación de segmento (`core' generado)

Del lado del carpincho

    conexion: 3
    Ya pedi permiso
    Llegoooooo
    Violación de segmento (`core' generado)

**Comment by iago64** [comment]
Buenas! Cómo va?

Cualquier cosa relacionada a memoria, de entrada te diría que lo revises con valgrind ya que los logs que impriman uds poco nos pueden aportar para saber que puntero les falto o que dato capaz escribieron mal.

Por las dudas revisate en el canal de [youtube](https://youtube.com/c/utnso) que tenemos un video de una charla de 2019 donde hablamos sobre valgrind y los mensajes que te puede dar.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @ivanscardaoni1 ! ¿Alguna novedad sobre el bug? ¿Pudiste probarlo con Valgrind como sugirió Dami? Saludos

**Comment by ivanscardaoni1** [comment]
Hola! Si, lo hice y me salteo el error y continuo con la ejecución normalmente, vi que es algo que puede pasar, de todas maneras, encontré otra forma de asegurarme que lo que estoy mandando y lo que se esta recibiendo es correcto! Muchas gracias a ambos!
