### ISSUE TITLE
Consultas Deadlock

### ISSUE THREAD

**Issue by iribs97** [sisoputnfrba/foro#2416]
¡Buenas! Estamos empezando a plantear el deadlock y tenemos algunas consultas:

1. Nuestra idea inicial es guardar en una lista los semáforos a los que un carpincho le hizo wait pero no post para luego validar junto con los procesos que están bloqueados por semáforos si hay espera circular. ¿Estaría bien encararlo así?
2. Después teníamos una duda respecto a los carpinchos que matamos para solucionar el deadlock. ¿Les envíamos un mensaje de fail y después les rechazamos todas las peticiones que nos hagan ya que para nosotros ya no existe más? 
3. ¿Qué pasa con los semáforos involucrados en el deadlock? ¿Tenemos que hacerle un falso post cada vez que matemos a un proceso que estaba bloqueado por ese semáforo?

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Si, es una de las posibles formas, otra forma que puede darse es que lo encaren a la inversa, partiendo desde los carpinchos bloqueados y buscando a los que retienen el semáforo por el cual esta bloqueado y ver si en algún momento siguiendo ese camino completan el ciclo.

2.- Es una opción, otra opción que tienen es cerrarle directamente el socket y listo.

3.- Si, al desalojar a un proceso / carpincho de su semáforo porque lo están finalizando, tendrían que hacer la lógica del post para desbloquear al primero de la lista de bloqueados por ese semáforo.

Saludos.-

**Comment by iribs97** [comment]
¡Genial! Muchas gracias por la info. 

Una consulta más... cuando estamos corriendo el algoritmo de deadlock y solucionandolo si es necesario, ¿deberíamos pausar la ejecución y planificación de carpinchos?

**Comment by iago64** [comment]
Buenas!

Pausar la planificación de que carpinchos? Porque los que están involucrados en el deadlock van a estar bloqueados y no van a poder hacer nada mas que esperar y son solo esos los que te importan 😉 

Saludos.-

**Comment by iribs97** [comment]
¡Buenisimo! Gracias por la respuesta
