### ISSUE TITLE
Deadlock - Estado de carpincho

### ISSUE THREAD

**Issue by Mdavicino** [sisoputnfrba/foro#2417]
Buenas!
Terminando la parte de deadlock nos surgió una duda con respecto a que debería pasar con la ejecución del carpincho una vez que el algoritmo de detección y recuperación lo elige como víctima. 
En el soporte nos habían comentado de que deberíamos mandarle a la matelib algún código de error que haga que se libere la mate_instance, pero el problema con esto es que deberíamos de alguna forma detener la ejecución del carpincho porque sigue y rompe al llamar nuevamente a la matelib con una mate_instance que fue eliminada.
Una opción que habíamos pensado previamente era dejarlo clavado en el recv del wait, pero ahí no se liberaría la mate_instance.

En resumen, en que estado debería quedar el carpincho y su ejecución una vez que se lo "termina" debido a un deadlock?

**Comment by iago64** [comment]
Buenas! Cómo va?

Una opción muy fácil que tienen es simplemente cerrar el socket y que el carpincho "no pueda hacer mas peticiones", lo que les importa a nivel kernel es que el carpincho no siga ejecutando, como lo hacen, siéntanse libres de buscar una solución creativa.

Saludos.-

**Comment by Mdavicino** [comment]
Buenas!
Muchas gracias!

Cierro el issue
