### ISSUE TITLE
HeapMetadata: como representar el NULL

### ISSUE THREAD

**Issue by Camila1401** [sisoputnfrba/foro#2418]
Buenas tardes! 

Me surgió una duda en como representar el NULL en el heapmetadata. En un principio había pensado en 0, pero cuando se trata de, por ejemplo el primer heap_metadata, que tiene el prevAlloc en NULL, se guardaría 0 y eso no me indicaría que estoy en el primer heap de todos ya que sería la siguiente situación (en donde el segundo heap también tiene el prevAlloc = 0):

![image](https://user-images.githubusercontent.com/62361275/141655515-4bea569a-b9a8-4773-a8fe-243d58bade7b.png)

Entonces, si yo quiero corroborar que se trata del primer heapMetadata cuando prevAlloc = NULL utilizando 0 no me serviría. Como debería implementarlo para manejarlo de manera correcta? 

Saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

Una linda forma de representar ese null puede ser un -1 😉, igual puede haber mil formas mas y muy posiblemente en todos los casos va a estar bien, lo importante es que a uds les sirva para identificarlo.

Saludos.-

**Comment by Camila1401** [comment]
También había pensado en esa posibilidad, pero el tipo del prevAlloc es uint32_t por lo que no admite números negativos. No se me ocurre como manejarlo para detectar inequívocamente que se trata del primer heap_metadata.

**Comment by iago64** [comment]
Buenas!

Que sea uint32_t no te impide asignarle -1, simplemente cambia como te lo puede interpretar, al final del día para C un int32_t, o un uint32_t, son tipos de dato numero que ocupan 4 bytes 😄 

Saludos.-

**Comment by Camila1401** [comment]
Ahh buenísimo, entonces uso -1. Pensé que usar valores negativos con uint32_t me podría llegar a traer problemas al momento de querer usar ese dato y que se haya guardado cualquier otro valor.

Muchas gracias por la respuesta! 
Saludos :)

**Comment by tferraro** [comment]
> Paso por acá nomás a modo de 👮‍♂️ para asegurarnos de que si quedó solucionado, no dejemos el ticket abierto 🤣
