### ISSUE TITLE
Un Edge Case de alloc

### ISSUE THREAD

**Issue by study64** [sisoputnfrba/foro#2419]
Hola que tal, quería saber como debe reaccionar el módulo RAM en el siguiente caso:

![image](https://user-images.githubusercontent.com/8770961/141656649-0aa3360a-4e2a-49b8-be4b-421984a3e186.png)

Supongamos que necesito hacer un alloc de 10 bytes, Si bien dispongo de los 10 bytes (de hecho dispongo de 15) no me alcanza para los 10 + los 9 del HeapMetada. ¿Qué se hace en este caso? Gracias.

**Comment by iago64** [comment]
Buenas! Cómo va?

En ese caso no entra y deberías seguir buscando un hueco, la regla es:

tamaño a reservar igual al espacio libre
o
tamaño a reservar menor o igual a espacio libre -9

Cualquier cosa que quede entre medio de esos 2 casos, simplemente no entra 😄 

Saludos.-

**Comment by tferraro** [comment]
☝️ Es más, fijate que es una cagada perder ese espacio, pero _que le vamos a hacer, no?_

Es la forma más óptima? Pues claro que no. Existen varios mecanismos para solucionar esos problemas, algunos se ven en la materia, pero no son obligatorios laburarlos en el TP porque el cuatrimestre solo tiene 4 meses 😛

**Comment by study64** [comment]
ok, muchas gracias
