### ISSUE TITLE
Acceso a los HeapMetadata

### ISSUE THREAD

**Issue by study64** [sisoputnfrba/foro#2421]
Hola, hoy estoy medio molesto con las preguntas pero me surgió la siguiente duda.  ¿la única forma en que puedo recorrer los Heap Metadata para controlar algún valor es partiendo desde la posición 0 y "siguiendo el trencito"? ¿o puedo usar algún tipo de estructura auxiliar para referenciarlos? Porque sino si por ejemplo quiero hacer un memwrite a partir de una dirección lógica que está en la página 5, para saber si esa es una dirección válida para escribir yo tengo que cargar a memoria (si no lo estuvieran ya) las paginas 1, 2, 3 y 4 para poder seguir el caminito y ver si la dirección lógica pertenece a un alloc. ¿se entiende? ¿me estoy perdiendo algo? Gracias por su ayuda.

**Comment by iago64** [comment]
Buenas! Cómo va?

Para la parte de los memalloc, efectivamente, tienen que seguir como dijiste, el trencito.

Para los memwrite, memread y memfree, simplemente la prueba va a estar orientada a algo totalmente fuera de la memoria del carpincho.
Un ejemplo rápido, si tenes páginas 4 de 100 bytes (para hacer números redondos nomas) y el read, write o free te llega en el byte 685, sabes que esta mal, que dicho sea de paso es lo que pasa en la realidad. 
Si estas dentro de tu memoria, memcpy (que es memread y memwrite combinados) hace lo que vos le digas, después si rompiste algo en el medio, problema tuyo (y es donde aparece el grandioso valgrind).

Saludos.-

**Comment by study64** [comment]
o sea si quieren romper, por ejemplo escribiendo en una dirección que corresponde a un Heap Metadata o que pertenece a una página pero no tiene alloc ¿lo permito?

**Comment by iago64** [comment]
Como sabes que no tiene un alloc? Si a vos solamente te va a llegar una dirección lógica? 😉 

De nuevo, el punto es que no escriba en memoria que no te pertenece y el So mira las cosas a nivel páginas, ya que estas en un esquema de paginación.

Saludos.-

**Comment by study64** [comment]
"Como sabes que no tiene un alloc? Si a vos solamente te va a llegar una dirección lógica?"
Porque lo puedo calcular con los Heap Metadata.

Pero bueno me dedico solo a controlar que no orinen fuera de la página. Gracias por su ayuda.
