### ISSUE TITLE
[Memoria] Memwrite en un HeapMetadata

### ISSUE THREAD

**Issue by Juyah** [sisoputnfrba/foro#2423]
Hola, buenos días.
La duda es en base a la siguiente respuesta de otro issue: https://github.com/sisoputnfrba/foro/issues/2421#issuecomment-968436715

Según entiendo se permite a que se escriba en un HeapMetadata o incluso leerlo, siempre y cuando sea dentro del limite de sus paginas?
Tengo entendido que la escritura sobre un HeapMetadata haría que se rompa la estructura para poder hacer nuevos allocs correspondientes a ese carpincho.

Saludos.

**Comment by iago64** [comment]
Buenas!

Efectivamente, mientras sea dentro de la memoria del carpincho, pueden escribir lo que sea.
Es un problema? Si, es un problema pero no de uds, si no de los changos que codearon el carpincho, parecido a como pasa cuando en C usamos mal la memoria y después un free nos explota y nos tira el clásico error de `double free or corruption` 😉 

Saludos.-

**Comment by Juyah** [comment]
Genial, muchas gracias!
