### ISSUE TITLE
Duda sobre mate_sem_destroy

### ISSUE THREAD

**Issue by NicolasWallovits** [sisoputnfrba/foro#2424]
Hola! Me queda una duda relacionada al mate_sem_destroy. ¿Qué deberíamos hacer en el caso que se pida destruir un semáforo, y exista un carpincho que tenga instancias de ese semaforo tomadas o incluso esté bloqueado por él?

Gracias!

### 💭 Soluciones posibles

a. No permitimos que se destruya un semaforo si sabemos que hay carpinchos que lo están usando
b. Destruimos el semaforo igual y dejamos al carpincho posiblemente bloqueado por la eternidad
c. Se lo expropiamos a todos los carpinchos, desbloqueamos a aquellos que lo estaban esperando, y después recién destruimos el semaforo

**Comment by iago64** [comment]
Buenas! Cómo va?

Algo copado de que este TP este super pegado a la teoría es que podemos por ejemplo revisar el [`man` de `sem_destroy()`](https://man7.org/linux/man-pages/man3/sem_destroy.3.html) y vemos que nos tira algo re copado que es:

> Destroying a semaphore that other processes or threads are currently blocked on (in sem_wait(3)) produces undefined behavior.

Con lo cual, la respuesta ante la pregunta es: hagan lo que mas simple les resulte, no vamos a testearlo porque es algo que ni en la realidad se sabe como funciona y posiblemente varíe de versión a versión del kernel y/o de la biblioteca de semaphore 😄.

Saludos.-

**Comment by NicolasWallovits** [comment]
Bárbaro. Gracias!
