### ISSUE TITLE
Duda sobre Memalloc y Metadatas

### ISSUE THREAD

**Issue by lotuuu** [sisoputnfrba/foro#2425]
Como expresan en el issue #2372, cuando un alloc "entra justo" en un metadata ya existente, tiene que si o si crear un Metadata al final del tamaño ocupado igual. Por lo que entiendo, esto significa que al final del espacio de direcciones de un carpincho, en el final de la última página, siempre habrá un Metadata libre (en el peor de los casos, de tamaño 0). Con esto en cuenta, cuando un memalloc no encuentra espacio suficiente en ninguna de las páginas del carpincho y debe pedir nuevas, ¿habría que utilizar este último metadata aprovechando el espacio de la nueva página? ¿O se crea un nuevo Metadata en la primera posición de la nueva página, quedando este "al lado" del previamente mencionado, que mantiene su tamaño 0?

### 📔 Citas del enunciado/videos

> En caso de que no se encuentre, se deberá generar un nuevo alloc al final del espacio de direcciones, teniendo en cuenta que si no cabe en las páginas ya reservadas se deberá solicitar más.

**Comment by iago64** [comment]
Buenas! Cómo va?

Si un alloc entra justo en un hueco libre no hace falta que creen otro heap_metadata porque va a usar los 2 que ya tenía de antes.
El del final se refiere al caso donde vos creas un alloc y tenes que marcar inicio y fin del mismo, entonces si creas por ejemplo el primer alloc te va a quedar algo asi como:

Heap Metadata | Alloc | Heap Metadata

Con la salvedad de que el último heap_metadata siempre te va a decir que esta libre.

Saludos.-

**Comment by lotuuu** [comment]
Hola! Muchas gracias, malinterpreté el issue anterior entonces.

Solo para corroborar, eso significa que si yo necesito alocar 10 bytes:
- Si encuentro un metadata de exactamente 10 bytes libre, lo utilizo.
- Si encuentro metadatas de 11-18 bytes, no los utilizo porque no entraría otro metadata.
- Si encuentro un metadata de 19 bytes o más, y está libre, hago el alloc y divido el bloque en 2.

Esto es correcto?

**Comment by iago64** [comment]
Exacto, mas claro no pudiste decirlo 😄

**Comment by lotuuu** [comment]
Perfecto! Muchas gracias.
