### ISSUE TITLE
Dudas Evento Obligatorios - Memoria

### ISSUE THREAD

**Issue by BDIPAULO** [sisoputnfrba/foro#2426]
Buenas noches, 

En el caso del 1er alloc de un proceso que es nuevo. Si cumplimos con lo mencionando en este issue #2380  cuando entras en la TLB mas allá de incrementar el tlb miss,  no podríamos cumplir con este requerimiento del  evento de log obligatorio dado que no cuento con el dato del numero de la pagina  por ser la primera vez que alloca. 

### 📔 Citas del enunciado/videos
>Eventos de log obligatorio
Para poder conocer lo que ocurre dentro del módulo y poder llevar adelante un seguimiento claro, listamos a continuación los eventos mínimos de log que esperamos que tenga el módulo, esto no quita que los alumnos puedan extender el log agregando más información si lo ven necesario.
Conexión y desconexión de un cliente - Identificando qué carpincho se conectó.
TLB Hit - Indicando PID, Número de página y marco.
**TLB Miss - Indicando PID, Número de página.**
Reemplazo de una entrada indicando víctima y la nueva entrada, ambos con PID, Número de página y Marco en ambos casos.

Por favor me podrán informar que hacer.

**Comment by LeandroCarbajales** [comment]
Buenas!
Por qué no contarías con el número de página? En definitiva cómo sabés que es un hit o un miss si no tenés el número de página?
En el caso del primer alloc entiendo que escribirías tanto las direcciones correspondientes al primer heapMetadata como al "último", podés deducir los números de página diviendo esas direcciones por el tamaño de página. Por ejemplo, el primer heapMetadata seguro esté en la página 0.


Saludos!
        Lean

**Comment by BDIPAULO** [comment]
Buenas. 

Esto es lo que nos hace ruido. En el issue #2380 realice una consulta sobre el 1er alloc y lo que comprendimos es que cuando recibis un alloc tenes que ir a la tlb a buscar si tu proceso ya tiene una entrada cargada, Si es negativo buscarlo en TP y seguir el diagrama.  Por eso consulto esto del evento obligatorio. 
Me cerraba mas seguir el diagrama cuando haces un memread memwrite o memfree. No cuando haces un alloc.  

Puntualmente la duda es: 
1- Cuando allocas por primera vez seguís el diagrama de la teoria ??? 

Buscar en la TLB
Si es un miss buscar en la tabla de páginas
Si no esta en MP pedirlo a swap

**Comment by LeandroCarbajales** [comment]
Buenas!
El diagrama de traducción lo seguirías justamente para la parte que es leer y/o escribir páginas del proceso (en este caso, los heapMetadata) y toda la actualización de estructuras que eso implica, no necesariamente para otras operaciones que conlleve tu primer alloc como inicializar alguna entrada, etc.

Espero que te sirva la respuesta :)
Saludos!
       Lean

**Comment by BDIPAULO** [comment]
Buenas. 

Si ahí se comprendió la referencia del issue anterior.  
Gracias. Saludos
