### ISSUE TITLE
Posible condición de carrera en RAM y Duda con Free

### ISSUE THREAD

**Issue by study64** [sisoputnfrba/foro#2427]
Hola, por lo que entiendo del enunciado, el módulo de ram debe poder atender varias peticiones en paralelo (a nivel red), perfecto
 y swamp las peticiones de ram de una a la vez, también perfecto. Mi pregunta es ¿dos carpinchos pueden por ejemplo escribir la memoria al mismo tiempo? o a pesar de que las peticiones lleguen juntas yo uso un semaforo para que solo acceda a memoria uno a la vez?

edit: tambien me surgio una segunda duda. Al hacer free el enunciado dice que si la pagina se queda vacia esta debe liberarse, ¿eso aplica a la última página o también a páginas intermedias? O sea ¿si hago un free de un alloc cuyo Heap Metadata esta en la pag 1 y el siguiente en la pag 3, tengo que destruir la pag 2?

Saludos.

**Comment by iago64** [comment]
Buenas!

Interesante pregunta, la parte copada es que cada carpincho tiene su sección de memoria, con lo cual, 2 carpinchos no van a escribir "al mismo tiempo la misma memoria", pero si puede ser que empiecen a pelear por frames a la hora de correr el algoritmo de reemplazo, con lo cual, deberían sincronizar los accesos para no pisarse entre peticiones.

Saludos.-

**Comment by study64** [comment]
Hola que tal, no cerré el tema porque no me han respondido la segunda duda. Saludos

**Comment by iago64** [comment]
Buenas! Mil disculpas!

El liberar las páginas vacías solo aplica a la/las última/s.

Saludos.-

**Comment by study64** [comment]
Muchas gracias
