### ISSUE TITLE
Duda sobre traer heapmetadata a memoria

### ISSUE THREAD

**Issue by mercedesmagnelli** [sisoputnfrba/foro#2428]
Buenas! Una pregunta rápida: los punteros que van a ser enviados desde el planificador a la ram para lectura o escritura, tiene que ser verificados directamente con la información guardada en memoria? Es decir, traer esos 9 bits a memoria principal (si estuvieran en memoria virtual) y evaluar directamente de ahí? Las verificaciones que queremos hacer van relacionadas a si se quiere leer un puntero liberado, de tamaño mayor o menor al disponible por la partición del heap o que no exista ese heap. Son verificaciones esperables o ya van a venir punteros "válidos" de por sí?
Esto nos surgió porque si leemos directamente de memoria, vamos a correr el algoritmo de reemplazo en esta instancia y los resultados finales cambiarían.

Gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Tienen que cargar la página en memoria, tanto los datos como el heap_metada es algo que al nivel de la paginación no tienen por que conocer, por lo que si tienen el heap_metada en swap, tienen que traerlo a memoria principal.

Saludos.-

**Comment by iago64** [comment]
@mercedesmagnelli Te quedo alguna duda? Hay algo que necesites que revisemos mas en detalle?

**Comment by mercedesmagnelli** [comment]
No!  Perfecto, muchas gracias. Creería que nos quedó claro!

**Comment by iago64** [comment]
Joya! Cerramos entonces, cualquier cosa pueden volver a abrir el issue o crear uno nuevo y referenciar este issue 😄

**Comment by mercedesmagnelli** [comment]
Hola! Reabro esto porque me volvió a entrar la duda: qué verificaciones son esperables entonces sobre los punteros que recibamos desde los módulos que se comunican con la RAM? Porque estamos haciendo las verificaciones mediante una lectura secuencial de los heaps lo que que genera que siempre se traigan a memoria todas las paginas que tienen heaps escritos, provocando que quede siempre como página más antiguamente usada la primer pagina del proceso (que es donde se guarda el primer heap), más que nada por el tema del algortimo LRU que hay que actualizar la timestamp. 

¡Saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

Las verificaciones las tienen que hacer efectivamente sobre los punteros que les llegan y la única que tienen que hacer es si la dirección esta por fuera del espacio de direcciones del carpincho. 
Es decir si su carpincho tiene 1 sola página de 32 bytes y la dirección indica que tienen que ir a la página 4.... bueno ahi esta el error 😄 

Saludos.-

**Comment by tferraro** [comment]
Cierro el issue por las moscas que haya quedado abierto pero solucionado 😜

**Comment by mercedesmagnelli** [comment]
@iago64 Volvemos una vez mas con la misma duda: tenemos que traer todos los HEAPS a memoria? Es decir si necesitamos leer el 4to HEAP tenemos que leer los HEAPs 1,2 y 3?
Volvemos a preguntar porque estamos corriendo los test de TLB que son de los últimos que nos falta pasar y creemos que no dan los resultados esperados por esta misma razón.
Hay que realizar un acceso directo? Si el HEAP apunta al bit 42 y dice que tiene que leer 5 bits, tengo que:
- leer todos los heaps anteriores de forma secuencial, verificando que el HEAP ubicado en el bit 33 me da como puntero de lectura el bit 42 y luego realizar la lectura del dato?
- leer solamente el HEAP ubicado en el bit 33 que me verifica que el puntero de lectura 42 es correcto, procediendo a la lectura del dato
- leer directamente del bit 42 el dato buscado

Nosotros estamos usando la primera alternativa, con la misma nos pasaron todos los test menos:
- Las dos pruebas de TLB

gracias!
