### ISSUE TITLE
[Memoria] Duda con inicialización de procesos

### ISSUE THREAD

**Issue by nicolasLannert** [sisoputnfrba/foro#2429]
Buenas tardes, teníamos una duda con la creación de la tabla de páginas. Tenemos entendido que por teoría cada proceso en nuestra memoria va a tener su propia tabla de páginas. La primera pregunta es:
- Esa tabla de páginas se crea en el momento en el que se conecta un carpincho a memoria por primera vez?

Por ejemplo llega un carpincho nuevo que su primer memalloc, en ese momento se le crea la tabla de páginas y se le asigna una primera página para empezar a reservar memoria.

Si la respuesta anterior es afirmativa también tenía la duda de si podemos tener una estructura administrativa que contenga todas las tablas de páginas de los carpinchos que tienen contenido en memoria, cada una de esas tablas con su respectivo id de carpincho.

Y una última duda es si cuando por ejemplo kernel se comunica con memoria: puede enviarnos el id del carpincho para saber de qué carpincho particularmente estamos hablando?

Gracias.

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Cuando crean la tábla de páginas? Pueden hacerlo al momento del mate_init o al momento de recibir el primer memalloc, da igual, lo importante es que no creen una página ni asignen ningun frame hasta que no ocurra el primer memalloc.

2.- La estructura que tenga la info de las tablas de página de los carpinchos es una estructura que se ve en la teoría y es la tabla de procesos 😉, con lo cual pueden tenerla.

3.- Si, el kernel puede facilitarles el id del carpincho, no hay problema en la info que se manden entre kernel y memoria 😄 

Saludos.-

**Comment by matiasferrerovilas** [comment]
Aprovecho que sigue abierto el issue, entonces uno tiene una "tabla de proceso" y dentro tiene uno una lista de tablas de páginas y el id del carpincho al cual corresponde?

**Comment by iago64** [comment]
Buenas @matiasferrerovilas!

Si les resulta mas cómodo para buscar tener una lista de listas donde la lista principal sea la "tabla de procesos" y la secundaria sea la "tabla de páginas" del carpincho, pueden tenerla, no hay problema 😄 

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Cierro por inactividad, si quedó cualquier duda pendiente no duden en reabrir el issue o abrir uno nuevo 😄
