### ISSUE TITLE
[Kernel] Eventos (new -> ready), (suspendido -> ready)

### ISSUE THREAD

**Issue by lalvarez-utn-frba** [sisoputnfrba/foro#2430]
Hola! buenas tardes!

Viendo el enunciado sólo menciona el comportamiento que tiene un proceso/carpincho en caso de ser suspendido, pero no en caso contrario, cuando pasa a ready. 

1- Nos preguntábamos si al momento de pasar a ready (desde suspendido), ¿tenemos que cargar en memoria nuevamente todos los marcos asignados al proceso/carpincho?

2- Por otro lado nos preguntábamos si tenemos que reservar todos los marcos cuando hacemos mate_init o cuando llega el primer malloc. ¿Caso que no haya lugar el proceso/carpincho quedaría aún en new?

### 📔 Citas del enunciado/videos

```Cuando un carpincho sea suspendido, todas sus páginas que se encuentren en memoria principal deben ser bajadas a swap. En el caso de la asignación fija, los marcos reservados serán liberados para dar entrada a nuevos carpinchos.```

**Comment by LeandroCarbajales** [comment]
Buenas!
1- La lógica es similar a pasar de (new->ready), en asignación fija tendrá su cantidad fija de marcos reservados, no confundir esto con cargar sus páginas en memoria.
2- Al hacer mate_init solamente implica que el carpincho entre a la cola "new", por lo que no debería tener ningún marco asignado aún.

Espero que sirva la respuesta!
Saludos!
       Lean

**Comment by lalvarez-utn-frba** [comment]
Excelente, gracias por la rápida respuesta. La 2 quedó clara.

Respecto de 1, mi pregunta es si puede pasar que el tamaño de memoria no soporte el grado de multiprogramación dado, qué pasaría en ese caso? Seguiría suspendido? Entiendo que Kernel tiene que fijarse en memoria antes de poder pasar un proceso a ready?

**Comment by LeandroCarbajales** [comment]
En asignación fija el grado de multiprogramación no debería ser más alto que la cantidad de procesos que entran en memoria, las configs de kernel y memoria tienen que ser congruentes, por lo que nunca pasaría ese caso :)

Saludos!
          Lean

**Comment by lalvarez-utn-frba** [comment]
Excelente, gracias por la aclaración. Cierro el issue! saludos!
