### ISSUE TITLE
[RAM] Creación de páginas

### ISSUE THREAD

**Issue by study64** [sisoputnfrba/foro#2431]
Hola de nuevo,

me surgió la siguiente duda respecto a la creación de páginas: ¿Cuándo creo una nueva página la cargo directamente en un marco o solo la envío a swamp y se carga en un marco la primera vez que se referencia?. Saludos.

**Comment by iago64** [comment]
Buenas! 

Al momento de crear una página vas a tener que asignarle un marco, ya que los carpinchos no pueden hacer cosas directo en swap y el crear una página nueva va a venir de la mano de un memalloc() de un carpincho 😄 

Saludos.-

**Comment by study64** [comment]
Eso lo entiendo, pero no es lo mismo:
caso 1) Se ejecuta alloc entonces creo la pagina y la mando a swamp, luego hago memWrite para agregar el heap metadata, entonces hago swapIn y la cargo en un frame (me como el tiempo de swapOut + SwapIn)
caso 2) Se ejecuta alloc entonces creo la pagina YA CARGADA EN UN FRAME y la mando a swamp luego hago memWrite para agregar el heap metadata la pagina ya esta cargada en memoria (me como el tiempo de swapOut y como mucho un tlbMiss)

no se si me explique? cualquier cosa me explayo mas. gracias

**Comment by LeandroCarbajales** [comment]
Buenas!
Sería más parecido al caso 1, cargar la página en memoria antes que en SWAP iría en contra de la paginación bajo demanda, de entrada no podrías agrandar el espacio de direcciones del proceso sin chequear que haya espacio en SWAP, teniendo esto en cuenta luego tendrás un TLB miss y un page fault al intentar escribir esa página.

**Comment by RodrigoLista** [comment]
> Buenas!
> 
> Al momento de crear una página vas a tener que asignarle un marco, ya que los carpinchos no pueden hacer cosas directo en swap y el crear una página nueva va a venir de la mano de un memalloc() de un carpincho 😄
> 
> Saludos.-

Pero si vamos al ejemplo de que me piden allocar un alloc que ocupa 3 paginas. Supongamos que el heap metadata nos ocupa menos de una pagina. Por lo tanto, al escribir en memoria el Heap, solo necesitaria tener en memoria la primer pagina. Porque deberia traer la segunda y tercera pagina a memoria si no voy a leerlas ni escribirlas.

**Comment by RodrigoLista** [comment]
Muchas gracias

**Comment by iago64** [comment]
@study64 te queda alguna duda? Hay algo mas que necesites que veamos mas en detalle?

**Comment by study64** [comment]
No muchas gracias
