### ISSUE TITLE
IP memoria

### ISSUE THREAD

**Issue by janaroz** [sisoputnfrba/foro#2432]
¿De donde saco la IP de la memoria para conectarse con la swamp y con el kernel? Porque en la config.

**Comment by iago64** [comment]
Buenas!

Cualquier cosa que no este en los archivos de config pero que uds necesiten lo pueden agregar, no hay problema con eso, solo recuerden de pushearse un archivo de ejemplo para el día de la entrega poder tener todo listo 😉 

Saludos.-

**Comment by mesaglio** [comment]
Buenas, agrego info a lo que comento Dami.

En el archivo de configuracion de Kernel tenes los siguientes campos:

- IP_MEMORIA
- PUERTO_MEMORIA

Mientras que en el archivo de configuracion de SWAMP tenes:

- IP (IP a la cual se deberá conectar con la memoria)
- PUERTO (Puerto al cual se deberá conectar con la memoria)

Teniendo esto en cuenta, no creo que haga falta agregar nada a las configs (en este caso), ya que el servidor va a ser Memoria y los clientes son tanto Kernel como SWAMP.

Salu2!

**Comment by iago64** [comment]
@janaroz quedo alguna duda? podemos cerrar el issue?

**Comment by janaroz** [comment]
Me quedo recién claro cuando me explicaron que cuando se levanta un socket servidor toma la IP de la computadora. Y que la IP debería coincidir con la de la config. (No sé si use las palabras correctas).
Si esto es correcto, entonces se puede cerrar el issue. 
Gracias

**Comment by iago64** [comment]
Buenas!

Efectivamente, cuando sos servidor levantas la IP local y después los demás configs tienen que apuntar a tu IP para saber a donde conectarse, por las dudas confirmame si no es algo que esta en la guía de sockets del tp0 porque estaría bueno que lo agreguemos de cara al cuatri que viene 😄 

Saludos.-

**Comment by iago64** [comment]
Cerramos por inactividad 👮
