### ISSUE TITLE
Duda Memoria Pagina

### ISSUE THREAD

**Issue by matiasferrerovilas** [sisoputnfrba/foro#2433]
Tenia una duda al escribir en memoria:
1. Cuando inicia un carpincho (C1), este no tiene paginas aun, le asigno una y escribo en el inicio de la memoria.
Ahora si llega otro carpincho (C2), tampoco tiene paginas aun, le asigno la pagina y al escribir, este no deberia escribir en el inicio de la memoria,no?
deberia desplazarme con el marco que le asigne?

2. Y por otro Los heap metadata en las paginas pueden estar separado? es decir una pagina puede tener el nextAlloc, y otra el prevalloc y otra el isfree de un heap_metadata?
 Ejemplo. Tengo paginas de 32.
.hago un alloc de 5; Entonces mi pagina 0 va a tener 23 bits ocupados (5 + 9 + 9). los 9 del heap_metadata.
.Ahora hago otro alloc de 23; Entonces 9 van a ir a la pagina 0 llenandola. Pido otra pagina, pagina 1. de esta ocupo 14 + 9(del heap).
. Si hago ahora un alloc de 3. Mi pagina 1 tiene 23 bits ocupados.
  Que hago aca? ocupo 3 y pido pagina nueva para los 9 del heap?

**Comment by iago64** [comment]
Buenas!

1.- Efectivamente, vos vas a asignarle un marco a cada uno de los carpinchos y vas a tener que ir trabajando con las direcciones lógicas, que al igual que en la teoría, vas a tener que traducirlas a las direcciones físicas (de nro de página y desplazamiento vas a tener que pasar a nro de frame y desplazamiento)

2.- Si, los heap metadata pueden estar partidos entre 2 páginas, con lo cual tengan cuidado de no pasarse cuando los escriban en la memoria porque pueden pisar otro frame que no les corresponde.
2.b.- El heap del final lo van a tener que pedir siempre, con lo cual si tienen que pedir una página de mas, la piden, no hay problema.

Saludos.-

**Comment by nicolasLannert** [comment]
Buenas, me sumo a la consulta, particularmente sobre la respuesta 2:
Supongamos que yo quiero meter un heap al final de la página 1, pero no me alcanza y tengo que pedir otra página, pero me doy cuenta que no tengo un frame contiguo, por ejemplo me quedaría página 1 - marco 1 y página 2 - marco 4, en ese caso tendría que pasar todo el heap a la página 2 y quedarme con una fragmentación interna en la página 1? O existe alguna forma de escribir parte del heap en el marco 1 y el resto en el marco 4?

**Comment by LeandroCarbajales** [comment]
Hola Nico!
Los heapMetadata no deberían comportarse distintamente al resto de direcciones lógicas del proceso, para leerlas o escribirlas tenés que traducir esas direcciones de (lógica -> física), por lo que si el mismo está partido entre 2 páginas, esto incluirá leer/escribir en 2 marcos distintos que no necesariamente tienen por qué estar contiguos.

**Comment by matiasferrerovilas** [comment]
Entonces por ejemplo:
![imagen](https://user-images.githubusercontent.com/27780879/142957100-7120aac5-68e4-4ce8-90e9-d4ee555df469.png)

Tengo mis Alloc con las paginas, cuya direcciones logicas son las que aparecen en la foto.
Ahora a la hora de escribir en memoria para hacer el memcpy, yo no tengo que tomar esa direccion que aparece, sino convertirla a una direccion fisica.
Entonces yo uso el marco de la pagina a la cual corresponde para formar la direccion fisica y escribo.
Ahora en caso que haya swap,, de la Pagina 0, por ejemplo. Cuando vuelva a memoria estas direccoines que estan en nextAlloc y prevAlloc no podrian estar ocupadas por otros allocs?. En este caso que pasaria?

**Comment by iago64** [comment]
Buenas! 

Justamente la idea de las direcciones lógicas es que te resuelven de manera "lógica" la dirección (valga la redundancia de la palabra). 
Un ejemplo de dirección lógica muy muy teórico sería si pudieras tener 2 números donde el primero sea el número de página y el segundo el desplazamiento, entonces vos de tu tabla de páginas vas a saber en que frame tenes tu página, por ejemplo un carpincho con una petición para la página 2 desplazamiento 10 te queda:

| Página | Frame |
| ------------- | ------------- |
| 0  | 4  |
| 1  | 45  |
| 2  | 1  |

Si vos tenes por ejemplo páginas de 64 bytes, sabes que la página 0 te arranca en la posición 0 (o en la posición que te devolvió el malloc que hiciste para la "memoria") y la página 1 va a empezar en `0 + 64` o también generalizándolo como `0 + (nro de página * tamaño de página)`
Entonces si tenes que ir al offset 10 va a quedarte la cuenta:
`0 + (nro de página * tamaño de página) + desplazamiento` (siempre 0 es lo que te devolvió el malloc del inicio).
Entonces que te pasa? tu next alloc y tu prev alloc, van a ser direcciones de este estilo, por ejemplo:
- prevAlloc = página 0, desplazamiento 10
- nextAlloc = página 0, desplazamiento 50

Como haces para que el número de página y el desplazamiento convivan en un único numero, ahí ya te lo dejo para que lo pienses, hay varias formas, algunas mas parecidas a como se ve en la teoría con operaciones a nivel de bits, otras utilizando operaciones matemáticas.

Saludos.-

**Comment by matiasferrerovilas** [comment]
Entiendo.
Pero entonces cuando uno hace el memcpy usa (nro de página * tamaño de página) + desplazamiento o (nro de marco* tamaño de página) + desplazamiento?
Despues en caso que envie la pagina a swap, dicho espacio debo liberarlo para que otra pagina lo ocupe, no?

**Comment by iago64** [comment]
Buenas!

Tanto memcpy() en la realidad como memwrite() y memread() en el tp lo que hacen es usar esa dirección "lógica" que vos creaste al momento de reservar la memoria para poder calcular después nro de página y desplazamiento.
Despues en donde va a estar alojada esa página es parte del problema que tenes que resolver como memoria para ubicarla en un marco y después poder saber que va a estar ahi.

Saludos.-

**Comment by iago64** [comment]
@matiasferrerovilas Te quedo alguna duda? Necesitas que revisemos algo mas en detalle?

**Comment by matiasferrerovilas** [comment]
por ahora no. cualquier cosa abro un issue nuevo
