### ISSUE TITLE
[Archivos de Pruebas] Dudas al compilar

### ISSUE THREAD

**Issue by federiver91** [sisoputnfrba/foro#2435]
Buenas!

Siguiendo los pasos del Readme, me sale el siguiente error.

![image](https://user-images.githubusercontent.com/49326422/142949584-a36f2328-dcea-47a1-9856-e2dec0ef7092.png)

Aclaro que probé poniendo la carpeta "carpinchos-pruebas" dentro de la misma carpeta del tp nuestro como afuera. En ambos casos, el error es el mismo

Alguna ayuda por ahí? Gracias

**Comment by iago64** [comment]
Buenas! 

Gracias por el aviso, estuvimos flojitos con el tema del readme de las pruebas, por casualidad no hiciste `make install` antes verdad? Porque justamente `make install` lo que hace es "instalar" el matelib.h para que los carpinchos lo puedan encontrar al momento de compilar.

Saludos.-

**Comment by federiver91** [comment]
Nnnop.

Seguí el readme al pie de la letra.

Previo al make hago el make install y debería funcionar entonces?

**Comment by iago64** [comment]
Buenas!

Ahora si, lo que no te esta encontrando es el path a la matelib, es decir el libmatelib.so que deberían haber generado uds.
Para resolver eso hay 2 caminos rápidos:

1- Que copien el libmatelib.so (es decir el shared object que generan despues de generar la matelib) en `/usr/lib`
2- Hacer el export del `LD_LIBRARY_PATH`

Ambas alternativas por las dudas están [comentadas](https://github.com/sisoputnfrba/foro/issues/2434#issuecomment-975940020) en el issue #2434 

Saludos.-

**Comment by federiver91** [comment]
Buenas,

Intenté hacer la primera opción y sigue tirando el mismo error. Aclaro que lo unico que hice es lo que dice el issue mencionado (desde el directorio raiz). Es decir... Hice "cd .." hasta que no fue posible seguir subiendo y escribi en la consola "export LD_LIBRARY_PATH=/home/utnso/workspace/tp-2021-2c-Recurpinchos/matelib/Debug" que es donde está el archivo que comentas. Le di al Enter y no pasó nada, con lo cual asumo que no hubo error. Pero cuando hice el make de nuevo, volvió a tirar el mismo error. Por lo tanto, asumo que algo hice mal u omití en el camino.


En cuanto a la PRIMERA opción, el simple copy-paste del archivo en el directorio que comentás, me devuelve este error de permisos
![image](https://user-images.githubusercontent.com/49326422/142954176-90acf09a-06df-497c-bfaf-2ad88fcb8d04.png)


Saludos y gracias!

**Comment by iago64** [comment]
Buenas!

El tema de los permisos lo podes resolver si haces la copia por consola, si el archivo libmatelib.so lo tenes en el path que pasaste te quedaría algo asi como:

`sudo cp /home/utnso/workspace/tp-2021-2c-Recurpinchos/matelib/Debug/libmatelib.so /usr/lib`

Esto es algo que puede verse facil en el [makefile de las commons](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/makefile), donde no es que reinventamos la rueda, simplemente generamos el .so y despues lo copiamos con sudo porque la carpeta /usr/lib es una carpeta de sistema y necesita permisos elevados para poder accederla 😄 

Para el tema del makefile, te agradezco una banda el input, vamos a estar acomodando un poco el script para que sea mas simple de utilizar, lo liberamos rápido para no demorar mucho y que puedan tener las pruebas pero claramente le falto un poco de laburo extra.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Me sumo porque estuve buscando una posible causa del error y resulta que:
- `LD_LIBRARY_PATH` sirve para linkear la shared library en runtime (o sea, para ir a buscar el .so al momento de ejecutar el carpincho).
- `LIBRARY_PATH` sirve para avisarle a `gcc` que vaya a buscar cualquier tipo de library (shared o static) a esa ruta al compilar (link de referencia [acá](https://stackoverflow.com/a/4250666/14089741)).

Es decir que la opción 2 sería exportar ambos `LIBRARY_PATH` y `LD_LIBRARY_PATH` con la ruta hacia el archivo `*.so` (el primero es para antes de compilar y el segundo para antes de ejecutar).

Saludos

**Comment by federiver91** [comment]
Gracias!

Ahí pude compilar!

Cierro esto
