### ISSUE TITLE
PruebaBase_CarpinchoN falta mate_close

### ISSUE THREAD

**Issue by FrancoMila** [sisoputnfrba/foro#2437]
Buenas,

A las pruebas bases les estaria faltando 'mate_close' para finalizar correctamente la ejecución del lado del kernel.

Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

El objetivo de la prueba base es ver que mas o menos todo el sistema funciona, con lo cual, el hecho de que no este el llamado a `mate_close()` no afecta en nada al propósito de la prueba.

De todas manera vamos a estar agregando el llamado a `mate_close()` por si las dudas justo esa es la función que hace volar todo por los aires (esperemos que no), pero no entren en pánico 😄 

Saludos.-

**Comment by FrancoMila** [comment]
No no, efectivamente a efectos de probar como se alternan los carpinchos la
prueba funciona correctamente. Solo que al no tener el mate_close no tenia
el paso al estado exit.

Saludos

**Comment by MarcoPiatti** [comment]
Buenas! Segundeo esto, me pasa que ante la falta de mate_close los carpinchos se desconectan "abruptamente" y me revienta el kernel jajaja (todo: agregar safeguards para desconexiones).

**Comment by iago64** [comment]
Buenas!

Que se desconecte abruptamente un carpincho es algo que deberían tolerar, mas alla de que no sea algo propio del comportamiento de los carpinchos del tp, puede ser que exista algún microcorte en la conexión y les llegaba el -1 en el recv() (aunque parezca joda, eso pasaba mucho mas en el laboratorio presencial que en als vms en la nube) y no esta bueno que todo explote por los aires.

Saludos.-

**Comment by FBanfi** [comment]
Hola!

Entonces si tenemos un caso en el que el servidor está bloqueado en el recv y el cliente finaliza haciendo un return, en ese caso, que retornaría el recv?

Porque nosotros probamos con -1 y con sus enums (EBADF, ENOTSOCK, EINTR, ENOTCONN) y ninguno de esos es el que retorna en esta situación.

**Comment by RaniAgus** [comment]
¡Buenas @FBanfi ! Fijate que en el [manual de recv](https://man7.org/linux/man-pages/man2/recv.2.html) dice:

```
RETURN VALUE
      These calls return the number of bytes received, or -1 if an
      error occurred.  In the event of an error, errno is set to
      indicate the error.
```

Es decir que, en caso de error, `recv()` devuelve siempre -1 y deja seteado el código de error en una _variable global*_ llamada [`errno`](https://man7.org/linux/man-pages/man3/errno.3.html) para indicar ese error que estabas buscando. 

Como dato, pueden pasar ese código de error a string usando la función [`strerror`](https://man7.org/linux/man-pages/man3/strerror.3.html) o directamente mostrarlo por pantalla junto con un mensaje usando [`perror`](https://man7.org/linux/man-pages/man3/perror.3.html).

> Aclaración: En realidad `errno` se puede usar como una variable global porque es un lvalue, pero es más que eso: tiene _algo_ que hace que sea local para cada hilo, o sea, un error en un hilo no te "pisa" el valor de `errno` en otro 😉: 
> ```
> errno is defined by the ISO C standard to be a modifiable lvalue
>        of type int, and must not be explicitly declared; errno may be a
>        macro.  errno is thread-local; setting it in one thread does not
>        affect its value in any other thread.
> ```

Saludos

**Comment by iago64** [comment]
Buenas!

Agregamos el llamado a mate_close() en la prueba base a fin de que no sea un dolor de cabeza la prueba, como dijimos anteriormente, la idea era ver que el tp levantara y pasaran los mensajes, asique para que no se preocupen 😄 

Saludos.-

**Comment by FBanfi** [comment]
Genial muchas gracias!

**Comment by iago64** [comment]
Agregado el mate_close() y resueltas las dudas intermedias, cerramos el issue, cualquier cosa pueden crear uno nuevo citando lo hablado aca 😄
