### ISSUE TITLE
Duda de sincronizacion en PruebaPlanificacion.c

### ISSUE THREAD

**Issue by amendezkar** [sisoputnfrba/foro#2438]
Buenas, en el archivo de PruebaPlanificacion.c tengo una duda sobre la sincronización de los carpinchos. Notamos de que los carpinchos inicializan en el sistema en un orden que depende de la ejecución, ya que al carpincho 3 llega primero, el 2 llega segundo, y el 1 llega tercero al kernel. Para que esto se de en orden, no tendría que pasar lo siguiente?

1. El carpincho 1 hace mate_init y se conecta al sistema
2. El carpincho 1 hace sem_post a va_el_2
3. El carpincho 2 se desbloquea tras haber hecho sem_wait a va_el_2
4. El carpincho 2 hace mate_init y se conecta al sistema
5. El carpincho 2 hace sem_post a va_el_3
6. El carpincho 3 se desbloquea tras haber hecho sem_wait a va_el_3
7. El carpincho 3 hace mate_init y se conecta al sistema

Y todos siguen su orden natural.

**Comment by mesaglio** [comment]
Buenas @amendezkar , ahi subi unos cambios a la prueba de planificacion.
Deberia forzar la llegada de los carpinchos al kernel:
1. Carpincho 1
2. Carpincho 2
3. Carpincho 3

Si encontras otro error, aqui estamos para parchearlo.
Salud2!

**Comment by amendezkar** [comment]
Perfecto, gracias!
