### ISSUE TITLE
Duda sobre el memread en pruebaBase

### ISSUE THREAD

**Issue by gabycosta04** [sisoputnfrba/foro#2439]
![image](https://user-images.githubusercontent.com/62992579/143088803-a0d35ea9-c352-473a-9ee8-fe98ac65031c.png)
Tenia una consulta respecto a esta parte porque no me estaria funcionando el memread, ya que cuando le quiero hacer el memcpy al char* (que ya tiene contenido y en realidad no realiza un malloc), no me deja escribirle contenido por el memcpy al mismo, y me tira un segmentation fault.

Queria saber si estaba bien o mal eso de las pruebas, porque vi por ejemplo, esta pruebas de MMU, pero acá antes de realizar el memread declara una variable que guarda un espacio en memoria, y en este caso el memread funcionaria bien claramente ya que se hace un memcpy sobre un espacio de memoria reservado.
![image](https://user-images.githubusercontent.com/62992579/143089010-4268c224-4702-41e7-8aee-9183866ea4a0.png)

Desde ya muchas gracias y saludos

**Comment by RaniAgus** [comment]
¡Buenas! Es correcto, como se menciona [acá](https://stackoverflow.com/a/2589963/14089741) es común que en varias arquitecturas los strings que se asignan a un "puntero a char" se terminen guardando dentro de un segmento de solo lectura, por lo que es probable que tire `segmentation fault`.

[Ahí lo corregí](https://github.com/sisoputnfrba/carpinchos-pruebas/commit/0fd2fc45e9f6fe50ce77fcd7950932a731cb3fae) para que se declare la variable como array de caracteres:  
```c
char saludo[] = "¡Hola mundo!\n";
```
De esta forma, sí se va a poder modificar en cualquier arquitectura ya que ese string se va a guardar dentro del stack, que es de lectura y escritura.

¡Gracias por notarlo!
Saludos

**Comment by gabycosta04** [comment]
Dale perfecto Agus, entonces quedo entendido
