### ISSUE TITLE
Duda sobre asignacion fija con la suspencion de procesos

### ISSUE THREAD

**Issue by matiashamide** [sisoputnfrba/foro#2440]
Buenas, Me surgio una duda en asignacion fija especificamente.
Cuando el proceso pasa a estar suspendido/bloqueado, toda su imagen pasa a swap para que esos frames puedan ser utilizados por cualquier proceso. En dinamica no habria problema porque lo desocupas, los frames los mandas a swap si  estan modificados y listo. Pero en asignacion Fija que reservas n cantidad de frames para un proceso, deberia marcar esos frames como libres? El problema que veo en ese caso es que llega otro proceso y ocupa esos n frames y el proceso que estaba suspendido no pueda volver a ready porque no lo podes instanciar nuevamente en memoria.

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va?
> en asignacion Fija que reservas n cantidad de frames para un proceso, deberia marcar esos frames como libres?

Correcto 👍🏻 

> El problema que veo en ese caso es que llega otro proceso y ocupa esos n frames y el proceso que estaba suspendido no pueda volver a ready porque no lo podes instanciar nuevamente en memoria.

Ahí es cuando entra en juego el grado de multiprogramación: como comentaba Dami en https://github.com/sisoputnfrba/foro/issues/2422#issuecomment-969358192, en asignación fija siempre vamos a limitar el grado de multiprogramación para que sea acorde a la capacidad que tenga la memoria. 

Por lo tanto, podemos asumir que ese caso que vos mencionás no va a ocurrir y siempre va a haber memoria suficiente para asignarle a cada proceso la cantidad de frames que haya configurado, así que el comportamiento es indefinido y pueden elegir cómo manejar el error (o incluso no manejarlo :P).

Saludos

**Comment by matiashamide** [comment]
Okey me quedo clarisimo, perfecto gracias

**Comment by matiashamide** [comment]
Me quedo calro gracias, Saludos
