### ISSUE TITLE
Duda con sem_wait

### ISSUE THREAD

**Issue by Nicolas-Russo** [sisoputnfrba/foro#2441]
Buenas, tengo una duda sobre como se puede hacer sem_wait. Por el lado de la mate lib en la funcion mate_sem_wait se nos ocurrio, despues de mandarle el mensaje al kernel con la info necesaria que se quede esperando un mensaje, hace un recv(conexion, buffer, size, MSG_WAITALL) y hasta que no reciba de vuelta nada no sigue ejecutando. Ahora en la parte del kernel, cuando se recibe el mensaje y se pasa al carpincho a la lista de bloqueados no sabemos como hacer para que se quede esperando a que al carpincho se lo vuelva a pasar a la lista de redy y asi poder enviar el mensaje para que el carpincho para que lo reciba y poder seguir ejecutando. Se nos ocurrio hacer un while(), hasta que no vuelva a la cola de ready se quede haciendo una espera activa. No se que tan mal esta eso.

Muchas Gracias!

**Comment by LeandroCarbajales** [comment]
Buenas!
Tener un while() con espera activa nunca es una buena opción y puede ser motivo de desaprobación, estos casos de "tengo que esperar a que pase algo" son ideal para usar semáforos como en los ejercicios vistos en clase.

Saludos!
      Lean

**Comment by Nicolas-Russo** [comment]
Dale Gracias.
