### ISSUE TITLE
Posible error en configuración de Prueba Base

### ISSUE THREAD

**Issue by MarcoPiatti** [sisoputnfrba/foro#2442]
Buenas, realizando la Prueba Base me pasa que el Carpincho N°2 no puede operar en la memoria. 
Después de andar debuggeando un rato creo que se debe a que hay algo medio chueco en la configuración del sistema solicitada por la prueba: entre el grado de multiprogramación, el tamaño de la memoria y el esquema de asignación fijo.

### 📔 Citas del documento de pruebas
[link a la config de la consigna](https://docs.google.com/document/d/1RuDWMyax49EFQF4o22CY1twNV0FSDsRrW99ndTEMyKA/edit#heading=h.3ns9py2dc5kl)

### 👍 Comportamiento esperado
El carpincho N°2 Debería poder utilizar el único frame que hay en memoria mientras el Carpincho N°1 está bloqueado en el semaforo.

### 👎 Comportamiento obtenido
* Ese único frame ya se encuentra ocupado por el Carpincho N°1, que se encuentra bloqueado en el semaforo.
* Como el grado de multiprogramación es 2, el Carpincho N°1 no es suspendido, la memoria no es liberada y no puede ser usada por el segundo.
* Como la asignacion es fija, el segundo no puede "robar" ese único frame del Carpincho N°1.

Debido a esto, la memoria no puede cargar la página del carpincho N°2 en MP y se produce el fallo.

### Posibles soluciones
✓ Incrementar el tamaño de la memoria principal para igualar el grado de multiprogramacion.
✓ Cambiar el esquema de asignación a global.
✓ Reducir el grado de multiprogramacion para que se ajuste al tamaño de la memoria.

Con cualquiera de estas alternativas me funciona apropiadamente

**Comment by iago64** [comment]
Buenas! 

Lo vamos a estar analizando y corrigiendo, a priori pueden probarlo ampliando el tamaño de la memoria principal y tambien cambiando el esquema de asignación, así de paso matan 2 pájaros de 1 tiro y prueban un poco los 2 esquemas de asignación en la prueba base 😉 

Saludos.-
