### ISSUE TITLE
[Pruebas Saludo humedal] Valores de los .config

### ISSUE THREAD

**Issue by federiver91** [sisoputnfrba/foro#2443]
Buenas!!

Seguro que los valores propuestos para los .config están correctos?
![image](https://user-images.githubusercontent.com/49326422/143158440-154dd09a-b83a-41c4-8a11-7516ecf87def.png)

Estoy obteniendo un error cuando corro el Carpincho2. Y me parece lógico ya que si la asignación es FIJA, el TAMANIO es 32 y el TAMANIO de la pagina es 32 también, entonces el Carpincho1 va a ocupar toda la memoria y va a quedar bloqueado (Ya que no cumple las condiciones de suspensión).

Con lo cual, el Carpincho2 va a tirar siempre un error.

Es lo que estuvimos viendo estas últimos minutos. Puede ser?

Saludos

**Comment by mesaglio** [comment]
#2442

**Comment by iago64** [comment]
Buenas! Paso a dejar la misma respuesta del issue #2442...

> Lo vamos a estar analizando y corrigiendo, a priori pueden probarlo ampliando el tamaño de la memoria principal y tambien cambiando el esquema de asignación, así de paso matan 2 pájaros de 1 tiro y prueban un poco los 2 esquemas de asignación en la prueba base 😉

Un extra: La prueba base no valida mucho mas que el hecho de que levante el tp y puedan pasar el comportamiento mas base del sistema, con lo cual, un pequeño ajuste en las pruebas no sería tan grave.

Saludos.-

**Comment by federiver91** [comment]
Gracias!
