### ISSUE TITLE
[MEMORIA] Dudas sobre el memfree

### ISSUE THREAD

**Issue by tselvaggi** [sisoputnfrba/foro#2444]
Buenas! Estamos teniendo dudas acerca del implementado del memfree, más que nada para en control de que la dirección que se envía efectivamente es del final de un bloque heapMetadata o es un MATE_FREE_FAULT. En principio nosotros lo tenemos implementado de la forma en la que se recorre desde el primer alloc hasta el que se debería liberar, en caso que no se encuentre, se efectúa el error. El problema de esto es que hay acceder y encontrar todas las paginas (si es necesario traerlas de swap).

### 📔 Citas del enunciado/videos

En caso de que se quiera liberar una posición de memoria errónea, se deberá devolver el error MATE_FREE_FAULT definido en el enum mate_errors de la matelib correspondiente con el valor -5.

### 💭 Soluciones posibles

Se nos ocurrió como alternativa, desde la matelib, cada vez que se hace un memalloc guardar el matepointer que se recibe de memoria en la estructura administrativa del carpincho, para que dado el caso de que quiera liberar un puntero invalido no se permita realizar la operación. Si se hace un memfree sobre un puntero que esta en la lista, se quita ese elemento y se envía a memoria para que modifique el metadata y consolide bloques si es necesario.

Otra solución para evitar recorrer todas las paginas en el memfree puede ser hacer de cuenta que el programador del carpincho nos paso bien la dirección del free y operar normalmente hasta que se encuentre un error.

**Comment by iago64** [comment]
Buenas! Cómo va?

Los errores de memoria (lectura, escritura o free) corresponden solamente a cuando la dirección esta por fuera del espacio de direcciones del carpincho, con lo cual, no tienen que complicarse levantando todas las páginas para hacer el free correspondiente.

Saludos.-

**Comment by tselvaggi** [comment]
Claro, pero que pasa si pido un free de una posición que se encuentra en el espacio de direcciones y no es un HeapMetadata? En principio debería modificar el byte que indica si está libre o no, luego, cuando quiera revisar el prevAlloc para consolidar bloques voy a estar leyendo eso en cualquier lado.
Quizás esa lectura errónea (del prevAlloc) me lleve a un lugar por fuera del espacio de direcciones o quizás no, depende de lo que esté escrito ahí.

![SO_ejemplo](https://user-images.githubusercontent.com/63843225/143298009-910be144-9b4d-4824-9b32-d7cf527e4ea7.png)

En este ejemplo sería correcto recibir un Free en la dirección lógica 9 y en 49, si no me equivoco, puesto a que se recibe lo que devolvió el memalloc.


En lo que es lectura y escritura usamos esa validación que nombraste, la duda es con el free, porque necesito de alguna forma la certeza de que estoy modificando un bloque de Metadata.

**Comment by iago64** [comment]
Buenas!

En la vida real, si, `free()` te chilla por `invalid pointer`, en este caso como no quisimos que se compliquen tanto fuimos por el camino mas optimista y asumimos que siempre a `memfree()` le van a llegar los punteros bien o algo que esta totalmente afuera del espacio de direcciones del carpincho, algo así como que el capincho tiene reservadas 2 páginas de 64 bytes y nosotros le mandamos una a hacer free al byte 2048.

Saludos.-

**Comment by tselvaggi** [comment]
Buenisimo, muchas gracias!
