### ISSUE TITLE
Duda de logs

### ISSUE THREAD

**Issue by matiasimartin** [sisoputnfrba/foro#2445]
Buenas, tengo una duda con la parte de logs de memoria
>Reemplazo de una entrada indicando víctima y la nueva entrada, ambos con PID, Número de página y Marco en ambos casos.

Se refiere al reemplazo de una entrada de la TLB no? O a un reemplazo de pagina en MP?

**Comment by mesaglio** [comment]
Hola @matiasimartin , ambos. Los reemplazos de la tlb y de la memoria para una mejor trazabilidad.

Salu2, Juani!
