### ISSUE TITLE
Tlb 

### ISSUE THREAD

**Issue by RodrigoLista** [sisoputnfrba/foro#2447]
Buenas. Quería hacer una consulta respecto a la tlb. Nosotros estamos haciendo una única tlb que guarda páginas que estén en memoria,  de cualquier proceso. Lo estamos haciendo bien o puede ser que exista una tlb por cada proceso en particular? 

Muchas gracias

**Comment by mesaglio** [comment]
Si es correcto, hay una tlb en todo el sistema que se comparte para todos los procesos.

Salu2, Juani!

**Comment by RodrigoLista** [comment]
Buenisimo. Muchas gracias

**Comment by iago64** [comment]
Buenas! Si la duda quedo resuelta no se olviden porfa de cerrar el issue 👮
