### ISSUE TITLE
[Prueba "Memoria TLB" Caso LRU] Cantidad de Entradas TLB vs Marcos por Carpincho - Asignación Fija

### ISSUE THREAD

**Issue by arielsarchioni** [sisoputnfrba/foro#2448]
Buenas, 

Intentando realizar la prueba de Memoria TLB, para el caso de LRU notamos que en el archivo de config de memoria la cantidad de entradas de la TLB es 3, Asignación FIJA y la cantidad de Marcos por Carpincho es de 2, con lo cual entendemos que nunca podríamos tener 3 entradas con datos de ese único carpincho ya que se repetiría el frame en la TLB, lo cual no sería correcto y por lo tanto los resultados esperados no son logrables . Puede ser que sea un error en la confección de la prueba?

Muchas gracias, saludos!

![image](https://user-images.githubusercontent.com/70733338/143334732-0cdf72be-0e32-4039-b19f-5a663bb95166.png)

**Comment by iago64** [comment]
Buenas! Cómo va?

Fue uno de los detalles que se nos pasaron al momento de escribir los configs, ya quedo actualizado el doc 😄 

Saludos.-

**Comment by arielsarchioni** [comment]
Bien,

Muchas gracias,

Saludos!
