### ISSUE TITLE
[Swamp] Error al reservar memoria

### ISSUE THREAD

**Issue by FedericoFuentesWeber** [sisoputnfrba/foro#2449]
Buenas noches,

 Quería hacer una consulta sobre un problema que nos surgió cuando intentamos hacer el test de swamp.
 En el momento en que empezamos a hacer el traslado de páginas de un proceso hacía otro archivo de swap nos sale el error 'malloc(): invalid size (unsorted)', con la primer estructura a la cual le hacemos malloc no hay problema pero cuando se intenta hacer la reserva de memoria para la siguiente estructura surge el error. Haciendo algunas pruebas nos dimos cuenta que esto pasa por el
tamaño de las páginas, en el caso de este test en especifico es de 2048 bytes, pero si lo hacemos con valores chicos no hay problema alguno.

Saludos.

**Comment by iago64** [comment]
Buenas!

No termino de entender de que estructura estas hablando, ya que de entrada la memoria principal deberías reservar tan solo 10240 bytes que va a ser toda tu memoria y en el caso de swamp lo que vas a tener son 2 archivos donde vas a guardar los datos que te lleguen desde la memoria a la hora de reemplazar las páginas del carpincho.

De todas formas, sería bueno que corras tu tp con valgrind y subas aca el archivo con el output porque me suena que el problema lo venis arrastrando de otro lado porque si con tamaños chicos no falla pero con 2048 si, me huele a que venís pisando memoria a lo loco y no les exploto antes de milagro.

Saludos.-

**Comment by iago64** [comment]
@FedericoFuentesWeber Pudiste correr con valgrind el módulo que te estaba trayendo problemas? Queres compartir el output de valgrind así te ayudamos a encontrar el problema?

**Comment by FedericoFuentesWeber** [comment]
Buenas,

 Disculpa la demora en contestar, usando valgrind creemos haber encontrado el problema, nos dimos cuenta que arrastrábamos memory leaks desde una consola que nos armamos nosotros para poder testear las cosas de swamp mientras se termina de dar los últimos retoques al módulo de memoria así que estamos trabajando en eso.
 Cierro el issue, cualquier cosa si el problema persiste vuelvo a abrir uno.  

Gracias.
