### ISSUE TITLE
[Prueba Deadlock] No hay deadlock

### ISSUE THREAD

**Issue by federiver91** [sisoputnfrba/foro#2450]
Buenas!

Con la configuracion del Kernel propuesta, no obtenemos deadlock ya que va ejecutando de a 1 carpincho sin desalojarse y finalizan todos su ejecución sin bloquearse.

![image](https://user-images.githubusercontent.com/49326422/143370668-445a7957-add3-47f0-a6f5-729bc51909d7.png)

Se podrá chequear?

Gracias!!

**Comment by NicolasWallovits** [comment]
Buenas, me sumo como para agregar un poco más de información de los problemas con esta prueba:

1. Si el grado de multiprogramación es 1, no se da un deadlock. Cada semáforo va tomando y liberando los recursos y nunca llega a darse la solicitud cruzada
2. Si se aumenta el grado de multiprogramación a 2, habría que cambiar de lugar el mate_close que hace el carpincho 0 (el que crea los semáforos). Porque así como está, hace que se mantenga en ejecución porque no llegó a ninguna instrucción bloqueante, y acapara uno de los procesadores que se necesitan para que los demás puedan coordinarse para el deadlock.
O sea esto:
...
    mate_instance instance;

    mate_init(&instance, argv[1]);

  // Creamos los semaforos que van a usar los carpinchos
    mate_sem_init(&instance, "SEM1", 1);
    mate_sem_init(&instance, "SEM2", 1);
    mate_sem_init(&instance, "SEM3", 1);
    mate_sem_init(&instance, "SEM4", 1);
    mate_sem_init(&instance, "SEM5", 1);
    mate_sem_init(&instance, "SEM6", 1);

  // Deadlock entre estos 4
	pthread_t carpincho1;
	pthread_t carpincho2;
	pthread_t carpincho3;
	pthread_t carpincho4;

  // Deadlock entre estos 2 con uno pendiente del anterior
	pthread_t carpincho5;
	pthread_t carpincho6;


	printf("MAIN - Utilizando el archivo de config: %s\n", argv[1]);

	pthread_create(&carpincho1, NULL, carpincho1_func, argv[1]);
    sleep(1);
	pthread_create(&carpincho2, NULL, carpincho2_func, argv[1]);
    sleep(1);
	pthread_create(&carpincho3, NULL, carpincho3_func, argv[1]);
    sleep(1);
	pthread_create(&carpincho4, NULL, carpincho4_func, argv[1]);
    sleep(1);
	pthread_create(&carpincho5, NULL, carpincho5_func, argv[1]);
    sleep(1);
	pthread_create(&carpincho6, NULL, carpincho6_func, argv[1]);
    sleep(1);

    mate_close(&instance);
...
Debería quedar algo así:
...
    mate_instance instance;

    mate_init(&instance, argv[1]);

  // Creamos los semaforos que van a usar los carpinchos
    mate_sem_init(&instance, "SEM1", 1);
    mate_sem_init(&instance, "SEM2", 1);
    mate_sem_init(&instance, "SEM3", 1);
    mate_sem_init(&instance, "SEM4", 1);
    mate_sem_init(&instance, "SEM5", 1);
    mate_sem_init(&instance, "SEM6", 1);

  // Deadlock entre estos 4
	pthread_t carpincho1;
	pthread_t carpincho2;
	pthread_t carpincho3;
	pthread_t carpincho4;

  // Deadlock entre estos 2 con uno pendiente del anterior
	pthread_t carpincho5;
	pthread_t carpincho6;


	printf("MAIN - Utilizando el archivo de config: %s\n", argv[1]);

        mate_close(&instance);

	pthread_create(&carpincho1, NULL, carpincho1_func, argv[1]);
    sleep(1);
	pthread_create(&carpincho2, NULL, carpincho2_func, argv[1]);
    sleep(1);
	pthread_create(&carpincho3, NULL, carpincho3_func, argv[1]);
    sleep(1);
	pthread_create(&carpincho4, NULL, carpincho4_func, argv[1]);
    sleep(1);
	pthread_create(&carpincho5, NULL, carpincho5_func, argv[1]);
    sleep(1);
	pthread_create(&carpincho6, NULL, carpincho6_func, argv[1]);
    sleep(1);
...
3. El grado de multiprogramación debería ser mínimamente 4. Porque siendo sólo 2, entra en juego la suspensión / reactivación de los 4 carpinchos totales que se intenta entren en deadlock. Y como las suspensiones se hacen de a uno, no permite la sincronización deseada
4. Habría un error también en la consigna de resultados esperados. Porque si los primeros 4 se bloquean, 5 no se va a quedar esperando a que se resuelva el bloqueo. O bien el grado de multiprogramación es > 4, entonces 5 puede ejecutar, o bien el grado de multiprogramación es = 4, y en ese punto con todos bloqueados alguno de ellos va a entrar en suspensión para poder hacer pasar al carpincho 5.

Saludos!

**Comment by RaniAgus** [comment]
¡Buenas! Efectivamente, la prueba original estaba pensada con `GRADO_MULTIPROGRAMACION=8` y `GRADO_MULTIPROCESAMIENTO=8` para que todos los carpinchos pueden tomar cada semáforo en paralelo y producir el deadlock. Al parecer hubo un cambio de último momento que no se aplicó y quedó con `2` y `1`. En un ratito hacemos la corrección y lanzamos el announcement.

¡Gracias por avisar!
Saludos

**Comment by federiver91** [comment]
Ok, gracias!
