### ISSUE TITLE
Diferencias en PruebaMMU

### ISSUE THREAD

**Issue by alejcha** [sisoputnfrba/foro#2451]
Buenas, en las pruebaMMU tanto LRU como CLOCK-M no me da el mismo resultado
los accesos a las paginas son recorriendo los heap metadatas de menor a mayor para buscar un hueco, y para signar escribo el inicial y luego el final y acceso directo en memread memwrite

en LRU luego de resolver el ultimo fallo de pagina me queda:

frame 0  pid:1 pagina:0 accedido:133 modificado:1
frame 1  pid:1 pagina:1 accedido:134 modificado:1
frame 2  pid:1 pagina:4 accedido:137 modificado:1
frame 3  pid:1 pagina:5 accedido:138 modificado:1
frame 4  pid:1 pagina:8 accedido:144 modificado:0
frame 5  pid:2 pagina:1 accedido:119 modificado:0
frame 6  pid:1 pagina:2 accedido:135 modificado:1
frame 7  pid:1 pagina:6 accedido:139 modificado:1
frame 8  pid:3 pagina:0 accedido:124 modificado:0
frame 9  pid:1 pagina:3 accedido:136 modificado:1
frame 10  pid:1 pagina:7 accedido:142 modificado:1
frame 11  pid:3 pagina:1 accedido:129 modificado:0
el resultado esperado dice:

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-41b1fe40-7fff-f41f-f1ab-7641bc729b00"><div dir="ltr" style="margin-left:0pt;" align="left">

C1P0 | C1P1 | C2P0 | C1P4 | C3P0 | C1P5 | C1P2 | C1P6 | C1P7 | C1P3 | C2P3 | C3P3
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

</div></b>
</body>
</html>

Pero C2P1 tiene acceso mas reciente que C2P3 y C2P0 y no se reemplaza. C2P0 y C2P3 se reemplazan con paginas de C1
mismo C3P1 con C3P3, ademas de la pagina 8 de p1 alocada que contiene el heapmetadata 

en clock, me da un resultado similar al de las pruebas, pero en diferente orden

CLOCK
frame 0  pid:1 pagina:4 accedido:0 modificado:1
frame 1  pid:1 pagina:0 accedido:0 modificado:1
frame 2  pid:1 pagina:1 accedido:0 modificado:1
frame 3  pid:1 pagina:5 accedido:0 modificado:1
frame 4  pid:1 pagina:6 accedido:0 modificado:1
frame 5  pid:1 pagina:7 accedido:0 modificado:1
frame 6  pid:1 pagina:2 accedido:0 modificado:1
frame 7  pid:1 pagina:8 accedido:1 modificado:0
frame 8  pid:2 pagina:1 accedido:0 modificado:0
frame 9  pid:1 pagina:3 accedido:0 modificado:1
frame 10  pid:3 pagina:0 accedido:0 modificado:0
frame 11  pid:3 pagina:1 accedido:0 modificado:0

hice las pruebas a mano, y me da lo mismo que en mi ejecución

**Comment by ncoen97** [comment]
Buenas, estuve revisando las pruebas.

En la de LRU no encontré errores y no coincido con los resultados que obtuviste. Teniendo en cuenta que antes de hacer los ultimos allocs hacemos memreads a todas las páginas 0, esas deberían quedarse en la memoria y no ser elegidas por LRU. Si te fijas en tus resultados, la página 0 del carpincho 2 que estaba en el frame 2 no debería ser reemplazada por esa razón. Otro caso raro que veo es que tu timestamp de carpincho 3 pag 0 es menor que el de la pag 1 y no debería ser así por esos memread que mencioaba.

Con respecto a la de CLOCK, si encontré que nos comimos algunos accesos cuando hicimos los resultados de las pruebas. A los que llegaste son correctos.

Gracias por el aviso! Lo vamos a tener en cuenta para ajustar el doc.
Cualquier consulta que te quede no dudes en preguntar.

**Comment by alejcha** [comment]
gracias, me quedo tranqui entonces con el CLOCK
el LRU sigue sin darme lo de las pruebas.
tengo del ultimo commit que las ultimas ejecuciones son:

C2 - Leo de la   página 0
C2 - Leo de la página 1
C3 - Leo de la página 0
C3 - Leo de la página 1
C1 - Escribo en la página 2
C1 - Escribo en la página 3
C1 - Escribo en la página 4
C1 - Reservo un alloc de 21 bytes

por lo que C3P1>C3P0>C2P1>C2P0>C2P3
y luego todas las paginas de C1 se leen y deben estar en memoria incluida la 8 del ultimo alloc

Gracias

**Comment by ncoen97** [comment]
Creo que ya se por qué. Las pruebas de LRU son con los carpinchos de `PruebaAsignacion.c`.

**Comment by alejcha** [comment]
Ah, con razon tanta diferencia,
ahi estuve probando con ese, me queda un poco mas parecido, pero tengo aun diferencias, veo que los FdP se producen con las ejecuciones finales:

a) C1 - Reservo un alloc de 23 bytes
b) C1 - Reservo un alloc de 23 bytes
C1 - Reservo un alloc de 23 bytes
C1 - Reservo un alloc de 23 bytes

en a) esta ok.
en b)
al intentar escribir del C1 la pagina 5 produce el FP y segun el documento va al frame 5 
el frame 5 tenia el pid:3 pagina:1
ese frame fue accedido cuando el carpincho hizo el ultimo memalloc son size 10

pero a mi me da que la victima es en el frame 7  pid:2 pagina:2
el ultimo acceso al F7 fue cuando el carpincho 2 hizo el ultimo memalloc son size 10
el memalloc 10 de C2 fue anterior al de C3, por lo que estaria correcto, no se hizo otro acceso a esas paginas
despues de ahi ya cambia ligeramente todo, al finalizar todo me queda

frame 0  pid:1 pagina:0 accedido:122 modificado:1
frame 1  pid:1 pagina:1 accedido:123 modificado:1
frame 2  pid:2 pagina:0 accedido:84 modificado:1
frame 3  pid:1 pagina:4 accedido:127 modificado:1
frame 4  pid:3 pagina:0 accedido:85 modificado:1
frame 5  pid:1 pagina:7 accedido:132 modificado:0
frame 6  pid:1 pagina:2 accedido:124 modificado:1
frame 7  pid:1 pagina:5 accedido:128 modificado:1
frame 8  pid:3 pagina:2 accedido:76 modificado:1
frame 9  pid:1 pagina:3 accedido:126 modificado:1
frame 10  pid:1 pagina:6 accedido:130 modificado:1
frame 11  pid:3 pagina:3 accedido:79 modificado:1

lo que tendria sentido ya que las paginas del c3 fueron accedidas en el ultimo alloc 10, que fue posterior al memalloc 10 del C2, luego del ese memalloc C2 solo accede a C2P0 (en el memwrite) y nada mas, por lo que los reemplazos son sobre C2P1,C2P2,C2P3 y C3P1 que fue accedida en el memalloc 10 antes que C3P2 Y C3P3 (C3P0 se accedio posteriormente en el memwrite)


Saludos

**Comment by ncoen97** [comment]
Okay, ahí revise los casos que me decis y es correcto como les quedó. Dejo los resultados fixeados, gracias!

**Comment by RodrigoLista** [comment]
Buenas noches. Al igual q lo mencionado en el issue #2460 , a nosotros también nos da diferente al estado De la prueba. Adjunto documento con los resultados concluidos en nuestra prueba. 

[PruebaAsignacion_Dinamica_y_LRU.txt](https://github.com/sisoputnfrba/foro/files/7606839/PruebaAsignacion_Dinamica_y_LRU.txt)
