### ISSUE TITLE
[Prueba suspensión] No se da suspensión

### ISSUE THREAD

**Issue by NicolasWallovits** [sisoputnfrba/foro#2452]
Buenas, como va? Quería consultar por la prueba de suspensión, porque no veo que debería entrar ningún carpincho a suspensión, dado que se crean 4 carpinchos en total, y el grado de multiprogramación por config debería ser = 4, por ende nunca nadie se queda esperando.
```c
int main(int argc, char *argv[]) {

	pthread_t carpincho1;
	pthread_t carpincho2;
	pthread_t carpincho3;
	pthread_t carpincho4;

	printf("MAIN - Utilizando el archivo de config: %s\n", argv[1]);

	pthread_create(&carpincho1, NULL, carpincho1_func, argv[1]);
	sleep(1);
	pthread_create(&carpincho2, NULL, carpincho2_func, argv[1]);
	sleep(1);
	pthread_create(&carpincho3, NULL, carpincho3_func, argv[1]);
	sleep(1);
	pthread_create(&carpincho3, NULL, carpincho4_func, argv[1]);

	pthread_join(carpincho4, NULL);
	pthread_join(carpincho3, NULL);
	pthread_join(carpincho2, NULL);
	pthread_join(carpincho1, NULL);

	printf("MAIN - Retirados los carpinchos de la pelea, hora de analizar los hechos\n");

	return EXIT_SUCCESS;
}
```
![image](https://user-images.githubusercontent.com/82244719/143457765-d9284437-9459-4d90-b225-0548ce8b72bb.png)

Saludos!

**Comment by RaniAgus** [comment]
¡Buenas! Efectivamente, la prueba original estaba pensada con `GRADO_MULTIPROGRAMACION=2` para que los carpinchos 3 y 4 queden en new y se haga la suspensión. Al parecer hubo un cambio de último momento que no se aplicó y quedó con `4`. En un ratito hacemos la corrección y lanzamos el announcement.

¡Gracias por avisar!
Saludos

**Comment by iago64** [comment]
@NicolasWallovits Ahora con la aclaración que hizo Agus pudieron correr la prueba y vieron si se dan los casos de suspensión?

**Comment by NicolasWallovits** [comment]
Sí ahora sí se suspenden sin drama. Gracias!
