### ISSUE TITLE
[Prueba Batalla Por Nordelta] Carpincho caído en combate

### ISSUE THREAD

**Issue by NicolasWallovits** [sisoputnfrba/foro#2453]
Buenas, como va? No me odien, sé que estoy en todos los issues. Pero encontré un problema con la prueba de Batalla por Nordelta, y es que entre los resultados esperados, todos los carpinchos deberían poder terminar sin inconvenientes. Sin embargo uno de ellos (carpincho2_func) queda bloqueado porque inicializa un semaforo (smirnoffc2) con un valor de 0, y se va a bloquear 2 veces, pero sólo una vez lo desbloquea otro carpincho. Entonces luego del segundo wait, muere ahí. Quizás la idea era en realidad inicializarlo con valor = 1?

Saludos!

**Comment by iago64** [comment]
Buenas!

Si señor, fue un desliz, era un 1 en el semaforo, gracias por el aviso, se ve que justo le pego fuerte al fondo blanco de smirnoff 😄 

Saludos.-

**Comment by NicolasWallovits** [comment]
Hola Damian,

Perdón que reabra el issue del pobre carpincho muerto. Pero parece que ahora incluso con el sem_post, por un tema de planificación, no llega tampoco a desbloquearse (como por 1.5 segundos). Por lo que veo en nuestro log, parece que el post que hace carpincho3_func se termina dando antes de que carpincho2_func pueda inicializar el semaforo:

![image](https://user-images.githubusercontent.com/82244719/143624135-9d80ed16-1b7b-49b4-9d90-9cf243ec742d.png)

Probé agregandole una solicitud de I/O antes de que haga el post, y asi sí logra llegar antes y terminan todos:
![image](https://user-images.githubusercontent.com/82244719/143627170-fc4d01ea-8ef1-4e75-997b-c07c165c2df3.png)


Y ya que estamos... que no hace nada al funcionamiento pero aviso por si quieren corregirlo, en carpincho7_func en el loop b nunca incrementa, o sea que siempre imprime "Vuelta número 0":

	printf("C7 - Un par de vueltas con semáforos... \n");
	int a = 1;
	int b = 0;
	while (a <= 256) {
		mate_sem_post(&instance, "SEMAFORO_NUEVO");
		usleep(5000);
		mate_sem_wait(&instance, "SEMAFORO_NUEVO");
		printf("C7 - Vuelta número %d... \n", b);
		a++;
	}

Gracias, saludos!

**Comment by RaniAgus** [comment]
[¡Fixeado!](https://github.com/sisoputnfrba/carpinchos-pruebas/commit/da184a02c1422bb332bba2add075379e1b34dc70) 😉 
Gracias de nuevo, saludos

**Comment by NicolasWallovits** [comment]
Gracias!

**Comment by sofiacortez** [comment]
Hola! reabro el issue porque vi que agregaron un mate_sem_init en el carpincho 3 del semáforo smirnoffc2 previo al post que hace, lo que provoca que el semáforo se inicialice 2 veces (una por el carpincho 2 y otra por el 3). Lo cual creemos que esta generando un bloqueo en nuestro caso (o por lo menos un problema, ya que no manejamos el error de inicializar dos veces un semaforo).
