### ISSUE TITLE
[Pruebas Kernel] ALFA = 1 da error

### ISSUE THREAD

**Issue by federiver91** [sisoputnfrba/foro#2454]
Buenas!!

Separo este tema del otro issue para darle un mejor seguimiento ya que es algo bastante más puntual.

Para las pruebas del Kernel (Suspension, Deadlock y BatallaPorNordelta) el valor de ALFA es igual a "1" en el documento de Pruebas. Creemos que esto va a traer errores de cara a las ecuaciones de SJF y, sobre todo, de HRRN. Esto se produce debido a que nos llevaría a dividir por 0 en caso de que el algoritmo sea HRRN y sea la primera ejecución de un carpincho (es decir, no tenga RAFAGA REAL ANTERIOR).

![image](https://user-images.githubusercontent.com/49326422/143465286-ff92be79-702a-4db5-8082-93dfd5251852.png)

**Comment by RaniAgus** [comment]
¡Buenas! Recordá que en la teoría la idea de "estimación inicial" es, justamente, _el primer valor que debe tomar la estimación_, sin necesidad de pasar por ninguna fórmula. Es decir que la primera vez que estimes SJF el valor va a ser para todos:
```c
rafaga_estimada_sjf = estimacion_inicial;
```
Y recién después de que se ejecute la primera ráfaga vas a poder armar la siguiente `rafaga_estimada_sjf` usando la fórmula, teniendo como `estimacion_anterior` el valor de la `rafaga_estimada_sjf` anterior (o sea, `estimacion_inicial`).

Saludos

**Comment by federiver91** [comment]
Okas, yo lo habia pensado distinto pero bueno..
Ya lo corregí. GRacias!!
