### ISSUE TITLE
Duda memoria  - conocer tamaño del alloc

### ISSUE THREAD

**Issue by RodrigoLista** [sisoputnfrba/foro#2456]
Buenas, tengo una consulta. Se habia dicho que se podia utilizar estructuras administrativas de los allosc en la memoria, siempre y cuando no repliquen la informacion contenida en los heaps.
La duda es la siguiente. Para calcular o conocer el size de un alloc, podria mantenerlo en una estructura administrativa o tendria que calcularlo a traves del heap?

Esto me generaria discrepancias en los ingresos a memoria. 
En el primer caso, suponiendo que quiero hacer un mem alloc, empiezo a iterar la lista de allocs, encuentro el primer elemento, y suponiendo que tiene un menor tamaño al solicitado, directamente pasaria al segundo elemento.
En cuanto al segundo caso, una vez que encuentre el primer alloc, va a leer si o si su metadata para poder calcular su size y a su vez conocer si esta libre.

Esto me daria segundo caso un acceso a memoria mientras que en el primero, no tendria acceso a memoria ante esa situacion.

Muchas gracias.

**Comment by ncoen97** [comment]
Buenas, para el caso del alloc van a tener que iterar dentro de la memoria principal para leer la metadata, esa info no pueden tenerla en estructuras administrativas.
Saludos!

**Comment by RodrigoLista** [comment]
Perfecto. Solo que el tamaño del alloc no está guardado en su metadata. Es un valor que podría calcularse con uno de los valores de su heap, ya sea next o prev alloc, y su dirección lógica, la cual no está guardada en su heap.  Por ende, si me baso en eso, yo podría conocer el size del alloc sin entrar al heap, ya q no es uno de los 3 valores específicos que posee el heap. 

Muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

Solo para aclarar mas que nada por si alguien mas lee el issue, me parece que la confusión viene por el lado de que se están mezclando las responsabilidades, ya que por un lado tienen la responsabilidad a nivel SO que es la de mantener las páginas y por otro la responsabilidad a nivel "usuario" (_que en c es la famosa stdlib.h_) que es la de hacer los alloc / free.
En el primer caso, pueden tener estructuras administrativas para gestionar todo, ya que el mismo SO en la realidad tiene estructuras que resuelven estas problemáticas como vieron en la teoria.
En el segundo caso, los alloc son algo definido a nivel usuario, es decir que los heapMetadata son datos del usuario para el SO y no deberían tener estructuras extra (pueden tenerlas? si, pero no puede influir en el resultado). Un poco mas a detalle y casi pisando una pregunta de coloquio / teoría, si tuvieran la info de porciones de memoria variables como pueden ser los allocs... estamos en una _paginación pura_, en una _segmentación pura_ o en una _segmentación paginada_? La respuesta a esta última pregunta es la que te da la pauta de que pueden estar desviándose del enunciado del tp donde se aclara que la memoria memoria usa un esquema de **paginación pura**

Dicho lo anterior y reforzando lo que dijo Nico, para un alloc, guste o no tienen que recorrer todas las páginas donde tengan los heapMetadata y para ello tienen que traerlas a memoria principal.

Saludos.-

**Comment by RodrigoLista** [comment]
Perfecto. Se entendió. Muchas gracias. Cierro issue.
