### ISSUE TITLE
[Pruebas Memoria] kernel no replanifica

### ISSUE THREAD

**Issue by FBanfi** [sisoputnfrba/foro#2457]
Hola, buenas noches!

Estuvimos viendo las pruebas de memoria de MMU y TLB y tenemos un problema a la hora de ejecutar varios carpinchos con grado de multiprocesamiento = 1. Se genera un conflicto ya que se usan las instrucciones sem_wait()/sem_post() que no pertenecen a nuestra biblioteca, por lo que el kernel no va a saber que hay que replanificar. Entonces el carpincho que entre a ejecutar, por mas de que se haga un sem_wait() y se trabe, no va a salir de execute y por lo tanto nunca se va a ejecutar el segundo. 

No se deberían usar las instrucciones mate_sem_wait()/mate_sem_post() una vez se hayan hecho los mate_init() para que así el kernel pueda saber cuando replanificar y ejecutar otro carpincho? 
Y usar los sem_wait()/sem_post() simplemente para el orden de entrada de los hilos?

Desde ya gracias, saludos!

**Comment by TiagoQuinteros** [comment]
Estamos con el mismo problema hace varios dias, estuvimos probando con multiprocesamiento y multiprogramación en 3

**Comment by iago64** [comment]
Buenas! Cómo va?

Estamos revisando este caso, pero a priori pueden probar utilizando la config de kernel de la prueba de asignación.
Respecto a la prueba de TLB No haría falta modificar nada ya que en la prueba de LRU hay 1 solo hilo y en el caso de la prueba de FIFO los carpinchos deberían alternarse por usar semáforos de la lib.

Saludos.-

**Comment by FBanfi** [comment]
Buenísimo gracias! probamos con el config de asignación entonces.
Y en el caso de la prueba de FIFO, creemos que no usa los semáforos de la lib y por eso no se alterna.

**Comment by iago64** [comment]
Buenas!

Es verdad, en la de fifo usan los sem comun, lo vi rapido y me parecio leer que eran los semaforos de la lib. Prueben utilizando la config de asignación para el kernel y deberían tener la alternancia.

Saludos.-

**Comment by kamipalomino** [comment]
buenas, aprovecho el issue, las pruebas de memoria no se pueden ejecutar sin el kernel, no?

saludos

**Comment by iago64** [comment]
Buenas @kamipalomino !

En principio no se pueden porque usan además de la memoria algunas cosas mínimas de kernel como ser el mate_init.

Saludos.-

**Comment by kamipalomino** [comment]
Perfecto, gracias.

Saludos 😺

**Comment by iago64** [comment]
@FBanfi Cómo va? Te queda alguna duda?

**Comment by FBanfi** [comment]
Buenas! Nono, todo bien, hicimos eso que dijiste.

Me había olvidado de cerrar el issue, muchas gracias!!
