### ISSUE TITLE
configuración de archivo de bash para la entrega 

### ISSUE THREAD

**Issue by santiagocorbalan** [sisoputnfrba/foro#2458]
¡Hola! ¿Cómo están? Quería saber si me podían ayudar a configurar el deploy para el sábado 😬, pudimos configurar para que clone el repositorio de las commons library (y también para que las instale) y los carpinchos de prueba peeeero ahí es donde tengo 2 dudas.

1. Se supone que antes de hacer un make compile en el repo de carpinchos-prueba tengo que declarar la variable de entorno **LD_LIBRARY_PATH**, en mi caso el path de la mate lib es "/home/utnso/tp-2021-2c-UCM-20-SO/MateLib/src" (en la carpeta src tenemos tanto el .h como el .c para simplificar los directorios). ¿ Cómo podría hacer esto en mi archivo de bash? ¿En el caso de que no se pueda, que nos recomiendan que hagamos?
2. Nosotros en el makefile del repo de carpinchos-prueba modificamos la variable LIB  **-lmatelib** por **-lmate** y en el flag **-I** agregamos la ruta donde está el header de la matelib (en nuestro caso es "/home/utnso/tp-2021-2c-UCM-20-SO/MateLib/src").

### Archivo de bash que tenemos actualmente

> 
> #!/bin/bash
> length=$(($#-1))
> OPTIONS=${@:1:$length}
> REPONAME="${!#}"
> CWD=$PWD
> echo -e "\n\nInstalando commons Library, o eso creo...\n\n"
> COMMONS="so-commons-library"
> git clone "https://github.com/sisoputnfrba/${COMMONS}.git" $COMMONS
> cd $COMMONS
> 
> sudo make uninstall
> make all
> sudo make install
> 
> echo -e "\n\n Instalando las pruebas de carpinchoide... \n\n"
> git clone "https://github.com/sisoputnfrba/carpinchos-pruebas.git"
> PRUEBACARPINCHO="carpinchos-pruebas"
>  ***Acá antes de hacer un make compile deberíamos declarar la variable de entorno LB_LIBRARY_PATH (si no entendí mal) y además deberíamos poder modificar ese flag "-I" y ponerle el path donde está nuestra cabecera de la matelib ***
> 
> cd $CWD
> echo -e "\n\nCompilando el proyecto...\n\n"
> make -C ./SWAmP
> make -C ./Memoria
> make -C ./Kernel
> make -C ./MateLib
> echo -e "\n\nDale boooooo, dale boooo!\n\n"

Disculpen si quedó muy desprolijo el issues, no suelo hacerlos 😬. ¡Muchas gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Me encanta que esten pensando en hacerse un script en bash para hacerse mas fácil los deploy.
Algo interesante que tiene el LD_LIBRARY_PATH es que es una vía de escape al problema de no poder guardar archivos en el repositorio de utilidades de usuario o también conocido en ingles como _User System Resources_  o por su path `/usr`, que generalmente se da cuando no se tienen los permisos suficientes, cosa que aca no nos pasa porque tienen el poder del `sudo`.

Una salida muy "elegante" que pueden tener para no complicarse, es copiar su archivo .so dentro del directorio `/usr/lib` como se hace en el [makefile de las commons](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/makefile).
Lo único que puede molestar de esto es que lo tienen que correr con sudo, pero dado que ya es algo que estan haciendo al instalar las commons, no creo que sea algo tan pesado 😄 

Respecto al header de la matelib, algo copado es que el repo de los carpinchos de prueba ya tiene el matelib.h y lo copia en otro directorio dentro de `/usr` que es el directorio `/usr/include` donde estan todos los .h que usamos habitualmente, como por ejemplo `stdio.h` o `stdlib.h` por lo que no tendrian que preocuparse en modificar mucho el makefile del repo de los carpinchos.

Cualquier otra duda avisa y lo vemos.
Saludos.-

P.D: El issue estuvo super prolijo 😄

**Comment by santiagocorbalan** [comment]
Hola Dami! Muchas gracias por la ayuda, casi que pudimos hacer funcionar nuestro archivo de bash pero tengo una consulta que es lo que no me está funcionando. 

- En el makefile de [carpinchos-pruebas](https://github.com/sisoputnfrba/carpinchos-pruebas/blob/master/makefile), especialmente en la variable LIBS, que significa **-lmatelib**? Porque no me lo estaría reconociendo, en cambio, en vez de poner lmatelib pongo **lmate** (cómo está en el makefile del repo de [ejemplo la matelib](https://github.com/sisoputnfrba/matelib/blob/main/Makefile)) y ahí si compila las pruebas. 

###Dejo un screen del mensaje que me tira con -lmatelib: 
<img width="756" alt="image" src="https://user-images.githubusercontent.com/62735838/143589553-f8c7d7a3-4409-499e-968f-adc5b36e6e30.png">

### Dejo actualizado el archivo de bash que tenemos hasta ahora

> #!/bin/bash
> length=$(($#-1))
> OPTIONS=${@:1:$length}
> REPONAME="${!#}"
> CWD=$PWD
> echo -e "\n\nInstalando commons Library, o eso creo...\n\n"
> COMMONS="so-commons-library"
> git clone "https://github.com/sisoputnfrba/${COMMONS}.git" $COMMONS
> cd $COMMONS
> 
> sudo make uninstall
> make all
> sudo make install
> 
> cd ..
> PRUEBACARPINCHO="carpinchos-pruebas"
> echo -e "\n\n Instalando las pruebas de carpinchoide... \n\n"
> git clone "https://github.com/sisoputnfrba/carpinchos-pruebas.git" $PRUEBACARPINCHO
> 
> 
> 
> cd $CWD
> echo -e "\n\nCompilando el proyecto...\n\n"
> make -C ./SWAmP
> make -C ./Memoria
> make -C ./Kernel
> make -C ./MateLib
> 
> echo -e "\n\n Copio la matelib a /usr/lib"
> sudo cp -u MateLib/src/libmate.so /usr/lib
> ls -a
> echo -e "\n\n Compilar los carpinchos de prueba\n\n"
> cd $PRUEBACARPINCHO
> make compile
> echo -e "\n\nDale boooooo, dale boooo!\n\n"
> 

Hago la consulta porque tal vez es algo que tengo mal configurado yo, muchas gracias nuevamente por la ayuda!
Saludos.

**Comment by iago64** [comment]
Buenas!

**-lmatelib** o **-lmate** son las referencias a la lib, lo que paso fue que en muchos casos vimos que usaban mas matelib que mate como nombre de la biblioteca porque asi estaba en el enunciado y bueno, le pusimos _-lmatelib_ en el makefile de los carpinchos, pero si para uds es _-lmate_, acuérdense de eso a la hora de compilar o bien suban el makefile de las pruebas modificado a su repo y listo, problema resuelto 😄 

Saludos.-

**Comment by santiagocorbalan** [comment]
Perfecto, ahí lo solucionamos, mil gracias Dami! 
Saludoss
