### ISSUE TITLE
Dudas de mate_instance e implementacion de comunicacion

### ISSUE THREAD

**Issue by Nicolas-Russo** [sisoputnfrba/foro#2459]
Buenas, queria saber si se puede modificar la estructura mate_instance porque nostros la modificamos y nos quedo algo asi:
```
typedef struct{
 int id;
 float estimacionProxRafaga;
 float tasaRespuesta;
 time_t tiempoInicialEnReady;
 time_t tiempoInicialEnExec;
 time_t tiempoDeEjecucionRafagaAnterior;
 int conexion;
}mate_instance;
```
En vez de tenerlo asi:
```
typedef struct{
 void* group_info;
}mate_instance;
```
Para asi poder modificar el id del carpincho y poder tenerlo cada vez que se haga una de la peticiones.
Se puede hacer asi o tendriamos que tener todo dentro del group_info;

Otra duda que tenemos es:
Si por cada carpincho se tiene que crear una conexion y mantener hasta el mate_close o se puede crear una conexion por cada peticion que el carpincho hace, y en el mate_close lo que se hace es pasarlo a la lista de exit y listo. Espero que se entienda la idea.

Gracias!

**Comment by ncoen97** [comment]
Buenas.
1. El struct con toda la info que necesiten para la lib tiene que estar adentro del `group_info`.
2. Ambas son opciones posibles.

Saludos!
