### ISSUE TITLE
problema con una funcion de la libreria de commons en eclipse

### ISSUE THREAD

**Issue by GuidoOliveri** [sisoputnfrba/foro#246]
buenas, cómo andan? ando con el siguiente tema: ejecuto por terminal el archivo de configuracion y el de log y no hay ningun problema, ahora ejecuto por eclipse y no aparece lo mismo que por terminal. 
Aparece esto: 
"el archivo de configuraciones se esta leyendo: configSwap " (es un printf que puse yo, configSwap es el nombre del archivo) 

Pero después deberían aparecer los printf con los valores del puerto, el retardo de la compactación y todo lo que tiene el archivo de config que lo printié,

Debuggié el programa y lo que me apareció fue lo siguiente: 

*_No source available for "config_get_string_value() at 0xb7fc2c6a" *_

Bueno, si alguién me puede ayudar desde ya se agradece !

**Comment by JuanQP** [comment]
No sé si es lo mejor dejar escrito acá en el issue porque ya está cerrado, pero me gustaría dejar resumido mi historia que es bastante parecida a lo que comentan, y luego de luchar mucho en StackOverflow no encontré nada que me ayude (y encontré la respuesta en este issue).

Mi proceso se ejecuta recibiendo un argumento. Así que configuré el debugger para que acepte como argumento algo como `prueba.cfg`. Este archivo estaba dentro de `Debug/`, como ahí va el binario asumí que si ponía un path relativo `prueba.cfg` el primer lugar en buscar iba a ser en esa carpeta, pero **no**.

Arrancaba debuggeando como un campeón pero cuando llegaba a una parte que utilizaba `config_get_string_value()` explotaba miserablemente, sin poder saber por qué, pero el mensaje era este:

![imagen](https://user-images.githubusercontent.com/11776905/30296850-f780c210-971b-11e7-9677-2e56e89c9b34.png)

El error básicamente me dice "*No te puedo mostrar el fuente de esa función*", pero yo no quería saber éso, yo quería saber por qué estaba explotando. Parece que Eclipse, al explotar, me quería mostrar la línea que falló, pero en lugar de decirme "*No abriste ningún archivo!*", me mostraba el último error: "*No tengo el fuente de la parte donde explotó*".

Moví el archivo `Debug/prueba.cfg` un nivel hacia arriba (hacia el root de ese proyecto), como sugirieron en este issue, y lo que ocurre ahora (que puedo debuggear esa parte) es que abre correctamente el archivo y me deja obtener la información.
