### ISSUE TITLE
Diferencia en reemplazo PruebaAsignacion.c

### ISSUE THREAD

**Issue by Jrigada** [sisoputnfrba/foro#2460]
Buenas noches, estuvimos probando las pruebas de Memoria Reemplazo MMU con LRU corriendo el carpincho **PruebaAsignacion.c** y llegamos en un momento a un reemplazo de marco distinto. Una vez que la memoria esta llena en el segundo reemplazo de pagina llega la peticion del carpincho 1 para la pagina 5 y segun nuestras pruebas deberia reemplazar al carpincho 3 pagina 1 con marco 5. 
En las pruebas dice que reemplaza al carpincho 2 pagina 2 marco 7 pero este uso por ultima vez en un momento posterior. 

Nosotros tenemos como ultimo uso del carpincho 3 pagina 1 la peticion numero 11 y como ultimo uso del carpincho 2 pagina 2 la peticion numero 15. 

Muchas gracias!

**Comment by ncoen97** [comment]
Buenas, quedó explicado en el #2451, cualquier duda nos consultan. Saludos!

**Comment by RodrigoLista** [comment]
Buenas noches. Al igual q lo mencionado, a nosotros también nos da diferente al estado De la prueba del issue #2451 . Adjunto documento con los resultados concluidos en nuestra prueba.

[PruebaAsignacion_Dinamica_y_LRU.txt](https://github.com/sisoputnfrba/foro/files/7606885/PruebaAsignacion_Dinamica_y_LRU.txt)

**Comment by TiagoQuinteros** [comment]
@ncoen97 creo que la diferencia esta en que en el tp del hilo #2451, acceden a todas las paginas cada vez que hacen un alloc, como lo encaramos nosotros, no es necesario dejar en memoria todas las paginas, sino que solo las que se necesitan para allocar.

**Comment by RodrigoLista** [comment]
> @ncoen97 creo que la diferencia esta en que en el tp del hilo #2451, acceden a todas las paginas que contienen un alloc, cada vez que hacen un alloc, como lo encaramos nosotros, no es necesario dejar en memoria todas las paginas, sino que solo las que se necesitan para allocar.

En el issue #2431 se menciona esta situación.

**Comment by gastoncastineira** [comment]
Buenas! @RodrigoLista @TiagoQuinteros 
Por lo que entiendo de ese issue que pasaron ustedes no se traen todas las páginas cuando un alloc es más grande que una página porque solo tienen que escribir el alloc en la primer página, cosa que está perfecto, pero esa situación no se da en esta prueba del TP. 
No me queda claro como a partir de eso es que tienen menos accesos a memoria. Puede ser la misma situación de #2379?

**Comment by TiagoQuinteros** [comment]
Buenas, me explique mal, nosotros tenemos un acceso menos en memoria porque no accedemos a la pagina 0 donde esta el primer alloc, sino directamente cargamos las que necesitamos para el nuevo alloc, ya hicimos un cambio para que cargue todos las paginas donde hay un heap_meta_data previo, pero no se porque es necesario

**Comment by RodrigoLista** [comment]
> Buenas! @RodrigoLista @TiagoQuinteros
> Por lo que entiendo de ese issue que pasaron ustedes no se traen todas las páginas cuando un alloc es más grande que una página porque solo tienen que escribir el alloc en la primer página, cosa que está perfecto, pero esa situación no se da en esta prueba del TP.
> No me queda claro como a partir de eso es que tienen menos accesos a memoria. Puede ser la misma situación de #2379?

Buenas. Encontramos el posible error con el que contamos. Falta una actualizacion de LRU en algunas paginas. Posiblemente al momento de la busqueda de un alloc free, para hacer un mem alloc.

El tema seria el siguiente. Cuando los carpinchos mandan a allocar el bloque de size 10, se terminan leyendo todas las paginas de cada uno de los carpinchos, ya que todas poseen metadata.

Por lo tanto, primero manda el C1, luego C2 y luego C3. Entonces quedarian como paginas mas antiguas todas las del C1, luego las del C2 y luego las del C3, todas en orden ascendente.

Seguidamente, el C1 manda a escribir todas las paginas que posee hasta ese momento (0,1,2,3), por lo tanto, se actualizaria su LRU, y quedarian como paginas mas antiguas, todas las del C2 en orden ascendente, luego todas las del C3 en orden ascendente y por ultimo, todas las paginas de C1 pero en orden descendente.

Despues C2 y C3 leen sus paginas 0, por lo tanto estas se actualizan y quedan como las mas nuevas. Quedando como próximo remplazo las paginas restantes de C2 (orden ascendente), las paginas restantes de C3 (orden ascendente), todas las paginas de C1 (orden descendente) y por ultimo pagina 0 de C2 y C3.

Por ultimo, el C1 realiza 4 mem alloc, por lo que en cada busqueda de un alloc correspondiente, se van a actualizar todas sus paginas nuevamente. Para realizar los allocs, voy a tener que crear y traer a memoria 4 paginas mas. Por lo que quedarian como victimas para remplazo, todas las paginas de C2, a excepcion de pag 0 que habia sido usada, y como cuarta pagina victima quedaria la pag 1 del C3.

Ahora buscaremos donde nos olvidamos de la actualizacion del LRU, para que los resultados de la prueba se ajusten a esto.

Muchas gracias

**Comment by ncoen97** [comment]
@TiagoQuinteros Buenas!
Deberían acceder siempre a la página 0, porque sino cómo saben donde está el 2do alloc? La única forma debería ser leyendo el 1ro y viendo el campo nextAlloc.
