### ISSUE TITLE
[Prueba Suspension] No se suspende en el orden que debería

### ISSUE THREAD

**Issue by amendezkar** [sisoputnfrba/foro#2461]
Buenas, tengo una duda sobre el resultado esperado de la prueba de suspensión, y es que lo que se espera que pase es que teniendo los carpinchos 1 y 2 en la cola de block, cuando ingrese el carpincho 3, se suspenda el 1 y cuando ingrese el 4, se suspenda el 2.

Pero esto sería correcto?

Porque el enunciado dice que se tiene que suspender el último en haber ingresado a la cola de block, con lo cual, cuando ingresa el 3, se debería suspender el 2 (porque es el último que ingreso a la cola de block), y cuando ingresa el 4, se debería suspender el 3.

Gracias de antemano, saludos.

**Comment by iago64** [comment]
Buenas! Cómo va?

Efectivamente primero debería suspenderse el 2 y luego el 1, igual sería bueno que nos pases algo mas de info porque siento que esta habiendo una situación borde y estaría bueno analizarla.

Saludos.-

**Comment by amendezkar** [comment]
Tal vez me expresé mal, mi pregunta era si es correcto esperar que se suspendan el 1 y el 2 como dice la prueba.

Porque cuando el carpincho 3 ingresa a New y el sistema se ve en la necesidad de suspender un carpincho de los que están en Block, suspende el carpincho 2 porque es el último que ingresó a la lista de bloqueados (tal como indica el enunciado), de esta forma queda:
Block: 1, 3
Block-Suspended: 2

Después cuando ingresa el carpincho 4 a New, el sistema necesita suspender otro carpincho mas, y teniendo en cuenta que el 1 y el 3 están en Block, siendo que el 3 es el último que ingresó a la lista de Block, entonces según el enunciado del tp se debería suspender al 3, de forma que queda:
Block: 1, 4
Block-Suspended: 2, 3

Estos son los logs:

[INFO] 19:35:31:882 kernel/(25142:25142): [NEW] Entra el carpincho de PID: 1 a la cola.
[INFO] 19:35:31:882 kernel/(25142:25146): [NEW] Se saca el carpincho de PID: 1 de la cola
[INFO] 19:35:31:882 kernel/(25142:25146): [POTENCIALES RETENSORES DE SEMAFOROS] Entra el carpincho de PID: 1 a la lista.
[INFO] 19:35:31:882 kernel/(25142:25146): [READY] Entra el carpincho de PID: 1 a la cola.
CARPINCHOS EN READY: 1 
[INFO] 19:35:31:883 kernel/(25142:25147): [EXEC] Ingresa el carpincho de PID: 1 con una rafaga de ejecucion estimada de 1000.000000 milisegundos.
[INFO] 19:35:31:922 kernel/(25142:25427): [BLOCK] Entra el carpincho de PID: 1 a la cola.
[INFO] 19:35:32:883 kernel/(25142:25142): Cliente conectado a kernel

[INFO] 19:35:32:884 kernel/(25142:25142): [NEW] Entra el carpincho de PID: 2 a la cola.
[INFO] 19:35:32:884 kernel/(25142:25146): [NEW] Se saca el carpincho de PID: 2 de la cola
[INFO] 19:35:32:884 kernel/(25142:25146): [POTENCIALES RETENSORES DE SEMAFOROS] Entra el carpincho de PID: 2 a la lista.
[INFO] 19:35:32:884 kernel/(25142:25146): [READY] Entra el carpincho de PID: 2 a la cola.
CARPINCHOS EN READY: 1 
[INFO] 19:35:32:884 kernel/(25142:25147): [EXEC] Ingresa el carpincho de PID: 2 con una rafaga de ejecucion estimada de 1000.000000 milisegundos.
[INFO] 19:35:32:922 kernel/(25142:25435): [BLOCK] Entra el carpincho de PID: 2 a la cola.
[INFO] 19:35:33:884 kernel/(25142:25142): Cliente conectado a kernel

[INFO] 19:35:33:885 kernel/(25142:25142): [NEW] Entra el carpincho de PID: 3 a la cola.
[INFO] 19:35:33:885 kernel/(25142:25144): [BLOCK] Sale el carpincho de PID: 2 de la cola.
[INFO] 19:35:33:885 kernel/(25142:25144): [BLOCK-SUSPENDED] Ingresa el carpincho de PID: 2 a la cola.
[INFO] 19:35:33:885 kernel/(25142:25146): [NEW] Se saca el carpincho de PID: 3 de la cola
[INFO] 19:35:33:885 kernel/(25142:25146): [POTENCIALES RETENSORES DE SEMAFOROS] Entra el carpincho de PID: 3 a la lista.
[INFO] 19:35:33:885 kernel/(25142:25146): [READY] Entra el carpincho de PID: 3 a la cola.
CARPINCHOS EN READY: 1 
[INFO] 19:35:33:885 kernel/(25142:25147): [EXEC] Ingresa el carpincho de PID: 3 con una rafaga de ejecucion estimada de 1000.000000 milisegundos.
[INFO] 19:35:33:922 kernel/(25142:25437): [BLOCK] Entra el carpincho de PID: 3 a la cola.
[INFO] 19:35:34:885 kernel/(25142:25142): Cliente conectado a kernel

[INFO] 19:35:34:885 kernel/(25142:25142): [NEW] Entra el carpincho de PID: 4 a la cola.
[INFO] 19:35:34:886 kernel/(25142:25144): [BLOCK] Sale el carpincho de PID: 3 de la cola.
[INFO] 19:35:34:886 kernel/(25142:25144): [BLOCK-SUSPENDED] Ingresa el carpincho de PID: 3 a la cola.
[INFO] 19:35:34:886 kernel/(25142:25146): [NEW] Se saca el carpincho de PID: 4 de la cola

Esto que plantié hasta ahora es lo que pasa según el enunciado del tp, pero el enunciado de la prueba parece que espera un orden de suspensión distinto al que plantea el enunciado del tp, probamos que pasaría si se suspendiera el primero que ingresó a Block, y ahí si se cumple el orden de la prueba:

[INFO] 19:42:34:109 kernel/(609:609): [NEW] Entra el carpincho de PID: 1 a la cola.
[INFO] 19:42:34:110 kernel/(609:613): [NEW] Se saca el carpincho de PID: 1 de la cola
[INFO] 19:42:34:110 kernel/(609:613): [POTENCIALES RETENSORES DE SEMAFOROS] Entra el carpincho de PID: 1 a la lista.
[INFO] 19:42:34:110 kernel/(609:613): [READY] Entra el carpincho de PID: 1 a la cola.
CARPINCHOS EN READY: 1 
[INFO] 19:42:34:110 kernel/(609:614): [EXEC] Ingresa el carpincho de PID: 1 con una rafaga de ejecucion estimada de 1000.000000 milisegundos.
[INFO] 19:42:34:149 kernel/(609:871): [BLOCK] Entra el carpincho de PID: 1 a la cola.
[INFO] 19:42:35:111 kernel/(609:609): Cliente conectado a kernel

[INFO] 19:42:35:111 kernel/(609:609): [NEW] Entra el carpincho de PID: 2 a la cola.
[INFO] 19:42:35:112 kernel/(609:613): [NEW] Se saca el carpincho de PID: 2 de la cola
[INFO] 19:42:35:112 kernel/(609:613): [POTENCIALES RETENSORES DE SEMAFOROS] Entra el carpincho de PID: 2 a la lista.
[INFO] 19:42:35:112 kernel/(609:613): [READY] Entra el carpincho de PID: 2 a la cola.
CARPINCHOS EN READY: 1 
[INFO] 19:42:35:112 kernel/(609:614): [EXEC] Ingresa el carpincho de PID: 2 con una rafaga de ejecucion estimada de 1000.000000 milisegundos.
[INFO] 19:42:35:150 kernel/(609:873): [BLOCK] Entra el carpincho de PID: 2 a la cola.
[INFO] 19:42:36:112 kernel/(609:609): Cliente conectado a kernel

[INFO] 19:42:36:113 kernel/(609:609): [NEW] Entra el carpincho de PID: 3 a la cola.
[INFO] 19:42:36:113 kernel/(609:611): [BLOCK] Sale el carpincho de PID: 1 de la cola.
[INFO] 19:42:36:113 kernel/(609:611): [BLOCK-SUSPENDED] Ingresa el carpincho de PID: 1 a la cola.
[INFO] 19:42:36:113 kernel/(609:613): [NEW] Se saca el carpincho de PID: 3 de la cola
[INFO] 19:42:36:114 kernel/(609:613): [POTENCIALES RETENSORES DE SEMAFOROS] Entra el carpincho de PID: 3 a la lista.
[INFO] 19:42:36:114 kernel/(609:613): [READY] Entra el carpincho de PID: 3 a la cola.
CARPINCHOS EN READY: 1 
[INFO] 19:42:36:114 kernel/(609:614): [EXEC] Ingresa el carpincho de PID: 3 con una rafaga de ejecucion estimada de 1000.000000 milisegundos.
[INFO] 19:42:36:150 kernel/(609:875): [BLOCK] Entra el carpincho de PID: 3 a la cola.
[INFO] 19:42:37:113 kernel/(609:609): Cliente conectado a kernel

[INFO] 19:42:37:113 kernel/(609:609): [NEW] Entra el carpincho de PID: 4 a la cola.
[INFO] 19:42:37:114 kernel/(609:611): [BLOCK] Sale el carpincho de PID: 2 de la cola.
[INFO] 19:42:37:114 kernel/(609:611): [BLOCK-SUSPENDED] Ingresa el carpincho de PID: 2 a la cola.
[INFO] 19:42:37:114 kernel/(609:613): [NEW] Se saca el carpincho de PID: 4 de la cola

El tema es que para que pase esto último que dice la prueba se tiene que suspender el primero que ingresó a Block, y el enunciado del tp dice que se tiene que suspender el último que ingresó a Block:

"...El planificador deberá tomar el último elemento en haber ingresado a la cola de bloqueado y pasarlo a suspendido, para dar entrada a nuevos carpinchos esperando el grado de multiprogramación en NEW..."

Perdón si es mucha info de golpe o si me enredé mucho, traté de explicarme lo mas detalladamente posible.
Espero que se entienda la situación que planteo.

**Comment by iago64** [comment]
Buenas!

Ahora si, claramente fue un error de comunicación.
El espíritu de la prueba es que los carpinchos empiecen a ciclar entre si al momento de suspenderse, ya que solo puede haber 2 y son 4 que se están constantemente bloqueando, ahí deje una sugerencia en las pruebas para aclarar un poco mejor esto.

Saludos.-

**Comment by amendezkar** [comment]
Buenas

Entonces está bien que se suspenda el último que entró a Block en vez del primero?
La sugerencia donde la podemos ver?

Gracias y saludos

**Comment by iago64** [comment]
Buenas! 

Ahí esta actualizado el Doc, se me había pasado confirmar las sugerencias de redacción, dado que como bien decís, al momento de llegar el carpincho 4, el 3 puede ser que justo se haya bloqueado y por eso se suspenda ese en lugar del 1.

Saludos.-

**Comment by amendezkar** [comment]
Perfecto, gracias!
