### ISSUE TITLE
Consulta cola de IO

### ISSUE THREAD

**Issue by matiaspar2000** [sisoputnfrba/foro#2464]
Buenas, en una parte de las pruebas (Kernel suspensión, resultados esperados, pag 14) mencionan 

`Validar la suspensión de los carpinchos 1 y 2 al momento de que llegan los carpinchos 3 y 4 y que empiecen a suspenderse a medida que se van moviendo de la cola de bloqueados por IO del dispositivo PILETA.`

Por lo que entendimos de la consigna la cola de bloqueados es una sola para todo el sistema (además de bloqueado suspendido) donde además de los bloqueos por IO están los bloqueados por semáforos, es a eso a lo que se refiere por "cola de bloqueados por IO" o cada dispositivo debe tener su propia cola de blocked para realizar alguna consulta eventual?

**Comment by iago64** [comment]
Buenas! Cómo va?

Se refiere al estado bloqueado en general, después si algún grupo lo implemento como colas separadas por cuestiones de simpleza no hay problema, pero justo en esa prueba los carpinchos solo se bloquean por IO 😄 

Saludos.-

**Comment by matiaspar2000** [comment]
Perfecto, muchas gracias. Cierro hilo.
