### ISSUE TITLE
Duda sobre base de liberacion heaps [Asignacion global]

### ISSUE THREAD

**Issue by mercedesmagnelli** [sisoputnfrba/foro#2465]
Un proceso empieza a liberar sus heaps y llega un punto en el que tiene un único heap ocupado y el último heap que está libre por defecto siempre y se libera; eso genera que el proceso ahora ya no tenga heaps asignados pero en realidad sí podría tener un heap base que dice que no tiene asignación (es decir, en -1 el next y el prev alloc) pero si eso lo dejamos guardado, entonces tiene que seguir teniendo una pagina porque si un proceso se le eliminan todos los heaps no es que  se ELIMINE EL PROCESO, sino que se elimina su asignación de memoria, pero sí tiene que marcarse en algún lado escrito, o sea, en la memoria tiene que estar escrito este heap. 
Es decir, si un proceso pide un único alloc, lo que generaria un heap ocupado y un heap libre, y se libera ese único heap ocupado habría que consolidar. Esto generaría que la página ya no tenga "memoria guardada", tendría que eliminarla y que el proceso ahora de 1 pagina tenga 0? Si nosotros cuando liberamos un heap que genera esta situación (ya se queda sin heaps), borraríamos todas las paginas? Porque si no las borramos a todas las paginas, NUNCA pasaría que un proceso tenga 0 paginas asignadas una vez que pidió un alloc.

Para asignación fija, pasa lo mismo?

Gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Es un caso bastante bastante borde y creo que no se da en las pruebas, pero eventualmente si, si tienen un solo alloc y lo liberan deberían liberar esa página.

Saludos.-

**Comment by mercedesmagnelli** [comment]
Ok, perfecto. Gracias!

**Comment by iago64** [comment]
Joya! Cerramos el issue entonces 😄
