### ISSUE TITLE
Makefile no me toma las commons

### ISSUE THREAD

**Issue by Nicolas-Russo** [sisoputnfrba/foro#2466]
Buenas, estoy haciendo el makefile para la matelib y probando con un carpincho vacio y al momento de hacer le make me tira:
```
gcc -o carpincho.out main.c  ../matelib/obj/matelib.o
../matelib/obj/matelib.o: In function `obtenerInfoConfig':
matelib.c:(.text+0x104): undefined reference to `config_create'
matelib.c:(.text+0x11a): undefined reference to `config_get_string_value'
matelib.c:(.text+0x130): undefined reference to `config_get_string_value'
matelib.c:(.text+0x146): undefined reference to `config_get_string_value'
matelib.c:(.text+0x15c): undefined reference to `config_get_string_value'
matelib.c:(.text+0x172): undefined reference to `config_get_string_value'
../matelib/obj/matelib.o: In function `mate_init':
matelib.c:(.text+0x428): undefined reference to `string_equals_ignore_case'
collect2: error: ld returned 1 exit status
```

En el makefile file de la matelib tengo esto:
```
CC = gcc

SRC = $(shell find ./src -type f -iname "*.c" -exec basename {} \;)
OBJ = $(SRC:%.c=./obj/%.o)

build: makefolder $(OBJ)

LINK = -lcommons -lpthread
CFLAGS = -c

./obj/%.o: ./src/%.c
	$(CC) $(CFLAGS) $< -o $@ $(LINK)

makefolder:
	if [ ! -d ./obj ]; then mkdir obj; fi
```

Y en del carpincho esta esto:
```
CC = gcc
OUTFILE = carpincho.out

SRC = $(shell find ./src -type f -iname "*.c" -exec basename {} \;)
OBJ = $(SRC:%.c=./obj/%.o)

SHARED = $(shell find ../matelib/obj/*.o)

build: makefolder makeshared $(OBJ)
	$(CC) -o $(OUTFILE) main.c $(OBJ) $(SHARED)

LINK = -lcommons -lpthread
CFLAGS = -c

./obj/%.o: ./src/%.c
	$(CC) $(CFLAGS) $< -o $@ $(LINK)

makefolder:
	if [ ! -d ./obj ]; then mkdir obj; fi

makeshared:
	make -C ../matelib
```

Ademas en el carpincho y en la matelib estan los #include <commons/config.h> #include <commons/string.h> y otros.
Yo tenia entendido que agregando el flag -lcommons no tendria que haber problema.

Gracias.

**Comment by RaniAgus** [comment]
¡Buenas! Fijate que al ejecutar `make` el makefile está haciendo:
```
gcc -o carpincho.out main.c  ../matelib/obj/matelib.o
```
Es ahí donde se deben agregar los `-l` para linkear las commons, pthread y otras bibliotecas, pero veo que en el makefile del carpincho `$(LINK)` está agregado en el lugar incorrecto:
```make
build: makefolder makeshared $(OBJ)
	$(CC) -o $(OUTFILE) main.c $(OBJ) $(SHARED)

./obj/%.o: ./src/%.c
	$(CC) $(CFLAGS) $< -o $@ $(LINK)
```

En realidad iría al generar el `*.out` final (y no hace falta para generar el `*.o`), ya que los `*.o` no son ejecutables:
```make
build: makefolder makeshared $(OBJ)
	$(CC) -o $(OUTFILE) main.c $(OBJ) $(SHARED) $(LINK)

./obj/%.o: ./src/%.c
	$(CC) $(CFLAGS) $< -o $@
```

Fijate de hacer ese cambio y avisanos si se pudo resolver el problema

Saludos

**Comment by RaniAgus** [comment]
PD: Algo que me olvidé de mencionar es que es necesario que compilen su `matelib` como una shared library (o sea, en este caso sería seteando `CFLAGS := -fPIC -shared`, y el archivo final se debe llamar `libmatelib.so`) porque sino no van a poder compilar los carpinchos como se explica en [el repo de pruebas](https://github.com/sisoputnfrba/carpinchos-pruebas).

**Comment by Nicolas-Russo** [comment]
Genial, creo que ya me funciona bien.
Gracias!
