### ISSUE TITLE
Duda sobre Prueba "Kernel planificacion"

### ISSUE THREAD

**Issue by silgch** [sisoputnfrba/foro#2467]
Hola! 

Estamos ejecutando la prueba "PruebaPlanificacion" y en al correrla con HRRN, no nos queda claro si el comportamiento obtenido es el esperado según  el documento.  Revisamos, y pareciera  que el resultado obtenido es  correcto (siempre elige el mayor RR) 

### 📔 Citas del documento de pruebas
" A diferencia del SJF, las ráfagas del carpincho 3 se deben intercalar junto con las del 1 y el 2." 

### 👍 Comportamiento esperado
(No tenemos claro si cuando dice intercalado tiene que ser en un orden especifico) 

### 👎 Comportamiento obtenido
Los carpinchos ejecutan  en este orden: 1, 2, 3, 2, 1, 2, 3, 1, 2, 1, 3, 3.

Gracias!

Silvina

**Comment by iago64** [comment]
Buenas! Cómo va?

Como están calculando las estimaciones? Podrías pasar el log del kernel para que veamos como estan dandoles las cuentas? porque en la prueba de HRRN los resultados terminan quedando siempre en escalera en el orden 1-2-3.

Saludos.-

**Comment by silgch** [comment]
Hola!
Para calcular las estimaciones guardamos en cada carpincho el tiempo de inicio de exec(time_t) y luego al  salir de EXEC calculamos  el tiempo real de ejecución y luego actualizamos la ráfaga estimada:

`carpincho->rafaga_real_anterior=(time(NULL) - carpincho->ultimo_tiempo_inicio_exec)*1000;`
`carpincho->rafaga_estimada=  ( alfa * carpincho->rafaga_real_anterior ) + ( (1-alfa) * carpincho->rafaga_estimada);`

Te paso el log:
[kernel.log](https://github.com/sisoputnfrba/foro/files/7613851/kernel.log)

Gracias por la colaboración,

**Comment by iago64** [comment]
Buenas! Cómo va?

Revisando hay algo que no me cierra y es que al momento de ordenar la cola de ready despues de que el carpincho 3 se va a bloqueado, veo que tenes en el log lo siguiente:

```sql
[DEBUG] 12:41:45:370 KERNEL/(20420:20425): CARPINCHO :1     RAFAGA REAL ANTERIOR: 2000.000000     RAFAGA ESTIMADA: 2000.000000		RR:5.000000
[DEBUG] 12:41:45:370 KERNEL/(20420:20425): CARPINCHO :2     RAFAGA REAL ANTERIOR: 0.000000     RAFAGA ESTIMADA: 1400.000000		RR:6.714286
```

Es posible que no estén actualizando bien la ráfaga real anterior de los carpinchos? ya que en ese punto ya tuviste una rafaga real que fue lo que ejecuto el carpincho antes de bloquearse.
La fórmula esta bien, lo que me llama la atención es que solo para ese caso no esta la ráfaga anterior y ahí se desacomoda el resto.

Saludos.-

**Comment by silgch** [comment]
Hola! 

Lo estuve revisando, segun veo  la ráfaga anterior la toma en 0 porque, según el log entra en EXEC el el mismo instante en que se bloquea:

```
[INFO] 12:41:37:358 KERNEL/(20420:20425): CAMBIO DE ESTADO - Carpincho 2  EXEC (CPU  0)
[INFO] 12:41:37:358 KERNEL/(20420:20425): CAMBIO DE ESTADO - Carpincho ID 2 BLOQUEADO
```
Esto no podría ser correcto?

**Comment by iago64** [comment]
Buenas!

No debería ser 0, porque si te fijas la función que ejecuta el carpincho tiene un `sleep()` de 2 segundos antes de imprimir y después llamar a `mate_call_io()`, con lo cual, me queda una duda importante, en que momento le estas contestando el `mate_init()` al carpincho?

Saludos.-

**Comment by silgch** [comment]
Buenas! 
Estamos devolviendo la respuesta del INIT en el momento que se conecta el carpincho( a diferencia de los otros mensajes que piden recursos), se espera que el INIT también se responda cuando este en EXEC? 

Gracias! 

Silvina

**Comment by iago64** [comment]
Ahi esta el problema! 😄 

La idea es que el init lo respondan al momento de mandarlo a exec, ya que en cuanto a la lib le contestan el `mate_init()` (o el `mate_call_io()`, o el `sem_wait()`) la lib completa la función y libera al carpincho para que ejecute libremente 😞 

Saludos.-
