### ISSUE TITLE
Tipo de datos direcciones de memoria

### ISSUE THREAD

**Issue by study64** [sisoputnfrba/foro#2468]
Hola que tal.

Les cuento que basados en la estructura de los HeapMetadata especificados para ram, nosotros veniamos utilizando uint32_t para nuestras direcciones lógicas, pero al implementar matelib nos dimos cuenta de que matelib.h espera un tipo de dato int32_t (sin el u) ¿que tipo de datos debemos usar para las direcciones lógicas de memoria? ¿Y en general para el resto de los datos? ya que nosotros venimos modelando todo como uint32_t.

Saludos.

**Comment by iago64** [comment]
Buenas! Cómo va?

Por suerte uint32_t e int32_t son tipos de dato compatibles, ya que ambos utilizan 4 bytes (o 32 bits) para almacenar la info, con lo cual, bien podrían devolver un -1 y asignárselo a un uint32_t y lo único que va a cambiar es que al momento de imprimirlo podes tener el -1 o un valor positivo muy muy grande. 
Dicho lo anterior, internamente pueden manejar todo con int32_t y después cuando le devuelven el valor a la matelib que esta lo maneje como un uint32_t 😄 

Saludos.-

**Comment by study64** [comment]
ok, gracias
