### ISSUE TITLE
Prueba Suspension - Duda sobre resultados

### ISSUE THREAD

**Issue by Jrigada** [sisoputnfrba/foro#2470]
Buenas! Estabamos haciendo la prueba de suspension y teniamos la duda sobre el resultado que deberia darnos. 
En nuestra prueba se suspenden dos de los carpinchos para dar lugar a los nuevos que entran a new pero luego de esto no se suspenden mas si no que terminan los que estan en bloqueado y luego finalizan los que estaban en suspended blocked. Esto creemos que esta bien por las condiciones de suspension del enunciado pero queria estar seguro. 

Muchas gracias!

tldr: Queriamos confirmas que se van a dar dos suspensiones en toda la prueba.

**Comment by iago64** [comment]
Buenas! Cómo va?

Estuvimos viendo que hubo un desfasaje entre el enunciado y después lo que respondimos en los issues, ya que en teoría deberían analizar también al momento de que algún carpincho llega a suspended-ready.
En honor a nuestro error, si se apegaron a las condiciones que decían solo que haya carpinchos en NEW y no englobaron la posibilidad de que estuvieran listos para empezar a ejecutar (lo cual sumaría el estado Suspended ready), la prueba estaría bien.

Saludos.-
