### ISSUE TITLE
Duda con ejecucion de carpinchos

### ISSUE THREAD

**Issue by Nicolas-Russo** [sisoputnfrba/foro#2471]
Buenas, tenemos una duda con respecto cuando un carpincho hace mate_sem_wait, mate_sem_post, mate_sem_init o mate_call_io si se da la casualidad de que el carpincho ejecute estas funciones estando en new o ready si este tendria que esperar a que se pase a exec para ejecutar esta funciones o si puede ejecutarlas desde el estado donde esta.

Entiendo que es medio obvio que tenga que ejecutar cuando esta en exec. 

Llegado al caso que tenga que esperar a que este en exec se podria hacer uso de un 
```C
while(!puedePasarAReady)
```
esperado a que el algoritmo lo deje pasar, o
```C
while(!puedePasarAExec)
```
esperando a que el grado de multiprocesamiento lo deje pasar.

Gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Los carpinchos si no están en exec deberían estar frenados de alguna forma (la mas fácil es por ejemplo esperando una respuesta del kernel en un recv dentro de la matelib), con lo cual no podría pasar que un carpincho ejecute una función fuera de estado de exec.

Saludos.-

**Comment by Nicolas-Russo** [comment]
Okey, nosotros tenemos algo asi implementado, pero en el kernel cuando hace el send no se fija si esta en exec. Lo que tenemos es un hilo que esta fijandose todo el tiempo si puede meter mas procesos en exec segun el grado de multiprocesamiento. Con esto lo que se me ocurre que no haga el send hasta que no este en exec, estaria mal si hacemos en el kernel:
```C
while(estado != exec){}
send();
```

Gracias.

**Comment by iago64** [comment]
Buenas!

Ojo con el tema de tener un while() así sin mucha sincro ni semáforos porque podes tener una espera activa.
Respecto al tema de cuando contestar, un poco la idea del TP es que uds por ejemplo cuando desde la matelib hacen un `mate_init()` se queden esperando una respuesta, y que esa respuesta les va a llegar justo en el momento que el kernel los pasa a _EXEC_.
Algo parecido pasaría por ejemplo para un `mate_sem_wait()` donde la lib se tendría que quedar esperando a que el kernel le conteste que pudo tomar el semáforo o para el `mate_call_io()` donde la lib espera que el kernel le conteste que finalizo la operación de IO.

Es medio raro el esquema porque siempre estamos acostumbrados a contestar inmediatamente el mensaje, pero justamente la idea de comunicar al carpincho con el kernel mediante sockets es que los sockets vienen a simular la interrupción que genera un proceso a la hora de llamar al Sistema Operativo 😉 

Saludos.-

**Comment by Nicolas-Russo** [comment]
Genial gracias, entendido.
