### ISSUE TITLE
Duda en la lógica del deadlock

### ISSUE THREAD

**Issue by matiaspar2000** [sisoputnfrba/foro#2472]
Buenas, estoy teniendo un problema con el tema deadlock porque no se como es que se deberían generar.
Por ahora en el tp lo tenemos programado tal que el camino hasta que un carpincho se bloquea es el siguiente: 

Carpincho se crea -> pasa a ready cuando haya lugar -> lo selecciona el planif corto plazo -> pasa a exec -> recibe instrucción de matelib -> realiza instrucción -> se bloquea si corresponde 

Supongamos que hay 2 carpinchos que pasan por eso y están bloqueados. Para que pueda haber deadlock tiene que haber una espera circular, pero por como lo tenemos hecho eso no podría pasar.

En nuestro código la instrucción la reciben (de a una a la vez) los carpinchos que son seleccionados por el planif. corto plazo, pasan a exec y recien ahi reciben. De esta manera un carpincho bloqueado no puede bloquearse y al mismo tiempo querer hacer POST de un semáforo (cosa de que se de la espera circular) porque para recibir la instrucción de POST necesita: 

1. Estar en ready para ser seleccionado por el planificador y no en bloqueado.
2. "Terminar" la instrucción anterior de WAIT (el valor que se retorna a matelib recien se envía cuando se desbloquea el carpincho)

La pregunta es, cómo deberíamos encarar este tema? Dónde debería el carpincho recibir la instrucción de matelib como para que se pueda dar el deadlock?

**Comment by iago64** [comment]
Buenas! Cómo va?

Un poco la idea del deadlock, si analizas [la prueba](https://github.com/sisoputnfrba/carpinchos-pruebas/blob/master/PruebaDeadlock.c) lo que pasa es que los carpinchos toman 2 semáforos, el primero que lo encuentran con valor 1 y el segundo que lo encuentran con valor 0 y por lo tanto se bloquean. En este punto lo que pasa es que tenes algo así como:
C1 esta bloqueado por el semáforo que pudo tomar C2
C2 esta bloqueado por el semáforo que pudo tomar C3
...
C6 esta bloqueado por el semáforo que pudo tomar C1

Entonces el deadlock se da por como esta pensada la prueba y porque justamente juega con los tiempos para permitirle a todos los carpinchos tomar 1 semáforo y al momento de tomar el segundo, medio asegurarse de que ya esta tomado por otro carpincho. Justamente el hecho de que analicen si se puede bloquear y en base a eso contesten es la parte esencial de como debe funcionar el TP y esta bien como lo están haciendo.

Saludos.-

**Comment by matiaspar2000** [comment]
Entendí como funciona la prueba pero me parece que lo estamos implementando mal nosotros, en nuestro código funciona así: 

```c
void planificador_corto_plazo(){
	int multiproc = config_get_int_value(config, "GRADO_MULTIPROCESAMIENTO");
	char* algoritmo = config_get_string_value(config, "ALGORITMO_PLANIFICACION");

	while(1){
		while(list_size(l_ready) > 0 && list_size(l_exec) < multiproc && list_size(l_suspended_ready) == 0) {
			t_carpincho* turno = buscar_carpincho(algoritmo); //aca selecciona al carpincho entre los q están en READY
			cambiar_estado(EXEC,turno);
			pthread_t tarea;
			pthread_create(&tarea, NULL, (void*) hacer_tarea, turno);
			pthread_detach((pthread_t) tarea);
		}
	}
}
```

```c
void hacer_tarea(void* args){
	t_carpincho* carpincho = args;
	int retorno = -1, cod_op, inicio_exec = timestamp();

	bool buscar_semaforo(void* sem_en_lista) {return string_equals_ignore_case(((t_semaforo*)sem_en_lista)->nombre,carpincho->instruccion->nombre_sem_io);}

	while(carpincho->estado == EXEC){
		if(string_equals_ignore_case(carpincho->esperando, "VACIO")){     //esto es algo q hicimos para que responda la instrucción antes de pedir una nueva cuando regresa de BLOCKED
			cod_op = recibir_operacion(carpincho->socket_carpincho); //recibe de matelib
			if(cod_op == DELETE || cod_op == S_CREATE || cod_op == S_WAIT || cod_op == S_POST || cod_op == S_DELETE || cod_op == CALL_IO){
				carpincho->instruccion = recibir_instruccion(cod_op,carpincho->socket_carpincho);
			}
                 }

		switch(cod_op){
			case S_WAIT:
				if(list_any_satisfy(lista_semaforos, buscar_semaforo)){
					t_semaforo* objetivo = list_find(lista_semaforos,buscar_semaforo);
					objetivo->valor--;   

					if(objetivo->valor < 1){  //se bloquea si corresponde 
						pthread_mutex_unlock(&existencia_semaforo);
						cambiar_estado(BLOCKED,carpincho); 
						carpincho->esperando = carpincho->instruccion->nombre_sem_io; //con esto recuerdo que semáforo me está bloqueando a este carpincho
						return;  //espera en BLOCKED hasta que se desbloquee y poder terminar la instruccion (retorno a matelib)
					}
				break;

			case S_POST:
				if(list_any_satisfy(lista_semaforos,buscar_semaforo)){
					t_semaforo* objetivo = list_find(lista_semaforos,buscar_semaforo);
					objetivo->valor++;

					if(list_any_satisfy(l_blocked, desbloquear)){
						desbloquear_el_primer_bloqueado(l_blocked);  //desbloquea el primero si hay
					}
					retorno = EXITO;
				break;

... sigue con los demás casos y el devolver respuesta

```

Ahora, por como está hecho el carpincho bloqueado por un semáforo no puede hacer POST y WAIT de otro hasta desbloquearse y pasar de vuelta por hacer_tarea(), entonces no puede haber deadlock. 
Lo que se me ocurrió es que el semáforo de alguna manera registre que carpinchos lo toman (le hacen WAIT pero sin bloquearse) y de esa manera consultar si hay un deadlock, pero sigo sin estar seguro si esa es la funcionalidad que se busca.

**Comment by iago64** [comment]
Buenas!

El problema lo tienen en el valor del semáforo, si el semáforo empieza en 1 y le hacen un Wait, el proceso no se bloquea porque el semáforo queda en **0**, recuerden que para bloquear un proceso el valor del semáforo tiene que quedar en un valor negativo.

Saludos.-

**Comment by matiaspar2000** [comment]
Entendido, muchas gracias. CIerro hilo
