### ISSUE TITLE
Duda conexion Memoria - Swamp

### ISSUE THREAD

**Issue by matiashamide** [sisoputnfrba/foro#2473]
Buenas, tengo una duda con la conexion memoria - swap.
La conexion es monohilo y estamos teniendo varios problemas y no podemos identificar el error pero a partir de esto se nos ocurrio una duda, la conexion es una sola y hariamos un while(1) a atender_peticiones? mientras que se quedaria bloqueado el recv de operacion? o deberiamos cerrar esa conexion y que memoria genere otro cliente (por cada peticion) para que el cliente desde swap sea distinto?

**Comment by iago64** [comment]
Buenas! Como va?

La idea es que el swap sea un solo hilo y del lado de la memoria tengan un solo socket para mandar y recibir mensajes, esto lo pueden resolver simplemente estableciendo un mutex con ese socket (o sobre el conjunto de operaciones de ese socket) y que todos los hilos de los diferentes "carpinchos" a la hora de tener que ir a swap hagan `mutex_lock()` operen todo lo que tengan que operar con swap y hagan `mutex_unlock()` 😄 

Saludos.-
