### ISSUE TITLE
Pruebas TLB LRU resultados distintos

### ISSUE THREAD

**Issue by TiagoQuinteros** [sisoputnfrba/foro#2476]
en la prueba_tlb_lru no nos coincide con los resultados esperados, 
segun nosotros la secuencia que se repite es: 134242
haciendo el grafico vemos que coincide con nuestros resultados
### 👍 Comportamiento esperado
<b style="font-weight:normal;" id="docs-internal-guid-c91fbd7b-7fff-3b65-d71d-45af35689446"><ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:Calibri,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"></li></ul><div dir="ltr" style="margin-left:0pt;" align="left">

Entrada 0 | 1A | 4A | 3A | 1A | 2A | ...
-- | -- | -- | -- | -- | -- | --
Entrada 1 | 2A | 2A | 4A | 3A | 1A |  
Entrada 2 | 3A | 1A | 2A | 4A | 3A |  

</div></b>
</body>
</html>

### 👎 Comportamiento obtenido
<b style="font-weight:normal;" id="docs-internal-guid-c91fbd7b-7fff-3b65-d71d-45af35689446"><ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;"><li dir="ltr" style="list-style-type:disc;font-size:11pt;font-family:Calibri,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;" aria-level="1"></li></ul><div dir="ltr" style="margin-left:0pt;" align="left">

Entrada 0 | 4A | 3A | 1A | 2A | ...
-- | -- | -- | -- | -- | --
Entrada 1 | 2A | 4A | 3A | 1A |  
Entrada 2 | 3A | 1A | 2A | 4A |  

</div></b>
</body>
</html>

Muchas Gracias

**Comment by matiashamide** [comment]
Hola, a mi me sucede igual que a tiago, sera un tema de la prueba supongo, me falta la secuencia 1 2 3 y lo corri mas de 20 veces

**Comment by iago64** [comment]
Buenas! Cómo va?

Estamos revisando las cuentas por si las dudas nos quedo algo mal, ahora, les parece si nos comparten los logs que estén generando en la memoria como para ver donde se genera la diferencia y de paso checkeamos en conjunto? 

Saludos.-

**Comment by TiagoQuinteros** [comment]
[fragmento_logs.txt](https://github.com/sisoputnfrba/foro/files/7666396/fragmento_logs.txt)

**Comment by Mdavicino** [comment]
Buenas!
Analizando los resultados que vemos de tu log vemos que el reemplazo inicial queda de esta forma. A nosotros nos está pasando lo mismo ya que el TUR de la página 2 es el menor por lo que se reemplaza a la página 2 con la 1 y después al querer usar la 2 reemplazo la 3

| Entrada 0 | 4 |
|-----------|---|
| Entrada 1 | 1 |
| Entrada 2 | 2 |

Perdón si no entendemos bien los logs pero adjunto lo que entendemos que es el reemplazo de la primera vuelta:

[INFO] 04:32:19:458 memory_CARPINCHOS_TP/(32760:32991): TLB entry: 0, pid: 5, numero de pagina: 3, marco: 0
[INFO] 04:32:20:502 memory_CARPINCHOS_TP/(32760:32991): TLB entry: 2, pid: 5, numero de pagina: 1, marco: 4
[INFO] 04:32:21:808 memory_CARPINCHOS_TP/(32760:32991): TLB entry: 1, pid: 5, numero de pagina: 0, marco: 3

Saludos

**Comment by alejcha** [comment]
el nuestro coincide con la prueba (considerando que nuestra tabla inicia en P0) buscando desde el principio de la ejecucion, y tambien entiendo que el resultado de la prueba es luego de 2 o 3 reemplazos (según el caso)
o sea, primero tengo:

Entrada:0    Estado:Ocupado  Carpincho: 1        Pagina: 0    Marco: 0
Entrada:1    Estado:Ocupado  Carpincho: 1        Pagina: 1    Marco: 1
Entrada:2    Estado:Ocupado  Carpincho: 1        Pagina: 2    Marco: 2

el primer reemplazo hace:

->Entrada:0    Estado:Ocupado  Carpincho: 1        Pagina: 3    Marco: 3
Entrada:1    Estado:Ocupado  Carpincho: 1        Pagina: 1    Marco: 1
Entrada:2    Estado:Ocupado  Carpincho: 1        Pagina: 2    Marco: 2

luego 
Entrada:0    Estado:Ocupado  Carpincho: 1        Pagina: 3    Marco: 3
Entrada:1    Estado:Ocupado  Carpincho: 1        Pagina: 1    Marco: 1
->Entrada:2    Estado:Ocupado  Carpincho: 1        Pagina: 0    Marco: 0
que coincide con el del documento

luego de 3 reemplazos queda

Entrada:0    Estado:Ocupado  Carpincho: 1        Pagina: 2    Marco: 2
Entrada:1    Estado:Ocupado  Carpincho: 1        Pagina: 3    Marco: 3
Entrada:2    Estado:Ocupado  Carpincho: 1        Pagina: 1    Marco: 1

otros 3 reemplazos:

Entrada:0    Estado:Ocupado  Carpincho: 1        Pagina: 0    Marco: 0
Entrada:1    Estado:Ocupado  Carpincho: 1        Pagina: 2    Marco: 2
Entrada:2    Estado:Ocupado  Carpincho: 1        Pagina: 3    Marco: 3

y asi sucesivamente

**Comment by iago64** [comment]
Buenas! Cómo va?

Perdon por la demora, estuvimos revisando los resultados y estamos viendo que los resultados pueden variar levemente si siguieron el enunciado y devolvieron la dirección del inicio de los datos o la dirección del heap_metadata, con lo cual, es una prueba que vamos a validar mas en detalle al momento de evaluar.
Si esta es la única prueba que tienen dudas no se preocupen mucho y vengan 😄 

Abrazo!

**Comment by iago64** [comment]
Cerramos el issue por inactividad 👮‍♂️
