### ISSUE TITLE
Duda con list_get_maximun

### ISSUE THREAD

**Issue by Nicolas-Russo** [sisoputnfrba/foro#2477]
Buenas, queriamos usar list_get_maximun para el algoritmo de deadlock y no sabemos como usarlo. Estamos haciendo esta prueba y no nos funciona.
```C
        int p1 = 1;
        int p2 = 2;
        int p3 = 3;
	t_list* carpinchosEnDeadlock = list_create();
	list_add(carpinchosEnDeadlock, &p1);
	list_add(carpinchosEnDeadlock, &p2);
	list_add(carpinchosEnDeadlock, &p3);

	bool maximoCarpin(int a, int b){
		return a > b;
	}

	int* abc = list_get_maximum(carpinchosEnDeadlock, (void*) maximoCarpin);
```
abc nos esta esta devolviendo cualquier cosa.
Creemos que estamos usando mal la funcion.

Gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

El problema que están teniendo es que no están respetando la documentación de la función:

```c
	/**
	* @NAME: list_get_maximum
	* @DESC: Retorna el maximo de la lista según el comparador
	* El comparador devuelve cuál es el máximo de dos valores
	*/
	void *list_get_maximum(t_list* self, void* (*maximum)(void*, void*));
```

Lo que tienen que hacer es que la función devuelva el **elemento** y no si es mayor o menor.

En el archivo de [test_list.c](https://github.com/sisoputnfrba/so-commons-library/blob/master/tests/unit-tests/test_list.c) hay un ejemplo de como usar la función `list_get_maximum` y un ejemplo de la función que compara y devuelve el elemento :)

Saludos.-

**Comment by Nicolas-Russo** [comment]
Claro.
Gracias!
