### ISSUE TITLE
Duda con mate_sem_destroy

### ISSUE THREAD

**Issue by study64** [sisoputnfrba/foro#2478]
Buena, me surgió la siguiente duda con kernel: 

Si un carpincho llama a mate_sem_destroy() y otro carpincho se encuentra bloqueado por un wait sobre  ese mismo semaforo, ¿que debe suceder? ¿evito que se realice el destroy? ¿desbloqueo los carpinchos bloqueados? ¿los dejo bloqueados para el resto de la eternidad?

Saludos.

**Comment by iago64** [comment]
Buenas! Cómo va?

Esta pregunta ya la contestamos en los issues #2424 y #2349, resumiendo, no hay comportamiento esperado, hagan lo que gusten. 

Saludos.-

**Comment by study64** [comment]
perfecto, gracias
