### ISSUE TITLE
Pruebas planificacion

### ISSUE THREAD

**Issue by alejcha** [sisoputnfrba/foro#2479]
Buenas tardes, en las pruebas de planificacion tenemos casos que por la duracion del dispositivo IO y el sleep del carpincho (que son iguales) en aleatoreamente finaliza el sleep del carpincho 2 antes que finalice el io del carpincho 1 y ejecuta el carpincho 3 (porque no hay otro en ready)

podemos utilizar un tiempo de io menor (1000 x ejemplo) que no afectaria la prueba pero asegura que no haya otra peticion de io mientras el dispositivo se utiliza?

Gracias

**Comment by mesaglio** [comment]
Buenas!

Hermoso que vengan con este laburo procesado!
Ya que es un caso medio border, el ayudante que corrija va a decidir que modificar de la prueba.

Salu2!

PD: revisen la simultaneidad de eventos en la cola de ready, a que se le da más prioridad.
PD2: para agregar mas trazabilidad, agreguen los logs que sean necesarios. Asi no hay dudas sobre lo que esta ocurriendo.

**Comment by alejcha** [comment]
perfecto, si, tenemos los logs, y cuando sucede indica que hay solo 1 elemento en ready
