### ISSUE TITLE
Duda Prueba MMU CLOCK-M

### ISSUE THREAD

**Issue by matiashamide** [sisoputnfrba/foro#2480]
Buenas como va,
 estuve haciendo las pruebas de MMU y me parecen algo confusas y llego a resultados muy similares. Con LRU nos dimos cuenta que se usaron los carpinchos de PruebaAsignacion para correrlos y efectivamente nos dieron a partir de ahi, mi pregunta es si para correr los de clock tendriamos que usar la pruebaAsignacion o pruebaMMU. Independientemente, con ningun ejecutable nos dan los valores correctos, segun estuve leyendo este [issue](https://github.com/sisoputnfrba/foro/issues/2451) donde se corrigieron varias cosas en el archivo de pruebas, a @ncoen97 dijo que se comieron algunos accesos, queria preguntar si se puede saber cuales se comieron, ya que nos da muy parecido al resultado esperado y siento que falta un detalle en nuestro codigo de actualizar el bit de uso o algo asi en un caso especifico. 

El resultado que nos da al final de la ejecucion es:

C1P4 | C1P1 |  C1P2 | C1P5 | C1P8| C2P1 |  C1P0 | C1P6|C3 P0 | C1P3 | C1P7 | C3P1

Cuando el esperado es:

C1P4 | C1P0 | C1P1 | C1P5 | C1P6 | C1P7 | C1P2 | C1P8 | C2P1 | C1P3 | C3P0 | C3P1

**Comment by iago64** [comment]
Buenas! Cómo va?

Para el tema de las pruebas como esta en el documento de pruebas quedan:

Clock-M --> PruebaMMU
LRU --> PruebaAsignacion

Respecto a la parte de Clock-M, queres compartirnos los logs que están generando? Se me ocurren un par de cosas que podrían estar fallando, pero con los logs si son claros es mucho mas fácil de ver 😊 

Saludos.-

**Comment by matiashamide** [comment]
Ok, ahi mando el txt del logger, tal vez fueron demasiados logs :S avisame en tal caso y ponemos solo los obligatorios.

El pid no necesariamente corresponde con el numero de carpincho, es un pid que asignamos dentro de nuestro programa
//------------------------------------------------------------------------------//

[INFO] 12:55:37:586 MEMORIA/(6291:6291): TLB inicializada correctamente
[INFO] 12:55:37:587 MEMORIA/(6291:6291): Conexion satisfactoria con SWAMP. Los marcos max por carpincho son 0.
[INFO] 12:55:37:587 MEMORIA/(6291:6291): Hay 12 frames de 32 bytes en memoria principal
[INFO] 12:55:37:587 MEMORIA/(6291:6291): Memoria principal inicializada con exito.
[INFO] 12:55:42:790 MEMORIA/(6291:6291): Se conecto un cliente 7

[INFO] 12:55:42:790 MEMORIA/(6291:6305): MEMALLOC: el cliente 7 solicito alocar memoria de 23 bytes
[INFO] 12:55:42:791 MEMORIA/(6291:6305): Inicializando el proceso 0...
[INFO] 12:55:42:791 MEMORIA/(6291:6305): El proceso 0 fue inicializado correctamente.
[INFO] 12:55:42:791 MEMORIA/(6291:6305): Se le asignaron correctamente 23 bytes al proceso 0.
[INFO] 12:55:42:791 MEMORIA/(6291:6291): Se conecto un cliente 8

[INFO] 12:55:42:791 MEMORIA/(6291:6306): MEMALLOC: el cliente 8 solicito alocar memoria de 23 bytes
[INFO] 12:55:42:791 MEMORIA/(6291:6306): Inicializando el proceso 1...
[INFO] 12:55:42:791 MEMORIA/(6291:6306): El proceso 1 fue inicializado correctamente.
[INFO] 12:55:42:791 MEMORIA/(6291:6306): Se le asignaron correctamente 23 bytes al proceso 1.
[INFO] 12:55:42:792 MEMORIA/(6291:6291): Se conecto un cliente 9

[INFO] 12:55:42:792 MEMORIA/(6291:6307): MEMALLOC: el cliente 9 solicito alocar memoria de 23 bytes
[INFO] 12:55:42:792 MEMORIA/(6291:6307): Inicializando el proceso 2...
[INFO] 12:55:42:792 MEMORIA/(6291:6307): El proceso 2 fue inicializado correctamente.
[INFO] 12:55:42:792 MEMORIA/(6291:6307): Se le asignaron correctamente 23 bytes al proceso 2.
[INFO] 12:55:42:792 MEMORIA/(6291:6305): MEMALLOC: el cliente 7 solicito alocar memoria de 23 bytes
[INFO] 12:55:42:792 MEMORIA/(6291:6305): Alocando 23 bytes de memoria para el proceso 0.
[INFO] 12:55:42:792 MEMORIA/(6291:6305): [TLB MISS] PID: 0 NRO_PAG: 0
[INFO] 12:55:42:992 MEMORIA/(6291:6305): [TLB MISS] PID: 0 NRO_PAG: 1
[INFO] 12:55:43:193 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 1  FRAME: 1 

[INFO] 12:55:43:293 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 1  FRAME: 1 

[INFO] 12:55:43:394 MEMORIA/(6291:6305): [TLB MISS] PID: 0 NRO_PAG: 2
[INFO] 12:55:43:594 MEMORIA/(6291:6305): Se le asignaron correctamente 23 bytes al proceso 0.
[INFO] 12:55:43:594 MEMORIA/(6291:6306): MEMALLOC: el cliente 8 solicito alocar memoria de 23 bytes
[INFO] 12:55:43:594 MEMORIA/(6291:6306): Alocando 23 bytes de memoria para el proceso 1.
[INFO] 12:55:43:595 MEMORIA/(6291:6306): [TLB MISS] PID: 1 NRO_PAG: 0
[INFO] 12:55:43:795 MEMORIA/(6291:6306): [TLB MISS] PID: 1 NRO_PAG: 1
[INFO] 12:55:43:996 MEMORIA/(6291:6306): [TLB HIT] PID: 1  NRO_PAG: 1  FRAME: 3 

[INFO] 12:55:44:096 MEMORIA/(6291:6306): [TLB HIT] PID: 1  NRO_PAG: 1  FRAME: 3 

[INFO] 12:55:44:196 MEMORIA/(6291:6306): [TLB MISS] PID: 1 NRO_PAG: 2
[INFO] 12:55:44:397 MEMORIA/(6291:6306): Se le asignaron correctamente 23 bytes al proceso 1.
[INFO] 12:55:44:397 MEMORIA/(6291:6307): MEMALLOC: el cliente 9 solicito alocar memoria de 23 bytes
[INFO] 12:55:44:397 MEMORIA/(6291:6307): Alocando 23 bytes de memoria para el proceso 2.
[INFO] 12:55:44:397 MEMORIA/(6291:6307): [TLB MISS] PID: 2 NRO_PAG: 0
[INFO] 12:55:44:597 MEMORIA/(6291:6307): [TLB MISS] PID: 2 NRO_PAG: 1
[INFO] 12:55:44:798 MEMORIA/(6291:6307): [TLB HIT] PID: 2  NRO_PAG: 1  FRAME: 5 

[INFO] 12:55:44:898 MEMORIA/(6291:6307): [TLB HIT] PID: 2  NRO_PAG: 1  FRAME: 5 

[INFO] 12:55:44:999 MEMORIA/(6291:6307): [TLB MISS] PID: 2 NRO_PAG: 2
[INFO] 12:55:45:199 MEMORIA/(6291:6307): Se le asignaron correctamente 23 bytes al proceso 2.
[INFO] 12:55:45:200 MEMORIA/(6291:6305): MEMALLOC: el cliente 7 solicito alocar memoria de 23 bytes
[INFO] 12:55:45:200 MEMORIA/(6291:6305): Alocando 23 bytes de memoria para el proceso 0.
[INFO] 12:55:45:200 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 0  FRAME: 0 

[INFO] 12:55:45:300 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 1  FRAME: 1 

[INFO] 12:55:45:400 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 2  FRAME: 6 

[INFO] 12:55:45:501 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 2  FRAME: 6 

[INFO] 12:55:45:601 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 2  FRAME: 6 

[INFO] 12:55:45:702 MEMORIA/(6291:6305): [TLB MISS] PID: 0 NRO_PAG: 3
[INFO] 12:55:45:902 MEMORIA/(6291:6305): Se le asignaron correctamente 23 bytes al proceso 0.
[INFO] 12:55:45:903 MEMORIA/(6291:6306): MEMALLOC: el cliente 8 solicito alocar memoria de 23 bytes
[INFO] 12:55:45:903 MEMORIA/(6291:6306): Alocando 23 bytes de memoria para el proceso 1.
[INFO] 12:55:45:903 MEMORIA/(6291:6306): [TLB HIT] PID: 1  NRO_PAG: 0  FRAME: 2 

[INFO] 12:55:46:003 MEMORIA/(6291:6306): [TLB HIT] PID: 1  NRO_PAG: 1  FRAME: 3 

[INFO] 12:55:46:103 MEMORIA/(6291:6306): [TLB HIT] PID: 1  NRO_PAG: 2  FRAME: 7 

[INFO] 12:55:46:204 MEMORIA/(6291:6306): [TLB HIT] PID: 1  NRO_PAG: 2  FRAME: 7 

[INFO] 12:55:46:305 MEMORIA/(6291:6306): [TLB HIT] PID: 1  NRO_PAG: 2  FRAME: 7 

[INFO] 12:55:46:405 MEMORIA/(6291:6306): [TLB MISS] PID: 1 NRO_PAG: 3
[INFO] 12:55:46:606 MEMORIA/(6291:6306): Se le asignaron correctamente 23 bytes al proceso 1.
[INFO] 12:55:46:606 MEMORIA/(6291:6307): MEMALLOC: el cliente 9 solicito alocar memoria de 23 bytes
[INFO] 12:55:46:606 MEMORIA/(6291:6307): Alocando 23 bytes de memoria para el proceso 2.
[INFO] 12:55:46:606 MEMORIA/(6291:6307): [TLB HIT] PID: 2  NRO_PAG: 0  FRAME: 4 

[INFO] 12:55:46:707 MEMORIA/(6291:6307): [TLB HIT] PID: 2  NRO_PAG: 1  FRAME: 5 

[INFO] 12:55:46:808 MEMORIA/(6291:6307): [TLB HIT] PID: 2  NRO_PAG: 2  FRAME: 8 

[INFO] 12:55:46:909 MEMORIA/(6291:6307): [TLB HIT] PID: 2  NRO_PAG: 2  FRAME: 8 

[INFO] 12:55:47:009 MEMORIA/(6291:6307): [TLB HIT] PID: 2  NRO_PAG: 2  FRAME: 8 

[INFO] 12:55:47:109 MEMORIA/(6291:6307): [TLB MISS] PID: 2 NRO_PAG: 3
[INFO] 12:55:47:311 MEMORIA/(6291:6307): Se le asignaron correctamente 23 bytes al proceso 2.
[INFO] 12:55:47:311 MEMORIA/(6291:6305): MEMALLOC: el cliente 7 solicito alocar memoria de 23 bytes
[INFO] 12:55:47:311 MEMORIA/(6291:6305): Alocando 23 bytes de memoria para el proceso 0.
[INFO] 12:55:47:311 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 0  FRAME: 0 

[INFO] 12:55:47:411 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 1  FRAME: 1 

[INFO] 12:55:47:512 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 2  FRAME: 6 

[INFO] 12:55:47:612 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 3  FRAME: 9 

[INFO] 12:55:47:712 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 3  FRAME: 9 

[INFO] 12:55:47:813 MEMORIA/(6291:6305): [REEMPLAZO CLOCK-M] Saco NRO_PAG 0 del PID 0 en FRAME 0
[INFO] 12:55:47:813 MEMORIA/(6291:6305): [MP->SWAMP] Tirando la pagina modificada 0 en swap, del proceso 0
[INFO] 12:55:47:813 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 3  FRAME: 9 

[INFO] 12:55:47:913 MEMORIA/(6291:6305): [TLB MISS] PID: 0 NRO_PAG: 4
[INFO] 12:55:48:113 MEMORIA/(6291:6305): Se le asignaron correctamente 23 bytes al proceso 0.
[INFO] 12:55:48:113 MEMORIA/(6291:6305): MEMALLOC: el cliente 7 solicito alocar memoria de 23 bytes
[INFO] 12:55:48:113 MEMORIA/(6291:6305): Alocando 23 bytes de memoria para el proceso 0.
[INFO] 12:55:48:113 MEMORIA/(6291:6305): PAGE FAULT! La pag 0 del proceso 0 no se encuentra en memoria.
[INFO] 12:55:48:114 MEMORIA/(6291:6305): [REEMPLAZO CLOCK-M] Saco NRO_PAG 2 del PID 0 en FRAME 6
[INFO] 12:55:48:114 MEMORIA/(6291:6305): [MP->SWAMP] Tirando la pagina modificada 2 en swap, del proceso 0
[INFO] 12:55:48:114 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 1  FRAME: 1 

[INFO] 12:55:48:214 MEMORIA/(6291:6305): PAGE FAULT! La pag 2 del proceso 0 no se encuentra en memoria.
[INFO] 12:55:48:214 MEMORIA/(6291:6305): [REEMPLAZO CLOCK-M] Saco NRO_PAG 0 del PID 1 en FRAME 2
[INFO] 12:55:48:214 MEMORIA/(6291:6305): [MP->SWAMP] Tirando la pagina modificada 0 en swap, del proceso 1
[INFO] 12:55:48:214 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 3  FRAME: 9 

[INFO] 12:55:48:314 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 4  FRAME: 0 

[INFO] 12:55:48:415 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 4  FRAME: 0 

[INFO] 12:55:48:515 MEMORIA/(6291:6305): [REEMPLAZO CLOCK-M] Saco NRO_PAG 1 del PID 1 en FRAME 3
[INFO] 12:55:48:515 MEMORIA/(6291:6305): [MP->SWAMP] Tirando la pagina modificada 1 en swap, del proceso 1
[INFO] 12:55:48:515 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 4  FRAME: 0 

[INFO] 12:55:48:615 MEMORIA/(6291:6305): [TLB MISS] PID: 0 NRO_PAG: 5
[INFO] 12:55:48:816 MEMORIA/(6291:6305): Se le asignaron correctamente 23 bytes al proceso 0.
[INFO] 12:55:48:816 MEMORIA/(6291:6305): MEMALLOC: el cliente 7 solicito alocar memoria de 23 bytes
[INFO] 12:55:48:816 MEMORIA/(6291:6305): Alocando 23 bytes de memoria para el proceso 0.
[INFO] 12:55:48:816 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 0  FRAME: 6 

[INFO] 12:55:48:917 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 1  FRAME: 1 

[INFO] 12:55:49:017 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 2  FRAME: 2 

[INFO] 12:55:49:117 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 3  FRAME: 9 

[INFO] 12:55:49:218 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 4  FRAME: 0 

[INFO] 12:55:49:319 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 5  FRAME: 3 

[INFO] 12:55:49:420 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 5  FRAME: 3 

[INFO] 12:55:49:520 MEMORIA/(6291:6305): [REEMPLAZO CLOCK-M] Saco NRO_PAG 2 del PID 1 en FRAME 7
[INFO] 12:55:49:520 MEMORIA/(6291:6305): [MP->SWAMP] Tirando la pagina modificada 2 en swap, del proceso 1
[INFO] 12:55:49:520 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 5  FRAME: 3 

[INFO] 12:55:49:620 MEMORIA/(6291:6305): [TLB MISS] PID: 0 NRO_PAG: 6
[INFO] 12:55:49:821 MEMORIA/(6291:6305): Se le asignaron correctamente 23 bytes al proceso 0.
[INFO] 12:55:49:821 MEMORIA/(6291:6305): MEMALLOC: el cliente 7 solicito alocar memoria de 23 bytes
[INFO] 12:55:49:821 MEMORIA/(6291:6305): Alocando 23 bytes de memoria para el proceso 0.
[INFO] 12:55:49:821 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 0  FRAME: 6 

[INFO] 12:55:49:921 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 1  FRAME: 1 

[INFO] 12:55:50:021 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 2  FRAME: 2 

[INFO] 12:55:50:121 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 3  FRAME: 9 

[INFO] 12:55:50:221 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 4  FRAME: 0 

[INFO] 12:55:50:322 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 5  FRAME: 3 

[INFO] 12:55:50:422 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 6  FRAME: 7 

[INFO] 12:55:50:522 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 6  FRAME: 7 

[INFO] 12:55:50:623 MEMORIA/(6291:6305): [REEMPLAZO CLOCK-M] Saco NRO_PAG 3 del PID 1 en FRAME 10
[INFO] 12:55:50:623 MEMORIA/(6291:6305): [MP->SWAMP] Tirando la pagina modificada 3 en swap, del proceso 1
[INFO] 12:55:50:623 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 6  FRAME: 7 

[INFO] 12:55:50:723 MEMORIA/(6291:6305): [TLB MISS] PID: 0 NRO_PAG: 7
[INFO] 12:55:50:924 MEMORIA/(6291:6305): Se le asignaron correctamente 23 bytes al proceso 0.
[INFO] 12:55:50:924 MEMORIA/(6291:6305): MEMWRITE: El cliente 7 solicito escribir memoria.
[INFO] 12:55:50:924 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 0  FRAME: 6 

[INFO] 12:55:51:024 MEMORIA/(6291:6305): MEMWRITE: El cliente 7 solicito escribir memoria.
[INFO] 12:55:51:024 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 1  FRAME: 1 

[INFO] 12:55:51:124 MEMORIA/(6291:6306): MEMREAD: El cliente 8 solicito leer memoria.
[INFO] 12:55:51:124 MEMORIA/(6291:6306): PAGE FAULT! La pag 0 del proceso 1 no se encuentra en memoria.
[INFO] 12:55:51:124 MEMORIA/(6291:6306): [REEMPLAZO CLOCK-M] Saco NRO_PAG 0 del PID 2 en FRAME 4
[INFO] 12:55:51:124 MEMORIA/(6291:6306): [MP->SWAMP] Tirando la pagina modificada 0 en swap, del proceso 2
[INFO] 12:55:51:125 MEMORIA/(6291:6306): MEMREAD: El cliente 8 solicito leer memoria.
[INFO] 12:55:51:125 MEMORIA/(6291:6306): PAGE FAULT! La pag 1 del proceso 1 no se encuentra en memoria.
[INFO] 12:55:51:165 MEMORIA/(6291:6306): [REEMPLAZO CLOCK-M] Saco NRO_PAG 1 del PID 2 en FRAME 5
[INFO] 12:55:51:165 MEMORIA/(6291:6306): [MP->SWAMP] Tirando la pagina modificada 1 en swap, del proceso 2
[INFO] 12:55:51:205 MEMORIA/(6291:6307): MEMREAD: El cliente 9 solicito leer memoria.
[INFO] 12:55:51:205 MEMORIA/(6291:6307): PAGE FAULT! La pag 0 del proceso 2 no se encuentra en memoria.
[INFO] 12:55:51:205 MEMORIA/(6291:6307): [REEMPLAZO CLOCK-M] Saco NRO_PAG 2 del PID 2 en FRAME 8
[INFO] 12:55:51:205 MEMORIA/(6291:6307): [MP->SWAMP] Tirando la pagina modificada 2 en swap, del proceso 2
[INFO] 12:55:51:205 MEMORIA/(6291:6307): MEMREAD: El cliente 9 solicito leer memoria.
[INFO] 12:55:51:205 MEMORIA/(6291:6307): PAGE FAULT! La pag 1 del proceso 2 no se encuentra en memoria.
[INFO] 12:55:51:244 MEMORIA/(6291:6307): [REEMPLAZO CLOCK-M] Saco NRO_PAG 3 del PID 2 en FRAME 11
[INFO] 12:55:51:244 MEMORIA/(6291:6307): [MP->SWAMP] Tirando la pagina modificada 3 en swap, del proceso 2
[INFO] 12:55:51:285 MEMORIA/(6291:6305): MEMWRITE: El cliente 7 solicito escribir memoria.
[INFO] 12:55:51:285 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 2  FRAME: 2 

[INFO] 12:55:51:385 MEMORIA/(6291:6305): MEMWRITE: El cliente 7 solicito escribir memoria.
[INFO] 12:55:51:385 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 3  FRAME: 9 

[INFO] 12:55:51:485 MEMORIA/(6291:6305): MEMWRITE: El cliente 7 solicito escribir memoria.
[INFO] 12:55:51:485 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 4  FRAME: 0 

[INFO] 12:55:51:586 MEMORIA/(6291:6305): MEMALLOC: el cliente 7 solicito alocar memoria de 21 bytes
[INFO] 12:55:51:586 MEMORIA/(6291:6305): Alocando 21 bytes de memoria para el proceso 0.
[INFO] 12:55:51:586 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 0  FRAME: 6 

[INFO] 12:55:51:686 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 1  FRAME: 1 

[INFO] 12:55:51:786 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 2  FRAME: 2 

[INFO] 12:55:51:886 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 3  FRAME: 9 

[INFO] 12:55:51:987 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 4  FRAME: 0 

[INFO] 12:55:52:087 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 5  FRAME: 3 

[INFO] 12:55:52:187 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 6  FRAME: 7 

[INFO] 12:55:52:287 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 7  FRAME: 10 

[INFO] 12:55:52:388 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 7  FRAME: 10 

[INFO] 12:55:52:488 MEMORIA/(6291:6305): [REEMPLAZO CLOCK-M] Saco NRO_PAG 0 del PID 1 en FRAME 4
[INFO] 12:55:52:488 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 7  FRAME: 10 

[INFO] 12:55:52:588 MEMORIA/(6291:6305): [TLB HIT] PID: 0  NRO_PAG: 7  FRAME: 10 

[INFO] 12:55:52:689 MEMORIA/(6291:6305): [TLB MISS] PID: 0 NRO_PAG: 8
[INFO] 12:55:52:889 MEMORIA/(6291:6305): Se le asignaron correctamente 21 bytes al proceso 0.
[INFO] 12:55:52:889 MEMORIA/(6291:6306): Se desconecto el cliente 8

[INFO] 12:55:52:889 MEMORIA/(6291:6307): Se desconecto el cliente 9

**Comment by iago64** [comment]
Buenas!

Estuve viendo el log y hay algo que me llama la atención, al momento de hacer el primer reemplazo lo haces bien:
`[INFO] 12:55:47:813 MEMORIA/(6291:6305): [REEMPLAZO CLOCK-M] Saco NRO_PAG 0 del PID 0 en FRAME 0`

Ahora cuando haces el segundo reemplazo, veo que tenes la siguiente línea:
`[INFO] 12:55:48:114 MEMORIA/(6291:6305): [REEMPLAZO CLOCK-M] Saco NRO_PAG 2 del PID 0 en FRAME 6`

Esa cuenta, como te esta dando? porque el puntero de clock deberías tenerlo justo en el frame 1 y por lo tanto cuando pegas la vuelta el primero que encontrás para cortar es justamente la página que esta en el frame 1.
Además lo otro que me llamo muchisimo la atención es que el que reemplazas es el frame 6 y la prueba dice reemplazo global, con lo cual, si pegaste la vuelta tenias los frames 2, 3, 4 y 5 para hacer bolsa antes de ir al frame 6, puede ser que estuvieras corriendo la prueba con reemplazo local?

Saludos.-

**Comment by matiashamide** [comment]
Gracias dami nos hiciste darnos cuenta de nuestro error, el problema era que el conjunto con el que trabajaba el algoritmo no estaba sorteado por index de frame, tiramos un list_sort() por eso y dio todo perfecto, muchas gracias
