### ISSUE TITLE
Prueba MMU - Resultados

### ISSUE THREAD

**Issue by Mdavicino** [sisoputnfrba/foro#2481]
Buenas!
Quería saber como es que se van a realizar las pruebas de Reemplazo MMU ya que en la consigna no se solicita informar el estado de los frames en ningún momento.

Gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Efectivamente, el enunciado no solicita el estado de los frames, pero si tienen eventos de log obligatorios como ser:

- Conexión y desconexión de los carpinchos
- TLB Hit / Miss - Indicando PID, Número de página y marco (si es Hit).
- Reemplazo de una página indicando víctima y la nueva entrada, ambos con PID, Número de página y Marco. (con esto último vemos que páginas se reemplazan y podemos saber si el algoritmo esta bien implementado o no)

Saludos.-

**Comment by Mdavicino** [comment]
Genial gracias!!
