### ISSUE TITLE
Duda sobre función de las commons

### ISSUE THREAD

**Issue by victoriaguillosson** [sisoputnfrba/foro#2482]
Buenas! 
Tengo una duda muy simple sobre la función list_is_empty de las commons que veo que retorna un int. No debería retornar un bool? O retorna un 1 o un 0 en formato int?

`
	/**
	* @NAME: list_is_empty
	* @DESC: Verifica si la lista esta vacía
	*/
	int list_is_empty(t_list *);
`

Saludos!

**Comment by mesaglio** [comment]
Buenas!

Se podria cambiar, lo llevamos para analizar de agregar para el cuatri que viene.

De todos modos el true y el false en [stdbool](https://sites.uclouvain.be/SystInfo/usr/include/stdbool.h.html) esta definido como constantes en 1 y 0, respectivamente.

Salu2, Juani!

**Comment by LeandroCarbajales** [comment]
Buenas!
Está respondida la duda? Se puede cerrar el issue?

**Comment by victoriaguillosson** [comment]
Buenas! 
Si, cierro el issue.
Gracias!!
