### ISSUE TITLE
TLB - Hits en Paginas que se encuentran en Swamp

### ISSUE THREAD

**Issue by mabelenda** [sisoputnfrba/foro#2483]
Buenas, realizando las pruebas de MMU, nos surgió una duda con la TLB, estamos realizando TLB Hit a una Pagina X del Proceso Y y la misma no se encuentra en Memoria Principal. 

La duda que nos surgieron son:

1. Las entradas de `TLB` deberían ser removidas al momento de enviar la pagina a `Swamp` porque encontramos que realizamos `TLB Hits` y la pagina no la tenemos en memoria. 

2. Si la primera opción es correcta, puede que afecte al reemplazo? Es decir, si necesito agregar una nueva entrada en la `TLB`, y al tener una vacía en cualquier posición no realizaría el algoritmo de reemplazo cierto? 

3. Es valido que la TLB siga guardando entradas de algo que no tenemos en Memoria Principal?

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Si, al momento de enviar una página a swamp deberían eliminar la entrada de la TLB.

2.- Efectivamente, si tenes una entrada en la TLB no corres algoritmo de reemplazo, simplemente guardas la entrada nueva en el espacio libre, como pasa cuando llenas la TLB.

3.- No, si no esta en memoria principal, no tiene que estar en la TLB porque podes producir errores de lectura, no te olvides que si tenes un TLB Hit, no vas a las tablas de páginas del proceso / carpincho.

Saludos.-

**Comment by mabelenda** [comment]
Genial Muchas gracias!! 😄
