### ISSUE TITLE
Duda con uso de t_list*

### ISSUE THREAD

**Issue by Nicolas-Russo** [sisoputnfrba/foro#2485]
Buenas, estamos teniendo un problema al momento de obtener las duraciones_io. Lo obtenemos asi: ```char** arrayDuraciones = config_get_array_value(configKernel, "DURACIONES_IO");``` y lo pasamos a t_list* con la funcion 'arrayATlistDeInts' para poder manejarlo mejor. Tenemos un ejemplo con los siguientes valores: DURACIONES_IO=[25000, 1000].

```C
t_list* arrayATlistDeInts(char** array){
	t_list* listaDeBloques = list_create();

	int largo;
	for (largo = 0; array[largo] != NULL; largo++) {
		char* bloque = array[largo];
		int bloqueInt = atoi(bloque);
		list_add(listaDeBloques, &bloqueInt);
	}

	return listaDeBloques;
}

void mostrarTlistint(t_list* lista){
	int t = list_size(lista);
	int i;
	for(i=0; i<t; i++){
		int* ab = list_get(lista, i);
		printf("Valor: %d\n", *ab);
	}
}
```
El error viene cuando llamamos a 'mostrarTlistint' y nos muestra Valor: 1000 Valor:1000, nunca nos muestra el valor 25000. Lo debugeamos y al momento de hacer el list_add los valores estan bien. No sabemos que podria estar pasando.

Gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

El problema lo estan teniendo al momento de que estan haciendo `int bloqueInt = atoi(bloque);` ahi la variable no deja de ser la misma en el __stack__, entonces están pisando el valor y despues en la lista si se fijan van a ver que tienen la misma dirección de memoria.

La solución correcta sería que la función utilice algo en __heap__, como por ejemplo:

```c
for (largo = 0; array[largo] != NULL; largo++) {
	char* bloque = array[largo];

	int* bloqueInt = malloc(sizeof(int));		 //Reservas memoria en el heap
	int tempVal = atoi(bloque);			//Obtener el valor en int del string que tenias en el config
	memcpy(bloqueInt, &tempVal, sizeof(int));	//Copias el valor a la variable que reservaste antes
	list_add(listaDeBloques, tempVal);		//Guardas la variable de heap en la lista en lugar la variable de stack
}

```

Saludos.-

**Comment by Nicolas-Russo** [comment]
Clarisimo, 
Gracias!
