### ISSUE TITLE
Duda con recursosIO

### ISSUE THREAD

**Issue by GabiSirota** [sisoputnfrba/foro#2486]
Buenas, estamos teniendo un problema parecido al issue #2485

Estamos cambiando de char* a t_list* y al copiar la información, en este caso "laguna" nos escribe otra cosa y no sabemos que sucede.

![image](https://user-images.githubusercontent.com/89555485/145121254-9168f8d1-43f3-4607-8bc3-8f4b81387a20.png)

Saludos!

**Comment by RaniAgus** [comment]
¡Buenas! Antes que nada, quisiera comentar que en el template que aparece justo antes de crear el issue sugerimos **no** subir capturas de pantalla:

```markdown
<!--
Contanos cuál es el contexto de tu duda o problema, cuál es el comportamiento que esperabas y el que
obtuviste. No olvides buscar primero en el buscador de issues por si la duda ya fue resuelta antes. Si
no se resuelve pero creés que el issue está relacionado, podés citarlo con un #.
-->

### 🔎 Búsqueda en foros
<!--
Contanos si investigaste sobre el tema en Google o en foros, y si encontraste algún post que sea de
utilidad para darnos más contexto sobre el problema.
-->

### 📝 Código relevante
<!--
No subas capturas de pantalla, copiá el código relevante a tu problema y pegalo acá. Podés darle
formato código con (Ctrl + 'e').
-->
### 🐛 Cómo reproducir el error
<!--
De ser necesario, explica los pasos a seguir para reproducir el error.
-->

### 💻 Logs
<!--
Si lo corriste con Valgrind, por consola o debugger y obtuviste un error, no subas capturas de
pantalla, copiá el texto y pegalo acá. Podés darle formato código con (Ctrl + 'e'). Si el output es
muy extenso, sentite libre de adjuntar un archivo de texto en su lugar.
-->

```

Esto se debe a que, como ayudantes:
1. No podemos copiar y pegar el código para probarlo localmente, lo cual nos complica más las cosas a la hora de dar un diagnóstico sobre el error.
2. El texto en imágenes no se puede obtener utilizando el [buscador de issues](https://github.com/sisoputnfrba/foro/issues), por lo que si otro compañero llega a tener la misma duda no va a poder encontrarlo.

Dicho esto, a ojo puedo decir que el problema puede venir por el lado de que están usando `string_length` para calcular el tamaño del string, pero tanto esta función como `strlen` no contemplan el `\0` que va al final de cualquier string en C:

![image](https://user-images.githubusercontent.com/39303639/145123508-3cc983f9-e027-49c2-aba9-616e6f287a23.png)

Este caracter debe estar ahí a la hora de hacer la copia ya que, como los strings son de tamaño variable, la forma que tienen las funciones que utilizan strings de saber cuándo terminar de leer es utilizando este valor como condición de corte. Internamente hacen algo parecido a esto:

```c
char str[6] = "Hello";
for (int i = 0; str[i] != '\0'; ++i) { 
    /// ...
}
```

Por lo tanto, deberían contemplar este caracter sumándole 1 al resultado de `string_length`:

```c
int tamBloque = string_length(bloque) + 1;
```

Ya que, de esta forma, al hacer el `malloc` y `memcpy` también se va a copiar el `\0`.

Saludos

**Comment by GabiSirota** [comment]
Gracias! Quedaron resueltas las dudas
