### ISSUE TITLE
Prueba Planificacion en VM de pruebas

### ISSUE THREAD

**Issue by Jrigada** [sisoputnfrba/foro#2487]
Buenas! perdon yo de nuevo, tenemos una consulta con la prueba de planificacion que ahora que estamos probando en la VM de pruebas nos da un poco distinto. Cuando ejecutamos en nuestra VM la estimacion nueva del primer carpincho nos da `2000,30` y del segundo` 2000,90` el segundo. Esto estaria correcto con el documento de las pruebas pero cuando lo probamos en la VM de pruebas nos da el primero un nuevo estimado de `2000,60` y el carpincho 2 nos da `2000,00. `

No tenemos muy claro que puede estar pasando que nos varia lo suficiente como para alterar el orden de los carpinchos asi que no sabemos bien por donde arrancar. Muchas gracias!

**Comment by tferraro** [comment]
Buenas! Por lo general, cuando el resultado esperado funciona localmente pero cambiando el entorno difiere, es de cajón un problema de concurrencia.

Fijate si corriendo helgrind (una tooling de valgrind para detectar condiciones de carrera) les arroja alguna luz:
`valgrind --tool=helgrind <tu app>`

**Comment by tferraro** [comment]
Bue nas! @Jrigada pudieron avanzar con algo?

**Comment by tferraro** [comment]
Lo cierro por inactividad, cualquier cosa nos pingean :D
