### ISSUE TITLE
Colas IO y planificador mediano plazo

### ISSUE THREAD

**Issue by GabiSirota** [sisoputnfrba/foro#2488]
Buenas teníamos una duda con respecto a los bloqueos por Recursos IO. 
Por lo comentado en #2394 entendemos que cuando un carpincho intenta hacer uso de un recurso que ya está siendo usado por otro carpincho se debería bloquear, pero lo que no nos queda del todo claro es si lo debemos ingresar al estado de blocked y tenerlo en cuenta a la hora de validar el estado de suspension del planificador a mediano plazo, o deberíamos hacer una cola donde tengamos los carpinchos que están esperando a que se libere el recurso y que de esta forma no se tengan en cuenta en la validación del estado de suspensión.

**Comment by LeandroCarbajales** [comment]
Buenas!
Así es, al igual que en los ejercicios de planificación que vemos en clase, apenas se hace el pedido de I/O el proceso pasa a estado bloqueado y es elegible para ser suspendido aunque su ráfaga de I/O no haya comenzado debido a que se está realizando la de otro proceso en el mismo dispositivo.

**Comment by Nicolas-Russo** [comment]
Hola, se me genero una duda leyendo el issue. Supongamos que se pasa al carpincho a suspendido mientras se queda esperando para poder ejecutar su rafaga de IO, tendria que esperar a que vuelva a exec para poder ejecutar su rafaga no? Osea no podria hacer el sleep() estando en suspendido.
Gracias!

**Comment by LeandroCarbajales** [comment]
Hola!
Tené en cuenta que la ráfaga de IO no se realiza en la CPU sino que en un dispositivo externo (como el disco) por lo que la misma se realiza aunque el proceso esté suspendido, justamente de esa manera es como pasa de (suspendido-bloqueado) a (suspendido-listo).

Saludos!
          Lean

**Comment by GabiSirota** [comment]
Muchas Gracias! Quedo todo mas claro
