### ISSUE TITLE
Duda sobre reporte de hit/miss

### ISSUE THREAD

**Issue by mercedesmagnelli** [sisoputnfrba/foro#2489]
Hola! Una consulta rápida, cuando hacemos la signal sigint para que se imprima el reporte por pantalla de los hits y miss, tienen que estar también los hits y miss de los procesos eliminados, es decir, de un historial de estos valores o solo los valores de los procesos que están corriendo al momento de disparar la signal? Gracias!

**Comment by LeandroCarbajales** [comment]
Buenas!
Exactamente, la idea es poder ver la cantidad de Hit y Miss de todos los carpinchos aunque ya hayan terminado de ejecutar, como bien dijiste sería ir acumulando el historial.

Saludos!
       Lean

**Comment by mercedesmagnelli** [comment]
Genial, muchas gracias Lean!
