### ISSUE TITLE
Prueba SWAMP - Ejecución

### ISSUE THREAD

**Issue by Mdavicino** [sisoputnfrba/foro#2490]
Buenas! estamos ejecutando la prueba de swap y nos encontramos con que la ejecución de la misma es muy larga. Queríamos saber si deberíamos cortarla en algún momento y evaluar los resultados o la prueba es efectivamente corta y tenemos algo mal nosotros.
Además queríamos saber como es que se va a evaluar que queden los carpinchos en distintos archivos de swap

Desde ya muchas gracias

Saludos

**Comment by mesaglio** [comment]
Buenas, como va?

Cuanto es mucho tiempo?
Si se decide cortar la prueba y ver en que estado esta la swamp, lo va a definir el ayudante que este evaluando.

---
Los carpinchos 1 y 2, van a ir escribiendo valores numéricos incrementados en 1 hasta llegar a 2000.
```
Carpincho 1 -> 1
Carpincho 2 -> 2
Carpincho 1 -> 3
Carpincho 2 -> 4
...
```

Cuando esto se baje a swamp deberíamos ver todos los números pares en un archivo y los impares en otro, si no recuerdo mal.

Salu2!

**Comment by Mdavicino** [comment]
Buenas!

Cuando lo corremos y llega más o menos al valor 800 empieza a haber reemplazos de memoria ya que solo hay 5 páginas y eso genera que tengamos que esperar el retardo de Swap por cada reemplazo. 
Lo estuvimos corriendo alrededor de 20 minutos y no terminaba, teniendo en cuenta que no hay retardos de la tlb ya que no existe en la prueba

Saludos!

**Comment by mesaglio** [comment]
Buenisimo, bajen el retardo de swamp entonces.

Prueben con 1 segundo, a ver que onda.

Saludos!

**Comment by Mdavicino** [comment]
Nos sigue pasando algo parecido, llegar a la vuelta 800 no es un problema, lo hace relativamente rápido, pero a partir de ese momento hay reemplazos, que aunque sea un segundo sigue retrasando la prueba.
Lo que nos pasa es que cada vuelta en ese momento tarda alrededor de 4 segundos, ya que hay que pedirle a swap que escriba la página que es reemplazada y que lea la que nos queremos traer a memoria. Mientras pasa todo esto también el carpincho acaparador también hace reemplazos.
Como Swap solo atiende mediante un hilo se van encolando los pedidos, lo que genera que la prueba demore.

**Comment by mesaglio** [comment]
Debe haber otra cosa entonces, capaz una sección critica muy grande. Pero con esa configuracion no deberia tardar tanto tiempo.

**Comment by Mdavicino** [comment]
Estuvimos revisando y la sección crítica que usamos es para los send y recv que hacemos de memoria a swap, que eso lo hacemos porque swap corre en un solo hilo y sino se mezclan las respuestas. Podría llegar a ser eso, pero no vimos otra solución posible para solucionar lo que nos pasaba

**Comment by iago64** [comment]
Buenas!

Eventualmente la prueba va a tornarse lenta cuando empiecen a ir a swap, una forma de resolver ese inconveniente es poner todos los retardos en 1 o 0, teniendo en cuenta que son con `usleep()`, 1 o 0 da lo mismo, debería volar 😄 

Saludos.-

**Comment by Mdavicino** [comment]
Genial, gracias!
