### ISSUE TITLE
Prueba Batalla por nordelta

### ISSUE THREAD

**Issue by sofiacortez** [sisoputnfrba/foro#2491]
Hola! viendo este issue [/issues/2453]  vi que agregaron un mate_sem_init en el carpincho 3 del semáforo smirnoffc2 previo al post que hace, lo que provoca que el semáforo se inicialice 2 veces (una por el carpincho 2 y otra por el 3). Lo cual creemos que esta generando un bloqueo en nuestro caso (o por lo menos un problema, ya que no manejamos el error de inicializar dos veces un semaforo).

**Comment by iago64** [comment]
Buenas!

El tema de iniciar 2 veces un semáforo no es problema, de hecho es algo que se aclaro en varios issues que si llega un mate_init de un semáforo que ya existe no hacen nada, simplemente contestan ok y que siga todo su curso, no se compliquen. 

Saludos.-

**Comment by ivanscardaoni1** [comment]
Perfecto! Gracias!

**Comment by sofiacortez** [comment]
Oki, gracias!
