### ISSUE TITLE
Prueba TLB FIFO - Grado Multiprogramación 

### ISSUE THREAD

**Issue by nicolaslazzaro** [sisoputnfrba/foro#2492]
Hola tenemos una duda en el grado de  multiprocesamiento de kernel en la prueba de TLB con FIFO, ya que cuando se hace: 
  
while (1)
{
  sem_wait(info->producer_sem);
  mate_memread(&mate_ref, key, thread_name, 10);
  mate_memread(&mate_ref, value, &current_value, sizeof(uint32_t));

  calculate_value_and_increment_seed(&current_value);
  print_thread_info(thread_name, current_value);

  mate_memwrite(&mate_ref, &current_value, value, sizeof(uint32_t));
  sem_post(info->consumer_sem);
}

al hacer el sem_wait(info->producer_sem) no podemos replanificar ya que no lo manejamos nosotros si no el sistema operativo. Cuando cambiamos el grado de multiprocesamiento a 2 obtenemos el resultado esperado. 

queríamos si hay un problema con la config o lo estamos pensando mal ? 

saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

No se preocupen, si con grado de multiprocesamiento 2 les funciona, lo ven con el ayudante que les este evaluando el tp, puede ser que nos haya quedado armado para la prueba de TLB de LRU donde solo hay 1 carpincho ejecutando.

Saludos.-

**Comment by tferraro** [comment]
Buenas! Que tul? Sirvio la respuesta de Dami?

**Comment by iago64** [comment]
Cerramos el issue por inactividad 👮‍♂️
