### ISSUE TITLE
Duda - Prueba TLB FIFO

### ISSUE THREAD

**Issue by mabelenda** [sisoputnfrba/foro#2493]
Buenas, tengo una consulta sobre la prueba de `TLB FIFO`. 

Mi consulta es la siguiente, actualmente nosotros por asignación fija estamos creando 3 paginas, en las cuales en base a los MEMALLOC recibidos les estamos reservando su espacio necesario. Dicho esto el resultado de la prueba de TLB FIFO nos menciona que en la TLB vamos a tener reemplazo de dos de las tres paginas reservadas. 

Nosotros en este momento, al buscar el frame de la pagina 3 de ambos procesos, estamos  guardando la misma en la TLB. Esto es correcto o encontramos algun error en el resultado de las pruebas? 

## Prueba
![image](https://user-images.githubusercontent.com/31737042/145271694-417898d7-f55b-4737-94ec-eb4a6034e308.png)

## Nuestra TLB

**MEMALLOC 1 Ambos procesos:** 
```
1A 2A  1B  2B
```
**MEMALLOC 2 Proceso 1:**
```
3C 1A 2A  1B
```

Reemplazando al 2B que sería el siguiente. Consideramos que el reemplazo es correcto, pero como el resultado es diferente al de las pruebas no sabemos si es correcto que `3C` se encuentre en `TLB `

**Comment by alejcha** [comment]
Buenas, si te sirve, a nosotros al principio no da tampoco, porque en la reserva y asignacion es diferente el reemplazo pero cuando ejecutan por unos segundos y los carpinchos comienzan a hacer los calculos, surge el patron del resultado

**Comment by iago64** [comment]
Buenas!

Como comenta @alejcha, la secuencia se da recién cuando empiezan a hacer los cálculos (es decir cuando empieza a imprimir thread name y value) ahí recién se te va a dar la secuela.

Saludos.-

**Comment by mabelenda** [comment]
Ah genial entonces!! Muchas Gracias @alejcha y @iago64 😄
