### ISSUE TITLE
Dudas sobre las direcciones de retorno

### ISSUE THREAD

**Issue by marianopoll** [sisoputnfrba/foro#2494]
Hola! 
1-Hoy revisando el enunciado del TP con mas detalle nos dimos cuenta que unos de los detalles del enunciado dice que: "Finalmente, como un detalle, el valor a retornar ante una reserva de memoria es la primera posición del bloque de datos reservado disponible (no la posición del HeapMetadata)." Nosotros armamos esto basándonos en que la dirección de retorno era la dirección lógica del inicio del Heap. Por eso  y dado que esto es una convención que solo afecta a las funciones internas de memoria y a su comunicación, quería consultar ¿es una condición de desaprobación directa que la dirección de retorno no sea  la primera posición del bloque de datos?

2-Otra duda de memoria, pero esta vez revisando las pruebas. A diferencia de los resultados mostrados en las pruebas. La numeración de las paginas en nuestra memoria no comienza en 0 sino en 1. ¿esto también es una condición de desaprobación directa?

Desde ya, muchas gracias!!

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Lo único que me preocupa de eso es que puedan estar teniendo que traer páginas de swap que no corresponden, con lo cual es super posible que no les den los resultados de los reemplazos de páginas.

2.- No hay problema, solo vamos a necesitar que nos avisen a la hora de corregir para saber que tenemos que contar desde 1 y no desde 0 😄 

Saludos.-

**Comment by marianopoll** [comment]
Volviendo a la consulta 1 ¿En que caso puede ser que sea posible? porque para memwrite, memread y memfree es posible que recibamos posiciones erróneas por lo que siempre tenemos que traer a memoria las paginas de los Heapmetadata anteriores. Finalmente, en el caso del memalloc, hay que recorrer los heaps del primero al ultimo.

**Comment by iago64** [comment]
Buenas!

El único caso de dirección errónea es que sea una dirección por fuera del espacio de direcciones del carpincho, si es un valor intermedio no deberían devolver el error, simplemente leen / escriben y ya 😄 

Saludos.-

**Comment by marianopoll** [comment]
okey, de esto me surgen 2 dudas:

1-¿Es posible que se pida hacer un memread en la mitad de un alloc? ¿debería leerse en ese caso?

2-Sigo un poco confundido respecto a lo que pregunte antes. Aunque no haya una dirección errónea intermedia, el recorrido de HeapMetaDatas hay que hacerlo igual porque no se sabe cual es el alloc final y ,como el heap esta antes que el alloc, estoy obligado a traer a memoria las paginas anteriores a este. Por lo que vuelvo a preguntar ¿Para que caso podria ser que mis reemplazos de paginas sean incorrectos?

**Comment by iago64** [comment]
Buenas!

1.- Si, es posible, de la misma forma que si vos reservas por ejemplo 500 bytes con un malloc y queres leer del byte 100 al 200 😄 

2.- En el caso del memalloc(), si estas obligado a recorrer todos los heap_metadata porque como bien decis, tenes que llegar al último.
Ahora en un `memread()`, `memwrite()` y `memfree()` a vos te dan una dirección lógica que vos generaste previamente en el `memalloc()` y por lo tanto debería servirte para saber sin tener que recorrer todos los heapMetadata en que página y offset esta esa dirección.

Saludos.-

**Comment by marianopoll** [comment]
Entiendo lo que me estas planteando Damian, pero el enunciado dice (para memwrite por ejemplo): 
"memwrite
Se usa para escribir en la memoria. Con la dirección lógica que nos proveen y  la tabla de páginas hacemos la traducción a direcciones físicas y guardamos el contenido en el alloc correspondiente.  
En caso de que se quiera escribir en una posición de memoria errónea, se deberá devolver el error MATE_WRITE_FAULT definido en el enum mate_errors de la matelib correspondiente con el valor -7."
Entonces me pregunto ¿esta mal el enunciado? ¿Cómo podemos saber que esa dirección no esta en error sin recorrer los allocs anteriores?

**Comment by iago64** [comment]
Buenas! Cómo va?

Aca creo que la confusión viene porque no esta claro donde termina un mundo del sistema operativo (que ve páginas) y el del usuario (que son los heap_metadata y los datos).
El sistema operativo lo único que va a poder hacer es verificar si la dirección que le estas pasando pertenece al carpincho o no, es decir si es una página valida o no, para ello se basa en la tábla de páginas.
Ahora respondiendo la pregunta concretamente si vos tenes por ejemplo un carpincho con 2 páginas de 32 bytes asignadas (osea 64 bytes en total de espacio de memoria) y te llega una lectura / escritura que por tus cálculos te da que es en el byte 75 (o en la 3er página) ahí deberías devolver el error.

Saludos.-

**Comment by marianopoll** [comment]
Aah esta bien, creo que ya entiendo por donde va la mano. Lo únicas dudas que me surgen son:

-¿no es posible que se pida, por ejemplo en un esquema igual al que ejemplificaste, un memwrite a la dirección 60 teniendo el ultimo alloc en la posición 40?

-la ultima pregunta es un poco estúpida pero la hago igual por las dudas Si en memwrite, memread y memfree recorro los allocs del inicial al final ¿debería rehacer los algoritmos basados en lo que me planteaste? me llama la atención que, las algunas pruebas retornen los resultados esperados y otras algunos muy parecidos (por eso hago la pregunta estúpida también jajaj)

Saludos.

**Comment by iago64** [comment]
Buenas!

Antes de que me ponga de mal humor, dejemos una cosa en claro, **no existen preguntas estúpidas**, fuera de joda, no crean que una pregunta pueda ser tonta, estúpida, u otro sinónimo, nadie nace sabiendo y el proceso de aprender cosas nueva es algo que se da por medio de las preguntas en muchísimos casos 😊 

Ahora si, respondiendo las preguntas:
1.- Puede darse? Si y mientras la lectura o la escritura no se pasen del limite de la última página reservada esta todo bien, igual no es algo que tengamos en las pruebas, no fuimos taaan rebuscados.

2.- Y si... deberias sacar la parte de recorrer todos los allocs y deberias tener alguna forma "copada" de poder en base a la dirección lógica saber la dirección física, un buen ejemplo es el desplazamiento desde el inicio (entonces dividís eso por el tamaño de página y tenes el nro de página y el resto de la división te da el desplazamiento 😉)

Abrazo!

**Comment by marianopoll** [comment]
Muchísimas gracias por todo Damian!! Me aclaraste el panorama ampliamente

Abrazo!
