### ISSUE TITLE
Duda Sleeps en Prueba Planificacion

### ISSUE THREAD

**Issue by MarcoPiatti** [sisoputnfrba/foro#2495]
Buenas! tengo una duda muy de la mano con lo que terminaron de charlar en #2467.

Viendo el código de los carpinchos de planificación, donde la funcion imprimir tiene un sleep interno de 2 segundos
```c
void exec_carpincho_1(char *config)
{
    mate_instance self;
    mate_init(&self, config);
    sem_post(va_el_2);
    for (int i = 0; i < 3; i++)
    {
        imprimir_carpincho_n_hace_algo(1);
        mate_call_io(&self, (mate_io_resource) "pelopincho", "Carpincho 1 se va a IO");
    }
    imprimir_carpincho_n_hace_algo(1);
    mate_close(&self);
}
```
Tengo entendido que la idea de esos sleeps es para que los carpinchos puedan extender su ráfaga de CPU "artificialmente".
Esto sucede al principio de manera correcta, ya que el `mate_init` retorna recién cuando se encuentre en exec, lo cual garantiza que el primer sleep suceda dentro de la rafaga de ejecución del CPU. 
Pero en las siguientes iteraciones del for, el sleep viene justo derecho de un `mate_call_io`, que hace lo contrario, saca al proceso de la CPU, lo que hace que el sleep se ejecute con el proceso por fuera de la CPU, mientras queda en ready, y hace que la rafaga sea practicamente instantánea para cuando tenga que ejecutar realmente.

Por como lo veo, a los carpinchos les faltaría algún llamado a CPU antes que el sleep, que no tenga efecto a la plani, cosa de garantizar que el sleep siempre esté entre ráfagas.
Dicho eso quería consultar si hay alguna consideración dentro de toda la tramoya, que pueda ser un problema de nuestra parte más que del carpincho y me esté pasando de largo.

Muchas gracias desde ya.

**Comment by iago64** [comment]
Buenas! Cómo va?

El problema que estas teniendo es que el carpincho deberia quedarse esperando que termine el llamado a `mate_call_io()` de la misma manera que se queda esperando que `mate_init()` lo deje en exec 😊 
Saludos.-

**Comment by MarcoPiatti** [comment]
Uh! gracias damian, las burradas salen a la luz solas. 

Solo para reconfirmar lo que me dijiste, nuestros llamados a IO o a semáforos actualmente resumen una vez que los carpinchos salen del estado bloqueado, y en realidad debería suceder que resumen una vez llegados a exec.

**Comment by iago64** [comment]
Buenas!

Efectivamente, deberían contestarle al carpincho cuando este llega a EXEC 😄 

Saludos.-

P.D: Las "burradas" son parte del aprendizaje y es lo lindo de la facultad, se pueden cometer mil que no vas a tener a un jefe puteandote hasta en amareo antiguo porque un error en prod mando un mensaje del estilo de "Mi vieja mula ya no es lo que era"

![image](https://user-images.githubusercontent.com/1622109/145486682-4c7fbcb1-dc84-4485-9b51-299a4463c83d.png)

P.D.2: Ni me quiero imaginar el bardo que debió haber en Santander después de que salió esa notificación 🤣
