### ISSUE TITLE
Prueba TLB LRU - Marcos por carpincho

### ISSUE THREAD

**Issue by Mdavicino** [sisoputnfrba/foro#2496]
Buenas! Ejecutando esta prueba nos surgió una duda.

El tema es que tenemos 3 entradas de TLB y el carpincho que ejecuta solo puede tener 3 páginas en memoria. El problema surge que según lo que vimos en la teoría al querer meter una nueva página se elige a la víctima, marcandola como ausente y después se agrega la entrada a la TLB de la nueva. Esto genera que nunca se corra el algoritmo de reemplazo de la TLB, ya que para el momento que queremos meter la entrada a la TLB, la misma tiene solo dos entradas por lo que entra directo.
Vimos en otro issue que anteriormente la config de cantidad de marcos por carpincho estaba en 2 y pasó a 3, pero entendemos que según la teoría con 3 tampoco correría el algoritmo de reemplazo en la TLB.

Desde ya muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

Muy buena observación, dado que en este caso el ir a swap no nos interesa, si ponen para tener 4 frames por carpincho se les dan los reemplazos en la TLB? Si es así validen los resultados y nos avisan.

Saludos.-

**Comment by Mdavicino** [comment]
Buenas! 
Sisi, con la config con 4 se dan los reemplazos

Saludos!
