### ISSUE TITLE
Prueba Suspensión

### ISSUE THREAD

**Issue by ivanscardaoni1** [sisoputnfrba/foro#2497]
Buenas!

Mi duda es mas que nada una confirmación de lo que nos esta pasando en la prueba de suspensión. Cuando en la prueba se suspende un proceso, toda su imagen debería ser enviada a swap, pero como nunca antes se hizo un alloc, esa imagen es vacía, entonces:

Cuando se hace un mate init. El kernel debe avisar a memoria y esta debería crear la tabla de paginas vacía y la imagen del proceso? Y cuando se suspende dicho proceso, no se manda nada a swap (porque no hay nada reservado)? 

Desde ya muchas gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Acá tienen libertad de acción, si no tienen absolutamente NADA en memoria, pueden darse el lujo de no mandar nada a swap, de todas formas, es muy importante que los procesos SI se muevan entre las colas de planificación y quede explicito en los logs  cuando esto pasa.

La prueba solo apuntaba a Kernel por eso nos miramos al costado con el temita de reservar memoria, pero bien podrían agregar un `memalloc()` uds para probar que estén haciendo todo como corresponde.

Saludos.-

**Comment by ivanscardaoni1** [comment]
Perfecto! Gracias!
