### ISSUE TITLE
Configuración VMs de prueba

### ISSUE THREAD

**Issue by ivanscardaoni1** [sisoputnfrba/foro#2498]
Hola! 

Dado que estamos próximos a la entrega, nos pusimos a investigar cómo hacer el deploy y cómo configurar las VMs que nos dan ustedes, pero no estamos encontrando demasiada info. Habrá algún tipo de tutorial que explique cómo hacerlo?

Muchas gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Por suerte, la VM server que van a usar no es mas que una copia de la VM que tienen actualmente peero, sin entorno gráfico, con lo cual, si es por amigarse con la terminal, pueden simplemente abrir una terminal y empezar a probar como clonarse el repo, como clonarse el repo de las commons, como instalar las commons, como compilar su projecto con el makefile, etc, etc, etc.

Si de última se sienten muy en 0, para arrancar pueden probar de seguir el tutorial de [Mario Bash](https://mariobash.utnso.com.ar/) que tenemos subido en el [blog](https://www.utnso.com.ar/) y que nombramos en el [video de introducción a la parte práctica](https://www.youtube.com/watch?v=Cfmau03_1SA&ab_channel=UTNSO).

Saludos.-

**Comment by ivanscardaoni1** [comment]
Perfecto Dami! Ahí pudimos hacerlo, ahora se nos presenta otro problema, no sabemos ni por donde arrancar para hacer el makefile para depoyar el proyecto.
Sabes de donde podemos sacar info para hacerlo?

Muchas gracias!

**Comment by iago64** [comment]
Buenas!

Por suerte no es necesario que se quemen las pestañas haciendo los makefile, pueden usar los que les genera eclipse, solo tienen que acordarse de subirlos al repo.
En caso de que ahora no los esten subiendo revisen que seguramente tengan mas de un archivo .gitignore (posiblemente dentro de cada proyecto de eclipse) que les esta haciendo omitir la subida de la carpeta debug (Acuerdense de hacer un make clean antes de subirlo asi no suben los binarios al repo)

Saludos.-

**Comment by ivanscardaoni1** [comment]
Perfecto! Efectivamente, los .gitignore estaban ahi, sacamos todo y va joya, pero ahora no me encuentra la biblioteca compartida a pesar de utilizar el comando export para setear la variable de entorno...

Me tira lo siguiente (futiles es nuestra biblioteca compartida)

`Building file: ../src/kernel.c
Invoking: GCC C Compiler
gcc -I"/home/utnso/workspace/tp-2021-2c-DesacatadOS/futiles" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/kernel.d" -MT"src/kernel.o" -o "src/kernel.o" "../src/kernel.c"`


`In file included from ../src/kernel.h:11:0,`
                        `from ../src/kernel.c:11:`
`../src/planificacion.h:26:29: fatal error: futiles/futiles.h: No such file or directory`
`compilation terminated.`
`src/subdir.mk:24: recipe for target 'src/kernel.o' failed`
`make: *** [src/kernel.o] Error 1
`

**Comment by iago64** [comment]
Buenas!

Por lo que estoy viendo, lo que no te encuentra ahí es uno de los .h de tu biblioteca, por suerte como es un problema super comun, Tom hace un par de cuatrimestres se copo y armo un tutorial muy simple de seguir en [video](https://www.youtube.com/watch?v=A6dhc9cCI18&t=1s&ab_channel=UTNSO) de como hacer todos los linkeos y demás desde eclipse, si después tenes todo en el mismo orden de carpetas en el repo, el correrlo en la server es tan simple como git clone, y después compilar las cosas en orden (primero la biblioteca compartida y después los procesos 😊).

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Para complementar con el video de Tom, vi que al parecer a `gcc` le están pasando:

`-I"/home/utnso/workspace/tp-2021-2c-DesacatadOS/futiles"`

El [flag `-I`](https://www.rapidtables.com/code/linux/gcc/gcc-i.html) indica una ruta a partir de la cual ir a buscar los headers. Asegúrense de que el repo esté en la carpeta `/home/utnso/workspace` para que les tome bien el include.

También, como consejo, hagan foco en ver alguna forma sencilla de cambiar de configs entre pruebas, si bien no hay ningún apuro por corregir, se agradecería mucho 👍🏻 

Creo que la forma más sencilla (pero no la única) sería subir todos los config al repo e ir pasando la ruta al de la prueba como parámetro de `main`: https://www.tutorialspoint.com/cprogramming/c_command_line_arguments.htm

La ruta puede ser relativa, por ejemplo:
```
./memoria ../src/config.cfg
```

También si necesitan editar algún config al momento en la entrega pueden ir viendo de usar `nano`, es el editor de texto más sencillo 😄 

Saludos

**Comment by ivanscardaoni1** [comment]
Hola! Gracias a ambos, ya pude resolver el problema!

Era que no me di cuenta que la VM de prueba ya venia con los directorios /home/utnso/ y los estaba creando a mano, los eliminé y repetí el camino partiendo de la creación del workspace únicamente, y ahí se soluciono todo porque paso a tener la misma estructura de directorios que en la VM que utilizamos para codearlo. 👍🏻

Muchas gracias de nuevo!

**Comment by ivanscardaoni1** [comment]
Hola! Gracias a ambos, ya pude resolver el problema!

Era que no me di cuenta que la VM de prueba ya venia con los directorios /home/utnso/ y los estaba creando a mano, los eliminé y repetí el camino partiendo de la creación del workspace únicamente, y ahí se soluciono todo porque paso a tener la misma estructura de directorios que en la VM que utilizamos para codearlo. 👍🏻

Con respecto a las Config, lo estamos entrenando para estar cancheros/as, pero muy buena esa idea, vamos a intentar implementarla!

Muchas gracias de nuevo!

**Comment by RaniAgus** [comment]
¡Buenísimo! 🚀 Recuerden que si no quedan dudas pueden cerrar el issue 👮🏻‍♂️ (?)
