### ISSUE TITLE
[Memoria] Protección de marcos

### ISSUE THREAD

**Issue by Juyah** [sisoputnfrba/foro#2499]
Muy buenas a todos,

Teníamos una duda respecto a la concurrencia en el modulo de memoria.
Nuestra duda seria si el modulo de memoria se tendría que proteger a nivel de cada marco de la memoria principal o a nivel general (es decir que las operaciones de memoria, como alloc, escritura, lectura y free, se excluyan entre sí, aunque una no sea análoga a la otra. Esto para que no haya inconsistencia con los marcos).

### Solución - Nivel general
La idea que tenemos, si hay que proteger a nivel general, es un mutex de la memoria para las 4 operaciones que están relacionadas con los marcos (alloc, escritura, lectura y free).

### Solución - Nivel cada marco
En este caso se nos ocurrió que cada marco tenga un mutex el cual sera usado por las 4 operaciones (alloc, escritura, lectura y free) por lo que si el marco es sustituido se esperaría a que se libere el mutex (es decir se termina de realizar alguna de las operaciones ya mencionadas), si es que se esta usando este marco, para que no se genere una inconsistencia (como escribir o leer en el marco pero fue sustituido por otra pagina del mismo u otro carpincho). 
Este marco también tendría un booleano para saber si puede o no ser sustituido (ya que puede estar en la lista de marcos y haber sido elegido para ser sustituido pero seguir en la misma por el mutex), ante esta situación sucede que en las pruebas se obtiene un orden distinto al requerido porque no depende de nosotros cual mutex se libera antes, sino del sistema operativo.

Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

La decisión de como resguardar que no se pisen cosas queda a criterio de uds y despues en el coloquio charlamos por que lo hicieron de una u otra forma, no se preocupen.

Lo único que si, traten de no sobrediseñar la solución para hacer algo relativamente fácil de manejar (la solución a nivel marco me parece demasiado compleja).

Saludos.-

**Comment by Juyah** [comment]
Muchas gracias Damian, estaremos trabajando en ello. 
Saludos
