### ISSUE TITLE
Prueba Planificación SJF - Orden de ejecución

### ISSUE THREAD

**Issue by Mdavicino** [sisoputnfrba/foro#2500]
Buenas! 

Estábamos revisando la prueba de SJF de planificación y nos surge una duda, ya que el resultado esperado dice que deberían ejecutar todas las ráfagas de 1 y 2 intercaladas y las de 3 al final. 
Sin embargo nos encontramos con que el tiempo del dispositivo de IO pelopincho es igual al sleep que determina la duración de la ráfaga, entonces en algunas ejecuciones lo que sucede es que el sleep termina infinitesimalmente antes que la entrada salida del 1 o 2, por lo que el 3 es el único que queda en la cola de ready y ese se asigna para ejecutar.
Creemos que no estamos ante una condición de carrera en Kernel ya que si bien los resultados varían en cada ejecución, esto depende del instante en el que se arranca el sleep en el carpincho y el sleep de la IO. Estamos en lo correcto?

Desde ya muchas gracias

Saludos

**Comment by gastonharari** [comment]
@FernandoLlallire @rocioveloso +1

**Comment by iago64** [comment]
Bueeenas! Cómo va?

Sabes que justo este mismo problema lo plantearon en otro issue? Por suerte como comentamos en el issue #2479 si vemos que eso se da y tienen los logs copados que nos permitan entender la situación, podemos ajustar los tiempos y volver a probar, no se preocupen 😊 

Saludos.-

**Comment by Mdavicino** [comment]
Genial Dami, metemos los logs para que se entienda la situación.

Gracias!

Saludos
