### ISSUE TITLE
DUDA - Prueba MMU Clock Mod.

### ISSUE THREAD

**Issue by mabelenda** [sisoputnfrba/foro#2501]
Buenas, corriendo las pruebas de `Clock Modificado` nos encontramos con un resultado diferente al esperado en el archivo de pruebas. A diferencia de los esperados, nuestros resultados son: 

## Nuestros Resultados 
```
F0-C1 P8
F1-C1 P0
F2-C1 P1
F3-C1 P5
F4-C1 P6
F5-C1 P7
F6-C1 P2
F7-C2 P0
F8-C2 P1
F9-C1 P3
F10-C3 P0
F11-C3 P1
```

## Resultados Pruebas: 
![image](https://user-images.githubusercontent.com/31737042/145511067-2376188e-084e-49e1-91df-4afec17f11a5.png)

**¿Puede ser que los resultados difieran por el uso del `HeapMetaData`?** 
Porque verdaderamente no podemos encontrar un error en como hacemos el reemplazo. 
Aquí dejo los [MEMORIALOGS.txt](https://github.com/sisoputnfrba/foro/files/7689869/MEMORIALOGS.txt) que generamos en nuestra prueba capaz sirve de ayuda para entender cual puede ser nuestro error

**Comment by iago64** [comment]
Buenas! Cómo va?

Estuve revisando los logs y me parece que el problema que estas teniendo es que no estas actualizando el puntero de clock al momento de hacer los reemplazos y por eso siempre arrancas del primero en lugar de arrancar por el siguiente al último que reemplazaste (es bastante intuición porque no estoy viendo donde tenes el log de la posición del puntero de clock 😞)

Saludos.-

**Comment by mabelenda** [comment]
Buenas, muchas gracias por la idea de nuevos logs. 

Pero lamentablemente seguimos sin encontrar el error en nuestro reemplazo, estuvimos bastante tiempo revisándolo y solamente vemos `2 Frames` distintos al de las pruebas 

Vuelvo a enviarles un nuevo archivo de [logs.txt](https://github.com/sisoputnfrba/foro/files/7695967/message.txt) para ver si ustedes pueden detectar nuestro error. 

Gracias devuelta! 

saludos.-

**Comment by alejcha** [comment]
Buenas
creo que no estarian actualizando el bit de modificado cuando hacen hit (o no se tiene encuenta en el algoritmo), se ve un hit a la pagina 6 y despues la mandan a swamp

[INFO] 20:17:09:846 [MEMORIA]/(13504:13577): TLB HIT: Proceso 0 Pagina 6 y Frame 3
[INFO] 20:17:09:846 [MEMORIA]/(13504:13577): Hubo un TLB HIT: Devuelvo el Frame 3 con exito
[INFO] 20:17:09:846 [MEMORIA]/(13504:13577): Enviando la Pagina 6 del Proceso 0 a Swamp

**Comment by iago64** [comment]
Buenas!

Por empezar estoy amando _el memory dump_ es una genialidad ese log, muy buen agregado 😄 
Revisando el único error que tienen esta en el último reemplazo, donde estan poniendo la página 9 en el frame 0, cuando por los cálculos debería quedar en el frame 7, ya que esa página en el reemplazo anterior se le habia eliminado el bit de modificado y era candidata a ser eliminada.

Por las dudas, para descartar la idea que propone @alejcha, prueben de poner 0 entradas de TLB y vuelvan a correr la prueba, porque si es eso, no debería ser tan complicado de arreglar 😊 

Saludos.-

**Comment by mabelenda** [comment]
Muchas gracias por sus ideas! Ya pudimos resolverlo!
