### ISSUE TITLE
Liberacion Config

### ISSUE THREAD

**Issue by ivanscardaoni1** [sisoputnfrba/foro#2503]
Hola! Me esta pasando que cree una función para que cuando llega la señal Ctrl + C me libere la memoria y destruya determinadas cosas (doy Ctrl + C cuando las pruebas ya terminaron).

Ahora, si hago un config_destroy en esta función de cierre, a pesar de no tocar Ctrl + C me cambia el resultado de las pruebas, es muy raro. (Lo estoy viendo con la prueba de planificación, la cual poniendo SJF, si no destruyo la config hace lo deseado, y si agrego esa funcionalidad, trabaja como si fuese HRRN). Pero si no libero tengo memory leak.

Que puedo hacer? 

Desde ya muchas gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Que pueden hacer? despreocuparse completamente, lo que nos importa de los memory leak es que no los tengan durante la ejecución, es decir que cuando tiran Ctrl + C en un módulo los valores de definitely lost e indirectly lost sean lo mas cercanos a 0 posible (0 idealmente)

Saludos.-

**Comment by ivanscardaoni1** [comment]
Perfecto! Muchas gracias
