### ISSUE TITLE
Heaps: lectura y tlb 

### ISSUE THREAD

**Issue by mercedesmagnelli** [sisoputnfrba/foro#2504]
Buenas noches! Referenciando el issue #2428 

Tenemos un par de dudas: 

1. Volvemos una vez mas con la misma duda: tenemos que traer todos los HEAPS a memoria? Es decir si necesitamos leer el 4to HEAP tenemos que leer los HEAPs 1,2 y 3?
Volvemos a preguntar porque estamos corriendo los test de TLB que son de los últimos que nos falta pasar y creemos que no dan los resultados esperados por esta misma razón.
Hay que realizar un acceso directo? Si el HEAP apunta al bit 42 y dice que tiene que leer 5 bits, tengo que:

a. leer todos los heaps anteriores de forma secuencial, verificando que el HEAP ubicado en el bit 33 me da como puntero de lectura el bit 42 y luego realizar la lectura del dato?
b. leer solamente el HEAP ubicado en el bit 33 que me verifica que el puntero de lectura 42 es correcto, procediendo a la lectura del dato
c. leer directamente del bit 42 el dato buscado
Nosotros estamos usando la primera alternativa, con la misma nos pasaron todos los test menos: las dos pruebas de TLB

1.i) Procedemos a explicar qué es lo que nos está ocurriendo, no sabemos si es porque estamos leyendo mal la tabla que nos pusieron en el documento de pruebas o porque estamos haciendo algo mal. 
Entendemos que el patrón a detectar en esta prueba (tlb-lru) es el siguiente: 1234 (para los mallocs y las escrituras previas al while 1) y dentro del while(1) se repite: 421342 | 421342 | ... Entonces, esto nos da a pensar que son las paginas FINALES para cada petición que queremos acceder. Lo que pasa, es que, por ejemplo, si se quiere acceder a la pagina 4 porque se quiere hacer una lectura del 4° malloc, voy a tener que traer todas las paginas anteriores a donde esta guardado  ya que así voy a poder leer cada heap y verificar que el puntero es correcto y no excede ningún tipo de limite impuesto por el malloc correspondiente. Es decir, a nosotros se nos actualiza el timestamp de la entrada correspondiente a la pagina en la cual esta guardada el heap cada vez que leemos o escribimos un heap. Esto es correcto?

2. En la TLB tenemos que guardar los accesos a las paginas generados por lectura o escrituras de heaps? ´

gracias!

**Comment by mercedesmagnelli** [comment]
Otra duda que nos surgió releyendo por enésima vez la tabla de la tlb: qué criterio usaron para elegir esas entradas? qué representan? Son elecciones de paginas? son estados que tiene que quedar en caso de que se haga un cambio de entradas? 

Gracias x2

**Comment by iago64** [comment]
Buenas! Cómo va?

La idea de los heap_metadata es que les sirvan para reservar espacios, despues una vez que tienen las direcciones lógicas no vuelven a entrar en juego hasta que hacen un `memfree()` por lo tanto no deberían leerlos para un `memread()` o un `memwrite()`, con lo cual la opción correcta es la C, leer solo el dato 😄 

En la TLB como vieron en la teoria se guardan las referencias a las últimas páginas que accedieron.

Duda extra: Lo que estaba en el doc de pruebas que estaba mal eran los cálculos previos, lo que termina pasando en la TLB es que como bien decís se da un ciclo de accesos en el mismo orden, por lo tanto las entradas de la TLB se empiezan a reemplazas siempre las mismas en LRU, en FIFO, no hay muchas chances de que se alternen.

Saludos.-

**Comment by jfloresmaquera** [comment]
Primero: entonces los heaps solamente se iteraran secuencialmente para los mallocs y nunca se vuelven a leer secuencialmente. Dicho esto un HEAP nunca se vuelve a leer mas que para los mallocs, y en caso de un free no leemos secuencialmente, sino que leemos directamente al HEAP que se quiere liberar. Tanto para write como para read no se lee el HEAP, directamente se entra al dato almacenado en el HEAP.
Entonces lo que se va a evaluar en esta prueba (tanto en FIJO como LRU) es que se repita un patron, no necesariamente el que esta subido dentro de los Test  o entendimos mal.
Gracias.

**Comment by iago64** [comment]
Buenas! Cómo va?

El patrón que estaba subido tenia un error de cálculo y por eso lo sacamos y vamos a estar revisando los cálculos que hicimos internamente con las evaluaciones para asegurarnos de que coinciden 100%

Saludos.-
