### ISSUE TITLE
Consulta sobre memallocs prueba swamp

### ISSUE THREAD

**Issue by gchimento** [sisoputnfrba/foro#2506]
Hola, cómo va?

Estoy ejecutando la prueba de swamp y por lo que lei en el issue #2490 creo que hay un error en el size del memalloc que pide cada carpincho. Quería confirmar si es así. Adjunto parte del log de la lib.
![image](https://user-images.githubusercontent.com/28161872/145658949-d730744b-1c82-4a64-9130-f2deec6b123b.png)
(Aclaración: los ids 0, 2, 4 serían 0, 1, 2)

Muchas gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Por que motivo decís que hay un error? La idea de ese `memalloc()` enorme es que les llene uno de los archivos y que en los otros 2 se les distribuyan los valores de los otros carpinchos :)

Saludos.-

**Comment by gchimento** [comment]
Perdón, no aclaré. No me refería al de 20k. Me suenan raros esos memallocs de size 4 que hacen tanto el carpincho 0 como el 2.

**Comment by iago64** [comment]
Buenas! Cómo va?

Ahora si estamos en orden, si, la prueba esta pensada para que basicamente ejecute "for ever" o hasta que se queden sin memoria, la posta es que en algun momento si revisan los archivos de swamp, van a ver que en uno no hay nada (que es el que tiene el `memalloc()` de 20k y en los otros les va a pasar que tienen números pares y en el otro impares 😉 

Saludos.-

**Comment by gchimento** [comment]
En nuestro caso es como decís, nunca deja de ejecutar. Llega un punto en el que la prueba es un loop infinito de lo siguiente:

> [INFO] 23:40:29:715 [Swamp ᶘ◕ᴥ◕ᶅ]/(26721:26721): Recibi el codigo de operacion 22 del proceso MEM..
> [INFO] 23:40:29:715 [Swamp ᶘ◕ᴥ◕ᶅ]/(26721:26721): Comando MEMORY_SEND_SWAP_RECV recibido.
> [INFO] 23:40:29:715 [Swamp ᶘ◕ᴥ◕ᶅ]/(26721:26721): Memoria solicita guardar la pagina 1 del proceso 0 en swap.
> [INFO] 23:40:29:716 [Swamp ᶘ◕ᴥ◕ᶅ]/(26721:26721): La pagina 1 del proceso 0 fue guardada correctamente.
> [INFO] 23:40:29:824 [Swamp ᶘ◕ᴥ◕ᶅ]/(26721:26721): Recibi el codigo de operacion 22 del proceso MEM..
> [INFO] 23:40:29:824 [Swamp ᶘ◕ᴥ◕ᶅ]/(26721:26721): Comando MEMORY_SEND_SWAP_RECV recibido.
> [INFO] 23:40:29:824 [Swamp ᶘ◕ᴥ◕ᶅ]/(26721:26721): Memoria solicita guardar la pagina 1 del proceso 2 en swap.
> [INFO] 23:40:29:825 [Swamp ᶘ◕ᴥ◕ᶅ]/(26721:26721): La pagina 1 del proceso 2 fue guardada correctamente.

Estaría bien entonces? No termino de entender y tampoco sé cómo revisar los archivos de swamp para chequear.

**Comment by iago64** [comment]
Buenas!

La forma amigable de revisar los archivos de swamp es usando el comando `hexdump -C <path al archivo>`, por ejemplo si estas en la misma carpeta de los archivos: `hexdump -C swap1.bin`

El parametro -C lo que hace es mostrarte en ASCII los valores hexadecimales del archivo.

Saludos.-

**Comment by gchimento** [comment]
Me dio esto. No entiendo cómo se lee, disculpa.

![image](https://user-images.githubusercontent.com/28161872/145661593-f593beb6-dde8-4ecc-bc06-d584ee9a4bab.png)
![image](https://user-images.githubusercontent.com/28161872/145661604-957592c0-ce55-4130-beca-780cfeda1581.png)

**Comment by iago64** [comment]
Buenas! Cómo va?

Nada que disculpar! Esta perfecto, lo que tenes es en la primer columna las direcciones de "memoria" del archivo, en la segunda los valores en hexa y en la tercera la transcripción a ASCII.

Lo que esta bien es que tengas en un archivo la data del carpincho1 y en otro la del carpincho2, me llama la atención es que tenes todo mezclado, estas siguiendo la premisa de que el contenido de 1 carpincho solo puede estar en 1 sola partición de swap?

Saludos.-

**Comment by gchimento** [comment]
Buenas!

Gracias por la explicación. Recién me fijé y se está eligiendo correctamente el mismo archivo para cada proceso cada vez que se guarda una página.

También probé en llamar a la función `guardar_pagina(int proceso, int pagina, void *contenido)` desde el main de swamp (sin conexiones). En `contenido` le pase la variable `a` seteada de la siguiente manera:
`void* a = malloc(swap_page_size)`
`memset(a, 'a', swap_page_size)`
Inventando así algunas páginas con diferentes letras y está escribiendo correctamente en cuanto a orden y contenido. Estaría bien esta prueba como para confirmar que swamp está recibiendo "basura" y por eso escribe cosas que no debería?

Saludos.

**Comment by iago64** [comment]
Buenas!

Estuve repasando la prueba y lo que debería pasar es que:
1 archivo lo vas a ver vació porque es el que de entrada el thread de `carpincho_acaparador` reserva 20k de memoria.
los otros 2 archivos vas a tener 1 con la info de 1 carpincho, osea va a decir CARPINCHO1 o CARPINCHO2 y despues deberías tener los números asociados a ese carpincho que van a ser todos pares o todos impares.

Por eso que lo que me llama la atención es que parecía que estuvieras salteando la restricción de que 1 carpincho va a un archivo y el siguiente va a ir a otro archivo porque los carpinchos se dividen entre archivos y no las páginas.

Saludos.-

**Comment by gchimento** [comment]
Buenas!

Sisi entiendo el punto y pareciera ser así porque se muestra más de un carpincho en cada archivo en el log que pasé pero estuve debugeando y chequeando con algunos logs y la distribución pareciera hacerse correctamente. Para dar más detalle, cada carpincho tiene asociada una estructura que contiene el nombre de un archivo de swap y su tabla de páginas invertida, entonces de ahí saco el nombre del archivo, armo el path, lo mapeo y trabajo sobre eso. La asignación inicial es mediante una función que se fija cuál es el archivo de swap con menos frames ocupados en base al size de esta tabla de páginas invertida. Si es necesario muestro un poco el código para despejar dudas.

Una pregunta, para el caso de los void* no es necesario poner el `\0` al final, no? Ya no sé por dónde buscar jaja.

Saludos.

**Comment by iago64** [comment]
Buenas!

Respecto al ` \0` eso es un delimitador de strings, pero para la memoria esta bien que no se ponga porque vos no sabes si lo que hay es un string o no.
Por las dudas te hago un par de preguntas:

1.- Están limpiando los archivos y dejándolos con `\0` cuando levantan swamp? Porque ya veo que nos comimos el viaje de una prueba anterior.
2.- Cuando guardan los datos de las páginas en los archivos, como los guardan? con `fseek()`  y `fwrite()` o usaron `mmap()`?

Saludos.-

**Comment by gchimento** [comment]
Buenas!

1. Lo que hacemos es un `system("rm -r swapdir")` para directamente borrar el directorio donde están los archivos de swap y crearlos todos desde cero.
2. Con `mmap()` y `memcpy()`. Se busca el frame que le corresponde (en el caso de asignación dinámica, el primero que esté libre) y se pone en la posición `swap_file_map + frame_asignado * swap_page_size`.

No hay una forma de "deserializar" el contenido de los `void*` a medida que van llegando? Como para ver si eso está ok y lo que se hace mal es la escritura.

Saludos.

**Comment by iago64** [comment]
Aloha!

Es algo que podrías debuguear, total el swamp si lo implementaron como les pedimos en el enunciado debería atender los pedidos de a 1 con lo cual no debería ser una pesadilla analizar con eclipse el contenido de ese buffer que lo pueden interpretar como char[] y ver el contenido.

Saludos.-

**Comment by gchimento** [comment]
Buenas!

Así estaría bien? Nos está dando vacío siempre (excepto con el nombre de los carpinchos). Desde que lo recibe memoria, así que eso es lo que le manda a swamp y lo que este le devuelve cuando le piden una página.

```
char* prueba = malloc(tamanioDePagina + 1);
memcpy(prueba, info, tamanioDePagina);
prueba[tamanioDePagina] = '\0';
log_warning(logger, "Contenido recibido: %s", prueba);
free(prueba);
```

`info` viene a ser el contenido de la página.

![image](https://user-images.githubusercontent.com/28161872/145932632-61be10bc-e607-447c-9996-ff848f6f09ce.png)
![image](https://user-images.githubusercontent.com/28161872/145931715-1337c5f9-f475-4d2f-a7f9-ab89a2a0f91f.png)

Gracias,
Saludos!

**Comment by iago64** [comment]
Buenas!

Justo la forma que usaron para imprimir los valores no es la mas copada porque tienen el problema de que si tienen un \0 en algun lado el log con %s lo corta. Por las dudas te diria que:

1.- Revises el hexdump de las commons que te baja en hexa los resultados como si hicieras hexdump del archivo 😉 
2.- Le mandes con valgrind a ver si en una de esas remotísimas casualidades están pisando memoria y eso hace que les de cualquier cosa.
3.- Por favor no postees screenshots porque para verlo a veces desde el cel se complica una banda 😿 

Saludos.-

**Comment by Patricio-Galli** [comment]
Buenos días, aprovecho que el issue está abierto para hacer una consulta sobre la prueba.
Veo que el config de la memoria indica que la cantidad de entradas de la tlb es 0, lo que significa que no hay TLB. Esa posibilidad no la contemplamos en el módulo de memoria. Como no sobra el tiempo, quiero saber si puede correrse la prueba con un valor alto de TLB, lo cual no debería afectar la prueba por lo que tengo entendido.
Saludos.

**Comment by iago64** [comment]
@Patricio-Galli Como va? Tu pregunta RE estaba para que sea un issue aparte porque es algo importante.

El enunciado no aclara que la TLB se tenga que poder desactivar y nosotros asumimos que uds podían manejar el valor 0 y que la iban a iterar desde 0 hasta el size de la TLB (asumiendo una TLB implementada como una lista o estructura similar), pero dado que como dije antes, no esta explicito que la TLB se tenga que poder desactivar, no es motivo de desaprobación eso, de ultima veremos como acomodamos en el momento, no te preocupes.

Saludos.-

**Comment by gchimento** [comment]
Buenas,

1. Hice el hexdump de las commons y la diferencia que noto es que es como una versión más extendida que el del sistema pero no sé qué debería buscar. Se sigue viendo que hay más de un carpincho en algunos archivos.
2. Corrimos la prueba con valgrind durante unos minutos y vimos lo siguiente:
**Swamp**
```
==8970== 
==8970== HEAP SUMMARY:
==8970==     in use at exit: 0 bytes in 0 blocks
==8970==   total heap usage: 73,907 allocs, 73,907 frees, 5,771,040 bytes allocated
==8970== 
==8970== All heap blocks were freed -- no leaks are possible
==8970== 
==8970== For counts of detected and suppressed errors, rerun with: -v
==8970== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Memoria**
[memoria valgrind.txt](https://github.com/sisoputnfrba/foro/files/7716471/memoria.valgrind.txt)

3. Perdón por los screen y juro que es el último jaja pero es de un hexdump que hice hace algunos días y no tengo forma de accederlo nuevamente (porque no es que pasa todo el tiempo, fueron algunas veces nada más). Como se ve en el archivo de swamp se están guardando parte de los logs del módulo memoria, podría significar que memoria está enviando "basura" o nada que ver?
![image](https://user-images.githubusercontent.com/28161872/146123583-36654b30-37af-45db-a04e-8201477f37a8.png)

Por las dudas adjunto hexdump de la prueba que hicimos con valgrind:
[hexdump.txt](https://github.com/sisoputnfrba/foro/files/7716483/hexdump.txt)

Realmente ya no sabemos por dónde más buscar, estamos desde el viernes con esto y no sabemos qué más mirar.

Gracias.

**Comment by alejcha** [comment]
si sirve de ayuda, en nuestro caso lo que ayudo mucho fue debug a full y ejecutar paso a paso y ver que valor recibia y tomaba cada variable para ver que hacia cada funcion (que te aseguro que muchas veces no hace lo que crees que hace cuando la programas), y un carpincho de prueba que haga lo que necesites probar, mandando un string por ejemplo y ver todo el circuito de donde iba y donde se guardaba con debug y logger

ahora, lo que en las imagenes me parece raro, es que en un momento memoria envia del c1 la p1 a swamp (asumo que hay un FP) y swamp dice que recibe 2 pedidos de guardar lo mismo (casi en simultaneo) y lo guarda 2 veces (segun el log), quiza tengan algo en la logica donde busca el pid, o donde guarde que repite y guarda en todos los archivos o en cualquiera

**Comment by Patricio-Galli** [comment]
> @Patricio-Galli Como va? Tu pregunta RE estaba para que sea un issue aparte porque es algo importante.
> 
> El enunciado no aclara que la TLB se tenga que poder desactivar y nosotros asumimos que uds podían manejar el valor 0 y que la iban a iterar desde 0 hasta el size de la TLB (asumiendo una TLB implementada como una lista o estructura similar), pero dado que como dije antes, no esta explicito que la TLB se tenga que poder desactivar, no es motivo de desaprobación eso, de ultima veremos como acomodamos en el momento, no te preocupes.
> 
> Saludos.-

Sí, creo que debería haber creado un issue aparte, mala mía.
Perfecto, entonces, me quedo tranquilo de que no lo tengo que agregar a último momento. Lo que sí me gustaría saber es con qué configuración es correcto correr la memoria para la prueba swamp entonces. Con cualquier número de entradas no debería generar problema tratándose de una prueba de swap. ¿Estoy en lo correcto si pongo cualquier valor potencia de 2?

Gracias y saludos

**Comment by iago64** [comment]
> Sí, creo que debería haber creado un issue aparte, mala mía. Perfecto, entonces, me quedo tranquilo de que no lo tengo que agregar a último momento. Lo que sí me gustaría saber es con qué configuración es correcto correr la memoria para la prueba swamp entonces. Con cualquier número de entradas no debería generar problema tratándose de una prueba de swap. ¿Estoy en lo correcto si pongo cualquier valor potencia de 2?
> 
> Gracias y saludos

Da lo mismo el número de entradas de TLB, lo que importa en la prueba de swamp es justamente que manden correctamente los marcos a swamp y los traigan de vuelta sin problemas.

Saludos.-

**Comment by Patricio-Galli** [comment]
Buenísimo, gracias.

Saludos.

**Comment by Eezee2** [comment]
Hola! Tengo una duda relacionada justamente a esta prueba:

No sabemos como confirmar si esta funcionando bien, ya que la dejamos corriendo varios minutos (y le bajamos los retardos a 1) y vemos que continua y continua.

imprimo una tabla de paginas para saber el estado en cada momento y esta es la siguiente (después de aprox 5 min)
![image](https://user-images.githubusercontent.com/55916261/146294253-4ae2939a-8256-4171-b691-edb4a3b748b2.png)

Para explicar la tabla:
La primera fila es el numero de partición
La segunda fila es el numero de carpincho
La tercer fila es el numero de pagina (siendo una V de vacío si el marco esta vacío)
Hay una columna por cada pagina.

Quedaron 3 archivos (0,1 y 2) en los primeros dos se reservaron 4 marcos de memoria para cada carpincho, mientras que en la ultima partición se reservaron los 10 marcos para el carpincho 3 (acaparador). Los carpinchos 1 y 2 luego guardaron 4 paginas cada uno (N° de paginas = 0,1,2 y 3).

A medida que pasa el tiempo se mantiene la tendencia de que cada archivo tiene paginas de un solo carpincho (escribiendo la consulta se asigno una pagina mas).

**Comment by iago64** [comment]
@Eezee2 Lo que podes hacer para validar el contenido de los archivos de swamp es usando el comando hexdump, un ejemplo es: `hexdump -C <path al archivo>`

@gchimento 
Recién me percato de que tenias una duda sobre unos logs, ahi lo que esta claro es que estas mandando basura, te diría que debugueen bien la memoria o la corran con valgrind porque me huele a que el problema viene de ahi 😢 

Saludos.-
