### ISSUE TITLE
Consulta manejo de deadlocks

### ISSUE THREAD

**Issue by danimontesano** [sisoputnfrba/foro#2508]
Hola buenos días. Tenia una consulta sobre como encarar la parte de los deadlocks para las pruebas.
Lo que estaba pensando es que los deadlocks se producen con los semáforos ya que si un proceso hace un wait el siguiente proceso no podrá seguir. haciendo que se pueda producir un bucle por los semáforos. 
Ahora, mi duda es:

Si yo tengo un proceso que hace un wait, yo tengo que tener en cuenta como si el proceso hubiera "tomado" un semáforo/recurso, pero si mi proceso termina solo y nunca hace un signal, ¿yo debería hacer el signal por él? ¿o se supone que esa parte se la dejo al que programe el test y yo no libero ningún semáforo?

Porque por otro lado tengo entendido que si el proceso hace un wait y luego se produce el deadlock yo ahí tengo que terminar carpinchos hasta que se solucione el deadlock. Pero en este caso, ¿yo tengo que hacer tantos signals como waits haya hecho el proceso con el fin de liberar todos los semaforos que fueron tomados por ese proceso?. Es correcto esto que planteo? ya que me parece extraño el modo de resolución.

**Comment by LeandroCarbajales** [comment]
Buenas!
Al finalizar un proceso se liberan todos los recursos que tiene asignados, eso incluye también en este caso a los semáforos que tenga tomados, de esa forma los que estaban bloqueados por alguno de esos pueden continuar y se libera el deadlock, o en el caso de que un carpincho no le haga signal antes de terminar, igualmente se libera, de lo contrario quedaría tomado para siempre.

Es similar a como, por ejemplo, al finalizar un carpincho se libera toda la memoria que tiene asignada, no es que le hagas "free" explicitamente, sino que actualizás tus estructuras directamente.

Espero que quede más claro :)
Saludos!
        Lean

**Comment by danimontesano** [comment]
claro el tema es que yo habia pensado que a lo mejor un proceso podría hacer 10 posts y y ningún wait, pero por lo que me comentas entonces siempre antes de un post tendria que haber un wait. O si hace un post y luego finaliza yo tengo que hacer tambien los waits?

**Comment by iago64** [comment]
Buenas! Cómo va?

Lo que quiere decir Lean es que independientemente de lo que haga un proceso (o carpincho a fin de respetar los nombres del TP) es que si tiene algún recurso tomado, al momento de finalizar lo libera y en el caso del TP, como los recursos son solamente semáforos, tendrías que simular como si hiciera un post sobre cada semáforo tomado. 

Saludos.-

**Comment by danimontesano** [comment]
Buenas, reabro el issue porque al seguir con el desarrollo de los semáforos me di cuenta que no me quedó del todo claro.
Les agrego esta imagen para que entiendan la situación
![image](https://user-images.githubusercontent.com/62483675/146078463-aff87641-fc94-40dd-ab71-e0990bf1ef18.png)
en este caso, un proceso crea el semáforo con 0 recursos, luego hago un post por lo que cambia a 1, luego un wait por lo que cambia a 0 de nuevo, pero ahora en mi programa yo considero que el proceso tiene tomado 1 recurso. Entonces cuando finalizo el proceso libero ese recurso por lo que vuelve a 1. 
A lo que voy es que de esta manera se me generó un recurso de la nada. Este es el funcionamiento que ustedes esperan?

**Comment by LeandroCarbajales** [comment]
El recurso lo estás generando en el momento que le hacés post() sin antes haber hecho un wait().
Sí, es el funcionamiento esperado.
