### ISSUE TITLE
Un hilo se nos queda colgado

### ISSUE THREAD

**Issue by Nicolas-Russo** [sisoputnfrba/foro#2509]
Buenas, haciendo la prueba de planificación con HRRN estamos teniendo un problema que no entendemos que puede ser, empieza ejecutando bien el 1 sigue el 2 y al momento que llega el 3 y pasa de exec a bloqueado para hacer la IO se cuelga y ejecutan la IO el 1 despues el 2 y recien ahi lo hace el 3. En la funcion que el carpincho pide IO pusimo un semaforo para que la transicionExecBlocked se haga de a uno y un printf para ver como van ejecutando los carpinchos. 

Cuando vamos a los logs vemos que 1 y 2 estan en ready y 3 en exec. Despues el 3 pasa a bloqued, imprime "Voy a hacer IO ID: 3" y el 1 pasa a exec. A los 2 segundos cuando el 3 tendria que terminar de usar el IO y empezar a usarlo el 1, empieza a usarlo el 1 y el 3 se queda en bloqueado. Despues el 1 pasa a exec y el 2 pasa a bloqueado y ejecuta la IO. Una vez que termino de usar la IO el 2 recien ahi la usa el 3. No terminamos de entender que es lo que esta pasando, no parece ser por un tema de semaforos porque lo que hace es un post, no tendria que colgarse.

```C
void carpinchoPideIO(mate_io_resource recurso, mate_instanceACambiar* carpincho) {

	recursoIO* recursoIO = encontrarRecursoIO(recurso);

	sem_wait(semExecBlocked);
	transicionExecBlocked(carpincho);
	printf("Voy a hacer IO ID: %d \n", carpincho->id);
	sem_post(semExecBlocked);

	sem_wait(recursoIO->semaforo);
	usleep(recursoIO->duracion * 1000);
	sem_post(recursoIO->semaforo);

	printf("Termine de hace IO ID: %d\n", carpincho->id);

	transicionSuspendBlockedSuspendReady(carpincho);
	transicionBlockedReady(carpincho);

}
```  
Gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

A priori me falta info para poder entender el problema, probaron de correr el módulo con helgrind? Porque capaz ahi tengamos mas info para entender el problema.

Saludos.-

**Comment by Nicolas-Russo** [comment]
Hola, lo corrimos con helgrind pero no tira nada de info ahi. Te paso los logs a ver si se entiende mejor el problema.
```
[INFO] 22:58:11:419 kernel/(6009:6009): INICIANDO LOG kernel...
[INFO] 22:58:11:493 kernel/(6009:6009): CREANDO CONFIG kernel...
[INFO] 22:58:11:587 kernel/(6009:6009): SERVIDOR LISTO PARA RECIBIR CLIENTES...
[INFO] 22:58:13:670 kernel/(6009:6009): SE CONECTO UN CLIENTE!!!!
[INFO] 22:58:13:692 kernel/(6009:6018): El Carpincho id:1 entra en NEW 
[INFO] 23:01:42:629 kernel/(6440:6441): El Carpincho id:1 entra en Ready
[INFO] 22:58:13:720 kernel/(6009:6011): El Carpincho id:1 entra en EXEC
[INFO] 23:01:42:660 kernel/(6440:6440): SE CONECTO UN CLIENTE!!!!
[INFO] 23:01:42:696 kernel/(6440:6450): El Carpincho id:2 entra en NEW 
[INFO] 23:01:42:703 kernel/(6440:6441): El Carpincho id:2 entra en Ready 
[INFO] 23:01:44:665 kernel/(6440:6440): SE CONECTO UN CLIENTE!!!!
[INFO] 23:01:44:674 kernel/(6440:6451): El Carpincho id:1 esta en estado BLOCKED 
[INFO] 23:01:44:678 kernel/(6440:6442): El Carpincho id:2 entra en EXEC 
[INFO] 23:01:44:680 kernel/(6440:6440): SE CONECTO UN CLIENTE!!!!
Voy a hacer IO ID: 1 
[INFO] 23:01:44:687 kernel/(6440:6452): El Carpincho id:3 entra en NEW 
[INFO] 23:01:44:688 kernel/(6440:6441): El Carpincho id:3 entra en Ready 
[INFO] 23:01:46:682 kernel/(6440:6440): SE CONECTO UN CLIENTE!!!!
Termine de hacer IO ID: 1
[INFO] 23:01:46:698 kernel/(6440:6451): El carpincho:1 sale de BLOCKED y vuelve a READY
[INFO] 23:01:46:705 kernel/(6440:6453): El Carpincho id:2 esta en estado BLOCKED 
[INFO] 23:01:46:710 kernel/(6440:6442): El Carpincho id:3 entra en EXEC 
Voy a hacer IO ID: 2 
[INFO] 23:01:48:707 kernel/(6440:6440): SE CONECTO UN CLIENTE!!!!
Termine de hacer IO ID: 2
[INFO] 23:01:48:724 kernel/(6440:6453): El carpincho:2 sale de BLOCKED y vuelve a READY
[INFO] 23:01:50:726 kernel/(6440:6440): SE CONECTO UN CLIENTE!!!!
[INFO] 23:01:56:723 kernel/(6440:6440): SE CONECTO UN CLIENTE!!!!
[INFO] 23:01:56:730 kernel/(6440:6457): El Carpincho id:3 esta en estado BLOCKED 
[INFO] 23:01:56:733 kernel/(6440:6442): El Carpincho id:1 entra en EXEC 
Voy a hacer IO ID: 3 
[INFO] 23:01:56:738 kernel/(6440:6455): El Carpincho id:1 esta en estado BLOCKED 
Voy a hacer IO ID: 1 
[INFO] 23:01:56:742 kernel/(6440:6442): El Carpincho id:2 entra en EXEC 
[INFO] 23:01:56:743 kernel/(6440:6456): El Carpincho id:2 esta en estado BLOCKED 
Voy a hacer IO ID: 2 
Termine de hacer IO ID: 1
[INFO] 23:01:58:741 kernel/(6440:6455): El carpincho:1 sale de BLOCKED y vuelve a READY
[INFO] 23:01:58:744 kernel/(6440:6442): El Carpincho id:1 entra en EXEC 
Termine de hacer IO ID: 3
[INFO] 23:02:00:741 kernel/(6440:6457): El carpincho:3 sale de BLOCKED y vuelve a READY
[INFO] 23:02:00:745 kernel/(6440:6440): SE CONECTO UN CLIENTE!!!!
[INFO] 23:02:00:751 kernel/(6440:6459): El Carpincho id:1 esta en estado BLOCKED 
[INFO] 23:02:00:757 kernel/(6440:6442): El Carpincho id:3 entra en EXEC 
```
Ahi se ve como el carpincho 3 dice que va a hacer IO, printf que esta en la funcion que pase anteriormente, pero nunca lo hace hasta tiempo despues.

Saludos!

**Comment by alejcha** [comment]
Creo que el problema lo tenés en
[INFO] 23:01:56:742 kernel/(6440:6442): El Carpincho id:2 entra en EXEC 
[INFO] 23:01:56:743 kernel/(6440:6456): El Carpincho id:2 esta en estado BLOCKED 
Este es raro, no ejecuta por dos segundos, se bloquea inmediatamente, como que no lo frenaste en el pedido de io anterior

**Comment by Nicolas-Russo** [comment]
Uuy eso no lo vi. Igual el problema que digo viene antes, el 1 hace IO antes que el 3, cuando el 3 se bloquea antes que el 1. Probamos agregandole un sleep y si funciona como tiene que funcionar. Es decir el 3 se bloquea y hace el IO y despues lo hace el 1. Pero sin ese sleep el 3 pasa por la linea del printf (2 lineas antes de hacer el usleep del IO) pero no ejecuta el usleep hasta despues del 1, el cual empieza a ejecutar la funcion de 'transicionExecBlocked' una vez que el 3 hace el 'sem_post(semExecBlocked);'
```C
	sem_wait(semExecBlocked);
	transicionExecBlocked(carpincho);
        sleep(1.5);
	printf("Voy a hacer IO ID: %d \n", carpincho->id);
	sem_post(semExecBlocked);

**Comment by alejcha** [comment]
Igual, creo que el problema está ahí, no se bloquea con los io, porque al carpincho 1 le pasa lo mismo, así que seguramente envían todos el pedido de io inmediatamente al pasar a exec, por lo que puede que lleguen todos los casi en simultáneo y llegue primero cualquiera, especialmente si decís que agregando el sleep funciona

**Comment by Nicolas-Russo** [comment]
Si entiendo, iba por ahi el tema. Nos dimos cuenta que no estabamos chqueando si estaba en exec cuando haciamos el send al carpincho para destrabarlo, solo lo haciamos al principio.

Gracias!
