### ISSUE TITLE
Duda Semaforos e Hilos

### ISSUE THREAD

**Issue by danimontesano** [sisoputnfrba/foro#2512]
Hola buenas tardes. Estábamos tratando de sincronizar los dispositivos de entrada salida (threads) con los hilos de ejecución a la hora de ejecutar una tarea de IO. El problema nos surgió con que la sincronización entre estos threads funciona de una forma muy extraña. Nosotros cargamos datos en una lista y luego de cargarlos hacemos un post, el thread de IO recibe ese post con un wait y extrae de la lista el primer valor que encuentre. Sin embargo por alguna razón cuando cargamos los datos y hacemos el post el thread de hilos de IO no encuentra nada en esa lista. Es más, mirando los loggers es como que el thread de IO se ejecuta antes que la carga de datos a la lista, cosa que no tenemos idea porque sucede si esto está antes del post.

### 📝 Código relevante
Este es el código del hilo de ejecución el cual como se puede ver, primero inserta en `dispositivo->listaEspera` al carpincho y luego al final realiza un `sem_post(dispositivo->semaforo);`
```
case CALL_IO:;

	char* recurso;
	char* mensaje; // no se usa?
	recv_call_io(carpincho->socketMateLib, &pid, &recurso, &mensaje);
	log_info(logger,"recivo una llamada del IO: %s", recurso);
	dispositivo_io* dispositivo = obtenerDispositivo(recurso);
	carpincho->c->status = BLOCKED;

	pthread_mutex_lock(&(dispositivo->mutexLista));
	list_add(dispositivo->listaEspera, carpincho);
	pthread_mutex_unlock(&(dispositivo->mutexLista));

	log_info(logger,"tamaño de la lista %s: %d", recurso, list_size(dispositivo->listaEspera));

	free(recurso);
	free(mensaje);

	sem_post(dispositivo->semaforo);

	break;
```

Luego acá abajo tenemos el `while` de los dispositivos de IO el cual está esperando con el `wait` a un post del dispositivo. Sin embargo, en el `if` la función `list_is_empty(dispositivo->listaEspera)` siempre da true a pesar de que yo cargo los datos antes de hacer el post.

```
void dispositivoIO(void* args){
	dispositivo_io* dispositivo = args;
	log_info(logger, "CONEXION AL RECURSO: %s - DURACION IO: %d", dispositivo->recurso, dispositivo->duracion);

	while(1){
		sem_wait(dispositivo->semaforo);
		pthread_mutex_lock(&(dispositivo->mutexLista));
		if(list_is_empty(dispositivo->listaEspera)){
			pthread_mutex_unlock(&(dispositivo->mutexLista));
			log_error(logger, "Error no hay ningun carpincho a la espera de la IO");
		}
		else{
			t_running_thread* carpincho = list_remove(dispositivo->listaEspera, 0);
			pthread_mutex_unlock(&(dispositivo->mutexLista));
			usleep(dispositivo->duracion * 1000);
			carpincho->c->status = READY;
			//list_add(LISTA_READY, carpincho);
			add_lista_ready(carpincho);
			log_info(logger, "IO envia carpincho a ready");
			send_R_call_io(carpincho->socketMateLib);

			sem_post(&carpinchosEnReady);
		}
	}
}

```

### 💻 Logs

En los logs del programa pude encontrar esto:
![image](https://user-images.githubusercontent.com/62483675/145879524-c867d9f1-b444-4303-9748-33f6fecffad8.png)

Acá se puede ver que, pese a que el log de imprimir el tamaño de la lista que hay en el primer codigo que mostré se imprime primero, el log error de que la lista está vacía tiene un numero menor, lo que me lleva a pensar que este hilo se está ejecutando primero, cosa que me parece que no tiene sentido ya que el sem_post está luego de eso

### 🐛 Posible solución

La verdad no logramos encontrar una buena solución, en un principio nos funcionaba poniendo un `sleep(1)` pero ahora ya ni así funciona.
Me preguntaba si saben de alguna forma para solucionar este problema

Muchas gracias

**Comment by tferraro** [comment]
Leí un:
>  en un principio nos funcionaba poniendo un sleep(1) pero ahora ya ni así funciona.

Y me matcheo la regex de "esto es un problema de concurrencia".
Chusmeen corriendolo con valgrind en modo helgrind para ver si encuentra posibles condiciones de carrera mal handleadas.

También asegurense de tener bien mutex en las regiones críticas y de revisar, si tienen semáforos, que se den bien los casos de las condiciones de Bernstein.

Fijate con eso y contanos :)

**Comment by danimontesano** [comment]
ya nos fijamos eso, ese es el único wait a ese semáforo que hay en todo el código y ese es el único post que hay a ese semaforo en todo el código y las cosas están llegando en buen orden al case. además la función se queda esperando hasta que recibe el post. recién cuando recibe el post empieza a ejecutar, solo que al ver la lista está vacía

**Comment by danimontesano** [comment]
Buenas, ya descubrí donde está el error. basicamente por algun motivo el puntero al semaforo que me crea para varios de los dispositivos IO es el mismo, es decir que tienen el mismo semaforo, por lo que cuando hago post me lo toma el dispositivo incorrecto, mi pregunta sería porqué se me genera el mismo semaforo si estoy usando dos sem_init diferentes. Será que con el for se libera la memoria del primer semaforo? eso no deberia pasar, verdad? porque se lo estoy pasando al carpincho. 
En cualquier caso esta es una screen del puntero al sem que me crea para cada dispositivo IO.
![image](https://user-images.githubusercontent.com/62483675/145913972-98775d0c-4d26-4449-9650-78a55014b84f.png)
Para dos dispositivos distintos tengo el mismo puntero.
Alguna idea de porque pasa esto?

**Comment by tferraro** [comment]
Un tanto dificil saber eso sin conocer el código en detalle che 😕
Puedo teorizar cosas si sirve, porque puede venir de que estés pisando la variable del puntero con la otra. suele pasar cuando tenes info guardada en algun elemento de una lista y sin hacer malloc de nuevo "pisas" el valor, y entonces la lista al referenciar al original; lo estás pisando y no creando algo nuevo.

Pero pura teorización, vos conoces mejor el código, fijate si ese caso tiene sentido; o como manejan los punteros de que apuntan a los semáforos 🙂

**Comment by danimontesano** [comment]
Si, al final era eso!!! 
Muchisimas gracias!!!! (งツ)ว
