### ISSUE TITLE
Diferencias en prueba MMU Clock-M

### ISSUE THREAD

**Issue by mnigliazzo** [sisoputnfrba/foro#2513]
Buenas tardes, como andan? Estabamos corriendo las pruebas de MMU de Clock-M, obtenemos diferencias en las pginas que estan presentes en memoria. No encontramos porque nos difiere esta prueba, Estuvimos siguiendo el log y por lo que vemos hace bien los reemplazos

### 📔 Citas del documento de pruebas

Actividades 
- Iniciar los módulos en el orden definido por el grupo configurando la memoria con CLOCK-M.
- Iniciar los carpinchos de  PruebaMMU.

### 👍 Comportamiento esperado

![image](https://user-images.githubusercontent.com/49684313/145896025-97cf368a-864d-4c9c-a3fa-71814889ef73.png)

### 👎 Comportamiento obtenido
```sh
Frame: 0	 Carpincho: 1	 Pagina: 4 P: 1	 U: 0	 M: 1
Frame: 1	 Carpincho: 1	 Pagina: 1 P: 1	 U: 0	 M: 1
Frame: 2	 Carpincho: 1	 Pagina: 0 P: 1	 U: 0	 M: 1
Frame: 3	 Carpincho: 1	 Pagina: 8 P: 1	 U: 1	 M: 0
Frame: 4	 Carpincho: 1	 Pagina: 5 P: 1	 U: 0	 M: 1
Frame: 5	 Carpincho: 2	 Pagina: 1 P: 1	 U: 0	 M: 0
Frame: 6	 Carpincho: 1	 Pagina: 2 P: 1	 U: 0	 M: 1
Frame: 7	 Carpincho: 3	 Pagina: 0 P: 1	 U: 0	 M: 0
Frame: 8	 Carpincho: 3	 Pagina: 1 P: 1	 U: 0	 M: 0
Frame: 9	 Carpincho: 1	 Pagina: 3 P: 1	 U: 0	 M: 1
Frame: 10	 Carpincho: 1	 Pagina: 6 P: 1	 U: 0	 M: 1
Frame: 11	 Carpincho: 1	 Pagina: 7 P: 1	 U: 0	 M: 1
```

Adjunto el log de la memoria
[memoria_211213_185159003.log](https://github.com/sisoputnfrba/foro/files/7707247/memoria_211213_185159003.log)

Muchas Gracias

Saludos

**Comment by tferraro** [comment]
Buenas!

Se me ocurren varias preguntas que me haría si me pasara este caso.

Primero, ¿en qué punto ves que empiezan a diferir los frames de la memoria? Y cuál sería es ese diff?

Como para entender por qué está seleccionando un frame incorrecto, y ahí poder ver bajo qué criterio pasa.
Si querés contanos que encontrás :)

**Comment by fedesz** [comment]
Buenas! Lo revisamos infinitas veces y no logramos encontrar el problema, sospechamos que hay algun tema de como marcamos los bits de modificado y uso, pero hicimos de todo para mitigarlo y no estamos llegando a una mejor solucion. De casualidad, podrian darnos una mano revisando el log que adjuntamos arriba? ya que a lo mejor se nos esta pasando algo y alguien nos puede tirar una soga! Muchas gracias!

**Comment by tferraro** [comment]
Hagamos entonces un debugging abierto 🙂 Porque los logs crudos no me dicen mucho dado que no conozco su código 😜

Tratemos primero de contestar la pregunta que habia mencionado. Donde ven que empieza a cambiar el comportamiento a como debería ser? Que estado tenia la memoria en ese momento, como quedaron las estimaciones para cada marco y que peticiones vinieron antes?

Hagamoslo con los ejemplos puntuales así no hay que scrollear en un log largo para ir encontrando los puntos y de paso puede haber muchas más miradas al respecto, te parece?

**Comment by fedesz** [comment]
De casualidad tienen el patron que deberia seguir la memoria? porque a lo mejor eso nos puede ayudar a entender donde nos esta modificando el patron!

**Comment by iago64** [comment]
Buenas @fedesz 

Son 130k el log, mas de 1300 líneas, si nos tiras un centro y nos decís que reemplazos están haciendo en orden los vamos a poder ayudar mejor.

Saludos.-

**Comment by fedesz** [comment]
hola dami, te dejo un listado de los reemplazos que se van haciendo!

[CLOCK - M] Encontre victima. Frame: 0	 Carpincho: 1	 Pagina: 0 P: 1	 U: 0	 M: 0 ---------------
[CLOCK - M] Encontre victima. Frame: 2	 Carpincho: 2	 Pagina: 0 P: 1	 U: 0	 M: 0 ---------------
[CLOCK - M] Encontre victima. Frame: 4	 Carpincho: 3	 Pagina: 0 P: 1	 U: 0	 M: 0 ---------------
[CLOCK - M] Encontre victima. Frame: 10	 Carpincho: 2	 Pagina: 3 P: 1	 U: 0	 M: 0 ---------------
[CLOCK - M] Encontre victima. Frame: 11	 Carpincho: 3	 Pagina: 3 P: 1	 U: 0	 M: 0 ---------------
[CLOCK - M] Encontre victima. Frame: 3	 Carpincho: 2	 Pagina: 1 P: 1	 U: 0	 M: 1 ---------------
[CLOCK - M] Encontre victima. Frame: 5	 Carpincho: 3	 Pagina: 1 P: 1	 U: 0	 M: 1 ---------------
[CLOCK - M] Encontre victima. Frame: 7	 Carpincho: 2	 Pagina: 2 P: 1	 U: 0	 M: 1 ---------------
[CLOCK - M] Encontre victima. Frame: 8	 Carpincho: 3	 Pagina: 2 P: 1	 U: 0	 M: 1 ---------------
[CLOCK - M] Encontre victima. Frame: 3	 Carpincho: 2	 Pagina: 0 P: 1	 U: 0	 M: 0 ---------------

Muchas gracias!

**Comment by fedesz** [comment]
Claro Dami, justamente en esto que decis coincide con nuestro problema. El esquema en el 5 esta asi:

[CLOCK - M] Antes De comenzar el algoritmo. Frame: 0	 Carpincho: 1	 Pagina: 4 P: 1	 U: 1	         M: 1
[CLOCK - M] Antes De comenzar el algoritmo. Frame: 1	 Carpincho: 1	 Pagina: 1 P: 1	 U: 1	         M: 1
[CLOCK - M] Antes De comenzar el algoritmo. Frame: 2	 Carpincho: 1	 Pagina: 0 P: 1	 U: 1	         M: 0
[CLOCK - M] Antes De comenzar el algoritmo. Frame: 3	 Carpincho: 2	 Pagina: 1 P: 1	 U: 0	 M: 1
[CLOCK - M] Antes De comenzar el algoritmo. Frame: 4	 Carpincho: 1	 Pagina: 5 P: 1	 U: 1	         M: 1
[CLOCK - M] Antes De comenzar el algoritmo. Frame: 5	 Carpincho: 3	 Pagina: 1 P: 1	 U: 0	 M: 1
[CLOCK - M] Antes De comenzar el algoritmo. Frame: 6	 Carpincho: 1	 Pagina: 2 P: 1	 U: 1	         M: 1
[CLOCK - M] Antes De comenzar el algoritmo. Frame: 7	 Carpincho: 2	 Pagina: 2 P: 1	 U: 0	 M: 1
[CLOCK - M] Antes De comenzar el algoritmo. Frame: 8	 Carpincho: 3	 Pagina: 2 P: 1	 U: 0         M: 1
[CLOCK - M] Antes De comenzar el algoritmo. Frame: 9	 Carpincho: 1	 Pagina: 3 P: 1	 U: 1	         M: 1
[CLOCK - M] Antes De comenzar el algoritmo. Frame: 10	 Carpincho: 2	 Pagina: 3 P: 1	 U: 0	 M: 0
[CLOCK - M] Antes De comenzar el algoritmo. Frame: 11	 Carpincho: 3	 Pagina: 3 P: 1	 U: 0	 M: 0

Puede ser que estemos teniendo inconvenientes en que nosotros cuando creamos la pagina, la mandamos directamente a Swap, por ende cuando la cargamos en memoria esta con el bit de modificado en 0?

**Comment by iago64** [comment]
Buenas!

Si, porque cuando creas la página en swap, la tendrías que crear vacía y los cambios que hagas al momento de hacer `memalloc()` son escrituras posteriores a la creación de la página.

Saludos.-

**Comment by fedesz** [comment]
ufffff nos acabas de tirar un dato que nos salvo la vida dami, pensabamos que la pagina se creaba "llena" digamos y por eso no aparecia modificada desde un principio! esto cambia toda nuestra existencia. Ahora probamos con eso y si esta todo ok avisamos!!!

**Comment by fedesz** [comment]
@iago64 Nos anduvo!!!! sos lo mas Dami! posta muchas gracias por la buena onda y la dedicacion! se agradece montones

**Comment by iago64** [comment]
Buenas!
Entonces nos quedamos tranquilos de que todo esta ok 😄!
Cierro el issue pero saben que siempre pueden reabrirlo si es necesario o citarlo en un nuevo issue.
Saludos.-
