### ISSUE TITLE
Duda SWAMP lleno

### ISSUE THREAD

**Issue by marianopoll** [sisoputnfrba/foro#2514]
Hola!

Realizando pruebas con mi grupo nos dimos cuenta que al llenarse SWAMP memalloc debe " en caso de que no haya más espacio (tanto memoria como en swap), se denegará la operación haciendo que la biblioteca devuelva la dirección NULL." La cual sustituimos con un 0 debido a que memalloc devuelve un entero representante de la posición del alloc de un proceso . Pero la posición 0 es recibida por las otras funciones (memwrite, memread o memfree) como una posición a operar ¿Qué deberíamos hacer en esta situación? ¿es un caso que debemos contemplar?

Desde ya muchas gracias

Saludos.

**Comment by tferraro** [comment]
Buenas!

Las demás funciones no deberían tomarla como una posición válida.
Bah, nunca tendrías en realidad la dirección 0x0 como valída por 2 motivos:
- Por un lado esto que comentás, el `NULL` es el "algo falló en el malloc" y no es una direccion que normalmente puedas usar (al igual que pasa con malloc normalmente)
- Y por el otro, por las propia forma de trabajar las direcciones de los punteros de metadata, no deberia ser una posición válida de memoria, porque estaría apuntando a la metadata, no a la memoria posta 😅

Les diría de hacer como hacen los SO en la práctica y denegar las direcciones NULLs :)
