### ISSUE TITLE
Diferencias en Prueba TLB - Marcos distintos

### ISSUE THREAD

**Issue by mabelenda** [sisoputnfrba/foro#2515]
Buenas, realizando las pruebas `TLB FIFO` nos encontramos con una diferencia en el resultado esperado utilizando la configuración `MARCOS_POR_CARPINCHO=4` vemos que el reemplazo se realiza correctamente, pero encontramos el siguiente patrón 

```
1A 2A 2B 1B 
```
También realizando la misma con `MARCOS_POR_CARPINCHO=3` notamos que el resultado es el mismo al de las pruebas en ocasiones, es decir, al correrlo una vez obtenemos el la respuesta esperada, y en la segunda iteración, la respuesta mostrada arriba

**Mi consulta son las siguiente:** 
1. ¿Tenemos algún error? Porque la prueba debe realizarse con 4 Marcos por carpincho
2. ¿Este resultado obtenido puede ser considerado correcto? Creemos que el mensaje que obtenemos primero es el correspondiente a la lectura/escritura de la pagina 2 del proceso B.

Además no sabemos, si el potencial race condition lo encontramos en la prueba, o en nuestro modulo

Comparto los Logs de ambas pruebas.
[logs_tlb_fifo_cuatro_marcos.txt](https://github.com/sisoputnfrba/foro/files/7707869/message.1.txt)
[logs_tlb_fifo_tres_marcos_OK.txt](https://github.com/sisoputnfrba/foro/files/7707943/message.2.txt)
[logs_tlb_fifo_tres_marcos_bad.txt](https://github.com/sisoputnfrba/foro/files/7707947/message.3.txt)

Gracias!! 😃

**Comment by iago64** [comment]
Buenas! Cómo va?

Por esas casualidades que dirección devuelven cuando hacen un `memalloc()`? Porque si devuelven la dirección del heap_metadata, ahí puede ser que tengan la diferencia.

Respecto al resultado, el correcto es el que pasamos y que de hecho lo charlamos en el issue #2511.

Saludos.-
