### ISSUE TITLE
Problema con tabla de página y listas 

### ISSUE THREAD

**Issue by matiaspar2000** [sisoputnfrba/foro#2516]
Buenas, estamos teniendo un problema con la tabla de páginas a la hora de buscarla y leer el contenido. Nosotros iniciamos la tabla así sin problemas y se crea bien

```c
void crear_tabla_de_paginas(uint32_t pid){
	t_tabla_de_paginas *tablaDePaginas = malloc(sizeof(t_tabla_de_paginas));

	tablaDePaginas->pid=pid;
	tablaDePaginas->paginas=list_create();
	tablaDePaginas->tlbHit = 0;
	tablaDePaginas->tlbMiss = 0;
	list_add(lista_de_tablas_de_paginas,tablaDePaginas);
}
```

Esta tabla tiene una lista de páginas la cual vamos llenando mientras es necesario, después de esto realizamos un mate_memalloc(), guardamos algunas cosas y funciona bien (para comprobar printeamos los valores de tlbHit, Miss y list_size(paginas) y da como tiene que dar).

Después de esto y sin nada en el medio salvo el responder a la matelib hacemos un memwrite y queremos buscar esta tabla de páginas 

```c
bool tabla_de_paginas_tiene_pid(void* x){
	t_tabla_de_paginas* elem = x;
	return elem->pid == static_pid;
}

t_tabla_de_paginas* list_find_by_pid(uint32_t pid){
	pthread_mutex_lock(&MUTEX_TABLAS_DE_PAGINAS);
	static_pid = pid;
	t_tabla_de_paginas* elem = list_find(lista_de_tablas_de_paginas, &tabla_de_paginas_tiene_pid);
	pthread_mutex_unlock(&MUTEX_TABLAS_DE_PAGINAS);
	if(elem != NULL && elem->paginas != NUL ){
		printf("PID: %d \n", elem->pid);
		printf("TLB HIT: %d \n", elem->tlbHit);
		printf("TLB MISS: %d \n", elem->tlbMiss); 
		printf("CANT PAGINAS: %d \n", list_size(elem->paginas));
	}
	return elem;
}
```

En este momento printeamos los valores y nos dan cosas distintas (por ej el TLB HIT da 4 en vez de 0 como al final del memalloc), tlb miss printea un valor cualquiera ej. 134514916 y cuando quiere hacer list_size o cualquier otra operacion de listas el programa se rompe.

Alguna idea de que podría estar pasando?

**Comment by iago64** [comment]
Buenas!

La primer idea que se me viene a la cabeza es preguntarte si lo corrieron con valgrind, porque esto tiene toda la pinta de ser que están pifiando fuerte con la memoria y están pisando alguna referencia y por eso les pasa que cuando imprimen valores se les va todo al tacho.

Saludos.-

**Comment by matiaspar2000** [comment]
Buenas, tenemos un problema con Valgrind, en nuestro proyecto tenemos la carpeta "Default" y no nos deja correrlo con Valgrind. Probando otros proyectos vemos que los que están creados de otra manera y tienen la carpeta "Debug" si nos deja correrlo, no se si tendrá algo que ver esto o cómo podemos correr los que tienen Default

![image](https://user-images.githubusercontent.com/62450031/146017255-66f932d2-cd7e-42ee-bcbe-853de428d1fc.png)

**Comment by RaniAgus** [comment]
¡Buenas! ¿Podemos ver la build configuration que usan para buildear el módulo memoria?

**Comment by matiaspar2000** [comment]
Al final lo solucionamos mas fácil creando el proyecto de nuevo y que se cree la carpeta Debug, ahora lo que si tenemos otro problema a la hora de deserializar el void* que mandamos en el memwrite.


Para serializar se hace bien
```c
t_buffer* serializar_memwrite(uint32_t pid, int32_t destino, int size, void* origen){
	t_buffer* buffer = malloc(sizeof(t_buffer));
	void* stream = malloc(sizeof(uint32_t) + sizeof(uint32_t)  + sizeof(int) + size);

	int desplazamiento = 0;

	memcpy(stream + desplazamiento, (void*)(&pid), sizeof(uint32_t));
	desplazamiento += sizeof(uint32_t);

	memcpy(stream + desplazamiento, (void*)(&destino), sizeof(int32_t));
	desplazamiento += sizeof(int32_t);

	memcpy(stream + desplazamiento, (void*)(&size), sizeof(int));
	desplazamiento += sizeof(int);

	memcpy(stream + desplazamiento, (void*)(origen), size);
	desplazamiento += size;

	buffer->size = desplazamiento;
	buffer->stream = stream;
	return buffer;
}
```

Y para deserializar rompe cuando recibe el void* 

```c
t_memwrite* recibir_memwrite(int socket_carpincho){
	int size;
	void* buffer;
	int desplazamiento = 0;
	t_memwrite* des = malloc(sizeof(t_memwrite));

	buffer = recibir_buffer(&size, socket_carpincho);

	memcpy(&(des->pid), buffer+desplazamiento, sizeof(uint32_t));
	desplazamiento += sizeof(uint32_t);

	memcpy(&(des->dir_log), buffer+desplazamiento, sizeof(int32_t));
	desplazamiento += sizeof(int32_t);

	memcpy(&(des->size), buffer+desplazamiento, sizeof(int));
	desplazamiento += sizeof(int);

	memcpy((des->data), buffer+desplazamiento, des->size); //aca rompe

	free(buffer);
	return des;
}
```

Yo había pensado que quizas tenia que ver con que al serializar el voiid* (origen) no le estoy agregando el & lo mismo al hacer el memcpy a des->data pero tampoco parece andar bien así. 

Corriendolo con valgrind me tira "Invalid write of size 4". Como dato lo que estoy enviando como void* es un string de size 5 (4 letras + \0)

**Comment by alejcha** [comment]
Buenas creo que el problema está en
recibir_memwrite
A des le asignas un tamaño fijo, pero es variable lo que te manda
Tendrías que de alguna forma tener el tamaño del dato primero para saber cuánto reservar

**Comment by matiaspar2000** [comment]
Parece que si era eso, lo cambié y lo demás que había preguntado se terminó arreglando. Muchas gracias, cierro hilo.
