### ISSUE TITLE
Pruebas planificador

### ISSUE THREAD

**Issue by AlexanderArmua** [sisoputnfrba/foro#2517]
Buenas, no se si se puede subir este tipo de consultas, pero considerando que la semana que viene es la última entrega, para no arriesgarme quisiera subirles las pruebas de algunos testcases para asegurarme que este todo bien :)

## Test de Planificación
No logré capturar un caso distinto en SJF, pero nos pasó que 1 de cada 10 ejecuciones mas o menos, en SJF salía distinto y vimos que era por una diferencia de milisegundos donde la cola de READY estaba vacía.

[planificador_01_sjf.log](https://github.com/sisoputnfrba/foro/files/7708772/planificador_01_sjf.log)
[planificador_02_hrrn.log](https://github.com/sisoputnfrba/foro/files/7708773/planificador_02_hrrn.log)

## Test de deadlock
Optamos por realizar una búsqueda en DFS a los grafos entre hilos y semáforos. Cuando encontramos el PID mayor, le retornamos a la lib que espera en WAIT que el hilo murió y hacemos un pthread_exit al hilo.

![ Todos los procesos en deadlock ](https://user-images.githubusercontent.com/11699672/145924156-611d5675-b9cc-4258-8d9f-694e5ca54932.PNG)
En la primer foto, se ve que el carpincho con PID-1 finalizó y el resto esta en un deadlock.  Y mas abajo el algoritmo que busca el deadlock como recorre los procesos.

![ Ultimos 2 hilos en deadlock ](https://user-images.githubusercontent.com/11699672/145924227-d3982758-73c3-4adf-bd1f-06bb9a440eb6.PNG)
En la segunda foto, es lo mismo pero solo entre los PID-6 y PID-7.

## Test de Suspensión
Dejo un archivo de texto con los logs, los fuí siguiendo y tienen sentido, pero igualmente los simplifiqué bastante y se los paso.

[planificador_suspension_sjf.log](https://github.com/sisoputnfrba/foro/files/7708685/planificador_suspension_sjf.log)

Igualmente tengo una duda que me surgió recientemente con este test. Si tengo 3 carpinchos (PID 1, 2 y 3). 
- PID-1 y PID-2 se encuentran bloqueados por el mismo dispositivo de E/S. 
- PID-3 se quiere bloquear para usar el mismo dispositivo pero debe moverse a SUSP-BLOQ.
- PID-1 y PID-2 terminan de usar el dispositivo y PID-3 sigue en SUSP-BLOQ. 
- Ahora, el PID-3 ¿Debería recién salir de SUSP-BLOQ cuando termine de usar el E/S?

Desde ya muchas gracias y disculpen por las molestias :)

**Comment by iago64** [comment]
Buenas!

Respecto de las pruebas de plani, lo de la diferencia medio justa es algo que ya tuvimos en cuenta y no se tienen que preocupar porque es algo muy justo y que se resuelve cambiando el tiempo de IO a 1 segundo, eso hace que en SJF no quedes tan jugado y en HRRN si hay un mínimo cambio en la secuencia quedando el orden de ejecución 1-2-3-1-2-1-3-1-2-3-2-3

La prueba de suspensión es bastante simple, es entran 2 carpinchos a EXEC, pasan a BLOQ y como no hay nada en READY pero si en NEW hay que suspender para que entren los otros 2, no es precisamente una prueba MUY compleja porque nos dimos cuenta que iba a ser eterna de testear si nos poníamos densos con los casos 😄 

Saludos.-

**Comment by AlexanderArmua** [comment]
Con respecto a las estimaciones hicimos esa prueba con 1 segundo y la diferencia en las estimaciones es muy chica (dejo un ejemplo abajo)
![image](https://user-images.githubusercontent.com/11699672/146112213-6717fa97-15d9-42bd-8a9e-8c97c0b3a854.png)

Y con la prueba de suspendido tengo una pregunta.
Segun mencionaba el TP, deberia haber carpinchos en bloqueado, no deberia haber en ready y deberia haber en new. 
Ahora: ¿Deberíamos tomar los carpinchos en suspendido-ready, como si estuvieran en new? Porque sinó en la prueba de suspendido llega un momento que quedan 2 carpinchos suspendidos hasta que los otros 2 terminan.

**Comment by iago64** [comment]
Buenas! Cómo va?

Respecto de las estimaciones, si el cambio del valor es relativamente chico, lo que importa es que con un IO de 1 segundo se aseguran de que no caen en una condición de carrera de ver que pasa primero, si el fin del IO o el fin del sleep del carpincho

Respecto de la suspensión:
Es algo que nos quedo mal en el enunciado y si nos apegamos a la teoría cruda deberían haber tomado el suspended-ready a la par de new para ver si hacia falta suspender algo, pero dado que no esta en el enunciado, esta bien que no lo consideren y no hay problema con que suspendan 2 y esos queden suspendidos hasta que alguno de los otros 2 terminen.

Saludos.-

**Comment by AlexanderArmua** [comment]
Perfecto muchas gracias!

**Comment by iago64** [comment]
Resueltas las dudas, no se olviden de cerrar los issues 😄 👮‍♂️
