### ISSUE TITLE
DUDA RESULTADO ESPERADO PRUEBA DE SWAMP

### ISSUE THREAD

**Issue by Aanchart** [sisoputnfrba/foro#2518]
Buenas,
Nosotros presentamos el TP el Sábado pasado y habíamos tenido un error en como se guardaban los datos en el archivo de la swap, logramos solucionarlo pero tenemos duda de si lo que se espera es que en cada archivo se escriba un carpincho, porque les habíamos entendido que solo se guardaban dos carpinchos y había uno que nunca debería ir a swap por eso la duda.
Les paso los archivos que se generaron luego de correr la prueba y la config que estamos usando para correr esta prueba que es la que nos pidieron que usemos el mismo sábado.

con hexdump en consola vemos lo siguiente

```
utnso@ubuntu-server ~ $ hexdump -C swap1.bin
00000000  ff ff ff ff 13 00 00 00  00 43 41 52 50 49 4e 43  |.........CARPINC|
00000010  48 4f 33 00 00 00 00 3c  4e 00 00 00 00 00 00 00  |HO3....<N.......|
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000030  00 00 00 00 00 00 00 00  00 00 00 00 13 00 00 00  |................|
00000040  ff ff ff ff 01 00 00 00  00 00 00 00 00 00 00 00  |................|
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00005000
utnso@ubuntu-server ~ $ hexdump -C swap2.bin
00000000  13 00 00 00 2a 00 00 00  00 00 20 00 00 00 34 00  |....*..... ...4.|
00000010  00 00 00 00 2a 00 00 00  3e 00 00 00 00 00 34 00  |....*...>.....4.|
00000020  00 00 48 00 00 00 00 00  3e 00 00 00 52 00 00 00  |..H.....>...R...|
00000030  00 00 48 00 00 00 5c 00  00 00 00 00 52 00 00 00  |..H...\.....R...|
00000040  ff ff ff ff 13 00 00 00  00 43 41 52 50 49 4e 43  |.........CARPINC|
00000050  48 4f 32 00 00 00 00 20  00 00 00 00 12 00 00 00  |HO2.... ........|
00000060  66 00 00 00 00 00 5c 00  00 00 70 00 00 00 00 00  |f.....\...p.....|
00000070  66 00 00 00 7a 00 00 00  00 00 70 00 00 00 ff ff  |f...z.....p.....|
00000080  ff ff 01 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000090  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00005000
utnso@ubuntu-server ~ $ hexdump -C swap3.bin
00000000  ff ff ff ff 13 00 00 00  00 43 41 52 50 49 4e 43  |.........CARPINC|
00000010  48 4f 31 00 00 00 00 20  00 00 00 00 13 00 00 00  |HO1.... ........|
00000020  13 00 00 00 2a 00 00 00  00 00 20 00 00 00 34 00  |....*..... ...4.|
00000030  00 00 00 00 2a 00 00 00  3e 00 00 00 00 00 34 00  |....*...>.....4.|
00000040  00 00 48 00 00 00 00 00  3e 00 00 00 52 00 00 00  |..H.....>...R...|
00000050  00 00 48 00 00 00 5c 00  00 00 00 00 52 00 00 00  |..H...\.....R...|
00000060  66 00 00 00 00 00 5c 00  00 00 70 00 00 00 00 00  |f.....\...p.....|
00000070  66 00 00 00 7a 00 00 00  00 00 70 00 00 00 84 00  |f...z.....p.....|
00000080  00 00 00 00 7a 00 00 00  8e 00 00 00 00 00 84 00  |....z...........|
00000090  00 00 ff ff ff ff 01 00  00 00 00 00 00 00 00 00  |................|
000000a0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00005000
```

La config que estamos usando es en la RAM un tamaño de memoria de 160 y de pagina de 32 y en la swamp un tamaño de marco de 32 y de tamaño de swap de 20480.

Por otro lado tambien queríamos aprovechar a consultar si en la prueba de Batalla por nordelta, solo se valida que todo termine y que no haya leaks o deberíamos tener en cuenta validar algo más.

Desde ya muchas gracias por su respuesta y disculpen si no se ve bien lo pegado del hexdump.

**Comment by iago64** [comment]
Buenas! Cómo va?

El caso de que "nunca" se guarda en swamp es si usan la configuración original ya que la página nunca se llega a reemplazar en memoria principal, pero justamente como hicieron un cambio y bajaron a páginas mas chicas lo que tienen ahi estaría bien porque estan teniendo los datos de cada carpincho en un archivo diferente 😄 

La batalla por nordelta efectivamente valida que termine todo y que no tengan esperas activas ni memory leaks.

Saludos.-

**Comment by Aanchart** [comment]
Genial, muchas gracias!!
