### ISSUE TITLE
Falla en prueba [SWAMP]

### ISSUE THREAD

**Issue by mnigliazzo** [sisoputnfrba/foro#2519]
Buenas, como andan? Estamos teniendo un error en la prueba de swamp. La falla que obtenemos es que no lee mal el heapmetadata llegando al final de la corrida, aproximadamente en la iteracion 800. No estamos encontrando el problema pero creemos que es cuando se parte el heapmetadata ya que arranca en la direccion logica 4092 y debe ir hasta la 4101, pero en el medio hay un cambio de pagina, Colocamos el log para ver un poco mas de detalle

```sh
[INFO] 13:36:54:122 memoria/(6824:6838): [PAGINA REFERENCIADA - CARPINCHO: 2 PAGINA: 1]
[INFO] 13:36:54:123 memoria/(6824:6838): [Lectura de HEAP METADATA] Lectura de memoria Principal de la direccion logica 4062 que esta en la direccion fisica 8158
[INFO] 13:36:54:123 memoria/(6824:6838): [LECTURA DE HEAP METADATA] Lei de memoria 9 bytes que estaban en la direccion fisica 8158
[INFO] 13:36:54:123 memoria/(6824:6838): [LECTURA DE HEAP METADATA] Termine de leer el Heap Metadata, cuyos valores son: prevAlloc: 4052	 nextAlloc: 4072	 isFree: 0
[INFO] 13:36:54:123 memoria/(6824:6838): [PAGINA REFERENCIADA - CARPINCHO: 2 PAGINA: 1]
[INFO] 13:36:54:123 memoria/(6824:6838): [Lectura de HEAP METADATA] Lectura de memoria Principal de la direccion logica 4072 que esta en la direccion fisica 8168
[INFO] 13:36:54:123 memoria/(6824:6838): [LECTURA DE HEAP METADATA] Lei de memoria 9 bytes que estaban en la direccion fisica 8168
[INFO] 13:36:54:123 memoria/(6824:6838): [LECTURA DE HEAP METADATA] Termine de leer el Heap Metadata, cuyos valores son: prevAlloc: 4062	 nextAlloc: 4082	 isFree: 0
[INFO] 13:36:54:123 memoria/(6824:6838): [PAGINA REFERENCIADA - CARPINCHO: 2 PAGINA: 1]
[INFO] 13:36:54:123 memoria/(6824:6838): [Lectura de HEAP METADATA] Lectura de memoria Principal de la direccion logica 4082 que esta en la direccion fisica 8178
[INFO] 13:36:54:123 memoria/(6824:6838): [LECTURA DE HEAP METADATA] Lei de memoria 9 bytes que estaban en la direccion fisica 8178
[INFO] 13:36:54:123 memoria/(6824:6838): [LECTURA DE HEAP METADATA] Termine de leer el Heap Metadata, cuyos valores son: prevAlloc: 4072	 nextAlloc: 4092	 isFree: 0
[INFO] 13:36:54:123 memoria/(6824:6838): [PAGINA REFERENCIADA - CARPINCHO: 2 PAGINA: 1]
[INFO] 13:36:54:123 memoria/(6824:6838): [Lectura de HEAP METADATA] Lectura de memoria Principal de la direccion logica 4092 que esta en la direccion fisica 8188
[INFO] 13:36:54:123 memoria/(6824:6838): [LECTURA DE HEAP METADATA] Lei de memoria 4 bytes que estaban en la direccion fisica 8188
[INFO] 13:36:54:123 memoria/(6824:6838): [PAGINA REFERENCIADA - CARPINCHO: 2 PAGINA: 2]
[INFO] 13:36:54:123 memoria/(6824:6838): [Lectura de HEAP METADATA] Lectura de memoria Principal de la direccion logica 4096 que esta en la direccion fisica 8192
[INFO] 13:36:54:123 memoria/(6824:6838): [LECTURA DE HEAP METADATA] Lei de memoria 5 bytes que estaban en la direccion fisica 8192
[INFO] 13:36:54:123 memoria/(6824:6838): [LECTURA DE HEAP METADATA] Termine de leer el Heap Metadata, cuyos valores son: prevAlloc: 2056	 nextAlloc: -1	 isFree: 1
[INFO] 13:36:54:129 memoria/(6824:6838): [PAGINA REFERENCIADA - CARPINCHO: 2 PAGINA: 1]
[INFO] 13:36:54:129 memoria/(6824:6838): [Lectura de HEAP METADATA] Lectura de memoria Principal de la direccion logica 2056 que esta en la direccion fisica 6152
[INFO] 13:36:54:129 memoria/(6824:6838): [LECTURA DE HEAP METADATA] Lei de memoria 9 bytes que estaban en la direccion fisica 6152
[INFO] 13:36:54:129 memoria/(6824:6838): [LECTURA DE HEAP METADATA] Termine de leer el Heap Metadata, cuyos valores son: prevAlloc: 2062	 nextAlloc: 134531072	 isFree: 0
[INFO] 13:36:54:129 memoria/(6824:6838): [PAGINA REFERENCIADA - CARPINCHO: 2 PAGINA: 1]
[INFO] 13:36:54:129 memoria/(6824:6838): [Lectura de HEAP METADATA] Lectura de memoria Principal de la direccion logica 2056 que esta en la direccion fisica 6152
[INFO] 13:36:54:129 memoria/(6824:6838): [LECTURA DE HEAP METADATA] Lei de memoria 9 bytes que estaban en la direccion fisica 6152
[INFO] 13:36:54:129 memoria/(6824:6838): [LECTURA DE HEAP METADATA] Termine de leer el Heap Metadata, cuyos valores son: prevAlloc: 2062	 nextAlloc: 134531072	 isFree: 0
```

Muchas Gracias
Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

Consulta, antes de llegar al final de la corrida, estuvieron controlando el contenido de los archivos de swap? Que contenido tienen? (Lo pueden ver rápidamente con el comando `hexdump -C <archivo>`

Abrazo!

**Comment by fedesz** [comment]
hola dami! justamente no nos llega al final de la corrida porque explota por como lee los heap metadatas, que al leer mal uno explota! hicimos el hexdump -C y dice CARPINCHO X al principio, pero despues quedan llenos de contenido random porque no estoy seguro de que se esten bajando las paginas a swap, dado que si no se hacen reemplazos no se bajan!

**Comment by iago64** [comment]
En ese caso, si saben que tienen un problema de lectura de memoria, valgrind es su mejor amigo, revisen los invalid read / invalid write que les marque valgrind, que mas que seguro que ahí tienen el problema.

Saludos.-

**Comment by fedesz** [comment]
en realidad, "el problema de lectura" puede ser que venga de la mano por haber partido mal un free alloc, o algo del estilo, pero nos esta costando mucho trackear en que momento pasa. Nos llamo mucho la atencion que en el ultimo alloc, marca como prevAlloc a la direccion logica 2056, que esta muuuuy lejos, lo cual nos da dudas de que puede estar pasando. No se si tenes alguna otra sugerencia para revisar, mas alla de los invalid read y write que ahora vamos a checkear!

**Comment by fedesz** [comment]
Esto puede tener que ver con lo que nos esta pasando dami?

![image](https://user-images.githubusercontent.com/45084886/146104054-6aeaeb8c-d870-4bd8-83e8-3b22266ae29d.png)

**Comment by tferraro** [comment]
😉 https://faq.utnso.com.ar/valgrind

**Comment by fedesz** [comment]
Buenas! estuvimos leyendo lo que nos comentaban, corregimos lo que decia valgrind pero aun asi no modifico en nada el comportamiento! alguna otra soga que nos puedan tirar? gracias!

**Comment by iago64** [comment]
La segunda idea que se me ocurre es que al momento de reconstruir el heap_metadata partido no estan haciendolo de la manera correcta, por las dudas, les pregunto, lo tienen en una variable aparte y lo copian tal cual esta en la memoria cuando lo guardan y cuando lo levantan?

**Comment by fedesz** [comment]
lo que estamos haciendo es antes de empezar a leer, armamos un void* que luego vamos haciendole memcpy con lo que vamos leyendo de memoria principal. Una vez q termina la lectura, devolvemos ese void* casteado a heap_metadata_t*

**Comment by fedesz** [comment]
dami, aprovecho y te consulto... puede llegar a estar pasando que nos esten reemplazando la pagina antes de que pueda terminar de leer el heap metadata? digamos, habria que implementar un lockeo de la pagina para que no la pueda tocar mientras este haciendo una operacion de lectura/escritura. Puede ser? o estamos flasheandola mucho ya? gracias!

**Comment by iago64** [comment]
Buenas!

Si, puede llegar a pasar, las condiciones exactas te las debo porque ya va un poco mas en como lo hayan implementado, pero en líneas generales es una condición que se les puede llegar a dar, con lo cual, seria bueno que tengan algo de sincro en ese punto.
Si quieren validar si tienen algo pueden correr su tp con helgrind y ahí van a tener al menos un indicio de las posibles condiciones de carrera que se les están dando.

Saludos.-

**Comment by fedesz** [comment]
Dami, implementamos el lockeo pero no llegamos a un mejor resultado. Estamos hace 3/4 dias con esta prueba que no logramos hacerla correr, y ya nos quedamos sin ideas... Es la unica prueba q no nos esta corriendo, y ya no sabemos que hacer jaja. No se si tienen alguna sugerencia, podemos pasar algun fragmento de codigo, algoritmo, lo que sea! Pero estamos ya en el manotazo de ahogado 🤣

**Comment by iago64** [comment]
Buenas!

Una pregunta importante, cuando se "frena" la ejecución, que contenido tienen en los archivos de swamp? pueden subir el resultado de un hexdump?

Saludos.-

**Comment by fedesz** [comment]
Dami, creemos que encontramos el problema! estabamos mandando mal un size desde la swap a la memoria, entonces siempre le llegaba menos infomracion de la pagina a la memoria! Estamos corriendo nuevamente la prueba a ver si funciona con esto, y cualquier cosa te avisamos! Por lo que lei en otros issues, deberia correr durante infinito tiempo y en algun momento en swap deberian aparecer los 3 carpinchos en archivos diferentes, no?

**Comment by iago64** [comment]
Buenas!

Efectivamente, deberían tener el contenido de los carpinchos repartido en los archivos.
Un archivo va a tener el contenido del carpincho 1, otro el contenido del carpincho 2 y el último el contenido del carpincho 3.

Saludos.-

**Comment by fedesz** [comment]
Dami, como va? ya no nos explota el codigo, pero notamos que las paginas 0 de los carpinchos 1 y 2 nunca se bajan a swap. Primero ejecutan los carpinchos 1 y 2 y hacen la secuencia de ir sumando 1, y en un momento aparece el acaparador, y agarra toda la consola aprox. Pero al parecer nunca estamos bajando esas paginas. Nosotros tomamos la estrategia de crear la pagina vacia, y luego cuando se la reemplace y este modificada, se escribe en SWAP. Estaria mal esto que nos esta pasando, desde el punto de vista de la prueba? O se puede justificar debido a nuestra estrategia?

**Comment by fedesz** [comment]
Aclaro por las dudas, el acaparador nos aparece aprox en la iteracion 400 y algo

**Comment by iago64** [comment]
Buenas!

Si quieren apurar la bajada a swamp lo que pueden hacer es achicar el tamaño de página a 32 bytes y el tamaño de la memoria a 160 bytes (5 frames) y deberían ver antes el contenido, pero no hay problema con que tarde, es algo contemplado en la prueba 😉 

Saludos.-

**Comment by fedesz** [comment]
Dami, pusimos el delay de la swap en 0 y nos anduvo joya! el problema es que por alguna razon, cuando le ponemos el delay de la swap, nos explota.. y no entendemos que peude estar pasando

**Comment by iago64** [comment]
Buenas! Cómo va?

A que llamas explotar? Que error tienen? Lo corrieron con valgrind? Si lo hicieron, que les dice? 
El nos explota en el aire no me ayuda mucho para ayudarlos 😢 

Saludos.-

**Comment by fedesz** [comment]
Hola dami, ya lo pudimos solucionar! Cierro el thread. Gracias!
