### ISSUE TITLE
mate_close y recursos asignados

### ISSUE THREAD

**Issue by FernandoLlallire** [sisoputnfrba/foro#2520]
Estamos teniendo dudas en cuanto al comportamiento de los carpinchos al momento de ejecutar el mate_close.
Por el momento tenemos implementado la lógica de esta manera: si un carpincho hace un mate_sem_wait de un semáforo y luego un mate_close, antes de eliminar el carpincho del kernel libera el recurso del semáforo asignado (como si fuera eliminado por deadlock). 
Viendo el issue [#2384](https://github.com/sisoputnfrba/foro/issues/2384#issuecomment-955147577) y probando un ejemplo con el comando de la lib sem_wait nos damos cuenta que si el thread que hizo sem_wait termina, no se modifica el semáforo. 
¿Está bien cómo implementamos la funcionalidad del mate_close? o tenemos que tener el mismo comportamiento de la lib original y delegar la buena práctica a quien usa la libreria?

**Comment by iago64** [comment]
Buenas! Cómo va?

En resumidas cuentas la idea del `mate_close()` es que si tenias tomado algún recurso lo liberes y esto en la práctica se traduce en que si tenias algún carpincho bloqueado por ese semáforo lo desbloquees y ya.

Saludos.-

**Comment by FernandoLlallire** [comment]
Perfecto, gracias!

**Comment by iago64** [comment]
Resuelta la duda, no se olviden de cerrar el issue 😄 👮‍♂️
