### ISSUE TITLE
Algoritmo Clock-M con asignación Fija y Local

### ISSUE THREAD

**Issue by Patricio-Galli** [sisoputnfrba/foro#2521]
Buenos días, vengo a hacer una consulta sobre los reemplazos dada una configuración de memoria fija y local y un algoritmo clock-m. Es un caso que no se plantea en las pruebas, así que quiero saber si se pide o evalúa. Más allá de eso, en caso de que lo tuviera que hacer, quiero confimar conceptualmente que mi análisis de lo que tendría que hacer es correcto.

Cada vez que se inicializa un carpincho en memoria (cuando llega un primer alloc o cuando vuelve el carpincho del estado suspendido), se setea el puntero clock en el primer marco del carpincho.
Opción 1: cada vez que se deba hacer un reemplazo, se evalúan los marcos que son propiedad del carpincho y se setea el puntero clock al siguiente marco del subgrupo.
Opción 2: siempre que haya que hacer un reemplazo se ubica el puntero en el primer marco del carpincho.

Tal vez es medio obvia la pregunta, pero quiero estar seguro.

Saludos.

**Comment by iago64** [comment]
Buenas! Cómo va?

Por suerte acá la forma de manejar los punteros es igual que la teoría, en la primer corrida esta al inicio de los marcos y después va a quedar apuntando al siguiente marco del que fue reemplazado.

Saludos.-

**Comment by Patricio-Galli** [comment]
Perfecto, es la primera opción. Muchas gracias.

**Comment by iago64** [comment]
Resuelta la duda, no se olviden de cerrar el issue 😄 👮‍♂️
