### ISSUE TITLE
TIEMPO_DEADLOCK en prueba deadlock

### ISSUE THREAD

**Issue by Nicolas-Russo** [sisoputnfrba/foro#2522]
Buenas, realizando las pruebas de deadlock nos dimos cuenta que usando TIEMPO_DEADLOCK=10000 no nos funciona. Detecta el 1er deadlock nomas. Revisando que es lo que pasaba nos encontramos que si se usa TIEMPO_DEADLOCK=15000 funciona todo bien y es porque el kernel necesita mas de 10 segs para procesar todo lo que se manda de la mate lib y llegar al deadlock antes que se lo interrumpa para correr el algoritmo de deteccion.
Hay algun problema si usamos TIEMPO_DEADLOCK=15000 para las pruebas?

Gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

No entiendo el problema que están teniendo, podrían correr el algoritmo de deadlock cada 1 segundo también y no habría problema, lo importante es que lo detecte, no en que corrida lo detecta 😉 

Saludos.-

**Comment by Nicolas-Russo** [comment]
Aaa claro, okey gracias.
