### ISSUE TITLE
No conecta en las VMs de prueba

### ISSUE THREAD

**Issue by Nicolas-Russo** [sisoputnfrba/foro#2523]
Buenas, queriendo probar en las VMs de prueba no se nos estan conectando los modulos entre si. Por ejemplo no nos esta conectando el swamp con memoria. Las funciones que tenemos para levantar el servidor en swamp son estas:

```C
int iniciarServidor(char* ip, char* puerto, t_log * log) {
	int socketServidor;
	struct addrinfo hints, *servinfo, *p;
	memset(&hints, 0, sizeof(hints));
	hints.ai_family = AF_UNSPEC;
	hints.ai_socktype = SOCK_STREAM;
	hints.ai_flags = AI_PASSIVE;
	getaddrinfo(ip, puerto, &hints, &servinfo);
	for (p = servinfo; p != NULL; p = p->ai_next) {
		if ((socketServidor = socket(p->ai_family, p->ai_socktype, p->ai_protocol)) == -1)
			continue;
                printf("SOCKET: %d \n", socketServidor);
		int activado = 1;
		setsockopt(socketServidor, SOL_SOCKET, SO_REUSEADDR, &activado, sizeof(activado));
		if (bind(socketServidor, p->ai_addr, p->ai_addrlen) == -1) {
			close(socketServidor);
			continue;
		}
		break;
	}
	listen(socketServidor, SOMAXCONN);
	freeaddrinfo(servinfo);
	log_info(log, "SERVIDOR LISTO PARA RECIBIR CLIENTES...");
	return socketServidor;
}
int esperarCliente(int socketServidor, t_log * log) {
	struct sockaddr_in dirCliente;
	socklen_t tamDireccion = sizeof(struct sockaddr_in);
	int socketCliente = accept(socketServidor, (void*) &dirCliente, &tamDireccion);
	printf("%s\n", strerror(errno));
	log_info(log, "SE CONECTO UN CLIENTE!!!!");
	return socketCliente;
}
```

Y estas son las de memoria:
```C
int crearConexion(char* ip, char* puerto){
	  	struct addrinfo hints;
	    struct addrinfo *server_info;
	    int clientSocket;
	    memset(&hints, 0, sizeof(hints));
	    hints.ai_family = AF_UNSPEC;
	    hints.ai_socktype = SOCK_STREAM;
	    hints.ai_flags = AI_PASSIVE;
	    int con = getaddrinfo(ip, puerto, &hints, &server_info);
	    printf("getaddrinfo: %d \n", con);
	    if(con){
	    	exit(-1);
	    }
	    clientSocket = socket(server_info->ai_family, server_info->ai_socktype, server_info->ai_protocol);
	    int con2 = connect(clientSocket, server_info->ai_addr, server_info->ai_addrlen);
	    printf("connect: %d \n", con2);
	    if(con2 == -1){
	    	printf("ERROR: %s \n", strerror(errno));
	        exit(-1);
	    }
	    freeaddrinfo(server_info);
	    return clientSocket;
}
```
Cuando se levanta memoria devuelve:
```
getaddrinfo: 0
connect: -1
ERROR: Connection refused
```
Y el print de swamp devuelve: ```SOCKET: 4```

No sabemos que es lo que puede esta mal.

Gracias!

**Comment by LeandroCarbajales** [comment]
Buenas!
Asumiendo que localmente funcionan normalmente, me fijaría primero que la IP a la que se esté conectando la Memoria sea efectivamente la de la VM donde está levantado el SWAmP.

**Comment by Nicolas-Russo** [comment]
Sisi en los archivos de configuracion estamos poniendo bien las IPs y los puertos. Es mas hasta probamos de levantar el servidor pasandole 0.0.0.0, 0 y NULL pero ninguna nos esta funcionando

**Comment by gastoncastineira** [comment]
Buenas
Repito la pregunta de Lean por si acaso. Local les funciona bien? Y otra pregunta, qué IP están poniendo en los archivos de config? La pública  que les pasamos, la privada que les pasamos, u otra?

**Comment by LeandroCarbajales** [comment]
> Sisi en los archivos de configuracion estamos poniendo bien las IPs y los puertos. Es mas hasta probamos de levantar el servidor pasandole 0.0.0.0, 0 y NULL pero ninguna nos esta funcionando

El servidor se debería levantar usando la IP local/privada de la VM, de la misma manera la Memoria debe conectarse a esa IP.

**Comment by Nicolas-Russo** [comment]
Si, estamos poniendo las IPs correctamente, pero no se estan conectando. Lo chequeamos varias veces pero eso esta bien

**Comment by iago64** [comment]
Buenas!

Una pregunta, al momento de crear los socket están validando los errores que les devuelve con [`perror()`](https://www.tutorialspoint.com/c_standard_library/c_function_perror.htm)?

Saludos.-

**Comment by tferraro** [comment]
Holiss, vengo con algo que no es la primera vez que lo veo, pasa cuatrimestre a cuatrimestre (?):
```
int iniciarServidor(char* ip, char* puerto, t_log * log) {
	int socketServidor;
	struct addrinfo hints, *servinfo, *p;
	memset(&hints, 0, sizeof(hints));
	hints.ai_family = AF_UNSPEC;
	hints.ai_socktype = SOCK_STREAM;
	hints.ai_flags = AI_PASSIVE;
	getaddrinfo(ip, puerto, &hints, &servinfo);
	for (p = servinfo; p != NULL; p = p->ai_next) {
		if ((socketServidor = socket(p->ai_family, p->ai_socktype, p->ai_protocol)) == -1)
			continue;
                printf("SOCKET: %d \n", socketServidor);
		int activado = 1;
		setsockopt(socketServidor, SOL_SOCKET, SO_REUSEADDR, &activado, sizeof(activado));
		if (bind(socketServidor, p->ai_addr, p->ai_addrlen) == -1) {
			close(socketServidor);
			continue;
		}
		break;
	}
	listen(socketServidor, SOMAXCONN);
	freeaddrinfo(servinfo);
	log_info(log, "SERVIDOR LISTO PARA RECIBIR CLIENTES...");
	return socketServidor;
}
```

En este iniciarServidor, están pasando una IP. Ya eso hace ruido, el server no necesita una ip, se bindea solo al puerto y va a escuchar en la interfaz de por defecto (creo, o todas, tengo que averiguar).
Ponerle una ip fija solo hace que pueda escuchar sobre "esa ip" o, incluso poner "localhost", termina haciendo que escuchen en la interfaz de loopback y que nunca vea la interfaz publica del 0.0.0.0.

De entrada, saquenle eso. Ahora, comentan que ni con eso anda, saquenle el `setsockopt` y prueben que onda. He visto algunas veces que setear el `SO_REUSEADDR` falla aunque nunca llegué a indagar bien el detalle de porqué.

Tengo muchos supuestos y pocas respuestas factibles, pero veamos cual va y después le hacemos ing inversa y averiguamos bien 😛 .

De todas formas, no se pierdan del `perror` que dice Dami, porque eso les va a decir cual es el error y lo pueden matchear con lo que dice el `man` de las syscalls

**Comment by Nicolas-Russo** [comment]
Cambie la ip por "localhost" y memoria y swamp se conectan bien. Pero la matelib no se nos conecta con el kernel. El kernel lo estamos levantando asi:
```C
int iniciarServidor(char* ip, char* puerto, t_log * log) {
	    int socketServidor;
	    struct addrinfo hints, *servinfo, *p;
	    memset(&hints, 0, sizeof(hints));
	    hints.ai_family = AF_UNSPEC;
	    hints.ai_socktype = SOCK_STREAM;
	    hints.ai_flags = AI_PASSIVE;
	    getaddrinfo("localhost", puerto, &hints, &servinfo);
	    for (p=servinfo; p != NULL; p = p->ai_next)
	    {
	        if ((socketServidor = socket(p->ai_family, p->ai_socktype, p->ai_protocol)) == -1)
	            continue;

	        if (bind(socketServidor, p->ai_addr, p->ai_addrlen) == -1) {
	        	printf("%s\n", strerror(errno));
	        	close(socketServidor);
	            continue;
	        }
	        break;
	    }
	    listen(socketServidor, SOMAXCONN);
	    freeaddrinfo(servinfo);
	    log_info(log, "SERVIDOR LISTO PARA RECIBIR CLIENTES...");
	    return socketServidor;
}
```
Y el socket que devuelve es siempre mayor a 0.
En la matelib tenemos esto:
```C
int crearConexion(char* ip, char* puerto){
	    struct addrinfo hints;
	    struct addrinfo *server_info;
	    int clientSocket;
	    memset(&hints, 0, sizeof(hints));
	    hints.ai_family = AF_UNSPEC;
	    hints.ai_socktype = SOCK_STREAM;
	    hints.ai_flags = AI_PASSIVE;
	    if(getaddrinfo(ip, puerto, &hints, &server_info)){
                perror("ERROR: ");
	        exit(-1);
	    }
	    clientSocket = socket(server_info->ai_family, server_info->ai_socktype, server_info->ai_protocol);
	    if(connect(clientSocket, server_info->ai_addr, server_info->ai_addrlen) == -1){
                perror("ERROR: ");
	        exit(-1);
	    }
	    freeaddrinfo(server_info);
	    return clientSocket;
}
```
Y nos devuelve ```ERROR: Conection refused```
No entiendo que puede ser porque el socket se esta levantando bien.

**Comment by iago64** [comment]
Buenas! Cómo va?

Si le pasas la dirección 0.0.0.0 y están en la misma VM van a funcionar porque 0.0.0.0 es un análogo a 127.0.0.1 o a localhost (basicamente la misma pc), pero es lo que comenta Tom, **no tienen que asociar un server a una ip, solo tienen que asociarlo al número de puerto**, ya que todas las demas conexiones que no lleguen a esa IP las va a rechazar y en los clientes van a tener el error de Connection refused.

Saludos.-

**Comment by Nicolas-Russo** [comment]
Esta bien, ya probe poniendo ```getaddrinfo(0, puerto, &hints, &servinfo);``` y ```getaddrinfo(NULL,puerto, &hints, &servinfo);``` pero de las 2 formas me sigue tirando ```Conection refused```.
Ya no sabemos que mas probar

**Comment by iago64** [comment]
Buenas!

Un par de cositas que me hacen ruido a la hora de ver lo que están haciendo:

1.- Por que usan el flag `AF_UNSPEC` en lugar del flag `AF_INET` como esta en la [guia de sockets](https://docs.google.com/document/d/17E5ge5eC6wRAeh5AWETRBB7UrmqBQ6i0JjfUD7KRY68/edit#)?

2.- Por que tiene un for para crear sockets y hacer el bind? Uds en el server solo van a querer 1 solo socket servidor (como esta en la [guia de sockets](https://docs.google.com/document/d/17E5ge5eC6wRAeh5AWETRBB7UrmqBQ6i0JjfUD7KRY68/edit#).

3.- Además del print del error en el `bind()` por que no lo tienen en el `listen()`?

4.- Cuando hacen el `accept()` están controlando los valores de retorno / errores?

Saludos.-

**Comment by Nicolas-Russo** [comment]
Arreglamos eso pero igualmente no sigue tirando ```Conection refused```. Tenemos al carpincho y el kernel en una VM y la memoria y swamp en la otra. El carpincho se conecta bien con el kernel pero cuando el kernel se quiere conectar con memoria salta el conection refused, pero memoria y swamp se conectan bien.
Modificamos segun lo que nos dijiste: 
```C
int iniciarServidor(char* puerto) {
	struct addrinfo hints, *servinfo;

	memset(&hints, 0, sizeof(hints));
	hints.ai_family = AF_INET;
	hints.ai_socktype = SOCK_STREAM;
	hints.ai_flags = AI_PASSIVE;

	getaddrinfo(NULL, puerto, &hints, &servinfo);

	int socketServidor = socket(servinfo->ai_family, servinfo->ai_socktype, servinfo->ai_protocol);
	if (socketServidor == -1){
		perror("Error");
		exit(-1);
	}

	int bindReturn = bind(socketServidor, servinfo->ai_addr, servinfo->ai_addrlen);
	if (bindReturn == -1) {
		perror("Error");
		close(socketServidor);
	    exit(-1);
	}

	int escucha = listen(socketServidor, SOMAXCONN);
	if(escucha == -1){
		perror("Error");
	}
	freeaddrinfo(servinfo);
	return socketServidor;
}
```
Pero sigue pasando lo mismo

**Comment by iago64** [comment]
Buenas!

En el servidor hasta este punto, están teniendo algún error? dejan el servidor frenado en el `accept()`?

Del lado del cliente, cambiaron también a que sea `AF_INET`? Del lado cliente, están seteando bien la IP y el puerto del servidor? Ahí si es importante que lo agreguen porque justamente cuando ejecuten la función `connect()` tienen que saber a donde conectarse.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Para sumar a la pregunta de Dami sobre si cambiaron a `AF_INET` desde el lado del cliente que hace el `connect` (o si siguen usando `AF_UNSPEC`), creo que [este comentario](https://github.com/sisoputnfrba/foro/issues/2000#issuecomment-739450264) les puede ayudar. Saludos
