### ISSUE TITLE
Dudas sobre prueba Batalla por Nordelta.

### ISSUE THREAD

**Issue by MastroianniSebastian** [sisoputnfrba/foro#2525]
Haciendo las pruebas nos surge una duda, lo que nos pasa es que el carpincho 7 ejecuta los post y wait todos juntos, queríamos chequear que el resultado es el esperado. 
Muchas gracias.

**Comment by iago64** [comment]
Buenas! 

Si ven el código tiene un while re simple:

```c
int a = 1;
while (a <= 256) {
	mate_sem_post(&instance, "SEMAFORO_NUEVO");
	usleep(200);
	mate_sem_wait(&instance, "SEMAFORO_NUEVO");
	printf("C7 - Vuelta número %d... \n", a);
	a++;
}
```

Lo que nos importa de esa prueba es que no salten esperas activas ni memory leaks 😄 

Saludos.-
