### ISSUE TITLE
Asignacion de semaforos en carpinchos luego de bloqueo

### ISSUE THREAD

**Issue by gastonharari** [sisoputnfrba/foro#2526]
Hola, buenas noches:

Realizando el tema del deadlock y la asignacion de semaforos, nos surgio la siguiente duda:

(Cito este [issue/comentario](https://github.com/sisoputnfrba/foro/issues/2520#issuecomment-994806263))

Es correcto que se considere asignado un recurso para un carpincho, luego que se desbloquea el mismo?

En un ejemplo:
Carpincho 0: init sem1 en 0
Carpincho 1 hace un wait de sem1 ----> Se bloquea
Carpincho 2 hace un post de sem1 --->Desbloquea a Carpincho1

La pregunta es si Carpincho1 tiene que tener asignado a sem1?

Todo esto nos surge por los valores con los cuales deberian quedar los semaforos este ejemplo 2:
![telegram-cloud-photo-size-1-5033015511687997980-x](https://user-images.githubusercontent.com/22179865/146315950-fe377788-afad-48f8-aef0-f2e64d9a15a0.jpg)

Desde ya, muchas gracias

Saludos

**Comment by gastonharari** [comment]
@FernandoLlallire @rocioveloso

**Comment by iago64** [comment]
Buenas! Cómo va?

La idea de un semáforo asignado a un carpincho es justamente en el periodo entre el wait y el signal (o hasta que termine si no hace nunca el signal)

Saludos.-

**Comment by gastonharari** [comment]
Muchas gracias por tu respuesta.

Disculpa por la duda que es reiterativa pero para esclarecerme mejor por que no me termina de quedar claro, es independiente si el semaforo bloqueo al carpincho?
Y si no hace el signal y termina con el semaforo asignado, se le tiene que sumar "1" al semaforo ya que tiene asignado ese semaforo

Gracias!!!

**Comment by iago64** [comment]
Buenas! Cómo va?

Es independiente, porque el carpincho que tiene "tomado" el semáforo puede no estar bloqueado pero si puede haber un carpincho bloqueado, por lo que, al terminar debería desbloquear al primer carpincho bloqueado para dicho semáforo.

Saludos.-

**Comment by gastonharari** [comment]
Perfecto!! muchas gracias!
