### ISSUE TITLE
Pruebas Planificación HRRN

### ISSUE THREAD

**Issue by victoriaguillosson** [sisoputnfrba/foro#2528]
Buenas! Estamos haciendo la prueba de planificación con HRRN y tenemos dudas sobre como queda el orden de los carpinchos.
Adjuntamos los logs con duracionIO =2000 y luego adjuntamos los de duracionIO=1000.

[log_carpinchos_io_2000.txt](https://github.com/sisoputnfrba/foro/files/7730472/log_carpinchos_io_2000.txt)
[log_con_io_2000.txt](https://github.com/sisoputnfrba/foro/files/7730473/log_con_io_2000.txt)

[log_carpinchos_io_1000.txt](https://github.com/sisoputnfrba/foro/files/7730471/log_carpinchos_io_1000.txt)
[log_con_io_1000.txt](https://github.com/sisoputnfrba/foro/files/7730474/log_con_io_1000.txt)

Consideramos que los logs son consistentes y con SJF si coinciden los resultados, al igual que el HRRN con una duracionIO=2000. 

Nuestra duda es si con la duracionIO=1000 estaría mal como terminan, porque segun el issue #2517, el orden de ejecución deberia ser 1-2-3-1-2-1-3-1-2-3-2-3.

Muchas gracias,
Saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

La prueba con 1000 de duración de IO es solamente una medida de "emergencia" para los casos donde veamos algún comportamiento medio errático en la prueba con 2000 de IO.

Lo que me llama un toque la atención es que el Response Ratio les esta dando 1.681818 para el carpincho 3 y de 1.5 para el carpincho 1 (que casualmente coincide con nuestros cálculos) en el momento que les difiere la prueba, que fórmula están usando para calcularlo?

Saludos.-

**Comment by franciscoidalgo** [comment]
Buenas noches! Gracias por la respuesta. En los logs detalla la estimación para la próxima ráfaga, que lo calculamos con la formula ``` estimacion = α * ultima ráfaga + (1 - α) * ultima estimación``` 
Luego, el RR para HRRN lo calculamos con la formula  ```RR = 1 + tiempo en ready / estimacion```
Dejo esto en código de C:
```c
double rafaga_estimada(void* elem) {

	infoConfigKernel info = leer_config(config);

	carpincho* carpinchoA = (carpincho*) elem;

	double rafaga = carpinchoA->ultimaEstimacion != 0 ? ((info.alfa * carpinchoA->ultimaRafaga)
			+ ((1 - info.alfa) * carpinchoA->ultimaEstimacion)) : info.estimacionInicial;

	return rafaga;

}

double calculo_HRRN(void* elem) {
	carpincho* carpinchoA = elem;
	carpinchoA->tiempoTotalEnReady = difftime(timeStampComparacion, carpinchoA->tiempoEnColaActual) * 1000;

	double rafaga = rafaga_estimada(elem);

	double result = 1.0 + (carpinchoA->tiempoTotalEnReady / rafaga);
	
	log_info(loggerKernel, "Carpincho %u:\nTiempo en ready: %f\nRafaga estimada: %f\nResponse ratio: %f", 
				carpinchoA->id, carpinchoA->tiempoTotalEnReady, rafaga, result);

	return result;
}
```
Verificamos los tiempos que toma para las ráfagas y tienen bastante sentido, nos tiene un poco confundidos esto.

**Comment by iago64** [comment]
Buenas!

Ahora si, creo que encontre el problema 😄 
uds estan haciendo 1 + (tiempo en ready / rafaga) pero casualmente HRRN tiene un calculo un pelin diferente y es:

RR = (W + S)/S

RR: Response Ratio
W: Tiempo de espera en Ready
S: Tiempo de ráfaga

Me suena a que por ahí vienen las diferencias, pueden probar a ver si con ese cálculo les dan los resultados (en principio deberían) 😊 

Saludos.-

**Comment by franciscoidalgo** [comment]
Las formulas deberían ser equivalentes (si hago la división por S queda la formula que tenemos nosotros) pero probamos modificándola para ver si hay algún cambio. Con operativos y C ya nada me sorprende jajaja. 
Saludos!

**Comment by iago64** [comment]
Mas allá de que si, deberían ser equivalentes, el redondeo puede ser que este haciendo la diferencia.

Por otro lado, otra cosa, están recalculando todas las estimaciones cuando hay un cambio en la cola de ready? o solo cuando llegan? porque ojo que ahí pueden tener otro punto de inflexión.

Saludos.-

**Comment by franciscoidalgo** [comment]
La estimación la calculamos cada vez que comparamos para ver quién ejecuta. La última estimación la asignamos luego de seleccionar un  carpincho para ejecutar (se guarda la estimación de dicho momento). Como un mini detalle que puede hacer que difiera en microsegundos, no guardamos exactamente la que usa para la comparación sino que la volvemos a calcular inmediatamente después para simplificar el código.

**Comment by iago64** [comment]
Buenas!

Me suena a que es muy mínima la diferencia como para que les cambie la estimación, de todas formas, si con 2000 les esta funcionando correctamente no se quemen mas la cabeza, por las dudas prueben en las VMs de prueba y asegúrense de que corren bien las pruebas ahí y nos vemos el sábado directamente 😄 

Saludos.-

**Comment by victoriaguillosson** [comment]
Muchas gracias Dami, buenas noches!!
