### ISSUE TITLE
Problema para compilar carpinchos-prueba

### ISSUE THREAD

**Issue by matiasbunader** [sisoputnfrba/foro#2531]
Buenas! Estamos teniendo problemas a la hora de compilar los carpinchos de pruebas. Seguimos los pasos del README, pero nos sigue tirando error.

En el readme, la primera alternativa dice: 

Copiar el archivo libmatelib.so que se genera al compilar matelib en uno de los directorios donde el compilador va a buscar las bibliotecas compartidas:

/usr/local/lib
/usr/lib
/lib
💡 ¡Deberás contar con permisos de root para poder copiarlo!

Vemos que el archivo libmate.so está copiado en la carpeta donde le indicamos 
(sudo cp /home/utnso/Documentos/tp-2021-2c-Grupo-SORE/matelib/libmatelib.so /usr/lib), pero al hacer make en carpinchos-pruebas nos tira error.

![Error compilacion](https://user-images.githubusercontent.com/31021438/146483407-1685ca47-87e3-4e98-8305-07bcce525e5d.png)

Seguimos todos los pasos del README pero no logramos compilar, alguna sugerencia?

Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

Por esas casualidades los copiaron en los 3 directorios que menciona el readme?
Otra cosa, probaron con la alternativa 2 de configurar la variable de entorno de LIBRARY_PATH como indica la alternativa 2? 

Saludos.-

**Comment by matiasbunader** [comment]
Buenas! Ya solucionamos este tema y pudimos compilar! Teníamos un error en el makefile.

Cierro, gracias!
