### ISSUE TITLE
Prueba MMU con CLOCK-M

### ISSUE THREAD

**Issue by study64** [sisoputnfrba/foro#2532]
Hola que tal, les cuento que tengo dos discrepancias en las pruebas de reemplazo mmu usando clock-m

El estado esperado es este:

C1P4 | C1P0 | C1P1 | C1P5 | C1P6 | C1P7 | C1P2 | C1P8 | C2P1 | C1P3 | C3P0 | C3P1

Y lo que acabo obteniendo es lo siguiente:
**Marco:0 - Carpincho:1 - Pagina: 8**
Marco:1 - Carpincho:1 - Pagina: 0
Marco:2 - Carpincho:1 - Pagina: 1
Marco:3 - Carpincho:1 - Pagina: 5
Marco:4 - Carpincho:1 - Pagina: 6
Marco:5 - Carpincho:1 - Pagina: 7
Marco:6 - Carpincho:1 - Pagina: 2
**Marco:7 - Carpincho:2 - Pagina: 0**
Marco:8 - Carpincho:2 - Pagina: 1
Marco:9 - Carpincho:1 - Pagina: 3
Marco:10 - Carpincho:3 - Pagina: 0
Marco:11 - Carpincho:3 - Pagina: 1

Como se aprecia tengo diferencias en el frame 0 y 7. Ademas en el caso del frame 0 el resultado correcto se expulsa con el ultimo reemplazo.

Mi log de cargas y reemplazos es el siguiente
Marco:0 - Cargada C1P0
Marco:1 - Cargada C1P1
Marco:2 - Cargada C2P0
Marco:3 - Cargada C2P1
Marco:4 - Cargada C3P0
Marco:5 - Cargada C3P1
Marco:6 - Cargada C1P2
Marco:7 - Cargada C2P2
Marco:8 - Cargada C3P2
Marco:9 - Cargada C1P3
Marco:10 - Cargada C2P3
Marco:11 - Cargada C3P3
Marco:0 - Expulsada C1P0 en paso 3
Marco:0 - Cargada C1P4
Marco:1 - Expulsada C1P1 en paso 2
Marco:1 - Cargada C1P0
Marco:2 - Expulsada C2P0 en paso 2
Marco:2 - Cargada C1P1
Marco:3 - Expulsada C2P1 en paso 2
Marco:3 - Cargada C1P5
Marco:4 - Expulsada C3P0 en paso 2
Marco:4 - Cargada C1P6
Marco:5 - Expulsada C3P1 en paso 2
Marco:5 - Cargada C1P7
Marco:7 - Expulsada C2P2 en paso 2
Marco:7 - Cargada C2P0
Marco:8 - Expulsada C3P2 en paso 2
Marco:8 - Cargada C2P1
Marco:10 - Expulsada C2P3 en paso 2
Marco:10 - Cargada C3P0
Marco:11 - Expulsada C3P3 en paso 2
Marco:11 - Cargada C3P1
Marco:0 - Expulsada C1P4 en paso 3
Marco:0 - Cargada C1P8

Ram esta recibiendo las siguientes instrucciones:
Mate Init
Mate Mem Alloc
Mate Init
Mate Mem Alloc
Mate Init
Mate Mem Alloc
Mate Mem Alloc
Mate Mem Alloc
Mate Mem Alloc
Mate Mem Alloc
Mate Mem Alloc
Mate Mem Alloc
Mate Mem Alloc
Mate Mem Alloc
Mate Mem Alloc
Mate Mem Alloc
Mate Mem Write
Mate Mem Write
Mate Mem Write
Mate Mem Write
Mate Mem Write
Mate Mem Alloc
Mate Close
Mate Close
Mate Close

Yo creo estar siguiendo el algoritmo al pie de la letra pero no encuentro el porque de esas dos diferencias. Podrian tirarme una punta? gracias.

**Comment by iago64** [comment]
Buenas! Cómo va?

Por esas casualidades te consulto porque es algo que ya le paso a un par de grupos, están actualizando bien el puntero del clock cuando hacen los reemplazos?

Por otro lado, están corriendo el archivo PruebaMMU verdad? Porque ese puede ser otro motivo.

Saludos.-

**Comment by study64** [comment]
Hola, si estoy usando PruebaMMU. El código sacando los logs es este y por lo que entiendo estoy avanzando el puntero.

`
  list_sort(paginasCargadas, (void*)_comparadorMarco);//Esto simplemente me devuelve las pag cargadas ordenadas por el marco en el que estan
  int indice = string_equals_ignore_case(TIPO_ASIGNACION, "DINAMICA") ? indiceClockGlobal : carpinchito->indiceClock;
  if(indice >= list_size(paginasCargadas))
    indice = 0;
  int indiceOriginal = indice;
  int pasoBusqueda = 1;

  while(true) {
    pAux = (pagina_t*)list_get(paginasCargadas, indice);
    if((!pAux->accedida && !pAux->modificada) || (!pAux->accedida && pAux->modificada && pasoBusqueda > 1) ) {
      result = pAux->marco;
      guardarEnSwamp(pAux);
      indice++;
      break;
    } else if(pasoBusqueda > 1)
      pAux->accedida = false;

    indice++;
    if(indice >= list_size(paginasCargadas))
      indice = 0;
    if(indice == indiceOriginal)
      pasoBusqueda++;
				
  }


  if(string_equals_ignore_case(TIPO_ASIGNACION, "DINAMICA"))
    indiceClockGlobal = indice;
  else
    carpinchito->indiceClock = indice;`

**Comment by fedesz** [comment]
buenas, no se si estan usando algun mecanismo de lockeo de paginas, porque nosotros si y justamente nos paso lo mismo, y era q no estabamos deslockeando en un lugar y por eso nos quedaba exactamente igual que a uds. Sino, me fijaria si estan actualizando bien el bit de modificado!

**Comment by study64** [comment]
No, no estamos usando. Voy a revisar lo de modificado pero basicamente solo lo ponemos en 1 cuando hacemos mem_write sobre una direccion perteneciente a la pag.

**Comment by study64** [comment]
Listo ya lo arregle, tenia un problema en la lógica, cuando la primera y la segunda iteracion fallaba, la tarcera estaba ejecutando al mismo tiempo la lógica de 1 y 2 o en otras palabras ahora el if es así:

```
if((!pAux->accedida && !pAux->modificada) || (!pAux->accedida && pAux->modificada && (pasoBusqueda  == 2 || pasoBusqueda > 3)) )
...
```

Gracias por su ayuda.
