### ISSUE TITLE
Consulta planificador de mediano plazo

### ISSUE THREAD

**Issue by FernandoLlallire** [sisoputnfrba/foro#2534]
Buenas, tenemos unas consultas con respecto al enunciado.

> Este módulo tendrá tres planificadores distintos. Uno de largo plazo, uno de corto y uno de mediano plazo. Cada planificador correrá de manera independiente a los otros con su propio algoritmo.

Esto quiere decir que cada  planificador es un thread independiente y solo puede pasar a estado suspendido un proceso que esta en la lista de bloqueados desde la logica de este thread? 

O se puede hacer que la logica de pasar a suspendido se ejecute en el thread del carpincho cuando este tiene que pasar a bloqueado?

@gastonharari @rocioveloso

**Comment by iago64** [comment]
Buenas! Cómo va?

No dice nada de hilos, con lo cual pueden implementarlo como les resulte mas práctico, Igual tengan cuidado porque en la prueba de suspensión especificamente, la condición que hace que se suspenda un carpincho no es precisamente en el momento que se bloquea si no mas adelante.

Saludos.-

**Comment by FernandoLlallire** [comment]
Gracias por la respuesta, pero esto me genera una duda más. 
Si tengo grado multiprogramación = 1 y mientras un carpincho esté ejecutando llega uno a la cola de new no pasaría nada.
Pero si el carpincho en ejecución se bloquea por io/mate_sem_wait, estaria bien que el carpincho pase directamente a un estado de suspended blocked y no blocked? esto dejaría que el carpincho en new pase a ready

**Comment by iago64** [comment]
Buenas! Cómo va?

El caso de multiprogramación de 1 es medio borde, pero si, en ese caso tendrías que bloquearlo y al toque suspenderlo.

Saludos.-
