### ISSUE TITLE
Carpinchos perdidos al realizar muchos mate_init al mismo tiempo

### ISSUE THREAD

**Issue by Ignacio-Ferrante** [sisoputnfrba/foro#2535]
Notamos que cuando la batalla por nordelta realiza los 8 mate_init al mismo tiempo, hay veces que en el kernel no nos llegan siempre los 8 carpinchos solicitando iniciar. Cuando sucede esto, si mato la mateLib me llegan todos los carpinchos restantes. Si llegan todos los carpinchos la prueba finaliza correctamente.

Lo que hago en el kernel es tener el hilo principal constantemente esperando conexciones y cada vez que llega una, genero un socket especificamente para esa conexion y le envio el puerto correspondiente.

**Si entre medio de la creacion de los hilos de la prueba le meto un sleep(1) la prueba funciona correctamente.**
### 📝 Código relevante
En el hilo principal del kernel esta constantemente esperando carpinchos.

```
while(seguir) {
      log_info(logger, "Kernel esperando algun carpincho");
      int socket_auxiliar_carpincho = esperar_cliente(socket_kernel); // Espero a que llegue un nuevo carpincho
      
      if(socket_auxiliar_carpincho < 0) {
	      log_error(logger, "Error en el socket recibido del carpincho que se intento conectar");
	      seguir = false;
      } else {
	      log_warning(logger, "Se ha conectado un carpincho (%d)", id_proximo_carpincho);
      
	      //creo la estructura para el nuevo carpincho
	      carpincho* nuevo_carpincho = malloc(sizeof(carpincho));
      
	      nuevo_carpincho->socket_mateLib = crear_socket_carpincho(socket_auxiliar_carpincho);
	      ...
                            ...
	      agregar_new(nuevo_carpincho);
	      id_proximo_carpincho++;
	      mate_init++;
      }
} 
```
```
int crear_socket_carpincho(int socket_auxiliar_carpincho) {
	//creo un nuevo servidor en un puerto libre que asigne el SO
	int socket_aux_carpincho = crear_conexion_servidor(ip_kernel, 0, 1);

	if(!validar_socket(socket_aux_carpincho, logger)) {
		close(socket_aux_carpincho);
		log_error(logger, "Error al crear un socket para comunicacion exclusiva con el carpincho");
	} else {
		//comunico al carpincho el puerto por el cual me tiene que hablar
		t_mensaje* mensaje_out = crear_mensaje(SEND_PORT);
		agregar_a_mensaje(mensaje_out, "%d", puerto_desde_socket(socket_aux_carpincho));
		enviar_mensaje(socket_auxiliar_carpincho, mensaje_out);
		liberar_mensaje_out(mensaje_out);

		close(socket_auxiliar_carpincho);
	}
	return socket_aux_carpincho;
} 
```

y la matelib manda los mensajes que se adaptan al kernel.
### 🐛 Cómo reproducir el error
No hay una manera especifica, corro la misma prueba 10 veces y la mitad de las veces faltan carpinchos.

**Comment by iago64** [comment]
Buenas! Cómo va?

Si es algo que pasa de manera aleatoria, tiene mucha pinta de ser una condición de carrera, por las dudas probaron su tp con valgrind / helgrind para ver que no tengan ningún inconveniente de condiciones de carrera o que estén pisando variables?

Saludos.-
