### ISSUE TITLE
Duda respuesta de mensajes

### ISSUE THREAD

**Issue by danimontesano** [sisoputnfrba/foro#2537]
Hola buenas tardes. 
Tengo una breve pregunta, nosotros planteamos que a penas se libera la entrada salida es esta entrada salida la que le responde al carpincho que terminó y que puede seguir adelante en vez de esperar a pasar a execute para responderle al carpincho. Quería consultar si este error es muy grave ya que dados los tiempos a las fechas en el que estamos se nos complica bastante corregir eso. La prueba de planificacion nos da diferente por este motivo, pero los calculos se hacen bien. 

Espero su respuesta. 
Muchas gracias.

**Comment by iago64** [comment]
Buenas! Cómo va?

El problema de eso es que uds van a tener carpinchos ejecutando código cuando no deberían hacerlo y eso lamentablemente esta mal.

Saludos.-

**Comment by danimontesano** [comment]
Menos mal que recién lo pudimos solucionar entonces jaja, muchas gracias por la respuesta.
