### ISSUE TITLE
👩‍💻 ¿Buscás Grupo / Integrantes para el 1c2022? ¡Posteá ACA! 👨‍💻

### ISSUE THREAD

**Issue by RaniAgus** [sisoputnfrba/foro#2540]
¡Buenas!

Con el objetivo de unificar todos los post de búsqueda de grupos / integrantes, vamos a centralizarlos en este post.

Les recomendamos encarecidamente que traten de **NO publicar números de celular** y limitarse solo a los mails. Tengan en cuenta que el foro es público, por lo que pueden llegar a quedar en alguna lista de spam o que les hable gente que no quieran.

Saludos.-

**Comment by SiegfriedRsK** [comment]
Hola!. Nos hace falta un integrante a nuestro grupo. Si alguien se quiere sumar, me puede enviar un mail a sfamulari@frba.utn.edu.ar .
gracias!

**Comment by neverkas** [comment]
Buenas, nos faltan dos integrantes (buscamos recursantes que no aprobaron por no llegar con el tp),
ya estamos armando el entorno para el próximo tp, con los tps con los que no llegamos..

Mail de Contacto: elazarte@frba.utn.edu.ar

Saludos,

**Comment by tomasanchez** [comment]
# Queres meter Operativos? 🚀 - [OPEN]

Tenes experiencia con C?  Te interesaría trabajar sobre el modulo de FileSystem (_si es que hay_)? Te cansaste de recursar por el TP por compañeros que no terminan sus modulos? **Este cuatri lo metemos juntos!**. 

## Qué vas a hacer

Te unirás a un equipo de utnianos dedicados a meterle fuerte a la parte de programación de módulos complejos para el trabajo práctico.

Lo mejor de todo es compartir ideas, información e innovación con nuestro equipo, pudiendote establecer una buena _networking_ para futuras oportunidades laborales :construction_worker:, hackatons :computer:, game-jams :video_game:.

❗ Vamos a implementar metodologías ágiles, es importante poder estar en contacto seguido.

## Que perfiles estamos buscando :wolf:

Buscamos entusiastas de la programación con compromiso con el TP, flexible para _salirse del manual de la cátedra_. Y sobre todo: **GANAS DE APRENDER**.

### Habilidades claves 🔑 

`C` intermedio, manejo de `Punteros`, con conocimientos básicos de `git` (pull/push/branch) y familiaridad con `sockets`. Disponibilidad horaria.

No excluyente.

Es un **plus**: haber cursado DDS, conocimiento de pruebas.

##  Nosotros  ℹ️ 

Somos un equipo que estamos trabajando hace 2 años en distintas materias. Estamos promediando 3ro con algunas de 4to año. Operativos nos está bloqueando el segundo cuatri y si no la metemos no podemos cursar nada 🔨 , asi que vamos a estar a full con esta materia.

No somos LOS expertos pero consideramos tener conocimientos  sólidos en `C` como programación en general, pueden ver nuestros GitHub dónde tambien van a encontrar nuestras redes y portfolios!

Vamos a trabajar con un montón de tecnologías _piolas_ para hacer mas entretenida la cursada, **la idea es aprender**.

Si te interesa, o cualquier otra consulta mandanos un mail :mailbox: 

@tomasanchez: [tosanchez@frba.utn.edu.ar](mailto:tosanchez@frba.utn.edu.ar) 
@rnsavinelli: [rsavinelli@frba.utn.edu.ar](mailto:rsavinelli@frba.utn.edu.ar)

**Comment by joseZudaire** [comment]
Buenas, como va? Somos un grupo de 4 personas que nos conocemos del cuatri pasado (tres de un grupo y una de otro), todos recursantes. Buscamos a alguien que haya trabajado extensivamente en kernel en el 2c de 2021. Les dejo mi mail acá para que nos contacten: zudairejosefrancisco@gmail.com
Saludos!!

**Comment by FrancoP08** [comment]
Buenas, estoy buscando grupo que le falte algún integrante para sumarme. Es mi primera ves cursando la materia. Tengo una base de C por lo visto en Sintaxis en el TP. Les dejo mi email de contacto por cualquier cosa:  fpasqualino@frba.utn.edu.ar
Saludos!

**Comment by comejia** [comment]
Buenas,

Busco equipo que ya la haya cursado y quiera arrancar con todo. Cree una "base" para empezar el TP (unas utils, makefile con valgrind y cosas del tp0).

Manejo bien C, Linux, Git/Github

Cualquier cosa les dejo mi mail: cmejia@frba.utn.edu.ar

Saludos.

**Comment by NKennedy31** [comment]
> Buenas, Somos 2, estamos buscando integrantes para completar el equipo lo antes posible y empezar a adelantar lo que se pueda. Saludos

Hola lili como va? Somos dos con un compañero podemos unirnos? Mi mail es ikennedy@frba.utn.edu.ar

**Comment by ealon2** [comment]
> Buenas, Somos 2, estamos buscando integrantes para completar el equipo lo antes posible y empezar a adelantar lo que se pueda. Saludos

Hola Lili, me sumo si hay lugar. Mi email es: ezequiel.fiasche@frba.utn.edu.ar

**Comment by fakita1** [comment]
Buenas! Curso en la K3053 (Mar 18:15 a 23:00 - Sab 13:30 a 15:00).

Ando buscando meterme en un grupo en el que los integrantes sepan que van a dar lo necesario para aprobar el tp y no vayan a abandonar a mitad de la cursada, yo se que puedo aportar lo mismo.

Tengo ya casi 4 años desarrollando en Node, y un poco de experiencia en C por fuera de la facultad.

flevaggi@frba.utn.edu.ar

**Comment by ArielMichelli** [comment]
Buenas! mi nombre es Ariel, busco grupo(o mas integrantes) curso los miércoles por la noche con Adro, preferiblemente que sean recursantes. La idea seria gente muy comprometida y con ganas de apuntar a la promo. Los parciales son sencillos solo falta ponerle garra al TP.

Dejo mi Mail: Arielm-04@hotmail.com

Saludos!.

**Comment by matiferraro** [comment]
Buenas! Soy Mati, curso en K3054 los Miércoles a la noche con Adro.

Junto con una compañera (laboral/facultad) estamos buscando armar un grupo que lleve día a día el TP, metiéndole todas las ganas posibles.
Lo ideal sería formar un equipo el cual ningún integrante deje la materia durante la cursada, y que estén convencidos para aprobarla/promocionarla.
Ambos tenemos entre 3 y 5 años de experiencia desarrollando en Java y en otras tecnologías.

Dejo mi mail por si se quieren sumar!
[matiferraro@frba.utn.edu.ar](url)

Abrazo!

**Comment by ezequielmalfonso** [comment]
Hola estoy buscando grupo, estoy recursando, mi contacto ealfonso@frba.utn.edu.ar

**Comment by jlserrudo** [comment]
Buenas!! Estoy cursando en el  K3153 (Mar 18:15 a 23:00 - Sab 13:30 a 15:00). Estoy buscando grupo para poder sumarme. Les dejo ,i contacto jserrudo@frba.utn.edu.ar
Saludos cordiales

**Comment by tomasgerardi07** [comment]
Buenas! 
Estamos buscando integrantes para nuestro grupo, somos 2 con un amigo. Ambos tenemos experiencia en C, es nuestra primera vez cursando esta materia. 
Buscamos gente que no abandone a mitad del cuatrimestre, nosotros aspiramos a promocionar esta materia en conjunto, ayudandonos entre nosotros. Por mi parte es la única materia a la que le voy a dedicar tiempo este cuatrimestre, por lo que el TP es mi prioridad durante esta primera parte del año. 
Pueden contactarme por mail: tgerardi@frba.utn.edu.ar. 
Con gusto los vamos a agregar a nuestro grupo.
Saludos!!

**Comment by agussaban** [comment]
Buenas, en mi grupo nos falta sumar una persona. Buscamos a alguien que tenga compromiso y ganas de laburar.
Si alguien quiere sumarse me puede escribir a asaban@frba.utn.edu.ar.
Saludos!!

**Comment by ArielMichelli** [comment]
Buenas!!, somos un grupo de 4 personas comprometidas, si a alguno le falta grupo avísenme (Arielm-04@hotmail.com). La idea es meterle a full al TP, en lo posible gente que le ponga garra y no se baje a la mitad del cuatri.

Saludos !

**Comment by santysisi** [comment]
Buenas!! En mi grupo nos faltan 2 personas , si alguien queire unirse le dejo mi contacto ssanamrtn@frba.utn.edu.ar

**Comment by brunomassaccese** [comment]
Buenas! Estamos buscando 3 personas para completar el grupo (preferentemente que sean recursantes), con muy buena disponibilidad para dedicarle al tp durante el cuatrimestre, y que realmente tengan como prioridad esta materia. Idealmente que ya tengan claros algunos conceptos necesarios para el tp.
Pueden contactarme al mail bmassaccese@frba.utn.edu.ar

**Comment by fdimatteo-utn** [comment]
Buenas!!, estoy buscando grupo, curso en K3013 (sabados por la mañana), es la primera vez que hago la materia,tengo conocimientos de C. Mi mail es fdimatteo@frba.utn.edu.ar
Saludos

**Comment by esigma5** [comment]
Hola, somos dos con Fede, y estamos buscando grupo. Vivimos por CABA y queremos aprobar la materia, de una buena vez

**Comment by fdimatteo-utn** [comment]
> Hola, somos dos con Fede, y estamos buscando grupo. Vivimos por CABA y queremos aprobar la materia, de una buena vez

Dale fijate que cree un Grupo "Grupo N/A"

**Comment by jschuhmann47** [comment]
Buenas! Estamos buscando grupo. Actualmente somos 3 personas que tenemos las materias al día y queremos gente comprometida que esté dispuesta a meterle al TP y que no se baje. Mi mail es jschuhmann@frba.utn.edu.ar
Saludos!

**Comment by adonascimento** [comment]
Buenas!
Buscamos dos personas que se quieran sumar a nuestro grupo
Somos un grupo de tres integrantes (recursantes) con ganas de meter la materia este cuatrimestre. Ya tenemos levantado el entorno en la VM con todo listo para arrancar. Los que estén interesados me escriben a adonascimento@frba.utn.edu.ar :)

**Comment by AgustinOrlando** [comment]
Hola gente!
Somos un grupo de 4, todos comprometidos con la materia y con el TP. Estamos buscando 1 más que se quiera sumar que sepa que le va a meter a la materia y no la va a dejar. Ya le estamos metiendo desde el minuto 0, asi que buscamos a alguien con el mismo compromiso.
El que tenga ganas de aprobar el TP y la materia es bienvenido 😃 
Dejo mi mail: orlandoagustin00@gmail.com

**Comment by MaquedaPaul** [comment]
Buenas! Estamos buscando un integrante con buena predisposición para juntarse (virtualmente). Que tenga ganas de laburar y compromiso con el TP. No estamos trabajando y por tanto, le vamos a dedicar todo nuestro esfuerzo a la materia, por eso esperamos lo mismo de vos. Apuntamos a la promoción, acá tenés mi mail de contacto si vos también:
pmaqueda@frba.utn.edu.ar

**Comment by Leanz652** [comment]
Buenas! En mi grupo nos falta un integrante. 
Les dejo mi correo: lean.alvarez@live.com.ar

Saludos!

**Comment by abuergo** [comment]
Buenas! Somos un grupo de 4 recursantes con muchas ganas de liquidar la materia. Nos está faltando un integrante con buena disponibilidad, preferentemente recursante y con los conocimientos necesarios para terminar el TP cuanto antes. 

Dejo mi mail de contacto: abuergo@frba.utn.edu.ar

Saludos!

**Comment by GerrMunoz** [comment]
Buenas

Estoy buscando grupo. Curso los miercoles en la noche con Andriano. Me queda por cursar sólo esta materia de 3ro asi que le quiero meter con todo.  Mi email es: gmunoznieto@frba.utn.edu.ar

Saludos

**Comment by edinsantos-hub** [comment]
Buenas, en nuestro grupo  falta un integrante, si alguien se quiere sumar dejo mi correo : esantosasencio@frba.utn.edu.ar
Saludos !!

**Comment by AlejoCont** [comment]
Buenas, busco grupo, recursante, con ganas de meterle a full a esta materia este cuatri.
Mail: alecontestabile@frba.utn.edu.ar

**Comment by karelysr** [comment]
Buenas, en mi grupo nos faltan dos integrantes dejo mi mail: krangelsalcedo@frba.utn.edu.ar
Saludos!

**Comment by marcorodriguezmelgarejo** [comment]
Buenas, estamos buscando un último integrante para nuestro grupo, que le dedique mucho esfuerzo al tp así intentamos aprobarlo. Si a alguno le interesa dejo mi mail, mrodrguezmelgarejo@frba.utn.edu.ar
Muchas gracias.

**Comment by yairtele** [comment]
Buenas! Junto a un compañero estamos buscando grupo de TP. Ambos somos recursantes e hicimos juntos el módulo de memoria el último cuatrimestre. Queremos sacarnos de encima la materia y tenemos la experiencia que se necesita para poder enfocarse como corresponde en este trabajo. Dejo mi correo en caso sea de interés: ytelezon@frba.utn.edu.ar

Saludos!

**Comment by JuanIBorda** [comment]
Buenas, junto a un compañero estamos buscando 3 integrantes para completar nuestro grupo, somos del curso K3011 (Martes y Sábado turno mañana). Para el que se quiera sumar le dejo mi correo: jborda@frba.utn.edu.ar

**Comment by Dylanhurtado1** [comment]
Buenas, somos un grupo de 4 personas, 2 somos recursantes y estamos buscando 1 integrante que quiera dedicarle tiempo al tp, preferentemente recursante y con los conocimientos necesarios para terminar el TP. Mi mail es: dhurtado@frba.utn.edu.ar
Gracias.

**Comment by melabelen** [comment]
Hola! Tengo un grupo con otras 3 personas y nos falta 1, preferentemente que tenga tiempo para dedicarle a la materia y al tp. Mi mail es; mholweger@frba.utn.edu.ar
Saludos!

**Comment by matiasBendayan** [comment]
Hola. en nuestro grupo somos 4, buscamos a alguien con  tiempo y ganas de sacarse esta materia de encima.

mi mail es matiasbendayan@hotmail.com

**Comment by LNArrUniv** [comment]
Buenas! Estoy buscando grupo, estoy cursando los sábados a la mañana en el curso K3013 y es mi primera vez cursando la materia. Actualmente no estoy trabajando así que voy a poder dedicarle bastante tiempo a la materia. Mi mail es: larrieta@frba.utn.edu.ar

**Comment by AgusSalvidio** [comment]
Buenas!
Somos por ahora 3 que ya la cursamos anteriormente. Vamos con todo a aprobar! Buscamos integrantes preferentemente con experiencia previa.
Si tenés ganas de firmar la materia, sumate que te estamos esperando!
Dejo el correo para contacto: [asalvidio@frba.utn.edu.ar](url)

**Comment by nespada** [comment]
Holaa!
Estoy buscando grupo. Curso los sabados a la mañana. Soy recursante, no llegamos con el TP el año anterior. 
Es la unica materia que curso este cuatrimestre, y que me falta de 3ro junto con Superior, asi que disponibilidad full.

Dejo mi mail: nespada@frba.utn.edu.ar

Saludos!

**Comment by parodi1998** [comment]
Buenas,
Busco grupo, recursante, con ganas de sacarse esta materia de encima al fina. Curso sábados a la mañana.
jparodi@frba.utn.edu.ar

**Comment by NEZDIAZ** [comment]
Buenas, busco grupo, estoy solo, curso los sábados a la mañana curso K3013. Mail: ndiaz@frba.utn.edu.ar

**Comment by matiasorieta** [comment]
Buenass, estoy buscando un grupo, estoy solo. Curso los sábados a la tarde K3055. Es mi última materia de 3ro, así que tengo pensado meterle a full este cuatri. morieta@frba.utn.edu.ar

**Comment by MatiasRosales** [comment]
Buenas,
Estoy buscando grupo. Curso los sabados a la mañana K3113. Solo curso esta materia para sacarmela de encima.
Tengo experiencia armando el modulo de memoria.
Mi mail es matias.rosales97@hotmail.com

Saludos

**Comment by Matias-Balboa** [comment]
Hola, ¿Cómo están todos?, estamos buscando a nuestro ultimo integrante de grupo. Buscamos a alguien que tenga intenciones de aprobar la materia y meterle pilas al tp, nosotros somos 3 recursantes y 1 que cursa por primera vez la materia.

mail: matiasbp98@gmail.com

**Comment by JuanPabloVillarreal** [comment]
Buenas, como va? Estoy buscando grupo para hacer el TP. Curso los martes a la noche y sabados a la mañana. Mi mail es: juvillarreal@frba.utn.edu.ar

Saludos!

**Comment by AGanem** [comment]
Hola! Somos 3 estamos los lunes a la noche. Estamos buscando dos miembros para el equipo. Les dejo mi correo abdulganem@gmail.com
Saludos.

**Comment by juanff22** [comment]
Buenas, estoy buscando grupo, ya curse la materia el año anterior pero esta vez la quiero aprobar. Curso los sábados a la tarde.
Dejo mi mail: jferchero@frba.utn.edu.ar

Saludos!!

**Comment by Britanico10** [comment]
Hola, busco grupo, con ganas de aprobar la materia.
Curso los miercoles.
Mi contacto: myoo@frba.utn.edu.ar

**Comment by lgmezabal** [comment]
Buenas, somos un grupo de 3 personas, cursamos los miércoles y viernes. Estamos buscando a 2 integrantes más para el equipo
Mi mail: lgmezabal@frba.utn.edu.ar

**Comment by SantuRod** [comment]
Buenas! Se nos bajaron 2 personas del grupo, así que estamos buscando otras 2 personas con ganas de aprobar. Somos 2 recursantes y uno nuevo en el grupo.
Les dejo mi mail: sarodriguez@frba.utn.edu.ar

**Comment by Gsirota01** [comment]
Buenas, somos un grupo de 4 recursantes, nos falta un integrante que se comprometa con el tp.

Mi contacto: gabisirota@gmail.com

**Comment by EstebanQ99** [comment]
Buenas, somos un grupo de 3, cursamos sabados por la tarde. Buscamos 2 más que se sumen.

Contacto: equintana@frba.utn.edu.ar

**Comment by gutti-mg** [comment]
Buenas, somos un grupo de 4 personas y estamos buscando gente que se comprometa con el tp (preferentemente que no se baje en la mitad de la cursada). 
Mi mail es mgutierrezfilgueira@frba.utn.edu.ar
Saludos

**Comment by fcafici** [comment]
### Buscamos integrante

Buenas! Estamos buscando un último integrante que esté comprometido con la materia. Somos 4 y estamos dispuestos a meterle muchas horas al TP.

Mi mail: fcafici@frba.utn.edu.ar

**Comment by FedericoFuentesWeber** [comment]
Buenas!
Somos 4 integrantes que ya la cursamos anteriormente. Vamos con todo a aprobar! Buscamos al último integrante preferentemente con experiencia previa.

Dejo el correo para contacto: fedefuentesweber@frba.utn.edu.ar

**Comment by lucasluna068** [comment]
Buenas! 
Somos un grupo de 4 integrantes. La mayoria estamos cursando la primera vez y pretendemos rendirla correctamente este cuatrimestre. 
Correo de contacto: lucluna@frba.utn.edu.ar

**Comment by ValenAquino** [comment]
Buenas!
Estoy buscando grupo. Es la primera vez que curso la materia y la curso los sábados a la tarde. Pretendo darle la mayor atención posible tanto al tp como a la cursada.
Mail de contacto: vaquino@frba.utn.edu.ar
Saludos!!

**Comment by Nicolas50399** [comment]
Buenas, soy recursante y estoy con un compañero mas buscando grupo. Cursamos los sabados a la tarde y estamos decididos a empezar el TP lo antes posible. Quien este interesado en aprobar la materia tanto como nosotros, puede sumarse!
Contacto: naparicio@frba.utn.edu.ar

**Comment by agusdubreucq1** [comment]
buenas!
somos un grupo de 4 integrantes. estamos buscando 1 persona que se comprometa con el tp, en lo posible que sea recursante, pero sino no hay drama.
mail de contacto: adubreucq@frba.utn.edu.ar

**Comment by daltplusplus** [comment]
hola!!
somos un grupo de 4 con muchas ganas de aprobar. Buscamos un ultimo integrante.
mail: dlopeztapia@frba.utn.edu.ar

**Comment by lucasluna068** [comment]
Buenas!
Somos un grupo de 4 integrantes. La mayoria estamos cursando la primera vez y pretendemos rendirla correctamente este cuatrimestre.
Correo de contacto: lucluna@frba.utn.edu.ar

**Comment by WalterJeronimoCabrera** [comment]
Buenas, estoy buscando grupo para unirme, soy recursante y esta vez quiero aprobarla. Les dejo mí correo: jeronimo.cabrera.jc@gmail.com
Saludos.

**Comment by NearDante** [comment]
Hola busco grupo, curso los sábados por la tarde
Dejo mi mail ezequieldante96@gmail.com

**Comment by nico-abram** [comment]
Buenas, estoy buscando grupo para unirme, soy recursante y ya lo arranque al TP
Dejo mi mail abramlujan@gmail.com

**Comment by NicoIamarino** [comment]
Holas nos faltan 2 integrantes para completar el grupo. 
Dejo mi mail niamarino@frba.utn.edu.ar

Pregunta: que pasa si no completamos antes del momento del cierre?

**Comment by iago64** [comment]
Buenas! 

Respecto a tu pregunta @NicoIamarino como dice en el [post del enunciado](https://www.utnso.com.ar/1c2022-llego-kiss-a-sisop/)

> Aquell@s alumn@s que para entonces no hayan encontrado grupo serán anotados con otras personas en las mismas condiciones.

Como nota extra, vamos a tratar de que estén en el mismo curso de teoría para que al menos puedan coincidir en esos horarios.

Saludos.-

**Comment by MastroianniSebastian** [comment]
Buenas! Nos falta un integrante para completar el grupo.
Dejo mi mail smastroianni@frba.utn.edu.ar

**Comment by BrunoSam** [comment]
Hola buenas tardes se nos acaba de bajar un integrante. Alguno si está buscando grupo aún puede escribirme a bsammarco@frba.utn.edu.ar

**Comment by iago64** [comment]
Buenas! Se nos paso cerrar esto, la inscripción de grupos finalizó ayer, a partir de este momento vamos a estar ordenando los grupos incompletos y alumnos sin grupo para que todos tengan un grupo para realizar el TP.
A partir del lunes 25/04 van a estar habilitados los cambios de grupo para que puedan reorganizarse en caso de ser necesario.

Saludos.-

**Comment by esigma5** [comment]
Hola, estoy buscando grupo. Este es el issue correcto?
Soy de Villa Urquiza, y programo mucho como un esclavo.
