### ISSUE TITLE
Fallo de conexion con el cliente desde el servidor  en la Etapa 3 

### ISSUE THREAD

**Issue by EspositoLucas** [sisoputnfrba/foro#2541]
Hola , Buenas  ! Disculpen las molestias, estuve tratando de resolver el TP0 version 2.2.1 y me surgio un problema a la hora de realizar la conexion entre cliente y servidor donde al compilar server.c  me salta este error  y no se a que se debe :

![image](https://user-images.githubusercontent.com/79590470/158705118-1f3d2baf-0803-45c1-b6aa-931f3e05ac22.png)

Aunque estuve investigando varios issues con el problema similar al mio, ninguno me termino sirviendo para solucionarlo . Basandome en este issue #2000, creo que el  incoveniente viene de la mano con las configs (IP, puerto) que se manejan a la hora de iniciar la conexion entre el cliente y servidor . En base al issue, inetente cambiar los flags de ai_family  a AF_INET   pero aun asi me sigue tirando el mismo error de que el parametro es invalido y por eso falla el bind y no se a cual se refiere

Reconozco que el error tiene que ver con las configs y flags de struct addrinfo pero no se exactemente de donde viene y quisiera que me ayudasen a solucionarlo . Por las dudas, adjunto el repositorio con el codigo junto al error que tengo hecho hasta el momento para que lo revisen  . Cualquier error, me avisan . Gracias 

https://github.com/EspositoLucas/tp0

Saludos,

Lucas

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va? Gracias por pasarnos el repo con el código, nos ayuda mucho a entrar en contexto.
Creo que ya sé a qué se puede deber el error, te muestro los pasos que seguí hasta encontrarlo:

1. Por lo que veo, en la parte de los logs (que para la próxima estaría buenísimo que nos pases un copy-paste directo en vez de una captura como sugiere el template, así otros alumnos pueden encontrar el issue usando el buscador) dice lo siguiente:
```
Fallo el bind: Invalid argument
```
Ese mensaje es impreso por la función `perror()` como un error al intentar hacer `bind()` acá:
```c
	struct addrinfo hints, *servinfo, *p;

	// ...

	if(bind(socket_servidor,(void*) &servinfo,sizeof(servinfo))!= 0){
		perror("Fallo el bind");
		return 1;
	}
```

2. Si leemos en el manual de `perror()` ([link](https://man7.org/linux/man-pages/man3/perror.3.html)), en la descripción se menciona lo siguiente:
> When a system call fails, it usually returns -1 and sets the
       variable [errno](https://man7.org/linux/man-pages/man3/errno.3.html) to a value describing what went wrong.  (These
       values can be found in <errno.h>.)  Many library functions do
       likewise.  The function perror() serves to translate this error
       code into human-readable form.

Es decir que el texto `Invalid argument` es una traducción a lenguaje humano del valor de una variable global llamada `errno`, que se usa normalmente para describir el error de muchas funciones cuando retornan `-1`, entre ellas, `bind()` (cito el [manual](https://man7.org/linux/man-pages/man2/bind.2.html)):

> On success, zero is returned.  On error, -1 is returned, and
       [errno](https://man7.org/linux/man-pages/man3/errno.3.html) is set to indicate the error.

3. Si nos fijamos en la tabla de códigos de error de `errno` ([link](https://www.thegeekstuff.com/2010/10/linux-error-codes/)), veremos que `Invalid Argument` es el error `EINVAL`.

4. Entonces, volviendo al manual de `bind()`, en la sección de errores nos aparecen los posibles motivos por los que el error se produjo:

>  EINVAL The socket is already bound to an address.

>  EINVAL addrlen is wrong, or addr is not a valid address for this
              socket's domain.

Dice que los parámetros `addrlen` o `addr` de la definición de la función pueden ser inválidos:
```c
int bind(int sockfd, const struct sockaddr *addr, socklen_t addrlen);
```

Volviendo a revisar el código, veo que la variable `servinfo` está declarada como `struct addrinfo *` y se está pasando a un argumento del tipo `struct sockaddr *`, te recomiendo leer la guía de sockets linkeada en la sección de guías del blog, ahí está explicado en detalle de dónde obtener los parámetros que `bind()` necesita: https://www.utnso.com.ar/recursos/guias/

Por otra parte, el proceso sigue después del error porque la función está devolviendo un valor (`return 1;`) en vez de finalizar (por ejemplo, con `exit(1);`). Te recomiendo hacer ese cambio para evitar que ocurra.

Saludos

**Comment by EspositoLucas** [comment]
Buenas . Si, estuve fijandome la guia y el problema se debia a los parametros  invalidos (addrlen/addr)  que recebia la funcion bind . Lo pude solucionar cambiandolo a como esta en la guia de esta forma : _bind(socket_servidor,servinfo->ai_addr,servinfo->ai_addrlen )_ y no me triro error de que fallo el bind  asi  que Gracias  !

Ahora bien, cuando compilo el client y quiero enviar mensajes por consola  usando netcat,  a la hora de ejecutar el comando _nc 127.0.0.1 4444_ y escribo por ejemplo "Hola" me salta este mensaje n la consola de Eclipse : _Operacion desconocida. No quieras meter la pata_  y no entiendo a que se debe esa falla . 

Creo que la falla esta en la funcion leer_consola  porque de alguna forma no me reconoce las lineas usando la funcion readline(">  ") pero la verda que no lo se  y por eso quisiera que me digan si el error esta ahi con el tema de enviar los mensajes por consola porque si bien la conexion se realizo correctamente  porque me aparece  en eclipse que el cliente se conecto y el servidor esta listo para escuhar pero a la hora de escribir las lineas por la terminal no me las reconoce  y las considera una "operacion desconocida" .

Actualice al repo los cambios con el bind, lo demas esta igual.  Cualquier error, me avisan . Gracias

Saludos

**Comment by RaniAgus** [comment]
¡Buenas! La forma de ejecutar el client es con el boton `Run` de Eclipse, como se muestra en el video linkeado al TP0: https://www.youtube.com/watch?v=Q8wfpu38PMc

También se puede ejecutar por consola moviéndose a la carpeta client y ejecutando:
```
./Debug/client
```

`netcat` es un comando que no está relacionado con el código del client, sino que es un programa ya instalado que envía directamente el string que uno ingresa. Como estos mensajes no siguen el protocolo que espera recibir el server (o sea, no vienen con el código de operación ni el `int` que indica el tamaño del string adelante), el servidor devuelve "Operación desconocida".

¿Es posible que hayas encontrado algún tutorial deprecado en el que se use `netcat`? Si es así, porfa avisanos dónde así vemos de quitar el link y evitar confusiones. ¡Mil disculpas!

Saludos

**Comment by EspositoLucas** [comment]
Con el tema de netcat, es de un video viejo sobre Sockets (2018) que esta en el canal principal de Youtube . 

Por otro lado, sabia del comando Run en Eclipse pero por la terminal no me habia percatado de ejecutarlo como ./Debug/client, asi que Gracias por eso . El problema es que me saltan dos cosas distintas, por un lado  en Eclipse cuando ejecuto me sale : 

___[INFO] 22:37:55:248 tp0/(5894:5894): Soy un Logger
[0m[INFO] 22:37:55:248 tp0/(5894:5894): Lei el valor de la CLAVE valor

[0m>___ 


y cuando lo ejecuto en la terminal (con el comando ./Debug/client) me salta  : 

_[INFO] 22:31:14:398 tp0/(5795:5795): Soy un Logger
No se pudo leer la config_


y no entiendo por que no me puede leer la config, y eso que ademas  cuando ejecuto tambien pero en server el comando  ./Debug/server se me queda esperando pero no se envian los mensajes por el problema de la config . Cual es el problema, tengo algun error por algun lado en el codigo que no me di cuenta ? Me parecio que estaba bien o capaz no estoy ejecutando bien algun comando .  

Saludos

**Comment by RaniAgus** [comment]
¿Está actualizado el repo? Pregunto porque veo que internamente el cliente intenta cargar el archivo `./tp0.config`, pero solo veo un archivo `./cliente.config` en la carpeta `client`:
```c
	t_config* nuevo_config;

	nuevo_config = config_create("./tp0.config");
```

Usualmente el problema tiene que ver con la carpeta desde la cual se ejecuta el programa, hacer testo:
```
$ cd client
$ ./Debug/client
```
No es lo mismo que hacer esto:
```
$ cd client/Debug
$ ./client
```
Ya que, a la hora de intentar abrir el config, en el primer caso el programa lo va a buscar en la carpeta `client/cliente.config` (ya que se ejecuta desde `client`), y en la segunda lo va a ir a buscar a `client/Debug/cliente.config` (ya que se ejecuta desde `client/Debug`).

Te paso el link de un post sobre el tema de las rutas y cómo revisar cuál es la ruta desde la cual ejecuta Eclipse: https://faq.utnso.com.ar/guia-rutas

**Comment by EspositoLucas** [comment]
Buenas ! 

 No, no lo habia subido al repositorio y ya lo agregue . En cuanto al comando, es verdad  porque al ejecutarlo  como : 
$ cd client
$ ./Debug/client

ahi no me tiro el mensaje de que no reconocia el tp0.config pero aun asi no compila bien porque el mensaje que me aparece al tratar de enviar  algunos mensajes por consola es este por ejemplo  : 

[INFO] 13:17:18:294 tp0/(6931:6931): Soy un Logger
[INFO] 13:17:18:294 tp0/(6931:6931): Lei el valor de la CLAVE valor

> Hola
> Hola
Segmentation fault (core dumped)


y creo que la falla tiene que ver con la funcion leer_consola() o con el readline() al enviar el paquete pero no lo logro corregir . Tendra que ver con eso el error o con otra cosa ? En el repo ya esta actualizado a lo ultimo que hice para que lo revisen cualquier cosa

Saludos

**Comment by RaniAgus** [comment]
Es difícil saberlo a ojo, ¿probaste usar el debugger de Eclipse para ver en qué línea falla? En la etapa 4 del TP0 podrás ver una mini guía y este video linkeado: https://faq.utnso.com.ar/video-eclipse-debugging

**Comment by EspositoLucas** [comment]
Si, ahi probe utilizando el debug y encontre dos errores a medida que iba avanzando en el codigo en client.c : 

Uno es este : 

_ip	char *	0x1 <error: Cannot access memory at address 0x1>_	

Y el otro que tiene que ver con el readline en leer_consola() : 

_leido	char *	0x6d301100 <error: Cannot access memory at address 0x6d301100>_	

Despues creo que ya no me deja seguir avanzando con el debug por esos problemas  . Por que me aparecen ?

**Comment by EspositoLucas** [comment]
Hola, Buenas ! Discupen las molestias de nuevo . Estuve tratando de solucionar los errores donde en el primero ( ip char * 0x1 <error: Cannot access memory at address 0x1>) creo que el debug me marcó eso porque no estaba inicializado el ip hasta ese punto, porque después cuando me paro en la parte donde asigno el char* ip como ip =config_get_string_value(config,"IP");  no me aparece que no se puede acceder a esa direccion asi que en teoria deberia ser eso porque sino no se me ocurre otra cosa

Eso sí, para el segundo error : leido char * 0x6d301100 <error: Cannot access memory at address 0x6d301100>   no sé cuál sería el problema y el debug como que no me ayuda mucho . Por qué me lo tira ? Tiene que ver con algo de la funcion readline() ?

Saludos

**Comment by RaniAgus** [comment]
Para entrar mejor en contexto, ¿en qué línea te aparece ese error? ¿Es en la mísma línea donde se produce el segmentation fault o _mucho_ antes? Si es antes, asumo que en ambos casos se debe a que la variable aún no fue inicializada.

También, te recomiendo identificar primero en qué linea se produce el segmentation fault y ver el estado de las variables en ese momento.

**Comment by RaniAgus** [comment]
El programa se detiene porque espera a que se ingrese una línea por consola. Abajo, en la pestaña de la consola de Eclipse podés ingresar el texto y presionar enter para continuar con la ejecución.

**Comment by RaniAgus** [comment]
PD: En cuanto a las capturas, quiero aclarar que lo importante es que en el caso de que haya algún mensaje de error o un fragmento de código que necesitemos ver lo podamos tener a mano en formato texto, ya sea para poder copiarlo fácilmente o para que otro alumno encuentre el issue en el buscador.

De todas formas, si crees que es necesario hacer una captura (como en este caso) está perfecto 😄

**Comment by RaniAgus** [comment]
Correcto, el server tiene que estar levantado antes de iniciar el debugger 👍🏻

**Comment by EspositoLucas** [comment]
Disculpame, estoy escribiendo por consola como envie antes y en la terminal del server no aparecen las lineas, se me queda esperando con el mensaje : "Servidor listo para recibir a cliente" y nada mas .  Hay algo que estoy haciendo mal ?

**Comment by RaniAgus** [comment]
Para saber:
1. ¿Fuiste avanzando línea por línea hasta llegar al `send()`?
2. ¿Lograste reproducir el segmentation fault que habías mencionado más arriba?

**Comment by EspositoLucas** [comment]
Si, fui avanzando linea por linea ( con el server levantado) pero a la hora de llegar a esta parte en leer_consola() : 

_while(strcmp(leido,"") != 0) {
			leido = readline("> ");
			log_info(logger,"Lei las lineas  %s\n",strlen(leido)+1);

		}_

y escribir otras lineas despues de  leido = readline("> ");  me  aparece este mensaje :  _Can't find a source file at "/build/glibc-mUak1Y/glibc-2.23/stdio-common/vfprintf.c" 
Locate the file or edit the source lookup path to include its location._

Y no se a que se refiere y por eso creo que no me deja llegar al send que me preguntas . Cual es el problema ? 

Por las dudas mando captura tambien por si se ve mejor  : 

![image](https://user-images.githubusercontent.com/79590470/159375704-82adb15d-086d-4455-8841-dce0c5217d60.png)

Y el server lo tengo asi  : 

![image](https://user-images.githubusercontent.com/79590470/159375778-509eddf5-9b8c-4b0e-8fb9-a0b811d71eaf.png)

**Comment by RaniAgus** [comment]
No te preocupes por el error `Can't find a source file at`, se debe a que el código de la biblioteca estándar de C no se encuentra disponible para debuggear. Simplemente con hacer `Step Out` podés regresar a la función que la invocó.

Te recomiendo repasar la guía de debugging que linkeé arriba, en este minuto se encuentra explicado el error: https://youtu.be/0OhCEzVgdRA?t=490 

También lo podés encontrar en algunos issues del foro utilizando el buscador: https://github.com/sisoputnfrba/foro/issues?q=is%3Aissue+Can%27t+find+a+source+file+at

**Comment by EspositoLucas** [comment]
Hola, Buenas  . Si, ahi vi la parte del video y otros issues con el mismo error pero me genera un inconveniente a la hora de hacer step return y volver a seguir con el programa porque al ejecutar ese comando ( una vez que se creo el IO vprintf internal) me aparecen estos mensajes n la consola del Debug  : 
 
<terminated>client [C/C++ Application]	
	<terminated, exit value: 0>gdb (7.11.1)	

<terminated, exit value: 0>gdb (7.11.1)	

y no me deja avanzar en el main.c, en este caso debería dejarme seguir en conexión = crear_conexion(ip, puerto);
pero no sigue y termina .  Es un error de alguna parte del programa o estoy ejecutando mal los pasos en el debug ?

**Comment by RaniAgus** [comment]
Otra forma de evitar entrar en las funciones de la biblioteca estándar de C (como `printf`) es haciendo un `Step Over` cuando te encuentres en esa línea.

En caso de que esto no funcione y el programa siga terminando abruptamente, ¿podrías subir una captura de pantalla para complementar? El debugger Eclipse tiene muchos menús y me es difícil poder entrar en contexto.

**Comment by EspositoLucas** [comment]
Si, intente eso y aun ai termina y no me permite avanzar con el programa . 

Esto es lo queme aparece antes de hacer el Step Over (que lo mande antes) : 

![image](https://user-images.githubusercontent.com/79590470/159593584-a62ceb6d-b42e-41f4-b252-853867727b2f.png)

y esto es lo que me aparece cuando lo ejecuto y termina : 

![image](https://user-images.githubusercontent.com/79590470/159593642-a4ccabfd-db9a-4402-8f0a-84417ea7ba1f.png)

**Comment by RaniAgus** [comment]
Perdón, me expliqué mal, quise decir que la forma de salir de esta pantalla: 

![img](https://user-images.githubusercontent.com/79590470/159593584-a62ceb6d-b42e-41f4-b252-853867727b2f.png)

Es pulsando en `Step Return`:
![image](https://user-images.githubusercontent.com/39303639/159595987-1a40f10b-09eb-45d5-a1b4-68cda8a4444b.png)




Otra alternativa pata **evitar** entrar en esa pantalla es ejecutando un `Step Over` en la pantalla **anterior**. 

Por ejemplo, en este caso, en vez de usar `Step Into`, vamos a usar `Step Over`:

![image](https://user-images.githubusercontent.com/39303639/159595579-117180b7-49dc-4341-80a9-4e9313361f61.png)

Lo cual hace que el debugger salte a la siguiente línea sin errores:

![image](https://user-images.githubusercontent.com/39303639/159595670-6b051128-9b93-4ed6-8d76-a8b2b1dd0c7e.png)

**Comment by EspositoLucas** [comment]
Si, intente en ambos casos como me decís pero me sigue tirando lo mismos mensajes de que termino el programa : 

_<terminated>client [C/C++ Application]	
	<terminated, exit value: 0>gdb (7.11.1)	

<terminated, exit value: 0>gdb (7.11.1)_	

Cual es el problema ?

**Comment by RaniAgus** [comment]
¿En qué número de línea y archivo (del repo) está terminando el programa exactamente?

**Comment by EspositoLucas** [comment]
No entiendo la pregunta, te referis  al numero de linea en la funcion `terminar_programa` ? porque  en ese caso seria en la linea 137 ( del repo) en el archivo client.c pero no se si te referis a eso

**Comment by iago64** [comment]
Buenas! Cómo va?

Lo que estoy notando es que estas encontrándote con el típico problema que se da cuando uno esta haciendo `step into` en una función de las bibliotecas estándar de C, entonces el problema que te genera eso es que te tira el error de que no puede encontrar los fuentes.
En ese caso lo que tenes que hacer es como dijo Agus, hacer siempre step over y no usar step into para que no intente entrar a las funciones de las cuales no tiene los fuentes.

El que te tire un `<terminated, exit value: 0>gdb (7.11.1)` significa que la aplicación termino sin inconvenientes, en el caso del server es la ejecución de la línea `return EXIT_SUCCESS;` 

Saludos.-

**Comment by EspositoLucas** [comment]
Buenas . Si,lo intento como me comentan ( siguiendo con stepover en vez de step into) pero aun así me sigue apareciendo el mismo mensaje `<terminated, exit value: 0>gdb (7.11.1)`  . No se si se puede, pero podrían mostrarme en una imagen como seria ? porque capaz no estoy entendiendo bien como seguir con el debug  . por ejemplo, estoy en con el debug en leer_consola () , ingreso "Hola", después me pide ingresar otra linea y pongo por ejemplo "h", después se me genera el IO vprintf internal y hago step over como me decian y simepre me tira el mensaje de que termino el programa . Es así a lo que se refieren ? Disculpen que este trabado con esto, capaz es algo muy obvio que me estoy dando cuenta

**Comment by RaniAgus** [comment]
> estoy en con el debug en leer_consola () , ingreso "Hola", después me pide ingresar otra linea y pongo por ejemplo "h", después se me genera el IO vprintf internal y hago step over como me decían 

Repito una vez más para que se entienda bien:
1. En el caso de que se genere el error `Can't find a source file at ...` hay que ejecutar `Step Return` para regresar, **NO** `Step over`.
2. Otra forma de evitar aparecer en esa pantalla es que en la línea donde se invoca esa función (que no sé si es `readline` o `printf`, a eso iba mi pregunta) es hacer, ahora sí, un `Step Over` para **evitar intentar entrar** a la función.

**Comment by RaniAgus** [comment]
PD: Pregunto lo de la línea para intentar reproducir el error en mi Eclipse, porque me resulta extraño que después de hacer un `Step Return` se termine la ejecución del programa (en realidad debería saltar a la siguiente línea de la función que la ejecutó).

**Comment by EspositoLucas** [comment]
Si, intente los dos casos  tal cual me mencionas y aun así termina el programa , lo mismo cuando estoy en `readline` y hago Step Over . La verdad que ni idea por que ocurre

**Comment by RaniAgus** [comment]
¿Qué contiene exactamente la línea en la que ocurre el error?

Perdón que sea insitente, quiero saber cómo reproducirlo 😅

**Comment by RaniAgus** [comment]
Recién revisando en la captura me dí cuenta que es la línea en la que se produce el `segmentation fault` que estábamos buscando:

![image](https://user-images.githubusercontent.com/39303639/159616505-32f4068b-8812-4137-9646-98dd410e4918.png)

**Comment by EspositoLucas** [comment]
Ese `segmentation fault` es lo que produce que termine el programa y no avance ? Que debería hacer entonces sino me funcionaron los pasos que me dijeron ?

**Comment by RaniAgus** [comment]
> Ese segmentation fault es lo que produce que termine el programa y no avance ? 

Exactamente

> Que debería hacer entonces sino me funcionaron los pasos que me dijeron ?

La intención de usar el debugger es identificar en qué línea de tu código se está produciendo y recolectar toda la información posible para poder corregirlo (por ejemplo, el valor de las variables en ese momento).

Un `segmentation fault` significa que el programa está intentando acceder a una porción de memoria que no le pertenece. Los motivos por los que se producen pueden ser varios.

Entonces, basándonos en el debugger, ¿qué línea de tu código está produciendo el `segmentation fault`?

**Comment by EspositoLucas** [comment]
> Entonces, basándonos en el debugger, ¿qué línea de tu código está produciendo el segmentation fault?

Como me fijo en el debugger la linea de código donde se produce ?
porque me aparece esto : 

```
Thread #1 [client] 32734 [core: 0] (Suspended : Signal : SIGSEGV:Segmentation fault)	
	_IO_vfprintf_internal() at vfprintf.c:1.632 0xb7dfd383	
	_IO_vsnprintf() at vsnprintf.c:114 0xb7e1f3df	
	_string_append_with_format_list() at 0xb7fb6ff9	
	string_from_vformat() at 0xb7fb65e1	
	_log_write_in_level() at 0xb7fb630d	
	log_info() at 0xb7fb618e	
	leer_consola() at client.c:106 0x8048bae	
	main() at client.c:44 0x8048a72	
```
Sera en esta parte :` at vfprintf.c:1.632 0xb7dfd383  ` ?
porque en ese caso seria en la linea 163 que justo coincide en` terminar_programa()`

**Comment by RaniAgus** [comment]
El formato que muestra el stack trace es el siguiente:
```
[FUNCION]() at [ARCHIVO].c:[NRO_DE_LINEA] [DIRECCION_DE_MEMORIA]
```
En este caso, si vamos bajando entre las funciones vamos a ver que al final aparece:
```
	log_info() at 0xb7fb618e	
	leer_consola() at client.c:106 0x8048bae
```
Es decir que en la línea `106` del archivo `client.c` hay una función `leer_consola()` que está llamando a `log_info()`.

**Comment by EspositoLucas** [comment]
Claro, y llama al log_info para loggear las líneas `( log_info(logger,"Lei las líneas  %s\n",strlen(leido)+1);)` pero no entiendo si te réferis a que es ahi donde esta el error . Debería corregir algo en esa parte del bucle donde leen y loguean hasta recibir un string vacío ?

**Comment by RaniAgus** [comment]
> no entiendo si te réferis a que es ahi donde esta el error

¡Exactamente! Ahí está el error, analicemos esta línea:

```c
log_info(logger,"Lei las líneas %s\n",strlen(leido)+1);
```

- `log_info` está esperando rellenar la parte en donde hay un `%s` con un `char*`
- Pero en su primer parámetro está recibiendo el resultado de `strlen(leido) + 1`, que es un `int`.

Entonces, por ejemplo,
- Si `leido` contiene un "Hola"
- `log_info` va a intentar acceder a la memoria que se encuentra en la posición `strlen(leido) + 1` => `4 + 1` => `5`
- Y ahí es cuando se produce el `segmentation fault`, ya que no se puede acceder a la dirección `0x5`

La solución es cambiar el `%s` por el formato correcto para un `int`. Te dejo un link con una tablita que tiene todos los formatos que recibe `printf`, ya que `log_info` usa los mismos: https://www.tutorialspoint.com/c_standard_library/c_function_printf.htm

Antes de terminar, una consulta, ¿al compilar el cliente te aparece algún warning en esa línea? Pregunto porque en C los warnings suelen ser un buen indicador de estar metiendo la pata con algún tipo de dato.

**Comment by EspositoLucas** [comment]
Si ! era cambiar el formato .  Al ser un int lo cambie por `%d` y ya no me tira `segmentation fault `y me permite seguir avanzando . pero me surge un incoveninete, cuando llego con el debug a `enviar_paquete()` se me termina el programa con el mensaje : ```
<terminated>client [C/C++ Application]	
	<terminated, exit value: 0>gdb (7.11.1)	
```
, eso esta bien o deberia seguir avanzando ? Pregunto porque  a la hora de compilar el client  me genera esto por ejemplo : 

```
INFO] 13:34:25:809 tp0/(3583:3583): Soy un Logger
[0m[INFO] 13:34:25:810 tp0/(3583:3583): Lei el valor de la CLAVE valor

[0m> Hola
> hola
[INFO] 13:34:31:971 tp0/(3583:3583): Lei las lineas  5

[0m> 
```
pero en el server (levantado en la terminal) no le llegan las lineas de "hola"  . No lo tendria que ver por la terminal ? por eso me parece raro

Con el tema de los warnings, en esa linea no me salto . Por que preguntas?

**Comment by EspositoLucas** [comment]
Disculpen, creo que lo pude arreglar pero no estoy seguro . El error  aca cuando puse "pero en el server (levantado en la terminal) no le llegan las lineas de "hola" . No lo tendria que ver por la terminal ? por eso me parece raro" era porque en crear_super_paquete () no habia descomentado las lineas ( me habia olvidado jaja y por eso me habai tirado el warning que despues cambie) . Despues lo volvi a ompilar con el server ya levantado en la terminal y me sale esto : 

En client escribo esto : 

[INFO] 15:27:08:117 tp0/(5098:5098): Soy un Logger
[0m[INFO] 15:27:08:117 tp0/(5098:5098): Lei el valor de la CLAVE valor

```
[0m> Hola
> 
[INFO] 15:27:12:235 tp0/(5098:5098): Lei las lineas  1

[0m> hola
> soy
> un
> paquete
> 

```
Y en la terminal me sale : 

```
INFO] 15:26:58:179 Servidor/(5087:5087): Servidor listo para recibir al cliente
[INFO] 15:27:12:235 Servidor/(5087:5087): Se conecto un cliente!
[INFO] 15:27:12:235 Servidor/(5087:5087): Me llego el mensaje valor
[INFO] 15:27:32:242 Servidor/(5087:5087): Me llegaron los siguientes valores:

Valor: hola
[INFO] 15:27:32:242 Servidor/(5087:5087): hola
Valor: soy
[INFO] 15:27:32:242 Servidor/(5087:5087): soy
Valor: un
[INFO] 15:27:32:243 Servidor/(5087:5087): un
Valor: paquete
[INFO] 15:27:32:243 Servidor/(5087:5087): paquete
```


Eso quiere decir que se enviaron bien las lineas ?

**Comment by RaniAgus** [comment]
Correcto 🎉

**Comment by EspositoLucas** [comment]
Perfecto !  Una duda, esto era el objetivo del TP0 o tengo que hacer/corregir algo mas ? Recomiendan algo aparte ?

**Comment by EspositoLucas** [comment]
Hola, Buenas !  Disculpen pero quisiera saber si me recomiendan corregir o hacer algo mas del TP así ya puedo dar por cerrado el issue y de paso también si me recomiedan avanzar con algún tema relacionado que me sea de utilidad . 

Saludos

**Comment by EspositoLucas** [comment]
Ok, lo tendré en cuenta . Gracias por el consejo y cualquier duda que surja pregunto👍 

Doy por cerrado el issue

Saludos
