### ISSUE TITLE
tengo problemas al querer instalar las Guest Additions de VirtualBox en Lubuntu

### ISSUE THREAD

**Issue by Lara-Melany-Pallenzona** [sisoputnfrba/foro#2542]
Hola, disculpen las molestias, al querer instalar las Guest Additions me sale el siguiente cartel:

![error del guest](https://user-images.githubusercontent.com/81935387/161382580-cdf26166-d127-42a0-ba6b-1f292b49acb7.PNG)

Y de este modo no se que hacer para poder instalarlas. Quisiera saber como arreglar esto. Desde ya muchas gracias.

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va?

Antes que nada, te recomiendo leer [los lineamientos del foro](https://github.com/sisoputnfrba/foro#readme) y [el template que aparece al crear un issue sobre VirtualBox](https://raw.githubusercontent.com/sisoputnfrba/foro/master/.github/ISSUE_TEMPLATE/02-necesito-ayuda-para-configurar-las-vms-de-la-c-tedra.md) 👮🏻‍♂️. Si bien no hace falta seguir todo al pie de la letra, te puede dar una mano para entender qué información solemos pedir para entrar en contexto con el problema.

Principalmente, preferimos contar con los códigos de error en texto antes que subir capturas de pantalla porque si otro alumno en un futuro busca `VERR_PDM_MEDIA_LOCKED` en el buscador de issues no lo va a poder encontrar. 

¿Probaste de buscar ese error? Quizás otro alumno ya se encontró con el mismo problema y su solución te pueda servir 😉 https://github.com/sisoputnfrba/foro/issues?q=is%3Aissue+VERR_PDM_MEDIA_LOCKED

Saludos

**Comment by Lara-Melany-Pallenzona** [comment]
Muchas gracias por la respuesta, lo puede solucionar.  Saludos

**Comment by RaniAgus** [comment]
¡Buenísimo! Recordá que podés cerrar el issue una vez resuelta la duda. Saludos 😄
