### ISSUE TITLE
Instalacion de Guest Additions

### ISSUE THREAD

**Issue by mbuchutn** [sisoputnfrba/foro#2543]
Hola, tengo un problema con la instalacion de las guest additions en la virtual de lubuntu, la que tiene la interfaz grafica.
La maquina virtual quedo bien instalada, ahora sigo los pasos del video de youtube sin problemas pero luego de reiniciar todo sigue igual. No puedoredimensionar la pantalla.
En los mensajes de instalacion no veo algunos mensajes que si estan en el video, como los que indican la instalacion de cada biblioteca. Es posible que exista algun tema de compatibilidad? entre guest additions y la version del ubuntu?

Gracias, Saludos

### 📦 Especificaciones de la VM
- Versión de VirtualBox: 6.1.32
- Memoria RAM asignada: 4GB

Le asigne dos nucleos a la virtual
Cambie el orden de booteo, tenia al CD como primera opcion y lo cambie por Hard drive

### 🖥️ Especificaciones del host
- Sistema Operativo y versión: Windows 10
- Memoria RAM: 16GB
- Procesador: i7 8generacion

### 💻 Logs
mensajes de consola de instalacion de guest additions
utnso@ubuntu-server:/media/utnso/VBox_GAs_6.1.32$ sudo ./VBoxLinuxAdditions.run
[sudo] password for utnso: 
Verifying archive integrity... All good.
Uncompressing VirtualBox 6.1.32 Guest Additions for Linux........
VirtualBox Guest Additions installer
Removing installed version 6.1.32 of VirtualBox Guest Additions...
update-initramfs: Generating /boot/initrd.img-4.4.0-116-generic
Copying additional installer modules ...
Installing additional modules ...
VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel 
modules.  This may take a while.
VirtualBox Guest Additions: To build modules for other installed kernels, run
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup <version>
VirtualBox Guest Additions: or
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup all
VirtualBox Guest Additions: Building the modules for kernel 4.4.0-116-generic.
update-initramfs: Generating /boot/initrd.img-4.4.0-116-generic
W: mdadm: /etc/mdadm/mdadm.conf defines no arrays.
VirtualBox Guest Additions: Running kernel modules will not be replaced until 
the system is restarted
utnso@ubuntu-server:/media/utnso/VBox_GAs_6.1.32$ 

Esto es lo unico que veo en el log de la VM referido a las guest additions
00:19:27.580393 VMMDev: Guest Additions information report: Version 6.1.32 r149290 '6.1.32'
00:19:27.580486 VMMDev: Guest Additions information report: Interface = 0x00010004 osType = 0x00053000 (Linux >= 2.6, 32-bit)
00:19:27.580614 VMMDev: Guest Additions capability report: (0x0 -> 0x0) seamless: no, hostWindowMapping: no, graphics: no

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va?

¿Chequeaste de habilitar el portapapeles compartido? Tenemos un video que explica cómo hacerlo: https://www.youtube.com/watch?v=xJ52dDTfCHo

En caso de que el portapapeles compartido funcione pero la pantalla completa no, quedate tranqui porque las Guest Additions están instaladas y es un problema del controlador gráfico de la pantalla.

Podés probar cambiándolo a VBoxVGA:

![image](https://user-images.githubusercontent.com/39303639/161397734-274bd332-da09-42f6-a28d-e27cfce09f96.png)

Sino, una alternativa es aumentar la pantalla a un tamaño fijo accediendo a los ajustes del monitor:

![image](https://user-images.githubusercontent.com/39303639/161397742-b1e8602d-aade-4525-8803-9579705d75e3.png)

Saludos

**Comment by mbuchutn** [comment]
Hola Agutin, gracias por la respuesta

Me olvide de comentar que el portapapeles funcionaba. Cambiar el controlador grafico no hizo ninguna diferencia pero el ajuste del monitor si me sirvio. Asi que lo deje de tamaño fijo y quedo bien
Agrego una configuracion mas por si le pasa lo mismo a otra persona. Tambien se puede jugar con el zoom iniciando la virtual y desde el menu Ver -> Pantalla Virtual 1 -> Escalar XX%

![zoom](https://user-images.githubusercontent.com/102838012/161398526-b847e53b-1225-4105-b759-370764290027.png)


Gracias!

**Comment by RaniAgus** [comment]
¡Gracias por el aporte! 🚀
Entonces, ¿podemos dar por cerrado el issue?

**Comment by mbuchutn** [comment]
si gracias!
