### ISSUE TITLE
No puedo instalar guest additions y "the root filesystem requires a manual fsck"

### ISSUE THREAD

**Issue by melabelen** [sisoputnfrba/foro#2544]
Hola! Estoy intentando hacer el setup de la VM y me encontré con dos problemas que no sé si están relacionados o no. 
1) Al prender la VM, antes de que me aparezca el entronno gráfico me tiraba el error "the root filesystem requires a manual fsck". Al seguir los pasos que encontré en internet y correr un fsck con la ruta que me indicaba ponía exit y la maquina arrancaba, pero luego me tiraba errores de permisos denegados en pantalla.
2) Luego de desinstalar y volver a instalar varias veces, algunas me tiro ese mismo error y otras no. En las que no, intenté instalar las Guest Additions siguiendo el tutorial de yt, y me sale esto:
![MVProblem](https://user-images.githubusercontent.com/50299734/161615509-2d7ba84e-cb3d-44f2-8a61-d7c986ebe6e9.png)
Que, al cerrar sesion y volver a ingresar e intentar cambiar el tamaño de la pantalla, no es responsive, por lo que entiendo que no están siendo instaladas. 

### 🔎 Búsqueda en foros
Lo que encontré sobre fsck : https://soyadmin.com/solucion-al-error-the-root-filesystem-on-dev-sda1-needs-a-manual-fsck-initramfs-al-iniciar-ubuntu-y-linux-mint/

### 📦 Especificaciones de la VM
- Versión de VirtualBox: Version 6.1.32 r149290 (Qt5.6.2)
- Memoria RAM asignada: 3655MB

### 🖥️ Especificaciones del host
- Sistema Operativo y versión: Windows 10
- Memoria RAM: 16GB
- Procesador: Intel core i7-9750h

**Comment by iago64** [comment]
Buenas! Cómo va?

Justo el "error" que te tira cuando dice: `VirtualBox Guest Additions: Running kernel modules will not be replaced until the system is restarted`

es un viejo conocido del foro que lo podemos encontrar en algunos issues como por ejemplo #2543 o #2302 y es recurrente porque no es un error en si mismo, si no que es un aviso de que no puede cambiar cosas del kernel hasta que no se reinicie el sistema, con lo cual si reinicias la VM la misma debería levantar sin inconvenientes.

Saludos.-

**Comment by melabelen** [comment]
Joya, ahí me dejó cambiarle la resolución desde los ajustes del monitor. Mil gracias y saludos!
