### ISSUE TITLE
Problema al compartir carpetas de mi host a mi VM

### ISSUE THREAD

**Issue by Francisco1106** [sisoputnfrba/foro#2546]
### 📦 Especificaciones de la VM
- Versión de VirtualBox: 6.1
- Memoria RAM asignada: 1024MB

### 🖥️ Especificaciones del host
- Sistema Operativo y versión: ubuntu 20.04.4 LTS
- Memoria RAM: 16gb
- Procesador: amd reyzen 7
![unknown](https://user-images.githubusercontent.com/82107671/161864669-141f6796-556a-4e34-922f-b260af9a617e.png)

**Comment by mgarciaisaia** [comment]
Probá [ejecutando estos dos comandos](https://superuser.com/a/1637478) en una terminal:

```
sudo usermod -aG vboxsf $(whoami)
sudo systemctl restart vboxadd-service.service
```

(así, con el `$(` y todo)

Si eso no funciona, pasanos una captura de la ventana de propiedades de VirtualBox en que configuraste la carpeta compartida, a ver si se ve algo por ahí.

**Comment by Francisco1106** [comment]
justo lo solucione con este comando que me encontre no se ni en que pagina 
sudo adduser utnso vboxsf
esto por si a alguien le pasa lo mismo

**Comment by mgarciaisaia** [comment]
Claro, es equivalente al primer comando de esos dos que pasé. Lo que está
entre $() es un comando que se ejecuta, y su salida (el texto que
normalmente imprime en pantalla) lo reemplaza en el comando original.

En este caso, whoami muestra el nombre de la cuenta de usuario que lo
ejecuta. Por eso el resultado es el mismo.

El segundo comando reinicia el servicio de VirtualBox. Quizá no es
necesario, o quizá reiniciaste la VM en algún momento.

¡Joya que funcione!
