### ISSUE TITLE
Duda con la Etapa 3 

### ISSUE THREAD

**Issue by FrancoP08** [sisoputnfrba/foro#2547]
Estamos teniendo algunos problemas cuando queremos conectar el servidor con el cliente. 
-Uno es que hasta que el cliente no termina, en la terminal del servidor no nos aparece que se conecto, una vez finalizado recien ahi llega todo junto.
-El otro es que la funcion enviar_mensaje funciona y envia el valor al servidor, pero en la parte de agregar al paquete y enviarlo para que el servidor lo reciba y lo muestre no nos esta funcionando.
Paso la parte del codigo en donde creemos que se encuentra el error en cuestion:

```
void paquete(int conexion)
{
    // Ahora toca lo divertido!
    char* leido;
    paquete__a_enviar = crear_paquete();

    leido = readline("> ");
    // Leemos y esta vez agregamos las lineas al paquete
    while(strcmp(leido,"\0")){
            agregar_a_paquete(paquete__a_enviar,leido,sizeof(leido)+1);
            //free(leido);
            leido = readline("> ");
        }
// ¡No te olvides de liberar las líneas y el paquete antes de regresar!
    free(1);
}
```

**Comment by mesaglio** [comment]
Buenas. como va?
Para la primera pregunta, lo estas corriendo en el eclipse o en la consola?
Para la segunda, creo q puede venir por el argumento que le estan pasando a la funcion agregar_a_paquete.
Revisen la diferencia entre sizeof y strlen.

Saludos, Juani

**Comment by JuliMartinez97** [comment]
Hola, para la pregunta 2, te estaría faltando llamar a la funcion enviar_paquete(paquete, conexion), si no me equivoco, a menos que lo hagas en donde invocas a la funcion paquete, pero al menos en el codigo que subis no se ve el llamado.

Saludos, 
Julian.

**Comment by mesaglio** [comment]
@FrancoP08 quedo resuelto el tema o falto algo mas?

Saludos, Juani

**Comment by FrancoP08** [comment]
Buenas, sisi, ya lo pudimos solucionar, disculpen la demora de la respuesta. Muchas gracias!!
