### ISSUE TITLE
Eclipse se desintalo solo de un día para el otro

### ISSUE THREAD

**Issue by JuliMartinez97** [sisoputnfrba/foro#2548]
Hola!

Ayer estuve avanzando con el TP0, llegue a terminar la parte 3 y cerre la VM sin problema.

Hoy por la mañana, vuelvo a ingresar para continuar con la parte 4 y veo que el eclipse no se encuentra mas instalado (primero vi que no estaba el icono en el escritorio, pero al intentar buscarlo en el menu de acceso no lo encuentro por ningun lado, y si accedo por ejemplo al tp0, a algun archivo .c e intento poner abrir con... no me aparece tampoco!

La verdad no se que pudo haber pasado, la unica "configuracion" que toque ayer, es que le agregue a la VM el soporte del teclado en ingles.

Algun idea de que pudo haber pasado? Me recomiendan re-instalar la VM o buscar instalar eclipse de nuevo a mano? El tema de ir por esta ultima opcion, es que no se si hay algun tema de version exacta que tendria que bajar, o cualquiera me serviria?.

Adjunto una captura del menu de "Programming" donde entiendo que deberia encontrarse eclipse, y tambien de las opciones que me aparece al ir al abrir con...

![image](https://user-images.githubusercontent.com/102930746/162627574-2246e037-290c-46bc-ad74-9c8e85ecb763.png)
![image](https://user-images.githubusercontent.com/102930746/162627674-96371cbe-2d62-4619-a3cf-1b86eeee0b2a.png)

Gracias de antemano!

Saludos, 
Julián.

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va?

Eclipse se encuentra instalado en las VMs descomprimiendo un `.tar.gz`, por lo que no va a aparecer en los menús de contexto o en la lista de programas instalados, sino que se abre desde un icono en el escritorio.

Veo que en el escritorio no te aparece ninguno (ni Eclipse, ni VSCode, ni changelog.txt); probablemente al cambiar el idioma se habrá cambiado la carpeta en donde buscar el escritorio, es decir, pasaste de ver `/home/utnso/Escritorio` a ver una carpeta distinta llamada `/home/utnso/Desktop`.

Fijate si en la carpeta `/home/utnso` te quedaron repetidas las carpetas en inglés y español y, de ser así, asegurate de pasar los archivos hacia la carpeta correcta.

Saludos

**Comment by JuliMartinez97** [comment]
> ¡Buenas! ¿Cómo va?
> 
> Eclipse se encuentra instalado en las VMs descomprimiendo un `.tar.gz`, por lo que no va a aparecer en los menús de contexto o en la lista de programas instalados, sino que se abre desde un icono en el escritorio.
> 
> Veo que en el escritorio no te aparece ninguno (ni Eclipse, ni VSCode, ni changelog.txt); probablemente al cambiar el idioma se habrá cambiado la carpeta en donde buscar el escritorio, es decir, pasaste de ver `/home/utnso/Escritorio` a ver una carpeta distinta llamada `/home/utnso/Desktop`.
> 
> Fijate si en la carpeta `/home/utnso` te quedaron repetidas las carpetas en inglés y español y, de ser así, asegurate de pasar los archivos hacia la carpeta correcta.
> 
> Saludos

Buenas! Estaba viendo exactamente eso que comentas, se me duplico la carpeta de escritorio al pasar de español a ingles, y me quedo el eclipse en Escritorio, pasandolo a Desktop salio todo andando :)

Muchas gracias por la pronta respuesta, cierro el issue.

Saludos!
