### ISSUE TITLE
Permission denied para crear el archivo .log

### ISSUE THREAD

**Issue by Danymmereles** [sisoputnfrba/foro#2549]
Buenas noches,

Espero que esten teniendo un buen fin de semana. 

Estaba tratando de hacer mi tp0, la parte de los logs y en la funcion de log_create me esta diciendo que tengo los permisos denegados para poder crear o abrir el archivo .log. Estuve hablando con mis compañeras del equipo de sistemas operativos pero se traban por el mismo problema y no sabiamos que podria ser. Corroboramos que este todo bien linkeado y que tome las funciones correctamente pero aun asi no podemos solucionarlo. Mis compañeras son @nrvargas @Carla-Benitez @ailendr @MariaTrinidad 

![WhatsApp Image 2022-04-10 at 6 52 16 PM](https://user-images.githubusercontent.com/47753130/162641649-24474b87-ab8a-4df1-8ead-9d8b621b0a36.jpeg)

Estuvimos viendo los issues pero no encontramos ninguno que nos pueda ayudar. 

Desde ya muchisimas gracias

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va?

Veo que en el primer parámetro de `log_create()` están pasando `"/tp0.log"`. Todas las rutas que empiecen con `/` son rutas absolutas, lo que significa que están intentando crear un archivo en la carpeta raíz del file system (`/`) (les recomiendo leer la [guía de rutas](https://faq.utnso.com.ar/guia-rutas) para más info).

Esa carpeta no tiene permisos de escritura para un usuario común, por lo que deben elegir otra ruta (por ejemplo, pueden usar una ruta relativa: `"./tp0.log"`). 


> Un pequeño spoiler de la teoría: en la parte de File System van a ver cómo funcionan los permisos en Unix. Sabiendo eso, van a poder intepretar la primera columna que aparece al consultar con `ls -l`, por ejemplo:
> ```
> $ ls -ld /
> drwxr-xr-x 22 root root 4096 feb 22  2018 /
> ```
> En este caso, solo el usuario `root` tiene todos los permisos (`rwx`), mientras que el resto de usuarios tienen permisos para lectura y ejecución nomás (`r-x`), por lo que pueden leer su contenido pero no crear archivos ahí.

Saludos

**Comment by mesaglio** [comment]
Un comentario para agregar, ya que estamos arrancando el cuatri.
No suban imagenes a los issues, acostumbrense a subir el codigo en cuestion usando la sintaxis de Mardown.
Les dejo un link con algunos [cheatsheets](https://help.zenhub.com/support/solutions/articles/43000010354-styling-comments-with-markdown).
Saludos, Juani

**Comment by RaniAgus** [comment]
¡Buenas @Danymmereles! ¿Alguna novedad?

De paso aprovecho para escribir que el error es `Cannot create/open log file: Permission denied`, para que aparezca al buscarlo usando el [buscador de issues](https://github.com/sisoputnfrba/foro/issues?q=is%3Aissue+cannot+create%2Fopen+log+file).

**Comment by Danymmereles** [comment]
Disculpa la demora @RaniAgus. Sisi ahi pudimos, mil pero mil gracias.

**Comment by RaniAgus** [comment]
¡Genial! Una vez resuelta la duda pueden cerrar el issue 😄
