### ISSUE TITLE
Setup de VM en Apple Silicon (M1)

### ISSUE THREAD

**Issue by dlopezjoffreutn** [sisoputnfrba/foro#2550]
Buenas! Yo estoy con una M1 y me paso algo parecido a lo detallado en este issue [#2299](https://github.com/sisoputnfrba/foro/issues/2299)!

Con [UTM](https://mac.getutm.app/) pude levantar una [iso de Ubuntu con arq ARM](https://ubuntu.com/download/server/arm), setupear todo de 0 con mucha tranquilidad (salvo por detalles menores, seguí [esta instalación](https://www.youtube.com/watch?v=-XFNUeWhsIQ)) e instalar todos los paquetes listados en https://www.utnso.com.ar/recursos/maquinas-virtuales pero la instalacion de ruby falla 😞

### 💻 Logs
Con el ultimo comando `rvm install --default ruby-head` tira estos errores:

<img width="765" alt="image" src="https://user-images.githubusercontent.com/82044090/162769770-b582659a-8890-4756-8142-41c13f0739bd.png">

> Warning! Requested ruby installation which requires another ruby available - installing ruby-2 first.
> 
> TruffleRuby does not support aarch64 currently.
> TruffleRuby does not support aarch64 currently.
> 
> Checking requirements for ubuntu.
> Requirements installation successful.
>
> TruffleRuby does not support aarch64 currently.
>
> truffleruby-20.3.0 - #downloading truffleruby-20.3.0-linux-, this may take a while depending on your connection...
> truffleruby-20.3.0 - #extracting truffleruby-20.3.0-linux- to /home/utn-so/.rvm/src/truffleruby-20.3.0.....
> 
> Error running '__rvm_package_extract /home/utn-so/.rvm/archives/truffleruby-20.3.0-linux-.tar.gz /home/utn-so/.rvm/tmp/rvm_src_2134',
> please read /home/utn-so/.rvm/log/1649688702_truffleruby-20.3.0/extract.log
> 
> There has been an error while trying to extract the source. Halting the installation.
> 
> To proceed rvm requires a ruby-2 compatible ruby is installed.
> We attempted to install it automatically but it failed with status 1.
> Please install it manually (or a compatible alternative) to proceed.

Parece que no esta supporteado TruffleRuby todavia para la arquitectura de Apple Sillicon (arm64) pero yo estoy dentro de la VM, no deberia tener amd64? Me pasa lo mismo instalando el .deb file de Google Chrome y VSCode.

Si alguno conoce del tema desde ya agradezco ideas para probar cositas! Saludos, Dolores 👋

### 🔎 Búsqueda en foros
Para comando de `gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB` tuve que cambiar el server por `keyserver.ubuntu.com` segun [esta respuesta](https://askubuntu.com/questions/1372425/gpg-keyserver-receive-failed)

Sobre el support de TruffleRuby para Apple Silicon encontré [este issue](https://github.com/oracle/truffleruby/issues/2181) oficial.
Tambien antes que nada probe el mismo comando de rvm install pero agregando la flag `--auto-dotfiles` según [esta respuesta](https://stackoverflow.com/questions/27448401/ruby-version-and-rvm-out-of-sync-ruby-interpreter-version-not-changing) pero sin cambiar el comando en si.

### 📦 Especificaciones de la VM
- Versión de UTM: v.3.1.5

### 🖥️ Especificaciones del host
- Sistema Operativo y versión: macOS Monterrey (v.12.2.1), con chip M1

**Comment by mgarciaisaia** [comment]
> Parece que no esta supporteado TruffleRuby todavia para la arquitectura de Apple Sillicon (arm64) pero yo estoy dentro de la VM, no deberia tener amd64? Me pasa lo mismo instalando el .deb file de Google Chrome y VSCode.

Desde la VM, podés hacer `uname -m` en una terminal para ver qué arquitectura tiene el SO guest. Lo más probable es que sea ARM (`aarch64`, como dice por ahí). Fijate que en la página que pasaste de UTM dice:

> UTM employs Apple's Hypervisor virtualization framework to run ARM64 operating systems on Apple Silicon at near native speeds. [ ... ] In addition, lower performance emulation is available to run x86/x64 on Apple Silicon as well as ARM64 on Intel.

Es decir, ejecuta las VMs en ARM64 por defecto, pero también puede emular x86 para ejecutar una VM x86. Probablemente no sea el default (porque va a ser bastante más lento el asunto, y con más potencial de pegarle a algún bug de la emulación), y, _si ese fuera el caso_, no funciona ejecutar una imagen ARM como mencionás al principio 🙃

Es decir, si la VM es ARM, el SO tiene que ser ARM. Si la VM es x86 (via emulación), el SO tiene que ser x86. Así que podrías intentar usar la emulación de x86 para ejecutar la VM que distribuye la cátedra, o podés crear una VM ARM e instalar el SO (como relataste en este post).

Yo me inclinaría por probar el primer caso: emular x86 a ver si funciona bien. El objetivo sería optimizar la felicidad del grupo evitando potenciales problemas por tener entornos/arquitecturas diferentes (que, buen, _para eso creamos las VMs_). Si anda _muy_ mal, evaluaría otras alternativas.

**Comment by nahuemazzeo** [comment]
Hola @dlopezjoffreutn si ves que de momento estas OK por favor cerra el issue y en caso que tengas algun otro problema podes reabrirlo.

Saludos. Nahuel
