### ISSUE TITLE
Problema al abrir archivos para instalar la VM de Linux

### ISSUE THREAD

**Issue by Gdepablo** [sisoputnfrba/foro#2551]
### 📦 Especificaciones de la VM
- Versión de VirtualBox:  Oracle VM VirtualBox 6.1.32
- Memoria RAM asignada: Desconozco cómo verlo

### 🖥️ Especificaciones del host
- Sistema Operativo y versión: Windows 10 Pro 21H2
- Memoria RAM: 16 GB
- Procesador: Ryzen 5 5600 6-Core Processor 3.70 GHz

### 💻 Logs
C:\Users\guill\Downloads\ubuntu-server-5.0.1.7z.001: El archivo está dañado

**Comment by mgarciaisaia** [comment]
¡Probá bajarlo de vuelta! :)

En la página de descargas tenés el hash MD5, por si querés buscar un poco cómo verificar que el archivo descargado sea correcto.

**Comment by Gdepablo** [comment]
Buenas, perdón por eso, no leí que eran 5 partes y bueno se ve que había fallado al abrir el archivo también.
Logré hacer todo como en el video salvo que, cuando le doy a start, dice esto:

Not in a hypervisor partition (HVP=0) (VERR_NEM_NOT_AVAILABLE).</p>
AMD-V is disabled in the BIOS (or by the host OS) (VERR_SVM_DISABLED).</p>


Código resultado: | E_FAIL (0x80004005)
-- | --
Componente: | ConsoleWrap
Interfaz: | IConsole {872da645-4a9b-1727-bee2-5585105b9eed}

Supongo que es algo de la BIOS que tengo que activar, pero qué exactamente?
Saludos!

**Comment by Gdepablo** [comment]
<html><body><p><p>No se pudo insertar el disco óptico virtual <nobr><b>C:\Program Files\Oracle\VirtualBox\VBoxGuestAdditions.iso</b></nobr> en la máquina <b>Lubuntu 5.0.1</b>.</p></p><qt><p>Could not mount the media/drive <b><nobr>'C:\Program Files\Oracle\VirtualBox/VBoxGuestAdditions.iso'</nobr></b> (VERR_PDM_MEDIA_LOCKED).</p>

Código resultado: | E_FAIL (0x80004005)
-- | --
Componente: | ConsoleWrap
Interfaz: | IConsole {872da645-4a9b-1727-bee2-5585105b9eed}
Receptor: | IMachine {85632c68-b5bb-4316-a900-5eb28d3413df}

<br></body></html>

Buenas, ya activé el SVM desde la BIOS, intenté el guest addition siguiendo paso por paso lo que decía en el video, y al momento de cerrar usuario y volver a abrir me saltaron varios errores, no se por qué. Además, cuando intento repetir el proceso yendo a  Dispositivos > Insertar imagen de CD de las Guest Additions me salta eso de arriba

**Comment by Gdepablo** [comment]
![image](https://user-images.githubusercontent.com/44046974/162878014-39c1dfb9-1aac-467e-99a2-439acad4ed1f.png)
Intenté probar esto, pero no me deja tocar nada en esos apartados. O sea no puedo cambiarlo

**Comment by mgarciaisaia** [comment]
[Busque, busque](https://github.com/sisoputnfrba/foro/search?q=VERR_PDM_MEDIA_LOCKED&type=issues) :)

**Comment by Gdepablo** [comment]
De alguna forma forcé la extracción del disco de VirtualBox, y cuando le hice click a install Guest Additions de nuevo pasa esto:

<html><body><p><p>No se pudo insertar el disco óptico virtual <nobr><b>C:\Program Files\Oracle\VirtualBox\VBoxGuestAdditions.iso</b></nobr> en la máquina <b>Lubuntu 5.0.1</b>.</p></p><qt><p>Could not mount the media/drive <b><nobr>'C:\Program Files\Oracle\VirtualBox\VBoxGuestAdditions.iso'</nobr></b> (VERR_PDM_MEDIA_LOCKED).</p>

Código resultado: | E_FAIL (0x80004005)
-- | --
Componente: | ConsoleWrap
Interfaz: | IConsole {872da645-4a9b-1727-bee2-5585105b9eed}
Receptor: | IMachine {85632c68-b5bb-4316-a900-5eb28d3413df}

<br></body></html>

Me estoy volviendo loco porque con lo que había probado antes de los enlaces que me mandaste, no funcionó nada.

**Comment by RaniAgus** [comment]
¡Buenas! 

Volviendo un comentario antes:

> al momento de cerrar usuario y volver a abrir me saltaron varios errores, no se por qué

¿Llegaste a ejecutar el comando para instalar las Guest Additions?

> cuando le hice click a install Guest Additions de nuevo pasa esto: [...] VERR_PDM_MEDIA_LOCKED

¿Podrías entrar a la configuración de la VM y pasarnos una captura de la sección "Storage"? (o "Almacenamiento", en español)

![image](https://user-images.githubusercontent.com/39303639/163042986-0b653c4f-f8d5-4ca0-ad0c-0436f139eca6.png)

Saludos

**Comment by Gdepablo** [comment]
![image](https://user-images.githubusercontent.com/44046974/163093194-4c129d4d-b388-4028-8746-04b6fe06820e.png)
Lo intenté ejecutar, medio que instaló unas librerías de no se qué era, pero me parece que no era de guest additions sino algo para poder capturar el ratón (que ya lo captura normalmente)
En el video, cuando seguía los pasos y le di para instalar el GetAdditions fue que me tiró el error, si mi memoria no me falla.

**Comment by Gdepablo** [comment]
![image](https://user-images.githubusercontent.com/44046974/163093412-bb9456b7-1a20-42f1-ae6c-889a9dde929d.png)
En la barra de tareas me aparece (Por las updates que instalé mientras probaba soluciones)
![image](https://user-images.githubusercontent.com/44046974/163093448-24dcb7d8-c85f-4875-9c81-1f07f92c6e79.png)

**Comment by Gdepablo** [comment]
Capaz la solución sea downgradear el Virtual Box? Que vi que esa también es una solución. O el Lubuntu. Pero para eso creo habría que hacer la reinstalación de todo ¿no?

**Comment by iago64** [comment]
Buenas! Cómo va?

Hacer el downgrade de la versión de virtualbox puede ser lo mas fácil, dependiendo de cada situación (no logramos encontrar un patrón) tuvimos buenos resultados con la 6.0 o con la 5.2

Hacer downgrade de lubuntu lo veo mas que difícil porque ya de por si estas en una versión de ubuntu de 32 bits del año 2016 y no sería bueno ir mas atrás aun en el tiempo porque los repositorios deben estar super caídos y/o desactualizados (tenemos pendiente el update de las vms, pero la virtualidad de 2020 y 2021 nos complicó los planes)

Saludos.-

**Comment by Gdepablo** [comment]
![image](https://user-images.githubusercontent.com/44046974/163250438-40b5bf0f-5808-4dc7-9d7c-1dc808ae47e0.png)
Me apareció esto, cuando intenté runearlo.
Recuerdo que en el pasado cuando lo intenté instalar me tiró error y de ahí surgió todo el lío entonces quería saber si hay una forma de "sacar todo" e instalar todo lo referente a guest Additions de nuevo. Igualmente siguiendo un comentario fui a preferencias, ajustes del monitor para cambiarle la resolución "a manopla" 
De la misma forma se puede hacer en Ver > Pantalla Virtual 1 > Escalar a XX (100/125/150, etc)
No es el guest additions, pero supongo que sirve. Igual me parece extraño que no tenga permiso así que por eso no cierro el thread, quiero saber si eso me puede traer problemas a futuro. Porque con Root entró perfecto

**Comment by Gdepablo** [comment]
No sé bien cómo chequear el tema de que el disco se esté insertando. A mi me chirría que me diga permission denied, cuando antes me dejaba acceder lo más bien. ¿Por qué sudo, que supuestamente da privilegios de administrador, no deja entrar a la carpeta? Es raro. 
La ruta que está en el video es la que probé, sólo que yo tengo una versión más reciente de guest additions, y bueno ahí es cuando me tira lo de permission denied
Y yendo manualmente al explorador me topé con algo extraño:
![image](https://user-images.githubusercontent.com/44046974/163274988-0466e023-1e7a-41d7-9b4d-4d1e4f661fe9.png)
![VM1](https://user-images.githubusercontent.com/44046974/163275807-3ebe0b37-ff51-4e1f-8470-512a88060f0d.png)
Ahí creo que lo pude solucionar, pero estoy teniendo un tema y es que el guest additions no lo redimensiona, pero no me tiró problemas con la instalación ni nada.

**Comment by LeandroCarbajales** [comment]
Eso significa que ya están instaladas 😄, reiniciando la VM debería quedar todo ok.
Si después de reiniciar no te deja redimensionar la pantalla fijate si te sirve [este issue](https://github.com/sisoputnfrba/foro/issues/2543)

**Comment by Gdepablo** [comment]
Lo de resizear no funciona, en efecto. 
Pero lo del monitor sí.
Última pregunta, ¿hay novedades del TP0? Porque vi el TP de Operativos, el original, pero nada del TP0.
Saludos y gracias!

**Comment by LeandroCarbajales** [comment]
El TP0 está en el [primer post del cuatrimestre](https://www.utnso.com.ar/1c2022-calentando-motores/) :)
Recordá que no es obligatorio hacerlo pero es un buen punto de partida para tener una base para el TP y familiarizarse con el desarrollo

**Comment by Gdepablo** [comment]
Muchas gracias!
Bueno como esto para bien o para mal está resuelto, cierro el issue
Gracias de nuevo por toda la ayuda!
