### ISSUE TITLE
Duda Enunciado

### ISSUE THREAD

**Issue by matiasferrerovilas** [sisoputnfrba/foro#2554]
Buenas, lei el enunciado y tenia un par de dudas.

Consola:
 1. En  el modulo de consola se hace referencia a un tamaño de proceso, este se corresponde con el tamaño del archivo?. Se tiene que validar que si pongo 3B mi archivo pese 3B tambien?

Kernel:
 1. A memoria solamente le envia/comunica cuando tiene que mover a suspendido un proceso o este comportamiento tambien se lo pasa al CPU?

CPU:
 1. Todas peticiones a memoria tienen que pasar por el modulo CPU, para hacer las traduccion de direcciones logicas/fisicas y de aca enviar a memoria?
 2. A la parte de Check interrupt se llega unicamente luego de finalizar el Fetch o en cualquier momento puede ser llamado?
 3. Para traducir direcciones, uno envia a memoria la entrada de nivel 1, memoria ahi retorna la tabla de paginas de nivel 2, CPU se fija en esa tabla agarra  el valor de la tabla de pagina de nivel 2 y llama a memoria nuevamente, ahora memoria me retorna una pagina con su marco, para despues llamar nuevamente a memoria pasandole el marco y el desplazamiento y ahi me retorna le contenido. Es correcto esto?

 TLB:
 1. La TLB contiene la pagina de 1er nivel o contiene pagina nivel 1 y 2?

**Comment by LeandroCarbajales** [comment]
Buenas!
Muy buenas preguntas :)

Consola:
1- El tamaño de proceso que se le pasa por parámetro sería el espacio de memoria que se va a reservar para el mismo, en este TP las instrucciones del proceso no cuentan para ese tamaño por lo que es indiferente al archivo de pseudocódigo.

Kernel
1- Por ejemplo, para qué le comunicaría a la CPU que acaba de suspender un proceso?

CPU:
1- Claro, las instrucciones tendrán únicamente direcciones lógicas del proceso, por lo que para hacer una petición de lectura/escritura en memoria tendrá que hacer la traducción a dirección fisica.
2- La idea es que la CPU siga un ciclo de instrucción, por lo que las interrupciones se chequean al final de cada ciclo.
3- La Memoria no necesita devolver la tabla de páginas de nivel 2 en sí sino solamente su número para que luego la CPU le pueda hacer la petición similar a como hizo con la de nivel 1. Para leer en memoria necesitarías únicamente enviarle la dirección física para que pueda devolverte el contenido. El procedimiento es similar a como se ve en los ejercicios de la guía/parciales.

TLB: Contiene la traducción entera (página -> marco), sin dividir la página, por lo que es indiferente a la cantidad de niveles de paginación del sistema.

**Comment by matiasferrerovilas** [comment]
Muchas gracias!.

Con respecto al de CPU el 3. 
![imagen](https://user-images.githubusercontent.com/27780879/163266072-c5d53701-4311-40d4-9300-b071d11caf71.png)
(No se igual si esta bien hecho este diagrama de la paginacion)

Si yo recibo la direccion logica 023.
Primero voy a mi tabla de nivel 1 y  envio la posicion 0 de mi tabla, en este caso el numero 0. Ahi memoria que me devuelve? el indice 0? o toda esa mini tabla

**Comment by LeandroCarbajales** [comment]
Solamente debería devolverte el índice, no la tabla en sí, de la misma manera que cuando vas a la tabla de 2do nivel (o la única tabla de páginas si fuera paginación simple), solamente te devuelve el número de marco, no el contenido del marco en sí.

**Comment by matiasferrerovilas** [comment]
ok perfecto. Una ultima duda. Mi tabla de nivel 1, contiene el indice de la tabla de nivel 2?. o a que hace referencia dicho numero? esta tiene un marco asociado tambien?

**Comment by LeandroCarbajales** [comment]
Buenas! El formato de las tablas está ejemplificado en el enunciado, la tabla de 1er nivel está simplificada al contexto del trabajo y por eso difiere en sus columnas.
No te preocupes si no te termina de cerrar del todo aun, tené en cuenta que Memoria (y paginación) lo van a ver en detalle en las clases pasado el 1er parcial, y por cómo está diseñado el trabajo pueden desarrollar la mayor parte del resto de los módulos y tener una iteración funcional antes de tener el esquema de memoria implementado.
De cualquier manera siempre estamos abiertos a estas dudas :)

**Comment by matiasferrerovilas** [comment]
Dale muchas gracias! Por ahora no tendria mas dudas

**Comment by LeandroCarbajales** [comment]
Genial!
Si te quedaron más claras las dudas podés cerrar el issue :)
