### ISSUE TITLE
Problema al instalar las guest adittions

### ISSUE THREAD

**Issue by GianfrancoRiccelli** [sisoputnfrba/foro#2555]
Al querer instalar las guest adittions, en la consola salta un error cuando estas inician "modprobe vboxsf failed"

### 📦 Especificaciones de la VM
- Versión de VirtualBox: 5.2.44
- Memoria RAM asignada: 1720mb

### 🖥️ Especificaciones del host
- Sistema Operativo y versión: Windows 7 Professional 32-bit
- Memoria RAM: 4GB
- Procesador: Intel Pentium B980
 BIOS X55A.417
Mother: Asus X55A Series Notebook

### 💻 Logs

![image](https://user-images.githubusercontent.com/102746409/163514052-d3224359-f9f7-4da5-9375-3053be74176c.png)

**Comment by mesaglio** [comment]
Hola @GianfrancoRiccelli, revisaste [estos issues](https://github.com/sisoputnfrba/foro/issues?q=is%3Aissue+is%3Aclose+modprobe+vboxsf+failed)?

Ya que estamos aclaro, si copias el codigo de la consola como en un bloque de codigo en el issue ayuda al proxim@ que tenga el mismo problema ya que al buscarlo por nombre matchearia. En cambio si subis una imagen la busqueda no traeria resultados.

Saludos, Juani

**Comment by mesaglio** [comment]
Buenas, @GianfrancoRiccelli hubo algun update sobre este issue?

**Comment by GianfrancoRiccelli** [comment]
Reinicie la VM y se soluciono, gracias por la ayuda
