### ISSUE TITLE
Problemas con las librerias

### ISSUE THREAD

**Issue by Francisco1106** [sisoputnfrba/foro#2556]
al intentar resolver el ejercicio 2 del tp 0 no me deja iniciar ya que me saltan un error de permisos en las librerías necesarias 

### 📔 Citas del enunciado/videos

![image](https://user-images.githubusercontent.com/82107671/163682493-5b013773-ca21-489e-8663-096a25aae2ee.png)

**Comment by RaniAgus** [comment]
¡Buenas!

Antes que nada, quisiera comentar que preferimos contar con los errores de compilación en texto, para que en caso de que otro alumno tenga el mismo problema pueda buscar "Permission denied" en el buscador de issues y encontrarlo. También dejo un link a un video de cómo reportar errores en Eclipse: https://www.youtube.com/watch?v=qKkmU13uKHw

Dicho esto, sinceramente no pude reproducir el error, intenté instalar las commons o clonarme el repo del tp0 usando `sudo` de distintas formas y en ningún caso tuve un problema de permisos.

Una vez descargada e instalada la VM:
1. ¿Hiciste algún cambio en la instalación? 
2. ¿Los comandos que usaste para instalar las commons y clonarte el tp0 son los mismos que aparecen en el enunciado?
3. ¿Qué te aparece al ejecutar en una consola el comando `ls -la /usr/include/commons`?

Saludos

**Comment by Fran452** [comment]
1) nop, no realice ningún cambio seguí todo exactamente igual al video 
2) si, son exactamente los mismos. copie y pegue el codigo
3) drwxr-x---  3 root root 4096 abr  5 20:18 .
drwxr-xr-x 49 root root 4096 abr  5 20:18 ..
-rwxr-x---  1 root root 3539 abr 16 12:10 bitarray.h
drwxr-x---  2 root root 4096 abr  5 20:18 collections
-rwxr-x---  1 root root 3151 abr 16 12:10 config.h
-rwxr-x---  1 root root  934 abr 16 12:10 error.h
-rwxr-x---  1 root root 3706 abr 16 12:10 log.h
-rwxr-x---  1 root root 1384 abr 16 12:10 memory.h
-rwxr-x---  1 root root 1016 abr 16 12:10 process.h
-rwxr-x---  1 root root 7535 abr 16 12:10 string.h
-rwxr-x---  1 root root 1184 abr 16 12:10 temporal.h
-rwxr-x---  1 root root 1286 abr 16 12:10 txt.h

**Comment by Fran452** [comment]
# Linea de codigo que me sale al intentar colipar tanto cliente.c como cliente.h
## en cliente.c:
make all 
Building file: ../src/client.c
Invoking: GCC C Compiler
gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/client.d" -MT"src/client.o" -o "src/client.o" "../src/client.c"
In file included from ../src/client.c:1:0:
../src/client.h:6:24: fatal error: /usr/include/commons/log.h: Permission denied
compilation terminated.
src/subdir.mk:21: recipe for target 'src/client.o' failed
make: *** [src/client.o] Error 1

## en cliente.h

make all 
Building file: ../src/client.c
Invoking: GCC C Compiler
gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/client.d" -MT"src/client.o" -o "src/client.o" "../src/client.c"
In file included from ../src/client.c:1:0:
../src/client.h:6:24: fatal error: /usr/include/commons/log.h: Permission denied
compilation terminated.
src/subdir.mk:21: recipe for target 'src/client.o' failed
make: *** [src/client.o] Error 1

**Comment by RaniAgus** [comment]
¡Buenas! 

Viendo el output de `ls -la /usr/include/commons` noto que los permisos están un poco raros 🤔 

En la segunda parte de la materia van a ver más en detalle cómo funcionan, pero básicamente estos permisos `rwxr-x---` te están diciendo que:

- El usuario root puede leer, escribir y ejecutar (`rwx`)
- El grupo de usuarios root puede solo leer y ejecutar (`r-x`)
- Cualquier usuario fuera del grupo no tiene ningún permiso (`---`)

En mi VM tengo los permisos así: `rw-r--r--` (o sea, todos los usuarios pueden leer el archivo y solo root puede escribirlo).

Intentá volver a clonarte el repo de las commons, desinstalarlas y volverlas a instalar:
```
git clone https://github.com/sisoputnfrba/so-commons-library
cd so-commons-library
make uninstall
make debug
make install
```

Una vez reinstaladas, probá ejecutando de nuevo `ls -la /usr/include/commons`, si aparece `rw-r--r--` ya debería estar solucionado.

Saludos

**Comment by Fran452** [comment]
okey hice exactamente eso y ahora tengo lo permisos asi: utnso@ubuntu-server:~$ ls -la /usr/include/commons
total 52
drwxr-xr-x  3 root root 4096 abr 20 10:45 .
drwxr-xr-x 49 root root 4096 abr 20 10:45 ..
-rw-r--r--  1 root root 3539 abr 20 10:45 bitarray.h
drwxr-xr-x  2 root root 4096 abr 20 10:45 collections
-rw-r--r--  1 root root 3151 abr 20 10:45 config.h
-rw-r--r--  1 root root  934 abr 20 10:45 error.h
-rw-r--r--  1 root root 3706 abr 20 10:45 log.h
-rw-r--r--  1 root root 1384 abr 20 10:45 memory.h
-rw-r--r--  1 root root 1016 abr 20 10:45 process.h
-rw-r--r--  1 root root 7535 abr 20 10:45 string.h
-rw-r--r--  1 root root 1184 abr 20 10:45 temporal.h
-rw-r--r--  1 root root 1286 abr 20 10:45 txt.h

y el error que me sale al intentar ejecutar es este: 
```
10:49:08 **** Incremental Build of configuration Debug for project client ****
make all 
Building file: ../src/client.c
Invoking: GCC C Compiler
gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/client.d" -MT"src/client.o" -o "src/client.o" "../src/client.c"
../src/client.c: In function ‘main’:
../src/client.c:10:8: warning: unused variable ‘valor’ [-Wunused-variable]
  char* valor;
        ^
../src/client.c: At top level:
../src/client.c:64:2: error: unknown type name ‘s’
 }s
  ^
../src/client.c:66:9: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
 t_config* iniciar_config(void)
         ^
../src/client.c: In function ‘leer_consola’:
../src/client.c:75:8: warning: variable ‘leido’ set but not used [-Wunused-but-set-variable]
  char* leido;
        ^
../src/client.c: In function ‘paquete’:
../src/client.c:91:13: warning: unused variable ‘paquete’ [-Wunused-variable]
  t_paquete* paquete;
             ^
src/subdir.mk:21: recipe for target 'src/client.o' failed
../src/client.c:90:8: warning: unused variable ‘leido’ [-Wunused-variable]
  char* leido;
        ^
make: *** [src/client.o] Error 1
```
y no me toma los t_log*

**Comment by RaniAgus** [comment]
Fijate que te debe haber quedado una "s" sin querer en esta línea:
```
../src/client.c:64:2: error: unknown type name ‘s’
 }s
```

> y no me toma los t_log*

No entendí 🤔, ¿podrías ser más específico porfa?

**Comment by RaniAgus** [comment]
¡Ahhh! En estos casos siempre conviene probar de hacer click en "Project > C/C++ Index > Rebuild" para que Eclipse actualice las referencias del proyecto.

**Comment by Francisco1106** [comment]
geniaaal mil graciaaas
