### ISSUE TITLE
Planificador de Mediano Plazo - Responsabilidad para el cambio de Transicion

### ISSUE THREAD

**Issue by neverkas** [sisoputnfrba/foro#2557]
### Duda
Según lo visto en clase el planificador de mediano plazo es quien se encarga de suspender los procesos, pasando el PCB del proceso a la cola de SUSPENDED (pudiendo ser ready/blocked) si se requiere ya sea porque el grado de multiprogramación llegó a su tope y hay procesos con mayor prioridad que deben estar en alguna de las colas READY/BLOCKED/RUNNING

Nuestra duda es.. si no es responsabilidad de este planificador el cambio de estado, de quien es entonces para ejecutar la rutina que actualizará el estado del PCB?
Puede ser que apunta a que ésta es una operación asincrónica que se debe desligar del hilo principal que ejecuta al planificador de mediano plazo?

### 📔 Citas del enunciado/videos
> La transición entre los estados SUSPENDED-BLOCKED y SUSPENDED-READY, al ser una transición que va a darse al finalizar una entrada salida, no necesariamente forma parte del planificador de Mediano Plazo.

**Comment by LeandroCarbajales** [comment]
Buenas!
Hace alusión, a que, al igual que como se ve en clases, la transición (suspended-blocked => suspended-ready) se da al finalizar su operación de entrada-salida correspondiente y no por una decisión del planificador. El mismo caso se da en la transición (blocked => ready)

**Comment by neverkas** [comment]
Buenas profe, quedó claro, gracias

**Comment by LeandroCarbajales** [comment]
Buenísimo!
Si quedó respuesta la duda podés cerrar el issue así le queda al resto para buscarlo?
