### ISSUE TITLE
Interacción permanente entre los módulos CPU y Memoria

### ISSUE THREAD

**Issue by neverkas** [sisoputnfrba/foro#2558]
### Duda
Entendemos que al momento de iniciar el CPU establece una conexión con Memoria, y el socket que se crea será el mismo durante durante todo el ciclo de vida de ambos procesos?

### 📔 Citas del enunciado/videos
> Al iniciarse el módulo, se conectará con la Memoria y realizará un handshake inicial para recibir la configuración relevante de la misma que le permita traducir las direcciones lógicas a físicas. Esto debería incluir al menos cantidad de entradas por tabla de páginas y tamaño de página
> A la hora de hacer las peticiones a Memoria, tendrá que traducir las direcciones lógicas (propias del proceso) a direcciones físicas (propias de la memoria). Para tal efecto, simulará las operaciones de una MMU disponiendo de una TLB.

**Comment by LeandroCarbajales** [comment]
Buenas!
Así es, una vez establecida una conexión entre los procesos, pueden siempre utilizar la misma para el envío/recibo de mensajes.

**Comment by neverkas** [comment]
Buenas profe, genial gracias

**Comment by RaniAgus** [comment]
¡Buenas @neverkas! Paso a patrullar para avisar (para la próxima) que si la duda ya fue resuelta podés cerrar el issue 👮🏻‍♂️ 
Si en un futuro ven que algo no terminó de cuadrar pueden tomarse la libertad de reabrirlo o abrir uno nuevo referenciando éste. ¡Saludos!
