### ISSUE TITLE
PCB Tiempo de Bloqueo

### ISSUE THREAD

**Issue by neverkas** [sisoputnfrba/foro#2559]
### Duda
1. Con que tiempo inicia?
2. La unidad de tiempo sólo sería sólo la dada en la config?

### 📔 Citas del enunciado/videos
> Ciclo de Instrucción -> Execute -> instruccion I/O(tiempo)
> Esta instrucción representa una syscall de I/O bloqueante. Se deberá devolver el PCB actualizado al Kernel junto al tiempo de bloqueo.

### Posible Solución
Iniciar timer cuando entra el PCB a la cola de LISTA_BLOQUEADOS y comparar con
- la config de tiempo de IO (para chequear que ejecutó esa unidad de tiempo)
- la config TIEMPO_MAXIMO_BLOQUEADO para saber si hay que pasar el proceso a la cola de LISTA_SUSPENDIDOS_BLOQUEADOS

**Comment by LeandroCarbajales** [comment]
Buenas!
No me queda clara la primer pregunta, si se referie a cuál será el tiempo de cada I/O, es lo que indique la instrucción en sí, por ejemplo (I/O 5000) debería bloquear al proceso por 5 segundos, la unidad de tiempo es en milisegundos.

No me queda clara la primer solución propuesta, cuál sería la config de tiempo de IO?
La posible solución de iniciar un timer cuando se pasa el PCB a bloqueado y comparándolo con el TIEMPO_MAXIMO_BLOQUEADO me parece bien siempre que siga la lógica del enunciado, recordando que el proceso debe estar bloqueado por esa cantidad de tiempo antes de suspenderse.

**Comment by neverkas** [comment]
Buenas profe, me refería a iniciar un timer y comparar 
1. la **config de tiempo de IO** la que se muestra en la configuración que la Consola debe parsear por ej. `I/O 3000` para saber que bloqueó ese tiempo con `usleep`
2. y también el tiempo limite **TIEMPO_MAXIMO_BLOQUEADO** que aparece en la config al final del apartado del módulo de Kernel

Consultaba por si estaba bien hacer ambas comparaciones, ya que si la config indica `I/O 15000` se bloquearía por 15 segundos y además `TIEMPO_MAXIMO_BLOQUEADO=10` no podría pasarlo a la cola de  Suspendidos hasta que termine esos 15 segundos del `usleep`

**Comment by LeandroCarbajales** [comment]
Claro, mi confusión venía por lo de "config" de tiempo de IO, a efectos del trabajo práctico, podríamos decir que es una lista de "instrucciones" más que un config, ya que por ejemplo un archivo de pseudocódigo podría tener varias líneas de I/O cada una con un tiempo distinto.

A nivel implementación, está bien que compares el tiempo que estará bloqueado con el TIEMPO_MAXIMO_BLOQUEADO, no es estrictamente necesario pero de esa manera podrías saber de antemano que ese proceso no necesitaría suspenderse.

Con respecto a "...si la config indica I/O 15000 se bloquearía por 15 segundos y además TIEMPO_MAXIMO_BLOQUEADO=10 no podría pasarlo a la cola de Suspendidos hasta que termine esos 15 segundos del usleep."
- Justamente al pasar esos 10 segundos debería pasar de estado "bloqueado" a "suspendido-bloqueado", y siguiendo tu ejemplo, 5 segundos después pasaría a "suspendido-listo" ya que habrían terminado sus 15 segundos.

Queda más claro el caso?

**Comment by LeandroCarbajales** [comment]
Buenas!
Quedó resuelta la duda? Se puede cerra el issue?

**Comment by LeandroCarbajales** [comment]
Cierro el issue por inactividad, cualquier cosa lo volvés a abrir :)

**Comment by neverkas** [comment]
Buenas profe, disculpe no haber confirmado, no me acostumbré al foro.
Me quedó más claro.

Reabro el issue por una duda que considero que está asociada, si no corresponde abro otro issue.

# Cita al enunciado
> Ciclo de Instrucción -> Execute -> instruccion I/O y EXIT
>I/O(tiempo): Esta instrucción representa una syscall de I/O bloqueante. Se deberá devolver el PCB actualizado al Kernel junto al tiempo de bloqueo
>EXIT: Esta instrucción representa la syscall de finalización del proceso. Se deberá devolver el PCB actualizado al Kernel para su finalización.

# Duda
Cuando hace referencia a `PCB actualizado` para ambos casos
1. al módulo CPU sólo le corresponde modificar cuanto tiempo estuvo ejecutando el proceso en cpu? (apunto a lo mismo que se menciona en este otro incidente #2621 )
2. corresponde modificar alguna otra métrica?
3. el cambio de estado a blocked/exited  es sólo responsabilidad al kernel, no?

Una última duda, es válido dejar en kernel un único hilo que se conecte a la conexión cpu dispatch y quede escuchando, para estas interacciones por el mismo socket? ó es necesario la conexión/desconexión sólo cuando estas interacciones ocurran?
