### ISSUE TITLE
Asignación y tamaño en swap

### ISSUE THREAD

**Issue by r-cbl** [sisoputnfrba/foro#2560]
Hola, con mi grupo tenemos algunas dudas con respecto al swamp:

1. ¿Qué tamaño debería tener? Recordamos que el año pasado teníamos un tamaño definido por config y deberíamos utilizar esa información para no alojar información si no hay espacio suficiente.
2. ¿Cómo se hace la asignación de páginas a swamp? Con esto nos referimos a es una asignación fija o variable. Al momento de pasar la página de un proceso a swamp, vamos a guardar en su propio archivo swamp, pero, por ejemplo, la primera vez hacemos un malloc por el tamaño de página * cantidad máxima de marcos por proceso o simplemente por el tamaño de dicha página y cada vez que bajemos una página nueva hacemos otro malloc?
3. En relación a estas preguntas, pensábamos en añadir esta información al config pero no sabemos si tenemos permitido esto

Gracias!

**Comment by LeandroCarbajales** [comment]
Buenas!
1- Los archivos de SWAP (porfa no le digamos swamp que puede causar confusiones con el tp del cuatri pasado) debería tener cada uno el tamaño del proceso (que no varía a lo largo de la ejecución), no hay tamaño máximo definido.
2- El enunciado aclara que la memoria virtual se implementa solamente con asignación fija de marcos, esto no debería afectar al SWAP.
3- El archivo de config lo pueden expandir, qué info estaban pensando agregar por ejemplo?

**Comment by r-cbl** [comment]
1. Pero entonces, hasta qué punto puedo bajar procesos sin que se rompa? Podemos definir un límite en el sentido de un tamaño max de swap?
2. Bien. Entonces a swap pasa el proceso completo siempre, no?
3. Por ejemplo, el tamaño máximo de memoria que disponemos para archivos swap

**Comment by LeandroCarbajales** [comment]
Todos los que vayan entrando al sistema, no hay un límite o tamaño máximo de swap, por lo que no necesitarían agregar eso a su config :)
Claro, en SWAP va a estar siempre el proceso completo

**Comment by r-cbl** [comment]
Gracias
