### ISSUE TITLE
DUDA CONFIG MEMORIA

### ISSUE THREAD

**Issue by matiasferrerovilas** [sisoputnfrba/foro#2561]
Tenia una duda con la parte de config de memoria.

![imagen](https://user-images.githubusercontent.com/27780879/163731075-0f3b6c61-16f1-405b-a658-fdd3635fdc67.png)

Que diferencia habia entre estos 2 campos exactamente. y si ambos eran para las tablas de nivel 1 y 2 o algunas eran para las de nivel 2 nada mas.

**Comment by LeandroCarbajales** [comment]
Buenas!
Me parece oportuno aclarar que si algunos conceptos del módulo de Memoria no les suena es porque aun no tuvimos la clase en que se explican estos esquemas.
La config de ENTRADAS_POR_TABLA aplica a ambos niveles de tablas, esto simplifica los cálculos también para el módulo CPU, el tamaño de página es independiente de los niveles de paginación en este caso.

**Comment by LeandroCarbajales** [comment]
Buenas!
Te sirvió la respuesta?

**Comment by LeandroCarbajales** [comment]
Cierro el issue por inactividad, cualquier cosa lo volvés a abrir :)
