### ISSUE TITLE
Duda sobre la consola: Implementación de la verificación de los datos de entrada (argumentos del programa) 

### ISSUE THREAD

**Issue by sofiabarreneche** [sisoputnfrba/foro#2563]
Sobre la consola: El tamaño del proceso que se pasa por consola tiene un máximo? tiene un mínimo? Que cosas serian importantes verificar a la hora de cargar el tamaño? 

### 📔 Citas del enunciado

> La Consola deberá aceptar 2 parámetros para ser ejecutado: el path del archivo de pseudocódigo y el tamaño que tendrá el proceso. Se recomienda utilizar los parámetros argc y argv de la función main ayudándose con [esta guía](https://docs.google.com/document/d/1lgJkujN9kBlsFcYyp9aEkNvmoWVFKCajceh84R8s2KQ).

**Comment by LeandroCarbajales** [comment]
Buenas!
El tamaño en sí va a ser un valor arbitrario que representa el espacio de direcciones en Memoria (virtual) del proceso, el mismo nos va a servir para probar el esquema de memoria justamente, es independiente de la cantidad de instrucciones y no tiene una restricción de tamaño definida.
Hasta no tener el esquema de Memoria el tamaño del proceso es irrelevante, pueden usar cualquier valor (1024 x ej).
Más adelante lo tendrán que tener en cuenta para que las instrucciones no accedan a direcciones inválidas, por ejemplo no debería haber una instrucción "READ 2000" en un proceso que se le definió un tamaño de 1024, ya que la dirección 2000 no existiría.
Queda más clara la idea?

Saludos!
         Lean

**Comment by sofiabarreneche** [comment]
Si Lean muchas gracias ya quedo clarísimo!
Saludos :)
