### ISSUE TITLE
Dudas sobre Módulos Kernel y CPU

### ISSUE THREAD

**Issue by nfuentes** [sisoputnfrba/foro#2565]
Buenas noches! después de haber leído el enunciado nos surgieron las siguientes dudas sobre los módulos mencionados

**Modulo Kernel**

1. La estructura PCB únicamente debe contener la información que indica el enunciado, o se le pueden llegar a agregar campos en caso de considerar necesario?
2. El campo "Tamaño" del PCB, a que hace referencia?. Se debe enviar dicha información al módulo de memoria?
3. Cuales estados se deben tomar en cuenta para el grado de multiprogramación? si el PCB esta creado, sin importar en cual estado este, cuenta para el grado de multiprogramación?

**Modulo CPU**

1. De acuerdo a estos ítems de la etapa execute del Ciclo de instrucción:

> READ(dirección_lógica): Se deberá leer el valor de memoria correspondiente a esa dirección lógica e imprimirlo por pantalla.
WRITE(dirección_lógica, valor): Se deberá escribir en memoria el valor del segundo parámetro en la dirección lógica del primer parámetro.

Esto se debe imprimir solo en éste modulo o también se debe imprimir en el módulo Consola?

2.  De acuerdo al paso "Check Interrupt" del Ciclo de instruccion:

> En este momento, se deberá chequear si el Kernel nos envió una interrupción. De ser el caso, se devuelve el PCB actualizado al Kernel. De lo contrario se reinicia el ciclo de instrucción, avanzando en 1 el Program Counter.

No se debería actualizar el Program Counter incluso si el proceso es interrumpido por Kernel (suponiendo que las instrucciones son atómicas) ?  Así como esta redactado, puede prestar a confusión de que una instrucción que se venia ejecutando deba ser ejecutada nuevamente.

Desde ya muchas gracias!

**Comment by LeandroCarbajales** [comment]
Buenas!
Kernel--
1.- Sí, el PCB lo podrían expandir si lo necesitaran, aunque consideramos que con lo explicitado en el enunciado debería alcanzar, qué campo/s se les ocurría agregar?
2.- Aclararemos mejor el campo "tamaño" en una próxima errata, pero sí, define el espacio de direcciones de memoria (virtual) del proceso, solamente va a ser de utilidad para que el mismo no tenga inconsistencias (por ejemplo, un proceso no debería intentar leer la dirección 2000 si el proceso ocupa 1200)
3.- El concepto de "grado de multiprogramación" se ve en detalle en la clase de procesos/hilos o de planificación, hace referencia a lo mismo :)

CPU--
1.- Sí, solamente en la CPU, la consola únicamente recibiría un mensaje de finalización del proceso por parte del Kernel.
2.- Es un buen punto! Lo aclararemos mejor en la próxima errata para que de menos lugar a confusiones

**Comment by LeandroCarbajales** [comment]
Buenas!
Quedaron dudas de esto?

**Comment by LeandroCarbajales** [comment]
Cierro el issue por inactividad, cualquier cosa lo volvés a abrir :)
