### ISSUE TITLE
Dudas sobre la tabla y swap

### ISSUE THREAD

**Issue by Matias-Balboa** [sisoputnfrba/foro#2566]
Hola, ¿como están?, tenia dos dudas con respecto al modulo de memoria y swap:

1- Mi tabla de nivel 2 se supone que es una por proceso? por ejemplo:

nivel 1:
proceso 1- > tabla 1
proceso 8 -> tabla 4

nivel2:
tabla 1 -> (bit de uso: 1, marco:3....)
                (bit de uso: 1, marco:4....)
                (bit de uso: 1, marco:6....)
tabla 4 -> (bit de uso: 1, marco:10....)
                (bit de uso: 0, marco: - ....)
                

2- cuando un proceso se suspende entonces escribo en el archivo de swap correspodiente la info que se encuentra en el espacio de usuario y cambio el bit de presencia de la tabla de ese proceso?

Saludos!!!

**Comment by LeandroCarbajales** [comment]
Buenas!
La idea es que el esquema sea similar a como se verá en la clase de Memoria, asique si aun no les cierra del todo es por eso :)
Tendrían una tabla de nivel 1 y N tablas de nivel 2 por proceso.
Al suspender escribirías lo necesario en el archivo de SWAP correspondiente, tengan en cuenta también el bit de modificado :)

Espero que les sirva la respuesta.
Saludos!
         Lean

**Comment by Matias-Balboa** [comment]
Genial, muchisimas graciass!!!
