### ISSUE TITLE
Dudas PCB, estimación, TLB y tabla de primer nivel.

### ISSUE THREAD

**Issue by matiaspar2000** [sisoputnfrba/foro#2567]
1. Cuando se manda el PCB de Kernel a CPU la consigna habla como si fuera necesario enviar todo. Hay que enviarlo entero o solo las cosas que la CPU pueda llegar a modificar? Pensamos que es solo necesario mandar el PID, las instrucciones, el PC y la tabla de páginas de 1er nivel.

2. A la hora de calcular el tiempo de ejecución para luego usarlo en el SRT, habría que hacerlo del lado de Kernel desde que el proceso cambia de estado a EXEC hasta que sale o del lado de CPU desde que arranca el ciclo de instrucción hasta que es interrumpido?

3. Podemos agregar mas cosas a la estructura de PCB además de las que figuran en la consigna? (EJ: estado o última ráfaga)

4. Puede tener un proceso mas de una tabla de primer nivel?

5. Teniendo la TLB en la CPU en vez de en memoria estaría generando que tengamos que mandarle de memoria a CPU mensajes adicionales para tenerla actualizada, esta bien que sea asi o podría estar la TLB en memoria?

6. Cuando un proceso finaliza hay que avisar a Memoria para que libere la memoria o la tabla de páginas? (creemos que si pero la consigna no lo dice)

**Comment by LeandroCarbajales** [comment]
Buenas!
1- No es necesario enviar todo, conceptualmente uno lo que necesita en la CPU es el "contexto de ejecución" y no el PCB entero, a nivel implementación del TP enviando todo es más difícil equivocarse y capaz se ahorran algún que otro chequeo del lado del Kernel.
2- Conceptualmente tiene más sentido que el Kernel sea quien haga el cálculo ya que es quien replanifica, por otro lado, agregando también a tu pregunta anterior, te ahorrarías tener que enviarte también el tiempo de ejecución desde la CPU al Kernel
3- Sí, pueden expandir la estructura de PCB si les sirve para facilitar alguna cuenta o chequeo de estado.
4- No, siempre es una sola tabla de 1er nivel, por eso hay un solo "puntero" en el PCB.
5- La TLB es parte de la CPU (es una caché de la misma), y en este TP está en ese módulo para que se use de forma similar a como se ve en clases.
6- Exacto! Sino la memoria quedaría llena con procesos finalizados, lo estaremos agregando en la próxima errata (soon)

Espero que te sirvan las respuestas!
Saludos!
          Lean

**Comment by matiaspar2000** [comment]
Muchas gracias, cierro hilo.
