### ISSUE TITLE
problema a la hora de abrir la vm.

### ISSUE THREAD

**Issue by olafq** [sisoputnfrba/foro#2568]
### prbolema 
Buenas, estoy teniendo un problema a la hora de abrir la vm, cuando la abro se me queda de esta manera, y nunca arranca. Este problema lo empezó cuando quise crear una carpeta compartida, siguiendo el instructivo que proporciona la catedra, cuando reinicie la vm empezó a pasar, este problema.

### 🔎 Búsqueda en foros
 https://askubuntu.com/questions/685946/how-to-exit-emergency-mode-and-boot-to-default-mode probe con los comando que me dice acá pero sigo sin lograrlo.

### 💻 Logs
```Welcome to emergency mode! After logging in,type "journalctl -xb" to view
system logs, "systemctl reboot" to reboot, "systemctl default" or ^D
to try again to boot into default mode.
Give root password for maintainence
(or type control-D to continue):``
```

**Comment by iago64** [comment]
Buenas! Cómo va?

Aunque no lo parezca nos falta una banda de info. Instalaste previamente las guest adittions de virtual box? 
Cuando ajustaste el archivo /etc/fstab, te aseguraste de no modificar nada de lo que estaba previamente no?

Saludos.-

**Comment by MaquedaPaul** [comment]
Hola! soy del mismo grupo que Olaf y me pasó exactamente lo mismo, y en mi caso no modifiqué nada de lo que estaba previamente. Además es totalmente asintómatico, recientemente me andaba perfectamente, apagué la máquina virtual (sin guardar el estado), varias veces y andaba bien.
Una vez se me tildó (se puso la pantalla negra), la reinicié forzadamente y me tiró el mismo error que Olaf.
Para solucionarlo modifiqué /etc/fstab/ desde la terminal que sale en emergency mode tal cual dice en este foro de ubuntu: https://askubuntu.com/questions/960790/stuck-in-emergency-mode-and-nothing-works

Tuve que remontar la carpeta compartida. Sospecho que este error tiene que ver con la versión de virtual box. Me gustaría que se me confirme si esta es la razón porque es bastante molesto modificar desde la terminal de emergency mode (no se actualiza en tiempo real y tengo que intentar cerrar virtualbox y cancelar para que lo haga) asi me cambio de versión o hago instalaciones pertinentes.
Estoy al pendiente, saludos.

**Comment by RaniAgus** [comment]
Hoy vimos el problema en el sábado de soporte. Renombramos la carpeta del host a `shared`, seguimos la guía montando esa carpeta con la VM encendida y funcionó.

Vamos a revisar la redacción de la guía para que quede bien aclarado cuáles son los parámetros que dependen del nombre de la carpeta en el host y cuáles son de la carpeta en el guest.

Porfa avisen si todos pudieron configurar correctamente la shared folder así damos por cerrado el issue.

Saludos

**Comment by iago64** [comment]
Cerramos el issue por inactividad, cualquier nueva duda o inconveniente relacionado lo pueden reabrir o crear uno nuevo con referencia a este issue.

Saludos.-
