### ISSUE TITLE
Windows 11 KB5012643 update rompe la VM | Kernel panic

### ISSUE THREAD

**Issue by fakita1** [sisoputnfrba/foro#2570]
Buenas! Quisiera aportar que luego de la actualización KB5012643 la VM deja de funcionar dando el error kernel panic - not syncing

Solucionado desinstalando la update de windows. Realizo el aporte para poder ayudar a cualquiera que tenga el mismo error luego de la update.

![Error](https://user-images.githubusercontent.com/50811499/164134539-10cba870-0479-4c14-be29-c0ccb83a909c.jpeg)

**Comment by mesaglio** [comment]
Buenisimo muchas gracias por la información!

**Comment by fakita1** [comment]
Segunda solución (para no tener que tener desactivadas las updates durante todo el cuatrimestre): darle más de un core de CPU y maxear la memoria de video (límite 128MB).

`Give the VM a second CPU core. Then max out the graphics RAM option in the VM settings (max will be 128MB). Then install the extension pack.`

https://forums.virtualbox.org/viewtopic.php?f=6&t=105926
