### ISSUE TITLE
Duda con el ejercicio de Archivos de Configuración

### ISSUE THREAD

**Issue by Francisco1106** [sisoputnfrba/foro#2571]
# Problema
cuando quiero convocar al config no me lo toma. entra directo en el if que indica que es null por lo tanto nunca llego a recibir esos valores

### 📔 Citas del enunciado/videos

# Enunciado
Estaría bueno loggear un valor que no sea un literal en el código, por lo que vamos a leer el valor de un archivo de configuración y lo vamos a loggear usando nuestro logger.
Para ello vamos a usar [las config de las commons](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/config.h). Usando el link, creemos una config sobre el archivo "tp0.config" y obtengamos el valor de la key CLAVE, en formato string.
### 💭 Soluciones posibles

```
# Codigo
int main(void)
{
	/*---------------------------------------------------PARTE 2-------------------------------------------------------------*/

	int conexion;
	char* ip;
	char* puerto;
	//char* valor;

	t_log* logger;
	t_config* config;

	/* ---------------- LOGGING ---------------- */

	logger = iniciar_logger();
	log_info(logger,"Soy un log 44");
	// Usando el logger creado previamente
	// Escribi: "Hola! Soy un log"
	log_destroy(logger);

	/* ---------------- ARCHIVOS DE CONFIGURACION ---------------- */

	config = iniciar_config();
	ip = config_get_string_value(config,"IP");
	printf("su puerto IP es: %s",ip);
}

t_config* iniciar_config(void)
{
	t_config* config = config_create('../cliente.config');
	if(config == NULL){
		printf("\n no se pudo leer el config");
		exit(2);
	}
	return config;
}
```
## y el archivo se encuentra en esta ubicación:  
![image](https://user-images.githubusercontent.com/82107671/164260830-9193ce2c-499d-4baf-b6d2-ddbdc3e25fb6.png)
## resultado por consola
```
[INFO] 12:00:42:274 TP0/(9191:9191): Soy un log 44
[0m
 no se pudo leer el config
```

**Comment by Francisco1106** [comment]
hola buenas, ahi lo lei y configure todo y aun asi no se en que le erro: 
```
t_config* iniciar_config(void)
{
	t_config* config = config_create('./cliente.config');
	if(config == NULL){
		printf("\n no se pudo leer el config");
		exit(2);
	}
	return config;
}

```
![image](https://user-images.githubusercontent.com/82107671/164468513-45c5897c-29d0-4172-bf01-4bc00ef7aa7c.png)

**Comment by RaniAgus** [comment]
¡Buenas! Creo que el problema puede estar en esta línea:
```c
t_config* config = config_create('./cliente.config');
```

Recordá que en C los strings se escriben únicamente con comillas dobles, ya que las comillas simples están reservadas únicamente para representar un único `char`.

Un consejo: si bien el código compila, recomiendo estar al tanto de los **warnings** que aparezcan, ya que suelen ser un indicador de haberse equivocado con los tipos:

```log
src/main.c: In function ‘iniciar_config’:
src/main.c:8:42: warning: character constant too long for its type
    8 |         t_config* config = config_create('./cliente.config');
      |                                          ^~~~~~~~~~~~~~~~~~
src/main.c:8:42: warning: passing argument 1 of ‘config_create’ makes pointer from integer without a cast [-Wint-conversion]
    8 |         t_config* config = config_create('./cliente.config');
      |                                          ^~~~~~~~~~~~~~~~~~
      |                                          |
      |                                          int
In file included from src/main.c:4:
/usr/include/commons/config.h:33:39: note: expected ‘char *’ but argument is of type ‘int’
   33 |         t_config *config_create(char *path);
      |                                 ~~~~~~^~~~
```

¡Saludos!

**Comment by Fran452** [comment]
Mil gracias estuve no se cuanto tiempo y nunca se me hubiera ocurrido eso, muchos saludos.
