### ISSUE TITLE
Dudas generales y sobre conexion entre consola y kernel

### ISSUE THREAD

**Issue by Salacas** [sisoputnfrba/foro#2572]
Buenas! Tengo un par de dudas generales:
1) Con respecto a los archivos que se leen como configs e instrucciones, ¿debo suponer que estos no poseen errores? Como por ejemplo que una instrucción no respete el formato determinado en la consigna
2) ¿Es obligatorio el salir de la ejecución de un modulo con un número de error que determine el motivo de la salida? ¿O es algo que podemos opcionalmente usar para debuggearlo?

Además una duda sobre la conexion entre el kernel y la consola:
3) ¿El kernel tiene que avisarle a la consola si el proceso generado por esta fue exitoso o tuvo un error? ¿O simplemente le avisa que terminó de ejecutarse? ¿O en realidad nunca puede llegar a pasar que un proceso no pueda continuar su ejecución por un error?

Muchas gracias, un saludo

**Comment by LeandroCarbajales** [comment]
Buenas!
1- No, no es necesario chequear errores de formato, la idea es que las instrucciones del archivo sean consistentes con la ejecución del TP y que tengan sentido conceptual de la materia, por ejemplo, la última siempre será un "EXIT".
2- La idea es que no explote ningún módulo :), de cualquier manera, y aplica para lo anterior también, pueden chequear estas cosas si les sirve para ahorrarse tiempo de debug.
3- Solamente le avisará cuando su proceso finalice, la idea es que todos finalicen exitosamente.

Espero que sirvan las respuestas :)
Saludos!
         Lean
