### ISSUE TITLE
Duda sobre duracion de instrucciones para calculo de rafagas de CPU

### ISSUE THREAD

**Issue by nico-abram** [sisoputnfrba/foro#2573]
Buenas noches! Leyendo el enunciado me surgieron 2 dudas con respecto a como se define la ejecucion de las instrucciones:

1) Todas las instrucciones estarian definidas como que tienen una duracion 1 ciclo de CPU en EXEC, mas alla del tiempo real que tarden en ejecutar? O alguna (Por ejemplo NOP, que tiene un retardo por archivo de config) se define como que pasa mas de 1 ciclo de CPU en estado EXEC?

2) De ser ese el caso, se puede calcular en el modulo KERNEL la duracion de la ultima rafaga de un proceso que devuelve el modulo CPU como la diferencia entre el pc del PCB que tenia el KERNEL y el PC del PCB que devuelve la CPU (Ya que no hay instrucciones de salto)?

**Comment by LeandroCarbajales** [comment]
Buenas!
La idea es que el tiempo de ejecución lo midan desde que el PCB se pone en EXEC hasta que vuelve y no por la cantidad de ciclos, ya que dependiendo la instrucción cada ciclo podría tardar una cantidad de tiempo diferente, sobretodo cuando se ejecuten instrucciones que interactúen con memoria. Por eso para lo que es probar el algoritmo SRT lo más predecible es solamente usar (no_op, io y exit)

Queda más clara la idea?
Saludos!
            Lean

**Comment by nico-abram** [comment]
Gracias Lean, me queda un poco mas claro. Entonces la rafaga de CPU la medimos en tiempo real (milisegundos, por ejemplo), y no en ciclos de CPU?

La ESTIMACION_INICIAL del config, en que unidades de tiempo estaria? Para usar las mismas unidades cuando se haga la aproximacion del SRT.

Aparte, me surgio una consulta sobre el modulo de memoria: El algoritmo de reemplazo, lo aplicariamos usando paginas, pero cuando haya que hacer un reemplazo se swapean todos los marcos del proceso, correcto? Pregunto porque me parece un poco extraño, porque capaz un proceso tiene asignados marcos que no usa y a pesar de estar activo se swapea entero, y no se si capaz habria que aplicar el algoritmo a nivel de todo un proceso (Osea, con la tabla de paginas de primer nivel en memoria que es una por proceso) y aplicar los flags a ese nivel.

**Comment by LeandroCarbajales** [comment]
Exacto! Sería en tiempo real.
La ESTIMACION_INICIAL de la config es en milisegundos, lo agregaremos en la próxima errata para que quede más claro :)

Con respecto a memoria, el reemplazo es como se ve en los ejercicios en clase, cuando hay que traer una página que no está presente y no hay marcos libres, se reemplaza por una de las que sí están presentes.

Saludos!
         Lean

**Comment by nico-abram** [comment]
Gracias!
