### ISSUE TITLE
Error al usar struct de addrinfo

### ISSUE THREAD

**Issue by napetruzzi** [sisoputnfrba/foro#2574]
Buenas! Estaba queriendo hacer la conexión de la consola con el kernel. Lo quise implementar como la relacion cliente-servidor del tp0, pero me sale un error con las struct de addrinfo.
Específicamente me tira `incomplete type is not allowed`

En google encontré alguien con el mismo error que me tiraba, pero la solución que planteaban (ir a `.vscode/c_cpp_properties.json` cambiar`"intelliSenseMode"` a `"${default}`") no me soluciono nada
Acá dejo donde lo vi, https://github.com/Microsoft/vscode-cpptools/issues/2025

Este es el codigo en cuestion, me tira el error en hints, luego en server_info me tira un `pointer to incomplete class type is not allowed`, pero asumo que es por el mismo motivo que el otro me falla

     struct addrinfo *server_info;
	struct addrinfo hints;

	memset(&hints, 0, sizeof(hints));
	hints.ai_family = AF_UNSPEC; 
	hints.ai_socktype = SOCK_STREAM;
	hints.ai_flags = AI_PASSIVE;

        int socket_cliente = socket(server_info->ai_family,
	                    server_info->ai_socktype,
	                    server_info->ai_protocol);

No estoy seguro de como replicarlo, porque hasta en un punto copie toda la carpeta de client del tp0 y la volqué en otro proyecto(para ver si había hecho algo mal), y me pasa la mismo, compila todo menos esto.

Desde ya, muchas gracias!

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va? 
Si hay un error en la compilación, cualquier cambio en la configuración de VSCode no va a tener ningún efecto, ya que el IDE y el compilador (`gdb`) funcionan por separado.

El error `incomplete type is not allowed` se debe a que no se encontró la definición de ese tipo de dato, normalmente porque falta hacer un `#include` de la biblioteca que tiene esa definición.

¿En el archivo `utils.h` del TP0 están todos los `#include` que necesita `getaddrinfo()`? Te dejo el link al manual de la función, en la sección de "Synopsis" aparecen todos los `#include`s que se pueden llegar a necesitar: [getaddrinfo(3) — Linux manual page](https://man7.org/linux/man-pages/man3/getaddrinfo.3.html).

Saludos

**Comment by napetruzzi** [comment]
Buenas! 
Ya lo pude solucionar.
Estaban todos los includes, tuve que irme a `.vscode/c_cpp_properties.json` y poner en ` "defines": [],` de Linux `"_GNU_SOURCE"` , de forma que me quedo así:
```
           //CODIGO ARRIBA
         "defines": [
                "_GNU_SOURCE"
            ],
         //CODIGO ABAJO
```
Que básicamente era lo que me decía que haga el enlace que mande antes, pero no lo supe interpretar bien.

Ahora, tengo otra duda respecto al tema, ¿por que me sucedió esto al crear un nuevo archivo? , aunque la verdad pregunta seria ¿Por qué el TP0 que pullie del repo no me dio este problema, pero cualquier copia que hiciera de este, (y cualquier nuevo archivo que crease/pullease sin correlacion al TP0) me diera el mismo error?

Saludos!

**Comment by RaniAgus** [comment]
¡Buenas! Solamente he visto que sea necesario definir `_GNU_SOURCE` para acceder a otras funciones más específicas (como `fallocate()` en este issue #2089), pero en ningún caso vi que surgiera la necesidad de agregarlo para acceder a las funciones de `getaddrinfo()`.

¿Estás usando las VMs provistas por la cátedra? ¿Con qué herramienta estás compilando el proyecto desde VSCode?

Saludos

**Comment by napetruzzi** [comment]
Buenas! 
Estoy utilizando las VMs de la cátedra, y el proyecto lo estoy compilando con gcc desde la terminal de VSCode.

Un par de info extra que quizás ayude a diagnosticar el problema:
En eclipse me pasaba lo mismo(no se como resolverlo aun)
No hice sudo upgrade ni update ni nada por el estilo
A un compañero de grupo le paso lo mismo en su propia versión de Linux, la cual es de 64bits ( ahora no recuerdo exactamente la distro)
La versión de mi Virtualbox es 5.2.4
Mi SO es Windows 10

Aunque me gustaría saber porque pasa esto, para que no vuelva a pasar, creo que podríamos dejar por cerrado el issue. Aunque esa decisión se la dejo a ustedes!

Saludos!

**Comment by RaniAgus** [comment]
Para solucionarlo en Eclipse pueden probar de hacer el `#define` desde el código como en el otro issue:

```c
#define _GNU_SOURCE
```

igual si considerás que la duda fue resuelta podés cerrar el issue, tranqui 😅

**Comment by napetruzzi** [comment]
Excelente, gracias!
