### ISSUE TITLE
Instrucciones del archivo de pseudocódigo

### ISSUE THREAD

**Issue by DamianArielLerner** [sisoputnfrba/foro#2575]
Hola que tal, si el archivo de pseudocódigo contiene esto: 
NO_OP 5
I/O 3000
READ 0
WRITE 4 42
COPY 0 4
EXIT
Entonces las instrucciones que debo recibir en el kernel serian las siguientes?
NO_OP
NO_OP
NO_OP
NO_OP
NO_OP
I/O 3000
READ 0
WRITE 4 42
COPY 0 4
EXIT
Gracias!

**Comment by DamianArielLerner** [comment]
Lean, otra pregunta si es posible, las instrucciones es mas comodo que las guardemos como estructuras en ves de char* como hicimos en el tp0? Para diferenciar la cantidad de parametros entre cada instruccion por ejemplo. Gracias!

**Comment by LeandroCarbajales** [comment]
Por supuesto!
Al momento de parsear pueden transformarlas a una estructura que luego les facilite la lectura del lado de la CPU, por ejemplo (char, uint32_t[2])

**Comment by LeandroCarbajales** [comment]
Buenas!
Quedó resuelta la duda? Se puede cerra el issue?

**Comment by DamianArielLerner** [comment]
Ahí está, me había olvidado!
