### ISSUE TITLE
Modulo Consola - Tamaño del proceso.

### ISSUE THREAD

**Issue by matiastito** [sisoputnfrba/foro#2577]
Buenas! Los molestamos porque no nos quedó claro como está definido el tamaño del proceso; cómo lo calculamos?

### 📔 Citas del enunciado/videos

Enunciado:

> Para poder instanciar una consola, la misma recibirá por parámetro:
> El tamaño que tendrá el proceso

Muchas gracias!!!!

**Comment by LeandroCarbajales** [comment]
Buenas!
El mismo será un valor arbitrario, no hay nada que calcular :), está respondido en estos issues de hace unos días: #2563 y #2554

Queda más clara la idea?
Saludos!
       Lean

**Comment by matiastito** [comment]
Si, muchas gracias!!!
