### ISSUE TITLE
Threads Kernel

### ISSUE THREAD

**Issue by matiastito** [sisoputnfrba/foro#2578]
Buenas tardes, perdón por molestar.
Tenemos una duda en cuanto a los threads que levanta el Kernel.

Entedemos que por cada conexión de la consola tiene que levantar uno.
Ahora bien, nosotros vamos a tener un límite de procesos las preguntas son:

1. Que pasa cuando alcanzamos ese 'n', ¿rechazamos la conexión?.
2. En cuanto a la creación de hilos, nosotros tenemos algó así:
```
while(1) {
	int cliente_fd = esperar_cliente(server_fd);
	pthread_t hiloCliente;
	pthread_create(&hiloCliente, NULL, (void*)atenderCliente, (int*)cliente_fd);
	pthread_detach(hiloCliente);
}
```
¿Hay que hacer algún tipo de Join?
3. ¿ El kernel ejecuta indefindamente?¿Hasta cuando?¿Quien mata el proceso kernel? La pregunta anterior está relacionada a que nosotros caundo levantamos uns cosola nace un muere luego de hablar con el kernel y obviomante, enteindo, finalizar la ejecución del pseuocódigo. ¿es así esto?

Eso por ahora, muchas gracias!!!

**Comment by LeandroCarbajales** [comment]
Buenas!
Solamente para aclarar, no es estrictamente necesario que levantes un hilo por cada consola que se conecta, podrías también guardarte su socket en alguna estructura para luego poder enviarle el mensaje de finalización, pero eso ya depende de la implementación de cada grupo :)
En cuanto al límite de procesos, si te referís al "grado de multiprogramación", no deberían rechazar ninguna conexión, pueden crear todos los PCBs de consolas que se vayan conectando, sí lo tienen que tener en cuenta antes de pasar esos PCBs a "READY".
La función pthread_join() es para bloquearse hasta que termine el hilo pasado por parámetro, por lo que veo en tu código que asumo es el hilo principal, siempre va a estar esperando conexiones entrantes, por lo que no podría pasar que termine antes que los otros hilos que fue creando.
Sí, el Kernel, así como el resto de los módulos principales (CPU y Memoria) quedan levantados indefinidamente (hasta que los matemos manualmente). Como bien decís las consolas sí terminan al recibir respuesta del Kernel

Saludos!
        Lean

**Comment by matiastito** [comment]
Hola Lean,
Supongo que con esto:
> Solamente para aclarar, no es estrictamente necesario que levantes un hilo por cada consola que se conecta, podrías también guardarte su socket en alguna estructura para luego poder enviarle el mensaje de finalización, pero eso ya depende de la implementación de cada grupo :)

Te referìs a famoso 'SELECT', que la verdad no vimos.
Honestamente, se me está complicando bastante porque son muchos temas que no vimos.

Gracias

**Comment by RaniAgus** [comment]
¡Buenas!

> Te referìs a famoso 'SELECT', que la verdad no vimos.

Nono, está perfecto crear un hilo para atender cada Consola (de hecho, en el enunciado les pedimos que el módulo Kernel atienda consolas de forma multihilo). 

A lo que se refería Lean es que no hace falta mantener ese hilo vivo durante toda la ejecución de la Consola hasta que llegue el EXIT, sino que pueden guardarse el socket en una estructura e írselo "pasando" entre hilos (asociándolo a la idea de hilo productor-consumidor que ven en la teoría). 

Entonces podés tener otro hilo que se encargue de interactuar con la CPU y, si el proceso tiene que pasar a EXIT, informarle al módulo Consola, usando el socket que te guardaste.

**Comment by matiastito** [comment]
Muchas gracias!!!
