### ISSUE TITLE
Consola, envio de instrucciones

### ISSUE THREAD

**Issue by matiastito** [sisoputnfrba/foro#2579]
Buenas tardes profes,

De nuevo molestando con otra duda.
Es en cuanto a la comunicacion Cosola--->Kernel.

Què recomiedan?:

1. Crean un paquete grande con todo el progrmama y mardalo, de esa manera el header del paquete serìa del tipo paquete (como el tp0) y dentro del payload mandamos todo el string de instrucciones.
2. Que cada instruccion sea un header diferente, y el payload serìa el valor. de este modo harìamos un Send() por instrucciòn, eso està bien? que pasa con el orden de los paquetes? puede llegar primero la segunda instrucciòn por ejemplo? quien me asegura el orden?

Muchas gracias!

**Comment by LeandroCarbajales** [comment]
Buenas!
A efectos del Kernel que es quien recibe el/los paquetes, es indistinto si desde la consola hacen un solo send() grande o muchos send() chiquitos, lo del orden es una muy buena pregunta, escapa un poco a los temas de la materia pero como se envía por protocolo TCP/IP (tanto local como cuando lo prueben con distintas máquinas), el orden está garantizado.
Mi recomendación sería que lo piensen por el lado de "cómo quiero recibirlo?" en vez de cómo conviene enviarlo.

Saludos!
        Lean

**Comment by matiastito** [comment]
Gracias lean, el tema es ue ví el video de multiplecación y dice que si envias un send, por ejemplo, uno por cada instrucción del pseudocódigo, nada te asegura que van a llegar en orden. ¿esto es así?.
TCP lo que te asegura es que el send atómico llega OK. ¿Puede ser?

Gracias

**Comment by LeandroCarbajales** [comment]
Buenas!
Más allá de lo de TCP que es más de redes que otra cosa, está bueno no depender del orden de llegada, por eso siempre decimos de hacer un solo send() con un paquete serializado y mi recomendación también es esa :)

**Comment by matiastito** [comment]
Muchas gracias !!!
