### ISSUE TITLE
Duda algoritmo planificacion memoria

### ISSUE THREAD

**Issue by matiasBendayan** [sisoputnfrba/foro#2580]
hola, no estaría entendiendo sobre que aplica el algoritmo de reemplazo de paginas, es sobre una tabla de segundo nivel especifica o sobre todas en general? y si se reemplazan todos los marcos relacionados con el proceso o si se va reemplazando marco por marco de una pagina.

**Comment by LeandroCarbajales** [comment]
Buenas!
El procedimiento de reemplazo de páginas se ve en la clase de memoria, es similar a los ejercicios de la guía de memoria virtual :)
El reemplazo es página por página, y como aclara el enunciado, el scope será siempre local al proceso.

Saludos!
          Lean

**Comment by LeandroCarbajales** [comment]
Buenas!
Te sirvió la respuesta para aclarar la duda?

**Comment by iago64** [comment]
Buenas! Ante la falta de respuesta asumimos que la duda fue resuelta, cualquier cosa lo pueden reabrir.
Saludos.-
