### ISSUE TITLE
Direccion de memoria en instruccion

### ISSUE THREAD

**Issue by Salacas** [sisoputnfrba/foro#2581]
Buenas, estoy medio confundido con la direccion de memoria que se pasa como argumento en las instrucciones READ, COPY y WRITE.
¿A qué parte de la dirección lógica corresponde ese parámetro? Pregunto porque antes de la ejecución del proceso no se sabe cual será la entrada de tabla de 1er nivel ni el de segundo nivel. ¿Es el desplazamiento?

Muchas gracias, un saludo

**Comment by LeandroCarbajales** [comment]
Buenas!
Es la dirección lógica entera :). Tendrán que hacer los cálculos necesarios y/o los pedidos necesarios a memoria para ir haciendo la traducción hasta llegar a la dirección física.

Queda más clara la idea?
Saludos!
       Lean

**Comment by Salacas** [comment]
Sigo confundido. La dirección logica contiene, entre otras cosas, la entrada de la tabla de 1er nivel. Esta entrada se le asigna a un proceso recien cuando entra a la cola de ready. Entonces no entiendo como se indica una dirección lógica en las instrucciones sin saber qué entrada de 1er nivel se le asignó al proceso correspondiente

**Comment by LeandroCarbajales** [comment]
Buenas!
Para aclarar, lo que se le asigna al proceso cuando entra a ready es el número de tabla en sí (básicamente, cuál es su tabla de 1er nivel). Esto hace alusión a lo que en clases se ve en el PCB como "puntero a tabla de páginas".
La dirección lógica en sí no "contiene" la entrada de tabla de 1er nivel (y de 2do), la dirección en si la idea es que simplemente sea un número entre [0, tamaño-1], pero esta dirección se divide en la CPU de cierta forma para poder traducirla a dirección física.
El proceso en sí es muy similar a como se ve en los ejercicios de las clases donde normalmente se hace en binario, diviendo la dirección según la cantidad de bits que tomemos para tamaño de página y entradas de tablas, podemos calcular la entrada de tabla correspondiente y el desplazamiento dentro de la página. En el TP la diferencia es que lo haríamos en decimal, para lo que incluímos las cuentas en el enunciado.
Por ejemplo, la dirección lógica "0" siempre va a ser (entrada 1er nivel 0, entrada 2do nivel 0, desplazamiento 0), teniendo en cuenta la cantidad de entradas por tabla y el tamaño de página siempre se pueden calcular estas 3 "partes".

Si alguna cosa de memoria no termina de cerrar solamente leyendo el enunciado es normal, la clase de memoria es recién la posterior al primer parcial.
De cualquier manera, espero que te pueda sacar las dudas :)

**Comment by Salacas** [comment]
Ahora entendí por donde viene la mano. Muchas gracias!
