### ISSUE TITLE
Consulta tamaño de procesos/direcciones validas para programa

### ISSUE THREAD

**Issue by nico-abram** [sisoputnfrba/foro#2582]
Buenas noches

Mi consulta es sobre el tamaño de proceso: Podemos asumir que las direcciones que usen los programas van a ser siempre entre [0,tamaño-1] ? Es decir, las direcciones logicas van a estar siempre dentro de un bloque contiguo en la direccion 0 del tamaño del proceso?

Tengo entendido que el espacio de direcciones que podrian soportar los procesos segun el config seria de tamaño `ENTRADAS_POR_TABLA*ENTRADAS_POR_TABLA*TAM_PAGINA` (Cantidad de entradas pag 1er nivel * cant entradas pag 2do nivel * tamaño de cada entrada/pagina). Por ejemplo para los datos del config de ejemplo del enunciado seria 
4*4\*64=1024 . Ese valor por lo general me imagino que va a ser mayor al tamaño de los distintos procesos. La pregunta la hago porque por ejemplo podria haber un proceso que solo use las direcciones [64,127] y tenga tamaño 64. Habria que soportar programas de ese tipo? Es decir, tener algun mapeo entre direcciones logicas al archivo de swap (El archivo de swap tendria que ser de tamaño, 64, pero se accede a por ejemplo la direccion 68 y hay que mapear eso a los bytes 4-7 del archivo, y asi con cada pagina del proceso)

**Comment by LeandroCarbajales** [comment]
Buenas!
Claro! La idea es que las instrucciones solamente accedan a direcciones lógicas entre 0 y (tamaño-1) para que sea consistente con el archivo de SWAP :)

Saludos!
         Lean

**Comment by nico-abram** [comment]
Gracias por la respuesta, cierro el issue.

Saludos!
