### ISSUE TITLE
Duda con PAGINAS_POR_TABLA

### ISSUE THREAD

**Issue by Matias-Balboa** [sisoputnfrba/foro#2584]
Hola, tengo una duda con respecto a una de las config, no estaria seguro de la funcion que tiene ya que tampoco esta explicada en el cuadro:

PAGINAS_POR_TABLA=4

Imagino que es una restriccion para la tabla de nivel dos, pero no se si me restringe la cantidad de paginas que puede tener 1 proceso en esa tabla de nievel 2 y almacenar otras paginas de mi mismo proceso en otras tablas(Suponiendo que mi proceso tenga mas de 4 paginas en memoria), por ejemplo:

Tabla_nvl_2: tabla 1
proceso 1, marco 1, pagina 1
proceso 1, marco 2, pagina 2
proceso 1, marco 3, pagina 3
proceso 1, marco 4, pagina 4
proceso 2, marco 5, pagina 1
proceso 2, marco 6, pagina 2
proceso 2, marco 7, pagina 3
proceso 2, marco 8, pagina 4
....
Tabla_nvl_2: tabla 2
proceso 1, marco 9, pagina 1
proceso 1, marco 10, pagina 2
proceso 1, marco 11, pagina 3
proceso 1, marco 12, pagina 4
proceso 3, marco 13, pagina 1
proceso 3, marco 14, pagina 2
proceso 3, marco 15, pagina 3
proceso 3, marco 16, pagina 4
...
O si es una restricción en general que me restringe que mi tabla de nivel 2 puede solo tener 4 paginas, de cualquier proceso, en esa tabla en especifico:

Tabla_nvl_2: tabla 1
proceso 1, marco 1, pagina 1
proceso 1, marco 2, pagina 2
proceso 1, marco 3, pagina 3
proceso 1, marco 4, pagina 4

Tabla_nvl_2: tabla 2
proceso 1, marco 5, pagina 4
proceso 1, marco 6, pagina 5
proceso 1, marco 7, pagina 6
proceso 1, marco 8, pagina 7

Tabla_nvl_2: tabla 3
proceso 2, marco 9, pagina 1
proceso 2, marco 10, pagina 2
proceso 2, marco 11 pagina 3
proceso 2, marco 12, pagina 4

**Comment by LeandroCarbajales** [comment]
Buenas!
Me acabo de dar cuenta que en la tabla está como "ENTRADAS_POR_TABLA" y en el ejemplo quedó como "PAGINAS_POR_TABLA", ya lo arreglamos.

El número define la cantidad de entradas que tendrá cada tabla, tanto de 1er nivel como de 2do nivel, lo van a necesitar no solo para crear las tablas sino también desde la CPU para poder traducir las direcciones lógicas a físicas.

**Comment by Matias-Balboa** [comment]
O sea que si mi cantidad de entradas por tabla es de 4 entonces tendría:
mi tabla de nivel 1 apuntando a 4 tablas de nivel 2 que a su vez tienen 4 entradas  y eso me daría un total de 16 entradas? o la tabla de nivel 1 va a depender de la cantidad de marcos disponibles((Tamaño memoria/ Tamaño pagina)/entradas por tabla)?

**Comment by LeandroCarbajales** [comment]
Claro, tanto tus tablas de 1er nivel como de 2do nivel tendrían 4 entradas, por lo que cada proceso no podría tener más de 16 páginas, es independiente de la cantidad de marcos.

**Comment by LeandroCarbajales** [comment]
Exacto, es prácticamente igual a como se ven en clases, solamente podrías tener 4 en memoria a la vez, siguiendo tu ejemplo, si quisieras acceder a una de las otras 2 que no están presentes tendrías que hacer un reemplazo.
Saludos!
         Lean

**Comment by Matias-Balboa** [comment]
Muchisimas graciasss!!!!
