### ISSUE TITLE
Binary not found y asociados

### ISSUE THREAD

**Issue by Gdepablo** [sisoputnfrba/foro#2585]
#1963 
Lo configuré como en las capturas, y ahora me está saliendo esto
'Launching Client Debug has encountered an error. Program file does not exist'

### 📝 Pasos para reproducir el error
Seguí los pasos listados en las capturas del tema 1963, sólo que en vez de browsear puse directamente debug/ Client Debug (que es así como me aparece que se llama el archivo)

### 💻 Logs
Program file does not exist
/home/utnso/tp0/client/Debug/client Debug not found
/home/utnso/tp0/client/Debug/client Debug not found
/home/utnso/tp0/client/Debug/client Debug not found

**Comment by RaniAgus** [comment]
¡Buenas! ¿Podrías abrir una terminal en la carpeta donde se encuentra el proyecto y pasarnos lo que aparece al ejecutar el comando `tree .`? Por ejemplo:

```
utnso@ubuntu-server:~/workspace/project$ tree .
.
├── Debug
│   ├── makefile
│   ├── objects.mk
│   ├── project
│   ├── sources.mk
│   └── src
│       ├── example.d
│       ├── example.o
│       └── subdir.mk
├── logger.log
└── src
    └── example.c

```
Saludos

**Comment by Gdepablo** [comment]
Buenas, acá lo dejo!

![image](https://user-images.githubusercontent.com/44046974/165191742-107f2db8-953a-4bec-b9b4-a53264668bc8.png)

**Comment by RaniAgus** [comment]
Genial, entonces el ejecutable que estás buscando es el que aparece en verde:

![image](https://user-images.githubusercontent.com/39303639/165194602-85063d82-a459-4f12-8777-9d40a7098e6e.png)

Por lo que en el apartado `C/C++ Application` deberás configurar `Debug/client` para que Eclipse lo encuentre :)

Saludos

**Comment by Gdepablo** [comment]
Le pude dar Run cuando lo cambié, pero después cuando intento darle run me dice que el programa tiene errores (porque hay errores en mi código) pero en vez de decirme, no sé, el error, me dice esto
Program file does not exist
/home/utnso/tp0/client/Debug/client not found
/home/utnso/tp0/client/Debug/client not found
/home/utnso/tp0/client/Debug/client not found

que es lo mismo que antes, creo. 

Aprovecho y pregunto ya por el error

incompatible types when assigning to type ‘t_config * {aka struct <anonymous> *}’ from type ‘t_config {aka struct <anonymous>}’

 en 	sarasa2= *config_create("tp0.config");

**Comment by Gdepablo** [comment]
![image](https://user-images.githubusercontent.com/44046974/165370899-c9d0f088-e319-40db-af62-6ae1c14f183a.png)

Ahí lo reviso!
En cuanto a lo otro sí, sigue apareciendo, es lo verdecito

**Comment by iago64** [comment]
Buenas! Cómo va?

Es posible que la config de eclipse no este apuntando precisamente a la carpeta debug, podes poner una captura de como tenes la config de run de eclipse?

Saludos.-

**Comment by Gdepablo** [comment]
![image](https://user-images.githubusercontent.com/44046974/165874054-3cc67fa1-a000-4d91-959b-915bd9f2bff1.png)


La tengo así.
Me di cuenta que si el código tiene errores, tira eso, pero si no tiene errores, no dice nada.
Es raro igualmente

**Comment by iago64** [comment]
Buenas! 
Me llama la atención que no te este encontrando el ejecutable porque veo que esta con Debug/client
Por las dudas podrás pasar por soporte mañana para verlo en vivo con algún ayudante? Porque capaz es algo que no estamos viendo acá y en vivo es mas fácil de seguir 😄 

Saludos.-

**Comment by Gdepablo** [comment]
Buenas! De qué hora a qué hora es? Porque tambien tengo la cursada de la materia

**Comment by RaniAgus** [comment]
¡Buenas! Como avisamos en el [post de anuncio del TP](https://www.utnso.com.ar/1c2022-llego-kiss-a-sisop/) el horario aproximado es de 10 a 15hs.

**Comment by LeandroCarbajales** [comment]
@Gdepablo Creo que pudimos resolver este problema en soporte, se puede cerrar el issue?
