### ISSUE TITLE
Problema TP0 

### ISSUE THREAD

**Issue by Gdepablo** [sisoputnfrba/foro#2587]
```c
#include "client.h"

int main(void)
{
	/*---------------------------------------------------PARTE 2-------------------------------------------------------------*/

	int conexion;
	char* ip;
	char* puerto;
	char* valor;
	char* ubicacion = "/home/utnso/TP0/tp0/client/logs/tp0.log";

	t_log* logger;
	t_config* config;
	t_config* sarasa2;

	/* ---------------- LOGGING ---------------- */

	t_log* sarasa = log_create("/home/utnso/TP0/tp0/client/logs/tp0.log", "log_tp0", true, LOG_LEVEL_INFO);
	log_info(sarasa,"Hola! Soy un log");
	//logger = iniciar_logger();
	// Usando el logger creado previamente
	// Escribi: "Hola! Soy un log"


	/* ---------------- ARCHIVOS DE CONFIGURACION ---------------- */

	config = iniciar_config();
	config= config_create("tp0.config");
	valor = *config_get_string_value(sarasa, "CLAVE");
	log_info(sarasa,valor);
	config_destroy(config);

	// Usando el config creado previamente, leemos los valores del config y los 
	// dejamos en las variables 'ip', 'puerto' y 'valor'

	// Loggeamos el valor de config


	/* ---------------- LEER DE CONSOLA ---------------- */
	char *leido;
	leer_consola(logger);
	while(strcmp(leido,'\0')){
		leer_consola(logger);
		log_info(logger,leido);};
		free(1);

t_log* iniciar_logger(void)
{
	t_log* nuevo_logger;

	return nuevo_logger;
}

t_config* iniciar_config(void)
{
	t_config* nuevo_config;

	return nuevo_config;
}

void leer_consola(t_log* logger)
{
	char* leido;

	// La primera te la dejo de yapa
	leido = readline("> ");
	// El resto, las vamos leyendo y logueando hasta recibir un string vacío


	// ¡No te olvides de liberar las lineas antes de regresar!

}
```

Parte 1 y Parte 2

El problema acá es el siguiente, que no logro debugear:
Cannot create/open log file: No such file or directory

Me dice eso, 20 veces probé cambiar cosas pero nada, no sé qué es el problema que está teniendo y me está tilteando jaja

**Comment by iago64** [comment]
Buenas! Cómo va?

Justo el error que estas teniendo es algo que ya [paso veces anteriores en el foro](https://github.com/sisoputnfrba/foro/issues?q=is%3Aissue+Cannot+create%2Fopen+log+file), y generalmente viene de la mano de que cuando queres crear un archivo, estas queriendo hacerlo en una ruta que **no existe**, por lo que te dice: che no existe el archivo o directorio.

Estas 100% seguro que el path `/home/utnso/TP0/tp0/client/logs/tp0.log` existe?

Saludos.-

**Comment by Gdepablo** [comment]
Gracias!
Una consulta, ¿esto está correcto? Porquee en teoría, no sé si no lo estoy ejecutando o qué, pero al revisar el eclipse y el archivo log que genera no veo los valores ip...etc etc

`config = iniciar_config();
	config= config_create("tp0.config");
	valor = *config_get_string_value(sarasa, "CLAVE");
	log_info(sarasa,valor);
	config_destroy(config);`

**Comment by iago64** [comment]
Buenas!

Justamente el config te permite leer y escribir archivos con el formato de config:
`CLAVE=VALOR`

Si vos haces un `config_get_string_value()`, lo que vas a hacer es buscar el valor de la clave que le pasaste, con lo cual, ahi no vas a grabar nada.

Si lo que queres es escribir tenes que revisar las funciones que estan al final del [config.h de las commons](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/config.h)

Saludos.-

**Comment by Gdepablo** [comment]
Pero no entiendo entonces, cómo hacemos para pasarle la clave y que, por ejemplo, lo guarde o algo así
No me termina de quedar claro

**Comment by Gdepablo** [comment]
```
t_paquete* crear_super_paquete(void)
{	char* paqueta;
	int sarasa = malloc(sizeof(t_paquete));
	t_paquete* paquete;
	agregar_a_paquete(paqueta,sizeof(&paqueta)+1);
	//	enviar_paquete(socket_cliente,paquete);
	eliminar_paquete(paquete);

	//descomentar despues de arreglar
	//paquete->codigo_operacion = PAQUETE;
	//crear_buffer(paquete);
	return paquete;
}
```

Acá el ide me dice too few arguments para la funcion agregar_a_paquete cosa que no entiendo por qué en primer lugar. 
Segundo, no me queda del todo claro lo comentado (lo de descomentar después de arreglar) qué es lo que hace. O sea, qué funcioón cumple? Otra cosa de la que no entiendo es cómo le pasamos la conexión, deberíamos inicializarla ahí mismo llamando a crear_conexion? Porque sino no veo la forma de que nosotros tengamos el "socket" bindeado para pasarselo

**Comment by iago64** [comment]
> Pero no entiendo entonces, cómo hacemos para pasarle la clave y que, por ejemplo, lo guarde o algo así No me termina de quedar claro

La forma mas simple de tener las config es tener el archivo ya creado a mano (los  ejemplos del enunciado del TP  son justamente texto que si lo pegas en un txt lo podes leer con las funciones de las config).


> ```
> t_paquete* crear_super_paquete(void)
> {	char* paqueta;
> 	int sarasa = malloc(sizeof(t_paquete));
> 	t_paquete* paquete;
> 	agregar_a_paquete(paqueta,sizeof(&paqueta)+1);
> 	//	enviar_paquete(socket_cliente,paquete);
> 	eliminar_paquete(paquete);
> 
> 	//descomentar despues de arreglar
> 	//paquete->codigo_operacion = PAQUETE;
> 	//crear_buffer(paquete);
> 	return paquete;
> }
> ```
> 
> Acá el ide me dice too few arguments para la funcion agregar_a_paquete cosa que no entiendo por qué en primer lugar. Segundo, no me queda del todo claro lo comentado (lo de descomentar después de arreglar) qué es lo que hace. O sea, qué funcioón cumple? Otra cosa de la que no entiendo es cómo le pasamos la conexión, deberíamos inicializarla ahí mismo llamando a crear_conexion? Porque sino no veo la forma de que nosotros tengamos el "socket" bindeado para pasarselo

El problema del few arguments basicamente te dice que te faltan argumentos,  en la definición de la función `agregar_a_paquete()`, cuantos argumentos te dice que necesita y cuantos le estas pasando?

El tema del  comentario,  cual es el objetivo de la función `crear_super_paquete()`? tiene que crear la conexión completa o solo genera el buffer que vas a mandar por el socket y despues del envío se encarga otra función?

Saludos.-

**Comment by Gdepablo** [comment]
agregar_a_paquete(2): Dado un string y su tamaño, lo agrega al paquete.

Rta:

agregar_a_paquete(paqueta,sizeof(&paqueta)+1);

Entonces por eso digo que no tiene sentido porque le estoy dando un string y su tamaño

Y lo de crear_super_paquete es esto: 
El único problema, es que estas funciones no nos sirven para enviar las líneas de consola todas juntas, por lo que vamos a crear un paquete. Este paquete nos va a asegurar que toda la información que mandemos se envíe junta. Para ello les proveemos otro conjunto de funciones o “API” para crear, rellenar y enviar paquetes
No tiene que generar la conexión, porque la conexión ya la genera otro subprograma que es crear_conexion; pero te pide en una de las funciones que dice el tp0 el "socket" que es donde estaría alojada la conexión, y eso no tengo forma de hacerlo a menos que llame a crear_conexion adentro de crear_super_paquete supongo, pero no sé si eso es mucha responsabilidad para la funcion

**Comment by iago64** [comment]
Estas 100% seguro que el agregar paquete recibe 2 parámetros? Si reviso el archivo [utils.h](https://github.com/sisoputnfrba/tp0/blob/master/client/src/utils.h) veo que tiene **3** argumentos, el string, el tamaño y el paquete al cual queres agregar el string.

El tema del `crear_super_paquete()` es literalmente lo mismo que `crear_paquete()`, lo único que tiene es que como te dice el comentario, le falta un `malloc()` para que pueda crear el paquete, ya que la idea es que vean con el debug del eclipse donde esta el problema:

```c
t_paquete* crear_super_paquete(void)
{
	//me falta un malloc!
	t_paquete* paquete;

	//descomentar despues de arreglar
	//paquete->codigo_operacion = PAQUETE;
	//crear_buffer(paquete);
	return paquete;
}

t_paquete* crear_paquete(void)
{
	t_paquete* paquete = malloc(sizeof(t_paquete));
	paquete->codigo_operacion = PAQUETE;
	crear_buffer(paquete);
	return paquete;
}
```

Una vez resuelto el tema del `malloc()` faltante solo tienen que descomentar las 2 líneas que están abajo para que se genere bien el paquete.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @Gdepablo! ¿Pudiste revisar lo que comentó Dami? Saludos

**Comment by Gdepablo** [comment]
Ahi lo vi pero me quedó la duda porque yo entendí del enunciado que había que crear una especie de crear paquete 2.0 y poner lo del socket y toda la historia. Si no es asi, no me queda claro que hace crear_super_paquete()

**Comment by RaniAgus** [comment]
En otras palabras, la idea era solo cambiar los lugares en donde usaste `crear_paquete()` por `crear_super_paquete()`, usar el debugger para entrar a la función y averiguar por qué rompe; y por último corregirla.

**Comment by LeandroCarbajales** [comment]
Buenas @Gdepablo, quedó resuelta la duda?

**Comment by Gdepablo** [comment]
Sisi ya está, gracias!
