### ISSUE TITLE
Duda suspensión de procesos

### ISSUE THREAD

**Issue by chelyx** [sisoputnfrba/foro#2589]
Buenas! Tengo unas dudas con respecto a cuando decido que un proceso va a ser suspendido:

> Para que un proceso entre en suspensión se debe cumplir que el mismo esté bloqueado por un tiempo mayor al límite definido por archivo de configuración.

Cuando me llega por la conexión con CPU que el proceso se bloquea por una instrucción de I/O, sabría cuanto tiempo dura ese bloqueo y podría determinar a priori que se va a suspender.  Por eso en un primer momento consideramos esta solución:
```
// llega el pcb desde CPU por un bloqueo. 
// lo paso a la cola de bloqueados
if(excede tiempo)
  sleep(tiempo_bloqueado)
  suspender_proceso()
else
  sleep(tiempo_bloqueado)
```
La otra solución que se me occurre es guardar en el pcb el timestamp desde cuando se bloqueo y tener un hilo aparte que chequee que no se exceda del tiempo máximo y en tal caso suspenda el proceso. Creo que esta es mejor considerando la cola de bloqueados y que el bloqueo puede demorar más que el tiempo que dure la I/O.

**Comment by LeandroCarbajales** [comment]
Buenas!
Viene por ahí la mano :), capaz en vez de guardarte el timestamp y todo eso prefieras directamente levantar un hilo que haga sleep de "tiempo_máximo_bloqueado" y que lo suspenda si sigue bloqueado después de ese tiempo.
Lo importante es que el proceso se suspenda después de estar esa cantidad de tiempo bloqueado y no apenas se bloquea.

Te sirve la respuesta?

Saludos!
        Lean

**Comment by chelyx** [comment]
Si! Me sirve un montón. 
Muchas gracias!!
