### ISSUE TITLE
Sockets modulo CPU: como crear los servidores en este modulo

### ISSUE THREAD

**Issue by dimoulasLucas** [sisoputnfrba/foro#2590]
Hola, que tal? Consultando en los sabados de soporte estuvimos charlando con algunos ayudantes sobre la forma de crear los servidores en el modulo de la CPU.  
Nuestra preguntas son: ¿debemos crear dos servidores con la misma ip pero que hagan bind (se liguen) a distintos puertos? (uno para el dispatch y otro para el interrupt) .
¿Dos servidores con dos ip y dos puertos distintos?
O, ¿debemos crear un unico servidor, con un unico puerto, por el que se envian mensajes con codigos de operacion distintos dependiendo de si se trata de un mensaje de interrupcion o no?

**Comment by RaniAgus** [comment]
¡Buenas! 

Sobre el tema conexiones no somos estrictos: en el enunciado recomendamos usar dos `bind()` a puertos distintos y un `accept()` para cada uno, aunque también existe una forma de hacer un solo `bind()` y dos `accept()` mediante handshakes.

En cuanto a hacer un solo `bind()` y `accept()` y manejarse con códigos de operación, les recomendamos no hacerlo: recuerden que en distintas etapas del ciclo de instrucción van a estar haciendo un `recv()` para un cierto tipo de mensaje, por lo que si reciben el otro van a tener que hallar la forma de no perderlo (lo cual es mucho más complejo que mantener dos conexiones separadas).

Saludos

**Comment by dimoulasLucas** [comment]
Genial, se entendió perfecto. Muchas gracias
