### ISSUE TITLE
Duda sobre el tamaño/direcciones usadas en el programa

### ISSUE THREAD

**Issue by echisaidman** [sisoputnfrba/foro#2591]
Buenas, con mi grupo nos surgió una duda sobre todo lo que es direcciones y tamaños. En la parte de configuracion de la Memoria, dice que el TAM_MEMORIA es el tamaño en bytes que tiene el programa, lo que limitaría el espacio direccionable por ese proceso. Por ejemplo, en [este issue](https://github.com/sisoputnfrba/foro/issues/2581) mencionaron que el espacio direccionable por el proceso seria [0, tamaño - 1].
Nuestra duda sería si verdaderamente este tamaño es en bytes, o si en realidad representa la cantidad de `uint32`s que puede "tener" el proceso. Por ejemplo, supongamos que el proceso se crea desde Consola con un tamaño 20, y una instruccion de ese proceso es `READ 15`. Qué habría que hacer en ese caso? Tirar error porque 15 no es multiplo de 4? Leer desde el byte 15 hasta el 18 inclusive (así se leen 4 bytes seguidos y se convierte a `uint32`)? Leer desde el byte 15 al 17 y tirar error porque son unicamente 3 bytes?

- Como agregado, si la unidad es en bytes, entonces hacer `READ 19` para un proceso con tamaño 20 tampoco sería válido, porque habría que leer el byte 19 y 3 bytes más, y te pasarías del 20

De forma similar, qué pasaría si yo creo el proceso con tamaño 13 (algo no multiplo de 4)? Va a existir un byte que el proceso no va a poder utilizar nunca (porque sería unicamente del byte 0 al byte 11, y podría guardar 3 `uint32`)?

- Aclaro por las dudas que eso del byte _x_ al byte _y_ no sería así porque las paginas del proceso pueden estar desordenadas, pero era nomas para que se entienda nuestra duda

La duda no nos termina de cerrar, así que probablemente no se entienda nada, así que lo resumo con un:

> Si tengo la instruccion `READ 1`, ¿qué habría que leer? ¿El "byte 1", o del "byte 4" al "byte 7"?

Muchas gracias :)

**Comment by LeandroCarbajales** [comment]
Buenas!
En resumen, si tienen una instrucción `READ 1` tendrían que leer 4 bytes desde la dirección (el byte) 1.
Más allá de eso, el tamaño y las direcciones no tienen por qué ser múltiplos de 4 y funcionaría todo igual siempre que no escriban solapado, y para aclarar, la idea es que las instrucciones que vienen por el archivo de pseudocódigo sean consistentes entre sí y con el tamaño del proceso.

Saludos!
 Lean

**Comment by echisaidman** [comment]
Buenas Lean, muchas gracias por la respuesta. Creo que entendí, pero para validar te mando [este ejemplo](https://imgur.com/a/RSb9Ygq) (y así de paso valido también si entendimos correctamente el esquema de la Memoria). Supongamos que con ese ejemplo un proceso tira `READ 10`, y que haciendo la traduccion a direccion fisica me da `6`. El tema ahí es que los bytes 6 y 7 de la memoria pertenecen al proceso, pero los bytes 8 y 9 (que serían los que leeríamos para leer los 4 bytes del `uint32`) pertenecen a otro proceso. En ese caso, qué es lo que habría que hacer?

1. Leer igualmente los bytes 6, 7, 8 y 9, aunque el 8 y 9 sean de otro proceso (probablemente esta no sea la respuesta correcta :))
2. Leer el 6, el 7 y los 2 primeros bytes de la pagina siguiente del proceso (en este caso 16 y 17)
3. Tirar error

**Comment by LeandroCarbajales** [comment]
Buenas!
En ese caso estarías accediendo a 2 páginas como en tu 2da opción, y te podés dar cuenta sin hacer ninguna traducción. Si tu tamaño de página es 4 y haces READ 10 (o sea las direcciones 10, 11, 12 y 13), ya sabés que tendrías que acceder a las páginas 2 y 3.

**Comment by echisaidman** [comment]
@LeandroCarbajales bárbaro, entonces te hago la última pregunta. Lo que yo había entendido era que la traducción de dirección lógica a física la hacía la CPU, y que a Memoria ya llegaba directamente la instrucción con la dirección física (en este caso lo que Memoria recibiría sería `READ 6`), ¿es así? Porque si desde Memoria directamente recibo READ 6 creo que no tiene mucho sentido, porque tendría que "des-traducir" la dirección física para llegar a la lógica (10), para saber que tengo que leer los bytes 10, 11, 12 y 13 y buscar las páginas necesarias, por lo que básicamente haber hecho la traducción fue un desperdicio. ¿Cómo sería eso?

**Comment by LeandroCarbajales** [comment]
Buenas!
Desde la CPU ya sabés de antemano que estás accediendo a 2 páginas distintas (porque el desplazamiento + 4 bytes se pasa del tamaño de página), por lo que tendrás que hacer 2 traducciones, una de las traducciones terminaría diciéndole a la memoria "dame 2 bytes desde el 6" y la otra traducción terminaría diciéndole "dame 2 bytes desde el 16".

**Comment by echisaidman** [comment]
Excelente Lean, muchísimas gracias por todo, quedó clarísimo ❤️! Cierro el hilo nomás =)
