### ISSUE TITLE
Problema de interpretacion de "N instancias de consola"

### ISSUE THREAD

**Issue by mbertogliati** [sisoputnfrba/foro#2592]
Hola, me surgen dudas sobre la interpretacion de las "N consolas" en el enunciado. Estas consolas, son consolas reales? Es decir un prompt? O es simplemente una forma de referirse a la función que lee y envia datos al kernel? Si fueran consolas reales, de que forma se pueden instanciar en un ubuntu sin interfaz grafica (Que es en el que vamos a usar cuando presentemos nuestro TP) ?

### 📔 Citas del enunciado/videos

>El módulo Consola será el punto de entrada. Su objetivo es definir los procesos que habrá en nuestro sistema, instanciándose tantas veces como procesos queramos tener en el mismo.

### 💭 Soluciones posibles

Creo haber leido sobre tty que serian multiples consolas en el ubuntu sin GUI pero la verdad no entendi mucho

**Comment by RaniAgus** [comment]
¡Buenas! El enunciado se refiere a instancias del módulo Consola del TP:

![image](https://user-images.githubusercontent.com/39303639/165518803-d0720b58-0689-4e74-9e80-2a6071dcdca7.png)

Cada módulo es un proyecto en C distinto (por eso usamos sockets para conectarlos entre sí). Se instancian por línea de comandos (`./kernel` , `./cpu`, etc), por lo que no es necesario desarrollar una interfaz gráfica.

Saludos

**Comment by mbertogliati** [comment]
Gracias por la respuesta!

**Comment by LeandroCarbajales** [comment]
Cierro el issue porque asumo que se resolvió la duda, cualquier cosa se vuelve a abrir :)
