### ISSUE TITLE
Tengo un mensaje de segmentation fault desde consola

### ISSUE THREAD

**Issue by DanielBareiro** [sisoputnfrba/foro#2593]
Buenas, tengo un problema con el config del tp0, cuando uso la consola del eclipse me anda todo bien me devuelve todos los valores que tengo en el client.config, pero cuando uso la consola de la terminal me lanza el mensaje de segmentation fault.

**Comment by RaniAgus** [comment]
¡Buenas! Te recomiendo ver esta [guía de rutas relativas y absolutas](https://faq.utnso.com.ar/guia-rutas); es cortita y explica en detalle cómo hace internamente Eclipse para resolver la ruta hacia el archivo config.

Saludos

**Comment by LeandroCarbajales** [comment]
@DanielBareiro Te sirvió la respuesta? Se puede cerrar el issue?

**Comment by iago64** [comment]
Cerramos por inactividad, cualquier cosa no se olviden que pueden reabrir el issue o pueden crear uno nuevo haciendo referencia a las respuestas de este issue 😄
