### ISSUE TITLE
Duda sobre direcciones virtuales o logicas

### ISSUE THREAD

**Issue by gustavosrey** [sisoputnfrba/foro#2594]
Buenas tenemos dudas sobre generacion de direcciones virtuales: El espacio de direcciones del proceso es el tamaño del proceso que se le pasa a consola con el  argumento de linea de comandos, eso seria la cantidad de bytes que el programa puede direccionar o referenciar. Pero al limitar la cantidad de entradas que tiene la tabla de pagina tanto del primer nivel como del segundo nivel puede darse que no alcancea la tabla de pagina  para todo el espacio de direcciones del proceso. Lo que quiero decir que a las tablas de paginas va a ir un subconjunto de todas las paginas del proceso el resto iria a swap entiendo, pero me cuesta ver como se forman las direcciones logicas ya que para acceder a una pagina en memoria utilizaria la siguiente formula
|Cantidad de  bits para direccionar tantas ENTRADAS_POR_TABLA| Cant bits para dir ENTRADAS_POR_TABLA| Cant bits para dir TAM_PAGINA (offset)|
o sea que la direccion virtual, o sea el espacio de direcciones virtuales del proceso me cambiaria segun  ENTRADAS_POR_TABLA y TAM_PAGINA  que este seteado en el archivo de configuracion. o sea no va aser algo fijo sino que puede cambiar segun el archivo de configuracion . Serian tan amables de aclararnos un poco este punto.
Gracias

**Comment by RaniAgus** [comment]
¡Buenas!

> al limitar la cantidad de entradas que tiene la tabla de pagina tanto del primer nivel como del segundo nivel puede darse que no alcancea la tabla de pagina para todo el espacio de direcciones del proceso

No vamos a contemplar este caso en las pruebas, siempre les vamos a dar un proceso con un tamaño que se pueda indexar en memoria.

> o sea que la direccion virtual, o sea el espacio de direcciones virtuales del proceso me cambiaria segun ENTRADAS_POR_TABLA y TAM_PAGINA que este seteado en el archivo de configuracion. o sea no va aser algo fijo sino que puede cambiar segun el archivo de configuracion

Partiendo de este comentario de Lean https://github.com/sisoputnfrba/foro/issues/2581#issuecomment-1108046636, en realidad las direcciones lógicas son siempre las mismas. Lo único que cambia a nivel archivo de configuración es cómo hace la memoria para organizar esas direcciones.

Por ejemplo, en una Consola de tamaño 256 bytes (o sea que las direcciones lógicas deben tener mínimo 8 bits), quizás en una prueba la Memoria esté configurada para partirla en [2 bits | 2 bits | 4 bits] y otra lo haga en [1 bit | 1 bit | 6 bits], pero las direcciones lógicas son fijas per sé.

Saludos

**Comment by gustavosrey** [comment]
Muchisimas Gracias Aguastin!!!! Aprovecho para despejar algunas dudas de cosas que no entendemos: el enunciado dice:
"se definirá una asignación de cantidad de marcos fija definida por archivo de configuración " y ademas "a diferencia de laspáginas de los procesos, sus tablas de páginas no necesitan ser swapeadas" pero tambien en otra parte habla de "Además debe implementar memoria virtual, más específicamente, paginación bajo demanda", como se implementaria esto si no hay fallo de pagina que traiga de swap o de disco, la paginacion bajo demanda implicaria que las tablas inicailmente esten vacias y se vayan cargando a las tablas por fallos de pagina, es decir las tablas de 1er nivel no se modificarian ya que estan en el PCB, pero las de 2do nivel si ya que estan en memoria, esas tablas de segundo nivel si podrian implementar paginacion bajo demanda. Entendemos que lo que se swapea es el PCB. Estamos confundidos en este punto cualquier luz que se pueda se agradeceria. Gracias por adelantado.

**Comment by LeandroCarbajales** [comment]
Buenas!
Salvo las aclaraciones del enunciado, todos estos conceptos son exactamente igual que como se ven en la clase de memoria virtual con paginación "normal", tendrás page fault cuando quieras acceder a una página que tenga presencia=0 y traerla de swap. Estarías solamente modificando las tablas de 2do nivel ya que al no tener que swapearlas, las tablas de 1er nivel quedan fijas.
Y para aclarar, el PCB nunca se swapea y el mismo no contiene ninguna tabla, sino un "puntero" a la misma.

**Comment by gustavosrey** [comment]
Gracias Lean, me aclaro bastante. La duda que me surge es si ante un TLB miss hay que generar una interrupcion por fallo de pagina guardar el PCB y la CPU entonces atenderia la interrupcion actualizando tabla de paginas 2do nivel y TLB, o sea que la duda seria que la CPU puede emitir dos tipos de interrupciones una seria "En el caso de los algoritmos con desalojo, cuando un proceso llegue a la cola READY se deberá enviar una Interrupción al proceso CPU a través de la conexión de interrupt para indicarle que deberá desalojar al proceso que se encuentra actualmente en ejecución." y la otra para page fault o el fallo de pagina se trataria sin interrupcion. Gracias nuevamente.

**Comment by LeandroCarbajales** [comment]
Buenas!
El fallo de página lo hacemos "sincrónico y no bloqueante" para este TP, cuando necesites una página que no está presente la traes de swap y devolvés el número de marco donde quedó, no nos vamos a meter en generar la interrupción de page fault porque sería dar mucha vuelta para ver los mismos conceptos de memoria virtual.

Saludos!
        Lean

**Comment by gustavosrey** [comment]
Muchisimas Gracias por responder Lean siempre nos aclaras las dudas, Nos han surgido algunas dudas respecto al funcionamiento de los bits de la tabla de pagina de segundo nivel, estos seria bit P de presencia, bit U de uso y bit M de modificado,si bien el enunciado no lo dice expresamente entendemos que significan eso. La duda que tenemos tiene que ver con como se llena la tabla de paginas y tambien los cambios de contexto cuando cambio una consola a otra. Inicialmente se crean las tablas de segundo y primer nivel pero no se llenan sus entradas ya que es paginacion por demanda, a medida que se van ejecutando las instrucciones  y solamente cuando sean WRITE o READ la memoria va a ser referenciado entendemos eso ya que entendemos que el codigo no se pagina, sino solamente las referencias a memoria del programa emtonces cuando se referencia una pagina que al principio no va a ester en las tablas se produce un page fault y se trae de swap entonces se actualiza la entrada en la tabla y ademas el bit de presencia se pone en 1, ademas de completar la entrada en TLB. Cuando es una instruccion WRITE el bit de Modificado se pone en 1 para que antes de elejir una pagina victima se escriba a swap la pagina. entendemos que para mantener la consistencia del TLB cuando hay un cambio de contexto se deben poner todas las entradas del TLB a 0. Nuestra pregunta es si nuestro razonamiento es correcto o el conjunto residente de las tablas de paginas debe empezar con algunas paginas cargadas en memoria.

Gracias por la paciencia.

**Comment by LeandroCarbajales** [comment]
Buenas!
Estás en lo correcto :), todo el mecanismo y estructuras que se utilizan son muy similares (un poco simplificadas) de lo que se verán en las clases de memoria y memoria virtual. Justamente por eso algunos conceptos como los bits de las tablas de páginas o el hecho de tener que limpiar la TLB en un cambio de proceso no están explicitadas en el enunciado.

Saludos!
       Lean

**Comment by gustavosrey** [comment]
Gracias por responder Lean, Nos surgio una duda en la pag 21 dice: "La memoria contara principalmente con 3 estructuras:
Un espacio contiguo de memoria (representado por un void  *). Este representara el espacio de usuario de la misma, donde los procesos podran leer y escribir."   Entendemos que el tamaño de este espacio corresponderia a MARCOS_POR _PROCESO * TAM_PAGINA que se corresponderia con la memoria real que tendria el proceso y no se corresponderia con el tamaño del proceso o consola que se pasa por linea de comando. Gracias

**Comment by RaniAgus** [comment]
¡Buenas! El espacio contiguo en memoria al que se refiere el enunciado tiene un tamaño fijo especificado por archivo de configuración:

![image](https://user-images.githubusercontent.com/39303639/166122501-b532c9d9-de9f-4353-a3ff-164dd20c9804.png)

Siempre va a ser múltiplo de `TAM_PAGINA` y vendría a representar únicamente los **frames** en memoria (no las **páginas** de cada proceso). 

Saludos

**Comment by LeandroCarbajales** [comment]
Buenas!
Quedó resuelta la duda?

**Comment by LeandroCarbajales** [comment]
Cierro el issue por inactividad, si quedaron dudas lo vuelven a abrir :)
