### ISSUE TITLE
Kernel post-consola

### ISSUE THREAD

**Issue by DamianArielLerner** [sisoputnfrba/foro#2595]
Buenas tardes, una pregunta, que recomendarian hacer luego de haber recibido las instrucciones por parte de la consola en el modulo kernel? Creamos una estructura de pcb, pero ademas de guardar el id del proceso y el tamaño junto a las instrucciones, y de haber cargado la configuración del kernel, no se nos ocurre como continuar el kernel como para progresar el checkpoint 2. Desde ya, muchas gracias!

**Comment by LeandroCarbajales** [comment]
Buenas!
Les recomendamos seguir con lo que es la planificación de corto plazo con el algoritmo FIFO, esto incluye poder enviarle el PCB (o lo que necesiten de él) a la CPU y que la misma puede ejecutar sus instrucciones, por ahora no se preocupen por las que interactuan con memoria, solamente implementen NO_OP, IO y EXIT.

Una vez que tengan eso van a tener una buena base para avanzar con el resto del Kernel que pide el 3er checkpoint (planificación de largo y mediano plazo y algoritmo SRT)

Saludos!
          Lean

**Comment by LeandroCarbajales** [comment]
@DamianArielLerner Les sirvió la respuesta? Se puede cerrar el issue? Tengo entendido que lo vieron también hoy en soporte :)

**Comment by DamianArielLerner** [comment]
Si, me olvidé de cerrar!
