### ISSUE TITLE
Colas READY

### ISSUE THREAD

**Issue by matiastito** [sisoputnfrba/foro#2597]
Buenas tardes, los molesto en referecia a la definición del tp del planificador de corto plazo.

> Los procesos que estén en estado READY serán planificados mediante los siguientes algoritmos:
> FIFO: First in First out
> SRT: Shortest Remaining Time (también visto como SJF con desalojo)

La  pregunta es la siguiente:
Parecen ser dos colas pero no llego a entender en función a qué criterio los procesos entran en uno o en otra.

Muchas Gracias!

**Comment by RaniAgus** [comment]
¡Buenas! Deben implementar ambos algoritmos y poder elegir uno u otro dependiendo del valor obtenido desde el archivo de configuración:
![image](https://user-images.githubusercontent.com/39303639/165631975-b8168109-336d-4f57-aa7a-28faa6454d06.png)

Saludos

**Comment by matiastito** [comment]
Gracias
