### ISSUE TITLE
Conexiones con memoria

### ISSUE THREAD

**Issue by Salacas** [sisoputnfrba/foro#2598]
Buenas! No entiendo bien la conexión de la memoria con el cpu y el kernel. En el config de la memoria se pasa solo un puerto para escuchar 2 conexiones. No debería haber un puerto abierto más?

Muchas gracias, un saludo

**Comment by RaniAgus** [comment]
¡Buenas!
No somos estrictos con el tema conexiones: si quieren pueden hacer un solo `bind()` y dos `accept()` para aceptar ambas conexiones como está sugerido (implementando un [handshake](https://faq.utnso.com.ar/guia-sockets) que indique si el módulo que se conectó es CPU o Kernel), o también pueden hacer dos `bind()` con sus respectivos `accept()` y configurar dos puertos distintos.

Recuerden que por cada `accept()` se devuelve un nuevo socket, distinto al que se usó para hacer `bind()`.

Saludos
