### ISSUE TITLE
[memoria] duda creación tablas

### ISSUE THREAD

**Issue by KaterinaCejas** [sisoputnfrba/foro#2599]
Hola! 
Me surgió una duda respecto a la respuesta que dieron en este [issue](https://github.com/sisoputnfrba/foro/issues/2586#issuecomment-1109877430)   

> "conceptualmente las mismas son de tamaño fijo, es decir siempre tendrían 4 entradas, pero sí es correcto crear solamente la cantidad necesaria"

Por ejemplo: tengo entradas_por_tabla = 4,  y un proceso que necesita un total de 6 paginas. Eso significaría 2 tablas de segundo nivel.
Según la respuesta que dieron en ese issue: 
Para la tabla de 1er nivel tendría 4 entradas con las primeras 2 entradas apuntando cada una a una tabla de 2do nivel, y las ultimas 2 entradas sin ninguna tabla de 2do nivel asignada, pero **creadas**.
Pero por ejemplo en este caso al ser 6 paginas, en una de las tablas de 2do nivel, solo se ocuparían 2 paginas. Las otras 2 las tengo que crear igual porque la creación de paginas es de **tamaño fijo si o si**, o en esos casos **solo se crearían las cantidad de entradas necesarias** como dijeron en el issue?
Graciassss, saludos

**Comment by LeandroCarbajales** [comment]
Buenas!
La lógica es la misma para todas las tablas, son de (en este ejemplo) 4 entradas. Eso no significa que tengan que crear 4 tablas de 2do nivel (de hecho no deberían hacerlo en este caso). En el caso de las tablas de 2do nivel, la gracia es que nunca van a acceder a esas entradas que "sobran" porque van a encajar siempre con direcciones lógicas que se pasan del tamaño del proceso, por lo que en definitiva no tendrían páginas de más tampoco.

Te resuelve la duda?
Saludos!
         Lean

**Comment by KaterinaCejas** [comment]
Geniall todo resuelto, gracias :)
