### ISSUE TITLE
Guardar structs en lista con list_add

### ISSUE THREAD

**Issue by dlopezjoffreutn** [sisoputnfrba/foro#2600]
Buenas! Como le paso a los chicos en https://github.com/sisoputnfrba/foro/issues/2485 nos pasa que dentro de un loop deseamos agregar elementos a una lista a traves de list_add y al recorrerla vemos que todos los elementos son el mismo (el último leido)! 

Entendemos que es porque el valor del puntero se pisa, pero en si siempre es el mismo puntero.

Probando la respuesta del issue linkeado, funciono bien para ints pero no para nuestra struct t_instruction:

```
typedef struct instruction {
    char* id;
    u_int32_t* params;
} t_instruction;
```

A esta le reservamos espacio en el heap de esta forma:

```
t_instruction* new_instruction(size_t id_size) {
	// Try to allocate instruction structure.
	t_instruction *instruction = malloc(sizeof(t_instruction));
	if (instruction == NULL)
		return NULL;

	// Try to allocate instruction id and params, free structure if fail.
	instruction->id = malloc((id_size + 1) * sizeof(char));
	if (instruction->id == NULL) {
		free(instruction);
		return NULL;
	}

	instruction->params = malloc(2 * sizeof(int));
	if (instruction->params == NULL) {
		free(instruction);
		return NULL;
	}

	return instruction;
}
```

El entorno del list_add es este mismo, y no sabemos como armar una `t_instruction` temporal para efectivamente agregarla a la lista sin pisar su valor.

> Tambien medio que entendimos que como hacemos `new_instruction` dentro de `parse_instruction`, la instruction siempre seria una nueva pero no fue el caso :)

```
while (lines_read != -1) {
	list_add(instruction_list, parse_instruction(line_buf));
	lines_read = getline(&line_buf, &line_buf_size, file);
}
```

Funcion parse instruction que reserva espacio para una nueva instruction, edita sus valores y la retorna.

```
t_instruction* parse_instruction(char *string) {
	int param;
	int i = 0;

	char *id = strtok(string, " ");
	t_instruction* instruction = new_instruction(strlen(id));
	instruction->id = id;

        printf("instruction addy: %d \n", &instruction);

	char *params = strtok(NULL, " ");
	while (params != NULL) {
		param = atoi(params);
		instruction->params[i] = param;
		params = strtok(NULL, " ");
		i++;
	}

	return instruction;
}
```

> Agrego que sumando el print de la direccion de `instruction`, en todos los casos es la misma:
> 
> <img width="260" alt="image" src="https://user-images.githubusercontent.com/82044090/165646826-85978d2d-c58f-44e4-bd3a-0300f564d966.png">

Hay forma de reutilizar el sistema del issue linkeado para t_instruction? 
Reemplazando el while con algo parecido pero con los tipos correctos... 

```
while (lines_read != -1) {
	t_instruction* bloque = malloc(sizeof(t_instruction));
	t_instruction temp = *parse_instruction(line_buf);

	memcpy(bloque, &temp, sizeof(t_instruction));
	list_add(instruction_list, temp);

	lines_read = getline(&line_buf, &line_buf_size, file);
}
```

directamente nos tira este error

<img width="548" alt="image" src="https://user-images.githubusercontent.com/82044090/165643702-217b0f46-3fb2-4b89-8240-ef95c46f8565.png">

Y cambiando el tipo de `temp` para que este sea un puntero (`t_instruction* temp = parse_instruction(line_buf);`), el `list_iterate` loguea una vez mas la lista con el ultimo valor repetido en todas las posiciones:

```
void log_elem(void *elem) {
	puts(((t_instruction*) elem)->id);
};

list_iterate(instruction_list, log_elem);
```

<img width="119" alt="image" src="https://user-images.githubusercontent.com/82044090/165644305-e1358808-d404-448d-a256-930654a296cd.png">
<img width="72" alt="image" src="https://user-images.githubusercontent.com/82044090/165644090-59ff4415-baf1-4c4e-8708-ab987f31b87a.png">

Cualquier guia a la direccion que va o codigo que nos pueda dar una mano en esta situacion (y seguro muchas mas a futuro) lo re agradecemos :))

Saludos, 
Dolores 👋

**Comment by RaniAgus** [comment]
¡Buenas! Antes que nada, un par de comentarios:
1. Tengan cuidado a la hora de "rellenar" el contenido de `instruction->id`. Por un lado están reservando memoria:
```c
instruction->id = malloc((id_size + 1) * sizeof(char));
```
Y por otro están "pisando" ese puntero con lo que devuelve `strtok()`:
```c
char *id = strtok(string, " ");
t_instruction* instruction = new_instruction(strlen(id));
instruction->id = id;
```

"Pisar" un puntero es distinto que "rellenar" el contenido al que apunta, les dejo este comment como referencia 😉: https://github.com/sisoputnfrba/foro/issues/2224#issuecomment-882803512

2. ¡No usen `strtok()`! Es una función peligrosa porque devuelve un string (hace una consulta) y a la vez modifica el string original (o sea, produce un efecto). 

Desde las commons les proveemos [funciones para que no tengan que complicarse la vida manejando strings](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/string.h), como `string_split()`. De hecho, si ven que necesitan hacer algo con strings y las commons no proveen esa funcionalidad, avísennos y vemos de incluirla 😄

3. El print de la direccion de instruction, en todos los casos es la misma porque están printeando `&instruction`, o sea, la dirección en memoria en donde se encuentra la variable en el stack que contiene al puntero. Para chequear el valor del puntero asegúrense de usar `instruction` con [el tag de printf correcto](https://www.tutorialspoint.com/c_standard_library/c_function_printf.htm).


Dicho todo esto, aclaro que `t_list` almacena punteros hacia otras estructuras (de cualquier tipo). Es decir, dentro de cada nodo únicamente se guarda la dirección en memoria que le pasen ustedes a `list_add()`, por lo que no hace falta crear una estructura "intermedia", sino que pueden pasar directamente el `t_instruction*` que parsearon mediante `parse_instruction()`.

Por último, les aconsejo repasar la [guía de manejo de punteros y memoria dinámica](https://faq.utnso.com.ar/punteros). Si ven algo de la guía que no queda del todo claro siéntanse libres de preguntarnos también 🤗 

Saludos

**Comment by LeandroCarbajales** [comment]
Buenas! @dlopezjoffreutn te sirvió la respuesta? :)

**Comment by dlopezjoffreutn** [comment]
Buenass, si! Súper colgué en contestar, mil gracias!

**Comment by LeandroCarbajales** [comment]
Genial! Cierro el issue entonces, buen finde!
