### ISSUE TITLE
FINALIZAR PROCESO EN MEMORIA

### ISSUE THREAD

**Issue by matiasferrerovilas** [sisoputnfrba/foro#2601]
Tenia una duda, con el enunciado.
![imagen](https://user-images.githubusercontent.com/27780879/165654893-44f4c75d-5705-4feb-9c37-3b9d3e3b9bfe.png)

En esa parte dice uque no hace falta eliminar la tabla, entonces queria confirmar si esta bien este pensamiento.
Cuando memoria se ejecuta este crea sus 2 listas (nivel 1 y 2) vacias, y cuando se van inicializando los procesos ahi se van agregando en las listas correspondiente. 
Mi duda es, si yo tengo el proceso 1, y 2. El proceso 1 se libera, entonces quedan las tablas en la lista de memoria (pero sin uso), cuando llega el proceso 3, tiene que utilizar esa tabla que quedo creada y sin uso, o hay que crear una nueva al final de la lista?.

**Comment by LeandroCarbajales** [comment]
Es indiferente, si quieren eliminar las tablas y crear nuevas, o si quieren reusar las que estaban, o (probablemente lo más simple) crear nuevas y dejar las viejas sin uso, lo único que va a cambiar es qué numerito le devuelven al Kernel al crear un proceso nuevo.
Como dice la nota al pie, los invitamos a pensar las implicancias que tendría su implementación en un sistema real.

**Comment by matiasferrerovilas** [comment]
ok ok. perfecto.
y una duda con las direcciones logicas y que hace memoria. si tengo la direccion logica 049. 0 es el indice de mi tabla nivel 1, 4 mi indice de entrada en la tabla 2?

**Comment by LeandroCarbajales** [comment]
Buenas!
La 2da parte estás en lo correcto, pero la dirección lógica no viene dividida de esa manera, para "dividirla" van a necesitar las cuentas que están incluidas en el enunciado.

Saludos!
       Lean

**Comment by matiasferrerovilas** [comment]
Perfecto, muchas gracias
