### ISSUE TITLE
Kernel: transición de estado

### ISSUE THREAD

**Issue by achoquemamani** [sisoputnfrba/foro#2602]
Tengo una duda cuando se pasa de "SUSPENDED-READY" a "READY":

1. Eso implica una llamada del módulo Kernel al módulo Memoria para liberar ese espacio en SWAP? Lo menciono porque es algo que no encontré en el TP

**Comment by LeandroCarbajales** [comment]
Buenas!
Por qué tendrías que liberar algo en SWAP en esa transición?

**Comment by achoquemamani** [comment]
Claro, en el tp dice que "Al ser suspendido un proceso, se debe liberar su espacio en memoria, escribiendo en SWAP ", pero cuando pasa de suspendido a listo, interpreto su acción opuesta, esa información se carga en memoria y en swap se libera, es correcto o cuando pasa de suspendido-listo a listo, solo cargamos la info en memoria pero swap no se libera?

**Comment by RaniAgus** [comment]
¡Buenas! Al igual que como se va a ver más adelante en la teoría, todas las páginas del proceso se encuentran en Swap y se va cargando una copia en Memoria a medida que se van solicitando (sin liberar la página en Swap)

**Comment by martina-facu** [comment]
Yo también tengo una consulta sobre esto aunque no se si estamos hablando de lo mismo. Con mi grupo interpretamos del tp es que podríamos implementar por ejemplo 2 colas que podría ver el planificador de largo plazo una de ready suspendido y otra de new y se fijaria primero en la de ready suspendido ¿Seria correcto pensarlo así?

Otra duda es que no entendemos que pasa cuando un proceso esta en bloqueado suspendido, llegamos a interpretar que la interacción con memoria es que saca las tablas que se le habían asignado cuando estaba en ready pero la verdad que no lo tenemos del todo claro y nos vendría bien una aclaración.

**Comment by LeandroCarbajales** [comment]
Buenas @martina-facu !
Si, esa es la prioridad que indica el enunciado para pasar a ready :)

Con respecto a la interacción con Memoria cuando suspenden un proceso, a efectos del Kernel lo único que les importa es que ese proceso ya no cuente para el "grado de multiprogramación", para la Memoria como aclara el enunciado no hace falta swapear las tablas de páginas, lo que tendrían que hacer es escribir en SWAP las páginas del proceso que sean necesarias y liberar sus marcos.

Les sirve la aclaración?

Saludos!
       Lean

**Comment by achoquemamani** [comment]
Por mi parte sí, muchas gracias @LeandroCarbajales

**Comment by martina-facu** [comment]
Hola @LeandroCarbajales 
Si me sirvió la aclaración, Muchas gracias!

**Comment by RaniAgus** [comment]
¡Buenísimo! Cierro el issue entonces.
