### ISSUE TITLE
(Duda) Modelo Cliente-Servidor

### ISSUE THREAD

**Issue by TomasR264** [sisoputnfrba/foro#2603]
Buenas! Ya logramos que Consola y Kernel esten conectados y que se manden mensajes, pero estamos teniendo dudas sobre como hacer para que Kernel, siendo servidor de Consola, sea tambien cliente de CPU:

Esto seria en simultaneo? Quiero decir, Kernel deberia poder hacer de servidor y cliente a la vez? O sea recibir mensajes de Consola a la vez que le manda mensajes a CPU? O nada mas podra mandarle cosas a CPU una vez que recibio las listas de instrucciones de Consola?

Desde ya muchas gracias! 🚀

**Comment by LeandroCarbajales** [comment]
Buenas!
Claro :), haría de servidor y cliente a la vez al igual que el módulo CPU. El mismo puede conectarse a CPU y a Memoria al iniciar, luego tendrán que usar hilos para poder seguir esperando conexiones de Consolas mientras realiza el resto de sus requerimientos, que incluye cada tanto tener que enviar o recibir mensajes a CPU.

Saludos!
        Lean
