### ISSUE TITLE
[Conexiones] Como cerrar el servidor apropiadamente

### ISSUE THREAD

**Issue by nicolasviegas** [sisoputnfrba/foro#2604]
Buenas, tengo una consulta, ya logre levantar el server de kernel, y que consola se conecte y le envie mensajes, el problema es que el servidor queda levantado, es decir, sigue escuchando a que lleguen mas clientes, como hago para cerrarlo sin ctrl+c y que continue kernel con su ejecucion normal, para que luego pueda hacer de cliente de CPU?

El codigo resumidamente:
``while(server_escuchar(fd_consola));``

 a su vez, dentro de ``server_escuchar`` hay un ``procesar_conexion()`` la cual tiene `` while (cliente_socket != -1)``

Y este ultimo seria el que no deja de iterar y hace que este siga escuchando

**Comment by LeandroCarbajales** [comment]
Buenas!
El Kernel no tiene que dejar de escuchar conexiones de Consolas ya que podrías instanciarlas en cualquier momento. algo similar se respondió en este issue #2603 .
La idea es que pueda realizar estas funciones "a la vez" (mejor dicho, concurrentemente). Por ejemplo, si la función de servidor que espera conexiones de consolas lo tienen en un hilo separado, no tendrían por qué cerrar el servidor.

Saludos!
        Lean

**Comment by nicolasviegas** [comment]
Ya lo entendi, muchas gracias!!
