### ISSUE TITLE
Consulta memoria

### ISSUE THREAD

**Issue by matiasBendayan** [sisoputnfrba/foro#2605]
Hola, que es exactamente lo que tengo que guardar en memoria?
Porque guardar un proceso por lo que vi es guardar un numero como maximo, y si voy a tener una tabla de primer nivel por proceso, no tiene mucho sentido que solo sea un numero, porque como mucho tendria una pagina por proceso. Ademas al solo tener una pagina en el reemplazo de paginas al pasar a suspendido solo tendria que bloquear toda la tabla de paginas de primer nivel sin importar el algoritmo y listo...

**Comment by RaniAgus** [comment]
¡Buenas! Cada proceso tiene un tamaño definido por parámetro. Las instrucciones `READ`, `WRITE` y `COPY` van a operar con direcciones lógicas dentro del rango de ese tamaño (es decir, entre las direcciones lógicas `[0; tamaño - 1]`).

Para ejecutar estas instrucciones, la Memoria debe tener cargada la página correspondiente dentro de los marcos del proceso y la MMU de la CPU deberá traducir esta dirección lógica a física consultando su TLB (y las tablas de páginas de Memoria en caso de ser necesario).

Saludos

**Comment by LeandroCarbajales** [comment]
Solamente para agregar un ejemplo a lo que dice Agus. Fijate que por cada WRITE (o COPY) que se ejecute vas a estar escribiendo algo en la Memoria, por lo que un proceso puede guardar todos los números que entren dado su tamaño.

**Comment by LeandroCarbajales** [comment]
Buenas!
Quedó resuelta la duda?

**Comment by LeandroCarbajales** [comment]
@matiasBendayan Cierro el issue por inactividad, si quedaron dudas lo volvés a abrir :)
