### ISSUE TITLE
Cálculo de la ráfaga de CPU: Cómo implementar el cálculo 

### ISSUE THREAD

**Issue by raquellacruz06** [sisoputnfrba/foro#2606]
Hola buen día! Teníamos una duda al momento de implementar al algoritmo SRT, ya que en el archivo de configuración tenemos 

> Estimación inicial para el cálculo de la primer ráfaga de CPU en milisegundos
 
A cuánto equivale una ráfaga de CPU en segundos? Por ejemplo, 1 ráfaga = 1 segundo? Tomando en cuenta que una ráfaga = 1 instrucción ejecutada. 

Otra opción que planteamos es usar timestamp, uno al iniciar el exec y uno al salir de exec para "medir" la duración real del proceso en ejecución (la diferencia entre tiempo final y tiempo inicial).

Cuál de estas 2 opciones es la mejor?

O por otro lado, queríamos preguntar si es un error del enunciado cuando mencionan ráfaga de CPU en "milisegundos" y realmente estaremos trabajando con ráfagas de CPU y no con tiempo en milisegundos

Acá agregamos otra cita que refiere a las estimaciones de la ráfaga de CPU con SRT pero no aclara cómo deberíamos calcularla (Sabemos que utilizaremos la fórmula vista en clase, pero tenemos esta inconsistencia con los datos a utilizar)

> Al recibir el PCB del proceso en ejecución, se calcularán las estimaciones correspondientes, según indique el algoritmo, para seleccionar el siguiente a ejecutar

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va?

> Otra opción que planteamos es usar timestamp, uno al iniciar el exec y uno al salir de exec para "medir" la duración real del proceso en ejecución (la diferencia entre tiempo final y tiempo inicial).

Esta es la opción correcta, y es la razón por la que la estimación inicial se encuentra expresada en milisegundos en vez de en ciclos de CPU 😋 

Saludos

**Comment by LeandroCarbajales** [comment]
Para sumar a esto, se respondió acá también #2573 :)

**Comment by LeandroCarbajales** [comment]
Buenas!
Quedó resuelta la duda?

**Comment by raquellacruz06** [comment]
Hola! Sí, nos queda claro ahora. Muchas gracias a ambos por la respuesta!!  Saludos :D

**Comment by LeandroCarbajales** [comment]
Buenísimo! Cierro el issue entonces.
