### ISSUE TITLE
IP del kernel

### ISSUE THREAD

**Issue by T-J-Antonio** [sisoputnfrba/foro#2607]
¡Buenos días! Una consulta. El módulo consola conoce la IP del módulo kernel mediante su archivo config. ¿Cómo debería conocer el módulo kernel su propia IP? No existe tal campo en el config del kernel. ¿Deberíamos agregar este campo, o bien definirlo con un `#define`?
Desde ya muchas gracias.

**Comment by ncoen97** [comment]
Buenas! Ambos aproach son valids. Lo unico tengan cuidado con usar la IP 127.0.0.1 para levantar el server, pueden usar la 0.0.0.0 que es similar.

**Comment by T-J-Antonio** [comment]
¡Muchas gracias!
