### ISSUE TITLE
Duda lectura de parámetros

### ISSUE THREAD

**Issue by jschuhmann47** [sisoputnfrba/foro#2608]
Buenas tardes! Con mi grupo hicimos un struct para modelar las instrucciones `char* instruccion, uint32 parametros[2]`. Teníamos una duda cuando otro módulo necesite leer una instrucción. 

Si tenemos una instrucción con un parámetro, al segundo parámetro le asignamos **NULL**, pero vimos en el enunciado que por ejemplo se puede hacer `COPY 0 4`. Si yo comparo **NULL** y 0 son iguales? Estamos con esta duda de como saber si la instrucción tiene un parámetro o dos, porque sino me podría leer una de cero o de un parámetro como una de dos parámetros con 0.

Gracias de antemano

**Comment by dariokozicki** [comment]
Hola! 
Sí, NULL **es** 0.  En el enunciado con cada instrucción corresponden parámetros fijos, así que con saber cuál es, alcanzaría (por ej. EXIT siempre tiene 0, WRITE siempre tiene 2, y así). 
Esto indica que ese struct no sería ideal para representar el modelo, ya que los fuerza a 
1. tener algún número mágico para descartar argumentos innecesarios,  o 
3. tener muchos IFs preguntando "¿Sos exit? Entonces no leo tus argumentos" en varios lugares de todos los programas. 

Fíjense si pueden darle una vuelta de rosca al/los struct/s.
Saludos!
