### ISSUE TITLE
Duda sobre las instrucciones y sus parámetros

### ISSUE THREAD

**Issue by fcafici** [sisoputnfrba/foro#2609]
Hola, una consulta, nos pueden llegar en el archivo de pseudocódigo instrucciones con una cantidad equivocada de parámetros? Por ejemplo : EXIT 2, o NO_OP 5 3 4...
Y si fuera así, qué tendríamos que hacer? Cancelar la ejecución? Omitir esa instrucción?

Gracias de antemano :)

**Comment by RaniAgus** [comment]
¡Buenas! Como comentamos en #2572 y #2582, no es necesario validar la sintaxis del archivo de pseudocódigo (y en el config tampoco) 😄. Si llegan a ver algo erróneo en alguna prueba avísennos porque probablemente debamos corregirlo. Saludos

**Comment by fcafici** [comment]
Ok gracias!
