### ISSUE TITLE
Duda sobre tablas de 1er nivel

### ISSUE THREAD

**Issue by mbertogliati** [sisoputnfrba/foro#2610]
Buenas, desarrollando el módulo de memoria nos surgió una duda: ¿Cuántas tablas de 1er nivel tiene cada proceso? Mi compañero se conectó el sábado al soporte y según lo que le explicaron y él entendió, un proceso puede tener tantas tablas de 1er nivel como se necesiten (es decir, los procesos no tienen límite de tamaño). Sin embargo, de mi parte, mirando distintos issues de este foro leí un par de comentarios que inferían que cada proceso tiene su propia y única tabla de 1er nivel (la apuntada por el PCB), lo cual indicaría que hay un número máximo de páginas que puede tener un proceso (cant_entradas_por_tabla al cuadrado). Esto nos confundió bastante y quisieramos despejar esa duda. Desde ya muchas gracias.

**Comment by LeandroCarbajales** [comment]
Buenas!
Como se ve en las clases de Memoria/Memoria virtual, en paginación cada proceso tiene una única tabla de 1er nivel (la apuntada por el PCB). Capaz a lo que se referían con lo del tamaño, es que no hay un límite definido al tamaño que se pasa cuando instancian una Consola, pero claramente ese tamaño tiene que ser consistente con el direccionamiento máximo de la CPU/Memoria (cant_entradas^2 * tam_página).

Saludos!
       Lean

**Comment by mbertogliati** [comment]
Muchas gracias por la aclaracion!
