### ISSUE TITLE
Consulta: tipo referencia a la tabla de páginas para PCB

### ISSUE THREAD

**Issue by lucas-marmo** [sisoputnfrba/foro#2611]
Buenas! Armando el struct para los PCB nos surgió la siguiente duda al tener que guardar la referencia a la tabla de páginas de primer nivel: de qué tipo tendría que ser esa referencia? 
Aún no conocemos mucho sobre memoria pero necesitamos saber de esto para poder armar el PCB y serializarlo. Por lo que fuimos leyendo, por un lado entendimos que existe una sola tabla de páginas de primer nivel (general), la cuál hará referencia a su vez a muchas tablas de segundo nivel, o sea que lo que guardaríamos en el PCB es la página de la primera tabla referente al proceso dado. Pero por lo que entendemos en la consigna y leímos en otros issues, existen muchas tablas de primer nivel.

Tenemos dos opciones, lo guardamos como un uintX_t o como un puntero (no sabemos de qué tipo). Entendemos que las páginas sí serían números:
>número_página = floor(dirección_lógica / tamaño_página)

pero no sabemos si las tablas de primer nivel (si es que hay más de una) se identifican por un número o debemos pensarlo de otra forma. 

Gracias!

**Comment by LeandroCarbajales** [comment]
Buenas!
En este TP ese "puntero a tabla de páginas" lo representamos con un número, asique pueden usar uint32 perfectamente. Para responder a la duda de Memoria, más allá de que lo verán en clase, cada PCB tiene un puntero justamente porque cada proceso tiene su tabla de páginas de 1er nivel.

Saludos!
       Lean

**Comment by lucas-marmo** [comment]
Gracias!
