### ISSUE TITLE
[CPU] Conexiones con el resto de módulos

### ISSUE THREAD

**Issue by Caruso-Martin** [sisoputnfrba/foro#2612]
Buenas! Tenemos algunas dudas sobre como funcionaria:

1. **Ida y vuelta de PCBs entre el Kernel y el CPU:** logramos mandar un PCB desde el Kernel a la CPU, pero nos preguntábamos como se realiza la comunicación inversa (con el PCB actualizado). ¿Es posible realizar un `send()` desde el CPU (servidor) al Kernel (cliente)? ¿Se debería crear una nueva conexión, donde los roles cliente-servidor se inviertan?

2. **Handshake:** queríamos saber si entendimos bien este proceso. Simplemente, ¿se conecta la Memoria, envía la configuración y se desconecta?

3. **Conexión con la Memoria:** en este caso, estamos dudando que sería lo más conveniente. Por un lado, creemos que se debería abrir y cerrar la conexión con este Módulo, cada vez que se desea ejecutar una instrucción _READ / WRITE / COPY_ para realizar las correspondientes traducciones (y accesos). Por el otro, se podría mantener una conexión constante con este Módulo en un hilo independiente. 

- También nos surge la pregunta de como hacer un ida y vuelta entre CPU y Memoria. Básicamente, **es la pregunta 1**, pero con estos módulos

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va?

1. ¿Llegaron a leer la [guía de Sockets](http://faq.utnso.com.ar/guia-sockets)? Ahí explicamos que la conexión establecida luego del `accept()` es _bidireccional_ (o peer to peer), o sea, ambos procesos pueden enviarse `send()` y `recv()` sin importar quién aceptó la conexión.
2. La idea de handshake (que también está explicada con más detalle en la guía de sockets) es enviar un mensaje para que ambos procesos sepan quién es quién antes de continuar con la conexión.
3. Si les es más cómodo abrir y cerrar la conexión por cada request pueden hacerlo, aunque... ¿qué uso pensaban darle a esa 2da conexión constante?

Saludos

**Comment by Caruso-Martin** [comment]
Primero que nada, gracias por la respuesta. 

En su momento leí la Guía de Sockets (hace un laaaaargo tiempo) pero se ve que se me escapo el dato que la comunicación era bidireccional. Ya re-leí el texto y pude refrescar ese concepto, y entender el mecanismo del _Handshake_ por suerte.   

Respecto a la ultima pregunta, estos últimos días estuvimos discutiendo los requerimientos y estábamos pensando en alternativas para implementar el funcionamiento de la MMU. La duda en cuestión es porque no sabemos que es más conveniente de estas soluciones:

1. Primero abrir una conexión con Memoria para realizar el _Handshake_ y cerrar dicha conexión. Después, abrir y cerrar conexiones con Memoria por cada instrucción que requiera una traducción (_READ / WRITE / COPY_)  
2. Primero abrir una conexión con Memoria (en un hilo independiente) para realizar el _Handshake_ y  **NO** cerrar dicha conexión. Después, este hilo esperara al momento que una instrucción requiera una traducción y este la realiza.

Por el momento, me inclino más por la primer alternativa por la "secuencialidad" que existe en todo el mecanismo descripto. Lo único que no me termina de gustar es la idea de tener que abrir y cerrar conexiones "a lo loco", a mis ojos parece ineficiente.

Quizás mantener un hilo independiente abierto todo el tiempo (como la 2da solución) puede no ser eficiente, pero tampoco ejecutaría nada.

**Comment by LeandroCarbajales** [comment]
Buenas!
Por qué ven la necesidad de un hilo extra para mantener la conexión con Memoria? Pueden abrir la conexión, realizar el handshake y luego hacer los send()/recv() cuando sea necesario ya que la ejecución es secuencial. Por supuesto que tener un hilo extra como el que plantearon también es una solución válida :), pero capaz se están complicando la implementación sin necesidad.

Saludos!
       Lean

**Comment by Caruso-Martin** [comment]
¡Listo, entonces! Implementaremos esa solución entonces. ¡Muchas gracias a ambos!
