### ISSUE TITLE
Comunicacion Kernel - CPU

### ISSUE THREAD

**Issue by TomasR264** [sisoputnfrba/foro#2613]
Buenas! Tenemos una duda un poco tonta respecto a esta parte del enunciado:

>Durante el transcurso de la ejecución de un proceso, se irá actualizando su PCB, que luego será devuelto al Kernel bajo los siguientes escenarios: finalización del mismo (instrucción EXIT), necesitar ser bloqueado (instrucción I/O), o deber ser desalojado (interrupción).

Esto querria decir que hay que mandarle el PCB una vez modificado de vuelta a Kernel, ya que CPU es servidor de Kernel, habria que hacerla una variable global al PCB para que Kernel pueda acceder a esta despues de que CPU la modifica? O como podriamos mandarla sino?

Desde ya muchas gracias! 🚀

**Comment by RaniAgus** [comment]
¡Buenas! Tranqui, no existen dudas tontas, siéntanse libres de preguntar lo que necesiten 😄 

> habria que hacerla una variable global al PCB para que Kernel pueda acceder a esta despues de que CPU la modifica?

Los 4 módulos del TP son procesos separados, por lo que no comparten variables globales.

>  O como podriamos mandarla sino?

¿Llegaron a leer la [guía de Sockets](http://faq.utnso.com.ar/guia-sockets)? Ahí explicamos que la conexión establecida luego del `accept()` es _bidireccional_ (o peer to peer), o sea, ambos procesos pueden enviarse `send()` y `recv()` sin importar quién aceptó la conexión.

Saludos

**Comment by TomasR264** [comment]
> ¡Buenas! Tranqui, no existen dudas tontas, siéntanse libres de preguntar lo que necesiten 😄
> 
> > habria que hacerla una variable global al PCB para que Kernel pueda acceder a esta despues de que CPU la modifica?
> 
> Los 4 módulos del TP son procesos separados, por lo que no comparten variables globales.
> 
> > O como podriamos mandarla sino?
> 
> ¿Llegaron a leer la [guía de Sockets](http://faq.utnso.com.ar/guia-sockets)? Ahí explicamos que la conexión establecida luego del `accept()` es _bidireccional_ (o peer to peer), o sea, ambos procesos pueden enviarse `send()` y `recv()` sin importar quién aceptó la conexión.
> 
> Saludos


Perfecto, muchas gracias!
