### ISSUE TITLE
Duda sobre ráfagas de ejecución y SRT

### ISSUE THREAD

**Issue by matiaspar2000** [sisoputnfrba/foro#2614]
Buenas, teníamos una duda a la hora de implementar el algoritmo SRT en Kernel. Para sacar la ráfaga de ejecución de un proceso pensábamos en tomar un timestamp a la entrada del estado EXEC y otro a la salida. 
Este timestamp por ahora lo tenemos en segundos pero nos surgió la duda de qué tanta precisión debe tener la ráfaga, si así es suficiente o habría que cambiarlo a que mida en milisegundos. Muchas gracias.

**Comment by LeandroCarbajales** [comment]
Buenas!
Usen milisegundos para todo lo que es duración de ráfagas y estimación de SRT, la estimación inicial por archivo de configuración también es en milisegundos.

Saludos!
      Lean

**Comment by matiaspar2000** [comment]
OK. Muchas gracias.
