### ISSUE TITLE
TLB y su estructura

### ISSUE THREAD

**Issue by Juyah** [sisoputnfrba/foro#2615]
Hola, tenemos una duda con respecto al enunciado:
```
TLB
Para agilizar el proceso de traducción, el módulo CPU contará también con una caché TLB. La misma deberá tener obligatoriamente la estructura [ página | marco ] y se definirá por archivo de configuración:
- La cantidad de entradas
- El algoritmo de reemplazo, que puede ser FIFO o LRU.
```

La estructura que aparece obligatoriamente es tener [ página | marco ], esto nos llevó a pensar que al no tener el ID del proceso o la tabla de nivel 1 asociada a esa página tendríamos que hacer lo siguiente: (_Teniendo en cuenta el archivo config_)

La pagina que se guardaría sería de [0 - 255] ( 16 procesos máx * 16 páginas que pueden tener). Por lo tanto para saber que tabla de paginas de primer nivel habría que hacer lo siguiente:
numero de la tabla de paginas de primer nivel =  floor (página / 16)
página de la tabla = página mod 16
Tomando en cuenta el numero de pagina 50 esto nos quedaría ID = 3 y Página = 2
Para no tener que realizar esto, no se podría agregar a la estructura la tabla de primer nivel quedando [NroTabla1 | página | marco]

Saludos.

**Comment by LeandroCarbajales** [comment]
Buenas!
Les recomendaría que le peguen una repasada (o esperen a verlo en clase) al concepto de TLB, porque la idea es justamente no tener que acceder a las tablas de páginas si tenemos la traducción ya guardada en TLB. Al no haber una columna para id del proceso en la tabla indica que (para este TP) siempre será local al proceso en ejecución.

Saludos!
       Lean

**Comment by Juyah** [comment]
Buenas Lean, si no entendí mal tendríamos una TLB por proceso entonces?

**Comment by LeandroCarbajales** [comment]
Buenas!
No, la TLB es una caché de la CPU por lo que hay una sola, en todo caso tendrían que vaciarla ante cada cambio de proceso al igual que como se ve en clase :)

**Comment by Juyah** [comment]
Okay, entiendo entonces que al ser una TLB sin ASIDs lo que tenemos que hacer es realizar el flush correspondiente al proceso actual. Si es correcto, cierro el issue.

**Comment by LeandroCarbajales** [comment]
Correcto :)
