### ISSUE TITLE
Dudad sobre tamaño de datos a escribir en memoria

### ISSUE THREAD

**Issue by mbertogliati** [sisoputnfrba/foro#2616]
Hola, abro un issue nuevo para que quienes tengan la misma duda que yo se les haga más fácil encontrarlo,.
Tenemos una duda, porque en el enunciado dice:
> Todos los valores a leer/escribir en memoria serán numéricos enteros no signados de 4 bytes

Pero en el issue #2591:
> Desde la CPU ya sabés de antemano que estás accediendo a 2 páginas distintas (porque el desplazamiento + 4 bytes se pasa del tamaño de página), por lo que tendrás que hacer 2 traducciones, una de las traducciones terminaría diciéndole a la memoria "dame 2 bytes desde el 6" y la otra traducción terminaría diciéndole "dame 2 bytes desde el 16".

Esto nos confunde ya que en el caso de que una página no alcance para completar la lectura o la escritura, el CPU partirá el dato en 2 y mandará a escribir un valor menor a 4 bytes en una página y otro también menor a 4 bytes en otra.

**Comment by ncoen97** [comment]
Buenas!
Ambas afirmaciones son correctas, solo que la primera se ve más "desde afuera" para denotar que no se van  guardar strings, booleanos o otros tipos de datos que no sean enteros, mientras que la segunda entra más en detalle de la implementación del módulo.
Saludos.

**Comment by mbertogliati** [comment]
Muchas gracias por la respuesta! De paso otra duda: Tanto el modulo cpu como el de la memoria implementan un solo hilo de ejecucion? o eso esta a criterio nuestro? Muchas gracias

**Comment by ncoen97** [comment]
No, ambos van a necesitar multiples hilos. En principio los relacionados a conexiones, luego dependerá de cómo lo implementen.
Saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

La CPU va a ser 1 sola, el tener varios hilos puede servirles por ejemplo para escuchar el aviso de interrupciones que vengan desde el kernel.

Saludos.-

**Comment by mbertogliati** [comment]
Muchas gracias! Entonces ya cierro el thread. Muchas gracias por siempre estar ayudando y respondiendo rapido
