### ISSUE TITLE
CPU - Duda sobre el rol de traducir direcciones en operaciones Read/Write

### ISSUE THREAD

**Issue by pabloquinci** [sisoputnfrba/foro#2617]
Buenas que tal? Tengo una duda con esta parte del enunciado:

> A la hora de traducir direcciones lógicas a físicas, la CPU debe tomar en cuenta que el esquema de memoria del sistema es de Paginación de 2 niveles. Por lo tanto, las direcciones lógicas se compondrán de la siguiente manera:
[entrada_tabla_1er_nivel | entrada_tabla_2do_nivel | desplazamiento]
>Estas traducciones, en los ejercicios prácticos que se ven en clases y se toman en los parciales, normalmente se hacen en binario. Como en la realización del trabajo práctico es más cómodo utilizar números enteros en sistema decimal, y tomando en cuenta que las tablas tanto de 1er nivel como de 2do nivel tendrán la misma cantidad de entradas, la operatoria sería más parecida a la siguiente:
número_página = floor(dirección_lógica / tamaño_página)
entrada_tabla_1er_nivel = floor(número_página / cant_entradas_por_tabla)
entrada_tabla_2do_nivel = número_página mod (cant_entradas_por_tabla)
desplazamiento = dirección_lógica - número_página * tamaño_página

Ahí especifica cómo se calculan núm. de pagina, tabla de primer nivel, etc. Por qué si ya tengo en el PCB la tabla de primer nivel para ir a buscar todo lo demás a Memoria debería hacer esos cálculos en la MMU? O es solamente a modo informativo?

>Como el único dato de la memoria que tenemos en el PCB es la tabla de páginas de 1er nivel del proceso, en total deberemos realizar 3 accesos a memoria para realizar la traducción:
Un primer acceso para conocer en qué tabla de páginas de 2do nivel está direccionado el marco en que se encuentra la página a la que queremos acceder
Un segundo acceso para conocer en qué marco está la misma
Finalmente acceder a la porción de memoria correspondiente (la dirección física).

Acá por qué se hacen 3 accesos para obtener un dato? Con uno solo no alcanza, o sea accediendo con la tabla de 1er nivel?

Gracias

**Comment by RaniAgus** [comment]
¡Buenas! El motivo es el mismo que comentaba Lean en https://github.com/sisoputnfrba/foro/issues/2586#issuecomment-1110196414: en un sistema real, y como vemos en clase, el módulo Memoria solamente se encarga de devolver el contenido que se encuentra en la dirección solicitada, y la CPU (a través de la MMU) es la encargada de realizar la traducción de dirección lógica a física.

En realidad el tener tablas de páginas en una estructura aparte es una simplificación: una implementación más cercana a la realidad sería tener las tablas de páginas también dentro del `void*` y que la CPU vaya consultando esas direcciones físicas, pero creemos que eso le agregaría una complejidad extra que no aporta demasiado al aprendizaje.

Saludos

**Comment by pabloquinci** [comment]
Gracias!

**Comment by LeandroCarbajales** [comment]
Buenas!
Exactamente :), uno de los objetivos del TP es entender el proceso de traducción de direcciones como vemos en clase. La diferencia es que en este TP algunos pasos están simplificados para darle enfoque a la parte algorítmica y de estructuras, por ejemplo, todo lo que hace al "page fault" lo hacemos "sincrónico y no bloqueante", dicho de otra manera, lo hace el módulo Memoria por su cuenta, ahorrándonos toda la parte de bloquear al proceso, replanificar y tener que reejecutar la instrucción luego.

Se entiende la idea?

Saludos!
     Lean
