### ISSUE TITLE
Duda manejo de PCB en CPU

### ISSUE THREAD

**Issue by TomasR264** [sisoputnfrba/foro#2618]
Buenas! Estamos mandando el PCB del proceso de Kernel a CPU y nos surgieron unas dudas

Habiendo visto el issue #2567 sabemos que solo haria falta pasarle el "contexto de ejecucion" a CPU, y no el PCB completo, esto que parte del PCB seria? Por que estamos teniendo problemas para mandarle el PID a la vez que las instrucciones, y creemos que el PID es necesario que CPU lo conozca tambien, pero no estamos seguros.

Desde ya muchas gracias!

**Comment by nahuemazzeo** [comment]
Hola @TomasR264!! Como andas?

Lo que indica el bug que indicas es que no es necesario enviar todo el PCB, que eso no implica que no puedan hacerlo. En el bug se indica:

> 1- No es necesario enviar todo, conceptualmente uno lo que necesita en la CPU es el "contexto de ejecución" y no el PCB entero, **_a nivel implementación del TP enviando todo es más difícil equivocarse y capaz se ahorran algún que otro chequeo del lado del Kernel._**

Ahora, la frase **contexto de ejecucion** entiendo que hace referencia a las cosas que solo necesita el CPU y no todo el PCB. Es una simple definicion que pusimos nosotros y capaz confunde.

Dicho esto, que problemas estan teniendo para mandar el PID y las instrucciones. ¿Es un problema de serializacion? Si nos indicas el problema capaz podemos ahondar en eso y solucionarlo.

Saludos.

**Comment by TomasR264** [comment]
Te paso la parte del codigo que esta causando problemas:
```

while (cliente_socket != -1) {

              if (!recv_pid_to_cpu(cliente_socket, &pid)) {
             log_error(log_cpu, "Fallo recibiendo pid");
             break;
             }
             log_warning(log_cpu,"El pid despues del recv es: %d",pid);

             if (recv(cliente_socket, &cop, sizeof(op_code_instrucciones), 0) != sizeof(op_code_instrucciones)) {

                 log_info(log_cpu, "El cliente se desconecto");

                    log_trace(log_cpu,"El socket de cpu despues de grar conexiones es: %d",fd_cpu);


                   return;
             }
                log_warning(log_cpu,"El codigo de operacion despues del recv es: %d",cop);
                switch (cop) {
                contador_instrucciones = 0; //esta variable es para ir modificando el PC
                    case NO_OP:{
                       // log_info(log_cpu, "entre al case NO_OP");
                        break;
                    }
                    case IO:{
                        //log_info(log_cpu, "entre a IO");
                        break;
                    }
                    // Errores
                    case -1:
                        log_error(log_cpu, "Cliente desconectado de %s...", server_name);
                        return;
                    default:
                        log_error(log_cpu, "Algo anduvo mal en el server de %s", server_name);
                        log_info(log_cpu, "Cop: %d", cop);
                        return;
                }
     }
    log_warning(log_cpu, "El cliente se desconecto de %s server", server_name);
    return;
}

```
Lo que esta pasando es que estamos recibiendo el pid del primer proceso, que lo recibe bien, pero despues cuando va el segundo recv, que seria para el codigo de operacion, para la primera instruccion, cuando entra por NO_OP, funciona bien, pero cuando hace el break y vuelve a iterar el primer recv (el del pid), entra por ahi y se le asigna el codigo de operacion de una instruccion a un pid, y por tanto se nos rompe todo el switch

**Comment by RaniAgus** [comment]
¡Buenas! Para estar seguro, ¿cómo está conformado el payload del paquete? Según entendí es algo como:

```
+---------+--------------------------+---
| pid     | op_code_instrucciones[N] | etc...
| int32_t | int32_t * N              |
+---------+--------------------------+---
```

Quizás pueden intentar hacer algo similar a lo que sugerimos en la [guía de serialización](http://faq.utnso.com.ar/guia-serializacion) para _estructuras dinámicas_, o sea, pueden enviar primero un `uint32_t` que indique la cantidad instrucciones a leer y del otro lado recibirlo para luego hacer un `for` que haga N `recv`s:

```
+---------+----------+--------------------------+---
| pid     | N        | op_code_instrucciones[N] | etc...
| int32_t | uint32_t | int32_t * N              |
+---------+----------+--------------------------+---
```

Saludos

> Nota: Me tomé el atrevimiento de editar el comment para indentar el código y que se lea mejor 😉
