### ISSUE TITLE
Problemas Console Module & string_array_push

### ISSUE THREAD

**Issue by Gdepablo** [sisoputnfrba/foro#2619]
string_array_push y el buffer se vuelven locos y ponen basura.

![image](https://user-images.githubusercontent.com/44046974/167043122-f2ade8e8-8923-4ddf-9243-33a1e5711d41.png)
![image](https://user-images.githubusercontent.com/44046974/167043128-6ba5e81b-9cbd-4585-8c9e-11e74b0baa1b.png)

El problema es que no sabemos por qué pasa porque cuando imprimimos buffer medio que lo imprime bien. 

Luego un par de dudas generales:

En el punto 1, en consola,el NO_OP 5 lo resuelve la consola o el kernel el tema de las iteraciones? onda consola manda 5 NO_OP o el kernel resuelve la parte iterativa
2-Usar el if con el else break es muy fulero ( o sea si usar el break del if es ilegal o sirve, y con ilegal me refiero a algo que no se deberia hacer)
3-como podemos resolver el tema de que el string_append si le pasamos (&buffer , &c)  nos devuelve porqueria (El motivo principal de este post junto con lo de string_array_push)

Si borramos el free(buffer); porque lo estamos creando localmente, entonces funciona, pero con el free imprime basura y no sabemos por qué.

**Comment by Gdepablo** [comment]
También probamos haciendo malloc y después de que haga toda la lógica hacer free(buffer); pero tira segmentation fault entonces estamos un toque perdidos

**Comment by iago64** [comment]
Buenas! Cómo va?

Antes que nada, no esta de mas recordar que los ayudantes **no somos compiladores humanos** y no podemos resolver una duda viendo una foto del código y si quisiéramos replicar el error simplemente nos va a llegar mucho tiempo el estar copiando a mano todo el código, con lo cual, ayúdanos a ayudarte y copia el código _completo_, porque si no con ese fragmento solo puedo tirar conjeturas en el aire ☺️ 

Respecto al error, cuando haces un [`string_new()`](https://github.com/sisoputnfrba/so-commons-library/blob/1136796838552318f475352a5983d926d16cc967/src/commons/string.c#L50) lo único que estas generando es un string vacío, con lo cual después cuando haces el `strcpy()` tenes el problema de que estas pisando memoria a lo pavote con lo que tengas en buffer, ya que `strcpy()` no reserva memoria mágicamente, tenes que reservarla vos y es posiblemente que ahi es donde se te empieza a "llenar" de "basura"

Otra cosa que me llama la atención es que estas usando funciones como `strtok()` cuando tenes `string_split()` o `strcpy()` cuando tenes `string_duplicate()` de las commons que hacen lo mismo y te van a ayudar a ser mas "claro" con el código y ademas estan pensadas para laburar con el `string_new()` 😉 

Saludos.-

**Comment by Gdepablo** [comment]
Sobre lo de arriba, mis compañeros lo resolvieron en soporte. Esto es una duda más personal pero, me llama la atención por qué la lectura funciona con fgets (y en teoría, si le tirás el print entre string_array_push y la reasignación de punteroAuxiliar ves que queda bien grabado, pero al momento en que vos querés consultar los valores desde afuera, entonces bam, te muestra EXIT EXIT EXIT EXIT
No sé si me explico, pero quería saber si entendían por qué pasaba esto. Saludos!

#include "consola.h"



int main(int *argc, char argv){
    if( argc != 3 ) {
        printf("cantidad de parametros incorrecta \n");
        return EXIT_FAILURE;
    }

    char* buffer = string_new();
    char* listaInstrucciones = string_array_new();
    FILE* archivo = fopen(argv[1], "r");

    fseek(archivo, 0L, SEEK_END);
    int size = ftell(archivo);

    rewind(archivo);

    char* punteroAuxiliar = fgets(buffer, size, archivo);
    int i = 0;

    while( punteroAuxiliar != NULL ){
        string_array_push(&listaInstrucciones, buffer);
        printf("%s \n", listaInstrucciones[i]); //Acá lee BIEN.
        punteroAuxiliar = fgets(buffer, size, archivo);
        i++;
    }

    size = string_array_size(listaInstrucciones);
    for(int i = 0; i < size; i++) { //acá lee MAL
        printf("%s \n", listaInstrucciones[i]);
    }

    free(archivo);
    return EXIT_SUCCESS;
}

**Comment by RaniAgus** [comment]
¡Buenas! Si revisamos el manual de [fgets](https://man7.org/linux/man-pages/man3/fgets.3p.html) (lo cual aconsejo hacer siempre que usemos cualquier función de la biblioteca de C) vamos a ver lo siguiente:

> ```c
> char *fgets(char *restrict s, int n, FILE *restrict stream);
> ```
> The fgets() function shall read bytes from `stream` into the array
       pointed to by `s` until `n`-1 bytes are read, or a <newline> is read
       and transferred to s, or an end-of-file condition is encountered.

Es decir, el primer parámetro `s` es un puntero al lugar en donde se va a guardar lo leído, y el segundo parámetro `n` es el máximo a leer si no se llega antes a un `\n`.

Esto es porque `s` debe tener la memoria ya reservada y `n` le indica a la función que no se pase en caso de que la línea sea muy larga.

Si reservás solamente un string vacio en `s` (de 1 byte) y le pasás a `n` el tamaño del archivo corrés el riesgo de corromper la memoria si la línea es más larga que 1 byte. Lo correcto sería primero reservar el `buffer` con `malloc` y luego pasarle el tamaño reservado como segundo parámetro.

También aclara que el `\n` **es transferido** a `s`, así que todos los strings que guardes lo van a tener. Tenelo en cuenta antes de continuar con el parseo.

Otro aspecto a tener en cuenta que `string_array_push()` guarda un string existente en el array, no una copia, por lo que si pusheás varias veces `buffer` vas a tener un array de punteros apuntando hacia el mismo string.

Por último, te aconsejo revisar los errores y **los warnings** del compilador: estos últimos son un buen indicativo de estar pifiándola con los tipos. También usar el [debugger](https://faq.utnso.com.ar/video-eclipse-debugging) te puede ayudar a monitorear las variables en todo momento y encontrar los bugs más rápido.

Saludos

**Comment by Gdepablo** [comment]
Mi duda es; hasta donde yo sé, string_new() no hacía un malloc adentro de la función? La otra sería, si las líneas son dispares, cómo le digo a "n" el límite? O sea nosotros pusimos el tamaño de todo el archivo porque nos pareció lo lógico, total siempre va a encontrar un /n, un /0 u un NULL para cortar, entonces, ¿habría que, en todo caso, corregir eso? 
Lo otro, entonces, para usar fgets deberíamos crear distintos strings para las distintas líneas para que el string_array_push haga lo propio o hacerlo a la antigua escribiéndolo con un for que itere "i" y vaya asignando los elementos?

**Comment by RaniAgus** [comment]
> Mi duda es; hasta donde yo sé, string_new() no hacía un malloc adentro de la función? 

Sí, pero como dijo Dami, guarda un string vacío, por lo que el `malloc()` es de solo 1 byte; y las instrucciones miden más que eso.

> La otra sería, si las líneas son dispares, cómo le digo a "n" el límite? O sea nosotros pusimos el tamaño de todo el archivo porque nos pareció lo lógico, total siempre va a encontrar un /n, un /0 u un NULL para cortar, entonces, ¿habría que, en todo caso, corregir eso?

No veo mal tomar el tamaño de todo el archivo como el "n" ya que como bien decís les asegura que siempre corte antes del `\n` o el fin del archivo, pero recuerden que el `buffer` debe tener esa memoria ya reservada.

> Lo otro, entonces, para usar fgets deberíamos crear distintos strings para las distintas líneas para que el string_array_push haga lo propio o hacerlo a la antigua escribiéndolo con un for que itere "i" y vaya asignando los elementos?

No entendí la segunda opción, aunque la primera suena bien: sí deben crear distintos strings para cada línea para evitar escribir sobre la misma dirección de memoria y terminar con solo la última instrucción.

**Comment by Gdepablo** [comment]
Con lo del for, me refiero a escribirlo a la antigua.
O sea agarro por ej el array listaInstrucciones y le digo

for (int i=0, i < sizeof(listaInstrucciones), i++) 
listaInstrucciones[i] = valor }

Algo así. La cuestión es que si creamos distintos strings para cada uno, estaríamos repitiendo no sólo bocha de lógica, sino que también sería medio imposible porque sería parecido a hardcodear posición por posición el valor (Si tenemos un file con 50 instrucciones entonces hardcodear 50 líneas)
No sé si me estoy explicando bien, pero no me parece rentable

**Comment by iago64** [comment]
Buenas! Cómo va?

Ahora que recuerdo algo que le comente a tus compañeros que podían hacer era por ejemplo levantar el archivo, pasarlo a una variable nueva y usar [`string_split()`](https://github.com/sisoputnfrba/so-commons-library/blob/1136796838552318f475352a5983d926d16cc967/src/commons/string.c#L146) con el caracter `'\n'` para separar las líneas de las instrucciones, ya que esa función les va a devolver el array de instrucciones. 
Es muy útil que se tomen un ratito y revisen todas las funciones de las commons, porque generalmente este tipo de problemas "comunes" ya tienen una solución y se las facilitamos mediante las commons :wink:

Saludos.-

**Comment by Gdepablo** [comment]
Claro, entiendo su utilidad, pero eso haría que el string_array_push con el fgets funcionase? O seguiría guardando EXIT EXIT EXIT EXIT?

**Comment by iago64** [comment]
Buenas! Cómo va?

Creo que no estas viendo que la solución de usar [`string_split()`](https://github.com/sisoputnfrba/so-commons-library/blob/1136796838552318f475352a5983d926d16cc967/src/commons/string.c#L146) con el caracter `'\n'` te resuelve directamente todo y no te hace falta el `string_array_push()`, porque el mismo `string_split()` ya te devuelve el array de instrucciones y después lo único que tendrías que hacer es simplemente agarrar e iterar el array que te devolvió el `string_split()`

Saludos.-
