### ISSUE TITLE
Enviar PCB Kernel - CPU

### ISSUE THREAD

**Issue by DamianArielLerner** [sisoputnfrba/foro#2620]
Hola buenas, nosotros teníamos pensado mandar el pcb con la función agregar paquete del tp0, parecido a eso de ir agregando parámetro por parametro, y de la lista de instrucciones también de cada elemento de la lista parámetro por parametro. Pero pensándolo bien, son muchos memcpy, no hay una forma más sencilla de mandar la estructura pcb, si solo voy a agregar todos los datos del mismo en un paquete, en una sola instancia? Gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Te recomiendo que le pegues una revisada al video de la [charla de serialización que dábamos allá por el 2019](https://www.youtube.com/watch?v=GnuurOt8yqE&ab_channel=UTNSO).

La serialización es algo que tienen que definir uds y el como hacerlo depende de su ingenio, pero no quita el hecho de que posiblemente si, tengan varios `memcpy()` tanto para serializar como para des serializar, es un poco parte del problema de trabajar con lenguajes tan "acotados" como C.

De todas formas, solo para que tengan una idea, uds ya deberían haberle mandado al Kernel la lista de instrucciones desde la consola, con lo cual, no deberían estar tan lejos de lo que necesitan para mandarlo del Kernel a la CPU.

Saludos.-

**Comment by DamianArielLerner** [comment]
Perfecto, pero entonces el Attribute packed para que serviría? No está relacionado un poco con lo que quiero conseguir al no utilizar tantos `memcpy()`?

**Comment by iago64** [comment]
Buenas!

El `__attribute__((packed))` como comentamos en el video, lo que hace es eliminar el padding, pero nada mas, si tenes una estructura compleja con cosas reservadas dinámicamente, no te queda otra que serializar y por consecuente, realizar todos los `memcpy()`.

Saludos.-

**Comment by DamianArielLerner** [comment]
Buenísimo entonces, seguiremos con la idea original! Mil gracias!
