### ISSUE TITLE
Duda actualizacion de la estimacion de la rafaga

### ISSUE THREAD

**Issue by AlejoGol** [sisoputnfrba/foro#2621]
Buenas, entiendo q cuando un pcb sale de cpu por IO ahí se calcularía la estimación de la próxima ráfaga con el calculo q usa el valor alpha dado en el config, pero mi consulta seria, cuando se desaloja un pcb de cpu por interrupción, ahí también se actualiza la estimación de la ráfaga?
Y si es q se actualiza debería ser con el calculo q usa el alpha o haciendo algo como "tiempo estimado - tiempo real" ya q realmente no usó todo su tiempo estimado y en la practica de la teoría en clase se ve de esta forma? En el segundo caso igual habría q guarda la estimación anterior para el próximo calculo con el alpha.

### 📔 Citas del enunciado/videos
Al recibir el PCB del proceso en ejecución, se calcularán las estimaciones correspondientes, según indique el algoritmo, para seleccionar el siguiente a ejecutar.

**Comment by iago64** [comment]
Buenas! Cómo va?

Siempre que sacan un PCB de la CPU tienen que recalcular las estimaciones, porque justamente tienen que ver si vuelve ese proceso o entra uno de los nuevos 😉 

Saludos.-

**Comment by LeandroCarbajales** [comment]
Para responder específicamente a esto:
> "Y si es q se actualiza debería ser con el calculo q usa el alpha o haciendo algo como "tiempo estimado - tiempo real" ya q realmente no usó todo su tiempo estimado y en la practica de la teoría en clase se ve de esta forma?..."
Claro, la lógica es la misma que se ve en clase en los ejercicios de plani, el cálculo de estimación es para estimar ráfagas, en caso de que la ráfaga no haya terminado (por interrupción justamente) solamente tienen que ver cuánto le falta a lo que estimaron para esa ráfaga.

Saludos!
      Lean

**Comment by LeandroCarbajales** [comment]
@AlejoGol Te sirvieron las respuestas? Te resolvió la duda?

**Comment by iago64** [comment]
Buenas! @AlejoGol te quedó alguna duda? Hay algo que no se entienda de la respuesta de Lean?

Saludos.-

**Comment by AlejoGol** [comment]
Buenas, muchas gracias por las respuestas!!!!!
