### ISSUE TITLE
Dudas TLB & Páginas primer nivel

### ISSUE THREAD

**Issue by jlsuh** [sisoputnfrba/foro#2622]
Muy buenas a todos :) dejo un par de consultas:

1) Haciendo referencia a la TLB:
  a) ¿Hay una imagen por cada proceso y cada vez que se ejecute en la CPU se debe cargar dicho "contexto" en la TLB (teniendo en cuenta que siempre estará en ejecución 1 solo proceso, debido a que la CPU es monoprocesador)?
  b) ¿O es una TLB a nivel global?

- En caso de que sea a): ¿este "contexto" debe estar en el PCB, o en su defecto estar en alguna estructura aparte que nos guarde esta información?
Entendemos que al tenerlo de esta manera se podría decir que tenemos los datos de una TLB por cada proceso. 
- En caso de que sea b): ¿se requiere estar cargando y descargando (_flusheando_) las entradas de la TLB global?

Nos surgió esta duda debido a que serían estrategias parecidas pero difieren en su implementación.

2) Las tablas de paginas de primer nivel, cuando se suspende un proceso, puede darse el caso en que el número de tabla de páginas (de primer nivel) cambie cuando un proceso vuelve de suspendido a memoria (Swap-in)? O siempre se supone que dicho índice de la lista (índice tabla de primer nivel) es fija y no varía durante todo el ciclo de vida del proceso?

**Comment by LeandroCarbajales** [comment]
Buenas!
Les recomendaría que le peguen una repasada (o esperen a verlo en clase) al concepto de TLB ya que su implementación es muy similar a como se ve en clase y en los ejercicios.
Con respecto a las tablas, si puede cambiar o no su número de tabla de páginas depende de la implementación que tome el equipo. Como aclara el enunciado, en este TP no es necesario swapear ni eliminar tablas, por lo que en principio no cambiaría su número.

Saludos!
       Lean
