### ISSUE TITLE
Duda desalojos SRT e interrupciones

### ISSUE THREAD

**Issue by jlsuh** [sisoputnfrba/foro#2623]
Muy buenas :)

## Duda
Cuando llega un nuevo proceso a ready: ¿se debe considerar mandar _N interrupciones_ consecutivas (Kernel->CPU), por ende también llevar a cabo _N desalojos_ (CPU->Kernel), siendo _N_ la cantidad de "procesos allegados a ready"? ¿O es suficiente considerar enviar solamente 1 interrupción (Kernel->CPU), por ende también 1 solo desalojo (CPU->Kernel), llevando a cabo 1 sola replanificación en base a SRT para todos aquellos "procesos allegados a ready" (por algún motivo del destino) que haya en el momento?

**Comment by iago64** [comment]
Buenas! Cómo va?

Si llegando 1 proceso a ready, te alcanza con mandar 1 sola interrupción a la CPU para desalojar el proceso que este en ese momento en EXEC y una vez desalojado actualizas las estimaciones y envías el que corresponda según el algoritmo SRT, tal cual lo vieron en clase.

Saludos.-
