### ISSUE TITLE
Duda Kernel - Cambio de BLOCKED a READY

### ISSUE THREAD

**Issue by NahuelFarias** [sisoputnfrba/foro#2624]
Buenas!
Viendo el enunciado del TP, veo que en una parte se menciona que la cola de SUSPENDED-READY tiene mas prioridad que la cola de NEW para pasar sus PCBs  a READY, pero en ningún momento se menciona a la cola de BLOCKED, y segun veo en el Diagrama de 7 estados, esta también pasa sus PCBs a la cola READY.

Cual seria entonces el orden de prioridad final?
Mas que nada saber si la cola de BLOCKED también será tomada dentro del conjunto de colas que pueden pasar sus PCBs a READY.

### 📔 Citas del enunciado/videos

> Es importante tener en cuenta que un proceso en estado SUSPENDED-READY tendrá más prioridad para entrar a la cola READY que los procesos en NEW, cuando el grado de multiprogramación lo permita.

> ![image](https://user-images.githubusercontent.com/48612415/167266008-f07bee16-37de-4fa4-8600-6a83ee8c0438.png)

**Comment by LeandroCarbajales** [comment]
Buenas!
Como dice en la cita del enunciado esta prioridad entre las colas NEW y SUSPENDED-READY es para pasar a los procesos a la cola READY "...cuando el grado de multiprogramación lo permita." La transición de BLOCKED->READY no modifica el grado de multiprogramación por lo que no compite contra esas dos.

Queda más clara la duda?

Saludos!
        Lean

**Comment by NahuelFarias** [comment]
Quedo claro Lean, gracias!

Cierro el issue.

Saludos! 🦾
