### ISSUE TITLE
Consulta discord

### ISSUE THREAD

**Issue by Schmidt-mat** [sisoputnfrba/foro#2625]
Buenas, ingresé al discord para los sábados de consulta y esperé 2 horas, de 1 a 3 de la tarde pero ningún ayudante se sumó a la sala de voz. El cuatri pasado me podía sumar a una lista controlada por el bot para sacar turno, pero lo único que me aparece es rules y lobby. Entré y esperé desde que terminó la clase hasta que se fueron todos los ayudantes, no sé si no tengo permisos para ver lo del bot con el turno o si simplemente no me atendieron.

**Comment by RaniAgus** [comment]
Dejo en el issue para aclarar por si alguien lo lee: todos los cuatris creamos un nuevo rol y reiniciamos el sistema de inscripciones, por lo que hay que volver a enviar "Estoy OK" en el canal #lobby del server para otorgarles dicho rol.
