### ISSUE TITLE
Reserva cantidad maxima de marcos por proceso

### ISSUE THREAD

**Issue by BDIPAULO** [sisoputnfrba/foro#2626]
Buenas tardes, 
En el equipo tenemos una duda con respecto a la reserva de la cantidad máxima de marcos por proceso en RAM. 

Caso 1: Llega un proceso y se le reserva la cantidad máxima de frames en la RAM. Luego se van usando los frames asignados a medida que se los necesita.  De esta forma creemos que se asegura la cantidad máxima de marcos para el proceso. 
       
Caso 2: Llega un proceso y se le reserva solo la cantidad necesaria de frames en RAM a medida que se necesitan hasta llegar a la cantidad máxima de marcos por proceso. Por lo cual el proceso no necesariamente puede llegar a utilizar el máximo de marcos. 

	 
### 💭 Soluciones posibles

Caso 1: 
	  Cuando realizarlo? 
	  1.1 Al momento del envío de mensaje de Kernel a Memoria para solicitar el numero de la tabla de 1er nivel. 
	  1.2 Al momento de recibir una solicitud de escritura/lectura que necesite pasar el proceso a RAM.  (Esta opción nos parece mas acertada) 

Caso 2: 
          Cuando realizarlo? 
	  2.1 Al momento de recibir una solicitud de escritura/lectura que necesite pasar el proceso a RAM y reservar a demanda controlando que no se pase del máximo.

**Comment by LeandroCarbajales** [comment]
Buenas!
Para clarar, la asignación de marcos por proceso en este caso no es un "máximo", es fija, es decir, se le asigna a cada uno esa cantidad de marcos sea que los use o no. La idea es que sea consistente con el grado de multiprogramación definido en el Kernel, por ejemplo, si la Memoria tiene 16 marcos y 4 marcos por proceso, el grado de multiprogramación no podría ser mayor a 4. En este contexto, desde que el proceso pasa a "ready" por primera vez ya tiene garantizados sus 4 frames.

Queda más clara la duda?

Saludos!
       Lean

**Comment by BDIPAULO** [comment]
Buenas ! 
Si quedo mas claro pero me surgieron otras ... 
1. Siendo que será consistente con el grado de multiprogramación definido en el Kernel reservo el marco a medida que los va usando  ?¿ 
2. No controlo que se pasen de la cantidad máxima de marcos ?  

(Es mas bien para estar 100% seguro q no la estamos manqueando)

Gracias por la respuesta. Saludos!
Belén

**Comment by LeandroCarbajales** [comment]
Buenas!
Como el esquema es paginación a demanda, la decisión de qué frame le damos a una página del proceso se hace recién cuando la CPU pida esa página, y al ser sustitución local, también tendrás que chequear si tenés frames libres para ese proceso, es decir si el proceso ya tiene 4 páginas en memoria, tendrás que sustituir otra para poder cargar una nueva aunque tengas otros marcos libres.

**Comment by BDIPAULO** [comment]
Buenas! 
Listo, despejadas todas las dudas. 
Gracias. Buen finde! 
Belén
