### ISSUE TITLE
Procesos bloqueados

### ISSUE THREAD

**Issue by mbuchutn** [sisoputnfrba/foro#2627]
Hola,

Tengo una duda sobre como tratar los procesos bloqueados. Entiendo que segun la version 1.1 del TP tenemos que manejar una sola cola BLOCKED, los procesos que lleguen por intruccion I/O bloqueante deben ingresar a esta cola con algoritmo FIFO con un tiempo de bloqueo asignado.
Entonces, suponemos que solo tenemos un dispositivo de entrada y salida que va a estar disponible para el sistema y va atendiendo los trabajos en el orden en que llegan a la cola. El tiempo asignado es lo que tarda el dispositipo I/O para procesar la solicitud.
Cuando el tiempo se cumple para el primer proceso de la cola BLOCKED, se quita de esta cola y se pasa a atender al segundo proceso y asi continuamente.
Puede pasar que el tiempo de ejecucion de I/O de este primer proceso sea mayor al permitido para la permanencia en la cola BLOCKED, entoces debemos enviarlo a SUSPENDED_BLOCKED.
En ese caso el dispositivo I/O seguiria atendiendo al proceso, ahora en SUSPENDED_BLOCKED, y el segundo proceso de BLOCKED, que pasa a ser el primero, deberia quedarse esperando
Eso es asi? en este escenario las colas BLOCKED y SUSPENDED_BLOCKED quedarian en serie, al menos por un tiempo
O quiza, en este caso en particular, no hay que enviar el proceso a SUSPENDED_BLOCKED, y se mantiene en BLOCKED hasta que termina. Los que si se podrian mover de cola son los procesos siguientes 
Si disponemos de mas de un dispositivo I/O la cosa cambia. cuantos? y el planificador de mediano plazo va contando el tiempo para varios a la vez?

saludos

**Comment by LeandroCarbajales** [comment]
Buenas!
Capaz sea más fácil razonarlo viendo al estado "SUSPENDED-BLOCKED" no como otra cola particular sino como que el proceso está bloqueado y también suspendido, en ese sentido, el hecho de que se suspenda no afecta a la cola de atención del dispositivo de IO, por lo que seguiría atendiendo al que acabamos de suspender.

> Si disponemos de mas de un dispositivo I/O la cosa cambia. cuantos?

Muy buena pregunta si hubiera más de un dispositivo de IO, como vemos en clase, el estado blocked en si no representa una sola cola, sino una cola por cada "evento" de bloqueo, dicho de otra manera, si tuviéramos 2 o más dispositivos de IO, tendríamos una cola de atención para cada uno.

> y el planificador de mediano plazo va contando el tiempo para varios a la vez?

Al planificador de mediano plazo en este caso le importa cuánto tiempo está bloqueado, asique si :)

Quedan más claras las dudas?
Saludos!
          Lean

**Comment by mbuchutn** [comment]
Hola Leandro,

gracias por la respuesta. No me quedo claro el tercer punto.
Si manejo una sola cola para todos los bloqueados, independientemente si estan en BLOCKED o SUSPENDED_BLOCKED, esta cola usa el algoritmo de planificacion FIFO entonces tengo que atender de a un proceso a la vez. O sea, voy decrementando la rafaga solo del primer proceso de la cola hasta que se termina y luego paso al segundo y asi sucesivamente. Es correcto?

O lo pensamos como un sistema capaz de atender todos los bloqueados en paralelo, y voy decrementendo la rafaga de todos al mismo tiempo? no me suena razonable... aunque podria ser asi para el TP

saludos

**Comment by LeandroCarbajales** [comment]
Buenas!

> Si manejo una sola cola para todos los bloqueados, independientemente si estan en BLOCKED o SUSPENDED_BLOCKED, esta cola usa el algoritmo de planificacion FIFO entonces tengo que atender de a un proceso a la vez. O sea, voy decrementando la rafaga solo del primer proceso de la cola hasta que se termina y luego paso al segundo y asi sucesivamente. Es correcto?

Exactamente! Para este TP estamos implementando la misma lógica que vemos en los ejercicios de planificación :)

> lo que si tengo que hacer para todos en paralelo es ir controlando el tiempo maximo para permanecer en estado BLOCKED y cambiar su estado a SUSPENDED_BLOCKED

Así es! En definitiva lo que se busca es bajar el grado de multiprogramación (y liberar memoria) para que puedan ingresar nuevos procesos, por lo que si hay muchos procesos encolados en blocked, se irán suspendiendo cuando cada uno supere ese tiempo en estado bloqueado.

Espero que te sirvan las respuestas :)
Saludos!
        Lean

**Comment by mbuchutn** [comment]
Listo Leandro, perfecto. quedo todo claro. muchas gracias!

**Comment by LeandroCarbajales** [comment]
Buenísimo!
Asumo que se puede cerrar el issue entonces :)
Cualquier cosa lo podés volver a abrir.

Saludos!

**Comment by nfernandezsanz** [comment]
Hola! Me sumo a este issue ya que no termino de comprender como se debe realizar la _medicion del tiempo_ para determinar si un proceso debe o no pasar a suspendido. <br>
A partir de que momento deberia de comenzar a medir el tiempo? Desde que el proceso ingresa en la lista de bloqueado o desde que es su turno para utilizar I/O? Podria pasar a suspendido procesos que aun no comenzaron a utilizar la I/O?

**Comment by iago64** [comment]
Buenas! @nfernandezsanz Cómo va?

Eso esta aclarado en el enunciado en la especificación del Diagrama de Estados en la página 12, que fue una de las cosas que se agregaron con la V1.1 del documento

> El kernel utilizará el diagrama de 7 estados para la planificación de los procesos, **teniendo en cuenta que se tendrá solamente una cola de procesos bloqueados, siendo sus operaciones atendidas en modo FIFO**, y siguiendo los lineamientos de suspensión que se detallarán posteriormente en la explicación del algoritmo de mediano plazo.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas @nfernandezsanz !
Te resolvió la duda?

**Comment by nfernandezsanz** [comment]
Si! Muchas gracias! Resuelto.
