### ISSUE TITLE
Hilos vs Sockets

### ISSUE THREAD

**Issue by Gdepablo** [sisoputnfrba/foro#2628]
https://www.youtube.com/watch?v=G8PD6wauMeY

Andaba viendo ese video, y veo que dicen que se puede usar hilos en vez de sockets, siempre y cuando puedas justificarlo
Lo que no entiendo es cómo se realizaría la transferencia de información entre los módulos mediante hilos (vi que dice como que se puede hacer, pero es un bardo) y en todo caso cómo conectás los módulos mediante hilos. Además, cómo diferencia el sistema los ULT de los KLT? O sea, a nivel C por ejemplo, cómo creo un ULT y cómo un KLT?

**Comment by LeandroCarbajales** [comment]
Buenas!
No sé a qué parte del video te referís en que se dice eso, pero conceptualmente sockets e hilos son cosas muy distintas, entiendo que lo que se explica es para qué usaríamos uno u otro.
Por otro lado, la biblioteca pthread, al menos en Linux crea hilos KLT ya que los mismos tienen cada uno su TID cuando listamos los hilos del sistema por consola.

Saludos!
          Lean

**Comment by Gdepablo** [comment]
Hola Leandro, capaz me confundí yo, pero me refería a en este minuto
[40:59](https://www.youtube.com/watch?v=G8PD6wauMeY&t=2459s) ¿Puedo usar procesos en vez de hilos?

O sea, no entiendo a qué se refiere con esto, "sockets en vez de hilos" o cosas así. Si me lo podrían explicar, gracias!

**Comment by LeandroCarbajales** [comment]
Ok, ahí pregunta por un caso particular que entiendo tiene más que ver con "Procesos vs Hilos", específicamente preguntan "Si yo quisiera tener una consola (terminal) interactiva en mi proceso, no podría crear un nuevo proceso y que se comuniquen por sockets? (en vez de levantar un hilo que espere las entradas de teclado)", y justamente le responde que en principio no tendría sentido porque los hilos de un mismo proceso ya comparten recursos, en cambio levantar un proceso nuevo solo para eso y que se comuniquen por sockets sería algo ineficiente.
Las ventajas/desventajas de cada approach se ve bastante en detalle en la clase teórica de Procesos/Hilos, capaz repasando también por ese lado puede que te termine de cerrar más :)

Saludos!
        Lean

**Comment by Gdepablo** [comment]
Okay! Ahora entiendo mejor, gracias Lean!
