### ISSUE TITLE
Estado del PCB al ejecutar Instrucion IO y EXIT

### ISSUE THREAD

**Issue by neverkas** [sisoputnfrba/foro#2629]
Buenas, antes que nada confirmaba que el #2559 estaba resuelta. 
Lo intenté reabrir pero no me permitía, por tanto creo este otro.

# Cita al enunciado
> Ciclo de Instrucción -> Execute -> instruccion I/O y EXIT
>I/O(tiempo): Esta instrucción representa una syscall de I/O bloqueante. Se deberá devolver el PCB actualizado al Kernel junto al tiempo de bloqueo
>EXIT: Esta instrucción representa la syscall de finalización del proceso. Se deberá devolver el PCB actualizado al Kernel para su finalización.

# Duda
Cuando hace referencia a `PCB actualizado` para ambos casos
1. al módulo CPU sólo le corresponde modificar cuanto tiempo estuvo ejecutando el proceso en cpu? (apunto a lo mismo que se menciona en este otro incidente #2621 )
2. corresponde modificar alguna otra métrica?
3. el cambio de estado a blocked/exited  es sólo responsabilidad de kernel, no? ó podemos realizarlo dentro del ciclo de instrucción cuando ejecuta dichas instrucciones?

Una última duda, es válido dejar en kernel un único hilo que se conecte a la conexión cpu dispatch y quede escuchando, para estas interacciones por el mismo socket? ó es necesario la conexión/desconexión sólo cuando estas interacciones entre kernel/cpu ocurren?

Gracias,

**Comment by LeandroCarbajales** [comment]
Buenas! Voy respondiendo por punto :)
1- Es una posibilidad, pero no es necesario ya que el mismo Kernel podría contar cuánto tiempo estuvo en EXEC hasta que se lo devuelven.
2- Hay un valor en específico que el CPU necesariamente actualiza cada ciclo de instrucción ;)
3- El manejo de estados es exclusivamente responsabilidad del Kernel.

Si desde Kernel no dejás un hilo esperando que te devuelvan el PCB, cómo sabrías cuándo te lo devuelven?

Saludos!
       Lean

**Comment by LeandroCarbajales** [comment]
Buenas @neverkas !
Te sirvieron las respuestas? Te resolvió las dudas?

**Comment by RaniAgus** [comment]
¡Buenas! Cierro por inactividad, ante cualquier consulta pueden reabrir el issue. Saludos
