### ISSUE TITLE
PCB, Unidad de Tiempo para las Instrucciones IO y NO_OP

### ISSUE THREAD

**Issue by neverkas** [sisoputnfrba/foro#2630]
# Cita del enunciado
> NO_OP: No hacer nada, solamente esperar un tiempo determinado por archivo de configuración. El objetivo principal de esta instrucción es hacer que la ejecución sea más predecible para facilitar las pruebas de los algoritmos de planificación de corto plazo.
> I/O(tiempo): Esta instrucción representa una syscall de I/O bloqueante. Se deberá devolver el PCB actualizado al Kernel junto al tiempo de bloqueo.

> Ejemplo de líneas a parsear
```
NO_OP 5
I/O 3000
...
```

# Dudas
Hago referencia a #2621 porque está asociado a la estimación de la próxima ráfaga más corta
1. El tiempo de bloqueo que se da en la operación de IO para simular el tiempo de respuesta del dispositivo I/O debe ser en microsegundos? ya que se sugiere investigar por la función `usleep` que utiliza esa unidad de tiempo, en el ejemplo dado deberia ser entonces 3000 microsegundos?
2. El tiempo dado en `NO_OP` en que unidad de tiempo sería? segundos? ó la misma que el de la instrucción I/O?

Esas dudas surjen porque estoy utilizando la función `clock()` para determinar cuanto tiempo estuvo un proceso en ejecución y realizar la estimación para el algoritmo sjf con desalojo, pero entiendo que esa función se maneja en milisegundos, y al probarla con tiempos muy cortos produce valores no deterministicos (ej. 0, ó negativos)

Gracias,

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va?

1. Tranqui, el parámetro de `I/O` viene dado en milisegundos. Se sugiere investigar `usleep()` ya que es una función que permite bloquear un hilo con precisión en milisegundos si multiplicás el valor de ese parámetro por 1000.

2. El segundo parámetro de `NO_OP` no es un tiempo sino la cantidad de veces que se repite la misma instrucción, cito el enunciado:

> Para facilitar su legibilidad y posteriores pruebas del trabajo práctico, el identificador NO_OP tendrá un parámetro especial, que no debe ser tomado como parámetro de la instrucción en sí, sino que representa la cantidad de veces que se repite esa misma instrucción. Por ejemplo, “NO_OP 5” debe ser tomado como 5 instrucciones seguidas de NO_OP.

Saludos

**Comment by LeandroCarbajales** [comment]
Buenas!
Agrego un comentario porque me hace ruido lo de usar la función `clock()`, según la [descripción del man](https://man7.org/linux/man-pages/man3/clock.3.html) dice `The clock() function returns an approximation of processor time used by the program.`.
Me parece que se estarían metiendo en varios problemas usando algo así, por eso sugerimos usar algo como Timer o simplemente comparar timestamps como se respondió en #2606.

Saludos!
       Lean

**Comment by neverkas** [comment]
Perfecto, gracias

**Comment by iago64** [comment]
Asumo que la duda quedo resuelta, por lo tanto, cierro el issue, cualquier cosa siempre lo pueden reabrir 😄
