### ISSUE TITLE
Mandar mas parametros en list_iterate

### ISSUE THREAD

**Issue by DamianArielLerner** [sisoputnfrba/foro#2631]
Básicamente mi duda es como mandar mas parámetros a la función en la que hago el `list_iterate()`, es decir, no solo mandar cada elemento de la lista, sino un `t_paquete` también. Gracias!

**Comment by RaniAgus** [comment]
¡Buenas! Creo que este video es lo que estás buscando 😉: https://www.youtube.com/watch?v=1kYyxZXGjp0 
Saludos

**Comment by DamianArielLerner** [comment]
Exacto, muchas gracias!
