### ISSUE TITLE
Creacion de void* con malloc explota

### ISSUE THREAD

**Issue by DamianArielLerner** [sisoputnfrba/foro#2632]
Buenas, tengo el siguiente codigo:
`void * magic = malloc(bytes);`
Al intentar crearlo con 212 bytes, tengo el siguiente mensaje de error:
"Error in `/home/utnso/tp-2022-1c-FaZe/kernel/Debug/kernel': malloc(): memory corruption: 0x0804dbe8 ***"
Es porque estoy intentando crearlo con mas memoria de la que dispongo? O es exagerada esa cantidad de bytes? Este tamaño de bytes es de todo mi pcb.
Gracias!

**Comment by RaniAgus** [comment]
¡Buenas! Probablemente se deba a que hayas manejado mal la memoria en alguna parte anterior a esa línea.

Te cuento más o menos cómo funciona `malloc()`: internamente tiene metadata entre cada porción de memoria que devuelve, o sea, algo así:

```
+----------+-----------------+----------+
| metadata | lo que devuelve | metadata |
|          |    malloc()     |          |
+----------+-----------------+----------+
```

Esa "metadata" le sirve a la función para saber si ese espacio de memoria está libre u ocupado, cuánto mide, etc. 

Si en algún momento sin querer sobreescribís esa metadata por haberte pasado de la memoria que devolvió `malloc()`, el error no va a saltar inmediatamente, sino recién cuando `malloc()` intente leerla para asignar una nueva porción de memoria.

Saludos

**Comment by RaniAgus** [comment]
PD: Para encontrar errores de manejo de memoria más fácilmente les aconsejo utilizar Valgrind. Pueden revisar [esta guía](https://faq.utnso.com.ar/valgrind) y [esta charla](https://www.youtube.com/watch?v=knRei6OBU4Q) para guiarse sobre cómo usar esta herramienta.

**Comment by DamianArielLerner** [comment]
Ya encontramos la solución, nos faltó liberar la memoria de la pcb, y en cuanto a la herramienta, de ahora en adelante le vamos a echar un ojo, muchas gracias!
