### ISSUE TITLE
Deserialización entre consola y kernel

### ISSUE THREAD

**Issue by ezequielmalfonso** [sisoputnfrba/foro#2635]
Buenas tardes, una consulta, estamos terminando la deserializacion entre consola y kernel y no estoy pudiendo hacer un debug paso a paso, saben como se relizaria el debug en estos casos, cuando le doy al debug me dice que no encuentra las shared, dejo el error:
**error while loading shared libraries: libshared-lib.so: cannot open shared object file: No such file or directory**

Como seria el procedimiento para realizar el debug en estos casos, o si me pueden decir donde verlo.

Gracias.-

**Comment by RaniAgus** [comment]
¡Buenas! Creo que este video les puede servir 😉: https://www.youtube.com/watch?v=A6dhc9cCI18
Saludos

**Comment by iago64** [comment]
@ezequielmalfonso Cómo va? Te sirvió el link que te dejo Agus? Necesitas una mano con algo mas relacionado al issue?

Saludos.-

**Comment by ezequielmalfonso** [comment]
@iago64 / @RaniAgus si gracias, me sirvio pude hacer el debug de la consola y el kernel. Muchas gracias.

**Comment by LeandroCarbajales** [comment]
Asumo que se puede cerrar el issue ya que quedó resuelto el problema, cualquier cosa lo vuelven a abrir :)
