### ISSUE TITLE
Dudas creación de hilos para gestión de colas

### ISSUE THREAD

**Issue by lucas-marmo** [sisoputnfrba/foro#2636]
Buenas! Estamos con varias dudas con respecto a la implementación de hilos.
Primero, creamos un while para recibir conexiones y por cada una que recibe, se crea un hilo que deserializa y encola el PCB en la cola de New. La consulta es a partir de acá: pensamos en crear un hilo que se encargue de, cada vez que entra un PCB a New, verificar si puede enviarlo a la cola de Ready (si el grado de multiprogramación lo permite). Acá nuestra duda viene de si este hilo que gestiona a New debe crearse dentro de la función ejecutada por el hilo de recepción/deserialización de cada consola o cómo se puede hacer?
A su vez, dentro de este nuevo hilo gestor de New, una vez que determina que puede enviar el proceso a Ready, debemos hacer que Ready se encargue de encolarlo o de reorganizar su cola (dependiendo el algoritmo), lo que pensabamos hacer con otro hilo más. También nos vuelve a surgir la pregunta: este hilo de Ready se debe crear dentro de la función ejecutada por el hilo de New o cómo sería?

Adjunto código para mostrar a lo que me refiero con el hilo creado para cada consola que ya tenemos hecho:
En `main`:
```
while(escuchar_servidor(logger,"KERNEL",server_socket, colaNew));
```
En `escuchar_servidor`:
```
int escuchar_servidor(t_log* logger, char* name, int server_socket, t_queue* colaNew){
    int cliente_socket = esperar_cliente(logger, name, server_socket);
    if (cliente_socket != -1){
        pthread_t hilo_procesar_consola;
        procesar_consola_args* arg = malloc(sizeof(procesar_consola_args));
        [...]
        pthread_create(&hilo_procesar_consola,NULL,(void)procesar_consola,(void)arg);
        pthread_detach(hilo_procesar_consola);
        return 1;
    }
    return 0;
}
```
La pregunta entonces sería si dentro de `procesar_consola` creamos el hilo ese de New del que hablamos arriba, o si deberíamos quizás hacerlo luego del `pthread_detach`, quizás devolviendo el PCB obtenido en `procesar_consola`.

**Comment by LeandroCarbajales** [comment]
Buenas!
Los hilos se pueden crear desde cualquier lugar del código y desde cualquier hilo, siempre se van a comportar igual. Dicho de otra manera, en vez de pensar donde "deben" crearlos, piensen donde conviene crearlos :)
Por ejemplo, para tener un hilo que maneja el estado de la cola Ready, tranquilamente lo podrían crear al comienzo del programa e ir despertándolo usando semáforos, muy similar a un productor-consumidor de los ejercicios.

Les resuelve la duda?
Saludos!
        Lean

**Comment by lucas-marmo** [comment]
Okey, por lo que entendemos hasta ahora, los hilos los estamos creando para usarlos en el momento, lo que sí se va a poder volver a usar es la función que utiliza el hilo, pero sería creando un nuevo hilo, por lo tanto no entiendo bien que sería eso de "ir despertándolo" al hilo. Sería hacer un pthread_create por cada vez que lo tenemos que usar? Y entonces con el tema de semáforos nos referimos a que, por ejemplo, no haya dos hilos de ordenamiento de cola de Ready ejecutándose al mismo tiempo, no?
Tampoco estaríamos entendiendo la analogía con "productor-consumidor" ya que en la cursada eso lo vimos para procesos y con el objetivo de bloquear variables globales, no se si te referías a, como mencioné más arriba, bloquear o desbloquear la posibilidad de crear un hilo de tal función para que dos hilos de esa misma función no se superpongan en la misma cola por ejemplo.

**Comment by LeandroCarbajales** [comment]
> Okey, por lo que entendemos hasta ahora, los hilos los estamos creando para usarlos en el momento, lo que sí se va a poder volver a usar es la función que utiliza el hilo, pero sería creando un nuevo hilo, por lo tanto no entiendo bien que sería eso de "ir despertándolo" al hilo. Sería hacer un pthread_create por cada vez que lo tenemos que usar? O cómo se puede reutilizar un hilo? Y entonces con el tema de semáforos nos referimos a que, por ejemplo, no haya dos hilos de ordenamiento de cola de Ready ejecutándose al mismo tiempo, no?

Por ejemplo, al igual que como vemos en la clase de sincronización, si tu función tiene un loop infinito `while(true)` que comienza con un `wait(semáforo)`, ese hilo lo podrías crear en cualquier momento y esa función se ejecutaría la cantidad de veces que se le haga `signal(semáforo)` desde cualquier otro hilo. Evitándote tener que crear un nuevo hilo cada vez que quieras ejecutar esa función y posibles condiciones de carrera.

> Tampoco estaríamos entendiendo la analogía con "productor-consumidor" ya que en la cursada eso lo vimos para procesos y con el objetivo de bloquear variables globales

Con hilos diría que la analogía con los ejercicios es aún más clara que con procesos como se ve en la cursada, tenés variables globales (tu lista ready por ejemplo) y tenés hilos accediendo concurrentemente (mutex) o queriendo que ejecuten tras un evento determinado (binarios/contadores). Por lo que la implementación queda exactamente igual si lo quisieran hacer de esa forma.

Por supuesto que los pueden usar como les sea más cómodo, pero mi recomendación para no marearse en general con hilos es crear los que necesito y no crear por las dudas.

Saludos!
        Lean

**Comment by iago64** [comment]
@lucas-marmo Cómo va? Te quedo alguna duda? Hay algo que no se entienda de la respuesta de Lean?

Saludos.-

**Comment by lucas-marmo** [comment]
Nono creo que ya entendimos bien todo, justo nos pusimos a implementarlo y me olvidé de responder, ahora cierro el issue, muchas gracias!
