### ISSUE TITLE
Duda sobre Sockets

### ISSUE THREAD

**Issue by Gdepablo** [sisoputnfrba/foro#2637]
```
int iniciar_servidor(void) {
	int socket_servidor;

	struct addrinfo hints, *servinfo, *p;

	memset(&hints, 0, sizeof(hints));
	hints.ai_family = AF_UNSPEC;
	hints.ai_socktype = SOCK_STREAM;
	hints.ai_flags = AI_PASSIVE;

	getaddrinfo(IP, PUERTO, &hints, &servinfo);

	// Asociamos el socket a un puerto

	// Escuchamos las conexiones entrantes

	log_trace(logger, "Listo para escuchar a mi cliente");

	return socket_servidor;
}

```
Tengo esta función, robada del TP0, que no está del todo implementada pero me puede servir como base.
Mi duda es que no se qué hace esto 
`struct addrinfo hints, *servinfo, *p;`

Sé que declara un struct, pero los campos de ese struct son hints, *servinfo, *p ? 
Anduve buscando en google y en el mismo video de la cátedra de 2018 veo que usan la func socket de C, que recibe 3 parámetros (domain, type y protocol)
https://man7.org/linux/man-pages/man2/socket.2.html

Entonces, mi duda es, el memset que me reemplaza los caracteres por /0 en el hints, junto a todo lo demás de abajo, no lo termino de entender. Tambien el getadrrinfo (https://man7.org/linux/man-pages/man3/getaddrinfo.3.html) no lo entiendo por mucho que lo busque en internet. 

Sé que la estructura de socket es
Socket > Connect (Handshake) > Bind > Listen > Send / Recv 

Entonces, eso que ya estaba de las utils de C me deja mareado, porque no sé si al poner esto 
`int socket_servidor = socket(AF_UNSPEC,SOCK_STREAM,AI_PASSIVE);`

Estoy reutilizando código o haciendo cosas innecesarias.
También mi idea era, como en el video este (https://www.youtube.com/watch?v=87gwfsJ_83o) poner el bind en un if cosa de poder tirar un pointer error si failea al conectar. 
Me llama la atención qué es serverinfo, o sea, qué contiene, qué datos? o se supone que el getaddr_info lo tenemos que guardar en serverinfo y ahí usar eso como referencia para bindear tal que así
`bind(socket_servidor, (* void) serverinfo, sizeof(serverinfo)); `

**Comment by RaniAgus** [comment]
¡Buenas! Muchas de las dudas se encuentran respondidas en la [guía de sockets](http://faq.utnso.com.ar/guia-sockets) linkeada al TP0. Particularmente `getaddrinfo()` es una forma "bonita" de convertir una IP y un puerto a las estructuras que requieren las otras syscalls que aparecen en la guía sin necesidad de hardcodear los valores.

> También mi idea era, como en el video este (https://www.youtube.com/watch?v=87gwfsJ_83o) poner el bind en un if cosa de poder tirar un pointer error si failea al conectar.

Está perfecto, les recomiendo hacerlo para cada función de la biblioteca estándar que usen para así detectar errores más rápido. Se pueden guiar con el manual para saber los valores de retorno y cómo leerlos, por ejemplo, `getaddrinfo()` dice que:

> getaddrinfo() returns 0 if it succeeds, or one of the following
       nonzero error codes:
> [...]
> The gai_strerror() function translates these error codes to a
       human readable string, suitable for error reporting.

En cambio, para otras funciones va a decir algo como:

> On error, -1 is returned, and [errno](https://man7.org/linux/man-pages/man3/errno.3.html) is set to indicate the error.

En estos casos, el manual de `errno` explica algunas formas de traducir ese código de error a string para poder loguearlo: https://man7.org/linux/man-pages/man3/perror.3.html 

Saludos

**Comment by iago64** [comment]
Buenas!

La idea de la serialización es poder mandar estructuras de datos complejas por socket, de una forma que puedas recibirlas del otro lado y asegurarte de que esta todo lo que mandaste, entonces todas las comunicaciones entre los procesos del TP van a tener serialización de los mensajes, de hecho el tp0 implementa una serialización muy muy simple con el t_paquete.
En un poco lo que comentamos en la [charla de serialización](https://www.youtube.com/watch?v=GnuurOt8yqE&t=1s&ab_channel=UTNSO), no tenes que verlo como algo propio del tp, si no algo propio de comunicarte entre procesos y que de hecho sale un poco a la luz en el minuto [14:29](https://www.youtube.com/watch?v=GnuurOt8yqE&t=869s) del video.

Saludos.-
