### ISSUE TITLE
DUDA TLB

### ISSUE THREAD

**Issue by matiasferrerovilas** [sisoputnfrba/foro#2638]
Tenia una duda respecto a la tlb.

![imagen](https://user-images.githubusercontent.com/27780879/167886485-81a93860-dbb8-4389-8743-fa435d2bf9e7.png)

Yo para traducir las direcciones. Primero obtengo el numero de pagina, dicho numero me tengo que fijar en mi tlb y si esta me quedo con el marco y listo, sino voy a memoria y hago los 3 accesos que tengo que hacer.

Mi duda radica en el numero de pagina que guardo en la tlb. Si tengo 2 procesos (proceso 1 y 2) ejecutando al mismo tiempo cada uno tiene su propia tabla de paginas, y ambos tienen la pagina numero 0.  Entonces si guardo el numero_pagina en la tlb, no me puede pasar que el proceso 1 acceda y le de el marco que tiene asignado para el proceso 2?

**Comment by LeandroCarbajales** [comment]
Buenas!
Al igual que en los ejercicios, como la TLB no tiene columna de proceso, la misma se tiene que limpiar ante cada cambio de proceso para que no pase eso :)

Saludos!
      Lean

**Comment by LeandroCarbajales** [comment]
Ante cada cambio de proceso en CPU, dicho de otra manera, cuando el Kernel cambia qué proceso está en EXEC.

**Comment by LeandroCarbajales** [comment]
Buenas @matiasferrerovilas !
Te resolvió la duda?

**Comment by matiasferrerovilas** [comment]
Si perfecto. Cierro el issue.
