### ISSUE TITLE
Duda sobre procesos bloqueados

### ISSUE THREAD

**Issue by comejia** [sisoputnfrba/foro#2639]
Estuve leyendo varios issues sobre los procesos en BLOCKED y SUSPENDED-BLOCKED pero sigo con dudas.

Supongamos el siguiente escenario:
* TIEMPO_MAXIMO_BLOQUEADO = 10 seg
* t = 0, P1 ingresa a BLOCKED con I/O 15 seg
* t = 1, P2 ingresa a BLOCKED con I/O 13 seg
* t = 2, P3 ingresa a BLOCKED con I/O 5 seg 

Si la cola de bloqueados se atiendo por FIFO y teniendo en cuenta que:
> Para que un proceso entre en suspensión se debe cumplir que el mismo esté bloqueado por un tiempo mayor al límite definido por archivo de configuración.

Entonces, ¿como se manejan los procesos bloqueados? 
Un posible caso puede ser:
* P1 hace I/O 10 seg, luego pasa a SUSPENDED-BLOCKED y alli esta por 5seg
* P2, en el instante t = 10, va  a hacer I/O 1 seg y luego pasa a SUSPENDED-BLOCKED y se queda ahi por 2 seg
* P3, ¿similar a P2? en t = 11 hace I/O 1 seg y pasa a SUSPENDED-BLOCKED por 4 seg

Si esto es asi, ¿como se maneja la cola de SUSPENDED-BLOCKED para pasar los procesos a SUSPENDED-READY?
¿Suspendo los procesos en el orden que llegaron? Es decir, P1 va a estar 5seg, luego P2 2seg y P3 4seg

Saludos, Cesar

**Comment by LeandroCarbajales** [comment]
Buenas!
Mi respuesta sería muy parecida a la de este issue #2627 
No pensar el estado SUSPENDED-BLOCK como una cola aparte sino simplemente para saber que esos procesos bloqueados, además están suspendidos.
Para seguir tu ejemplo:
Si P1 tiene que hacer 15s de IO, P2 no comenzará su IO hasta t=15, luego P3 comenzaría recién en t=28 y así siguiendo la lógica FIFO. En este contexto P1 se suspendería en t=10, P2 en t=11 y P3 en t=12 que es pasados 10s desde que se bloquearon.

La única diferencia entre blocked y suspended-blocked a efectos del Kernel es que, cuando terminen su IO, los que no se hayan suspendido pasan directamente a ready, mientras que los suspendidos pasan a suspended-ready.

Queda más clara la idea?

Saludos!
       Lean

**Comment by comejia** [comment]
Hola Lean,

Muchas gracias por la respuesta, me aclaraste la duda de como manejar la cola de bloqueados.
