### ISSUE TITLE
Kernel finaliza al querer joinear 2 hilos

### ISSUE THREAD

**Issue by DamianArielLerner** [sisoputnfrba/foro#2640]
Hola buenas, hace poco empezamos a usar hilos y administrar múltiples procesos, creamos el primer hilo que se encarga de recibir al proceso y agregarlo a una cola de nuevos procesos, lo probamos y funciono el recibir múltiples procesos, pero si intentamos crear y joinear otro hilo se termina el proceso del kernel, ni siquiera entra a las funciones de los 2 hilos.
Este vendría a ser el código que se encuentra en el main que provoca la finalización (osea desde el primer join):
`pthread_create(&hiloRecibirProcesos, NULL, (void*)recibir_cliente,NULL);`
`pthread_create(&hiloNewReady, NULL, (void*)newAReady,NULL);`
`pthread_join(hiloRecibirProcesos, NULL);`
`pthread_join(hiloNewReady, NULL);`
No tenemos mucha idea de como funcionan todavía los hilos, así que perdonen cualquier inconveniente. Muchas gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Por suerte para todo lo que es hilos tenemos el [video de una charla que tuvo lugar hace unos años](https://www.youtube.com/watch?v=G8PD6wauMeY&ab_channel=UTNSO), donde comentamos un poco estas cuestiones de como crear, como esperar y como matar un hilo.
Te recomiendo que le pegues una repasada al video a ver si te aclara un poco el panorama.
Porque tu problema es que si el hilo al cual le haces `pthread_join` termina, tu programa sigue y si tu programa termina, muere el proceso y todos sus procesos o hilos hijos.

Saludos.-

**Comment by DamianArielLerner** [comment]
Hola Dami, ahora nos miramos el video, pero las 2 funciones a las cuales agrego en `pthread_join` tienen un while(1) que se ejecutan indefinidamente, así que no entendería la razón de que un hilo termine a menos que lo mate yo, situación que todavía no codee para corroborar que se queden ejecutando. Saludos!

**Comment by DamianArielLerner** [comment]
Aparte de eso, ayer no me dejaba compilar el kernel porque no reconocía las funciones de pthread aunque les hice el include y se marcaban en violeta en el eclipse, entonces encontré que tenia que incluir a pthread como library en el proyecto y ahí si me pudo compilar y funcionar, esta bien lo que hice? o esta solución temporal me va a dar problemas a futuro? Gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Justamente el incluirlo en las configuraciones del proyecto es lo que te hace falta para que ademas te lo agregue en los makefiles que genera eclipse, asi que no te preocupes, eso no debería darte dolores de cabeza a futuro.

Respecto al tema del while(1), es importante que no estes teniendo un seg fault o alguna condición de ese estilo porque si revienta la función a la cual le estas haciendo el join revienta todo, por las dudas, corrieron con [valgrind y helgrind](https://www.youtube.com/watch?v=knRei6OBU4Q) para ver que onda por que se termina el proceso?

Saludos.-

**Comment by DamianArielLerner** [comment]
No, no probamos usar valgrind y helgrind por ahora. En un rato lo usamos y te contamos que onda. Muchas gracias!

**Comment by DamianArielLerner** [comment]
La linea de codigo que me marca valgrind es la siguiente:
`t_pcb* pcb = queue_pop(colaNew);`
Y el error es el siguiente: "Access not within mapped region at address 0x0 [PID: 4481]"
Para contextualizar, antes de esa linea de codigo yo creo una pcb con malloc y despues de agregarlo a la cola no lo libero.
Es posible que el error se trate de que por alguna razon esta queriendo guardar una pcb aunque no haya nada en la cola todavia?

**Comment by DamianArielLerner** [comment]
> La linea de codigo que me marca valgrind es la siguiente: `t_pcb* pcb = queue_pop(colaNew);` Y el error es el siguiente: "Access not within mapped region at address 0x0 [PID: 4481]" Para contextualizar, antes de esa linea de codigo yo creo una pcb con malloc y despues de agregarlo a la cola no lo libero. Es posible que el error se trate de que por alguna razon esta queriendo guardar una pcb aunque no haya nada en la cola todavia?

Sip, era esto, cambiamos la validacion de un if y ahora funciona correctamente. Muchas gracias por enseñarnos esta herramienta!
