### ISSUE TITLE
Duda tipo de dato de Estimacion de rafaga

### ISSUE THREAD

**Issue by AlejoGol** [sisoputnfrba/foro#2641]
Buenas, una consulta sobre este tema. Es mejor que el valor que guarda el pcb sobre la estimación de la ráfaga esta en milisegundos o microsegundos? Y es mejor que sea un int o un double? Me surgió la duda porque puede pasar que el pcb este muy poco tiempo en la cpu (antes de ser enviada a kernel por una instrucción IO, por ejemplo), por lo que puede pasar que si tengo un timer que cuenta en milisegundos (adaptado a lo que se use para la estimación de la ráfaga, que lo tomé como milisegundos por como es dado en el config) este me diga que el pcb estuvo en la cpu por un tiempo de 0 milisegundos (lo que creo que no debería pasar) y al querer actualizar la estimación esta se vuelva solo la mitad de la estimación anterior.

**Comment by LeandroCarbajales** [comment]
Buenas!
Para la precisión que estaremos manejando es más que suficiente representar los tiempos en milisegundos. Más allá de que normalmente estaremos usando instrucciones NO_OP para que los tiempos en CPU sean predecibles, si se diera el caso de que el tiempo de ejecución fuera 0 no habría ningún problema tampoco :), lo podemos tomar como una ráfaga de CPU muy muy corta que a efectos de SRT cumple con su objetivo.

Saludos!
      Lean

**Comment by RaniAgus** [comment]
¡Buenas @AlejoGol! ¿Se resolvió la duda con lo que comentó Lean? Saludos

**Comment by AlejoGol** [comment]
Buenas, sisi, se soluciono, muchas gracias
