### ISSUE TITLE
Qué se guarda en la queue de NEW?

### ISSUE THREAD

**Issue by alexisdona** [sisoputnfrba/foro#2642]
Buenas! 
En el planificador de largo plazo del kernel no me queda claro qué es lo que se debe guardar en la cola de NEW. Estoy recibiendo la lista de instrucciones y creando el PCB en el kernel con toda la info, pero éste no tiene el estado del proceso. ¿En dónde es que se asigna este estado del proceso? Por otro lado la queues que representan los estados de procesos tiene que contener el PCB entero? 

**Planificador de Largo Plazo**
_Al conectarse una consola al kernel, deberá generarse la estructura PCB detallada anteriormente y asignarse este proceso al estado NEW.
En caso de que el grado de multiprogramación lo permita, los procesos pasarán al estado READY, enviando un mensaje al módulo Memoria para que inicialice sus estructuras necesarias y obtener el valor de la tabla de páginas que deberá estar almacenado en nuestro PCB._

**Comment by LeandroCarbajales** [comment]
Buenas!
Pueden agregar el estado a la estructura PCB si así lo desean, y/o pueden tener una cola en la que tengan a los PCBs en estado NEW directamente y su estado estaría implícito por estar en esa cola.

Saludos!
         Lean

**Comment by alexisdona** [comment]
Excelente! Gracias lean! creo que vamos por la opción manenar colas de PCBs y que quede implicito el estado del proceso por estar en la cola.

**Comment by LeandroCarbajales** [comment]
Buenísimo!
Si te resolvió la duda cierro el issue, cualquier cosa lo volvés a abrir  :)
