### ISSUE TITLE
Maximo de PCBs

### ISSUE THREAD

**Issue by Salacas** [sisoputnfrba/foro#2643]
Buenas, quisiera saber si puedo determinar un maximo de PCBs que el kernel guarde al mismo tiempo. Se puede determinar un máximo (es decir, con un array) o sí o sí tengo que ir guardando en un puntero con memoria dinamica?
Muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

No hay un máximo estipulado, porque a priori no tenemos escritas todas las pruebas, pero en lugar de andar preocupándose de usar un array, les recomiendo que se fijen de utilizar las listas de las commons, pueden accederlas al igual que un array por posición si lo necesitan 😉 

Saludos.-

**Comment by Salacas** [comment]
Claro, me olvidé de aclarar eso. Ese array que mencioné es digamos para guardar las pcb y las listas que representan los estados guardan punteros a esas pcb. Segun pude ver, las listas y colas de la commons no guardan datos si no un puntero a ellos, entonces en algún lado tengo que guardan el contenido de lo que apunta el puntero. Está bien lo que dije?

**Comment by RaniAgus** [comment]
¡Buenas! Sí, es correcto, las listas guardan punteros a datos en los nodos, por lo que hace falta haber reservado memoria con `malloc()` y pasarle a `list_add()` el puntero hacia la misma. 

De todas formas, no entendí cuál sería el inconveniente al hacerlo 🤔 

Saludos

**Comment by Salacas** [comment]
Ahora entendí, me habia confundido pensando que había que usar un puntero y hacerle malloc y realloc para guardar todas las pcbs de forma contigua digamos. El problema era que al hacer realloc se podían llegar a realocar todas las direcciones anteriores, provocando que los punteros guardados en las listas referencien a zonas de memoria prohibidas. No se si me expliqué jajaja
Pero ahora me di cuenta de que es innecesario eso y que simplemente hago un malloc por cada pcb y voy pasando el puntero entre las listas.
Muchas gracias por la respuesta, un saludo
