### ISSUE TITLE
Dudas Enunciado y TLB

### ISSUE THREAD

**Issue by Gdepablo** [sisoputnfrba/foro#2644]
Todos los procesos tienen handshake? 

Cita: `Al iniciarse el módulo, se conectará con la Memoria y realizará un handshake inicial para recibir la configuración relevante de la misma que le permita traducir las direcciones lógicas a físicas. Esto debería incluir al menos cantidad de entradas por tabla de páginas y tamaño de página.`

Tengo que esperar a que un proceso termine de ejecutar I/O y termine su segundo round de CPU antes de empezar el otro o mientras uno ejecuta I/O yo puedo ejecutar el otro?
Y si ese proceso en I/O termina no puede retomar el original de I/O a menos que el proceso B entre en I/O también? (pero por algoritmo FIFO entrarian los demas procesos)
Me explico, supongamos que yo tengo un proceso A que tiene una tabla
CPU | I/O | CPU
3         5      3 

Y un proceso B
CPU | I/O | CPU
7         2      3 

Cuando A está en I/O (y bloqueado porque si está en I/O ese KLT está bloqueado) el proceso B puede ejecutar CPU en ese lapso de I/O? O sea si en el TP hay que considerar ese caso o sólo FIFO sin importar si está en I/O no (O sea que si está en I/O y después tiene CPU, espera a que termine el segundo round de CPU antes de hacer un cambio al proceso B)
Si no es así, ¿qué pasaría cuando el proceso A termine I/O? Ya que se estaría ejecutando el proceso B, y no hay desalojo, debería terminarse o llegar a I/O para que cambie de proceso ¿o no? 

La otra duda es respecto a cómo pasa el Kernel la PCB a la CPU. Si los pasa uno a uno, o una lista. Especifico abajo:

Si el Kernel pasa la lista entera de pcb de procesos (y por ende no me importa en qué orden los ponga en la lista a pasarle en el CPU) o si por el contrario el Kernel tiene la lista de procesos y decide que proceso mandar a la CPU para que se ejecute (de a 1)

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- El tema del handshake como se comenta en el [video de sockets](https://www.youtube.com/watch?v=V0KFn9w62sY&ab_channel=UTNSO), es una forma copada de iniciar una conexión y asegurarnos que en el socket tenemos conectado lo que esperamos que este conectado (Ha pasado históricamente de entregas en el labororio de Medrano que ponían mal una IP y se "conectaban" tps de grupos diferentes y explotaba todo por los aires al primer mensaje).
Ahora si es obligatorio o no, depende de cada grupo, la recomendación es que siempre en toda conexión tengan un handshake.

2.- Respecto al orden, de ejecución es tal cual lo ven en clase, si un proceso se va a hacer I/O, se queda bloqueado hasta que termina si I/O y recien ahi pueden continuar con sus siguientes ráfagas de CPU.

3.- El kernel le tiene que pasar de a 1 los PCB a la CPU, ya que a la CPU solo le importa el PCB que tiene que ejecutar, los demas no sabe ni que existen.

Saludos.-

**Comment by Gdepablo** [comment]
Todo claro excepto el 2.
En el 2 me refería a que si, como digo en el ejemplo, mi proceso A está bloqueado en I/O, mi CPU puede ejecutar el proceso B a la par que ese proceso A hace I/O
Saludos!

**Comment by iago64** [comment]
Ahora si, no te había entendido esa parte 😄 
La idea es que sea como en los ejercicios de la teoría, cuando un proceso se bloquea por I/O desaloja la CPU y la puede utilizar otro proceso.

Saludos.-

**Comment by Gdepablo** [comment]
Perfecto, gracias!
