### ISSUE TITLE
[CPU] Dudas generales de TLB

### ISSUE THREAD

**Issue by MaxiReg** [sisoputnfrba/foro#2645]
Hola buenas mañanas, nos surgieron un par de dudas con el enunciado:

1. ¿Pueden 2 tablas de segundo nivel tener marcos repetidos entre si (mismo valor de marco)?

> Por ej, un marco = 0 puede estar en 2 tablas de segundo nivel distintas

2. ¿Que es exactamente la variable tabla_paginas del PCB? ¿Como se usa?

3. ¿En el acceso a la TLB, tenemos que simular la busqueda tal como se da en la vida real (preguntar a todas las entradas a la vez)?
¿O hacemos una busqueda secuencial?

**Comment by LeandroCarbajales** [comment]
Buenas!
Agrego algunos datos más:
1.- En un momento dado puede pasar que más de una entrada de las tablas tengan el mismo marco siempre y cuando una sola de esas páginas tenga el bit de presencia en 1.
2.- Viene a representar a lo que en clase vemos como "puntero a tabla de páginas", es para que la CPU sepa en qué tabla de la Memoria buscar la entrada correspondiente.

Saludos!
       Lean

**Comment by MaxiReg** [comment]
Buenaaaaas, gracias a ambos por sus respuestas, pero se nos generaron un par de dudas: 
1. Sinceramente, no estamos muy seguros de como es eso del bit de presencia (aun no cursamos la clase de Memoria Principal). Queriamos saber si para hacer una implementación básica tendríamos que tener en cuenta los marcos repetidos.
2. Entonces, para acceder a la tabla de paginas en la CPU, ¿deberíamos crear una copia (o referencia) utilizando el puntero?
3. Mejor que sea secuencial. Se nos había ocurrido utilizar múltiples hilos (uno por cada entrada de la TLB), pero sabia que era bastante rari.

**Comment by LeandroCarbajales** [comment]
Buenas!
Como aclaración general, la clase de memoria y memoria virtual las tendrán en estas 2 próximas semanas, por eso la recomendación para el checkpoint es que tengan implementado todo lo relacionado al módulo Kernel que es lo que les va a permitir correr pruebas. Luego del checkpoint ya deberían haber visto en clase todo lo que necesitan para implementar el módulo de Memoria y la parte de MMU de la CPU.

Para responder sus preguntas:
1- El concepto de bit de presencia lo verán en clase, más allá de eso, sí, tendrán que tener una manera de administrar qué marcos tienen libres y cuáles están ocupados, una opción es tener un bitmap de marcos libres, también lo verán en clase ;)
2- No, lo verán con más detalle en la clase de memoria pero en el enunciado también está explicado qué se hace con eso y se habló mucho de eso acá #2586 y acá #2617

Obviamente si quisieran ya ir viendo en profundidad estos conceptos, siempre pueden ver clases grabadas de cuatrimestres anteriores :)
Saludos!
          Lean

**Comment by MaxiReg** [comment]
Muchas gracias por las respuestas. Tendremos en cuenta todo eso para pensar mejor la solucion.
