### ISSUE TITLE
Duda suspension de procesos

### ISSUE THREAD

**Issue by AlejoGol** [sisoputnfrba/foro#2646]
Buenas, me surgió una duda sobre la suspensión de procesos.
Estaría bien hacer que si el TIEMPO_MAXIMO_BLOQUEADO es menor que el tiempo que tiene que estar bloqueado el proceso por la instrucción, entonces primer se haga usleep por el tiempo máximo bloqueado, después se suspensa el proceso (con el aviso a memoria) y después se haga usleep del tiempo restante para que después el proceso pase a suspended-ready?
O es necesario que el bloqueo y la suspensión se evalúen en paralelo en dos threads distintas?

### 📔 Citas del enunciado/videos
Para que un proceso entre en suspensión se debe cumplir que el mismo esté bloqueado por un tiempo mayor al límite definido por archivo de configuración.
Al suspenderse un proceso se enviará un mensaje a Memoria con la información necesaria y se esperará la confirmación del mismo.

**Comment by LeandroCarbajales** [comment]
Buenas! Ambas implementaciones son válidas :), pero tengan en cuenta que si se empiezan a encolar procesos bloqueados para IO, seguramente estarán más tiempo bloqueados de lo que diga su IO correspondiente, por lo que tengan cuidado por ese lado si lo hacen "secuencial".
Hay un ejemplo bastante claro en el issue #2639 y algo más de explicación en el #2627.

Les sirve la respuesta?
Saludos!
        Lean

**Comment by AlejoGol** [comment]
Buenas, sisi, me re sirvió la respuesta para repensar la lógica.
Entonces es mejor que se evalúe en paralelo ya que el momento en el que empiezo a evaluar si suspender un proceso (o sea empiezo un timer para ese proceso) es cuando el proceso entra en la cola de bloqueados y no cuando se lo elige para ser atendido por la IO (o sea cuando se va a hacer su usleep correspondiente).
Además, esta bien asumir que hay solo 1 dispositivo de IO, no? Porque no recuerdo si se especifica lo contrario. O sea, que hay una cola de bloqueados y se va haciendo el usleep de a uno según elegidos por FIFO.

**Comment by RaniAgus** [comment]
¡Buenas! Sí, está bien, de hecho se especifica en el enunciado (sección "Diagrama de Estados" del Kernel):

> El kernel utilizará el diagrama de 7 estados para la planificación de los procesos, **teniendo en cuenta que se tendrá solamente una cola de procesos bloqueados, siendo sus operaciones atendidas en modo FIFO, y siguiendo los lineamientos de suspensión que se detallarán posteriormente en la explicación del algoritmo de mediano plazo.**

Saludos

**Comment by AlejoGol** [comment]
Perfecto, ya se entendió. Muchas gracias!!!!!
