### ISSUE TITLE
Duda con Semaforo entre modulos CPU y Kernel

### ISSUE THREAD

**Issue by TomasR264** [sisoputnfrba/foro#2647]
Buenas!

Estamos teniendo un problema en el que en el codigo, para pasar del estado exec a exit, tenemos un semaforo que hasta que cpu no termina el ciclo de ejecucion, no desbloquea al semaforo en cuestion, que una vez desbloqueado permite que Kernel finalice el proceso. El problema es que el semaforo cuando en CPU le hacemos el post, del lado de kernel sigue con el valor 0 y por tanto no se desbloquea:

Abajo dejo una especie de pseudocodigo de la seccion problematica para ayudar a comprender la idea mejor:

![image](https://user-images.githubusercontent.com/62635603/169909859-599634c4-0af2-4e35-997d-7fd0ed0a37e6.png)

Kernel le manda el pcb con las instrucciones cuando esta en ready a CPU, y ahi este hace el ciclo de ejecucion y despues desbloquea el semaforo.

**Comment by RaniAgus** [comment]
¡Buenas!

¿Pensaban armar un semáforo compartido entre **procesos** (no hilos)? O sea, un semáforo inicializado con `sem_init` apuntando a un cacho de memoria compartido ~~de una forma medio turbia~~ como sugiere [el manual](https://man7.org/linux/man-pages/man3/sem_init.3.html) 🤔 

Quizás sería más sencillo aprovechar que `send` y `recv` son bloqueantes para que el Kernel se quede esperando un mensaje de la CPU diciéndole que se ejecutó un EXIT 😉 

Saludos

**Comment by TomasR264** [comment]
Gracias! Nos sirvio! Saludos 🚀
