### ISSUE TITLE
El compilador no me toma funciones declaradas en el .h

### ISSUE THREAD

**Issue by martina-facu** [sisoputnfrba/foro#2650]
Hola, Buenos días
Estoy tratando de importar las funciones relacionadas con las instrucciones de un archivo instrucciones.h, en el que tengo definidos los prototipos de las funciones que desarrollo en el archivo instrucciones.c, que a su vez también importa intrucciones.h. Yo importe el archivo en consola.c que es donde las quiero usar así: #include "../../Shared/utils/instrucciones.h"  pero es como si me reconociera las estructuras pero no las funciones y me salta el error de compilación: 
/home/utnso/tp-2022-1c-9-12/Consola/Debug/../src/Consola.c:44: undefined reference to `definirCodigo'
makefile:30: recipe for target 'Consola' failed

Por otro lado si pongo el desarrollo de las funciones en el .h si me compila el proyecto, lo mismo pasa si me importo el .c de las instrucciones en el consola.c, igual por lo que leí esto seria incorrecto pero no se como solucionarlo sino. Si alguien me puede dar una mano lo agradaría

Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

Te hago un par de consultas al respecto:
1.- el .c que tiene las implementaciones de las funciones tiene el include del .h?
2.- en el .h tenes las directivas `#ifndef`, `#define` y `#endif`?

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Me suena a que por algún motivo no se está incluyendo el archivo `instrucciones.c` al compilar con `gcc` (quizás porque se encuentra en una carpeta Shared por afuera del proyecto), ¿podrías pasarnos lo que devuelve la consola al momento de compilar?

Por ejemplo:

```
13:11:04 **** Build of configuration Debug for project prueba ****
make all 
Building file: ../src/prueba.c
Invoking: GCC C Compiler
gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/prueba.d" -MT"src/prueba.o" -o "src/prueba.o" "../src/prueba.c"
Finished building: ../src/prueba.c
 
Building target: prueba
Invoking: GCC C Linker
gcc  -o "prueba"  ./src/prueba.o   
Finished building target: prueba
 

13:11:04 Build Finished (took 303ms)
```
En este caso solo estoy compilando un archivo `prueba.c`

Saludos

**Comment by martina-facu** [comment]
Hola, buenas tardes
Perdón por la demora, lo que devuelve la consola cuando quiero compilar el modulo consola es esto:

18:44:48 **** Incremental Build of configuration Debug for project Consola ****
make all 
Building file: ../src/Consola.c
Invoking: GCC C Compiler
gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/Consola.d" -MT"src/Consola.o" -o "src/Consola.o" "../src/Consola.c"
Finished building: ../src/Consola.c
 
Building target: Consola
Invoking: GCC C Linker
gcc  -o "Consola"  ./src/Consola.o ./src/cliente.o ./src/consolaConfig.o   -lcommons -lpthread
./src/Consola.o: In function `deserializar_instrucciones':
/home/utnso/tp-2022-1c-9-12/Consola/Debug/../src/../../Shared/utils/protocolo.h:54: undefined reference to `getCantidadParametros'
makefile:30: recipe for target 'Consola' failed
./src/Consola.o: In function `obtener_intrucciones':
/home/utnso/tp-2022-1c-9-12/Consola/Debug/../src/Consola.c:28: undefined reference to `definirCodigo'
./src/Consola.o: In function `empaquetar_instrucciones':
/home/utnso/tp-2022-1c-9-12/Consola/Debug/../src/Consola.c:52: undefined reference to `calcular_espacio_instrucciones'
./src/Consola.o: In function `main':
/home/utnso/tp-2022-1c-9-12/Consola/Debug/../src/Consola.c:100: undefined reference to `mostrar_instrucciones'
collect2: error: ld returned 1 exit status
make: *** [Consola] Error 1

18:44:49 Build Finished (took 1s.401ms)

**Comment by RaniAgus** [comment]
Sip, como se puede ver en esta línea, se está compilando solo el código de los archivos `Consola.c`, `cliente.c` y `consolaConfig.c`:

```
gcc -o "Consola" ./src/Consola.o ./src/cliente.o ./src/consolaConfig.o -lcommons -lpthread
```
_(Eclipse por defecto se genera un `.o` con cada `.c` del proyecto)_

Como Eclipse solamente compila el código que está en el `src` del proyecto, pueden seguir [este tutorial](https://www.youtube.com/watch?v=A6dhc9cCI18) para crear en la carpeta Shared un proyecto tipo shared library y linkearlo a cada módulo.

Saludos

**Comment by martina-facu** [comment]
Hola, muchas gracias
Sigo el tutorial entonces cualquier cosa sino lo llevo mañana a las consultas.

Saludos
