### ISSUE TITLE
[Memoria] Duda con TAM_MEMORIA

### ISSUE THREAD

**Issue by CarolinaSeoane** [sisoputnfrba/foro#2651]
Hola, tenemos la siguiente duda: en el enunciado dice que TAM_MEMORIA es el tamaño de la memoria, ¿es este espacio solamente de usuario o también abarca el espacio de kernel?

La duda surgió porque en el config dice que el tamaño de la memoria sería de 4096 bytes. De ahí sacamos que los frames de la memoria son 64. Como el grado de multiprogramación es de 4 y se asignan 4 frames por proceso estaríamos usando sólo 16 frames de la memoria.  Entonces, los que quedan, ¿son el espacio de kernel?

Gracias.

**Comment by iago64** [comment]
Buenas! Cómo va?

Tengan en cuenta que los configs del enunciado son meros ejemplos, puede que no concuerden 100% con una prueba real, para las pruebas vamos a darles valores correctos 😉 

Saludos.-

**Comment by CarolinaSeoane** [comment]
Hola, entiendo pero el TAM_MEMORIA hace referencia solamente el espacio de usuario o ahí también tienen que entrar las tablas de páginas?

**Comment by RaniAgus** [comment]
¡Buenas! Nono, en este TP las tablas de páginas son estructuras administrativas que no deben guardarse en el espacio de memoria reservado para los procesos. Saludos

**Comment by CarolinaSeoane** [comment]
Perfecto, gracias!
