### ISSUE TITLE
Problemas con la shared library

### ISSUE THREAD

**Issue by TfernandezFrancou** [sisoputnfrba/foro#2652]
Buenas noches, hace unos días tomamos la decisión de hacer una shared library por una cuestión de comodidad y después de haber visto el tutorial completo, ya está armada, linkeada y demás para todos los módulos del tp. El problema lo tenemos cuando queremos correr el kernel, nos salta este error:
`error while loading shared libraries: libutils.so: cannot open shared object file: No such file or directory`
Pero si corremos consola, por ejemplo, la cual configuramos de la misma manera de kernel para que reconozca la shared library, funciona sin problemas. Gracias de antemano y disculpen las molestias
Saludos

**Comment by iago64** [comment]
Buenas Buenas! Cómo va?

Están corriendo el TP en eclipse? 
Si es así les recomiendo que le peguen una revisada al video que grabó Tom hace unos cuatrimestres de como [crear una shared library en eclipse](https://www.youtube.com/watch?v=A6dhc9cCI18) que seguramente les va a dar una mano.

Saludos.-

**Comment by TfernandezFrancou** [comment]
A ese tutorial me refería, configuré todo en base a eso. En teoría funciona porque me reconoce los headers, el flag -lutils y si corremos otro módulo configurado de la misma manera, no se presenta el error. En este caso probamos corriendo consola porque no presenta errores de otro tipo. Y queriendo probar el kernel, que nos está compilando bien, nos salta el error que marqué en el issue.
Puede ser una mala configuración en run configurations?

**Comment by RaniAgus** [comment]
¡Buenas! Me suena a que configuraron `LD_LIBRARY_PATH` para ejecutar Consola pero no para Kernel. Si entran a las Run Configurations van a ver que cada módulo tiene sus configuraciones separadas. Saludos

**Comment by TfernandezFrancou** [comment]
Buenas, lo que explica en el video lo chequeé varias veces que esté bien. También por ejemplo me fijé bien dónde estaba cada cosa porque podían variar los directorios con respecto a los que ponía Tom.
Decidí borrar el repo de mi pc, volver a clonar y configurar siguiendo el tutorial de nuevo, pero ahora el problema es que por más que agregue el Library search path (todo, en realidad), al compilar siempre muestra el error `cannot find -lutils`

**Comment by RaniAgus** [comment]
¿Llegaste a compilar la shared library después de volver a clonar el repo? Quizás no esté encontrando el archivo libutils.so

**Comment by TfernandezFrancou** [comment]
Compila con ciertos warnings pero compila, el libutils lo genera. Así que estaré viendo qué onda

**Comment by TfernandezFrancou** [comment]
De algo que nos estamos dando cuenta es que antes nos generaba `libutils.so` y ahora, no sé por qué nos lo genera sin el .so, simplemente libutils. No se si es ese el problema ni la razón, mucho menos la solución jajaja

**Comment by TfernandezFrancou** [comment]
Hola, de nuevo yo. Intenté creando otra shared library y configurándola de la misma manera que venía haciendo y funciona perfecto. Puede ser que el problema sea que estamos importando mal la shared library cuando clonamos el repo? Nosotros la agregamos al workspace de la misma manera que los otros módulos (Makefile project with existing code)

**Comment by RaniAgus** [comment]
Es posible que el workspace que hayan elegido para iniciar Eclipse sea distinto, por lo que la variable `workspace_loc` habrá quedado apuntando para otro lado. Pueden elegir el workspace ni bien inician Eclipse o yendo a `File > Switch Workspace > Other...`

Les debe aparecer esta pantalla, en donde podrán elegir la carpeta en donde tienen clonado repo, por ejemplo:
![image](https://user-images.githubusercontent.com/39303639/170810930-f704f7d8-5fa8-4f81-add9-0e07bfb10cdc.png)

**Comment by TfernandezFrancou** [comment]
Buen día, eso lo revisé bien hace unos días y por las dudas le pasamos el path completo sin usar la variable, para quedarnos seguros. Ahora, conseguí solucionar el problema, lo comento por si a alguien le pasa lo mismo.
* En lugar de importar la shared library como `Makefile Project with Existing Code`, la importamos con un `Open Projects from File System`. Esto la va a importar pero no va a dejar configurarla, entonces hacemos `New -> Convert to a C/C++ Project (Adds C/C++ Nature)`, elegimos C project y la shared library. Eso ya nos permite configurar tal cual dice el tutorial que subió Tom (https://youtu.be/A6dhc9cCI18) y compilar perfecto.

Muchas gracias por la paciencia!
