### ISSUE TITLE
Instrucciones I/0 y Exit no deberian ejecutar el check interrupt?

### ISSUE THREAD

**Issue by ospocarpa** [sisoputnfrba/foro#2653]
Buenas  con mi grupo no nos pusimos deacuerdo que  cuando en CPU estamos ejecutando alguna de estas instrucciones ,debemos terminar el ciclo de instruccion o podemos cortarlo es decir : 
Ejemplo si tenemos una instruccion i/o ,actualizamos el  PCB(program counter++) ,enviamos dicho PCB a KERNEL sin pasar por check interrupt (idem para EXIT )    o ejecutar todo el ciclo de instruccion ,incluido el check interrup .
Con la 2da opcion conceptualmente creemos que dejamos que termine la instruccion , por mas que en ambos casos, halla o no halla interrupciones los procesos para kernel van a ir a bloqueado o finalizado .

**Comment by LeandroCarbajales** [comment]
Buenas!
A efectos del TP es irrelevante chequear interrupciones al ejecutar IO o EXIT, asique no es necesario que lo hagan porque en definitiva devuelven el PCB y replanifican :)

Saludos!
        Lean

**Comment by ospocarpa** [comment]
Perfecto, muchas gracias!

**Comment by martina-facu** [comment]
Una consulta sobre este tema, no se si se pueda seguir comentando en el issue cerrado, sino abro otro.
En caso de que te haya llegado una interrupción mientras estabas ejecutando una instrucción i/o o exit y no haces la parte del check interrupt ¿No estarías dejando sin atender esa interrupción?
