### ISSUE TITLE
Cola de procesos Bloqueados 

### ISSUE THREAD

**Issue by stephywasiuchnik** [sisoputnfrba/foro#2654]
Buenas! Queríamos saber si el enunciado, cuando aclara que habrá una única cola de procesos bloqueados, se refiere a una cola para el estado BLOCKED en si, o la misma también incluiría a los procesos en estados SUSPENDED-BLOCKED y SUSPENDED-READY. En este ultimo caso, conceptualmente nos complica pensar que en una misma cola habrá procesos en memoria y fuera de esta. 
Entendemos que en la ultima versión del enunciado hicieron una aclaración sobre este tema, así que disculpen si la pregunta tiene una respuesta evidente.

**Comment by LeandroCarbajales** [comment]
Buenas! Para nada es una respuesta "evidente" :)
Es algo que ya se preguntó en los issues #2627 y #2639 donde se ve con algunos ejemplos, y creo que no son los únicos, pero entiendo que eso respondería a tu pregunta pero cualquier cosa lo seguimos por acá.

Saludos!
       Lean

**Comment by fcafici** [comment]
Hola, comento sobre este issue porque partiendo del mismo, seguimos teniendo un par de dudas (somos del mismo grupo).

Empezamos a plantear posibles soluciones para el hecho de que tenemos que hacer varias cosas al mismo tiempo:
- Tomar el tiempo desde que se bloqueó cada proceso para ver si hay que suspenderlo.
- Ir avanzando en la cola de bloqueados para atender al siguiente proceso.
- Atender al proceso (ejecutar la instrucción IO propiamente dicha).

Una de ellas fue evaluar, en el momento que cada proceso llega a la cola de bloqueados, si el mismo va a suspenderse o no antes de ser atendido (teniendo en cuenta los procesos que tiene por delante en la cola, cuánto tiempo va a estar atendiéndose cada uno y el tiempo máximo estipulado en el archivo de config). En base a esto, suspenderíamos al proceso cuando le corresponda.
El problema es que no sabemos qué tan certero será predecir cuándo el proceso se suspenderá, teniendo en cuenta que podrían ocurrir imprevistos y el tiempo calculado podría diferir del real, ni cómo vamos a hacer todo esto al mismo tiempo (la respuesta obvia es hilos, pero cómo aplicarlos en si para este problema).

**Comment by stephywasiuchnik** [comment]
y para concluir lo anterior, entendemos (en base a esos issues mencionados), que se tendrá una cola para procesos en estado BLOQUED y SUSPENDED-BLOCKED, pero otra para SUSPENDED-READY. Es correcto esto?

**Comment by LeandroCarbajales** [comment]
Buenas!

> (la respuesta obvia es hilos, pero cómo aplicarlos en si para este problema).
Una forma de implementar esto con hilos puede ser, por ejemplo, levantar un hilo cuando un proceso se mueva a blocked que lo único que haga sea "esperar" (pueden usar usleep), el tiempo definido por config y luego chequear si el proceso sigue bloqueado, en ese caso lo suspende y termina.
Para ir avanzando en la cola de bloqueados puede ser un solo hilo que vaya tomando los pcbs bloqueados, espere el tiempo de io y luego lo pase a ready o a suspended-ready segun corresponda (no olviden los mutex!)

> y para concluir lo anterior, entendemos (en base a esos issues mencionados), que se tendrá una cola para procesos en estado BLOQUED y SUSPENDED-BLOCKED, pero otra para SUSPENDED-READY. Es correcto esto?
Claro! Los que estén en suspended-ready están ahí para ser desuspendidos (y volver a ready) apenas el grado de multiprogramación lo permita

Les sirven las respuestas?
Saludos!
         Lean

**Comment by fcafici** [comment]
Buenísimo, nos re sirvió, gracias! Ya para cerrar el tema, un detalle que nos quedó pendiente:
En el enunciado, cuando explica lo que hace cada instrucción, dice:

> I/O(tiempo): Esta instrucción representa una syscall de I/O bloqueante. Se deberá devolver el PCB actualizado al Kernel junto al tiempo de bloqueo en milisegundos.

Y la duda que tenemos es, hace falta mandar el tiempo en milisegundos además del PCB? No puede el Kernel directamente leer la instrucción y ver cuánto tiempo debe bloquearse?

**Comment by RaniAgus** [comment]
¡Buenas! Creería que es más simple devolverlo en un mensaje, pero a fines prácticos pueden hacer lo que les sea más cómodo. 

Ese tiempo no tiene ningún valor teórico porque en la vida real no se puede anticipar cuánto va a durar una I/O, solo les damos ese valor prearmado para simplificar la realidad (y para que las pruebas den resultados determinísticos :P).

Saludos

**Comment by fcafici** [comment]
Buenísimo, muchas gracias!!
