### ISSUE TITLE
Dudas memoria, swap, reemplazo

### ISSUE THREAD

**Issue by pabloquinci** [sisoputnfrba/foro#2655]
Buenas qué tal, tengo un par de dudas con respecto a memoria, swap y el reemplazo de páginas:

> Al ser suspendido un proceso, se debe liberar su espacio en memoria, escribiendo en SWAP solamente la información necesaria. Se debe tener en cuenta que, para la realización de este trabajo práctico, no se requiere el swapeo de tablas de páginas.

- Cuál sería la información? El dato que se encuentre en el marco de memoria correspondiente? Y cómo sería el formato de archivo, un bloque contiguo dividido en páginas?

> La memoria contará principalmente con 3 estructuras:

> Un espacio contiguo de memoria (representado por un void*). Este representará el espacio de usuario de la misma, donde los procesos podrán leer y/o escribir.

> Las tablas de páginas, que representarán el espacio de Kernel.

> Un archivo por proceso, que representarán el espacio de SWAP de cada uno.

- Qué significa espacio de "kernel" en el segundo item? no sería "espacio de usuario"?

Con respecto al reemplazo de páginas:
- Cuando se hace un reemplazo, la página sale del espacio de direcciones del proceso, es decir quedaría disponible para asignarse a otro ó, simplemente se le deja el bit de presencia en 0 (dentro del espacio de direcciones de ese mismo proceso)?

Gracias.

**Comment by LeandroCarbajales** [comment]
Buenas!
Todo esto seguramente lo estén viendo en las clases de memoria virtual (próximas 2 clases), obviamente pueden adelantarse viendo clases grabadas de cuatrimestres anteriores ;)
De cualquier forma te respondo:
- Se swapean páginas enteras, y como verán en clase, no sería necesario swapear páginas que no estén modificadas. El archivo de SWAP para este TP es un archivo contiguo del tamaño del proceso.
- La tablas de páginas representan a lo que en clase vemos como "espacio de memoria asignada al kernel", en definitiva ningún proceso de usuario va a tocar eso directamente.
- El proceso de reemplazo es igual que como verán en los ejercicios en clase, pero tené en cuenta que en este TP el reemplazo es local, por lo que lo que planteas no podría darse nunca.

Saludos!
      Lean

**Comment by LeandroCarbajales** [comment]
@pabloquinci Te sirvieron las respuestas? Se puede cerrar el issue?

**Comment by LeandroCarbajales** [comment]
Cierro el issue por inactividad, cualquier cosa lo vuelven a abrir :)

**Comment by comejia** [comment]
Buenos dias,

Reabro porque estoy bastante perdido con memoria. No entiendo que es lo que se swapea?

Leandro cuando decis:
> Se swapean páginas enteras...

Esto es el marco correspondiente a esa pagina no? Osea se swapea una porcion de memoria (de tamaño TAM_PAGINA) del espacio de usuario?

**Comment by LeandroCarbajales** [comment]
Buenas @comejia!
Exactamente! Tal como lo verán en la clase de memoria virtual, al swapear una página modificada, tendríamos que escribir todo su contenido (de tamaño TAM_PAGINA, que está en el marco que indica la tabla de páginas) en SWAP.

Queda más clara la duda?
Saludos!
     Lean

**Comment by comejia** [comment]
Quedo clarisimo!!

Saludos, Cesar

**Comment by pabloquinci** [comment]
Gracias! Perdón que colgué
