### ISSUE TITLE
Duda Asignacion de marcos

### ISSUE THREAD

**Issue by matiasferrerovilas** [sisoputnfrba/foro#2656]
Buen dia, tenia una duda respecto a como hacer los algoritmos de clock y clock modificado.

Yo cuando creo las tablas de lvl 1 y 2 para el proceso que se conecto, automaticamente tengo que asignarle a  todas las paginas posibles un marco disponible?, ejemplo tengo la pagina 0,1,2,3,4 y mi sistema permite hasta 2 marcos por proceso, entonces mi pagia 0 y 1 tendrian un marco asignado y el bit de rpesencia en 1, mientras que las demas paginas tendrian bit presencia 0?.

**Comment by matiasferrerovilas** [comment]
Perfecto y una ultima duda. CPU genera la direccion fisica, es posible que cuando creo la direccion fisica y  envia para escribir o leer, dicha pagina se haya ido de memoria? o no hace falta volver a verificar cuando uno escribe/lee en memoria uqe dicha pagina esta en memoria?

**Comment by LeandroCarbajales** [comment]
Buenas!
1- Nunca te podría pasar eso porque todo el proceso de traducción se hace en el mismo ciclo de instrucción.
2- Ninguna prueba va a estar armada de esa forma asique no va a pasar, en un caso real implicaría referenciar 2 páginas distintas ya que el dato te quedaría separado en 2

Saludos!
      Lean

**Comment by matiasferrerovilas** [comment]
Perfecto, gracias!
