### ISSUE TITLE
Duda sobre liberar estructuras de listas y colas de las commons

### ISSUE THREAD

**Issue by Daniel-Aizcorbe** [sisoputnfrba/foro#2657]
Hola! no entiendo bien las funciones para liberar las listas y colas

`list_destroy_and_destroy_elements(t_list*, void(*element_destroyer)(void*))`
y
`queue_destroy_and_destroy_elements(t_queue*, void(*element_destroyer)(void*))`

que le tengo que pasar como segundo parámetro exactamente?
Vi el video de las funciones de orden superior de las `commons`, y pude usar funciones como `list_map` pero con estas dos no se exactamente que tipo de funcion(? debería pasarle.

**Comment by iago64** [comment]
Buenas! Cómo va?

Las funciones que le tenes que pasar deberían ser capaces de liberar la memoria de **un elemento** de tu lista / cola, internamente esas funciones recorren la lista / cola y liberan cada elemento con la función que le pases. Una vez recorrida la estructura, liberan los datos de la estructura.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Para sumar a lo que dijo Dami, pueden encontrar varios ejemplos de uso de cualquier función de las commons en [los tests del repo](https://github.com/sisoputnfrba/so-commons-library/blob/master/tests/unit-tests/test_list.c#L333-L341). Saludos

**Comment by Daniel-Aizcorbe** [comment]
Gracias!
