### ISSUE TITLE
Envio del PCB Kernel-CPU

### ISSUE THREAD

**Issue by facuxfdz** [sisoputnfrba/foro#2658]
Buenas tardes! Tengo una consulta sobre el envio de datos entre estos dos modulos. En la seccion del Kernel del enunciado dice lo siguiente

> Al recibir el PCB del proceso en ejecución, se calcularán las estimaciones correspondientes, según indique el algoritmo, para seleccionar el siguiente a ejecutar

Y en la parte de la CPU lo siguiente
> Quedará a la espera de conexión a través del puerto dispatch por parte del Kernel, quien, una vez conectado, le enviará un PCB para ejecutar. Habiéndose recibido, se procederá a realizar el ciclo de instrucción tomando como punto de partida la instrucción que indique el Program Counter del PCB recibido.

Y no termino de entender el flujo de los datos entre los modulos. Como kernel, mando la interrupcion y me quedo esperando a que me devuelva el proceso en ejecucion? Y si no hay proceso ejecutando como podria manejarse ese caso?

No termino de entender quien espera a quien.

Graciass!

**Comment by LeandroCarbajales** [comment]
Buenas!

> Como kernel, mando la interrupcion y me quedo esperando a que me devuelva el proceso en ejecucion?

Siempre que haya un proceso en ejecución el Kernel va a tener que estar esperando a que se lo devuelvan ya que puede ocurrir en cualquier momento (por ejemplo por IO o EXIT).

> Y si no hay proceso ejecutando como podria manejarse ese caso?

Si no hay ningún proceso en ejecución es irrelevante para este TP mandar una interrupción o no porque no lo necesitaríamos para replanificar.

Queda más clara la idea?
Saludos!
        Lean

**Comment by facuxfdz** [comment]
Claro pero, por ejemplo mando la interrupcion siempre independientemente de todo y despues mando el pcb a ejecutar? O primero tengo que revisar que la cpu no este ejecutando algo para mandar a ejecutar el que sigue. No termino de entender cuando envio el pcb y cuando lo recibo desde el kernel

**Comment by LeandroCarbajales** [comment]
Buenas!
Al igual que como se ve en clases, en lo posible siempre debe haber algo en ejecución, por lo que apenas se libere la CPU vas a querer enviar al próximo proceso a ejecutar.

**Comment by facuxfdz** [comment]
Buenisimo, ya lo pude resolver, me estaba faltando entender el concepto de "N instancias de conecciones" y el tema de que "apenas se libera". Gracias Lean! Cierro el issue
