### ISSUE TITLE
Pequeña duda acerca de la suspension de procesos

### ISSUE THREAD

**Issue by nicolasviegas** [sisoputnfrba/foro#2659]
Buenas! 

Tenemos una duda acerca de algo que se pregunto ya en otros issues como el  #2639 y #2627 por ejemplo, pero aun asi no estamos seguros de si nos quedo clara la idea

Ej:  Si un proceso tiene tiempo de bloqueo 12s y el tiempo maximo de bloqueo es 10s.

La condicion para un proceso se suspenda es que tiene que superar el tiempo maximo de bloqueo establecido en el config, en tal caso habra que pasarlo al estado suspended-blocked. Nuestra pregunta es, habria que bloquearlo 10 segundos ( sleep(10)) y despues suspenderlo el resto (sleep(2))? O que habria que hacer exactamente?

Desde ya muchas gracias! 🚀

**Comment by LeandroCarbajales** [comment]
Buenas! Haciendo referencia al ejemplo del issue #2639, el tiempo de IO de cada proceso es el que indica la instrucción (en tu ejemplo 12s), una vez suspendido y habiéndose atendido su IO (es decir, ya estando en suspended-ready) solamente se desuspenderá (volverá a ready) cuando el grado de multiprogramación lo permita.

Queda más clara la idea?
Saludos!
       Lean

**Comment by nicolasviegas** [comment]
Ah buenisimo, ya lo entendi, muchas gracias!!
