### ISSUE TITLE
Formato del real ejecutado a considerar

### ISSUE THREAD

**Issue by jlsuh** [sisoputnfrba/foro#2660]
Muy buenas :)
1) En base a la siguiente ejecución:
```shell
[INFO] 00:58:29:450 Kernel/(58638:58638): Inicialización de campos correcta
[INFO] 00:58:29:529 Kernel/(58638:58638): Conexión con CPU por canal Dispatch establecida
[INFO] 00:58:29:532 Kernel/(58638:58638): Conexión con CPU por canal Interrupt establecida
[INFO] 00:58:29:537 Kernel/(58638:58638): Se inicializa el grado multiprogramación en 4
[INFO] 00:58:29:764 Kernel/(58638:58638): Se crean los hilos planificadores
[INFO] 00:58:29:765 Kernel/(58638:58638): A la escucha de nuevas conexiones en puerto 6
[INFO] 00:58:31:599 Kernel/(58638:58681): Creación de nuevo proceso ID 0 de tamaño 500 mediante <socket 7>
[INFO] 00:58:31:602 Kernel/(58638:58681): Transición de NULL->NEW PCB <ID 0>
[INFO] 00:58:31:614 Kernel/(58638:58640): Transición de NEW->READY PCB <ID 0>
[INFO] 00:58:31:615 Kernel/(58638:58642): Se toma una instancia de READY
[INFO] 00:58:31:618 Kernel/(58638:58642): Se permite dispatch
[INFO] 00:58:31:622 Kernel/(58638:58644): Transición de READY->EXEC PCB <ID 0>
[DEBUG] 00:58:36:672 Kernel/(58638:58644): Elapsed time: 5042 miliseconds
[INFO] 00:58:36:681 Kernel/(58638:58644): Transición de EXEC->BLOCKED PCB <ID 0>
[INFO] 00:58:36:686 Kernel/(58638:58645): Ejecutando ráfagas I/O de PCB <ID 0> por 6000 milisegundos
[INFO] 00:58:36:687 Kernel/(58638:58644): PCB <ID 0> ingresa a la cola de espera de I/O
[DEBUG] 00:58:36:701 Kernel/(58638:58688): Iniciando contador de blocked a suspended blocked de PCB <ID 0>
[INFO] 00:58:42:702 Kernel/(58638:58645): Transición de BLOCKED->READY PCB <ID 0>
[INFO] 00:58:42:703 Kernel/(58638:58642): Se toma una instancia de READY
[INFO] 00:58:42:703 Kernel/(58638:58642): Se permite dispatch
[INFO] 00:58:42:704 Kernel/(58638:58644): Transición de READY->EXEC PCB <ID 0>
[DEBUG] 00:58:42:713 Kernel/(58638:58644): Elapsed time: 8 miliseconds
[INFO] 00:58:42:713 Kernel/(58638:58644): Transición de EXEC->BLOCKED PCB <ID 0>
[INFO] 00:58:42:713 Kernel/(58638:58645): Ejecutando ráfagas I/O de PCB <ID 0> por 6000 milisegundos
[INFO] 00:58:42:714 Kernel/(58638:58644): PCB <ID 0> ingresa a la cola de espera de I/O
[DEBUG] 00:58:42:753 Kernel/(58638:58698): Iniciando contador de blocked a suspended blocked de PCB <ID 0>
[INFO] 00:58:48:715 Kernel/(58638:58645): Transición de BLOCKED->READY PCB <ID 0>
[INFO] 00:58:48:716 Kernel/(58638:58642): Se toma una instancia de READY
[INFO] 00:58:48:717 Kernel/(58638:58642): Se permite dispatch
[INFO] 00:58:48:718 Kernel/(58638:58644): Transición de READY->EXEC PCB <ID 0>
[DEBUG] 00:58:48:724 Kernel/(58638:58644): Elapsed time: 6 miliseconds
[INFO] 00:58:48:726 Kernel/(58638:58644): Transición de EXEC->EXIT PCB <ID 0>
```
La duda yace en los logs de debug que respecta al tiempo que estuvo en ejecución un proceso en la CPU.

Teniendo en cuenta que actualmente la implementación es algo como:
```c
    struct timespec start;
    clock_gettime(CLOCK_REALTIME, &start);
    // Enviar pcb a cpu
    // Esperar su vuelta
    struct timespec end;
    clock_gettime(CLOCK_REALTIME, &end);
    uint64_t realEjecutado = (end.tv_sec - start.tv_sec) * 1000 + (end.tv_nsec - start.tv_nsec) / 1000000; 
    log_debug(kernelLogger, "Elapsed time: %ld miliseconds", realEjecutado);
```
Cuando obtenemos el `realEjecutado`, se obtienen ciertas cifras adicionales debido a las ejecuciones de nuestra máquina en donde desarrollamos, siendo un ejemplo:
```shell
[DEBUG] 00:58:36:672 Kernel/(58638:58644): Elapsed time: 5042 miliseconds
```
¿Deberíamos, de alguna forma forzada, hacer que se respete los 5000 milisegundos estipulados por el archivo pseudo-assembler (por ejemplo, debido a que un NO_OP se hace 5 veces de 1000 milisegundos), eliminando de alguna forma dichas cifras adicionales?

2) Adicionalmente, se me ocurre también que podría haber un NO_OP de 1 vez de 10500 milisegundos. Entonces, ¿los valores que se aporten en el día de las entregas finales pueden ser, pasados a segundos, con punto flotante? En este caso 10500 milisegundos serían 10.5 segundos.

Saludos y muchas gracias :)

**Comment by LeandroCarbajales** [comment]
Buenas!

> Cuando obtenemos el realEjecutado, se obtienen ciertas cifras adicionales debido a las ejecuciones de nuestra máquina en donde desarrollamos...

Eso es completamente esperado! De hecho 5042 milisegundos sobre una ejecución esperada de 5000 milisegundos es un grado de error muy bajo, a nivel teórico lo podrían ver como el "overhead" por cambios de modo/contexto.
A nivel pruebas del TP recién comenzarían a tener problemas si por ejemplo estuvieran midiendo un segundo más de lo esperado. De cualquier manera, tengan en cuenta que probablemente midan ese mismo "error" en todas las estimaciones, por lo que dificilmente cambie la planificación final.

> ¿Deberíamos, de alguna forma forzada, hacer que se respete los 5000 milisegundos estipulados por el archivo pseudo-assembler (por ejemplo, debido a que un NO_OP se hace 5 veces de 1000 milisegundos), eliminando de alguna forma dichas cifras adicionales?

Para nada, la idea es que justamente el Kernel no sabe cuánto va a ejecutar el proceso.

> Adicionalmente, se me ocurre también que podría haber un NO_OP de 1 vez de 10500 milisegundos. Entonces, ¿los valores que se aporten en el día de las entregas finales pueden ser, pasados a segundos, con punto flotante? En este caso 10500 milisegundos serían 10.5 segundos.

Más allá de que en las entregas vamos a intentar siempre manejar números "redondos" y predecibles, si manejan los tiempos en milisegundos siempre van a ser valores enteros por lo que no habría que lidiar nunca con punto flotante.

Saludos!
      Lean

**Comment by jlsuh** [comment]
Quedó todo claro, muchas gracias lean !
