### ISSUE TITLE
Scripts para realizar las pruebas 

### ISSUE THREAD

**Issue by alexjgonzalez** [sisoputnfrba/foro#2661]
Buenas, aún no se ven los scripts de prueba en el repositorio https://github.com/sisoputnfrba/kiss-pruebas mencionados en el Documento de Pruebas.

También notifico que en el readme del repositorio el link del "enunciado de las pruebas" enlaza a un documento que solicita permisos.

Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

Este error es una muestra de que usar una GUI para git no siempre es buena idea, ya esta resuelto el tema de los scripts 😄 

Por otro lado, gracias por el aviso del link, ya esta corregido

Saludos.-

**Comment by alexjgonzalez** [comment]
Perfecto !

Gracias !
