### ISSUE TITLE
Conexiones multiples entre CPU y Memoria.

### ISSUE THREAD

**Issue by nullspace1** [sisoputnfrba/foro#2662]
Hola! Que tal?
Acá me salto una duda principalmente sobre los requerimientos del sistema. Nos resulta conveniente tener mas de una conexión entre el modulo de CPU y Memoria - es decir, tener dos sockets. La pregunta es si esto se encuentra permitido, ya que si bien no esta explicitado que la conexión entre módulos debe ser única, los archivos de configuración solo definen un solo puerto para memoria.

Muchas gracias!

**Comment by LeandroCarbajales** [comment]
Buenas!
Para qué necesitarían 2 conexiones entre CPU y Memoria?

**Comment by nullspace1** [comment]
Hola!

Me preocupaba tener problemas con la actualización de la TLB frente a la eliminacion de paginas de la memoria principal (que podrían estar en la tlb) causado por swapeo de procesos. Tener una conexión adicional entre el módulo de la tlb y la memoria ayudaría a mantener todo actualizado de manera paralela al envío de pedidos de escritura, lectura, etc.

Gracias!

**Comment by LeandroCarbajales** [comment]
Buenas!
Con swapeo de procesos te referís a cuando son suspendidos? Un proceso suspendido nunca sería elegido para ejecutar, y por otro lado, la TLB solamente tendría entradas correspondientes al proceso actualmente en ejecución, por lo que nunca podría pasarte eso, por otro lado :)

**Comment by nullspace1** [comment]
Okaa, confío en que me estoy haciendo la cabeza nomás.

Muchas gracias de nuevo! :)
