### ISSUE TITLE
Duda pruebas y orden de ejecución

### ISSUE THREAD

**Issue by matiaspar2000** [sisoputnfrba/foro#2663]
Buenas, estamos haciendo la prueba de Kernel - Planificación con SRT, mirando el enunciado nos habla de que "En el caso de SRT los fin de IO forzarán una re-planificación y los scripts finalizarán en el orden que fueron ejecutados." 

Actualmente el orden de ejecución nos está quedando 2-0-1 en vez del pedido pero analizando las estimaciones y las interrupciones vemos que el algoritmo funciona correctamente. 

Viendo el enunciado de la prueba vemos la parte de "los fin de IO forzarán una re-planificación".  Mirando los logs vemos que pasa lo siguiente

```
[INFO] 13:09:53:438 Kernel/(6496:6507): Creación de nuevo proceso ID 0 de tamaño 200 mediante <socket 7>
[INFO] 13:09:53:443 Kernel/(6496:6509): Creación de nuevo proceso ID 1 de tamaño 400 mediante <socket 8>
[INFO] 13:09:53:448 Kernel/(6496:6499): Transición de NEW->READY PCB <ID 0>
[INFO] 13:09:53:464 Kernel/(6496:6501): Se permite dispatch
[INFO] 13:09:53:470 Kernel/(6496:6499): Transición de NEW->READY PCB <ID 1>
[INFO] 13:09:53:472 Kernel/(6496:6504): Transición de READY->EXEC PCB <ID 0>
[INFO] 13:09:53:480 Kernel/(6496:6511): Creación de nuevo proceso ID 2 de tamaño 350 mediante <socket 9>
[INFO] 13:09:53:484 Kernel/(6496:6501): Se envía interrupción a CPU
[INFO] 13:09:53:485 Kernel/(6496:6499): Transición de NEW->READY PCB <ID 2>
[INFO] 13:09:56:539 Kernel/(6496:6504): Transición de EXEC->READY PCB <ID 0> *llegada de P2 interrumpe P0*
```

Cuando se crea el Proceso 2 al ya haber un PCB ejecutando se produce una interrupción, desaloja y replanifica. Esto hace que las estimaciones cambien y afecte el orden de ejecución mas adelante causando que P2 termine antes. 
Si fuera un ejercicio en hoja pondríamos que que los 3 procesos arrancan en un T=0, entonces no existiría, pero acá al haber una demora entre q mandamos las consolas si causa que ocurra.

Nuestra pregunta es si está bien la existencia de esa interrupción en el contexto del TP

**Comment by jlsuh** [comment]
Muy buenas :)
Quería agregar al issue que consideramos implementarlo de la forma como indica el siguiente issue: https://github.com/sisoputnfrba/foro/issues/2660

Sospechamos que al emplear el `clock_gettime()`, no hay un cierto determinismo sobre las ejecuciones de las consolas. Se podría dar el caso en donde 2 procesos hayan ejecutado técnicamente el mismo realAnterior (asumiendo SRT) debido al mismo valor de, por ejemplo, un NO_OP de 1 vez de 5000 ms, solo que por diferencia de 1 milisegundo, siendo un caso: 5023ms vs. 5024ms, termina eligiendo el primero, en vez de desempatar por FIFO.

Saludos y muchas gracias :)

**Comment by RaniAgus** [comment]
¡Buenas @matiaspar2000! Tengan en cuenta que la estimación inicial de todos los procesos es la misma (20000ms), por lo que si suponemos que los procesos arrancan en:

- P1: T=0ms
- P2: T=400ms
- P3: T=800ms

Cuando ingrese P2 se va a producir el desalojo, pero como P1 ya habría ejecutado 1000ms (que es el tiempo que tarda un NO_OP), le quedarían 19000ms de su estimación inicial y debería continuar con su ejecución. Cuando ingrese P3 debería ocurrir lo mismo.

@jlsuh no te preocupes, nos tomamos la precaución de evitar esas situaciones de desempate para que las pruebas sean determinísticas.

Saludos

**Comment by matiaspar2000** [comment]
Muchas gracias, también nos dimos cuenta que había un error en otra cosa. Cierro hilo, saludos.
