### ISSUE TITLE
Tipado de ints

### ISSUE THREAD

**Issue by AlejoGol** [sisoputnfrba/foro#2664]
Buenas, una consulta, todos los valores del pcb que sean representados por ints serán del tipo uint32_t o puede ser que alguno llegue a ser uint64_t? 
Y digo sobre los parámetros del pcb porque seguro esos si ya que son los serializados, pero tienen que ser todos los ints usados de tipo uint?

**Comment by LeandroCarbajales** [comment]
Buenas! No hay una restricción sobre los tipos de datos para las variables del PCB, para qué querrían usar uint64_t?

**Comment by AlejoGol** [comment]
Lo pregunto porque el enunciado dice
Cabe aclarar que todos los valores a leer/escribir en memoria serán numéricos enteros no signados de 4 bytes, considerar el uso de uint32_t.

Tenia entendido que habia que pasar todo lo que sea de tipo int a tipo uint32 para no tener problema con el serializado en la vm sin interfaz grafica, esto es necesario?

**Comment by LeandroCarbajales** [comment]
Buenas!
Tanto Int como uint32_t son tipos de dato que en la VM pesan 4 bytes, por lo que no deberían tener problema usando uno u otro, aunque por supuesto que es una buena práctica usar uint32_t ya que es menos dependiente del sistema.
En ese sentido, no usaría uint64_t ya que pesa 8 bytes, salvo que lo necesiten para algo muy específico, por eso preguntaba.

Saludos!
       Lean

**Comment by AlejoGol** [comment]
Okey, entonces si vengo usando int y las cosas andan correctamente, vale la pena cambiar todo a uint32_t (considerando que esto tardaría tiempo y quizás llevaría a problemas)?

**Comment by LeandroCarbajales** [comment]
Buenas!
Dado el scope del TP donde no trabajamos con valores muy grandes, y que corremos todo sobre la misma VM (con y sin interfaz gráfica es la misma VM), diría que es una de las últimas cosas que me preocuparía si ya tienen todo implementado con Ints y funcionando correctamente.

**Comment by AlejoGol** [comment]
Muy bien, muchas gracias!!!!
