### ISSUE TITLE
Duda operacion NO_OP y interrupciones

### ISSUE THREAD

**Issue by AlejoGol** [sisoputnfrba/foro#2665]
Buenas, una consulta, la instrucción NO_OP se ejecuta toda junta y después de esto se chequea por interrupciones? 
O si por ejemplo tengo una instrucción NO_OP 5 y al final del tercer NO_OP el kernel manda una interrupción, entonces tengo que atenderla y la próxima vez que ingrese este proceso a ejecutar se ejecutaran los otros dos NO_OP restantes?

### 📔 Citas del enunciado/videos
Para facilitar su legibilidad y posteriores pruebas del trabajo práctico, el identificador NO_OP tendrá un parámetro especial, que no debe ser tomado como parámetro de la instrucción en sí, sino que representa la cantidad de veces que se repite esa misma instrucción. Por ejemplo, “NO_OP 5” debe ser tomado como 5 instrucciones seguidas de NO_OP.

NO_OP: No hacer nada, solamente esperar un tiempo determinado por archivo de configuración. El objetivo principal de esta instrucción es hacer que la ejecución sea más predecible para facilitar las pruebas de los algoritmos de planificación de corto plazo.

**Comment by LeandroCarbajales** [comment]
Buenas!
Como dice el enunciado, "NO_OP 5" en el pseudo-código viene a representar 5 instrucciones seguidas de NO_OP (solamente se hace para que los archivos queden más cortos y legibles), por lo que cada una correrá en un ciclo de instrucción distinto.

Te resuelve la duda?
Saludos!
        Lean

**Comment by AlejoGol** [comment]
Entonces esta bien que en la lista de instrucciones del pcb figuren 5 instrucciones NO_OP (sin parámetros) seguidas en lugar de 1 instrucción "NO_OP 5"? (Esto en el caso que en el pseudo-código aparezca una instrucción "NO_OP 5")

**Comment by LeandroCarbajales** [comment]
Claro, de hecho es lo esperado :)

Saludos!
      Lean

**Comment by AlejoGol** [comment]
Perfecto, muchas gracias por la ayuda!!!
