### ISSUE TITLE
Duda aviso a memoria cuando un proceso pasa de suspended-ready a ready

### ISSUE THREAD

**Issue by AlejoGol** [sisoputnfrba/foro#2666]
Buenas, una duda, no se si se especifica en el enunciado, pero cuando un proceso deja de estar suspendido (pasa de suspended-ready a ready) hay que avisar a memoria sobre esto? Principalmente por el bit de presencia en la tabla de paginas.

**Comment by RaniAgus** [comment]
¡Buenas! Sí deben avisar a Memoria, pero no debido al bit de presencia (recuerden que el Swap-in es a demanda), sino por el esquema de asignación de Memoria: es **asignación fija** con **reemplazo local**.

Saludos

**Comment by RaniAgus** [comment]
¡Buenas! No hace falta avisar a Memoria ya que el Swap-in es a demanda, o sea, se van a traer de Swap a Memoria solo las páginas una vez las vayan accediendo, al igual que ocurre en la transición de NEW a READY. Los frames también se van asignando a demanda teniendo en cuenta el límite de frames por proceso.

Saludos

**Comment by LeandroCarbajales** [comment]
Buenas!
Comento ya que me llamaron :P

> Lo que hicimos fue asignarle los marcos los use o no, ya que son fijos. Es decir, aunque como máximo use 2 da igual porque los otros 2 restantes no los va a poder usar ningún otro proceso.

Solamente para aclarar, en tu ejemplo la asignación fija sería de 4 marcos, y lo que decís es correcto, pero me genera la duda de si apenas pasan el proceso a ready ya le están asignando los marcos [0,1,2,3] por ejemplo en vez de simplemente mantener un contador con la cantidad.

> Por lo mismo, a la hora de pasar de suspend a ready lo que hacemos es asignar los marcos a las paginas que previamente tenían el bit de presencia en 1, para que se mantenga el estado previo a ser suspendido.

Esto es un error ya que iría en contra de la paginación bajo demanda como comentó Agus, tendría sentido si en el TP implementáramos algún tipo de _pre-fetching_.
Si lo mantienen de esa manera lo más probable es que una prueba de suspensión + memoria no dé los resultados esperados, por lo que deberían deshacer ese mensaje, a nivel código también se estarían ahorrando cierta lógica y algunas estructuras.

**Comment by Juyah** [comment]
Genial, refactorizaremos eso. 
Entonces el bit de presencia no es necesario guardar, solo el de uso y modificado para mantener el estado? O cuando se cargan las páginas al pasarlo a ready no se guarda su estado y arrancan todas en 0? 
Haciendo un análisis entendemos que no es necesario guardar el estado de los bits, solo los datos.

**Comment by LeandroCarbajales** [comment]
Si siguen la lógica de paginación bajo demanda, no necesitan guardarse nada de la tabla al suspender (ni avisarle nada a Memoria al desuspender), al swapear sus páginas ya no estarían modificadas ni presentes y el bit de uso sería irrelevante porque se pondrá en 1 cuando las vuelvan a referenciar, y se cargarían en el 1er frame que haya libre si tiene menos de 4 páginas presentes.

Queda más clara la idea?
Saludos!
      Lean

**Comment by LeandroCarbajales** [comment]
Buenas!
Entiendo que esto lo charlamos en el check asique cierro el issue, cualquier cosa lo vuelven a abrir :)
