### ISSUE TITLE
Duda prueba suspension

### ISSUE THREAD

**Issue by nico-abram** [sisoputnfrba/foro#2667]
Buenas noches

No entiendo porque en la prueba 3 de suspension se debe suspender al programa SUSPE_2

Se tiene configurado

> TIEMPO_MAXIMO_BLOQUEADO=8000

SUSPE_1 tiene una IO de 13000, por lo que se va a suspender por ser mayor a 8000:

> I/O 13000

Mi consulta es sobre SUSPE_2, que solo tiene una IO de 5000:

> NO_OP 3
> I/O 5000
> NO_OP 3
> EXIT

No entiendo porque se deberia suspender.

En mis pruebas no se me esta suspendiendo SUSPE_2, por lo que termina SUSPE_2 primero incluso con el algoritmo SRT, y recien despues termina SUSPE_1 y luego SUSPE_3.

**Comment by RaniAgus** [comment]
¡Buenas! Tengan en cuenta que solamente hay una cola de bloqueados, por lo que SUSPE_2 se va a quedar encolado esperando a que la I/O de SUSPE_1 termine, de forma similar a lo que comentó Lean en https://github.com/sisoputnfrba/foro/issues/2639#issuecomment-1124494275

Saludos

**Comment by nico-abram** [comment]
Muchas gracias
