### ISSUE TITLE
Copiar contenidos de una t_list a un atributo t_list de un struct

### ISSUE THREAD

**Issue by dlopezjoffreutn** [sisoputnfrba/foro#2668]
Buenass, como andan? Estoy deserializando una estructura medio compleja y en la recta final me encuentro con que la lista deserializada esta llena de elementos (y la cantidad correcta) pero cuando quiero copiarla a la lista dentro de mi struct, la segunda queda vacia.

### 📝 Código relevante
```
t_list *params = stream_take_LIST(stream, stream_take_UINT32P);
memcpy(instruction->params, params, sizeof(uint32_t));
```

1. `params` es una `t_list` de `uint32_t`, `stream_take_LIST` devuelve la lista y ya corroboramos que está completa y tiene los elementos bien.
2. `instruction` es una struct con el atributo `params` (de tipo `t_list*`) que fue anteriormente "allocada" con nuestra funcion `create_instruction`

> ```
> t_instruction* create_instruction(size_t id_size) {
> 	// Try to allocate instruction structure.
> 	t_instruction *instruction = malloc(sizeof(t_instruction));
> 	if (instruction == NULL)
> 		return NULL;
> 
> 	// Try to allocate instruction id and params, free structure if fail.
> 	instruction->id = malloc((id_size + 1) * sizeof(char));
> 	if (instruction->id == NULL) {
> 		free(instruction);
> 		return NULL;
> 	}
> 
> 	instruction->params = list_create();
> 	if (instruction->params == NULL) {
> 		free(instruction->id);
> 		free(instruction);
> 		return NULL;
> 	}
> 
> 	return instruction;
> }
> ```

3. El id de la instruccion se deserializa y copia correctamente 

> ```
> char *id = stream_take_STRING(stream);
> if (instruction == NULL) {
>     instruction = create_instruction(string_length(id));
> }
> memcpy(instruction->id, id, string_length(id) + 1);
> ```
 

El problema justamente es en la copia de `params` (que loggeando el atributo `elements_count` de la `t_list` es = 2) hacia `instruction->params` (que su `elements_count` da = 0). 

### 💻 Logs
```
printf("count devuelto: %d \n param count real: %d\n",
		params->elements_count, instruction->params->elements_count);
```

<img width="183" alt="image" src="https://user-images.githubusercontent.com/82044090/171522894-c7932924-881d-4cf5-953c-ee48401286cb.png">

Nuestra pregunta es: Es `memcpy` la forma de correcta de copiar lo que hay en una `t_list` en otra? Si es asi, cómo? Nos falta cambiar algo en nuestro `memcpy`? 

Si la respuesta es que no hay que usar `memcpy`, seria alternativa recorrer la lista `params` (que sabemos que esta bien) y por cada elemento "encontrado" hacer un `list_add` a la lista "destino" (`instruction->params`)? 

> Vale aclarar que esto nos pasa con la lista de params de una instruction, pero de la misma forma nos pasa con la lista de instructions de un proceso:
> 
> ```
> t_list *instructions = stream_take_LIST(packet->payload, stream_take_instruction);
> memcpy(process->instructions, instructions, sizeof(t_instruction));
> ```
> 
> Donde el elements_count de instructions es un numero acorde (y los valores son correctos) pero el de process->instructions es = 0.

Desde ya muchas gracias! Con esta ultima parte se nos destraba el testeo de los planificadores del kernel 👯 

Saludos, 
Dolores 👋 👩

**Comment by RaniAgus** [comment]
¡Buenas! Me parece que ya sé por dónde puede andar el error, se los voy a mostrar con un par de dibujos. Por un lado están haciendo:
```c
t_instruction *instruction = malloc(sizeof(t_instruction));
// ...
instruction->params = list_create();
```

![File_000](https://user-images.githubusercontent.com/39303639/171727176-eb4dc22d-0c87-4a52-bb2a-7cc50ca2212a.png)

Y luego, más adelante, deserializan una lista de, por ejemplo, 2 elementos:
```c
t_list *params = stream_take_LIST(stream, stream_take_UINT32P); // devuelve una lista de uint32_t*
```

![File_001](https://user-images.githubusercontent.com/39303639/171727236-b2524980-ac13-43a3-a1cd-4c764670c9fd.png)

Entonces, con el `memcpy` solo están copiando los primeros 4 bytes del `t_list` dentro de otro `t_list` sin haber copiado el `elements_count`, por lo que les quedó una lista inconsistente:
```c
memcpy(instruction->params, params, sizeof(uint32_t));
```

![File_002](https://user-images.githubusercontent.com/39303639/171727856-4e62ee4a-a444-4931-a4e7-5778afd00b35.png)


Siempre que trabajen con listas recuerden usar las funciones que les proveemos en `commons/list.h` en vez de manipular los datos directamente (por ejemplo, usen `list_size(params)` en vez de `params->elements_count`). 

En este caso, la solución rápida es reemplazar ese `memcpy()` por un [`list_add_all()`](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/collections/list.h#L75-L80):

```c
list_add_all(instruction->params, params);
```

Y, por último, no se olviden de liberar los nodos de `params` para no tener memory leaks, ya que `list_add_all()` crea nuevos nodos para guardar los `uint32_t*` en la otra lista:

```c
list_destroy(params);
```

Saludos

**Comment by LeandroCarbajales** [comment]
Excelente explicación Agus!
Solamente tengo una duda para agregar, hasta donde entiendo al hacer `t_list* params = stream_take_LIST` ya crean una lista, que es exactamente la misma lista (t_list* con elementos de tipo uint32_t) que necesitan en `instruction->params`.
En ese contexto, por qué necesitan copiar la lista? No les convendría directamente asignarla? Por ejemplo `instruction->params = params`. De esa forma también se ahorrarían el `list_create` en `create_instruction`.

Saludos!
        Lean

**Comment by RaniAgus** [comment]
Claro, si bien lo de usar `list_add_all()` era una solución rápida, también podrían repensar la función `create_instruction()` y darle un enfoque más "objetoso", o sea, así como en Java (que es como Wollok pero con tipado estático) uno puede tener una clase con atributos y un constructor:

```java
class Instruction {
  // estos son los atributos
  String id;
  List<Integer> params;

  // este es el constructor
  Instruction(String id, List<Integer> params) {
    this.id = id;
    this.params = params;
  }
}
```
Que se instancia así:

```java
var instruction = new Instruction(id, params);
```

Ustedes pueden hacer que `create_instruction()` sea el "constructor" que crea la estructura y setea los "atributos" que recibe por parámetro:

```c
// estos son los "atributos"
typedef struct {
	char *id;
	t_list *params;
} t_instruction;

// este es el "constructor"
t_instruction* create_instruction(char *id, t_list *params) {
	t_instruction *instruction = malloc(sizeof(t_instruction));
	instruction->id = id;
        instruction->params = params;

	return instruction;
}
```

Entonces quien la invoque ya no va a tener que liberar `id` y `params`, porque la memoria a la que apuntan es la misma que está seteada en el struct:

```c
char *id = stream_take_STRING(stream);
t_list *params = stream_take_LIST(stream, stream_take_UINT32P);

t_instruction* instruction = create_instruction(id, params);

// No hay free(), porque:
// free(id) liberaría instruction->id
// free(params) liberaría instruction->params
```
Este enfoque también les va a evitar inconsistencias a la hora de inicializar un `t_instruction*` (o cualquier otro TAD que armen para el TP), ya que si ven que necesitan agregar o quitar un parámetro pueden editar el `create` y quedarse con la tranquilidad de que el código no va a compilar hasta que no apliquen el cambio en todas las partes del código en donde llamen a ese `create`.

**Comment by dlopezjoffreutn** [comment]
Wooow, me encantaron ambas explicaciones/propuestas, muchas gracias a ambos! Justo ayer lo resolvimos directamente con el memcpy y no llegue a leer sus respuestas pero me coparon mucho :) 

Seguramente para esta primera etapa remplace esos memcpy's con `list_add_all` que ni la identifique leyendo `commons/list` 😛 

Me gusto igualmente eso de repensar los create, porque es verdad que estamos inicializando el objeto vacio y despues copiandole las cosas ya en varios lugares y estaria bueno tener el constructor. Hubo una vez que lo quisimos encarar asi y tiraba unos errores feos asi que lo volvimos para atras, pero nos sirven los code snippets para intentar de nuevooo.

Gracias una vez mas, super valiosos ambos aportes 👏 👏 👏 Saludos!

**Comment by iago64** [comment]
Asumimos que la respuesta fue lo que esperaban, vamos cerrando el issue, cualquier cosita lo pueden volver a abrir 😄
