### ISSUE TITLE
Agregar ALFA al Config del CPU

### ISSUE THREAD

**Issue by matiastito** [sisoputnfrba/foro#2669]
Buenas tardes, espero se encuentren bien, los molesto porque en nuestro TP al momento necesitariamos agregar el ALFA del SRT en el archivo de configuracion de la CPU dado que es ahí en dónde hacemos el cálculo y actualizamos la PCB.
Ustedes lo indican en el Config del Kernel y a nosotros nos ahorarría algo de tiempo tenerlo en la CPU.

Gracias!

**Comment by LeandroCarbajales** [comment]
Me suena raro que necesiten tener el alfa del planificador en CPU, más allá de que la planificación es exclusivamente responsabilidad del módulo Kernel, en qué momento de la ejecución de CPU estarían calculando el estimado de la próxima ráfaga?

**Comment by matiastito** [comment]
Medimos desde que empieza a ejecutar hasta que o interrumpido o IO o EXIT.
Y al devolver la PCB actualziada, actulizamos ahi mismo la estimacion.

**Comment by fcafici** [comment]
Hola, perdón, nosotros estamos teniendo el mismo problema. 
En nuestro caso, como CPU devuelve la PCB actualizada, hicimos todo en base a que CPU cuente cuánto tiempo estuvo la PCB ejecutando y modifique la estimación antes de devolverla. Además, habíamos visto [este issue](https://github.com/sisoputnfrba/foro/issues/2621#issuecomment-1122404988) y nos quedamos tranquilos con que no iba a ser un problema.
El tema es que nos acabamos de dar cuenta que CPU no conoce el alfa, estaría mal ponerlo en la config de CPU?

**Comment by LeandroCarbajales** [comment]
De mi lado la recomendación sigue siendo que lo haga el Kernel, lo considero más simple por tener que enviar y recibir menos datos y un poco más consistente a nivel diseño, por ejemplo, si el algoritmo de planificación fuera FIFO aun así estarían reestimando a pesar de que es un dato que no se va a usar?
A fin de cuentas, es algo que no cambia el resultado de las pruebas, pero diría que la info de config que su CPU necesite de su Kernel la pasen durante el handshake en vez de agregarlo como config para evitar duplicados/inconsistencias (por ejemplo que en la prueba para Kernel se setee un alpha=0.3 y se olviden cambiarlo para CPU)

Saludos!
       Lean
