### ISSUE TITLE
Cálculo de la siguiente ráfaga

### ISSUE THREAD

**Issue by jschuhmann47** [sisoputnfrba/foro#2674]
Buenas! Con nuestro grupo teníamos una duda sobre cómo calcular la estimación de la siguiente ráfaga. 

Actualmente nosotros en el struct de la PCB guardamos la ráfaga actual. Cuando se va al CPU ésta se actualiza al volver, pero pisando el valor de la vieja, por lo que no podemos aplicar la fórmula de la estimación con el alfa, ya que perdimos la anterior.

Se nos ocurrió que la PCB tenga un atributo de estimacion actual y uno de anterior (aunque no sabríamos muy bien cómo inicializarlo), pero queríamos preguntar porque en el enunciado dice:

> Estimación_ráfaga: estimación utilizada para planificar los procesos en el algoritmo SRT, la misma tendrá un valor inicial definido por archivo de configuración y será recalculada bajo la fórmula de promedio ponderado vista en clases.

o sea que es un solo atributo.

En resumen, estaría bien tener los dos campos? O deberíamos guardar la estimación en el Kernel antes de mandarla a CPU, para calcularla cuando vuelve? (Que como son N consolas no sabemos bien cómo)

Gracias de antemano!

**Comment by LeandroCarbajales** [comment]
Buenas!
Pueden agregarle al PCB campos auxiliares como "duración_última_ráfaga" si les facilita la implementación del algoritmo :)
