### ISSUE TITLE
MULTIPLE DEFINITIONS OF...

### ISSUE THREAD

**Issue by Danymmereles** [sisoputnfrba/foro#2675]
Buenas noches, 
Espero que anden bien.

Con mi compañera @ailendr, estabamos tratando de construir uno de nuestros modulos cuando aparecio multiples errores que decian **_"MULTIPLE DEFINITIONS OF"_**. Todos esos errores afectan a nuestros semaforos pero solamente lo inicializamos en un archivo y luego los ocupamos en diversas funciones. Ademas, cuando queremos ver la linea donde tira el error, te señala lineas que no tienen sentido alguno, como una linea que solamente hay una llave cerrada y antes de eso nunca los invocamos. Estuvimos leyendo los issues #1027 (creado en 2018) y #1292 (creado en 2019) pero ninguno nos pudo dar una idea de que ocurria. Ya limpiamos el proyecto y volvimos a construirlo pero ocurrio exactamente lo mismo. Debajo les dejamos los errores que se produjeron.

![Captura de pantalla (350)](https://user-images.githubusercontent.com/47753130/171773788-afd4d47b-0c84-497d-8e92-8c3b72213803.png)

Desde ya, muchisimas gracias y disculpen la hora.

**Comment by iago64** [comment]
Buenas! Cómo va?

No se si pudieron ver este tema en el check presencial, pero cuando se dan estos multiple definitions es porque posiblemente en el .h les falten las directivas  **#ifndef**  y **#endif**
Igual sin ver el código de donde están definiendo los semáforos y como los están usando se complica un poco poder dar una respuesta mas completa.

Saludos.-

**Comment by Danymmereles** [comment]
Buenas, 
Ayer con mi grupo pudimos ir al check presencial y dos ayudantes nos pudieron dar 3 posibles soluciones. Lo que nos paso es que teníamos un archivo Kernel.c que utilizaba Planificador.h y este Utils.h. Cuando Kernel importa el Planificador, esta obligado a importar Utils. Al momento de llamar al LargoPlazo (que es la función que utiliza el archivo Kernel del Planificador) quiere volver a importar Utils y como los semáforos están ahí declarados, me dice que se importa dos veces. Para solucionarlo nos dijeron que...:
1. La solución que acabas de expresar fue una de las que nos dieron
2. Directamente hacer la declaración de los semáforos entre muchas cosas mas dentro de la shared library, para evitar esa doble importación
3. Evitar usar un archivo intermedio o sea planificador
Ahora tenemos que intentarlo realizar que era lo que íbamos a intentar hoy.
Desde ya gracias por la atención y apenas lo solucionemos o no y nos volvemos a trabar, lo comento para que quede registrado.

**Comment by RaniAgus** [comment]
¡Buenas @Danymmereles! ¿Pudieron resolverlo? Saludos

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, ante cualquier consulta pueden reabrirlo o abrir uno nuevo. Saludos

**Comment by Danymmereles** [comment]
Buenas tardes,

Queria comentarles la solucion que encontramos para esto con la ayuda de @RaniAgus y @mesaglio

En el .h donde queremos declarar la variable global que utilizaremos en los otros archivos hay que declararlo con un extern. A su vez, como el extern no reserva memoria, hay que declararlo en el .c que le corresponde a ese .h

Por ejemplo
utils.h
-> extern t_log* logger

utils.c
-> t_log* logger

Desde ya muchas gracias a ambos.
