### ISSUE TITLE
Duda vm sin interfaz grafica

### ISSUE THREAD

**Issue by AlejoGol** [sisoputnfrba/foro#2676]
Buenas, como hago para compartir el portapapeles de esta vm? Toda la info trata sobre la que tiene interfaz grafica y no me estaría funcionando en esta. Nada de guest aditions ni setear el "compartir portapapeles" de vbox estaria andando.

Principalmente lo que quiero lograr es copiar la ssh key generada por la vm para poder clonar el proyecto.

**Comment by iago64** [comment]
Buenas! Cómo va?

Para la VM sin interfaz gráfica no van a poder compartir el portapapeles ni nada, ya que justamente es una vm que solo expone una consola, para conectarse pueden usar cualquier cliente ssh y ahí van a poder tener el portapapeles del sistema del cual se conecten.

Justo en el post del Formato de entrega virtual (como era en la época de pandemia) tenemos algunas recomendaciones de terminales que pueden usar para conectarse por ssh a las VMs server https://www.utnso.com.ar/1c2020-formato-de-entrega-virtual/

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Quisiera agregar a lo que dijo Dami, también tenemos un video que explica cómo [reenviar puertos en VirtualBox para conectarse por SSH a una Ubuntu Server](https://youtu.be/SDeqYSxFd10) :+1:

**Comment by iago64** [comment]
@AlejoGol Cómo va? Te sirvieron las respuestas? Necesitas una mano con algo mas?

Saludos.-

**Comment by iago64** [comment]
Cerramos por inactividad, cualquier cosa lo pueden volver a abrir 😄
