### ISSUE TITLE
Pruebas FIFO -- Caso PLANI y SUSP.

### ISSUE THREAD

**Issue by matiastito** [sisoputnfrba/foro#2677]
Buenas tardes, espero anden bien, los molestamos por las pruebas.

Estamos haciendo la de SUSP y PLANI.

Por SJF nos anda bien, quiero decir, en el roden indicado en el documento de prueba; el tema es FIFO, nos está terminando en este orden:

- SUSP -->  S3 y luego S1, y S2. Yo creo que está bien pero en el documento de prebas dice otra cosa.
- PLANI --> P2 y luego P1 y P1 estos ultimos dos en el orden lanzado. Yo creo que está bien pero en el documento de prebas dice otra cosa.

Y la verdad es que haciendo una prueba de escritorio, _creo_ que está mal el orden del doc de pruebas para esos casos de FIFO.

Gracias!

**Comment by LeandroCarbajales** [comment]
Buenas!
Ese orden de finalización es correcto! Por lo que veo en el documento de pruebas no está detallado el orden de finalización esperado para FIFO, pero si hacen un GANTT de los mismos les debería dar ese orden de finalización :)

**Comment by matiastito** [comment]
Muchas gracias!
