### ISSUE TITLE
Forzar cierre de socket después de matar proceso

### ISSUE THREAD

**Issue by Pekerle** [sisoputnfrba/foro#2678]
Hola, buenas noches. 

Creo el issue porque me lo pidió Damian después de hablarlo hoy en el laboratorio, más que nada para que quede constancia del comando. 

En resumen, después de ejecutar los módulos y matarlos con `Ctrl+C`, se tiene que esperar 1 minuto aprox. para volver a ejecutarlos sin problemas porque, al no haber hecho su correspondiente `close()`, Linux tarda cierto tiempo entre que mata el proceso y cierra el socket, por lo que resulta algo tediosa la espera entre pruebas.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Probablemente esto se deba a que a la hora de intentar hacer `bind()` éste les devuelva el error:

```log
Address already in use
```


Pueden agregar las siguientes 2 líneas después de llamar a `socket()` para setear ese puerto como reusable antes de llamar a `bind()`:

```c
int fd; // este sería el File Descriptor que devuelve socket()

int yes = 1;
setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &yes, sizeof(yes));
```

Ahí lo dejé anotado para agregarlo a la guía de sockets.

Saludos

**Comment by RaniAgus** [comment]
¡Buenas @Pekerle! ¿Pudieron probarlo? Saludos

**Comment by Pekerle** [comment]
Mil disculpas por la respuesta tardía, suelo avanzar con el tp los fines de semana y, sumado a que estaba abstrayendo la lógica de conexiones a una biblioteca compartida, tardé más de lo esperado en probarlo.

Agregué lo que sugeriste, probé ejecutando varias veces los módulos y parece haberse solucionado el problema.

Muchas gracias por la respuesta, saludos.
