### ISSUE TITLE
Instruccion READ

### ISSUE THREAD

**Issue by GonzaloMartinezSa** [sisoputnfrba/foro#2679]
Buenas.  Mi grupo y yo vamos bastante bien con el TP, pero resulta que hay algo que dejamos de una manera hasta ahora, que no sabemos muy bien la manera que pide el enunciado de hacerla. Es sobre la instruccion READ, que en el enunciado aparece así:

``` 
READ(dirección_lógica): Se deberá leer el valor de memoria correspondiente a esa dirección
lógica e imprimirlo por pantalla. 
```

Quiere decir por la consola que mandó a correr el programa? Esto nos parecía raro, porque significa que la Cpu (donde se ejecuta la instruccion READ) tiene que mandarle lo que leyó al Kernel, para que este se lo mande a la consola (no?). 

O sea: CPU -> KERNEL -> CONSOLA en medio de todo lo que está pasando.

O es que la Cpu va a tener que conocer a la consola y hacerlo desde ahí? O tal vez ninguna de estas y es otra cosa?

Saludos.

**Comment by LeandroCarbajales** [comment]
Buenas! Imprimirlo por pantalla (o loguearlo) en CPU :)

**Comment by LeandroCarbajales** [comment]
Hola @GonzaloMartinezSa !
Te resolvió la duda? Se puede cerrar el issue?

**Comment by GonzaloMartinezSa** [comment]
Sí, ahí lo cierro
