### ISSUE TITLE
Pruebas - SUSPE

### ISSUE THREAD

**Issue by Salacas** [sisoputnfrba/foro#2680]
Buenas! Cómo andan? Puede ser que SUSPE_2 en realidad no se suspenda? porque el tiempo de i/o es de 5000 y TIEMPO_MAXIMO_BLOQUEADO es de 8000. En el enunciado dice que se tendría que suspender pero por lo que puedo ver no sería así. No se si me estoy pasando algo por alto.
Muchas gracias, un saludo

**Comment by iago64** [comment]
Buenas! Cómo va?

No estas teniendo en cuenta el tiempo extra que va a estar esperando bloqueado antes de iniciar la I/O

Saludos.-

**Comment by Salacas** [comment]
Creo que entendí. En bloqueado pueden estar multiples procesos pero hay una cola de espera para I/O, no? Es decir que en I/O puede estar solo un proceso a la vez. Es correcto lo que planteo?

**Comment by LeandroCarbajales** [comment]
Buenas!
Es correcto :), muy similar a como se representan las IO en los ejercicios, ya fue respondido en este issue #2667

Saludos!
        Lean

**Comment by Salacas** [comment]
Gracias chicos, un saludo
