### ISSUE TITLE
Asignacion de memoria

### ISSUE THREAD

**Issue by SofiaPalmieri** [sisoputnfrba/foro#2681]
Buenas, 
Estamos terminando el modulo de memoria y nos dimos cuenta que no estabamos utilizando en ningun lado el parametro que se pasa por consola como tamaño de proceso y nos surgio la duda de si deberiamos reservar memoria para ese tamaño o que si por ej hacemos un "READ 500" deberiamos primero mirar si es menor al tamaño de proceso antes de reservar la memoria.

Gracias,
Sofia.

**Comment by RaniAgus** [comment]
¡Buenas! Ese parámetro **es** el tamaño del proceso en memoria y es independiente al tamaño del archivo de instrucciones (#2563). Sobre el mismo se efectúan las instrucciones READ, COPY y WRITE, por lo que las direcciones lógicas van a entrar siempre en el rango [0; tamaño-1] (#2582).

Saludos

**Comment by SofiaPalmieri** [comment]
Y ese parámetro que se envía por consola debería ser el tamaño mínimo que habría que asignarle a ese proceso?

Gracias por las respuestas!

**Comment by LeandroCarbajales** [comment]
Buenas!
Para separar las cosas, ese parámetro representa el tamaño del proceso (que para este TP no varía a lo largo de su ciclo de vida) por lo que su archivo SWAP necesariamente debería ser de ese tamaño, sin embargo, al haber paginación bajo demanda con asignación fija, la cantidad de marcos que pueda tener presente en memoria no varía con el tamaño sino que eso siempre lo define la config de marcos_por_proceso.

Queda más clara la idea?
Saludos!
     Lean

**Comment by matiastito** [comment]
Hola!

Si, o sea, que ¿TODOS los procesos tienen el mismo esquema de Tablas de Paginas?

Gracias!!!

**Comment by SofiaPalmieri** [comment]
Gracias, me quedo claro!

**Comment by LeandroCarbajales** [comment]
@SofiaPalmieri Buenísimo! Cierro el issue entonces, cualquier cosa lo vuelven a abrir.

@matiastito No entiendo exactamente a qué se refiere la pregunta, el esquema de tablas es para todos los procesos el definido en el enunciado, si te parece abrite un issue nuevo (podés citar este) explayando un poco más la duda así tenemos el seguimiento de las 2 consultas por separado.

Saludos!
     Lean
