### ISSUE TITLE
Codigo de error de escritura

### ISSUE THREAD

**Issue by SofiaPalmieri** [sisoputnfrba/foro#2682]
Buenas,
Vimos que en la pagina 22 del enunciado se mencionaba que ante un pedido de escritura podria haber un error. Cuando se daria dicho error?

Gracias,
Sofia.

**Comment by LeandroCarbajales** [comment]
Buenas!
A efectos del TP, las pruebas van a estar armadas para que no hayan errores, es posible que esa oración haya quedado desactualizada, hoy lo chequeo bien y les confirmo :)

**Comment by SofiaPalmieri** [comment]
Entonces no deberíamos contemplar ningún caso donde se intente escribir en una dirección de memoria invalida?

Muchas gracias por la respuesta!

**Comment by LeandroCarbajales** [comment]
Si lo pueden contemplar buenísimo, pero no será evaluado en las pruebas, por lo que mi recomendación es que se enfoquen en que funcione suponiendo que eso no ocurre :)

**Comment by RaniAgus** [comment]
¡Buenas @SofiaPalmieri! ¿Alguna duda con lo que comentó Lean? Saludos

**Comment by SofiaPalmieri** [comment]
Buenas, todo claro. Mil gracias! Saludos

**Comment by RaniAgus** [comment]
¡Buenísimo! Recuerden que pueden cerrar el issue una vez resuelta la duda :)
