### ISSUE TITLE
[Pruebas] Suspensión SRT

### ISSUE THREAD

**Issue by CarolinaSeoane** [sisoputnfrba/foro#2683]
Hola, teníamos una duda de la prueba de suspensión de SRT.

![image](https://user-images.githubusercontent.com/54453203/172296979-dee08de4-8094-4aec-857f-8233d0615b1e.png)

Corrimos las pruebas y las estimaciones dan bien, el problema es que en el instante que señalé en rojo el SUSPE_3 llega a ejecutar una ráfaga más de CPU. Estuvimos viendo y esto es así porque como el proceso SUSPE_1 se suspendió mientras ejecutaba IO, antes de pasarlo a Ready tenemos que pasarlo a Susp/Ready y hacer la petición a memoria y esto demora un poco entonces el proceso no llega justo en ese instante a Ready, por lo que no se dispara el desalojo y el otro proceso alcanza a hacer otra ráfaga de CPU. Ya en el instante siguiente sí desaloja al SUSPE_3.

¿Esto está bien así o tenemos que resolverlo de alguna manera? Gracias!!

**Comment by LeandroCarbajales** [comment]
Buenas!
Es normal que los desalojos les queden una unidad de tiempo desplazada porque además el proceso en ejecución terminaría de ejecutar el ciclo actual antes de replanificar :)

Saludos!
       Lean
