### ISSUE TITLE
CPU e interrupciones 

### ISSUE THREAD

**Issue by martina-facu** [sisoputnfrba/foro#2685]
Hola, buenos días 
Tengo una consulta sobre como interpretar las interrupciones que le pueden llegar a la cpu. Entiendo que a efectos del tp las únicas interrupciones que deberíamos atender desde la cpu seria cuando hay que sacar un proceso de ejecución por desalojo. Entonces, en las instrucciones que devuelven el pcb al kernel como exit o i/o no haria falta chequar esto porque ya se estaría replanificando y el ciclo de instrucción terminaría en el execute por asi decirlo ¿Esto es correcto?

**Comment by LeandroCarbajales** [comment]
Buenas!
Exactamente :), dado que a efectos del TP (a diferencia de lo que pasa en la realidad) la interrupción solamente la usamos para avisar que hay que replanificar, sería irrelevante ya que al ejecutar IO o EXIT ya se forzaría una replanificación.

Saludos!
       Lean

**Comment by martina-facu** [comment]
Genial entonces, muchas gracias!

**Comment by TomasR264** [comment]
> Buenas! Exactamente :), dado que a efectos del TP (a diferencia de lo que pasa en la realidad) la interrupción solamente la usamos para avisar que hay que replanificar, sería irrelevante ya que al ejecutar IO o EXIT ya se forzaría una replanificación.
> 
> Saludos! Lean

Hola Lean! Consulta, si bien en el TP no se aclara, si un proceso trata de escribir en un lugar donde no debe, ocacionando un seg fault, habria que interrumpirlo y desalojarlo como pasa en la realidad tambien? O solo con mandar el mensaje de error basta?

Gracias! 🚀

**Comment by LeandroCarbajales** [comment]
Buenas!
En la realidad, ante un segfault normalmente se terminaría finalizando al proceso, en el TP no están contemplado errores de dominio como se aclaró en #2682

**Comment by TomasR264** [comment]
> Buenas! En la realidad, ante un segfault normalmente se terminaría finalizando al proceso, en el TP no están contemplado errores de dominio como se aclaró en #2682

Ah listo, muchas gracias, ya me quedo claro :)
