### ISSUE TITLE
Conexión bidireccional KERNEL -> CPU -> KERNEL

### ISSUE THREAD

**Issue by alexisdona** [sisoputnfrba/foro#2686]
Hola!

Tengo una duda con la conexión que hay entre kernel y CPU. En una primera instancia el kernel le envía el PCB al CPU y se queda esperando a que le avise cuando termina el proceso. Lo que veo es que solo con el file descriptor del kernel en el CPU (como cliente de CPU) no alcanza, desde el CPU le envío (send(...) )el paquete con el PCB terminado y la operación TERMINAR_PROCESO, pero del lado del kernel nunca la recibo. Intenté crear un socket con la ip y puerto del kernel en el CPU y cuando el proceso termina le mando a ese file descriptor el PCB con el código de operación para que termine y lo recibe bien la primera vez y el cliente (cpu se desconecta como cliente) y ya no le envía los siguientes PCBs que van terminando.
¿Cómo es la lógica de conexión para que se mantenga?

```
//Kernel.c
 while (cliente_fd != -1) {
		op_code cod_op = recibirOperacion(cliente_fd);
		switch (cod_op) {

...
...
...

	

		    case TERMINAR_PROCESO:
                log_info(logger, "PCB recibido para terminar proceso");
                t_pcb* pcbFinalizado = recibirPCB(cliente_fd);
                pthread_mutex_lock(&mutexGradoMultiprogramacion);
                GRADO_MULTIPROGRAMACION++;
                printf("GRADO_MULTIPROGRAMACION++: %d\n", GRADO_MULTIPROGRAMACION);
                pthread_mutex_unlock(&mutexGradoMultiprogramacion);
                sem_post(&semGradoMultiprogramacion);
```
```
// cpu.c
  while(clienteDispatch!=-1) { // Este el file descriptor del kernel como cliente
		op_code cod_op = recibirOperacion(clienteDispatch);
		switch (cod_op) {
	....
        ....
		    case PCB:
                enviarMensaje("** CPU **Recibi el PCB, termino de ejecutar y te aviso.", clienteDispatch);
                log_info(logger, "me llego un PCB");
		        t_pcb* pcb = recibirPCB(clienteDispatch);


                sleep(5); //simulo tiempo en executing y le aviso al kernel para que lo termine
                enviarPCB(kernel_fd, pcb, TERMINAR_PROCESO); // kernel_fd es el file descriptor del kernel como socket creado a partir de su ip y puerto
		       break;
```
Saludos!
Alexis

**Comment by iago64** [comment]
Buenas! Cómo va?

La idea de las conexiones en este TP es que una vez establecidas no hagas nunca un `close()` del socket, entonces siempre y cuando tengas en claro quien manda y quien recibe los paquetes, vos podes hacer tantos `send()` y `recv()` como quieras y la conexión va a seguir andando.

Saludos.-

**Comment by alexisdona** [comment]
Buenisimo! Ahora estoy pensando cómo sabe el kernel qué consola es a la que debe informar que terminó el proceso. Calculo que poniendo el file descriptor del socket en el PCB me puede servir, no?

**Comment by alexisdona** [comment]
Metí los dos fd de consola y kernel respectivamente en el PCB y cuando el CPU le devuelve el pcb ya procesado no lo recibe el kernel :disappointed: 
No sé qué estoy haciendo mal, pero entiendo que una vez que desde el CPU recibo el como cliente un fd es el del kernel y si a ese fd del kernel le hago un send() debería llegarle algo porque está escuchando.

**Comment by RaniAgus** [comment]
¡Buenas! No entendí bien cómo sería la comunicación, o sea, ¿están intentando hacer un `send()` a Consola desde CPU usando el fd que tiene Kernel?

Los file descriptors pertenecen únicamente al proceso que se conectó, o sea, es completamente factible que al conectar Consola y Kernel:

- En Consola, el socket con el que se hace `connect()` es 4
- En Kernel, el socket que devuelve `accept()` es 12

También, como son de cada proceso, uno no puede "pasarle" el socket a otro proceso, es decir, en el ejemplo anterior no se puede enviar a CPU el socket 12 e intentar hacer `send()` y `recv()` a la Consola desde ahí.

Algo que sí sería válido es guardarse el socket de la Consola en el PCB, enviarlo completo a la CPU y recibirlo más adelante así como se envió. Como un fd es solo un `int`, lo importante es mantener el valor que devolvió `accept()`.

Saludos

**Comment by alexisdona** [comment]
Hola Agus!

> ¡Buenas! No entendí bien cómo sería la comunicación, o sea, ¿están intentando hacer un `send()` a Consola desde CPU usando el fd que tiene Kernel?

No, estoy enviando en el PCB el fd de la consola en el PCB desde el kernel al CPU, para que cuando el CPU termine la ejecución de las instrucciones le diga al kernel que se le conectó que ya terminó la ejecución y éste a su vez le diga a la consola (en el fd que había guardado previamente al crear el PCB en el kernel) que terminó el proceso 

> Algo que sí sería válido es guardarse el socket de la Consola en el PCB, enviarlo completo a la CPU y recibirlo más adelante así como se envió. Como un fd es solo un `int`, lo importante es mantener el valor que devolvió `accept()`.

Claro, esto es exactamente lo que estamos haciendo, lo que me extraña es que en la comunicación consola --> kernel --> consola si está funcionando el enviar mensaje, cuando una consola se conecta desde el kernel le aviso "Recibí tus instrucciones, termino de ejecutar y te aviso".

**Comment by RaniAgus** [comment]
Hmm... 🤔 

¿Es posible que sea un problema de serialización? ¿Pudieron revisar con ayuda del [debugger](https://faq.utnso.com.ar/video-eclipse-debugging) si los mensajes entre Kernel y CPU se envían y reciben correctamente?

**Comment by alexisdona** [comment]
Hola Agus,

Pudimos resolver el tema. Cierro el issue.

Saludos!
Alexis
