### ISSUE TITLE
Remove by condition - Commons

### ISSUE THREAD

**Issue by Gdepablo** [sisoputnfrba/foro#2687]
¡Buenas! Estaba haciendo con mi grupo el SJF y estábamos en duda de si hay alguna función de las commons que te devuelva el index, ya que queremos hacer list_remove para cambiar un proceso de una cola a otra, pero no tenemos la forma de sacar el índice ni sabemos cómo está declarada la lista en las commons para poder loopearla con un while, entonces se nos complica poder manejarnos con esa lista.
Y si decidimos que es una queue, no tenemos el list_get_minimum para calcular cuál de los procesos de la lista de ready tiene menor estimacion de ráfagas. 

```
prox_pcb_a_ejecutar = list_get_minimum(lista_ready,pcb.estimacion_rafagas());
		esperar_syscall(); // espera el interrupt del SO
		pcb_en_ejecucion.estimacion_rafagas() -= rafagas_ejecutadas; // Esto me da las ráfagas que me van a quedar x proceso
		list_add(lista_ready,pcb_en_ejecucion);
		//Add to lista_exec (Acá deberíamos agregar nuestra pcb en ejecucion a lista de exec)

```
elemento = prox_pcb_a_ejecutar;
list_remove_by_condition(&lista_ready,elemento.id_proceso() == prox_pcb_a_ejecutar.id_proceso());

Y a partir de las dos líneas de arriba (que tambien son parte del codigo) viene el problema, que no sé cómo decirle que la condición en el list_remove_by_condition es que el elemento sea igual al id de proceso de mi PCB. O sea que sean del mismo proceso (cosa que no sé si tiene sentido porque no me acuerdo si un proceso podía tener más de una PCB). Entonces esto me tiene dándole vueltas y no encuentro la forma. Tirenme un gancho porfa jaja

**Comment by RaniAgus** [comment]
¡Buenas! Si tu duda es cómo pasar el ID para compararlo con los ID de cada PCB hasta que coincidan, creo que este video es lo que estás buscando: https://www.youtube.com/watch?v=1kYyxZXGjp0 
Saludos

**Comment by Gdepablo** [comment]
Buenas! Ya logramos resolverlo. No pudimos guiarnos mucho del video porque hablaba solo del list_filter y los tipos son distintos. Estaría bueno si se puede indicar en la documentación una guía o video más general sobre las funciones de orden superior ya que algunas son medio difíciles de entender. Gracias!

**Comment by RaniAgus** [comment]
Oops, olvidé mencionar que pueden encontrar ejemplos de uso en los [tests](https://github.com/sisoputnfrba/so-commons-library/blob/master/tests/unit-tests/test_list.c#L207-L219). Saludos
