### ISSUE TITLE
Inicialización del proceso

### ISSUE THREAD

**Issue by matiastito** [sisoputnfrba/foro#2690]
Del enunciado:

> **Inicialización del proceso**
> El módulo deberá crear las estructuras administrativas necesarias y enviar como respuesta el número de tabla de página de primer nivel de ese proceso.

De lo que se lee en el enunciados, las estrucutras de la memoria son:

> - Un espacio contiguo de memoria (representado por un void*). Este representará el espacio de usuario de la misma, donde los procesos podrán leer y/o escribir.
> - Las tablas de páginas, que representarán el espacio de Kernel.
> - Un archivo por proceso, que representarán el espacio de SWAP de cada uno.

Pregunta 1:
¿Se supone que las a lo que se refiere para cada proceso son:
- Las tablas y
- Un archivo por proceso
y que ambos tengas como tamaño el tamaño del proceso?

Pregunta 2:
¿Como diferenciamos el espacio del kernel y el de los procesos (usuarios) dentro de la memoria?

Pregunta 3:
¿Solo se swapea el 'espacio contiguo de memoria'?

Pregunta 4:
¿Los marcos de pagina de hace referecia al espacio contiguo de memoria?

Pregunta 5:
Con respecto a la TLB, ¿es una por proceso?¿cómo se va llenando la TLB?¿qué pasa cuando se repite una página?¿para usar LRU, hay que agrgarlo un campo a la estrucutra verdad?

Muchas gracias, eso por el momento.
Gracias!

**Comment by LeandroCarbajales** [comment]
Buenas!
1- Exacto! Para cada proceso vas a necesitar crear sus tablas y su archivo de SWAP.
2- Como dice en la cita de arriba, el espacio de usuario lo representa ese void* y el espacio de kernel lo representamos con las tablas (ya que las mismas en la realidad están en el espacio de kernel de la memoria)
3- Exacto! Como aclara en el enunciado, no es necesario swapear las tablas para este TP.
4- Exacto, igual que como se ve en los ejercicios :)
5- Es una caché de la CPU por lo que hay una sola, la lógica de uso es igual que como se ve en clases y en los ejercicios :). Pueden agregarse un campo extra con el tiempo de uso/carga si les facilita la implementación.

Saludos!
      Lean
