### ISSUE TITLE
Duda: ¿Proceso puede pasar de NEW a SUSPENDED-READY?

### ISSUE THREAD

**Issue by julian-salinas** [sisoputnfrba/foro#2691]
Hola! En nuestro grupo estabamos re-viendo el planificador del kernel y nos entró la siguiente duda: Si llega un proceso a NEW y no hay cupos de multiprogramación disponibles para que el proceso pueda pasar a READY, ¿El proceso debería quedarse en la cola NEW o debería pasar a SUSPENDED-READY?

En el enunciado, la arista de transición NEW → SUSPENDED-READY no figura, pero teníamos la duda si era una arista que quedaba implícita en la planificación, ya que en (casi) todos los diagramas de 7 estados, dicha arista está presente.

De antemano muchas gracias por su tiempo, saludos cordiales.

**Comment by LeandroCarbajales** [comment]
Buenas!
No tendría sentido la transición porque si el proceso aún no fue inicializado en Memoria no hay nada que suspender.

Más allá de eso, si no me equivoco en los diagramas de 7 estados que vemos nunca hay una transición de NEW -> SUSPENDED-READY (como si la hay de READY->SUSPENDED-READY, pero en este TP no hay ninguna condición para que se dé). Igual si tienen uno a mano lo vemos porque me parecería raro.

Saludos!
        Lean

**Comment by julian-salinas** [comment]
Entiendo, muchísimas gracias por tu respuesta Lean, saludos!
