### ISSUE TITLE
MMU, SWAP y ciclo instruccion

### ISSUE THREAD

**Issue by napetruzzi** [sisoputnfrba/foro#2692]
Buenas, tenemos un par de dudas con mi grupo!

En cuanto al modulo memoria
1.1)Archivo SWAP, como esta conformado? Solo tiene el tamaño del proceso?

1.2) En cuanto al modelado de las tablas de pagina, nos conviene hacerlas como "listas enlazadas" o como matrices?

En cuanto a la MMU

2.1)La dirección física donde se usa? No nos queda claro si solo lo calcula la MMU o si se usa para otra interacción.

2.2)Cuando dice 
```
..las direcciones lógicas se compondrán de la siguiente manera:
[entrada_tabla_1er_nivel | entrada_tabla_2do_nivel | desplazamiento]...
```
Como obtenemos esto? Con que datos?, luego tampoco nos queda claro que hacer con esto

En cuanto a el ciclo de instrucciones

3.1) Cuando en `READ` nos dan la `dirección_lógica`, la cual entendemos es un valor decimal, este se lo pasamos al modulo Memoria para que busque en las tablas el valor, pero no nos queda claro como se relaciona este dato con la tabla.

Desde ya muchas gracias!

**Comment by LeandroCarbajales** [comment]
Buenas!
1.1- Simplemente un archivo del tamaño del proceso (pueden inicializarlo en cero para que sea más legible).
1.2- Dado que las mismas conceptualmente son de tamaño fijo, podrían implementarlas como vectores/matrices si les es más cómodo que listas :)

2 y 3- Toda la lógica de traducción es muy similar a como se ve en clases para paginación bajo demanda salvo por los page fault.
2.1- La posición en Memoria donde deben leer/escribir los 4 bytes
2.2- Con las cuentas dadas en el enunciado se calculan esos 3 valores de la dirección lógica, en clases se suele ver en solamente en binario/hexadecimal.

Saludos!
     Lean

**Comment by napetruzzi** [comment]
Excelente, nos quedo mas claro!
Gracias!
