### ISSUE TITLE
Kernel-Suspension orden de finalizacion

### ISSUE THREAD

**Issue by chelyx** [sisoputnfrba/foro#2693]
Buenas! Estamos teniendo un problema con el orden en el que terminan las pruebas de suspensión en kernel. Termina de ejecutarlos en este orden SUSPE_1, SUSPE_3, SUSPE_2. 
Revisando en el foro encontré el issue #2683 donde muestran un gantt con la ejecución. Mirando el log entre CPU y Kernel a nosotros nos queda algo así el gantt:

![image](https://user-images.githubusercontent.com/34224902/172881657-0a2b402d-e7b0-4a80-982a-11c72b4cac5c.png)

No entiendo porque cuando termina de hacer los 3 no_op de susp_2 quedan 5 "ráfagas" vacías hasta que ejecuta susp_3.  La única que se me ocurre es esperar para ejecutar la consola de susp3 una vez que suspendió p0 (aka susp_1). Esto es así? o deberíamos ejecutar las consolas una atrás de la otra?
Gracias!

**Comment by RaniAgus** [comment]
¡Buenas!

> No entiendo porque cuando termina de hacer los 3 no_op de susp_2 quedan 5 "ráfagas" vacías hasta que ejecuta susp_3.

Esto se debe a que el grado de multiprogramación de la prueba es 2, o sea, no pueden haber más de 2 procesos en READY+EXEC+BLOCKED a la vez.

En este caso, SUSP_3 se debería quedar esperando en NEW hasta que SUSP_1 se suspenda.

Saludos

**Comment by chelyx** [comment]
Hola! 
Justo estaba viendo que me habia quedado mal el config y tenia el grado de multiprogramacion en 4.
Graciasss
