### ISSUE TITLE
Parametros CPU para MMU

### ISSUE THREAD

**Issue by matiastito** [sisoputnfrba/foro#2694]
Hola a todos, la consulta es la siguiente; en la MMU (que está en la CPU) hay que hacer la traducción de dirección lógica a física. Con lo cual necesitaré los siguientes parámetros:

<b style="font-weight:normal;" id="docs-internal-guid-18c82887-7fff-9931-f147-654ba5941d4c"><div dir="ltr" style="margin-left:0pt;" align="center">

TAM_MEMORIA | Numérico | Tamaño expresado en bytes del tamaño de la memoria.
-- | -- | --
TAM_PAGINA | Numérico | Tamaño de las páginas en bytes.

</div></b>

Sin embargo estos están en el archivo de configuración de la memoria y no en el de la CPU. Podemos agregarlos en la cofnig o tenemos que pasarlos de la memoria al kernel?

Gracias!!!!

**Comment by LeandroCarbajales** [comment]
Buenas!
Citando al enunciado (página 16):

> Al iniciarse el módulo, se conectará con la Memoria y realizará un handshake inicial para recibir la configuración relevante de la misma que le permita traducir las direcciones lógicas a físicas. Esto debería incluir al menos cantidad de entradas por tabla de páginas y tamaño de página.

Saludos!
     Lean

**Comment by matiastito** [comment]
Uh! Perdón, se me escapó, gracias!
