### ISSUE TITLE
Sobre lo que se guarda en memoria

### ISSUE THREAD

**Issue by matiastito** [sisoputnfrba/foro#2695]
Hola a todos, primero perdón que vuelva a moelstar con otras consultas:.

Pregunta 1
Sabemos que en el espacio de memoria del usuario vamos a guardar lo que nos pasen en WRITE y COPY; ahora bien:
1-a: Qué tipo de valores vamos a guardar?
1-b: Cómo lo delimitamos? Es decir, como saber donde empieza y termina lo que grabamos con WRITE
Por ejemplo:
WRITE 4 5000
READ 4 ---> tendria que leer 5000 pero cunado traduzcamos el 4 nos va a dar la direccion del primer byte, cómo sabemos cuantoas hay que leer?

Pregunta 2
Dado que debemos  tener una tabla de 1erNivel por proceso. Entonces, la memoria, ¿cómo sabe a qué tabla de 1er nivel acceder si no conoce nada del proceso en ejecución? Es decir, cuando la CPU ejecuta una instruccion por ejemplo WRITE, como el dice a la memoria a que tabla de 1er nivel debe ir?

Pregunta 3
3.a Como inicializamos las tablas de paginas de un proceso? Arracan todo vacio? 
3.b Para saber como inicializar las tablas de 1er y 2do nvel dividos el tamaño del programa por el tamaño de paginas y luego por N para sabes cuatas entradas en la tabla de 1er nivel vamos a usar?
3.c Que pasa si la primera instruccion es un READ sin haber hecho un WRITE?.

Pregunta 4
4.a ¿El tamaño de un proceso es la cantidad de memoria **que va a usar** con sus operaciones de WRITE y COPY? 
4.b Hay que guardar en algun lado de la memoria la lista de instrucciones? (Entiendo que la respuesta en NO pero para asegurarme nomas)

Pregunta 6
¿El limiete de las Direcciones Logicas es del tamaño del proceso? Que es el mismo que el tamaño del SWAP, es decir:
`tamañoFileSwap = tamañoDelPrograma = maximaDireccionLogicaQuePodemosUsar - 1`

Pregunta 7
Por otro lado, y suponiedo que los valores de WRITE se guardan como String, que pasa si el valor que se guarda justo cae al final de la pagina de manera tal que una parte queda en una pagina y la otra en la siguiente. ¿Consideramos ese caso?

Muchas Gracias!!

**Comment by RaniAgus** [comment]
¡Buenas!

1. Cito el enunciado: 

> Cabe aclarar que todos los valores a leer/escribir en memoria serán numéricos enteros no signados de 4 bytes, considerar el uso de uint32_t.

O sea, `WRITE 4 5000` significa "en la dirección lógica 4, escribir el valor 5000".

2. Es por eso que en el PCB del proceso en ejecución deberán guardarse el número de tabla de página de primer nivel 👍🏻 

3. Pueden aprovechar el tamaño del proceso para crear solo las tablas de 1er y 2do nivel necesarias. Como verán en la teoría, todas arrancan con el bit de presencia en 0. 

Si la primera instruccion es un READ sin haber hecho un WRITE, simplemente leen el valor como cualquier otro. Al igual que ocurre en C con las variables sin inicializar, probablemente ese dato que lean sea "basura".

4. Sí, como comentó Lean en #2563, ese parámetro es el tamaño del proceso en memoria y es independiente al tamaño del archivo de instrucciones.

5. En la memoria, no. En este TP deben guardar la lista de instrucciones en el PCB del Kernel (y pasársela a la CPU cuando entre en EXEC).

6. Sí, como comentó Lean en #2582, las direcciones lógicas que reciben WRITE/READ/COPY siempre van a entrar dentro de ese tamaño.

7. No hace falta que contemplen ese caso.

Saludos

**Comment by matiastito** [comment]
Muchas gracias, y perdón; entonces por 

> Es por eso que en el PCB del proceso en ejecución deberán guardarse el número de tabla de página de primer nivel 👍🏻

deberia pasarle desde la CPU a la Memoria ése número de tabla que podria ser el indice de una lista?

Y perdón si fueron preguntas muy obvias.

Saludos!

**Comment by RaniAgus** [comment]
> Y perdón si fueron preguntas muy obvias.

¡Tranqui! No hay preguntas obvias, siéntanse tranquilos de hacer [todas las necesarias para aprobar este TP](https://www.youtube.com/watch?v=IuZKB1fxKW4&t=22s) 😄 

> deberia pasarle desde la CPU a la Memoria ése número de tabla que podria ser el indice de una lista?

Exacto, la idea es que lo pasen junto con la _entrada de la tabla de primer nivel_ (que se calcula a partir de la dirección lógica) para que la memoria recorra las tablas (que pueden estar en una lista de listas) y le devuelva a la CPU el dato del número de tabla de segundo nivel.

Saludos

**Comment by matiastito** [comment]
Muchas gracias! :D

> Exacto, la idea es que lo pasen junto con la entrada de la tabla de primer nivel (que se calcula a partir de la dirección lógica) para que la memoria recorra las tablas (que pueden estar en una lista de listas) y le devuelva a la CPU el dato del número de tabla de segundo nivel.

Eso seria el primer acceso (si no está en la TLB), lo que decís arriba es el paso (1) de:

1- Un primer acceso para conocer en qué tabla de páginas de 2do nivel está direccionado el marco en que se encuentra la página a la que queremos acceder
2- Un segundo acceso para conocer en qué marco está la misma
3- Finalmente acceder a la porción de memoria correspondiente (la dirección física).

Restarían 2 y 3. ¿no?

Gracias!!!

**Comment by RaniAgus** [comment]
Así es 👍🏻

**Comment by matiastito** [comment]
Gracias!!!
