### ISSUE TITLE
Problema con path de config

### ISSUE THREAD

**Issue by LucasBatalla** [sisoputnfrba/foro#2696]
Buenas tardes!

Me surgió un problema con el path del config que paso por parámetro a config_create, me tira este error:

`config_create - WARNING: the file ../config-kernel-1.config contains a \r\n sequence - the Windows new line sequence. The \r characters will remain as part of the value, as Unix newlines consist of a single \n. You can install and use `dos2unix` program to convert your files to Unix style. `

Me resulta raro que a mis compañeros no les tira el mismo error ya que todos lo corremos desde WSL en Windows.

Imprimí el path por pantalla y me sale igual al que paso por parámetro, no entiendo cual es el caracter que no reconoce. 

Tenemos una función crear_config en donde pasamos dicho path y su segundo parámetro es un char* (que seria el path).

`crear_config(&configKernel, "../config-kernel-1.config", loggerKernel);`

Existe alguna solución?, ya que instale el programa que me decía en el error, "dos2Unix", pero sigue tirando el mismo error.

Desde ya, muchas gracias!.

**Comment by iago64** [comment]
Buenas! Cómo va?

Lo que les esta diciendo ahi es que estan teniendo los saltos de linea en formato windows `\r\n`, lo que deberían hacer es eliminar esos `\r\n` y reemplazarlos por `\n`.
El path esta bien (siempre y cuando lo tengan en la carpeta anterior al ejecutable)

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! 
Ese error significa que el archivo config tiene caracteres `\r` porque es el "enter" de Windows. Te paso una breve explicación de su origen en este comment: https://github.com/sisoputnfrba/foro/issues/1832#issuecomment-657300753

Una posibilidad es que en el editor de texto que uses quizás tengas configurado para guardar el archivo config usando saltos de línea tipo Windows. En VSCode aparece en la barrita de abajo como "CRLF" (por Carriage Return Line Feed):

![image](https://user-images.githubusercontent.com/39303639/172962800-dfd5c330-bcac-48b0-8526-34a1c4c9181b.png)

Asegurate de cambiarlo a LF (solo Line Feed):

![image](https://user-images.githubusercontent.com/39303639/172962847-88338d96-c4ee-4360-b100-110415116844.png)

Otro posible motivo (que puede ser la razón por la que al resto de tus compañeros no les aparece) es que tu instalación de Git esté configurada para que convertir todos los LF a CRLF al pullear y viceversa al commitear y pushear. Podés cambiar este comportamiento ejecutando:

```
git config --global core.autocrlf false
```

Te paso este [comment](https://stackoverflow.com/a/20653073) para más info sobre cómo funcionan los distintos modos.

Por último, mencionabas que instalaste `dos2unix`, pero, ¿ejecutaste el comando pasándole el archivo config? Ej: `dos2unix ./config-kernel-1.config`

También podés directamente ejecutar `dos2unix` sobre todo el repo de esta forma:

```
cd carpeta-del-repo
find . -type f -print0 | xargs -0 dos2unix
```

Saludos

**Comment by LucasBatalla** [comment]
Buenísimo, probé usando el dos2unix y ahora funciona!!.

Muchas gracias a ambos!! 😄 

Saludos!.
