### ISSUE TITLE
[CPU] Duda sobre estructura de TLB

### ISSUE THREAD

**Issue by brunomassaccese** [sisoputnfrba/foro#2698]
Hola a todos,

Mi duda tiene que ver con la estructura que tiene que tener la TLB, más que nada para saber como pensar la lógica de los algoritmos de reemplazo necesarios.

El enunciado dice:
"Para agilizar el proceso de traducción, el módulo CPU contará también con una caché TLB. La misma deberá tener **### obligatoriamente** la estructura [ página | marco ] y se definirá por archivo de configuración".

Mi idea es poner 2 timestamps dentro de la estructura de la TLB para saber cuando se crea un registro en ella (para el algoritmo FIFO), y para saber cuando es utilizado por última vez ese registro (para el algoritmo LRU), pero veo que el TP resalta la palabra "obligatoriamente" y no entiendo si está relacionado a que la estructura de la TLB tiene que tener si y solo si página y marco, o si debe tener mandatoriamente esos 2 campos pero además se le pueden agregar otros.

Muchas gracias por su ayuda!

**Comment by LeandroCarbajales** [comment]
Buenas!
Hace referencia solamente a que no tiene una columna de proceso, y por ende a nivel traducción es solamente (Página, Marco). Pero pueden agregarle campos auxiliares para facilitarse la implementación de los algoritmos, por ejemplo instante de carga y/o tiempo de última referencia.

Saludos!
        Lean

**Comment by brunomassaccese** [comment]
Perfecto Lean, super claro.
Muchas gracias!

Bruno

**Comment by LeandroCarbajales** [comment]
Buenísimo! Cierro el issue entonces, cualquier cosa lo vuelven a abrir.

**Comment by 23737k** [comment]
Perdón, justamente sobre esto. El enunciado dice que se le pueden agregar campos auxiliares para los algoritmos de reemplazo, pero ¿se le pueden agregar otros? Por ejemplo, en nuestro caso queríamos agregarle un campo booleano que indica si la entrada está vacía. 
Gracias.
