### ISSUE TITLE
Duda sobre Tabla de 1er Nivel

### ISSUE THREAD

**Issue by maxicaleca** [sisoputnfrba/foro#2699]
Buenas, a raíz de [esta issue](https://github.com/sisoputnfrba/foro/issues/2610) nos surgió la siguiente duda:

¿Cómo deberíamos manejar la situación en caso  de que venga un proceso que no pueda ser direccionado en 1 sola tabla de 1er nivel teniendo en cuenta la config  cant_entradas^2 * tam_página ? 

No deberíamos admitirlo y listo ?

Gracias
Saludos

**Comment by LeandroCarbajales** [comment]
Buenas!
La respuesta corta para el TP: no va a ocurrir :)
La respuesta coneptual: sería equivalente a que un proceso sea más grande que el direccionamiento lógico del sistema, que es imposible.

Saludos!
      Lean

**Comment by maxicaleca** [comment]
Perfecto, gracias Lean.
