### ISSUE TITLE
Duda sobre los cálculos que hace la MMU

### ISSUE THREAD

**Issue by thiagocabrera** [sisoputnfrba/foro#2701]
Buenas, con mi grupo estuvimos organizando como arrancar con el Checkpoint 4, y nos surgió una duda con respecto a la traducción de direcciones lógicas:
Entendemos que la tabla de 1er nivel sería como la siguiente:

![image](https://user-images.githubusercontent.com/82061778/173252444-65a11f46-cd6b-45e4-9d1f-7d45acc51deb.png)

Por lo que para acceder al nro de tabla de 2do nivel, necesitaríamos el nro de página (del proceso correspondiente).
Lo que no entendemos es por qué utilizamos la entrada a la tabla de 1er nivel, que sigue esta cuenta:

> entrada_tabla_1er_nivel = floor(número_página / cant_entradas_por_tabla)

Siendo que el número de página, que sigue la siguiente ecuación, a nuestro entendimiento ya es el número de página que estamos buscando

> número_página = floor(dirección_lógica / tamaño_página)

Tampoco entendemos mucho que lógica siguen las cuentas que hay que hacer para traducir las direcciones lógicas desde entero al formato especificado en la consigna.

Gracias!

**Comment by RaniAgus** [comment]
¡Buenas! 

La estructura de la tabla de 1er nivel es la que figura en el enunciado:
![image](https://user-images.githubusercontent.com/39303639/173272178-cf55fa9d-27f5-4783-a0ee-e9f8bf379c6f.png)
La primera columna no tiene nombre porque es el **número de entrada** (o sea, el índice, el número de fila), que se obtiene del cálculo que citabas.

También tengan en cuenta que no puede haber dos entradas referenciando al mismo número de tabla de páginas de 2do nivel.

> Tampoco entendemos mucho que lógica siguen las cuentas que hay que hacer para traducir las direcciones lógicas desde entero al formato especificado en la consigna.

No entendí la pregunta, tanto las direcciones lógicas como las físicas son números enteros.

Saludos

**Comment by RaniAgus** [comment]
El `nro_pagina` vendría a ser una combinación entre los valores de entrada de tabla de páginas de 1er y 2do nivel. O sea, mirando el ejemplo:

- Página 0 = entrada 1er nivel 0, entrada 2do nivel 0 ---> Frame 15
- Página 1 = entrada 1er nivel 0, entrada 2do nivel 1 ---> Frame 12
- Página 2 = entrada 1er nivel 0, entrada 2do nivel 2 ---> Frame 10
- Página 3 = entrada 1er nivel 1, entrada 2do nivel 0 ---> Frame 6
...
- Página 8 = entrada 1er nivel 2, entrada 2do nivel 2 ---> Frame 17

También ese `nro_pagina` será lo que guarden en la TLB de la CPU una vez realizada la traducción, para así en un futuro ahorrarse accesos a memoria cada vez que se intente acceder a la misma página.

Saludos

**Comment by lucas-marmo** [comment]
Ah okey perfecto ahí vamos entendiendo mejor. No tenemos directamente el número de página en la primer tabla como cuando hacemos paginación de un solo nivel, sino que entonces lo componemos del desplazamiento en ambas tablas.
Me surge la pregunta de si entonces una tabla de segundo nivel va a corresponder solo a un proceso? Concluyendo de esto: 
> También tengan en cuenta que no puede haber dos entradas referenciando al mismo número de tabla de páginas de 2do nivel.

Y también sobre esto concluyo que la cantidad de entradas por tabla va a ser igual a la cantidad de tablas de segundo nivel que corresponden a un solo proceso, en este caso serían 3 de segundo nivel solamente del proceso 1:
> Página 0 = entrada 1er nivel 0, entrada 2do nivel 0 ---> Frame 15
Página 1 = entrada 1er nivel 0, entrada 2do nivel 1 ---> Frame 12
Página 2 = entrada 1er nivel 0, entrada 2do nivel 2 ---> Frame 10
Página 3 = entrada 1er nivel 1, entrada 2do nivel 0 ---> Frame 6
...
Página 8 = entrada 1er nivel 2, entrada 2do nivel 2 ---> Frame 17

Última pregunta que me queda: nosotros pensábamos tener guardado el acceso a las tablas de primer nivel en un diccionario donde la key quizás podría ser el pid del proceso, entonces ese es el número de tabla que se está guardando el pcb, está bien la idea?

Gracias de nuevo

**Comment by thiagocabrera** [comment]
Leyendo el issue #2705 ya la última duda nos quedaría resuelta, entonces la cambio un poco en base a eso:
Podríamos hacer que las tablas sean una lista y guardar la posición de inicio de la tabla de x proceso en su PCB? O debe ser parte misma de la memoria gigante representada por el void*?

**Comment by LeandroCarbajales** [comment]
Buenas!
Una recomendación más del `nro_pagina`, se lo pueden pasar de CPU a Memoria en los mensajes que necesiten para no tener que hacer cuentas (que ya hizo la CPU) para ya saber dónde leer/escribir en SWAP por ejemplo.

> Me surge la pregunta de si entonces una tabla de segundo nivel va a corresponder solo a un proceso?

Exacto! En definitiva, las tablas de 2do nivel de un proceso no son más que la tabla de páginas de siempre pero "paginada".

> Y también sobre esto concluyo que la cantidad de entradas por tabla va a ser igual a la cantidad de tablas de segundo nivel que corresponden a un solo proceso, en este caso serían 3 de segundo nivel solamente del proceso 1:

Claro! En definitiva `entradas_por_tabla ^ 2 * tam_página` es el direccionamiento lógico del sistema :)

> Podríamos hacer que las tablas de 1er nivel estén en una única lista (t_list) y guardar la posición de inicio de la tabla de x proceso en su PCB? O debe ser parte de la misma memoria gigante representada por el void*?

Como aclara el enunciado, el void* lo tomamos solamente como el espacio de usuario de la memoria, por lo que las tablas no ocuparían espacio del mismo :)

Les aclara las dudas?
Saludos!
      Lean

**Comment by thiagocabrera** [comment]
Perfecto entonces, todo clarísimo, gracias a los dos!
