### ISSUE TITLE
Grado De Multiprogrmacion - Memoria VS Kernel

### ISSUE THREAD

**Issue by matiastito** [sisoputnfrba/foro#2702]
Hola a todos, espero estén bien, los molesto porque tengo algunas consultas con respecto a cómo se gestionan los marcos por proceso.

1. Debemos contraol de alguna manera que:
El gradoMultiprogramacion indicado en el Kernel sea igual al que nos da la cuenta `TAM_MEMORIA / MARCOS_POR_PROCESO` (modulo memoria)
Es decir, tenemos que hacer un chequeo nosotros de nuestro lado o asumimos que todo esos parametros van a ser consistentes.
2. Tenemos que tener una estrucutra adicional para gestionar los Marcos asignados y saber cual se va a reemplar o conviene usar la estructura ya dada, es decir, iterar las tablas del proceso o agregar una estrucutra adicional?
3. Cuando incializamos uun proceso en memoria, ¿como asignamos los marcos? 
4. Podemos ir asginando los marcos secuencialmente?
5. ¿Es un requerimiento que las tablas de páginas no tengan N y tengan la cantidad de paginas requeridas por el tamaño del proceso?

Muchas gracias!
Espero haber sido claro con las preguntas.

Saludos!

**Comment by RaniAgus** [comment]
¡Buenas!
1. No hace falta, pueden asumir que los valores van a ser consistentes (y si ven que hay alguna prueba que no los tiene, avísennos porque probablemente sea un error de tipeo :P)
2. Pueden tener una estructura adicional para simplificar los cálculos 👍🏻 
3. Deberían irlos asignando a medida que vayan cargando páginas, por lo que al iniciar un proceso en memoria no haría falta hacer nada por ese lado.
4. ¿O sea, ir chequeando desde el 0 al N-1 hasta encontrar uno libre? Si, creería que es lo más sencillo 😅
5. No es requerimiento, si ven que están jugados pueden crear tablas de 2do nivel para todas las entradas de 1er nivel, aunque estaría bueno que usen el tamaño del proceso para crear solo las necesarias (por ej, si ven que el tamaño da 6 páginas y hay 4 entradas por tabla, lo ideal sería crear solo 2 tablas de 2do nivel en vez de las 4).

Saludos
