### ISSUE TITLE
[Memoria] / [CPU] Popurrí de dudas...

### ISSUE THREAD

**Issue by Caruso-Martin** [sisoputnfrba/foro#2703]
### CPU
- En el cálculo de `entrada_tabla_2do_nivel`, ¿“`mod()`” vendría a representar el operador `%` o es otra cosa? 

### MEMORIA
- En la inicialización de un proceso,  ¿qué pasaría si un proceso tiene `tamanio_proceso = 161 bytes`?.  Asumiendo que el .config tiene los siguiente campos `tamanio_pagina = 40 bytes` y `marcos_por_proceso = 4` 

- Leyendo otros issues, nos enteramos que el archivo .swap tiene su tamaño definido por el parámetro que ingresamos por el modulo **Modulo Consola**, ¿Deberíamos inicializar el archivo con una cantidad de `uint32_t` equivalente a `tamanio_proceso`? (¿qué pasaría si un proceso tiene `tamanio_proceso` que no es múltiplo de `sizeof(uint32_t)`?)

- Al momento de inicializar/modificar el archivo .swap, ¿podríamos utilizar `fwrite()`?; la pregunta nos surgió ya que escuchamos de la función `mmap()`. ¿Cuál es mas recomendable para nuestro TP?

**Comment by RaniAgus** [comment]
¡Buenas!
1. Sí, de hecho, "mod" es una abreviación para [modulo](https://www.geeksforgeeks.org/modulo-operator-in-c-cpp-with-examples/).
2. Recuerden que la ventaja de utilizar memoria virtual es que se puede direccionar más memoria que la disponible. En este caso, su proceso va a tener 5 páginas y 4 marcos asignados.
3. El tamaño del proceso está definido en bytes. No se preocupen que en las pruebas siempre les vamos a dar tamaños múltiplos de 4.
4. Pueden usar cualquiera de las dos. La ventaja de `mmap()` es que al mapearse el archivo a un `void*` las operaciones de lectura y escritura son simplemente un `memcpy()` (lo van a ver explicado más en detalle en la teoría). Por otro lado, si es un `FILE*` van a tener que usar las operaciones de archivo que ya conocen.

Saludos

**Comment by Caruso-Martin** [comment]
¡Gracias por las respuestas, me quedaron claras bastantes cosas!

Me quedo la duda de la forma de inicializar el archivo .swap. Si yo se que el `tamanio_proceso = 40` y `tamanio_pagina = 20`, ¿como deberíamos inicializar dicho archivo?

Una posible idea que se nos ocurrió fue inicializarlo 10 `uint32_t` de valor "0". Por ende, el archivo se vería como una cadena de "0s". Y para diferenciar que valores pertenecen a cual pagina, deberíamos movernos 5 `uint32_t`

**Comment by RaniAgus** [comment]
Sip, pueden inicializarlo con ceros o simplemente truncarlo y que en su contenido queden bytes "basura", es indistinto 👍🏻
