### ISSUE TITLE
Cómo crear y leer el SWAP

### ISSUE THREAD

**Issue by Gdepablo** [sisoputnfrba/foro#2704]
Buenas, con mi grupo estamos teniendo problemas con el tema del archivo de SWAP, ya que entendemos que para swapear, no puede ser un simple 'archivo de texto' sino que debe ser un archivo que adentro tenga paginas, ya sea en lista o una abajo de la otra.
Entonces creo que no sirve el fopen en a+ para escribirlo si no existe, y tampoco entendemos cómo sacar una página de ese swap y reemplazarla por otra.
Leí lo de mmap y no me quedó claro (issue #2703) si ayuda en algo, tampoco del todo su uso.

Nosotros habiamos pensado en algo asi, pero no estaría dando resultado, porque si no son strings, no estaríamos sabiendo cómo 'leer' la pagina o lo que sea que haya en swap.

```c
while(!eof(archivo)) {
		fread(a,sizeof(archivo)+1,1,archivo);
		//Mecanism de lectura para el swap y que me devuelva la pag
	y = elemento;
	}
```
	
La idea al final de todo este while es que busque la página en el swap y si la encuentra la guarde en una variable auxiliar de tipo pagina que despues es usada en el list_replace para reemplazarla por la pagina anterior.

Otra duda sería si es mejor usar lista (commons.h) o array en C, porque creemos que el array se hace muy cuesta arriba (hay que llenarlo de ifs para iterar y todo eso) mientras que la lista no.
Además, la tabla de paginas de primer nivel, tendria solo un puntero a la tabla de paginas de segundo nivel o tendria algo mas? 

EDIT1:  Estaba fijándome en el list_find, y el problema es que hay que pasarle una función que tenga un único parámetro (según las pruebas de las commons) por tanto, yo no sé cómo hacer un subprograma que compare si una pagina de mi array de paginas tiene igual numero de frame que otra porque solo le puedo pasar un parametro. A menos que haga la comparacion a mano con un while pero no es la idea creo yo.
Dejo la definicion:
```c
	void *list_find(t_list *, bool(*closure)(void*)); 
```	
Así intenté plantearlo yo:
```c

list_find(tabla_segundo_nivel[numero_pagina].paginas,es_igual_a())

bool es_igual_a(pagina paginaPedida) {
return tabla_segundo_nivel.paginas == paginaPedida;
}
```
No sé si esto funciona, creo que no, porque estoy comparando un array con una pagina y no lo estoy iterando. No se me ocurre cómo hacerlo.
*bool es una librería que me traje de <stdbool.h>

**Comment by RaniAgus** [comment]
¡Buenas!

> entendemos que para swapear, no puede ser un simple 'archivo de texto' sino que debe ser un archivo que adentro tenga paginas, ya sea en lista o una abajo de la otra.

En realidad los archivos (al igual que la memoria) son simplemente un array de bytes. Y las páginas, al igual que los frames, son solo una forma que tiene el sistema operativo de organizar ese array de bytes.

Por ejemplo, si creamos un archivo `main.c` y lo leemos usando el comando `hexdump -C main.c`, veremos algo como esto:

```
00000000  23 69 6e 63 6c 75 64 65  20 3c 73 74 64 6c 69 62  |#include <stdlib|
00000010  2e 68 3e 0a 23 69 6e 63  6c 75 64 65 20 3c 73 74  |.h>.#include <st|
00000020  64 69 6f 2e 68 3e 0a 0a  69 6e 74 20 6d 61 69 6e  |dio.h>..int main|
00000030  28 29 20 7b 0a 09 70 72  69 6e 74 66 28 22 48 65  |() {..printf("He|
00000040  6c 6c 6f 20 57 6f 72 6c  64 21 21 21 22 29 3b 0a  |llo World!!!");.|
00000050  09 72 65 74 75 72 6e 20  30 3b 0a 7d 0a           |.return 0;.}.|
0000005d
```

- La 2da y la 3ra columna es literalmente el contenido del archivo en disco escrito en hexadecimal. ¡Es solo un conjunto de bytes!
- La 4ta columna tiene lo mismo que las 2 anteriores, pero traduciendo ese número en hexadecimal a caracter ASCII. Literalmente si vos tomás cualquier secuencia, (ej: `23 69 6e 63 6c 75 64 65`), y traducís byte a byte leyendo de la tabla ASCII vas a ver que en la otra columna dice el resultado (ej: `#include`).

De hecho, si se fijan en la firma de `fwrite`/`fread`/etc van a ver que recibe un `void*`, no un `char*`. Entonces, en definitiva, para pasar una página a un frame o viceversa simplemente hay que leer o escribir el archivo en la posición indicada como cualquier porción de memoria.

> Leí lo de mmap y no me quedó claro si ayuda en algo, tampoco del todo su uso.

Pueden investigar sobre su uso (aunque les aconsejo verlo en la clase de teoría primero para entender conceptualmente en qué consiste), pero básicamente permite manejar el contenido de un archivo como si fuera una porción de memoria (o sea, un `void*`).

> Además, la tabla de paginas de primer nivel, tendria solo un puntero a la tabla de paginas de segundo nivel o tendria algo mas?

Ojo, recuerden lo que hablamos con Lean el sábado pasado, ¡no es un puntero! Es solo un índice.
¿Por qué crees que debería tener algo más?

> Estaba fijándome en el list_find, y el problema es que hay que pasarle una función que tenga un único parámetro (según las pruebas de las commons) por tanto, yo no sé cómo hacer un subprograma que compare si una pagina de mi array de paginas tiene igual numero de frame que otra porque solo le puedo pasar un parametro.

Misma respuesta que en https://github.com/sisoputnfrba/foro/issues/2687#issuecomment-1149827466 😉 

Saludos

**Comment by Gdepablo** [comment]
Porque sería raro tener un struct de una sola línea (un indice), por eso pensaba que capaz tendría que tener algo más. Luego, me fijé en el ejemplo de las commons lo del list_find; y entiendo cómo funciona, pero justamente los ejemplos ahí comparan contra la edad hardcodeada de una persona. Nosotros no podemos hardcodear una pagina porque no sabemos contra qué tabla de páginas va a comparar (Sabiendo que cada proceso tiene su tabla de páginas, necesitamos el indice para acceder a la de ese x proceso). Entonces por eso, para mí, debería recibir más de un parámetro pero esa función no lo permitía.

**Comment by MatiasDellafiore** [comment]
Buenas, no nos quedó muy claro lo del SWAP. Nos tiene bastante confundido el como interpretar el `.swap`, más que nada porque no nos cierra mucho interpretarlo como archivo de texto, teniendo en cuenta también que tendríamos que, de alguna forma, guardar los datos que tiene para hacer el reemplazo.

Saludos.

**Comment by LeandroCarbajales** [comment]
Buenas!
Solamente es un archivo de texto si lo interpretan de a 1 byte, si lo interpretan de a 4 bytes sería un archivo de (uint_32), en definitiva el archivo guarda bytes, no "texto" ni "páginas".

Me hace un poco de ruido toda la operación de búsqueda que están intentando hacer para recorrer el archivo, si habíamos visto que en definitiva ya saben dónde leer/escribir `nro_página * tamaño_página` y cuántos bytes (tam_página)

**Comment by MatiasDellafiore** [comment]
No recordamos muy bien cómo era para recorrer el archivo, por eso hicimos eso. ¿Nos podrías recordar  como era?

Por otro lado estamos teniendo dificultades con esto

```
typedef struct {
    uint32_t num_tabla;
    pagina *paginas = list_create(); // No puede ser mas de 4 (Lo sacas del config)
} paginas_segundo_nivel_t;
```

Y nos tira este error
![image](https://user-images.githubusercontent.com/83479468/173960009-5284afea-be38-454c-823f-d3037a227aad.png)

¿A qué se puede deber eso?

**Comment by RaniAgus** [comment]
> No recordamos muy bien cómo era para recorrer el archivo, por eso hicimos eso. ¿Nos podrías recordar como era?

En Google encontré esta página que lo explica bien detallado: https://www.programiz.com/c-programming/c-file-input-output 👍🏻 

> ¿A qué se puede deber eso?

Se debe a que en C los structs solamente se utilizan para definir atributos y sus tipos, pero no cómo van a ser inicializados. Para esto último pueden crear una función `paginas_segundo_nivel_create()` que la inicialice, similar a cómo lo hacen los `create` de las commons como [`list_create()`](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/collections/list.c#L31-L36). 

Si les queda alguna duda sobre esta forma de encarar la inicialización de los structs pueden verla explicada más en detalle acá: https://github.com/sisoputnfrba/foro/issues/2668#issuecomment-1145459289

> Un ejemplo de error que nos tira:
> ```
> while(tabla_segundo_nivel[numero_tabla_pagina] -> paginas[iterador_pagina_2].bit_uso != 0
>                     && iterador_pagina_2 <= MARCOS_POR_PROCESO)
> ```
> Esto no funciona porque dice
> 'suscripted value is neither array nor pointer nor vector'

El motivo del error es porque los `t_list*` no son arrays, sino que [tienen una estructura particular](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/collections/list.h#L23-L26) con [nodos enlazados](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/collections/node.h#L21-L25).

Por lo tanto, no es posible acceder a cada elemento utilizando `lista[index]` sino que deberán usar, por ejemplo, [`list_get(lista, index)`](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/collections/list.h#L82-L86).

También, al no ser un array sino un `t_list *` deberán cambiar la forma de definir el struct a:
```c
typedef struct {
    uint32_t num_tabla;
    t_list *paginas; // No puede ser mas de las del config
} paginas_segundo_nivel_t;
```

Saludos

**Comment by LeandroCarbajales** [comment]
Ok!
Queda alguna duda más del issue? Entiendo que Agus respondió en buen medida las dudas :)

**Comment by Gdepablo** [comment]
Gracias!
Otra duda que tenemos con el equipo es: 
Cuál es la diferencia entre entradas por tabla y marcos por proceso?
No nos termina de quedar claro, o sea si nosotros tenemos una lista de paginas y queremos ver que, por ejemplo, no supere la el tamaño permitido, iría entradas por tabla o marcos por proceso?

**Comment by LeandroCarbajales** [comment]
Cierro el issue por inactividad ya que entiendo que la duda fue resuelta en parte también en soporte.
