### ISSUE TITLE
Duda con tablas de páginas y modelado

### ISSUE THREAD

**Issue by JuanPabloVillarreal** [sisoputnfrba/foro#2705]
Buen día, como va? Nosotros habíamos pensado el modelado de las tablas de la siguiente manera:

Primero, vamos a tener una lista de índices, donde cada elemento de esa lista va a ser un struct con la siguiente forma:

**typedef struct {**

t_dictionary tablaPrimerNivel;
 t_list* listaDeTablasDeSegundoNivel;
**} elementoListaIndices (uno por proceso)**

Donde el primer elemento del struct es un map, en el cual la KEY es el numero de pagina y el VALUE es el numeroTablaDePaginaDeSegundoNivel. Y el segundo elemento del struct, es una lista de maps tablaSegundoNivel, que cada uno sería del estilo *t_dictionary tablaSegundoNivel*. En este segundo mapeo, el KEY es el numero de pagina y el VALUE es una estructura (que tiene el bit de presencia, nro de marco, bit de uso y bit de modificado). 

Pero tenemos dudas con las formulas para ir traduciendo las direcciones, ya que nos dan la formula para sacar la entrada de tabla de primer, de segundo nivel y que es algo que hace la MMU. Pero en realidad nosotros le estamos pidiendo a memoria que lo busque con el map. Nosotros con esto "simplificamos la busqueda", pero no sabemos si estaría bien planteado. 

En el caso que este mal, como podríamos encararlo o qué nos convendría hacer? 

![WhatsApp Image 2022-06-13 at 11 24 23 AM](https://user-images.githubusercontent.com/62812983/173386345-16e83fc9-663f-4733-8f1f-292e5f4b9cde.jpeg)

**Comment by RaniAgus** [comment]
¡Buenas! Para entender mejor cómo funciona el proceso de traducción de dirección lógica a física les recomiendo arrancar por la respuesta de Lean en #2689

También, como comentaba en #2596, la idea es que las colecciones de tablas de 1er y 2do nivel sean globales a toda la memoria (o sea, no deberían estar indexadas por proceso). Es por eso que en el PCB cuentan con el número de tabla de 1er nivel.

Saludos

**Comment by LeandroCarbajales** [comment]
Claro! Con tenerlas en una lista, la CPU ya sabría "dónde" (en qué tabla) está lo que necesita, más allá de eso, pueden tener mapeado [pid, tablas] si les facilita algunas operaciones.

Saludos!
      Lean
