### ISSUE TITLE
Swapear un marco

### ISSUE THREAD

**Issue by matiastito** [sisoputnfrba/foro#2707]
Buenas!

Los moelsto porque en una parte del enunciado dice:

> Acceso a tabla de páginas
> El módulo deberá responder lo siguiente:
> Si se trata de una tabla de primer nivel, el número de la tabla de segundo nivel.

¿Esto es asi? Porque como cada entrada de la tabla de 1er Nivel apunta al primer elmento de la tabla de segundo nivel. ¿Como retornas el indica si el indice de la tabla de 2do nivel lo determina el llamado posterior (el que detallo  abajo).
A lo que voy es que deberia retornar la direccion de memoria del inicio de la pagina de 2do Nivel para esa entrada de 1er Nivel.

> Si se trata de una tabla de segundo nivel, el número de marco correspondiente. Para este caso, si la página correspondiente no se encuentra en memoria (bit de presencia en 0) se deberá cargar la misma en algún marco para poder finalmente responderle a la CPU. Téngase en cuenta que esto podría incluir reemplazos de páginas y escrituras en swap.
Aca tengo distintos caminos:

1.  La pagina esta Presente, nada que hacer.
2. La pagina no esta Presenta:
2a. Si le quedan marcos, lo pido y lo asigno.
2b. SI NO le quedan marcos, tengo que reemplzar uno. El problema que tengo aca es, en caso de tener que SWAPEAR la pagina necesitaria la direccion logica (AB) completa de la pagina para poder copiarla en el file de swap, para hacer algo asi `punteroInicioSwap + direccionLogica(AB) = marcoQueQuieroSwapear` entonces ahi **neceisto toda la direcicon logica para guardar el marco o la otra es copiar todas**. 

- ¿Tengo que tener alguna estrucutra adicional?
- ¿Cual es la forma recomendada para swapear algun marco?¿como mapear el swap con el proceso?

Como se ve en la imagen mi maepo Swap <--> Proceso, las direcciones estas uno a uno por asi decirlo, en verdad, el offset del Swap es la diureccionLogica.

![Diagrama en blanco](https://user-images.githubusercontent.com/2874428/173715475-31d2faf3-d662-49dc-a781-5b9db2e61b43.jpeg)

Muchas gracias!

**Comment by RaniAgus** [comment]
¡Buenas! 

> ¿Esto es asi? Porque como cada entrada de la tabla de 1er Nivel apunta al primer elmento de la tabla de segundo nivel. ¿Como retornas el indica si el indice de la tabla de 2do nivel lo determina el llamado posterior (el que detallo abajo).
A lo que voy es que deberia retornar la direccion de memoria del inicio de la pagina de 2do Nivel para esa entrada de 1er Nivel.

La tabla de páginas de 1er nivel solamente contiene el _index_ de la tabla de páginas de 2do nivel, no la posición en memoria del primer elemento. En #2596 pueden encontrar esta duda explicada más en detalle. 

> El problema que tengo aca es, en caso de tener que SWAPEAR la pagina necesitaria la direccion logica (AB) completa de la pagina para poder copiarla en el file de swap, para hacer algo asi punteroInicioSwap + direccionLogica(AB) = marcoQueQuieroSwapear entonces ahi neceisto toda la direcicon logica para guardar el marco o la otra es copiar todas.

Cuando envíen desde CPU el mensaje de "acceso a tabla de páginas de 2do nivel" pueden pasar el PID y/o el índice de la tabla de primer nivel para así acceder a todas las páginas presentes y elegir la que va a ser reemplazada según el algoritmo.

Sino, si ven que se les complica y necesitan alguna otra estructura para saber qué página mandar a swap, está bien si se arman alguna estructura auxiliar, no creo que les cambie las pruebas 👍🏻 

Saludos

**Comment by LeandroCarbajales** [comment]
Buenas!
Solamente para agregar algún tip:

> A lo que voy es que deberia retornar la direccion de memoria del inicio de la pagina de 2do Nivel para esa entrada de 1er Nivel.

Al devolver el índice de la tabla de 2do nivel, de alguna manera están representando la dirección de inicio de la misma en Memoria, dicho de otra manera, "dónde está" o "cuál es".

> ¿Tengo que tener alguna estrucutra adicional?

Como dijo Agus, pueden tener estructuras adicionales y/o enviarse desde CPU el PID y número de página para saber dónde escribir en SWAP si fuera necesario.

> ¿Cual es la forma recomendada para swapear algun marco?¿como mapear el swap con el proceso?
Como se ve en la imagen mi maepo Swap <--> Proceso, las direcciones estas uno a uno por asi decirlo, en verdad, el offset del Swap es la diureccionLogica.

Exactamente así :), SWAP lo pueden ver como una representación del espacio de direcciones del proceso.

Saludos!
       Lean

**Comment by matiastito** [comment]
Si, esta calro, entonces el 'error' de lo que pase es que cada entrada de la tabla de paginas de 1er nivel tiene su tabla de paginas de 2do nivel, encontes; solo tenemos 2 tablas y NO 'n' tablas de 2do nivel por CADA entrada de 1er nivel.

@LeandroCarbajales cuando decis:
> Como dijo Agus, pueden tener estructuras adicionales y/o enviarse desde CPU el PID y número de página para saber dónde escribir en SWAP si fuera necesario.

Seria pasarle en tanto el pid como la entrada de 1er Nivel y 2do Nivel para 'reconstruir' la direccion logica del lado de la memoria. Porque si solamente me pasan una de las dos entredas no tengo manera de reconstruirla completamente.

**Comment by LeandroCarbajales** [comment]
> Si, esta calro, entonces el 'error' de lo que pase es que cada entrada de la tabla de paginas de 1er nivel tiene su tabla de paginas de 2do nivel, encontes; solo tenemos 2 tablas y NO 'n' tablas de 2do nivel por CADA entrada de 1er nivel.

Entiendo que es un typo, pero por las dudas, sería una tabla de 2do nivel por cada entrada de la de 1er nivel.

> Seria pasarle en tanto el pid como la entrada de 1er Nivel y 2do Nivel para 'reconstruir' la direccion logica del lado de la memoria. Porque si solamente me pasan una de las dos entredas no tengo manera de reconstruirla completamente.

Para qué necesitarían "reconstruir" la dirección lógica en Memoria si ya la tienen en CPU? Con el número de página calculado en CPU ya sabrían dónde leer en SWAP, o por ejemplo podrían tener también alguna estructura "inversa" [marco, libre/ocupado, pid-página] si les facilita el algoritmo :)

**Comment by matiastito** [comment]
> Entiendo que es un typo, pero por las dudas, sería una tabla de 2do nivel por cada entrada de la de 1er nivel.

Si, gracias

> Para qué necesitarían "reconstruir" la dirección lógica en Memoria si ya la tienen en CPU? Con el número de página calculado en CPU ya sabrían dónde leer en SWAP, o por ejemplo podrían tener también alguna estructura "inversa" [marco, libre/ocupado, pid-página] si les facilita el algoritmo 

Ok entonces para el caso de:
`dameMarco(pid, entrada1erNivel, entrada2donivel) --> devuelve el marco y ademas adentro del metodo recosntruyo la direccion logica para poder luego swapear`
puedo hacer algo asi:
`dameMarco(pid, entrada1erNivel, entrada2donivel, direccionLogicaSinDesplazamiento) --> devuelve el marco y ademas adentro del metodo uso la direccionLogicaSinDesplazamiento para poder luego swapear`

En caunto a esto:

> [marco, libre/ocupado, pid-página] 

Seguiria teneindo el problema de no poder identificar la pagina en el swap.

Gracias

**Comment by matiastito** [comment]
@RaniAgus 

Gracias Agus, el tema es que segun ese issue:
> La tabla de páginas de 1er nivel solamente contiene el index de la tabla de páginas de 2do nivel, no la posición en memoria del primer elemento. En https://github.com/sisoputnfrba/foro/issues/2596 pueden encontrar esta duda explicada más en detalle.
Solo tenes 1 tabla de 2do Nivel, y entiendo que es es 1 Tabla de 2do nivel por cada entrada de la tabla de 1er nivel.

Gracias

**Comment by RaniAgus** [comment]
> En un caso tenes n+n y el otro n*n. ¿Qué esquema usamos?

Nono, las tablas de páginas de 1er y 2do nivel tienen N entradas, por lo que la cantidad de páginas direccionables es siempre N*N

A lo que se refiere el issue es que las tablas de 2do nivel no están agrupadas por proceso, sino que son globales a todo el sistema.

La entrada de tabla de página de 1er nivel debe contener el index (un `int`) en donde encontrar la tabla de 2do nivel dentro de esa lista global, en vez de tener directamente el puntero a la tabla (o sea, un `t_tabla*` o algo parecido).

> Ok entonces para el caso de:
dameMarco(pid, entrada1erNivel, entrada2donivel) --> devuelve el marco y ademas adentro del metodo recosntruyo la direccion logica para poder luego swapear
puedo hacer algo asi:
dameMarco(pid, entrada1erNivel, entrada2donivel, direccionLogicaSinDesplazamiento) --> devuelve el marco y ademas adentro del metodo uso la direccionLogicaSinDesplazamiento para poder luego swapear

Tengan en cuenta que cada mensaje es atómico, o sea, no hay un solo `dameMarco()` sino que la Memoria tiene varios:
- `dameNumeroTabla2doNivel(nroTabla, nroEntrada)`
- `dameNumeroMarco(nroTabla, nroEntrada)`
- `escribimeEn(direccionFisica, numero)`/`leemeDe(direccionFisica)`/`copiame(dirFisica1, dirFisica2)`
 
Y la CPU es la encargada de irlos llamando e ir reconstruyendo la dirección física en base a la lógica.

>  O sea, segun el enunciado lo unico que le llega a la memoria de la CPU en la secuencia de llamados son Entrada1erNivel, Entrada2doNivel y el Marco. 

Recuerden que `entrada1erNivel` y `entrada2doNivel` se obtienen a partir del número de página (más info en https://github.com/sisoputnfrba/foro/issues/2701#issuecomment-1154070004), por lo que podrían hacer la operación inversa para obtenerla

**Comment by matiastito** [comment]
Gracias @RaniAgus 

Cunado decis 

> operación inversa para obtenerla

El tema es tener una opraciones en la moemria tipo: `damePagina(marco) --> pagina` que hace el recorrido inverso, es decir, busca el marco en la tabla de 2do nivel, obtiene esa entrada y luego la busca en la tabla de 1er nivel, algo asi:

`
damePagina(marco) {
    entrada2doNivel = buscarEntrada2doNivel(marco)
    entrada1erNivel  = buscarEntrada1erNivel(entrada2doNivel)
    // el tema viene aca, como es el cualculo inverso
}
`

Ahi puse un comentario, dado un marco podemos hacer el lookup pero..... como hacemos el calculo para ovetener la direccion logica, se pone feo....


Gracias

**Comment by RaniAgus** [comment]
Por "operación inversa" me refería a que, si dado el `número_página` se puede calcular:

> entrada_tabla_1er_nivel = floor(número_página / cant_entradas_por_tabla)
> entrada_tabla_2do_nivel = número_página % cant_entradas_por_tabla

Entonces dados `entrada_tabla_1er_nivel` y `entrada_tabla_2do_nivel` pueden calcular `número_página` haciendo la operación inversa a la división con resto 😄 

Saludos

**Comment by RaniAgus** [comment]
> Con respesto a las tablas, aca Lean me dice otra cosa: https://github.com/sisoputnfrba/foro/issues/2707#issuecomment-1156699769

No entendí, ¿a qué te referís exactamente con "me dice otra cosa"? ¿En qué parte?

**Comment by matiastito** [comment]
Acá:

> sería una tabla de 2do nivel por cada entrada de la de 1er nivel

**Comment by RaniAgus** [comment]
Perdón, me refería a que las tablas de 2do nivel no están agrupadas por tabla de páginas de 1er nivel:

![image](https://user-images.githubusercontent.com/39303639/173911687-3a80dcb2-0129-4372-8f62-07d1012f9714.png)

Sino que están todas juntas, en una estructura global, al igual que las de 1er nivel:

![image](https://user-images.githubusercontent.com/39303639/173911212-5cd315b8-e224-43d7-83b9-8f17cfd09c7d.png)

Pero la relación en cuanto a cantidad sigue siendo una tabla de 2do nivel por cada entrada de la de 1er nivel

**Comment by matiastito** [comment]
Gracias Agus, el tema es que está raro porque si decís que son globales dos procesos que accedan a las dirección lógica 100, por ejemplo, mapearian con el mismo marco.
Entiendo que por cada tabla de 1er nivel tenés ese array de tablas de 2do nivel por cada uno.
La única diferencia que veo entre los dos gráficos es que en uno tenés un puntero y en otro un índice

Muchas gracias

**Comment by LeandroCarbajales** [comment]
Buenas!
A efectos del TP es casi lo mismo, aunque hacerlas globales entiendo que les ahorraría algo de lógica en la Memoria, por ejemplo no tener que pasarse nuevamente la entrada de 1er nivel.
En definitiva, conceptualmente las tablas están todas "en la Memoria", no hay razón para no poder acceder a las de 2do nivel directamente (de hecho podrían tener una sola lista de "tablas" y funcionaría igual) y justamente las tablas de 1er nivel te dicen cuáles son las de 2do nivel de tu proceso por lo que no ocurriría que se pisen. Por otro lado, si lo piensan del lado de querer compartir memoria entre procesos, podríamos asignarles la misma (o mismas) tabla de 2do nivel a algunas entradas de la de 1er nivel de cada proceso y ya estarían compartiendo todo ese direccionamiento.
Por eso recomendamos esa implementación más allá de que lo puedan indexar por proceso, si ya lo tienen implementado así igual está bien.

Más allá de eso, pudieron resolver cómo manejar el SWAP? Entiendo que lo último fue:

> En caunto a esto:
    [marco, libre/ocupado, pid-página]
Seguiría teniendo el problema de no poder identificar la pagina en el swap dado que la posicion del marco no es la misma que tendrá en la Swap. Entonces, si en la memoria no tenes la pagina (el desplazamiento no importa) y aca dogo que no la tenes porque cuando hablas con la memoria solo le pasas indices de entrada y un marco, entocnes como haces para identificar qué página swapear. O sea, segun el enunciado lo unico que le llega a la memoria de la CPU en la secuencia de llamados son Entrada1erNivel, Entrada2doNivel y el Marco. Con esos datos desde la memoria no podes swapear digamos.

A lo que mi respuesta es la misma, se pueden pasar el número de página y el PID desde la CPU a la Memoria para saber de dónde leer en SWAP la página nueva y también tener esa estructura para saber dónde escribir en SWAP si la página a reemplazar estuviera modificada. Lo podrían hacer sin eso? Si, como dijo Agus con las entradas de tabla pueden calcular nuevamente el número de página, pero así no repiten esos cálculos y queda más simple el código :)

**Comment by matiastito** [comment]
Si, gracias @LeandroCarbajales  y @RaniAgus 

Para finalizar, yo creo que confundo un poco el tema de llamar a la tabla de 2do nivel como globales, pero, creo que basicamnte seria asi:

![Diagrama en blanco (1)](https://user-images.githubusercontent.com/2874428/173942827-5da86455-fd79-4dfc-87e3-c4945329f4d6.jpeg)

Tendriamos una estrucutra: 

`t_mem_proceoso` que contiene:
- una tabla de 1er nivel y
- un arreglo de tablas de 2do nivel.

Esta `t_mem_proceoso` es una por proceso, todas en una lista (en la imagen hay dos) y la PCB tiene el indice a esta lista de  `t_mem_proceoso`.

**Comment by LeandroCarbajales** [comment]
> Es bastante diferente a como lo plantea Agus acá https://github.com/sisoputnfrba/foro/issues/2707#issuecomment-1156855575 donde las tables de 1er nivel son globales con lo cual, no tenes referencia que tabla de 1er Nivel va con que tabla de 2do Nivel.

Si se tendría referencia de qué tabla de 1er nivel va con cuál de 2do nivel justamente porque las de 1er nivel tienen el índice de su correspondiente tabla de 2do nivel para cada entrada, de nuevo, si como lo tienen implementado funciona, no tienen por qué cambiarlo.

> Hay algun criterio para hacer la asginacion?

No, por lo que pueden simplemente asignar el primero que tengan libre.

> Puede pasar que la cuenta CantidadDeProcesos * CantidadDeMarcos > RAM cumpla con eso en algunos de los casos de prueba
Tenemos que controlar que la cantidad de marcos por proceso no sobrepase el tamaña total de la RAM?

No, grado_de_multiprogramación y la configuración de Memoria van a ser consistentes.

Saludos!
       Lean

**Comment by matiastito** [comment]
Gracias por todo Lean, cierro el issue.
