### ISSUE TITLE
Duda con uso de TLB y mantener actualizados los accesos a páginas.

### ISSUE THREAD

**Issue by muratoredante** [sisoputnfrba/foro#2708]
Buenas, teníamos una duda relacionada con la TLB.

Entiendo que la TLB se utiliza para que cuando CPU tenga que acceder a una página que ya tiene cacheado su respectivo número de frame en TLB, le envíe directamente la dirección física a memoria y se eviten los 3 accesos de traducción.

Considerando que memoria tiene una lista de páginas y cada una de ellas tienen que mantener actualizados el bit de modificado y el bit de uso ante cada acceso. Entonces cuando se acceda a una página cacheada en TLB y memoria reciba la dirección física, no sería obvio para memoria saber a que pagina corresponde el frame para actualizar esos bits.

Se me ocurren varias formas de resolverlo como por ejemplo enviar desde CPU la información necesaria para saber que pagina es o que memoria tenga alguna referencia a la página en cada frame. Pero la situación se me hace medio rara respecto al a teoria asi que queria asegurarme que no estoy malinterpretando o ignorando algo.

Gracias

**Comment by LeandroCarbajales** [comment]
Buenas! Muy buena pregunta!
En la vida real: depende del CPU/arquitectura, la TLB puede tener cacheada la entrada entera de la tabla (incluidos los bits y otros datos de la misma) y/o tener un puntero a tabla según qué tabla esté cacheando.
En el TP: pueden enviarse desde CPU todo lo que consideren necesario para hacer las tareas de Memoria, sin embargo, en los ejercicios que vemos en clase no es algo que veamos en detalle por lo que es un caso que vamos a evitar en las pruebas.

Saludos!
      Lean

**Comment by muratoredante** [comment]
Perfecto, gracias!
