### ISSUE TITLE
[Memoria/TLB] Duda sobre la actualización de la TLB 

### ISSUE THREAD

**Issue by fcafici** [sisoputnfrba/foro#2709]
Buenos días, estábamos pensando en cómo armar el tema del reemplazo de páginas en la TLB y nos surgió la siguiente duda. Cuando saco una pagina de mi memoria y la llevo al swap, yo debería sacarla también de la TLB no? Por que sino la próxima vez que la saque de swap y la vuelva a meter memoria podría tener otra dirección física, y la dirección vieja de la TLB no va a ser la correcta. 
Es correcto que lo manejemos con mensajes entre memoria y cpu? Saludos

**Comment by fcafici** [comment]
Perfecto, gracias!

**Comment by LeandroLienard** [comment]
Hola, como va? me surgió una duda al respecto 

> Cuando lleven una página a swap (ej: página 2, marco 5) va a ser porque se va a cargar otra página sobre ella (ej: página 4, marco 5).
A nivel memoria, vamos a tener un proceso que tenga su propia tabla de páginas nivel 2 y (suponiendo entradas_por_tabla = 4), esta tabla va a **tener** siempre los mismos 4 frames asignados fijos?
Llevandolo a un ejemplo si tenemos cargados los 4 marcos:
![ejemplo_memoria_reemplazo](https://user-images.githubusercontent.com/81934049/174231345-efa243a1-f076-468d-84c2-15b407502ddb.png)

Suponienod tamb que los nros_pag son:
<html>
<body>
<google-sheets-html-origin>

Nros_pags | Nros_marcos
-- | --
0 | 0
1 | 1
2 | 2
3 | 3


</body>
</html>

Si quisieramos agregar otro nro_pag, por ejempo "página 5", habría que asignarle y sobreescribir alguno de los marcos asociados al proceso ? es decir[0,1,2,3]
O se debería asignar un nuevo marco "5" y reemplazarlo por alguno de los marcos existentes.

**Comment by LeandroCarbajales** [comment]
Buenas!
Como se ve en los ejercicios con asignación fija, suelen usarse siempre los mismos marcos una vez asignados a un proceso y se van reemplazando las páginas entre los mismos, aunque no tiene necesariamente por qué ser así, pero considero que es lo más simple de implementar y de probar :)

> O se debería asignar un nuevo marco "5" y reemplazarlo por alguno de los marcos existentes.

Hacer eso quedaría algo parecido a page buffering, pero no encaja con el esquema del TP ya que estarían suponiendo que siempre hay frames libres para asignar.

Saludos!
        Lean

**Comment by RaniAgus** [comment]
¡Buenas! Me sumo solo para aclarar que cuando me refería a "se va a cargar otra página sobre ella" quise decir "sobre **ese marco**", ahí edité el comment por si alguien más lo llega a ver :)

**Comment by LeandroLienard** [comment]
Genial, gracias a los dos, clarisimo esto, me quedaron algunas consultas peor las hago mañana por discord!
Saludos! 
Lean
