### ISSUE TITLE
Obtener pagina en Memoria

### ISSUE THREAD

**Issue by matiastito** [sisoputnfrba/foro#2710]
Hola chicos, creo un issue para ver si me pueden ayudar con el siguietne calculo:

En la MMU tenemos el siguiente calculo:
```
[entrada_tabla_1er_nivel | entrada_tabla_2do_nivel | desplazamiento]

número_página = floor(dirección_lógica / tamaño_página)
entrada_tabla_1er_nivel = floor(número_página / cant_entradas_por_tabla)
entrada_tabla_2do_nivel = número_página mod (cant_entradas_por_tabla)
desplazamiento = dirección_lógica - número_página * tamaño_página
```

Ahora bien en la memoria yo tengo:
```
entrada_tabla_1er_nivel
entrada_tabla_2do_nivel
```

se me esta complicando saber el nro de pagina a partir de esos datos.

Gracias

**Comment by LeandroCarbajales** [comment]
Buenas!
Más allá de que se la pueden enviar desde CPU para no repetir el cálculo.
Conceptualmente:
 `número_página = entrada_1er_nivel * cant_entradas_por_tabla + entrada_2do_nivel`

Saludos!
      Lean
