### ISSUE TITLE
Dudas modulo memoria

### ISSUE THREAD

**Issue by cjgonzalo** [sisoputnfrba/foro#2711]
Buenas noches, tengo algunas dudas sobre el modulo de memoria

1. La cantidad de entradas por tabla que viene en el config sería para la tabla de primer nivel cuantas tablas de segundo nivel puede referenciar, y para las tablas de segundo nivel cuantas paginas puede tener cada una como máximo no? Suponiendo esto paso a la pregunta 2

2. Cuando el kernel solicita que se creen las tablas de páginas de un proceso, que se hace si se pasa el máximo de entradas en la tabla de primer nivel? Se envía un error al kernel? Se espera a que se desocupe una entrada para meter la tabla nueva? O no se tiene en cuenta el caso que se supere el máximo?

3. El kernel debe enviar el tamaño del proceso cuando solicita la creación de tablas? Si es así y el tamaño del proceso es mayor al tamaño máximo de una tabla de paginas de segundo nivel (que supongo es entradas_por_tabla * tam_pagina) se debe crear mas de una tabla de segundo nivel para ese proceso? Si es así y cada tabla de segundo nivel tiene asignado un numero de tabla de primer nivel, que numero se debería responder al kernel? O puede ser que las tablas de segundo nivel compartan un mismo numero de tabla de primer nivel?

**Comment by LeandroCarbajales** [comment]
Buenas!

> La cantidad de entradas por tabla que viene en el config sería para la tabla de primer nivel cuantas tablas de segundo nivel puede referenciar, y para las tablas de segundo nivel cuantas paginas puede tener cada una como máximo no? Suponiendo esto paso a la pregunta 2

Así es, como aclara el enunciado, ambos niveles tienen la misma cantidad de entradas :)

> Cuando el kernel solicita que se creen las tablas de páginas de un proceso, que se hace si se pasa el máximo de entradas en la tabla de primer nivel? Se envía un error al kernel? Se espera a que se desocupe una entrada para meter la tabla nueva? O no se tiene en cuenta el caso que se supere el máximo?

No, los procesos no pueden ser más grandes que lo que pueden direccionar las tablas, ya que sería equivalente a que sean más grandes que el direccionamiento lógico del sistema. Por ejemplo, si tuvieras 4 entradas_por_tabla (16 páginas máximo) y tamaño_pagina 1024, lo podés ver como que tu direccionamiento lógico es de 14 bits (4 para número de página y 10 para offset), por lo que los procesos nunca podrían ser más grandes que 2^14 bytes.

> El kernel debe enviar el tamaño del proceso cuando solicita la creación de tablas? Si es así y el tamaño del proceso es mayor al tamaño máximo de una tabla de paginas de segundo nivel (que supongo es entradas_por_tabla * tam_pagina) se debe crear mas de una tabla de segundo nivel para ese proceso? Si es así y cada tabla de segundo nivel tiene asignado un numero de tabla de primer nivel, que numero se debería responder al kernel? O puede ser que las tablas de segundo nivel compartan un mismo numero de tabla de primer nivel?

Claro! Justamente cada entrada de la tabla de 1er nivel nos "apunta" a una tabla de 2do nivel diferente del proceso, por lo que como máximo, tomando el ejemplo anterior, tendrías 1 tabla de 1er nivel y 4 tablas de 2do nivel para el proceso. Si el proceso fuera más chico (requiriera direccionar menos páginas), podrían considerar solamente crear la cantidad de tablas de 2do nivel necesarias, que es una de las ventajas de paginación en 2 niveles con respecto a paginación "simple".

Saludos!
        Lean

**Comment by cjgonzalo** [comment]
Perfecto todo claro, muchas gracias!
Saludos!
