### ISSUE TITLE
Limpiar TLB

### ISSUE THREAD

**Issue by gastonpaz** [sisoputnfrba/foro#2712]
El enunciado dice `Esta caché deberá ser limpiada cada vez que ocurra un cambio de proceso.`. Nosotros actualmente al inicio de cada ciclo de instrucción limpiamos la TLB y queríamos saber si con el siguiente escenario es necesario hacerlo o modificar lo que hicimos.

Escenario:
1- Kernel lanza una interrupción
2- CPU desaloja el proceso
3- El algoritmo del PCP (SRT seguramente) elige al mismo proceso
4- Se limpió de la TLB las entradas y no hubo un cambio de proceso.

Ante este escenario cuando ingrese la nueva instrucción después atender la interrupción el proceso será el mismo, en este caso es necesario limpiar la TLB? 
Gracias!

**Comment by RaniAgus** [comment]
¡Buenas! En ese escenario la TLB no debería ser limpiada ya que no hubo un cambio de proceso. Saludos

**Comment by LeandroCarbajales** [comment]
Buenas @gastonpaz !
Quedó resuelta la duda? Se puede cerrar el issue?

**Comment by gastonpaz** [comment]
Sisi, gracias! cierro.
