### ISSUE TITLE
Limpieza de TLB

### ISSUE THREAD

**Issue by DamianArielLerner** [sisoputnfrba/foro#2713]
Buenas, una pregunta, tendría que limpiar la TLB siempre que un proceso nuevo entre a EXEC? O se tiene que limpiar cuando ese proceso nuevo necesita comunicarse con el modulo de Memoria?
Es decir, si el proceso 0 llenó la TLB y se bloquea, para que posteriormente entre el proceso 1, y este ultimo solo necesite ejecutar instrucciones de NO_OP, es necesario vaciar la TLB que contiene los números de pagina del proceso 0?
Desde ya, muchas gracias!

**Comment by LeandroCarbajales** [comment]
Buenas!
Sí, la idea es limpiarla siempre que haya cambio de proceso para que no quede inconsistente, conceptualmente no se sabe qué va a ejecutar el proceso hasta que ejecuta por lo que no tendría sentido hacer ese chequeo (y de paso es más simple la implementación 😉) , por otro lado, en la realidad no existe (o sería un caso extremadamente borde) que un proceso no acceda a Memoria.

Saludos!
         Lean
