### ISSUE TITLE
Reemplazo de páginas

### ISSUE THREAD

**Issue by matiastito** [sisoputnfrba/foro#2714]
Hola chicos, de nuevo moletando.

Estoy en el caso en el cual ya asignamos todos los marcos ye tenemos que elegir qué pagina eliminar ahora, la pregunta es:

Una vez que detectamos qué pagina vamos eliminar, primero la swapeamos, y luego, al momento de traer ésa página a un nuevo frame:

1- ¿Podemos reusar el mismo marco, es decir, el que acabo de swapear para poner la nueva página?
2- Ésa nueva página, ¿la traemos del Swap? Porque si el Swap lo incializamos todo en cero no nos preocupamos si se swapeó o no antes.

Gracias

**Comment by LeandroCarbajales** [comment]
Buenas!
Es igual que en los ejercicios de clase, al seleccionar una página a reemplazar, la página nueva va a ese mismo marco ya que es el que estaríamos liberando.
No se si estoy entendiendo bien la última pregunta, pero las páginas las traes de SWAP ya que es donde está el contenido del proceso, aunque se haya inicializado en cero, su contenido irá variando a medida que se escriban valores.

Saludos!
       Lean

**Comment by matiastito** [comment]
Gracias Lean!
