### ISSUE TITLE
Limpiar memoria proceso

### ISSUE THREAD

**Issue by matiastito** [sisoputnfrba/foro#2715]
Buenas a todos, el motivo por el cual les consulto tiene que ver con la finalización de un proceso y es estado en el que queda la memoria.

En mi caso, implementé tanto las tablas de pagina de 1er nivel como las de 2do nivel como listas globales.
Esto está bien, el asunto es que como las entradas de las paǵinas de 1er nivel tiene el índice de la tablas de 2do nivel, va a pasar el caso de que cuando un proceso termine NO podamos sacarlo de la lista porque vamos a romper todos los índices. Con lo cual podemos hacer dos cosas:

- Cuando un proceso termina, y si queremos eliminar todas sus tablas, hay que reodenar todos los índicaes lo cual me parece muy trabajoso.
- La otra es poner NULL en dónde estaban esas tablas y listo (haciendo todos los frree's correspondientes). El tema es que van a quedar 'huecos' en las listas de las dos tablas globales, pero bueh.

Seguramente haya mas alternativas.

Gracias!

**Comment by LeandroCarbajales** [comment]
Buenas!
Cito al enunciado:

> Finalización de proceso
Al ser finalizado un proceso, se debe liberar su espacio de memoria y eliminar su archivo de SWAP correspondiente. **Se debe tener en cuenta que, para la realización de este trabajo, no es requerido eliminar las tablas de páginas del proceso**.

Y los invito también a leer la nota al pie sobre lo mismo :)

Saludos!
        Lean

**Comment by matiastito** [comment]
Graccias Lean!
