### ISSUE TITLE
Problema con la TLB de un proceso suspendido

### ISSUE THREAD

**Issue by FacuBazzi** [sisoputnfrba/foro#2716]
Hola, quería consultar cómo deberíamos manejar la siguiente situación:

Tengo un único proceso, y está ejecutando sus instrucciones en el CPU guardando sus páginas en la TLB.
En determinado momento, el proceso se suspende, por lo que memoria guarda sus páginas en el swap y deja de considerar como propios a los frames que tenía ocupados.
El proceso se desbloquea y vuelve a ejecutarse, por lo que CPU no limpia la TLB al tratarse del mismo proceso.
Las instrucciones implican lecturas/escrituras sobre páginas que existen en la TLB, por lo que no le pide nada memoria y solicita lecturas/escrituras directamente sobre direcciones físicas, pero esas direcciones físicas ya no son del proceso en cuestión.

Dado que la asignación de frames en memoria se da cuando me solicitan el numero de frame de una página que no tengo cargada, para memoria en ese último momento, esa dirección física no es de nadie y posiblemente lo sobreescriba tarde o temprano.

Quería saber como podemos manejar esta posible situación, gracias!

**Comment by LeandroCarbajales** [comment]
Buenas!
Si hacen IO o EXIT pueden suponer que la TLB se limpia ya que el proceso está dejando la CPU voluntariamente :)

Saludos!
        Lean

**Comment by FacuBazzi** [comment]
Ah buenísimo, teníamos entendido que si luego de una IO se sigue ejecutando el mismo proceso, no había que limpiar la TLB.
Gracias por responder tan rápido, cierro el issue :)
