### ISSUE TITLE
Finalización de un proceso

### ISSUE THREAD

**Issue by matiastito** [sisoputnfrba/foro#2718]
Buen día chicos, espero se encuntren bien, les escribo porque en el enunciado hace referencia a la finalización de un proceso del siguietne modo:

![image](https://user-images.githubusercontent.com/2874428/174485924-f3a680ed-9758-4ded-a8db-480d9cf24340.png)

La pregunta es: ¿tenemos que _esperar_ la confirmación de la memoria?; me hago esa pregunta porque en el caso de la suspención de un proceso sí dice que debemos esperar el mensaje de la memoria.

Muchas gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Si el enunciado no dice que tienen que esperar, pueden darse el lujo de "no esperar", ahora, cuanto puede demorarles la memoria en contestarles el mensaje de "Finaliza X Proceso"? 

Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas!
Dicho sea de paso, el enunciado sí aclara de esperar la confirmación de Memoria :)

> Cuando se reciba un PCB con motivo de finalizar el mismo, se deberá pasar al proceso al estado EXIT y dar aviso al módulo Memoria para que éste libere sus estructuras. **Una vez liberadas**, se dará aviso a la Consola de la finalización del proceso.

Saludos!
        Lean

**Comment by matiastito** [comment]
Gracias a los dos, evidentemente se me escapó esa parte, gracias y perdon
