### ISSUE TITLE
Duda swap y suspensión

### ISSUE THREAD

**Issue by lucas-marmo** [sisoputnfrba/foro#2719]
Buenas! Estoy con unas dudas con respecto al funcionamiento del Swap y no encuentro respuesta en otros issues.

Entiendo por las clases teóricas y por el enunciado, que el archivo de swap de cada proceso va a representar a la memoria virtual, entonces el archivo al ser creado va a tener un espacio destinado a cada marco, una posición inmutable. Esa posición va a ser la que sea referenciada en tabla de páginas cuando el bit de presencia es 0. Si es 1, me da el número de marco de memoria real.

Me surge la duda, al momento de suspender un proceso, lo que estaría haciendo es simplemente indicar que la posición que ubicaban sus marcos en memoria real está disponible para otros procesos. El archivo de swap no es modificado, ya que de por sí tiene a todos los marcos cargados en sus posiciones fijas desde un principio.
Mi pregunta es: cómo puedo saber qué marcos son los que tengo que volver a poner en memoria al finalizar la suspensión? Entiendo que son los mismos que saqué de memoria al suspender, debería entonces en algún lado guardarme la referencia a esos marcos que saqué para después volverlos a poner en memoria?

También me surge la duda de cuándo actualizar en el swap la información que le fue llegando a un marco que está en memoria real. La actualizaría cuando un marco sale de memoria y queda solamente en swap, no?

Muchas gracias, espero que se haya entendido.

**Comment by RaniAgus** [comment]
¡Buenas!
> Mi pregunta es: cómo puedo saber qué marcos son los que tengo que volver a poner en memoria al finalizar la suspensión? Entiendo que son los mismos que saqué de memoria al suspender, debería entonces en algún lado guardarme la referencia a esos marcos que saqué para después volverlos a poner en memoria?

Como comentaba en #2666, al finalizar la suspensión no hay que volver a cargar las páginas que estaban en memoria al momento de suspender, sino que se siguen cargando a demanda.

> También me surge la duda de cuándo actualizar en el swap la información que le fue llegando a un marco que está en memoria real. La actualizaría cuando un marco sale de memoria y queda solamente en swap, no?

¡Exacto! Idealmente solo se actualiza la página si bit de modificado es 1, lo cual me da pie a la anterior duda:

> Me surge la duda, al momento de suspender un proceso, lo que estaría haciendo es simplemente indicar que la posición que ubicaban sus marcos en memoria real está disponible para otros procesos. El archivo de swap no es modificado, ya que de por sí tiene a todos los marcos cargados en sus posiciones fijas desde un principio.

Al suspender el proceso, en caso de que alguna de las páginas presente tenga el bit de modificado en 1 el archivo de swap **sí** es modificado, ya que hay que actualizar el contenido de esas páginas antes de liberar los marcos correspondientes.

Saludos

**Comment by RaniAgus** [comment]
No hace falta chequearlo, pueden asumir que en Kernel el `grado_multiprogramacion` va a ser consistente con la configuración de Memoria para evitar quedarse sin espacio 😄

**Comment by lucas-marmo** [comment]
Perfecto, cierro el issue.
