### ISSUE TITLE
Duda sobre limite de marcos x proceso y SWAP

### ISSUE THREAD

**Issue by LeandroLienard** [sisoputnfrba/foro#2720]
Buenas, hace unos días había hecho unas consultas acerca de los marcos de un proceos pero todavía no me queda 100% claro cómo se produce el reemplazo.
Pongo un poco de contexto:

> `si según config tengo marcos x proceso  = 4 y entradas x tabla = 4 `

=>puedo direccionar hasta 16 posiciones (4 entradas x tabla nivel 1 y 4 entradas x tabla nivel 2)

Pero solamente voy a tener cargadas a la vez en memoria principal 4 frames a la vez 
=> esto me limitaria a tener solamente 4 frames de los 16 posibles con bit Presencia= 1

- DUDA 1 : puede ser que otra pagina, además de la activa, me quede con el mismo **nro_frame** asignado, pero con bit presencia = 0, 
osea tendría: 
- - pág 0 con nro_frame = 'n' y P = 0 
- - pág 4 con nro_frame = 'n' y P = 1

Su caso sería el que a la página 0 se le **había asignado el marco** y fue victima del algoritmo de reemplazo. Esto sería correcto?

Otro contexto del cual tengo duda: 
El caso en el que yo quiero acceder a un nro_pag que no esta en mem_principal
- DUDA 2: cuando es el caso en el que tengo que ir a buscarlo a SWAP? es decir, tengo que ir a **leer** lo que está en swap para hacer alguna operación, conozco el caso de escritura que es cuando tiene el bit M=1, pero en algún momento voy a tener que ir a buscar ese dato al archivo ?
- DUDA 3: suponiendo bit_array uso_x_proceso = {1111}; // es decir tengo el maximo de marcos x proceso
=>alg de reemplazo, 
                      

```
si M=0 => sobreescribo
M=1 => llevo valor a SWAP, y después sobreescribo
al sobreescribir los valores se actualizan a(P=1, U=0 ,M=0)
```
Al sobreescribir tengo que **actualizar** U o M ?

Duda 4:

> Acceso a espacio de usuario
> El módulo deberá realizar lo siguiente:
> Ante un pedido de lectura, devolver el valor que se encuentra en la posición pedida
> Ante un pedido de escritura, escribir lo indicado en la posición pedida. En caso satisfactorio se responderá un mensaje de ‘OK’ o, de lo contrario, un mensaje de error.
> 

Cuales son los casos en los que se produzca un **error de escritura**, o sea, hay algún caso de uso en el que haciendo las cosas bien, lleguemos a eso? o sucedería ante un error de cálculo de la direc_física o errores de implementación similares

**Comment by LeandroCarbajales** [comment]
Buenas!

> DUDA 1 : puede ser que otra pagina, además de la activa, me quede con el mismo nro_frame asignado, pero con bit presencia = 0,
Su caso sería el que a la página 0 se le había asignado el marco y fue victima del algoritmo de reemplazo. Esto sería correcto?

Exacto! Es algo muy normal en un sistema con memoria virtual.

> DUDA 2: cuando es el caso en el que tengo que ir a buscarlo a SWAP? es decir, tengo que ir a leer lo que está en swap para hacer alguna operación, conozco el caso de escritura que es cuando tiene el bit M=1, pero en algún momento voy a tener que ir a buscar ese dato al archivo ?
    DUDA 3: suponiendo bit_array uso_x_proceso = {1111}; // es decir tengo el maximo de marcos x proceso
    =>alg de reemplazo,
si M=0 => sobreescribo
M=1 => llevo valor a SWAP, y después sobreescribo
al sobreescribir los valores se actualizan a(P=1, U=0 ,M=0)
Al sobreescribir tengo que actualizar U o M ?

La lógica de reemplazo es la misma que en los ejercicios que vemos en clases:

- Si se intenta acceder a una página que tiene el bit de presencia en 0, esa página tendrá que ser cargada a un marco (leída de SWAP), además si la operación es por escritura se deberá marcar el bit de modificado en 1.
- Por lógica del algoritmo de clock y clock-modificado, el bit de uso se setea en 1 cada vez que se referencia esa página.

> Cuales son los casos en los que se produzca un error de escritura, o sea, hay algún caso de uso en el que haciendo las cosas bien, lleguemos a eso? o sucedería ante un error de cálculo de la direc_física o errores de implementación similares

Dado que no hay ningún error tipificado para este TP, pueden ignorar lo del mensaje de error (de hecho ya no está en el enunciado)

Saludos!
       Lean

**Comment by LeandroLienard** [comment]
Buenisimo lean, me quedo todo clarisimo, muchas gracias.
Saludos!
