### ISSUE TITLE
Duda sobre PF

### ISSUE THREAD

**Issue by akalinin11** [sisoputnfrba/foro#2721]
Buenas tardes, con nuestro grupo teníamos la duda de como hacer el desarrollo del codigo cuando haya page fault. No sabemos si en caso de que pase, tenemos que reiniciar la instrucción, dejando el pcb en bloqueado para que pueda cargarse el frame en las estructuras necesarias

Lo planteado por nosotros fue algo relacionado directamente con la teoría, pero queríamos asegurarnos si esto es así o en el trabajo practico a modo de simplificación la memoria se encarga de hacer el retardo por acceso a disco sin tener que bloquear el pcb.

**Comment by LeandroCarbajales** [comment]
Buenas!
Citando el enunciado:

> Acceso a tabla de páginas
El módulo deberá responder lo siguiente:
...
Si se trata de una tabla de segundo nivel, el número de marco correspondiente. Para este caso, si la página correspondiente no se encuentra en memoria (bit de presencia en 0) se deberá cargar la misma en algún marco para poder finalmente responderle a la CPU. Téngase en cuenta que esto podría incluir reemplazos de páginas y escrituras en swap.

Para enfocar el trabajo en la parte estructural de memoria virtual y que de alguna manera quede más parecido a un ejercicio de la guía, la lógica del page fault (traer la página + el posible reemplazo) se hace "sincrónica y no bloqueante", es decir, se hace en el momento para poder obtener el número de marco y que la CPU finalmente pueda acceder a la dirección física sin tener que bloquear al proceso y luego reiniciar la instrucción.

Saludos!
        Lean

**Comment by akalinin11** [comment]
Excelente, quedo mas que claro.
Muchas gracias!!!
