### ISSUE TITLE
Dudas sobre tamanio_pagina

### ISSUE THREAD

**Issue by FernandoHerbas** [sisoputnfrba/foro#2722]
Buenas, que tal? Tengo dudas sobre el tamanio de paginas que nos pueden mandar para las pruebas: 
1- Este valor puede ser menor a un entero de 4 bytes? Por ejemplo, puede haber paginas de 1 byte? Donde un entero (que seria nuestra info a leer/escribir) estaria en 4 paginas.
2- En caso que no pueda ser menor, siempre va a ser multiplo de 4?

**Comment by LeandroCarbajales** [comment]
Buenas!
1- No, al igual que con las pruebas del Kernel, la idea es probar la funcionalidad con una configuración coherente y consistente.
2- Sí, será siempre potencia de 2 :)

Saludos!
        Lean

**Comment by FernandoHerbas** [comment]
Genial Leandro, muchas gracias!
