### ISSUE TITLE
Dudas sobre swap y suspension

### ISSUE THREAD

**Issue by Agusevans** [sisoputnfrba/foro#2723]
Buenas! Nos surgieron las siguientes dudas:

1- Cuando kernel avisa a memoria que se suspendió un proceso, memoria tiene que desasignar las paginas de dicho proceso en los marcos en los que están asignadas y escribir en swap si el bit de modificado es 1.  Esto debe hacerse en ese momento? o habría que poner por ejemplo un flag a los proceso que diga si esta suspendido o no y luego si llega otro proceso que necesite ese marco recién ahí swapearlo?

2- Al momento de traer de vuelta una pagina del swap, debe colocarse en el mismo marco al que estaba asignada originalmente? o puede ser a cualquier otro marco?

3- Solo para confirmar, la escritura en swap de una pagina se realiza siguiendo la lógica de: Numero de pagina * Tamaño de pagina? De esta forma las tengo ordenadas en el swap y puedo acceder al espacio de cada una haciendo esta cuenta?

**Comment by RaniAgus** [comment]
¡Buenas!

1- 
> memoria tiene que desasignar las paginas de dicho proceso en los marcos en los que están asignadas y escribir en swap si el bit de modificado es 1. Esto debe hacerse en ese momento?

Sí, debe hacerse en ese momento.

> o habría que poner por ejemplo un flag a los proceso que diga si esta suspendido o no y luego si llega otro proceso que necesite ese marco recién ahí swapearlo?

Lo más parecido a eso sería un esquema de page buffering, en donde se marca un frame "de reserva" como libre mientras al que hay que liberar se lo bloquea mientras se escribe en swap, pero **no** es el esquema a implementar en este TP.

2- En general, como habrán visto en la teoría, cualquier página puede ser colocada en cualquier marco :)

Si te referís al caso particular de un proceso volviendo de suspensión, como mencioné en #2666 y #2719 no hay que volver a cargar las páginas que estaban cargadas antes de suspender.

3- ¡Exacto!

Saludos

**Comment by Agusevans** [comment]
Genial, gracias!!
