### ISSUE TITLE
Sobre el submodulo SWAP

### ISSUE THREAD

**Issue by facuxfdz** [sisoputnfrba/foro#2725]
Buenas! Estuvimos leyendo los issues con mi grupo y repasando la teoria pero no nos termina de quedar claro el tema de la SWAP

1. Entendemos que si llega un proceso de 320 bytes, este necesitaria 5 paginas para ser administrado. Esto quiere decir que tengo que escribir en swap al estilo de un memcpy() 320 bytes que representen el direccionamiento de mi proceso?

2. Ligado a lo anterior, al inicializarse un proceso nosotros creamos una tabla de paginas de primer nivel y, siguiendo con el ejemplo anterior, 2 paginas de segundo nivel. Estas estructuras nosotros las creamos como variables en el programa pero no persistimos nada en ningun archivo. La idea es que en ese momento se genere el archivo .swap con la logica que comentaba en el punto anterior?

3. Cuando tenga que actualizarse la SWAP por cualquier motivo, necesitariamos agarrar la info que tengamos guardada en el void* que representa espacio de usuario (porque por ejemplo se leyo una instruccion de WRITE) y escribirla tal cual en el swap? Porque nos confunde un poco la idea de que una pagina no tiene informacion en si sino la referencia a un marco en donde realmente esta la informacion

4. Cuando tengamos que swappear alguna pagina (o la data que contiene el marco al cual referencia) como hacemos para saber que numero de pagina es? Porque me imagino que solamente vamos a tener el numero de frame pero teniendo eso como hariamos para saber a que pagina del proceso corresponde?

Creo que muchas de estas dudas son mas conceptuales pero estuve revisando las clases y no las termine de cerrar bien y como no curso hasta el sabado aprovecho el espacio de consultas

Muchas gracias!

**Comment by LeandroCarbajales** [comment]
1- Si quisieran indexar alguna estructura por pid lo podrían hacer ya que el dato lo tienen.
2- No es necesario ya que todo es calculable, pero creo que lo más sencillo es pasarse ese dato para no repetir lógica.
3- número_página se calcula como dice el enunciado y es siempre igual, vendría a ser sin la división de niveles de tablas, dicho de otra forma, quedaría como si hubiera un solo nivel de paginación, por eso luego se calcula por separado las entradas de distintos niveles. Por lo que en tu ejemplo, sería la página 4.
4- Depende cómo lo estructures, por ejemplo si quisieras tener una lista de páginas presentes (como en algunos ejercicios de la guía) por proceso no necesitarías hacer la cuenta, pero capaz es más fácil hacer la cuenta :)

Saludos!
      Lean

**Comment by facuxfdz** [comment]
Buenisimo gracias Lean! Queda mas claro. Gracias por tu respuesta 🙌🏼 
Cierro el issue. Saludos!
