### ISSUE TITLE
Dudas memoria y pid de procesos

### ISSUE THREAD

**Issue by cjgonzalo** [sisoputnfrba/foro#2726]
Buenas noches, vengo con algunas preguntas sobre el modulo de memoria
1. Que pasaría si cuando llega un nuevo proceso no hay suficientes marcos disponibles para asignarle? Habría que swapear páginas de otros procesos para darle lugar a este? Mandar directo a swap las paginas de este nuevo proceso, o no deberíamos tener en cuenta esto?

2. Cuando el kernel solicita la suspención de un proceso hay que mandar a swap toda la memoria de usuario de este? Sino, como recuperamos después la información de la memoria de usuario?

Otra pregunta que no tiene mucho que ver con memoria: Se puede enviar el pid directo desde la consola? Porque ahora estamos obteniendolo en el kernel y nos genera siempre el mismo y necesitaríamos que sean distintos para los archivos de swap

**Comment by LeandroCarbajales** [comment]
Buenas!
1- El grado de multiprogramación siempre va a ser menor o igual a (marcos_por_proceso * cant_marcos) por lo que no necesitan chequearlo

2- Claro! Aunque conceptualmente solamente necesitarían escribir en SWAP aquellas páginas que estén modificadas.

> ... Se puede enviar el pid directo desde la consola? Porque ahora estamos obteniendolo en el kernel y nos genera siempre el mismo y necesitaríamos que sean distintos para los archivos de swap

La idea es que el pid lo genere el Kernel, lo más simple que se me ocurre es un contador que inicie en 0 y se vaya aumentando cada vez que crean un PCB.

Te resuelve las dudas?
Saludos!
     Lean
