### ISSUE TITLE
Accesos a Swap en paralelo

### ISSUE THREAD

**Issue by lucas-marmo** [sisoputnfrba/foro#2727]
Buenas! Tengo una duda con respecto al enunciado, más que nada para confirmar. El enunciado dice lo siguiente:
>El SWAP, al imitar los accesos a disco, deberá implementarse como si fuera un único hilo de ejecución. Esto significa que no se podrán tener 2 o más lecturas/escrituras en paralelo. 

Teniendo en cuenta que nuestra memoria tiene 2 hilos en paralelo, uno que escucha los mensajes de `Kernel` y otro que escucha a `CPU`, nuestra duda es la siguiente:
Entonces no podríamos por ejemplo estar por un lado con el `hilo de kernel` suspendiendo un proceso (que en ese caso podría estar escribiendo en swap los marcos que tengan bit de modificado en 1) y por otro lado estar con el `hilo de CPU` realizando alguna lectura escritura en memoria (claramente en el archivo de swap de otro proceso distinto al del punto anterior)? Deberíamos tener algún semáforo de acceso a `Swap` (imaginando que el swap es como un archivo único, como en la realidad sería el disco).

Otra pregunta: Como en la práctica, cada desplazamiento dentro de un marco es de 1 byte, no? Entonces para cumplir con lo siguiente:
> Cabe aclarar que todos los valores a leer/escribir en memoria serán numéricos enteros no signados de 4 bytes, considerar el uso de uint32_t.

deberíamos tener 4 desplazamientos seguidos a partir del desplazamiento inicial que nos dan para poder escribir un dato.

Gracias!

**Comment by LeandroCarbajales** [comment]
Buenas!
La aclaración viene más por el lado de que si necesitan hacer 2 operaciones sobre SWAP, por ejemplo al reemplazar una página modificada, las mismas sean secuenciales y por lo tanto tarden el doble de tiempo. No hay problema con que la suspensión se haga concurrentemente ya que siempre van a estar tocando un archivo de SWAP que no está en ejecución.

Sobre la otra pregunta, sí, igual siempre las direcciones lógicas que referencien las instrucciones van a ser múltiplo de 4 por lo que no van a tener problema con el desplazamiento.

Saludos!
     Lean
