### ISSUE TITLE
Memoria: páginas, marcos y límites por procesos

### ISSUE THREAD

**Issue by ldelpieri** [sisoputnfrba/foro#2728]
Hola! tenemos una duda de memoria con los marcos y las páginas.
Entendemos que cada proceso tiene un límite de marcos que se le pueden se asignados, y que cada página hace referencia a un único marco. Teniendo esto en cuenta, suponiendo que tiene todos los marcos que le corresponden ya asignados, y llega una nueva petición de memoria, se envía a swap alguno de los que tenga para hacer lugar y se reemplaza por el nuevo, o directamente se niega la petición?

Otra duda que nos surge pero ahora con las páginas es que al organizar las páginas en las tablas cuando enviamos algo a swap no eliminamos esa página, sino que simplemente le ponemos el bit de presencia en 0 y liberamos el marco al que hacía referencia para que pueda ser usado. La pregunta es, ¿qué hacemos cuando el proceso tenga todas las páginas que le pertime la cantidad de entradas por tabla? importa el bit de presencia para la cuenta o aunque haya páginas en swap se cuentan para este caso?

Espero haber sido claro, nos cuesta un poco terminar de entender cómo trabaja la memoria con estas cuestiones.
Gracias!

**Comment by LeandroCarbajales** [comment]
Buenas!
La lógica es la misma que en los ejercicios que vemos en clase, si ya no se le pueden asignar más marcos se tendrá que reemplazar alguna de las páginas que están presentes :)

> ¿qué hacemos cuando el proceso tenga todas las páginas que le pertime la cantidad de entradas por tabla? importa el bit de presencia para la cuenta o aunque haya páginas en swap se cuentan para este caso?

Respondería lo mismo que acá https://github.com/sisoputnfrba/foro/issues/2711#issuecomment-1158116253

Te aclara las dudas?

Saludos!
      Lean
