### ISSUE TITLE
Tipo de dato de direcciones logicas y fisicas 

### ISSUE THREAD

**Issue by martina-facu** [sisoputnfrba/foro#2729]
Hola, Buenas tardes
Tengo una consulta acerca de que tipo de dato seria necesario usar para las direcciones fisicas y logicas en la mmu, nosostros habiamos elegido implementarlo con un int pero nos surge la duda de si podriamos tener pruebas con números que superen ese tamaño, por lo que quería consultar para confirmar si estaría bien que usemos int o deberíamos usar un double por ejemplo. 

Saludos!

**Comment by LeandroCarbajales** [comment]
Buenas!
Citando al enunciado:

> Cada instrucción se compone de un identificador y sus parámetros, siendo los últimos, en caso que los tuviera, siempre numéricos (valores enteros no signados de 4 bytes)

Por otro lado, la idea es que las pruebas sean "legibles" por lo que los valores no van a estar ni cerca del límite de un Int.

Saludos!
         Lean

**Comment by martina-facu** [comment]
Genial, gracias!
