### ISSUE TITLE
Duda sobre los retardos

### ISSUE THREAD

**Issue by thiagocabrera** [sisoputnfrba/foro#2730]
Buenas, nos surgieron 2 dudas con respecto a los retardos.
1. Cuando estamos creando los marcos de los procesos, tenemos que hacer un retardo por cada marco escrito en el swap o uno solo general? 
2. El retardo de memoria se hace en paralelo a lo que esté haciendo la memoria o se hace después de procesar todo lo necesario para responder?

**Comment by LeandroCarbajales** [comment]
Buenas!
1- A qué se refieren con "creando los marcos de los procesos"? La idea es que, al igual que en los ejercicios que vemos en clase, si tienen que traerse una página de SWAP por page fault, eso implica un acceso, y si hubiera reemplazo de una página modificada implicaría otro para escribir la página a reemplazar, por lo que podrían tener 2, 1 o 0 accesos a SWAP por cada instrucción de la CPU.
2- Creo que lo más simple de implementar es hacer un usleep antes de responder, citando al enunciado:
> Tiempo en milisegundos que se deberá esperar para dar una respuesta al CPU.

La idea es que, similar a como en algunos ejercicios (el 10 de la guía por ejemplo), según si la traducción está en TLB o no, una instrucción de CPU podría incurrir en 1 o más accesos a Memoria, en nuestro caso al haber paginación en 2 niveles, si no está en TLB incurriría en 3 accesos a Memoria por lo que tardaría el triple que si lo estuviera.

Te aclara las dudas?

Saludos!
      Lean

**Comment by thiagocabrera** [comment]
Con la pregunta 1) me refiero a cuando llega un proceso desde new y hay que inicializar las estructuras del proceso, creando su archivo swap con todos los marcos que va a utilizar, el programa debería hacer el retardo cada vez que va a escribir un marco o uno general para toda la escritura de marcos?
Con la pregunta 2) , lo preguntabamos porque nos dimos cuenta que si lo hacemos a lo último de todo (antes del send de respuesta) y justo tiene que swappear un marco entonces tendrías que esperar el retardo de swap y el retardo de cpu. Entonces si entendí bien eso estaría bien que suceda de esa manera?

**Comment by RaniAgus** [comment]
¡Buenas!
1. Respondo tu duda citando el enunciado:

> | Campo | Tipo | Descripción |
> |--|--|--|
> | RETARDO_MEMORIA | Numérico | Tiempo en milisegundos que se deberá esperar para dar una respuesta **al CPU**. |

A pesar de que en la realidad sí son accesos a disco, la intención de agregar los tiempos de retardo es poder diferenciar las velocidades entre los accesos a TLB y Memoria. Como la inicialización de un proceso es una interacción con Kernel, devuelvan la respuesta directamente sin ninguna espera.

Por otro lado, tengan en cuenta que a la hora de inicializar un proceso alcanza con crear el archivo y truncarlo. Pueden inicializarlo con ceros si quieren, pero no hace falta.

2. Sí, debería tener ambos retardos por acceso a memoria y a disco. Análogamente, en la vida real uno no puede cargar una página sin antes haber leído que su bit de presencia es 0, sería medio raro que ambas acciones se disparen en paralelo :P

Saludos

**Comment by LeandroCarbajales** [comment]
Buenas @thiagocabrera !

Te resolvió la duda? Se puede cerrar el issue?

**Comment by thiagocabrera** [comment]
Buenas sisi me olvidé de responder, mala mía.
Gracias x las respuestas!
