### ISSUE TITLE
Tamaño de memoria y tamaño de página

### ISSUE THREAD

**Issue by Naicon67** [sisoputnfrba/foro#2731]
Buenas, tengo una duda sobre el enunciado y es que el archivo de configuración de ejemplo dice:

TAM_MEMORIA=4096
TAM_PAGINA=64
ENTRADAS_POR_TABLA=4

Es decir, un proceso tiene como máximo 4 tablas de segundo nivel, es decir 16 marcos asignados. Pero el tamaño del marco es de 64 bytes, y si hago 4 (1er nivel) * 4 (2do nivel) * 64 (tamaño marco) me da que un proceso como máximo puede usar 1024 bytes, de los 4096 disponibles más arriba, sin contar con la memoria virtual. Es decir, como resuelvo esta incoherencia (si es que hice bien las cuentas)?  Priorizo el tamaño de memoria y el tamaño de página lo modifico?

**Comment by RaniAgus** [comment]
¡Buenas!
Solo con esos datos no hay razones para concluir que hay una inconsistencia, ya que se podría configurar en Kernel un `GRADO_MULTIPROGRAMACION` muy alto (por ejemplo, 16 procesos), por lo que la cantidad de `FRAMES_POR_PROCESO` tiene que ser menor a la cantidad máxima de páginas direccionables para no quedarse sin memoria ante la llegada de muchos procesos (por ejemplo, 4 frames).

De todas formas, a nivel general no deben cambiar los valores recibidos por config. Siempre asuman que los datos que les pasemos para las pruebas van a ser coherentes (y si ven alguna prueba en la que no lo son, avísennos porque puede ser un dedazo de nuestro lado 😅). 

También si sobra memoria no pasa nada: es como ponerle 16GB de RAM a una compu con un procesador de 32 bits, solo vas a poder direccionar 2^32 Bytes = 4GB de esos 16GB, pero arranca.

Saludos

**Comment by LeandroCarbajales** [comment]
Buenas @Naicon67 !
Te resolvió la duda? Se puede cerrar el issue?

**Comment by Naicon67** [comment]
Si perdón, contestado, gracias!
