### ISSUE TITLE
Duda corta sobre MMU y el dato de tamaño de página

### ISSUE THREAD

**Issue by 23737k** [sisoputnfrba/foro#2732]
Hola, tenía una duda simple. 
![image](https://user-images.githubusercontent.com/82678482/175752234-312b1a2b-642e-4af6-949e-9eb60a04c495.png)
¿De dónde saco el tamaño de página? 
Porque este dato lo tiene memoria en su config, y no creo que el cpu tenga que hacer un acceso más para pedirle este dato. ¿Debería cargar el config de memoria en el CPU también? 

Gracias.

**Comment by RaniAgus** [comment]
¡Buenas! Respondo tu duda con otra cita del enunciado, más arriba, en la página 16 😄

> ### Lineamiento e implementación
> Al iniciarse el módulo, se conectará con la Memoria y realizará un handshake inicial para recibir la configuración relevante de la misma que le permita traducir las direcciones lógicas a físicas. Esto debería incluir al menos cantidad de entradas por tabla de páginas y tamaño de página.

Saludos

**Comment by 23737k** [comment]
Ahh, que despistado que soy. ¡Mil gracias!
