### ISSUE TITLE
Memoria: Bytes vs Uint32s

### ISSUE THREAD

**Issue by GonzaloMartinezSa** [sisoputnfrba/foro#2733]
Hola, hace poco escuche de un compañero que los marcos de memoria hay que manejarlos como si estuviesen divididos en bytes en vez de unit32, como lo habíamos pensado en principio. Estuve viendo unos issues que parecen sugerir eso también. Pero me parece raro. 

Escribo para que me confirmen cómo es la cosa, bien completo.

El tema, por ej, es que escuche que entonces el desplazamiento en una direccion te da el Nro (o indice, digamos) de Byte en vez del de Uint32. Esto es raro porque se podria hacer, ponele WRITE 2 10, que queda en "el medio" del uint32 que deberia ir ahi. Vi en un issue que deberiamos considerar que eso no se va a hacer y listo, pero por qué tener una cantidad de direcciones que puedo poner en el WRITE, si solo puedo usar 1/4 de ellas? 
Por qué no hacer que el desplazamiento sea el indice del próximo Uint32, en vez del próximo Byte? O sea, WRITE 1 10 usa un uint32 para poner 10 y WRITE 2 20 usa el uint32 directamente siguiente para poner un 20. Por decirlo de alguna manera, nunca trabajar con Bytes y siempre con Uint32s.

El punto es que no me queda muy claro cómo es. Como nota, como lo estabamos pensando era que los marcos estaban divididos en uint32, y las direcciones tanto lógicas como físicas estaban acorde a eso. También, para asignar los datos de un marco empezabamos con un malloc(tam. pagina) en esos datos, que despues interpretabamos como un array de uint32, y ahí quedaba.

**Comment by iago64** [comment]
Buenas! Cómo va?

La memoria es un **array de bytes**, que nosotros les digamos que los datos que van a escribir sean de tipo uint_32 es simplemente para facilitar el desarrollo del TP ya que no nos interesa que estén  teniendo que interpretar tipos de datos diferentes (char*, uint16_t, etc, etc).

Dicho lo anterior, nada impediría que en una prueba pongamos un WRITE de la dirección 0 y un READ de la dirección 2, ya que a fines prácticos los datos que se guardan o leen en la memoria, no los vamos a utilizar para ningún cálculo, o mismo podríamos poner un WRITE en la dirección 2 y el siguiente en la 6 y seguiría siendo igual de válido.

Esto es mas o menos lo que pasa cuando, por ejemplo, manqueamos con los desplazamientos al serializar y justamente al sistema operativo, no le importa lo que hagamos mientras que estemos dentro de nuestro espacio de direcciones. Ahora, si nos vamos de ahi, es donde aparece nuestro hermosa amiga la señal SIGSEGV o también conocida como segfault o segment fault, que es la forma del SO para venir a cortarnos la ejecución (Esto no va a pasar en el TP, ya que todas las direcciones que les damos son del espacio de direcciones reservados al inicio del proceso).

Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas! @GonzaloMartinezSa 

Te resolvió la duda? Se puede cerrar el issue?
