### ISSUE TITLE
Duda tamaño TLB

### ISSUE THREAD

**Issue by lucas-marmo** [sisoputnfrba/foro#2734]
Buenas, estamos analizando varios casos puntuales que se nos pueden dar y entre ellos nos surgió una duda con el tamaño de la TLB. Siempre su cantidad de entradas va a ser menor o igual a `marcos_por_proceso`, no? Porque en caso de que sea mayor nos encontramos con el problema de que la TLB tendría datos "desactualizados".
Leímos en el issue #2709 que si la TLB está por guardar una página y un marco, pero detecta que ya está ese marco guardado con otra página, entonces debe actualizar la página y colocar la que acaba de llegar, en lugar de agregarse en una nueva entrada de la TLB o eliminar cualquier otra siguiendo con el criterio de los algoritmos. En ese caso, creería que aunque los `marcos_por_proceso` sean menores a las entradas de la TLB, ni siquiera me afectaría ya que siempre voy a guardar en la TLB hasta la cantidad de marcos_por_proceso, nunca agregaría uno extra ya que se van reemplazando.

Saludos

**Comment by LeandroCarbajales** [comment]
Buenas!
Exactamente, cuando se hace un reemplazo de página, la TLB debería borrar la entrada de la página que se está reemplazando ya que ya no sería válida, por lo que tus entradas en TLB nunca van a superar a la cantidad de marcos asignados al proceso aunque la misma pueda tener más.

Saludos!
       Lean

**Comment by lucas-marmo** [comment]
Genial muchas gracias!
