### ISSUE TITLE
Lectura y escritura en espacio de usuario

### ISSUE THREAD

**Issue by Matias-Balboa** [sisoputnfrba/foro#2735]
Hola, ¿Cómo están?, tengo una duda con respecto a la lectura y escritura de espacio de usuario(EU) en memoria.
Entiendo que CPU le manda al modulo de memoria la dirección física y un void* para escribir en EU, y en caso de que se quiera leer CPU manda una dirección física y Memoria debería retornar lo que hay en EU.

Mi duda es la siguiente: 
A la hora de escribir en EU, ¿puedo guardar el size de lo que se escribo?.
Un ejemplo de como se vería una pagina de EU:
" 4hola                 9comoestas                     4bien"
Entonces de esta manera a la hora de leer el EU, CPU me mandaría la dirección física (en donde debería estar el size) y yo sabría cuantos bytes tengo que leer para no agarrar elementos que no me corresponden.

Otra opción seria leer hasta encontrar un carácter de corte
" hola\0                 9comoestas\0                     4bien\0"

Pero no se cual solución es valida.

Saludos!!

**Comment by RaniAgus** [comment]
¡Buenas! Cito en el enunciado la parte de "Execute" (p. 17):

> Cabe aclarar que **todos** los valores a leer/escribir en memoria serán numéricos enteros no signados de **4 bytes**, considerar el uso de uint32_t.

Por lo tanto, no hace falta pasar tamaños, ya que todos los valores son de 4 bytes.

Saludos

**Comment by Matias-Balboa** [comment]
No me habia dado cuenta de esa parte, gracias.
