### ISSUE TITLE
Simultaneidad en búsqueda de página 

### ISSUE THREAD

**Issue by DamianArielLerner** [sisoputnfrba/foro#2736]
Hola que tal, me acaba de surgir una duda revisando la teoría, en el TP vamos a tener que buscar la página en la TLB y en el módulo Memoria en simultáneo? O primero la TLB, y si no se encuentra, en Memoria? Desde ya, muchas gracias!

**Comment by LeandroCarbajales** [comment]
Buenas!
Igual que como harían un ejercicios de la guía, primero en TLB, luego en sus tablas de páginas.
El hecho de que en la realidad ambas operaciones se hagan en simultáneo, así como que la TLB lee todas sus entradas simultáneamente es una particularidad de eficiencia del HW que no es la idea representar en el TP.

Saludos!
        Lean

**Comment by LeandroCarbajales** [comment]
Buenas! @DamianArielLerner 

Te resolvió la duda? Se puede cerrar el issue?

**Comment by DamianArielLerner** [comment]
Perdon Lean
