### ISSUE TITLE
Dudas algoritmos clock y clock-modificado

### ISSUE THREAD

**Issue by lucas-marmo** [sisoputnfrba/foro#2738]
Buenas, mientras hacía ejercicios de la guía para practicar para el parcial me di cuenta que estábamos cometiendo un error con el equipo en cuando a la implementación de estos algoritmos. La cuestión es que nosotros ibamos avanzando el puntero en orden creciente por número de página (solo se frenaba a tomar alguna decisión cuando bit de presencia era igual a 1).
Pero realizando los ejercicios nos dimos cuenta que el puntero no avanza así, sino que avanza recorriendo los marcos en el orden que le fueron asignados al proceso (si alguna página reemplaza a otra en un mismo marco, dicho marco mantiene su misma posición en nuestro orden). En este caso tendríamos que tener, aparte de las tablas de páginas, una lista ordenada por cada proceso que sepa qué marcos de memoria están siendo ocupados y por qué páginas (de ese proceso), y el puntero recorrería esta lista, similar a lo que hacemos en las guías de ejercicios.
Básicamente estoy consultando para confirmar si esto que nos dimos cuenta es así, ya que nos implicaría refactorizar varias cosas del tp que no teníamos previstas (esta lista sería modificada en casi todas las funciones principales de memoria).
Muchas gracias.

**Comment by LeandroCarbajales** [comment]
Buenas!
Clock y clock-M derivan de FIFO, por lo que las páginas deberían ser iteradas en orden de carga (igual que FIFO), por lo que entiendo que su implementación actual no cumpliría con eso. Hay varias maneras de implementarlo, pueden hacerse una estructura auxiliar como en los ejercicios, o por ejemplo tener una columna de "instante de carga" en la tabla e iterar las páginas presentes por orden de carga.

**Comment by lucas-marmo** [comment]
Perfecto, cierro el issue, gracias!
