### ISSUE TITLE
Falla consistente de un send()

### ISSUE THREAD

**Issue by jschuhmann47** [sisoputnfrba/foro#2739]
Buenas, con nuestro grupo tenemos un problema que no conseguimos darnos cuenta por qué sucede.

Tenemos un send desde memoria a CPU, que al ingresar un primer proceso funciona siempre bien, y al mandar el mismo proceso nuevamente falla en todas las ocasiones con el mismo output.

En memoria tenemos esto
```c
void procesar_entrada_tabla_primer_nv(int socket_cpu){
if(recv(socket_cpu, &requestPrimerTabla, sizeof(uint32_t), MSG_WAITALL) == -1){
        log_error(memoria_swapLogger, "Memoria: Error al recibir requestPrimerTabla de CPU: %s", strerror(errno));
        exit(-1);
    }

    t_primerNivel* entradaTabla = list_get(tablaPrimerNivel, requestPrimerTabla);
    uint32_t indiceSegundoNivel = entradaTabla->indiceTablaSegundoNivel;

    if(send(socket_cpu,&indiceSegundoNivel,sizeof(uint32_t),0) == -1){ //ACA SE ENVIA BIEN
        log_error(memoria_swapLogger, "Memoria: Error al enviar indiceSegundoNivel a CPU: %s", strerror(errno));
        exit(-1);
}
void procesar_entrada_tabla_segundo_nv(int socket_cpu){
	log_info(memoria_swapLogger, "Memoria: Procesando entrada de tabla de segundo nivel");

    uint32_t nroTabla;
    if(recv(socket_cpu, &nroTabla, sizeof(uint32_t), MSG_WAITALL) == -1){
        log_error(memoria_swapLogger, "Memoria: Error al recibir nroTabla de CPU: %s", strerror(errno));
        exit(-1);
    }
    
    t_tablaSegundoNivel* tablaSegundoNivel = list_get(tablasSegundoNivel, nroTabla); //encuentra la tabla correspondiente
	}
```

mientras que en el MMU tenemos esto
```c
	//...
	op_code opCode = TABLAUNO;
    if(send(socket_memoria,&opCode,sizeof(op_code),0)<0){
        log_error(cpuLogger, "CPU: No se pudo enviar opCode a Memoria.");
        exit(-1);
    }
    
    if(send(socket_memoria,&entradaTablaPrimerNivel,sizeof(uint32_t),0)<0){
        log_error(cpuLogger, "CPU: No se pudo enviar entradaTablaPrimerNivel a Memoria.");
        exit(-1);
    }
    
    //log_info(cpuLogger, "CPU: Se mando entradaTablaPrimerNivel a Memoria.");
    if(recv(socket_memoria,&rtaTablaPrimerNivel,sizeof(uint32_t),MSG_WAITALL)==-1){ //ACA SE RECIBE MAL
        log_error(cpuLogger, "CPU: No se pudo recibir rtaTablaPrimerNivel de Memoria.");
        exit(-1);
    }
    
    log_info(cpuLogger, "CPU:RTA TABLA (INDICE) %i",rtaTablaPrimerNivel);
    //log_info(cpuLogger, "CPU: Se recibio rtaTablaPrimerNivel de Memoria.");

    op_code opCodeDos = TABLADOS;
	//...
```
Lo que se debería asignar es el indice de la tabla del proceso en memoria. La primera ejecucion selecciona la tabla 0 como libre y manda y recibe 0.
Luego el segundo proceso asigna la 1, y al recibirla recibe "42" en todas las ocasiones. Este 42 sospechamos que podria ser el 42 del pseudocodigo que estamos mandando (WRITE 4 42), pero se supone que al asignar indiceSegundoNivel=1 antes de hacer el send es raro que se pise con algo.
No nos podemos dar cuenta de qué es lo que falla. Probamos lo siguiente:
- Chequeamos si el socket se está usando al mismo tiempo en otra funcion u hilo, pero no parece es el caso
- Tanto el send como el recv podrian estar devolviendo -1, pero tampoco

Nos resulta extraño porque estamos mandando exactamente las mismas instrucciones.

Desde ya muchas gracias

**Comment by LeandroCarbajales** [comment]
Buenas!
Si cambian la instrucción para que mande otro valor (por ejemplo, WRITE 4 100, les llega siempre un 100 también?
Si ese es el caso, probablemente estén mandando/recibiendo algo indebidamente, les recomiendo ejecutar ambos CPU y Memoria en debug y colocar algún breakpoint donde se envíen/reciban estos datos para chequear bien los valores.

**Comment by jschuhmann47** [comment]
Voy a probar eso a ver que onda, por ahora cierro el issue. Cualquier cosa pregunto de nuevo, gracias!

**Comment by LeandroCarbajales** [comment]
Buenas!
Probaron esto? 
> Si cambian la instrucción para que mande otro valor (por ejemplo, WRITE 4 100) les llega siempre un 100 también?

Me suena que, probablemente al hacer un READ, del lado de la memoria están enviando el valor leído (en este caso 42), pero del lado del CPU nunca lo reciben, por lo que ese valor queda en el buffer del socket hasta que hacen el próximo recv() (en este caso al esperar el índice de la 2da tabla).

**Comment by jschuhmann47** [comment]
> Me suena que, probablemente al hacer un READ, del lado de la memoria están enviando el valor leído (en este caso 42), pero del lado del CPU nunca lo reciben

Efectivamente era esto, se nos re pasó por alto. Muchas gracias Lean!! 

Cierro el issue
