### ISSUE TITLE
Ubicacion puntero prueba "Memoria - Clock y Clock-M"

### ISSUE THREAD

**Issue by DamianArielLerner** [sisoputnfrba/foro#2740]
Buenas, en cuanto al ejemplo de la prueba "Memoria - Clock y Clock-M", me surgió una duda que no se si ya aclararon. Tengo entendido que al querer escribir realizar esta instrucción: [WRITE 1024 3000](https://github.com/sisoputnfrba/kiss-pruebas/blob/main/MEMORIA_1#L9), como por proceso tengo máximo 3 marcos, ya no me quedarían libres y tendría que utilizar el algoritmo de sustitución. En ese caso, mi puntero, antes de empezar con el algoritmo, estaría apuntando al primer frame que asigné? Gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Justo en ese momento no deberían tener un reemplazo, ya que el proceso se fue a I/O [2 instrucciones antes](https://github.com/sisoputnfrba/kiss-pruebas/blob/main/MEMORIA_1#L7), y como la I/O es de 6000ms y el tiempo de suspensión es de 5000ms, deberían haber suspendido, con lo cual en el write que citas recién estarían cargando el segundo frame 😉 

Saludos.-

**Comment by DamianArielLerner** [comment]
Hola Dami. Perdón, hay algo que me marea un poco, luego de que se haya suspendido el proceso y vuelva a memoria, debería volver todo el proceso de swap no? Es decir, pasarían a tener de nuevo el bit de presencia las páginas que previamente estaban cargadas en memoria, al menos en este caso. Por lo que no comprendería porque después de regresar a memoria, al ejecutar la instrucción de la que estábamos hablando ocuparía el segundo frame. Gracias!

**Comment by DamianArielLerner** [comment]
Ahora entendí, como hace un [READ 0](https://github.com/sisoputnfrba/kiss-pruebas/blob/main/MEMORIA_1#L8), esta usando un marco, y el [WRITE 1024 3000](https://github.com/sisoputnfrba/kiss-pruebas/blob/main/MEMORIA_1#L9) usa el segundo libre, mil disculpas Dami, gracias!

**Comment by DamianArielLerner** [comment]
Buenas, vuelvo a abrir el issue porque me surgió otra duda, si antes de ejecutar la instrucción [IO 6000](https://github.com/sisoputnfrba/kiss-pruebas/blob/main/MEMORIA_1#L7) yo le asigné al proceso los marcos 1, 2 y 3 por ejemplo, a la hora de ejecutar la instrucción [WRITE 1024 3000](https://github.com/sisoputnfrba/kiss-pruebas/blob/main/MEMORIA_1#L9), se me va a asignar el marco 2 o el 4? Saludos!

**Comment by RaniAgus** [comment]
¡Buenas! Antes que nada, respondo la duda anterior:

> luego de que se haya suspendido el proceso y vuelva a memoria, debería volver todo el proceso de swap no? Es decir, pasarían a tener de nuevo el bit de presencia las páginas que previamente estaban cargadas en memoria, al menos en este caso.

Esto no es así, al finalizar la suspensión no hay que volver a cargar las páginas que estaban en memoria al momento de suspender, sino que se siguen cargando a demanda (como comentaba en #2666 y #2719).

Entonces, antes de que se ejecute [READ 0](https://github.com/sisoputnfrba/kiss-pruebas/blob/main/MEMORIA_1#L8) el proceso no debería tener ninguna página cargada en memoria.

Saludos

**Comment by LeandroCarbajales** [comment]
Buenas @DamianArielLerner !
Te sirvió la respuesta de Agus?

**Comment by iago64** [comment]
Por inactividad cerramos, cualquier cosa pueden re abrir el issue o citarlo en uno nuevo.
