### ISSUE TITLE
Volver de SWAP sin marcos libres

### ISSUE THREAD

**Issue by DamianArielLerner** [sisoputnfrba/foro#2742]
Buenas, me surgió una duda que no se si ya la contestaron, digamos que mi proceso se suspendió y ya no me quedan marcos libres porque los están utilizando otros procesos, como es reemplazo local, tengo entendido que ese proceso que volvió de suspenderse no le va a poder robar los marcos a otros procesos si estos siguen presentes en memoria. Que deberíamos hacer en ese caso? O nunca nos vamos a encontrar con esa situación en la que no tenemos marcos libres? Gracias!

**Comment by RaniAgus** [comment]
¡Buenas! El grado de multiprogramación va a ser consistente con la configuración de memoria para que siempre queden marcos libres para los procesos que están en READY/EXEC/BLOCKED, como se menciona en https://github.com/sisoputnfrba/foro/issues/2707#issuecomment-1158110706, https://github.com/sisoputnfrba/foro/issues/2719#issuecomment-1160932514 y https://github.com/sisoputnfrba/foro/issues/2726

Saludos
