### ISSUE TITLE
Problemas al escribir y leer de void* como memoria

### ISSUE THREAD

**Issue by pmdea** [sisoputnfrba/foro#2743]
Hola buenas noches!
Tal vez algo tarde la duda pero haciendo pruebas más extensas sobre el módulo de memoria, en específico el espacio de usuario con su void*, me encuentro que no estoy logrando escribir y recuperar correctamente los datos que voy guardando.
No se si hay alguna forma ya dada pero en los issues que revisé no terminé de encontrar el mismo error que estoy teniendo, pero, utilizando tanto memcpy como aritmética de punteros, cuando quiero guardar una variable lo """logro""" pero para traerla nuevamente me es imposible.

Me hice un ejemplo para demostrar el error que estoy teniendo

### 📝 Código relevante

```
	void* mem = malloc(4096); // reservo 4096 bytes

	uint32_t* test1 = malloc(sizeof(uint32_t));
	*test1=12344444;

	uint32_t* test2 = malloc(sizeof(uint32_t));
	*test2=56788888; // declaro unos valores de prueba

	memcpy(&mem, &test1, sizeof(uint32_t)); // copio a mem el test1
	memcpy(&mem+sizeof(uint32_t), &test2, sizeof(uint32_t)); // copio a mem el test2 con un offset del sizeof(uint32_t)

	uint32_t* response1 = malloc(sizeof(uint32_t));
	uint32_t* response2 = malloc(sizeof(uint32_t));

	memcpy(&response1, &mem, sizeof(uint32_t));
	memcpy(&response2, &mem+sizeof(uint32_t), sizeof(uint32_t));
	printf("response1: %d\n", *response1); //Obtengo 12344444, el valor correcto
	printf("response2: %d\n", *response2); //Obtengo 0, incorrecto
```
También hice un método (malo pero solo para probar) de recorrer el void* mem e imprimir lo que enceuntro cada 1 sizeof(uint32) y obtengo lo siguiente:

`12344444 0 0 0 0 0 33 0 56788888 0 
`
Pareciera como si entre el valor de test1 y test2, se guardan valores que no veo bien de donde salen. ¿Son algun efecto no esperado del memcpy de la forma que lo estoy usando?

Probé también hacer un memset de todo el void* mem en 0 para probar si lo estaba ensuciando de alguna forma y no obtuve resultados distintos.

Dudo si estoy interpretando bien como funcionan los punteros o el memcpy pero por lo que lo utilicé con char* y otras estructuras, entiendo que deberia estar funcionando como espero.

Muchas gracias y disculpen si existía un issue parecido pero no vi que sea de programación en C, solo conceptuales.

**Comment by pmdea** [comment]
Investigando me di cuenta que el error era mío por pasar los pointers con el '&' en vez del puntero directamente. Cambiando eso ya lo logré solucionar.

De todas formas si hay mejor forma de manejar la memoria me interesaria saber

**Comment by iago64** [comment]
Buenas! Cómo va?

Lograste solucionar el problema porque justamente `memcpy()` recibe punteros, esos punteros ya los habías declarado y les habías hecho malloc, pero después estabas pasándole a `memcpy()` el puntero del puntero y por eso te fallaba, con lo que hiciste estas en la solución correcta y no deberías tener al menos ese tipo de problemas a futuro.

Por cualquier cosa siempre les recomendamos que los problemas de memoria los analicen con Valgrind que va a darles una mano enorme a entender este tipo de situaciones 😉 

Saludos.-

**Comment by pmdea** [comment]
Claro!
Creo que entre probar varias formas se me pasó eso.

Probé usando Valgrind pero no me marcaba ningún problema. Tal vez me faltó pasarle algun flag.

Cierro issue!
