### ISSUE TITLE
Duda escribir archivo 

### ISSUE THREAD

**Issue by matiasrizzatobusta** [sisoputnfrba/foro#2744]
Hola buenos dias, con mi equipo estamos teniendo un problema al querer escribir en un archivo de swap. La funcion que tenemos funcionaba bien cuando el archivo se creaba dentro de la carpeta memoria, pero cuando quisimos escribir en un archivo dentro de la carpeta swap no estaria andando bien. Lo unico que cambiamos fue lo que recibia la funcion escribir, ya que antes solo le pasabamos el nombre del archivo y ahora un path.

```
void crear_archivo(char *nuevo_archivo)
{
    char *ruta_final= string_new();

    string_append(&ruta_final, "/home/utnso/swap/");
    string_append(&ruta_final, nuevo_archivo);
    struct stat st = {0};

    if (stat("/home/utnso/swap", &st) == -1) { //poner ruta a la carpeta donde se vana crear los archivos .swap

         mkdir("/home/utnso/swap/", 0700);
         printf("created directory swap successfully! \n");

     }
    if (!verificar_archivo(nuevo_archivo))
     {
         FILE *archivo = fopen(ruta_final, "w+");
         //w+ es para que sea de lectura escritura.si queremos escribir y leer en binario cambiarlo a wb+
         fclose(archivo);
     }
     else
     {
         //error_show("El directorio: %s ya existe\n", ruta_archivo);
     }
     free(ruta_final);
}
char* pasar_a_char(uint32_t num){

    char* terminacion = ".swap";
    //char* str;


    //char* num_char = my_itoa(num,str);
    char* num_char = itoa(num);

    char* nuevo_path = strcat(num_char,terminacion);

    //log_warning(log_memoria,"El nuevo path es: %s",nuevo_path);

    return nuevo_path;
}

void escribir_swap(char* filepath,char* text ,int pagina,int offset){

	 printf("Will write text '%s'\n", text);

	    int fd = open(filepath, O_RDWR | O_CREAT, (mode_t)0600);

	    if (fd == -1)
	    {
	        perror("Error opening file for writing");
	        exit(EXIT_FAILURE);
	    }

	    ftruncate(fd,0);
	    ftruncate(fd,tam_swap);

	    // Stretch the file size to the size of the (mmapped) array of char

	    size_t textsize = strlen(text) + 1; // + \0 null character

	    if (lseek(fd, textsize-1, SEEK_SET) == -1)
	    {
	        close(fd);
	        perror("Error calling lseek() to 'stretch' the file");
	        exit(EXIT_FAILURE);
	    }

	    if (write(fd, "", 1) == -1)
	    {
	        close(fd);
	        perror("Error writing last byte of the file");
	        exit(EXIT_FAILURE);
	    }


	    // Now the file is ready to be mmapped.

	    char *map = mmap(NULL, tam_swap, PROT_READ | PROT_WRITE, MAP_FILE | MAP_SHARED , fd, 0);
	    if (map == MAP_FAILED)
	    {
	        close(fd);
	        perror("Error mmapping the file");
	        exit(EXIT_FAILURE);
	    }

	    memcpy(map +pagina*tam_pagina +offset,text,textsize);

	    // Write it now to disk
	    if (msync(map, textsize, MS_SYNC) == -1)
	    {
	        perror("Could not sync the file to disk");
	    }
	    printf("direccion pagina 1: %p\n",map);

	    // Don't forget to free the mmapped memory
	    if (munmap(map, tam_swap) == -1)
	    {
	        close(fd);
	        perror("Error un-mmapping the file");
	        exit(EXIT_FAILURE);
	    }

	    // Un-mmaping doesn't close the file, so we still need to do that.
	    close(fd);


}
```

**Comment by RaniAgus** [comment]
¡Buenas! Si funcionaba bien en una carpeta y no en otra tiene toda la pinta de ser un problema de permisos. Pueden probar de cambiar el segundo parámetro de `mkdir()` por `775` (o sea, `rwxrwxr-x`).

Por otro lado, veo que `escribir_swap()` escribe un `char*`: tengan cuidado porque si en alguna parte de esa página que van a mandar a swap hay un byte seteado en `0x00` (o sea, `'\0'`) la escritura va a cortar ahí porque `strlen()` va leyendo hasta encontrar ese byte.

Saludos

**Comment by matiasrizzatobusta** [comment]
ahi corregimos lo de escribir, pusimos como `void escribir_swap(char* filepath,char* text ,int pagina,int offset){

	FILE *file = fopen(filepath, "rb+");

	int desp = pagina * tamanio_paginas + offset;

	fseek(file, desp, SEEK_SET);

	fwrite(text, sizeof(text), 1, file);



	fclose(file);

}
`
en cuanto a los permisos, ahi probe cambiarlo a 775 pero sigo teniendo problemas. La consola de memoria me tira lo siguiente:
`` [DEBUG] 11:28:15:919 memoria/(9799:9825): El tam del proceso recbido por kernel es: 2048
[DEBUG] 11:28:15:919 memoria/(9799:9825): El float es: 8.000000
[DEBUG] 11:28:15:919 memoria/(9799:9825): El size de la lista de paginas del proceso es: 8
[DEBUG] 11:28:15:919 memoria/(9799:9825): El size de la lista de tablas de 2do nivel es 2
[DEBUG] 11:28:15:919 memoria/(9799:9825): El size de la tabla de primer nivel es: 2
[TRACE] 11:28:15:919 memoria/(9799:9825): envie el inice a kernel 0
Segmentation fault (core dumped)
`

**Comment by matiasrizzatobusta** [comment]
update: probe crear la carpeta a mano yo y pude hace que cree un archivo, pero a la hora de escrirlo sigue tirando seg fault

**Comment by RaniAgus** [comment]
Les recomiendo revisar con `perror` los valores de retorno de las funciones `mkdir`, `fopen`, `fseek`, etc:

```c
FILE *file = fopen(filepath, "rb+");
if (file == NULL) {
    perror("fopen");
}

if (fseek(file, desp, SEEK_SET) == -1) {
    perror("fseek");
}

// y así...
```

Para saber qué valores de retorno son de error, pueden buscar en los manuales oficiales ejecutando desde la consola `man [funcion]` (ej: `man fopen`) y scrolleando hasta la sección "Return value". También los pueden encontrar, por ejemplo, en [esta página](https://man7.org/linux/man-pages/man3/fopen.3.html).

También más allá de probarlo en un entorno controlado, estaría bueno que lo puedan probar en el TP usando el debugger y Valgrind como les comenté más arriba.

Saludos

**Comment by matiasrizzatobusta** [comment]
Buenas! anduve probando correr el programa con valgrind y me tiro lo siguiente:
[INFO] 21:25:44:275 memoria/(12128:12128): Cliente conectado (a MEMORIA)

[DEBUG] 21:25:44:298 memoria/(12128:12142): el cliente sock es: 5
==12128== Thread 2:
==12128== Use of uninitialised value of size 4
==12128==    at 0x411524B: _itoa_word (_itoa.c:179)
==12128==    by 0x4119221: vfprintf (vfprintf.c:1631)
==12128==    by 0x413C3DE: vsnprintf (vsnprintf.c:114)
==12128==    by 0x4078FF8: _string_append_with_format_list (in /usr/lib/libcommons.so)
==12128==    by 0x40785E0: string_from_vformat (in /usr/lib/libcommons.so)
==12128==    by 0x407830C: _log_write_in_level (in /usr/lib/libcommons.so)
==12128==    by 0x40780E3: log_trace (in /usr/lib/libcommons.so)
==12128==    by 0x804980E: procesar_conexion_memoria_kernel (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x405E294: start_thread (pthread_create.c:333)
==12128==    by 0x41BD0AD: clone (clone.S:114)
==12128== 
==12128== Conditional jump or move depends on uninitialised value(s)
==12128==    at 0x4115253: _itoa_word (_itoa.c:179)
==12128==    by 0x4119221: vfprintf (vfprintf.c:1631)
==12128==    by 0x413C3DE: vsnprintf (vsnprintf.c:114)
==12128==    by 0x4078FF8: _string_append_with_format_list (in /usr/lib/libcommons.so)
==12128==    by 0x40785E0: string_from_vformat (in /usr/lib/libcommons.so)
==12128==    by 0x407830C: _log_write_in_level (in /usr/lib/libcommons.so)
==12128==    by 0x40780E3: log_trace (in /usr/lib/libcommons.so)
==12128==    by 0x804980E: procesar_conexion_memoria_kernel (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x405E294: start_thread (pthread_create.c:333)
==12128==    by 0x41BD0AD: clone (clone.S:114)
==12128== 
==12128== Conditional jump or move depends on uninitialised value(s)
==12128==    at 0x41187A4: vfprintf (vfprintf.c:1631)
==12128==    by 0x413C3DE: vsnprintf (vsnprintf.c:114)
==12128==    by 0x4078FF8: _string_append_with_format_list (in /usr/lib/libcommons.so)
==12128==    by 0x40785E0: string_from_vformat (in /usr/lib/libcommons.so)
==12128==    by 0x407830C: _log_write_in_level (in /usr/lib/libcommons.so)
==12128==    by 0x40780E3: log_trace (in /usr/lib/libcommons.so)
==12128==    by 0x804980E: procesar_conexion_memoria_kernel (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x405E294: start_thread (pthread_create.c:333)
==12128==    by 0x41BD0AD: clone (clone.S:114)
==12128== 
==12128== Conditional jump or move depends on uninitialised value(s)
==12128==    at 0x4118CBD: vfprintf (vfprintf.c:1631)
==12128==    by 0x413C3DE: vsnprintf (vsnprintf.c:114)
==12128==    by 0x4078FF8: _string_append_with_format_list (in /usr/lib/libcommons.so)
==12128==    by 0x40785E0: string_from_vformat (in /usr/lib/libcommons.so)
==12128==    by 0x407830C: _log_write_in_level (in /usr/lib/libcommons.so)
==12128==    by 0x40780E3: log_trace (in /usr/lib/libcommons.so)
==12128==    by 0x804980E: procesar_conexion_memoria_kernel (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x405E294: start_thread (pthread_create.c:333)
==12128==    by 0x41BD0AD: clone (clone.S:114)
==12128== 
==12128== Conditional jump or move depends on uninitialised value(s)
==12128==    at 0x4118B04: vfprintf (vfprintf.c:1631)
==12128==    by 0x413C3DE: vsnprintf (vsnprintf.c:114)
==12128==    by 0x4078FF8: _string_append_with_format_list (in /usr/lib/libcommons.so)
==12128==    by 0x40785E0: string_from_vformat (in /usr/lib/libcommons.so)
==12128==    by 0x407830C: _log_write_in_level (in /usr/lib/libcommons.so)
==12128==    by 0x40780E3: log_trace (in /usr/lib/libcommons.so)
==12128==    by 0x804980E: procesar_conexion_memoria_kernel (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x405E294: start_thread (pthread_create.c:333)
==12128==    by 0x41BD0AD: clone (clone.S:114)
==12128== 
==12128== Conditional jump or move depends on uninitialised value(s)
==12128==    at 0x4118B4D: vfprintf (vfprintf.c:1631)
==12128==    by 0x413C3DE: vsnprintf (vsnprintf.c:114)
==12128==    by 0x4078FF8: _string_append_with_format_list (in /usr/lib/libcommons.so)
==12128==    by 0x40785E0: string_from_vformat (in /usr/lib/libcommons.so)
==12128==    by 0x407830C: _log_write_in_level (in /usr/lib/libcommons.so)
==12128==    by 0x40780E3: log_trace (in /usr/lib/libcommons.so)
==12128==    by 0x804980E: procesar_conexion_memoria_kernel (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x405E294: start_thread (pthread_create.c:333)
==12128==    by 0x41BD0AD: clone (clone.S:114)
==12128== 
==12128== Use of uninitialised value of size 4
==12128==    at 0x411524B: _itoa_word (_itoa.c:179)
==12128==    by 0x4119221: vfprintf (vfprintf.c:1631)
==12128==    by 0x413C3DE: vsnprintf (vsnprintf.c:114)
==12128==    by 0x407902A: _string_append_with_format_list (in /usr/lib/libcommons.so)
==12128==    by 0x40785E0: string_from_vformat (in /usr/lib/libcommons.so)
==12128==    by 0x407830C: _log_write_in_level (in /usr/lib/libcommons.so)
==12128==    by 0x40780E3: log_trace (in /usr/lib/libcommons.so)
==12128==    by 0x804980E: procesar_conexion_memoria_kernel (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x405E294: start_thread (pthread_create.c:333)
==12128==    by 0x41BD0AD: clone (clone.S:114)
==12128== 
==12128== Conditional jump or move depends on uninitialised value(s)
==12128==    at 0x4115253: _itoa_word (_itoa.c:179)
==12128==    by 0x4119221: vfprintf (vfprintf.c:1631)
==12128==    by 0x413C3DE: vsnprintf (vsnprintf.c:114)
==12128==    by 0x407902A: _string_append_with_format_list (in /usr/lib/libcommons.so)
==12128==    by 0x40785E0: string_from_vformat (in /usr/lib/libcommons.so)
==12128==    by 0x407830C: _log_write_in_level (in /usr/lib/libcommons.so)
==12128==    by 0x40780E3: log_trace (in /usr/lib/libcommons.so)
==12128==    by 0x804980E: procesar_conexion_memoria_kernel (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x405E294: start_thread (pthread_create.c:333)
==12128==    by 0x41BD0AD: clone (clone.S:114)
==12128== 
==12128== Conditional jump or move depends on uninitialised value(s)
==12128==    at 0x41187A4: vfprintf (vfprintf.c:1631)
==12128==    by 0x413C3DE: vsnprintf (vsnprintf.c:114)
==12128==    by 0x407902A: _string_append_with_format_list (in /usr/lib/libcommons.so)
==12128==    by 0x40785E0: string_from_vformat (in /usr/lib/libcommons.so)
==12128==    by 0x407830C: _log_write_in_level (in /usr/lib/libcommons.so)
==12128==    by 0x40780E3: log_trace (in /usr/lib/libcommons.so)
==12128==    by 0x804980E: procesar_conexion_memoria_kernel (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x405E294: start_thread (pthread_create.c:333)
==12128==    by 0x41BD0AD: clone (clone.S:114)
==12128== 
==12128== Conditional jump or move depends on uninitialised value(s)
==12128==    at 0x4118CBD: vfprintf (vfprintf.c:1631)
==12128==    by 0x413C3DE: vsnprintf (vsnprintf.c:114)
==12128==    by 0x407902A: _string_append_with_format_list (in /usr/lib/libcommons.so)
==12128==    by 0x40785E0: string_from_vformat (in /usr/lib/libcommons.so)
==12128==    by 0x407830C: _log_write_in_level (in /usr/lib/libcommons.so)
==12128==    by 0x40780E3: log_trace (in /usr/lib/libcommons.so)
==12128==    by 0x804980E: procesar_conexion_memoria_kernel (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x405E294: start_thread (pthread_create.c:333)
==12128==    by 0x41BD0AD: clone (clone.S:114)
==12128== 
==12128== Conditional jump or move depends on uninitialised value(s)
==12128==    at 0x4118B04: vfprintf (vfprintf.c:1631)
==12128==    by 0x413C3DE: vsnprintf (vsnprintf.c:114)
==12128==    by 0x407902A: _string_append_with_format_list (in /usr/lib/libcommons.so)
==12128==    by 0x40785E0: string_from_vformat (in /usr/lib/libcommons.so)
==12128==    by 0x407830C: _log_write_in_level (in /usr/lib/libcommons.so)
==12128==    by 0x40780E3: log_trace (in /usr/lib/libcommons.so)
==12128==    by 0x804980E: procesar_conexion_memoria_kernel (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x405E294: start_thread (pthread_create.c:333)
==12128==    by 0x41BD0AD: clone (clone.S:114)
==12128== 
==12128== Conditional jump or move depends on uninitialised value(s)
==12128==    at 0x4118B4D: vfprintf (vfprintf.c:1631)
==12128==    by 0x413C3DE: vsnprintf (vsnprintf.c:114)
==12128==    by 0x407902A: _string_append_with_format_list (in /usr/lib/libcommons.so)
==12128==    by 0x40785E0: string_from_vformat (in /usr/lib/libcommons.so)
==12128==    by 0x407830C: _log_write_in_level (in /usr/lib/libcommons.so)
==12128==    by 0x40780E3: log_trace (in /usr/lib/libcommons.so)
==12128==    by 0x804980E: procesar_conexion_memoria_kernel (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x405E294: start_thread (pthread_create.c:333)
==12128==    by 0x41BD0AD: clone (clone.S:114)
==12128== 
[TRACE] 21:25:44:311 memoria/(12128:12142): la condicion antes del recv es: 67473328
[INFO] 21:25:46:481 memoria/(12128:12128): Cliente conectado (a MEMORIA)

[DEBUG] 21:25:46:483 memoria/(12128:12152): el cliente sock es: 7
[TRACE] 21:25:46:484 memoria/(12128:12152): la condicion antes del recv es: 0
[TRACE] 21:25:50:261 memoria/(12128:12152): la condicion antes del recv es: 0
[DEBUG] 21:25:50:267 memoria/(12128:12152): El tam del proceso recbido por kernel es: 2048
[DEBUG] 21:25:50:300 memoria/(12128:12152): El float es: 8.000000
[DEBUG] 21:25:50:302 memoria/(12128:12152): El size de la lista de paginas del proceso es: 8
[DEBUG] 21:25:50:306 memoria/(12128:12152): El size de la lista de tablas de 2do nivel es 2
[DEBUG] 21:25:50:309 memoria/(12128:12152): El size de la tabla de primer nivel es: 2
[TRACE] 21:25:50:312 memoria/(12128:12152): envie el inice a kernel 0
==12128== Thread 3:
==12128== Invalid write of size 1
==12128==    at 0x402F076: strcat (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==12128==    by 0x804CE09: pasar_a_char (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x8049997: procesar_conexion_memoria_kernel (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x405E294: start_thread (pthread_create.c:333)
==12128==    by 0x41BD0AD: clone (clone.S:114)
==12128==  Address 0x4298eb2 is 0 bytes after a block of size 2 alloc'd
==12128==    at 0x402E0B8: calloc (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==12128==    by 0x804CDB8: itoa (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x804CDF5: pasar_a_char (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x8049997: procesar_conexion_memoria_kernel (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x405E294: start_thread (pthread_create.c:333)
==12128==    by 0x41BD0AD: clone (clone.S:114)
==12128== 
==12128== Invalid write of size 1
==12128==    at 0x402F085: strcat (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==12128==    by 0x804CE09: pasar_a_char (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x8049997: procesar_conexion_memoria_kernel (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x405E294: start_thread (pthread_create.c:333)
==12128==    by 0x41BD0AD: clone (clone.S:114)
==12128==  Address 0x4298eb6 is 4 bytes after a block of size 2 alloc'd
==12128==    at 0x402E0B8: calloc (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==12128==    by 0x804CDB8: itoa (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x804CDF5: pasar_a_char (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x8049997: procesar_conexion_memoria_kernel (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x405E294: start_thread (pthread_create.c:333)
==12128==    by 0x41BD0AD: clone (clone.S:114)
==12128== 
==12128== Invalid read of size 1
==12128==    at 0x402F383: strlen (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==12128==    by 0x40784DD: string_append (in /usr/lib/libcommons.so)
==12128==    by 0x804CC93: crear_archivo (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x80499A8: procesar_conexion_memoria_kernel (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x405E294: start_thread (pthread_create.c:333)
==12128==    by 0x41BD0AD: clone (clone.S:114)
==12128==  Address 0x4298eb2 is 0 bytes after a block of size 2 alloc'd
==12128==    at 0x402E0B8: calloc (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==12128==    by 0x804CDB8: itoa (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x804CDF5: pasar_a_char (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x8049997: procesar_conexion_memoria_kernel (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x405E294: start_thread (pthread_create.c:333)
==12128==    by 0x41BD0AD: clone (clone.S:114)
==12128== 
==12128== Invalid read of size 1
==12128==    at 0x402F079: strcat (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==12128==    by 0x407850F: string_append (in /usr/lib/libcommons.so)
==12128==    by 0x804CC93: crear_archivo (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x80499A8: procesar_conexion_memoria_kernel (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x405E294: start_thread (pthread_create.c:333)
==12128==    by 0x41BD0AD: clone (clone.S:114)
==12128==  Address 0x4298eb2 is 0 bytes after a block of size 2 alloc'd
==12128==    at 0x402E0B8: calloc (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==12128==    by 0x804CDB8: itoa (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x804CDF5: pasar_a_char (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x8049997: procesar_conexion_memoria_kernel (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x405E294: start_thread (pthread_create.c:333)
==12128==    by 0x41BD0AD: clone (clone.S:114)
==12128== 
created directory swap successfully! 
==12128== Invalid read of size 1
==12128==    at 0x402F383: strlen (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==12128==    by 0x40784DD: string_append (in /usr/lib/libcommons.so)
==12128==    by 0x804CBEC: verificar_archivo (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x804CCF0: crear_archivo (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x80499A8: procesar_conexion_memoria_kernel (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x405E294: start_thread (pthread_create.c:333)
==12128==    by 0x41BD0AD: clone (clone.S:114)
==12128==  Address 0x4298eb2 is 0 bytes after a block of size 2 alloc'd
==12128==    at 0x402E0B8: calloc (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==12128==    by 0x804CDB8: itoa (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x804CDF5: pasar_a_char (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x8049997: procesar_conexion_memoria_kernel (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x405E294: start_thread (pthread_create.c:333)
==12128==    by 0x41BD0AD: clone (clone.S:114)
==12128== 
==12128== Invalid read of size 1
==12128==    at 0x402F079: strcat (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==12128==    by 0x407850F: string_append (in /usr/lib/libcommons.so)
==12128==    by 0x804CBEC: verificar_archivo (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x804CCF0: crear_archivo (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x80499A8: procesar_conexion_memoria_kernel (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x405E294: start_thread (pthread_create.c:333)
==12128==    by 0x41BD0AD: clone (clone.S:114)
==12128==  Address 0x4298eb2 is 0 bytes after a block of size 2 alloc'd
==12128==    at 0x402E0B8: calloc (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==12128==    by 0x804CDB8: itoa (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x804CDF5: pasar_a_char (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x8049997: procesar_conexion_memoria_kernel (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x405E294: start_thread (pthread_create.c:333)
==12128==    by 0x41BD0AD: clone (clone.S:114)
==12128== 
==12128== Syscall param open(filename) points to unaddressable byte(s)
==12128==    at 0x41AB73F: ??? (syscall-template.S:84)
==12128==    by 0x413FACF: _IO_file_open (fileops.c:221)
==12128==    by 0x413FC50: _IO_file_fopen@@GLIBC_2.1 (fileops.c:328)
==12128==    by 0x41343B0: __fopen_internal (iofopen.c:86)
==12128==    by 0x413441D: fopen@@GLIBC_2.1 (iofopen.c:97)
==12128==    by 0x804CE93: poner_archivo_con_ceros (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x80499BA: procesar_conexion_memoria_kernel (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x405E294: start_thread (pthread_create.c:333)
==12128==    by 0x41BD0AD: clone (clone.S:114)
==12128==  Address 0x4298eb2 is 0 bytes after a block of size 2 alloc'd
==12128==    at 0x402E0B8: calloc (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==12128==    by 0x804CDB8: itoa (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x804CDF5: pasar_a_char (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x8049997: procesar_conexion_memoria_kernel (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x405E294: start_thread (pthread_create.c:333)
==12128==    by 0x41BD0AD: clone (clone.S:114)
==12128== 
==12128== Invalid read of size 4
==12128==    at 0x413B947: fseek (fseek.c:35)
==12128==    by 0x804CEB8: poner_archivo_con_ceros (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x80499BA: procesar_conexion_memoria_kernel (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x405E294: start_thread (pthread_create.c:333)
==12128==    by 0x41BD0AD: clone (clone.S:114)
==12128==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==12128== 
==12128== 
==12128== Process terminating with default action of signal 11 (SIGSEGV)
==12128==  Access not within mapped region at address 0x0
==12128==    at 0x413B947: fseek (fseek.c:35)
==12128==    by 0x804CEB8: poner_archivo_con_ceros (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x80499BA: procesar_conexion_memoria_kernel (in /home/utnso/tp-2022-1c-yaguarethreads-/memoria/memoria.out)
==12128==    by 0x405E294: start_thread (pthread_create.c:333)
==12128==    by 0x41BD0AD: clone (clone.S:114)
==12128==  If you believe this happened as a result of a stack
==12128==  overflow in your program's main thread (unlikely but
==12128==  possible), you can try to increase the size of the
==12128==  main thread stack using the --main-stacksize= flag.
==12128==  The main thread stack size used in this run was 8388608.
==12128== 
==12128== HEAP SUMMARY:
==12128==     in use at exit: 3,641 bytes in 83 blocks
==12128==   total heap usage: 426 allocs, 343 frees, 28,451 bytes allocated
==12128== 
==12128== LEAK SUMMARY:
==12128==    definitely lost: 24 bytes in 2 blocks
==12128==    indirectly lost: 0 bytes in 0 blocks
==12128==      possibly lost: 272 bytes in 2 blocks
==12128==    still reachable: 3,345 bytes in 79 blocks
==12128==         suppressed: 0 bytes in 0 blocks
==12128== Rerun with --leak-check=full to see details of leaked memory
==12128== 
==12128== For counts of detected and suppressed errors, rerun with: -v
==12128== Use --track-origins=yes to see where uninitialised values come from
==12128== ERROR SUMMARY: 91 errors from 20 contexts (suppressed: 0 from 0)
Killed
utnso@ubuntu-server:~/tp-2022-1c-yaguarethreads-/memoria$
