### ISSUE TITLE
Duda sobre algoritmos de reemplazo, tablas de páginas y que hacer SWAP

### ISSUE THREAD

**Issue by pmdea** [sisoputnfrba/foro#2746]
Hola, buenos días! Haciendo pruebas vi que utilicé varias estructuras auxiliares para facilitar la implementación de los algoritmos y me surgieron dudas.

Pregunta 1: Cuando hay page fault y necesito reemplazar una página en memoria, dejé en una lista de queue, con id de proceso para poder identificarlas, las páginas que fui agregando en orden que se me fue pidiendo. La estructura queue entiendo que sería la ideal ya que la mantengo como FIFO por obligación, y me ahorro ordenarla.
¿Es esto correcto? Vi en otro issues #2738 y #2724 que recomendaban poner en las páginas un campo más para el instante en el que se le reservó un marco y luego en momento de un reemplazo, se haría una lista de páginas del proceso ordenada por ese campo y se ejecutaría el algoritmo.

Pregunta 2: Para tener en cuenta el número de marcos asignados a un proceso, cree un método que dada su tabla de nivel 1, recorre todas sus páginas contando los marcos asignados y responde si se le puede asignar uno más. Entiendo que sería poco eficiente, ya que teniendo en cuenta que hay n² páginas, perdería tiempo en recorrer la tabla buscando.
Utilizar una tabla de marcos para ver si está asignado o no y a qué tabla, me parece una solución parecida en eficiencia.
Por lo tanto, ¿se podría guardar en la tabla de primer nivel un contador con la cantidad de marcos asignados?  Y si no es así, ¿mi solución anterior sería válida? No vi en los otros issue si tuvieron ese problema.

Pregunta 3: Al escribir en SWAP, ¿qué es lo que escribimos de la página? O sea, armo el archivo con el tamaño correspondiente y cuando necesito swapear, ¿que es lo que se escribe al archivo? ¿Los frames correspondientes asignados por página que estarían representados por el void* de la memoria principal?
En el enunciado aclara: 
> Cabe aclarar que todos los valores a leer/escribir en memoria serán numéricos enteros no signados de 4 bytes, considerar el uso de uint32_t.

Pero en el módulo de memoria, por configuración se indica el tamaño de la página y por ende el del marco, ¿entonces qué se estaría escribiendo si en vez de 4bytes de tamaño de marco fueran 64 bytes como en el ejemplo? Probablemente esto sea una confusión mía conceptual

**Comment by FacuAntelo** [comment]
Buenas tardes, sumando una duda relacionada con el issue. En el algoritmo de reemplazo clock, cuando se produce un page-fault, siempre debemos sobreescribir la pagina en SWAP? o podemos controlar el bit de modificado para ver si es necesario sobreescribirla?. Es decir, no lo tendriamos en cuenta para ver que pagina reemplazar como se hace en el Clock-M, pero si para sobreescribir la pagina en SWAP.

**Comment by iago64** [comment]
Buenas! Cómo va?

Respuesta 1: La estructura de queue les puede servir, el tema es que no te olvides que tenes 2 operaciones (push y pop) con lo cual para recorrerla tendrías que ir sacando de a 1 y después volviéndolos a insertar en otra queue auxiliar, pero mas allá de ese mínimo detalle, usar una queue o una lista es mas o menos lo mismo, lo que importa es que recorran los frames en el orden que fueron asignados.

Respuesta 2: No nos vamos a poner a ver si el algoritmo que implementaron es el optimo o te permite freír una milanesa arriba de la CPU, la idea del TP es que resuelvan la necesidad de alguna forma y que después nos cuenten en el coloquio justamente que "problemas" (énfasis en las comillas porque para el TP no es un problema) tiene su algoritmo y como podrían optimizarlo (obviamente en este punto sin llevarlo a código si no mas bien conceptual).

Respuesta 3: En SWAP literalmente guardan la página tal cual la tienen guardada en memoria, piensen que SWAP no es mas que una imagen del proceso en un almacenamiento secundario y el SO no tiene ni la mas mínima idea de que cuernos graba el proceso, solo se encarga de mover los "cachitos" de memoria (entiéndase cachitos por paginas y/o segmentos en caso de otros esquemas de memoria).
Lo que vas a terminar escribiendo en memoria son datos de 4 bytes, que van a estar en una dirección específica que te va a indicar la CPU (después de traducir la dirección lógica), pero en una página vas a tener varios de esos datos.


Bonus @FacuAntelo la solución que plantean es justamente como se ve que funcionan los algoritmos vistos en la teoría 😉 

Saludos.-

**Comment by pmdea** [comment]
Gracias! @iago64 . Entonces para confirmar.
1: Entonces me preocupo más por el recorrer que la estructura en sí que use, lista auxiliar, queue, o lo que sea serán válidas.
2: Perfecto! Lo dejo comentado en el código y lo hablaremos en la defensa.
3: Entonces, si entendí bien, desde el punto de vista de escribir y leer de swap, va a ser "agnóstico" el módulo de memoria respecto a qué escribe mientras se escriba y lea la página.

Por el momento se me aclararon las dudas. Dejo el issue abierto, si te parece, hasta que @FacuAntelo responda si le falta algo.


Muchas gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Si, totalmente, la estructura vean que les resulte simple a uds.
2.- 👌 
3.- Exacto, vos lees y escribís páginas en SWAP.

Saludos.-

**Comment by FacuAntelo** [comment]
Por mi parte me quedo claro, en el clock simple cuando escribimos en swap solo sobreescribimos si el bit de Mod = 1. Pueden cerrar el issue. Muchas gracias! Saludos.

**Comment by pmdea** [comment]
Cierro issue!
