### ISSUE TITLE
Pruebas con identificador "I/O" y "IO"

### ISSUE THREAD

**Issue by comejia** [sisoputnfrba/foro#2747]
Buenas,

Estaba corriendo unas pruebas y me di cuenta que hay scripts con "I/O" (ej BASE_1) y "IO" (ej MEMORIA_1). En mi caso rompio porque no se considero "IO", se que es solo agregar una validacion mas pero lo comento por las dudas.

Saludos, Cesar

**Comment by iago64** [comment]
Buenas! 

Mil gracias por el aviso, se nos recontra paso al subir las pruebas, ya esta corregido 😄 

Abrazo!
