### ISSUE TITLE
Tablas de segundo nivel y varios procesos

### ISSUE THREAD

**Issue by Naicon67** [sisoputnfrba/foro#2748]
Hola, estoy con la duda si en una tabla de segundo nivel puede haber paginas de dos procesos distintos. Lo que me hace pensar eso es que puede haber una diferencia entre ENTRADAS_POR_TABLA y MARCOS_POR_PROCESO, es decir, si una tabla de segundo nivel tiene 4 entradas pero marcos por proceso es 3, estaría desperdiciando una entrada de cada tabla de segundo nivel, a menos que permita que haya paginas de varios procesos en una misma tabla. Gracias!

**Comment by pmdea** [comment]
Me sumo a tu duda ya que no me quedó claro del todo, pero hasta donde entendí, cuando vos arrancás el proceso por consola, le mandás además del archivo de pseudocódigo, el tamaño del proceso

> La Consola deberá aceptar 2 parámetros para ser ejecutado: el path del archivo de pseudocódigo y el tamaño que tendrá el espacio de direcciones del proceso al cargarse en Memoria,

Por lo que entendí, y creo que aparece en algun issue la respuesta aunque no lo tengo a mano, vos tendrías que crear entradas de páginas correspondientes al tamaño del proceso.
Esperaría que conteste alguien que sepa más que yo igual.

**Comment by Naicon67** [comment]
Sisi tengo claro que tengo que definir cuantas entradas de tabla de segundo nivel va a necesitar el proceso dependiendo el tamaño, lo que no entiendo es si en una misma tabla de segundo nivel puedo tener entradas de procesos distintos

**Comment by iago64** [comment]
Buenas! Cómo va?

Las tablas de páginas son **por proceso**, con lo cual, no podrías tener una tabla de segundo nivel compartida entre 2 procesos.

Saludos.-

**Comment by Naicon67** [comment]
Ok, entonces qué significa una posible diferencia en entradas por tabla y marcos por proceso? No me queda claro, ya que entradas por tabla explicitamente dice la cantidad de entradas para ambas tablas, pero si marcos por proceso es menor a eso, la de segundo nivel siempre va a tener menos

**Comment by Naicon67** [comment]
Perfecto!
