### ISSUE TITLE
Nuevo proceso en SWAP

### ISSUE THREAD

**Issue by DamianArielLerner** [sisoputnfrba/foro#2749]
Buenas! Una pregunta, para asignar fijamente una cantidad de bytes en un archivo cuando me llega un proceso nuevo, debo hacer lo siguiente?
`fwrite(NULL, NULL, PCB->TamProceso, fp);`
O tendría que hacer esto?
`fwrite(0, sizeof(uint32_t), PCB->TamProceso, fp);`
Es decir, mi idea es que quede todo "vacío". Gracias!

**Comment by DamianArielLerner** [comment]
Mí pregunta es si alguna de las 2 opciones me permite darle a un archivo un tamaño fijo sin meter todavía contenido en el. Saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

Y si lo prueban?

Perdón si se lee medio chocante la respuesta, pero es algo que pueden probar y sacarse la duda ustedes mismos y eso los hace mas independientes  y al final del día un programador independiente es un programador que progresa mas rápido. 

Saludos.-

**Comment by RaniAgus** [comment]
Para sumar a lo que dijo Dami, además de probarlo (que es **clave** para sacarse todas las dudas rápido sin tener que esperar la respuesta de un ayudante), repito el consejo de revisar la documentación oficial porque en ambos casos los parámetros no concuerdan con lo que pide la función. Para acceder pueden ir al link que les pasé o ejecutar `man fwrite` en una consola.

Saludos

**Comment by iago64** [comment]
@DamianArielLerner Cómo va? Te quedó alguna duda? Pudiste avanzar con el creado de los archivos de SWAP?

**Comment by iago64** [comment]
Cerramos el issue por inactividad.
