### ISSUE TITLE
MEMORIA : Estructura de tablas de páginas de 1er y 2do nivel

### ISSUE THREAD

**Issue by alexisdona** [sisoputnfrba/foro#2751]
Buenas!
Me leí los issues [#2701](https://github.com/sisoputnfrba/foro/issues/2701) [#2711](https://github.com/sisoputnfrba/foro/issues/2711) y [#2596](https://github.com/sisoputnfrba/foro/issues/2596) y no me termina de quedar claro cómo es que se tiene que armar la estructura de las tablas de páginas. Abajo pego una imagen ejemplo de cómo lo pensamos a ver si así resuelve.

Un proceso solo puede tener asociado un índice de la tabla de primer nivel que es una lista de enteros solamente, donde el entero es el índice a la tabla de 2do nivel que tiene como máximo ENTRADAS_POR_TABLA = MARCOS_POR_PROCESO de registros. Por eso no entiendo lo que plateó el compañero en el issue #2701 donde dice PROC 1 y la tabla de primer nivel tiene 4 registros. No hay forma de que pueda guardar eso en el PCB que solo tiene un índice a la tabla de primer nivel. Entonces en el PCB de cada proceso nos queda

Proceso 1 --> PCB --> Entrada tabla de páginas = 0
Proceso 2 --> PCB --> Entrada tabla de páginas = 1
Proceso 3 --> PCB --> Entrada tabla de páginas = 2
Proceso 4 --> PCB --> Entrada tabla de páginas = 3
 

![image](https://user-images.githubusercontent.com/22838115/177685431-9e46f4a2-e73f-4109-a2c8-8e33ebccccb4.png)

DUDAS

1. No podría tener valores de config diferentes para MARCOS_POR_PROCESO y ENTRADAS_POR_TABLA, ¿qué sentido tendría eso?, porque la cantidad de entradas de la tabla de 2do nivel son justamente para referenciar a los marcos que tiene asignado el proceso. 

2. Un proceso no podría ser nunca mayor que ENTRADAS_POR_TABLA * TAMAÑO_PAGINA, no?

3. En el enunciado dice que las traducciones lógicas se hacen así: 

_número_página = floor(dirección_lógica / tamaño_página)
entrada_tabla_1er_nivel = floor(número_página / cant_entradas_por_tabla)
entrada_tabla_2do_nivel = número_página % cant_entradas_por_tabla
desplazamiento = dirección_lógica - número_página * tamaño_página_

¿Qué pasa si dos procesos diferentes por ejemplo tienen la instrucción WRITE 5000 5, donde se supone que debería escribir un 5 en esa dirección lógica. De acuerdo a la cuenta que puse arriba el número de página me va a dar igual para ambos procesos y por ende los otros tres valores entrada_tabla_1er_nivel, entrada_tabla_2do_nivel y desplazamiento

Saludos!
Alexis

**Comment by RaniAgus** [comment]
¡Buenas! Antes de empezar con las dudas, cito el diagrama del enunciado:

![image](https://user-images.githubusercontent.com/39303639/177771867-7f33f836-3442-4fea-bc8a-ec7ce746d676.png)

En este ejemplo se puede observar que el proceso 1 tiene una tabla de páginas de 1er nivel y hasta N tablas de 2do nivel. Es decir, cada proceso **no** tiene **solo** una entrada de tabla de páginas de 1er nivel, sino que tiene **toda una tabla completa**. 

1. Como habrán visto en la teoría, la característica principal de un esquema con memoria virtual es poder direccionar más páginas que la capacidad de la memoria física, es decir que pueden haber páginas que no estén presentes en un marco (bit de presencia = 0). También pueden ver un ejemplo en https://github.com/sisoputnfrba/foro/issues/2748#issuecomment-1176325046

2. Como cada proceso tiene una tabla de 1er nivel propia, sería ENTRADAS_POR_TABLA * ENTRADAS_POR_TABLA * TAMAÑO_PAGINA

3. Ahí es donde entra en juego el `número_tabla_1er_nivel` que se encuentra en el PCB: es distinto para cada proceso, por lo que al combinarlo con la `entrada_tabla_1er_nivel` calculada siempre se obtiene un `número_tabla_2do_nivel` distinto.

Saludos

**Comment by LeandroCarbajales** [comment]
Buenas!

> Una duda que nos surgió es qué pasa si un proceso es de tamaño 512 bytes y dentro tiene una instrucción COPY 511 0...

Pueden chequear las pruebas para ver que eso no va a ocurrir :)

Saludos!
       Lean

**Comment by alexisdona** [comment]
Buenísimo! Gracias Lean! Seguimos craneando esto y cualquier cosa les avisamos.  Cierro el issue
