### ISSUE TITLE
Dudas Modulo Memoria

### ISSUE THREAD

**Issue by Gdepablo** [sisoputnfrba/foro#2755]
Buenas, estaba viendo el enunciado con mi grupo y nos surgen las siguientes dudas:

En memoria, si tengo por ejemplo un máximo de 4 entradas por tabla y un tamaño de paginas de, por ejemplo, 64 bytes, tengo:  4* 4 * 64 = 1024 bytes de tamaño maximo por proceso. Entonces, el tamaño de direcciones que se ingresa por consola no puede ser mas grande que 1024 bytes?

Otra duda, en caso de que el tamaño maximo por proceso sea 1024 bytes y se ingresa que el tamaño de direcciones del proceso es 512 bytes, tendria que crear solo la cantidad de paginas necesarias para que el tamaño total sea 512 bytes?

Por ultimo, es el MMU el encargado de fijarse que la direccion logica pedida no se pase del tamaño de direcciones asignado?

**Comment by LeandroCarbajales** [comment]
Buenas!
Estos detalles son equivalentes a como los vemos en clase, tanto a nivel teórico como en los ejercicios.

> En memoria, si tengo por ejemplo un máximo de 4 entradas por tabla y un tamaño de paginas de, por ejemplo, 64 bytes, tengo: 4* 4 * 64 = 1024 bytes de tamaño maximo por proceso. Entonces, el tamaño de direcciones que se ingresa por consola no puede ser mas grande que 1024 bytes?

Claro, sería equivalente a tener direcciones lógicas de 10bits (2 TP1, 2 TP2, 6 offset), por lo que nunca podrías acceder a direcciones superiores a 1023.

> Otra duda, en caso de que el tamaño maximo por proceso sea 1024 bytes y se ingresa que el tamaño de direcciones del proceso es 512 bytes, tendria que crear solo la cantidad de paginas necesarias para que el tamaño total sea 512 bytes?
Lo que te va a cambiar en todo caso es cuántas tablas de 2do nivel necesita el proceso (igual que como vemos en clase).

> Por ultimo, es el MMU el encargado de fijarse que la direccion logica pedida no se pase del tamaño de direcciones asignado?
En todo caso eso se chequearía al haber un page fault, en el TP no va a ocurrir.

Saludos!
        Lean

**Comment by LeandroCarbajales** [comment]
Buenas!
Así es :)
Sin embargo, en las pruebas nos tomamos la consideración de que eso no ocurra (las pueden corroborar)

Saludos!
       Lean

**Comment by tomasbernat** [comment]
Aunque no ocurra en los test debemos implementar que se cargue una pagina en memoria en caso de que ocurra?

**Comment by LeandroCarbajales** [comment]
Las pautas de aprobación del trabajo son que pase la pruebas correctamente :)
Si quieren implementarlo son bienvenidos a hacerlo, pero mi recomendación sería primero asegurarme que pasan las pruebas.

Saludos!
      Lean

**Comment by tomasbernat** [comment]
Buenisimo, gracias!

**Comment by Gdepablo** [comment]
LA MULA cierra el issue.
