### ISSUE TITLE
Duda teorica con la desuspension memoria/swap

### ISSUE THREAD

**Issue by jschuhmann47** [sisoputnfrba/foro#2756]
Buenas, estaba teniendo una duda con el tema de la desuspensión de los procesos, y quería preguntar para saber bien que hay que hacer cuando sucede eso.

Tengo entendido que al suspender un proceso, se swapean las paginas que estaban presentes en memoria y deja los marcos que tenía ocupados como libres. Al ser a demanda, cuando se desuspende un proceso no se deben cargar las paginas que estaban en memoria en ese momento, sino que se van a cargar a medida que se vayan necesitando.

Mi duda es, cuando vuelve de la suspension, cómo se si la pagina que solicita el proceso estaba en el archivo swap (como para levantarla del mismo y cargarla a memoria), en vez de simplemente asignarle el marco y listo? O no hay que recuperar el contenido de los archivos? 

Gracias de antemano

**Comment by iago64** [comment]
Buenas! Cómo va?

Siento que te enroscaste en el problema mas de la cuenta 😄 
La idea es que vos cuando sacas un proceso del estado suspendido no haces nada del lado de memoria (porque no podes adivinar si la/s página/s que tenias en memoria las estaba usando todas, solo una o ninguna), por lo cual, lo que haces es simplemente seguir con la ejecución normal y como es de esperarse, al tener las páginas en swap, lo que te va a pasar es que vas a tener una mayor cantidad de page faults por un tiempo.

Saludos.-

**Comment by jschuhmann47** [comment]
Entonces lo que guardo en el archivo swap no lo tengo que leer? Solamente se escribe? Mi duda venia por un caso asi:
Por ejemplo asigno de un proceso en la pagina 0 el marco 0. Ahí escribo "Hola". Se suspende entonces guardo la pagina en swap (guardo el "Hola"). Ahora cuando se desuspende, tengo que leer de swap para volver a tener el "Hola" en memoria y poder escribir por ej "Hola mundo", o no se carga esta informacion de vuelta en memoria? Y me quedo con el marco "limpio" sin ningun dato digamos?

**Comment by iago64** [comment]
Buenas! Cómo va?

La información que guardas en swap la vas a leer si y solo si tenes una referencia a esa página.
Por ejemplo, si vos guardas tu pagina con el "Hola" y después tenes que leerlo o escribir al lado el " mundo", ahí recién es cuando volves a traer tu página a memoria, si no, queda en swap durmiendo feliz y contenta.

Saludos.-

**Comment by jschuhmann47** [comment]
Perfecto, muchas gracias! Cierro el issue
