### ISSUE TITLE
Limpieza de Memoria

### ISSUE THREAD

**Issue by 23737k** [sisoputnfrba/foro#2757]
Hola, mi consulta es breve ¿Tengo que limpiar la memoria al inicio? Es decir ¿qué pasa si la primera instrucción de un proceso es READ, y aún no ha escrito nada en ese marco?

Gracias.

**Comment by LeandroCarbajales** [comment]
Buenas!
Va a depender de cómo inicializaron el archivo de swap del proceso, si está solamente truncado a su tamaño probablemente sean puros '\0', otra opción es que lo hayan llenado de 0s.
En cualquier caso, si chequean las pruebas, van a ver que siempre escribimos las direcciones antes de leerlas para que el resultado sea predecible :)

Saludos!
       Lean

**Comment by 23737k** [comment]
¡Genial, gracias!

**Comment by LeandroCarbajales** [comment]
Asumo que está resuelta la duda asique cierro el issue.
Cualquier cosa lo vuelven a abrir :)
