### ISSUE TITLE
Cantidad de datos a escribir/leer en read/write/copy

### ISSUE THREAD

**Issue by r-cbl** [sisoputnfrba/foro#2758]
Hola, estamos terminando los detalles de memoria-cpu y nos surge la siguiente cuestión:

1. ¿Qué cantidad de datos envía memoria a cpu con la operación read? Nos surge la duda de si envía:
a. siempre envía 4 bytes (sin importar si leo un pedazo de otro marco o basura)
b. lo que hay desde el desplazamiento que tiene la direccion hasta que termina el marco
c. lo que hay desde el desplazamiento que tiene la direccion hasta que termina el marco o lea 4 bytes (lo que suceda primero)

2. Misma pregunta para el write ¿qué pasa si me excedo del marco? ¿cpu envía siempre 4 bytes a escribir o pueden ser menos?
3.  En el copy ¿qué tamaño de datos copio? ¿4 bytes? ¿1 byte?

Gracias 🤗🤗

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Siempre van a leer 4 bytes porque asi lo "simplificamos" en el enunciado en la página 17:

> Cabe aclarar que **todos** los valores a leer/escribir en memoria serán numéricos enteros no signados de **4 bytes**, considerar el uso de _uint32_t_.

2.- Siempre se mandan **4 bytes**, en el caso del WRITE como tienen texto que levantan del archivo tienen que convertir ese número de texto a un entero. Y para que no se alarmen, _no se van a pasar del marco_, lo pueden validar con las pruebas publicadas.

3.- Idem 1 y 2, siempre **4 bytes**

Saludos.-

**Comment by r-cbl** [comment]
Muchas gracias, nos confundió el issue 2591.
Lo cierro, un abrazo
