### ISSUE TITLE
Actualización de la TLB

### ISSUE THREAD

**Issue by maxicaleca** [sisoputnfrba/foro#2759]
Buenas, cómo andan ? 

Nos surgió esta duda para poder mantener la TLB consistente habiendo pasado por esta [issue ](https://github.com/sisoputnfrba/foro/issues/2709)

Supongamos la situación en la que tenemos la TLB con el registro  **marco** 1 | **página** 2 , pero justo en una próxima instrucción me piden  la página 3 que no está en memoria, entonces aplicando un algoritmo de sustitución de páginas (porque todos los marcos los tengo ocupados) me dá que es necesario liberar el marco 1.

En este caso, la entrada de la TLB no me va a servir más porque realmente el marco 1 va a estar asignado a la página 3, pero la duda es, dependiendo la implementación, _no me serviría con solo actualizar la página en la entrada del marco 1, no ? Porque si estoy usando FIFO por ej, podría estar alterando el próximo resultado de aplicar ese algoritmo._ Puntualizándolo en una estructura, si mi tlb está representada por un array, debería hacer el reordenamiento lógico para evitar esa alteración, no?

Saludos

**Comment by RaniAgus** [comment]
¡Buenas! Así es, siempre al momento en que agreguen una nueva entrada a la TLB el orden es el mismo sin importar que hayan reemplazado otra entrada o no.

Dependiendo de cómo lo hayan implementado, esto puede ser más sencillo o no, por ejemplo:
- Si lo implementaron como array hay que, como mencionabas, reordenar las entradas y agregar la nueva al final:

![image](https://user-images.githubusercontent.com/39303639/178282678-d80b8e91-21c2-483b-80e2-2213f0f407f4.png)

- Si lo implementaron como `t_list` ([incluso se puede con una `t_queue`](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/collections/queue.h#L22-L24)) hay que remover la entrada inválida y agregar la nueva al final como cualquier otra.

- Si hay una columna "instante de carga" alcanza con actualizar la entrada con la nueva página y su instante de carga.

Saludos

**Comment by maxicaleca** [comment]
Genial, muchas gracias. Cierro la issue.
