### ISSUE TITLE
Archivos de configuracion de la pruebas

### ISSUE THREAD

**Issue by lalvarez-utn-frba** [sisoputnfrba/foro#2761]
Hola!
Tenemos una duda respecto a los archivos de configuración. 
En nuestro equipo planteamos tener un archivo por cada prueba y módulo ya cargado en el repo (ej: para la prueba base de kernel. tendríamos un 3 archivos de config para memoria/cpu/kernel y los respectivos archivos con instrucciones para consola), entonces al momento de correr una prueba, simplemente levantamos cada módulo con su propio archivo de config (que tiene lo mismo que pide la prueba).
Queríamos saber si esto está bien o nos van a pasar los ayudantes los archivos de config para usarlos.
Muchas gracias de antemano!

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va?
Está perfecto, de hecho, es lo que recomendamos en la guía de deploy 😉: https://docs.utnso.com.ar/guias/herramientas/deploy.html#contar-con-los-config-de-las-pruebas

Saludos

**Comment by lalvarez-utn-frba** [comment]
Excelente, muchas gracias, cierro el issue! buena semana!
