### ISSUE TITLE
Prueba de Estabilidad Integral - Resultados esperados

### ISSUE THREAD

**Issue by aleasquini** [sisoputnfrba/foro#2762]
Hola !

En el apartado de Prueba de Estabilidad Integral no figura en que orden de ejecución deben finalizar los procesos. En caso de poseerlo, podrán compartirlo para que podamos verificar el correcto funcionamiento de los planificadores? 

Gracias y saludos!
Ale

**Comment by aleasquini** [comment]
Gracias Dami!

**Comment by EspositoLucas** [comment]
Buenas . Disculpen que reabra el issue, Con el grupo surgió una duda sobre el orden de ejecución de las consolas porque por ejemplo si se tiene un cantidad de entradas de tabla de página que es 4 y el tamaño de página que es 256 . Si las pruebas tienen tamaño 2048, al dividirlo por el tamaño de pagina (para saber cuantas paginas tiene el proceso) quedarían que el proceso tiene 8 paginas y dividiendo por la cantidad de entradas , nos queda  que se necesita 2 tablas de segundo nivel, ósea que se ocupan dos entradas de la tabla de primer nivel . Al correr dos procesos a la vez se llenarían todas las tablas, como haríamos en el caso de correr 5 consolas a la vez ?  El nivel de multiprogramación en ese caso no debería ser 2 ?  o se ejecuta una prueba a la vez ?

Saludos
