### ISSUE TITLE
Problema al conectar varias PCs para las pruebas

### ISSUE THREAD

**Issue by TomasR264** [sisoputnfrba/foro#2763]
Buenas!
Hoy fuimos hasta medrano para probar que el TP se conecta bien en mas de una computadora.
Una vez que pusimos las IP que creemos que iban, levantamos memoria y despues en otra compu quisimos levantar CPU, y se conectaban pero inmediatamente se desconectaban. Ahora estamos tratando de hacer lo mismo con tres computadoras que tenemos en nuestras casas para minimo ver de conectar dos.

No sabemos si esto es un problema recurrente, pero de no ser asi y se necesita mas informacion para ayudarnos a resolverlo, por favor digannos

Desde ya, muchas gracias! 😃

**Comment by iago64** [comment]
Buenas! Cómo va?

Por lo general ese problema se da cuando ponen la IP 127.0.0.1 al momento de crear el socket, por las dudas controlen que no sea eso.

Saludos.-

**Comment by TomasR264** [comment]
@iago64 Lo que hicimos fue poner ifconfig y ver cual era la IP y pusimos esas en los configs del tp, por que con la 127.0.0.1, ni nos conectaba

**Comment by iago64** [comment]
Buenas!

La IP 127.0.0.1 solo les va a servir si están en la misma maquina, por lo que no les va a funcionar en el labo.
La pregunta venia si justamente al momento de crear el servidor estaban poniendo la IP 127.0.0.1 en la función `getaddrinfo` ya que lo que termina pasando ahi es que se bindean a esa IP solamente en lugar de a cualquier IP de la máquina que eso lo logran pasandole `null` 😄 

Por las dudas, para las pruebas asegurense de que las VMs las levantan con el adaptador en bridge, para que les "asigne" una ip el router para que se vean entre las VMs

Saludos.-

**Comment by TomasR264** [comment]
Ah buenisimo, gracias, ahora a la tarde vamos a Medrano a probar y si anda bien, cierro el issue

Saludos!

**Comment by TomasR264** [comment]
@iago64 ahi lo acabos de probar y anda perfecto.

Muchas gracias! :rocket:
