### ISSUE TITLE
Criterio de aprobacion en la prueba de estabilidad integral

### ISSUE THREAD

**Issue by facuxfdz** [sisoputnfrba/foro#2764]
Buenas noches!

Tenemos una duda respecto a la ultima prueba. Sabemos que solo se espera que finalicen pero, ese es el criterio de aprobacion? 

Me refiero a que, si los procesos terminan, pero en el medio hay problemas como que el uso de la cpu o memoria tienen sobresaltos, es considerado al momento de aprobar o no el TP?

Muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

A que llaman sobresaltos en el uso de CPU y memoria? 
La condición de la prueba dice que los procesos terminan porque es lo que tienen que hacer, ahora a los ayudantesesa prueba nos sirve para validar varias cosas, por ejemplo que no tengan esperas activas o memory leaks.

Saludos.-

**Comment by facuxfdz** [comment]
Por ejemplo que la CPU pase de ejecutar del 5% al 40% o la memoria tenga saltos de 20M o mas.

Igualmente, probando en el ubuntu server va joya a nivel del uso de la cpu y memoria, el tema esta en el lubuntu, ahi pasa mas esto de los "sobresaltos". Calculo que jugara el tema del desktop environment y todo lo relacionado a eso pero igualmente pregunto ante la duda, si el identificar algun memory leak importante llevaria a la desaprobacion del tp

**Comment by iago64** [comment]
Buenas!

Literalmente es el 4to punto del checklist de las pruebas, un memory leak o una espera activa es condición de desaprobación.

![image](https://user-images.githubusercontent.com/1622109/178400187-4ed85e3d-3414-461f-8af9-4acf1ffe7073.png)

Saludos.-

**Comment by facuxfdz** [comment]
Entonces tienen que cumplirse todos los ítems en simultáneo para aprobar? Si están todos bien menos uno ya estaría desaprobado el TP o hay algún otro criterio al momento de evaluar?

**Comment by iago64** [comment]
Buenas! Cómo va?

El checklist son todos los puntos que debe cumplir el TP, ven alguno que no estén entendiendo el objetivo? Justamente si cumplen con las pruebas el checklist esta en un 90% bien, solo estos primeros puntos son los que capaz se prestan a confusión, pero son las cosas que les decimos desde el primer día, por ejemplo que el TP tiene que correr en varias maquinas, que no tengan esperas activas ni memory leaks, etc, etc.

Nuevamente, si hay algún punto que les haga ruido avisen y lo vemos en detalle. 

Saludos.-

**Comment by fcafici** [comment]
Hola, me sumo a la consulta. No tener memory leaks implica que al correr con Valgrind debería decirnos "Definately lost: 0 bytes"?

**Comment by facuxfdz** [comment]
Claro perfecto.

Solo nos queda una duda con el de los memory leak. Cómo te comentaba antes al correr las pruebas en el ubuntu server andan genial, el tema es con el Lubuntu, cuando un compañero lo prueba tiene saltos en el uso de la memoria. 

Esto puede darse por los consumos de la interfaz gráfica? O deberían correr igual en ambos entornos?

Graciass

**Comment by iago64** [comment]
> Hola, me sumo a la consulta. No tener memory leaks implica que al correr con Valgrind debería decirnos "Definately lost: 0 bytes"?

El 0 en valgrind es el ideal, pero no lo vamos a medir así (porque sería engorroso y además valgrind puede enmascarar otros problemas), la validación de los memory leaks se hace corriendo las pruebas con un htop siempre visible y ahí se ve tanto el consumo de CPU como de memoria.

> Claro perfecto.
> 
> Solo nos queda una duda con el de los memory leak. Cómo te comentaba antes al correr las pruebas en el ubuntu server andan genial, el tema es con el Lubuntu, cuando un compañero lo prueba tiene saltos en el uso de la memoria.
> 
> Esto puede darse por los consumos de la interfaz gráfica? O deberían correr igual en ambos entornos?
> 
> Graciass

Es posible que la interfaz gráfica interfiera, mas en VMs que no están precisamente sobradas de recursos, por eso las pruebas finales les recomendamos que las corran en las VM server (como va a ser la entrega final) y ahí van tener muchisimas menos cosas que les puedan hacer subir el consumo de CPU o Memoria.

Para ambas preguntas, lo importante es ver que el consumo de memoria no crezca indefinidamente, es decir, si sube en un momento por ejemplo de 130 a 150mb de consumo y después vuelve a bajar a 130, no hay problema, ya que se asume que fue que usaron memoria para algo y la liberaron, ahora si el consumo de memoria va de 130 a 140 a 150 a 160 ... y llega a 200 y nunca baja, ahí esta la prueba de que tienen un memory leak. Tengan en cuenta que el no eliminar las tablas de páginas es algo contemplado en el TP pero no debería consumir mas de 1 o 2Mb a lo largo de las pruebas ya que son estructuras relativamente ligeras

Para el caso de las esperas activas, lo que van a ver es que algún proceso va a consumir mucha CPU y en `htop` lo van a ver como una CPU (o la CPU en caso de que tengan 1 solo core asignado a la VM) con un consumo cercano al 99.9% durante largos periodos de tiempo (por no decir casi constante)

Saludos.-

**Comment by facuxfdz** [comment]
Perfecto muchas gracias todo mas claro ahora!

Cierro el issue. Saludos!
