### ISSUE TITLE
Prueba integral 

### ISSUE THREAD

**Issue by Lara-Melany-Pallenzona** [sisoputnfrba/foro#2765]
Buen día
Tenemos una duda con la prueba integral. Es normal que dicha prueba dure mucho tiempo? Por ejemplo unos 8 minutos?
Muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

La prueba integral dura bastante mas que las específicas de los módulos, para ser honestos no hicimos el cálculo exacto del tiempo que debería durar pero teníamos un estimado que rondaba entre 5 y 10 minutos.

Cualquier cosa si están corriendo todas las pruebas y no quieren esperar mucho pueden bajar los retardos de NO_OP, de los accesos a memoria y SWAP así no les demora mucho, el objetivo de esa prueba es que todo ejecute sin errores, después si es un poco mas rápido o un poco mas lento es lo de menos. 

Saludos.-

**Comment by Lara-Melany-Pallenzona** [comment]
Genial, muchas gracias.
