### ISSUE TITLE
Duda logs necesarios/obligatorios para la entrega

### ISSUE THREAD

**Issue by nicolasviegas** [sisoputnfrba/foro#2766]
Buenas tardes, con mi grupo estamos realizando los últimos detalles para la entrega, nos gustaría saber que sería conveniente/necesario loggear para que se entienda todo de la mejor manera.

Otra duda es si el log tiene que ser lvl info o puede ser de mayor lvl para que se entienda mejor aún.

¡Desde ya muchas gracias! 🚀

**Comment by iago64** [comment]
Buenas! Cómo va?

No tenemos una "definición completa" de que logs son obligatorios y que logs no lo son, por eso les pedimos que tengan el criterio suficiente como para poner los logs que sirvan para entender que eventos están sucediendo en sus módulos.
Por ejemplo cosas que son sumamente necesarias saber: cambios de estado de los procesos, reemplazos de páginas, reemplazos en la TLB, interrupciones en la CPU, etc.

Respecto al log level, no importa, mientras que terminen en un archivo de log que podamos consultar 😄 

Saludos.-

**Comment by nicolasviegas** [comment]
Buenísimo, muchas gracias!
