### ISSUE TITLE
Modulo Swap - Escritura/Lectura

### ISSUE THREAD

**Issue by NahuelFarias** [sisoputnfrba/foro#2768]
La consulta va orientada a si el planteo de swap que estamos haciendo va por el buen camino o podria llevarnos a tener inconvenientes:
- Entendemos que desde swap se leen o se escriben paginas enteras, cuyo tamaño es dado por config.
- Las lecturas/escrituras se realizan de a una, es decir que no vamos a tener lecturas/escrituras en paralelo.

### 📔 Citas del enunciado/videos
> El SWAP, al imitar los accesos a disco, deberá implementarse como si fuera un único hilo de ejecución. Esto significa que no se podrán tener 2 o más lecturas/escrituras en paralelo.

### 💭 Soluciones posibles
Partiendo de los puntos planteados en el inicio y la parte del enunciado, creemos que una solución viable seria realizar las lecturas/escrituras del archivo swap de manera contigua, es decir leer o escribir siempre una serie de datos que serian del tamaño de la pagina.
Y para saber desde que parte del archivo swap comenzar a hacer la lectura/escritura realizaríamos una cuenta para saber el numero de pagina al que queremos ingresar, y luego de hacer `numPag * tamPag`, tendríamos la posición exacta dentro del archivo desde adonde leer/escribir.

Esta solución planteada seria viable o puede llegar a desembocarnos en algún problema que no estemos considerando?

**Comment by LeandroCarbajales** [comment]
Buenas!
Siempre la idea es leer/escribir SWAP de a páginas por lo que la implementación que plantean es correcta :)

Saludos!
     Lean

**Comment by NahuelFarias** [comment]
Perfecto!

Cierro el issue 👋
