### ISSUE TITLE
Pruebas de Sistema Completo / Memory leaks

### ISSUE THREAD

**Issue by lalvarez-utn-frba** [sisoputnfrba/foro#2769]
### 📔 Citas del documento de pruebas
![image](https://user-images.githubusercontent.com/89167525/178826736-3a55a4fc-6ab2-47a8-8d07-04c578de9739.png)

### 👍 Comportamiento esperado
El sistema no registra casos de Espera Activa ni Memory Leaks.

### Nuestra duda
Queremos saber cómo se va a evaluar que nuestro sistema no tenga memory leaks. Lo único que se nos ocurre por el momento es escuchar un sigint y liberar todos los recursos que estamos usando (malloc).
Hay algún margen de error respecto a los bytes que estamos dejando sin liberar? 
Por ahí es probable que no logremos tener 0 bytes al finalizar.

**Comment by LeandroCarbajales** [comment]
Buenas!
Simplemente tendremos htop abierto en alguna terminal para corroborar que el uso de Memoria no crezca indefinidamente, bajo ningún punto de vista es requerido tener 0 bytes perdidos ya que no se correrá con Valgrind y de hecho esa no es la definición de Memory Leak :)

**Comment by lalvarez-utn-frba** [comment]
Tenés razón, entendido, muchas gracias! Cierro el issue.
