### ISSUE TITLE
Verificar si se escribio en espacio de usuario

### ISSUE THREAD

**Issue by AgusSartorio** [sisoputnfrba/foro#2770]
En la funcion de memoria que se utiliza para leer una posicion del espacio de usuario, si me solicitan una posicion donde previamente no se haya escrito, rompe y finaliza la ejecucion. Lo que necesitaria para poder resolver esto es que si se escribio previamente retorne el valor y si no se escribio que no devuelva nada (quizas un loggeo de error). 
Mi problema es que no se como escribir este if, se que deberia ser algo como que el valor en esa posicion tiene que ser distinto a nulo o cero
Por otra parte se que siempre me van a hacer escribir previo a leer, pero utilizo esta funcion tambien cuando tengo que swapear y guardar lo escrito en el .swap correspondiente. Por ende por fragmentacion interna me puede pasar que haya una parte que no este ocupada/escrita

```
uint32_t* leerElPedido(int posicion){
	uint32_t* datoALeer = malloc(sizeof(uint32_t));
	if(&memoria+posicion != 0){
		memcpy(&datoALeer, &memoria+posicion, sizeof(uint32_t));
		return *datoALeer;
	}else{
		return 0;
	}
}
```

**Comment by RaniAgus** [comment]
¡Buenas! No es requerimiento del enunciado validar que la memoria a leer haya sido escrita previamente. De hecho, si miran las pruebas van a ver que no hay ningún caso en el que eso suceda.

Incluso sería más correcto que el comportamiento sea el mismo que en C a la hora de leer una variable sin inicializar: que el dato se lea de todas formas sin importar que contenga "basura". 

Igual, si eligen inicializar la memoria en 0 también estaría bien, pero sería incorrecto asumir que si lo leído vale 0 es porque hay un error. Es como que C no te permita leer un `int a = 0;` :P

Saludos
