### ISSUE TITLE
Swap en primer acceso a memoria

### ISSUE THREAD

**Issue by GabiSirota** [sisoputnfrba/foro#2771]
Buenas teniamos una consulta acerca del primer acceso a memoria

Queriamos saber que pasaria cuando no hay frames cargados en memoria, entonces al hacer esa primera escritura deberiamos cargar de SWAP la pag vacía o distinguir el caso y escribir directamente en memoria

**Comment by RaniAgus** [comment]
¡Buenas! El comportamiento debe ser el mismo que en la teoría: se debe producir el page fault y cargar la página en un frame. Saludos
