### ISSUE TITLE
Perdida o errores de comunicacion en Tests Integrales Distribuidos

### ISSUE THREAD

**Issue by nfernandezsanz** [sisoputnfrba/foro#2773]
Buen dia! 
Hace varios meses venimos haciendo pruebas en las comunicaciones sin ningun sobresalto.. con estas mismas funciones de envio y recepción nos funcionaron todos los test (incluidos los integrales) excelentemente en **una unica VM**. Para cualquier tipo de envio, generamos un strem (void*) y ejecutamos un unico send. 
En estos dias estuvimos probando los test en entornos distribuidos, varias notebooks con la VM Server de la catedra, en una misma LAN. Los test funcionan perfecto, pero en algunos casos los Test Integrales sufren de problemas en la comunicacion.. puntualmente con el stream de los pcb.. Entre tantos envios los programas se nos terminan corrompiendo y conduciendo a errores.. 
Haciendo multiples pruebas, en la serializacion y des-serializacion estamos algo confundidos ya que funciona todo perfecto el 99,9% de las veces.. en los test integrales los PCB se envian muchas veces como para no estar detectando un error de estas caracteristicas en local. Los datos siempre comienzan a enviarse correctamente.. y logramos des-serializar hasta +- la mitad del paquete problematico.  
Leyendo en internet encontramos que en algunos casos existen tamaños maximos de paquete a enviar.. los programas de los test integrales son bastante mas grandes que los de los otros test y sospechamos que puede llegar a tener algo que ver con esto. 
Otra cosa curiosa que nos sucedio es que **luego de varias horas de pruebas** el SO nos tiro el siguiente error: ` Too Many Open Files`.  Imprimiendo varios logs notamos que el nro de socket no se esta reutilizando.. y cada vez que creamos una conexion la numeracion es mayor (los sockets el SO los termina tratando como archivos a fin de cuentas, no?).
Existe alguna configuracion o flags que debamos colocar en los sockets para evitar estos problemas? Existe algun tipo de validacion en el protocolo que evite que lleguen datos corruptos? 
Estos problemas los estamos teniendo unicamente en la ejecución distribuida del TP y con los test integrales.

**Comment by iago64** [comment]
Buenas! Cómo va?

Vamos por partes porque el issue es bastante extenso 😄
 
1.- Tamaños de los scripts: No debería ser un problema si serializan bien las cosas, para esto es sumamente importante que si están pasando strings y usan `strlen()` no se olviden de sumar el `'\0'` y agregarlo, porque puede que eso les traiga algunos problemitas.

2.- Error de `Too many open files` efectivamente, en linux *TODO* es un archivo, incluidos los sockets, lo que me deriva en una pregunta, uds crean un socket, mandan el mensaje y lo cierran? o como tienen armada la gestión de los sockets? Porque puede ser que venga por ahí el problema. La idea es que los sockets los levanten una vez al inicio y los mismos queden ahí para todas las comunicaciones hasta que terminan los procesos (ya sean las consolas porque termina el proceso o kernel / cpu / memoria  porque lo matan con Ctrl + C)

3.- Un poco la idea de los test integrales era justamente esto, ver que la resiliencia del TP, es decir, que no se comieran todos los recursos (ya sea la CPU con una espera activa, la memoria con memory leaks o los sockets por abrir mil sockets y dejarlos abiertos).

Saludos.-

**Comment by nfernandezsanz** [comment]
Buenas! 
Nos sirvio bastante, estabamos levantando un socket por conexión.. por lo que acumulabamos muchos.. si bien los cerrabamos  con `close` seguian vinculados al proceso.
Realizamos esa modificacion y comenzo a funcionar mucho mejor. Ahora abrimos un socket al inicio (por cada via de comunicacion) y lo `reutilizamos`.
Gracias 👯 !
