### ISSUE TITLE
Uso de scripts para cambiar la configuracion

### ISSUE THREAD

**Issue by Salacas** [sisoputnfrba/foro#2774]
Buenas! Con mi grupo se nos ocurrió utilizar scripts de bash para cambiar automaticamente la configuración para una determinada prueba. Esto se puede hacer, no?
Muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

Se puede y de hecho los vamos a querer un montón porque agiliza las pruebas 😄 

Saludos.-
