### ISSUE TITLE
Duda  en manejo instrucciones memoria

### ISSUE THREAD

**Issue by EspositoLucas** [sisoputnfrba/foro#2775]
Hola, Buenas  . Surgió una pequeña duda a la hora de hacer las traducciones en memoria de las direcciones que envía CPU para las tres instrucciones . Entendemos la lógica de que por ejemplo para la instrucción READ, se tiene que buscar dentro de las tablas de paginas de segundo nivel del proceso el marco a leer de la dirección física y enviárselo después  a CPU  . Por ahora eso lo tenemos implementado así :  

```
uint32_t leer_de_memoria(uint32_t dir_fisica){
	uint32_t nro_marco = (uint32_t) (dir_fisica / config_valores_memoria.tam_pagina);

	tabla_de_segundo_nivel* tabla_donde_leer = (tabla_de_segundo_nivel*) list_find(lista_tablas_segundo_nivel,tiene_mismo_indice);

	pthread_mutex_lock(&mutex_marcos);
	t_p_2* indice_segunda_tabla = (t_p_2*) list_find(tabla_donde_leer->lista_paginas,nro_marco);
	uint32_t valor_leido_memoria = indice_segunda_tabla->marco;
	pthread_mutex_unlock(&mutex_marcos);
	return valor_leido_memoria;
}
```
El problema es que nos trabamos en en el tema de buscar las tablas  del proceso, capaz es una sencillez pero para ese caso, se podría directamente pasar como parametro el `pcb` ( que tiene un campo `id_proceso`) para así obtener a través del id las tablas del proceso ? No lo pusimos porque entendemos que el manejo de instrucciones se usa independientemente del pcb o proceso porque ya viene la dirección cargada desde CPU pero surgió ese problema y pensamos que capaz en ese caso para cualquier instrucción (READ, WRITE o COPY) se necesita si o si el pcb para el dato de las tablas de los procesos . Por ejemplo,seria algo asi en este ejemplo de leer donde se recibiria el pcb como segundo parametro : 
```
uint32_t leer_de_memoria(uint32_t dir_fisica, pcb*pcb){
}
```
Como decía, capaz es algo muy simple pero nos trabamos en eso . Gracias

Saludos

**Comment by RaniAgus** [comment]
¡Buenas!

1. No entendí si lo que están intentando implementar es el 2do acceso a memoria o el 3ro. Repasando:

- Primer acceso: Dados `nro_tabla_1er_nivel` y `nro_entrada_1do_nivel`, devolver `nro_tabla_2do_nivel`
- Segundo acceso: Dados `nro_tabla_2do_nivel` y `nro_entrada_2do_nivel`, devolver `nro_frame`
- Tercer acceso: Es el único que depende de la instrucción. 
   - Si es READ: Dada una `direccion_fisica`, devolver el `valor` que hay en esa dirección (un `uint32_t`).

2. Les recomiendo revisar la definición de la función [list_find()](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/collections/list.h#L210-L214) porque veo que en el parámetro donde deberían pasarle una función están pasando un valor. Los [tests](https://github.com/sisoputnfrba/so-commons-library/blob/master/tests/unit-tests/test_list.c#L257-L270) suelen ser un buen ejemplo.

Saludos

**Comment by EspositoLucas** [comment]
Buenas . Si, es el tercer acceso a memoria para la instrucción . La duda es,dada la direccion fisica que viene como parametro, como se necesita saber las tablas del proceso para obtener el marco de la direccion fisica, cómo hacer para poder obtener el id del proceso, se podría directamente pasarle como segundo parametro el pcb a la funcion  `leer_de_memoria` que tenemos ? o este acceso a memoria es independiente del pcb ?

**Comment by RaniAgus** [comment]
1. No necesitan obtener el `numero_marco` dada una `direccion_fisica` ya que la MMU se encarga de juntar el `numero_marco` del paso anterior con el `offset`. Ese cálculo lo habrán visto en la teoría y es:

**direccion_fisica** = numero_marco * tamaño_pagina + desplazamiento

Como el espacio de usuario en memoria es solo un `void*`, para implementar la lectura deberían poder hacer simplemente:

```c
void *espacio_memoria; // Esto se inicializa al principio con un malloc(tam_memoria)

uint32_t leer_de_memoria(uint32_t dir_fisica) {
   uint32_t valor;
   memcpy(espacio_memoria + dir_fisica; &valor, sizeof(uint32_t));
   return valor;
}
```

2. Esa línea está bien, me refería a la siguiente:
```c
uint32_t nro_marco;

//...

t_p_2* indice_segunda_tabla = (t_p_2*) list_find(tabla_donde_leer->lista_paginas,nro_marco);
```
Pueden implementar una nested function como en [este video](https://www.youtube.com/watch?v=1kYyxZXGjp0) para pasarle el `numero_marco` a la función que recibe `list_filter()`. También recuerden tener en cuenta el bit de presencia.

Saludos

**Comment by EspositoLucas** [comment]
Ok, se entendio la logica de tener que usar el bit de presencia . Pero genero una duda, si nos basamos en tu funcion que nos pusiste de ejemplo : 

```
void *espacio_memoria; // Esto se inicializa al principio con un malloc(tam_memoria)

uint32_t leer_de_memoria(uint32_t dir_fisica) {
   uint32_t valor;
   memcpy(espacio_memoria + dir_fisica; &valor, sizeof(uint32_t));
   return valor;
}
```
En ese caso no haría falta tener en cuenta el bit de presencia porque si el valor esta en el espacio de usuario, se puede asumir que ya esta cargada esa pagina, verdad ? No se si la aclaración del bit iba para la funcion `list_find()` cuando se recorria la tabla del proceso pero confunde porque ya no se usaría mas esa función al no tener que recorrer ninguna lista

**Comment by RaniAgus** [comment]
Sisi tranqui, la aclaración iba para lo del `list_find()` que había antes. Saludos

**Comment by EspositoLucas** [comment]
Ok . Gracias 👍 Cierro por ahora el issue y cualquier cosa lo vuelvo abrir si surge algo
