### ISSUE TITLE
Logear errores de comunicación

### ISSUE THREAD

**Issue by Gdepablo** [sisoputnfrba/foro#2777]
Buenas, tengo una duda con el enunciado

"Módulo: Kernel
El módulo Kernel, dentro de nuestro trabajo práctico, será el encargado de gestionar la ejecución de los diferentes procesos que se ingresen al sistema mediante las consolas, planificando su ejecución en la CPU del sistema.
Lineamiento e Implementación
Al ser un módulo que deberá mantener conexiones con la CPU, la memoria y las diferentes consolas que conecten, deberá implementarse mediante una estrategia de múltiples hilos de ejecución.
Cualquier fallo en las comunicaciones deberá ser informado mediante un mensaje en el archivo de log y el sistema deberá continuar con su ejecución.
"

¿A qué considera como fallo en las comunicaciones? ¿Handshake incorrecto? ¿Qué más? ¿Page Faults?
No sabemos qué es y por ende no sabemos cómo programarlo
Saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

El ejemplo del handshake incorrecto es uno de los casos mas visibles, otro caso que puede darse (no a proposito) es si por ejemplo se cae la memoria o la CPU, eso a uds les va a saltar como un error en un `send()` o en un `recv()`, la idea es que el kernel no tire seg fault y explote todo, si no que avisen que se corto la conexión de forma "controlada"

Saludos.-

**Comment by Gdepablo** [comment]
Sisi está resuelta. Ya lo cierro
