### ISSUE TITLE
Problemas al conectar módulos.

### ISSUE THREAD

**Issue by mSpagnol** [sisoputnfrba/foro#2778]
Buenos días! Vinimos a probar con mi grupo el tp al laboratorio de Medrano y tanto ayer cómo hoy estamos teniendo el mismo problema. Utilizamos tres máquinas distintas y cada una con una maquina virtual sin entorno gráfico. Cuando intentamos conectar los tres módulos (Kernel, Cpu y Memoria) nos salta un segmentation fault al momento de conectar la cpu con kernel. Sin embargo, cuando probamos levantar cpu en una maquina virtual con entorno gráfico funciona perfecto (En el mismo laboratorio).

Ya estuvimos revisando el código varias veces y no sabemos si al no tener el entorno gráfico cambia en algo en cuanto a las conexiones. Capaz en entregas anteriores tuvieron algún problema similar por lo que nos podrían orientar.

Espero su respuesta,

Martín.

**Comment by iago64** [comment]
Buenas! Cómo va?

El caso por como lo plantean es raaro, pero tengo una consulta, en la VM con entorno gráfico lo corren con eclipse o desde la terminal? Porque lo que me suena es que le están mandando alguna ruta hardcodeada de los config y por eso no lo encuentra y revienta.

Saludos.-

**Comment by JuanCruzReyAlvarez** [comment]
Buenas, nos esta pasando exactamente  lo mismo que dicen los chicos, y no tenemos ninguna ruta harcodiada. Nosotros lo estamos intentando correr en la VM sin entorno grafico en LAN y no podemos .  Nos corre bien la comunicacion de kernel a memoria pero memoria cpu siempre falla.  No sabemos donde puede estar el problema. Saludos

**Comment by mSpagnol** [comment]
Damian! Nosotros ya lo pudimos resolver, cambiamos un par de cosas en las conexiones y funcionó. Pero nos sorprendió.

Muchas gracias por estar atentos, nos vemos mañana!

**Comment by FacuBazzi** [comment]
Hola @mSpagnol , perdón por molestarte pero si es posible podrías mostrarnos cuál era el error? Así nos aseguramos de no estar haciendo lo mismo :) Gracias!

**Comment by mSpagnol** [comment]
@FacuBazzi la verdad que no tengo la solución exacta. Estuvimos dos días mirando el código y cambiamos los hilos de como recibían las conexiones. Después lo probamos todo un día y anduvo perfecto, pero no tengo una solución exacta. Perdón!

**Comment by Salacas** [comment]
A nosotros nos pasó lo mismo, con el entorno gráfico andaba y en el ubuntu server no (aunque no fuimos a Medrano).
El problema era que nosotros mandábamos como parte de la pcb un puntero. Parece que cuando lo corríamos en la ubuntu server un proceso utilizaba un puntero de 32 bits y otro de 64 bits, causando que el kernel se quede esperando otros 32 bits que el cpu nunca le iba a mandar.

**Comment by iago64** [comment]
> Hola @mSpagnol , perdón por molestarte pero si es posible podrías mostrarnos cuál era el error? Así nos aseguramos de no estar haciendo lo mismo :) Gracias!

Buenas! Si les copa, creen un nuevo issue y revisamos su problema en particular, por favor tiren algo mas de info (por ejemplo si corrieron el tp en consolas desde la vm con entorno gráfico, si tienen todas las carpetas creadas, etc, para poder darles algo mas de info, porque en el aire es complicado adivinar)

> A nosotros nos pasó lo mismo, con el entorno gráfico andaba y en el ubuntu server no (aunque no fuimos a Medrano). El problema era que nosotros mandábamos como parte de la pcb un puntero. Parece que cuando lo corríamos en la ubuntu server un proceso utilizaba un puntero de 32 bits y otro de 64 bits, causando que el kernel se quede esperando otros 32 bits que el cpu nunca le iba a mandar. Lo solucionamos mandando un entero, en cambio. Por eso también la importancia de mandar los int como int32_t.

Alguien del grupo estaba utilizando linux de manera nativa? porque tanto la VM server como la entorno gráfico son de 32 bits (por ahora) , de hecho la vm con interfaz gráfica es la server con un par de paquetes de GUI instalados 😄

**Comment by Salacas** [comment]
> > Hola @mSpagnol , perdón por molestarte pero si es posible podrías mostrarnos cuál era el error? Así nos aseguramos de no estar haciendo lo mismo :) Gracias!
> 
> Buenas! Si les copa, creen un nuevo issue y revisamos su problema en particular, por favor tiren algo mas de info (por ejemplo si corrieron el tp en consolas desde la vm con entorno gráfico, si tienen todas las carpetas creadas, etc, para poder darles algo mas de info, porque en el aire es complicado adivinar)
> 
> > A nosotros nos pasó lo mismo, con el entorno gráfico andaba y en el ubuntu server no (aunque no fuimos a Medrano). El problema era que nosotros mandábamos como parte de la pcb un puntero. Parece que cuando lo corríamos en la ubuntu server un proceso utilizaba un puntero de 32 bits y otro de 64 bits, causando que el kernel se quede esperando otros 32 bits que el cpu nunca le iba a mandar. Lo solucionamos mandando un entero, en cambio. Por eso también la importancia de mandar los int como int32_t.
> 
> Alguien del grupo estaba utilizando linux de manera nativa? porque tanto la VM server como la entorno gráfico son de 32 bits (por ahora) , de hecho la vm con interfaz gráfica es la server con un par de paquetes de GUI instalados 😄

Usamos una sola vm con ubuntu server. Logeamos el sizeof del puntero y en una consola era de 8 y en otra de 4. Dejamos de enviar el puntero y el programa anduvo perfecto. Rarísimo

**Comment by iago64** [comment]
Buenas! Rarísimo no es si usaron una VM que no sea la de la cátedra, porque las VMs de la cátedra son de 32 bits y cualquier otra instalación / VM que hagan seguramente sea de 64bits, ya que las VMs de la cátedra estan algo viejas y estamos planeando el upgrade 😉

**Comment by Salacas** [comment]
@iago64 usamos la vm de la entrega. La que está publicada en utnso.com.ar. Igualmente el problema ya está resuelto aunque nos sigue pareciendo rarísimo. Quizás nos pasamos algo por alto pero, en base a los logs y por cómo resolvimos el problema, entendemos que un proceso utilizaba 64 bits para el puntero y otro proceso utilizaba 32 (en la misma vm).

**Comment by iago64** [comment]
Buenas!

Es muy raro, las VMs son de 32 bits, de hecho es uno de los motivos por los cuales estamos entre medio de las evaluaciones armando las VMs nuevas para el cuatri que viene para que sean todas de 64 bits y eliminar el problema de "compatibilidad" que hay cuando alguien utiliza su instalación nativa de linux.

El sizeof(void*) en las vms hasta ahora debería ser de 4 bytes sin dudar, pero bueno, al menos tenemos la info de que pudo haber sido algo de manejo de punteros y que moraleja, no se mandan nunca punteros por sockets 😉 

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Para sumar: algo que puede haber pasado es que la VM con entorno gráfico esté configurada con el adaptador de red en "Bridged Adapter" como en este issue https://github.com/sisoputnfrba/foro/issues/2783#issuecomment-1186085776 (se nota porque IP arranca en  `192.168.x.x`) y en la VM server no (por lo que arranca en `10.0.0.x` y no puede ser accedida desde fuera).

El segmentation fault me suena a que se haya producido por no tener manejo de errores en las funciones de sockets para detectar el fallo en la conexión a tiempo, tipo:

```c
if (getaddrinfo(...) != 0) {
    // printear que hubo un error en getaddrinfo
    exit(EXIT_FAILURE);
}

// ...

if (connect(...) == -1) {
   // printear que hubo un error en connect
   exit(EXIT_FAILURE);
}
```
Sin ese chequeo, el programa sigue y puede llegar a haber algo que produzca el segmentation fault.

Saludos

**Comment by iago64** [comment]
Cerramos el issue por inactividad, cualquier cosa pueden abrir uno nuevo y citarlo 😄
