### ISSUE TITLE
Asignación de posición de página en swap

### ISSUE THREAD

**Issue by pmdea** [sisoputnfrba/foro#2779]
Buenas tardes, testeando el módulo de swap, revisé que tomé un acercamiento que no estoy del todo seguro si es correcto. Cuando creo las tablas de páginas, les asigno por un contador global el id de la página. Por ejemplo, si el proceso 1 tiene 16 páginas con id 0-15, el proceso 2, comenzaría por la página id 16. Entendíamos que era la forma correcta para reprensentar más cerca como funciona realmente.
Luego, en nuestro struct para representar la página, agregamos un id interno para el número interno de página del proceso. Así, cuando se necesita escribir y leer de swap, hacemos nro_pag_interno * tam_pagina para obtener la dirección dentro del swap.

¿Este acercamiento sería incorrecto?

Entiendo que si lo es, deberiamos hacer que los ids de tablas de páginas sean internos al proceso y así no tendríamos ese problema. O recorrer todo el archivo de swap buscando posiciones libres y para leer buscar la página que coincida.

**Comment by iago64** [comment]
Buenas! Cómo va?

En principio la solución no esta mal, ahora mi pregunta es para que necesitan el número global, si cada proceso tiene su propio archivo de swap?

Saludos.-

**Comment by pmdea** [comment]
Buenas! Sí, tenés razon. Nos habiamos confundido ya que el id global lo usamos para el numero de tabla, no de pagina. Cierro issue!
