### ISSUE TITLE
Dudas varias sobre el kernel

### ISSUE THREAD

**Issue by mbuchutn** [sisoputnfrba/foro#2780]
Buenas, todavia tengo algunas dudas sobre el enunciado del kernel. Lo tengo funcionando de alguna forma pero quiero aclarar esto entes de darle un cierre. Son 4 preguntas, la primera es mas general
Es un poco largo, lo se, pero espero que puedan responderme.  muchas gracias

1.	Cualquier fallo en las comunicaciones deberá ser informado mediante un mensaje en el archivo de log y el sistema deberá continuar con su ejecución.

Como se trata esto? 
Tengo que cerrar el sistema o esperar a que se conecte de nuevo con el modulo caido? Cuantos intentos de reconexión hago?

2.	En caso de que el grado de multiprogramación lo permita … 
Luego dice: El grado de multiprogramación siempre será un valor que permita mantener todos los procesos cargados en memoria principal

Para controlar el grado de multiprogramación, tengo que considerar también la cantidad de memoria que el proceso necesita? O las pruebas están armadas de tal forma que esto siempre encaje y solo tenga que considerar la cantidad de procesos y no su tamaño?

Me refiero a que el planificador de largo plazo decide ejecutar un proceso solo si:
A.	el grado de multiprogramación lo permite (cantidad de procesos en ejecución) 
B.	tengo memoria suficiente (un control que debo hacer yo)

o solo con el primer punto alcanza?

3.	Planificador de mediano plazo:
Estoy trabajando con una sola cola de procesos bloqueados, como dice el enunciado. Uso la función usleep para dormir un hilo que representa el dispositivo de E/S. Tomo el primer proceso de la cola BLOCKED y lo duermo la cantidad de tiempo que corresponda. Una vez que este tiempo termina, el hilo se activa y hago lo que corresponda hacer con ese proceso. Luego tomo el siguiente y repito la operación.

El problema es con los procesos bloqueados que superan el tiempo máximo definido en TIEMPO_MAXIMO_BLOQUEADO. Se me ocurren dos opciones

A.	Podria hacer lo mismo que explique antes, usar un hilo por cada proceso, dormirlo con usleep y cuando se activa, envio el proceso a SUSPENDED-BLOCKED. 
Esta opción es un poco difícil de controlar y además me quedan un montón de hilos dormidos que si tengo que cerrar el programa los tengo que enviarles una señal con pthread_kill o pthread_cancel y no es muy recomendable

B.	La otra opción es enviar a suspendido solo cuando lo necesite. Cuando no tenga  memoria libre, recorro la cola de bloqueados y suspendo los procesos de mayor tiempo, hasta cubrir la memoria necesaria y que demás superen el limite permitido. Seria por solicitud del planificador de largo plazo

Cual es la opción que se recomienda para el TP? parece que van mas por la opción A …

4.	Entre los procesos NEW y SUSPENDED-READY, teniendo en cuenta que SUSPENDED-READY tiene mayor prioridad, tengo que manejarlo con FIFO?

Si dispongo solo de una porción de memoria que alcanza para ejecutar un proceso que no esta primero en el orden, entre las dos colas, por ejemplo, que este ultimo. Lo envio a ejecutar? Esto provocaría starvation de procesos de gran tamaño. O siempre respeto el orden? La prioridad de colas seguro que si, esta definido así en el TP

**Comment by mbuchutn** [comment]
Buenas! gracias por las respuestas. todo mas claro ahora
Hace una semana que estoy programando para que todo se cierre perfectamente, que toda la memoria se libere, todos los hilos terminen adecuadamente, etc, etc.... no sabia lo del Ctrl+C 
Bueno gracias por la ayuda!!

**Comment by iago64** [comment]
Buenas! Me alegro que la respuesta haya sido de utilidad, no se olviden de cerrar los issues 😄
