### ISSUE TITLE
Duda sobre uso de mmap en swap

### ISSUE THREAD

**Issue by EspositoLucas** [sisoputnfrba/foro#2782]
Hola, Buenas  . Nosotros con al grupo decidimos encarar la parte de crear el archivo de swap para realizar las operaciones de lectura/escritura como un` void*` para asi poder usar el `mmap()` y `unmap()`  para esas operaciones (haciendo el `memcpy`)  . La duda que nos genero es por cada acceso a swap, hay que hacer un `mmap` al archivo ( entiendo que seria como hacer un `malloc`) y una vez que se termino con la operación de swap hacer el `munmap` ( seria como el `free` del `malloc` )? 

El codigo actualmente lo tenemos asi en swap  : 

```
#include "swap.h"

void* archivo_swap ; // la hago global para usarlo en otras funciones una vez que se crea el swap

char* armarPath(int idProceso){
	char* path=string_new();
	path=strcat(pathSwap,strcat("/",strcat(string_itoa(idProceso),".swap")));
	return path;
}

void crearSwap(uint32_t idProceso){ // el swap se crea una sola vez
	int fd;
	char* path=armarPath((int)idProceso);
	if((fd=open(path,O_TRUNC|O_CREAT|O_EXCL,S_IROTH|S_IWOTH))==-1){
		log_info(memoria_logger,"Error al crear el archivo swap del proceso: %d\n",idProceso);
		exit(-1);
	} else {
		log_info(memoria_logger,"Se creo el archivo swap del proceso: %d\n",idProceso);
	}
	ftruncate(fd,idProceso); // pongo el truncate porque el ayudante me dijo que no funcionaba sino el mmap y unmap

	// hacer el mmap para que quede siempre abierto

	archivo_swap = mmap(NULL,idProceso,PROT_WRITE|PROT_READ,MAP_SHARED,fd,0);

	//close(fd);
}
void eliminarSwap(pcb* pcb){
	munmap(archivo_swap,pcb->tamanio_proceso); // una vez que se escribio en swap y libero el espacio, ahi recien se hace el free del mmap
	if(remove(armarPath(pcb->id_proceso))==-1){
		log_info(memoria_logger,"Error al borrar el archivo swap del proceso: %d\n",pcb->id_proceso);
		exit(-1);
	} else {
		log_info(memoria_logger,"Se borro con exito el archivo swap del proceso: %d\n",pcb->id_proceso);
	}
}

void suspender_proceso(int socket_cliente) { // aca hay que desasignar las paginas del proceso en los marcos en los que están asignadas y escribir en swap si el bit de modificado es 1

	pcb* pcb = recibirPcb(socket_cliente);

	//chequeo bit modificado de las paginas y las escribo en swap si esta en 1

	usleep(config_valores_memoria.retardo_swap); // retardo swap antes de escribir paginas modificadas

	escribirPaginasModificadas(pcb);


}
bool modificados(t_p_2* marq){
	return marq->m;
}
t_list* marcosMod(t_list* marquinhos){
	t_list* modificado=list_filter(marquinhos,modificados);
	return modificado;
}
void escribirPagEnSwap(t_p_2* pag){
	usleep(config_valores_memoria.retardo_swap);
	memcpy(archivo_swap+get_marco_offset(pag->indice),memoria_usuario+get_marco_offset(pag->marco),config_valores_memoria.tam_pagina);
}

void escribirPaginasModificadas(pcb* pcb){
	t_list* paginasProc=marcosMod(paginasEnMemoria(pcb->id_proceso));

	for(int i=0;i<list_size(paginasProc);i++){
		t_p_2* pag=list_get(paginasProc,i);
		escribirPagEnSwap(pag,archivo_swap);
		liberarMarco(pag->marco); // despues de escribir la pag, libero el marco de esa pagina
	}
}

void* traerPaginaDeSwap(uint32_t numPag){
	usleep(config_valores_memoria.retardo_swap);
	void* pag=malloc(sizeof(config_valores_memoria.tam_pagina));
	memcpy(pag,archivo_swap + get_marco(numPag),config_valores_memoria.tam_pagina);
	return pag;
}




```
donde archivo swap en nuestro caso es una variable global y el sabado pasado en soporte un ayudante me comento de que el archivo swap, en la funcion `crearSwap()`queda siempre abierto donde el `mmap` se haría despues de a hacer el `ftruncate` para cambiar el tamaño del archivo al tamaño del proceso . La duda que nos genero tambien a partir de ahi si en ese caso, el `mmap` seria una sola vez al momento de crear el swap o tambien se tendria que aplicar para las lecturas/ escrituras como por ejemplo en `suspender_proceso()` ? Porque confunde si el `archivo_swap` al quedar siempre abierto habría un solo `mmap` al crearlo y `munmap` cuando se liberan todas las estructuras del proceso en swap . No se si fui claro pero espero que se haya entendido la duda jaja

Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

Si van a utilizar `mmap()` lo que tienen que hacer es lo siguiente:

1.- Crear el archivo
2.- Truncarlo al tamaño del proceso
3.- Levantarlo con `mmap()`
4.- Guardar el puntero devuelto por `mmap()` en algún lado para poder hacer las operaciones de lectura / escritura
5.- Después de cada operación de **escritura** mandar un `msync()` a ese puntero que les devolvió `mmap()` para "forzar" la escritura de los datos.

Saludos.-

**Comment by EspositoLucas** [comment]
@iago64 Buenas Damian . No entiendo el uso de `msync()` cuando mencionas para _"forzar" la escritura de los datos_. Eso que significa ? Consultando el man , menciona que `msync () `elimina los cambios realizados en la copia del archivo swap que se levanto con `mmap() `para que antes de llamar a `munmap()` tener los cambios ya escritos en el archivo, a eso te referis ? 
En ese caso, cuando se mandaria el `munmap()` ?  Despues de haber hecho todas las llamadas de msync para cada escritura o despues de cada acceso a swap ?

Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

Justamente la idea detras de `msync()` es actualizar los datos en el archivo.
Después, pregunta importante, para que quieren hacer `munmap()`? No les resulta mas práctico tener los archivos siempre levantados mientras el proceso vive?

Saludos.-

**Comment by EspositoLucas** [comment]
@iago64  Buenas Damian . Al final decidimos usar `munmap() `solo una vez, cuando se elimina el swap porque justamente es en ese caso donde el proceso ya no esta "vivo" al no tener mas sus estructuras cargadas en memoria . 
Surgieron de paso dos dudas : 
1. Sober el uso del `msync()`, para el tercer parámetro que flag le pasaríamos, `MS_ASYNC` o `MS_SYNC` ? porque no entendí muy bien la diferencia y cual aplicar o es indistinto ? 
2. No se muy bien cuando se haría el close del `fd` (file descriptor) que se crea en swap, se haría una vez que se crea o cuando se elimina el swap ? 

Saludos

**Comment by iago64** [comment]
Buenas!

1.- El 3er parametro de `msync()` que queres pasarle es `MS_SYNC` para decirle que vas a esperar hasta que grabe los cambios, igual si no van a estar cerrando el archivo (haciendo `munmap()` no se preocupen, en algun momento los cambios se van a guardar en el archivo)

2.- El FD lo tienen que cerrar cuando ya no van a usar mas el archivo, si lo cierran antes les va a explotar en la cara 😄 

Saludos.-

**Comment by EspositoLucas** [comment]
Ok, lo tendré en cuenta. Gracias @iago64 Damian . Cierro el issue y cualquier otra duda lo vuelvo a abrir o abro uno nuevo 

Saludos
