### ISSUE TITLE
Conectar modulos en red local

### ISSUE THREAD

**Issue by fakita1** [sisoputnfrba/foro#2783]
Buenas noches! Queremos probar cada modulo desde una computadora distinta, conectados a la misma red, pero no estamos pudiendo siquiera recibir los mensajes.

Cosas que probamos: 

1. Ver la IP local de las VMs y es igual en todas, así que descartamos eso.
2. Mandar el mensaje a la IP local de las maquinas reales.
3. Punto 2 pero con reenvío de puertos desde VirtualBox. Habremos hecho mal esto? (IP Anfitrion: 127.0.0.2, Puerto anfitrion: el que toque abrir, IP invitado: 10.0.2.15, Puerto invitado: mismo que puerto anfitrion)

Cual es la manera de lograr hacer esto?

**Comment by RaniAgus** [comment]
¡Buenas! En el caso de querer conectar varias máquinas en la misma red la configuración que usamos en el labo es "Bridged Adapter":

![image](https://user-images.githubusercontent.com/39303639/179338791-67261efb-6185-44c6-8440-7186c770230d.png)
> Si les da curiosidad, [este video en inglés](https://www.youtube.com/watch?v=QO_Tv02ND-k) explica cómo funciona cada adaptador de red de VirtualBox.

Ejecutando `ifconfig` debería aparecer la IP con un formato parecido a [este](https://docs.utnso.com.ar/guias/consola/bash.html#ifconfig).

También tenemos un video sobre cómo conectar dos máquinas distintas sin que estén en la misma red usando `ngrok`, por si quieren probarlo entre miembros del grupo: https://www.youtube.com/watch?v=vFkmdQVn4Ug

**Comment by fakita1** [comment]
Resuelta, muchas gracias! En el lío de probar todo la madrugada anterior se me olvido responder.
