### ISSUE TITLE
Retardos de SWAP

### ISSUE THREAD

**Issue by Naicon67** [sisoputnfrba/foro#2784]
> cada acceso a SWAP deberá tener una espera en milisegundos

Cuando un proceso es suspendido, y es necesario mandar varias páginas a SWAP, el retardo especificado sería para cada escritura de cada página, o sería el retardo total de la acción escribir varias páginas? Lo mismo para cuando el proceso es desuspendido, la lectura tendría tantos retardos como páginas haya que traer, o uno solo debido a que se interpreta que se hizo una única lectura del archivo?

**Comment by iago64** [comment]
Buenas! Cómo va?

Separemos el problema en 2 partes:
1.- Al momento de **suspender**, pueden tomarlo como N operaciones a SWAP o 1 sola, la verdad que en ambos casos no nos va a cambiar mucho los resultados de la prueba 😄 

2.- Al momento de **des-suspender** un proceso, no tienen que traer nada a memoria, las páginas se van a ir cargando a medida que se den los page fault cuando quieran acceder. No se olviden que es paginación bajo demanda 😉 

Saludos.-

**Comment by Naicon67** [comment]
Gracias! No había tenido en cuenta lo de la des-suspensión, vamos por 1 sola así es un poco más ágil jeje
