### ISSUE TITLE
Manejo de interrupciones en kernel

### ISSUE THREAD

**Issue by mbuchutn** [sisoputnfrba/foro#2785]
Hola!

Tengo una duda sobre el planificador de corto plazo, con SRT (tambien pasa con FIFO, con algunas diferencias)
Cuando llega un proceso a READY envio una interrupcion al CPU para que se detenga y me devuelva el PCB por dispatch.

¿Que debo hacer entre el tiempo en que envio la interrupcion y el CPU me contesta? 
En los ejecicios hablamos siempre de instantes, pero ahora ya no es asi, las operaciones de envio de datos por red pueden tardar un poco

En esta situacion, y teniendo en cuenta que mas procesos van a estar llegando desde NEW, BLOCKED, SUSPENDED_READY ya que todo esto se trabaja en hilos independientes
Tengo dos caminos programados, solo quiero asegurarme de saber cual es el correcto

1. Serializo las interrupciones: tengo un mutex que se bloquea cuando se envia la interrupcion, cuando la CPU contesta tomo el primer elemento de READY (estan ordenados), comparo con el que se estaba ejecutando y envio el que correcponda a la CPU. Recien despúes de todo esto, desbloqueo el mutex y atiendo la siguiente interrupcion. Repito el proceso por cada interrupcion
- Esta opcion fija el instante de seleccion de proceso al momento de generar la interrupcion -

3. Envio la interrupcion pero mientras espero la respuesta de la CPU, dejo entrar otras interrupciones que vayan llegando, que practicamente las ignoro. es como si las deshabilitara. Cuando la CPU me contesta, bloqueo la llegada de interrupciones, tomo el primer proceso de READY, compraro con EXEC, etc... lo mismo de arriba
- Esta opcion fija el instante de seleccion de proceso al momento en que la CPU es desalojada -

Aclaro que la cola de READY esta ordenada por rafaga y los parametros de la catedra (clock, finalizacion de eventos, procesos nuevos)

gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

La verdad que están planteando un escenario un tanto "complicado", si se fijan en las pruebas es bastante poco probable (al menos en las que medimos bien la planificación) que les ocurran mas cosas mientras están esperando una respuesta de CPU, con lo cual, a priori, ambas soluciones deberían funcionar correctamente.

Saludos.-

**Comment by mbuchutn** [comment]
gracias, todo claro!
