### ISSUE TITLE
Duda prueba integral

### ISSUE THREAD

**Issue by GabiSirota** [sisoputnfrba/foro#2786]
Buenas estabamos intentando ejecutar la prueba integral y vimos que la INTEGRAL_3 tiene un comportamiento distinto a las otras pruebas que realizan operaciones parecidas.

Quisieramos saber que es lo que se busca probar con este script para saber donde podemos llegar a tener un error, porque ya lo analizamos detenidamente y no sabemos a que se debe.

Saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

El objetivo de la prueba en general es el de evaluar como se comporta el sistema completo funcionando con cosas que no están del todo "claras", por eso es que los resultados esperados son que los procesos terminen y que en el medio no hayan tenido esperas activas o memory leaks.

Saludos.-
