### ISSUE TITLE
Gants pruebas

### ISSUE THREAD

**Issue by marcorodriguezmelgarejo** [sisoputnfrba/foro#2787]
Hola buenas tardes, con nuestro grupo nos vamos a presentar para la segunda entrega, y uno de los errores que tuvimos fue que no se cumplía el orden de ejecución de los procesos en las pruebas de Planificación y Suspensión. Si bien los procesos terminaban en el orden esperado, la planificación de los mismos difería con la especificada en el gant. Están subidos a algún lado los gantt de estas dos pruebas (planificación y suspensión) con los distintos algoritmos como para que podamos así analizar en donde falla nuestro tp?
Saludos.

**Comment by iago64** [comment]
Buenas! Cómo va?

Los gantt no están en su mejor formato pero mas o menos se entiende como deberían quedar los procesos:

Prueba de Suspensión
![image](https://user-images.githubusercontent.com/1622109/179727210-bc85c892-10a4-4c2a-a786-8237819ae5ba.png)

El de plani es mas o menos parecido solo que en el caso de FIFO la IO es mas corta y en SRT el proceso 3 se va cortando de a cachitos porque los que vuelven de IO tienen mas prioridad que el último que entró, igual pueden armarlo siguiendo como un ejercicio de clase y tomando cada "rafaga" como 1000ms

Saludos.-

**Comment by marcorodriguezmelgarejo** [comment]
Ok muchas gracias, me re sirve. Saludos.
