### ISSUE TITLE
Retardo intencional entre kernel y memoria

### ISSUE THREAD

**Issue by Salacas** [sisoputnfrba/foro#2788]
Buenas! Tengo entendido que las solicitudes que el kernel hace a memoria, a diferencia del cpu, no deberían tener un retardo intencional (ni de memoria propiamente dicho ni de swap). Es correcto esto? Porque nuestro TP sí provocaba un retardo con kernel, haciendo que el kernel planifique de una forma diferente al gantt que los ayudantes tenían como guía.
Muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

Una pregunta al respecto, porque no me termina de quedar claro, el retardo que uds estaban generando era por una cuestión de que reutilizaban el código que tenían para por ejemplo atender un page fault o porque les pareció correcto agregarlo?

Saludos.-

**Comment by Salacas** [comment]
Nos pareció correcto agregar a todas las acciones de swap un retardo. Y algunas de estas son acciones que solicita solamente el kernel, no el cpu. Lo que hicimos ahora fue quitar ese retardo solo de estas acciones y dejar el retardo para las de cpu. Está bien lo que hicimos?

**Comment by RaniAgus** [comment]
¡Buenas! Quizás el enunciado pudo haber sido más claro ya que solo en el config se especifica:

> | Campo | Tipo | Descripción |
> |--|--|--|
> | RETARDO_MEMORIA | Numérico | Tiempo en milisegundos que se deberá esperar para dar una respuesta **al CPU**. |

Retomando las respuestas en https://github.com/sisoputnfrba/foro/issues/2730 y https://github.com/sisoputnfrba/foro/issues/2752, si bien en la vida real también hay accesos a disco al interactuar con Kernel (por lo que no está mal haber asumido que iba un retardo), la intención de contar con éstos era mostrar la diferencia de velocidades entre los accesos a TLB y Memoria al hacer `READ`, `WRITE` o `COPY`.

Hicimos éste y otros cambios respecto a la vida real para que las pruebas de planificación en el Kernel no dependan de lo que ocurre en Memoria (como verán, solo tienen instrucciones `NO_OP` e `I/O` por el mismo motivo).

En este caso, si un proceso tarda `RETARDO_SWAP` en suspenderse y hay otro encolado, este último recién entra un rato después, por lo que lamentablemente el Gantt cambia dependiendo de si tienen implementado Memoria o no. 😓 

Saludos

**Comment by Salacas** [comment]
Entonces, solo para confirmar, entre kernel y memoria no debería existir ningún retardo de swap, es así? (El retardo de memoria propiamente dicho ya desde un principio, en nuestro tp, fue solo para el cpu)

**Comment by RaniAgus** [comment]
Confirmo que es así: entre Kernel y Memoria no debería haber ningún retardo de Swap. Saludos

**Comment by LeandroCarbajales** [comment]
Buenas!
Actualizamos el enunciado para que quede explícito que no tengan en cuenta el tiempo de retardo de SWAP para las operaciones de Kernel ya que no estaba definido con claridad.
