### ISSUE TITLE
Page faults en clock y clock-m

### ISSUE THREAD

**Issue by r-cbl** [sisoputnfrba/foro#2789]
Buenas, tengo unas dudas sobre las pruebas de memoria. Hice el ejercicio a modo de borrador y me dio que ocurren dos pf. Y cuando ocurren tengo todos los bits de modificados y de uso en 1 (todas las operaciones anteriores son write), por lo cual obtengo el mismo resultado con ambos algoritmos. 
No entiendo qué parte estoy haciendo mal porque así tengo el mismo tiempo de ejecución en ambas pruebas.
Muchas gracias 🤗

**Comment by FacuBazzi** [comment]
Por la mitad de la ejecución el proceso se bloquea 6 segundos y el tiempo máximo bloqueado es de 5 segundos, por lo que el proceso se suspende. Al suspenderse se guardan todas las páginas en swap y por lo tanto pierden valor todos los bit de presencia, uso y modificado (vuelven todos a 0).
Asumo que no estás teniendo en cuenta esto porque comentás que tenés todos los bit de modificado en 1, siendo que al momento de hacer los reemplazos importantes para la prueba (después de la suspensión) solo están modificadas las páginas que se escriben después de la IO del proceso (2 nomás).
Fijate eso y te va a salir :D

**Comment by r-cbl** [comment]
Muchas gracias! Ya ajusté eso, una consulta más del tema. Cuando suspendo, quién le avisa a cpu? para que pueda actualizar la tlb, porque fuera de la prueba de memoria no tenemos problemas, pero en memoria al tener un sólo proceso sí.

**Comment by FacuBazzi** [comment]
Justo yo hice una consulta muy parecida en #2716 jajaja.
Según me dijo Lean, cuando un proceso abandona el CPU voluntariamente (para hacer IO), hay que resetear la TLB por más que después le toque ejecutar a él de nuevo.
