### ISSUE TITLE
Fallas en recepción de paquete

### ISSUE THREAD

**Issue by lucas-marmo** [sisoputnfrba/foro#2790]
Buenas, estamos teniendo un problema con algunos casos puntuales corriendo las pruebas integrales. Fuimos ya a la entrega del sábado pasado y pasamos todas las pruebas menos la integral que faltaba evitar alguna condición de carrera que corriéndolo en una sola PC no ocurría, las cuales estuvimos solucionando con mutex. Ahora con los cambios hechos la realidad es que corriéndolo en una PC sola anda perfecto, pero cuando conectamos varias (en una red casera), si corremos las integrales en un momento nos pasa esto:
Kernel serializa el PCB para mandarselo a CPU, todos los datos están bien antes de serializar:
![kernel](https://user-images.githubusercontent.com/82062622/179644689-c59f6e6c-58d9-4db2-93a1-409700c3d2ea.jpg)

CPU comienza deserializando también bien, antes de lo de la foto también se mandan algunas cosas más, pero en un momento (instrucción 160) comienza a recibir cualquier cosa:
![cpu](https://user-images.githubusercontent.com/82062622/179644694-97a0ab3b-2d59-4c07-9cab-72338deb0005.jpg)

Esto no nos pasa si lo corremos en una PC sola, tampoco es que pasa siempre porque el mismo PCB ya había sido enviado varias veces de CPU a Kernel y viceversa y no tuvo ningún problema hasta luego de un tiempo de ejecución. También el resto de pruebas están corriendo perfecto en las múltiples PCs.
Quizás la red casera tenga algún problema, pensamos ir igualmente a probarlo a los labos a ver si cambia el funcionamiento, pero no tenemos idea qué podemos hacer para solucionarlo.
Se me ocurre que podría ser un tema de que el size_payload que indica el tamaño de todo lo que se serializará después, al ser de tipo size_t (4 bytes) quizás queda chico para indicar el tamaño de tantas instrucciones y que por eso quizás no llega a englobar todo.
Otra teoría que se nos ocurrió es que ese tipo size_t es distinto en sistemas de 32 bits o de 64 bits (por lo que leí), pero queda descartada ya que printeamos el sizeof(size_t) en ambas computadoras y las dos marcan 4 bytes.
Muchas gracias, espero que se entienda.

**Comment by iago64** [comment]
Buenas! Cómo va?

Con cariño, no pienso ver exactamente que cambia con el texto serializado, pero generalmente este tipo de problemas se dan por algunos motivos básicos:

1.- Basura en los buffer (generalmente cuando serializamos un string nos comemos el temita del \0 al final y bueno, pasan estas cosas
2.- Manejo incorrecto de los desplazamiento, es algo parecido a lo anterior, solo que contamos mal porque usamos strlen() y capaz leemos bytes de menos.
3.- Pisado de memoria: Mas de lo mismo, un acceso mal hecho y un byte que se escribe mal te desarma la cadena para atrás.

Respecto al size_t, calcula que 4 bytes te alcanzan aprox para un número de 2^32, no hay chances de que sea eso, ahora lo que si puede ser es que si están laburando en una maquina de 64bits y en una de 32 bits y por esas remotas casualidades están pasando el sizeof() de un puntero... ahí la cosa se pone fulera porque los punteros entre 32 y 64 bits un poco que se desconocen y bueno... pasan cosas de este estilo que no entendes bien por donde vienen los tiros, pero que casualmente si corre todo en la misma PC al ser la misma arquitectura, todo funca 10/10

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Para sumar, un par de preguntas sobre cómo armaron la lógica de los `recv()`:
- ¿Están chequeando que siempre devuelva la cantidad de bytes que esperan recibir?
- ¿Probaron de pasarle el flag `MSG_WAITALL` en el último parámetro?

Saludos

**Comment by lucas-marmo** [comment]
Muchas gracias a los dos. Al final después de revisar todo, decidimos ir a probarlo a los laboratorios de la facu y nos anduvo todo perfecto allá. Probablemente haya sido algún tema de la red de computadoras casera que estuviera mal configurada. Cierro el issue.
