### ISSUE TITLE
Problema al eliminar swap al finalizar proceso

### ISSUE THREAD

**Issue by EspositoLucas** [sisoputnfrba/foro#2791]
Hola, Buenas . Estamos teniendo problemas a la hora eliminar la estructura swap cuando tiene que finalizar un proceso . Tira un error de `segmentation fault` al tener que hacer un `munmap` del archivo swap y al cerrar el file descriptor del archivo swap con `close(fd)`
y no sabemos por que razon lo tira . probamos descimentándolo y funciono que el proceso termine pero no esta bien que el archivo quede siempre abierto y no se libere el mapeo ni cierre  una vez que finaliza toda la ejecución y por esa razon quería consultarles por que razon se debía . Tanto el `archivo_swap` como el `fd `son variables que están en una estructura global de tipo `archivos_swap`  que se usa para crear y eliminar el swap  . La estructura mas las funciones de `crear_swap()` y eliminar swap() las tenemos asi : 

```C
typedef struct
 {
 	uint32_t pid ;
 	void* archivo;
 	int fd;

 } archivos_swap;

void crearSwap(uint32_t idProceso,uint32_t tamanio_proceso){ // el swap se crea una sola vez
	int fd;
	char* path=armarPath((int)idProceso);
	if((fd=open(path,O_TRUNC|O_CREAT|O_EXCL,S_IROTH|S_IWOTH))==-1){
		log_info(memoria_logger,"Error al crear el archivo swap del proceso: %d\n",idProceso);
		exit(-1);
	} else {
		log_info(memoria_logger,"Se creo el archivo swap del proceso: %d\n",idProceso);
	}
	ftruncate(fd,tamanio_proceso); // pongo el truncate porque el ayudante me dijo que no funcionaba sino el mmap y unmap

	// hacer el mmap para que quede siempre abierto

	archivo_swap = mmap(NULL,idProceso,PROT_WRITE|PROT_READ,MAP_SHARED,fd,0);
	archivos_swap* archivo= malloc(sizeof(archivo));
	archivo->pid = idProceso;
	archivo->archivo = archivo_swap;
	archivo->fd = fd;
	list_add(archivos,archivo);

}
void eliminarSwap(pcb* pcb){
	pthread_mutex_lock(&mutex_comparador_archivo_pid);
	comparador_archivo=pcb->id_proceso;
	pthread_mutex_unlock(&mutex_comparador_archivo_pid);
	pthread_mutex_lock(&mutex_lista_archivo);
	archivos_swap* archivo = (archivos_swap*)list_remove_by_condition(archivos,archivos_con_pid);
	pthread_mutex_unlock(&mutex_lista_archivo);
	//munmap(archivo->archivo,pcb->tamanio_proceso); // una vez que se escribio en swap y libero el espacio, ahi recien se hace el free del mmap
	//close(archivo->fd); // cierro el archivo swap una vez que s etermino de liberar el archivo swap con el munmap
	if(remove(armarPath(pcb->id_proceso))==-1){
		log_info(memoria_logger,"Error al borrar el archivo swap del proceso: %d\n",pcb->id_proceso);
		exit(-1);
	} else {
		log_info(memoria_logger,"Se borro con exito el archivo swap del proceso: %d\n",pcb->id_proceso);
	}
}
```

Capaz habrá un error con el tema de las inicializaciones o no haber asignado bien los valores a las variables pero no estamos seguros de cual es la causa del seg fault . Como comentaba, estan comentadas las lineas del `munmap` y el `close(fd)` en `eliminar swap()` porque tiraba el error  . Si bien funciono sin aplicar eso, entiendo que es un error y por las dudas consulto para ver de corregirlo

Saludos

**Comment by LeandroCarbajales** [comment]
Buenas!
Les recomendaría que pongan un breakpoint en la línea en que hacen el mmap() y correrlo en debug para chequear que los parámetros que le están pasando sean correctos, si les tira un segmentation fault al hacer el munmap es porque algún tamaño no está encajando.

Por otro lado, offtopic:
`	ftruncate(fd,tamanio_proceso); // pongo el truncate porque el ayudante me dijo que no funcionaba sino el mmap y unmap`

Pudieron preguntar para entender qué es truncar un archivo y por qué no funciona el mapeo si no lo hacen?

**Comment by EspositoLucas** [comment]
@LeandroCarbajales Buenas Leandro . 

1 .  Si, ahi probamos y el problema con el `munmap()` y el `close(fd`) no esta en el tamaño sino que a la hora de asignar el `archivo_swap` mapeado al` void* archivo` de la estructura` archivos_swap`  .Esa asignacion se hace en esta funcion : 

```C
void asignarAlArchivo(uint32_t pid) {
	pthread_mutex_lock(&mutex_lista_archivo);
	archivos_swap* archivo = (archivos_swap*)list_find(archivos,archivos_con_pid);
	pthread_mutex_unlock(&mutex_lista_archivo);

	pthread_mutex_lock(&mutex_archivo_swap);
	archivo_swap = archivo->archivo;
	pthread_mutex_unlock(&mutex_archivo_swap);
}
```
y por las dudas lo  mando de nuevo, las inicializaciones de la estructura `archivos_swap` se hace en `crear_swap()` asi : 

```C
void crearSwap(uint32_t idProceso,uint32_t tamanio_proceso){ // el swap se crea una sola vez
	int fd;
	char* path=armarPath((int)idProceso);
	if((fd=open(path,O_TRUNC|O_CREAT|O_EXCL,S_IROTH|S_IWOTH))==-1){
		log_info(memoria_logger,"Error al crear el archivo swap del proceso: %d\n",idProceso);
		exit(-1);
	} else {
		log_info(memoria_logger,"Se creo el archivo swap del proceso: %d\n",idProceso);
	}
	ftruncate(fd,tamanio_proceso); // pongo el truncate porque el ayudante me dijo que no funcionaba sino el mmap y unmap

	// hacer el mmap para que quede siempre abierto

	archivo_swap = mmap(NULL,idProceso,PROT_WRITE|PROT_READ,MAP_SHARED,fd,0);
	archivos_swap* archivo= malloc(sizeof(archivo));
	archivo->pid = idProceso;
	archivo->archivo = archivo_swap;
	archivo->fd = fd;
	list_add(archivos,archivo);

}
```

 No se porque tira error cuando la estructura la inicializamos p con el malloc y los campos también se le asignan, cual seria el problema ahi ? lo mismo con el `fd `porque al hacer `close(fd)` tambien tiraba` seg fault` , capaz habrá un problema en como se inicializan los campos o algo por el estilo porque sino no se me ocurre la razon 

2 .Sobre el `ftruncate(fd,tamanio_proceso)` se me paso el comentario que estaba de antes . Entendemos que esa funcion hace cambiar el tamaño del archivo swap al tamaño del proceso que se le pasa por parámetro  . Pero igualmente, parece que no encaja con esa logica porque al crer el archivo swap con un tamaño de proceso enviado por consola de 1000, tiene un tamaño de 0 bytes cundo deberia ser de 100 bytes, no es asi ? O el uso del `ftruncate()` es para otra cosa ? Capaz eso tambien influye a la hora de hacer el `mmap()` porque depende de ese tamaño que se trunque 

Saludos

**Comment by FacuBazzi** [comment]
me suena a que cuando hacen el malloc en crearSwap, estan calculando el sizeof de un puntero y no del struct.
sizeof(archivo) vendría a ser sizeof(archivos_swap*), y vos necesitas sizeof(archivos_swap).
proba cambiando eso

**Comment by EspositoLucas** [comment]
Lo probé con esa solución y no funciono lamentablemente . Sera un problema al hacer `mmap ` a `archivo_swap` ? porque estoy perdido de donde podría ser sino el error

**Comment by RaniAgus** [comment]
¡Buenas! Lo que dice @FacuBazzi es cierto, cuando al operador `sizeof` se le pasa el nombre de una variable, termina adoptando el tamaño del tipo de dato, en este caso, un puntero. Hay 2 formas correctas de inicializarlo:

a) Indicando el tipo de dato
```c
	archivos_swap* archivo= malloc(sizeof(archivos_swap));
```

b) Desreferenciando la variable
```c
	archivos_swap* archivo= malloc(sizeof *archivo);
```

Dicho esto, se nos dificulta bastante poder entender el motivo del posible error ya que no conocemos los detalles de la implementación de cada función, pero yo empezaría por deshacer un par de malas prácticas de código:

1. ¿Cuál es la intención de tener `archivo_swap` como una variable global si a la vez están ingresando ese puntero en un `struct archivos_swap`, que luego va a una lista global? ¿Hay algún otro lado en donde se esté usando?

2. Lo mismo para `comparador_archivo`. Tengan mucho cuidado con el uso de variables globales, sobre todo en un proceso multihilo. Asumo que esta variable existe porque luego la usan para buscar el archivo con el ID del proceso:

```c
void eliminarSwap(pcb* pcb) {
	pthread_mutex_lock(&mutex_comparador_archivo_pid);
	comparador_archivo=pcb->id_proceso;
	pthread_mutex_unlock(&mutex_comparador_archivo_pid);
	pthread_mutex_lock(&mutex_lista_archivo);
	archivos_swap* archivo = (archivos_swap*)list_remove_by_condition(archivos,archivos_con_pid);
	pthread_mutex_unlock(&mutex_lista_archivo);
	//...
```

Sin embargo, esto se puede lograr de forma más segura (sin necesidad de una variable global) usando una nested function como en [este video](https://www.youtube.com/watch?v=1kYyxZXGjp0):

```c
void eliminarSwap(pcb* pcb) {
        bool archivos_con_pid(archivos_swap* un_archivo) {
            return un_archivo->pid == pcb->id_proceso;
        }
	pthread_mutex_lock(&mutex_lista_archivo);
	archivos_swap* archivo = (archivos_swap*)list_remove_by_condition(archivos,archivos_con_pid);
	pthread_mutex_unlock(&mutex_lista_archivo);
	//...
```

3. En la función `asignarAlArchivo(uint32_t pid)` no están usando el `pid` que recibe, por lo que quizás la función `archivos_con_pid` no esté utilizando el pid correcto al filtrar. Recuerden prestar atención a los warnings del compilador porque son un indicativo de estar cometiendo un error, por ejemplo:

```
warning: unused variable 'pcb' [-Wunused-variable]
```

Saludos

**Comment by RaniAgus** [comment]
Sobre `ftruncate()`,

>  Pero igualmente, parece que no encaja con esa logica porque al crer el archivo swap con un tamaño de proceso enviado por consola de 1000, tiene un tamaño de 0 bytes cundo deberia ser de 100 bytes, no es asi ? O el uso del ftruncate() es para otra cosa ?

Dado que justamente al crear un archivo con `open()` el mismo tiene 0 bytes, ¿por qué crees que no sería lógico truncarlo al tamaño del archivo usando `ftruncate()`? (aclaro que "truncate" significa "truncar" en inglés).

**Comment by EspositoLucas** [comment]
Buenas . @RaniAgus gracias a  tus comentarios, utilizando la nested function pusimos solucionar el problema del `munmap()` y `close(fd)`, Gracias por eso  👍   . Tambien @LeandroCarbajales  ese mmap habia quedado viejo y lo cambiamos  al tamanio_proceso y funciono creandose el archivo con ta-mnio en bytes del tamaño proceso 👍 

Ahora estamos teniendo problemas al mapearse el archivo porque si bien se mapea asi : 

`archivo_swap = mmap(NULL,tamanio_proceso,PROT_WRITE|PROT_READ, MAP_FILE|MAP_SHARED,fd,0);`

a la hora de hacer una lectura (memcpy) del archivo mapeado, nos dice al correr con el debug  que el buffer tuvo overflow arrojando una señal de SIGNAL ABORT  . Este erro esta en esta funcion : 

```C
void* traerPaginaDeSwap(uint32_t numPag){
	usleep(config_valores_memoria.retardo_swap);
	void* pag=malloc(sizeof(config_valores_memoria.tam_pagina));

	memcpy(pag,archivo_swap + get_marco(numPag),config_valores_memoria.tam_pagina);
	return pag;
}

```

donde` archivo_swap` es al variable global que se le asigna al archivo ya mapeado de la estructura `archivos_swap`

Entonces a partir de esto : 

1. Se esta implementando bien el uso de mmap() pasandole bien los parámetros o hay algun parametro o flag que no se le este pasando o que este mal ?

Por las dudas pongo el código de como se crea el swap : 

```C
void crearSwap(uint32_t idProceso,uint32_t tamanio_proceso){ // el swap se crea una sola vez
	int fd;
	char* path=armarPath((int)idProceso);
	printf("tamanio proceso %d\n",tamanio_proceso);
	if((fd=open(path,O_CREAT|O_EXCL|O_RDWR,S_IRUSR|S_IWUSR))==-1){
		log_info(memoria_logger,"Error al crear el archivo swap del proceso: %d\n",idProceso);
		exit(-1);
	} else {
		log_info(memoria_logger,"Se creo el archivo swap del proceso: %d\n",idProceso);
	}
	ftruncate(fd,tamanio_proceso);

	// hacer el mmap para que quede siempre abierto

	archivo_swap = mmap(NULL,tamanio_proceso,PROT_WRITE|PROT_READ, MAP_FILE|MAP_SHARED,fd,0);
	if (archivo_swap == MAP_FAILED)
		    {
		        close(fd);
		        perror("Error mmapping the file");
		    }
	archivos_swap* archivo= malloc(sizeof(archivos_swap));
	archivo->pid = idProceso;
	archivo->archivo = archivo_swap;
	archivo->fd = fd;
	list_add(archivos,archivo);

}
```

Saludos

**Comment by RaniAgus** [comment]
Acá:
```c
	void* pag=malloc(sizeof(config_valores_memoria.tam_pagina));
```

El `sizeof()` está de más.

**Comment by EspositoLucas** [comment]
Buenas . @RaniAgus ahi agus ese `sizeof()` nos resolvió ese problema , y se pudo traer bien de swap, Gracias 👍 

Ahora estamos teniendo un problema al probar la prueba MEMORIA_1 , al hacer la instruccion WRITE 260 2000, tira otro `seg fault` en memoria en la funcion ` asignarAlArchivo()` (funcion donde nos recomendaste usar la nested function), en el que al hacer `printf` para poder  saber el tamaño de la lista global archivos, que es una lista de` archivos_swap` aparece que es de tamaño 0 y es raro porque al crear el swap se incializan los campos de la estructura archivos_swap y despues se le agrega a la lista `archivos` asi : 

```C
void crearSwap(uint32_t idProceso,uint32_t tamanio_proceso){ // el swap se crea una sola vez
	int fd;
	char* path=armarPath((int)idProceso);
	printf("tamanio proceso %d\n",tamanio_proceso);
	if((fd=open(path,O_CREAT|O_EXCL|O_RDWR,S_IRUSR|S_IWUSR))==-1){
		log_info(memoria_logger,"Error al crear el archivo swap del proceso: %d\n",idProceso);
		exit(-1);
	} else {
		log_info(memoria_logger,"Se creo el archivo swap del proceso: %d\n",idProceso);
	}
	ftruncate(fd,tamanio_proceso);

	// hacer el mmap para que quede siempre abierto

	archivo_swap = mmap(NULL,tamanio_proceso,PROT_WRITE|PROT_READ, MAP_FILE|MAP_SHARED,fd,0);
	if (archivo_swap == MAP_FAILED)
		    {
		        close(fd);
		        perror("Error mmapping the file");
		      //  exit(EXIT_FAILURE);
		    }
	printf("tamanio archivo swap %d\n",archivo_swap);
	archivos_swap* archivo= malloc(sizeof(archivos_swap));
	archivo->pid = idProceso;
	archivo->archivo = archivo_swap;
	archivo->fd = fd;
	printf("tamanio del swap : %d",sizeof(archivo));
	pthread_mutex_lock(&mutex_lista_archivo);
	list_add(archivos,archivo);
	pthread_mutex_unlock(&mutex_lista_archivo);

}
```

y la funcion `asiganarAlArchivo()` esta asi ahora con el cambio de la nested function : 

```C
void asignarAlArchivo(uint32_t pid) {
	 bool archivos_con_pid(archivos_swap* un_archivo) {
	            return un_archivo->pid == pid;
	        }
	pthread_mutex_lock(&mutex_lista_archivo);
	printf("tamanio lista archivos %d \n", list_size(archivos));
	archivos_swap* archivo = (archivos_swap*)list_find(archivos,archivos_con_pid);
	printf("tamanio lista archivos %d \n", list_size(archivos));
	printf("archivo pid %d \n", archivo->pid);
	pthread_mutex_unlock(&mutex_lista_archivo);

	pthread_mutex_lock(&mutex_archivo_swap);
	archivo_swap = archivo->archivo;
	pthread_mutex_unlock(&mutex_archivo_swap);
}
```

y el error que tira es este (mando captura para que se vea exactamente donde es por si sirve ) : 

![image](https://user-images.githubusercontent.com/79590470/180626441-9734d51f-5f22-4f97-a356-cf8d7a6a23af.png)

Puede ser un error al crear swap ? porque si el tamaño de la lista  `archivos` es 0 debería ser por eso pero sino no se me ocurre la razon 

Saludos

**Comment by RaniAgus** [comment]
Pongan breakpoints en todos los lugares donde se usa la lista `archivos` y fíjense si se ejecutan en el orden esperado.

**Comment by EspositoLucas** [comment]
Buenas . @RaniAgus ahi agus estuvimos probando y no funciono, sigue tirando el mismo error . No entendemos porque al realizar las operaciones de WRITE la lista de archivos de alguna forma se borra y queda en 0  . Lo único que modificamos es que al agregar  al lista de archivos la estructura archivo en `crearSwap()` no tenía semáforos y al hacer una variable global debería estar, lo mismo agregamos al eliminar swap cuando se elimina la lista  . las fucnciones estan asi : 

```C
void crearSwap(uint32_t idProceso,uint32_t tamanio_proceso){ 
	int fd;
	char* path=armarPath(idProceso);
	if((fd=open(path,O_CREAT|O_EXCL|O_RDWR,S_IRUSR|S_IWUSR))==-1){
		log_info(memoria_logger,"Error al crear el archivo swap del proceso: %d\n",idProceso);
		exit(-1);
	} else {
		log_info(memoria_logger,"Se creo el archivo swap del proceso: %d\n",idProceso);
	}
	ftruncate(fd,tamanio_proceso);

	

	archivo->archivo = mmap(NULL,tamanio_proceso,PROT_WRITE|PROT_READ, MAP_FILE|MAP_SHARED,fd,0);
	if (archivo->archivo == MAP_FAILED)
		    {
		        close(fd);
		        perror("Error mmapping the file");
		    }

	pthread_mutex_lock(&mutex_lista_archivo);
	list_add(archivos,archivo);
	pthread_mutex_unlock(&mutex_lista_archivo);


}


void eliminarSwap(pcb* pcb) {
        bool archivos_con_pid(archivos_swap* un_archivo) {
            return un_archivo->pid == pcb->id_proceso;
        }

	pthread_mutex_lock(&mutex_lista_archivo);
	archivos_swap* archivo = (archivos_swap*)list_remove_by_condition(archivos,archivos_con_pid);
	pthread_mutex_unlock(&mutex_lista_archivo);


		munmap(archivo->archivo,pcb->tamanio_proceso); // una vez que se escribio en swap y libero el espacio, ahi recien se hace el free del mmap
		close(archivo->fd); // cierro el archivo swap una vez que s etermino de liberar el archivo swap con el munmap
		
		if(remove(archivo->path_swap)==-1){
			log_info(memoria_logger,"Error al borrar el archivo swap del proceso: %d\n",pcb->id_proceso);
			exit(-1);
			} else {
				log_info(memoria_logger,"Se borro con exito el archivo swap del proceso: %d\n",pcb->id_proceso);
			}
}
```
Tambien, otra cuestion es que la lista se queda vacia al hacer una escritura en memoria, en esta funcion : 

```C
void escribirPagEnMemoria(void* pagina,uint32_t numMarco){
	pthread_mutex_lock(&mutex_memoria_usuario);
	printf("tamanio lista archivos %d \n", list_size(archivos));
	memcpy(memoria_usuario + get_marco(numMarco),pagina,config_valores_memoria.tam_pagina);
	printf("tamanio lista archivos %d \n", list_size(archivos));
	pthread_mutex_unlock(&mutex_memoria_usuario);
}
```
cosa que es raro porque no involucra el uso de  la lista de archivos swap, porque el `memcpy` es a `memoria_usuario` donde se usa para leer o escribir en memoria, no en swap  . tendra que ver con esa escritura el problema ? porque si depues de ese `memcpy` ahi recien la listase vacia, debe haber algo que provoque esa escritura pero sino no se nos ocurre la razon del error 

Saludos

**Comment by RaniAgus** [comment]
¿Eso compila? En `crearSwap` están usando una variable `archivo` que no está declarada.

**Comment by EspositoLucas** [comment]
Buenas . Al final, lo solucionamos porque el problema estaba que al inicializar la memoria, ele spacio de usuario estab inicilaizado asi : 

`memoria_usuario=malloc(sizeof(config_valores_memoria.tam_memoria));`

Y justo ese sizeof no iba y con eso pasaba que se queria escribir a un muy chico y por eso tiraba seg fault .
Sobre lo de `crearSwap(`), se me paso copiar todo el codigo . En realidad lo tenemos asi : 

```C
void crearSwap(uint32_t idProceso,uint32_t tamanio_proceso){ // el swap se crea una sola vez
	int fd;
	printf("valor pathSwap %s \n",pathSwap);
	char* path=armarPath(idProceso);
	printf("tamanio proceso %d\n",tamanio_proceso);
	if((fd=open(path,O_CREAT|O_EXCL|O_RDWR,S_IRUSR|S_IWUSR))==-1){
		log_info(memoria_logger,"Error al crear el archivo swap del proceso: %d\n",idProceso);
		exit(-1);
	} else {
		log_info(memoria_logger,"Se creo el archivo swap del proceso: %d\n",idProceso);
	}
	ftruncate(fd,tamanio_proceso);

	printf("antes de iniciar archivo swap \n");
	printf("despues de inicar archivo swap \n");
	printf("id de swap : %d \n",archivo->pid);
	archivo->fd = fd;
	archivo->path_swap = path;


	// hacer el mmap para que quede siempre abierto

	archivo->archivo = mmap(NULL,tamanio_proceso,PROT_WRITE|PROT_READ, MAP_FILE|MAP_SHARED,fd,0);
	if (archivo->archivo == MAP_FAILED)
		    {
		        close(fd);
		        perror("Error mmapping the file");
		    }

	pthread_mutex_lock(&mutex_lista_archivo);
	list_add(archivos,archivo);
	pthread_mutex_unlock(&mutex_lista_archivo);


}

```
Ahora estamos teniendo problemas con alguna traducciones al hacer la prueba MEMORIA_1 pero como es otro tema, cierro el issue y cualquier cosa abro uno nuevo sobre el problema . Gracias

Saludos
