### ISSUE TITLE
Variables con uint32_t, uint4_t, etc...

### ISSUE THREAD

**Issue by DamianArielLerner** [sisoputnfrba/foro#2792]
Hola buenas, al no tener laboratorio para probar el tp el día de mañana se me ocurrió que una razón para que "rompa" sea que haya algunas variables declaradas como int, otras como uint32_t y así, y suframos temas de compatibilidad. Hay algún problema con esto? O que tipo de variables deben tener cada tipo (int, uint32_t, uint4_t, etc)? Gracias!

**Comment by RaniAgus** [comment]
¡Buenas! Si te referís al caso borde de que "tengo una variable en `X` tipo de dato y se la asigno a otra variable de `Y` tipo de dato", como:

```c
void mi_funcion(int32_t c) {
    // ...
}

int main() {
  uint32_t a = 1;
  int b = a;
  
  mi_funcion(b);

  //...
}
```

No se preocupen porque C se encarga de castearlo y va a tomar los valores correctos salvo que justo esa variable haya tomado un valor por fuera del rango de su tipo de dato.

En otras palabras, solo pueden llegar a perder información en los casos en los que se pasen del rango, tipo:
- usar `unsigned` o `uintXX_t` para una variable que soporta números negativos
- usar `short int` o `int8_t` para una variable que puede tomar valores por fuera del rango de -128 a 127

También, en caso de haber algún problema muy grosero quédense tranquilos que el compilador se va a encargar de avisar con un warning. De hecho, el warning no es error porque el compilador hace el casteo igual y te avisa que quizás no sea lo que querías hacer (¡por eso **los warnings son tan importantes como los errores**!).

Incluso pueden probar de asignarle distintos valores `int` a un `uint8_t` y van a ver que solo falla cuando se pasa de rango.

Por otro lado, si te referís al caso de "las variables pueden medir distinto dependiendo de la arquitectura si uso `int`, `long`, etc", justamente contamos con las VMs para evitar esos problemas de portabilidad: al ser **la misma imagen que la del labo** cada tipo de dato está declarado de forma unificada. 

Usar tipos independientes de la arquitectura como `int32_t` puede ser útil solo si quieren desarrollar _por afuera_ de las VMs y justo quieren conectar dos procesos que están en distintos entornos (lo cual en la entrega no va a pasar).

Saludos

**Comment by DamianArielLerner** [comment]
Buenísimo, muchísimas gracias por la respuesta!
