### ISSUE TITLE
Duda orden de mandado de consolas - Prueba Integral 

### ISSUE THREAD

**Issue by EspositoLucas** [sisoputnfrba/foro#2794]
Buenas . Con el grupo surgió una duda sobre el orden de ejecución de las consolas porque por ejemplo si se tiene un cantidad de entradas de tabla de página que es 4 y el tamaño de página que es 256 . Si las pruebas tienen tamaño 2048, al dividirlo por el tamaño de pagina (para saber cuantas paginas tiene el proceso) quedarían que el proceso tiene 8 paginas y dividiendo por la cantidad de entradas , nos queda que se necesita 2 tablas de segundo nivel, ósea que se ocupan dos entradas de la tabla de primer nivel . Al correr dos procesos a la vez se llenarían todas las tablas, como haríamos en el caso de correr 5 consolas a la vez ? El nivel de multiprogramación en ese caso no debería ser 2 ? o se ejecuta una prueba a la vez ?

Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

Están olvidando el sutil detalle de que cada proceso tiene su propia tabla de primer nivel, lo que los puede llegar a limitar es la memoria total (que justo para la prueba integral esta calculada para que sobre por todos lados) 

Saludos.-

**Comment by EspositoLucas** [comment]
Si, no lo tuvimos en cuenta . gracias por la aclaración . Cierro el issue y cualquier inconveniente aviso
