### ISSUE TITLE
Atencion de Memoria a modulos CPU y Kernel

### ISSUE THREAD

**Issue by alesiosaba** [sisoputnfrba/foro#2795]
Buenas, con el grupo estamos desarrollando el modulo Memoria pero nos topamos con el inconveniente que no podemos gestionar correctamente las atenciones de CPU y Kernel utilizando solo un puerto.

Logramos generar un socket distinto para CPU y Kernel a la hora de conectarse a Memoria pero cuando intercalamos envios de paquetes desde ambos modulos en cierto momento deja de atender alguno de los dos sockets.

Nuestra alternativa para que funcione correctamente fue que Memoria utilice un puerto de escucha para CPU y otro distinto para Kernel.

¿Podemos optar por esta alternativa para continuar el desarrollo del Modulo o seria algo erroneo?

Desde ya muchas gracias.

**Comment by RaniAgus** [comment]
¡Buenas! Misma respuesta que en #2598 .

Igual si se cierra la conexión en uno de los sockets dudo que sea por tener un solo socket de escucha. Recuerden que `accept()` devuelve **otro socket** (distinto al de escucha) conectado a **otro puerto** disponible, por lo que no hay chance de que interfiera una conexión con otra.

Saludos
