### ISSUE TITLE
cómo inicializar PCB sin perder espacios de memoria

### ISSUE THREAD

**Issue by Gabi314** [sisoputnfrba/foro#2796]
Hola. Estuve probando ejecución con Valgrind y encontré que cuando inicializo el pcb hay memoria que queda perdida y no sé por qué.  Seguramente es una tontería que no estoy viendo pero estoy trabado con eso. En la función hago los siguientes cambios con el pcb:
1° Reservo espacio con malloc y reservo el espacio de memoria correspondiente (acá es donde me tira el error) 
`t_pcb* PCB = malloc(sizeof(t_pcb));`

2° Lo inicializo de la siguiente manera
```
PCB->idProceso = rand() % 985 + 16;
PCB->tamanioProceso = sizeof(t_pcb); 
PCB->instrucciones = listaDeInstrucciones;
PCB->program_counter = 1;
PCB->tabla_paginas = -1;
PCB->estimacion_rafaga = estimacionInicial;
PCB->estimacion_anterior = 0;
PCB->rafagaMs = 0;
PCB->horaDeIngresoAExe = 0;
PCB->estado = NEW;
```
3° Creo una estructura que contiene un parámetro que apunta al idProceso 
```
t_pidXsocket*  datosCliente = malloc(sizeof(t_pidXsocket));
				datosCliente->pid = PCB->idProceso;
				datosCliente->socket = nuevo_cliente;
```
4° Lo paso por parámetro a una funcion que lo mete en una cola de pcbs

`agregarANew(PCB)`

```
void agregarANew(t_pcb* proceso) {

	queue_push(colaNew, proceso);
	log_info(logger, "[NEW] Entra el proceso de PID: %d a la cola.", proceso->idProceso);
}
```
Esto es lo que me tira Valgrind: 
`120 bytes in 3 blocks are definitely lost in loss record 56 of 64 [PID: 32225]	`

**Comment by RaniAgus** [comment]
¡Buenas! Yo buscaría en los lugares en los que haya un `queue_pop(colaNew)`, a ver si hay algún caso en el que falte el `free()`.

**Comment by Gabi314** [comment]
Hola. Sí, hay una función que se encarga de hacerlo. La idea sería hacer algo así?
```
t_pcb* sacarDeNew(){

	t_pcb* proceso = queue_pop(colaNew);
	log_info(logger, "[NEW] Se saca el proceso de PID: %d de la cola", proceso->idProceso);
        free(queue_peek(colaNew))
	return proceso;
}
```
Sinceramente es lo único que se me ocurre pero creo que haciendo eso estaría tratando de liberar espacio de algo que ya no está ahí porque el pop extrae el elemento directamente. Después lo guardo en la variable proceso y va recorriendo cola por cola hasta llegar a una variable global llamada procesoAFinalizar. Así que agregué este free.

`free(procesoAFinalizar);`

pero el problema inicial sigue estando.


Quería hacer otra pregunta ya que estamos. Yo estoy corriendo el programa y en la medida que modifico cosas para que funcione correctamente reviso lo que me tira valgrind porque pensé que me podía dar soluciones a problemas de ejecución. Me conviene seguir así o es mejor terminar de hacer que se ejecute bien por completo y después de eso probar con valgrind.

**Comment by RaniAgus** [comment]
> creo que haciendo eso estaría tratando de liberar espacio de algo que ya no está ahí porque el pop extrae el elemento directamente

En realidad, lo que esta línea está haciendo:
```c
free(queue_peek(colaNew));
```

Es liberar el **siguiente** elemento de la queue y encima sin quitarlo. Dudo mucho que quieras hacer eso porque el siguiente `queue_pop(colaNew)` te va a devolver memoria liberada.

Sigamos todo el algoritmo por donde pasa ese `t_pcb*` hasta la función en la que se pierde la referencia. Las preguntas que me haría para seguir el código son:
- ¿Quién llama a `sacarDeNew()`?
- ¿Esa función guarda el `t_pcb*`, en otra colección (queue/list/dictionary) o lo descarta?
- Si siempre lo agrega a otra colección, ¿en qué momento se quita de ahí?
- ¿En qué momento dejo de necesitar el `t_pcb*`?

Por las dudas, no estoy pidiendo que me muestres todo el código del TP, solo intento orientarte a encontrar el leak por tu cuenta.

> Quería hacer otra pregunta ya que estamos. Yo estoy corriendo el programa y en la medida que modifico cosas para que funcione correctamente reviso lo que me tira valgrind porque pensé que me podía dar soluciones a problemas de ejecución. Me conviene seguir así ? O es mejor terminar de hacer que se ejecute bien por completo y después de eso probar con valgrind?

No entendí la pregunta, o sea, C es un lenguaje compilado por lo que cada cambio que hagas en el código no se va a impactar en tu ejecución actual (hay que cerrar valgrind, recompilar y volver a ejecutar).

**Comment by Gabi314** [comment]
> También me genera dudas que usen una variable global para finalizarlo, ¿la están protegiendo correctamente? ¿Hay alguna forma de evitar usar una variable global para finalizarlo?

Hola! Sí, al final hubo una forma de evitar usar una variable global. Después de pensar en las preguntas y de descartar el uso de una variable global fue más fácil identificar el `free() `que faltaba. Gracias!

> No entendí la pregunta, o sea, C es un lenguaje compilado por lo que cada cambio que hagas en el código no se va a impactar en tu ejecución actual (hay que cerrar valgrind, recompilar y volver a ejecutar).

Perdón, creo que me expliqué mal. Sí, esto lo entiendo. Mi pregunta iba más por el lado de si convenía usar Valgrind como último paso antes de hacer la entrega del tp o era mejor usarlo en la medida que iba modificando el código por cualquier corrección o cosa que falte.

**Comment by RaniAgus** [comment]
> Hola! Sí, al final hubo una forma de evitar usar una variable global. Después de pensar en las preguntas y de descartar el uso de una variable global fue más fácil identificar el free() que faltaba. Gracias!

¡Buenísimo! 🚀 

> Perdón, creo que me expliqué mal. Sí, esto lo entiendo. Mi pregunta iba más por el lado de si convenía usar Valgrind como último paso antes de hacer la entrega del tp o era mejor usarlo en la medida que iba modificando el código por cualquier corrección o cosa que falte.

¡Ahh! Sí, recomiendo usarlo como una herramienta más de debugging. Es más fácil ir corrigiendo los leaks a medida que van surgiendo antes que esperar a la entrega y que aparecan todos de golpe 😉

**Comment by Gabi314** [comment]
Perfecto! Muchas gracias!
