### ISSUE TITLE
Dudas de retardos en swap, memoria y bit modificado

### ISSUE THREAD

**Issue by pmdea** [sisoputnfrba/foro#2797]
Buenas!
Con mi grupo estamos haciendo todas las pruebas y me di cuenta que cuando realicé la implementación de memoria me surgieron algunas dudas.

1. Cuando se suspende un proceso y se pasan todas sus paginas, el retardo por SWAP sería uno solo por la operación de suspender, o uno por cada página con bit modificado = 1 que se escribe en disco? 

2. Cuando se escribe en una página, se marca como modificada, pero en la teoría también se escriben en disco. Entonces, también se escriben en el momento? O se espera a que se suspenda, o se haga swap para escribirlas en el archivo de swap?

3. El bit modificado, se borra en algun momento? Actualmente lo estoy haciendo cuando se escribe en swap la página, pero tengo entendido que no es lo correcto.

4. Y una duda para las entregas en el laboratorio. Ví que recomendaron tener por consola que reciba como parámetro la ruta del archivo de configuracion en cada módulo para las pruebas y lo mismo para la IP. Es necesario esto? Tendríamos que agregarlo si es así.

**Comment by RaniAgus** [comment]
¡Buenas!

1. Ninguna de las dos, cito el enunciado (p.21):

> El tiempo de retardo de SWAP definido por archivo de configuración, al tener como objetivo simular la diferencia de velocidades al reemplazar páginas modificadas debido a tener que realizar un acceso extra a disco por escritura, no debe ser tenido en cuenta para las operaciones con Kernel previamente definidas.

2. Se espera a que se haga swap-out (ya sea por reemplazo o por suspensión) para escribirlas en el archivo de swap. Tengo entendido que en la teoría es igual aunque quizás algunos sistemas operativos escriban las páginas en Swap periódicamente a modo de optimización, pero no es algo que pidamos en el enunciado.

3. Sí, sería correcto borrarlo porque ese bit significa que la página se encuentra modificada respecto a lo que se encuentra en Swap. De todas formas, como mencionaba antes, para el TP solo vamos a escribir en Swap cuando haya que hacer un swap-out.

4. Como comentamos en la [guía de deploy](https://docs.utnso.com.ar/guias/herramientas/deploy.html#contar-con-los-config-de-las-pruebas), contar con los configs en el repo y pasarlo por parámetro es _altamente recomendado_ para agilizar los tiempos de entrega. La IP puede ir dentro del config.

Saludos

**Comment by RaniAgus** [comment]
> Ok, entonces para cualquier pedido del Kernel (Iniciar el proceso, suspenderlo, y finalizar) no se agregan retardos por swap? Solo se agregan para los reemplazos de páginas?

Exacto

> Entonces con agregarnos en una carpeta dentro del repo los configs que figuran en el documento de pruebas estaríamos? Y agregandole un campo IP_MODULO o algo del estilo para configurar más fácilmente la ip.

Sí, pueden agregarle al config los campos que crean necesarios.

Saludos

**Comment by pmdea** [comment]
Perfecto. Muchas gracias.
Tengo una duda más. Para CPU, Kernel y Memoria, hay algun momento en donde solos deban finalizarse los procesos de sus módulos? O sea, alguna condición en donde por ejemplo, el módulo de Memoria, tenga que finalizar todos sus procesos y terminar la ejecución. 

Por el momento los 3 módulos nunca finalizan al menos que forcemos la finalizacion de alguno y el resto, al detectar clientes desconectados, finalizan también limpiando sus estructuras.

**Comment by RaniAgus** [comment]
Nono, nunca finalizan a menos que se fuerce con `Ctrl`+`C` al terminar la prueba 😄

**Comment by pmdea** [comment]
Gracias! Cierro issue
