### ISSUE TITLE
Error al cerrar el txt

### ISSUE THREAD

**Issue by Daniel-Aizcorbe** [sisoputnfrba/foro#2798]
Hola, me surgió un error cuando hago `fclose(archivo_proceso)`, que es la última linea de la consola.
funciona todo pero al terminar me manda `corrupted size vs. prev_size`.

Tambien tengo problemas con `config_destroy()` que me tira un error `double free detected in tcache 2`

No es consistente, de a ratos tira uno u otro, a veces no dice nada

Probé con valgrind y lo mismo, de a ratos anda bien y a veces tira esos errores.

No pongo código porque realmente no hago nada especial con el config ni con el archivo txt asi que no se por que puede ser

**Comment by RaniAgus** [comment]
¡Buenas! Estaría bueno contar con un poco más de info para poder entender el problema, pero voy a hacer un esfuerzo...

Primero que nada, ¿están ejecutando `valgrind` con el flag `--leak-check=full` como sugiere la [guía](https://faq.utnso.com.ar/valgrind)? Me suena raro que no les esté mostrando nada ante ambos errores. También pueden probar de ejecutar Valgrind con el flag `-s` como suele sugerir al final para ver si no les está suprimiendo algo:
```
==5342== For lists of detected and suppressed errors, rerun with: -s
```

1. [Investigando un poco sobre el primer error](https://stackoverflow.com/a/49660707), parece ser un problema de manejo de memoria parecido a este: https://github.com/sisoputnfrba/foro/issues/2632#issuecomment-1120495292

Con Valgrind debería aparecer algo como:

```
==4412== Invalid write of size 1
==4412==    at 0x40053A: main (ej1.c:5)
==4412==  Address 0x51f1045 is 0 bytes after a block of size 5 alloc'd
==4412==    at 0x4C2B3F8: malloc (in usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4412==    by 0x40052D: main (ej1.c:4)
```

2. Sobre `double free`, también con Valgrind suele aparecer la línea en la que se hizo el `free()` por primera y segunda vez:

```
==5342== Invalid free() / delete / delete[] / realloc()
==5342==    at 0x483CA3F: free (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==5342==    by 0x10919C: main (main.c:9)
==5342==  Address 0x4a49040 is 0 bytes inside a block of size 7 free'd
==5342==    at 0x483CA3F: free (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==5342==    by 0x109190: main (main.c:7)
==5342==  Block was alloc'd at
==5342==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==5342==    by 0x48F338E: strdup (strdup.c:42)
==5342==    by 0x109180: main (main.c:6)
```

Acá los `free()` están en las líneas 7 y 9 (y el `malloc()`, en la 6).

Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

@Daniel-Aizcorbe te sirvió la respuesta de Agus? Necesitas mas info?

Saludos.-

**Comment by Daniel-Aizcorbe** [comment]
No pude replicar el error, dejó de pasar, volví a ejecutar con valgrind y ya no aparecen esos errores.
Gracias!
