### ISSUE TITLE
Error al ejecutar dos veces Consola al mismo tiempo

### ISSUE THREAD

**Issue by guidoreboredo-frba** [sisoputnfrba/foro#2799]
Hola! buenas noches,

Estamos ejecutando pruebas en el TP y estamos teniendo un problema que no logramos resolver. Los módulos comienzan correctamente, pero si queremos ejecutar dos consolas al mismo tiempo en distintas terminales arroja **"bash: ./bin/consola.out: Permission denied"**. 
Hasta ahora venimos probando creando distintos ejecutables o corriendo consola en múltiples VMs pero tenemos entendido que en la entrega esta funcionalidad debe ser aceptada por el programa. Ya buscamos bastante y aún no logramos dar con la solución. 

Intentamos ejecutar usando sudo antes del comando pero tampoco dio resultado. Intentamos también que los archivos log y config sean propios de cada ejecución y cambiar también el Script que ejecutaban para ver si era un problema de la gestión de Archivos en C pero tampoco, entiendo que el error viene directamente de consola.out.

Por favor, ¿podrían ayudarnos a ver cual puede ser el problema? 

Desde ya muchas gracias, 
Saludos

![Capture](https://user-images.githubusercontent.com/82243287/181867468-128c13d1-4e94-49ad-9c6c-db955916d4f9.PNG)

**Comment by RaniAgus** [comment]
¡Buenas! Yo revisaría los permisos de las carpetas y los archivos a los que accede la consola, quizás falte alguno. 

Pueden corroborarlo ejecutando en la consola `ls -l` (pueden encontrar un ejemplo en la [guía de bash](https://docs.utnso.com.ar/guias/consola/bash.html#moverse-entre-carpetas)).

Saludos

**Comment by guidoreboredo-frba** [comment]
Buenas, antes que nada gracias por la respuesta! 

El tema es que como se ve en la imagen arriba a la derecha, la consola está ejecutándose sin ningún problema. El error aparece cuando queremos ejecutar otra mas al mismo tiempo que la primera. Pero si ejecuto una sola consola funciona correctamente. 

Revisé y todos los archivos tienen todos los permisos, aun así seguimos con el mismo error.

Muchas gracias, 
Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

Por las dudas, podes poner el output del `ls -l`?
Otra cosa, tirale un `chmod +x` al programa por las dudas.

Saludos.-

**Comment by guidoreboredo-frba** [comment]
Ahí adjunto la imagen, le hice un chmod 777 a todo lo que usa el ejecutable. Configs, Logs, Scripts y el ejecutable.

Hice lo que me contabas pero aun asi no funcionó. 

Muchas gracias 
Saludos

![image](https://user-images.githubusercontent.com/82243287/181945782-34340229-9dc5-4b9a-97c9-db33dcef32aa.png)

![image](https://user-images.githubusercontent.com/82243287/181946861-837b23d3-1848-409c-bd80-97c839bbf85e.png)

![image](https://user-images.githubusercontent.com/82243287/181947188-644ba35b-0c91-4928-b6bb-56467f3535d2.png)

**Comment by RaniAgus** [comment]
¡Ahí está! El problema no eran los permisos, sino el owner:

![image](https://user-images.githubusercontent.com/39303639/181961709-a9d7066d-b001-4d47-b694-bfab94127629.png)

Lo más probable es que hayas clonado el repo con `sudo` (es decir, `sudo git clone https://github.com/sisoputnfrba/TU_REPO`) y, entonces, el directorio lo creó el usuario `root` (ya que fue `root` quien ejecutó ese comando). Como el owner del directorio es `root`, el usuario `utnso` no tiene permisos sobre ese directorio.

Una forma de solucionar este problema es hacer `sudo chown -R utnso:utnso /path/a/tu/directorio` para que el directorio (y todo su contenido) pase a ser del usuario `utnso`; aunque quizás la forma más sencilla de evitarlo es clonar el repo sin `sudo`.

Saludos

**Comment by guidoreboredo-frba** [comment]
Hola Como estás?

No cloné con SUDO, y si quiero cambiar el owner con el comando me devuelve esto: 
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set

De todas maneras lo raro es que *puedo ejecutar la consola sin problemas*. Lo que no puedo es ejecutarla dos veces al mismo tiempo. Digamos que por eso no creo que sea un problema del usuario, porque una vez me deja siempre ejecutar, sin sudo ni nada. 

Muchas gracias, 
Saludos

**Comment by RaniAgus** [comment]
Por lo que pude investigar, este mensaje:

```
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
```

Significa que [están rotos los permisos de `sudo`](https://askubuntu.com/a/452868). Según mencionan [acá](https://stackoverflow.com/a/19306929/14089741), **suele** ocurrir porque los permisos del archivo `/usr/bin/sudo` son seteados en 777.

Te aconsejo probar el TP en otra VM porque no encontré que haya alguna solución sencilla a eso 😕 

Avisanos si el error persiste. Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

@guidoreboredo-frba pudiste resolver el inconveniente con lo que te comento Agus?

Saludos.-

**Comment by guidoreboredo-frba** [comment]
Hola Como están? 

Perdón la demora, encontramos el problema o al menos una forma de solucionarlo que la cuento por si le sirve a alguien mas: 
El problema lo teníamos con los permisos de la carpeta shared, habíamos clonado el repo en una carpeta compartida entre windows y la VM y eso es por lo que todo quedaba bajo root y no nos permitía ajustar los permisos. Lo que hice fue clonar de nuevo el repo pero en una carpeta de la VM y después de eso funciono perfecto. 

Muchas gracias por el apoyo, 
Saludos!
