### ISSUE TITLE
Porcentaje CPU al correr las pruebas integrales

### ISSUE THREAD

**Issue by EspositoLucas** [sisoputnfrba/foro#2800]
Buenas . Estuvimos haciendo las pruebas integrales y todos los procesos finalizaron correctamente pero nos surgió una duda con respecto al porcentaje de cpu y  al uso de memoria al correr el htop . 

Al correrlas, kernel  se quedaba usando 5-10 % de cpu cuando terminaba  y usaba unos megas que no devuelve hasta que termina el programa . Esto es un problema o es normal que pase ? Porque capaz habría que hacer unos `free` o liberar algo que no se hace . Capaz en el caso de kernel , cuando finaliza una consola se queda esperando a que otra se conecte,podra ser que la espera activa aumente por ejemplo ?
Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

Un par de preguntas como para entender el contexto:
1.- Estan en la VM server o en la VM con entorno gráfico?
2.- Filtraron en htop para ver que efectivamente es el Kernel el que se queda usando el 5/10% o es otro proceso?
3.- Esto es solo cuando termina la ejecución? Cuando inician todo antes de mandar las consolas, como esta el uso de CPU por parte de los procesos?

Por otro lado, el tema del `free()` no tiene *nada* que ver con el uso de CPU, eso les va a repercutir en el uso de memoria (que lo pueden validar con Valgrind)

Saludos.-

**Comment by EspositoLucas** [comment]
@iago64 Buenas Damian 

1. Hicimos las pruebas en ambas pero el caso que te menciono paso en la server
2. Si, solo con ese proceso
3. Antes también estaba con ese porcentaje, se mantenía constante hasta que terminaba una consola y esperaba a otra . Sobre esto ultimo, esta situación se podría considerar espera activa aunque ese porcentaje se mantenga contante ? 

Saludos

**Comment by RaniAgus** [comment]
¡Buenas! ¿Tienen algún hilo con un `while(true)` que se ejecute sin importar lo que ocurra? Es decir, incluso aunque no haya ningún proceso activo. Si lo tienen, probablemente sea la razón por la que el porcentaje de uso de CPU no es 0% en esos casos.

Saludos

**Comment by EspositoLucas** [comment]
Si, en el hilo que se encarga de manejar las conexiones entre los clientes, en este caso las consolas con kernel . Entonces si esa es la razon,  no debería ser un problema, no es así? Porque kernel se tiene que a mantener siempre levantado para recibir a las consolas a menos que se finalice el programa voluntariamente 

Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

Pero si tienen un hilo aceptando conexiones nuevas, no deberia sumarles carga de CPU ya que el mismo se tendría que encontrar bloqueado en una operación bloqueante como es un `accept()`, estan seguros que no hay nada mas? Porque un 5-10% de CPU es **demasiado** para un proceso que no esta haciendo nada.

Saludos.-

**Comment by EspositoLucas** [comment]
Buenas . Si, efectivamente había algo mas que era un `while(true)` que aparentemente no finalizaba al terminar un proceso . Ese ciclo en kernel estaba  para poder calcular el tiempo que llevaba un proceso ejecutando y tener en cuenta ese tiempo en al planificación para ver si se tenia que suspender o no por ejemplo .  El problema también era que lo habíamos puesto como parte del inicio de los hilos de la planificación de largo, mediano y corto plazo, con lo cual hacia que se tuviera siempre corriendo ese calculo en el ciclo que consumía bastante CPU . Ahora parece estar funcionando bien porque ya no parece mas ese porcentaje del 5-10% al inicio y final del proceso . Cierro el issue pero si surge algún otro problema relacionado o el mismo, lo reabro y consulto . Gracias por las observaciones

Saludos
