### ISSUE TITLE
Comunicación de Kernel con Cpu y Memoria

### ISSUE THREAD

**Issue by Gabi314** [sisoputnfrba/foro#2801]
Hola. Nos surgieron dudas respecto a algunas cosas que envía y recibe Kernel:

1) En el enunciado dice lo siguiente:
> I/O(tiempo): Esta instrucción representa una syscall de I/O bloqueante. Se deberá devolver el PCB actualizado al Kernel junto al tiempo de bloqueo en milisegundos.

Las dudas son : el tipo de dato del tiempo debería ser colck_t o int? En cualquiera de los dos casos, kernel debería recibirlo por el puerto interrupt o por dispatch? Entendemos que por el primero pasan mensajes (char*) y por el segundo estructuras pcb.

2) También tenemos preguntas sobre las suspensiones: 

> Al suspenderse un proceso se enviará un mensaje a Memoria con la información necesaria y se esperará la confirmación del mismo.

- En el caso de suspensión y/o desuspensión, desde Kernel hay que enviar a Memoria un pid o un pcb entero? 
- Qué sería exactamente la confirmación de suspensión que llega de Memoria? Un mensaje?

Entendemos que capaz hay cosas que las podemos (y tenemos) que decidir nosotros, pero como no estábamos seguros en estos casos preferimos preguntar.

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- El tipo de dato puede ser el que gusten, tengan en cuenta que es un tiempo en milisegundos y despues el socket por el cual lo manden es indistinto, la idea de decirles que tengan 2 sockets fue para que no se compliquen sobrediseñando las cosas.

2.- De Kernel a memoria pueden mandar lo que les pinte siempre y cuando a memoria le alcance para poder suspender el proceso. Para des-suspender no tienen que mandar nada, simplemente van a llegar peticiones de páginas que van a tener que ir cargando a memoria.
La confirmación de suspensión es lo mismo, manden lo que gusten, puede ser tan simple como un ok y ya.

Saludos.-

**Comment by Gabi314** [comment]
Muchas gracias! Cierro el issue. Saludos!
