### ISSUE TITLE
Problemas con el uso del bloqueo de recv

### ISSUE THREAD

**Issue by Gabi314** [sisoputnfrba/foro#2803]
Hola. Tenemos un problema con una función que estamos usando para bloquear hilos de kernel que quedan a la espera de códigos de operación de otros módulos. Cuando lo usamos, en el primer ciclo el hilo queda bloqueado a la espera de la operación y no ejecuta hasta ese momento. Pero cuando recibe algo no se deja de ejecutar el `while `a pesar de que en el segundo ciclo se vuelve a hacer un `recv `desde `recibir_operacion` y desde otro módulo no se vuelve a hacer `send`

```
int recibir_operacion(int socket_cliente, int cod_op)
{

	if(recv(socket_cliente, &cod_op, sizeof(int), MSG_WAITALL) > 0)
		return cod_op;
	else
	{
	
		return -1;
	}
}
```

```
void atender_interrupcion_de_ejecucion() {

while (1) {
	int cod_op;
	cod_op = recibir_operacion(socketCpuDispatch, cod_op);

	switch (cod_op) {	

	case I_O:
		...
		break;
	case EXIT:
               ...
		break;

	case INTERRUPT:
              ....
		break;

	default:
		//log_info(logger, "operacion invalida");

		break;
	}
	.....

	}
}
```

**Comment by RaniAgus** [comment]
¡Buenas! ¿Probaron de usar el [debugger](https://docs.utnso.com.ar/guias/herramientas/debugger) a ver qué devuelve `recibir_operacion()` en esos casos y si está ejecutando línea por línea de la forma que esperan en cada caso? Saludos

**Comment by iago64** [comment]
Buenas! Otra cosa importante a tener en cuenta, la info que mandan de un lado es la misma cantidad que reciben del otro lado?

Es decir si por ejemplo mandan un COD_OP de tipo uint32_t que son 4 bytes y despues un payload de 20 bytes, estan recibiendo los 4 bytes del COD_OP y despues los 20 del payload? Porque me suena a que el problema que tienen es que estan teniendo mucha info en el buffer y por eso les empieza a ciclar.

Una buena forma de ver que onda es como les dijo Agus, usando el debuguer y pasandose antes del `recv()`.
Incluso si quieren ver bien el valor del recv() pueden hacer un minimo ajuste:

```c
int recibir_operacion(int socket_cliente, int cod_op)
{
        int valorRecv = recv(socket_cliente, &cod_op, sizeof(int), MSG_WAITALL);
	if(valorRecv  > 0)
		return cod_op;
	else
	{
		return -1;
	}
}
```

Saludos.-

**Comment by Gabi314** [comment]
Holaa! Al final debuggeamos y resultó ser un problema del tamaño que venía de la serialización de los datos. Muchas gracias!
