### ISSUE TITLE
Error de Sockets al volver a conectar los modulos. 

### ISSUE THREAD

**Issue by guidoreboredo-frba** [sisoputnfrba/foro#2804]
Hola Buenas tardes! 

Estamos teniendo un erro cuando cerramos los modulos o se caen por algún error. Los puertos quedan como **tomados** o no se como explicarlo, pero luego de que suceda eso no los podemos volver a ejecutar hasta pasados unos minutos, que entiendo que el SO está limpiando las conexiones y ahí todo vuelve a funcionar correctamente. 
Esto sucede aunque matemos el programa con ctr+c compilemos nuevamente y re-ejecutemos todo. 

El orden de ejecución de los modulos es : Memoria -> CPU -> Kernel -> Consola/s . Y el orden de finalización DEBE ser el opuesto (Comenzando por la/s Consola/s). Si no lo terminamos en ese orden exacto sucede el error mencionado. Debajo dejo algunas de las capturas donde se puede ver el servidor de memoria corriendo exitosamente pero el Kernel diciendo que no se encuentra el servidor. A su vez, dejo una captura del LSOF -i que muestra como si memoria tuviera levantado un puerto distinto al configurado siempre que tenemos este problema, y no entendemos por qué. 

En todos los main, tenemos una función de terminar programa que ataja el ctrl+c, y termina las conexiones. No se si tenemos algo mal ahí

```
//Finalizacion por interrupción ctrl + c
void sighandler(int s){

	if(conexionAMemoria){
		liberar_conexion(&conexionAMemoria);
	}

	terminar_programa();
	exit(0);
}

void terminar_programa(){
	matar_hilos();
	config_destroy(config);
	log_debug(logger,CONFIGURACION_CERRADA);
	liberar_conexion(&conexionAMemoria);
	close(serverDispatch);
	close(serverInterrupt);
	log_debug(logger,TERMINANDO_EL_LOG);
	log_destroy(logger);

}
```

Y por otro lado agregamos algo que vi en un incidente si no me equivoco, al crear el socket: 
```
	// Ahora vamos a crear el socket.
	int socket_cliente = 0;
	socket_cliente = socket(server_info->ai_family, server_info->ai_socktype, server_info->ai_protocol);
	int yes = 1;
	setsockopt(socket_cliente, SOL_SOCKET, SO_REUSEADDR, &yes, sizeof yes);
```

<img width="995" alt="image" src="https://user-images.githubusercontent.com/82243287/182926523-1438de9d-93f7-40b2-b521-205fb2e6104d.png">
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/82243287/182926989-0fa6cbc8-3ef0-4953-9aaf-8c0d04e5d858.png">

**Comment by RaniAgus** [comment]
¡Buenas! Para estar seguro, ¿las líneas con `setsockopt()` las agregaron después de crear el `socket()` y antes de `bind()`earse al puerto?

**Comment by FacuBazzi** [comment]
Según el post de stackoverflow que menciona la guía de despliegue, puede ser necesario hacer el setsockopt() tanto con SO_REUSEADDR como con SO_REUSEPORT, y según veo ustedes lo hacen solo con el primero.

En mi TP lo hicimos así y funcionó joya:
. . .
socket_servidor = socket(p->ai_family, p->ai_socktype, p->ai_protocol);
setsockopt(socket_servidor, SOL_SOCKET, SO_REUSEADDR, &(int){1}, sizeof(int));
setsockopt(socket_servidor, SOL_SOCKET, SO_REUSEPORT, &(int){1}, sizeof(int));
. . .

No entiendo mucho del tema pero tal vez sea eso! Suerte :D

**Comment by iago64** [comment]
Buenas! Cómo va?

Para traer un poco de tranquilidad, si pasa eso de que el SO no les suelta el socket y hay que esperar unos minutos para correr la siguiente prueba no es el fin del mundo, se espera y se corre la siguiente prueba, por lo que si es lo único que les queda por parcehar revisenlo para tranquilidad de uds, pero si no, traten de pulir el resto de pruebas 😉 

Saludos.-

**Comment by guidoreboredo-frba** [comment]
Hola! 

Antes que nada muchas gracias por sus respuestas. Sobre todo por la tranquilidad que nos dan dado el poco tiempo que queda para la entrega. Por suerte, solo tenemos que enfocarnos en resolver detalles como este. 

Hoy justo voy a estar muy complicado para revisarlo, pero por la tarde revisare en detalle los comentarios para ver si puedo resolverlo antes de la entrega. 

Muchas gracias nuevamente a todos, 
Saludos
