### ISSUE TITLE
Quiero armar grupo y me faltan integrantes. 

### ISSUE THREAD

**Issue by esigma5** [sisoputnfrba/foro#2805]
Donde esta el issue para buscar grupo?

Gracias!

**Comment by iago64** [comment]
Lo acabas de crear 😄 
Importante como siempre, no se olviden de que el foro es público, traten de no publicar números de celulares si no quieren recibir spam super directo 😉

**Comment by GabrielNicolasLopez** [comment]
Buenas!
Somos por ahora 3 que ya la cursamos anteriormente. Vamos con todo a aprobar! Buscamos integrantes preferentemente con experiencia previa.

Dejo el correo para contacto: glpez@frba.utn.edu.ar

**Comment by agussaban** [comment]
Buenas, por ahora somos un grupo de 3. Buscamos 2 personas más para conformar el grupo, principalmente que se comprometan a meterle con el tp y tengan tiempo para juntarse en la semana.

Dejo mi mail para que me escriban: asaban@frba.utn.edu.ar

**Comment by MatiasRosbaco** [comment]
Buenas, tenemos un grupo de 4 personas. Buscamos 1 persona para cerrar el grupo, necesitamos personas comprometidas a llegar hasta el final con el TP , que sean responsables y respondan por el grupo privado de wpp y que tengan tiempo para codear/aportar en el tp.

Interesados me pueden escribir al mail: mrosbacobertrand@frba.utn.edu.ar

**Comment by AgustinTejera** [comment]
Buenas gente 😄! 
Estamos buscando un integrante mas, actualmente somos 4 en el equipo! 

Valores que fomentamos en el equipo y buscamos en el futuro integrante : 
- Estar comprometido con la materia, 
- Ganas de meterle al TP y de codear hasta que salga,
- Conocimiento en C,
- Responder activamente en las comunicaciones del equipo,
- Participar de los encuentros para avanzar con el TP,
- Trabajar en equipo e individualmente, responsablemente.
- Seguimiento del trabajo en la herramienta Trello,
- Uso de canales como Discord, Meet, Wsp, etc para comunicacion constante.

Interesados comunicarse a 😉 : atejera@frba.utn.edu.ar

**Comment by ayllon89** [comment]
Hola!,
Somos 2 recursantes que llegamos a la entrega final del cuatri pasado, pero no llegamos con las correcciones que nos dijeron para la ultima entrega. Por lo que tendriamos una buena base para empezar el TP, si sabes C genial si no no pasa nada, te guiamos para que aprendas. Nos vamos a estar juntando minimamente una vez a la semana por discord para ver avances, por lo que si no vemos alguno te vamos a tener que dar de baja del grupo.
Si este cuatri le vas a meter a la materia y sobre todo a codear, escribime por favor
Un abrazo

**Comment by rami-nava** [comment]
Buenas, somos un grupo de 3 que esta buscando 2 integrantes mas para completar el grupo que estén dispuestos a comprometerse con el TP.
Si alguno esta interesado, acá dejo mi mail: ramnavarro@frba.utn.edu.ar

**Comment by alecaragiulo** [comment]
Buenas!  Somos un grupo de 2 buscando integrantes para completar el grupo, ambos integrantes contamos con disponibilidad durante la semana. Cursamos la materia los miércoles por la noche.
Si tenés algún interés en formar grupo, dejo el mail institucional : acaragiulo@frba.utn.edu.ar

**Comment by Casorey** [comment]
hola! soy recursante con buena disponibilidad, curso los sabados a la mañana, ando buscando grupo. Quiero aprobar la materia este año si o si y prefiero un gropu que se junte seguido, dejo mi mail: casorey1@gmail.com

**Comment by dpoveda** [comment]
Hola buenas, somos tres personas en el grupo, estamos buscando dos personas mas que sean responsables y no dejen el grupo a mitad de cursada, buscamos gente que preferentemente este enfocado en darla este cuatri y que tenga buena disponibilidad entre la semana y el finde, dos de nosotros cursamos sabados por la mañana. Dejo mi email a los interesados: dpoveda@frba.utn.edu.ar

**Comment by lewislee0920** [comment]
Buenas! Busco grupo para el TP. Curso los martes y sabado a la mañana y tengo bastante tiempos vacios para este materia. Dejo mi mail para contacto: jlee@frba.utn.edu.ar

**Comment by facu777** [comment]
Buenas, busco grupo para el tp. mi mail es ffranco@frba.utn.edu.ar

**Comment by vrojas2022** [comment]
Buenas, no tengo grupo, estoy disponible, mi mail es vrojas@frba.utn.edu.ar. Curso los Miercoles a la noche. Hago otra materia.   Disponible para juntarnos semana, finde.

**Comment by federicotortolano** [comment]
Buenas! Somos 2 personas buscando grupo, cursamos los miercoles a la noche y tenemos disponibilidad para juntarnos. Dejo mi mail: ftortolano@frba.utn.edu.ar

**Comment by camilamarinio** [comment]
Buenas, somos un grupo de 4 personas , estamos en busca de una personas mas que  sea responsable y esté comprometida con la materias ,buscamos gente que esté con la mejor disposición para dar la materia esté cuatri y que tenga buena disponibilidad entre la semana y el finde, dos de nosotros cursamos sabados por la mañana. Dejo mail mcamila28@live.com

**Comment by Munetakachan** [comment]
Buenas, busco grupo mi mail es dyamada@frba.utn.edu.ar
Estoy cursando los lunes y además curso una electiva.
Disponible para los findes y durante la semana también

**Comment by andreaavalos99** [comment]
Hola, estoy en busca de integrantes para armar un grupo! Si tiene disponibilidad en la semana para ver el tp mejor. 
Dejo mi email para que se comuniquen: andreaavalos99@gmail.com

**Comment by parodi1998** [comment]
Buenas, somos 2 recursantes, buscamos gente para completar el grupo y hacer el TP este cuatri. cursamos lunes a la noche, estairua buenoq ue tengan disponibilidad los sabados a la mañana, y en la semana en lo paosible, apra juntarnos seguidos y ver el progreso dle TP.
mi mail jparodi@frba.utn.edu.ar

**Comment by istadius** [comment]
Buenas somos dos recursantes y programadores, cursamos sábados a la mañana y buscamos completar el grupo de preferencia con recursantes o gente que ya tenga experiencia con C.  
istadius@frba.utn.edu.ar

**Comment by FeliMattei** [comment]
Buenas, estoy buscando gente para armar un grupo, es la primera vez que la curso pero se el tiempo y dedicación que conlleva el TP por lo que busco personas comprometidas.
Este cuatrimestre me anoté únicamente a dos materias para dedicarle de lleno. A quien le interese mandeme un mail a fmattei@frba.utn.edu.ar

**Comment by IESTomasAraujo** [comment]
Buenas, estoy buscando Grupo comprometido para desarrollar el tp de Sistemas Operativos. Tengo conocimientos en C asi como Hilos, semaforos y commons-libraries ( utilizacion de collections ), entendimiento de la funcion mmap y msync . He recursado la materia y tengo ganas de aprobarla este cuatrimestre si o si. 
Mi numero de contacto es : 1160272693.  mi mail academico : taraujo@frba.utn.edu.ar
Desde ya muchas gracias.

**Comment by GreenGeer** [comment]
Alo alo , soy Germán, que más agregar? Después de todo lo que se dice arriba y abajo, vengo en busca de un Equipo, tengo buena disponibilidad horaria cursando los sábados a la mañana, conocimientos en GIT, C, hilos, semáforos. 
Dejo mi contacto: [gvautier@frba.utn.edu.ar](url)
Les deseo una exitosa cursada a todos, aprendiendo del error y de los demás.

**Comment by Ignaciofmunoz** [comment]
busco grupo soy recursante, ignacio40309782@yahoo.com

Saludos!

**Comment by facu777** [comment]
Buenas. Estoy en busqueda de un grupo, soy recursante, ya repase el  tp0. email: ffranco@frba.utn.edu.ar

**Comment by LucasMaspero** [comment]
Buenas! Nos falta un integrante para nuestro grupo. Dejo mi mail para el que **quiera sumarse y tenga intenciones de aprobar la materia y aportar al equipo**. Mail: lmaspero@frba.utn.edu.ar

**Comment by Rocio-20** [comment]
Hola! Nos faltan 2 personas para completar el grupo, buscamos personas que puedan aportar al equipo.
Mi mail es rcopa@frba.utn.edu.ar

**Comment by MatiasRosbaco** [comment]
Buenas, nos falta un integrante del grupo, necesitamos a una persona comprometida a aprobar el tp, que se pueda reunir al menos una vez a la semana (preferiblemente los miercoles) y que tenga buena comunicacion en el grupo de wpp. Con el grupo ya empezamos a armar el tp, les dejo mi mail para que se comuniquen: mrosbacobertrand@frba.utn.edu.ar

**Comment by LucasK237** [comment]
Buenas. Estoy en busqueda de grupo. Soy recursante.
email: lucask237@gmail.com
Saludos!

**Comment by martinbrustti** [comment]
Buenas, nos falta un integrante. Buscamos a una persona responsable. Email: mbrustti@frba.utn.edu.ar

**Comment by AGanem** [comment]
Hola!
Estamos en búsqueda del quinto integrante. 
Somos recusantes, no llegamos a la entrega porque se nos rompió el tp unos días antes. Me pueden escribir a abdulganem@gmail.com

**Comment by ayllon89** [comment]
Buenas!,
Tenemos casi mitad del TP hecho, debido a que este ultimo TP se parece al del cuatrimestre pasado. Si hiciste el TP0 escribime a layllonzelaya@frba.utn.edu.ar y te sumamos al grupo.
Un saludo
Luis

**Comment by SantiagoBlastre00** [comment]
Buenas tardes! Estoy buscando grupo para el TP, tengo conocimiento basico de C++ y algo de GIT.

MAIL: sanblastre@gmail.com

**Comment by nachodcortes** [comment]
Buena estoy buscando grupo! Somos 2 personas, tenemos conocimiento de C++ y de GIT.
Mail: nachocortes250@gmail.com

**Comment by SantiagoBlastre00** [comment]
> Buena estoy buscando grupo! Somos 2 personas, tenemos conocimiento de C++ y de GIT. Mail: [nachocortes250@gmail.com](mailto:nachocortes250@gmail.com)

same

**Comment by alejandro-mattioli-frba** [comment]
Hola, estoy sin grupo. Tengo casi nada de experiencia con C, no tengo inconvenientes para programar pero si necesito entender como empezar, con otras materias no me ha pasado pero en esta necesito de un grupo que me acompañe para entender y con el que pueda contar para pedir ayuda, estoy pidiendo mucho, lo sé, pero en serio necesito ayuda y quiero sacarme la materia del **** de encima. amattioli@frba.utn.edu.ar

**Comment by Mathy977** [comment]
Hola a todos! Alguien quedó sin grupo? Somos 2 con conocimientos de programación y git y nociones de C además que operativos es la única materia que hacemos. 

Mi mail srabahia@frba.utn.edu.ar

**Comment by MaiiCardenas** [comment]
Holis! Estoy buscando grupo! mi correo es cardenasmailen@gmail.com
