### ISSUE TITLE
Problemas con la extracción de archivos

### ISSUE THREAD

**Issue by Gabi314** [sisoputnfrba/foro#2806]
Hola. Quiero instalar la vm pero al extraer los archivos me salta este error con el primero. No sé qué puede ser. Solo pasa con el primero. 
![image](https://user-images.githubusercontent.com/82108679/185244262-6f1184c1-7ab0-4d28-ab49-45cfd9136a30.png)

**Comment by iago64** [comment]
Buenas! Cómo va?

La VM esta separada en 6 partes para que sea mas "ligera" la descarga si tienen una conexión limitada, para extraerla tienen que tener las 6 partes en el mismo directorio y por lo que veo en la foto solo tenes el primero.

Saludos.-

**Comment by Gabi314** [comment]
Lo intenté con las otras 5 partes en el mismo directorio y se pudo extraer la primera Dami. Muchas gracias!
