### ISSUE TITLE
La VM no inicia correctamente

### ISSUE THREAD

**Issue by Gabi314** [sisoputnfrba/foro#2807]
Buenas. Perdón por molestar de nuevo. Pude crear la vm desde VirtualBox pero al iniciarla se me queda colgada en una pantalla
![image](https://user-images.githubusercontent.com/82108679/185267483-b712f359-bee4-4ca7-98a5-6f08e4f6f06c.png)
Justo después de eso se queda así
![image](https://user-images.githubusercontent.com/82108679/185267533-d08fd19d-e8bf-4e5a-b911-e2b899962032.png)
Edit: Me olvidé de poner la información de la máquina.
![image](https://user-images.githubusercontent.com/82108679/185270362-bedd43a4-e464-43b9-a2f9-3bf2c2c42510.png)

**Comment by iago64** [comment]
Buenas! Cómo va?

Solo para arrancar a setear algunas cositas:

1.- Traten de no subir screenshots a menos que sean 100% necesarios
2.- Hay un hermoso template de issue para los problemas con las VMs que pide algunos datos que nos pueden ayudar a resolver este tipo de inconvenientes.

A priori te recomiendo que sigas el paso a paso de la guía de como [Conseguir un entorno Linux](https://docs.utnso.com.ar/primeros-pasos/entorno-linux.html#descargar-virtualbox), la mayoria de los problemas comunes estan remarcados en las advertencias 😄 

Saludos.-

**Comment by Gabi314** [comment]
1. - Perdón por las screens. Pensé que en este caso eran necesarias porque tal vez tenía algo que me falte habilitar o deshabilitar en la parte inferior derecha al iniciar la vm. Voy a tratar de evitarlas.
2. - Sinceramente no lo leí esta vez 

No había revisado la advertencia que decía 

> En caso de no poder iniciar la VM en Windows (o que ande muy lento), es probable que tengan habilitado Hyper-V, un software de virtualización que no es compatible con VirtualBox.
> 
> De ser así, les recomendamos primero leer [cómo deshabilitar Hyper-V](https://docs.microsoft.com/es-es/troubleshoot/windows-client/application-management/virtualization-apps-not-work-with-hyper-v)

Quise deshabilitar Hiper-V pero no aparecía en "Características de Windows" y al intentar deshabilitarlo desde PowerShell aparece esto

```
PS C:\WINDOWS\system32> Disable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V-Hypervisor                Disable-WindowsOptionalFeature : Feature name Microsoft-Hyper-V-Hypervisor is unknown.
En línea: 1 Carácter: 1
+ Disable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Disable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.DisableWindowsOptionalFeatureCommand

PS C:\WINDOWS\system32>
```
Sin embargo, en "Informacion del sistema" sí aparece de esta manera

```
Hyper-V - Extensiones de modo de monitor VM	Sí
Hyper-V - Extensiones de traducción de dirección de segundo nivel	Sí
Hyper-V - Virtualización habilitada en Firmware	Sí
Hyper-V -Protección de ejecución de datos	Sí
```
Aunque según el tutorial de Microsoft debería encontrarme también con 

> Se ha detectado un hipervisor. No se mostrarán las características necesarias para Hyper-V.

Sinceramente no estoy seguro de si cuento o no con Hyper-V, es como si contara con extensiones y otras herramientas del mismo pero no tengo el Hyper-V propiamente dicho. También me parece raro que no figure en "Características de Windows"

**Comment by RaniAgus** [comment]
¡Buenas! Esta línea:
```
Disable-WindowsOptionalFeature : Feature name Microsoft-Hyper-V-Hypervisor is unknown.
```
Dice que tu instalación de Windows no reconoce la feature `Microsoft-Hyper-V-Hypervisor`. Esto significa que no cuenta con Hyper-V, por lo que ese no es el problema. 

Quizás tenga algo que ver con la aclaración que aparece arriba del video: las nuevas VMs son de **64 bits**, por lo que debemos elegir ese núcleo al crearla en VB. 😄 

Saludos

**Comment by Gabi314** [comment]
Holaa. Intenté con 64 bits y funcionó. Muchas gracias!! No se me había ocurrido.

No encontré la aclaración sinceramente pero debe ser porque soy medio miope jajaj. Cierro el issue
