### ISSUE TITLE
Problema VirtualBox con Procesador M1

### ISSUE THREAD

**Issue by agussaban** [sisoputnfrba/foro#2808]
Buenas a todos!

Estoy intentando instalar la VirtualBox y veo que no es compatible con el chip M1 de Apple. Quería saber si alguien tiene el mismo problema y sabe cómo solucionarlo.

Muchas gracias!

**Comment by LeandroCarbajales** [comment]
Buenas!
En la [guía para conseguir un entorno Linux](https://docs.utnso.com.ar/primeros-pasos/entorno-linux.html) el primer Spoiler muestra un apartado con varios links y una guía para quienes tienen M1 y por lo tanto necesiten una alternativa a VirtualBox.

Saludos!
       Lean

**Comment by agussaban** [comment]
Buenísimo Lean, voy con esta alternativa entonces, mil gracias!

**Comment by LeandroCarbajales** [comment]
Genial @agussaban !
Si te resolvió la duda podés cerrar el issue :)

**Comment by agussaban** [comment]
Hola Lean, estuve intentando y la realidad es que todavía no pude resolver el problema. Puedo instalar la máquina virtual de Ubuntu 22.04 en UTM, pero después no puedo instalarle todas las herramientas necesarias para el TP (Eclipse, vscode, etc.). 
Asi que si alguien está en la misma que yo y sabe cómo darme una mano, se agradece mucho :)

**Comment by RaniAgus** [comment]
︎¡Buenas! ¿Cómo va?

¿Podrías ser más específico sobre _"no puedo instalarle todas las herramientas necesarias para el TP"_? O sea, ¿aparece algún mensaje de error sobre el que nos podamos guiar? ¿Al ejecutar qué comando de los scripts?

Quizás haya algo en lo que podamos ayudar.

Saludos

**Comment by RaniAgus** [comment]
Ahhhh, creo que entendí lo que puede haber pasado.

Entre los minutos 7:17 y 8:47 se explica una forma de instalar una interfaz gráfica, pero en nuestro caso no hace falta seguir ese paso ya que el script `interfaz-grafica.sh` se encarga de instalar otro entorno (más liviano) 😅 

Probemos si se resuelve siguiendo el tutorial solo hasta el minuto 7:17 y luego ejecutando los scripts. De ser así, pondré un aviso aclarando que hay que omitir esa parte.

> Nota al pie: el mensaje que aparece no es un error en sí, solo es un warning diciendo que estás intentando instalar un display manager teniendo ya uno, lo cual tiene sentido ya que primero instalaste el entorno gráfico de Ubuntu (que ya viene con otro display manager y un desktop environment más pesado). 👍🏻

**Comment by agussaban** [comment]
Ahi volví a hacer todo desde cero y después de iniciar sesión con el usuario creado, ejecuté los scripts.
<img width="1440" alt="Captura de Pantalla 2022-08-30 a la(s) 12 45 58" src="https://user-images.githubusercontent.com/82107683/187482798-5e8ef5c9-b559-43e0-9523-e4930181ef0a.png">

Me tira todo eso, y cuando le doy reboot me vuelve a pedir usuario y contraseña, pero no arranca el entorno.

<img width="1440" alt="Captura de Pantalla 2022-08-30 a la(s) 12 52 15" src="https://user-images.githubusercontent.com/82107683/187483346-4d4faa8d-ebfa-4b50-b704-5a27fa9ba104.png">

**Comment by RaniAgus** [comment]
> Ahi volví a hacer todo desde cero y después de iniciar sesión con el usuario creado, ejecuté los scripts.

> Me tira todo eso, y cuando le doy reboot me vuelve a pedir usuario y contraseña, pero no arranca el entorno.

Fijate que te faltó agregarle el flag `-qO-` a `wget`, tal como aparece en el readme del repo.

> Sumo algo más que quizás sirve, en el video me hace instalar tasksel y cuándo veo que es lo que puedo usar con esa herramienta me aparece esto:

**Comment by agussaban** [comment]
Claro si, me olvide de comentar esa parte. Primero lo hice de esa forma, pero me decía esto
<img width="832" alt="Captura de Pantalla 2022-08-30 a la(s) 18 07 01" src="https://user-images.githubusercontent.com/82107683/187543382-4b082a86-53dd-4be0-8041-120ddccbf122.png">

**Comment by RaniAgus** [comment]
Qué raro, ¿es posible que estés usando el cero `-q0-` en vez de la letra O mayúscula `-qO-`?

**Comment by agussaban** [comment]
Era ese el error, no lo puedo creer. Ahi me inició con la interfaz gráfica de la cátedra. Lo que me está pasando ahora es que no me abre Eclipse (VsCode si, es medio raro), y cuando quiero acceder por ejemplo a la carpeta de descargas, me tira este mensaje
<img width="731" alt="Captura de Pantalla 2022-08-30 a la(s) 19 21 08" src="https://user-images.githubusercontent.com/82107683/187554030-07ea8ec9-87a6-4316-86ab-0a3c8572471b.png">

Me imagino que es porque yo estoy iniciando con mi usuario personal, y no con el de utnso. Hay alguna forma de iniciar con utnso?

**Comment by RaniAgus** [comment]
Oops, eso no debería pasar, mil disculpas

A la izquierda del explorador, en donde aparecen las carpetas `Documents`, `Downloads`, `Music`, `Pictures` y `Videos`, en realidad hay accesos directos. De momento te aconsejo borrarlos haciendo click derecho > `Remove Shortcut`:

![image](https://user-images.githubusercontent.com/39303639/187556138-75a58c47-3496-4972-ade1-f1bcc6705e13.png)

Sobre Eclipse, ¿simplemente no abre sin ningún mensaje de error?

**Comment by agussaban** [comment]
Nop, le hago doble click, le doy click derecho y "execute" y no hace nada. Iba a probar eliminarlo e instalarlo desde firefox, pero no se si se solucionará

**Comment by RaniAgus** [comment]
Dale, podemos intentarlo, dejo a mano el link de descarga: https://www.eclipse.org/downloads/packages/release/2022-06/r/eclipse-ide-cc-developers

**Comment by agussaban** [comment]
Ahi lo descargué, pasa que me descarga un .exe y no lo puedo ejecutar

**Comment by RaniAgus** [comment]
Oh, wait, hay que descargar uno de los paquetes para Linux:

![image](https://user-images.githubusercontent.com/39303639/187566403-d18fa5ee-6782-46d9-bb39-5d4f42611436.png)

¿Qué te aparece al ejecutar...?
```bash
dpkg --print-architecture
```
- Si dice `amd64`, hay que descargar la versión para "x86_64"
- Si dice `arm64`, hay que descargar la versión para "AArch64"

**Comment by agussaban** [comment]
Claro cuando tiro ese comando me dice que es arm64, entonces descargo ese archivo, pero es .dmg. Cómo hago para ejecutarlo?

**Comment by agussaban** [comment]
Acabo de poder bajar el Eclipse, asi que creo que ya tengo todo el entorno como para poder hacer el TP con esta compu. Muchísimas gracias, me dieron una mano gigante! Cierro el issue y ojalá le sirva a alguien más :)
