### ISSUE TITLE
TP0: Dudas sobre tipos de datos y uso de memcpy 

### ISSUE THREAD

**Issue by Gabi314** [sisoputnfrba/foro#2809]
Hola, pude resolver el tp0 sin problemas. Pero me quedaron muchas dudas respecto a algunas funciones de las `utils.c` . En resumen lo que me cuesta es darme cuenta cuándo debería usar una dirección de una variable y cuándo una variable propiamente dicha en `memcpy`. 
Además de usos de `void*` que no me terminan de cerrar. 

```
void* serializar_paquete(t_paquete* paquete, int bytes)
{
	void * magic = malloc(bytes);
	int desplazamiento = 0;

	memcpy(magic + desplazamiento, &(paquete->codigo_operacion), sizeof(int));
	desplazamiento+= sizeof(int);
	memcpy(magic + desplazamiento, &(paquete->buffer->size), sizeof(int));
	desplazamiento+= sizeof(int);
	memcpy(magic + desplazamiento, paquete->buffer->stream, paquete->buffer->size);
	desplazamiento+= paquete->buffer->size;

	return magic;
}
```

Por ejemplo acá. Por qué como segundo argumento de `memcpy` primero se reciben las direcciones de los enteros pero en el 3er caso se recibe el `stream` del `buffer `( que es de tipo `void*` y asumo que tiene un "conjunto de datos variados", no sus direcciones) ?

```
void enviar_mensaje(char* mensaje, int socket_cliente)
{
	t_paquete* paquete = malloc(sizeof(t_paquete));

	paquete->codigo_operacion = MENSAJE;
	paquete->buffer = malloc(sizeof(t_buffer));
	paquete->buffer->size = strlen(mensaje) + 1;
	paquete->buffer->stream = malloc(paquete->buffer->size);
	memcpy(paquete->buffer->stream, mensaje, paquete->buffer->size);

	int bytes = paquete->buffer->size + 2*sizeof(int);

	void* a_enviar = serializar_paquete(paquete, bytes);

	send(socket_cliente, a_enviar, bytes, 0);

	free(a_enviar);
	eliminar_paquete(paquete);
}
```
En este caso `mensaje` es una dirección de memoria por ser `char *` no? (al igual que una lista) 

```
void paquete(int conexion)
{
	char* leido;
	t_paquete* paquete = crear_paquete();
	while (1) {
		        .....
		        printf("%s\n", leido);
		        agregar_a_paquete(paquete, leido, sizeof(leido));
		        free(leido);
		    }
......
}
```
Acá uso la variable `leido` para mostrarla por pantalla y después llamo a `agregar_a_paquete() `
```
void agregar_a_paquete(t_paquete* paquete, void* valor, int tamanio)
{
	paquete->buffer->stream = realloc(paquete->buffer->stream, paquete->buffer->size + tamanio + sizeof(int));

	memcpy(paquete->buffer->stream + paquete->buffer->size, &tamanio, sizeof(int));
	memcpy(paquete->buffer->stream + paquete->buffer->size + sizeof(int), valor, tamanio);

	paquete->buffer->size += tamanio + sizeof(int);
}
```
Acá `valor` es `leido` pasado por parámetro. Pero ya se usó como variable en `paquete()`. Entonces en el `memcpy `se usaría como dirección o como variable nuevamente?

**Comment by iago64** [comment]
Buenas! Cómo va?

Algo importante de [`memcpy()`](https://man7.org/linux/man-pages/man3/memcpy.3.html) es que es una funcion super simple, copia memoria y nada mas.

Si vemos la firma de `memcpy()`, vemos que nos dice lo siguiente:
`void *memcpy(void *restrict dest, const void *restrict src, size_t n);`

El primer parámetro que recibe es **a donde** queres copiar
El segundo parámetro es **desde donde** queres copiar
El tercer parámetro te indica la cantidad de memoria a copiar.

Ahora cerrando un poco mas la respuesta a tu pregunta:  Siempre, siempre, siempre, a memcpy le vas a pasar una dirección de memoria (o en su defecto memcpy va a asumir que le pasas una dirección de memoria) y la misma por lo general la vas a tener en una variable de tipo puntero (void*, char*, etc) o podes tenerlo dentro de una estructura como por ejemplo el caso de `paquete->buffer->stream` donde stream es un void*. Los casos en los cuales le vas a pasar la dirección de una variable (con el &) es en aquellos casos que esa variable la tengas declarada en tu stack (por ejempo haciendo `int contador;`) y necesites modificarla y no puedas hacer por ejemplo `contador = 1;`

Saludos.-
