### ISSUE TITLE
No puedo iniciar la VM

### ISSUE THREAD

**Issue by FelipeAlborch** [sisoputnfrba/foro#2810]
Buenas! Hace unas semanas había configurado una VM que iba a ser donde iba a desarrollar el TP de este cuatri y me funcionaba. Hace poco, tratando de iniciarla de vuelta para configurar el entorno de VScode me esta mostrando un error que no estaría encontrando como solucionarlo.

![foroProblemaVM](https://user-images.githubusercontent.com/82057459/187264047-ed6b8d98-536d-48eb-961d-6a2863957d8f.jpeg)

**Comment by iago64** [comment]
Buenas! Cómo va?

Si estas usando las VMs nuevas ojo porque como aclaramos en el [doc](https://docs.utnso.com.ar/primeros-pasos/entorno-linux.html#crear-la-maquina-virtual), las nuevas son de 64 bits y por eso no te esta levantando.

Saludos.-

**Comment by Diego1939** [comment]
> 
Yo la tengo en 64 bits y me figura lo mismo

**Comment by Diego1939** [comment]
Yo estoy en 64 bits y me figura algo parecido
![Github](https://user-images.githubusercontent.com/103906211/187309584-57dbc999-91c9-4630-be20-47a7f27ee336.png)

**Comment by iago64** [comment]
Buenas! Cómo va?

Antes que nada, por favor no pongan solo screen del error, porque alguien mas no puede buscar por el error que se ve en el screenshot.

Por otro lado @Diego1939, tu error es diferente y si le prestas atención, te dice algo muy claro que es VERR_NEM_NOT_AVAILABLE, que casualmente si lo [buscas en el foro](https://github.com/sisoputnfrba/foro/issues?q=is%3Aissue+VERR_NEM_NOT_AVAILABLE) es un error que ya paso, y viene de la mano de que no tenes habilitada la virtualización en el BIOS de tu pc y de hecho te lo dice en la segunda linea del error donde dice AMD-V is disabled in the BIOS 😉 

Saludos.-

**Comment by FelipeAlborch** [comment]
Ahí pude solucionarlo. Muchas gracias por la ayuda!

**Comment by iago64** [comment]
Buenisimo @FelipeAlborch 

@Diego1939 Pudiste solucionar el problema?

**Comment by Diego1939** [comment]
@iago64 Si, ahi arreglé el problema
Muchas Gracias.

**Comment by iago64** [comment]
Buenisimo! Cerramos el issue :)
