### ISSUE TITLE
Dudas sobre logs y estructuras de Kernel 

### ISSUE THREAD

**Issue by Gabi314** [sisoputnfrba/foro#2811]
Hola! tengo una consulta sobre los logs:

> Cada módulo contará con un listado de logs mínimos y obligatorios, pudiendo ser extendidos por necesidad del grupo en un archivo aparte.

Es necesario separar los logs entre obligatorios y agregados nuestros? no podemos agregarlos al obligatorio? Serían dos archivos .log entonces?

También tengo un par sobre kernel:

1. Cada "unidad de trabajo" sería una instancia de una tarea específica del dispositivo? (asumo que en cada instrucción  de  I/O hay una sola tarea)

2.

>  la cantidad de unidades de trabajo será lo que deberá informarnos la CPU al momento de devolver un PCB por una instrucción de I/O. En estos dispositivos los procesos se encolan a medida que llegan las peticiones de I/O.

O sea, en kernel metemos la lista de instrucciones en el pcb, lo enviamos a cpu y después esta devuelve a kernel la cantidad de unidades de trabajo que salieron inicialmente  de las instrucciones?

**Comment by iago64** [comment]
Buenas! Cómo va?

Respecto a los logs, si, tienen que separarlos, ya que la idea de los logs obligatorios es ayudarnos a poder ordenar lo que vemos en las evaluaciones, si cada grupo agrega sus propios logs dificulta la corección.

Respecto a las preguntas del kernel:

La "Unidad de trabajo" es como ven en la teoría que por ejemplo un proceso se va a IO por 6, ese 6 es la cantidad de unidades de trabajo, lo que le agregamos al TP es el extra de que cada unidad de trabajo tiene un tiempo de retardo (para que pueda correr a un tiempo humano razonable)

Lo que tienen que hacer para el caso de I/O solamente es devolverle el PCB actualizado y ahi le dicen ademas que el motivo de vuelta es I/O y que son X unidades de trabajo, donde esa X es la cantidad que esta en la instrucción.

Saludos.-

**Comment by Gabi314** [comment]
Perfecto Dami. Muchas gracias!
