### ISSUE TITLE
Duda sobre dispositivos de I/O

### ISSUE THREAD

**Issue by dimoulasLucas** [sisoputnfrba/foro#2812]
Hola, que tal? Buen dia. Teniamos una pregunta con respecto a los dispositivos I/O que nos vendran en una lista por archivo de configuracion. Queria consultar si los tipos de dispositivos de I/O van a ser acotados o pueden existir una cantidad potencialmente infinita de dispositivos que se pueden ingresar. Esta consulta la hago para ver como representar el dato del dispositivo dentro de mis modulos. 

La cita que especifica esto es la siguiente (se encuentra en la pagina 13, subtitulo "Diagrama de estados", parrafo 2, 1a linea):

> Aparte se tendrá una lista de Dispositivos de Entrada-Salida, los cuales vendrán por archivo de configuración [...]

Para guardar el dato se me ocurrian dos soluciones. Primera solucion: en caso de ser potencialmente infinita la cantidad de dispositivos I/O, guardarlo como un string (char*), eso implicaria que a la hora de enviarlo por sockets, deberia especificar el tamanio del mismo a priori. Segunda solucion: en caso de tener una cantidad finita, podria crear una estructura de tipo enum, la cual seria mucho mas sencilla de comunicar entre los modulo por su tamanio fijo. Solo alcanzaria con agregar los tipos de dispositvos en el codigo.

Desde ya muchas gracias, aguardo su respuesta.

Lucas

**Comment by LeandroCarbajales** [comment]
Hola!
Conceptualmente la cantidad de dispositivos de I/O será variable en el sentido que una prueba se podría correr con 0 dispositivos de I/O mientras que otra se podría correr con 3, por lo que la cantidad no variará durante la ejecución, sin embargo no veo ideal usar un enum ya que no sabemos cuántos son antes de comenzar a ejecutar, si fuera el caso de que fuera una cantidad fija podríamos simplemente tenerlos listados en el enunciado y no como parte de la configuración. En ese sentido, para implementarlo recomendaría que se ayuden con las bibliotecas de las commons, podrían tener simplemente una lista o un diccionario indexado por nombre del dispositivo.
Con respecto a pasarlo por socket, para qué necesitarían pasar la información de los dispositivos del módulo Kernel por socket?

**Comment by dimoulasLucas** [comment]
Hola lean, cómo estás? Gracias por la respuesta.

Entiendo entonces que la cantidad de dispositivos que podrían existir es variable y no hay un set de dispositivos posibles. Me surgió una pregunta más: ¿qué pasaría en caso de que una consola quiera usar un dispositivo que el kernel no reconoce? ¿Habría un error?

Con enviar a través de sockets, me refiero a que la consola tendrá que enviar las instrucciones al kernel cuando logre conectarse y se haya reservado su memoria. En ese caso, si había una cantidad finita de dispositivos posibles, era más sencillo enviar la instrucción de IO con el argumento del dispositivo como un enum. Habrá que enviarlo entonces como un string, que es el formato en el que se lee del archivo. 

Aguardo tu respuesta.

Gracias

**Comment by LeandroCarbajales** [comment]
> Me surgió una pregunta más: ¿qué pasaría en caso de que una consola quiera usar un dispositivo que el kernel no reconoce? ¿Habría un error?

No es un error tipificado por lo que ese caso no va a ser parte de las pruebas, pero conceptualmente si, el "proceso" podría querer usar dispositivos de I/O que no existen.

> En ese caso, si había una cantidad finita de dispositivos posibles, era más sencillo enviar la instrucción de IO con el argumento del dispositivo como un enum

Claro no, el nombre del dispositivo que es parte de la instrucción puede quedar como string durante todo el ciclo de vida, cuando al Kernel le llegue el pedido desde la CPU para usar ese dispositivo, simplemente puede chequear ese string con los nombres de los dispositivos que tiene (o con las entradas de su diccionario si lo implementan con uno)

Queda más clara la idea?

Saludos!
          Lean

**Comment by dimoulasLucas** [comment]
Sí, quedó todo mucho más claro.

Muchas gracias y un saludo!

Lucas
