### ISSUE TITLE
Problema con Clang

### ISSUE THREAD

**Issue by FelipeAlborch** [sisoputnfrba/foro#2814]
Buenas! Estoy usando vscode para desarrollar el TP y constantemente me aparece este error: Please install [clang](http://clang.llvm.org/) or check configuration `clang.executable`
Vi que se podía resolver con "sudo apt install clang", pero a la hora de poner ese comando, se me queda trabado ya que me aparece este error: Fallo temporal al resolver «ar.archive.ubuntu.com»
No estaría sabiendo como poder solucionarlo

**Comment by RaniAgus** [comment]
¡Buenas! Para entrar un poco en contexto, ¿estás usando algún entorno Linux que hayamos compartido en la guía [Conseguir un entorno Linux](https://docs.utnso.com.ar/primeros-pasos/entorno-linux)?

Pregunto esto porque para compilar el TP usamos el compilador `gcc` (el que viene instalado en cualquier Linux), que tiene un par de features que no están en el compilador de MacOS (`clang`). De hecho, no deberías instalar `clang` en Ubuntu por ese mismo motivo.

Saludos

**Comment by FelipeAlborch** [comment]
Nop, no descargue mas que la VM y las guest additions. Asimismo, yo puedo compilar el TP a medida que agrego cosas, pero constantemente, cada vez que cambio de ventana en vscode, me aparece ese error arriba y tener que cerrarlo cada vez se vuelve un poco tedioso

**Comment by RaniAgus** [comment]
No logro reproducir el error en las VMs de la cátedra, ¿es posible que se deba a algún plugin extra relacionado con `clang` que hayas instalado sin querer?

**Comment by FelipeAlborch** [comment]
Pasa que yo el plugin extra lo trate de instalar en base al error que me aparecía, no antes. Pero no pasa nada, Agus. Busco por internet a ver si aparece algo. Muchas gracias igualmente

**Comment by iago64** [comment]
Cerramos el issue por inactividad, cualquier cosa el creador lo puede reabrir o pueden crear uno nuevo referenciando este issue.
