### ISSUE TITLE
Duda sobre estructura de parámetros

### ISSUE THREAD

**Issue by LautaroRobles** [sisoputnfrba/foro#2815]
El enunciado dice
>Cada línea tendrá el formato “INSTRUCCIÓN parámetros”. Los parámetros serán siempre valores numéricos separados por un espacio. Según la instrucción, cada línea puede tener entre 0 o 2 parámetros.

Lo que no queda claro es como se traduciría algunos parámetros a valor numérico. Por ejemplo:
el enunciado da como una instruccion posible ```SET AX 1``` donde SET podria transformarse en un enum y 1 se transforma en un int y esto se puede enviar facilmente al CPU, pero como se podría transformar "AX" en un numero, sería un enum de registros?
Lo mismo ocurre con la instruccion ```I/O DISCO 10```.

**Comment by RaniAgus** [comment]
¡Buenas! Tenés razón, hubo un error de redacción ahí ya que esos parámetros no son numéricos, vamos a corregirlo.

Los registros pueden ser un `enum` ya que en CPU se especifican los valores posibles, pero los dispositivos de I/O no ya que (como comentó Lean en #2812) los valores vienen por archivo de configuración.

Saludos

**Comment by LautaroRobles** [comment]
Muy bien, pero incluso leyendo #2812 no me queda claro.

En esa respuesta dice el comentario https://github.com/sisoputnfrba/foro/issues/2812#issuecomment-1241357287
>Cuando al Kernel le llegue el pedido desde la CPU para usar ese dispositivo, simplemente puede chequear ese string con los nombres de los dispositivos que tiene

O sea da a entender que la consola no hace nada con los strings que recibe por archivo, si no que se lo mandan así como vienen al Kernel y luego le este los envia a la CPU.

Yo entendia que la **Consola** al tener un parser **Parser** se deberían convertir los strings en Tokens y luego se envia las cadenas ya tokenizadas.

Por ejemplo, la consola enviaría una lista de:
```c
typedef struct {
	t_operator operator;
	t_list* parameters;
} t_instruction;
```
Donde los parametros son una lista de int (como el enunciado dice, parametros numéricos).

---

Pero para confirmar que entiendo a lo que se refieren.
Al recibir un archivo la consola realiza lo siguiente con los strings:
>Operadores
>- Si se recibe "SET", "ADD", ... -> se convierte a numeros usando enums

>Parametros
>- Si se recibe "1", "2", "3",..., "AX", "BX", "CX", "DX" -> se convierte a numeros usando atoi o enums
>- Si se recibe "Disco" -> se mantiene como un string

¿Quedaría así?

**Comment by RaniAgus** [comment]
Ambas implementaciones serían válidas. Quizás parsear en la consola sería más robusto al hacer pruebas ya que, si llega a haber una instrucción inválida, el error salta antes de enviarlas, pero si asumen que al momento de la evaluación todos los archivos de pseudocódigo que reciban van a tener instrucciones válidas también va a estar bien.

**Comment by LautaroRobles** [comment]
Listo, ya entendí.
