### ISSUE TITLE
Problema al Compilar en VSCODE

### ISSUE THREAD

**Issue by TomasGliozzo** [sisoputnfrba/foro#2816]
Buenas! Tengo un problema al intentar compilar los distintos directorios en vscode. Para compilar utilizo `make clear` y `make start` y luego me sale lo siguiente: 

`utnso@utnso:~/Documents/tp-2022-2c-HCF/cpu$ make start`
`gcc -g -Wall -DDEBUG -o "bin/cpu.out" obj/cpu_utils.o obj/cpu_thread.o obj/main.o obj/cpu_config.o -I../static/include -I./include -``L../static/bin -lstatic -lcommons -lpthread -lm`
`/usr/bin/ld: obj/cpu_thread.o:/home/utnso/Documents/tp-2022-2c-HCF/cpu/./include/cpu_config.h:18: multiple definition of ``CPU_CONFIG'; obj/cpu_utils.o:/home/utnso/Documents/tp-2022-2c-HCF/cpu/./include/cpu_config.h:18: first defined here
/usr/bin/ld: obj/main.o:/home/utnso/Documents/tp-2022-2c-HCF/cpu/./include/cpu_config.h:18: multiple definition of `CPU_CONFIG'; obj/cpu_utils.o:/home/utnso/Documents/tp-2022-2c-HCF/cpu/./include/cpu_config.h:18: first defined here
/usr/bin/ld: obj/cpu_config.o:/home/utnso/Documents/tp-2022-2c-HCF/cpu/./include/cpu_config.h:18: multiple definition of `CPU_CONFIG'; obj/cpu_utils.o:/home/utnso/Documents/tp-2022-2c-HCF/cpu/./include/cpu_config.h:18: first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:55: bin/cpu.out] Error 1

Interpreto que el compilador encuentra más de una definición del cpu_config.h cuando realemente no las hay en el mismo directorio. Por ahi es un tema del Makefile pero no sabría como solucionarlo. Por eso adjunto un archivo txt con el codigo del Makefile por si ayuda a solucionar el problema.
Desda ya muchas gracias. 
[Makefile.txt](https://github.com/sisoputnfrba/foro/files/9559575/Makefile.txt)

**Comment by RaniAgus** [comment]
¡Buenas! Por lo que veo el error dice que estás definiendo múltiples veces una variable global que está en el archivo `cpu_config.h`, en la línea 18:

```
obj/cpu_thread.o:/home/utnso/Documents/tp-2022-2c-HCF/cpu/./include/cpu_config.h:18: multiple definition of ``CPU_CONFIG';
```

Esto es un error de las versiones más recientes de `gcc`: se ve que ahora al definir una variable global en el header se comporta igual que al definir el cuerpo de una función ahí. O sea, al hacer `#include <cpu_config.h>` en dos archivos distintos, te vas a estar trayendo el código 2 veces, por lo que cuando luego el compilador junte ambos archivos va a saltar el error de `multiple definition of`.

Una solución rápida es mover la definición de la variable global al `.c` y declararla en el header como `extern` para que esté disponible en el resto de archivos. De hecho es un cambio que tuvimos que hacer en el tp0: https://github.com/sisoputnfrba/tp0/commit/9b3a907c20d19b0e65b54e9dda26a3edaa07e562

Saludos

**Comment by TomasGliozzo** [comment]
Solucionado! Muchas gracias. 

> ¡Buenas! Por lo que veo el error dice que estás definiendo múltiples veces una variable global que está en el archivo `cpu_config.h`, en la línea 18:
> 
> ```
> obj/cpu_thread.o:/home/utnso/Documents/tp-2022-2c-HCF/cpu/./include/cpu_config.h:18: multiple definition of ``CPU_CONFIG';
> ```
> 
> Esto es un error de las versiones más recientes de `gcc` (en las VMs del cuatri pasado no pasaba): se ve que ahora al definir una variable global en el header se comporta igual que al definir el cuerpo de una función ahí. O sea, al hacer `#include <cpu_config.h>` en dos archivos distintos, te vas a estar trayendo el código 2 veces, por lo que cuando luego el compilador junte ambos archivos va a saltar el error de `multiple definition of`.
> 
> Una solución rápida es mover la definición de la variable global al `.c` y declararla en el header como `extern` para que esté disponible en el resto de archivos. De hecho es un cambio que tuvimos que hacer en el tp0: [sisoputnfrba/tp0@9b3a907](https://github.com/sisoputnfrba/tp0/commit/9b3a907c20d19b0e65b54e9dda26a3edaa07e562)
> 
> Saludos

**Comment by RaniAgus** [comment]
Hago un follow up de este issue, hace poco agregamos una sección en docs que aclara en detalle cómo resolver este problema: https://docs.utnso.com.ar/guias/programacion/buenas-practicas#%C2%BFy-las-variables-globales
