### ISSUE TITLE
Problema para conseguir el archivo vdi de la VM

### ISSUE THREAD

**Issue by FelipeAlborch** [sisoputnfrba/foro#2817]
Hola, buenas! Estoy teniendo problemas con la nueva VM de Xubuntu. Descargue los 6 archivos xfce. Los tengo todos en el Escritorio de mi ordenador, pero no estaría sabiendo como hacer para obtener el vdi y poder usar, finalmente, la VM

**Comment by RaniAgus** [comment]
¡Buenas! En la [guía para conseguir un entorno Linux](https://docs.utnso.com.ar/primeros-pasos/entorno-linux.html#descargar-virtualbox) se explica cómo descomprimir el vdi, verificar la descarga y crear la VM.

Saludos

**Comment by FelipeAlborch** [comment]
Ahí estuve siguiendo los pasos. Descargue las 6 partes devuelta como un .zip, pero a la hora de descomprimir los archivos vuelvo a lo mismo. Me habían comentado que cuando descomprimiera los archivos, iba a tener que descomprimir otro para obtener el vdi, pero por el momento solo obtuve esto:

![Uploading fotoProblema.jpeg…]()

**Comment by RaniAgus** [comment]
Claro, lo que se encuentra en Drive es el vdi comprimido en 6 partes en formato `7z` (que es otro formato de compresión como `rar` o `zip`.

Para descomprimirlo abrí xfce.7z.001 con WinRar.

**Comment by FelipeAlborch** [comment]
Perdón Agus que siga mandando dudas con esto. Ahí lo abrícon WinRar pero me aparece este error:

![WhatsApp Image 2022-09-14 at 14 53 17](https://user-images.githubusercontent.com/82057459/190227283-76c26aa7-c02c-4a9c-9b22-28e06e86bcd5.jpeg)

De todas formas, cuando seleccione la opción "Extrae en" se me crea una carpeta con el nombre del archivo, vacía, en el mismo directorio

**Comment by iago64** [comment]
Buenas!

Otra opción que podes probar es usar [7Zip](https://www.7-zip.org/) que es otra herramienta para lo mismo.

Saludos.-

**Comment by FelipeAlborch** [comment]
Genial! Ahí pude solucionarlo. Muchas gracias a los dos

**Comment by RaniAgus** [comment]
¡Buenísimo @FelipeAlborch !
Una vez resuelta la duda podés cerrar el issue :)
