### ISSUE TITLE
Duda sobre rutas relativas y absolutas

### ISSUE THREAD

**Issue by franco-magne** [sisoputnfrba/foro#2818]
¡Buenas!

Tengo un problemas al querer incluir un archivo .h que se encuentra en otro proyecto. Nosotros creamos un proyecto por cada módulo, todo dentro del mismo workspace. Luego decidimos crear un nuevo proyecto porque vimos que hay código que se repite entre clases y para solucionarlo (o para tenerlo más ordenado) creamos el quinto proyecto.

Planteo la situación concreta: 

Supongamos que desde un archivo .h del módulo consola quiero acceder al .h de la carpeta compartida. Al momento de incluirlo desde el módulo consola lo que hice fue `#include "../shared/include/shared.h"` (carpetaProyecto/subcarpeta/archivo) donde me lo marca como inclusión sin resolver. Después intentamos con el path completo `//#include "/home/utnso/tp-2022-2c-Malta/shared/include/shared.h"` y me lo toma como válido, pero luego no reconoce las funciones que tenemos declaradas en el .h

¿Cuál sería la manera correcta de incluirlo en caso de poderse? Muchas gracias

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va? No va a funcionar ya que Eclipse solamente incluye los archivos ".c" de cada proyecto por separado. 

Una forma de incluir ".c" de otros proyectos es creando _bibliotecas_ (¡como las commons!). En nuestro sitio de guías contamos con un tutorial para crear bibliotecas compartidas e incluirlas en un proyecto: https://docs.utnso.com.ar/guias/programacion/shared-libraries

Saludos

**Comment by franco-magne** [comment]
¡Resuelto! Muchas gracias por la ayuda, no lo había visto que estaba en video

Si me surge algún otro problema vuelvo a abrir el issue.

Saludos
