### ISSUE TITLE
Dudas sobre las instrucciones de Teclado y Pantalla

### ISSUE THREAD

**Issue by Gabi314** [sisoputnfrba/foro#2819]
Hola! Queríamos asegurarnos de estar entendiendo bien algunas cosas que se piden para el teclado y la pantalla.
Para empezar, las instrucciones de estos dispositivos aparecen a partir del archivo de pseudocódigo? Surgió un poco la duda porque no se mostraban en los ejemplos

Después, la **Pantalla** se maneja de la misma manera que otros dispositivos con la única diferencia que se manda la instrucción a consola para que se muestre algo no? Dónde se encuentra el valor que imprime?

Por otro lado, el **Teclado** también hace lo que otros dispositivos salvo por el tiempo de bloqueo que ya depende de lo que se tarde en ingresar el valor por la consola tengo entendido. Es así? En este caso la unidad de trabajo siempre nos va a quedar 1 en la instrucción o pueden ser más? En caso de que puedan haber más, tendríamos que calcular el tiempo que se tardó en ingresar el valor y repetirlo hasta terminar las unidades de trabajo? 

Perdón si son muchas. Desde ya, gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

Antes que nada, mil disculpas por la demora, tu pregunta nos hizo replantearnos varias cosas.
En estos días vamos a estar publicando la v1.1 del enunciado con un poco mas de claridad respecto a como tienen que manejarse las IO de Pantalla y Teclado. 

Saludos.-

**Comment by Gabi314** [comment]
Ok. No hay problema! Muchas gracias de todos modos😅 Esperamos la v 1.1 entonces
