### ISSUE TITLE
Problema para correr el TP

### ISSUE THREAD

**Issue by FelipeAlborch** [sisoputnfrba/foro#2820]
Hola! Buenas noches. Estuvimos con mi grupo avanzando con el código del TP y nos esta surgiendo un problema. A la hora de correr el trabajo, cuando yo lo hacia con la VM anterior (Ubuntu) no tenia ningún problema, después, un compañero de grupo que lo corrió con Xubuntu tampoco tuvo problemas, pero yo, al correrlo con Xubuntu también, me esta apareciendo el siguiente error, que solo me aparece a mi:
![WhatsApp Image 2022-09-15 at 00 37 23](https://user-images.githubusercontent.com/82057459/190308381-ad5a8abf-5a67-4da8-b78d-f1f7411a8599.jpeg)

**Comment by RaniAgus** [comment]
¡Buenas! Antes que nada, aviso que recomendamos ampliamente copiar los mensajes de error en vez de subir capturas de pantalla, ya que si alguien más escribe esto en el buscador no lo va a encontrar:
```
fatal error: commons/log.h: No such file or directory
```

Dicho esto, ¿instalaste las commons como sugiere la guía para [preparar el entorno para codear](https://docs.utnso.com.ar/primeros-pasos/entorno-desarrollo)?

Saludos

**Comment by FelipeAlborch** [comment]
No lo habia hecho en este VM, lo hice en la anterior, por eso me aparecía ese error. Muchas gracias nuevamente, Agus!
