### ISSUE TITLE
[Memoria] Asignación fija con segmentacion paginada

### ISSUE THREAD

**Issue by MatiasRosales** [sisoputnfrba/foro#2823]
Buenas,
Tengo entendido que las tablas de páginas no van a ser sólo por PID, sino que además se incluirá el nro del segmento.
EJ: se crea una tabla de paginas segmento PID 1, Segmento 0

Ahora mi consulta sería que, con asignación fija, ¿se debería limitar el nro de frames entre las tablas de paginas que pertenezcan al mismo proceso?. Eso querría decir que, en swapping al elejir la victima a reemplazar, se deberá seleccionar entre todas las paginas que pertenezcan al mismo PID, independientemente de que segmento se trate ?

Un ejemplo de como iniciaria un flujo de memoria que tengo pensado:
1) Se genera una solicitud para allocar al proceso 1, segmento 1. Creo su tabla de paginas y se asignan todos los frames disponibles para el proceso 1. Quedando ninguno más libre
2) Se genera una solicitud para allocar al proceso 1, segmento 2. Creo otra tabla. Voy a tener que reasignar los marcos del P1S1 a las paginas de esta tabla.
Seria asi?

Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

Algo interesante del esquema de segmentación paginada, es que la CPU ve ambas cosas (por eso que la CPU te puede tirar segment fault), pero para la memoria, seguis viendo solo páginas.

Ahora bien, si nos enfocamos en la consulta y teniendo en cuenta lo que dije previamente, no te importa de que segmento son, solo te importa que sean del mismo proceso 😄 
Por otro lado, no te olvides que la paginación es *bajo demanda*, por lo cual, vos no vas a cargar ninguna página en memoria principal a menos que la quieras acceder.

Estos temas igual los van a ver mas en detalle en las clases de memoria que vienen despues del primer parcial, por ahora pueden encarar mas la CPU, Consola y Kernel :wink:

Saludos.-

**Comment by MatiasRosales** [comment]
Genial! Ahí entendí

Gracias 👍
