### ISSUE TITLE
Consulta sobre los registros del PCB

### ISSUE THREAD

**Issue by Gabi314** [sisoputnfrba/foro#2824]
Hola. Una consulta. La idea de tener los registros en el PCB sería que se puedan guardar valores en ellos no ? Estoy con duda de si cada PCB tiene sus propios registros o si en alguno de los módulos hay unos registros únicos que se comparten entre procesos.

**Comment by iago64** [comment]
Buenas! Cómo va?

No te olvides que en el PCB se guarda el contexto de ejecución, eso incluye una copia de los valores del registro de procesador al momento de ser desalojado :wink:

Saludos.-

**Comment by Gabi314** [comment]
Buenísimo. Muchas gracias!
