### ISSUE TITLE
Consulta por interpretación de lo que debería hacer Kernel

### ISSUE THREAD

**Issue by Gabi314** [sisoputnfrba/foro#2825]
Hola, hay una parte del enunciado de Kernel que nos confunde un poco: 

> En caso de que el grado máximo de multiprogramación lo permita, los procesos pasarán al estado READY, enviando un mensaje al módulo Memoria para que inicialice sus estructuras necesarias y obtenga el valor de la tabla de páginas que deberá estar almacenado en la tabla de segmentos del PCB

¿Cuando se dice "obtenga el valor de tabla de páginas" se refiere a la memoria o al kernel? O sea, la idea sería que Kernel le pida a memoria el valor de la tabla y lo guarde en el PCB (como en el tp anterior) o que Memoria haga eso por su cuenta sin que Kernel le pida nada (solo enviándole el mensaje)

**Comment by LeandroCarbajales** [comment]
Hola @Gabi314 !
La idea es que el Kernel se guarde en el PCB un identificador de la tabla de cada segmento (si, similar al tp pasado), en breve actualizaremos esa parte del enunciado para que quede más clara con la errata V1.1

Saludos!
            Lean

**Comment by LeandroCarbajales** [comment]
Hola @Gabi314 
Pudiste resolver la duda?

**Comment by Gabi314** [comment]
@LeandroCarbajales Sí perdón, me olvidé de cerrar el issue. Muchas gracias!
