### ISSUE TITLE
Duda sobre configuracion para las pruebas

### ISSUE THREAD

**Issue by LautaroRobles** [sisoputnfrba/foro#2826]
Consulta
¿Podemos modificar las estructuras de los archivos de config?

Ya que en la entrega final no sabemos de ante mano la ip de cada modulo y hay que hacer varias pruebas donde tenemos muchos archivos de configuracion. ¿Podemos tener un unico archivo de configuracion para las IP y PUERTOS que se compartan con todas las pruebas?

**Comment by iago64** [comment]
Buenas! Cómo va?
Por los archivos de config no tenemos problema, simplemente les ponemos los parametros que nos interesan que sean configrables el día de la entrega sin tener que modificar el código, asi que son libres de administrarlos como guten.

Les dejo algunas ideas:
- Un solo archivo y lo van modificando el día de la entrega
- Un archivo por prueba y lo único que les agregan son las IPs
- Un script mega magico que les genere los archivos de config (No hagan esto a menos que esten hyper mega recontra sobrados de tiempo)

Cualquier otra duda nos avisan.
Saludos.-

**Comment by LautaroRobles** [comment]
Buenisimo, creo que vamos a ir por la segunda idea.
