### ISSUE TITLE
Consulta sobre quantum e instrucciones CPU bound

### ISSUE THREAD

**Issue by pablomartinfranco** [sisoputnfrba/foro#2827]
Tenemos dudas acerca de como sincronizar la unidad de tiempo en Kernel y CPU para implementar el tiempo de quantum y los tiempos de las instrucciones, ya que no nos queda claro si el tiempo de las intrucciones lo administra CPU o lo administra Kernel, o cada modulo administra tiempos independientes y Kernel desaloja la CPU en el momento del ciclo de instruccion donde CPU revisa si hubo interrupciones. 

Tambien nos hace ruido el tema de hacerlo por tiempo porque nos estaria faltando el tiempo de ejecucion de algunas instrucciones ya que en el enunciado solo encontramos el tiempo de las operaciones I/O bound.
Y en el caso que cada instruccion tenga sus tiempos determinados nos seria util una orientacion de con que tiempos de quantum nos conviene comenzar probando, teniendo en cuenta el esquema de tiempos de las intrucciones CPU bound.

#### *Planificador de Corto Plazo*
. . .
*En el caso de los algoritmos con desalojo (Round Robin), cuando se cumpla el quantum definido por
archivo de configuración se deberá enviar un mensaje de interrupción al módulo CPU a través de la
conexión de interrupt para indicarle que deberá desalojar al proceso que se encuentra actualmente
en ejecución.*
. . .
. . .
*Para el cálculo de los tiempos de Round Robin se deberá crear un hilo específico que espere el
tiempo definido por archivo de configuración (en milisegundos) y pasado este lapso, envíe la
interrupción a la CPU.*

### 💭 Soluciones posibles

Tener informacion sobre la proporcion en unidades de tiempo, que requiere ejecutar cada instruccion.
Ejemplo: 
```
MOV = 1 x tiempo
ADD = 2 x tiempo

Quantum = 10 x tiempo
```

**Comment by LeandroCarbajales** [comment]
Buenas!
Recuerden que para la CPU, la interrupción por fin de quantum es _asincrónica_, por lo que no estará sincronizada con sus ciclos, sino que llegará "en cualquier momento". En este contexto, la CPU puede tardar una cantidad distinta de tiempo por ciclo según qué esté ejecutando, mientras que al módulo Kernel (como planificador de corto plazo en este caso) no le interesa saber cuántos ciclos de instrucción hace la CPU, sino que solamente define un tiempo fijo tras el cual manda la interrupción, de esta manera se garantiza un _tiempo de espera_ predecible para los procesos que planifica.

A modo de ejemplo para que prueben con sus archivos de configuración, si tienen que la CPU toma 1000ms para cada instrucción ADD y SET, y en el kernel definen un Q = 3000ms, lo más probable es que a la CPU esa interrupción le llegue durante el 4to ciclo (3000ms y monedas después de haberse puesto a ejecutar), por lo que terminaria ejecutando 4 instrucciones antes de tener que desalojar al proceso actual. Por supuesto, en las pruebas estaría contemplado el caso borde que por "timing" se lleguen a ejecutar solo 3 por ejemplo siempre que los logs mínimos estén ahí para corroborar.
Para probar esto pueden armarse un archivo de pseudocódigo con muchos SET o ADD seguidos y levantar 2 consolas con el mismo, esos 2 "procesos" deberían irse intercalando en la CPU.

Queda más clara la idea?

Saludos!
       Lean

**Comment by LeandroCarbajales** [comment]
Hola @pablomartinfranco !
Les sirvió la respuesta?

**Comment by pablomartinfranco** [comment]
Hola @LeandroCarbajales . si perfecto !! teniamos dudas sobre que tiempos darle a las instrucciones, lo decidimos nosotros entonces. 
perdon que no respondi antes.
Gracias !!
Saludos
