### ISSUE TITLE
El Debugger en VS no inicia

### ISSUE THREAD

**Issue by pabloquinci** [sisoputnfrba/foro#2830]
Buenas noches. Quería consultarles por un problema que estamos teniendo para debugguear en VS desde la VM, nos aparece este error:
![image](https://user-images.githubusercontent.com/11711534/197088616-e05aea98-3fc1-49c9-a10f-f9998a65fe15.png)

Cómo es la configuración de la task 'make-project' que me pide ahi?

Si elijo 'Debug anyway', me aparece la consola del debugguer pero no me toma los breakpoints. Se queda ahí
![image](https://user-images.githubusercontent.com/11711534/197088808-843fd047-beb8-4105-9f94-00cc7c3e0699.png)

No se si alguien tuvo el mismo problema
Gracias

Saludos

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va?

Todas las configuraciones de VSCode para el proyecto en el que estás se encuentran en una subcarpeta `.vscode`, ya sea:

a) Si abrieron todo el repo directamente con la opción `File` > `Open Folder...`, VSCode lo va a ir a buscar ahí mismo:

![image](https://user-images.githubusercontent.com/39303639/197104738-b3ccdedd-b968-42c2-9cbd-97cabbd0b601.png)

b) Si abrieron cada módulo con la opción `File` > `Add Folder to Workspace...`, VSCode lo va a ir a buscar en cada carpeta que hayan abierto (en el ejemplo anterior sería en `client` y `server`).

El error dice que no te está encontrando la task `make-project` (las tasks se definen en el archivo `tasks.json`). ¿Podrían copy-pastearnos el contenido de ese archivo para poder ver si falta algo?

También, de paso, pásennos el `launch.json`, que es el que tiene toda la configuración de ejecución y probablemente en algún lado dirá:

```json
"preLaunchTask": "make-project"
```

Saludos

**Comment by pabloquinci** [comment]
Este es el launch.json:
![image](https://user-images.githubusercontent.com/11711534/197174649-2bef88f9-ed8d-454f-ac7c-56034417d9df.png)

Y en el task.json:
![image](https://user-images.githubusercontent.com/11711534/197174943-d7252e7b-3ba4-45e3-923e-825ebeb6d469.png)

**Comment by RaniAgus** [comment]
Antes que nada, quisiera recordar lo que mencionamos en el [template que aparece al crear un issue](https://raw.githubusercontent.com/sisoputnfrba/foro/master/.github/ISSUE_TEMPLATE/07-necesito-ayuda-con-otra-herramienta.md), **desalentamos el uso de capturas de pantalla** ya que:
1. No podemos copiarlo y pegarlo para reproducir el error, por lo que toda la ayuda que vamos a dar tendrá que ser a ojo
2. El buscador de issues no reconoce el texto en imágenes, por lo que a otro alumno con la misma duda no le va a aparecer este issue al buscarlo.

Dicho esto 👮🏻, efectivamente el `launch.json` está buscando una task que no existe en el `tasks.json`. 

Lo que está en el `launch.json` me resulta familiar, ¿están usando mi template? Si es así les recomiendo borrar todo lo que tengan en la carpeta `.vscode` y leer las 3 guías de cómo [importar un proyecto](https://raniagus.github.io/so-project-template-guide/guia/code/project), [incluir código de otros archivos](https://raniagus.github.io/so-project-template-guide/guia/code/include) e [incluir una biblioteca](https://raniagus.github.io/so-project-template-guide/guia/code/static).

Saludos

**Comment by pabloquinci** [comment]
Ese es el c_pp_properties.json
`{
    "version": 4,
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "/usr/include",
                "/usr/local/include",
                "${workspaceFolder}",
                "${workspaceFolder}/project/static/include",
                "${workspaceFolder}/project/shared/include",
                "${workspaceFolder}/project/consola/include",
                "${workspaceFolder}/project/kernel/include",
                "/usr/include/x86_64-linux-gnu/sys"
            ],
            "intelliSenseMode": "linux-gcc-x64",
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "gnu17",
            "cppStandard": "gnu++17",
            "configurationProvider": "ms-vscode.makefile-tools"
        }
    ]
}`

Este es el launch.json
`{
            "name": "cpu",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/project/cpu/bin/cpu.out",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "make-project-cpu"
        }/`

Y este es el task.json
`{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "shell",
			"label": "make-project-cpu",
			"command": "make all",
			"problemMatcher": [
                "$gcc"
            ],
			"group": {
                "kind": "build",
                "isDefault": true
            }
		}
	]
}`

Tal como dice el link que me pasaste de cómo importar un proyecto, en la parte de configurar el debugger, lo reimporté como dice ahi y despues por única vez me levantó el debugger. Ya a la segunda vez queda como dije en el primer mensaje, la consola sin hacer nada

**Comment by RaniAgus** [comment]
PD: ¿En qué carpeta está tu `.vscode`? Pregunto porque en la guía aclaré que se debe agregar cada proyecto por separado al workspace (`cpu`, `consola`, etc) pero veo ahí que en el includePath del archivo `c_cpp_properties.json` están apuntando a todos los proyectos juntos:

```json
                "${workspaceFolder}/project/static/include",
                "${workspaceFolder}/project/shared/include",
                "${workspaceFolder}/project/consola/include",
                "${workspaceFolder}/project/kernel/include",
```

Entonces probablemente el archivo `tasks.json` le esté indicando a VSC de ejecutar este comando desde otra carpeta que no es `cpu`, sino la carpeta que está 2 niveles más arriba:

```json
   "command": "make all",
```

Y quizás eso estaría arrojando algún error previo a ejecutar ya que no hay ningún makefile en esa carpeta.

**Comment by pabloquinci** [comment]
En agregué la configuración del .vscode solamente en CPU. Si bien levanta el debugger, no me toma ningún breakpoint,y cuando quiero por ejemplo levantar otra consola con memoria y que se conecte, ahí el debugger de CPU desde el VS no levanta.

**Comment by pabloquinci** [comment]
Ahí agregué la configuración del .vscode solamente en CPU. Si bien levanta el debugger, no me toma ningún breakpoint,y cuando quiero por ejemplo levantar otra consola con memoria y que CPU se conecte, ahí el debugger de CPU desde el VS no levanta.

**Comment by RaniAgus** [comment]
> Si bien levanta el debugger, no me toma ningún breakpoint,

Raaro... yo probaría de ejecutar `make clean` en CPU y luego volverlo a levantar con el debugger.

> y cuando quiero por ejemplo levantar otra consola con memoria y que CPU se conecte, ahí el debugger de CPU desde el VS no levanta.

¿Están ejecutando el CPU usando los `"args"` correctos y desde el mismo `"cwd"` que lo suelen ejecutar desde la terminal? Me suena a que quizás no se esté leyendo el archivo de configuración.

**Comment by iago64** [comment]
Buenas @pabloquinci 

Las respuestas de Agus te sirvieron? Hay algo que siga sin funcionar?

Saludos.-

**Comment by pabloquinci** [comment]
> > Si bien levanta el debugger, no me toma ningún breakpoint,
> 
> Raaro... yo probaría de ejecutar `make clean` en CPU y luego volverlo a levantar con el debugger.
> 
> > y cuando quiero por ejemplo levantar otra consola con memoria y que CPU se conecte, ahí el debugger de CPU desde el VS no levanta.
> 
> ¿Están ejecutando el CPU usando los `"args"` correctos (más info en [esta guía](https://docs.utnso.com.ar/guias/programacion/main.html#pasar-argumentos-desde-visual-studio-code)) y desde el mismo `"cwd"` que lo suelen ejecutar desde la terminal? Me suena a que quizás no se esté leyendo el archivo de configuración.


Ya probé pasándole en el args el archivo de config, y probé también pasandolo vacío y tomandolo de una variable hardcodeada. Pero el problema ahora es que no toma los breakpoints. Y ya ejecuté en la VM el comando que postearon en la página. Por si las dudas el launch me quedó así:

`{
    // Utilizar IntelliSense para aprender acerca de los posibles atributos.
    // Mantenga el puntero para ver las descripciones de los existentes atributos
    // Para más información, visite: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "cpu",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/bin/cpu.out",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "environment": [{ "name": "config", "value": "Debug" }],
            "externalConsole": false,
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "logging": { "trace": true, "traceResponse": true },
            "launchCompleteCommand": "exec-run",
            "MIMode": "gdb",
            "preLaunchTask": "make-project-cpu"
        }
    ]
}`

Probé conectandolo a memoria y va bien. Pero el problema sigue siendo el de los breakpoints que me los ignora y aparecen grisados. Cuando te parás en uno te dice: "Module containing this breakpoint has not yet loaded or the breakpoint address could not be obtained."

**Comment by RaniAgus** [comment]
Buscando en todos lados el único motivo por el cual puede pasar eso es que no estén usando el flag `-g` al compilar con `gcc`.

Abran una consola en la carpeta cpu, ejecuten primero `make clean` para que les borre cualquier compilación previa y luego pásennos el output que les aparece al ejecutar `make`.

Saludos

**Comment by pabloquinci** [comment]
make -C ./project/consola
make[1]: Entering directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/consola'
if [ ! -d ./bin ]; then mkdir bin; fi
if [ ! -d ./obj ]; then mkdir obj; fi
make -C ../shared
make[2]: Entering directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/shared'
if [ ! -d ./obj ]; then mkdir obj; fi
gcc -c src/shared_utils.c -o obj/shared_utils.o -lpthread -lcommons -lm
make[2]: Leaving directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/shared'
gcc -c src/consola_utils.c -o obj/consola_utils.o -lpthread -lcommons -lm
gcc -o ./bin/consola.out consola.c ./obj/consola_utils.o ../shared/obj/shared_utils.o -lpthread -lcommons -lm
make[1]: Leaving directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/consola'
make -C ./project/kernel
make[1]: Entering directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/kernel'
if [ ! -d ./bin ]; then mkdir bin; fi
if [ ! -d ./obj ]; then mkdir obj; fi
make -C ../shared
make[2]: Entering directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/shared'
if [ ! -d ./obj ]; then mkdir obj; fi
make[2]: Leaving directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/shared'
gcc -c src/planificacion.c -o obj/planificacion.o -lpthread -lcommons -lm
gcc -c src/kernel_utils.c -o obj/kernel_utils.o -lpthread -lcommons -lm
gcc -o ./bin/kernel.out kernel.c ./obj/planificacion.o ./obj/kernel_utils.o ../shared/obj/shared_utils.o -lpthread -lcommons -lm
make[1]: Leaving directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/kernel'
make -C ./project/cpu
make[1]: Entering directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/cpu'
if [ ! -d ./bin ]; then mkdir bin; fi
if [ ! -d ./obj ]; then mkdir obj; fi
make -C ../shared
make[2]: Entering directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/shared'
if [ ! -d ./obj ]; then mkdir obj; fi
make[2]: Leaving directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/shared'
gcc -c src/cpu_utils.c -o obj/cpu_utils.o -lpthread -lcommons -lm
gcc -c src/auxiliares.c -o obj/auxiliares.o -lpthread -lcommons -lm
gcc -o ./bin/cpu.out cpu.c ./obj/cpu_utils.o ./obj/auxiliares.o ../shared/obj/shared_utils.o -lpthread -lcommons -lm
make[1]: Leaving directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/cpu'
make -C ./project/memoria
make[1]: Entering directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/memoria'
if [ ! -d ./bin ]; then mkdir bin; fi
if [ ! -d ./obj ]; then mkdir obj; fi
make -C ../shared
make[2]: Entering directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/shared'
if [ ! -d ./obj ]; then mkdir obj; fi
make[2]: Leaving directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/shared'
gcc -c src/memoria_utils.c -o obj/memoria_utils.o -lpthread -lcommons -lm
gcc -o ./bin/memoria.out memoria.c ./obj/memoria_utils.o ../shared/obj/shared_utils.o -lpthread -lcommons -lm
make[1]: Leaving directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/memoria'

**Comment by pabloquinci** [comment]
Ahi paso. No se si no me está generando todas las lineas de la consola en el archivo:

make -C ./project/consola
make[1]: Entering directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/consola'
if [ ! -d ./bin ]; then mkdir bin; fi
if [ ! -d ./obj ]; then mkdir obj; fi
make -C ../shared
make[2]: Entering directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/shared'
if [ ! -d ./obj ]; then mkdir obj; fi
gcc -c src/shared_utils.c -o obj/shared_utils.o -lpthread -lcommons -lm
make[2]: Leaving directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/shared'
gcc -c src/consola_utils.c -o obj/consola_utils.o -lpthread -lcommons -lm
gcc -o ./bin/consola.out consola.c ./obj/consola_utils.o ../shared/obj/shared_utils.o -lpthread -lcommons -lm
make[1]: Leaving directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/consola'
make -C ./project/kernel
make[1]: Entering directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/kernel'
if [ ! -d ./bin ]; then mkdir bin; fi
if [ ! -d ./obj ]; then mkdir obj; fi
make -C ../shared
make[2]: Entering directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/shared'
if [ ! -d ./obj ]; then mkdir obj; fi
make[2]: Leaving directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/shared'
gcc -c src/planificacion.c -o obj/planificacion.o -lpthread -lcommons -lm
gcc -c src/kernel_utils.c -o obj/kernel_utils.o -lpthread -lcommons -lm
gcc -o ./bin/kernel.out kernel.c ./obj/planificacion.o ./obj/kernel_utils.o ../shared/obj/shared_utils.o -lpthread -lcommons -lm
make[1]: Leaving directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/kernel'
make -C ./project/cpu
make[1]: Entering directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/cpu'
if [ ! -d ./bin ]; then mkdir bin; fi
if [ ! -d ./obj ]; then mkdir obj; fi
make -C ../shared
make[2]: Entering directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/shared'
if [ ! -d ./obj ]; then mkdir obj; fi
make[2]: Leaving directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/shared'
gcc -c src/cpu_utils.c -o obj/cpu_utils.o -lpthread -lcommons -lm
gcc -c src/auxiliares.c -o obj/auxiliares.o -lpthread -lcommons -lm
gcc -o ./bin/cpu.out cpu.c ./obj/cpu_utils.o ./obj/auxiliares.o ../shared/obj/shared_utils.o -lpthread -lcommons -lm
make[1]: Leaving directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/cpu'
make -C ./project/memoria
make[1]: Entering directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/memoria'
if [ ! -d ./bin ]; then mkdir bin; fi
if [ ! -d ./obj ]; then mkdir obj; fi
make -C ../shared
make[2]: Entering directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/shared'
if [ ! -d ./obj ]; then mkdir obj; fi
make[2]: Leaving directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/shared'
gcc -c src/memoria_utils.c -o obj/memoria_utils.o -lpthread -lcommons -lm
gcc -o ./bin/memoria.out memoria.c ./obj/memoria_utils.o ../shared/obj/shared_utils.o -lpthread -lcommons -lm
make[1]: Leaving directory '/home/utnso/tp-2022-2c-CodeandoConSuenio/project/memoria'

**Comment by RaniAgus** [comment]
Ahhh, ahora entiendo, al final no estaban usando los templates como había preguntado en un principio sino uno un makefile propio.

Efectivamente, si hacés `Ctrl` + `F` y buscás `-g` vas a ver que no está entre los flags que le pasan a `gcc`. La solución es agregarlo en el makefile en todas las rules donde usen `gcc`.

Lo que hace ese flag es, a costa de algo de performance y espacio en el archivo final, agregar las referencias de cada instrucción a la línea de código correspondiente para poder debuggear (ref: https://www.rapidtables.com/code/linux/gcc/gcc-g.html)

Saludos

**Comment by pabloquinci** [comment]
Ahí pude, agregué el flag a mano en el makefile.
Gracias!
