### ISSUE TITLE
Implementacion de Quantum

### ISSUE THREAD

**Issue by carrilloFN** [sisoputnfrba/foro#2831]
El kernel envia procesos a ejecutar a la CPU, y tendrá un hilo exclusivamente para enviar interrupciones a la CPU tras un determinado tiempo para desalojarlo por fin de " Quantum ", suponiendo que dentro de las **instrucciones a ejecutar** hay una que es **bloqueante**, la **CPU devuelve el pcb** del proceso en ejecución al kernel **esperando por un nuevo pcb**, tomando este caso como ejemplo, **_¿qué pasa con el " Quantum " ?_** _**¿debería reiniciarse el "conteo" tal cual los ejercicios prácticos de planificación?**_, cuyo caso, para evitar procesamiento en la cpu para enviar las interrupciones, el fin de quantum lo realizo mediante un usleep de dicho tiempo para que al despertar envíe la interrupción, ¿existe alguna manera de despertar a ese proceso durmiendo?

### 📔 Citas del enunciado/videos
>Para el cálculo de los tiempos de Round Robin se deberá crear un hilo específico que espere el tiempo definido por archivo de configuración (en milisegundos) y pasado este lapso, envíe la interrupción a la CPU.

### 💭 Soluciones posibles

- El hilo de interrupciones simplemente las envía cada cierto tiempo sin tener en cuenta el proceso que se encuentra ejecutando (lo cual afectaría la planificación dado a que un proceso podría llegar a ejecutar mucho menos que el Quantum que le corresponde), una manera de reducir este problema podría ser dormir al proceso muchas veces por poco tiempo para ir chequeando si debe de reiniciar el Quantum.

**Comment by iago64** [comment]
Buenas! Cómo va?

La idea es que sea tal cual los ejercicios de la teoría, si tenian un proceso con un Quantum de 4 y en el instante 2 se va a I/O, el quantum restante se pierde.

Como implementarlo ya va a depender de cada grupo y mas que posible si lo hablamos con 10 grupos tengamos 9 soluciones distintas (porque el 10mo todavía no lo resolvió). Como algo de info para que tengan un _hilo_ de investigación, pueden investigar dentro de la biblioteca de pthread que hay funciones para _cancelar_ un thread 😉 

Saludos.-

**Comment by carrilloFN** [comment]
Perfecto, voy a investigar pthread entonces, muchas gracias!
(cierro el issue).
