### ISSUE TITLE
Buenas

### ISSUE THREAD

**Issue by FabriPuch** [sisoputnfrba/foro#2832]
Quisiera saber como puedo buscar mediante texto en un cuadro de base de datos dentro de un forms de visual studio lo que pasa es que tengo ya la base de datos pero no se como puedo hacer para filtrar las busquedas mediante letras

**Comment by LeandroCarbajales** [comment]
Buenas!
Creo que te equivocaste de foro de consultas, cualquier duda chusmeá el Readme ;)
