### ISSUE TITLE
Problema con archivos de shared libraries

### ISSUE THREAD

**Issue by Gabi314** [sisoputnfrba/foro#2833]
Hola. Estuve viendo el video tutorial que está subido en utnso sobre las Shared Libraries. Creé un nuevo proyecto en Eclipse para tener una teniendo en cuenta que sea de tipo _shared libraries_. Pero cuando se crea solo genera los archivos de include. Los .c, los objetos, etc en cambio no. Y no estoy seguro si la idea es que creemos algunos archivos nosotros o estoy haciendo algo mal. Como no es algo urgente preferí preguntar antes para estar seguro. Desde ya gracias.

**Comment by RaniAgus** [comment]
¡Buenas! Sí, en el video Tom aclara que ya está codeada la library (o sea, ya había creado la carpeta `src` con los archivos de antemano).

¿Cuando hablás de los "archivos de include" te referís a esto?

![image](https://user-images.githubusercontent.com/39303639/197625173-96f666bc-484e-4b54-935f-aac635cad35a.png)

En realidad esos headers no se crean dentro de la library (si abrís el explorador de archivos vas a ver que no hay una carpeta `Includes`), sino que son las rutas a todos los headers que están instalados en el sistema, por ejemplo las commons.

Saludos

**Comment by RaniAgus** [comment]
¡Buenas @Gabi314! ¿Quedó clara la idea? Saludos

**Comment by Gabi314** [comment]
Hola Agus. Sí, quedo más clara y pudimos resolverlo! Gracias!
