### ISSUE TITLE
Consulta sobre I/O

### ISSUE THREAD

**Issue by nachovilla123** [sisoputnfrba/foro#2834]
Buenas, tenemos dudas sobre como realizar las instrucciones de IO. En el caso de que sea pantalla/teclado, CPU le va a devolver la instrucción a kernel. Kernel le va a enviar algo a consola que referencie a si es pantalla o teclado. 
En caso de ser pantalla, ¿Qué hay que esperar a que responda?
En caso de ser teclado, consola tiene que estar a la espera de un mensaje de kernel para que en algún momento "nosotros" le pongamos algún valor?

### 📔 Citas del enunciado/videos

Pantalla: se deberá leer el registro que el módulo CPU nos informó, enviar su valor al módulo Consola para que lo imprima y esperar a que responda.
Teclado: se deberá recibir un valor desde el módulo Consola y guardarlo en el registro que el módulo CPU nos informó.
Aparte se tendrá una lista de Dispositivos de Entrada-Salida, los cuales vendrán por archivo de configuración y tendrán un nombre y una duración por unidad de trabajo. La cantidad de unidades de trabajo será lo que deberá informarnos la CPU al momento de devolver un PCB por una instrucción de I/O. En estos dispositivos los procesos se encolan a medida que llegan las peticiones de I/O.

**Comment by RaniAgus** [comment]
¡Buenas! Las respuestas a ambas consultas se encuentran especificadas en el módulo Consola (p.11), cito:

>  Una vez recibida la confirmación de recepción, la consola quedará a la espera de nuevos mensajes del Kernel los cuales pueden ser:
> - Imprimir un valor por pantalla, con un tiempo de retardo definido por archivo de configuración antes de responder al Kernel.
> - Solicitar que se ingrese un valor por teclado.
>
> Ambas operaciones recibirán únicamente valores numéricos y una vez finalizadas se deberá informar al Kernel para que éste desbloquee el proceso.

En caso de ser pantalla, cualquier respuesta que indique que la operación se completó está bien.

Saludos

**Comment by nachovilla123** [comment]
Cuando dice "Solicitar que se ingrese un valor por teclado" es explícitamente ingresar manualmente un valor por MI teclado? o hay que leer algún valor guardado en una variable llamada teclado que toma su valor del archivo de configuración.

y en este caso "Pantalla: se deberá leer el registro que el módulo CPU nos informó, enviar su valor al módulo Consola para que lo imprima y esperar a que responda." 
Debemos literalmente imprimir con un log o un printf en el modulo consola?

**Comment by RaniAgus** [comment]
> Cuando dice "Solicitar que se ingrese un valor por teclado" es explícitamente ingresar manualmente un valor por MI teclado?

Exacto, la idea es que el proceso quede bloqueado hasta que no ingresemos un valor por teclado. No hace falta manejar casos de error, pueden asumir que siempre vamos a ingresar valores válidos.

> y en este caso "Pantalla: se deberá leer el registro que el módulo CPU nos informó, enviar su valor al módulo Consola para que lo imprima y esperar a que responda."
Debemos literalmente imprimir con un log o un printf en el modulo consola?

Correcto 👍🏻 

Saludos

**Comment by LeandroCarbajales** [comment]
Buenas @nachovilla123 !
Quedó resuelta la duda? Se puede cerrar el issue?

**Comment by nachovilla123** [comment]
Disculpen la tardanza de la resuesta, si se puede cerrar el issue
