### ISSUE TITLE
Actualización VM

### ISSUE THREAD

**Issue by LucasLamanna** [sisoputnfrba/foro#2835]
Buenas. 
Hoy quise actualizar la VM con el comando que subieron en el post del blog pero al correrlo me surge el siguiente error:
```
utnso@ubuntu-server:~$ curl -fsSL https://faq.utnso.com.ar/vms-fix.sh | sh
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```
La VM es la que descargué el cuatrimestre pasado solo que le cambie la opción de 32 bits a 64 bits. Tendría que eliminarla y volver a descargarla?

**Comment by iago64** [comment]
Buenas! Cómo va?

Las VMs de 64bits son de este cuatrimestre, la del cuatrimestre anterior (y de muchos otros para atras) eran de 32 bits y el script solo sirve si tenias las que se lanzaron a principio de este cuatrimestre que ya eran de 64 bits.
Si tenes una VM del cuatrimestre pasado, sería bueno que bajes las nuevas ya que las pruebas en el laboratorio se van a hacer con las nuevas VMs de 64bits.

Saludos.-

**Comment by LucasLamanna** [comment]
Perfecto, muchas gracias
