### ISSUE TITLE
Cola de bloqueados

### ISSUE THREAD

**Issue by ayllon89** [sisoputnfrba/foro#2836]
Hola que tal, tengo una duda con el enunciado, en el modulo Kernel en la pagina 13 dentro del apartado "Diagrama de estados" se menciona lo siguiente

📔 Citas del enunciado
El kernel utilizará el diagrama de 5 estados para ordenar la planificación de los procesos. Dentro del
estado BLOCK, se tendrán múltiples colas.
Las 2 primeras serán fijas y asociadas a cada consola que haya ingresado un proceso al sistema, ya
que deberán enviar un mensaje a la misma y dejar el proceso bloqueado hasta recibir su respuesta:
- Pantalla: se deberá leer el registro que el módulo CPU nos informó, enviar su valor al módulo
Consola para que lo imprima y esperar a que responda.
- Teclado: se deberá recibir un valor desde el módulo Consola y guardarlo en el registro que el
módulo CPU nos informó.

💭 Soluciones posibles
Con mi grupo habiamos pensado manejar una cola por cada estado y mediante hilos planificadores ir moviendo cada PCB a la cola que corresponda. No entiendo concretamente la parte que dice "Las 2 primeras seran fijas y asociadas a cada consola que haya ingresado un proceso al sistema" Osea en una cola irian los procesos que se bloquearon por querer ejecutar la instruccion "pantalla" y en la otra cola irian los procesos que se bloquearon por querer ejecutar la instruccion "teclado"?

Espero que se haya entendido mi duda, muchas gracias de antemano por responder
Un saludo
Luis

**Comment by LeandroCarbajales** [comment]
Buenas!
Los procesos en sí estarían en estado bloqueado, pero se deberían encolar por separado según el dispositivo de I/O (o más generalmente, por el evento) que estén esperando, por lo que tendrían una cola por cada dispositivo de I/O que disponga el Kernel.

>  Osea en una cola irian los procesos que se bloquearon por querer ejecutar la instruccion "pantalla" y en la otra cola irian los procesos que se bloquearon por querer ejecutar la instruccion "teclado"?

No exactamente, como dice el enunciado: "...serán fijas y asociadas a cada consola que haya ingresado un proceso al sistema", dicho de otra manera, cada proceso tendría su propia "pantalla" y su propio "teclado", por lo que nunca se encolarían por esos dispositivos. En cambio, si varios procesos necesitan usar el dispositivo "DISCO", sí se encolarían ya que hay uno solo (como en los ejercicios que vemos en clase).

Queda más clara la idea?

Saludos!
       Lean

**Comment by LeandroCarbajales** [comment]
Hola @ayllon89 !
Te resolvió la duda? Se puede cerrar el issue?

**Comment by RaniAgus** [comment]
¡Buenas @ayllon89! Cierro el issue por inactividad, ante cualquier consulta pueden reabrirlo o abrir uno nuevo. Saludos
