### ISSUE TITLE
Error en un #include

### ISSUE THREAD

**Issue by LucasLamanna** [sisoputnfrba/foro#2837]
Buenas, como va?
Nos surgió el siguiente error a nuestro grupo cuando fuimos desarrollando el tp:
![image](https://user-images.githubusercontent.com/82039984/198840735-c6e1dc1a-1927-4022-a9f7-f5ae7c788fc6.png)

Calculo que se deberá a algún error de path mal referenciado pero no sabemos como solucionarlo.

A qué se refiere con lo de actualizar el includePath, dónde lo podríamos hacer??

**Comment by RaniAgus** [comment]
¡Buenas! Para empezar, ¿podrías copiar el mensaje de error en texto en vez de usar una captura? Como comentamos en el [readme del foro](https://github.com/sisoputnfrba/foro/blob/master/README.md), el error no se puede buscar usando el buscador de issues a partir de una imagen.

Dicho esto, el error es específico de VSCode: como la compilación y el corrector del IDE van por caminos distintos, no es lo suficientemente inteligente como para adivinar todas las posibles carpetas de dónde se puede incluir código, sino que solo incluye las que ya haya instaladas (`/usr/include`, `/usr/local/include`, etc).

Entonces, para corregir esto, hay que especificarlo a mano. Créense una carpeta `.vscode` y agréguenle un archivo `c_cpp_properties.json` que tenga lo siguiente:

```json
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                // TODO: Agregar los include paths
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "gnu17",
            "cppStandard": "gnu++17",
            "intelliSenseMode": "linux-gcc-x64"
        }
    ],
    "version": 4
}
```

Ahí podrían agregar el valor hardcodeado, por ejemplo:
```json
                "/home/utnso/tp-2022-2c-Redeem-Team/kernel/include"
```


O mejor usar alguna de las variables de VSCode ([pueden encontrar la docu acá](https://code.visualstudio.com/docs/editor/variables-reference)). Por ejemplo, `workspaceFolder` convenientemente toma la ruta de la carpeta que fue abierta por VSCode:

```jsonc
                // esto sería si abrieron la carpeta del repo:
                "${workspaceFolder}/kernel/include" 
                // y esto sería si abrieron la carpeta de cada módulo por separado:
                "${workspaceFolder}/include" 
```

Esta alternativa es mejor que la primera porque no depende de en qué carpeta tengan clonado el repo, sino solo de haber abierto la carpeta correcta.

Saludos

**Comment by LeandroCarbajales** [comment]
Hola @LucasLamanna !
Te sirvió la respuesta? Se puede cerrar el issue?

**Comment by LucasLamanna** [comment]
Si, perdón que no respondí. Sirvió, gracias.

**Comment by RaniAgus** [comment]
Dejo este comment para poder encontrar el issue, el error es:

```
#include errors detected. Please update your includePath.
Squiggles are disabled for this translation unit
```
