### ISSUE TITLE
Como matar el hilo que controla el quantum

### ISSUE THREAD

**Issue by NearDante** [sisoputnfrba/foro#2838]
Cuando implementamos el round robin, creamos un hilo temporizador por cada hilo de proceso. Este hilo temporizador se duerme con sleep(Quantum). Y cuando termina envia la señal de interrupcion. Pero cuando el PCB regresa antes por entrada y salida, deberia matar este hilo para que no envie la señal de interrupcion. 
Pregunta: Como se mata el hilo temporizador? para que no termine de ejecutar el sleep(). Porque sino recorre el inicio de los siguientes quantums.

**Comment by LeandroCarbajales** [comment]
Buenas!

> Pero cuando el PCB regresa antes por entrada y salida, deberia matar este hilo para que no envie la señal de interrupcion.

No es estrictamente necesario matar al hilo, podrían hacer algún chequeo extra en el hilo una vez que finaliza su sleep antes de enviar la interrupción, por ejemplo chequear que ese Pid no haya sido ya devuelto (sea por IO, EXIT, Page fault, etc).
Igualmente si quieren ir por el lado de matar el hilo, chusmeen la función [pthread_cancel](https://man7.org/linux/man-pages/man3/pthread_cancel.3.html)

Saludos!
       Lean

**Comment by LeandroCarbajales** [comment]
Buenas @NearDante !
Te resuelve la duda? Se puede cerrar el issue?
