### ISSUE TITLE
DUDA I/O - DISPOSITIVOS + PANTALLA Y TECLADO

### ISSUE THREAD

**Issue by valentinarau** [sisoputnfrba/foro#2839]
Hola buenas tardes, tenemos algunas consultas de cara al proximo checkpoint (3)
Nos trabamos en el manejo por parte del kernel de las peticiones de teclado y pantalla hacia las consolas.
Partiendo de la base de que tenemos un **unico hilo** que atiende a las consolas (se conecta y recibe los datos necesarios para crear un proceso), nosotros queremos ahora atender las solicitudes de pantalla y teclado para cada consola. 

1) Seria correcto crear un hilo on demand para cada solicitud de pantalla y teclado y asociarlo a cada consola? sabiendo que en ese hilo tenemos que esperar la respuesta de la misma. 

2) Considerando el issue [2836](https://github.com/sisoputnfrba/foro/issues/2836) no entendemos el motivo de las colas de teclado y pantalla, presentes en el enunciado, porque no nos queda claro qué encolariamos, quien va a consumir de esa cola y que va a hacer, ya que cada consola tiene su teclado y su pantalla y como decimos en el item anterior, **cada hilo creado manejaria cada peticion**

3) Entonces, por lo que dice tambien el issue mencionado, es necesario encolar por **cada** dispositivo  del archivo de configuracion?

**Comment by LeandroCarbajales** [comment]
Buenas!
1- Sería una buena opción :)
2- Como respondí en ese mismo issue, nunca se encolarían por esos dos dispositivos ya que habría uno por proceso, la idea de los mismos es que justamente podamos bloquear al proceso sin tener que encolarlos detrás de otros procesos que también estén bloqueados, por ejemplo, podríamos bloquear P1 por su teclado y luego P2 por su teclado, sin embargo, luego podríamos desbloquear primero a P2 y dejar a P1 bloqueado indefinidamente a pesar de haberse bloqueado antes que P2. Este mismo caso no podría pasar con ninguno de los dispositivos "compartidos" del Kernel (los definidos por archivo de config).
Otro ejemplo con "pantalla" es que simplemente querramos que un proceso se bloquee por un período muy corto de tiempo sin depender de que haya otros procesos bloqueados o no.
3- Sí, tomando como ejemplo las pruebas, teniendo un disco y una impresora en el sistema, si un proceso se bloquea por disco y ya hay otro bloqueado por el mismo, se encolaría hasta que el anterior termine su I/O (igual que en los ejercicios de clase).

Queda más clara la idea?

Saludos!
      Lean

**Comment by valentinarau** [comment]
Sii re, gracias!
