### ISSUE TITLE
Resultado RR - Pruebas Base

### ISSUE THREAD

**Issue by Solanaaz** [sisoputnfrba/foro#2840]
Buenas, 
Estuvimos testeando con el grupo las pruebas base y consideramos que los resultados del RR = [2,1,3] son incorrectos ya que la prueba BASE_1 contiene mas instrucciones que BASE_2 entonces seria el ultimo proceso a finalizar obteniendo así un resultado de ejecución igual a 2>>3>>1 . Queriamos saber si se puede revisar ese resultado y si estos resultados que proponemos son coherentes. 
Gracias.

### 📔 Citas del documento de pruebas

> Resultados Esperados

> Con el algoritmo FIFO los procesos finalizan en el orden 1-2-3.

**> Con el algoritmo RR los procesos finalizan en el orden 2-1-3.**

### 👍 Comportamiento esperado

> Resultados Esperados

> Con el algoritmo FIFO los procesos finalizan en el orden 1-2-3.

**> Con el algoritmo RR los procesos finalizan en el orden 2-3-1.**

**Comment by LeandroCarbajales** [comment]
Buenas!
El documento mostraba erróneamente levantar "BASE_1", "BASE_2" y "BASE_2" nuevamente, ahí lo corregimos, deberían ser 1, 2 y 3.
Los script 1 y 3 tienen el mismo largo por lo que en un RR deberían terminar en ese orden, quedando [2,1,3] como resultado esperado.

Pueden chequear nuevamente usando los scripts 1, 2 y 3?

Saludos!
      Lean

**Comment by Solanaaz** [comment]
Ahora si!

Gracias
