### ISSUE TITLE
Resultados Pruebas Plani Base - FEEDBACK 

### ISSUE THREAD

**Issue by Solanaaz** [sisoputnfrba/foro#2841]
Buenas,
tenemos una duda con el resultado de ejecución de las pruebas plani base.
Cuando cambiamos a el algortimo FEEDBACK el documento dice esperar un resultado de ejecución 2>>4>>3 especificando que P3 y P4 luego de ejecutar su primera instrucción irán a la Cola de FIFO por fin de Q. 
Por qué el P2 no iría a la cola de FIFO por fin de Q si luego de ejecutar la primera instrucción ya consume el Q y debería ser desalojado.
Por otro lado, cuál debería ser el tiempo de retardo de I/O pantalla por configuración ya que no esta especificado en los archivos.

### 📔 Citas del documento de pruebas

> Resultados Esperados

> Con FIFO los procesos terminan en el siguiente orden: 2-3-4-1

> Con RR los proceso terminan en el siguiente orden 2-4-3-1

**> Con FEEDBACK los procesos terminan en el orden 2-4-3 pero tanto P3 como P4 pasan por la cola de FIFO ya que son desalojados por fin de quantum**

### 👎 Comportamiento obtenido

> Resultados Esperados

> Con FIFO los procesos terminan en el siguiente orden: 2-3-4-1

> Con RR los proceso terminan en el siguiente orden 2-4-3-1

**> Con FEEDBACK los procesos terminan en el orden 2-3-4 con P2,P3 y P4 desalojados por fin de Q a la cola de FIFO

**Comment by LeandroCarbajales** [comment]
Buenas!

> Por qué el P2 no iría a la cola de FIFO por fin de Q si luego de ejecutar la primera instrucción ya consume el Q y debería ser desalojado.

Tienen razón! Se nos pudo haber pasado en los cálculos, en cuanto podamos lo revisamos y actualizamos el documento, de cualquier manera, lo importante es que tengan los logs necesarios para poder seguir la ejecución.

> Por otro lado, cuál debería ser el tiempo de retardo de I/O pantalla por configuración ya que no esta especificado en los archivos.

Pueden probar con algún valor menor a 1000, por ejemplo 750 debería ir bien para estas pruebas. En la semana agregaremos la config de consola con algún valor como ese para que todos tengan lo mismo.

Gracias por el feedback!

**Comment by LeandroCarbajales** [comment]
Buenas @Solanaaz !
Ya actualizamos el doc y los scripts, efectivamente teníamos un error en los cálculos, por favor avísen si encuentran alguna otra discrepancia.
Muchas gracias y nos vemos el sábado :)

**Comment by LeandroCarbajales** [comment]
Cierro el issue por inactividad y asumo que la duda está resuelta ya que lo vimos en el checkpoint. Cualquier cosa abren otro issue :)

**Comment by GRodriguezPardo** [comment]
Hola, con el cambio de la consigna ahora menciona que solo los proceso 2 y 3 pasan por FIFO. El proceso P4 en un momento ejecuta 3 instrucciones de CPU seguidas, siendo la 3ra EXIT, pero siendo el Q=1500 y el retardo de instrucción 1000, no podría ejecutar mas de 2 instrucciones, y se ve desalojado por Quantum, y relegado a la cola de FIFO.

En conclusion, al correr las pruebas pasan tanto P2 y P3 como P4 por FIFO, pero la consigna no menciona que P4 debería. 
El problema es nuestro o de la consigna?
Gracias!

**Comment by LeandroCarbajales** [comment]
Buenas!
Se nos pasó que el EXIT se ejecutaría ya estando en cola FIFO, de cualquier manera no afecta a la planificación esperada más allá de ese detalle al final de la ejecución de P4, para la fecha de entrega actualizaremos el doc para que quede plasmado.

Saludos!
         Lean
