### ISSUE TITLE
Criterio para crear tabla de páginas

### ISSUE THREAD

**Issue by CFedericoDavid** [sisoputnfrba/foro#2843]
Buenas tardes, 
No entiendo el enunciado a la hora de crear las tablas de páginas (más específicamente, qué valor tengo que tomar como la cantidad de páginas en la tabla), y la función de los tamaños de segmentos que se mandan desde Consola.

En la sección Consola, la hoja 11 dice

> Luego se conectará al kernel y enviará la información correspondiente al listado de instrucciones **y los tamaños de los segmentos.**

Y seguido, en la configuración, está esto

> SEGMENTOS | Lista | Lista ordenada de los tamaños de los segmentos de Datos del proceso en los cuales podrá leer o escribir.

Leyendo sólo esto, deduje que la cantidad de entradas de la tabla de páginas de un segmento es variable, según el tamaño del segmento (ej, el segmento es de 128 B, el tamaño de una pagina es 64 B => 2 páginas en su tabla)

Pero después en la configuración de la Memoria, aparece un valor 

> ENTRADAS_POR_TABLA | Numérico | Cantidad de entradas de cada tabla de páginas.

Entonces, no me queda claro si a la hora de crear una tabla de páginas, tengo que tomar como referencia el tamaño real (desde consola) de un segmento y dividirlo por el tamaño de una pagina (me quedarían tablas de largo variable)
O tomar el valor de configuración _cantidad de entradas por tabla_ (con lo que me quedarían todas las tablas del mismo tamaño).

---
Otra cosa relacionada es que en la sección de MMU, a la hora de conocer el numero de segmento de una dirección lógica dice:

> tam_max_segmento = cant_entradas_por_tabla * tam_pagina
> **num_segmento = floor(dir_logica / tam_max_segmento)**

O sea que para saber en qué segmento está, compara con el tamaño máximo, no con el tamaño real. (Lo mismo para un posible segmentation fault). Entonces no se bien qué función cumple el tamaño real de un segmento.

Por ahí es medio rebuscado lo que planteo, así que cualquier duda la aclaro

**Comment by LeandroCarbajales** [comment]
Buenas @CFedericoDavid !
Es una muy buena pregunta que va de la mano con los ejercicios que vemos en clase.
Conceptualmente las tablas de páginas son de tamaño fijo ya que deben permitir direccionar lo máximo que pueda la CPU (direccionamiento lógico), a efectos del trabajo si les sirve representarla como una lista que tenga solamente la cantidad necesaria de entradas no hay ningún problema ya que es un escenario simplificado.
El valor "cant_entradas_por_tabla" vendría a representar los bits de la dirección que nos dice el número de página, por lo que las cuentas para "descomponer" la dirección lógica la tenemos que hacer con ese número, para hacer el paralelo con las clases si el mismo fuera de 16 es como si tuviera 4 bits para número de página (2^4=16), esto significaría que los segmentos nunca podrían ser más grandes que (16 * tam_página) y tus tablas nunca tendrían más de 16 entradas (esto no es algo que necesiten chequear, las config siempre van a ser coherentes).
Para chequear SEG FAULT sí lo hacen con el tamaño real del segmento que tendrían en la tabla de segmentos, por ejemplo, si un segmento tiene tamaño 1500 y quisiera acceder a un offset de 1600 dentro del mismo, no se debería permitir.

Queda más clara la idea?

Saludos!
        Lean

**Comment by CFedericoDavid** [comment]
Ok genial
Entonces para ver si entendí, las tablas las puedo hacer de tamaño fijo usando entradas_tabla para todas.
En ese caso habría páginas "fantasma", más de las que tiene el segmento en sí. 

Pero no habría problema cuando CPU pida una página, porque por dirección lógica nunca me va a poder pedir una de esas (porque el chequeo de SEG FAULT se hace con el tamaño real, y se interrumpiría antes de terminar el pedido).

Lo estoy razonando bien?

**Comment by LeandroCarbajales** [comment]
Buenas!
Exactamente :), si crean todas las tablas usando cant_entradas_tablas, simplemente tendrían algunas entradas de sus tablas que no se usarían.
Imagínense que en caso de que tenga que crecer un segmento por ejemplo (que no va a ocurrir en este trabajo), solamente tendrían que actualizar su tamaño en la tabla de segmentos.

Saludos!
      Lean

**Comment by LeandroCarbajales** [comment]
Buenas @CFedericoDavid !
Quedó resuelta la duda? Se puede cerrar el issue?

**Comment by CFedericoDavid** [comment]
Buenas! sí quedó resuelta, disculpá la demora
Muchas gracias!
