### ISSUE TITLE
DUDA MEMORIA SCOPE DE REEMPLAZO

### ISSUE THREAD

**Issue by lrocampo** [sisoputnfrba/foro#2844]
Hola buenas, tenemos una duda de enunciado.
No entendemos si el scope de reemplazo local seria del segmento de la tabla de paginas, o todos los segmentos del proceso. (o sea si mi algoritmo de reemplazo tendria que recorrer una tabla de paginas de un segmento, o cada una de las tablas de todos los segmentos del proceso)

### 📔 Citas del enunciado/videos
_En este contexto, se definirá una asignación de cantidad de marcos fija definida por archivo de configuración y un scope de reemplazo local._

**Comment by iago64** [comment]
Buenas! Cómo va?

Esto justo lo respondimos en el issue #2823 😄 

Saludos.-

**Comment by lrocampo** [comment]
Gracias!
