### ISSUE TITLE
COMO ENCARAR SWAP

### ISSUE THREAD

**Issue by lrocampo** [sisoputnfrba/foro#2845]
Hola buenas, no nos queda muy claro como implementar/pensar el modulo de swap.
No se me ocurren qué funciones de C o de las commons me pueden ser útiles para manipular el SWAP, o sea:
- Qué funciones me sirven para leer o escribir el archivo SWAP en una posicion especifica?
- Qué funciones me sirven para liberar espacio de SWAP?
Tambien teniamos la duda de, a la hora de finalizar los procesos, como se supone que se "libera" su memoria en swap (siendo este un unico archivo), quedando disponible para los demas procesos, como sabe la memoria que hay espacio para asignar paginas ahi? para utilizarlo y reutilizarlo.

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Para lo que es el **archivo** de swap, podes utilizar las funciones de manejo de archivos de C (Por Ej: [fread()](https://man7.org/linux/man-pages/man3/fwrite.3.html), [fwrite()](https://man7.org/linux/man-pages/man3/fwrite.3p.html), [fseek()](https://man7.org/linux/man-pages/man3/fseek.3.html)

2.- El tema de liberarlo, es algo que vas a tener que manejarlo vos en tus estructuras administrativas, con marcarlo como libre ya alcanza, no es necesario que hagan ningun borrado de los datos.

Saludos.-

**Comment by lrocampo** [comment]
Gracias por la respuesta. Algo más que me sigue sin quedar claro es cómo se dónde posicionar una página en SWAP obteniendo el próximo espacio libre.

**Comment by lrocampo** [comment]
Gracias, le doy una leida.
