### ISSUE TITLE
Cantidad de segmentos por proceso Consola

### ISSUE THREAD

**Issue by CFedericoDavid** [sisoputnfrba/foro#2846]
Buenas, me surge una duda simple
La cantidad de segmentos de datos por proceso Consola es siempre la misma o es variable? (en el config de ejemplo serían 4).
Gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

La cantidad de segmentos es variable. 
Para que no entren en pánico, no van a tener 1000 segmentos pero asuman que va a ser una lista variable, en algunos tendran 1, en otros tendran 2 y en otros quizas 10.

Saludos.-

**Comment by CFedericoDavid** [comment]
Genial, y hay algún workaround para calcular esa cantidad? porque la función de las commons para sacar un array de un config devuelve un char** 
O lo tenemos que desarrollar nosotros?

**Comment by iago64** [comment]
Si la duda quedo resuelta por favor no olviden cerrar el issue 😄
