### ISSUE TITLE
Error :malloc corrupted top size

### ISSUE THREAD

**Issue by camilamarinio** [sisoputnfrba/foro#2847]
Buenas , 
con mi grupo estamos teniendo un problema cuando agregamos la tabla de segmentos a la estructura del pcb , el problema es al momento de serializar . La serialización funcionaba perfecto, pero cuando agregamos la lista de tablas de segmentos, nos empezó a tirar este error,  no podes saber en que le estamos errando. 
Hicimos un debugger y nos salió en el lugar que rompe, que es al momento de crear el paquete para enviarlo .Al momento de utilizar la función crear paquete ,que ya estábamos utilizando y funcionaba, nos rompe en la primera linea donde le hacemos el malloc.
No podemos entender bien como solucionar este error .
el error malloc corrupted top size lo tira  kernel cuando quiere mandar el pcb serializado a la cpu.

esta es la linea en la que actualmente nos tira este error en la función crear paquete : t_paqueteActual *paquete = malloc(sizeof(t_paqueteActual));

así serializamos la tabla de segmentos 
esto le agregamos al buffer->size = + list_size(pcb->tablaSegmentos) * sizeof(t_tabla_segmantos)

```
void *stream = malloc(buffer->size);
	int offset = 0;
t_buffer *buffer = malloc(sizeof(t_buffer));

memcpy(stream + offset, &(pcb->tablaSegmentos->elements_count), sizeof(uint32_t));
offset += sizeof(uint32_t);

int n = 0;
	while (n < list_size(pcb->tablaSegmentos))
	{
		memcpy(stream + offset, list_get(pcb->tablaSegmentos, n), sizeof(t_tabla_segmantos));
		offset += sizeof(t_tabla_segmantos);
		n++;
	}

	buffer->stream = stream;

	crearPaquete(buffer, tipoMensaje, socket);
```

**Comment by camilamarinio** [comment]
ya pudimos solucionarlo pero no se como borrarlo por eso lo cerré

**Comment by iago64** [comment]
Buenas! 

No hay problema con que quede el issue, solo aprovecho a dejar el comment de que ante cualquier problema de memoria, no se olviden de usar `valgrind` para tener mas info de donde puede venir el error 😄 

Saludos.-
