### ISSUE TITLE
Consultas sobre parámetros de threads y void*

### ISSUE THREAD

**Issue by Gabi314** [sisoputnfrba/foro#2848]
Buenas tardes. Tengo una consulta respecto a los parámetros que reciben las funciones que toman los hilos al crearse. Supongamos que tengo:
```
	pthread_t hilo;
	int hiloCreado = pthread_create(&hilo, NULL, (void*) funcion, parametro);
	pthread_detach(hiloCreado);
```

con 
    
```
 void funcion(t_parametro parametro) {
}
```

Tengo entendido que `parametro` debería ser del tipo `void*` . Por ende en el lugar de `t_parametro` tiene que ir `void*` siempre? 
Sinceramente nunca supe bien cómo funciona el `void*`
Un struct de datos como por ej

```
typedef struct {
int ej1;
char * ej2;
t_list * ej3;
} t_parametro
```

puede funcionar en el ejemplo anterior?

O deberiámos tratar al `void* `siempre como el stream del paquete del tp0 (armando una cadena de datos dentro de un `void*` haciendo uso de `memcpy`)?

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va?

Para empezar, ¿qué es un puntero?
La memoria se encuentra indexada de a bytes, y un puntero es solamente un número entero que indica un índice dentro de esa memoria:

```
+-----------+------+
|                  |
+-----------+------+
0           n    tam-1
            ^
            esto es un puntero
```

Los punteros que más conocemos son los que tienen el tipo explícito. Éstos indican de qué tipo es el **contenido** al que apunta ese puntero. Por ejemplo, si es `int*` yo sé que va a medir 4 bytes, si es `char*` sé que va a medir 1, y así, según el `sizeof` del tipo:

```c
sizeof(char) // => es 1
sizeof(uint32_t) // => es 4
// ...etc
```
Esto le sirve al compilador para, por ejemplo, saber cómo se desreferencia un puntero:
```c
mi_struct_especial *a = struct_especial_create();
mi_struct_especial b = *a; // esto no lo podría hacer si no supiera el sizeof
```
O acceder a un valor que está dentro del struct:
```c
(*a).campo1 = 2;
a->campo1 = 2; // esto es un syntax sugar de la línea anterior
```

Sin embargo, al ser una dirección de memoria, el puntero en sí **siempre tiene el mismo tamaño**, no importa a lo que apunte. Todos estos tienen el mismo resultado:
```c
sizeof(char*) // => es 8 (en 64 bits)
sizeof(int*) // => es 8 (en 64 bits)
sizeof(mi_struct_especial*) // => es 8 (en 64 bits)
// ...etc
```

Entonces, ¿qué es un `void*`? Es un puntero a memoria que no sé de qué tipo es. Por ejemplo, `malloc()` devuelve un `void*` ya que no sabe para qué se va a usar esa memoria que devuelve.

Por último, para el caso del parámetro que se le pasa a la función de `pthread_create()`, el hecho de que reciba `void*` significa que "va a recibir un puntero a algo". ¿A qué? A lo que vos quieras, no hace falta que esté contiguo porque lo que se pasa no es el bloque de memoria en sí, sino que es solo un puntero.

Pero debe ser un **puntero a** algo, no solo un "algo", ya que lo que estás pasando debe medir siempre los 8 bytes que tiene un puntero. 

Por eso, retomando el ejemplo, para que funcione la función debería verse así:

```c
void funcion(t_parametro* parametro) {
}
```

Y el llamado a `pthread_create()` debe pasar un puntero que apunte al heap (o sea, que se haya creado con `malloc()`):

```c
t_parametro *parametro = malloc(sizeof *parametro);

// ...

pthread_t hilo;
int hiloCreado = pthread_create(&hilo, NULL, (void*) funcion, parametro);
pthread_detach(hiloCreado);
```
_(aclaro por las dudas que no hace falta hacer el `malloc` ahí mismo, vos podrías tener una función `t_parametro* parametro_create()` que inicialice la estructura y usar ese puntero que devuelve para pasárselo a `pthread_create`)_

Saludos

**Comment by Gabi314** [comment]
Agus te quiero mucho. Muchas gracias de verdad, quedó todo mucho más claro. 
Recién me di cuenta lo del `pthread_detach()` ahora lo corregimos.
