### ISSUE TITLE
DUDA - Tabla de paginas y marcos

### ISSUE THREAD

**Issue by valentinarau** [sisoputnfrba/foro#2850]
Hola buenas noches, teniamos una duda con respecto a la creacion e inicializacion de tablas de paginas para un nuevo proceso. 
Por un lado, creamos la tabla por segmento, pero tenemos dudas con respecto a las entradas y marcos asignados. No se nos ocurre bien como regulariamos la cantidad de marcos por proceso al crear / manipular la tabla. 
Hay que asignar marcos al momento de crearla? y que las entradas de las tablas que cree manejen esos mismos marcos siempre? o se haria a lo largo del tiempo? porque en ese caso habria que hacer una busqueda por una estructura que me sepa decir cuantos o quienes son los marcos de dicho proceso. 
![image](https://user-images.githubusercontent.com/82102044/201498186-5b44ed32-0192-4de3-9585-8d77120101de.png)
Tambien nos queda la duda porque, en esta imagen, aparece el numero de marco repetido. Entendemos que un proceso tendria numero de marcos repetidos porque tiene una cantidad maxima de marcos, pero nos complicamos al momento de la implementacion o de la logica inicial 
Saludos

**Comment by valentinarau** [comment]
Tengo Otra duda:
en el enunciado dice 
``` 
cada segmento creado contará con su propia tabla de páginas cuya  cantidad de entradas será definida por archivo de configuración.
```
Eso quiere decir que si tengo 4 segmentos, voy a tener 4 tablas con una cantidad N (definida por archivo de configuracion)? Porque me surgen dudas con el tema de los **Tamaños de los segmentos** No defino la cantidad de paginas que necesito en base a esos tamaños? o los tamaños de los segmentos son solo para direccionamientos??

**Comment by RaniAgus** [comment]
¡Buenas, Valen! ¿Cómo va?
En cuanto a la primera duda, 
> Por un lado, creamos la tabla por segmento, pero tenemos dudas con respecto a las entradas y marcos asignados. No se nos ocurre bien como regulariamos la cantidad de marcos por proceso al crear / manipular la tabla.
Hay que asignar marcos al momento de crearla? y que las entradas de las tablas que cree manejen esos mismos marcos siempre? o se haria a lo largo del tiempo? 

La asignación de marcos es, al igual que se explica en la teoría, **a demanda**. Lo cual significa que al crear la tabla de páginas no se debe cargar ninguna página en ningún marco, sino que arrancan todos con bit de presencia = 0 y se van cargando a medida que el CPU las vaya necesitando para ejecutar una instrucción.

> porque en ese caso habria que hacer una busqueda por una estructura que me sepa decir cuantos o quienes son los marcos de dicho proceso.

Exacto. El TP no aclara cómo deben estar modeladas estas estructuras para poder manejar los page faults, por lo que tienen más libertad sobre cómo implementarlo (de hecho, es una buena pregunta de coloquio 😉).

Por ejemplo, en un principio se me ocurre que agregando un bitmap de frames libres y un par de columnas a las tablas para implementar los algoritmos de reemplazo alcanzaría, pero no es la única alternativa válida y probablemente no sea la más simple.

> Tambien nos queda la duda porque, en esta imagen, aparece el numero de marco repetido. 

Recuerden que el **bit de presencia** determina la validez del resto de los valores de la fila: si es 0, lo único que me dice es que esa página _estuvo_ presente la última vez en el frame 5, pero ahora mismo solo está en swap.

> Entendemos que un proceso tendria numero de marcos repetidos porque tiene una cantidad maxima de marcos, pero nos complicamos al momento de la implementacion o de la logica inicial

En realidad, no. No debería haber números de marcos repetidos (entre las páginas presentes) ya que cuando tengan que bajar ese frame a swap no sabrían cuál página escribir 😅. La cantidad máxima de marcos solo indica hasta cuántas páginas podés tener presentes a la vez.

En cuanto a la segunda duda, creo que está muy relacionada con este issue #2843. Les recomiendo leer la respuesta de Lean y si quedó alguna duda avísennos.

¡Saludos!

**Comment by valentinarau** [comment]
Gracias Aguss!
