### ISSUE TITLE
Tamaño del programa en SWAP

### ISSUE THREAD

**Issue by CFedericoDavid** [sisoputnfrba/foro#2851]
Buenas, 
Para calcular el tamaño del programa que se reserva en swap, que es la suma de los tamaños de los segmentos
Se usan los tamaños reales o se puede hacer con el tamaño máximo que viene de configuración?
Gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

El tamaño de un proceso en SWAP va a te lo va a dar la cantidad de segmentos, el tamaño de las páginas y la cantidad de entradas por tabla.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas!
Para agregar algo más a la respuesta, la implementación en sí del "mapeo" de páginas a swap queda a discreción de cada grupo, no es necesario tener páginas "inválidas" (que se pasen del tamaño del segmento) mapeadas a SWAP ya que no se usarían, aunque sería una linda charla de coloquio ver las ventajas y desventajas de la solución que usaron.

Saludos!
     Lean

**Comment by CFedericoDavid** [comment]
Genial, entonces para el trabajo práctico queda a decisión del grupo, entiendo

Cierro el issue entonces
