### ISSUE TITLE
Reemplazo local con el algoritmo de Clock

### ISSUE THREAD

**Issue by adrielaran** [sisoputnfrba/foro#2852]
Buenas tardes!
Junto con el grupo nos surgieron dos dudas...
1) El reemplazo local de la tabla de paginas debería realizarse a nivel segmentos o  a nivel de paginas? 
2) Si tenemos una pagina que se encuentra en memoria física y por causa del algoritmo de Clock su Bit de Uso es igual a 0. Al solicitarse nuevamente y al encontrarse en memoria pero teniendo su Bit de Uso igualado a 0, debemos cambiarlo o continua quedando con el valor 0? Sabemos que en la teoría se cambia por 1 y queremos asegurarnos de su aplicación en el TP.

 Desde ya, muchas gracias!

**Comment by LeandroCarbajales** [comment]
Buenas!
La lógica del algoritmo de reemplazo clock y el alcance local es igual que como vemos en clase.
1. El reemplazo es local a las páginas del proceso, es decir, podrían reemplazarse páginas de distintos segmentos siempre que sean del mismo proceso.
2. Al referenciar una página se le vuelve a marcar el bit de uso en 1.

Saludos!
      Lean
