### ISSUE TITLE
Duda Scripts Memoria

### ISSUE THREAD

**Issue by camilamarinio** [sisoputnfrba/foro#2853]
Estuvimos viendo en las pruebas los scripts de memoria , y vimos que en las instrucciones MOV_IN  y MOV_OUT los parámetros están invertidos , no están según lo que dice el enunciado del tp .

Así esta en el enunciado : 
SET AX 1
ADD AX BX
**MOV_IN CX 4
MOV_OUT 8 DX**
I/O DISCO 10
I/O TECLADO AX
I/O PANTALLA BX
EXIT

y así esta en el script : 
SET AX 228
**MOV_OUT AX 0
MOV_OUT AX 4
MOV_OUT AX 8
MOV_OUT AX 16
MOV_IN 0 BX
MOV_IN 4 CX
MOV_IN 8 DX**
ADD AX BX
ADD AX CX
ADD AX DX
I/O PANTALLA AX
EXIT

**Comment by iago64** [comment]
Buenas! Cómo va?

Mil gracias por el aviso, los generamos rapido y nos quedaron invertidos 😄 
Ya se encuentran corregidos.

Saludos.-

**Comment by camilamarinio** [comment]
De nada ,Saludos !!
