### ISSUE TITLE
Script MEMORIA_3 sin instrucción EXIT

### ISSUE THREAD

**Issue by xyz-frba** [sisoputnfrba/foro#2854]
Hola!

Observamos que el script `MEMORIA_3` no tiene la instrucción `EXIT`

Y en nuestro TP estamos validando que los scripts tengan dicha instrucción; caso contrario, **CONSOLA** finaliza su ejecución sin enviar el set de instrucciones a **KERNEL**.

¿Es un error en el script o deberíamos eliminar la validación que estamos realizando?

Gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

No habíamos tneido en cuenta el tema del EXIT ya que ese script tiene que morir por _segment fault_ al momento de hacer la segunda instrucción, pero se la agregamos para evitar inconvenientes.

Saludos.-

**Comment by xyz-frba** [comment]
Muchas gracias!!
