### ISSUE TITLE
Consulta scripts PLANI_BASE

### ISSUE THREAD

**Issue by camilamarinio** [sisoputnfrba/foro#2855]
Buenas, 
Tenemos una consulta con respecto a los script de PLANI_BASE_2 , PLANI_BASE_3 , PLANI_BASE_4 y MEMORIA_3 
Los 4 son los únicos que al final tienen un enter ,esto esta bien que sea así ? porque en los demás scripts no esta. Y si hay un enter al final  nos rompe al ejecutar. 
Porque vincule nuestro repo con el que subieron de pruebas  y no puedo hacer cambios sobre eso.

**Comment by iago64** [comment]
Buenas! Cómo va?

Ahi ajustamos los scripts para que no tengan esa linea vacía al final.

Saludos.-

**Comment by camilamarinio** [comment]
Buenaas 
Genial, muchas gracias !!

Saludos
