### ISSUE TITLE
Duda sobre pruebas TLB

### ISSUE THREAD

**Issue by lrocampo** [sisoputnfrba/foro#2857]
Buenos días. Tenemos una duda con las pruebas TLB. Porque en nuestro TP el proceso A estaría finalizando por segmentation fault y no el proceso B. Y nos pusimos hacer las cuentas para ver por qué.

En la prueba TLB_1 hay una instrucción "MOV_OUT 576 AX" que es la que finaliza el proceso A por segmentation fault.

Considerando que, con el memoria.config de la prueba tlb, el tam_max_segmento es : 4 * 64 = 256 (cant de entradas por tabla * tamaño de pagina) y los segmentos son [160, 144, 32] 

Tomando el 576 como la dirección lógica, el número de segmento (que se calcula como 576 / 256) nos está dando 2.
El desplazamiento_segmento = 576 % 256 = 64.

Nos está dando que el segmento es el 2 (o sea el último segmento, de tamaño 32) pero el desplazamiento es 64. Entonces como el desplazamiento es mayor que el tamaño se va por segmentation fault.

Queremos saber si hubo un error en el archivo TLB_1 para que sucediera esto.

Por otro lado, por qué la TLB_2 se iría por segmentation fault? Si las direcciones lógicas son 0.

**Comment by lrocampo** [comment]
Muchas gracias!

**Comment by CFedericoDavid** [comment]
Buenas, cómo se da que el proceso B reemplaza paginas de TLB? si las primeras dos instrucciones 
`MOV_OUT 0 AX
MOV_IN BX 0`
son de la misma pagina, y la tercera instrucción
`MOV_OUT 64 AX`
ya es la que da SEG_FAULT, en qué momento reemplaza entradas en TLB? (además la cant. de entradas según config es de 4)

Gracias

**Comment by iago64** [comment]
@CFedericoDavid Hubiera sido un golaso que abras un issue nuevo.

Respondiendo tu consulta, se reemplaza 1 página y despues tenes un HIT de la tlb.

Saludos.-
