### ISSUE TITLE
Duda sobre tablas de páginas, segmentos y algunos logs de MEMORIA

### ISSUE THREAD

**Issue by istadius** [sisoputnfrba/foro#2858]
Buenas gente, me surgieron algunas dudas respecto al enunciado de MEMORIA:

1.  A la hora de crear las tablas de páginas para cada segmento yo les estoy asignando un id único autoincremental que estoy devolviendo a kernel y cpu para su uso. Entonces, en los mensajes que reuieren especificar una página (por ejemplo cuando se consulta por la presencia de una pag en un frame o cuando se pide cargar una pag en un frame) ademas del número de página  cpu y kernel deben enviarme el identificador de la tablar. ¿ese comportamiento es correcto o deben enviarme el PID y el número de segmento y yo averiguar a que tabla referenciar?. En caso de ser la segunda: ¿para que envio los identificadores de tablas?
2. Uno de los logs obligatorios de MEMORIA es "Acceso a Tabla de Páginas:" y no termino de entender ante que evento logueo esto. ¿Cuando se consulta si una pag esta  presente?¿cuando se la carga en un frame? ¿cuando se lee y escribe? ¿cuando se pone el bit de uno en 1? ¿todas las anteriores?
3. Y por último, respecto al bit de uso. Se coloca en 1 cuando la página:

- Se carga en ram
- Se consulta si esta presente y lo está
- Se lee o se escribe

¿me falta o me sobra algún caso?

Graias por su ayuda.

**Comment by iago64** [comment]
Buenas!

1.- El funcionamiento esta bien, solo les pedimos que ademas envíen el PID en los requests para poder ver en los logs que estan accediendo.

2.- El log es para cuando la CPU realice el primer acceso para saber en que marco esta una página, en caso de que tenga un marco asignado deberían devolver el valor del marco, caso contrario no.

3.- Estan bien los casos, son los mismos que se ven en la teoría 😉 

Saludos.-

**Comment by istadius** [comment]
Muchas gracias por las aclaraciones, saludos.
