### ISSUE TITLE
Duda sobre ENTRADAS_POR_TABLA y SEGMENTOS

### ISSUE THREAD

**Issue by pablomartinfranco** [sisoputnfrba/foro#2859]
Hola,
tenemos dudas al momento de traducir la direccion logica.

Estamos queriendo obtener el numero de segmento a partir de la direccion logica pero no logramos
interpretar si ENTRADAS_POR_TABLA es la cantidad de paginas del segmento en la tabla de paginas (TP), 
y en el caso que asi sea para que seria entonces el tamanio en bytes de cada segmento ?
porque entonces si ENTRADAS_POR_TABLA es igual para todas las TP por configuracion y el tamanio de pagina es fijo,
los segmentos tendrian todos el mismo tamanio en bytes ? que por lo visto no es asi porque los segmentos son variables.
Algo estamos interpretando mal.

**Comment by iago64** [comment]
Buenas! Cómo va?

Es una interesante pregunta, lo importante que tienen que tener en cuenta es que TAM_PAGINA x ENTRADAS_POR_TABLA les da el **_tamaño maximo del segmento_**, es decir, que un segmento no podría ocupar mas que eso, ahora esto no quita que un segmento pueda ocupar menos espacio.
Por eso el **_tam_max_segmento_** despues se utiliza para calcular el **_num_segmento_** pero la validación de segfault se hace contra el tamaño del segmento y no contra el **_tam_max_segmento_**.

Saludos.-

**Comment by pablomartinfranco** [comment]
Ah perfecto, entiendo entonces que TAM_PAGINA x ENTRADAS_POR_TABLA es para delimitar o convencionar de forma estatica la logica de las cifras en el direccionamiento, y que tamaño maximo del segmentoes para validar el seg_fault
Gracias
Saludos

**Comment by RaniAgus** [comment]
¡Buenas @pablomartinfranco! Paso a patrullar para avisar (para la próxima) que si la duda ya fue resuelta pueden cerrar el issue 👮🏻‍♂️

Si en un futuro ven que algo no terminó de cuadrar pueden tomarse la libertad de reabrirlo o abrir uno nuevo referenciando éste. 

¡Saludos!
