### ISSUE TITLE
Duda sobre prueba de estabilidad

### ISSUE THREAD

**Issue by CapriLucas** [sisoputnfrba/foro#2860]
Buenos días. Tengo una duda con la prueba de estabilidad. Porque estoy viendo un tema al convertir una dirección lógica y no sé si es un problema de la consigna o de nuestro TP en sí.

En la prueba [ESTABILIDAD_2](https://github.com/sisoputnfrba/geck-pruebas/blob/main/ESTABILIDAD_2) hay una instrucción `MOV_OUT 256 AX` (línea 4) que no debería traer ningun tipo de problemas según los expected results.

Considerando que, con el [memoria.config de la prueba estabilidad](https://docs.google.com/document/d/1qxF4h9dkL5L6X6P8qts997wTC1qLxIg6ElZzlU1Xgi4/edit#heading=h.jkjwaano6aec), el tam_max_segmento es : 4 * 64 = 256 (cant de entradas por tabla * tamaño de pagina) y **el único** segmento es [1024]

Tomando el 256 como la dirección lógica, el número de segmento (que se calcula como 256 / 256) da 1.
El tema es que los numeros de segmentos se empiezan a contabilizar con un índice en 0, por lo que el segmento 1 en esta instancia de consola ESTABILIDAD_2 no existe. (esto hace implosionar todo por supuesto jaja)

Quería saber si se me está escapando algo. Muchas Gracias!

**Comment by RaniAgus** [comment]
¡Buenas! Efectivamente estaba mal la configuración de Memoria, ya que hay segmentos de 1024 pero el tamaño máximo de segmento era de 256. Ya se encuentra corregido en el doc.

¡Gracias!
Saludos
