### ISSUE TITLE
Memory Leak en pthread_create

### ISSUE THREAD

**Issue by GRodriguezPardo** [sisoputnfrba/foro#2861]
Hola,
tengo un problema a la hora de correr los módulos con valgrind.  Valgrind me dice que tengo un memory leak al llamar la funcion " pthread_create ". Vi varios issues en donde se menciona esto pero no me quedo clara la respuesta. El problema es exactamente el mismo que se menciona en los siguientes issues.

### 🔎 Búsqueda en foros
#2284 
#2222 
[#1617 (comment)](https://github.com/sisoputnfrba/foro/issues/1617#issuecomment-610735218)

**Comment by LeandroCarbajales** [comment]
Buenas!
Si tenés el mismo mensaje de Valgrind cuando termina el proceso que [acá](https://github.com/sisoputnfrba/foro/issues/1617#issuecomment-610745850) entonces no es un Memory Leak justamente por lo que explica el comment anterior, los Memory Leaks son cuando se pierde memoria durante la ejecución del proceso, cualquier "pérdida" que pueda darse al finalizar es irrelevante ya que igualmente el sistema operativo va a liberar toda la memoria asignada al proceso.

Queda más clara la idea?

**Comment by GRodriguezPardo** [comment]
Siii genial, gracias! Agrego otra consulta mas. 
Al ejecutar con Valgrind, la memoria que utiliza el kernel según me indica el HTOP va aumentando constantemente al correr las pruebas, y no desciende incluso cuando finalizan consolas. Esto es algo que noté particularmente al correr las pruebas de estabilidad que por las instrucciones que tienen, realizan muchas I/O, y en consecuencia crean muchos hilos. 
Por este mensaje que me mostraba Valgrind, pensé que esa crecida constante de memoria era culpa de los hilos (Al finalizar me decía que habia una enorme cantidad de memoria posiblemente perdida en el pthread_create que resolvía las I/O). 
Lo raro es que al ejecutar los modulos por fuera de Valgrind, esto nunca sucede, la memoria nunca crece, se mantiene en un rango constante.
Puedo asumir entonces que es un problema de Valgrind a la hora de cerrar los hilos?

**Comment by LeandroCarbajales** [comment]
Buenas!
Valgrind normalmente va a ocupar más memoria (y quizás hasta te salve de algun segfault) porque justamente observa todo lo que ocurre durante la ejecución para darte el análisis. Las pruebas las vamos a correr siempre sin Valgrind para corroborar el uso de Memoria en htop.

**Comment by GRodriguezPardo** [comment]
Genial gracias!
