### ISSUE TITLE
Duda sobre prueba de estabilidad

### ISSUE THREAD

**Issue by CapriLucas** [sisoputnfrba/foro#2862]
Buenos días. Tengo una duda con la prueba de estabilidad. Porque estoy viendo un tema en una instrucción

En la prueba [ESTABILIDAD_1](https://github.com/sisoputnfrba/geck-pruebas/blob/main/ESTABILIDAD_1#L30) línea 30 hay una instrucción `MOV_IN 0 BX` (línea 30) que tiene los parámetros al revés.
Debería mantener esos parametros como mov_out o alternar los parámetros?.
Muchas Gracias!

**Comment by LeandroCarbajales** [comment]
Buenas! Posiblemente sea una equivocación en el orden de los parámetros.
A la brevedad lo revisamos y lo corregimos, gracias por avisar! 😄

**Comment by LeandroCarbajales** [comment]
Fixeado!

**Comment by CapriLucas** [comment]
Gracias!
