### ISSUE TITLE
Cantidad de Colas de Bloqueo por Dispositivo

### ISSUE THREAD

**Issue by fdimatteo-utn** [sisoputnfrba/foro#2864]
Estimados,

Tengo una duda respecto de la cantidad de colas que debería manejar Kernel para bloquear dispositivos.

Es claro que hay un minimo de 2 (una para teclado y otra para pantalla), mi duda es respecto a los demas dispositivos. 

Es decir, si tomamos como ejemplo DISCO e IMPRESORA, cada uno de estos dispositivos cuenta con una cola específica para cada uno de ellos o todos convergen a unica cola general (que no es teclado ni pantalla)?

Gracias!!

**Comment by iago64** [comment]
Buenas! Cómo va?

Cada dispositivo va a tener su cola propia, la cantidad la va a determinar los dispositivos que tengas en la config del kernel. 

Si tenes: DISPOSITIVOS_IO=[DISCO] solo vas a tener una cola
Si tenes: DISPOSITIVOS_IO=[DISCO, WIFI, MODEM, RED, DISPOSITIVO_EXPERIMENTAL] solo vas a tener 5 colas, una para cada dispositivo.

Por lo tanto la cuenta final de colas de IO va a ser tamaño del array de DISPOSITIVOS_IO + 2xConsola (Una para TECLADO y otra para PANTALLA)

Saludos.-

**Comment by fdimatteo-utn** [comment]
Muchas Gracias Damian!!!
Quedo clarisimo, cierro el Issue
