### ISSUE TITLE
Dudas sobre Prueba Memoria (Cantidad de accesos a SWAP)

### ISSUE THREAD

**Issue by LautaroRobles** [sisoputnfrba/foro#2866]
Buenas.

Viendo el programa del proceso A no nos queda claro porque debería haber distintas cantidades de acceso a SWAP. Entendemos un acceso a SWAP como SWAP IN o SWAP OUT.
Un SWAP IN ocurre cuando hay que buscar un proceso en DISCO y SWAP OUT ocurre cuando la victima tiene bit M = 1.

En esta prueba entendemos que como hay 2 entradas a tabla en memoria, tenemos 2 frames disponibles.

El programa del proceso A tiene 4 MOV OUT al principio.

MOV_OUT 0 AX
MOV_OUT 128 AX
MOV_OUT 256 AX
MOV_OUT 384 AX

Entonces entendemos que sucederian 4 page faults y 2 reemplazos aca. Con 2 accesos a SWAP para escribir esos 2 reemplazos (porque tienen el bit M = 1)

Cuando se ejecute
MOV_IN BX 0

La pagina que se va a reemplazar tiene bit M = 1, entonces ocurren 2 accesos a SWAP: 1 para leer del SWAP el "0" y otro para escribir en el SWAP el reemplazo (o sea el "256").
Pero luego de finalizado este reemplazo la pagina del "0" tendria como bit de U = 1 y M = 0 porque es solo lectura, no escritura.

Cuando se ejecute
MOV_IN DX 384

El "384" ya esta cargado en la memoria entonces no sucede ningun PAGE SWAP

Cuando se ejecute
MOV_IN CX 128

Se debe reemplazar por "0" o "384", si se elije "0" hay solo 1 acceso a SWAP (para leer) pero si se elije "384" hay 2 accesos (1 para leer y otro para escribir "128" que estaba con M = 1).
Pero no importa cual algoritmo CLOCK o CLOCK-M se use, siempre se va a reemplazar por "0" y nunca por "384".

¿Es nuestra lógica correcta?

Cuando escribo "0", "384" etc. Es como una referencia a la pagina del segmento, para no poner segmento: 0, pagina: 0 y segmento: 3, pagina: 0.

**Comment by RaniAgus** [comment]
¡Buenas!

> Pero no importa cual algoritmo CLOCK o CLOCK-M se use, siempre se va a reemplazar por "0" y nunca por "384".
> ¿Es nuestra lógica correcta?

No es correcta, uno de los algoritmos contempla el bit de modificado y termina priorizando las páginas que no están modificadas para ahorrarse accesos de escritura a swap, pero el otro no.

Saludos

**Comment by LautaroRobles** [comment]
Claro, pero en todas las veces que lo probamos los dos algoritmos terminan desalojando el que no esta modificado y ambos se ahorran un PAGE OUT.

Porque el algoritmo hace esto

Clock:
Chequeo "0" (U=1|M=0)-> U == 0? -> NO -> entonces seteo U = 0
Chequeo "384" (U=1|M=0)-> U == 0? -> NO -> entonces seteo U = 0
Comienzo de nuevo el algoritmo
Chequeo "0" (U=0|M=0)-> U == 0? -> SI, es la VICTIMA

En Clock-M tambien se encuentra "0" como la victima porque justamente es el que no esta modificado.
Pero en CLOCK normal depende del orden en la tablas de paginas, y en nuestro caso siempre esta "0" antes de "384".

**Comment by iago64** [comment]
Buenas! Cómo va?

Tu problema es que estas buscando la diferencia en el punto incorrecto de la prueba 😉, la misma se da en el último reemplazo, ya que al momento de hacer `MOV_IN 128 CX` lo que haces es reemplazar una página en memoria y ahi es donde en CLOCK-M va a pesar el bit de modificado y va a evitarte 1 acceso a swap.

Saludos.-

**Comment by LautaroRobles** [comment]
En el momento en el que se va a hacer `MOV_IN CX 128` las 2 paginas que estan presentes son las que corresponden al `MOV_IN BX 0` y al `MOV_IN DX 384`, donde el "0" tiene U=1|M=0 y el "384" tiene U=1|M=1.
Entonces segun lo que vos decis CLOCK normal deberia desalojar "384" y CLOCK-M deberia desalojar "0"?

**Comment by iago64** [comment]
Una imagen vale mas que mil palabras:

![image](https://user-images.githubusercontent.com/1622109/204803422-05930518-d31b-4ab2-94df-2ab481e904d9.png)

**Comment by LautaroRobles** [comment]
Pero... El algoritmo de CLOCK podría desalojar "0" (el que no esta modificado) si empieza chequeando con ese, no?

Como puse antes:
> Clock: Chequeo "0" (U=1|M=0)-> U == 0? -> NO -> entonces seteo U = 0 
> Chequeo "384" (U=1|M=0)-> U == 0? -> NO -> entonces seteo U = 0 
> Comienzo de nuevo el algoritmo Chequeo "0" (U=0|M=0)-> U == 0? -> SI, es la VICTIMA

**Comment by RaniAgus** [comment]
Tengan en cuenta que en ambos algoritmos el puntero queda en "384" a partir del reemplazo anterior, por lo que:
- CLOCK lo elige luego de _pegar una vuelta_ seteando U=0.
- CLOCK-M también pega la vuelta pero no lo elige porque primero busca U=0, M=0 y luego U=0, M=1.

**Comment by LautaroRobles** [comment]
Genial, creo que eso es lo que nos estaba faltando. Nosotros NO estábamos usando un puntero!
