### ISSUE TITLE
Error con instrucción EXIT de ESTABILIDAD_1

### ISSUE THREAD

**Issue by juliangarcia45** [sisoputnfrba/foro#2867]
Buenas, estamos corriendo las pruebas y no tenemos problemas con ninguna de la de estabilidad, excepto con ESTABILIDAD_1 que es que no reconoce la instrucción EXIT, es con el único .txt que pasa, la forma que encontramos de solucionarlo fue copiando el EXIT de otro archivo de instrucciones porque incluso borrándolo y escribiéndolo de nuevo tampoco lo reconoce. En el código para reconocer las instrucciones lo hacemos con strcmp.

Por otro lado tenemos una duda con las pruebas de memoria, las entradas de la TLB son 0, tenemos que contemplar un caso en el que  no hay TLB?

**Comment by RaniAgus** [comment]
Hola Juli, 

> no tenemos problemas con ninguna de la de estabilidad, excepto con ESTABILIDAD_1 que es que no reconoce la instrucción EXIT, es con el único .txt que pasa

¿Puede que tenga que ver con que se nos escapó un `\n` al final del archivo? Si es así, ahí recién lo corregí, hagan un pull del repo de pruebas: https://github.com/sisoputnfrba/geck-pruebas/commit/b019d77f77e5a616cacf3abe3d569e7df279c8f5

> Por otro lado tenemos una duda con las pruebas de memoria, las entradas de la TLB son 0, tenemos que contemplar un caso en el que no hay TLB?

Claro, en ese caso podrían pensarlo como que siempre hay TLB miss y siempre se consulta a la memoria para hacer las traducciones.

Saludos

**Comment by juliangarcia45** [comment]
Buenísimo Rani, gracias.

**Comment by juliangarcia45** [comment]
Hola, no me había dado cuenta pero ESTABILIDAD_2 también tiene el EXIT con un \n de mas jajsjsj, ESTABILIDAD_1 ya funciona bien.

**Comment by iago64** [comment]
Buenas! Cómo va?

Estas seguro que esa linea extra no la agregaron uds en alguna prueba? Porque revisando el repo, el último cambio de [ESTABILIDAD_2](https://github.com/sisoputnfrba/geck-pruebas/blob/main/ESTABILIDAD_2) es de hace 10 días y no tiene ninguna linea vacía al final.

Saludos.-

**Comment by juliangarcia45** [comment]
Tenes razón, se ve que en algún momento lo edite sin querer, raro que no me haya avisado que lo modifique cuando pullee, gracias!
