### ISSUE TITLE
Entradas en la TLB

### ISSUE THREAD

**Issue by carrilloFN** [sisoputnfrba/foro#2868]
Buenas!, tengo una consulta sobre las entradas de la TLB, la cantidad de entradas que tiene (que vienen dadas por archivo de config), ¿es para todos los procesos o es la cantidad que puede ocupar cada proceso?, es decir, si un proceso hizo muchos accesos a memoria y cargo sus 4 entradas (máximas por config), y viene otro proceso, ¿este proceso debería "pisar" las entradas del anterior o solamente las voy cargando en la TLB y las recupero a medida que los procesos las requieran?

## TLB
> Para agilizar el proceso de traducción, el módulo CPU contará también con una caché TLB. 
> La misma deberá tener obligatoriamente la estructura [ pid | segmento | página | marco ] 
> y se definirá por archivo de configuración:
> La cantidad de entradas
> El algoritmo de reemplazo, que puede ser FIFO o LRU.
> Esta caché deberá limpiar los registros asociados a los procesos que finalicen.

**Comment by LeandroCarbajales** [comment]
Buenas!
Al igual que como vemos en clase y en los ejercicios, las entradas de la TLB se comparten entre todos los procesos, por lo que el algoritmo de reemplazo podría pisar entradas de otro proceso tranquilamente.

Saludos!
        Lean

**Comment by carrilloFN** [comment]
Perfecto, gracias Lean!, cierro el issue.
