### ISSUE TITLE
Duda con respecto a la lectura y escritura de Memoria

### ISSUE THREAD

**Issue by FelipeAlborch** [sisoputnfrba/foro#2870]
Buenas! Estoy teniendo, con mi grupo, dudas para encarar la parte de leer y escribir en Memoria, nos quedamos un poco estancados  y no estaríamos pudiendo encontrarle la vuelta.

Por el momento, tenemos las siguientes funciones:
```c
void leer_memoria(int direccion_fisica)
{
  Logger *logger = iniciar_logger_cpu();
  Paquete *paquete = crear_paquete(LEER_DE_MEMORIA);
  agregar_a_paquete(paquete, &direccion_fisica, sizeof(int));

  enviar_paquete_a_servidor(paquete, ESTRUCTURA_MEMORIA.SOCKET_MEMORIA);
  char *valor = obtener_mensaje_del_servidor(ESTRUCTURA_MEMORIA.SOCKET_MEMORIA);
  log_info(logger, "Se recibio el valor leido %s de memoria", valor);
  free(valor);
  eliminar_paquete(paquete);
  log_destroy(logger);
}
```

```c
void escribir_memoria(int direccion_fisica, int valor_a_escribir)
{
  Paquete *paquete = crear_paquete(ESCRIBIR_EN_MEMORIA);
  agregar_a_paquete(paquete, &direccion_fisica, sizeof(int));
  agregar_a_paquete(paquete, &valor_a_escribir, sizeof(int));
  enviar_paquete_a_servidor(paquete, ESTRUCTURA_MEMORIA.SOCKET_MEMORIA);
  eliminar_paquete(paquete);

  char *confirmacion = obtener_mensaje_del_servidor(ESTRUCTURA_MEMORIA.SOCKET_MEMORIA);
  free(confirmacion);
}
```

No estaríamos sabiendo, en ambos casos, desde CPU, que variables mandarle a Memoria para hacer las peticiones tanto de lectura como de escritura. Tenemos las estructuras, tanto de Memoria como de CPU ya definidas, pero no se nos ocurre, concretamente, que seria lo que mandar a Memoria desde CPU para las peticiones, como mas arriba detallé.

**Comment by iago64** [comment]
Buenas! Cómo va?

La comunicación de la memoria esta definida en la hoja 24, donde tenes por un lado las funciones o peticiones que tiene que resolver la memoria contra el kernel (Inicio y fin de procesos o atender un Page Fault) y las funciones o peticiones que tiene que responder para la CPU:

- Acceso a tabla de páginas
En este caso fijate que lo que te va a devolver es el marco en cual se encuentra una página, por lo que minimamente vas a tener que pasarle los datos que necesite la memoria para encontrar la página en las estructuras que tengan definidas, por ejemplo se me ocurre que el número de página y el segmento al cual pertenece pueden ser un buen punto de partida.

- Acceso a espacio de usuario 
En el caso de acceso al espacio de usuario tenes 2 acciones que son leer y escribir, en el caso de leer es facil, la CPU ya en la MMU hizo todos los calculos necesarios y te va a tener que pasar la posición de la cual quiere leer y cuanto quiere leer, *en este TP **TODAS las lecturas y escrituras son de 4 bytes***. En el caso de escritura al igual que para leer la CPU hizo todas las cuentas entonces te va a tener que pasar la dirección, pero ademas va a tener que pasarte **que** es lo que tiene que escribir, por lo tanto vas a tener 2 parametros.

Saludos.-

**Comment by FelipeAlborch** [comment]
Perfecto, ahí nos queda mas claro. Muchas gracias!
