### ISSUE TITLE
Duda de teclado y pantalla como recursos de consola

### ISSUE THREAD

**Issue by Gabi314** [sisoputnfrba/foro#2871]
Hola, quería consultar si cada consola tiene su propia pantalla y teclado, y si pueden usarlas al mismo tiempo. En un soporte nos dijeron que no hay una sola pantalla y un solo teclado para todas las consolas, sino que cada consola dispone de amobos recursos. Por ende asumimos que tranquilamente dos consolas podrían usar la pantalla a la vez por ejemplo y por lo tanto no deberían haber cola de procesos de pantalla ni de teclado. Sin embargo en la consigna se las presenta como colas: 

> El kernel utilizará el diagrama de 5 estados para ordenar la planificación de los procesos. Dentro del estado BLOCK, se tendrán múltiples colas.
> Las 2 primeras serán fijas y asociadas a cada consola que haya ingresado un proceso al sistema, ya que deberán enviar un mensaje a la misma y dejar el proceso bloqueado hasta recibir su respuesta:
> Pantalla: se deberá leer el registro que el módulo CPU nos informó, enviar su valor al módulo Consola para que lo imprima y esperar a que responda.
> Teclado: se deberá recibir un valor desde el módulo Consola y guardarlo en el registro que el módulo CPU nos informó.

Vimos eso y nos confundió un poco. Esperamos su respuesta. Desde ya, gracias.

**Comment by LeandroCarbajales** [comment]
Buenas!
Pudieron ver alguno de los issues cerrados al respecto?
Se respondió sobre esta misma duda en estos issues #2864, #2839 y #2836

Pueden citar comentarios de los mismos acá si algo no quedó claro y lo vemos :)

Saludos!
       Lean

**Comment by Gabi314** [comment]
Hola, mil disculpas,  no los habíamos revisado. 


> 2- Como respondí en ese mismo issue, nunca se encolarían por esos dos dispositivos ya que habría uno por proceso, la idea de los mismos es que justamente podamos bloquear al proceso sin tener que encolarlos detrás de otros procesos que también estén bloqueados, por ejemplo, podríamos bloquear P1 por su teclado y luego P2 por su teclado, sin embargo, luego podríamos desbloquear primero a P2 y dejar a P1 bloqueado indefinidamente a pesar de haberse bloqueado antes que P2. Este mismo caso no podría pasar con ninguno de los dispositivos "compartidos" del Kernel (los definidos por archivo de config).
> Otro ejemplo con "pantalla" es que simplemente querramos que un proceso se bloquee por un período muy corto de tiempo sin depender de que haya otros procesos bloqueados o no.
(issue#2839)

Creo que la idea de las colas de teclado y pantalla la cumplimos. Nosotros no usamos estructuras que representen esas colas en sí. Para los otros dispositivos sí lo hacemos, pero en el caso de teclado y pantalla, cuando la cpu le devuelve el pcb al kernel por esas IO, nos manejamos creando un hilo y delegándole la tarea de realizar el procedimiento de la interrupción con la consola correspondiente. Mientras tanto la planificación sigue su curso tomando el proceso que tenga mayor prioridad en la cola (o colas) de ready ( en caso de que tengan procesos) y enviándolo a ejecutar. Cuando el hilo termina la tarea que se le dio, mete al proceso en un cola de ready y muere. 

Estaríamos bien por ese lado entonces o hay algún requisito que nos comimos?

**Comment by LeandroCarbajales** [comment]
Lo veo bien :)

**Comment by Gabi314** [comment]
Perfecto. Muchas gracias!
