### ISSUE TITLE
Obtención de Dirección Física en Memoria 

### ISSUE THREAD

**Issue by TomasGliozzo** [sisoputnfrba/foro#2873]
Tengo un problema al escribir en memoria, CPU me manda la dirección física y el contenido a escribir por socket. Lo que entiendo es que al recibir la dirección física al escribir, estaría obligado a escribir en el marco que CPU me índica, en vez de escribir en el primero que pueda o el que resulte de aplicar un algoritmo de reemplazo (siempre manejandome dentro de una tabla de páginas dada por un proceso y segmento determinado). El problema es que como no se de ante mano la dirección física, no se como escribirlo en memoria. Puedo crear mi propia ec y liberarme de la idea de dirección física para manejo interno, o asignarle una dirección predefinida a cada marco para que siempre lea y escriba en el mismo lugar? 
Desde ya muchas gracias y espero su respuesta.

**Comment by RaniAgus** [comment]
¡Buenas! Para ir ordenando un poco...

Desde el lado de la Memoria, cuando recibe un pedido de lectura o escritura a partir de una dirección física, lo único que debe hacer es, dentro del **espacio de usuario** (representado por un `void*` inicializado con `malloc(TAMANIO_MEMORIA)`), desplazarse los bytes que indique la dirección física y escribir o leer el dato de ahí, nada más. Al tratarse de una dirección física, no existe distinción de frames en este paso.

Dicho esto, el paso previo a éste es la conversión de dirección lógica a dirección física, que es responsabilidad de la CPU y se encuentra explicada en el enunciado en la sección de ese módulo. La misma requiere de otras interacciones con el módulo Memoria para consultar sus **tablas de páginas**, pero no para acceder directamente al **espacio de usuario** de la misma.

Saludos
