### ISSUE TITLE
Como averiguo el tamaño de un proceso 

### ISSUE THREAD

**Issue by Alexander-Ferreira** [sisoputnfrba/foro#2874]
### Nose como encontrar el tamaño del proceso 
Hola que tal buenos días, tengo una consulta, como hayo el tamaño de un  proceso, ya que bajo mi entendimiento ese dato debería venir del pcb, pero según unos compañero ese dato viene de archivo de configuración de memoria , o tal vez es un error se debería calcular con los datos dados pero nose con cuales desde ya muchas gracias.

**Comment by RaniAgus** [comment]
¡Buenas!

Antes que nada, para la próxima, el texto que está entre `<!--` y `-->` no lo vemos ya que es un comentario de HTML (ahí lo corregí).

Dicho esto, no existe un tamaño del proceso en sí, sino un tamaño para cada segmento, los cuales están definidos en el config de cada consola:

Campo | Tipo | Descripción
-- | -- | --
SEGMENTOS | Lista | Lista ordenada de los tamaños de los segmentos de Datos del proceso en los cuales podrá leer o escribir.

Y luego son enviados al Kernel para que éste los guarde en el PCB (cito pág. 14):

> Tabla de Segmentos: Contendrá los tamaños de los segmentos de datos del proceso y el número o identificador de tabla de páginas asociado a cada uno.

Lo que sí define la Memoria es el tamaño del espacio de usuario:

Campo | Tipo | Descripción
-- | -- | --
TAM_MEMORIA | Numérico | Tamaño expresado en bytes del espacio de usuario de la memoria.

<hr>

De paso, aprovecho para hacer una fe de erratas de algo que recuerdo haberles comentado hoy en soporte: si bien se pueden dar varios page faults en paralelo, se atienden uno a la vez. 

Esto ocurre porque ni bien se produce el page fault la Memoria **solo** debe devolverle al CPU el mensaje de page fault, y es el Kernel quien se comunica con la Memoria para disparar el algoritmo.

Hay una sección en Kernel que explica cómo debe implementarse (pág. 15-16) pero, para tener en cuenta, como solo debe haber una conexión entre Kernel y Memoria, habrá que sincronizar esos mensajes para que se den uno a la vez. Es decir, hasta no obtener la respuesta del primer page fault no se debe procesar la siguiente para no tener condiciones de carrera, similar a lo que comentamos en este issue: https://github.com/sisoputnfrba/foro/issues/2863#issuecomment-1327697424

Saludos, y mil disculpas por el malentendido

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, ante cualquier consulta pueden reabrirlo o abrir uno nuevo. Saludos
