### ISSUE TITLE
Problema con pruebas de memoria 

### ISSUE THREAD

**Issue by camilamarinio** [sisoputnfrba/foro#2875]
Buenas 
Estamos teniendo un problema  en las pruebas de memoria , ya que se ejecuta en vez del scrip de memoria 1 , 2 y 3 , se ejecutan 1 ,3 y 3. 
Ya miramos los scrip nuestros , están correctos y estuvimos viendo de donde venia el error . ejecutando 1 y 2 funciona , ejecutando 2 y 3 también funciona , pero no cuando ejecutamos los 3 juntos. 
Estuvimos haciendo un par de pruebas y nos dimos cuenta que el problema esta cuando ejecuta el proceso 1 del scrip de memoria 1   y llegan los demás , el 2 se encola en la lista new perfecto , pero cuando llega el 3 pisa al 2 , se escribe 2 veces .No tenemos idea de porque.
Esto lo probamos con otros scrip en el grado de multiprogramación 2 y 4 procesos , pasa lo mismo los últimos 2 se repiten , en vez de hacer 1 , 2 , 3 y 4 hace 1, 2, 4 y 4. 
El agregar a la lista new tiene mutex porque es una variable global. 

Por otro lados las pruebas de planin corren perfecto.

No sabemos porque esta pasando esto , el código de pasar a new es este:
el mutex y la lista están inicializados
```
void pasar_a_new(t_pcb *pcb)
{
	pthread_mutex_lock(&mutex_lista_new);
	list_add(LISTA_NEW, pcb);
	pthread_mutex_unlock(&mutex_lista_new);

	log_debug(logger, "Paso a NEW el proceso %d", pcb->id);
}
```

**Comment by iago64** [comment]
Buenas! Cómo va?

Estan debugueando el código y estan viendo que no se les pise ninguna variable? 
Porque me suena raro que con el código que tienen se les "dupliquen" los pcb sin mayor explicación, si saben que ahi es en el único lugar donde agregan los pcb a la lista de NEW, les diría que revisen cuando sacan los pcb de NEW para pasarlos a READY, no sea cosa de que en ese momento sea que se les esten pisando las referencias.

Saludos.-

**Comment by camilamarinio** [comment]
Sisi , estuvimos mirando y vimos que el problema estaba cuando el proceso entraba a new . Ya pudimos solucionarlo, era un tema de que se pisaban entre si porque no les estábamos reservando bien la memoria.
Gracias , Saludos !
