### ISSUE TITLE
Duda acerca de como atender un PF

### ISSUE THREAD

**Issue by FelipeAlborch** [sisoputnfrba/foro#2876]
Buenas! Nos surgió una duda con mi grupo acerca de la atención de un PF. El mismo puede ocurrir cuando CPU le solicita un marco a Memoria, el problema seria que nosotros cuando atendemos el PF lo hacemos con la dirección física, pero al haber un PF y no poder haberle mandado a CPU el numero de marco para poder calcular la dirección física y, posteriormente, mandarle esa misma dirección física a Memoria no estaríamos sabiendo como poder atender el PF, a continuación les dejo como tenemos las funciones:

void atender_page_fault(int pid, int sid, int nro_pag, int direccion_fisica)
{ //TODO
  tabla_de_paginas* tabla = obtener_tabla_de_paginas(pid,sid);
  pagina* pagina_buscada = leer_de_swap(pid,sid,nro_pag);
  marco* marco;

  if(!memoria_principal_llena() && tiene_marcos_por_asignar(pid)) //BUSCAR UNA PAG EN BLANCO PARA ESCRIBIR.
  {
    marco = primer_marco_libre(pid,sid);
    completar_marco(marco, pid, sid, pagina_buscada);

    log_lectura_pagina_swap(pid,sid,marco->marco_id,nro_pag);

    escribir_en_memoria_principal(pagina_buscada->contenido, direccion_fisica, pid);

    tabla->cant_pags_en_memoria++;
    pagina_buscada->marco_asignado = marco;
    bits_pag_escritura_en_memoria(pagina_buscada);
  }
  else //REEMPLAZAR
  {
    marco = aplicar_algoritmo_de_reemplazo(tabla, pagina_buscada);

    log_lectura_pagina_swap(pid,sid,marco->marco_id,nro_pag);

    asignar_pagina_al_marco_reemplazado(pagina_buscada, marco);

    escribir_en_memoria_principal(pagina_buscada->contenido, direccion_fisica, pid);
    bits_pag_escritura_en_memoria(pagina_buscada);
  }
}

**Comment by RaniAgus** [comment]
¡Buenas! El page fault se debe atender usando la **dirección lógica** ya que, justamente, la página a la que apunta la dirección lógica no se encuentra cargada en memoria física y, por ende, no existe la dirección física en ese momento. En otras palabras, si la CPU ya logró obtener la dirección física no habría page fault, porque la página está presente.

Una vez Kernel envíe el mensaje para disparar el algoritmo de page fault, es la Memoria la encargada de llevar el seguimiento de los frames libres (o de hacer el reemplazo correspondiente) para cargar la página en un frame en memoria.

Saludos

**Comment by FelipeAlborch** [comment]
Perfecto, Agus! Muchas gracias. Ahí lo pudimos resolver
