### ISSUE TITLE
Consulta - Páginas por segmento

### ISSUE THREAD

**Issue by Diego1939** [sisoputnfrba/foro#2877]
Buenas, tenia una duda con la cantidad de paginas que creamos para cada segmento.
Al ser fijas las entradas por tabla y al haber una tabla por segmento, cada segmento, independientemente de su tamaño, tendría la misma cantidad de paginas en swap? o tenemos que crear una determinada cantidad de paginas de acuerdo al tamaño de cada segmento?

**Comment by LeandroCarbajales** [comment]
Buenas!
Dependiendo del tamaño del segmento, habría entradas de su tabla de páginas que no se accederían nunca (saltaría antes el seg fault), por lo que no necesitarían asignarles espacio en SWAP.

Les cierra la duda?
Saludos!
       Lean

**Comment by Diego1939** [comment]
Si si, muchas gracias
