### ISSUE TITLE
Consulta sobre la automatización de las pruebas.

### ISSUE THREAD

**Issue by FelipeAlborch** [sisoputnfrba/foro#2878]
Buenas! Con mi grupo teníamos una duda y queríamos pedir recomendaciones acerca de como hacer de forma mas sencilla el remplazo de los archivos .config para poder correr de forma menos tediosa cada prueba.
Se nos ocurrió reemplazas las config con un script de bash para cada prueba, pero quizás ya tienen una solución recomendada.

**Comment by iago64** [comment]
Buenas! Cómo va?

Respecto a las config pueden hacer varias cosas, la mas facil es tener todos los archivos de config ya creados y subidos al repo y solamente cambiar el parametro a la hora de correr cada prueba, despues si quieren mandarse a hacer un script en bash pueden hacerlo pero a menos que esten super confiados de que todas las pruebas corren perfecto no les recomendamos que inviertan tiempo en eso.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Solo me sumo al comentario de Dami para agregar que ésta y otras recomendaciones para la entrega se encuentran mencionadas en la [guía de despliegue de TP](https://docs.utnso.com.ar/guias/herramientas/deploy.html). Saludos

**Comment by FelipeAlborch** [comment]
Pefecto! Muchas gracias a los dos.
