### ISSUE TITLE
Duda para leer en SWAP

### ISSUE THREAD

**Issue by FelipeAlborch** [sisoputnfrba/foro#2880]
Buenas! Con mi grupo estamos teniendo un problema para leer datos en la SWAP. La funcion que tenemos es la siguiente:

```c
Pagina* leer_de_swap(int pid, int sid, int nro_pag) 
{
  Tabla_de_Paginas* tabla = obtener_tabla_de_paginas(pid,sid);
  log_info(logGlobal, "Tabla de paginas [%d] obtenida correctamente", tabla->id_tabla);
  Pagina* pag_buscada = list_get(tabla->entradas,nro_pag);

  int tam_pagina = MEMORIA_CONFIG.TAM_MEMORIA;

  int offset_pag = offset_pagina(pid, sid, nro_pag); 
  log_info(logGlobal, "Offeset de la pagina [%d]: %d", pag_buscada->nro_pagina, offset_pag);

  u_int32_t contenido_leido;

  realizar_espera_swap();
  contador_accesos_disco++;

  fseek(archivo_swap, offset_pag, SEEK_SET);
  fread(&contenido_leido, tam_pagina, 1, archivo_swap);

  pag_buscada->contenido = contenido_leido;

  return pag_buscada;
}
```

Nos tira error en el fread, pero no estariamos pudiendo encontrar el motivo por el cual esta fallando

**Comment by RaniAgus** [comment]
¡Buenas! ¿Están seguros que `fread()` "les tira error"? No veo chequeo de errores en ese fragmento de código. Prueben, como dice la [documentación](https://man7.org/linux/man-pages/man3/fread.3.html), de chequear el valor de retorno a ver si realmente les devuelve que se leyeron menos bytes de los esperados:

```c
size_t bytes = fread(&contenido_leido, 1, tam_pagina, archivo_swap);
if (bytes < tam_pagina) {
    printf("error al leer swap: %d/%d bytes leídos\n", bytes, tam_pagina);
    exit(-1);
}
```
> Aclaro que cambié el orden del 2do y 3er parámetro para que devuelva la cantidad de bytes escritos.

También les sugiero hacer lo mismo cuando escriban el archivo de swap.

PD: Un dato de color - en markdown podés darle formato a un bloque de código (de más de una línea) usando tres comillas invertidas arriba y abajo (si le agregás una "c"  lo interpreta como código C y lo colorea), así:

<img src="https://user-images.githubusercontent.com/39303639/125994157-e624b220-1b6c-46a7-a64b-dac602249a37.png" height="75">

```c
printf("¡Hola mundo!\n");
```

**Comment by RaniAgus** [comment]
Me di cuenta de algo: están intentando leer una página completa (`tam_pagina`) y guardar ese dato en un `uint32_t`, por lo que eso podría provocar un `segmentation fault`.

Si es así, porfa, la próxima avisen cuál es el error que les aparece. Nos es mucho más difícil desde nuestro lado poder ayudarlos si la única información que tenemos es "me tira error". 😞 

Saludos

**Comment by FelipeAlborch** [comment]
Perfecto, Agus. Ahí me encargo de resolver eso, cualquier cosa aviso por acá. Gracias por la respuesta!
