### ISSUE TITLE
error al conectar cliente con servidor

### ISSUE THREAD

**Issue by Gabi314** [sisoputnfrba/foro#2881]
Holaa. Tenemos un problema con la funcion crear_conexion() en los módulos de cpu y kernel.  Cuando cpu intenta conectarse a memoria se devuelve el mensaje de error` "Error al conectar al servidor" `  . Lo cual nos hace pensar que el problema puede estar en accept() aunque no sabemos por qué. Cuando ejecutamos en Eclipse ocurre algunas veces pero cuando lo hacemos en las vm servers pasa siempre. A veces cuando cpu logra conectarse bien con memoria, surge el mismo problema en kernel al conectarse con cpu. 

```
int crear_conexion(char *ip, char* puerto)
{
	struct addrinfo hints;
	struct addrinfo *server_info;

	memset(&hints, 0, sizeof(hints));
	hints.ai_family = AF_UNSPEC;
	hints.ai_socktype = SOCK_STREAM;
	hints.ai_flags = AI_PASSIVE;

	getaddrinfo(ip, puerto, &hints, &server_info);

	// Crear el socket
	int socket_cliente = socket(server_info->ai_family,
								server_info->ai_socktype,
								server_info->ai_protocol);

	// Fallo al crear el socket
//	if (socket_cliente == -1) {
//		// Pasar logger correspondiente por parametro
//		//log_error(logger, "Hubo un error al crear el socket del servidor");
//		return 0;
//	}

	// Conectar el socket...
	// Error al conectar
	if(connect(socket_cliente, server_info->ai_addr, server_info->ai_addrlen) == -1) {
		log_error(logger, "Error al conectar al servidor");
		freeaddrinfo(server_info);
		return -1;
	}

	freeaddrinfo(server_info);

	return socket_cliente;
}

```

MAIN DE CPU

```
int main(int argc, char *argv[]) {

	logger = log_create("cpu-auxiliar.log", "CPU-AUX", 1, LOG_LEVEL_INFO);
....
.....
....
	handshakeMemoria();

	server_dispatch = iniciar_servidor(IP_CPU, puertoDeEscuchaDispatch, "Kernel");
	log_info(logger,"Servidor CPU-DISPATCH:[%d] iniciado", server_dispatch);

	server_interrupt = iniciar_servidor(IP_CPU, puertoDeEscuchaInterrupt,"Kernel");
	log_info(logger,"Servidor CPU-INTERRUPT:[%d] iniciado", server_interrupt);
......

}
```

```
void handshakeMemoria(){
	pthread_mutex_t mutexPrimerHandshake;
	pthread_mutex_init(&mutexPrimerHandshake,NULL);

	pthread_mutex_t mutexPrimerHandshake2;
	// Creamos una conexión hacia el servidor


//	pthread_mutex_lock(&mutexPrimerHandshake);
//	log_info(logger,"entra al mutex");
    socket_memoria = crear_conexion(ipMemoria, puertoMemoria);
//	pthread_mutex_unlock(&mutexPrimerHandshake);
	log_info(logger,"Hola memoria, soy cpu");

......
}
```

MAIN DE MEMORIA

```
int main(int argc, char *argv[]) {
.......
	memoria_fd = iniciar_servidor(IP_MEMORIA, puertoMemoria, "MEMORIA");
	while(1){
		// Escucho a cliente CPU
		server_escuchar(loggerAux, "MEMORIA", "CPU", memoria_fd);
		// Escucho a cliente Kernel
		server_escuchar(loggerAux, "MEMORIA", "KERNEL", memoria_fd);
	}

}
```

```
int server_escuchar(t_log* logger, char* server_nombre, char* cliente_nombre, int server_socket) {
	static pthread_mutex_t mutexPrimerHandshake;
	// Se conecta un cliente
	log_info(logger, "Esperando a un cliente (Kernel o CPU)");
	pthread_mutex_lock(&mutexPrimerHandshake);
    int cliente_socket = esperar_cliente(server_socket, cliente_nombre);
    pthread_mutex_unlock(&mutexPrimerHandshake);
.......
.......
.......

}
```
```

int esperar_cliente(int socket_servidor, char* cliente) {
	struct sockaddr_in dir_cliente;

	socklen_t tam_direccion = sizeof(struct sockaddr_in);

	// Aceptamos un nuevo cliente
	int socket_cliente = accept(socket_servidor,(void*) &dir_cliente, &tam_direccion);

	log_info(logger, "Se conecto el %s", cliente);

	return socket_cliente;
}
```

Ya intentamos sacar el while de memoria y reemplazarlo por un semaforo. También usamos mutex en el handshake de cpu con memoria pero los resultados son los mismos. 
Mil disculpas por preguntar sobre la hora y desde ya gracias.

**Comment by iago64** [comment]
Buenas! Cómo va?

Un error de ese estilo puede deberse a 2 posibles problemas:
1.- Tienen mal creado el socket que hace el `listen()` (Veo el llamado a la función `iniciar_servidor()` pero no veo como esta armada la función)
2.- Al momento de hacer el connect estan pifiandole al puerto que tienen configurado y bueno, quieren conectarse a un socket que no existe.

Para saber bien que onda el problema del lado del cliente en lugar de solo tener el `printf()` con _Error al conectar al servidor_ lo que pueden hacer es agregar un llamado a la función [`perror()`](https://www.tutorialspoint.com/c_standard_library/c_function_perror.htm) para que les imprima algo mas de info a ver si pueden encontrar el problema.

Por otro lado el tema del socket del servidor, solo para descartar, revisen que no tienen los valores de IP y Puerto y que por eso estan apuntando a un puerto inexistente.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Para sumar a lo que comentó Dami:

3- En ese `iniciar_servidor(IP_CPU, puertoDeEscuchaDispatch, "Kernel")` están pasando un `IP_CPU`, que:

  a) al estar en mayúsculas entiendo que podría ser un valor hardcodeado ("localhost" o "127.0.0.1"); y
  b) no es necesario pasar una IP para crear un servidor. Si le pasan `NULL` al primer parámetro de `getaddrinfo()` junto con el flag `AI_PASSIVE` como aparece en la [guía de sockets](https://docs.utnso.com.ar/guias/linux/sockets.html#bind-y-listen) ya deberían poder iniciar un servidor.  

4- Si todas las alternativas anteriores no funcionaron, les recomiendo chusmear este issue: https://github.com/sisoputnfrba/foro/issues/2000#issuecomment-739450264

Saludos

**Comment by Gabi314** [comment]
```
int iniciar_servidor(char* ip, char* puerto, char* cliente)
{
	int socket_servidor;

	struct addrinfo hints, *server_info;

	memset(&hints, 0, sizeof(hints));
	hints.ai_family = AF_UNSPEC;
	hints.ai_socktype = SOCK_STREAM;
	hints.ai_flags = AI_PASSIVE;

	getaddrinfo(ip, puerto, &hints, &server_info);

	// Creamos el socket de escucha del servidor
	socket_servidor = socket(server_info->ai_family, server_info->ai_socktype, server_info->ai_protocol);

	// Asociamos el socket a un puerto
	bind(socket_servidor, server_info->ai_addr, server_info->ai_addrlen);

	// Escuchamos las conexiones entrantes
	listen(socket_servidor, SOMAXCONN);

	freeaddrinfo(server_info);

	log_trace(logger, "Listo para escuchar a %s", cliente);

	return socket_servidor;
}
```

ese es nuestro` iniciar_servidor()`. Recién intentamos reemplazando SOMAXCONN por una variable dependiendo la cantidad de clientes que necesite cada modulo ( Usamos somaxconn para kernel, 1 para cada puerto de cpu y 2 para memoria) pero aparecian los mismos errores.

 `perror()` devuelve `Connection refused`

**Comment by RaniAgus** [comment]
¡Buenas! Para sumar a lo que comentó Dami:

3- En ese `iniciar_servidor(IP_CPU, puertoDeEscuchaDispatch, "Kernel")` están pasando un `IP_CPU`, que:

  a) al estar en mayúsculas entiendo que podría ser un valor hardcodeado ("localhost" o "127.0.0.1"); y
  b) no es necesario pasar una IP para crear un servidor. Si le pasan `NULL` al primer parámetro de `getaddrinfo()` junto con el flag `AI_PASSIVE` como aparece en la [guía de sockets](https://docs.utnso.com.ar/guias/linux/sockets.html#bind-y-listen) ya deberían poder iniciar un servidor.  

4- Si todas las alternativas anteriores no funcionaron, les recomiendo chusmear este issue: https://github.com/sisoputnfrba/foro/issues/2000#issuecomment-739450264

Saludos

**Comment by Gabi314** [comment]
Buenas. Nos fijamos el issue #2000  y adaptamos nuestro código a la alternativa que se muestra pero de todos modos seguimos con el mismo error. Cabe aclarar también que lo que nos pasa en eclipse siempre es que la primera vez que intentamos ejecutar se conectan bien pero a partir del segundo intento empieza a fallar, sobre todo con cpu para conectarse a memoria.

**Comment by RaniAgus** [comment]
Veo que del lado del servidor no están manejando errores al llamar a `socket()`, `bind()` y `listen()`...

¿Podrían verificar que le esté devolviendo un valor `!= -1` y, de ser así, imprimir el error con `perror()` como sugirió Dami más arriba?

También les recomiendo hacer lo mismo con `getaddrinfo()`, solo que en este caso [la documentación](https://man7.org/linux/man-pages/man3/getaddrinfo.3.html#RETURN_VALUE) aclara que devuelve un código de error `!= 0` y que pueden convertirlo a string usando `gai_strerror()`, por ejemplo, así:

```c
int result = getaddrinfo(...);
if (result != 0) {
    printf("Error en getaddrinfo: %s\n", gai_strerror(result));
    exit(-1);
}
```

**Comment by Gabi314** [comment]
cambiamos nuestro iniciar_servidor
```
int iniciar_servidor(char* ip, char* puerto, char* cliente)
{
	int socket_servidor;

	struct addrinfo hints, *server_info;

	memset(&hints, 0, sizeof(hints));
	hints.ai_family = AF_UNSPEC;
	hints.ai_socktype = SOCK_STREAM;
	hints.ai_flags = AI_PASSIVE;

	int resultadoGetAdd = getaddrinfo(NULL, puerto, &hints, &server_info);
	if(resultadoGetAdd != 0){
		log_info(logger,"Restulado get add incorrecto: %s",gai_strerror(resultadoGetAdd));
		}
	// Creamos el socket de escucha del servidor
	socket_servidor = socket(server_info->ai_family, server_info->ai_socktype, server_info->ai_protocol);

	// Asociamos el socket a un puerto
	int resultadoBin = bind(socket_servidor, server_info->ai_addr, server_info->ai_addrlen);
	if(resultadoBin == -1){
		perror("Resultado bin incorrecto");
	}
	// Escuchamos las conexiones entrantes
	int resultadoListen = listen(socket_servidor, SOMAXCONN);
	if(resultadoListen == -1){
			perror("Resultado listen incorrecto");
		}
	//freeaddrinfo(server_info);

	log_trace(logger, "Listo para escuchar a %s", cliente);

	return socket_servidor;
}
```

apenas ejecutamos memoria el perror de bind nos devuelve `Adress already in use` . Estamos viendo cuál puede ser la causa.

**Comment by RaniAgus** [comment]
¡No busque más! Ese y otros errores comunes se encuentran explicados en la [guía de despliegue de TP](https://docs.utnso.com.ar/guias/herramientas/deploy.html) 😉

**Comment by Gabi314** [comment]
@iago64 @RaniAgus muchas gracias de verdad! Los quiero mucho ❤️
