### ISSUE TITLE
Se le asigna la misma IP a distintas maquinas virtuales 

### ISSUE THREAD

**Issue by MMoyanoFontana** [sisoputnfrba/foro#2882]
Buenas, quería probar algo del deploy en mi computadora y segui las instrucciones que estan en la [guía de despliegue](https://docs.utnso.com.ar/guias/herramientas/deploy.html#como-practicar-el-despliegue-en-local) pero cuando ejecuto ifconfig en la maquina "original" y la clonada me sale que la ip de ambas es la misma (192.168.0.40)

Me asegure de que esta seleccionado el "Bridged Adapter" en la parte de conexión y también intente usar la opcion de "Complete clone" pero no cambió nada

**Comment by RaniAgus** [comment]
¡Buenas! En el labo nos hemos encontrado con el mismo problema y armamos una solución que pueden probar siguiendo estos pasos:

1- Con la VM apagada, cambiar el adaptador de red de vuelta a "NAT"
2- Prender la VM y ejecutar:

```
curl -fsSL https://faq.utnso.com.ar/fluship.sh | sh
```
Tiene que aparecer un mensajito indicando que se ha creado un symlink en una ruta.

3- Apagar la VM y cambiar el adaptador de nuevo a "Bridged Adapter"

Lo que hace eso es instalar un script que asigna una nueva IP cada vez que prendas la VM. No viene incluido en las VMs ya que no es ideal que la IP esté cambiando constantemente, pero para el caso de las pruebas nos ha sido útil.

Saludos

**Comment by MMoyanoFontana** [comment]
Pude ejecutar el comando y me salio este mensaje de symlink 
![image](https://user-images.githubusercontent.com/81981926/208207946-5baa744b-d8b7-43c5-b13d-c9f70a8ccad8.png)
Asi que supongo que eso esta bien, pero cuando apago la vm y vuelvo al Bridged Adapter sigue tirando la misma ip de antes (192.168.0.40) :(

No se si tenga otra solucion pero gracias igualmente :)

**Comment by RaniAgus** [comment]
Solo para estar seguro: ¿lo ejecutaste en ambas VMs y luego en ambas te aparece la misma IP? Quizás en una se haya asignado la `192.168.0.40` pero en la otra no.

**Comment by MMoyanoFontana** [comment]
Sisi, lo probe pero las dos seguían marcando lo mismo. Igualmente lo que hice al final, aunque sea para probar, fue ejecutar una VM del servidor sin la interfaz y otra VM normal en la que fuimos haciendo el tp, que a esta si le asigna una ip diferente. Ahí fui probando ir abriendo algunas consolas en cada VM y variar en que VM abro cada modulo y no habia problema asi que creo que lo puedo dar como cerrado. Gracias :)

**Comment by parodi1998** [comment]
Buenas noches.

A mi me ocurre lo mismo, y correr ese script tampoco lo soluciono.  :(
