### ISSUE TITLE
Duda comunicacion kernel con memoria durante PF

### ISSUE THREAD

**Issue by MMoyanoFontana** [sisoputnfrba/foro#2883]
Buenas perdón por la hora pero mientras estabamos cerrando todo para mañana nos surgió una duda de como funciona ahora nuestra manera de resolver el page fault y en general la conexion con memoria. Siguiendo lo que dice en la repuesta del issue #2863 lo que tenemos ahora es un semaforo para la conexión de memoria y cuando ocurre un page fault hacemos algo de este estilo: 
```
pthread_mx_lock(&mx_memoria); 
Send(); //todo lo necesario para el PF
Recv(); // confirmacion de que se cargo
pthread_mx_lock(&mx_memoria);
```
Con esto funciona de acuerdo a las pruebas y no hay problemas de condiciones de carrera pero bloquea toda la conexión con memoria del kernel hasta que se cargue la pagina (que tiene sentido porque no va a liberar el semaforo hasta recibir el mensaje). O sea que no se pueden mandar otros mensajes a memoria desde kernel, por ejemplo los de crear o liberar las estructuras de un proceso que es nuevo o que finalizó. No sabemos si esto es correcto o si hay alguna manera de seguir enviando mensajes mientras se resuelve el PF 

Tambien una duda más simple era que queriamos saber si a la hora de crear un proceso nuevo y asignarle el espacio en SWAP a sus paginas esto lo debemos tomar como acceso a swap y aplicar el retardo que especifica el archivo de config.

Gracias y de nuevo perdon por la hora.

**Comment by RaniAgus** [comment]
¡Buenas! Seré breve:

1. Es correcto que realicen una solicitud a la vez, ya que se realiza utilizando un único socket.

2. No deben aplicar el retardo (cito el enunciado, sección "Acceso a espacio de usuario" de Memoria):

> Para simular la diferencia de velocidades entre los accesos a TLB y Memoria, cada acceso a tablas o a espacio de usuario tendrá un tiempo de espera en milisegundos definido por archivo de configuración. Este tiempo **no** debe ser tenido en cuenta para las operaciones con Kernel (Creación, Finalización de proceso o Page Fault).

Saludos

**Comment by MMoyanoFontana** [comment]
1 Perfecto entonces.
2. Si es verdad justo repasamos el enunciado y vimos la parte que dice que no aplica, nos habiamos olvidado 

Muchas Gracias, cierro el issue :)
