### ISSUE TITLE
👩‍💻 ¿Buscás Grupo / Integrantes para el 1c2023? ¡Posteá ACA! 👨‍💻

### ISSUE THREAD

**Issue by RaniAgus** [sisoputnfrba/foro#2884]
¡Buenas!

Con el objetivo de unificar todos los post de búsqueda de grupos / integrantes, vamos a centralizarlo en este post.

Les recomendamos encarecidamente que traten de **NO publicar números de celular** y limitarse solo a los mails. Tengan en cuenta que el foro es público, por lo que pueden llegar a quedar en alguna lista de spam o que les hable gente que no quieran.

Saludos.-

**Comment by atononi** [comment]
Buenas, como va? Busco grupo, estoy totalmente solo. Me gustaría gente que ya sepa manejar git y que sea organizada.
Dejo mi mail: augustd@frba.utn.edu.ar

**Comment by sergidalessio** [comment]
Hola, estamos buscando para nuestro grupo gente (preferentemente recursante) que haya participado en desarrollos de tps de años anteriores y tenga una idea básica de Git y resto de herramientas. 
Somos tres por ahora y  todos del curso K3053. Cualquier cosa me escriben a dalessio@frba.utn.edu.ar 
Slds

**Comment by NKennedy31** [comment]
Buenas!! Estamos buscando dos integrantes para nuestro grupo. Somos tres recursantes y nos gustaria gente que esté dispuesta a  dedicarle tiempo al tp y aprobarlo. Dejo mi mail: ikennedy@frba.utn.edu.ar

**Comment by esigma5** [comment]
Hola! Estoy buscando grupo. La cursé por primera vez en el 2005. Conozco algo de la materia.

**Comment by JCNeira14** [comment]
Buenaas, estamos buscando 3 integrantes para el grupo. Buscamos gente con buena onda, predisposicion y sobre todo ganas de dedicarle tiempo a la materia para llevar bien el TP. Somos del curso K3053 y mi mail es jneira@frba.utn.edu.ar

**Comment by LucasThier** [comment]
Buenas, Busco grupo para el TP. Es la primera vez que curso la materia y se lo básico de Git.
Dejo mi mail: lthier@frba.utn.edu.ar

**Comment by melinaloza** [comment]
Buenass, busco grupo para sumarme o para armarlo. Soy del curso K3053.
Mi mail es mlozaflores@frba.utn.edu.ar

**Comment by joaco-bruno** [comment]
Buenas, estoy buscando 2 personas que quieran sumarse al grupo. Buscamos que tengan ganas de aprobar SO, dedicarle tiempo a la materia y mucha predisposición para trabajar. Dejo mi mail para adjuntar CV :smile: :smile:.  Soy del curso de los martes a la noche
joabruno@frba.utn.edu.ar

**Comment by Munetakachan** [comment]
Buen día, estoy buscando grupo para el tp. Estoy en el curso de los sábados a la tarde K3055. Trabajo durante el día, pero estoy para meterle al tp durante la semana a la noche :)
dyamada@frba.utn.edu.ar

**Comment by kamipalomino** [comment]
Buenas busco un grupo que tenga totalmente como `PRIORIDAD` aprobar la materia, `recursantes` y que con tiempo para dedicarle varias horas a la semana al tp. (En lo posible de noche)
Soy del curso martes noche les dejo mí email cpalomino@frba.utn.edu.ar.
Saludos!

**Comment by gabdigiorgio** [comment]
Buenas, buscamos 3 personas para que se sumen al grupo, somos 2. Soy del curso de martes a la noche.
gdigiorgio@frba.utn.edu.ar

**Comment by fedealvarenga** [comment]
Buenas soy del curso k3154(miércoles a la noche) busco grupo preferentemente del mismo curso. Mi mail es falvarenga@frba.utn.edu.ar

**Comment by brunoEjaime** [comment]
> Buenas, buscamos 3 personas para que se sumen al grupo, somos 2. Soy del curso de martes a la noche. [gdigiorgio@frba.utn.edu.ar](mailto:gdigiorgio@frba.utn.edu.ar)

Buenas! Siguen buscando? Somos 3 nosotros

**Comment by Hamamura-S** [comment]
Buenas, estoy solo y soy del K3153 (martes noche). No manejo bien git todavía pero estoy cursando paradigmas asi que ya va a ir queriendo😁. Dejo mi mail por si a alguien le entra uno más. hamamurasantiago@frba.utn.edu.ar

**Comment by jfr4nc0** [comment]
Gente como están?
 Estamos buscando 3 personas para armar el grupo, somos dos que trabajamos en sistemas para el área de desarrollo y nos llevamos bien con Linux. 
 Si tenés buena predisposición y experiencia programando escribimos!

Contacto: jfcpersonal99@gmail.com

**Comment by mijHwang** [comment]
Hola, estoy buscando un grupo para unirme. Estoy cursando el miércoles/viernes mañana, es la primera vez que lo curso y no tengo muchas experiencias, pero aprobar SO es mi prioridad número uno este año y estoy dispuesto 100% a poner el tiempo y el esfuerzo necesario.

mhwang@frba.utn.edu.ar

**Comment by LeoMorsella** [comment]
Hola, estoy buscando grupo para unirme, me encuentro solo. Estoy cursando los sábados por la tarde.
Este año es mi prioridad cursar y aprobar SO, la curse en el 2020 previamente.
Actualmente trabajo en el área de desarrollo, y es mi prioridad principal este cuatrimestre poder aprobar la materia.
Dejo mi mail leomorsella@frba.utn.edu.ar

**Comment by gabrirodriguez** [comment]
Hola. Estoy buscando grupo. Curso los martes a la noche. Trabajo en sistemas (devops) y trabajo en linux. 
Hay algún grupo que tenga buena predisposición y que le falte algún integrante?

gabrirodriguez@frba.utn.edu.ar

**Comment by D-M-Gonzalez** [comment]
Hola que tal.

Busco grupo, preferiblemente que curse los sábados por la mañana. Soy desarrollador actualmente trabajando en un ERP, y conozco algunas cosas de operativos, linux y demas. Busco algún grupo con buena predisposición, que intente promocionar la materia.

dami.m.gonza@gmail.com

**Comment by Brai93** [comment]
Buenas,

Busco gente que cumpla las siguientes condiciones:
1. Ya haya cursado la materia y tenga base fuerte de la teoria
2. Tenga experiencia en desarollo (o haya realizado el tp de forma avanzada)
3. Ganas de aprobar la materia y no darle vueltas
4. Buena predisposicion para trabajar en equipo

Si cumplen esto o creen que entienden el desafio, mandenme mail o privado: brian.fk@hotmail.com o brianfink@frba.utn.edu.ar
Mi idea es tener un equipo fuerte que quiera liquidar pronto el tp para enfocarse luego a los parciales/finales

Por mi parte, les comento. Curse la materia con anterioridad 3 veces (aprobe 2 veces la teoria, 1 tp/coloquio), trabajo hace años en Sistemas, soy muy organizado y me gusta resolver las cosas de forma simple y rapida.

Saludos!

**Comment by BenjaminAlegre** [comment]
Hola buenas, busco grupo, soy del curso de martes a la noche K3153. 
Dejo mi contacto: balegrerocha@frba.utn.edu.ar

**Comment by goonzaah** [comment]
Hola. Estoy buscando grupo. Curso los lunes a la noche K3051. Trabajo como desarrollador hace mas de 4 años.
Este cuatrimiestre tengo como prioridad esta matería, la curse en el 2020.

ghernandez@frba.utn.edu.ar

**Comment by tolaDiego** [comment]
Hola, busco grupo para hacer el TP. Estoy cursando los sabados por la mañana, dejo mi email:
diegotola1999@gmail.com

**Comment by tobiasvialeruiz** [comment]
Hola. Somos un grupo de cuatro que nos falta una persona. Buscamos a alguien que vaya a priorizar la materia y que busque la promoción.

Para el que le interese mándame un mail a: tvialeruiz@frba.utn.edu.ar

**Comment by fdavinsonegoavil** [comment]
Buenas, busco grupo para hacer el TP. Estoy cursando los lunes TN, dejo mi email:
fdavinsonegoavil@@frba.utn.edu.ar

**Comment by vrojas2022** [comment]
Hola, curso Miercoles Noche, busco gente que quiera sumarse para el grupo, ideal que seamos todo de Miércoles noche, así nos vemos siempre en la cursada. Soy recursante. 
Dejo mi mail vrojas@frba.utn.edu.ar.

**Comment by alejosandrini** [comment]
Buenas, estamos buscando un integrante más para nuestro grupo. Principalmente buscamos que haya cursado las materias de segundo año (pdp y sintaxis), que esté comprometido con la cursada y no dejé la materia a medio camino. Nuestro grupo va a priorizar esta materia y la aprobación del tp. Cualquier cosa me mandan un mail a asandrini@frba.utn.edu.ar

**Comment by MiltonMartorello** [comment]
Gúenas! Busco gente responsable y comprometida con la materia que preferentemente curse los Miércoles a la noche para formar grupo. Personalmente solo curso esta materia este cuatri porque la quiero meter. Ya tengo el TP0 hecho.
mmartorello@frba.utn.edu.ar

**Comment by RecaldeMartina** [comment]
Buenas! estamos buscando 2 personas que se comprometa con el tp y a trabajar en equipo.
Nosotros estamos cursando los miércoles a la noche y tenemos muchas ganas de meter la materia este cuatrimestre. Si a alguno le interesa sumarse dejo mi mail mrecalde@frba.utn.edu.ar

**Comment by CarlosGVelasquez** [comment]
Hola, estoy buscando grupo, curso los martes a la noche, y ya tengo la VM instalada y arranque con el tp0 (envio mensajes bien, me falta el paquete por ahora). Tengo muchas ganas de sacar adelante la materia.
carlovelasquezmenchaca@frba.utn.edu.ar

**Comment by isma-morel** [comment]
Hola, estoy buscando grupo, curso sábados por la tarde. Tengo solidos conocimientos en git y bash. Busco un grupo que quiera realizar el TP de forma rápida y uniforme. 
Contacto: imorel@frba.utn.edu.ar

**Comment by gonhernandez** [comment]
> Hola. Estoy buscando grupo. Curso los lunes a la noche K3051. Trabajo como desarrollador hace mas de 4 años. Este cuatrimiestre tengo como prioridad esta matería, la curse en el 2020.
> 
> [ghernandez@frba.utn.edu.ar](mailto:ghernandez@frba.utn.edu.ar)

Sigo buscando, preferentemente turno lunes a la noche

**Comment by tralph3** [comment]
Sigo buscando. Curso sábados a la tarde. Tengo buena experiencia con Linux y git, sé programar, pero no estoy del todo acostumbrado a C. Manden CV:

tomasralph2000@gmail.com

**Comment by dhuallpa** [comment]
Hola buenas. Estoy buscando grupo. Curso los sábados a la mañana.  Tengo tiempo para dedicarle a la materia y experiencia en los módulos de File System/Memoria en anteriores TPs, no tengo problema con hacer otro modulo.
Contacto: vcontreras@frba.utn.edu.ar

**Comment by suhjorge** [comment]
Hola, Estoy buscando grupo. Curso los Miercoles y Viernes por la mañana. No tengo problema con horarios, tengo experiencia con Modulo File System.
Contacto: suhjorge@gmail.com

**Comment by maxi09** [comment]
Hola! Estoy buscando grupo. Curso los martes por la noche. Dejo mi correo de contacto: maxmarquez@frba.utn.edu.ar

**Comment by alexclaureM** [comment]
Buenos dias!, somos 2 personas por el momento, estamos buscando gente que quiera meter el tp y la materia. trabajando en equipo y donde podamos aprender todos. Cursamos los Lunes a la noche. Les dejo mi correo de contacto:
alexclauremontecinos@frba.utn.edu.ar

**Comment by ivansmalinsky** [comment]
Buenas, estoy buscando grupo, curso los sábados a la tarde. Mi idea es meterle a la materia hasta el final, no soy ningún crack pero hice algunas cosas en C. Dejo mi correo: ismalinsky@frba.utn.edu.ar

**Comment by Vvallejos984** [comment]
Buenass. Estoy buscando grupo, cursé la materia el cuatri pasado, aprobé los parciales pero no llegué con el TP porque se bajaron 3 de los 4 compañeros que tenía. Así que si alguien está armando algún grupo con ganas de centrarse en el TP, les dejo mi contacto: vvallejos@frba.utn.edu.ar

**Comment by sandreu95** [comment]
Buenas!! Estoy buscando grupo estoy solo por ahora. Llevo poquito usando Git y tengo que meterle a C, pero quiero meterle a la cursada y aprobar SO. Lo que si llevo siendo QA hace varios años por si sirve algo de planificación. Estoy en el curso de los sábados a la tarde (K3055). Mi mail es sandreu@frba.utn.edu.ar, no duden en escribirme si les queda un lugar

**Comment by alejandro-mattioli-frba** [comment]
Hola! Estoy buscando grupo, estoy completamente solo. Preferiría que sean alumnos del curso de los miercoles a la noche para vernos presencialmente. Es la unica materia que estoy cursando con lo cual tengo disponibilidad para hacer el TP todos los días. 
Dejo mi mail : amattioli@frba.utn.edu.ar

**Comment by jonaespinoza** [comment]
Hola, estoy buscando grupo. Tengo intenciones de aprobar el tp y meterle a full, estoy en la clase de los martes a la noche K3053. Cursé la materia el primer cuatri del año pasado y logramos avanzar un poco mas de la mitad con el tp pero se nos bajaron 2 integrantes del grupo y se nos complicó terminarlo, algunas cosas como para encararlo de arranque tengo. Mi mail: jonaespinoza@frba.utn.edu.ar

**Comment by FrancoQuiroga01** [comment]
Hola, nos falta 1 para completar el grupo de 5. Somos del curso de miercoles a la noche.

dejo mi mail: fquiroga@frba.utn.edu.ar

**Comment by aguustingc** [comment]
Buenas, ando en búsqueda de grupo. Curso los martes a la noche K3053, laburo en sistemas hace más de dos años y tengo intenciones de meter la materia este cuatri. La cursé el cuatri pasado por ende una base tengo. Actualmente estoy cursando solo 3 dias asi que tengo disponibilidad!
Contacto: agonzalezcanosa@frba.utn.edu.ar

**Comment by Vvallejos984** [comment]
Buenass. Estamos buscando 2 integrantes más para el grupo. Somos los tres recursantes y del curso del martes a la noche. Buscamos de preferencia gente con intención de aprobar el TP y algo de conocimiento de programación para poder cerrar el TP lo antes posible y evitarnos desaprobarlo por falta de tiempo.

Les dejo mi contacto, cualquier cosa hablenme: vvallejos@frba.utn.edu.ar

**Comment by JuanFreH** [comment]
Buenas, busco grupo estoy solo. Soy del curso de los miercoles a la noche. Busco gente que se comprometa con el tp para poder sacarlo lo mas pronto posible.
Dejo mi mail : [jfreyre@frba.utn.edu.ar](mailto:jfreyre@frba.utn.edu.ar)

**Comment by TiagoLob** [comment]
Buenos días! Estoy buscando grupo o gente para conformar uno; por ahora estoy solo. En estos momentos solo estoy cursando dos materias, por lo que mi idea seria meterle a Sistemas Operativos y tratar de firmarla en esta cursada (o promocionarla, siempre hay que ser optimista).

Estoy cursando la materia los miércoles a la noche, estaría bueno que sean del mismo curso así tenemos una mejor comunicación.

Dejo mi mail para contactarme: tlobretto@frba.utn.edu.ar

Saludos y felices pascuas!

**Comment by gdrusetich** [comment]
Somos un grupo de 3.
Buscamos dos integrantes, preferentemente recursante, y con amplia disponibilidad horaria.
gdrusetich@frba.utn.edu.ar

**Comment by NicoleChavez** [comment]
Buenas! nos falta un integrante para nuestro grupo. Somos todos recursantes (algunos más de una vez y tienen experiencia con el tp, llegaron hasta 80%-90% terminado), en lo posible buscamos a alguien que también la este recursando y con disponibilidad para meterle al tp ya que todos cursamos pocas materias. 
Dejo mi mail: nchavezalvarez@frba.utn.edu.ar

**Comment by crema2** [comment]
Buen dia, estamos a la busqueda de 2 personas para que formen parten del grupo. 
Estamos en gral metidos en 2 o 3 materias cada uno. Laburamos y nuestros horarios de estudio son a la noche, queremos sacar la materia adelante. Contamos con un recursante con un conocimiento solido en los temas a tomar.
De momento nosotros cursamos los lunes a la noche.
Que buscamos? Que tenga conocimiento o no, se plante de cara con el TP y no tenga miedo de consultar asi nos vamos dando una mano entre todos. Que este presente, conozca la veracidad del Trabajo, se acomode en horarios pactados y asuma la carga correspondiente. 
Dejo mi correo a disposicion: msantanacantero@frba.utn.edu.ar

**Comment by Ariel-Hab** [comment]
Hola somos un grupo de 4 y estamos buscando un integrante para nuestro grupo. Somos del curso del sabado a la mañana. Lo ideal seria alguien con disponibilidad, con ganas de meterle.
dejo aca mi mail: ahabib@frba.utn.edu.ar

**Comment by ndelorte** [comment]
Buenas, estoy en busqueda de grupo. Es la primera vez que curso la materia pero tengo bastante disponibilidad horaria y mi objetivo principal este cuatrimestre es SO, asi que le voy a dedicar mi tiempo al TP, si a alguno le falta gente en el grupo o esta solo y quiere empezar a armar un grupo de 0 puede contactarme, mi mail es delorte85@gmail.com

**Comment by Alejood** [comment]
Buenas, estoy buscando grupo o gente para hacer uno. Estoy cursando SO y otra materia mas, mi objetivo es aprobarla este cuatri. Estoy cursando la materia los miercoles a la noche.

Mi mail: aledilluvio@frba.utn.edu.ar

**Comment by everlizarraga** [comment]
Hola. Estoy buscando grupo para el TP. Curso SO los martes a la noche. Soy recursante.
Mi mail: everlizarraga@frba.utn.edu.ar

**Comment by TiagoLob** [comment]
Buenos días!! Estamos en la búsqueda de un integrante para nuestro grupo.

Somos chicos del curso de los martes y miércoles a la noche, y estamos decididos a meterle al TP en este cuatri.

Si estas interesado, te dejo mi mail para contactarme: tlobretto@frba.utn.edu.ar

Saludos!!

**Comment by fdavinsonegoavil** [comment]
Buenas. Sigo buscando grupo para el TP. Curso los lunes a la noche. Soy recursante
Mi mail: fdavinsonegoavil@frba.utn.edu.ar

**Comment by fueguino3** [comment]
Buenas! Buscamos un integrante para formar el grupo e inscribirnos inmediatamente.
Somos un grupo de 4 en la cátedra K3011 y necesitamos uno más.

**Comment by JuanFreH** [comment]
Buenas, somos 2 del turno noche. Buscamos gente con tiempo para dedicarle a full al tp
Mi mail: jfreyre@frba.utn.edu.ar

**Comment by fueguino3** [comment]
Hola, somos 4 ya. Nos faltaría 1

**Comment by ndelorte** [comment]
Buenas sigo buscando grupo, estoy solo. Soy del curso de sabado a la mañana, delorte85@gmail.com

**Comment by fueguino3** [comment]
> Te interesa unirte a nuestro grupo? Somos 4 en la catedra K3011

**Comment by martinfarrell11** [comment]
Buenas, estoy buscando grupo, soy del curso de miércoles a la mañana K3014. 
Dejo mi correo mfarrell11@frba.utn.edu.ar

**Comment by nramrezmoreale** [comment]
Buenas, busco grupo, soy del curso de los miércoles a la noche K3054.
Mi email es nramrezmoreale@frba.utn.edu.ar

**Comment by velazquezlautaro12303** [comment]
Buenas busco grupo estoy solo.. mí mail lavelazquez@frba.utn.edu.ar

**Comment by fueguino3** [comment]
> Buenas, estoy buscando grupo, soy del curso de miércoles a la mañana K3014. Dejo mi correo [mfarrell11@frba.utn.edu.ar](mailto:mfarrell11@frba.utn.edu.ar)

Te interesa unirte a nuestro grupo? Somos 4 en la catedra K3011

**Comment by fueguino3** [comment]
> Buenas busco grupo estoy solo.. mí mail [lavelazquez@frba.utn.edu.ar](mailto:lavelazquez@frba.utn.edu.ar)
Te interesa unirte a nuestro grupo? Somos 4 en la catedra K3011

**Comment by fueguino3** [comment]
> Buenas busco grupo estoy solo.. mí mail [lavelazquez@frba.utn.edu.ar](mailto:lavelazquez@frba.utn.edu.ar)

Te interesa unirte a nuestro grupo? Somos 4 en la catedra K3011

**Comment by fueguino3** [comment]
> Buenas. Sigo buscando grupo para el TP. Curso los lunes a la noche. Soy recursante Mi mail: [fdavinsonegoavil@frba.utn.edu.ar](mailto:fdavinsonegoavil@frba.utn.edu.ar)

Te interesa unirte a nuestro grupo? Somos 4 en la catedra K3011

**Comment by PiMedina** [comment]
buenas, estoy buscando grupo, soy del curso de los sábados a la mañana, mi mail pmedinaangulo@frba.utn.edu.ar

**Comment by noemi15** [comment]
Hola!!, soy Noemi ,  recursante de SO el tp lo avanzamos digamos un 60%  pero no seguimos porque no aprobamos los exámenes, actualmente curso los sábados , solo estoy cursando esta materia porque es la única materia que debo del tercer año y necesito aprobarla si o si , no soy programadora pero le meto mucha onda. 
Busco grupo, mi mail es  nmorenogomero@frba.utn.edu.ar

**Comment by karelysr** [comment]
Hola, estoy buscando grupo para unirme, soy del curso miercoles en la noche, mi mail es krangelsalcedo@frba.utn.edu.ar

**Comment by Matitisco** [comment]
Buenas, somos 4 y estamos buscando 1 integrante. Mi mail es: matiscornia@frba.utn.edu.ar

**Comment by Rojo2202** [comment]
Hola, estamos buscando **1 integrante**, somos 4, mi mail es: [acaldernrodriguez@frba.utn.edu.ar](url)
