### ISSUE TITLE
Error al abrir la MV

### ISSUE THREAD

**Issue by NicoMargheim** [sisoputnfrba/foro#2885]
Hola, tuve de problema que no me inicia la VM.
Descargué la Xubuntu de 64 bits para poder empezar a estudiar, y siguiendo el video de controlar hash ví que se instale bien.
![image](https://user-images.githubusercontent.com/129228788/229127203-3f8b0e8f-6eeb-43e5-a357-4fae3b15953e.png)
Me quedaron esos 3 archivos.
Para cuando tocó crear la MV en sí seguí la otra guía para asegurarme de no hacer ninguna pavada. Puse Linux de sistema y Ubuntu 64 bits como decía la página, luego seleccione 1024 para la ram y la imagen virtual que había descargado para la memoria de disco duro.
Sin embargo, cuando voy a iniciar la maquina me salta este error.
![image](https://user-images.githubusercontent.com/129228788/229127879-eb7d4dab-5fc9-454e-84d7-261e8c3a89e8.png)
Inmediatamente me fijé en la página lo que había que hacer, pero cuando intenté buscar lo de Hiper-V no me aparecía (incluso buscándolo de otra manera que googlee).
Como no funcionó, googlee el error que me saltaba "E_FAIL (0X80004005)" pero eso no llegó a nada.
¿Alguien me podría ayudar?

### 📦 Especificaciones de la VM
- Versión de VirtualBox: La que me mandó desde Utnso (con el extension pack)
![image](https://user-images.githubusercontent.com/129228788/229128832-a9ea5072-4863-475c-8623-2801242b8b99.png)

- Memoria RAM asignada: 1024 (en un intento posterior 2048 con mismos resultados)

### 🖥️ Especificaciones del host
- Sistema Operativo y versión: Windows 10 home (64 bits) 21H2

- Memoria RAM: Tengo una DDR4 de 8 Gb, 3000 MHz

- Procesador: Ryzen 5 3400G

**Comment by juanibencardino** [comment]
![image](https://user-images.githubusercontent.com/83251119/229163158-f86adff8-d8d0-4bac-8b32-100f3a5d4a9c.png)

Fijate yo la cree asi, en version me autocompleto conXubuntu de 64bits, no Ubuntu

**Comment by RaniAgus** [comment]
¡Buenas!

@NicoMargheim Como comentamos en la [sección de consultas de docs](https://docs.utnso.com.ar/consultas), está bueno primero revisar el buscador de issues del foro ya que es muy probable que cualquier problema de VirtualBox ya le haya ocurrido a otro alumno antes y ya se encuentre la respuesta ahí sin tener que esperar la respuesta de un compañero o ayudante.

En tu caso, el código de error es `VERR_SVM_DISABLED`, para lo cual mi respuesta va a ser la misma que la de Mati en https://github.com/sisoputnfrba/foro/issues/2551#issuecomment-1095841969

También te recomiendo copiar todo el texto de error en vez de una captura, ya que sino alguien más no podría usar el buscador para encontrar este issue si escribe, por ejemplo, `VERR_NEM_NOT_AVAILABLE` o `AMD-V is disabled in the BIOS (or by the host OS)`.

@juanibencardino ¡gracias por sumarte para ayudar! Igual te recomiendo seguir los pasos de la [guía para conseguir entorno Linux](https://docs.utnso.com.ar/primeros-pasos/entorno-linux), ya que ahí se explica, entre otras cosas, que la versión es Ubuntu 64-bit 😅. 

Sin embargo creo que Xubuntu también debería andar bien (ya que es una distribución basada en Ubuntu), si te funcionó no creo que haga falta cambiarlo.

Saludos a ambos

**Comment by NicoMargheim** [comment]
Muchas gracias por la ayuda!

**Comment by RaniAgus** [comment]
¡No hay de qué! Una vez configures la BIOS, si eso resuelve tu problema podés cerrar el issue 👍🏻
