### ISSUE TITLE
VM no inicia ayuda

### ISSUE THREAD

**Issue by MaximoBoglioli** [sisoputnfrba/foro#2887]
Hola, estuve siguiendo los pasos de la guía para tener una máquina virtual y cuando llegué a la parte de darle start no funcionó. Se queda pensando y no aparece ninguna opción.
Tras reiniciarlo (Apagándolo), me da la opción de elegir como iniciarlo. Pero tras elegirlo se queda la pantalla en negro con el cursor titilando arriba a la derecha.

### 🔎 Búsqueda en foros
En los foros solo encontré uno pero parecía ser de otro tema.
En google encontré esta página sobre personas con el mismo problema, pero en versiones anteriores de Virtual Box: https://bbs.archlinux.org/viewtopic.php?id=258217
había varios que decían que cambiando el USB a 1.0 se les resolvía. Probe cambiándolo al 1.0, al 2.0, deshabilitándolo y en ningún caso funcionó.
También hablaban de no utilizar la extensión, pero como en el foro dicen que es útil tenerla no probé sacarla.

### 📦 Especificaciones de la VM
- Versión de VirtualBox: 7.0
- Memoria RAM asignada: 2048 MB
- Ubuntu de 32 bit

### 🖥️ Especificaciones del host
- Sistema Operativo y versión: Windows 10
- Memoria RAM: 16 GB
- Procesador: Rysen 5 2600
- Verifique el tema de Hyper-V. Lo tenía deshabilitado. Probe habilitarlo y deshabilitarlo de nuevo y en ningun momento funcionó
- También verifique los hash de cada uno de los 3 archivos

### 💻 Logs
En el archivo de logs "VBOX.log" me aparece el siguiente error 2 veces.
00:00:07.328808 ERROR [COM]: aRC=VBOX_E_VM_ERROR (0x80bb0003) aIID={4680b2de-8690-11e9-b83d-5719e53cf1de} aComponent={DisplayWrap} aText={Could not take a screenshot (VERR_NOT_SUPPORTED)}, preserve=false aResultDetail=-37

**Comment by LeandroCarbajales** [comment]
Buenas!
En cuanto podamos lo vemos más en detalle, pero para corroborar antes que nada veo esto `Ubuntu de 32 bit`, para las nuevas VMs hay que seleccionar Ubuntu (64-bit)

**Comment by MaximoBoglioli** [comment]
Si, era ese el problema
