### ISSUE TITLE
¿Cómo compilar correctamente el TP0?

### ISSUE THREAD

**Issue by Martin-Fedorenko** [sisoputnfrba/foro#2888]
### Contexto

Habiendo realizado todo lo pedido en la consigna del TP0 (a excepción de implementar los "paquetes"), el servidor y cliente ya pueden inicializar los sockets y conectarse entre si. Sin embargo a la hora de que se realice el "handshake" entre el cliente y el servidor, no percibo que el cliente "llegue a mandar la CLAVE" y que el servidor "llegue a recibir y notificar la CLAVE". Es decir, no hay interacción entre el cliente y el servidor.

### 📔 Citas del enunciado

![image](https://user-images.githubusercontent.com/67556470/229380136-69301178-a57e-4873-b685-5a4a5dcd1d3b.png)

### 💭 Soluciones posibles

Prender dos consolas, una que corra el servidor y otro que corra el cliente de tal manera que "puedan interactuar".

**Comment by RaniAgus** [comment]
¡Buenas! No entendí del todo si es una sola duda o varias, así que responderé en partes 😅 

> ¿Cómo compilar correctamente el TP0? 

Importando el TP como se indica en la [Etapa 1](https://docs.utnso.com.ar/primeros-pasos/tp0#etapa-1-setup-inicial) y luego compilando y ejecutando desde Eclipse:

![image](https://docs.utnso.com.ar/img/primeros-pasos/tp0/workspace-06.png)

> Sin embargo a la hora de que se realice el "handshake" entre el cliente y el servidor, no percibo que el cliente "llegue a mandar la CLAVE" y que el servidor "llegue a recibir y notificar la CLAVE". Es decir, no hay interacción entre el cliente y el servidor.

Eso deben implementarlo en el lugar donde dejamos el comentario:

https://github.com/RaniAgus/tp0/blob/master/client/src/client.c#L44-L45

Para aprender cómo hacerlo recuerden que tienen disponible la guía de sockets linkeada al principio de la [Etapa 3](https://docs.utnso.com.ar/primeros-pasos/tp0#etapa-3-programar-el-cliente-servidor)

> Prender dos consolas, una que corra el servidor y otro que corra el cliente de tal manera que "puedan interactuar".

Exactamente, son dos ejecutables distintos. Deben iniciar el servidor primero y el cliente después, pero recuerden primero implementar las funciones necesarias en el `main()`.

Saludos

**Comment by Martin-Fedorenko** [comment]
> Exactamente, son dos ejecutables distintos. Deben iniciar el servidor primero y el cliente después, pero recuerden primero implementar las funciones necesarias en el main().
Claro, esa era mi duda en realidad, como genero esos dos ejecutables para que luego interactúen?

**Comment by RaniAgus** [comment]
Justamente se compila usando el :hammer: (o apretando `Ctrl` + `B`) y se ejecuta con :arrow_forward: (o `Ctrl` + `F11`).

![workspace-06](https://docs.utnso.com.ar/img/primeros-pasos/tp0/workspace-06.png)

Deben elegir ejecutar ambos módulos como `Local C/C++ Application`:

![image](https://user-images.githubusercontent.com/39303639/229678471-95a03736-25f0-475d-9353-8b75c6b13af5.png)

**Comment by iago64** [comment]
Buenas @Martin-Fedorenko la respuesta de Agus te fue útil?

Saludos.-

**Comment by Martin-Fedorenko** [comment]
La verdad no del todo. Compilo primero servidor y luego cliente por separado y me sale los siguiente:

![image](https://user-images.githubusercontent.com/67556470/230504182-b26d2fd8-6ce5-49d6-bcec-3adf4c89b16f.png)
![image](https://user-images.githubusercontent.com/67556470/230504231-c4f51083-f4a3-4e1a-98b3-935293c5f019.png)

Pero no entiendo o al menos no logro hacer que el cliente mande el mensaje, el servidor lo reciba y eso aparezca en el log.

Dejo lo que hice hasta ahora: https://github.com/Martin-Fedorenko/TP0_SO.git

**Comment by RaniAgus** [comment]
Si te fijás en el cliente en la última línea hay un ">" que seguramente pertenece a un llamado a `readline("> ")`

Como se explica en el enunciado, esa función permite que el usuario ingrese valores por consola.

Una vez ingreses un valor, tocá enter y verás que el programa sigue :)

**Comment by Martin-Fedorenko** [comment]
Claro, pero haciendo eso solo se guarda en el log lo que ingrese por la consola. El log del server no cambia de ninguna manera.
![image](https://user-images.githubusercontent.com/67556470/230521148-8e3be0e6-d071-46f2-ae5c-ab16da9cdd55.png)

**Comment by RaniAgus** [comment]
Sisi, por ahora se está comportando como se espera. Hasta ahí estaría la parte de la [Etapa 2](https://docs.utnso.com.ar/primeros-pasos/tp0#etapa-2-comandos-basicos) y ahora el nuevo `readline` es para la [Etapa 3](https://docs.utnso.com.ar/primeros-pasos/tp0#etapa-3-programar-el-cliente-servidor) 😄
