### ISSUE TITLE
No puedo conectar cliente y servidor. No funciona crear_conexion

### ISSUE THREAD

**Issue by Hamamura-S** [sisoputnfrba/foro#2889]
Hola! Dejo abajo mi función crear_conexion del usuario, corre hasta el final porque me imprime el mensaje del final. 

![image](https://user-images.githubusercontent.com/129311632/229380161-f7111085-c3a0-4e7f-84d8-b971f2a8e0e2.png)

Pero despues en consola me sale un 'segmentation fault'

![image](https://user-images.githubusercontent.com/129311632/229380509-11ceb5c6-d21e-4f13-9bd8-b68811c3b7c2.png)

Del servidor creo que anda bien, está en espera a que le llegue algo en el accept pero nunca le llega algo. En el config están la misma ip y el mismo puerto que puse en iniciar_servidor

**Comment by RaniAgus** [comment]
¡Buenas! Antes que nada, porfa te recomiendo ampliamente leer primero el [README del foro](https://github.com/sisoputnfrba/foro/blob/master/README.md) ya que tiene sugerencias sobre cómo usarlo que nos ayudan a poder ayudarles.

Dicho esto, como no puedo copiar y pegar el código de la función, a ojo solo puedo deducir que no veo nada raro... ¿Intentaron usar el debugger para ejecutar el programa línea por línea y validar que realmente esté tirando Segmentation fault en esa función y no en otra? Tenemos una [guía de debugging en Eclipse](https://docs.utnso.com.ar/guias/herramientas/debugger) al respecto con tips y consejos.

Saludos

**Comment by Hamamura-S** [comment]
Hola! No encontré cosas raras debuggeando asi que comparto el codigo del servidor que lo deja en escucha
```
int iniciar_servidor(void)
{

	int socket_servidor;

	struct addrinfo hints, *servinfo, *p;

	memset(&hints, 0, sizeof(hints));
	hints.ai_family = AF_UNSPEC;
	hints.ai_socktype = SOCK_STREAM;
	hints.ai_flags = AI_PASSIVE;

	getaddrinfo("127.0.0.1", "23457", &hints, &servinfo);

	// Creamos el socket de escucha del servidor
	socket_servidor = socket(servinfo->ai_family,
						servinfo->ai_socktype,
						servinfo->ai_protocol);
	// Asociamos el socket a un puerto
	bind(socket_servidor, servinfo->ai_addr, servinfo->ai_addrlen);
	// Escuchamos las conexiones entrantes
	listen(socket_servidor, SOMAXCONN);

	freeaddrinfo(servinfo);
	//log_debug(logger, "Listo para escuchar a mi cliente");

	return socket_servidor;
}

int esperar_cliente(int socket_servidor)
{
	// Aceptamos un nuevo cliente
	log_debug(logger, "Servidor listo para recibir al cliente");
	int socket_cliente = accept(socket_servidor, NULL, NULL);
	log_info(logger, "Se conecto un cliente!");

	return socket_cliente;
}
```

Se queda en el accept de esperar_cliente eternamente :(

**Comment by RaniAgus** [comment]
Viendo esta línea:

```c
getaddrinfo("127.0.0.1", "23457", &hints, &servinfo);
```
1. La IP en `getaddrinfo()` no debería estar hardcodeada. En la [parte de `bind()` y `listen()` de la guía de sockets](https://docs.utnso.com.ar/guias/linux/sockets#bind-y-listen) tenemos una recomendación al respecto.

2. En el cliente, ¿están configurando el puerto para que apunte a `23457`?

Por otro lado, 

3. ¿A qué te referís con "No encontré cosas raras debuggeando"? ¿No se reproduce el mismo `Segmentation Fault` que ocurre al ejecutar el cliente directamente desde consola? Tené en cuenta que probablemente este error se produzca más adelante en el código, después de llamar a `crear_conexion()`, **no** ahí.

4. Les recomiendo chequear los valores de retorno de `getaddrinfo()`, `bind()`, `listen()`, `socket()`, `connect()`, etc, ya que puede ser que el programa continúe ejecutando con un socket inválido y falle más adelante por culpa de un error anterior. 

Pueden revisar cuál es el valor de retorno que deben chequear según cada función consultando el [manual online](https://man7.org/linux/man-pages/) o abriendo una consola y ejecutando `man nombre_de_funcion`. Ejemplos:

#### `getaddrinfo()`

![image](https://user-images.githubusercontent.com/39303639/229563535-4989e9be-1d81-4295-93d4-cb9ac3b6059d.png)
![image](https://user-images.githubusercontent.com/39303639/229563605-ab90c7c9-42c7-45d8-8b4d-59341da70f1b.png)

```c
int resultado_getaddrinfo = getaddrinfo(...);
if (resultado_getaddrinfo < 0) {
    fprintf(stderr, "Error en getaddrinfo: %s\n", gai_strerror(resultado_getaddrinfo));
    exit(-1);
}
```

#### `socket()`

![image](https://user-images.githubusercontent.com/39303639/229563716-b96bede3-7474-4f74-9798-c4e7b04778ca.png)
![image](https://user-images.githubusercontent.com/39303639/229564890-b587911b-9b1c-4deb-a5a2-3b53d7a5d88c.png)

```c
socket_servidor = socket(...);
if (socket == -1) {
    perror("Error en socket");
    exit(-1);
}
```

**Comment by Hamamura-S** [comment]
**UPDATE** Logré la conexión, solo modifiqué los parámetros de crear_conexion de
```
        memset(&hints, 0, sizeof(hints));
	hints.ai_family = AF_UNSPEC;
	hints.ai_socktype = SOCK_STREAM;
	hints.ai_flags = AI_PASSIVE;
```
por
```
        memset(&hints, 0, sizeof(hints));
	hints.ai_family = AF_INET;
	hints.ai_socktype = SOCK_STREAM;
```
copié lo que estaba en la guía tal cual estaba, yo lo tenia un poco distinto.

1. Se que la IP y el puerto las puedo leer del .config y guardarlas en dos punteros char*, pero el programa no funciona cuando reemplazo "127.0.0.1" por ```ip``` por ejemplo. Invoco ```conexion = crear_conexion(ip, puerto);``` y en crear_conexion escribo ```getaddrinfo(ip, valor, &hints, &server_info);``` y obtengo un segmentation fault por consola. Si hardcodeo se envía un mensaje (aunque no se recibe como debería, en vez de "valor" se recibe "LINE=24" pero creo que es otro issue)
2. Los puertos están revisados y re-revisados

**Comment by Hamamura-S** [comment]
Pongo NULL en IP del servidor, por otra parte el segmentation fault era en el cliente y lo arreglé moviendo el config_destroy hacia el final del codigo :skull: no sabía que los punteros `char*` dependían de que el config esté activo, por eso también era el segmentation_fault, el puntero apuntaba a cualquier parte.

Gracias por las sugerencias y la paciencia, seguiré molestando en otros issues :wave:

**Comment by RaniAgus** [comment]
Oops! Es cierto, me llevo ese feedback para más adelante documentar mejor los side effects de `config_destroy`, gracias 👍🏻
