### ISSUE TITLE
No puedo sacar capturas de pantalla en la VM

### ISSUE THREAD

**Issue by irinaperezg** [sisoputnfrba/foro#2890]
Hola! Tengo un problema para sacar captura de pantalla en la VM, ya tengo las guest additions instaladas. Un compañero me dijo que trate de hacer en la consola "sudo apt install xfce4-dev-tools -y" pero al hacerlo me sale "Unable to locate package xfce4-dev-tools"
No se que puede pasar, todo lo demás me anda bien, el portapapeles también.

### 💻 Logs
Cuando toco la tecla impr pant del teclado me sale:
Failed to launch shortcut "Print"
Failed to execute child process "xfce4-screenshooter" (No such file or directory)

**Comment by RaniAgus** [comment]
¡Buenas! Estuve haciendo pruebas y, sí, al parecer nos faltó instalar `xfce4-screenshooter`, que es el programa para sacar capturas de pantalla.

Lo pude instalar sin drama con estas dos líneas:
```bash
sudo sed -i "s/\#\$nrconf{restart} = 'i';/\$nrconf {restart} = 'l';/" /etc/needrestart/needrestart.conf
sudo apt install xfce4-screenshooter
```

Igual algo que suelo usar para sacar capturas directamente desde fuera de la VM es ir a `File` > `Preferences` > `Input` y desactivar `Auto Capture Keyboard`:

![image](https://user-images.githubusercontent.com/39303639/229946183-3bbac622-0117-4dd3-9948-8dd18c2a5f92.png)

Esto también hace que otros comandos como Alt+Tab o la tecla Windows también solo funcionen desde fuera de la VM, como si VirtualBox fuera un programa cualquiera.

Saludos

**Comment by irinaperezg** [comment]
Muchas gracias, con esto se me solucionó :)
