### ISSUE TITLE
No me coincide el hash del .vdi de la VM Xubuntu

### ISSUE THREAD

**Issue by geroPenaflor** [sisoputnfrba/foro#2891]
Buenas noches, estuve buscando bastante y la verdad no encuentro que a nadie le haya surgido que el hash del .vdi no coincida con el estipulado. Trato de ir paso a paso porque también tengo otros mensajes raros en el medio. 
Los archivos que descomprimo son estos:
![imagen](https://user-images.githubusercontent.com/102915702/229953769-a2f966b1-547b-40fd-8436-e060c5292d39.png)

Luego de descomprimir (con 7-Zip) me saltan los siguientes problemas:
![imagen](https://user-images.githubusercontent.com/102915702/229951152-f6bc6640-0ac3-4cc3-a4ee-3b2c16da71b4.png)

Aparece entonces: el archivo "Grafica.vdi" y una carpeta llamada "VM Entorno Grafico 6.1", dentro de la cual se encuentra el archivo "Grafica.zip.002" (no quería insertar foto acá para no poner tantas, pero es exactamente lo que describo). 

Yo entonces controlo hash con Powershell, y me dan bien los de Grafica.zip-001.001 (Archivo comprimido, el de la primera foto) y el de Grafica.zip.002, pero NO es así con Grafica.vdi, a lo cual yo supongo está relacionado con el "Data error" que me salta en 7-Zip, pero no se a ciencia cierta. Me da d4290b345d7948c8f870826054fd445a en lugar de b417a5eda3d50de7a03a0c4c6114006e

De veras busqué hasta bien atrás a ver si encontraba un problema similar, pero noté que la mayoría estaban relacionados ya con el inicio de la MV en VirtualBox, yo acá ya tengo un problema de descarga que no se cómo solucionar. No se si influye el navegador, pero yo descargué primero de Firefox (mi predeterminado) y luego probé de Chrome a ver si cambiaba algo pero nada. 

Quedo atento a cualquier ayuda, y desde ya muchas gracias!

### 🖥️ Especificaciones del host
- Sistema Operativo y versión: Windows 10 Home 21H2 (64 bits)
- Memoria RAM: 16 GB
- Procesador: Intel(R) Core(TM) i7-1165G7

**Comment by iago64** [comment]
Buenas! Cómo va?

Si te coinciden los hashes de las partes, proba de usar 7zip como dice en el [sitio de docs](https://docs.utnso.com.ar/primeros-pasos/entorno-linux), ya que de hecho fue el software que se uso para "cortar" el archivo comprimido.

Saludos.-

**Comment by geroPenaflor** [comment]
Solucionado! Estaba interpretando mal el cómo descomprimir, ya lo hice como corresponde y me da bien el hash.
De igual manera, me seguía tirando el error de "Data error" al querer descomprimir con el nombre "Grafica.zip-001.001". Cuando lo cambié a "Grafica.zip.001" ahí me dejó incluso descomprimirlo directo con WinRAR, que vi que a muchos no les dejaba. 
Muchas gracias!
