### ISSUE TITLE
Error E_FAIL (0X80004005)

### ISSUE THREAD

**Issue by Nicolucena** [sisoputnfrba/foro#2892]
Hola, tengo un problema con el virtualbox.  Cuando quiero iniciar una maquina virtual, empieza a cargarla pero no llega a abrirse y me tira el error E_FAIL (0X80004005). Yo investigué si se podía resolver y me encontré con dos videos en los que decía que había que pegar un código en el command, pero me sigue tirando el problema. Aclaro que me descargué la versión VirtualBox 7.0.6. Abajo dejo todo el código del error que me tira. 

VM Name:Ubuntu
Not in a hypervisor partition (HVP=0) (VERR_NEM_NOT_AVAILABLE).</p>
VT-x is disabled in the BIOS for all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED).

Result Code:  E_FAIL (0X80004005)
Component: ConsoleWrap
Interface: IConsole {6ac83d89-6ee7-4e33-8ae6-b257b2e81be8}

**Comment by iago64** [comment]
Buenas! Cómo va?

Algo copado del foro es que pueden buscar en los issues cerrados y no esperar 7 horas a que un ayudante vea el issue y les conteste.
En este caso este es un tema conocido y ya hubo varias resoluciones, por ej en los issues: #2022 y #2013 😄 

Por favor confirmanos si esos issues te ayudaron a resolver el inconveniente.
Saludos.-

**Comment by Nicolucena** [comment]
Si, perdón no sabia lo de los temas cerrados. Pude solucionar el problema buscando un poco mejor porque las soluciones que me aparecieron cuando busque por primera vez no me sirvieron, pero pude encontrar la solución. Muchas Gracias

**Comment by iago64** [comment]
Buenas!

No hay problema, siempre les recordamos el tema de buscar en issues cerrados justamente para que no pierdan tiempo y puedan resolver sus problemas lo mas rapido posible 😄 

Si el problema esta resuelto por favor no te olvides de cerrar el issue 😉 

Saludos.-
