### ISSUE TITLE
Duda sobre serializacion (void* a_enviar)

### ISSUE THREAD

**Issue by cserrudo** [sisoputnfrba/foro#2893]
Buenas, tengo una consulta en esta parte del codigo cuando armamos el stream despues de llenar el paquete con el buffer en la guia de serializacion:

```c
typedef struct {
    uint8_t codigo_operacion; // <--
    t_buffer* buffer;
} t_paquete;

typedef struct {
    uint32_t size; // <--
    void* stream;
} t_buffer;


// Armamos el stream a enviar
void* a_enviar = malloc(buffer->size + sizeof(uint8_t) + sizeof(uint32_t));
```

Mi duda es por qué al pedir memoria para el stream a enviar se debe pasar por parametros la suma de los 3, no me estaría dando cuenta de que representan, no sé si por el int8_t se refiere al tipo del opcode (codigo de operacion) y al uint32_t es el tipo del tamaño del payload, siendo el buffer->size el tamaño de la suma de los tipos. Si es así, por qué se deben sumar? Y si no es, que representaria cada uno

**Comment by cserrudo** [comment]
Claro! mi confusión también venia por el lado de que el tamaño del buffer lo consideraba como el contenido el buffer, pero ahora veo que no son lo mismo. Gracias

**Comment by iago64** [comment]
@cserrudo Por favor si la duda fue resuelta, no te olvides de cerrar el issue 😄
