### ISSUE TITLE
Consulta puerto de la memoria en la config de file system

### ISSUE THREAD

**Issue by gabdigiorgio** [sisoputnfrba/foro#2894]
Hola, estuve tratando de hacer la conexión entre el módulo file system y el de memoria pero me encontre con una discrepancia en las configs de el enunciado del TP.

### 📔 Citas del enunciado/videos

En el archivo de configuración de la memoria (página 27) el puerto es 8002:
>**PUERTO_ESCUCHA=8002**
TAM_MEMORIA=4096
TAM_SEGMENTO_0=128
CANT_SEGMENTOS=16
RETARDO_MEMORIA=1000
RETARDO_COMPACTACION=60000
ALGORITMO_ASIGNACION=BEST

Mientras que en el archivo de configuración del file system (página 31) el puerto de la memoria es 127.0.0.1:
>IP_MEMORIA=127.0.0.1
**PUERTO_MEMORIA=127.0.0.1**
PUERTO_ESCUCHA=15471
PATH_SUPERBLOQUE=/home/utnso/fs/superbloque.dat
PATH_BITMAP=/home/utnso/fs/bitmap.dat
PATH_BLOQUES=/home/utnso/fs/bloques.dat
PATH_FCB=/home/utnso/fs/fcb
RETARDO_ACCESO_BLOQUE=15000

### 💭 Soluciones posibles
La solución que encontre para que me funcione fue poner en la config de del file system el valor de 8002 para el puerto de la memoria.

**Comment by LeandroCarbajales** [comment]
Buenas! Claramente metimos un copy-paste mal ahí, en breve lo arreglamos en el enunciado. Gracias por reportarlo!
El puerto_memoria de todos los módulos (FS,Kernel y CPU) debe ser el mismo que expone la memoria en puerto_escucha como bien decís.

**Comment by LeandroCarbajales** [comment]
Ya debería estar arreglado, también actualizamos el ejemplo de puerto_escucha del FS a 8003 para que coincida con el ejemplo del Kernel.
Si ahí lo ves bien, podés cerrar el issue :)

**Comment by gabdigiorgio** [comment]
Perfecto, muchas gracias!
