### ISSUE TITLE
repositorio de grupo de TP

### ISSUE THREAD

**Issue by tomasmartinez02** [sisoputnfrba/foro#2895]
Hola, me llego el mail para unirme al repo de mi grupo pero cuando entro para unirme, me aparece error 404. Mis compañeros me dicen que no me ven como participante del repo, quisiera poder solucionarlo para empezar a trabajar.
Mail: t***********@frba.utn.edu.ar (asociado a github)
Legajo: ******-*
Nombre: T**** M*******
Curso: K****
Desde ya gracias.

**Comment by LeandroCarbajales** [comment]
Buenas @tomasmartinez02 !
Les sirvió la respuesta de @iago64 ?

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, ante cualquier consulta pueden reabrirlo o abrir uno nuevo. Saludos
