### ISSUE TITLE
ERROR visual code 

### ISSUE THREAD

**Issue by MorosiniP** [sisoputnfrba/foro#2896]
Buenas! Estoy en la maquina virtual... 

En eclipse el proyecto del tp0 la parte dos (que es hasta donde llegue por ahora) esta todo ok

Pero al momento de querer hacer eso mismo en el visual que  esta instalado en la .vdi me sale el siguiente error

`format not a string literal and no format arguments [-Wformat-security]`

y me lo marca 3 veces... este es un fragmento de mi codigo que me marca el logger del parametro log_info

`ip = config_get_string_value(config,key);
		log_info(logger,ip);
`

Hay alguna solución posible? SI no usare el eclipse peo como estoy familiarizado con el visual me era mas fácil
Gracias

**Comment by RaniAgus** [comment]
¡Buenas!

Lamentablemente el TP0 está armado para que se pueda importar directamente desde Eclipse. Si quieren usar Visual Studio Code hará falta configurar el debugger y la compilación a mano (o usar un template como el de #2007).

De todas formas, lo que está resaltando el IDE (que no es un error, sino más bien un warning, si lo compilan con `gcc` probablemente no les falle) se debe a que las funciones de log de las commons tienen el mismo formato que `printf`.

¿Qué significa esto? Que se espera que el primer parámetro sea un string _literal_ que contenga el _template_ de lo que se va a imprimir, y no una variable. O sea:

```c
char *saludo = readline("> ");

printf("%s\n", saludo); // Esta es la forma correcta
printf(saludo); // Esta forma también funciona, pero es insegura y arroja warning

log_info(logger, "%s", saludo); // Esta es la forma correcta
log_info(logger, saludo); // Esta forma también funciona, pero es insegura y arroja warning

```

El warning se debe a razones de seguridad, pueden encontrar detalles al respecto en este link: https://owasp.org/www-community/attacks/Format_string_attack

**Comment by LeandroCarbajales** [comment]
Buenas @MorosiniP !
Te sirvió la respuesta de @RaniAgus ?

**Comment by MorosiniP** [comment]
> Buenas @MorosiniP !
> Te sirvió la respuesta de @RaniAgus ?

Buenas! Aaa okey bien, ahí lo corrijo igual si me rendi y ya me estoy amigamdo con eclipse!
Muchas gracias!!

**Comment by RaniAgus** [comment]
¡Buenas, @MorosiniP!
Por favor, si la duda fue resuelta, no te olvides de cerrar el issue 😄
