### ISSUE TITLE
Consulta super_paquete del TP0

### ISSUE THREAD

**Issue by LFLarocca** [sisoputnfrba/foro#2897]
Buen día! Perdón por molestar en el finde largo, quería consultar algo del tp0. Con mi grupo estuvimos viendo la cuestión del **superpaquete** para envíos entre cliente y servidor, y no terminamos de entender bien _qué es_ o cómo podríamos implementarlo. El fragmento de código que tenemos insinúa que deberíamos tratarlo como un paquete normal, ¿Sería un conjunto de paquetes dentro de uno mayor? Desde ya mil gracias!

![image](https://user-images.githubusercontent.com/102746549/230423321-d59d08be-d6ac-48d2-871a-bb4bff677842.png)

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va?

Al parecer se ve que esa función nos quedó de una versión previa del TP0, en la que había una cuarta etapa explicando brevemente cómo usar el debugger. Sin embargo, la quitamos porque probablemente ya hayan necesitado usarlo antes (y sino, les recomendamos chusmear la [Guía de Debugging](https://docs.utnso.com.ar/guias/herramientas/debugger), ya que es una herramienta fundamental para detectar errores rápidamente).

En resumen, no se preocupen que esa función no debería estar ahí 😅 

Saludos

**Comment by LeandroCarbajales** [comment]
Buenas @LFLarocca !
Te sirvió la respuesta de @RaniAgus ? Si es así podés cerrar el issue.

**Comment by LFLarocca** [comment]
Buenísimo! Muchas gracias @RaniAgus.
Saludos!

**Comment by LFLarocca** [comment]
Buen día Profe!
Recién respondí y cerré el issue, gracias por la respuesta y atención.
Saludos!
