### ISSUE TITLE
Inlcuir archivos de otro proyecto

### ISSUE THREAD

**Issue by matolivaUTN** [sisoputnfrba/foro#2898]
Hola buenos dias, estamos teniendo un problema a la hora incluir archivos de otros proyectos.
Para nuestro TP creamos un proyecto por cada modulo y queriamos crear otro proyecto que tenga cosas comunes para todos. Cuando queremos importar archivos de este proyecto compartido a otro modulo haciendo #include "../shared/include/utils.h" no encuentra el path.
La estructura de nuestro tp por ahora es:
![WhatsApp Image 2023-04-06 at 13 37 56](https://user-images.githubusercontent.com/102746569/230442507-93ab976e-285f-4327-a42a-5fb50314102f.jpeg)
Queriamos consultar si hay alguna configuracion adicional que hay que hacer en eclipse. 
Muchas gracias.

**Comment by LeandroCarbajales** [comment]
Buenas!
Lo primero que chequearía es si la ruta relativa del #include es desde la ubicación raíz del proyecto o si es desde la ubicación del archivo .c que se encuentra en la carpeta src, en ese caso probablemente tengan que ir hacia atrás una vez más haciendo por ejemplo "../../shared/loquesiga"

Por otro lado, si lo que quieren es tener una biblioteca compartida, es decir, tener un proyecto con código compilado que luego se ejecute en otros proyectos, les recomiendo leer la [guía de _shared libraries_](https://docs.utnso.com.ar/guias/programacion/shared-libraries).
En el video se explica cómo crear estas bibliotecas compartidas y cómo incluirlas en los otros proyectos :)

**Comment by matolivaUTN** [comment]
Buenas, lo que estabamos buscando era una shared library como mencionaste. Siguiendo la guia lo pudimos solucionar, muchas gracias.
