### ISSUE TITLE
Problemas con t_log* y t_create*

### ISSUE THREAD

**Issue by maxideluca** [sisoputnfrba/foro#2899]
Buenas, ya tengo la maquina virtual bajada con las commons tambien. Las linkie con el tp0, pero, en el archivo client.c, cuando me paro sobre t_log* y t_config*, me tira un error de "could not be resolved". Pero me deja utilizar funciones como destroy_log o create_log. Desde ya muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

Para poder darte una mano, necesitamos saber si estas usando eclipse o vs code y como linkeaste las commons, ya que si las instalaste como dice en el [repo de las commons](https://github.com/sisoputnfrba/so-commons-library), deberías poder ver el archivo .h (mas no él .c, ya que ese esta compilado)

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Para sumar, en caso de que Eclipse tire errores raros de no encontrar enums o tipos a pesar de haberlos importado y tener todo instalado, conviene probar de hacer click en "Project > C/C++ Index > Rebuild" para que el IDE actualice las referencias del proyecto.

**Comment by maxideluca** [comment]
> ¡Buenas! Para sumar, en caso de que Eclipse tire errores raros de no encontrar enums o tipos a pesar de haberlos importado y tener todo instalado (como se ve en [#2556 (comment)](https://github.com/sisoputnfrba/foro/issues/2556#issuecomment-1103991425)), conviene probar de hacer click en "Project > C/C++ Index > Rebuild" para que el IDE actualice las referencias del proyecto.

Gracias chicos ya lo pude resolver
