### ISSUE TITLE
Dudas sobre los Módulos a implementar 

### ISSUE THREAD

**Issue by MiltonMartorello** [sisoputnfrba/foro#2900]
Holis, soy Milton! Terminé el TP0 el finde pasado y me sentí D10s. Ahora leí el enunciado del señor TP y estoy en posición fetal. Para no dejar pasar el tiempo voy a preguntar todo lo que no estoy entendiendo, como para que me vayan cerrando algunas ideas ya que el enunciado me pegó un cachetazo con onomatopeya de látigo.

### 📔 Citas del enunciado/videos

1. Sobre la cantidad de Módulos

> El trabajo práctico consiste de 5 módulos: Consola (múltiples instancias), Kernel, CPU, Memoria y File System (1 instancia cada uno).

1.1) Cuando habla de que la consola tiene múltiples instancias y los demás módulos tienen 1. Yo me imagino 5 máquinas corriendo donde la máquina que tiene el módulo consola levanta varias veces el proceso consola apuntando a un mismo kernel. Estoy errado?
1.2) Interpretar que el CPU y el Kernel podrían estar en el mismo módulo es erróneo?

2. Sobre el Kernel

> Este módulo deberá mantener una conexión activa con la CPU, la Memoria, File System y las diferentes consolas que se conecten.

2.1) Por lo que interpreto el Kernel debe estar como muy pendiente de los demás módulos y entiendo que va a recibir y enviar distintos tipos de mensajes. Me estoy imaginando que mucho de lo que se armó para el TP0 entra en lo que es el Kernel, o por lo menos esa parte de la escucha activa que tiene el servidor. Esta bien pensar que el TP0 es la base del kernel? 
2.2) Y pregunto también si no me estoy quedando corto y en realidad el servidor es algo que deba implementar en todos los módulos que reciban mensajes? 

Muchas gracias!

**Comment by iago64** [comment]
Buenas! Cómo va? Justamente la idea del TP0 es que sea ese primer boost de adrenalina de ver cosas funcionando, imaginate cuando no existía y te chocabas de frente con el tp... era feo 😢 

Respondiendo tus consultas que están muy bien planteadas:

1.1.- No necesariamente vas a tener 5 maquinas (podrías correr todo en una misma máquina) pero si estas en lo correcto de que vas a correr varias veces el ejecutable de la consola 😄 

1.2.- Si, son 2 módulos o programas distintos que se tienen que comunicar por socket.

2.1.- Esta bien en pensar que el servidor del TP0 es una base del Kernel, ya que es servidor de las consolas, pero también el Kernel es cliente de CPU, Memoria y File System, con lo cual, la idea es que puedan de alguna manera copada, primero conectarse a todos procesos de los que son clientes y si este todo ok, recién ahi levantar el servidor para las consolas 😉 

2.2.- Algo copado de las conexiones es que quien es cliente y quien es servidor es simplemente para definir quien se conecta y quien espera las conexiones, pero una vez establecidas, los mensajes pueden iniciar en cualquiera de los módulos 😉 

Por último, no por stalker, pero veo que no estas en el [sistema de inscripciones](https://inscripciones.utnso.com.ar/), por favor no cuelgues en anotarte y en crearte / unirte a un grupo, ya que el tp es de 5 personas y no creo que quieras hacer el laburo de 5 vos solo 😄 

Saludos.-
