### ISSUE TITLE
Checkpoint 1: Dudas sobre protocolo de comunicación y conexiones

### ISSUE THREAD

**Issue by MiltonMartorello** [sisoputnfrba/foro#2901]
Buenas dejo otra consulta y la separo de la otra para visibilizarla
Estuve viendo que el sábado 15/04 ya debemos presentar grupo y protocolo de comunicación. Quería entender un poco más cómo es la dinámica de esa presentación, que tan preparado hay que ir.

### 📔 Citas del enunciado/videos

>Definir el Protocolo de Comunicación.

Esto como se presenta? En un diagrama? 
Que nivel de detalle debería tener? Nombre de mensaje y datos que se envían?

>Todos los módulos están creados y son capaces de establecer conexiones entre sí.

Esto se puede mostrar desde el eclipse o ya es necesario bajarse la vm sin gráfica y tenerlo compilado para correrlo por consola?

Muchas gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Antes que nada, perdón por el mal entendido que se pueda dar a partir de las Normas de Trabajo Práctico, no todos los checkpoints son entregas per se, sino que son una guía para ayudarlos en el avance del tp.

Dicho lo anterior, si quieren validar el protocolo, con algun ayudante, con que lo tengan más o menos claro y lo puedan explicar les sobra. Lo copado de estas validaciones es que un ayudante les puede simplificar la implementación.

Un poco más de lo anterior, los checkpoints no son entregas, con lo cual, si quieren mostrar código (hasta la entrega final) pueden hacerlo en las VMs con entorno gráfico.

Saludos.-
