### ISSUE TITLE
No funciona esperar_cliente(), problema con connect

### ISSUE THREAD

**Issue by cserrudo** [sisoputnfrba/foro#2902]
Buenas, busqué mi duda en anteriores issues pero ninguno me daba solución, estoy teniendo un problema en el main del server.c en esta linea:

`int cliente_fd = esperar_cliente(server_fd);`

después de esta linea se queda ahi y viendo como tengo implementado esperar_cliente, supongo que es por el accept pero lo raro es que ni siquiera me aparece el mensaje de error.

```

int esperar_cliente(int socket_servidor)
{
// Aceptamos un nuevo cliente
int socket_cliente = accept(socket_servidor, NULL, NULL);

if(socket_cliente == -1){
printf("ERROR EN ACCEPT: ", strerror(errno));
}
log_info(logger, "Se conecto un cliente!");

return socket_cliente;
}
```

lo ultimo que me aparece es el **"Servidor listo para recibir al cliente"** que está una linea antes del esperar cliente, después de eso se queda ahí. 

PD: en el iniciar servidor CREO que tengo todo bien porque no me marcó nada y tengo probados el getaddrinfo, connect, bind, listen etc. Y en el cliente tengo configurado el puerto que es el "4444" y la IP que es "127.0.0.1", por las dudas.

**Comment by iago64** [comment]
Buenas! Cómo va?

Justamente algo interesante de las conexiones es que algunas de sus funciones lo que hacen es colgar el proceso (o el hilo mejor dicho) que las ejecuta hasta que pasa algo.
En el caso del `accept()`, es justamente una de estas funciones, que va a detener la ejecución hasta que se le conecte algo, esto es algo que se explica un poco mejor en la [guía de sockets](https://docs.utnso.com.ar/guias/linux/sockets).

Con lo cual, respondiendo a tu pregunta, es posible que no tengas un error, sino que simplemente le estes pasando puertos distintos y por eso no se conectan los procesos.

Saludos.-

**Comment by cserrudo** [comment]
Claro como hace una llamada al sistema, va a esperar (se va a bloquear) hasta que un cliente se conecte. 
El tema es que configure los mismos puertos para los dos, por las dudas cambié de puerto al cliente y el servidor, al "23456" y sigo teniendo el mismo problema, los configure asi: 

```
int conexion;
char* ip = "127.0.0.1";
char* puerto = "23456";
char* valor;
```

y esto es en el servidor: 
`int resuaddrinfo = getaddrinfo(IP, "23456", &hints, &servinfo)`

Me estaría olvidando cambiar en otro lado más? o es otro el problema? Gracias

**Comment by LeandroCarbajales** [comment]
Buenas @cserrudo !
Dejo para que chusmees también el issue #2903 ya que podría ser un caso similar

**Comment by cserrudo** [comment]
Gracias!
