### ISSUE TITLE
No podemos conectar el Cliente con el Servidor

### ISSUE THREAD

**Issue by juanibencardino** [sisoputnfrba/foro#2903]
Buenas, estamos trabados con el TP0 ya que al ejecutar el servidor y luego el cliente, no se conectan. En la consola del servidor solo queda el "Servidor listo para recibir al cliente". Verificamos que nos devolvía cada función viendo en el manual que devolvía en caso de error y ninguna nos devolvía este caso. La consola no tira ningún error. 

Entiendo que nos esta faltando algo pero lo estuvimos viendo todo el día hoy y no sabemos que estamos haciendo mal.
También vimos otros issues como el #2889 pero no logramos solucionarlo. 

Adjunto código de iniciar_servidor, esperar_cliente y crear_conexion.

Agrego a @LucianoFoglia @Plata92 

iniciar_servidor()
```
int iniciar_servidor(void)
{
	// Quitar esta línea cuando hayamos terminado de implementar la funcion
	//assert(!"no implementado!");

	int socket_servidor;

	struct addrinfo hints, *servinfo, *p;

	memset(&hints, 0, sizeof(hints));
	hints.ai_family = AF_UNSPEC;
	hints.ai_socktype = SOCK_STREAM;
	hints.ai_flags = AI_PASSIVE;

	getaddrinfo(NULL, PUERTO, &hints, &servinfo);

	// Creamos el socket de escucha del servidor

	socket_servidor = socket(servinfo->ai_family,
							 servinfo->ai_socktype,
							 servinfo->ai_protocol);

	// Asociamos el socket a un puerto

	bind(socket_servidor, servinfo->ai_addr, servinfo->ai_addrlen);


	// Escuchamos las conexiones entrantes

	listen(socket_servidor, SOMAXCONN);


	freeaddrinfo(servinfo);
	log_trace(logger, "Listo para escuchar a mi cliente");

	return socket_servidor;
}
```
esperar_cliente()
```
int esperar_cliente(int socket_servidor)
{
	// Quitar esta línea cuando hayamos terminado de implementar la funcion
	//assert(!"no implementado!");

	// Aceptamos un nuevo cliente
	int socket_cliente;
	socket_cliente = accept(socket_servidor, NULL, NULL);
	log_info(logger, "Se conecto un cliente!");


	return socket_cliente;
}
```
crear_conexion
```
int crear_conexion(char *ip, char* puerto)
{
	struct addrinfo hints;
	struct addrinfo *server_info;

	memset(&hints, 0, sizeof(hints));
	hints.ai_family = AF_UNSPEC;
	hints.ai_socktype = SOCK_STREAM;
	hints.ai_flags = AI_PASSIVE;

	getaddrinfo(ip, puerto, &hints, &server_info);

	// Ahora vamos a crear el socket.
	int socket_cliente = 0;

	socket_cliente = (server_info->ai_family,
					  server_info->ai_socktype,
					  server_info->ai_protocol);

	// Ahora que tenemos el socket, vamos a conectarlo

	if ((connect(socket_cliente, server_info->ai_addr, server_info->ai_addrlen))== -1){
		printf("Error al conectar cliente de serivdor.");
	}


	freeaddrinfo(server_info);

	return socket_cliente;
}
```

### 📔 Citas del enunciado/videos

Consigna
El entregable de esta etapa es enviar al servidor el valor de CLAVE en el archivo de configuración, y luego enviarle todas las líneas que se ingresaron por consola juntas en un paquete.

Simplificando un poco, una conexión por socket hacia otro programa va a requerir de realizar lo siguiente:

- Iniciar el servidor en la función iniciar_servidor() del utils del server.
- Esperar a que el cliente se conecte mediante la función esperar_cliente()
- Crear una conexión contra el servidor en la función crear_conexión() del utils del client.
- Enviar como mensaje el valor de CLAVE.
- Ir juntando las líneas que se leen por consola para luego enviarlas como paquete.
- Cerrar la conexión.

**Comment by MiltonMartorello** [comment]
Hola @juanibencardino, primero aclaro que soy alumno no ayudante. Puede ser que te este faltando bindear el socket a un puerto y luego dejarlo escuchando en crear_conexion? Es tal cual lo que hiciste en el servidor pero replicado en el cliente.
Entiendo que ahi estarías configurando el socket de lado cliente y me parece que si no haces esos pasos nunca vas a recibir una respuesta del server, pero puedo estar errado che.
Espero sirva, saludos

**Comment by LeandroCarbajales** [comment]
Buenas!
Probaron ejecutar el cliente con el debugger para saber en qué línea se corta la ejecución?

Del lado del servidor, si la última línea en la consola es `Servidor listo para recibir al cliente`, significa que está _bloqueado_ en el `accept()` de `esperar_cllente()`, de lo contrario avanzaria y loguearía `Se conecto un cliente!`.

Si el cliente tampoco loguea nada lo que puede estar pasando es que el cliente no esté intentando conectarse por ejemplo por estar _bloqueado_ en la función `readline()` de leer_consola()` esperando a que ingresen un mensaje por consola que está a modo de ejemplo antes de establecer la conexión.
Chequeen si eso es lo que está pasando, la idea es que puedan luego, una vez establecida la conexión, enviar cualquier mensaje que escriban por consola en un paquete para que le llegue al servidor :)

**Comment by juanibencardino** [comment]
Hola! Gracias por las respuestas!

Estuvimos debuggeando un poco mas y parece que es el ` acept(); ` de ` esperar_cleinte(); ` como bien dice Leandro.

Mañana ibamos a continuar temprano para ver como lo solucionamos. 

Con respecto al cliente. Si logue pero tood sobre las etapas anteriores, lo ultimo que aparece en consola es el > del readline esperando para recibir texto hasta el enter. 

Ahora que estoy escribiendo esto en ningun momento aprete enter. Por esto puede ser que no continue no? jajajja bueno mañana veremos.

Aviso cualquier cosa

Gracias!

**Comment by RaniAgus** [comment]
¡Buenas! Viendo el código del principio, ¿puede ser que hayan borrado sin querer el llamado a `socket()` en `crear_conexion()`?

```c
int socket_cliente = 0;
socket_cliente = (server_info->ai_family,
					  server_info->ai_socktype,
					  server_info->ai_protocol);
```

Sería:

```c
int socket_cliente = socket(server_info->ai_family,
					  server_info->ai_socktype,
					  server_info->ai_protocol);
```

**Comment by juanibencardino** [comment]
Buenaaas, 

Les comento que ya esta solucionado, en mi codigo pasaba que faltaba el llamado a socket(). Pero tambien estabamos olvidandonos de tocar enter para que salga de ` leer_consola() `

Muchas gracias por la ayuda. ;)
