### ISSUE TITLE
problema para leer config

### ISSUE THREAD

**Issue by maxideluca** [sisoputnfrba/foro#2905]
Buenas, pude loguear bien y mostrar por consola la primera parte, El problema empieza cuando empiezo config, primero intente copiando la ruta en la funcion "config_create" ----> "./cliente.config", y no me corrio, luego copie entera la ruta "/home/utnso/tp0/client/cliente.config"). Desde ya muchas gracias

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va?
Me suena a que es un problema de rutas relativas vs absolutas, por suerte tenemos una mini-guía explicando eso acá: https://docs.utnso.com.ar/guias/consola/rutas

Saludos

**Comment by maxideluca** [comment]
> ¡Buenas! ¿Cómo va? Me suena a que es un problema de rutas relativas vs absolutas, por suerte tenemos una mini-guía explicando eso acá: https://docs.utnso.com.ar/guias/consola/rutas
> 
> Saludos

Acabo de leer la guia pero no me termina de quedar claro cual es el problema. Por lo que vi tengo el mismo workspace, y consulte con compañeros y a ellos al corrrer esa ruta les lee el valor y se los imprime en pantalla. No sabria cual es el error.

**Comment by RaniAgus** [comment]
Mmm raro... Probemos de agregar estas 3 líneas al `main()` de tu programa para verificar que el cwd es la ruta que esperabas:

```c
    char *current_dir = getcwd(NULL, 0);
    printf("El directorio actual es %s\n", current_dir);
    free(current_dir);
```

**Comment by LeandroCarbajales** [comment]
Hola @maxideluca !
Pudieron resolver este problema?

**Comment by LeandroCarbajales** [comment]
Cierro el issue por inactividad, si persiste el problema lo podés volver a abrir :)
