### ISSUE TITLE
consulta de consigna de paquete del tp0

### ISSUE THREAD

**Issue by adrianquispe** [sisoputnfrba/foro#2906]
buenas, tengo una duda con el tema de los mensajes por consola y el paquete a enviar.
en el momento que se escribe por consola aparte de loguear en cliente el mensaje, hay que empaquetarlo y enviarlo al servidor o hay que "juntarlas" para enviar varias a la vez. 
edit: la duda esta enfocada en que para hacer lo que pide el enunciado, tendria que modificar el comportamiento de las funciones dadas y nose si requiere hacerlo con lo que esta dado (por ejemplo a leer_consola le agrege un parametro mas o que una funcion void ahora tenga retorno)

**Comment by LeandroCarbajales** [comment]
Buenas!
No hay problema que modifiques funciones existentes o crees nuevas si te sirven para el hacer el trabajo :)
La idea sería juntarlas (hasta ingresar un string vacío) para luego empaquetarlo y enviarlo al servidor.

**Comment by adrianquispe** [comment]
dale, igual ya aclare el tema en discord, gracias
