### ISSUE TITLE
Problemas para utilizar código de shared libraries

### ISSUE THREAD

**Issue by MiltonMartorello** [sisoputnfrba/foro#2908]
Buenas, hoy estuvimos luchando muchísimo con eclipse y el compilador de C para incluír algunas funciones del tp0 en los distintos proyectos.

Nuestro problema radica en la utilización de código compartido.
Queremos correr la función inciar_servidor en varios módulos es por esto que llevamos esa función al proyecto shared para incluirlo en todos nuestros módulos. El proyecto compila luego de ver las guías de shared libraries, pero tiene errores al ejecutar.

### 📝 Código relevante

el main en cpu/src/cpu.c
```
int main(void) {

	puts("!!!Hello World!!!"); /* prints !!!Hello World!!! */

	t_log* logger;
	if((logger = log_create("tp0.log","TP0",1,LOG_LEVEL_INFO)) == NULL) {
		printf("no pude crear el logger \n");
		exit(1);
	}
	log_info(logger, "test de log");
	int server_fd = iniciar_servidor(); // <----- FALLA ACÁ
	log_info(logger, "Iniciada la conexión de servidor: %d",server_fd);
	return EXIT_SUCCESS;
}
```
Y los includes del header en shared/src/utils.h
```
#include<stdio.h>
#include<stdlib.h>
#include<sys/socket.h>
#include<unistd.h>
#include<netdb.h>
#include<commons/log.h>
#include<commons/collections/list.h>
#include<string.h>
#include<assert.h>
```
La implementación de la función en shared/src/utils.c
```
int iniciar_servidor(void)
{
	int socket_servidor;
	struct addrinfo hints, *servinfo, *p;

	memset(&hints, 0, sizeof(hints)); // <----- FALLA ACÁ
	hints.ai_family = AF_UNSPEC;
	hints.ai_socktype = SOCK_STREAM;
	hints.ai_flags = AI_PASSIVE;

	//TODO REFACTORIZAR PUERTO PARA QUE SALGA DE UN ARCHIVO
	getaddrinfo(NULL, PUERTO, &hints, &servinfo);

	// Creamos el socket de escucha del servidor
	socket_servidor = socket(
			servinfo->ai_family,
			servinfo->ai_socktype,
			servinfo-> ai_protocol);

	// Asociamos el socket a un puerto
	bind(socket_servidor,servinfo->ai_addr,servinfo->ai_addrlen);

	// Escuchamos las conexiones entrantes
	listen(socket_servidor,SOMAXCONN);

	freeaddrinfo(servinfo);
	log_trace(logger, "Listo para escuchar a mi cliente");

	return socket_servidor;
}
```

Al Correr el código nos loguea lo siguiente
> !!!Hello World!!!
[INFO] 18:13:19:723 TP0/(2417:2417): test de log
[0m

Nunca llega al log que hacemos luego de iniciar el servidor.
Al debuguear nos daba el siguiente error en la linea del memset
>Can't find a source file at "./string/../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S"

Desde que movimos la linea del puts (en el main) arriba de todo, empezó a dar el siguiente error:
>Can't find a source file at "./string/../sysdeps/x86_64/multiarch/strlen-avx2.S" 

Entendemos que algunas dependencias se deben estar leyendo bien al compilar pero tal vez mal al correr, pero no sabemos que nos falta linkear. 
Ya agregamos al run configurations el parametro LD_LIBRARY_PATH
>LD_LIBRARY_PATH=${workspace_loc}/tp-2023-1c-Don-Satur/shared/Debug

Para sumar al contexto, tenemos una carpeta con 6 proyectos. Los 5 módulos y el proyecto shared
En el caso en cuestión queremos linkear el proyecto cpu con el proyecto shared

- shared se creó como Shared Library y dentro de sus Linker -> Libraries tiene las Commons
- shared tiene seteado el flag -fPIC
- cpu es un proyecto executable y dentro de sus Linker -> Libraries tiene las shared y las commons. 
- cpu tiene como library search path (-L) tiene el directorio {workspace}/shared/Debug
- cpu tiene como incudes el {workspace}/shared/src

Desde ya muchas gracias y si necesitan que escribamos algo más al hilo lo agregamos

**Comment by RaniAgus** [comment]
¡Buenas!

Si fuera un problema al linkear la biblioteca, debería arrojar error inmediatamente al compilar o al ejecutar, no debería pasar que arranque ejecutando y luego tire error.

Segundo, el "error" de `Can't find source file at` es un problema tan común que tiene su propia sección en la [guía de debug](https://docs.utnso.com.ar/guias/herramientas/debugger#can-t-find-source-file-at-el-error-que-no-es).

Por último, les recomiendo validar los valores de retorno de `getaddrinfo()`, `bind()`, `listen()`, `socket()`, `connect()`, `send()`, `recv()`, etc, ya que podemos estar perdiendo información sobre en qué momento el programa falla. 

Para revisar cuál es el valor de retorno que deben chequear según cada función consultando el [manual online](https://man7.org/linux/man-pages/) o abriendo una consola y ejecutando `man nombre_de_funcion`. Ejemplos:

#### `getaddrinfo()`

![image](https://user-images.githubusercontent.com/39303639/229563535-4989e9be-1d81-4295-93d4-cb9ac3b6059d.png)
![image](https://user-images.githubusercontent.com/39303639/229563605-ab90c7c9-42c7-45d8-8b4d-59341da70f1b.png)

```c
int resultado_getaddrinfo = getaddrinfo(...);
if (resultado_getaddrinfo < 0) {
    fprintf(stderr, "Error en getaddrinfo: %s\n", gai_strerror(resultado_getaddrinfo));
    exit(-1);
}
```

#### `socket()`

![image](https://user-images.githubusercontent.com/39303639/229563716-b96bede3-7474-4f74-9798-c4e7b04778ca.png)

Y luego vamos a la página de `errno` y vemos que...

![image](https://user-images.githubusercontent.com/39303639/229564890-b587911b-9b1c-4deb-a5a2-3b53d7a5d88c.png)

```c
socket_servidor = socket(...);
if (socket == -1) {
    perror("Error en socket");
    exit(-1);
}
```


Saludos

**Comment by MiltonMartorello** [comment]
Pudimos resolverlo sin entender muy bien como. Solo le pase el .project y .cproject a mis compañeros y dimos de vuelta la página.

Con respecto a los demás consejos muchas gracias @RaniAgus , no lo veníamos contemplando y descubrimos algunos números negativos al crear conexiones 😄
