### ISSUE TITLE
Warnings molestos manejando hilos

### ISSUE THREAD

**Issue by MiltonMartorello** [sisoputnfrba/foro#2909]
Holis. Con el equipo queríamos ir adelantando con algunas tareas así que nos vimos la guía de hilos para ver si podíamos paralelizar algunas tareas de servidor y nos topamos con algo molesto.

### 🐛 Problema
El compilador todo el tiempo nos pone warnings. A veces se van a veces vuelven y no entendemos bien por qué. Más que nada queríamos saber si le estamos chingando al código o es Eclipse que se mambea de alguna manera.

-------------------------------------

```
pthread_t * thread_servidor;
socket_kernel = pthread_create(&thread_servidor, NULL, esperar_cliente_hilo,  (void *) &socket_file_system);
```
### 💻 Warning Eclipse pthread
> passing argument 1 of ‘pthread_create’ from incompatible pointer type [-Wincompatible-pointer-types]
-------------------------------------

`int cod = pthread_join(thread_servidor, NULL);`

### 💻 Warning Eclipse pthread_join
> passing argument 1 of ‘pthread_join’ makes integer from pointer without a cast [-Wint-conversion]

-------------------------------------

`return (void*) socket_kernel;`
### 💻 Warning Eclipse esperar_cliente_hilo
>cast to pointer from integer of different size [-Wint-to-pointer-cast]

-------------------------------------

### 🔎 Búsqueda en foros
Según el Man el pthread devuelve un 0 en caso de éxito y en caso de error, el número de error.
Esto matchea con el video que define la firma tanto de pthread_create y pthread_join como int.
Es por esto que nos llama la atención que aveces nos pida castear a int

Muchas gracias!

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va?

Fíjense que un par de errores dicen `passing argument 1 of ...`, o sea, el tipo que no le está convenciendo del todo al compilador es del primer parámetro que se pasa, no el que se recibe. Entonces:

1. En la firma de [`pthread_create`](https://man7.org/linux/man-pages/man3/pthread_create.3.html), el primer parámetro debe ser un `pthread_t *` (o sea, un puntero a `pthread_t`) y en el ejemplo están pasando un `pthread_t **` (o sea, un puntero a **un puntero a** `pthread_t`).

Por si sirve de ayuda, el operador `&` se puede leer como "la dirección de memoria en donde se encuentra la variable", o sea, en este caso un ejemplo correcto sería:

```c
pthread_t thread_servidor; // reservo memoria en el stack
pthread_create(&thread_servidor, ...); // le paso un puntero al stack
```

o sino:

```c
pthread_t *thread_servidor = malloc(sizeof *thread_servidor); // reservo memoria en el heap
pthread_create(thread_servidor, ...); // le paso el mismo puntero al heap
```

2. En la firma de [`pthread_join`](https://man7.org/linux/man-pages/man3/pthread_join.3.html), el primer parámetro es directamente el `pthread_t`, pueden:

Pasar directamente un `pthread_t` del stack:

```c
pthread_t thread_servidor; // reservo memoria en el stack

pthread_join(thread_servidor, ...); // paso directamente el valor
```

O desreferenciar el puntero al heap con `*`:

```c
pthread_t *thread_servidor = malloc(sizeof *thread_servidor); // reservo memoria en el heap

pthread_join(*thread_servidor, ...); // paso el contenido apuntado por el puntero como valor
```

<hr>

Por otro lado, sobre `cast to pointer from integer of different size`:

3. Este warning dice que la función espera devolver un `void*` (un puntero que, al estar en una VM de 64 bits, mide 8 bytes) y en su lugar ustedes están pasando un `int` (que mide 4 bytes). 

También, como se menciona [acá](https://stackoverflow.com/a/61915170/14089741), esta conversión no está definida y depende de la implementación de gcc, por lo que se la considera como insegura.

Creo que pueden castear a [`intptr_t`](https://stackoverflow.com/a/6326362/14089741), que la definición es como "un entero del tamaño de un puntero", o sea que:
- En máquinas de 64 bits, mide lo mismo que un `int64_t`
- En máquinas de 32 bits, mide lo mismo que un `int32_t`
- ...etc

```c
return (intptr_t) socket_kernel;
```

Lo bueno es que al castear de un tipo de dato más chico a uno más grande, no deberían preocuparse por perder información 😄 

Saludos

**Comment by MiltonMartorello** [comment]
Clarísimo todo, muchas gracias @RaniAgus
