### ISSUE TITLE
Error al intentar usar funciones como fgets o readline

### ISSUE THREAD

**Issue by mcotens** [sisoputnfrba/foro#2911]
Buenas, al intentar leer el archivo de pseudocódigo con fgets o readline, el programa termina con -1. Al debuggear sale el siguiente mensaje:
`Can't find a source file at "./libio/./libio/iofgets.c" 
Locate the file or edit the source lookup path to include its location.`
Y además, el Thread figura como suspendido por:
`Thread #1 [consola] 2660 [core: 0] (Suspended : Signal : SIGSEGV:Segmentation fault)`
Por lo que, lo relaciono con el post #469 .
Sin embargo, no entiendo dónde estaría el error.

Mi código es el siguiente:
`char texto[150];
    while(fgets(texto, 150, archivo_pseudocodigo)){
    	printf("Leido: %s", texto);
    }
`
Nunca llega a imprimir ninguna línea por consola.
Gracias.

**Comment by LeandroCarbajales** [comment]
Buenas!
El error que te tira al debuggear lo más probable es que se deba a que estén haciendo "step into" sobre funciones que no tienen el código fuente disponible, sino que las importan ya compiladas, como por ejemplo, `fgets`, `readline`, `malloc`, las de pthread, las de sockets, las de strings, las commons, etc. Para las cuales, al debuggear deberían usar "step over" para ejecutar esa línea pero sin entrar al código de la misma, o una vez que les sale ese error pueden usar "step return" para seguir de donde estaban. Esto mismo está explicado en la [guía de debugging](https://docs.utnso.com.ar/guias/herramientas/debugger#can-t-find-source-file-at-el-error-que-no-es) y es un poco lo que hablaban en el issue que linkeaste.

Mi recomendación sería que lo puedan debuggear evitando ese "error que no es error" para estar seguros de dónde y por qué es que falla el programa al ejecutarlo normalmente.

**Comment by mcotens** [comment]
Perfecto, problema solucionado. Gracias!

**Comment by emfer** [comment]
Buenas como estan?
Consulta, recien ahora me empezo a pasar lo mismo mientras debuggeaba y me tira el siguiente error: Can't find a source file at "./string/../sysdeps/x86_64/multiarch/strlen-avx2.S" 
Locate the file or edit the source lookup path to include its location.
El problema es que esta pasando en la mayoria de las funciones log info y no me permite  seguir el orden del programa. Cuando toco step return como dice la guia, igualmente me termina el debug y sale del modo. Por lo cual no puedo "saltearlo" por asi decirlo.
Alguna idea de como podria solucionar esto?
