### ISSUE TITLE
Problema al compilar client.c

### ISSUE THREAD

**Issue by ffaiella** [sisoputnfrba/foro#2912]
Hola buenos dias!! Al comento de intentar compilar client.c me aparecen tres errores(Adjunto las imagenes abajo)
![image](https://user-images.githubusercontent.com/129689847/231205827-611b32ed-215f-45b7-b5d8-cf1a8cb44045.png)
Linea en la que se produce el primer error:
![image](https://user-images.githubusercontent.com/129689847/231206030-f093ac00-e66e-4588-8801-fbcbc170c214.png)
Linea en la que se produce el segundo error:
![image](https://user-images.githubusercontent.com/129689847/231206368-8fdfcaca-fa3b-4fc2-abea-99781d336a58.png)

Esto me ocurrio luego de realizar algunas cosas de la primera parte del TP0, pensé que los errores se podrían producir por algunas de mis modificaciones, al no detectar nada elimine los cambios realizados y volví a compilar, se generaron los mismos errores. 
Elimine el repositorio descargado, volví a descargar, y siguen apareciendo los mismo errores. Saben a qué se pueden deber estos errores? Las commons ya estas descargadas e instaladas

**Comment by ffaiella** [comment]
Me acabo de dar cuenta que dentro de la carpeta include no tengo la carpeta readline, este archivo se tuvo que cargar en ese directorio al instalar los commons?

**Comment by ffaiella** [comment]
Tampoco se encuentra readline.h en el repositorio descargado

**Comment by iago64** [comment]
Buenas!
Veo que el problema fue resuelto, en ese caso no te olvides de cerrar el issue.

Por otra parte, te consulto, estas usando las VMs de la cátedra o estas usando tu instalación nativa de linux? Porque en las VMs readline.
En caso de que estes utilizando una instalación propia de linux, te recomiendo que revises los [paquetes que están instalados](https://github.com/sisoputnfrba/entorno-vms/blob/main/base-server.sh) para que no te falte nada a futuro

Saludos.-

**Comment by ffaiella** [comment]
Si, el problema esta resuelto. No estoy utilizando la VMs de la catedra, tengo una máquina que tiene instalado Ubuntu 18.04 y la estoy utilizando. Ok, ya los reviso, gracias!
