### ISSUE TITLE
No nos encuentra algunos subprogramas de la shared library y otros si

### ISSUE THREAD

**Issue by LucianoFoglia** [sisoputnfrba/foro#2915]
Buenas, que tal? Ya configuramos Cuando queremos iniciar el servidor, al utilizar funciones de la carpeta shared, nos dice que algunas no estan definidas. La shared library esta configurada y la probamos con subprogramas basicos creados por nosotros y funcionaba.
Por ejemplo, iniciar_servidor funciona pero al agregar esperar_cliente al main, no compila.
### 🔎 Búsqueda en foros

Vimos algunos issues similares a nuestro problema pero no nos sirvio. En el issue #2650 a ellos no les toma ningun subprograma y a nosotros nos toma algunas si y otras no.

### 📝 Código relevante

```
Building target: kernel
Invoking: GCC C Linker
gcc -L"/home/utnso/Documents/tp-2023-1c-aLaGrandeLePuseCuca/shared/Debug" -o "kernel" ./src/kernel.o    -lcommons -lshared
/usr/bin/ld: ./src/kernel.o: in function main':
/home/utnso/Documents/tp-2023-1c-aLaGrandeLePuseCuca/kernel/Debug/../src/kernel.c:8: undefined reference to esperar_cliente'
collect2: error: ld returned 1 exit status
make: *** [makefile:43: kernel] Error 1
"make all" terminated with exit code 2. Build might be incomplete.
```

@juanibencardino @Plata92 @Nicolucena @corona6054

**Comment by iago64** [comment]
Buenas! Cómo va?

Les dejo un par de preguntas como para saber por donde arrancar
¿Siguieron el [tutorial de las shared que está en docs.utnso.com.ar](https://docs.utnso.com.ar/guias/programacion/shared-libraries)? 
¿Recompilan las shared después de agregar las funciones?

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @LucianoFoglia! ¿Pudieron revisar lo que les comentó Dami? Saludos

**Comment by LucianoFoglia** [comment]
Buenas, si seguimos lo del video y recompilabamos las shared despues de agregar funciones. Al final le terminamos preguntando a un ayudante el sabado pasado en la charla, perdon nos olvidamos de cerrar el issue. El problema era que estaban mal importadas las bibliotecas en los headers. Muchas gracias por la ayuda.
