### ISSUE TITLE
Problema de VM 

### ISSUE THREAD

**Issue by lewislee0920** [sisoputnfrba/foro#2916]
Buenas, cuando ejecuto el vm no se ejecuta y se queda como la imagen de abajo

![image](https://user-images.githubusercontent.com/62365146/232229422-ba8483fc-d2e6-45d9-92af-6e9957f23834.png)

**Comment by lewislee0920** [comment]
Buenas, estoy usando oracle VM virtualbox 7.0.6. 
Funcionaba el vm antes pero de nada me sale ese pantalla negra y no me deja entrar.
Voy dejando fotos de la configuracion:

![image](https://user-images.githubusercontent.com/62365146/232535423-c8787ebc-499f-4996-8705-a9a6ad1d8d64.png)
![image](https://user-images.githubusercontent.com/62365146/232535625-2018a4c5-e0b4-4946-9e42-1c7a84e655b9.png)
![image](https://user-images.githubusercontent.com/62365146/232535729-c66f8b3a-4da8-4f71-a937-8b0f8068d398.png)
![image](https://user-images.githubusercontent.com/62365146/232535793-211a79ed-6b02-4a94-8f48-a312562ee4e5.png)

**Comment by iago64** [comment]
Buenas!

Un par de observaciones:

1.- Es posible que estes usando la vm de "lubuntu"? Esas vms son de 32 bits y ya se deprecaron como vms oficiales, podes seguir usandolas, pero te recomiendo que bajes las nuevas desde la página de [docs.utnso.com.ar](https://docs.utnso.com.ar/recursos/vms#xubuntu), que no tengas ninguna sorpresa a la hora de probar el tp en el labo ya que se hace con las nuevas vms que son de 64bits (y si calculas mal el tamaño de los punteros puede explotar todo por los aires).

2.- La memoria de video está muy baja, en la 3er captura dice que tiene 16mb, te recomiendo que lo lleves al máximo que te permita, ya que eso puede estar provocando que el driver de video de la VM no levante un entorno gráfico por falta de memoria de video.

3.- En la segunda captura tenes asignados 2gb de ram de 16gb disponibles, si pasas a las nuevas vms, vas a poder asignarles hasta 8gb (que es lo máximo que te habilita virtual box que es el 50% de la ram disponible) y te va a andar mucho más rapido, especialmente si usas eclipse para programar.

Saludos.-

**Comment by lewislee0920** [comment]
Buenas, hiso lo que decia en docs.utnso.com.ar y el vm se ve distinto con los de videos. Esta todo bien? o hay algo que me equivoque?

![image](https://user-images.githubusercontent.com/62365146/232632048-248e47f4-0c60-4960-83e9-4864031031aa.png)

**Comment by RaniAgus** [comment]
¡Buenas! Sí, es esa la nueva VM. No vimos la necesidad de regrabar los videos ya que los pasos a realizar son prácticamente los mismos como se puede ver en la [guía para conseguir un entorno Linux](https://docs.utnso.com.ar/primeros-pasos/entorno-linux).

**Comment by lewislee0920** [comment]
dale, muchas gracias por la ayuda
