### ISSUE TITLE
Problemas de punteros e inicialización de estructuras (SEG FAULT)

### ISSUE THREAD

**Issue by MiltonMartorello** [sisoputnfrba/foro#2917]
Holiwis !!!  Cómo vaaa? Yo mal, porque los punteros no nos dejan tener un buen domingo.
Les comento: Estamos con el reto de serializar el programa para enviarlo al kernel. Veníamos re bien, llevando todo a funciones mas chicas hasta que burbujeamos de vuelta hasta el main y nos explotó todo, dando SEG FAULT. 

### 📝 main
```
t_programa* programa = parsear_programa(archivo_programa, logger);
printf("Size del programa fuera de parsear_programa %d\n" ,programa->size); // 🐛 ESTE PRINTF DA UN SEGMENTATION FAULT
```

### 📝 en algun momento parsear_programa llama a crear_programa y le pasa por parámetro una t_list* creado con list_create
```
t_programa* crear_programa(t_list* instrucciones){
	t_programa* programa = malloc(sizeof(t_programa));
	programa->size = 0;
	programa->instrucciones = instrucciones;
	printf("Size del programa %d\n" ,programa->size); // 🆗  ESTO LEE EL SIZE Y LO IMPRIME
	return programa;
}
```

### 📝 finalizando la funcion parsear_programa a 2 instrucciones de volar por los aires
```
printf("Size del programa %d\n" ,programa->size); // 🆗 ESTO LEE EL SIZE Y LO IMPRIME
return programa;
```

### 📝 Estructura utilizada
```
typedef struct {
	int size;
	t_list* instrucciones;
} t_programa;
```

### 💻 Logs
Al debuggear y evaluar la estructura programa desde el main, nos dice lo siguiente:

```
Failed to execute MI command:
-data-evaluate-expression (programa)->size
Error message from debugger back end:
Cannot access memory at address 0x5555b860
```

Lo cual es muy cómico porque una función un nivel mas adentro, una instrucción antes(hablando de momentos)
decía lo siguiente:

```
Name : size
	Details:0
	Default:0
	Decimal:0
	Hex:0x0
	Binary:0
	Octal:0
```

Cómo que se nos desconocieron los programas, es como si hubieramos perdido la referencia del programa. Puede ser que tengamos que inicializar con program_create en el main y luego pasarlo por parámetro hacia abajo en las sub-funciones? No hicimos esta prueba porque en el TP0 se crea desde adentro y luego se pasa hacia arriba como es el caso de t_buffer y funciona. Pero ya nos bloqueamos y neceistamos una manita.

Muchas gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Creo que es un hermoso momento para que les presentemos la herramienta que les va a cambiar la vida y que les va a llenar de alegría el alma y el corazón, así que, sin más preámbulos, les presento [valgrind](https://docs.utnso.com.ar/guias/herramientas/valgrind).

Por favor corran de nuevo su programa con valgrind y revisen los logs, con esa herramienta van a poder ver un poco mejor como es la cadena y donde están perdiendo la referencia, la guía es un poco extensa, pero si le prestan atención, no van a tener un solo putero que les complique la existencia.

Por favor si no entienden algo de lo que les devuelve valgrind, nos pueden subir en un archivo .txt el output de valgrind y lo analizamos en conjunto 😄 

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @MiltonMartorello! ¿Pudieron correr el programa con Valgrind como les comentó Dami? Saludos

**Comment by MiltonMartorello** [comment]
Hola, luego de mucha lucha se pudo correr valgrind e ir luchando con los distintos problemas que nos fue arrojando, si nos trabamos con algo consultamos mañana en el soporte. Muchas gracias!
