### ISSUE TITLE
Consulta fin TP0: recibir paquete en servidor y cerrar conexión

### ISSUE THREAD

**Issue by sandreu95** [sisoputnfrba/foro#2919]
Hola, buenas noches, como va?
Estoy teniendo un inconveniente con la resolución final del TP0: llego a enviar el paquete y que el servidor lo reciba con éxito (en consola me informa que recibió bien el paquete), pero al momento de querer cerrar la conexión, por alguna razón, la función recibir_operacion retorna -1 con lo cual, por como esta armado server.c, se loguea el error 
[ERROR] 02:06:23:595 Servidor/(5964:5964): el cliente se desconecto. Terminando servidor
¿Cuál podría ser la razón por la cual la función de arriba reciba -1?
Por otro lado, el ultimo string del paquete pareciera quedar con strings basura (en consola se muestran cuando llegan al servidor, cual podría ser la razón? Adjunto imagen de ambos errores:

![imagen_2023-04-17_000435638](https://user-images.githubusercontent.com/129904699/232368143-3986b8b3-ace4-4aec-8cdd-9891620a1010.png)
?

### 📔 Citas del enunciado/videos
Parte 3 del tp0. Items:
- Ir juntando las líneas que se leen por consola para luego enviarlas como paquete.
- Cerrar la conexión.

**Comment by iago64** [comment]
Buenas! Cómo va?

Justamente que reciban 0 es la señal de que se desconectó el proceso como se indica en el [man de recv](https://linux.die.net/man/3/recv), algo importante es que revisen un poco más las funciones del tp0 y ahi vas a ver que en realidad `recv()` no es el que devuelve -1, sino que es la propia `recibir_operacion()` la que te devuelve el -1:

```c
int recibir_operacion(int socket_cliente)
{
	int cod_op;
	if(recv(socket_cliente, &cod_op, sizeof(int), MSG_WAITALL) > 0)
		return cod_op;
	else
	{
		close(socket_cliente);
		return -1;
	}
}
```

Respecto a la basura que están recibiendo, es posible que no estén pasándole correctamente el size de lo que mandan / reciben o que estén omitiendo agregar el `'\0'` en su string entonces eso hace que las funciones de strings no sepan donde cortar y sigan recorriendo la memoria hasta encontrar ese famoso `'\0'` que las corta.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @sandreu95! ¿Pudieron revisar lo que les comentó Dami? Saludos

**Comment by sandreu95** [comment]
Buenas tardes! Si, lo pudimos resolver, ambas preguntas. Se entendió la devolución de la función recibir_operacion(). Respecto a los caracteres, efectivamente, estábamos enviando mal el tamaño del string del paquete. Ya lo corregimos y dejo de devolvernos basura
Muchas gracias!!

**Comment by RaniAgus** [comment]
¡Buenísimo! Una vez resuelta la duda o consulta ya pueden cerrar el issue :)
