### ISSUE TITLE
Cambios de grupo

### ISSUE THREAD

**Issue by RaniAgus** [sisoputnfrba/foro#2920]
¡Buenas!

Habiendo cerrado la inscripción de grupos, damos paso al inicio de los cambios de grupo. 

En este thread van a poder buscar integrantes para completar su grupo, o grupo en caso de haberse quedado solos. Tengan en cuenta que los cambios no son para andar probando suerte, si no para unificar a aquellos grupos que sufrieron bajas.

Por favor, traten de **NO publicar números de celular**, ya que el foro es público y cualquier persona incluso fuera de la UTN FRBA puede llegar a ver su número.

Como siempre, cualquier inconveniente con los cambios de grupos envíen un mail a inscripciones@utnso.com.ar

Saludos.-

**Comment by TamirFeldenblum** [comment]
Buenas noches, un compañero de nuestro grupo se bajó. Estamos buscando alguien que quiera sumarse.
Saludos, Tamir Feldenblum.

**Comment by daltplusplus** [comment]
Buenas! Andamos buscando 2 integrantes para nuestro grupo. Mandenme un mail a dlopeztapia@frba.utn.edu.ar si les interesa

**Comment by ArgonzMatias** [comment]
Buenas, estamos buscando 1 integrante para nuestro grupo. Se pueden comunicar a margonz@frba.utn.edu.ar si les interesa.

**Comment by TamirFeldenblum** [comment]
Estimados,

Me dirijo a ustedes para invitarlos a formar parte del grupo, ya que se nos bajó un compañero.

Si están interesados en unirse pueden escribirme a tfeldenblum@frba.utn.edu.ar

Saludos, Tamir.

**Comment by Fcallero** [comment]
Hola buenas, estaríamos buscando a 2 integrantes nuevos para nuestro grupo.
Los que necesiten y les interese pueden mandarme un mail a mi a fcallero@frba.utn.edu.ar.

**Comment by LucasThier** [comment]
Hola buenas, estamos buscando un integrante para nuestro grupo ya que un compañero abandono la materia. Ya estamos desarrollando la parte de hilos, si a alguno le interesa pueden mandarme un mail a lthier@utn.frba.edu.ar

**Comment by JCNeira14** [comment]
Buenaas, estamos buscando 2 personas para nuestro grupo porque los integrantes que estaban se dieron de baja de la materia. Los 3 que quedamos le estamos poniendo onda al tp para seguir llevandolo pero nos vendria bien encontrar 2 personas mas. Si a alguno le interesa sumarse, mandenme un mail a jneira@frba.utn.edu.ar

**Comment by dcoccaro** [comment]
Buenas, como va?
Queria saber si a alguien le falta uno en el grupo, ya que el mio abandonó la materia. Estoy haciendo el TP solo me falta conectar con los hilos los procesos, pero se hace cuesta arriba solo. Mi mail es dcoccaro@frba.utn.edu.ar. No quiero perder la materia por personas que no se comprometen con la causa.

**Comment by ParedesMicaela** [comment]
Buenas! Buscamos a alguna persona que quiera sumarse a nuestro equipo. Somos 4, estamos terminando el checkpoint 2 y empezado a adelantar un poco el checkpoint 3, cualquier cosa manden mensajito a mi mail miparedes@frba.utn.edu.ar   <3

**Comment by cserrudo** [comment]
Buenas, buscamos a una persona responsable que quiera sumarse a nuestro grupo, estamos avanzando con el checkpoint 2 y dentro de poco nos vamos a dividir cada módulo restante. Si están interesados, mí mail es: cserrudo@frba.utn.edu.ar

**Comment by gdrusetich** [comment]
Buen día Coccaro.
Espero que ya hayas conseguido grupo.
De lo contrario, en mi equipo hay 3 que están trabajando bastante, y uno
que más o menos. Pero estamos buscando un 5to integrante.
Cualquier cosa, el equipo muchachOS te espera!
Un saludo!


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by adrianquispe** [comment]
buenas, se nos bajo 1, si alguien le falta grupo o se desarmo su grupo tenemos 1 cupo, mp a adrianquispe@frma.utn.edu.ar

**Comment by GabrielNicolasLopez** [comment]
Buenas! Buscamos a 1 integrante que quiera sumarse a nuestro equipo. Somos 4 recursantes, todos los módulos van al día con respecto a los checkpoints excepto CPU que es justamente donde necesitamos ayuda. Si están interesados en unirse me pueden enviarme un mail a: glpez@frba.utn.edu.ar

**Comment by RodrigoGutson** [comment]
Buenas! Con mi grupo estamos en búsqueda de UN INTEGRANTE. Con el TP nos encontramos al día hasta el checkpoint 2 y avanzando con el checkpoint 3. Venimos avanzando bastante bien con los módulos de kernel y cpu y, para memoria ya tenemos designado los responsables a hacerlo. Estamos buscando a alguien que preferentemente conozca de filesystem y pueda aportar con esa parte, sumado obviamente a disponibilidad de tiempo y la buena predisposición por aprobar el TP.  
Cualquier interesado enviarme un mail: rgutson@frba.utn.edu.ar

**Comment by Tomai15** [comment]
Buenas, con mi grupo andamos buscando un integrante, ya que hace un par de días dejo la materia uno de nuestros compañeros. No importa en que modulo tenga conocimiento, cualquiera ayuda viene bien. Dejo mi mail: tdelgadoandrade@frba.utn.edu.ar

**Comment by MiltonMartorello** [comment]
Holis. El grupo Don Satur anda buscando integrantes que quieran subirse a la Don-Saturneta:

**Actualmente el cupo es de 2**:
RIP member 1: 15/04 12:15 - 12:16
RIP member 2: 15/04 - 23/05


## Que buscamos y qué no buscamos
✅ Preferentemente gente de los Miércoles a la Noche
✅ Gente con voluntá!
✅ En lo posible que sean autosuficientes y que puedan tomar un tema, investigarlo, Animarse!
✅ Levantar la mano si se traban o necesitan ayuda y no esperar a la frustración.
✅ Que se haya enfrentado a los obstáculos que tiene el TP

💀 No hacemos Shadowing: 1 Programa y 4 miran no nos sirve. (emoji de pala)
💀 No hacemos Pair Programming: No solemos manejar los mismos horarios, nos reunimos para intercambiar ideas o hacer pruebas de integración solamente.

## Que usamos:

### 💻  Eclipse! Si, lo dije, pero es handy para debuggear.

### 🔢   Trello 😄 
Asi vas a saber siempre que tomar (ticket, refactor, valium 5mg, etc)
![image](https://github.com/sisoputnfrba/foro/assets/49041770/4709c02f-d9e9-4279-9279-9f6c1840d992)

### Diagramitas con colorcitos 📊 
Para saber hacia donde vamos y todos estar alinead@s
![image](https://github.com/sisoputnfrba/foro/assets/49041770/c8e72f3e-c6b3-4aeb-ae64-5aea481ad2c3)

### Salbutamol 100mcg
Para cuando el proyecto deja de compilar

### Status actual del TP:
Checkpoint 2 OK
Checkpoint 3 Pendientes:
- SIGNAL, WAIT, I/O en CPU y KERNEL.
- Manejo de Recursos y procesos bloqueados
- Uso de Makefiles


Subite a la DonSaturneta
Ref: mmartorello@frba.utn.edu.ar

**Comment by PabloSorrentino** [comment]
Buenas, andamos buscando un 5° integrante porque uno se bajo justo ahora. Cualquier cosa me @.

**Comment by PabloSorrentino** [comment]
Buenas, buscamos un 5° integrante ya que tuvimos una baja reciente en el grupo, por favor la persona interesada @. Salu2

**Comment by joacobruno** [comment]
Buenas, se nos bajo un integrante del equipo. Al que quiera sumarse me manda un mail joabruno@frba.utn.edu.ar

**Comment by iago64** [comment]
Buenas! Cómo va?

Mala mía, asumí que se entendía porque el issue está cerrado, pero los cambios de grupo cerraron el día 03/06, como se anunció en el post https://www.utnso.com.ar/1c2023-ppts-sabados-de-soporte-y-cambios-de-grupo/

Saludos.-
