### ISSUE TITLE
Error al recuperar Config

### ISSUE THREAD

**Issue by Danymmereles** [sisoputnfrba/foro#2921]
Buenas noches,

Estamos teniendo un tema al recuperar los configs. Elegimos hacer el proyecto con el template de @RaniAgus y corre bien pero estamos teniendo un pequeño temilla con la ruta de config. Cada tanto, al hacer make y una corrida del ejecutable por alguna nueva implementación, estamos obligados a cambiar la ruta del config.

O sea:
```
configKernel = config_create("../consola.config");

En la consola:
cd /home/utnso/tp-2023-1c-Default-2.0/ConsolaT/
make
```

Ahi va todo ok pero no recupera la configuracion por lo tanto vamos y cambiamos a :

```
configKernel = config_create("../ConsolaT/consola.config");
```

Ahi el make lo hace correctamente y los datos del config tambien. Pero cuando volvemos a hacerlo, pasa lo mismo y tenemos que volver a cambiarlo a:

```
configKernel = config_create("../consola.config");
```

Y asi es un bucle infinito. Sabrian que puede estar pasando y/o como arreglarlo por casualidad?? No es que pasa siempre, pero pasa mas seguido de lo que nos gustaria y deberia ser.

Desde ya muchisimas gracias 

Pd: vi otros issues pero no encontre algo asi

**Comment by LeandroCarbajales** [comment]
Buenas! Lo primero que se me ocurre que puede estar pasando, es que al compilar y correr desde la terminal, tanto el archivo de config como el ejecutable estarían en la carpeta "ConsolaT", por lo que su ruta relativa "../consola.config" fallaría ya que estaría buscando el archivo un directorio arriba del esperado. En cambio, cuando lo corren desde Visual Studio, lo más probable es que se esté ejecutando desde "src" o "debug" por lo que sí funcionaría esa ruta relativa.

Mi recomendación es que chequeen si existe esa diferencia de rutas (si cambia desde dónde se ejecuta) y luego, si es necesario pueden simplemente copiar el archivo de config a ambas rutas y que la ruta que le pasan al config create sea el directorio actual ("consola.config")

**Comment by Danymmereles** [comment]
El tema es que las dos corridas fueron por consola, no utilice un método distinto para poder ejecutarlo.

Sinceramente estoy perdidisima. Encima no es que pueda forzar el error, igual ahi intento con esa solución. 

La duda es donde lo dejaría? Actualmente esta distribuido de la siguiente forma:

```
ConsolaT
  |-> src
      |-> consola.c
      |-> consola.h
  |-> bin
      |-> ConsolaT.out
  |-> obj
  |-> consola.config
```

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va?

En el caso de que haya sido siempre por consola, me re suena a que estén haciendo a veces:

```
cd bin
./ConsolaT.out
```

Y a veces:
```
./bin/ConsolaT.out
```

Entonces en base a eso la ruta relativa al directorio actual (o cwd) de la consola cambia.

La idea es ejecutarlo de la segunda forma y no de la primera, ya que las configs para Eclipse y VSCode hacen lo mismo.

Saludos :)

**Comment by Danymmereles** [comment]
Okas okas perfecto, entonces lo dejariamos en 

> configKernel = config_create("../consola.config");

y lo correriamos con

> ./bin/ConsolaT.out

Asi no?

**Comment by RaniAgus** [comment]
Asumiendo que el config lo dejan en la carpeta `ConsolaT` como más arriba y ejecutan el binario desde ahí mismo (`./bin/ConsolaT.out`), la ruta sería solo "consola.config"

**Comment by Danymmereles** [comment]
Okas okas, muchisimas gracias a ambos @RaniAgus @LeandroCarbajales 

Cualquier cosa reabro el issue.
