### ISSUE TITLE
Duda en Planificación, en la solicitud de segmentos

### ISSUE THREAD

**Issue by ezequielmalfonso** [sisoputnfrba/foro#2922]
Buenas noches, tengo una duda del enunciado, estoy empezando con la planificación en el Kernel en el siguiente párrafo:.
>Planificador de Largo Plazo
Al conectarse una Consola al Kernel, deberá generarse la estructura PCB detallada anteriormente y asignarse este proceso al estado NEW.
En caso de que el grado máximo de multiprogramación lo permita, los procesos pasarán al estado READY, enviando un mensaje al módulo Memoria para que inicialice sus estructuras necesarias y obtenga la tabla de segmentos inicial que deberá ser almacenada en el PCB. La salida de NEW será mediante el algoritmo FIFO.
Cuando se reciba un mensaje de CPU con motivo de finalizar el proceso, se deberá pasar al mismo al estado EXIT, liberar todos los recursos que tenga asignados y dar aviso al módulo Memoria para que éste libere sus estructuras. Una vez hecho esto, se dará aviso a la Consola de la finalización del proceso.

Cuando dice "_**enviando un mensaje al módulo Memoria para que inicialice sus estructuras necesarias y obtenga la tabla de segmentos inicial que deberá ser almacenada en el PCB.**_"
En este caso entiendo que desde el Kernel le envió un mensaje a Memoria para que haga la inicialización, y lo que me devuelve la memoria es el segmento 0 ?
Porque entiendo que la memoria va ir creando segmentos cuando el CPU lo solicite a medida que ejecute los CREATE_SEGMENT.
Este segmento 0, que no termino de visualizar si es una lista de struct o un array, no me queda claro  que debo devolverle al Kernel desde la memoria?
Puede ser que la lista de segmentos la implemente como un array y en cada posición del mismo tenga el tamaño de cada segmento?
Y el  el segmento 0 como lo representaría?

Cuando inicio la planificación en este caso estoy con FIFO, cuando pasa a EXEC, le envio el proceso al CPU para que lo ejecute y en 
>CREATE_SEGMENT (Id del Segmento, Tamaño): Esta instrucción solicita al kernel la creación del segmento con el Id y tamaño indicado por parámetro.

Cuando dice que solicita al kernel al creación del segmento, el segmento lo crea el kernel o la memoria, no me termina de quedar claro eso?

Muchas gracias.-

**Comment by LeandroCarbajales** [comment]
Buenas! Paso a responder por puntos:

> el Kernel le envió un mensaje a Memoria para que haga la inicialización, y lo que me devuelve la memoria es el segmento 0 ?
Porque entiendo que la memoria va ir creando segmentos cuando el CPU lo solicite a medida que ejecute los CREATE_SEGMENT.

A efectos de implementación del trabajo, podrías esperar solamente el segmento 0 porque ya sabés que todos los procesos solamente arrancan con ese segmento y no estaría mal.
Si quisieras verlo a nivel diseño, esto no escalaría si por ejemplo los procesos ya iniciaran con otros segmentos ya creados (cosa que no va a ocurrir en el trabajo), por lo que si quisieras separar responsabilidades entre los módulos, el Kernel podría esperar que la memoria le devuelva la tabla de segmentos "completa" en su estado inicial, de este modo, sería responsabilidad solamente del módulo Memoria saber cómo se inicializa la tabla de segmentos de cada proceso.
Por lo pronto, hasta que no comiencen con la implementación del manejo de memoria, el módulo Memoria podría simplemente devolver un valor de prueba (mock) para el segmento 0 (les dejo un ejemplo en la respuesta de abajo).

> Este segmento 0, que no termino de visualizar si es una lista de struct o un array, no me queda claro que debo devolverle al Kernel desde la memoria?
Puede ser que la lista de segmentos la implemente como un array y en cada posición del mismo tenga el tamaño de cada segmento?
Y el el segmento 0 como lo representaría?

Como indica en la definición de la tabla de segmentos en el PCB, cada segmento estaría representado en la tabla por un id, su dirección base y su tamaño, por ejemplo {id: 0, base: 0, tamaño: 64}
La tabla de segmentos podría ser simplemente una lista de ese struct. No recomiendo usar un array para representarlo ya que no sabrían su tamaño máximo antes de leer el archivo de config.

> Cuando dice que solicita al kernel al creación del segmento, el segmento lo crea el kernel o la memoria, no me termina de quedar claro eso?

Un poco de ambos :)
Para hacer un paralelo con un proceso real, ese "CREATE_SEGMENT" vendría a representar una syscall (llamada al sistema), en ese sentido el proceso le pide al Kernel que lo haga.
Luego, a efectos de implementación del trabajo, para que puedan desarrollarlo de manera iterativa incremental, la lógica de crear el segmento está dividida entre el módulo Kernel quien hace algunas validaciones previas (esto lo pueden ver en la sección "Manejo de Memoria") y el módulo Memoria es quien implementa la lógica del manejo de memoria en sí (asignación, eliminación y compactación de segmentos).

Saludos!
       Lean

**Comment by ezequielmalfonso** [comment]
Muchas @LeandroCarbajales re claro todo, y te hago una consulta mas para terminar de entender o visualizar, la tabla de segmentos (que es la lista de segmentos cuyo id = 0 voy a considerar que es el segmento 0) donde me conviene tenerla en el kernel a medida que va recibiendo los segmentos creados por la memoria o en la memoria? o estoy muy perdido?

Muchas gracias,
Ezequiel.-

**Comment by LeandroCarbajales** [comment]
La tabla de segmentos de cada proceso la tendrías en su estructura PCB como indica el enunciado :)

**Comment by LeandroCarbajales** [comment]
@ezequielmalfonso Quedó alguna duda sobre esto último?

**Comment by LeandroCarbajales** [comment]
Genial! Normalmente esperamos que cierren el issue cuando la duda está resuelta para saber cuáles aun requieren atención.

>  A esta altura habrá alguna forma para testear si voy bien encaminado?

Por supuesto!
Un test podría ser crearse un script solamente con algunas instrucciones SET intercaladas por algún YIELD y que termine en EXIT para corroborar que pueden correr algunas consolas con esas instrucciones "base".
Los logs mínimos obligatorios que tengan que ver con eso también los puede ayudar a corroborar que funciona adecuadamente.

Saludos!
    Lean

**Comment by LeandroCarbajales** [comment]
Hola @ezequielmalfonso !
Te sirvió la respuesta? Para corroborar los valores de las estructuras que van creando también puede servir correr el Kernel en este caso con el debugger :)

**Comment by LeandroCarbajales** [comment]
Cierro el issue por inactividad, cualquier cosa podés volver a abrir un nuevo issue :)
