### ISSUE TITLE
me tira siempre errores y no se si es que eclipse anda muy mal o si es algo mio

### ISSUE THREAD

**Issue by lucasdeferrari** [sisoputnfrba/foro#2923]
eclipse me tira errores todo el tiempo como 
![image_2023-04-21_213344742](https://user-images.githubusercontent.com/102559642/233752262-624ee803-072c-4bdc-bb26-49ce2fe76faa.png)

no se si es algo mio o que, pero siempre termino teniendo que borrar el repositorio y clonandolo de nuevo, si hago algun cambio o algo me rompe todo, necesito ayuda

**Comment by lucasdeferrari** [comment]
tambien a veces cuando compilo se me borra el .c de la maquina (???) la verdad no entiendo nada

**Comment by iago64** [comment]
Buenas! Cómo va?

Vamos un poco en orden porque estoy viendo el issue y siento que es un desorden como está planteado y dificulta una banda poder darte una guía:

Cuando se crea un issue hay ciertas cosas que están en el template que lo que busca es ayudarnos a ayudarlos:
1.- El error de eclipse es solo lo que dice error, los otros son warnings que en primer lugar vamos a descartarlos, pero en lugar de esa captura, sería un golazo que **copies y pegues el texto** que te da eclipse en la solapa de **console**

2.- La parte de que se eliminan los .c, es rarísimo, estas seguro que no estás haciendo un git checkout en el medio? Estan usando los makefile de eclipse?

3.- Por último, están usando todos eclipse o algunos usan eclipse y otros vscode? Tienen archivos .project y .cproject que no estan en las carpetas correspondientes? Me parece que parte de los warnings que vemos tienen que ver con esto y es en parte lo que hace que tengas tantos problemas.

Saludos.-

**Comment by lucasdeferrari** [comment]
Buenas noches, perdón estaba frustrado y confundido en el momento de escribir el issue. Por suerte pude solucionar los problemas salvo el que a veces se me borra el .c . No estoy haciiendo ningun git checkout en el medio, y usamos los makefile de eclipse. Usamos todos eclipse.  No pasa todo el tiempo, solo a veces cuando compilo. Siento que es medio al azar. Varias veces tambien me deja compilar un proyecto desde la consola pero no desde eclipse. Estoy considerando reinstalar la maquina virtual pero no se si sera la mejor opcion.

**Comment by RaniAgus** [comment]
Buenas, me suena bastante bizarro que les borre un .c, jamás escuché que ocurra algo similar...
¿Nos pasás una captura de cómo se ve la pestaña `Project Explorer` en tu Eclipse? 

Por ejemplo:
![image](https://user-images.githubusercontent.com/39303639/233996017-fe9571b7-d6ad-4810-add5-7a28532263ef.png)

Si no entra en toda la pantalla tratá de cerrar las subcarpetas (`src` y `Debug`) para que podamos ver realmente todos los proyectos que tenés importados en tu workspace (en el ejemplo serían "client" y "server").

Saludos

**Comment by lucasdeferrari** [comment]
Sí, usualmente pasaba cuando habia algun error en el codigo, ahi se borraba el archivo. Aca hay una captura del Project Explorer de Consola
![image](https://user-images.githubusercontent.com/102559642/234084089-56921505-52a2-4df6-a3be-441557f039a5.png)

**Comment by RaniAgus** [comment]
¿Podrías pasarnos **todo** lo que hay en tu `Proyect Explorer`, porfa? A eso me refería con que:

> Si no entra en toda la pantalla tratá de cerrar las subcarpetas (src y Debug) **para que podamos ver realmente todos los proyectos que tenés importados en tu workspace** (en el ejemplo serían "client" y "server").

**Comment by RaniAgus** [comment]
> Nota: el Memoriaa es lo mismo que src, solo que le cambiamos el nombre una vuelta y no se lo volvimos a cambiar

Ojo que ahí veo que la carpeta aparece con el icono de "proyecto" y no de "source code" como las demás carpetas `src`. Probablemente si entran desde el explorador de archivos a esa carpeta `src` y tocan Ctrl+H para ver los archivos ocultos vean varios archivos generados por Eclipse ahí, lo cual no deberia ocurrir.

Es raro... creo que la solución más efectiva va a ser armar los proyectos de nuevo, o sea:
1. quitar todos los proyectos del workspace (click derecho > `Delete`) y cerrar Eclipse
2. ir al repo y borrar todo lo generado por Eclipse que encuentren (puntualmente los archivos `.cproject` y `.project` y las carpetas `.settings`, `.metadata` y `Debug`).
3. abrir de nuevo Eclipse y crear los proyectos desde cero seleccionando cada carpeta y eligiendo la opción "Empty Project" (tranqui, no les va a borrar nada, solo les va a aparecer un warning de que la carpeta existe, y está bien que así sea):

![image](https://user-images.githubusercontent.com/39303639/234329516-e4a8ec92-672c-445e-9bfd-86e529b096d5.png)

4. linkear de nuevo las libs que estén usando (commons, pthread, etc)

![image](https://user-images.githubusercontent.com/39303639/234332351-4c9aca8b-12c5-404d-a46b-c8cfd47fa664.png)

**Comment by lucasdeferrari** [comment]
uh bueno vamos a probar eso, gracias!
