### ISSUE TITLE
No coincide el hash de la Grafica.vdi con la dada y me tira Data error al descomprimir 

### ISSUE THREAD

**Issue by ErnestinaKerbs** [sisoputnfrba/foro#2924]
Buenas tardes!
Volví a descargar las .vdi para configurar la mv gráfica (la que tenía funcionaba hasta que hace unos días, cuando la volví a encender, me tiraba un error de kernel o algo por el estilo, por lo que decidí volver a instalarla de cero). 

El problema es que no puedo volver a levantar la MV porque descomprimo el archivo y me tira **"Data error", "Final inesperado del archivo" o "El archivo está dañado".** 

El problema está a la hora de descomprimir porque los hashes de los archivos .zip me dan correctos.   

Estoy usando el programa 7-zip tal como indica la guía https://docs.utnso.com.ar/primeros-pasos/entorno-linux y de la misma forma que lo hice la primera vez (la cual funcionó en su momento). También intenté con WinRAR y tampoco funcionó. 

Ya borré y volví a descargar los .zip un montón de veces pero siempre vuelvo al mismo resultado. 

No sé que mas hacer.

Espero que me puedan ayudar!! Gracias!

### 💻 Obtencion de los hashes: 

**Grafica.vdi**

C:\Users\ernes> certutil -hashfile "C:\Users\ernes\Documents\MV gráfica\Grafica.zip-001\Grafica.vdi" md5
MD5 hash de C:\Users\ernes\Documents\MV gráfica\Grafica.zip-001\Grafica.vdi:
d4290b345d7948c8f870826054fd445a
CertUtil: -hashfile comando completado correctamente.

**Grafica.zip.001**

C:\Users\ernes> certutil -hashfile "C:\Users\ernes\Documents\MV gráfica\Grafica.zip-001.001"  md5
MD5 hash de C:\Users\ernes\Documents\MV gráfica\Grafica.zip-001.001:
5ee3c35d23d922943977b54e24d218b4
CertUtil: -hashfile comando completado correctamente.

**Grafica.zip.002**

C:\Users\ernes> certutil -hashfile "C:\Users\ernes\Documents\MV gráfica\Grafica.zip.002" md5
MD5 hash de C:\Users\ernes\Documents\MV gráfica\Grafica.zip.002:
60691da5303b1e1763ef20b2701208b8
CertUtil: -hashfile comando completado correctamente.

### 🖥️ Especificaciones del host
- Sistema Operativo y versión: Windows 11 version 22621.232
- Memoria RAM: 8gb
- Procesador: Intel core i3

**Comment by iago64** [comment]
Buenas! Cómo va?

Me llama realmente la atención que ambos md5 de los archivos de la vm estan bien pero no extraen, acabo de bajarlos nuevamente y los md5 son los siguientes:

```
facch@DESKTOP-0UI0J72 MINGW64 /e/Mis Documentos/Descargas
$ certutil -hashfile Grafica.zip.001 md5
MD5 hash de Grafica.zip.001:
5ee3c35d23d922943977b54e24d218b4
CertUtil: -hashfile comando completado correctamente.

facch@DESKTOP-0UI0J72 MINGW64 /e/Mis Documentos/Descargas
$ certutil -hashfile Grafica.zip.002 md5
MD5 hash de Grafica.zip.002:
60691da5303b1e1763ef20b2701208b8
CertUtil: -hashfile comando completado correctamente.
```

Lo que me lleva a preguntar, 7zip, estas usando la opción de extraer aqui o extract here?
![image](https://user-images.githubusercontent.com/1622109/233867021-f9103c76-baec-4620-ba32-5c800bfe5e29.png)

Porque no le encuentro una explicación a que te falle el descomprimir si los archivos están bien.

Saludos.-

**Comment by ErnestinaKerbs** [comment]
Hola!! Ya lo pude resolver! Resulta que tenía que seleccionar ambos archivos (el .001 y el .002) y extraerlos simultáneamente. Haciendo eso descomprime Grafica.vdi perfecto. Mil gracias por la pronta respuesta igual!! 

Saludos!
