### ISSUE TITLE
Problema "double free or corruption (out)" "Aborted (core dumped)" respecto a "crear_conexion" de commons

### ISSUE THREAD

**Issue by MaximoBoglioli** [sisoputnfrba/foro#2925]
Intentando hacer que nuestro programa del modulo filesystem funcione, nos aparece este error con la funcion crear_conexion. Más puntualmente en la linea de "freeaddrinfo(server_info);"
Identificamos que era allí a partir del uso de printf. Como es una función del sistema vengo a preguntar en este foro.
Cabe destacar que si comento la linea, el error desaparece y el codigo funciona correctamente.

### 🔎 Búsqueda en foros
Buscamos en los foros pero ninguno de los que vimos era respecto a la función "freeaddrinfo(server_info);"

### 📝 Código relevante
**Nuestro codigo de filesystem**
```c
#include "include/filesystem.h"

int main(void){

	char* puerto_escucha;
	char* puerto_memoria;
	char* ip_memoria;
	int handshake_Memoria = 4;
	int handshake_Kernel;
	int result_Memoria;
	int resultOk = 0;
	int resultError = 1;

	//Inicializamos el log
	logger = iniciar_logger("./logsfilesystem.log", "Log-FILESYSTEM");

	//Creamos el archivo de configuación
	t_config* config = iniciar_config("./filesystem.config");

	printf("\n0\n");

	//Cargamos la configuración en variables
	leer_config(config, puerto_escucha,  puerto_memoria, ip_memoria);

	printf("\n1\n");

	//Creamos la conexión con la Memoria
	int conexion_memoria = crear_conexion(ip_memoria, puerto_memoria);
	log_info(logger,"Se creo la conexion con la Memoria.");

	printf("\n2\n");

	//Iniciamos el servidor y esperamos el kernel
	int server_kernel = iniciar_servidor(logger);
	log_info(logger, "Servidor listo para recibir al kernel");
	int conexion_kernel = esperar_cliente(server_kernel, logger);

	handshake_cliente (conexion_memoria, result_Memoria, handshake_Memoria);
	if (result_Memoria != 0){
		log_error(logger, "ERROR EN EL HANDSHAKE FILESYSTEM -> MEMORIA!, exit 1");
//		exit(1);
	}

	else {
		log_info(logger, "Hanshake FileSystem -> Memoria realizado correctamente");
	}

	// Hacemos el handshake FILESYSTEM - Kernel
	handshake_servidor(conexion_kernel, handshake_Kernel, resultOk, resultError);


	//Terminamos el progama y liberamos las conexiones, logger y config
	terminar_programa(logger, config, conexion_memoria);
	return 0;
}
```

**Funcion de cliente.c (recortada del resto del archivo)**
```c
int crear_conexion(char *ip, char* puerto)
{
	printf ("1.1\n");
	struct addrinfo hints;
	printf ("1.2\n");
	struct addrinfo *server_info;

	printf ("1.3\n");
	memset(&hints, 0, sizeof(hints));
	printf ("1.4\n");
	hints.ai_family = AF_UNSPEC;
	printf ("1.5\n");
	hints.ai_socktype = SOCK_STREAM;
	printf ("1.6\n");
	hints.ai_flags = AI_PASSIVE;

	printf ("1.7\n");
	getaddrinfo(ip, puerto, &hints, &server_info);
	printf ("1.8\n");
	// Ahora vamos a crear el socket.
	int socket_cliente = socket(server_info->ai_family, server_info->ai_socktype, server_info->ai_protocol);
	printf ("1.9\n");
	// Ahora que tenemos el socket, vamos a conectarlo
	connect(socket_cliente, server_info->ai_addr, server_info->ai_addrlen);
	printf ("1.10\n");
	freeaddrinfo(server_info);  <-- **Linea de Error**
	printf ("1.11\n");
	return socket_cliente;
}
```

### 🐛 Cómo reproducir el error
Ejecutamos el modulo filesystem y esta es la salida:

```
0

0.1

0.2

0.3

0.4
[INFO] 20:25:07:435 Log-FILESYSTEM/(55332:55332): Lei los siguientes datos: 
 Puerto Kernel: 46870 
Puerto Memoria: 46850 	 IP Memoria: 127.0.0.1 


0.5

1
1.1
1.2
1.3
1.4
1.5
1.6
1.7
1.8
1.9
1.10
double free or corruption (out)
Aborted (core dumped)

```

Muchas gracias por leer
Saludos
Maxikiosco

**Comment by iago64** [comment]
Buenas! Cómo va?

Empecé a leer el issue y me hicieron poner triste ya que la frase: _Identificamos que era allí a partir del uso de printf_ me hace notar que en materias anteriores no les comentaron de lo copado que es tener un IDE y una herramienta de debug. Si están usando eclipse les recomiendo muchísimo que le peguen una revisada a la [Guia de Debugging en Eclipse](https://docs.utnso.com.ar/guias/herramientas/debugger) que esta en la pagina de docs, asi no tienen que sufrir con ese infiermo de printfs por todos lados :)

En segundo lugar, los errores de memoria si bien son de lo más común en C, la verdad que es complicado andar adivinando a ciegas, por lo que otra guía que les recomiendo que revisen es la [Guía de Valgrind](https://docs.utnso.com.ar/guias/herramientas/valgrind), eso los va a ayudar a futuro y en este caso les va a poder dar info de si liberaron o no la variable de `server_info`.

Ahora si, me tome el tiempo de dejarles 2 guías que los van a ayudar a futuro, ya que este tipo de problemas van a pasarles más de 1 vez y no esta bueno que tengan que comerse la espera hasta que algún ayudante ande dando vueltas por el foro y les pueda responder. 

Saludos.-

**Comment by iago64** [comment]
Buenas! Cómo va?

@MaximoBoglioli Con las guías que te pase, pudiste encontrar el origen del error? 

Saludos.-

**Comment by MaximoBoglioli** [comment]
Hola,

Si, debuggueando vimos que era un problema en la configuración. Aun no lo resolvimos pero hardcodeando pudimos seguir adelante.

Muchas Gracias igualmente

**Comment by iago64** [comment]
Buenas! 

Que problema de la config? no les levantaban los valores? Es importante que no dejen pasar estas cosas tampoco porque despues avanza el cuatrimestre y no se acuerdan por que estan esos valores hardcodeados en el tp 😉 

Saludos.-

**Comment by iago64** [comment]
Cerramos el issue por inactividad, cualquier cosa lo pueden volver a abrir.
