### ISSUE TITLE
Cambiar almacenamiento de la VM en mi sistema.

### ISSUE THREAD

**Issue by juannardi13** [sisoputnfrba/foro#2926]
Hola! Perdón por molestar, pero estoy teniendo un problema con el almacenamiento de la VM, no sé si es que funciona como yo pienso pero dentro de mi sistema tengo guardados los datos de lo que "voy haciendo en la VM". El tema es que esos datos los tengo en un disco que ya no tiene espacio casi y quería cambiarlos a otro disco.  Quería saber si puedo cambiar de lugar esos datos para que no se quede sin espacio la VM y cómo puedo hacerlo.
Perdón por las molestias, buenas noches.

**Comment by RaniAgus** [comment]
¡Buenas!

Podés ir a `File` > `Virtual Media Manager`:

![image](https://user-images.githubusercontent.com/39303639/233994233-b943a0ce-b266-4933-ba8c-f95ccc9f9471.png)

Desde ahí seleccionás el .vdi a mover y hacés click en `Move` para elegir el destino:

![image](https://user-images.githubusercontent.com/39303639/233994518-f98801fb-4200-4e44-bc6a-a666f9cbef7e.png)


Saludos

**Comment by juannardi13** [comment]
Ya lo pude solucionar! Muchísimas gracias por tu tiempo :)))

**Comment by iago64** [comment]
No se olviden de cerrar los issues cuando los problemas estan resueltos 😊
