### ISSUE TITLE
Dudas con respecto a WAIT y SIGNAL

### ISSUE THREAD

**Issue by DanielBareiro** [sisoputnfrba/foro#2927]
Buenas tengo una consulta con esta parte del enunciado.
>A la hora de recibir de la CPU un Contexto de Ejecución desplazado por WAIT, el Kernel deberá verificar primero que exista el recurso solicitado y en caso de que exista restarle 1 a la cantidad de instancias del mismo. En caso de que el número sea estrictamente menor a 0, el proceso que realizó WAIT se bloqueará en la cola de bloqueados correspondiente al recurso.

Es decir que el proceso cuando le resta una instancia de recurso o le suma con SIGNAL, ese proceso sigue en el cpu? y solamente "vuelve" a kernel cuando el recurso solicitado su instancia es menor a 0 y le da lugar a ejecutar a otro proceso?

>A la hora de recibir de la CPU un Contexto de Ejecución desplazado por SIGNAL, el Kernel deberá verificar primero que exista el recurso solicitado y luego sumarle 1 a la cantidad de instancias del mismo. En caso de que corresponda, desbloquea al primer proceso de la cola de bloqueados de ese recurso. 

Cuando dice que desbloquea el proceso de la cola de bloqueados, eso quiere decir que vuelve a ready no? como en la teoria?

**Comment by LeandroCarbajales** [comment]
Buenas!

> Es decir que el proceso cuando le resta una instancia de recurso o le suma con SIGNAL, ese proceso sigue en el cpu? y solamente "vuelve" a kernel cuando el recurso solicitado su instancia es menor a 0 y le da lugar a ejecutar a otro proceso?

Si no "volviera" al Kernel nunca estarías ejecutando el WAIT o el SIGNAL, pero la idea es que en los casos que mencionás no habría razón para bloquear al proceso y, por tener un algoritmo sin desalojo, para replanificar tampoco, por lo que el proceso se mantendría en estado "running" y deberías volver a poner a ejecutar al mismo.

> Cuando dice que desbloquea el proceso de la cola de bloqueados, eso quiere decir que vuelve a ready no? como en la teoria?

Exactamente, pasaría de estado bloqueado a ready.

Saludos!
      Lean

**Comment by DanielBareiro** [comment]
Ok creo que entiendo. Gracias!

**Comment by LeandroCarbajales** [comment]
Exacto!
Igual que como funcionaría un semáforo convencional que usamos en los ejercicios :)

**Comment by DanielBareiro** [comment]
Perfecto, muchas gracias!!
