### ISSUE TITLE
Ejecutar mi programa desde la terminal linux

### ISSUE THREAD

**Issue by GuidoMartinez1** [sisoputnfrba/foro#2928]
A la hora de querer ejecutar un modulo desde la consola de linux, el mismo "no hace nada". Pero a la hora de realizar lo mismo desde la consola del eclipse, funciona correctamente. 

A continuación adjunto imagenes que reflejan mi inconveniente.

![MemoriaLevantadaDesdeEclipse](https://user-images.githubusercontent.com/49042305/234109489-63722188-f393-4f8d-a18c-057e6b85f605.jpg)

En esta imagen, se puede ver, como al correrlo con eclipse, con sus enviroment correctamente seteadas, el servidor de Memoria se levanta correctamente. 

Pero a la hora de levantarlo por la terminal de linux (habiendole editado la rute path al archivo de config y de logs) me pasa lo siguiente:

![MemoriaEjecutadaDesdeConsola](https://user-images.githubusercontent.com/49042305/234110401-979cbaea-9bd6-4453-8314-5977ecb46732.jpg)

Una aclaración tal vez no menor, es que previo a implementar la libreria compartida, yo ejecutando "./Memoria" el programa se ejecutaba correctamente.

Gracias desde ya!

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va?

A ojo estoy viendo que en una parte del código tienen algo como:
```c
if (memoria_logger == NULL) {
    exit(1);
}

// ...

if (memoria_config == NULL) {
    exit(2);
}
```
Probablemente si agregan un `printf` antes de los `exit` verán que no es que el programa "no hacía nada", sino que "no _imprimía_ nada", porque al entrar por esa condición del `if` finalizaba y la terminal le regresaba el control al usuario inmediatamente.

También veo a la derecha que están ejecutando el programa desde la carpeta `Debug`, por lo que probablemente esté entrando dentro de uno de esos `if` por un problema de rutas relativas. Por suerte, tenemos [una guía al respecto que pueden consultar](https://docs.utnso.com.ar/guias/consola/rutas) 😉 

Avísennos lograron resolver el problema aplicando la solución que propone la guía.

Saludos

**Comment by GuidoMartinez1** [comment]
Acabo de revisar lo que me dijiste, printeando previo a cada exit y sigue sin mostrame nada la consola... 

Gracias de todas formas por contestar Agustin!

**Comment by RaniAgus** [comment]
¿Volvieron a compilar para aplicar los cambios de código que hicieron? 
¿Ejecutaron `./Debug/Memoria` desde la carpeta `Memoria` como sugiere la guía?

**Comment by iago64** [comment]
Buenas! Cerramos el issue por inactividad, cualquier cosa lo pueden volver a abrir o crear uno nuevo haciendo referencia a este issue.
