### ISSUE TITLE
Duda si se tienen que contemplar errores del usuario

### ISSUE THREAD

**Issue by lucasdeferrari** [sisoputnfrba/foro#2929]
Buenos días, tenemos una consulta con el enunciado. Si en el archivo de pseudocodigo que le llega a la consola hay algun error, como por ejemplo una instruccion con parametros de mas o de menos, o algun error de tipeo en alguna instruccion; deberiamos contemplarlo nosotros o eso corre por cuenta del usuario? 
Desde ya, muchas gracias.

**Comment by LeandroCarbajales** [comment]
Buenas!
El enunciado nunca pide que se detecten ese tipo de errores ni cómo contemplarlos.
Si llegara a ser el caso nos deberían avisar así arreglamos las pruebas ya que en este caso seríamos los "usuarios" :)

Saludos!
       Lean

**Comment by lucasdeferrari** [comment]
Genial gracias!
