### ISSUE TITLE
Acceso a repo del TP

### ISSUE THREAD

**Issue by FacundoStancanelliUTN** [sisoputnfrba/foro#2930]
Hola, no estaría pudiendo entrar al repositorio de mi grupo, creo que es porque expiro el tiempo de acceso.
Repo del grupo: https://github.com/sisoputnfrba/tp-2023-1c-6666
Estuve trabajando con el user de un compañero pero no pude entrar con el mio. 
Mi mail: [fstancanelli@frba.utn.edu.ar](mailto:fstancanelli@frba.utn.edu.ar)
Gracias!
Saludos!

**Comment by LeandroCarbajales** [comment]
Buenas!
Podés volver a enviarte la invitación al repo desde el sistema de inscripciones :)

Saludos!
      Lean

**Comment by FacundoStancanelliUTN** [comment]
Dale, ahi pude.
Gracias!
