### ISSUE TITLE
Instrucción SIGNAL

### ISSUE THREAD

**Issue by JoacoAltalef** [sisoputnfrba/foro#2932]
Buenas. Tengo una duda con respecto al enunciado del TP:

Al final de la parte de manejo de recursos del Kernel, dice que "se devuelve la ejecución al proceso que peticionó SIGNAL". ¿Esto quiere decir que, cuando se está ejecutando las instrucciones de un proceso, y llega la instrucción SIGNAL, se debe avisar a Kernel que se liberó ese recurso, pero el proceso sigue en estado EXEC? Es decir, ¿sigue ejecutando el resto de instrucciones?

Porque si es así, ¿no se contradiría con la parte del enunciado que dice que se debe desalojar (al final de la parte de Execute, la parte del ciclo de Instrucción, del módulo CPU)?

¿O simplemente, tanto en WAIT como SIGNAL, debo desalojar el proceso, hacer lo que tenga que hacer el kernel, y enviar a este proceso a Ready?

### 📔 Citas del enunciado/videos
En la parte de Manejo de Recursos del Kernel:
"A la hora de recibir de la CPU un Contexto de Ejecución desplazado por SIGNAL, el Kernel deberá verificar primero que exista el recurso solicitado y luego sumarle 1 a la cantidad de instancias del mismo. En caso de que corresponda, desbloquea al primer proceso de la cola de bloqueados de ese recurso. Una vez hecho esto, se devuelve la ejecución al proceso que peticionó el SIGNAL."

Al final de la parte de Execute, en la parte de Ciclo de Instrucción, del módulo CPU:
"Para las siguientes instrucciones se deberá devolver al módulo Kernel el Contexto de Ejecución actualizado junto al motivo del desalojo y los parámetros que necesite cada instrucción: I/O, F_OPEN, F_CLOSE, F_SEEK, F_READ, F_WRITE, F_TRUNCATE, WAIT, SIGNAL, CREATE_SEGMENT, DELETE_SEGMENT, YIELD y EXIT."

**Comment by LeandroCarbajales** [comment]
Buenas!

> ¿Esto quiere decir que, cuando se está ejecutando las instrucciones de un proceso, y llega la instrucción SIGNAL, se debe avisar a Kernel que se liberó ese recurso, pero el proceso sigue en estado EXEC? Es decir, ¿sigue ejecutando el resto de instrucciones?

No es así, justamente como bien marcás, en todos esos casos que indica la parte de implementación de CPU, el contexto de ejecución se devuelve al Kernel y la CPU se quedará esperando que le vuelva a dar otro (que puede ser el mismo).
A nivel diseño de implementación del trabajo, la idea es que la CPU no sabe qué hacen ni WAIT ni SIGNAL ni ninguna de esas, solamente conoce su interfaz, por lo que si o si debe devolver el contexto de ejecución para que eso lo haga el Kernel.
Luego, viéndolo a nivel conceptual de la materia, es la misma idea de una syscall, el proceso no puede realizar esa función por sí mismo, debe delegarle esa ejecución al Kernel. Luego el Kernel en este caso en particular decide mantener al mismo proceso en ejecución (no replanificar), pero un Kernel distinto (por ejemplo si el algoritmo de planificación de corto plazo fuera con desalojo) podría decidir replanificar si lo quisiera.

> ¿O simplemente, tanto en WAIT como SIGNAL, debo desalojar el proceso, hacer lo que tenga que hacer el kernel, y enviar a este proceso a Ready?

En estos casos el proceso no volvería a ready ya que no hay replanificación alguna, para el Kernel su estado sigue siendo "running" a pesar de que durante el tiempo en que está atendiendo esa "syscall" no se está ejecutando el proceso en la CPU.
Entonces la idea es que durante todo este proceso el proceso está "running":
Ejecuta la instrucción SIGNAL() -> Le devuelve el contexto de ejecución al Kernel -> el Kernel hace lo que tiene que hacer (en este caso no replanifica) -> vuelve a darle el mismo contexto de ejecución a la CPU para que siga ejecutando.

Este procedimiento es similar al de una syscall real no bloqueante:
El proceso ejecuta la syscall -> Cede la ejecución al SO (cambio de contexto) -> El SO hace lo que tiene que hacer -> Vuelve a darle la ejecución al proceso (cambio de contexto)

Queda más clara la idea?

**Comment by JoacoAltalef** [comment]
Clarísimo! Muchas gracias!
