### ISSUE TITLE
Duda sobre serialización de la lista de instrucciones

### ISSUE THREAD

**Issue by fmarsico8** [sisoputnfrba/foro#2933]
Hola! como estan?
Les hago una consulta, estamos con el tema de serializar la lista de instrucciones que leemos del archivo que recibe la consola.
Nuestra estructura es del tipo: 
```
typedef struct{
    uint32_t tamanio;
    t_list* instrucciones;
}t_instrucciones;

typedef struct {
    uint32_t size; 
    void* stream; 
} t_buffer;

typedef struct {
    uint8_t cod_op;
    t_buffer* buffer;
} t_paquete;
```
Pero nos trabamos al momento de calcular el tamaño de la lista, dado que no le podemos hacer un sizeof() o strlen() como en los ejemplos. Nuestra idea era mapear la lista con strlen y dsps obtener la sumatoria, pero se nos complico y tampoco creemos q sea la forma correcta, pero vimos que en la guia de serialización sumaba sizeof(unit8_t) + la longitud de un string, entonces eso capaz nos confundio si se sumaban bytes con caracteres. Nos podrian dar una mano?

### 📝 Código relevante
```
t_instrucciones instruccion;

    t_buffer* buffer = malloc(sizeof(t_buffer));

    buffer->size = sizeof(uint32_t) + tamanioLista(listado);

    void* stream = malloc(buffer->size);
    int offset1 = 0;

    memcpy(stream  + offset1, &instruccion.tamanio, sizeof(uint32_t));
    offset1 += sizeof(uint32_t);
    memcpy(stream + offset1, instruccion.instrucciones, tamanioLista(listado));

    buffer->stream = stream;

    free(instruccion.instrucciones);
```

**Comment by ncoen97** [comment]
Buenas!

Para guiarlos un poco mejor me parece interesante empezar viendo un poco más a detalle qué es un `t_list *`. Este tipo es el usado en las commons y representa a la lista en sí. Cómo pueden ver en [list.h](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/collections/list.h), tiene varias funciones asociadas, por ejemplo para crear la estructura, añadirle elementos, iterar, etc. Una de las funciones es `list_size(my_list)`, que directamente les devuelve la cantidad de elementos.

Dicho esto, me parece que estaría bueno que definan bien qué es una instrucción. Esto lo están haciendo desde el módulo consola? Tienen solo los char* de cada linea de instrucción? O ya las parsearon a alguna estructura como para diferenciar qué es cada una? En ambos casos esa estructura o char* sería el contenido de cada item de la lista, que lo añaden mediante `list_add(instrucciones, (void*)instruccion);`. 

Empiecen evaluando estas cosas. Una vez que armen bien esta estructura ya les va a ser más sensillo lo que sigue, y si tienen más dudas con respecto a la serialización las vemos.

Saludos!!

**Comment by chiaraberetta0** [comment]
Sip lo estamos haciendo desde la consola, y lo que tenemos en cada elemento de la lista
es el char* de cada línea de instrucción. Lo que hicimos fue ir leyendo el archivo y 
guardando el contenido en un vector auxiliar hasta que se encontrase con un "/n" para finalmente
agregar el contenido de ese vector a la lista.
Nuestra duda venia más por el lado de si estaba bien que su tamaño fuese el size de la lista,
si le teníamos que sumar los "/0" o si necesitábamos la sumatoria de los length de cada instrucción.

**Comment by LeandroCarbajales** [comment]
Buenas!

> Nuestra duda venia más por el lado de si estaba bien que su tamaño fuese el size de la lista,
si le teníamos que sumar los "/0" o si necesitábamos la sumatoria de los length de cada instrucción.

Probablemente no necesiten la sumatoria de los length de cada instrucción, pero sí el list_size y agregar un "\0" al final de cada línea para poder saber su longitud con strlen().
De esta manera lo pueden pensar en 2 niveles, quiero enviar una lista con N elementos, entonces seguramente quiera enviar primero la cantidad de elementos N, que vendría a ser el list_size (la cantidad de instrucciones). Luego para enviar cada instrucción enviarían la cadena de caracteres con su tamaño (strlen() de la misma), el "\0" pueden no enviarlo si luego lo agregan nuevamente al recibirlo desde el Kernel.

Les sirve la respuesta?
Saludos!
      Lean
