### ISSUE TITLE
Duda de lo que recibe la CPU del Kernel

### ISSUE THREAD

**Issue by agusdubreucq1** [sisoputnfrba/foro#2934]
buenas, queria consultar si cuando un proceso pasa a ser ejecutado, lo que le mandamos a la CPU podria ser el PCB completo y que la CPU use lo que sea necesario. Y en el caso de que solo haya que pasarle lo correspondiente a el contexto de ejecucion ¿que partes del PCB serian? entiendo que las instrucciones, program_counter, registros de la CPU y la tabla de segmentos, pero para sacarme la duda.

**Comment by LeandroCarbajales** [comment]
Buenas!
La recomendación es que se envíen solamente lo necesario ya que eso implicaría:
- Menos cosas para serializar ;)
- Si en algún momento quisieran agregarle algo más al PCB que les sea útil (por ejemplo, estado del proceso, socket de la consola, etc) no necesitarían modificar la serialización :)

El contexto de ejecución es todo lo que necesita la CPU para ejecutar ese proceso en particular que es justamente todo eso que bien marcás y le agregaría también el PID para poder cumplir con los logs del módulo CPU.

Les aclara la duda?
Saludos!
     Lean

**Comment by agusdubreucq1** [comment]
ahh perfecto, si se entendio. muchas gracias!!
