### ISSUE TITLE
Problema con las commons

### ISSUE THREAD

**Issue by luciagandur** [sisoputnfrba/foro#2935]
Al abrir el documento de log.h de los commons en eclipse no aparece nada, como si estuviese vacio. Luego cuando accedemos a traves del exploador de archivos abre con todo lo que tiene que tener. Esto produce que muchas de las funciones compartidas no existan y por consiguiente no compile.
### 📝 Pasos para reproducir el error
Clonamos el repo, en una compu, abrimos eclipse, y al compilar nos tira errores porque no tiene las funciones definidas.
Cabe aclarar que en otras 2 pcs de nuestros compañeros compila bien.
💻 Logs
19:32:49 **** Build of configuration Debug for project shared ****
make all 
Building file: ../src/cliente.c
Invoking: GCC C Compiler
gcc -O0 -g3 -Wall -c -fmessage-length=0 -fPIC -MMD -MP -MF"src/cliente.d" -MT"src/cliente.o" -o "src/cliente.o" "../src/cliente.c"
../src/cliente.c: In function ‘crear_super_paquete’:
../src/cliente.c:79:16: warning: ‘paquete’ is used uninitialized [-Wuninitialized]
   79 |         return paquete;
      |                ^~~~~~~
Finished building: ../src/cliente.c
 
Building file: ../src/servidor.c
Invoking: GCC C Compiler
gcc -O0 -g3 -Wall -c -fmessage-length=0 -fPIC -MMD -MP -MF"src/servidor.d" -MT"src/servidor.o" -o "src/servidor.o" "../src/servidor.c"
In file included from ../src/servidor.c:1:
../src/../include/servidor.h:23:8: error: unknown type name ‘t_log’
   23 | extern t_log* logger;
      |        ^~~~~
../src/../include/servidor.h:29:1: error: unknown type name ‘t_list’; did you mean ‘va_list’?
   29 | t_list* recibir_paquete(int);
      | ^~~~~~
      | va_list
../src/servidor.c:3:1: error: unknown type name ‘t_log’; did you mean ‘u_long’?
    3 | t_log* logger;
      | ^~~~~
      | u_long
../src/servidor.c: In function ‘iniciar_servidor’:
../src/servidor.c:35:9: warning: implicit declaration of function ‘log_trace’ [-Wimplicit-function-declaration]
   35 |         log_trace(logger, "Listo para escuchar a mi cliente");
      |         ^~~~~~~~~
../src/servidor.c:12:44: warning: unused variable ‘p’ [-Wunused-variable]
   12 |         struct addrinfo hints, *servinfo, *p;
      |                                            ^
../src/servidor.c: In function ‘esperar_cliente’:
../src/servidor.c:50:9: warning: implicit declaration of function ‘log_info’ [-Wimplicit-function-declaration]
   50 |         log_info(logger, "Se conecto un cliente!");
      |         ^~~~~~~~
../src/servidor.c: At top level:
../src/servidor.c:88:1: error: unknown type name ‘t_list’; did you mean ‘va_list’?
   88 | t_list* recibir_paquete(int socket_cliente)
      | ^~~~~~
      | va_list
../src/servidor.c: In function ‘recibir_paquete’:
../src/servidor.c:93:9: error: unknown type name ‘t_list’; did you mean ‘va_list’?
   93 |         t_list* valores = list_create();
      |         ^~~~~~
      |         va_list
../src/servidor.c:93:27: warning: implicit declaration of function ‘list_create’ [-Wimplicit-function-declaration]
   93 |         t_list* valores = list_create();
      |                           ^~~~~~~~~~~
../src/servidor.c:93:27: warning: initialization of ‘int *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
../src/servidor.c:104:17: warning: implicit declaration of function ‘list_add’ [-Wimplicit-function-declaration]
  104 |                 list_add(valores, valor);
      |                 ^~~~~~~~
make: *** [src/subdir.mk:23: src/servidor.o] Error 1
"make all" terminated with exit code 2. Build might be incomplete.

19:32:52 Build Failed. 6 errors, 7 warnings. (took 3s.147ms)

**Comment by RaniAgus** [comment]
¡Buenas! Como verás, Eclipse está invocando a gcc de la siguiente forma:

```
gcc -O0 -g3 -Wall -c -fmessage-length=0 -fPIC -MMD -MP -MF"src/cliente.d" -MT"src/cliente.o" -o "src/cliente.o"

gcc -O0 -g3 -Wall -c -fmessage-length=0 -fPIC -MMD -MP -MF"src/servidor.d" -MT"src/servidor.o" -o "src/servidor.o" "../src/servidor.c"
```

Y que le está faltando el flag `-lcommons` para vincular la biblioteca. La forma de hacerlo se encuentra en [este video](https://www.youtube.com/watch?v=Q8wfpu38PMc) que también está en [los primeros pasos de Docs](https://docs.utnso.com.ar/primeros-pasos/entorno-desarrollo#crear-un-proyecto-en-eclipse).

Saludos

**Comment by LeandroCarbajales** [comment]
Agrego también que en el [readme de las commons](https://github.com/sisoputnfrba/so-commons-library#desde-eclipse) están los pasos para linkear las commons en un proyecto de eclise :)

**Comment by iago64** [comment]
@luciagandur Cómo va? te sirvieron los comentarios de Agus y Lean? Podes comentarnos si seguís con el inconveniente?

Saludos.-

**Comment by iago64** [comment]
Cerramos el issue por inactividad, cualquier inconveniente pueden reabrir el issue o pueden crear uno nuevo y referenciarlo
