### ISSUE TITLE
Duda sobre las estructuras de FileSystem

### ISSUE THREAD

**Issue by Juan-Polito** [sisoputnfrba/foro#2937]
Querido destinatario/a.
Me preguntaba si las estructuras de File System (superbloque, bitmap, bloques y fcb) se crean a travez de codigo en el path indicado en las config del archivo o, si se crean a mano y luego se levantan por codigo. Ademas, me preguntaba si el archivo fcb tambien es un .dat como el resto.
Desde ya muchas gracias, Juan.

📔 Citas del enunciado

Ejemplo de Archivo de Configuración
IP_MEMORIA=127.0.0.1
PUERTO_MEMORIA=8002
PUERTO_ESCUCHA=8003
PATH_SUPERBLOQUE=/home/utnso/fs/superbloque.dat
PATH_BITMAP=/home/utnso/fs/bitmap.dat
PATH_BLOQUES=/home/utnso/fs/bloques.dat
PATH_FCB=/home/utnso/fs/fcb
RETARDO_ACCESO_BLOQUE=15000

**Comment by RaniAgus** [comment]
¡Buenas!

El único que ya debe venir creado de antemano es el archivo de superbloque, el resto les recomendaría hacer el chequeo de si ya existen o no (y, en caso de no existir, crearlos), más que nada por comodidad si hace falta limpiar el FS actual y cambiar la configuración del superbloque entre pruebas.

En la parte de FS verán que en Linux da lo mismo la extensión del archivo, aunque en este caso el PATH_FCB lo escribimos de esta forma porque se trata de un directorio.

Saludos

**Comment by iago64** [comment]
Buenas @Juan-Polito te sirvió la respuesta de Agus? Necesitas una mano con algo mas?

**Comment by Juan-Polito** [comment]
Si, me sirvió y lo implementamos con el grupo. Gracias por la ayuda

**Comment by iago64** [comment]
No se olviden de cerrar los issues por favor 😊

**Comment by MatiasHermidaUTN** [comment]
Buenas, una duda sobre esto. Para crear las estructuras de File System (bitmap y bloques) desde el código, pensamos usar comandos de linux con system() para ya crearlos con el tamaño total necesario.
Para el bitmap: dd if=/dev/zero of=bitmap.dat bs=1 count=8192
Para el bloques: dd if=/dev/urandom bs=65536 count=64 | tr -c '[:print:]' '-' > bloques.dat

Mi pregunta es si es necesario crearlos con el tamaño total o se puede simplemente crear los archivos con un fopen(bloques, "w") e ir agrandandolos conforme necesitemos (por ejemplo, cuando le agrego un puntero indirecto y bloques a un file)?

**Comment by RaniAgus** [comment]
¡Buenas @MatiasHermidaUTN!
Perdón pero antes de responder me tengo que poner la gorra y decir (como recomendamos en el README del foro) que para la próxima si encuentran una pregunta que se encuentra cerrada y no resuelve completamente su duda, no escriban en esa misma pregunta: anoten el número de issue para referirlo en su nueva pregunta.

Esto es porque en Discord tenemos un webhook que nos avisa a todos cuando se abre o cierra un issue, por lo que no hace falta arrobarnos a algunos de nosotros para saber que apareció un comentario nuevo 😅 

Ahora sí, respondiendo tu duda, sí deben truncar los archivos a sus tamaños correspondientes, pero para eso puede que les resulte más cómodo usar `ftruncate()`: [ftruncate(3p) — Linux manual page](https://man7.org/linux/man-pages/man3/ftruncate.3p.html)

Saludos

**Comment by MatiasHermidaUTN** [comment]
Perfecto, perdón y muchísimas gracias
