### ISSUE TITLE
Duda con serialización

### ISSUE THREAD

**Issue by fmarsico8** [sisoputnfrba/foro#2938]
Hola, teníamos una duda con el envió de paquete desde la consola al kernel, ya armamos toda la estructura y reutilizamos el código de Tp0 de agregar_a_paquete, el problema esta en que del lado del kernel cuando recibe la operación nos da -1, por lo que estaría fallando la cantidad de bytes enviada. Lo que enviamos sería algo así: 

### 📝 Código relevante

```
void paquete(socket_conexion, listado){

    t_paquete* paquete = crear_paquete();
    int i;

    for(i=0; i<list_size(listado); i++){
        agregar_a_paquete(paquete, list_get(listado, i), strlen(list_get(listado, i)) + 1); //agrega el \0
    }

    enviar_paquete(paquete, socket_conexion);

    eliminar_paquete(paquete);
}
```
Nosotros el pseudocodigo lo agregamos en una lista y en esta función iteramos los elementos de la lista, para ir agregándolos uno por uno al paquete. 

Tenemos duda si el tamaño que estamos enviando es el correcto, ya que en la descripción de agregar_a_paquete dice que se le debe agregar un stream y luego un string (en el tp0 en la página de utnso).

Copio textual como lo dice en la página de UTNSO
agregar_a_paquete(2): Dado un stream y su tamaño, lo agrega al paquete.
Es importante recalcar que hay que agregar al paquete un string (y no un stream).

**Comment by RaniAgus** [comment]
¡Buenas! Creo que a continuación del texto que citaban se encuentra la respuesta a su pregunta 😅 

> La diferencia entre ambos radica en que, si bien son una seguidilla de "bytes", el string termina en el caracter `'\0'`, mientras que un stream puede contener cualquier tipo de dato, por lo que hace falta especificar su tamaño utilizando un parámetro extra.

> Para calcular el tamaño de ese string vamos a consultar la documentación de una función amiga llamada [`strlen()`](https://man7.org/linux/man-pages/man3/strlen.3.html). Veremos que nos devuelve el tamaño de un string, sin contar el caracter centinela, por lo que hay que "sumarle 1".

Saludos

**Comment by chiaraberetta0** [comment]
La diferencia la entendimos, pero no nos queda claro si estaria bien lo q le estamos pasando, entendemos q si pero algo rompe

**Comment by RaniAgus** [comment]
Pueden probar de extraer ese `list_get(listado, i)` a una variable y usar el debugger para chequear que les esté retornando el string que esperaban. 

O, también, validar que el `send()` que está dentro de `enviar_paquete()` no les esté devolviendo algún error. Para esto, pueden consultar la [documentación de send](https://man7.org/linux/man-pages/man2/send.2.html).

**Comment by fmarsico8** [comment]
Hola! Perdón que siga pero se nos esta complicando esta parte =( 
Pudimos ver que lo que nos esta pasando es que a la hora de generar el listado que hace recibir_paquete nos esta devolviendo esto: 
```

Listado: Y�B�AV 
Listado: ���  
Listado: �B�AV 
Listado: �`Hd 
Listado: �`Hd 
Listado: ���  
Listado: `���  
Listado: ���  
Listado: 0���  
Listado: ���  
Listado: ���  
Listado: ���  
Listado: ���  
```
Y más símbolos extraños aun, saben si eso puede tener alguna causa?

**Comment by RaniAgus** [comment]
Perdón pero sin saber cómo tienen implementado el envío y la recepción del mensaje se me complica mucho poder ayudarles 😞 

¿La idea sería enviar algo muy parecido a un mensaje del TP0, no? Es decir, un stream que contenga:

```
+------------------+---------------+----------------------------------+----------------------+----
| codigo_operacion | buffer->size  | strlen(list_get(listado, 0)) + 1 | list_get(listado, 0) | ...
|  int (4 bytes)   | int (4 bytes) |            int (4 bytes)         | char[] (n bytes)     |
+------------------+---------------+----------------------------------+----------------------+----
```

De ser así, les recomendaría que con el debugger vayan validando del lado del kernel si efectivamente están recibiendo 4 bytes para el código de operación, 4 para el `buffer->size`, n para el resto del buffer, etc.

También, para entender un poco mejor la implementación del TP0 y que puedan hacer la suya para los distintos tipos de mensajes que necesiten enviar entre procesos, tenemos la [guía de serialización](https://docs.utnso.com.ar/guias/linux/serializacion).
