### ISSUE TITLE
consulta sobre list_remove_by_condition. Parámetros de condition

### ISSUE THREAD

**Issue by Hamamura-S** [sisoputnfrba/foro#2939]
Hola, estoy intentando utilizar `list_remove_by_condition` pasandole un valor por parámetro a `condition` pero no se cómo hacerlo o si se puede hacer. Quiero eliminar un nodo de una lista si el socket de la lista coincide con el socket que yo tengo, para eso necesito pasar el socket por parametro a condition. El problema es que entiendo que condition solo recibe el nodo a evaluar.

**Comment by ncoen97** [comment]
Buenas!

Lo que pueden hacer es poner la funcion que remueve elemento dentro del bloque de código que están ejecutando.

Por ejemplo:
```c
void my_function() {
  int socket;
  t_list* list;
  
  _Bool remover(element_t* element) {
    return element->socket == socket;
  }
  
  list_remove_by_condition(list, (void*)remover);
}
```
Cualquier cosa nos avisan 👌

**Comment by Hamamura-S** [comment]
Gracias! Simple como eso👌
