### ISSUE TITLE
Conexion de multiples consolas a kernel

### ISSUE THREAD

**Issue by lucaschiesa01** [sisoputnfrba/foro#2940]
Buenas, estabamos por hacer la conexion de multiples consolas al modulo de kernel y nos surgio una duda al momento de hacer la conexion.

A la hora de crear/conectar una consola a kernel, del lado de kernel deberiamos crear un thread por cada consola conectada (sentimos que esto puede ser un problema si se crean muchas consolas) o simplemente manejar las conexiones en un main thread? Hay algun otro approach que nos estemos comiendo?

### 🔎 Búsqueda en foros

https://stackoverflow.com/a/45458463
https://www.geeksforgeeks.org/socket-programming-in-cc-handling-multiple-clients-on-server-without-multi-threading/

**Comment by LeandroCarbajales** [comment]
No es necesario tener un hilo por consola, de hecho como bien decís podría terminar haciendo todo más complicado. En un hilo pueden esperar conexiones de consolas nuevas `accept()`, crear su PCB (y quizás guardar su socket en el mismo) y agregarlo a una lista o cola NEW.

**Comment by iago64** [comment]
Buenas @lucaschiesa01 te sirvió la respuesta de Lean? Necesitas una mano con algo mas?

**Comment by iago64** [comment]
Cerramos el issue por inactividad, cualquier inconveniente lo pueden reabrir o crear uno nuevo referenciando este issue
