### ISSUE TITLE
Pthread join o pthread detach

### ISSUE THREAD

**Issue by Plata92** [sisoputnfrba/foro#2941]
Estábamos creando los hilos para conectar varias consolas al kernel y tenemos la siguiente duda:
Con el Pthread detach no ejecuta el subprograma asignado al hilo pero al cambiar por Pthread join si lo ejecuta, Nosotros creemos que es necesario usar el detach dado que mientras se esta ejecutando continua con el código pero no nos estaría andando.

### 🔎 Búsqueda en foros
Vimos el video https://docs.utnso.com.ar/guias/linux/threads, pero seguimos bastante perdidos con el tema hilos.

### 📝 Código relevante
```
void establecer_conexiones()
{
    server_fd = abrir_servidor(logger,config);
    
    pthread_t manejo_consolas;
    pthread_create(&manejo_consolas, NULL, (void *) manejar_clientes, (void *) server_fd);
    pthread_detach(manejo_consolas);
   
}

void manejar_clientes(int server_fd){
    //thread para esperar clientes
    while(1){
        t_conexiones conexiones;
        conexiones.socket = esperar_cliente(server_fd, logger);
        conexiones.socket_anterior = 0;
        // threads para recepcion de info de las consolas
        pthread_t t;
        pthread_create(&t, NULL, (void *) manejar_conexion_con_consola, (void *) &conexiones);
        pthread_detach(t);
    }
}

void manejar_conexion_con_consola(t_conexiones* conexiones){
    int socket = conexiones->socket;
    int socket_anterior = conexiones->socket_anterior;

    int cod_op = recibir_operacion(socket);
    t_list* lista_de_instrucciones = list_create();

    switch(cod_op){
        case 0:
            break;
        case 1:
            lista_de_instrucciones = recibir_paquete(socket);
            crear_pcb(lista_de_instrucciones);
            break;
        default:
            break;
    }
    
}

int abrir_servidor(t_log* logger,t_config* config)
{
    int puerto_escucha;
    puerto_escucha = config_get_int_value(config, "PUERTO_ESCUCHA");

    return iniciar_servidor(logger, puerto_escucha);
}
```
@juanibencardino @LucianoFoglia

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va?

¿Cuál sería la función que llama a `establecer_conexiones()`? Si es simplemente el `main()`, es decir, algo así:

```c
int main() {
    // ...

    establecer_conexiones();

    // ...
    return 0;
}
```
...es probable que lo que esté ocurriendo no sea que "no ejecuta el subprograma asignado al hilo", sino que luego de ejecutar el `phread_detach()` el hilo principal continúa su ejecución hasta ejecutar el `return 0;` del final, lo cual finaliza todos los hilos del proceso, similar a lo que habrán visto en el ejemplo de detach del video.

De ser así, quizás evaluaría llamar directamente `manejar_clientes()` en vez de crear un hilo para eso, por lo que el hilo principal quedaría en ese bucle infinito y no finalizaría el proceso.

Saludos

**Comment by iago64** [comment]
Buenas @Plata92 te sirvió la respuesta de Agus? Necesitas una mano con algo mas respecto de este issue?

**Comment by Plata92** [comment]
Buenas, perfecto muchas gracias, vamos a estar probando, nos falto un semaforo y se iba al main. Cualquier cosa volvemos a consultar. muchas gracias
