### ISSUE TITLE
Duda Program Counter - en PCB y Contexto de Ejecución

### ISSUE THREAD

**Issue by a-sandoval** [sisoputnfrba/foro#2942]
¡Buenas! Quería preguntar por el modelado del Program Counter dentro del PCB y el Contexto de Ejecución que actualiza la CPU.  ¿Bastaría que sea un entero inicializado en 0, que se vaya incrementando a medida que la CPU ejecuta las instrucciones del proceso? Entiendo que esto nos podría servir para, por ejemplo, si se desaloja un proceso, al reiniciar su ejecución obtener la instrucción con el índice que indique el PC. O, en cambio, ¿será algo que se acerque más a la realidad, que hay que esperar a que podamos implementar lo relacionado con Memoria? Entiendo que no haría falta por la simplificación del enunciado, pero no estoy segura. 

### 📔 Citas del enunciado/videos

>Quedará a la espera de las conexiones por parte del Kernel. Una vez conectado, el Kernel le enviará el Contexto de Ejecución para ejecutar. Habiéndose recibido, se procederá a realizar el ciclo de instrucción tomando como punto de partida la instrucción que indique el Program Counter recibido.

**Comment by RaniAgus** [comment]
¡Buenas!

Sí, con un entero que indique el índice dentro de la lista de instrucciones alcanzaría, ya que para la implementación de este TP vamos a guardar esa lista en el PCB como aclaramos en el módulo Kernel, cito:

> A diferencia de la realidad donde el código de un proceso estaría en Memoria, tendremos las instrucciones dentro del PCB para facilitar la implementación del trabajo práctico en los tiempos del cuatrimestre y de forma incremental con respecto a los temas que se ven en clase.

Esto les permite tener implementada una buena parte de la planificación de Kernel-CPU sin tener nada por el lado de Memoria.

Saludos

**Comment by a-sandoval** [comment]
Muchas gracias! Saludos
