### ISSUE TITLE
Duda con el manejo de archivos del filesystem

### ISSUE THREAD

**Issue by AgustinOliva02** [sisoputnfrba/foro#2943]
Buenas, tenemos una duda con el manejo de los archivos en el filesystem. Cuando el filesystem va recibiendo del kernel que tiene que ejecutar operaciones como el F_READ O F_WRITE la idea es que las vaya realizando de forma concurrente con hilos o tiene que ejecutar una despues de otra?

**Comment by LeandroCarbajales** [comment]
Buenas!
Es una muy buena pregunta, la idea es que ejecute una después de otra.
De cualquier manera acabamos de ver que no está aclarado explícitamente en el enunciado, por lo que lo tendremos en cuenta para agregarlo como errata.

Saludos!
        Lean

**Comment by AgustinOliva02** [comment]
Genial! Muchas gracias.
