### ISSUE TITLE
Problema con fopen

### ISSUE THREAD

**Issue by MFalcoo** [sisoputnfrba/foro#2945]
Hola, tengo un problema a la hora de querer abrir mi archivo de pseudocodigo para extraer las instrucciones.
Directamente no me funciona la funcion fopen, o estoy escribiendo mal el path, lo q seria raro.

![issue](https://user-images.githubusercontent.com/102535899/236027331-03397837-43c8-4835-bb8a-084debb594b8.PNG)

**Comment by MFalcoo** [comment]
lo corro y en la consola me imprime: No se pudo abrir el archivo.

**Comment by MFalcoo** [comment]
Ahi pudimos hacerlo, claro estabamos poniendo mal la ruta. Gracias por la mano y los consejos. Saludos

**Comment by RaniAgus** [comment]
¡Buenísimo! Para la próxima, pueden cerrar el issue si ya fue resuelta la duda o consulta 👍🏻
