### ISSUE TITLE
ayuda con los commons

### ISSUE THREAD

**Issue by chen-angela** [sisoputnfrba/foro#2947]
hola, queria hacer una consulta, a la hora de querer linkear los commons, no me aparece la carpeta de GCC C Linker en el setting del eclipce, hay alguna solución a esto?

**Comment by RaniAgus** [comment]
¡Buenas! ¿Podrías pasarnos una captura de pantalla del menú en donde esperabas ver la opción GCC C Linker para contar con más contexto sobre tu duda? Saludos

**Comment by chen-angela** [comment]
cuando queria intentar con otro proyecto no me dejaba, pero con el tp0 ahora si, muchas gracias!

**Comment by iago64** [comment]
Buenas @chen-angela!

Sin una captura o un mensaje de error se nos complica muchísimo poder darte una mano, podes subirnos algo asi podemos ayudarte y que no pierdas mas tiempo.

Saludos.-

**Comment by iago64** [comment]
Buenas @chen-angela, cómo va?

Pudiste avanzar? Podes compartirnos las capturas de los errores asi podemos ayudarte?

Saludos.-

**Comment by chen-angela** [comment]
![16836788156012245427916338662716](https://github.com/sisoputnfrba/foro/assets/129124311/25712bc0-a0f7-496d-b7f5-0d3e112f5f00)
Así es como me aparece ahora

**Comment by RaniAgus** [comment]
Veo que a la izquierda tienen importada la carpeta incorrecta: `tp0` no es un proyecto C/C++, sino que tiene dos carpetas `client` y `server` con proyectos distintos, ya que son dos ejecutables separados. 

Deben importar ambas carpetas como se muestra en la primera parte del enunciado para que Eclipse reconozca los proyectos como C/C++:

![image](https://github.com/sisoputnfrba/foro/assets/39303639/d2292ab3-9319-4789-b3f1-e25acd01b6ad)

Esta imagen la pueden encontrar acá, junto con la guía completa de cómo hacer el setup inicial: https://docs.utnso.com.ar/primeros-pasos/tp0#etapa-1-setup-inicial

Saludos

**Comment by RaniAgus** [comment]
PD: Si han tenido problemas para sacar capturas de pantalla les aconsejo revisar #2890 👍🏻

**Comment by iago64** [comment]
@chen-angela Pudiste resolver el inconveniente? ¿Te sirvió la respuesta de Agus?

**Comment by iago64** [comment]
Buenisimo! Por favor no se olviden de cerrar los issues 😊
