### ISSUE TITLE
Uso de hilos en Kernel

### ISSUE THREAD

**Issue by FacuD** [sisoputnfrba/foro#2949]
Buenas, nos surgio la duda de donde implementar los hilos en el modulo Kernel, porque en el enunciado dice: 
>> Lineamiento e Implementación
>>> Este módulo deberá mantener una conexión activa con la CPU, la Memoria, File System y las diferentes consolas que se conecten. Para ello, deberá implementarse mediante una estrategia de **múltiples hilos de ejecución**.

En un principio pensamos, del lado de kernel, crear un hilo por cada consola. Pero en #2940 @LeandroCarbajales sugirio: 

> En un hilo pueden esperar conexiones de consolas nuevas accept(), crear su PCB (y quizás guardar su socket en el mismo) y agregarlo a una lista o cola NEW.

Por lo tanto no sabriamos bien donde conviene usarlos, quizas cuando hagamos la planificacion?

Gracias!

**Comment by LeandroCarbajales** [comment]
Buenas!
Exactamente, seguramente toda la parte de planificación (de largo y corto plazo) quieran que se efectúen concurrentemente mientras siguen esperando conexiones de más consolas. Otro ejemplo podría ser para esperar una cantidad de tiempo definida o algún evento antes de desbloquear a un proceso en particular.
Cabe aclarar que esta no es una implementación obligatoria, y que el mismo comportamiento se podría dar teniendo un hilo por cada consola, pero en mi opinión eso les dificultaría más el desarrollo del trabajo.

Les sirve la respuesta?

**Comment by iago64** [comment]
Buenas @FacuD!

Te sirvió la respuesta de Lean? podemos ayudarte con algo mas?

Saludos.-

**Comment by FacuD** [comment]
Buenas, nos **re** sirvio la respuesta, gracias!

Saludos.
