### ISSUE TITLE
Duda con respecto al Segmentation Fault

### ISSUE THREAD

**Issue by FelipeAlborch** [sisoputnfrba/foro#2950]
Buenas! Encarando la parte de la MMU en CPU, en una parte del enunciado dice:

"En caso de que el desplazamiento dentro del segmento (desplazamiento_segmento) sumado al tamaño a leer / escribir, sea mayor al tamaño del segmento, deberá devolverse el Contexto de Ejecución al Kernel para que este lo finalice con motivo de Error: Segmentation Fault (SEG_FAULT)."

Mi duda con respecto a esto es si yo directamente para realizar esta verificación debería tomar en cuenta el tamaño máximo de segmento que me dan por archivo de configuración o si debería sacar ese tamaño de otro lugar

**Comment by LeandroCarbajales** [comment]
Buenas!
El chequeo debería hacerse con respecto al tamaño de ese segmento en particular (el que se está intentando acceder), el cual debería estar en la tabla de segmentos.
El tamaño máximo definido por configuración sirve para el cálculo de traducción de direcciones porque justamente es un máximo, pero los segmentos pueden ser más chicos.

Aclara la duda?
Saludos!
      Lean

**Comment by FelipeAlborch** [comment]
Hola Lean, sisi, me sirve mucho la respuesta, muchas gracias!!

**Comment by iago64** [comment]
Buenas! Si la respuesta resuelve las dudas, no se olviden de cerrar los issuees 👮
