### ISSUE TITLE
Lectura de PUERTOS del .config

### ISSUE THREAD

**Issue by Hamamura-S** [sisoputnfrba/foro#2951]
Hola, estabamos pensando en generalizar las funciones del tp0 para iniciar el servidor y sus auxilliares dependiendo del puerto de escucha. El problema es que todas ellas utilizan el PUERTO como un string, y el enunciado dice que los puertos son numéricos. Sería incorrecto levantar el puerto del .config con `config_get_string_value`?

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va?

Sip, a diferencia de otros formatos como JSON en donde esto:
```json
{
    "PUERTO": 8008
}
```
...es distinto de esto:
```json
{
    "PUERTO": "8008"
}
```
...para los configs no deben preocuparse por el tipo, ya que siempre se trata de un string:
```
PUERTO=8008
```

Que, incluso como verán en [la implementación de `config_get_int_value()`](https://github.com/sisoputnfrba/so-commons-library/blob/af8458ff77bb2b7e095a1c4ff97c9f491df27a62/src/commons/config.c#L78-L81), se lee como tal y se parsea al tipo correspondiente, por lo que pueden directamente usar `config_get_string_value()` si lo que necesitan es un string.

Saludos
