### ISSUE TITLE
Duda con los pedidos a FileSystem desde el Kernel.

### ISSUE THREAD

**Issue by FacundoPiaggio** [sisoputnfrba/foro#2952]
Buenas!
La duda que tenemos es respecto a los diferentes pedidos que se le hacen al FileSystem por parte del kernel.
Principalmente F_TRUNCATE, F_READ_ y F_WRITE. En estas 3 mencionan que los procesos deben mantenerse en estado "Bloqueado" hasta que el FileSystem finalice la operacion.

¿Mientras un proceso esta bloqueado, podría venir otro proceso y hacer otro pedido al FileSystem, de manera tal que se tengan que ejecutar mas de una operacion de FileSystem en paralelo?

**Comment by RaniAgus** [comment]
¡Buenas! 

Como comentó Lean en https://github.com/sisoputnfrba/foro/issues/2943#issuecomment-1536850075, la idea es que ejecute una operación después de otra, y es un punto que tendremos en cuenta para aclarar en la próxima revisión del enunciado.

Saludos

**Comment by FacundoPiaggio** [comment]
Había visto el issue, pero quería estar seguro de que había entendido correctamente.
Muchas gracias agus!
