### ISSUE TITLE
Calculo de la dirección física de un segmento

### ISSUE THREAD

**Issue by FacundoPiaggio** [sisoputnfrba/foro#2953]
Buenas!

Entiendo que la dirección lógica de un segmento esta formada por: [Nro Segmento | Desplazamiento].

Y si no me equivoco conceptualmente, para traducirla a dirección física, es: DF = Base del segmento + Desplazamiento (offset)

¿El cpu, para hacer obtener la direccion fisica, de donde saca la base del segmento que esta intentando acceder?

¿La tabla de segmentos forma parte del contexto de ejecución que le envía el kernel, y accede a través de ella?
¿Le pide la base del segmento X, al kernel, y este se la da?
¿Le pide la base a la memoria?

**Comment by RaniAgus** [comment]
¡Buenas! 

La tabla de segmentos forma parte del contexto de ejecución que le envía el Kernel a la CPU, por lo que éste último accede a la base través de ella.

Saludos

**Comment by FacundoPiaggio** [comment]
Excelente agus, muchas gracias!
