### ISSUE TITLE
Concepto de la funcion YIELD

### ISSUE THREAD

**Issue by GonzaBena** [sisoputnfrba/foro#2954]
Necesito ayuda para entender que debería hacer la función yield. Tengo entendido por otra issue que necesitaría usar las instrucciones, program_counter, registros de la CPU y la tabla de segmentos de la pcb pero no sabría que necesitaría hacer con eso.

**Comment by iago64** [comment]
Buenas!

La instrucción YIELD del TP lo que hace es desalojar el proceso de la CPU.
Podes interpretarlo como que el proceso es buena onda y quiere dejar que otros ejecuten tambien.

Saludos.-

**Comment by iago64** [comment]
@GonzaBena Cómo va?

Teniendo en cuenta la nueva version del enunciado, te cierra mas la idea de YIELD? Necesitas ayuda con algo mas?

Saludos.-

**Comment by GonzaBena** [comment]
Acabo de leer el nuevo enunciado y no veo que hayan agregado Información sobre yield.
Sin embargo entiendo que lo que hace yield es cambiar los punteros para que apunten a la siguiente instrucción de otro proceso no?

**Comment by iago64** [comment]
Buenas!

YIELD lo que hace es sacar al proceso que está ejecutando de la CPU, lo que aclaramos en el enunciado es que si están en HRRN, tienen que volver a calcular el estimado.

Poniéndolo en un ejemplo, vos tenes lo siguiente:
READY: P2, P3
EXEC: P1

P1 ejecuta la instrucción YIELD. 
Entonces P1 sale de EXEC y desaloja la CPU.
Entra a ejecutar P2 que era el primero en ready y la cola de ready queda con P3 y P1
Resultado:
EXEC: P2
READY: P3, P1

Saludos.-

**Comment by fedecassina** [comment]
Buenas! Con mi grupo estamos con la misma duda, pero con la planificación FIFO, como funcionaria YIELD, me podrías dar un ejemplo como el de HRRN anterior. Lo que entendemos es que lo desalojamos, pero después lo tenemos que ejecutar devuelta?!

**Comment by iago64** [comment]
Buenas!

En el caso de HRRN lo que tienen que hacer es volver a ejecutar la estimación y recien ahí en base a esa nueva estimación van a tener que ver quien va a ejecutar y puede pasar que tenga que volver a ejecutar el mismo o que ejecute otro de la lista de ready.

En el caso de FIFO es el mas simple porque desalojan y va al final de la cola de ready :wink:

Saludos.-

**Comment by LeandroCarbajales** [comment]
Para agregar a la respuesta de @iago64 cito al enunciado:

> Al recibir de CPU una instrucción YIELD, el proceso será enviado al final de la cola READY.
En caso de utilizar el algoritmo HRRN, se deberá además calcular un nuevo estimado para su próxima ráfaga utilizando la fórmula de promedio ponderado vista en clases.

Es decir, no importa el algoritmo de planificación, el proceso se va al final de la cola READY (como muestra el ejemplo que dió más arriba justamente sobre  cómo se comportaría el planificador FIFO). Se aclara que para el caso de HRRN deberían también estimarle una nueva ráfaga, de lo contrario no podrían replanificar.

**Comment by ezequielmalfonso** [comment]
Muchas gracias, nos re sirvió la respuesta.

**Comment by iago64** [comment]
@GonzaBena Te quedo claro cómo funciona YIELD? Necesitas que aclaremos algo más?

**Comment by GonzaBena** [comment]
Creo que me quedo claro muchas gracias

**Comment by LeandroCarbajales** [comment]
Recuerden que pueden cerrar el issue cuando la duda quedó resuelta :)
