### ISSUE TITLE
Consulta Response Ratio de HRRN.

### ISSUE THREAD

**Issue by jocarrizo** [sisoputnfrba/foro#2955]
Buenas tardes, queríamos consultar con mi grupo acerca del calculo de RR para la plani del algoritmo HRRN.

Al usar temporal tenemos que parar el timer y obtener el resultado del calculo. Lo que genera duda es que entre calculo y calculo de proceso puede llegar a haber un desfasaje que puede provocar inconsistencia en el resultado. NO sabemos como resolver el asunto o si es siquiera relevante.

Encontramos algo del 2018 que dice que lo calculemos todo seguido pero la duda sigue.

Ante todo muchas gracias.

**Comment by iago64** [comment]
Buenas! Cómo va?

En el caso del tp del 2018 no creo que les sirva de mucho porque son TPs diferentes.
En este tp la idea es que uds calculen los tiempos al momoento que reciben de la CPU el contexto de ejecución que se desaloja y con eso ya van a tener el nuevo estimado, recuerden que puedne extender la estructura del PCB para guardar la info que necesiten para calcular el RR del proceso :wink:

Saludos.-

**Comment by iago64** [comment]
@jocarrizo Cómo va? 

Te sirvió mi respuesta? Necesitas ayuda con algo mas?

Saludos.-

**Comment by jocarrizo** [comment]
Hola, disculpa que no haya respondido no me habia llegado la notificacion. Si todo resuelto muchas gracias!
