### ISSUE TITLE
Rompen los tests de la commons

### ISSUE THREAD

**Issue by atononi** [sisoputnfrba/foro#2956]
Buenas, como andan?
Estoy intentando realizar tests con CSpecs pero al ejecutarlos me tira error con las commons.

mi test:
```
#include <stdlib.h>
#include <unistd.h>
#include <stdio.h>
#include <cspecs/cspec.h>
#include "../include/consola_config.h"
#include "../../shared/include/settings.h"

context(config_test)
{
    describe("config inexistente")
    {
        char *path = "/home/utnso/tp-2023-1c-LaResistenciaSO/consola/configuracion.cfg";
        t_log *logger = iniciar_logger("consola.log", "CONSOLA");

        it("devuelve NULL")
        {
            t_consola_config *consola_config = consola_leer_configuracion(logger, path);
            should_ptr(consola_config) be null;
        } end
        
    } end
}
```

En consola realizo: **gcc test_config.c -o pruebas -lcspecs** y me arroja lo siguiente:

> 
> In file included from test_config.c:4:0:
> /usr/include/commons/string.h:177:45: error: expected declaration specifiers or ‘...’ before ‘}’ token
>   bool    string_ends_with(char* text, char* end);
>                                              ^
> /usr/include/commons/string.h:177:45: error: expected ‘;’, ‘,’ or ‘)’ before ‘}’ token
> /usr/include/commons/string.h:177:45: error: expected identifier or ‘(’ before ‘)’ token
>   bool    string_ends_with(char* text, char* end);
>                                              ^
> In file included from ../../shared/include/settings.h:6:0,
>                  from test_config.c:6:
> /usr/include/commons/string.h:177:48: error: expected identifier or ‘(’ before ‘)’ token
>   bool    string_ends_with(char* text, char* end);

tengo las commons actualizadas (incluso volví a clonar nuevamente e instalar). También tengo CSpecs instalado

**Comment by atononi** [comment]
los sombreritos (^) me los marca en el parámetro **end** para ambos casos

**Comment by atononi** [comment]
update: también intente ejecutar linkeando las commons con -lcommons pero obtuve el mismo resultado

**Comment by atononi** [comment]
por el momento creo que lo solucione. Cree una regla con Makefile para que me compile todo el proyecto y ejecute solo los tests

**Comment by RaniAgus** [comment]
¡Buenas @atononi! 

Me sumo para comentar la solución al problema, ya que recuerdo que a otros grupos les pasó pero no encontré ningún issue al respecto, así si alguien más se encuentra con este issue lo va a poder solucionar. 

Esta línea:
```
#include <cspecs/cspec.h>
```
debe ser el último include del archivo, así el compilador no usa la macro `end` a la hora de leer los headers de las commons.

Saludos
