### ISSUE TITLE
Error al recibir el programa desde el Kernel

### ISSUE THREAD

**Issue by MiltonMartorello** [sisoputnfrba/foro#2957]
Buenas, estoy teniendo un problema que hace semanas no puedo resolver y ya me estoy rindiendo.
El problema viene con la interfaz entre Consola y Kernel

### 🐛 Cómo reproducir el error
1. Consola envía operación nro 5(CONSOLA), para realizar un handshake. OK
2. Kernel recibe operación nro 5 y devuelve un mensaje "Handshake Consola-Kernel" a consola. OK
3. Consola envía el programa con un stream que tiene como primeros 4 bytes la operación 6(PROGRAMA). ERROR

Resultado esperado: Recibida op code 6:

Resultado obtenido:
[INFO] 17:03:20:127 kernel/(109794:109794): Recibida op code: 5
[INFO] 17:03:20:131 kernel/(109794:109794): Iniciado hilo de escucha con consola en socket 4
**[INFO] 17:03:20:134 kernel/(109794:109794): Recibida op code: -1**

### Alternativas probadas.
Probé desarmar el punto 3 reutilizando la función enviar_operacion y que solo envié la operación número 6 y aun así falla.
Probé también sacar la función del hilo y que se ejecute instantaneamente luego de enviar le mensaje de handshake en la misma función y sigue pasando el error.

No termino de entender como la misma función manda bien el mensaje una vez y a la segunda no y ya estoy medio frustrado y falto de ideas para arreglar este error.

Muchas gracias

### 📝 Código relevante
```
void enviar_operacion(int socket, int operacion ) {
    void *buffer = malloc(sizeof(int));
    memcpy(buffer, &operacion, sizeof(int));
    send(socket, buffer, sizeof(int), 0);

    free(buffer);
}

int recibir_operacion(int socket_cliente)
{
	int cod_op;
	int errorno = recv(socket_cliente, &cod_op, sizeof(int), MSG_WAITALL);
	if( errorno > 0)
		return cod_op;
	else
	{
		close(socket_cliente);
		return errorno;
	}
}

dentro del main del kernel {
log_info(logger, "Esperando un cliente nuevo de la consola...");
int socket_consola = esperar_cliente(socket_kernel, logger);
log_info(logger, "Entró una consola con el socket: %d", socket_consola);

int modulo = recibir_operacion(socket_consola); -- log que deuelve op code 5
log_info(logger, "Recibida op code: %d", modulo);
	switch (modulo) {
		case CONSOLA:

			enviar_mensaje("Handshake Consola-Kernel", socket_consola, logger);
			args->socket = socket_kernel;
			args->log = logger;
			procesar_consola(args);
}

void procesar_consola(void *args_hilo) {

	t_args_hilo_cliente *args = (t_args_hilo_cliente*) args_hilo;

	int socket_consola = args->socket;
	t_log* logger = args->log;
	log_info(logger, "Iniciado hilo de escucha con consola en socket %d", socket_consola);
	int cod_op = recibir_operacion(socket_consola);  -- log que deuelve op code -1
        log_info(logger, "Recibida op code: %d", cod_op);
	...
```

**Comment by ncoen97** [comment]
Buenas!

A simple vista no veo ningun error en el código que mandaron, pero podemos intentar descartar algunas cosas.
- Primero me fijaría si están haciendo algun `close()` fuera del hilo de escucha de consola, esto les puede pasar cuando no tienen en cuenta que el código del hilo que llama a `pthread_create()` sigue corriendo mientras el nuevo hilo corre en paralelo.
- Tengo entendido que el return de `recv()` no es el errno, sino el numero de bytes recibidos o -1 en caso de error. Intenten [imprimir el errno](https://stackoverflow.com/questions/34854634/getting-error-number-returned-by-recv-function) así nos da alguna pista de qué puede estar pasando.
- Del lado de consola, el `send()` qué está retornando? Debería ser un 4, que es la cantidad de bytes enviada.

Cuando tengan estos puntos seguimos viendo cuál puede ser el problema.

Saludos!

**Comment by LeandroCarbajales** [comment]
Buenas!
Para agregar a la respuesta de @ncoen97 veo en el código que su función `recibir_operacion` retorna la variable en la que reciben el código de operación solamente cuando el recv retorna sin error, se está logueando -1 porque justamente está devolviendo -1 debido a un error al ejecutarlo como indicó Nico.
Por otro lado me fijaría también si no están cerrando la conexión del lado de la consola (sea por ejecutar close o porque finaliza la misma) antes de que el Kernel ejecute el recv

Saludos!
        Lean

**Comment by MiltonMartorello** [comment]
Hola, muchas gracias por sus respuestas.
Como quedó el código tenemos un solo hilo corriendo para descartar alternativas de paralelismo. Sigue sin funcionar.
close() hay 2 solos, 1 en caso de que falle el recv justamente y otro cuando termina el server del kernel.
Probé agregar lo que adjuntaron y sirvió para detectar el tipo de error el cual es el siguiente:

`recv: Transport endpoint is not connected (107)
`

Interpretando que se trata de un problema de conexión como dijo Lean, intenté loguear el estado con el siguiente código y no parece detectar ningun error. Pero luego en el recv que esta en la fila siguiente a validar_conexion, falla con el error 107. 

```
int validar_conexion(int socket) {
	int optval;
	socklen_t optlen = sizeof(optval);
	int err = getsockopt(socket, SOL_SOCKET, SO_ERROR, &optval, &optlen);
	if (err == 0) {
	    if (optval != 0) {
	        // hay un error de conexión pendiente
	        fprintf(stderr, "Error de conexión pendiente: %s\n", strerror(optval));
	        return -1;
	    }
	} else {
	    // hubo un error al obtener el estado de la conexión
	    fprintf(stderr, "Error al obtener el estado de la conexión: %s\n", strerror(errno));
	    return -1;
	}
	printf("Socket OK\n");
	return 1;
}
```

Vi que hay sugerencias en la red de hacer un select para espabilar al socket pero me parece muy raro ya meterme ahí, no vi que se lo mencione en otros issues closed que vi, no creí que tuviese que meter tanta mano con los sockets pero si es por ahí lo voy a tener que investigar, no tengo mucha idea de como seguir.
Gracias!

**Comment by LeandroCarbajales** [comment]
Buenas!
Acabo de ver que al recibir un código de operación por primera vez utilizan correctamente el socket que se acaba de crear para la conexión con esa consola `socket_consola` en la línea: `int modulo = recibir_operacion(socket_consola); -- log que deuelve op code 5`
En cambio, al crear un hilo para atender a esa consola en particular, le pasan como argumento el socket que espera conexiones `socket_kernel` en esta línea: `args->socket = socket_kernel;`

**Comment by MiltonMartorello** [comment]
Dios mío que vergüenza, era eso. Gracias @LeandroCarbajales. Una vista de afuera es clave
