### ISSUE TITLE
Serialización de lista de instrucciones

### ISSUE THREAD

**Issue by Martin-Fedorenko** [sisoputnfrba/foro#2958]
Buenas! Intentando serializar y deserializar la lista de instrucciones (un t_list) me tope con el problema de que no se deserializa lo mismo que serialice. Usualemente se devuelven valores erraticos y si la instruccion (un char*) es demasiado larga directamente muestra segmentation fault. Para la serialización seguí la guía que esta en la página de sistemas operativos.

### 📝 Código relevante

Estan son las dos funciones que utilizó:

```
t_paquete* serializar_instrucciones(t_list* lista_ins){
    t_paquete* paquete = malloc(sizeof(t_paquete));
    paquete->buffer = malloc(sizeof(t_buffer));
   
    int offset = 0;
    void* instruccion;
    int tam_instruccion = 0;
    int tam_lista = 0;
    int cantidad_instrucciones = list_size(lista_ins);

    //sumo los tamaños de las distintas instrucciones para saber cuanto pesan en total
    for(int i=0; i<cantidad_instrucciones; i++){
        instruccion = list_get(lista_ins, i);
        tam_lista += string_length(instruccion)/sizeof(char);
    }

    //calculo el peso total del stream
    //todas las instrucciones + los tamaños de cada una + el tamaño total del stream
    int bytes = tam_lista + (cantidad_instrucciones + 1)*sizeof(int);
    paquete->buffer->size = bytes;
    void* stream = malloc(bytes);

    //serializo, primero el tamaño del stream, luego el tamaño de una instruccion y la instruccion
    memcpy(stream + offset, &cantidad_instrucciones, sizeof(int));
    offset += sizeof(int);

    for(int i=0; i<cantidad_instrucciones; i++){
        instruccion = list_get(lista_ins,i);
        tam_instruccion = string_length(instruccion);

        memcpy(stream + offset, &tam_instruccion, sizeof(int));
        offset += sizeof(int);
        memcpy(stream + offset, instruccion, tam_instruccion);
        offset += tam_instruccion;
    }

    paquete->buffer->stream = stream;

    return paquete;
}
```

```
t_list* deserializar_instrucciones(t_buffer* buffer, t_log* logger){
    t_list* lista_ins = list_create();
    void* stream = buffer->stream;

    int tam_instruccion;
    void* instruccion;
    int cantidad_instrucciones;

    //deserializo primero el tamaño del stream
    memcpy(&cantidad_instrucciones, stream, sizeof(int));
    stream += sizeof(int);

    log_info(logger, "cant_instrucciones: %d", cantidad_instrucciones);

    // Deserializo tamaños de cada instruccion y la instruccion
    for(int i=0; i<cantidad_instrucciones; i++){
        memcpy(&tam_instruccion, stream, sizeof(int));
        stream += sizeof(int);

        log_info(logger, "tam_instruccion %d :%d", i, tam_instruccion);

        instruccion = malloc(tam_instruccion);
        memcpy(instruccion, stream , tam_instruccion);
        stream += sizeof(tam_instruccion);
        log_info(logger, "instruccion %d : %s", i, (char*)instruccion);
        
        //agrego la instruccion a la lista que luego retornare 
        list_add(lista_ins, (void*)instruccion);
        free(instruccion);
    }

    return lista_ins;
}

```

### 💻 Logs

Asimismo dejo el log que tengo:
![image](https://user-images.githubusercontent.com/67556470/236698096-43a82446-67db-4f14-91fa-b8efaedcdf32.png)

**Comment by iago64** [comment]
Buenas! Cómo va?

En principio creo que el problema que estas teniendo viene dado por varios factores:

1.- Al imprimir un string, tenes que asegurarte de que tenga el '\0', caso contrario, la función de imprimir va a seguir buscandolo y en el mejor de los casos, te imprime basura, en el peor tenes un seg fault.

2.- Cuando te encuentres con un segfault, lo primero que tenes que hacer levantar tu tp con valgrind para tener toda la info de como fue que se dió el segfault.

3.- Por las dudas, debuguea el código, para validar primero lo del '\0' y segundo que estes realmente desplazandote como debes en el stream.

Saludos.-

**Comment by iago64** [comment]
Buenas @Martin-Fedorenko Cómo va?

Los comentarios que te deje, te fueron utiles para encontrar el error? Necesitas alguna ayuda extra?

Saludos.-

**Comment by Martin-Fedorenko** [comment]
Buenas noches! Disculpa la tardanza. Al final desistí de serializar y deserializar un t_list y decidí mandar simplemente un char* con las instrucciones, sin embargo los problemas perduran.

Corrí valgrind y creo que lo siguente es lo mas relevante que me indica (ya que es el unico lugar donde realmente pierde memoria el programa):
![image](https://github.com/sisoputnfrba/foro/assets/67556470/43625e22-6928-4cf6-8151-0e030045250d)
![image](https://github.com/sisoputnfrba/foro/assets/67556470/bd2a6195-b39c-4c94-9165-7b671bc6dfc1)

No obstante, no soy capaz de encontrar cual es el error que provoca la perdida de memoria.

Las nuevas funciones de serialización que uso son estas (casi idénticas a las anteriores y agrego procesar_conexion():

`t_paquete* serializar_instrucciones(char* lista_ins){
    t_paquete* paquete = malloc(sizeof(t_paquete));
    paquete->buffer = malloc(sizeof(t_buffer));
    
    int tam_lista = string_length(lista_ins);
    int offset = 0;

    int bytes = tam_lista + sizeof(int) + 1;
    paquete->buffer->size = bytes;
    void* stream = malloc(bytes);

    memcpy(stream + offset, &tam_lista, sizeof(int));
    offset += sizeof(int);
    memcpy(stream + offset, lista_ins, tam_lista + 1);
    
    paquete->buffer->stream = stream;

    return paquete;
}

char* deserializar_instrucciones(t_buffer* buffer){
    char* lista_ins;
    void* stream = buffer->stream;

    int tam_lista;

    memcpy(&tam_lista, stream, sizeof(int));
    stream += sizeof(int);
    lista_ins = malloc(tam_lista);
    memcpy(lista_ins, stream, tam_lista);
    return lista_ins;
}

void procesar_conexion(void* socket_cliente){
	int cliente = *((int*)socket_cliente);

	t_paquete* paquete = recibir_paquete(cliente);
	char* lista_ins = deserializar_instrucciones(paquete->buffer);
	log_info(logger_kernel, "opcode: %d", paquete->opcode);
	eliminar_paquete(paquete);

	log_info(logger_kernel,"la lista es: %s", lista_ins);
`

De esta manera creo los char* que voy a mandar:

`char* armar_lista_instrucciones(char* pathArchivo, t_log* logger){
    char* lista_ins = string_new();

    FILE* archivo = fopen(pathArchivo, "r");
    if (archivo == NULL) {
        log_error(logger,"No se pudo abrir el archivo.");
        exit(EXIT_FAILURE);
        }
    char linea[256];
    while (fgets(linea,sizeof(linea),archivo)){
        string_append(&lista_ins, linea);
    }

    int tam = strlen(lista_ins);
    lista_ins[tam+1] = '\0';

    fclose(archivo);
    return lista_ins;
}`

Por ultimo, una consulta, es malo tener mucha memoria still reachable?

**Comment by Martin-Fedorenko** [comment]
Al final lo que me faltaba era un free(lista_ins) en procesar_conexion, por eso había un memory leak 🙄
