### ISSUE TITLE
Basura en comunicacion entre modulos

### ISSUE THREAD

**Issue by lucasdeferrari** [sisoputnfrba/foro#2959]
Buenas, queria consultar porque desde el tp0 que cuando enviamos paquetes entre 2 modulos hay veces que tenemos una "basura" al final de cada renglon

### 🔎 Búsqueda en foros
Estuve leyendo otros issues sobre el tema y vi que comentaban que a veces quedaba en basura en el buffer por no poner el '/0' al final de cada string, pero investigando un poco vi que la funcion strcpy (la cual utilizamos) agrega automaticamente este caracter al final de cada string, asi que no sabria realmente donde esta el probema

### 📝 Código relevante
El codigo que comparto es del agregado de los strings de consola a una lista que seria la que linea por linea enviamos al kernel

```
while (fgets(linea, sizeof(linea), archivo) != NULL) {
			char* nueva_linea = (char*)malloc(strlen(linea));
			strcpy(nueva_linea, linea);
			insertar(&cabeza, nueva_linea);
		}
```
```
void insertar(Nodo** cabeza, char* linea) {
    Nodo* nuevo_nodo = (Nodo*)malloc(sizeof(Nodo));
    nuevo_nodo->linea = linea;
    nuevo_nodo->siguiente = NULL;

    Nodo* ultimo = *cabeza;

    if (*cabeza == NULL) {
        *cabeza = nuevo_nodo;
        return;
    }

    while (ultimo->siguiente != NULL) {
        ultimo = ultimo->siguiente;
    }

    ultimo->siguiente= nuevo_nodo;
    return;
}
```

### 💻 Logs
Este es el archivo de prueba .txt que estoy utilizando:

```
hola soy lucas
sistemas operativos
2023
universidad tecnologica nacional
ay
!*.:-_ 
```
Y esto es lo que reproduce el Kernel cuando se le envia ese archivo:

![image](https://user-images.githubusercontent.com/102559642/236988579-13a3bd30-8829-4a3c-b891-d510318b9a8b.png)

Perdon por enviar una imagen, pero si lo copiaba y pegaba no se copiaban todos los caracteres raros.
Desde ya, muchas gracias.

**Comment by iago64** [comment]
Buenas! Cómo va?

Ojo con asumir que `strcpy()` agrega un `'\0'`, porque justamente, strcpy, lo que hace es copiar del string de origen y lo lee hasta que encuentra un `'\0'`, con lo cual, si vos originalmente no se lo estas pasando, `strcpy()` te va a leer basura y la va a copiar.

De hecho si vemos la definición del [man de `strcpy()`](https://man7.org/linux/man-pages/man3/strcpy.3.html) nos dice lo siguiente:
> The strcpy() function copies the string pointed to by src, including the terminating null byte ('\0')

Con lo cual, cuidado con lo que le pasan a las funciones que empiezan con str, porque si no tienen el delimitador del `'\0'` les va a agregar basura siempre.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Para sumar a lo que dijo Dami, otro problema que están teniendo está en la siguiente línea:
```c
char* nueva_linea = (char*)malloc(strlen(linea));
```
Si bien más adelante usen `strcpy()` para copiar lo de `linea` a `nueva_linea`, no están contemplando ese caracter extra al reservar memoria con `malloc()`. Lo correcto sería hacer lo siguiente:

```c
char* nueva_linea = malloc(strlen(linea) + 1);
```

Por otro lado, les recomiendo ampliamente utilizar las funciones de las [commons](https://faq.utnso.com.ar/commons), las cuales ya tienen resueltos gran parte de los problemas que se pueden encontrar al manejar estructuras de datos:

- [`<commons/string.h>`](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/string.h) tiene funciones para manejo de strings usando memoria dinámica, como por ejemplo `string_duplicate()` para duplicar un string.
- [`<commons/collections/list.h>`](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/collections/list.h) tiene una implementación de listas ampliamente testeada y con funciones de alto nivel como `filter`, `map`, etc., por lo que no necesitan desarrollar su propia implementación con `void insertar(Nodo** cabeza, char* linea)`
- También tenemos implementadas otros tipos abstractos de datos como [diccionarios/mapas](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/collections/dictionary.h),  [arrays de bits](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/bitarray.h) o [manejo de timestamps](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/temporal.h), que seguramente les ahorrará tiempo de desarrollo en el TP.

Saludos

**Comment by lucasdeferrari** [comment]
Genial muchas gracias a los dos! Voy a probar con lo que me dijeron
