### ISSUE TITLE
Consulta por la llegada de un proceso a ready

### ISSUE THREAD

**Issue by FacundoPiaggio** [sisoputnfrba/foro#2960]
Buenas!

En el enunciado se plantea lo siguiente:

"En caso de que el grado máximo de multiprogramación lo permita, los procesos pasarán al estado READY, enviando un mensaje al módulo Memoria para que inicialice sus estructuras necesarias y obtenga la tabla de segmentos inicial que deberá ser almacenada en el PCB"

¿No debería ser al revés? es decir, una vez que tenes un proceso en NEW, no debería esperar a tener todo lo necesario para ejecutar y ser "admitido" de NEW -> READY.
¿o es exactamente esto lo que plantea el enunciado, y yo lo estoy entendiendo mal?
Yo lo que entiendo es: Tengo un proceso en NEW, si la multiprogramacion me permite moverlo a READY lo hago, y luego de moverlo, envio el mensaje a memoria para que me devuelva la tabla de segmentos.

Hago esta consulta principalmente por lo que se ve en la teoría, que un proceso en NEW no es admitido a READY hasta que tiene todo lo que necesita (memoria, por ejemplo) para ejecutar.

**Comment by LeandroCarbajales** [comment]
Buenas!

> es decir, una vez que tenes un proceso en NEW, no debería esperar a tener todo lo necesario para ejecutar y ser "admitido" de NEW -> READY.

Estás en lo correcto y es lo que intenta plantear el enunciado, por un lado, un proceso solamente debería ser admitido en READY si el grado de multiprogramación lo permite. Por otro lado, también debería inicializarse en Memoria antes de ser encolado en READY, pero la idea es que en este TP esto último no es una limitación extra al grado de multiprogramación ya que no debería haber ningún caso en que un proceso no pueda inicializarse en Memoria.
El enunciado a lo que apunta es que, si el grado de multiprogramación no lo permite, ni siquiera debería intentar inicializarse en Memoria.

Queda más clara la idea?
Saludos!
     Lean

**Comment by FacundoPiaggio** [comment]
Excelente! creo que entiendo.

Pero solo para estar seguro, la secuencia de pasos sería algo así:

Tengo un pcb en NEW -> Si la el grado de multiprogramacion lo permite -> pido la tabla de segmentos a memoria, que se que va a poder inicializarlo sin problemas -> Una vez que la tengo, muevo el pcb a READY.

Muchas gracias lean!

**Comment by LeandroCarbajales** [comment]
Exacto :)

**Comment by FacundoPiaggio** [comment]
Buenisimo lean! Muchas gracias! :D
