### ISSUE TITLE
Traduccion direccion logica a fisica

### ISSUE THREAD

**Issue by damiangluk** [sisoputnfrba/foro#2962]
#### Consulta
Hola, con mi grupo tenemos una duda sobre el enunciado y la implementacion de la traduccion de direccion logica a fisica.
Queriamos saber si estamos bien o nos desviamos de lo que dice el enunciado, porque en ningun momento utilizamos los calculos mencionados como floor, la division y el resto.
Hicimos lo siguiente:

#### Estructuras
```
typedef struct
{
    char AX[4], BX[4], CX[4], DX[4];
    char EAX[8], EBX[8], ECX[8], EDX[8];
    char RAX[16], RBX[16], RCX[16], RDX[16];
} Registros;

typedef struct
{   
    int Id;
    int* DireccionBase;
    int Tamanio;
} Segmento;

typedef struct
{
    int Id;
    char* Nombre;
    int* Direccion;
} Archivo;

typedef enum
{
    NEW,
    READY,
    BLOCK,
    EXEC,
    EXIT
} Estado;

typedef struct
{
    int Size;
    int PID; // Process ID
    t_list* Instrucciones; // Lista de Char*
    int PC; // Program Counter: Proxima instruccion a ejecutar
    Registros* RegistrosCPU;
    t_list* TablaSegmentos; // Lista de Segmento
    int EstimadoProximaRafaga;
    int TiempoLlegadaAReady;
    t_list* TablaArchivosAbiertos; // Lista de Archivo
    Estado Estado; 
} PCB;

typedef struct
{
    int NumeroSegmento;
    int Desplazamiento
} DireccionLogica;
```

#### Funciones
```
int* traducir_dir_logica_fisica() {
  Segmento* segmento = list_find(pcb->TablaSegmentos, equals);
  int* dirFisica = segmento->DireccionBase;
  dirFisica += dirLogica->Desplazamiento;

  if(dirFisica > (segmento->DireccionBase + segmento->Tamanio)) {
    log_error(logger, "PID: %d - Error SEG_FAULT- Segmento: %s - Offset: %s - Tamaño: %s", pcb->PID, segmento, dirLogica->Desplazamiento, segmento->Tamanio);
    return 0;
  }

  return dirFisica;
}

bool equals(Segmento *segmento) {
  return segmento->Id == dirLogica->NumeroSegmento;
}

```

### 📔 Citas del enunciado/videos
Enunciado TP - Página 18
> "A la hora de traducir direcciones lógicas a físicas, la CPU debe tomar en cuenta que el esquema de memoria del sistema es de Segmentación. Por lo tanto, las direcciones lógicas se compondrán de la siguiente manera:
[N° Segmento | Desplazamiento]
Estas traducciones, en los ejercicios prácticos que se ven en clases y se toman en los parciales, normalmente se hacen a partir de su representación en binario. Como en la realización del trabajo práctico es más cómodo utilizar operaciones aritméticas, la forma de realizar los cálculos sería más parecida a la siguiente:
num_segmento = floor(dir_logica / tam_max_segmento)
desplazamiento_segmento = dir_logica % tam_max_segmento
En caso de que el desplazamiento dentro del segmento (desplazamiento_segmento) sumado al tamaño a leer / escribir, sea mayor al tamaño del segmento, deberá devolverse el Contexto de Ejecución al Kernel para que este lo finalice con motivo de Error: Segmentation Fault (SEG_FAULT)."

**Comment by RaniAgus** [comment]
¡Buenas! La dirección lógica es número entero que viene parseado desde el archivo de instrucciones, por lo que no van a poder convertirlo a struct sin saber el tamaño máximo de segmento configurado en CPU.

Saludos

**Comment by damiangluk** [comment]
Buenisimo, quedo claro.
Muchas gracias.

**Comment by RaniAgus** [comment]
¡Buenísimo! Recuerden que pueden cerrar el issue una vez resuelta la duda 👍🏻
