### ISSUE TITLE
Manejo de hilos en memoria

### ISSUE THREAD

**Issue by MattP2001** [sisoputnfrba/foro#2963]
Buenas, tenemos una duda con el manejo de los hilos en la memoria. Cuando la memoria va recibiendo mensajes de kernel/fs/cpu que tiene que ejecutar operaciones como el leer/escribir/compactar/etc de memoria la idea es que lo maneje como fs, con la ultima actualizacion del enunciado, es decir con una cola fifo de mensajes o de otra manera?

Desde ya muchas gracias, Mati

**Comment by LeandroCarbajales** [comment]
Buenas!
No hay restricción al respecto, pueden manejar cada conexión [kernel, fs, cpu] con un hilo diferente y que esos mensajes se atiendan concurrentemente.

**Comment by MattP2001** [comment]
Perfecto, muchas gracias!!
