### ISSUE TITLE
Problema con struct 

### ISSUE THREAD

**Issue by chiaraberetta0** [sisoputnfrba/foro#2964]
Hola, estamos teniendo un problema con una estructura, no nos reconoce el tipo de dato al querer usarla en funciones.
tenemos un archivo .h (donde está declarada) y un .c donde también la usamos y no tenemos problema, por lo que el archivo .h esta bien importado.
Pero luego la queremos usar en otro .c y .h que no nos la reconocen. Estuvimos haciendo esto con un montón de estructuras en todo el resto del tp, que esta todo ok, entonces no sabemos que es lo que pasa. 
Todas nuestros proyectos están estructurados iguales con una carpeta src donde estan los .c y otra include donde estan los .h 
### 📝 Código relevante
```
Este error nos tira: 
unknown type name ‘t_pcb’	planificador.h	/kernel/include	line 44	C/C++ Problem

Lo importamos asi:  #include "../include/pcb.h"


```

**Comment by RaniAgus** [comment]
¡Buenas! ¿En todos los archivos en donde usan el `t_pcb` tienen puesto el `#include` arriba?

Por ejemplo, en `planificador.h`:

```c
// ... otros includes
#include "pcb.h" // No haría falta regresar a "../include", ya que ambos archivos están en esa carpeta

// ... otras funciones
int mi_funcion_que_recibe_un_pcb(t_pcb *pcb);
```

Y en el `planificador.c`:

```c
#include "../include/planificador.h" // Esto agrega todos los "#include" del .h acá arriba

int mi_funcion_que_recibe_un_pcb(t_pcb *pcb) {
    // ...
}
```

Saludos

**Comment by chiaraberetta0** [comment]
Gracias, el problema era otro pero ya lo resolvimos. Saludos!
