### ISSUE TITLE
Duda con el comando I/O

### ISSUE THREAD

**Issue by ezequielmalfonso** [sisoputnfrba/foro#2965]
Buenas, tenemos una duda con la instrucción I/O, cuando se ejecuta la misma y devuelve el contexto de ejecución al kernel, deberia ir a una cola de bloqueados por entrada/salida y luego de transcurrido ese tiempo pasar a la cola de ready, en caso de FIFO al final de la cola y en el caso de HRRN a la cola de ready para su re planificación?
Mientras tanto tiene que ejecutarse el siguiente procesos que le toque?
La duda que me surge es como implementar que este un determinado tiempo en al cola de bloqueado, no se si nos podrian dar un pista de como encararlo?

Gracias.-

**Comment by LeandroCarbajales** [comment]
Buenas!
Pueden utilizar las funciones [sleep ](https://linux.die.net/man/3/sleep) o [usleep](https://man7.org/linux/man-pages/man3/usleep.3.html) para esperar una determinada cantidad de tiempo en segundos o microsegundos respectivamente, probablemente esto quieran hacerlo en un hilo aparte.

**Comment by ezequielmalfonso** [comment]
Buenas, ah perfecto creí que estaba medio "prohibido usar sleep" si generamos un hilo separado con pthread_detach que segun entendí una vez realizado esto ya no se puede joinear por lo que una vez finalizado el tiempo lo liberamos.
Esta bien eso?

**Comment by LeandroCarbajales** [comment]
Buenas!
Por qué estaría prohibido usar sleep?
No necesitarías joinear el hilo si por ejemplo desde esa misma función reincorporás al proceso correspondiente a ready luego de hacer el sleep()

**Comment by ezequielmalfonso** [comment]
Buenas, no se de donde me quedo eso de no usar sleep.
Si lo hice así y ya esta funcionando la plani fifo para I/O.
Lo q hice para probar fue luego de levantar los modulos Memoria, CPU, FILESYSTEM y Kernel, abrí varias terminales y trate de enviar varias consolas lo mas rápido q pude y se llega a ver como, el orden de los procesos como se ejecutan.
Muchas gracias.

**Comment by LeandroCarbajales** [comment]
Genial,
Si la duda quedó resuelta podés cerrar el issue :)

**Comment by irinaperezg** [comment]
![image](https://github.com/sisoputnfrba/foro/assets/83139862/a217593a-cd0e-446d-99e8-73b4f705c337)
Hola! Me quedó una duda con respecto a esto, estaría bien hacerlo de esta manera? todavía no le agarro bien la mano a los hilos en código y me confunde un poco el orden, no se si está bien que el hilo ejecute entre los cambios de estado
![image](https://github.com/sisoputnfrba/foro/assets/83139862/788fcf28-7da0-4659-b34b-0b7c97916a9a)
más que nada el tema de que pasaría concurrentemente que se pasaría a ready no? aunque no haya terminado el hilo, pero si hago el join no se "bloquearia" el proceso no? 
no se si otra función debería llamar a ejecutar_proceso_io y esperar a que esta termine y recién ahí cambiar el estado

**Comment by ezequielmalfonso** [comment]
Buenas tardes, tengo una duda con el enunciado cuando habla del manejo de recursos:
>Manejo de Recursos
Los recursos del sistema vendrán indicados por medio del archivo de configuración, donde se encontrarán 2 variables con la información inicial de los mismos:
La primera llamada RECURSOS, la cual listará los nombres de los recursos disponibles en el sistema.
La segunda llamada INSTANCIAS_RECURSOS será la cantidad de instancias de cada recurso del sistema, y estarán ordenadas de acuerdo a la anterior lista (ver [ejemplo].
A la hora de recibir de la CPU un Contexto de Ejecución desplazado por WAIT, el Kernel deberá verificar primero que exista el recurso solicitado y en caso de que exista restarle 1 a la cantidad de instancias del mismo. En caso de que el número sea estrictamente menor a 0, el proceso que realizó WAIT se bloqueará en la cola de bloqueados correspondiente al recurso.

Entiendo que si:
>RECURSOS=[DISCO, RECURSO_1]
INSTANCIAS_RECURSOS=[1, 2]

Es una instancia del DISCO y dos instancias de RECURSO_1

No me queda claro que pasa con el proceso, cuando ejecuta el wait,  si tengo dos procesos, cuando llega al momento de ejecutar la instrucción WAIT, como el ejemplo el CPU envía el contexto al kernel y el kernel se fija si hay una o mas instancias entonces le avisa al cpu que lo ejecute (Seria imprimir en pantalla que se esta ejecutando el recurso en cuestión?)? Si es 0 que hace?
Y si es menor a cero lo envió a una cola de bloqueados, ahí la otra duda, tendría que tener una cola de bloqueados por cada Recurso? osea una cola para DISCO y otra para RECURSO_1? pero puede llagar que haber mas recursos que eso dos o ya son fijo?
Y  una vez que son desbloqueado lo envió a la cola READY?

Gracias.-

**Comment by LeandroCarbajales** [comment]
Buenas!
Citando el [readme](https://github.com/sisoputnfrba/foro/blob/master/README.md) que considero una buena norma de "convivencia":

> Por cada consulta que tengas, [buscá](https://github.com/sisoputnfrba/foro/issues?utf8=%E2%9C%93&q=is%3Aissue) si alguien hizo una pregunta similar previamente. Si la pregunta sigue abierta y vos tenés la misma duda, podés suscribirte a la duda con el botón de Subscribe bajo Notifications. Si la pregunta se encuentra cerrada y no resuelve completamente tu duda, no escribas en esa misma pregunta: anotá el número de issue para referirlo en tu nueva pregunta.

Les voy a pedir a ambos (por separado) que creen un nuevo issue ya que considero que son dudas distintas, tanto a la original, como entre sí.
Por otro lado, por default no nos llegan notificaciones sobre issues ya cerrados, en cambio sí nos llega cuando abren un nuevo issue, justamente para tener ordenado qué dudas aun no están resueltas.

Saludos!
      Lean

**Comment by ezequielmalfonso** [comment]
@LeandroCarbajales uh te pido mil disculpas, te juro que creí que estaba generando una issue nueva para la consulta del wait, no fue mi intención preguntar acá mismo, se ve que haciendo cosas del laburo lo metí acá, pero la intención era abrir una nueva. Nuevamente te pido disculpas.

**Comment by LeandroCarbajales** [comment]
No hay por qué pedir disculpas, sea por equivocación o inexperiencia estamos todos para aprender, se los remarco ya que hubiera sido probable que sus dudas queden sin responder porque no nos llegan notif sobre comentarios en issues cerrados.
