### ISSUE TITLE
Error Multiple Declarations (No levanta valores de archivo config)

### ISSUE THREAD

**Issue by diegohcanetti** [sisoputnfrba/foro#2967]
Hola buenas tardes, el sábado pasado tuve problemas al intentar hacer un utils dentro del módulo de CPU ya que me generaba problemas con los multiple delcarations, parecido a lo que ocurrió en #1896. Un ayudante me intentó solucionar el problema con extends dentro del .h, pero seguían surgiendo problemas como guardar los valores del archivo config del CPU.  Inclusive al ayudante le pareció raro que se puede volver a declarar el t_xonfig en el cpu_utils.c

📝 Código relevante
```
#ifndef CPU_UTILS_H
#define CPU_UTILS_H


extern t_config* config;
extern t_handshake* configuracion_tabla;
extern t_log* cpu_logger ;
extern int socket_memoria;

typedef struct  // archivo de configuracion cpu
{
   char* ip_cpu;
   int retardo_instruccion;
   char* ip_memoria;
   char* puerto_memoria;
   char* puerto_escucha;
   char* puerto_escucha_kernel;
   int tamanio_maximo_segmento;
} arch_config;

extern arch_config config_valores_cpu;
```
```

#include "cpu_utils.h"

t_config* config;
t_handshake* configuracion_tabla;
t_log* cpu_logger ;
int socket_memoria;
arch_config config_valores_cpu;


//======================= Funciones Globales ==============

/// CONFIGURACIÓN ///
void cargar_configuracion(char* path){

    t_config* config = config_create(path); //Leo el archivo de configuracion

    if (config == NULL) {
        perror("Archivo de configuracion de cpu no encontrado \n");
        abort();
    }

	config_valores_cpu.ip_cpu=config_get_string_value(config,"IP_CPU");
```

🐛 Cómo reproducir el error
Debuggeamos el código y cuando entraba a la línea de código  "config_valores_cpu.ip_cpu=config_get_string_value(config,"IP_CPU");" se leía la variable, pero no se guardaba. Esto se repeteía con el resto de valores

**Comment by iago64** [comment]
Buenas! Cómo va?

Estuve intentando recrear el error que estas teniendo y estaría funcionandome de manera correcta, con lo cual, creo que el problema es por la visualización del debug, te paso el escenario que hice para recrear el problema:

testInclude.c
```c
#include <stdio.h>
#include <stdlib.h>
#include "testInclude.h"

int main(void) {

	cargar_configuracion("/home/utnso/config.cfg");
	printf("Valor IP: %s\n", config_valores_cpu.ip_cpu);
	return EXIT_SUCCESS;

}
```

testInclude.h
```c
#ifndef TESTINCLUDE_H_
#define TESTINCLUDE_H_

#include "utils.h"


#endif /* TESTINCLUDE_H_ */
```

utils.c
```c
#include "utils.h"
#include <stdio.h>
#include <commons/config.h>

arch_config config_valores_cpu;
t_config* config;

void cargar_configuracion(char* path){

    config = config_create(path); //Leo el archivo de configuracion
	config_valores_cpu.ip_cpu = config_get_string_value(config,"IP");

}
```

utils.h
```c
#ifndef UTILS_H_
#define UTILS_H_

#include <commons/config.h>

extern t_config* config;

typedef struct  // archivo de configuracion cpu
{
   char* ip_cpu;
   int retardo_instruccion;
   char* ip_memoria;
   char* puerto_memoria;
   char* puerto_escucha;
   char* puerto_escucha_kernel;
   int tamanio_maximo_segmento;
} arch_config;

extern arch_config config_valores_cpu;

void cargar_configuracion(char* path);

#endif /* UTILS_H_ */
```

Si compilo y ejecuto el código, el mismo me imprime bien los valores del archivo de config que cree:

![image](https://github.com/sisoputnfrba/foro/assets/1622109/07058a28-d1c3-4274-8547-664797507381)
![image](https://github.com/sisoputnfrba/foro/assets/1622109/67704942-5f61-40b1-840d-a2d41cd89cdf)

Por las dudas te consulto, aparte de debuguearlo, si imprimis el valor abajo de asignarlo, falla?

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Para sumar, una aclaración sobre esta parte:
> Inclusive al ayudante le pareció raro que se puede volver a declarar el t_xonfig en el cpu_utils.c

En C, una cosa es _declarar_ una variable y otra cosa es _definirla_:
- Al _declarar_ una variable, solo le estás diciendo al compilador que la misma existe en alguna parte del programa, pero no se reserva memoria. Es lo mismo que hacemos con los prototipos de las funciones en los headers: _declaramos_ que la función existe, pero sabiendo que va a estar _definida_ en otro lado.
- Al _definir_ una variable, ahí sí se reserva el espacio correspondiente en memoria:
  - Si es una variable global, se reserva en el segmento **datos** al iniciar el proceso.
  - Si es una variable local, se reserva en el segmento **pila** cada vez que se llame la función.

Entonces, lo que hace el operador `extern` en el ejemplo de Dami es avisarle a todos los archivos que importen `utils.h` que existe la variable, mientras que en el `utils.c` definimos el espacio en memoria que va a ocupar.

Saludos

**Comment by iago64** [comment]
Buenas @diegohcanetti cómo va?

¿Te sirvieron las respuestas? Necesitas que veamos más en detalle algo de tu código?

Saludos.-

**Comment by diegohcanetti** [comment]
Si me sirvieron, me senté hoy y logré corregir los problemas. 
Muchas gracias
