### ISSUE TITLE
Dudas con instrucción WAIT

### ISSUE THREAD

**Issue by ezequielmalfonso** [sisoputnfrba/foro#2968]
Buenas tardes, tengo una duda con el enunciado cuando habla del manejo de recursos: puede estar relacionado con la issue
#2927 pero no termino de entenderlo.
>Manejo de Recursos
Los recursos del sistema vendrán indicados por medio del archivo de configuración, donde se encontrarán 2 variables con la información inicial de los mismos:
La primera llamada RECURSOS, la cual listará los nombres de los recursos disponibles en el sistema.
La segunda llamada INSTANCIAS_RECURSOS será la cantidad de instancias de cada recurso del sistema, y estarán ordenadas de acuerdo a la anterior lista (ver [ejemplo].
A la hora de recibir de la CPU un Contexto de Ejecución desplazado por WAIT, el Kernel deberá verificar primero que exista el recurso solicitado y en caso de que exista restarle 1 a la cantidad de instancias del mismo. En caso de que el número sea estrictamente menor a 0, el proceso que realizó WAIT se bloqueará en la cola de bloqueados correspondiente al recurso.

Entiendo que si:

>RECURSOS=[DISCO, RECURSO_1]
INSTANCIAS_RECURSOS=[1, 2]

Es una instancia del DISCO y dos instancias de RECURSO_1

No me queda claro que pasa con el proceso, cuando ejecuta el wait, si tengo dos procesos, cuando llega al momento de ejecutar la instrucción WAIT, como el ejemplo el CPU envía el contexto al kernel y el kernel se fija si hay una o mas instancias entonces le avisa al cpu que lo ejecute (Seria imprimir en pantalla que se esta ejecutando el recurso en cuestión?)? Si es 0 que hace?
Y si es menor a cero lo envió a una cola de bloqueados, ahí la otra duda, tendría que tener una cola de bloqueados por cada Recurso? o sea una cola para DISCO y otra para RECURSO_1? pero puede llegar a haber mas recursos que esos dos o ya son fijos?
Y una vez que son desbloqueado lo envió a la cola READY?

Gracias.-

**Comment by LeandroCarbajales** [comment]
Buenas!
Voy respondiendo por partes:

> ...como el ejemplo el CPU envía el contexto al kernel y el kernel se fija si hay una o mas instancias entonces le avisa al cpu que lo ejecute (Seria imprimir en pantalla que se esta ejecutando el recurso en cuestión?)? Si es 0 que hace?

Pensalo como algo similar a una syscall, el proceso no puede ejecutar WAIT por su cuenta, por lo tanto lo único que haría la instrucción WAIT es pedirle al Kernel que lo haga, luego ya continuaría con su próxima instrucción. Por lo que todo el comportamiento de la misma es el que está definido en el Kernel.

> Si es 0 que hace?
Y si es menor a cero lo envió a una cola de bloqueados, ahí la otra duda, tendría que tener una cola de bloqueados por cada Recurso?

El comportamiento es ser similar a un semáforo, si hay alguna instancia disponible, se le asigna (pudiendo quedar su valor en 0 o más) y sigue ejecutando el mismo proceso, si no las hay (quedando su valor en negativo) se bloquea esperando por **ese recurso en particular** por lo que efectivamente necesitan una cola de bloqueados por cada recurso.

> o sea una cola para DISCO y otra para RECURSO_1? pero puede llegar a haber mas recursos que esos dos o ya son fijos?

Las listas de recursos y cantidad de instancias vienen por configuración por lo que podrían cambiar entre una prueba y otra, pero no durante la ejecución.

> Y una vez que son desbloqueado lo envió a la cola READY?
Exactamente :)

**Comment by LeandroCarbajales** [comment]
> Entonces cuando viene ejecutando un proceso y llega al WAIT y tiene por ejemplo un recurso con una instancia, se lo pasa al Kernel y lo ejecuta en el Kernel y el proceso ejecuta la próxima instrucción?

En cualquier caso lo único que tiene que hacer CPU con el WAIT (así como las otras "syscalls" definidas) es pasárselo al Kernel y esperar un nuevo contexto a ejecutar.

> Pero si el mismo no tiene disponible un recurso (instancia menor a cero) se bloquea todo el proceso esperando que se libere una instancia de ese recurso y pasa a ejecutar otro proceso que este en la cola de ready según la planificación y cuando el proceso bloqueado se desbloquea pasa a la cola de ready?

Claro, al bloquearlo debería replanificar inmediatamente. Luego al desbloquearlo con la ejecución de algún SIGNAL volvería a ready como es lo esperado :)

**Comment by ezequielmalfonso** [comment]
>En cualquier caso lo único que tiene que hacer CPU con el WAIT (así como las otras "syscalls" definidas) es pasárselo al Kernel y esperar un nuevo contexto a ejecutar.

La ultima q te jodo perdón, entonces si tengo:
P1 en Exec
P2 en Ready
P1 ejecuta el WAIT (suponiendo q tiene recursos disponibles para ejecutar la instrucción) le envía el contexto al kenel y si en ese lapso de tiempo puede ejecutar P2 pq ya estaba en ready lo hace? Vendría a ser una especie de "I/O" pero con instancias?

**Comment by LeandroCarbajales** [comment]
Si hay instancias disponibles del recurso que pide P1, entonces no se bloquearía por lo que debería volver a CPU para seguir ejecutando (no se replanifica)

**Comment by LeandroCarbajales** [comment]
@ezequielmalfonso 

Quedó aclarada la duda? Se puede cerrar el issue?

**Comment by ezequielmalfonso** [comment]
Si si , por ahora si. Muchas gracias.

**Comment by ezequielmalfonso** [comment]
Disculpa estoy implementando el WAIT y SIGNAL y me surgió una duda:
Si tengo a P1 al momento de ejecutar el WAIT, por ejemplo disco, y no hay instancias disponibles, lo mandó a la cola de bloqueados del recurso DISCO, y este proceso NO ejecuta la I/O (q es la siguiente instrucción) hasta que no se libere una instancia de DISCO?
Si es así si ejecuto un P2, que tiene las mismas instrucciones tb se bloqueria y así se bloquerian todos y no avanzaría ninguno, pq ninguno puede llegar a la instrucción SIGNAL o me estoy equivocando mucho?
¿Cómo podría hacer una prueba, para verificar que lo que hice está bien?

**Comment by LeandroCarbajales** [comment]
Buenas!
Eso solamente te podría ocurrir si el recurso DISCO estuviera inicializado en 0 (que entiendo que en este caso no tendría sentido si se quiere usar a modo de mutex), o si otro proceso toma el recurso y nunca lo libera.
Con el recurso inicializado en 1 podrías probar el caso que mencionás con algún script que tenga algo como:
WAIT DISCO
IO 10
SIGNAL DISCO

Suponiendo que tenés P1 y P2 que ejecuten en ese orden:
P1 vendría primero, tomaría el recurso sin bloquearse (quedando el valor del recurso en 0) y luego se bloquearía en IO por 10 segundos.
Seguiría P2 ejecutando WAIT y se bloquearía por no haber instancias disponibles (quedando el valor del recurso en -1).
Al desbloquearse P1 del IO, su próxima instrucción sería SIGNAL y desbloquearía a P2.

**Comment by ezequielmalfonso** [comment]
Muchas gracias, ahi lo entendí.

**Comment by ezequielmalfonso** [comment]
@LeandroCarbajales perdón que lo vuelva a abrir, una consulta mas sobre este tema:
Estaba probando el HRRN, y me surgió una duda, mirando el ejemplo que me pusiste para probar;
>Suponiendo que tenes P1 y P2 que ejecuten en ese orden:
P1 vendría primero, tomaría el recurso sin bloquearse (quedando el valor del recurso en 0) y luego se bloquearía en IO por 10 segundos.
Seguiría P2 ejecutando WAIT y se bloquearía por no haber instancias disponibles (quedando el valor del recurso en -1).
Al desbloquearse P1 del IO, su próxima instrucción sería SIGNAL y desbloquearía a P2.

Cuando P2 se desbloquea, que pasa de BLOCKED -> READY, y luego a EXECUTE, que instrucción debería de ejecutar, el WAIT por el cual fue bloqueado y luego continuar con el ciclo de instrucciones?

Gracias.-

**Comment by irinaperezg** [comment]
> Buenas! Eso solamente te podría ocurrir si el recurso DISCO estuviera inicializado en 0 (que entiendo que en este caso no tendría sentido si se quiere usar a modo de mutex), o si otro proceso toma el recurso y nunca lo libera. Con el recurso inicializado en 1 podrías probar el caso que mencionás con algún script que tenga algo como: WAIT DISCO IO 10 SIGNAL DISCO
> 
> Suponiendo que tenés P1 y P2 que ejecuten en ese orden: P1 vendría primero, tomaría el recurso sin bloquearse (quedando el valor del recurso en 0) y luego se bloquearía en IO por 10 segundos. Seguiría P2 ejecutando WAIT y se bloquearía por no haber instancias disponibles (quedando el valor del recurso en -1). Al desbloquearse P1 del IO, su próxima instrucción sería SIGNAL y desbloquearía a P2.

Una consulta con respecto a esto, si solamente se ejecutase la instrucción IO sin una instrucción WAIT no haría falta que espere ningun recurso no?

**Comment by iago64** [comment]
Buenas! Cómo va? No soy lean, pero puedo dar algo de luz sobre las preguntas 😄 

@ezequielmalfonso El WAIT funciona al igual que en la teoría, uds al hacer WAIT ya ejecutaron esa instrucción y el resultado es que se bloquearon, entonces lo que pasa es que tienen que continuar con la siguiente.

@irinaperezg Esa era una hermosa pregunta para otro issue, pero ya que estamos hacemos un 2x1 en respuestas 😄, si les llega un I/O sin un WAIT antes, como bien decis, solamente devuelven el Contexto de Ejecución al Kernel y este los bloquea por la cantidad de segundos que tiene como parámetro I/O 😊 

Saludos.-

**Comment by irinaperezg** [comment]
jajaja perdón y gracias <3

**Comment by ezequielmalfonso** [comment]
@iago64  muchas gracias, haciendo las pruebas y mirando y mirando los logs nos empezamos a confundir y nos entro la duda. 
De paso aprovecho y te hago otra :), para probar la plani en FIFO es mas o menos fácil seguir el log, pero el HRRN, hay algún script o forma de probar para que sepamos de antemano  lo que nos tendría que dar como resultado los logs.
Probamos de enviar 4 consolas los mas rápido posible  y finalizan todas bien, peor nos queda la duda si están bien la secuencia.
Gracias.-

**Comment by iago64** [comment]
Buenas! Cómo va @ezequielmalfonso 

Admito que un poco a propósito tarde en contestarte porque estábamos por largar las pruebas, ahi tenes un lindo ejemplo de como vamos a testear HRRN 😉 

Saludos.-

**Comment by ezequielmalfonso** [comment]
@iago64  gracias!!!
