### ISSUE TITLE
Duda con instrucción IO

### ISSUE THREAD

**Issue by irinaperezg** [sisoputnfrba/foro#2969]
Buenas :)
En el issue #2965 vi que comentaron que había que hacer que el proceso ejecute el IO (que espere) con un hilo.
Como no tengo muy en claro todavía el tema de los hilos quería consultar si estaría bien la forma en que lo hice, me confunde un poco el orden, no se si está bien que el hilo ejecute entre las funciones para cambiar al proceso de estado porque pasaría concurrentemente que la espera y el pasaje a ready no? osea, sin que haya terminado tal vez el tiempo de espera.
pero si hago el join no se "bloquearia" el proceso no? no se si otra función debería llamar a ejecutar_proceso_io y esperar a que esta termine y recién ahí cambiar el estado

### 💭 Soluciones posibles
![image](https://github.com/sisoputnfrba/foro/assets/83139862/b64ccb2c-7893-474e-9c42-4258a77fb77e)

**Comment by iago64** [comment]
Buenas! Cómo va?

Algo copado de la solución con hilos es que ambas opciones pueden ser completamente válidas, porque podes hacer que el hilo espere nomas el tiempo y que el movimiento de los procesos lo haga el "hilo del planificador", o podes hacer que el hilo de io mueva el proceso a bloqueado, espere y mueva a ready al proceso y en ambos casos se cumpliría la condición que tiene este TP de que la IO es propia del proceso.

Lo único que **no puede faltar** en ninguna de las 2 opciones, es la sincro, asumo que en las funciones `pcb_pasar_de_xxxx_a_yyyy_public()` tienen los elementos de sincro correspondientes para que solo 1 hilo a la vez este operando sobre esas colas del planificador.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Dejo un comentario sobre esto:

> no se si está bien que el hilo ejecute entre las funciones para cambiar al proceso de estado porque pasaría concurrentemente que la espera y el pasaje a ready no? osea, sin que haya terminado tal vez el tiempo de espera.

Entiendo que te referís a la solución de la derecha y estarías en lo cierto, al ejecutar `pthread_create()` se comenzará a ejecutar la función sleepHilo en un hilo nuevo, sin embargo, el hilo que llamó a `pthread_create()` seguirá ejecutando concurrentemente las líneas que siguen, por lo que en este caso probablemente ejecutaría la función `pcb_pasar_a_ready()` antes de que el otro termine su sleep.
Como decía @iago64, lo más importante acá es que tengan clara la sincro, tanto la mutua exclusión como qué cosas quieren que pasen en determinado orden, si lo que buscan es pasar al proceso a ready **después** de hacer el sleep, pueden esperar que eso ocurra utilizando algún semáforo "binario" o `pthread_join()`, o simplemente hacer ese paso en el mismo hilo que hace el sleep.

**Comment by irinaperezg** [comment]
Claro, tal vez lo mejor es que se pase a ready en la función del hilo que hace sleep
La diferencia entre la primera solución y la de la derecha sería que en uno el proceso seguiria ejecutando aunque esté haciendo el sleep no? osea utilizando la cpu, mientras que en el segundo mientras espera el IO ya se libera la cpu?

**Comment by iago64** [comment]
Buenas! 

Creo que aca tenemos un par de conceptos cruzados, por un lado, el tema de hilos para programar y por otro el tener algo en la CPU del tp:

Respecto a los hilos para programar, en el momento que haces el `sleep()` el hilo se bloquea hasta que pasa el tiempo que le indicas.

Respecto a la CPU del TP, en ambos casos vas a tener que si o si sacar al proceso que está ejecutando y mandar a otro o no mandar a ninguno si no tenes otro proceso en la cola de ready.

Saludos.-

**Comment by irinaperezg** [comment]
claro, lo que no me queda claro es cual seria la diferencia entre las dos implementaciones, y con respecto a lo que dijiste antes, si, está sincronizada dentro de las funciones el tema de cambio de estados de pcb :)
![image](https://github.com/sisoputnfrba/foro/assets/83139862/9b530e16-b5db-45e5-974c-8ec0c4293354)
una consulta relacionada con estas instrucciones que tengo 
para que un proceso haga una instruccion IO deberia tener algun recurso asignado o no hace falta? si no hace falta, para que seria el wait? osea para que querria un proceso un recurso?

**Comment by LeandroCarbajales** [comment]
> claro, lo que no me queda claro es cual seria la diferencia entre las dos implementaciones, y con respecto a lo que dijiste antes, si, está sincronizada dentro de las funciones el tema de cambio de estados de pcb :)

En la solución de la izquierda tenés:

```
Hilo 1:
  Pasa al proceso a block
  Hace sleep
      (este hilo espera por x segundos)
  Pasa al proceso a ready
```

En la solución de la derecha:
```
Hilo 1:                                         Hilo 2:
  Pasa al proceso a block                         Hace sleep (este hilo espera por x segundos)
  Crea al hilo 2
  Pasa al proceso a ready
```

En la de la izquierda tenés el problema que mientras hacés `sleep()` no estarías replanificando, por lo que una solución posible sería que `ejecutar_instruccion_io` se haga en un `pthread_create()` directamente.

En la de la derecha tenés el problema que estás pasando al proceso a ready **mientras** el otro hilo hace el sleep en lugar de pasarlo a ready después de esperar ese tiempo, por lo que una solución podría ser como bien dijiste pasar al proceso a ready desde la función hiloSleep en este caso

> una consulta relacionada con estas instrucciones que tengo
para que un proceso haga una instruccion IO deberia tener algun recurso asignado o no hace falta?

A efectos del trabajo, no hace falta justamente para poder probar la planificación sin tener implementada la parte de recursos, eso no significa que en alguna prueba no pidamos un recurso antes de hacer IO, pero no es una validación que tengan que hacer.

> si no hace falta, para que seria el wait? osea para que querria un proceso un recurso?

A efectos académicos, el propósito es que incorporen el concepto de un recurso reusable similar a un semáforo, en ese sentido para el Kernel el motivo es irrelevante, pueden pedir los recursos que quieran sin motivo alguno.

A efectos de las pruebas podríamos usar wait en los scripts para forzar las siguientes situaciones:
1. Como bien comentabas antes, hacer el wait antes de IO para forzar el comportamiento de que se encolen por IO como si hubieran dispositivos.
2. Para forzar a que ocurra un deadlock entre estos procesos.
3. Para evitar una condición de carrera cuando estos procesos accedan al segmento compartido definido por el módulo Memoria.

Queda más clara la idea? :)

**Comment by irinaperezg** [comment]
Genial! Ahora si me quedo mucho mas claro. Muchas gracias :))
