### ISSUE TITLE
Dudas sobre los huecos libres en memoria

### ISSUE THREAD

**Issue by FacundoPiaggio** [sisoputnfrba/foro#2970]
Buenas tardes!

Tengo algunas dudas con el concepto de hueco libre en memoria.

Primero que nada, ¿que representa el hueco libre? ¿un espacio de memoria que podría llegar a ocupar cualquier segmento?
Si esto es así, me genera otras preguntas.

¿Cuantos huecos tengo inicialmente? ¿Un gran hueco de 4096 (tamaño de la memoria)?

¿Los huecos, se van "creando" por decir de alguna manera, a medida que se quieren crear los segmentos? es decir, si quiero crear un segmento de 64 bytes, ¿voy a tener que "crear" un hueco de dicho tamaño para mostrar ese lugar de memoria como "ocupado"?.

Pregunto esto principalmente por que no veo el motivo por el cual, inicialmente tendría muchos huecos, es decir, ¿podría pasar que un proceso quiera una parte de la memoria en el medio por así decir, pese a que toda la memoria este libre?

Si esto no puede suceder, entonces los huecos se irían creando a demanda con cada segmento, ¿verdad?

Entiendo que por ejemplo, un P1 cree un seg1.1. y despues venga un P2 y cree el seg2.1. Entonces si P1 borra al seg1.1 te va a quedar ese hueco libre (del tamaño del segmento borrado), despues tenes el seg2.1 y seguido vas a tener el resto de la memoria por estar contigua (el hueco mayor, digamos). ¿Esto es así?

Muchas gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Algo interesante de la planificación del TP es que estos temas recién los vas a ver la semana que viene cuando empiecen con las clases de memoria y para el próximo sábado aun estaría cerrando el tema de planificación del kernel.

Aun así, entiendo que la manija nos puede a todos así que, vamos a responder las dudas.

Un hueco libre es básicamente un pedazo de memoria que no está asignado a ningún proceso.
Inicialmente vas a tener un único hueco libre que va a ser toda la memoria menos el segmento 0 que es el segmento que va a estar compartido entre todos los procesos, después a medida que te lleguen las peticiones de crear segmentos ese hueco libre se va a ir reduciendo (dependiendo del tamaño del segmento que te pidan crear a la vez)
El problema de los huecos libres se te va a dar recién cuando un proceso libere sus segmentos (ya sea porque hizo un DELETE_SEGMENT o porque finalizó)
Entonces como bien decís, si P1 crea un segmento, después P2 crea otro segmento, la memoria te va a quedar algo asi como:

|...Segmento_Compartido...|....P1...|...P2...|...Libre...|
Y al momento de finalizar P1 o que este ejecute el delete segment la memoria te va a quedar:
|...Segmento_Compartido...|.Libre.|...P2...|...Libre...|

Saludos.-

**Comment by FacundoPiaggio** [comment]
Excelente dami, clarisimo todo!.

Muchas gracias!
