### ISSUE TITLE
Consulta closure funcion list_find de las commons

### ISSUE THREAD

**Issue by pablomartinfranco** [sisoputnfrba/foro#2972]
Hola, 
en la funcion de las commons list_find
```c
void* list_find(t_list *self, bool(*condition)(void*)) {
	t_link_element **indirect = list_get_indirect_by_condition(self, condition);
	return (*indirect) != NULL ? (*indirect)->data : NULL;
}
```
cual seria la forma correcta de capturar un valor desde fuera de un closure y devolver el puntero a la funcion que evalua la condicion contra ese valor capturado ?

quiero buscar un elemento en una lista matcheando por uno de los elementos introduciendo el target value desde fuera de la funcion condicion.

estoy intentando hacer un closure que recibe un valor y devuelva el puntero a la funcion condicion.

PD: estoy tratando de hacerlo sin la extension de nested functions.

Edit: creo que pude hacerlo pero reimplementando la funcion para que reciba el contexto.
```c
// Asi quedaria la firma agregando el contexto
void* list_find(t_list *self, bool(*fn)(void *elem, void *ctx), void *ctx);
```

Gracias 
Saludos

**Comment by RaniAgus** [comment]
¡Buenas! En estos casos les recomiendo intentar no reinventar la rueda y pasarle una nested function a `list_find()`. La idea de usar las commons es que no se queden atascados en buscar cómo implementar listas enlazadas y puedan enfocarse en los requerimientos del TP.

Si la razón es que el VSCode les colorea con rojo al no ser una feature de C estándar (https://github.com/microsoft/vscode-cpptools/issues/1035), pueden hacer 2 cosas:
1. Desactivar el intellisense agregando esta línea a su config del workspace:
```json
{
	"settings": {
		"C_Cpp.errorSquiggles": "disabled", 
	},
}
```
2. No hacer nada, solo ignorarlo. Los verdaderos warnings y errores son los que arroja el compilador, si el IDE les marca algo, eso no es ningún impedimento para que se ejecute `gcc` para compilar.

Saludos

**Comment by pablomartinfranco** [comment]
Ok
Saludos
