### ISSUE TITLE
INVITACION REPO GIT

### ISSUE THREAD

**Issue by azuubaez** [sisoputnfrba/foro#2975]
Hola! Buenas tardes, queria consultarles si me podrian reenviar la invitacion al repo de git porque tuve un inconveniente y se me vencio! Muchas graciaas

**Comment by LeandroCarbajales** [comment]
Buenas!
Se pueden volver a mandar la invitación desde el sistema de inscripciones :)

Cualquier inconveniente con el mismo pueden mandar mail a inscripciones@utnso.com.ar
Saludos!
           Lean
