### ISSUE TITLE
Duda sobre bloqueos con F_TRUNCATE y orden de recvs

### ISSUE THREAD

**Issue by FacundoPiaggio** [sisoputnfrba/foro#2976]
Buenas!

Planteo la siguiente situacion:

Un proceso P1 hace F_TRUNCATE y se bloquea esperando la respuesta de FS, digamos que esperamos en un hilo a parte, con un recv.
Como el proceso P1 que estaba ejecutando, ahora esta bloqueado, yo puedo ejecutar a otro proceso P2. Ahora este P2 quiere hacer algun pedido a FS, por ejemplo un F_OPEN, y luego hacemos un recv para recibir el OK por parte de FS.

La duda es: 
¿Puede generar un problema a la hora de recibir los mensajes?
es decir, ¿puede pasar que la respuesta al F_TRUNCATE de P1, llegue al recv del F_OPEN de p2?.
El orden de solicitudes que maneje el FS sera una peticion detras de la otra, pero si tenemos mas de un recv esperando por algo, ¿puede pasar que el send que haga FS llegue a un recv incorrecto?

Espero haberme explicado bien.
Muchas gracias.

**Comment by LeandroCarbajales** [comment]
Buenas!
Sí, les puede generar un problema ya que tendrían varios hilos esperando leer sobre la misma variable compartida (en este caso el socket con FS) sin un orden definido.
Puede pasar que les arroje error al recibir el mensaje desde un hilo porque en realidad están recibiendo el mensaje que le corresponde al otro y viceversa.
Justamente por eso explicitamos en el FS que no es necesario que el mismo atienda solicitudes de manera concurrente: `Una vez conectado, atenderá una por una las solicitudes que el Kernel le envíe`

Por lo tanto, del lado del Kernel podrían hacer algo como:
```c
pthread_mutex_lock(&mutex_fd);
send(fd, ...);
recv(fd, ...);
pthread_mutex_unlock(&mutex_fd);
```
De esta manera, siempre las solicitudes al FS tendrían su respuesta de manera atómica.
Cabe aclarar, que esto mismo les podría llegar a pasar en la comunicación con el módulo Memoria, por lo que recomendamos lo mismo en ese caso.

Les sirve la respuesta?

Saludos!
       Lean

**Comment by FacundoPiaggio** [comment]
Nos sirve un montón, muchas gracias lean!
