### ISSUE TITLE
Duda calculo de HRRN y la instrucción YIELD

### ISSUE THREAD

**Issue by MiltonMartorello** [sisoputnfrba/foro#2977]
Holiiis volvimoos _(suena la marcha)_ 
Esta vez con una duda sobre el cálculo del ratio de HRRN.

### 📔 Citas del enunciado/videos
`En caso de utilizar el algoritmo HRRN, se deberá además calcular un nuevo estimado para su próxima ráfaga utilizando la fórmula de promedio ponderado vista en clases.`

Tenemos 3 dudas que paso a etiquetar con numeritos

1️⃣ Entiendo que deberíamos utilizar las siguientes 2 fórmulas:

1.  - **R.R. = (S + W) / S**  
      Donde S = Ráfaga estimada y W = Tiempo de espera.
2. - **S = α . estimadoAnterior + (1 - α) . ráfagaAnterior**

Esto es correcto?
Si hay que usar las fórmulas mencionadas anteriormente... Es válido el siguiente caso de uso de 3 ráfagas de un mismo proceso que desaloja por YIELD?

- i - La primera vez que se planifica no se calcula el estimado, directamente se toma el valor de ESTIMACION_INICIAL = 10000 milisegundos.
- ii - El proceso ejecuta y vuelve a Ready por YIELD luego de ejecutar 3000 milisegundos.
- iii - Se replanifica y al considerar el proceso en cuestión se calcula:
```
       S1 = α . estimado + (1 - α) . ráfagaAnterior
       S1 = 0,5 . 2️⃣ ¿ESTIMACION_INICIAL? + 0,5 . 3000
```
 
- iv - El proceso ejecutó 7500 milisegundos, se bloquea y vuelve a Ready por desbloqueo.
- v -  Se replanifica una vez más:
```
       S2 = α . estimado + (1 - α) . ráfagaAnterior
       S2 = 0,5 . 3️⃣ S1? + 0,5 . 7500 
```

Disculpen si quedó medio rebuscado el caso pero me genera muchas dudas que pasa con el caso de YIELD y sobre todo si las fórmulas estan siendo bien aplicadas

Muchas gracias!

**Comment by LeandroCarbajales** [comment]
Buenas!
Lo veo correcto, el cálculo de estimado es exactamente igual que al calcular un ejercicio de planificación de SJF. El YIELD como bien marcaste lo vemos en este TP como que finalizó su ráfaga y por lo tanto le calculamos inmediatamente un nuevo estimado. Luego, la fórmula de Response Ratio también es la misma :)

Saludos!
        Lean
