### ISSUE TITLE
Duda instruccion Signal

### ISSUE THREAD

**Issue by vamanfredi** [sisoputnfrba/foro#2979]
Buenas, tengo la duda de qué ocurre cuando llega una instruccion signal teniendo todas las instancias de un recurso disponibles. En ese caso se agregaría una instancia más o quedaría igual?

**Comment by LeandroCarbajales** [comment]
Buenas!
En el enunciado no hay ningún chequeo al respecto:

> el Kernel deberá verificar primero que exista el recurso solicitado y luego sumarle 1 a la cantidad de instancias del mismo

Por lo que similar a un semáforo "contador/binario", se agregaría una instancia más del recurso.

Saludos!
        Lean

**Comment by vamanfredi** [comment]
Muchas gracias !
