### ISSUE TITLE
Reservar bloques en el bitmap al redimensionar un archivo

### ISSUE THREAD

**Issue by pablomartinfranco** [sisoputnfrba/foro#2980]
Hola !
consulta,
para alocar bloques en el bitmap cuando se redimensiona un archivo,
usamos memoria contigua o hay que hacer un algoritmo que aproveche los espacios libres  ?
calculo que esta pensado para memoria contigua verdad ?
porque sino faltaria una estructura de punteros de varios niveles en el FCB, no es asi ?

Saludos

**Comment by LeandroCarbajales** [comment]
Buenas!
Como indica en el "Anexo: Implementación de File System", el FCB tiene una estructura de punteros:
`Puntero directo: Apunta al primer bloque de datos del archivo.`
`Puntero indirecto: Apunta a un bloque que contendrá los punteros a los siguientes bloques del archivo.
`
Por lo tanto, los bloques del archivo no tienen por qué estar contiguos entre sí.

Saludos!
         Lean

**Comment by pablomartinfranco** [comment]
ok barbaro, gracias.
y otra consulta, en los indirectos, es un puntero por cada bloque o pares de puteros (principio, fin) tipo arbol digamos ?

**Comment by pablomartinfranco** [comment]
perdon ya lo resolvi, cierro el issue, gracias !
