### ISSUE TITLE
Duda sobre el manejo de consola en kernel

### ISSUE THREAD

**Issue by cserrudo** [sisoputnfrba/foro#2981]
Buenas! Tengo una duda sobre lo que nos dijo Lean en el soporte de hoy. 

Con mi grupo le mostramos como veniamos con el TP, nosotros tomamos como que por cada cliente que se conecta a kernel (en este caso las distintas consolas) le asignabamos un hilo y nos dijo que no era necesario, o que a lo sumo usáramos hilos de corta duración, como una buena practica, que hubiera tenido mas sentido si hubiera habido una ida y vuelta entre kernel y consola.
Si no son necesarios por qué en el enunciado dice que usa una estrategia de múltiples hilos de ejecución? No estaría entendiendo.
Otra consulta que tengo tambien es si lo implementaramos sin hilos, seria como los ejercicios que hacemos en la parte practica, no? 
Gracias

### 📔 Citas del enunciado/videos

> 
Este módulo deberá mantener una conexión activa con la CPU, la Memoria, File System y las diferentes consolas que se conecten. Para ello, deberá implementarse mediante una estrategia de múltiples hilos de ejecución.

**Comment by ncoen97** [comment]
Buenas!

A lo que apuntaba Lean con la aclaración es que una vez que uds ya reciben la info de la nueva consola (parsean los mensajes, etc) y meten al proceso en la cola de New, ya no es necesario tener un hilo activo exclusivamente para esa consola. Sí van a tener hilos que manejen la planificación en gral, pero no uno dedicado a cada consola. Cuando esa consola llegue a Exit, directamente le hacen un `send()` al socket correspondiente (para que esa consola muera) y listo 👍 

Cualquier duda me avisan!

**Comment by cserrudo** [comment]
Perfecto! se entendió, gracias
