### ISSUE TITLE
Duda con la sincronización de planificador de largo plazo

### ISSUE THREAD

**Issue by MiltonMartorello** [sisoputnfrba/foro#2982]
Holanda! Como va eso ? Acá disfrutando de un sábado a la noche junto a mis amigos los planificadores. 
Tengo una duda con respecto a si el responsable de chequear la cola de exit es realmente el planificador de largo plazo o si se puede dividir responsabilidades con otro hilo.

Sucede que en nuestro caso tenemos 2 + N hilos por ahora en kernel.

1 - Planificador de largo plazo
2 - Planificador de corto plazo
N - Para atender consolas.

Ahora en cuanto a sincronización el planificador de largo plazo tiene un while(1) donde espera el wait de 2 semáforos:
 - Existe un nuevo proceso en NEW (El hilo de consola lo deposita allí)
 - El grado de multiprogramación permite un nuevo proceso.

Sin embargo el enunciado dice
### 📔 Citas del enunciado dentro de Planificacor de largo plazo.
`Cuando se reciba un mensaje de CPU con motivo de finalizar el proceso, se deberá pasar al mismo al estado EXIT, liberar todos los recursos que tenga asignados y dar aviso al módulo Memoria para que éste libere sus estructuras. Una vez hecho esto, se dará aviso a la Consola de la finalización del proceso.`

Como en nuestro algoritmo el planificador de largo plazo esta todo el tiempo a la espera de nuevos procesos, no puede estar también pendiente de los procesos que estan en exit. O por lo menos creemos que no puede.

Esta bien que el hilo de consola maneje esta consulta ya que al depositar un proceso en la cola de NEW el próximo paso es traerse el resultado (que podría interpretarse que esta en la cola de exit). 
Entendemos que en la realidad es el planificador de largo plazo quien chequea esto y es quien baja el grado de multiprogramación, pero se puede dividir esas responsabilidades en distintos hilos(por ejemplo el de escucha a la consola) o es indefendible y deberíamos ver como hacer para que el hilo de largo plazo pueda manejar ambas colas?

Muchas Gracias!

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

¿Quién les dijo que el planificador de largo plazo solo es un único hilo? 
¿Por qué no pueden tener uno que se encargue de escuchar las nuevas conexiones y tener otro que se encargue de ver que procesos se van a EXIT?

Saludos.-
