### ISSUE TITLE
Duda con  compatibilidad con el formato de los archivos de config de las commons en el Superbloque de FS

### ISSUE THREAD

**Issue by lucasdeferrari** [sisoputnfrba/foro#2984]
Buenas tardes, tengo una duda con la compatibilidad de las commons de config en el Superbloque de FS. En en enunciado se menciona que este archivo es compatible con las commons de config, es decir que se deberia poder utilizar todas las funciones. Sin embargo, no aclara de que forma se da esta compatibilidad. Podría sacar las claves del archivo de superbloques de la siguiente forma?
```
if (config_has_property(p_superbloque, "BLOCK_SIZE")) {
			 printf("Existe el la clave block size.\n");
			 block_size = config_get_int_value(config, "BLOCK_SIZE");
			 }
```
Donde p_superbloque sea el path al archivo del superbloque. O debería modificar algo para forzar esta compatibilidad? Desde ya, muchas gracias.

**Comment by iago64** [comment]
Buenas! Cómo va?

Cuando decimos que son compatibles es literalmente que uds pueden copiar el ejemplo que está en el enunciado, pegarlo en un archivo y después leerlo como si fuera un archivo de config como están haciendo en el ejemplo de código que están pasando, no tienen que hacer nada extra 😄 

Saludos.-

**Comment by lucasdeferrari** [comment]
genial muchas gracias!
