### ISSUE TITLE
Dudas relacionadas a la tabla de segmentos

### ISSUE THREAD

**Issue by Santiagomorel** [sisoputnfrba/foro#2985]
Buenas tardes, tengo una serie de dudas sobre cómo sería conveniente implementar la tabla de segmentos dentro del pcb.
La tabla de segmentos es conveniente representarla como una **estructura de tipo t_list** (que es como comenzamos a implementarlo) o es mejor utilizar una **lista simplemente enlazada**.

_Fragmento de enunciado:_
>... enviando un mensaje al módulo Memoria para que inicialice sus estructuras necesarias y **obtenga la tabla de segmentos inicial** que deberá ser almacenada en el PCB

Suponiendo que represento la TS (tabla de segmentos) como un t_list, ¿Lo que recibiría el Kernel luego de solicitar la creación de la tabla seria una tabla completa, aka un struct t_list, o solamente el segmento inicial de una tabla?

---

A continuación tengo un inconveniente relacionado con programación en c, partiendo de la implementación de la TS como un t_list.

El problema sucede al agregar un elemento de tipo struct (en este caso segmento_base) dentro de una lista de tipo t_list (en este caso tabla_segmentos). Al intentar agregar el struct me retorna un segmentation fault.
Asumo que es un problema a la hora de acceder al espacio de memoria de la tabla_segmentos pero no puedo determinar por qué?

Código relacionado:
```c
> memoria.c
t_list* tabla_segmentos = list_create();
t_segmento* segmento_base = crear_segmento(0,0,64); 
list_add(tabla_segmentos, segmento_base); // ERROR aca hay un segfault
```

```c
> utils.h
typedef struct{
	int id_segmento;
	int direccion_base;
	int tamanio_segmento;
} t_segmento;
```

```c
> memoria.c
t_segmento* crear_segmento(int id_seg, int base, int tamanio){
    t_segmento* unSegmento;
    unSegmento->id_segmento = id_seg;
    unSegmento->direccion_base = base;
    unSegmento->tamanio_segmento = tamanio; 
    return unSegmento;
}
```
Saludos, Santiago.

**Comment by iago64** [comment]
Buenas! Cómo va?

Respecto a la forma de representar la tabla de segmentos, hay tantas alternativas como grupos inscriptos este cuatrimestre, con lo cual, una t_list es una de las tantas posibilidades.

Respecto al segfault que te esta tirando, te recomiendo que lo veas con valgrind (asi como cualquier error de memoria), ya que a priori, lo que veo es que estas declarando un puntero a un `t_segmento` (`t_segmento* unSegmento;`), pero en ningún lado le estás haciendo un `malloc()`, con lo cual, te falta la memoria para guardar esa estructura.

Saludos.-

**Comment by Santiagomorel** [comment]
Perfecto, me faltaba hacer el `malloc()`.
Muchas gracias!
