### ISSUE TITLE
Duda del segmento 0

### ISSUE THREAD

**Issue by agtorres1** [sisoputnfrba/foro#2986]
Buenas, tengo dudas sobre el segmento 0, lei en otros issues que voy a tener inicialmente un hueco del tamaño de la memoria menos el segmento 0, ahora lo que no entiendo es que se hace con ese segmento 0? es decir, cuando voy particionando la memoria va a ser de los huecos libres pero no entiendo para que seria el segmento 0?
O es que a cada proceso le tengo que mandar una lista con ese segmento 0?

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

El segmento 0 es un segmento que va a estar compartido entre TODOS los procesos, por eso, lo que va a pasar es que al iniciar la memoria van a tener que crear ese segmento 0 y se lo van a tener que agregar a todas las tablas de segmentos de todos los procesos que creen a lo largo de la ejecución del TP.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas @agtorres1 !
Te sirvió la respuesta de @iago64 ? Quedó alguna duda al respecto?

**Comment by agtorres1** [comment]
holaa, sisis gracias

**Comment by iago64** [comment]
No se olviden de cerrar los issues entonces 👮‍♂️
