### ISSUE TITLE
Uso correcto de diccionarios

### ISSUE THREAD

**Issue by Mimito164** [sisoputnfrba/foro#2987]
Estoy desarrollando el modulo consola.  Quiero hacer una "validación" de las instrucciones que están en el pseudocodigo, por ej: si la instrucción existe y si la cantidad de argumentos es correcta.

Para resolver esto y matar dos pájaros de un tiro pensé en usar los diccionarios que vienen en la commons, así puedo usar la función `dictionary_has_key` para ver si existe la instrucción y `dictionary_get` para obtener un entero que representa la cantidad de argumentos que debe recibir la instrucción.

La cuestión es que creo que lo pude implementar bien, osea compila y ejecuta y **"** todo está bien **"**, pero me tira el siguiente warning: `warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]`

### 🔎 Búsqueda en foros

Me fije en los archivos de testing para ver como es que fue implementado el diccionario, pero no me quedo del todo claro porque usaban estructuras y tampoco compile los tests para ver si sale la misma warning.

### 📝 Código relevante
Así es como lo tengo implementado:
```c
// ArchivoQueCreaElDiccionarioConTodaLaData.c
void inicializar_diccionario() {
    diccionario_instrucciones = dictionary_create();
    dictionary_put(diccionario_instrucciones,"SET", (void*) 2);
    dictionary_put(diccionario_instrucciones,"MOV_OUT",  (void*)(int) 2);
    ...

// ArchivoQueHaceLaValidacion.c
bool esUnaInstruccionValida(Instruccion instruccion) {
    if ( !dictionary_has_key(diccionario_instrucciones,  instruccion.instruccion) ) return false;
    if ( (int) dictionary_get(diccionario_instrucciones, instruccion.instruccion) != string_array_size( instruccion.argumentos )) return false;
    return true;
}
```

### 💻 Logs
```c
warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    5 |     if ( (int) dictionary_get(diccionario_instrucciones, instruccion.instruccion) != string_array_size( instruccion.argumentos )) return false;
      |          ^
```

**Comment by iago64** [comment]
Buenas! Cómo va?

Solo para no tener problemas con Greenpeace o alguna ONG de prorección de animales no hace falta matar ni un pajaro 😄 
Los scripts que les vamos a dar no van a contener ningún error, de hecho, si lo tienen, nos van a tener que abrir un issue para que los corrijamos, con lo cual, no pierdan tiempo en eso y enfóquense en otras funcionalidades que si están pedidas en el TP.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! 

Para sumar por si alguien se encuentra con el issue buscando `warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]`, la razón del warning es que los nodos (tanto para las listas como para los diccionarios) están pensadas para almacenar un *puntero al dato*, es decir, un `void*`, por ejemplo: 

```c
typedef enum { MOV_OUT, MOV_IN } t_codigo;

typedef struct {
    t_codigo codigo;
    int parametro1;
    int parametro2;
} t_instruccion;

t_instruccion *instruccion_create(t_codigo codigo, int parametro1, int parametro2) {
    t_instruccion *self = malloc(sizeof(t_instruccion));
    self->codigo = codigo;
    self->parametro1 = parametro1;
    self->parametro2 = parametro2;

    return self;
}

t_list *lista = list_create();
list_add(instruccion_create(MOV_OUT, 120, AX));
list_add(instruccion_create(MOV_IN, BX, 120));
```

![File_000](https://github.com/sisoputnfrba/foro/assets/39303639/34c21838-eae3-43eb-b3d4-9f57ac0f67ed)

Ahora, si lo que queremos guardar en esa lista o diccionario es solo un número entero, tenemos 2 alternativas:

a) Reservar memoria del tamaño de un `int` y pasarle el *puntero al dato* a la lista/diccionario:

```c
int *elemento = malloc(sizeof(int));
*elemento = 42;

t_list *lista = list_create();
list_add(lista, elemento);

int *first = list_get(lista, 0);
printf("el valor guardado es: %d\n", *first);
```

![File_001](https://github.com/sisoputnfrba/foro/assets/39303639/db13ab70-ee7c-4ae0-9e32-2d672070ad24)

b) Embeber el `int` en el nodo (que es lo que estaban intentando hacer), pero para esto no podemos usar `int` porque [la conversión de `int` a `void*` no está definida](https://stackoverflow.com/a/61915170/14089741) (de ahí el warning). En su lugar, podemos usar su primo hermano `intptr_t` (que es como "un entero del tamaño de un puntero"), tanto para insertar el valor como para recuperarlo:

```c
t_list *lista = list_create();
list_add(lista, (intptr_t) 42);

intptr_t first = list_get(lista, 0);
printf("el valor guardado es: %d\n", first);
```

![File_002](https://github.com/sisoputnfrba/foro/assets/39303639/a47b2335-886b-4389-87ef-f5ba2e1dc5ee)

> Nota: En el ejemplo los punteros y el `intptr_t` están midiendo 4 cuadraditos (4 bytes), pero en nuestro caso medirían 8.

Saludos
