### ISSUE TITLE
Consulta de implementación del bitmap

### ISSUE THREAD

**Issue by lucasdeferrari** [sisoputnfrba/foro#2988]
Buenas noches, tengo una duda acerca de como se implementaria el bitmap. Una vez que creo el bitarray como deberia hacer para que el mismo se muestre en el bitmap.dat? Busque en las commons y no encontre nada para hacer algo similar. 

Desde ya, muchas gracias

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Te tengo que contestar con una pregunta, investigaron `mmap()`?
Justamente les dejamos esa aclaración en el enunciado para que lo vean y se den una idea de cómo pueden implementar el bitmap (y porque no también el archivo de bloques)

Saludos.-

**Comment by lucasdeferrari** [comment]
Buenisimo muchas gracias!
