### ISSUE TITLE
Inicializacion del bitarray

### ISSUE THREAD

**Issue by lucasdeferrari** [sisoputnfrba/foro#2989]
Buenas noches, tengo una duda corta sobre la inicialización del bitarray. 
Estuve leyendo el issue #2983 en el cual el ayudante responde que para inicializarlo solamente habría que usar el block count. Pero no habria que utilizar tambien el block size? Ya que el parametro `size `de la funcion de creacion del bitarray (`bitarray_create_with_mode`) es la cantidad de bits del bitarray expresada en bytes, por lo que en ese parametro deberia ir el valor de` block count * block size` segun lo que entendí. Entendí correctamente o se me está pasando algo?

Desde ya, muchas gracias.

**Comment by RaniAgus** [comment]
¡Buenas!
Para aclarar con distintas palabras, cada bloque del file system debe tener información en dos lugares:
1- Archivo de bloques: acá tendrá un espacio de `BLOCK_SIZE` bytes para guardar los datos que almacenan los procesos con `F_WRITE` y leen con `F_READ`.
2- Bitmap: acá tendrá solamente un espacio de **un bit**, con 1 o un 0 indicando si el bloque está ocupado o libre respectivamente.

Entonces no, el tamaño del bitmap en bytes no involucra el `BLOCK_SIZE`, solo el `BLOCK_COUNT`, ya que solo hay un 1 o un 0 por cada bloque. De hecho, al recibir el tamaño en bytes necesitan dividir ese valor por 8, ya que por cada byte hay espacio suficiente para saber si 8 bloques del FS están libres u ocupados.

Saludos

**Comment by lucasdeferrari** [comment]
ahh habia entendido mal el enunciado entonces.
 De paso, queria hacer otra pregunta de la implementacion del bitmap. La idea sería que tengamos el bitarray dentro del archivo bitmap.dat y que cada vez que se modifique el bitarray se modifique el archivo? Porque utilizando mmap() no estoy logrando esto. Entiendo que el mmap() lo que hace es tratar un archivo como si fuese un array por asi decirlo, pudiendo leer y escribir sobre su contenido. Pero, si ya tengo un bitarray creado no comprendo como deberia hacer para que el mismo este dentro del archivo y que se pueda manipular con mmap(). 
Perdon si fue medio lio este mensaje, muchas gracias.

**Comment by lucasdeferrari** [comment]
Excelente muchas gracias!!
