### ISSUE TITLE
Dudas generales sobre el enunciado (más que nada relacionado a Memoria y archivos)

### ISSUE THREAD

**Issue by JoacoAltalef** [sisoputnfrba/foro#2990]
Buenas, tengo muchas consultas para hacer:

1) Al ejecutar **F_READ** o **F_WRITE**, ¿también se debe actualizar/guardar la nueva posición del puntero (hasta la posición que se leyó/escribió) no?

2)  En los **logs obligatorios** del _Kernel_ de _Leer Archivo_ y _Escribir Archivo_, ¿el puntero a mostrar tiene que ser el que se obtiene luego de que se realice la operación? ¿La _Dirección Memoria_ a mostrar tiene que ser la _física_ o _lógica_? ¿El _tamaño_ a mostrar tiene que ser el tamaño del archivo o la cantidad de bytes a leer/escribir?

3) Creo que no lo especifica el enunciado, pero cuando ocurre un **SEG_FAULT**, ¿se deben cerrar todos los archivos que el proceso tenía abierto no? Y, además de eso, ¿solo se debe mandar a _Exit_ al mismo?

4) Si un proceso abre un archivo, y viene otro e intenta abrirlo pero no puede porque ya está abierto, por lo que se bloquea, ¿cuándo debería abrir el segundo el archivo? ¿cuando se desbloquee (estando en Ready)?

5) El enunciado dice que, cuando se ejecuta un **DELETE_SEGMENT**, el _Kernel_ debe recibir de _Memoria_ la **tabla de segmentos actualizada**, pero ¿es necesario realmente esto? porque ya conozco el _Id_ del segmento a eliminar, por lo que puedo eliminarlo de la tabla de segmentos del pcb sin esperar a Memoria. Básicamente, ¿cuánto caso le tengo que hacer al enunciado?

6) Algo parecido a 5) me sucede cuando quiero inicializar un proceso, que según el enunciado _Kernel_ tiene que recibir la _tabla de segmentos_ inicial de _Memoria_, pero no estoy tan seguro de cómo sería esta tabla inicial. ¿Sería solamente una lista con un único segmento, que es el segmento 0? Porque de ser así, la única información que no tiene _Kernel_ para hacer esto es el tamaño del _segmento 0_, por lo que solo bastaría con que _Memoria_ le mande al _Kernel_ este tamaño, en vez de una tabla con un solo segmento, que es el segmento 0. Por lo que repito la pregunta: ¿cuánto caso debo hacerle al enunciado?

7) La **dirección logica** que va por parámetro en **F_WRITE** y **F_READ**, ¿es entera o hexadecimal?

8) ¿Cómo se calcula la **direccion_fisica**? Porque si hago:
`int direccion_fisica = tamanio_segmento * numero_segmento + desplazamiento_segmento;`
no sería correcto pues no todos los segmentos tienen el mismo tamaño, ¿no? ¿o se lo tengo que preguntar a _memoria_ pasándole el _pid_ y el _numero_segmento_?

9) En el **log obligatorio de CPU** de segfault, ¿el **Offset** sería `desplazamiento_segmento + cantidad_de_bytes - tamanio_segmento`? ¿o cómo se caclularía sino*? ¿Y **tamaño** sería el tamaño a leer/escribir o el del segmento?

10) No entiendo a qué se refiere con "consolidar actualizando sus estructuras administrativas." cuando habla de eliminar un segmento en la parte de **Memoria**.

Eso es todo, disculpen por la biblia de preguntas que escribí.

### 📔 Citas del enunciado
2- En el módulo **Kernel**, en la sección de **Logs mínimos y obligatorios**:
"Leer Archivo: “PID: <PID> - Leer Archivo: <NOMBRE ARCHIVO> - Puntero <PUNTERO> - Dirección Memoria <DIRECCIÓN MEMORIA> - Tamaño <TAMAÑO>"
Escribir Archivo: “PID: <PID> -  Escribir Archivo: <NOMBRE ARCHIVO> - Puntero <PUNTERO> - Dirección Memoria <DIRECCIÓN MEMORIA> - Tamaño <TAMAÑO>”

5- En el módulo **Kernel**, en la sección **Manejo de memoria**:
"Para realizar un DELETE_SEGMENT, el Kernel deberá enviarle a la Memoria el Id del segmento a eliminar y recibirá como respuesta de la Memoria la tabla de segmentos actualizada."

6- En el módulo **Kernel**, en la sección de **Planificador de Largo Plazo**:
"[...] los procesos pasarán al estado READY, enviando un mensaje al módulo Memoria para que inicialice sus estructuras necesarias y obtenga la tabla de segmentos inicial que deberá ser almacenada en el PCB."
y
En el módulo **Memoria** , en la sección _Comunicación con Kernel, CPU y File System_, en la parte de _Inicialización del proceso_:
"El módulo deberá crear las estructuras administrativas necesarias y enviar como respuesta la tabla de segmentos inicial del proceso. Esta tabla tendrá un tamaño fijo definido por archivo de configuración."

9- En el módulo **CPU** en la sección de **Logs mínimos y obligatorios**:
Error Segmentation Fault: “PID: <PID> - Error SEG_FAULT- Segmento: <NUMERO SEGMENTO> - Offset: <OFFSET> - Tamaño: <TAMAÑO>”

10- En el módulo **Memoria**, en la sección **Comunicación con Kernel, CPU y File System**, en la parte de **Eliminación de Segmento**:
"El módulo marcará el segmento como libre y en caso de que tenga huecos libres aledaños, los deberá consolidar actualizando sus estructuras administrativas."

**Comment by LeandroCarbajales** [comment]
Buenas!
Algunas las respondo cortitas así no se alarga de más

> Al ejecutar F_READ o F_WRITE, ¿también se debe actualizar/guardar la nueva posición del puntero (hasta la posición que se leyó/escribió) no?

Sí

> En los logs obligatorios del Kernel de Leer Archivo y Escribir Archivo, ¿el puntero a mostrar tiene que ser el que se obtiene luego de que se realice la operación? ¿La Dirección Memoria a mostrar tiene que ser la física o lógica? ¿El tamaño a mostrar tiene que ser el tamaño del archivo o la cantidad de bytes a leer/escribir?

Es el puntero al comenzar. El resto de los parámetros son los que recibe de CPU, dirección física y tamaño de lo que quiere leer/escribir

> Creo que no lo especifica el enunciado, pero cuando ocurre un SEG_FAULT, ¿se deben cerrar todos los archivos que el proceso tenía abierto no? Y, además de eso, ¿solo se debe mandar a Exit al mismo?

Sí, estaría incluído en lo de "liberar todos los recursos que tiene asignados"

> Si un proceso abre un archivo, y viene otro e intenta abrirlo pero no puede porque ya está abierto, por lo que se bloquea, ¿cuándo debería abrir el segundo el archivo? ¿cuando se desbloquee (estando en Ready)?

Se comportaría igual que un recurso, cuando otro proceso lo cierra (libera), se desbloquea justamente porque se le estaría asignando.

> El enunciado dice que, cuando se ejecuta un DELETE_SEGMENT, el Kernel debe recibir de Memoria la tabla de segmentos actualizada, pero ¿es necesario realmente esto? porque ya conozco el Id del segmento a eliminar, por lo que puedo eliminarlo de la tabla de segmentos del pcb sin esperar a Memoria. Básicamente, ¿cuánto caso le tengo que hacer al enunciado?

A efectos de diseño, estarían perdiendo cohesividad y de alguna manera dificultando la división de responsabilidades entre los módulos. En el extremo, al no tener esa dependencia, se les puede olvidar decirle a Memoria que borre el segmento porque igual "yo lo puedo borrar solo" y te quedaría inconsistente la tabla con la Memoria. El módulo Memoria necesita (y es quien sabe cómo) tener todas las tablas de segmentos actualizadas para poder administrar su espacio de usuario, el Kernel no, le alcanza con que Memoria le diga cómo quedaron las cosas.
Ahora, si vamos al funcionamiento del trabajo, lo pueden hacer funcionar de esa manera, pero se están comprando tener código/lógica de cómo borrar el segmento de la tabla repetido en Kernel y en Memoria.

> Algo parecido a 5) me sucede cuando quiero inicializar un proceso, que según el enunciado Kernel tiene que recibir la tabla de segmentos inicial de Memoria, pero no estoy tan seguro de cómo sería esta tabla inicial. ¿Sería solamente una lista con un único segmento, que es el segmento 0? Porque de ser así, la única información que no tiene Kernel para hacer esto es el tamaño del segmento 0, por lo que solo bastaría con que Memoria le mande al Kernel este tamaño, en vez de una tabla con un solo segmento, que es el segmento 0. Por lo que repito la pregunta: ¿cuánto caso debo hacerle al enunciado?

Misma idea que 6, al módulo Kernel no le interesa la lógica ni el código de cómo ni por qué hay un segmento 0 compartido, si por ejemplo el módulo Memoria en cambio inicializara las tablas con varios segmentos específicos por cada proceso seguramente ya no lo verían como una opción que lo haga el Kernel ;)
A efectos de este TP en particular, nos da lo mismo y lo pueden hacer funcionar igualmente, pero en mi opinión solamente se están comprando repetir código entre 2 módulos.

> La dirección logica que va por parámetro en F_WRITE y F_READ, ¿es entera o hexadecimal?

Todas las direcciones van estar en decimal.

> ¿Cómo se calcula la direccion_fisica? Porque si hago:
int direccion_fisica = tamanio_segmento * numero_segmento + desplazamiento_segmento;
no sería correcto pues no todos los segmentos tienen el mismo tamaño, ¿no? ¿o se lo tengo que preguntar a memoria pasándole el pid y el numero_segmento?

Igual que en un ejercicio de segmentación pero en decimal, necesitás el tamaño máximo de segmentos (direccionamiento lógico), la cuenta está facilitada en el enunciado en la parte de MMU.

`num_segmento = floor(dir_logica / tam_max_segmento)`
`desplazamiento_segmento = dir_logica % tam_max_segmento`

> En el log obligatorio de CPU de segfault, ¿el Offset sería desplazamiento_segmento + cantidad_de_bytes - tamanio_segmento? ¿o cómo se caclularía sino*? ¿Y tamaño sería el tamaño a leer/escribir o el del segmento?

Misma cuenta que arriba, offset es desplazamiento_segmento, es decir el offset al que quisiste acceder que hizo que salte el seg_fault. Tamaño es tamaño del segmento, justamente el seg_fault te va a saltar si el offset + el tamaño de lo que quieras leer/escribir se pase del tamaño del segmento.

> No entiendo a qué se refiere con "consolidar actualizando sus estructuras administrativas." cuando habla de eliminar un segmento en la parte de Memoria.

Al borrar un segmento te puede pasar por ejemplo que te queden 2 huecos libres contiguos, por lo que deberías consolidarlos en uno solo, de lo contrario luego se te complicaría más el algoritmo de asignación cuando quieras crear un segmento nuevo.

Saludos!
       Lean

**Comment by JoacoAltalef** [comment]
> Igual que en un ejercicio de segmentación pero en decimal, necesitás el tamaño máximo de segmentos (direccionamiento lógico), la cuenta está facilitada en el enunciado en la parte de MMU.
> 
> num_segmento = floor(dir_logica / tam_max_segmento)
> desplazamiento_segmento = dir_logica % tam_max_segmento

Sisi, el cálculo de `numero_segmento` y `desplazamiento_segmento` lo hicimos así, tenía dudas sobre `direccion_fisica`. Pero creo que entendí, por lo que me dijiste, que se debería calcular parecido a como te había dicho, solo que multiplicando por el `tamanio_maximo_segmentos` en vez del `tamanio_segmento` de ese segmento en particular. Es decir, de la siguiente forma:
`direccion_fisica = lectura_de_config.TAM_MAX_SEGMENTO * numero_segmento + desplazamiento_segmento;`
¿no?
Aunque, ahora que lo pienso, esa cuenta me daría igual a la `direccion_logica`. No, entonces sigo sin entender cómo hallar la `direccion_fisica`.

> Misma cuenta que arriba, offset es desplazamiento_segmento, es decir el offset al que quisiste acceder que hizo que salte el seg_fault. Tamaño es tamaño del segmento, justamente el seg_fault te va a saltar si el offset + el tamaño de lo que quieras leer/escribir se pase del tamaño del segmento.

Ahh ok, osea que `offset` y `desplazamiento_segmento` son sinónimos, ¿no? Había pensado que se refería a cuánto demás había querido leer/escribir, es decir, cuántos bytes superaría al tamaño del segmento.


Y te sumo una nueva duda:

11- La cantidad máxima de segmentos que puede tener un proceso, ¿de qué me sirve? ¿Solo para evaluar si se puede crear un nuevo segmento en base a este número? ¿quién debería ser el encargado de validar esto y qué ocurriría si se solicita la creación de un número de segmentos mayor a lo que se establece? Creo que no se habla mucho sobre esto en el enunciado.

El resto se entendió perfecto!
Saludos.

**Comment by LeandroCarbajales** [comment]
> Aunque, ahora que lo pienso, esa cuenta me daría igual a la direccion_logica. No, entonces sigo sin entender cómo hallar la direccion_fisica.

Pensé que la duda era sobre la dirección lógica 😅 , la dirección física se calcula también igual que en un ejercicio, la base del segmento (tomada de la tabla de segmentos) + el offset.

> Ahh ok, osea que offset y desplazamiento_segmento son sinónimos, ¿no? Había pensado que se refería a cuánto demás había querido leer/escribir, es decir, cuántos bytes superaría al tamaño del segmento

Claro, offset es desplazamiento en inglés, a veces puede causar confusión porque se usa con distintos propósitos pero en este caso se refiere, al igual que en los ejercicios, al desplazamiento dentro del segmento, por lo pronto lo único que nos importa es si se pasa del tamaño o no, no por cuánto se pasa :)

> La cantidad máxima de segmentos que puede tener un proceso, ¿de qué me sirve? ¿Solo para evaluar si se puede crear un nuevo segmento en base a este número? ¿quién debería ser el encargado de validar esto y qué ocurriría si se solicita la creación de un número de segmentos mayor a lo que se establece? Creo que no se habla mucho sobre esto en el enunciado.

Quizás es más una aclaración teórica que algo que necesiten implementar, viene a representar la parte "izquierda" de su dirección lógica, no tienen por qué preocuparse por eso si se manejan con listas dinámicas ya que nunca se pedirán segmentos que no pueden existir, sin embargo le puede servir a algún grupo que la tabla de segmentos la vea como algo estático (de tamaño igual al máximo de segmentos)

**Comment by JoacoAltalef** [comment]
Perfecto todo lean! Muchísimas gracias, me re ayudaste.
