### ISSUE TITLE
Dudas con las pruebas con el HRRN

### ISSUE THREAD

**Issue by ezequielmalfonso** [sisoputnfrba/foro#2991]
Buenas, tenemos una duda, con la prueba BASE con HRRN cuando dice:
>Con el algoritmo HRRN finaliza el proceso A primero luego de esperar bastante tiempo en la cola de ready mientras se alternan B y C.

Vemos que el proceso A finaliza primero, pero no sabemos si el tiempo que esta en ready  es lo suficiente según la prueba, ya probamos varias veces, y vemos que despues del YIELD, vuelve a la cola de ready y por la planificación vuelve a EXECUTE, les dejo parte del log:
>[INFO] 20:00:48:511 Kernel/(43032:43038): Envio solicitud a MEMORIA
[INFO] 20:00:48:512 Kernel/(43032:43038): Recibiendo Segmento 0 (Compartido) creado: Id: 0 - Dir Base: 0 - Tamanio: 128
[INFO] 20:00:48:513 Kernel/(43032:43038): “PID: 0 - Estado Anterior: NEW - Estado Actual: READY
[INFO] 20:00:48:513 Kernel/(43032:43033): PID: 0 - Estado Anterior: READY - Estado Actual: EXECUTE hrrn
[INFO] 20:00:48:513 Kernel/(43032:43033): PID: hrrn_ready_execute
[INFO] 20:00:48:924 Kernel/(43032:43032): Cliente conectado (a KERNEL_SV)
[INFO] 20:00:48:925 Kernel/(43032:43042): Envio solicitud a MEMORIA
[INFO] 20:00:48:968 Kernel/(43032:43042): Recibiendo Segmento 0 (Compartido) creado: Id: 0 - Dir Base: 0 - Tamanio: 128
[INFO] 20:00:48:968 Kernel/(43032:43042): “PID: 1 - Estado Anterior: NEW - Estado Actual: READY
[INFO] 20:00:49:485 Kernel/(43032:43032): Cliente conectado (a KERNEL_SV)
[INFO] 20:00:49:485 Kernel/(43032:43044): Envio solicitud a MEMORIA
[INFO] 20:00:49:527 Kernel/(43032:43044): Recibiendo Segmento 0 (Compartido) creado: Id: 0 - Dir Base: 0 - Tamanio: 128
[INFO] 20:00:49:527 Kernel/(43032:43044): “PID: 2 - Estado Anterior: NEW - Estado Actual: READY
**_[INFO] 20:01:00:528 Kernel/(43032:43034): PID: 0 - Recibi YIELD de CPU lo mandamos al final de la cola READY
[INFO] 20:01:00:528 Kernel/(43032:43033): PID: 0 - Estado Anterior: READY - Estado Actual: EXECUTE hrrn
[INFO] 20:01:00:528 Kernel/(43032:43033): PID: hrrn_ready_execute
[INFO] 20:01:02:531 Kernel/(43032:43034): PID: 0 - Estado Anterior: EXECUTE - Estado Actual: EXIT_**
[INFO] 20:01:02:533 Kernel/(43032:43033): PID: 2 - Estado Anterior: READY - Estado Actual: EXECUTE hrrn
[INFO] 20:01:02:533 Kernel/(43032:43033): PID: hrrn_ready_execute
[INFO] 20:01:04:538 Kernel/(43032:43034): PID: 2 - Recibi YIELD de CPU lo mandamos al final de la cola READY

En negrita puse la partee que no nos convence.
No se si con esto alcanza para que nos digan si es problema del código?

Gracias.

**Comment by LeandroCarbajales** [comment]
Buenas!
Puede ser que estén poniendo a ejecutar al que tiene menor RR en vez de al que tiene el mayor? Porque luego también elige a P2 en vez de a P1 como debería.

**Comment by D-M-Gonzalez** [comment]
Hola Ezequiel,

Nosotros vimos lo mismos, hicimos los cálculos y nos dio esto:

![image](https://github.com/sisoputnfrba/foro/assets/808691/208ee330-31f4-44c0-915a-87e1763e6f4d)

**Comment by D-M-Gonzalez** [comment]
Probamos cambiando los valores para beneficiar los procesos B y C, y nos da algo mas parecido a lo que se pide, pero con los valores originales no da eso.

**Comment by ezequielmalfonso** [comment]
Ah perfecto gracias, si nosotros ayer terminamos de armarlo asi, pq los otros dos casos de pruebas nos da bien, solo ese que difiere respecto al enunciado de pruebas.
Nos quedo igual al gantt. Muchas gracias, se ve que venimos encaminados.

**Comment by D-M-Gonzalez** [comment]
Dejo nuestros logs tambien con los procesos como pide el enunciado de la prueba:

[INFO] 12:46:01:909 KERNEL/(4034:4034): Valores de configuracion leidos correctamente
[0m[INFO] 12:46:01:910 KERNEL/(4034:4034): Memoria
[0m[31m[ERROR] 12:46:01:910 KERNEL/(4034:4034): Fallo al realizar el handshake, cerrando conexion
[0m[INFO] 12:46:01:910 KERNEL/(4034:4034): Cpu
[0m[INFO] 12:46:01:910 KERNEL/(4034:4034): Se establecio correctamente la conexion
[0m[INFO] 12:46:01:910 KERNEL/(4034:4034): File system
[0m[31m[ERROR] 12:46:01:910 KERNEL/(4034:4034): Fallo al realizar el handshake, cerrando conexion
[0m[INFO] 12:46:01:919 KERNEL/(4034:4034): Kernel listo para recibir Consolas
[0m[INFO] 12:46:13:629 KERNEL/(4034:4044): Se conecto un cliente!
[0m[INFO] 12:46:13:629 KERNEL/(4034:4044): Se crea el proceso: 0 en NEW
[0m[INFO] 12:46:13:629 KERNEL/(4034:4042): PID: 0 - Estado Anterior: PCB_NEW - Estado Actual: PCB_READY
[0m[INFO] 12:46:13:629 KERNEL/(4034:4039): Cola Ready HRRN :  0
[0m[INFO] 12:46:15:155 KERNEL/(4034:4044): Se conecto un cliente!
[0m[INFO] 12:46:15:155 KERNEL/(4034:4044): Se crea el proceso: 1 en NEW
[0m[INFO] 12:46:15:155 KERNEL/(4034:4042): PID: 1 - Estado Anterior: PCB_NEW - Estado Actual: PCB_READY
[0m[INFO] 12:46:15:155 KERNEL/(4034:4039): Cola Ready HRRN :  1
[0m[INFO] 12:46:16:605 KERNEL/(4034:4044): Se conecto un cliente!
[0m[INFO] 12:46:16:605 KERNEL/(4034:4044): Se crea el proceso: 2 en NEW
[0m[INFO] 12:46:16:605 KERNEL/(4034:4042): PID: 2 - Estado Anterior: PCB_NEW - Estado Actual: PCB_READY
[0m[INFO] 12:46:26:665 KERNEL/(4034:4041): El proceso 0 llego a yield. Se envio al final de ready
[0m[INFO] 12:46:26:665 KERNEL/(4034:4039): Cola Ready HRRN :  1 2 0
[0m[INFO] 12:46:29:670 KERNEL/(4034:4041): El proceso 1 llego a yield. Se envio al final de ready
[0m[INFO] 12:46:29:670 KERNEL/(4034:4039): Cola Ready HRRN :  2 0 1
[0m[INFO] 12:46:32:672 KERNEL/(4034:4041): El proceso 2 llego a yield. Se envio al final de ready
[0m[INFO] 12:46:32:673 KERNEL/(4034:4039): Cola Ready HRRN :  0 1 2
[0m[INFO] 12:46:35:684 KERNEL/(4034:4039): Cola Ready HRRN :  1 2
[0m[INFO] 12:46:35:684 KERNEL/(4034:4043): Finaliza el proceso 0 - Motivo: SUCCESS
[0m[INFO] 12:46:38:699 KERNEL/(4034:4041): El proceso 1 llego a yield. Se envio al final de ready
[0m[INFO] 12:46:38:699 KERNEL/(4034:4039): Cola Ready HRRN :  2 1
[0m[INFO] 12:46:41:715 KERNEL/(4034:4041): El proceso 2 llego a yield. Se envio al final de ready
[0m[INFO] 12:46:41:715 KERNEL/(4034:4039): Cola Ready HRRN :  1 2
[0m[INFO] 12:46:44:722 KERNEL/(4034:4041): El proceso 1 llego a yield. Se envio al final de ready
[0m[INFO] 12:46:44:722 KERNEL/(4034:4039): Cola Ready HRRN :  2 1
[0m[INFO] 12:46:47:730 KERNEL/(4034:4041): El proceso 2 llego a yield. Se envio al final de ready
[0m[INFO] 12:46:47:730 KERNEL/(4034:4039): Cola Ready HRRN :  1 2
[0m[INFO] 12:46:50:743 KERNEL/(4034:4041): El proceso 1 llego a yield. Se envio al final de ready
[0m[INFO] 12:46:50:743 KERNEL/(4034:4039): Cola Ready HRRN :  2 1
[0m[INFO] 12:46:53:754 KERNEL/(4034:4041): El proceso 2 llego a yield. Se envio al final de ready
[0m[INFO] 12:46:53:754 KERNEL/(4034:4039): Cola Ready HRRN :  1 2
[0m[INFO] 12:46:56:756 KERNEL/(4034:4041): El proceso 1 llego a yield. Se envio al final de ready
[0m[INFO] 12:46:56:756 KERNEL/(4034:4039): Cola Ready HRRN :  2 1
[0m[INFO] 12:46:59:759 KERNEL/(4034:4041): El proceso 2 llego a yield. Se envio al final de ready
[0m[INFO] 12:46:59:759 KERNEL/(4034:4039): Cola Ready HRRN :  1 2
[0m[INFO] 12:47:02:761 KERNEL/(4034:4041): El proceso 1 llego a yield. Se envio al final de ready
[0m[INFO] 12:47:02:761 KERNEL/(4034:4039): Cola Ready HRRN :  2 1
[0m[INFO] 12:47:05:765 KERNEL/(4034:4041): El proceso 2 llego a yield. Se envio al final de ready
[0m[INFO] 12:47:05:766 KERNEL/(4034:4039): Cola Ready HRRN :  1 2
[0m[INFO] 12:47:08:768 KERNEL/(4034:4041): El proceso 1 llego a yield. Se envio al final de ready
[0m[INFO] 12:47:08:768 KERNEL/(4034:4039): Cola Ready HRRN :  2 1
[0m[INFO] 12:47:11:770 KERNEL/(4034:4041): El proceso 2 llego a yield. Se envio al final de ready
[0m[INFO] 12:47:11:770 KERNEL/(4034:4039): Cola Ready HRRN :  1 2
[0m[INFO] 12:47:13:773 KERNEL/(4034:4041): El proceso 1 llego a yield. Se envio al final de ready
[0m[INFO] 12:47:13:773 KERNEL/(4034:4039): Cola Ready HRRN :  2 1
[0m[INFO] 12:47:15:784 KERNEL/(4034:4041): El proceso 2 llego a yield. Se envio al final de ready
[0m[INFO] 12:47:15:784 KERNEL/(4034:4039): Cola Ready HRRN :  1 2
[0m[INFO] 12:47:17:785 KERNEL/(4034:4043): Finaliza el proceso 1 - Motivo: SUCCESS
[0m[INFO] 12:47:19:785 KERNEL/(4034:4043): Finaliza el proceso 2 - Motivo: SUCCESS

**Comment by iago64** [comment]
Buenas! Cómo va?

Ahi revisamos los cálculos y efectivamente la habíamos pifiado con el estimado inicial. Por favor revisen el doc con los nuevos valores y confirmen si ahora los resultados son coherentes.

Saludos.-

**Comment by iago64** [comment]
Buenas!

En el issue #2994 esta como queda la ejecución, el resultado es: A - B - C - B - C - A... (y continúan B y C hasta que terminan)
Si no les da ese resultado es posible que estén tomando al revés el Response Ratio

Saludos.-
