### ISSUE TITLE
Problema con sem_wait en el planificador a largo plazo

### ISSUE THREAD

**Issue by cserrudo** [sisoputnfrba/foro#2992]
Buenas! Tenemos un problema con el sem_wait del semaforo de new, esta linea está en el planificador a largo plazo. este planificador lo llamamos desde el inicialice() donde nos ocupamos de inicializar las colas de estados, los semaforos y planificadores. Por cada planificador creamos un hilo. El programa compila, ejecuta y aparece en el .log el "kernel starting", o sea que ejecuta hasta antes y durante el inicialice, las lineas por debajo del inicialice ya no las ejecuta. Lo debuggeamos y es lo mismo, se queda en el inicialice, y cuando hacemos step into llega hasta la creacion del hilo por el planificador a largo plazo, entra a este y la ultima linea que aparece en verde es:

`sem_wait(&semaphore_new);`

pensabamos que con el detach se iba a solucionar pero no, por lo que entendimos el detach lo que hace es que ese hilo no sea esperado, no? no sé si lo que entendemos está mal conceptualmente, pusimos mal el detach o está mal la logica. 

### 📝 Código relevante
<!-

```c
void inicialice(t_log* logger_kernel)
{

	// Inicializa las variables
	new_list = list_create();
	exit_list =  list_create();
	ready_list = list_create();
	running_list =  list_create();
	blocked_list =  list_create();

	// Inicializo Semaforo
	sem_init(&semaphore_multiprog,0,4);
	sem_init(&semaphore_new,0,0);
	sem_init(&semaphore_ready,0,0);
	sem_init(&semaphore_running,0,1); 
	
	pthread_mutex_init(&mutex_new, NULL);
	pthread_mutex_init(&mutex_exit, NULL);
	pthread_mutex_init(&mutex_ready, NULL);
	pthread_mutex_init(&mutex_blocked, NULL);
	pthread_mutex_init(&mutex_running, NULL);

	// Creo Hilo para el planificador de largo plazo
    pthread_create(&thread_long_term, NULL, (void*)long_term_planner,NULL);

    // Creo Hilo para el planificador de corto plazo
    pthread_create(&thread_short_term, NULL, (void*)short_term_planner_exec,NULL);

    pthread_detach(thread_long_term);
    pthread_detach(thread_short_term);

}

```

```c
void long_term_planner(){
	while(1){
		sem_wait(&semaphore_new); <---- ultima linea que lee y se cuelga ahí
               //etc...
         }
  }

```

```c

int main(void) {
	// Instancio el logger
	  t_log* logger = iniciar_logger("kernel.log","proceso_kernel");

	// Levanto las configuraciones del Kernel
	  t_kernel_config *kernel_config = kernel_leer_configuracion("kernel.config");
       //Conecto a CPU
	  kernel_fd = iniciar_servidor(kernel_config->puerto_escucha,logger);

	  log_info(logger,"Kernel Starting \n");

	  inicialice(logger);<----- en el debugger se queda en esta linea

	cpu_fd = crear_conexion(kernel_config->ip_cpu, kernel_config->puerto_cpu);

	while(server_handle(kernel_fd,logger));

	log_info(logger,"Kernel finaliza\n");


}
```
-->

El debugger se queda asi despues de darle step over a la linea del sem_wait mencionada. No me deja seguir dandole dandole step over, into o return

![problema con el sem wait](https://github.com/sisoputnfrba/foro/assets/102488578/bc202802-2a63-4dc3-9af8-7cfce1bb98d7)

Gracias.

**Comment by LeandroCarbajales** [comment]
Buenas!
Por lo pronto veo normal que el hilo que hace `sem_wait(&semaphore_new)` se bloquee en esa línea dado que el semáforo está inicializado en 0, se desbloquearía recién cuando algún otro hilo haga `sem_post(&semaphore_new)`.
Luego desde el debugger pueden cambiar el hilo al que están siguiendo desde el panel de la izquierda si setearon los breakpoints correspondientes.

En este caso el [pthread_detach](https://linux.die.net/man/3/pthread_detach) no creo que tenga nada que ver, lo único que hace es que cuando el hilo termine sus recursos se liberen sin la necesidad de que otro hilo le haga join (de hecho no se le puede hacer join si ya está _detached_)

**Comment by cserrudo** [comment]
pero no es un problema que no haga lo que esta abajo de la llamada al inicialiceen el main? ese wait no me bloquea todo?

**Comment by cserrudo** [comment]
ahi me explico mi compañero que esta entendiendo mal, gracias! cierro el hilo
