### ISSUE TITLE
LD_LIBRARY_PATH - NO FUNCIONA EN LA TERMINAL

### ISSUE THREAD

**Issue by AgustinTejera** [sisoputnfrba/foro#2995]
Buenas tardes, necesitaria ayuda con lo siguiente:

1) Creamos la biblioteca compartida con el video https://www.youtube.com/watch?v=A6dhc9cCI18&ab_channel=UTNSO

2) En Run Configurations establecimos las variables para el **LD_LIBRARY_PATH** de cada modulo, al compilarlo y ejecutarlo por Eclipse funciona todo OK, pero al momento de correrlo por terminal nos indica el error "while loading shared libraries: libcompartida.so: cannot open shared object file: No such file or directory"

3) Descubrimos que esto se debe a que el proyecto no esta ubicado en el workspace de Eclipse (por ejemplo lo tenemos ubbicado en  el Desktop)

4) Por lo cual, la unica manera de poder ejecutarlo por terminal es pasando LD_LIBRARY_PATH="/home/utnso/Desktop/tp/utilsCompartida/Debug/" ./moduloAEjecutar

Duda A) Hay alguna manera de solucionar este inconveniente sin necesidad de que el projecto este creado en Workspace?? 
Duda B) De que manera deberiamos configurar la LD_LIBRARY_PATH en run configurations para que al momento de la entrega se pueda correr en terminal independientemente de donde este ubicado el projecto??

Muchas gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

A.- El export del LD_LIBRARY_PATH lo van a tener que hacer en todas las terminales que ejecuten los procesos de su TP, ya que es una variable de entorno que configuran para la ejecución dentro de esa terminal en si.
B.- Lo mas "rápido" que tiene es correr el comando `export LD_LIBRARY_PATH=<Path al archivo.so>` al inicio de cada terminal, es una fiaca pero es mas amigable correrlo 1 vez que correrlo cada vez que van a ejecutar un proceso.

Saludos.-
