### ISSUE TITLE
Archivos que terminan en CRLF y no en LF

### ISSUE THREAD

**Issue by f-and** [sisoputnfrba/foro#2996]
Buenas tardes, escribo para consultar, ya que corriendo las pruebas de DEADLOCK y ERROR, el SO me tiro errores que no habia tirado anteriormente, cosa que al fijarme mas a profundo pude encontrar que los archivos de esas dos pruebas (no las de BASE), que copié con git clone directo del repo, vinieron con el formato de lineas de Microsoft (\r\n), en vez del formato que de Linux (\n), que en el TP se especifica que la consola deberia leer únicamente en el segundo, deberia modificar el comportamiento de la consola para recibir ambos parametros?

**Comment by f-and** [comment]
PS: Se puede comprobar esto haciendo los siguientes comandos:
`git clone https://github.com/sisoputnfrba/tuki-pruebas.git; cd tuki-pruebas; git ls-files --eol`
El output esperado seria: 
i/lf    w/lf    attr/                 	BASE_1
i/lf    w/lf    attr/                 	BASE_2
i/crlf  w/crlf  attr/                 	DEADLOCK_1
i/crlf  w/crlf  attr/                 	DEADLOCK_2
i/crlf  w/crlf  attr/                 	DEADLOCK_3
i/crlf  w/crlf  attr/                 	DEADLOCK_4
i/crlf  w/crlf  attr/                 	ERROR_1
i/crlf  w/crlf  attr/                 	ERROR_2
i/lf    w/lf    attr/                 	README.md

Con i/lf w/lf siendo el caso de archivos de Linux y i/crlf w/crlf siendo el caso de archivos de Microsoft

**Comment by iago64** [comment]
Buenas! Cómo va?

Ya se parchearon los scripts, efectivamente nos quedó mal el encoding del final de línea, por favor volve a correr las pruebas y comentamos cualquier cosa.

Saludos.-

**Comment by MiltonMartorello** [comment]
Abriendolo con el Visual Code en la VM se puede pasar a LF desde el extremo inferior derecho y luego guardar y soluciona el problema. También nos pasó que tardamos bastante en darnos cuenta del problema.

**Comment by f-and** [comment]
Muchas gracias a ambos, si los pase a LF y anduvo todo perfecto despues. Cierro el issue.
