### ISSUE TITLE
Duda enunciado

### ISSUE THREAD

**Issue by MattP2001** [sisoputnfrba/foro#2997]
Buenas! Consulta sobre los logs obligatorios de cpu. 

Acceso Memoria: “PID: <PID> - Acción: <LEER / ESCRIBIR> - Segmento: <NUMERO
SEGMENTO> - Dirección Física: <DIRECCION FISICA> - Valor: <VALOR LEIDO / ESCRITO>”

Entiendo que solo se hace el log cuando es cpu el que accede a memoria pero con el grupo no estamos del todo seguros. Me lo podrian aclarar? Muchas gracias!!

Ahh tambien tanto en fopen, fwrite, mov in y mov out hay q checkear si hay seg fault, no?
y la ultima, el numero_segmento es igual al id_segmento? pq se calcula dividiendo por el tam_max_segmento, pero el tamaño de cada segmento es variable.

**Comment by LeandroCarbajales** [comment]
Buenas!
Así es, serían los accesos a Memoria que hace la CPU directamente.

El seg_fault lo deberían chequear siempre que traducen una dirección lógica a física justamente para no terminar leyendo o escribiendo por fuera del segmento.

Sí, numero_segmento o id_segmento los estamos usando como sinónimos en este caso.

Te resuelve las dudas?

Saludos!
       Lean

**Comment by MattP2001** [comment]
Clarísimo, mil gracias!
