### ISSUE TITLE
Duda sobre aplicar la regla de catedra al planificador de corto plazo

### ISSUE THREAD

**Issue by Fcallero** [sisoputnfrba/foro#2998]
Buenas, tenemos una duda y es si hay que contemplar la regla de cátedra con el HRRN y FIFO? por ejemplo,  si un proceso que vuelve de IO vs un proceso que se desalojo voluntariamente, se le debe dar prioridad al proceso desalojado, o no es necesario? En el enunciado del TP no dice nada, pero surgió la duda

**Comment by LeandroCarbajales** [comment]
Buenas!
Eso de que lleguen a ready en el mismo instante como en los ejercicios no existe en la realidad y por eso se toma un criterio lo más objetivo posible para los ejercicios. A nivel código del TP tampoco es algo que te pueda llegar a pasar, quien llega primero es el primero que se agregó a la cola/lista, no hay desempate en ese sentido.

Saludos!
       Lean

**Comment by Fcallero** [comment]
ah buenisimo gracias
