### ISSUE TITLE
Duda sobre como atiende peticiones memoria

### ISSUE THREAD

**Issue by alecaragiulo** [sisoputnfrba/foro#3000]
Buenas! 

mi duda era respecto de si la memoria atiende las peticiones de a una o puede atender peticiones de distintos módulos a la vez, desde ya muchas gracias .

**Comment by LeandroCarbajales** [comment]
Buenas!
No hay restricciones al respecto en el enunciado, sin embargo lo más recomendable sería que pueda atender peticiones de distintos módulos _concurrentemente_ dado que cada uno tiene su propia conexión.
