### ISSUE TITLE
Ejecución de scripts de prueba

### ISSUE THREAD

**Issue by Martin-Fedorenko** [sisoputnfrba/foro#3001]
Buenas tardes! Una consulta respecto a las pruebas. Las instrucciones hay que ingresarlas todas "al mismo" tiempo (en el tiempo cero) y que el programa decida quien ejecute o puedo ejecutar un script, luego otro y luego otro (a mi ritmo por así decirlo). Mi pregunta se debe a que si ingreso un script y luego el otro, es muy probable que el primero ya haya terminado.

![image](https://github.com/sisoputnfrba/foro/assets/67556470/20abb250-feb9-4501-9d59-753994e1405b)

**Comment by LeandroCarbajales** [comment]
Buenas!
Si te podés armar un script para la terminal (en bash por ejemplo) que ejecute las 3 consolas en orden te ahorrarías tener que hacerlo a mano. Sin embargo, con tener 3 terminales listas para ejecutar las consolas de a una (a tu ritmo) deberías estar bien dado que el proceso A tarda 12 segundos en terminar su primer ráfaga.

**Comment by Martin-Fedorenko** [comment]
Muchas gracias!!
