### ISSUE TITLE
El socket de servidor cada tanto usa un puerto random

### ISSUE THREAD

**Issue by maxiostro** [sisoputnfrba/foro#3002]
Sin ninguna explicación aparente, a veces cuando levantamos el un socket de servidor (tanto para CPU como para Kernel), se bindea en un puerto al azar (de 5 digítos). Lo probamos en varios entornos (tanto la VM de Ubuntu como WSL) y no funciona. Probamos hacer make clean y limpiar todo lo posible, y tampoco lo arregla. Simplemente, a veces usa el puerto correcto y a veces no. Puedo confirmar que el puerto al que estoy intentando bindear no está en uso (no aparece en "sudo lsof -i -P -n | grep LISTEN").
Esto lo vimos hoy en el checkpoint con uno de los asistentes, que me pidió que arme un issue, para poder revisarlo con tiempo (porque es raro).

### 📚 Documentación oficial
- Sockets: https://www.gnu.org/software/libc/manual/html_node/Sockets.html

### 🔎 Búsqueda en foros
Busqué mucho en Stackoverflow, algunas cosas, pero nada que funcione.

### 📝 Código relevante
```c
int socket_initialize(char* ip, char* port) {
	struct addrinfo hints, *server_info;
	memset(&hints, 0, sizeof(hints));
	hints.ai_family = AF_UNSPEC;
	hints.ai_socktype = SOCK_STREAM;
	hints.ai_flags = AI_PASSIVE;
	getaddrinfo(ip, port, &hints, &server_info);

	// Creamos el socket de escucha del servidor
	int server_socket = socket(server_info->ai_family, server_info->ai_socktype, server_info->ai_protocol);
	if (server_socket == -1) return -1;

	if (ip == NULL) { // Para servidor
		// Asociamos el socket a un port
		bind(server_socket, server_info->ai_addr, server_info->ai_addrlen);
		// Escuchamos las conexiones entrantes
		if(listen(server_socket, SOMAXCONN) == -1) return -1;
	} else { // Para cliente
		// Ahora que tenemos el socket, vamos a conectarlo
		if (connect(server_socket, server_info->ai_addr, server_info->ai_addrlen) == -1) return -1;
	}

	freeaddrinfo(server_info);
	return server_socket;
}

int socket_initialize_server(char* port) {
	return socket_initialize(NULL, port);
}

int main(int argc, char** argv) {
	//...
	char* port = config_get_string_value(config, "PUERTO_ESCUCHA");	 // Obtenemos el puerto con el que escucharemos conexiones
	int socket_kernel = socket_initialize_server(port);
	//...
```

### 🐛 Cómo reproducir el error
Al ejecutarlo (al menos dentro del TP), pasa al menos 1 de cada 3 veces. A la primera normalmente funciona. Al detener el proceso y levantarlo de vuelta, ya no.

### 💻 Logs
**Cuando levanta bien**
```bash
maxi@Maxi-PC:~/tp-2023-1c-OneLeito$ sudo lsof -i -P -n | grep LISTEN
node     23 maxi   18u  IPv4  29702      0t0  TCP 127.0.0.1:36753 (LISTEN)
cpu     551 maxi    4u  IPv4  23738      0t0  TCP *:8001 (LISTEN)
kernel  628 maxi    4u  IPv4  23762      0t0  TCP *:7848 (LISTEN)
```
**Cuando levanta mal**
```bash
maxi@Maxi-PC:~/tp-2023-1c-OneLeito$ sudo lsof -i -P -n | grep LISTEN
node     23 maxi   18u  IPv4  29702      0t0  TCP 127.0.0.1:36753 (LISTEN)
kernel  628 maxi    4u  IPv4  23762      0t0  TCP *:7848 (LISTEN)
cpu     994 maxi    4u  IPv4  21545      0t0  TCP *:43959 (LISTEN)
```
 (En muchos casos tanto CPU y Kernel lo obitienen mal)
Los logs de los programas siempre son los esperados, diciendo el número de puerto en el que debería estar levantado.

**Comment by iago64** [comment]
Buenas! Cómo va?

Estuve un rato dándole vueltas al asunto para ver cuál era el problema que estaba generando que les pase esto y despues de hacer algunas pruebas encontré la forma de "replicar" el error, simplemente lo que tienen que hacer es correr mas de 1 proceso que intente tomar el mismo puerto 😄 

![image](https://github.com/sisoputnfrba/foro/assets/1622109/9b0218b5-ab35-47c8-82f5-9f1db3ac0056)

Por las dudas, si quieren replicar el error, el programa que arme (copiando el código que dejaron) es el siguiente:

```c
#include <stdlib.h>
#include <stdio.h>
#include<sys/socket.h>
#include<unistd.h>
#include<netdb.h>
#include<commons/log.h>
#include<commons/collections/list.h>
#include<string.h>
#include<assert.h>

int socket_initialize(char* ip, char* port) {
	struct addrinfo hints, *server_info;
	memset(&hints, 0, sizeof(hints));
	hints.ai_family = AF_UNSPEC;
	hints.ai_socktype = SOCK_STREAM;
	hints.ai_flags = AI_PASSIVE;
	getaddrinfo(ip, port, &hints, &server_info);

	// Creamos el socket de escucha del servidor
	int server_socket = socket(server_info->ai_family, server_info->ai_socktype, server_info->ai_protocol);
	if (server_socket == -1) return -1;

	if (ip == NULL) { // Para servidor
		// Asociamos el socket a un port
		bind(server_socket, server_info->ai_addr, server_info->ai_addrlen);
		// Escuchamos las conexiones entrantes
		if(listen(server_socket, SOMAXCONN) == -1) return -1;
	} else { // Para cliente
		// Ahora que tenemos el socket, vamos a conectarlo
		if (connect(server_socket, server_info->ai_addr, server_info->ai_addrlen) == -1) return -1;
	}

	freeaddrinfo(server_info);
	return server_socket;
}

int socket_initialize_server(char* port) {
	return socket_initialize(NULL, port);
}

int main(int argc, char* argv[]) {
    char* port = "8001";
    int socket_kernel = socket_initialize_server(port);
    char* input = getc(stdin);
    return 0;
}
```

Basicamente su problema no es que les asigna un puerto random porque le pinta al SO, su problema es que no estan matando instancias viejas que se ve que quedan ejecutando en background ó estan poniendo el mismo puerto por error, solo por las dudas, revisen con `htop` que no tengan corriendo otras instancias del mismo proceso.
Por las dudas, les cito un [comentario de Agus de hace 1 año](https://github.com/sisoputnfrba/foro/issues/2678#issuecomment-1146814640) donde vimos que para estos casos pueden forzar que se reutilice el socket (y asi evitar que el SO les asigne otro al azar):

> Pueden agregar las siguientes 2 líneas después de llamar a `socket()` para setear ese puerto como reusable antes de llamar a `bind()`:
> 
> ```c
> int fd; // este sería el File Descriptor que devuelve socket()
> 
> int yes = 1;
> setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &yes, sizeof yes);
> ```

Saludos.-

**Comment by iago64** [comment]
Buenas! @maxiostro Cómo va?

Pudiste analizar / probar algo de lo que te deje en el comment?

Saludos.-

**Comment by iago64** [comment]
Cerramos el issue por inactividad, cualquier cosa lo pueden volver a abrir o crear uno nuevo haciendo referencia.
