### ISSUE TITLE
Consulta sobre memory leaks en la entrega

### ISSUE THREAD

**Issue by Martin-Fedorenko** [sisoputnfrba/foro#3004]
Buenos días! 

Probando el TP me surgieron dos inquietudes:

-¿Se va a tener en cuenta durante la entrega cualquier comportamiento errático o no deseado a la hora de "apagar los distintos módulos" para volver a ejecutarlos de nuevo? (Ej: apago kernel y CPU tiene algun comportamiento no deseado o tira segmentation fault). 

-¿Que tanta tolerancia habrá a los memory leaks? (Ej: Si todas las pruebas se ejecutan de manera esperada pero hay memory leaks en alguno de los módulos)

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- No vamos a evaluar eso ya que el TP se prueba con **todos** los módulos funcionando.

2.- La tolerancia va a ser que nos demos cuenta que hay, es decir, si tienen un leak que no se nota en `htop` no nos vamos a dar cuenta. Las pruebas **no se corren con valgrind**, pero si con un `htop` siempre a la vista y si la memoria crece continuamente mientras se ejecutan las pruebas es una señal clara de que tienen un leak.
De todas formas, va a haber una prueba específica para detecar leaks groseros y se van a dar cuenta uds solos al momento de ejecutarla si los tienen o no.

Saludos.-
