### ISSUE TITLE
Consulta sobre los uint y los semáforos

### ISSUE THREAD

**Issue by irinaperezg** [sisoputnfrba/foro#3005]
Holis, que tal? Quería hacer una consulta con respecto al uso de uint32_t ya que con mi grupo para la parte de la ejecución de las instrucciones WAIT y SIGNAL utilizamos semáforos contadores de la siguiente manera:
```
bool semaforo_recurso_puedo_utilizar_recurso(t_semaforo_recurso *self)
{
    uint32_t instancias = semaforo_recurso_get_instancias(self);
    return instancias >= 0;
}

bool semaforo_recurso_debe_bloquear_proceso(t_semaforo_recurso *self)
{
    return !semaforo_recurso_puedo_utilizar_recurso(self);
}

```
Al principio no funcionaba correctamente porque los procesos no se bloqueaban y nos dimos cuenta a que se debía a que el 'atributo' de las instancias de nuestras struct de semáforos era un uint32_t, por lo tanto nunca iba a tomar valores negativos.
```
struct semaforo_recurso
{
    uint32_t instancias;
    t_estado *estadoRecurso;
};
typedef struct semaforo_recurso t_semaforo_recurso;
```

Cuestión que lo cambiamos a un int32_t y todo funcionó bien y las pruebas pasaron :) pero cuando lo mostramos ayer un ayudante nos dijo que si o si debiamos usar uint32_t porque sino podía llegar a romper, esto es estrictamente necesario? int32_t no sirve para mantener el mismo tamaño sin importar la arquitectura?
como podríamos resolver esto usando uint32_t? porque como basicamente planteamos todo el tema semáforos basándonos en la ídea de que la cantidad de procesos bloqueados era un número negativo, habria que cambiar eso a algo tipo hacer un contador de procesos bloqueados o algo por el estilo??
saludos <3

**Comment by iago64** [comment]
Buenas! Cómo va?

Es posible que haya habido un mal entendido durante el check porque era un griterío, la idea del uso de uint32_t e int32_t es que sean implementaciones que no sean susceptibles a cambios de arquitectura como bien decís.
En este caso, si les está funcionando con int32_t, pueden dejarlo así 😊 

Saludos.-

**Comment by irinaperezg** [comment]
Genial, muchas gracias!
