### ISSUE TITLE
Preguntas sobre FS y manejo de FS desde Kernel 

### ISSUE THREAD

**Issue by irinaperezg** [sisoputnfrba/foro#3010]
Hola! Que tal? Quería hacer algunas consultas sobre el manejo de FS
1) Siempre que se haga fclose, fseek, ftruncate, fread y fwrite, kernel tiene que chequear que ese proceso tenga ese archivo abierto no? que pasa si no lo tiene? se debe terminar el proceso??
2) Igualmente con cada instruccion, el fs debe chequear que ese archivo exista? si no existe, se termina el proceso tambien? (excepto cuando le solicitan crear un nuevo archivo)
3)
> Actualizar Puntero Archivo: “PID: <PID> - Actualizar puntero Archivo: <NOMBRE ARCHIVO> - Puntero <PUNTERO>” Nota: El valor del puntero debe ser luego de ejecutar F_SEEK.

A que se refiere que el valor del puntero debe ser luego de ejecutar f_seek? no es el mismo puntero que se pasa en la instrucción? (ósea la ubicación que se le pasa)
4) Es necesario que el fs se ocupe de abrir un archivo? abrir un archivo no representa únicamente que el kernel lo abra en su tabla global de archivo? ósea, el kernel debe preguntarle al fs si el archivo existe o no, pero de "abrirlo" no se ocupa kernel? por que fs debería hacer un log cuando "abre" un archivo si en realidad lo único que hace fs es verificar si exista? tal vez lo estoy interpretando mal.

Saludos <3

**Comment by iago64** [comment]
Bueenas! ¿Cómo va?

1.- No vamos a hacer scripts que pidan algo de un archivo sin abrirlo previamente.

2.- Idem punto 2, al abrir un archivo si no existe se crea, asi que, no se va a dar la situación.

3.- Efectivamente, es el valor en el que queda el puntero / lo que llega por F_SEEK, pero lo aclaramos por si alguien pone el log **antes** de ejecutar F_SEEK.

4.- Si, porque si el archivo no existe el kernel tiene que pedir la creación del mismo y cito al enunciado:

> Abrir Archivo
Esta operación consistirá en verificar que exista el FCB correspondiente al archivo y en caso de que exista deberá devolver un OK, caso contrario, deberá informar que el archivo no existe.

No parece una gran operación, pero tiene su cuota de sentido cuando le sumas que el kernel tiene que saber si un archivo existe o no para actuar en consecuencia (en este tp lo crea, **en otro tp de otro cuatrimestre** puede ser que abrir un archivo que no existe mate el proceso).

Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas!
Exactamente, **para este TP en particular** no son necesarios esos chequeos en las interacciones con el FS ya que no buscamos probar esos casos de error. Los casos de error esperados por las instrucciones y que tienen su comportamiento definido (finalizar al proceso por ejemplo) son solamente los que están definidos en el enunciado (como seg_fault o recurso inexistente).

Queda más clara la idea?
Saludos!
       Lean

**Comment by irinaperezg** [comment]
Genial, quedó claro
Gracias
