### ISSUE TITLE
Dudas con el Archivo de Bloques

### ISSUE THREAD

**Issue by mcisilino** [sisoputnfrba/foro#3012]
Hola! Tengo un par de dudas con el archivo de bloques que no estoy pudiendo terminar de resolver.
Entiendo que este archivo contiene a todos los bloques del filesystem, por lo que cada uno va a tener el tamaño que esté especificado en el `BLOCK_SIZE`, pero lo que no me termina de cerrar del todo es qué información se debería almacenar en cada bloque.
Por otro lado otra pregunta que me surgió es si cada vez que se quiere "guardar" algo en un bloque hay que verificar que haya espacio suficiente. Imagino que si pero no estoy segura si estoy entendiendo bien o se me mezclaron las cosas

Saludos y graciass!

**Comment by iago64** [comment]
Buenas! Cómo va?

La información que se almacena en los bloques, es el **contenido** de los archivos.

No les vamos a hacer escribir en un archivo que no tenga el espacio suficiente. Ahora, lo que si puede pasar es que empieces a escribir en un bloque, lo llenes y tengas que pasar al siguiente, creo que a esto te referías con el espacio suficiente no?

Saludos.-

**Comment by mcisilino** [comment]
Claro si, a eso me refería. Creo que ya me quedó más claro entonces
Graciass!

**Comment by iago64** [comment]
Si esta resuelta la duda, no te olvides de cerrar el issue 👮‍♂️
