### ISSUE TITLE
Consulta persistencia archivos fileSystem

### ISSUE THREAD

**Issue by lucasdeferrari** [sisoputnfrba/foro#3013]
Buenas noches, tengo una consulta con el tema de la persistencia de los archivos del fileSystem. La idea seria que cada vez que se corra el modulo los archivos esten limpios, sin ningun valor para que puedan trabajar libremente verdad? Pero, no encuentro la forma de limpiar el bitarray del bitmap. Intente modificando un bit del array, luego haciendo el bitarray_destroy() y luego levantar de nuevo el modulo, (sin modifucar de nuevo ese bit) testear ese bit, y me daba que igualmente tenia el valor  1; cuando deberia ser 0.

### 📝 Código relevante
```
bitarray_set_bit(bitarray_mapeado, 0);
   bitarray_set_bit(bitarray_mapeado, 1);
   bitarray_set_bit(bitarray_mapeado, 2);

   // Ver el valor que acabo de modificar
   bool valor = bitarray_test_bit(bitarray_mapeado, 0);
   bool valor2 = bitarray_test_bit(bitarray_mapeado, 1);
   bool valor3 = bitarray_test_bit(bitarray_mapeado, 2);
   bool valor4 = bitarray_test_bit(bitarray_mapeado, 3);


   printf("El valor del bit 0 es %i\n", valor);
   printf("El valor del bit 1 es %i\n", valor2);
   printf("El valor del bit 2 es %i\n", valor3);
   printf("El valor del bit 3 es %i\n", valor4);

   // Sincronizar los cambios con el archivo en disco
   if (msync(mapping, block_count, MS_SYNC) == -1) {
	   perror("Error en msync");
	   exit(1);
   }
    // Liberar recursos después de su uso
    bitarray_destroy(bitarray_mapeado);
    if (msync(mapping, block_count, MS_SYNC) == -1) {
   	   perror("Error en msync");
   	   exit(1);
      }
    munmap(mapping, block_count);
    close(fd);
    fclose(archivo_bitmap);
```
Aca es donde hago lo que comento. Cuando levanto el modulo por segunda vez, lo que hago es comentar la linea  `bitarray_set_bit(bitarray_mapeado, 1);` por ejemplo, para que me devuelva 0.

Desde ya, muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

La idea del FS es que levanten lo que tengan, si no, medio que pierde el sentido de "persistencia" del FS, con lo cual, estaría mal que limpien el bitarray cada vez que inician el FS.

Saludos.-

**Comment by lucasdeferrari** [comment]
Buenisimo gracias
