### ISSUE TITLE
Dudas generales sobre la implementacion de memoria

### ISSUE THREAD

**Issue by tomasmartinez02** [sisoputnfrba/foro#3014]
Hola, estamos con algunas dudas en cuanto a la implementación general de memoria.
- Los segmentos creados deben ocupar parte de la memoria de usuario o deben ir por fuera de esta memoria? es decir, deberíamos usar algo como un calloc para simular la ocupación de esta memoria?
- En la memoria de usuario van a estar los archivos del filesystem o esta memoria de usuario va a ser como la RAM y los archivos de filesystem deberían estar en el disco?
- el segmento 0 tiene que ocupar realmente espacio de la memoria de usuario?
- Debemos trabajar con las direcciones físicas o lógicas? Y como podríamos obtener estas?
Desde ya gracias.

**Comment by iago64** [comment]
Buenas! Cómo va?

Vamos a desarmar la ensalada de conceptos:

1.- Los segmentos van a crearse **dentro** de un `malloc()`, es decir, uds arrancan la memoria, leen la config y ven que les dice tamaño de la memoria y con eso, hacen un `malloc()` de ese tamaño.
Una vez tienen ese malloc, van a tener que poder "crear" segmentos, que esos segmentos va a ser una división de ese `malloc()`, para eso, van a tener que crearse alguna estructura administrativa (como las que vieron en la teoría) para saber donde empieza y donde termina (o que tamaño tiene) cada segmento y a quien pertenece.

2.- Los archivos del FS no tienen nada que ver con la memoria, lo que si puede pasar es que tengan que escribir algo de la memoria a un archivo (F_WRITE) o que tengan que leer algo de un archivo y guardarlo en la memoria (F_READ) pero esas son operaciones que son parecidas a como funcionan MOV_OUT y MOV_IN de la CPU.

3.- El segmento 0 si, es parte del espacio de memoria del usuario y es compartido entre **todos** los procesos, por eso te conviene crearlo de entrada cuando armas todas tus estructuras administrativas.

4.- Las direcciones lógicas son las que les vamos a pasar en los scripts para que ejecuten, el módulo memoria debería trabajar con las direcciones físicas. 
Pueden para implementar las direcciones físicas tomarse una licencia poética (por decirlo de una manera) y decir que sus direcciones físicas empiezan en 0 y consideran como posición 0 lo que les devuelve el `malloc()` del punto 1 y de ahí se mueven con el resultado del `malloc()` + dirección fisica.

Saludos.-

**Comment by tomasmartinez02** [comment]
Buenisimo, muchas gracias!
Tengo una ultima duda, en la cantidad de segmentos que tiene un proceso esta incluido el segmento 0? Es decir que si el archivo de configuracion me dice que un proceso puede tener 12 segmentos, este puede tener 11 + el segmento 0 o 12 + el segmento 0?

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

La cantidad total es la cantidad total de entradas en la tabla, por eso en tu ejemplo serían 11 + el segmento 0 (e irian del 0 al 11 😉) 

Saludos.-

**Comment by tomasmartinez02** [comment]
Muchisimas gracias!
