### ISSUE TITLE
ID del segmento

### ISSUE THREAD

**Issue by Hamamura-S** [sisoputnfrba/foro#3015]
Buenas, tengo estas dudas sobre el ID del segmento

1. La dirección logica para el TP se define `NroSegmento-Desplazamiento`. NroSegmento es el ID del segmento?
2. La idea es que ese ID se repite en las distintas tablas de segmento verdad? Quiero decir, cada tabla puede tener su propio "segmento **1**"? O dicho de otra forma, cada proceso puede ejecutar su propio `CREATE_SEGMENT 1 [tamaño]`

Si es así, sí necesito indexar cada tabla de segmentos al proceso que le corresponde(usando el PID por ejemplo). Pero creo que no está explicitada la unicidad o no del ID de segmento. Saludos

### 📔 Citas del enunciado/videos
> MMU
A la hora de traducir direcciones lógicas a físicas, la CPU debe tomar en cuenta que el esquema de memoria del sistema es de Segmentación. Por lo tanto, las direcciones lógicas se compondrán de la siguiente manera:
[N° Segmento | Desplazamiento]

**Comment by LeandroCarbajales** [comment]
Buenas!
Sí, el "id" de la tabla de segmentos sería sinónimo de N° segmento en este caso. Luego cada proceso tiene sus segmentos, en ese sentido sí, cada tabla (cada proceso) tendría su propio segmento 1.

Te aclara la duda?

Saludos!
       Lean

**Comment by Hamamura-S** [comment]
Sí, gracias👌
