### ISSUE TITLE
Duda sobre asignación de un hueco de mayor tamaño al segmento.

### ISSUE THREAD

**Issue by FacundoPiaggio** [sisoputnfrba/foro#3017]
Buenas tardes!

Tenemos una duda sobre que pasa cuando se quiere crear un segmento que tiene un tamaño menor al hueco encontrado por el algoritmo.

Digamos que el algoritmo es First fit, por ejemplo, y el primer hueco que encuentra libre es de 512 bytes. Si se quiere crear un segmento de 64 ¿se le asigna ese hueco de 512?, ¿o habría que particionarlo para darle exactamente lo que necesita?, quedando de esta manera, un "nuevo" hueco ocupado de 64 y el hueco libre de 448.

Imagino que habría que asignarle el de 512, ya que de la otra forma FIRST FIT parece mas un BEST, pero por las dudas pregunto

Saludos!

**Comment by LeandroCarbajales** [comment]
Buenas!
Segmentación maneja particiones dinámicas, por lo que siempre vas a asignar solamente el espacio necesario. Por lo que en tu ejemplo ocurriría exactamente eso: 

> quedando de esta manera, un "nuevo" hueco ocupado de 64 y el hueco libre de 448.

La idea justamente es que inicialmente tienen un solo hueco libre "grande" y el mismo se irá achicando o partiendo a medida que se creen y se liberen segmentos.
En el ejemplo que das, la diferencia es que un BEST fit buscaría que ese hueco libre que te queda luego de asignar un segmento sea lo más chico posible en vez de partir un hueco libre más grande.

El caso que das de que se asigne un hueco libre completo aunque sobre espacio sería un manejo de particiones fijas que no es lo que se pide en este TP.

Queda más clara la idea?
Saludos!
        Lean

**Comment by FacundoPiaggio** [comment]
Excelente lean, muy claro!.

Solo me quedó una duda con la diferencia que mencionas del BEST. 
¿A que te referís con "... BEST fit buscaría que ese hueco libre que te queda luego de asignar un segmento sea lo mas chico posible"? 
¿No debería ser que BEST ya busque al mas chico y luego deja libre lo restante?. Digamos que se quiere crear uno de 32 y el mas chico es de 64, BEST va a encontrar ese de 64, asignarle uno de 32 al segmento y dejar uno libre de 32.

**Comment by LeandroCarbajales** [comment]
Claro, uno es consecuencia del otro :) Al buscar al más chico, deja un restante más chico.

Si tuvieras 2 huecos libres, uno de 256 y otro de 64. Y quisieras asignar un segmento de 32:
BEST fit busca al más chico, en este caso de 64, por lo que te quedarían el hueco libre 256 y otro de 32, FIRST fit en cambio tomaría al primero quedando un hueco libre de 224 y el de 64.

**Comment by FacundoPiaggio** [comment]
Ahhh excelente, ahí entendí esto.

Sin embargo se me ocurrió otra pregunta que no tiene mucho que ver pero la hago acá así no abro otro issue. 
¿Cuando es necesario que se consoliden los huecos? ¿cada vez que haya que compactar? o ¿cada vez que se libera un hueco, tendría que revisar si es posible consolidar?

**Comment by LeandroCarbajales** [comment]
Cito al enunciado:

> Eliminación de Segmento
El módulo marcará el segmento como libre y en caso de que tenga huecos libres aledaños, los deberá consolidar actualizando sus estructuras administrativas.

**Comment by FacundoPiaggio** [comment]
Ahh mala mía jeje.

Te agradezco mucho lean, siempre muy claro!
