### ISSUE TITLE
Duda con tamaño de la tabla de segmentos

### ISSUE THREAD

**Issue by MarcosGurruchaga** [sisoputnfrba/foro#3018]
### 📔 Citas del enunciado/videos
Inicialización del proceso
El módulo deberá crear las estructuras administrativas necesarias y enviar como respuesta la tabla de
segmentos inicial del proceso. Esta tabla tendrá un tamaño fijo definido por archivo de configuración.

![image](https://github.com/sisoputnfrba/foro/assets/83126979/d44960ae-a064-474a-acb3-0f6613fa39e4)

**Duda:**
Tengo una duda, el "tamaño fijo definido por archivo de configuración" seria el campo CANT_SEGMENTOS de la config? Osea que la cantidad de segmentos máxima que puede tener un proceso en su tabla es ese número? Por ejemplo la tabla de segmentos puede tener hasta 16 entradas, de la id 1 hasta la 15 por ejemplo, teniendo en cuenta que la 0 siempre va estar tomada por el segmento 0.

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Efectivamente, la cantidad máxima se segmentos que va a tener un proceso es ese valor, por eso como bien decís, si ahi ponemos 16, van a tener segmentos del 0 al 15 (con la salvedad que el 0 ya va a venir creado por default y se van a poder crear / eliminar del 1 al 15)

Saludos.-

**Comment by MarcosGurruchaga** [comment]
Gracias por la respuesta, cierro hilo.
