### ISSUE TITLE
Error despues del deserializar

### ISSUE THREAD

**Issue by Danymmereles** [sisoputnfrba/foro#3019]
Buenas noches,

Disculpen la hora pero venimos teniendo un problema con una deserializacion. Resulta que estabamos haciendo una de las pruebas para ver como corria pero andabamos teniendo problemas al momento de recuperar el contexto. El contexto se deserializa correctamente (dejo captura del debuggeo de esa parte para que vean que recibi el proceso y tengo pid = 0)

![image](https://github.com/sisoputnfrba/foro/assets/47753130/39af6910-91ae-4f2f-adb9-1075b53d21e8)

Pero, al volver al main, vemos que contexto sigue vacio. Le declaramos el contextoRecibido = NULL al inicio. Tambien intentamos con no igualar a nada, solo declararlo. Poner un malloc para inicializarlo no nos resulto correcto porque es hacer 2 malloc solo que uno le pasa lo que tiene al otro y deberiamos hacer un free. Asi que no sabriamos que hacer.

![image](https://github.com/sisoputnfrba/foro/assets/47753130/7093afe0-ca30-47f2-abc1-0d45ce5748b3)

En ese if ya muere y el error que salta es "Segmentation Fault". Esto ya lo hicimos funcionar y no tocamos nada desde la ultima vez que corrio correctamente. Le sacamos el if y se lo volvimos a escribir porque era como estaba en el momento que funciono pero no dio resultado. Se nos acabaron las posibles soluciones. Les dejo adjuntado como inicia el contexto al iniciar la serializacion como para que se vea que si cargan cosas al finalizar esta funcion.

![image](https://github.com/sisoputnfrba/foro/assets/47753130/f7a20836-028b-493e-a7f6-0898b0e6d8cb)

Desde ya mil disculpas por la hora y mil gracias por el tiempo

**Comment by iago64** [comment]
Buenas! Cómo va?

Las capturas de pantalla son un problema porque no nos dejan copiar el código y replicarlo, con lo cual, ahi vuelvo a pedir lo mismo de siempre, de que no nos suban capturas de pantalla.

Dicho eso, cualquier problema de memoria, lo segundo que tienen que hacer despues de debuguear es ver con Valgrind que esta pasando, porque si bien tienen identificado el origen del problema, es muy posible que todo venga atado a algun free o alguna referencia que estan perdiendo.

A priori, la función de deserializar contexto parece estar bien (aunque de nuevo, es una apreciación sin poder copiar el código y verlo corriendo), ahora la pregunta del millon es, como tienen definida la variable de contextoRecibido, ya que eso puede ser que tenga algo que ver.

Saludos.-

**Comment by mesaglio** [comment]
Sumo un granito de arena, hice tests de las funciones de serializacion y deserializacion y no tiene errores.
Salu2!

**Comment by LeandroCarbajales** [comment]
Buenas @Danymmereles !
Genial que se haya solucionado reinstalando la VM, viendo solamente las imágenes no se veía ningún error a simple vista.

Recuerden que quien abrió el issue lo puede cerrar cuando el problema/duda está resuelta :)
