### ISSUE TITLE
Error con las Pruebas Unitarias

### ISSUE THREAD

**Issue by jfr4nc0** [sisoputnfrba/foro#3020]
Buenas! Tengo un problema que cuando trato de correr una simple prueba, me rompe la configuracion del ambiente, pero cuando ejecuto el binario principal me carga de forma correcta la configuracion. No es un tema del PATH del .config porque es absoluto.
Adjunto screen para que se entienda mejor.

** make test-helgring:
![image](https://github.com/sisoputnfrba/foro/assets/76176196/0f6a3ac0-0be0-4b7a-8dd2-654ba1a0ebbf)

** make helgrind:
![image](https://github.com/sisoputnfrba/foro/assets/76176196/830781c0-30b9-45e6-b57b-b3746558e8df)

Alguno sabe porque puede ser esto?

**Comment by mesaglio** [comment]
Buenas, en que branch estas trabajando?

Por lo que veo en el branch `modulo_cpu` actualmente en el [ultimo commit](https://github.com/sisoputnfrba/tp-2023-1c-KernelPanic/blob/3edf00c83af22318c0a4345c08211a98d598a4d8/modules/kernel/src/kernel.h#L154) no estas usando rutas absolutas.

Aca hay [un post](https://linuxhint.com/absolute-relative-paths-linux/) donde muestra la diferencia. Basicamente la ruta absoluta arranca desde el root dir `/` y si vemos la ruta del `kernel.h` no pareciera absoluta.

Proba cambiando el path del log y del config a rutas absolutas, o fixea la ruta relativa.

Salu2!

**Comment by jfr4nc0** [comment]
Buenas Agustín! Voy a probar eso que me comentaste que seguro rompe por el
main. Un saludo

**Comment by iago64** [comment]
@jfr4nc0 Cómo va?

Te sirvió la respuesta de Agus al final?

Saludos.-

**Comment by jfr4nc0** [comment]
Buenas gente! Pensé que había contestado, colgué mala mía jaja me sirvió lo de separar el main de las funciones. Muchas Gracias a los que contestaron, buen finde !
