### ISSUE TITLE
Consulta de FileSystem

### ISSUE THREAD

**Issue by ezequielmalfonso** [sisoputnfrba/foro#3021]
Buenas, antes que nada disculpa si había otra issue, busque y no encontré, la issue #3010 algo me aclaro, pero nos siguen quedando dudas.
1) Cuando dice:
>Abrir Archivo
Esta operación consistirá en verificar que exista el FCB correspondiente al archivo y en caso de que exista deberá devolver un OK, caso contrario, deberá informar que el archivo no existe.

En el caso del OK, lo entiendo, pero si no existe el archivo le devuelve un mensaje al kernel de que el archivo no existe, en ese instante el kernel le debe solicitar la creación del archivo al FS, o cuando el archivo que solicita abrir el kernel si no existe el FS lo crea y le avisa al kernel que no existe y que lo creo?

2) Cuando se levantan todos los modulos, el FS genera las estructuras administrativas necesarias:
 Cito:
>Bitmap de Bloques
Este archivo es un archivo que contendrá un bit por cada bloque disponible en el filesystem, cualquier otra implementación será motivo de desaprobación.
Se recomienda investigar el uso de mmap(), y las funciones de [bitarray de las commons](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/bitarray.h) para facilitar la implementación del mismo.

El bitmap de bloques, cuando levanta por primera vez el FS se crea, y cuando lo levante luego, tiene que levantar ese mismo archivo no crearlo de nuevo?

3) Entendemos que vamos a tener un archivo de FCB por cada archivo que recibamos por parámetro, esta bien esto?
Si es así,  cuando corro un vez y recibo por parámetro el archivo Archivo_1, luego de parar todos módulos y vuelvo a correr, ese PCB de ese archivo lo tengo que tener o se elimina cuando finalizan?

Estaría bien si creamos una lista de pcbs, para no tener que recorrer todo el directorio de PCBs cada vez recibimos un archivo para saber si ya existe?

Gracias.-

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- La idea es que uds manden desde el Kernel el abrir archivo, el FS les diga que no existe y sea el Kernel el que le diga al FS: Crea el archivo, al momento de que recibe que el archivo no existe.
TL-DR: Esto es porque no es responsabilidad del FS saber si tiene que crear o no el archivo, es el Kernel el que "decide" crearlo al momento de abrirlo y que no exista.

2.- El resumen raido seria: Si existen los archivos, levantan los archivos que existen, si no los crean.
Aca lo que pueden hacer es crearse los archivos fuera del módulo FS, es decir, tirando los touch y los truncate en una terminal  antes de arrancar el módulo.

3.- El FCB va a ser uno por archivo, despues si quieren levantarlos a memoria y tener una lista, pueden hacerlo, pero cualquier cambio que hagan tienen que persistirlo en el archivo.

Saludos.-

**Comment by ezequielmalfonso** [comment]
Gracias por las respuesta, te hago otras consultas.
1)  Hay que cerrar el bitmap cuando liberamos la configuración o después de levantarlo? No me termina de quedar claro que papel cumple el bitmap luego de creado.
2) Al fileSystem le importa la ID del proceso, pq tanto al tabla global como la tabla del proceso de archivos abiertos la actualizo desde el kernel?
Que debería de guardar en la estructura de la Tabla Global de Archivos Abierto? nombre archivo? Volumen? Modo de acceso?Y la Tabla de Archivos Abiertos por Proceso?
3) En el código de iniciarBitmap, hay una línea que dice: Inicializo todos los bits en 0, eso se debería hacer solo la primera vez que corremos el tp, luego ya no lo debería de tocar mas o siempre q levanto todos los módulos lo tenemos que inicializar en 0?
4) Que relación tiene el bitarray con el archivo de bloques y el bitmap no terminamos de entender el funcionamiento gral?
5) El archivo de Bloques va a tener un tamaño de Block_Count * BlockSize? 
Y cada bloque como defino el tamaño dentro del archivo de bloques? O eso es en memoria?
6) Como asignar el puntero directo y como sería un bloque de punteros, para que apunte el puntero indirecto, estos son punteros como manejamos siempre no son alguno tipo de punto en especial?

Desde ya muchas gracias y perdón si se hizo largo.

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- La idea del bitmap es que puedan saber que bloques están ocupados y que bloques están libres, tengan en cuenta que uds van a ir creando archivos y asignándoles bloques en tiempo de ejecución y eso lo tienen que persistir en algún lado.

2.- Al FS mucho no le importa, al Kernel si porque si un proceso tiene abierto el archivo, otro no puede abrirlo.
La tabla global de archivos abiertos tiene que tener lo que uds necesiten para saber si un archivo esta abierto, quien lo tiene y por ej quienes estan bloqueados esperandolo.

3.- Solo tienen que inicializar el bitmap la primera vez, despues si encuentran un bitmap existente, tienen queusarlo.

4.- El bitmap (o bitarray por el nombre de las funciones en las commons) tiene una relación 1 a 1 con el archivo de bloques, cada **bit** del bitmap, les dice si el bloque correspondiente en el archivo de bloques esta usado o libre.

5.- Efectivamente el tamaño del archivo de bloques tiene que ser BLOCK_COUNT * BLOCK_SIZE.
Como definen el tamaño dentro del archivo, ya es parte del problema que tienen que resolver, pero es bastaaante parecido a como resolverían el problema en una memoria con paginación.

6.- Puntero directo: Buscan el primer bloque libre dentro del archivo de bloques y ponen ese número en el puntero directo, después cuando lo lean van a tener que ver uds como hacen para llegar a ese bloque.
Bloque de punteros: es un bloque lleno de números de bloque (por eso la aclaración de que son uint32_t) la idea es que uds pongan ahi los números de los bloques que le van asignando al archivo.

Saludos.-

P.D: No tienen que pedir disculpas por preguntar ☺️

**Comment by irinaperezg** [comment]
Agrego una consulta relacionada a FS, cuando se crea un archivo arranca con los punteros inicializados en 0 y recién se le asignan con el truncate? o ya se crea con al menos el puntero directo configurado?

**Comment by iago64** [comment]
Buenas! Cómo va?

Pueden asignar el puntero directo al crear el archivo o al momento del F_TRUNCATE, a fines prácticos de las pruebas va a dar lo mismo porque no vamos a pedirles que escriban en un archivo que no tiene reservado el espacio previamente.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas!
Para sumar a la respuesta, aun si lo quisieran mantener consistente, tampoco importaría qué número le inicialicen a los punteros ya que si el tamaño del archivo es 0 debería tirar error por intentar leer/escribir fuera del archivo, pero como dijo @iago64 son casos de error que no vamos a probar y que no están definidos en el enunciado. Si vamos a un contexto más conceptual, un archivo con tamaño 0 (por ejemplo, recién creado) no debería tener ningún bloque asignado/ocupado.

**Comment by ezequielmalfonso** [comment]
Una pregunta a lo mejor es media pava, pero me que me genera dudas, cuando creo un archivo por pedido del kernel, lo creo físicamente, o solo loggeo que lo creo y actualizo todas las estructuras debe actualizar por ejemplo con open("nombre_archivo.txt");

Gracias.-

**Comment by LeandroCarbajales** [comment]
Buenas!
Cito al enunciado:

> Todas las operaciones que se realicen sobre los FCBs, Bitmap y Bloques deberán mantenerse actualizadas en disco a medida que ocurren.

Al crear el archivo intuyo mínimamente se le crearía una estructura FCB con valores iniciales, por lo que debería también persistir esa estructura.

**Comment by AGanem** [comment]
Hola no me queda claro el  punto 6, y siguiendo el ejemplo que está en el enunciado:
Ejemplo de FCB
NOMBRE_ARCHIVO=Notas1erParcialK9999
TAMANIO_ARCHIVO=256
PUNTERO_DIRECTO=12
PUNTERO_INDIRECTO=45
Ejemplo superbloque
BLOCK_SIZE=64
BLOCK_COUNT=65536


El PUNTERO_DIRECTO apunta al bloque 12 el cual tiene datos por lo tanto ahí leo 64 bytes, luego tomo el PUNTERO_INDIRECTO que me indica que vaya al bloque 45,
pero aca no entiendo que contiene ese bloque, será un puntero a otro bloque y así siguiendo, como si estuvieran enlazados? ya que me restan leer 3 bloques para completar los 256bytes del tamaño indicado.
Y en tal caso que estuvieran enlazados, que contiene el último bloque?

**Comment by uriliahaff** [comment]
Hola, con respecto  del puntero indirecto, el mismo es un puntero que apunta a un **bloque de punteros**, es decir, un bloque que en vez de tener datos va a tener punteros a otros bloques (que pueden ser bloques de datos como bloques de punteros...😱😱). 
Entonces, si tu bloque es de tamaño 64, en el bloque de punteros entrarían dos punteros a bloques (Tomando en cuenta que el tamaño de los punteros a bloques es de 32).

**Comment by AGanem** [comment]
Perfecto, ahora me quedó claro al ver como funcionan fseek(), fread() y fwrite(), pero me surgió una duda, porque dijiste que en un bloque de 64 bytes entran 8 punteros de 4bytes, no entrarían 16 punteros?

**Comment by uriliahaff** [comment]
Sisi, es como decis... Fe de erratas. Pero para generalizar el calculo seria: CantDePunteros = TamañoDeBloque / TamañoDePuntero

**Comment by AGanem** [comment]
Excelente, muchas gracias!

**Comment by ezequielmalfonso** [comment]
@LeandroCarbajales  por nuestra parte por ahora vamos avanzando, gracias.

**Comment by iago64** [comment]
Cerramos el issue por inactividad.
Cualquier cosa pueden abrir uno nuevo haciendo referencia a este.
