### ISSUE TITLE
Fallo al recibir String en el servidor

### ISSUE THREAD

**Issue by juannardi13** [sisoputnfrba/foro#3022]
Buenas noches, antes que nada mil disculpas por la hora y por estar molestando otra vez en el foro con un problema. Tengo un problema al deserializar en el Servidor un String que mando por parte del cliente, estoy casi seguro que es a la hora de deserializar porque no veo fallas a la hora de enviar el String en el lado del cliente y, además, estuve debugeando el servidor y me di cuenta de que el código de operación que recibía este era el tamaño del string que se mandaba (cosa que no creo que sea casualidad), el orden en el que envío y recibo las cosas es correcto creo yo, a continuación mando el código: 

### 📝 Código relevante
Del lado del cliente:
```
void enviar_string(int conexion_servidor, char* string, op_code codigo_op) {
	t_paquete* paquete = malloc(sizeof(t_paquete));
	//void* string_a_enviar = serializar_string(string, paquete, codigo_op);
	t_buffer* buffer = malloc(sizeof(t_buffer));

		int tamanio_string = strlen(string) + 1;

		buffer->stream_size = tamanio_string;
		void* stream = malloc(buffer->stream_size);
		int offset = 0;

		memcpy(stream + offset, string, tamanio_string);
		offset += tamanio_string;

		buffer->stream = stream;

		paquete->codigo_operacion = codigo_op;
		paquete->buffer = buffer;

		void* a_enviar = malloc(buffer->stream_size + sizeof(int) + sizeof(int));
		offset = 0;

		memcpy(a_enviar, &(paquete->codigo_operacion), sizeof(int));
		offset += sizeof(int);
		memcpy(a_enviar, &(paquete->buffer->stream_size), sizeof(int));
		offset += sizeof(int);
		memcpy(a_enviar + offset, paquete->buffer->stream, paquete->buffer->stream_size);
		offset += paquete->buffer->stream_size;

	send(conexion_servidor, a_enviar, (paquete->buffer->stream_size) + sizeof(int) + sizeof(int), 0);
	free(a_enviar);
	eliminar_paquete(paquete);
}
```

También debugeé el cliente y se arma todo perfecto y sin ningún problema:
![image](https://github.com/sisoputnfrba/foro/assets/102627173/fdeb4680-7397-4cab-b090-45ec99736e7a)
Esto es al final de la función de arriba mismo.

Después del lado del Servidor, el código es el siguiente:
```
int atender_clientes_kernel(int socket_servidor, t_log* logger) {

	int socket_cliente = esperar_cliente(logger,"KERNEL", socket_servidor); // se conecta el cliente

		if(socket_cliente != -1) {
			t_manejar_conexion_args* args = malloc(sizeof(t_manejar_conexion_args));
			args->fd = socket_cliente;
			args->log = logger;
			manejar_conexion(args);
			free(args);
			return 1;
		} else {
			log_error(logger, "Error al escuchar clientes... Finalizando servidor \n"); // log para fallo de comunicaciones
		}


	return 0;
}

void manejar_conexion(void *void_args) {
	t_manejar_conexion_args *args = (t_manejar_conexion_args*) void_args;
	t_log *logger = args->log;
	int socket_cliente = args->fd;

	t_paquete* paquete = malloc(sizeof(t_paquete));
	paquete->buffer = malloc(sizeof(t_buffer));

	recv(socket_cliente, &(paquete->codigo_operacion), sizeof(int), 0); <-- ACÁ ES DONDE RECIBE EL CÓDIGO DE OPERACIÓN MAL

	recv(socket_cliente, &(paquete->buffer->stream_size), sizeof(int), 0);
	paquete->buffer->stream = malloc(paquete->buffer->stream_size);
	recv(socket_cliente, paquete->buffer->stream, paquete->buffer->stream_size, 0);

	void* data;

	switch(paquete->codigo_operacion)
	{
	case CONSOLA:
		log_info(logger, "Me llegó una Consola");
		data = deserializar_string(paquete->buffer);

		break;
	default:
		log_warning(logger, "Operacion desconocida \n");
		break;
	}
}


```

A la hora del Debug en el servidor donde está señalizado justo arriba donde dice "ACÁ ES DONDE RECIBE EL CÓDIGO DE OPERACIÓN MAL" recibe lo siguiente:
![image](https://github.com/sisoputnfrba/foro/assets/102627173/a74e1a99-f668-4194-838f-c650fa4bb315)
Recibe como código de operación 88 que es el tamaño del String enviado. Intenté de mil formas pero sigue sin funcionar, no sé si es que estoy enviando en un orden incorrecto las cosas pero yo lo veo bien.

Muchas gracias por leerme otra vez y pido disculpas nuevamente por el contratiempo. 
Saludos.

**Comment by mesaglio** [comment]
Bueeeeenas, como va?
1. No tenes que pedir perdon por el horario de publicacion, cuando algun ayudante este libre va a contestar 😄.
2. Tampoco tenes que pedir disculpas por usar el foro, para eso esta 💪.

Ahora veamos si el problema puede venir por este lado.
En tu codigo del servidor me levanto un warning esta sentencia:
```c
...
   recv(socket_cliente, &(paquete->codigo_operacion), sizeof(int), 0); <-- ACÁ ES DONDE RECIBE EL CÓDIGO DE OPERACIÓN MAL
...
```
ese ultimo `0` que le estas pasando al `recv`, ¿que funcion cumple?

Si vemos la [documentacion](https://man7.org/linux/man-pages/man2/recv.2.html) de la funcion, corresponde a un identificador de flags.
```c
#include <sys/socket.h>
ssize_t recv(int sockfd, void *buf, size_t len, int flags);
...
```

Estos flags terminan definiendo un coportamiento particular para la funcion `recv`. Por ejemplo, al usar el flag `MSG_DONTWAIT` hace que se comporte como no bloqueante. 
Creo que en este caso el comportamiento que estas buscando es que en `&(paquete->codigo_operacion)` este la cantidad de bytes que queres (que en este caso es `sizeof(int)`) por lo tanto deberia ser bloqueante.
Para que el `recv` sea bloqueante podes usar el flag `MSG_WAITALL` como lo indica la documentacion.

```
MSG_WAITALL (since Linux 2.2)
              This flag requests that the operation block until the full
              request is satisfied.  However, the call may still return
              less data than requested if a signal is caught, an error
              or disconnect occurs, or the next data to be received is
              of a different type than that returned.  This flag has no
              effect for datagram sockets. 
```

Puede estar pasando que de los 4 bytes que esperas, al no ser bloqueante el `recv`, este reciviendo menos y al compararlo nunca matchearia el tipo de operacion.
Proba cambiando el flag del `recv` y ya que estamos podes logear el valor que retorna el `recv` que son la cantidad de bytes recibidos.

Salu2!

**Comment by juannardi13** [comment]
Hola! Muchas gracias por tu respuesta :)
Cambié el flag como bien me indicaste pero sigue pasando lo mismo, la recepción de la cantidad de bytes fue como esperaba:
![image](https://github.com/sisoputnfrba/foro/assets/102627173/3cc41679-a0b4-4559-bc08-6f78842415e4)
Me sucedió otra vez que el código de operación que recibe es el tamaño del buffer :(

**Comment by RaniAgus** [comment]
¡Buenas!
Eso se debe a que al serializar el tamaño del buffer les faltó sumar el `offset`:
```c
memcpy(a_enviar, &(paquete->codigo_operacion), sizeof(int));
offset += sizeof(int);
memcpy(a_enviar, &(paquete->buffer->stream_size), sizeof(int)); // <--- ACÁ
offset += sizeof(int);
memcpy(a_enviar + offset, paquete->buffer->stream, paquete->buffer->stream_size);
offset += paquete->buffer->stream_size;
```

Les recomiendo extraer la lógica repetida en una función auxiliar que se encargue de llenar el `a_enviar` y a su vez actualice el `offset`:

```c
int agregar_a_stream(void *stream, int* offset, void *src, int size) {
  memcpy(stream + *offset, src, size);
  *offset += size;
}

int offset = 0;
agregar_a_stream(a_enviar, &offset, &(paquete->codigo_operacion), sizeof(int));
agregar_a_stream(a_enviar, &offset, &(paquete->buffer->stream_size), sizeof(int));
agregar_a_stream(a_enviar, &offset, paquete->buffer->stream, paquete->buffer->stream_size);
```
De esta forma, es imposible que haya inconsistencias entre lo que se envía a `memcpy` y lo que se actualiza en el `offset`.

Saludos

**Comment by juannardi13** [comment]
Buenas! Muchísimas gracias por la ayuda Juan y Agus!, ya está todo bien :))
Al final, al delegarlo en la serialización, funcionó.

Muchas gracias por la paciencia.
Saludos.
