### ISSUE TITLE
Duda para correr las pruebas

### ISSUE THREAD

**Issue by ZoeGolfieri** [sisoputnfrba/foro#3023]
Hola! Teniamos una duda y no podemos asistir hoy al campus para resolverla.
Queriamos saber cual seria la forma correcta para correr las pruebas. Debido a que lo hicimos con un script el cual tiene el siguiente contenido:
./Consola "../consola.config" "/home/utnso/tp-2023-1c-Los-operadores/Consola/base1.txt" &
./Consola "../consola.config" "/home/utnso/tp-2023-1c-Los-operadores/Consola/base2.txt" &
./Consola "../consola.config" "/home/utnso/tp-2023-1c-Los-operadores/Consola/base2.txt"
wait
Pero al correr la prueba 1 no nos da como debería. Estuvimos pensando otras opciones como enviar mas parametros con los otros archivos pero no sabiamos si estaba del todo bien.
### 👍 Comportamiento esperado

En la prueba de base debía finalizar primero el proceso 1, luego el 2 y luego el 3.

### 👎 Comportamiento obtenido

La prueba se nos ejecuta finalizando primero el proceso 3, luego el 1 y luego el 2

**Comment by mesaglio** [comment]
Buenas, que orden de llegada tienen los proceso en el planificador en los logs? El algoritmo es FIFO.
Podrias sumar los logs del planificador, orden de arribo y traza de ejecucion al issue, por favor?
Salud2!

**Comment by LeandroCarbajales** [comment]
Buenas! @ZoeGolfieri 
Pudieron ver lo que les comentó @mesaglio ?
Les sigue pasando este problema?

**Comment by ZoeGolfieri** [comment]
Hola! Sisi, nos dimos cuenta que nos faltaba el sleep en el set. Muchísimas gracias

**Comment by LeandroCarbajales** [comment]
Genial!
Recuerden que pueden cerrar el issue cuando la duda está resuelta :)
