### ISSUE TITLE
Informacion que le envia el kernel a memoria

### ISSUE THREAD

**Issue by fpesce27** [sisoputnfrba/foro#3024]
Hola tengo una consulta, cuando el kernel solicita un create_segment, este le puede enviar todo el contexto de ejecucion en donde esta incluida la instruccion con sus parametros y la tabla de segmentos, ademas de otra informacion, esto nos serviria ya que tenemos una funcion que ya lo hace. A esto se le suma otra consulta si es q la tabla de segmentos del proceso puede estar en el contexto, muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

Vamos en orden:
1.- Pueden devolver todo el contexto de ejecución? Si pueden, de hecho, una buena práctica sería que ante cada petición de la CPU al Kernel, devuelvan el contexto de ejecución completo, ya que por ej en el CREATE_SEGMENT, puede ser que se queden sin espacio y tengan que matar al proceso.

2.- La tabla de segmento **tiene que ser parte** del contexto de ejecución, si no como va a hacer la CPU para calcular las direcciones físicas de memoria?

Saludos.-

**Comment by fpesce27** [comment]
perfecto muchas gracias
