### ISSUE TITLE
Tengo una consulta del MMU

### ISSUE THREAD

**Issue by DanielBareiro** [sisoputnfrba/foro#3025]
Buenas, una consulta del enunciado, en la parte de mmu dice 

>En caso de que el desplazamiento dentro del segmento (desplazamiento_segmento) sumado al tamaño a leer / escribir, sea mayor al tamaño del segmento

que seria el tamaño a leer/escribir que se suma?

**Comment by iago64** [comment]
Buenas! Cómo va?

El tamaño a leer / escribir es el tamaño del registro con el cual están operando (4, 8 o 16 bytes) o el tamaño que reciben en el F_READ / F_WRITE.

Saludos.-

**Comment by DanielBareiro** [comment]
Muchas gracias!
