### ISSUE TITLE
duda enunciado F_READ, F_WRITE y F_TRUNCATE

### ISSUE THREAD

**Issue by LucianoSangroni123** [sisoputnfrba/foro#3028]
Buenas, tenemos una duda con las operaciones de F_READ, F_WRITE y F_TRUNCATE. Cuando dice que se bloqueará el proceso se refiere a que el kernel se bloqueará por completo hasta recibir la respuesta del filesystem o que se debe bloquear el proceso solo y debe pasar a ejecutar el siguiente de la cola ready?

**Comment by iago64** [comment]
Buenas! Cómo va?

El que se bloquea es el proceso que hace el llamado a F_READ, F_WRITE o F_TRUNCATE, el Kernel tiene que seguir planificando los demas procesos.

Saludos.-

**Comment by LucianoSangroni123** [comment]
Joya, muchas gracias
