### ISSUE TITLE
Consulta FS operacion f_open

### ISSUE THREAD

**Issue by pablomartinfranco** [sisoputnfrba/foro#3030]
Hola,
tengo una consulta,
el tp menciona lo siguiente:
"Siempre será posible crear un archivo y por lo tanto esta operación deberá devolver OK"

que debe suceder si ya hay un fcb creado ? queda el que esta tal cual o se pisa con uno nuevo todo en cero ?

Gracias saludos

**Comment by iago64** [comment]
Buenas!

No vamos a hacer una prueba de crear 2 archivos con el mismo nombre.

Saludos.-

**Comment by pablomartinfranco** [comment]
genial, gracias !
