### ISSUE TITLE
Dudas con FCB

### ISSUE THREAD

**Issue by fmarsico8** [sisoputnfrba/foro#3031]
Buenos días, teníamos dudas más conceptuales del FCB entendemos que es un archivo que se crea por cada nuevo archivo, pero no entendemos como deberíamos de modelar el FCB cuando lo creamos si es que hay que directamente usar FWRITE para escribirlo o  como se debería hacer.
¿Se debería crear un tipo struct para el FCB? 
¿Cada vez que creamos un fcb lo levantamos con el mismo path del config del file system?
Y por ultimo entendemos que hay que crear un FCB por cada archivo pero el archivo asociado a ese FCB hay que crearlo o no? 

Desde ya muchas gracias.

**Comment by LeandroCarbajales** [comment]
Buenas!
Por lo pronto, un FCB (File Control Block) es la estructura administrativa que vas a usar para administrar cada archivo (similar a PCB para un proceso). Dicho esto, sus atributos para definir el struct son los que están definidos en el anexo de File System.
La principal diferencia es que así como el Bitmap y el archivo de Bloques, estos deben ser persistidos (cada uno en un archivo) para que luego "ya existan" si tiramos todo abajo y lo volvemos a levantar.

Queda más clara la idea? :)
Saludos!
         Lean

**Comment by fmarsico8** [comment]
okey pero entonces estos fcb, tendrian que tener formato de config? o simplemente un archivo nuevo?

**Comment by LeandroCarbajales** [comment]
Los FCB pueden persistirlos con el formato de los archivos de config de las commons, cito al enunciado:

> Ejemplo de FCB

> NOMBRE_ARCHIVO=Notas1erParcialK9999
TAMANIO_ARCHIVO=256
PUNTERO_DIRECTO=12
PUNTERO_INDIRECTO=45

> Los archivos de FCB serán compatibles con el formato de los [archivos de config de las commons](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/config.h), por lo que se recomienda la utilización de las funciones ya creadas para facilitar su implementación.

**Comment by LeandroCarbajales** [comment]
Buenas @fmarsico8 !
Te resolvió la duda? Se puede cerrar el issue?

**Comment by fmarsico8** [comment]
Buenas! Sisi muchas gracias, perdón que colgue en cerrarlo
