### ISSUE TITLE
Problema con las Instrucciones

### ISSUE THREAD

**Issue by MartoSimon** [sisoputnfrba/foro#3032]
Buenas tardes, cuando en el kernel recibimos las instrucciones de la consola siempre nos aparecian unos cuadraditos que no sabiamos que eran pero como no rompían nada nunca les dimos importancia. El problema es que ahora creemos que es lo que nos esta rompiendo, ya que al querer concatenar las instrucciones para despues poder mandarlas al cpu se muere el kernel unicamente cuando llega  a esas instrucciones (las primeras 4 instrucciones las hace bien ya que no tienen cuadraditos).

Queriamos saber si saben de donde salen y como eliminarlos, o si tenemos que buscar otra forma de hacer las cosas.
PD: El archivo de instrucciones usa el ejemplo proporcionado en las consignas.

![Screenshot_1](https://github.com/sisoputnfrba/foro/assets/72176653/57ad7de5-4d3c-47b7-aba2-b9ce5635097a)

### 📝 Código relevante
```
Funcion para enviar el paquete desde consola:
void paquete(){  
	int longitud;
	t_paquete* paquete;
	paquete = crear_paquete();
	log_info(logger, "Se recibieron las siguientes instrucciones del archivo de PSEUDOCODIGO:");
	FILE *leido;
	char buffer[100];
	leido = fopen("instrucciones.psc", "r");
	if (leido == NULL) {
		log_error(logger, "Error en la apertura del archivo de PSEUDOCODIGO.\n");
	}
	while (fgets(buffer, sizeof(buffer), leido)) {
		buffer[strcspn(buffer, "\n")] = '\0';
		longitud = strlen(buffer);
		agregar_a_paquete(paquete, buffer, longitud);
		log_info(logger, "\t Longitud: %d \tInstruccion: %s", longitud, buffer);
	}
	enviar_paquete(paquete, conexion);
	eliminar_paquete(paquete);
	fclose(leido);
}
```

**Comment by LeandroCarbajales** [comment]
Buenas!
Mi recomendación sería que corran el Kernel en modo debug parando la ejecución apenas terminan de recibir las instrucciones para chequear que no estén recibiendo caracteres de más.
Algo a tener en cuenta por ejemplo, es que funciones como `strlen()` no funcionan correctamente si no se encuentra el `\0` correspondiente, por lo que es fácil terminar enviando de más o de menos. Luego al hacer `printf()`, sucede esto mismo, si no hay un `\0` no se sabe en dónde termina el string que se quiere imprimir y termina imprimiendo cosas de más.

**Comment by MartoSimon** [comment]
Estuvimos chequeando y seguimos sin poder encontrar el error, nos parece que es medio complicado mostrar el problema por texto, asi que preferimos ir al soporte del sabado :).
Gracias por la ayuda
