### ISSUE TITLE
Duda acerca de la cantidad de segmentos.

### ISSUE THREAD

**Issue by tomasmartinez02** [sisoputnfrba/foro#3033]
Hola, estábamos con una duda en memoria. Tenemos que contemplar el caso en que un proceso solicita crear mas segmentos de los que ya tiene? Como en el enunciado no se nombra ese caso, queríamos saber si en ese caso hay que terminar el proceso con un error o no hay que contemplarlo.
Gracias.

**Comment by iago64** [comment]
Buenas ¿Cómo va?

No tienen que contemplarlo.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas @tomasmartinez02 !
Te resolvió la duda? Se puede cerrar el issue?

**Comment by iago64** [comment]
Cerramos el issue por inactividad.

Cualquier inconveniente pueden reabrir este issue o crear uno nuevo y hacer referencia a este.
