### ISSUE TITLE
Duda sobre que le pasa el kernel al FS cuando se ejecuta un F_READ o F_WRITE.

### ISSUE THREAD

**Issue by FacundoPiaggio** [sisoputnfrba/foro#3034]
Buenas tardes

Entendemos que cuando hay que realizar un F_READ o F_WRITE, el kernel debe pasarle al FS el nombre del archivo, la dirección física calculada por la mmu, la cantidad de bytes a leer/escribir y ademas el puntero del archivo para que lea/escriba a partir de ahí.

Esto es así? o hay algo que sobra o este de mas?

**Comment by iago64** [comment]
Buenas! Cómo va?

Es tal cual lo que dice el enunciado y cito al enunciado:

> F_READ: Para esta función se solicita al módulo File System que lea desde el puntero del archivo pasado por parámetro la cantidad de bytes indicada y lo grabe en la dirección física de memoria recibida por parámetro. El proceso que llamó a F_READ, deberá permanecer en estado bloqueado hasta que el módulo File System informe de la finalización de la operación.

> F_WRITE: Esta función solicitará al módulo File System que escriba en el archivo desde la dirección física de memoria recibida por parámetro la cantidad de bytes indicada. El proceso que llamó a F_WRITE, deberá permanecer en estado bloqueado hasta que el módulo File System informe de la finalización de la operación.

> Nota: Es importante aclarar que para las operaciones de F_READ y F_WRITE siempre se van a pasar tamaños y punteros válidos.

Después que uds necesiten pasar algo código de operación u otra cosa ya corre por cuenta de cómo definan uds el protocolo.

Saludos.-

**Comment by FacundoPiaggio** [comment]
Excelente dami, queríamos estar seguros de que era así.
Muchas gracias!
