### ISSUE TITLE
Duda funcionamiento registros

### ISSUE THREAD

**Issue by lucasosacuenca** [sisoputnfrba/foro#3035]
Buenas, tenemos una duda con la parte de registros, en el sentido de que los mismos son generales de la CPU, es decir que no hay uno por proceso, pero nosotros lo devolveriamos como contexto de ejecucion para que si el proceso vuelve a ir a execute, retome desde esos valores los registros? y en ese caso, tendriamos que mandarlo en un principio inicializado en cero, o si es la primera vez que llega a la CPU se toman los registros que ya estan? Gracias :)

**Comment by iago64** [comment]
Buenas! Cómo va?

En principio da lo mismo que tengan los registros al comienzo de la ejecución ya que lo primero que vamos a hacer con un registro que vayamos a usar es hacer o un SET o un MOV_IN para cargarle algo de info "util"
Si por simpleza, prolijidad o simplemente para calmar la ansiedad de inicializar todas las variables, pueden hacerlo.

Saludos.-

**Comment by lucasosacuenca** [comment]
Buenisimo, gracias
