### ISSUE TITLE
Duda sobre inicialización del proceso en Memoria

### ISSUE THREAD

**Issue by ailindenoya** [sisoputnfrba/foro#3036]
Buenas! 
Con mi grupo teníamos una duda acerca de esta parte citada del enunciado. 
Queríamos saber por qué es necesario enviar la tabla de segmentos inicial, ya que entendemos que al inicio solamente tendría el segmento 0, y se podría inicializar en Kernel sin esa comunicación.

### 📔 Citas del enunciado/videos

>Inicialización del proceso
El módulo deberá crear las estructuras administrativas necesarias y enviar como **_respuesta_** la tabla de
segmentos inicial del proceso. Esta tabla tendrá un tamaño fijo definido por archivo de configuración.<

Muchísimas gracias!

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Esto es algo que se comentó en el issue #2990, y es que simplemente al Kernel no le interesa tener la lógica de saber donde, como o por que esta el segmento 0.
Es un poco el principio de división de responsabilidades que ven en paradigmas o en diseño.

Saludos.-
