### ISSUE TITLE
Logs minimos de File System e Implementación de Bitmap

### ISSUE THREAD

**Issue by f-and** [sisoputnfrba/foro#3038]
Buenos dias, estamos con mi grupo implementando el File System y nos genero una duda el "Acceso a Bitmap" de los logs minimos del mismo. Ya que como tenemos actualmente el Bitmap, el único uso que le damos es la busqueda de bloques libres para asignar a archivos y para esto simplemente hacemos un for loop checkeando cada bit del bloque hasta llegar al proximo libre. 

La duda que tendriamos es: ¿Estamos implementando bien el bitmap como un bitarray y con el for loop? Porque si llegara el caso donde tenemos un archivo que llega al bloque 1000, y se debe hacer un log por cada acceso al bitmap (cada comprobación del for loop), ¿serian 1000 log_infos?

### 📔 Citas del enunciado/videos

En Logs minimos y obligatorios de File System.

Acceso a Bitmap: “Acceso a Bitmap - Bloque: <NUMERO BLOQUE> - Estado: <ESTADO>” Nota: El estado es 0 o 1 donde 0 es libre y 1 es ocupado.

### 💭 Soluciones posibles

Una posible solución seria modificar como se comprueban los bloques libres.

**Comment by iago64** [comment]
Buenas! Cómo va?

Si, efectivamente tienen que ser 1000 logs.
Somos conscientes de que puede ser un choclo de logs eternos, pero para que se queden tranquilos:
1.- No vamos a hacer pruebas taaan extensas que tengan que llegar al bloque 1000 (nos da fiaca hasta a nosotros)
2.- Si no recorren el bitarray no tienen otra forma de encontrar un bloque libre, asi que es parte de la idea de ver que van iterando por bloques ocupados y encuentran uno libre 😉 

Saludos.-

**Comment by f-and** [comment]
Ah ok, entonces lo dejo silenciado hasta la entrega jajajja!
Muchas gracias!
