### ISSUE TITLE
Compactación de memoria. Hay que congelar todo?

### ISSUE THREAD

**Issue by Hamamura-S** [sisoputnfrba/foro#3039]
Buenas, el enunciado dice que hay que chequear que no hayan operaciones entre el FS y Memoria, pero por qué particulariza en F_READ y F_WRITE? El resto de operaciones si se pueden hacer? y las operaciones que solo implican CPU? Tengo entendido de la teórica que hay que freezar todo, pero no lo dice en el enunciado. Saludos

### 📔 Citas del enunciado/videos
Compactación de Memoria
Al momento de recibir de la Memoria el mensaje que indica que se dispondría del espacio solicitado post compactación, el Kernel deberá primero validar que no se estén ejecutando operaciones entre el File System y la Memoria **(F_READ y F_WRITE)**.
En caso de que se tengan operaciones del File System en curso, el Kernel deberá esperar la finalización de las mismas para luego proceder a solicitar la compactación a la Memoria.
Como resultado de la compactación, el Kernel recibirá las tablas de segmentos actualizadas de todos los procesos y deberá actualizar las mismas en los PCB de cada proceso.
Una vez terminada esta rutina, el Kernel repetirá la solicitud de creación del segmento.

**Comment by RaniAgus** [comment]
¡Buenas!
Recuerden que en este TP solamente contamos con un CPU, por ende solo se puede ejecutar una instrucción a la vez y el proceso quedará en EXEC hasta que finalice la instrucción `CREATE_SEGMENT`. Entonces, si para crear el segmento es necesario compactar, lo único que va a estar en ejecución en ese momento es el algoritmo de compactación.

Por otro lado, no debería haber ningún problema al ejecutar un `F_OPEN`, `F_SEEK` o `F_CLOSE` ya que no interactúan con la Memoria.

Les dejo para pensar el motivo por el cual los `F_READ` y `F_WRITE` encolados deben ejecutarse antes de compactar: ¿qué pasaría si compacto primero y luego ejecuto la instrucción que recibo del FS?

Saludos

**Comment by RaniAgus** [comment]
Citando la pág. 11, solo hay que esperar a que terminen los `F_WRITE` y `F_READ`:

> #### Compactación de Memoria
> Al momento de recibir de la Memoria el mensaje que indica que se dispondría del espacio solicitado post compactación, **el Kernel deberá primero validar que no se estén ejecutando operaciones entre el File System y la Memoria (F_READ y F_WRITE)**.
> En caso de que se tengan operaciones del File System en curso, **el Kernel deberá esperar la finalización de las mismas para luego proceder a solicitar la compactación a la Memoria**.

El resto de operaciones de FS encoladas pueden continuar mientras se esté ejecutando `CREATE_SEGMENT` 👍🏻
