### ISSUE TITLE
Duda sobre FCB

### ISSUE THREAD

**Issue by gabriel1816** [sisoputnfrba/foro#3041]
Hola, mi duda es la siguiente, en la teoría vimos que se puede levantar el FCB y tenerlo en memoria (entre otras estructuras) para operar de forma más sencilla y luego grabar el archivo, mi duda es respecto a la implementación en el tp, este FCB tiene que estar en el módulo memoria, es decir, levantarse en file system y enviarse a memoria y las operaciones que se realicen desde el módulo file system o siempre está en filesystem?

**Comment by iago64** [comment]
Buenas! Cómo va?

En el TP los FCB tienen que estar siempre en el módulo FS, no tienen que cargarlos al módulo memoria.
Después si quieren tener alguna estructura en el FS para tener los FCB en memoria y cada cambio lo graban en el archivo correspondiente, no hay problema.

Saludos.-

**Comment by gabriel1816** [comment]
Muchas gracias!!
