### ISSUE TITLE
Dudas enunciado y Tests para el resto de instrucciones.

### ISSUE THREAD

**Issue by JoacoAltalef** [sisoputnfrba/foro#3042]
Buenas. Tengo 3 cuestiones:

1) Si `id_segmento` es sinónimo de `num_segmento`, no entiendo cómo la siguiente cuenta tiene sentido:
`num_segmento = floor(dir_logica / tam_max_segmento)`
Ya que cada segmento puede tener un tamaño variable, es muy probable que no dé lo que debería dar.
El otro día le hice esta consulta a Lean y creo que me dijo que esto era así porque siempre se iban a ingresar segmentos del tamaño máximo, pero de ser así, ¿qué sentido tendría la compactación? puesto a que siempre que haya lugar en memoria, va a haberlo para un múltiplo del tamaño máximo de segmento.

2) Cuando un proceso muere por algún motivo que no sea por haber hecho _EXIT_, ¿deberíamos hacer _SIGNAL_ de todos los recursos que había hecho _WAIT_ previamente? ¿O no hay que contemplar este caso?

3) ¿Podrían, si tienen, pasarnos tests para ir probando todo el resto de instrucciones? No importa si son medio básicos pero por lo menos para ir probando algo más oficial y no nos quedarnos solo con nuestras pruebas.

**Comment by LeandroCarbajales** [comment]
Buenas!
Voy respondiendo por punto:

1- Nunca dije que se ingresarían solamente segmentos del tamaño máximo, me disculpo si se interpretó eso, recuerdo que lo habíamos visto en el issue #2990, me refería a que ese es el valor con el que se calcula el `num_segmento` de la dirección lógica como en cualquier ejercicio (con la salvedad que se haría, más fácilmente, en binario o hexa) y como está aclarado en el enunciado en la parte que citaste, es indiferente al tamaño de cada segmento.

Entiendo que la duda viene más por el lado de por qué se usa el tamaño máximo y no el tamaño de cada segmento para hacer el cálculo, para lo cual, además de repasar la teoría de memoria/segmentación, podemos verlo de la siguiente manera:

Lo único que estamos haciendo ahí es separando la dirección _lógica_ en 2 partes, [ num_segmento | offset ]. A priori el proceso podría querer referenciar cualquier dirección lógica (válida o no), y estas direcciones son generalmente estáticas, lo que yo ponga en la dirección X quiero que siempre esté en la dirección X. Dicho esto, estas direcciones no tienen en sí ninguna correlación con su dirección física, que podría cambiar de lugar, y eso para el proceso es transparente.
Por lo tanto, a la hora de interpretar una dirección lógica, no hay ninguna parte que cambie, son N bits para `num_segmento` y M bits para `offset`, luego la tabla tiene la información necesaria para chequear que esa dirección sea válida y hacer la traducción.
Si tomáramos el tamaño de cada segmento para interpretar la dirección lógica, éstas "cambiarían de lugar" al cambiar el tamaño de los segmentos.

Veamos un ejemplo:
Tengo 16 bits de direccionamiento, de los cuales, 12 son offset y 4 num_segmento. Esto es exactamente lo mismo que decir que manejamos direcciones lógicas desde `0 hasta 2^16 - 1`, un `tam_máximo_segmento = 4096` y `cant_max_segmentos = 16`.
En este contexto, la dirección _lógica_ 7096 SIEMPRE va a referirse al segmento 1, offset 3000. Si ese segmento es más chico que 3000 simplemente significará que es una dirección inválida, si fuera válida entonces podemos traducirla normalmente tomando su base.
Si tomáramos el tamaño del segmento para interpretar esa dirección, la misma cambiaría de segmento al achicar o agrandar el segmento 1, lo cual no tiene sentido.

Espero que sirva la explicación :)

2- Cito al enunciado

> Cuando se reciba un mensaje de CPU con motivo de finalizar el proceso, se deberá pasar al mismo al estado EXIT, **liberar todos los recursos que tenga asignados** y dar aviso al módulo Memoria para que éste libere sus estructuras.

Aclaro que esto incluye también cerrar archivos si los tuviera abiertos (ya que deben verse como recursos de una única instancia).

3- No tenemos tests preparados para publicar aun, pero no estaría mal preguntar para entender cómo hacer una prueba y/o validar sus resultados

**Comment by JoacoAltalef** [comment]
1) Claro, yo me refería a la consulta que te había hecho presencial después del Checkpoint 3, pero había entendido algo al revés (osea mal jajaja). Ahora con esa explicación me volvió a quedar claro.

2) Ok perfecto, lo habíamos hecho así tanto para los recursos como para los archivos, pero preguntaba por las dudas.

3) Un ejemplo de una prueba que hicimos nosotros es la siguiente:
```
F_OPEN PEPITO
SET AX HOLA
MOV_OUT 4 AX
F_TRUNCATE PEPITO 64
F_WRITE PEPITO 4 4
F_SEEK PEPITO 0
F_READ PEPITO 10 4
MOV_IN BX 10
F_CLOSE PEPITO
EXIT
```
Y acá validamos que el registro `BX` contenga _HOLA_, que el tamaño del archivo haya cambiado y que se haya creado el `FCB` de _PEPITO_ correctamente básicamente.

Otra prueba que hicimos fue:
```
CREATE_SEGMENT 1 40
CREATE_SEGMENT 2 20
CREATE_SEGMENT 3 40
DELETE_SEGMENT 2
CREATE_SEGMENT 4 40
EXIT
```
En donde comprobamos que, para una memoria de 128 bytes, haya compactado correctamente para la última instrucción y luego haya creado el segmento.

No sé si ejemplos como estos son las pruebas que esperan que hagamos, ¿o recomiendan hacerlas diferentes? ¿Cómo deberíamos hacerlas y validarlas en ese caso? Porque parte de las validaciones que hicimos fueron imprimiendo por pantalla.

**Comment by iago64** [comment]
Buenas! Cómo va?

La prueba de como validar lo que graban en el archivo es una de las formas, la otra sería revisando el archivo de bloques con alguna herramienta estilo `hexdump` (que tambien la pueden usar para ver como cambia el archivo del bitmap) 😉 

Respecto a la prueba de compactar no es taaan asi, posiblemente tengamos mas procesos para llenar la memoria y ver que actualizan bien las tablas de segmentos de todos, pero lo que hicieron es una muy linda prueba inicial para probar la compactación 😄 

Saludos.-

**Comment by iago64** [comment]
Buenas! Cómo va?

@JoacoAltalef Quedo resuelta la duda?

Saludos.-

**Comment by JoacoAltalef** [comment]
Sisi, me olvidé de cerrar el issue. Se entendió todo. Muchas gracias por la ayuda!
