### ISSUE TITLE
duda de FCBs

### ISSUE THREAD

**Issue by agusdubreucq1** [sisoputnfrba/foro#3043]
buenas, no estoy entendiendo la implementacion del filesystem

>el módulo File System deberá levantar el [bitmap de bloques] y recorrer el directorio de FCBs para crear las estructuras >administrativas que le permita administrar los archivos.

en esta parte no entiendo a que se refiere con recorrer el directorio de FCBs.
por lo que entiendo cuando creo un archivo, debo crear un FCB (un archivo real que queda despues de terminar la ejecucion), que se guardara en la ruta '<path_FCB>/<nombre_del_FCB>'. luego cuando vuelvo a ejecutar el filesystem para saber cuantos archivos hay y cuales son. ¿deberia usar una funcion para ver todos los archivos del directorio? como 'opendir' y 'readdir'? 
y cuando me piden abrir un archivo, para verificar que existe debo leer cada FCB y matchear con el nombre? o capaz haberlos leido antes a todos y almacenado el nombre en una estructura o variable?

**Comment by iago64** [comment]
Buenas! Cómo va?

Justamente la idea de recorrer el directorio de FCBs es que puedan saber que archivos existen.
Una de las tantas posibles implementaciones es recorrer el directorio con `readdir()` y cargarlo en memoria, otra más "simple" es no cargar nada e ir cargando los FCB a medida que les llegan las peticiones de F_OPEN.

Elijan uds cual les resulta mas comoda.

Saludos.-

**Comment by iago64** [comment]
Buenas! Cómo va?

@agusdubreucq1 quedo resuelta la duda?

Saludos.-

**Comment by Ignaciofmunoz** [comment]
> Buenas! Cómo va?
> 
> Justamente la idea de recorrer el directorio de FCBs es que puedan saber que archivos existen. Una de las tantas posibles implementaciones es recorrer el directorio con `readdir()` y cargarlo en memoria, otra más "simple" es no cargar nada e ir cargando los FCB a medida que les llegan las peticiones de F_OPEN.
> 
> Elijan uds cual les resulta mas comoda.
> 
> Saludos.-

buenas re-preguntando sobre esto, van a existir archivos creados previamente a la ejecucion del modulo que deban encontrarse con readir ? o se arranca en cero y segun cada f_open creo el fcb?
