### ISSUE TITLE
Validaciones de MOV_IN y MOV_OUT

### ISSUE THREAD

**Issue by Danymmereles** [sisoputnfrba/foro#3044]
Buenas tardes,

Una consulta, cuando **CPU** le mande a **Memoria** las instrucciones tanto para **MOV_IN** y **MOV_OUT**, validamos si esto se puede hacer. A lo que me refiero es, por ejemplo que el **MOV_OUT** quiera escribir algo en un espacio inexistente o en un segmento ocupado por otro proceso. La primer duda es, es correcto eso?? Y si es asi, como se proseguiría?? Que se continue la lista de instrucciones planteadas ignorando la errónea o matamos el proceso o que deberíamos hacer???

**Comment by iago64** [comment]
Buenas! Cómo va?

Vamos a separar las preguntas para ordenar las respuestas 😄 

1.- Puede leer / eescribir en un segmento de otro proceso? No se puede dar, ya que uds van a calcular el segmento en base a la tabla de segmentos del proceso que esta corriendo.

2.- Pueden escribir / leer en una posición inválida? Si, es el problema del segment fault y se les va a dar cuando por ej tengan un tamaño maximo de segmento de 128 bytes, el segmento creado sea de 50 y les pidamos que lean / escriban a partir del byte 70.

En el caso del punto 2, el proceso como esta aclarado en el enunciado, finaliza por segment fault.

Saludos.-

**Comment by Danymmereles** [comment]
Okas, muchisimas gracias
