### ISSUE TITLE
Consulta tamaño de bloques e instrucciones

### ISSUE THREAD

**Issue by irinaperezg** [sisoputnfrba/foro#3045]
Hola!! Que tal? Tenía una consulta con respecto a como interpretar la intruccion f_truncate
por ejemplo, si se hace f_truncate 'nombreArchivo' 192
y el block_size es 64, significa que ese archivo debe tener asignado 3 o 2 bloques en total? el bloque indirecto que solo contiene punteros, cuenta como un bloque del archivo?
me refiero a si por ejemplo si f_truncate se pasa con 128, habria que asignarle 1 bloque en su puntero directo y 1 bloque indirecto de punteros o habría que asignarle 1 bloque en su puntero directo, 1 bloque de punteros con 1 puntero a un bloque ( ya que serian dos bloques de datos y 1 de punteros)
y por el otro lado, si f_truncate se pasa con un valor que es menor a la cantidad de bloques actuales, es decir que hay que achicar al archivo, hay que desasignarle al archivo los ultimos bloques asignados no? (osea de atras para adelante)
gracias :)

**Comment by iago64** [comment]
Buenas! Cómo va?

Vamos en orden con las preguntas:

1.- El bloque de punteros (el apuntado por el puntero indirecto) no cuenta como bloque de datos, con lo cual, si tienen un block size de 64 bytes y les pasamos un F_TRUNCATE de 128 van a tener:
1 bloque directo
1 bloque de punteros (indirecto)
1 bloque de datos apuntado por el primer puntero del bloque de punteros.

2.- Efectivamente si el F_TRUNCATE les llega con un tamaño menor al actual, van a tener que liberar bloques (si hace falta) contando desde el último hacia el primero.

Saludos.-

**Comment by irinaperezg** [comment]
Genial gracias!
