### ISSUE TITLE
Duda general con la implementacion de memoria

### ISSUE THREAD

**Issue by lucasdeferrari** [sisoputnfrba/foro#3046]
Buenas tardes, tenemos varias dudas de diferentes temas sobre la implementacion de la memoria:

1. estuve buscando en varios issues para entender mas o menos que es el segmento 0 y como implementarlo. Me quedaron algunas dudas:

- Si el segmento 0 tiene que estar en espacio de usuario y ademas en cada tabla de segmentos. Es decir que si por ejemplo hay 3 procesos, tendria 4 segmentos 0 en todo el sistema.
- Si el segmento 0 tiene que ser uno solo pero debe ser compartido entre todos por medio de punteros. Es decir que habría un solo segmento 0 afuera del espacio de usuario que tiene que ser referenciado por todos los procesos y ademas por el espacio de memoria. No estoy nada seguro de esta ya que no tiene sentido que el segmento este por afuera de la memoria. 

Basicamente, no sabemos bien como hacer para implementar este segmento 0 y donde tiene que ir y donde no y de que forma.  

2. Además, tenemos una duda de saber si pensamos bien la idea de la lista de huecos libres:

Pensamos que lo mejor seria tratar cada hueco libre como un elemento que tiene una base y desplazamiento, y cada vez que se agrega/elimina un proceso hay que modificar esta lista. Estaria bien pensado asi? 

3. La ultima pregunta seria sobre el id del segmento que recibe kernel en CREATE_SEGMENT. Éste id que recibe kernel es el mismo que se referencia en la tabla de segmentos? Es decir, si CPU pasa un CREATE_SEGMENT con id = 4, eso quiere decir que tengo que crear un segmento con el id 4? Ya que nuestra tabla de segmentos tiene id, base, limite.
Ademas, no sabemos es si CPU podria por ejemplo pedir 2 segmentos con el mismo id, o si en Kernel se conoce que ids ya estan asignados.

Desde ya, muchas gracias.

**Comment by iago64** [comment]
Buenas! Cómo va?
Hermoso el orden de las preguntas, vamos con las respuestas

1.- Van a tener solo 1 segmento 0 en todo el sistema y lo que va a pasar es que todas las tablas de segmentos de los procesos, van a tener el mismo segmento 0.

2.- No hay una única implementación correcta para los huecos libres, la que estan planteando es una linda implementación para tener los huecos libres, la pregunta que te puedo hacer para ayudarlos a pensar un poco mas a futuro, como tienen pensado trabajar la compactación?

3.- No necesariamente, el ID de segmento que les pasamos es referente al proceso que ejecuta, pero despues si uds les dan un id auto incremental en la memoria puede ser que el segmento 1 del proceso 1 sea el segmento 45 de su memoria.
Respecto a pedirles que creen 2 veces el mismo segmento, olvídense, no es una prueba que tengamos pensada hacer.

Saludos.-

**Comment by kamipalomino** [comment]
Buenas, 
Sumo una duda sobre el segmento 0, en el caso de que CPU o Filesystem le mande escribir algo en la memoria, tengo que contemplar que pueden pedir o escribir en ese segmento 0?

En el caso que así sea, todos los procesos tienen que saber que ya se escribió en ese segmento?


Saludos!
