### ISSUE TITLE
Tengo dudas de como implementar F_CREATE

### ISSUE THREAD

**Issue by alejandro-mattioli-frba** [sisoputnfrba/foro#3047]
Hola,
Tengo muchas dudas sobre la implementacion de FS, no tengo idea como plasmarlas y no entendi mucho de lo que hablan en otros issues.

1) Cuando el FS reciba un F_CREATE de Kernel, lo que se espera del FS es que cree un archivo con fopen y escriba la estructura del FCB como si fuera un archivo config (como muestra el enunciado) o se espera un archivo plano cualquiera vacío donde despues se va a escribir cuando se reciba F_WRITE? 

2) Al momento de crear un archivo los valores del puntero directo e indirecto por el hecho de crearse "sin bloques asociados" se deja en blanco?

// NOMBRE_ARCHIVO=nombreArchivo
// TAMANIO_ARCHIVO=0
// PUNTERO_DIRECTO=
// PUNTERO_INDIRECTO=

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Tienen que crear el FCB como se muestra en el enunciado y despues a medida que lleguen los F_TRUNCATE le van a asignar los bloques.

2.- Pueden asignarle los primeros bloques (puntero directo y puntero indirecto) al momento de crearlo o pueden hacerlo en el primer F_TRUNCATE, con eso no hay problema.

Saludos.-

**Comment by alejandro-mattioli-frba** [comment]
Gracias!
