### ISSUE TITLE
Duda exceso de bloques

### ISSUE THREAD

**Issue by gabriel1816** [sisoputnfrba/foro#3048]
Hola! cómo les va? Me surgió una duda sobre qué debemos hacer si se excede la cantidad máxima de bloques en el filesystem, es decir ¿se va a testear que se supere el límite? ¿debemos manejar esos errores?, por ejemplo, hacer un f_truncate para agrandar el archivo y que no haya bloques libres, ¿se va a evaluar ese caso?

**Comment by iago64** [comment]
Buenas! Cómo va?

No se preocupen, no vamos a llegar a testear ese caso, la idea del TP es que vean la interacción del kernel con el FS no de que armen un FS completo :wink: 

Saludos.-

**Comment by gabriel1816** [comment]
Muchas gracias!!!

**Comment by gabriel1816** [comment]
Holaaaaa, me surgió una duda más con respecto a la asignación de bloques, yo entiendo que el puntero al primer bloque va en el "puntero directo" del fcb y luego en "puntero indirecto" va el puntero al bloque que tiene los punteros al resto de bloques sin el primero, esto es así? 
Otra duda es cuando hacemos un F_truncate supongamos que, a un archivo con 0 bytes, lo aumento a 128 (2 bloques si cada bloque es de 64), se le asigna solamente un bloque para puntero directo y uno para puntero indirecto no?
Gracias de antemano!

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Tal cual decís, el primer bloque va con el puntero directo y después en el puntero indirecto tenes del segundo bloque de datos en adelante.

2.- Le asignas el bloque de datos para el puntero directo, un bloque de punteros para los indirectos y un segundo bloque de datos apuntado por el puntero indirecto.
En resumen el bloque de punteros no se cuenta para el tamaño del archivo.

Saludos.-

**Comment by gabriel1816** [comment]
Y una última consulta, a la hora de reducir el tamaño del archivo con F_truncate, basta con marcar los bloques con 0 en el bitmap o además hay que limpiar el bloque apuntado por el puntero indirecto, en caso de que sea así, cómo podría limpiarlos? setearlos con otro valor?

**Comment by LeandroCarbajales** [comment]
No haría falta limpiarlos ya que no se va a testear acceder a una posición inválida del archivo, basta con marcar esos bloques como libres y actualizar el tamaño del archivo.

Saludos!
        Lean

**Comment by gabriel1816** [comment]
Muchas gracias!
