### ISSUE TITLE
Duda sobre log FileSystem "Acceso a Bloque:"

### ISSUE THREAD

**Issue by Tomai15** [sisoputnfrba/foro#3051]
Hola, buenas noches. Tengo una duda con respecto a uno de los logs minimos de FileSystem.

El log dice > Acceso a Bloque: “Acceso Bloque - Archivo: <NOMBRE_ARCHIVO> - Bloque Archivo: <NUMERO BLOQUE ARCHIVO> - Bloque File System <NUMERO BLOQUE FS>”

Por lo que entiendo el NUMERO BLOQUE ARCHIVO se trata al numero de bloque dentro de todos los bloques que tiene asignado un archivo. Mi duda es como deberiamos tratar el bloque de punteros de cada archivo, si cuenta como el el primer bloque de cada archivo o directamente deberia aclarar en el log que es solamente el bloque de punteros.

**Comment by iago64** [comment]
Buenas! Cómo va?

Los bloques del archivo van a ser: 
0 el puntero directo
1 en adelante los apuntados por el bloque de punteros.

Despues puede pasarte que el bloque 0 de un archivo sea el bloque número 15 del archivo de bloques porque previamente tenes un archivo que ocupo los bloques del 0 al 14 del archivo de bloques.

La idea de este log es que nos muestren que están usando el FCB.

Saludos.-

**Comment by Tomai15** [comment]
Claro, entiendo. Pero en el caso que haga un acceso al bloque de punteros de un archivo, como seria el formato del log?

**Comment by LeandroCarbajales** [comment]
Buenas!
Deberías aclarar en el log si el acceso es al bloque de punteros del archivo en lugar de un bloque de datos.

Saludos!
         Lean

**Comment by Tomai15** [comment]
Ah, genial. Muchas gracias.
