### ISSUE TITLE
Problemas con los hilos

### ISSUE THREAD

**Issue by tomasmartinez02** [sisoputnfrba/foro#3052]
Hola, estamos en memoria con un problema, los hilos que creamos nunca inician a ejecutar la función que se les pasa en pthread_create, entonces nunca se genera el bucle infinito y el modulo de memoria termina su ejecución. Si llamo a la función en el main, funciona pero ya a esta altura necesitamos si o si hilos distintos de ejecución. Adjunto el código para ver si me pueden dar una mano.
Desde ya gracias

```
static void __inicializar_hilos(){

    pthread_t atencionKernelth;
    pthread_create(&atencionKernelth, NULL, atender_peticiones_kernel, NULL);
    pthread_detach(atencionKernelth);

    return;
}


void *atender_peticiones_kernel(void* args)
{

    for (;;) {
        int socketKernel = memoria_config_get_socket_kernel(memoriaConfig);
        pthread_mutex_lock(&mutexSocketKernel);
        t_header headerRecibido = stream_recv_header(socketKernel);
        t_buffer* bufferRecibido = buffer_create();
        
        switch (headerRecibido) {
            case HEADER_solicitud_inicializacion_proceso:
            {
                stream_recv_buffer(socketKernel,bufferRecibido);
                uint32_t pid = adapter_kernel_recibir_pid(bufferRecibido);
                t_info_segmentos** tablaCreada = crear_tabla_nuevo_proceso(pid);
                adapter_kernel_enviar_tabla(tablaCreada, HEADER_tabla_segmentos);
                log_info(memoriaLogger,  "Creacion de Proceso PID: <%d>", pid);
                break;
            }
            case HEADER_crear_segmento:
            {   
                log_info(memoriaLogger,  "Entra a crear segmento");
                t_info_segmentos *segmento = adapter_kernel_recibir_segmento_a_crear(socketKernel, bufferRecibido);
                log_info(memoriaLogger,  "Recibe segmento a crear");
                uint32_t pid = adapter_kernel_recibir_pid(bufferRecibido);
                log_info(memoriaLogger,  "Recibe pid");
                
                if (verificar_memoria_suficiente(segmento->tamanio)){
                    log_info(memoriaLogger,  "Entra a verificar memoria suficiente");
                    if (verificar_memoria_contigua(segmento->tamanio)) {
                        log_info(memoriaLogger,  "Tiene memoria contigua");
                        uint32_t baseSegmento = crear_segmento(segmento, pid);
                        adapter_kernel_enviar_direccion_base(socketKernel, baseSegmento);
                        log_info(memoriaLogger,  "PID: <%d> - Crear Segmento: <%d> - Base: <%d> - TAMAÑO: <%d>", pid, segmento->idSegmento, baseSegmento, segmento->tamanio); 
                        // No hay que hacer free del puntero?
                    } else {
                        adapter_kernel_solicitar_compactacion(socketKernel);
                        log_info(memoriaLogger,  "Se solicita la compactacion");
                        free(segmento);
                    }
                } else {
                    log_error(memoriaLogger,  "PID: <%d> - Crear Segmento: <%d> - ERROR: No hay memoria suficiente", pid, segmento->idSegmento);
                    adapter_kernel_error_out_of_memory(socketKernel);
                    free(segmento);
                }
                break;
            }
            case HEADER_eliminar_segmento: 
            {
                uint32_t idSegmento = adapter_kernel_recibir_id_segmento_a_eliminar(socketKernel, bufferRecibido);
                uint32_t pid = adapter_kernel_recibir_pid(bufferRecibido);

                eliminar_segmento(idSegmento, pid); // El log esta adentro
                adapter_kernel_enviar_eliminacion_segmento(socketKernel, pid);
                break;
            }
            case HEADER_compactar:
            {
                break;
            } 
            // tambien deberíamos agregar para cuando se finaliza un proceso
            default:
            {   
                // ERROR
                break;
            }
        }
        pthread_mutex_unlock(&mutexSocketKernel);
        buffer_destroy(bufferRecibido);
    }

    return NULL;
}

```

Las funciones no estan en el mismo archivo pero supongo que no influye porque estan incluidas.

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va? 

Me surgen un par de preguntas para entender mejor el contexto del problema:
1- ¿Desde dónde se llama a `__inicializar_hilos()`? ¿Es posible que esa función termine retornando al `main()` y éste último ejecute su `return`? Recuerden que cuando retorna `main()` el proceso finaliza matando todos sus hilos.
2- ¿Cuáles serían los distintos hilos de ejecución? En otras palabras, ¿qué rol cumpliría cada uno?
3- ¿Qué recurso está protegiendo `mutexSocketKernel`? Pregunto porque veo una variable local llamada `socketKernel`, que al ser variable local es única para cada hilo que llame a `atender_peticiones_kernel()`.

Saludos

**Comment by tomasmartinez02** [comment]
Si, se la llama retornando al main y seguramente ese sea el problema. Como deberíamos hacer para que no termine la ejecución del main?
Pensamos en hacer 3 hilos de ejecución, uno para atender cpu, otro para atender filesystem y otro para kernel (no sabemos si no hacer uno exclusivamente para que se encargue de crear y eliminar las estructuras del los procesos cuando se crean o finalizan).
El mutex del socket la idea es que proteja que 2 hilos no estén intentando comunicarse con el kernel al mismo tiempo y así poder recibir datos erróneos.

**Comment by iago64** [comment]
Buenas! Cómo va?

Si la función `__inicializar_hilos()` ejecuta en `main()` y la función `main()` no tiene nada que lo "bloquee", entonces si, se les termina el proceso.
Lo que pueden hacer para resolver ese inconveniente es tener los `pthread_t` como variables en main y en lugar de hacer `pthread_detach()` hacerles `pthread_join()` para que el hilo `main` se quede esperando que estos finalicen.

Saludos.-

**Comment by tomasmartinez02** [comment]
Gracias!
