### ISSUE TITLE
Consulta FileSystem condición de carrera por FS

### ISSUE THREAD

**Issue by ezequielmalfonso** [sisoputnfrba/foro#3054]
Buenas, siguiendo con el **FS**, nos surgió otra duda respecto del manejo del **FS** desde le **Kernel**, estuvimos en este issue #3021, la duda es la siguiente:
Si tenemos un proceso P1, ejecutando F_TRUNCATE para el archivo_1 (se bloquea en la cola de FS hasta q finalice el F_TRUNCATE).
Mientras viene P2 para otro archivo_2, y quiere comenzar a utlizar el **FS** con F_OPEN.
Que pasa con P2?:
- Se bloquea todo el proceso para que el planificador pueda seguir con otros procesos que vengan puedan utilizar el CPU y P2 cuando se libere el FS pasa al final de la cola de READY y cuando llegue a EXECUTE sigue desde la operación de **FS** que le tenia y ahí verificara si puede o no usar el el **FS**?
- O debe bloquearse y esperar en una cola fifo hasta que entre la instrucción al fs y pasa a ready una vez se completó la instrucción ("instantáneamente" para fopen)?

- Estábamos viendo de implementar un cola de bloqueados por las operaciones de F_TRUNCATE, F_CLOSE,

Cito enunciado:
>Historial de Cambios
Agregada aclaración que el FS atiende peticiones de a una

Gracias.-

**Comment by iago64** [comment]
Buenas! Cómo va?

Es una situación bastante especifica la que estas planteando, pero efectivamente el FS atiende las peticiones de a 1 y justo el F_OPEN no es una instrucción que bloquee al proceso, con lo cual, lo que va a terminar pasando es que uds van a tener a la CPU esperando al Kernel que va a estar esperando que termine el F_TRUNCATE antes de ejecutar el F_OPEN correspondiente.

Una fiaca? Si, total, pero no hace falta que se rebusquen mucho mas con la implementación.

Saludos.-

**Comment by ezequielmalfonso** [comment]
Buenas, antes que nada gracias por la respuesta.
Si en vez de un fopen llega un ftruncate mientras está ocupado el fs, también se queda el cpu esperando o ejecuta el que siga en ready?

Saludos.-

**Comment by iago64** [comment]
Buenas! Cómo va?

El resumen del accionar de las operaciones son: 

F_TRUNCATE: Bloquea el proceso y lo desbloquea cuando termina.
F_OPEN: No bloquea el proceso y eventualmente puede darse la situación donde la CPU este esperando que terminen otras operaciones.
El FS atiende las peticiones de a 1 en el orden que llegan.

Te hago una pregunta ¿Estas intentando hardcodear todas las posibles situaciones que se pueden dar en las pruebas? 

Saludos.-

**Comment by ezequielmalfonso** [comment]
Hola, no, nos armamos archivos de instrucciones de prueba y queríamos ver si iba bien la cosa porque probando nos genero muchas dudas como manejarlo, primero hicimos una cola de bloqueados de FS, que cuando se producía un ftruncate crea un hilo mientras espera que finalice esa operación y pasamos de ready ->execute el próximo proceso, pero cuando hicimos una prueba de enviar 3 consolas, 2 con el mismo archivo y 1 con otro archivo se nos genero una mezcla de los procesos, y a veces quedaba colgado alguno sin terminar, eso nos dio la pauta de que teníamos algo mal sincronizado con estas operaciones. Pero dps nos comenzó a surgir la inquietud de como se deberían dar los casos, y estábamos discutiendo entre dos posibilidades:
1 - Era de que cuando un proceso esta haciendo uso del FS independientemente del archivo, si viene otro proceso, lo mando a la cola de bloqueados y ahí entra en la planificación y volvera a ready  y cuando le toque puede correr el riesgo de volver a bloqueado si hay un procesos haciendo uso del FS.
2- Y la otra era si un proceso esta usando algún instrucción bloqueante que pasaba con las que no,  y creo que nos aclaraste bastante.

Gracias y cualquier cosa te seguimos preguntando.

**Comment by iago64** [comment]
Buenas! Cómo va?

Creo que están sobre pensando las cosas más de lo que hace falta.
Traten de quedarse con lo que dice el enunciado, en el caso de las operaciones que les dice que bloquea el proceso, lo mandan a bloqueado y lo atienden cuando corresponde, si no dice que se bloquea (como F_OPEN) van a tener que dejar todo medio congelado hasta que le toque el turno ya que el Kernel le va a ir tirando las peticiones al FS a medida de que le van llegando.

Saludos.-

**Comment by irinaperezg** [comment]
Una consulta, para ver si nos quedó claro porque estabamos viendo lo mismo
Si FS está atendiendo un f_truncate y el proceso se bloquea y el proceso que le toca ejecutar hace un F_OPEN, tiene que quedarse ejecutando "esperando" a que termine f_truncate y recién ahí hacer el fopen o debe bloquearse tambien y pasar al siguiente proceso?

**Comment by LeandroCarbajales** [comment]
Buenas @irinaperezg !
Reiterando las respuestas de @iago64 y lo que dice el enunciado, el F_OPEN del Kernel de este TP **únicamente** bloquea al proceso si el archivo ya está abierto, por lo tanto podría llegar a darse el primer escenario que mencionás pero nunca el segundo. 
Es algo que tengan que tener en cuenta? En absoluto, si siguen la implementación del enunciado es lo esperado que ocurra normalmente.
Es ineficiente? Claro que sí, y es un caso borde que esperamos que identifiquen (como lo acaban de hacer) de esta implementación particular de bloqueos.

Saludos!
        Lean

**Comment by irinaperezg** [comment]
Genial gracias! Lo implementamos bien entonces, es que nos parecía raro que el proceso que hace el f_open se quedase "ejecutando" pero sin hacer nada hasta que no terminara f_truncate pero ahora nos quedamos tranquilas :)

**Comment by iago64** [comment]
Buenas! @ezequielmalfonso te queda alguna duda? Podemos ayudarte con algo mas respecto a este issue?

**Comment by iago64** [comment]
Cerramos el issue por inactividad.
