### ISSUE TITLE
Serializacion de puntero de CPU a MEMORIA

### ISSUE THREAD

**Issue by fpesce27** [sisoputnfrba/foro#3055]
Hola tengo una duda, a la hora de que mov_out  o mov_in en el cpu le envien a memoria la direccion fisica para que operen, cual seria la mejor forma de serializarlo? Porque usamos un void* para representar el puntero, ya que no sabemos a que puede estar apuntando. Pensamos en quizas serializar el contenido al que apunta el puntero pero al no saber a donde apunta siento que es muy enrevesado, muchas gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Una pregunta para entender un poco mejor, ¿Cómo están administrando los segmentos?, es decir, ¿Qué estructuras tienen en la memoria para saber que segmento está ocupado y que segmento esta libre? 

Me parece que están complicándose más las cosas de lo que esperamos que se las compliquen, como consejo, la dirección física de la memoria puede tener una "traducción" que sería que la dirección física 0 es el puntero que les devuelve el `malloc()` que hacen al inicio de la memoria para reservar el espacio de usuario y de ahi pueden empezar a calcular todas las demás direcciones y las mismas serían un simple `int` que es mas simple de serializar.

Saludos.-

**Comment by fpesce27** [comment]
Para saber que segmento esta libre, usamos una lista de huecos libres, donde cada hueco tiene la base, el tamaño y si esta libre. El problema es el siguiente, este es el codigo de CPU para que se entienda mejor:
`case MOV_OUT:
		log_info(LOGGER_CPU, "PID: %d  -Ejecutando: %d - %s %s", ctx->PID, instruccion_actual->operacion, instruccion_actual->parametros[0], instruccion_actual->parametros[1]);
		registro = obtenerRegistro(&ctx->registros, instruccion_actual->parametros[1]);
		dir_fisica = MMU(atoi(instruccion_actual->parametros[0]), atoi(instruccion_actual->parametros[1]), ctx);
		if (!dir_fisica)
		{
			return SEG_FAULT;
		}
		agregar_parametro_desalojo(ctx, registro);
		agregar_parametro_desalojo(ctx, dir_fisica);
		paquete = crear_paquete(MOV_OUT);
		serializar_motivos_desalojo(ctx->motivos_desalojo, paquete);
		enviar_paquete(paquete, SOCKET_MEMORIA);
		free(paquete);

		// recibir ok memoria
		recibir_operacion(SOCKET_MEMORIA);
		char *mensaje = recibir_mensaje(SOCKET_MEMORIA);
		if (strcmp(mensaje, "OK") != 0)
		{
			log_error(LOGGER_CPU, "PID: %d  -Error al escribir en memoria", ctx->PID);
			return SEG_FAULT;
		}

		log_info(LOGGER_CPU, "PID: %d  -Acción: ESCRIBIR - Segmento: %s - Dirección Física: %s - Valor: %s", ctx->PID, floor_div(atoi(instruccion_actual->parametros[1]), TAM_MAX_SEGMENTO), dir_fisica, "hola");

		return 0;`
El problema esta en que la funcion MMU que dada una direccion logica te devuelve la fisica, luego, esa direccion fisica se la tengo que enviar a memoria para que escriba en esa direccion, cual seria la mejor forma de serializar el void* que devuelve el MMU (la direccion fisica) o hay alguna forma mejor de manejar esto?

**Comment by RaniAgus** [comment]
¡Buenas!

Tanto los punteros como las direcciones físicas/lógicas son índices dentro de un gran array de bytes, por lo que también podrían pensarlo como números enteros que pueden serializar y deserializar de la misma forma que cualquier otro `int`.

De hecho, hasta no es necesario modelar a la dirección física como un `void*`, podría ser tranquilamente un `int` y al calcular dónde escribir/leer pueden usar aritmética de punteros para desplazarse dentro del `malloc()` inicial usando la dirección física como offset.

> Dato de color: los punteros que usan en C [son en realidad direcciones lógicas, no físicas](https://www.youtube.com/watch?v=Aw0YAUdQp1c).

Saludos

**Comment by fpesce27** [comment]
Ah perfecto, muchas gracias!
