### ISSUE TITLE
Duda con finalizar los procesos cuando hay segmentation fault

### ISSUE THREAD

**Issue by MarcosGurruchaga** [sisoputnfrba/foro#3056]
### 📔 Citas del enunciado/videos
![image](https://github.com/sisoputnfrba/foro/assets/83126979/4e5b29b0-1bc3-426b-bdf4-f0670a6f5c8d)

**Duda:**
Tengo una duda con esta parte del enunciado dentro de la sección "MMU". ¿El segmentation fault lo chequea el modulo de memoria verdad? porque ese tamaño del segmento que se menciona, no entendi si es el tamaño del segmento o el tamaño máximo posible. 

Suponiendo que es el tamaño del segmento, deberia utilizar la conexion de cpu a memoria para primero chequear si hay segmentation fault y avisarle al cpu que ocurrio con el nro de segmento y ese desplazamiento (direccion logica que luego memoria sabe que dir fisica es a partir de la base de segmento), para lo cual el devuelve el contexto al kernel y finaliza el proceso? Osea la conexión de cpu con memoria sirve para eso, calcular la dirección fisica y dársela al kernel para que luego haga cosas como enviarsela al filesystem para que haga el fwrite o fread, volvíendose a comunicar con memoria? 

Otra duda relacionada aunque supongo que se puede hacer de las dos formas: quiero hacer un mov in, la cpu deberia devolverle el contexto al kernel para que le pregunte a memoria, este le devuelva el valor leido y luego kernel se lo mande a cpu para que lo almacene en el registro o directamente puedo hacer que le llega el mov in a cpu y lo hace a traves de su conexion con memoria (es decir, la memoria le lee el valor y se lo devuelve a la cpu para que lo guarde en el registro?

**Comment by iago64** [comment]
Buenas! Cómo va?

El módulo que checkea el segment fault es la CPU.
Lo tienen que hacer basándose en el tamaño del segmento que tienen en la tabla de segmentos que es parte del contexto de ejecución.
El tamaño máximo del segmento les sirve para poder saber con qué segmento tienen que operar y cito al enunciado:

> **num_segmento** = floor(dir_logica / **tam_max_segmento**)

Si el desplazamiento del segmento les da más grande que el tamaño del segmento es seg fault y ahi le tienen que devolver al Kernel el contexto de ejecución avisándole que lo mande a EXIT porque finaliza por seg fault.

Las operaciones de MOV_IN y MOV_OUT son las únicas operaciones de la memoria en las cuales la CPU le pide cosas directamente a la memoria.

Saludos.-

**Comment by MarcosGurruchaga** [comment]
Gracias, se re entendio
