### ISSUE TITLE
Algunas dudas sobre File System

### ISSUE THREAD

**Issue by D-M-Gonzalez** [sisoputnfrba/foro#3057]
Que tal buenas noches!

Tenemos un par de dudas con respecto a la implementación de File System.

Por un lado, la función mmap() vs fseek()/fwrite()/fread()
Entiendo que los últimos utilizan lógica muy similar a realizar memcpy(). Como primera implementación, vamos a utilizar un void* espacio_disco = malloc(TAM_BLOQ * CANT_BLOQ) y estaremos realizando las operaciones sobre este espacio de memoria.
Entiendo que luego esto, en vez de hacerlo sobre un espacio de memoria, hay que hacerlo directamente sobre el archivo de bloques utilizando fseek()/fwrite()/fread() verdad? Y que en estos últimos yo puedo hacer un fseek por ej a fseek(stream, 0, id_bloq * tam_bloq) posicionandome en bloque que quiero escribir/leer luego y de esta manera manejarme sobre el archivo como si se tratase de un memcpy. Que ventaja trae mmap entonces? porque lo leimos y no logramos entenderlo.

Por otro lado, en que momento utiliza el file system TP la memoria RAM?, porque no veo en ningun lado una estructura para dar a conocer que los FCB se guardan en la ram...
Solo se utilizan para sacar y meter datos algo así como MOV_IN/MOV_OUT? en ningun momento se pone en ram el archivo en si o su FCB verdad?

**Comment by iago64** [comment]
Buenas! Cómo va?

Si usan `mmap()` lo que tiene es que todo lo resuelven con `memcpy()`, mientras que con `fseek() / fwrite() / fread()` es como dicen, que tienen que tener un espacio de memoria reservado para ir leyendo / escribiendo del archivo.

Respecto al tema de los FCB, en el TP no tienen que cargar nada de los FCB en el módulo memoria.

Saludos.-

**Comment by irinaperezg** [comment]
>  tienen que tener un espacio de memoria reservado para ir leyendo / escribiendo del archivo. 
Esto es obligatorio de implementar? Yo estaba escribiendo directamente en el archivo de bloques, estaría mal?
En el caso de los fcbs si  escribo primero en una estructura y después lo persisto, pero no le vi mucho sentido a hacer lo mismo en el archivo de bloques.

**Comment by D-M-Gonzalez** [comment]
Muchisimas gracias!
Ahí entendí para que era el mmap gracias a ese comentario jaja, y lo pude hacer andar. Leemos y escribimos con memcpy directamente en el archivo es excelente!.
