### ISSUE TITLE
Duda compactacion + IDs segmentos

### ISSUE THREAD

**Issue by lucasdeferrari** [sisoputnfrba/foro#3058]
Buenas tardes, tenemos una duda acerca de que pasa con los IDs de los segmentos cuando el Kernel le pide una compactacion a la Memoria. Una vez que la Memoria compacta tiene que devolver las tablas de segmentos actualizadas. El tema es, no entendemos como hace la memoria para devolverle al Kernel los IDs de los segmentos que tenia antes, ya que cuando creamos un segmento en memoria le asignamos un id auntoincremental distinto al id que se usa en kernel. 

Pensamos tener dentro del struct segmento 2 variables ID, una que sea para el manejo en memoria, y otra en la que se guarde el ID que llega de kernel para usarlo en la compactación. Tendría sentido esta solución? Cuando compactamos vamos a cambiar las bases de varios segmentos de distintos procesos a la vez por lo que si dejamos solo el ID del Kernel, para esto pensamos tener un id autoincremental en la memoria porque sino ¿Cómo sabría la memoria de qué segmento de qué proceso debe cambiar la base?

Desde ya, muchas gracias.

**Comment by iago64** [comment]
Buenas! Cómo va?

Hay una cosa que no me termina de cerrar y es porque al compactar estarían cambiando los ids de segmento, ya que lo único que tendrían que hacer es mover la base del segmento al inicio (y copiar el contenido dentro del void* del espacio de usuario)

Eventualmente las estructuras que utilicen para administrar el void* pueden tener los campos que uds necesiten, pero me preocupa el hecho de que esten creando segmentos "nuevos" a la hora de compactar.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Agrego a la respuesta de @iago64 por esta parte

> ya que cuando creamos un segmento en memoria le asignamos un id auntoincremental distinto al id que se usa en kernel.

Por qué tendrían ids de segmentos distintos en Kernel que en Memoria? Si es el módulo Memoria el único que modifica la tabla de segmentos y se las devuelve al Kernel.

**Comment by lucasdeferrari** [comment]
Buenas! Perdon, quizas me exprese mal, no queria decir que se cambiarian los IDs del segmento cuando se compacta, sino que si la Memoria no conoce los IDs que maneja Kernel, no podria decirle a que ID de segmento pertenece cada uno para que actualice sus tablas.

En cuanto a la respuesta de Leandro, en el punto 3 del issue #3046 nos dijeron que Memoria podia manejar un ID distinto al del kernel.

**Comment by lucasdeferrari** [comment]
Genial, gracias!
