### ISSUE TITLE
Dudas respecto a la escritura/lectura en memoria

### ISSUE THREAD

**Issue by FacundoPiaggio** [sisoputnfrba/foro#3059]
Buenas!

En mi grupo estamos teniendo un debate de como entendemos el enunciado a la hora de escribir/leer en memoria.

Por un lado entendemos que el CPU es el que calcula la dirección física dada la lógica, eso se lo pasa a memoria cuando ejecuta el MOV_OUT/IN y después en memoria se hará el memcpy(memoria+DF, valor, size); (si es escritura) o memcpy(valor, memoria+DF, size); (si es lectura). Sin importarle a que segmento o proceso pertenezca esa memoria, porque de eso se encarga el cpu cuando se fija si hay Seg_fault, o si esta accediendo a un segmento valido de la tabla del proceso.

Por otro lado, otros integrantes del grupo entienden que la DF es calculada en memoria y se escribe/lee a partir de la base de un segmento. Ademas de que si le importa a que segmento y pid pertenece esa memoria.  

Saludos.

**Comment by iago64** [comment]
Buenas! Cómo va?

Por desgracia ambas visiones estan bien y depende de como lo terminen implementando, ya que uds con las cuentas que están en el enunciado en la parte de la MMU, lo que calculan es el nro de segmento y el desplazamiento.
Si uds en la misma CPU suman la base del segmento + desplazamiento y le mandan esa dirección a la memoria, es el primer escenario
Si uds en la CPU solo mandan el desplazamiento y el nro de segmento, entonces es la memoria la que tiene que hacer la cuenta y le importa saber que proceso y que segmento están accediendo.

Saludos.-

**Comment by FacundoPiaggio** [comment]
Ah excelente dami, muchas gracias!

**Comment by bot37** [comment]
Buen día!

Creemos que si usamos el segundo enfoque que se menciona, la tabla de segmentos en cada PCB no se usaría en ningún momento (incluso en la compactación), sino que se podría manejar todo con las estructuras de memoria. Es esto correcto?

Gracias!
