### ISSUE TITLE
Duda sobre f_open, bitmap y asignación de bloques

### ISSUE THREAD

**Issue by franco-magne** [sisoputnfrba/foro#3060]
¡Buenas!

Terminé implementando la creación de FCBs con sus respectivos configs a demanda, a medida que se solicitan los f_open. Ahora, no estoy seguro si es necesario la validación de que haya espacio disponible para crearlo. Citando el ejemplo del fcb.config, si TAMANIO_ARCHIVO=256, ¿tengo que chequear que hayan 4 bloques disponibles (64 Bytes) en el archivo de bloques o es uno de esos escenarios **que no van a suceder** al momento de hacer las pruebas?

Luego, el tema de la asignación de bloques, ¿es simplemente esto de corroborar que haya espacio para que ese archivo pueda escribir o tengo de alguna manera reservarlos para el fcb que solicitó su f_open por primera vez y que ningún otro archivo pueda acceder o tomarlos? Si tengo que reservarlos me imagino que tengo que ver en el bitmap los N primeros bloques libres que el fcb necesite, ver su correspondencia en el archivo de bloques y estos guardarlos en el bloque de punteros que se mencionó en otros issues. ¿Va por ahí?

Relacionado a lo anterior, si reservo los bloques para un fcb entiendo que en el bitmap van a seguir apareciendo como libres porque están vacíos ya que no fueron escritos aún (en este ejemplo). Si llega otro archivo para crear su fcb y encuentra estos mismos bloques como libres, debería chequear también que esos bloques no se encuentran ya asignados a otro fcb, ¿no? Otra alternativa que pensé es que si asigno unos bloques a un fcb setee al bit con 1 en el bitmap para que no los tome otro fcb, pero entiendo que sería incorrecto porque los bloques están vacíos.

Una duda corta sobre el bitmap: dado que los bloques son de 64 bytes tienen espacio suficiente para saber si hay 8 bloques libres u ocupados dentro. Si un bloque solo ocupa/escribe 5 posiciones y le quedan 3 libres, su estado en el bitmap sería libre, ¿no? Solo lo marco como ocupado cuando ocupó todo me imagino.

Por último, citando la issue #3047 donde mencionan que la asignación de bloques se puede hacer al momento de crearlo o al primer f_truncate, ¿no se puede dar el caso en el que sin antes haber hecho un f_truncate solicite leer o escribir un archivo que ya fue creado pero no tenga sus bloques asignados? Me estaba por decidir de asignar los bloques al momento de crear el fcb, pero esto me generó un poco de confusión y no sé si entendí bien la respuesta del ayudante.

Eso es todo. Desde ya gracias.

**Comment by iago64** [comment]
Buenas! Cómo va?

Respecto a los FCB, uds no deberían checkear si tienen espacio al momento de crearlo porque se crean en 0 los archivos, de todas formas no vamos a hacerles ninguna prueba de llenar el FS hasta que no queden bloques libres.

Volviendo un poco al punto anterior, al hacer un F_OPEN, si llegan a tener que crear el archivo, el mismo lo van a crear en 0 de tamaño y despues con F_TRUNCATE es que van a asignarle bloques.

Respecto al bitmap, un bloque que asignen a un FCB, van a tener que marcarlo como ocupado ya que los bloques **no se comparten entre archivos**

Sobre lo último, no, no vamos a hacerles un F_READ o un F_WRITE de un archivo en una posición inexistente, lo que si puede pasar es que un proceso haga el F_OPEN, F_TRUNCATE y F_CLOSE y otro solo haga F_OPEN y despues el F_READ / F_WRITE.

Saludos.-

**Comment by franco-magne** [comment]
Entonces el valor TAMANIO_ARCHIVO=256 del fcb.config ejemplo es de un FCB que ya hizo un F_TRUNCATE, no es su estado inicial. Yo tengo en una carpeta los fcbs.config donde los leo y creo las estructuras, y había entendido que lo creaba con ese tamaño. Debería cambiarlo a cero en el config, ¿no?

Bien, entonces entiendo que la asignación de bloques es indicado hacerlo al momento del F_TRUNCATE.

Sobre el ejemplo que menciona al final, un proceso hace F_OPEN y después F_READ/FWRITE: ¿es uno de esos casos error que esperan que suceda? Porque tendría tamaño cero y asumiendo que no hizo un F_TRUNCATE antes de hacer el F_OPEN (por ejemplo, abre el archivo, hace el truncate, lo cierra y después lo vuelve a abrir).

Sumo una duda de la creación de archivos en el caso que FS le avisa a Kernel de que no existe el archivo. ¿Lo único que recibe FS para crearlo es el nombre de ese archivo y los demás datos los inicializo en cero? Como no es una instrucción de CPU y no está el detalle de los parámetros que le llegan a FS quería confirmar.

**Comment by franco-magne** [comment]
Todo resuelto. ¡Muchas gracias!
