### ISSUE TITLE
Dudas sobre FS

### ISSUE THREAD

**Issue by irinaperezg** [sisoputnfrba/foro#3061]
Holis :) Que tal? Tengo un surtido de algunas preguntas de FS

1. ¿Dónde leemos lo que está en filesystem para mandárselo a memoria? ¿Está bien hacerlo en un char *y después ponerlo en un buffer para enviárlo?
2. ¿Hay que persistir el fcb a medida que se asigna/desasigna CADA bloque o se puede nada más persistir en cada f_truncate? (osea cuando se asignen/desasignen toda la cantidad de bloques deseada)
3. ¿El tiempo de retardo de acceso a bloque solo se tiene en cuenta para fwrite y fread? o también se debe tener en cuenta para ftruncate cuando escribimos en el bloque de punteros los punteros a otros bloques ?
4. ¿En las pruebas siempre que haya un f_open va a haber (eventualmente) un f_close? porque si lo hacemos anda perfecto pero si no hay fclose da mal, no se si es algo que hay que checkear.
5. Con respecto a la persistencia, se refiere a que cada vez que compilemos los módulos todos los fcbs/archivos/bitmap tienen que estar? Osea que la única vez que se crea el bitmap con todo 0 es la "primera" vez que se ejecuta?

gracias por tanto <3

**Comment by iago64** [comment]
Buenas! Cómo va?

Gracias por numerar las preguntas 😊 

1.- Por el donde te referis al tipo de dato? Si es asi, es medio irrelevante ya que en C los tipos de dato son una forma de interpretar los bytes en esa posición de memoria, pero si, un char* es una buena opción siendo que los registros van a tener valores ASCII.

2.- Pueden persistirlo despues de hacer todo el F_TRUNCATE y asignar todos los bloques que sean necesarios.

3.- Tienen que tenerlo en cuenta cada vez que leen / escriben en un bloque, entonces aplica para F_READ, F_WRITE y cuando acceden al bloque de punteros (lo cual puede hacer que tengan 2 accesos a bloque si tienen que leer / escribir en un bloque que esta apuntado por el bloque de punteros)

4.- Si tranqui, para este TP si hay un F_OPEN, hay un F_CLOSE.

5.- Efectivamente, solo inicializan todo la primera vez, despues tienen que mantener todo lo que encuentren, es la idea de tener un File System 😉 

Saludos.-

**Comment by irinaperezg** [comment]
Genial, muchas gracias!!
Solo queria consultar una cosita más del #3057, quería saber si se podia escribir/leer directo en el archivo de bloques o si era obligatorio tener un espacio en memoria :)

**Comment by irinaperezg** [comment]
genial muchas gracias!!
