### ISSUE TITLE
Test de lo que envío de un módulo a otro

### ISSUE THREAD

**Issue by Fcallero** [sisoputnfrba/foro#3062]
Buenas, de casualidad se podría de alguna forma testear lo que se envía de un módulo a otro módulo de alguna forma con cspec? osea si en una función hago un enviar_paquete() a otro módulo, mi duda es como puedo testear si el paquete que le envía es correcto? Estuve buscando información pero no encontré nada. Saludos.

**Comment by LeandroCarbajales** [comment]
Buenas!
Cspec es una herramienta principalmente para realizar pruebas unitarias. En ese sentido, pueden probar que lo que envían es correcto realizando algún tipo de assert sobre el contenido del buffer que envían.
Si lo que están buscando en cambio es testear que ese mismo mensaje le llega al otro módulo o que el mensaje que recibe el otro módulo es correcto, eso ya lo veo más como un test de integración, para lo que creo que Cspec no sería la herramienta adecuada y para ese caso de uso en particular recomendaría simplemente ejecutar ambos módulos y loguear o ver en debug el contenido que envían y que reciben para verificar eso.

**Comment by Fcallero** [comment]
ah ok buenisimo, Gracias!! Tendremos que hacer las pruebas integrales

**Comment by Fcallero** [comment]
ah ok buenisimo, Gracias!! Tendremos que hacer las pruebas integrales.
