### ISSUE TITLE
Duda sobre tabla de segmentos y el Ids de los segmentos

### ISSUE THREAD

**Issue by FranPenaUtn** [sisoputnfrba/foro#3063]
Hola buenas tardes!
Tengo algunas dudas sobre la tabla de segmentos y los IDs de los mismos. En su momento había visto un issue (que ahora no lo encuentro) donde se mencionaba que no hacía falta un campo id dentro de la estructura segmento, ya que si utilizamos una estructura como esta:   
```
typedef struct {
    int pid;
    t_list* segmentos;
} t_tabla_segmentos;
```
y guardamos los segmentos en una lista podríamos usar como id de segmento el índice de la lista. Partiendo de que esto sea correcto, mi duda es la siguiente:
Supongamos que al modulo de memoria le llega la orden de crear un segmento con id 2, pero nunca se pidió crear para ese proceso el segmento con id 1, si establecemos los IDs de los segmentos por el índice de la lista entonces sería imposible crear dicho segmento, a menos que, previamente (al iniciar la tabla de segmentos por ejemplo) completemos la lista de segmentos con segmentos `nulleados` es decir, con la cantidad máxima de segmentos permitidos pero sin valor.

_Segmento nulleado (sin valor):_
```
typedef struct {
    void* direccion_base;
    int tamanio_segmento;
} t_segmento;

t_segmento* segmento_nulleado = malloc(sizeof(t_segmento));
segmento_nulleado->direccion_base = NULL;
segmento_nulleado->tamanio_segmento = 0;
```

Gracias!

**Comment by LeandroCarbajales** [comment]
Buenas!
>  a menos que, previamente (al iniciar la tabla de segmentos por ejemplo) completemos la lista de segmentos con segmentos nulleados es decir, con la cantidad máxima de segmentos permitidos pero sin valor.

Exactamente, si lo quieren implementar de esa forma (usar el mismo índice de la lista como id del segmento), tendrían que crear todas las entradas preventivamente y todos esos segmentos tendrían tamaño 0 (la dirección base sería irrelevante porque nunca serían accedidos), luego a la hora de crear un segmento actualizarían el tamaño y dirección base de la entrada correspondiente al id.

Les aclara la idea?
Saludos!
         Lean

**Comment by FranPenaUtn** [comment]
Perfecto Lean, clarisimo! 

Gracias
