### ISSUE TITLE
Problema con Bitmap

### ISSUE THREAD

**Issue by fmarsico8** [sisoputnfrba/foro#3064]
Buenas, estamos teniendo problemas con llenar el bitmap de 0, nuestra idea fue iterar el bitarray y llenarlo de 0 con la función bitarray clean bit, que por lo que entendemos setea todas las posiciones en 0. Cuando lo debuggeamos nos salió el error de SIGBUS: Bus error pero todavía no entendemos porque. También intentamos con la función memset pero igualmente nos da error. Antes iterabamos el archivo y los escribíamos con 0 (Lo cambiamos porque nos dijeron que no se hacia asi) y nos daba la cantidad bien así que entendemos que el bitmap_size no es el problema. 
### 📝 Código relevante
```
t_bitarray* crear_bitmap(char* path) {


    FILE* archivo_bitmap = fopen(path, "w+");

    if (archivo_bitmap == NULL) {
        printf("No se pudo crear el archivo del bitmap\n");
        return NULL;
    }

    //printf("Se creo el bitmap\n");


    off_t bitmap_size = block_count / 8; // Calcula el tamaño del bitmap en bytes
        if (block_count % 8 != 0) {
            bitmap_size++; // Si la división no es exacta, se agrega un byte adicional
        }

    // Mapear el archivo en memoria
    void* bitmapDeBloques = mmap(NULL, bitmap_size, PROT_READ | PROT_WRITE, MAP_SHARED, fileno(archivo_bitmap), 0);
    if (bitmapDeBloques == MAP_FAILED) {
        printf("Fallo mmap\n");
        fclose(archivo_bitmap);
        return NULL;
    }

    t_bitarray* bitarray = bitarray_create_with_mode(bitmapDeBloques, bitmap_size, LSB_FIRST);

	for(int i=0; i<bitmap_size;i++){
		bitarray_clean_bit(bitarray,i);
		}
	
	fclose(archivo_bitmap);
	return bitarray;
}
```

### 💻 Logs
```
Thread #1 [file_system] 3707 [core: 1] (Suspended : Signal : SIGBUS:Bus error)	
	bitarray_clean_bit() at bitarray.c:61 0x7ffff7fa1d94	
	crear_bitmap() at funciones.c:114 0x555555556a20	
	levantar_bitmap() at funciones.c:129 0x555555556a8c	
	main() at filesystem.c:18 0x55555555712f
```

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va?

Según encontré [acá](https://stackoverflow.com/questions/20587935/bus-error-opening-and-mmaping-a-file), el error se debe a que se está intentando escribir en un archivo que no tiene espacio en disco asignado.

Antes de mapearlo a memoria deberían [truncarlo](https://linux.die.net/man/2/ftruncate) para que ocupe el tamaño correspondiente en bytes.

Saludos

**Comment by fmarsico8** [comment]
Muchas gracias, creo que con eso se nos arreglo =)

**Comment by Luli57** [comment]
@fmarsico8 como lo solucionaron? Porque nos pasa algo similar cuando queremos hacer bitarray_teast_bit(bitarray,i)

**Comment by RaniAgus** [comment]
¡Buenas @Luli57! En el comentario de más arriba dejé el link a la documentación de una función que permite truncar un archivo: https://linux.die.net/man/2/ftruncate

Si con esto no se resuelve su problema, por favor abran un nuevo issue, ya que nos llega una notificación a todos los ayudantes cada vez que se abre uno (en cambio, si comentan un issue cerrado, solo nos llega a los que respondimos ese).

Saludos
