### ISSUE TITLE
dudas del kernel

### ISSUE THREAD

**Issue by agusdubreucq1** [sisoputnfrba/foro#3065]
buenas, tenia un par de dudas la implementacion del kernel.
1) cuando un proceso hace un WAIT y no se bloquea porque habia instancias del recurso, significa que el proceso no es desalojado de la CPU por ende no debe estimar la siguiente rafaga, o debe ir a ready y calcular la rafaga
2) En los logs del kernel dice:
>Fin de Proceso: “Finaliza el proceso <PID> - Motivo: <SUCCESS / SEG_FAULT / OUT_OF_MEMORY>”
osea que hay 3 formas de que un proceso finalice, cuando un proceso hace un WAIT de un recurso que no existe y se debe finalizar el proceso que motivo deberia ir.
3) si yo creo una estructura archivo(con el nombre y lista de bloqueados) cuando hago un F_OPEN y el archivo no se encuentra en la tabla global, cuando yo cierro el archivo(ya sea por F_CLOSE o porq un proceso que tenia ese archivo termino) y la lista de bloqueados esta vacia, yo ya podria liberar la memoria de ese archivo creado no?

**Comment by LeandroCarbajales** [comment]
Buenas!
1- En ese caso debe seguir ejecutando el mismo proceso.
2- Faltaba incluir el ejemplo por recurso inválido en el log, ahí lo agregamos :)
3- Si la lista de bloqueados está vacía (su recurso asociado pasa a valer 1), es decir, no hay ningún otro proceso que tenga el archivo abierto, deberían quitar esa entrada de la tabla global. Cito al enunciado:

> F_CLOSE: Esta función se encargará de quitar la entrada correspondiente al archivo recibido por parámetro de la tabla de archivos abiertos del proceso, en este punto pueden ocurrir 2 cosas:
Hay procesos bloqueados esperando por este archivo. En este caso, se deberá desbloquear al primer proceso bloqueado en la cola del archivo.
No queda ningún proceso que tenga abierto el archivo, por lo que se deberá eliminar la entrada también de la tabla global de archivos abiertos.

Te aclara las dudas?
Saludos!
       Lean

**Comment by agusdubreucq1** [comment]
si perfecto, muchas gracias!

**Comment by LeandroCarbajales** [comment]
Genial :)
Recuerden que pueden cerrar el issue cuando la duda está resuelta.
