### ISSUE TITLE
Duda puntero indirecto - FS

### ISSUE THREAD

**Issue by FrandelCampo** [sisoputnfrba/foro#3066]
Buenas! Tengo una duda sobre la implementación del puntero indirecto del FCB y bloques en general. Tenemos entendido que el archivo de bloques va a ser un array de estructuras tipo bloque, los cuales podran almacenar los valores contenidos en los registros (salvo que sean bloques libres). ¿Sería valido hacer una estructura que represente a otro tipo de bloque, cuya finalidad sea almacenar los punteros a esos bloques de datos? O deberíamos abstraer la idea de "bloque" y que sean todos iguales/misma estructura?
Saludos!

**Comment by LeandroCarbajales** [comment]
Buenas!

> estructuras tipo bloque, los cuales podran almacenar los valores contenidos en los registros (salvo que sean bloques libres).

Ojo en sobrecomplicarse la implementación con esto, si hacen las cosas bien los bloques de datos solamente contienen "bytes" que leen del módulo Memoria, sin ningún formato en específico.

> ¿Sería valido hacer una estructura que represente a otro tipo de bloque, cuya finalidad sea almacenar los punteros a esos bloques de datos? O deberíamos abstraer la idea de "bloque" y que sean todos iguales/misma estructura?

A efectos prácticos podrían hacerlo, pero deberían en cuenta que un mismo bloque podría ser un bloque de punteros en un momento y ser un bloque de datos en otro (si por ejemplo se liberara y se le asignara a otro archivo nuevo).
Si ven al bloque de manera más genérica solamente como un conjunto de bytes, la única diferencia entre un bloque de datos y un bloque de punteros es que este último, al accederlo desde un puntero indirecto, ya sabríamos que hay que leerlo como una seguidilla de números (punteros) cada uno de 4 bytes como indica el enunciado para este FS.

Les aclara la duda?
Saludos!
         Lean

**Comment by FrandelCampo** [comment]
Perfecto Lean, muchisimas gracias!
