### ISSUE TITLE
Formato de los punteros en el bloque del puntero indirecto (FS)

### ISSUE THREAD

**Issue by bot37** [sisoputnfrba/foro#3067]
Buenas! En el filesystem implementamos que las direcciones que se guardan en el bloque del puntero indirecto sean números enteros **decimales**, principalmente porque nos facilitaban ciertos cálculos. Comparando con la teoría, nos surgió la duda de si es esto algo que se puede hacer o lo correcto sería guardar números hexadecimales. **Creemos** que la diferencia sería que, utilizando **hexadecimales**, las direcciones serían más **cortas**, pudiendo así almacenar mayor cantidad de estas en un bloque. aumentando el tamaño máximo posible de un archivo.
Es esta diferencia de tamaños algo relevante/existente o le estamos dando muchas vueltas al asunto?
Gracias! Un saludo.

**Comment by LeandroCarbajales** [comment]
Buenas!
Representar un número en decimal o en hexadecimal no cambia la cantidad **bits** que son necesarios para almacenarlo. En todo caso un número en hexa puede ser más corto de escribir como cadena de caracteres.
En resumen, se están imaginando un problema que no existe :P

Cito al enunciado:
> Nota: todos los punteros del FS se almacenarán como números enteros no signados de 4 bytes (uint32_t)

**Comment by RaniAgus** [comment]
¡Buenas! Me sumo al comentario de Lean con un código de ejemplo:

```c
#include <stdio.h>
#include <stdint.h>
#include <commons/memory.h>

int main() {
	uint32_t decimal = 305419896;
	uint32_t hexa = 0x12345678;

	mem_hexdump(&decimal, sizeof(int));
	mem_hexdump(&hexa, sizeof(int));

	puts("");

	printf("Decimal - %d\n", decimal);
	printf("Hexa    - %d\n", hexa);

	puts("");

	printf("Decimal - %x\n", decimal);
	printf("Hexa    - %x\n", hexa);

	return 0;
}
```

Si lo ejecutan van a ver que tanto `decimal` como `hexa` almacenan exactamente lo mismo en memoria, por lo que ambas variables se pueden imprimir por pantalla en cualquiera de los dos formatos.

**Comment by bot37** [comment]
Buenísimo! Gracias :)
