### ISSUE TITLE
persistencia Archivo de Bloques

### ISSUE THREAD

**Issue by SolGarciaLinfozzi** [sisoputnfrba/foro#3068]
Nuestra duda es al momento de levantar el archivo de bloques y mapear el contenido del archivo en nuestro array de bloques.
También tenemos dudas del contenido de los bloques. Consideramos que un bloque esta compuesto por caracteres. La cantidad de esos caracteres es igual al BLOCK_SIZE que nos llega por el archivo de superbloque. Y en nuestro archivo de bloques cada linea correspondería a cada bloque del array.

### 💭 Soluciones posibles

```
    archivo_bloques = fopen(p_bloques, "r+");
	//"/home/utnso/tp-2023-1c-Los-operadores/Consola/prueba.txt"

	if (archivo_bloques == NULL) {
		fprintf(stderr, "Error al abrir el archivo de bloques.\n");
		exit(1);
	}

	int fd_archivo_bloques = fileno(archivo_bloques);
	printf("File descriptor: %i\n" , fd_archivo_bloques);

	// Ajustar el tamaño del archivo para que coincida con el tamaño del array
	off_t result_archivo_bloques = lseek(fd_archivo_bloques, tamanio_total - 1, SEEK_SET);
	if (result_archivo_bloques == -1) {
		perror("Error al ajustar el tamaño del archivo");
		exit(1);
	}

	// Escribir un byte nulo al final del archivo para que ocupe espacio
	result_archivo_bloques = write(fd_archivo_bloques, "", 1);
	if (result_archivo_bloques == -1) {
		perror("Error al escribir en el archivo");
		exit(1);
	}

	// Realizar el mapeo
	void* mapping_archivo_bloques = mmap(NULL, tamanio_total, PROT_WRITE, MAP_SHARED, fd_archivo_bloques, 0);
	if (mapping_archivo_bloques == MAP_FAILED) {
		perror("Error en mmap");
		exit(1);
	}

```

Pensamos hacerlo de esta manera, y utilizar:

`char array_archivo_bloques[block_count][block_size];`

Pero no sabemos como podemos mapear la memoria.

Considerando que en nuestro archivo de bloques cada linea correspondería a cada bloque del array. Pensamos que podríamos ir leyendo linea a linea el mapping_archivo_bloques e ir guardando la información de cada bloque en nuestro array_archivo_bloques.

**Comment by LeandroCarbajales** [comment]
Buenas!
Solamente a modo de recordatorio, no es necesario mapear el archivo de bloques a memoria ya que para cualquier operación que quieran hacer sobre el mismo con las funciones estándar de manejo de archivos alcanza.
En este caso, veo que ya lo tienen mapeado en la variable `mapping_archivo_bloques`, en cuyo caso, no le veo mucho sentido a este nuevo array `char array_archivo_bloques[block_count][block_size];` ya que justamente perderían las ventajas de tener el archivo mapeado a memoria. Pueden usar directamente la variable `mapping_archivo_bloques` y accederla como si fuera un array de la siguiente forma:
Por ejemplo, con un BLOCK_SIZE=64 si quisiera acceder a la posición (al byte) 200 del archivo, éste se encontraría en su bloque número 3, offset 8, ya que 3*64 + 8 = 200. 
Supongamos que el bloque 3 del archivo corresponde al bloque número 10 del FS, lo accederían haciendo `mapping_archivo_bloques+10*64+8`, más genéricamente `mapping_archivo_bloques+num_bloque*BLOCK_SIZE+offset`.
De esta manera mantendrían las ventajas de tener el archivo mapeado a memoria.

Les sirve la respuesta?
Saludos!
      Lean
