### ISSUE TITLE
Duda segmentos

### ISSUE THREAD

**Issue by vamanfredi** [sisoputnfrba/foro#3070]
Buenas, estaba haciendo algunos casos de prueba para el módulo memoria, y me surgió la duda si la siguiente secuencia de instrucciones es válida:

CREATE_SEGMENT 5 400
DELETE_SEGMENT 5
CREATE_SEGMENT 5 300
### 💭Posibles soluciones

Supongo que no debería hacer mucha diferencia a la implementación, pero justo ese caso me estaba generando conflictos

**Comment by iago64** [comment]
Buenas! Cómo va?

Es una secuencia válida, ya que previo al segundo CREATE_SEGMENT está el DELETE_SEGMENT, lo que no les puede pasar es que les lleguen 2 CREATE_SEGMENT con el mismo id si no se elimina en el medio.

Saludos.-

**Comment by vamanfredi** [comment]
Perfecto muchas gracias!
