### ISSUE TITLE
Manejo de recursos y truncate

### ISSUE THREAD

**Issue by alecaragiulo** [sisoputnfrba/foro#3071]
Buenas tardes, luego de bastante tiempo de haber hecho el manejo de recursos con el grupo nos dimos cuenta que puede ocurrir que un proceso haga wait y luego termine sin hacer el signal, por lo tanto deberiamos llevar algun control de los recursos que tiene asignado el proceso hasta que haga signal, y ver si en caso de que nunca suceda el mismo debamos liberarlos cuando haga exit, o no es necesario el control porque debemos asumir que siempre existirá un signal.

Nuestra otra duda era respecto del truncate ya que no sabemos si es correcto que un proceso entrante deba esperar al bloqueado de la operacion de truncamiento para ejecutar alguna accion del fs.

Muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

Respecto al tema de los recursos asignados, tal cual ven en la teoría al final un proceso tiene que liberar los recursos asignados, cito la página 9 del enunciado:

> Cuando se reciba un mensaje de CPU con motivo de finalizar el proceso, se deberá pasar al mismo al estado **EXIT**, liberar todos los recursos que tenga asignados y dar aviso al módulo Memoria para que éste libere sus estructuras. Una vez hecho esto, se dará aviso a la Consola de la finalización del proceso.

Sobre truncate, el FS atiende las peticiones de a una, con lo cual, todas las operaciones van a tener que "bloquearse" si hay otra ejecutando.

Saludos.-

**Comment by alecaragiulo** [comment]
hola @LeandroCarbajales  si, se entendió, muchisimas gracias!
