### ISSUE TITLE
Consulta sobre creación de segmento y temporizador

### ISSUE THREAD

**Issue by Chabelamas** [sisoputnfrba/foro#3072]
Con respecto al enunciado del trabajo práctico teníamos dos consultas:

1. En vez de devolver la dirección base a Kernel desde Memoria cuando se crea un nuevo segmento, ¿podríamos mandar directamente la tabla de segmentos?
2. ¿Se debería crear un temporizador en Memoria o File System cuando se ejecutan las instrucciones, para después enviárselo a Kernel (para tenerlo en cuenta en la decisión del HRRN)? ¿O no aporta este tiempo en la planificación?

¡Desde ya muchas gracias!

### 📔 Citas del enunciado/videos
> "Que el segmento se cree exitosamente y que la memoria nos devuelva la base del nuevo segmento."

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Tecnicamente si mandan la tabla de segmentos estan mandando la base del nuevo segmento (y mas info) con lo cual no habría problema 😄 

2.- No hace falta ya que los tiempos de FS que pueden afectar son cuando se bloquea el proceso y ahi ya con los timers de READY y EXEC les alcanza.

Saludos.-
