### ISSUE TITLE
Mas preguntas de File System

### ISSUE THREAD

**Issue by D-M-Gonzalez** [sisoputnfrba/foro#3073]
Bueno, seguimos avanzando con File System y nos surgen algunas dudas que no estan aclaradas en el enunciado. Creemos que sabemos como va, pero no estamos seguros.

1) F_SEEK: El fseek modifica el puntero del archivo. Digamos, si mis bloques son de 64 bytes, tengo 3 bloques, tengo reservados 192 bytes. Hasta ahí estamos bien. Ahora, si yo quiero pararme en el byte 150 para realizar un F_READ por ej, el F_SEEK es de 150? o es el valor absoluto desde el bloque 0 de todo el file_system? Creemos que es el primer caso.
2) Cuando nosotros hacemos un F_WRITE o F_READ el proceso va a block y luego llega un nuevo proceso a EXEC. Este nuevo proceso hace algunos create_segment/delete_segment y genera una solicitud de compactación. ¿Que hacemos con este proceso nuevo mientras esta esperando que el F_WRITE o F_READ terminen? ¿Queda bloqueado en EXEC o tenemos que mandarlo a la lista de BLOCK?
3) Mismo caso, proceso que solicito un F_WRITE/READ y llega un proceso nuevo, pero en este caso el proceso solicita hacer un F_OPEN. Nosotros la comunicación de Kernel/File System la manejamos con 1 solo thread, por lo tanto, el nuevo proceso quedaría a la espera de que termine el F_WRITE/READ y de una respuesta de esto antes de tomar una nueva solicitud. ¿Esto esta bien? ¿En este caso, el proceso nuevo va a BLOCK hasta que termine el F_WRITE/READ o queda esperando en EXEC?

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- El F_SEEK va a tener el valor al cual va a tener que apuntar el puntero, por lo que si les pasamos 150, van a apuntar al byte 150 del archivo, si les pasamos 0, es al byte 0 del archivo.

2.- Por desgracia, va a quedarse ese proceso en EXEC clavado esperando que termine el F_READ / F_WRITE.

3.- Esta perfecto que se quede esperando, ya que el FS atiente las peticiones de a 1 y es similar a la compactación, se queda en EXEC porque en la definición de F_OPEN, no pasan nada a bloqueado.

Saludos.-

**Comment by D-M-Gonzalez** [comment]
Perfecto gracias, si mi duda es si es el byte 150 del archivo, o el byte 150 del archivo de bloques, pero por lo que decis es del archivo.

Por otro lado, estamos agregando al FCB un parámetro que es puntero_archivo, el cual guarda el puntero del FSEEK. El problema es que realizamos la serialización de instrucciones con 3 parámetros, y para enviar una instrucción por ejemplo F_WRITE de kernel a FSYSTEM necesitaríamos 4 (dir física, puntero, nombre y tamaño), por lo que preferimos guardar el puntero en el FSYSTEM y que al recibir un F_WRITE desde kernel ( osea ya paso por CPU y se tradujo ) no necesite ese parámetro. Es válido? o no podemos agregar nada a los FCB?

**Comment by iago64** [comment]
Buenas! Cómo va?

El FCB no tiene que tener la info del puntero. El puntero es algo que lo tienen que guardar en la tabla de archivos abiertos y que cuando el Kernel le avise al FS que tiene que leer o escribir, ademas, le sume como parámetro el puntero.

Saludos.-
