### ISSUE TITLE
FS Truncar Archivo

### ISSUE THREAD

**Issue by AGanem** [sisoputnfrba/foro#3074]
Hola! Cómo va?
Tengo una duda al truncar el archivo específicamente al achicar el archivo. Qué valor le pongo o que punteros pongo al momento de "eliminar" los punteros a bloques de datos que sobran en el bloque de punteros. 
En la imagen serían los que están en rojo

![19befd2b-9a61-46b0-ac8f-4c1d9c11cb44](https://github.com/sisoputnfrba/foro/assets/17953894/427c2369-8410-449e-8596-7ba23aa94514)

Saludos

**Comment by irinaperezg** [comment]
Hola! Yo tengo una duda similar, especialmente en el caso de desasignar el puntero indirecto (en el caso de que el bloque de punteros quede vacio porque el tamaño total es de 1 bloque) ya que si le ponemos 0 podría ser una referencia al bloque numero 0, pero si quisiese que el valor -1 sea vacio entonces tendria que hacer que el tipo de los punteros sea int32_t en vez de uint32_t y no se si esta bien. Lo mismo en el caso de desasignar el puntero directo (en caso de que se pase un f_truncate con tamaño 0, lo cual no se si tenemos que contemplar)

**Comment by iago64** [comment]
Buenas! Cómo va?

En principio no tienen que hacer nada con esos punteros ya que esos bloques están marcados como libres en el bitmap (o deberían estarlo).
Lo importante es que se guíen por el tamaño del archivo (el cual solo contempla los bloques de datos).

Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas @AGanem @irinaperezg !
Les resolvió la duda la respuesta de @iago64 ? Se puede cerrar el issue?

**Comment by irinaperezg** [comment]
Holis por mi parte si :)

**Comment by AGanem** [comment]
Hola! De mi parte también. Muchas gracias!
