### ISSUE TITLE
Consulta CANT_SEGMENTOS

### ISSUE THREAD

**Issue by FrandelCampo** [sisoputnfrba/foro#3075]
Buenas buenas! Me surgio una duda sobre el valor del config de memoria CANT_SEGMENTOS. 
Nosotros la tabla de segmentos inicial de cada proceso la habíamos implementado como una t_list con un único nodo (el segmento 0). Y a medida que llega un CREATE_SEGMENT, lo agregamos a la tabla (list_add) validando antes que la tabla del respectivo proceso, tenga menos segmentos que config.CANT_SEGMENTOS (ademas de que haya espacio en memoria). viendo el issue #3033 entiendo que no se va a testear dicho caso en la entrega, pero no sabemos si debemos corregir nuestra lógica para que la tabla inicial ya tenga CANT_SEGMENTOS segmentos, y que CREATE_SEGMENT solo acceda al segmento del mismo index que id_segmento y le asigne los respectivos valores, o si no hace falta cambiar nada.
Gracias de antemano!
### 📔 Citas del enunciado/videos

>El módulo deberá crear las estructuras administrativas necesarias y enviar como respuesta la tabla de segmentos inicial del proceso. Esta tabla tendrá un tamaño fijo definido por archivo de configuración.

**Comment by iago64** [comment]
Buenas! Cómo va?

No hace falta que corrijan nada, siempre y cuando con un CANT_SEGMENTOS de 16 puedan tener en su tabla los segmentos 0, 4 y 12 por dar un ejemplo.

Saludos.-

**Comment by FrandelCampo** [comment]
Perfecto, saludos!
