### ISSUE TITLE
Problema al recibir el contexto de ejecucion en cpu

### ISSUE THREAD

**Issue by LucianoFoglia** [sisoputnfrba/foro#3076]
Buenas, el problema que tenemos es que al enviar el contexto de ejecucion del kernel al cpu nunca lo termina de recibir. Solo lo recibe al matar al kernel. Por lo que suponemos que estamos calculando mal los tamaños y el cpu se queda esperando. El problema es que probamos mandandole menos bytes del stream y sigue sin funcionar. 
Leimos la guia de serializacion y con los ejemplos mas la teoria tratamos de adaptarlo a nuestro caso pero tampoco nos funciono. Tambien probamos usando los subprogramas del TP0 y acomodarlos pero tampoco nos resulto.

### 📝 Código relevante

Como lo serializamos en kernel:
```
void serializar_cde(contexto_de_ejecucion cde){
	// Ver tamanios de los nodos de las listas
	Cde_serializado cde_serializado;

	cde_serializado.pid = cde.pid;
	cde_serializado.program_counter = cde.program_counter;

	int tam_de_1_nodo_instruccion = (sizeof(uint32_t)*2 + sizeof(uint8_t) + 15 + 15);

    cde_serializado.tam_lista_instrucciones = 
		tam_de_1_nodo_instruccion * list_size(cde.lista_de_instrucciones); 
	
	cde_serializado.lista_de_instrucciones = list_create();
	cde_serializado.lista_de_instrucciones = cde.lista_de_instrucciones;
	
    cde_serializado.registrosCpu = cde.registrosCpu; // tamanio fijo de 112 bytes
	
    cde_serializado.tam_tabla_segmentos = (sizeof(uint32_t)*3) * list_size(cde.tabla_segmentos);
    
	cde_serializado.tabla_segmentos = list_create();
	cde_serializado.tabla_segmentos = cde.tabla_segmentos;
    
    cde_serializado.estado = cde.estado;

	t_paquete* paquete = crear_paquete();

	int tam =
		cde_serializado.tam_lista_instrucciones + cde_serializado.tam_tabla_segmentos +
		112 + (sizeof(uint32_t) * 4) + sizeof(uint8_t);

	void* stream = malloc(tam);
	int offset = 0;
	
	memcpy(stream + offset, &cde_serializado.pid,sizeof(uint32_t));
	offset += sizeof(uint32_t);
	
	memcpy(stream + offset, &cde_serializado.program_counter,sizeof(uint32_t));
	offset += sizeof(uint32_t);

	// tam_lista_instrucciones esta en bytes
	memcpy(stream + offset, &cde_serializado.tam_lista_instrucciones,sizeof(uint32_t));
	offset += sizeof(uint32_t);
	

	for(int i=0; i < list_size(cde_serializado.lista_de_instrucciones); i++){
		memcpy(stream + offset, list_get(cde_serializado.lista_de_instrucciones,i),tam_de_1_nodo_instruccion);
		offset += tam_de_1_nodo_instruccion;
	}
	
	memcpy(stream + offset, &cde_serializado.registrosCpu, 112);
	offset += 112;

	// tam_tabla_segmentos esta en bytes
	memcpy(stream + offset, &cde_serializado.tam_tabla_segmentos,sizeof(uint32_t));
	offset += sizeof(uint32_t);
	
	memcpy(stream + offset, cde_serializado.tabla_segmentos, cde_serializado.tam_tabla_segmentos);
	offset += cde_serializado.tam_tabla_segmentos;
	
	memcpy(stream + offset, &cde_serializado.estado, sizeof(uint8_t));
	offset += sizeof(uint8_t);
	
	log_info("offset: %d, tam: %d", offset, tam);

	// Llenamos el paquete --------------------------------------------------------
	paquete->codigo_operacion = CONTEXTOEJEC; // Podriamos usar una constante por operación

	// Armamos el stream a enviar	

	void* a_enviar = malloc(paquete->buffer->size + sizeof(uint8_t) + sizeof(uint32_t));
	offset = 0;
	
	memcpy(a_enviar + offset, &(paquete->codigo_operacion), sizeof(uint8_t));
	offset += sizeof(uint8_t);

	memcpy(a_enviar + offset, &(paquete->buffer->size), sizeof(uint32_t));
	offset += sizeof(uint32_t);
	
	memcpy(a_enviar + offset, paquete->buffer->stream, paquete->buffer->size);

	// Por último enviamos
	send(socket_cpu, a_enviar, paquete->buffer->size + sizeof(uint8_t) + sizeof(uint32_t), 0);

	list_destroy(cde_serializado.tabla_segmentos);
	list_destroy(cde_serializado.lista_de_instrucciones);
	free(stream);
}
```

Como lo deserializamos en cpu:
```
void deserializar_cde(){		
	log_info(logger,"Entre a deserializar_cde");
	
	int op = recibir_operacion(kernel_fd);
	
	log_info(logger,"Recibi el codigo de operacion: %d", op);
	
	t_list* lista = recibir_paquete(kernel_fd);

	log_info(logger,"Recibi el paquete");
	
	void* stream_recibido = list_get(lista, 0);
	Cde_serializado* cde_recibido = malloc(sizeof(Cde_serializado)); //arreglar dsps el sizeof
	int offset = 0;

	memcpy(&(cde_recibido->pid), stream_recibido + offset, sizeof(uint32_t));
    offset += sizeof(uint32_t);
	
	memcpy(&(cde_recibido->program_counter), stream_recibido + offset, sizeof(uint32_t));
	offset += sizeof(uint32_t);

	memcpy(&cde_recibido->tam_lista_instrucciones, stream_recibido + offset, sizeof(uint32_t));
	offset += sizeof(uint32_t);
	
	cde_recibido->lista_de_instrucciones = list_create();
	
	int tam_de_1_nodo_instruccion = (sizeof(uint32_t)*2 + sizeof(uint8_t) + 15 + 15);
	int cant_nodos_instrucciones = cde_recibido->tam_lista_instrucciones / tam_de_1_nodo_instruccion;
	
	for(int i=0; i < cant_nodos_instrucciones; i++){
		Instruction* instruccion;
		memcpy(&instruccion, stream_recibido + offset ,tam_de_1_nodo_instruccion);
		list_add(cde_recibido->lista_de_instrucciones,instruccion);
		offset += tam_de_1_nodo_instruccion;
	}

	memcpy(&(cde_recibido->registrosCpu), stream_recibido + offset,  112);
	offset += 112;

	memcpy(&(cde_recibido->tam_tabla_segmentos), stream_recibido + offset, sizeof(uint32_t));
	offset += sizeof(uint32_t);

	cde_recibido->tabla_segmentos = list_create();
	
	int tam_de_1_segmento = sizeof(uint32_t)*3;
	int cant_nodos_segmento = cde_recibido->tam_tabla_segmentos / tam_de_1_segmento;
	
	for(int i=0; i < cant_nodos_segmento; i++){
		Segmento* segmento;
		memcpy(&segmento, stream_recibido + offset, tam_de_1_segmento);
		list_add(cde_recibido->lista_de_instrucciones, segmento);
		offset += tam_de_1_nodo_instruccion;
	}
	
	memcpy(&cde_recibido->estado, stream_recibido + offset, sizeof(uint8_t));
	offset += sizeof(uint8_t);


	log_info(logger,"Pid: %d", cde_recibido->estado);
	log_info(logger,"PC: %d", cde_recibido->program_counter);
	log_info(logger,"Estado: %d", cde_recibido->estado);

	log_info(logger,"Termine de deserializar.");   
}
```

```
t_list* recibir_paquete(int socket_cliente){
	int size;
	int desplazamiento = 0;
	void * buffer;
	t_list* valores = list_create();
	int tamanio;

	buffer = recibir_buffer(&size, socket_cliente);
	while(desplazamiento < size)
	{
		memcpy(&tamanio, buffer + desplazamiento, sizeof(int));
		desplazamiento+=sizeof(int);
		char* valor = malloc(tamanio);
		memcpy(valor, buffer+desplazamiento, tamanio);
		desplazamiento+=tamanio;
		list_add(valores, valor);
	}
	free(buffer);
	return valores;
}
```

@juanibencardino @corona6054 @Nicolucena

**Comment by RaniAgus** [comment]
¡Buenas! Primero, un par de preguntas para entender mejor la idea:
1- ¿Cuál sería el rol de tener un `Cde_serializado`? Por lo que parece, tiene los mismos atributos que `contexto_de_ejecucion` por lo que estaría sin serializar (veo que en varios lugares están pasando punteros al dato en vez de serializar el dato en sí)
2- Ojo que en varios lugares están teniendo memory leaks porque están creando una lista y luego pisando el puntero con el de la lista existente:

```c
cde_serializado.lista_de_instrucciones = list_create();
cde_serializado.lista_de_instrucciones = cde.lista_de_instrucciones;
```
```c
cde_serializado.tabla_segmentos = list_create();
cde_serializado.tabla_segmentos = cde.tabla_segmentos;
```
Pueden encontrar una explicación de la diferencia entre "pisar" y "rellenar" un puntero acá: https://github.com/sisoputnfrba/foro/issues/2224#issuecomment-882803512

3- También noto que para serializar la `tabla_segmentos` no están recorriendo la lista para serializar cada elemento, sino que solo están copiando un `t_list` y usando `cde_serializado.tam_tabla_segmentos` como tamaño:

```c
memcpy(stream + offset, cde_serializado.tabla_segmentos, cde_serializado.tam_tabla_segmentos);
```

Dicho esto, en general veo que la funciones para serializar y deserializar son bastante grandes, por lo que es bastante difícil debuggearlas. Si cursaron Paradigmas probablemente hayan visto la idea de "dividir y conquistar", es decir, separar un problema grande en pedacitos más chiquitos e irlos resolviendo de a poco para luego juntar las partes.

Un buen ejemplo sería crear una interfaz mínima para agregar o quitar cosas a un `t_buffer`:
```c
typedef struct {
    void *stream;
    uint32_t size;
    uint32_t offset;
}

// Crea un buffer vacío (size 0, offset 0)
t_buffer *buffer_create();

// Crea un buffer recibiendo el size y el stream desde una conexión activa
t_buffer *buffer_recv(int socket);

// Aumenta el size del buffer n bytes usando realloc() y agrega el src recibido al final
/*
  Ej:
  t_buffer *buffer = buffer_create();
  uint32_t pid = 23;

  buffer_write(buffer, &pid, sizeof(uint32_t));
*/
void buffer_write(t_buffer *buffer, void *src, int n);


// Lee n bytes del principio del buffer y los guarda en dest, desplazando su offset
/*
  Ej:
  t_buffer *buffer = buffer_recv(socket_cpu);

  uint32_t pid;
  buffer_read(buffer, &pid, sizeof(uint32_t));
*/
void buffer_read(t_buffer *buffer, void* dest, int n);

// Libera la memoria ocupada por un buffer
void buffer_destroy(t_buffer *buffer);
```

Luego, armar funciones para deserializar/deserializar los tipos más comunes:
```c
// Agrega un uint32_t al final del buffer
void buffer_write_uint32(t_buffer *buffer, uint32_t entero);

// Quita un uint32_t del principio del buffer
uint32_t buffer_read_uint32(t_buffer *buffer);

// Agrega un string al final del buffer, con un uint32_t al principio indicando su tamaño
void buffer_write_string(t_buffer *buffer, char* string);

// Quita un string del principio del buffer, leyendo primero el uint32_t que indica su tamaño
char *buffer_read_string(t_buffer *buffer);
```

Y, por último, usar las funciones de arriba para serializar y deserializar los structs que ustedes construyeron:
```c
void         buffer_write_instruction(t_buffer* buffer, Instruction *instruction);
Instruction *buffer_read_instruction(t_buffer *buffer);

void      buffer_write_segmento(t_buffer *buffer, Segmento *segmento);
Segmento *buffer_read_segmento(t_buffer *buffer);

void                  buffer_write_cde(t_buffer *buffer, contexto_de_ejecucion cde);
contexto_de_ejecucion buffer_read_cde(t_buffer *buffer);
```

De esta forma, van a notar que cuando les toque serializar y deserializar un `contexto_de_ejecucion`, les va a resultar mucho más sencillo y van a estar más seguros de que funciona porque solo van a estar usando funciones que ya saben que funcionan. 

También, si usan `realloc()` para cambiar el tamaño del buffer de forma dinámica, no necesitan sacar la calculadora para averiguar qué tamaño tiene que tener cada parte y sumarlas en un solo `malloc()`, solo escriben o leen lo que necesiten usando las funciones que ya crearon. En un contexto real no sería ideal ya que realocar tiene un alto costo en performance, pero en la materia no nos vamos a fijar en eso así que no se preocupen 😄 

Les recomiendo volver a encarar el problema por ese lado, entiendo que quizás les lleve un poco de tiempo al principio, pero una vez logren resolver lo más básico podrán reutilizar gran parte de lo que armaron para resolver lo más complejo.

Saludos

**Comment by LucianoFoglia** [comment]
Buenas, nos re sirvio lo que nos comentaste, muchas gracias. 
Te respondo lo que nos dijiste:
1- Si es verdad, no tiene mucho sentido ese struct. Igual el nombre estaria mal, seria cde_a_serializar.
2- okok, ahi vimos bien el issue ese y lo terminamos de entender.
3- Si eso no nos dimos cuenta y nos quedo de una version anterior. Nuestra idea seria copiar nodo por nodo en el stream y al principio de todos los nodos, poner la cantidad de nodos que tiene esa lista (similar a los strings).

Problemas que nos surgieron:
A) Ya estuvimos creando las funciones para serializar y deserializar. Pero estamos teniendo un problema al momento de leer un string. Cuando agregamos 2 strings en el stream (siendo el primero mas largo que el segundo), al leer el segundo string, nos agrega unos caracteres basura al final pero lo raro es que si esta leyendo bien el tamaño del string y despues hace un malloc de ese tamaño. Cuando lo hacemos al revez, (primero el chico y despues el grande) si funciona. 

B) Luego probamos enviando el stream entre dos modulos. Al recibir el stream y leer un string tambien agrega 2 bytes de basura por mas que los pongamos en cualquier orden. 


![image](https://github.com/sisoputnfrba/foro/assets/83732289/baad4595-b3b4-49bd-b3be-c514172ad2a6)

UTILS SERIALIZACION
```
// UINT32
void buffer_write_uint32(t_buffer* buffer, uint32_t entero){
	buffer->stream = realloc(buffer->stream, buffer->size + sizeof(uint32_t));
	
	memcpy(buffer->stream + buffer->size, &entero, sizeof(uint32_t));
	buffer->size += sizeof(uint32_t);
}

uint32_t buffer_read_uint32(t_buffer *buffer){
	uint32_t entero;
	
	memcpy(&entero, buffer->stream, sizeof(uint32_t));
	buffer->stream += sizeof(uint32_t);

	return entero;
}

//STRING
void buffer_write_string(t_buffer* buffer, char* cadena){
	uint32_t tam = 0;
	
	while(cadena[tam] != NULL)
		tam++;
	
	buffer_write_uint32(buffer,tam);
	
	buffer->stream = realloc(buffer->stream, buffer->size + tam);

	memcpy(buffer->stream + buffer->size, cadena , tam);
	buffer->size += tam;
}


char* buffer_read_string(t_buffer *buffer){
	uint32_t tam = buffer_read_uint32(buffer);
	char* cadena = malloc(tam);

	memcpy(cadena, buffer->stream, tam);
	buffer->stream += tam;

	return cadena;
}
```

**Comment by RaniAgus** [comment]
¡Buenas! Me alegra que les haya servido :)

Sobre la duda, por lo que veo en `buffer_read_string()` falta reservar memoria para el `'\0'` del final del string. Si reservan `tam + 1` y setean en `'\0'` el último caracter debería solucionarse.

También, un detalle: cuando usan los `buffer_read_<something>()` veo que están editando el valor de `buffer->stream`, con lo cual es probable que el `buffer_destroy()` les falle al intentar liberar un puntero que no es el resultado de un `malloc()`.

Para evitar esto pueden guardarse el offset en el struct y usar ese atributo en los read.

Saludos

**Comment by iago64** [comment]
@LucianoFoglia, Cómo va? te sirvió la ultima respuesta de Agus? Necesitas que aclaremos algo mas?

**Comment by LucianoFoglia** [comment]
buenas, lo de leer strings probamos eso y un par de cosas mas pero no nos funciono. Ibamos a preguntar mañana en las consultas y si lo terminabamos arreglando, avisabamos y cerrabamos el issue.
Lo otro, si, terminamos implementando lo del offset para el buffer.
Muchas gracias por toda la ayuda.

**Comment by LucianoFoglia** [comment]
Hola, ayer en el sabado de consultas ya pudimos arreglar el problema y ahora esta funcionando. Mil gracias por toda la ayuda.
