### ISSUE TITLE
Duda enunciado sobre F_WRITE confuso

### ISSUE THREAD

**Issue by Fcallero** [sisoputnfrba/foro#3077]
Buenas, estoy teniendo problemas para entender el F_WRITE en filesystem, entiendo que recibo del kernel, la dirección física de donde tengo que enviar a leer a memoria y además la cantidad de bytes a leer. Mi duda es en que bloque debe escribir lo que leyó memoria?  o como es esta parte porque en el enunciado de kernel no habla nada del puntero a escribir y en el de filesystem dice que se recibe, entonces me confundo todavía más.

**Comment by iago64** [comment]
Buenas! Cómo va?

El bloque lo tienen que calcular a partir de la posición del puntero del archivo (que es lo que cambian con F_SEEK)

Saludos.-

**Comment by Fcallero** [comment]
Ah ok, entonces ese puntero de dónde sale ? De la tabla global de archivos abiertos por proceso no? O me equivoco?

**Comment by iago64** [comment]
Buenas!

Efectivamente, en la tabla de archivos abiertos vas a tener la posición del puntero y de ahi vas a poder saber desde donde empezas a leer o escribir en el archivo.

Saludos.-

**Comment by Fcallero** [comment]
perfecto, muchas gracias.
