### ISSUE TITLE
Duda logs obligatorios mov_in y mov_out en memoria

### ISSUE THREAD

**Issue by lucasdeferrari** [sisoputnfrba/foro#3078]
Buenas noches, tengo una duda con los logs obligatorios de mov_in y mov_out en memoria:

`Acceso a espacio de usuario: “PID: <PID> - Acción: <LEER / ESCRIBIR> - Dirección física: <DIRECCIÓN_FÍSICA> - Tamaño: <TAMAÑO> - Origen: <CPU / FS>”`

El PID no es necesario para hacer el mov_in ni mov_out en la memoria, se lo deberiamos pasar solamente para que pueda completar ese log obligatorio?

Desde ya, muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

Si, es necesario que le pasen ese parámetro, si no, como vamos a saber quien esta haciendo que pedido en que momento 😉 

Saludos.-

**Comment by lucasdeferrari** [comment]
Genial gracias, otra pregunta mas. El tamaño que nos piden en ese log sería el tamaño del registro que quiere leer/escribir no?

**Comment by iago64** [comment]
Buenas!

Es el tamaño de lo que leen / escriben. Si son los registros de CPU si van a 4, 8 o 16, ahora del FS depende de lo que venga en las instrucciones de F_READ o F_WRITE.

Saludos.-

**Comment by iago64** [comment]
Buenas! Cómo va?

@lucasdeferrari te sirvieron las respuestas? Necesitas que veamos algo más?

Saludos.-

**Comment by lucasdeferrari** [comment]
Hola si, me resolvió la duda. Mil disculpas me olvidé de cerrar el issue
