### ISSUE TITLE
Duda con f truncate 

### ISSUE THREAD

**Issue by fmarsico8** [sisoputnfrba/foro#3080]
Hola me surgió una duda luego de leer el issue #3074 .  Al leer que al reemover bloques del puntero indirecto únicamente hay que marcarlos como libres en el bitmap y no borrarlos del archivo de bloques, nos surgió la duda de como calcular el offset, ya que nos habíamos imaginado algo como ver que byte no tenia nada escrito, aunque ahora con esto la cosa cambia y no sabemos como deberíamos de calcular el offset. 

Otra duda es si debemos de considerar el caso que se pueda truncar el tamaño del archivo a <= 64, ya que de ser así no se necesitaría el puntero indirecto.

**Comment by iago64** [comment]
Buenas! Cómo va?

Respecto al truncado, lo que dijimos es que no hace falta borrar los datos del bloque de punteros, que con marcarlos como libres les debería alcanzar ya que uds en el FCB también tienen el tamaño en bytes del archivo y con eso podrían saber rápidamente hasta que bloque ocupan.

El tema de truncar a un tamaño menor a un bloque, es decir, que el tamaño sea mayor a 0 y menor que el tamaño de un bloque puede pasar y ahi pueden simplemente no desasignar el bloque de punteros (puntero indirecto) y tenerlo ahi por si el archivo necesita crecer a futuro, sinceramente no definimos un comportamiento para ese punto ya que no nos cambia el fin de las pruebas lo que decidan hacer.

Saludos.-

**Comment by fmarsico8** [comment]
Ahhh perfecto, muchas gracias! Ya me quedo más claro
