### ISSUE TITLE
Duda con tabla global de archivos abiertos 

### ISSUE THREAD

**Issue by gutti-mg** [sisoputnfrba/foro#3081]
Buenass, nos surgieron algunas dudas al plantear el manejo de archivos en kernel.
1. Definimos la tabla de archivos abiertos como un t_list que en cada entrada tiene los siguientes campos:
```
typedef struct
{
	char* nombreArchivo;
	uint32_t puntero;
	uint32_t tamanioArchivo;
	t_list *lista_block_archivo;
	pthread_mutex_t mutex_lista_block_archivo;
}t_entradaTGAA;
```
y tambien definimos la tabla de archivos abiertos por proceso de la siguiente manera:
```
typedef struct
{
	char* nombreArchivo;
	uint32_t puntero;
	uint32_t tamanioArchivo;
}t_entradaTAAP;
```

a. Tenemos que guardar en la tabla global de archivos abiertos el puntero a la posición del archivo? Esto implicaria que al hacer un F_SEEK deberiamos actualizar en las dos tablas (tabla global de archivos abiertos y en la tabla de archivos abiertos por proceso)

b. Otro planteo que estamos pensando es modificar como tenemos definida la tabla de archivos abiertos por proceso para que se guarde el nombre de archivo y un puntero a la estructura correspondiente a ese archivo en la tabla general de archivos abiertos, asi cuando se hace un F_SEEK se actualiza el puntero en todos los procesos que lo tengan abierto.

2. El filesystem tiene un tiempo de retardo para acceder a los bloques. ¿Eso significa que kernel deberia quedarse esperando a que filesystem le responda despues de haber esperado el retardo correspondiente?

3. Cuando se refiere "y bloqueará" en el enunciado:  
>F_TRUNCATE: Esta función solicitará al módulo File System que actualice el tamaño del archivo al nuevo tamaño pasado por parámetro **y bloqueará al proceso hasta que el File System informe de la finalización de la operación**.

Eso significa que el proceso entrará en la lista de procesos bloqueados y comenzara a ejecutar uno nuevo o significa que kernel se tendra que quedar esperando hasta la finalizacion de la operacion?
El mismo comportamiento tienen las instrucciones F_WRITE y F_READ, por lo tanto se deberia aplicar la misma lógica?

Saludos.-

**Comment by iago64** [comment]
Buenas! Cómo va?

Gracias por poner los números de las preguntas, ayudan a que sea mas simple de seguir ☺️ 

1.- El puntero del archivo tiene que estar en la tabla de archivos abiertos por proceso, cito al enunciado:

> El PCB será la estructura base que utilizaremos dentro del Kernel para administrar los procesos lanzados por medio de las consolas. [...]
**Tabla de archivos abiertos**: Contendrá la lista de archivos abiertos del proceso con la posición del puntero de cada uno de ellos.

Mientras que la tabla global de archivos abiertos dice lo siguiente:

> Para la gestión de los archivos, el Kernel deberá implementar una **tabla global de archivos abiertos**, a fin de poder gestionar los mismos como si fueran un recurso de una única instancia. Cada archivo podrá estar abierto por solo un proceso a la vez, por lo que se deberá implementar **locks exclusivos y obligatorios sobre cada archivo**.

Dicho lo anterior, con que muevan el puntero del struct de la global a la del proceso les alcanza.


2.- El Kernel siempre va a esperar la respuesta del FS, la idea del retardo es que apliquen ese retardo en cada acceso a un bloque en el FS, ya sea para escribirlo o leerlo (aplica tambien para el bloque de punteros)

3.- Efectivamente F_TRUNCATE tiene un comportamiento similar a F_READ y F_WRITE respecto a lo que pasa con el proceso en el Kernel.

Saludos.-

**Comment by gutti-mg** [comment]
Buenísimo, muchas gracias!
