### ISSUE TITLE
Duda sobre las ultimas 2 funciones de FS

### ISSUE THREAD

**Issue by matigol48** [sisoputnfrba/foro#3084]
En el enunciado dice que lee la informacion de los bloques en un puntero determinado, pero de que tipo es la informacion que esta leyendo?

La otra duda es que la direccion fisica llega a FS desde el kernel por parametro o se crea dentro de FS para mandarselo a memoria
### 📔 Citas del enunciado/videos

Leer Archivo
Esta operación deberá leer la información correspondiente de los bloques a partir del puntero y el tamaño recibidos. Esta información se deberá enviar a la Memoria para ser escrita a partir de la dirección física recibida por parámetro y esperar su finalización para poder confirmar el éxito de la operación al Kernel.
Escribir Archivo
Se deberá solicitar a la Memoria la información que se encuentra a partir de la dirección física y escribirlo en los bloques correspondientes del archivo a partir del puntero recibido.

**Comment by iago64** [comment]
Buenas! Cómo va?

El tipo de información no les interesa o mejor dicho, no les tiene que interesar, ya que uds mueven una cantidad de bytes fija (algo similar a lo que hace memcpy, que uds le dicen origen, destino y tamaño).

La dirección física la tiene que calcular la CPU en la MMU y después se la pasa al kernel y este al FS.

Saludos.-

**Comment by iago64** [comment]
@matigol48 Cómo va?

Te quedo alguna duda respecto a cómo es el pasaje de mensajes con la dirección física?

Saludos.-

**Comment by matigol48** [comment]
si, en la funcion de leer y en la de escribir dice que le llega un puntero como parametro pero en que momento decidimos cual es el puntero para mandarle porque desde kernel llega el nombre de un archivo y no dice en ningun lugar a que puntero mandarle

tambien queria saber si la informacion que llega desde memoria hacia FS tiene un tamanio limitado como si la info es para solo un bloque o puede guardarse en varios bloques

**Comment by iago64** [comment]
Buenas! Cómo va?

Respecto a la duda del puntero, es el puntero que tienen que tener en la tabla de archivos abiertos del proceso.

Respecto al tamaño de lo que se manda entre memoria y FS, es uno de los parámetros de F_READ o F_WRITE, no tenemos ninguna restricción en el enunciado.

Saludos.-
