### ISSUE TITLE
Problema con memcpy

### ISSUE THREAD

**Issue by fmarsico8** [sisoputnfrba/foro#3085]
Hola! estamos teniendo un problema con f truncate a la hora de que el tamaño nuevo sea menor al tamaño actual, ya que cuando hacemos memcopy para buscar el bloque a eliminar dentro del puntero indirecto, ese valor nos devuelve 0 siempre y no entendemos por que, primero pensamos que era un tema con la sincronización y usamos msync pero eso no lo soluciono, cuando agrandamos el tamaño funciona bien. La lógica esta bien xq además lo debuggeamos y todas las demás variables nos dan bien el unico que trae problema es la variable copia que siempre que pasa por el memcopy se pone en 0. 

### 📝 Código relevante
```
Función cuando el nuevo valor de bloques es mayor al actual 
	int puntero_indirecto = config_get_int_value(config_path, "PUNTERO_INDIRECTO");
	memcpy(archivoDeBloques + (puntero_indirecto*block_size + (offset + 1)), &j, sizeof(uint32_t));
	msync(archivoDeBloques,1,MS_SYNC);
	memcpy(&copia,archivoDeBloques + (puntero_indirecto*block_size + (offset + 1)),sizeof(uint32_t));
	offset++;
	printf("EL valor apuantado por el puntero indirecto es %u\n", copia);
	bitarray_set_bit(bitmap, j);
	break;
```
```
Función cuando el nuevo valor de bloques es menor al actual 

	uint32_t copia;

	int puntero_indirecto = config_get_int_value(config_path, "PUNTERO_INDIRECTO");
	memcpy(&copia,archivoDeBloques + (puntero_indirecto*block_size + (offset)),sizeof(uint32_t));
	offset--;
	printf("EL valor eliminado del puntero indirecto es %u\n", copia);
	bitarray_clean_bit(bitmap,copia);
```

**Comment by iago64** [comment]
Buenas! Cómo va?

Solo para ubicarme un poco mas en cuanto al código, de que tipo es la variable offset? Porque no nos olvidemos que uds tienen que moverse de a 4 bytes o el sizeof(uint32_t) y en el código que funciona bien hacen `offset++` y despues le hacen `offset--` en el que falla.

Una opción mas que pueden hacer es ver como va cambiando el archivo usando `hexdump` sobre el archivo de bloques, esto les va a permitir ver cuando graban el bloque como se modifica. 
Para hacer la prueba facil pueden usar un tamaño de bloque muy chico (ej: 16 bytes) y pocos bloques (ej: 10) y eso les va a permitir que si es el primer archivo deberían estar entre los primeros 3 bloques del archivo la info cosa de que no tengan que scrollear mucho.

Saludos.-

**Comment by fmarsico8** [comment]
Hola, estuvimos probando lo del hexdump como nos dijiste, cambiamos el tamaño del bloque y pusimos 10 bloques, y al usar el comando vimos que nos lo esta escribiendo mal creo, ya que primero nunca nos escribe sobre el primer byte del bloque, y ademas como que los pone invertidos los bloques, 

Nuestra idea cuando pensamos el f truncate al agrandar o achicar archivos era la de iterar con un for la cantidad de bloques a agregar o la cantidad de bloques eliminar, y luego en el caso de agregar buscabamos con otro for en el bitmap un bloque que no este ocupado y escribiamos en el puntero indirecto el valor del segundo for.
Y el offset lo tomabamos como la cantidad de bloques actuales - 1 ( debido al puntero directo) 

El offset en todos los casos era de tipo uint32_t 
```
for(int i=0; i < bloquesAAgregar; i++){

	for(int j=0; j < bitarray_get_max_bit(bitmap); j++){

		if(!bitarray_test_bit(bitmap, j)){
			uint32_t copia;

			int puntero_indirecto = config_get_int_value(config_path, "PUNTERO_INDIRECTO");
			memcpy(archivoDeBloques + (puntero_indirecto*block_size + (offset + 1)), &j, sizeof(uint32_t));
                        msync(archivoDeBloques, (puntero_indirecto*block_size + (offset + 1)),sizeof(uint32_t));
			memcpy(&copia,archivoDeBloques + (puntero_indirecto*block_size + (offset + 1)),sizeof(uint32_t));
			offset++;
			printf("EL valor apuantado por el puntero indirecto es %u\n", copia);
			bitarray_set_bit(bitmap, j);
			break;
		}
	}
}
```
Una duda más el hacer msync dsp de cada cambio en el archivo de bloques estaría bien? los parámetros que le estamos pasando están bien?
Asi es como nos aparecía el archivo de bloques: 

![](https://cdn.discordapp.com/attachments/1079947279999455382/1124342697155629056/IMG-20230628-WA0064.jpg)

**Comment by iago64** [comment]
Buenas! Cómo va?

Ahora si tiene mas sentido, el offset si lo tienen definido como uint32_t y le hacen ++ lo único que van a hacer es que se corra 1 byte en lugar de 4... por eso no les dan las cuentas ni a gancho, esto lo hubieran visto rápidamente debugueado su código, les recomiendo que revisen la [guía de debug](https://docs.utnso.com.ar/guias/herramientas/debugger) así ganan agilidad e independencia.

Respecto al `msync()`, la función lo que busca es forzar la persistencia de los cambios en el archivo que van a ocurrir de todas formas y que posiblemente sea sumamente rápido porque no es que el kernel de la vm va a estar bajo bombardeo de requests, de todas formas si quieren usarlo porque les da seguridad, les recomiendo que revisen el [man de `msync()`](https://man7.org/linux/man-pages/man2/msync.2.html).

Saludos.-

**Comment by fmarsico8** [comment]
Buenas! Creo que ya nos esta andando pero tenemos una ultima duda 
Entendemos que un bloque de 64 bytes es de la linea 40 a la linea 70, ahora nuestra duda viene de si el bloque tendria que verse como la linea 40 o la 50, es decir uno al lado del otro o uno cada 4 bytes (por el uint32_t)
![](https://cdn.discordapp.com/attachments/1079947279999455382/1124775832150347846/image.png)

**Comment by iago64** [comment]
Buenas! Cómo va?

Tengan en cuenta que cada par de octetos (00) es 1 byte, con lo cual cada línea del `hexdump` son 16 bytes y a partir de la línea 40, uds tendrían el segundo bloque del archivo de bloques.
Respecto a cómo se ven los datos, la línea 00000040 tiene sentido porque tienen los bloques 2, 3, 4 y 5, lo que hay en la línea 00000050, puede ser basura del archivo o algo de una prueba anterior que está mal, por las dudas, prueben de agregarle más bloques y fíjense si pisan esos datos.

Saludos.-

**Comment by fmarsico8** [comment]
Perfecto todo mucho más claro, muchas gracias!
