### ISSUE TITLE
Chars y el caracter `/0`

### ISSUE THREAD

**Issue by Laureano11** [sisoputnfrba/foro#3086]
Hola, cuando estoy utilizando los chars, tanto para guardar en memoria, como para guardar en los registros de CPU, este mismo me esta ocupando un  byte de mas por el hecho de que contiene el `/0` al final de cada char. 
Entonces si yo lo copio tanto a registro como a memoria utilizando `memcpy()` (en el ultimo parametro colocando el largo del char) luego a la hora de manipularlo como usar un ```strlen()``` con ese char, esta funcion no funciona correctamente al haberle "cortado" el `/0`, y asi tambien sucede con otras funciones propias de C para manipular los strings. Tambien por ejemplo si quiero escribir el char "Hola" en la memoria, este vendria a ocupar 5 bytes en lugar de 4, por el mismo motivo. Como encaro este problema? En el sentido de que hago agrando el tamaño de los registros? y lo mismo pasaria en memoria cuando guarde un string de N longitud me va a ocupar N+1 bytes?

**Comment by FrandelCampo** [comment]
Buenas, me sumo a la consulta. Entiendo que en CPU la data se guarda en los registros sin el \0, pero en filesystem también nos vendría bien contar con el carácter nulo para poder solucionar el tema de leer la data de un bloque que tenga fragmentación interna (el ultimo a leer). sds

**Comment by iago64** [comment]
Buenas! Cómo va?

Justamente el problema que tienen es que estan usando `strlen()`, la idea de este TP de darles tamaños fijos en los registros es que puedan hacer `memcpy()` de los registros sin preocuparse por tener el `'\0'` que les delimita el string.

Dicho lo anterior, si el problema viene de que uds los quieren imprimir los valores del registro de la CPU, ahi si, no les va a quedar otra que agregárselo justo antes de imprimir los valores (por ejemplo teniendo una variable con ese byte extra a la hora de imprimir), pero eso les sirve nada mas que para imprimir, para todo lo demás, tienen que usar los tamaños **fijos** de los registros o en su defecto entre FS y Memoria los tamaños pasados en las operaciones de F_READ y F_WRITE, ya que las pruebas las vamos a calcular en base a eso.


@FrandelCampo el problema de la fragmentación interna no les tiene que afectar porque F_READ y F_WRITE van a tener el tamaño a leer / escribir, entonces con eso uds pueden delimitar fácilmente hasta donde tienen que "recorrer" del archivo.

Saludos.-

**Comment by iago64** [comment]
Buenas! Cómo va?

Quedaron resueltas las dudas?

Saludos.-
