### ISSUE TITLE
Duda sobre operacion entre memoria y fileSystem desde el kernel.

### ISSUE THREAD

**Issue by FacundoPiaggio** [sisoputnfrba/foro#3087]
Buenas!

A la hora de solicitar una compactacion desde el kernel, el enunciado dice esto:

"Al momento de recibir de la Memoria el mensaje que indica que se dispondría del espacio solicitado
post compactación, el Kernel deberá primero validar que no se estén ejecutando operaciones entre
el File System y la Memoria (F_READ y F_WRITE)."
"En caso de que se tengan operaciones del File System en curso, el Kernel deberá esperar la
finalización de las mismas para luego proceder a solicitar la compactación a la Memoria."

La duda en concreto es, si le corresponde al kernel saber si esta habiendo una operacion en curso, o si el kernel tiene que preguntarle a la memoria para saber si esta respondiendo una solicitud del filesystem.

Saludos y muchas gracias.

**Comment by LeandroCarbajales** [comment]
Buenas!
El kernel debería saberlo ya que la operación puede estar en curso y el FS aun no haberle solicitado nada a Memoria.

**Comment by FacundoPiaggio** [comment]
Excelente lean, clarisimo. Muchas gracias!
