### ISSUE TITLE
Valores dentro de lista de recursos asignados de un PCB se pisan y no sabemos por qué

### ISSUE THREAD

**Issue by a-sandoval** [sisoputnfrba/foro#3088]
Buenas, cómo va? Con mi grupo nos dimos cuenta de que no estábamos realizando el segundo punto mencionado en el issue #3042 y nuestra forma de corregir eso fue que, cada vez que haga un wait válido, añada a una lista de recursos asignados dentro del PCB el nombre del recurso. Luego, cuando realiza signal no sólo aumentará la cantidad de instancias del recurso sino también lo borrará de dicha lista. 

El problema es que, en algún punto entre la syscall wait y la syscall signal los nombres de los recursos no se mantienen, sino que se pisan y contienen basura (cuando la lista de recursos asignados no es modificada en ningún momento ni enviada como parte del contexto de ejecución de la CPU), por lo que al finalizar un proceso (incluso de forma exitosa) se loggea el fin del proceso con motivo de éxito, pero luego también de error. 

### 📝 Código relevante

```
void wait_s(t_pcb *proceso, char **parametros){

    char *recurso = parametros[0];

    else {
        list_add(proceso->recursosAsignados, (void*)recurso);
        volverACPU(proceso);
    }
}

void signal_s(t_pcb *proceso, char **parametros){

    char *recurso = parametros[0];

    int indexRecurso = indiceRecurso(recurso);

    if (indexRecurso == -1){
        exit_s(proceso, &segFault); 
        return;
    }

    int instancRecurso = instanciasRecursos[indexRecurso];
    instancRecurso++;
    
    eliminarRecursoLista(proceso->recursosAsignados,recurso); 


}

void eliminarRecursoLista(t_list* recursos, char* recurso){
    int cantRecursos = list_size(recursos);
    
    int i;
    
    for(i=0;i<cantRecursos;i++){
        
        if(!strcmp((char*)list_get(recursos,i), recurso)){
            list_remove(recursos,i); 
            
        }
    }
}

```
Omití varias partes del código que no eran necesarias para esto. Al debuggear encontramos que, como recursosAsignados para el momento de realizar signal contiene valores que no son (dependiendo de la ejecución encontramos, por ejemplo, CREATE_SEGMENT 1 128), no logra encontrar el recurso y, por lo tanto, no lo puede eliminar. 

Estuvimos utilizando el ejemplo del enunciado, en el cual hace WAIT de disco y luego SIGNAL de disco, por lo que no entendemos siquiera con qué error nos estamos encontrando. 

Gracias desde ya!

**Comment by iago64** [comment]
Buenas! Cómo va?

Los cortes de código mucho no ayudan porque por ejemplo nos queda un `else` perdido sin el `if` que lo "origina", pero más allá de eso, si están pisando memoria puede venir por varios lados y en ese caso, lo más importante es que puedan correr el Kernel con Valgrind y se fijen todos los `Invalid read` e `Invalid Write` ya que en alguno de esos va a estar la respuesta a en que linea están haciendo un `memcpy()` con un tamaño incorrecto y que se les está pasando del fragmento correspondiente.

Si se les dificulta mucho seguir el output del valgrind, nos lo pueden subir aca **en un archivo de texto** y nosotros lo vemos.

Saludos.-

**Comment by a-sandoval** [comment]
Sí, efectivamente era porque el nombre del recurso se liberaba y no se estaba haciendo un string_duplicate al copiarlo. 
Gracias :) !Cierro el issue.
