### ISSUE TITLE
Consulta instrucciones CUSTOM

### ISSUE THREAD

**Issue by D-M-Gonzalez** [sisoputnfrba/foro#3089]
Buenas!

Hago una consulta, que creo no hay drama pero por las dudas para tenerlo preparado.
Nosostros estamos agregando algunas instrucciones propias para ayudarnos en el desarrollo, para debuguear, etc.
Por ej, tenemos PRINT_MEMORY_STATE que imprime las tablas de segmentos tanto en Kernel como en Memoria, tenemos lo mismo para File System, tenemos F_DELETE, para que borre un archivo y no tener que andar borrando a mano ( y cambiando los bits, etc ).
Hay algun problema que estas cosas lleguen a la entrega final?

**Comment by iago64** [comment]
Buenas! Cómo va?

Mientras que lo que se pidió este y cumpla los requisitos y las restricciones, lo que tengan de extra no hay problema.

Saludos.-
