### ISSUE TITLE
Duda sobre CANT_SEGMENTOS

### ISSUE THREAD

**Issue by D-M-Gonzalez** [sisoputnfrba/foro#3090]
Buenas!

Comenzamos las pruebas mas intensivas del módulo memoria y re-leyendo el enunciado nos dimos cuenta que se nos paso una parte:

El módulo deberá crear las estructuras administrativas necesarias y enviar como respuesta la tabla de segmentos inicial del proceso. Esta tabla tendrá un tamaño fijo definido por archivo de configuración.

CANT_SEGMENTOS del config.

Nosotros lo resolvimos de una manera que quisiera validar que sea correcta.
La tabla de segmentos es global en el módulo MEMORIA. El módulo Kernel luego de realizar un CREATE o DELETE realiza una solicitud_tabla_segmentos() para actualizar su propia tabla global de segmentos y sincronizarla con memoria.
Cada proceso por su parte, tiene un puntero que apunta al puntero de esta tabla global, por lo que al actualizar la global, el proceso ya ve los cambios en su tabla.
Los diferentes procesos pueden solicitar un CREATE con un ID libre, ya que no asociamos el ID a un orden específico.
Por ejemplo, teniendo el PID 1, PID 3 y PID 4 en ejecución, el PID 1 podría solicitar crear los segmentos 3 7 8, el PID 3 el 1 2 4 5, y el PID 4 el resto, siempre y cuando se cumpla que los ID de segmento esten libres.

Ahora, la duda viene aca. Cuando se inicia un proceso, el kernel se comunica con memoria, crea una nueva tabla de segmentos para este proceso y le asigna el PID y ya le añade el segmento 0 ( que es global y compartido entre todos ).
Despues a medida que el proceso hace CREATE_SEGMENT, la memoria los añade a la tabla de segmentos con el PID del proceso, el Kernel solicita la tabla y se actualiza todo en base a la de memoria.

La verdad que se nos re paso esto ( simplificaba bastante todo jaja, nos quedo re complejo ) nosotros lo pensamos como que cualquier proceso podría crear un segmento con el ID que se le antoje.
Como esta armado, podríamos cumplir con la consigna solamente verificando que el ID_SEGMENTO < CANT_SEGMENTOS, ya que como los ID no se pueden repetir, si el CANT_SEGMENTOS = 16, el máximo va a ser siempre 15 ( el segmento 0 ya esta creado ), pero seguiríamos enviando solamente el segmento 0 al iniciar el proceso.
¿Es válido, o tenemos que cambiar todo?

**Comment by iago64** [comment]
Buenas! Cómo va?

No se si me perdí en algo de la explicación, pero a priori la cantidad maxima de segmentos aplica a CADA proceso y por lo que entiendo no estarían aceptando que por ejemplo se de que el PID 1 cree los segmentos 1, 2 y 3 y que despues el PID 2 intente crear el segmento 1 por ejemplo, es asi?

Saludos.-

**Comment by D-M-Gonzalez** [comment]
Claro, no puede suceder, como tampoco puede suceder que se cree un segmento con un ID mayor a X número.
Entonces el CANT_SEGMENTOS no es total? Osea que si CANT_SEGMENTOS es 4, el PID 1 puede tener el 1 2 3, y el PID 2 podría tener el 4 5 6?

**Comment by D-M-Gonzalez** [comment]
Ok perfecto, gracias por la aclaración!
