### ISSUE TITLE
implementación del F_TRUNCATE del lado del filesystem

### ISSUE THREAD

**Issue by Fcallero** [sisoputnfrba/foro#3091]
Buenas, como va? tenemos un problemita para implementar el F_TRUNCATE de filesystem. Supongamos que tengo que agregar 5 bloques nuevos al archivo, cuantos punteros directos y  cuantos indirectos debería agregar? osea hasta cuantos punteros directos podemos tener? porque puedo agregar todos punteros directos, como sea necesario y no usar nunca los punteros indirectos.

**Comment by RaniAgus** [comment]
¡Buenas! Como se muestra en el ejemplo del enunciado, en nuestro FS cada archivo puede contener solamente un puntero directo y uno indirecto, por lo que si necesitan agregar 5 bloques, el primero estaría en el puntero directo y los otros 4 en el bloque apuntado por el puntero indirecto:
```env
NOMBRE_ARCHIVO=Notas1erParcialK9999
TAMANIO_ARCHIVO=256
PUNTERO_DIRECTO=12
PUNTERO_INDIRECTO=45
```
En un esquema real de FS tipo Unix (como el EXT que ven en la teoría) el tamaño de un FCB es estático. Van a ver que cuentan con más punteros directos (e indirectos simples, dobles y triples), pero esta cantidad siempre es fija porque en un FS real no sería conveniente ir reservando espacio para redimensionar cada FCB a medida que se van necesitando punteros.

Saludos

**Comment by Fcallero** [comment]
Ahh ok, lo había entendido mal, ahi me quedó más claro. Bueno y otra consulta, en el enunciado, modulo File System, en el lineamiento de implementación, dice: "Luego de establecer la comunicación con la Memoria, el módulo File System deberá levantar el bitmap de bloques y recorrer el directorio de FCBs para crear las estructuras administrativas que le permita administrar los archivos", esto significa que debemos al inicio hacer un fopen a todos los archivos del fcb que encontremos en el path para crear el t_fcb ? o lo podemos hacer a demanda en abrir archivo ?

**Comment by RaniAgus** [comment]
Cualquiera de las dos formas es válida :)

**Comment by Fcallero** [comment]
Perfecto, muchas gracias.
