### ISSUE TITLE
Duda sobre el bloque de punteros

### ISSUE THREAD

**Issue by franco-magne** [sisoputnfrba/foro#3092]
Buenas, cómo va

Me surgió la duda de si el puntero directo e indirecto pertenecen al bloque de punteros. Creería que el puntero directo no, pero no estoy seguro si el puntero indirecto es el primer bloque del bloque de punteros o si directamente tampoco está incluido. Siendo así, por ejemplo, un archivo que necesita 8 bloques solamente tendría 6 bloques contenidos en el bloque de punteros, ¿no? Hasta el momento tenía a ambos punteros en la lista de bloques del FCB, pero haciendo una función para recuperar los bloques me di cuenta de esto.

**Comment by franco-magne** [comment]
Se entendió. ¡Gracias, Lean!

Me surgió otra duda algo relacionada. Dado este FCB:

NOMBRE_ARCHIVO=NotasSO
TAMANIO_ARCHIVO=512
PUNTERO_DIRECTO=16
PUNTERO_INDIRECTO=17

Al momento de hacer el truncate, yo marco los bloques necesarios en el bitmap como ocupados, pero hasta ahora nada con el archivo de bloques. Si entiendo bien, debería posicionarme en el bloque 17 y "escribir" en él las posiciones que se encuentran en el bloque de punteros, incluido el puntero indirecto. ¿Es así?

Y aprovecho para otra duda, pero sobre la creación de archivos. ¿Es correcto asumir que si me llega un **F_CREATE** como respuesta al F_OPEN fallido después yo "abra" el archivo o tengo que volver a recibir un F_OPEN y que en esta ocasión sí se pueda abrir? Viendo lo que hice vi que asumí lo primero, pero quería corroborar si es está bien.

**Comment by LeandroCarbajales** [comment]
> Al momento de hacer el truncate, yo marco los bloques necesarios en el bitmap como ocupados, pero hasta ahora nada con el archivo de bloques. Si entiendo bien, debería posicionarme en el bloque 17 y "escribir" en él las posiciones que se encuentran en el bloque de punteros, incluido el puntero indirecto. ¿Es así?

Claro, deberías escribir el bloque de punteros con los punteros correspondientes a los bloques de datos que asignaste, sino cómo sabrías luego cuáles asignaste? :)
El puntero indirecto ya está persistido en el FCB, no tendría sentido tenerlo en el mismo bloque de punteros al que referencia.

> Y aprovecho para otra duda, pero sobre la creación de archivos. ¿Es correcto asumir que si me llega un F_CREATE como respuesta al F_OPEN fallido después yo "abra" el archivo o tengo que volver a recibir un F_OPEN y que en esta ocasión sí se pueda abrir? Viendo lo que hice vi que asumí lo primero, pero quería corroborar si es está bien.

Es correcto, en este TP un archivo se crea únicamente como consecuencia de querer abrirlo, luego la comunicación entre FS y Kernel queda a discreción del equipo para que funcione de esa manera.

**Comment by franco-magne** [comment]
Perfecto, todo claro. Gracias por la ayuda
