### ISSUE TITLE
Dudas sobre recursos y archivos

### ISSUE THREAD

**Issue by gabriel1816** [sisoputnfrba/foro#3095]
Hola tengo una duda respecto al manejo de recursos, ya que el enunciado pide "Para las operaciones de WAIT y SIGNAL donde el recurso no exista, se deberá enviar el proceso a EXIT", mi duda es si manejamos a los archivos como recursos, se va a testear que se haga un WAIT pasando por parámetro el nombre de un archivo?

**Comment by LeandroCarbajales** [comment]
Los archivos no son recursos a los cuales se les haga WAIT y SIGNAL. El concepto de ver al archivo como un recurso de una única instancia afectará solamente a las instrucciones F_OPEN y F_CLOSE para simular el concepto de lock exclusivo obligatorio. Internamente por supuesto pueden reutilizar las estructuras y lógica del wait y signal sobre un recurso para implementar el mismo comportamiento en f_open y f_close por el tema de tener una cola de bloqueados por cada uno por ejemplo.
Queda clara la idea?
Saludos!
        Lean

**Comment by gabriel1816** [comment]
siii graciass
