### ISSUE TITLE
Duda memoria CREATE_SEGMENT

### ISSUE THREAD

**Issue by ezequielmalfonso** [sisoputnfrba/foro#3096]
Buenas, tenemos una duda en el momento del CREATE_SEGMENT  en el caso de cuando no tiene huecos continuos, cito:
>En caso de contar con el espacio necesario pero el mismo se encuentre en diferentes huecos, se deberá informar al Kernel que debe solicitar una compactación previa a crear el segmento.

La memoria le dice al Kernel que solicite compactación, cuando finaliza la misma, tiene que volver a pedir la creación del segmento por la que se genero la compactación o la memoria lo crea de una al segmento o el kernel lo tiene que volver a solicitar?

Hay alguna forma de comenzar a realizar pruebas viendo que estamos casi terminando?

Gracias.-

**Comment by iago64** [comment]
Buenas! Cómo va?

La secuencia debería ser

Kernel a Memoria: Crea el segmento de tamaño X
Memoria a Kernel: Che no tengo el espacio contiguo, tengo que compactar
Kernel a Memoria: Compactá
Memoria a Kernel: Listo ya compacté, aca tenes las nuevas tablas de segmentos.
Kernel a Memoria: Crea el segmento de tamaño X
Memoria a Kernel: Listo, esta es la base del segmento

Si quieren realizar las pruebas es tan facil como tener una memoria de 128 bytes, un segmento 0 de 32 bytes y despues tener un script que haga mas o menos lo siguiente:
CREATE_SEGMENT 1 32
CREATE_SEGMENT 2 32
DELETE_SEGMENT 1
CREATE_SEGMENT 3 60 (aca podría ser el 1 nuevamente si asi lo quieren)

Al momento de llegar el CREATE_SEGMENT de 60, la memoria se va a ver obligada a comptactar porque va a tener la memoria de la siguiente manera antes del último CREATE_SEGMENT

00--Segmento 0--31||32--Libre--63||64--Segmento 2--95||96--Libre--128

Saludos.-

**Comment by ezequielmalfonso** [comment]
Muchas gracias, ahora lo pruebo. 
Pregunta hay alguna prueba disponible para probar todo un ciclo entero de todo el tp?

Gracias.

**Comment by iago64** [comment]
Buenas!

Por ahora solo estan las pruebas del check presencial que en si cubren buena parte de lo que es planificación, las de la entrega final las vamos a estar sacando en unos días.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Cierro el issue ya que asumo que la duda fue resuelta, cualquier cosa pendiente lo podés volver a abrir :)
Saludos!
