### ISSUE TITLE
Compactacion

### ISSUE THREAD

**Issue by fpesce27** [sisoputnfrba/foro#3097]
Hola tengo una duda sobre compactacion, mas que nada lo que le envia el kernel a memoria. Porque tengo 2 ideas en mente, la primera seria tener una tabla de segmentos global en memoria (no me gustaria hacer esta porque ya hice todo memoria sin eso, no se si estara bien eso igual :( ) y con eso compactar y devolverle todas las tablas a kernel para que kernel despues se fije cual es cual y asignar y todo eso. La segunda opcion seria que kernel le envie todas las tablas de segmentos a memoria, que compacte, y despues se las devuelve. Como ven este planteamiento o estoy muy en cualquiera jijiji? muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

Me preocupa seriamente como estas manejando la memoria sin tener una tabla de segmentos o algo similar para saber que segmento es de que proceso y que huecos libres tenes en la memoria y mas aun, como hacen para compactar la memoria.
Respecto a cómo implementarlo, hay muchísimas formas, pero en todas las implementaciones que se me ocurren la memoria conoce su estado (segmentos, procesos y huecos libres) en todo momento, con lo cual el compactar no debería ser más que recibir el mensaje del kernel, compactar y cuando le contesta mandarle las tablas actualizadas para que el Kernel las guarde en cada PCB.

Saludos.-

**Comment by fpesce27** [comment]
Nono, perdon, quizas se entendio mal, ahi veo q no redacte muy bien jasjasjasjsa. Si, en memoria tengo una tabla de segmentos, y una lista de huecos, lo que no sabia era si tendria que haber una tabla de segmentos global, aparte de la tabla de segmentos por proceso o no. Pero veo que si, asi que toca hacerla, bueno muchas gracias, perdon por la confusion
