### ISSUE TITLE
Duda sobre actualización de las tabla de segmentos de cada proceso

### ISSUE THREAD

**Issue by DanielBareiro** [sisoputnfrba/foro#3098]
Buenas tengo una duda con respecto a lo siguiente: 

> Como resultado de la compactación, el Kernel recibirá las tablas de segmentos actualizadas de todos los procesos y deberá actualizar las mismas en los PCB de cada proceso.

Esto de actualizar la tabla de segmentos de cada pcb va incluso para los que estan en estado bloqueados como los que estan ready?

**Comment by RaniAgus** [comment]
¡Buenas! Sí, en la compactación podría cambiar el inicio de cualquier segmento de cualquier proceso, por lo que hay que actualizar todas las tablas para mantenerlas consistentes. Saludos

**Comment by DanielBareiro** [comment]
Muchas gracias!
