### ISSUE TITLE
Que pasa si se solicita mas segmentos que CANT_SEGMENTOS.

### ISSUE THREAD

**Issue by ArgonzMatias** [sisoputnfrba/foro#3099]
<
Hola buen dia, nos surjio una duda con cant_segmentos. Entendemos que este numero es la cantidad maxima de segmentos por pcb. Y q cada pcb puede tener esa cantidad de segmentos. Que pasa cuando un pcb solicita mas de ese numero? 

### 💭 Soluciones posibles
Lo que me imagino es que se da un error y se pasa el pcb a estado exit. Esto seria el OUT OF MEMORY que se usa cuando no existe mas lugar para los segmentos? Nada queria aclarar esa duda q me surjio. Gracias.

**Comment by LeandroCarbajales** [comment]
Buenas!
Cito al enunciado -> Kernel -> Manejo de Memoria

> No se solicitará la creación de un segmento de un Id inválido (0 o mayor o igual al Id máximo).

Saludos!

**Comment by ArgonzMatias** [comment]
Joya perfecto, como estaba modelando la tabla de segmentos con listas pensé que me tenía q fijar en su tamaño. Pero perfecto ahí entendí.
