### ISSUE TITLE
Consulta mensaje log acceso bloque y bitmap

### ISSUE THREAD

**Issue by pablomartinfranco** [sisoputnfrba/foro#3100]
Hola, 
consulta. 

los mensajes de log de acceso a bloque y bitmap son solo al leer y escribir o tambien al reservar y liberar bloques ?

si se ecribe o se lee una cierta cantidad de bytes que supera el rango de un bloque se notifica solo el acceso al primer bloque afectado o tambien al bloque que le sigue ?

el retardo de acceso a bloque solo afecta al leer y escribir o tambien al reservar y liberar bloques ?
me imagino que solo al leer y escibir porque el realloc de bloques solo afecta al bitmap, verdad ?

y ese retardo se multiplica por la cantidad de bloques leidos o escritos o se cuenta un solo retardo por operacion de f_write y f_read ?

f_open y f_create no afectan ni el log de acceso a bloque ni de acceso a bitmap verdad?

Gracias 
Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

Esto se respondió en parte en el issue #3038

El log de acceso a bloque va a aplicar para los casos de lectura y/o escritura de un bloque, esto incluye obviamente al bloque de punteros, por eso que puede darse el caso de que en una lectura o escritura tengas 2 logs de acceso a bloque y en un truncate puede que tengas varios más si asignas más de 1 bloque al bloque de punteros.

En el caso del bitmap es mas de lo mismo, si lo recorren van a tener una lista de "logs" diciendo bloque ocupado, bloque ocupado hasta que aparezca un bloque libre.

F_OPEN al no afectar ni a los bloques ni al bitmap no cuentan.
El tema del crear depende de si uds asignan el bloque de punteros de una o no.

Saludos.-

**Comment by irinaperezg** [comment]
Hola! Una consulta, al ir asignando bloques tenemos estos logs de bloque 1 ocupado, bloque 2 ocupado, bloque 3 libre...
ahí deberiamos tener uno que diga "se asigno al bloque 3 al archivox" ? o "se asigno el bloque 3 como bloque directo/indirecto del archivox" ? pregunto porque ahora para probar tenemos ese tipo de logs pero no sabemos si van a ser necesarios.

**Comment by pablomartinfranco** [comment]
Todo perfecto, lo que no entiendo porque el truncate logearia acceso a bloques si solo afecta al bitmap ?

**Comment by iago64** [comment]
Buenas! Cómo va?

@irinaperezg tu pregunta re va para un issue aparte, pero bueno, mientras tengan los logs minimos y obligatorios, no hay problema que tengan logs extra.

@pablomartinfranco paso a contestarte tus dudas

No hay problema con lo que implementaron, pero avisenlo al momento de la corrección para que el ayudante tenga en cuenta que estan recorriendo 2 veces el bitmap.
No entiendo la parte de "acceso aleatorio", uds deberían desasignar del último bloque libre hacia el primero, con lo cual sería un _acceso directo_ al bitmap, y es lo esperado.

Saludos.-

**Comment by pablomartinfranco** [comment]
Ok perfecto. 
Pero el log tiene que estar antes o despues del clean_bit(bitmap, index) ?
Por que si loggeamos antes del clean_bit el estado va a ser siempre 1 y despues del clean_bit va a ser siempre 0.

**Comment by iago64** [comment]
Buenas!

Mientras nos avisen en que momento esta el log no hay drama, otra opción es que pongan los 2 logs y uno intermedio que diga liberando bloque 😉 

Saludos.-

**Comment by pablomartinfranco** [comment]
Ok gracias !! 
cierro issue
