### ISSUE TITLE
Dudas Fread/write

### ISSUE THREAD

**Issue by chiaraberetta0** [sisoputnfrba/foro#3101]
Buenas! Tengo un par de preguntas con respecto a fread y fwrite
1- Deberíamos usar el nombre del archivo para mas algo además de los logs obligatorios? Es decir por ejemplo, kernel le solicita a fs que escriba sobre cierto bloque, pero habría que verificar que dicho bloque pertenezca a los que ese archivo tenia asignados o algo por el estilo? la consigna no aclara nada al respecto. Lo mismo para fread 
2- El puntero que nos manda el kernel seria uno de los que pertenecen al archivo en cuestion? Es decir dentro de los q estan en el puntero indirecto
Gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- El nombre del archivo en princpio les sirve para levantar el FCB y para saber de que archivo estan hablando a la hora de hacer las peticiones desde el kernel al FS y por consecuencia que los tengamos en los logs.

2.- El puntero es lo que setean con `F_SEEK` que es de manera resumida una forma de indicarle al kernel y al FS a partir de que byte tiene que leer / escribir en el archivo y eso lo tienen en la tabla de archivos abiertos del proceso.
A partir de ese puntero o indicador de byte de inicio, es que uds tienen que calcular a que bloque del archivo pertenece.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas @chiaraberetta0 !
Te sirvió la respuesta de @iago64 ? Quedó alguna duda pendiente?

**Comment by chiaraberetta0** [comment]
Quedo claro! Perdon colgue en contestar, gracias!!
