### ISSUE TITLE
log kernel bloqueado

### ISSUE THREAD

**Issue by agusdubreucq1** [sisoputnfrba/foro#3103]
buenas tenia una duda en el log de motivo de bloqueo en el kernel
>Motivo de Bloqueo: “PID: <PID> - Bloqueado por: <IO / NOMBRE_RECURSO / NOMBRE_ARCHIVO>”

cuando se bloquea un procesos por alguna accion de file system como truncate, read o write , el log deberia decir bloqueado por: <nombre del archivo que se quiere leer/escribir/truncar>. 
osea si el log deberia decir lo mismo que cuando se bloquea por que el archivo no estaba abierto con el F_OPEN

**Comment by iago64** [comment]
Buenas! Cómo va?

Si, el log es ese, si uds quieren agregar más logs pueden hacerlo 😉 

Saludos.-

**Comment by agusdubreucq1** [comment]
Buenisimo, muchas gracias!!
