### ISSUE TITLE
Tablas de segmento

### ISSUE THREAD

**Issue by bot37** [sisoputnfrba/foro#3104]
Buen día!
En la issue #3059 https://github.com/sisoputnfrba/foro/issues/3059#issuecomment-1599473223
Se menciona que una visión válida es mandar desde CPU a Memoria el Número de Segmento, el Desplazamiento y el PID, para que en esta se realicen los cálculos necesarios.

Creemos que si usamos este enfoque, la tabla de segmentos en cada PCB no debería ser necesariamente actualizada en la compactación, y sería utilizada solamente cuando se revisa Segmentation Fault en MMU (para lo cual se debe actualizar con los create/delete segment). Es esto correcto?

Gracias!

**Comment by bot37** [comment]
Cierro momentáneamente hasta debatir mejor con grupo.

**Comment by NKennedy31** [comment]
Buenas, nosotros con nuestro grupo tenemos parecido la misma duda ¿Es realmente necesario mantener las tablas de segmentos actualizadas en las PCBs de los procesos o directamente se pueden mantener actualizadas desde memoria pidiendo la base para su uso antes de realizar la traduccion desde CPU a Memoria? Porque luego de la compactacion el actualizar las tablas de segmentos de todos los procesos nos parece innecesario si ya tenemos actualizadas todas las tablas de segmentos en memoria.
