### ISSUE TITLE
Duda de conceptos generales de algunas instrucciones

### ISSUE THREAD

**Issue by felipenani** [sisoputnfrba/foro#3105]
Buenas tardes, tenia una serie de preguntas mas que nada con el planteo de algunas cosas generales.

1- Primero, en cuanto a los registros, vi en algunos issues que se recomendaba modelarlos como char[n] pues lo que se va a manejar en ellos (y en memoria tambien)  son caracteres alfanumericos, sin embargo tambien el pcb necesita tener una lista de estos registros de CPU (nosotros los modelamos como variables globales en dicho modulo). La duda que surge aca seria que los procesos al tener una lista de registros estan "al tanto" de sus valores, entonces, seria correcto que cuando se devuelva un proceso al kernel se haga una actualizacion de las listas de registros de cada proceso que este activo? O por ahi es mas conveniente una funcion en el CPU que al entrar un proceso, antes  de ejecutar cualquier cosa, haga que "lea" los registros y se actualice solo su lista?

2- Al ejecutar la instruccion CREATE_SEGMENT y DELETE_SEGMENT el enunciado dice que el proceso es desalojado y el Kernel atiende una rutina de creacion/eliminacion de segmento que, una vez terminada, devuelve dicho proceso a la CPU. En este caso dicho proceso queda en estado Bloqueado o Ready? Y no se replanifica otro proceso para entrar a la CPU, es decir, esta queda vacia esperando que el Kernel termine la rutina y devuelva el proceso? 

3- En cuanto a DELETE_SEGMENT, cuando el enunciado dice que no se solicitara la eliminacion de un segmento inexistente, se refiere a que siempre se solicitara que se borre un segmento de la memoria y que dicho segmento pertenezca a ese proceso?

4- Por ultimo, respecto a WAIT (y SIGNAL tambien) lei el issue #2968 pero no me termino de quedar claro. En terminos de CPU es casi como un simple desalojo, obviamente avisandole al Kernel que rutina deberia seguir, pero simplemente se lo devuelve y al vaciarse espera por un proceso nuevo? Tambien entiendo que si se hace WAIT y hay instancias disponibles (>=0) el proceso desalojado se quedara en Ready, mientras que si no las hay (<0) se bloqueara el proceso en la cola de bloqueados de dicho recurso, cierto?

Desde ya muchas gracias.

### 📔 Citas del enunciado/videos

"Para realizar un DELETE_SEGMENT, el Kernel deberá enviarle a la Memoria el Id del segmento a eliminar y recibirá como respuesta de la Memoria la tabla de segmentos actualizada.
Nota: No se solicitará nunca la eliminación del segmento 0 o de un segmento inexistente.
En ambos casos, al finalizar la rutina, se deberá devolver el Contexto de ejecución a la CPU para que esta continúe con la ejecución del proceso."

"Durante el transcurso de la ejecución de un proceso, se irá actualizando su Contexto de Ejecución, que luego será devuelto al Kernel bajo los siguientes escenarios: finalización del mismo (instrucción EXIT o ante un error), necesitar ser bloqueado (instrucción I/O o WAIT), peticiones al Kernel (F_* y *_SEGMENT), o pedir ser desalojado (YIELD)."

**Comment by felipenani** [comment]
Buenas Lean, sisi se aclararon bastante, igual repregunto para terminar de cerraralas;

1- Quedo claro eso, entonces al ser parte del contexto la actualizacion de esos valores una vez entra a la CPU seria conceptualmente mas correcta que hacersela a todos los procesos cuando se devuelve dicho contexto?

2 y 3 joya clarisimos

4- Y en el caso del SIGNAL? no hay ningun desalojo nunca? simplemente se liberaria la instancia del recurso que indican los parametros y sigue con otra instruccion?

**Comment by LeandroCarbajales** [comment]
1- Cada vez que le llega un contexto a CPU debería pisar lo que tenga con esos valores que le llegan, al devolverlo debería devolver esos valores actualizados, justamente para que cada proceso (en la vida real, hilos) tenga su propio set de registros.

4- En este caso el SIGNAL no desaloja nunca porque el algoritmo de planificación es sin desalojo, por lo que el hecho de que se desbloquee un proceso no implica replanificar.

**Comment by felipenani** [comment]
Barbaro!! Muchas gracias, quedo todo claro :)
