### ISSUE TITLE
Fseek despues de fwrite/fread

### ISSUE THREAD

**Issue by irinaperezg** [sisoputnfrba/foro#3106]
Holis
Quería consultar si luego de que se ejecute un fwrite/fread kernel deberia actualizar el puntero del archivo en el pcb? Me refiero a hacer un fseek pero sin que se ejecute esa instrucción especificamente. No está aclarado pero yo asumo que si porque sino al hacer fwrite/fread consecutivos siempre estaria en la misma posición.
Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

No este aclarado porque no hace falta que lo hagan, nosotros nos vamos a encargar de hacer los F_SEEK que sean necesarios para validar que el FS funciona como esperamos.

Saludos.-

**Comment by irinaperezg** [comment]
Ahh genial, gracias
