### ISSUE TITLE
Duda sobre el ID de segmento

### ISSUE THREAD

**Issue by martudominguez** [sisoputnfrba/foro#3107]
Buenas, tengo una duda con la instrucción CREATE_SEGMENT. Esta misma pasa como parámetro el id del segmento que se quiere crear. Quería saber si entre diferentes procesos se podía repetir este ID o si es único de cada proceso. Gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Esto ya se aclaró en el issue #3090

Saludos.-

**Comment by martudominguez** [comment]
Ok gracias!
