### ISSUE TITLE
Consultas acerca de delays de lectura de bloque

### ISSUE THREAD

**Issue by D-M-Gonzalez** [sisoputnfrba/foro#3108]
Buenas!

Tengo un par de dudas, ya que aclara que hay que implementar un retardo de acceso a bloque pero no habla de una implementación correcta/incorrecta.

Nosotros al hacer un F_TRUNCATE actualmente implementamos de esta manera:
Obtiene todos los bloques del FCB actual -> X lectura de bloque - 1 ( el directo esta en el FCB no hace falta leer ), donde X es la cantidad de bloques de datos total del FCB.
Luego ejecuta la lógica del bitmap y todo eso para reasignar tamaños, pero ya no hay mas lecturas.

Al hacer un F_READ/F_WRITE:
Obtiene todos los bloques necesarios para trabajar -> X lectura de bloque - 1, donde X es la cantidad de bloques de datos afectados por la lectura.
Lee/escribe de cada bloque los datos -> X lectura de bloque, donde X es la cantidad de bloque en la lista de bloques a leer/escribir.

Para la lectura/escritura no hay muchas opciones, como no sabes si los bloques son contiguos tenes que si o si leer bloque por bloque.
Pero para traerse la lista de bloques, osea los ID, estos estan todos contiguos en el bloque_indirecto. Nosotros lo implementamos con una iteracion, digamos, si necesito 3 bloques ( sin contar el directo ) entonces accedo 3 veces al bloque_indirecto en las 3 posiciones, eso son 3 delays.
Esto esta bien? o tenemos que cambiarlo a que haga 1 solo acceso al bloque_indirecto, saque todos los datos, y de ahí file_system trabaje para separarlos?

**Comment by iago64** [comment]
Buenas! Cómo va?

Una pregunta, para que obtienen todos los bloques al truncar? Con que obtengan el de punteros les debería alcanzar, si no tienen que "recorrer" el archivo.

Para el caso de F_READ y F_WRITE esta perfecto que levanten los bloques necesarios y el tema del acceso al bloque de punteros es medio polémico, pero no hay problema, de ultima será pregunta de coloquio que nos cuenten porque no está bueno que funcione así en la realidad 😉 

Saludos.-

**Comment by D-M-Gonzalez** [comment]
Es para facilitar la implementación.
Truncar agarra el tamaño del archivo y se fija si lo estoy agrandando o achicando. A partir de ahí guarda la cantidad de bloques que tengo que sacar o agregar.
Tomo todos los bloques actuales del FCB, los guardo en una lista, y hago pop o push la cantidad de veces necesaria. 
Como modificas el bitmap de los bloques existentes sin saber su id ( osea sin acceder a los datos del bloque indirecto)?

Sobre lo otro si perfecto, entendemos que a nivel performance es horrible, pero la lógica es bastante simple por eso venía la pregunta, osea usamos la misma función de lectura para todo.

**Comment by irinaperezg** [comment]
Puede ser entonces que en F_TRUNCATE se haga 1 tiempo de retardo (el tiempo que tarda en escribir si agrega punteros), el tema es que si achica no tendría tiempo de retardo porque tecnicamente no cambia nada ni lee el bloque de punteros. Estaría bien hacerlo así o directamente no usamos retardo cuando truncamos?

**Comment by D-M-Gonzalez** [comment]
> Puede ser entonces que en F_TRUNCATE se haga 1 tiempo de retardo (el tiempo que tarda en escribir si agrega punteros), el tema es que si achica no tendría tiempo de retardo porque tecnicamente no cambia nada ni lee el bloque de punteros. Estaría bien hacerlo así o directamente no usamos retardo cuando truncamos?

Como hacen para sacar los id de bloques sin leer el bloque de punteros cuando hacen un TRUNCATE para achicar?

Digamos, tengo un fcb, con tamanio_bloque 64

TAMANIO: 250
PUNTERO_DIRECTO: 1
PUNTERO_INDIRECTO: 5

Necesita 4 bloques, por lo que en el BLOQUE 5 quedan guardados los 3 id de bloque extra y asigno 1 al bit del bitmap de cada uno de esos bloques.

Le hago un TRUNCATE 150

Ahora necesita solo 3 bloques, por lo que tengo que liberar 1 bloque de esos que estan guardados adentro del 5.
Como saben cual liberar sin acceder a los datos del BLOQUE 5 ( osea minimo 1 lectura )?

**Comment by irinaperezg** [comment]
Ah, tenes razón, me confundí, cuando hacemos el ftruncate para achicar el archivo leemos el archivo de bloques para leer los punteros asignados y marcarlos como libre en el bitmap, entonces si, si queremos sacarle X bloques, leemos el archivo de bloque X veces

**Comment by D-M-Gonzalez** [comment]
> Una pregunta, para que obtienen todos los bloques al truncar? Con que obtengan el de punteros les debería alcanzar, si no tienen que "recorrer" el archivo.

Claro! por eso no entiendo eso:

Una pregunta, para que obtienen todos los bloques al truncar? Con que obtengan el de punteros les debería alcanzar, si no tienen que "recorrer" el archivo.

Pero bueno, espero a que responda para saber.

**Comment by LeandroCarbajales** [comment]
Buenas!
En ambos casos no deberían necesitar más de un acceso a bloque de punteros.
Una vez leído el bloque de punteros, ya sabrían todos los bloques correspondientes al archivo, por lo que ya podrían marcar como libres todos los que correspondan, misma idea para f_read o f_write, ya sabrían qué bloques necesitan leer/escribir. En el caso de agrandar el archivo solamente necesitarían escribir una vez el bloque de punteros en caso de asignar bloques nuevos.

Si la implementación de leer/escribir todo de una en el bloque de punteros les cuesta mucho, que no los mate la literalidad, pueden hacer varias operaciones sobre el mismo y luego un solo sleep(), lo importante es que entiendan y representen apropiadamente el concepto subyacente.

**Comment by D-M-Gonzalez** [comment]
Claro, como necesitar solo se necesita 1 acceso. Esta bien, si es obligatorio que sea 1 solo sleep lo cambiamos.
Gracias.
