### ISSUE TITLE
Problemas con un struct

### ISSUE THREAD

**Issue by Nicolucena** [sisoputnfrba/foro#3110]
Hola, me comunico por un problema que estoy teniendo a la hora de usar algunos struct, cuando quiero utilizar el program counter mediante contexto_de_ejecucion.program_counter me salta el error type cannot be resolved. La cosa es que no me lanza este tipo de error con otros struct cuando los uso de la misma manera, ademas de que un compañero probo hacer lo mismo y utilizar el struct y no le tiro ningun error, eso significa que el error deberia estar en mi lado pero no se que es lo esta mal. Espero por una respuesta, desde ya muchas gracias.

**Comment by iago64** [comment]
Buenas! Cómo va?

Podrías darnos un poco más de info? Por ejemplo:
- Como está definido el struct?
- El error lo tenes al compilar o es un warning de eclipse?
- Estas usando la VM de la cátedra o una instalación de linux nativa?

A priori como comentas el problema es muy difícil poder entender que te está pasando.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Hola @Nicolucena !
Pudiste ver este error con lo que te comentó @iago64 ?

**Comment by Nicolucena** [comment]
Si, al final el error era mío y era muy tonto, les pido mil disculpas por las molestias
