### ISSUE TITLE
Duda sobre compactación

### ISSUE THREAD

**Issue by ailindenoya** [sisoputnfrba/foro#3111]
Buenas! 
        Tenemos una duda rápida con respecto a la compactación. Puede ocurrir que llegue un proceso (con un CREATE_SEGMENT) justo en el momento en que se haga la compactación? Porque en caso de que pase, estaríamos asignando una tabla de segmentos distinta a la tabla de segmentos al final de la compactación. Entendemos que no, ya que el proceso no se bloquea, sino que queda esperando para poder continuar una vez creado su segmento. 
Muchísimas gracias!

**Comment by LeandroCarbajales** [comment]
Exactamente!
Durante todo el proceso de compactación no se va a estar ejecutando ningún otro proceso.

Saludos!
          Lean
