### ISSUE TITLE
Duda con la prueba de ERROR_4

### ISSUE THREAD

**Issue by FacundoPiaggio** [sisoputnfrba/foro#3112]
Buenas tardes.

La duda es sobre la configuracion de la memoria y el cpu.
Veo que la prueba crea segmentos de 256, pero el tamaño maximo de segmento de cpu es 128.
Ademas la memoria es de 4096, causando que no arroje error de out of memory. 

¿Estan mal los valores de la config? o ¿tenemos que considerar el caso de que se pida crear un segmento de mayor tamaño que el del maximo en cpu?

Entiendo que es lo primero, puesto que hay una aclaracion en el enunciado del kernel que indica: "No se solicitará nunca la creación de un segmento con tamaño mayor al máximo configurado
en el sistema"

Gracias

**Comment by tomasmartinez02** [comment]
Buenas me sumo a la consulta, note lo mismo.
Saludos.

**Comment by iago64** [comment]
Buenas! Cómo va?

De las cosas que podían salir mal, olvidarnos de aceptar una sugerencia de cambios en el doc era algo que nos podía pasar 😄 
El tamaño de la memoria tiene que ser el 1024 y ya está corregido en el doc de pruebas, gracias por avisar.

Saludos.-

**Comment by MiltonMartorello** [comment]
@iago64 quería agregar una pavadita: El config de kernel para pruebas de error tiene:
ESTIMACION_INICIAL=10000, lo que difiere de las pruebas base. (2000)
Sin embargo en las pruebas vemos que se corre todo con FIFO. Se puede usar directamente el config de las pruebas base no? 
Gracias!

**Comment by iago64** [comment]
@MiltonMartorello Da lo mismo, eso quedo así porque no nos importa la estimación y porque el config es una copia del que tienen en el enunciado.
