### ISSUE TITLE
Duda con la prueba de memoria

### ISSUE THREAD

**Issue by FacundoPiaggio** [sisoputnfrba/foro#3113]
Buenas tardes.

Viendo la configuracion con la que hay que probar los scripts de memoria, note que el valor del algoritmo de asignacion es el siguiente:

"ALGORITMO_ASIGNACION=FIRST / BEST / WORST"

La pregunta (un poco boluda) es: ¿el valor es "FIRST / BEST / WORST"? o ¿es cualquiera de los 3?

**Comment by iago64** [comment]
Buenas, Cómo va?

Lo que quisimos exponer ahi es que van a tener que correr las pruebas 3 veces, 1 por cada algoritmo 😉 

Saludos.-

**Comment by FacundoPiaggio** [comment]
Ahh excelente. Muchas gracias
