### ISSUE TITLE
Posible error en las pruebas de FS

### ISSUE THREAD

**Issue by FacundoPiaggio** [sisoputnfrba/foro#3114]
Buenas tardes.

En el script: FS_1, linea 18 falta el nombre del archivo. Asumo que es "Consoles"

**Comment by FacundoPiaggio** [comment]
Otro posible error que note:

En el script: FS_3, linea 4, los parametros del MOV_IN están al revés.
Basándome en el enunciado debería ser: (REGISTRO, DIRECCIÓN LÓGICA), pero está como: (DIRECCIÓN LÓGICA, REGISTRO)

**Comment by franco-magne** [comment]
Buenas, qué tal

Aprovecho a comentar una duda sobre el mismo script FS_1.

F_OPEN Consoles
F_TRUNCATE Consoles 256
F_SEEK Consoles 128

Si el archivo Consoles tiene un tamaño de 256, con el block_size definido en las configs tendrá cuatro bloques: el puntero directo y dos punteros a los bloques dentro del puntero indirecto. Ahora mi duda es cuando se hace el F_SEEK Consoles 128, ¿no tendría que ser un número del 0 al 2 (sin contar el puntero indirecto)? Yo hasta el momento tenía entendido que la instrucción recibía la posición del puntero, pero sino nosotros podemos dividir este valor por el block_size para obtenerlo.

**Comment by irinaperezg** [comment]
@franco-magne Creo que si el tamaño es 256 el archivo tendría puntero directo, puntero indirecto y tres bloques en el bloque de punteros. Y me parece que a F_SEEK se le pasa el byte del archivo en el que se quiere poner el puntero, no el número de bloque, porque podría ser en cualquier posición del bloque, no necesariamente al incio.

**Comment by franco-magne** [comment]
Bien, ¡gracias por la observación y ayuda! Ya hice los ajustes necesarios

**Comment by iago64** [comment]
Buenas! Cómo va?

Gracias por los avisos, efectivamente nos había faltado el nombre en el F_WRITE y en MOV_IN teníamos los parámetros dados vuelta, ya quedaron corregidos los scripts.

Saludos.-
