### ISSUE TITLE
Problemas con fread al leer chars del archivo de bloques

### ISSUE THREAD

**Issue by irinaperezg** [sisoputnfrba/foro#3115]
Holis :) Estoy teniendo un problema al leer chars del archivo de bloques implementando la instrucción F_READ
Pusimos muchos logs como para poder encontrar en donde se genera el error, el tema es que no le encontramos error.
Al leer punteros (uint32_t) del archivo de bloques para F_WRITE Y F_READ no tenemos problema, lee correctamente y salta de bloque en bloque como corresponde. Tampoco hay problema al escribir char en bloques usando en F_WRITE.

### 🐛 Cómo reproducir el error
Por comodidad usamos bloques de 16 bytes para poder interpretar mejor el archivo de bloques con el hexdump.
`F_OPEN archivo
F_SEEK archivo 32
F_READ archivo 16 64
F_CLOSE archivo
EXIT`
Mandamos este proceso para que lea 64 bytes a partir del byte 32 del archivo (que ya tiene bloques asignados y cosas escritas por un f_write hecho previamente)

![image](https://github.com/sisoputnfrba/foro/assets/83139862/836dd1fa-447b-4b25-bdbf-0b9ad59abe7f)

Haciendo hexdump vemos que el contenido del archivo de bloques es correcto.
![image](https://github.com/sisoputnfrba/foro/assets/83139862/c14f3cd0-9296-45dc-bfc5-03fd2482a92a)
(Perdón por las capturas de pantalla pero me pareció que se iban a entender mejor los logs así)

### 📝 Código relevante
```
void leer_archivo(char *nombreArchivo, uint32_t punteroProceso, uint32_t direccionFisica, uint32_t cantidadBytes, uint32_t pidProceso)
{   
....
....
 bytesQueFaltanPorLeer = cantidadBytes;
    char *informacion = malloc(cantidadBytes);
    char *buffer = malloc(tamanioBloques);

    // Obtengo la posicion desde la cual voy a empezar a leer informacion.
    posicionAbsoluta = obtener_posicion_absoluta(fcbArchivo, punteroProceso);
    log_info(filesystemLogger,"Va a empezar a leer desde la posicion <%u>.", posicionAbsoluta);

    espacioDisponible = espacio_disponible_en_bloque_desde_posicion(punteroProceso);

    archivoDeBloques = abrir_archivo_de_bloques();
    fseek(archivoDeBloques, posicionAbsoluta, SEEK_SET);
    log_info(filesystemLogger, "posicion desde la que vamos a leer: %ld", ftell(archivoDeBloques));
    
     if (cantidadBytes < espacioDisponible)
    {   
        ... 
    }
    // Si la cantidad de bytes a leer es mayor que el espacio que queda en el bloque seleccionado, se leen todos los bytes que queden en el bloque antes de pasar al siguiente.
    else
    {
        log_info(filesystemLogger,"La cantidad de bytes a leer <%u> es mayor al espacio disponible <%u> del bloque", cantidadBytes, espacioDisponible);
        size_t cantBytesLeidas = fread(buffer, sizeof(char), espacioDisponible, archivoDeBloques); -->ESTO NOS DEVUELVE 0
        log_info(filesystemLogger,"Leyo <%lu> cant bytes", cantBytesLeidas );
        // Se mueve el puntero del archivo hasta el ultimo lugar que se leyo.
        puntero = puntero + espacioDisponible; 
        log_info(filesystemLogger,"Ahora el puntero del proceso apunta a <%u> ", puntero);
        // Contador de bytes leidos.
        bytesLeidos = espacioDisponible;
        // Contador de bytes que faltan por leer.
        bytesQueFaltanPorLeer = bytesQueFaltanPorLeer - bytesLeidos;

        // Pasar la data leida del buffer al char *informacion.
        memcpy(informacion, buffer, bytesLeidos);

        log_info(filesystemLogger,"Leyo <%s>", buffer);
        free(buffer);
    }
```

Después siguiendo el código se leen la cantidad de bloques que haga falta y eso a juzgar por los logs anda bien, asi que no sería tanto un problema la lógica sino que por alguna razón fread no está leyendo correctamente, y como la manera en que leemos es igual en todas las iteraciones y casos, el problema lo tenemos en toda la función. No hay problemas al abrir el archivo de bloques porque verificamos que se abra correctamente, también abrimos de modo r+b pero tampoco creemos que es el problema porque para leer punteros y escribir chars no tuvimos ningun tipo de problema.

No se si se entenderá bien a lo que me refiero pero igualmente muchas gracias por leer :)
Saludos

**Comment by LeandroCarbajales** [comment]
Buenas!
Efectivamente es un error raro, más allá de correrlo en debug para corroborar que todos los valores que le están pasando a sus funciones sean los correctos y devuelvan lo esperado, les puedo recomendar que, como dice en el [man de fread()](https://man7.org/linux/man-pages/man3/fread.3.html) -> RETURN VALUE, si la función fread devuelve cero es porque hubo un error en la misma y deberían chequearlo con feof o ferror. Fíjense de agregar el chequeo cuando devuelve 0 para identificar el error que está teniendo la función.

**Comment by irinaperezg** [comment]
Dale gracias :)) Voy a seguir buscando entonces.
