### ISSUE TITLE
Consulta alloc dealloc bloques

### ISSUE THREAD

**Issue by pablomartinfranco** [sisoputnfrba/foro#3116]
Hola !! 
consulta simple pero pregunto por las dudas,
cuando f_truncate pide aumentar size de un archivo y no llega a necesitar reservar un bloque.

Puede ser que no hay acceso a bloque pero igual se actualiza el file_size en el FCB ?

Hay que poner un caracter EOF en el byte que corresponde al final del archivo ?

Pregunto porque sino pareciera que solo se actualiza el file_size cuando se agranda o achica el archivo pero no se sale del ultimo bloque.

**Comment by iago64** [comment]
Buenas! Cómo va?

Si el F_TRUNCATE aumenta el size del archivo, pero no necesita agregar bloques, efectivamente, no deberían tener ningún acceso a bloque, con actualizar el FCB alcanza.

Saludos.-

**Comment by pablomartinfranco** [comment]
genial gracias !
