### ISSUE TITLE
orden de conexiones

### ISSUE THREAD

**Issue by agusdubreucq1** [sisoputnfrba/foro#3117]
hola buenas, queria consultar si cuando conectemos los modulos en la entrega final, nosotros ponemos el orden en que se conectan los modulos o puede ser aleatorio?
porque hasta ahora venimos haciendo que la memoria interprete que la primera conexion en la de FileSystem, la segunda de CPU, y asi. por lo que si conectamos en diferente orden puede interpretar que la CPU es el filesystem y todo funcionaria mal.

**Comment by iago64** [comment]
Buenas! Cómo va?

En la entrega final uds van a ejecutar las pruebas, no hay problema con que tengan un orden definido para levantar los procesos.

Saludos.-

**Comment by agusdubreucq1** [comment]
perfecto, muchas gracias!
