### ISSUE TITLE
Posible error sobre waits y signals en las pruebas

### ISSUE THREAD

**Issue by JuanpiCasti** [sisoputnfrba/foro#3118]
Buenas, tengo algunas dudas sobre el comportamiento esperado de los SIGNALS mas especificamente.
En las pruebas se hacen SIGNAL sobre recursos de los que un proceso no hizo un WAIT previamente. 

Por ejemplo, en el script MEMORIA_1:

```WAIT RA
SET AX h014
MOV_OUT 12 AX
CREATE_SEGMENT 1 128
SIGNAL RB
WAIT RA
DELETE_SEGMENT 1
MOV_IN DX 12
SIGNAL RB
WAIT RA
EXIT
```

El proceso que lo ejecute hara signal sobre RB sin haber hecho waits previos.

Esto es un error? Si no lo es, cual seria el comportamiento esperado, dejarlo pasar?

**Comment by iago64** [comment]
Buenas! Cómo va?

Deberían implementarlo como esta en el enunciado, cito al enunciado en donde en ningun momento se dice que el proceso que hace el SIGNAL es el mismo que hizo el WAIT:

> A la hora de recibir de la CPU un Contexto de Ejecución desplazado por SIGNAL, el Kernel deberá verificar primero que exista el recurso solicitado y luego sumarle 1 a la cantidad de instancias del mismo. En caso de que corresponda, desbloquea al primer proceso de la cola de bloqueados de ese recurso. Una vez hecho esto, se devuelve la ejecución al proceso que peticionó el SIGNAL.

Saludos.-

**Comment by JuanpiCasti** [comment]
Perfecto, se me hacia raro pensar que el sistema en algun momento tuviera mas instancias en un recurso que con las que empieza desde el config.
Muchas gracias.
Saludos

**Comment by agusdubreucq1** [comment]
buenas, no entendi si te referiste a que si un proceso hace un signal de un recurso al cual no hizo un wait la instancia se sumaria o quedaria como estaba.
porque capaz pensando un recurso como un semaforo, los procesos pueden hacer un signal sin haber hecho un wait. pero pensandolo como una impresora capaz no tenia sentido que en algun momento se tengan mas instancias que con las que empezaron.
