### ISSUE TITLE
syscall de un proceso, sin desalojar

### ISSUE THREAD

**Issue by agusdubreucq1** [sisoputnfrba/foro#3120]
buenas! 
una consulta, en los casos donde un proceso invoca al kernel, pero luego sigue ejecutando ese mismo proceso.
nosotros lo implementados de una manera medio rara que para mi esta mal, pero quiero chequearlo porque en el grupo hay dudas.
nosotros luego de ejecutar la instrucción desde el Kernel, estamos mandando al proceso a la cola de ready y al momento de mandar un proceso a cpu, sacamos ese mismo proceso sabiendo cual ejecuto antes. 
Todo funciona bien ya que no actualizamos el tiempo en ready y solo lo hacemos en los casos que sabemos que vuelve el mismo proceso, pero es mas desde un punto de vista teórico y por los logs que muestra para la entrega final

**Comment by iago64** [comment]
Buenas! Cómo va?

Es medio extraño ese comportamiento, ya que en las syscalls si vuelve a ejecutar el mismo proceso no deberían "desalojar" el mismo y es lo que justamente están haciendo al pasarlo a ready.

Saludos.-

**Comment by agusdubreucq1** [comment]
perfecto, lo cambiamos. muchas gracias!
