### ISSUE TITLE
Consulta: Posible error en pruebas de memoria

### ISSUE THREAD

**Issue by MiltonMartorello** [sisoputnfrba/foro#3121]
Holis. Cómo andan?
Estabamos corriendo pruebas de memoria y nos cruzamos con las siguientes lineas en la prueba de MEMORIA_2

### 📔 Citas del documento de pruebas
```
SET_EAX CoscuWin
...
SET_EBX GermanNo
```

Teníamos entendido que no se iban a enviar instrucciones inválidas. En este caso la función y el registro no estan separados por espacio
Deberíamos contemplar este caso o esta mal la prueba?

[Cito lineas en su repo](https://github.com/sisoputnfrba/tuki-pruebas/blob/73874b54a4c3e40b6a8bd3a4dd1f979aed86c314/MEMORIA_2#L16-L18)

Gracias

**Comment by iago64** [comment]
Buenas!

Fue un dedazo a la hora de redactar el script, ya quedo arreglado 😄 

Saludos.-
