### ISSUE TITLE
duda comportamiento signal

### ISSUE THREAD

**Issue by agusdubreucq1** [sisoputnfrba/foro#3122]
Buenas! Cómo va?

Deberían implementarlo como esta en el enunciado, cito al enunciado en donde en ningun momento se dice que el proceso que hace el SIGNAL es el mismo que hizo el WAIT:

> A la hora de recibir de la CPU un Contexto de Ejecución desplazado por SIGNAL, el Kernel deberá verificar primero que exista el recurso solicitado y luego sumarle 1 a la cantidad de instancias del mismo. En caso de que corresponda, desbloquea al primer proceso de la cola de bloqueados de ese recurso. Una vez hecho esto, se devuelve la ejecución al proceso que peticionó el SIGNAL.

Saludos.-

_Originally posted by @iago64 in https://github.com/sisoputnfrba/foro/issues/3118#issuecomment-1627808435_

buenas no pude reabrir el issue, pero no entendi si te referiste a que si un proceso hace un signal de un recurso al cual no hizo un wait la instancia se sumaria o quedaria como estaba.
porque capaz pensando un recurso como un semaforo, los procesos pueden hacer un signal sin haber hecho un wait. pero pensandolo como una impresora capaz no tenia sentido que en algun momento se tengan mas instancias que con las que empezaron.

**Comment by LeandroCarbajales** [comment]
Buenas!
Es como dice el enunciado (citado en el comentario), siempre se le suma uno independientemente de si antes le hizo wait o no, es análogo a la implementación básica de semáforos vista en clases. En estas últimas pruebas el uso es como si fueran semáforos "binarios" (para garantizar orden de ejecución).
Si lo quisieras ver como una impresora por ejemplo, no sería raro tampoco el hecho de agregar una instancia más de ese recurso durante la ejecución (por ejemplo si se conectó una nueva), la idea en este trabajo es justamente poder usarlos para cualquier propósito, por eso la validación que mencionan estaría de más.

Saludos!
          Lean

**Comment by agusdubreucq1** [comment]
clarisimo, muchas gracias!
