### ISSUE TITLE
Duda de como guardar los bloques dentro del bloque de mi puntero indirecto

### ISSUE THREAD

**Issue by IanFeldman0810** [sisoputnfrba/foro#3123]
Buenass! 
Tengo una duda sobre como guardar los bloques que tengo que usar dentro del bloque del puntero indirecto.
Supongamos que mi puntero indirecto corresponde al bloque 1, y cada bloque tiene un tamaño de 16,  entonces en mi archivo de bloques, que esta mapeado, iría de la posición 16 a la 25 inclusive. 
Me llega un f_truncate  y me dice que el tamaño es de 48, entonces estaría necesitando 1 bloque directo y 3 adicionales, leo mi bitmap y se que los bloques 3, 4, 5 están disponibles, entonces en el bloque de mi puntero indirecto tengo que guardar los bloques adicionales que necesito.
Ahora mi duda es la siguiente, para guardar en mi bloque 1 que necesito el bloque 3,4 y 5 puedo separar los bloques con algún carácter especial?
Ejemplo:
Bloque 1 (Pos. 16-25)
16: 3 (bloque)
17: |
18: 4 (bloque)
19: |
20: 5 (bloque)
....
El pipe(u otro carácter especial) lo usaría para cuando leo el bloque 1 saber cuales son los bloques adicionales que tengo, sino no tengo forma de saber cuantos caracteres tenia el identificador de ese bloque adicional.

La otra forma que se me ocurrió es haciendo algún tipo de estructura en el que guardo el nro de posición (ejemplo 16) y la cantidad de caracteres que ocupa(en este caso 1), así si puedo saber cuantos caracteres tenia el identificador de ese bloque adicional y leer cada uno sin problemas, solo aplicaría esto si no se podría hacer de la otra forma.

Muchísimas gracias!!

**Comment by iago64** [comment]
Buenas! Cómo va?

La implementación que propones contradice al enunciado. Cito al enunciado:

> Nota: todos los punteros del FS se almacenarán como números enteros no signados de 4 bytes (uint32_t)

Saludos.-

**Comment by IanFeldman0810** [comment]
Buenoas dias!!

Se me había pasado por alto eso, mil gracias!!
