### ISSUE TITLE
Consulta tamaño de archivo y bloques

### ISSUE THREAD

**Issue by gabdigiorgio** [sisoputnfrba/foro#3124]
Buenas tengo una duda en cuanto a que tamaño tiene un archivo cuando lo truncamos. Por ejemplo, con bloques de 16 bytes, si yo hago un F_TRUNCATE ARCHIVO 48, debería tener asignado un puntero directo, un indirecto y un bloque apuntado por el puntero indirecto? o el tamaño ocupado por el puntero indirecto no cuenta para el tamaño del archivo? 

En caso de no contar el tamaño del puntero indirecto, sería un puntero directo, un indirecto y 2 bloques apuntados por el puntero indirecto? 

Saludos!

**Comment by LeandroCarbajales** [comment]
Buenas!
Respondido en #3045

**Comment by gabdigiorgio** [comment]
Genial muchas gracias!
