### ISSUE TITLE
Consulta sobre F_WRITE en FS_1

### ISSUE THREAD

**Issue by franco-magne** [sisoputnfrba/foro#3126]
Buenas, ¿cómo están?

Quería confirmar cuál de los dos caminos que estoy pensando hacer está bien. Resulta que la instrucción F_WRITE me pide que escriba 80 bytes de lo que se encuentra en la dirección 32, que entiendo sería **SonyPlaystation1**, pero esta es una cadena de 16 bytes. Cuando escribo esta cadena en el archivo de bloques, ¿tengo que ver los 16 bytes de la cadena y los 64 bytes restantes como cadena vacía o tengo que repetir N veces los 16 bytes hasta completar los 80 bytes que me piden?

📔 Citas del documento de pruebas

SET RBX SonyPlaystation1
MOV_OUT 32 RBX
...
F_OPEN Consoles
F_TRUNCATE Consoles 256
F_SEEK Consoles 128
SIGNAL RB
F_WRITE Consoles 32 80
...

**Comment by RaniAgus** [comment]
¡Buenas!
La memoria no registra de dónde proviene los bytes que contiene, por lo que si le piden leer 80 bytes desde la dirección 32, va a leer desde la dirección 32 hasta la 111 inclusive.

Saludos

**Comment by franco-magne** [comment]
Muchas pero muchas gracias. Vimos que nuestra duda y problema pasaba por otro lado y ya lo pudimos solucionar.

Saludos.
