### ISSUE TITLE
Agregar otro parametro al config

### ISSUE THREAD

**Issue by D-M-Gonzalez** [sisoputnfrba/foro#3127]
Buenas!

Molesto denuevo jaja. Estabamos pensando que para facilitar las pruebas, en el caso de que tengamos que reiniciar todo a 0 ( memoria, file system y archivos .dat ) es un quilombo hacerlo a mano.
Se nos ocurrio agregar un parámetro a las config de memoria y file_system que sea INICIALIZAR y FORMATEAR. En memoria no afecta mucho pero lo usamos nosotros para ver lo que hay en memoria ( hicimos un monitor de la memoria de ambos modulos ) y sino queda con basura.
Pero en file system si, porque si pasa un error o algo, hay que reiniciar el bitmap, y borrar los fcb que no van, y esto implica cambiar el código, por lo que tener un parámetro FORMATEAR en nuestras config que si esta en 1 haga esto, nos facilita bastante.

Se puede? Si no se puede con las config que pide la cátedra, hay algún drama si lo agregamos como argumento de ejecución?

Gracias!

**Comment by iago64** [comment]
Cito al enunciado:

> Archivos de Configuración: En este punto se da un archivo modelo y que es lo mínimo que se pretende que se pueda parametrizar en el proceso de forma simple. En caso de que el grupo requiera de algún parámetro extra, podrá agregarlo.

Saludos.-

**Comment by D-M-Gonzalez** [comment]
Perdon, estamos muy quemados ya jajaja, gracias!
