### ISSUE TITLE
Conexion entre modulos

### ISSUE THREAD

**Issue by matolivaUTN** [sisoputnfrba/foro#3128]
Hola buenos dias, queriamos consultar si podemos agregar como parametro a los archivos de config la ip de su propio modulo para el getaddrinfo o si se deberia hacer de otra manera ya que los modulos se conectan localmente pero no entre computadoras distintas.

**Comment by iago64** [comment]
Fue respondido en la consulta #3127

**Comment by matolivaUTN** [comment]
Genial, muchas gracias
