### ISSUE TITLE
Consulta sobre liberacion de procesos y sus recursos

### ISSUE THREAD

**Issue by FacundoPiaggio** [sisoputnfrba/foro#3129]
Buenas.

Corriendo las pruebas de memoria, notamos que al finalizar los procesos se liberan recursos de mas, que originalmente no estaban en el sistema (por configuración).
Cuando se hace un WAIT de algún recurso, nosotros, ademas de quitarle una instancia, lo guardamos en una lista_de_recursos_asignados de proceso, para que luego, en un signal se remueva la entrada y se sume la instancia correspondiente.

¿Cual es el problema? Cuando nosotros desde el kernel vamos a terminar un proceso, en caso de este haber terminado por algún error (SEG_FAULT o OUT_OF_MEMORY) revisamos que no le queden recursos asignados que no haya liberado voluntariamente y le sumamos una instancia.
Es decir, un proceso podría venir, hacer WAIT R1, pero por algún error terminar antes de hacer el SIGNAL y perder ese recurso. Considerando esto, nosotros "liberamos" ese recurso antes de terminar al proceso.

En las pruebas de memoria, los procesos hacen WAIT de recursos los cuales el SIGNAL seran realizados por otros proceso. Causando que no se remuevan dichos recursos de la listas de los procesos y siendo liberados al finalizar los mismos por normalidad, y como resultado, quedan mas recursos de los que originalmente había.

Esto esta mal, ¿verdad?

`[TRACE] 20:02:17:096 kernel/(3830:3832): Finaliza el proceso < 2 > - Motivo: < SUCCESS >`
`[TRACE] 20:02:17:096 kernel/(3830:3832): El proceso < 2 > se movio a TERMINATED`
`[DEBUG] 20:02:17:097 kernel/(3830:3832): Se libera instancia del recurso: RB. Instancias: 1`
`[DEBUG] 20:02:17:097 kernel/(3830:3832): Se libera instancia del recurso: RB. Instancias: 2`
`[DEBUG] 20:02:17:097 kernel/(3830:3832): Se libera instancia del recurso: RB. Instancias: 3`
`[DEBUG] 20:02:17:097 kernel/(3830:3832): Se libera instancia del recurso: RB. Instancias: 4`

**Comment by iago64** [comment]
Buenas! Cómo va?

Como vieron en la teoría, los procesos al finalizar liberan los recursos que tenian tomados, entonces, si el proceso A termina y no tenia tomado ningun recurso, listo, no pasa nada, eventualmente los SIGNALS que hacía para liberar a los procesos B (hablando ya de la prueba de memoria) no se van a dar y esos procesos van a quedar frenados.

De todas formas, en la prueba de memoria, no debería morir ningún proceso de forma anomala, para eso tenemos la prueba de errores 😉 

Saludos.-

**Comment by FacundoPiaggio** [comment]
Genial!

El tema es que nosotros estamos liberando los recursos tomados sin importar el motivo por el cual termina el proceso. Es decir, lo habíamos entendido como que no podía liberar algún recurso sin antes pedirlo. Por ejemplo, nos sonaba raro que se libere una impresora sin habérsela asignado antes.

¿Para arreglar esto lo que podemos hacer es liberar los recursos solamente si el proceso esta finalizando por algún error no?
De otra forma estaría terminando de manera correcta y suponemos que el pedido y liberado de los recursos va a ser el correcto entre los procesos

Muchas gracias dami!

**Comment by iago64** [comment]
Buenas! Cómo va?

La implementación que tienen de que solo liberan lo que tomaron independientemente de cómo finalice esta bien, pero solo tienen que liberar los que tomo la cantidad de instancias que tomo el proceso.

Saludos.-

**Comment by FacundoPiaggio** [comment]
Ehmm me mareo un poco la ultima oración "solo tienen que liberar los que tomo la cantidad de instancias que tomo el proceso"
perdón jajajaj

**Comment by iago64** [comment]
Buenas! Cómo va?

No hay nada que perdonar, en estas fechas es normal estar un poco más quemados que de costumbre 😄 Veamos si un ejemplo ayuda:

Supongamos que tenes en el sistema los recuros A, B, C y D y el proceso 1 que solo hace lo siguiente:
WAIT A
WAIT B
WAIT C
EXIT

Al ejecutar el EXIT, solo tendría que liberar 1 instancia de A, 1 instancia de B y 1 instancia de C, nada más ni nada menos, me explique bien ahi? (Yo tambien estoy algo quemado 😢)

Saludos.-

**Comment by FacundoPiaggio** [comment]
Genial, clarisimo dami, muchas gracias!
