### ISSUE TITLE
Error extraño con bitarray

### ISSUE THREAD

**Issue by lucasdeferrari** [sisoputnfrba/foro#3130]
Buenas tardes, tenemos una duda con un error que nos tira el bitarray. Cada vez que intentamos utilizar la funcion `test_bit` fuera del main, nos lanza un segmentation fault. Corrimos con valgrind y en la linea donde hacemos el `test_bit` nos lanza 2 errores: 
1- Access not within mapped region at address 0<40370000 [PID: 2585]
2-  Invalid read of size 1
Investigando, nos dimos cuenta que esos errores saltan porque estamos intentando de acceder a memoria no mapeada/ no disponible. El tema es que en el main nos deja y en otro lugar no. Cabe aclarar, que no hacemos absolutamente nada con el bitarray, y que esta inicializado en el archivo .h. Estuvimos dandole vueltas a este error por horas y no logramos encontrar la solucion. 

Este es el codigo que nos lanza error: (está el numero 1 porque queriamos ver si el error estaba en el valor del bit que le pasabamos apra que lea pero no)
`bool valor= bitarray_test_bit(bitarray_mapeado, 1);`

Muchas gracias y buen martes.

**Comment by iago64** [comment]
Buenas! Cómo va?

Podrías subir todo el código de como están abriendo el archivo, mapeandolo y como crean el bitarray? 
Porque en el aire pueden tener problemas en el momento que lo mapean pero por las dudas estaría bueno checkear que no estén pasando mal ningún tamaño.

Saludos.-

**Comment by lucasdeferrari** [comment]
Por supuesto, adjunto el codigo: 
```
if (config_has_property(config, "PATH_BITMAP")) {
       	 printf("Existe el path al bitmap.\n");
       	 p_bitmap = config_get_string_value(config, "PATH_BITMAP");
       	 }
       	 else {
       	 printf("No existe el path al bitmap.\n");
       	 exit(5);
       	 }

    //CHEQUEO SI EL ARCHIVO YA EXISTE
    if (access(p_bitmap, F_OK) == -1) {
       printf("El archivo bitmap no existe.\n");
       archivo_bitmap = fopen(p_bitmap, "w");
       if (archivo_bitmap) {
              printf("El archivo bitmap se ha creado exitosamente.\n");
              fclose(archivo_bitmap);
          } else {
              printf("No se pudo crear el archivo bitmap.\n");
          }
    }

    archivo_bitmap = fopen(p_bitmap, "r+");
    if (archivo_bitmap == NULL) {
        fprintf(stderr, "Error al abrir el archivo de bitmap.\n");
        exit(1);
    }

    // OBTENGO EL DESCRIPTOR DE ARCHIVO
    int fd = fileno(archivo_bitmap);
    printf("File descriptor: %i\n" , fd);

    // AJUSTO EL TAMAÑO DEL ARCHIVO PARA Q COINCIDA CON EL DEL BITARRAY
	off_t result = lseek(fd, block_count - 1, SEEK_SET);
	if (result == -1) {
		perror("Error al ajustar el tamaño del archivo");
		exit(1);
	}

	// ESCRIBO UN BYTE NULO AL FINAL DEL ARCHIVO PARA Q OCUPE ESPACIO
	result = write(fd, "", 1);
	if (result == -1) {
		perror("Error al escribir en el archivo");
		exit(1);
	}


    // Realizar el mapeo
    mapping = mmap(NULL, block_count, PROT_WRITE, MAP_SHARED, fd, 0);
    if (mapping == MAP_FAILED) {
        perror("Error en mmap");
        exit(1);
    }

    //lo agregue por afuera porque lo necesitaba
    bitarray_mapeado = bitarray_create_with_mode(mapping, block_count, LSB_FIRST);
```

**Comment by iago64** [comment]
Buenas! 

A priori veo algunos detalles a tener en cuenta:

1.- El tamaño del archivo debería ser `block_count / 8`
2.- El tamaño del bitarray si esta bien que sea block_count
3.- En lugar de hacer el seek, directamente pueden usar [ftruncate()](https://linux.die.net/man/2/ftruncate)`` y se ahorran que eso pueda estar generandoles inconvenientes.

Saludos.-

**Comment by Luli57** [comment]
Buenos días,

Realizamos las modificaciones sugeridas y seguimos teniendo el mismo problema:

	int result = ftruncate(fd, block_count/8);
	if (result == -1) {
		perror("Error al ajustar el tamaño del archivo");
		exit(1);
	}else if (result == 0 ){
		printf("El tamanio del archivo se modifico correctamente");
	}

En este while nos sigue saltando el invalid read:

while(bitarray_test_bit(bitarray_mapeado, bloqueNuevo) != 0){
        bloqueNuevo++;
}

No es simplemente en el bit test, si no utilizamos esa funcion nos salta de todas formas para el bit set y bit clean.

**Comment by RaniAgus** [comment]
¡Buenas! Veo que están abriendo el archivo para solo lectura:
```c
archivo_bitmap = fopen(p_bitmap, "r+");
```

Y luego están mapeando la memoria para solo escritura:
```c
mapping = mmap(NULL, block_count, PROT_WRITE, MAP_SHARED, fd, 0);
```

Pueden probar pasando `rw+` y `PROT_WRITE | PROT_READ` respectivamente.

Saludos

**Comment by Luli57** [comment]
Sigue saltandonos el error :(

**Comment by Luli57** [comment]
puedo mandar el codigo compelto de la funcion si eso ayuda a entender el problema, o de haber algun ayudante disponible podriamos verlo rapidamente por discord de ser posible?

El bitarray se usa para f_truncate, la funcion es la siguiente:
void truncar_archivo(char* nombreArchivo, int tamanio){

	crearPathArchivo(nombreArchivo);

	configFCBT = config_create(p_fcb);

	int tamanioArchivo = 0;
	int punteroIndirecto = 0;
	int punteroDirecto = 0;
	char tam[20];

	if (configFCBT == NULL) {
	        printf("No se pudo crear el config.\n");
	        exit(5);
	 }else{

	    if (config_has_property(configFCBT, "TAMANIO_ARCHIVO")) {
	    	tamanioArchivo =  config_get_int_value(configFCBT, "TAMANIO_ARCHIVO");
	    	punteroIndirecto =  config_get_int_value(configFCBT, "PUNTERO_INDIRECTO");
	    	punteroDirecto =  config_get_int_value(configFCBT, "PUNTERO_DIRECTO");
	    }else {
	    	printf("No existe la property.\n");
	    	exit(5);
	    }

    	        snprintf(tam, sizeof(tam), "%d", tamanio);
		config_set_value(configFCBT, "TAMANIO_ARCHIVO", tam);

		int cantidadBloquesNecesarios = ceil(tamanio / block_size)+1;

		int cantidadBloquesActual = 0;
		int contador = 0;

		if (punteroDirecto != 0){
			cantidadBloquesActual++;
		}

		if (punteroIndirecto != 0){
			char* blockChar = (char*)mapping2 + punteroIndirecto*block_size + (contador*4);
			uint32_t block = atoi(blockChar);

			while (bitarray_test_bit(bitarray_mapeado, block) != 0){
				contador++;
				char* blockChar = (char*)mapping2 + punteroIndirecto*block_size + (contador*4);
			}
		}

		cantidadBloquesActual += contador;

		if (tamanio < tamanioArchivo){
//				Reducir el tamaño del archivo: Se deberá asignar el nuevo tamaño del archivo en el FCB y
//				se deberán marcar como libres todos los bloques que ya no sean necesarios para direccionar
//				el tamaño del archivo (descartando desde el final del archivo hacia el principio).

			if(cantidadBloquesNecesarios < (cantidadBloquesActual)){

				//liberar bloques del bitmap.
				int i = 0;
				int diferencia = cantidadBloquesActual - cantidadBloquesNecesarios;
				int bloquesALiberar = diferencia-1;

				if (cantidadBloquesNecesarios == 0){
					bitarray_clean_bit(bitarray_mapeado, punteroDirecto);
					log_info(logger, "Acceso a Bitmap - Bloque: <%d> - Estado: <%d>\n", punteroDirecto, 0);
				}

				if(cantidadBloquesNecesarios <= 1){
					bitarray_clean_bit(bitarray_mapeado, punteroIndirecto);
					log_info(logger, "Acceso a Bitmap - Bloque: <%d> - Estado: <%d>\n", punteroIndirecto, 0);
				}

				while (i < diferencia){
					char* blockALiberarChar = (char*)mapping2 + punteroIndirecto*block_size + (bloquesALiberar*4);
					int blockALiberar = atoi(blockALiberarChar);
					bitarray_clean_bit(bitarray_mapeado, blockALiberar);
					log_info(logger, "Acceso a Bitmap - Bloque: <%d> - Estado: <%d>\n", blockALiberar, 0);
					i++;
					bloquesALiberar--;
				}
			}
		} else if (tamanio > tamanioArchivo){
//				Ampliar el tamaño del archivo: Al momento de ampliar el tamaño del archivo deberá actualizar
//				el tamaño del archivo en el FCB y se le deberán asignar tantos bloques como sea necesario para
//				poder direccionar el nuevo tamaño.

			if(cantidadBloquesNecesarios > cantidadBloquesActual){

			//Agregar los bloques que sean necesarios y modificar el bit en el bitarray a 1.
				int diferencia = cantidadBloquesNecesarios - cantidadBloquesActual;

				int i = 0;
				while (i < diferencia){
					uint32_t bloqueNuevo = 1;

					while(bitarray_test_bit(bitarray_mapeado, bloqueNuevo) != 0){
						bloqueNuevo++;
					}

					if(punteroDirecto == 0){
						punteroDirecto = bloqueNuevo;
						char pd[20];
				    	        snprintf(pd, sizeof(pd), "%d", punteroDirecto);
						config_set_value(configFCBT, "PUNTERO_DIRECTO", pd);
						bitarray_set_bit(bitarray_mapeado, bloqueNuevo);

						log_info(logger, "Acceso a Bitmap - Bloque: <%d> - Estado: <%d>\n", bloqueNuevo, 1);

						while(bitarray_test_bit(bitarray_mapeado, bloqueNuevo) != 0){
							bloqueNuevo++;
						}
						i++;
					}

					if (punteroIndirecto == 0 && cantidadBloquesNecesarios > 1){
						punteroIndirecto = bloqueNuevo;
						char pi[20];
						snprintf(pi, sizeof(pi), "%d", punteroIndirecto);
						config_set_value(configFCBT, "PUNTERO_INDIRECTO", pi);
						bitarray_set_bit(bitarray_mapeado, bloqueNuevo);

						log_info(logger, "Acceso a Bitmap - Bloque: <%d> - Estado: <%d>\n", bloqueNuevo, 1);

						while(bitarray_test_bit(bitarray_mapeado, bloqueNuevo) != 0){
							bloqueNuevo++;
						}
					}

					if (diferencia > i){
						char* block = (char*)mapping2 + punteroIndirecto*block_size + ((cantidadBloquesActual)*4);
						sprintf(block, "%d", bloqueNuevo);
						bitarray_set_bit(bitarray_mapeado, bloqueNuevo);
						log_info(logger, "Acceso a Bitmap - Bloque: <%d> - Estado: <%d>\n", bloqueNuevo, 1);
						i++;
						cantidadBloquesActual++;
					}
				}
			}
		}
	}
	config_save(configFCBT);
	printf("Config guardado\n");
}

**Comment by Luli57** [comment]
Listo, ya encontramos el problema, muchas gracias por la ayuda

**Comment by lucasdeferrari** [comment]
Queremos pedir perdón por hacerles perder el tiempo, estabamos cerrando el bitarray antes de accederlo 🙃
