### ISSUE TITLE
implementacion f_open y duda log bitmap

### ISSUE THREAD

**Issue by agusdubreucq1** [sisoputnfrba/foro#3131]
buenas, como va?
tenia unas dudas:
1) En la instruccion f_open nosotros estamos mandando la instruccion al fileSystem y este se encarga de ver si esta creado el archivo y sino lo crea, en vez de enviarle al kernel que no existe y que el kernel le vuelva a mandar otra instruccion. Estaria mal? habria que cambiarlo?

2) En el log de acceso a bitmap de FileSystem:
>Acceso a Bitmap: “Acceso a Bitmap - Bloque: <NUMERO BLOQUE> - Estado: <ESTADO>”
Nota: El estado es 0 o 1 donde 0 es libre y 1 es ocupado.

cuando desasignamos un bloque deberiamos mostrar cuando estaba ocupado o despues de liberarlo, o ambos.
entiendo que cuando asignamos un bloque y buscamos uno libre mostramos los 2 log xq son 2 accesos, uno para verificar si es 0 y otro para setearlo en 1

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Conceptualmente está mal, ya que la instrucción es abrir y después es el kernel el que solicita la creación.

2.- Con que muestren una vez alcanza, solo avisen en que momento tienen el log, si antes o después, si ponen los 2 logs, también avisen así lo tenemos en cuenta a la hora de la corrección.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Cierro el issue ya que asumo que fue resuelto.
