### ISSUE TITLE
Actualizacion tablas de segmentos

### ISSUE THREAD

**Issue by NKennedy31** [sisoputnfrba/foro#3132]
Buenas, con nuestro grupo tenemos una duda ¿Es realmente necesario mantener las tablas de segmentos actualizadas en las PCBs de los procesos o directamente se pueden mantener actualizadas desde memoria pidiendo la base para su uso antes de realizar la traducción desde CPU a Memoria? Porque luego de la compactación el actualizar las tablas de segmentos de todos los procesos nos parece innecesario si ya tenemos actualizadas todas las tablas de segmentos en memoria.

**Comment by iago64** [comment]
Buenas! Cómo va?

Si, es obligatorio porque en la CPU tiene que poder calcular la dirección física a la cual tiene que acceder en la memoria de manera autónoma.

Saludos.-
