### ISSUE TITLE
Duda sobre f_write, f_read y f_truncate

### ISSUE THREAD

**Issue by DanielBareiro** [sisoputnfrba/foro#3133]
Una consulta cuando se hace  f_write, f_read y f_truncate pueden tener mas de un proceso bloqueado para cada uno? El filesystem podria tener mas de un proceso bloqueado?

**Comment by iago64** [comment]
Buenas! Cómo va?

Es posible que se de pero van a ser de archivos diferentes, igual por las dudas checkea las pruebas que ya están publicadas

Saludos.-

**Comment by DanielBareiro** [comment]
Claro esa era mi duda, ya me fije las pruebas, muchas gracias.
