### ISSUE TITLE
duda de scripts para las pruebas

### ISSUE THREAD

**Issue by agusdubreucq1** [sisoputnfrba/foro#3135]
buenas, tengo dudas de como es el script para correr las consolas a la vez. 
por ejemplo en las pruebas de HRRN nosotros estamos usando para probar lo siguiente:
`./Consola /home/utnso/tp-2023-1c-Simple-y-Funciona/config/Consola.config /home/utnso/tp-2023-1c-Simple-y-Funciona/pseudocodigo/BASE_1 & ./Consola /home/utnso/tp-2023-1c-Simple-y-Funciona/config/Consola.config /home/utnso/tp-2023-1c-Simple-y-Funciona/pseudocodigo/BASE_2 & ./Consola /home/utnso/tp-2023-1c-Simple-y-Funciona/config/Consola.config /home/utnso/tp-2023-1c-Simple-y-Funciona/pseudocodigo/BASE_2`

pero esto hace que se conecte kernel primero el proceso que tiene el archivo BASE_2
si pongo el proceso con el archivo BASE_1 al final, es el primero que ejecuta y funcionaria todo bien.

esto funciona asi? o es algo raro?
pregunto para saber como son los scripts que se corren en la entrega.
saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

Lo que van a hacer en la entrega es tener mas de una ventana para correr consolas (precisamente 1 por cada módulo consola)
Y lo que hacen es lanzar de a 1 las consolas, en el caso de que prueben con la VM con entorno gráfico, pueden dividir la terminal terminator que les permite ir dividiéndola haciendo click derecho.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Cierro el issue ya que asumo que fue resuelto.
