### ISSUE TITLE
Consutla sobre pruebas de MEMORIA

### ISSUE THREAD

**Issue by ezequielmalfonso** [sisoputnfrba/foro#3136]
Buenas noches, una consulta, en las prueba de memoria, que algoritmo iría, porque en las config de las pruebas indican los 3 separados de barras, eso indicaría que para memoria hay que correrlo con los 3 algoritmos?

Gracias.-

**Comment by iago64** [comment]
Buenas, Cómo va?

Van a correr 3 veces la prueba, una por cada algoritmo 😄 

Saludos.-

**Comment by ezequielmalfonso** [comment]
Gracias, era para confirmar.

**Comment by ezequielmalfonso** [comment]
@iago64 una consulta, cuando corremos con el algoritmo WORST, nos da que no hay espacio en memoria, puede ser que sea así o también tiene que finalizar bien como los otros dos algoritmos.
Gracias.-

**Comment by LeandroCarbajales** [comment]
Buenas!
Con el algoritmos WORST FIT debería forzar una compactación debido a que hay espacio suficiente en memoria pero no está contiguo.

**Comment by ezequielmalfonso** [comment]
Gracias, si tenias unas cosas mal ese ese algoritmo.

**Comment by LeandroCarbajales** [comment]
Genial :)
Cierro el issue ya que asumo que fue resuelta la duda, cualquier cosa lo pueden volver a abrir.
