### ISSUE TITLE
Duda pruebas de memoria y deploy

### ISSUE THREAD

**Issue by tomasmartinez02** [sisoputnfrba/foro#3137]
Buenas, estábamos probando y notamos que con los scripts actuales, en las pruebas de memoria solo se necesita compactar cuando el algoritmo es worst, es correcto?
Por otro lado, estamos preparando unos archivos .sh para agilizar el deploy y en nuestras maquinas no nos deja ejecutarlo salvo que le demos permisos a través del siguiente comando:
`chmod +x nombrearchivo.sh `
No hay problema con esto?
También queríamos saber en cuantas computadoras se prueba y que hay que abrir en cada una, ya que en esta semana queremos practicar el deploy antes de la entrega.
Saludos.

**Comment by iago64** [comment]
Buenas! Cómo va?

La prueba de memoria habría que ver en que momento hacen la compactación y como les quedan las asignaciones en Best y First, pero está bien que compacten solo en worst 😉 
Respecto al `chmod +x `de los scripts, no hay problema.

Saludos.-

**Comment by tomasmartinez02** [comment]
Genial gracias! Una pregunta mas, leí que la prueba se corre con un stack para chequear la memoria, como podemos poner ese stack para cuando practiquemos?

**Comment by LeandroCarbajales** [comment]
Buenas!
Pueden chequear el uso de memoria en todo momento con `htop` desde la terminal.
Las pruebas recomendaría que las prueben en al menos 3 máquinas/VMs, por ejemplo: [Consolas, Kernel+CPU, Mem+FS]

Saludos!
      Lean

**Comment by tomasmartinez02** [comment]
Gracias!
