### ISSUE TITLE
Problema al conectar los modulos en la VM server

### ISSUE THREAD

**Issue by vamanfredi** [sisoputnfrba/foro#3138]
Buenas noches, tenemos un inconveniente al correr los modulos de la siguiente manera :    **./nombreArchivo.out** en la VM server. Nos tira un segfault al conectar los modulos, cosa que en la VM grafica no nos ocurre. Tambien tenemos la siguiente regla de makefile para correr un modulo:

.PHONY: run
run: $(BIN)
	./$(BIN) $(ARGS)

Al correr con esta regla, si funciona todo correcto y pasa las pruebas, pero la verdad no encontramos la diferencia entre esto y correr directamente el tp con el "./"

### 📦 Especificaciones de la VM
- Versión de VirtualBox: 
- Memoria RAM asignada:

### 🖥️ Especificaciones del host
- Sistema Operativo y versión:
- Memoria RAM:
- Procesador:

**Comment by iago64** [comment]
Buenas! Cómo va?

Consulta, cuando lo corren con ./ le están pasando los argumentos que espera el programa? Porque me da la sensación que les tira un segfault furioso porque espera que le llegue algún parámetro como ser el archivo de config y al no llegarles explota por los aires.

Saludos.-

**Comment by vamanfredi** [comment]
@iago64  El programa no estaba esperando ningún parámetro. En la vm con interfaz gráfica si nos funciona el ./

**Comment by RaniAgus** [comment]
¡Buenas! ¿Podrían mostrarnos qué les imprime el makefile después de ejecutar `make run` y antes de que el módulo empiece a imprimir cosas por pantalla? Saludos

**Comment by vamanfredi** [comment]
@RaniAgus Buen día, te dejo lo que nos imprime:

utnso@utnso:~/tp-2023-1c-Kernel-Liquidators/memoria$ make run
./bin/memoria.out 
[INFO] 13:05:58:227 log_memoria/(223096:223096): INICIO MEMORIA

**Comment by vamanfredi** [comment]
@RaniAgus Si, tenemos rutas relativas, pero lo estamos ejecutando de la misma forma que el makefile ./bin/memoria.out
Estaría funcionando en la vm de xubuntu, pero en la vm server se nos cae todo cuando conectamos el último módulo (sin mandar ninguna consola).

**Comment by RaniAgus** [comment]
De ser así les recomiendo correrlo con Valgrind en la VM server para ver en qué línea se produce el seg fault. Ambas VMs parten desde la misma imagen base (una [Ubuntu Server 22.04 LTS](https://ubuntu.com/download/server)), por lo que no debería haber diferencia entre una y otra.

**Comment by vamanfredi** [comment]
@RaniAgus Estamos corriendo valgrind manualmente de la siguiente manera:
valgrind --leak-check=full --track-origins=yes --log-file="memcheck.log" ./bin/cpu.out
y no se produce el segfault, no sé si tendria que pasar algún otro parámetro

**Comment by vamanfredi** [comment]
@RaniAgus En memcheck.log me aparecen 272 bytes en possibly lost por cada hilo que iniciamos en pthread_create, después nada raro. Corriendo con hellgrind tampoco tira segfault y el log tampoco me muestra ningún error.

**Comment by RaniAgus** [comment]
¿En ambos lugares están usando la misma config, o hay algún parámetro que cambie entre uno y el otro?

**Comment by vamanfredi** [comment]
@RaniAgus estamos probando con el mismo archivo de config, ya que lo traemos directo del repo, igualmente probamos con el hexdump y  cat -A para ver si había algún caracter raro, pero no hay.
