### ISSUE TITLE
Duda sobre los paths en la config de FS

### ISSUE THREAD

**Issue by FacundoPiaggio** [sisoputnfrba/foro#3140]
Buenas!

Vi que en el issue #3127 mencionaron que se puede agregar algunos parametros a los archivos de configuracion, por ejemplo la IP del modulo propio.
Mi duda es sobre los paths a las diferentes estructuras de FS.
Nosotros en nuestro archivo orginial lo tenemos de la siguiente manera:
`PATH_SUPERBLOQUE=drive/superbloque.dat`
`PATH_BITMAP=drive/bitmap.dat`
`PATH_BLOQUES=drive/bloques.dat`
`PATH_FCB=drive/fcb`
Pero noté que en las config de las pruebas se ve mas así:
`PATH_SUPERBLOQUE=~/fs/sbloque.dat`
`PATH_BITMAP=~/fs/bitmap.dat`
`PATH_BLOQUES=~/fs/bloques.dat`
`PATH_FCB=~/fs/fcb`

Hay algun inconveniente con la forma en la que pasamos el path? En nuestro caso, el directorio"drive" es un dir que esta dentro de: carpetaDelTp/fs.
es decir se veria algo asi: carpetaDelTp/fs/drive/

**Comment by LeandroCarbajales** [comment]
Buenas!
Esos path son un ejemplo al igual que las IP, están para que los cambien con el path que corresponda :)

Saludos!
        Lean

**Comment by FacundoPiaggio** [comment]
Genial lean, muchas gracias!
