### ISSUE TITLE
Problemas con pruebas de MEMORIA

### ISSUE THREAD

**Issue by D-M-Gonzalez** [sisoputnfrba/foro#3141]
Buenas!

Tenemos una duda con las pruebas de memoria, queremos saber cuales son los comportamientos esperados para las pruebas de memoria.

Inicialmente, tenemos [RA1,RB0,RC0] como recursos disponibles, pero al terminar la ejecución nos queda [RA1,RB1,RC0].
Esto nos sucede porque, al ejecutar P1, este hace un SIGNAL antes de que P2 ( quien consume los RB ) llegue a hacer un WAIT, por lo que al finalizar P2 libera sus instancias de RB y nos queda una más que la inicial.

Creemos que este comportamiento es esperado, debido a que el P2 esta liberando correctamente los 4 RB que consumio, y que P1 al hacer un SIGNAL de un recurso en 0, cambio el estado incial del Kernel generando un recurso de la nada.

¿Esta bien lo que estamos pensando?

**Comment by LeandroCarbajales** [comment]
Buenas!
Ese comportamiento es esperado, lo más importante es que los procesos ejecuten en el orden correcto que determinan estos semáforos "binarios" :)

Saludos!
      Lean

**Comment by D-M-Gonzalez** [comment]
Excelente!

Seguimos con las pruebas entonces. Si, por lo que vimos necesitan de un orden específico para no dar errores.
