### ISSUE TITLE
Duda sobre las rutas para las pruebas

### ISSUE THREAD

**Issue by ZoeGolfieri** [sisoputnfrba/foro#3142]
Hola! Tenemos dudas sobre como deben estar las rutas cuando corremos las pruebas en el laboratorio. 
Por ejemplo tenemos la siguiente en el config:
config = config_create("/home/utnso/tp-2023-1c-Los-operadores/Memoria/memoria.config");
Esta bien así? Ya que al clonar el repositorio en el laboratorio no sabemos si existirán las 2 primeras carpetas con esos nombres.
Además tenemos de esta forma en el script:
./Consola "../consola.config" "/home/utnso/tp-2023-1c-Los-operadores/Consola/pruebaBase/base1.txt" 
También deberíamos cambiarlas? 
Gracias

**Comment by LeandroCarbajales** [comment]
Buenas!
Las pruebas se van a correr sobre la misma VM sin interfaz gráfica que tienen disponible, por lo que llegado el caso pueden corroborarlo probándolo en esa VM :)
De cualquier manera te respondo que sí, "/home/utnso" existe en ambas VMs.

Saludos!
       Lean

**Comment by ZoeGolfieri** [comment]
Buenisimo, gracias!
Tambien te consulto porque estamos teniendo un problema para correr las Vms con putty. Tenemos distintos ips en cada maquina virtual y al ingresar a putty ponemos ese ip de cada una pero un mismo puerto para todas.
Al querer correr los modulos nos salta este error:
OpenSSH_8.9p1 Ubuntu-3 Invalid SSH identification string. 
Ya configuramos las configs con el nuevo ip y puerto, pero no se nos conectan los modulos entre ellos.

**Comment by LeandroCarbajales** [comment]
Buenas!
Por lo pronto ese mensaje de error supondría que es independiente de que los módulos no se puedan conectar.
Podrías subir imágenes de la configuración de red con la que están levantando las VMs y de la configuración de Putty antes de conectarse a una de ellas?

**Comment by ZoeGolfieri** [comment]
Si obvio!
![image](https://github.com/sisoputnfrba/foro/assets/102538296/09edceb7-5b29-4819-84ec-71e6fd55b4ba)
![image](https://github.com/sisoputnfrba/foro/assets/102538296/9b5e67e2-9b7b-4e20-8726-8d6e347ba4df)

**Comment by LeandroCarbajales** [comment]
Mmm parecería estar bien la config de red. Esto mismo le pasa a alguien más del grupo?
Y para chequear lo de las conexiones, el mensaje `OpenSSH_8.9p1 Ubuntu-3 Invalid SSH identification string.` sale recién cuando un módulo intenta conectarse a otro módulo (de otra VM?).

**Comment by ZoeGolfieri** [comment]
Sisi, es en ese momento!

**Comment by iago64** [comment]
Buenas! Cómo va?

Me llama muchísimo la atención que el problema de SSH se los tire en su tp ya que no deberían tener nada sobre SSH, solo para confirmar, el error lo tienen al levantar los procesos o al conectarse con putty a la VM?

Si es problema al momento de conectarse a la VM, por las dudas levanten la vm y desde la ventana que les genera VirtualBox corran el siguiente comando:
```bash
curl -fsSL https://faq.utnso.com.ar/fluship.sh | sh -x
```
Es una fiaca escribirlo porque no hay autocompletado, pero una vez que termine reinicien la VM y prueben nuevamente y nos confirman.

Saludos.-

**Comment by ZoeGolfieri** [comment]
El error nos salta cuando corremos por ejemplo CPU que se conecta a memoria. Ni bien corremos memoria no nos salta. 
Ese comando lo corrimos sin el -x ya que no se no nos cambiaban los ips y lo vimos en otro issue! Corriéndolo con el -x haría otra cosa? Igualmente ahora lo pruebo. Gracias!

**Comment by iago64** [comment]
Buenas!

El -x hace que se ejecute el script :)

Igual para confirmar, ¿Les pasa a todos los integrantes del grupo? ¿Solo les pasa si corren desde putty o si lo corren por ejemplo directo de la VM funciona?

Saludos.-

**Comment by ZoeGolfieri** [comment]
Ahora lo hacemos en otras y les aviso! Pero si, solo en putty. En la VM nos sigue corriendo bien. 
El problema solo saltó cuando un módulo le mandaba algo al otro en putty

**Comment by iago64** [comment]
Buenas! 

Solo para checkear una cosita más, en que puerto están levantando los módulos, en los 8000 y algo o en el 22? Podes subir los config de los módulos?

Saludos.-

**Comment by ZoeGolfieri** [comment]
Todos en el 22, que es el que estaba en putty.

Config memoria
PUERTO_ESCUCHA=22
TAM_MEMORIA=512
TAM_SEGMENTO_0=128
CANT_SEGMENTOS=16
RETARDO_MEMORIA=1000
RETARDO_COMPACTACION=30000
ALGORITMO_ASIGNACION=FIRST

Kernel config
IP_MEMORIA=192.168.0.242
PUERTO_MEMORIA=22
IP_FILESYSTEM=192.168.0.243
PUERTO_FILESYSTEM=22
IP_CPU=192.168.0.244
PUERTO_CPU=22
PUERTO_ESCUCHA=22
ALGORITMO_PLANIFICACION=FIFO
ESTIMACION_INICIAL=10000
HRRN_ALFA=0.5
GRADO_MAX_MULTIPROGRAMACION=12
RECURSOS=[RA, RB]
INSTANCIAS_RECURSOS=[1, 0]

Filesystem config
IP_MEMORIA=192.168.0.242
PUERTO_MEMORIA=22
PUERTO_ESCUCHA=22
RETARDO_ACCESO_BLOQUE=15000
PATH_SUPERBLOQUE=/home/utnso/tp-2023-1c-Los-operadores/FileSystem/superbloque.dat
PATH_BITMAP=/home/utnso/tp-2023-1c-Los-operadores/FileSystem/bitmap.dat
PATH_BLOQUES=/home/utnso/tp-2023-1c-Los-operadores/FileSystem/bloques.dat
PATH_FCB=/home/utnso/tp-2023-1c-Los-operadores/FileSystem/fcb

CPU config
RETARDO_INSTRUCCION=1000
IP_MEMORIA=192.168.0.242
PUERTO_MEMORIA=22
PUERTO_ESCUCHA=22
TAM_MAX_SEGMENTO=256

Consola config
IP_KERNEL=192.168.0.245
PUERTO_KERNEL=22

**Comment by iago64** [comment]
Buenas! Cómo va?

Ahi esta el problema, el puerto 22 es un puerto "reservado", como casi cualquier puerto abajo de 1024, por eso les pusimos siempre en los configs los puertos 8000, 8001, 8002, etc.

Ademas de eso, es importante que los puertos entre los módulos sean diferentes asi no se chocan y no tenemos esta situación:
![image](https://github.com/sisoputnfrba/foro/assets/1622109/a44fe1dc-84af-45e4-90cd-3b541a4606f6)

Esto les explota cuando corren por putty, justamente porque el putty se conecta al puerto 22 y este queda configurado para conexiones SSH, cosa que en el tp, no hacen, por lo cual, para resolver el problema, prueben de poner puertos como los que están en los ejemplos (8000 al 8010 por ejemplo)

Saludos.-

**Comment by ZoeGolfieri** [comment]
Ahhh buenooo! Muchas gracias y mil disculpas. Buenas noches
