### ISSUE TITLE
Pruebas de deploy - Misma IP en todas las VM's

### ISSUE THREAD

**Issue by lucaschiesa01** [sisoputnfrba/foro#3143]
Estamos haciendo las pruebas de deploy en nuestra maquina local para antes de ir a medrano a probarlo. Logramos hacer correr los modulos independientemente pero cuando se tiene que conectar pincha.

Cuando hicimos el ifconfig nos tira la misma ip en todas las vm's siguiendo la guia de deploy (no estamos seguros si esto es esperado o no). Adjunto imagenes con los ifconfig y el .config de file-system con las 2 ips asignadas.

![image](https://github.com/sisoputnfrba/foro/assets/43383862/a5059958-9f49-4e1f-96a3-51a1a175a53b)

![image](https://github.com/sisoputnfrba/foro/assets/43383862/50a6a1ce-3ea3-4e4f-bbc6-b720d1f27767)

De yapa, agrego que en nuestro caso cuando copiamos nuestra shared library en /usr/local/lib y /usr/local/include como esta especificado en la guia de despliegue no nos funciono. Sin embargo, cuando lo copiamos en /usr/lib y /usr/include si nos funciono.

**Comment by RaniAgus** [comment]
¡Buenas!
No, no es lo esperado que las VMs tengan todas la misma IP. Prueben de ejecutar este script con el fix y luego reinicien:
```sh
curl -fsSL https://faq.utnso.com.ar/fluship.sh | bash
```

Ahí actualizo la guía de deploy con estos detalles que nos comentaron, ahí corroboré y efectivamente al parecer no se puede usar `/usr/local` sin configurar el linker para que tome esas rutas.

Saludos

**Comment by MiltonMartorello** [comment]
Buenas @RaniAgus. A nosotros no nos funciona el script. Si bien ejecuta, nos sucede que al reiniciar la vm. Sigue teniendo la misma IP que antes. Y abriendo vms clonadas siguen teniendo todas la misma. Lo estuvimos probando en las máquinas del labo también y no parece darnos bola. Entiendo que mañana vamos a probar el tp en una cantidad limitada de máquinas. En ese caso nos ayudan ustedes a cambiarles la IP? Probamos también con distintos adaptadores y no hay caso. 
Gracias. Saludos.

**Comment by RaniAgus** [comment]
Oops... Probemos otro método:
```
sudo dhclient -r
sudo dhclient
```
Sería primero liberar la IP y luego pedir una nueva

**Comment by MiltonMartorello** [comment]
Holis @RaniAgus, lamentablemente no nos funcionó. Terminamos haciendo las pruebas en 5 pcs distintas

**Comment by Mimito164** [comment]
Si sirve como dato, esto también me sucedió a mi y depende en gran medida del router o del proveedor de internet. Es decir, **prueben en otras casas o en otros lugares**.

_(a mi tampoco me funcionó el script de la catedra para arreglar las ip)_

Yo tuve la oportunidad de probar el despliegue en mi laptop (misma config) en diferentes lugares (osea diferentes conexiones a internet) con diferentes resultados (en algúnos funcionaba bien y en otros las vms tenían la misma IP).

Dejo también este link:
https://blogs.oracle.com/scoter/post/oracle-vm-virtualbox-networking-options-and-how-to-manage-them
Me sirvió para entender un poco las settings de network de virtual box aunque no tuve tiempo para investigar más. Aparte, al final con bridged pude hacerlo andar. De ser posible estaría bueno no depender del router, creo que vbox permite una conexión local entre vm's sin necesidad de depender del router (Host-Only Networking o internal network).

@LeandroCarbajales @RaniAgus @MiltonMartorello

**Comment by RaniAgus** [comment]
¡Gracias por el dato @Mimito164!

También, por si sirve, hace poco en #3378 descubrimos que este tema de las asignaciones de IPs repetidas puede deberse a que ambas máquinas tienen el mismo machine id. 

Prueben de ejecutar las 3 líneas que están en el issue, que también las dejamos hace ya unas semanas en la última etapa del TP0 para [resolver conflictos de red](https://docs.utnso.com.ar/primeros-pasos/tp0#resolver-conflictos-de-red).

Saludos
