### ISSUE TITLE
Error al hacer el deploy

### ISSUE THREAD

**Issue by SolGarciaLinfozzi** [sisoputnfrba/foro#3144]
Buen día, estamos teniendo problemas para poder hacer el deploy del tp, logramos poder levantar cada módulo por separado pero no se conectan entre sí.
Para las conexiones usamos IPs y puertos distintos para cada módulo. 

![image](https://github.com/sisoputnfrba/foro/assets/102705958/d1c8ac21-9ef2-475b-8023-80f75c3e5364)

En la foto se ve como levantamos cada módulo, funciona, pero en ese momento se tendría que conectar FS con Memoria automáticamente y nunca se conecta.

Estos son los configs que tenemos:
Config memoria
PUERTO_ESCUCHA=8002
TAM_MEMORIA=512
TAM_SEGMENTO_0=128
CANT_SEGMENTOS=16
RETARDO_MEMORIA=1000
RETARDO_COMPACTACION=30000
ALGORITMO_ASIGNACION=FIRST

Kernel config
IP_MEMORIA=192.168.0.242
PUERTO_MEMORIA=8002
IP_FILESYSTEM=192.168.0.243
PUERTO_FILESYSTEM=8003
IP_CPU=192.168.0.244
PUERTO_CPU=8001
PUERTO_ESCUCHA=8000
ALGORITMO_PLANIFICACION=FIFO
ESTIMACION_INICIAL=10000
HRRN_ALFA=0.5
GRADO_MAX_MULTIPROGRAMACION=12
RECURSOS=[RA, RB]
INSTANCIAS_RECURSOS=[1, 0]

Filesystem config
IP_MEMORIA=192.168.0.242
PUERTO_MEMORIA=8002
PUERTO_ESCUCHA=8003
RETARDO_ACCESO_BLOQUE=15000
PATH_SUPERBLOQUE=/home/utnso/tp-2023-1c-Los-operadores/FileSystem/superbloque.dat
PATH_BITMAP=/home/utnso/tp-2023-1c-Los-operadores/FileSystem/bitmap.dat
PATH_BLOQUES=/home/utnso/tp-2023-1c-Los-operadores/FileSystem/bloques.dat
PATH_FCB=/home/utnso/tp-2023-1c-Los-operadores/FileSystem/fcb

CPU config
RETARDO_INSTRUCCION=1000
IP_MEMORIA=192.168.0.242
PUERTO_MEMORIA=22
PUERTO_ESCUCHA=22
TAM_MAX_SEGMENTO=256

Consola config
IP_KERNEL=192.168.0.245
PUERTO_KERNEL=8000

![image](https://github.com/sisoputnfrba/foro/assets/102705958/15f820d5-540c-4e00-8fa9-642f58cebcb4)

Te envío esta foto con la corroboramos que los puertos y IPs son correctos.

**Comment by LeandroCarbajales** [comment]
Buenas!
Veo que cuando levantan sus servidores, en "utils.h" todos tienen hardcodeado algo como:

```c
#define IP "127.0.0.1"
#define PUERTO "8001"
```
Y luego en utils.c:
```c 
getaddrinfo(IP, PUERTO, &hints, &servinfo);
```
Esto significa que el servidor escuche _solamente_ conexiones entrantes desde "127.0.0.1" (localhost, es decir, desde esa misma VM), seteando ese primer parámetro como NULL debería funcionar. Luego, el puerto no creo que traiga problema tenerlo en código porque son distintos, pero es recomendable usar el puerto pasado por config (para eso está el puerto_escucha).

Luego, usen el puerto 22 **únicamente** para conectarse con putty, el CPU config quedó seteado para conectarse a ese puerto :P

Saludos!
        Lean

**Comment by SolGarciaLinfozzi** [comment]
Muchas gracias, ya corregimos eso del código, pero nos sigue saltando el mismo error, nos levantan los módulos pero no se conectan correctamente.
Perdón, no nos quedó claro, en la configuración de putty al configurar cada módulo debo poner el puerto que tengo en las configs o ahí va el 22 siempre? Si va el 22, dónde asigno el puerto de cada módulo ?? Ya que no entendemos sino como se asocia el puerto con el que pusimos en las configs
