### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by tomasmartinez02** [sisoputnfrba/foro#3146]
Buenas, estábamos ensayando las pruebas y queríamos ver lo de los memory leaks. En valgrind, como programadores solo nos interesan los definetly lost no? Es decir, no deberíamos preocuparnos por los possibly lost?
Gracias y saludos.

**Comment by RaniAgus** [comment]
¡Buenas! Justo comentamos esto en la última sección de la [guía de Valgrind](https://docs.utnso.com.ar/guias/herramientas/valgrind#los-leaks-que-no-son), si hay algo que no queda claro avísennos ;)
Saludos

**Comment by LeandroCarbajales** [comment]
Cierro el issue ya que asumo que fue resuelto.
