### ISSUE TITLE
Filesystem Paths

### ISSUE THREAD

**Issue by LucasThier** [sisoputnfrba/foro#3147]
Hola buenas tardes, tengo una consulta sobre los path en el archivo de config de filesystem
![image](https://github.com/sisoputnfrba/foro/assets/106763411/cc98f6f4-c201-4b8d-a5ad-437d42546a7d)

1. Son paths relativas o absolutas?
2. Si o si tiene que ser esa ruta o podemos modificarlas para mayor comodidad?
3. Si la respuesta de la 2 es no, los directorios ya existiran en la vm o hay que crearlos? si hay que crearlos, se crean  manualmente o por codigo?

Por ejemplo el archivo de superbloque se encuentra en el directorio de "~/fs/Superbloque.dat", en la VM de la entrega, la carpeta "~/fs" o el archivo "~/fs/Superbloque.dat" ya existen?

**Comment by LeandroCarbajales** [comment]
Buenas!
Respondido en #3140 :)

**Comment by LucasThier** [comment]
ah perfecto gracias
