### ISSUE TITLE
Tema con las pruebas de ERROR_3 y ERROR_4

### ISSUE THREAD

**Issue by D-M-Gonzalez** [sisoputnfrba/foro#3148]
Buenas!

La prueba ERROR_3 tiene las siguientes intrucciones:
SET AX HOLA
SET RAX MappaLlegaEl2c23
MOV_OUT 124 AX
MOV_IN BX 124
MOV_OUT 120 RAX
MOV_IN RBX 120
EXIT

La prueba ERROR_4 tiene las siguientes intrucciones:
CREATE_SEGMENT 1 256
CREATE_SEGMENT 2 256
CREATE_SEGMENT 3 256
CREATE_SEGMENT 4 256
EXIT

Con los config:
Memoria.config
PUERTO_ESCUCHA=8002
TAM_MEMORIA=4096
TAM_SEGMENTO_0=128
CANT_SEGMENTOS=16
RETARDO_MEMORIA=1000
RETARDO_COMPACTACION=60000
ALGORITMO_ASIGNACION=BEST

CPU.config
RETARDO_INSTRUCCION=1000
IP_MEMORIA=127.0.0.1
PUERTO_MEMORIA=8002
PUERTO_ESCUCHA=8001
TAM_MAX_SEGMENTO=128

Cito la consigna:
**No se solicitará nunca la creación de un segmento con tamaño mayor al máximo configurado en el sistema.**
No se solicitará la creación de un segmento de un Id inválido (0 o mayor o igual al Id máximo).
No se solicitará la creación de un segmento que se encuentre con un tamaño distinto a 0 (es decir, ya creado)

1) El ERROR_3 en todos los casos accede al segmento 0, que es parte del proceso siempre porque es el compartido. ( num_segmento = floor(dir_logica (124) / tam_max_segmento (128)) = 0 ). Porque debería dar SEG_FAULT?
2) El tamaño maximo es 128, ustedes dijeron que no se iba a solicitar crear un segmento mayor al máximo, ahí pide uno de 256 y debería decir OUT_OF_MEMORY?? Esta mal esto no?

**Comment by iago64** [comment]
Buenas! Cómo va?

Gracias por el aviso, cuando copiamos los configs nos olvidamos de ajustar el del tamaño maximo de la CPU para que sea 256.
Respecto al SEG_FAULT, RAX es un registro de 16 bytes y lo estas queriendo grabar a partir del byte 120 y solo te quedan 8 del segmento, es decir que te pasas por 8.

Saludos.-

**Comment by D-M-Gonzalez** [comment]
Genial, muchas gracias! se nos había pasado eso. Ya lo estamos corrigiendo.

Saludos
