### ISSUE TITLE
Consulta FS cuando un archivo pide un bloque que previamente habia sido ocupado

### ISSUE THREAD

**Issue by FacundoPiaggio** [sisoputnfrba/foro#3149]
Buenas, tenemos una duda.

¿Cuando se agranda un archivo hay que blanquear/limpiar los bytes que se estuvieran alocando? si previamente hubiera un archivo que estuviera ocupando dichos bloques, al archivo le quedaría basura.

Por ejemplo: archivo1 pide un bloque que previamente estaba ocupado por archivo2, pero el bloque tiene cosas escritas por el archivo2.

Muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

No, no hace falta, si hay basura la dejan ahí y de ultima de sobre escribe.

Saludos.-

**Comment by FacundoPiaggio** [comment]
Excelente dami, muchas gracias!
