### ISSUE TITLE
Consulta para el Seteo de IPs en Configs

### ISSUE THREAD

**Issue by MiltonMartorello** [sisoputnfrba/foro#3150]
Holis como va? 
hoy hicimos el simulacro de deploy y detectamos que nos consume muchísimo tiempo el seteo de IPs en las configs. Tenemos un archivo config para cada una de las pruebas y teniendo en cuenta que son varios módulos y varias pruebas se va mucho tiempo.

Se nos ocurrió desacoplar la IP de la config general y llevarla a un archivo que sea seteable por módulo. En este escenario podemos reducir los cambios a 1 por módulo.

Es viable hacerlo así? o si o si la IP tiene que salir del mismo archivo config juntos os demás parámetros

Gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

No hay problema, si eso les facilita el despliegue hagan el cambio, es mejor para todos 😉 

Saludos.-
