### ISSUE TITLE
Concurrencia y Serialización estática

### ISSUE THREAD

**Issue by BrunoRizzo765** [sisoputnfrba/foro#3152]
Tengo un par de dudas sobre concurrencia y serialización:

(void esperar_clientes()) A la hora de querer implementar el requerimiento de que se le avise a consola cuando finaliza su proceso, no cerramos la conexión con esta hasta que el proceso finalice. Esto generó que deje de haber concurrencia ya que el segundo proceso queda esperando en  esperar_cliente(socket_servidor); hasta que finalice el primer proceso. Antes de querer implementar esto había concurrencia, pero en ese caso cerrábamos la conexión y no podíamos indicarle que había finalizado el proceso.

(instruction_set) La otra duda es sobre la serialización de la lista de instrucciones, queríamos saber si podríamos hacer las instrucciones de tipo estático es decir poner un valor máximo al char de la instrucción y a los parámetros. En este momento lo hacemos de manera dinámica, pero esto nos trae problemas a la hora de mandar el pcb por segunda vez a CPU y la lista viaja con contenido basura. 

### 📝 Código relevante

```c
    typedef struct
    {
          char *instruccion;
          char **params;
    } instruction_set;


void esperar_clientes() {
    int socket_servidor = crear_servidor(ip,puerto_escucha);

    while (1) {
        log_info(logger, "Esperar Cliente...");
        int socket_cliente = esperar_cliente(socket_servidor);

        if (socket_cliente == -1) {
            perror("Error al aceptar la conexión del cliente");
            exit(EXIT_FAILURE);
        }

        int op_code = recibir_operacion(socket_cliente);
        switch (op_code){
            case PAQUETE_INSTRUCCIONES:
                t_list* instrucciones = recibir_instrucciones(socket_cliente);
                t_pcb* pcb_nuevo = crear_pcb(instrucciones, socket_cliente);
                agregar_pcb_cola_nuevos(pcb_nuevo);
                //list_destroy(instrucciones);
                break;
            default: 
                log_error(logger, "El codigo de operacion recibido es inválido");
                break;
        }
    }
    close(socket_servidor);
}
```

**Comment by RaniAgus** [comment]
¡Buenas!

1. Lo que pueden hacer es, basándose en cómo lo tenían implementado antes, hacer un `send()` antes de cerrar la conexión. Recuerden de la [guía de sockets](https://docs.utnso.com.ar/guias/linux/sockets) que la conexión por sockets es bidireccional, por lo que ambos pares pueden hacer `send()` y `recv()`.

2. No deberían tener problemas para serializar o deserializar una estructura dinámica, les aconsejo volver a revisar la [guía de serialización](https://docs.utnso.com.ar/guias/linux/serializacion) y si tienen algún problema con esas funciones avísennos y los ayudamos a revisarlas; aunque antes de eso les recomiendo usar el [debugger](https://docs.utnso.com.ar/guias/herramientas/debugger).

Saludos

**Comment by BrunoRizzo765** [comment]
Gracias por la respuesta. 
En el tema de concurrencia cuando nosotros cerrábamos la conexión con la consola lo hacíamos luego de crear el pcb, por lo que si le mandamos un mensaje en ese momento diciendo que termino el proceso no seria cierto.  Abajo están los logs de kernel en este momento.

**LOGS Concurrencia**

Esto pasa en kernel con la concurrencia espera a que termine uno para que entre otro:

[INFO] 14:13:55:690 KERNEL/(212074:212074): Esperar Cliente...
[INFO] 14:13:59:266 KERNEL/(212074:212074): Esperar Cliente...
[INFO] 14:13:59:269 KERNEL/(212074:212116): Cliente conectado
[INFO] 14:13:59:274 KERNEL/(212074:212075): Cola Ready FIFO: [0]

[INFO] 14:13:59:274 KERNEL/(212074:212075): PID: 0 - Estado Anterior: NEW - Estado Actual: READY

[INFO] 14:13:59:274 KERNEL/(212074:212076): PID: 0 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 14:13:59:275 KERNEL/(212074:212076): PID: 0 - Yield 

[INFO] 14:13:59:275 KERNEL/(212074:212076): PID: 0 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 14:13:59:275 KERNEL/(212074:212076): Cola Ready FIFO: [0]

[INFO] 14:13:59:275 KERNEL/(212074:212076): PID: 0 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 14:13:59:276 KERNEL/(212074:212076): Finaliza el proceso 0 - Motivo: SUCCESS

[INFO] 14:13:59:276 KERNEL/(212074:212076): PID: 0 - Estado Anterior: EXEC - Estado Actual: EXIT

[INFO] 14:13:59:286 KERNEL/(212074:212074): Esperar Cliente...
[INFO] 14:13:59:286 KERNEL/(212074:212120): Cliente conectado
[INFO] 14:13:59:286 KERNEL/(212074:212075): Cola Ready FIFO: [1]

[INFO] 14:13:59:286 KERNEL/(212074:212075): PID: 1 - Estado Anterior: NEW - Estado Actual: READY

[INFO] 14:13:59:286 KERNEL/(212074:212076): PID: 1 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 14:13:59:287 KERNEL/(212074:212076): PID: 1 - Yield 

[INFO] 14:13:59:287 KERNEL/(212074:212076): PID: 1 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 14:13:59:287 KERNEL/(212074:212076): Cola Ready FIFO: [1]

[INFO] 14:13:59:287 KERNEL/(212074:212076): PID: 1 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 14:13:59:288 KERNEL/(212074:212076): PID: 1 - Yield 

[INFO] 14:13:59:288 KERNEL/(212074:212076): PID: 1 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 14:13:59:288 KERNEL/(212074:212076): Cola Ready FIFO: [1]

[INFO] 14:13:59:288 KERNEL/(212074:212076): PID: 1 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 14:13:59:288 KERNEL/(212074:212076): PID: 1 - Yield 

[INFO] 14:13:59:289 KERNEL/(212074:212076): PID: 1 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 14:13:59:289 KERNEL/(212074:212076): Cola Ready FIFO: [1]

[INFO] 14:13:59:289 KERNEL/(212074:212076): PID: 1 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 14:13:59:289 KERNEL/(212074:212076): PID: 1 - Yield 

[INFO] 14:13:59:289 KERNEL/(212074:212076): PID: 1 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 14:13:59:289 KERNEL/(212074:212076): Cola Ready FIFO: [1]

[INFO] 14:13:59:289 KERNEL/(212074:212076): PID: 1 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 14:13:59:290 KERNEL/(212074:212076): PID: 1 - Yield 

[INFO] 14:13:59:290 KERNEL/(212074:212076): PID: 1 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 14:13:59:290 KERNEL/(212074:212076): Cola Ready FIFO: [1]

[INFO] 14:13:59:290 KERNEL/(212074:212076): PID: 1 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 14:13:59:291 KERNEL/(212074:212076): PID: 1 - Yield 

[INFO] 14:13:59:291 KERNEL/(212074:212076): PID: 1 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 14:13:59:291 KERNEL/(212074:212076): Cola Ready FIFO: [1]

[INFO] 14:13:59:291 KERNEL/(212074:212076): PID: 1 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 14:13:59:291 KERNEL/(212074:212076): PID: 1 - Yield 

[INFO] 14:13:59:291 KERNEL/(212074:212076): PID: 1 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 14:13:59:291 KERNEL/(212074:212076): Cola Ready FIFO: [1]

[INFO] 14:13:59:291 KERNEL/(212074:212076): PID: 1 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 14:13:59:292 KERNEL/(212074:212076): PID: 1 - Yield 

[INFO] 14:13:59:292 KERNEL/(212074:212076): PID: 1 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 14:13:59:292 KERNEL/(212074:212076): Cola Ready FIFO: [1]

[INFO] 14:13:59:292 KERNEL/(212074:212076): PID: 1 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 14:13:59:292 KERNEL/(212074:212076): Finaliza el proceso 1 - Motivo: SUCCESS

[INFO] 14:13:59:293 KERNEL/(212074:212076): PID: 1 - Estado Anterior: EXEC - Estado Actual: EXIT

[INFO] 14:13:59:294 KERNEL/(212074:212074): Esperar Cliente...
[INFO] 14:13:59:294 KERNEL/(212074:212124): Cliente conectado
[INFO] 14:13:59:294 KERNEL/(212074:212075): Cola Ready FIFO: [2]

[INFO] 14:13:59:294 KERNEL/(212074:212075): PID: 2 - Estado Anterior: NEW - Estado Actual: READY

[INFO] 14:13:59:294 KERNEL/(212074:212076): PID: 2 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 14:13:59:295 KERNEL/(212074:212076): PID: 2 - Yield 

[INFO] 14:13:59:295 KERNEL/(212074:212076): PID: 2 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 14:13:59:295 KERNEL/(212074:212076): Cola Ready FIFO: [2]

[INFO] 14:13:59:295 KERNEL/(212074:212076): PID: 2 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 14:13:59:296 KERNEL/(212074:212076): PID: 2 - Yield 

[INFO] 14:13:59:296 KERNEL/(212074:212076): PID: 2 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 14:13:59:296 KERNEL/(212074:212076): Cola Ready FIFO: [2]

[INFO] 14:13:59:296 KERNEL/(212074:212076): PID: 2 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 14:13:59:296 KERNEL/(212074:212076): PID: 2 - Yield 

[INFO] 14:13:59:296 KERNEL/(212074:212076): PID: 2 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 14:13:59:296 KERNEL/(212074:212076): Cola Ready FIFO: [2]

[INFO] 14:13:59:296 KERNEL/(212074:212076): PID: 2 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 14:13:59:297 KERNEL/(212074:212076): PID: 2 - Yield 

[INFO] 14:13:59:297 KERNEL/(212074:212076): PID: 2 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 14:13:59:297 KERNEL/(212074:212076): Cola Ready FIFO: [2]

[INFO] 14:13:59:297 KERNEL/(212074:212076): PID: 2 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 14:13:59:298 KERNEL/(212074:212076): PID: 2 - Yield 

[INFO] 14:13:59:298 KERNEL/(212074:212076): PID: 2 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 14:13:59:298 KERNEL/(212074:212076): Cola Ready FIFO: [2]

[INFO] 14:13:59:298 KERNEL/(212074:212076): PID: 2 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 14:13:59:298 KERNEL/(212074:212076): PID: 2 - Yield 

[INFO] 14:13:59:298 KERNEL/(212074:212076): PID: 2 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 14:13:59:298 KERNEL/(212074:212076): Cola Ready FIFO: [2]

[INFO] 14:13:59:298 KERNEL/(212074:212076): PID: 2 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 14:13:59:299 KERNEL/(212074:212076): PID: 2 - Yield 

[INFO] 14:13:59:299 KERNEL/(212074:212076): PID: 2 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 14:13:59:299 KERNEL/(212074:212076): Cola Ready FIFO: [2]

[INFO] 14:13:59:299 KERNEL/(212074:212076): PID: 2 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 14:13:59:302 KERNEL/(212074:212076): PID: 2 - Yield 

[INFO] 14:13:59:303 KERNEL/(212074:212076): PID: 2 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 14:13:59:303 KERNEL/(212074:212076): Cola Ready FIFO: [2]

[INFO] 14:13:59:303 KERNEL/(212074:212076): PID: 2 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 14:13:59:304 KERNEL/(212074:212076): Finaliza el proceso 2 - Motivo: SUCCESS

[INFO] 14:13:59:304 KERNEL/(212074:212076): PID: 2 - Estado Anterior: EXEC - Estado Actual: EXIT

**Comment by RaniAgus** [comment]
Les sugiero que, para no perder la referencia al socket del proceso, lo que pueden hacer es agregarlo como atributo al PCB y usarlo para hacer `send()` y `close()` desde la función que lo pase a EXIT.

**Comment by BrunoRizzo765** [comment]
Claro si eso es lo que hacemos, tenemos la conexión de la consola en el pcb y le hacemos el send y el close en exit.
Pero pasa eso que no entra otro proceso hasta que el anterior no termina.
`void doExit(t_pcb* process){
	//pasar al mismo al estado EXIT
	log_info(logger,"PID: %d - Estado Anterior: EXEC - Estado Actual: EXIT\n", process->pid);
	
	//liberar todos los recursos que tenga asignados
	liberarRecursosAsignados(recursos_disponibles, process->recursos_asignados);

	agregar_pcb_en_cola_terminados(process);
	
	sem_post(&semMultiprogramacion);  
	
	t_paquete* fin = crear_paquete_con_codigo_op(FIN_PROCESO);
	agregar_entero_a_paquete(fin, process->pid);
	enviar_paquete(fin,process->conexion_consola);
	close(process->conexion_consola);
}`

**Comment by RaniAgus** [comment]
Asumo que `agregar_pcb_cola_nuevos(pcb_nuevo)` solamente agrega el PCB a una queue y luego hace el post para que otro hilo consuma de esa queue, ¿cierto?

De ser así, yo revisaría si ese hilo que consume la queue no está atendiendo los pcbs de a uno, o que de alguna forma en la lógica haga que se termine planificando como si el grado de multiprogramación fuera siempre 1.

Digo esto porque `esperar_cliente()` (que entendería que usa `accept()`) devuelve un nuevo socket cada vez que una nueva consola se conecta, independientemente de que haya otra ya conectada. Varios sockets pueden estar conectados al mismo tiempo durante la ejecución del programa.

Saludos

**Comment by BrunoRizzo765** [comment]
Claro agregar_pcb_cola_nuevos lo agrega a la queue y hace el post para que el long_term_scheduler consuma de la cola de nuevos, este a su vez, si el grado de multiprogramación lo permite, lo agrega en la cola de listos haciendo el post al short_term_scheduler. Por lo que entiendo esto debería poder atender a varios procesos, coméntame si ves algún error en la lógica de esto.
Si el esperar_cliente() usa el accept().

`int esperar_cliente(int socket_servidor){
	int socket_cliente;
	if ((socket_cliente = accept(socket_servidor, NULL, NULL)) == -1)
	{
		printf("No se pudo conectar el modulo\n");
		return EXIT_FAILURE;
	}
	// log_info(logger, "Se conecto un cliente!");
	return socket_cliente;
}`

`void agregar_pcb_cola_nuevos(t_pcb* proceso) {

    pthread_mutex_lock(&procesosNuevosMutex);

    queue_push(new_queue, proceso);

    pthread_mutex_unlock(&procesosNuevosMutex);

    sem_post(&semProcesoNuevo);
}`

`void agregar_pcb_en_cola_listos(t_pcb* proceso) 
{
    pthread_mutex_lock(&procesosListosMutex);

    queue_push(ready_queue, proceso);

    pthread_mutex_unlock(&procesosListosMutex);
    
    if(algoritmo_es_hrrn(algoritmo_planificacion))empezar_espera_ready(proceso);

    mostrar_cola_ready();

    sem_post(&semProcesoListo);
}`

`void long_term_scheduler() {
    
	while (true){
        sem_wait(&semProcesoNuevo);
		sem_wait(&semMultiprogramacion);

		t_pcb* pcb = sacar_pcb_de_cola_nuevo();

		agregar_pcb_en_cola_listos(pcb);

		log_info(logger,"PID: %d - Estado Anterior: NEW - Estado Actual: READY\n", pcb->pid);
    }
}

void short_term_scheduler() {
	while (true) {
		sem_wait(&semProcesoListo);

		if(algoritmo_es_hrrn()){
			ordenar_cola_listos();
		}

		t_pcb* pcb = sacar_pcb_cola_listos();
		
		meter_pcb_en_ejecucion(pcb);

		// Ejecutar proceso
		log_info(logger,"PID: %d - Estado Anterior: READY - Estado Actual: EXEC\n", pcb->pid);
		
		enviar_pcb(pcb, conexion_cpu);
		
		recibir_pcb_de_CPU(conexion_cpu);
		
		
    }
	
}`

**Comment by RaniAgus** [comment]
Volviendo a revisar los logs noté que los 3 procesos ejecutan en el mismo segundo, ¿si aumentan el tiempo de retardo de instrucción a 1000ms sigue ocurriendo?

**Comment by BrunoRizzo765** [comment]
Si ocurre lo mismo

**Comment by RaniAgus** [comment]
Revisándolo punta a punta no veo nada raro que pueda estar relacionado... Ninguna de las funciones que llama `esperar_clientes()` hace algún `sem_wait()`, ¿no? Y todos los mutex que usa se están desbloqueando luego de usarse 🤔 

Comentando los hilos que llaman a `long_term_scheduler` y `short_term_scheduler` (o sea, no creándolos para que no consuman la queue), ¿el hilo que llama a `esperar_clientes()` logra agregar las 3 consolas a la queue o se queda colgado al agregar la primera?

**Comment by BrunoRizzo765** [comment]
Comentando los hilos queda colgado después del primer proceso.

[INFO] 16:48:48:217 KERNEL/(301623:301624): Esperar Cliente...
[INFO] 16:48:58:849 KERNEL/(301623:301624): Esperar Cliente...
[INFO] 16:48:58:857 KERNEL/(301623:301718): Cliente conectado

**Comment by RaniAgus** [comment]
Bien, es un avance, ya sabemos que el problema no está en otros hilos. 

Si lo corren con el debugger, ¿podremos determinar en qué línea se queda?

**Comment by RaniAgus** [comment]
¿Quién llama a `handle_consola()`? Es la primera vez que veo esa función en este issue 😅 

También, pregunta leyendo los logs: ¿están conectando 2 consolas o 3? Por lo que veo asumo que 2 porque se ejecuta 2 veces el log de `"Esperar Cliente..."`

**Comment by BrunoRizzo765** [comment]
Se ejecutan 3 consolas con este sh:
```
cd ./consola
./consola ./config/consola.config ./config/BASE_1.pseudo
./consola ./config/consola.config ./config/BASE_2.pseudo
./consola ./config/consola.config ./config/BASE_2.pseudo
cd ..
```

Cambie el `esperar_clientes()` y me olvide de mandarlo por acá 😅

```
void handle_consola(int* socket_cliente){
	log_info(logger, "Cliente conectado");
    int conexion_consola = *socket_cliente;
    int op_code = recibir_operacion(conexion_consola);

	switch (op_code){
		case PAQUETE_INSTRUCCIONES:
			t_list* instrucciones = recibir_instrucciones(conexion_consola);
			t_pcb* pcb_nuevo = crear_pcb(instrucciones, conexion_consola);
			agregar_pcb_cola_nuevos(pcb_nuevo);
			//list_destroy(instrucciones);
			break;
		default: 
			log_error(logger, "El codigo de operacion recibido es inválido");
			break;
	}
}

void esperar_clientes() {
	int socket_servidor = crear_servidor(ip,puerto_escucha);
	
   	while (1) {
		log_info(logger, "Esperar Cliente...");
		pthread_t hilo_cliente;

        int socket_cliente = esperar_cliente(socket_servidor);

		int* consola_ptr = malloc(sizeof(int));
		*consola_ptr = socket_cliente;

        pthread_create(&hilo_cliente, NULL, (void*) handle_consola, consola_ptr);
        pthread_detach(hilo_cliente);
    }

	close(socket_servidor);
}
```

**Comment by RaniAgus** [comment]
Ya entendí, el motivo del error es que el script que están usando ejecuta los 3 comandos uno atrás del otro, por lo que siempre se va a esperar a que la anterior consola finalice para arrancar con la siguiente 😅 

Abran 3 terminales distintas y ejecuten `./consola ./config/consola.config ./config/BASE_<N>.pseudo` en cada una.

**Comment by BrunoRizzo765** [comment]
Ejecute desde tres distintas consolas y se conectan todas pero empiezan a ejecutar solo cuando termina el anterior.

[INFO] 18:14:38:893 KERNEL/(316976:316979): Esperar Cliente...
[INFO] 18:14:48:922 KERNEL/(316976:316979): Esperar Cliente...
[INFO] 18:14:48:924 KERNEL/(316976:317079): Cliente conectado
[INFO] 18:14:49:458 KERNEL/(316976:316979): Esperar Cliente...
[INFO] 18:14:49:464 KERNEL/(316976:317082): Cliente conectado
[INFO] 18:14:50:243 KERNEL/(316976:316979): Esperar Cliente...
[INFO] 18:14:50:257 KERNEL/(316976:317123): Cliente conectado
[INFO] 18:14:58:930 KERNEL/(316976:316977): Cola Ready FIFO: [0]

[INFO] 18:14:58:930 KERNEL/(316976:316977): PID: 0 - Estado Anterior: NEW - Estado Actual: READY

[INFO] 18:14:58:930 KERNEL/(316976:316978): PID: 0 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 18:14:58:931 KERNEL/(316976:316978): PID: 0 - Yield 

[INFO] 18:14:58:931 KERNEL/(316976:316978): PID: 0 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 18:14:58:931 KERNEL/(316976:316978): Cola Ready FIFO: [0]

[INFO] 18:14:58:931 KERNEL/(316976:316978): PID: 0 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 18:14:58:932 KERNEL/(316976:316978): Finaliza el proceso 0 - Motivo: SUCCESS

[INFO] 18:14:58:932 KERNEL/(316976:316978): PID: 0 - Estado Anterior: EXEC - Estado Actual: EXIT

[INFO] 18:14:59:473 KERNEL/(316976:316977): Cola Ready FIFO: [1]

[INFO] 18:14:59:473 KERNEL/(316976:316977): PID: 1 - Estado Anterior: NEW - Estado Actual: READY

[INFO] 18:14:59:473 KERNEL/(316976:316978): PID: 1 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 18:14:59:474 KERNEL/(316976:316978): PID: 1 - Yield 

[INFO] 18:14:59:474 KERNEL/(316976:316978): PID: 1 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 18:14:59:474 KERNEL/(316976:316978): Cola Ready FIFO: [1]

[INFO] 18:14:59:474 KERNEL/(316976:316978): PID: 1 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 18:14:59:475 KERNEL/(316976:316978): PID: 1 - Yield 

[INFO] 18:14:59:475 KERNEL/(316976:316978): PID: 1 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 18:14:59:475 KERNEL/(316976:316978): Cola Ready FIFO: [1]

[INFO] 18:14:59:475 KERNEL/(316976:316978): PID: 1 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 18:14:59:477 KERNEL/(316976:316978): PID: 1 - Yield 

[INFO] 18:14:59:477 KERNEL/(316976:316978): PID: 1 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 18:14:59:477 KERNEL/(316976:316978): Cola Ready FIFO: [1]

[INFO] 18:14:59:477 KERNEL/(316976:316978): PID: 1 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 18:14:59:478 KERNEL/(316976:316978): PID: 1 - Yield 

[INFO] 18:14:59:478 KERNEL/(316976:316978): PID: 1 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 18:14:59:478 KERNEL/(316976:316978): Cola Ready FIFO: [1]

[INFO] 18:14:59:478 KERNEL/(316976:316978): PID: 1 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 18:14:59:479 KERNEL/(316976:316978): PID: 1 - Yield 

[INFO] 18:14:59:480 KERNEL/(316976:316978): PID: 1 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 18:14:59:480 KERNEL/(316976:316978): Cola Ready FIFO: [1]

[INFO] 18:14:59:480 KERNEL/(316976:316978): PID: 1 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 18:14:59:481 KERNEL/(316976:316978): PID: 1 - Yield 

[INFO] 18:14:59:481 KERNEL/(316976:316978): PID: 1 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 18:14:59:482 KERNEL/(316976:316978): Cola Ready FIFO: [1]

[INFO] 18:14:59:482 KERNEL/(316976:316978): PID: 1 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 18:14:59:482 KERNEL/(316976:316978): PID: 1 - Yield 

[INFO] 18:14:59:482 KERNEL/(316976:316978): PID: 1 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 18:14:59:482 KERNEL/(316976:316978): Cola Ready FIFO: [1]

[INFO] 18:14:59:483 KERNEL/(316976:316978): PID: 1 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 18:14:59:484 KERNEL/(316976:316978): PID: 1 - Yield 

[INFO] 18:14:59:484 KERNEL/(316976:316978): PID: 1 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 18:14:59:484 KERNEL/(316976:316978): Cola Ready FIFO: [1]

[INFO] 18:14:59:484 KERNEL/(316976:316978): PID: 1 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 18:14:59:485 KERNEL/(316976:316978): Finaliza el proceso 1 - Motivo: SUCCESS

[INFO] 18:14:59:485 KERNEL/(316976:316978): PID: 1 - Estado Anterior: EXEC - Estado Actual: EXIT

[INFO] 18:15:00:262 KERNEL/(316976:316977): Cola Ready FIFO: [2]

[INFO] 18:15:00:262 KERNEL/(316976:316977): PID: 2 - Estado Anterior: NEW - Estado Actual: READY

[INFO] 18:15:00:262 KERNEL/(316976:316978): PID: 2 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 18:15:00:263 KERNEL/(316976:316978): PID: 2 - Yield 

[INFO] 18:15:00:263 KERNEL/(316976:316978): PID: 2 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 18:15:00:263 KERNEL/(316976:316978): Cola Ready FIFO: [2]

[INFO] 18:15:00:263 KERNEL/(316976:316978): PID: 2 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 18:15:00:264 KERNEL/(316976:316978): PID: 2 - Yield 

[INFO] 18:15:00:264 KERNEL/(316976:316978): PID: 2 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 18:15:00:264 KERNEL/(316976:316978): Cola Ready FIFO: [2]

[INFO] 18:15:00:264 KERNEL/(316976:316978): PID: 2 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 18:15:00:265 KERNEL/(316976:316978): PID: 2 - Yield 

[INFO] 18:15:00:265 KERNEL/(316976:316978): PID: 2 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 18:15:00:265 KERNEL/(316976:316978): Cola Ready FIFO: [2]

[INFO] 18:15:00:265 KERNEL/(316976:316978): PID: 2 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 18:15:00:268 KERNEL/(316976:316978): PID: 2 - Yield 

[INFO] 18:15:00:268 KERNEL/(316976:316978): PID: 2 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 18:15:00:269 KERNEL/(316976:316978): Cola Ready FIFO: [2]

[INFO] 18:15:00:269 KERNEL/(316976:316978): PID: 2 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 18:15:00:270 KERNEL/(316976:316978): PID: 2 - Yield 

[INFO] 18:15:00:270 KERNEL/(316976:316978): PID: 2 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 18:15:00:270 KERNEL/(316976:316978): Cola Ready FIFO: [2]

[INFO] 18:15:00:270 KERNEL/(316976:316978): PID: 2 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 18:15:00:271 KERNEL/(316976:316978): PID: 2 - Yield 

[INFO] 18:15:00:271 KERNEL/(316976:316978): PID: 2 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 18:15:00:271 KERNEL/(316976:316978): Cola Ready FIFO: [2]

[INFO] 18:15:00:271 KERNEL/(316976:316978): PID: 2 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 18:15:00:274 KERNEL/(316976:316978): PID: 2 - Yield 

[INFO] 18:15:00:274 KERNEL/(316976:316978): PID: 2 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 18:15:00:274 KERNEL/(316976:316978): Cola Ready FIFO: [2]

[INFO] 18:15:00:274 KERNEL/(316976:316978): PID: 2 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 18:15:00:277 KERNEL/(316976:316978): PID: 2 - Yield 

[INFO] 18:15:00:277 KERNEL/(316976:316978): PID: 2 - Estado Anterior: EXEC- Estado Actual: READY

[INFO] 18:15:00:277 KERNEL/(316976:316978): Cola Ready FIFO: [2]

[INFO] 18:15:00:277 KERNEL/(316976:316978): PID: 2 - Estado Anterior: READY - Estado Actual: EXEC

[INFO] 18:15:00:278 KERNEL/(316976:316978): Finaliza el proceso 2 - Motivo: SUCCESS

[INFO] 18:15:00:278 KERNEL/(316976:316978): PID: 2 - Estado Anterior: EXEC - Estado Actual: EXIT

**Comment by RaniAgus** [comment]
Viendo los logs entiendo que el hilo que espera los clientes está agregando las consolas a la cola de new (ya que están todos los "Cliente conectado" al principio), pero parece ser que el hilo de `long_term_scheduler()` que consume esa queue y los agrega a ready no estaría funcionando de acuerdo al grado de multiprogramación.

¿Dónde están inicializando `semMultiprogramacion`? ¿Tienen configurado que el grado sea mayor a 1?
¿Tienen algún otro `sem_wait` en la función `sacar_pcb_de_cola_nuevo()`?

**Comment by BrunoRizzo765** [comment]
En el main se llama a `iniciar_listas_y_semaforos();` donde se inicializa el semáforo en el grado de multiprogramación, este lo sacamos del config(con el debugger me fije que se inicialice bien y si lo hace en 12). La función `sacar_pcb_de_cola_nuevo()` solo hace un queue_pop con sus correspondientes mutex .
```
int main()
{
	logger = iniciar_logger("./config/kernel.log","KERNEL");
	config = iniciar_config("./config/kernel.config");
	
	inicializacionDeVariables();
	
	iniciar_listas_y_semaforos();
	
	/////////////////PLANIFICADORES///////////////////////////
	
	crear_hilo_planificador_largo_plazo();
	
	crear_hilo_planificador_corto_plazo();

	//////////////////PARTE SERVIDOR///////////////////////////

	pthread_t server_thread;
	if(pthread_create(&server_thread, NULL,(void*) esperar_clientes, NULL)<0){
		perror("Error al crear el hilo cliente");
		exit(EXIT_FAILURE);
	}

	pthread_join(server_thread,NULL);
	
	terminar_programa(logger, config);
}
```

```
void iniciar_listas_y_semaforos() {
    new_queue = queue_create();
    ready_queue = queue_create();
    pcb_a_ejecutar = NULL;

    exit_list = list_create();

    pthread_mutex_init(&procesoMutex, NULL);
    pthread_mutex_init(&procesosNuevosMutex, NULL);
    pthread_mutex_init(&procesosListosMutex, NULL);
    pthread_mutex_init(&procesosEjecutandoMutex, NULL);
    pthread_mutex_init(&procesosBloqueadosMutex, NULL);
    pthread_mutex_init(&procesosTerminadosMutex, NULL);
    pthread_mutex_init(&mutex_recursos,NULL);
    pthread_mutex_init(&mutexPID,NULL);

    sem_init(&semMultiprogramacion, 0, gradoMaxMultiprog);
    sem_init(&semProcesoNuevo, 0, 0);
    sem_init(&semProcesoListo, 0, 0);
}
```
```
t_pcb* sacar_pcb_de_cola_nuevo() {

    pthread_mutex_lock(&procesosNuevosMutex);

    t_pcb* proceso = queue_pop(new_queue);

    pthread_mutex_unlock(&procesosNuevosMutex);

  return proceso;
}
```

**Comment by LeandroCarbajales** [comment]
Buenas @BrunoRizzo765 !
Chequeen que estén esperando el tiempo correspondiente para la instrucción SET en CPU, ya que según los logs el proceso vuelve inmediatamente de CPU, por lo que el proceso finaliza en menos de 2ms en lugar de tardar algunos segundos.

**Comment by BrunoRizzo765** [comment]
Recién revise y no estábamos esperando el tiempo correspondiente en el set, lo arregle pero igual sigue sucediendo lo mismo. Los procesos se ejecutan cuando termina el anterior.

**Comment by RaniAgus** [comment]
Me parece que nos va a ser muy difícil encontrar el error de forma asincrónica, ¿les parece bien de venir el sábado que viene a Discord así lo revisamos con más detalle?

**Comment by BrunoRizzo765** [comment]
Dale buenísimo, gracias.
