### ISSUE TITLE
Implementacion del Archivo de Bloques

### ISSUE THREAD

**Issue by Juan-Polito** [sisoputnfrba/foro#3153]
Buenas tardes, los molesto con una duda sobre el archivo de bloques. 
Estamos considerando estructurarlo de una de las dos formas que muestran la imagen.

 A la izaquierda tenemos un unico archivo al cual accedemos a cada bloque por indice de linea en el txt. De esta forma si queremos escribir en el bloque con indice 1 "dato1" lo hacemos abriendo el archivo y escribiendo en el primer renglon la informacion. Mientras que los punteros indirectos (en el ejemplo la linea 45)  tienen la direccion a la linea dentro del archivo con la informacion. 

A la derecha Archivo de Bloques tiene se comporta como un directorio que posee los archivos que representan los dato.

Cual de estas dos alternativas recomiendan para implementar en el fileSystem?

![image](https://github.com/sisoputnfrba/foro/assets/102620994/736951c4-7bfb-4d16-8e60-1a30186f9837)

**Comment by RaniAgus** [comment]
¡Buenas! El archivo de bloques es un **único** array de bytes (es decir, no es abrible con un bloc de notas como un txt), y en él hay que guardar los distintos bloques uno al lado del otro sin saltos de línea ni ningún otro separador. Los bloques de punteros deben almacenarse en formato `uint32_t` como se especifica en el enunciado.

Saludos

**Comment by Juan-Polito** [comment]
Gracias
