### ISSUE TITLE
Consulta sobre envio de consolas 

### ISSUE THREAD

**Issue by Chabelamas** [sisoputnfrba/foro#3154]
Buenas,
Tenemos un problema con la finalización de las consolas en el EXIT ya que si las consolas esperan al mensaje de Kernel para finalizar lo que nos pasa es que los procesos se crean en desorden y no corren las pruebas de FIFO y HRRN correctamente ¿Eliminamos el mensaje de respuesta de Kernel? ¿O existe alguna otra manera de solucionarlo? 
¡Desde ya muchas gracias!

La duda surge de la siguiente frase de la consigna:
"Una vez recibida la confirmación de recepción, la consola quedará a la espera del mensaje del Kernel que indique la finalización del mismo."

**Comment by RaniAgus** [comment]
¡Buenas!
No entendí bien por qué enviar un mensaje de EXIT (es decir, hacer un `send()` de Kernel a Consola) afectaría la creación de los procesos ya que es un evento que ocurre mucho antes.

¿Podrían darnos una idea de cómo modelaron en código la parte de aceptar nuevas consolas y la parte de enviarles el mensaje para que finalicen? ¿Usaron hilos diferentes?

Saludos

**Comment by gabriel1816** [comment]
Lo que nos pasa es que al ejecutar varias consolas con una misma terminal utilizando && nos funcionaba mal, pero mandando varias consolas con terminales separadas se solucionó!
