### ISSUE TITLE
Consulta de lectura dememoria

### ISSUE THREAD

**Issue by cgonzalezriverol** [sisoputnfrba/foro#3156]
Buenas

Estamos teniendo el siguiente problema y queriamos saber si saben por donde puede venir la mano:
Si nosotros ejecutamos en la misma consola MOV IN y MOV OUT, los valores se escriben y se leen de forma correcta. Pero si mandamos ambas instrucciones por consolas diferentes, no se leen los valores esperados.

muchas gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

En principio, la respuesta a la pregunta va a tener que ser más preguntas:

1.- Que scripts están corriendo?
2.- Están apuntando ambos al segmento 0 que es compartido entre los procesos o están apuntando a segmentos creados para cada proceso?
3.- Debuguearon la CPU para ver que ambos procesos están apuntando a la misma dirección física?
4.- Tienen logs que nos puedan compartir de la CPU o de la Memoria para ver que estan ejecutando?

Saludos.-

**Comment by joacobruno** [comment]
Buenas, te respondo :
1- Corremos los scripts de Memoria1 y dsp Memoria2
2- Claro, cuando el script Memoria2 quiere levantar lo que escribio en la direccion logica 12 el script Memoria1 lee cualquier cosa
3- Si, ambos procesos apuntan al segmento 0 y offset 12
4- 
LOG-MEMORIA:
[INFO] 03:31:59:935 MEMORIA/(10092:10092): Log creado
[INFO] 03:31:59:935 MEMORIA/(10092:10092): Servidor listo para recibir al cliente
[INFO] 03:32:02:271 MEMORIA/(10092:10092): Se conecto un cliente!
[INFO] 03:32:02:271 MEMORIA/(10092:10094): esperando codop
[INFO] 03:32:04:520 MEMORIA/(10092:10092): Se conecto un cliente!
[INFO] 03:32:04:521 MEMORIA/(10092:10103): esperando codop
[INFO] 03:32:06:516 MEMORIA/(10092:10103): pid 1
[INFO] 03:32:06:517 MEMORIA/(10092:10103): Creación de Proceso PID: <1>
[INFO] 03:32:06:517 MEMORIA/(10092:10103): esperando codop
[INFO] 03:32:07:553 MEMORIA/(10092:10094): Regsitro valor : 'h014'
[INFO] 03:32:07:553 MEMORIA/(10092:10094): PID: <1> - Acción: <ESCRIBIR> - Dirección física: <12> - Tamaño: <h014> - Origen: <CPU / FS>
[INFO] 03:32:08:554 MEMORIA/(10092:10094): esperando codop
[INFO] 03:32:08:640 MEMORIA/(10092:10103): esperando codop
[INFO] 03:32:13:016 MEMORIA/(10092:10103): pid 2
[INFO] 03:32:13:016 MEMORIA/(10092:10103): Creación de Proceso PID: <2>
[INFO] 03:32:13:016 MEMORIA/(10092:10103): esperando codop
[INFO] 03:32:13:104 MEMORIA/(10092:10094): PID: <2> - Acción: <LEER> - Dirección física: <12> - Tamaño: <12> - Origen: <CPU / FS>


LOG-CPU:

[INFO] 03:55:47:184 CPU/(11461:11461): PID : '1'
[INFO] 03:55:47:184 CPU/(11461:11461): PC : '1'
[INFO] 03:55:47:184 CPU/(11461:11461): Cantidad instrucciones : '11'
[INFO] 03:55:47:184 CPU/(11461:11461): Cantidad segmentos : '1'
[INFO] 03:55:47:184 CPU/(11461:11461): Segmento recibido 0 0 128
[INFO] 03:55:47:184 CPU/(11461:11461): Instruccion SET, cantidad parametros: 2
[INFO] 03:55:48:185 CPU/(11461:11461): PID: <1> - Ejecutando: <SET> - <AX> - <h014>

[INFO] 03:55:48:185 CPU/(11461:11461): Instruccion MOV_OUT, cantidad parametros: 2
[INFO] 03:55:48:185 CPU/(11461:11461): PID: <1> - Ejecutando: <MOV_OUT> -

[INFO] 03:55:48:185 CPU/(11461:11461): PID: <1> - Acción: <ESCRIBIR> - Segmento: <0> - Dirección Física: <12> - Valor: <h014>
[INFO] 03:55:49:186 CPU/(11461:11461): termino memoria 1
[INFO] 03:55:49:186 CPU/(11461:11461): Instruccion CREATE_SEGMENT, cantidad parametros: 2
[INFO] 03:55:49:186 CPU/(11461:11461): PID: <1> - Ejecutando: <CREATE_SEGMENT> -

[INFO] 03:55:49:186 CPU/(11461:11461): Registro 0 : AX, con longitud 2
[INFO] 03:55:49:186 CPU/(11461:11461): Registro valor 0 : h014, con longitud 4
[INFO] 03:55:49:272 CPU/(11461:11461): Me llego un PCB
[INFO] 03:55:49:272 CPU/(11461:11461): PID : '1'
[INFO] 03:55:49:272 CPU/(11461:11461): PC : '4'
[INFO] 03:55:49:272 CPU/(11461:11461): Cantidad instrucciones : '11'
[INFO] 03:55:49:272 CPU/(11461:11461): Cantidad segmentos : '2'
[INFO] 03:55:49:272 CPU/(11461:11461): Segmento recibido 0 0 128
[INFO] 03:55:49:272 CPU/(11461:11461): Segmento recibido 1 0 128
[INFO] 03:55:49:272 CPU/(11461:11461): Instruccion SIGNAL, cantidad parametros: 1
[INFO] 03:55:49:272 CPU/(11461:11461): PID: <1> - Ejecutando: <SIGNAL> -

[INFO] 03:55:49:272 CPU/(11461:11461): IO RB
[INFO] 03:55:49:272 CPU/(11461:11461): Instruccion SIGNAL, Valor: RB con longitud 2
[INFO] 03:55:49:273 CPU/(11461:11461): Me llego un PCB
[INFO] 03:55:49:316 CPU/(11461:11461): PID : '1'
[INFO] 03:55:49:316 CPU/(11461:11461): PC : '5'
[INFO] 03:55:49:316 CPU/(11461:11461): Cantidad instrucciones : '11'
[INFO] 03:55:49:316 CPU/(11461:11461): Cantidad segmentos : '2'
[INFO] 03:55:49:316 CPU/(11461:11461): Segmento recibido 0 0 128
[INFO] 03:55:49:316 CPU/(11461:11461): Segmento recibido 1 0 128
[INFO] 03:55:49:316 CPU/(11461:11461): Instruccion WAIT, cantidad parametros: 1
[INFO] 03:55:49:316 CPU/(11461:11461): PID: <1> - Ejecutando: <WAIT> -

[INFO] 03:55:49:316 CPU/(11461:11461): IO RA
[INFO] 03:55:49:316 CPU/(11461:11461): Instruccion WAIT, Valor: RA con longitud 2
[INFO] 03:55:51:981 CPU/(11461:11461): Me llego un PCB
[INFO] 03:55:52:024 CPU/(11461:11461): PID : '2'
[INFO] 03:55:52:024 CPU/(11461:11461): PC : '0'
[INFO] 03:55:52:024 CPU/(11461:11461): Cantidad instrucciones : '30'
[INFO] 03:55:52:024 CPU/(11461:11461): Cantidad segmentos : '1'
[INFO] 03:55:52:024 CPU/(11461:11461): Segmento recibido 0 0 128
[INFO] 03:55:52:024 CPU/(11461:11461): Instruccion WAIT, cantidad parametros: 1
[INFO] 03:55:52:024 CPU/(11461:11461): PID: <2> - Ejecutando: <WAIT> -

[INFO] 03:55:52:024 CPU/(11461:11461): IO RB
[INFO] 03:55:52:024 CPU/(11461:11461): Instruccion WAIT, Valor: RB con longitud 2

[INFO] 03:55:52:025 CPU/(11461:11461): Me llego un PCB
[INFO] 03:55:52:068 CPU/(11461:11461): PID : '2'
[INFO] 03:55:52:068 CPU/(11461:11461): PC : '1'
[INFO] 03:55:52:068 CPU/(11461:11461): Cantidad instrucciones : '30'
[INFO] 03:55:52:068 CPU/(11461:11461): Cantidad segmentos : '1'
[INFO] 03:55:52:068 CPU/(11461:11461): Segmento recibido 0 0 128
[INFO] 03:55:52:068 CPU/(11461:11461): Instruccion MOV_IN, cantidad parametros: 2
[INFO] 03:55:52:068 CPU/(11461:11461): PID: <2> - Ejecutando: <MOV_IN> -

[INFO] 03:55:53:069 CPU/(11461:11461): Regsitro valor : '�������������U'
[INFO] 03:55:53:069 CPU/(11461:11461): Recibi de memoria :1
[INFO] 03:55:53:069 CPU/(11461:11461): recibido valor �������������U
[INFO] 03:55:53:069 CPU/(11461:11461): PID: <2> - Acción: <LEER> - Segmento: <0> - Dirección Física: <12> - Valor: <�������������U>

Ahi deje los logs de ambos en este caso, si algo no se entiende avisame. 

Desde ya gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

A priori parece estar bien el tema de las direcciones, por las dudas pregunto, debuguearon la serialización?

Saludos.-

**Comment by joacobruno** [comment]
Segun entiendo, serializacion se hace bien porque el modulo memoria recibe bien lo que le envie la cpu. Ademas si un proceso escribe en memoria y dsp el mismo lee lo que escribio en memoria lo lee bien. El tema esta cuando quiere leer lo que escribio otro

**Comment by iago64** [comment]
Lo que me llama muchísimo la atención es que tienen logs del estilo de: 
```
[INFO] 03:55:53:069 CPU/(11461:11461): PID: <2> - Acción: - Segmento: <0> - Dirección Física: <12> - Valor: <�������������U>
```

Eso me suena a que es algo que les esta faltando y/o fallando, pero en el aire es muy difícil saberlo y quiero ver si puedo acortar los caminos para que el sábado por discord podamos darles una mano más acertada y aprovechar al máximo el tiempo.

Pueden correr con valgrind y revisar si tienen algún invalid read / invalid write? Esto es algo que comentamos en la [Guía de Valgrind / Helgrind](https://docs.utnso.com.ar/guias/herramientas/valgrind) 

Saludos.-

**Comment by iago64** [comment]
Buenas!

@cgonzalezriverol @joacobruno pudieron resolver el inconveniente en soporte el sabado? Necesitan que veamos algo mas y/o nos pueden subir los logs de valgrind?

Saludos.-

**Comment by iago64** [comment]
Cerramos el issue por inactividad.
