### ISSUE TITLE
Dudas sobre logs a mostrar de filesystem

### ISSUE THREAD

**Issue by MiltonMartorello** [sisoputnfrba/foro#3157]
Buenas como andan? 
Quería sacarme unas dudas que me surgieron con respecto a un issue que se cerró.

Me llamó la atención la respuesta de @iago64 con respecto a que los bloques de punteros son del 1 a N. 

`Respecto al id del archivo nos referíamos a la posición de bloque dentro del archivo, es decir, que el directo es el bloque 0 y los punteros del bloque de punteros son del 1 hasta N, pero bueno, como dije antes, si es solo este detalle y lo aceptamos, lo que si avísenle al ayudante que los evalúe para que lo tenga en cuenta.`

_Originally posted by @iago64 in https://github.com/sisoputnfrba/foro/issues/3145#issuecomment-1636422840_

1) Para nosotros el 1 es el bloque indirecto que tiene a los punteros y luego los otros comienzan desde el 2. esto es válido? o la idea es que se logueen solamente los bloques de datos del archivo ?

2)  Por otro lado, deberíamos loguear el Acceso a bloque tanto para lectura como para escritura? Pregunto porque el log no parece discriminarlo y tal vez quede confuso.

3) Y una más. Cuando la lectura/escritura supera al bloque directo, las pruebas loguean primero el bloque indirecto

```
[INFO] 03:07:42:809 file_system/(43197:43197): Escribir Archivo: <Consoles> - Puntero: <128> - Memoria: <32> - Tamaño: <80>
[INFO] 03:07:42:809 file_system/(43197:43197): Acceso Bloque - Archivo: <Consoles> - Bloque Archivo: <1> - Bloque File System <1>
[INFO] 03:08:12:810 file_system/(43197:43197): Acceso Bloque - Archivo: <Consoles> - Bloque Archivo: <0> - Bloque File System <0>
[INFO] 03:08:27:810 file_system/(43197:43197): Acceso Bloque - Archivo: <Consoles> - Bloque Archivo: <2> - Bloque File System <2>
[INFO] 03:08:42:811 file_system/(43197:43197): Acceso Bloque - Archivo: <Consoles> - Bloque Archivo: <3> - Bloque File System <3>
[INFO] 03:08:57:812 file_system/(43197:43197): Acceso Bloque - Archivo: <Consoles> - Bloque Archivo: <4> - Bloque File System <4>
```

Esto sucede porque si se sabe que se va a escribir/leer algo que va mas allá, ya traemos el bloque indirecto y encolamos todos los bloques de datos que se van a leer. por eso salte del 0 (directo) al 2 (primer bloque de datos extra).
Esto es aceptable?
Perdón si son preguntas pavas, no quiero que se me escape nada.

Muchas Gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Si tomaron al bloque 1 como el bloque de punteros, avisenlo a la hora de la evaluación para poder seguir mejor los logs :)
2.- Si, el acceso a bloque es acceso a bloque independientemente de la operación.
3.- Si, está bien, solo avisen por favor a la hora de la evaluación que el bloque 1 es el bloque de punteros, así es más fácil seguir el log 😉 

Saludos.-
