### ISSUE TITLE
Duda acerca del bitmap y mmap

### ISSUE THREAD

**Issue by lucasosacuenca** [sisoputnfrba/foro#3159]
Estoy teniendo muchas dudas a la hora de inicializar el bitmap, a la hora de crear con el bitarray bien, entiendo que es lo que tengo que hacer, mi problema viene con el mmap, no termino de entender como funciona:

```
int cant_bytes = superbloque->block_count/8; //cantidad de bytes necesarios para representar los bloques en bits
	int fd = open(filesystem_configs->path_bitmap, O_RDWR | O_CREAT, 0750);
	if(fd == -1){
		//error al abrir
		printf("NO SE PUDO ABRIR EL ARCHIVO BITMAP");
	}
	char* bitarray = calloc(cant_bytes, sizeof(char));
	t_bitarray* bitmap= bitarray_create_with_mode(bitarray, cant_bytes, LSB_FIRST);
	void* respuesta_mapeo = mmap(NULL, cant_bytes, PROT_READ| PROT_WRITE, MAP_SHARED, fd, 0);
```

Diganme si estoy equivocado, al yo pasarle el fd, lo que hace la funcion es devolverme un puntero a la primera direccion de ese archivo? si eso es lo que hace, a mi me convendria guardar eso en el bitarray del t_bitarray, o manejar las dos cosas por separado y actualizarlas con el msync? Gracias.

**Comment by iago64** [comment]
Buenas! Cómo va?

Creo que se te estan mezclando los conceptos un poco entre `mmap()` y `msync()`

En principio lo que planteas de abrir el archivo y con el fd pasarselo a `mmap()` para que este te devuelva el puntero a la posición de memoria que después le vas a pasar al `bitarray_create()` es la mejor idea, ya que con eso vos te aseguras de que cada cambio que hagas sobre el bitarray, en algun momento se va a persistir en el archivo.

`msync()` por otro lado, lo que hace es hacer que el programa espere esa sincronización, es en pocas palabras una syscall bloqueante y para el TP es algo que no hace falta que se compliquen en usarlo ya que los cambios al correr solo el SO y su TP en la VM no es que está sufriendo mucho el disco.

Te desaconsejo la idea de copiar lo que te devuelve `mmap()` a otro espacio de memoria porque es un doble trabajo que es mas propenso a un error 

Saludos.-

**Comment by lucasosacuenca** [comment]
claro, pero creando con ese puntero el bitarray
	```
char** bitarray = mmap(NULL, cant_bytes, PROT_READ| PROT_WRITE, MAP_SHARED, fd, 0);
	if(bitarray == MAP_FAILED){
			//Fallo mapeo
		}
	t_bitarray* bitmap= bitarray_create_with_mode(bitarray, cant_bytes, LSB_FIRST);
```
de esta manera por ejemplo, igualmente puedo usar la funciones de las commons de bitarray? pq el bitarray pasa a ser char**, la otra forma es que yo lo pase como `t_bitarray* bitmap= bitarray_create_with_mode(&bitarray, cant_bytes, LSB_FIRST);` para que me quede como char*, que es lo que tendria que hacer para que se me actualize en memoria? porque tengo entendido que por mas que haga los cambios, no se van a ver reflejados en el archivo

**Comment by iago64** [comment]
Buenas! Cómo va?

Si, podes usar las funciones de bitarray, porque justamente si te fijas en la función [`bitarray_create_with_mode()`](https://github.com/sisoputnfrba/so-commons-library/blob/af8458ff77bb2b7e095a1c4ff97c9f491df27a62/src/commons/bitarray.h#L77) lo que tenes que pasarle es un `char*` y lo que te devuelve [`mmap()`](https://man7.org/linux/man-pages/man2/mmap.2.html) es un `void*` (y si, haces mal al declarar la variable `bitarray` como `char**` porque no es lo que devuelve `mmap()`), es decir ambos son punteros a memoria y los podes usar sin problemas.

Saludos.-

**Comment by lucasosacuenca** [comment]
dale muchas gracias
