### ISSUE TITLE
Duda sobre multiples peticiones de un mismo modulo a memoria

### ISSUE THREAD

**Issue by FranPenaUtn** [sisoputnfrba/foro#3161]
Hola buenas tardes! Teniamos una duda en el armado del file system que fue aclarada en este issue: https://github.com/sisoputnfrba/foro/issues/2976. Sin embargo, al leer ese issue nos surgio otra duda...
cito lo que escribio @LeandroCarbajales 

> Cabe aclarar, que esto mismo les podría llegar a pasar en la comunicación con el módulo Memoria, por lo que recomendamos lo mismo en ese caso.

La duda que tenemos es:
En que situacion podria pasar lo mismo en la comunicacion con memoria si ninguna de las operaciones que memoria maneja bloquea el proceso, es decir, en todas las instrucciones el kernel se queda esperando una respuesta de memoria. La unica que se nos viene a la cabeza es al momento de compactar pero tampoco se bloquea el proceso por eso nuestra duda.

Gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Depende muchísimo de la implementación que tengan a nivel de kernel y memoria, pero pensa que el Kernel no solo va a estar atendiendo las "syscalls" de la CPU, si no que además hace otras cosas como por ej administrar procesos.

Saludos.-

**Comment by FranPenaUtn** [comment]
Clarisimo, gracias!
Ya que estoy te hago otra consulta sobre el manejo de los archivos abiertos. El enunciado habla de locks exclusivos y obligatorios sobre cada archivo:

> Para la gestión de los archivos, el Kernel deberá implementar una tabla global de archivos abiertos, a fin de poder gestionar los mismos como si fueran un recurso de una única instancia. Cada archivo podrá estar abierto por solo un proceso a la vez, por lo que se deberá implementar locks exclusivos y obligatorios sobre cada archivo.

Nosotros cada vez que llega un F_OPEN validamos si ese archivo que se quiere abrir figura en la tabla global de archivos abiertos. 

- Si figura, entonces bloqueamos el proceso y lo encolamos en la cola de procesos bloqueados de ese archivo.
- Si no figura en la tabla global de archivos abiertos, consultamos en fs (si no existe se crea) y posteriormente se crean las entradas en las 2 tablas (global y la del proceso).

La duda es si los locks exclusivos y obligatorios que hace referencia el enunciado se refiere a esto o a otra cosa que no estamos contemplando en lo que comente anteriormente? 

Gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Los locks exclusivos y obligatorios hacen referencia a lo que planteas, y es que solo 1 proceso pueda tener el archivo abierto a la vez, capaz que nos quedó un poco redundante en el tp.

Saludos.-
