### ISSUE TITLE
Duda acerca de la funcion "Leer archivo" Filesystem

### ISSUE THREAD

**Issue by LucianoKremer** [sisoputnfrba/foro#3162]
Cerrando un par de cosas del filesystem me surgio una duda del enunciado: lo que se recibe para esta funcion si bien como dice es un puntero y un tamaño, en que formato lo recibe? Yo interpreto como que recibe el numero de bloque (osea el contenido del puntero) y el tamaño que quiere leer. Pero no termino de estar seguro, si realmente es el bloque al que apunta el puntero u otra cosa.

### 📔 Citas del enunciado/videos
>
Leer Archivo:
Esta operación deberá leer la información correspondiente de los bloques a partir del puntero y el tamaño recibidos. Esta información se deberá enviar a la Memoria para ser escrita a partir de la dirección física recibida por parámetro y esperar su finalización para poder confirmar el éxito de la operación al Kernel.

**Comment by iago64** [comment]
Buenas! Cómo va?

Es muy muy similar a como funciona `fread()` uds con `fseek()` setean el puntero en un archivo (que le dicen a que byte tiene que apuntar) y después con `fread()` leen la cantidad de bytes que necesitan leer.

Ahora si la pregunta es como lo implementaron a nivel mensaje de Kernel, es algo que tienen que definir uds internamente de como serializan los mensajes.

Saludos.-

**Comment by LucianoKremer** [comment]
Reformulo la pregunta: Con el tamaño se refieren a la cantidad de bytes a leer? Con puntero se refieren al contenido que iria dentro del puntero ó, al nro del puntero ó algun identificador del mismo?

**Comment by iago64** [comment]
El tamaño es la cantidad de bytes a leer.
El puntero es lo que deberían tener en su tabla de archivos abiertos y les debería decir a partir de que byte del archivo tienen que leer.

**Comment by LucianoKremer** [comment]
Genial, muchas gracias! Saludos
