### ISSUE TITLE
Problema al Debuggear 

### ISSUE THREAD

**Issue by emfer** [sisoputnfrba/foro#3163]
Buenas como estan?
Adjunto el issue #2911 que habla de este tema.
Consulta, recien ahora me empezo a pasar lo mismo mientras debuggeaba y me tira el siguiente error: 
Can't find a source file at "./string/../sysdeps/x86_64/multiarch/strlen-avx2.S"
Locate the file or edit the source lookup path to include its location.

El problema es que esta pasando en la mayoria de las funciones log info y no me permite seguir el orden del programa. Cuando toco step return como dice la guia, igualmente me termina el debug y sale del modo. Por lo cual no puedo "saltearlo" por asi decirlo.
Alguna idea de como podria solucionar esto?

**Comment by iago64** [comment]
Buenas! Cómo va?

Por esas casualidades, leyeron la [Guía de Debugging](https://docs.utnso.com.ar/guias/herramientas/debugger) al completo?
Porque justamente uno de los títulos es: _Can't find source file at: El error que no es_

Saludos.-

**Comment by emfer** [comment]
Buenas, todo bien?
 Si, lei la guia y el error es el mismo, lo que esta pasando es que la recomendacion de hacer step return me liquida el debug y no me devuelve a la funcion de donde se llamo. Si bien ya se que el problema aparece por uno de los varios log info (no pasa en todos el error) despues termina el debug y no puedo seguir.

**Comment by iago64** [comment]
Buenas! Cómo va?

En estos casos lo importante es no hacer click en el `step into`, porque si lo hacen dentro del log es cuando les pasan estas cosas de que eclipse intenta "entrar" al fuente de las funciones y explota.

Lo que pueden hacer es usar el `step over`, que salta el llamado de la función ejecutándola sin buscar los fuentes.

Saludos.-

**Comment by emfer** [comment]
Buenas, todo bien?
En este caso no estoy usando step into.
Lo raro es que cuando toco step over tampoco funciona, tambien rompe, no sigue debugeando las lineas siguientes.

**Comment by iago64** [comment]
Si ponen un breakpoint después del log y le dan resume (el botón de play verde y amarillo) también rompe? 
El error por el que termina el debug cuál es? No sera un segfault y en realidad el problema es que le están pasando una dirección de memoria mal al log?

**Comment by RaniAgus** [comment]
¡Buenas! Me sumo para comentar que también en algunos casos les puede aparecer el mensaje si justo tienen algún error que finaliza el programa, como puede ser un segmentation fault. La clave está en leer la pestaña de Debug, si les aparece algo como:

![image](https://github.com/sisoputnfrba/foro/assets/39303639/68c59948-54bb-453c-980f-3921d68ac15a)

Es porque en esa línea el programa terminó (o sea, el debug no rompe el programa, sino que ya está roto y no se puede continuar). Si scrollean a través del stack trace, en algún renglón les aparecerá la línea de su código que provoca que se finalice el programa.

También [Valgrind](https://faq.utnso.com.ar/valgrind) imprime el stack trace cuando ocurre un seg fault o cualquier otro tipo de señal que finalice el proceso.

Saludos

**Comment by emfer** [comment]
Damian, Agustin, como estan?

Mil gracias. Estaba pasando eso. Si bien no podia pasar del log info, sea con breakpoint y resume o step over, me fije de la forma que paso agustin y tenia un segmentation fault. Una vez solucionado pude volver a debuggear normalmente.

Muchas gracias!

**Comment by iago64** [comment]
Buenas, ¿cómo va?

Buenisimo, si está resuelta la duda, no se olviden de cerrar el issue 😄 

Saludos.-
