### ISSUE TITLE
Duda log en acceso a bloque

### ISSUE THREAD

**Issue by MarcosGurruchaga** [sisoputnfrba/foro#3164]
Buenas tardes, tengo la siguiente duda:
El bloque de punteros seria el bloque 1 o el 2 del archivo si tenemos en cuenta que el primer bloque es bloque directo? Arrancamos a contar desde 0 o 1 seria la pregunta?

### 📔 Citas del enunciado/videos
![image](https://github.com/sisoputnfrba/foro/assets/83126979/13df1fe7-962c-4aa2-aa93-fa3a014eefc1)
Viene a que aca en este log hay que detallar a que bloque se esta accediendo

**Comment by iago64** [comment]
Buenas! Cómo va?

No se compliquen, para nosotros es indistinto si arrancaron en 0 o en 1, simplemente avisen al ayudante que les este corrigiendo el TP así le es mas facil leer el log 😉 .

Saludos.-
