### ISSUE TITLE
Problema con la escritura de bloques

### ISSUE THREAD

**Issue by GermanBergera** [sisoputnfrba/foro#3166]
Buenas, estamos teniendo un problema a la hora de escribir los bloques, creemos que esta relacionado a un block buffer que tenemos y creemos que esta guardando informacion incorrecta

### 📝 Código relevante
nuestra funcion para escribir es:
```
void escribir(char *f_name, uint32_t offset, uint32_t cantidad, char *data)
{
  t_fcb *fcb = levantar_fcb(f_name);
  int desplazamiento = 0;
  int bloque_inicial = offset / BLOCK_SIZE;
  int bloque_final = (offset + cantidad) / BLOCK_SIZE;

  if (bloque_inicial == 0 && bloque_final == 0)
  {
    memcpy(blocks_buffer + fcb->f_dp + offset, data, cantidad);
    log_info(logger_filesystem, "Acceso Bloque - Archivo: %s - Bloque Archivo: %d - Bloque File System %d", f_name, 0, fcb->f_dp / BLOCK_SIZE);
    sleep(RETARDO_ACCESO_BLOQUE / 1000);
  }
  else if (bloque_inicial == bloque_final)
  {
    uint32_t puntero_a_escribir;
    memcpy(&puntero_a_escribir, blocks_buffer + fcb->f_ip + sizeof(uint32_t) * (bloque_inicial - 1), sizeof(uint32_t));
    log_info(logger_filesystem, "Acceso Bloque - Archivo: %s - Bloque Archivo: %d (indirecto) - Bloque File System %d", f_name, 1, fcb->f_ip / BLOCK_SIZE);
    sleep(RETARDO_ACCESO_BLOQUE / 1000);

    memcpy(blocks_buffer + puntero_a_escribir + (offset - BLOCK_SIZE * bloque_inicial), data, cantidad);
    log_info(logger_filesystem, "Acceso Bloque - Archivo: %s - Bloque Archivo: %d - Bloque File System %d", f_name, bloque_inicial + 1, puntero_a_escribir / BLOCK_SIZE);
    sleep(RETARDO_ACCESO_BLOQUE / 1000);
  }
  else
  {
    int bloques_a_escribir = (bloque_final - bloque_inicial) + 1;
    int cantidad_restante = cantidad;
    int desplazamiento = 0;
    if (bloque_inicial == 0)
    {
      memcpy(blocks_buffer + fcb->f_dp + offset, data, BLOCK_SIZE - offset);
      desplazamiento += BLOCK_SIZE - offset;
      cantidad_restante -= desplazamiento;
      log_info(logger_filesystem, "Acceso Bloque - Archivo: %s - Bloque Archivo: %d - Bloque File System %d", f_name, 0, fcb->f_dp / BLOCK_SIZE);
      sleep(RETARDO_ACCESO_BLOQUE / 1000);
    }
    else
    {
      uint32_t puntero_primer_bloque_a_escribir;
      memcpy(&puntero_primer_bloque_a_escribir, blocks_buffer + fcb->f_ip + sizeof(uint32_t) * (bloque_inicial - 1), sizeof(uint32_t));
      log_info(logger_filesystem, "Acceso Bloque - Archivo: %s - Bloque Archivo: %d (indirecto) - Bloque File System %d", f_name, 1, fcb->f_ip / BLOCK_SIZE);
      sleep(RETARDO_ACCESO_BLOQUE / 1000);

      memcpy(blocks_buffer + puntero_primer_bloque_a_escribir + (offset - BLOCK_SIZE * bloque_inicial), data + desplazamiento, BLOCK_SIZE * (bloque_inicial + 1) - offset);
      log_info(logger_filesystem, "Acceso Bloque - Archivo: %s - Bloque Archivo: %d - Bloque File System %d", f_name, bloque_inicial + 1, puntero_primer_bloque_a_escribir / BLOCK_SIZE);
      sleep(RETARDO_ACCESO_BLOQUE / 1000);

      desplazamiento = +BLOCK_SIZE * (bloque_inicial + 1) - offset;
      cantidad_restante -= BLOCK_SIZE * (bloque_inicial + 1) - offset;
    }
    bloques_a_escribir--;

    for (int i = bloque_inicial + 1; i <= bloque_final; i++)
    {
      uint32_t puntero;
      memcpy(&puntero, blocks_buffer + fcb->f_ip + sizeof(uint32_t) * (i-1), sizeof(uint32_t));
      int cant_a_escribir = cantidad_restante > BLOCK_SIZE ? BLOCK_SIZE : cantidad_restante;
      memcpy(blocks_buffer + puntero, data + desplazamiento, cant_a_escribir);
      desplazamiento += cant_a_escribir;
      cantidad_restante -= cant_a_escribir;
      log_info(logger_filesystem, "Acceso Bloque - Archivo: %s - Bloque Archivo: %d - Bloque File System %d", f_name, i + 1, puntero / BLOCK_SIZE);
      sleep(RETARDO_ACCESO_BLOQUE / 1000);
    }
  }

  // Actualizar block_file
  FILE *blocks_file = fopen(PATH_BLOQUES, "w");
  fwrite(blocks_buffer, BLOCK_SIZE, BLOCK_COUNT, blocks_file);
  fclose(blocks_file);
  free(fcb);
}
```
cuando levantamos el bloque lo hacemos de la siguiente manera:
```
char *levantar_bloques()
{
  char *blocks_buffer = calloc(BLOCK_COUNT, BLOCK_SIZE); 


  FILE *blocks_file = fopen(PATH_BLOQUES, "r");

  if (blocks_file == NULL)
  {
    blocks_file = fopen(PATH_BLOQUES, "w");
    fwrite(blocks_buffer, BLOCK_SIZE, BLOCK_COUNT, blocks_file);

  }

  fread(blocks_buffer, BLOCK_SIZE, BLOCK_COUNT, blocks_file);
  fclose(blocks_file);
  return blocks_buffer;
}
```

adjunto las pruebas hechas
```
F_OPEN Consoles
F_TRUNCATE Consoles 256
F_SEEK Consoles 128
F_WRITE Consoles 32 80
F_CLOSE Consoles
EXIT
```

### 💻 Logs
aca dejamos el hexdump de las  pruebas, ya esta corrido con valgrind y no notamos nada fuera de lo normal(no hubo invalid write ni invalid read).Creemos que la informacion guardada en la foto a continuacion pertenece a un log que dice "enviamos empaquetado de datos" que se encuentra antes pero solo se guarda una porcion:

![image](https://github.com/sisoputnfrba/foro/assets/46140822/c993ce92-af19-42ad-8374-b72257e16c95)

Desde ya muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

Asumiendo que los path estan todos bien y que no tienen el logger apuntando al mismo archivo que los bloques, me queda preguntar algunas cosas:

1.- Cuando llegan los MOV_OUT a la memoria, estan bien los datos?
2.- Debuguearon a ver el contenido del blocks_buffer? Si necesitan bajar el contenido a algo "mostrable" pueden usar las funciones de las commons de hexdump
3.- En las pruebas, hicieron los SET previos al F_OPEN y F_WRITE o es solo lo que esta en el script? Porque ahi si no, tendrían datos basura que anda a preguntarle a Dennis Ritchie que tiene la memoria.
4.- Investigaorn `mmap()`? Esto es mas a modo de recomendación porque el `blocks_buffer` que tienen podrían reemplazarlo por el puntero que les devuelve `mmap()` y no tendrían los `fseek()` / `fwrite()` 

Saludos.-

**Comment by GermanBergera** [comment]
Buenas!
1- Si!, ya que cuando realizamos (lo que podemos porque estamos con otro issue #3165 ) del mov in pudimos loggear lo que extrae de memoria y es lo correcto.
2-Probamos con la funcion  `mem_hexdump(blocks_buffer, BLOCK_COUNT);` y nos imprimio lo siguiente: 
![image](https://github.com/sisoputnfrba/foro/assets/46140822/1da37563-ca73-42bf-9e73-2b75248f2bef)
este es al levantar con calloc y se puede ver que levanta todo con 0(falta una parte porque no me entraba en la consola) y la siguiente es luego de ejecutar las instrucciones:
![image](https://github.com/sisoputnfrba/foro/assets/46140822/656922b3-82ae-4f65-8a10-d619b06a33ef)


3-Estuvimos ejecutando estas pruebas
```
SET RDX Plisstopiminpain
MOV_OUT 16 RDX
F_OPEN Consoles
F_TRUNCATE Consoles 256
F_SEEK Consoles 128
F_WRITE Consoles 16 80
F_CLOSE Consoles
EXIT
```
nos recomendarian ejecutar otras pruebas para testear esto?
4-Intentamos implementar el siguiente mmap` char *blocks_buffer = mmap(NULL,BLOCK_COUNT,PROT_WRITE,MAP_SHARED,blocks_file,0);` sin exito, no entendimos como implementarlo bien ademas de no entender si debiamos quitar los fwrites y reemplazarlos con algo o nada.

**Comment by iago64** [comment]
Buenas!

Ahora empiezan a tener más sentido las cosas, el F_WRITE solamente va a escribir lo que movieron del RDX seguido de lo que tengan en la memoria, por eso que en la prueba específica de FS se escriben 5 registros, por las dudas, lo que pueden hacer es hacer un `mem_hexdump()` de la memoria a ver si tienen bien la info ahi o si estan teniendo otros problemas.

Respecto al `mmap()`, el segundo parámetro tiene que ser `BLOCK_COUNT * BLOCK_SIZE` porque es el tamaño total del archivo y donde tienen `PROT_WRITE` tienen que poner `PROT_READ|PROT_WRITE` para poder leer y escribir las páginas, por las dudas es fundamental que siempre tengan la referencia del [man de `mmap()`](https://man7.org/linux/man-pages/man2/mmap.2.html) y despues todos los `fread()` / `fwrite()` se reemplazan por `memcpy()` ya que leen y escriben de memoria.

Por último, generalmente cuando se tienen estos tipos de errores de que la memoria se pisa, es fundamental que siempre checkeen con Valgrind que no están pisando memoria, es decir, que no tienen ninguna observación.

Saludos.-

**Comment by GonzaloGarmon** [comment]
Buenasss, 

Probamos de nuevo cambiar los parametros del mmap y borrar los fread y fwrites por memcpy pero ahora nos sigue rompiendo el mmap. 

```
char *levantar_bloques()
{
 

  log_warning(logger_filesystem,"antes del fopen");
  FILE *blocks_file = fopen(PATH_BLOQUES, "r");
  log_warning(logger_filesystem,"antes del if");

  char *blocks_buffer = mmap (NULL, BLOCK_SIZE * BLOCK_COUNT, PROT_WRITE | PROT_READ, MAP_SHARED, blocks_file, 0);

  if (blocks_file == NULL)
  {
    log_warning(logger_filesystem,"antes del fopen del if");
    blocks_file = fopen(PATH_BLOQUES, "w");
    memcpy(blocks_buffer, blocks_file, BLOCK_SIZE * BLOCK_COUNT);

  }

  memcpy(blocks_buffer, blocks_file, BLOCK_SIZE * BLOCK_COUNT);
  
  fclose(blocks_file);
  return blocks_buffer;
}
```

**Comment by GonzaloGarmon** [comment]
Buenasss,

Probamos utilizando el mmap pero nos sigue devolviendo errores, hicimos los cambios que mencionaste

```
char *levantar_bloques()
{
 

  log_warning(logger_filesystem,"antes del fopen");
  FILE *blocks_file = fopen(PATH_BLOQUES, "r");
  log_warning(logger_filesystem,"antes del if");

  char *blocks_buffer = mmap (NULL, BLOCK_SIZE * BLOCK_COUNT, PROT_WRITE | PROT_READ, MAP_SHARED, blocks_file, 0);

  if (blocks_file == NULL)
  {
    log_warning(logger_filesystem,"antes del fopen del if");
    blocks_file = fopen(PATH_BLOQUES, "w");
    memcpy(blocks_buffer, blocks_file, BLOCK_SIZE * BLOCK_COUNT);

  }

  memcpy(blocks_buffer, blocks_file, BLOCK_SIZE * BLOCK_COUNT);
  
  fclose(blocks_file);
  return blocks_buffer;
}
```

**Comment by iago64** [comment]
Buenas! Cómo va?

El FD que necesita `mmap()` lo obtienen con [`open()`](https://man7.org/linux/man-pages/man2/open.2.html) no con `fopen()`, por eso seguramente `mmap()` les devuelve una banda de errores.

Saludos.-

**Comment by GermanBergera** [comment]
Buenas! perdon por mantener el issue abierto bastante tiempo, acabamos de encontrar la razon de la escritura(estabamos pasandole un buffer vacio 💀) y tenia ese comportamiento extraño. Gracias por las respuestas!
