### ISSUE TITLE
Se empieza con archivos ya creados?

### ISSUE THREAD

**Issue by lucasosacuenca** [sisoputnfrba/foro#3168]
Buenas, tenia la duda de si al comenzar las pruebas, ya van a haber archivos en el directorio, mas que nada por esta parte que dice:
![image](https://github.com/sisoputnfrba/foro/assets/95377233/68004d3b-ebd3-48e3-ad04-ee5a15559e29)
donde habla que luego de levantar el bitmap, ya recorre el directorio de FCBs, para mi no tiene sentido pq sino tampoco sabriamos que hay en el archivo de bloques(o tambien ya deberia estar creado). La pregunta es si se puede obviar esa parte de recorrer el directorio, ya que no habria ningun archivo creado. Gracias

**Comment by RaniAgus** [comment]
¡Buenas! Es importante incluir esa parte porque una de las pruebas consiste en reiniciar el módulo File System y hacer que éste lea el archivo de bloques, el bitmap y los FCB que se generaron luego de correr la instancia anterior. Saludos
