### ISSUE TITLE
Consulta sobre prueba MEMO Algoritmo BEST

### ISSUE THREAD

**Issue by ezequielmalfonso** [sisoputnfrba/foro#3169]
Buenas, una consulta, sobre la pruebas de memoria, con el algoritmo BEST puede ser que no tengo que compactar?
Porque con los otros dos algoritmos nos compacta y con el BEST no.

Gracias.-

**Comment by iago64** [comment]
Buenas! Cómo va?

En la única prueba que deberían compactar es en la de WORST, por las dudas te consulto:
1.- Estan consolidando los huecos libres adyacentes luego de hacer un DELETE_SEGMENT?
2.- En que momento les salta la compactación en el caso de FIRST?

Saludos.-

**Comment by ezequielmalfonso** [comment]
Hola @iago64 muchas gracias antes que nada.
Si estamos consolidando los huecos. Nos salta aca, no se si se puede pegar el log aca, sino avisame y lo borro.
>INFO] 22:39:16:590 Memoria/(17362:17365): [KERNEL] Recibiendo solicitud de segmento para programa 0
[INFO] 22:39:16:590 Memoria/(17362:17365): [KERNEL] Se crea el proceso PID: 0 en NEW -1934524248
[INFO] 22:39:16:590 Memoria/(17362:17365): [KERNEL] Envio de segmento 0 para programa 0
[INFO] 22:39:17:077 Memoria/(17362:17365): [KERNEL] Recibiendo solicitud de segmento para programa 1
[INFO] 22:39:17:078 Memoria/(17362:17365): [KERNEL] Se crea el proceso PID: 1 en NEW -1934524248
[INFO] 22:39:17:078 Memoria/(17362:17365): [KERNEL] Envio de segmento 0 para programa 1
[INFO] 22:39:17:581 Memoria/(17362:17365): [KERNEL] Recibiendo solicitud de segmento para programa 2
[INFO] 22:39:17:581 Memoria/(17362:17365): [KERNEL] Se crea el proceso PID: 2 en NEW -1934524248
[INFO] 22:39:17:581 Memoria/(17362:17365): [KERNEL] Envio de segmento 0 para programa 2
[INFO] 22:39:17:593 Memoria/(17362:17363): [CPU] Recibido pedido de MOV_OUT
[INFO] 22:39:17:593 Memoria/(17362:17363): PID: 0 - N° Segmento: 0, Desplazamiento: 12, Tamanio: 5, Escribir: h014
[INFO] 22:39:18:594 Memoria/(17362:17363): PID: 0 - Acción: ESCRIBIR - Dirección física: 12 - Tamaño: 4 - Origen: CPU
[INFO] 22:39:18:596 Memoria/(17362:17365): [KERNEL] Solcitud de creacion de segmento
[INFO] 22:39:18:637 Memoria/(17362:17365): [KERNEL] PID: 0 - Crear Segmento id: 1 - BASE: 128 - TAMAÑO: 128
[INFO] 22:39:18:638 Memoria/(17362:17363): [CPU] Recibido pedido de MOV_IN
[INFO] 22:39:18:638 Memoria/(17362:17363): PID: 1 - N° Segmento: 0, Desplazamiento: 12, Tamanio: 4
[INFO] 22:39:19:639 Memoria/(17362:17363): PID: 1 - Acción: LEER - Dirección física: 12 - Tamaño: 4 - Origen: CPU
[INFO] 22:39:19:640 Memoria/(17362:17365): [KERNEL] Solcitud de creacion de segmento
[INFO] 22:39:19:681 Memoria/(17362:17365): [KERNEL] PID: 1 - Crear Segmento id: 1 - BASE: 256 - TAMAÑO: 64
[INFO] 22:39:19:682 Memoria/(17362:17365): [KERNEL] Solcitud de creacion de segmento
[INFO] 22:39:19:725 Memoria/(17362:17365): [KERNEL] PID: 1 - Crear Segmento id: 2 - BASE: 320 - TAMAÑO: 64
[INFO] 22:39:19:770 Memoria/(17362:17365): [KERNEL] Solcitud de creacion de segmento
[INFO] 22:39:19:813 Memoria/(17362:17365): [KERNEL] PID: 1 - Crear Segmento id: 3 - BASE: 384 - TAMAÑO: 64
[INFO] 22:39:19:858 Memoria/(17362:17365): [KERNEL] Solcitud de creacion de segmento
[INFO] 22:39:19:902 Memoria/(17362:17365): [KERNEL] PID: 1 - Crear Segmento id: 4 - BASE: 448 - TAMAÑO: 64
[INFO] 22:39:19:946 Memoria/(17362:17365): [KERNEL] Solcitud de creacion de segmento
[INFO] 22:39:19:989 Memoria/(17362:17365): [KERNEL] PID: 1 - Crear Segmento id: 5 - BASE: 512 - TAMAÑO: 64
[INFO] 22:39:20:034 Memoria/(17362:17365): [KERNEL] Solcitud de creacion de segmento
[INFO] 22:39:20:077 Memoria/(17362:17365): [KERNEL] PID: 1 - Crear Segmento id: 6 - BASE: 576 - TAMAÑO: 64
[INFO] 22:39:20:122 Memoria/(17362:17365): [KERNEL] Solcitud de creacion de segmento
[INFO] 22:39:20:165 Memoria/(17362:17365): [KERNEL] PID: 1 - Crear Segmento id: 7 - BASE: 640 - TAMAÑO: 64
[INFO] 22:39:20:210 Memoria/(17362:17365): [KERNEL] Solcitud de creacion de segmento
[INFO] 22:39:20:253 Memoria/(17362:17365): [KERNEL] PID: 1 - Crear Segmento id: 8 - BASE: 704 - TAMAÑO: 64
[INFO] 22:39:21:298 Memoria/(17362:17363): [CPU] Recibido pedido de MOV_OUT
[INFO] 22:39:21:298 Memoria/(17362:17363): PID: 1 - N° Segmento: 0, Desplazamiento: 12, Tamanio: 5, Escribir: Ch4u
[INFO] 22:39:22:298 Memoria/(17362:17363): PID: 1 - Acción: ESCRIBIR - Dirección física: 12 - Tamaño: 4 - Origen: CPU
[INFO] 22:39:22:302 Memoria/(17362:17365): [KERNEL] Recibido pedido de Eliminar segmento
[INFO] 22:39:22:345 Memoria/(17362:17365): [KERNEL] PID: 0 - Eliminar Segmento id: 1 - BASE: 128 - TAMAÑO: 128
[INFO] 22:39:22:345 Memoria/(17362:17365): Direccion del seg a llenar:128
[INFO] 22:39:22:345 Memoria/(17362:17365): creo un hueco: base:128 - tam: 128
[INFO] 22:39:22:346 Memoria/(17362:17363): [CPU] Recibido pedido de MOV_IN
[INFO] 22:39:22:346 Memoria/(17362:17363): PID: 0 - N° Segmento: 0, Desplazamiento: 12, Tamanio: 4
[INFO] 22:39:23:346 Memoria/(17362:17363): PID: 0 - Acción: LEER - Dirección física: 12 - Tamaño: 4 - Origen: CPU
[INFO] 22:39:23:352 Memoria/(17362:17365): [KERNEL] Solcitud de creacion de segmento
[INFO] 22:39:23:394 Memoria/(17362:17365): [KERNEL] PID: 1 - Crear Segmento id: 9 - BASE: 768 - TAMAÑO: 64
[INFO] 22:39:24:396 Memoria/(17362:17363): [CPU] Recibido pedido de MOV_OUT
[INFO] 22:39:24:397 Memoria/(17362:17363): PID: 1 - N° Segmento: 1, Desplazamiento: 0, Tamanio: 9, Escribir: CoscuWin
[INFO] 22:39:25:397 Memoria/(17362:17363): PID: 1 - Acción: ESCRIBIR - Dirección física: 256 - Tamaño: 8 - Origen: CPU
[INFO] 22:39:26:399 Memoria/(17362:17363): [CPU] Recibido pedido de MOV_OUT
[INFO] 22:39:26:399 Memoria/(17362:17363): PID: 1 - N° Segmento: 8, Desplazamiento: 0, Tamanio: 9, Escribir: GermanNo
[INFO] 22:39:27:399 Memoria/(17362:17363): PID: 1 - Acción: ESCRIBIR - Dirección física: 704 - Tamaño: 8 - Origen: CPU
[INFO] 22:39:27:401 Memoria/(17362:17365): [KERNEL] Solcitud de creacion de segmento
**[ERROR] 22:39:27:446 Memoria/(17362:17365): SOLICITAR COMPACTACION**
[WARNING] 22:39:27:446 Memoria/(17362:17365): Tiempo de compactacion: 60000
[INFO] 22:40:27:446 Memoria/(17362:17365): Segmento encontado PID:1 - Seg. Id:1 - base:256
[INFO] 22:40:27:447 Memoria/(17362:17365): Nueva direccion del Seg ID: 1  - Dir. Base: 128
[INFO] 22:40:27:447 Memoria/(17362:17365): Segmento encontado PID:1 - Seg. Id:2 - base:320
[INFO] 22:40:27:449 Memoria/(17362:17365): Nueva direccion del Seg ID: 2  - Dir. Base: 192
[INFO] 22:40:27:450 Memoria/(17362:17365): Segmento encontado PID:1 - Seg. Id:3 - base:384
[INFO] 22:40:27:451 Memoria/(17362:17365): Nueva direccion del Seg ID: 3  - Dir. Base: 256
[INFO] 22:40:27:451 Memoria/(17362:17365): Segmento encontado PID:1 - Seg. Id:4 - base:448
[INFO] 22:40:27:451 Memoria/(17362:17365): Nueva direccion del Seg ID: 4  - Dir. Base: 320
[INFO] 22:40:27:451 Memoria/(17362:17365): Segmento encontado PID:1 - Seg. Id:5 - base:512
[INFO] 22:40:27:451 Memoria/(17362:17365): Nueva direccion del Seg ID: 5  - Dir. Base: 384
[INFO] 22:40:27:451 Memoria/(17362:17365): Segmento encontado PID:1 - Seg. Id:6 - base:576
[INFO] 22:40:27:452 Memoria/(17362:17365): Nueva direccion del Seg ID: 6  - Dir. Base: 448
[INFO] 22:40:27:452 Memoria/(17362:17365): Segmento encontado PID:1 - Seg. Id:7 - base:640
[INFO] 22:40:27:452 Memoria/(17362:17365): Nueva direccion del Seg ID: 7  - Dir. Base: 512
[INFO] 22:40:27:452 Memoria/(17362:17365): Segmento encontado PID:1 - Seg. Id:8 - base:704
[INFO] 22:40:27:452 Memoria/(17362:17365): Nueva direccion del Seg ID: 8  - Dir. Base: 576
[INFO] 22:40:27:453 Memoria/(17362:17365): Segmento encontado PID:1 - Seg. Id:9 - base:768
[INFO] 22:40:27:453 Memoria/(17362:17365): Nueva direccion del Seg ID: 9  - Dir. Base: 640
[INFO] 22:40:27:453 Memoria/(17362:17365): FIN COMPACTACION
[INFO] 22:40:27:490 Memoria/(17362:17365): [KERNEL] Solcitud de creacion de segmento
[INFO] 22:40:27:490 Memoria/(17362:17365): [KERNEL] PID: 2 - Crear Segmento id: 1 - BASE: 704 - TAMAÑO: 256
[INFO] 22:40:27:534 Memoria/(17362:17363): [CPU] Recibido pedido de MOV_IN
[INFO] 22:40:27:535 Memoria/(17362:17363): PID: 2 - N° Segmento: 0, Desplazamiento: 12, Tamanio: 4
[INFO] 22:40:28:535 Memoria/(17362:17363): PID: 2 - Acción: LEER - Dirección física: 12 - Tamaño: 4 - Origen: CPU
[INFO] 22:40:28:537 Memoria/(17362:17363): [CPU] Recibido pedido de MOV_IN
[INFO] 22:40:28:537 Memoria/(17362:17363): PID: 1 - N° Segmento: 1, Desplazamiento: 0, Tamanio: 8
[INFO] 22:40:29:537 Memoria/(17362:17363): PID: 1 - Acción: LEER - Dirección física: 128 - Tamaño: 8 - Origen: CPU
[INFO] 22:40:29:538 Memoria/(17362:17365): [KERNEL] Recibido pedido de Eliminar segmento
[INFO] 22:40:29:582 Memoria/(17362:17365): [KERNEL] PID: 1 - Eliminar Segmento id: 1 - BASE: 128 - TAMAÑO: 64
[INFO] 22:40:29:582 Memoria/(17362:17365): Direccion del seg a llenar:128
[INFO] 22:40:29:582 Memoria/(17362:17365): creo un hueco: base:128 - tam: 64
[INFO] 22:40:29:582 Memoria/(17362:17363): [CPU] Recibido pedido de MOV_IN
[INFO] 22:40:29:582 Memoria/(17362:17363): PID: 1 - N° Segmento: 8, Desplazamiento: 0, Tamanio: 8
[INFO] 22:40:30:583 Memoria/(17362:17363): PID: 1 - Acción: LEER - Dirección física: 576 - Tamaño: 8 - Origen: CPU
[INFO] 22:40:30:584 Memoria/(17362:17365): [KERNEL] Recibido pedido de Eliminar segmento
[INFO] 22:40:30:625 Memoria/(17362:17365): [KERNEL] PID: 1 - Eliminar Segmento id: 2 - BASE: 192 - TAMAÑO: 64
[INFO] 22:40:30:625 Memoria/(17362:17365): Direccion del seg a llenar:192
[INFO] 22:40:30:626 Memoria/(17362:17365): [KERNEL] Recibido pedido de Eliminar segmento
[INFO] 22:40:30:670 Memoria/(17362:17365): [KERNEL] PID: 1 - Eliminar Segmento id: 4 - BASE: 320 - TAMAÑO: 64
[INFO] 22:40:30:670 Memoria/(17362:17365): Direccion del seg a llenar:320
[INFO] 22:40:30:670 Memoria/(17362:17365): creo un hueco: base:320 - tam: 64
[INFO] 22:40:30:671 Memoria/(17362:17365): [KERNEL] Recibido pedido de Eliminar segmento
[INFO] 22:40:30:714 Memoria/(17362:17365): [KERNEL] PID: 1 - Eliminar Segmento id: 5 - BASE: 384 - TAMAÑO: 64
[INFO] 22:40:30:715 Memoria/(17362:17365): Direccion del seg a llenar:384
[INFO] 22:40:30:718 Memoria/(17362:17365): [KERNEL] Solcitud de creacion de segmento
[INFO] 22:40:30:762 Memoria/(17362:17365): [KERNEL] PID: 2 - Crear Segmento id: 2 - BASE: 128 - TAMAÑO: 128
[INFO] 22:40:30:855 Memoria/(17362:17365): [KERNEL] PID: 2 - Eliminar Segmento id: 2 - BASE: 128 - TAMAÑO: 128
[INFO] 22:40:30:855 Memoria/(17362:17365): Direccion del seg a llenar:128
[INFO] 22:40:30:855 Memoria/(17362:17365): [KERNEL] PID: 2 - Eliminar Segmento id: 1 - BASE: 704 - TAMAÑO: 256
[INFO] 22:40:30:855 Memoria/(17362:17365): Direccion del seg a llenar:704
[INFO] 22:40:30:855 Memoria/(17362:17365): ELIMINACION DE PROCESO PID: 2
[INFO] 22:40:30:855 Memoria/(17362:17365): ELIMINACION DE PROCESO PID: 0
[INFO] 22:40:30:855 Memoria/(17362:17365): [KERNEL] PID: 1 - Eliminar Segmento id: 9 - BASE: 640 - TAMAÑO: 64
[INFO] 22:40:30:855 Memoria/(17362:17365): Direccion del seg a llenar:640
[INFO] 22:40:30:855 Memoria/(17362:17365): [KERNEL] PID: 1 - Eliminar Segmento id: 8 - BASE: 576 - TAMAÑO: 64
[INFO] 22:40:30:855 Memoria/(17362:17365): Direccion del seg a llenar:576
[INFO] 22:40:30:855 Memoria/(17362:17365): [KERNEL] PID: 1 - Eliminar Segmento id: 7 - BASE: 512 - TAMAÑO: 64
[INFO] 22:40:30:855 Memoria/(17362:17365): Direccion del seg a llenar:512
[INFO] 22:40:30:855 Memoria/(17362:17365): [KERNEL] PID: 1 - Eliminar Segmento id: 6 - BASE: 448 - TAMAÑO: 64
[INFO] 22:40:30:855 Memoria/(17362:17365): Direccion del seg a llenar:448
[INFO] 22:40:30:855 Memoria/(17362:17365): [KERNEL] PID: 1 - Eliminar Segmento id: 3 - BASE: 256 - TAMAÑO: 64
[INFO] 22:40:30:855 Memoria/(17362:17365): Direccion del seg a llenar:256
[INFO] 22:40:30:856 Memoria/(17362:17365): ELIMINACION DE PROCESO PID: 1

**Comment by iago64** [comment]
Buenas! Cómo va?

¿Es posible que la validación la tengan con menor estricto? Porque en el momento que les llega la creación del Proceso C (o PID 2) de tamaño 256, debería entrar al final de la memoria.
El problema me parece que lo tienen al momento de crear el S9 del PID 1:

```
[INFO] 22:39:23:394 Memoria/(17362:17365): [KERNEL] PID: 1 - Crear Segmento id: 9 - BASE: 768 - TAMAÑO: 64
```
Esto debería quedar en la base 128, no 768.

Saludos.-

**Comment by ezequielmalfonso** [comment]
@iago64 muchas gracias, ahí lo pudimos solucionar ayer,  estábamos haciendo mal una comparación adentro del algoritmo.

Muchas gracias por tu respuesta.

**Comment by iago64** [comment]
Buenísimo, si está resuelto el problema recuerden que pueden cerrar el issue.
