### ISSUE TITLE
mover elementos al compactar

### ISSUE THREAD

**Issue by Ariel-Hab** [sisoputnfrba/foro#3170]
Hola, queria confirmar si tras compactar (osea si muevo de lugar los segmentos)  debo mover tambien la informacion contenida (localizada en la memoria dentro de los limites de dichos segmento).

**Comment by RaniAgus** [comment]
¡Buenas! Definitivamente sí deberían hacerlo, ya que al compactar el inicio de cada segmento cambia, por ende, la misma dirección lógica va a traducirse a una dirección física distinta.

Si solamente modificaras las entradas de las tablas de segmentos sin mover la información que hay en cada uno, al momento de leer no estarías accediendo a los mismos datos que el proceso escribió previamente.

Saludos

**Comment by Ariel-Hab** [comment]
Graciass
