### ISSUE TITLE
manejo de punteros indirectos

### ISSUE THREAD

**Issue by lucasosacuenca** [sisoputnfrba/foro#3171]
Buenas, estoy con una duda sobre el bloque de punteros indirectos, en el caso de que yo tenga que incializar, truncar, lo que sea y no se llegue a completar el bloque de punteros(entran 4 punteros de 4bytes y yo solamente uso 2) no encuentro al forma de como llenar ese espacio, mas que nada para si por ejemplo tengo que leer ese bloque saber el limite de punteros que tengo, se me habia ocurrido ponerles -1 para saber q es espacio donde no hay punteros pero usamos uint32_t, me pueden tirar una ayuda de como manejar eso? gracias

**Comment by RaniAgus** [comment]
¡Buenas! Pueden deducir cuántos bloques tiene asignado el archivo a partir de su tamaño. Saludos

**Comment by lucasosacuenca** [comment]
tal cual, gracias

**Comment by lucasosacuenca** [comment]
perdon, volviendo al tema del tamaño, el puntero indirecto se tiene en cuenta? por ejemplo si el size del archivo es de 256bytes, cada bloque soporta 64bytes, tendria 1 directo, el indirecto y 4 dentro de ese indirecto o 3?

**Comment by RaniAgus** [comment]
El size del archivo coincide con el tamaño que recibe `F_TRUNCATE` como parámetro. Por ejemplo, si el `BLOCK_SIZE` es 64 y se ejecuta `F_TRUNCATE ARCHIVO 256` quedarían indexados 4 bloques: 1 directo del FCB y 3 indirectos del bloque de punteros.

Si bien ese archivo tendría 5 bloques reservados en el bitmap (1 para el bloque de punteros y 4 para datos del archivo), el size solo considera el espacio utilizable por el usuario.

**Comment by lucasosacuenca** [comment]
perfecto gracias
