### ISSUE TITLE
Pruebas filesystem

### ISSUE THREAD

**Issue by Martin-Fedorenko** [sisoputnfrba/foro#3172]
Buenas noches! 
Realizando las pruebas de filesystem no surgió la siguiente inquietud:

Luego de hacer FS_1 y FS_2 tenemos que ejecutar FS_3 cuatro veces en distintas consolas. El primer proceso que ejecute FS_3 usa un archivo y en teoría bloquearía a los demás procesos que intenten acceder a ese archivo. Pero como se bloquearían dichos procesos si nunca tratan de acceder a dicho archivo. FS_3 no tiene ninguna instrucción que desaloje el proceso actual y deje ejecutar a otro, y en consiguiente permita que otro proceso intente acceder al archivo y quede bloqueado.

FS_3 no tendría que tener alguna instrucción como YIELD o I/O para desalojar el proceso actual y que deje ejecutar a los demás (y permitir que queden bloqueados)?

![image](https://github.com/sisoputnfrba/foro/assets/67556470/f95547aa-594e-40b3-9431-7a45b9e8f57f)

**Comment by ncoen97** [comment]
Buenas Martin!

La primer instrucción de FS_3 es `F_OPEN`, y esta implica un pasaje a bloqueado. Entonces las consolas que vayan ejecutando van pasando a bloqueado y solo van a salir cuando se libere el recurso (`F_CLOSE`) y lo puedan abrir.

Saludos.

**Comment by Martin-Fedorenko** [comment]
Me confunde un poco que F_OPEN pase a bloqueado. Siempre que hago fopen se me va a bloquear mi proceso? O solo si el archivo sobre cuál hago fopen ya está siendo usado por otro proceso?

Por otra parte, si siempre se me bloquea mi proceso por hacer fopen, cómo lo desbloqueo al proceso si soy yo quien esta usando la única instancia del archivo.

Capaz me estoy confundiendo el estado BLOQUEADO con un proceso bloqueado por un archivo.

**Comment by iago64** [comment]
Buenas! Cómo va?

Solo tienen que bloquearlo si lo tiene abierto otro proceso. Cito al enunciado:

> **F_OPEN**: Esta función será la encargada de abrir o crear el archivo pasado por parámetro. Dado que el Kernel maneja una tabla global de archivos abiertos y una tabla por cada proceso, es posible que se den los siguientes escenarios:
>- La tabla global de archivos abiertos tenga este archivo, se agrega la entrada en la tabla de archivos abiertos del proceso con el puntero en la posición 0 y se bloqueará al proceso que ejecutó F_OPEN en la cola correspondiente a este archivo.
>- El archivo no esté presente en la tabla global de archivos abiertos, se deberá consultar al módulo File System si existe o no el archivo.


Saludos.-

**Comment by ncoen97** [comment]
Creo que la confusión viene por el lado de que una vez que se abre el archivo, no se necesita que el proceso quede en Exec (porque realmente lo que se ejecutan son las instrucciones). Una vez que se abre, el proceso es desalojado y pasa a ready para luego poder ejecutar las otras instrucciones.

**Comment by Martin-Fedorenko** [comment]
Ahhhh ahora todo tiene sentido!

Ejecutó el proceso -> se ejecuta el fopen -> desalojo el proceso -> dejo que otro proceso ejecute.

Otra consulta. Además de fopen, wait (en algunos casos), i/o, yield y éxit. Que otra instrucción desaloja al proceso actual de cpu y del estado exec?

**Comment by ncoen97** [comment]
Cito enunciado:

> Durante el transcurso de la ejecución de un proceso, se irá actualizando su Contexto de Ejecución, que luego será devuelto al Kernel bajo los siguientes escenarios: finalización del mismo (instrucción EXIT o ante un error), necesitar ser bloqueado (instrucción I/O o WAIT), peticiones al Kernel (F_* y *_SEGMENT), o pedir ser desalojado (YIELD).

**Comment by Martin-Fedorenko** [comment]
Perfecto, muchísimas gracias!!!

**Comment by Martin-Fedorenko** [comment]
Buenas tardes! Releyendo el TP me tope con este fragmento:

"En esta implementación, el módulo Kernel recibirá el Contexto de Ejecución de la CPU con motivo de ejecutar un CREATE_SEGMENT o un DELETE_SEGMENT y realizará la rutina correspondiente manteniendo el proceso en estado EXEC."

No estaría contradiciendo este otro?:

"Durante el transcurso de la ejecución de un proceso, se irá actualizando su Contexto de Ejecución, que luego será devuelto al Kernel bajo los siguientes escenarios: finalización del mismo (instrucción EXIT o ante un error), necesitar ser bloqueado (instrucción I/O o WAIT), peticiones al Kernel (F_* y *_SEGMENT), o pedir ser desalojado (YIELD)."
