### ISSUE TITLE
Problemas de Deploy

### ISSUE THREAD

**Issue by joaco-bruno** [sisoputnfrba/foro#3174]
Hola estoy intentando clonar distintas vms desde virtual box para poder hacer las pruebas pero por algun motivo me trae siempre la misma ip. Ejecute el scipt que  deberia funcionar pero no. Vi otros issues donde se recomendaron otros comandos pero nada. Tienen idea como podria solucionar esto? Alguna alternativa para probar ( que no sea ir a la facu) ?

desde ya gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Podes subir la captura de como tenes la config de las vms? Especialmente la parte red?

Saludos.-

**Comment by joaco-bruno** [comment]
Te paso captura de las configs y y lo que me responde el "ifconfig"


![image](https://github.com/sisoputnfrba/foro/assets/111391917/fbb0006b-dede-4ba4-8876-aa2ba340763d)
![image](https://github.com/sisoputnfrba/foro/assets/111391917/6e3d8a5d-def9-4c22-ba02-fc477d4ffed7)

![image](https://github.com/sisoputnfrba/foro/assets/111391917/db7018f7-6e6f-4963-90fe-04a01ed2baf8)
![image](https://github.com/sisoputnfrba/foro/assets/111391917/bae01c42-bfac-4ca8-8c49-794e9a826696)

**Comment by iago64** [comment]
Buenas!

Ahí prueben de ejecutar los siguientes comandos:

```bash
sudo dhclient -r
sudo dhclient
```

Ya que no tienen ipv4 en el adaptador enp0s3 que es el que deberían usar, el adaptador lo es el de loopback y es basicamente la llamada al localhost.

Saludos.-

**Comment by joaco-bruno** [comment]
No termine de entender lo que me dijiste. Pero tire ambos comandos en todas las virtuales ( por ahora 2) y el segundo se queda pensando y no hace nada. Cual seria el puerto que deberiamos usar? Deberiamos elegir otro adaptador? 

![image](https://github.com/sisoputnfrba/foro/assets/111391917/b59896ce-3521-49cb-bffe-3e5b5203aa80)

**Comment by iago64** [comment]
Buenas!

Los adaptadores estan bien, lo que decía es que tienen que ver la ip que les trae el adaptador:
![image](https://github.com/sisoputnfrba/foro/assets/1622109/eeacbd43-63e4-4fc8-ba3c-a9efe0f157d7)

Ahi fijate que tenes una dirección `inet6` y no `inet`

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Espero no haber llegado tarde 😅 

Estuve haciendo algunas pruebas y al parecer mi router asigna IPv6 cuando estoy conectado por WiFi, pero no tengo ningún problema conectándome por LAN.

También probé de levantar un server usando la dirección IPv6 (y el flag `AF_UNSPEC` para que `getaddrinfo()` acepte ambos tipos de IP), pero luego el `connect()` falla por "Invalid argument".

De todas formas parece que cambiando el adaptador de `enp` a `wlp` mi router sí me asignó una IPv4 (`inet`):

![image](https://github.com/sisoputnfrba/foro/assets/39303639/2e6418b4-8799-48be-b295-cca7e05d9364)

Prueben haciendo ese cambio a ver si en su caso también se resuelve.

Saludos
