### ISSUE TITLE
Conexiones

### ISSUE THREAD

**Issue by LucasGelabert** [sisoputnfrba/foro#3175]
Tenemos una duda porque nosotros ya hicimos las conexiones y lo hicimos tal que primero se prende el kernel y despues se conectan todos los modulos entre si, pero en el enunciado, como esta citado abajo, dice que primero el modulo de File System se conecta con memoria y luego espera conexion con el kernel, entonces...
Es necesario que sigamos ese orden o podriamos usar el nuestro?

### 📔 Citas del enunciado/videos

>Este módulo File System será el encargado de persistir la información por medio de una serie de archivos. Estos archivos, se encontrarán configurados dentro del archivo de configuración.
El File System será un cliente más del módulo Memoria y será servidor del módulo Kernel.
Lineamiento e Implementación
Al iniciarse el módulo, se conectará con la Memoria y realizará un handshake inicial para verificar que se está conectando correctamente.

**Comment by mesaglio** [comment]
Buenas, pueden iniciar los modulos en el orden que quieran.

Salu2!
