### ISSUE TITLE
Problema con ultima prueba de FS

### ISSUE THREAD

**Issue by matikalo** [sisoputnfrba/foro#3176]
Buenas, estamos teniendo problemas con la prueba de filesystem 3 (FS_3), que cuando al ejecutarla normalmente por primera vez es interrumpida de manera incorrecta, sin embargo luego al ejecutarla nuevamente, genera el comportamiento esperado.

Les dejamos, de dos primeras ejecuciones, el output:

![image](https://github.com/sisoputnfrba/foro/assets/44058368/1078eb70-5c09-4689-8efe-98cc994555d6)

![image](https://github.com/sisoputnfrba/foro/assets/44058368/f7188edb-550d-462a-9d30-25dcddc7aca3)

Y otro de cuando ejecuta correctamente:

![image](https://github.com/sisoputnfrba/foro/assets/44058368/eeaf07a8-6f20-4841-9320-29b491a872a6)

Como se observa, en las primeras fotos no pasa del segundo proceso, mientas que en la tercera finaliza correctamente.

Ademas, ejecutamos con valgrind y no aparecieron "invalid reads" ni "invalid writes".

Desde ya, muchas gracias.

**Comment by RaniAgus** [comment]
¡Buenas! ¿Podrían correr varias pruebas con Valgrind y pasarnos los logs de cada una (por separado)? Me parece muy improbable que no detecte un memory corruption.
También, si es un problema que ocurre a veces, pueden estar teniendo condiciones de carrera. Prueben de correr el programa con Helgrind (en la 2da mitad de la charla grabada del [tutorial](https://faq.utnso.com.ar/valgrind) hay una explicación de su output).

Saludos

**Comment by guidogelvan** [comment]
Buenas! Ahi pudimos solucionarlo, parece que era una condicion de carrera. La duda que nos surgio al ver el memcheck es la siguiente.

Cuando observamos los memory leaks en el Heap summary obtenemos que la mayoria de los bytes reservados son liberados pero en el Leak summary arroja una cantidad interesante de bytes. No sabemos en que poner el foco de atencion (Por si las dudas, matamos el programa a traves de Control + C). Estuvimos revisando la guia de Valgrind pero seguimos teniendo dudas en cuanto a que preocuparnos o no.

Un ejemplo es este en CPU:
![image](https://github.com/sisoputnfrba/foro/assets/82114359/fc720796-3d28-46e2-8363-0e3f825de667)

![image](https://github.com/sisoputnfrba/foro/assets/82114359/52fcaf46-cffa-4d33-9670-0af3c2d9be81)
Como se observa en la primer foto, se libera un porcentaje alto del Heap.
Saludos!

**Comment by RaniAgus** [comment]
¡Buenas! Como dice la guía, no hay de qué preocuparse con still reachable y possibly lost, por lo que sí deben tener en cuenta los demás (definitely lost y indirectly lost).

En este caso tienen casi 50k de memoria reservada al proceso que no se está utilizando en 2200 mallocs distintos. Si bien no buscamos el 0 ideal, es un número bastante grande.

Saludos
