### ISSUE TITLE
Problema con levantar la VM Server

### ISSUE THREAD

**Issue by felipenani** [sisoputnfrba/foro#3177]
Buenas tardes, como va? Armo el issue porque estoy teniendo [serios] inconvenientes con el inicio de la VM Server. Me descargue del [link de drive ](https://drive.google.com/drive/folders/1Pn1SveTGkEVfcc7dYAr1Wc10ftEe8E0J) que esta en utnso y de inicio ya me resulta raro que al descomprimir el .rar únicamente me extraiga el Server.vdi y no también un .zip.001 como le ha sucedido a compañeros a los cuales le funciona (adjunto foto de mi carpeta de VMs)
![image](https://github.com/sisoputnfrba/foro/assets/82170825/1bcadb64-0a1c-467a-82d3-4ab000c12af8)
Sin embargo, eso tanto no me preocupa; si bien tengo leves sospechas, no sabría decirlo con seguridad ya que a la Grafica también le falta el .zip.001 (solo tiene el 002) pero anda sin ningún inconveniente, todo joya.

Después de todo el contexto, les comento que de todas formas decido ignorar eso e intentar crear la VM Server en VirtualBox, y al iniciarla me sucede lo siguiente. (perdón por la captura pero no me deja copiar el texto)
![image](https://github.com/sisoputnfrba/foro/assets/82170825/68f8b78c-0040-4a41-beeb-d099ffdf25e8)

### 🔎 Búsqueda en foros
Buscando en este foro vi que hay issues como el #1609 y el #1010, pero las soluciones que se propusieron no me sirvieron. Por supuesto que intente eliminando la VM y creándola nuevamente, y hasta borrar y reinstalar dicho .zip pero no hubo caso.

### 📦 Especificaciones de la VM
En cuanto a las especificaciones pienso que esto puede servir, no lo se, pero también intente cambiar el sistema operativo entre Ubuntu, Lubuntu y Xubuntu (todos de 64-bit)
![image](https://github.com/sisoputnfrba/foro/assets/82170825/5aca8454-f11b-4276-b901-f0d70bdea483)

Desde ya muchas gracias.

**Comment by iago64** [comment]
Buenas! Cómo va?

Vamos en orden con algunas cosas.
En primer lugar, que no veas las extensiones de los archivos es algo propio de windows, eso lo podes cambiar desde la opción de view o vista (si tenes windows en español).
Mas allá de eso, el problema del kernel panic, puede venir por el lado de que no esté bien el archivo bajado, en la [página de docs](https://docs.utnso.com.ar/primeros-pasos/entorno-linux) hay una guía de como descargar y descomprimir los archivos y por las dudas recomendamos 7zip en lugar de winrar ya que fue la herramienta que se uso para generar los archivos y además te recomiendo que checkees que los MD5 de los archivos te den bien antes de descomprimir, los mismos están en la [página de descargas](https://docs.utnso.com.ar/recursos/vms#xubuntu)

Saludos.-

**Comment by felipenani** [comment]
Con respecto a lo primero, joya, ya vi lo de la visualizacion de las extensiones, sin embargo lo comentaba mas que nada porque arriba en la grafica si me aparecia el ".zip.002" y como que no tenia sentido que algunos los muestre y otros no, pero es casi indiferente, lo resaltaba porque veia diferencias jaja. 
Luego con el tema de descomprimir; si, me olvide de mencionarlo en el issue y justo se lo estaba comentando a un compañero. Ya probe desinstalando y volviendo a instalar pero usar 7zip en lugar de WinRar y tampoco anduvo, y los md5 son coincidentes con los que indica la guia de utnso.
De todas formas mañana pedire prestada una computadora a un familiar asi puedo ver si es tema de mi computadora en particular, es la unica solucion que vi en el corto plazo hasta el momento.

**Comment by iago64** [comment]
Si los MD5 te dan iguales entonces la segunda opción que puede estar complicando las cosas es que tengas la virtualización habilitada desde el BIOS, eso es un poco mas complicado de que nos pases un screen, pero fijate de entrar al BIOS de tu pc y fijate si tenes AMD-V o Intel-VT (dependiendo del fabricante de tu procesador), eso debería estar desactivado para evitarte inconvenientes con virtualbox.

Saludos.-

**Comment by felipenani** [comment]
Buenas, probe tal como dijiste vos y el issue #1010 desde la BIOS y no puedo levantar maquinas virtuales, ni siquiera las graficas jajaja. Me sale el siguiente mensaje en VirtualBox: 
![image](https://github.com/sisoputnfrba/foro/assets/82170825/2ff1a6c1-d9ab-444f-93ab-79ef183e97d9)
La ventana de la izquierda es el administrador de tareas que en apartado de CPU dentro de Rendimiento me permite ver el estado de la virtualizacion (Deshablitado). Voy a volverlo a activar asi puedo seguir trabajando sobre el codigo porque pareceria que no pasa por aca. De todas formas sigo investigando que puede llegar a ser. Saludos

**Comment by iago64** [comment]
Ok, lo de la virtualización deshabilitada algo de sentido tiene, ahora te pregunto, como tenes las configuraciones dentro de la parte de sistema de virtual box? Podes pasarnos las capturas? 😊

**Comment by felipenani** [comment]
Obvio ahi adjunto la captura. Los procesadores no se si influiran, es mas, no creo porque probe con 1, con 2 y mismo ahora con 3 je.
![image](https://github.com/sisoputnfrba/foro/assets/82170825/028b7f62-18de-48fc-889e-2cbe107cab0e)

Te referis a estas configuraciones generales o más bien a alguna en especifico dentro de alguna solapa en la ruedita de configuracion como "Orden de arranque"  en "Sistema", por ejemplo.

**Comment by iago64** [comment]
Te estaba por pedir la configuración puntual dentro de la parte de Sistema, pero ahi veo que tenes habilitada la paginación anidada, proba de extraer un VDI nuevo y no activar esa opción, se de varios casos que eso trajo problemas 😢

**Comment by felipenani** [comment]
Damian, sabes que ni bien termine de redactar este issue dije "vamos a probar levantarla de nuevo" porque me habia olvidado de activar la virtualizacion despues de que no haya funcionado, y esta vez arranco jajajaja

![image](https://github.com/sisoputnfrba/foro/assets/82170825/f0094b69-d4fe-4ee3-ade5-bf46505dbb92)

Asi que nada, error rarisimo que se soluciono desactivando y activando nuevamente la virtualizacion, como enchufar y desenchufar pero bien a la raiz je. Pero excelente, de todas formas muchas gracias por las respuestas!! Cierro el issue.
Saludos.
