### ISSUE TITLE
Duda compactacion prueba fs

### ISSUE THREAD

**Issue by Ariel-Hab** [sisoputnfrba/foro#3178]
Hola, estabamos corroborando detalles de las pruebas del tp y nos dimos cuenta que cuando termina la prueba fs 1 y 2 se espera lo siguiente:  "La compactación no inicia hasta que no finalizan las lecturas / escrituras pendientes en el FS.". Pero el tema es que la prueba fs2 es desbloqueada por el signal RB de fs1 y luego entra a ejecutar porque fs1 se bloquea al hacer fwrite, entonces va a arrancar a ejecutar fs2 y por ende compactar antes de que termine fwrite y vuelva a ready fs1. Adjunto igual logs de kernel que se entienden mejor:
![image](https://github.com/sisoputnfrba/foro/assets/129193075/3b3cb1a5-d15f-40e6-87ca-403731db57e9)
![image](https://github.com/sisoputnfrba/foro/assets/129193075/02dd9fdc-cd9c-4c12-b0c6-70fb4f28f2e3)
![image](https://github.com/sisoputnfrba/foro/assets/129193075/dc4683dd-ebdf-484d-a9f1-5cea9eeda38a)

**Comment by LeandroCarbajales** [comment]
Buenas!
Es justamente lo que buscamos, cito al enunciado:

> Compactación de Memoria
Al momento de recibir de la Memoria el mensaje que indica que se dispondría del espacio solicitado post compactación, el Kernel deberá primero validar que no se estén ejecutando operaciones entre el File System y la Memoria (F_READ y F_WRITE).
En caso de que se tengan operaciones del File System en curso, el Kernel deberá esperar la finalización de las mismas para luego proceder a solicitar la compactación a la Memoria.

Es decir, aunque la compactación se pida desde el proceso "fs2" mientras se está realizando un fwrite, el Kernel debe esperar a que finalice la misma antes de darle la orden a Memoria de compactar.

Queda más clara la idea?
Saludos!

**Comment by Ariel-Hab** [comment]
Dale mil gracias

**Comment by Ariel-Hab** [comment]
otra consulta, en la semana hay algun dia q hayan ayudantes en medrano para hacer pruebas? o ya no lo hacen mas?

**Comment by iago64** [comment]
Buenas! 

No, durante la semana no va a haber ayudantes, solo el sábado para la entrega y si se cruzan a alguno posiblemente este rindiendo algún final.

Saludos.-

**Comment by Ariel-Hab** [comment]
oka gracias
