### ISSUE TITLE
Error en el decode de la instruccion EXIT

### ISSUE THREAD

**Issue by FranPenaUtn** [sisoputnfrba/foro#3179]
Buenas tardes!
El sabado pasado fuimos a medrano a hacer la entrega del TP y tuvimos un error que en nuestras PCs no estabamos teniendo y en las computadoras del laboratorio si. 
El problema se daba al momento de ejecutar la instrucción EXIT. Al leer dicha instruccion en lugar de tomar los 4 caracteres, solo se tomaba el primer caracter _**E**_, lo que causaba que no entrara en la lógica correspondiente y nunca finalizara el proceso.
Quisiera aclarar que este error no pudimos replicarlo en nuestras PC's y no entendemos a que se debe este cambio de funcionamiento. 

### 📝 Código relevante
```
//se busca la instruccion completa a partir del contexto
char* instruccion = buscar_instruccion(contexto);
char** instruccion_decodificada = decodificar(instruccion);

//funciones usadas arriba
char* buscar_instruccion(t_contexto* contexto) {
	return list_get(contexto->instrucciones, contexto->program_counter);
}

char** decodificar(char* instruccion) {
	char** instruccion_decodificada = string_split(instruccion, " ");
}

```

Basicamente ese es el código relevante en cuanto al FETCH y DECODE de instrucciones. Luego que obtenemos el array con la instruccion y sus argumentos, tenemos un IF gigante para validar que instruccion tenemos que ejecutar.

ejemplo reducido:
```
if(!strcmp(instruccion[0], "SET")) {
    //logica set
} else if(!strcmp(instruccion[0], "EXIT")){
    //logica exit
}
```
El problema es que,como comentaba antes, para la instruccion EXIT no entraba en ningun IF ya que dentro de la variable `instruccion[0]` el valor era `'E'`. 

Gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

En sus pcs, estan corriendo la VM server o como están corriendo las pruebas? Es una pregunta rara porque no debería afectar por el código que vemos.

Por las dudas, corrieron la CPU con valgrind y no les tiro nada de invalid read / invalid write?

De todas formas, la opción que pueden hacer, si solo les pasa con EXIT es dejar el EXIT como la opción por default... es decir, si no reconocieron ninguna otra instrucción bueno, que sea EXIT, no es la solución más "prolija" pero sería una solución que les permitiría terminar las pruebas.

Saludos.-
