### ISSUE TITLE
error al correr log_info()

### ISSUE THREAD

**Issue by lucasosacuenca** [sisoputnfrba/foro#3180]
Buenas, estoy teniendo un error cuando uso el log info, viene corriendo bien, y cuando quiere hacer devuelta un log info me tira el error:
`realloc(): invalid next size`  tengo entendido que es algo de memoria, pero nose como solucionarlo, les dejo el codigo para q vean como viene funcionando: 
```
log_info(logger_consola,"Estoy en send_instruccion_consola_kernel"); 
t_buffer *buffer_send = buffer_create();
parsear_pseudocodigo(buffer_send, PATH_INSTRUCCIONES, logger_consola);
log_info(logger_consola,"se parseo las instrucciones");
``` 
el primer log_info lo hace bien, adentro de parsear `pseudocodigo()` unicamente realiza log_info(), no usa el logger para nada mas, despues cuando vuelve y quiere hacer `log_info(logger_consola,"se parseo las instrucciones");`  tira el error `realloc(): invalid next size`

**Comment by iago64** [comment]
Buenas! Cómo va?

Como siempre les pedimos, por favor cuando tengan errores relacionados con memoria (`malloc()`, `free()`, `realloc()`, etc) por favor suban el log de valgrind asi podemos darles una mano.

Lo mas probable es que esten pisando la memoria y no se estén enterando.
Saludos.-

**Comment by lucasosacuenca** [comment]
ahi con valgrind estamos avanzando, gracias!
