### ISSUE TITLE
Stack Smashing en Memoria en F Write

### ISSUE THREAD

**Issue by Danymmereles** [sisoputnfrba/foro#3181]
Buenas noches,

Perdonen la hora. Andabamos realizando las pruebas @nrvargas @ailendr  y en el momento de realizar el F Write, estamos teniendo un problema al mandar lo que se almaceno en Memoria a File System. Son las mismas funciones utilizadas en Move In, que funciona correctamente y verificamos que el Move Out almacena correctamente la información también. Probamos distintas alternativas:

**### _CASO 1:_**
![Imagen de WhatsApp 2023-08-03 a las 23 52 01](https://github.com/sisoputnfrba/foro/assets/47753130/f35520b4-5437-4d1f-9ce2-e1ffbf73d953)
![Imagen de WhatsApp 2023-08-03 a las 23 53 09](https://github.com/sisoputnfrba/foro/assets/47753130/70de4c0b-11f3-4344-b7b2-a4d727471ffd)
![Imagen de WhatsApp 2023-08-03 a las 23 56 49](https://github.com/sisoputnfrba/foro/assets/47753130/2a59a860-90b6-49ae-9f0d-fdadf16ba2da)

Como pueden ver, al momento de guardar en el memcpy, se observa que en numSeg esta guardando PlayStation2 cuando tiene que almacenarlo solamente en valorAGuardar. Debajo dejamos lo que imprime cada uno de los módulos luego de esta sección de código.

![Imagen de WhatsApp 2023-08-03 a las 23 59 06](https://github.com/sisoputnfrba/foro/assets/47753130/3ae4a8b4-d64e-4d32-b357-d080a7bc5b27)
![Imagen de WhatsApp 2023-08-04 a las 00 06 11](https://github.com/sisoputnfrba/foro/assets/47753130/315bb77b-13a7-46ba-91c5-7ad50b38e249)

**### _CASO 2:_**
![Imagen de WhatsApp 2023-08-04 a las 00 26 45](https://github.com/sisoputnfrba/foro/assets/47753130/dbb197b3-b81f-44b0-be87-fbd269ac9a46)
![Imagen de WhatsApp 2023-08-04 a las 00 12 29](https://github.com/sisoputnfrba/foro/assets/47753130/c7331490-502a-40f4-a713-3f8bd8a35322)

Aca no ocurre stack smashing porque estamos usando el stream de un t_buffer para copiar la informacion con el memcpy, pero no entendemos porque el FS no lo recibe correctamente como se puede visualizar en las imagenes debajo

![Imagen de WhatsApp 2023-08-04 a las 00 16 24](https://github.com/sisoputnfrba/foro/assets/47753130/a2dc209a-747b-46b1-88a0-7e5b77882b75)
![Imagen de WhatsApp 2023-08-04 a las 00 15 00](https://github.com/sisoputnfrba/foro/assets/47753130/40aa1c67-b2ab-4cca-b0f0-b76aa0ddc16b)

En ambos casos se corrieron con Valgrind y al momento de buscar ayuda en los issues no encontramos nada que nos pudiera dar una mano.

Desde ya muchisimas gracias

**Comment by Danymmereles** [comment]
![Imagen de WhatsApp 2023-08-04 a las 15 53 01](https://github.com/sisoputnfrba/foro/assets/47753130/c335167e-45d3-4ab4-88fd-6a833ca3cb6a)

Tambien estuvimos intentando por este lado pero no nos funciono tampoco y el stack smashing seguia (tratamos de reformular la cuenta)

![Imagen de WhatsApp 2023-08-04 a las 15 53 09](https://github.com/sisoputnfrba/foro/assets/47753130/73648730-e486-4cd2-ae8e-6e60147a39f0)

**Comment by RaniAgus** [comment]
¡Buenas, Dany! Antes que nada, si bien las capturas con el debugger son muy útiles para entender el estado de todas las variables línea por línea, estaría buenísimo poder contar con las porciones de código en texto así podemos copiar y pegarlas para probar por nuestra cuenta. 

Por ejemplo, justo iba a comentar algo sobre la línea 325 de la primera captura, y no llego a ver todo el `memcpy()` porque me tapa el IDE 😓 

Dicho esto, veo que en varios lugares reservan memoria para guardar el valor a enviar:
```c
char *valorAEnviar = malloc(bytes + 1);
```
![File_000 (3)](https://github.com/sisoputnfrba/foro/assets/39303639/c386ac6c-9db0-4335-9d50-fda95c04ddf9)

Y luego pisan ese puntero con el valor a enviar:
```c
memcpy(&valorAEnviar, ...);
```
![File_000 (4)](https://github.com/sisoputnfrba/foro/assets/39303639/f9b3a47a-eeaa-41fc-93dc-28d0130844de)

En lugar de pisar _el contenido_, es decir:
```c
memcpy(valorAEnviar, ...);
```
![File_000 (5)](https://github.com/sisoputnfrba/foro/assets/39303639/34142a5e-9fec-4c14-875b-2fcd8b98c555)

Probablemente Valgrind no solo les arroje un stack smashing, sino que además en el reporte del final debería estar el memory leak.

Pude reproducirlo en este ejemplito:
```c
#include <string.h>
#include <stdlib.h>
#include <stdio.h>

int main(int argc, char* argv[]) {
    char *m = malloc(12);
    memcpy(&m, "Hello world", 12);

    return 0;
}
```
```
==13826== Memcheck, a memory error detector
==13826== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==13826== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==13826== Command: ./bin/project.out
==13826== 
*** stack smashing detected ***: terminated
==13826== 
==13826== Process terminating with default action of signal 6 (SIGABRT)
==13826==    at 0x4905A7C: __pthread_kill_implementation (pthread_kill.c:44)
==13826==    by 0x4905A7C: __pthread_kill_internal (pthread_kill.c:78)
==13826==    by 0x4905A7C: pthread_kill@@GLIBC_2.34 (pthread_kill.c:89)
==13826==    by 0x48B1475: raise (raise.c:26)
==13826==    by 0x48977F2: abort (abort.c:79)
==13826==    by 0x48F86F5: __libc_message (libc_fatal.c:155)
==13826==    by 0x49A5769: __fortify_fail (fortify_fail.c:26)
==13826==    by 0x49A5735: __stack_chk_fail (stack_chk_fail.c:24)
==13826==    by 0x1091EC: main (main.c:10)
==13826== 
==13826== HEAP SUMMARY:
==13826==     in use at exit: 12 bytes in 1 blocks
==13826==   total heap usage: 1 allocs, 0 frees, 12 bytes allocated
==13826== 
==13826== 12 bytes in 1 blocks are definitely lost in loss record 1 of 1
==13826==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==13826==    by 0x1091B4: main (main.c:6)
==13826== 
==13826== LEAK SUMMARY:
==13826==    definitely lost: 12 bytes in 1 blocks
==13826==    indirectly lost: 0 bytes in 0 blocks
==13826==      possibly lost: 0 bytes in 0 blocks
==13826==    still reachable: 0 bytes in 0 blocks
==13826==         suppressed: 0 bytes in 0 blocks
==13826== 
==13826== For lists of detected and suppressed errors, rerun with: -s
==13826== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```

Saludos
