### ISSUE TITLE
👩‍💻 ¿Buscás Grupo / Integrantes para el 2c2023? ¡Posteá ACA! 👨‍💻

### ISSUE THREAD

**Issue by LeandroCarbajales** [sisoputnfrba/foro#3182]
¡Buenas!

Con el objetivo de unificar todos los post de búsqueda de grupos / integrantes, vamos a centralizarlo en este post.

Les recomendamos encarecidamente que traten de NO publicar números de celular y limitarse solo a los mails. Tengan en cuenta que el foro es público, por lo que pueden llegar a quedar en alguna lista de spam o que les hable gente que no quieran.

Saludos!

**Comment by lucholud** [comment]
Buenas! Curso: K3673/K3573 Estoy buscando grupo, la primera vez cursando la materia. Mi mail es lluduena@frba.utn.edu.ar 
Comprometido en afrontar hasta el final la materia.

Saludos.

**Comment by matibrewda** [comment]
Buenas, algun grupo buscando un integrante? Disponibilidad para conectarme en la semana a la mañana o a la tarde. Sabados tambien.
Contacto: mbrewda@frba.utn.edu.ar
Saludos!

**Comment by nicolasgalfione** [comment]
Hola! Somos 2 personas recursando la materia que buscamos grupo, necesitamos gente que preferentemente haya cursado ya la materia como para poder empezar a meterle apenas nos den el tp y llevarlo siempre al día con las entregas, y también que este decidida a afrontar la materia sin dejarla en ninguna instancia. Pueden escribirme al mail de la facu ngalfione@frba.utn.edu.ar

**Comment by GonzaloRDuart** [comment]
Buenas! estoy buscando un grupo, preferencialmente gente de los cursos K3574/3674 (Miercoles a la noche). Es la primera vez que curso la materia pero estoy comprometido, si no la apruebo pierdo una promoción 😅. Dejo mi mail para cualquiera que este interesado/a: goduarte@frba.utn.edu.ar

**Comment by Ignaciofmunoz** [comment]
Buenas, soy del curso K3574/3674 (Miercoles a la noche),  busco grupo,soy recursante dejo mi email: ignacio40309782yahoo.com

Saludos

**Comment by tomaslcarballo** [comment]
Buenas! Tenemos un grupo de 4 personas en donde la mayoria somos del curso K3673/K3573.
Dejo mi mail por si alguien que este comprometido con la materia se quiere sumar, tcarballo@frba.utn.edu.ar.
Saludos!

**Comment by jlserrudo** [comment]
Buenas!! Estoy en la búsqueda de grupo.  Es la primera vez que curso y me anote solo en esta materia en este cuatrimestre para tener mas disponibilidad. Les dejo mi correo jserrudo@frba.utn.edu.ar.
Saludos!!!!

**Comment by fedecassina** [comment]
Buenas! Estoy buscando grupo para el TP. La curse el cuatrimestre pasado. Soy del curso K3672 (viernes noche). Dejo mi mail fcassinacarbia@frba.utn.edu.ar

**Comment by FrancoVillaverdeJesus** [comment]
Buenas! Estoy buscando grupo para el TP, es la segunda vez que la curso y es la única materia que voy a cursar este cuatrimestre. Soy del curso K3523 (Sábados a la mañana). Les dejo mi mail fvillaverdejesus@frba.utn.edu.ar
Saludos

**Comment by JuanFreH** [comment]
Buenas! Busco grupo para el TP. Soy del curso K3574/3674 (Miercoles Noche). Curse la materia el cuatrimestre pasado. 
Dejo mi email: jfreyre@frba.utn.edu.ar

Saludos

**Comment by JoaquinYoko** [comment]
Hola qué tal, estamos en búsqueda de 2 personas para unirse a nuestro grupo. Preferiblemente no-recursantes así estamos todos en la misma. Interesados a: jnegrete@frba.utn.edu.ar

Saludos!

**Comment by vrojas2022** [comment]
Hola, busco integrantes para armar grupo (4 lugares disponibles), preferentemente que cursen Martes a la noche (no excluyente), soy recursante, sean recursantes o no,  la idea es seguir la materia. Interesados a: vrojas@frba.utn.edu.ar

**Comment by KevinQ73** [comment]
Muy buenas, busco integrarme a un grupo que esté dispuesto a seguir la materia todo lo que quede del año y llegar con tiempo a las entregas del TP. Soy recursante del cuatrimestre pasado. Cualquier cosa, manden correo a kquinones@frba.utn.edu.ar

**Comment by ealon2** [comment]
Buenas :hand:  Estamos en la busqueda de 3 integrantes para el armado del grupo, somos recursantes de la materia y estamos en la busqueda de gente preferentemente con conocimientos en C, git, etc, y que haya trabajado en el TP0 :muscle: 
Contacto: ezequiel.fiasche@frba.utn.edu.ar

**Comment by LautaroRomero21** [comment]
Buenas, estoy cursando los sabados en el curso K3523 a la mañana y nos faltan 3 integrantes para formar el grupo. El que quiera unirse mandeme un mail a lromerogalvan@frba.utn.edu.ar

**Comment by jlserrudo** [comment]
Buenas, vuelvo a escribir porque me olvide poner el curso!! Estoy en la búsqueda de grupo. Es la primera vez que curso y me anote solo en esta materia en este cuatrimestre para tener mas disponibilidad, curso en el k3574 los miercoles a la noche y sabados a la tarde . Les dejo mi correo [jserrudo@frba.utn.edu.ar](mailto:jserrudo@frba.utn.edu.ar).
Saludos!!!!

**Comment by Plata92** [comment]
Buenas, estoy buscando grupo para el Tp, curso los sabados a la mañana. les dejo mi mail: plata@frba.utn.edu.ar

**Comment by josebarreto97** [comment]
Buenas, que tal? Estoy buscando grupo para el tp, curso los miércoles a la noche (K3673). Estoy cursando esta materia junto a Comunicaciones y me comprometo en meterle. Les dejo mi mail: josebarreto@frba.utn.edu.ar

**Comment by rlarrart** [comment]
Buenas, estoy buscando grupo para el TP, curso en K3572 los viernes a la noche y los sábados a la tarde. Les dejo mi mail: rlarrart@frba.utn.edu.ar

**Comment by laugonzalezutn** [comment]
Hola, todo bien? Estoy buscando un grupo, o formar uno tambien, para el TP. Estoy cursando los miércoles a la noche y sábados a la tarde. Mi email es: laugonzalez@frba.utn.edu.ar

**Comment by FrancoVillaverdeJesus** [comment]
Buenas! Estamos buscando gente para formar grupo somos 2, es la segunda vez que la curso y es la única materia que voy a cursar este cuatrimestre. Soy del curso K3523 (Sábados a la mañana). Les dejo mi mail fvillaverdejesus@frba.utn.edu.ar
Saludos

**Comment by JulianFernandezMakusas** [comment]
Hola, busco grupo para el TP, curse la materia el cuatrimestre pasado, llegando a desarrollar la mitad del tp. Curso los sábados a la mañana, dejo mi correo: jfernandezmakusas@frba.utn.edu.ar. Saludos

**Comment by karelysr** [comment]
Hola, estoy buscando grupo para unirme, soy del curso miercoles en la noche, mi mail es krangelsalcedo@frba.utn.edu.ar

**Comment by fdavinsonegoavil** [comment]
Hola, soy del curso K3571 Lu TN, soy recursante y busco grupo mi mail es fdavinsonegoavil@frba.utn.edu.ar
Saludos!

**Comment by FV-Cano** [comment]
## ¡sOS!

Buenas! Dejando de lado el chiste malo, estamos buscando un último integrante para nuestro grupo de Sistemas Operativos. Aviso de antemano por las dudas, que los integrantes del grupo no coincidimos en los días de cursada. Así que si hay alguna persona que quiere que todos compartan el mismo día de cursada (como vi en algunas publicaciones), les dejo saber que no cumplimos con ese requisito.
Más allá de eso, los requisitos para entrar al grupo son:
Gracias por leer los requisitos.

Bueno, ahora si. El requisito es lo que se espera de cualquier participante, poder trabajar en equipo, resolver los problemas / responder dudas entre todos y hacer todo lo posible para hacer una buena cursada.

Por último y ya con esto termino, para que nos conozcan un poco más. Como les dije somos 4 personas, 2 ya cursaron en su momento la materia y otros 2 (yo incluido), es la primera vez que la cursamos. Ya estuvimos discutiendo entre nosotros más o menos las metodologías de trabajo y seguramente usemos como herramientas (además de las obligatorias) Discord, Trello y organicemos una weekly para comentar los avances.

Si les interesa, les dejo mi mail para estar en contacto! fecano@frba.utn.edu.ar

**Comment by Damuchi99** [comment]
Buenas tardes, recursante aquí.
Estoy buscando grupo para el TP que esté dispuesto a **_seguir la materia_** y **_llegar con tiempo a cada uno de los checkpoints del TP_**.
Curso los sábados a la mañana.
Mi mail para contacto es: daalvarez@frba.utn.edu.ar

**Comment by everlizarraga** [comment]
Hola. Soy recursante.
Tengo conocimientos en C y estoy buscando meterle a full a esta materia.
Curso los  miércoles a la noche, tengo disponibilidad horaria en la semana y los findes.
Mail de contacto: everlizarraga@frba.utn.edu.ar

**Comment by tomasgerardi07** [comment]
¡Buenos días!

Estamos incorporando personas a nuestro grupo para el TP, somos 2 por el momento. Cursamos los sábados a la mañana.
Somos 2 recursantes, hicimos el TP el cuatrimestre pasado completo, la idea es poder ayudarnos y comprometernos entre todos para poder finalmente dar bien este nuevo TP.

Nuestra metodología es muy simple, una o dos reuniones por semanas para comentar avances y ayudarnos con los bloqueantes que podamos llegar a tener para poder seguir avanzando. De igual forma, durante la semana siempre estamos activos ya sea por grupo de Whatsapp o Discord para resolver cualquier problema que presentemos.

Les dejo nuestros mails de contacto:
tgerardi@frba.utn.edu.ar
acappellacci@frba.utn.edu.ar

Muchas gracias y buena cursada para todos!

**Comment by juan9772** [comment]
Buenas!
Tenemos un grupo de 4 y nos está faltando un integrante, cursamos los miércoles y viernes a la mañana en la comisión k3524
si alguno está interesado puede escribirme a: 
jtamayomazo@frba.utn.edu.ar 

Saludos a todos!

**Comment by CristianClaros** [comment]
Buenas!
Soy recursante curso los Lunes K3571, busco grupo para meterle pilas desde el principio.
Mi mail: cclaroschoque@fra.utn.edu.ar
Saludos a todos

**Comment by FedericoEncinazSayago** [comment]
¡Buenas! 

A raíz de la creación de grupos en Sistemas Operativos para el Trabajo Práctico, estamos en búsqueda de un quinto integrante para terminar de conformar el grupo. 
Si estás dispuesto a aportar ideas, no dudes en escribirme a: fencinazsayago@frba.utn.edu.ar

Curso: K5375 - sábado a la tarde

**Comment by Ariel-Michelli** [comment]
Buenas gente!!, Busco grupo soy recusante con los parciales aprobados, en lo posible un grupo que le meta garra a full y apunte a la promo, la materia es difícil pero se puede!. 
Dejo mi mail: [amichellilescano@frba.utn.edu.ar](mailto:amichellilescano@frba.utn.edu.ar)
PD: curso los sábados a la mañana(K3623), sé que no aporta nada, pero es un detalle de color. Saludos!

**Comment by corona6054** [comment]
Hola gente, somos un grupo de 4 integrantes y estábamos buscando un integrante para completar el grupo.
Somos recursantes y estamos cursando el martes a la mañana.
Si te interesa mi mail es: vcorona@frba.utn.edu.ar
Saludos!

**Comment by jfr4nc0** [comment]
Buenas, estoy buscando grupo, la curse el cuatri pasado y voy a encarar directamente la resolución del tp, estoy buscando grupo que sean recursantes. Cualquier cosa me escriben a jcanossa@frba.utn.edu.ar
Gracias!

**Comment by Ariel-Michelli** [comment]
Buenas Joan, ya conseguiste grupo para SO?. Que días cursas la materia?

________________________________

**Comment by JuanCarlosFRBA** [comment]
Buenas, estoy buscando grupo para TP. Cualquier cosa me escriben a jgrageda@frba.utn.edu.ar . curso los martes a la noche.
Desde ya muchas gracias

**Comment by agusocampo145** [comment]
Buenas! Agustin aca, Curso de Martes a la noche! Buscando grupo, soy yo solo! Cualquier cosa me escriben a oca_a@outlook.com.ar.

Saludos!!

**Comment by francoalanoca** [comment]
Buenas!!
Ando armando grupo, de momento nos estaría faltando 2, de preferencia viernes/miércoles noche, pero sino no hay problema escribime noma.
Cualquier cosa me escribís por acá: falanocavillarreal@frba.utn.edu.ar

Saludos, Franco.

**Comment by Zeta2003x** [comment]
Buenas,
Estamos armando grupo y faltan 2 personas, lo queremos hacer en vscode.
Los 3 cursamos los miércoles a la noche.

Si te interesa escribime a mgrin@frba.utn.edu.ar

Saludos, Matías.

**Comment by BrianVillarroel94** [comment]
Hola gente, ando en busca de grupo para el TP soy recursante , estoy en el curso K3572 (Viernes por la noche) 
Dejo mi mail: bvillarroelrocha@frba.utn.edu.ar

**Comment by FedericoEncinazSayago** [comment]
Buenas! Cómo andan? Estamos en busqueda de nuestros 4º y 5º integrantes!

Qué te ofrecemos?

Un equipo comprometido que utiliza Discord para comentar avances y superar bloqueos juntos, asegurando un progreso constante. Además, contamos con un Trello para que puedas ver nuestro avance en cualquier momento.

Qué necesitamos? Compromiso, y ganas de afrontar juntos a éste trabajo práctico.

Dónde vamos a plantear el trabajo? La idea principal es usar Visual Studio Code, en conjunto con MakeFiles.

Contacto (✉): fencinazsayago@frba.utn.edu.ar

**Comment by favrissio** [comment]
Buenas tardes,

Estoy en la búsqueda de grupo para el trabajo practico. Curso los miércoles a la noche y es la primera vez que hago la materia.
Mi intención es meterle pilas a la cursada y seguirla hasta el final del cuatrimestre.
Respecto al grupo me gustaría que todos trabajemos parejo, para poder aprender y sacar adelante el tp de la mejor manera.

Dejo mi correo por cualquier consulta:  fabriciofernandez@frba.utn.edu.ar

**Comment by LautaroRobles** [comment]
Buenas tardes.

Estamos buscando 2 integrantes mas para completar nuestro grupo.
Vamos a utilizar VSCode y Makefile, ya tenemos un entorno preparado.
Necesitamos gente que este dispuesta a llevar el TP hasta fin de cuatri.

**Comment by jfr4nc0** [comment]
Buenas gente, nos hacen falta dos personas mas en el grupo, ya tenemos el ambiente de desarrollo levantado. 
Cualquier cosa me confirman por mi mail: jcanossa@frba.utn.edu.ar
Gracias!

**Comment by ZekielLTK** [comment]
Buenas gente, como estan?
Estamos en busca de nuestro quinto integrante para el grupo. Nosotros cursamos los sabados a la mañana, pero estamos abiertos a cualquiera que se quiera unir, mientras le ponga las ganas necesarias para poder afrontar el TP todos juntos.
Si alguno esta interesado, me pueden escribir a mi mail: elitvak@frba.utn.edu.ar

**Comment by CristianClaros** [comment]
Hola buenas tardes. como están?
Estamos buscando el 5to integrante para completar el grupo.
Si alguno esta interesado, mi mail es: cclaroschoque@fra.utn.edu.ar

**Comment by KevinQ73** [comment]
Buenas, tendrían lugar todavía en su grupo?

**Comment by KevinQ73** [comment]
Buenas noches, busco agruparme a un grupo que tenga ganas de trabajar y de sacar adelante al TP. Soy recursante del cuatrimestre pasado y dispongo de tiempo como para ayudar en lo que necesiten. Si me quieren contactar, manden mail a kquinones@frba.utn.edu.ar

**Comment by LucasTomas** [comment]
Buenos dias, mi nombre es Lucas y formo parte de la comision k3652 los viernes a la noche y sabado a la tarde. Nuestro grupo consta de 4 integrantes y nos faltaria uno. Dejo mi email lubarrera@frba.utn.edu.ar cualquiera que este interesado mandeme un mesaje. Saludos

**Comment by LucasTomas** [comment]
Hola, disculpa pero ya estamos completos

**Comment by adrianquispe** [comment]
buenas, estoy en busca de grupo, curso los sabados a la mañana, si algun grupo necesita un integrante le dejo mi correo aquisperamos@frba.utn.edu.ar

**Comment by lukagreco9** [comment]
Buenas estoy en búsqueda de un grupo, curso los miércoles a la noche. Dejo mi mail lgreco@frba.utn.edu.ar y mi celular 1136298612.

**Comment by favrissio** [comment]
Buenas tardes,

Nos están faltando dos integrantes para completar el grupo. Somos una persona del martes y dos del miércoles, ambos a la noche. 
Si alguien todavía esta sin grupo y esta interesado en sumarse se puede contactar a mi correo: fabriciofernandez@frba.utn.edu.ar

**Comment by GreenGeer** [comment]
Buenas busco grupo, curso los viernes la noche , soy recursante.
Mail: germanvautier@hotmail.com 
Cel: 1130702260
