### ISSUE TITLE
Puertos CPU

### ISSUE THREAD

**Issue by juanibencardino** [sisoputnfrba/foro#3183]
Buenasss
Con mi grupo teniamos una duda con los puertos de escucha del CPU, por los configs de este se ve que tiene 2, el del dispatch y el del interrupt. 
Lo que nos dimos cuenta es que en el config del kernel hay 1 solo puerto del cpu, y este no coincide con ninguno de los dos del config de cpu. Es porque el cpu a parte tiene un puerto general que falta agregar? O el kernel tiene que enviar al dispatch? (se que esto deberia estar en la consigna). Yo creo que el kernel puede enviar por los dos puesrtos es asi? Faltaria agregar puertos en el config de kernel?

### 📔 Citas del enunciado/videos

![image](https://github.com/sisoputnfrba/foro/assets/83251119/ffdc3b56-68d0-416e-918c-e14530ea1c95)

![image](https://github.com/sisoputnfrba/foro/assets/83251119/3e55f04f-aa31-43af-a1bd-8247e4b1f378)

@folaciregui  @nmolina02

**Comment by folaciregui** [comment]
Perfecto, gracias!!
Saludos.

**Comment by RaniAgus** [comment]
Un placer! No olviden cerrar el issue una vez resuelta la duda/consulta :)
