### ISSUE TITLE
No puedo compilar y ejecutar el servidor

### ISSUE THREAD

**Issue by jlserrudo** [sisoputnfrba/foro#3185]
Buenas.

Mi duda es la siguiente, estoy en la etapa 3 del tp0, y no puedo compliar y ejecutar el servidor.
Quise hacerlo como dice el video, desde la consola del ubuntu, pero me sale el siguiente error
```
utnso@utnso:~/tp0$ ls
client  README.md  server
utnso@utnso:~/tp0$ cd server
utnso@utnso:~/tp0/server$ ls
Debug  log.log  Release  src
utnso@utnso:~/tp0/server$ make
make: *** No targets specified and no makefile found.  Stop.
utnso@utnso:~/tp0/server$ cd Release
utnso@utnso:~/tp0/server/Release$ make
rm -rf ./src/server.d ./src/server.o ./src/utils.d ./src/utils.o
rm -rf server
 
utnso@utnso:~/tp0/server/Release$ ./server
bash: ./server: No such file or directory
```

No logro enender como usar el make para compliar y luego para ejecutar. Habra otro metodo para hacerlo

**Comment by RaniAgus** [comment]
¡Buenas! Inicialmente, les recomiendo prestar más atención a el output de los comandos que ejecutan, ya que suelen proveer muy buena información sobre lo que falló. Para empezar:
```
make: *** No targets specified and no makefile found.  Stop.
```
En resumen, esto dice que no se encontró un archivo llamado `makefile` dentro de esa carpeta. Ese archivo es una especificación que luego usa `make` para entender cómo compilar el código C.

Más adelante:
```
rm -rf ./src/server.d ./src/server.o ./src/utils.d ./src/utils.o
rm -rf server
```
Este `make` ejecutó el comando `rm`, el cual como verán en la [guía de Bash](https://docs.utnso.com.ar/guias/consola/bash) (y pueden practicar en el tutorial interactivo Mario Bash que está linkeado en la guía) sirve para eliminar archivos, no para compilar. El comando que usamos para compilar es `gcc`

Por lo tanto, si intentan ejecutar algo, les va a aparecer que no existe:
```
bash: ./server: No such file or directory
```

Dicho esto, si bien el TP0 está pensado para ser compilado directamente desde Eclipse, también deberían poder hacerlo moviéndose con `cd` hacia la carpeta `Debug` de cada proyecto y ejecutando `make` desde ahí:

```bash
cd server/Debug
make
```
Luego de ejecutar `make`, este comando imprime por pantalla todos los comandos `gcc` que usa para compilar. Si no ocurrió ningún error, al ejecutar `ls` verán al binario ya creado.

Dato: Al ejecutar el `ls` en esa carpeta verán que ahí sí hay un archivo `makefile`. Es el que se usó para compilar :)

Luego, para ejecutarlo de la misma forma que lo hace Eclipse, les recomiendo moverse un paso atrás y ejecutar el binario desde esa carpeta, o sea:

```
cd ..
./Debug/server
```

Los motivos por los cuales hacemos esta sugerencia están detallados en [esta guía](https://docs.utnso.com.ar/guias/consola/rutas)

¡Saludos!

**Comment by jlserrudo** [comment]
hola buenas, Si tambien lo quise hacer desde el debug pero me sigue sin compilar, adjunto la consola

utnso@utnso:~/tp0$ cd server
utnso@utnso:~/tp0/server$ ls
Debug  log.log  Release  src
utnso@utnso:~/tp0/server$ cd Debug
utnso@utnso:~/tp0/server/Debug$ ls
makefile  objects.mk  sources.mk  src
utnso@utnso:~/tp0/server/Debug$ make
rm -rf ./src/server.d ./src/server.o ./src/utils.d ./src/utils.o
rm -rf server

**Comment by RaniAgus** [comment]
Qué raro... me bajé el TP0 desde el repo y pude compilarlo:
```
@RaniAgus ➜ /workspaces/tp0 (master) $ cd server/Debug
@RaniAgus ➜ /workspaces/tp0/server/Debug (master) $ make
Building file: ../src/server.c
Invoking: GCC C Compiler
gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/server.d" -MT"src/server.o" -o "src/server.o" "../src/server.c"
Finished building: ../src/server.c
 
Building file: ../src/utils.c
Invoking: GCC C Compiler
gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/utils.d" -MT"src/utils.o" -o "src/utils.o" "../src/utils.c"
../src/utils.c: In function ‘iniciar_servidor’:
../src/utils.c:12:37: warning: unused variable ‘p’ [-Wunused-variable]
   12 |  struct addrinfo hints, *servinfo, *p;
      |                                     ^
Finished building: ../src/utils.c
 
Building target: server
Invoking: GCC C Linker
gcc  -o "server"  ./src/server.o ./src/utils.o   -lcommons
Finished building target: server
 
@RaniAgus ➜ /workspaces/tp0/server/Debug (master) $ ls
makefile  objects.mk  server  sources.mk  src
```
Si aún no commitearon nada pueden revertir lo que haya cambiado ejecutando (desde la carpeta del tp0):
```
git checkout server/Debug
git checkout client/Debug
```
Sino, prueben de abrir el proyecto desde Eclipse y compilarlo con el martillito 🔨, quizás el IDE modifica los makefiles automáticamente y lo logra compilar. De ser así, cuando intenten compilar desde consola con `make` van a obtener el mismo resultado.

**Comment by jlserrudo** [comment]
Hola buenas, al final el git checkout server/Debug y logro compilar. Porque pudo haber pasado el error anterior? Al hacer el checkout vuelve al estado anterior, y tambien lo hace makefile?

Te comento que desde el eclipse si compilaba el server pero desde la consola no lo hacia. Eso lo decía porque una parte del tp0 decia que tanto el server y el client tendria que estar en ejecucion para comunicarse. 
El client lo ejecutaba desde el eclipse y el server lo hacia desde la consola del ubuntu. Se podra ejecutar tanto el server como el client en el eclipse?

**Comment by RaniAgus** [comment]
> Hola buenas, al final el git checkout server/Debug y logro compilar. Porque pudo haber pasado el error anterior? Al hacer el checkout vuelve al estado anterior, y tambien lo hace makefile?

Honestamente no sé por qué pudo haber ocurrido, pero sí, al hacer `git checkout` se revierten todos los cambios que no hayan agregado con `git add`.

> Te comento que desde el eclipse si compilaba el server pero desde la consola no lo hacia. Eso lo decía porque una parte del tp0 decia que tanto el server y el client tendria que estar en ejecucion para comunicarse.
El client lo ejecutaba desde el eclipse y el server lo hacia desde la consola del ubuntu. Se podra ejecutar tanto el server como el client en el eclipse?

Se puede, para hacerlo seleccionen el proyecto a ejecutar y denle al ▶️:

![image](https://github.com/sisoputnfrba/foro/assets/39303639/4063fc2c-6cab-4efa-aa56-8aa7f0ad0ac9)

Una vez iniciados ambos, van a poder switchear entre consolas en el menú de abajo:

![image](https://github.com/sisoputnfrba/foro/assets/39303639/868cd49b-720c-41f5-9965-9c504e7b29e1)


También otra cosa que pueden hacer es compilar 🔨 desde Eclipse y ejecutar el archivo ya compilado usando la consola:

```
cd tp0/server
./Debug/server
```

**Comment by jlserrudo** [comment]
Muchas gracias por el aporte

**Comment by RaniAgus** [comment]
@jlserrudo ¡No hay de qué! No se olviden de cerrar el issue una vez resuelta la duda/consulta :)
