### ISSUE TITLE
Consulta sobre configuracion VSCode (siguiendo issue #1878)

### ISSUE THREAD

**Issue by patriciojgf** [sisoputnfrba/foro#3186]
Hola, buenas

Estoy tratando de encarar el TP en VSCode, veo que hace unos años se hizo una guia con video (https://github.com/sisoputnfrba/foro/issues/1878).
En una parte se configura el c_cpp_properties.json, dentro de uno de los ultimos cambios es que se paso a 32bits. 
Alguien me puede orientar a si tengo que ponerle clang-x64 en lugar de ""intelliSenseMode": "clang-x86"? 
[link archivo en git](https://github.com/dariokozicki/utnso-vscode/blob/master/proceso1/.vscode/c_cpp_properties.json)

Muchas gracias

El contenido del archivo en cuestión:

{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}",
                "/usr/include/c++/5",
                "/usr/include/i386-linux-gnu/c++/5",
                "/usr/include/c++/5/backward",
                "/usr/lib/gcc/i686-linux-gnu/5/include",
                "/usr/local/include",
                "/usr/lib/gcc/i686-linux-gnu/5/include-fixed",
                "/usr/include/i386-linux-gnu",
                "/usr/include",
                "${workspaceFolder}/include",
                "../shared/include"
            ],
            "defines": ["_GNU_SOURCE"],
            "intelliSenseMode": "clang-x86",
            "browse": {
                "path": [
                    "${workspaceFolder}",
                    "${workspaceFolder}/include",
                    "../shared/include",
                    "/usr/include/c++/5",
                    "/usr/include/i386-linux-gnu/c++/5",
                    "/usr/include/c++/5/backward",
                    "/usr/lib/gcc/i686-linux-gnu/5/include",
                    "/usr/local/include",
                    "/usr/lib/gcc/i686-linux-gnu/5/include-fixed",
                    "/usr/include/i386-linux-gnu",
                    "/usr/include"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++17"
        }
    ],
    "version": 3
}

**Comment by patriciojgf** [comment]
me falto incluir, al momento lo modifique 
-cambiando a 64
-cambiando las carpetas "i386-linux-gnu" a la que encontré que es  "aarch64-linux-gnu" 
-cambiand c++/5 a c++/11 que es lo que veo en la VM

de todas formas me quedan todos los archivos del proyecto en verde, como untracked que entiendo este archivo me lo tendria que solucionar.

lo deje asi:

{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}",
                "/usr/include/c++/11",
                "/usr/include/aarch64-linux-gnu/c++/11",
                "/usr/include/c++/11/backward",
                "/usr/lib/gcc/aarch64-linux-gnu/11/include",
                "/usr/local/include",
                "/usr/include/aarch64-linux-gnu",
                "/usr/include",
                "${workspaceFolder}/include",
                "../shared/include"
            ],
            "defines": ["_GNU_SOURCE"],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "${workspaceFolder}",
                    "${workspaceFolder}/include",
                    "../shared/include",
                    "/usr/include/c++/11",
                    "/usr/include/aarch64-linux-gnu/c++/11",
                    "/usr/include/c++/5/backward",
                    "/usr/lib/gcc/aarch64-linux-gnu/11/include",
                    "/usr/local/include",
                    "/usr/include/aarch64-linux-gnu",
                    "/usr/include"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++17"
        }
    ],
    "version": 3
}

**Comment by RaniAgus** [comment]
¡Buenas! Ese video fue un aporte que en su día le sirvió a muchos grupos a trabajar en VSCode cuando las VMs eran de 32 bits. Con el tiempo se fue iterando la idea y ya en [docs](https://docs.utnso.com.ar/guias) tenemos linkeada una guía al respecto que está actualizada a las VMs de 64 bits: https://raniagus.github.io/so-project-template/

Peguenle una leída y avísennos si surge alguna duda o problema :)

Saludos

**Comment by patriciojgf** [comment]
> ¡Buenas! Ese video fue un aporte que en su día le sirvió a muchos grupos a trabajar en VSCode cuando las VMs eran de 32 bits. Con el tiempo se fue iterando la idea y ya en [docs](https://docs.utnso.com.ar/guias) tenemos linkeada una guía al respecto que está actualizada a las VMs de 64 bits: https://raniagus.github.io/so-project-template/
> 
> Peguenle una leída y avísennos si surge alguna duda o problema :)
> 
> Saludos

perfecto, ahi lo adapte a ese template, muchas gracias.
