### ISSUE TITLE
Implementacion de Hilos

### ISSUE THREAD

**Issue by Mimito164** [sisoputnfrba/foro#3188]
La verdad no se si esta pregunta me la puedan contestar o sea una cuestión que deba resolver con mi grupo... pero no pierdo nada preguntando...

No se bien como plantear el esquema de conexiones entre módulos, mas que nada si vale la pena implementar hilos o no. Tenía pensado hacer que el modulo memoria tenga un hilo por cada cliente, FS y CPU en principio no deberían necesitar hilos, Kernel seguramente use hilos, primero porque me lo canto el enunciado:

> _el Kernel será el encargado de gestionar las peticiones contra la Memoria y el File System, por lo que deberá implementarse siguiendo una estrategia multihilo que permita la concurrencia de varias solicitudes provenientes de diferentes orígenes._

Pero no estoy seguro si implementar un hilo por cada servidor (algo parecido a como esta organizado el modulo memoria) o si organizar un hilo por cada tipo de petición que tenga que responder, por ejemplo, que haya un hilo encargado de responder consultas sobre  el estado de la "tabla global de archivos abiertos".

Creo que al final va a terminar siendo muy parecidas las dos estrategias, lo que me serviría saber es si le estoy pifiando a la estrategia y me la estoy re complicado  o si conviene alguna de estas dos ideas que planteé.

Muchas gracias.

**Comment by RaniAgus** [comment]
¡Buenas! Probablemente en este TP para CPU, Memoria y FS sea más sencillo determinar cuántos hilos crear ya que son módulos que reciben una consulta, la procesan y devuelven una respuesta.

No es así para Kernel, ya que es el encargado de iniciar esas consultas a los otros módulos, por lo que creo que sería un poco rebuscado pensar en hilos que responden consultas. Es éste el que debe iniciarlas y obtener una respuesta de los demás módulos.

En definitiva, la forma de plantear cuántos hilos se crean en Kernel, qué responsabilidades tiene cada uno, qué recursos comparten (como productor y como consumidor) no es tan trivial sino que es algo a definir por cada grupo. 

Al leer más en profundidad la especificación del módulo se van a encontrar con que varias tareas sí o sí tienen que ocurrir en paralelo, así que van a necesitar distintos hilos para procesarlas. Por ejemplo, mandar un proceso en Exec a ejecutar ciclos de CPU y otro en Blocked a leer un archivo del FS.

Como consejo para encarar esta parte, suele ser útil hacer algo parecido a los ejercicios de sincro: una tabla con una columna por hilo y algo de lógica a alto nivel sobre qué responsabilidades y recursos compartidos requiere cada uno.

Si quieren charlar sobre lo que decidan implementar, estamos disponibles los sábados de soporte ;)

Saludos
