### ISSUE TITLE
Como hago para correr el client.c y el server.c a la vez?

### ISSUE THREAD

**Issue by MateoPereyra88** [sisoputnfrba/foro#3189]
Estoy por la parte de en la que hay que configurar el servidor y el cliente. Se que para probar esto hay que correr los dos al mismo tiempo pero no se como.

Para ser precisos se me complica esta parte:
* Iniciar el servidor en la función iniciar_servidor() del utils del server.
* Esperar a que el cliente se conecte mediante la función esperar_cliente()
* Crear una conexión contra el servidor en la función crear_conexión() del utils del client.

Cuando intento correr el server.c por default me corre el client.c.

**Comment by Mimito164** [comment]
![image](https://github.com/sisoputnfrba/foro/assets/57462065/8841b311-87aa-4aea-b74d-ab1a203798f4)

![image](https://github.com/sisoputnfrba/foro/assets/57462065/3f15d3b9-f641-42e2-895f-cc424d193d04)

con esa flechita podes elegir cual de todas las consolas que tenes abiertas.

Si ya corriste ambos codigos y compilaron y no dieron errores probablemente lo tengas en ese menu desplegable.

Una cosa mas, si tenes muchas consolas abiertas podes eliminarlas con la :x: color gris.

**Comment by MateoPereyra88** [comment]
No me aparece el server. Cuando le doy para debuguear me corre solo cliente, sin importar si estoy en la ventana del codigo del cliente o el servidor.

**Comment by RaniAgus** [comment]
¡Buenas! Para mandar a ejecutar un módulo primero seleccionen el proyecto a ejecutar acá y luego dénle al ▶️:

![image](https://github.com/sisoputnfrba/foro/assets/39303639/4063fc2c-6cab-4efa-aa56-8aa7f0ad0ac9)

En este caso primero seleccionan Server, lo ejecutan y van a ver que se abre la consola. Luego lo mismo con el Client.

Si quieren debuggear, en el menú de al lado pueden seleccionar otro tipo de ejecución que no sea Run, y les va a reemplazar el ▶️ por el 🐛:
![image](https://github.com/sisoputnfrba/foro/assets/39303639/ac6d3f7e-a64f-4f26-8bc7-096fbd00d3d2)

Saludos

**Comment by RaniAgus** [comment]
Cierro el issue por inactividad, ante cualquier consulta pueden reabrirlo o abrir uno nuevo. Saludos
