### ISSUE TITLE
No me deja correr el kernel

### ISSUE THREAD

**Issue by MartoSimon** [sisoputnfrba/foro#3190]
Buen dia, quiero correr el kernel pero me tira error y me da el siguiente mensaje: /home/utnso/tp-2023-2c--Uwuntu-/kernel/Debug/kernel: error while loading shared libraries: libShared_Library.so: cannot open shared object file: No such file or directory
Shared_Library es un modulo que esta en la misma carpeta que el kernel y es donde guardamos las utils. 
A otro compañero teniendo la misma configuración le permite correr el kernel sin ningún problema.

**Comment by RaniAgus** [comment]
¡Buenas! ¿Tienen configurado `LD_LIBRARY_PATH` como se explica en el minuto 11:30 del video? https://youtu.be/A6dhc9cCI18?t=690&feature=shared

Saludos

**Comment by MartoSimon** [comment]
Hola, sisi. Segui todo el video y tengo todo igual a un compañero al cual le funciona perfectamente.

**Comment by Damuchi99** [comment]
Buenas, tengo el mismo problema, configuré el LD_LIBRARY_PATH como indica en el video y sigo teniendo el mismo error.

**Comment by Damuchi99** [comment]
Intente cambiar la variable agregándole comillas al **value**, ejecutarlo y después volver a sacarlas y ahí me funcionó

**Comment by RaniAgus** [comment]
@MartoSimon, ¿es posible que tengas configurado tu workspace en una ruta distinta que la del video? 

`${workspace_loc}` es una variable que se reemplaza por, valga la redundancia, la ubicación de tu espacio de trabajo. La forma de verificar cuál es es ir a File > Switch Workspace > Other y ver qué te aparece ahí, ej:
![image](https://github.com/sisoputnfrba/foro/assets/39303639/db1c2bf4-35a4-4701-9341-f2b227941387)

Si por algún motivo la ruta de tu workspace no coincide con la carpeta del repo donde se encuentra el proyecto y no tienen ganas de volver a configurar todo de nuevo, pueden simplemente agregar la ruta completa a mano:

![image](https://github.com/sisoputnfrba/foro/assets/39303639/ae52798f-28d9-45ac-818c-9879a5b358aa)

La desventaja que tiene esto es que si se clonan el repo en otra carpeta distinta no les va a funcionar la configuración. La mejor forma sería tener el workspace en la carpeta correcta y usar la variable que parte desde ahí.

**Comment by mesaglio** [comment]
Buenas, que estructura tiene su biblioteca compartida? Tienen todos los archivo `.c` y `.h` dentro del directorio `src`?

**Comment by GregorioOndjian** [comment]
Buenas, soy del mismo grupo que martin simon y me pasa exacatamente igual. Ya intente pegando la ruta exacta en vez del "workspace-loc" pero tampoco funciona.
Adjunto foto de la estructura de la Shared
![image](https://github.com/sisoputnfrba/foro/assets/82954160/9a930282-5357-4028-8933-d2e99ada432c)
Bueno y el error por si sirve de algo
![image](https://github.com/sisoputnfrba/foro/assets/82954160/56b0416c-b573-4515-9a12-76dc9dfecba9)

**Comment by MartoSimon** [comment]
En el soporte pudimos solucionarlo poniendo el path completo en la launch configuration. Dejo el issue abierto porque hay otras personas que no se si pudieron resolver el problema.
