### ISSUE TITLE
No encuentra el utils.h de las shared librarys

### ISSUE THREAD

**Issue by GregorioOndjian** [sisoputnfrba/foro#3191]
A la hora de intenter buildear el tp no me ve el archivo de utils.h que utilizamos con nuestro grupo para poner algunas funciones clave.

### 🔎 Búsqueda en foros

Ya realice el tutorial para instalar las shared librarys y esta todo en orden

### 📝 Pasos para reproducir el error

Intento buildear y no funciona

### 💻 Logs

```
In file included from ../src/memoria.c:11:
../src/memoria.h:19:10: fatal error: utils.h: No such file or directory
   19 | #include "utils.h"
      |          ^~~~~~~~~
compilation terminated.
make: *** [src/subdir.mk:20: src/memoria.o] Error 1
```

**Comment by irinaperezg** [comment]
Holis :) Una consulta, utils.h está en la carpeta src? Tal vez el problema está ahí. 
Si no es eso, te pido si nos podes mostrar la estructura de archivos para ver como están organizados.
Saludos

**Comment by MiltonMartorello** [comment]
Holis. Quería agregar que, una vez que declaras esas utils.h como shared libraries, 
ya no las referencias así **"utils.h"** sino así **<utils.h>** de la misma manera que otras bibliotecas externas.
Tal vez ayude. 
Saludos!

**Comment by GregorioOndjian** [comment]
Buenass, sisi, el utils.h esta e la carpeta src de la shared. Por el otro, ya probe de las 2 formas: <utils.h> y "utils.c". Probe de las 2 formas porq en otra compu me funciona bien con las comillas, pero en esta nada. 


![image](https://github.com/sisoputnfrba/foro/assets/82954160/43fd43ea-58e4-4155-9461-4ef25dbd3699)
Ak esta la imagen de la estructura de archivos. 
Muchas graciass.
Un saludo.

**Comment by irinaperezg** [comment]
Holis! Como el archivo utils.h no esta en la misma carpeta de kernel tendrías que poner el path, creo que poniendo #include <utils/utils.h> debería funcionar.

**Comment by GregorioOndjian** [comment]
Ahi probe de las 2 formas y tampoco :( nose q onda
![image](https://github.com/sisoputnfrba/foro/assets/82954160/bb2523ea-02ce-44ab-9b12-2b26cd49f861)
voy a volver a repasar el video de shared librarys a ver si me falto algo

**Comment by GregorioOndjian** [comment]
Ya lo pude solucionar, al parecer el path del compilador estaba mal puesto. Muchisimas gracias igualmente. Un saludo.

**Comment by GregorioOndjian** [comment]
Ya lo pude solucionar, al parecer el path del compilador estaba mal puesto. Muchisimas gracias igualmente. Un saludo.
