### ISSUE TITLE
Problema con los makefiles de cpu y filesystem

### ISSUE THREAD

**Issue by ParedesMicaela** [sisoputnfrba/foro#3192]
Decidimos pasarnos a vscode pero estamos teniendo problemas para hacer el makefile de la cpu y el filesystem. Creamos un workspace donde pusimos todas las carpetas, cada una con los archivos .vscode, obj, scr, cfg, scr, include y el makefile. A la hora de hacer make al kernel y a memoria, no tuve problemas pero cuando hice exactamente lo mismo con la cpu y el filesystem tuve el mismo error de que no encuentra el main y no se como resolverlo.

### 🔎 Búsqueda en foros
Use esta guia para poder pasarnos a vscode, la segui tal cual y me funciono para kernel y memoria.
https://github.com/dariokozicki/utnso-vscode

### 📝 Código relevante
Este es nuestro makefile, el cual lo hice siguiendo la guia que pase anteriormente.
```
PROCESS_NAME=fileSystem
IDIR =./include
SHARED_IDIR = ../shared/include
CC=gcc
CFLAGS=-I$(IDIR) -I$(SHARED_IDIR) -g -Wall

ODIR=./obj
SRCDIR =./src
LIBS=-lcommons -lpthread -lreadline -lcunit -lrt

SHARED_SRCDIR = ../shared/src
SHARED_ODIR = ../shared/obj

DEPS = $(wildcard $(IDIR)/*.h)

SRC = $(wildcard $(SRCDIR)/*.c)
OBJ = $(patsubst $(SRCDIR)/%.c,$(ODIR)/%.o,$(SRC))

$(ODIR)/%.o: $(SRCDIR)/%.c $(DEPS) $(SHARED_DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

$(SHARED_ODIR)/%.o: $(SHARED_SRCDIR)/%.c $(SHARED_DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

SHARED_DEPS = $(wildcard $(SHARED_IDIR)/*.h)

SHARED_SRC = $(wildcard $(SHARED_SRCDIR)/*.c)
SHARED_OBJ = $(patsubst $(SHARED_SRCDIR)/%.c,$(SHARED_ODIR)/%.o,$(SHARED_SRC))

$(PROCESS_NAME): $(OBJ) $(SHARED_OBJ)
	$(CC) -o $@ $^ $(CFLAGS) $(LIBS)

.PHONY: clean

clean:
	rm -f $(ODIR)/*.o *~ core $(INCDIR)/*~ $(PROCESS_NAME) $(SHARED_ODIR)/*.o
```

Y esto es lo que se encuentra en filesystem.c (donde esta el main):
```
#include "filesystem.h"

int main(void)
{
	 filesystem_logger = log_create("/home/utnso/tp-2023-1c-Desayuno_Pesado/filesystem/cfg/filesystem.log", "filesystem.log", 1, LOG_LEVEL_INFO);

	 cargar_configuracion("/home/utnso/tp-2023-1c-Desayuno_Pesado/filesystem/cfg/filesystem.config");

	 log_info(filesystem_logger, "Archivo de configuracion cargada \n");


    // COMUNICACIÓN MEMORIA //
	socket_memoria = crear_conexion(config_valores_filesystem.ip_memoria, config_valores_filesystem.puerto_memoria);

    int server_fd = iniciar_servidor(config_valores_filesystem.ip_filesystem,config_valores_filesystem.puerto_escucha);
    log_info(filesystem_logger, "Filesystem listo para recibir al modulo cliente \n");
    int cliente_fd = esperar_cliente(server_fd);
    log_info(filesystem_logger,"Se conecto un cliente \n");

    return EXIT_SUCCESS;
}
```

### 💻 Logs
Este es el error que obtengo cuando intento hacer el make:
```
gcc -o fileSystem ../shared/obj/logconfig.o ../shared/obj/operaciones.o ../shared/obj/socket.o -I./include -I../shared/include -g -Wall -lcommons -lpthread -lreadline -lcunit -lrt
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x1b): undefined reference to `main'
collect2: error: ld returned 1 exit status
make: *** [makefile:31: fileSystem] Error 1
```

**Comment by RaniAgus** [comment]
¡Buenas! Parece ser que no te está encontrando los archivos *.c que se encuentran en la subcarpeta `src` de esos dos módulos. ¿Podrías ejecutar el comando `tree .` desde la carpeta del repositorio así podemos ver cómo es la estructura de archivos, porfa? Saludos

**Comment by MartinSintas** [comment]
ahora que lo estoy revisando noté que no tenemos hechas las respectivas carpetas de obj
![tree parte uno](https://github.com/sisoputnfrba/foro/assets/129544689/c3714a83-b448-4960-aafb-441d9e505cc5)
![tree parte dos](https://github.com/sisoputnfrba/foro/assets/129544689/6a2a7c5f-5382-4cae-830e-6197b343511c)
![tree parte tres](https://github.com/sisoputnfrba/foro/assets/129544689/e150c251-5c7b-41a2-8dc7-20abd7aec0fa)

Desde ya, muchas gracias por la ayuda :D

**Comment by RaniAgus** [comment]
Un detalle más: veo que acá las carpetas se llaman `scr` en vez de `src`
![image](https://github.com/sisoputnfrba/foro/assets/39303639/99c3f549-b129-4b45-ae6d-0d641dd82271)

Una vez hechas las correcciones, siéntanse libres de cerrar el issue si no quedan más dudas :)

**Comment by ParedesMicaela** [comment]
Muchas gracias!! Ahí ya nos anda el proyecto c:
