### ISSUE TITLE
Pushear cosas en una branch

### ISSUE THREAD

**Issue by GregorioOndjian** [sisoputnfrba/foro#3193]
Buenass como va? Con mi grupo empezamos a utilizar branchs, estamos terminando de entender como funciona y hay cosas que no terminamos de entender. Si yo quiero pushear cambios en la branch que estoy trabajando, como hago? cuando lo intento hacer con un push normal me dice como que tengo que actualizar la main branch tambien (o eso es lo que entiendo) o me dice que esta todo actualizado y no es asi.
### 💻 Logs

![image](https://github.com/sisoputnfrba/foro/assets/82954160/9ee51a15-cf24-446d-9e68-7ef1397c0f35)
![image](https://github.com/sisoputnfrba/foro/assets/82954160/b90e4d5f-0d1b-4018-b6a3-8977a934485b)
Aca faltaria esos comentarios que estan en la branch del cpu.
Aguardo respuesta, un saludoo!

**Comment by RaniAgus** [comment]
¡Buenas! ¿Podrías hacer un `git status` para chequear en qué branch estás? Así evitamos pushear un commit a la branch incorrecta 😅 

Al ser git un sistema distribuido (o sea, puede funcionar en tu máquina sin necesidad de estar conectado a internet), no alcanza con crear un commit en tu branch local para que se suban los cambios, también hace falta hacer un `git push` que se encargue de sincronizar con la branch que se encuentra en el repositorio remoto.

Si creaste una branch en local con:
```
git checkout -b mi-nueva-branch
```
Para crearla en el repositorio remoto hace falta vincular esa branch local con una nueva remota:
```
git push --set-upstream origin mi-nueva-branch
```

También, en [docs](https://docs.utnso.com.ar/guias) les dejamos linkeado un tutorial interactivo de Git Branching que está buenísimo para entender mejor cómo funciona 👍🏻 

https://learngitbranching.js.org/?locale=es_AR

Saludos

**Comment by GregorioOndjian** [comment]
Okeyy, me tiraba eso sii me tiraba esto "git push --set-upstream origin mi-nueva-branch" pero tenia miedo de hacerlo y romper algo je, ahora hago un git status y lo mando pero creo que estoy en el lugar correcto. Voy a mirar ese tuto asi ya termino de entender todo.
![image](https://github.com/sisoputnfrba/foro/assets/82954160/0afaa580-22ec-4712-a8f4-729a8da9e31e)
Ahi estaria, creo que bien no?

**Comment by RaniAgus** [comment]
> Okeyy, me tiraba eso sii me tiraba esto "git push --set-upstream origin mi-nueva-branch" pero tenia miedo de hacerlo y romper algo je, ahora hago un git status y lo mando pero creo que estoy en el lugar correcto. Voy a mirar ese tuto asi ya termino de entender todo.

Jajajaj claro! Normalmente suele ocurrir que uno intenta pushear y aparece algo como:
```
fatal: The current branch cpu-branch has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin cpu-branch

To have this happen automatically for branches without a tracking
upstream, see 'push.autoSetupRemote' in 'git help config'.
```
Recomiendo leer los mensajes de error de git porque las sugerencias que aparecen suelen ser muy útiles, ya sea para entender lo que está pasando o incluso resolverlo :)

> Ahi estaria, creo que bien no?

Si la intención es subir el commit a la branch `cpu-branch`, ta bien 👍🏻

**Comment by GregorioOndjian** [comment]
Buenismoo, muchas graciass. Un saludo
