### ISSUE TITLE
Tamaño de bloque vs tamaño de pagina

### ISSUE THREAD

**Issue by GuidoMartinez** [sisoputnfrba/foro#3194]
Buenas! 

Tenemos una duda sobre el tamano de pagina vs el tamano de bloque. En el apartado de archivo de configuracion de FileSystem indica que van a coincidir, pero en los ejemplos de config los mismos difieren.

### 📔 Citas del enunciado:
Config memoria:
`TAM_PAGINA=16`

Config Filesystem:
`TAM_BLOQUE=1024`
```
*El tamaño de bloque será siempre configurado igual al tamaño de página del módulo Memoria.
```

Deberian ser el mismo o el tamano de pagina va a ser multiplo del tamano de bloque?

**Comment by tomasmartinez02** [comment]
Buenas, como va? Como dice en el enunciado, el tamaño del bloque y de pagina siempre van a coincidir, los ejemplos que están en el enunciado son para que ustedes vean como son con valores arbitrarios, pero cuando estén las pruebas van a coincidir y en caso que ustedes quieran testear deben ser del mismo tamaño también, no se preocupen por eso.
Saludos!

**Comment by GuidoMartinez** [comment]
Muchas gracias Tomas!
