### ISSUE TITLE
DETENER_PLANIFICACION - Duda sobre instruccion en EXEC en Kernel

### ISSUE THREAD

**Issue by GuidoMartinez** [sisoputnfrba/foro#3195]
Buenas!

Viendo como implementar el DETENER_PLANIFICACION nos surgio una duda sobre como manejar en kernel algunas instrucciones al desalojarlas del CPU:

En el caso de SLEEP, donde se debe bloquear el proceso por X tiempo. Al DETENER_PLANIFICACION se deberia guardar el proceso y su estado hasta que se inicie la planificacion nuevamente y a partir de ese instante comienza a contabilizar el tiempo de SLEEP? De esta manera entendemos que al rehabilitar la planificacion se terminaria de ejecutar el tratamiento correspondiente desde el exec del kernel.

La otra opcion que se nos ocurre es que se bloquea el proceso luego de tratar la syscall y recien ahi se detiene la planificacion? Al volver de CPU se inicia el SLEEP, se bloquea el proceso y no se busca un nuevo proceso a ejecutar. Este ultimo caso podria generar que ya pueda volver a READY cuando se inicie la planificacion nuevamente.

En el caso de las operaciones con FS / MEMORIA tenemos la misma duda, al volver de CPU se envia la peticion al modulo correspondiente y se bloquea o debe guardarse el pedido para ejecutarlo al momento de iniciar la planificacion nuevamente?

La duda principal seria que al INICIAR_PLANIFICACION no estariamos replanificando directamente sino que tendriamos que terminar de tratar las syscall y recien ahi replanificar.

### 📔 Citas del enunciado:
```
Funciones por consola

Detener planificación: Este mensaje se encargará de pausar la planificación de corto y largo plazo. El proceso que se encuentra en ejecución NO es desalojado, pero una vez que salga de EXEC se va a pausar su transición al siguiente estado.
Nomenclatura: DETENER_PLANIFICACION
```

**Comment by RaniAgus** [comment]
¡Buenas! Como la idea de `DETENER_PLANIFICACION` es detener las transiciones de estado de todos los procesos (y al igual que lo que debe suceder con un proceso que está en Exec y ejecutando en CPU), si justo un proceso estaba bloqueado por un SLEEP, por más que uno detenga la planificación el tiempo va a seguir transcurriendo. Si concluye el tiempo del SLEEP, va a permanecer bloqueado hasta que la planificación se vuelva a iniciar.

Saludos

**Comment by GuidoMartinez** [comment]
Gracias Agus, queda claro!

Una consulta adicional, para terminar de entender "las transiciones de estados". Por ejemplo en el caso de un F_TRUNCATE:

> F_TRUNCATE: Esta función solicitará al módulo File System que actualice el tamaño del archivo al nuevo tamaño pasado por parámetro y bloqueará al proceso hasta que el File System informe de la finalización de la operación.

a) Se envia al módulo FS el pedido y se frena la transición a bloqueado? Bloqueandose cuando vuelva a iniciarse la plani pero ya el FS consume retardo de la operación.

b) Al momento de volver el contexto de ejecución de CPU se debe detener el manejo de la syscall en Kernel y se retoma al planificar nuevamente (se detiene antes de enviar el pedido de F_TRUNCATE al FS y lo retoma al iniciar la plani nuevamente)

**Comment by RaniAgus** [comment]
Creo que en general lo mejor va a ser la b), que el proceso se mantenga en Exec y hasta no reanudar la planificación no se maneje ningún motivo de desalojo.

**Comment by GuidoMartinez** [comment]
Buenísimo Agus, lo manejamos de esa manera.
Muchas gracias!
