### ISSUE TITLE
Problema con las librerías (o bibliotecas) compartidas

### ISSUE THREAD

**Issue by MartinSintas** [sisoputnfrba/foro#3196]
Hola buenas!!, estoy teniendo un inconveniente (y algunos compañeros de mi grupo también) con unas librerías compartidas de nuestro tp ya que Vs Code no las toma (ME TIRA ERROR 😢  )

Desde ya muchas gracias por la ayuda y por tomarse el tiempo para responder :D

### 📝 Código relevante

![Captura de pantalla 2023-09-09 154250](https://github.com/sisoputnfrba/foro/assets/129544689/70f06249-ae35-4e6b-8f71-76de2c52691f)
![Captura de pantalla 2023-09-09 154415](https://github.com/sisoputnfrba/foro/assets/129544689/7bb2ea32-b06f-4654-a7db-f10cb0393c48)

**Comment by RaniAgus** [comment]
¡Buenas! Me es muy difícil entender cuál sería el error con solo esa info... tengo un par de preguntas para que nos ayuden a ayudarles: 

1. ¿Cuál es el mensaje de error? (si puede ser en texto sería ideal así aparece en el buscador de issues cuando otro alumno lo busque)
2. ¿Es un error del VSCode o es un error del compilador?
3. ¿Cuál es la estructura de carpetas completa? (de todo el repo, que se vea tanto la shared como el módulo al que la quieren incluir)

Saludos

**Comment by MartinSintas** [comment]
Buenas, disculpas por no ser suficientemente claro
1) Al momento de ejecutar en la terminal (del VsCode) el make me da el siguiente error:

utnso@utnso :  ~/Desktop/tp-2023-2c-KernelTitans/kernel$ make
gcc -c -o obj/kernel.o src/kernel.c -I./include -I../share/include -g -Wall
In file included from src/kernel.c:1:
./include/kernel.h:12:10: fatal error: shared/socket.h: No such file or directory
   12  |  #include <shared/socket.h>
         |
compilation terminated.
make: *** [makefile:20: obj/kernel.o] Error 1

2) Es un error con el VsCode 😿 

3) 
![Captura de pantalla 2023-09-10 190706](https://github.com/sisoputnfrba/foro/assets/129544689/2a80220c-fe8b-49ec-86d5-1e7ae936182a)
![Captura de pantalla 2023-09-10 190725](https://github.com/sisoputnfrba/foro/assets/129544689/e6f2fd90-94af-4790-b382-312b5cec1632)
![Captura de pantalla 2023-09-10 190916](https://github.com/sisoputnfrba/foro/assets/129544689/ae482fc9-2090-4c51-8ebb-60b1557c100d)
![Captura de pantalla 2023-09-10 190924](https://github.com/sisoputnfrba/foro/assets/129544689/6463a897-49e4-44f9-966d-7ed998c96311)

**Comment by MartinSintas** [comment]
Buenas! no sé porque se subió recién el comentario de arriba (era de hace una hora y pico aprox) pero ya pude solucionarlo, gracias por la ayuda igualmente :D
