### ISSUE TITLE
Duda sobre funcion por consola INICIAR_PROCESO

### ISSUE THREAD

**Issue by itulau** [sisoputnfrba/foro#3197]
Hola buenas, queria consultar algunas dudas puntuales sobre algunos parametros:

El parametro PATH, que por el nombre deduzco que es una ruta a un archivo, mi duda es: la ruta puede contener espacios? ej: /home/user/Nombre Con Espacios/archivo

El parametro SIZE, que representaria? es un entero?

**Comment by RaniAgus** [comment]
¡Buenas!

> El parametro PATH, que por el nombre deduzco que es una ruta a un archivo, mi duda es: la ruta puede contener espacios? ej: /home/user/Nombre Con Espacios/archivo

No se preocupen, no vamos a ser tan malos 😅 

En general contar con rutas con espacios es un problema para cualquier parser de parámetros por consola, ya que justamente cada parámetro también está separado con espacios.

> El parametro SIZE, que representaria? es un entero?

Es el tamaño que debe ocupar el proceso en Swap, se va a utilizar al momento de crearlo cuando encaren la parte de Memoria y FS.

Saludos

**Comment by ParedesMicaela** [comment]
Buenas! Tengo una pregunta del mismo tema. El PATH seria un path que le pasamos por consola interactiva al kernel y el kernel se lo va a tener que pasar a memoria para que pueda leer y mandar las instrucciones una por una a la cpu?

**Comment by itulau** [comment]
Dale, gracias.
