### ISSUE TITLE
Duda sobre como implementar FAT y archivo de bloques

### ISSUE THREAD

**Issue by lucasosacuenca** [sisoputnfrba/foro#3198]
Buenas, estaba viendo como crear la FAT y el archivo de bloques, note que se pedia que ambos sean archivos binarios, y especificamente el archivo de bloques se pedia que no pueda ser leido desde un editor de texto normal, queria preguntar, esto como se logra? simplemente cambiando la extension? o con alguna implementacion en especifico? tenia pensado usar mmap tanto para la FAT y el archivo de bloques, eso tambien es lo mas combeniente o se recomienda alguna otra implementacion? Gracias.

**Comment by LeandroCarbajales** [comment]
Buenas!
En Linux todos los archivos son binarios, la diferencia radica en cómo guardan los datos.
La aclaración se hace ya que lo que se busca guardar son bytes y no cadenas de caracteres, por ejemplo para la tabla FAT que guarda números, tanto 10 como 999999 los representamos con 4 bytes (uint32_t) y no como cadenas de caracteres "10" (2 caracteres/2 bytes) o "999999" (6 caracteres/6 bytes). Un editor de texto solamente lee cadenas de caracteres, por lo que normalmente no podría leer apropiadamente el archivo de la FAT.
Queda más clara la idea?

**Comment by lucasosacuenca** [comment]
sisi ahi va, muchas gracias
