### ISSUE TITLE
Duda con PCB (registros CPU)

### ISSUE THREAD

**Issue by MartinSintas** [sisoputnfrba/foro#3199]
Buenas! con nuestro grupo nos surgió una duda sobre el PCB (registros de CPU)

### 📔 Citas del enunciado/videos
![image](https://github.com/sisoputnfrba/foro/assets/129544689/6e633456-796d-457e-8d6e-5c202a6071d6)

### 💭 Soluciones posibles
Estamos dudando de si los registros de CPU deben ser estructuras o listas?

Desde ya muchas gracias! 😄

**Comment by RaniAgus** [comment]
¡Buenas! Como verán en la parte de CPU del enunciado (p. 18), existen 4 registros:

> La CPU contará con una serie de registros de propósito general, los cuales tendrán los siguientes nombres: AX, BX, CX, DX.

Por lo que alcanza con que sea una estructura.

Saludos

**Comment by MartinSintas** [comment]
Buenísimo, mil gracias!
