### ISSUE TITLE
Nombre de instruccion ADD o SUM

### ISSUE THREAD

**Issue by GonzaloRDuart** [sisoputnfrba/foro#3200]
Buenas! Tenemos una duda sobre el enunciado. Cuando se muestra como ejemplo las isntrucciones en pseudocódigo se utiliza la instrucción **ADD** pero en la explicación del execute habla de la instruccion **SUM**. Teníamos la duda de cual de las dos deberíamos utilizar a la hora de leer las instrucciones. Esta diferencia se encuentra en la página 19 del enunciado. Saludos!

**Comment by LeandroCarbajales** [comment]
Buenas!
La instrucción es SUM, el ejemplo había quedado desactualizado, ahí lo actualizamos, gracias por avisar! :)

**Comment by GonzaloRDuart** [comment]
Gracias a vos!
