### ISSUE TITLE
Duda sobre ejecución de consola interactiva

### ISSUE THREAD

**Issue by tomaslcarballo** [sisoputnfrba/foro#3201]
Hola, como están?

Quería consultar si para la parte de la consola interactiva es un requerimiento obligatorio tener que escribir la opción deseada por teclado completa, por ejemplo <INICIAR_PROCESO "home....." 2 3> o si se puede ir desmenuzando la opción como por ejemplo si escribí INICIAR_PROCESO que luego me pida los parámetros.
Al tener tan libre albedrio estoy un poco perdido, en caso de tener que ingresar una instrucción completa con los parámetros en una sola linea, lo más optimo sería ingresar un string con readline y analizarlo con alguna función de las commons o utilizar [argumentos para el main](https://docs.utnso.com.ar/guias/programacion/main) en otro proceso aparte?

Muchas gracias.

Saludos!

**Comment by mesaglio** [comment]
Buenas, como va?
Pensa q la consola la van a manejar ustedes, por lo que la respuesta seria lo que ustedes creen que les va a ser los mas comodo el dia de la entrega.

Con respecto a si usar readline o los argumentos de ejecucion, pensa que vas a tirar distintos comandos en una misma prueba. Por ejemplo iniciar_proceso, detener_planificacion, modificar_multiprogramacion, etc.

Saludos, Juani

**Comment by tomaslcarballo** [comment]
Muchas gracias, ahí está un poco más claro.
Saludos!
