### ISSUE TITLE
👩‍💻 Cambios de grupo 2c2023 👨‍💻

### ISSUE THREAD

**Issue by LeandroCarbajales** [sisoputnfrba/foro#3202]
¡Buenas!

Habiendo cerrado las inscripciones, damos inicio a los cambios de grupo.
La idea de este thread es unificar la búsqueda de integrantes para completar su grupo, o búsqueda de grupo en caso de haberse quedado solos. Tengan en cuenta que los cambios están limitados a uno por persona, por lo que no son para probar suerte.

Por favor, traten de NO publicar números de celular ya que el foro es público y cualquier persona incluso fuera de la UTN puede llegar a ver su número.

Como siempre, cualquier inconveniente con los cambios de grupos envíen un mail a [inscripciones@utnso.com.ar](mailto:inscripciones@utnso.com.ar)

Saludos!

**Comment by Matitisco** [comment]
Hola! Estamos buscando un 5to integrante, si estas sin grupo podes avisarme a mi mail, matiscornia@frba.utn.edu.ar :)

**Comment by aguspenia** [comment]
Buenas tardes! como están? al arrancar el cuatrimestre se nos bajo un integrante el día después de cerrar grupos. Venimos metiéndole a la materia y nos falta un integrante mas. cualquier duda o alguien que este interesado en unirse.... le dejo nuestros mails.
agpena@frba.utn.edu.ar
ftortolano@frba.utn.edu.ar

**Comment by jqnsantosr** [comment]
Buenas!
Estamos en busca de un integrante, dado que se nos dio de baja uno de los 5.
Les dejo un mail:
jsantosrodriguez@frba.utn.edu.ar

**Comment by liliperalta** [comment]
Buenas!!
Nos estaría faltando un integrante para completar el grupo, dejo el mail de contacto: liliperaltacollante@frba.utn.edu.ar
Saludos!!

**Comment by JulianFernandezMakusas** [comment]
Buenas
Nos estaria faltando 3 integrantes para completar el grupo. Tenemos hasta el checkpoint 3 realizado del tp, les dejo mail de contacto: jfernandezmakusas@frba.utn.edu.ar

**Comment by AgustinTejera** [comment]
Buenas, estamos buscando un integrante mas para meterle al TP en lo ultimo que queda de la cursada. Si alguien esta interesado, les dejo mi correo: atejera@frba.utn.edu.ar

**Comment by Facundo-Su** [comment]
Buenas
estamos buscando un integramnte mas , porque se nos bajo uno , por si alguno le falta equipo, estamos por terminar la tercera entrega. les dejo mi correo: fsu@frba.utn.edu.ar

**Comment by iago64** [comment]
Se cierran los cambios de grupo por este cuatrimestre, lo único que vamos a procesar a partir de este momento son bajas.
