### ISSUE TITLE
Problemas con configurar la VM 2023

### ISSUE THREAD

**Issue by ezemartlopez** [sisoputnfrba/foro#3203]
Hola, nesecito ayuda para configurar la pantalla de la máquina virtual que sea auto adaptable a la vista.
### 🔎 Búsqueda en foros

Use los videos de la catedra para instalar las guest aditions, pero como estaban en otro sistema operativo (no el actual) puede ser que le haya errado en algo. Pero aun asi busque en youtube, internet como configurar la VM y nada. 

### 📦 Especificaciones de la VM
- Versión de VirtualBox: 7.0.10
- Memoria RAM asignada: 2GB

### 🖥️ Especificaciones del host
- Sistema Operativo y versión: Windows 10
- Memoria RAM: 8GB
- Procesador: I5

**Comment by RaniAgus** [comment]
¡Buenas! Los videos están linkeados en la guía para [Conseguir un entorno Linux](https://docs.utnso.com.ar/primeros-pasos/entorno-linux) junto con las aclaraciones correspondientes.

También en la sección de [Consultas](https://docs.utnso.com.ar/consultas) y el [README de este repositorio](https://github.com/sisoputnfrba/foro) se encuentran tips y consejos sobre cómo usar el foro :)

Saludos

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, ante cualquier consulta pueden reabrirlo o abrir uno nuevo. Saludos
