### ISSUE TITLE
Un modulo me tira un error que no esta en ningun lado

### ISSUE THREAD

**Issue by GregorioOndjian** [sisoputnfrba/foro#3204]
Buenas como va, por un problema tuve que reinstalar la maquina virtual. Instale y seguí los pasos de el tutorial de las Shared Librarys pero a la hora de ejecutar el modulo de cpu, que es en donde aplique los cambios, me tira un error que no figura en ningun archivo del modulo en cuestion. 

### 📝 Pasos para reproducir el error

Lo que hago es poner para ejecutar el modulo y me tira un warning de que hay un error
### 💻 Logs

![image](https://github.com/sisoputnfrba/foro/assets/82954160/a2884c5b-7de4-445f-aa4a-050cb35c0687)
En ningun lado me dice que realmente hay un error
![image](https://github.com/sisoputnfrba/foro/assets/82954160/88bb0af7-6542-4a25-b614-2c03dd8b8aeb)

Desde ya muchas gracias. Un saludo.

**Comment by iago64** [comment]
Buenas! Cómo va?

En principio me esta faltando algo de info para poder ayudarte (puntualmente el error o el warning que decir que te devuelve), pero te tiro un par de preguntas a ver si te puedo orientar hacia una respuesta:

1.- Dentro de la carpeta Debug de cpu, tenes un ejecutable?
2.- En la carpeta de la shared, tenes creado el archivo .so que tiene la shared compilada?

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Para sumar, veo que en Eclipse tienen importada la carpeta del repo (tp-2023-2c-...) cuando en realidad deberían tener un proyecto por cada módulo (cpu, filesystem, kernel, shared, etc).

Prueben volviendo a importar el proyecto con solamente los módulos, similar a lo que habrán hecho en el TP0:

![lo que hicieron el TP0](https://docs.utnso.com.ar/img/primeros-pasos/tp0/workspace-04.png)

Saludos

**Comment by GregorioOndjian** [comment]
Buenass, al final era un error en el path de los includes, ya lo pude solucionarr, muchas gracias igualll
