### ISSUE TITLE
Consulta sobre grado de multiprogramación

### ISSUE THREAD

**Issue by Bru-Nicolas-FRBA** [sisoputnfrba/foro#3205]
Buenas tardes, una consulta. En el TP se nos habla del grado de multiprogramación inicial, pero nunca de uno mínimo o máximo. ¿Cómo debemos interpretar al grado de multiprogramación mínimo?

**Comment by iago64** [comment]
Buenas! Cómo va?

El grado inicial es con el que van a arrancar la ejecución o dicho de otra forma el que va a estar en el archivo de config, recuerden que es un valor que se puede cambiar en tiempo de ejecución.

Saludos.-

**Comment by Bru-Nicolas-FRBA** [comment]
> Buenas! Cómo va?
> 
> El grado inicial es con el que van a arrancar la ejecución o dicho de otra forma el que va a estar en el archivo de config, recuerden que es un valor que se puede cambiar en tiempo de ejecución.
> 
> Saludos.-

Buenas!

Claro, lo de que es el inicial y puede variar eso ya lo teníamos entendido.

Pero me refería al grado máximo de multiprogramacion, al cual se hace referencia pero no se establece en el tp.

Que debemos hacer respecto al "grado máximo" de multiprogramacion


![IMG_20230914_102301.jpg](https://github.com/sisoputnfrba/foro/assets/82009198/0edc3ec9-8fd9-4bdc-9ac7-9ab9a1432446)

**Comment by iago64** [comment]
Buenas!

_Siempre el grado de multiprogramación es el máximo_, solo que como el mismo puede ir variando a lo largo de la ejecución, cuando hablamos de _grado de multiprogramación inicial_ es el que está en el archivo de config.

Saludos.-

**Comment by mesaglio** [comment]
Quedo resuelto el issue @Bru-Nicolas-FRBA ?

**Comment by Bru-Nicolas-FRBA** [comment]
Si, muchas gracias. Disculpas por no cerrarlo, soy nuevo en los issues jajajaj
