### ISSUE TITLE
Como mostrar las direcciones de memoria en los logs

### ISSUE THREAD

**Issue by LucianoFoglia** [sisoputnfrba/foro#3206]
Buenas, teniamos una consulta con los logs en los que hay que mostrar la direccion fisica. Deberiamos mostrar la direccion del modulo memoria en hexadecimal y que esa sea la misma que la de que muestra el log de cpu? 
Por otro lado, Al querer mostrar la direccion con un entero, hay casos en los que nos devuelve un numero negativo. Siendo que es un uin32_t.
En el caso en el que haya que mostrarla como string, podemos asegurar que siempre van a ser de 12 digitos las direcciones?

### 📝 Código relevante
En el momento en el que ejecutamos esto, pagina->direccionInicio apunta al mismo lugar que memoriaPrincipal. 
```
...
        void* dirFisicaALeer = pagina->direccionInicio + desplazamiento;

	char* dirFisicaChar = malloc(12);

	sprintf(dirFisicaChar, "%lx", dirFisicaALeer);

	log_info(logger_memoria, "Direcci memPrinc: %p", memoriaPrincipal);
	log_info(logger_memoria, "Direccion inicio: %p", pagina->direccionInicio);
	log_info(logger_memoria, "Direcci en void*: %d", dirFisicaALeer);
	log_info(logger_memoria, "Direccion  char:   %s", dirFisicaChar);
...
```

### 🐛 Cómo reproducir el error

Terminal de memoria
```
[INFO] 15:56:19:525 MEMORIA/(18115:18115): Esperando Cpu....
[0m[INFO] 15:56:25:506 MEMORIA/(18115:18115): Se conecto Cpu
[0m[INFO] 15:56:25:514 MEMORIA/(18115:18115): Direcci memPrinc: 0x562187f11890
[0m[INFO] 15:56:25:514 MEMORIA/(18115:18115): Direccion inicio: 0x562187f11890
[0m[INFO] 15:56:25:514 MEMORIA/(18115:18115): Direcci en void*: -2014242672
[0m[INFO] 15:56:25:514 MEMORIA/(18115:18115): Direccio en char: 562187f11890
[0m[INFO] 15:56:25:514 MEMORIA/(18115:18115): Valor leido: 25
```
Terminal de cpu
```
[INFO] 15:56:25:506 CPU/(18203:18203): Se conecto al servidor 127.0.0.1:8002
[0m[33m[WARNING] 15:56:25:514 CPU/(18203:18203): Tam de pag recibido: 16
[0m[INFO] 15:56:25:515 CPU/(18203:18203): Pid: 3 - Accion: Leer - Direccion Fisica: -2014242672 - Valor: 25
```

**Comment by RaniAgus** [comment]
¡Buenas!
1) Cuando pedimos en el enunciado la dirección física, es solamente la variable que ustedes llaman `desplazamiento` (o sea, el desplazamiento dentro del `malloc(TAM_MEMORIA)` que hicieron al principio). Piensen que sino sería imposible para nosotros evaluarlo 😅 
2) Este log les está devolviendo un número negativo porque están leyendo un `void*` como `int`, el cual acepta números negativos:
```c
void* dirFisicaALeer = pagina->direccionInicio + desplazamiento;

log_info(logger_memoria, "Direcci en void*: %d", dirFisicaALeer);
```
3) Les recomendamos encarecidamente que no usen funciones inseguras como `sprintf`, `strcat`, etc. y en su lugar usen las funciones de string de las commons: [so-commons-library/src/commons/string.h](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/string.h), las cuales ya resuelven el problema de reservar memoria y utilizarla para armar el string:

```c
char *dirFisicaChar = string_from_format("%lx", dirFisicaALeer);
```

De todas formas en ese caso no necesitan usar `string_from_format` porque `log_info` ya les permite formatear cualquier parámetro que le pasen 😉 

Saludos

**Comment by smarquesgomez** [comment]
Genial, ahí pudimos! Muchas gracias!
