### ISSUE TITLE
Duda sobre consola interactiva y INICIAR_PLANIFICACION y DETENER_PLANIFICACION

### ISSUE THREAD

**Issue by itulau** [sisoputnfrba/foro#3207]
Buenas, mi duda gira en torno si deberiamos diseñar la implementacion de estos comando asumiendo que puedan ejecutarse varias veces de forma consecutiva, ej:
>INICIAR_PLANIFICACION
>INICIAR_PLANIFICACION
...
>DETENER_PLANIFICACION
>DETENER_PLANIFICACION

¿Podria darse esta situacion? O podemos asumir que **siempre** que se inicia la planificacion, se debe detenerla antes de volver a iniciarla nuevamente.

**Comment by iago64** [comment]
Buenas! Cómo va?

Pregunta simple, respuesta simple: **No vamos a probar eso**

Explicación: A fines prácticos el poder iniciar / detener la planificación es para que sean más fáciles las pruebas y no estén tirando los comandos de INICIAR_PROCESO como locos con el riesgo de equivocarse en alguno, entonces, tuvimos que recurrir a esta solución no muy catedrática para poder facilitar las pruebas y evitar un par de colapsos mentales a la hora de las pruebas.

Saludos.-

**Comment by itulau** [comment]
Entiendo, gracias. :+1:
