### ISSUE TITLE
Duda sobre consola interactiva y finalizacion de la misma para detener Kernel

### ISSUE THREAD

**Issue by itulau** [sisoputnfrba/foro#3208]
Buenas, queria consultar como se esperaria que deba terminar la ejecucion de la consola, ya que entre los comandos esperados no vi ninguno que finalice la ejecucion del kernel. ¿Esto quiere decir que quedaria a nuestro criterio, si por ejemplo decidimos agregar un comando SALIR o algo similar?

**Comment by mesaglio** [comment]
Buenas!
Hay modulos que nunca van a finalizar siempre van a quedar a la espera de nuevos msj.

Salu2, Juani

**Comment by itulau** [comment]
Hola Juani, me queda claro que entonces no deberiamos modelar una salida para el TP, pero en caso de que nosotros quisieramos agregarlo no habria problema? Mas que nada para evitar un cierre forzoso y leakear memoria.

**Comment by mesaglio** [comment]
Si el programa se finaliza el so termina liberando toda la memoria, no hay leaks. No se preocupen por esto.

**Comment by RaniAgus** [comment]
¡Buenas @itulau! ¿Quedó todo claro con la respuesta de Juani? Saludos

**Comment by itulau** [comment]
Si, gracias
