### ISSUE TITLE
Consulta sobre la creacion de proceso

### ISSUE THREAD

**Issue by LautaroRobles** [sisoputnfrba/foro#3209]
En el enunciado dice lo siguiente

> Ante la solicitud de la consola de crear un nuevo proceso el Kernel deberá informarle a la memoria que debe crear un proceso con el nombre del archivo de pseudocódigo junto con el tamaño en bytes que ocupará el mismo.

La memoria deberia recibir solamente el "nombre del archivo de pseudocódigo" y el "tamaño en bytes". Podemos hacer que reciba otros parametros, como el PID?

Porque nos interesa saber quien deberia ser el encargado de crear el PID para un proceso, ¿la memoria o el kernel?

**Comment by mesaglio** [comment]
Como poder pueden, pero hace sentido?
El modulo que se encarga de orquestar los proceso es el kernel, por lo que tiene todo el sentido que la administración de los pid sea su responsabilidad.

Saludos, Juani

**Comment by LautaroRobles** [comment]
Gracias!
