### ISSUE TITLE
Cspec ( Prueba de modulos 

### ISSUE THREAD

**Issue by brian-colman** [sisoputnfrba/foro#3210]
# Cspec

Buenas, como estan? Tengo unas consultas sobre Cspec

## Prueba de modulos 

Para probar los modulos  (FS,Memoria,CPU,consola,kernel ) , hay alguna forma de que Cspect levante los modulos y haga las conexiones para ver si todo se mantiene acorde? o deberia hacer un bash para probar ? o levantarlo siempre a mano ? , Esto es mas que nada para saber si no se rompe la comunicacion basica entre los modulos a la hora de mergear ramas ( Luego talves se agreguen mas pruebas de los modulos ) 

## Extra 

Hay algun lugar mas alla de la  [documentacion oficial](https://github.com/mumuki/cspec) , para obtener mas ejemplos/informacion o con esos ya alcanzaria para realizar la mayoria de los test para el tp? 

Desde ya muchas gracias 
Saludos

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va?
CSpec es un framework de testing **unitario**. En otras materias de la carrera como [Paradigmas de Programación](https://docs.google.com/document/d/1Q_v48gZfRmVfLMvC0PBpmtZyMoALbh11AwmEllP__eY/edit) y [Diseño de Sistemas](https://dds-jv.github.io/apuntes/validacion/) aprenderán que este tipo de testeo involucra probar pequeños partes de funcionalidad individualmente y no su conexión entre ellas (lo cual se va más para el lado de los tests de **integración**).

Un buen ejemplo de pruebas unitarias son los tests de las commons: cada suite de tests está enfocada únicamente en probar un TAD en particular. Si quieren pueden chusmear la [guía de CSpec](https://docs.utnso.com.ar/guias/herramientas/cspec) para luego armar tests unitarios con los TADs que vayan armando en cada módulo, pero no creo que les sirva de mucho utilizarlo para automatizar pruebas de integración.

Para asegurarse que funcione la comunicación básica entre los módulos es importante la comunicación y la coordinación entre integrantes del equipo: creo que estaría mejor que cuando trabajen sobre eso lo hagan todos sobre la misma rama ya que es la parte más crítica del sistema. Ejecuten los módulos y utilicen el [debugger](https://docs.utnso.com.ar/guias/herramientas/debugger) del IDE para corregir posibles errores en la integración.

Luego, me parece bien si quieren dividirse en subgrupos el trabajo de cada módulo. Si se dan cuenta que es necesario hacer algún cambio en la interacción con los demás, asegúrense de coordinarlos entre todos.

Saludos
