### ISSUE TITLE
Espacio extra en "Ejemplo de Archivo de Configuración" del enunciado

### ISSUE THREAD

**Issue by LautaroRobles** [sisoputnfrba/foro#3211]
El "Ejemplo de Archivo de Configuración" del Kernel tiene un espacio de mas en la linea RECURSO

```
IP_MEMORIA=127.0.0.1
PUERTO_MEMORIA=8002
IP_FILESYSTEM=127.0.0.1
PUERTO_FILESYSTEM=8003
IP_CPU=127.0.0.1
PUERTO_CPU_DISPATCH=8006
PUERTO_CPU_INTERRUPT=8007
ALGORITMO_PLANIFICACION=PRIORIDADES
QUANTUM=2000
RECURSOS=[RA,RB,RC] <--- espacio extra
INSTANCIAS_RECURSOS=[1,2,1]
GRADO_MULTIPROGRAMACION_INI=10
```

Si lo copias asi como esta en el enunciado y obtenes los valores usando `config_get_array_value` de las commons, el ultimo recurso tendrá el corchete de cierre "]":

```
char** keys = config_get_array_value(config, "RECURSOS");
int length = 0;
while(keys[length] != NULL) {
    char* str = keys[length];
    printf("%s\n", keys[length]);
    length++;
}
```
```
RA
RB
RC]
```

**Comment by RaniAgus** [comment]
Ya fue corregido, ¡gracias!
De todas formas, quédense tranquilos que todas las configuraciones que les demos en las pruebas van a estar bien escritas (y sino, avísennos así las corregimos 😉).

Saludos
