### ISSUE TITLE
Duda con fase de Fetch y Decode

### ISSUE THREAD

**Issue by GregorioOndjian** [sisoputnfrba/foro#3212]
Buenas como va, tengo una duda con el tema de las fases fetch y decode del modulo de CPU.
A la hora de realizar el fetch le pido a memoria la instruccion con el contenido del Program Counter, eso que me devuelve, es la direccion logica de la instruccion no? A esa direccion logica la tengo que transformar en direccion fisica para luego poder hacer el decode?
No me queda del todo claro, en que momento tengo que tranformar la direccion logica en fisica.

### 📔 Citas del enunciado/videos

![image](https://github.com/sisoputnfrba/foro/assets/82954160/74b5fcea-4533-487b-b7b7-4dbb73f113fb)
![image](https://github.com/sisoputnfrba/foro/assets/82954160/9d7074e0-3681-4b44-a0d5-5673e70d6c72)
Desde ya muchas graciass. Un saludo.

**Comment by LeandroCarbajales** [comment]
Buenas!

> A la hora de realizar el fetch le pido a memoria la instruccion con el contenido del Program Counter, eso que me devuelve, es la direccion logica de la instruccion no?

No, la idea es que te devuelva la instrucción directamente. En el mundo real es posible que se necesite traducir direcciones para la etapa de fetch, ese aspecto en este TP está simplificado a efectos de que puedan implementarlo según el orden en que se aprenden los temas en clase, ya que aun no vieron traducción de direcciones.

> A esa direccion logica la tengo que transformar en direccion fisica para luego poder hacer el decode?
No me queda del todo claro, en que momento tengo que tranformar la direccion logica en fisica.

La idea de la etapa de decode es discernir qué instrucción nos llegó e interpretar si esa instrucción requiere o no que se traduzca una dirección lógica a física, ya que una instrucción que requiera de ello no podrá ser ejecutada hasta que no se traduzcan las direcciones lógicas que vienen por parámetro.
Misma idea que antes, muchas instrucciones (especialmente las que pedimos para los checkpoint 2 y 3) no requieren traducción de direcciones ya que es algo que aun no vieron en clase.

Te aclara las dudas?
Saludos!
      Lean

**Comment by GregorioOndjian** [comment]
Okeyy, buenismo, entonces por ahora una vez que tengo la instruccion paso directo a la fase decode y luego execute? Por otro lado, no entiendo bien en que casos si necestaria hacer la traduccion de memoria logica a fisica.
Igualmente se me aclararon muchas cosas asi que graciass. Un saludo

**Comment by LeandroCarbajales** [comment]
Por ejemplo la instrucción MOV_IN:

`MOV_IN (Registro, Dirección Lógica): Lee el valor de memoria correspondiente a la Dirección Lógica y lo almacena en el Registro.`
Esa dirección lógica que viene como parámetro de la instrucción debería ser traducida a dirección física para saber en qué lugar de memoria buscar el valor que guardaremos en el registro.

**Comment by LeandroCarbajales** [comment]
@GregorioOndjian Quedó alguna duda con esto?
Se puede cerrar el issue?

**Comment by GregorioOndjian** [comment]
Nono, clarisimo, muchas graciass.
