### ISSUE TITLE
Duda Memoria (Paginación bajo demanda y logs)

### ISSUE THREAD

**Issue by smarquesgomez** [sisoputnfrba/foro#3214]
Buenas, tenemos tres dudas con memoria.

1. Con respecto a la paginación bajo demanda, al momento de crear una proceso el cual tiene cierta cantidad de páginas, en que momento se cargan en memoria las mismas? No terminamos de entender si es al momento de la creación del proceso, o al momento de leer o escribir alguna. 

2. Cuando finaliza un proceso, se eliminan sus paginas de la tabla global o solo se cambia el bit de presencia?

3. En los logs mínimos y obligatorios de memoria aparece PID_PAG y no sabemos en que momento se utiliza. Dejo la parte de la consigna abajo.

Muchas gracias!

### 📔 Citas del enunciado/videos

Es importante tener en cuenta que al tener reemplazo global los procesos se pueden robar páginas, por eso en los logs cuando ponemos el PID es el PID del proceso que inició la solicitud, mientras que PID_PAG es el PID del proceso dueño de la página que se está modificando.

**Comment by iago64** [comment]
Buenas! Cómo va?

Es normal que a esta altura del cuatrimestre tengan dudas sobre memoria porque son temas que se ven despues del primer parcial 😄 

Dicho lo anterior paso a contestar las dudas:

1.- La paginación bajo demanda lo que hace es que la página se carga en memoria al momento de usarla, eso quiere decir que, solo van a traer una página de swap en el momento en el que hagan una operación sobre esa página (por ej MOV_IN, MOV_OUT, F_READ o F_WRITE)

2.- Al finalizar el proceso, los frames que tengan en memoria tienen que dejarlos como libres para que los pueda tomar cualquier otro proceso sin tener que ejecutar un algoritmo de reemplazo.

3.- Pequeño detalle de redacción, lo vamos a estar corrigiendo en una futura errata, queríamos decir que en el log de Reemplazo de página, cuando les decimos Page Out, tienen que poner el PID correspondiente al proceso que era "dueño" del frame antes del reemplazo.

Saludos.-

**Comment by smarquesgomez** [comment]
Muchas Gracias!! Se entendió perfecto!
