### ISSUE TITLE
Estrategia multihilos del kernel

### ISSUE THREAD

**Issue by jraijman** [sisoputnfrba/foro#3215]
No termino de entender como seria la implementación de los hilos para el kernel, entiendo que es el encargado de iniciar las consultas a los otros módulos, pero no me queda claro en que momentos se harían "varias consultas en paralelo" en las que necesite hilos

El issue está relacionado con el #3188.

### 📔 Citas del enunciado/videos
>Además de las operaciones de la consola interactiva, el Kernel será el encargado de gestionar las peticiones contra la Memoria y el File System, por lo que deberá implementarse siguiendo una estrategia multihilo que permita la concurrencia de varias solicitudes provenientes de diferentes orígenes.

Muchas gracias.

**Comment by RaniAgus** [comment]
¡Buenas! Uno de esos momentos es el que comentaba en ese mismo issue:
> Al leer más en profundidad la especificación del módulo se van a encontrar con que varias tareas sí o sí tienen que ocurrir en paralelo, así que van a necesitar distintos hilos para procesarlas. Por ejemplo, mandar un proceso en Exec a ejecutar ciclos de CPU y otro en Blocked a leer un archivo del FS.

Otro ejemplo son los comandos por consola: el Kernel tiene que poder ir atendiendo a los procesos en ejecución y a la vez recibir el input del usuario por si se ingresa cualquiera de los comandos. Eso sí o sí debe ser un hilo aparte ya que mientras se quede colgado en un `readline("> ");` el módulo debe poder seguir haciendo el resto de las tareas especificadas (planificación de corto y largo plazo, consultas a memoria y FS, etc).

¿Quedó mas clara la idea?

Saludos

**Comment by jraijman** [comment]
Buenas, va quedando más claro. Entonces sería cada vez que se crea un proceso crear un hilo para el mismo y además otro hilo para la consola?
Gracias!

**Comment by iago64** [comment]
En principio, un hilo para la consola lo van a tener que tener si o si porque ese hilo va a estar bloqueado esperando el input por teclado.
Después el resto de hilos los van a ir creando a medida que quieran hacer más cosas en paralelo como por ejemplo estar esperando un sleep porque bloquean un proceso, o esperando la respuesta del FS o esperando la respuesta de la memoria, etc.

Saludos.-

**Comment by jraijman** [comment]
Perfecto, gracias!
