### ISSUE TITLE
Duda sobre pedido de instrucciones e inicio de proceso

### ISSUE THREAD

**Issue by cserrudo** [sisoputnfrba/foro#3216]
Buenas, tenemos una consulta sobre la interpretación de esta parte del enunciado:

> Al momento de recibir la creación de un proceso, la memoria de instrucciones deberá leer el archivo de pseudocódigo indicado y generar las estructuras que el grupo considere necesarias para poder devolver las instrucciones de a 1 a la CPU según ésta se las solicite por medio del Program Counter. Ante cada petición se deberá esperar un tiempo determinado a modo de retardo en la obtención de la instrucción, y este tiempo, estará indicado en el archivo de configuración.

Pensabamos en que kernel le avisa a memoria que tiene que iniciar un proceso, y si CPU le solicita una instruccion, memoria ademas de crear las estructuras necesarias tambien manda las instrucciones a pedido. 
Si CPU no mandara ninguna solicitud de instrucciones, memoria solo crearia las estructuras, y si kernel no inicia un proceso, CPU no podria pedir instrucciones, es así? Gracias

**Comment by RaniAgus** [comment]
¡Buenas! Es así. Si su duda es si la Memoria _debería_ validar que ante un pedido de instrucciones de CPU el proceso exista, no lo veo estrictamente necesario para el TP ya que no vamos a probar casos de envío de mensajes inválidos. 

Sin embargo, en general está bueno contar con algún log indicando que algo raro está pasando, más que nada para que ustedes mismos puedan detectar la razón del bug y hacer las correcciones necesarias lo antes posible.

Saludos

**Comment by cserrudo** [comment]
Perfecto! Gracias, esa era la duda.
