### ISSUE TITLE
Conexion kernel - CPU

### ISSUE THREAD

**Issue by jraijman** [sisoputnfrba/foro#3218]
Buenas, releyendo el enunciado del kernel nos surgió una duda, nosotros planteamos que el kernel sea cliente de los otros módulos, pero en esta parte de la consigna, nos hace dudar si es necesario que sea servidor tambien para poder estar escuchando el mensaje de exit de la cpu.

### 📔 Citas del enunciado/videos
>Cuando se reciba un mensaje de CPU con motivo de finalizar el proceso, se deberá pasar al mismo al estado EXIT, liberar todos los recursos que tenga asignados y dar aviso al módulo Memoria para que éste libere sus estructuras.

Gracias!

**Comment by RaniAgus** [comment]
¡Buenas! En la parte del módulo CPU del enunciado se especifica que EXIT es una instrucción como cualquier otra (p.20):
> - **EXIT**: Esta instrucción representa la syscall de finalización del proceso. Se deberá devolver el **Contexto de Ejecución** actualizado al Kernel para su finalización.

Y, además, las conexiones entre Kernel y CPU son solamente las de _dispatch_ e _interrupt_ (p. 18):

> Quedará a la espera de las conexiones por parte del Kernel, tanto por el puerto dispatch como por el puerto interrupt. Una vez conectado, el Kernel le enviará el Contexto de Ejecución para ejecutar a través del puerto dispatch. 

A través de la conexión de _dispatch_ se devuelve el contexto de ejecución junto con el motivo de desalojo después de ejecutar cualquier instrucción que requiera de dicho desalojo.

Saludos
