### ISSUE TITLE
Consulta sobre quantum y funciones de tiempo en las commons

### ISSUE THREAD

**Issue by MartinSintas** [sisoputnfrba/foro#3219]
Buenas! tenía algunas dudas:
1) una (1) unidad de quantum sería un milisegundo o un nanosegundo?
2) las funciones de tiempo de las commons (las temporal.h) pueden trabajar con la respectiva unidad de tiempo que use el quantum (si es con ms, que trabaje con ms y si es con ns que trabaje con ns )?

Desde ya muchas gracias :D

**Comment by iago64** [comment]
Buenas! Cómo va?

Respecto al quantum, cito al enunciado (Pag 16):
> Tiempo en milisegundos del quantum para utilizar bajo el algoritmo RR

Respecto a las funciones de tiempo de las commons son para hacer calculos de diferencias de tiempos y que no tengan que romperse la cabeza con eso, si lo que quieren implementar es el quantum preguntando si paso el tiempo en un while(1) eso les va a generar una espera activa y es motivo suficiente para desaprobar.

Saludos.-

**Comment by MartinSintas** [comment]
Buenísimo, muchas gracias resolver la duda :)
