### ISSUE TITLE
Implementación de conexiones entre módulos

### ISSUE THREAD

**Issue by FV-Cano** [sisoputnfrba/foro#3220]
# Contexto

Estamos intentando levantar todos los módulos y establecer todas las conexiones entre ellos. **La estructura planteada, siguiendo la arquitectura del sistema del enunciado del tp, y el comportamiento esperado**, es el siguiente:

1. Levantar el módulo de Memoria (levanta el servidor de memoria)
2. Levantar el módulo FileSystem (FS de ahora en más)
2.1. FS se conecta a Memoria
2.2. FS levanta su servidor
2.3. Memoria se conecta a FS
3. Levantar el módulo CPU
3.1. CPU se conecta a Memoria
3.2. CPU levanta su servidor
4. Levantar el módulo Kernel
4.1. Kernel se conecta a los servidores de Memoria, FS y CPU. 

El resultado obtenido no es el esperado:

- Memoria acepta las conexiones de todos los módulos (implementamos hilos) ✔️ 
- Memoria no se conecta a FS ❌ 
- Kernel no se conecta a CPU de forma total ❌ 

Paso a explicar los dos problemas con un poco más de detalle

## Memoria no se conecta a FS

El título es bastante explicativo por si mismo. Creo que la causa de este comportamiento es que, al levantar Memoria primero, levanta su servidor pero a la vez quiere conectarse como cliente a un servidor que aún no existe ¿Podría llegar a ser el caso? de ser así, ¿Cómo podríamos evitar esto?

## Kernel no se conecta a CPU de forma total

El módulo de CPU en su config tiene 2 puertos, uno de dispatch y otro de interrupt. En este módulo lo que hacemos es iniciar el servidor 2 veces, una vez con el puerto de dispatch y otra vez con el puerto de interrupt. Funciona siempre con el primero que esté en el orden de llegada, independientemente de si es dispatch o interrupt. Luego cuando se quiere iniciar el servidor con el otro puerto no se llega a realizar la conexión. Intentamos implementar hilos pero no nos está saliendo, tampoco sabemos hasta qué punto los servidores manejan recursos compartidos (dado que son sockets diferentes, lo único que comparten es la IP).

---
_Nota: Les pedimos disculpas, sabemos que es muy difícil entender el problema sin mucha información como el código de nuestra parte, pero no sabemos que tanto código deberíamos copiar para ilustrar el problema en el issue. Nuestra idea de igual manera es consultarlo luego con el soporte el sábado, pero queríamos ver si al menos mediante esta vía encontrábamos una forma de encontrarle la vuelta a estos problemas._

### 🔎 Búsqueda en foros

Estuvimos buscando e investigando durante los últimos días y no encontramos nada relevante.

### 📝 Código relevante

```
int servidor(char* puerto_servidor)
{
	serverlogger = log_create("log.log", "Servidor", 1, LOG_LEVEL_DEBUG);

	int socket_server = iniciar_servidor(puerto_servidor);
	log_info(serverlogger, "Servidor listo para recibir al cliente");
	
	while (1)
	{
		int socket_cliente = esperar_cliente(socket_server);

		pthread_t hilo;
		threadConnArgs *threadArgs = malloc(sizeof(threadConnArgs));
		threadArgs->socket_cliente = socket_cliente;

		pthread_create(&hilo, NULL, manejar_conexion, (void *)threadArgs);
		pthread_detach(hilo);
	}
	
	return EXIT_SUCCESS;
}

void *manejar_conexion(void *args)
{
	threadConnArgs *threadArgs = (threadConnArgs *)args;
	int socket_cliente = threadArgs->socket_cliente;

	t_list* lista;
	while (1) {
		int cod_op = recibir_operacion(socket_cliente);
		switch (cod_op) {
		case MENSAJE:
			recibir_mensaje(socket_cliente);
			break;
		case PAQUETE:
			lista = recibir_paquete(socket_cliente);
			log_info(serverlogger, "Me llegaron los siguientes valores:\n");
			list_iterate(lista, (void*) iterator);
			break;
		case -1:
			log_error(serverlogger, "el cliente se desconecto. Terminando servidor");
			close(socket_cliente);
			free(threadArgs);
			pthread_exit(NULL);
		default:
			log_warning(serverlogger,"Operacion desconocida. No quieras meter la pata");
			break;
		}
	}
}
```

### 🐛 Cómo reproducir el error

Mencionado al principio

### 💻 Logs

-

---
Dejo mencionado a @GonzaloGarmon con quien estuve trabajando para implementar esta funcionalidad. Desde ya muchas gracias por su atención.

**Comment by tomasmartinez02** [comment]
Buenas! en cuanto a la primera duda tengan en cuenta que la conexión que se establece después del `accept()` es bidireccional, por lo que ambos módulos pueden comunicarse con `send()` y `recv()` sin importar quien recibio la conexion, si tienen dudas sobre esto revisen la [guía de sockets](https://docs.utnso.com.ar/guias/linux/sockets).
En cuanto a la segunda duda, tal vez falta un poco de contexto como la implementación de `esperar_cliente()` o como invocan a las funciones `servidor(char* puerto_servidor)` y `void *manejar_conexion(void *args)`, pero viendo la implementación de `servidor(char* puerto_servidor)` tienen un `while(1)` en el que crean un hilo y luego hacen `pthread_detach(hilo)`, como no tienen nada bloqueante, estarían creando hilos dentro de un bucle infinito que nunca se bloquea y tal vez el error viene por ahí, se entiende?
Saludos.

**Comment by FV-Cano** [comment]
Perfecto! Todo entendido, muchas gracias!
