### ISSUE TITLE
Consulta con instruccion WAIT

### ISSUE THREAD

**Issue by LautaroRobles** [sisoputnfrba/foro#3222]
En el enunciado aclara que cuando ocurre un SIGNAL el PCB debe continuar ejecutando (no se debe replanificar).

Para WAIT dice que si no hay mas instancias deberia bloquearse. Pero no aclara que deberia suceder si hay instancias disponibles.

¿Debe ir al final de la cola de READY? ¿Debe continuar ejecutando?

**Comment by iago64** [comment]
Buenas! Cómo va?

WAIT tiene que funcionar al igual que como se ve en la teoría, si hay instancias disponibles, el proceso sigue ejecutando ya que no se bloquea.

Saludos.-

**Comment by LeandroCarbajales** [comment]
@LautaroRobles Te sirvió la respuesta de @iago64 ? Quedó alguna duda al respecto?

**Comment by iago64** [comment]
Cerramos el issue por inactividad.
