### ISSUE TITLE
Cómo ejecutar dos procesos a la vez 

### ISSUE THREAD

**Issue by ParedesMicaela** [sisoputnfrba/foro#3223]
Hola buenas! Tenia una consulta sobre cómo puedo probar correr 2 procesos a la vez en mi planificador. Lo que estuvimos haciendo por el momento, fue escribir en un txt unas instrucciones y después escribir la ubicación de ese txt en la consola, pero si quiero probar 2 procesos cómo hago? Gracias!

**Comment by tomasmartinez02** [comment]
Buenas! La consola interactiva que es la que les debe permitir iniciar los procesos debe estar siempre a la espera de nuevos ingresos por pantalla, por lo que luego de ingresar un comando, debe volver a estar a la espera de otro ingreso por pantalla. Si lo que les esta pasando es que por cuestión de velocidad no llegan a ingresar el segundo proceso antes de que finalice el primero, pueden probar con la siguiente secuencia:

1.  Detener la planificación
2.  Iniciar los procesos (la cantidad que quieran)
3.  Iniciar la planificación

Asi, pueden tener la cantidad de procesos que ustedes quieran y en el orden que quieran, todos en el estado NEW, se entiende?
Saludos!

**Comment by ParedesMicaela** [comment]
aaa perfecto, claro, por eso no podiamos. Muchas gracias!
