### ISSUE TITLE
Consulta comando consola finalizar proceso

### ISSUE THREAD

**Issue by itulau** [sisoputnfrba/foro#3225]
Buenas, como estan?

Queria consultarles sobre el comando finalizar proceso. En particular nos interesaría saber si este comando **solamente** se utilizaría para resolver Deadlock, o se ejecutaria en algun otro contexto?

Ya que queremos saber si al implementar dicho comando deberiamos contemplar esos otros casos: Finalizar un proceso en ejecucion, uno bloqueado por sleep, etc...

Gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

El finalizar aplica para cualquier caso, por lo que si, tienen que manejar la posibilidad de que les tiremos un finalizar a un proceso en ejecución, mas que nada tambien por si alguien comete un error en la prueba que no explote todo porque mato al proceso "incorrecto"

Saludos.-

**Comment by LeandroCarbajales** [comment]
Hola @itulau 
Te sirvió la respuesta de @iago64 ? Se puede cerrar el issue?

**Comment by itulau** [comment]
Si, gracias
