### ISSUE TITLE
Consulta sobre el desalojo por prioridades

### ISSUE THREAD

**Issue by itulau** [sisoputnfrba/foro#3226]
Buenas teniamos otra consulta con respecto a lo que pide el enunciado "En caso que el algoritmo requiera desalojar al proceso en ejecución, se enviará una interrupción a través de la conexión de interrupt para forzar el desalojo del mismo."

A la hora de implementar esto para el algoritmo de Prioridades, nos genera un conflicto la siguiente situacion: Suponiendo que tenemos el planificador de corto plazo que esta por tomar un proceso de ready y pasarlo a EXEC, y justo al mismo tiempo el planificador de largo plazo recibe un proceso nuevo con mayor prioridad que el que se está **JUSTO** por ejecutar. Deberiamos sincronizar esto para que el evento de "desalojar por interrupt" espere a que haya algun proceso en EXEC para desalojarlo, o este caso no podria darse?

**Comment by iago64** [comment]
Buenas! Cómo va?

Algo super interesante es que el justo se esta por dar o en el mismo instante o ese tipo de conceptos, son cosas que se ven en la teoría porque hablamos siempre de tiempos discretos, es decir, siempre hablamos de instantes T1, T2, T3, etc.
En la realidad es practicamente imposible que 2 cosas ocurran al mismo tiempo ya que incluso en la VM server van a correr con 1 solo core, con lo cual, si el proceso esta haciendo algo, no va a poder hacer otra cosa "al mismo tiempo".
Con lo cual, si definen bien las regiones críticas no deberían preocuparse, ya que si mandan a EXEC un proceso con una prioridad y llega otro con una prioridad mayor, bueno, ejecutará una instrucción y tendrá que ser desalojado.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas @itulau !
Quedó alguna duda con esto?
