### ISSUE TITLE
Duda sobre la asignación de recursos

### ISSUE THREAD

**Issue by ParedesMicaela** [sisoputnfrba/foro#3227]
Hola buenas! Tenia una consulta sobre el manejo de recursos entre kernel y cpu. Cuando la cpu le devuelve su contexto  de ejecucion al kernel por motivo de wait, el kernel tiene que hacer toda la lógica de ver si el recurso existe, mandar el proceso a exit si no existe, crear las colas de bloqueo por cada recurso si no esta disponible y asignar el recurso si es que esta disponible. Toda la parte lógica de manejar la asignacion de recurso la hice. Mi problema es que a la hora de asignarle el recurso a la cpu y mandarle el contexto, no sé de qué tipo hacer los recursos asignados. O sea yo pensaba hacer, dentro de la estructura pcb, algo como `recursos_asignados` pero no sé de que tipo conviene hacerlo porque depende de lo que me pidan. 

### 💭 Soluciones posibles
-Si tengo que mostrar el nombre de los recursos que tengo asignados capaz me conviene una t_list o un char**, en el cual me quedaria algo como "[RA,RB,RC]"pero yo imagino que los procesos me deben poder pedir más de una instancia de un recurso entonces no sé si me sirve tanto.
-Si tengo que mostrar unicamente la cantidad de instancias que el proceso tiene de cada recurso ("[0,2,1]") capaz me conviene hacerlo como un int*.

Pregunto porque capaz me estoy complicando yo sola con el tema de cómo hacer la asignación de recursos y hay una forma más sencilla de hacerlo 😅. Gracias!

**Comment by LeandroCarbajales** [comment]
Buenas!
Y por qué no las dos? :)
Por ejemplo armarse un "t_recurso" con su nombre y una cantidad, esta misma estructura te podría servir para tu lista de asignados como de disponibles por ejemplo.

Te sirve la idea?
Saludos!
        Lean

**Comment by ParedesMicaela** [comment]
Buenísimo Lean! Ahí ya lo implementé en el código y quedó genial. Además creo que también va a servir para deadlock, muchas gracias!
