### ISSUE TITLE
traducción de direcciones lógicas a física

### ISSUE THREAD

**Issue by Fcallero** [sisoputnfrba/foro#3228]
Buenas, entiendo que para hacer la traducción de dirección lógica a física, necesito el tamaño de pagina, pero eso en CPU de donde lo obtengo? porque en el archivo de configuración no esta, solo lo tiene la memoria y en el enunciado de este modulo, en el apartado de "Comunicación con Kernel, CPU y Filesystem" no aparece el acceso a tamaño de pagina o similar, por lo tanto de donde debería sacar el tamaño de pagina? saludos

**Comment by LeandroCarbajales** [comment]
Buenas!
Citando al enunciado de CPU (Lineamiento e Implementación):

> Al iniciar la CPU se deberá conectar al módulo Memoria y realizará un handshake inicial para **recibir de la memoria la información relevante que le permita traducir las direcciones lógicas en direcciones físicas**, esta información debería incluir al menos el **tamaño de página**.

Te aclara la duda?
Saludos!
      Lean

**Comment by Fcallero** [comment]
Ah perfecto, me olvide de esa parte, muchas gracias.
