### ISSUE TITLE
Duda sobre Check Interrupt con instrucciones que consultan al Kernel

### ISSUE THREAD

**Issue by LautaroRobles** [sisoputnfrba/foro#3230]
Buenas, tenemos la siguiente consulta.

Por el ciclo de instruccion de la CPU una cosa que detectamos es que con WAIT y SIGNAL se estan ignorando las interrupciones de fin de quantum y llegada de proceso de mayor prioridad, ya que estas instrucciones devuelven el contexto de ejecucion antes que se pueda ejecutar el Check Interrupt, por lo que entendimos del enunciado y la teoria.

¿Como podriamos solucionar esto?

**Comment by LeandroCarbajales** [comment]
Buenas!
A efectos del TP ese es el comportamiento esperado, pueden descartar esa interrupción pendiente si en ese ciclo ya devolvieron el contexto de ejecución.

**Comment by LautaroRobles** [comment]
Claro, el problema es que el CPU devuelve el contexto con motivo de WAIT o SIGNAL, por lo tanto se ejecuta el codigo de (por ejemplo) SIGNAL y se lo devuelve a la CPU. La CPU deberia devolver por motivo de INTERRUPT para saber que ejecutar.

**Comment by LeandroCarbajales** [comment]
Es un caso de uso que no nos interesa probar a ese nivel de detalle.
Idealmente se me ocurre que tendría que hacer ambas cosas, realizar el signal y desalojar (estaríamos devolviendo el contexto con 2 motivos). Otra opción es hacer el signal, volver a la CPU y será desalojado en la próxima instrucción, a efectos prácticos la idea es que las pruebas que armemos no dependan de este tipo de eventos que ocurran al mismo tiempo sino que sea algo que sea relativamente predecible, por ejemplo una prueba de deadlock (para probar los wait y signal) la podemos hacer por FIFO y no depender de desalojos.

**Comment by LautaroRobles** [comment]
Quiero darte un poco mas de contexto en como lo pensamos nosotros.

El enunciado dice
> A la hora de recibir de la CPU un Contexto de Ejecución desalojado por SIGNAL [...] Una vez hecho esto, se devuelve la ejecución al proceso que peticiona el SIGNAL.

Con esto entendimos que hay algunas **instrucciones** que devuelven el contexto de ejecucion pero despues deben continuar ejecutando.

Entonces la CPU cuando lee alguna instruccion por la que tenga que **desalojar (SLEEP, WAIT, SIGNAL)**:
1. Envia el mensaje (SLEEP, WAIT, SIGNAL) al Kernel por dispatch (enviando el contexto de ejecucion actualizado)
2. No hace el CHECK INTERRUPT (porque ya se desalojo el proceso)
3. Se queda a la espera de un proceso que envie el Kernel.

El Kernel espera que el contexto sea desalojado:
Si fue desalojado por:
- WAIT: 
	- Si hay instancias disponibles: Le asigna el recurso y **envia el mismo proceso a la CPU**
	- Si no hay instancias disponibles: Lo bloquea y **replanifica (envia otro proceso o espera a que haya uno en READY)**
- SIGNAL:
	- Aumenta la cantidad de instancias y **envia el mismo proceso a la CPU**

Con este contexto nos puede pasar este problema:

Supongamos que 
- Algoritmo RR con Q=1
- Recurso RA=1
- Instrucciones:
```
WAIT RA
SIGNAL RA
WAIT RA
SIGNAL RA
WAIT RA
SIGNAL RA
WAIT RA
SIGNAL RA
EXIT
```

Por cada instruccion el proceso se desaloja de la CPU y luego el Kernel lo devuelve.
## Se ignorarian las interrupciones de fin de quantum

**Comment by LeandroCarbajales** [comment]
Buenas!
Su análisis es correcto, están entendiendo bien el enunciado. En ese caso el proceso no sería desalojado por fin de quantum, en un sistema real esto sería un problema o podríamos verlo como que durante la ejecución de estas "syscalls" se deshabilitan las interrupciones.
Bajo cualquier interpretación, es un caso borde que tenemos identificado y no nos preocupa a la hora de testear ya que las pruebas intentamos armarlas para que sean predecibles, llegado el caso que ocurra durante la ejecución de una prueba estarían en lo correcto en que se termine comportando de esa manera dadas las limitaciones de este sistema.

**Comment by LautaroRobles** [comment]
Muchas gracias!!! :100:
