### ISSUE TITLE
Consulta instruccion leer archivo FS

### ISSUE THREAD

**Issue by lucasosacuenca** [sisoputnfrba/foro#3232]
Buenas, como va? tenia una duda con esta parte del enunciado: 
>Leer Archivo
Esta operación leerá la información correspondiente al bloque a partir del puntero, siempre se leerá el contenido completo del bloque. 
>
Esto se refiere a que el puntero va a apuntar al bloque del que se debe leer(el bloque entero) o me apunta a un bloque, y yo debo leer desde donde esta ese puntero hasta donde finaliza el bloque?

**Comment by iago64** [comment]
Buenas! Cómo va?

Gracias por el issue, nos dimos cuenta que nos quedo algo inconsistente, lo vamos a estar corrigiendo en una próxima errata.

Saludos.-

**Comment by LeandroCarbajales** [comment]
@lucasosacuenca 
En la última errata se agregó una aclaración sobre esto, te aclara la duda?

**Comment by lucasosacuenca** [comment]
sisi basicamente nos pasan el puntero apuntando al bloque y leemos/escribimos el bloque entero, verdad?

**Comment by LeandroCarbajales** [comment]
Por las dudas cito la parte relevante:

> Nota: El tamaño de la información a leer/escribir de la memoria coincidirá con el tamaño del bloque / página. Siempre se leerá/escribirá un bloque completo, **los punteros utilizados siempre serán el 1er byte del bloque o página**.

El puntero apuntaría al primer byte del bloque, desde ahí leen el tamaño de un bloque :)

Saludos!
     Lean
