### ISSUE TITLE
Dudas sobre manejo de interrupciones

### ISSUE THREAD

**Issue by FV-Cano** [sisoputnfrba/foro#3233]
Buenas! Estoy con unos problemas intentando organizar lógicamente el manejo de Interrupciones, más específicamente en el módulo de Kernel. Actualmente estoy trabajando con los planificadores de largo y corto plazo, con sus 3 algoritmos de planificación respectivamente.
La lógica de funcionamiento en general la tengo, sé cómo debe funcionar y tengo un boceto de código general que define esa secuencia de funcionamiento. Mi problema viene con las interrupciones en la ejecución de un proceso. Los pongo en contexto para que entiendan bien a lo que me refiero.

Inicialmente mi planteo era tener dos hilos en paralelo ejecutando constantemente y que estos tengan las funcionalidades de los planificadores de largo y corto plazo. Si bien estos hilos cuentan con espera activa, controlo la sincronización con semáforos.
Esto teóricamente funcionaria para algunos escenarios (crear proceso -> proceso new a ready -> ready a exec, etc).
El problema viene cuando yo recibo una Interrupción (por ejemplo EXIT). Cómo debería representar la ejecución de la instrucción? Debería tener dentro de mi while(1) una comprobación constante si hay o no una instrucción? Siento que no debería ser así.

Otra opción que plantee fue que Kernel reciba mensajes y realice acciones según los mensajes que recibe, así delegando toda la funcionalidad a una única función. El problema es que no sé si se puede hacer eso, este comportamiento que describo es el de un servidor, y se supone que justo Kernel no es servidor de nadie. 
La verdad que estoy muy perdido y no se me ocurre cómo encarar este problema, creo que cada vez me voy más por las ramas. Espero que se entienda mi inquietud. Mil disculpas por la longitud del mensaje y gracias de antemano!

**Comment by FV-Cano** [comment]
Hago un update intentando explicar un poco mejor mis alternativas de solución porque tal vez doy muchas vueltas con el texto.

Alternativa 1:
- Hacer un solo hilo que sea un message handler enorme y que tenga la lógica completa del kernel como un pseudo-servidor (en términos de implementación reduciría muchísimo el overhead y los problemas de sincronización)

Alternativa 2:
- Seguir con los hilos de ambos planificadores y en cada "iteración" de la planificación chequear por interrupciones en un momento dado específicamente para evitar problemas de sincronización y recién ahí atender a las interrupciones (serían 3 hilos, dos de los planificadores y un message handler que se mantiene en escucha activa y si recibe un mensaje que sea una interrupción activa la lógica en los planificadores).

Son ambas soluciones viables? Me estoy equivocando en algo? Gracias!

**Comment by LeandroCarbajales** [comment]
Buenas!
En primera medida quiero corroborar que estamos entendiendo lo mismo en cuanto a qué es lo esperado en el comportamiento del TP.

> El problema viene cuando yo recibo una Interrupción (por ejemplo EXIT). Cómo debería representar la ejecución de la instrucción?

Cuando te referís a "cuando yo recibo una interrupción" entiendo que te estás refiriendo al módulo Kernel en este caso. Si es así, vamos a separar los casos de uso y las palabras que usamos en cada uno:

El módulo Kernel en este TP no recibe interrupciones sino que es quien, ante ciertos eventos, le envía (a través del socket _interrupt_) al módulo CPU el aviso de que tiene que devolver el proceso en ejecución, y esto es a lo único que le llamamos interrupción en este TP.

El caso que das de EXIT por ejemplo (que entiendo que podrían ser WAIT, SIGNAL u otras), que es la CPU quien nos lo envía (a través del puerto _dispatch_) es porque voluntariamente, como parte de la ejecución normal, nos está devolviendo el contexto para que el módulo Kernel haga algo, estas instrucciones las podemos pensar como "syscalls" en este TP.
Para este caso de uso mi recomendación sería que el mismo hilo que se encarga de planificador de corto plazo (ready -> exec) se quede esperando a que la CPU le responda (quedaría bloqueado en el recv() del socket) ya que de cualquier modo no tendría sentido volver a planificar si todavía sigue ejecutando el proceso que mandamos a exec. Por otro lado, es este mismo hilo quien puede encargarse de interpretar y efectuar esa syscall ya que dependiendo de la misma puede que deba seguir ejecutando el mismo proceso (no replanificar) o que debamos finalizarlo, bloquearlo, etc y por lo tanto debamos replanificar.

Te aclara la idea?
Saludos!
    Lean

**Comment by FV-Cano** [comment]
Buenas! 
Gracias por responder,

En primer lugar:

> Cuando te referís a "cuando yo recibo una interrupción" entiendo que te estás refiriendo al módulo Kernel en este caso. Si es así, vamos a separar los casos de uso y las palabras que usamos en cada uno:
>
>El módulo Kernel en este TP no recibe interrupciones sino que es quien, ante ciertos eventos, le envía (a través del socket interrupt) al módulo CPU el aviso de que tiene que devolver el proceso en ejecución, y esto es a lo único que le llamamos interrupción en este TP.

Exactamente, entendiste mi problema a la perfección. Gracias por las palabras para cada caso, me estaba explicando muy mal.

Sobre la implementación, creo que me quedó más claro. Tal y como indicas, tiene sentido que el PCP se quede bloqueado en recv() porque no va a replanificar de otro modo. En base a esto me surgen dos preguntas. La primera tiene que ver con un fragmento de la consigna:

>Finalizar proceso: Se encargará de finalizar un proceso que se encuentre dentro del sistema. Este mensaje se encargará de realizar las mismas operaciones como si el proceso llegara a EXIT por sus caminos habituales (deberá liberar recursos, archivos y memoria).
Nomenclatura: FINALIZAR_PROCESO [PID]

En este caso, y considerando lo hablado anteriormente, a fines prácticos lo que haría la llamada de finalizar proceso por consola es hacer que el CPU devuelva el contexto de ejecución del proceso en ejecución al Kernel como si hubiese finalizado normalmente con la instrucción EXIT, por lo tanto el razonamiento sería el mismo que el que me comentaste, no es así?

Mi otra duda está relacionada con los desalojos de RR o prioridades. Con esto que me dijiste entiendo que la lógica es bastante similar. En RR por ejemplo el PCP va a estar bloqueado en recv() pero también debería estar a la espera de que haya un desalojo por quantum (podría ser un mensaje?). Lo mismo sucedería con prioridades si entra un proceso de mayor prioridad.

Nuevamente muchas gracias por la ayuda
Saludos!

**Comment by LeandroCarbajales** [comment]
> En RR por ejemplo el PCP va a estar bloqueado en recv() pero también debería estar a la espera de que haya un desalojo por quantum (podría ser un mensaje?).

Me parecería raro que un hilo esté bloqueado en recv() y a la vez haciendo otra cosa :P
El mensaje de desalojo (tanto en prioridades como en RR) se lo pueden enviar a CPU desde cualquier otro hilo, luego el PCP recibiría el contexto de ejecución como siempre pero con motivo de "desalojo" en vez de alguna de las syscalls que normalmente manda CPU.
El mensaje de finalizar proceso para un proceso en ejecución lo pueden pensar como un desalojo más, con la diferencia de que, en vez de devolverlo a ready, a éste lo finalizarían una vez devuelva el contexto.

**Comment by FV-Cano** [comment]
Buenísimo! Muchas gracias Lean! Estoy mejor encaminado ahora. Ahora a intentar ponerlo en práctica. Gracias nuevamente!
