### ISSUE TITLE
Duda sobre restar registros

### ISSUE THREAD

**Issue by ParedesMicaela** [sisoputnfrba/foro#3234]
Hola buenas! Tenia una duda con el tema de restar registros; en el enunciado dicen que son valores enteros no signados de 4 bytes pero al restarlos debería de tomar el absoluto o solamente debería poder restarse si la resta es >= a 0?

**Comment by LeandroCarbajales** [comment]
Buenas!
No vamos a probar ningún caso en que una resta dé menos que cero, por lo que queda a su consideración :)

Saludos!
     Lean

**Comment by ParedesMicaela** [comment]
Buenisimo, gracias!
