### ISSUE TITLE
Duda Quantum RR

### ISSUE THREAD

**Issue by MartinSintas** [sisoputnfrba/foro#3236]
Buenas justo estaba probando en las pruebas el  RR  y me está sucediendo maso menos lo mismo con el grupo que hizo el issue hace un rato #3235 , pero mí duda iba más por otro lado, con el quantum de la configuracion *QUANTUM=2000* me está terminando los procesos antes de que finalice el quantum por lo que no termina como PLANI_3, PLANI_2 y PLANI_1 sino que se realiza el orden PLANI_1, PLANI_2 y PLANI_3. al ver esto, me puse a recordar la teoría donde sabemos que si un quantum de Round Robin es exageradamente grande, el algoritmo se va a comportar como FIFO, por eso mi duda con si está bien que el *QUANTUM=2000* o debería ser más chico
### 📔 Citas del documento de pruebas
> QUANTUM=2000
Página 5

### 👍 Comportamiento esperado
>En RR los procesos terminan PLANI_3, PLANI_2, PLANI_1

### 👎 Comportamiento obtenido
*PLANI_1, PLANI_2, PLANI_3*

**Comment by LeandroCarbajales** [comment]
Buenas!
Acabo de responder en el otro issue y me suena que tu problema probablemente se deba a lo mismo, con un retraso de 1 segundo al buscar cada instrucción los procesos deberían ser desalojados por el quantum varias veces.

**Comment by MartinSintas** [comment]
Buenísimo Lean, con el grupo vamos a probar con eso, muchas gracias :D
