### ISSUE TITLE
Recursos en enunciado de prueba + enunciado de TP

### ISSUE THREAD

**Issue by diegohcanetti** [sisoputnfrba/foro#3237]
Estabamos haciendo las pruebas propuestas y no hemos entendido del todo que error se debería ocasionar en el error 2. Además de que no entendemos a que se refiere el hecho de que no haya sido solicitado por ese proceso.

### 📔 Citas del enunciado
>ERROR_2 → Recurso no tomado

Además de esta parte del enuncidado: 
>Para las operaciones de WAIT y SIGNAL donde no se cumpla con las verificaciones (no haya sido solicitado por ese proceso), se deberá enviar el proceso a EXIT.

**Comment by LeandroCarbajales** [comment]
Buenas!
Cito esa parte del enunciado:

> A la hora de recibir de la CPU un Contexto de Ejecución desalojado por SIGNAL, el Kernel deberá verificar primero que exista el recurso solicitado, luego que el proceso cuente con una instancia del recurso (solicitada por WAIT) y por último sumarle 1 a la cantidad de instancias del mismo. En caso de que corresponda, desbloquea al primer proceso de la cola de bloqueados de ese recurso. Una vez hecho esto, se devuelve la ejecución al proceso que peticiona el SIGNAL.

> Para las operaciones de WAIT y SIGNAL donde no se cumpla con las verificaciones (ya sea que el recurso no exista o no haya sido solicitado por ese proceso), se deberá enviar el proceso a EXIT.

La idea es que un proceso no pueda liberar un recurso que no tiene asignado, de lo contrario estaríamos creando nuevas instancias del mismo y dificultaría la detección de deadlocks.

Queda más clara la idea?
Saludos!
         Lean

**Comment by diegohcanetti** [comment]
Ya entendí, ahí me queda más claro.
