### ISSUE TITLE
Round Robin no funciona como se espera

### ISSUE THREAD

**Issue by MartinSintas** [sisoputnfrba/foro#3238]
Buenas! me encontraba haciendo la prueba de la planificación para round robin (teniendo en cuenta el retardo de un 1 segundo en memoria) y su comportamiento no es el esperado, adjunto código y los scripts del kernel y cpu. Seguramente hay algo que está mal en la función del RR pero no lo estoy viendo :(

### 📝 Código relevante
t_pcb *obtener_siguiente_RR()
{
    log_info(kernel_logger, "Inicio la planificación RR\n");

    int quantum = config_valores_kernel.quantum; 

    // hace el bloqueo y desbloqueo de ready
    pthread_mutex_lock(&mutex_ready);
    t_pcb *proceso_seleccionado = list_remove(dictionary_int_get(diccionario_colas, READY), 0);
    pthread_mutex_unlock(&mutex_ready);

    if (proceso_seleccionado != NULL)
    {
        log_info(kernel_logger, "PID[%d] sale de READY por planificación RR", proceso_seleccionado->pid);

        int tiempo_restante = quantum; // Comienza con el valor del quantum

        while (tiempo_restante > 0)
        {
            usleep(1000); // Simula la ejecución y pausa el proceso en 1 ms

            // Si el proceso finaliza durante su ejecución, es porque está en EXIT
            if (proceso_seleccionado->estado_pcb == EXIT)
            {
                log_info(kernel_logger, "PID[%d] ha finalizado durante su quantum de RR\n", proceso_seleccionado->pid);
                pthread_mutex_lock(&mutex_exit);
                list_remove(dictionary_int_get(diccionario_colas, EXIT), 0);
                pthread_mutex_unlock(&mutex_exit);
                return proceso_seleccionado;
            }

            tiempo_restante--; 
        }

        if (tiempo_restante == 0)
        {
            log_info(kernel_logger, "PID[%d] ha agotado su quantum de RR y se mueve a READY\n", proceso_seleccionado->pid);
            
            // Mueve el proceso al final de la cola READY.
            pthread_mutex_lock(&mutex_ready);
            list_add(dictionary_int_get(diccionario_colas, READY), proceso_seleccionado);
            pthread_mutex_unlock(&mutex_ready);
        }
    }
    
    return proceso_seleccionado;
}

### 💻 Logs
KERNEL:

>INICIAR_PLANIFICACION
INICIO DE PLANIFICACIÓN 
Busco otra instrucción
>[INFO] 20:53:17:988 kernel.log/(7283:7286): PID[1] sale de NEW para planificacion 

[INFO] 20:53:17:988 kernel.log/(7283:7286): PID: 1 - Estado Anterior: New - Estado Actual Ready

[INFO] 20:53:17:989 kernel.log/(7283:7286): Cola READY RR : [1]

[INFO] 20:53:17:989 kernel.log/(7283:7286): PID[2] sale de NEW para planificacion 

[INFO] 20:53:17:989 kernel.log/(7283:7286): PID: 2 - Estado Anterior: New - Estado Actual Ready

[INFO] 20:53:17:989 kernel.log/(7283:7286): Cola READY RR : [1, 2]

[INFO] 20:53:17:989 kernel.log/(7283:7286): PID[3] sale de NEW para planificacion 

[INFO] 20:53:17:989 kernel.log/(7283:7286): PID: 3 - Estado Anterior: New - Estado Actual Ready

[INFO] 20:53:17:989 kernel.log/(7283:7286): Cola READY RR : [1, 2, 3]

[INFO] 20:53:17:989 kernel.log/(7283:7287): El algoritmo de planificacion elegido es RR 

[INFO] 20:53:17:989 kernel.log/(7283:7287): Inicio la planificación RR

[INFO] 20:53:17:989 kernel.log/(7283:7287): PID[1] sale de READY por planificación RR
[INFO] 20:53:21:387 kernel.log/(7283:7287): PID[1] ha agotado su quantum de RR y se mueve a READY

[INFO] 20:53:21:387 kernel.log/(7283:7287): PID[1] ingresando a EXEC

[INFO] 20:53:21:387 kernel.log/(7283:7287): PID: 1 - Estado Anterior: Ready - Estado Actual Exec

[INFO] 20:53:21:387 kernel.log/(7283:7287): Se envio el PCB 1 a la CPU 

[INFO] 20:53:56:463 kernel.log/(7283:7287): Recibi el PCB 1 de la cpu por motivo de: exit

[INFO] 20:53:56:466 kernel.log/(7283:7287): PID: 1 - Estado Anterior: Exec - Estado Actual Exit

[INFO] 20:53:56:467 kernel.log/(7283:7287): [EXIT]Sale de EXIT y Finaliza el  PCB de ID: 1

[INFO] 20:53:56:471 kernel.log/(7283:7287): Enviando a memoria liberar estructuras del proceso 

[INFO] 20:53:56:480 kernel.log/(7283:7287): Respuesta memoria de estructuras liberadas del proceso recibida 

[INFO] 20:53:56:480 kernel.log/(7283:7287): El algoritmo de planificacion elegido es RR 

[INFO] 20:53:56:480 kernel.log/(7283:7287): Inicio la planificación RR

[INFO] 20:53:56:480 kernel.log/(7283:7287): PID[2] sale de READY por planificación RR
[INFO] 20:53:59:399 kernel.log/(7283:7287): PID[2] ha agotado su quantum de RR y se mueve a READY

[INFO] 20:53:59:399 kernel.log/(7283:7287): PID[2] ingresando a EXEC

[INFO] 20:53:59:399 kernel.log/(7283:7287): PID: 2 - Estado Anterior: Ready - Estado Actual Exec

[INFO] 20:53:59:400 kernel.log/(7283:7287): Se envio el PCB 2 a la CPU 

[INFO] 20:54:18:476 kernel.log/(7283:7287): Recibi el PCB 2 de la cpu por motivo de: exit

[INFO] 20:54:18:477 kernel.log/(7283:7287): PID: 2 - Estado Anterior: Exec - Estado Actual Exit

[INFO] 20:54:18:478 kernel.log/(7283:7287): [EXIT]Sale de EXIT y Finaliza el  PCB de ID: 2

[INFO] 20:54:18:479 kernel.log/(7283:7287): Enviando a memoria liberar estructuras del proceso 

[INFO] 20:54:18:479 kernel.log/(7283:7287): Respuesta memoria de estructuras liberadas del proceso recibida 

[INFO] 20:54:18:479 kernel.log/(7283:7287): El algoritmo de planificacion elegido es RR 

[INFO] 20:54:18:479 kernel.log/(7283:7287): Inicio la planificación RR

[INFO] 20:54:18:479 kernel.log/(7283:7287): PID[3] sale de READY por planificación RR
[INFO] 20:54:21:849 kernel.log/(7283:7287): PID[3] ha agotado su quantum de RR y se mueve a READY

[INFO] 20:54:21:850 kernel.log/(7283:7287): PID[3] ingresando a EXEC

[INFO] 20:54:21:850 kernel.log/(7283:7287): PID: 3 - Estado Anterior: Ready - Estado Actual Exec

[INFO] 20:54:21:850 kernel.log/(7283:7287): Se envio el PCB 3 a la CPU 

[INFO] 20:54:28:934 kernel.log/(7283:7287): Recibi el PCB 3 de la cpu por motivo de: exit

[INFO] 20:54:28:934 kernel.log/(7283:7287): PID: 3 - Estado Anterior: Exec - Estado Actual Exit

[INFO] 20:54:28:934 kernel.log/(7283:7287): [EXIT]Sale de EXIT y Finaliza el  PCB de ID: 3

[INFO] 20:54:28:934 kernel.log/(7283:7287): Enviando a memoria liberar estructuras del proceso 

[INFO] 20:54:28:935 kernel.log/(7283:7287): Respuesta memoria de estructuras liberadas del proceso recibida 

---------------------------------------------------------------------------------------------------------------------------------------
CPU (solo el proceso 3 que es el más corto): 

[INFO] 20:54:18:476 cpu.log/(7279:7279): Espero recibir paquete
[INFO] 20:54:21:850 cpu.log/(7279:7279): Ya recibi paquete
[INFO] 20:54:21:850 cpu.log/(7279:7279): Recibi un PCB del Kernel :)

[INFO] 20:54:22:919 cpu.log/(7279:7279): PID: 3 - Ejecutando: SET - AX - 1

[INFO] 20:54:22:919 cpu.log/(7279:7279): AX = 1 BX = 1 CX = 8 DX = 1
[INFO] 20:54:22:919 cpu.log/(7279:7279): Recursos Asignados: Recurso - Cantidad: 0
[INFO] 20:54:22:919 cpu.log/(7279:7279): Recursos Asignados: Recurso - Cantidad: 0
[INFO] 20:54:22:919 cpu.log/(7279:7279): Recursos Asignados: Recurso - Cantidad: 0
[INFO] 20:54:23:920 cpu.log/(7279:7279): PID: 3 - Ejecutando: SET - BX - 1

[INFO] 20:54:23:920 cpu.log/(7279:7279): AX = 1 BX = 1 CX = 8 DX = 1
[INFO] 20:54:23:920 cpu.log/(7279:7279): Recursos Asignados: Recurso - Cantidad: 0
[INFO] 20:54:23:920 cpu.log/(7279:7279): Recursos Asignados: Recurso - Cantidad: 0
[INFO] 20:54:23:920 cpu.log/(7279:7279): Recursos Asignados: Recurso - Cantidad: 0
[INFO] 20:54:24:922 cpu.log/(7279:7279): PID: 3 - Ejecutando: SET - CX - 1

[INFO] 20:54:24:922 cpu.log/(7279:7279): AX = 1 BX = 1 CX = 1 DX = 1
[INFO] 20:54:24:923 cpu.log/(7279:7279): Recursos Asignados: Recurso - Cantidad: 0
[INFO] 20:54:24:923 cpu.log/(7279:7279): Recursos Asignados: Recurso - Cantidad: 0
[INFO] 20:54:24:923 cpu.log/(7279:7279): Recursos Asignados: Recurso - Cantidad: 0
[INFO] 20:54:25:929 cpu.log/(7279:7279): PID: 3 - Ejecutando: SET - DX - 1

[INFO] 20:54:25:929 cpu.log/(7279:7279): AX = 1 BX = 1 CX = 1 DX = 1
[INFO] 20:54:25:929 cpu.log/(7279:7279): Recursos Asignados: Recurso - Cantidad: 0
[INFO] 20:54:25:929 cpu.log/(7279:7279): Recursos Asignados: Recurso - Cantidad: 0
[INFO] 20:54:25:930 cpu.log/(7279:7279): Recursos Asignados: Recurso - Cantidad: 0
[INFO] 20:54:26:930 cpu.log/(7279:7279): PID: 3 - Ejecutando: SUM - AX - BX

[INFO] 20:54:26:931 cpu.log/(7279:7279): AX = 2 BX = 1 CX = 1 DX = 1
[INFO] 20:54:26:931 cpu.log/(7279:7279): Recursos Asignados: Recurso - Cantidad: 0
[INFO] 20:54:26:931 cpu.log/(7279:7279): Recursos Asignados: Recurso - Cantidad: 0
[INFO] 20:54:26:931 cpu.log/(7279:7279): Recursos Asignados: Recurso - Cantidad: 0
[INFO] 20:54:27:932 cpu.log/(7279:7279): PID: 3 - Ejecutando: SUM - CX - DX

[INFO] 20:54:27:933 cpu.log/(7279:7279): AX = 2 BX = 1 CX = 2 DX = 1
[INFO] 20:54:27:933 cpu.log/(7279:7279): Recursos Asignados: Recurso - Cantidad: 0
[INFO] 20:54:27:933 cpu.log/(7279:7279): Recursos Asignados: Recurso - Cantidad: 0
[INFO] 20:54:27:933 cpu.log/(7279:7279): Recursos Asignados: Recurso - Cantidad: 0
[INFO] 20:54:28:934 cpu.log/(7279:7279): PID: 3 - Ejecutando: EXIT

[INFO] 20:54:28:934 cpu.log/(7279:7279): Devolvi el contexto ejecucion al kernel por motivo de: exit

**Comment by iago64** [comment]
Buenas! Cómo va?

Estuve revisando un poco el código y hay una cosa que no me cierra y es que, si no entendí mal, estas esperando el quantum antes de devolver el PCB y mandárselo a la CPU.

Lo que deberías hacer en RR es devolver el PCB que le toca ejecutar, mandárselo a la CPU y recién ahi iniciar el thread que haga el `sleep()` (o `usleep()` del quantum).

Saludos.-

**Comment by MartinSintas** [comment]
buenísimo Dami, voy a probar con eso... si me vuelvo a trabar reabro el issue :D

**Comment by MartinSintas** [comment]
estuvimos probando una nueva implementación para RR pero sucede otro error 😭 
NOTA: cabe aclarar que al momento de mandar un proceso a cpu ya se le está enviando el pcb antes de quantum
### código relevante
t_pcb *obtener_siguiente_RR()
{
    log_info(kernel_logger, "Inicio la planificación RR\n");

    int quantum = config_valores_kernel.quantum;

    // Bloquea y desbloquea el mutex de READY para sacar el primer proceso de la cola.
    pthread_mutex_lock(&mutex_ready);
    t_pcb *proceso_seleccionado = list_remove(dictionary_int_get(diccionario_colas, READY), 0);
    pthread_mutex_unlock(&mutex_ready);

    if (proceso_seleccionado != NULL)
    {
        log_info(kernel_logger, "PID[%d] sale de READY por planificación RR", proceso_seleccionado->pid);

        

        // Simula la ejecución del proceso reduciendo el tiempo restante.
        while (quantum > 0)
        {
            usleep(1000); // Simula la ejecución de una instrucción
            quantum--;
            //tiempo_restante--;

            if (quantum == 0)
        {
            // Reinicia el tiempo restante para el siguiente proceso.
            log_info(kernel_logger, "PID[%d] ha agotado su quantum de RR y se mueve a READY\n", proceso_seleccionado->pid);
            //quantum = config_valores_kernel.quantum;


            pthread_mutex_lock(&mutex_exec);
            list_remove_element(dictionary_int_get(diccionario_colas, EXEC), proceso_seleccionado);
            pthread_mutex_unlock(&mutex_exec);
            
            t_paquete *paquete = crear_paquete(DESALOJO);
            agregar_entero_a_paquete(paquete, proceso_seleccionado->pid);
            enviar_paquete(paquete, socket_cpu_interrupt);
            eliminar_paquete(paquete);

            pthread_mutex_lock(&mutex_ready);
            t_pcb *proceso_siguiente = list_remove(dictionary_int_get(diccionario_colas, READY), 0);
            pthread_mutex_unlock(&mutex_ready);
            
            return proceso_siguiente;
            
        } 
        
        }
        
    }

    return NULL;
}

### LOGS
### KERNEL
INICIO DE PLANIFICACIÓN 
Busco otra instrucción
>[INFO] 20:21:20:187 kernel.log/(8113:8116): PID[1] sale de NEW para planificacion 

[INFO] 20:21:20:188 kernel.log/(8113:8116): PID: 1 - Estado Anterior: New - Estado Actual Ready

[INFO] 20:21:20:188 kernel.log/(8113:8116): Cola READY RR : [1]

[INFO] 20:21:20:189 kernel.log/(8113:8117): El algoritmo de planificacion elegido es RR 

[INFO] 20:21:20:190 kernel.log/(8113:8117): Inicio la planificación RR

[INFO] 20:21:20:190 kernel.log/(8113:8117): PID[1] sale de READY por planificación RR
[INFO] 20:21:20:192 kernel.log/(8113:8116): PID[2] sale de NEW para planificacion 

[INFO] 20:21:20:192 kernel.log/(8113:8116): PID: 2 - Estado Anterior: New - Estado Actual Ready

[INFO] 20:21:20:192 kernel.log/(8113:8116): Cola READY RR : [2]

[INFO] 20:21:20:192 kernel.log/(8113:8116): PID[3] sale de NEW para planificacion 

[INFO] 20:21:20:192 kernel.log/(8113:8116): PID: 3 - Estado Anterior: New - Estado Actual Ready

[INFO] 20:21:20:192 kernel.log/(8113:8116): Cola READY RR : [2, 3]

[INFO] 20:21:23:593 kernel.log/(8113:8117): PID[1] ha agotado su quantum de RR y se mueve a READY

[INFO] 20:21:23:600 kernel.log/(8113:8117): PID: 2 - Estado Anterior: Ready - Estado Actual Exec

[INFO] 20:21:23:608 kernel.log/(8113:8117): Se envio el PCB 2 a la CPU 

[INFO] 20:21:24:607 kernel.log/(8113:8117): Recibi el PCB 2 de la cpu por motivo de: desalojo

[INFO] 20:21:24:607 kernel.log/(8113:8117): PID: 2 - Estado Anterior: Exec - Estado Actual Ready

[INFO] 20:21:24:607 kernel.log/(8113:8117): El algoritmo de planificacion elegido es RR 

[INFO] 20:21:24:607 kernel.log/(8113:8117): Inicio la planificación RR

[INFO] 20:21:24:607 kernel.log/(8113:8117): PID[3] sale de READY por planificación RR
[INFO] 20:21:27:828 kernel.log/(8113:8117): PID[3] ha agotado su quantum de RR y se mueve a READY

[INFO] 20:21:27:829 kernel.log/(8113:8117): PID: 2 - Estado Anterior: Ready - Estado Actual Exec

[INFO] 20:21:27:829 kernel.log/(8113:8117): Se envio el PCB 2 a la CPU 

[INFO] 20:21:28:831 kernel.log/(8113:8117): Recibi el PCB 2 de la cpu por motivo de: desalojo

[INFO] 20:21:28:831 kernel.log/(8113:8117): PID: 2 - Estado Anterior: Exec - Estado Actual Ready

[INFO] 20:21:28:831 kernel.log/(8113:8117): El algoritmo de planificacion elegido es RR 

[INFO] 20:21:28:831 kernel.log/(8113:8117): Inicio la planificación RR

[INFO] 20:21:28:831 kernel.log/(8113:8117): PID[2] sale de READY por planificación RR
[INFO] 20:21:32:297 kernel.log/(8113:8117): PID[2] ha agotado su quantum de RR y se mueve a READY

### CPU: 
[INFO] 20:20:17:232 cpu.log/(8103:8103): Configuracion de CPU cargada
[INFO] 20:20:17:236 cpu.log/(8103:8103): Archivo de configuracion cargado 

[INFO] 20:20:17:237 cpu.log/(8103:8103): Conexion con memoria realizada 

[INFO] 20:20:17:238 cpu.log/(8103:8103): Handshake enviado a memoria 

[INFO] 20:20:17:239 cpu.log/(8103:8103): Tamanio de pagina 32 para realizar handshake :)
[INFO] 20:20:17:239 cpu.log/(8103:8103): Servidores iniciados en CPU 

[INFO] 20:20:28:007 cpu.log/(8103:8103): Se conectaron los clientes de dispatch e interrupt

[INFO] 20:20:28:008 cpu.log/(8103:8103): Espero recibir paquete
[INFO] 20:21:23:602 cpu.log/(8103:8103): Ya recibi paquete
[INFO] 20:21:23:603 cpu.log/(8103:8103): Recibi un PCB del Kernel :)

[INFO] 20:21:23:598 cpu.log/(8103:8114): Recibi un aviso por interrupt del kernel
[INFO] 20:21:24:606 cpu.log/(8103:8103): PID: 2 - Ejecutando: SET - AX - 1

[INFO] 20:21:24:606 cpu.log/(8103:8103): AX = 1 BX = 0 CX = 0 DX = 0
[INFO] 20:21:24:607 cpu.log/(8103:8103): Recursos Asignados: Recurso - Cantidad: 0
[INFO] 20:21:24:607 cpu.log/(8103:8103): Recursos Asignados: Recurso - Cantidad: 0
[INFO] 20:21:24:607 cpu.log/(8103:8103): Recursos Asignados: Recurso - Cantidad: 0
detectamos interrupcion[INFO] 20:21:24:607 cpu.log/(8103:8103): Devolvi el contexto ejecucion al kernel por motivo de: desalojo 

[INFO] 20:21:24:607 cpu.log/(8103:8103): Espero recibir paquete
[INFO] 20:21:27:829 cpu.log/(8103:8114): Recibi un aviso por interrupt del kernel
[INFO] 20:21:27:829 cpu.log/(8103:8103): Ya recibi paquete
[INFO] 20:21:27:829 cpu.log/(8103:8103): Recibi un PCB del Kernel :)

[INFO] 20:21:28:830 cpu.log/(8103:8103): PID: 2 - Ejecutando: SET - BX - 1

[INFO] 20:21:28:830 cpu.log/(8103:8103): AX = 1 BX = 1 CX = 0 DX = 0
[INFO] 20:21:28:830 cpu.log/(8103:8103): Recursos Asignados: Recurso - Cantidad: 0
[INFO] 20:21:28:830 cpu.log/(8103:8103): Recursos Asignados: Recurso - Cantidad: 0
[INFO] 20:21:28:830 cpu.log/(8103:8103): Recursos Asignados: Recurso - Cantidad: 0
detectamos interrupcion[INFO] 20:21:28:831 cpu.log/(8103:8103): Devolvi el contexto ejecucion al kernel por motivo de: desalojo 

### Observaciones
está arrancando el P1 pero ni siquiera ejecuta 1 instrucción (Set ax 1) y me agarra al P2 y ejecuta la primera instruccion. toma P3 pero está pasando lo mismo que en P1 😭 
> pthread_mutex_lock(&mutex_ready);
        t_pcb *proceso_siguiente = list_remove(dictionary_int_get(diccionario_colas, READY), 0);
        pthread_mutex_unlock(&mutex_ready);
        
>        return proceso_siguiente;

quizas el problema está ahí pero yo como RR estoy desalojando al proceso que tengo seleccionado y tengo que buscar otro para ejecutar. Quizás me estoy haciendo un matete en la cabeza y es más simple de lo que parece
