### ISSUE TITLE
Duda sobre pausa de planificacion durante desbloqueo de proceso

### ISSUE THREAD

**Issue by LautaroRobles** [sisoputnfrba/foro#3239]
En el enunciado dice:

> De la misma forma, los procesos bloqueados van a pausar su transición a la cola de Ready.

Estamos teniendo un problema cuando finalizamos un proceso por la consola.
Si finalizamos un proceso el cual tiene recursos asignados, y de esos recursos hay procesos que estan bloqueados. Los procesos no deberian pasar a ready si la planificacion esta pausada, pero esto provoca que nuestra funcion que libera un proceso se quede trabada y por lo tanto la consola tambien. 
Ya que para lograr esto usamos el mismo semaforo de pausa de planificacion dentro la funcion que pasa los procesos bloqueados por un recurso a ready.

**Comment by iago64** [comment]
Buenas! Cómo va?

Este es el tipo de situaciones son a las que apuntamos que resuelvan a la hora de sincronizar la detención / reanudación de la planificación.
Una forma simple que se me ocurre ahora de resolver esto sería teniendo una lista de transiciones pendientes donde al momento que se reanude la plani puedan aplicar todas las transiciones que tienen pendientes.

Saludos.-

**Comment by LautaroRobles** [comment]
Hola iago como estas?

Habiendo leido tu respuesta, nos dimos cuenta que nos falto aclarar algo mas que no entendimos exactamente del cambio en el enunciado: 

_¿Que deberia ocurrir cuando eliminamos un proceso mientras está pausada la planificación?_

Segun lo que respondiste, pareciera que habria que eliminar el proceso "a medias" y cuando se reaunuda la planificacion se termina de eliminar (liberar sus recursos)?

O........... eliminar un proceso deberia no importarle que esta pausada la planificacion y simplemente liberar recursos normalmente.

Eso es lo que nos agradaria saber para proseguir.

Gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

Es justo un caso complicado el que estas planteando, ya que efectivamente, al eliminar un proceso deberían liberar los recursos que tenia tomados y eventualmente si hay un proceso bloqueado, desbloquearlo.

Dado que es un caso muy borde no nos preocupa tanto el momento "exacto" en el que lo hacen, podrían eliminar el proceso, mandarlo a exit y dejar pendiente de desbloquear los procesos que tuvieran que ser desboleados por la liberación de recursos.

Saludos.-

**Comment by LeandroCarbajales** [comment]
@LautaroRobles 
Quedó resuelta la duda? Se puede cerrar el issue?

**Comment by LautaroRobles** [comment]
Listo, quedo claro
