### ISSUE TITLE
Registros Fase fetch

### ISSUE THREAD

**Issue by pfernandezUTN** [sisoputnfrba/foro#3240]
Hola, tengo una duda sobre la fase fetch del Modulo Cpu. 

El enunciado plantea que hay que ir a buscar a memoria la siguiente instruccion utilizando el IP.  En base a esto yo interpreto que el resultado de esta solicitud a memoria se debe guardar en el registro IR (instruction register). 
Mi duda es, en el IR se almacena tanto la instruccion como los parametros de la misma, o debo utilizar otros registros para los parametros (como el MAR o el MDR)?

**Comment by iago64** [comment]
Buenas! Cómo va?

Para fines prácticos, no hace falta que se generen todos los registros tal cual los ven en arquitectura, con que tengan los definidos en el enunciado y despues puedan manejar el string de la instrucción y sus parámetros que le piden a memoria alcanza.

Saludos.-

**Comment by LeandroCarbajales** [comment]
@pfernandezUTN 
Te sirvió la respuesta? Se puede cerrar el issue?

**Comment by LeandroCarbajales** [comment]
Cierro el issue por inactividad. Cualquier cosa lo pueden volver a abrir :)
