### ISSUE TITLE
Duda page fault

### ISSUE THREAD

**Issue by cserrudo** [sisoputnfrba/foro#3243]
Buenas, tengo dudas con respecto al enunciado:

### 📔 Citas del enunciado/videos

_Comunicación con Kernel, CPU y File System
**Creación de proceso**
El módulo deberá crear las estructuras administrativas necesarias y notificar al módulo FS para que nos asigne un bloque de SWAP para cada página del proceso.
**Finalización de proceso**
Al ser finalizado un proceso, se debe liberar su espacio de memoria y notificar al módulo FS que marque como disponibles las páginas correspondientes al proceso en la partición de SWAP.
**Acceso a tabla de páginas**
El módulo deberá responder el número de marco correspondiente a la página consultada. Para este
caso, si la página correspondiente no se encuentra en memoria se deberá responder con un Page Fault.
**Acceso a espacio de usuario**
El módulo deberá realizar lo siguiente:
● Ante un pedido de lectura, devolver el valor que se encuentra a partir de la dirección física
pedida.
● Ante un pedido de escritura, escribir lo indicado a partir de la dirección física pedida. En caso
satisfactorio se responderá un mensaje de ‘OK’.
Cada petición tendrá un tiempo de espera en milisegundos definido por archivo de configuración.
**Page Fault**
El módulo deberá solicitar al módulo File System la página correspondiente y escribirla en la memoria principal.
En caso de que la memoria principal se encuentre llena, se deberá seleccionar una página víctima utilizando el algoritmo de reemplazo. Si la víctima se encuentra modificada, se deberá previamente escribir en SWAP._

Por lo que entiendo, los clientes de memoria pueden pedirle a esta que cree/finalice un proceso y pueden acceder a la tabla de páginas de un proceso, pero no pueden pedir un "Page Fault" no? Eso se produce cuando quiere acceder a una página que no está en memoria y tiene que cargarla o cuando se quiere cargar una página a un marco y está llena la memoria, solo en esos casos

Gracias! Saludos

**Comment by cserrudo** [comment]
Y tengo otra duda relacionado a eso, los clientes  solo pueden pedir acceso a una pagina por vez, no? o sea, no puedo pedir toda la tabla de paginas de un proceso, y por consecuencia (siguiendo la misma lógica de que si yo pido una y no está, se carga en memoria) solo puedo ir cargando 1 pagina por vez cada vez que el cliente pide (me llegue la flag ACCESO_A_TABLA). Es asi? Gracias

**Comment by MartinSintas** [comment]
Buenas, aprovecho que esta abierto el issue para hacer una consulta acerca del enunciado...
>El módulo deberá solicitar al módulo File System la página correspondiente y escribirla en la memoria principal.
En caso de que la memoria principal se encuentre llena, se deberá seleccionar una página víctima utilizando el algoritmo de reemplazo. Si la víctima se encuentra modificada, se deberá previamente escribir en SWAP.
Básicamente esto me está diciendo que hay un paso de mensajes bidireccional entre Memoria y FS, es así (siguiendo el modelo de la arquitectura del sistema)?

Desde ya muchas gracias.

**Comment by iago64** [comment]
Buenas @MartinSintas! Cómo va?

Si, la comunicación es bidireccional, de hecho, si te fijas, la línea tiene flechas de ambos lados ya que la memoria puede pedirle cosas al FS y el FS puede mandarle cosas a la memoria, por ejemplo, en el caso de F_READ donde el FS le dice a la memoria que guarde el contenido de un bloque en una página determinada.

Saludos.-

**Comment by MartinSintas** [comment]
genial Dami, se aclara la duda, mil gracias.

Saludos

**Comment by cserrudo** [comment]
Buenas! Gracias por responder, me quedó claro todo. Solo tengo una pregunta más que surgió en mi grupo ya que no estábamos seguros con esta parte del enunciado: 

> _Comunicación con Kernel, CPU y File System **Creación de proceso** El módulo deberá crear las estructuras administrativas necesarias y notificar al módulo FS para que nos asigne un bloque de SWAP para cada página del proceso. 

Pensando en el caso de que viene una página pedida y la memoria está vacía, hace falta que lo pidamos en FS el espacio SWAP? ya que no va a usarla porque la memoria al estar vacía, la página puede estar en cualquier marco de ésta. O es que puede estar en SWAP y memoria al mismo tiempo? 

Gracias, saludos.

**Comment by cserrudo** [comment]
> Buenas! Gracias por responder, me quedó claro todo. Solo tengo una pregunta más que surgió en mi grupo ya que no estábamos seguros con esta parte del enunciado:
> 

> 
> Page Fault
>  El módulo deberá solicitar al módulo File System la página correspondiente y escribirla en la memoria principal.
> 

> 
> Pensando en el caso de que viene una página pedida y la memoria está vacía, hace falta que lo pidamos en FS el espacio SWAP? ya que no va a usarla porque la memoria al estar vacía, la página puede estar en cualquier marco de ésta. O es que puede estar en SWAP y memoria al mismo tiempo?
> 
> Gracias, saludos.

**Comment by LeandroCarbajales** [comment]
Buenas!
El proceso cuando se crea debería estar completamente en SWAP ya que vamos por un esquema de paginación a demanda puro, es decir, tenemos siempre todo en SWAP y vamos copiando a memoria a medida que se pide.
En este sentido, respondo cada punto:
1- 

> O sea, cuando se inicia un proceso se crea la tabla de paginas x proceso, y cada pagina deberia estar en SWAP?

Exactamente! Sin embargo, hay una simplificación en este TP sobre esto, por la cual no se van a mandar bloques de SWAP al iniciar un proceso, que está en este mismo apartado del enunciado del FS, cito:

> Peticiones del módulo Memoria
Iniciar Proceso
El módulo Memoria solicitará que se reserve una cantidad de bloques de SWAP, como respuesta el módulo File System enviará el listado de los bloques reservados al proceso.
Al momento de reservar un bloque, el mismo deberá rellenarse con '\0', el algoritmo y las estructuras necesarias para la gestión de estos bloques serán definidas por el grupo.

Es decir, todos los procesos iniciarán con sus páginas/bloques rellenas con '\0', por supuesto no sería el caso en un sistema real.

2-

> En el caso de que en kernel mande un page fault a memoria o sea cargar una pagina de SWAP a MP, puede ocurrir el caso de que esta pagina no se encuentre en SWAP o es un caso que no tengo que contemplar?

Buena pregunta! Si nos apegamos a la teoría, el Kernel primero debería chequear que esa página no se exceda del tamaño del proceso cuando atiende un Page Fault, de lo contrario debería finalizar al proceso. Sin embargo, esto mismo no está contemplado en el enunciado del módulo Kernel, vamos a revisarlo si es que se nos escapó o si simplemente no se va a probar.

Saludos!
      Lean

**Comment by cserrudo** [comment]
Buenisimo Lean! Quedó todo claro, muchas gracias.

Saludos.
