### ISSUE TITLE
Duda programacion (Recibo de contexto de ejecucion)

### ISSUE THREAD

**Issue by NKennedy31** [sisoputnfrba/foro#3244]
Hola necesito ayuda con este problema. Me tira seg. fault en   "contexto->pid = leer_entero(buffer, &desplazamiento);" quise debuguear la funcion leer_entero y la ejecuto completa pero cuando retorna el valor  y lo asigna a contexto->pid tira el error. Me podrian ayudar? Muchas gracias.

### 📝 Código relevante

```c
typedef struct{
    int pid;
    int program_counter;
    int prioridad;
    estado_proceso estado;
    motivo_exit motivo_exit;
    motivo_block motivo_block;
    registros_cpu* registrosCpu;
    t_list* instrucciones;
}t_contexto_ejecucion; 

t_contexto_ejecucion* desempaquetar_contexto_ejecucion(t_contexto_ejecucion* contexto, int socket) {
    int size = 0;
    char* buffer;
    int desplazamiento = 0;

    buffer = recibir_buffer(&size, socket);

    contexto->pid = leer_entero(buffer, &desplazamiento);
    contexto->program_counter = leer_entero(buffer, &desplazamiento);
    contexto->prioridad = leer_entero(buffer, &desplazamiento);

    char* auxiliar = leer_string_enum(buffer, &desplazamiento);
    contexto->estado = transformar_string_a_estado(auxiliar);

    char* auxiliar2 = leer_string_enum(buffer, &desplazamiento);
    contexto->motivo_exit = transformar_string_a_motivo_exit(auxiliar2);

    char* auxiliar3 = leer_string_enum(buffer, &desplazamiento);
    contexto->motivo_block = transformar_string_a_motivo_block(auxiliar3);

    contexto->registrosCpu = desempaquetar_registros(buffer, &desplazamiento); // hay que liberar antes de perder la referencia

    free(buffer);

    return contexto; // Agrega esta declaración de retorno
}

int leer_entero(void *buffer, int *desplazamiento) // Lee un entero en base a un buffer y un desplazamiento, ambos se pasan por referencia
{
	int ret;
	memcpy(&ret, buffer + (*desplazamiento), sizeof(int)); // copia dentro de ret lo que tiene el buffer con un size de int
	desplazamiento += sizeof(int);
	//printf("allocating / copying entero %d \n", ret);
	return ret;
}
```

### 🐛 Cómo reproducir el error

Para reproducir el error hay que escribir en consola ./exec, primero en el modulo memoria, luego en cpu y luego en kernel. Una vez en kernel elegimos la opcion 1 y ingresamos instrucciones1 1 1.

**Comment by iago64** [comment]
Buenas! Cómo va?

La forma de "reproducir el error" que nos proporcionas no es posible si no tenemos el código completo, la idea de eso es que nos cuenten que parametros recibe o que valores tiene el código que nos mandan para que podamos verlo.

Dicho lo anterior, cualquier error relacionado a memoria como puede ser que tienen basura en una variable o que algo les tira seg fault siempre, pero siempre, tienen que validarlo primer con valgrind, porque ahi van a tener toda la info necesaria para poder entender el origen del error y de ahi pueden tener una idea de como resolverlo.
Por las dudas dejo el link a la guía / tutorial de Valgrind: https://docs.utnso.com.ar/guias/herramientas/valgrind

Si el output de valgrind se complica mucho, podes subirlo al issue y lo vemos.

Saludos.-

**Comment by iago64** [comment]
@NKennedy31 Cómo va? Pudiste resolver el inconveniente? Necesitas ayuda con los logs de valgrind?

**Comment by NKennedy31** [comment]
Hola si pude, ya cierro el issue
