### ISSUE TITLE
CPUs al 100% con cualquier cosa

### ISSUE THREAD

**Issue by atononi** [sisoputnfrba/foro#3245]
La CPU se va al mango, 100% clavado. Al principio tenía una sola CPU asignada a la VM y notaba que iba lento incluso para abrir el File Manager (30% CPU) y con **solo abrir** el VSCode adiós CPU.
Aumente a 3 CPUs y funcaba bien, pero cuando empecé a debugear dos de las tres CPUs se ponen al 100% y se traba la VM.
Lo que probé:
- Diferentes cantidades de memoria/CPU/video. 4 de ram - 64mb de video - 2 CPU / 7 de ram - 128mb de video - 1 CPU / Etc
- Diferentes versiones del guest. Ubuntu-64 / Lubuntu-64 / Etc
- Desactive aplicaciones que arrancaban con el inicio.
Leí que algunas distribuciones de Linux pueden tener problemas con la frecuencia del Kernel, pero ahí ya no tengo idea.
https://www.virtualbox.org/manual/UserManual.html#ts_linux-guest-high-cpu 
> Some Linux guests may cause a high CPU load even if the guest system appears to be idle. This can be caused by a high timer frequency of the guest kernel. Some Linux distributions, for example Fedora, ship a Linux kernel configured for a timer frequency of 1000Hz. We recommend to recompile the guest kernel and to select a timer frequency of 100Hz.

Recuerdo que con las VMs viejas no tenía problemas utilizando incluso una sola CPU bajo el mismo Host.

### 🔎 Búsqueda en foros

Busque pero no encontré problemas parecidos.

### 📦 Especificaciones de la VM
- Versión de VirtualBox: 7.0
- Memoria RAM asignada: 8GB

- Video: 128mb
- Procesadores: 3 CPUs

### 🖥️ Especificaciones del host
- Sistema Operativo y versión: Windows 11
- Memoria RAM: 16GB
- Procesador: Ryzen 5 5600X

**Comment by atononi** [comment]
Update: Me sucede lo mismo si ejecuto mediante terminal. No es solo problema de los recursos que consume vs code

**Comment by iago64** [comment]
Buenas! Cómo va?

Podrías abrir una terminal y compartirnos una captura del comando `htop` dentro de la VM?

Saludos.-

**Comment by atononi** [comment]
Buenas!
Volviendo a poner solo 1 CPU en la configuración ahora funciona de diez, no sé que tipo de magia habrá ocurrido.
Cierro el issue 👍
