### ISSUE TITLE
Trabajar con mas de un archivo

### ISSUE THREAD

**Issue by GonzaloRDuart** [sisoputnfrba/foro#3246]
Buenas! con mi equipo estamos intentando incorporar mas archivos por modulo dada la complejidad que va sumando el TP. Tengo un problema, a la hora de crear un archivo nuevo si bien se compila y se pueden llamar a las funciones entre los archivos, no logro que compartan variables entre sí. Esto nos sería de utilidad ya que en algunos archivos se definen variables globales que tenemos que pasar por referencia a cada función que utilicemos de los archivos y eso aumenta la posibilidad de que nos equivoquemos al usarlas, lo cual no sería ideal. 

### 🔎 Búsqueda en foros
Vi los videos que estan en este issue:
https://github.com/sisoputnfrba/foro/issues/2291
y creo que nuestro makefile cumple lo necesario pero aún así no se soluciona el problema

### 📝 Código relevante
En cpu, archivo de instrucciones (con el ejemplo de una función):
```
#include "instructions.h"

// Asigna al registro el valor pasado como parámetro.
void _set(char *registro, char* valor, t_contexto_ejecucion *contexto)
{
    *(get_registry(registro, contexto)) = str_to_uint32(valor);
    contexto->codigo_ultima_instru = SET;
}
mas instrucciones...
```

```
#include "cpu.h"
#include "instructions.h"

t_contexto_ejecucion *contexto_actual;

void sighandler(int s)
{
    finalizar_cpu();
    exit(0);
}

int main(int argc, char **argv)
{
mas logica de cpu...
```

Si yo quiero llamar a la variable contexto_actual no puedo. Intente meter el header de cpu (cpu.h) en el archivo instructions.c pero si hago eso devuelve un error:
```
 of `mutex_interrupt'; obj/cpu.o:/home/utnso/Repos/tp-2023-2c-No-me-quemes/cpu/./include/cpu.h:25: first defined here
/usr/bin/ld: obj/instructions.o:/home/utnso/Repos/tp-2023-2c-No-me-quemes/cpu/./include/cpu.h:36: multiple definition of `config_valores_cpu'; obj/cpu.o:/home/utnso/Repos/tp-2023-2c-No-me-quemes/cpu/./include/cpu.h:36: first defined here
y asi para varias lineas...
```
El makefile es el siguiente:
```
PROCESS_NAME=cpu
IDIR =./include
SHARED_IDIR = ../shared/include
CC=gcc
CFLAGS=-I$(IDIR) -I$(SHARED_IDIR) -g -Wall

ODIR=./obj
SRCDIR =./src
LIBS=-lcommons -lpthread -lreadline -lcunit -lrt -lm

SHARED_SRCDIR = ../shared/src
SHARED_ODIR = ../shared/obj

DEPS = $(wildcard $(IDIR)/*.h)

SRC = $(wildcard $(SRCDIR)/*.c)
OBJ = $(patsubst $(SRCDIR)/%.c,$(ODIR)/%.o,$(SRC))

$(ODIR)/%.o: $(SRCDIR)/%.c $(DEPS) $(SHARED_DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

$(SHARED_ODIR)/%.o: $(SHARED_SRCDIR)/%.c $(SHARED_DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

SHARED_DEPS = $(wildcard $(SHARED_IDIR)/*.h)

SHARED_SRC = $(wildcard $(SHARED_SRCDIR)/*.c)
SHARED_OBJ = $(patsubst $(SHARED_SRCDIR)/%.c,$(SHARED_ODIR)/%.o,$(SHARED_SRC))

$(PROCESS_NAME): $(OBJ) $(SHARED_OBJ)
	$(CC) -o $@ $^ $(CFLAGS) $(LIBS)

.PHONY: clean

clean:
	rm -f $(ODIR)/*.o *~ core $(INCDIR)/*~ $(PROCESS_NAME) $(SHARED_ODIR)/*.o 
```

Entiendo que si no tuviera ese error cuando incluyo el archivo cpu.h del podría definir la variable en ese archivo y podría utilizarlo en ambos. En este caso es una sola variable pero en otros casos habría que pasar varias a cada función.

**Comment by RaniAgus** [comment]
¡Buenas! Prueben moviendo la definición de `contexto_actual` al header (o sea, al `cpu.h`) y luego agreguen el siguiente flag al compilar con gcc: `-fcommon`

O sea, la variable `CFLAGS` les quedaría así:
```make
CFLAGS=-I$(IDIR) -I$(SHARED_IDIR) -g -Wall -fcommon
```

Ese flag hace que todas las posibles definiciones variables globales se definan en un lugar común para luego crearlas, entonces si incluyen `cpu.h` en varios lugares ya no debería volver a aparecer el error de "multiple definition of".

Saludos

**Comment by GonzaloRDuart** [comment]
Buenas! Agregue esa flag, me aparece en la consola, pero me sigue tirando el mismo error de múltiple definition :/

**Comment by RaniAgus** [comment]
Qué raro :/

Otra alternativa es _declarar_ todas las variables globales como `extern` en los headers (es decir, reservar el nombre de variable para ese tipo de dato pero sin reservar memoria para ella) y _definirlas_ en el archivo .c correspondiente, o sea...

En cpu.h:
```c
extern t_contexto_ejecucion *contexto_actual;
```

En cpu.c:
```c
t_contexto_ejecucion *contexto_actual; // Si querés inicializarla con un valor, el "=" iría acá
```

Eso te va a permitir incluir cualquier header en cualquier .c ya que si una variable declarada como `extern` se lee dos veces no se va a intentar reservar memoria sino apuntar a la definición que haya en otro archivo.

**Comment by GonzaloRDuart** [comment]
ahí va con eso si pude. Muchas gracias!!
