### ISSUE TITLE
Consulta sobre lectura recomendada File System (para el TP)

### ISSUE THREAD

**Issue by Bru-Nicolas-FRBA** [sisoputnfrba/foro#3248]
Buenas noches, estaba viendo el libro "Fundamentos de los sistemas operativos" de la catedra.

Quería consultar que capítulos de este libro podemos leer para entender mejor específicamente el FS.

Por mi parte intuyo que son del 9 a 12, pero doy fe re erratas.

Muchas gracias por el tiempo y disculpen la molestia.

**Comment by LeandroCarbajales** [comment]
Buenas!
Más allá de conceptos de FileSystems en general que pueden encontrar en esos capítulos, prestaría particular atención al capítulo 11 donde se ve el funcionamiento de la estructura FAT en un esquema de asignación enlazada ya que lo pedido es una versión simplificada de esto mismo.

**Comment by Bru-Nicolas-FRBA** [comment]
Muchas gracias
