### ISSUE TITLE
Duda Crear Archivo FS

### ISSUE THREAD

**Issue by MartinSintas** [sisoputnfrba/foro#3251]
Buenas, tenía una consulta media pava sobre la creación de archivos, más que nada el bloque_inicial.

### 📔 Citas del enunciado/videos
> Crear Archivo
En la operación crear archivo, se deberá crear un archivo FCB con tamaño 0 y sin bloque inicial.
Siempre será posible crear un archivo y por lo tanto esta operación deberá devolver OK.
### 💭 Soluciones posibles
Mi consulta es... cuando creo el archivo nuevo le paso un valor de bloque_inicial tipo NULL? o directamente cuando creo el archivo con el nombre y tamaño ignoro completamente al bloque_inicial¿ 

opción con NULL:
config_set_value (archivo_nuevo, "NOMBRE_ARCHIVO", nombre);
config_set_value (archivo_nuevo, "TAMANIO_ARCHIVO", "0");
config_set_value (archivo_nuevo, "BLOQUE INICIAL", NULL);
	
opción sin NULL: 
config_set_value (archivo_nuevo, "NOMBRE_ARCHIVO", nombre);
config_set_value (archivo_nuevo, "TAMANIO_ARCHIVO", "0");

Desde ya mil gracias 😸

**Comment by iago64** [comment]
Buenas! Cómo va?

Pueden elegir cualquiera de las 2 opciones, a fines prácticos es lo mismo ya que la idea es que no le asignen un bloque, con lo cual mientras lo puedan administrar uds esta perfecto.

Saludos.-

**Comment by MartinSintas** [comment]
Buenísimo Dami, cierro el issue
