### ISSUE TITLE
Conexiones bidireccionales

### ISSUE THREAD

**Issue by NKennedy31** [sisoputnfrba/foro#3252]
Buenas, con mi grupo tenemos una duda acerca de conexiones entre modulos. Nosotros tenemos las conexiones creadas entre los modulos pero tenemos un problema y es que, por ejemplo, en este caso en el modulo de memoria queremos enviar a cpu un mensaje con el fd = cliente socket para realizar el hanshake pero cpu no lo estaria recibiendo entonces la conexion no parece ser bidireccional. Nos podrian ayudar? Dejo el codigo implementado al procesar las conexiones que van llegando.

```c
static void procesar_conexion(void *void_args) {
    int *args = (int*) void_args;
    int cliente_socket = *args;

    op_code cop;
    while (cliente_socket != -1) {
        if (recv(cliente_socket, &cop, sizeof(op_code), 0) != sizeof(op_code)) {
            log_info(logger, "El cliente se desconecto de %s server", server_name);
            return;
        }
        switch (cop) {
            case HANDSHAKE_CPU:
                recibir_mensaje(logger,cliente_socket);
                enviar_mensaje_con_op_code(HANDSHAKE_MEMORIA, "Handshake memoria - cpu ok", cliente_socket);
                break;
}

void enviar_mensaje_con_op_code(op_code opCode, char* mensaje, int socket_cliente){
    t_paquete* paquete = malloc(sizeof(t_paquete));

    paquete->codigo_operacion = opCode;
    paquete->buffer = malloc(sizeof(t_buffer));
    paquete->buffer->size = strlen(mensaje) + 1;
    paquete->buffer->stream = malloc(paquete->buffer->size);
    memcpy(paquete->buffer->stream, mensaje, paquete->buffer->size);

    int bytes = paquete->buffer->size + 2*sizeof(int);

    void* a_enviar = serializar_paquete(paquete, bytes);

    send(socket_cliente, a_enviar, bytes, 0);

    free(a_enviar);
    eliminar_paquete(paquete);
}
```

**Comment by iago64** [comment]
Buenas! Cómo va?

Algo bastante interesante de las conexiones es que de entrada, todas son bidireccionales, es decir, no importa quien haga el connect y el accept, después `send()` y `recv()` se pueden hacer de los 2 lados.
Ahora si la idea de uds es armar una comunicación redundante, es decir, tener 2 conexiones abiertas entre 2 procesos, lo que pueden hacer fácilmente es hacer 2 o mas `connect()` y 2 `accept()` y uds definir que proceso va a estar a la espera de nuevos mensajes en cada conexión.

Saludos.-

**Comment by NKennedy31** [comment]
Buenas!!

La idea que queremos implementar es la de mandar la instruccion de memoria a cpu, sin embargo nos falta el fd por lo tanto no sabemos si cuando cpu le envia el Program Counter a memoria enviarle tambien el fd_cpu o si utilizar el cliente_socket en procesar_conexion por parte de memoria. En este segundo caso, cpu no estaria recibiendo la instruccion y no sabemos cual es el problema.

**Comment by iago64** [comment]
Buenas! 

Para entender un poco mejor el contexto, uds quieren mandar la instrucción de Memoria a CPU sin que CPU la pida? Si es asi, estan yendo en contra de lo que dice el enunciado, ya que en la etapa de Fetch del ciclo de instrucción es cuando la CPU **le pide a memoria** que le mande la instrucción.

Si ahora el problema que tienen es que la CPU les pide la instrucción y les falla el send de la instrucción el problema puede venir de la mano de que no estan mandando bien las cosas, o estan esperando recibir mas de lo que realmente estan mandando o simplemente de alguno de los lados estan cerrando la conexión cosa que al menos en el código que pegaste no lo estaría viendo.

Saludos.-

**Comment by NKennedy31** [comment]
El problema que tenemos es que la CPU pide la instrucción y falla el send de la instrucción. Dejo un poco mas de codigo.

Desde CPU:
En main:
    fd_memoria = crear_conexion(ip_memoria, puerto_memoria);
    enviar_mensaje("Hola, soy CPU!", fd_memoria);

    log_info(logger, "SE GENERARON CORRECTAMENTE LAS CONEXIONES");

    // Inicio de servidor
    fd_cpu_dispatch = iniciar_servidor(logger, IP, puerto_escucha_dispatch);
    while(server_escuchar());

int server_escuchar() {
    server_name = "Cpu";
    int cliente_socket = esperar_cliente(logger, server_name, fd_cpu_dispatch);

    if (cliente_socket != -1) {
        pthread_t hilo;
        int *args = malloc(sizeof(int));
        args = &cliente_socket;
        pthread_create(&hilo, NULL, (void*) procesar_conexion, (void*) args);
        pthread_detach(hilo);
        return 1;
    }

    return 0;
}

static void procesar_conexion(void *void_args) {
    int *args = (int*) void_args;
    int cliente_socket = *args;

    op_code cop;
    cop = recibir_operacion(cliente_socket);
    while (cliente_socket != -1) {
        if (cop == -1) {
            log_info(logger, "El cliente se desconecto de %s server", &server_name);
            return;
        }
        switch (cop) {
            case MENSAJE:
                recibir_mensaje(logger, cliente_socket);
                break;
            case INSTRUCCION_MEMORIA:
                log_info(logger, "ENTRO INSTRUCCION_MEMORIA");
                t_list* instruccion_recibida = recibir_paquete(socket_cliente);
                instruccion_global = instruccion_recibida;
                sem_post(&decode_ciclo);
                break;
}

Desde memoria:
En main:
    // Inicio servidor
    fd_memoria = iniciar_servidor(logger, IP, PUERTO);
    while(server_escuchar);

int server_escuchar() {
    server_name = "Memoria";
    int cliente_socket = esperar_cliente(logger, server_name, fd_memoria);

    if (cliente_socket != -1) {
        pthread_t hilo;
        int *args = malloc(sizeof(int));
        args = &cliente_socket;
        pthread_create(&hilo, NULL, (void*) procesar_conexion, (void*) args);
        pthread_detach(hilo);
        return 1;
    }

    return 0;
}

static void procesar_conexion(void *void_args) {
    int *args = (int*) void_args;
    int cliente_socket = *args;

    op_code cop;
    while (cliente_socket != -1) {
        if (recv(cliente_socket, &cop, sizeof(op_code), 0) != sizeof(op_code)) {
            log_info(logger, "El cliente se desconecto de %s server", server_name);
            return;
        }
        switch (cop) {
            case MENSAJE:
                recibir_mensaje(logger, cliente_socket);
                break;
            case SOLICITUD_INSTRUCCION_CPU:
                sem_wait(&instrucciones_listas);
                //ESPERAR RETARDO: ARCHIVO DE CONFIG (RETARDO_RESPUESTA)
                sleep(retardo_respuesta/1000);
                int program_counter = recv_program_counter_cpu(cliente_socket);
                t_instruccion* instruccion = buscar_instruccion(program_counter, logger);
                t_paquete* paquete_instruccion = crear_paquete(INSTRUCCION_MEMORIA);
                agregar_a_paquete(paquete_instruccion, &(instruccion->instruccion), sizeof(cod_instruccion));
                agregar_a_paquete(paquete_instruccion, instruccion->parametro1, strlen(instruccion->parametro1) + 1);
		        agregar_a_paquete(paquete_instruccion, instruccion->parametro2, strlen(instruccion->parametro2) + 1);
                enviar_paquete(paquete_instruccion, cliente_socket);
}

DEJO FUNCIONES QUE USAMOS PARA SOCKETS
int iniciar_servidor(t_log* logger, char* ip, char* puerto)
{
    int socket_servidor;

    struct addrinfo hints, *servinfo;

    memset(&hints, 0, sizeof(hints));
    hints.ai_family = AF_UNSPEC;
    hints.ai_socktype = SOCK_STREAM;
    hints.ai_flags = AI_PASSIVE;

    getaddrinfo(ip, puerto, &hints, &servinfo);

    // Creamos el socket de escucha del servidor

    socket_servidor = socket(servinfo->ai_family, servinfo->ai_socktype, servinfo->ai_protocol);

    // Asociamos el socket a un puerto

    bind(socket_servidor, servinfo->ai_addr, servinfo->ai_addrlen);

    // Escuchamos las conexiones entrantes

    listen(socket_servidor, SOMAXCONN);

    log_info(logger, "Listo para escuchar a mi cliente");

    freeaddrinfo(servinfo);

    return socket_servidor;
}

int esperar_cliente(t_log* logger, const char* name, int socket_servidor) {
    struct sockaddr_in dir_cliente;
    socklen_t tam_direccion = sizeof(struct sockaddr_in);

    int socket_cliente = accept(socket_servidor, (void*) &dir_cliente, &tam_direccion);

    log_info(logger, "Cliente conectado a %s", name);

    return socket_cliente;
}

int crear_conexion(char *ip, char* puerto)
{
	struct addrinfo hints;
	struct addrinfo *server_info;

	memset(&hints, 0, sizeof(hints));
	hints.ai_family = AF_UNSPEC;
	hints.ai_socktype = SOCK_STREAM;
	hints.ai_flags = AI_PASSIVE;

	getaddrinfo(ip, puerto, &hints, &server_info);

	// Ahora vamos a crear el socket.
	int socket_cliente = socket(server_info->ai_family, server_info->ai_socktype, server_info->ai_protocol);

	// Ahora que tenemos el socket, vamos a conectarlo
	if (connect(socket_cliente, server_info->ai_addr, server_info->ai_addrlen) == -1) {
		socket_cliente = -1;
	}

	freeaddrinfo(server_info);

	return socket_cliente;
}

**Comment by RaniAgus** [comment]
¡Buenas! 

1.  Cuidado que acá:
```c
 int *args = malloc(sizeof(int));
 args = &cliente_socket;
```
Primero están reservando memoria con `malloc()` y guardando un puntero a ella en la variable `args`, para luego **pisar** el valor de ese puntero con la dirección en donde se encuentra la variable `cliente_socket`, por lo que el hilo que crean más adelante está recibiendo un puntero al stack del hilo padre.

La forma correcta de asignar el contenido al que apunta un puntero es desreferenciándolo con `*`:
```c
 int *args = malloc(sizeof(int));
 *args = cliente_socket;
```

El [debugger](https://docs.utnso.com.ar/guias/herramientas/debugger) es una herramienta que les puede servir para monitorear el estado de las variables y corroborar de forma sencilla que un valor que esperaban que esté ahí siga estando.


2. Les recomiendo chequear los valores de retorno de `getaddrinfo()`, `bind()`, `listen()`, `socket()`, `connect()`, `send()`, `recv()`, etc, ya que puede ser que el programa continúe ejecutando con un socket inválido y termine fallando más adelante a causa de un error anterior que no fue manejado.

Pueden revisar cuál es el valor de retorno que deben chequear según cada función consultando el [manual online](https://man7.org/linux/man-pages/) o abriendo una consola y ejecutando `man nombre_de_funcion`. Ejemplos:

#### `getaddrinfo()`

![image](https://user-images.githubusercontent.com/39303639/229563535-4989e9be-1d81-4295-93d4-cb9ac3b6059d.png)
![image](https://user-images.githubusercontent.com/39303639/229563605-ab90c7c9-42c7-45d8-8b4d-59341da70f1b.png)

```c
int resultado_getaddrinfo = getaddrinfo(...);
if (resultado_getaddrinfo != 0) {
    log_error(logger, "Error en getaddrinfo: %s", gai_strerror(resultado_getaddrinfo));
    exit(-1);
}
```

#### `socket()`

![image](https://user-images.githubusercontent.com/39303639/229563716-b96bede3-7474-4f74-9798-c4e7b04778ca.png)

Luego vamos a la página de `errno` y vemos que...

![image](https://user-images.githubusercontent.com/39303639/229564890-b587911b-9b1c-4deb-a5a2-3b53d7a5d88c.png)

```c
socket_servidor = socket(...);
if (socket_servidor == -1) {
    log_error(logger, "Error en socket: %s", strerror(errno));
    exit(-1);
}
```
