### ISSUE TITLE
Consulta sobre procesos y locks - Tema archivos

### ISSUE THREAD

**Issue by Bru-Nicolas-FRBA** [sisoputnfrba/foro#3253]
Buenas noches.

Tengo dos consultas sobre el bloqueo de procesos y archivos:

1- La primera es la mas corta. Es simplemente saber si en el momento en el que se detecta la instruccion de tipo archivo (FOPEN,FSEEK,FWRITE, etc) debemos bloquear al proceso hasta que se resuelva, y ahi devolverlo al estado de ready.

2- La segunda es respecto a los locks de archivos

![image](https://github.com/sisoputnfrba/foro/assets/82009198/e1554ee4-b829-4e9c-ba5d-864a03da7c0f)

Si el archivo esta bloqueado significa que no podremos hacer ningún tipo de modificación o lectura sobre este, hasta donde tengo entendido.
Lo referenciado en este parrafo significa que debemos hacer una "ejecución aparte" de todas las instrucciones relacionadas a archivos bloqueados por este motivo?

**Comment by iago64** [comment]
Buenas! Cómo va?

Para F_OPEN solo lo tienen que bloquear si no puede tomar el lock de escritura / lectura correspondiente.
Para F_SEEK no tienen que bloquear nada porque es solo actualizar el puntero en la tabla de archivos abiertos
Para F_TRUNCATE, F_READ y F_WRITE si tienen que bloquearse esperando que el FS haga lo que tiene que hacer.

El tema de los locks de los archivos están pensados para que se implementen como read-write locks (Que está en el capitulo 5 del sibers), para resumirlo sería que los locks de escritura / lectura te dicen que vos **podes tener tantos locks de lectura concurrentes como quieras**, es decir, podes tener tantos procesos leyendo el archivo como quieras a la vez, total no pasa nada porque no cambian el contenido del archivo, **pero solo 1 de escritura a la vez** y además si tenes uno de escritura no podes tener ninguno de lectura, porque este lock de escritura va a estar modificando el archivo y puede ser que lo que leas cambie en el medio y no sea consistente.

Saludos.-

**Comment by Bru-Nicolas-FRBA** [comment]
Muchas gracias por la respuesta, un ultimo detalle:

A que se refiere con
"Para F_OPEN solo lo tienen que bloquear si no puede tomar el lock de escritura / lectura correspondiente."

Si se esta escribiendo o leyendo el archivo no podremos abrirlo? O si no encontramos lock de lectura/escritura activos bloqueamos?

**Comment by iago64** [comment]
Buenas!

Voy a dividirlo en escenarios, a ver si puedo ayudar a esclarecer la situación:

F_OPEN de lectura:
1.- No hay ningun proceso que lo haya abierto para lectura -> Lo abre sin problemas y no se bloquea.
2.- Hay otros procesos que tienen abierto y todos lo tienen para lectura -> Abre el archivo y no se bloquea.
3.- Hay otros procesos que tienen abierto el archivo de los cuales hay un grupo que lo tiene para lectura y al menos 1 proceso para escritura -> **se bloquea esperando que termine/n el/los de escritura**

F_OPEN de escritura:
1.- No hay ningun proceso que lo haya abierto -> Lo abre sin problemas y no se bloquea.
2.- Hay procesos que tienen abierto el archivo -> Se bloquea a la espera de que terminen los que estan con el archivo abierto independientemente de si es lectura o escritura.

Saludos.-

**Comment by Bru-Nicolas-FRBA** [comment]
Ahhhh okok.

Se entendió todo y quedo clarísimo, mil gracias.
