### ISSUE TITLE
despues de borrar el proyecto y clonearlo del repositorio no me deja compilar el proyecto en eclipse

### ISSUE THREAD

**Issue by Facundo-Su** [sisoputnfrba/foro#3254]
buenas , habia hecho el tp en una rama y cuando queria mergear las 2 ramas , me genera un comflico, lo que hice fue eliminar todo los  archivo de la rama main , y mergear con la rama secundaria , despues de hacer eso , el proyecto no me deja compilar en eclipse , pero me sigue andando en la consola 
![image](https://github.com/sisoputnfrba/foro/assets/82105260/c8c67925-3d5a-462a-80e4-a18925841d7e)

![image](https://github.com/sisoputnfrba/foro/assets/82105260/409e4eef-d68b-4801-990d-762453e1b87f)

**Comment by iago64** [comment]
Buenas! Cómo va?

Lo que me da la sensación es que eclipse no reconoce el proyecto como un proyecto puntualmente si no como una carpeta con código y ya.

Por las dudas, elimina el proyecto de eclipse (no del disco) y después importalo nuevamente como un "makefile project" y confirmanos si ahi te lo reconoce.

Saludos.-

**Comment by Facundo-Su** [comment]
si , ahi me reconocio el proyecto , muchas gracias
