### ISSUE TITLE
Consulta sobre logs de SWAP IN y SWAP OUT

### ISSUE THREAD

**Issue by LautaroRobles** [sisoputnfrba/foro#3255]
En el enunciado dice que se debe logear

> Lectura de Página de SWAP: “SWAP IN -  PID: \<PID> - Marco: \<MARCO> - Page In: \<PID>-\<NRO_PAGINA>”
> Escritura de Página en SWAP: “SWAP OUT -  PID: \<PID> - Marco: \<MARCO> - Page Out: \<PID>-\<NRO_PAGINA>”

¿Cual PID deberia logearse en la parte de **\<PID>-\<NRO_PAGINA>**?

**Comment by iago64** [comment]
Buenas! Cómo va?

El PID del proceso que esta asociado a la página que estas sacando / insertando en memoria (en el caso del SWAP IN es redundante, pero nos sirve para comparar rápido solo esa parte del log.

Saludos.-

**Comment by LautaroRobles** [comment]
Muchas gracias
