### ISSUE TITLE
Tamaño de página en CPU

### ISSUE THREAD

**Issue by diegohcanetti** [sisoputnfrba/foro#3256]
El tamaño de página también tenemos que obtenerlo de la Memoria?  

### 📔 Citas del enunciado/videos
>Estas traducciones, en los ejercicios prácticos que se ven en clases y se toman en los parciales, normalmente se hacen en binario. Como en el lenguaje C los números enteros se operan independientemente de su base numérica, la operatoria puede desarrollarse de la siguiente forma:
número_página = floor(dirección_lógica / tamaño_página)
desplazamiento = dirección_lógica - número_página * tamaño_página

>Como las tablas de páginas están presentes en el módulo Memoria, para conseguir el número de marco correspondiente a la página se deberá solicitar el mismo a dicho módulo para traducción.

**Comment by LeandroCarbajales** [comment]
Buenas!
Cito al enunciado del módulo CPU.

> Lineamiento e Implementación
Al iniciar, la CPU se deberá conectar al módulo Memoria y realizará un handshake inicial para recibir de la memoria la información relevante que le permita traducir las direcciones lógicas en direcciones físicas, esta información debería incluir al menos el tamaño de página.

Te resuelve la duda?
Saludos!
        Lean

**Comment by diegohcanetti** [comment]
Si justo lo acabo de ver, se me había olvidado :/
Gracias
