### ISSUE TITLE
Decode en CPU

### ISSUE THREAD

**Issue by diegohcanetti** [sisoputnfrba/foro#3257]
No me queda del todo claro que hago una vez que dicierno de las instrucciones que necesitan traducción (MOV_IN/MOV_OUT) pq no hay ningún delay en la CPU y no se especifica bien en el enunciado.

### 📔 Citas del enunciado/videos
>Decode
Esta etapa consiste en interpretar qué instrucción es la que se va a ejecutar y si la misma requiere de una traducción de dirección lógica a dirección física.

### 💭 Soluciones posibles
Vi que se preguntó en #3212, pero no me quedó claro que se hace una vez que se discierne

**Comment by iago64** [comment]
Buenas! Cómo va?

Si el enunciado no especifica que tengan que simular un retardo es porque no tienen que simularlo, ya van a tener el retardo de la memoria para devolverles la instrucción.

Saludos.-

**Comment by diegohcanetti** [comment]
Claro entonces que tiene que hacer el CPU cuando ve que la instrucción necesita traducción?

**Comment by iago64** [comment]
Buenas! Cómo va?

Si requiere ina traducción, realicen la traducción, si no, como van a ejecutar la instrucción?

Saludos.-

**Comment by diegohcanetti** [comment]
Aaaa perfecto, yo entendí que la traducción se hacía desde la ejecución, no desde el Decode. Perfecto, muchas gracias.
