### ISSUE TITLE
Consulta "Abrir archivo" y "Crear archivo"

### ISSUE THREAD

**Issue by Bru-Nicolas-FRBA** [sisoputnfrba/foro#3258]
Buenas tardes, una consulta respecto a abrir/cerrar archivos.

Estoy medio confundido respecto a que manera tiene el FileSystem de saber cuando crear y cuando abrir el archivo.

Cuando al kernel le llega la info de que hay una instruccion "f_open" si o si se refiere a la apertura?
O tambien tenemos que hacer que cuando llegue un "f_open" al kernel, el FileSystem revise si existe (y si no existe, lo crea)? 

![image](https://github.com/sisoputnfrba/foro/assets/82009198/5e08cbf4-a6fa-4a70-a169-f29d779262a0)
![image](https://github.com/sisoputnfrba/foro/assets/82009198/49b96d74-c001-433e-bbca-2aba8cd6be29)

(2 imagenes para quitar el pie de pagina de la consigna)

**Comment by RaniAgus** [comment]
¡Buenas! File System no reconoce una operación `F_OPEN`, sino que (como bien citan ahí) expone en su interfaz una operación para abrir un archivo y otra para crearlo. 

Es decir, lo que necesita el Kernel para hacer el `F_OPEN` es lo siguiente: primero envía una solicitud para abrir el archivo. En caso de que el File System le devuelva que el archivo no existe, el Kernel deberá hacer una segunda solicitud a File System para crearlo y una tercera para volver a intentar abrirlo.


Saludos

**Comment by Bru-Nicolas-FRBA** [comment]
Ahhh muchas gracias.
