### ISSUE TITLE
Consutla truncado de archivo y locks

### ISSUE THREAD

**Issue by Bru-Nicolas-FRBA** [sisoputnfrba/foro#3259]
Buenas tardes, tenia una consulta:

Cuando vamos a truncar un archivo debemos asegurarnos de que este no este lockeado por lectura/escritura?

**Comment by iago64** [comment]
Buenas! Cómo va?

No se preocupen por eso, creo que no esta aclarado pero para truncar tambien vamos a hacer previamente un F_OPEN.

Saludos.-

**Comment by ParedesMicaela** [comment]
Hola buenas! Una consulta sobre esto último, el f_open lo vamos a hacer nosotros o se espera que cuando se haga cualquier función de archivos, se verifique si está abierto y si no está abierto, lo abramos y después volvamos a hacer esa instrucción?

**Comment by LeandroCarbajales** [comment]
@ParedesMicaela No nos llegan las notificaciones de issues cerrados, para estos casos recomiendo abrir un nuevo issue mencionando al original.
Con respecto a la duda, no, como dijo Damián (y como pueden verificar en las pruebas que están publicadas) siempre vamos a hacer un F_OPEN antes de hacer cualquier operación con algún archivo, por lo que no es algo que necesiten chequear.

Saludos!
     Lean

**Comment by ParedesMicaela** [comment]
AA genial! Gracias! Dale la proxima hago eso con el issue 😅😅
