### ISSUE TITLE
Duda sobre Abrir Archivo en el Filesystem

### ISSUE THREAD

**Issue by LautaroRobles** [sisoputnfrba/foro#3262]
Buenas, otra vez!

Notamos que el mensaje al Filesystem de "Abrir Archivo" lo unico que hace es devolvernos el tamaño del archivo o decirnos que no existe.
Pero como el Kernel tiene la tabla de archivos abiertos, él puede validar si el archivo existe o no (ya que no lo encontraria en la tabla) y solamente usaria el mensaje de "Crear Archivo" cuando no existe en la tabla de archivos.

¿Tiene algun otro uso el mensaje de Abrir Archivo?
¿Puede que hayan archivos existentes al iniciar el Filesystem? ¿o viene pelado?

**Comment by iago64** [comment]
Buenas! Cómo va?

Vamos en orden:

1.- Si el Abrir archivo del kernel es solamente para saber si existe o no un archivo.

2.- No es responsabilidad del Kernel saber TODOS los archivos abiertos, pensa que la tabla de archivos abiertos es algo que vos tenes inicialmente vacía y la vas completando a medida que te llegna las peticiones de F_OPEN.

3.- Si, El FS uds lo inician pelado, crean archivos, pero despues si lo bajan y lo vuelven a levantar los archivos tienen que estar ahi, porque la idea de un FS es la persistencia a largo plazo 😉 

Saludos.-

**Comment by LautaroRobles** [comment]
Muchas, gracias!
