### ISSUE TITLE
Lectura bloques.dat

### ISSUE THREAD

**Issue by smarquesgomez** [sisoputnfrba/foro#3263]
Buenas, tenemos una consulta de File System! Fuimos un sábado de consulta y nos dijeron que podíamos abrir el archivo de bloques.dat de esta manera:
```
void levantarArchivoDeBloques(){
    
    int blfd = open(config_file_system.path_bloques);  // bloques file descriptor
    

     bloquesMapeado = mmap(blfd, /* sabemos q faltan parametros*/); 
}
```
Nos pusimos a leer y nos dimos cuenta q mmap tiene muchos parámetros pero no terminamos de entender como funciona. Queríamos bajar el bloques.dat a bloquesMapeado que es un void*.  

Muchas gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Vamos a repasar un poco lo que nos dice el man de `[mmap()](https://man7.org/linux/man-pages/man2/mmap.2.html)`

Arrancamos con el prototipo de la función:

```c
void *mmap(void addr[.length], size_t length, int prot, int flags, int fd, off_t offset);;
```

El primer parámetro `void *addr` es un parametro opcional, ya que nos permite indicarle en que dirección queremos que se mapee nuestro archivo, esto podemos completarlo con `NULL`, esto esta en el man en la siguiente linea:

> If addr is NULL, then the kernel chooses the (page-aligned) address at which to create the mapping

El segundo parámetro `size_t length` es mucho muy importante, y nos dice el tamaño de lo que queremos mapear, en el caso del TP puede ser el tamaño completo del archivo o pueden usar la cuenta de `CANT_BLOQUES * TAM_BLOQUE`

El tercer parámetro `int prot` es un poco mas complicado ya que nos indica el grado de protección de las páginas de memoria, en este caso lo que tienen que ponerle es `PROT_WRITE` que es el enum para decirle a `mmap()` que pueden escribir las páginas.

El cuarto parámetro `int flags` lo que nos indica son varios flags propios de la funcion y que tienen relación en como maneja el kernel el archivo, en este caso como no nos cambia mucho pueden usar `MAP_SHARED` total no van a tener otros procesos accediendo a los archivos.

El quinto parámetro `int fd` es el mas fácil, porque es el File Descriptor que les devuelve la funcion `open()`

Y por último el sexto parámetro les sirve para indicarle a `mmap()` si en lugar de mapear desde el inicio del archivo, lo hacen desde un offset en particular, uds no deberian complicarse tanto y deberían poner 0 y que `mmap()` mapee desde el inicio del archivo.

Espero no haberlos mareado con la descripción de los parametros, cualquier duda o explicación que no se entienda me avisan.
Saludos.-

**Comment by LucianoFoglia** [comment]
Genial Dami, muchas gracias. Mañana lo probamos y si funciona cerramos el issue. Cualquier cosa volvemos a consultar.
gracias, nos vemos.

**Comment by iago64** [comment]
@LucianoFoglia Cómo va? pudieron probar la implementación de `mmap()`?

**Comment by LucianoFoglia** [comment]
Buenas Dami, ya pudimos abrirlo bien! Y terminamos de entender el mmap. Nos rompia al momento de querer escribirlo. Nos faltaba ponerle unos flags al open
```
 int blfd = open(config_file_system.path_bloques, O_RDWR | O_CREAT, S_IRUSR | S_IWUSR);
```
Muchas gracias por todo.

**Comment by RaniAgus** [comment]
¡Buenas @smarquesgomez @LucianoFoglia! Paso a patrullar para avisar (para la próxima) que si la duda ya fue resuelta pueden cerrar el issue 👮🏻‍♂️

Si en un futuro ven que algo no terminó de cuadrar pueden tomarse la libertad de reabrirlo o abrir uno nuevo referenciando éste. 

¡Saludos!
