### ISSUE TITLE
Duda enunciado abrir archivo en fs, respuesta a kernel

### ISSUE THREAD

**Issue by ArgonzMatias** [sisoputnfrba/foro#3264]
### 📔 Citas del enunciado/videos
Peticiones del módulo Kernel
Abrir Archivo
La operación de abrir archivo consistirá en verificar que exista el FCB correspondiente al archivo. 
En caso de que exista deberá devolver el tamaño del archivo.
En caso de que no exista, deberá informar que el archivo no existe.

Para ejecutar estas funciones, el Kernel va a recibir el Contexto de Ejecución de la CPU y la función como motivo. El accionar de cada función va a ser el siguiente:
F_OPEN: Esta función será la encargada de abrir el archivo pasado por parámetro (y crearlo en caso de que no exista). Dado que el Kernel maneja una tabla global de archivos abiertos y una tabla por cada proceso, es posible que se den los siguientes escenarios:
Modo Lectura: Al llegar este pedido se deberá validar si existe un lock de escritura activo
En caso de existir, se debe bloquear el proceso y esperar a que finalice dicha operación.
En caso de no existir pueden darse dos casos:
Que ya exista un lock de lectura en curso, de ser así se debe agregar al proceso como “participante” de dicho lock y el mismo finalizará cuando se ejecuten todos los F_CLOSE de los participantes.
Que no exista un lock de lectura. En este caso, se debe crear dicho lock como único participante.
Modo Escritura: Al llegar este pedido se creará un lock de escritura exclusivo para el proceso. Si ya existe un lock activo se bloqueará el proceso encolando dicho lock.

**Comment by iago64** [comment]
Buenas! Cómo va?

No se si estoy viejo, medio ciego o simplemente no logre entender cual es la consulta puntualmente respecto, ya que solo veo la cita del enunciado.

Por las dudas asumo que tu pregunta es sobre que tiene que contestar el FS al Kernel cuando le llega un F_OPEN, eso esta detallado en el punto de Abrir Archivo del FS (Página 28)

Saludos.-

**Comment by ArgonzMatias** [comment]
Ahre, se me borro la consulta jajaja nose que onda, arriba de las citas del enunciado tenia la pregunta . Rarisimo. Lo vuelvo a poner. Mi Consulta es que hace Kernel cuando recibe si existe el archivo , que dice esto en la seccion de FS: "En caso de que exista deberá devolver el tamaño del archivo." Tipo no me queda claro para que quiero recibir el tamaño del archivo kernel, si es para un logger o si lo tengo que usar para algo ya que no encontre nada que diga en la parte del kernel.

**Comment by iago64** [comment]
Buenas! Cómo va?

Ahora sí, claramente no había chances de que entienda la pregunta por ese lado, el definir que devuelvan el tamaño es para que lo carguen en la tabla de archivos abiertos, después queda en uds si lo guardan o no y si le indican al FS si ante un truncate el FS tiene que ampliar o reducir el archivo desde el Kernel o si delegan todo eso en el FS.
Lo realmente importante del Abrir archivo en el FS es checkear si existe o no.

Saludos.-

**Comment by ArgonzMatias** [comment]
Joya perfecto. Gracias!
