### ISSUE TITLE
Duda direccion fisica y memoria

### ISSUE THREAD

**Issue by cserrudo** [sisoputnfrba/foro#3265]
Buenas! Esto lo había preguntado en el soporte de la semana pasada pero no me terminó de cerrar, cuando memoria necesita de la dirección fisica en las funciones de leer_espacio_usuario(dirFisica) (si el bit de modificado esta en 1, me traigo del marco victima su contenido) y escribir_espacio_usuario(dirFisica,valor) (al escribir el nuevo marco) cuando hay un page fault, esa dirección fisica se saca de CPU? Eso me habían dicho en el soporte de la semana pasada, pero el tema es que lo estuvimos pensando con mi grupo y no tiene mucho sentido porque le tendría que mandar el marco (donde está el marco victima) para que me pase su dirección fisica asi tengo que escribir/leer en ese espacio, el problema ahí esta en que memoria es el que maneja todo el tema de los marcos por eso nos hace ruido esto.

También habíamos pensado en que memoria deberia tener alguna estructura que tenga el numero de marco y la posición en donde se encuentra (dirección fisica) así directamente lo carga y no tengo que andar pidiendole a CPU pero no sé si es está bien. Si la dirección fisica la maneja memoria, podemos hacer como en el cuatri pasado que la dirección fisica empieza en 0 y el offset sería lo que nos devuelve el malloc() de una pagina? (el cuatri pasado era eso pero con los segmentos)

Codigo relacionado:

```
uint32_t leer_espacio_usuario(uint32_t direccion) {
	uint32_t valor;

	pthread_mutex_lock(&mutex_memoria);
	memcpy(&valor, espacio_usuario + direccion, sizeof(uint32_t));
	pthread_mutex_unlock(&mutex_memoria);

	return valor;
}

void escribir_espacio_usuario(uint32_t direccion, uint32_t valor) {
	pthread_mutex_lock(&mutex_memoria);
	memcpy(espacio_usuario + direccion, &valor, sizeof(int));
	pthread_mutex_unlock(&mutex_memoria);

}

void reemplazar_marco_victima(int index){
        ...
	if(pagina->bit_modificado = 1){
		//swappeo, paso de lo que esta en el espacio de usuario (necesito la direccion fisica del marco victima para hacer 
                  esto) a SWAP para que tenga los ultimos cambios antes de borrar ese marco
	}
        ...
}

//FS me manda el VALOR y CPU me manda la DIR debo cargarlo?
escribir_espacio_usuario(dir,valor); 


```

Gracias, saludos.

**Comment by iago64** [comment]
Buenas! Cómo va?

Quien termina pasando la dirección lógica a física siempre es la CPU en el submódulo de la MMU, ahora bien.
Cuando es que la CPU va poder obtener la dirección fisica de una página? Cuando la misma este cargada en memoria, caso contrario, sale por Page Fault el contexto de ejecución sale de la CPU y se va al Kernel, quien atiende este pedido.

Ahora bien, al momento de recibir el Page Fault de la Memoria, la CPU no debería haber actualizado el Program Counter, con lo cual, si el contexto de ejecución es desalojado por un Page Fault, cuando vuelva a ejecutar va a arrancar el ciclo de instrucción en la misma instrucción que antes provocó el PF, pero con la salvedad de que ahora la página va a estar en memoria y por lo tanto cuando la CPU le pida la dirección a la Memoria esta le va a poder devolver la dirección y no un PF.

Saludos.-
