### ISSUE TITLE
Duda hilo Consola

### ISSUE THREAD

**Issue by noemi15** [sisoputnfrba/foro#3266]
Tengo dudas con el tp, en mi caso realice el hilo consola de Kernel , te paso a comentar cómo interpreto el código 
-Se crea el hilo consola
- Se maneja la interacción con semáforos en hilo consola e hilo Kernel para evitar uso innecesario
- Se genera una función para tomar los datos ingresados por teclado, el lee la línea y toma los datos necesarios, por ejemplo ingreso por teclado INICIAR_PROCESO dfe 23 23 y devuelve un resultado, en este caso no se podra enviar varias instrucciones a la vez.

Estaría bien esta implementación?

**Comment by iago64** [comment]
Buenas! Cómo va?

La implementación esta bien a priori, ya que en ningun lado les pedimos que puedan ejecutar varias instrucciones a la vez, en las pruebas a lo mucho van a tener que ir escribiendo una instrucción atras de otra y darle enter para que se ejecute cada una :)

Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas @noemi15 !
Te resolvió la duda la respuesta de @iago64 ?

**Comment by noemi15** [comment]
si, gracias
________________________________

**Comment by LeandroCarbajales** [comment]
Genial, no olviden cerrar el issue si la duda fue resuelta :)
