### ISSUE TITLE
Duda sobre deadlocks de archivos

### ISSUE THREAD

**Issue by LautaroRobles** [sisoputnfrba/foro#3267]
Buenas!

En el enunciado dice
> Frente a acciones donde los procesos lleguen al estado Block (por recursos **o archivos**) se debe realizar una detección automática de deadlock
> [...]
> En dicho mensaje se debe informar cuales son los procesos (PID) que se encuentran en deadlocks, cuales son los recursos **(o archivos)** tomados y cuales son los recursos **(o archivos)** requeridos (por los que fueron bloqueados).

Tenemos la duda de como deberiamos tratar un deadlock con archivos y recursos.
¿Podrían mezclarse o deberiamos detectar deadlocks por separado (uno para recursos y otro de archivos)? ¿En tal caso como deberia ser el log de deteccion de deadlocks de archivos?

**Comment by iago64** [comment]
Buenas! Cómo va?

No se compliquen, no vamos a hacer pruebas así porque no definimos un comportamiento para eso en el enunciado.

Saludos.-

**Comment by LautaroRobles** [comment]
Buenas

No me quedo claro, ¿podría ocurrir deadlock de procesos solo por locks de archvios? ¿tenemos que detectar eso?

**Comment by iago64** [comment]
Buenas!

No, no vamos a testear eso, solo nos importa que nos digan que archivos están afectados porque el proceso tiene tomado un lock y no lo puede liberar porque esta en deadlock.

Saludos.-

**Comment by LautaroRobles** [comment]
No lo van a testear, ¿pero tenemos que detectarlo?

**Comment by iago64** [comment]
No, **solamente detecten los deadlocks por los recursos**, los archivos es a modo informativo.

**Comment by LautaroRobles** [comment]
Para estar seguro, en el log de deadlock ¿donde deberiamos agregar los archivos abiertos?

> Deadlock detectado: <PID> - Recursos en posesión <RECURSO_1>, <RECURSO_2>, <RECURSO_N> - Recurso requerido: <RECURSO_REQUERIDO>

¿Deberian estar incluidos junto a los recursos en posesión? o ¿Deberia ir en una linea al final?

**Comment by LeandroCarbajales** [comment]
Como prefieran, mientras se puede diferenciar cuáles son recursos y cuáles son archivos va a estar bien.

**Comment by LeandroCarbajales** [comment]
Cierro el issue porque asumo que la duda está resuelta, cualquier cosa lo vuelven a abrir :)
