### ISSUE TITLE
Como empezar el file

### ISSUE THREAD

**Issue by GregorioOndjian** [sisoputnfrba/foro#3268]
Buenass, con un compañero de grupo estamos encargados de empezar a hacer el FS, el tema es que no estamos entendiendo mucho como empezar: En la consigna nos dice que deben haber 2 particiones en un mismo archivo, una SWAP(que no se que es) y la otra FAT.
Por un lado no comprendemos el tema del archivo binario del FAT, como lo representamos/creamos y que debería tener. 
Por el otro para que usaríamos los archivos ".fcb" en este caso pudimos avanzar con algunas peticiones.
Y por ultimo no entendemos cuando en la consigna dice que el archivo de bloques (que no se que es tampoco) esta compuesto por SWAP y FAT.
Desde ya muchas gracias, y perdón por tantas preguntas.

**Comment by LeandroCarbajales** [comment]
Buenas!
Paso a responder por partes:

>  Por un lado no comprendemos el tema del archivo binario del FAT, como lo representamos/creamos y que debería tener.

La idea es que implementen la misma tabla FAT que se ve en clase, por lo que debería tener lo mismo que se ve en clase como especifica el enunciado.
`La File Allocation Table será un archivo binario que contendrá una entrada por cada bloque de la partición FAT...`
`Cada entrada será representada por un dato de tipo uint32_t...`
A efectos de implementación puede ser un array de uint32_t, un t_list*, o lo que prefieran.
Luego, para persistirla en un archivo real (o para leerla si ya existe), pueden usar las funciones estándar de manejo de archivos de C como fopen(), ftruncate(), fread(), fwrite(), etc.

>  Por el otro para que usaríamos los archivos ".fcb" en este caso pudimos avanzar con algunas peticiones.

Misma idea que un FCB que vemos en clase aunque simplificado, la idea es tener una estructura FCB por cada "archivo" que se quiera crear para los "procesos" que planifica el TP. Luego, estos FCB hay que persistirlos cada uno en un archivo real.

> Y por ultimo no entendemos cuando en la consigna dice que el archivo de bloques (que no se que es tampoco) esta compuesto por SWAP y FAT.

El archivo de bloques vendría a representar el "disco" de nuestro TP. Una parte (la partición FAT) de este "disco" se usaría para guardar el contenido de los archivos que cree este FS. La otra parte (SWAP) se usaría justamente para el swapeo de páginas hacia/desde el módulo Memoria similar a como funciona la paginación bajo demanda (Memoria Virtual) que vemos en clase.
Misma idea que para el resto de estructuras de este módulo, esta información la pueden implementar como un t_list*, un array, etc. pero debe estar persistida en un archivo real.

Te aclara un poco las dudas?

Saludos!
       Lean

**Comment by iago64** [comment]
Buenas! @GregorioOndjian te quedo alguna duda después de la respuesta de lean? Podemos ayudarte con algo mas?

**Comment by GregorioOndjian** [comment]
Buenas, nos quedo bastante más claro, vamos a intentar empezar y cualquier duda les decimos. Muchas graciass

**Comment by LeandroCarbajales** [comment]
Buenísimo :)
Cierro el issue si no hay más dudas inmediatas, cualquier cosa pueden abrir nuevos :)
