### ISSUE TITLE
Duda de Estructura de Tabla de Página

### ISSUE THREAD

**Issue by diegohcanetti** [sisoputnfrba/foro#3269]
No estamos muy seguros de como armar la tabla de páginas ya que nos está costando el hecho de asociarlo al proceso_en_memoria + la búsqueda de la página asociada al marco.  Deberíamos hacer una estructura más "simple"? Deberíamos tomar en cuenta otras variables importantes? Al inicializar la tabla, deberíamos poner el bit_de_presencia en 1?

### 📝 Código relevante
```
typedef struct {
    int numero_de_pagina;
    int marco; 
    int bit_de_presencia; 
    int bit_modificado; 
    int posicion_swap; 
} entrada_t_pagina;

typedef struct {
    entrada_t_pagina* entradas;
    int cant_paginas;                 
} t_pagina;
```

**Comment by iago64** [comment]
Buenas! Cómo va?

Justo estas son las preguntas que la respuesta es tan simple como: _Resuelvanlo de la forma que les sea mas práctica_.

Repasando algunas implementaciones que pueden tener son:
Un struct que tenga absolutamente toda la info, incluido el PID y que cualquier iteración que hagan sea sobre esa lista y tengan que filtrar por PID.
Una lista de listas donde la lista padre sea una "tabla" de procesos y las listas hijas sean las tablas de páginas de cada proceso.

La realidad es que puede depender de a quien le pregunten la respuesta que obtengan ya que hay gente que prefiere las listas de listas, otros prefieren una lista con toda la info e ir obteniendo las sublistas.
Tengan en cuenta que lo que buscamos es que implementen y entiendan segmentación, pero eso no los tiene que limitar a lo que ven solo en la teoría, si no que pueden tomar decisiones de "ampliar" las estructuras y que después sea una charla de coloquio que nos cuenten por que agregaron esos campos o como pensaron el algoritmo.

Saludos.-

**Comment by diegohcanetti** [comment]
Muy buena respuesta jeje, gracias dami
