### ISSUE TITLE
INICIAR_PROCESO (Memoria a Filesystem)

### ISSUE THREAD

**Issue by MartinSintas** [sisoputnfrba/foro#3270]
Buenas, mi duda va referida a si debemos tener en cuenta/implementar el caso en el que la cantidad de bloques a reservados no puedan ser reservados por fragmentación externa (el tamaño de bloques que tengo que reservar es mucho mayor que el tamaño o mejor dicho espacio de bloques disponibles)

### 📔 Citas del enunciado/videos
>Iniciar Proceso
El módulo Memoria solicitará que se reserve una cantidad de bloques de SWAP, como respuesta el módulo File System enviará el listado de los bloques reservados al proceso.
Al momento de reservar un bloque, el mismo deberá rellenarse con '\0', el algoritmo y las estructuras necesarias para la gestión de estos bloques serán definidas por el grupo.

Saludos y muchas gracias por la ayuda (como siempre : D )

**Comment by iago64** [comment]
Buenas! Cómo va?

¿En qué parte del enunciado dijimos que las páginas en swap tenían que estar contiguas? 
Y ya que estamos, metemos un repaso para el parcial... ¿Que nos dice la fragmentación externa? ¿Se da en este caso donde no estamos obligados a tener todo contiguo?

Saludos.-
