### ISSUE TITLE
Consulta modos apertura

### ISSUE THREAD

**Issue by Bru-Nicolas-FRBA** [sisoputnfrba/foro#3272]
Buenas tardes, cuando nosotros abrimos un archivo en modo escritura (con su correspondiente lock)

Vamos a tener que escribir en el archivo algo? O solamente lo abrimos en modo escritura para activar el lock

**Comment by iago64** [comment]
Buenas! Cómo va?

En principio no, solamente van a escribir sobre los bloques del archivos en el momento que hagan el llamado a F_WRITE.

Saludos.-

**Comment by Bru-Nicolas-FRBA** [comment]
Muchas gracias
