### ISSUE TITLE
Consulta Accesos a Memoria

### ISSUE THREAD

**Issue by FrancoGiachetta27** [sisoputnfrba/foro#3273]
Buenas tardes, 
Cuando, al momento de leer/escribir, memoria recibe una dirección real inválida ¿qué deberíamos hacer en esos casos?

**Comment by iago64** [comment]
Buenas! Cómo va?

No deberían poder llegar peticiones con direcciones inválidas, ya que las direcciones se calculan en la MMU de la CPU.

Saludos.-

**Comment by FrancoGiachetta27** [comment]
Perfecto, muchas gracias!
