### ISSUE TITLE
Comunicacion Kernel FS

### ISSUE THREAD

**Issue by Mimito164** [sisoputnfrba/foro#3275]
Tenemos una duda con una parte del enunciado, en particular es sobre la comunicación entre Kernel y FS. Como FS va a resolver las tareas de manera concurrente una vez las vaya resolviendo va a ir mandando mensajes. En el enunciado habla sobre la implementación de esto:

> Para su implementación, deberá ser un proceso multihilo capaz de atender todas las peticiones de manera concurrente, a tales efectos, se recomienda implementar cada petición como una conexión nueva.

Lo que me hace ruido es la parte donde dice `se recomienda implementar cada petición como una conexión nueva.`
No entiendo si pretenden que hagamos una nueva conexión con un socket nuevo o si simplemente manejemos todas las peticiones de manera aislada con hilos.

### 💭 Soluciones posibles

En tal caso podríamos crear hilos para cada tarea que tenga que resolver FS y le asignamos un ID que puede ser el PID del proceso que solicita la tarea y a la hora de responderla, el kernel sabe a que proceso corresponde el mensaje.

**Comment by iago64** [comment]
Buenas! Cómo va?

La idea es que creen un nuevo socket para cada petición que le hagan al FS y que las mismas las manejen con hilos independientes del lado del FS, ya que si tienen una sola conexión, no van a poder por ejemplo estar recibiendo nuevas peticiones a la vez de que están esperando contestar / contestando una petición anterior.

Saludos.-

**Comment by Mimito164** [comment]
Perfecto gracias.
