### ISSUE TITLE
Bloqueo de los procesos en el Filesystem

### ISSUE THREAD

**Issue by diegohcanetti** [sisoputnfrba/foro#3276]
En el TP, una vez que la CPU devuelve el contexto de ejecución con una operación de archivo lo mandamos directamente el proceso a bloqueado y lo mandamos a un hilo llamado atender_peticiones_fs con el proceso asociado. El tema es que releyendo el enunciado no nos queda del todo claro si tenemos que bloquear el proceso apenas reciba la operación de archivo o más adelante cuando se empieze a atender esta petición.

**Comment by iago64** [comment]
Buenas! Cómo va?

El bloqueo va a depender de la operación que estén haciendo. Para un F_CLOSE o un F_SEEK no deberían bloquear el proceso. Para el resto de los casos está bien que lo bloqueen ni bien llega la operación ya que si no lo bloquean que harían?

Saludos.-

**Comment by diegohcanetti** [comment]
Perfecto muchas gracias
