### ISSUE TITLE
Consulta uso POPEN para busqueda de archivos

### ISSUE THREAD

**Issue by Bru-Nicolas-FRBA** [sisoputnfrba/foro#3277]
Buenos días, tenia una consulta (que sorpresa...)_

Estoy intentando hacer un código para buscar un archivo (por el nombre, según indica la consigna hasta donde tengo entendido) y me encontré con la función POPEN

Respecto a la función, por lo que leí, sirve para poder listar buscar archivos

      **FILE *dir = popen("ls -1", "r");**
      **//busco el archivo**
      **pclose(dir);**
 
Por ejemplo esto de acá me abre una tubería para poder buscarlo.

Mi consulta es esta, respecto de la definición se aclara algo importante:

_popen es útil cuando deseas ejecutar comandos del sistema y capturar su salida en tu programa C. Sin embargo, debes tener cuidado al utilizar popen, ya que implica la ejecución de comandos externos y puede tener implicaciones de seguridad. Asegúrate de que los comandos que ejecutas sean seguros y que la entrada proporcionada sea validada adecuadamente para evitar vulnerabilidades de seguridad_

La utilización de esta función supone algún problema? Capaz podemos usar otra que sea mas segura, o hay alguna recomendación que se me escapó

**Comment by LeandroCarbajales** [comment]
Buenas!
No deberían tener ningún problema usando `popen()` dado que es un entorno aislado.

Otra opción podría ser levantar a una lista todos los archivos .fcb al iniciar el módulo FS y luego directamente buscarlos en esa lista cuando se quiere abrir.
Para listar todos los archivos de un directorio pueden usar algo como [scandir()](https://man7.org/linux/man-pages/man3/scandir.3.html)

**Comment by Bru-Nicolas-FRBA** [comment]
Muchas gracias 😊
