### ISSUE TITLE
Consulta lectura archivos binarios

### ISSUE THREAD

**Issue by Bru-Nicolas-FRBA** [sisoputnfrba/foro#3278]
Buenas tardes, una consulta sobre la lectura de archivos binarios:

![image](https://github.com/sisoputnfrba/foro/assets/82009198/d326cedd-b267-4ecb-96db-dbd7bcda8b95)

Es obligatorio este pie ge pagina? Porque la lectura hasta donde tengo entendido se puede realizar mediante fread, por lo menos la de la tabla fat. Para lo cual supongo podemos trasladar a el archivo de bloques

**Comment by LeandroCarbajales** [comment]
Buenas!
Se refiere a cómo leer el archivo desde la terminal. Desde código por supuesto que pueden usar fread().

Te resuelve la duda?
Saludos!
     Lean

**Comment by Bru-Nicolas-FRBA** [comment]
Ahh entonces desde el código usamos fread, perfecto.

Pero desde la terminal hexdump o xxd??
O simplemente con el fread y llevar los datos para mostrarlo sirve?

**Comment by LeandroCarbajales** [comment]
La idea de usar hexdump o xxd es para poder leer el archivo cuando el TP no está corriendo. Por ejemplo, correr primero una prueba con FS, luego bajar todo y fijarse desde la terminal cómo quedó el archivo.

**Comment by Bru-Nicolas-FRBA** [comment]
Ahhh entonces deberíamos preparar un comando aparte con hexdump o xxd para las pruebas?

Y en tal caso solo debería estar enfocado a ver el contenido del archivo?

**Comment by LeandroCarbajales** [comment]
No tienen que preparar nada al respecto, sirve para en cualquier momento corroborar el contenido del archivo. Les puede servir incluso para debuggear si es muy engorroso printear por pantalla todo el archivo durante la ejecución.

**Comment by Bru-Nicolas-FRBA** [comment]
Excelente, muchas gracias lean
