### ISSUE TITLE
Creacion de procesos - memoria

### ISSUE THREAD

**Issue by NKennedy31** [sisoputnfrba/foro#3279]
Buenas tengo una duda acerca de si el size que se pasa en la consola es el size del proceso o del archivo de pseudocodigo. Se que se aclara en otra parte del enunciado que por consola se pasa el path del archivo de pseudocodigo y el size que ocupara el mismo pero tengo la duda porque no tengo bien en claro que funcion vendria a cumplir este size.

### 📔 Citas del enunciado/videos

Ante la solicitud de la consola de crear un nuevo proceso el Kernel deberá informarle a la memoria que debe crear un proceso con el nombre del archivo de pseudocódigo junto con el tamaño en bytes que ocupará el mismo.

**Comment by LeandroCarbajales** [comment]
Buenas!
Se refiere al tamaño del proceso, no del archivo. Este tamaño le puede servir a la Memoria para administrar mejor su tabla de páginas por ejemplo.

Te aclara la duda?
Saludos!
      Lean

**Comment by NKennedy31** [comment]
Buenas, sisi perfecto muchas gracias!!
