### ISSUE TITLE
Duda asignación de bloque

### ISSUE THREAD

**Issue by MartinSintas** [sisoputnfrba/foro#3280]
#3251 
Buenas, estaba releyendo el enunciado del tp porque hay una parte que no me termina de quedar clara. En qué momento a nuestro archivo le asignamos un bloque_inicial en la FAT?

### 📔 Citas del enunciado/videos
>Iniciar Proceso
El módulo Memoria solicitará que se reserve una cantidad de bloques de SWAP, como respuesta el módulo File System enviará el listado de los bloques reservados al proceso.
Al momento de reservar un bloque, el mismo deberá rellenarse con '\0', el algoritmo y las estructuras necesarias para la gestión de estos bloques serán definidas por el grupo.

### 💭 Soluciones posibles
Por lo que entiendo ahí es que al iniciar el proceso me va a reservar los bloques que reserva pero en SWAP, esto quiere decir que en algún momento se pasan a la FAT? 
No me termina de quedar claro :/

Desde ya muchas gracias

**Comment by LeandroCarbajales** [comment]
Buenas!
Son completamente independientes los procesos de los archivos, por lo que al iniciar un proceso lo único que se asignarían serían bloques de SWAP (donde no hay archivos).
Se le van a asignar bloques (de la partición FAT) a un archivo cuando el mismo ocupe ese tamaño (es decir, sea truncado). Por ejemplo, un archivo de tamaño 0 (recién creado) no necesita tener ningún bloque asignado. Si luego trunco el archivo a algún tamaño mayor a 0 mínimamente necesitaré asignarle un bloque (o los que necesite para ese tamaño).

Te aclara las dudas?
Saludos!
      Lean

**Comment by MartinSintas** [comment]
Aaaahhh, buenísimo Lean, se aclaran las dudas. Muchas gracias :D
