### ISSUE TITLE
Consulta tamaño de bloque

### ISSUE THREAD

**Issue by Bru-Nicolas-FRBA** [sisoputnfrba/foro#3281]
Hola, una consulta respecto del tamanio de los bloques del fs

Dentro del archivo de configuracion de ejemplo tenemos un tamanio de 32, lo que se refiere a un uint32_t, por lo tanto al crear los bloques tenemos esto (medio resumido):

for (size_t i = 0; i < tamanio_fat / sizeof(uint32_t)); i++)
{
     fwrite(&valor_inicial, sizeof(uint32_t)), 1, archivo_fat);
}

Pero si nos diesen otro tamanio, por ejemplo 8 o 12, deberiamos hacer esto? O siempre va a ser 32?

for (size_t i = 0; i < tamanio_fat / sizeof(TAMANIO_DEL_ARCHIVO_DE_CONFIGURACION)); i++)
{
     fwrite(&valor_inicial, sizeof(TAMANIO_DEL_ARCHIVO_DE_CONFIGURACION)), 1, archivo_fat);
}

**Comment by LeandroCarbajales** [comment]
Buenas!
El tamaño de bloque está definido en bytes (al igual que el tamaño de página), por lo que un tamaño de 32 no se refiere a un uint32_t (que pesa 32 bits, es decir, 4 bytes), en todo caso entrarían 8 de estos números en cada bloque de 32 bytes.
El tamaño no va a ser siempre 32, de hecho es configurable, pero no vamos a probar tamaños de bloque menores a 4 bytes ya que tampoco tendría mucho sentido teórico.

Te aclara la duda?
Saludos!
       Lean

**Comment by Bru-Nicolas-FRBA** [comment]
Sii, se entendio perfecto

Me ayudo tambien leer la consigna otra vez. Tenia la duda de si teniamos que acceder varias veces al bloque cuando escribiamos para terminar de llenarlo

![image](https://github.com/sisoputnfrba/foro/assets/82009198/d5edcd51-9e6e-459b-9db9-e32b1da6732d)

Pero según entiendo acá, cada vez que hagamos F_WRITE siempre va a ser de todo el bloque, por lo tanto si hacemos:

F_WRITE ARCHIVO X // un numero
F_WRITE ARCHIVO Y // un numero distinto

Sera en los dos bloques distintos y no en el mismo. (O comprendi mal la consigna?)

**Comment by LeandroCarbajales** [comment]
Podría ser el mismo bloque tranquilamente, capaz sea otro lugar de memoria desde el que tomes la información a escribir. Pero es correcto que cada F_WRITE en este caso corresponde a un solo acceso a bloque.

Viendo también el código de tu pregunta inicial, no veo correcto hacer un fwrite cada "sizeof(uint32_t)" ni de ningun otro sizeof, podés escribir directamente una cantidad <tamaño_bloque> de bytes.

**Comment by Bru-Nicolas-FRBA** [comment]
Muchas gracias

**Comment by Bru-Nicolas-FRBA** [comment]
Perdon, creo que me exprese mal en como me hice la pregunta.

A lo que me queria referir es si en las pruebas van a ser siempre de escribir un bloque completamente (ocupando todo el espacio)?

O puede pasar el caso en el que den dos ``` F_WRITE ``` para escribir y debamos escribir en el mismo bloque (porque, a proposito, con el 1er ``` F_WRITE ``` no logramos "llenar" todo el bloque)

**Comment by LeandroCarbajales** [comment]
Nono, como dice la nota, la idea es que siempre escriban el bloque completo, de hecho no les estamos pasando un tamaño a escribir :P
