### ISSUE TITLE
Ayuda, no me muestra los errores al momento de codear en visual

### ISSUE THREAD

**Issue by Bru-Nicolas-FRBA** [sisoputnfrba/foro#3282]
Hola... Ayuda porfavor

![image](https://github.com/sisoputnfrba/foro/assets/82009198/b5102f5e-df3e-40f3-bf72-e3eeb41bf3ac)

Tengo este problema hace dos dias y me esta impidiendo que VSCODE me muestre los errores, intente solucionarlo con el Enable Error Squiggle

Hace unos dias tambien me instale LIVESHARE para intentar codear con un amigo, pero no se si eso es lo que puede estar dando este problema. O si?

**Comment by RaniAgus** [comment]
¡Buenas! Al parecer el error tiene muchas posibles causas según https://github.com/microsoft/vscode-cpptools/issues/9684#issuecomment-1455998834 🫤

¿Podrías pasarnos el contenido de todos los archivos de configuración de code? Son todos los que están en la carpeta `.vscode` y, en caso de haber uno, el archivo del workspace.

👮🏻 Side note 👮🏻: Como mencionamos en el [readme del foro](https://github.com/sisoputnfrba/foro/blob/master/README.md), desaconsejamos el uso de capturas de pantalla ya que a quienes quieran usar el buscador les va a ser más difícil encontrar el issue con el texto `command-line error: language modes specified are incompatible`

¡Saludos!

**Comment by Bru-Nicolas-FRBA** [comment]
Hola!

La carpeta .vscode me desaparecio del tp, la intente crear pero no me deja

![image](https://github.com/sisoputnfrba/foro/assets/82009198/eced556a-72ea-46b5-883a-6328deaf4acd)

Me creo sola esta carpeta, que no tiene nada adentro y no se que es 

![image](https://github.com/sisoputnfrba/foro/assets/82009198/e9e7d386-c362-42bf-b7f1-239f15a605df)

Cuando intento crear la carpeta manualmente adentro del tp me aparece esto, el unico archivo workspace que tengo es el que aparece de fondo en esa imagen... Pero ni siquiera me deja abrirlo en el visual para ver lo que tiene adentro

**Comment by Bru-Nicolas-FRBA** [comment]
Hice por las dudas (y por quincuajesuma vez) un clone y me creo mas archivos en el vs-code/cpptools

![image](https://github.com/sisoputnfrba/foro/assets/82009198/c6f20af0-6536-4e9d-b716-cb84d29553fa)

![image](https://github.com/sisoputnfrba/foro/assets/82009198/45e20d27-d781-4b65-a09f-ad57298985e4)

![image](https://github.com/sisoputnfrba/foro/assets/82009198/09bfd79e-cdfd-411f-b407-c188a2936a9a)

Voy a ser completamente honesto... No se de donde salió todo esto (ni como pudo hacer esto git clone), es la primera vez que tengo un error que al hacer un clone me crea un archivo fuera de la carpeta que clono

**Comment by Bru-Nicolas-FRBA** [comment]
Este fue el **resultado de ls -la**

![image](https://github.com/sisoputnfrba/foro/assets/82009198/3dc5c0a0-79ae-4d6d-9a5e-f08be6dc63be)

Los contenidos de .vscode son los mismos launch/settings/tasks

![image](https://github.com/sisoputnfrba/foro/assets/82009198/eaea194b-51ac-4931-b4bb-5c95cca671e7)

contenido de **launch.json**

![image](https://github.com/sisoputnfrba/foro/assets/82009198/4f501e6b-16a8-46ad-aa99-a2ec8209b5de)


contenido de **settings.json**

![image](https://github.com/sisoputnfrba/foro/assets/82009198/ef6b22e0-ba8c-468c-a02f-ca730d4e5fea)


contenido de **tasks.json**

![image](https://github.com/sisoputnfrba/foro/assets/82009198/5dd8b6a5-7c97-408d-8b37-30725d1969e9)

**Comment by RaniAgus** [comment]
A ver el archivo .code-workspace

Y repito, porfa, no suban capturas de pantalla, otra de las ventajas mencionadas en el readme es que puedo copiar y pegar lo que me muestren e intentar reproducir el error.

**Comment by Bru-Nicolas-FRBA** [comment]
Perdón por la captura, se me paso.

```
{
        "settings": {
                "debug.onTaskErrors": "abort",
                "files.associations": {
                        "*.h": "c",
                        "cmath": "c"
                },
                "C_Cpp.errorSquiggles": "disabled",
        },

        "folders": [
                {
                        "path": "cpu"
                },
                {
                        "path": "filesystem"
                },
                {
                        "path": "kernel"
                },
                {
                        "path": "memoria"
                },
                {
                        "path": "shared"
                }
        ]
}
```
Este es el workspace

Paso tambien lo que tiene adentro los archivos en modo de codigo?

**Comment by RaniAgus** [comment]
> Paso tambien lo que tiene adentro los archivos en modo de codigo?
Tranqui, no hace falta

Podemos probar borrando la carpeta .vscode que está en la raíz del repo e importando el TP usando File > Add folder to workspace... (seleccionando el archivo code-workspace que tienen allí).

**Comment by Bru-Nicolas-FRBA** [comment]
Pude borrar la carpeta  ```.vscode```

Una vez que intento seleccionar el archivo code-workspace no me deja.

(Estoy tentado a mandar una captura de pantalla de como se ve en un gris claro el texto, pero me voy a abstener)

**Comment by RaniAgus** [comment]
Perdón, me expresé mal, lo que puedas copiar en texto siempre es mejor pero si estás en una GUI medio que no queda otra que mandar screenshot 😅 

Igual me estoy dando cuenta que me confundí de opción, es `Open Workspace from File...`, mala mía :P

**Comment by Bru-Nicolas-FRBA** [comment]
Jesucristo santo bendito... Tenia un  ```.vscode``` oculto afuera en el escritorio principal.

Lo elimine, clone devuelta y me retornó a la normalidad. POR FIN

Muchisimas gracias por la ayuda
