### ISSUE TITLE
Duda sobre logs de abir archivo en el Filesystem

### ISSUE THREAD

**Issue by LautaroRobles** [sisoputnfrba/foro#3283]
Buenas! 
En el enunciado dice que el filesystem deberia logear:
> Apertura de Archivo: “Abrir Archivo: <NOMBRE_ARCHIVO>”

Y tenemos una duda con este caso:
- 5 procesos van a abrir el mismo archivo en modo lectura.

¿Deberian haber 5 logs de Abrir Archivo o deberia haber solo 1?. 

Esto lo preguntamos porque el Kernel tiene la tabla global de archivos abiertos. Cuando el primer proceso abre el archivo, el Kernel agrega la entrada a la tabla de archivos abiertos y enviamos una solicitud al Filesystem para que abra el archivo y en su defecto lo cree, despues los demas procesos tambien abren el archivo pero no se agregan mas entradas, solo se aumenta el valor del contador de aperturas pero no se vuelve a solicitar abrir el archivo al Filesystem.

**Comment by LeandroCarbajales** [comment]
Buenas!
Si al módulo FileSystem no le llega la petición de abrir el archivo no tiene por qué loggearlo :), en ese caso Kernel lo loggearía 5 veces y FS solo una vez.

**Comment by LeandroCarbajales** [comment]
Cierro el issue porque asumo que la duda está resuelta, cualquier cosa lo vuelven a abrir :)
