### ISSUE TITLE
Se puede truncar archivos abiertos en modo Read?

### ISSUE THREAD

**Issue by LautaroRobles** [sisoputnfrba/foro#3284]
Buenas!

Tenemos una duda sobre que si tenemos que impedir que un proceso trunque un archivo cuando lo abrio en modo READ.
Ya que por ejemplo, podriamos tener varios procesos que abrieron un mismo archivo en modo READ y cada uno lo trunca y lee, lo cual podria romperse.

¿Este caso sucedera en las pruebas?

**Comment by LeandroCarbajales** [comment]
No necesitan impedir que ocurra este caso. Siempre vamos a probar punteros y direcciones válidas para los F_READ y F_WRITE, por lo que no se va a dar el caso de que un proceso trunque un archivo y luego otro quiera leer o escribir una posición del archivo que ya no existe.

**Comment by LeandroCarbajales** [comment]
Cierro el issue porque asumo que la duda está resuelta, cualquier cosa lo vuelven a abrir :)
