### ISSUE TITLE
Consulta archivo.fat

### ISSUE THREAD

**Issue by Bru-Nicolas-FRBA** [sisoputnfrba/foro#3285]
Buenos dias, les hago una consulta:

Respecto al archivo fat, que va a tener guardado toda la tabla fat actualizada.

Tenemos estructura que representa una entrada de la tabla FAT

```c
typedef struct {
    char* nombre_archivo; //esto puede ser que no usemos, pero para algunas cosas plantea ser mas comodo
    int numero_bloque;
    uint32_t* direccion_bloque;
    uint32_t* puntero_siguiente_bloque;
} t_fat; //entrada de tabla fat
``` 

Al momento de guardar en el archivo ```t_fat``` estamos haciendo:

``` 
fwrite(&entrada_fat, sizeof(t_fat), 1, archivo_fat);
``` 

Pero desconzco si al ser un tipo estructura puede generar problemas con el tamaño de guardado.

Quizas convendria hacer esto? Para que el tamaño sea acorde a un entero

``` 
fwrite(&entrada_fat, sizeof(uint32_t), 1, archivo_fat);
```

**Comment by iago64** [comment]
Buenas! Cómo va?

Como esa en la página [28 del enunciado](https://docs.google.com/document/d/1g6DEcbjilpX2XUBADuF6dPnrLv5lzoTZSVYCPgpHM_Q/edit#heading=h.8twoqzlfmory):

> Cada entrada será representada por un dato de tipo uint32_t, es decir que el tamaño en bytes del archivo FAT será (CANT_BLOQUES_TOTAL - CANT_BLOQUES_SWAP) * sizeof(uint32_t)

Con lo cual, ese struct que están armando, no estaría correcto para implementar la tabla FAT, recuerden que la tabla FAT no es mas que un **array de números** donde el numero indica el siguiente bloque, si es el EOF (`UINT32_MAX`) o si esta libre (`0`)

Saludos.-

**Comment by Bru-Nicolas-FRBA** [comment]
Muchas gracias por la corrección profe

**Comment by Bru-Nicolas-FRBA** [comment]
Buenos dias, perdon por volver a abrir el issue pero me surgió otra consulta sobre que sea un **array de numeros**

Si solo guardamos el ```puntero al siguiente bloque```, ```EOF``` y ```si esta libre o no```. La ```informacion del bloque``` que vayamos a leer/escribir donde quedaria guardada? En el **archivo de bloques** ?

**Comment by iago64** [comment]
Buenas!

Con la tabla FAT uds van pudiendo recorrer el archivo, ahora para obtener la data van a tener que ir al archivo de bloques.

Saludos.-

**Comment by Bru-Nicolas-FRBA** [comment]
Mucahs gracias otra vez <3
