### ISSUE TITLE
Consulta Tamaño de procesos

### ISSUE THREAD

**Issue by LucianoFoglia** [sisoputnfrba/foro#3286]
Buenas, que tal? 
Nos surgio una duda. Existe la posibilidad de que un proceso "pida" mas paginas de las que puede tener? Teniendo en cuenta el tamaño del proceso que se le pasa a kernel al momento de iniciar un proceso. 
En caso de que asi sea, como deberia ser? Kernel solo manda solicitudes validas a memoria o es memoria la que le dice a kernel luego de un page fault que ya no puede asignarle paginas a ese proceso? Tendriamos que matar el proceso o como seria?
Desde ya, muchas gracias.

**Comment by iago64** [comment]
Buenas! Cómo va?

No vamos a hacer esa prueba.

Saludos.-

**Comment by LucianoFoglia** [comment]
Buenisimo, muchas gracias.
Saludos.
