### ISSUE TITLE
El programa a veces funciona, a veces no

### ISSUE THREAD

**Issue by MartoSimon** [sisoputnfrba/foro#3287]
Buenos dias, estamos teniendo problemas con la ejecución de las instrucciones de la cpu en el kernel. Ya las tenemos hechas hace un tiempo, pero ahora sin motivo alguno nos dejaron de funcionar. Cuando corremos el programa por primera vez en la VM nos funciona todo perfecto, pero cuando lo queremos correr devuelta nos empieza a fallar, el kernel recibe mal los datos y entonces se rompe. Puede ser que le queden como "restos" en la memoria de la VM y entonces se nos rompa todo?
No adjunto codigo porque me parece que es bastante y capaz es algo más teórico que otra cosa, si necesitan que les adjunte algo porfavor avísenme.
Lo que si adjunto son los logs de la primera vez (donde funciona) y de la segunda y tercera vez (donde no funcionan), aunque las instrucciones y configs son iguales. Los separo con -----

Saludos!

### 💻 Logs
```
[INFO] 20:16:34:453 KERNEL/(9925:9934): envie el pcb
[INFO] 20:16:34:453 KERNEL/(9925:9934): PID: 0
[INFO] 20:16:34:453 KERNEL/(9925:9934): AX: 0
[INFO] 20:16:34:453 KERNEL/(9925:9934): BX: 0
[INFO] 20:16:34:453 KERNEL/(9925:9934): CX: 0
[INFO] 20:16:34:453 KERNEL/(9925:9934): DX: 0
[INFO] 20:16:34:453 KERNEL/(9925:9934): DX: 0
[INFO] 20:16:34:453 KERNEL/(9925:9934): PCB MANDADA
[INFO] 20:16:38:537 KERNEL/(9925:9937): recibi instrucciones  0
[INFO] 20:16:38:537 KERNEL/(9925:9937): Entre a contexto SLEEP
[INFO] 20:16:38:537 KERNEL/(9925:9937): PID: 0
[INFO] 20:16:38:537 KERNEL/(9925:9937): AX: 1
[INFO] 20:16:38:537 KERNEL/(9925:9937): BX: 1
[INFO] 20:16:38:537 KERNEL/(9925:9937): CX: 1
[INFO] 20:16:38:537 KERNEL/(9925:9937): DX: 0 

[INFO] 20:16:38:537 KERNEL/(9925:9937): Numero: 6
[INFO] 20:16:38:537 KERNEL/(9925:9937): Tiempo: 10
[INFO] 20:16:48:537 KERNEL/(9925:9937): Hice el sleep: 10
[INFO] 20:16:51:543 KERNEL/(9925:9937): recibi instrucciones  11
[INFO] 20:16:51:543 KERNEL/(9925:9937): Entre a contexto EXIT
[INFO] 20:16:51:543 KERNEL/(9925:9937): PID: 0
[INFO] 20:16:51:543 KERNEL/(9925:9937): AX: -1
[INFO] 20:16:51:543 KERNEL/(9925:9937): BX: 1
[INFO] 20:16:51:543 KERNEL/(9925:9937): CX: 1
[INFO] 20:16:51:543 KERNEL/(9925:9937): DX: 0

------------------------------------------------------------------------------------

[INFO] 22:58:45:276 KERNEL/(8928:8938): envie el pcb
[INFO] 22:58:45:276 KERNEL/(8928:8938): PID: 0
[INFO] 22:58:45:276 KERNEL/(8928:8938): AX: 0
[INFO] 22:58:45:276 KERNEL/(8928:8938): BX: 0
[INFO] 22:58:45:276 KERNEL/(8928:8938): CX: 0
[INFO] 22:58:45:276 KERNEL/(8928:8938): DX: 0
[INFO] 22:58:45:276 KERNEL/(8928:8938): DX: 0
[INFO] 22:58:45:276 KERNEL/(8928:8938): PCB MANDADA
[INFO] 22:58:49:337 KERNEL/(8928:8938): recibi instrucciones  0
[INFO] 22:58:49:340 KERNEL/(8928:8938): Entre a contexto SLEEP
[INFO] 22:58:49:340 KERNEL/(8928:8938): PID: 0
[INFO] 22:58:49:340 KERNEL/(8928:8938): AX: 1
[INFO] 22:58:49:340 KERNEL/(8928:8938): BX: 1
[INFO] 22:58:49:340 KERNEL/(8928:8938): CX: 1
[INFO] 22:58:49:340 KERNEL/(8928:8938): DX: 0 

[INFO] 22:58:49:340 KERNEL/(8928:8938): Numero: 6
[INFO] 22:58:49:340 KERNEL/(8928:8940): CPU devolvio mal 8
[INFO] 22:58:49:341 KERNEL/(8928:8938): Tiempo: 32739

---------------------------------------------------------------------------------------------------

[INFO] 22:53:36:232 KERNEL/(8256:8266): envie el pcb
[INFO] 22:53:36:232 KERNEL/(8256:8266): PID: 0
[INFO] 22:53:36:232 KERNEL/(8256:8266): AX: 0
[INFO] 22:53:36:232 KERNEL/(8256:8266): BX: 0
[INFO] 22:53:36:232 KERNEL/(8256:8266): CX: 0
[INFO] 22:53:36:232 KERNEL/(8256:8266): DX: 0
[INFO] 22:53:36:232 KERNEL/(8256:8266): DX: 0
[INFO] 22:53:36:232 KERNEL/(8256:8266): PCB MANDADA
[INFO] 22:53:40:287 KERNEL/(8256:8266): recibi instrucciones  0
[INFO] 22:53:40:287 KERNEL/(8256:8268): CPU devolvio por interrupcion  0
[INFO] 22:53:40:287 KERNEL/(8256:8266): Numero: 0
[INFO] 22:53:40:287 KERNEL/(8256:8268): Entre a contexto interrupcion.
[INFO] 22:53:40:287 KERNEL/(8256:8268): PID: 1
[INFO] 22:53:40:288 KERNEL/(8256:8268): AX: 0
[INFO] 22:53:40:288 KERNEL/(8256:8268): BX: 0
[INFO] 22:53:40:288 KERNEL/(8256:8268): CX: 0
[INFO] 22:53:40:288 KERNEL/(8256:8268): DX: 0
[INFO] 22:53:40:288 KERNEL/(8256:8268): PROGRAM COUNTER: 0
```

**Comment by iago64** [comment]
Buenas! Cómo va?

Dejando de lado cualquier susceptibilidad, duda o esoterismo que pueda venir de la mano de creer que alguna fuerza del mal puede estar actuando desde las sombras en contra de tu tp. Te hago una pregunta simple, en ambos casos, ¿Corriste el TP con valgrind? Porque si nos subís los logs de valgrind, muy muy posiblemente podamos empezar a tener algo de certeza sobre lo que pasa.

Saludos.-

**Comment by MartoSimon** [comment]
Buenas!
Lo corrimos con el valgrind y los unicos errores que nos aparecen son de este estilo (adjunto foto), puede ser que tenga algo que ver con la cantidad de bytes perdidos?
![Screenshot_1](https://github.com/sisoputnfrba/foro/assets/72176653/9682afcb-38c4-4388-bb33-8d6e3e25e91b)
Si necesitan que nos metamos mas adentro de alguno de los errores o si necesitan otra cosa avisenos. 
Saludos!

**Comment by LucaPrestia** [comment]
Buenas!
Ahi lo corrimos con valgrind no entendemos porque después de recibir el numero de instrucción el valor de la operación anterior cambia y porque manejar instrucción se hace como si fuera un hilo y sigue mientras sigue la funcion de ejecución.

Saludos!

![codigo1](https://github.com/sisoputnfrba/foro/assets/102747439/8a8379bc-e947-4f31-965e-1200c4ae8111)
![codigo2](https://github.com/sisoputnfrba/foro/assets/102747439/159acc3f-65cb-4bc2-adb5-d0959ca4e607)
![log](https://github.com/sisoputnfrba/foro/assets/102747439/a7562b73-2ed5-4c95-90bf-9c70b89f4d04)
![valgrind](https://github.com/sisoputnfrba/foro/assets/102747439/e3846188-85e2-4a35-a709-84d39316122d)

**Comment by LucaPrestia** [comment]
Hola, perdón no me sabia las reglas del formato.
Arreglamos el invalid size de recibir numero y nos sigue pasando lo mismo. El unico invalid size que tenemos es uno que viene de las commons de list en esta linea  del hilo del planificador de largo plazo.
`pcb* procesoParaReady = list_remove(new,list_size(new)-1);`
Saludos.

**Comment by iago64** [comment]
Buenas! Cómo va?

Algo divertido e interesante de las commons, es que no tienen por si solas invalid read / invalid write, si no imagínense que tienen más de 10 años y pasaron varios cuatrimestres, seguro alguien hubiera encontrado el problema, así que muy posiblemente ese último invalid read tambien deberían tener que resolverlo para estar tranquilos de que no estan haciendo nada malo con la memoria.

De todas formas, entiendo que tienen diferentes threads en el kernel? Esos threads, los validaron con helgrind? no sea cosa de que tengan una condición de carrera y no se hayan dado cuenta (creanme que a veces cuesta mucho verlas sin helgrind)

Saludos.-

**Comment by LeandroCarbajales** [comment]
Cierro el issue por inactividad, por cualquier cosa pueden crear uno nuevo citando este :)
