### ISSUE TITLE
Config fcb no funcion config_create()

### ISSUE THREAD

**Issue by ArgonzMatias** [sisoputnfrba/foro#3288]
### 📝 Código relevante
```
uint32_t encontrar_bloque_n(char* nombre_archivo, uint32_t bloque_puntero){
    char* newPath = crearPathAlFCB(nombre_archivo);
    t_config* fcb_config= config_create(newPath);   //<-- falla aca
    uint32_t bloque_aux = config_get_int_value(fcb_config, "BLOQUE_INICIAL");
    for(int i=0; i<bloque_puntero;i++){
        memcpy(&bloque_aux, mapeo_tabla_fat + (bloque_aux*sizeof(uint32_t)),sizeof(uint32_t));
    }
    config_destroy(fcb_config);
    return bloque_aux;
}
```
adjunto screenshot de como quedan las variables en las commons del config. 
![WhatsApp Image 2023-11-18 at 8 16 42 AM](https://github.com/sisoputnfrba/foro/assets/62978820/e972978b-80e5-4f5e-aa41-9b0ceb03d8a3)

-->

**Comment by ArgonzMatias** [comment]
bueno claramente estoy haciendo los issues mal pq se me borra todo jajaja perdon. Explico la situacion. 
Cuando ejecuta f_read, me falla config_create(newPath); cuando ya anteriormente me crea el archivo, cuando lo abre y cuando lo trunca ejecuta la misma sentencia de codigo sin problema y en cada instancia lo cierra despues de su uso. Puede ser que sea por un fallo en la memoria? O alguna otra idea?

Las instrucciones que se ejecutan son estas:
SET AX 1
SET BX 1
SUM AX BX
SUB AX BX
MOV_IN DX 0
MOV_OUT 0 CX
SLEEP 10
JNZ AX 4
WAIT RECURSO_1
SIGNAL RECURSO_1
F_OPEN ARCHIVO W
F_TRUNCATE ARCHIVO 64
F_SEEK ARCHIVO 8
F_WRITE ARCHIVO 0
F_READ ARCHIVO 0   <-- falla aca
F_CLOSE ARCHIVO
EXIT

**Comment by iago64** [comment]
Buenas! Cómo va?

Es un segment fault, la primer respuesta automática, asi como cualquier ISP te pregunta si reiniciaste el modem, tiene que ser correr el tp con valgrind y ver que error les marca.
Una vez que tienen identificado el error y el strack asociado al error, ahí pueden empezar a debuguear su código para dar con el error y finalmente encarar una solución.

Saludos.-

P.D: Corran con valgrind y suban el output de valgrind si no lo entienden y les damos una mano en encontrar que les esta fallando.
P.D.2: Los archivos de instrucciones no se vuelvan locos abriendolos y cerrandolos, abranlos a la primera y despues guardense la data en memoria asi se ahorran el abrir y cerrar archivos constantemente 😉

**Comment by ArgonzMatias** [comment]
Buenas, gracias por la rapida respuesta. Con valgrind estuve probando y encontre el error y lo pude solucionar. Basicamente cuando lo estabamos truncando, no se estaba guardando el valor bien en el .fcb, (nose pq pero bueno). Ahora ya anda. Gracias!
