### ISSUE TITLE
SWAP: Duda sobre algoritmos para asignacion de bloques

### ISSUE THREAD

**Issue by GriselSanchez** [sisoputnfrba/foro#3289]
Hola como andan? Tengo una consulta sobre esta parte del enunciado:

> El módulo Memoria solicitará que se reserve una cantidad de bloques de SWAP, como respuesta el módulo File System enviará el listado de los bloques reservados al proceso.
> Al momento de reservar un bloque, el mismo deberá rellenarse con '\0', el algoritmo y las estructuras necesarias para la gestión de estos bloques serán definidas por el grupo.

Podriamos usar una asignacion de bloques de tipo enlazada, asi podemos reutilizar la logica de FAT? Pero en vez de guardar los ptrs en un archivo FAT, los guardariamos en un array de uint32 por ejemplo.

**Comment by iago64** [comment]
Buenas! Cómo va?

Si a uds les resulta fácil, pueden hacerlo, por algo les dijimos:

> las estructuras necesarias para la gestión de estos bloques serán definidas por el grupo.

Saludos.-
