### ISSUE TITLE
Uso de mmap

### ISSUE THREAD

**Issue by matibrewda** [sisoputnfrba/foro#3290]
Buenas, estaba utilizando la funcion mmap para la tabla fat que tengo cargada de la siguiente manera

```
fat = fopen(configuracion_filesystem->path_fat,"rb");
	if(!fat){
		fat = fopen(configuracion_filesystem->path_fat,"wb");
		if (fat)
		{
			uint32_t tamanio_fat = (configuracion_filesystem->cant_bloques_total - configuracion_filesystem->cant_bloques_swap);
			for (uint32_t i = 0; i < tamanio_fat ; i++)
			{
				fputc(0,fat);
			}
			

		}
```

la pregunta es: para levantar la tabla luego quiero utilizar la funcion `mmap()`, lo que no estoy sabiendo hacer es como utilizar el puntero que me devuelve mmap para acceder a cada entrada de la tabla

**Comment by iago64** [comment]
Buenas! Cómo va?

Primero que nada, para usar `mmap()` tienen que abrir el archivo con `open()` en lugar de `fopen()`.
En segundo lugar, lo que les devuelve mmap() es un puntero a memoria, entonces lo que tienen que hacer es asumir que tienen en memoria el archivo, entonces en la posición 0 tienen el primer valor, 4 bytes despues tienen el segundo valor y asi, recuerden que la tabla tiene numeros en formato uint32_t, con lo cual, ahi lo que estan haciendo de usar `fputc()` esta mal, ya que eso graba un char que ocupa 1 byte, en lugar de los 4 de un uint32_t.

Saludos.-

**Comment by matibrewda** [comment]
Muchas gracias, 
"Primero que nada, para usar mmap() tienen que abrir el archivo con open() en lugar de fopen()."
 Si, el mmap lo hago despues para levantar la tabla, abriendo el archivo con open.
por otro lado, si yo hago *ptr=mmap()
ptr[0] deberia ser la primer posicion, ptr[4] la segunda y asi?

en cuanto el fat lo corregi asi

```
fat = fopen(configuracion_filesystem->path_fat,"rb");
	if(!fat){
		fat = fopen(configuracion_filesystem->path_fat,"wb");
		if (fat)
		{	
			uint32_t a = 0;
			uint32_t tamanio_fat = (configuracion_filesystem->cant_bloques_total - configuracion_filesystem->cant_bloques_swap);
			for (uint32_t i = 0; i < tamanio_fat ; i++)
			{
				fwrite(&a,sizeof(uint32_t),1,fat);
			}
			free(a);

		}
```

**Comment by matibrewda** [comment]
Ok. Muchas gracias!, una consulta mas pero con referencia al enunciado,
> Leer Archivo
Esta operación leerá la información correspondiente al bloque a partir del puntero.
La información se deberá enviar al módulo Memoria para ser escrita a partir de la dirección física recibida por parámetro, una vez recibida la confirmación por parte del módulo Memoria, se informará al módulo Kernel del éxito de la operación.
Escribir Archivo
Se deberá solicitar al módulo Memoria la información que se encuentra a partir de la dirección física recibida y se escribirá en el bloque correspondiente del archivo a partir del puntero recibido.
Nota: El tamaño de la información a leer/escribir de la memoria coincidirá con el tamaño del bloque / página. Siempre se leerá/escribirá un bloque completo, los punteros utilizados siempre serán el 1er byte del bloque o página.

Cuando leemos y escribimos lo hacemos en el bloque que nos da el puntero? no leemos recorriendo los bloques de la tabla FAT?

**Comment by iago64** [comment]
Buenas, cómo va?

No se olviden lo que vieron en la teoría, en los bloques tienen la información, pero la tabla FAT les sirve para saber cual es el siguiente bloque en un archivo. 
Por ejemplo si mi FCB me dice que el bloque inicial es el bloque 4 despues en la tabla FAT pueden darse 2 situaciones:

- Bloque 4 tiene un número de bloque, esto quiere decir que el siguiente bloque de mi archivo es el bloque que me indique la tabla FAT.
- Bloque 4 tiene la marca de EOF, eso quiere decir que es el último bloque del archivo.

Por lo tanto si tuvieran que por ejemplo escribir en el bloque 5 del archivo, tienen que obtener el bloque 0 del FCB y despues ir recorriendo la tabla fat hasta llegar al bloque 5 y de ahi irse con ese número al archivo de bloques y leer / escribir en ese bloque.

Saludos.-

**Comment by matibrewda** [comment]
Ok, entonces si no entiendo mal. El puntero que recibimos nos indica cierto byte del archivo, entonces yo tendria que dividir el puntero por el tamaño del bloque y recorrer la tabla FAT buscando el bloque nro x de mi archivo?

**Comment by iago64** [comment]
Buenas! Cómo va?

Efectivamente, como vieron en la teoría, el puntero lo dividen por el tamaño del bloque y eso les va a dar el bloque al cual tienen que apuntar, que casualmente en las pruebas publicadas si se dan cuenta apunta siempre al primer bytes del bloque para que les sean mas fáciles las cuentas y todo de redondito sin restos de división.

Saludos.-

**Comment by matibrewda** [comment]
buenas, una consulta mas con respecto al `mmap()`
ahora que lo quiero utilizar para el archivo de bloques, que a diferencia del fat los bloques no tienen un tamaño definido sino que varian segun la config que se este usando, 
es correcta la siguiente implementacion para asi moverme por cada bloque?
```
void *bloque = malloc(sizeof(configuracion_filesystem->tam_bloque));
bloque=mmap() //todos los parametros
```

**Comment by matibrewda** [comment]
entiendo, pero quiero luego tener un vector de bloques para poder escribir o leerlos de una manera mas facil. como deberia hacerlo?

**Comment by iago64** [comment]
Buenas! @matibrewda esta resuelta la duda, hay algo mas con lo que te pueda ayudar?
Saludos.-
