### ISSUE TITLE
Cambio de algoritmo de planificacion durante la ejecucion

### ISSUE THREAD

**Issue by LautaroRobles** [sisoputnfrba/foro#3292]
Buenas!

Quisieramos consultarle sobre la Prueba Base que dice:

> Cambiar el algoritmo de planificación a RR y volver a ejecutar. 

Nosotros leemos cual es el algoritmo de planificacion cuando inicializamos el Kernel, si lo cambiamos no podemos obtener cual es el nuevo algoritmo de planificacion.

¿Podemos, cuando pida cambiar la configuracion, detener los modulos y volverlos a iniciar con la nueva configuracion?

**Comment by LeandroCarbajales** [comment]
Buenas!
Es exactamente eso, el algoritmo de planificación no se cambia durante la ejecución. La idea es tirar todo y volver a correr la misma prueba pero con RR para ver la diferencia :)

**Comment by LautaroRobles** [comment]
Muchas Gracias!
