### ISSUE TITLE
Error de declaración de una función.

### ISSUE THREAD

**Issue by GregorioOndjian** [sisoputnfrba/foro#3293]
Buenas, tengo un problema que no se bien porque sale, es un error que no me permite seguir ejecutando el programa.
Esto es en la parte del FS en donde yo quiero hacer una funcion para crear un FCB con distintos parametros. El que genera problemas es el array de la FAT que esta declarado como un uint32_t arrayFAT[]. Cuando lo saco de los parametros, se va el error. 

Ya tuve este mismo error en otros lados por la misma razón, le pregunté a mi profe de SO y lo pudo solucionar, cambiando los parametros de lugar, y haciendo copypaste de la declaracion del .c al .h. Intente hacer esto pero ya no resulta.
### 📝 Código relevante

El error siempre sale en la parte del header.
`void crear_fcb(uint32_t arrayFAT[],char* nombreArchivo, int socket_kernel ,t_log* logger);`
el error que tira es: 
conflicting types for ‘crear_fcb’; have ‘void(uint32_t *, char *, int,  t_log *)’ {aka ‘void(unsigned int *, char *, int,  t_log *)’}

Por otra parte, la funcion esta exactamente igual en el .c:
`void crear_fcb(uint32_t arrayFAT[],char* nombreArchivo, int socket_kernel ,t_log* logger){
`

**Comment by iago64** [comment]
Buenas! Cómo va?

Es posible que tengas definida 2 veces la función crear_fcb en 2 archivos .h distintos?? 

Saludos.-

**Comment by GregorioOndjian** [comment]
Buenass, como va, nono ya me fije y esta solo una vez.

**Comment by iago64** [comment]
Buenas!

Me tome el atrevimiento de revisar el repo, es posible que no este subida la última actualización?

Porque veo que en el archivo `peticiones.h` tienen el siguiente código:

```c
void crear_fcb(char* nombreArchivo, int socket_kernel,t_log* logger);
```

Y en el archivo `filesystem.h` tienen lo siguiente:

```c
void crear_fcb(uint32_t arrayFAT[],char* nombreArchivo, int socket_kernel ,t_log* logger);
```

Y `filesystem.h` incluye a `peticiones.h`, entonces de ahi que puede venir el conflicto al momento de compilarlo.
Saludos.-

**Comment by LeandroCarbajales** [comment]
Para agregar una humilde recomendación, el array de la FAT lo tendría definido como variable global para no tener que pasarlo por parámetro en todas las funciones de manejo de archivos.
Por otro lado, y ya más importante, por qué necesitan pasarse la FAT para crear el FCB?
Por lo que veo del código están haciendo
```c
bloqueInicial = posicionPrimerBloqueLibre(arrayFAT);
```
Sin embargo, un FCB recién creado con tamaño 0 no debería tener ningún bloque asignado (y por lo tanto ningún bloque inicial) como indica el enunciado.

> Crear Archivo
En la operación crear archivo, se deberá crear un archivo FCB con tamaño 0 y sin bloque inicial.
