### ISSUE TITLE
Duda sobre el F_WRITE

### ISSUE THREAD

**Issue by ParedesMicaela** [sisoputnfrba/foro#3295]
Buenas noches, mi duda es sobre la última parte del enunciado donde dice que si el proceso solicita un lock de lectura, lo mandamos a exit. No entiendo muy bien a qué se refiere.  Yo los locks los implemente como 2 variables de tipo bool dentro de la estructura del archivo y aparte estoy usando una cola de solicitudes para cada archivo y una cola de lectura para tener juntos a los procesos que están leyendo. Cuando un proceso hace un f_read o un f_write, le pongo al archivo el lock que corresponde y meto el proceso en la cola que corresponde.  Lo estoy implementando mal? Los locks son algo que los procesos me piden? O se refiere a que si hago un f_write, el modo de apertura con el que abri el archivo debe ser W? 

### 📔 Citas del enunciado/videos
F_WRITE: Esta función, en caso de que el proceso haya solicitado un lock de escritura, solicitará al módulo File System que escriba en el archivo desde la dirección física de memoria recibida por parámetro. El proceso que llamó a F_WRITE, deberá permanecer en estado bloqueado hasta que el módulo File System informe de la finalización de la operación. En caso de que el proceso haya solicitado un lock de lectura, se deberá cancelar la operación y enviar el proceso a EXIT con motivo de INVALID_WRITE.

**Comment by iago64** [comment]
Buenas! Cómo va?

La respuesta esta en la misma pregunta 😄 

> el modo de apertura con el que abri el archivo debe ser W

Si lo abren como R, no deberían poder escribir y por eso un F_WRITE los manda a EXIT.

Saludos.-

**Comment by ParedesMicaela** [comment]
AAA perfecto! Gracias 😅😅
