### ISSUE TITLE
Conexión FS-Memoria

### ISSUE THREAD

**Issue by ValennCoronel** [sisoputnfrba/foro#3296]
Hola, como están? Con nuestro grupo estamos con un inconveniente, actualmente tenemos en FS una función la cual crea un hilo nuevo cada vez que recibe una petición ya sea de Kernel o de Memoria (esto lo implementamos así para que pueda atender todas las peticiones de manera concurrente)
El problema lo encontramos cuando implementamos la función f_read del lado del FS la cual debería enviarle a memoria el contenido leído para que esta lo escriba en la dirección indicada, pero como el pedido viene inicialmente de kernel no contamos con el socket para hacer el envío a memoria. Como podríamos resolver esto para tener ambos sockets disponibles sin dejar de implementar el modulo FS como multihilo?

**Comment by iago64** [comment]
Buenas! Cómo va?

¿No se les ocurrió crear nuevas conexiones a medida que lo necesiten? En ninguna parte del enunciado les dijimos que no lo pueden hacer 😉  

Saludos.-

**Comment by Fcallero** [comment]
Buenas, estoy en el mismo grupo que @ValennCoronel. Con crear nuevas conexiones a que te referis? a crear una nueva conexión aparte solo para FS y memoria? Y si es así, no pasa nada si hay como una condición de carrera en quien de los dos se conecta primero con el otro modulo?

**Comment by iago64** [comment]
Buenas!

Efectivamente, me refería a crear nuevas conexiones, es decir, hacer nuevos `connect()` del lado del FS y hacer nuevos `accept()` del lado de la memoria.

La condición de carrera no se debería dar, ya que estamos hablando de que uds van a ir creando estas conexiones a medida que las necesiten.

Saludos.-

**Comment by ValennCoronel** [comment]
Holaa, si ya quedó resuelta la duda, muchas gracias!
