### ISSUE TITLE
Problema con biblioteca "math.h"

### ISSUE THREAD

**Issue by GregorioOndjian** [sisoputnfrba/foro#3299]
Buenass, estamos teniendo problemas con la biblioteca "math.h" ya que cuando intentamos utilizar alguna de sus funciones el compilador no las reconoce, obviamente las incluimos en casi todos lados, pero no hay forma de que las vea. También lo que probamos fue incluir la biblioteca en los .h que tenemos relacionados al modulo de FS y tampoco funcionó.
Este error nos aparece solo en el  filesystem.c ya que en el kernel y cpu también utilizamos la biblioteca y no genera ningún tipo de problema.
Por otro lado nos aparece un "multiple definition of" de 2 variables globales que son tablaFAT y tablaBloques que las definimos únicamente en un archivo llamado "peticiones.h".

### 💻 Logs

```
/usr/bin/ld: ./src/peticiones.o:/home/utnso/eclipse-workspace/tp-2023-2c--Uwuntu-/filesystem/Debug/../src/peticiones.h:22: multiple definition of `tablaFAT'; ./src/filesystem.o:/home/utnso/eclipse-workspace/tp-2023-2c--Uwuntu-/filesystem/Debug/../src/peticiones.h:22: first defined here
/usr/bin/ld: ./src/peticiones.o:/home/utnso/eclipse-workspace/tp-2023-2c--Uwuntu-/filesystem/Debug/../src/peticiones.h:23: multiple definition of `arrayBloques'; ./src/filesystem.o:/home/utnso/eclipse-workspace/tp-2023-2c--Uwuntu-/filesystem/Debug/../src/peticiones.h:23: first defined here
/usr/bin/ld: ./src/filesystem.o: in function `truncar_archivo':
/home/utnso/eclipse-workspace/tp-2023-2c--Uwuntu-/filesystem/Debug/../src/filesystem.c:334: undefined reference to `ceil'
/usr/bin/ld: /home/utnso/eclipse-workspace/tp-2023-2c--Uwuntu-/filesystem/Debug/../src/filesystem.c:335: undefined reference to `ceil'
/usr/bin/ld: /home/utnso/eclipse-workspace/tp-2023-2c--Uwuntu-/filesystem/Debug/../src/filesystem.c:339: undefined reference to `itoa'
collect2: error: ld returned 1 exit status
```

**Comment by iago64** [comment]
Buenas! Cómo va?

El problema de `math.h` es que les esta faltando seguramente agregarlo como flag de compilación similar a como agregan pthread o las commons, en el caso de math, es simplemente `m`

La parte de multiple definitions ok, por las dudas revisen de no tener definito en el .h la variable y despues en algun lugar definida nuevamente. o de no tener includes recursivos, es decir:
`peticiones.h` incluye a `archivo.h`
`archivo.h` incluye a `utils.h`
`utils.h` incluye a `peticiones.h`

Cuando pasan esas cosas el compilador de C medio que dice: Che esto ya lo tenia definido de antes.

Saludos.-

**Comment by GregorioOndjian** [comment]
Buenismoo, muchas graciass.
