### ISSUE TITLE
Log obligatorio acceso a FAT

### ISSUE THREAD

**Issue by lucasosacuenca** [sisoputnfrba/foro#3301]
Buenas, para la fat yo lo que hago es luego de crearla recorrerla una vez para inicializarla en cero, es necesario en ese caso hacer tanto el log obligatorio de acceso a FAT y el retardo de acceso a FAT?

Tambien en el caso de truncate que tengo que reducir los bloques que utiliza, yo busco el ultimo bloque y ese lo tengo que poner en cero, cuenta como dos accesos el encontrarlo y luego ponerlo en cero, o se interpreta que es en la misma accion?

Muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

Cuando la inicializan la primera vez no hace falta que pongan esos logs.
En el caso del truncate, si importa porque ahi mostrarían que recurren bien la tabla FAT.

Saludos.-
