### ISSUE TITLE
abrir archivo file system

### ISSUE THREAD

**Issue by tolaDiego** [sisoputnfrba/foro#3304]
Hola, tengo una duda con el enunciado de FS con la peticion de abrir archivo. Cuando abro el archivo tengo que asignarle bloques en la fat dandole un nuevo bloque inicial? Por otra parte en el caso que no exista el archivo, aviso a kernel que no existe y espero que me mande la orden de crear el archivo o lo creo directamente sino lo encuentro?

**Comment by iago64** [comment]
Buenas! Cómo va?

Al momento de abrir el archivo, pueden darse 2 situaciones:

1. El archivo ya existe, ahi solamente el FS le contesta al Kernel que el archivo existe y es tema del kernel actualizar las estructuras administrativas (tabla de archivos abiertos)
2. El archivo no existe, en ese caso el FS le avisa al kernel que el archivo no existe y el Kernel le pide que lo cree con tamaño 0.

Entiendo que ambas dudas quedaron resueltas.
Saludos.-
