### ISSUE TITLE
Duda sobre leer y escribir en FS

### ISSUE THREAD

**Issue by GregorioOndjian** [sisoputnfrba/foro#3305]
Buenas como va? Nos surgió una duda con respecto a estas 2 peticiones. A la hora de escribir nos van a mandar una dirección física y un puntero. Nosotros solicitamos la información a memoria para escribir en un bloque. Este bloque sería el bloque correspondiente a alguno de los reservados en swap no? porque nosotros hicimos la función pensando que había que escribir la FAT y no nos cierra en nada. Con el leer es la misma duda. 
En síntesis, estas 2 peticiones operan sobre la parte de swap no?
Desde ya muchas gracias.

**Comment by iago64** [comment]
Buenas! Cómo va?

Solo para ordenar un poco el panorama, porque creo que estas viendo solo una parte del escenario, vos tenes 2 archivos principales en el FS:

### Tabla FAT
Este archivo es el que tiene como bien decís los números de los bloques.


### Archivo de bloques
Este archivo tiene 2 partes, una reservada para SWAP y otra para los datos de los archivos que en el enunciado lo llamamos partición FAT:

![image](https://github.com/sisoputnfrba/foro/assets/1622109/66fd5bb1-047e-483e-97c4-6419b96b528c)

Entonces los datos de los archivos van a estar en esta segunda partición (la que esta en color amarillo claro)

Saludos.-

**Comment by GregorioOndjian** [comment]
Okey okey, no entonces entedimos mal, pensabmos que la particion fat era la tabla fat que mencionaban mas arrba, ahora entiendo un poco mejor. Dejo el hilo abierto por las dudas por si nos surge alguna duda mas hoy. Graciass
