### ISSUE TITLE
Prueba file system

### ISSUE THREAD

**Issue by cserrudo** [sisoputnfrba/foro#3307]
Buenas, tengo dudas sobre los resultados que estamos teniendo al ejecutar los 6 procesos, el problema lo tenemos en los MOV OUT/IN, antes cuando ejecutaban y finalizaban los 6 procesos nosotros lo teniamos implementado de esta forma en memoria, en la parte de conexiones :

```c 
case ACCESO_A_ESPACIO_USUARIO_ESCRITURA:
	//recibo de CPU dir fisica, el valor a escribir y PID
	pid = pedido_cpu->pid;
	dirFisica = pedido_cpu->direccion;
	escribir_espacio_usuario(dirFisica,valor);
	nroPag = dirFisica / memoriaConfig->tam_pagina;
	t_pagina* pagEscritura = buscar_pag_tabla(nroPag,pid);
	pagEscritura->ultimo_acceso = time(NULL);
	pagEscritura->bit_modificado = 1;
	//enviar OK
	enviar_memoria_cpu(pedido_cpu, memoriaConfig->socket_cpu, MARCO_EXITO);
	log_info(memoriaLogger,"PID: %d - Accion: <ESCRIBIR> - Direccion fisica: %d",pid,dirFisica);
break;
//MOV IN desde cpu
case ACCESO_A_ESPACIO_USUARIO_LECTURA:
	//recibo de CPU dir fisica
	pid = pedido_cpu->pid;
	dirFisica = pedido_cpu->direccion;
	valor = leer_espacio_usuario(dirFisica);
	nroPag = dirFisica / memoriaConfig->tam_pagina;
	t_pagina* pagLectura = buscar_pag_tabla(nroPag,pid);
	pagLectura->ultimo_acceso = time(NULL);
	pedido_cpu->registroValor = valor;
	enviar_memoria_cpu(pedido_cpu, memoriaConfig->socket_cpu, MARCO_EXITO);
	log_info(memoriaLogger,"PID: %d - Accion: <LEER> - Direccion fisica: %d",pid,dirFisica);
break;
```

El tema es que yo tenía entendido que esta formula: dirFisica / memoriaConfig->tam_pagina; es la de número de marco, y no de página, lo cambié para que sea el numero de marco pero rompió todo este cambio, ahora nos está pasando que esta cuenta nos termina devolviendo a veces marcos que están libres, debuggeando ví que primero finaliza el proceso 6, luego el 2 (el 2 había ocupado el marco 0) y después cuando quiere hacer un MOV OUT el proceso 4 tira segmentation fault porque esta linea:  buscar_pag_tabla(nroPag,pid); nos devuelve NULL ya que el numero de marco calculado nos da 0, entonces al buscar el marco 0 que le pertenecia al proceso 2 y como lo desalojó, termina quedando sin un proceso asociado y no se puede modificar la pagina del proceso asociado pq no hay tal pagina, tiene más sentido que intente escribir y como no está lo cargue después en memoria, pero como no está escrito como resultado esperado en las pruebas y tampoco está en el enunciado me parece raro.

Intenté arreglarlo de esta forma: 
```c
if(!marco_escritura->libre){
	t_pagina* pagEscritura = buscar_pag_tabla(marco_escritura->pid_pag, marco_escritura->pid_proceso);
	escribir_espacio_usuario(dirFisica,valor);
	pagEscritura->ultimo_acceso = time(NULL);
	pagEscritura->bit_modificado = 1;
	enviar_memoria_cpu(pedido_cpu, memoriaConfig->socket_cpu, MARCO_EXITO);
	log_info(memoriaLogger,"PID: %d - Accion: <ESCRIBIR> - Direccion fisica: %d",pid,dirFisica);
}else{
	enviar_memoria_cpu(pedido_cpu, memoriaConfig->socket_cpu, NO_OK);
	log_error(memoriaConfig, "no se encontro la pagina");
}
```

Implementándolo de esta forma avanza bastante pero no terminan finalizando todos, quedan el 4 y 5 sin finalizar. 
Mi compañero sugirió que cuando no encuentre la pagina cuando calculamos el nro de marco a partir de la dirección fisica, mandemos la instrucción de page fault para cargar la página así la escribimos/leemos y yo pienso igual, pero quería saber si estaría bien, o es que ni siquiera es un problema que deberiamos tener sino que le estamos errando al calculo del numero de marco (capaz la formula del numero de marco no es así).

Esto nos muestra en CPU y FS cuando intentamos escribir/leer en un marco que está libre (lo que está en rojo): 

![image](https://github.com/sisoputnfrba/foro/assets/102488578/dea5f31d-b095-4b92-8db6-4c9cf11fc5b2)
![image](https://github.com/sisoputnfrba/foro/assets/102488578/927bbd8f-e3b7-4b4e-bafc-352bfc74c826)

Gracias

**Comment by cserrudo** [comment]
Entonces el problema no es que haya cambiado que dirFisica/tamanio_pagina es el número de marco, no? El problema viene de antes de que haga el MOV_OUT 
Lo que me llama la atención es que antes de que haga ese cambio por lo menos finalizaban todos los procesos y el proceso 6 finalizaba por invalid write, como antes funcionaba entonces pensaba que estaba mal el cálculo y era eso.

Gracias, saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

Efectivamente lo que dice Lean es que el problema da la sensación de que lo tienen de antes, por eso la pregunta de si estaban gestionando el Page Fault al momento de que traducen la dirección lógica a física en el F_READ (en este caso).

Por otro lado, no se queden con el pensamiento de que antes terminaba y eso estaba bien, porque puede ser que terminase, pero hiciese cualquier fruta y por ej si en el archivo escribían el número 65, después podía ser que leían el 35287234 que NADA tiene que ver con el 65 original que escribieron, por favor no se queden con el "termino, ya esta ok".

Saludos.-

**Comment by cserrudo** [comment]
Si! Era eso y también teníamos problemas con la función fwrite con los flags, ya lo pudimos solucionar

Muchas gracias dami y lean.
