### ISSUE TITLE
problema con conexion , le mando una vez , pero le llega 2 vece el mismo codigo de operacion a fs

### ISSUE THREAD

**Issue by Facundo-Su** [sisoputnfrba/foro#3309]
buenas, nos surgio una duda a la hora de hacer conexion de kernel a fs cuando hago un fopen, por lado de kernel le aviso a fs que realize la operacion f_open 1 sola vez, pero el fs recibe 2 vece abrir archivo, y me pisa el variable que le pase ,(la primera vez le llega bien y la segunda como que queda vacio)

### 📝 Código relevante
```c
case ABRIR_ARCHIVO:
			t_list* nose = recibir_paquete(cliente_fd);
			char *nombre_nose = list_get(nose,0);
			log_info(logger_file_system, "llegue %i vez ",prueba);
			prueba++;
			log_info(logger_file_system, "Abrir Archivo: <%s>",nombre_nose);
			int tamanio_archivo = abrir_archivo_fcb(nombre_nose);
			//enviar_tamanio_archivo(tamanio_archivo, cliente_fd);
			break;
```
### 🐛 Cómo reproducir el error
![image](https://github.com/sisoputnfrba/foro/assets/82105260/d42c5844-ecdd-4c4d-8a88-dc5108d273cb)

**Comment by iago64** [comment]
Buenas! Cómo va?

Algo super importante y que capaz no están notando es que en el log del FS hay un fragmento muy copado de Valgrind que me juego a que viene de un invalid read / write y que dice `Address 0x.... is 20 bytes`, eso me da la pauta de que el problema no es el doble mensaje, si no, que están teniendo algún problema de otra índole.
Revisen los invalid read / invalid write del FS y vean si con eso no se soluciona el problema, porque a priori el poco código que pasaron no me da la sensación de que este haciendo nada raro, aunque faltan las implementaciones de las funciones y el `enviar_tamanio_archivo()` esta comentado.

Saludos.-

**Comment by Facundo-Su** [comment]
![image](https://github.com/sisoputnfrba/foro/assets/82105260/9b2f1a8e-18c5-4b21-8024-fd1232d09858)
solucione todo los invalid read/ write , pero me sigue saliendo el problema
