### ISSUE TITLE
Duda sobre prueba integral (posible error en las pruebas)

### ISSUE THREAD

**Issue by Fcallero** [sisoputnfrba/foro#3310]
### 📔 Citas del documento de pruebas

En resultados esperados de las pruebas integrales dice: 
Inicia el proceso B, crea el archivo GuiaPlatinoSagaDarkSouls, lo trunca y escribe en él, cuando finaliza lo cierra liberando a C.
Inicia el proceso C, desaloja al que esté ejecutando en ese momento, intenta abrir el archivo GuiaPlatinoSagaDarkSouls y se bloquea por el read/write lock hasta que lo libere B.

Y cuando se inicia el proceso dice que escribamos en consola:
INICIAR_PROCESO INTEGRAL_C 32 1

y en el pseudocodigo se referencia a la pagina 3 (direccion logica 48):
F_READ GuiaPlatinoSagaDarkSouls 48

### 👍 Comportamiento esperado
Que B libere a C y C termine de ejecutar correctamente los F_read llegando a exit

### 👎 Comportamiento obtenido
Nos tira segmentation fault debido a que C tiene 2 paginas y en el pseudocodigo se referencia a la pagina 3 para guardar el contenido leido del archivo.

Esto es un error de las pruebas o es un error a propósito y deberia finalizar el proceso por algun motivo o de alguna otra manera?

**Comment by iago64** [comment]
Buenas! Cómo va?

Efectivamente nos quedó un error en el doc (culpa del copy-paste) el tamaño del proceso C es 64 no 32, gracias por avisar.

Saludos.-
