### ISSUE TITLE
Logs mínimos y obligatorios

### ISSUE THREAD

**Issue by matibrewda** [sisoputnfrba/foro#3311]
### 📔 Citas del enunciado/videos
> Logs mínimos y obligatorios
> “Acceso FAT - Entrada: <NRO_ENTRADA_FAT> - Valor: <VALOR_ENTRADA_FAT>”

Buenas, una consulta.
Este log lo tenemos que hacer cuando leemos la tabla, la escribimos o en ambos casos?

**Comment by iago64** [comment]
Buenas! Cómo va?

En ambos casos.

Saludos.-

**Comment by matibrewda** [comment]
Muchas gracias!
