### ISSUE TITLE
Proceso 2 en Prueba Estres tarda mucho tiempo en finalizar

### ISSUE THREAD

**Issue by LautaroRobles** [sisoputnfrba/foro#3312]
Buenas!

En la prueba de estres dice:
> - Los procesos ESTRES_1, ESTRES_2 y ESTRES_4 finalizan sin problemas.
> - Los 4 procesos ESTRES_3 continúan en loop infinito.

Los procesos ESTRES_1 y ESTRES_4 estan finalizando sin problemas. Pero el proceso ESTRES_2 lo tenemos ejecutando bastante tiempo y nunca termina.

¿Será que que la instruccion de SET AX 5000 usa un valor muy alto?

```
SET AX 5000
SET BX 1
SET CX 0
SET DX 1
SUM CX DX
SUB AX BX
WAIT REC1
SIGNAL REC1
JNZ AX 4
EXIT
```

Con el delay configurado en memoria (50ms) y el quantum del kernel (200ms) calculamos se restara a 5000 cada 1,2 segundo mas o menos.
Con lo cual el proceso finalizaria en mas o menos 1h y 45min.

**Comment by iago64** [comment]
Buenas! Cómo va?

La idea de la prueba de estres es que no escale la memoria, que tarde 1 hora significa que la vamos a cortar antes si vemos que no tienen esperas activas / memory leaks 😉 

Saludos.-

**Comment by LautaroRobles** [comment]
Buenisimo, gracias!
