### ISSUE TITLE
Duda sobre creacion de proceso

### ISSUE THREAD

**Issue by LautaroRobles** [sisoputnfrba/foro#3313]
Buenas, se que esto es una duda sobre algo bastante viejo. Pero recien notamos lo siguiente en el enunciado:

#### En la parte de creacion de procesos en el Kernel dice:
> Ante la solicitud de la consola de crear un nuevo proceso el Kernel deberá informarle a la memoria que debe crear un proceso con el nombre del archivo de pseudocódigo junto con el tamaño en bytes que ocupará el mismo.

Con esto entendimos que cuando se recibe la solicitud de memoria de crear proceso se debe comunicar a memoria la cual inicializa las estructuras del proceso dado todos esos datos.

#### Pero despues en el enunciado dice:
> En caso de que el grado máximo de multiprogramación lo permita, los procesos pasarán al estado READY, enviando un mensaje al módulo Memoria para que inicialice sus estructuras necesarias.

Ahora la inicializacion de las estructuras deberia ocurrir cuando se pasa un proceso de NEW a READY.

¿Debemos tener dos mensajes a memoria? ¿Que rol cumpliria el primer mensaje?

**Comment by iago64** [comment]
Buenas! Cómo va?

El primer mensaje esta pensado para que la Memoria reserve en SWAP el espacio ya que lo va a estar utilizando a futuro.

En el caso del pasaje a READY es para que en caso de que no tengan creadas las estructuras administrativas como ser la tabla de páginas la creen, si hacen todo con el primer mensaje, entonces no hay problema, pueden no tener el segundo mensaje.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Para agregar a esto mismo, a efectos prácticos pueden hacer todo junto en el paso de new a ready si ya lo tienen de esa manera.

**Comment by Mimito164** [comment]
@iago64 Que sucede si no hay espacio en memoria para crear el proceso, se supone que espere en el estado de NEW o lo debería mandar al estado de EXIT?

**Comment by LeandroCarbajales** [comment]
Por si queremos matar procesos que estén en NEW desde la consola del Kernel :)

**Comment by LautaroRobles** [comment]
Entendido, entonces vamos a enviar un unico mensaje a Memoria cuando se crea el proceso
