### ISSUE TITLE
Segmentation fault al usar una libreria de las commons

### ISSUE THREAD

**Issue by pfernandezUTN** [sisoputnfrba/foro#3314]
Estamos teniendo un segmentation fault al querer tratar strings en varios modulos del proyecto. Actualmente nos pasa en cpu y kernel.
Haciendo debugs nos encontramos con que el problema ocurre con la funcion de las commons **string_split()** al querer acceder a alguno de las posiciones de la lista que retorna. 

### 🔎 Búsqueda en foros

Estuve probando una forma de debugear segmentation faults que encontre en un [video ](https://www.youtube.com/watch?v=bfWxAG1vUM4) de youtube. Esta herramienta te muestra la linea donde salta el sf, al correrlo con el codigo del cpu, vemos que esta saltando en un archivo fuera del proyecto (abajo de todo esta el mensaje exacto).
### 📝 Código relevante

Resumen de lo que se hace en CPU:
char* respuesta = strdup("SUM AX BX"); // hardcodeado para el ejemplo
char** spliteado;
spliteado = string_split(respuesta, " ");
printf("instruccion: %s", spliteado[0]); 
### 💻 Logs

**Mensaje de gdb ante el sf:**
`Program received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:74
74            >>/sysdeps/x84_64/multiarch/strlen-avx2.S: No such file or directory.`

**Comment by pfernandezUTN** [comment]
Un detalle... el sf que tenemos en kernel tira exactamente el mismo mensaje al correrlo con gdb.

**Comment by iago64** [comment]
Buenas! Cómo va?

Algo interesante y copado de las commons es que tienen varios años dando vueltas y como han de suponer sin memory leaks ni segment fault propios de la biblioteca.

Respecto a los segment faults, hay una herramienta hermosa que es Valgrind y que les puede dar mucha mas info de el origen del problema y que ademas nos puede ayudar a nosotros a tener algo de info respecto a que esta pasando en su código, por eso te pido que primero vean la guía de Valgrind: https://docs.utnso.com.ar/guias/herramientas/valgrind

Y en segundo lugar nos pasen el output de valgrind de alguno de los módulos que les tira segment fault para poder ayudarlos, en el aire se nos complica un monton.

Saludos.-

**Comment by pfernandezUTN** [comment]
Buenas Damian, gracias por la rapida respuesta.
Ahi estoy probando con valgrind como me decis, y paso algo raro... 
Al ejecutar el modulo con el comando valgrind funciona bien!! no tengo el segmentation fault. 
Te dejo lo que se loguea por consola en ambas ejecuciones del mismo codigo (con y sin valgrind).:

**Con Valgrind:**

`utnso@utnso:~/Desktop/tp-2023-2c-SyntaxisError/cpu$ valgrind ./bin/cpu.out 
==39943== Memcheck, a memory error detector
==39943== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==39943== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==39943== Command: ./bin/cpu.out
==39943== 
[INFO] 18:32:36:552 CPU/(39943:39943): 
---------- INICIO DEL LOG ----------

[INFO] 18:32:36:628 CPU/(39943:39943): Inicio el ciclo de instruccion.
[INFO] 18:32:36:630 CPU/(39943:39943): Entre al fetch para la instruccion 0
[INFO] 18:32:36:632 CPU/(39943:39943): Instruccion recibida de memoria en fase fetch: SUM AX BX
[INFO] 18:32:36:633 CPU/(39943:39943): Entre al decode para la instruccion 0
algo: 4[INFO] 18:32:36:637 CPU/(39943:39943): resultado del decode: instr:SUM | p1:AX | p2:BX
[INFO] 18:32:36:642 CPU/(39943:39943): Se ejecuta la instruccion SUM AX BX
==39943== 
==39943== HEAP SUMMARY:
==39943==     in use at exit: 554 bytes in 7 blocks
==39943==   total heap usage: 110 allocs, 103 frees, 13,457 bytes allocated
==39943== 
==39943== LEAK SUMMARY:
==39943==    definitely lost: 0 bytes in 0 blocks
==39943==    indirectly lost: 0 bytes in 0 blocks
==39943==      possibly lost: 0 bytes in 0 blocks
==39943==    still reachable: 554 bytes in 7 blocks
==39943==         suppressed: 0 bytes in 0 blocks
==39943== Rerun with --leak-check=full to see details of leaked memory
==39943== 
==39943== For lists of detected and suppressed errors, rerun with: -s
==39943== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
`
---------------------------------------------------------------------------------------------
**Sin Valgrind:**

`utnso@utnso:~/Desktop/tp-2023-2c-SyntaxisError/cpu$ ./bin/cpu.out 
[INFO] 18:34:58:003 CPU/(40062:40062): 
---------- INICIO DEL LOG ----------

[INFO] 18:34:58:003 CPU/(40062:40062): Inicio el ciclo de instruccion.
[INFO] 18:34:58:003 CPU/(40062:40062): Entre al fetch para la instruccion 0
[INFO] 18:34:58:003 CPU/(40062:40062): Instruccion recibida de memoria en fase fetch: SUM AX BX
[INFO] 18:34:58:004 CPU/(40062:40062): Entre al decode para la instruccion 0
Segmentation fault (core dumped)
`

**Comment by iago64** [comment]
Con Valgrind es todo el output que tenes? Hay algo que no me cierra, porque con Valgrind no estas teniendo ningun invalid read / invalid write ni el segment fault.

**Comment by pfernandezUTN** [comment]
Si, ese es todo el output, desde que ejecuto el comando hasta que termina la ejecucion. Cabe aclarar que hice un bypass para llegar a la parte del problema mas rapido sin que haya tantos log que no vienen al caso (aun con el bypass el error ocurre igual).

**Comment by pfernandezUTN** [comment]
Ademas, se puede ver que en el log sin valgrind el sf salta cuando estoy en el decode y ejecuto el split, mientras que en el log con valgrind el decode se hace bien y se muestra el resultado del split.

**Comment by iago64** [comment]
Buenas!

Estuve viendo el fragmento de código que dejaste y si bien entiendo que es la forma de reproducir el error, y no me esta tirando error alguno

```c
#include <stdio.h>
#include <string.h>
#include <commons/string.h>

int main() {
  
  char* respuesta = strdup("SUM AX BX"); // hardcodeado para el ejemplo
  char** spliteado;
  spliteado = string_split(respuesta, " ");
  printf("instruccion: %s", spliteado[0]);
  return 0;
}
```

Es mucho pedirte que tires algo mas de código de donde viene el error?

Saludos.-

**Comment by pfernandezUTN** [comment]
![imagen](https://github.com/sisoputnfrba/foro/assets/132232375/6037892a-857f-4270-8382-56199d34ae34)

----
En la captura se puede ver:
- Primero la ejecucion comun, sin nada
- Segundo la ejecucion con valgrind (se ve que no hay sf y que el printf se hace bien)
- Tercero: la ejecucion con gdb que muestra la linea donde tengo el sf y que lo esta ocacionando (que es lo que esta en el primer mensaje del post)

El codigo que ejecute fue este:
`int main() {
  
  char* respuesta = strdup("SUM AX BX"); // hardcodeado para el ejemplo
  char** spliteado;
  spliteado = string_split(respuesta, " ");
  printf("instruccion: %s", spliteado[0]);
  return 0;`

**Comment by iago64** [comment]
Buenas!

Revisando el output un poco mas en detalle, veo que te dice `Segmentation fault at src/cpu.c:27` eso quiere decir que te esta rompiendo la línea 27 y el código que me pasas, constando includes no debería irse mas allá de las 13 lineas.

De hecho podes hacer la prueba mas simple que es crear el siguiete código en un archivo `main.c`:

```c
#include <stdio.h>
#include <string.h>
#include <commons/string.h>

int main() {
  
  char* respuesta = strdup("SUM AX BX"); // hardcodeado para el ejemplo
  char** spliteado;
  spliteado = string_split(respuesta, " ");
  printf("INSTRUCCION: %s\n", spliteado[0]);
  printf("PARAMETRO 1: %s\n", spliteado[1]);
  printf("PARAMETRO 2: %s\n", spliteado[2]);
  return 0;
}
```

Y compilarlo con el siguiente comando `gcc main.c -o main -lcommons` y despues lo corres con `gdb` y fijate, eso no deberia darte error.

Saludos.-

**Comment by iago64** [comment]
@pfernandezUTN Cómo va?

Pudiste resolver el inconveniente?

Saludos.-

**Comment by pfernandezUTN** [comment]
Buenas. No, todavia no pudimos solucionarlo, igual aun no probe el ultimo comando que me mandaste. Mas que nada porque decidimos darle prioridad a otras cosas antes que resolver esto.

**Comment by RaniAgus** [comment]
¡Buenas! Por si sirve de ayuda, estuve revisando el código del repo y veo que la `respuesta` es una variable global que más adelante se libera. Quizás `string_split` esté recibiendo un puntero a una `respuesta` ya liberada.

Idealmente estaría bueno que esa variable sea un parámetro de la función y no una variable global. De todas formas, antes de hacer el refactor, podemos probar agregando un chequeo de que no sea nulo ni bien entramos a la función, y seteando el puntero en `NULL` luego de liberarlo para así dejarlo consistente.

O sea:
```c
void decode() {
    if (respuesta == NULL) {
        log_error(logger, "No se puede ejecutar decode sin respuesta!");
        exit(1);
    }
    // ...
    free(respuesta);
    respuesta = NULL;
}
```

¿Hay algún otro hilo que pueda estar seteando esta variable global? De ser así, pueden probar de correr el módulo con Helgrind para chequear posibles condiciones de carrera. En el video de la charla de Valgrind pueden encontrar una mini-guía de cómo se usa.

Otro detalle, en la función encontré este comentario:
```c
// el exit lo tengo que resolver distinto, al string split no le gustan los textos que no tengan el caracter a splitear
```
Ante cualquier duda sobre el funcionamiento de las commons no duden en consultarnos o crear un nuevo `main()` y probar. Justo en las commons no tenemos tests de ese caso, pero me puse a probarlo en un main y no noté ningún problema:

```c
#include <stdio.h>
#include <string.h>
#include <commons/string.h>

int main() {
    char **spliteado = string_split("EXIT", " ");

    printf("spliteado[0] => %s\n", spliteado[0]);
    printf("spliteado[1] => %s\n", spliteado[1]);

    string_array_destroy(spliteado); // libera spliteado[0] y spliteado
    return 0;
}
```

```
$ gcc main.c -lcommons
$ ./a.out
spliteado[0] => EXIT
spliteado[1] => (null)
```

Saludos

**Comment by pfernandezUTN** [comment]
Buenas tardes. Ok, vamos a probar esto que comentas, muchas gracias.

**Comment by pfernandezUTN** [comment]
El main de prueba ue mandaste lo puedo ejecutar sin problema. Pero aun no estoy pudiendo lograr que en el programa real funcione. Probe con el string_array_destroy() y sacando los free para ver si cambiaba algo pero nada.

**Comment by pfernandezUTN** [comment]
Ahora probe comentar el main actual y hacer otro main haciendo simplemente el split y ahi tambien me esta tirando el segmentation fault, la verdad que ya no se me ocurre que hacer. 
![imagen](https://github.com/sisoputnfrba/foro/assets/132232375/12056887-c7ac-410f-8a62-74bc48125977)

**Comment by pfernandezUTN** [comment]
Ahi lo solucione. El resumen de porque ocurria es este:
Si ven en nuestro repo, tenemos una carpeta de utils con cosas generales que se usan en todos los modulos. Resulta que tenemos un header llamado common.h que solamente tiene unos enums y los \#include de otras cosas ahi, esto con el fin de no estarlos repitiendo en todos los archivos. Tambien, hay un string.c que solamente tiene una funcion para que el str_compare devuelva 1 en vez de 0. Su header tiene un \#include <string.h> y a su vez el common.h tambien tiene ese include, creo yo que eso esta generando como una especie de referencia circular medio falopa o algo por el estilo... El punto es que borrando el string.c de los utils se soluciono el segmentation fault, Asi que 100% que ahi esta el problema.

**Comment by iago64** [comment]
Genial, si el problema esta resuelto, no se olviden de cerrar el issue.
