### ISSUE TITLE
Pregunta sobre PageFault

### ISSUE THREAD

**Issue by ParedesMicaela** [sisoputnfrba/foro#3316]
Buenas tardes! Tenia una duda sobre esta parte del enunciado. No termino de entender eso de pedirle al FS la pagina. El FS debería tener una estructura de páginas? 

### 📔 Citas del enunciado/videos
```
Page Fault
El módulo deberá solicitar al módulo File System la página correspondiente y escribirla en la memoria principal.
```

**Comment by iago64** [comment]
Buenas! Cómo va?

Ahi queda a criterio de cada grupo, pueden tener alguna estructura en el FS o pueden tener en la memoria la posición o bloque en SWAP.

Saludos.-

**Comment by iago64** [comment]
@ParedesMicaela Cómo va? ¿Quedo resuelta la duda?

Saludos.-

**Comment by ParedesMicaela** [comment]
SII mil disculpas que no lo cerré! Gracias!
