### ISSUE TITLE
Escribir en SWAP (Múltiples preguntas)

### ISSUE THREAD

**Issue by diegohcanetti** [sisoputnfrba/foro#3317]
Esto significa que en la particion de swap, la cual teniamos asignada con un malloc, le hacemos un fwrite del contenido de la pagina? Este contenido sería lo que está escrito en el espacio de usuario? Si es así, tendríamos que hacer un memcpy y mandarlo al FS, esto sería con un send o con paquetes? 

### 📔 Citas del enunciado/videos
>Si la víctima se encuentra modificada, se deberá previamente escribir en SWAP.

**Comment by iago64** [comment]
Buenas! Cómo va?

La particion de SWAP es parte del FS y es parte del archivo de bloques, no deberían haberla implementado como un `malloc()`

Tengan en cuenta que inicialmente los procesos reservan su espacio en SWAP y despues como es paginación bajo demanda, van a ir cargando las páginas a medida de que lleguen los page fault, es decir, que les va a llegar el Page Fault, van a pedirle la página desde la Memoria al FS y este se las va a devolver (todo por comunicación via sockets).

Saludos.-

**Comment by MartinSintas** [comment]
Buenas Dami, entonces redondeando el tema debemos asignar un espacion fijo como se ve en las config de filesystem 

>CANT_BLOQUES_SWAP=64

ahora me cierra más porque no un malloc() , mil gracias :D

**Comment by iago64** [comment]
Buenas!

Efectivamente, uds van a tener 2 cantidades de bloques de su archivo de bloques:

```ini
CANT_BLOQUES_TOTAL=1024
CANT_BLOQUES_SWAP=64
```
Entonces algunas cuentas rápidas que tienen son las siguientes:
El valor de `CANT_BLOQUES_TOTAL` les va a decir cuantos bloques tiene el FS, de lo que se desprende que `CANT_BLOQUES_TOTAL` * `TAM_BLOQUE` les va a dar el tamaño del archivo de bloques.

El valor de `CANT_BLOQUES_SWAP` les dice cuantos bloques de SWAP tienen, entonces lo que les conviene hacer es respetando el enunciado es reservar desde el bloque 0 hasta el bloque `CANT_BLOQUES_SWAP - 1` para SWAP y el resto dejarlo para la parte de "FAT" o dicho de otra manera, los bloques de los archivos:

![image](https://github.com/sisoputnfrba/foro/assets/1622109/8e74bff6-0888-4ef1-9690-357df12588d4)

Saludos.-
