### ISSUE TITLE
Duda con levantar FAT

### ISSUE THREAD

**Issue by ParedesMicaela** [sisoputnfrba/foro#3319]
Buenas! Tenia una duda con esta parte del enunciado. Nosotros implementamos el for de esta forma para que lea todo el tamaño de la fat pero no sabemos si es solamente un while hasta el UINT32_MAX, ya que se menciona en el enunciado y no lo estamos usando. 

### 📔 Citas del enunciado/videos
```
Cada entrada será representada por un dato de tipo uint32_t, es decir que el tamaño en bytes del archivo FAT será (CANT_BLOQUES_TOTAL - CANT_BLOQUES_SWAP) * sizeof(uint32_t).
Si al iniciar el FS, no se encuentra el archivo de la tabla FAT, se deberá crear el mismo e inicializarlo con todos valores en 0 que representará que dicho bloque lógico está libre. Cabe resaltar que el bloque lógico 0 estará reservado y no debe ser asignado a ningún archivo.
El valor correspondiente a un EOF (End of File) será representado como la constante UINT32_MAX.
```
Nosotros lo hicimos asi:
```
	//si no existe el archivo fat, lo abre y pone su valor en 0
	if (archivo_fat == NULL)
	{
		archivo_fat = fopen(path, "wb+");

		uint32_t valor_inicial = 0; 
	    for (size_t i = 1; i < tamanio_fat; i++) 
		{
			fwrite(&valor_inicial, sizeof(tam_entrada), 1, archivo_fat);
        }
        fflush(archivo_fat);
```

**Comment by diegohcanetti** [comment]
Nuestra pregunta Dami era si teníamos que hacer un while(!EOF) para levantar el FAT o se podría hacer como hicimos, un for que recorra el tamanio_fat (que sería el tamaño del archivo).

**Comment by diegohcanetti** [comment]
![image_2023-12-06_213453](https://github.com/sisoputnfrba/foro/assets/102698705/7d0e21ca-751c-424c-89fd-f00cc82bf347)

Queda claro gracias!
