### ISSUE TITLE
Estructuras necesarias para la deteccion de Deadlock

### ISSUE THREAD

**Issue by Mimito164** [sisoputnfrba/foro#3320]
Estoy viendo como implementar todo el tema del _manejo de recursos_ incluyendo la _detección de deadlocks_ y _bloqueo de procesos_. Quería saber si lo que estoy queriendo hacer va por buen camino o si da para quilombo.

### Tipos de bloqueo

Por lo que estuve viendo en el enunciado hay 3 tipos de motivos por los cuales un proceso se puede bloquear: por recursos que vienen por config, por locks de archivos, por page faults. 

En principio mi idea seria hacer una lista de bloqueados con sub listas. Por ejemplo:

- Lista Bloqueados
  - Bloqueados por recursos:
    - RA
    - RB
    - RN...
  - Bloqueados por archivos
  - Bloqueados por Page Fault
  
### Gestión de recursos

La asignación y peticiones de recursos entiendo que se maneja por separado al bloqueo de procesos. Mas que nada por el hecho de que el algoritmo de detección de deadlock requiere de mas información que solo tipo de bloqueo.

Para la gestión de recursos pensé en hacer 3 estructuras:

1. Vector/Lista de recursos disponibles (lo uso para manejar cuantos recursos disponibles tengo)
2. Matriz de recursos asignados  
3. Matriz de solicitudes de recursos

Para las dos matrices las utilizaría para el algoritmo de detección de deadlock.  Al principio pensé en hacer el algoritmo de detección de deadlock que enseña la cátedra, pero en un checkpoint me recomendaron buscar bucles en la asignación/solicitud de recurso (no encontré en ningún issue si esta chekeado de que esto funke).

Para buscar bucles tendría que
1. empezar por cada proceso que tiene una solicitud de recursos
2. para cada uno de estos recursos buscar a que proceso tiene una instancia asignada.
3. para cada uno de estos pocesos buscar que solicitud de recurso tiene (repetir paso 1).
4. eventualmente, encontrar el proceso que empezó todo, osea, hay un bucle.

**Comment by LeandroCarbajales** [comment]
Buenas!
Voy respondiendo por partes

> Tipos de bloqueo

Estás en lo correcto, hay distintos motivos por los cuales un proceso puede estar bloqueado, cada uno con un evento distinto de desbloqueo ("page fault" ante respuesta de la memoria, "recurso" ante un signal y "archivo" ante un f_close). Para el caso de recursos y archivos se podría agregar también que cuando un proceso finaliza libera todos sus recursos y archivos.
A estos 3 motivos te agrego uno más, el bloqueo por "sleep" que se desbloquearía al transcurrir el tiempo indicado.

A efectos de implementación queda a criterio del equipo, no veo mal tener distintas listas para cada uno, lo único que te puedo aportar es que en el caso de archivos como de recursos, los procesos no se bloquean por "recurso" o "archivo" en general sino por un recurso o un archivo en particular, por lo que quizás prefieran tener una lista de bloqueado por cada recurso y cada archivo.

> Gestión de recursos
> Para las dos matrices las utilizaría para el algoritmo de detección de deadlock. Al principio pensé en hacer el algoritmo de detección de deadlock que enseña la cátedra, pero en un checkpoint me recomendaron buscar bucles en la asignación/solicitud de recurso (no encontré en ningún issue si esta chekeado de que esto funke).

Mejor que hacer caso ciego a un comentario es mejor comprenderlo con los conceptos de la materia :)
Por supuesto que ante la duda pueden implementar el algoritmo de detección de deadlock que se ve en clase ya que el mismo no deja lugar a dudas ni lleva a falsos positivos ni falsos negativos.
La posibilidad de solamente buscar un bucle (lo que en clase vemos como espera circular) se da específicamente por la configuración de la prueba de deadlock que está publicada desde el checkpoint 3, donde hay una sola instancia de cada recurso. En ese contexto, si se da espera circular también se da un deadlock, y de ahí viene la recomendación que les damos para simplificarles esta parte. Si hubiera más de una instancia de algún recurso esto no sería cierto y no quedaría otra que correr el algoritmo de detección "posta".

Teniendo esto en cuenta te respondo lo siguiente:

> Para buscar bucles tendría que
    1. empezar por cada proceso que tiene una solicitud de recursos
    2. para cada uno de estos recursos buscar a que proceso tiene una instancia asignada.
    3. para cada uno de estos pocesos buscar que solicitud de recurso tiene (repetir paso 1).
    4. eventualmente, encontrar el proceso que empezó todo, osea, hay un bucle.


Algorítmicamente, a efectos de encontrar un bucle (o para el algoritmo de detección "posta") no es necesario que recorran literalmente sus listas de recursos y/o procesos, para eso está justamente la idea de hacerse una matriz de asignaciones y peticiones.
Recorrer una matriz buscando un "bucle" de 1s es mucho más simple que recorrer listas de elementos.

Te sirve la respuesta?
Saludos!
     Lean

**Comment by Mimito164** [comment]
No te entiendo del todo, por mas de que tenga la matriz de recursos asignados y la matriz de solicitud de recursos, de igual forma tengo que recorrer ambas matrices para encontrar bucles (a esto me refería en el mensaje, no estaba pensando en recorrer ninguna lista de procesos o recursos).

Si quisiera ahorrarme la búsqueda iterativa se me ocurre hacer lo siguiente:

1. Armo una nueva matriz que represente todas las conexiones, de procesos a recursos y de recursos a procesos.
2. Con esta nueva matriz puedo multiplicarla por si  misma y sacar los caminos de longitud n siendo n la cantidad de veces que la multiplico por si misma, si hago: $m^2$ me va a dar los caminos de longitud $2$, si hago $m^4$ obtendría los caminos de longitud 4, en este caso tendría un bucle.

No se si era esto lo que me estabas recomendando hacer.


Adjunto imagenes para explicar mejor esto:
![image](https://github.com/sisoputnfrba/foro/assets/57462065/7f8a5c8c-29f5-4b01-ba93-969f1ed70bb1)

**Comment by Mimito164** [comment]
Ahora creo que entendí todo mejor, no había leído el documento de pruebas y  no sabia que era una sola instancia... me guie mas por la consigna del tp que en el config figuran 2.

Solo para confirmar y me dejo de joder, entonces como es una instancia por recurso, pueden darse solo dos casos, hay un bucle (hay deadlock) o hay una cadena de solicitudes/asignaciones (no hay deadlock)

Muchísimas gracias

**Comment by LeandroCarbajales** [comment]
Tampoco tenés por qué creer en mí :P, como se ve en clase sobre las condiciones de deadlock: una espera circular es condición necesaria (si no existe no hay deadlock). En caso de tener una sola instancia de cada recurso pasa a ser necesaria y suficiente (hay deadlock).

Doy por aclarada la duda entonces y cierro el issue :)
