### ISSUE TITLE
Semaphore nivel MultiProgramacion

### ISSUE THREAD

**Issue by ArgonzMatias** [sisoputnfrba/foro#3321]
Buen dia, estoy con el siguiente problema. En la prueba 3, tengo que cambiar el nivel inicial seteado de multiprogramacion. Esto yo lo manegaba con un semaphoro que se iniciaba al principio y listo. Estuve investigando, y no hay manera de modificar este semaphoro ya iniciado, lo que me recomendaron online es que mate ese semaphoro y lo vuelva a iniciar con el semaphoro inicial. Sin embargo, si hago esto, descubri que ademas tendria que levantar todos los hilo que usan este semaphoro, el de largo plazo por ejemplo. Esto se que es poco recomendado (matar y volver a levantar hilos) pero fue lo mejor que encontre. Lo plantee de esta manera pero es medio raro, es como que se queda trabado el flujo sin avanzar como antes. En el debugger, si lo abro, me marca bien que hubo 4 posts al semaphoro inicial de new por ejemplo, pero no avanza, esta como congelado ahi.  pero si en Visual studio code paro manualmente el hilo, y lo vuelvo a ejecutar, ahi si agarra ese semaphoro como actualizado, ejecuta lo que tiene que ejecutar, y se para en el siguiente semaphoro que fue reiniciado (el ready por ejemplo). Queria saber si hay algun consejo de como encarar este punto o si vengo bien y hay alguna solucion para este probelma. 

### 📝 Código relevante
void operarConsola()
{
	pthread_mutex_lock(&mutexLoggerKernel);
	log_info(kernelLogger, "iniciando conosla");
	pthread_mutex_unlock(&mutexLoggerKernel);
	int planificacionIniciada = 1;
	pthread_mutex_init(&resources, NULL);
	while (1)
	{
		printf("ingrese un comando: \n");
		char *leido = readline(">");

		char **split = string_split(leido, " ");
		
//....
		else if (string_equals_ignore_case(split[0], "MULTIPROGRAMACION"))
		{
			int nivelMultiprogramacion = atoi(split[1]);
			kernelConf->grado_max_multiprogramacion = nivelMultiprogramacion;
			destruirPlani();
			sem_init(&planificacionPausada, 0, 0);
			planificacionIniciada = 0;
			iniciar_planificacion();		
		}
//...
}
void iniciar_planificacion()
{

    new = list_create();
    ready = list_create();
    exec = list_create();
    exit_estado = list_create();
    blocked = list_create();
    deadlocks = list_create();

    // semaforos
    sem_init(&semExecute, 0, 0);
    sem_init(&execute_libre, 0, 1);
    sem_init(&semNew, 0, 0);
    sem_init(&grado_multiprogramacion, 0, kernelConf->grado_max_multiprogramacion);
    sem_init(&semReady, 0, 0);
    sem_init(&io, 0, 0);
    sem_init(&fCreate, 0, 0);
    pthread_mutex_init(&mutex_tabla_archivos, NULL);
    pthread_mutex_init(&lista_recursos, NULL);
    pthread_mutex_init(&mutex_quantum, NULL);
    pthread_mutex_init(&mutex_pid_global, NULL);
    pthread_mutex_init(&mutexNodo, NULL);

    // mutex estados
    pthread_mutex_init(&mutexBlocked, NULL);
    pthread_mutex_init(&mutexNew, NULL);
    pthread_mutex_init(&mutexReady, NULL);
    pthread_mutex_init(&mutexExec, NULL);
    pthread_mutex_init(&mutexExit, NULL);

    lista_espera_archivos = list_create();
    lista_global_archivos = list_create();

    // inicio el array de recursos

    pthread_create(&th_largo_plazo, NULL, (void *)largo_plazo, NULL);
    pthread_detach(th_largo_plazo);

    pthread_create(&th_execute_pcb, NULL, (void *)execute, NULL);
    pthread_detach(th_execute_pcb);

    pthread_create(&th_corto_plazo, NULL, (void *)corto_plazo, NULL);
    pthread_detach(th_corto_plazo);

    pthread_create(&th_fs_respuesta, NULL, (void *)desbloquearPcbFS, NULL);
    pthread_detach(th_fs_respuesta);

    pthread_create(&th_memoria_respuesta, NULL, (void *)desbloquearPcbMemoria, NULL);
    pthread_detach(th_memoria_respuesta);
}

void destruirPlani()
{
    list_destroy(new);
    list_destroy(ready);
    list_destroy(exec);
    list_destroy(exit_estado);
    list_destroy(blocked);
    list_destroy(deadlocks);

    sem_destroy(&grado_multiprogramacion);
    sem_destroy(&semNew);
    sem_destroy(&semReady);
    sem_destroy(&semExecute);
    sem_destroy(&execute_libre);
    sem_destroy(&io);
    sem_destroy(&planificacionPausada);
    sem_destroy(&fCreate);
    pthread_mutex_destroy(&mutex_tabla_archivos);
    pthread_mutex_destroy(&lista_recursos);
    pthread_mutex_destroy(&mutex_quantum);
    pthread_mutex_destroy(&mutex_pid_global);
    pthread_mutex_destroy(&mutexNodo);
    pthread_mutex_destroy(&mutexBlocked);
    pthread_mutex_destroy(&mutexNew);
    pthread_mutex_destroy(&mutexReady);
    pthread_mutex_destroy(&mutexExec);
    pthread_mutex_destroy(&mutexExit);

    list_destroy(lista_espera_archivos);
    list_destroy(lista_global_archivos);

    pthread_cancel(th_largo_plazo);

    pthread_cancel(th_execute_pcb);

    pthread_cancel(th_corto_plazo);

    pthread_cancel(th_fs_respuesta);

    pthread_cancel(th_memoria_respuesta);
}

//inicialmente empieza asi todo:

void inicio_array_recursos()
{
    sem_init(&planificacionPausada, 0, 1);
    
    tamanioArrayRecurso = sizeof(kernelConf->recurso);
    for (int i = 0; i < tamanioArrayRecurso; i++)
    {
        t_queue *cola = queue_create();
        arrayRecursos[i] = cola;
    }
}

int main(int argc, char *argv[])
{
   pthread_mutex_init(&mutexLoggerKernel, NULL);
  pthread_mutex_lock(&mutexLoggerKernel);
  kernelLogger = log_create("bin/kernel.log", "Kernel", true, LOG_LEVEL_DEBUG);
  pthread_mutex_unlock(&mutexLoggerKernel);
  kernelConf = kernel_config_crear(PATH_CONFIGS);

  hacerConexiones(kernelConf);

  pthread_mutex_lock(&mutexLoggerKernel);
  log_info(kernelLogger, "conexiones realizadas con exito en kernel");
  pthread_mutex_unlock(&mutexLoggerKernel);
  // aca tendria que recibir cosas de los distintos modulos
  inicio_array_recursos();
  iniciar_planificacion();
  
  // que avise si no hay procesos para planificar

  pthread_t manejo_consola;
  pthread_create(&manejo_consola, NULL, (void *)operarConsola, NULL);
  pthread_detach(manejo_consola);
  
  
  for (;;)
  {
  }
  

  pthread_mutex_unlock(&mutexExit);
  return 0;
}

### 🐛 Cómo reproducir el error
ejecuto toda la prueba anterior, y se muere en la ultima prueba de cambiar nivel multiprogramacion. Si solo ejecuto la ultima parte, sin toda la parte anterior, sucede lo mismo.

**Comment by LeandroCarbajales** [comment]
Buenas!
Creo que se están complicando de más.
Aumentar el grado de multiprogramación no es más que hacerle los sem_post() necesarios al semáforo.
Reducir el grado de multiprogramación no es más que hacerle los sem_wait() necesarios al semáforo, para esto último el problema que se podría dar es si el semáforo llega a valer 0 (o menos) y se te terminaría bloqueando el hilo que realiza el wait, sin embargo, si analizan un poco las pruebas, deberían poder corroborar que esto último no ocurre.

Te aclara las dudas?
Saludos!
      Lean

**Comment by ArgonzMatias** [comment]
Buenas lean, tenes razon, me habia olvidado que se podia implementar asi. Gracias!
