### ISSUE TITLE
Problema con socket interrupt

### ISSUE THREAD

**Issue by GonzaloRDuart** [sisoputnfrba/foro#3324]
Buenas! Estamos con mi equipo haciendo las pruebas de estres y despues de recibir muchas interrupciones seguidas en el socket de interrupt de CPU se rompió el socket de tal forma que ya reinicié la VM 3 veces y sigue sin andar. Intente usar dhclient -r pero tampoco me anduvo. Alguna idea de como solucionarlo? Gracias!

**Comment by iago64** [comment]
Buenas!

Reabro el issue porque asumo que fue un miss click al responder.
En principio lo que estas seteando esta bien, por eso me llama la atención el error, lo que te pasa después es que directamente no conecta?
Porque me llama muchísimo la atención que una vez finalizado el programa y vuelto a levantar después de un rato siguiera sin funcionar.

Saludos.-
