### ISSUE TITLE
Consulta uso liberias para ftruncate()

### ISSUE THREAD

**Issue by Bru-Nicolas-FRBA** [sisoputnfrba/foro#3325]
Buenas noches, tengo una consutla.

Se podria usar la libreria  ``` <unistd.h> ``` para poder usar un ftruncate() (incluido en esta libreria)

Estoy intentando truncar un archivo en el disco antes de modificarlo y queria ver si es posible usarla.
En caso de no poder utilizarla estaria usando una tecnica que supuestamente es menos eficiente pero de todas maneras funciona, la cual es: ``` Ir directamente a la posicion nueva (ampliando) y escribir un dato ```

**Comment by iago64** [comment]
Buenas!

Si, no hay problemas con las bibliotecas estandares de C.

Saludos.-
