### ISSUE TITLE
Escribir en bloque 

### ISSUE THREAD

**Issue by diegohcanetti** [sisoputnfrba/foro#3328]
Queria saber si entendí correctamente la consigna, ya que en el escribir en vez de recorrer todos los bloques simplemente tome el bloque final (que lo obtuve de la división del puntero de archivo sobre el tamaño de bloque) y copie el contenido en la "direccion" que obtuve del fat_mappeado (que sería el contenido de los archivos mmapeado). En otras palabras, hace falta recorrer la tabla de FAT, para realizar la escritura? Ya que en la lectura fui pasándola a la memoria cada bloque para ser escrito en memoria, pero en la escritura entiendo que solamente tienes que escribir en el bloque_final.

### 📔 Citas del enunciado/videos
>Se escribirá en el bloque correspondiente del archivo a partir del puntero recibido. Siempre se leerá/escribirá un bloque completo, los punteros utilizados siempre serán el 1er byte del bloque o página.

### 💭 Soluciones posibles
```
void escribir_contenido_en_bloque(uint32_t bloque_final, void* contenido, int tam_bloque) {
		
	uint32_t nro_de_bloque = tabla_fat_en_memoria[bloque_final];
	int tamanio = nro_de_bloque * tam_bloque;
		    
	//Copio los datos desde el archivo contenido al bloque del fat mappeado 
    	memcpy((char*)fat_mapeado + tamanio, contenido, tamanio);

}
```

**Comment by iago64** [comment]
Buenas! Cómo va?

Yo te hago una pregunta, si el resultado de la cuenta `puntero / tam_bloque`, te da por ej 6, ¿Es el bloque 6 del FS o el bloque 6 del archivo? Si es el bloque 6 del archivo, ¿Cómo sabes que bloque del FS es el bloque 6 del archivo?

Saludos.-

**Comment by diegohcanetti** [comment]
Sería así el algoritmo Dami? Lo que tengo un poquito de dudas es con el calculo que hice del memcpy.

```
void buscar_bloque_a_leer() {

	//Bloque_que_quiero_leer
	uint32_t bloque_final = puntero_archivo/tam_bloque;

	//Bloque por donde empiezo a recorrer tabla_FAT
	uint32_t bloque_inicial = archivo_a_leer->bloque_inicial; 

	uint32_t indice = bloque_inicial;

	//Mientras no acceda al bloque_final o al EOF
 	while (tabla_fat_en_memoria[indice] != UINT32_MAX && tabla_fat_en_memoria[indice] != bloque_final) {		

	//Leemos el próximo bloque
	indice = tabla_fat_en_memoria[indice]; 
	}

	//El dato que se encuentra adentro del bloque final
	uint32_t dato_a_copiar = tabla_fat_en_memoria[indice];
	int tamanio = dato_a_copiar * tam_bloque;

	memcpy((char*)fat_mapeado + tamanio, contenido, tamanio); 
}
```
Después de realizar el memcpy tengo que hacer un msync? En el caso que haga falta me podrías por favor explicar la función y sus parámetros. Muchas gracias.

**Comment by iago64** [comment]
Buenas! Cómo va?

Vos con la cuenta de `puntero / tam_bloque` obtenes el número de bloque del archivo, es decir, que tenes que recorrer la tabla fat desde el bloque inicial del archivo y saltar tantas veces como te indica el número de bloque que acabas de obtener.

`msync()` no es necesario, es una función que frena el programa hasta que se sincronizan los cambios en el archivo, pero a fines del TP no hace falta.

Saludos.-
