### ISSUE TITLE
verificar si hay memory leaks y espera activa

### ISSUE THREAD

**Issue by Fcallero** [sisoputnfrba/foro#3329]
Buenas, una duda, como se van a fijar si hay memory leaks y espera activa? porque entiendo que no van a ejecutar con Valgrind, o si?

**Comment by tomasmartinez02** [comment]
Buenas! La espera activa y los memory leaks lo chequeamos con [htop](https://learn.microsoft.com/es-es/troubleshoot/developer/webapps/aspnetcore/practice-troubleshoot-linux/3-2-task-managers-top-htop#:~:text=Htop%20es%20un%20visor%20de,los%20procesos%20que%20se%20ejecutan.) que nos marca el uso de memoria y de CPU, las pruebas no se corren con valgrind.
La VM lo tiene incorporado y pueden probarlo abriendo una terminal con el comando `htop`.
Saludos.

**Comment by Fcallero** [comment]
ah okok, ahi veo que te indica el % de uso de cpu y de memoria, pero cuales serian parametros aceptables? por ejemplo si me tira en % de memoria me tira 0.5 seria aceptable o tiene que estar si o si en 0? (y la misma duda para la de CPU)

**Comment by nahuemazzeo** [comment]
Hola @Fcallero. La espera activa se indica con un sobre consumo del cpu en todo momento, osea con un porcentaje del 100% del cpu constante. Los memory leaks es con el aumento del consumo de memoria de tu proceso a traves del tiempo.

Con respecto a tu pregunta, no hay una medida aceptable. No deberia ocurrir ninguna de las dos. Con respecto a memory leaks dependiendo el nivel se ve mas cuando es mas grandes y es un posible gran strike con que mas sea el numero

Saludos.

**Comment by Fcallero** [comment]
ah buenisimo, muchas gracias
