### ISSUE TITLE
Duda orden en Prueba Integral

### ISSUE THREAD

**Issue by GuidoMartinez** [sisoputnfrba/foro#3331]
Buenas! 

Tenemos una duda sobre las pruebas integrales, segun el enunciado debemos correr lo siguiente en la consola:

Ejecutar los siguientes comandos en la consola del Kernel

- INICIAR_PLANIFICACION
- INICIAR_PROCESO INTEGRAL_A 128 10
- INICIAR_PROCESO INTEGRAL_B 128 5
- INICIAR_PROCESO INTEGRAL_C 64 1

Nos llama la atencion que tengamos que iniciar la plani y mientras estamos planificando sumemos procesos. Por lo que consultamos varias veces los sabados la idea de detener/iniciar plani es para poder facilitar la carga de procesos simplemente o modificar el grado de multi.

La primer instruccion deberia ser DETENER_PLANIFICACION y al final iniciarla? O es correcta la prueba?

Actualmente por como diseñamos la consola interactiva y la plani, no podemos podemos iniciar procesos con la planificacion activa. Opcionalmente podriamos:
`detener plani ->  iniciar_proceso INTEGRAL_A -> iniciar plani -> denter plani -> iniciar_proceso INTEGRAL_B   -> iniciar plani -> denter plani -> iniciar_proceso INTEGRAL_C  -> iniciar plani`

De esta manera al iniciar el INTEGRAL_B e iniciar la plani, desalojo al integral_a ya que B tiene mayor prioridad. Mismo caso al iniciar integral A desalojando a integral_b.

Podemos verificar el comportamiento esperado de esta manera?

Gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Lo vemos en la entrega, ya que es un comportamiento no esperado en la consola del Kernel, pero la consola en si misma no forma parte de los conceptos de la materia.

Saludos.-

**Comment by GuidoMartinez** [comment]
Perfecto Dami, lo vemos mañana en la entrega entonces!
Gracias
