### ISSUE TITLE
Prueba de DL, problemas que antes no teníamos

### ISSUE THREAD

**Issue by diegohcanetti** [sisoputnfrba/foro#3332]
La prueba de DL en el 3er checkpoint nos andaba perfecto, pero actualmente con los 2 archivos agregados a la cola de FIFO los archivos no tienen el tiempo suficiente para quedarse en DL, pero con las pruebas anteriores si quedaban en DL. Entonces actualmente, todos los procesos llegan a finalizar correctamente.

**Comment by iago64** [comment]
Buenas! Cómo va?

La prueba es la misma del checkpoint presencial, es decir, deberían ejecutarse los mismos 4 scripts de la prueba del check presencial y quedar en deadlock y despues se suman los 2 de las pruebas de error. Por las dudas, pregunto, están deteniendo la planificación como se indica en el enunciado? Y si detienen la planificación, la cola de NEW la manejan como un FIFO?

Saludos.-

**Comment by diegohcanetti** [comment]
Aaaa la idea es volver a hacer los 4 procesos y el finalizar el proceso 1. Después correr los otros 2 procesos y las pruebas de errores? Pq en ese caso entonces es que no se entendía bien la prueba.

**Comment by iago64** [comment]
La idea es que corran todos los procesos y veamos 4 en deadlock y los demas que finalizan por error.
