### ISSUE TITLE
Problema con el path del archivo de bloques

### ISSUE THREAD

**Issue by ParedesMicaela** [sisoputnfrba/foro#3335]
Buenas noches, estamos teniendo un error con el path de archivo de bloques. Esta variable global y el puntero al archivo (FILE* archivo_de_bloques) nunca se tocan pero en un momento se corrompe y escribe basura, es diferente de NULL.
 Ya nos fijamos y no hay memory leaks ni condiciones de carrera.

### 📝 Código relevante
Esta funcion la usamos cada vez que abrimos el archivo y anda en todas excepto en la funcion de swap.
```
FILE* levantar_archivo_bloque() {
	
    archivo_de_bloques = fopen(path_archivo_bloques, "rb+");

    if (path_archivo_bloques == NULL) {
        log_error(filesystem_logger, "No se pudo abrir el archivo.");
    }
	return archivo_de_bloques;
}
```

```
void swap_out(int pid, int nro_pagina)
{
    //no va a pasar que el bloque no exista
    archivo_de_bloques = levantar_archivo_bloque();
    if (archivo_de_bloques == NULL) {
        perror("Error al abrir el archivo de bloques de SWAP en swap out\n");
        return;
    }

    bloque_swap* bloque_a_leer = buscar_bloque_swap(nro_pagina, pid);

    while (fread(bloque_a_leer, sizeof(*bloque_a_leer), 1, archivo_de_bloques) == 1) {
        if (bloque_a_leer->nro_pagina == nro_pagina) {
            t_paquete* paquete = crear_paquete(PAGINA_PARA_ESCRITURA);
            agregar_entero_a_paquete(paquete, bloque_a_leer->nro_pagina);
            agregar_entero_a_paquete(paquete, bloque_a_leer->posicion_swap);
            agregar_entero_a_paquete(paquete, pid);

            enviar_paquete(paquete, socket_memoria);
            eliminar_paquete(paquete);
            break;
        }
    }

    fclose(archivo_de_bloques);
}
```

**Comment by iago64** [comment]
Buenas! Cómo va?

Un memory leak aca importa poco, lo que puede estar pasándoles es que estén pisando la memoria, porque en algún lado están mandando mal un tamaño en un `memcpy()` o están pasando mal alguna referencia, por ej en lugar de pasar un puntero pasan la dirección del puntero, ej:

```c
void * data = malloc(...);
memcpy(&data, ..., ...);
```

Por las dudas, eso en Valgrind les va a saltar como `invalid write of size X`, chequeen que no tengan alguno de esos mensajes.

Por otro lado, les dejo algunas preguntas:
¿Cómo están comprobando lo que escriben? 
Si repiten la prueba ¿Es el mismo error? es decir, ¿Escriben lo mismo si repiten la prueba en las mismas condiciones?

Saludos.-

**Comment by ParedesMicaela** [comment]
Teniamos un memory leak 😵. Ahi ya lo corregimos. Gracias!
