### ISSUE TITLE
Lock escritura bloquea participantes lock lectura

### ISSUE THREAD

**Issue by Mimito164** [sisoputnfrba/foro#3336]
Buenas, tengo una duda muy breve: 

Si un lock de escritura me bloquea todos los participantes del lock de lectura, ¿que debo hacer con los procesos que ya estaban bloqueados por otro motivo y tenían un lock de lectura?

¿Debería duplicar el pcb bloqueado? o ¿tendría que moverlo de lista de bloqueado? Ninguna de estas dos opciones me cierran.

### 📔 Citas del enunciado/videos

> Al momento en el que se active el lock de escritura se deben empezar a encolar todos los locks de lectura o escritura que se requieran para dicho archivo. Dicho lock se bloqueará hasta que se resuelvan todos los pedidos que participen en el lock de dicho archivo que ya se encontraban activos.

### 💭 Soluciones posibles

La ultima alternativa que es la que que mas me convence es no hacer nada, y en el momento en el que se desbloquee, verificar nuevamente si hay un lock de escritura, pero no se como hacer la transición, si pasaría de BLOCKED a READY y al momento de ejecutar verificar que hay un lock de escritura e ir a BLOCKED o si directamente pasa de BLOCKED a BLOCKED cambiando de lista de bloqueado.

Solamente para aclarar contextualizar, yo estoy manejando por un lado la listas pcbs bloqueados y por otro lado una cola de los locks de escritura y una lista de participantes en el lock de lectura. Si tengo que bloquear a un proceso, leo su pid de la cola de locks o la lista de participantes, busco el pcb y lo bloqueo.

Saludos.

**Comment by iago64** [comment]
Buenas! Cómo va?

Por suerte no hay pruebas tan rebuscadas, de hecho, están publicadas y podrías revisarlas para quedarte tranquilo.
Eventualmente la solución que propones de checkear una vez que te desbloqueas por el otro motivo sería el menos complejo de implementar.

Saludos.-

**Comment by Mimito164** [comment]
Muchas gracias por la respuesta. 
Le voy a pegar una buena revisada.
Cierro el Issue
