### ISSUE TITLE
Consulta tabla fat y archivo bloques

### ISSUE THREAD

**Issue by Bru-Nicolas-FRBA** [sisoputnfrba/foro#3337]
Buenas tardes profes.

Si la tabla fat contiene una referencia a la ocupacion de bloques ``` 0 - bloque - eof ``` 
Y el archivo de bloques esta dividido en ``` swap - fat ``` 

Esto significa que en las primeras referencias de la tabla fat van a ser de la particion SWAP? o Unicamente para la parte FAT?

**Comment by iago64** [comment]
Buenas! Cómo va?

La tabla FAT es solo para la parte de FAT, la partición de SWAP pueden administrarla como más cómodo les quede.

Saludos.-
