### ISSUE TITLE
Consulta lectura/escritura redundancia

### ISSUE THREAD

**Issue by Bru-Nicolas-FRBA** [sisoputnfrba/foro#3338]
Buenas tardes profes.

Una consulta respecto a la lectura/escritura

Nosotros en teoria recibimos por la instrucción el dato a escribir (uso el ejemplo de la consigna)
```
F_OPEN ARCHIVO W
F_TRUNCATE ARCHIVO 64
F_SEEK ARCHIVO 8
F_WRITE ARCHIVO 0
F_READ ARCHIVO 0
F_CLOSE ARCHIVO
``` 

Si nosotros tenemos el archivo de bloques ya creado e indexado, cuando truncamos el archivo nosotro ya usamos fwrite() y inicalizamos el valor del bloque con un "/0"

Mi duda radica en que cuando usamos el ``` fseek()``` , si nos posicionamos en el inicio del bloque. No deberíamos poder hacer un

``` fseek(archivo_bloques, (espacio_swap + bloque_inicial_archivo + bloque_a_leer/escribir))``` ?

Y una vez hecho esto simplemente hacemos ``` una vez verificados los locks obviamente)```  fread() o fwrite()

Me surgieron las siguientes dudas:

-La tabla fat en este aspecto en que ayudaria? Porque si ya el archivo de bloques esta indexado podriamos simplemente abrirlo e ir hacia la posicion del bloque para leer/escribir y realizar la accion

-En caso de tener que usar la tabla fat, no seria para verificar si el bloque ya esta escrito o no? Porque recuerdo en un checkpoint presencial haber escuchado que debemos reescribir un bloque si nos llega a tocar una instruccion como:
``` 
F_SEEK ARCHIVO 8
F_WRITE ARCHIVO 1
F_SEEK ARCHIVO 3
F_WRITE ARCHIVO 5
``` 

A todo esto una de las cosas que mas me dio miedo preguntar también es el hecho de utilizar la memoria para la devolver la direccion fisica. 

-De que manera nos sirve esta dirección si ya cuando creamos el archivo de bloques estamos dividiendo el archivo y podemos posicionarnos con en el fseek()??

(Mil disculpas por la cantidad de preguntas, pero una fue llevando a la otra)

**Comment by MartinSintas** [comment]
Buenas, siendo compañero del mismo grupo y debatiendo entre nosotros creo que comprendí(mos) un poco mejor como funciona el F_WRITE... viendo las pruebas de FS(más que nada la A,D y E) noté que antes de un F_WRITE "nombre_del_archivo" tenemos varios MOV_OUT.
Ahora repasando un poco el enunciado de tp (en la parte de CPU):
>MOV_OUT (Dirección Lógica, Registro): Lee el valor del Registro y lo escribe en la dirección física de memoria obtenida a partir de la Dirección Lógica.

yy un poquito de FS
>Escribir Archivo
Se deberá solicitar al módulo Memoria la información que se encuentra a partir de la dirección física recibida y se escribirá en el bloque correspondiente del archivo a partir del puntero recibido.

Entonces por lo que entiendo(llegamos a entender) con el F_WRITE nos van a estar pasando una, varias direcciones físicas donde allí se encuentran valores de registros, que dichos valores serán escritos en el archivo seleccionado. Es esto así o me estoy equivocando en algo?

Saludos y muchas gracias como siempre.

**Comment by iago64** [comment]
Buenas!

Que buena onda que debatan entre uds, ahora les sumo algo para el debate y medio que es la respuesta final:
En el TP se leen y escriben bloques completos, es por esto que casualmente los tamaños de bloque y página son iguales, para que asi como leen las páginas de SWAP para dárselas a memoria, también van a poder usar las mismas mismas funciones para hacer las lecturas y escrituras de los bloques de FAT.

Dicho lo anterior, les sumo algo mas por la pregunta de para que sirve la tabla FAT y es: **No se olviden de la teoría**, ya que uno de los objetivos del TP es, cito el enunciado:

> Mediante la realización de este trabajo se espera que el alumno: 
>>Afirme diversos conceptos teóricos de la materia mediante la implementación práctica de algunos de ellos.

Y pasado el heads up, les recuerdo que el hecho de que van a tener varios archivos y que van a tener que asignarles bloques cuando hagan un F_TRUNCATE que agrande el archivo, después la tabla FAT les va a servir para poder recorrer esos archivos y sabes cual es el segundo bloque, tercer bloque, cuarto bloque, quinto, etc, etc.

Saludos.-

**Comment by Bru-Nicolas-FRBA** [comment]
Muchas gracias profe, si llega a surgir otra duda de este estilo vuelvo a abrir este issue.
