### ISSUE TITLE
Duda con el bloque inicial

### ISSUE THREAD

**Issue by ParedesMicaela** [sisoputnfrba/foro#3339]
Buenas noches! Tenia la duda de si el bloque inicial es igual al puntero de la tabla de archivos de proceso. Estuve leyendo un par de issues y no entiendo si cuando se habla del puntero de tabla la de archivos de proceso, se habla del bloque inicial. De esto me surgieron 2 preguntas:

1. Cuando hago el f_seek tengo que actualizar el puntero o el bloque inicial? 

2. Por ejemplo nosotros cuando ejecutamos un f_write estamos haciendo esto. Seria correcto?😣😣:

```
void escribir_archivo(char* nombre_archivo, uint32_t puntero_archivo, void* contenido){
	
	fcb* archivo_a_leer = levantar_fcb (nombre_archivo);

	uint32_t bloque_inicial = archivo_a_leer->bloque_inicial; 
	uint32_t bloque_a_escribir = puntero_archivo/tam_bloque;
	free(archivo_a_leer);

	escribir_contenido_en_bloque(bloque_a_escribir,bloque_inicial, contenido);
}


void escribir_contenido_en_bloque(uint32_t bloque_a_escribir, uint32_t bloque_inicial, void* contenido) {
	
	uint32_t nro_bloque = buscar_bloque_en_FAT(bloque_a_escribir, bloque_inicial);

	escribir_contenido_en_archivo(nro_bloque, contenido);
}

static uint32_t buscar_bloque_en_FAT(uint32_t cantidad_bloques_a_leer, uint32_t bloque_inicial)
{
	uint32_t nro_bloque = 0;

	int retardo = config_valores_filesystem.retardo_acceso_fat;

	uint32_t indice = bloque_inicial; 

	for (int i = 0; i < cantidad_bloques_a_leer; i++) {
		usleep(1000* retardo);
		cantidad_bloques_a_leer = tabla_fat_en_memoria[i];
	}

	//El indice que cumple la condicion, es donde está el dato
	nro_bloque = cantidad_bloques_a_leer;
	
	return nro_bloque;
}

static void escribir_contenido_en_archivo (uint32_t nro_bloque, void* contenido) {

	int retardo = config_valores_filesystem.retardo_acceso_bloque;

	uint32_t direccion_bloque = tam_bloque * nro_bloque;

	uint32_t offset = direccion_bloque + tamanio_swap;
	
	//Abrimos archivo
	archivo_de_bloques = levantar_archivo_bloque();

	//Nos posicionamos en el dato
	fseek(archivo_de_bloques, offset, SEEK_SET);

	usleep(1000* retardo);
	fwrite(contenido, tam_bloque, 1, archivo_de_bloques);

	mem_hexdump(contenido, sizeof(contenido));
}
```

**Comment by iago64** [comment]
Buenas! Cómo va?

El bloque inicial está en el FCB, el puntero lo podés ver como el byte a partir del cual queres leer / escribir en el archivo.
Aclarado el error:

1.- Cito al enunciado:

> **F_SEEK** (Nombre Archivo, Posición): Esta instrucción solicita al kernel actualizar el puntero del archivo a la posición pasada por parámetro.

2.- Menos miedo y validaciones de si el código está bien y más prueba y error, perdón si la respuesta es medio corta mambo, pero los ayudantes no somos compiladores humanos, entonces, van a sacarle más provecho a una prueba de su propio código que a una respuesta de un ayudante que puede comerse un detalle y decirles si anda o no.
La forma facil de probar el FS, es ejecutando el script FS_A de las pruebas y una vez que termina validar que en el `hexdump -C` del archivo de bloques ven que tiene 2 palabras... XBOX y SONY, porque si, las pruebas son con números de caracteres ascii para poder leer algo en el dump en hexa y que sea mucho mas simple de corregir.

Saludos.-

**Comment by ParedesMicaela** [comment]
Buenas! Ahi modificamos el algoritmo con lo que me dijiste y me imprimio esto:
![Imagen de WhatsApp 2023-12-11 a las 08 22 50_b23b5406](https://github.com/sisoputnfrba/foro/assets/83614884/b849fdfb-e85a-49a4-96d7-74cf77a65188)

Viendolo por encima. Esto puede ser un error del truncar o del escribir? 😓
/

**Comment by LeandroCarbajales** [comment]
Buenas!
No se llega a leer el comando de la terminal, pero puede ser que estés imprimiendo el hexdump del archivo `consolas.fcb` en lugar de al archivo de bloques?

**Comment by ParedesMicaela** [comment]
Ayy estabamos cansados, tenes razón Lean 😅😅

Esto se consideraría correcto o tiene que salir perfecto? En el caso que no se considere perfecto hay alguna manera de testear el Filesystem y la memoria (y el paquete con el contenido) para saber donde está el error, pq eso es lo que nos está constando más trabajo saber como hacer. Ya que más allá de que usemos hexdump en todos los puntos donde lo usamos no vimos basura.
![sony_xbox](https://github.com/sisoputnfrba/foro/assets/83614884/cd7ec82a-a613-4c2a-80ba-38de35b6b3f4)

**Comment by iago64** [comment]
Buenas! No soy Lean pero creo que puedo responder.

En principio parece estar ok, lo que me llama la atención es que tenes una BANDA de espacio entre un bloque y el otro.
Por las dudas prueben de iniciar con un FS limpio y vean, porque el truncate del archivo debería dejarles bloques contiguos si no hay nadie mas reservando bloques en ese momento.

Saludos.-

**Comment by ParedesMicaela** [comment]
Perfectoo muchas gracias! Vamos a empezar a ver eso 👌
