### ISSUE TITLE
apertura archivo de tabla FAT

### ISSUE THREAD

**Issue by Jcleosenco** [sisoputnfrba/foro#3340]
Buenas, como va? 
"Si al iniciar el FS, no se encuentra el archivo de la tabla FAT, se deberá crear el mismo e inicializarlo con todos valores en 0 que representará que dicho bloque lógico está libre."
Mi duda es: se puede presentar el caso en el que ya haya una fat inicializada con bloques ocupados?
Muchas gracias.

**Comment by iago64** [comment]
Buenas! Cómo va?

Si, de hecho es la idea de tener un FileSystem, que se pueda apagar y cuando se vuelva a encender todo este ahi tal cual se dejo cuando se apagó.

Saludos.-
