### ISSUE TITLE
Truncar 

### ISSUE THREAD

**Issue by diegohcanetti** [sisoputnfrba/foro#3342]
A la hora de truncar el archivo de bloques tenemos que considerar todo el archivo? O deberíamos truncar solo la parte de FAT?

### 📔 Citas del enunciado/videos
```
Truncar Archivo
Al momento de truncar un archivo, pueden ocurrir 2 situaciones: 
Ampliar el tamaño del archivo: Al momento de ampliar el tamaño del archivo deberá actualizar el tamaño del archivo en el FCB y se le deberán asignar tantos bloques como sea necesario para poder direccionar el nuevo tamaño.
Reducir el tamaño del archivo: Se deberá asignar el nuevo tamaño del archivo en el FCB y se deberán marcar como libres todos los bloques que ya no sean necesarios para direccionar el tamaño del archivo (descartando desde el final del archivo hacia el principio).
Siempre se van a poder truncar archivos para ampliarlos, no se realizará la prueba de llenar el FS.
```

**Comment by iago64** [comment]
Buenas! Cómo va?

Lo que se truncan son los archivos dentro del FS, no el archivo de bloques.

Saludos.-

**Comment by Bru-Nicolas-FRBA** [comment]
Buenas!

Entonces únicamente al truncar cambiamos
-El fcb con el tamanio nuevo
-La tabla FAT con la asignación de bloques (0/num_siguiente/EOF) correspondiente al archivo y a su bloque incial
-El archivo de bloques (la parte FAT) con el ' \0 ' en cada bloque libre correspondiente al archivo, no?

**Comment by iago64** [comment]
Buenas!

Si, recuerden que al momento de ampliar el archivo, van a tener que asignar bloques nuevos en la tabla FAT (no se la compliquen mucho en como asignarlos, si buscan el primer bloque libre esta perfecto)

El tema de los '\0' es solo para SWAP, para los archivos no se compliquen tanto, total en las pruebas sobreescribimos los bloques.

Saludos.-

**Comment by diegohcanetti** [comment]
Muchas gracias! Dami
