### ISSUE TITLE
Duda sobre Page Faults concurrente

### ISSUE THREAD

**Issue by Mimito164** [sisoputnfrba/foro#3344]
Buenas tardes,

Para manejar el mensaje de page fault (PF de ahora en mas) recibido por la CPU, el kernel debe hacer una hilo para resolver este problema.

Si tengo que crear un hilo exclusivamente para resolver el PF, ¿No me convendría abrir un socket y crear un hilo del lado de la memoria que resuelva este problema o desde el lado de memoria ir encolando las peticiones de PF? Mas que nada porque me soluciona algunos problemas de sección critica con el socket a cambio de crear un par mas de hilos, ademas no es algo que no hayamos implementado ya...  ¿Que le hace una raya mas al tigre?

Saludos.

**Comment by diegohcanetti** [comment]
No soy un ayudante, pero si puedes implementar un hilo con detach que atienda esa peticion.  No se a que te refieres con abrir un socket ya que el kernel desde el comienzo puede abrir un socket hacia memoria que lo puedes utilizar en todo el kernel de manera "global".

Recuerda que los paso del PF son:
1.- CPU hace MMU.
2.- Memoria le dice que no esta cargada la pagina.
3.-CPU le avisa al Kernel que hay PF.
4.- Kernel mueve al proceso al estado Bloqueado. Este estado bloqueado será **independiente** de todos los demás ya que solo afecta al proceso y no compromete recursos compartidos.
5.- Kernel solicita a memoria que se cargue en memoria principal la página correspondiente, esta la obtuviste del CPU.
6.- El Kernel espera la respuesta del módulo memoria.
7.- La memoria le pide al FS la pagina.
8.- La memoria carga la pagina y le avisa a la Kernel.
4.- El Kernel al recibir la respuesta del módulo memoria, desbloquea el proceso y lo encola en la cola de ready.

**Comment by iago64** [comment]
Buenas! Cómo va?

Si quieren crear un hilo por cada petición de PF y resolverla individualmente no hay ningún problema, de hecho, es lo mas simple y aislado que pueden armar :wink:

Saludos.
