### ISSUE TITLE
Duda sobre las pruebas de memoria

### ISSUE THREAD

**Issue by ParedesMicaela** [sisoputnfrba/foro#3345]
Buenas! Estaba corriendo las pruebas de memoria y cuando tengo que hacer la segunda parte de la prueba, donde bajo el grado de multiprogramación a 1 y vuelvo a correr los procesos, se queda ejecutando el proceso 1 en un bucle por el JNZ. Eso es correcto? 

### 📔 Citas del documento de pruebas
SET CX 20
SET AX 1
MOV_OUT 0 CX
MOV_OUT 16 CX
MOV_OUT 32 CX
MOV_OUT 48 CX
SUB CX AX
JNZ CX 2
EXIT

**Comment by iago64** [comment]
Buenas! Cómo va?

El JNZ lo que hace es volver a la instrucción 2 y después de 20 vueltas debería finalizar ya que en CX terminas teniendo el valor 0.

Saludos.-

**Comment by ParedesMicaela** [comment]
AA entonces cuando el SUB hace una resta y el registro al que le estoy restando llega a 0, tengo que mandar a finalizar el proceso? Porque yo había preguntado hace tiempo que pasaba si en el SUB me daba un numero negativo pero nunca me dijeron que había que finalizar el proceso y tampoco lo vi en la consigna. Capaz se me pasó. Si es así lo cambio ya mismo.

**Comment by LeandroCarbajales** [comment]
El SUB nunca debería llegar a un número negativo, la idea es que el JNZ te cambia el PC solamente si (en este caso) el registro CX vale 0, siendo que el registro CX comienza en 20 y se le resta 1 en cada iteración, luego de 20 vueltas el JNZ no haría nada y por lo tanto la próxima instrucción a ejecutar sería el EXIT.

**Comment by ParedesMicaela** [comment]
Claroo ahí está, gracias. Ahi ya lo cambie✨✨
