### ISSUE TITLE
Significado de Memoria llena

### ISSUE THREAD

**Issue by diegohcanetti** [sisoputnfrba/foro#3347]
Estabamos realizando la 3er prueba y nos dio una duda. Al mencionar que la memoria llena significa que ya no entra más paginas`(cantidad_max_paginas = tam_memoria/tam_pagina`) y que no haya marcos libres? O solamente la condición del espacio, ya que el enunciado no especifíca si no hay marcos libres.

### 📔 Citas del enunciado/videos
>En caso de que la memoria principal se encuentre llena, se deberá seleccionar una página víctima utilizando el algoritmo de reemplazo. Si la víctima se encuentra modificada, se deberá previamente escribir en SWAP.

**Comment by iago64** [comment]
Buenas! Cómo va?

La idea es que con la prueba se ocupan todos los marcos y después empiezan a producirse los reemplazos.

Saludos.-

**Comment by diegohcanetti** [comment]
Aaa perfecto entonces solo tenemos en cuento los marcos. Gracias.
