### ISSUE TITLE
Pregun(ton)ta sobre INICIAR/FINALIZAR PROCESO filesystem

### ISSUE THREAD

**Issue by MartinSintas** [sisoputnfrba/foro#3348]
Buenas :D tengo una duda medio sonsa pero quiero saber si lo que estoy pensando es correcto o me estoy equivocando...
Supongamos que tenemos una instrucción que se llame "INICIAR_PROCESO mate_amargo 64 1" siendo 64 el tamaño del proceso y 1 la prioridad (aunque no es relevante para la pregunta). Si yo tengo de filesystem.config->tam_bloque = 16, eso significa que le voy a asignar 4 bloques de swap? (ya que 64/16 = 4)
Si es así entonces intuyo que al finalizar le libero los bloques SWAP  ya asignados anteriormente al proceso

Desde ya muchas gracias :D

**Comment by LeandroCarbajales** [comment]
Buenas!
Exactamente, como indica el enunciado (módulo Memoria):

> Creación de proceso
El módulo deberá crear las estructuras administrativas necesarias y notificar al módulo FS para que nos asigne un bloque de SWAP para cada página del proceso.

Si tu proceso es de 64 bytes, y tus páginas de 16 bytes. Podés pensar a tu proceso como si estuviera "dividido" en 4 páginas, por lo que deberías asignarle 4 bloques de swap.

Te aclara la duda?
Saludos!
        Lean

**Comment by MartinSintas** [comment]
si, perfecto Lean muchísimas gracias
