### ISSUE TITLE
Duda con el fwrite de \0

### ISSUE THREAD

**Issue by MartoSimon** [sisoputnfrba/foro#3349]
Buenas, tenia una duda respecto al tamaño que tenemos que pasarle a fwrite cuando tenemos que reservar los bloques de la SWAP, donde tenemos que poner "\0" segun la consigna en los bloques que tenemos que reservar. 

Tambien les queria preguntar sobre el tema del path del fcb. Porque no terminamos de entender si hace referencia a un archivo FCB o si marca la carpeta en donde deberian estar guardados, ya que si hace referencia a un archivo, no entendemos por que se pasa tambien el nombre de un fcb en las instrucciones.

### 📝 Código relevante
Este es el codigo que tenemos hecho al momento de asignar los bloques. De esta forma estamos poniendo \0 en los bytes del bloque libre. La duda que tenemos es que nosotros en el fwrite usamos sizeof(uint8_t) ya que son bytes, pero en este caso estamos poniendo un char. Que tendriamos que hacer en este caso?

```
fseek(bloques, (i * file_config.tam_bloque) * sizeof(uint8_t), SEEK_SET);
fwrite("/0", sizeof(uint8_t), 1, bloques);
```

Saludos

**Comment by iago64** [comment]
Buenas! cómo va?

En principio el fwrite esta bien, salvo que la cantidad de elementos no es 1, si no que debería ser tamaño_bloque, ya que uds estan escribiendo 1 byte :)

Saludos.-

**Comment by MartoSimon** [comment]
Muchas gracias, quedo claro

Saludos!
