### ISSUE TITLE
Duda creacion y escritura archivo binario

### ISSUE THREAD

**Issue by pepinony** [sisoputnfrba/foro#3350]
Buenas, ya tenemos todos los test corriendo pero nos quedaron haciendo ruido tres cosas de los archivos binarios:
1. Cuando se crean por primera vez pesan lo que "tienen" que pesar sea la FAT o el archivo de bloques (catEntradas*sizeof(uint32_t) y cantBloques*tamBloques), pero los archivos tienen mas bloques/entradas de los que tendrian que tener.
2. Cuando se corre el FS_D para el archivo fibonacci se escriben bien todos los números con el detalles que los dos ultimos numeros (377 y 610) en hexa los esta escribiendo 79 1 y 62 2 respectivamente.
3. Cuando corremos el archivo FS_E termina escrito NINTENED, en las lineas 24 y 25 del mismo se hacen un mov out de los registros AX y CX pero en las lineas 19 y 18 se hacen los set con los valores ASCII para la D y O en los registros CX y DX, puede ser que las pruebas estén mal?

### 📝 Código relevante
```
F_WRITE consolas 0
SET AX 69
SET BX 78
SET CX 68
SET DX 79
F_SEEK consolas 16
F_READ consolas 16
MOV_OUT 16 AX
MOV_OUT 20 BX
MOV_OUT 24 AX
MOV_OUT 28 CX
F_WRITE consolas 16
F_CLOSE consolas
EXIT
```
```
int offset_puntero_archivo(int punteroArchivo, char *nombreArchivo) {
  char *path = path_FCB(nombreArchivo);
  t_fcb *fcb = leer_archivo_fcb(path);
  int bloqueLogico = calcular_bloques(punteroArchivo);
  int bloqueEnFAT = fcb->bloqueInicial;

  sem_wait(&sem_FAT);
  for (int i = 0; i < bloqueLogico; i++) {
    if ((i + 1 != bloqueLogico) ||
        i == 0) { // Para el caso de que sea el primer bloque
      log_trace(logger,
                "Acceso FAT - Entrada: %d - Valor: %d (Buscando el bloque por "
                "el puntero de archivo)",
                bloqueEnFAT, tabla_FAT->entradas[bloqueEnFAT]);
      bloqueEnFAT = tabla_FAT->entradas[bloqueEnFAT];
    }
  }
  sem_post(&sem_FAT);

  int offset =
      (bloqueEnFAT + archivo_bloques->cantSWAP) * archivo_bloques->tamBloque;

  free(path);
  free(fcb->nombreArchivo);
  free(fcb);
  return offset;
}
```
```
void actualizar_archivo_bloques(void *info, long offset) {
  FILE *archivo = fopen("file_blocks", "rb+");
  sem_wait(&sem_bloques);
  size_t tamBloque = archivo_bloques->tamBloque;
  sem_post(&sem_bloques);
  void *buffer = malloc(tamBloque);
  memcpy(buffer, info, tamBloque);
  if (fseek(archivo, offset, SEEK_SET) != 0) {
    log_error(logger, "Error al establecer la posición del puntero de archivo");
    fclose(archivo);
    return;
  }

  size_t bytesEscritos = fwrite(buffer, tamBloque, 1, archivo);

  free(buffer);
  fclose(archivo);
}
```
```
void crear_archivo_bloques(t_log *logger) {

  FILE *archivo = fopen("file_blocks", "wb");

  if (archivo == NULL) {
    log_error(logger, "Error al crear el archivo");
    return;
  }

  // Seteo todas las entradas con bloques vacios
  sem_wait(&sem_bloques);
  size_t cantBloque = archivo_bloques->cantFAT + archivo_bloques->cantSWAP;
  size_t tamBloque = archivo_bloques->tamBloque;
  sem_post(&sem_bloques);

  size_t tamanioTotal = (cantBloque * tamBloque);
  void *buffer = (void *)calloc(cantBloque, tamBloque);

  size_t prueba = fwrite(buffer, tamBloque, cantBloque, archivo);
  if (prueba == cantBloque * tamBloque) {
    log_error(logger, "Error al crear archivo de bloques");
  }
  free(buffer);
  fclose(archivo);
}
```
### 💻 Logs
Cuando lo corro con Valgrind no me tira nada.
![image](https://github.com/sisoputnfrba/foro/assets/102746551/b8e8b2ae-b93b-4cb2-ba47-96c7faffa3c2)
El FS_A en cambio si escribe bien 
![image](https://github.com/sisoputnfrba/foro/assets/102746551/a2265706-f15c-4af7-a241-cd8ee9d7a462)

**Comment by diegohcanetti** [comment]
Hola buenas no soy ayudante, pero a cuando levantan los archivos desde 0 les da esta cantidad de espacio?

![image](https://github.com/sisoputnfrba/foro/assets/102698705/1f0a5a64-5ba3-4319-a425-0ab1177477f3)

**Comment by diegohcanetti** [comment]
Igual primero borra tus archivos, corre la memoria y el filesystem. Ahí realiza el hexdump, con los archivos en "blanco". Para ver con que tamaño creas inicialmente los archivos, sin realizar ninguna prueba ni nada.

**Comment by pepinony** [comment]
Ahora no estoy en mi casa, pero el archivo de bloques lo crea como con F100h entradas y la FAT con muchas mas de 3072d

**Comment by iago64** [comment]
Buenas!

Repasando un poco el issue.
@pepinony lo que estas imprimiento en el archivo de bloques pareciera estar bien, importante hace la prueba con los archivos limpios.

Saludos.-

**Comment by pepinony** [comment]
Hola dami como andas? Todas las pruebas de escritura las hacemos borrando todos los archivos, las pruebas estan dado bien pero con unos detalles.
1. En el FS_E escribe NINTENED, pero si cambio los ulimos dos MOV OUT para que sean sobre el registro CX y DX respectivamente imprime NINTENDO.
2. En la INTEGRAL_B escribe PRAISE THE SU, pero cuando agrego un MOV OUT 52 AX entre el ultimo SET (linea 29) y el primer F_SEEK (linea 30), imprime PRAISE THE SUN

**Comment by iago64** [comment]
Buenas!

@pepinony Estan perfectos esos resultados que estás viendo.

Saludos.-

**Comment by pepinony** [comment]
Dale buenisimo, gracias!
