### ISSUE TITLE
El hilo me ta mandando cualquier cosa, ayuda

### ISSUE THREAD

**Issue by Bru-Nicolas-FRBA** [sisoputnfrba/foro#3351]
Buenas tardes, tenia una consulta de como poder solucionar un problema

La verdad es que no tengo la menor idea de porque puede estar pasando esto:

Planteo:

-Tengo una estructura ```t_pcb``` rellena con datos del proceso.
-Mandamos esa estructura a ejecutarse en una funcion ```atender_peticiones_al_fs``` dentro de un un ```hilo```
-Al hilo apenas lo creamos le hacemos ```detach```

Problema:
El problema surge que el proceso en la ejecucion tiene una variable llamada ```motivo_bloqueo```, esta variable se nos corrompe o no se que pingo y nos esta llegando un dato erroneo al hilo.

![image](https://github.com/sisoputnfrba/foro/assets/82009198/005b602f-7e97-47ef-9f61-56912909954d)
(perdon por la captura, pero no podia copiar ese mensaje con esos simbolos)

Cuando mandamos al hilo a ejecutar hacemos esto:
```c
 if (!pthread_create(&peticiones_fs, NULL, (void *)atender_peticiones_al_fs, (void *)proceso)){
            pthread_detach(peticiones_fs);
            //log_info(kernel_logger, "Mandamos a atender la peticion al fs, creamoe l hilo e hicimos detach\n");
        } else {
            log_error(kernel_logger,"Error en la creacion de hilo para realizar %s\n", proceso->motivo_bloqueo);
            abort();
        }
```

Tambien probe esto, pero tampoco funciona:
```c
pthread_create(&peticiones_fs, NULL, (void *)atender_peticiones_al_fs, (void *)proceso);
pthread_detach(peticiones_fs);
```

**Comment by Bru-Nicolas-FRBA** [comment]
Agrego a la pregunta, porque creo que esto es que se nos esta rompiendo el dato:

- Pasar de un hilo a otro puede corromper los datos?
- Se puede mandar mas de un parámetro a un hilo?
- Capaz tenemos que mandar otro parámetro?

**Comment by LeandroCarbajales** [comment]
Buenas!
Pudieron debuggear (o printear) el valor de este ```proceso->motivo_bloqueo``` justo antes y después de crear el hilo para corroborar que el problema esté al pasarlo al el otro hilo? Siendo un char* es fácil a veces equivocarse con alguna asignación, etc.

Para responder brevemente a las preguntas:
``` Pasar de un hilo a otro puede corromper los datos? ```
No.
```Se puede mandar mas de un parámetro a un hilo?```
No, pero siempre pueden crear una estructura nueva que tenga todos los datos/parámetros que necesiten localmente en el hilo nuevo.
```Capaz tenemos que mandar otro parámetro?```
A efectos prácticos podrían no mandar nada y sacar el pcb en cuestión de alguna variable/lista global.

**Comment by Bru-Nicolas-FRBA** [comment]
Muchas gracias profe, justo hace unos minutos intente guardarlo antes de una variable global y pudo reconocerlo.

Si llego a tener otro problema de este estilo reabro el hilo, gracias nuevamente
