### ISSUE TITLE
Duda del log Acceso a Bloque a Archivo

### ISSUE THREAD

**Issue by Gaston-Erazo18** [sisoputnfrba/foro#3353]
Nos surgió una duda de que valor tendría que ir en <NUMERO_BLOQUE_FS> si tenemos que poner el numero de bloque teniendo en cuenta los bloques de SWAP (contando los bloques desde el principio del archivo de bloques) o el numero de bloque que corresponde a la entrada FAT.

### 📔 Citas del enunciado/videos
```
“Acceso Bloque - Archivo: <NOMBRE_ARCHIVO> - Bloque Archivo:
<NUMERO_BLOQUE_ARCHIVO> - Bloque FS: <NUMERO_BLOQUE_FS>”
```

**Comment by iago64** [comment]
Buenas! Como va?

Es indistinto, total el número de bloques de swap lo tenemos y podemos hacer la cuenta.

Saludos.-

**Comment by Gaston-Erazo18** [comment]
Ok, muchas gracias.
