### ISSUE TITLE
Duda sobre F_WRITE , log de FAT y mmap()

### ISSUE THREAD

**Issue by Luca-Aiello** [sisoputnfrba/foro#3355]
1- Buenas como va? Tengo una duda sobre el funcionamiento del F_WRITE, se supone que  Kernel le manda a File System el nombre del archivo , el puntero que tiene el proceso al archivo y la dirección física recibida de CPU. En File System se le debe solicitar a Memoria que le envie el contenido de esa dirección fisica y luego cuando File System recibe esa información escribirla en la dirección del puntero del proceso al archivo(el recibido por Kernel) . La dudas es, si ese es el funcionamiento correcto y si la inforamción recibida de Memoria es equivalente al tamaño del bloque.

2- Otra duda con respecto a File System y Kernel, se supone que File System atiende las peticiones de a 1? Es decir, en el caso de que un proceso (P1) haya realizado un F_WRITE, este pasa a estar en el estado BLOCKED, se le envía a CPU otro proceso (P2) , y este último ejecuta un F_READ, Kernel debe enviar la petición o tiene que esperar a que File System finalice la petición de P1 , para luego ejecutar la petición de P2.

3- Otra consulta con respecto al log del Wait. Cuando un proceso ejecuta un WAIT y ese recurso no tiene mas instancias por lo tanto el proceso pasa al estado BLOCKED, el log a realizar del WAIT se realiza igualmente? 
Sería algo asi: Wait: “PID: <PID> - Wait: <NOMBRE RECURSO> - Instancias: <INSTANCIAS RECURSO>”
En caso de que no sea así, debe realizarse el log de esta petición cuando el proceso que tiene este recurso realice un SIGNAL, es decir, si un proceso (P1) realiza un SIGNAL del recurso R_2 , y el proceso (P2) se encuentra primero en su lista de bloqueados, luego de liberar ese recurso R_2 , se lo asignamos a P2 y ahi ejecutamos el WAIT correspondiente de P2?
Sería: “PID: 1 - Signal: R_2 - Instancias: 1” 
Wait: “PID: 2 - Wait: R_2 - Instancias: 0”
“PID: 2 - Estado Anterior: BLOCKED - Estado Actual: READY"

### 📔 Citas del enunciado/videos

Para el caso de 1 y 2:
![Captura de pantalla 2023-12-13 212238](https://github.com/sisoputnfrba/foro/assets/129466268/4a9d5f7a-a703-4d1e-8078-45334084671a)

Para 3:
![wait](https://github.com/sisoputnfrba/foro/assets/129466268/03d0c05a-b0d2-4cec-abca-a8dd3e084431)

**Comment by iago64** [comment]
Buenas! Cómo va?

Gracias por nomerar las preguntas, paso a contestarlas:

1.- Si, la idea es que siempre copien bloques / páginas enteras y ambos van a tener siempre el mismo tamaño.

2.- No, justamente el FS tiene que poder atender peticiones en paralelo, es parte de los lineamientos de implementación:

> Para su implementación, deberá ser un proceso multihilo capaz de atender todas las peticiones de manera concurrente, a tales efectos, se recomienda implementar cada petición como una conexión nueva.

3.- Si, hagan el log aunque se bloquee el proceso.

Saludos.-

**Comment by Luca-Aiello** [comment]
Genial gracias por responder tan rápido, y eso quedo claro. Ahora surgieron otras dudas:
1- Es necesario logear el acceso a la FAT por cada entrada de la tabla. Porque nosotros utilizamos un for para recorrer la FAT hasta encontrar lo que necesitamos, y en cada iteracion de ese for logeamos el acceso a la FAT. Un ejemplo sería:

	while(tablaFatEnMemoria[i] != EOF_FS){
		log_info(filesystem_log_obligatorio, "Acceso FAT - Entrada: <%d> - Valor: <%d>", i, tablaFatEnMemoria[i]);
		usleep(RETARDO_ACCESO_FAT);
		i = tablaFatEnMemoria[i];
		*aux = i;
	}

2- Otra duda relacioanda con el mmap() , es necesario utilizar el munmap(), ya que nosotros cuando inicializamos el modulo de File System cargamos a memoria la tabla FAT, la particion SWAP y la particion FAT, y trabajamos con esto en todo el módulo, como se supone que utilizando el memcpy() escrbimos/leemos de lo mapeado y solo usamos el fclose() al finalizar el módulo, no sabemos si es necesario desmapearlo.

**Comment by LeandroCarbajales** [comment]
Buenas!

1- Sí! Es el comportamiento esperado justamente para corroborar la cantidad de accesos a la tabla para encontrar un bloque.

2- Viendo la documentacion de munmap() dice:
`The region is also automatically unmapped when the process is terminated. On the other hand, closing the file descriptor does not unmap the region. `
Es decir, cerrar el archivo no deshace el mapeo, pero de cualquier forma al finalizar el proceso el mapeo se deshace automáticamente.

Saludos!
     Lean

**Comment by iago64** [comment]
Buenas!

Para sumar un poco a lo que comenta Lean, la gracia de `mmap()` es que uds lo pueden usar para como es el tp, levantar un "archivo de bloques" o "una tabla fat", pero en realidad tiene muchísimos usos muy zarpados que nosotros no nos acercamos, por eso que hay también funciones como `msync()` para forzar a que el hilo se bloquee esperando que se sincronicen los cambios entre el archivo y la memoria o `munmap()` que sirve para liberar el mapeo y por lo tanto no consumir tanta memoria en tu proceso.

Por lo dicho antes, no se calienten por `msync()` o `munmap()`, mientras que después de que pasa algo tiran un `hexdump -C` o un `xxd` sobre el archivo y se ven los cambios, estamos de 10

Saludos.-

**Comment by Luca-Aiello** [comment]
Gracias Lean y Damian , quedo todo clarisimo. Cierro el issue :)
