### ISSUE TITLE
Prueba de laboratorio

### ISSUE THREAD

**Issue by matibrewda** [sisoputnfrba/foro#3356]
Buenas, como hago para reservar un turno para ir mañana (u hoy si lo leen el viernes) a probar el tp en medrano? puedo ir sin turno?

Ya que estamos otra consulta, para el tp utilizamos la syscall chmod para que otorgar permisos y poder utilizar el archivo. Podriamos llegar a tener problemas a la hora de correr pruebas?

**Comment by tomasmartinez02** [comment]
Buenas! No hay que sacar turno para simular la prueba en los laboratorios, normalmente están abiertos solamente tienen que avisar ahí y pueden pasar. Por el chmod seguramente lo utilizaron para los archivos .sh o similares y no hay problema, son necesarios para que los puedan ejecutar.
Saludos!

**Comment by matibrewda** [comment]
el chmod lo utilizamos para los archivos binarios en filesystem, esta ok igual?

**Comment by iago64** [comment]
Buenas! Cómo va?

Lo único que **no esta permitido** es correr el tp con `sudo`, pero después pueden tirar todos los `chmod` que necesiten.

Saludos.-
