### ISSUE TITLE
Duda Tabla FAT

### ISSUE THREAD

**Issue by Federico-Baez** [sisoputnfrba/foro#3357]
Hola buenas! con mi grupo nos surgieron 2 dudas respecto a la tabla FAT
1. En primer lugar, seria suficiente asignarle valor de EOF a la primer posicion de la tabla, para poder cumplir con la parte del enunciado que dice que este bloque no debe ser asignado a ningun archivo?
![image](https://github.com/sisoputnfrba/foro/assets/67663140/f4d6299e-d003-4ce8-964e-c86762a432a8)

2. La otra duda era a la hora de buscar entradas libres en la fat, deberiamos primero buscarlos todos(generando un log de acceso FAT hasta que se encuentren todas las entradas) y luego actualizar la tabla(generarando ahora un log de acceso FAT hasta que se actualicen todas)?

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Mientras ese primer bloque no se lo asignen a nada esta bien, pueden simplemente empezar a contar desde el bloque 1 en lugar del 0 y listo, pero sean felices con ese punto :)

2.- La primer parte si, van a loguear todos los accesos, en la segunda uds ya tienen el indice de la tabla fat, asi que ahi solo sería 1 mas para marcar el nuevo valor.

Saludos.-

**Comment by Federico-Baez** [comment]
1. Genial muchas gracias

2. con respecto a esto no me queda muy claro, por ejemplo en el caso de truncar un archivo, que me solicita 4 bloques más, primero no serian todos los accesos hasta encontrar los libres, y luego no serian otros 4 para actualizar cada una de las posiciones?

**Comment by iago64** [comment]
Buenas!

2.- Si, tendrias los accesos para buscar el bloque libre + 1 para el cambio del dato en la posicion de la fat y eso tantas veces como bloques que tengas que agregar al archivo.

Saludos.-

**Comment by Federico-Baez** [comment]
perfecto, muchas gracias!
