### ISSUE TITLE
Consulta sobre archivos filesystem

### ISSUE THREAD

**Issue by liliperalta** [sisoputnfrba/foro#3359]
Buenas,
  Tenemos una consulta sobre las pruebas. Entre cada set de pruebas,  por ejemplo finaliza el de memoria, y cuando arranquemos con la siguiente de filesystem, los archivos deben arrancar desde 0 ?, asignando el primer bloque del archivo según la nueva configuración?

Gracias.
Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

En principio no tienen que hacer nada con los archivos del FS, solo para la prueba de FS posiblemente les pidamos que limpien los archivos para que sea mas facil validar que escriben bien las cosas y que no tengamos un scroll infinito con los dumps en hexadecimal.

Saludos.-

**Comment by liliperalta** [comment]
Muchas gracias!!
