### ISSUE TITLE
Escritura rara en archivo de bloques

### ISSUE THREAD

**Issue by MartoSimon** [sisoputnfrba/foro#3363]
Buenaas, perdon por la hora, haciendo las pruebas de filesystem, al momento de reservar los bloques de SWAP para mandarselos a memoria me escribe TamanioBloque. El codigo es parte del reservarBloquesSwap

### 📝 Código relevante

```
           if (contador == file_config.tam_bloque){
            		uint32_t* bloqueReservado = malloc(sizeof(uint32_t));
            		*bloqueReservado = i;
            		list_add(bloquesReservados, bloqueReservado);
            		log_debug(logger, "Reserve este bloque %d ",i);
            		if(j == 0){
            			primerBloqueReservadoSWAP = i;
            			log_debug(logger, "Primer Bloque %d ",primerBloqueReservadoSWAP);
            		}
            		usleep(file_config.retardo_acceso_bloque * 1000);
            		memcpy(archivo_de_bloques + (i * file_config.tam_bloque) * sizeof(uint8_t), "/0", file_config.tam_bloque);
            		break;
            	}
```

### 💻 Logs
```
00000000: 534f 4e59 5950 0000 0000 0000 0000 0000  SONYYP..........
00000010: 0000 5461 6d61 6e69 6f20 626c 6f71 7565  ..Tamanio bloque
00000020: 0000 5461 6d61 6e69 6f20 626c 6f71 7565  ..Tamanio bloque
00000030: 0000 5461 6d61 6e69 6f20 626c 6f71 7565  ..Tamanio bloque
00000040: 0000 5461 6d61 6e69 6f20 626c 6f71 7565  ..Tamanio bloque
00000050: 0000 5461 6d61 6e69 6f20 626c 6f71 7565  ..Tamanio bloque
00000060: 0000 5461 6d61 6e69 6f20 626c 6f71 7565  ..Tamanio bloque
00000070: 0000 5461 6d61 6e69 6f20 626c 6f71 7565  ..Tamanio bloque
00000080: 0000 5461 6d61 6e69 6f20 626c 6f71 7565  ..Tamanio bloque
00000090: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000a0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000b0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000c0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000d0: 0000 0000 0000 0000 0000 0000 0000 0000  ................

```

**Comment by RaniAgus** [comment]
¡Buenas! En esta línea:
```c
memcpy(archivo_de_bloques + (i * file_config.tam_bloque) * sizeof(uint8_t), "/0", file_config.tam_bloque);
```
`memcpy` recibe 3 parámetros:
1. Puntero destino: `archivo_de_bloques + (i * file_config.tam_bloque) * sizeof(uint8_t)`
2. Puntero origen: `"\0"`
3. Tamaño a copiar: `file_config.tam_bloque`

Supongamos que tengo un tamaño bloque de 16. Eso hace que `memcpy()` lea 16 bytes desde el puntero origen y los copie a destino. 

El problema acá es que el string `"\0"` tiene solo dos bytes: `0000`, por lo que `memcpy()` va a seguir de largo y copiar los bytes que se encuentren inmediatamente posteriores a la posición en memoria donde se encuentre ese string.

En este caso, no hay segmentation fault porque, como todos los literales se encuentran juntos en el segmento de código, al parecer el compilador está dejando un string que empieza con los 14 bytes que forman la frase `"Tamanio bloque"` después del string `"\0"`. Es una posición válida, pero no es lo que queríamos hacer

Si la idea era setear esos bytes en cero, les aconsejo usar `memset()`: https://man7.org/linux/man-pages/man3/memset.3.html

Saludos

**Comment by Federico-Baez** [comment]
Alabado seas
