### ISSUE TITLE
Lenguaje de programación para los próximos cuatrimestres

### ISSUE THREAD

**Issue by MartinSintas** [sisoputnfrba/foro#3364]
Buenas, tenía una consulta acerca del cuatri que viene si finalmente se pasará a hacer el tp con el lenguaje de go para ir empezando a estudiar cosas de dicho lenguaje o si seguirá utilizándose c.

Muchas gracias por todo y nos vemos en los próximos cuatrimestres :D 

Felices fiestas

**Comment by nahuemazzeo** [comment]
Hola @MartinSintas. A falta de anuncio oficial el trabajo practico sigue y va seguir siendo en C.

Saludos. Nahuel
