### ISSUE TITLE
👩‍💻 ¿Buscás Grupo / Integrantes para el 1c2024? ¡Posteá ACÁ! 👨‍💻

### ISSUE THREAD

**Issue by RaniAgus** [sisoputnfrba/foro#3365]
¡Buenas!

Con el objetivo de unificar todos los post de búsqueda de grupos / integrantes, 
vamos a centralizarlos en este post.

Les recomendamos encarecidamente que traten de **NO publicar números de 
celular** y limitarse solo a los mails. Tengan en cuenta que el foro es público,
por lo que pueden llegar a quedar en alguna lista de spam o que les hable gente 
que no quieran.

Ante cualquier inconveniente con las inscripciones, por favor envíen un mail
a inscripciones@utnso.com.ar

Saludos.-

**Comment by santi-p98g** [comment]
Buenas! Con @NKennedy31 estamos buscando alumn@s para nuestro grupo de tp. En especial que hayan recursado como nosotros, y que quieran liquidar la materia este cuatrimestre. Nosotros tampoco estamos trabajando en este momento por eso también seria ideal disponer de bastante tiempo.
Les dejo mi mail: santi.p98g@gmail.com
Saludos! :)

**Comment by sergidalessio** [comment]
Buenas, acá buscando formar un grupo. Estoy anotado en el curso K3153.  Mi experiencia es bastante lejana (2003) , en donde la forma de trabajo era un poco distinta. En este momento estoy tratando de familiarizarme con las herramientas disponibles, o sea, es como un "volver a empezar". Con lo cual ganas de laburar no me faltan solo pido paciencia y colaboración si me trabo con algo jeje. Dejo mail para los que quieran sumarse (dalessio@frba.utn.edu.ar)

**Comment by daltplusplus** [comment]
buenas. soy recursante con ganas de liquidar la materia y ando buscando grupo. dejo mi mail para armar grupo o entrar a alguno
dlopeztapia@frba.utn.edu.ar

**Comment by sergidalessio** [comment]
Buenas noches Dante. Si todavía estas sin grupo y te interesa podes agregarte al mio.Somos dos por ahora. Dejo link de wapp: Invitación a grupo de WhatsApp Abrazo, buena cursada! Enviado desde Correo para Windows De: DanteEnviado: viernes, 22 de marzo de 2024 21:27Para: sisoputnfrba/foroCC: sergidalessio; CommentAsunto: Re: [sisoputnfrba/foro] 👩‍💻 ¿Buscás Grupo / Integrantes para el 1c2024? ¡Posteá ACÁ! 👨‍💻 (Issue #3365) buenas. soy recursante con ganas de liquidar la materia y ando buscando grupo. dejo mi mail para armar grupo o entrar a ***@***.***—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by verocamiz** [comment]
Buenas, somos 2 buscando gente para el tp. Es la primera vez que curso la materia, asi que no tengo muchos conocimientos del TP pero si estoy dispuesta a meterle para llegar a tiempo con las entregas!  Sabemos que es una materia que requiere mucha dedicacion, mi amiga ya la habia cursado varias veces.

**Comment by sergidalessio** [comment]
Hola verocamiz pásame tu mail y hablamos Enviado desde Correo para Windows De: verocamizEnviado: viernes, 22 de marzo de 2024 23:28Para: sisoputnfrba/foroCC: sergidalessio; CommentAsunto: Re: [sisoputnfrba/foro] 👩‍💻 ¿Buscás Grupo / Integrantes para el 1c2024? ¡Posteá ACÁ! 👨‍💻 (Issue #3365) Buenas, somos 2 buscando gente para el tp. Es la primera vez que curso la materia, asi que no tengo muchos conocimientos del TP pero si estoy dispuesta a meterle para llegar a tiempo con las entregas! Sabemos que es una materia que requiere mucha dedicacion, mi amiga ya la habia cursado varias veces.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by iIvanPod** [comment]
Buscamos 2 integrantes que sea la primera vez que cursen la materia y esten dispuestos a seguir la materia hasta el final.
si estas interesado: ipreinsperger@frba.utn.edu.ar

**Comment by iIvanPod** [comment]
Nos quedo lugar para 1 integrante.

**Comment by tomasdemonasterio** [comment]
Estoy buscando grupo. Me manejo bien con C y tengo intenciones de aprobar la materia. Busco grupo serio. 
Curso sabados a la mañana.

tdemonaterio@frba.utn.edu.ar

**Comment by sergidalessio** [comment]
Buenas, nos estaría faltando un integrante, alguien que curse los martes TN con Masoero preferentemente. Interesado/a mande mail a dalessio@frba.utn.edu.ar

**Comment by sdelperciorodriguez** [comment]
Hola, formo parte de un grupo junto con 2 personas más. Nos faltan 2 integrantes que estén dispuestos a darle bola al tp y no dejar la materia. Dejo mi mail por si se quieren unir : sdelperciorodriguez@frba.utn.edu.ar

**Comment by Pazsantiago** [comment]
Buenas a todos!, estamos buscando un integrante que nos falta. Estamos buscando gente que tenga el tiempo y ganas para hacer el tp, además queremos intentar presentarlo en go (y si no en c), así que si están interesados este es mi mail: spaz@frba.utn.edu.ar.

**Comment by MZuran** [comment]
Hola. Buscamos 2 integrantes de grupo para hacer el tp. No nos importa si son recursantes o no, lo que queremos es alguien dedicado al tp y que tenga un mínimo de conocimientos previos. Si sos así, mandanos un mail. En lo posible, a las 3 direcciones:
mzuran@frba.utn.edu.ar
gajuarez@frba.utn.edu.ar
jannet7mil@gmail.com

**Comment by AlejandroNahuelFernandez** [comment]
Hola es la primera vez que curso la materia, estoy buscando formar un grupo o integrarme a uno , no importa si son recusantes o si la cursan por primera vez , tengo algunos conocimientos en algunos lenguajes de programación , no busco personas que sepan programar ,busco personas que estén decididas a esforzarse y completar el tp , soy del k3011 nose si las comisiones se mezclan , pero si es posible busco compañeros del mismo curso , mi mail es afernndez@frba.utn.edu.ar

**Comment by fedecassina** [comment]
Buenas! Estábamos buscando dos integrantes que quieran terminar la materia y centrarse en el trabajo practico y llevarlo al día. Somos de los cursos del miércoles noche y viernes noche . Si están interesados pueden mandar mail a: 
fcassinacarbia@frba.utn.edu.ar 
eotero@frba.utn.edu.ar

**Comment by ealon2** [comment]
Buenas! Estoy buscando integrante, me interesa que sean recursantes dado que la curva de aprendisaje sera mas rapida, tambien el hecho de que hayan ya trabajado en C, y otros legunajes, como tambien el uso de todas las herramientas (principalmente GIT). En mi caso, recurso la materia, programo C y trabajo en sistemas.

Dejo mi email: ezequiel.fiasche@frba.utn.edu.ar

Abrazo y exitos con la cursada!

**Comment by LuichiTW** [comment]
Hola, busco grupo, es la primera vez que curso. Soy del K3014 y mi mail es:
ltitaewatanabe@frba.utn.edu.ar

**Comment by AlejandroNahuelFernandez** [comment]
ya somos dos integrantes del curso k3011, nos queda lugar para 3 personas mas.  afernndez@frba.utn.edu.ar

**Comment by IgnacioPringles** [comment]
Estoy buscando grupo, primera vez que curso la materia, curso K3055.
Mail: ipringles@frba.utn.edu.ar

**Comment by Notshak** [comment]
Hola, busco grupo, es mi 1ra vez cursando la materia, curso en K3011  nahperez@frba.utn.edu.ar

**Comment by fabbiodv** [comment]
Hola! Estamos buscando integrantes para el grupo especialmente comprometidos para tener las cosas al día, somos alumnos que trabajan en sistemas, curso K3051.
Mi mail es: fmazarella@frba.utn.edu.ar

**Comment by gkrayeski** [comment]
Buenas, estoy buscando grupo, es la primera vez que curso SSOO, y de C no se mucho, pero algoritmos la promocione con 10, y me quiero dedicar de lleno al tp para aprobar la materia, no voy a abandonar, y soy aplicado. Mail: gkrayeski@frba.utn.edu.ar

**Comment by matefernandezcc** [comment]
Buenas, ando buscando grupo para el TP, es la primera vez que curso la materia.
Si son de la comisión K3054 o si cursan los Miércoles (Noche) y Sábados (Tarde) mejor asi coordinamos horarios
Mail: mfernandezcruz@frba.utn.edu.ar

**Comment by ruizbrunoi** [comment]
Buenas!

Busco armar un grupo que esté bastante comprometido para poder llevar el tp al día, que la materia sea prioridad, sean recursantes y hayan estado involucrados.

Me pueden escribir a bruiz@frba.utn.edu.ar 

Saludos y éxito en la cursada!

**Comment by MendezTomasI** [comment]
Buenas, estoy buscando grupo para el TP, estoy en el curso K3011 es la primera vez que la curso.
Mi mail es: tmendez@frba.utn.edu.ar

**Comment by thomyluca** [comment]
Buenas, nos falta un integrante para el tp. Somos 4 que le metemos bastante (ya tenemos todos hecho el tp0) así que buscamos alguien que también esté medio vivido, preferentemente de los miércoles noche K3054/K3154. Si alguno está interesado, hableme a tluca@frba.utn.edu.ar 🫵🏻

**Comment by francoalanoca** [comment]
Buenas nos estarían faltando dos integrantes.
De preferencia que tengan disponibilidad horaria y no vayan a abandonar la materia, si se manejan en C y/o promocionaron Algoritmos suma bastante, si la recursan que hayan estado involucrado seriamente en el Tp.
Si te interesa me puedes escribir a falanocavillarreal@frba.utn.edu.ar

**Comment by ealon2** [comment]
> Buenas! Estoy buscando integrante, me interesa que sean recursantes dado que la curva de aprendisaje sera mas rapida, tambien el hecho de que hayan ya trabajado en C, y otros legunajes, como tambien el uso de todas las herramientas (principalmente GIT). En mi caso, recurso la materia, programo C y trabajo en sistemas.
> 
> Dejo mi email: [ezequiel.fiasche@frba.utn.edu.ar](mailto:ezequiel.fiasche@frba.utn.edu.ar)
> 
> Abrazo y exitos con la cursada!

Nos falta un intengrante!

**Comment by LucianoZunino** [comment]
Buenas, buscamos 2 integrantes del grupo, no nos interesa que estén recursando o no. Que estén cursando 3ro para adelante en la carrera y que esta materia sea su prioridad. Los tres que componemos el grupo somos súper aplicados y con muchas ganas de meterle y llevarla al día. Nuestra comisión es k3054/3154, k3053.
lzunino@frba.utn.edu.ar

**Comment by ilorences** [comment]
Buenas, buscamos 1 integrante de grupo, preferentemente que haya cursado Sintaxis y Paradigmas y pueda poner esta materia como prioridad. Los integrantes somos de las comisiones k3054/3154 y k3153.
Mail de contacto: ilorences@frba.utn.edu.ar

**Comment by ArielMichelli** [comment]
Buenas!, busco gente que le ponga garra y corazón a la materia que solamente tiene mala fama. La idea es hacerlo en Go, y si no nos aceptan le entramos en C no pasa nada, experiencia tengo en ambos lenguajes!. 

Dejo mi mail: Arielm-04@hotmail.com

Muy importante, se apunta a la promoción.

**Comment by gonramirez36** [comment]
Buenas, nos falta uno para nuestro grupo que tenga ganas y tiempo para meterle al tp, en lo posible que sea de los martes a la noche. Dejo mi mail: gonramirez@frba.utn.edu.ar

**Comment by KirkSH** [comment]
Hola. Estamos buscando un integrante para nuestro grupo. No importa el curso, solamente las ganas.
Email: anubile@frba.utn.edu.ar

**Comment by OleksiyTkach** [comment]
Buenas noches, soy del curso k3014 los miercoles y viernes, aun estoy sin grupo, soy de seguir en el proyecto hasta el final, aunque mis conocimientos podrian llega a ser insuficientes, pero confio en que durante la cursada logre ampliarlos, entonces si a algun grupo le falta un miembro, tengan la amabilidad de aceptarme. Mi correo es ole.tkach@gmail.com

**Comment by CristianClaros** [comment]
Bueeenas, soy alumno del Curso k3051, de los Lunes Noche, soy recursante, y busco meterle ganas al TP que es de lo mas importante del comienzo.
Saludos. Mi correo : cclaroschoque@frba.utn.edu.ar

**Comment by juanpdebonis** [comment]
Buenas, soy del curso K3154, turno miercoles noche. Soy recursante y estoy buscando grupo para realizar el tp. Mi correo es: [juanpablodebonis@hotmail.com](url).

**Comment by lucholud** [comment]
Buenas! Estoy solo y busco un grupo. Estoy comprometido y quiero sacar la materia sí o sí este cuatri. Tengo conocimientos en C, git y laburo en sistemas. Mi curso es K3153.

Les dejo mi mail:
lluduena@frba.utn.edu.ar

**Comment by rubinhoemanuel** [comment]
Buenas noches, soy del curso de los miercoles a la noche K3054 y busco grupo. Soy recursante, programo en C y trabajo como desarrollador java. Dejo mi email: merubinho@frba.utn.edu.ar.

**Comment by patriciojgf** [comment]
> Buenas noches, soy del curso de los miercoles a la noche K3054 y busco grupo. Soy recursante, programo en C y trabajo como desarrollador java. Dejo mi email: [merubinho@frba.utn.edu.ar](mailto:merubinho@frba.utn.edu.ar
Hola, a nosotros nos falta uno y somos de miercoles a la noche, te mando mail

**Comment by knseri** [comment]
Buenas, soy del curso de los sabados K3213 y estoy buscando grupo. Soy recursante.

Dejo mail: 
kseri@frba.utn.edu.ar

**Comment by ruizbrunoi** [comment]
Hola!

Nos faltan dos personas pars el grupo. La idea es que estemos todos en la misma sintonia

**Comment by ruizbrunoi** [comment]
Buenas!

Nos faltan dos personas para completar el grupo. La idea es que estemos todos en la misma situación... El tp de la materia tiene que ser prioridad!

Somos recursantes y estuvimos bastante involucrados con el tp.

Mi mail es bruiz@frba.utn.edu.ar 

Saludos y éxito en la cursada!

**Comment by alex-claure-m** [comment]
Hola, estamos buscando 2 integrantes para sumar al equipo. No nos interesa si es es recusante o si recien es su primera vez en la materia, o si sabe poco el lenguaje C, la idea es que este comprometido a realizar el tp, a trabajar en equipo y aprender a la par. 

Mi mail es: alexclauremontecinos@frba.utn.edu.ar

**Comment by alobianco** [comment]
Hola, estamos buscando 2 integrantes, es la primera vez que hacemos el TP, pero no vamos a abandonar.

Mi mail es agustinlobianco@frba.utn.edu.ar

**Comment by niromero** [comment]
Buenas! Estamos buscando un integrante que quiera centrarse en el trabajo practico y llevarlo al día. Si están interesados pueden mandar mail a:
niromero@frba.utn.edu.ar

**Comment by SanchezEnzo** [comment]
Hola! Estamos en búsqueda de 2 integrantes para nuestro grupo de TP. Pretendemos llevarlo al día, el único requisito es no abandonar. 

Les dejo mi mail: ensanchez@frba.utn.edu.ar

**Comment by matibapti** [comment]
Buenas!!! Estamos en la busqueda de un intregrante que se quiera sumar, estamos comprometidos y con ganas de sacar adelante el tp, somos del curso de los miercoles a la noche.
Mi mail es: matibapti@frba.utn.edu.ar

**Comment by ValenSampayo** [comment]
Buenas, estoy buscando grupo soy de la comisión K3213 (Sabados a la mañana), es la primera vez que curso la materia y estoy comprometido a terminar el TP.

Mi mail de contacto es: vsampayo@frba.utn.edu.ar

**Comment by NahuRodas** [comment]
Buenas, estoy buscando grupo! Es la primera vez que curso la materia pero cuento con conocimientos en C/C++ y quiero darle con todo al TP.
Mi mail es: crodas@frba.utn.edu.ar

**Comment by JuanLyna** [comment]
Buenas!!! Estamos en la busqueda de 3 integrantes para sumar a nuestro equipo, estamos comprometidos de aprobar el TP y finalizar toda la materia, cualquiera es bienvenido mientras se comprometa a trabajar en equipo y llevar acabo la realización del TP
 les dejo mi Mail para contacto: jlunarumualdo@frba.utn.edu.ar

**Comment by tomaslcarballo** [comment]
Buenas, estamos un buscando un integrante más para completar el grupo. Somos 4, algunos recursantes y otros cursando por primera vez, todos trabajamos en sistemas y queremos llegar hasta el final de la materia.
Dejo mi mail de contacto: tcarballo@frba.utn.edu.ar

**Comment by benjaminCesar** [comment]
Buenas, estamos buscando dos integrantes para terminar de formar el grupo. Es nuestra primera vez cursando la materia, y es bienvenido cualquiera que se comprometa con el trabajo de la materia. Pueden escribirnos a cualquiera de los siguientes mails: bcesar@frba.utn.edu.ar o jpella@frba.utn.edu.ar

**Comment by karelysr** [comment]
Buenas, busco grupo, soy del curso K3154
Mi correo es: krangelsalcedo@frba.utn.edu.ar

**Comment by ValenSampayo** [comment]
Buenas, estamos buscando 2 integrantes! Es la primera vez que cursamos la materia y estamos comprometidos a teminar tanto el TP como la materia en sí.
Pueden comunicarse a cualquiera de los siguientes mails:
vsampayo@frba.utn.edu.ar
crodas@frba.utn.edu.ar

**Comment by alobianco** [comment]
Buenas, nos falta un integrante para completar los 5, estamos en cursos del sábado y también en miércoles a la noche
Si alguien esta interesado enviar mail a:
agustinlobianco@frba.utn.edu.ar

**Comment by manuix** [comment]
Buenas, somos 4 y nos esta faltando un integrante para terminar de armar el grupo, estamos cursando sábados a la tarde, comisión K3055 y los miércoles, comisión K3254.
Mi mail es maocampo@frba.utn.edu.ar

**Comment by mdiasperi** [comment]
Buenas! nos estarian faltando dos integrantes para completar el grupo. 
Mi mail es mdiasperi@frba.utn.edu.ar

**Comment by ArielMichelli** [comment]
Buenas!!, Estamos en la búsqueda del último integrante para nuestro grupo. Gente comprometida para meterle mucha garra al TP. Somos del curso K3054 / K3154, aunque igualmente estamos abiertos a gente de cualquier curso. 

Les dejo mi mail: [Arielm-04@hotmail.com](mailto:Arielm-04@hotmail.com)	

Saludos!

**Comment by Zoxcrat** [comment]
buenas! nos falta 1 integrante para el grupo
dejo el link de acceso al grupo de whatsapp
https://chat.whatsapp.com/BhqMz34n619FxCah5lDBc8

**Comment by maxikbch** [comment]
buenas nos falta 1 en el grupo
mi mail es: [mkallenbach@frba.utn.edu.ar](url)

**Comment by leonardocelestino** [comment]
Buenas!
Estamos en busca de un integrante mas. Somos todos del curso K3054/3154.
Dejo mi correo: lcelestino@frba.utn.edu.ar

**Comment by santinosommaruga** [comment]
buenas, somos un grupo de cuatro y nos falta un integrante, estamos comprometidos a aprobar el tp pueden contactarme a mi mail: ssommaruga@frba.utn.edu.ar

**Comment by ArielCastro00** [comment]
Buenas, estoy cursando la materia por primera vez y estoy buscando grupo para realizar el tp. Soy del curso K3213 sabados a la mañana. Les dejo mi mail para contactarme: acastroapaza@frba.utn.edu.ar

**Comment by Baldra** [comment]
Buenas. Ando buscando grupo. Soy de la comisión K3213 cursando los sábados a la mañana. Si a alguien le falta un integrante o también esta solo y quiere formar equipo, dejo mi contacto: [tbaldracchi@frba.utn.edu.ar](tbaldracchi@frba.utn.edu.ar)

**Comment by lucasciola1** [comment]
Buenas, buscamos un solo integrante que se sume a nuestro grupo. Cualquier interesado hábleme a este mail: lsciola@frba.utn.edu.ar
Saludos

**Comment by MarieLuz-Mamani** [comment]
> ¡buenas! nos falta 1 integrante para el grupo dejo el link de acceso al grupo de whatsapp https://chat.whatsapp.com/BhqMz34n619FxCah5lDBc8

Aun les falta un integrante ?

**Comment by facu777** [comment]
Hola estoy creando un grupo nuevo.  Alguien no tiene grupo? 
Mi teléfono es 1121841407

**Comment by clarkelamothe** [comment]
Hola buenas, estoy buscando grupo. Curso los sábados a la mañana. Dejo mi mail: glamothe@frba.utn.edu.ar por si tiene lugar en un grupo o si alguuien quiere hacer un grupo. Gracias.

**Comment by BrianVillarroel94** [comment]
Hola soy de curso k3052 (viernes por la noche) y soy recursante, estoy buscando grupo, mi mail es: bvillarroelrocha@frba.utn.edu.ar.

**Comment by Naruss0** [comment]
> Buenas!!, Estamos en la búsqueda del último integrante para nuestro grupo. Gente comprometida para meterle mucha garra al TP. Somos del curso K3054 / K3154, aunque igualmente estamos abiertos a gente de cualquier curso.
> 
> Les dejo mi mail: [Arielm-04@hotmail.com](mailto:Arielm-04@hotmail.com)
> 
> Saludos!

Aún les falta integrante? soy de la misma comisión

**Comment by f-carracedo** [comment]
¡Hola! Ando buscando grupo para el TP, con la idea de meterle mucha garra. Si andan buscando a alguien pueden responderme por acá o mandarme un mail a fcarracedo@frba.utn.edu.ar

**Comment by Oshiro28** [comment]
Buenas!!, Estamos en la búsqueda del último integrante para nuestro grupo. Somos del curso K3254 de los miércoles a la noche y sábados a la tarde.
Seria ideal que este en nuestro mismo curso, aunque también no estaría mal que pertenezca a otra.

Les dejo mi mail: joshirotaipe@frba.utn.edu.ar

Saludos!

**Comment by RedStarIndustries** [comment]
Hola, necesito grupo. Preferentemente gente del curso K3013 y que acepte un n00b total que esta bastante perdido.

Por favor contactarme a [matias_ramirez_92@live.com.ar](url) y/o [mramirezvega@frba.utn.edu.ar](url) .

(Si no contesto en un mail reenviarlo al otro, muchas gracias.)

**Comment by liamkarolt** [comment]
Buenas noches!! Estoy buscando grupo. Curso sábado por la mañana K3213 no soy re-cursante. Tengo bastante disponibilidad días de semana por la tarde y sábados. Si a algún grupo le faltan integrantes por favor contáctenme a mi mail
Mail: [lkarol@frba.utn.edu.ar](url)

**Comment by javfernandezfrba** [comment]
Buenas estoy buscando grupo, curso los viernes a la noche k3052

**Comment by javfernandezfrba** [comment]
Buenas estoy buscando grupo, curso los viernes a la noche k3052
mail: javfernandez@frba.utn.edu.ar

**Comment by brian7178** [comment]
Hola,soy del turno mañana de los sabados y estoy buscando grupo.Es la primera vez que curso la materia,si alguno le queda espacio contactarme a bsiscosalazar@frba.utn.edu.ar

**Comment by CabreraGE** [comment]
> Buenas, estamos un buscando un integrante más para completar el grupo. Somos 4, algunos recursantes y otros cursando por primera vez, todos trabajamos en sistemas y queremos llegar hasta el final de la materia. Dejo mi mail de contacto: [tcarballo@frba.utn.edu.ar](mailto:tcarballo@frba.utn.edu.ar)

Hola, siguen buscando 1 integrante? Estoy sin grupo
gcabrera@frba.utn.edu.ar comision K3213

**Comment by CabreraGE** [comment]
Buenas tardes, estoy en busqueda de grupo. Soy de curso K3213 (era del K3113 pero nos unieron a esta comision) de los sabados a la mañana.
Por favor si hay disponible un lugar en algun grupo me avisan asi me sumo? No tengo preferencias, solo compromiso para poder trabajar en equipo y lograr el objetivo de aprobar la materia

correo: gcabrera@frba.utn.edu.ar

**Comment by zyusti** [comment]
Hola! Nos falta una persona en el grupo. Cursamos los Sábados, la mayoría por la tarde, pero quien quiera unirse es bienvenido. Mi mail es zyusti@frba.utn.edu.ar 
Muchas gracias y suerte para todos!

**Comment by CabreraGE** [comment]
> Hola! Nos falta una persona en el grupo. Cursamos los Sábados, la mayoría por la tarde, pero quien quiera unirse es bienvenido. Mi mail es [zyusti@frba.utn.edu.ar](mailto:zyusti@frba.utn.edu.ar) Muchas gracias y suerte para todos!

Hola, curso los sabados y estoy sin grupo
Si esta disponible el cupo me puedo sumar
Te pase un correo con mis datos
Saludos y gracias.-

**Comment by MirkoPeschel** [comment]
Hola, somos 4 y nos falta un integrante para nuestro grupo.
Si buscas grupo y tenes ganas de aprobar S.O. no dudes en hablarme: mpeschel@frba.utn.edu.ar

**Comment by CabreraGE** [comment]
> Hola, somos 4 y nos falta un integrante para nuestro grupo. Si buscas grupo y tenes ganas de aprobar S.O. no dudes en hablarme: [mpeschel@frba.utn.edu.ar](mailto:mpeschel@frba.utn.edu.ar)

Hola, me puedo sumar a su grupo
gcbarera@frba.utn.edu.ar

**Comment by Cynthia-21** [comment]
Hola, estamos buscando un integrante mas para nuestro grupo ya que se nos dio de baja uno de ellos. cualquier cosa hablame a: cabbate@frba.utn.edu.ar

**Comment by LAF96** [comment]
Hola, busco grupo. Estoy recursando. Si todavía le falta un integrante a algún grupo que esté decidido a seguir con la materia, avísenme.
leofierens@frba.utn.edu.ar

**Comment by r-Larrea-utn** [comment]
Hola, Busco integrantes para mi grupo( 2), somos del curso k3054/3154 miercoles a la noche, de preferencia que tenga tiempo los fines de semana o viernes por la noche, asi coordinamos los meets.
mail: rlarrea@frba.utn.edu.ar

**Comment by lucassurdo** [comment]
hola busco grupo, es la primera vez que curso la materia mail: lsurdo@frba.utn.edu.ar

**Comment by CabreraGE** [comment]
lkarol@frba.utn.edu.ar
bsiscosalazar@frba.utn.edu.ar
glamothe@frba.utn.edu.ar
Como andan? Armamos grupo? Somos todos de los sabados a la mañana K3213.
Avisen y armo el grupo si esra libres y nos faltaria 1 mas

**Comment by lucassurdo** [comment]
Yo soy son k3013 de los sábados a la mañana pero si quieren igual estoy

**Comment by jsanchezbusatto** [comment]
Hola. Tenemos un grupo, ya somos 4 personas y buscamos a una mas. cualquier cosa me avisan. jsanchezbusatto@frba.utn.edu.a

**Comment by liamkarolt** [comment]
> [lkarol@frba.utn.edu.ar](mailto:lkarol@frba.utn.edu.ar) [bsiscosalazar@frba.utn.edu.ar](mailto:bsiscosalazar@frba.utn.edu.ar) [glamothe@frba.utn.edu.ar](mailto:glamothe@frba.utn.edu.ar) Como andan? Armamos grupo? Somos todos de los sabados a la mañana K3213. Avisen y armo el grupo si esra libres y nos faltaria 1 mas

Buenas Tardes como andas? Yo estoy en un grupo de 2 si te queres sumar mandame un mail a [lkarol@frba.utn.edu.ar](url)

**Comment by nhuamanicatano** [comment]
Hola como va? Estoy buscando grupo! si alguno tiene un lugar me avisa, muchas gracias! huamanicatano@frba.utn.edu.ar

**Comment by Gaston-Erazo18** [comment]
Hola, busco grupo, soy recursante, si alguno tiene un lugar me avisa, muchas gracias!
Adjunto mi email: rerazolera@frba.utn.edu.ar

**Comment by nicoopenna** [comment]
Buenas! Estamos buscando 2 integrantes para completar el equipo, les dejo mi correo npenna@frba.utn.edu.ar
Saludos!

**Comment by Prixthix** [comment]
Que tal?
Soy Alejandro, soy cursante del K3055,(sábado turno tarde), curso por primera vez SO, estoy buscando grupo para el tp.
Les adjunto mi mail: alcabral@frba.utn.edu.ar
Saludos

**Comment by NehuenS** [comment]
Hola, que tal? 
Soy Santiago, estoy cursando en la K3154 (que cursa junto a la K3054). Estoy cursando la materia por primera vez y busco grupo para el TP. Mi mail es [sansilva@frba.utn.edu.ar](mailto:%73%61%6es%69l%76%61@%66r%62%61%2e%75%74n%2ee%64u%2e%61%72)

**Comment by clarkelamothe** [comment]
@CabreraGE dale si

**Comment by MendezTomasI** [comment]
Buenas, somos 4 en el grupo.
Si alguien le falta grupo, puede escribirme al mail: tmendez@frba.utn.edu.ar

**Comment by FranciscoMassera** [comment]
Buenas soy Francisco. Estoy cursando en el curso K3154/3054 y estoy buscando algun grupo para el TP. Mi mail es: fmassera@frba.utn.edu.ar

**Comment by RogerZu** [comment]
Buenas mi nombre es Roger del curso k3055 sabado a la tarde y es la primera vez que curso la materia y estoy buscando un grupo, no importa recursantes o primera cursada, lo importante es hacer en grupo el tp, mail: rogerzunigasayas@frba.utn.edu.ar

**Comment by EstebanUtn** [comment]
Hola, busco grupo. Curso k3213--mail: ecervanteslozano@frba.utn.edu.ar.

**Comment by aguila91** [comment]
Hola, como va? busco grupo:

**Comment by aguila91** [comment]
> [lkarol@frba.utn.edu.ar](mailto:lkarol@frba.utn.edu.ar) [bsiscosalazar@frba.utn.edu.ar](mailto:bsiscosalazar@frba.utn.edu.ar) [glamothe@frba.utn.edu.ar](mailto:glamothe@frba.utn.edu.ar) Como andan? Armamos grupo? Somos todos de los sabados a la mañana K3213. Avisen y armo el grupo si esra libres y nos faltaria 1 mas

ya tenes el faltante?

**Comment by martingabrielmartinez3** [comment]
Hola! Soy de K3055 Formamos grupo para el TP? Digan y te paso código de invitación O me pasan y acepto. Saludos
 mi mail es martinmartinez@frba.utn.edu.ar
