### ISSUE TITLE
Versiones de Ubuntu

### ISSUE THREAD

**Issue by sergidalessio** [sisoputnfrba/foro#3366]
Buenas ayudantes! Estoy empezando a preparar el entorno de trabajo en mi pc y quería saber si para este cuatri las versiones de Ubuntu Server/Graphics para usar en la VM son las mismas del año pasado.Muchas Gracias.

**Comment by iago64** [comment]
Buenas! Cómo va?

Respuesta corta: Si, son las mismas del cuatri / año pasado.

Respuesta extendida: las VMs estan basadas en las versiones LTS de ubuntu y la proxima no sale hasta fines del mes que viene, asi que con suerte vamos a hacer una version nueva para el cuatrimestre que viene.

Saludos.-

**Comment by fercoiman** [comment]
Corolario de esto entonces es que C sigue siendo el lenguaje utilizado?

**Comment by LeandroCarbajales** [comment]
Afirmativo!

**Comment by RaniAgus** [comment]
¡Buenas @sergidalessio! Paso a patrullar para avisar (para la próxima) que si la duda ya fue resuelta pueden cerrar el issue 👮🏻‍♂️

Si en un futuro ven que algo no terminó de cuadrar pueden tomarse la libertad de reabrirlo o abrir uno nuevo referenciando éste. 

¡Saludos!

**Comment by sergidalessio** [comment]
Hola Agustin, si, duda despejada. Gracias por cerrarlo.Slds
