### ISSUE TITLE
🤦🏽‍♂️ Error al instalar ambiente en Mac M1 

### ISSUE THREAD

**Issue by lpangaro** [sisoputnfrba/foro#3367]
Buenas! que tal? 🙋🏽‍♂️
Estoy instalando la VM en una Mac M1, seguí los pasos del [video recomendado](https://www.youtube.com/watch?v=hnwK-nkXolc&t=339s) (instalando la versión para ARM), no tuve problema, pude instalar el Ubuntu server, tengo mi usuario y todo; Pero al momento de continuar con la [instalación del ambiente ](https://github.com/sisoputnfrba/entorno-vms) y ejecutar el comando  `curl -fsSL https://faq.utnso.com.ar/base-server.sh | sudo sh -x` hace un montón de configuración y termina diciendo ...
```
EROR 404: Not Found
``` 
Dejo más abajo los últimos renglones antes del error por si sirven de contexto

### 📦 Especificaciones de la VM
- Versión de UTM:  4.4.5 (94)
- Memoria RAM asignada: 4GB
- Ubuntu 22.04 for **ARM**

### 🖥️ Especificaciones del host
- Sistema Operativo y versión: Sonoma 14.4
- Memoria RAM: 8GB
- Procesador: M1

### 💻 Logs

``` 
Procesando disparadores para libgdk-pixbuf-2.0-0:arm64 (2.42.8+dfsg-1ubuntuo.2)...
Scanning processes...
Scanning linux images...
Running kernel seems to be up-to-date.
No services need to be restarted.
No containers need to be restarted.
No user sessions are running outdated binaries.
No VM guests are running outdated hypervisor (gemu) binaries on this host.
+ dpkg --print-architecture
+ ARCHITECTURE=aPm64
+ uget -0/tmp/gdb_12.1-0ubuntu1~22.04_arm64.deb https://launchpad.net/ubuntu-toolchain-r/tarchive/ubuntu/ppa/tbuild/23606523/+files/gdb_12.1-0ubuntu1™22.04_ar
m64. del
--2024-03-22 03:43:39-- https://launchpad.net/ubuntu-toolchain-r/tarchive/ubuntu/ppa/+54110/23606523/+files/gdb_12.1-0ubuntu1722.04_arm64.deb
Resolving launchpad.net (launchpad.net)
Connecting to
launchpad.net
185.125.189.223,
185.125.189.222, 2620:20:4000:1009::3ba,
(launchpad.net) |185.125.189.2231:443... connected.
HTTP request
sent, await ing response..
404 Not Found
2024-03-22 03:43:41 ERROR 404: Not Found.
```

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va? Mala mía, hace poco probé el script y me pasó lo mismo así que lo actualicé, pero me olvidé de actualizar el link al que apunta el direccionario 😅 

Ya está corregido, probá ahora de ejecutarlo de nuevo y contanos.

Saludos

**Comment by lpangaro** [comment]
Creo que mejoro, pero no del todo...
Tengo forma de borrar lo anterior para volver a instalar de cero?
Sino pruebo haciendo una VM nueva 😅
```
Ipangaro@utnso: ** curl -fsSL https://faq.utnso.com.ar/base-server.sh | sh -x
+ set
+ apt-get update -y
Leyendo lista de
paquetes.. Hecho
E: No se oudo abrir el fichero de bloqueo #/var/1ib/aot/1ists/lock» - oben (13: Permission denied)
E: No se pudo bloquear el directorio /var/librant/lists/
W: Se produjo un problema al desligar el fichero /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Se produjo un problema al desligar el fichero /var/cache/apt/sropkgcache.bin - RemoveCaches (13: Permission
+ add-apt-repository -y ppa:git-core/ppa
Error: must run as root
```

**Comment by RaniAgus** [comment]
Creo que te faltó agregar el `sudo` al comando, es:

```sh
curl -fsSL https://faq.utnso.com.ar/base-server.sh | sudo sh -x
```

**Comment by lpangaro** [comment]
Efectivamente! Ya pude instalar el server, la interfaz y el tema.
Muchas gracias ☺️
