### ISSUE TITLE
Guest Additions e iso del server que se utilizara para la correccion de las entragas de los TPS

### ISSUE THREAD

**Issue by francomoron** [sisoputnfrba/foro#3368]
#3367 Buenas noches ! 👋 Despues de estar todo el dia intentando configurar virtualbox 😵 con mi computadora, no me quedo otra alternativa que instalar ubuntu desde UTM.
Luego no tuve ningun inconveniente y puede clonar el repo de la catedra y hacer distintas pruebas sin problemas. Queria saber si hay alguna forma de implementar Guesst Aditions en UTM ya que son muy utiles y si debo instalar el server en UTM tambien para probar que todo corre bien ahi tambien. Graciass !!

**Comment by RaniAgus** [comment]
¡Buenas! Asumo que seguiste el video en inglés linkeado a la [guía](https://docs.utnso.com.ar/primeros-pasos/entorno-linux) porque aún no existe soporte para VirtualBox en Mac con M1, ¿cierto?

En el mismo video se explica cómo instalar los drivers para poder resizear la pantalla y compartir el portapapeles entre host y guest a partir del minuto 8:47 (es por eso que les recomendamos seguir viendo el video a partir de ahí).

Saludos

**Comment by francomoron** [comment]
Siiii, ayer no me funcionaba habiendo seguido todos los pasos pero hoy ya esta todo perfecto 🎉
 Muchas gracias por el tiempo !! 🙌
