### ISSUE TITLE
problema de interfaz al correr la VM

### ISSUE THREAD

**Issue by fedeg04** [sisoputnfrba/foro#3369]
Buenas, estoy tratando correr la VM y primero tuve un error que solucioné corriendo fsck de manera manual, pero ahora es como si no cargase la interfaz, y cuando quiero logearme con utnso me dice login incorrecto:

![image](https://github.com/sisoputnfrba/foro/assets/132087687/f90ef156-caca-4b64-8e8a-c97d0134938b)

Por otro lado, cuando la inicio entre todos los OK en verde, aparecen algunos Failed que dicen lo siguiente (son muchos no los llego a leer todos):
- Failed to start light display manager 
- Failed to start system logging service 
- Failed to start openbsd secure shell server

De todas maneras me termina llevando al log in de la imagen que pegué arriba
Gracias!

**Comment by FredeHG** [comment]
El primer error que comentas era de este estilo?
![image](https://github.com/sisoputnfrba/foro/assets/38965532/3516f5a2-9a45-4e63-a89f-324c9803fc38)

Si es así, tenes un problema en la descarga de las imágenes, proba descargándolas de nuevo y podes validar con el checksum que este todo bien cuando descomprimas 👼

**Comment by fedeg04** [comment]
Buenas, al final el problema estaba en que se dañaba la grafica.vdi cuando descomprimía. Lo terminé descomprimiendo con winRar y anduvo. Gracias!
