### ISSUE TITLE
Problema al compilar el server en la máquina sin entorno gráfico

### ISSUE THREAD

**Issue by fedenimi** [sisoputnfrba/foro#3370]
Hola, qué tal? Estamos haciendo la cuarta etapa del tp0. Tenemos un problema a la hora de compilar el server en la máquina sin entorno gráfico. Cuando corremos el comando gcc server.c -o server, nos dice que no reconoce las funciones de las commons. Por ejemplo "/usr/bin/ld: server.c:(.text+0x32): undefined reference to `logger'". No sabemos si estamos haciendo bien las cosas o si falta hacer algo más. Gracias

**Comment by karengrams** [comment]
¡Aló @fedenimi! 

¿Cómo va? Espero que bien. Como primer instancia, me gustaría resaltar que este error se produjo en otros cuatrimestres, especificamente en el issue #3322 o en el #1908, soy fundamentalista de prueba/error, asi que diria de probar las dos soluciones que se mencionaron en esos dos issues.

En caso de no funcionar, me gustaría preguntarte si podias comentarnos como estas compilando el TP0, los comandos que estan utilizando y por fis, el output completo.

¡Gracias de antemano! Y muy buen comienzo de semana.

Kar.

**Comment by fedenimi** [comment]
Muchas gracias, ahí pudimos correr el server en una de las máquinas con el archivo server que se crea en la carpeta bin cuando ejecutamos make. Ahora tenemos otro problema, cuando corremos el cliente en la carpeta bin (en la máquina clonada) nos dice que no se pudo crear el config porque entra en este if:

t_config* iniciar_config(void) {
   t_config *nuevo_config;
   if ((nuevo_config = config_create("./cliente.config")) == NULL) {
       printf("No pude crear el config");
       exit(2);
   }
   return nuevo_config;
}
Lo cual es raro porque cuando lo corremos en la máquina virtual con entorno gráfico, funciona perfectamente. Muchas gracias y buen comienzo de semana para vos también!

**Comment by RaniAgus** [comment]
¡Buenas! Para esto les recomiendo leer la siguiente guía: [Rutas relativas y absolutas](https://docs.utnso.com.ar/guias/consola/rutas)

También, para sumar al problema anterior, cuando ejecuten `make` les recomiendo prestar atención al output que les muestra. Como verán es simplemente un script que ejecuta `gcc` por ustedes pero con un par de flags extra.

El más importante (y la razón del error) es el siguiente: `-lcommons`. Este flag le avisa al compilador que debe vincular ("linkear") la biblioteca commons al ejecutable, para que así al momento de ejecutar se cargue en memoria el código asociado.

Saludos

**Comment by fedenimi** [comment]
Buenísimo! Hicimos eso y pudimos resolver el problema. Muchas gracias!
