### ISSUE TITLE
"Data error" al descomprimir archivos de la VM. No coincide el hash de la Grafica.vdi. 

### ISSUE THREAD

**Issue by sdelperciorodriguez** [sisoputnfrba/foro#3372]
Buen día, me pasa algo igual a los issues #2891 y  #2924, pero no pude solucionar el problema con las respuestas dadas . 

Cuando le doy a "Extract Here" con 7 zip a los archivos "Grafica.zip-001.001" y "VM Entorno Grafico 6.1-20240326T140758Z-002" (los dos archivos en simultaneo) , me extrae la carpeta "VM Entorno Grafico 6.1" (con Grafica.zip.002 adentro) y el archivo "Grafica.vdi". 
7zip me tira los errores "Unexpected end of data" y "Data error: Grafica.vdi". 

Al controlar los hashes, me pasa lo mismo que el issue #2891; los de "Grafica.zip-001.001" y "Grafica.zip.002" me dan bien, excepto el de Grafica.vdi. Probé cambiando el nombre de "Grafica.zip-001.001" como hizo el chico de ese issue pero no me solucionó el problema. Menciona que lo solucionó porque "estaba interpretando mal el cómo descomprimir" pero es una respuesta ambigua. 

También probe lo que hizo la chica del issue #2924, seleccionando ambos archivos (el .001 y el .002) y extraerlos simultaneamente, pero me salta un error más: "Cannot open file as archive". 

Desde ya muchas gracias!

### 🖥️ Especificaciones del host
- Sistema Operativo y versión: Windows 10 Home 22H2 (64 bits)
- Memoria RAM: 16 GB
- Procesador: AMD Ryzen 5 2600

### 💻 Logs

Al extraer los archivos "Grafica.zip-001.001" y "VM Entorno Grafico 6.1-20240326T140758Z-002" simultáneamente:
```
C:\Users\santi\Desktop\SO\Xubuntu (recomendado para desarrollo)\Grafica.zip-001.001
Grafica.zip-001
Unexpected end of data
Data error : Grafica.vdi
```

Al extraer los archivos .001 y .002 como la solución del issue #2924

```
C:\Users\santi\Desktop\SO\Xubuntu (recomendado para desarrollo)\Grafica.zip-001.001
Grafica.zip-001
Unexpected end of data
Data error : Grafica.vdi
C:\Users\santi\Desktop\SO\Xubuntu (recomendado para desarrollo)\Grafica.zip.002
Cannot open file as archive
```

**Comment by mefederico** [comment]
Hola, tuve el mismo problema, lo solucione descargando desde el drive de forma individual los archivos para que google no me genere el archivo `VM Entorno Grafico 6.1-20240326T140758Z-002`, luego pude descomprimir sin problema con 7zip con la opción "extract here" seleccionando ambos archivos

**Comment by sdelperciorodriguez** [comment]
Era eso. Muchas gracias!
