### ISSUE TITLE
Error al leer mensajes de consola TP0

### ISSUE THREAD

**Issue by ValenSampayo** [sisoputnfrba/foro#3373]
Buenas, estoy resolviendo la Etapa 2 del TP0 y me está saltando el siguiente error cuando trata de leer un mensaje de consola: "> Mensaje de consola 1
[1] + Done                       "/usr/bin/gdb" --interpreter=mi --tty=${DbgTerm} 0<"/tmp/Microsoft-MIEngine-In-2i2xvb0x.fta" 1>"/tmp/Microsoft-MIEngine-Out-tkgwqngf.tj4" ".

Cuando el string está vacío también tira un error: "> 
Se cargo un string vacío[1] + Done                       "/usr/bin/gdb" --interpreter=mi --tty=${DbgTerm} 0<"/tmp/Microsoft-MIEngine-In-hkb2jdgc.epx" 1>"/tmp/Microsoft-MIEngine-Out-czbyaq22.ypo" ".

Traté de buscarle una solución en google y se supone que cambiando el atributo "externalConsole" de launch.json a falso se debería solucionar pero ya probé eso y tampoco se soluciona.
El logger y el config funcionan sin problema, los mensajes aparecen en la consola y se guardan en el tp0.log

La función está así:
![image](https://github.com/sisoputnfrba/foro/assets/49347551/06cd5d01-d603-4036-ab16-9157f89c16f4)

El main está así:
![image](https://github.com/sisoputnfrba/foro/assets/49347551/94a19bf9-e135-4178-b346-c99ce19a1af2)
![image](https://github.com/sisoputnfrba/foro/assets/49347551/de377683-f634-4aeb-bcaf-b1b3076bb9b7)

**Comment by RaniAgus** [comment]
PD: Cuidado que acá están retornando del bucle infinito sin liberar la memoria apuntada por `leido`:

```c
if (!seguir) {
    printf("Se cargo un string vacío");
    break;
```

**Comment by ValenSampayo** [comment]
Ahí quedó mas claro, es que cuando lo busque me salió que era un error de Linux y ya me mareo eso.
Ya corrijo lo del memory leak y me anoto lo de las capturas.
Gracias
