### ISSUE TITLE
VM no arranca en linux con secure boot instalado

### ISSUE THREAD

**Issue by marianoSLamaison** [sisoputnfrba/foro#3374]
Estaba tratando de correr la verción grafica de buntu dada por la catedra en mi computadora pero cuando trato esto me da un error "Kernel driver not installed (rc=-1908)"

![Screenshot_2024-03-28_00-57-30](https://github.com/sisoputnfrba/foro/assets/126605894/e29c12e2-e0fa-4cb7-a57a-6ae2d50e7e28)
![segunod_screen_grafica](https://github.com/sisoputnfrba/foro/assets/126605894/c9b8093a-70ce-4a90-af80-1a7696ff76ee)

Busque un poco en internet y parece que es por que tengo el secure boot activado en mi PC, quisiera saber como resolver el problema sin desactivar el secure boot.

### 🔎 Búsqueda en foros

Estos son los sitios que revise

https://superuser.com/questions/1661616/virtualbox-kernel-driver-not-installed-rc-1908

https://stackoverflow.com/questions/38437264/i-cant-execute-command-modprobe-vboxdrv

### 📦 Especificaciones de la VM
- Versión de VirtualBox: La que esta actualmente disponible en el drive de la pagina
- Memoria RAM asignada: 1024

### 🖥️ Especificaciones del host
- Sistema Operativo y versión: Zorin OS lite 16.
- Memoria RAM: 4G
- Procesador: Intel(R) Pentium(R) G3220 3GHZ

**Comment by RaniAgus** [comment]
¡Buenas! El error dice, traducido al español:

> El driver del kernel de Linux de VirtualBox no está instalado o no está configurado correctamente. Por favor, reinstalá el paquete `virtualbox-dkms` y cargá el módulo del kernel ejecutando `modprobe vboxdrv` como root.

> Si tu sistema tiene EFI Secure Boot habilitado podrías también necesitar firmar los módulos del kernel antes de cargarlos. Por favor, buscá la documentación de tu distro de Linux para más información.

Es decir, podría no ser un tema de tener o no el secure boot, sino también que la instalación de VirtualBox esté dañada, lo que me lleva a la pregunta: ¿cómo instalaste VirtualBox?

La forma correcta de hacerlo en Linux es ir a la [página de descargas](https://www.virtualbox.org/wiki/Linux_Downloads) y elegir la que corresponde con tu distro. En tu caso, como estás en Zorin 16, creo que es [Ubuntu 20.04](https://download.virtualbox.org/virtualbox/7.0.14/virtualbox-7.0_7.0.14-161095~Ubuntu~focal_amd64.deb).

Una vez descargado, utilizá `apt` para instalarlo usando `./` para que tome la ruta al archivo:

```sh
sudo apt install ./virtualbox-7.0_7.0.14-161095~Ubuntu~focal_amd64.deb
```

No uses el comando `dpkg`, ya que éste no te va a instalar las dependencias de VirtualBox y va a quedar dañada la instalación.

Saludos

**Comment by marianoSLamaison** [comment]
Probe como usted dijo. Ahora pude ver que era un problema por no registrar el driver que viene con virtual vox.

![aviso_de_secure_boot](https://github.com/sisoputnfrba/foro/assets/126605894/586e0984-46f6-4709-a22b-c2a4724b44de)

La primera vez lo descargue por la tienda de zorin, saca una ventana de aviso tambien pero me puse a hacer algo mas y me olvide de registrar el driver la proxima vez que reinicie la computador

Al descargarlo por consola ya no es tan facil de olvidarse que lo viste jaja. 

Muchisimas gracias por su tiempo.

**Comment by RaniAgus** [comment]
Voy a escribir `VERR_VM_DRIVER_NOT_INSTALLED` porque quería referenciar este issue en uno nuevo y justo ese texto solo aparece en imagen :)

**Comment by marianoSLamaison** [comment]
Perdon, la quise editar y nunca cargo denuevo. Hay la arregle a la imagen
