### ISSUE TITLE
El archivo del zip.001 del drive esta dañado y no puedo instalar la Grafica.vdi

### ISSUE THREAD

**Issue by ManuMar28** [sisoputnfrba/foro#3375]
Descargue los archivos del drive que se encuntran en la seccion de "Maquinas Virtuales" del foro de sistemas operativos, mas concretamente los de xubuntu. Luego de descargar el zip.001 y el 002, intente descomprimir el 001 en una carpeta que tengo creada en el disco C, pero tanto en WinRar como 7-zip me dicen que el archivo esta daño o que se interrumpio la lectura de este previamente.
Aclaro que el hash de ambos zips da bien, pero al descomprimir el 001, el hash de grafica.vli da mal.
![image](https://github.com/sisoputnfrba/foro/assets/83931785/6e85fe68-2423-42d6-b389-7a6ff01a87f1)

**Comment by FredeHG** [comment]
Hola, el error que comentas es muy parecido a este https://github.com/sisoputnfrba/foro/issues/3372, probaste la solucion de ese issue?

**Comment by iago64** [comment]
@ManuMar28 Te sirvió lo que comento Fede? Necesitas que veamos algo mas?

Saludos.-

**Comment by iago64** [comment]
Cerramos el issue por inactividad.
