### ISSUE TITLE
Para clonar los repos en las vms usamos una ssh?

### ISSUE THREAD

**Issue by N3chh** [sisoputnfrba/foro#3376]
Quiero clonar mi repo personal para guardar el tp0 o clonar la estructura del tp, pero no me permite iniciar sesión con mi cuenta, imagino que debería usar una ssh no?

utnso@utnso:~$ git clone https://github.com/N3chh/tp0-entrega.git
Cloning into 'tp0-entrega'...
Username for 'https://github.com': N3chh
Password for 'https://N3chh@github.com': 
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/N3chh/tp0-entrega.git/'

**Comment by RaniAgus** [comment]
¡Buenas! También pueden generar un Personal Access Token de GitHub. En el [TP0](https://docs.utnso.com.ar/primeros-pasos/tp0#despliegue-del-repositorio) les dejamos el link a la docu de GitHub de cómo generar uno:

![image](https://github.com/sisoputnfrba/foro/assets/39303639/137b529d-16d0-4ab1-b4b0-6c7e1ae121bb)

Saludos

**Comment by N3chh** [comment]
Ah se me pasó de largo. Genial, muchas  gracias!

**Comment by iago64** [comment]
Buenas!

Si la duda esta resuelva no se olviden de cerrar el issue 😄 

Saludos.-
