### ISSUE TITLE
Consulta punto 4 tp0

### ISSUE THREAD

**Issue by verocamiz** [sisoputnfrba/foro#3377]
buenas una consulta, estoy en el punto 4 del tp0 y me pide que clone el repo del tp0 con los cambios.. yo clone el repo publico e hice los cambios a partir de ahi, mi duda es: si subo los cambios estoy actualizando el repo publico? o se crea un repo en mi cuenta? o tengo que duplicar yo el repo en mi cuenta y despues subir los cambios?

![image](https://github.com/sisoputnfrba/foro/assets/38118030/7060ff47-a331-4832-af77-43dcbc835019)

**Comment by verocamiz** [comment]
Al final me cree otro repo pero tengo una duda aca, como hago para cambiar la configuracion del cliente? para hacer referencia a la ip del servidor
![image](https://github.com/sisoputnfrba/foro/assets/38118030/75fc70cf-5ddb-4fba-bfa1-c45693b5546a)

**Comment by iago64** [comment]
Buenas! Cómo va?

Vamos en orden con las preguntas:

1.- Repositorio: El repo del tp0 es público para lectura, pero nadie más que los ayudantes tienen permiso para subir cosas, con lo cual, no les queda otra opción que usar un repo de uds.

2.- Desplegarlo en 2 maquinas: Primero que nada es mucho muy importante que lo prueben es una sola VM, ya que eso te va a permitir saber que esta funcionando, al menos la lógica.
Ahora para desplegarlo en una segunda máquina, si leiste la [guía de sockets](https://docs.utnso.com.ar/guias/linux/sockets) a detalle y no de forma rápida para marcar el check de haberla leído, deberías haber encontrado que hay una función que justamente te traduce la ip y el puerto a algo que interpreta C y es la función `getaddrinfo()`. Por lo que para conectarte entre 2 máquinas es importante que a esa función le pases de alguna manera las IP de las VMs.
En el caso del servidor tenes que poner su ip propia o `NULL`, mientras que en el caso del cliente, tenes que pasarle la IP de la máquina que va a tener corriendo el servidor.

Saludos.-

**Comment by verocamiz** [comment]
_2.- Desplegarlo en 2 maquinas: Primero que nada es mucho muy importante que lo prueben es una sola VM, ya que eso te va a permitir saber que esta funcionando, al menos la lógica._

Disculpa que vuelva a repreguntar pero no estoy entendiendo como correr la app, que comando usar dentro de la vm

_Ahora para desplegarlo en una segunda máquina, si leiste la [guía de sockets](https://docs.utnso.com.ar/guias/linux/sockets) a detalle y no de forma rápida para marcar el check de haberla leído, deberías haber encontrado que hay una función que justamente te traduce la ip y el puerto a algo que interpreta C y es la función getaddrinfo(). Por lo que para conectarte entre 2 máquinas es importante que a esa función le pases de alguna manera las IP de las VMs.
En el caso del servidor tenes que poner su ip propia o NULL, mientras que en el caso del cliente, tenes que pasarle la IP de la máquina que va a tener corriendo el servidor._

Entiendo, esto de las IP se configura a nivel de codigo cierto? tengo que modificar las ip en el repo

**Comment by verocamiz** [comment]
> Buenas! Cómo va?
> 
> Vamos en orden con las preguntas:
> 
> 1.- Repositorio: El repo del tp0 es público para lectura, pero nadie más que los ayudantes tienen permiso para subir cosas, con lo cual, no les queda otra opción que usar un repo de uds.
> 
> 2.- Desplegarlo en 2 maquinas: Primero que nada es mucho muy importante que lo prueben es una sola VM, ya que eso te va a permitir saber que esta funcionando, al menos la lógica. Ahora para desplegarlo en una segunda máquina, si leiste la [guía de sockets](https://docs.utnso.com.ar/guias/linux/sockets) a detalle y no de forma rápida para marcar el check de haberla leído, deberías haber encontrado que hay una función que justamente te traduce la ip y el puerto a algo que interpreta C y es la función `getaddrinfo()`. Por lo que para conectarte entre 2 máquinas es importante que a esa función le pases de alguna manera las IP de las VMs. En el caso del servidor tenes que poner su ip propia o `NULL`, mientras que en el caso del cliente, tenes que pasarle la IP de la máquina que va a tener corriendo el servidor.
> 
> Saludos.-

2.- Desplegarlo en 2 maquinas: Primero que nada es mucho muy importante que lo prueben es una sola VM, ya que eso te va a permitir saber que esta funcionando, al menos la lógica.

Disculpa que vuelva a repreguntar pero no estoy entendiendo como correr la app, que comando usar dentro de la vm

Ahora para desplegarlo en una segunda máquina, si leiste la [guía de sockets](https://docs.utnso.com.ar/guias/linux/sockets) a detalle y no de forma rápida para marcar el check de haberla leído, deberías haber encontrado que hay una función que justamente te traduce la ip y el puerto a algo que interpreta C y es la función getaddrinfo(). Por lo que para conectarte entre 2 máquinas es importante que a esa función le pases de alguna manera las IP de las VMs.
En el caso del servidor tenes que poner su ip propia o NULL, mientras que en el caso del cliente, tenes que pasarle la IP de la máquina que va a tener corriendo el servidor.

Entiendo, esto de las IP se configura a nivel de codigo cierto? tengo que modificar las ip en el repo

**Comment by verocamiz** [comment]
En el caso del servidor estaria en null entonces 
![image](https://github.com/sisoputnfrba/foro/assets/38118030/ac2e6bd1-1c43-46c5-bc48-905ca370cc3e)

y para el cliente modifico la ip dentro del archivo cliente.config cierto?
![image](https://github.com/sisoputnfrba/foro/assets/38118030/2beffe46-1ce3-407a-9e1d-aa060450f2ed)

**Comment by verocamiz** [comment]
update, ahi pude correr el serv pero el cliente me da error 
![image](https://github.com/sisoputnfrba/foro/assets/38118030/150a5963-e3b6-4edf-b73e-75977fbe701b)

**Comment by RaniAgus** [comment]
¡Buenas! Si en la VM gráfica prueban de ejecutar ambos desde una consola (NO desde code), ¿también tienen el mismo problema? Saludos

**Comment by RaniAgus** [comment]
Bien, significa que el error no ocurre en la VM server, sino que es algo que tiene que ver con cómo ejecuta VSCode y cómo ejecuta uno en la terminal.

Antes que nada, ¿manejaron el caso en el que hubo un error al crear la config como se sugiere en el enunciado del TP0?

Revisen la documentación de [config.h](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/config.h#L35) para más info.

Saludos

**Comment by verocamiz** [comment]
En que parte de la doc explican eso del error?

**Comment by RaniAgus** [comment]
Antes que nada, les recomiendo encarecidamente que lean el [README del foro](https://github.com/sisoputnfrba/foro/blob/master/README.md) ya que en él se encuentran algunos consejos sobre cómo redactar issues, entre ellos, desaconsejamos el uso de capturas de pantalla, ya que:

1. Como ayudantes no podemos copiar el texto, por lo que nos es más difícil reproducir el error o hacer búsquedas en otros foros. La única ayuda que podremos darle será "a ojo". Como en este caso el error se puede observar bien los puedo ayudar, pero sepan que en otros casos más complejos me darían una mano enorme si pudiera copiar y pegarlo 😢
2. El buscador de issues no reconoce texto en imágenes, por lo que a quienes quieran usarlo les va a ser más difícil encontrar ese issue en caso de tener la misma duda.

Dicho esto, sí, es ese el manejo de errores al que hago referencia. Supongo que ya sabrán cómo funciona la sentencia `return`: la misma _retorna_ de la función que se está ejecutando. 

Si justo están ejecutando la función `main()` eso significa que el programa finaliza, por lo que no tendrían este problema, pero desde **cualquier** otra función, esta sentencia solo retorna para continuar ejecutando la función que la llamó.

En este caso, en el lugar que hayan llamado a `iniciar_config()` el programa va a continuar ejecutando con un puntero inválido y luego se producirá el `segmentation fault`.

A lo que íbamos con este warning en el TP0:
![image](https://github.com/sisoputnfrba/foro/assets/39303639/c1e324b0-6e23-4516-ae74-d675a9938eee)

Es a que primero impriman por pantalla un mensaje avisando el motivo del error (en este caso, algo como "¡No se pudo crear el config!"), y luego lo finalicen llamando a la función `exit()` con un valor de error (o sea, no cero).

Saludos

**Comment by verocamiz** [comment]
> Antes que nada, les recomiendo encarecidamente que lean el [README del foro](https://github.com/sisoputnfrba/foro/blob/master/README.md) ya que en él se encuentran algunos consejos sobre cómo redactar issues, entre ellos, desaconsejamos el uso de capturas de pantalla, ya que:
> 
> 1. Como ayudantes no podemos copiar el texto, por lo que nos es más difícil reproducir el error o hacer búsquedas en otros foros. La única ayuda que podremos darle será "a ojo". Como en este caso el error se puede observar bien los puedo ayudar, pero sepan que en otros casos más complejos me darían una mano enorme si pudiera copiar y pegarlo 😢
> 2. El buscador de issues no reconoce texto en imágenes, por lo que a quienes quieran usarlo les va a ser más difícil encontrar ese issue en caso de tener la misma duda.
> 
> Dicho esto, sí, es ese el manejo de errores al que hago referencia. Supongo que ya sabrán cómo funciona la sentencia `return`: la misma _retorna_ de la función que se está ejecutando.
> 
> Si justo están ejecutando la función `main()` eso significa que el programa finaliza, por lo que no tendrían este problema, pero desde **cualquier** otra función, esta sentencia solo retorna para continuar ejecutando la función que la llamó.
> 
> En este caso, en el lugar que hayan llamado a `iniciar_config()` el programa va a continuar ejecutando con un puntero inválido y luego se producirá el `segmentation fault`.
> 
> A lo que íbamos con este warning en el TP0: ![image](https://private-user-images.githubusercontent.com/39303639/318105989-c1e324b0-6e23-4516-ae74-d675a9938eee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MzM5NjMsIm5iZiI6MTcxMTczMzY2MywicGF0aCI6Ii8zOTMwMzYzOS8zMTgxMDU5ODktYzFlMzI0YjAtNmUyMy00NTE2LWFlNzQtZDY3NWE5OTM4ZWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDE3MzQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMGM1ZTIyMDUwNTdiZWU0MDAxMDVkY2EyZGU0MTRmNWNmODk2Nzk1ZTgxNDFiNzFmZWNlYzIxOTI3ZWVjOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9ww7zkcL0ApFB7vgOsQewu2zYA3fvZRQDxu3T9KbPm4)
> 
> Es a que primero impriman por pantalla un mensaje avisando el motivo del error (en este caso, algo como "¡No se pudo crear el config!"), y luego lo finalicen llamando a la función `exit()` con un valor de error (o sea, no cero).
> 
> Saludos

Entiendo no hay problema! Agregue esto y me sale el mensaje de error al correrlo por consola 
`t_config* iniciar_config()
{
	t_config* nuevo_config;

	nuevo_config = config_create("./cliente.config");

	if (nuevo_config == NULL) {
    t_log* nuevo_logger;
	nuevo_logger = log_create("tp0.log", "error_config", true, LOG_LEVEL_INFO);
	log_info(nuevo_logger, "Error al crear el config");
	exit(500);
	}

	return nuevo_config;
}`

`t_config* iniciar_config()
{
	t_config* nuevo_config;

	nuevo_config = config_create("./cliente.config");

	if (nuevo_config == NULL) {
    t_log* nuevo_logger;
	nuevo_logger = log_create("tp0.log", "error_config", true, LOG_LEVEL_INFO);
	log_info(nuevo_logger, "Error al crear el config");
	exit(500);
	}

	return nuevo_config;
}`

**Comment by RaniAgus** [comment]
Genial, entonces ya sabemos que el problema está al intentar leer la config. Probablemente tenga que ver con un problema de [rutas relativas](https://docs.utnso.com.ar/guias/consola/rutas) para llegar hasta el config que tienen guardado. Lean esa guía y avísennos si tuvieron algún problema.

**Comment by verocamiz** [comment]
puede ser que me este faltando modificar algo aca?
CLAVE=valor
IP=192.168.0.198
PUERTO=4444

solo modifique la IP

**Comment by verocamiz** [comment]
> Genial, entonces ya sabemos que el problema está al intentar leer la config. Probablemente tenga que ver con un problema de [rutas relativas](https://docs.utnso.com.ar/guias/consola/rutas) para llegar hasta el config que tienen guardado. Lean esa guía y avísennos si tuvieron algún problema.

la ruta cambia si lo ejecuto desde la consola?

**Comment by RaniAgus** [comment]
Justo en el comment dejé linkeada la guía que habla en detalle sobre el tema: https://docs.utnso.com.ar/guias/consola/rutas

**Comment by verocamiz** [comment]
Ahi estuve probando, puedo ver que si son diferentes, pero no veo que estoy haciendo mal
agregue lo siguiente
`char* config;
   config = malloc(strlen(current_dir)+ strlen("/cliente.config")); /* make space for the new string (should check the return value ...) */
strcpy(config, current_dir); /* copy name into the new var */
strcat(config, "/cliente.config"); 
	nuevo_config = config_create(config);`
![image](https://github.com/sisoputnfrba/foro/assets/38118030/b7203cbd-f9d5-4f50-9c38-cab8ce0aa596)

En VSC sigue corriento bien y en la consola sigue tirando error

en vsc esta es la ruta: El directorio actual es /home/utnso/tp0-local/client

En consola: El directorio actual es /home/utnso/tp0-local/client/bin

**Comment by RaniAgus** [comment]
> en vsc esta es la ruta: El directorio actual es /home/utnso/tp0-local/client

> En consola: El directorio actual es /home/utnso/tp0-local/client/bin

¡Exacto! Si te fijás bien vas a ver que la ruta desde la cual estás ejecutando desde consola es distinta a la ruta que ejecuta VSCode. Podés probar con ejecutar desde la consola de la forma que se sugiere al final de la guía.

**Comment by verocamiz** [comment]
Ahi pude!
Yo estaba haciendo cd client/bin y despues ./client
al hacer cd client y despues ./bin/client como dice aca me dejo:
![image](https://github.com/sisoputnfrba/foro/assets/38118030/396074f6-b086-476f-be59-8fcc5a6e95a0)

![image](https://github.com/sisoputnfrba/foro/assets/38118030/74ba40cd-be15-43f9-af33-c269b42fa514)

**Comment by verocamiz** [comment]
claro ahi estoy viendo que al ejecutar la VM que cree con el cliente no esta esperando a recibir los mensajes para mandar por paquete al servidor como si hace en la consola que te mostre recien. Puede tener que ver con el path tambien?
![image](https://github.com/sisoputnfrba/foro/assets/38118030/5638dbd9-c28e-42a1-8ff4-1cfb70c95828)

**Comment by RaniAgus** [comment]
Hmmm lo que veo acá:

![image](https://github.com/sisoputnfrba/foro/assets/39303639/69a0b458-f1e5-4e40-860b-2e2a168b1279)

Es que el programa está finalizando después de imprimir "Soy un logger :)" y estás tipeando `asd` en la terminal, lo cual no es un comando que esté instalado en las VMs 🤔. Estaría bueno tener un mensajito de error antes de finalizar así podemos investigar mejor el motivo.

¿Levantaste el server en la otra VM? ¿Editaste la config del cliente para que apunte a la IP del server?

**Comment by verocamiz** [comment]
Levante el server desde una VM, la clone y en la que clone levante el cliente. edite la IP del config.cliente para que apunte al servidor:
CLAVE=valor
IP=192.168.0.198
PUERTO=4444

**Comment by verocamiz** [comment]
no se esta conectando con el servidor en la VM
![image](https://github.com/sisoputnfrba/foro/assets/38118030/4984a067-04a4-4128-81e9-8abeff52b4b4)

**Comment by RaniAgus** [comment]
Lo que estoy viendo ahí es que la IP del **cliente** es 192.168.0.198... ¿la del server es igual? Si es así probá con cambiar el adaptador de red como hizo el chico de https://github.com/sisoputnfrba/foro/issues/3378#issuecomment-2027445331 porque deberían tener IPs distintas.

**Comment by RaniAgus** [comment]
También de nuevo estoy viendo lo mismo que antes:
![image](https://github.com/sisoputnfrba/foro/assets/39303639/3ccf4022-7c54-4161-8c8c-6acec66c8cac)

El cliente nunca llega a conectarse y finaliza. Repito, si pudiéramos contar con algún log o printf antes de hacer el `exit()` o el `return` desde `main()` estaría buenísimo para entender dónde podría estar fallando.

**Comment by RaniAgus** [comment]
Entonces el error no está ahí y hay que agregar un mensaje de error más adelante :)

**Comment by verocamiz** [comment]
en mi caso solo tengo una opcion y no me aparecen las opciones que mencionas en el otro issue
![image](https://github.com/sisoputnfrba/foro/assets/38118030/4c38e2b4-322f-4018-b276-b1ce5c8e0844)

**Comment by verocamiz** [comment]
Igual ahi probando otras config pude hacer que se conectaran. Cambie en client el conectado a: NAT
![image](https://github.com/sisoputnfrba/foro/assets/38118030/5e227c65-89bd-4c5b-912b-f8ecc6c4a9aa)

**Comment by RaniAgus** [comment]
Mmm entiendo que funcionará ahora, pero en el TP cuando tengan varias VMs que se conectan entre sí no les va a funcionar.

Probá de volverlo a configurar como "Bridged Adapter", abrir una consola y ejecutarte estas 3 líneas:
```sh
sudo rm -rf /var/lib/dbus/machine-id /etc/machine-id
sudo dbus-uuidgen --ensure=/etc/machine-id
sudo systemctl restart systemd-networkd
```

Si funciona todo bien, lo agregamos a la guía :)

**Comment by verocamiz** [comment]
> Mmm entiendo que funcionará ahora, pero en el TP cuando tengan varias VMs que se conectan entre sí no les va a funcionar.
> 
> Probá de volverlo a configurar como "Bridged Adapter", abrir una consola y ejecutarte estas 3 líneas:
> 
> ```shell
> sudo rm -f /etc/machine-id
> sudo dbus-uuidgen --ensure=/etc/machine-id
> sudo reboot
> ```
> 
> Si después de reiniciar funciona todo bien, lo agregamos a la guía :)

Ahi probe cambiando nuevamente a bridge adapter y ejecutar esos comandos.
Me cambio la IP del cliente y ahi si me dejo correrlo bien nuevamente. Gracias!
![image](https://github.com/sisoputnfrba/foro/assets/38118030/8b4b9ff6-0cb1-4ec1-876c-34d591a2eef6)

**Comment by RaniAgus** [comment]
¡Buenísimo! Si no quedan más dudas podés cerrar el issue :)

**Comment by ahuarca** [comment]
Hola! Tengo una duda, cambiaste la configuración de la IP solo  en el archivo de la config dentro de la  VM del cliente o también lo hiciste en la VM del servidor?

**Comment by iago64** [comment]
@ahuarca Cómo va? Si tenes alguna duda crea un issue nuevo y hace referencia a este issue.
