### ISSUE TITLE
Misma IP en la Ubuntu Server y su clon (Etapa 4 del TP0)

### ISSUE THREAD

**Issue by AgustinCarlanaRivero** [sisoputnfrba/foro#3378]
Hola, buenas. Probé el código que hice del tp0 desde 2 consolas del XUbuntu, y funcionaba a la perfección. Ahora, al momento de hacer lo indicado en la etapa 4, es decir, probarlo en la Ubuntu Server y su clon, daba un error cuando el cliente intentaba enviar un mensaje (en la función connect). Luego de esto, me percaté de que ambas maquinas virtuales tenían la misma IP.  Mi duda es si existe una forma de evitar una asignación de IP manual, y hacer que directamente no se generen dos IP iguales, o simplemente saber el por qué ocurre esto.

### 💭 Soluciones posibles
Le pregunté a Chat GPT como asignar una IP manualmente (lo cual consistió en hacer "sudo nano /etc/netplan/00-installer-config.yaml" y editar el archivo). Hice eso en el clon, y ahí sí me funcionó. Es por eso que mi duda no es tanto "cómo hacer que funcione", si no más "como hacer para no tener que asignar la IP manualmente".

**Comment by RaniAgus** [comment]
¡Buenas! 

Estuve haciendo algunas pruebas y al parecer solo tengo ese problema cuando estoy conectado por WiFi, pero no tengo ningún problema conectándome por LAN.


Parece que cambiando el adaptador de `enp` a `wlp` mi router sí me asignó una IP distinta:

![image](https://github.com/sisoputnfrba/foro/assets/39303639/2e6418b4-8799-48be-b295-cca7e05d9364)

Prueben haciendo ese cambio a ver si en su caso también se resuelve.

Saludos

**Comment by AgustinCarlanaRivero** [comment]
Entiendo lo que decis, sin embargo, en mi PC figuran distintos esos nombres:

![image](https://github.com/sisoputnfrba/foro/assets/138989637/fabe3cfc-5858-42dd-bf23-b3d820dfc07d)

Pese a eso, decidí ponerme a probar cada opción, y acá los resultados:
- La que dice Intel, si me conecto al internet por Wi-Fi se asignan IPs iguales, y si lo hago por cable la máquina virtual no se termina de iniciar.
- La que dice Realtek, si me conecto al internet por Wi-Fi la máquina virtual no se termina de iniciar, y si lo hago por cable se asignan IPs iguales
- Ahora, la que dice Microsoft, tanto por cable como por Wi-Fi funciona. Me asigna IPs distintas, pero son de la forma 192.168.137.X

El error de cuando no termina de iniciar la maquina virtual, es este:
![image](https://github.com/sisoputnfrba/foro/assets/138989637/b057bb5b-7242-425d-bd77-f6e6625e5518)

Ahora, por qué ocurre todo esto?? Muchas gracias de antemano.

**Comment by RaniAgus** [comment]
Gracias por probar, es bueno saberlo.

Entonces con la opción Microsoft Wi-Fi Direct Virtual Adapter pudieron obtener IPs distintas, ¿no?

**Comment by AgustinCarlanaRivero** [comment]
Si, aunque no entiendo por qué la IP es de la forma 192.168.137.X, ni por qué no funcionaba antes... ¿Es cuestión del Router, de la PC, o de qué?

**Comment by RaniAgus** [comment]
Ahí estuve investigando y según [este post](https://unix.stackexchange.com/questions/419321/why-are-my-cloned-linux-vms-fighting-for-the-same-ip/419322#419322) tiene que ver con que ambas VMs tienen el mismo contenido en el archivo `/etc/machine-id`, que es el que utiliza el DHCP server para retornar la IP.

Si te animás, probá a volver a como estaba configurado antes y ejecutá estas 3 líneas:

```sh
sudo rm -rf /var/lib/dbus/machine-id /etc/machine-id
sudo dbus-uuidgen --ensure=/etc/machine-id
sudo systemctl restart systemd-networkd
```

Eso debería asignarte una nueva IP. Si es así, lo agregamos a la guía :)

Saludos

**Comment by AgustinCarlanaRivero** [comment]
Funcionó a la perfección! Y es una solución más sencilla y directa que la que decía Chat GPT.  Asi que, muchas gracias!
