### ISSUE TITLE
Dudas con respecto al codigo "client.c" del TP0

### ISSUE THREAD

**Issue by EzequielSecchi** [sisoputnfrba/foro#3380]
¡Hola! ¡buenas tardes! tengo una duda que me surgio de este codigo cuando lo abri en mi visual estudio, y es que, cuando abro el codigo, instantaneamente me tira este error en la linea del include

![image](https://github.com/sisoputnfrba/foro/assets/164372726/28a06f3d-bf22-4e6b-b27c-fce4255a388e)

es un problema de mi visual studio eso? estoy usando la maquina virtual Xubuntu para abrir el codigo

**Comment by RaniAgus** [comment]
¡Buenas! En la [etapa 1](https://docs.utnso.com.ar/primeros-pasos/tp0#etapa-1-setup-inicial) del TP0 van a ver cómo importar el repo en VSCode. Spoiler: no es abriendo la carpeta del repo. Saludos

**Comment by EzequielSecchi** [comment]
aaah perfecto, muchas gracias!

**Comment by iago64** [comment]
Buenas! 

Si la duda esta resuelta, no se olviden de cerrar el issue. 👮 

Saludos.-
