### ISSUE TITLE
Instalacion de so-commons-library

### ISSUE THREAD

**Issue by TomasLVUTN** [sisoputnfrba/foro#3381]
Hola, estoy intentando descargar e instalar las bibliotecas, pero estoy teniendo inconvenientes en la misma.

_git clone https://github.com/sisoputnfrba/so-commons-library
cd so-commons-library
make debug
make install_

El repositorio lo pude clonar sin problemas, el inconveniente esta en el tercer paso, donde comienza a tirar errores. Primero me mencionaba que el error se debía a que el acceso había sido denegado, eso lo "solucione" brindándole acceso a todos los usuarios (igualmente no se en que podía cambiar, ya que es el único de la maquina) Ese error desapareció, pero sigo sin poder instalarlo

Adjunto el log
### 💻 Logs
`$ cd so-commons-library

dell17@LAPTOP-GPEDA3KI MINGW64 ~/Desktop/New folder/so-commons-library (master)
$ make debug
cd src && /usr/bin/make debug
make[1]: Entering directory `/c/Users/dell17/Desktop/New folder/so-commons-library/src'
gcc -DDEBUG -g -c -fmessage-length=0 -fPIC -MMD -MP -MF"build/commons/bitarray.d" -MT"build/commons/bitarray.d" -o "build/commons/bitarray.o" "commons/bitarray.c"
gcc -DDEBUG -g -c -fmessage-length=0 -fPIC -MMD -MP -MF"build/commons/collections/dictionary.d" -MT"build/commons/collections/dictionary.d" -o "build/commons/collections/dictionary.o" "commons/collections/dictionary.c"
gcc -DDEBUG -g -c -fmessage-length=0 -fPIC -MMD -MP -MF"build/commons/collections/list.d" -MT"build/commons/collections/list.d" -o "build/commons/collections/list.o" "commons/collections/list.c"
gcc -DDEBUG -g -c -fmessage-length=0 -fPIC -MMD -MP -MF"build/commons/collections/queue.d" -MT"build/commons/collections/queue.d" -o "build/commons/collections/queue.o" "commons/collections/queue.c"
gcc -DDEBUG -g -c -fmessage-length=0 -fPIC -MMD -MP -MF"build/commons/config.d" -MT"build/commons/config.d" -o "build/commons/config.o" "commons/config.c"
gcc -DDEBUG -g -c -fmessage-length=0 -fPIC -MMD -MP -MF"build/commons/error.d" -MT"build/commons/error.d" -o "build/commons/error.o" "commons/error.c"
gcc -DDEBUG -g -c -fmessage-length=0 -fPIC -MMD -MP -MF"build/commons/log.d" -MT"build/commons/log.d" -o "build/commons/log.o" "commons/log.c"
gcc -DDEBUG -g -c -fmessage-length=0 -fPIC -MMD -MP -MF"build/commons/memory.d" -MT"build/commons/memory.d" -o "build/commons/memory.o" "commons/memory.c"
gcc -DDEBUG -g -c -fmessage-length=0 -fPIC -MMD -MP -MF"build/commons/process.d" -MT"build/commons/process.d" -o "build/commons/process.o" "commons/process.c"
commons/process.c:22:10: fatal error: sys/syscall.h: No such file or directory
   22 | #include <sys/syscall.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [build/commons/process.o] Error 1
make[1]: Leaving directory `/c/Users/dell17/Desktop/New folder/so-commons-library/src'
make: [debug] Error 2 (ignored)
cd tests/unit-tests && /usr/bin/make debug
make[1]: Entering directory `/c/Users/dell17/Desktop/New folder/so-commons-library/tests/unit-tests'
cd ../.. && git submodule init && git submodule update
cd ../../cspec && /usr/bin/make all
make[2]: Entering directory `/c/Users/dell17/Desktop/New folder/so-commons-library/cspec'
mkdir -p release/cspecs/
gcc -c -fmessage-length=0 -fPIC -MMD -MP -MF"release/cspecs/cspec.d" -MT"release/cspecs/cspec.d" -o "release/cspecs/cspec.o" "cspecs/cspec.c"
gcc -shared -o "release/libcspecs.so" release/cspecs/cspec.o
make[2]: Leaving directory `/c/Users/dell17/Desktop/New folder/so-commons-library/cspec'
cd ../../src && /usr/bin/make all
make[2]: Entering directory `/c/Users/dell17/Desktop/New folder/so-commons-library/src'
gcc -c -fmessage-length=0 -fPIC -MMD -MP -MF"build/commons/process.d" -MT"build/commons/process.d" -o "build/commons/process.o" "commons/process.c"
commons/process.c:22:10: fatal error: sys/syscall.h: No such file or directory
   22 | #include <sys/syscall.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [build/commons/process.o] Error 1
make[2]: Leaving directory `/c/Users/dell17/Desktop/New folder/so-commons-library/src'
make[1]: [../../src/build/libcommons.so] Error 2 (ignored)
gcc -DDEBUG -g -I"../../src" -I"../../cspec" -c -fmessage-length=0 -fPIC -MMD -MP -MF"build/test_bitarray.d" -MT"build/test_bitarray.d" -o "build/test_bitarray.o" "test_bitarray.c"
gcc -DDEBUG -g -I"../../src" -I"../../cspec" -c -fmessage-length=0 -fPIC -MMD -MP -MF"build/test_config.d" -MT"build/test_config.d" -o "build/test_config.o" "test_config.c"
gcc -DDEBUG -g -I"../../src" -I"../../cspec" -c -fmessage-length=0 -fPIC -MMD -MP -MF"build/test_dictionary.d" -MT"build/test_dictionary.d" -o "build/test_dictionary.o" "test_dictionary.c"
gcc -DDEBUG -g -I"../../src" -I"../../cspec" -c -fmessage-length=0 -fPIC -MMD -MP -MF"build/test_list.d" -MT"build/test_list.d" -o "build/test_list.o" "test_list.c"
gcc -DDEBUG -g -I"../../src" -I"../../cspec" -c -fmessage-length=0 -fPIC -MMD -MP -MF"build/test_memory.d" -MT"build/test_memory.d" -o "build/test_memory.o" "test_memory.c"
gcc -DDEBUG -g -I"../../src" -I"../../cspec" -c -fmessage-length=0 -fPIC -MMD -MP -MF"build/test_queue.d" -MT"build/test_queue.d" -o "build/test_queue.o" "test_queue.c"
gcc -DDEBUG -g -I"../../src" -I"../../cspec" -c -fmessage-length=0 -fPIC -MMD -MP -MF"build/test_string.d" -MT"build/test_string.d" -o "build/test_string.o" "test_string.c"
gcc -DDEBUG -g -L"../../src/build" -L"../../cspec/release" -o "build/commons-unit-test" build/test_bitarray.o build/test_config.o build/test_dictionary.o build/test_list.o build/test_memory.o build/test_queue.o build/test_string.o -lcommons -lcspecs
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: cannot find -lcommons
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: cannot find -lcspecs
collect2.exe: error: ld returned 1 exit status
make[1]: *** [build/commons-unit-test] Error 1
make[1]: Leaving directory `/c/Users/dell17/Desktop/New folder/so-commons-library/tests/unit-tests'
make: [debug] Error 2 (ignored)`

gracias

**Comment by TomasLVUTN** [comment]
![image](https://github.com/sisoputnfrba/foro/assets/112028448/8700d8af-5867-4026-a456-1bd9520b6570)

**Comment by RaniAgus** [comment]
¡Buenas! Como vi un "MINGW64" asumo que estás desde Windows. Te aconsejo primero leer la guía de [Cómo conseguir un entorno Linux](https://docs.utnso.com.ar/primeros-pasos/entorno-linux) ya que el TP debe ser desarrollado, compilado y ejecutado en un entorno linux. Saludos

**Comment by TomasLVUTN** [comment]
Evidentemente era eso! Mala mia! Gracias

**Comment by TomasLVUTN** [comment]
Gracias
