### ISSUE TITLE
Problema con el codigo del tp0

### ISSUE THREAD

**Issue by EzequielSecchi** [sisoputnfrba/foro#3383]
Hola! buenos dias. Hace unos dias hice una duda sobre un error de codigo que tenia en el archivo "client.c". Al seguir los pasos de la guia del tp0 lo logre resolver, ahora puse las funciones log_create(), log_info() y log_destry() tal y como dice en la guia del tp0. Pero cuando lo compilo, ahora me da este error:

![image](https://github.com/sisoputnfrba/foro/assets/164372726/4ee57fa9-d4c4-4d2b-b536-10be8743eb11)

este error me aparece al compilar el archivo, y me aparece en el archivo "utils.h". Segui la guia paso a paso y me sigue sucediendo lo mismo ¿Que es lo que puede estar provocando este error?

**Comment by RaniAgus** [comment]
¡Buenas! ¿Seguiste la guía de [crear un proyecto en C](https://docs.utnso.com.ar/primeros-pasos/primer-proyecto-c)?
Tengan en cuenta que el orden de las guías en la sección "Primeros Pasos" es por algo: si no tienen instaladas las commons no van a poder avanzar con el TP0. Saludos

**Comment by EzequielSecchi** [comment]
aah okay perfecto, gracias!
