### ISSUE TITLE
Error en Run and Debug: "The preLaunchTask 'C/C++: gcc build active file' terminated with exit code -1."

### ISSUE THREAD

**Issue by MarianelaBen** [sisoputnfrba/foro#3385]
Estoy empezando la etapa 2 del TP0, por ahora lo que hice fué crear un logger y posteriormente cerrarlo al final del programa. El problema está cuando quiero compilar y ejecutar el programa con "Run and Debug", se abre la terminal pero aparece un cartel con el siguiente mensaje: "The preLaunchTask 'C/C++: gcc build active file' terminated with exit code -1."

Tampoco me aparecen las opciones para ejecutar desde "run(client)", sólo hay un botón azul que dice "Run and Debug"

Alguien sabe cuál puede ser el problema? Desde ya, muchas gracias

**Comment by RaniAgus** [comment]
¡Buenas! Te invito a leer más detenidamente la [etapa 1](https://docs.utnso.com.ar/primeros-pasos/tp0#etapa-1-setup-inicial) del TP0 ya que el error me da a entender que no llegaste a abrirlo como se indica ahí, y no te está tomando las configuraciones que les proveemos por eso. Saludos

**Comment by MarianelaBen** [comment]
Ahí lo pude solucionar, volví a clonar el repo y ahora funciona. Creo que el problema fué que cuando escribí el comando code, después de clonar el repositorio, no puse "tp0.code-workspace", sino que escribí "code ." directamente.

**Comment by MarianelaBen** [comment]
Ahí lo pude solucionar, volví a clonar el repo y ahora funciona. Creo que el problema fué que cuando escribí el comando code, después de clonar el repositorio, no puse "tp0.code-workspace", sino que escribí "code ." directamente.
