### ISSUE TITLE
No me deja enviar los paquetes desde el cliente al server- Punto 4

### ISSUE THREAD

**Issue by ahuarca** [sisoputnfrba/foro#3386]
Hola! A la hora de enviar los mensajes desde el cliente al servidor, se me corta el programa por decirlo así  y se me termina la conexión

![Captura de pantalla (77)](https://github.com/sisoputnfrba/foro/assets/163689778/d29b6c53-09c5-4cd9-8b06-26ae38af912f)

como vi en el issue #3377  que configuraron la ruta de la función inicio del config, me preguntaba si tenia que hacer lo mismo, aunque mi código es distinto ya que le puse la dirección de esta forma porque sino no me leía la config
![Captura de pantalla (78)](https://github.com/sisoputnfrba/foro/assets/163689778/bff4e062-a07f-4486-be95-f8341a671387)

**Comment by RaniAgus** [comment]
¡Buenas! El `/Debug` que veo ahí me indica que quizás tengas descargada una versión más antigua del TP0 en la que nos basábamos puramente en Eclipse. Te recomiendo lo siguiente:

1) Volvé atrás a la [guía de primer proyecto en C](https://docs.utnso.com.ar/primeros-pasos/primer-proyecto-c). Es bastante diferente a la de cuatrimestres anteriores ya que explica paso a paso cómo compilar y ejecutar tanto desde VSCode como **desde la consola**. Es muy valioso sobre todo que hagas foco en esto último.

2) Luego del paso 1, volvé a hacer la etapa 1 del TP0 utilizando la **última versión**, ya que también te va a servir para cuando importes la estructura de TP que les proveemos al generar el repositorio del grupo.

3) Volvé a revisar el problema que tuviste al cargar la config, muy probablemente tenga que ver con lo que mencionamos en [esta guía](https://docs.utnso.com.ar/guias/consola/rutas).

Por último, si tu grupo está evaluando cambiarse a Eclipse tenemos [una guía para eso](https://docs.utnso.com.ar/guias/herramientas/eclipse) que pueden seguir para el TP0, pero puede que les tome un ratito seguirla ya que todo el setup tiene que ser a mano (no se puede guardar en el repo y que quede para todos).

Saludos

**Comment by ahuarca** [comment]
Dale, lo hago y te aviso!

**Comment by iago64** [comment]
@ahuarca Cómo va?

Pudiste probar lo que te dijo @RaniAgus?

Saludos.-

**Comment by TotiGonzalez** [comment]
Hola, estoy con el mismo problema, y eso que estoy en la ultima version del tp. Estoy haciendo todo en el VSCode y ejecutandolo por consola alli mismo. Adjunto imagenes: 
![Captura de pantalla 2024-04-02 001225](https://github.com/sisoputnfrba/foro/assets/83785951/d2453d5c-dd63-4762-b03a-895af9269ab1)
![Captura de pantalla 2024-04-02 001238](https://github.com/sisoputnfrba/foro/assets/83785951/677383e3-b516-43af-ba2e-470ac35e87d6)

**Comment by iago64** [comment]
Buenas! Cómo va?

Algo interesante de los programas es que cuando se quedan sin instrucciones estos terminan, en el caso del cliente, efectivamente termina porque si se están basando en el template del tp0, lo último que hacen después de mandar el paquete es terminar el programa.

Ahi si quieren que el cliente se quede un tiempo "esperando" lo que pueden hacer es agregar un `sleep()` con un valor bastante alto o poner otra llamada a `readline()` y no hacer nada en la consola del cliente.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @ahuarca! Cierro el issue por inactividad, ante cualquier consulta pueden reabrirlo o abrir uno nuevo.

@TotiGonzalez en caso de seguir con el problema te invito a abrir un nuevo issue así podemos atender las consultas de forma más organizada. Tengamos en cuenta que las razones por las que no se comporta como deberían pueden ser muchas, y siempre puede servir de ayuda usar el [debugger](https://faq.utnso.com.ar/guia-debug-eclipse) para monitorear línea por línea el estado de las variables.

Saludos
