### ISSUE TITLE
Error al intentar compilar los primeros pasos

### ISSUE THREAD

**Issue by IamJuanpax** [sisoputnfrba/foro#3387]
![image](https://github.com/sisoputnfrba/foro/assets/129467505/2b5cd216-f36f-4c03-86bf-a61ada5f9c6d)

Me aparece ese error al querer compilar el primer paso del tp0, el cual es usar el log_create. Probamos varias cosas y no sabemos que puede ser.

**Comment by RaniAgus** [comment]
¡Buenas! Me parece que están teniendo el mismo problema que en https://github.com/sisoputnfrba/foro/issues/3385. Saludos

**Comment by iago64** [comment]
@IamJuanpax Cómo va?

Te sirvió lo que comento @RaniAgus?

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, ante cualquier consulta pueden reabrirlo o abrir uno nuevo. Saludos
