### ISSUE TITLE
log_info y variables

### ISSUE THREAD

**Issue by marianoSLamaison** [sisoputnfrba/foro#3388]
Estoy resolviendo el tp0, pero tengo el visor de problems lleno con warnings que leen "format not a string literal and no format arguments [-Wformat-security]" Y no se como desacerme de ellas.

Entiendo que da la warning por que estoy usando una  variable en ves de un string normal, pero no se como escribir el valor de la variable si no. 

En resumen queria saber si hay una manera de escribir el valor de la variable sin tener la warning.

### 📝 Código relevante

Un ejemplo de codigo seria 
`log_info(logger, valor);`

**Comment by RaniAgus** [comment]
¡Buenas! Ese warning se debe a que los logs de las commons funcionan igual que `printf()`, reciben un string template y "n" parámetros para rellenar ese template. Entonces podés pasarle lo siguiente:

```c
log_info(logger, "%s", valor);
```

Se recomienda que el string template sea un literal para que así el compilador te pueda reconocer algún error si por algún motivo te llegás a confundir de chirimbolo, por ejemplo, si intento pasar un `int` en donde se espera un `char*`:

```c
log_create(logger, "%s", 42);
```

Saludos

**Comment by marianoSLamaison** [comment]
Muchas gracias, con eso ya me pude deshacer de esas warning. cierro el issue.
