### ISSUE TITLE
Error con archivo Grafica.zip.002

### ISSUE THREAD

**Issue by elin-winter** [sisoputnfrba/foro#3389]
Holaa, estoy teniendo un problema con la descarga de un archivo de la carpeta "VM Entorno Gráfico 6.1", en especifico el de "Gráfica.zip.002". 

Estoy con una Mac y me baje "The Unarchiver", con él pude descargarme sin problemas el 001, pero cuando intento el 002 me aparece este mensaje:

![image](https://github.com/sisoputnfrba/foro/assets/164521483/8efebe1e-7df6-436d-b85d-bfce07d70095)

Alguno tendrá alguna idea sobre qué hacer?

### 🖥️ Especificaciones del host
- Sistema Operativo y versión: macOS Monterey 12.7.2
- Memoria RAM: 16GB
- Procesador: 2,5 GHz Intel Core i7 de dos núcleos

**Comment by RaniAgus** [comment]
Hola, el error que comentás es muy parecido a este:  https://github.com/sisoputnfrba/foro/issues/3372, ¿probaste la solución de ese issue?

**Comment by RaniAgus** [comment]
¡Buenas! Los archivos .zip.001 y .zip.002 son en realidad partes de un mismo archivo comprimido, así que al descomprimir la .001 inevitablemente estás usando la .002

¿Lograste descargar la Grafica.vdi correctamente chequeando el md5?

Saludos

**Comment by elin-winter** [comment]
Si, pude descargar todo y lo sume a virtual box, aunque no lo chequee con md5 porque no entendí como hacerlo jaja. Igual, si decis que no hay problema con la descarga del 002 me quedo tranquila. 

Mil gracias
