### ISSUE TITLE
No me deja crear la máquina virtual

### ISSUE THREAD

**Issue by Facundo2323** [sisoputnfrba/foro#3390]
Buenas, cuando intento crear la máquina virtual (dando clic en iniciar), me dice que la máquina virtual se detuvo inesperadamente con un código de salida -1073741424. 

Código de resultado: E_FAIL (0X80004005)
Componente: MachineWrap
Interfaz: IMachine {300763af-5d6b-46e6-aa96-273eac15538a}

Tengo todo instalado y los hashes están todos correctos. No es el Hyper-V porque ya lo desactivé y me sigue tirando lo mismo.  Los anteriores issues con el mismo código de resultado E_FAIL (0X80004005) tampoco me sirvieron.

**Comment by MiltonMartorello** [comment]
Holis. 
#1600 En este thread se habló bastante del tema y hay un link a un foro donde hay muchas soluciones distintas ya que el problema puede venir de varios lados. Pegale una ojeada y porfa nos comentas si con todo lo que esta ahi aún no funcionó .
Saludos!

**Comment by Facundo2323** [comment]
Intenté deshabilitar la BIOS, e incluso instalé una version mas vieja de VirtualBox, pero me sigue tirando el mismo error.
Lo que me hace ruido es

**Comment by iago64** [comment]
Buenas! Cómo va?

Podrías pasarnos mas info de la config de la VM en VirtualBox y del error? 
Por otra parte, dentro de las características de windows, te recomiendo que deshabilites todo lo referente a Hyper-V, ya que en algunos casos falla igual.
![image](https://github.com/sisoputnfrba/foro/assets/1622109/080aab90-5393-4727-b2c5-a7cbe3063473)


Porque me llama la atención que el error que tenes es el MachineWrap que generalmente viene asociado a Hyper-V o a cuestiones de virtualización.

Saludos.-

**Comment by Facundo2323** [comment]
Reinstalé el Virtualbox y además probé habilitar la virtualización nuevamente y funcionó. Muchas gracias por la ayuda!
