### ISSUE TITLE
Duda sobre el puerto de escucha del kernel

### ISSUE THREAD

**Issue by tomipodo** [sisoputnfrba/foro#3391]
Hola! Qué tal? Nos surgió una duda leyendo el enunciado del TP. Vemos que el módulo I/O se debe conectar al kernel a través del PUERTO_KERNEL que se encuentra en el config del I/O, pero el config del kernel no tiene un puerto de escucha entre sus variables. No sabemos si debemos crear una nueva variable en el config, o como proceder. Gracias, saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

Eso lo dejamos a libre implementación de cada grupo, si quieren agregar un parámetro en el archivo de config pueden hacerlo ya que a fines prácticos es lo mismo si lo agregan en un config o lo hardcodean, lo que nos importa es que se conecten las interfaces de I/O.

Saludos.-

**Comment by tomipodo** [comment]
Buenísimo, gracias!
