### ISSUE TITLE
Tp 0 - Etapa 2

### ISSUE THREAD

**Issue by arribas7** [sisoputnfrba/foro#3394]
En el siguiente enunciado:

"Parados en el archivo cliente.c, si revisamos el [header de log de las commons](https://faq.utnso.com.ar/commons/blob/72470a6732312c085185ae08d911e9f0d7c7fc1a/src/commons/log.h#L40-L57) vamos a encontrar la función log_create(), que nos devuelve un logger listo para usar.
Ayudándonos con la descripción que aparece en el header, vamos a configurarla para que:
Loguee en el archivo "tp0.log"
Muestre los logs por pantalla (y no solo los escriba en el archivo)
Muestre solo los logs a partir del nivel "info"."

Qué archivo especificamente se necesita editar? 
so-commons-library/src/commons/log.c   
ó
tp0/client.c

Tengo dudas antes de editar el  so-commons-library/src/commons/log.c   aunque ya tomé un backup, porque parecen ser parte de las bibliotecas que se van a necesitar en el futuro.
Gracias
Saludos

**Comment by RaniAgus** [comment]
¡Buenas! Las commons son una biblioteca que les proveemos desde la cátedra y solamente deben instalar antes de iniciar. No es necesario modificarlas, su código ya funciona.

Quizás en vez de "configurarla" el término correcto para esa oración sea "utilizarla", ya que como verás los ítems que aparecen listados coinciden con los parámetros de `config_create`. Es por eso que les pedimos que lean la documentación que se encuentra en el header (el `log.h`) y no el archivo fuente (el `log.c`).

Saludos

**Comment by RaniAgus** [comment]
¡Buenas @arribas7! ¿Quedó clara la idea? Saludos

**Comment by karengrams** [comment]
¡Buenas @arribas7! 

Cerramos el issue por inactividad, de todas formas, si no quedo resuelta la duda, podes re-abrirlo. 

¡Saludos!
