### ISSUE TITLE
Problema al descargar las commons

### ISSUE THREAD

**Issue by Fernando-23** [sisoputnfrba/foro#3395]
Buenas, estoy realizando mi primer proyecto en C (Todavia no empece el TP0) y tengo problema para descargar las commons.

Cuando clono el repo no hay problema, el problema es cuando escribo "make debug" no me reconoce el termino "make".
Mi duda es si tengo que configurar algo, descargar algo ademas de lo que descargue (en la parte "Busqueda en foros" aclaro que descargue) o tengo que hacerlo dentro de la VM.

### 🔎 Búsqueda en foros
Busque en google y supuestamente tengo que descargar make. 
Lo instale de aca https://gnuwin32.sourceforge.net/packages/make.htm pero sigue sin funcionarme.
Tambien trate de agregar la carpeta /bin al path pero sigue igual sin funcionarme.

### 📝 Código relevante

PS D:\Fer\Desktop\Facultad\Sistemas Operativos\commons> cd so-commons-library
PS D:\Fer\Desktop\Facultad\Sistemas Operativos\commons\so-commons-library> make debug
make : El término 'make' no se reconoce como nombre de un cmdlet, función, archivo de script o programa ejecutable.
Compruebe si escribió correctamente el nombre o, si incluyó una ruta de acceso, compruebe que dicha ruta es correcta e
inténtelo de nuevo.
En línea: 1 Carácter: 1
+ make debug
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (make:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS D:\Fer\Desktop\Facultad\Sistemas Operativos\commons\so-commons-library>

**Comment by RaniAgus** [comment]
¡Buenas! Te recomiendo seguir la guía de primeros pasos en el orden que establecimos en la página, ya que previamente a crear tu primer proyecto en C tenés que [conseguir un entorno Linux](https://docs.utnso.com.ar/primeros-pasos/entorno-linux) sobre el cual desarrollar el TP, el cual incluye syscalls específicas de Linux, por lo que no es posible desarrollarlo en Windows.

Saludos

**Comment by Fernando-23** [comment]
Gracias!
Pense que se tenia que hacer en windows y no en la VM.
Buen finde!
