### ISSUE TITLE
Perdido en la parte de archivos de configuracion

### ISSUE THREAD

**Issue by IamJuanpax** [sisoputnfrba/foro#3396]
Buenas, estoy perdido en esta parte: 
![image](https://github.com/sisoputnfrba/foro/assets/129467505/182c8abc-98b3-4c4b-aaf9-6692644d9f5b)

No se como poner la clave, ni como la funcion config_create puede interpretar cual puede ser la clave. Me darian una mano porfa ?

**Comment by mefederico** [comment]
Hola o/
Si miras todos los headers de las configs de las commons podes ver esta [función](https://github.com/sisoputnfrba/so-commons-library/blob/d22eb0076cc863bcbb7edbdf47ef43e6d434ffc6/src/commons/config.h#L47) que te puede llegar a servir, toma un t_config, una key (clave) y te devuelve un valor como string

Ahora con esto nuevo capaz se entiende más en que nos puede ayudar el `config_create`

**Comment by RaniAgus** [comment]
¡Buenas @IamJuanpax! ¿Te sirvió el comment de Fede? Saludos

**Comment by karengrams** [comment]
¡Buenas @IamJuanpax! 

Cerramos el issue por inactividad, de todas formas, si todavía estas perdid@, podes re-abrirlo o acercarte a un sábado de soporte para poder charlar un poco más a fondo. 

¡Saludos!
