### ISSUE TITLE
Recomendaciones e imagenes que no funcionan en Docs.ssoo

### ISSUE THREAD

**Issue by VEBravo** [sisoputnfrba/foro#3398]
Hola! Estuve iniciandome en todo este mundillo bello que es ssoo y me gustaría hacer un par de aportes en los docs.
1. En la guía de debugging hay un par de imagenes que no cargan. Probé con distintos dispositivos y personas y tienen el mismo problema. 
2. En la consigna del tp0 en un principio dice que tenemos que clonar el repositorio del tp0. El problema es que al llegar a la etapa 4  dice: "Clonar el repo del TP0 (que en este caso va a ser un repo privado suyo)." Estaría bueno que se recomiende al iniciar el tp0 forkear el repo del tp para evitar después tener que mover todo lo trabajado en el repo clonado del tp0 a un repo privado y cambiar las direcciones dentro de los archivos para pushearlo y ahi recién clonarlo en la ubuntu server. 
Capaz uno aprende a leer la consigna completa antes de empezar, o bien hay una solución más fácil que la que mencioné. Pero creo que si desde un principio se dijera que no se trabaje sobre el repo del tp0 sino sobre una copia privada se evitaría luego tener problemas con esto.
3. Un detalle medio quisquilloso, estaría bueno en la guia de serialización que reemplacen los gifs por slides para poder seguir mejor los procesos de empaquetado.

Espero sumar un poquito y aprovecho el espacio para agradecer todo el material disponible.

**Comment by RaniAgus** [comment]
¡Buenas! Antes que nada gracias por todo el feedback, cualquier detalle por más quisquilloso que sea nos sirve un montón.

1. ¿Podrían detallarnos qué imágenes no cargan? Ahí intenté entrar y desde todos los dispositivos se ven bien 😅 

2. ¡Buena idea! Me la llevo como mejora.

3. No lo veo imposible ya que la página está hecha con [Vitepress](https://vitepress.dev/), el cual permite usar componentes de [Vue.js](https://vuejs.org/) para agregarle features extra, así que se podría buscar en algún lado algún slide copado que permita reproducir, pausar o desplazarse entre varias imágenes. 

Si sabés o conocés a alguien que sepa de Vue (o incluso con saber algo de front alcance) siéntanse libres de subirnos un PR a [docs](https://github.com/sisoputnfrba/docs) 😉

Inicialmente esa guía estaba escrita en un google docs, así que entiendo que no había muchas más alternativas a poner un gif en ese momento jajaj

Saludos

**Comment by VEBravo** [comment]
Las imagenes que no cargan son
- Sección introducción: la imagen que viene despues de "lo que sientas en tu corazon al ver esto:"
- Seccion empezando: la imagen que continua a "Soy un documento en iternet"
- Seccion Vista Variables: " " "pausa dramatica y ruido de pensamiento"
- Seccion programa complejo: " " "solucion en C"
- Seccion programa complejo complejo: " " "programar una posible solucion" y la imagen que viene despues de "¿qué tendría que pasar?"
Después, no conozco a nadie que sepa de Vue.js sino lo mandaba.

**Comment by iago64** [comment]
Buenas! Cómo va?

Una consulta, las imágenes que decís que no se ven son las que se ven como la siguiente imagen?

![image](https://github.com/sisoputnfrba/foro/assets/1622109/cb69749a-2743-44f9-bc68-98061cb6a045)

Porque si es así, justamente la imagen esa lo que quiere representar es que tienen que pensar uds en lo que acaban de leer, capaz que no fuimos claros con ese tema 😞 

Saludos.-

**Comment by VEBravo** [comment]
Sí, era esa la imagen, ahora que lo leo entiendo. En el afán de querer aportar cosas no leí bien, tenés razón si, era esa la imagen jajajajja

**Comment by LeandroCarbajales** [comment]
Cierro el issue para que el aporte quede documentado, ya está actualizado el punto 2 en la documentación del TP0 :D

Con respecto al punto 3, dejo el último comentario de Agus para futuros aportes a las docs:

"Si sabés o conocés a alguien que sepa de Vue (o incluso con saber algo de front alcance) siéntanse libres de subirnos un PR a [docs](https://github.com/sisoputnfrba/docs) 😉"

Gracias nuevamente!
