### ISSUE TITLE
VM Eclipse, faltan dependencias del nucleo Python

### ISSUE THREAD

**Issue by MarcoIoannisci** [sisoputnfrba/foro#3399]
Buenas, estuve haciendo los pasos que me indican en primeros pasos para poder empezar con la virtualBox pero me salto este cuadro que aunque entiendo lo que me quiere decir, no se como resolverlo y estoy preocupado de meter mano donde no deba. Queria pedir ayuda mas por discord asi me podian guiar cualquier cosa pero me mandaron directo aca.

### 🔎 Búsqueda en foros
Consulte con otros compañeros de la cursada y dicen que no les salto el mismo cuadro.

### 📦 Especificaciones de la VM
- Versión de VirtualBox: 7.0.14
- Memoria RAM asignada: aun no instalado.

### 🖥️ Especificaciones del host
- Sistema Operativo y versión: Windows 10 
- Memoria RAM: 16
- Procesador: Ryzen 5

Mando imagen para poder ver si se entiende mejor el problema.
![Sin título](https://github.com/sisoputnfrba/foro/assets/63261451/2378df71-e074-423f-b0e8-e71cff76261d)

Desde ya muchas gracias

**Comment by RaniAgus** [comment]
¡Buenas! Hice una búsqueda rápida en Google y me encontré con este video que te puede servir: [How to Fix Missing Dependencies Python Core / win32api in VirtualBox](https://www.youtube.com/watch?v=Yf9VgzFp2CY). Saludos

**Comment by NicolasKalaydjian** [comment]
Hola, a mi me saltó el mismo cartel pero le di para adelante y pude instalar la VM sin problemas, creo que decia que iba a tener que instalarlo después pero no me fue necesario (al menos por ahora)

**Comment by MarcoIoannisci** [comment]
gracias a ambos, al final no termine instalando las dependencias del nucleo de python y parece que todo esta bien, pero por las dudas si salta algun problema instalare lo de python mas adelante

**Comment by iago64** [comment]
Buenas! Si el issue esta resuelto, por favor no te olvides de cerrarlo 😄
