### ISSUE TITLE
Problema al instalar Virtualbox en ChromeOs

### ISSUE THREAD

**Issue by sofiimoguilner** [sisoputnfrba/foro#3401]
Hola estoy tratando de descargar Virtualbox en ChromeOs. trate de descargarlo desde la terminal ya que con el link  no podía. Cuando hice eso me dice que tenía fallas con los paquetes libvpx5 y python.  Con respecto al link averigüe y se supone que se descargaba con debian 11 pero cuando hice eso me aparece completamente vacío. Y no se que mas puedo hacer

**Comment by iago64** [comment]
Buenas @sofiimoguilner! Cómo va?

Antes que nada, por favor, tratá de usar un titulo un poco mas acotado a la hora de crear un issue y despues describí el problema en el cuerpo del issue.

Ahora, viendo el problema que planteas, hasta donde recuerdo no tenemos registros de alumnos que quisieran instalar VirtualBox en ChromeOS, con lo cual me falta bastante contexto respecto a que ejecutaste o que pasos seguiste como para poder darte una mano.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Para sumar, nos gustaría poder contar (para más contexto) con los comandos que ingresaste y el output que te devuelve, ya que hay varias formas de **"descargarlo desde la terminal"** y distintos tipos de **"fallas con los paquetes libvpx5 y python"**. Saludos

**Comment by sofiimoguilner** [comment]
Gracias por la rápida devolución! Les comento un poco más del contexto.

Primero traté de descargarlo a partir de este video https://www.youtube.com/watch?v=ZDLSm7JKHKI. Lo cual no me funcionó ya que cuando me metía a descargas me aparecía un archivo completamente vacío.
![Screenshot 2024-04-01 17 28 13](https://github.com/sisoputnfrba/foro/assets/165674606/49efeac0-f76c-42c1-bbbf-4dafb4720a14)

Luego traté con otros links diferentes a los del video pero me salía este error:
![Screenshot 2024-04-01 17 27 43](https://github.com/sisoputnfrba/foro/assets/165674606/e22916b4-6e00-4960-ab63-7375b741510a)

A partir de esto, empecé a buscar otros videos para poder descargarlo y encontré uno para hacerlo desde la terminal pero VirtualBox 6.  https://www.youtube.com/watch?v=YtrnmtIUB7A

Aquí empecé a tener problemas que los empecé a ver con ChatGPT porque no encontraba información y no entendía nada. Estos eran los problemas: (pero en conclusion me decia que tenia paquetes rotos y ChatGPT me decia que tenia que instalar libvpx5 python. Pero python no pude y ahi me dijo que instalara Python 3 pero se me seguia rompiendo)

sofiaribes472@penguin:~$ sudo apt install virtualbox-6.0
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 virtualbox-6.0 : Depends: libvpx5 (>= 1.6.0) but it is not installable
                  Depends: python (< 2.8) but it is not installable
                  Depends: python (>= 2.7) but it is not installable
                  Depends: python:any (>= 2.6.6-7~) but it is not installable
                  Recommends: libsdl-ttf2.0-0 but it is not going to be installed
                  Recommends: kmod but it is not going to be installed or
                              kldutils but it is not installable or
                              module-init-tools but it is not installable
                  Recommends: linux-headers-generic or
                              linux-headers-generic-pae but it is not installable or
                              linux-headers-686-pae but it is not installable or
                              linux-headers-amd64 but it is not going to be installed or
                              linux-headers-2.6-686 but it is not installable or
                              linux-headers-2.6-amd64 but it is not installable or
                              linux-headers but it is not installable
                  Recommends: linux-image but it is not installable
                  Recommends: make or
                              build-essential but it is not going to be installed or
                              dpkg-dev but it is not going to be installed
                  Recommends: pdf-viewer
E: Unable to correct problems, you have held broken packages.
sofiaribes472@penguin:~$ sudo apt update
Hit:1 http://download.virtualbox.org/virtualbox/debian bionic InRelease
Hit:3 https://deb.debian.org/debian bookworm InRelease                             
Hit:4 https://deb.debian.org/debian bookworm-updates InRelease                     
Hit:5 https://mirror.mwt.me/shiftkey-desktop/deb any InRelease                     
Hit:6 https://deb.debian.org/debian-security bookworm-security InRelease           
Hit:2 https://packages.microsoft.com/repos/code stable InRelease                   
Ign:7 https://storage.googleapis.com/cros-packages/122 bookworm InRelease
Hit:8 https://storage.googleapis.com/cros-packages/122 bookworm Release
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
W: http://download.virtualbox.org/virtualbox/debian/dists/bionic/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
sofiaribes472@penguin:~$ sudo apt install libvpx5 python
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package python is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python-is-python3 2to3

Package libvpx5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libvpx5' has no installation candidate
E: Package 'python' has no installation candidate
sofiaribes472@penguin:~$ sudo apt --fix-broken install
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  cpp-10 gcc-10 gcc-11-base glib-networking glib-networking-common
  glib-networking-services gnome-desktop3-data libappstream-glib8 libasan6
  libatk1.0-data libbpf0 libcbor0 libdns-export1110 libflac8 libfuse2
  libgcc-10-dev libgdk-pixbuf-xlib-2.0-0 libgdk-pixbuf2.0-0 libicu67
  libisc-export1105 libldap-2.4-2 libllvm11 liblmdb0 libmpdec3 libncurses6
  libperl5.32 libprocps8 libproxy1v5 libpython3.9 libpython3.9-minimal
  libpython3.9-stdlib librest-0.7-0 libsoup-gnome2.4-1 libsoup2.4-1
  libsoup2.4-common libtiff5 libtsan0 libwebp6 libwxbase3.0-0v5
  libwxgtk3.0-gtk3-0v5 libxkbregistry0 perl-modules-5.32 python3.9
  python3.9-minimal
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
sofiaribes472@penguin:~$ sudo apt install virtualbox-6.0
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 virtualbox-6.0 : Depends: libvpx5 (>= 1.6.0) but it is not installable
                  Depends: python (< 2.8) but it is not installable
                  Depends: python (>= 2.7) but it is not installable
                  Depends: python:any (>= 2.6.6-7~) but it is not installable
                  Recommends: libsdl-ttf2.0-0 but it is not going to be installed
                  Recommends: kmod but it is not going to be installed or
                              kldutils but it is not installable or
                              module-init-tools but it is not installable
                  Recommends: linux-headers-generic or
                              linux-headers-generic-pae but it is not installable or
                              linux-headers-686-pae but it is not installable or
                              linux-headers-amd64 but it is not going to be installed or
                              linux-headers-2.6-686 but it is not installable or
                              linux-headers-2.6-amd64 but it is not installable or
                              linux-headers but it is not installable
                  Recommends: linux-image but it is not installable
                  Recommends: make or
                              build-essential but it is not going to be installed or
                              dpkg-dev but it is not going to be installed
                  Recommends: pdf-viewer
E: Unable to correct problems, you have held broken packages.
sofiaribes472@penguin:~$ ^C
sofiaribes472@penguin:~$ sudo apt update
Hit:2 https://deb.debian.org/debian bookworm InRelease                             
Hit:3 https://deb.debian.org/debian bookworm-updates InRelease                     
Hit:4 http://download.virtualbox.org/virtualbox/debian bionic InRelease            
Hit:5 https://deb.debian.org/debian-security bookworm-security InRelease           
Hit:1 https://packages.microsoft.com/repos/code stable InRelease                   
Hit:6 https://mirror.mwt.me/shiftkey-desktop/deb any InRelease      
Ign:7 https://storage.googleapis.com/cros-packages/122 bookworm InRelease
Hit:8 https://storage.googleapis.com/cros-packages/122 bookworm Release
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
W: http://download.virtualbox.org/virtualbox/debian/dists/bionic/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
sofiaribes472@penguin:~$ sudo apt install virtualbox-6.0
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 virtualbox-6.0 : Depends: libvpx5 (>= 1.6.0) but it is not installable
                  Depends: python (< 2.8) but it is not installable
                  Depends: python (>= 2.7) but it is not installable
                  Depends: python:any (>= 2.6.6-7~) but it is not installable
                  Recommends: libsdl-ttf2.0-0 but it is not going to be installed
                  Recommends: kmod but it is not going to be installed or
                              kldutils but it is not installable or
                              module-init-tools but it is not installable
                  Recommends: linux-headers-generic or
                              linux-headers-generic-pae but it is not installable or
                              linux-headers-686-pae but it is not installable or
                              linux-headers-amd64 but it is not going to be installed or
                              linux-headers-2.6-686 but it is not installable or
                              linux-headers-2.6-amd64 but it is not installable or
                              linux-headers but it is not installable
                  Recommends: linux-image but it is not installable
                  Recommends: make or
                              build-essential but it is not going to be installed or
                              dpkg-dev but it is not going to be installed
                  Recommends: pdf-viewer
E: Unable to correct problems, you have held broken packages.
sofiaribes472@penguin:~$ sudo apt install python
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package python is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python-is-python3 2to3

E: Package 'python' has no installation candidate
sofiaribes472@penguin:~$ sudo apt install python-is-python3
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  cpp-10 gcc-10 gcc-11-base glib-networking glib-networking-common
  glib-networking-services gnome-desktop3-data libappstream-glib8 libasan6
  libatk1.0-data libbpf0 libcbor0 libdns-export1110 libflac8 libfuse2
  libgcc-10-dev libgdk-pixbuf-xlib-2.0-0 libgdk-pixbuf2.0-0 libicu67
  libisc-export1105 libldap-2.4-2 libllvm11 liblmdb0 libmpdec3 libncurses6
  libperl5.32 libprocps8 libproxy1v5 libpython3.9 libpython3.9-minimal
  libpython3.9-stdlib librest-0.7-0 libsoup-gnome2.4-1 libsoup2.4-1
  libsoup2.4-common libtiff5 libtsan0 libwebp6 libwxbase3.0-0v5
  libwxgtk3.0-gtk3-0v5 libxkbregistry0 perl-modules-5.32 python3.9
  python3.9-minimal
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  python-is-python3
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 3,000 B of archives.
After this operation, 15.4 kB of additional disk space will be used.
Get:1 https://deb.debian.org/debian bookworm/main amd64 python-is-python3 all 3.11.1-3 [3,000 B]
Fetched 3,000 B in 0s (9,338 B/s)             
Selecting previously unselected package python-is-python3.
(Reading database ... 49019 files and directories currently installed.)
Preparing to unpack .../python-is-python3_3.11.1-3_all.deb ...
Unpacking python-is-python3 (3.11.1-3) ...
Setting up python-is-python3 (3.11.1-3) ...
Processing triggers for man-db (2.11.2-2) ...
sofiaribes472@penguin:~$ sudo apt install virtualbox-6.0
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 virtualbox-6.0 : Depends: libvpx5 (>= 1.6.0) but it is not installable
                  Depends: python (< 2.8) but it is not installable
                  Depends: python (>= 2.7) but it is not installable
                  Depends: python:any (>= 2.6.6-7~) but it is not installable
                  Recommends: libsdl-ttf2.0-0 but it is not going to be installed
                  Recommends: kmod but it is not going to be installed or
                              kldutils but it is not installable or
                              module-init-tools but it is not installable
                  Recommends: linux-headers-generic or
                              linux-headers-generic-pae but it is not installable or
                              linux-headers-686-pae but it is not installable or
                              linux-headers-amd64 but it is not going to be installed or
                              linux-headers-2.6-686 but it is not installable or
                              linux-headers-2.6-amd64 but it is not installable or
                              linux-headers but it is not installable
                  Recommends: linux-image but it is not installable
                  Recommends: make or
                              build-essential but it is not going to be installed or
                              dpkg-dev but it is not going to be installed
                  Recommends: pdf-viewer
E: Unable to correct problems, you have held broken packages.

**Comment by RaniAgus** [comment]
Entiendo... Leyendo la página de VirtualBox en la sección de [Linux Downloads](https://www.virtualbox.org/wiki/Linux_Downloads) dice que para poder instalarlo directamente desde la consola hay que seguir un par de pasos previos para agregar un repositorio distinto a los que vienen por defecto. Esto sería editar el archivo `/etc/apt/sources.list` y luego registrar una clave con `gpg`.

Igual creo que lo más sencillo va a ser descargar el archivo `.deb` correcto para tu distro e instalarlo directamente con `apt`. Para esto, chequeemos la versión de Debian con este comando:

```
cat /etc/debian_version
```

Si en lugar de aparecer directamente el número de versión te aparece un personaje de Toy Story [^1], la versión asociada a cada uno es:

- `bookworm` -> Debian 12
- `bullseye` -> Debian 11
- `buster` -> Debian 10

Descarguémoslo y, en vez de instalarlo con una interfaz gráfica, abramos una consola en la carpeta donde está descargado y usemos `apt` a ver qué nos devuelve:

```
sudo apt install ./<NOMBRE_DEL_ARCHIVO>.deb
```

No te preocupes por el contenido de los archivos `.deb` porque no son archivos de texto, así que no lo vas a poder abrir con un editor.

[^1]: https://www.debian.org/doc/manuals/debian-faq/ftparchives

**Comment by sofiimoguilner** [comment]
Ahi hice lo que me dijiste, me devolvia 12.5, por ende descargue Debian 12. Pero ahora me salta como que no es compatible con El commando apt install, segun lo que lei puede der que el archivo este roto o que no sea valido

**Comment by RaniAgus** [comment]
@sofiimoguilner , de nuevo, ¿podrías mostrarnos el comando que ejecutaste y lo que te devuelve? Desde nuestro lado es muy difícil buscar información si lo único que sabemos es que "salta como que no es compatible".

Saludos

**Comment by sofiimoguilner** [comment]
okok, disculpame ahi va 

sudo apt install ./virtualBox.deb
Reading package lists... Done
E: Unsupported file ./virtualBox.deb given on commandline

**Comment by sofiimoguilner** [comment]
Queria avisar  que ahi puede, no se que paso pero ya se me descargo. 

Muchisimas gracias por tomarse el tiempo de ayudarme.

Saludos!

**Comment by RaniAgus** [comment]
¡Buenísimo! Siempre que no queden más dudas, podés sentirte libre de cerrar el issue. En caso de que surja alguna otra podés abrir uno nuevo. Saludos
