### ISSUE TITLE
Necesito ayuda para configurar el server de la VM

### ISSUE THREAD

**Issue by andresramos92** [sisoputnfrba/foro#3402]
Hola buenas noches como estan?
Les hago una consulta, no pude hacer la instalacion de VM server ya que al momento de la configuracion no sabia cual es la opcion para la version, ya que en la lista desplegable no dice por ningun lado UBUNTU SERVER de 64bit.
Quisiera saber que version debo escoger.

**Comment by RaniAgus** [comment]
¡Buenas! Es la misma que para la gráfica: **Ubuntu (64-bit)**. Saludos

**Comment by RaniAgus** [comment]
¡Buenas @andresramos92! ¿Pudiste instalar la VM server? Saludos

**Comment by andresramos92** [comment]
Buenas! Sii lo pude instalar. Te consulto, en este caso, cuando ya está instalado el server, se ve directamente como si tuviese un terminal abierto? Te consulto ya que no me quedo un escritorio como en el caso de la gráfica Ubuntu.

**Comment by RaniAgus** [comment]
Es correcto.

![Screenshot_20240403_202949_Chrome.png](https://github.com/sisoputnfrba/foro/assets/39303639/77904513-bf13-4023-af57-0f5e219bedb4)

**Comment by andresramos92** [comment]
Entonces si, lo instale bien. Muchas gracias.

**Comment by karengrams** [comment]
¡Buenas @andresramos92! 

Cerramos el issue considerando que la duda esta resuelta. Cualquier cosa, si vuelve a surgir otra duda respecto a lo mismo, no dudes en re-abrir el issue.

¡Saludos!
