### ISSUE TITLE
No puedo compilar mi primer proyecto en C

### ISSUE THREAD

**Issue by mamusante** [sisoputnfrba/foro#3404]
Estoy intentando compilar el proyecto en C pero no me reconoce las funciones, no se si tiene algo que ver con las commons, las instale siguiendo el paso a paso de clonar, hacer make debug y make install, no se si me falto un paso para terminar de linkearlas o como es, ya que vi que tenia que hacer un -lcommons pero no entendi como se hacia ese paso. 
### 📔 Citas del enunciado/videos

Copia del error que me aparece: 
```
Executing task: make all 

gcc -g -Wall -DDEBUG -fdiagnostics-color=always -o "bin/ejemplo" obj/main.o -I./src  -lcommons -lpthread -lreadline -lm
/usr/bin/ld: obj/main.o: in function `main':
/home/utnso/ejemplo/src/main.c:6: undefined reference to `txt_write_in_stdout'
collect2: error: ld returned 1 exit status
make: *** [makefile:39: bin/ejemplo] Error 1

 *  The terminal process "/usr/bin/bash '-c', 'make all'" terminated with exit code: 2. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

**Comment by RaniAgus** [comment]
¡Buenas! Me parece que hay algo raro en la instalación de las commons porque no te está encontrando la definición de la función.

Probemos algo, ejecutá estos dos comandos y pasanos el output:
```
ls -la /usr/include/commons
```

```
ls -la /usr/lib/libcommons.so 
```

Saludos

**Comment by RaniAgus** [comment]
PD: En cuanto al `-lcommons`, es justamente uno de los parámetros que el makefile le está pasando a `gcc`, así que todo bien por ese lado:

```
gcc -g -Wall -DDEBUG -fdiagnostics-color=always -o "bin/ejemplo" obj/main.o -I./src -lcommons -lpthread -lreadline -lm
```

**Comment by mamusante** [comment]
Ahi te paso lo que me puso:

utnso@utnso:/$ ls -la /usr/include/commons
total 12
drwxr-xr-x  3 root root 4096 Mar 30 14:50 .
drwxr-xr-x 49 root root 4096 Mar 30 14:50 ..
-rw-r--r--  1 root root    0 Mar 30 14:50 bitarray.h
drwxr-xr-x  2 root root 4096 Mar 30 14:50 collections
-rw-r--r--  1 root root    0 Mar 30 14:50 config.h
-rw-r--r--  1 root root    0 Mar 30 14:50 error.h
-rw-r--r--  1 root root    0 Mar 30 14:50 log.h
-rw-r--r--  1 root root    0 Mar 30 14:50 memory.h
-rw-r--r--  1 root root    0 Mar 30 14:50 process.h
-rw-r--r--  1 root root    0 Mar 30 14:50 string.h
-rw-r--r--  1 root root    0 Mar 30 14:50 temporal.h
-rw-r--r--  1 root root    0 Mar 30 14:50 txt.h
utnso@utnso:/$ ls -la /usr/lib/libcommons.so 
-rwxr-xr-x 1 root root 0 Mar 30 14:50 /usr/lib/libcommons.so

**Comment by iago64** [comment]
Buenas! Cómo va?

Consulta, te puedo pedir si nos pasas como tenes los imports en el archivo `main.c` o si tenes un `main.h` tambien nos pasas eso? Porque me suena que te esta faltando un include.

Saludos.-

**Comment by RaniAgus** [comment]
Sip, hay algo raro... El comando que te pasé, [`ls` con el flag `-la`](https://docs.utnso.com.ar/guias/consola/bash#moverse-entre-carpetas), te devuelve una tablita con, entre otras cosas, el tamaño del archivo en la 5ta columna. En tu caso te está devolviendo todo `0` en vez de algo como:

```
utnso@utnso:/$ ls -la /usr/include/commons
total 72
drwxr-xr-x  3 root root  4096 Oct 29 16:55 .
drwxr-xr-x 92 root root 20480 Mar 14 19:06 ..
-rw-r--r--  1 root root  3539 Oct 29 16:55 bitarray.h
drwxr-xr-x  2 root root  4096 Oct 29 16:55 collections
-rw-r--r--  1 root root  3256 Oct 29 16:55 config.h
-rw-r--r--  1 root root   934 Oct 29 16:55 error.h
-rw-r--r--  1 root root  3706 Oct 29 16:55 log.h
-rw-r--r--  1 root root  1384 Oct 29 16:55 memory.h
-rw-r--r--  1 root root  1016 Oct 29 16:55 process.h
-rw-r--r--  1 root root  8345 Oct 29 16:55 string.h
-rw-r--r--  1 root root  2839 Oct 29 16:55 temporal.h
-rw-r--r--  1 root root  1286 Oct 29 16:55 txt.h
utnso@utnso:/$ ls -la /usr/lib/libcommons.so 
-rwxr-xr-x 1 root root 111232 Oct 29 16:55 /usr/lib/libcommons.so
```

Yo diría de volver a instalar las commons y probar de nuevo. Si sigue igual pasanos el output que te devuelve al instalarlas y lo intentamos entender un poquito mejor.

**Comment by mamusante** [comment]
Esto es todo lo que tengo en el main, no toque nada desde q lo clonee 

#include <stdio.h>
#include <stdlib.h>
#include <commons/txt.h>


int main(int argc, char* argv[]) {
    txt_write_in_stdout("Hola, Operativos!!\n");
    return 0;
}

**Comment by mamusante** [comment]
En cuanto a volver a instalar las commons tendria que hacer un make uninstall ? O como es

**Comment by iago64** [comment]
Buenas!

Excelente, veo que tenes el include correcto, en ese caso, reinstala las commons por lo que comenta @RaniAgus 

Saludos.-

**Comment by RaniAgus** [comment]
@mamusante Yo diría de hacer primero:

```
make uninstall
make clean
```
Eso te va a borrar la instalación[^1] y lo que tengas compilado[^2]. Luego podés instalarlas con `debug` e `install` como siempre.


[^1]: https://github.com/sisoputnfrba/so-commons-library/blob/master/src/makefile#L41-L42

[^2]: https://github.com/sisoputnfrba/so-commons-library/blob/master/src/makefile#L34

**Comment by mamusante** [comment]
Ahi reinstale y me funciona todo, en el TP 0 tenia el mismo problema con las funciones y tambien se resolvio. Gracias, cierro el Issue. 
Saludos :)
