### ISSUE TITLE
Free readline

### ISSUE THREAD

**Issue by IgnacioPringles** [sisoputnfrba/foro#3405]
Buenas, es más que nada una duda conceptual sobre como se está manejando el uso de la memoria al utilizar múltiples veces `readline`.

Esta es mi implementación de `leer_consola`
![image](https://github.com/sisoputnfrba/foro/assets/62760419/990f5d0a-e451-482c-af02-1aa51b0b92f6)

Si no estoy entendiendo mal, cada llamado a `readline` a su vez llama a `malloc`, lo que devuelve una nueva posición de memoria a donde `leido` termina apuntando. Si no estuviese el `free` dentro del bucle estaríamos con un problema de memory leak?

Gracias.

**Comment by mefederico** [comment]
Hola o/
Exacto, cada vez que llamas a `readline`, se asigna memoria dinámica mediante `malloc`, y el puntero resultante se guarda en la variable `leido`. Dado que esto ocurre dentro de un bucle `while`, es necesario liberar la memoria asignada previamente antes de realizar una nueva asignación. De lo contrario, se perderá la referencia anterior, lo que provoca un memory leak

Y finalmente fuera del loop lo tienes que hacer de nuevo porque al romper la condición no se ejecuta el `free` de adentro

**Comment by RaniAgus** [comment]
¡Buenas! Para sumar, esto se puede encontrar visitando la [docu de readline](https://man7.org/linux/man-pages/man3/readline.3.html) o escribiendo en la consola:

```
man readline
```

Vas a ver que en la descripción dice:

> The line returned is allocated with [malloc(3)](https://www.man7.org/linux/man-pages/man3/malloc.3.html); the caller must free it when finished.

Saludos
