### ISSUE TITLE
Procedencia de scripts

### ISSUE THREAD

**Issue by fmigliavacca** [sisoputnfrba/foro#3406]
Hola! Tenía una duda respecto al enunciado del Tp. Quería saber de dónde obtenemos el script con los procesos o si debemos crearlo nosotros. Si es que nos lo dan ustedes, también me gustaría saber en qué formato vendría para saber como armar las estruturas para escribirlos en memoria. Saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

Si por scripts de procesos te referis a los archivos de pseudo código que tienen que parsear y mandarselos instrucción por instrucción a la CPU, para la entrega final les vamos a dar un set de pruebas definido, para el desarrollo pueden creárselos uds ya que tienen los ejemplos en el enunciado.
Eventualmente si se crean un programa de prueba y quieren validarlo nos pueden preguntar.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas @fmigliavacca !
Te sirvió la respuesta de @iago64 ? Quedó resuelta la duda?

**Comment by iago64** [comment]
Buenas!

Cerramos el issue por inactividad.

Saludos.-
