### ISSUE TITLE
Direcciones fisicas

### ISSUE THREAD

**Issue by fmigliavacca** [sisoputnfrba/foro#3407]
Hola! Tengo una duda sobre el enunciado. Las direcciones físicas pueden utilizar el formato que yo quiera? O debo utilizar alguno en específico como aclararon con la traducción de las direcciones lógicas a físicas?

**Comment by iago64** [comment]
Buenas! Cómo va?

En principio uds cuando lleguen a la parte teórica de memoria donde ven las traducciones de direcciones lógicas a físicas, van a ver que se usan N bits para el número de página y M bits para el desplazamiento, aca como trabajamos con números decimales, les dejamos la libertad de que se armen las estructuras como más cómodas les resulten a la hora de implementar, teniendo en cuenta la aclaración de las cuentas que están en la sección de MMU de la CPU en el enunciado, ya que en base a eso nosotros vamos a hacer las pruebas.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas @fmigliavacca !
Te sirvió la respuesta de @iago64 ? Quedó resuelta la duda?

**Comment by iago64** [comment]
Buenas!

Cerramos el issue por inactividad.

Saludos.-
