### ISSUE TITLE
Bit array / duda

### ISSUE THREAD

**Issue by fmigliavacca** [sisoputnfrba/foro#3408]
Hola, tengo una consulta. Cuando usamos la librería de los bitarrays, al usar la funcion:
	void 		 bitarray_destroy(t_bitarray*);
La memoria reservada para ese bit array se libera? O debo hacer un free al puntero con el que reserve esa memoria?

**Comment by iago64** [comment]
Buenas!

Algo super divertido de las commons es que no solo tienen los headers, si no que ademas en el [repo](https://github.com/sisoputnfrba/so-commons-library) tienen los .c con la implementación y pueden despejar las dudas.

En el caso de la funcion `void bitarray_destroy(t_bitarray*);` el código es tan simple como el siguiente:

```c
void bitarray_destroy(t_bitarray *self) {
	free(self);
}
```

Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas @fmigliavacca !
Te sirvió la respuesta de @iago64 ? Quedó resuelta la duda?

**Comment by iago64** [comment]
Buenas!

Cerramos el issue por inactividad.

Saludos.-
