### ISSUE TITLE
Memoria virtual

### ISSUE THREAD

**Issue by fmigliavacca** [sisoputnfrba/foro#3409]
Hola! Una consulta, no me queda claro si el modulo memoria debe incluir memoria virtual o no. Supongo que como tiene MMU en CPU probablemente la tenga pero pregunto para confirmar nada mas :)

**Comment by iago64** [comment]
Buenas! Cómo va?

Respuesta corta: No, no hay memoria virtual en este TP.

Explicación:
No tiene nada que ver que la CPU tenga una MMU con tener o no memoria virtual. 
Deberían haberlo en visto en arquitectura que el trabajo de la MMU es el de traducir direcciones lógicas a direcciones físicas y esto no tiene nada que ver con tener segmentación, paginación o el hecho de tener o no memoria virtual.

En este TP no tienen memoria virtual, ya que la complejidad de la memoria radica en que el contenido puede abarcar más de 1 página, o dicho de otra forma, podemos darles una dirección lógica de inicio en la página 0 de un proceso, pero el contenido a guardar termina en la página 1 o 2 del mismo proceso.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas @fmigliavacca !
Te sirvió la respuesta de @iago64 ? Quedó resuelta la duda?
