### ISSUE TITLE
TP0 - Etapa 3 - Enviar mensaje al servidor con el cliente 

### ISSUE THREAD

**Issue by GusDPA** [sisoputnfrba/foro#3410]
Estoy tratando de enviar un MENSAJE con la función "enviar_mensaje()" al servidor. El server lo levanto desde otra terminal y funciona, desde la terminal de visual studio y también levanta, pero tal parece que el mensaje no se envía, en la función "recibir_mensaje()" que entre, otras cosas, logguea el mensaje en el archivo server.log, pero no lo hace.

En cliente.c tenemos: 
```c
config = iniciar_config();
ip = config_get_string_value(config,"IP");
puerto = config_get_string_value(config, "PUERTO");
clave = config_get_string_value(config, "CLAVE");

log_info(logger, "Leí la ip: %s y puerto: %s\n",ip, puerto);

conexion = crear_conexion(ip, puerto);
enviar_mensaje(clave,conexion);
```
La función enviar_mensaje() está definida como:
```c
void enviar_mensaje(char* mensaje, int socket_cliente){
	t_paquete* paquete = malloc(sizeof(t_paquete));

	paquete->codigo_operacion = MENSAJE;
	paquete->buffer = malloc(sizeof(t_buffer));
	paquete->buffer->size = strlen(mensaje) + 1;
	paquete->buffer->stream = malloc(paquete->buffer->size);
	memcpy(paquete->buffer->stream, mensaje, paquete->buffer->size);

	int bytes = paquete->buffer->size + 2*sizeof(int);

	void* a_enviar = serializar_paquete(paquete, bytes);

	send(socket_cliente, a_enviar, bytes, 0);

	free(a_enviar);
	eliminar_paquete(paquete);
}
```
Y la función serializar_paquete():
```c
void* serializar_paquete(t_paquete* paquete, int bytes)
{
	void * magic = malloc(bytes);
	int desplazamiento = 0;

	memcpy(magic + desplazamiento, &(paquete->codigo_operacion), sizeof(int));
	desplazamiento+= sizeof(int);
	memcpy(magic + desplazamiento, &(paquete->buffer->size), sizeof(int));
	desplazamiento+= sizeof(int);
	memcpy(magic + desplazamiento, paquete->buffer->stream, paquete->buffer->size);
	desplazamiento+= paquete->buffer->size;

	return magic;
}

Del lado del server.c tenemos:

int main(void) {
	logger = log_create("server.log", "Servidor", 1, LOG_LEVEL_DEBUG);
	int server_fd = iniciar_servidor();
	log_info(logger, "Servidor listo para recibir al cliente");
	int cliente_fd = esperar_cliente(server_fd);
	t_list* lista;
	while (1) {
		int cod_op = recibir_operacion(cliente_fd);
		switch (cod_op) {
		case MENSAJE:
			printf(recibir_mensaje(cliente_fd));
			break;
		case PAQUETE:
			lista = recibir_paquete(cliente_fd);
			log_info(logger, "Me llegaron los siguientes valores:\n");
			list_iterate(lista, (void*) iterator);
			break;
		case -1:
			log_error(logger, "el cliente se desconecto. Terminando servidor");
			return EXIT_FAILURE;
		default:
			log_warning(logger,"Operacion desconocida. No quieras meter la pata");
			break;
		}
	}
	return EXIT_SUCCESS;
}
```
En recibir_mensaje(): 
```c
void recibir_mensaje(int socket_cliente){
	int size;
	char* buffer = recibir_buffer(&size, socket_cliente);
	log_info(logger, "Me llego el mensaje %s", buffer);
	free(buffer);
}
```
No tenemos implementado la función "recibir_paquete()" porque si aún no podemos hacer recibir un simple mensaje, menos un paquete.

Esperamos respuesta, Muchas gracias!!

**Comment by RaniAgus** [comment]
¡Buenas! Para la próxima, por favor, tengan en cuenta que si escriben un texto entre `<!--` y `-->` no vamos a ver nada porque es un **comentario**:

![image](https://github.com/sisoputnfrba/foro/assets/39303639/9810d831-e8d5-4d82-bbca-bf828e13bf45)

![image](https://github.com/sisoputnfrba/foro/assets/39303639/1ec0b77c-8189-45d5-b841-58d34907094c)

También, en markdown podés darle formato a un bloque de código (de más de una línea) usando tres comillas invertidas arriba y abajo (si le agregás una "c"  lo interpreta como código C y lo colorea), así:

<img src="https://user-images.githubusercontent.com/39303639/125994157-e624b220-1b6c-46a7-a64b-dac602249a37.png" height="75">

```c
printf("¡Hola mundo!\n");
```

Dicho esto, ¿probaste de usar el debugger para monitorear que todas las variables contengan lo que esperabas? Al iniciar el servidor y conectarse desde el cliente, ¿manejaron los casos de error como sugerimos en la guía de sockets?

![image](https://github.com/sisoputnfrba/foro/assets/39303639/6e488220-851a-404a-b485-a7d225bd6903)

Dejo acá a mano los links:

- [errno(3) — Linux manual page](https://man7.org/linux/man-pages/man3/errno.3.html)
- [strerror(3) — Linux manual page](https://man7.org/linux/man-pages/man3/strerror.3.html)
- [gai_strerror(3p) — Linux manual page](https://man7.org/linux/man-pages/man3/gai_strerror.3p.html)

Saludos
