### ISSUE TITLE
TP0 - etapa 2 - duda con uso config_get_string_value()

### ISSUE THREAD

**Issue by KirkSH** [sisoputnfrba/foro#3411]
Hola. Tengo dudas sobre como maneja/asigna la memoria la función config_get_string_value() de la commons.
Estoy en esta parte del enunciado del tp0:

"Para ello vamos a usar las config de las commons. Siguiendo su header, creemos una config que levante el archivo "cliente.config" y obtengamos el valor de la key CLAVE en formato string."

La parte de levantar el "cliente.config" la entiendo perfecto.
La siguiente parte (obtener los valores), la resolví así:

![Captura](https://github.com/sisoputnfrba/foro/assets/85580665/3bcd1eab-04fd-45d0-a726-479bb8797317)

Al correr el programe, funciona, los punteros (ip, puerto, valor) parecen apuntar a los valores levantados del archivo.
Ahora bien, creo que algo está mal. Porque esos punteros quedan apuntando a una memoria que no está reservada (por lo tanto puede ser corrompida por otra asignacion de otra varable).
Esto lo verifiqué queriendo hacer un free() de los punteros, que me dió error, pues me decía que config_get_string_value() ya se encargaba de liberar antes a dicha memoria.
Todo esto me da indicios de que mi solución no es correcta, pero no sé como solucionarlo.

**Comment by iago64** [comment]
Buenas! Cómo va?

Buenisimo que pudiste levantar los valores del archivo, ahora lo interesante de las commons, es que no tenes que adivinar como funcionan, si no que por el contrario, el código esta subido en el [repo de las commons](https://github.com/sisoputnfrba/so-commons-library/tree/master), donde esta el `config.c` que es el archivo que tiene la implementación de esas funciones.

El `free()` que te dio error puede ser por varios temas, pero si no nos pones el error, se nos complica decirte por que fue que te dio error.

Respecto a la posibilidad de que se corrompa la memoria, odio ser yo quien te arruine el momento, pero en C cualquier asignación de memoria mal hecha, siempre y cuando sea memoria de tu proceso la puede pisar, por eso que siempre hablamos tanto de que le den mucha bola a lo que dice [Valgrind](https://docs.utnso.com.ar/guias/herramientas/valgrind), ya que esa herramienta les va a tirar la posta de si estan pisando o no memoria.

Saludos.-

**Comment by KirkSH** [comment]
Gracias por responder. Pero no entendí muy bien.
Pregunto. Así como lo hice, con una simple asignación (al puntero recien creado, le asigné lo retornado de la función get_string_value() )
¿Estoy reservando memoria?

**Comment by iago64** [comment]
Buenas! Cómo va?

Respuesta corta: Si, reservaste memoria

Respuesta Larga:
Lo que en realidad pasa es que al momento de hacer el `config_create()` estas generando un diccionario de valores, que casualmente son los valores que tenes en el archivo de config.
Entonces despues las funciones de `get_config_` lo que hacen es devolverte un puntero a ese registro en el diccionario.
Para liberar la memoria del config, no tenes que hacerle un free a lo que te devuelve un `get_config_` si no que tenes que usar la función `config_destroy()`.

Saludos.-

**Comment by KirkSH** [comment]
Ahora entendí perfecto. Muchísimas gracias. 😁

**Comment by KirkSH** [comment]
Ahora entendí perfecto. Muchísimas gracias. 😁
