### ISSUE TITLE
Leer de consola

### ISSUE THREAD

**Issue by mSpadoni** [sisoputnfrba/foro#3412]
tengo una duda sobre la parte leer consola y strings de la etapa 2, cuando dice que se debe de terminar el programa al ingresarse un string vacío, quiere decir que debemos de terminar todo el programa con exit(1) o que debemos de salir de la función leer_consola() y volver a la función principal??

**Comment by LeandroCarbajales** [comment]
Buenas!
Con terminar el programa, efectivamente, se refiere a finalizar el mismo con exit().

Saludos!
       Lean

**Comment by mSpadoni** [comment]
gracias

**Comment by mSpadoni** [comment]
sabes si en la parte de paquete al agregar una linia, hay que usar también redline? 
![cp](https://github.com/sisoputnfrba/foro/assets/164950683/838a4a1d-400d-478c-a062-b7915bfd4ce7)

**Comment by iago64** [comment]
Buenas! Cómo va?

Primero que nada, por favor, no subas una foto del monitor y/o captura de pantalla, ya que el buscador de Github no es tan copado como para saber que hay en la imagen, si tenes una duda del código, por favor copia y pega el código.

Dicho lo anterior, `readline()` lo que te permite es leer desde el teclado, ahora al agregar a paquete, vos ya tenes en la variable `leido` lo que `readline()`, leyó del teclado, entonces ahi solamente tenes que agregar ese string al paquete de datos a enviar.

Saludos.-

**Comment by mSpadoni** [comment]
a gracias y perdón

**Comment by iago64** [comment]
@mSpadoni La duda quedo resuelta? Podemos cerrar el issue?

Saludos.-
