### ISSUE TITLE
Agregar al Paquete

### ISSUE THREAD

**Issue by mSpadoni** [sisoputnfrba/foro#3413]
Hola, alguno sabe si en la función de paquete al agregar una linia, hay que usar también redline?
![cp](https://github.com/sisoputnfrba/foro/assets/164950683/309ecfcd-adb7-4325-9b51-fbc61817944a)

Algo así??

**Comment by iago64** [comment]
Hola.

Esto es lo mismo que preguntaste en el issue #3412, seguimos la duda por ese issue.

Saludos.-
