### ISSUE TITLE
Problemas para correr el código y errores en las utils.c

### ISSUE THREAD

**Issue by mSpadoni** [sisoputnfrba/foro#3414]
Hola, a alguno mas le paso algo así al depurar y correr el codigo?? 
![cpp](https://github.com/sisoputnfrba/foro/assets/164950683/ce24998d-246e-4d3e-a375-dc05bb0e23c9)

y a alguien mas le aparece este error??

![cppp](https://github.com/sisoputnfrba/foro/assets/164950683/27b87c39-4ac6-4481-8255-81a4bbd3b41c)

**Comment by iago64** [comment]
Buenas! Cómo va?

Por favor copia y pega los textos del error porque el buscador de GitHub no puede indexar el contenido de las fotos del monitor / capturas de pantalla.

Por las dudas te pregunto, como abriste el workspace en VSCode? Porque me suena a que simplemente abriste la carpeta de una en lugar de seguir lo que dice la guía de [File > Open Workspace from File](https://docs.utnso.com.ar/primeros-pasos/tp0)

Saludos.-

**Comment by mSpadoni** [comment]
gracias

**Comment by mSpadoni** [comment]
.
