### ISSUE TITLE
Leer_Consola

### ISSUE THREAD

**Issue by mSpadoni** [sisoputnfrba/foro#3415]
Hola, alguno sabe si esto esta bien?? es de la etapa 2 en leer consola y strings

```c
void leer_consola(t_log* logger){
	 char *leido;

    while (1) {
        leido = readline(">");

		if (strcmp(leido,"")==0) {
                   exit(1);
                }
               if (!leido) {
                   break;
                }

        log_info(logger,"%s\n",leido);
        free(leido);
    }
}
```

**Comment by LeandroCarbajales** [comment]
Buenas!
La mejor forma de confirmarlo es ejecutarlo y verificar que haga lo que quieras que haga :)

Por otro lado, te recomiendo leer sobre [Markdown](https://docs.github.com/es/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) que te permite formatear tu mensaje para que sea mucho más accesible para todo el resto.
En este caso, te editamos el mensaje para que quede formateado como código en C, te dejo la guía de [bloques de código en Markdown](https://docs.github.com/es/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) para hacerlo :)

Saludos!
     Lean

**Comment by mSpadoni** [comment]
gracias, el tema es que ya lo probé pero no se como terminar el ciclo para pasar a la siguiente parte del programa

**Comment by LeandroCarbajales** [comment]
Genial :)
Para eso podrías por ejemplo tener un condicional más que haga el `break;`, se me ocurre al escribir "end" o algo por el estilo.
Por otro lado, el `log_info()` podrías hacerlo inmediatamente después del `readline()`, de lo contrario no estarías imprimiendo el valor por pantalla antes de finalizar el programa o cortar el ciclo.

**Comment by mSpadoni** [comment]
gracias, se pueden agregar funciones extras al programa??

**Comment by mSpadoni** [comment]
gracias
