### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by mSpadoni** [sisoputnfrba/foro#3418]
Hola, alguno sabe por que me escribe CLAVE si yo nunca lo ingrese??

[INFO] 21:02:31:489 Servidor/(14577:14577): Servidor listo para recibir al cliente
[INFO] 21:03:22:427 Servidor/(14577:14577): Se conecto un cliente!
[INFO] 21:03:22:428 Servidor/(14577:14577): Me llego el mensaje valor
[INFO] 21:03:22:428 Servidor/(14577:14577): Me llegaron los siguientes valores:

[INFO] 21:03:22:428 Servidor/(14577:14577): CLAVE
[ERROR] 21:03:22:428 Servidor/(14577:14577): el cliente se desconecto. Terminando servidor

**Comment by mSpadoni** [comment]
void leer_consola(t_log* logger){
	 char *leido;
    while (1) {
        leido = readline(">");
		if (strcmp(leido,"")==0) {
            exit(1);
        }
		if(strcmp(leido,"end")==0) {
            break;
        }
		log_info(logger,"%s\n",leido);
		free(leido);
    }
   free(leido);
}

**Comment by mSpadoni** [comment]
void paquete(int conexion){
char* leido;
int tam=strlen(leido) + 1; // leido me aparece subrayado en amarillo y me aparece este error 'leido' is used uninitialized
t_paquete* paquete=crear_paquete();
agregar_a_paquete(paquete,leido,tam);
enviar_paquete(paquete,conexion);
eliminar_paquete(paquete);
}

**Comment by mSpadoni** [comment]
No se si esto sirve de algo

**Comment by mSpadoni** [comment]
lo pude resolver

**Comment by RaniAgus** [comment]
¡Buenas! Es muy probable que se deba justamente al warning que vos señalás en esta línea:

```c
int tam=strlen(leido) + 1; // leido me aparece subrayado en amarillo y me aparece este error 'leido' is used uninitialized
```

Por si no se entiende el inglés, la traducción es: "`leido` está siendo usado sin inicializar"

Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

Antes que nada, permitime ordenar un poco algunas cosas, porque durante el día veo que venís abriendo una cantidad interesante de issues (7 para ser exacto) y en la mayoría se repite un mismo patrón y es que tiras una foto de la pantalla, un log o algo a medio explicar y sin un contexto con el cual nosotros te podamos ayudar.
Entonces para empezar te pido que por favor leas la guía de uso del foro que se encuentra en el [README del repositorio](https://github.com/sisoputnfrba/foro).

En segundo lugar, es importante que antes de empezar a crear issues a mansalva pares la pelota y te pongas a analizar lo que estuviste haciendo, el código que escribiste y el código que ya tenias anteriormente, para que nos puedas explicar que estas haciendo, de donde vienen las cosas que ves y como es que llegaste a la situación actual, para poder hacer eso, te recomiendo que veas la [Guía de Debugging que esta en la página de docs](https://docs.utnso.com.ar/guias/herramientas/debugger).

En tercer lugar, cuando algún ayudante te pida algo de info extra para poder darte una mano, no hace falta que tires 2 o 3 mensajes con pedazos de código, podes utilizando un poco de markdown dejar todo en un solo comment cosa de que sea mas fácil de seguirlo.
Por ejemplo, en este caso, el valor CLAVE, puede ser algo que estas levantando del archivo de configuración o algún `log_info()` que pusiste que no estamos viendo, porque en el código que nos compartiste no vemos nada relacionado a recibir un paquete o similares.

Saludos.-
