### ISSUE TITLE
Duda respecto a como funciona "agregar_a_paquete()"

### ISSUE THREAD

**Issue by ValenSampayo** [sisoputnfrba/foro#3419]
Buenas, no tengo error en el envío del paquete en sí pero el tamaño del string que se envia queda corto en varios casos, lo revise debugeando y al agregar datos al paquete se agregan pasando el parametro "tamanio" de la función usando sizeof(leido) que es un char* y el tamaño siempre queda como 9. Probé cambiar este ultimo parametro pasando el tamaño usando la función strlen(leido) y los mensajes se leen bien y no me salto ningún error pero tengo la duda de si la función usaba sizeof() porque quedo de una versión vieja del TP0  o si es por pura casualidad que anda bien con el strlen().

Mensajes enviados usando sizeof():
![image](https://github.com/sisoputnfrba/foro/assets/49347551/0b4756db-0096-4382-8010-e0d3a14564af)

Mensajes enviados usando strlen():
![image](https://github.com/sisoputnfrba/foro/assets/49347551/63a49569-cfe6-4282-9bd2-a7976f523014)

**Comment by iago64** [comment]
Buenas! Cómo va?

Algo super importante de C es el entender como funcionan los tipos de datos y algunas funciones.
`sizeof()` lo que va a hacer es darte el tamaño de lo que pesa **la variable** y no su contenido.
`strlen()` lo que te va a devolver es el tamaño del **string**, y es importante que entendamos que para que un **string** sea un **string** tiene que terminar con el caracter `\0` que es no imprimible,

Esto hace que cuando vos le digas `sizeof()` de un `char*` lo que hace `sizeof()` es decirte, mira, el puntero pesa 8 bytes (porque estamos en una arquitectura de 64 bits) mientras que `strlen()` lee a lo que apunta ese `char*` y calcula cuanto pesa el string.

Como para completar un poco mas, te dejo la [Guía de Manejo de Punteros y Memoria Dinámica](https://docs.utnso.com.ar/guias/programacion/punteros) donde esta mucho mas explicado como funciona todo este extraño mundo de las variables en C.

Saludos.-

**Comment by RaniAgus** [comment]
Buenas! Para sumar, algo muy importante a tener en cuenta es que `sizeof` es un **operador**, no una función. ¿Qué significa esto? Que los valores que devuelve siempre se pueden calcular en tiempo de compilación (en otras palabras, son estáticos, no dependen del contenido de la variable, sino del tipo de la variable en sí).

Es decir, como bien dice Dami, si vos hacés `sizeof` de `char*` o de cualquier otra variable de tipo puntero (`int*`, `float*`, `void*`, `char**`...), el valor que te va a calcular es siempre el mismo: el tamaño de un puntero.

Si vos lo que querés es en realidad calcular dinámicamente el tamaño de un string (o sea, el valor va a cambiar entre ejecución y ejecución), un operador no te va a servir, sino una función. En este caso, `strlen()` es una función súper simple que va leyendo caracter a caracter partiendo desde la dirección de memoria que le indicás hasta encontrar un caracter nulo (o sea, un `\0`).

Saludos

**Comment by ValenSampayo** [comment]
Perfecto ahí quedo más claro, gracias a ambos, cierro el issue.

Saludos
