### ISSUE TITLE
Problema con los CD de los complementos de invitados

### ISSUE THREAD

**Issue by MarcoIoannisci** [sisoputnfrba/foro#3421]
Buenas, ando con un problema con el tema de expandir la pantalla y que se ajuste...y el problema es que no aparece nada, no aparece ninguna ventana nueva, no me tira error ni nada por el estilo. Encontre este video por YouTube para ver si podia resolverlo, pero estoy preocupado de colgar la VirtualBox, y aun con la pantalla reducida puede funcionar. Si a alguien le paso lo mismo porfa digame como hizo.
https://www.youtube.com/watch?v=Hqgm-Nzc-BA

(Por lo que estoy escuchando estos problemas les pasan a gente que tiene AMD en vez de Intel)

Por ahora estoy usando la opcion que dan de expandir la pantalla, pero se ve bastante pixeleada, asique si alguien pudo encontrarle solucion se lo agradeceria.

**Comment by RaniAgus** [comment]
¡Buenas! 

Cada tanto a lo largo de los cuatrimestres surgen problemas para redimensionar la pantalla dinámicamente, y normalmente terminamos sugiriendo como workaround es aumentar la resolución desde los ajustes de Display de la VM (o sea, desde el propio Linux). 

![image](https://github.com/sisoputnfrba/foro/assets/39303639/342ef1a4-384f-484e-8905-8a876cfe18f6)

Si bien no es lo ideal ya que no se puede redimensionar a gusto, al menos te permite trabajar con un tamaño de pantalla razonable.

Me parece más importante que puedas copiar y pegar entre host y guest. Si lograste hacer eso, significa que las Guest Additions están correctamente instaladas 👍🏻

Saludos

**Comment by MarcoIoannisci** [comment]
Eso tampoco lo pude chequear pero mas por el hecho que no encuentro el bloc de notas en la virtualBox. Busco el leaf en el buscador del inicio y no aparece. Y no entiendo que comando uso en el video para buscarlo

**Comment by MarcoIoannisci** [comment]
Acabo de probar viendo si podia copiar y pegar en el buscador de inicio de linux y tampoco funciona.

**Comment by RaniAgus** [comment]
¡Buenas! No entendí, ¿funciona o sigue sin funcionar? De no funcionar, ¿seguiste lo que dice el video para habilitar el portapapeles compartido? Que es básicamente:

![image](https://github.com/sisoputnfrba/foro/assets/39303639/b7a4a4e5-9dea-4142-b6b1-462eaa419573)

También, sobre un comentario anterior, me refería a redimensionar la pantalla **desde Linux**. No sé si lo habrás notado pero la captura de pantalla anterior no está en virtualbox sino que aparece al buscar "Display" (o sea, "Pantalla") en el buscador de aplicaciones:

![image](https://github.com/sisoputnfrba/foro/assets/39303639/dc0ccf3c-0df9-4f8a-9d10-9da688c56ddd)

De todas formas, si ya te funciona el redimensionado, mejor 👍🏻

**Comment by MarcoIoannisci** [comment]
Hola, por lo que vi del video que esta en la pagina de instalacion de VM segui los pasos y me aparece asi 
![image](https://github.com/sisoputnfrba/foro/assets/63261451/acf48522-6494-4975-b614-88ff80cf3a53)
pero no esta funcionando ni el copiado y pegado, ni insertar imagen de cd de los complementos del invitado.
Lo otro del display acabo de probarlo y ahi me funciono. No se si tengo que esperar que aparezca algo cuando hago click en insertar imagen de cd de los complementos del invitado, pero si tengo que esperar no pasa nada.

Igual gracias por la ayuda con el display de la pantalla

**Comment by iago64** [comment]
Buenas! cómo va?

Consulta, cuando insertas el CD de los complementos, te tira algun error o simplemente no hace nada?

Saludos.-

**Comment by MarcoIoannisci** [comment]
Hola a ambos, pude hablar con mi profesor y si, nos dimos cuenta que no pude instalar las guest additions, pero no me tira ningun error, ni me aparece ninguna pantalla, asique no tengo nada para saber como solucionar el problema.

Busque estos videos por internet pero estoy preocupado porque en algunos de los que busque me decia que se podia colgar la VM, y en otros la VM es windows y no Linux, por lo que estoy preocupado de meter mano donde no debo:

https://www.youtube.com/watch?v=2uWadn6xjvw

https://www.youtube.com/watch?v=s2yeJ4LRPXA

Desde ya muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

Para que tengas de referencia la configuración de la VM debería estar como la siguiente (puede tener menos memoria base, yo la tengo con 6gb porque hice una prueba y quedo, pero con 4gb ya debería funcionar correctamente)
![image](https://github.com/sisoputnfrba/foro/assets/1622109/051b7415-13ca-41e3-8fb4-6a8c1cf0adb1)

Por otro lado cuando insertas el CD de las guest additions, no te aparece el siguiente icono en el escritorio de la VM?
![image](https://github.com/sisoputnfrba/foro/assets/1622109/3b7728e8-d79b-422a-93a0-a4f4432d6e09)

Saludos.-

**Comment by MarcoIoannisci** [comment]
Buenas, aca mando imagen de mi VM, por lo que veo esta casi igual (lo raro es que dice Intel cuando yo tengo AMD)
![image](https://github.com/sisoputnfrba/foro/assets/63261451/42087ea5-7344-451d-8db4-730427d8304f)

En cuanto a la segunda imagen, eso siempre lo tengo a la vista cuando inicio la VM. Apreto ahi y veo que ocurre?

![image](https://github.com/sisoputnfrba/foro/assets/63261451/648f8dee-e09c-472b-a388-a1a048bb8f72)

**Comment by RaniAgus** [comment]
¡Buenas! Exactamente. Tal y como está explicado en el vídeo, hay que hacer doble click en ese icono para que se abra una carpeta, y de ahí poder levantar una terminal y ejecutar los comandos. Saludos

**Comment by MarcoIoannisci** [comment]
No esta funcionando el redireccionamiento 
![image](https://github.com/sisoputnfrba/foro/assets/63261451/667983a8-883f-45e0-bcce-d9e8ea1f6c63)

**Comment by RaniAgus** [comment]
No te está tomando el comando porque es `cd` y vos estás ingresando `..cd`

De todas formas lo que te sugería era mucho más simple, y es exactamente lo mismo que está en el video en docs pero con una versión distinta de Ubuntu:

![Alguien haciendo click derecho en un icono de CD para luego más adelante hacer click derecho y abrir una terminal en la carpeta actual](https://github.com/sisoputnfrba/foro/assets/39303639/f3f185b6-f434-4ba8-b5b1-13c7917e8724)


Saludos

**Comment by MarcoIoannisci** [comment]
Perfecto, ya esta andando todo, tanto el modificar tamaño de la pantalla como el copiar y pegar Gracias
