### ISSUE TITLE
Tp0-etapa 2, problema con "log_create"

### ISSUE THREAD

**Issue by santti0** [sisoputnfrba/foro#3423]
Buenas noches, estoy teniendo problemas con log create, Al compilar me tira "undefined to reference "log_create"" tampoco me crea el archivo, más que nada quisiera saber que me está tirando al compilar. 

Parados en el archivo cliente.c, si revisamos el header de log de las commons vamos a encontrar la función log_create(), que nos devuelve un logger listo para usar.

Ayudándonos con la descripción que aparece en el header, vamos a configurarla para que:

Loguee en el archivo "tp0.log"

Muestre los logs por pantalla (y no solo los escriba en el archivo)

Muestre solo los logs a partir del nivel "info".

Declare a parte las variables que iba a usar  de parametros.
Lo que yo hice fue: logger = log_create(...);
Log_info(logger,"message")

![IMG-20240402-WA0008.jpg](https://github.com/sisoputnfrba/foro/assets/114032498/18c6fc25-4016-4d9e-8afd-510a70cec22e)

**Comment by RaniAgus** [comment]
¡Buenas! Me parece que están teniendo el mismo problema que en #3385 y #3387. Saludos

PD: Para la próxima, porfa lean el [README del foro](https://github.com/sisoputnfrba/foro/blob/master/README.md), ya que entre otros tips se recomienda copiar y pegar el texto en lugar de usar capturas de pantalla. También a la hora de crear un [primer proyecto C](https://docs.utnso.com.ar/primeros-pasos/primer-proyecto-c#errores-de-compilacion) les dejamos un par de heurísticas sobre cómo reportar errores de compilación

**Comment by LeandroCarbajales** [comment]
Buenas @santti0 !
Te sirvió la respuesta de @RaniAgus ? Pudiste resolver el problema?

**Comment by santti0** [comment]
Buenas, si pude resolver el problema, muchas gracias!!, cierro el issue
