### ISSUE TITLE
Utilizacion de otro sistema para el TP.

### ISSUE THREAD

**Issue by mathiVelazquez** [sisoputnfrba/foro#3424]
Hola, buenos días, quería consultarles si se podría utilizar un WSL para el desarrollo del trabajo practico, ya que el mismo lo tengo instalado en la máquina desde antes, con el Sistema de Ubuntu.

He estado buscado la palabra "WSL" y vi que hay 2 issues donde se nombra por arriba el uso del mismo.

¡Muchas gracias y saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

Pueden usar WSL para desarrollar el TP, pero tene en cuenta que las pruebas si o si se van a correr en la VM de Ubuntu Server.

Saludos.-
