### ISSUE TITLE
No puedo correr la vm en mac M1

### ISSUE THREAD

**Issue by oxnico** [sisoputnfrba/foro#3425]
Hola, hay alguna forma de hacer la maquina funcionar en M1? Usando la beta disponible de VB para M1 y siguiendo todos los pasos, me crashea cuando la inicio

**Comment by iago64** [comment]
Buenas! Cómo va?

Dentro del apartado de [Conseguir un entorno Linux](https://docs.utnso.com.ar/primeros-pasos/entorno-linux) que justamente es para casos como el tuyo que no podes instalar virtualbox ya que tienen mac con ARM, dejamos un tutorial de virtualización con UTM y estan los scripts para que puedan instalarse un ubuntu desde la imagen server.

![image](https://github.com/sisoputnfrba/foro/assets/1622109/1491f051-4379-482e-aa8e-5eabe81e7d59)

La VM pre armada no va a funcionar en ARM ya que fue armada utilizando un host x86 / x64

Saludos.-

**Comment by oxnico** [comment]
Pude instalar la maquina virtual pero no instalarle los paquetes, cuando entro al "curl -fsSL https://faq.utnso.com.ar/XXXXX.sh" pongo sudo sh -x y pongo mi contraseña como dice en el read me pero no se instala nada (en todos pasa lo mismo). También lo probe sin el sudo.

**Comment by oxnico** [comment]
probe clonando el repo y corriendo los scripts, el de base server me tiraba que ya lo tenia instalado, el de la interfaz grafica se quedo en 0% y nunca se instaló 

<img width="1440" alt="Screenshot 2024-04-05 at 11 58 05" src="https://github.com/sisoputnfrba/foro/assets/76959273/42417aa5-dc04-46d3-b137-c2fe8019b42f">

**Comment by RaniAgus** [comment]
¡Buenas! Traigo novedades: Hace un tiempo teníamos semi-cocinada una guía de @mgarciaisaia para emular las VM server usando UTM, pero no habíamos llegado a testearla. Estas últimas horas @FredeHG se puso la diez para hacerlo y también agregamos una sección más para poder conectarse a ella desde Visual Studio Code y desarrollar remotamente.

Link a la guía: https://docs.utnso.com.ar/guias/herramientas/macos-arm

Tengamos en cuenta que es experimental y puede ser un poquito _heavy_ seguirla, pero tenemos fe de que va a funcionar bastante bien. Ante cualquier duda venite un sábado de soporte y lo terminamos de pulir 😉

Saludos

**Comment by iago64** [comment]
Buenas! @oxnico pudiste probar la guía que te dejo @RaniAgus?

Saludos.-

**Comment by oxnico** [comment]
Ahi pude hacer que arranque, Gracias! lo único que el teclado esta en español y no lo puedo cambiar a ingles como esta mi teclado.

**Comment by RaniAgus** [comment]
¡Buenas! Solo para confirmar: ¿lograste que arranque siguiendo la nueva guía para emular y luego conectarte por SSH, cierto?

Por otro lado, para cambiar el layout del teclado en la VM server podés editar el archivo `/etc/default/keyboard` para que la variable `XKBLAYOUT` diga `"us"` en vez de `"latam"` :)

Saludos

**Comment by oxnico** [comment]
Hola, ya pude conectar al SSH. Gracias

**Comment by iago64** [comment]
Excelente, si ya no quedan dudas, por favor no te olvides de cerrar el issue. 👮‍♂️
