### ISSUE TITLE
Dudas con el mario bash

### ISSUE THREAD

**Issue by MarcoIoannisci** [sisoputnfrba/foro#3426]
Buenas, estoy en el ultimo nivel del mario bash y tengo una duda sobre la parte que me pide mover la bomba a otra directorio.
```
mario@utnso:~/mundo_desierto$ scp /home/mario/mundo_desierto/1.bomba koopa_ip@192.168.0.13:/home/koopa
No existe el archivo o el directorio.
mario@utnso:~/mundo_desierto$ scp /home/mario/mundo_desierto/1.bomba koopa_ip192.168.0.13:/home/koopa
No existe el archivo o el directorio.
mario@utnso:~/mundo_desierto$ scp /home/mario/mundo_desierto/1.bomba koopa@192.168.0.13:/home/koopa
No existe el archivo o el directorio.
mario@utnso:~/mundo_desierto$ scp /home/mario/mundo_desierto/1.bomba koopa@192.168.0.13:/home/koopa
No existe el archivo o el directorio.
mario@utnso:~/mundo_desierto$ scp 1.bomba koopa@192.168.0.13:/home/koopa
No existe el archivo o el directorio.
```
Probe estas 4 opciones pero no funciona, por lo que tengo la suposicion de que el problema esta en el directorio del koopa. Tambien tengo una consulta con las funciones que sirven para mover o eliminar, ya que aparece para utilizar 3 parametros pero no me funcionaba asi, solo me funcionaba cuando le mandaba 2. Ej aca:

 mv -opciones origen destino

solo me funcionaba cuando ponia la opcion y el destino, cuando trataba de poner la opcion, el origen y el destino me tiraba error

**Comment by RaniAgus** [comment]
¡Buenas! 

> Probe estas 4 opciones pero no funciona, por lo que tengo la suposicion de que el problema esta en el directorio del koopa. 

Si ejecutás `man scp` vas a ver una descripción simple de los parámetros que recibe el comando. Prestá más atención al parámetro `user`.

> solo me funcionaba cuando ponia la opcion y el destino, cuando trataba de poner la opcion, el origen y el destino me tiraba error

Supongo que habrás querido decir que te dejaba poner origen y destino. Entiendo, tengan en cuenta que Mario Bash ofrece una versión simplificada de los comandos de Bash, por lo que puede que falten opciones, pero las que hay son suficientes para completar todos los niveles.

Saludos

**Comment by MarcoIoannisci** [comment]
Hola Rani, no en el nivel uno directamente dice mover las monedas al cofre, y cuando lo hacia solo funcionaba si ponia

`mario@utnso:~/mundo_nube$` ls

cofre

instrucciones.txt`
1.moneda
2.moneda
1.estrella
2.estrella
3.estrella
mario@utnso:~/mundo_nube$ mv 1.moneda cofre`

no funciona en el caso que escriba mario@utnso:~/mundo_nube$ mv 1.moneda mundo_nube cofre`

**Comment by RaniAgus** [comment]
¡Está bien! El parámetro `origen` que recibe `mv` es justamente el propio archivo. Por otro lado, el parámetro `destino` puede ser:
a. Un directorio existente hacia la cual mover el archivo
b. El nuevo nombre del archivo (en caso de que no exista un directorio con el mismo nombre)

Es por esto que sirve tanto para mover archivos como para renombrarlos. Por ejemplo, podés escribir `mv 1.moneda cofre`, o sino `mv 1.moneda cofre/1.moneda`.

Saludos

**Comment by iago64** [comment]
@MarcoIoannisci Cómo va?

Te sirvieron las respuestas de @RaniAgus?

Saludos.-

**Comment by MarcoIoannisci** [comment]
Hola, la verdad no me quedo claro. ` mv -opciones origen destino` entiendo como que deberian ser 3 datos que le tengo que mandar. opciones = seria la moneda, origen = seria el mundo_nube, destino = seria el cofre, pero solo me funciona cuando uso `mv 1.moneda cofre` si hago lo 1ero entonces me tira:
`mario@utnso:~/mundo_nube$ mv 1.moneda mundo_nube cofre
mv: falta el operando archivo de destino después de «1.moneda»`

**Comment by RaniAgus** [comment]
¡Buenas! El parámetro `-opciones` es muy común a la hora de trabajar con comandos por consola. Es **opcional** (valga la redundancia) y como se indica en la descripción, viene precedido por un guión: `-`.

En el caso de `mv`, una opción copada puede ser `-v` (de **v**erbose), que sirve para imprimir por pantalla el archivo que se movió o renombró. Por ejemplo, si ejecutás `mv -v 1.moneda cofre` probablemente se imprima algo como:
```
renamed '1.moneda' -> 'cofre/1.moneda'
```

Entonces, volviendo a tu caso, al ejecutar `mv 1.moneda cofre`, como ningún parámetro viene precedido por `-`, estás diciendo que `1.moneda` es el origen y `cofre` es el destino, sin ninguna opción extra.

Saludos

**Comment by MarcoIoannisci** [comment]
Ah, ok gracias por la respuesta, ahi me quedo clara.

Ahora tengo otra duda pero con el scp:
`Copiar un archivo de un ordenador remoto al 
ordenador local: 
         scp user@ip_host:/ruta_archivo_origen 
ruta_dir_destino `

la duda es por qué no funciona este copiado.
`mario@utnso:~/mundo_hongo$ scp 
luigi@192.168.0.5:/home/luigi/mensaje.txt 
home/mario/mundo_hongo 
No existe el archivo o el directorio.`

pero si funciona este:
`mario@utnso:~/mundo_hongo$ scp 
luigi@192.168.0.5:/home/luigi/mensaje.txt .`

**Comment by RaniAgus** [comment]
Eso se debe a que `home/mario/mundo_hongo` y `/home/mario/mundo_hongo`, si bien parecen similares, son dos rutas completamente distintas. Las rutas que empiezan con `/` son **absolutas** (es decir, parten desde el directorio raíz) y las que no son **relativas** a la carpeta desde la cual estás ejecutando el comando.

Esto está explicado más en detalle en la siguiente guía: https://docs.utnso.com.ar/guias/consola/rutas

Saludos

**Comment by MarcoIoannisci** [comment]
Gracias, ahora le hago un chequeo a esa guia.

**Comment by RaniAgus** [comment]
¡Dale! Avisanos cómo te fue y si está todo bien sentite libre de cerrar el issue :)

**Comment by iago64** [comment]
@MarcoIoannisci Cómo va?

Al final como te fue con Mario Bash? Necesitas ayuda con algo mas?

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, ante cualquier consulta pueden reabrirlo o abrir uno nuevo. Saludos

**Comment by MarcoIoannisci** [comment]
Buenas, si. Disculpen que no respondiera pero me habia olvidado. Al fianl ya se me aclararon todas las dudas. Gracias
