### ISSUE TITLE
Prolema con linux , Abriendolo con la maquina virtual

### ISSUE THREAD

**Issue by Ro0xx0** [sisoputnfrba/foro#3428]
Segui todos los pasos ,me deja abrirlo pero no el sitema operativo y me aparece esto 
![Captura de pantalla 2024-04-03 191537](https://github.com/sisoputnfrba/foro/assets/164669511/f9b76973-1377-4781-b796-1043d225f9cf)

**Comment by santi12386** [comment]
Buenas, en nuestro grupo tuvimos problemas parecidos. Parece que en la imagen de kubuntu que esta en el drive (en 2 partes) puede traer problemas al momento de extraerse.

Recomiendo probar de hacer los checksum en las 2 partes del .zip y ver si te dan los mismos valores que se muestran en el blog.

**Comment by iago64** [comment]
Buenas!

Aparte del aporte de Santi, sumo una pregunta, ¿Qué configuración le pusiste a la VM en virtualbox?

Saludos.-

**Comment by Ro0xx0** [comment]
Hola , 
el  checksum ya lo hize y me muestran los mismos valores, y no me funcina,
Puse la condifuracion q viene en el video ,segui los pasos del tuto,
Y probe con otro sistema operativo ,(Un ubuntu mas actulizado) me aparece lo mismo
Probe con otra aplicacion  y me funciono, creo q el prolema es vitual box,puedo usar otra aplicacion aplicacion? y otro ubuntu ?

**Comment by iago64** [comment]
Buenas!

Respecto a usar otras alternativas de software de virtualización, como puede ser VMWare, pueden usarlas, no hay problema, nosotros desde la facultad no podemos tener como default un software que tiene licencia, pero uds por su cuenta pueden usarlo.

Respecto a la versión de ubuntu, las VMs estan basadas en 22.04 y les recomendamos que usen esa versión ya que es una version LTS o Long Term Support, pero si quieren instalarse un ubuntu por su cuenta pueden, de hecho esta público el [repo que tiene todos los scripts de todo lo que tiene instalada la VM](https://github.com/sisoputnfrba/entorno-vms).

Tengan en cuenta nomas que el script de interfaz-grafica les instala cosas propia de XFCE y que si usan Ubuntu y no Xubuntu muy posiblemente no funcione.

Saludos.-

**Comment by iago64** [comment]
@Ro0xx0 Cómo va?

Pudiste resolver el tema de la VM? Necesitas ayuda con algo mas?

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, ante cualquier consulta pueden reabrirlo o abrir uno nuevo. Saludos
