### ISSUE TITLE
Dudas sobre el modulo I/O

### ISSUE THREAD

**Issue by MartoSimon** [sisoputnfrba/foro#3429]
Buenaas, estaba leyendo la parte de las interfaces de I/O y me surgió una duda con respecto a en que momento es que se crean las mismas. Con mi grupo no terminamos de entender si es que al momento de iniciar los módulos debemos crear una interfaz de cada tipo o si estas se van creando al momento de que el kernel lo vaya pidiendo y es posible que haya más de una interfaz de cada tipo.

También aprovecho para preguntar sobre como es el tema de los checkpoints de la interfaz DialFS, ya que en ninguno de los checkpoints se la menciona. Esta consulta es más que nada para saber cuanto debería estar hecho de esa interfaz para cada uno de los checkpoints.

Saludos!

**Comment by LeandroCarbajales** [comment]
Buenas!
Las mismas se pueden conectar (y desconectar) al Kernel en cualquier momento, hay una aclaración en el enunciado en la parte de "manejo de interfaces" del Kernel:
`Toda interfaz de I/O puede conectarse y desconectarse en tiempo de ejecución.`
Por otro lado, no debería haber limitación en los tipos ni cantidad de interfaces que pueden conectarse al Kernel, podrían tener una de cada tipo, o 3 de STDIN, 1 DialFS y 2 genéricas o cualquier otra combinación.

Para hacerlo de forma evolutiva, pueden arrancar con una sola interfaz que se conecte al Kernel y nunca se desconecte, cuando tengan eso funcionando pueden evolucionarlo para que se conecten varias, y en una evolución final tomar en consideración cuando alguna se desconecta.

Con respecto a los checkpoints y el DialFS, el mismo se pide solamente para la entrega final, no para los checkpoints intermedios.

Te aclara las dudas?
Saludos!
     Lean

**Comment by MartoSimon** [comment]
Clarisimo Lean, solo tengo una última consulta. ¿Cómo le llega al I/O que tipo de interfaz se debe crear? ¿Qué módulo se lo indica y en que momento se lo dice?

**Comment by LeandroCarbajales** [comment]
Cada interfaz será del tipo que indique el archivo de configuración al momento de crearse la misma.
<img width="733" alt="Screenshot 2024-04-03 at 21 06 21" src="https://github.com/sisoputnfrba/foro/assets/11889948/b325627a-5450-4045-8efc-67e276ad2f77">

**Comment by MartoSimon** [comment]
Perfecto Lean, muchas gracias
