### ISSUE TITLE
problema al iniciar lubuntu

### ISSUE THREAD

**Issue by luchito12** [sisoputnfrba/foro#3430]
al iniciar lubuntu me sale  _  y se queda ahi y no carga el sistema operativo
chequie todos los hash md5 y me dieron correctamente
### 🔎 Búsqueda en foros
busque en Internet soluciones, y una era iniciar el sistema en modo recovery, pero al iniciarlo me volvía a salir _ otra era asignar mas memoria de vídeo, pero seguía saliendo _

### 📦 Especificaciones de la VM
Versión de VirtualBox:  7.0
- Memoria RAM asignada: 1024mb
- tipo: linux 
- version: ubuntu 32(bits)

### 🖥️ Especificaciones del host
- Sistema Operativo y versión:  windows 10, versión 22H2
- Memoria RAM: 16gb
- Procesador: ryzen 5600g
 al principio tuve que activar la virtualizacion desde la bios 

### 💻 Logs
lo que obtengo en pantalla es _ esa linea que parpadea constantemente 
![VirtualBox_lubunto_03_04_2024_23_04_47](https://github.com/sisoputnfrba/foro/assets/82194770/dca71733-64e2-4e35-b08b-950b04986c2c)

**Comment by iago64** [comment]
Buenas! Cómo va?

Por desgracia las viejas VMs de Lubuntu que se usaban cuando se grabó el video eran de 32-bit, las nuevas de Xubuntu son de 64-bit y al configurar Virtual Box hay que poner como sistema Ubuntu (64 Bit).

La mala noticia es que cuando configuras la VM con un "host" de 32 bit, tenes que volver a extraer el VDI ya que VirtualBox por lo general corrompe el VDI.

Saludos.-

**Comment by luchito12** [comment]
muchas gracias, ahí lo pude solucionar

**Comment by iago64** [comment]
Si lo pudiste solucionar, por favor no te olvides de cerrar el issue 👮‍♂️

Saludos.-
