### ISSUE TITLE
TP0: Tengo un problema etapa 2 - Leer consola  free(): invalid pointer

### ISSUE THREAD

**Issue by Fernagarcia** [sisoputnfrba/foro#3431]
Buenas, estaba realizando la parte de Leer consola del punto 2 cuando al correr el cliente.c me salta un warning en la funcion `crear_conexion()` que no me permite terminar el programa y no entiendo porque.
![ayuda](https://github.com/sisoputnfrba/foro/assets/87620647/acb05c1f-6eda-4a7c-b2ed-d10d22abb249)

Continúe con el TP para ver si se arreglaba más tarde pero no fue así.  Y no se si es porque me falta una dependencia o algo pero justo es de una linea que no codee yo.

Desde ya, muchas gracias.

**Comment by iago64** [comment]
Buenas! Cómo va?

Algo te está fallando al momento de ejecutar la función `getaddrinfo()`.
Esto lo ves porque la variable err está en -1, esto se debe a que estas posiblemente leyendo mal la config y a la ip no le estas pasando una dirección IP si no que le estas pasando el string `valor` esto hace que `getaddrinfo()` no funcione correctamente y termine explotando cuando haces el llamado a `freeaddrinfo()`

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! No entendí bien si te referís al warning en la línea 28 o si es el error `free(): invalid pointer`.

De ser el primer caso, justo en una parte de la guía de "mi primer proyecto C" les mostramos [cómo leer errores de compilación](https://docs.utnso.com.ar/primeros-pasos/primer-proyecto-c#errores-de-compilacion) y la diferencia entre un "warning" y un "error".

De ser el segundo caso, justo a la izquierda podés ver el estado de las variables: ¿son correctos los parámetros? ¿Cuál es el valor de `err`?

Saludos

**Comment by Fernagarcia** [comment]
Muchisimas gracias, ahi ya pude solucionarlo.
