### ISSUE TITLE
Cuando inicio la VM me queda en initramfs

### ISSUE THREAD

**Issue by jasminecucagna** [sisoputnfrba/foro#3432]
Buenas! Estoy teniendo problemas con la maquina virtual. 
La instalé hace unos días, me funcionaba todo perfecto, pero en el día de hoy cuando vuelvo a ingresar el Visual Studio estaba medio trabado, por lo que decidí apagar la maquina y volverla a prender. 
Una vez que la prendo me lanza este mensaje, selecciono Ubuntu (también probé seleccionando el Advanced pero pasa lo mismo)
![b860e16a-c919-4682-9b8b-7d7bd9561e06 (1)](https://github.com/sisoputnfrba/foro/assets/82092650/e8ec1d38-4683-4a9f-b92c-b507f007e45e)
Y empieza a correr pero se queda trabado en initramfs
![WhatsApp Image 2024-04-04 at 11 57 16 AM](https://github.com/sisoputnfrba/foro/assets/82092650/f00ddd1c-7b9e-4c67-bc1e-6e8cad705e0e)

🔎 Búsqueda en foros
Estuve buscando en issues si a alguien le pasó, pero lo más cercano que encontré fue https://github.com/sisoputnfrba/foro/issues/2544 aunque no se relaciona con mi problema

Intenté tirar ls y el comando "mount /dev/sdXY /mnt" que me recomendó chatgpt pero tampoco me sirvió
![418026f9-22a1-495b-9cd3-43a6cf8fc342](https://github.com/sisoputnfrba/foro/assets/82092650/2d537e25-d3be-4812-b34b-46917ae98152)

Espero que me puedan ayudar! cualquier cosa que quieran visualizar me avisan,
Muchas gracias!

**Comment by jasminecucagna** [comment]
Hola buenas tardes! Lo único que hice fue cerrar y seleccionar la opción de "Apagar la Máquina"
![image](https://github.com/sisoputnfrba/foro/assets/82092650/40eeeb58-3bfe-4a65-a421-7157f3155848)
 
Les consulto, que desean saber específicamente de la VirtualBox?

**Comment by iago64** [comment]
La configuración que tiene la VM, una captura como la siguiente nos alcanza:

![image](https://github.com/sisoputnfrba/foro/assets/1622109/ccb91560-417f-423d-8bfb-69d43ac5b670)

Saludos.-

**Comment by jasminecucagna** [comment]
Hola buenas! te comparto la configuración de mi VM
![image](https://github.com/sisoputnfrba/foro/assets/82092650/5285a860-2b9a-4793-bffa-b5ef36ac3100)

**Comment by RaniAgus** [comment]
¡Buenas! Me hace un poco de ruido que en la sección de "Almacenamiento" aparezca un `.vdi` que se llama distinto a los que les proveemos y, además, tiene menos capacidad. Normalmente debería decir algo como lo siguiente:

![image](https://github.com/sisoputnfrba/foro/assets/39303639/52e5e50d-a9e3-47fa-b2f3-a295271e6c8c)

Creo que lo más sencillo será volver a seguir el tutorial para descargar e importar el `.vdi` :(

Si luego de hacerlo y reiniciar te sigue apareciendo el problema, avisanos

Saludos

**Comment by jasminecucagna** [comment]
Hola buenos días! Ahí volví a bajarme todo y por ahora va todo OK.
Muchas gracias! Saludos

**Comment by iago64** [comment]
Buenisimo! Si esta resuelta la duda, no se olviden de cerrar el issue 👮‍♂️
