### ISSUE TITLE
Problemas a la hora de compartir archivos

### ISSUE THREAD

**Issue by LucasAponte** [sisoputnfrba/foro#3433]
Hola, como dice el titulo cuando intento compartir algún archivo de la maquina física a la virtual no me deja abrirlos, me tira lo siguiente:

![image](https://github.com/sisoputnfrba/foro/assets/127443180/83224e56-268a-4fca-8de3-c5be52558e0a)

y ahora tambien para la carpeta UTNso

![image](https://github.com/sisoputnfrba/foro/assets/127443180/719c7925-ec53-40e6-a902-4c720d5f92cc)

Ya instalé los Guest Additions y puse en la configuración que sea bidireccional.
Intenté Instalándolo de nuevo, pero no solucionó nada.

Investigué por Google, pero no llegué a nada.

Espero que me puedan ayudar, desde ya gracias :D.

**Comment by iago64** [comment]
Buenas! Cómo va?

En principio lo de bidireccional funciona solamente para el portapapeles.
Respecto a las carpetas, que estarías necesitando compartir entre la VM y la máquina host? Hay varias cosas que pueden tenerlas directamente en la VM sin necesidad de trabajar en su SO de base.

Saludos.-

**Comment by LucasAponte** [comment]
Hola, si si hablando con compañeros llegamos a la misma conclusión que no hacía falta. Pensaba que si porque en el video de como instalar las Guest Additions lo muestra y pensé que era obligatorio que funcioné eso, de todas formas, gracias por la ayuda :D.

**Comment by iago64** [comment]
Buenas!

No, no es obligatorio que funcione el tema de la carpeta compartida, lo teniamos porque hubo algunos tps donde les servía poder pasar archivos desde la pc host a la VM para poder llevarse sets de datos de un par de GB (Por suerte evolucionamos y ya no hacemos esos TPs que tardaban una eternidad en evaluarse)

Saludos.-
