### ISSUE TITLE
Duda sobre mi descarga fallida del template para el primer proyecto en c usando el comando

### ISSUE THREAD

**Issue by ahuarca** [sisoputnfrba/foro#3434]
Hola! Cuando quise ejecutar el comando para descargar el temaplate me salió este error, estuve investigando y puede ser que haya un error en el archivo comprimido, o que haya otros comandos más factibles para descomprimirlo

```
utnso@utnso:~/Desktop$ cd ejemplito
utnso@utnso:~/Desktop/ejemplito$ wget -qO- https://faq.utnso.com.ar/project.tar.gz | tar -xzvf - --strip-components 1

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

Después intente hacerlo de la otra forma, con un repo mio utilizando el template y ahí si pude acceder al template. 
![Captura de pantalla (88)](https://github.com/sisoputnfrba/foro/assets/163689778/96a6a401-06fe-4b5c-8340-ac6aa23bf113)

 Por las dudas también le quite la z a "xzvf", ya que era una solución que se recomendaba por si no se comprimia con esa extensión pero no me lo reconocé y devuelve esto: 

```
utnso@utnso:~/Desktop/ejemplito$ wget -qO- https://faq.utnso.com.ar/project.tar.gz | tar -xvf - --strip-components 1
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
```

**Comment by iago64** [comment]
Buenas! Cómo va?

Vamos en orden a manejar un poco los 3 comandos que estan en la guía de [Primer Proyecto en C](https://docs.utnso.com.ar/primeros-pasos/primer-proyecto-c).

`mkdir ejemplo` Sirve para crear una carpeta llamada ejemplo
`cd ejemplo` Sirve para moverse a la carpeta llamada ejemplo

Por último el comando picante que hace varias cosas es:
```
wget -qO- https://faq.utnso.com.ar/project.tar.gz | tar -xzvf - --strip-components 1
```

Este comando lo que hace con `wget -qO-` es bajar el archivo project.tar.gz
Despues viene un `|` ese caracter o pipe, lo que hace es que la salida del `wget` se lo pases al programa `tar` que lo que hace es descomprimir ese archivo .tar.gz que acabas de bajar, recibe varios parametros como el `-xzvf -` y el `--strip-components 1` el primero le indica como se "comprimió" el archivo para que `tar` lo pueda descompromir, y el segundo le dice que omita la carpeta, entonces al final del día lo que te termina quedando en la carpeta es lo siguiente:

```
utnso@utnso:~/ejemplo$ tree -a
.
├── .gitignore
├── makefile
├── README.md
├── settings.mk
├── src
│   └── main.c
└── .vscode
    ├── c_cpp_properties.json
    ├── launch.json
    ├── settings.json
    └── tasks.json

2 directories, 9 files
```

Por las dudas, esto solo les "facilita" una estructura similar a la que ya tienen en el repo que se les generó si se les confirmo el grupo en el sistema de inscripciones, si quieren el camino más "fácil" es clonarse directamente el repo de la cátedra que se les generó.

Saludos.-

**Comment by iago64** [comment]
@ahuarca Cómo va?

¿Pudiste avanzar con la creación del primer proyecto en C? Seguís necesitando ayuda con algo más?

Saludos.-

**Comment by ahuarca** [comment]
Holaa! sisi ya termine todo lo de mi primer proyecto en C, ahora me encuentro atascada en en la etapa 3, pero ya abrí un nuevo issues en #3449

**Comment by iago64** [comment]
Bien, si la duda esta resuelta, por favor no te olvides de cerrar los issues.
