### ISSUE TITLE
Problema en la etapa 2.

### ISSUE THREAD

**Issue by JuanTerri** [sisoputnfrba/foro#3435]
Muy parecido a lo que ocurre aca #3385
Pero volvi a la etapa 1, lo abri siguiendo estas instrucciones 
"TIP

También podemos abrir el proyecto abriendo Visual Studio Code haciendo click en File > Open Workspace from File... y seleccionando el archivo tp0.code-workspace que se encuentra en la carpeta del TP0."
Y sigue sin funcionarme, lo que me sale en consola es esto: 
"Executing task: C/C++: gcc build active file 

Starting build...
/usr/bin/gcc -fdiagnostics-color=always -g /home/juan/tp0/client/src/client.c -o /home/juan/tp0/client/src/client
/home/juan/tp0/client/src/client.c: In function ‘main’:
/home/juan/tp0/client/src/client.c:37:18: warning: passing argument 1 of ‘log_info’ from incompatible pointer type [-Wincompatible-pointer-types]
   37 |         log_info(config,"Valor leido de config",valor);
      |                  ^~~~~~
      |                  |
      |                  t_config *
In file included from /home/juan/tp0/client/src/client.h:6,
                 from /home/juan/tp0/client/src/client.c:1:
/usr/include/commons/log.h:88:41: note: expected ‘t_log *’ but argument is of type ‘t_config *’
   88 |         void            log_info(t_log* logger, const char* message, ...) __attribute__((format(printf, 2, 3)));
      |                                  ~~~~~~~^~~~~~
/home/juan/tp0/client/src/client.c:37:25: warning: too many arguments for format [-Wformat-extra-args]
   37 |         log_info(config,"Valor leido de config",valor);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/ld: /tmp/ccnyRdxv.o: in function `main':
/home/juan/tp0/client/src/client.c:21: undefined reference to `log_info'
/usr/bin/ld: /home/juan/tp0/client/src/client.c:30: undefined reference to `config_get_string_value'
/usr/bin/ld: /home/juan/tp0/client/src/client.c:31: undefined reference to `config_get_string_value'
/usr/bin/ld: /home/juan/tp0/client/src/client.c:32: undefined reference to `config_get_string_value'
/usr/bin/ld: /home/juan/tp0/client/src/client.c:37: undefined reference to `log_info'
/usr/bin/ld: /home/juan/tp0/client/src/client.c:48: undefined reference to `crear_conexion'
/usr/bin/ld: /tmp/ccnyRdxv.o: in function `iniciar_logger':
/home/juan/tp0/client/src/client.c:63: undefined reference to `log_create'
/usr/bin/ld: /tmp/ccnyRdxv.o: in function `leer_consola':
/home/juan/tp0/client/src/client.c:82: undefined reference to `readline'
/usr/bin/ld: /tmp/ccnyRdxv.o: in function `terminar_programa':
/home/juan/tp0/client/src/client.c:106: undefined reference to `log_destroy'
/usr/bin/ld: /home/juan/tp0/client/src/client.c:107: undefined reference to `config_destroy'
collect2: error: ld returned 1 exit status

Build finished with error(s)."

Sinceramente a lo que viene ser los warning no le estoy dando mucha bola (siento que esta medio bugeado ese tema) la mayoria son por usar "" o ´´ y otros son por cosas que ya venian codeadas de clonar el repo.

### 💭 Soluciones posibles

Un compañero me dijo que falta que se vinculen las commons
Tu gcc no está vinculando las commons
 -lcommons falta

**Comment by RaniAgus** [comment]
¡Buenas! ¿Podrías pasarnos un par de capturas de pantalla?

Primero, del explorador de archivos (debería verse así):

![image](https://docs.utnso.com.ar/img/primeros-pasos/tp0/vscode-file-explorer.png)

Y segundo, del menú desplegable de la pestaña "Run and Debug":

![image](https://docs.utnso.com.ar/img/primeros-pasos/tp0/vscode-run-debug.gif)

Saludos

**Comment by RaniAgus** [comment]
¿Estás ejecutando los módulos desde esa sección (la de "Run and Debug") seleccionando `run (client)` o `run (server)`?

Entiendo que en tu VSCode podría llegar a haber otros botones de play, pero solamente desde ese que le indicamos va a funcionar.

**Comment by JuanTerri** [comment]
Pido perdon, pensaba que era lo mismo de donde se ejecutaba, mala mia por hacerte perder tiempo ,me siento un boludo jajajajjaj
