### ISSUE TITLE
Necesito ayuda con las dos VMs

### ISSUE THREAD

**Issue by santiparis** [sisoputnfrba/foro#3436]
Segui la guia del Tp0 hasta el final pero no me quedo claro como ejecutar la parte de server y el cliente en la máquina sin interfaz gráfica. Uso el comando make en la carpeta, pero luego intento utilizar el comando gcc -o para crear el ejecutable y me tira errores en los comandos del log y la config. Supongo que habrá otro método para ejecutar los programas.

**Comment by iago64** [comment]
Buenas! Cómo va?

El comando `make` lo que hace es compilarte el programa.
Despues para correrlo vas a tener que hacer `./<NOMBRE DEL PROGRAMA> `, que es lo mismo que si lo corrieras en la terminal de la VM con entorno gráfico. Si queres un poco mas de info de como usar bash (entorno de linea de comandos, te recomiendo que sigas la [Guia de uso de Bash](https://docs.utnso.com.ar/guias/consola/bash).

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Para sumar, te invito a ejecutar `make clean` y, luego, ejecutar `make` de nuevo prestando atención a lo que imprime la consola. Saludos

**Comment by iago64** [comment]
@santiparis Cómo va?

Te sirvió lo que te comentamos con @RaniAgus? Necesitas ayuda con algo mas?

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, ante cualquier consulta pueden reabrirlo o abrir uno nuevo. Saludos
