### ISSUE TITLE
Necesito ayuda para iniciar Ubuntu Server en Virtual Box

### ISSUE THREAD

**Issue by facundo-longin** [sisoputnfrba/foro#3437]
![SharedScreenshot](https://github.com/sisoputnfrba/foro/assets/113182808/53f97729-6ebd-47f6-88e1-49493434fef8)
Me sale login luego de iniciar la VM, tengo entendido que hay que poner "utnso", pero luego me pide Password y no me deja escribir. No puedo salir de ahí y solo me deja cerrar la maquina

**Comment by RaniAgus** [comment]
¡Buenas! Por las dudas debo preguntar: ¿probaste escribiendo "utnso" a ciegas? Normalmente cuando la consola te pide ingresar contraseña no te aparecen los "*". Saludos

**Comment by facundo-longin** [comment]
Me funcionó! pero me muestra esto y no se que hacer
![SharedScreenshot2](https://github.com/sisoputnfrba/foro/assets/113182808/ebe2d989-1013-4c95-8516-474c9da71281)

**Comment by iago64** [comment]
Buenas! Cómo va?

Esa VM que levantaste es la VM de pruebas y justamente no tiene entorno gráfico, toda la interacción es mediante comandos de consola, como los que podes encontrar en la [Guía de uso de Bash](https://docs.utnso.com.ar/guias/consola/bash), igual si queres una VM para desarrollar el TP tienen que utilizar la de Xubuntu que tiene interfaz gráfica y se parece mucho mas a un windows.

Saludos.-

**Comment by RaniAgus** [comment]
¡Es una terminal! Ahí es donde van a desplegar el TP. También podrías usarla para desarrollarlo, pero probablemente te convenga descargar la versión gráfica siguiendo el tutorial de [conseguir un entorno Linux](https://docs.utnso.com.ar/primeros-pasos/entorno-linux)

Luego, lo recomendable es seguir avanzando por todas las guías de primeros pasos hasta llegar al TP0. Spoiler: Ahí vas a poder practicar un despliegue en la VM server.

Saludos

**Comment by iago64** [comment]
Buenas! Si la duda fue resuelta, no te olvides de cerrar el issue 👮‍♂️
