### ISSUE TITLE
CPU: envio y recepción de solicitudes

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3438]
Buenas tardes, tenemos dudas con respecto a la CPU que por un lado debe actuar de "servidor" del kernel, recibir sus solicitudes, y, por otro lado, ser "cliente" de la memoria, ósea poder enviarle solicitudes.
1) A la hora de ver la guía de sockets, vemos un while(1) que lo que hace es estar en escucha constantemente y crear hilos de acuerdo a las conexiones que reciba para luego manejarlas en una función "(void*) atender_cliente". Como haría, por ejemplo, la CPU, que no es solo servidor, no solo debe recibir solicitudes del kernel, sino que también debe poder ser capaz de enviar solicitudes a la memoria al mismo tiempo. En un momento pensamos en realizar la conexión hacia la memoria antes de entrar al bucle while pero nos parece que eso, de igual forma, no va funcionar.
2)La CPU realmente necesita estar en escucha constante? O cuando se le conecte el kernel ya no sería necesario y por lo tanto el bucle while(1) tampoco tendría mucho sentido?

**Comment by iago64** [comment]
Buenas! Cómo va?

Muy buena pregunta y la respuesta rapida es, una vez que tienen establecidas las conexiones con Kernel y Memoria, pueden "olvidarse" de la parte de crear conexiones, pero lo que si van a tener que empezar a trabajar en base a los mensajes que les lleguen.

Un consejo, pueden ir leyendo el enunciado y diagramar en papel que cosas va haciendo la CPU, por ej, les dejo los primeros pasos:
1.- Conectarse a Memoria como cliente
2.- Aceptar las conexiones del Kernel como Server
3.- Esperar que el server nos mande un Contexto de ejecución

Del 4 en adelante se los dejo a uds 😊 

Saludos.-

**Comment by rood8592** [comment]
Muchas gracias! Y me surgio otra duda, con respecto a la escucha constante, para las interfaces I/O si necesitaremos obligatoriamente que el kernel este escuchando siempre, no? Ya que realmente no se cuantas interfaces se me van a conectar. No es como la cpu que se le conecta el kernel unicamente y listo.

**Comment by iago64** [comment]
Buenas! Cómo va?

Si, el Kernel siempre tiene que estar escuchando nuevas conexiones de Interfaces de I/O

Saludos.-
