### ISSUE TITLE
Problema conexion modulo I/O

### ISSUE THREAD

**Issue by GregorioOndjian** [sisoputnfrba/foro#3439]
Lo que hicimos fue crear un hilo en kernel y memoria para que todo el tiempo esten escuchando. Como primer avance estamos intentando conectar una unica interfaz para luego ir escalandola (como nos aconsejaron). El tema es que nos da "segmentation fault".

### 📝 Código relevante

Esta es la parte del kernel
```
void levantar_conexiones(){
    conexion_memoria= conectar_a_servidor(config.ip_memoria,config.puerto_memoria);
    conexion_cpu_dispatch =conectar_a_servidor(config.ip_cpu,config.puerto_cpu_dispatch);
    conexion_cpu_interrupt = conectar_a_servidor(config.ip_cpu,config.puerto_cpu_interrupt);
    pthread_create(&hilo_conexiones_entradasalida, NULL, (void*)conexiones_entradasalida,NULL );
	pthread_detach(hilo_conexiones_entradasalida);  
}
void conexiones_entradasalida(){
    log_info(logger,"Entre al hilo de io");
    int socket_entrada_salida = iniciar_servidor(config.ip_kernel,config.puerto_escucha);
    while(1);
}

```
Esta es la parte de la memoria
```
void levantar_conexiones(){
	socket_escucha = iniciar_servidor(config.ip_memoria,config.puerto_escucha);
	conexion_cpu = esperar_cliente(socket_escucha);
	pthread_create(&hilo_conexiones_entradasalida, NULL, (void*)conexiones_entradasalida,NULL );
	pthread_detach(hilo_conexiones_entradasalida);  
	conexion_kernel = esperar_cliente(socket_escucha);
}
void conexiones_entradasalida(){
    while(1){
        int conexion_entradasalida = esperar_cliente(socket_escucha);
      
    }
}
```
y esto es lo que hicimos en el modulo de I/O

```
int main(int argc, char* argv[]) {
    t_config* entradasalida_config_file = iniciar_config();
    levantarconfig(entradasalida_config_file);
	levantar_conexiones();
    decir_hola("una Interfaz de Entrada/Salida");
	while(1);
    return 0;
}

void levantar_conexiones(){
  	conexion_memoria = conectar_a_servidor(config.ip_memoria,config.puerto_memoria);
  	conexion_kernel = conectar_a_servidor(config.ip_kernel,config.puerto_kernel);
}
```
y esto es lo que nos tira cuando ejecutamos 
![image](https://github.com/sisoputnfrba/foro/assets/82954160/7efd5492-7ef9-4452-a6f0-71e0a63d6b32)

### 🐛 Cómo reproducir el error

Para ejecutarlo primero iniciamos memoria, cpu, kernel y por ultimo I/O

**Comment by iago64** [comment]
Buenas! Cómo va?

Lo que te está tirando ahi el segment fault es una función de las commons? Por esas casualidades al debuguear, se fijaron que le está llegando a esa función? Por ej, que valor tiene la variable logger?

Saludos.-

**Comment by iago64** [comment]
@GregorioOndjian Cómo va?

Pudiste ver las consultas que te deje en la respuesta anterior?

Saludos.-

**Comment by GregorioOndjian** [comment]
Buenass, no lo pude ver, hoy a la noche lo miro. No se si se puede dejar abierto un toq mas, sino no pasa nada. Un saludo

**Comment by iago64** [comment]
Si tranqui, el issue puede quedar, fue solamente un mensaje para hacer seguimiento para saber si estaba resuelto.

**Comment by GregorioOndjian** [comment]
Buenass, ahi finalemente nos dimos cuenta que no habiamos iniciado el logger. Muchas graciass.
