### ISSUE TITLE
Consulta, que consola se esta utilizando?

### ISSUE THREAD

**Issue by FrancoGegon** [sisoputnfrba/foro#3440]
Yo estoy usando Git bash pero cuando escribo make debug y make install me salta que make: command not found y el siguiente codigo que debo copiar para crear el directorio (el que comienza diciendo mkdir) me salta estos tres errores:
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

queria saber cual es el error o si quizas me estoy equivocando de consola en donde poner alguna de estas cosas, gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

El TP lo tienen que hacer en linux.
Te recomiendo que te pases por la [Guia de Primeros Pasos](https://docs.utnso.com.ar/primeros-pasos/) y que no te quedes en la primer parte de inscribirte, si no que ademas leas la parte de [Normas del Trabajo Practico](https://docs.utnso.com.ar/primeros-pasos/normas-tp) que en parte igual mañana en la charla algo bastante de eso vamos a charlar y ya que venís siguiendo las opciones del menú, leete con tiempo el documento importante que es el de [Conseguir un entorno Linux](https://docs.utnso.com.ar/primeros-pasos/entorno-linux) ya que es fundamental para el TP.

Saludos.-

**Comment by iago64** [comment]
@FrancoGegon Cómo va?

Pudiste avanzar con una VM en Linux?

Saludos.-

**Comment by FrancoGegon** [comment]
Hola, gracias por la ayuda, al final el tema era escribir esos comandos adentro de la VM y no en la consola de mi computadora local, algo que no quedaba del todo claro en el texto. Ya pude resolverlo, ahora cierro el issue, muchas gracias
