### ISSUE TITLE
Error al iniciar la VM

### ISSUE THREAD

**Issue by Vibello** [sisoputnfrba/foro#3442]
Hola buenas! Al querer iniciar la VM, me salta el siguiente error: 
"**Failed to open image 'E:\Program Files\Oracle\MV\Grafica.vdi' for writing due to wrong permissions (VERR_VD_IMAGE_READ_ONLY).
AHCI: Failed to attach drive to Port0 (VERR_VD_IMAGE_READ_ONLY).**"
Este mismo error lo pude solucionar el día anterior, desinstalando todo y volviendo a instalar, pero esta mañana volvió el problema y ya no puedo entrar para continuar el tp. Ya modifiqué los permisos del archivo Grafica.vdi, autorizando todos los permisos que tiene, y lo mismo con el archivo Grafica.zip.002 .
![screen1](https://github.com/sisoputnfrba/foro/assets/165044802/161a12fe-5b38-4a03-bf68-391c22e340fb)
![screen2](https://github.com/sisoputnfrba/foro/assets/165044802/345ff51a-9402-4ccc-84fa-a2e0e2edfc36)

Gracias de antemano!

**Comment by RaniAgus** [comment]
¡Buenas! Yo probaría de borrar la VM y todos los archivos y repetir el proceso de instalación pero guardando el `Grafica.vdi` en una carpeta de usuario como "Mis Documentos" o "Descargas", ya que quizás el hecho de que esté guardado en "Archivos de Programa" esté causando problemas. 

En cuanto a los archivos `Grafica.zip.001` y `Grafica.zip.002`, es irrelevante lo que hagan con ellos ya que una vez se descomprimió el `Grafica.vdi` ya éste contiene todo lo necesario para iniciar la VM. De hecho, podés aprovecharlos para omitir el paso de la descarga y descomprimirlo en otra carpeta :)

Saludos

**Comment by TomasAArin** [comment]
Buenas, a mi me paso lo mismo, para que quede mas lindo la carpeta de Sistemas Operativos que esta en mi Escritorio, lo que tenes que hacer es poner la Grafica como tambien por las dudas la Grafiza.zip y Grafiza.zip.002 en donde estaba antes de moverlas.
Espero que se haya entendido lo que puse y que lo puedas solucionar.
Saludos

**Comment by iago64** [comment]
@Vibello Te sirvieron las respuestas que te pasaron? Necesitas ayuda con algo mas para iniciar la VM?

Saludos.-

**Comment by Vibello** [comment]
Muchas gracias! Ya lo pude resolver. Además de cambiar de lugar los archivos, tuve que cambiar cada uno de los permisos para que arrancara.
