### ISSUE TITLE
Duda con tipo de datos en el config de I/O

### ISSUE THREAD

**Issue by nicolasreypc** [sisoputnfrba/foro#3443]
Dentro del config de I/O en el enunciado del TP aparece que la IP_KERNEL es un Numerico, y que el PUERTO_KERNEL es un string, esto no deberia ser al reves? (siguiendo las estructuras de los modulos anteriores)

![image](https://github.com/sisoputnfrba/foro/assets/143523417/157a164e-39fa-4bcc-ac94-a6b93dbcc9f4)

**Comment by RaniAgus** [comment]
¡Buenas! Es correcto, ya lo corregimos, gracias por notarlo :)

**Comment by iago64** [comment]
Ya se encuentra corregido en el enunciado.
