### ISSUE TITLE
Error a la hora de abrir la maquina virtual

### ISSUE THREAD

**Issue by sofiimoguilner** [sisoputnfrba/foro#3444]
Hola, que tal?

![Screenshot 2024-04-06 16 06 21](https://github.com/sisoputnfrba/foro/assets/165674606/7711958f-a83c-45a3-8d75-386c8683365a)

Tuve unos problemas a la hora de descomprimir los archivos y una vez que lo pude hacer trate de generar la maquina virtual pero me salta esto y no pude resolverlo. Me meti a buscar y encontre el siguiente link https://askubuntu.com/questions/41118/virtualbox-kernel-driver-not-installed 
pero una vez que hago lo que me dice en la terminal tambien me parece un error y no se como solucionarlo
![Screenshot 2024-04-06 16 46 10](https://github.com/sisoputnfrba/foro/assets/165674606/89d486e6-6f2b-4a33-8a4e-fc708acded6e)
 
-->

**Comment by RaniAgus** [comment]
¡Buenas! Antes de continuar, para más contexto: ¿cuál es tu distribución de Linux y cómo instalaste VirtualBox? Me suena a que muy probablemente hayas usado un método que te instala el paquete sin sus dependencias. Saludos

**Comment by sofiimoguilner** [comment]
Hola!
Estoy usando chromeOS, que contiene Debian 12.5  e instale virtualbox mediante la terminal.

**Comment by MarcoIoannisci** [comment]
Hola, probaste activar la vsm? A mi me tiraba un error similar y se soluciono con eso.
![image](https://github.com/sisoputnfrba/foro/assets/63261451/3b8269e5-9162-4f42-ae6a-aa5f0679d510)

**Comment by sofiimoguilner** [comment]
te referis a la memoria virtual compartida?

**Comment by RaniAgus** [comment]
@MarcoIoannisci gracias por sumarte! Igual creo que tu error es diferente ya que el código de error es `VERR_NEM_NOT_AVAILABLE` y el de @sofiimoguilner es `VERR_VM_DRIVER_NOT_INSTALLED`

@sofiimoguilner, ¿podrías volver a intentar instalar VirtualBox desde la consola y mostrarnos tanto el comando que usaste como el output que imprime?

Saludos

**Comment by sofiimoguilner** [comment]
Ahi lo pude descargar desde el link propuesto, use Debian 12 y ahora me sale esto
![Screenshot 2024-04-06 19 38 42](https://github.com/sisoputnfrba/foro/assets/165674606/391138f1-7e5a-4f04-85cc-d487826f64b1)

**Comment by iago64** [comment]
Buenas! Cómo va?

Es posible que no este pudiendo abrir el viejo archivo de definición de la maquina virtual, podrías probar de eliminarla y volver a crearla?

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @sofiimoguilner! ¿Pudiste probar lo que te sugirió Dami? Saludos

**Comment by sofiimoguilner** [comment]
hola que tal! perdon que aparezca recien pero no lo segui. Hoy me puse y me aparecio el mismo problema. 
![Screenshot 2024-04-09 16 39 40](https://github.com/sisoputnfrba/foro/assets/165674606/c204fdda-6122-4d62-b8ea-8c4b31506113)
Buscando parece que ChromeBook le faltan un par de modulos y no va a ser compatible. Lei que puedo descargar QEMU

**Comment by iago64** [comment]
Buenas!

Para la parte de QEMU, podes ver un poco la parte de la [guía de no usar virtual box](https://docs.utnso.com.ar/primeros-pasos/entorno-linux#sin-usar-virtualbox), es bastante experimental ya que lo estamos usando para Macs con ARM pero puede servirte como una base para hacer alguna prueba.

Saludos.-

**Comment by sofiimoguilner** [comment]
Hola!

Buenisimo muchas gracias!

**Comment by iago64** [comment]
> Hola!
> 
> Buenisimo muchas gracias!

Por favor avisanos si la solución te sirve y que tal te resulta si funciona asi lo tenemos en cuenta para próximos casos 😊 

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @sofiimoguilner! Si te surge algún problema al seguir la guía no dudes en venir a sábado de soporte mañana temprano, ya sea por Discord o presencial en Campus (quizás sea más conveniente presencial así lo vemos con la máquina ahí mismo) Saludos

**Comment by karengrams** [comment]
¡Buenas @sofiimoguilner!

Veo que este issue se resolvio en #3491 asi que vamos a cerrar este vicunlandolo con el otro.

¡Saludos!

Kar.-
