### ISSUE TITLE
type name is not allowed C/C++ (254)

### ISSUE THREAD

**Issue by NahuRodas** [sisoputnfrba/foro#3445]
Buenas, tengo un problema con el TP0 justo al inicio que no me deja empezar, VS me tira el error **"type name is not allowed C/C++ (254)"** en `t_log logger`

![image](https://github.com/sisoputnfrba/tp0/assets/99214538/e42f168a-1571-417c-b57c-a91df8dc508b)

Y al intentar hacer el debbug me tira el siguiente error por consola 

![image](https://github.com/sisoputnfrba/tp0/assets/99214538/f7d4dadc-9ef6-4444-9853-2163b26d0c3f)

**Comment by RaniAgus** [comment]
PD: Ahí transferí el issue al repo del foro, que es donde recibimos las consultas :)

**Comment by iago64** [comment]
@NahuRodas Cómo va?

Pudiste ver lo que te comento @RaniAgus?

Saludos.-

**Comment by NahuRodas** [comment]
@iago64 sisi era eso
