### ISSUE TITLE
Fallas entre conexiones modulos

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3447]
Buenas tardes, estamos haciendo lo de las conexiones entre los distintos modulos y nos surgió la duda de si es necesario manejar el tema de errores cuando uno de ellos, por ejemplo, la memoria no levantó su "servidor" correctamente. 
Hasta ahora logramos levantar memoria, cpu y el kernel se conecta correctamente a ellos cuando ambos están corriendo. Pero a la hora de que uno no funcione correctamente, el kernel hace un exit y se termina el programa en su totalidad. Pensamos que no tendría sentido manejar este tipo de errores ya que a la hora de presentar el tp sino se conectan todos los modulos correctamente no se lo podrá probar de todas formas.

**Comment by RaniAgus** [comment]
¡Buenas! Técnicamente imprimir un mensaje informando del error y finalizar el programa ya es de por sí una estrategia muy válida de manejo de errores. No manejarlo sería dejar que siga ejecutando, lo cual sí sería incorrecto.

Me parece bien finalizar el programa ante un fallo de ese estilo, ya que como bien dicen probablemente se deba a un problema de configuración o un fallo temporal que, de ocurrir, no se preocupen, vamos a pedirles repetir la prueba :)

Saludos

**Comment by rood8592** [comment]
Muchas gracias!
