### ISSUE TITLE
Error al crear mi primer proyecto C

### ISSUE THREAD

**Issue by marianonahuelbruno** [sisoputnfrba/foro#3448]
Hola estoy trabado en crear el primer proyecto C. Estoy con el visual Studio code. Ya descargue e instale las so-commons-library y descargue el repositorio para correr el programa de ejemplo con el comando (antes creando una nueva carpeta para instalarlo) wget -qO- https://faq.utnso.com.ar/project.tar.gz | tar -xzvf - --strip-components 1 pero al intentar ejecutar me aparece este error. estuve viendo varias cosas como el horario de la maquina virtual pero no puede encontrar el error aun. Muchas gracias

![Captura de pantalla 2024-04-06 193754](https://github.com/sisoputnfrba/so-commons-library/assets/164648424/e7225253-181c-41c1-943a-9bf65d259d3b)

**Comment by RaniAgus** [comment]
Buenas, porfa la próxima vez subí la duda a este repo al que transferí al issue. Saludos
