### ISSUE TITLE
No me llegan los paquetes desde el cliente al server ni desde la consola, ni desde la terminal

### ISSUE THREAD

**Issue by ahuarca** [sisoputnfrba/foro#3449]
Hola!!  Cuando ejecuto el cliente seguiendo lo que recomenda en la guía de rutas, no me llagan los mensajes al servidor, lo mismo me ocurre en la consola de visual
![Captura de pantalla (89)](https://github.com/sisoputnfrba/foro/assets/163689778/a5c9753b-3089-4a5e-b7db-5c0a647a5abb)
![Captura de pantalla (90)](https://github.com/sisoputnfrba/foro/assets/163689778/fac11c40-d637-4eea-a435-cfc75ba38fb8)

Ya le puse mensajes de error a cada función que se especifica en al guía de sockets y no me salta nada

En en los utils.c del cliente:

```c
int errorgetclient =getaddrinfo(ip, puerto, &hints, &server_info);

	if(errorgetclient != 0){
			printf("Error en la getaddrinfo del cliente: %s", gai_strerror(errorgetclient));
			exit(-1);
		}

int errorconnect = connect(socket_cliente, server_info->ai_addr, server_info->ai_addrlen);

		if( errorconnect!= 0){
			printf("se produjo un error en la connect del cliente ");
		}
```

En los utils.c del server también:

```c
int errorgetservec= getaddrinfo(NULL, PUERTO, &hints, &servinfo);
		if(errorgetservec != 0){
			printf("Error en la getaddrinfo del server : %s", gai_strerror(errorgetservec));
			exit(-1);


	int errorbind = bind(socket_servidor,servinfo->ai_addr, servinfo->ai_addrlen);
		 if(errorbind== -1){
			printf("error en la bind del server %s", gai_strerror(errorbind));
			exit(-1);
		 }


	int errorlisten=listen(socket_servidor, SOMAXCONN);
	if(errorbind== -1){
			printf("error en el lsiten del server %s", gai_strerror(errorlisten));
			exit(-7);
		 }
```

Pero aún asi no me salta ningún error

**Comment by iago64** [comment]
Buenas! Cómo va?

En el código que dejaste lo único que esta es el código de la generación de la conexión, hasta ahi parece que vas bien, ahora, podrías pasar el código que tenes para enviar y recibir los mensajes?

Saludos.-

**Comment by ahuarca** [comment]
Hola! dale ahi te lo paso:


en las uitls.c del cliente: 
void enviar_mensaje(char* mensaje, int socket_cliente)
{
	t_paquete* paquete = malloc(sizeof(t_paquete));

	paquete->codigo_operacion = MENSAJE;
	paquete->buffer = malloc(sizeof(t_buffer));
	paquete->buffer->size = strlen(mensaje) + 1;
	paquete->buffer->stream = malloc(paquete->buffer->size);
	memcpy(paquete->buffer->stream, mensaje, paquete->buffer->size);

	int bytes = paquete->buffer->size + 2*sizeof(int);

	void* a_enviar = serializar_paquete(paquete, bytes);


	send(socket_cliente, a_enviar, bytes, 0);

	free(a_enviar);
	eliminar_paquete(paquete);
}


En el send me salta este error cuando ejecuto solo al cliente en la consola , después del espacio en blanco se queda como colgando, no lo imprime y  no termina el programa
![Captura de pantalla (95)](https://github.com/sisoputnfrba/foro/assets/163689778/8d51df9b-4fb2-42da-a173-fe3f01bd19e3)

en la consola de Debug me sale esto:

reakpoint 1, main () at src/client.c:17
17		logger = iniciar_logger();
Loaded '/lib/libcommons.so'. Symbols loaded.
Loaded '/lib/x86_64-linux-gnu/libreadline.so.8'. Symbols loaded.
Loaded '/lib/x86_64-linux-gnu/libc.so.6'. Symbols loaded.
Loaded '/lib/x86_64-linux-gnu/libtinfo.so.6'. Symbols loaded.

Program received signal SIGPIPE, Broken pipe.
0x00007ffff7e4b8b0 in __libc_send (fd=4, buf=0x555555573890, len=14, flags=0) at ../sysdeps/unix/sysv/linux/send.c:28

en el utils. c del server:

void recibir_mensaje(int socket_cliente)
{
	int size;
	char* buffer = recibir_buffer(&size, socket_cliente);
	log_info(logger, "Me llego el mensaje %s", buffer);
	free(buffer);
}

**Comment by iago64** [comment]
Buenas! Cómo va?

El error de broken pipe, es uno de los más comunes que se suelen dar porque del otro lado te cortaron la conexión, esto puede ser por ejemplo porque el otro proceso terminó y entonces te enteras de esto al momento de querer enviarle algo, el server al momento de que te tiró broken pipe, estaba corriendo?

Saludos.-

**Comment by ahuarca** [comment]
Hola!! Ahí corrí el server antes y me dejo de aparecer el   error de broken pipe en el cliente jajja, es que antes no me aparecía ese error (cuando solo corría el cliente en vsc).}
 
Pero siguen sin llegarme los mensajes al server

![Captura de pantalla (98)](https://github.com/sisoputnfrba/foro/assets/163689778/7e268a5d-d59d-45a2-8e7e-dc1c7222a114)

**Comment by iago64** [comment]
Buenas!

Bien, avanzamos un paso, ahora tenes el cliente conectado al servidor, ahora, sería un buen momento para que debuguees el servidor a ver que te está llegando cuando sale de la función `recv()`, ya que es recontra posible que lo que te esta faltando es desempaquetar lo que recibís.

Saludos.-

**Comment by FredeHG** [comment]
Hola, pudiste revisar lo que te comento Dami? Algo más en lo que te podamos ayudar referido al issue o podemos ir cerrando el issue?

**Comment by ahuarca** [comment]
hola! ahi lo pruebo, lo que pasa es que estuve enferma, pero ahí  subo lo que me tira el debuggin

**Comment by ahuarca** [comment]
Holaa!

Acá debugee tres lineas en total con la función recv(), para ver las variables:

El recv () que esta dentro de recibir operación

![Captura de pantalla (101)](https://github.com/sisoputnfrba/foro/assets/163689778/492fad15-6dda-4236-8560-1ee682c88880)

Del recv() dentro  de recibir_buffer()

![Captura de pantalla (102)](https://github.com/sisoputnfrba/foro/assets/163689778/8d0bfbb2-31cd-4af1-b8de-9f85f78aeaaa)


del otro recv() dentro de recibir_buffer()
![Captura de pantalla (106)](https://github.com/sisoputnfrba/foro/assets/163689778/fefe8145-e26b-4370-b695-31e6c466ea03)

Por las dudas dejo mi repo por acá, por si lo quieren ver: https://github.com/ahuarca/TP_0.git

**Comment by RaniAgus** [comment]
¡Buenas! No nos sirve de mucho saber las direcciones de memoria que muestra el debugger, sí nos serviría saber el contenido de los streams que se envían de un lado y se reciben del otro.

Esto se puede hacer en VSCode haciendo click en el inspector de memoria (justo en otro issue le comentaba a un compañero cómo pueden hacerlo: https://github.com/sisoputnfrba/foro/issues/3459#issuecomment-2043302751)

O sea, luego que se envíe el valor de la clave que está en el config, probá de ingresar varios valores y revisemos que se estén enviando y recibiendo bien.

Saludos

**Comment by RaniAgus** [comment]
¡Buenas @ahuarca! ¿Pudiste probar de nuevo inspeccionando la memoria? Saludos

**Comment by ahuarca** [comment]
Holaa, sisi

Envie estos mensajes
![Captura de pantalla (112)](https://github.com/sisoputnfrba/foro/assets/163689778/fbde2320-555e-4baf-9624-a6ba4901dc5a)

y luego me pare en la funcion enviar_paquete del cliente

![Captura de pantalla (118)](https://github.com/sisoputnfrba/foro/assets/163689778/b2c38daf-1fba-4bb5-8e93-2fe36020a480)

y en las variables de memoria me aparece esto:

![Captura de pantalla (120)](https://github.com/sisoputnfrba/foro/assets/163689778/ac1fa5fa-0099-48e6-920d-597086d434bf)


![image](https://github.com/sisoputnfrba/foro/assets/163689778/84358e93-df32-4b77-9716-01f788bcc9e8)

despues me pare en la funcion recibir_paquete() del servidor y en sus variables no me figuran los mensajitos

![image](https://github.com/sisoputnfrba/foro/assets/163689778/076a866d-8fd9-4ee4-afaa-21e69a5c018a)

![image](https://github.com/sisoputnfrba/foro/assets/163689778/062e8a58-9f31-4764-8580-d5ab9ad9e50a)

**Comment by RaniAgus** [comment]
Algo importante a tener en cuenta sobre los breakpoints es que frenan la ejecución _antes_ de ejecutar la línea, no después. Es por esto que, por ejemplo, en `recibir_paquete()` la variable `bytes` tiene un valor basura, porque todavía no se recibió el buffer.

Para no hacerla larga, solo mostrarnos 3 cosas:

1) Las líneas que ingresaste del lado del cliente
2) Lo que te devuelve el inspector al inspeccionar `a_enviar` en la línea del `send()` (lo que nos pasaste es la dirección de memoria 0x8, que no existe)
3) Lo que te devuelve el inspector al inspeccionar `buffer` en el `while(desplazamiento < size)`

También me llama la atención que el tamaño de `a_enviar` sea 8 (4 para el opcode y 4 para el buffer), ¿estás ingresando valores o estás mandando un buffer vacío?

Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

Creo que es mucho muy importante que recuerde que tenemos una [Guía de Debugging](https://docs.utnso.com.ar/guias/herramientas/debugger) que si bien esta armada con capturas de Eclipse, los conceptos que tiene aplican de igual manera a VSCode.

Saludos.-

**Comment by ahuarca** [comment]
Holaaa, envie estos valores

![image](https://github.com/sisoputnfrba/foro/assets/163689778/69303ec7-66df-4333-9dc7-7b63931c2778)

Cuando debuggee en send() en la variable a_enviar me aparece esto:

![image](https://github.com/sisoputnfrba/foro/assets/163689778/32cf641f-d90e-4ce2-b5a5-c63210c80538)

![image](https://github.com/sisoputnfrba/foro/assets/163689778/5e7f3b2f-7df8-4d99-8e17-dfd904257148)

![image](https://github.com/sisoputnfrba/foro/assets/163689778/75de35f0-85c0-47b9-be87-fc645afce911)

y  cuando debuggeo en la linea del while me aparece esto en la variable buffer ( solo el mensaje de que recibió el valor de la clave, pero no me aparce nada con respecto a los mensajes)

![Captura de pantalla (139)](https://github.com/sisoputnfrba/foro/assets/163689778/5951b741-6985-4671-bd88-ec2f50e0b53b)

**Comment by RaniAgus** [comment]
¡Buenas! Si prestás atención a la primera captura de pantalla vas a ver que no estás enviando ningún valor: en lugar de eso veo que presionaste dos veces "enter" (la primera, para salir del ciclo readline-log_info; y la segunda para salir del ciclo readline-agregar_a_paquete).

De hecho podés poner un breakpoint en el log_info y otro en agregar_a_paquete, y verás que el primero se ejecuta varias veces pero el segundo nunca lo hace.

Entonces, el problema que veo es que se está enviando un paquete con código de operación 1 y tamaño de buffer 0 (o sea, un stream de 8 bytes en total).

Una vez más te invitamos a ver la guía de debugging que pasó Dami y a leer e interpretar lo que dice el inspector de memoria, ya que va a ser muy útil para entender qué se está ejecutando en cada línea del TP y encontrar y corregir errores más rápido.

Saludos

**Comment by iago64** [comment]
Buenas @ahuarca Te sirvió la respuesta de @RaniAgus?

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, ante cualquier consulta pueden reabrirlo o abrir uno nuevo. Saludos
