### ISSUE TITLE
Se traba la VM

### ISSUE THREAD

**Issue by c4shew** [sisoputnfrba/foro#3451]
Hola! Yo me baje la máquina virtual en un disco externo por un tema de falta de espacio, pude configurar todo e iniciar sesión sin problemas, ahora luego de iniciar sesión se traba, es decir que deja de responder y no puedo hacer ninguna acción. Lo máximo que pude hacer fue abrir la terminar y escribir un comando.

No encontré ningún issue relacionado pero hablando con amigas y compañeros de grupo me sugirieron que tal vez la máquina no tiene suficiente memoria.

### 📦 Especificaciones de la VM
- Versión de VirtualBox: Oracle VM VirtualBox Manager 7.0.14
- Memoria RAM asignada: 2 GB

### 🖥️ Especificaciones del host
- Sistema Operativo y versión: MacOS 10.15.5
- Memoria RAM: 4 gb
- Procesador: 1,6 GHz Intel Core i5 de dos núcleos

### 💻 Logs
No obtuve ningún error simplemente se queda trabada

**Comment by c4shew** [comment]
<!--
Hola! Yo me baje la máquina virtual en un disco externo por un tema de falta de espacio, pude configurar todo e iniciar sesión sin problemas, ahora luego de iniciar sesión se traba, es decir que deja de responder y no puedo hacer ninguna acción. Lo máximo que pude hacer fue abrir la terminar y escribir un comando.

No encontré ningún issue relacionado pero hablando con amigas y compañeros de grupo me sugirieron que tal vez la máquina no tiene suficiente memoria.

### 📦 Especificaciones de la VM
- Versión de VirtualBox: Oracle VM VirtualBox Manager 7.0.14
- Memoria RAM asignada: 2 GB


### 🖥️ Especificaciones del host
- Sistema Operativo y versión: MacOS 10.15.5
- Memoria RAM: 4 gb
- Procesador: 1,6 GHz Intel Core i5 de dos núcleos


### 💻 Logs
No obtuve ningún error simplemente se queda trabada

**Comment by iago64** [comment]
Buenas! Cómo va?

Un dato interesante es que todo lo que queda despues de la secuencia `<!--` github no te lo muestra en el issue, por eso te edite el primer comment.

Respecto a lo de que se traba, a que te referis? Anda lento o directamente se congela y al rato vuelve a arrancar?
La memoria está un toque justo, porque si tenes 4gb de ram máximo le vas a poder asignar entre 1.5 y 2gb a la VM, te va a andar, pero no en los parámetros más óptimos.

Por las dudas, podrías dejarnos una captura de las configuraciones de la VM?

Saludos.-

**Comment by c4shew** [comment]
Si se congela y no vuelve a arrancar a menos que la cierre y la vuelva a iniciar. De todos modos cuando la vuelvo a inciar anda un poquito y se congela de nuevo.

Adjunto captura de la configuraciones que me parece que son más relevantes: 

![Captura de Pantalla 2024-04-08 a la(s) 09 45 10](https://github.com/sisoputnfrba/foro/assets/88902514/7e928ff1-7f77-4565-895a-84c5b9ebfef5)
![Captura de Pantalla 2024-04-08 a la(s) 09 44 36](https://github.com/sisoputnfrba/foro/assets/88902514/09a11120-f533-4cc1-9cf9-98ea5373d98d)
![Captura de Pantalla 2024-04-08 a la(s) 09 44 11](https://github.com/sisoputnfrba/foro/assets/88902514/8f9a6f1b-7f34-4e19-bcab-d89d86822cb0)
![Captura de Pantalla 2024-04-08 a la(s) 09 43 48](https://github.com/sisoputnfrba/foro/assets/88902514/d4ed9ae4-3dc1-4b9d-86bb-b2ba26ede5d6)
![Captura de Pantalla 2024-04-08 a la(s) 09 43 27](https://github.com/sisoputnfrba/foro/assets/88902514/8f7f84fc-c83b-4fdf-9ff3-e40862f405b6)

**Comment by iago64** [comment]
Buenas!

El problema que estas teniendo es que la VM esta medio jugada de recursos, si bien con 2gb de ram puede llegar a andar, va a estar bastante justa si levantas más cosas que un VSCode.

Una alternativa que podés usar que si bien no es la "más elegante" es la que mejor te puede llegar a funcionar es la que tenemos planteada para la gente con Macs con M1 donde levantar la VM con interfaz gráfica es bastante molesto y lo que pueden hacer es [Codear desde la VM Server](https://docs.utnso.com.ar/guias/herramientas/macos-arm#%C2%BFy-como-codeo-desde-la-vm-server) usando el Remote Development del VSCode.

Reitero, no es lo más elegante, pero lo bueno de la VM server es que con 512Mb ya levanta y con 1GB ya estas más que sobrada porque de hecho es con lo que nosotros las levantamos en el labo para correr las pruebas.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @c4shew! ¿Pudiste probar de conectarte remotamente a la VM Server desde VSCode como sugirió Dami? Saludos

**Comment by karengrams** [comment]
¡Aló @c4shew! 

¿Cómo va? Cerramos el issue dado a inactividad. De todas formas, _vale aclarar_, si la duda no fue resuelta, te invitamos acercarte a cualquier sábado de soporte para poder resolverla o re-abrir el issue. 

¡Saludos!

Kar.
