### ISSUE TITLE
Escritura invisible en etapa "Leer de consola"

### ISSUE THREAD

**Issue by sdelperciorodriguez** [sisoputnfrba/foro#3453]
Buenas, estoy teniendo un problema en la etapa 2 del TP0, en la sección "Leer de consola".

El problema está en que luego de correr el programa, a veces puedo ver lo que escribo en la terminal y a veces no. Es decir, cuando escribo luego del ">" por momentos escribo "invisible" (como cuando la consola en linux pide la contraseña y aunque no aparezca lo que escribis, estás escribiendo igual). 

Dejo mi implementación de `leer_consola`

```
void leer_consola(t_log* logger)
{
	char* leido;

	// La primera te la dejo de yapa
	leido = readline("> ");

	while(1){
		
		if(strcmp(leido, "") == 0 ){
			break;
		}
		// El resto, las vamos leyendo y logueando hasta recibir un string vacío
		log_info(logger,leido);

		// ¡No te olvides de liberar las lineas antes de regresar!
		free(leido);
		leido = readline("> ");
	}
	
}
```
Asi se ve la terminal cuando puedo ver lo que escribo:
```
[INFO] 13:24:06:378 TP0/(7018:7018): Hola!, Soy un log
[INFO] 13:24:06:379 TP0/(7018:7018): El valor de la key CLAVE es valor

> ahora puedo ver lo que escribo en consola
[INFO] 13:24:15:838 TP0/(7018:7018): ahora puedo ver lo que escribo en consola
> en este momento funciona
[INFO] 13:24:27:344 TP0/(7018:7018): en este momento funciona
> 
utnso@utnso:~/tp0/client$
```
Asi se ve la terminal cuando no puedo ver lo que escribo:
```
[INFO] 13:28:59:585 TP0/(7609:7609): Hola!, Soy un log
[INFO] 13:28:59:586 TP0/(7609:7609): El valor de la key CLAVE es valor

[INFO] 13:29:07:307 TP0/(7609:7609): aescribo invisible
[INFO] 13:29:16:287 TP0/(7609:7609): nopuedoverloqueescribo
> 
utnso@utnso:~/tp0/client$ 
```
Entre las dos ejecuciones no modifiqué el código.

**Comment by sdelperciorodriguez** [comment]
Me olvidé aclarar que una vez que pasa, se soluciona reiniciando vscode.

**Comment by iago64** [comment]
Buenas! Cómo va?

Una consulta importante, si lo corres desde una terminal directo y no desde VSCode, el problema es el mismo?

Saludos.-

**Comment by sdelperciorodriguez** [comment]
Ahí probé. No me pasa si lo corro desde una terminal directo.

**Comment by iago64** [comment]
Buenas!

Entonces es lo que me temía, VSCode lo que tiene es que a veces no tiene una "terminal" muy amigable, entonces queda medio trancada y se arregla justamente reiniciando, mientras funcione bien desde una terminal, estamos joya, ya que el TP se va a probar via terminal y no en VSCode.

Saludos.-

**Comment by sdelperciorodriguez** [comment]
Ok, gracias!
