### ISSUE TITLE
Por alguna razon no puedo usar el struct ADDRINFO o AI_PASSIVE por ejemplo

### ISSUE THREAD

**Issue by nicolasreypc** [sisoputnfrba/foro#3454]
Pese a tener las librerias y haber copiado las funciones del TO0, no puedo utilizarlos.
![image](https://github.com/sisoputnfrba/foro/assets/143523417/fc83829b-18df-4cf0-9872-dc3489dc0234)
![image](https://github.com/sisoputnfrba/foro/assets/143523417/87cc82d3-627e-42d8-a097-9f7590f83fc2)

**Comment by iago64** [comment]
Buenas! Cómo va?

Regla Número 1: Si tenes un problema de código, por favor copia y pega el código utilizando markdown como se indica en el [README.md del foro](https://github.com/sisoputnfrba/foro) para que los ayudantes podamos hacer un copy/paste del código ya que no somos compiladores humanos.

De todas formas, en lo que mostras, ya a simple vista veo un problema muy grave y es que tenes un include con una ruta absoluta: `/home/utnso/Desktop/.../utils/shared.h` eso es casi una receta para el desastre absoluto y mas si es el TP que compartís con tus compañeros, ya que otro puede haberse clonado el repo en otra ubicación que no sea Desktop y no le va a compilar ni de onda.

Igual para que no sea un juego de suposiciones, que pasa si queres compilar el tp0? Que errores y/o warnings te tira el compilador? Ya que aunque no lo parezca el compilador muchísimas veces te dice donde estas metiendo la pata.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Otro tip para los includes: la estructura que les proveemos está lista para poder escribir la ruta partiendo del `src`, tanto para cada módulo como para el `utils`.

Es por esto que en el repo inicial pueden ver la siguiente línea:
```c
#include <utils/hello.h>
```

Y en la estructura de carpetas de `utils` se encuentran con:

```
.
└── src
    └── utils
        ├── hello.h
        └── hello.c
```

Saludos

**Comment by DanielKesel** [comment]
Hola!, Estoy teniendo el mismo problema. Lo peor es que yo ya había terminado el TP0 y me andaba todo perfecto, al otro día (hoy) prendí las VMs y de la nada tenía ese error y no puedo enteder por qué. Encontré este issue cerrado: https://github.com/sisoputnfrba/foro/issues/2574 De la forma que el chico lo resuelva a mi no me funciona.
Necesito ayuda también.
Gracias!

**Comment by DanielKesel** [comment]
Los errores al compilar son:
[{
	"resource": "/home/utnso/Desktop/DANI/tp0/client/src/utils.c",
	"owner": "C/C++: IntelliSense",
	"code": "3365",
	"severity": 8,
	"message": "incomplete class type \"struct addrinfo\" is not allowed",
	"source": "C/C++",
	"startLineNumber": 28,
	"startColumn": 2,
	"endLineNumber": 28,
	"endColumn": 7
}]
y:
[{
	"resource": "/home/utnso/Desktop/DANI/tp0/client/src/utils.c",
	"owner": "C/C++: IntelliSense",
	"code": "20",
	"severity": 8,
	"message": "identifier \"AI_PASSIVE\" is undefined",
	"source": "C/C++",
	"startLineNumber": 29,
	"startColumn": 19,
	"endLineNumber": 29,
	"endColumn": 29
}]

**Comment by RaniAgus** [comment]
Buenas @DanielKesel, no estoy tan seguro de que sea el mismo problema. ¿Podrías crear un issue y complementar el texto de error con capturas de pantalla para saber dónde te aparece el error? Saludos

**Comment by RaniAgus** [comment]
¡Buenas, @nicolasreypc! ¿Alguna novedad sobre el problema?

**Comment by nicolasreypc** [comment]
Me di cuenta que pese a que en VSCode me aparezca asi, puedo compilar y ejecutar igualmente.

**Comment by RaniAgus** [comment]
¿Es posible que tengas abierta la carpeta del repo en lugar del workspace? La configuración que les proveemos les deshabilita los errores de IntelliSense para que aparezcan solo los errores al compilar.

**Comment by nicolasreypc** [comment]
No se si es a lo que se refiere tu pregunta, pero tengo el repositorio clonado y trabajo por modulos independientes (osea cuando compilo y ejecuto lo hago dentro del modulo CPU x ejemplo), pero al hacer Ctrl+click para ir a los utils me aparece el "error" este, pero funciona todo bien.

**Comment by RaniAgus** [comment]
Al igual que en el TP0, en los repos que les proveemos hay un archivo `tp.code-workspace` que deben usar para importar el TP en VSCode. Si, en lugar de hacer eso, abren directamente la carpeta del repositorio, VSCode no va a cargar ninguna configuración. 

Esto lo podés notar si te movés a la pestaña "Run and Debug" y no te aparece ninguna configuración para ejecutar los módulos, o sea:

![vscode](https://docs.utnso.com.ar/img/primeros-pasos/tp0/vscode-run-debug.gif)

Si no te aparece `run (kernel)`, `run (memoria)`, etc., es porque no abriste el TP desde el archivo workspace.

**Comment by nicolasreypc** [comment]
Muchisimas gracias!!!!, se arreglo y ademas me facilitaste 10 veces la vida ajajaj

**Comment by RaniAgus** [comment]
¡Buenísimo! Una vez resuelta la duda o problema no olviden cerrar el issue :)
