### ISSUE TITLE
Consulta sobre escenarios de devolución de contexto de ejecución.

### ISSUE THREAD

**Issue by Mimito164** [sisoputnfrba/foro#3455]
Buenas. Estuve leyendo el enunciado del TP y me surgion algunas dudas sobre los distintos escenarios en los que el cpu va a devolver un contexto de ejecución. Más específicamente con el siguiente párrafo del enunciado:

> Durante el transcurso de la ejecución de un proceso, se irá actualizando su Contexto de Ejecución, que luego será devuelto al Kernel bajo los siguientes escenarios: finalización del mismo (instrucción EXIT o ante un error), necesitar ser bloqueado, o deber ser desalojado (interrupción).

No me queda bien claro en cuál de estos eventos entran las instrucciones de IO. ¿Seria "necesitar ser bloqueado"? 

Y por otro lado, ¿Cual es la diferencia entre "necesita ser bloqueado" y "debe ser desalojado"? ¿no es el cpu quien desaloja en todo momento  y es el kernel quien define como proceder? 

 "deber ser desalojado" ¿únicamente es cuando hay una interrupción?  

### 💭 Soluciones posibles

Para mi  los motivos de devolución  se deberían clasificar de la siguiente manera:

- Interrupcion: este motivo de devolución queda reservado cuando recibe una interrupción por quantum y cuando se manda la señal de kill desde la consola. 
- Desalojo: Sería cuando un proceso necesita que el kernel le resuelva algo pero no necesariamente va a ser bloqueado, por ejemplo cuando se hace un wait o un signal.
- Bloqueo: en este caso se sabe que el proceso debe ser bloqueado y las instrucciones de io entrarían en esta categoría.

**Comment by Mimito164** [comment]
"El kernel puede recibir de la CPU un Contexto de Ejecución desalojado por WAIT o por SIGNAL"

¿Esto sería un desalojo o una necesidad de ser bloqueado?

**Comment by iago64** [comment]
Buenas!

En el caso de Wait puede ser que el proceso se bloquee, si el recurso no tiene mas instancias disponibles.
Para el caso de signal, simplemente procesarían el signal y deberían enviar de nuevo el proceso a ejecutar a la CPU.

En ambos casos tengan en cuenta que es una representación de una syscall.

Saludos.-

**Comment by Mimito164** [comment]
Finalización:
  - Producidas cuando el proceso llega a la instrucción EXIT
  - Producidas cuando el CPU recibe un interrupt del Kernel por la necesidad de matar un proceso en EXEC

Desalojo:
  - Producida cuando el CPU emite un SIGNAL o un WAIT
  - Producidas cuando el CPU recibe un interrupt del Kernel por los fines de Quantum de RR / VRR.

Bloqueo:
  - Producidas cuando el proceso requiere de una IO

**Comment by LeandroCarbajales** [comment]
Buenas!
Lo de "necesitar ser bloqueado" creo que quedaría mejor explicado como "pedirle algo al Kernel" o "syscalls" como te decía @iago64 (por ejemplo WAIT, SIGNAL, IO). Luego el Kernel decidirá si bloquear al proceso o no.
Lo único que catalogaría como "desalojo" es la interrupción de fin de Q ya que esta es ajena a la ejecución del proceso.

**Comment by Mimito164** [comment]
Perfecto, ahora creo que entendí todo, muchas gracias, cierro el issue.
