### ISSUE TITLE
Detectar desconexión de interfaz IO

### ISSUE THREAD

**Issue by Mimito164** [sisoputnfrba/foro#3456]
Leyendo la consigna vemos que las interfaces I/O se conectarán a Kernel, es decir, Kernel es servidor de las interfaces I/O.
Pero al momento de comunicarse, kernel le hará, alguna petición a las interfaces para que ejecuten algún proceso, la interfaz lo ejecutará y luego le enviará la respuesta a kernel (que quedará a la espera de la misma). En la práctica kernel es cliente, pues este le hace las peticiones a IO.

Mi pregunta es:

- Cómo deberíamos gestionar las desconexiones de una interfaz I/O ? Estamos pensando en hacerles un ping desde kernel antes de utilizarlas para checkear su estado, pero el enunciado no aclara esto.
- La interfaz I/O se puede desconectar mientras está procesando algo ?

**Comment by iago64** [comment]
Buenas!

Me parece que estas confundiendo conceptos, la idea de quien es cliente y quien es servidor es solamente para definir quien inicia la comunicación, después una vez que la misma está establecida, los mensajes pueden ir y venir sin importar quien inició la comunicación.

Respecto a las desconexiones, hay varias formas, la de tirar un "ping" es una opción válida, otra mas simple es mandar el mensaje y si `send()` falla, listo, la interfaz esta desconectada.
Las interfaces de I/O en las pruebas del laboratorio no está pensado que se desconecten, pero no vendría mal que checkeen si el `recv()` no les devuelve -1 cuando están esperando la respuesta de la interfaz de I/O, porque capaz la interfaz voló por los aires por algún error (Segment Fault por ej) y si uds no lo manejan van a volar por los aires con el Kernel también.

Saludos.-
