### ISSUE TITLE
Hilos: pthread_join y pthread_detach

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3457]
Buenas tardes, 
Tenemos una duda con respecto a los hilos, y es que, en el Kernel creamos dos hilos, uno para que "maneje" la conexión con la memoria y otro con la CPU, implementamos un handshake simple para ambos y funciona correctamente. Mi duda es, con respecto a pthread_join, al crear ambos hilos nosotros usamos, en una primera instancia, pthread_detach pero el programa en los distintos modulos terminaba sin pasar absolutamente nada, lo reemplazamos por dos joins, uno por cada hilo y ahí funcionó, mi duda es: al utilizar join primero hace un handshake un hilo y despues el otro? Esto por ahora no molesta, ya que es un simple handshake pero afectaría si el hilo que se ejecuta primero tuviera que hacer más cosas y rompería con la idea de usar hilos para realizar tares de manera concurrente, por eso pensamos en el detach primero pero sucedia lo que comentamos más arriba, el hilo principal no dejaba que estos hagan el handshake antes de terminar el programa.

**Comment by iago64** [comment]
Buenas!

El único problema que van a tener con `pthread_join()` es que el programa se va a clavar esperando que termine el hilo en cuestión.
Por contraparte, el Kernel al ser un proceso que debería vivir siempre, lo que pueden hacer es jugar con el `pthread_detach()` y el hecho de que van a tener un servidor esperando siempre conexiones de las interfaces de I/O, entonces, mientras el hilo main no finalice, los demás hilos tampoco lo van a hacer y main es un muy buen lugar para quedarse esperando las conexiones de las interfaces de I/O 😉 

Saludos.-

**Comment by rood8592** [comment]
Entiendo que eso funcionaria en el caso del Kernel ya que siempre tiene que estar escuchando interfaces I/O, pero en el caso de la CPU como sería? Ahí íbamos a hacer un hilo por cada conexión con Kernel (dispatch e interrupt) y una para manejar la conexión con la memoria. En este caso, la memoria no tiene esto de quedarse escuchando esperando otras cosas, al menos por ahora, con lo cual, en ese caso, nos surgiría el mismo problema.

**Comment by rood8592** [comment]
Realizamos un ejemplo simplificado de lo que no está pasando en el tp a la hora de usar detach en vez de join. Hicimos un programa simple con dos hilos, cuando usamos join funcionan correctamente, con la desventaja de que un hilo se ejecuta primero (saludar) y luego el otro, que es lo que justamente preguntamos en este issue como solucionar, pero cuando usamos detach en vez de join y hacemos un while(1) simulando la escucha constante que habría en el kernel, el programa se queda colgado y no hace absolutamente nada.

ARCHIVO main.c

    #include "../include/main.h"

    int main(int argc, char* argv[]) {

    pthread_t hiloSaludo,hiloDespido;
    pthread_create(&hiloSaludo,NULL,saludar,NULL);
    pthread_create(&hiloDespido,NULL,despedir,NULL);
    pthread_join(hiloDespido,NULL);
    pthread_join(hiloSaludo,NULL);
    //while(1);
   
    return 0;
    }

    void* saludar(void* arg)
    {   
       int n=0;
       while(n<3)
       {
           printf("Hola!");
           n++;
       }
       return NULL;
    }

    void* despedir(void* arg)
    {
       int n = 0;
       while(n<3)
        {
           printf("Chau!");
         n++;
        }
        return NULL;
    }

Archivo main.h

    #ifndef MAIN_H_
    #define MAIN_H_

    #include <stdlib.h>
    #include <stdio.h>
    #include "../../utils/include/sockets.h"
    #include <pthread.h>

    void* saludar(void*);
    void* despedir(void*);

    #endif

El programa está hecho con los joins, cuando descomento el while(1) del main y uso detach, en vez de join, ahí es donde se queda colgado.

**Comment by iago64** [comment]
Buenas! Cómo va?

> Entiendo que eso funcionaria en el caso del Kernel ya que siempre tiene que estar escuchando interfaces I/O, pero en el caso de la CPU como sería? Ahí íbamos a hacer un hilo por cada conexión con Kernel (dispatch e interrupt) y una para manejar la conexión con la memoria. En este caso, la memoria no tiene esto de quedarse escuchando esperando otras cosas, al menos por ahora, con lo cual, en ese caso, nos surgiría el mismo problema.

En el caso de la CPU es muchísimo más simple, pensalo de esta forma, la CPU, siempre pero siempre va a estar ejecutando el ciclo de instrucción: Fetch -> Decode -> Execute -> Check Interrupt y volves a empezar

El hilo que escucha las interrupciones tiene sentido ya que ese va a estar esperando algo en un `recv()` del Kernel.

Ahora bien, las conexiones con la memoria, para que queres tenerlas en un hilo? Vos vas a estar siempre esperando que la memoria te mande algo de manera random o tenes momentos exactos en los que le pedis algo a la memoria y no podes continuar sin esa respuesta?

Respecto a que se les cuelga todo con el `while(1)` es porque posiblemente si se fijan en `htop` se estan comiendo TODA la CPU de la VM y simplemente la VM esta siendo tan cagada a palos que no puede ni procesar otras cosas.
Dato interesante, ese `while(1)` al final no es mas ni menos que una espera activa que para peor no hace NADA, entonces es literalmente comerse la CPU por comersela y ni siquiera estan esperando algo.

Saludos.-

**Comment by rood8592** [comment]
Es tampoco tenemos muy claro tampoco cuando crear un hilo y cuando no hace falta. En el caso del kernel, esta explicitamente en la consigna, pero en los otros casos no es así. ¿Qué requisitos debemos analizar para ver si es correcto, viable o necesario la creación de un hilo o cuando no tiene sentido? Solo se crea un hilo en el caso de querer hacer tareas en paralelo o existen otras situaciones (en este tp al menos)?. Al principio queriamos crear un hilo por cada conexion bidireccional (al menos para el primer checkpoint) pero vemos que no es tan lineal la decisión.

**Comment by iago64** [comment]
Buenas!

A este punto quería llegar, basicamente la idea de crear un hilo es cuando vos queres hacer algo "a la par" de otra cosa, consideremos que pongo a la par entre " " porque en realidad es que se van a ir turnando para hacer un poquito cada uno y eso se llama ejecución concurrente y esto se da principalmente porque la VM tiene 1 solo core, pero no importa, a fines prácticos para entenderlo mas facil, van a la par.

Esas cosas que queres hacer de manera concurrente, por ej, son cosas que no vas a saber cuando van a pasar, como por ejemplo, que te llegue una interrupción del kernel, o que al kernel le avise una interfaz de IO que termino de hacer algo.
Ahora en la CPU, vos casi casi salvo por las interrupciones, el resto de cosas, vas a poder ordenarlas y que sigan un hilo de ejecución sumamente ordenado, por eso que te decía que no necesitas precisamente un hilo.

Te recomiendo que veas la [Charla de Threads](https://docs.utnso.com.ar/guias/linux/threads) que quedo grabada de hace varios años (pre pandemia) donde explicamos un poco esto con algo mas de detalle.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @rood8592! ¿Se entendió lo que comentaba Dami? ¿Pudieron ver la charla de threads? Saludos

**Comment by rood8592** [comment]
Buenas, si se entendió perfecto. Tenia una ultima duda con respecto a la memoria, esta tendria sentido hacerle hilos (no sé cuantos todavía)? Por si, por ejemplo, le llega la peticion de crear un proceso desde kernel y a la vez otro modulo solicita consultar la tabla de paginas (por ahora con lo poco que entiendo las consideró tareas independientes) o se debería establecer una prioridad de atiendo primero kernel, despues al otro modulo. En la consigna no especifica mucho más alla de lo que hacen las solicitudes, por eso la pregunta.

**Comment by iago64** [comment]
Buenas! cómo va?

No se la compliquen tanto, son operaciones que deberían ser independientes entre si porque van a manejarlas por caminos diferentes, una va a venir desde la CPU y otra desde el Kernel, entonces una buena idea sería tener en la memoria un hilo que escucha los pedidos de CPU y otro hilo que escuche las peticiones del Kernel.

Eventualmente si ambos llegan a un punto donde van a estar accediendo a la misma estructura, ahi si puede estar bueno sincronizarlas de alguna manera (como vieron o van a ver en la clase de sincro)

Saludos.-

**Comment by rood8592** [comment]
Muchas gracias por aclararnos todas las dudas! Saludos.
