### ISSUE TITLE
Omision de función por consola MULTIPROGRAMACION [VALOR]

### ISSUE THREAD

**Issue by Mimito164** [sisoputnfrba/foro#3458]
Creo que se les olvidó agregar al enunciado la función por consola que cambia el grado de multiprogramación.

[link al minuto del video](https://youtu.be/7KtjlJdhSIw?t=763)

### 📔 Citas del enunciado/videos

> - Ejecutar Script de Instrucciones: Se encargará de abrir un archivo de instrucciones el cual se encontrará en la máquina donde corra el Kernel contendrá alguna de las siguientes 5 Instrucciones y que las deberá ejecutar una a una hasta finalizar el archivo.
Nomenclatura: EJECUTAR_SCRIPT [PATH]
> - Iniciar proceso: Se encargará de ejecutar un nuevo proceso en base a un archivo dentro del file system de linux que se encontrará en la máquina donde corra la Memoria. Dicho mensaje se encargará de la creación del proceso (PCB) y dejará el mismo en el estado NEW.
Nomenclatura: INICIAR_PROCESO [PATH]
> - Finalizar proceso: Se encargará de finalizar un proceso que se encuentre dentro del sistema. Este mensaje se encargará de realizar las mismas operaciones como si el proceso llegara a EXIT por sus caminos habituales (deberá liberar recursos, archivos y memoria).
Nomenclatura: FINALIZAR_PROCESO [PID]
> - Detener planificación: Este mensaje se encargará de pausar la planificación de corto y largo plazo. El proceso que se encuentra en ejecución NO es desalojado, pero una vez que salga de EXEC se va a pausar el manejo de su motivo de desalojo. De la misma forma, los procesos bloqueados van a pausar su transición a la cola de Ready.
Nomenclatura: DETENER_PLANIFICACION
> - Iniciar planificación: Este mensaje se encargará de retomar (en caso que se encuentre pausada) la planificación de corto y largo plazo. En caso que la planificación no se encuentre pausada, se debe ignorar el mensaje.
Nomenclatura: INICIAR_PLANIFICACION
> - Listar procesos por estado: Se encargará de mostrar por consola el listado de los estados con los procesos que se encuentran dentro de cada uno de ellos.
Nomenclatura: PROCESO_ESTADO

### 💭 Soluciones posibles

No me molestaria que no este estafunciónn en el tp 😁

**Comment by iago64** [comment]
Buenas! 

Gracias por el aviso, nos había quedado como una sugerencia que no aceptamos cuando liberamos el enunciado, aprovechamos y también agregamos la aclaración sobre el camino a tomar a la hora de reducir el grado de multiprogramación si hay mas procesos de los que permite el gradod e multiprogramación.

Saludos.-
