### ISSUE TITLE
Llega el paquete pero no la consola no loguea los mensajes

### ISSUE THREAD

**Issue by Eliaslis** [sisoputnfrba/foro#3459]
Tengo un problema con el paquete. Se manda y llega al server pero no aparecen los mensajes en sí (se puede apreciar mejor en la imagen). Lo raro es que me había estado andando todo este tiempo, incluso con los cambios ya subidos.
![image](https://github.com/sisoputnfrba/foro/assets/81607428/514d5bbe-9a15-4c9f-a176-f202c388c77a)
![image](https://github.com/sisoputnfrba/foro/assets/81607428/8eccc9e7-aaf3-4e27-89c1-abd584fe5ded)
El repo sería este: https://github.com/Eliaslis/tp0/
De todos modos les dejo acá el código de la función paquete, cualquier cosa que falte, estoy a disposición:

```c
void paquete(int conexion)
{
	// Ahora toca lo divertido!
	char* leido;
	t_paquete* paquete = crear_paquete();

	// Leemos y esta vez agregamos las lineas al paquete
		while(1){
		leido = readline("> ");

		if(!strcmp(leido, "")){
			free(leido);
			break;
		}

		agregar_a_paquete(paquete, leido, strlen(leido) + 1);

		free(leido);
		}
	
	
		enviar_paquete(paquete,conexion);

	// ¡No te olvides de liberar las líneas y el paquete antes de regresar!
	eliminar_paquete(paquete);
	
}
```

**Comment by RaniAgus** [comment]
¡Buenas! ¿Usaste el debugger para verificar que se estén serializando y deserializando bien los paquetes? ¿Hiciste algún cambio a las funciones provistas para enviar o recibir los mensajes que pueda haber hecho que deje de funcionar?

Tip: En VSCode podés inspeccionar memoria haciendo click acá:

![image](https://github.com/sisoputnfrba/foro/assets/39303639/ebc7393e-0428-4916-a299-63fe33e1aad4)

Y acá podés ver, por ejemplo, los 36 bytes que voy a enviar desde mi solución del TP0:

![image](https://github.com/sisoputnfrba/foro/assets/39303639/24a5aaf0-9161-460d-875a-1ef957592a3c)

Que son:
- 4 bytes para el código de operación 1 (`PAQUETE`).
- 4 bytes para el tamaño del buffer (que es 28):
![image](https://github.com/sisoputnfrba/foro/assets/39303639/4cccec39-a541-4db3-9bf7-933787d80bf8)
- Y luego el size y los caracteres de cada mensaje del paquete, que se pueden ver a la derecha en ASCII

Saludos

**Comment by iago64** [comment]
Buenas!

Algo interesante es que valores no es más que una lista, entonces eso apunta a una estructura que no necesariamente va a tener el contenido de lo que mandaste.
Si vos queres ver lo que tiene tendrías que por ej inspeccionar el valor de `head` de la `t_list` valores, y ahi si deberías encontrar por ejemplo `prueba`, despues si inspeccionas el next de head vas a encontrar `otra cosa` y por último si inspeccionas el next del next de head vas a encontrar `una linea mas` que son los valores que mandaste.

Saludos.-

**Comment by Eliaslis** [comment]
Hola! Tomando la última explicación me dí cuenta que sí estaban los datos en la lista,

![image](https://github.com/sisoputnfrba/foro/assets/81607428/895582fd-bf47-4b58-9aa0-0cbc30422069)

Pero sigue teniendo el mismo resultado al logguear la lista 😓😓 (el `memory.bin` es de la variable `lista`).
Yo la verdad no encuentro nada raro en el código, lo único que hice es agregar el `list_destroy(lista);` para evitar futuros problemas con la memoria nada más.

```c
#include "server.h"

int main(void) {
	logger = log_create("log.log", "Servidor", 1, LOG_LEVEL_DEBUG);

	int server_fd = iniciar_servidor();
	log_info(logger, "Servidor listo para recibir al cliente");
	int cliente_fd = esperar_cliente(server_fd);

	t_list* lista;
	while (1) {
		int cod_op = recibir_operacion(cliente_fd);
		switch (cod_op) {
		case MENSAJE:
			recibir_mensaje(cliente_fd);
			break;
		case PAQUETE:
			lista = recibir_paquete(cliente_fd);
			log_info(logger, "Me llegaron los siguientes valores:\n");
			list_iterate(lista, (void*) iterator);
			list_destroy(lista);
			break;
		case -1:
			log_error(logger, "el cliente se desconecto. Terminando servidor");
			return EXIT_FAILURE;
		default:
			log_warning(logger,"Operacion desconocida. No quieras meter la pata");
			break;
		}
	}
	return EXIT_SUCCESS;
}

void iterator(char* value) {
	log_info(logger,"%s", value);
}

```

**Comment by RaniAgus** [comment]
¡Buenas @Eliaslis! ¿Pudiste revisar lo que te comentaba? Saludos

**Comment by RaniAgus** [comment]
¡Dale! Igual, para no esperar hasta el sábado, podés aprovechar para arrancar con otra herramienta muy útil para estos casos que es [Valgrind](https://docs.utnso.com.ar/guias/herramientas/valgrind).

Si podés, fijate de correrlo con memcheck a ver si nos tira algún centro de dónde puede estar el error de manejo de memoria.

Saludos

**Comment by Eliaslis** [comment]
Buenas! Hace un rato me conecté al soporte de los sábados y resolvimos el problema!. El tema estaba en esta línea: `free(valor);` en el código de `t_list* recibir_paquete(int socket_cliente)`:
```c
t_list* recibir_paquete(int socket_cliente)
{
	int size;
	int desplazamiento = 0;
	void * buffer;
	t_list* valores = list_create();
	int tamanio;

	buffer = recibir_buffer(&size, socket_cliente);
	while(desplazamiento < size)
	{
		memcpy(&tamanio, buffer + desplazamiento, sizeof(int));
		desplazamiento+=sizeof(int);
		char* valor = malloc(tamanio);
		memcpy(valor, buffer+desplazamiento, tamanio);
		desplazamiento+=tamanio;
		list_add(valores, valor);
		free(valor);
	}
	free(buffer);
	return valores;
}
```
Como mencionó antes @RaniAgus la forma correcta de eliminar la lista y sus valores es utilizando la función `list_destroy_and_destroy_elements()` y no liberando la referencia a medida que se ingresaba un valor nuevo a la lista como estaba haciendo yo. 
Así que nada, muchas gracias por la información y la ayuda, me sirvió un montón. Cierro el hilo.
