### ISSUE TITLE
Hay dos PC?

### ISSUE THREAD

**Issue by diegohcanetti** [sisoputnfrba/foro#3460]
Revisando el Enunciado y nuestro TP nos dimos cuenta que tenemos repetido el program counter. Debería haber uno solo?

### 📔 Citas del enunciado/videos
>Program Counter: Número de la próxima instrucción a ejecutar.
Registros de la CPU: Estructura que contendrá los valores de los registros de uso general de la CPU.

Y mas adelante

>Registros de la CPU
En la implementación de nuestra CPU, vamos a utilizar una serie de registros para poder modelar la operatoria de una CPU real...
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-660530b6-7fff-3d29-d568-a5a9ceb24278"><div dir="ltr" style="margin-left:0pt;" align="left">
Registro | Tamaño | Tipo de Dato | Descripción
-- | -- | -- | --
PC | 4 bytes | uint32_t | Program Counter, indica la próxima instrucción a ejecutar

</div></b>
</body>
</html>

**Comment by LeandroCarbajales** [comment]
Buenas!
Cito la misma parte del enunciado:
"Registros de la CPU: Estructura que contendrá los valores de los registros `de uso general` de la CPU."

En la definición del PCB separamos el PC dada su importancia y que es un registro _de uso específico_ en lugar de general, pero a efectos de implementación pueden tener un struct con todos juntos si quisieran.

Te aclara la duda?
Saludos!
      Lean

**Comment by diegohcanetti** [comment]
Entonces lo separaron en general y específico, pero es lo mismo?

**Comment by LeandroCarbajales** [comment]
Hay uno solo sí, se nombra una sola vez en el módulo CPU y Kernel, normalmente Program Counter / Instruction Pointer hay uno solo por cada CPU, no tendría mucho sentido tener 2 en este caso :)

**Comment by diegohcanetti** [comment]
Perfecto gracias!!
