### ISSUE TITLE
Error inesperado de struct addrinfo

### ISSUE THREAD

**Issue by DanielKesel** [sisoputnfrba/foro#3462]
Hola!, Ya había terminado el TP0 y me andaba todo perfecto, al otro día (hoy) prendí las VMs y de la nada tenía marcado en rojo y sin poder compilar las variables del struct addrinfor y no puedo entender por qué. Encontré este issue cerrado: https://github.com/sisoputnfrba/foro/issues/2574 De la forma que el chico lo resuelva a mi no me funciona.

Todo lo que remarco en negro en el visual studio está subrayado en rojo:
esto es parte de mi archivo utils.c

```c
#include <commons/collections/list.h>
#include "utils.h"


void* serializar_paquete(t_paquete* paquete, int bytes) {
  void * magic = malloc(bytes);
  int desplazamiento = 0;

  memcpy(magic + desplazamiento, &(paquete->codigo_operacion), sizeof(int));
  desplazamiento+= sizeof(int);
  memcpy(magic + desplazamiento, &(paquete->buffer->size), sizeof(int));
  desplazamiento+= sizeof(int);
  memcpy(magic + desplazamiento, paquete->buffer->stream, paquete->buffer->size);
  desplazamiento+= paquete->buffer->size;

  return magic;
}

int crear_conexion(char *ip, char* puerto) {
  struct addrinfo hints;
  struct addrinfo *server_info;

  memset(&hints, 0, sizeof(hints));
  hints.ai_family = AF_INET;
  hints.ai_socktype = SOCK_STREAM;
  hints.ai_flags = AI_PASSIVE;

  getaddrinfo(ip, puerto, &hints, &server_info);

  // Ahora vamos a crear el socket.
  int socket_cliente = socket(server_info->ai_family, server_info->ai_socktype, server_info->ai_protocol);

  // Ahora que tenemos el socket, vamos a conectarlo
  connect(socket_cliente, server_info->ai_addr, server_info->ai_addrlen);
```

Los server info tambien están subrayados en rojo.

Paso un print de pantalla de errores al compilar:
![image](https://github.com/sisoputnfrba/foro/assets/82064789/241cdfef-7418-4e53-86dc-2a4850943b4f)}}

No entiendo que me está pasando acá sinceramente :(

**Comment by RaniAgus** [comment]
¡Buenas! ¿Podrías copiarnos lo que te imprime la pestaña de terminal? Te paso un ejemplo sacado de Crear tu primer proyecto C > Errores de compilación > Cómo reportar errores:

![image](https://docs.utnso.com.ar/img/primeros-pasos/primer-proyecto-c/vscode-copy-compiler-output.gif)

Saludos

**Comment by DanielKesel** [comment]
Cuando doy run and debug la terminal da estos mensajes:

Starting build...
/usr/bin/gcc -fdiagnostics-color=always -g /home/utnso/Desktop/DANI/tp0/client/src/utils.c -o /home/utnso/Desktop/DANI/tp0/client/src/utils
/usr/bin/ld: cannot open output file /home/utnso/Desktop/DANI/tp0/client/src/utils: Permission denied
collect2: error: ld returned 1 exit status

Build finished with error(s).

 *  The terminal process terminated with exit code: -1. 
 *  Terminal will be reused by tasks, press any key to close it. 

Cuando hago el make all me arroja esto:

utnso@utnso:~/Desktop/DANI/tp0/client$ sudo make all
gcc -g -Wall -DDEBUG -fdiagnostics-color=always -c -o "obj/utils.o" src/utils.c -I./src
src/utils.c: In function ‘crear_conexion’:
src/utils.c:42:16: warning: variable ‘bytes’ set but not used [-Wunused-but-set-variable]
   42 |         size_t bytes;
      |                ^~~~~
gcc -g -Wall -DDEBUG -fdiagnostics-color=always -c -o "obj/client.o" src/client.c -I./src
src/client.c: In function ‘main’:
src/client.c:43:9: warning: format not a string literal and no format arguments [-Wformat-security]
   43 |         log_info(logger, valor);
      |         ^~~~~~~~
src/client.c: In function ‘iniciar_logger’:
src/client.c:85:16: warning: returning ‘int’ from a function with return type ‘t_log *’ makes pointer from integer without a cast [-Wint-conversion]
   85 |         return 1; // Termina el programa con un código de error
      |                ^
src/client.c: In function ‘leer_consola’:
src/client.c:126:17: warning: implicit declaration of function ‘add_history’ [-Wimplicit-function-declaration]
  126 |                 add_history(leido);
      |                 ^~~~~~~~~~~
src/client.c:133:17: warning: format not a string literal and no format arguments [-Wformat-security]
  133 |                 log_info(logger, leido);
      |                 ^~~~~~~~

**Comment by RaniAgus** [comment]
Qué raro, al darle a "Run and Debug" debería aparecerte algo como:
```
Executing task: make all
```
¿Qué te aparece en el desplegable de esa pestaña? ¿Tenés abierto el TP0 desde el workspace?

**Comment by DanielKesel** [comment]
Agus gracias por ese último datazo del workspace, se ve que algo pasó y se me había salido o quizá yo lo volvi a abrir fuera del workspace y no hice el code tp0.code-workspace.
Hice code tp0.code-workspace y se me abrió de nuevo y ahora anda todo perfecto!.

Con respecto a lo de SUDO, sinceramente no se por qué, pero desde que instalé xubuntu siempre para hacer cualquier cosa me tira error por no tener permisos y tengo que usar sudo para todo. A diferencia de las de ubuntu (sin grafica) que no necesito meter un sudo a todo.

**Comment by RaniAgus** [comment]
Hmm... No deberías tener problemas de permisos 🤔 
¿Es posible que tengas el TP0 montado en una carpeta compartida? De ser así, te aconsejaría dejar de usarla, ya que (spoiler de la parte teórica) el file system que utiliza Linux maneja los permisos de forma muy distinta al de Windows, por lo que solemos encontrarnos con conflictos de este estilo al montar una carpeta de un NTFS en un EXT4, por ejemplo.

**Comment by DanielKesel** [comment]
Lo tenía en una carpeta dentro del escritorio, pero en otra VM dejé el tp0 en el escritorio y ahi me funcionaba sin sudo. Ni idea la verdad!

**Comment by RaniAgus** [comment]
¡Buenísimo! Como ya está todo resuelto cerramos el issue.
