### ISSUE TITLE
Inicio de interfaces i/o

### ISSUE THREAD

**Issue by ElielBejar** [sisoputnfrba/foro#3463]
Que tal! Quería saber del enunciado por donde se hace el inicio de cada interfaz y por donde se pasan los parámetros del nombre y del archivo de configuración. ¿Hay que hacer una consola en ese módulo para iniciar las interfaces o por donde se hace?

### 📔 Citas del enunciado/videos
>Al iniciar una Interfaz de I/O la misma deberá recibir 2 parámetros:
Nombre: Este nombre será único dentro del sistema y servirá como identificación de la Interfaz dentro del TP.
Archivo de Configuración

### 💭 Soluciones posibles
Hacer una consola que lea entradas en el módulo de interfaz i/o donde se le pase esos dos parámetros y ahí levante el archivo de configuración correspondiente para esa interfaz

**Comment by LeandroCarbajales** [comment]
Buenísimo :)
Si la duda está resuelta cierro el issue.
