### ISSUE TITLE
Archivos de pseudocódigo

### ISSUE THREAD

**Issue by fmigliavacca** [sisoputnfrba/foro#3464]
Hola, no estoy comprendiendo cómo son los archivos de pseudocódigo. Me gustaría saber de qué estilo serían para así ver cómo procesarlos por parte de la memoria. Si me podrían decir en qué formato vendría o dónde podría encontrar información me re ayudarían. Saludos!!

### 💭 Soluciones posibles
Pienso que podría ser un archivo.txt con instrucciones del estilo mov ax bx una abajo de la otra.

**Comment by LeandroCarbajales** [comment]
Buenas!
Hay un ejemplo del mismo en el módulo CPU, pero sí, es literalmente un archivo de texto con instrucciones "una debajo de la otra" (separadas por /n).

**Comment by RaniAgus** [comment]
¡Buenas @fmigliavacca! ¿Quedó clara la respuesta de Lean? Saludos

**Comment by fmigliavacca** [comment]
Clarisima! Gracias

**Comment by RaniAgus** [comment]
¡Buenísimo! No se olviden de cerrar el issue una vez resuelta la duda
