### ISSUE TITLE
Duda sobre Protocolo de Comunicación 

### ISSUE THREAD

**Issue by elin-winter** [sisoputnfrba/foro#3466]
Hola, con mí grupo teníamos una duda sobre el primer checkpoint obligatorio. En él, dice que se debe configurar el protocolo de comunicación, sin embargo no entendemos cómo se podría hacer. Alguno tiene idea?

**Comment by LeandroCarbajales** [comment]
Buenas!
En el TP0 ya está predefinido el protocolo de comunicación en el sentido de que hay un proceso "servidor" que espera conexiones y un "cliente" quien se conecta al mismo y es quien comienza mandando un mensaje mientras que el servidor solamente recibe los mismos.
En este TP, además de definir quién espera y quién se conecta (o ambas, como el caso del Kernel) tienen que definir, ya a decisión propia, una vez conectados los módulos quién inicia la comunicación (quién manda mensajes y quien los espera) y si tendrán un handshake pertinente (por ejemplo para saber quién se conectó).

Te ayuda la respuesta?
Saludos!
       Lean

**Comment by iago64** [comment]
Buenas! Cómo va?

Tal cual decís, ya con eso tienen una primera parte del protocolo que es quien se conecta a quien y como hacen el handshake.
Después de eso lo que sigue es ver quién se queda esperando algo después del handshake, por ejemplo, la cpu se va a quedar esperando que el Kernel le mande un contexto de ejecución en el socket dispatch y una interrupción en el socket interrupt y asi con el resto de los módulos.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @elin-winter! ¿Se entendió lo que comentó Dami? Saludos

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, ante cualquier consulta pueden reabrirlo o abrir uno nuevo. Saludos
