### ISSUE TITLE
Problema de acceso al repo del tp

### ISSUE THREAD

**Issue by GonGarciaFontenla** [sisoputnfrba/foro#3468]
Buen día!

Espero que estén bien. Quería compartir un pequeño inconveniente que estoy teniendo. Ayer me crearon el repositorio para el trabajo práctico de la materia, pero estoy teniendo dificultades para acceder a él.

Hablé con uno de los ayudantes y me comentó que el problema podría estar relacionado con una posible error en la inscripción. Alguien podría orientarme sobre cómo proceder en este caso?

Agradezco de antemano cualquier ayuda o consejo que puedan brindarme.

Gracias!

pd: Adjunto foto del error (la screen la saque desde mi maquina personal, pero me aparece lo mismo en la VM).

![Captura de pantalla (58)](https://github.com/sisoputnfrba/foro/assets/134091098/b7a40d25-202a-404e-86f5-2f6a2dd8e081)

**Comment by iago64** [comment]
Buenas! Cómo va?

Eso puede deberse a que originalmente no aceptaste la invitación a la organización de sisoputnfrba.
Por suerte podes volver a invitarte desde el [sistema de inscripciones](https://inscripciones.utnso.com.ar).

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, ante cualquier consulta pueden reabrirlo o abrir uno nuevo. Saludos
