### ISSUE TITLE
Comunicación de las interfaces de IO

### ISSUE THREAD

**Issue by fedenimi** [sisoputnfrba/foro#3469]
Hola, qué tal? Estamos tratando de plantear la comunicación entre las interfaces de IO y el kernel y nos surgieron un par de dudas.
 1- Como el kernel debe enviarle a la interfaz una petición cada vez que un proceso necesite hacer una E/S, esas interfaces deberían tener servidores que esperen a que el kernel los llame? 
2- Cuando se conecta un socket a un servidor y luego termina de realizar una tarea, este se "muere" instantáneamente o puede quedarse conectado y seguir mandando mensajes cuando lo necesite en un momento posterior?
Muchas gracias y saludos.

**Comment by FredeHG** [comment]
Hola buenas! 
1. El concepto de servidor y cliente es quien inicia la comunicación, una vez establecida cualquier parte puede enviar un mensaje a su contraparte. Mirando el archivo de configuración de kernel y las interfaces podes deducir como puede venir la mano. Te dejo un issue relacionado que te puede ayudar https://github.com/sisoputnfrba/foro/issues/3456

2. Esto te invito a que intentes hacer un programa sencillo que envié multiples mensajes con un for o aun mejor que el cliente (o servidor) pida inputs por teclado y luego los mande a la contraparte ese mismo input, encuentro que esto puede esclarecer como funciona un protocolo cliente-servidor


Si algo de ahi no se entiende no dudes en re-preguntar
Y si esta respuesta es suficiente, por favor cerraremos el issue.

**Comment by fedenimi** [comment]
Ok, perfecto, gracias!
