### ISSUE TITLE
CPU: Multiprocesamiento

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3470]
Buenas, en el enunciado nos hablan de multiprogramación que, según lo poco que vi de teoría, es la cantidad de procesos que pueden estar en "ready+exec+blocked" pero no habla en ningún momento de multiprocesamiento, la CPU solo podrá ejecutar de a un proceso a la vez? Tendría un único nucleo digamos.

**Comment by LeandroCarbajales** [comment]
Buenas!
Exactamente, en este Trabajo simularemos (simplificadamente) la actividad de solamente una CPU (1 core).
