### ISSUE TITLE
Password Keyring

### ISSUE THREAD

**Issue by JuanScollo** [sisoputnfrba/foro#3471]
Buenas, tengo un problema cuando entro a visual, me pide una contraseña, probe con utnso pero no me funciono. Estoy usando la vm de la catedra siguiendo los pasos del foro.
![WhatsApp Image 2024-04-09 at 20 55 09](https://github.com/sisoputnfrba/foro/assets/164966875/cd3320cf-8481-415a-b61b-1a32e4d0261c)

**Comment by iago64** [comment]
Buenas! Cómo va?

Por las dudas te pregunto, por casualidad guardaste credenciales de git en vscode? Porque puede venir por ahí, ahora el tema es que si no te toma la password del usuario de utnso, capaz creaste algo mas que no estaríamos sabiendo.

Saludos.-

**Comment by JuanScollo** [comment]
Perdon, pero no sabria decirte, no se que son las credenciales. Creeria que no, hay alguna forma de fijarme?

**Comment by RaniAgus** [comment]
¡Buenas! Probablemente Visual Studio Code te haya facilitado el login a GitHub guardando las credenciales en un [keyring](https://itsfoss.com/ubuntu-keyring/), que es como una base de datos de contraseñas que solo se pueden desencriptar contando con una contraseña.

Para esto, primero es necesario _crear_ dicho keyring, para lo cual asumo que se habrá abierto una ventana como la siguiente:

![Screenshot from 2024-04-10 20-18-45](https://github.com/sisoputnfrba/foro/assets/39303639/f7d57910-3f3e-49eb-9939-2355ce417320)

Es por esto que Dami sugiere que, quizás por confusión, hayas ingresado acá la contraseña de GitHub creyendo que se pide la contraseña para loguearse, cuando en realidad es una contraseña nueva que sirve para, justamente, guardar de forma segura las credenciales de GitHub.

Saludos

**Comment by JuanScollo** [comment]
Hola RaniAgus, gracias por la info! 
Estuve probando con la contrasena de github y variantes parecidas por si erre alguna tecla, pero no es. Creando la VM denuevo se podria solucionar?
Saludos!

**Comment by RaniAgus** [comment]
¡Buenas! Sip, creando la VM de nuevo deberías poder configurar una password cuando aparezca esa pantalla y luego usarla 👍🏻

**Comment by karengrams** [comment]
¡Aló @JuanScollo!

¿Cómo estas? Espero que bien. Suponemos que la resolución que te dio Agus fue suficiente, debido a la inactividad, cerramos el issue. De todas formas, _vale aclarar_, si la duda no fue resuelta, te invitamos acercarte a cualquier sábado de soporte para poder resolverla o re-abrir el issue.

¡Saludos!

Kar.-
