### ISSUE TITLE
Logs mínimos y obligatorios

### ISSUE THREAD

**Issue by lucasvazz16** [sisoputnfrba/foro#3473]
Hola, la duda que tengo es ¿Tengo que hacer un archivo de log distinto por cada item que aparece en el enunciado o puedo hacer un archivo de log que contenga varios items?

### 📔 Citas del enunciado/videos

> Logs mínimos y obligatorios
Creación de Proceso: “Se crea el proceso <PID> en NEW”
Fin de Proceso: “Finaliza el proceso <PID> - Motivo: <SUCCESS / INVALID_RESOURCE / INVALID_WRITE>”
Cambio de Estado: “PID: <PID> - Estado Anterior: <ESTADO_ANTERIOR> - Estado Actual: <ESTADO_ACTUAL>”
Motivo de Bloqueo: “PID: <PID> - Bloqueado por: <INTERFAZ / NOMBRE_RECURSO>”
Fin de Quantum: “PID: <PID> - Desalojado por fin de Quantum”
Ingreso a Ready: “Cola Ready <COLA>: [<LISTA DE PIDS>]”

### 💭 Soluciones posibles

Por ejemplo, en este caso, yo crearía un solo archivo de registro para "Creación de procesos" y "Fin de procesos", donde se registraría lo que pide cada uno, pero no sé si lo que se busca es que cree un archivo para registrar "Creación de procesos" y otro archivo para registrar "Fin de procesos" por separado.

**Comment by FredeHG** [comment]
Hola buenas! 
La idea es que los logs mínimos y obligatorios estén en un archivo de cada modulo. Pudiendo ustedes de necesitar más logs agregarlos en un archivo aparte

Si esta respuesta es suficiente, por favor cerraremos el issue.
Saludos!
