### ISSUE TITLE
Creación de módulos

### ISSUE THREAD

**Issue by tomassagrada** [sisoputnfrba/foro#3474]
-	Estamos dudando en a que se refiere la consigna con la creación de los módulos, entonces la duda viene en que sería necesario para que un módulo se considere creado (o archivos a crear).

**Comment by iago64** [comment]
Buenas! Cómo va?

Si repasamos el checkpoint del día 20/04, lo referente al desarrollo del TP son:

> Aprender a utilizar las Commons, principalmente las funciones para listas, archivos de configuración y logs.
Esto ya deberían tenerlo del tp0, o basicamente es poder leer el archivo de config del módulo y crear el archivo de log del mismo.

> Definir el Protocolo de Comunicación.
Esto es definir quien se conecta con quien y como quedan despues esperando los mensajes, es algo que tambien lo preguntaron en el issue #3466 

> Todos los módulos están creados y son capaces de establecer conexiones entre sí.
Un poco mas de lo del anterior, los módulos son programas que se pueden ejecutar y se conectan entre si.

Saludos.-

**Comment by tomassagrada** [comment]
Buenísimo, Muchas gracias.
