### ISSUE TITLE
Problema de undefined reference

### ISSUE THREAD

**Issue by nicolasreypc** [sisoputnfrba/foro#3476]
Cree un gestor para que las funciones definidas en archivos .c distintos del main puedan reconocer las variables globales.
Pero estoy teniendo este error:
![image](https://github.com/sisoputnfrba/foro/assets/143523417/6bfa137e-6403-4fa4-867d-c591200cd785)
![image](https://github.com/sisoputnfrba/foro/assets/143523417/60894b7b-4c99-4da3-a89c-9d257fe8609b)
![image](https://github.com/sisoputnfrba/foro/assets/143523417/961fcf7a-333f-4a9b-9150-4db0995ea7d2)
![image](https://github.com/sisoputnfrba/foro/assets/143523417/a8838416-c4d7-4e7b-bc42-d2345f383ea6)

No entiendo porque no reconocen al k_gestor

**Comment by nicolasreypc** [comment]
//-----------------------------------------------CODIGO DEL GESTOR
#ifndef K_GESTOR_H_
#define K_GESTOR_H_

#include <utils/shared.h>

#include <stdint.h>
#include <pthread.h>
#include <commons/txt.h>
#include <commons/collections/list.h>


//Variables GLOBALES
extern t_log* kernel_logger;
extern t_log* kernel_log_debug;

extern int fd_kernel;
extern int fd_memoria;         
extern int fd_entrada_salida;
extern int fd_cpu_dispatch;
extern int fd_cpu_interrupt;

extern int identificador_PID;
extern int contador_pcbs;

extern pthread_mutex_t mutex_pid;

#endif

//-----------------------------------------------CODIGO DEL SERVICIOS_KERNEL.H
#ifndef SERVICIOS_KERNEL_H_
#define SERVICIOS_KERNEL_H_

#include "./k_gestor.h"

int asignar_pid ();



#endif

//---------------------------------------CONDIGO DEL SERVICIOS_KERNEL.C
#include "../include/servicios_kernel.h"

int asignar_pid (){
    int valor_pid;
    
    pthread_mutex_lock(&mutex_pid);
    valor_pid = identificador_PID;
    identificador_PID++;
    pthread_mutex_unlock(&mutex_pid);

    return valor_pid;
}

**Comment by iago64** [comment]
Buenas! Cómo va?

Antes que nada, fijate la [guía de markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) para que quede mas prolijo el código en el issue.
Respecto al problema que estas teniendo, una consulta, vos estas abriendo la carpeta directamente o estas abriendo el workspace con la opción de Open Workspace from file?

![image](https://github.com/sisoputnfrba/foro/assets/1622109/ae04e814-f6f6-49f2-ad92-5658dbd5e40c)

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @ReyNicolas! ¿Pudieron resolver el problema? Saludos

**Comment by nicolasreypc** [comment]
No podia solucionarlo pero a mis compañeros les andaba bien, asi que borre y volvi a clonar el codigo y se soluciono, gracias!
