### ISSUE TITLE
Problema con asignacion de IP a la VM

### ISSUE THREAD

**Issue by LucasCristin23** [sisoputnfrba/foro#3477]
Buenas! Visto que no hay ningun Issue al respecto paso a consultar, estoy en la etapa 4 del TP0, ya cree la VM, pero cuando inicia me asigna un IP distinto al formato que se esperaria (192.168.xxx.xxx), el mismo es 127.0.0.1
Ya tengo la red configurada en Bridged Adapter. 

### 📔 Captura de lo que me dice la bash
Adjunto una captura de pantalla ya que no es posible copiar y pegar el texto
![Captura de pantalla 2024-04-10 204853](https://github.com/sisoputnfrba/foro/assets/85961117/20e99b3e-14db-4166-9b31-561b4acc6a4a)

**Comment by iago64** [comment]
Buenas! Cómo va?

Vos en esa VM tenes 2 interfaces de red, `enp0s3` que es la del router y después `lo` o loopback que es la referencia a tu misma máquina (127.0.0.1)

Lo que me llama la atención es que si la tenes en modo puente (o Bridged Adapter) tu router esta asignándote una ipv6 en lugar de una ipv4, si abris una terminal en la VM con entorno gráfico y ejecutas el comando `ifconfig` te tira tambien una ipv6?

Saludos.-

**Comment by LucasCristin23** [comment]
Como estas? 
Si, en la que tiene entorno grafico tambien tiene una ipv6
Me devuelve lo siguiente: 
`enp0s3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255
        inet6 fe80::a00:27ff:fe6e:9541  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:6e:95:41  txqueuelen 1000  (Ethernet)
        RX packets 2  bytes 1180 (1.1 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 36  bytes 6184 (6.1 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0`
`lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 10  bytes 1564 (1.5 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 10  bytes 1564 (1.5 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0`

**Comment by RaniAgus** [comment]
¡Buenas! Ahí la de entorno gráfico te está devolviendo una IPv4, pero es de la red local porque no está configurada como "Bridged Adapter":
```
        inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255
```

Volviendo a la configuración de la Server, ¿te aparecen varias opciones al elegir el nombre del adaptador de red?

![image](https://github.com/sisoputnfrba/foro/assets/39303639/c1918474-6162-4f47-8f55-9b921a17f42d)

De ser así, podríamos probar con varios a ver si alguno permite asignar IPv4.

**Comment by LucasCristin23** [comment]
Buen día! en la VM al elegir el nombre del adaptador de red me aparece una sola opción, la siguiente

![Captura de pantalla 2024-04-11 132757](https://github.com/sisoputnfrba/foro/assets/85961117/3c2b655c-1a95-4759-ad11-9b100bb685ba)

**Comment by iago64** [comment]
Buenas! Cómo va?

El problema no parece ser la configuración de la VM, si no más bien que el router elige asignarte una IPv6, por casualidad, que empresa de internet tenes? Como para andar teniendo algunos casos testigo de routers que ya asignan IPv6 por defecto.
De todas formas para la prueba local del TP en 2 VMs podrías probar NAT y usar las IP que empiezan en 10.0.X.X ya que la red NAT es una red que arma entre las VMs de deberían poder verse entre si.

Saludos.-

**Comment by LucasCristin23** [comment]
Buenas noches! Probé con la IP 10.0.x.x y no me funciono.
De empresa de internet tengo Telecentro, tengo un amigo que tiene Fibertel que le pasa exactamente lo mismo.
Muchas gracias a todos por contestar, saldos.

**Comment by NazarenoLopez** [comment]
Hola, estoy teniendo el mismo problema con el servidor...
Como me puedo contectar a la VM desde Shell usando NAT? Porque uso el comando ssh pero no funciona...
