### ISSUE TITLE
Duda multiples conexiones IO-Kernel e IO-memoria

### ISSUE THREAD

**Issue by patriciojgf** [sisoputnfrba/foro#3478]
Buenas,

Mi duda es sobre como realizar las conexiones entre IO y los otros modulos.
Puede haber varias conexiones de IO diferentes al kernel o a memoria en simultaneo?
Si es asi, los clientes son siempre las IO y tanto memoria como kernel tienen un puerto_escucha que esta manejando las conexiones a todas esas interfaces a la vez?
Cuando kernel tenga que ejecutar una instrucción que vaya a una interfaz, y tenga el nombre de la misma, como va a saber a que cliente de los que se conectaron tiene que ir? Guardo el dato del nombre junto a su socket en alguna estructura dentro del kernel?

Gracias.

**Comment by iago64** [comment]
Buenas! Cómo va?

Si recordas la [Guía de Sockets](https://docs.utnso.com.ar/guias/linux/sockets), al momento de hacer `accept()` esta función te devuelve un valor, ese valor es el socket propiamente dicho que vas a tener para la comunicación con ese módulo.
Después depende de uds implementar una serie de mensajes para poder tener mas info al respecto de ese socket y por ej poder identificar que Interfaz de IO es.

Saludos.-

**Comment by patriciojgf** [comment]
Hola Damian, como estas?
Perfecto, armo un socket por conexión y le paso tipo-io por codop y nombre por mensaje tipo handshake.
Mi duda es, la relación socket-nombre la guardo en una estructura tipo la de archivos en kernel y en memoria?
Gracias

**Comment by patriciojgf** [comment]
Dale, hago esas estructuras entonces para la relacion.
Grcias!
