### ISSUE TITLE
Duda sobre conexiones en Kernel

### ISSUE THREAD

**Issue by Champa123** [sisoputnfrba/foro#3479]
### 📔 Citas del enunciado/videos

> Además de las operaciones de la consola interactiva, el Kernel será el encargado de gestionar las peticiones contra la Memoria (a través de una conexión de dispatch y otra de interrupt) y las interfaces de I/O (conectadas dinámicamente), por lo que deberá implementarse siguiendo una estrategia multihilo que permita la concurrencia de varias solicitudes desde o hacia diferentes módulos.

### 💭 Soluciones posibles
Entiendo que la conexion de dispatch e interrupt son contra la CPU. En particular la primera para el envio de PCBs, y la segunda para interrumpir procesos. Esperaria que el CPU pueda devolver al kernel el contexto de ejecucion actual del proceso desalojado (ya sea por un desalojo o un bloqueo por uso de IO) El cpu puede usar la conexion que tiene con el kernel de dispatch para enviar data? Es decir tanto kernel como cpu son clientes y servidores con esa conexion?

**Comment by RaniAgus** [comment]
¡Buenas! Como explicamos en la [guía de sockets](https://docs.utnso.com.ar/guias/linux/sockets), las conexiones que se establecen son **bidireccionales**. De hecho, justamente en el ejemplo de handshake tanto el cliente como el servidor se envían (`send()`) y reciben (`recv()`) información. 

La arquitectura cliente-servidor sirve solamente para que ambos procesos puedan encontrarse en una red distribuida. Haciendo una analogía: uno debe saber la ubicación del otro, y el otro tiene que estar ahí para abrirle la puerta, digamos.

Te invito a repasar la guía de sockets por si no se entendió algo sobre cómo se da dicha comunicación.

Saludos

**Comment by Champa123** [comment]
Gracias Agus, cierro el Issue
