### ISSUE TITLE
Duda multiples modulos I/O

### ISSUE THREAD

**Issue by GregorioOndjian** [sisoputnfrba/foro#3481]
Buenass, no me queda claro como encarar el tema de las multiples modulos de I/O. Se que el kernel solucita la creacion de estos modulos a traves de un nombre unico y un config, que ya debería estar creado. Pero la verdad no se me ocurre como pasarlo a código. Como hago para iniciar los módulos desde el código? yo inicio los modulos con un botoncito :(
### 📔 Citas del enunciado/videos

> Módulo: Interfaz de I/O
> Las interfaces de I/O pueden ser varias, en la realidad las conocemos como Teclados, Mouse, Discos, Monitores o hasta Impresoras.
> Lineamiento e Implementación
> Cada interfaz en la vida real tiene diferentes velocidades, por lo que para simplificar esto en nuestro TP vamos a tener en la configuración del módulo el Tiempo de unidad de trabajo, este valor luego se va a multiplicar por otro valor que va a estar dado según el tipo de interfaz que tengamos, en este TP vamos a trabajar con 4 tipos de Interfaces: Genéricas, STDIN, STDOUT y DialFS.
> Al iniciar una Interfaz de I/O la misma deberá recibir 2 parámetros:
> Nombre: Este nombre será único dentro del sistema y servirá como identificación de la Interfaz dentro del TP.
> Archivo de Configuración

**Comment by RaniAgus** [comment]
¡Buenas! El kernel no es el que inicia dichos módulos, sino que acepta las conexiones de éstos y las registra para saber si puede o no atender una petición.

Como analogía, en la vida real el kernel no puede enchufar un teclado, un usuario lo hace y el sistema operativo debe encargarse de registrar dicha conexión.

Saludos

**Comment by GregorioOndjian** [comment]
Aa okey, o sea que los multiples modulos ya deberian estar inciados, y de ahi el kernel registra y opera con ellos?

**Comment by RaniAgus** [comment]
Correcto!
