### ISSUE TITLE
Cuando se realiza el IO_GEN_SLEEP también hay que hacer un sleep en Kernel?

### ISSUE THREAD

**Issue by diegohcanetti** [sisoputnfrba/foro#3482]
Según entiendo cada vez que se mande un proceso a IO lo único que hay que hacer es mandarlo a blockeado y cuando el IO termine de realizar su operación, le avisa al proceso que puede entrar a Ready. En ninguna parte del TP se explica cuando es que el proceso pasa de Blockeado a Ready.

### 📔 Citas del enunciado/videos
>IO_GEN_SLEEP (Interfaz, Unidades de trabajo): Esta instrucción solicita al Kernel que se envíe a una interfaz de I/O a que realice un sleep por una cantidad de unidades de trabajo.
>Motivo de Bloqueo: “PID: <PID> - Bloqueado por: <INTERFAZ / NOMBRE_RECURSO>”

**Comment by iago64** [comment]
Buenas! Cómo va?

Asumimos que se entendía por lo visto en la teoría que una vez que finaliza el bloqueo por un dispositivo el proceso se pasa de estado bloqueado a ready.

Saludos.-

**Comment by diegohcanetti** [comment]
Perfecto, muchas gracias 👍
