### ISSUE TITLE
 Program received signal SIGSEGV, Segmentation fault. - MAC OS 

### ISSUE THREAD

**Issue by Rasco007** [sisoputnfrba/foro#3483]
Tengo el problema de que no corre el programa en la vm levantada desde mi MAC Intel, pero sí corre desde una compu Windows(la del trabajo). Me tira "Program received signal SIGSEGV, Segmentation fault." en el tab de Debug Console. Todo esto desde el Visual Studio. En ambos seguí los mismos pasos, ejecuté el comando "code tp.code-workspace" y luego lo corrí y sucede esto.

<img width="1260" alt="Captura de Pantalla 2024-04-11 a la(s) 12 55 24" src="https://github.com/sisoputnfrba/foro/assets/56683567/84c274dd-e610-41e4-bd4d-cae1c3c8b23e">

**Comment by Rasco007** [comment]
<img width="657" alt="Captura de Pantalla 2024-04-11 a la(s) 13 02 49" src="https://github.com/sisoputnfrba/foro/assets/56683567/0ff0cb6d-d528-403c-bb30-b80202ffc58c">

Este es el código del TP, queremos probar correrlo primero todos. 
Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

Solo para empezar a entender un poco las diferencias, hay una herramienta muy copada que nos ayuda a interpretar un poco mas estos problemas de memoria y esa herramienta es la tan mencionada [Valgrind](https://docs.utnso.com.ar/guias/herramientas/valgrind), es un buen momento para que empieces a conocerla a ver si te tira un centro con el error.

De todas formas si no entendés lo que te devuelve por favor no subas una captura de lo que te devuelve, si no que subí el texto así es mas fácil para nosotros para buscar ahí.

Saludos.-

**Comment by Rasco007** [comment]
Hola cómo va? Lo solucioné llevando Virtualbox a una versión más antigua, la 6.1, yo estaba en la 7.0. Igualmente voy a usar esa herramienta para futuros problemas. Muchas gracias y saludos!
Santino
