### ISSUE TITLE
Que paso con CSPEC ?

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3485]
Buenas, tengo una duda un poco general y es que me gustaria hacer algunos tests unitarios para el tp y yo habia visto que estaba en los docs subido un tutorial para usar CSPEC pero ahora veo que ese tutorial no esta mas y que ademas el makefile no tiene las reglas para testing que tenia antes. Esto se debe a que ya no recomiendan usar esa libreria para hacer tests unitarios o como va el asunto? Desde ya muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

La recomendación de cspec sigue estando y de hecho sigue viva la [página](https://docs.utnso.com.ar/guias/herramientas/cspec), pero se ve que ordenando el menú lateral se nos pasó el link.

Algo mucho muy importante es que no les recomendamos que se pongan a crear test unitarios si no están 100% seguros de lo que están haciendo, porque muchas veces ser mas papista que el papa solo genera que se terminen atrasando y por consecuencia, no llegan a terminar el tp 😢 

Saludos.-

**Comment by RaniAgus** [comment]
Holi 👋🏻 Es mi culpa, la guía que tenemos en la página está redactada para importarse en Eclipse y no llegué a tiempo a actualizarla para que matchee con el nuevo repo scaffold. Probablemente ya el próximo cuatri la tengamos lista y actualizada.

De todas formas, como dijo Dami, es una guía bastante avanzada. Los conceptos de unit testing se ven mucho más en profundidad en PdeP y DDS, así que si los tienen adquiridos de ahí probablemente esté buenísimo contar con ellos, pero en caso de no ser así nuestra recomendación es no entrar ahí. Suele pasar que uno arranque queriendo simular pruebas de **integración** con una herramienta que es para testeo **unitario** y se termine rompiendo la cabeza en hacer código de setup y teardown que no termine valiendo la pena. Además, el código debe estar bien modularizado, separando responsabilidades y armando buenas abstracciones, todas cuestiones que se ven por primera vez en PdeP, luego se mejoran notoriamente en DDS y optativamente les pueden dar un último golpe de horno en TADP. Al ser una materia de 2do año entendemos que es probable que muchas de estas cosas no las hayan visto.

Dicho todo esto, avisen si quieren unit testing configurado en el repo y cuando tenga tiempo les mandaré una PR con el setup que haga falta :)

Saludos
