### ISSUE TITLE
El kernel tiene PCB o solo PID?

### ISSUE THREAD

**Issue by tomipodo** [sisoputnfrba/foro#3486]
Hola! No entendíamos si el Kernel al ponerlo en la cola para planificar, se queda con todo el PCB o solo el PID. Ya que para planificar es más sencillo que tenga los PCBs de todos los procesos, pero en ese caso, no comprendemos porque la memoria tendría los PCBs también.
Saludos.

**Comment by iago64** [comment]
Buenas! Cómo va?

En que parte del enunciado nos quedó que la memoria tiene que tener los PCBs? 
No te estarás quedando con la visión de la teoría en donde todas las estructuras del kernel existen en memoria pero que en el TP lo simplificamos porque sería muy muy complejo y molesto que TODO tenga que estar en un módulo que van a poder tener funcionando para el final del cuatrimestre.

Saludos.-

**Comment by tomipodo** [comment]
Ah claro, perfecto. Sí, nos estábamos quedando con la teoría que decía que los PCBs están siempre en RAM pero en el TP nunca dice esto. Muchas gracias, saludos!
