### ISSUE TITLE
Conexiones a Memoria. Checkpoint 1

### ISSUE THREAD

**Issue by tenagliaFranco** [sisoputnfrba/foro#3487]
Buenos días,

estoy teniendo dudas sobre como encarar la conexión de los módulos con la memoria. Leí el Issue #3466, pero sigue sin quedarme claro. 

Según infiero del gráfico Arquitectura del Sistema, los tres módulos realizan peticiones a la memoria. Por otro lado, leyendo el enunciado, entiendo que el Kernel gestiona las peticiones: _“el Kernel será el encargado de gestionar las peticiones contra la Memoria…” (pág 9. Lineamientos e Implementación)._

Para cumplir los requerimientos del primer checkpoint, ¿debería conectar solo el Kernel (CLIENTE) a la Memoria (SERVIDOR) y los otros dos módulos realizaran peticiones a través del Kernel? 

En el caso de que se conecten directamente los tres módulos a la memoria, ¿debería reservar tres sockets, uno para cada módulo?

**Comment by iago64** [comment]
Buenas! Cómo va?

Para el primer checkpoint solo se necesitan las conexiones contra la memoria, después para el segundo checkpoint es cuando la memoria tiene que poder leer los scripts y pasar de a 1 línea (o instrucción)

Saludos.-

**Comment by tenagliaFranco** [comment]
Perfecto, muchas gracias!
