### ISSUE TITLE
Primer checkpoint

### ISSUE THREAD

**Issue by tomipodo** [sisoputnfrba/foro#3488]
Buenas. No sabemos si ya poner el tag del primer checkpoint, creemos que ya está, pero no estamos seguros. Qué pasa si el tag no cumple con lo pedido? Tendremos un feedback antes del 20/04 como para poder modificarlo?
Creemos que ya cumplimos lo solicitado pero no estamos seguros por el tema del protocolo. En cada modulo dejamos asentado que es lo que recibiría cada uno pero aún no está especificado en el código desde donde se enviará cada uno de los mensajes ya que la mayoría dependen de cosas que no forman parte de esta entrega, como por ejemplo: los mensajes relacionados a las IO (IO_FS_CREATE, IO_FS_TRUNCATE, etc.).
Gracias, saludos!

**Comment by RaniAgus** [comment]
¡Buenas! No se preocupen, tenemos en cuenta que en esta primera iteración el protocolo de comunicación que definan puede no estar _perfecto_, lo importante es que para esta instancia ya hayan definido uno y se puedan establecer las conexiones entre los distintos módulos.

En el único momento en el que requeriremos que el TP funcione exactamente igual a como está especificado en la entrega, cuando ya cuenten con un documento de pruebas para validar que esté funcionando todo bien y no se lleven ninguna sorpresa. Para los checkpoints, lo más importante es que hayan avanzado con lo especificado (con o sin bugs).

Saludos

**Comment by tomipodo** [comment]
Bárbaro! Y respecto a lo de aprobar los checkpoints, se corrijen antes de la fecha límite o al final de cuatrimestre? No me quedó claro. Por las dudas, si no llegase a estar aprobado.
Gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Si por antes de la fecha límite te referís a que los revisemos antes del día que tienen para presentarlo (Ej antes del 20/04 para el primer checkpoint) no es posible ya que seguramente muchos grupos estén generando el tag el mismo día (esto está permitido).

Muy posiblemente no podamos evaluarles mucho del TP "funcionando" ya que es un avance y como dijo Agus, no hay pruebas especificadas salvo las de la entrega final. La idea es que nos presenten que están avanzando con el TP y no que "por arte de magia" aparece el TP subido en 4 commits 1 semana antes de la entrega. 
Esto no quiere decir que si por ej, para el segundo check se pide que la memoria solo lea las instrucciones de los archivos y Uds. de manijas y porque leyeron el libro se mandaron a hacer las estructuras de memoria esté mal, al contrario, es un gol al ángulo en el minuto 89 que rompe el 0 a 0. 
La contraparte es que si crean un tag sin código o con el template que les dimos al crear el repo y bueno... todo muy lindo con el tag, pero eso va a ser algo que vamos a observar y posiblemente sea causal de que antes de la entrega final les llegue un mail preguntándoles que onda, por que hay 3 tags de un repo sin código.

Saludos.-

**Comment by tomipodo** [comment]
Buenas, listo nos quedamos más tranquilos entonces, gracias por la aclaración!
Saludos.
