### ISSUE TITLE
Duda con la ejecucion de los modulos

### ISSUE THREAD

**Issue by IanR4** [sisoputnfrba/foro#3489]
En el TP ya hicimos las conexiones entre el modulo kernel, cpu y memoria. El problema que nos surgio es que si corremos primero el modulo de kernel que lo definimos como cliente de cpu y memoria, y luego corremos los otros dos modulos, no se produce la conexion. En cambio si ejecutamos en otro orden, por ejemplo, memoria - cpu - kernel, si funciona. 
En la guia de sockets dice "si el servidor no está en accept(), connect() fallará y devolverá un error.". Supongo que ahi estaria la falla. Hay alguna forma de solucionarlo?

**Comment by RaniAgus** [comment]
¡Buenas! Es correcto, si no hay ningún proceso `bind()`eado al puerto, al intentar `connect()`arse se producirá un error de "connection refused"

La solución es, como bien mencionás, iniciar los procesos en orden :)

También si quieren podrían implementar una lógica de reintentos cada "n" segundos, pero para este TP no es necesario, al momento de correr las pruebas siempre vamos a iniciar los procesos en el orden que hayan establecido.

Saludos
