### ISSUE TITLE
Alternativa de visualBox

### ISSUE THREAD

**Issue by sofiimoguilner** [sisoputnfrba/foro#3491]
Buenas! Comento un poco del contexto, tengo como Sistema operativo ChromeOS. VistualBox no me va a correr directamente. Como soluciones encontre las siguiente pero no se por cual me convendria seguir: QEMU,KVM o usar GitHub codespace que me crea una VM en la nube. 

Desde ya gracias por la ayuda!

**Comment by RaniAgus** [comment]
Buenas, ¿cómo va? ¡Gracias por el aporte, @kenzogrosvald!

En cuanto al entorno gráfico, da lo mismo XFCE o cualquier otro, nosotros instalamos ese porque era de los más livianos que existe pero antes teníamos, si no me equivoco, un LXDE. Lo único que es crítico es si surge alguna diferencia entre versiones de `gcc`, aunque también suele ser un caso bastante borde.

@sofiimoguilner lamentablemente no tenemos ninguna seguridad de que vaya a funcionar, no recordamos otros casos de gente que trabaje con Chromebook y ninguno de los ayudantes tiene una como para probar, así que todo lo que podamos averiguar nos sirve un montón para contar como feedback y, idealmente, armar una guía al respecto que les quede para futuros alumnos.

Saludos

**Comment by sofiimoguilner** [comment]
Buenas! Hoy estuve viendo bastante cosas, los chicos hoy en las consultas tambien me re ayudaron. 

Estuve viendo este video y voy a ir por este lado como alternativa 

https://www.youtube.com/watch?v=1b4c6D7OTH0 

Desde ya muchas gracias por la ayuda  la paciencia!

**Comment by karengrams** [comment]
¡@sofiimoguilner!

¡Buenisimo! Cerramos el issue dado que duda fue resuelta. Muchisimas gracias por el update.

¡Besos!

Kar.-
