### ISSUE TITLE
Problema para compilar los modulos con Make

### ISSUE THREAD

**Issue by GRogani** [sisoputnfrba/foro#3492]
Buen dia, estuve intentando compilar los modulos del tp recien clonado y no me fue posible, ya que parece no encuentra la carpeta de los utils, perdon si es una duda muy tonta, pero no se trabajar con make files.

### 🔎 Búsqueda en foros

Busque en el foro informacion y encontre problemas similares pero no supe como utilizarlos para resolver mi 

### 🐛 Cómo reproducir el error

Simplemente instale las commons, clone el repo del tp y hice make a cada modulo y ninguno generaba el compilado binario.

### 💻 Logs
```
make --no-print-directory -C ../utils/ 3>&1 1>&2 2>&3 | sed -E 's,(src/)[^ ]+\.(c|h)\:,../utils/&,' 3>&2 2>&1 1>&3
mkdir -pv obj/utils/
mkdir: created directory 'obj'
mkdir: created directory 'obj/utils/'
gcc -g -Wall -DDEBUG -fdiagnostics-color=always -fPIC -c -o "obj/utils/hello.o" src/utils/hello.c -I./src
mkdir -pv bin/
mkdir: created directory 'bin/'
ar rcs -o "bin/libTP.a" obj/utils/hello.o
mkdir -pv obj/
mkdir: created directory 'obj/'
gcc -g -Wall -DDEBUG -fdiagnostics-color=always -c -o "obj/main.o" src/main.c -I../utils/src -I./src
mkdir -pv bin/
mkdir: created directory 'bin/'
gcc -g -Wall -DDEBUG -fdiagnostics-color=always -o "bin/TP" obj/main.o -I../utils/src -I./src -L../utils/bin -lutils -lcommons -lpthread -lreadline -lm
/usr/bin/ld: cannot find -lutils: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [makefile:39: bin/TP] Error 1
```

**Comment by RaniAgus** [comment]
¡Buenas! ¿Desde qué entorno estás codeando? Veo que hay algunas variables que se están definiendo de forma medio extraña.

Acá en vez de compilar un `libutils.a`, está compilando un `libTP.a`:

```
ar rcs -o "bin/libTP.a" obj/utils/hello.o
```

Y acá está intentando generar un ejecutable `TP` en vez de `kernel`/`memoria`/etc:
```
gcc -g -Wall -DDEBUG -fdiagnostics-color=always -o "bin/TP" obj/main.o -I../utils/src -I./src -L../utils/bin -lutils -lcommons -lpthread -lreadline -lm
```

Saludos

**Comment by RaniAgus** [comment]
PD: Esto parte de la variable `BIN` del makefile, que evalúa al nombre de la carpeta en donde se encuentra:

```
BIN = bin/$(shell cd . && pwd | xargs basename)
```

Si quisieras podrías editarla a manopla para que se llame igual que la carpeta que contiene el `makefile`, pero esto también me parece una señal de que quizás no estés desarrollando el TP desde en un [entorno Linux](https://docs.utnso.com.ar/primeros-pasos/entorno-linux)

**Comment by GRogani** [comment]
Hola Agus gracias por responder, estoy haciéndolo todo desde la máquina virtual en Linux que nos pasaron y el ide es visual code probé por consola y mediante la pestaña debugg de vsc, y no cambie nada así como generaron el repo lo clone e intenté hacerle make a cada módulo. Que puedo hacer?

**Comment by RaniAgus** [comment]
Creo que un fix rápido sería editar esa variable `BIN` en cada `makefile` para que diga en cada módulo lo que se espera compilar, por ejemplo en kernel:

```mk
BIN = bin/kernel
```

Y en las utils, al ser una library, el formato es un toque distinto:

```mk
BIN = bin/libutils.a
```

Me hace mucho ruido que necesites hacerlo, ya que varios compañeros han arrancado con el TP en el mismo entorno y pudieron compilar sin problemas. De todas formas, lo tendremos en cuenta y, en caso de que surjan más casos similares, veremos si es necesario hacerle un fix a esa línea para futuros cuatris 👍🏻

**Comment by GRogani** [comment]
Solucionado gracias Agus!, tendrá algo que ver con que cree una carpeta "TP SO" en el escritorio y dentro de esta clone el repo, las commons las instale desde ahí también? me queda la duda porque no entiendo bien que hace esta línea
`$(shell cd . && pwd | xargs basename)`.

**Comment by RaniAgus** [comment]
Ahhh es muy probable! En general Linux se lleva **muy** mal con las carpetas y archivos que tienen espacios, ya que suele ser un separador muy común. Probablemente `basename` te esté tomando la parte de `/home/utnso/TP` como primer parámetro y la parte de `SO/tp-2024-1c/etc/etc` como un segundo parámetro que lo termina descartando.

Me lo anoto para tenerlo en cuenta y ver algún posible workaround. ¡Gracias por notarlo!

Si no quedan más dudas pueden cerrar el issue. Saludos

**Comment by RaniAgus** [comment]
PD: `$(shell ...)` es una función de make que te permite ejecutar comandos por consola y devolver su output :)

**Comment by GRogani** [comment]
Muchas gracias Agus!

**Comment by RaniAgus** [comment]
Estuve viendo cómo resolverlo y encontré un fix: se soluciona reemplazando la parte que dice `$(shell cd . && pwd | xargs basename)` por `$(shell pwd | xargs -I{} basename "{}")`, ya que al encerrar el parámetro entre comillas `basename` puede recibir la ruta correctamente.
