### ISSUE TITLE
Como manejar las conexiones de los modulos servidor

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3494]
Hola, como va? tenemos una duda sobre como hacen los modulos que hacen tipo de servidores para manejar las conexiones. La duda es si, por ejemplo cuando el kernel se conecta a la cpu o a la memoria o cuando una interfaz E/S se conecta con el kernel, hay que mantenerla viva esa unica conexion? o por cada send que hago tengo que conectarme devuelta?

### 💭 Soluciones posibles
Ejemplo con pseudocodigo:
Si mantuviese viva la conexion seria algo como:
```
    socket1 = connect()
    send(socket1,unNumero)
    send(socket1,Unapersona)
```
Si no la mantuviese:
```c
   socket1 = connect()
   send(socket1,unNumero)
   close(socket1)
   socket1 = connect()
   send(socket1,Unapersona)
   close(socket1)
```
Saludos cordiales y espero se entienda la pregunta

**Comment by iago64** [comment]
Buenas! Cómo va?

En este enunciado no se aclara como se tienen que manejar las conexiones, con lo cual pueden crear una conexión inicial y mantenerla a lo largo de la ejecución y hacer todos los `send()` y `recv()` que necesiten.

Saludos.-

**Comment by GonTurri** [comment]
gracias por la pronta respuesta
