### ISSUE TITLE
Error con las commons

### ISSUE THREAD

**Issue by lseijasferraudo** [sisoputnfrba/foro#3495]
Estoy haciendo el tp0 pero al momento de querer compilar no funciona como deberia, no se a que se debe
### 📔 Citas del enunciado/videos

```
tarting build...
/usr/bin/gcc-11 -fdiagnostics-color=always -g /home/utnso/tp0/client/src/client.c -o /home/utnso/tp0/client/src/client
/home/utnso/tp0/client/src/client.c: In function ‘iniciar_logger’:
/home/utnso/tp0/client/src/client.c:59:26: warning: assignment to ‘t_log *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
   59 |         if (nuevo_logger =log_create("tp0.log", "tp0", true, LOG_LEVEL_INFO) == NULL ){
      |                          ^
/usr/bin/ld: /tmp/ccL0ilWq.o: in function `main':
/home/utnso/tp0/client/src/client.c:22: undefined reference to `log_info'
/usr/bin/ld: /tmp/ccL0ilWq.o: in function `iniciar_logger':
/home/utnso/tp0/client/src/client.c:59: undefined reference to `log_create'
/usr/bin/ld: /tmp/ccL0ilWq.o: in function `leer_consola':
/home/utnso/tp0/client/src/client.c:77: undefined reference to `readline'
/usr/bin/ld: /tmp/ccL0ilWq.o: in function `terminar_programa':
/home/utnso/tp0/client/src/client.c:104: undefined reference to `log_destroy'
collect2: error: ld returned 1 exit status

Build finished with error(s).

 *  The terminal process terminated with exit code: -1. 
 *  Terminal will be reused by tasks, press any key to close it. 
 ```
me tira eso por la consola
![error](https://github.com/sisoputnfrba/foro/assets/87786118/7223a0fd-b1c6-4a3d-beb8-8f71b6d404e2)

**Comment by iago64** [comment]
Buenas! Cómo va?

Podrías pasarnos el código que te esta diciendo gcc que no puede compilar? Ya que el error te dice por ejemplo que no tiene referencias a las funciones de `log_create`, `log_destroy`, `log_info` y `readline`, pero esto puede deberse a falta de algunos `#include` o a que por ejemplo no abriste la carpeta del tp0 como se indica en la [etapa de setup inicial de la guía del tp0](https://docs.utnso.com.ar/primeros-pasos/tp0#etapa-1-setup-inicial) 

Saludos.-

**Comment by lseijasferraudo** [comment]
ya lo pude solucionar después de hablar con unos compañeros
había abierto mal el archivo ya que yo hacia un "code ." en vez de abrirlo desde visual studio con "open Workspace from file..."
