### ISSUE TITLE
Como manejar que un mismo programa sea cliente y servidor en distintas comunicaciones?(para checkpoint 1) 

### ISSUE THREAD

**Issue by Lisandrogq** [sisoputnfrba/foro#3496]
Buenass! traigo una duda respecto a como definir incialmente cada modulo(en particular Kernel y cpu).

En el caso del Kernel, este actua como cliente para la memoria pero como servidor para las interfaces IO. Creo que, en etapas futuras, esto se debería manejar con threads, pero para el checkpoint 1 ¿Como deberíamos trabajar estas dos posibilidades?

![image](https://github.com/sisoputnfrba/foro/assets/69394660/71f19f82-c8c3-49d9-ad4b-9e6782ba2942)

💭 Soluciones posibles:
Dentro del Modulo Kernel crear dos archivos, uno donde esté la logica del rol de servidor y otro para el rol de cliente, de esta forma podemos definir los protocolos para cada conexion y mas adelante, cuando veamos threads, unificar todo en un archivo.

**Comment by iago64** [comment]
Buenas! Cómo va?

La idea de los hilos es la mas correcta.
En este checkpoint 1 como la idea es que los procesos se conecten nomas y puedan hacer un handshake, podrían por ejemplo levantar las conexiones cliente del Kernel y después iniciar el servidor como para decir, bueno, ya tengo todo listo para laburar.

Después a futuro si estas conexiones pueden, y casi seguro, que necesiten empezar a separarlas en hilos.

Respecto a los archivos, no hay una única estructura que funcione, ahi siéntanse libres de seguir lo que su instinto les indique, solo les recomendamos que traten de hacer funcione acotadas para no quemarse la cabeza después siguiendo código spaghetti. 

Saludos.-

**Comment by Lisandrogq** [comment]
Perfecto Damian, muchas gracias por la rapida respuesta
