### ISSUE TITLE
VScode no detecta netdb.h ni puede encontrar utils/hello.h

### ISSUE THREAD

**Issue by marianoSLamaison** [sisoputnfrba/foro#3497]
VScode no puede encontrar netdb.h ni tampoco utils/hello.h pero mis compañeros dicen que a ellos ninguna de estas les dio ningún problema, y que pueden compilar normalmente. No tenia este problema en el tp0 pero ahora me aparece en el tp grupal.
### 🔎 Búsqueda en foros

Aqui tubieron un problema similar pero lo aparentemente trabajan solo con compilador directamente a si que no se como aplicar la solucion a vscode: https://stackoverflow.com/questions/7571870/netdb-h-not-linking-properly
Tambien leì esta pero aparentemente segun uno de los usuarios el error ya no deberia existir y la solucion de agregar _GNU_SOURCE no me funciono:
https://github.com/Microsoft/vscode-cpptools/issues/2025 ( no encontre la issue de este foro donde linkeaban a esta issue )
### 📝 Pasos para reproducir el error

Mi proceso para intalar las VMs fue el siguiente:
Descargue las VM's, las puse en un folder de mi escritorio, chequee la integridad de las descargas, las desempaque, siguiendo el video (exceptuando la que dice grafica.zip.002 dado no puedo desempaquetarla y al cambiar su nombre por un .zip normal, la computadora me dice que esta dañado) prosegui a instalar virtual vox, correr la virtual box grafica, y instalar las guest additions seguido de las commons. Cuando abro vs code para editar algo y doy a run vscode me pregunta cual de todos los compiladores quiero usar y le digo que quiero usar el primero ( el que empieza desde  usr).

### 💻 Logs

`fatal error: utils/hello.h: No such file or directory` y no lo tengo aqui pero con respecto a `struct addrinfo` me decia que era un "inclomplete type"

**Comment by RaniAgus** [comment]
¡Buenas! ¿Nos podrías pasar el output completo al momento de ejecutar?

[![image](https://docs.utnso.com.ar/img/primeros-pasos/primer-proyecto-c/vscode-copy-compiler-output.gif)](https://docs.utnso.com.ar/primeros-pasos/primer-proyecto-c#errores-de-compilacion)

También me llama la atención que VSCode te pregunte por el compilador a usar ya que no tiene por qué saberlo: la build task solo se encarga de ejecutar `make all` en la carpeta.

Saludos

**Comment by marianoSLamaison** [comment]
Buenas, perdón la tardanza. 
Este es todo el output de la consola cuando intente correr el modulo de memoria

 *  Executing task: C/C++: gcc-11 build active file 

Starting build...
/usr/bin/gcc-11 -fdiagnostics-color=always -g /home/utnso/Desktop/utnSO/tp-2024-1c-Palawarriors/memoria/src/main.c -o /home/utnso/Desktop/utnSO/tp-2024-1c-Palawarriors/memoria/src/main
/home/utnso/Desktop/utnSO/tp-2024-1c-Palawarriors/memoria/src/main.c:3:10: fatal error: utils/hello.h: No such file or directory
    3 | #include <utils/hello.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.

Build finished with error(s).

 *  The terminal process failed to launch (exit code: -1). 
 *  Terminal will be reused by tasks, press any key to close it. 

 *  Executing task: C/C++: gcc-11 build active file 

Starting build...
/usr/bin/gcc-11 -fdiagnostics-color=always -g /home/utnso/Desktop/utnSO/tp-2024-1c-Palawarriors/memoria/src/main.c -o /home/utnso/Desktop/utnSO/tp-2024-1c-Palawarriors/memoria/src/main
/home/utnso/Desktop/utnSO/tp-2024-1c-Palawarriors/memoria/src/main.c:3:10: fatal error: hello.h: No such file or directory
    3 | #include <hello.h>
      |          ^~~~~~~~~
compilation terminated.

Build finished with error(s).

 *  The terminal process failed to launch (exit code: -1). 
 *  Terminal will be reused by tasks, press any key to close it. 

 
Starting build...
/usr/bin/gcc-11 -fdiagnostics-color=always -g /home/utnso/Desktop/utnSO/tp-2024-1c-Palawarriors/memoria/src/main.c -o /home/utnso/Desktop/utnSO/tp-2024-1c-Palawarriors/memoria/src/main
/home/utnso/Desktop/utnSO/tp-2024-1c-Palawarriors/memoria/src/main.c:3:10: fatal error: utils/hello.h: No such file or directory
    3 | #include <utils/hello.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.

Build finished with error(s).

 *  The terminal process terminated with exit code: -1. 
 *  Terminal will be reused by tasks, press any key to close it. 

 
Starting build...
/usr/bin/gcc-11 -fdiagnostics-color=always -g /home/utnso/Desktop/utnSO/tp-2024-1c-Palawarriors/memoria/src/main.c -o /home/utnso/Desktop/utnSO/tp-2024-1c-Palawarriors/memoria/src/main
/home/utnso/Desktop/utnSO/tp-2024-1c-Palawarriors/memoria/src/main.c:3:10: fatal error: utils/hello.h: No such file or directory
    3 | #include <utils/hello.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.

Build finished with error(s).

 *  The terminal process failed to launch (exit code: -1). 
 *  Terminal will be reused by tasks, press any key to close it. 

 
Starting build...
/usr/bin/gcc-11 -fdiagnostics-color=always -g /home/utnso/Desktop/utnSO/tp-2024-1c-Palawarriors/memoria/src/main.c -o /home/utnso/Desktop/utnSO/tp-2024-1c-Palawarriors/memoria/src/main
/home/utnso/Desktop/utnSO/tp-2024-1c-Palawarriors/memoria/src/main.c:3:10: fatal error: utils/hello.h: No such file or directory
    3 | #include <utils/hello.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.

Build finished with error(s)

**Comment by RaniAgus** [comment]
¡No hay problema! Me parece que estás teniendo un problema muy parecido al de este issue: https://github.com/sisoputnfrba/foro/issues/3435

Leelo y avisanos y pudiste solucionarlo. Saludos :)

**Comment by marianoSLamaison** [comment]
Para el registro. El problema parece haberse solucionado re abriendo el proyecto de la manera que especifican en la issue #3435 
y cuando vs code te pregunte por compilador a usar, tu solo ignoras la pregunta y vas directo a la opción que dice "run".
Muchisimas gracias.
