### ISSUE TITLE
Path del pseudocódigo

### ISSUE THREAD

**Issue by tomipodo** [sisoputnfrba/foro#3498]
Buenas! Qué tal? Queríamos saber como se va a mandar el path del pseudocódigo cuando se ejecuta el comando INICIAR_PROCESO [PATH]. Ya que dependiendo de si la ruta (absoluta o no), la manera de encontrarlo en el módulo memoria es diferente. Gracias!

**Comment by FredeHG** [comment]
Hola buenas! Ustedes deciden donde dejar los archivos de pseudo código (en la misma maquina donde este ejecutando memoria) y ustedes definen como enviar el `path` si solamente el nombre y con eso ya saben en que carpeta o toda la carpeta

Lo mismo aplica para el script de instrucciones con la diferencia que este debe estar en la maquina en la que ejecuta el kernel

Si esta respuesta es suficiente, por favor cerraremos el issue.
Saludos!

**Comment by tomipodo** [comment]
Listo, excelente! Muchas gracias
