### ISSUE TITLE
⚽ Mercado de pases ⚽ Busca grupo o integrantes para completar tu grupo.

### ISSUE THREAD

**Issue by iago64** [sisoputnfrba/foro#3499]
Buenas! Cómo va?

Habiendo cerrado las inscripciones como les habíamos comentado, damos inicio a la etapa de cambios de grupos.
La idea de este thread es el de tener un único punto de encuentro para unificar las búsquedas de integrantes y/o grupos.
Tengan en cuenta que los cambios están limitados a **uno por persona**, por lo que sean conscientes antes de pedir los mismos y traten siempre de hablar las situaciones antes de llegar a considerar el cambio.

Les recordamos que este foro es público y por lo tanto les recomendamos NO publicar números de celular o links a grupos de WhatsApp ya que cualquier persona incluso fuera de la UTN puede llegar a obtener su información.

Como de costumbre, cualquier inconveniente con los cambios de grupos envíen un mail a [inscripciones@utnso.com.ar](mailto:inscripciones@utnso.com.ar)

Fecha de cierre de cambios: **15/06**

Saludos!

**Comment by ivysdll** [comment]
Buenas! Qué tal va todo? 

Tenemos un equipo de 3 integrantes actualmente, se nos dieron de baja 2 personas hace poco y estamos buscando remplazos. Cualquier duda que tengan o interesado me puede escribir. Gracias!

**Comment by lperezpersico** [comment]
holiii, se nos bajó un compañero y estábamos buscando a alguien más. Si a alguien le falta grupo me manda por acá o por mail: lperezpersico@frba.utn.edu.ar 
Gracias!!

**Comment by matefernandezcc** [comment]
Buenas en mi grupo se nos dio de baja una persona, somos 4 si alguien no tiene grupo y le interesa unirse mandenme un mail: mfernandezcruz@frba.utn.edu.ar

**Comment by matefernandezcc** [comment]
Buenas en mi grupo se nos dio de baja una persona, somos 4 **si alguien no tiene grupo y le interesa unirse mandenme un mail**: [mfernandezcruz@frba.utn.edu.ar](mailto:mfernandezcruz@frba.utn.edu.ar)

Gracias!

**Comment by StephieOrtiz** [comment]
Buen dia! Se nos bajó un compañero de nuestro grupo, somos 4 actualmente.
Si alguien no tiene grupo y quisiera unirse puede enviarme un mail a stortiz@frba.utn.edu.ar   
 
Gracias!

**Comment by CabreraGE** [comment]
Buenas tardes, hay algun grupo al que le falten integrantes del K3213 (sabado a la mañana) ya que no logro unirme al grupo en el que estoy esperando que habiliten los cambios y no quisiera perder mas tiempo.
Por favor si hay alguno sin grupo de la misma comision me avisan asi me sumo?

gcabrera@frba.utn.edu.ar 
Gracias.-

**Comment by ThiagoPerez12** [comment]
Buenas, se nos bajo un integrante de nuestro grupo y somos 4. Si alguien esta sin grupo y quiere unirse escribame porfi thperez@frba.utn.ar

**Comment by alejandroriedel** [comment]
Buenas, se bajó un integrante así que estamos buscando reemplazo. Si alguien quiere unirse, por favor enviar mail a alejandro.riedel@frba.utn.edu.ar.

**Comment by NicolasPazz** [comment]
Buenas, se nos bajó un integrante, somos 4. Buscamos un reemplazo.
npaz@frba.utn.edu.ar

**Comment by Marco230497** [comment]
Buenas se nos bajo un integrante, si quieren unirse al grupo mande un mail
mdelgadojapa@frba.utn.edu.ar

**Comment by MirkoPeschel** [comment]
Hola perdimos un integrante del grupo y somos 4, si buscas grupo mándame por acá o por mail: mpeschel@frba.utn.edu.ar

**Comment by milagrosvera** [comment]
Holaa,
 Estamos buscando un integrante , somos 4 y cursamos los sábados a la mañana. Si necesitan grupo mandenme por mail: mveraoliver@frba.utn.edu.ar

**Comment by jkarabin** [comment]
Hola, estamos buscando un integrante, somos 4 personas y una ya curso la materia. 
Cursamos los martes a la noche (2 integrantes), lunes noche (1) y sábado a la tarde (1).
Contacto: jkarabin@frba.utn.edu.ar

**Comment by fnacevedo** [comment]
Buenas!

Se busca 5to integrante comprometido con la materia, con posibilidad de juntarse semanalmente(virtual) una o dos veces.  Ya tenemos hecho el primer checkpoint del TP.

fegnus@frba.utn.edu.ar

**Comment by LucianoKremer** [comment]
Buenas! 
Así como la gran mayoría, estamos buscando un integrante, ya que se nos dio uno de baja. Estamos cerrando el checkpoint 2. Querríamos alguien con tiempo a disposición y ganas de trabajar (no estaría mal si tiene también paciencia y buena onda). Saludos!

Contacto: lkremer@frba.utn.edu.ar

**Comment by santiparis** [comment]
Hola, mi grupo se disolvió así que estoy buscando vacantes en algún otro. Soy de K3055 de los sábados a la tarde. Cualquier cosa háblenme por acá sparispuebla@frba.utn.edu.ar

gracias

**Comment by MendezTomasI** [comment]
Buenas, estamos buscando un ultimo integrante ya que se bajo uno y somos 4 por el momento.
Si te falta grupo, escribime a tmendez@frba.utn.edu.ar

**Comment by Fabian2112** [comment]
> Buenas! Qué tal va todo? 
> 
> Tenemos un equipo de 3 integrantes actualmente, se nos dieron de baja 2 personas hace poco y estamos buscando remplazos. Cualquier duda que tengan o interesado me puede escribir. Gracias! 

Hola. Siguen en busqueda? Somos 2 que  estamos buscando porque se nos bajaron 3.

**Comment by Oshiro28** [comment]
Buenas, estamos buscando un último integrante, recién se cambio de grupo uno de nuestros integrantes. 
Somos del curso K3254, cursamos los miércoles a la noche y los sábados por la tarde, es la primera vez que cursamos esta materia, así que sí hay algún recursante o no que se quiera sumar bienvenido. Si alguien esta interesado me puede enviar un mail: joshirotaipe@frba.utn.edu.ar

**Comment by Cielo418** [comment]
Buenas, 
Nuestro 5to integrante se dio de baja y estamos en la búsqueda de un integrante para completar el grupo. 
Si alguno está interesado me puede escribir a mi mail jcabreragonzalez@frba.utn.edu.ar

**Comment by benitezcamila** [comment]
Hola! nos falta un integrante. Somos 4 que estamos cursando tercer año, le ponemos onda al TP y buscamos alguien con ganas de comprometerse y aprobarla este cuatrimestre, idealmente que haya aprobado pdep y ayed. Si están interesados me pueden escribir a cabenitez@frba.utn.edu.ar

**Comment by Utngibber** [comment]
Hola somos 2(1 sabado a la mañana y 1 sabado a la tarde) se nos bajaron 3 integrantes, si hay un grupo que le falten 2 me pueden hablar por el email  misoto@frba.utn.edu.ar

**Comment by BrunoBarlari** [comment]
# Buscamos 1 Integrante
Somos un grupo de *4 integrantes* con algunos recursantes, se nos acaba de bajar uno del grupo y tenemos un cupo libre. 
**Trabajamos a buen ritmo casi todos los dias!**

Si te interesa escribime a mi mail: 
bbarlari@frba.utn.edu.ar

**Comment by Cynthia-21** [comment]
Hola chicos, estamos buscando un integrante para nuestro grupo, se nos acabó de bajar uno. Estamos bien organizados para la siguiente entrega.
Si alguno está interesando les dejo mi mail: cabbate@frba.utn.edu.ar

**Comment by Tomas-Perez** [comment]
Buenas gente, estamos buscando un ultimo integrante para nuestro grupo. 
Si hay alguien interesado por favor escribir a este mail
[`toperez@frba.utn.edu.ar`](url)

**Comment by alex-claure-m** [comment]
Buenas tardes gente, estamos buscando un integrante, debido a que se dio de baja uno del nuestro. No importa si es de cualquier comision o si es la primera vez que cursa , lo importante es dedicarle al tp, la materia y aprender todos a la par.  Estamos en camino, realizando el 2do checkpoint. si estas interesado, dejo el siguiente mail para comunicarse: alexclauremontecinos@frba.utn.edu.ar

**Comment by JoaquinCoaricona** [comment]
Hola buenas. Estamos buscando un integrante para el grupo porque uno se nos dio de baja. Estamos con el tp encaminado para el checkpoint 2. Si les interesa les paso mi mail: ncoariconacruz@frba.utn.edu.ar

**Comment by nicoopenna** [comment]
Buen día, como están?
Estamos buscando 2 integrantes para nuestro grupo dado que tuvimos bajas, venimos con un buen avance y trabajo en equipo así que cualquiera interesado me puede escribir a npenna@frba.utn.edu.ar
Cursamos Miércoles noche  Sábado tarde (2) y sábados mañana (1).

**Comment by Cynthia-21** [comment]
Hola chicos, cómo están? Estamos buscando un integrante para nuestro equipo ya que se bajo uno de ellos! Estamos armando todo para el checkpoint 2. Si estás interesado/a mándame un mail a cabbate@frba.utn.edu.ar

**Comment by MGAzario** [comment]
Buenas, estamos buscando un integrante para nuestro grupo. Mi mail es mazario@frba.utn.edu.ar

**Comment by facu777** [comment]
Buenas me estoy quedando practicamente sin grupo. Alguien necesita un integrante para su grupo?

**Comment by JoaquinCoaricona** [comment]
> Buenas me estoy quedando practicamente sin grupo. Alguien necesita un integrante para su grupo?

Buenas en nuestro grupo tenemos lugar. Ya tenemos casi todo terminado para el checkpoint 2. Mi mail es ncoariconacruz@frba.utn.edu.ar por si te interesa

**Comment by Lucas-Olivares** [comment]
Buenas, me quedé sin grupo y estoy buscando otro. Cualquier cosa mi mail es lolivareschang@frba.utn.edu.ar

**Comment by SerattiTomas** [comment]
Buenas gente! estamos buscando un integrante para nuestro grupo, somos 4 personas.
Cursamos los martes a la noche (2 integrantes), lunes noche (1) y sábado a la tarde (1).
Contacto: [tseratti@frba.utn.edu.ar](mailto:tseratti@frba.utn.edu.ar)

**Comment by MercedesdelaTorre** [comment]
Buenas! Se nos bajaron 3 del grupo. Somos dos que no consideramos dejar la materia. Mi mail es mdelatorre@frba.utn.edu.ar

**Comment by saporapo** [comment]
Buenas! Tenemos un equipo de 4 integrantes, se nos dio de baja 1 persona hace poco y estamos buscando su remplazo en el módulo Memoria (tenemos una organización por módulos, pero nos ayudamos entre sí). Si hay algún interesado me puede escribir por [somunoz@frba.utn.edu.ar](url) Gracias!

**Comment by Facundo-Su** [comment]
Buenas, somos 4 en el grupo, se nos bajó uno, por el momento vamos con la entrega 3 del tp , necesitamos uno más para implementar la parte de entrada de salida. sí hay algún interesado pueden mandarnos mail.
mmaurino@frba.utn.edu.ar
fsu@frba.utn.edu.ar

**Comment by juaniagui** [comment]
Buenas, en mi grupo quedamos solamente 2 integrantes y estamos buscando unirnos a otro grupo ya que no queremos recursar la materia(ya la recursamos una vez).Mi mail es: juaaguirre@frba.utn.edu.ar

**Comment by JuanLyna** [comment]
Buenas, buscamos 3 integrantes ya que los de4 nuestro equipo de bajó de la materia, Gente que quiera aprobar esta materia y que TENGA TIEMPO  de meterle, si vienes a probar y sin nada hecho por favor pasa de largo. Cualquier cosa me escriben al mail jlunarumualdo@frba.utn.edu.ar

**Comment by VinixHub** [comment]
Buenaos días/tardes/noches a quien haya llegado a mi mensaje!
Tristemente se nos bajó un integrante del grupo, por lo que buscamos integrar a una única persona a éste.
- 3 de nosotros estamos en las comisiones K3213 y K3013 (_sábados a la mañana_).
- 1 de nosotros está en la comisión K3051 (_lunes a la noche_).
Les dejo mi mail para que se comuniquen!: fvinitzca@frba.utn.edu.ar

**Comment by MendezTomasI** [comment]
Buenas, se bajaron dos integrantes de la cursada y quedamos tres en el grupo.
Si alguien le interesa sumarse, mi mail es: tmendez@frba.utn.edu.ar

**Comment by LucianoSantinoValenzuelaMaltas** [comment]
Hola buenas, se nos bajaron 2 compañeros del equipo, y nos quedamos 3. Nuestra prioridad es conseguir 2 integrantes nuevos, aunque estamos abiertos a la posibilidad de dividirnos, en el caso de no consumarse ninguna otra propuesta.
eMail de contacto: lvalenzuelamaltas@frba.utn.edu.ar

**Comment by matiasnu** [comment]
Hola buenas, se nos bajo 1 compañera del equipo y quedamos 4. Queremos incorporar a un recursante que tenga experiencia con el TP para llegar tranquilos a la entrega final. Venimos cumpliendo con los checkpoints asi que el que sume tiene que tener tiempo para meterle al TP y estar comprometido.
Si a alguien le interesa del dejo mi mail: matnunez@frba.utn.edu.ar

**Comment by Cynthia-21** [comment]
Hola chicos, estamos buscando un integrante para nuestro grupo! ☺️ Si están interesados me pueden mandar un mail a cabbate@frba.utn.edu.ar

**Comment by lperezpersico** [comment]
Hola! Estamos buscando un integrante para nuestro equipo ya que se nos bajó uno, dejo mi mail por si alguno está interesado lperezpersico@frba.utn.edu.ar

**Comment by FelipeRuizDiaz** [comment]
Hola a todos! ¿Cómo va? 

Lamentablemente se nos bajo un compañero del equipo del tp y quedamos 4 personas.
Venimos bastante bien con la cursada teorica y llegamos al checkpoint 2 con todo bien planteado salvo el cpu.

Estamos en la búsqueda de un integrante que tenga ganas de formar un buen ambiente de trabajo y que tenga tiempo para hacerlo. No hace falta que seas un genio en programación, pero sí que te comprometas con el equipo. 

Si a alguno le interesa sumarse, pueden contactarnos al siguiente mail:
fruizdiaz@frba.utn.edu.ar

**Comment by daltplusplus** [comment]
Hola a todos!

Estamos al dia con el tp y andamos buscando 2 integrantes. 

Si alguno se quiere sumar por favor mandeme un mail a dlopeztapia@frba.utn.edu.ar

**Comment by AylenAnchart** [comment]
Buenas! Como va? Estamos buscando dos integrantes para nuestro grupo, ya que dejaron la materia. Preferentemente recursantes.
Dejo mi correo: ayanchart@frba.utn.edu.ar

**Comment by abmango** [comment]
Qué tal, con un compañero estamos buscando un grupo que le falten 2 integrantes para poder continuar el tp, ya que en el nuestro sólo quedamos 2.
Dejo mi correo: alexi@frba.utn.edu.ar

**Comment by marianonahuelbruno** [comment]
Buenas, se nos bajo uno del grupo y estamos buscando otro integrante antes de que termine el periodo de pases Si tenes ganas de trabajar en equipo y meterle onda al tp mandame mail: marbruno@frba.utn.edu.ar

**Comment by SantiagoDopazo** [comment]
Buenas somos 3 es probable que seamos 2, estamos buscando otro intregante al menos 1 que se cope y tenga ganas de aprobar la materia. Nos gustaria que se centre en I/O o nos ayude a terminar el Kernel.
mail: sadopazo@frba.utn.edu.ar

**Comment by valensilva** [comment]
Buenas, estamos buscando un integrante para nuestro grupo ya que se bajo uno, les dejo mi mail valsilva@frba.utn.edu.ar

**Comment by baroloagustin** [comment]
Buenas, estamos buscando 2 integrantes que puedan sumarse para terminar el tp. 
Tenemos los 2 primeros checkpoints y nos falta terminar el modulo de memoria para  el tercero. Dejo mi mail. abarolo@frba.utn.edu.ar
 Saludos cordiales.

**Comment by BenjaminAlegre** [comment]
Buenas, con una compañera estamos buscando un grupo que le falten 2 integrantes para continuar el tp.
Mi correo: balegrerocha@frba.utn.edu.ar

**Comment by Facundo-Su** [comment]
Buenas, se nos bajó un integrante, buscamos a un integrante más para colaborar con el módulo IO entrada salida.si hay algún interesado mándanos un mail
mmaurino@frba.utn.edu.ar
fsu@frba.utn.edu.ar

**Comment by NazarenoLopez** [comment]
Buenas, estamos buscando 1 integrante para terminar el TP, tenemos todo bastante encaminado :-). 
Mi mail es nlpezzmijak@frba.utn.edu.ar

**Comment by esigma5** [comment]
Hola, soy Esteban y busco grupo. Este es el liugar adecuado? 🤔

**Comment by iago64** [comment]
@esigma5 Cómo va? Yo también  estoy buscando grupo, pero creo que acaban de crear un nuevo issue, te lo dejo, cualquier cosa mandame un mail y charlamos para armar grupo!

https://github.com/sisoputnfrba/foro/issues/4228

Abrazo!
