### ISSUE TITLE
SEGMENTATION FAULT AL EXTRAER DEL BUFFER RECIBIDO

### ISSUE THREAD

**Issue by nicolasreypc** [sisoputnfrba/foro#3500]
Buenas, estoy teniendo un fallo de segmentacion al querer extraer informacion de un stream que recibo en memoria desde el kernel, ya revise las funciones, el tamaño de los buffers mientras compilaba y no hay caso. Puedo extraer todo antes de serializarlo y mandarlo, pero luego en el modulo de memoria no puedo por mas que el size del buffer sea el mismo que en el kernel.

------parte kernel---------------
`t_buffer* buffer = crear_buffer();
        printf("Ingresaste: %s\n", comando_consola[1]);
        uint16_t pid = asignar_pid();
        cargar_uint16_al_buffer(buffer, pid);
        cargar_string_al_buffer(buffer, comando_consola[1]);

        // Imprimir
        uint16_t cargadoint = extraer_uint16_al_buffer(buffer);
        char* cargadostring = extraer_string_al_buffer(buffer);

        printf("PID en buffer: %hu\n", cargadoint);            
        printf("Path en buffer: %s\n", cargadostring);

        cargar_uint16_al_buffer(buffer, pid);
        cargar_string_al_buffer(buffer, comando_consola[1]);

        t_paquete* a_enviar = crear_paquete (INICIAR_PROCESO, buffer); // [PID] [PATH]
    
        enviar_paquete(a_enviar, fd_memoria);
        
        destruir_paquete(a_enviar);`
        
        --------------------parte memoria------------
        ` INICIAR_PROCESO:
                // Recibir el tamaño del buffer
                int size_of_stream = recibir_size_del_buffer(fd_kernel);
                
                t_buffer* buffer_recibido = crear_buffer();
                buffer_recibido -> size = size_of_stream;
                buffer_recibido->stream = malloc(size_of_stream);

                //recibo el buffer, teniendo como dato su tamanio
                if (recv(fd_kernel, buffer_recibido -> stream, size_of_stream, MSG_WAITALL) != size_of_stream ){
                perror("Error al recibir el buffer");
                exit(EXIT_FAILURE);
                }

                uint16_t pid_recibido = extraer_uint16_al_buffer (buffer_recibido);
                char* path_recibido = extraer_string_al_buffer (buffer_recibido);
            
                // Imprimir
                printf("SE RECIBIO: %hu\n", pid_recibido);            
                printf("SE RECIBIO: %s\n", path_recibido);`
                
               -------------------funciones shared involucradas------------
               `void* extraer_choclo_al_buffer(t_buffer* un_buffer) {
    // Verificar si el buffer está vacío
    if(un_buffer->size == 0) {
        printf("\n[ERROR] Al intentar extraer contenido de un t_buffer vacio\n\n");
        exit(EXIT_FAILURE);
    }
    // Verificar si el tamaño del buffer es negativo (lo cual sería inusual y un error)
    if(un_buffer->size < 0) {
        printf("\n[ERROR] Esto es raro. El t_buffer contiene un size NEGATIVO\n\n");
        exit(EXIT_FAILURE);
    }

    // Obtener el tamaño del dato del buffer
    int size_choclo;
    memcpy(&size_choclo, un_buffer->stream, sizeof(int));  //EL PROBLEMA DE SEGM ESTA AQUI <--------------------------------------
    
    // Asignar memoria para el dato
    void* choclo = malloc(size_choclo);
    if(choclo == NULL) {
        perror("Error al asignar memoria para choclo");
        exit(EXIT_FAILURE);
    }
    
    // Copiar el dato desde el buffer
    memcpy(choclo, un_buffer->stream + sizeof(int), size_choclo);

    // Calcular el nuevo tamaño del buffer después de extraer el dato
    int nuevo_size = un_buffer->size - sizeof(int) - size_choclo;
    
    // Verificar si el nuevo tamaño del buffer es 0
    if(nuevo_size == 0) {
        // Si es 0, liberar el stream del buffer y establecer el tamaño del buffer en 0
        un_buffer->size = 0;
        free(un_buffer->stream);
        un_buffer->stream = NULL;
        return choclo; // Devolver el dato extraído
    }
    // Verificar si el nuevo tamaño del buffer es negativo (lo cual sería un error)
    if(nuevo_size < 0) {
        perror("/n[ERROR_CHOCLO] BUFFER con tamanio negativo");
        exit(EXIT_FAILURE);
    }
    
    // Si el nuevo tamaño del buffer es mayor que 0, realojar memoria para el nuevo stream del buffer
    void* nuevo_stream = malloc(nuevo_size);
    if(nuevo_stream == NULL) {
        perror("Error al asignar memoria para nuevo_stream");
        exit(EXIT_FAILURE);
    }
    // Copiar el resto del buffer al nuevo stream
    memcpy(nuevo_stream, un_buffer->stream + sizeof(int) + size_choclo, nuevo_size);
    // Liberar el stream original y actualizar el stream y tamaño del buffer
    free(un_buffer->stream);
    un_buffer->size = nuevo_size;
    un_buffer->stream = nuevo_stream;

    return choclo; // Devolver el dato extraído
}

uint16_t extraer_uint16_al_buffer (t_buffer* un_buffer){
	uint16_t* un_entero = extraer_choclo_al_buffer(un_buffer);
	uint16_t valor_retorno = *un_entero;
	free(un_entero);
	return valor_retorno;
}
char* extraer_string_al_buffer (t_buffer* un_buffer){
	char* un_string = extraer_choclo_al_buffer(un_buffer);
	return un_string;
}

void* serializar_paquete (t_paquete* un_paquete){
	int size_coso = un_paquete->buffer->size + 2* sizeof(int);
	void* coso = malloc(size_coso);
	int desplazamiento = 0;
	memcpy(coso + desplazamiento, &(un_paquete->codigo_operacion), sizeof(int));
	desplazamiento += sizeof(int);
	memcpy(coso + desplazamiento, &(un_paquete->buffer->size), sizeof(int));
	desplazamiento += sizeof(int);
	memcpy(coso + desplazamiento, &(un_paquete->buffer->stream), un_paquete->buffer->size);

	return coso;
}

void enviar_paquete (t_paquete* paquete, int conexion){
	void* a_enviar = serializar_paquete(paquete);

	int bytes_enviados = 0;
    int bytes_a_enviar = paquete->buffer->size + 2 * sizeof(int);

    while (bytes_enviados < bytes_a_enviar) {
        int bytes_enviados_actual = send(conexion, a_enviar + bytes_enviados, bytes_a_enviar - bytes_enviados, 0);
        if (bytes_enviados_actual == -1) {
            perror("Error al enviar el paquete");
            exit(EXIT_FAILURE);
        }
        bytes_enviados += bytes_enviados_actual;
    }

    free(a_enviar);

    // Verificar si se enviaron todos los bytes del paquete
    if (bytes_enviados == bytes_a_enviar) {
        printf("El paquete se ha enviado completamente.\n");
    } else {
        printf("Error: No se han enviado todos los bytes del paquete.\n");
    }
}`

**Comment by nicolasreypc** [comment]
disculpas, no se xq se envio mal el codigo

**Comment by iago64** [comment]
Buenas! 

Ahi te edite el mensaje, la idea es que si vas a pegar fragmentos de código los pongas en un bloque como se muestra en la parte de [Quoting Code de la guía de markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code), que si queres sumarle el tema de colores despues de los 3 tildes que abren la sección le pones el lenguaje, por ej c y eso hace que se vea bonito.

Respecto al problema que estas teniendo, algo importante es que no nos decis si te tira un seg fault, te trae cualquier dato o que está pasando. Por eso y que de paso esta bueno que empiecen a conocer, te recomiendo que uses una herramienta que como un poco en chiste, un poco en serio decimos que salva TPs y es Valgrind, de la cual obviamente tenemos una [Guía en el sitio de Docs](https://docs.utnso.com.ar/guias/herramientas/valgrind).

Si estas haciendo algo mal con la memoria, Valgrind te lo va a decir y ahi vamos a poder desentrañar el problema.

Saludos.-

**Comment by nicolasreypc** [comment]
esto me dice el kernel:
![image](https://github.com/sisoputnfrba/foro/assets/143523417/851c41b2-1990-41f8-8eeb-d9004ac9a75a)


y esto la memoria:
![image](https://github.com/sisoputnfrba/foro/assets/143523417/fcdabac1-cc32-48f0-94d7-398a7640abbe)

estoy viendo y leyendo los videos del doc para ver si entiendo los errores que me salen en memoria

**Comment by iago64** [comment]
Buenas! Cómo va?

Al igual que con el código, por favor el output de Valgrind, no lo subas en capturas de pantalla.
En principio fijate que Valgrind te esta mencionando Invalid Read  en ambos casos, eso se parece muuucho a los [Invalid Write que estan en la guía](https://docs.utnso.com.ar/guias/herramientas/valgrind#invalid-write-of-size), te recomiendo que empieces por debuguear y ver si no te están llegando mal los valores ahi.

Saludos.-

**Comment by nicolasreypc** [comment]
Mil gracias!!!! comenzare a usar mas Valgrind jaja....
Por si a alguien le interesa el error era que pasaba la direccion de memoria de un_paquete->buffer->stream, en vez del puntero propiamente, en la funcion serializar paquete.
`void* serializar_paquete (t_paquete* un_paquete){
	int size_coso = un_paquete->buffer->size + 2* sizeof(int);
	void* coso = malloc(size_coso);
	int desplazamiento = 0;
	memcpy(coso + desplazamiento, &(un_paquete->codigo_operacion), sizeof(int));
	desplazamiento += sizeof(int);
	memcpy(coso + desplazamiento, &(un_paquete->buffer->size), sizeof(int));
	desplazamiento += sizeof(int);
	memcpy(coso + desplazamiento, un_paquete->buffer->stream, un_paquete->buffer->size);

	return coso;}`
