### ISSUE TITLE
Hilos en módulo memoria

### ISSUE THREAD

**Issue by fmigliavacca** [sisoputnfrba/foro#3501]
Hola! Quería consultarles si hay necesidad de implementar hilos en el módulo de memoria. Entiendo que debe escuchar las peticiones de parte de las i/o , el cpu y el kernell. Entiendo que por ejemplo si dos procesos están bloqueados al mismo tiempo por necesitar cierta información de memoria, ambos querrán acceder al módulo de memoria. Mi pregunta es si estos dos procesos deberían acceder en simultaneo (concurrentemente) con la implementación de hilos. O no, ya que podría ser perjudicial si por ejemplo dos deciden escribir el mismo espacio en memoria en simultaneo. O quizás debo implementar los hilos y poner cierta complejidad como semáforos o algo de ese estilo apra que no se pisen ambos hilos. Espero su respuesta, saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

La experiencia me suele dictar que el uso de hilos cuando hablas con múltiples clientes es mucho más simple que tener todo con `select()` y tener miles de `if()` anidados porque el código se vuelve spaghetti y es muy fácil que pierdan horas viendo que se les rompió. Dicho lo anterior, la concurrencia es algo que van a tener que manejar si van por hilos, pero que de momento no deberían preocuparse ya que para los checkpoints previos al primer parcial solo tienen que encarar los pedidos de las instrucciones de parte de la CPU y la creación / finalización de procesos del Kernel.

Ahora bien, si el enunciado no aclara que el proceso tiene que ser multihilo, pueden optar por no hacerlo multihilo, pero traten de parar la pelota y pensar que ganan / pierden con hilos y que ganan /pierden con `select()`.

Saludos.-

**Comment by fmigliavacca** [comment]
Perfecto, gracias. Y la función select() de que librería es? Para saber que hace más o menos

**Comment by LeandroCarbajales** [comment]
Buenas @fmigliavacca !
Quedó resuelta la duda?

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, ante cualquier consulta pueden reabrirlo o abrir uno nuevo. Saludos
