### ISSUE TITLE
list.h

### ISSUE THREAD

**Issue by fmigliavacca** [sisoputnfrba/foro#3502]
Hola! Me encuentro en la necesidad de utilizar la bibliotecta list.h, la cuestión es que no estoy pudiendo entender como implementarla.
Entiendo que la catedra desarrolla esa bibliotecta por lo que no encontré información en Google y los archivos list.h y list.c no fueron suficientes en mi caso para poder comprender su implementación. Por lo que esperaba, si es posible, que me muestren un ejemplo medio pavo de cómo implementarla. Por ejemplo:
Si yo quisiera realizar una lista cuyos elementos respeten esta estructura:
struct estructura{
int dato1;
int dato2;
char dato3[10]; };
Por favor, mostrarme cómo sería en código. También si es posible, cómo hacer el list_create. Espero su respuesta, saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

Para entender un poco como funcionan las commons podes:

1.- Ver los [unit-tests](https://github.com/sisoputnfrba/so-commons-library/blob/master/tests/unit-tests/test_list.c) que estan implementados en el repo de las commons, casualmente el caso de las listas tiene un struct, no es igual a como lo pedis vos, pero te puede servir de guía.

2.- Otro ejemplo de código bastante copado es el TP0, donde casualmente en la parte del server, usa el `list_create()` para crear una lista de los parámetros que recibió del cliente.

Por último, algo que quisiera que se entienda, es que la respuesta de mandarte a buscar en otros lados viene de la mano de que los ayudantes estamos para guiarlos en su aprendizaje y en su desarrollo como futuros profesionales, es decir, no vamos a darles el código resuelto, si no que vamos a ayudarlos a que uds puedan crear el código. 

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Me sumo para agregar que todas las funciones se encuentran documentadas en el list.h que mencionás. Dudo mucho que te sea difícil invocar un `list_create()`, ya que justamente es una función que ni siquiera recibe parámetros y tiene un valor de retorno.

Luego, tené en cuenta que tanto `list` como `config`, `log`, etcétera son Tipos Abstractos de Datos (TADs). Al igual que otros TADs que probablemente hayas visto en AyED (como, por ejemplo, `FILE`), no interesa saberse perfectamente la implementación interna de cada función, sino las operaciones asociadas a dicho TAD.

Así como con `FILE` tenés `fopen`, `fread`, `fwrite`, `fclose` y etcétera, con las funciones de las commons tenés todas las operaciones posibles que esperarías en una lista (incluso algunas más que van a ver más en detalle en PdeP).

Como bien dijo Dami, entendemos que no sería lo más pedagógico darte la respuesta. Una habilidad muy importante que debe tener un profesional es la de saber **encontrar las respuestas a sus propias dudas**: nadie nace sabiendo y es imposible ser un experto en todas las tecnologías existentes, por lo que es normal encontrarse con la necesidad de aprender algo nuevo y aplicarlo durante el aprendizaje.

Haciendo una analogía, nuestra intención no es darte el pescado, sino que logres aprender a pescar :)

Saludos

**Comment by LeandroCarbajales** [comment]
Hola @fmigliavacca !
Te sirvieron las respuestas de @iago64 y @RaniAgus ?

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, ante cualquier consulta pueden reabrirlo o abrir uno nuevo. Saludos
