### ISSUE TITLE
Pipe broken al intentar de conectarse con el servidor del Kernel

### ISSUE THREAD

**Issue by Sancho6446** [sisoputnfrba/foro#3503]
A la hora de conectar algún modulo(En modo cliente) al Kernel(en modo servidor) algunas veces funciona y otras salta una excepcion del lado del cliente con la leyenda "Broken pipe", a la hora de intentar hacer el handshake con el Kernel.

Este es el código del handshake del lado del cliente:
```
int handshake(int socket_cliente)
{
    size_t bytes;

    int32_t handshake = 3;//PASAR ESTO A CONFIG en utils
    int32_t result;

    bytes = send(socket_cliente, &handshake, sizeof(int32_t), 0);
    bytes = recv(socket_cliente, &result, sizeof(int32_t), MSG_WAITALL);

    if (result != 0)
    {
        exit(-1);
    }
    return result;
}
```
Este es el codigo del handshake del lado del kernel:
```
int handshake_Server(int socket_cliente)
{

	size_t bytes;

	int32_t handshake;
	int32_t resultOk = 0;
	int32_t resultError = -1;

	bytes = recv(socket_cliente, &handshake, sizeof(int32_t), MSG_WAITALL);
	
	if (handshake>=0 && handshake<=3)
	{
		bytes = send(socket_cliente, &resultOk, sizeof(int32_t), 0);
	}
	else
	{
		bytes = send(socket_cliente, &resultError, sizeof(int32_t), 0);
	}
	return handshake;
}
```
Este es el codigo main del kernel:
```
#include <stdlib.h>
#include <stdio.h>
#include <utils/hello.c>
#include <string.h>
#include <commons/log.h>
#include "utils.h"

int main(int argc, char *argv[])
{
    logger = log_create("kernel.log", "Servidor", 1, LOG_LEVEL_DEBUG);
    int server_fd = iniciar_servidor();
    log_info(logger, "Kernel listo para recibir");
    int cliente_fd = esperar_cliente(server_fd);

    int modulo = handshake_Server(cliente_fd);

    switch (modulo)
	{
	case 0:
	log_info(logger,"se conecto el modulo kernel");
		break;
	case 1:
	log_info(logger,"se conecto el modulo cpu");
		break;
	case 2:
	log_info(logger,"se conecto el modulo memoria");
		break;
	case 3:
	log_info(logger,"se conecto el modulo io");
		break;

	}
  decir_hola("Kernel_Servidor");
    return 0;
}

```
El error que dice es : Excpetion : broken pipe
Despues de mas testing pareciera ser que la primera vez despues de guardar un archivo funciona y luego en una segunda conexion deja de funcionar.

**Comment by RaniAgus** [comment]
¡Buenas! El error "Broken pipe" surge al intentar hacer un `send()` a una conexión que fue cerrada del otro lado.

1. ¿Es posible que haya algún `close()` del lado del server?
2. ¿Validaron que el `socket_cliente` que recibe la función `handshake()` haya hecho el `connect()` correctamente? O sea, que la función no haya retornado `-1`.

**Comment by Sancho6446** [comment]
Hola buenas
No hay ningun close del lado del server y el connect no retorna -1. El error igual es verdad esta ahi en el send

**Comment by RaniAgus** [comment]
Hmmm, les recomiendo validar los valores de retorno de todas las syscalls que usen (`socket`, `bind`, `listen`, `connect`, `accept`, etc) para poder diagnosticar exactamente cuál fue la que falló. También convendría imprimir en el mensaje de error qué IP y puerto recibió la función, en caso de que quizás haya alguna config con un puerto repetido u otra cosa.

Me suena a que probablemente esté fallando el `bind()` porque el puerto quedó reservado por alguna ejecución anterior y el SO todavía no llegó a liberar ese puerto para que la nueva instancia lo use.

**Comment by Sancho6446** [comment]
Hola de vuelta, el error esta en el listen y es el siguiente "Address already in use" después de investigar un poco y llegar a este [link](http://www.softlab.ntua.gr/facilities/documentation/unix/unix-socket-faq/unix-socket-faq-4.html#ss4.2)
nuestra conclusión es que no es algo que nos debería preocupar ahora mismo ya que ocurre por correr el servidor muy rápido dos veces seguidas y las soluciones (Menos la obvio que es esperar un poco de tiempo a que se libere) parecen complicar la situación. Aunque se nos hace raro que cuando usamos el modulo memoria como servidor este error no ocurre.

**Comment by RaniAgus** [comment]
Así es, también hay un comment al respecto en este issue: https://github.com/sisoputnfrba/foro/issues/1624#issuecomment-611745367

Si no quedan más dudas pueden cerrar el issue :)
