### ISSUE TITLE
Duda sobre tipos de variables

### ISSUE THREAD

**Issue by GianLema** [sisoputnfrba/foro#3504]
Hola buenass. Queriamos saber con mi grupo si las variables que el enunciado dice que cada modulo va a usar, deben ser del tipo especificado al momento de declararlas en nuestro tp (ej PC, numerico), o si pueden ser declaradas con otro tipo.

**Comment by iago64** [comment]
Buenas! Cómo va?

Los registros de la CPU no se negocia el tipo de dato, ya que vamos a armar las pruebas teniendo en cuenta exactamente los tipos de dato que les pasamos.
Ahora en los configs, si uds por ej tienen el `PUERTO ESCUCHA` que es un número y lo quieren leer como string porque les resulta mas simple, no hay problema.

Saludos.-

**Comment by GianLema** [comment]
okok mil graciass!
