### ISSUE TITLE
DUDA CON FUNCION EJECUTAR_SCRIPT

### ISSUE THREAD

**Issue by nicolasreypc** [sisoputnfrba/foro#3505]
![image](https://github.com/sisoputnfrba/foro/assets/143523417/23564a4f-dad4-4a10-9648-378b611c7db9)

Buenas, tengo una duda con la funcion EJECUTAR_SCRIPT, no entendi bien si contendra instrucciones de kernel como INICIAR_PROCESO, FINALIZAR_PROCESO, etc o instrucciones de CPU como MOV, ADD etc. Y tambien me seria de ayuda saber como estan separadas entre si.
Tambien si son del tipo INICIAR_PROCESO, querria saber si no se tiene en consideracion la instuccion PROCESO_ESTADO, ya que dice de las siguientes 5.

**Comment by iago64** [comment]
Buenas! Cómo va?

El archivo que les pasemos al EJECUTAR_SCRIPT, va a tener instrucciones del Kernel y van a estar divididas por líneas, es decir, separados por `\n`.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas!
Lo de "las siguientes 5" quedó desactualizado, ya mismo lo corregimos, sí debería poder incluir todos los comandos del Kernel. Muchas gracias por notarlo!

**Comment by LeandroCarbajales** [comment]
Hola @nicolasreypc !
Te sirvieron las respuestas? Quedó resuelta la duda?

**Comment by nicolasreypc** [comment]
Si, muchas gracias!
