### ISSUE TITLE
Debugger, Valgrind y Helgrind

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3506]
Buenas tardes,
Quería saber con respecto al debugger si solo debemos utilizarlo cuando nuestro programa no funciona como quisieramos que lo haga. Porque entiendo que Valgrind/Helgrind siempre es recomendable pasarlo ya que nos ayuda a detectar problemas con la memoria, leaks y esas cosas que no necesariamente afectan la correcta ejecución de nuestro código.

**Comment by iago64** [comment]
Buenas! Cómo va?

El tema del debugger, siempre que algo no funcione como esperan, esta bueno darse un ratito de tiempo y ver que info les puede aportar ,ya que les permite ir paso a paso en su código y les permite ver si pusieron mal un `if()` o si les esta llegando algo mal, esto es una primera "instancia" si se quiere, despues cuando ven que algo no esta teniendo mucho sentido, por ej, que un valor cambia "magicamente", ahi es donde entran en juego Valgrind y Helgrind.

Valgrind y Helgrind son herramientas que los van a salvar cuando no tengan contexto de las cosas o el contexto no sea muy claro, porque Valgrind lo que hace es ver como estan usando la memoria y en el caso de Helgrind lo que hace es ver que tanto se les puede complicar con los threads.

Saludos.-

**Comment by rood8592** [comment]
Gracias!
