### ISSUE TITLE
Como realizo conexiones sucesivas

### ISSUE THREAD

**Issue by nicolasvultaggio** [sisoputnfrba/foro#3507]
La idea es, para el checkpoint 1, realizar las conexiones cliente servidor necesarias, el problema que tengo son mas dudas teóricas para la aplicación en C. Teníamos pensado empezar con Memoria, que lo único que hace es ser SERVIDOR de los otros 3 módulos, nosotros habíamos pensado en ejecutarla primero, y que lo que haga es: que ponga en escucha un puerto (para este checkpoint, cada modulo solo dispone de un solo puerto?), y quedarse esperando con accept la conexión de algun modulo, y ahí ejecutar el CPU, que dispone su puerto en escucha para ser servidor del kernel, y de paso se conecta con la memoria para hacer su respectivo handshake, y así sucesivamente con el resto de módulos. 

Main de memoria:

```c
int main() {
  decir_hola("Memoria, verdad y justicia");
  logger_memoria = log_create("memoria_logs.log","memoria",1,LOG_LEVEL_INFO);
  config_memoria = config_create("./configs/memoria.config");
  leer_configuraciones();
  socket_server_MEMORIA = iniciar_servidor(NULL, PUERTO_ESCUCHA);
  log_info(logger_memoria, "Puerto de memoria habilitado para sus clientes");
  socket_cliente_MODULO = accept(socket_server_MEMORIA,NULL,NULL);
  handshakeSERVIDOR(socket_cliente_MODULO,handshakeDeCPU,conexionExitosaCPU,noCoincideHandshakeCPU);
  close(socket_server_MEMORIA);
}

// estas funciones sirven para los handshake 

void handshakeSERVIDOR(int socketConexion , int32_t handshakeExitoso , int32_t * conexionExitosa , int32_t * noCoincideHandshake ){
	
	int32_t handshake;
	size_t bytes;
	
       if ( recv(socketConexion,&handshake,sizeof(int32_t), MSG_WAITALL)==(-1)){
         printf("No se pudo recibir handshake");
      };
      if(handshake == handshakeExitoso){
        bytes = send(socketConexion, conexionExitosa, sizeof(int), 0);
       }else{
        bytes = send(socketConexion, noCoincideHandshake, sizeof(int), 0); 
        }
	return;
}
     // declaro la variable bytes porque send y recv deben devolver algo

    // se implementa despues de hacer connect
void handshakeCLIENTE( int socketConexion , int32_t * handshakeAEnviar, int32_t valorDeConfirmacion  ){
	size_t bytes;
	int resultado;
	bytes = send(socketConexion, handshakeAEnviar , sizeof(int),0 );
	bytes = recv(socketConexion, &resultado, sizeof(int), MSG_WAITALL);
	if( resultado != valorDeConfirmacion){
		printf("El cliente recibio la respuesta del servidor pero no fue la correcta");
		exit(-1)
	}
	return;
}
```

Entonces, con estas ideas, se supone que apenas se ejecute el cpu, tendra que hacer la funcion handshakeCLIENTE, enviar su int32_t a la memoria, pero mi duda es:

Luego de que la memoria hace handshakeSERVIDOR, el cliente sera el encargado de recibir su respuesta, y luego cerrar el socket de la conexion, pero yo no entiendo como hacer para que el puerto de la memoria siga habilitado para que luego reciba mas conexiones, ya que si igualo el socket conexion a otro accept nuevo (luego de handshakeSERVIDOR), para que se conecte despues el kernel, para una nueva conexion, se me borraría el filedescriptor de la conexion antes de que el cliente pueda recibir la informacion y EL cerrar el file descriptor? Debería usar mas de un puerto? En ese caso, no debería implementar HILOS?

Es muy confuso, se que quizas muchas cosas que dije quizas son incorrectas en aspectos teoricos, por eso me gustaria una aclaracion de mas o menos el "panorama".

**Comment by nicolasvultaggio** [comment]
Bueno, no se por que algunas partes del codigo no se me suben como codigo, algo estare haciendo mal

**Comment by nicolasvultaggio** [comment]
sisi, igual esa no era mi duda principal, quizas aparece como que cerre el issue, pero fue por que me equivoque, en realidad es la primer pregunta, la que arranca con "La idea es, en el checkpoint 1," 

Aclaro porque en un momento sin querer cerre el issue por accidente, pero en realidad sigo teniendo esa duda, mil gracias

**Comment by iago64** [comment]
Buenas! Ahí te acomode un poco el código, aprovecha a editar el post, podes fijarte como queda para que quede mas prolijo en el próximo issue.

Respecto a tu duda:
Si vos cerras el socket despues de hacer el handshake como que mucho sentido no tiene la conexión, lo que vos buscas cuando creas un socket es despues dejarlo abierto para mandar y recibir información por ahí.
El puerto de la memoria va a seguir escuchando ya que hay algo que no estas viendo que pasa a nivel SO y es que cuando vos llamas a `accept()` en el servidor, este te devuelve un nuevo socket en un puerto que no te importa en lo mas minimo ya que de eso se encargó el SO para dejarte el puerto que definiste como escucha libre para aceptar nuevas conexiones, vos solo te guardas el file descriptor (el int) que te devuelve `accept()` y con eso despues haces todos los `send()` y `recv()` que necesites.

Te recomiendo que le pegues una leida de nuevo a la [guía de sockets](https://docs.utnso.com.ar/guias/linux/sockets) y que no sea una leída para marcar el check de hablera leído, si no que pares la pelota y analices lo que decimos y que ademas podes complementarlo con el video de la charla que se daba hace varios años donde es un poco mas gráfico esto que te estoy contando en texto y en todo caso si aun despues de releer la guía y ver la charla algo no te cierra, nos hagas las preguntas que necesites para poder entender un poco como funciona esto de los sockets.

Saludos.-

**Comment by nicolasvultaggio** [comment]
Sí, entiendo por que no hay que hacer close (socket_server_MEMORIA), eso cerraría el socket de escucha, eso lo tengo claro, lo que me pregunto es, si despues de que el cliente recibe la respuesta del handshake, y cierra el socket de conexion , eso significa que el servidor debe volver a hacer accept para que acepte a cualquier otro cliente que quiera conectarse, o si con hacer una accept una vez al principio ya alcanza para que varios clientes hagan connect (por ahora no al mismo tiempo, porque no busco usar hilos)

Por ahora solo busco que se conecten, hagan el handshake, y se cierre la conexion, pero que al servidor se le puedan conectar luego los clientes que quieran

**Comment by nicolasvultaggio** [comment]
creo que ya lo entendi
