### ISSUE TITLE
validacion de interfaces

### ISSUE THREAD

**Issue by tolaDiego** [sisoputnfrba/foro#3509]
Buenas, mi duda es sobre sobre como se hacen las validaciones de interfaces.

### 📔 Citas del enunciado/videos

![image](https://github.com/sisoputnfrba/foro/assets/82244941/ce20697c-1a2a-416d-b345-e8a097967c4a)

### 💭 Soluciones posibles

Por el momento se me ocurren dos caminos:
Las interfaces una vez conectadas le avisan al kernel que se conectaron(o desconectaron) para que este último pueda tener un registro de las mismas y que luego pueda usar para validar las peticiones que le llegan de cpu o kernel se comunica con entradasalida en varios pasos para resolver si es una interfaz valida.

**Comment by RaniAgus** [comment]
¡Buenas! Para validar la conexión es sencillo, ya que luego de hacer el `accept()` podrías aprovechar el handshake para chequear qué tipo de dispositivo se está conectando.

Para la desconexión es un poquito más complicado, ya que la interfaz no puede "avisarte" que se desconectó. Es parecido a desenchufar el teclado: justamente el dispositivo deja de estar conectado para poder enviarte mensajes.

Lo que sí: no es requisito que el Kernel sepa en _tiempo real_ qué dispositivos hay conectados o no. Podrías simplemente hacer el intento de enviar el mensaje y si el mismo falla manejarlo apropiadamente y marcarlo como desconectado.

Para saber más detalles sobre cómo aceptar conexiones, qué es un handshake y cómo manejar apropiadamente una desconexión, contamos con la [guía de sockets](https://docs.utnso.com.ar/guias/linux/sockets).

Saludos

**Comment by tolaDiego** [comment]
¡Buenos dias! Gracias por la respuesta.
Aca va otra duda
Estaria bien que en el handshake, ademas de enviar el tipo de interfaz que se conecta, envie el nombre de la interfaz para que kernel lo guarde junto al socket de esa interfaz?  Porque sino puedo enviar el nombre de la interfaz no estaria entendiendo como sabe kernel a que interfaz enviar el mensaje.

**Comment by iago64** [comment]
Buenas! Cómo va?

En el handshake uds pueden mandar todo lo que necesiten. Piesen en el heandshake como un saludo / presentación de los módulos, entonces no sería loco que en el handshake le digas algo asi como _Hola Kernel, soy la interfaz INT01, soy de tipo DialFS_, obviamente que con menos texto y mas serializado.

Saludos.-

**Comment by tolaDiego** [comment]
Genial, me queda claro! Muchas gracias nuevamente.

**Comment by iago64** [comment]
Buenas! Si la duda esta resuelta no se olviden de cerrar el issue 👮‍♂️
