### ISSUE TITLE
no puedo ejecutar la memoria

### ISSUE THREAD

**Issue by nicolasvultaggio** [sisoputnfrba/foro#3510]
Tengo un problema y es que quiero darle run y debug a la memoria pero me dice  

launch: program 'home/utnso/Desktop/C COMENTA 2/tp-2024-1c-Grupo-5/memoria/bin/memoria' does not exist

![image](https://github.com/sisoputnfrba/foro/assets/131707089/09cd9f55-8bdd-45f3-aa8e-3ff34bca8a0a)

y la unica opcion que tengo es abrir el json para las configuraciones, pero yo de eso no toque nada

![image](https://github.com/sisoputnfrba/foro/assets/131707089/d6772595-12da-4bc8-a512-8e6a3ee03157)

lo mismo con todos los modulos, no puedo ejectuarlos porque me aparece el mismo mensaje

**Comment by nicolasvultaggio** [comment]
creo que por algun motivo no se me estan creando los ejecutables en las carpetas bien, supongo que tendra que ver con algo de los makefiles, pero yo no toque nada de eso

**Comment by RaniAgus** [comment]
¡Buenas! Veo que la ruta al TP tiene una carpeta con espacios. Te aconsejo quitar los espacios de la carpeta ya que hay un bug que está comentado más en detalle en: https://github.com/sisoputnfrba/foro/issues/3492

Saludos

**Comment by nicolasvultaggio** [comment]
Muchas gracias!!! Ahí se solucionó

**Comment by RaniAgus** [comment]
¡Buenísimo! Una vez resuelta la duda no olviden cerrar el issue 👮🏻‍♂️ Saludos
