### ISSUE TITLE
Dudas de Memoria

### ISSUE THREAD

**Issue by santi-p98g** [sisoputnfrba/foro#3512]
Buenas! Espero que ande todo bien

Hice estas consultas el sábado en soporte y me dijeron que las deje acá ya que no tenían la respuesta en el momento.

1) ¿Qué pasa al hacer un resize de tamaño menor al que ya tiene el proceso y además hay información en todos los marcos?
Es decir, tengo un PA que tiene supongamos con un primer RESIZE(20 BYTES), luego se escriben en memoria en los marcos que se le den y hay en ese caso por ejemplo 4 marcos asociados al proceso, y no libres sino con data escrita. Ahora viene un RESIZE(10 BYTES), ¿Qué hago con los marcos que ya están cargados? ¿Cuál debería borrar, el mayor desde el final aunque tenga información? 

2) ¿Qué pasa cuando viene un resize no múltiplo del tamaño de pagina?
Por ejemplo si el tamaño de la pagina es 5 BYTES y ejecuto un RESIZE(12 BYTES), ¿Se le dan 3 paginas y quedan 3 bytes inutilizables en la última?

Y una cosa mas que no me queda clara:
Suponiendo que tenemos algo como esto en la memoria:
<img width="190" alt="Captura de pantalla 2024-04-15 a la(s) 19 08 59" src="https://github.com/sisoputnfrba/foro/assets/82118725/f257317c-ec1e-4094-be66-e7aa8edd88f2">
Quedan libres 3B en el marco asociado al Proceso A. ¿Se puede seguir usando para otras escrituras? Porque en ese caso debería confiar en que la dirección lógica de la cpu tiene un desplazamiento correcto, sino puede pisar los valores que ya estaban escritos anteriormente. O quizás me estoy confundiendo algo.

Muchas Gracias! un saludo :)

**Comment by LeandroCarbajales** [comment]
Buenas!
1- Este caso está específicado en el enunciado, cito:

> Reducción de un proceso
Se reducirá el mismo desde el final, liberando, en caso de ser necesario, las páginas que ya no sean utilizadas (desde la última hacia la primera).

Es decir, marcarías libres los marcos que estaban asignados a las páginas que ya no apliquen, no es necesario "borrar" el contenido de esos marcos.

2-
No habría ningún problema con que el tamaño de página no sea múltiplo con el resize ya que simplemente se asignan páginas/marcos,  llegado el caso el proceso podría usar "un poquito más" de lo que pidió (lo que "sobra" de la última página), y si no lo usa a eso se le llama **fragmentación interna**, que es un concepto que siempre se evalúa en los parciales ;)

Con respecto a lo último, sí, es el comportamiento esperado que un proceso pueda pisar lo que ya escribió y/o seguir escribiendo en el "resto" de la página que todavía no utilizó.

Te aclara las dudas?
Saludos!
     Lean

**Comment by santi-p98g** [comment]
Perfecto!

Solo una cosita con 1), entonces cuando se libera un marco no es necesario 'borrar' lo que hay en el? directamente se pisa luego al asignarselo a otra pagina?

Después de eso todo entendido, mil gracias :)

**Comment by LeandroCarbajales** [comment]
Exactamente, simplemente se marca "libre" para luego poder ser asignado a otra página.
