### ISSUE TITLE
Error al hacer handshake (Error 104 y 0)

### ISSUE THREAD

**Issue by IanR4** [sisoputnfrba/foro#3513]
Ya tenemos los modulos hechos y parece que se conectan bien. Al hacer los handshake para cada conexion, funcionan todos menos el  de interfaz - kernel e interfaz - memoria. El error que nos da es "Connection reset by peer (104)" y en otras ocasiones "Success (0)". 

![image_2024-04-15_204323434](https://github.com/sisoputnfrba/foro/assets/164390953/9f7500dc-a89b-4aa8-af05-b44ba8697f76)

![image_2024-04-15_204336405](https://github.com/sisoputnfrba/foro/assets/164390953/4963af38-928c-4622-9657-c30476e62765)

Interfaz como cliente:
```
//-------------INTERFAZ >> MEMORIA---------------------
    char* ip_memoria = config_get_string_value(config, "IP_MEMORIA");
    char* port_memoria_interfaz = config_get_string_value(config, "PUERTO_MEMORIA_INTERFAZ");
    
    *fd_memoria_interfaz = crear_conexion(logger, ip_memoria, port_memoria_interfaz, "Memoria_interfaz");

//-------------INTERFAZ >> KERNEL---------------------
    char* ip_kernel = config_get_string_value(config, "IP_KERNEL");
    char* port_kernel_interfaz = config_get_string_value(config, "PUERTO_KERNEL");

    *fd_kernel_interfaz = crear_conexion(logger, ip_kernel, port_kernel_interfaz, "Kernel_interfaz");

    send_handshake(logger, fd_kernel_interfaz, "INTERFAZ / Kernel");
    send_handshake(logger, fd_memoria_interfaz, "INTERFAZ / Memoria");
```

Memoria como servidor: 
```
   char* puerto_memoria_interfaz = config_get_string_value(config, "PUERTO_MEMORIA_INTERFAZ");

    fd_memoria_interfaz = iniciar_servidor(logger, ip_memoria, puerto_memoria_interfaz, "Memoria_interfaz");

    fd_interfaz = esperar_cliente(logger, fd_memoria_interfaz, "MEMORIA_INTERFAZ");
   
    recv_handshake(fd_interfaz);
```

Kernel como servidor:
```
    char* ip_kernel = config_get_string_value(config, "IP_KERNEL");
    char* puerto_interfaz = config_get_string_value(config, "PUERTO_ESCUCHA");

    fd_kernel = iniciar_servidor(logger, ip_kernel, puerto_interfaz, "KERNEL_Interfaz");

    fd_interfaz = esperar_cliente(logger, fd_kernel, "KERNEL_Interfaz");
  
    recv_handshake(fd_interfaz);
```

Funcion del handshake:
```
bool send_handshake(t_log* logger, int fd, const char* connection_name){
    size_t bytes;
    int32_t handshake = 1;
    int32_t result;

    bytes = send(fd, &handshake, sizeof(int32_t), 0);
    bytes = recv(fd, &result, sizeof(int32_t), MSG_WAITALL);

    if (result == 0) {
        log_info(logger, "Handshake OK de %s", connection_name);
    } else {
        log_error(logger, "Handshake ERROR de %s, el error es %s (%d)", connection_name, strerror(errno), errno);
    }
    return true;
}

bool recv_handshake(int fd){
    size_t bytes;

    int32_t handshake;
    int32_t resultOk = 0;
    int32_t resultError = -1;

    bytes = recv(fd, &handshake, sizeof(int32_t), MSG_WAITALL);
    if (handshake == 1) {
        bytes = send(fd, &resultOk, sizeof(int32_t), 0);
    } else {
        bytes = send(fd, &resultError, sizeof(int32_t), 0);
    }
    return true;
}
```

**Comment by RaniAgus** [comment]
¡Buenas! ¿El compilador les tira algún warning de pasar algún tipo de dato que no concuerde? ¿Usaron el debugger para chequear que todas las funciones reciban valores correctos? ¿Al iniciar servidor y cliente validaron los valores de retorno de las syscalls por si hay algún error previo? Saludos

**Comment by IanR4** [comment]
Buenas! El compilador no nos tira warning. Validamos los valores de retorno de servidor - cliente y todo funciona. Al usar el debugger, nos dimos cuenta que al hacer el primer send del handshake (envia el valor 1) el servidor no recibe este valor, recibe basura. Ahi debe estar el problema pero no se nos ocurre una solucion. Pensamos en que la conexion entre cliente - servidor falla pero la validamos con los valores de retorno y en teoria, es correcta.

**Comment by NicolasGilRodriguez** [comment]
Otra cosa que estuvimos probando es que cambiando de lugar los recv y los send de los handshakes los handshakes que antes estaban bien pasaron a dar  Handshake Error Success (0). El orden de los recv y los send van de una forma fija o deberian de dar bien sin importar el orden?

**Comment by iago64** [comment]
Buenas! Cómo va?

El orden de los `send()` y `recv()` es FUNDAMENTAL, porque justamente si vos de un lado mandas algo, del otro lado lo tenes que estar esperando, es por esto que si ven la [guía de sockets](https://docs.utnso.com.ar/guias/linux/sockets) el dibujo es bastante claro y esta marcado que de un lado haces `send()` y del otro `recv()` y después es al revés cuando contesta.

Por otro lado, corriendo con Valgrind? Porque si les llega basura es mucho muy probable que algo no esté del todo bien en el manejo de la memoria, aunque parezca super simple y sean simples `int` a veces un `&` o un `*` de mas que no nos damos cuenta, nos puede complicar la existencia.

Saludos.-

**Comment by NicolasGilRodriguez** [comment]
Muchas gracias!!! Al final si era un error de poner ``` & ``` y ``` * ``` en unos lugares que faltaba. Pero aprovecho para preguntar, con el orden de ``` send() ``` y ``` recv() ``` no me referia a cambiar el orden entre el cliente y servidor sino a que, por ejemplo la interfaz tiene que mandar 2 ``` send() ``` uno a kernel y otro a memoria, da igual a quien le envia el ``` send() ``` primero o afecta en algo?

**Comment by iago64** [comment]
Buenas! Cómo va?

Gracias por la aclaración, si el orden de los handshake es indistinto, parte del protocolo de comunicación es eso, definir quien le habla primero a quien, pero pueden cambiar el orden si les resulta mas cómodo.

Saludos.-

**Comment by NicolasGilRodriguez** [comment]
Ok. Muchas gracias.

**Comment by IanR4** [comment]
Gracias por el soporte!
