### ISSUE TITLE
DIRECCIONES IP IGUALES

### ISSUE THREAD

**Issue by TommyChinchay** [sisoputnfrba/foro#3514]
Buenas noches.

Sucede que tengo la Xubuntu ( grafica ) y la Ubuntu Server ( consola ), la primera siempre la mantuve en Nat ( daba IP algo como 10.0.2.etc ), luego instale la Ubuntu Server y esta la configure en bridge, caso que esta me dio una IP 192.168.0.etc. El problema esta en que la Xubuntu al momento de pasarla a bridge me salta que la IP es la misma que la de Server.

De que manera podria solucionarse para que la Xubuntu muestre otra IP distinta?
Gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

Este problema lo tuvimos en el laboratorio, para remediarlo deberías clonarte el repositorio de [entorno-vms](https://github.com/sisoputnfrba/entorno-vms/tree/main) y deberías ejecutar el script `fluship.sh`, una vez que termina simplemente reinicias la VM con el comando `reboot` en el caso de la server o desde el menu en la vm de Xubuntu y al iniciar deberían tomar una nueva IP sin problemas.

Saludos.-

**Comment by TommyChinchay** [comment]
@iago64 Buenas tardes.

Buenisimo, lo voy a probar en caso vuelva a pasarme, gracias!

**Comment by LeandroCarbajales** [comment]
Buenas @TommyChinchay !
Con este último comentario está resuelta la duda?

**Comment by TommyChinchay** [comment]
@LeandroCarbajales Buenas noches.

Se podria decir que si, me conecte a otra red wifi (en otra casa) y se me soluciono lo del IP), mas si esta bueno esa forma que paso Iago en caso vuelva a suceder eso en el laboratorio o en otro contexto, ahora cierro el issue, saludos!
