### ISSUE TITLE
Serialización: prototipo de funciones genericas

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3515]
Buenas noches,
En la guía de serialización nos dan algunos prototipos de funciones para que hagamos, mi pregunta es si no es un problema hacer que avance el desplazamiento a pesar de que por ahí sea el ultimo dato que serialicemos o deserialicemos. Pueden surgir problemas con la memoria?

**Comment by iago64** [comment]
Buenas! Cómo va?

Si hicieron bien las cuentas, no deberían desplazarse mas allá del último elemento, de todas formas, si quieren para facilitarse la vida un poco pueden tomar de ejemplo las funciones que estan armadas en el tp0.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! ¿Quedó clara la respuesta de Dami?

Dicho en otras palabras, son ustedes los responsables de crear el TAD y de utilizarlo, así que el único "peligro" puede ser el de no haber hecho las cuentas correctamente para calcular el tamaño del buffer.

También pueden aprovechar el ejemplo del TP0, que lo que hace es ir resizeando el buffer a medida que se le vayan agregando cosas. En un sistema real, esto no es ideal ya que `realloc()` es una operación más costosa que hacer un solo `malloc()` (cuando vean Memoria creo que van a entender mejor por qué, es muy similar a cambiar el tamaño de un segmento), pero no hay ningún problema en hacerlo para el TP, de hecho hasta les podría resultar más sencillo.

Saludos

**Comment by rood8592** [comment]
Ok perfecto, gracias, utilizaremos las del tp0

**Comment by RaniAgus** [comment]
¡Buenísimo! Una vez resuelta la duda, no se olviden de cerrar el issue 👮🏻‍♂️
