### ISSUE TITLE
Duda con MMU

### ISSUE THREAD

**Issue by GregorioOndjian** [sisoputnfrba/foro#3516]
Buenass, tengo una duda con el el tema de las direcciones fisicas y logicas. Cuando el cpu decodifique una instrucción que tenga una direccion logica esta tiene que ser traducida por la MMU no? Esta que le pide a memoria, el tamaño de pagina u otra cosa? porque en el enunciado aparece la forma de "fabricar" la dirección física.
### 📔 Citas del enunciado/videos

> MMU

> A la hora de traducir direcciones lógicas a físicas, la CPU debe tomar en cuenta que el esquema de memoria del sistema es de Paginación. Por lo tanto, las direcciones lógicas se compondrán de la siguiente manera:
> [número_pagina | desplazamiento]
> Estas traducciones, en los ejercicios prácticos que se ven en clases y se toman en los parciales, normalmente se hacen en binario. Como en el lenguaje C los números enteros se operan independientemente de su base numérica, la operatoria puede desarrollarse de la siguiente forma:
> número_página = floor(dirección_lógica / _**tamaño_página**_)
> desplazamiento = dirección_lógica - número_página * tamaño_página

**Comment by iago64** [comment]
Buenas! Cómo va?

La CPU al momento de traducir la dirección lógica a física, lo que le tiene que pedir si o si a la memoria es el marco en el cual se encuentra la página del proceso.
Ahora la forma en la que obtienen el tamaño de página ya queda a criterio de uds, por ej puede devolverlo la memoria en el handshake o pueden agregar una config en la CPU y en ambos casos estaría bien.

Saludos.-

**Comment by GregorioOndjian** [comment]
Buenísimo, muchísimas graciasss.

**Comment by LeandroCarbajales** [comment]
Si está resuelta la duda, no olviden cerrar el issue :)
