### ISSUE TITLE
Pequeña consulta teórica

### ISSUE THREAD

**Issue by nicolasvultaggio** [sisoputnfrba/foro#3517]
Estuve leyendo los apartados de Conexión-Cliente servidor, para abordar el tema de hilos y multiplexación, y me surgió una pregunta:

cuando dice:

> Pensemos en todo lo que hicimos hasta ahora. Creamos sockets en ambos cliente y servidor, marcamos el servidor en escucha a nuevas conexiones, y se queda bloqueado en accept hasta que su cliente haga connect(). ¿Y si otro cliente hace connect() mientras el servidor no está en accept() por estar atendiendo al otro cliente?

yo tenía entendido que cuando el cliente hacía connect, lo que pasaba es que el accept devolvía OTRO FD que representaba la conexion bidireccional, como dejando "libre" al FD de escucha para recibir nuevos clientes, entonces, por qué otro cliente que hace connect (luego de haberse conectado el primero) debería esperar? si se supone que el FD de escucha esta libre?

**Comment by RaniAgus** [comment]
¡Buenas! Es cierto lo que mencionás: `accept()` te devuelve un nuevo file descriptor para atender la conexión. El problema es que si tu único hilo principal se dedica exclusivamente a atender dicha conexión, no va a poder ejecutar `accept()` de nuevo para aceptar la segunda conexión hasta que no termine la primera.

Entonces, el segundo cliente se va a quedar clavado en `connect()` hasta que el primero no se desconecte, y lo que nosotros queremos en este punto es multiplexar, es decir, atender múltiples clientes a la vez.

Saludos

**Comment by nicolasvultaggio** [comment]
perfecto!!! gracias
