### ISSUE TITLE
Duda alcance etapa 1

### ISSUE THREAD

**Issue by lseijasferraudo** [sisoputnfrba/foro#3518]
Buenos días, queria saber que es lo que debe poder realizar en tp en la entrega 1 ya que no termino de comprender la consigna en la parte de "definir protocolo de comunicación" 
Además cuando dicen "todos los módulos están creados y son capaces de establecer comunicaciones entre si" sería que simplemente puedan conectarse ? Que sería "comunicarse" ?
Por otra parte las funciones que fueron dadas en el tp0 pueden ser utilizadas en el trabajo ?

**Comment by iago64** [comment]
Buenas! Cómo va?

Por _definir el protocolo de comunicación_ nos referimos a que definan en una primera instancia quien se conecta a quien, como hacen el handshake, después el protocolo va a ir evolucionando a medida que crezca el TP y empiecen a agregarse mas mensajes.

Cuando decimos que _Todos los módulos están creados y son capaces de establecer comunicaciones entre si_ es como bien decís que pueden conectarse y mandarse mensajes.

De los puntos anteriores se deduce que lo que les pedimos, _para que no lo cuelguen hasta final del cuatrimestre_, es que ya tengan las conexiones, hagan un handshake y empiecen a trabajar pensando en que los procesos se van a comunicar constantemente.

Las funciones del TP0 las pueden usar, para algo se las damos ;)

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @lseijasferraudo! ¿Quedó clara la respuesta de Dami? Saludos

**Comment by lseijasferraudo** [comment]
Sisi quedó claro, muchas gracias

**Comment by RaniAgus** [comment]
¡Buenísimo! Una vez resuelta la duda no olviden cerrar el issue 👮🏻‍♂️
