### ISSUE TITLE
Duda con respecto a ejecutar la comunicación entre módulos

### ISSUE THREAD

**Issue by zakerik10** [sisoputnfrba/foro#3520]
Buenas, tengo una duda con respecto a la ejecución al momento de hacer que se comuniquen los módulos.

Tengo entendido que por ejemplo el Kernel funciona como cliente y servidor.
Al momento de ejecutarlo, como todo esta en un mismo módulo, no creo que sea posible tener 2 consolas corriendo al mismo tiempo, para que uno funcione como server y el otro como cliente. Entonces, ¿Cómo podría hacer para probar después la conexión?

Lo que se me ocurrió hacer, pero no se que tan correcto es, es que al ejecutar, lo primero que hace el Kernel es si ejecutar en "modo cliente" o "modo server", y asi probarlo.

**Comment by iago64** [comment]
Buenas! Cómo va?

Solo para entender un poco, ¿viste el concepto de hilos en teoría? La idea de tener varios hilos de ejecución es que puedas hacer varias cosas a la vez por ej un hilo sea el servidor que acepta las conexiones y otros sean los clientes.

Ahora ya enfocándonos un poco más en el módulo kernel, lo que podés hacer es establecer las conexiones cliente contra al CPU y la memoria y guardarte esos sockets para cuando tengas que hacer algo y después quedarte escuchando nuevas conexiones y a medida que se te conecten las interfaces de I/O también guardar sus sockets y la info que necesites para trabajar con ellas. Después a medida que inicies procesos desde un hilo que puede ser la consola del kernel (aca empiezan a jugar los hilos) empezas a ver que tendrías que pasos tendrías que ir haciendo según lo que te dice el enunciado.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @zakerik10! ¿Quedó clara la respuesta de Dami? Saludos

**Comment by zakerik10** [comment]
Sisi, quedo clara, muchas gracias

**Comment by RaniAgus** [comment]
¡Buenísimo! Una vez resuelta la duda, no olviden cerrar el issue 👮🏻‍♂️
