### ISSUE TITLE
Bloqueo de threads

### ISSUE THREAD

**Issue by Champa123** [sisoputnfrba/foro#3521]
El programa quedaba trancado y no procesaba algo que esperaba que ejecute.
En particular estaba enviando un mensaje a un socket para procesarlo y veia que el programa terminaba sin recibir el mensaje.

**Comment by iago64** [comment]
Buenas! Cómo va?

Solo para entender, ¿A qué te referís con que no loguea bien? ¿Los logs van desordenados? ¿Hay cosas que no se escriben en el log?

Saludos.-

**Comment by Champa123** [comment]
Hay cosas que no se loguean... Estaba revisando parece que tampoco se ejecutan por alguna razon, capaz estoy bloqueando los hilos 🤔

**Comment by Champa123** [comment]
Mmm en Memoria creo 2 threads uno que se conecte y haga handshake al Kernel y otro a CPU.
Intento enviar algo por el CPU y cuando tengo los 2 threads en memoria se queda colgado 🤔 
Puede hacer algo el thread de kernel que bloquee al hilo de CPU ?

**Comment by Champa123** [comment]
Con un solo thread funciona como esperado

**Comment by Champa123** [comment]
mmm Cambie los pthread_join por pthread_detach y parece que funcionó.
Voy a cambiar el titulo a algo mas relevante de threads

**Comment by iago64** [comment]
Buenas! Cómo va?

Efectivamente `pthread_join()` te frena la ejecución del hilo hasta que se termina el hilo que le pasas como parámetro, por eso no te logueaba nada que estuviera después.

Saludos.-
