### ISSUE TITLE
Tamaño de los registros de las instrucciones relacionadas con IO

### ISSUE THREAD

**Issue by Mimito164** [sisoputnfrba/foro#3524]
Estaba haciendo la serialización de algunos mensajes de CPU y me encontré con un problema sobre los tamaños de la información que tengo que serializar.

En la parte de CPU cuando habla sobre las instrucciones de las IO, hace referencia a `Registro Dirección` `Registro Tamaño` y en el ejemplo de las instrucciones a interpretar se ve que le pasa un registro `EAX` o `AX` de forma indistinta. Pero no ocupa la misma cantidad de bytes el `EAX` o el `AX`. ¿Que tamaño tiene el registro dirección/registro tamaño? 

Me queda claro que el ejemplo de las instrucciones a interpretar no representa un código real que vayan a hacer en las pruebas, pero creo que vale la aclaración.

### 📔 Citas del enunciado/videos

> El siguiente ejemplo es solo de las instrucciones, no representa un programa funcional.
> SET AX 1
> [....]
> IO_STDIN_READ Int2 **EAX AX** 
> IO_STDOUT_WRITE Int3 **BX EAX** 

> IO_STDIN_READ (Interfaz, Registro Dirección, Registro Tamaño): Esta instrucción solicita al Kernel que mediante la interfaz ingresada se lea desde el STDIN (Teclado) un valor cuyo tamaño está delimitado por el valor del Registro Tamaño y el mismo se guarde a partir de la Dirección Lógica almacenada en el Registro Dirección.

> IO_STDOUT_WRITE (Interfaz, Registro Dirección, Registro Tamaño): Esta instrucción solicita al Kernel que mediante la interfaz seleccionada, se lea desde la posición de memoria indicada por la Dirección Lógica almacenada en el Registro Dirección, un tamaño indicado por el Registro Tamaño y se imprima por pantalla.

Se puede ver en el orden de los argumentos que en ambas instrucciones primero va el `Registro Dirección` y luego el `Registro Tamaño` y en los ejemplos se usan los registros EAX y AX de forma indistinta.

### 💭 Soluciones posibles

Para mi en un sistema operativo el tamaño de las direcciones es fijo, si es de 32 bit serán direcciones de 32 bit. Pero si tuviera que resolver este inconveniente a la hora de serializar guardaría un int indicando el tamaño del próximo registro, entonces cuando este deserializando voy a saber si viene un `EAX` o un `AX`

**Comment by iago64** [comment]
Buenas! Cómo va?

Los que nos importa de los registros es el valor, es decir un posible script sea:

SET EAX 0
SET AX 50
IO_STDIN_READ Int2 EAX AX

Lo que debería hacer es obtener los valores de EAX y AX y despues con esos valores pedirle al Kernel que ejecute IO_STDIN_READ a la Interfaz Int2 para que lea 50 bytes y los almacene en la posición asociada a la dirección lógica 0.

Obviamente en los scripts no vamos a poner valores que no correspondan, por ej, si la instrucción tiene los registros *X van a ser valores hasta 255, en el caso de los E*X ahi si, son valores entre 0 y 2^32 -1.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @Mimito164! ¿Quedó clara la respuesta de Dami? Saludos

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, ante cualquier consulta pueden reabrirlo o abrir uno nuevo. Saludos
