### ISSUE TITLE
Duda manejar listas

### ISSUE THREAD

**Issue by GregorioOndjian** [sisoputnfrba/foro#3525]
Buenas, estoy viendo de utilizar una lista para implementar la TLB, pensaba usar la función list_find que tiene esta forma:"void *list_find(t_list *, bool(*closure)(void*));" para chekear si el marco esta o no en la TLB, el tema es que no se como hacer clausula. Si es una lista de numeros puedo utilizar una funcion que checkee numeros y devuelva bool y nada mas? o tengo que pensar en otra cosa. 

Muchas graciass. Un saludo.

**Comment by iago64** [comment]
Buenas! Cómo va?

El tema de la funcion clojure, es una función que simplemente recibe un parámetro del tipo de dato del elemento de la `t_list` que tenes y retorna un `bool`, podes buscar un poco mas de "inspiración" en los unit-tests de las listas.
Otra opción que podrías hacer que es mas o menos que el `list_find()` es recorrer la lista con un `list_iterate()` e ir comparando uno a uno los elementos y si encontras el que buscas guardarlo en una variable.

No hay una única forma correcta de hacerlo, asi que de ultima si queres tirar algo en código y consultar mas en concreto no hay problema.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @GregorioOndjian! ¿Quedó clara la respuesta de Dami? También tenemos un [video de nested functions](https://www.youtube.com/watch?v=1kYyxZXGjp0) que te puede interesar. Saludos

**Comment by GregorioOndjian** [comment]
Buenas, si perdón, seguro hoy lo mire hoy. No quería cerrarlo por si me quedaba alguna duda pero puedo cerrar el issue y de última pregunto en otro.

**Comment by RaniAgus** [comment]
No se preocupen, cierren el issue solo si está resuelta la duda

**Comment by GregorioOndjian** [comment]
Aah buenisimo, justo estaba viendo lo que me habia dicho iago, vi los unit test pero la verdad no me quedo muuuy claro. 
Hice algo pero no me compila:
```
int buscarEnTLB(int numeroPagina){

	void buscarPagina(objetoTLB* obejto){
		objeto->numPagina = numeroPagina;
	}
	
	if(list_iterate(listaTLB,(void*)buscarPagina)!= 0){
		int hola = list_iterate(listaTLB,(void*)buscarPagina);
		return 1;
	}else{
		return 0;
	}
}
```
Lo que me sigue dando dudas es el tema del clousure, hice el buscarPagina pero nose si esta bien implementado en el iterate, que es otra cosa que me da dudas: no termino de entender como me devuelve lo que encontro o como meterlo en una variable como me habian sugerido mas arriba.

**Comment by RaniAgus** [comment]
¡Buenas! Primero quiero señalar varias consideraciones a tener en cuenta:

1) ¿Cuál es la idea de `buscarEnTLB()`? ¿Querés obtener un `objetoTLB*` en base a su número de página? ¿Querés saber si existe esa página en la lista? 

Aunque parezca pavo, es importante primero pensar en qué querés hacer y luego hacer una función que se llame acorde a lo que uno espera: capaz ahora no te des cuenta pero dentro de 3 meses cuando estés cerca de la entrega y necesites reusar una función que ya existe o debuggear una, no está tan bueno tener que ir releyendo todo porque no se entiende qué es lo que cada función hace.

En este caso, si realmente esperás `buscarEnTLB()`, quizás lo más apropiado sea retornar un `objetoTLB*`. En cambio, si lo que querés hacer es preguntar si `existeEnTLB()`, puede que lo mejor sea renombrar la función y retornar un `bool`.

También esto es importante porque la operación que quieras hacer sobre la lista puede cambiar según lo que quieras hacer.

2) Prestá atención a la firma de `list_iterate()`, que si te vas al header de las commons (o simplemente posás el mouse sobre la función desde el IDE) verás que es la siguiente:

```c
/**
 * @fn    list_iterate
 * @brief Itera la lista llamando al closure por cada elemento
 */
void list_iterate(t_list *, void(*closure)(void*));
```

La función tiene tipo de retorno `void`. Eso quiere decir que no te devuelve nada. No interesa saber cómo está implementada, alcanza con saber lo que **hace**, en este caso: `Itera la lista llamando al closure por cada elemento`.

Esto quiere decir que este closure que le estás pasando se ejecuta para cada elemento de la lista, y _solo eso_. No retorna nada. Por lo que en un caso muy feliz el compilador te va a tirar un error al compilar o, en el caso no feliz, te va a tirar un warning y el comportamiento va a ser indefinido.

Ahora, analicemos el closure un segundo:
```c
void buscarPagina(objetoTLB* obejto){
	objeto->numPagina = numeroPagina;
}
```
Esto lo que hace es recibir un puntero a `objetoTLB` (que, como vimos en la firma de `list_iterate`, esto se llama para cada elemento de la lista) y hace una **asignación**. Es decir, le asigna a todos los `objetoTLB` de la lista el valor del número de página.

Te sugiero parar la pelota un segundo y con más tranquilidad analizar qué es lo que esperás que haga la función. Como pista, te recomiendo revisar la firma de `list_find()` y `list_any_satisfy()` y ver si es lo que se adecúa a lo que necesitás.

Aunque en un principio no lo parezca, tomarse una pausa para tomar la decisión correcta es mucho más rápido que tirar código e ir probando.

Saludos

**Comment by GregorioOndjian** [comment]
Buenisimo, muchisimo mejor, ahi me di cuenta que estaba haciendo una asignacion je, queria poner == en vez de =. Mas alla de que el planteo este mal, estaba bien llamado"" el clausure en el iterate?

**Comment by RaniAgus** [comment]
No entendí la pregunta, ¿a qué te referís con "bien llamado"?
