### ISSUE TITLE
Manejo archivos de pseudocodigo

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3526]
Buenas, pensamos en que los archivos de pseudocodigo sean archivos .txt pero en las commons no hay muchas funciones para el manejo de estos. El tema de leer el archivo y demás para obtener las instrucciones debemos implementarlo nosotros "a mano"?

**Comment by iago64** [comment]
Buenas! Cómo va?

Si, tienen que implementarlos a mano, solo como dato interesante, los scripts van a tener 1 instrucción por línea, asi que podrían operarlos sabiendo que el delimitador de cada instrucción es el caracter `\n`.

Pueden buscar ejemplos de estos programas en repos de pruebas anteriores, no les van a servir de mucho porque vamos mutando el lenguaje cuatrimestre a cuatrimestre, pero el formato de los archivos es el mismo.

Saludos.-

**Comment by rood8592** [comment]
Y con respecto al envio de instruccion, entiendo que se envia de a una pero el tamaño de las instrucciones puede variar, se podria estandarizar como un string de un tamaño maximo que ninguna instruccion pueda superar (las que son muy chicas quedarian con espacios en blanco) y que cuando llegue utilizando la función de string.h eliminemos el sobrante a derecha. Esto lo pregunto porque la otra alternativa sería hacer un send, recv personalizado por cada instrucción ya que cada uno ocupa distinta cantidad de bytes y hacer un switch gigante.

**Comment by rood8592** [comment]
Ahora que lo pienso el header podria ser la instruccion representada por un numero y podrias mandar un struct que dos char* que sean los registros, sus respectivos length. Eso para las instrucciones que requieren 2 parametros al menos y ace un send y un recv para todas ellas.

**Comment by iago64** [comment]
Buenas!

La forma en la cual van a mandar las instrucciones la pueden definir a gusto de cada grupo, igual si hicieron el TP0 que mandaban el texto que ingresaban por teclado, ese texto era variable, capaz les puede servir de "inspiración" para hacer el envío de las instrucciones.

Saludos.-

**Comment by rood8592** [comment]
Buenas noches, estamos haciendo lo de las instrucciones y para hacerlo, en primera instancia hicimos que la memoria envié la instrucción completa de una línea utilizando la función del tp0 enviarMensaje. La CPU recibe un string, por ejemplo "SET AX 2" y luego a la hora de recibirlo hacemos un string_split para que en la primera posición del array se encuentre la acción únicamente que seria SET en este caso. En switch como no se puede utilizar el string "SET" directamente hicimos una funcion string_to_opcode que convierte ese string en un valor del enum correspondiente a la instrucción, esa función de string_to_opcode son muchos ifs anidados, lo cual nos hace un poco de ruido. Luego de solucionar eso, viene otro problema y es que los registros que se quieren modificar tambien vienen en formato string, entonces tendriamos que hacer otro tipo de conversion, en este caso convertirlo el "AX" por ejemplo a un tipo de dato uint8_t* que es lo que reciben nuestras funciones set,sum, etc para modificar los registros de la cpu.

SPLIT EN LA CPU Y SWITCH

    char** instruccionDesarmada = string_split(instruccion," ");
        int op_code = string_to_opcode(instruccionDesarmada[i]);


        switch(op_code)
        {
            case SET:
                set_8(&registro.AX,atoi(instruccionDesarmada[2]));
            case SUM:
                break;
            case SUB:
                break;
            case -1:
                log_warning(logger,"Instruccion invalida");
            default:
                log_error(logger,"Error al decodificar instruccion");

        }

FUNCION STRING TO OPCODE

    int string_to_opcode(char* instruccion)
    {
        if(string_equals_ignore_case("SET",instruccion))
        {
            return SET;
        }
        else if(string_equals_ignore_case("SUM",instruccion))
        {
            return SUM;
        }
        else{
            return SUB;
        }
        return -1; //case del switchS
    }

**Comment by iago64** [comment]
Buenas! Cómo va?

No entiendo que problema están teniendo, por desgracia si, van a tener muchos `if()` anidados, por eso es importante que sean prolijos y encapsulen este comportamiento en funciones cosa de que puedan asegurarse que funcionan bien.

Solo les diría que tengan en cuenta que para SUM y SUB revisen si el registro que les llega es `_X` o `E_X`, por el tipo de dato.

Saludos.-

**Comment by rood8592** [comment]
Ok, muchas gracias, tendremos eso en cuenta. Cierro el issue para no seguir extendiendolo.
