### ISSUE TITLE
Error al intentar clonar el repo del tp

### ISSUE THREAD

**Issue by saporapo** [sisoputnfrba/foro#3527]
Intento clonar el repositorio para comenzar a trabajar el tp, pero me tira un "fatal: authentication failed..." después de poner mi usuario y contraseña. 

Pese a que seguí las instrucciones de un caso similar en el foro y de integrantes en mi grupo de tp que les pasó lo mismo y lo solucionaron, no me funcionó. Probé habilitando la autenticación de 2fa y generé un token de acceso personal para ponerlo en vez de mi contraseña, pero sigue tirando el mismo error.

**Comment by RaniAgus** [comment]
¡Buenas! ¿Es posible que el token creado no tenga los permisos suficientes para leer y escribir en el repo?

Por ejemplo, acá podés elegir el repo:
![image](https://github.com/sisoputnfrba/foro/assets/39303639/406accd7-19e9-4b86-b6da-69066ee7dd15)

Y acá los permisos de escritura (en "Contents"):

![image](https://github.com/sisoputnfrba/foro/assets/39303639/86c7e11c-1705-4841-9289-366f13603f82)

Saludos

**Comment by saporapo** [comment]
Me parece q no tengo permitido escribir en el repo, tengo deshabilitado poder ver los commits hechos y otras cosas

**Comment by saporapo** [comment]
En la creación del token no me aparece para seleccionar el grupo X al q pertenezco

**Comment by RaniAgus** [comment]
¿Es posible que estés intentando copiar el token desde tu computadora host a la VM y haya algún problema con eso? También tené en cuenta que para pegar algo en la terminal hay que usar Ctrl+**Shift**+V.

Sino otra opción es usar un [token classic](https://github.com/settings/tokens):

![image](https://github.com/sisoputnfrba/foro/assets/39303639/4a8e09c2-0b61-43ec-97c4-b032cb010219)

Con, al menos, todos los permisos de repo:
![image](https://github.com/sisoputnfrba/foro/assets/39303639/b94ac2a3-66e8-4340-ae6f-67267327fc6c)

Saludos

**Comment by saporapo** [comment]
En la terminal de la vm coloco: git clone la url del repo del grupo X desde el github de sisoputnfrba (lo copio y pego con las opciones q se despliegan con el click derecho), me aparece colocar mi usuario saporapo y la contraseña q seria el nombre del token. Doy enter y tira el fatal. Mañana volveré a probar por so cambia algo, talvez necesita descansar la maquina.

**Comment by iago64** [comment]
Buenas! Cómo va?

Cuando decis el nombre del token te referis al string que empieza con `ghp_` no? Osea básicamente el string que solo te muestra 1 vez cuando creas el token:

![image](https://github.com/sisoputnfrba/foro/assets/1622109/a089e3a1-5599-42b8-9eed-4845adb24745)


Saludos.-

**Comment by saporapo** [comment]
Tengo que poner eso?

**Comment by iago64** [comment]
Buenas!

Si, el nombre del token es para que lo puedas reconocer vos, pero el valor que te da acceso es ese string casi imposible de recordar que empieza con `ghp_`

Saludos.-

**Comment by saporapo** [comment]
Gracias, ya funciono xd
