### ISSUE TITLE
Problema con la primera parte

### ISSUE THREAD

**Issue by MarcoIoannisci** [sisoputnfrba/foro#3528]
Buenas me encuentro con un problema del tp 0. Cuando cargo en
`t_config* iniciar_config(void) {
	t_config* nuevo_config = log_create("tp0_log.log", "LOGGER_TP0", 1, LOG_LEVEL_INFO);
        return nuevo_config;
     }`

y despues tengo que imprimir en patalla con `log_info(logger, "Hola! Soy un log");`

me salta un error en la parte log.c
![image](https://github.com/sisoputnfrba/foro/assets/63261451/81470b29-36b4-4040-ac5c-4beeb3dce5b6)

pero si lo hago con un printf el error no salta pero la consola lo escribe como
![image](https://github.com/sisoputnfrba/foro/assets/63261451/6ec0b3dc-2900-49cd-9902-1b6d0c5d042e)
y no estoy entendiendo el error. Por favor responder cuando puedan

Tambien el log.log me queda en blanco, por lo que no se esta guardando lo que se tiene que guardar

**Comment by MarcoIoannisci** [comment]
Encontre mas errores en la consola del stack
![image](https://github.com/sisoputnfrba/foro/assets/63261451/a8f1ed9c-efed-41b6-869a-f554ae2b3ec1)

**Comment by MarcoIoannisci** [comment]
Ya esta, no dije nada, el problema se origino porque no estaba eligiendo la linea de codigo correcta.

**Comment by RaniAgus** [comment]
¡Buenas! ¿Entonces ya está resuelto el problema de esta línea? Que se está creando un log y guardando el puntero en donde se espera un config:
```c
t_config* nuevo_config = log_create("tp0_log.log", "LOGGER_TP0", 1, LOG_LEVEL_INFO);
```
Como mencionamos en la guía de [primer proyecto C](https://docs.utnso.com.ar/primeros-pasos/primer-proyecto-c#errores-de-compilacion), es **altamente recomendable** prestar atención a los warnings del compilador para detectar este tipo de equivocaciones.

Saludos

**Comment by MarcoIoannisci** [comment]
Si si, ya esta resuelto, pero no pude detectarlo solo porque el error me lo tiraba en otro lado.

**Comment by RaniAgus** [comment]
¡Buenísimo! Una vez resuelto el problema no olvides cerrar el issue 👮🏻‍♂️ Saludos

**Comment by MarcoIoannisci** [comment]
Buenas, me salto otro error y aca entiendo cual es, pero no entiendo porque me salta. El problema en el codigo esta aca sino me equivoco
`t_config* iniciar_config(void)
{
	t_config* nuevo_config = config_create("cliente.config");
	if(nuevo_config == NULL){
		perror("Error al intentar cargar el config.");
		exit(EXIT_FAILURE);
	}
	
	return nuevo_config;
}`
