### ISSUE TITLE
Duda sobre uso de registros en instrucciones

### ISSUE THREAD

**Issue by JBDelupi** [sisoputnfrba/foro#3529]
Buenos dias. Tenemos un par de preguntas sobre los registros al ser usados en la ejecución de instrucciones: 

-los distintos tipos de registros se pueden usar en cualquier instruccion? o hay instrucciones que usan exclusivamente numericos y otras de direccion?

-esta bien que tratemos a cada tipo de registro en distintos casos en cada instruccion? nos quedan las mismas validaciones
```c
case SET:
        {
            char* registro_string = (char*)list_get(instruccion->parametros, 0);
            t_registro registro = registro_str_a_enum(registro_string);

            if(registro >= 0 && registro <= 3) {
                uint8_t valor = atoi(list_get(instruccion->parametros, 1));
                contexto->registros[registro] = valor;
            }
            if(registro >= 4 && registro <= 7) {
                uint32_t valor = atoi(list_get(instruccion->parametros, 1));
                contexto->registros_ext[registro] = valor;
            }
            if(registro == 10) {
                uint32_t valor = atoi(list_get(instruccion->parametros, 1));
                contexto->program_counter = valor;
            }
        }
 ```       
-se pueden usar dos tipos distintos de registros en la misma instruccion?

**Comment by iago64** [comment]
Buenas! Cómo va?

Los registros se van a utilizar independientemente de si se usen para un SUM o para un MOV_IN / MOV_OUT, la idea es que si les decimos registro dirección, uds tomen el valor decimal almacenado en ese registro y transformen esa dirección lógica a una dirección física en la MMU.
Esto esta aclarado en el 2do parrafo de la MMU donde decimos:

> Estas traducciones, en los ejercicios prácticos que se ven en clases y se toman en los parciales, normalmente se hacen en binario. Como en el lenguaje C los números enteros se operan independientemente de su base numérica,

Con lo cual, no se compliquen tanto en pensar si es un registro dirección o un regitro de hecho podríamos hacer algo asi como:
```
SET AX 0
MOV_OUT AX AX
```
Y esto debería almacenar el valor 0 ocupando 1 byte en la posición 0 de memoria, o podríamos tener el siguiente ejemplo:
```
SET EAX 16
MOV_OUT EAX EAX
```
Y esto debería guardar el valor 16 ocupando 4 bytes en la posición 16 de memoria.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @JBDelupi! ¿Quedó clara la respuesta de Dami? Saludos

**Comment by JBDelupi** [comment]
si, quedo claro. Muchas gracias
