### ISSUE TITLE
Dudas sobre el Checkpoint

### ISSUE THREAD

**Issue by tomassagrada** [sisoputnfrba/foro#3530]
Buenas tenia algunas dudas sobre el checkpoint y eran:
1_Si las conexiones ya funcionan todas y los módulos se pueden conectar como esta en el esquema ya es suficiente? (aunque no se hayan aplicado por ejemplo hilos aun). La comunicación tiene que mantenerse y ser ida y vuelta de mensajes? (me refiero para el primer check).

2_Una vez que hacemos el Tag, se guarda lo ultimo que teníamos hasta ese momento y podemos seguir trabajando en el main? o si pusheamos algo que cambiase el funcionamiento antes del sábado se cambiaria y el checkpoint quedaría mal?

3_Una vez que el Tag esta hecho hay alguna manera de ver que lo hayamos hecho bien y que el código que se haya mandado de manera correcta?

**Comment by RaniAgus** [comment]
¡Buenas! 
1. Sí, está bien. A esta altura lo más importante es que hayan logrado un avance estableciendo las conexiones y una primera iteración del protocolo de comunicación (o sea, los primeros mensajes entre módulos). Igual si ya lo consiguieron, pueden aprovechar de ver la [charla de threads](https://docs.utnso.com.ar/guias/linux/threads) y la última sección de la [guía de sockets](https://docs.utnso.com.ar/guias/linux/sockets#multiplexando-ando) para ir adelantando :)

2. En el readme del repo van a encontrar un mini-tutorial de cómo crear y subir un tag. Los tags se atan a un determinado commit y sirven principalmente para versionado, así que son independientes de la branch desde la cual se crea. Un ejemplo de esto son los [tags de las commons](https://github.com/sisoputnfrba/so-commons-library/tags), que todos fueron creados a partir de la rama `master` y, como verán, cada uno tiene un commit asociado diferente:

![image](https://github.com/sisoputnfrba/foro/assets/39303639/24d097ad-5c72-47cc-8e62-70ca530c92d3)

3. Sí, en su repo hay una sección de "tags" en la que pueden verlos listados y fijarse si quedaron atados al último commit:

![image](https://github.com/sisoputnfrba/foro/assets/39303639/f1071c8e-a5da-472f-825b-0a49fcd898a3)

Saludos

**Comment by tomassagrada** [comment]
Muchas gracias

**Comment by tomassagrada** [comment]
Buenas tenia una duda sobre esta parte de la respuesta "una primera iteración del protocolo de comunicación (o sea, los primeros mensajes entre módulos)" cuando se habla de mensajes entre módulos es que el cliente mande mensaje (cosa que pudimos hacer), pero también tiene que haber una respuesta del servidor que le llegue al cliente y se muestre?

**Comment by iago64** [comment]
Buenas! Cómo va?

La idea de Cliente y Servidor es para definir quien se conecta a quien, después una vez establecida la comunicación, los mensajes van y vienen entre ambos sin distinción de quien se conectó a quien.
Es por esto que les pedimos en el primer check que establezcan el protocolo, es decir, quien se conecta a quien y quien se queda esperando mensajes de quien aparte del formato de los mensajes.

Saludos.-

**Comment by tomassagrada** [comment]
ah, ok claro entonces con que se establezca la conexión y llegue el mensaje dejando del cliente estaría para el primero. Perfecto gracias.

**Comment by iago64** [comment]
Si la duda esta resuelta, no te olvides de volver a cerrar el issue 👮‍♂️
