### ISSUE TITLE
Error al intentar cargar el config

### ISSUE THREAD

**Issue by matibapti** [sisoputnfrba/foro#3531]
Buenas, a la hora de querer probar las conexiones en la terminal de VSC pareciera estar todo bien. Ahora, cuando quiero pasar a probar por consola; aplico el make a cada modulo para generar el ejecutable y cuando quiero abrir el ejecutable me salta el siguiente error: "Error al intentar cargar el config.: No such file or directory". Desconozco a que se deba, si el error se refiere al config.h de las commons o al archivo config que cree en cada modulo para cargar loas configuraciones.

### 🔎 Búsqueda en foros

Encontré un video en el canal de youtube de SO (C - Shared Library) donde donde trata un error parecido, y para resolverlo recomienda setearlo en la variable de entorno no sin antes verificar las bibliotecas con las que linkea con el comando ldd; cuando realizo esto pareciera no tener ningún problema con la librería commons (adjunto lo arrojado por consola).

### 🐛 Cómo reproducir el error
```
utnso@utnso:~/tp-2024-1c-Grupo-SO-/memoria$ ls
bin  cliente.log  makefile  memoria.config  obj  settings.mk  src
utnso@utnso:~/tp-2024-1c-Grupo-SO-/memoria$ cd bin
utnso@utnso:~/tp-2024-1c-Grupo-SO-/memoria/bin$ ls
memoria
utnso@utnso:~/tp-2024-1c-Grupo-SO-/memoria/bin$ ./memoria
Error al intentar cargar el config.: No such file or directory
utnso@utnso:~/tp-2024-1c-Grupo-SO-/memoria/bin$ ldd memoria
	linux-vdso.so.1 (0x00007ffec95f1000)
	libcommons.so => /lib/libcommons.so (0x00007f4b8cc87000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4b8ca5e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4b8cca8000)
```

**Comment by RaniAgus** [comment]
¡Buenas! Me suena a que estás teniendo un problema de [rutas relativas](https://docs.utnso.com.ar/guias/consola/rutas). Leete la guía y avisanos si te ayudó a resolverlo. Saludos

**Comment by RaniAgus** [comment]
PD: El error ocurre en runtime, así que se refiere a no poder encontrar el archivo config. Si fuera un problema de linkeo, el programa no podría ni empezar a ejecutar.

**Comment by matibapti** [comment]
Perfecto me sirvió la guía de rutas relativas, ya pude solucionarlo. Muchas gracias!!!
