### ISSUE TITLE
Problema en el Logging

### ISSUE THREAD

**Issue by MarcoIoannisci** [sisoputnfrba/foro#3532]
Buenas, me salto otro error y aca entiendo cual es, pero no entiendo porque me salta. El problema en el codigo esta aca sino me equivoco
```
{
	t_config* nuevo_config = config_create("cliente.config");
	if(nuevo_config == NULL){
		perror("Error al intentar cargar el config.");
		exit(EXIT_FAILURE);
	}
	
	return nuevo_config;
}
```

El problema es que parece que no lee el cliente.config, o lo ve vacio, a pesar de que tiene datos.
![image](https://github.com/sisoputnfrba/foro/assets/63261451/155fa925-3609-4adf-9389-65d9db5b7a8d)

**Comment by RaniAgus** [comment]
¡Buenas! ¿Usaste el [debugger](https://docs.utnso.com.ar/guias/herramientas/debugger) para monitorear el estado de las variables hasta llegar a la línea en la que se produce la impresión inválida? 

Veo que en ese código no aparece ninguna línea que diga algo como `log_info(logger, "VALOR leido de la config: (%s)", valor)`, así que te recomendaría arrancar revisando por ese lado, a ver si el valor de esa variable que le pases se está seteando correctamente.

Aclaro que a la variable le puse `valor` a modo de ejemplo, quizás pudiste haber elegido otro nombre, ya eso no puedo saberlo.

Saludos

**Comment by MarcoIoannisci** [comment]
Buenas, si te referis a usar el run a debug entonces si, estoy haciendo el run (client)

en cuanto a lo segundo el log info lo tengo asi:
`log_info(logger,"VALOR leido de la config: %s", valor);`

Esta exactamente igual. (Probe agregarle los parentesis al %s y nada, sigue igual)

**Comment by RaniAgus** [comment]
Usar el debugger va mucho más allá que solo clickear `run (client)`. A lo que me refería a usar las **herramientas** que provee el debugger para chequear el estado de las variables, por ejemplo, usando un breakpoint para frenar en esa línea y chequear a qué apunta `valor`.

En mi anterior comentario te linkeé una guía que está hecha en Eclipse pero deberías poder seguirla para VSCode ya que todos los debuggers tienen las mismas features: poner breakpoints, step into, step over, step return, resume, etc

Este es el link: https://docs.utnso.com.ar/guias/herramientas/debugger

**Comment by MarcoIoannisci** [comment]
Ok, ahora lo leo, pero sigo sin saber cual podría ser el problema cuando tengo la misma linea de código que vos. Cualquier cosa sigo comentando por acá para saber si se arregla o si sigue igual.

**Comment by MarcoIoannisci** [comment]
Buenas, estuve leyendo la guia pero no estaba entendiendola del todo asique me vi un video para que me explicaran mejor lo de los breakpoints en VSC y quede con esto
![image](https://github.com/sisoputnfrba/foro/assets/63261451/6d0603b1-d0f9-4333-9fa1-dbadb760977f) asique por lo que puedo deducir es que no puede leer el valor y no tengo idea de por qué.
En el config tengo 
![image](https://github.com/sisoputnfrba/foro/assets/63261451/8dded52e-4511-44fc-b6c5-2d8da68f0ab9)
y en la linea de código tengo
```
         ip = config_get_string_value(config, "IP");
	puerto = config_get_string_value(config, "PUERTO");
	valor = config_get_string_value(config, "VALOR");
```

**Comment by RaniAgus** [comment]
¡Buenísimo! Recuerden que si la duda ya fue resuelta pueden cerrar el issue 👮🏻‍♂️
