### ISSUE TITLE
Conexión de procesos a través de hilos

### ISSUE THREAD

**Issue by jotab0** [sisoputnfrba/foro#3533]
Buenas noches, estoy intentano establecer la conexión de todos los módulos a través de hilos pero estoy teniendo problemas. Lo que más duda me genera es que el éxito del hilo depene de si uso `pthread_join` en lugar de `pthread_detach`

Dejo a continuación la porción de código donde creo el hilo:

```
int err = pthread_create(&hilo_memoria,NULL,(void*)esperar_memoria_cpu,NULL);
    if (err!=0){
        perror("Fallo de creación de hilo_memoria(cpu)\n");
        return -3;
    }
    pthread_join(hilo_memoria,NULL);

```
Esta es la variable que funciona. La función espera a través de in while(1) que le llegue un mensaje de memoria.  La ejecución si uso `pthread_detach` se corta a pesar de que memoria siga corriendo y aunque ponga un wait(x) luego del hilo, la ejecución se corta directamente.

**Comment by RaniAgus** [comment]
¡Buenas @jotab0! ¿Quedó clara la respuesta de Dami? Saludos

**Comment by iago64** [comment]
Buenas!

La cantidad de código es bastante, pero justo el segment fault es algo que para poder darte una mano se nos complica con solo ver el código, es mucho pedirte que subas el output de Valgrind?

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @jotab0! ¿Pudieron revisar lo que les comentó Dami? Saludos

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, ante cualquier consulta pueden reabrirlo o abrir uno nuevo. Saludos
