### ISSUE TITLE
Duda lectura de instrucciones en memoria

### ISSUE THREAD

**Issue by Champa123** [sisoputnfrba/foro#3534]
No termino de entender bien como obtiene la memoria una instruccion.
Imagino que cuando inicializa el proceso carga las instrucciones correspondientes al archivo pasado por parametro.
Lo que no termino de entender es si las puedo tener en una lista, en un diccionario por ejemplo, o tienen que estar en las paginas de la memoria. De ser en las paginas no termino de entender bien como con el program-counter termino pidiendole a la memoria que instruccion me tiene que devolver.

### 📔 Citas del enunciado/videos
Al momento de recibir la creación de un proceso, la memoria de instrucciones deberá leer el archivo de pseudocódigo indicado y generar las estructuras que el grupo considere necesarias para poder devolver las instrucciones de a 1 a la CPU según ésta se las solicite por medio del Program Counter.

Puedo crear cualquier estructura ?

### 💭 Soluciones posibles
--

**Comment by iago64** [comment]
Buenas! Cómo va?

Para las instrucciones pueden utilizar cualquier estructura que necesiten.

Saludos.-

**Comment by Champa123** [comment]
Osea puedo meter las instrucciones en una lista de char* y obtenerlas mediante el pc?

**Comment by iago64** [comment]
Buenas! Cómo va?

Si, pueden hacer eso.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @Champa123! ¿Quedó clara la respuesta de Dami? Saludos

**Comment by iago64** [comment]
Cerramos el issue por inactividad 👮‍♂️
