### ISSUE TITLE
¿Mi Kernel y Memoria deben soportar muchos procesos entrada/salida a la vez?

### ISSUE THREAD

**Issue by julienf04** [sisoputnfrba/foro#3535]
Buenas! Entiendo que el módulo entrada/salida debe poder conectarse como cliente con los módulos del Kernel y de la Memoria. Y también entiendo que mi Kernel y Memoria deben poder soportar diferentes tipos de interfaces entrada/salida. Mi duda es, sólo se conectará un dispositivo de entrada/salida durante cada ejecución de mi sistema operativo en las pruebas, o se conectarán más de uno?

Por ejemplo, mi TP debe poder manejar que se conecten 2 o más DialFS diferentes y operar con cada uno de ellos por separado sin que colapse mi sistema?

U otro ejemplo, debería poder soportar un STDIN y un STDOUT al mismo tiempo sin que colapse?

**Comment by LeandroCarbajales** [comment]
Buenas!
Te respondería en parte lo mismo que en el issue #3429, no debería haber una limitación en la cantidad ni tipo de interfaces que se puedan conectar a tu sistema. Tener un STDIN y un STDOUT al mismo tiempo seguramente forme parte de una de las pruebas del trabajo :)

Te aclara la duda?
Saludos! 
     Lean

**Comment by julienf04** [comment]
Sí, clarísimo! Muchas gracias Lean ;)
