### ISSUE TITLE
No me reconoce la commons config.h

### ISSUE THREAD

**Issue by francoalanoca** [sisoputnfrba/foro#3537]
Buenas, estoy teniendo problema con correr el tp, si bien hice ejecutar el template de guía inicial de manera exitosa, también logre hace el tp0 correctamente, me encuentro con el problema de que no me estaría reconociendo los config.h pero si los log.h, por lo cual no creo este andando del todo bien, lo cual me pareció raro ya que puede hacer todo lo anterior, mi problema seria algo similar a lo que pasa en #3404  

### 📝 Pasos para reproducir el error

En el .h tengo esto:
```c
#include <stdio.h>
#include <stdlib.h>

#include <utils/utils.h>
#include <commons/log.h>
#include <commons/config.h>

#include "kernel.h"

t_log* kernel_logger;
t_log* kernel_logger_obligatorio;
t_config* kernel_config;
```

### El problema según el run and debug de vsc:
```
gcc -g -Wall -DDEBUG -fdiagnostics-color=always -c -o "obj/config.o" src/config.c -I../utils/src -I./src
In file included from src/config.c:1:
src/config.h:15:1: error: unknown type name ‘t_config’
   15 | t_config* kernel_config;
      | ^~~~~~~~
src/config.c: In function ‘inicializar_config’:
src/config.c:17:21: warning: implicit declaration of function ‘config_create’; did you mean ‘log_create’? [-Wimplicit-function-declaration]
   17 |     kernel_config = config_create("./kernel.config");
      |                     ^~~~~~~~~~~~~
      |                     log_create
src/config.c:17:19: warning: assignment to ‘int *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
   17 |     kernel_config = config_create("./kernel.config");
      |                   ^
make: *** [makefile:42: obj/config.o] Error 1
```

Cabe aclarar que segui los paso que mencionaron hasta la reinstalacion como en #3404 y aun persiste el problema, paso lo que sale por consola por si ayuda:
```
total 72
drwxr-xr-x  3 root root  4096 Apr 18 19:04 .
drwxr-xr-x 49 root root 20480 Apr 18 19:04 ..
-rw-r--r--  1 root root  3695 Apr 18 19:04 bitarray.h
drwxr-xr-x  2 root root  4096 Apr 18 19:04 collections
-rw-r--r--  1 root root  3297 Apr 18 19:04 config.h
-rw-r--r--  1 root root   936 Apr 18 19:04 error.h
-rw-r--r--  1 root root  3729 Apr 18 19:04 log.h
-rw-r--r--  1 root root  1384 Apr 18 19:04 memory.h
-rw-r--r--  1 root root  1016 Apr 18 19:04 process.h
-rw-r--r--  1 root root  8627 Apr 18 19:04 string.h
-rw-r--r--  1 root root  2819 Apr 18 19:04 temporal.h
-rw-r--r--  1 root root  1286 Apr 18 19:04 txt.h


-rwxr-xr-x 1 root root 111248 Apr 18 19:04 /usr/lib/libcommons.so
```
Me recomendaron hasta tener que llegar a volver a instalar la vm por si acaso, pero espero no llegar hasta ese punto jaja.
Desde ya mychas gracias chicos.

**Comment by iago64** [comment]
Buenas! Cómo va?

Es posible que estes teniendo un archivo llamado `config.c` y/o `config.h`? Porque si hay algo que no le gusta ni un poco a C es el hecho de tener archivos con el mismo nombre.

Saludos.-

**Comment by francoalanoca** [comment]
Buenas!! Así es tengo un config.c y un config.h

Probé cambiar de carpetas y ni así le gusta a C jaja, luego de eso probé de cambiarles el nombre a los .c para que no tenga argumento de queja, haciendo el run and debug en cada caso, pero bueno el error aun sigue. En un momento lo agarro pero volvi a cambiar el nombre y no lo agarro mas.


Pd: puede que sea cierto de los los nombres pero yo en la carpeta de utils donde van las funciones generales hay un utils.c y otro utils.h con esos no tiene queja, pero eso imagino porque son los ya venían con el repo

**Comment by iago64** [comment]
Buenas! Cómo va?

El problema es con el nombre del archivo, no con la carpeta donde se encuentra, a veces estas cosas son muy propias del lenguaje, pero justamente el compilador de C dice:
- Tengo que importar `config.h` donde tengo las cabeceras de las funciones y `config.c` donde tengo las implementaciones y de buenas a primeras se encuentra que tiene 2 archivos `config.h` y 2 archivos `config.c` y si bien los compiladores son herramientas muy potentes, este tipo de cosas a veces les joden.

Por esto te decía que cambies el nombre del archivo y no que lo muevas de carpeta, a diferencia de lenguajes como JavaScript que le importa la carpeta donde está el archivo, C, mira el nombre del archivo y gracias, la carpeta si la puede encontrar y no tiene problemas de permisos para leerla, le da exactamente lo mismo.

Saludos.-

**Comment by iago64** [comment]
Buenas!

Si no es un tema de nombre de archivos, podrías subir a un branch del repo el código para poder investigarlo? 
Porque me esta faltando bastante info de como tenes levantado el proyecto, ya que la ejecución de `gcc` no veo que tenga ninguno de los flags que les dejamos en el template de proyecto del repo, como por ejemplo las commons.

Saludos.-

**Comment by francoalanoca** [comment]
### Solucionado

Luego de cambiar los nombres también faltaba la actualización de las líneas iniciales #ifndef #define para que no chocara con el nombre de config de las commons.

Gracias por la paciencia muchachos!!
