### ISSUE TITLE
Duda conexion CPU como servidor y como cliente

### ISSUE THREAD

**Issue by GabrielIacomini** [sisoputnfrba/foro#3538]
Hola buenas,  con mi grupo estamos haciendo las conexiones del modulo CPU. Cuando lo iniciamos como servidor del modulo Kernel, lo dejamos en escucha durante toda la ejecucion, para poder recibir las conexiones del Kernel. Al mismo tiempo, necesitamos que sea ejecutado como cliente para conectarse al modulo Memoria. No sabiamos como hacer para que se siga corriendo como servidor a la espera de conexiones, al mismo tiempo que sea cliente de Memoria. ¿Hay alguna estructura o función que nos estemos comiendo, o estamos entendiendo mal la consigna?

Adjunto código:
Archivo main del CPU:
```c
#include "../include/mainCPU.h"

t_log* logger;

int main(void)
{
	int conexion_memoria;

	char* llegue_bien = "ME CONECTE, SOY CPU";

	char* ip_memoria;
	char* puerto_memoria;
        char* puerto_escucha_dispatch;
        char* puerto_escucha_interrupt;
	char* server_name = "CPU";
	char* ip_CPU;

	t_log* logger;
	t_config* config_CPU;

	/* ---------------- LOGGING ---------------- */
	logger = iniciar_logger_CPU();

	/* ---------------- ARCHIVOS DE CONFIGURACION ---------------- */
	config_CPU = iniciar_config_CPU();
	

	// Traemos todos los valores del archivo de configuracion del modulo CPU -
	ip_memoria = config_get_string_value(config_CPU, "IP_MEMORIA");
    puerto_memoria = config_get_string_value(config_CPU, "PUERTO_MEMORIA");

	ip_CPU = config_get_string_value(config_CPU, "IP_CPU");
    puerto_escucha_dispatch = config_get_string_value(config_CPU, "PUERTO_ESCUCHA_DISPATCH");
    puerto_escucha_interrupt = config_get_string_value(config_CPU, "PUERTO_ESCUCHA_INTERRUPT");
	
	/* ---------------- CPU COMO SERVIDOR ---------------- */
	int server_fd_d = iniciar_servidor(logger, server_name, ip_CPU,puerto_escucha_dispatch);
	int server_fd_i = iniciar_servidor(logger,server_name,ip_CPU,puerto_escucha_interrupt);
	
	log_info(logger, "Servidor listo para recibir al cliente");
	
	while(server_escucha(logger, server_name, server_fd_d));
	while(server_escucha(logger, server_name, server_fd_i));

	/* ---------------- CPU COMO CLIENTE ---------------- */
	conexion_memoria = crear_conexion(ip_memoria, puerto_memoria, logger);

	enviar_mensaje(llegue_bien, conexion_memoria);

	terminar_programa(logger, config_CPU);
	liberar_conexion(conexion_memoria);

}
```

**Comment by ncoen97** [comment]
Buenas!

Si, se estan comiendo algo y es el uso de hilos. Les recomiendo empezar por [esta parte](https://docs.utnso.com.ar/guias/linux/sockets#multiplexando-ando) de los docs.

Saludos.

**Comment by LeandroCarbajales** [comment]
Buenas!
Sumo a las recomendaciones de Nico, además de aprovechar el uso de hilos para poder manejar múltiples servidores (2 en este caso), les recomiendo repensar un poco también la idea de CPU como cliente.
Les dejo un par de preguntas para pensar:
  - Tiene sentido esperar mensajes del Kernel si aun no me pude conectar con Memoria?
  - Siguiendo con lo anterior, en qué momento le mando mensajes a Memoria? Solamente cuando me conecto (handshake y demás) o necesitaré también mandarle mensajes para atender al Kernel?
