### ISSUE TITLE
Problema con inicializar lista

### ISSUE THREAD

**Issue by PabloV2003** [sisoputnfrba/foro#3541]
Hola! nos sale error cuando runneamos el programa con las listas

### 📝 Código relevante

```c
PUERTO_ESCUCHA = config_get_string_value(kernel_config, "PUERTO_ESCUCHA");
    IP_MEMORIA = config_get_string_value(kernel_config, "IP_MEMORIA");
    PUERTO_MEMORIA = config_get_int_value(kernel_config, "PUERTO_MEMORIA");
    IP_CPU = config_get_string_value(kernel_config, "IP_CPU");
    PUERTO_CPU_DISPATCH = config_get_string_value(kernel_config, "PUERTO_CPU_DISPATCH");  
    PUERTO_CPU_INTERRUPT = config_get_string_value(kernel_config, "PUERTO_CPU_INTERRUPT");  
    ALGORITMO_PLANIFICACION = config_get_string_value(kernel_config, "ALGORITMO_PLANIFICACION"); 
    QUANTUM = config_get_int_value(kernel_config, "QUANTUM"); 
    RECURSOS = config_get_string_value(kernel_config, "RECURSOS"); 
    INSTANCIAS_RECURSOS = config_get_string_value(kernel_config, "INSTANCIAS_RECURSOS"); 
    GRADO_MULTIPROGRAMACION = config_get_int_value(kernel_config, "GRADO_MULTIPROGRAMACION");
```
Esta inicializado asi en kernel.h:
```c
char* PUERTO_ESCUCHA;
char* IP_MEMORIA;
int PUERTO_MEMORIA;
char* IP_CPU; //creo que esta mal en la consigna
char* PUERTO_CPU_DISPATCH;
char* PUERTO_CPU_INTERRUPT;
char* ALGORITMO_PLANIFICACION;
int QUANTUM;
char* RECURSOS[];
int INSTANCIAS_RECURSOS[];
int GRADO_MULTIPROGRAMACION;
```
### 💻 Logs

```
src/kernel.c: In function ‘main’:
src/kernel.c:53:14: error: ‘RECURSOS’ has an incomplete type ‘char *[]’
   53 |     RECURSOS = config_get_string_value(kernel_config, "RECURSOS");
      |              ^
src/kernel.c:54:25: error: ‘INSTANCIAS_RECURSOS’ has an incomplete type ‘int[]’
   54 |     INSTANCIAS_RECURSOS = config_get_string_value(kernel_config, "INSTANCIAS_RECURSOS");
      |                         ^
```

**Comment by LeandroCarbajales** [comment]
Buenas!
En primer lugar les recomiendo leer la guía markdown como se recomienda en el Readme de este repositorio para que los issues sean más legibles para todos, en especial, la parte de formatear código y logs que pueden encontrar [acá](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks), en este caso ya se los edité por lo que pueden tomarlo como ejemplo de cómo hacerlo y cómo queda a la vista :)

Para responder la duda en sí, fíjense que el log les dice:
`error: ‘INSTANCIAS_RECURSOS’ has an incomplete type ‘int[]`
Es decir, INSTANCIAS_RECURSOS es de tipo "vector de int" (`int*` o `int[]`) y ustedes están intentando leerlo como un "string" (`char*`).
Algo similar les ocurre con el valor de RECURSOS.

**Comment by RaniAgus** [comment]
¡Buenas @PabloV2003! ¿Pudieron revisar lo que les comentó Lean? Saludos

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, ante cualquier consulta pueden reabrirlo o abrir uno nuevo. Saludos
