### ISSUE TITLE
Duda sobre identificación de interfaces I/O

### ISSUE THREAD

**Issue by marianogq7** [sisoputnfrba/foro#3542]
Buenas, como va??
Nuestra duda es la siguiente, queriamos saber si para la primer entrega hace falta que se puedan conectar y sobre todo identificar cada tipo de interfaz entrada/salida, o simplemente con una interfaz generica para la entrada/salida seria suficiente para este primer checkpoint

**Comment by LeandroCarbajales** [comment]
Buenas!
Por lo pronto, lo importante es que tengan la conexión y comunicación inicial entre los módulos con algún tipo de handshake, identificar el tipo de interfaz no conlleva mucho más que enviar un string o número identificador y tener un switch-case del lado del Kernel por lo que no es definitorio para el checkpoint, pero es algo que tendrán que hacer más temprano que tarde :)

Saludos!
       Lean

**Comment by marianogq7** [comment]
Genial, quedo claro, muchas gracias!

**Comment by iago64** [comment]
Buenas! Si quedo resuelta la duda no se olviden de cerrar los issues 👮‍♂️
