### ISSUE TITLE
Conexiones entre el kernel y la memoria

### ISSUE THREAD

**Issue by mSpadoni** [sisoputnfrba/foro#3543]
hola buenas noches, estaba haciendo las conexiones entre el kernel y la memoria, y me surgió la duda si es que hay que hacer una conexión dispatch y otra interrupt como con el CPU, ya que en lineamiento e implementación del kernel dice eso

**Comment by RaniAgus** [comment]
¡Buenas! Ese fue un error de redacción que ya corregimos en la [última actualización](https://www.utnso.com.ar/1c2024-soporte-sabado-20-y-enunciado-v1-1/). Saludos

**Comment by mSpadoni** [comment]
a ok gracias
