### ISSUE TITLE
Tiempo Límite para entregar CHECKOUT #1.

### ISSUE THREAD

**Issue by AlonsoSalinasLucasA1000** [sisoputnfrba/foro#3544]
Me gustaría consultar si algún horario límite dentro del sábado 20/04 para entregar el primer checkout. Desde ya, muchas gracias.

**Comment by RaniAgus** [comment]
¡Buenas! El tiempo límite es a las 23:59:59:999. Saludos

**Comment by AlonsoSalinasLucasA1000** [comment]
¡Gracias!

**Comment by saporapo** [comment]
si entregué 1hora tarde porque por error en vez de fusionar la rama main con otra para hacer el tag, elimine toda la rama, pero la recupere con el head commit, hice el merge y entregue el tag, lo aceptan?
