### ISSUE TITLE
Ayuda con Segmentation fault

### ISSUE THREAD

**Issue by fornesagus** [sisoputnfrba/foro#3545]
Hola! Cuando corro el trabajo, en el modulo memoria me salta un error de Segmentation fault sobre uno de los commons. No se como solucionarlo. Adjunto foto de lo que me aparece.
Gracias!
![image](https://github.com/sisoputnfrba/foro/assets/164947602/5ea927d0-fe80-4a1d-ba69-966baa684d0b)

**Comment by RaniAgus** [comment]
¡Buenas! Acá:
![image](https://github.com/sisoputnfrba/foro/assets/39303639/ce8a9fe7-47d5-42c8-b52d-d165597ccccc)

podés ver que la variable `value` apunta a la dirección 0x0, es decir `NULL`.

Esto se debe a que acá:
![image](https://github.com/sisoputnfrba/foro/assets/39303639/311cd49d-5eaa-4033-8b71-97d9a8c247b9)

`config_get_string_value()` está retornando un valor apuntando a `NULL`, lo cual me da a entender que el segundo parámetro `key` (que justo no llego a leer el valor en la pantalla de debug) no existe en el archivo config.

Saludos

**Comment by iago64** [comment]
Buenas!

Para sumar un poco a la excelente respuesta de Agus, cuando tengan errores de Segment Fault o cualquier cosa medio extraña de memoria, no se olviden de pegarle una pasada con [Valgrind](https://docs.utnso.com.ar/guias/herramientas/valgrind) al proceso que les trae problemas así pueden ver de donde vienen bien los problemas y así de paso se van a costumbrando a usar esta herramienta que en 1 o 2 meses va a ser un integrante mas de cada grupo.

Saludos.-

**Comment by KiaraDVecchio** [comment]
Buenísimo, ahora entendemos el por qué pasa eso (soy de su grupo), pero seguimos sin entender como solucionarlo. Gracias !
![WhatsApp Image 2024-04-19 at 11 50 55 (1)](https://github.com/sisoputnfrba/foro/assets/164945102/2405b021-0ab9-40c1-9c5d-bf2198d1059a)
![WhatsApp Image 2024-04-19 at 11 51 52](https://github.com/sisoputnfrba/foro/assets/164945102/aa1204e7-d041-4b30-99cd-5adb29d908fd)

**Comment by KiaraDVecchio** [comment]
También probamos el Valgrind, pero seguimos sin tener alguna idea de que hacer.
![WhatsApp Image 2024-04-19 at 12 01 28](https://github.com/sisoputnfrba/foro/assets/164945102/2c24ccc7-e099-4336-b9d1-943783281de9)

**Comment by iago64** [comment]
Buenas! Cómo va?

Primero que nada, por favor eviten las capturas de pantalla con el código, ninguno de los ayudantes es un compilador humano de C, por lo que cuando nos pasen algo para revisar, por favor tomense el tiempito de copiar el código y subirlo, nos ayuda a ayudarlos a uds.

Respecto al error, tomense el tiempo de parar la pelota y analizar, si les llega la dirección `0x0` es porque estan apuntando a null, con lo cual, a partir de ahi se deberían empezar a preguntar:
1.- De donde sacan ese dato?
2.- Con el debugger, veo que lo estoy levantando bien?
3.- Al ser un valor del config, esta levantando bien el archivo y/o la variable?
4.- Si obtiene bien el archivo, el valor de config que busco, existe en el archivo?

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @fornesagus y @KiaraDVecchio! ¿Pudieron revisar lo que les comentó Dami? Saludos

**Comment by fornesagus** [comment]
Holaa, sisi nos sirvió y lo pudimos solucionar. Perdón, se nos pasó
responder.

Gracias por la ayuda!
