### ISSUE TITLE
Protocolo de comunicacion

### ISSUE THREAD

**Issue by Lord-Bardo** [sisoputnfrba/foro#3546]
Que tal, mi duda es que se pretende que hagamos nosotros de este protocolo, dado que las funciones necesarias ya estan hechas en el utils.

### 💭 Soluciones posibles
Yo entiendo que es algo para que tengamos en cuenta nada mas, o sino mandar un msje con el formato de int int void * como prueba?

**Comment by RaniAgus** [comment]
¡Buenas @Lord-Bardo! ¿Quedó clara la respuesta de Dami? Saludos

**Comment by Lord-Bardo** [comment]
Que tal, si quedo claro, muchas gracias.
