### ISSUE TITLE
Duda sobre para que se usan las interrupciones

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3547]
Buenas queriamos saber si las interrupciones entre cpu y kernel solo eran por temas de desalojo del proceso en EXEC porque habiamos pensando con el grupo implementar como una cola de interrupciones pero veo que la unica interrupcion posible es por desalojo. Obvio se pueden implementar distintos tipos de mensaje como INTR_IO INTR_ERROR INTR_EXIT etc etc

Desde ya muchas gracias

**Comment by LeandroCarbajales** [comment]
Buenas!
Exactamente, en el enunciado están especificados los dos casos en que el módulo Kernel le envía un mensaje a través de la conexón _interrupt_ a CPU y ambos son para desalojar al proceso en ejecución, en las secciones "eliminación de procesos" y "planificador de corto plazo".

Saludos!
     Lean

**Comment by GonTurri** [comment]
Entonces no pueden haber 2 interrupciones a la vez? solo tendria que esperar a que llegue la primera y lo desalojo cuando corrresponde?

**Comment by iago64** [comment]
Buenas!

Si hacemos un poco de memoria de lo que vieron en arquitectura, las interrupciones lo único que hace es tener un flag de hubo interrupción.
En el caso del proceso CPU esperamos exactamente lo mismo, que tengan un flag de hubo interrupción y cuando lleguen al paso de _Check Interrupt_ ahi digan: _Tengo una interrupción, le devuelvo el contexto de ejecución al Kernel_ y que sea problema del kernel saber por que se lo devolvieron, que en el TP puede ser por 2 cosas
- Fin de quantum
- Fin del proceso desde la consola del kernel.

Saludos.-
