### ISSUE TITLE
Duda sobre el archivo de configuración interfaz IO

### ISSUE THREAD

**Issue by EstebanHurtado0** [sisoputnfrba/foro#3548]

**Comment by iago64** [comment]
Buenas! Cómo va?

De minima van a tener un config para cada tipo de interfaz, la realidad es que van a tener muchos archivos de config, incluso para las pruebas esta buenisimo que tengan uno armado previamente para cada prueba cosa de hacer las cosas lo mas rápido posible.

Saludos.-

**Comment by EstebanHurtado0** [comment]
Perfecto, eso me quedo claro. Pero como le indicamos al programa que tipo de interfaz iniciar? Eso lo ingresamos por teclado?

**Comment by iago64** [comment]
Buenas!

Esto pueden hacerlo de la forma que gusten, no hay una que este mal, pensando rápido y tomando la opción que mencionas tienen 3 opciones:

1.- Utilizan los parámetros de ejecución del programa y uno de esos parámetros puede ser el tipo de itnerfaz
2.- Se agregan un valor en el archivo de config que diga: TIPO_INTERFAZ y ahi lo definen
3.- Le piden que se ingrese por teclado 

Saludos.-
