### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by FrancoVinaccia** [sisoputnfrba/foro#3551]
Buenas, tenemos un problema al querer conectar la CPU a MEMORIA.
Los servers se inicializan bien, pero cuando se deberia conectar la cpu tira este error.
(edit) Al querer conectar KERNEL a MEMORIA pasa lo mismo

![image](https://github.com/sisoputnfrba/foro/assets/164783682/3cf035e9-0b1e-4b7d-aac2-d18f52f32998)

**Comment by iago64** [comment]
Buenas! Cómo va?

Creo que es un buen momento para recordar que hay un [README.md](https://github.com/sisoputnfrba/foro/blob/master/README.md) que justamente explica un poco como usar el foro y por si eso no fuera suficiente, hay unos hermosos templates que armo @RaniAgus que por ej para un problema de programación en C tiene secciones que nos ayudan a los ayudantes a ayudarlos a uds tales como:

### 📝 Código relevante

### 🐛 Cómo reproducir el error

Y por último, lo que nos subiste (aunque en format incorrecto ya que pedimos explicitamente que no sean capturas de pantalla...
### 💻 Logs


Dicho lo anterior, con 2 capturas de pantalla de un log que escribieron uds y sin código, no puedo hacer mas que decirte que revises la [Guía de Debug](https://docs.utnso.com.ar/guias/herramientas/debugger) a ver por que esta pasando que tienen un segment fault y en segundo lugar si con la [Guía de Debug](https://docs.utnso.com.ar/guias/herramientas/debugger) no conseguis llegas al origen del problema, que recurras al viejo y querido [Valgrind](https://docs.utnso.com.ar/guias/herramientas/valgrind) y nos pases el output **en formato texto** para que podamos ayudarte a ver por que es que estas teniendo un Segment Fault.

Saludos.-
