### ISSUE TITLE
error al buildiar

### ISSUE THREAD

**Issue by MaCejas** [sisoputnfrba/foro#3552]
Hola buenas, estoy intentando buildiar y me salta un error que no tengo idea de como solucionarlo
![image](https://github.com/sisoputnfrba/foro/assets/164409070/0c86d7b2-abc0-4ab2-8285-110e97f3e8c5)

**Comment by RaniAgus** [comment]
¡Buenas!

1) Les recomiendo leer el [README del foro](https://github.com/sisoputnfrba/foro/blob/master/README.md) ya que entre otras recomendaciones se aconseja no subir capturas de pantalla. También en [Mi primer proyecto C](https://docs.utnso.com.ar/primeros-pasos/primer-proyecto-c#errores-de-compilacion) explicamos cómo reportar errores desde VSCode.

2) El error dice, literalmente, que en la línea 36 y 68 de `utils/Servidor/servidor.c` se está referenciando a una variable `logger` que no existe. ¿Declararon la variable en algún archivo? De ser así, ¿cómo la incluyeron?

Saludos

**Comment by RaniAgus** [comment]
¡Buenas @MaCejas! ¿Pudieron revisar lo que les comentaba? Saludos

**Comment by MaCejas** [comment]
Si gracias
