### ISSUE TITLE
Diferencia entre cambio de modo y de conexto

### ISSUE THREAD

**Issue by VEBravo** [sisoputnfrba/foro#3553]
Buenas! Capaz esta pregunta puede estar más relacionada a algo teórico que a algo del enunciado, pero como se menciona le puse la label de enunciado. Quería consultar ¿existe alguna diferencia entre el cambio de modo y el cambio de contexto? o ¿son lo mismo?

**Comment by LeandroCarbajales** [comment]
Buenas!
Si la pregunta es en el contexto del trabajo práctico, en el mismo no están representados los cambios de modo de forma explícita. Si te referís a las clases (en la realidad), te recomiendo rever alguna de clase de repaso de arquitectura y la de Procesos :)

**Comment by VEBravo** [comment]
Perfecto, gracias
