### ISSUE TITLE
Error con vacio

### ISSUE THREAD

**Issue by MarcoIoannisci** [sisoputnfrba/foro#3554]
Buenas, estoy teniendo problemas con este error que me salta de una excepción.
![image](https://github.com/sisoputnfrba/foro/assets/63261451/b4c9ea24-3cc2-4e41-9318-7bc4cd43d44b)
Este error ocurre cuando mando por la consola un valor vacío, pero no se porque, si antes me cortaba bien la consola cuando esto ocurría. Desde ya muchas gracias

**Comment by RaniAgus** [comment]
Buenas, creo que lo que está en este issue te puede servir: #3503. Saludos

**Comment by MarcoIoannisci** [comment]
Eh, estuve buscando en el codigo y esta aca el close del socket
```
int recibir_operacion(int socket_cliente)
{
	int cod_op;
	if(recv(socket_cliente, &cod_op, sizeof(int), MSG_WAITALL) > 0)
		return cod_op;
	else
	{
		close(socket_cliente);
		return -1;
	}
}
```

**Comment by RaniAgus** [comment]
For the record: ya lo vimos en soporte y se debía a que el server no estaba iniciado al momento de ejecutar el client. Cierro el issue.
