### ISSUE TITLE
Duda caso borde en pseudocodigo

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3555]
Hola queria saber si nuestro trabajo debe contemplar estas situaciones:
```
SET AX 5
SET BX 3
JNZ AX 25
SUM AX BX
SET BX 10
```
otro ejemplo parecido:
```
SET AX 5
SET BX 3
JNZ AX 4
EXIT
SET BX 10
```

Del enunciado comprendo que podemos asumir sintaxis y semantica correctas pero me entro la duda para estos casos

### 💭 Soluciones posibles
En el caso de respuesta afirmativa el fetch te devolveria un null ponele y le tendrias que mandar un mensaje al kernel para que te desaloje con motivo ERROR o EXIT

Desde ya muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

En todos los casos los scripts van a estar correctos, en el primer caso, si el script es ese, estaría mal por 2 motivos, el primero es que JNZ te manda a una instrucción inválida y el segundo es que falta la instrucción EXIT.

En el segundo script, tenes una instrucción después de EXIT, cosa que no vamos a hacer, la última instrucción de un script es EXIT.

Saludos.-
