### ISSUE TITLE
Error 404 al intentar acceder al Repositorio

### ISSUE THREAD

**Issue by Th1rdson** [sisoputnfrba/foro#3556]
Hola buenas estoy teniendo problema con el git clone del repositorio. Me llego el email de la confirmacion del repositorio con el link y una vez que abro el link me tira 404 page not found. A mis compañeros tampoco les aparezco en el repositorio pero si me mandaron el link de la confirmacion. 
![Sin título](https://github.com/sisoputnfrba/foro/assets/166052454/cf93aa4c-f347-41fc-ac4d-cf0669636ad2)

![Imagen de WhatsApp 2024-04-19 a las 21 41 50_394620a6](https://github.com/sisoputnfrba/foro/assets/166052454/9d49f85a-9ff5-4906-a853-e3124b7031d5)
La primera imagen es donde me llega el email y la segunda imagen de una compañera que no aparezco. Ya me loguie con el mismo email que me registre en Git.

**Comment by RaniAgus** [comment]
¡Buenas! Esto se debe a que aún no aceptaste la invitación a la organización de GitHub para poder incluirte al team y al repo. De todas formas, no te preocupes, podés reenviarte la invitación desde el mismo sistema. Saludos

**Comment by iago64** [comment]
@Th1rdson Te sirvió la respuesta de Agus?

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, ante cualquier consulta pueden reabrirlo o abrir uno nuevo. Saludos
