### ISSUE TITLE
Dudas de enunciado de IO

### ISSUE THREAD

**Issue by diegohcanetti** [sisoputnfrba/foro#3558]
Queríamos saber si:
1. Cuando se manda a EXIT cuando la interfaz no existe, no esta conectada y/o no acepta la operación hace falta desalojarla de la CPU? Pq en el momento que se realiza el IO la CPU devuelve el contexto y el proceso sigue en estado **EXECUTE**.
2. En el enunciado se comenta que las interfaces son únicas, esta información la utilizamos para poder agregar a listas en Kernel para hacer las verificaciones de arriba y más cositas. Sin embargo nos surgió la duda: Al momento de crear la interfaz, debemos validar que esta no existe? Es decir, no existe otra interfaz con el mismo nombre. En caso de ser necesario, se haría la validación en el Kernel o en Entradasalida?

### 📔 Citas del enunciado/videos

>Todas las interfaces de I/O tendrán un único nombre que las identificará en el sistema, este nombre deberá ser consultado al momento de que una Interfaz se conecte al kernel. Como este nombré será único se utilizará en los programas para identificar a la Interfaz.
Al recibir una petición de I/O de parte de la CPU primero se deberá validar que exista y esté conectada la interfaz solicitada, en caso contrario, se deberá enviar el proceso a EXIT.
En caso de que la interfaz exista y esté conectada, se deberá validar que la interfaz admite la operación solicitada, en caso de que no sea así, se deberá enviar el proceso a EXIT.

>Al iniciar una Interfaz de I/O la misma deberá recibir 2 parámetros:
Nombre: Este nombre será único dentro del sistema y servirá como identificación de la Interfaz dentro del TP.
Archivo de Configuración

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- En el momento que la CPU devuelve el contexto no le debería importar que contexto le vuelve a llegar, en cierta forma la CPU es bastante limitada, solo sabe recibir un contexto y ejecutarlo, si lo devuelve por un motivo X, después cuando le llega un contexto sigue ejecutando, pero no le importa en lo mas mínimo si es el mismo que devolvió u otro.
Ahora al Kernel si le importa y si estas mandando a EXIT un proceso, este no debería estar en EXEC, igual si va a hacer una IO, ya de base debería en principio dejar EXEC y pasar a BLOCK.

2.- No hace falta, justamente les decimos en el enunciado que son únicas para que no se quemen la cabeza pensando en formas de validarlo, simplemente eso no se va a probar.

Saludos.-

**Comment by diegohcanetti** [comment]
En cuanto a la respuesta de la 1), antes de que el Kernel haga esto:
>Al recibir una petición de I/O de parte de la CPU primero se deberá validar que exista y esté conectada la interfaz solicitada, en caso contrario, se deberá enviar el proceso a EXIT.
Ya el proceso debería entrar en BLOCK? En otras palabras, apenas te llegue alguna petición de IO se manda a BLOCK el proceso sin necesidad de validarlo? Ya que nosotros lo que habíamos entendido es que una vez que se chequea que se cumplen las condiciones para hacer el IO, se manda a la cola de BLOCK de **ESA INTERFAZ** al proceso.

**Comment by iago64** [comment]
Buenas!

Creo que estas sobredimensionando el problema, con lo cual vamos por partes. como Kernel, cuando te llega un contexto de ejecución desalojado por IO, lo tenes que sacar de EXEC porque de ahi pueden pasarte 2 cosas:

1- Lo desalojaron por IO y cumple con las condiciones de la IO (Interfaz conectada y función aceptada por esa interfaz) lo pasas a BLOCK y lo pones en la cola de esa Interafaz
2- Lo desalojaron por IO y no se cumple alguna condición de IO lo mandas a EXIT

Saludos.-

**Comment by diegohcanetti** [comment]
Perfecto, me queda claro
