### ISSUE TITLE
Falta agregar RETRASO_COMPACTACION  en el enunciado en la página 27 

### ISSUE THREAD

**Issue by diegohcanetti** [sisoputnfrba/foro#3559]
Debería estar en:
>Al leer el archivo de configuración solo le van a importar las propiedades de:

**Comment by iago64** [comment]
Buenas! Cómo va?

Gracias por avisar, se nos pasó aceptar el comment cuando publicamos la errata, ya quedo listado.

Saludos.-

**Comment by diegohcanetti** [comment]
De nada,
Saludos
