### ISSUE TITLE
BROKEN PIPE, signal SIGPIPE - en función send() del handshake

### ISSUE THREAD

**Issue by Rasco007** [sisoputnfrba/foro#3560]
Hola cómo va, estoy teniendo problemas al conectar la interfaz i/o, me tira BROKEN PIPE, signal SIGPIPE en la función send(). Leí la guía de sockets y vi que para que no tire eso se pone MSG_NOSIGNAL, pero lo que ocurre ahí es que esa función la pasa pero luego cuando chequea si el handshake que esperaba es el mismo que recibió, justamente no son los mismos y me patea para afuera.

Aclaro que la conexión se crea exitosamente, donde falla es ahí.

<img width="1305" alt="Captura de Pantalla 2024-04-20 a la(s) 12 52 22" src="https://github.com/sisoputnfrba/foro/assets/56683567/038de0cb-a0ee-476e-97d0-b6e22d312cff">

Este es el error por escrito que teira la consola debugger:

Program received signal SIGPIPE, Broken pipe.
0x00007ffff7e9f8b0 in __libc_send (fd=4, buf=0x7fffffffdcc4, len=4, flags=0) at ../sysdeps/unix/sysv/linux/send.c:28

Y además mando lo que dice en el primer archivo de callstack(abajo a la izquierda) que falla en send.c:
Could not load source './socket/../sysdeps/unix/sysv/linux/send.c': 'SourceRequest' not supported..

**Comment by iago64** [comment]
Buenas! Cómo va?

Vamos por partes, la más fácil que es la de que no te deja cargar el source es fácil, el código fuente de `send()` no está disponible, simplemente esta la biblioteca compilada y con eso tenemos que arreglarnos.

Respecto al SIGPIPE, es un error que en pocas palabras te dice que del otro lado te cortaron la conexión, con lo cual ahi tengo que preguntar, del lado Kernel, cuando mandan la respuesta del handshake, no le están haciendo `close()` al socket no?

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @Rasco007! ¿Te sirvió la respuesta de Dami?

También vale la pena aclarar que lo que dice en la guía de sockets no sirve para "arreglar" el error, sino más bien para cambiar la estrategia para manejarlo. Como dice Dami, el error sigue siendo que la conexión fue cortada del otro lado, así que por más que le pases a `send()` el flag `MSG_NOSIGNAL`, éste va a seguir retornando un código de error que debe ser manejado apropiadamente. No existe flag que te permita mandar un mensaje por una conexión que ya fue cortada 😅 

Saludos

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, ante cualquier consulta pueden reabrirlo o abrir uno nuevo. Saludos
