### ISSUE TITLE
Error al compilar

### ISSUE THREAD

**Issue by lseijasferraudo** [sisoputnfrba/foro#3562]
Estoy intentando correr el moludo de memoria pero al momento de ejecutar me tira este error y no estoy seguro de que es
investigue un poco y decia que es como que me falta una biblioteca
pero no estoy seguro de como resolverlo
```
 *  Executing task in folder memoria: make all 

make --no-print-directory -C ../utils/ 3>&1 1>&2 2>&3 | sed -E 's,(src/)[^ ]+\.(c|h)\:,../utils/&,' 3>&2 2>&1 1>&3
make[1]: Nothing to be done for 'all'.
gcc -g -Wall -DDEBUG -fdiagnostics-color=always -c -o "obj/main.o" src/main.c -I../utils/src -I./src
gcc -g -Wall -DDEBUG -fdiagnostics-color=always -c -o "obj/memoria_log.o" src/memoria_log.c -I../utils/src -I./src
gcc -g -Wall -DDEBUG -fdiagnostics-color=always -o "bin/tp" obj/main.o obj/memoria_log.o -I../utils/src -I./src -L../utils/bin -lutils -lcommons -lpthread -lreadline -lm
/usr/bin/ld: cannot find -lutils: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [makefile:39: bin/tp] Error 1

 *  The terminal process "/usr/bin/bash '-c', 'make all'" terminated with exit code: 2. 
 *  Terminal will be reused by tasks, press any key to close it. 
```
el codigo lo tengo en "https://github.com/sisoputnfrba/tp-2024-1c-En-casa-compilaba/tree/memoria"
al mometo de ejecutar memoria me tira error

**Comment by FredeHG** [comment]
Hola buenas!

Como estas haciendo para compilar? 
Si con la consola te paras en la carpeta de memoria y ejecutas `make`, te da el mismo error?

**Comment by lseijasferraudo** [comment]
Si, hasta ayer lo compilaba desde el vs y andaba todo bien, probé desde la consola y desde el vs 
Con diferentes versiones del codigo y me rompe igual

**Comment by RaniAgus** [comment]
¡Buenas! ¿Puede ser que hayas clonado el TP en una carpeta con espacios cuya primera palabra es "tp"? De ser así, porfa renombrala para que no tenga espacios porque hay un bug que encontramos en #3492 Saludos

**Comment by lseijasferraudo** [comment]
Seh lo tengo en "tp operativos" ahora cuando pueda pruebo y confirmo, gracias

**Comment by lseijasferraudo** [comment]
ya lo corrobore tuve que eliminar por completo las carpetas y copiarla de nuevo en una que no tenga ese espacio que mencionaste.
gracias
