### ISSUE TITLE
Instrucción SUM, JNZ

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3565]
Buenas noches,
Quisiera preguntar si debe ser posible ejecutar la instruccion "SUM EAX AX" por ejemplo o siempre registro destino y origen siempre seran o los dos uint8_t o los dos uint32_t. De ser posible, que pasaría si se hace "SUM AX EAX" y el EAX es demasiado grande para un uint8_t ?
Y en el caso del jump deberiamos tener en cuenta si se quiere saltar a una instrucción que no existe, por ejemplo si el archivo de pseudocodigo tiene 20 instrucciones y se quiere saltar a una instrucción 40.

**Comment by LeandroCarbajales** [comment]
Buenas!
Sí, debe ser posible sumar registros de distintos tamaños.
Todos los pseudocódigos que les haremos correr en las pruebas serán sintácticamente válidos y sin errores, no necesitan hacer ninguno de los chequeos que mencionás :)

**Comment by rood8592** [comment]
Gracias, lo tendremos en cuenta entonces!
