### ISSUE TITLE
Una duda mas de memoria

### ISSUE THREAD

**Issue by santi-p98g** [sisoputnfrba/foro#3566]
Buenas!

Estaba haciendo trazas de ciertos métodos con varias instrucciones y se me dio este caso:

<img width="565" alt="Captura de pantalla 2024-04-22 a la(s) 16 47 18" src="https://github.com/sisoputnfrba/foro/assets/82118725/3acfb545-a0c0-42fc-b181-0f7cc9865cdf">

Como me habían dicho antes las paginas del proceso no necesitan estar contiguas, pero los datos que se escriben en ellas si verdad?
Ya que por ejemplo en este caso, el string 'HOLASUSANA' quedaría cortado por el '5' que fué escrito antes. No solo eso sino que ademas lo pisaría, escribiendo en el void* con memset por ejemplo.

Las respuestas que se me vienen serían:
1) Esta bien de esa manera, es decir, en ese caso ese string no se podría copiar ya que hay 10 bytes 'seguidos' en las paginas (aunque ellas no estén contiguas) para copiar el string  total. 

2) Si se podría ese caso y deberíamos manejar cada caso y quedan los valores 'cortados'

3) En el caso de arriba, se pisa el '5' para escribir el string, aunque dudo que sea asi ya que estariamos violando el ocupado del byte de ese marco en particular.

Muchas gracias! Espero que se haya entendido.

**Comment by iago64** [comment]
Buenas! Cómo va?

La respuesta mas correcta es la opción 3, ya que en realidad, lo que se marca como libre u ocupado es la página entera y no byte a byte.

Esto hace que si haces el COPY_STRING y después de MOV_OUT se pise el valor de la segunda S de Susana por el 5, que eventualmente es un valor que no se va a ver, por lo que si lo llevamos a una STDOUT ese string verías `HOLASU ANA`, si lo haces al revés y mandas primero el MOV_OUT y después el COPY_STRING, pisarías el valor de 5 por la segunda S de Susana.

Si queres empezar a ver cosas de Memoria, te recomiendo que repases el Capítulo 8 del Silberschatz que habla obre memoria y cualquier duda nos avises.

Saludos.-

**Comment by santi-p98g** [comment]
Perfecto! Ahora reviso el libro para repasar.

Pero entonces en el caso de enteros entonces, se maneja todo con las DL y DF, sin importar si hay ya algo o no.

En el caso de Strings hay que ver el tema de la cantidad de paginas necesarias. 

Pero lo que no me queda claro es, si me viene un COPY_STRING(10B), las paginas son de 4B, necesito 3 marcos/paginas. A partir de la DF que me llegue (Supongamos que es MARCO 2 PAGINA 3 DESPLAZAMIENTO 0), copio en los 3 marcos siguientes (que tengan asignadas paginas del proceso)  a ese MARCO 2? Es decir, los correspondientes a las Paginas 4 y 5? 


Gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Tal cual lo decís, a vos como memoria **no te importa el contenido**, vos tenes que preocuparte por respetar páginas y marcos, después lo que hagan los procesos con su memoria, es problema de los procesos.

Por otro lado, si tu string (HOLA_SUSANA) ocupa 3 páginas, cada una de 4 bytes, vas a tener que ir traduciendo las direcciones de todas las páginas, digamos que en otras palabras, si tu proceso tiene la siguiente tabla:

|Página|Marco|
| :------: | :-----: |
|0|2|
|1|4|
|2|1|

Y la DL es la 0, vos tendrías que arrancar a copiar el string quedándote en cada página lo siguiente:
|Página|Contenido|
| :------: | :-----: |
|0|`HOLA`|
|1|`_SUS`|
|2|`ANA `|

Página 0: `HOLA`
Página 1: `_SUS`
Página 2: `ANA `

Lo que en marcos se traduce en:

|Marco|Contenido|
| :------: | :-----: |
|0|`    `|
|1|`ANA `|
|2|`HOLA` |
|3|`    `|
|4|`_SUS`|

Ya que los marcos se van asignando a medida que se piden y esto hace que no siempre terminen en orden.
No se si con la tabla quedó más claro el punto, cualquier cosa avisame y veo como puedo graficarlo mejor.
Saludos.-

**Comment by santi-p98g** [comment]
Impecable Dami, mil gracias por la explicación.
Creo que me estaba yendo por las ramas jaja.
Saludos!
