### ISSUE TITLE
duda sobre compactacion

### ISSUE THREAD

**Issue by Jcleosenco** [sisoputnfrba/foro#3568]
buenas, como va? tengo la duda en el caso en que tenga que ampliar el tamaño de un archivo y no tengo bloques contiguos. Debería sacarle los bloques que tenía asignados previamente para juntarlos con los nuevos, y así, asignarlos todos juntos? Tanto en el bitmap como con los datos de ese archivo en el archivo de bloques de datos.

Muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

Si, efectivamente vas a tener que mover el contenido de bloques.
Como dato importante, no hay problema con que creen todas las estructuras auxiliares que necesiten, con lo cual pueden ponerse creativos siempre y cuando el resultado termine escrito en los archivos (tanto bitmap como bloques).

Saludos.-

**Comment by ParedesMicaela** [comment]
Hola buenas! Aprovecho que el issue sigue abierto para preguntar qué pasa si no hay suficientes bloques disponibles. Gracias
