### ISSUE TITLE
DUDA CON TAMAÑO DE MEMORIA

### ISSUE THREAD

**Issue by nicolasreypc** [sisoputnfrba/foro#3569]
Buenas tengo una duda acerca del funcionamiento basico de la memoria, como podemos saber el tamaño de la misma?

En un principio pensaba que era el dato que viene en el config llamado TAM_MEMORIA, pero luego lei que este era el espacio de memoria de usuario. Y se dice que este solo puede ser usado por llamadas de CPU e IO. Pero en estos modulos nunca se hace referencia a este espacio, es criterio del grupo decidir cuando utilizarlo?

Ademas agrego una duda que tengo desde el inicio del TP, es necesario dividir las funciones y estructuras del codigo en base a las partes del modulo? Ejemplo, puedo hacer una serie de instrucciones que muevan a un proceso entre las colas de kernel sin distincion. O debo separar las mismas en el planificador de largo plazo y aparte el de corto plazo. Otro ejemplo seria al implementar la MMU, deben ser un grupo de funciones "juntas" o no es necesario?

**Comment by FredeHG** [comment]
Hola buenas!

El modulo memoria contiene un espacio continuo de memoria del tamaño de la configuración, esto lo podes ver como un `malloc(TAM_MEMORIA)`

Ahora cuando usar este espacio de usuario, siempre que se mencione dirección física y dirección lógica, se esta haciendo referencia a la memoria del usuario, que es la memoria asignada a los procesos, por lo que los módulos CPU e IO van a hacer peticiones a la misma mediante las direcciones lógicas

La ultima pregunta no te estoy siguiendo muy bien, podes reutilizar todas las funciones que necesites y estructuras, y estructurar tu código como consideres más optimo, por otro lado en el caso del planificador de largo plazo y corto plazo tene en consideración que los mismos tienen que funcionar concurrentemente y tienen funcionalidades distintas, pero podrías reutilizar la función que mueve de una queue a otra sin problemas. No sé si esto aclara tu duda

Si algo no está claro no dudes en repreguntar, si estas respuestas son suficientes cerremos el issue

Saludos!
