### ISSUE TITLE
El iniciar_planificacion en el kernel es solo para reanudar?

### ISSUE THREAD

**Issue by uriGrif** [sisoputnfrba/foro#3570]
Buenas! Una pregunta sobre el comando iniciar_proceso de la consola del kernel. El enunciado dice que este comando se encarga de retomar la planificación si esta se encuentra pausada.
Mi pregunta seria: arranca pausada la planificación del kernel?
Si yo recien cuando inicio el kernel, ejecuto unicamente el comando:

> iniciar_proceso "path/process"

El kernel ya arrancaría a planificar automáticamente y lo pasaría a ready y después a execute?
O después de ese comando tengo que pasarle otro comando "iniciar_planificacion" para que arranque?

**Comment by iago64** [comment]
Buenas! Cómo va?

En este caso, pueden decidir uds si arranca pausada o no, eventualmente nosotros en las pruebas finales para los scripts que necesitemos pausar algo, vamos a hacerlo explicito cosa de evitar malos entendidos.

Saludos.-
