### ISSUE TITLE
duda con detener planificacion

### ISSUE THREAD

**Issue by nicolasreypc** [sisoputnfrba/foro#3573]
Buenas tengo una duda, en caso de que se quiera iniciar un proceso, pero la planificacion este detenida. Se deberan guardar los datos del mismo hasta que la planificacion este activa y se pueda crear el proceso o pueden ser desechados y hacer como que nunca le llego al kernel la orden de crear ese proceso?

Tambien tengo la duda de que se debe hacer si se quiere crear un proceso pero la memoria esta llena

**Comment by RaniAgus** [comment]
¡Buenas! La funcionalidad de iniciar y detener la planificación es una feature que inventamos (que no existe en ningún planificador real) justamente para poder iniciar varios procesos bajo el mismo t=0 sin ningún apuro a la hora de escribir en la consola. Por lo tanto, todos los procesos que creen con la planificación pausada deben permanecer en NEW hasta que se reanude la misma. Saludos

**Comment by nicolasreypc** [comment]
muchas gracias, pensaba que la funcionalidad de crear proceso tambien se veia pausada, pero ahora entiendo que no.

**Comment by nicolasreypc** [comment]
Tambien tengo la duda de que se debe hacer si se quiere crear un proceso pero la memoria esta llena.

**Comment by LeandroCarbajales** [comment]
En este trabajo no hay ninguna limitación de memoria a la hora de crear procesos ya que los mismos inicialmente no ocupan memoria del espacio de usuario.
