### ISSUE TITLE
Handshake IO-Kernel

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3574]
Buenas tardes,
Estabamos pensando en que a la hora de hacer el handshake de IO con kernel, lo unico que le mandamos en nuestro codigo, por ahora, es el nombre de la interfaz pero no el tipo. Como haría el kernel para saber el tipo para verificar que la instruccion que recibe de la cpu la puede realizar dicha interfaz? Sería valido mandarselo en un paquete el tipoInterfaz y nombreInterfaz a la hora de hacer handshake? Otra que se nos ocurrió es concatenar el nombre de la interfaz con el tipo para enviar un solo string y desarmarlo del lado del kernel (ej. "Generica-NombreInterfazGenerica"). Ambas opciones serían validas? La 2da es más para ahorrar armar el paquete unicamente enviando un tipo de dato simple char*.

**Comment by LeandroCarbajales** [comment]
Buenas!
Veo 2 opciones válidas:
- No enviarle el tipo de interfaz al Kernel y que luego pueda responderle "error" al Kernel si el mismo le pida una IO que esa interfaz no soporta.
- Enviarle el tipo de interfaz al Kernel durante su handshake para que él mismo pueda discernir si la interfaz soporta esa IO. En este punto, cómo lo envían es decisión del equipo, ambas opciones que mencionás son válidas.

**Comment by rood8592** [comment]
Ok, gracias!!
