### ISSUE TITLE
Duda memoria

### ISSUE THREAD

**Issue by nicolasreypc** [sisoputnfrba/foro#3575]
cuál es la diferencia entre el path de instrucciones que le pasa el kernel a la memoria y el path que recibe la memoria desde el config?

 no sé en q momento se usa del de la config

**Comment by iago64** [comment]
Buenas! Cómo va?

Creo que no nos quedó muy claro en el enunciado.
La idea del path de instrucciones que recibe del kernel es un path relativo dentro del repositorio de pruebas, por ejemplo `/prueba1/SCRIPT_1` pero eso solo no te alcanza porque en tu FS no vas a tener una carpeta en el root que se llame `prueba1`, entonces lo que va a terminar pasando es que en la config vas a tener algo del estilo de `/home/utnso/c-comenta-pruebas` que justamente va a ser el path a donde clonaron el repo de las pruebas.

Y la conjunción de ambos path va a darte algo del estilo de `/home/utnso/c-comenta-pruebas/prueba1/SCRIPT_1` que va a ser la ruta absoluta al script que queremos que corra el proceso que acaba de iniciar el kernel.

Saludos.-

**Comment by nicolasreypc** [comment]
Muchas gracias!
