### ISSUE TITLE
Enviar un paquete

### ISSUE THREAD

**Issue by FedericoGSantoro** [sisoputnfrba/foro#3576]
Hola! Como estan? No logre ver esto en un issue y que me lo solucione, les cuento, estoy intentando en kernel enviar el contexto a la cpu para que ejecute las instrucciones, pero cpu al momento de recibir el contexto recibe cualquier dato, no se que problema es.
Al momento de hacer cualquiera de los agregar_a_paquete del otro lado lo que recibo es un -1201243 por ejemplo.

### 🔎 Búsqueda en foros
Busque un poco sobre que podia ser pero no encontre nada que me lo solucione, me decian de revisar el puntero que se le pasa o de revisar si esta bien inicializado el pcb pero al menos el pcb me muestra sus datos por pantalla

### 📝 Código relevante
```
typedef struct{
	uint32_t pc;
	uint8_t ax;
	uint8_t bx;
	uint8_t cx;
	uint8_t dx;
	uint32_t eax;
	uint32_t ebx;
	uint32_t ecx;
	uint32_t edx;
	uint32_t si;
	uint32_t di;
} t_registros_cpu;

typedef struct{
	uint64_t stack_pointer; // puntero a pila del sistema
	uint64_t heap_pointer; // puntero a memoria dinamica
	uint64_t data_pointer; // puntero a memoria estatica
	uint64_t code_pointer; // puntero a instrucciones propias del programa
} t_punteros_memoria;

typedef struct{
	uint32_t pid; // process ID
	uint64_t registro_estados; // registros con los flags
	t_registros_cpu registros_cpu;
	t_punteros_memoria punteros_memoria;
	process_state state;
	blocked_reason motivo_bloqueo;
} t_contexto_ejecucion;

typedef struct{
	uint64_t quantum_faltante; // duracion restante del tiempo de ejecucion
	int io_identifier; // identificador de la entrada/salida correspondiente
	t_contexto_ejecucion contexto_ejecucion;
	char* path_archivo; // archivo con las instrucciones a ejecutar
} t_pcb;

void empaquetar_contexto_ejecucion(t_paquete* paquete, t_pcb* pcb) {
    agregar_a_paquete(paquete, &(pcb->contexto_ejecucion.pid), sizeof(uint32_t));
    agregar_a_paquete(paquete, &(pcb->contexto_ejecucion.registro_estados), sizeof(uint64_t));
    empaquetar_registros_cpu(paquete, pcb);
    agregar_a_paquete(paquete, &(pcb->contexto_ejecucion.motivo_bloqueo), sizeof(int));
}
```

### 🐛 Cómo reproducir el error
Simplemente creo el pcb todo normal pero al momento de empaquetarlo y enviarlo a la cpu se envia mal parece.

### 💻 Logs
```
[INFO] 21:20:21:538 LOG_EXTRA_CPU/(51632:53620): Recibi el contexto de ejecucion
[INFO] 21:20:21:538 LOG_EXTRA_CPU/(51632:53620): -1610607248
[INFO] 21:20:21:538 LOG_EXTRA_CPU/(51632:53620): Envie el contexto de ejecucion
[ERROR] 21:21:01:174 LOG_EXTRA_CPU/(51632:53620): Desconexion de Kernel Modo Dispatch
```
Ese numero es lo que muestra cuando muestro con el log por ejemplo el pid que le envie

**Comment by iago64** [comment]
Buenas! Cómo va?

Una consulta sumamente importante, estas inicializando esos registros con algún valor?
Esto te lo consulto porque en el código no veo ningún valor inicial y lo que suele pasar es que la memoria cuando la reservas toma el valor de lo que había en la memoria y a veces puede ser que sean un valor asi de fruta.

Por las dudas, cuando pasan estas cosas, nunca esta de mas meterte con el debugger a ver que onda los valores en memoria y/o tirarle una pasadita con Valgrind a ver si no metiste la pata con la memoria.

Saludos.-

**Comment by FedericoGSantoro** [comment]
Si, esta bien inicializado, ahora estuve probando algunas cosas y pareceria que lo solucione, por si a alguien le sirve, lo que me pasaba era que al momento de recibir el paquete eso devuelve una lista, y al usar el list_get necesitaba poner adelante * (int *) por ejemplo, eso me lo logro solucionar.
Gracias!
