### ISSUE TITLE
duda obtencion de instrucciones

### ISSUE THREAD

**Issue by luciarizicman** [sisoputnfrba/foro#3577]
Hola, la duda que tenemos con el grupo es de donde se obtienen las instrucciones del módulo de la cpu; si las instrucciones se obtienen del pcb o hay que hacer una solicitud a memoria, o con le propio program counter ya es suficiente. Gracias.

**Comment by iago64** [comment]
Buenas! Cómo va?

Cito la página 16 del enunciado:

> Fetch
La primera etapa del ciclo consiste en buscar la próxima instrucción a ejecutar. **En este trabajo práctico cada instrucción deberá ser pedida al módulo Memoria utilizando el Program Counter** (también llamado Instruction Pointer) que representa el número de instrucción a buscar relativo al proceso en ejecución. Al finalizar el ciclo, este último deberá ser actualizado (sumarle 1) si corresponde.

Saludos.-

**Comment by martinzaj** [comment]
¿Es necesario conectarse a la memoria para obtener la instrucción teniendo en cuenta que recibimos el program counter y contexto a través de la PCB, y que el contador apunta a la instrucción?

**Comment by RaniAgus** [comment]
¡Buenas! Como citó Dami recién, el Program Counter:
> representa el número de instrucción a buscar relativo al proceso en ejecución.

Es decir, la instrucción está cargada en Memoria, no está en el PCB, por lo que si quieren saber cuál es la siguiente instrucción a ejecutar deben consultarle a dicho módulo.

Saludos

**Comment by martinzaj** [comment]
Gracias
