### ISSUE TITLE
Duda sobre el modulo de I/O

### ISSUE THREAD

**Issue by TomasLVUTN** [sisoputnfrba/foro#3579]
Hola, tengo una duda sobre la implementacion de la Interfaz, lo estaba pensando como una funcion general, y en base a la necesidad, se derivaria si es generica, stdin, etc. La duda es que, en el enunciado menciona que la interfaz debe recibir dos parametros, el nombre y el archivo config. El tema es que la generica debera comunicarse con el Kernel, y STDIN con memoria, seria incorrecto agregar el FD de kernel y memoria como parametros a la interfaz (quedando 4 parametros en lugar de 2), gracias

### 📔 Citas del enunciado/videos
Módulo: Interfaz de I/O
Las interfaces de I/O pueden ser varias, en la realidad las conocemos como Teclados, Mouse, Discos, Monitores o hasta Impresoras. Las mismas irán recibiendo desde Kernel distintas operaciones a realizar para determinado proceso, y le irán dando aviso a dicho módulo una vez completadas.
Lineamiento e Implementación
Cada interfaz en la vida real tiene diferentes velocidades, por lo que para simplificar esto en nuestro TP vamos a tener en la configuración del módulo el Tiempo de unidad de trabajo, este valor luego se va a multiplicar por otro valor que va a estar dado según el tipo de interfaz que tengamos, en este TP vamos a trabajar con 4 tipos de Interfaces: Genéricas, STDIN, STDOUT y DialFS.
Al iniciar una Interfaz de I/O la misma deberá recibir 2 parámetros:
Nombre: Este nombre será único dentro del sistema y servirá como identificación de la Interfaz dentro del TP.
Archivo de Configuración

**Comment by iago64** [comment]
Buenas! Cómo va?

Un comentario, por favor cuidado con el hecho de que el texto quede entre `<!-- y -->` porque eso hace que no se lea el texto y de hecho nos llega la notificación del issue vacio 😢 

Respecto a tu pregunta, los file descriptos que se usan para los sockets son cosas que construis vos con tu código como por ej en el tp0.
Los datos de conexión los vas a tener en el archivo de config como IP_KERNEL / PUERTO_KERNEL o como IP_MEMORIA / PUERTO_MEMORIA.

Saludos.-

**Comment by TomasLVUTN** [comment]
Ok, entonces si seria necesario agregarlo en dicha función/procedimiento! Gracias

**Comment by RaniAgus** [comment]
¡Buenas @TomasLVUTN! Paso a patrullar para avisar (para la próxima) que si la duda ya fue resuelta pueden cerrar el issue 👮🏻‍♂️

Si en un futuro ven que algo no terminó de cuadrar pueden tomarse la libertad de reabrirlo o abrir uno nuevo referenciando éste. 

¡Saludos!
