### ISSUE TITLE
Hilos

### ISSUE THREAD

**Issue by tomassagrada** [sisoputnfrba/foro#3580]
Buenas, Ya hecho el checkpoint 1 ahora estamos intentando pasar todo el sistema a conexiones con hilos (porque teníamos entendido que es necesario tenerlo de esta manera) el problema es que por ejemplo ya logramos que memoria pueda mantener múltiples clientes a la vez, pero no llegamos a entender que tiene que suceder en esa conexión, ósea con eso me refiero a si tenemos que encarar el código a que se mantenga la conexión/a que solo se envié un mensaje por conexión/a que por ejemplo el cliente se pueda desconectar manualmente cuando quiera/si la memoria debe poder recibir mas de un mensaje del mismo cliente. Digamos que no llegamos a entender como encarar el código con hilos.

**Comment by iago64** [comment]
Buenas! Cómo va?

Siento que te estas enredando con el tema hilos y mas alla del mal chiste, lo que tenes que pensar es que un hilo tiene que servirte para hacer cosas en "paralelo", con lo cual, si de momento no tenes que por ej bloquearte esperando algo, no hace falta que agregues hilos por que sí.
Ahora bien un ejemplo rápido donde si podes tener un segundo hilo es en la CPU, para estar escuchando por el socket interrupt a que el kernel te avise que tenes una interrupción y que tu hilo solamente sea estar en el `recv()` esperando el mensaje y después setear el flag de `hayInterrupcion` y volves al `recv()`

Saludos.-

**Comment by tomassagrada** [comment]
Claro por ahí no les estaba viendo uso pero trataba de implementarlos forzadamente, gracias.
