### ISSUE TITLE
Duda sobre finalizar proceso

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3581]
Buenas, entiendo que las unicos casos en donde el kernel interrumpe al cpu, es por fin de quantum y cuando desde la consola le doy a FINALIZAR_PROCESO <PID>

Dado el enunciado
### 📔 Citas del enunciado/videos

> Finalizar proceso: Se encargará de finalizar un proceso que se encuentre dentro del sistema. Este mensaje se encargará de realizar las mismas operaciones como si el proceso llegara a EXIT por sus caminos habituales (deberá liberar recursos, archivos y memoria).

En todo el sistema se refiere a que no importa en que cola este el proceso hay que mandarlo a exit, o solo es si se esta ejecutando?
### 💭 Soluciones posibles
En el caso de que halla que finalizarlo, da igual en que cola esté, deberia iterar todas las colas tratandolas como una lista (chau FIFO) y encontrar el pcb que corresponda y mandarlo a exit, pero no se si este procedimiento es muy fiel a la teoria

Desde ya muchas gracias

**Comment by GonTurri** [comment]
Pero es requerimiento del tp ?

**Comment by iago64** [comment]
Buenas!

Si, es requerimiento del TP, por eso está la instrucción FINALIZAR_PROCESO.

Saludos.-
