### ISSUE TITLE
Error con Git: object file is empty, loose object is corrupt

### ISSUE THREAD

**Issue by RaniAgus** [sisoputnfrba/foro#3582]
_Originally posted by @nicolasvultaggio in https://github.com/sisoputnfrba/foro/issues/3578#issuecomment-2074880468_

Perfecto!! Creo que mas o menos entendí, sin embargo, ahora me surgió otro problema, esta vez nada que ver con teoría, si no con github, jamas me había pasado esto, yo abri mi repositorio para ponerme a trabajar ahora, y cuando intente pullear sobre una de las ramas, me devolvio esto:

```
error: object file .git/objects/1e/0ce9df5e9c3fc5dc32730eae1e42768e1ff6b6 is empty
fatal: loose object 1e0ce9df5e9c3fc5dc32730eae1e42768e1ff6b6 (stored in .git/objects/1e/0ce9df5e9c3fc5dc32730eae1e42768e1ff6b6) is corrupt
```
entonces, como quería resolver rapido el problema, pregunte a chatgpt, el cual me dio una serie de instrucciones a ejectuar, estas son:

```sh
cd .git/objects    # para ubicarme en la carpeta de objetos del repo local
ls 1e
rm 1e/0ce9df5e9c3fc5dc32730eae1e42768e1ff6b6 
```
con este ultimo comando, me hizo borrar ese archivo, que yo pense que era el que me estaba generando un problema,
y ahora cuando quiero hacer acciones normales, me aparece:
```sh
fatal: bad object HEAD # cuando hago status

error: object file .git/objects/78/b2ed76e5f9e46bb659b58cb46f2b85b5528ed4 is empty
fatal: loose object 78b2ed76e5f9e46bb659b58cb46f2b85b5528ed4 (stored in .git/objects/78/b2ed76e5f9e46bb659b58cb46f2b85b5528ed4) is corrupt
```
cuando intento hacer pull en una rama

y no se, se varias cosas mas, no se por que se me rompio el repo local de un dia para el otro sin haber tocado nada, y además creo que yo empeore el problema cuando borre ese archivo, hay algo que pueda hacer para trabajar con normalidad?

**Comment by RaniAgus** [comment]
¡Buenas @nicolasvultaggio! Generalmente para troubleshooting suele ser mejor acudir al viejo y confiable StackOverflow: https://stackoverflow.com/a/31110176

Si nada de esto te funciona, también podés probar clonándote de nuevo el repo. En caso de que te quedara algún cambio sin pushear, creo que lo más sencillo será copiar los archivos del repo corrupto al nuevo.

Saludos

**Comment by nicolasvultaggio** [comment]
bueno al final lo clone de nuevo, estaba perdiendo mucho tiempo, pero muchas gracias!!!

**Comment by RaniAgus** [comment]
Ta bien, cierro el issue entonces :)
