### ISSUE TITLE
Duda algoritmos MMU

### ISSUE THREAD

**Issue by GregorioOndjian** [sisoputnfrba/foro#3583]
Buenass, como va? estoy con una duda en torno a la implementacion de los algoritmos de sustitucion de la MMU. No es necesario usar un hilo en donde este la funcion de reemplazo no? A mi me parece que no porque no deberia ser necesario que esta este todo el tiempo atenta ya que solo se va a hacer sustitucion cuando sea TLB MISS y que la memoria no devuelva PF. Estoy en lo correcto? Nose si me explique bien.
Desde ya muchas graciass.

### 📝 Código relevante
```c
int MMU(int dirLogica){
	int numeroPagina = floor(dirLogica/config.tam_pag_memoria); 
	int desplazamiento = dirLogica - numeroPagina*config.tam_pag_memoria;
	objetoTLB* retornoTLB = buscarEnTLB(numeroPagina);
	if(retornoTLB!=NULL){
    log_info(logger, "PID: %d- TLB HIT - Pagina: %d",proceso->pid,numeroPagina );
		return (retornoTLB->numMarco)+desplazamiento;
	}else{
		log_info(logger, "PID: %d- TLB MISS - Pagina: %d",proceso->pid,numeroPagina );
		mandar_numero_actualizado(conexion_memoria,numeroPagina,BUSCAR_MARCO);
		op_code codOp = recibir_operacion(conexion_memoria);
		if(codOp == NUMERO){
     		log_debug(logger,"Entre a numero bien");
			int marco = 0;
			marco = recibir_numero(conexion_memoria);
			if(list_size(listaTLB)<config.cantidad_entradas_tlb){
				agregar_a_TLB(proceso->pid,numeroPagina,marco);
			}else{
				//el algoritmoSustitucion debe estar en un hilo?
				algoritmoSustitucion(proceso->pid,numeroPagina,marco);
			}
		  	return marco+desplazamiento;
    	}
    	if(codOp == PAGE_FAULT){
      		log_debug(logger,"Entre a page fault");
      		int recibo_descartable = recibir_numero(conexion_memoria);
		  	proceso->PC -= 1;
			enviar_contexto_kernel(proceso,PAGE_FAULT);
      		return -1;
    	}
	}
	return -1;
}

```

**Comment by iago64** [comment]
Buenas! Cómo va?

Antes que nada, un consejo, si van a reutilizar el código de TPs anteriores, traten de ver que partes son compatibles y que partes no.
En este TP no tenemos Page Fault ya que no hay memoria virtual.

Saludos.-

**Comment by RaniAgus** [comment]
¿Qué ventajas y desventajas le ves a crear un hilo para hacer el reemplazo?

**Comment by GregorioOndjian** [comment]
Creo q acá no es necesario pq no es que la función siempre tiene que estar "atenta", tipo creo que no habría ninguna ventaja

**Comment by iago64** [comment]
Buenas!

Veo que vas por el camino correcto, en este TP al no tener Page Fault  la TLB es 100% dependiente de que te llegue una petición para que cambie algo y las páginas una vez que estan en memoria, no tenes que cambiarlas porque no se reemplazan, con lo cual, tiene sentido el hilo que este pendiente?

Saludos.-

**Comment by GregorioOndjian** [comment]
No claro, no debería ser necesario. Muchísimas graciass
