### ISSUE TITLE
Condicion de carrera READLINE()

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3584]
Buenas, no se si es tema de mi VM pero, entre los logs del kernel y la consola a veces se nos traspapelan los caracteres y helgrind te tira mil errores de condiciones de carrera en el stdout
```
>: [INFO] 14:28:41:994 Kernel/(5645:5649): PID: 1 - Estado Anterior: READY - Estado Actual: EXEC
```

Este seria un ejemplo donde se nos solapa el readline con el log. Mi pregunta es si hay que sincronizarlos (el >) es el cosito del readline. Pero entiendo que sincronizar esto no es trivial

**Comment by RaniAgus** [comment]
¡Buenas! Quizás lo más conveniente sea setear en false el parámetro `is_active_console` de `log_create()` y, en una nueva consola, tirarle un `tail -f` al log si quieren irlo siguiendo: https://docs.utnso.com.ar/guias/consola/bash#visualizar-archivos

Existe una forma de ir tirando el ">" para abajo al imprimir cada mensaje de log para poder ingresar cosas por consola, pero no creo que valga tanto la pena hacer foco en eso.

Saludos

**Comment by GonTurri** [comment]
Ok! entiendo, pero en la entrega esos logs los tengo que mandar al stdoout? o podes hacer eso de abrirte la consola?

**Comment by RaniAgus** [comment]
¡Se puede! Simplemente abrimos una sesión más de [PuTTY](https://docs.utnso.com.ar/guias/herramientas/deploy#paso-2-despliegue-obligatorio) y abrimos el log desde ahí 👍🏻
