### ISSUE TITLE
Duda caso borde con desconexion de interfaces

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3585]
Buenas! nos surgio una duda sobre el manejo de interfaces, ya que el enunciado nos pide podes manejar su desconexion pero. 
Que pasa si yo ya mande un proceso a bloqueado esperando a que la interfaz termine y justo desconectamos esa interfaz, el kernel no tiene manera de saber cual es la interfaz que se desconecto porque "no le llega nada en el recv" y tampoco se si puedo fijarme cada fd porque puede ser que encuentre otra interfaz que ya se desconecto pero todavia no fue solicitada por cpu. 

# Nuestro tp debe contemplar esta posibilidad?

**Comment by RaniAgus** [comment]
¡Buenas! Leyendo el [manual de recv](https://man7.org/linux/man-pages/man2/recvmsg.2.html) pueden notar que en caso de que el par se desconecte la función retorna menos bytes de los esperados:

> These calls return the number of bytes received, or -1 if an
       error occurred.  In the event of an error, [errno](https://man7.org/linux/man-pages/man3/errno.3.html) is set to
       indicate the error.

> When a stream socket peer has performed an orderly shutdown, the
       return value will be 0 (the traditional "end-of-file" return).

Esto también ocurre si usan `MSG_WAITALL`:

> MSG_WAITALL (since Linux 2.2)
              This flag requests that the operation block until the full
              request is satisfied.  However, the call may still return
              less data than requested if a signal is caught, an error
              or disconnect occurs, or the next data to be received is
              of a different type than that returned.  This flag has no
              effect for datagram sockets.

Saludos

**Comment by GonTurri** [comment]
Disculpa, no se si me explique muy bien :( 
lo que pasa es que tenemos un diccionario que asocia (nombre_interfaz->cola_bloqueados) por cada interfaz o recurso. El tema es que podemos ver eso de los bytes leidos para saber si un cliente se desconecto pero no podemos saber CUAL. 
De todas formas se nos acaba de ocurrir ir compararndo el fd de todas las interfaces conectadas con el fd que leyó menos bytes de lo esperado y de ahi sacarlo. 
Que opinas?

**Comment by iago64** [comment]
Buenas! Cómo va?

Y si en lugar de tener un diccionario que sea nombre_interfaz, cola_bloqueados, arman una lista que tenga FD, Nombre y lista de bloqueados? A veces repensar una estructura te puede evitar horas de pensar un algoritmo y te simplifican el laburo :)

Saludos.-

**Comment by GonTurri** [comment]
Perfecto, seguiremos tus sabios consejos
