### ISSUE TITLE
Implementación de procesos

### ISSUE THREAD

**Issue by Eliaslis** [sisoputnfrba/foro#3587]
Hola! Ando un poco perdido con el tema de como implementar los procesos. Estuve buscando documentación y viendo ejemplos, esto es lo que llegué a codear hasta el momento:
```c
typedef struct{
    uint32_t pc;
    uint8_t ax;
    uint8_t bx;
    uint8_t cx;
    uint8_t dx;
    uint32_t eax;
    uint32_t ebx;
    uint32_t ecx;
    uint32_t edx;
    uint32_t si;
    uint32_t di;
}registros_cpu;
typedef struct{
    pid_t pid;
    pid_t pc;
    int quantum;
    registros_cpu* registros;
}pcb;

typedef struct{
    //stack
    //heap
    //datos
    pcb* pcb;
}proceso;

void iniciar_proceso(){
	int pid = fork();
	pcb* pcb = iniciar_pcb();
	log_info(logger_cliente,"Se crea el proceso <%d> en NEW",pcb->pid); //1er log minimo y obligatorio
}

pcb* iniciar_pcb(){

	pcb* pcb = malloc(sizeof(pcb));
	pcb->pid = getpid();
	pcb->quantum = atoi(quantum);
	pcb->registros = NULL;
	return pcb;	
}
```
Obviamente anda muy verde el tema, quería saber mas que nada que hacer con `stack`, `heap` y `datos`, aunque se acepta cualquier recomendación para las funciones y demás estructuras. Muchas gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Me parece que te estas enroscando demasiado ni bien arrancas.
La idea del TP es **simular** la creación de un proceso, con una estructura que intenta ser un PCB, pero que en el fondo no es mas que una simulación.
En segundo lugar, veo que estas llamando a la funcion `fork()` que la misma lo que hace es hacer una copia de tu proceso posta posta y eso no es lo que se pide en el enunciado.

Te recomiendo que te ponga de acuerdo con tu grupo para ver como se van a dividir las cosas, en principio en el Kernel tienen que empezar a trabajar las diferentes colas de procesos donde deberían guardar esa estructura que definiste como PCB.
Por otro lado, si tienen establecidas las conexiones con CPU, ya deberían empezar a ver como serializar esta estructura y enviarsela a la CPU, ya con eso tienen como para ir arrancando.

Lo que definiste de stack, heap y datos, estan muy lindos para la teoría pero en esta simplificación para que no se maten no lo vamos a usar.

Saludos.-

**Comment by Eliaslis** [comment]
Muchas gracias por las aclaraciones!
