### ISSUE TITLE
Duda sobre incremento de PC y JNZ

### ISSUE THREAD

**Issue by JoaquinBergara** [sisoputnfrba/foro#3588]
Hola buenas tardes! Tenemos una duda con respecto a donde poner el incremento del PC, en la consigna dice que "Al finalizar el ciclo, este ultimo (el PC) debera ser actualizado (sumarle 1) si corresponde". Nosotros tenemos hecho de esta forma, pero hay problemas con la instruccion JNZ, ya que se le suma 1 al valor que setea el JNZ, cayendo en una instruccion incorrecta (osea, una mas adelante).
Pensamos en poner el incremento del PC dentro de la funcion decode_and_execute() pero no le tenemos muy claro por lo que dice en la consigna, ya que no seria el fin de ciclo. Gracias!

    void realizarCicloInstruccion(int fd_conexion_memoria)
    {
    int i=0;
    while(i<3){
    // FETCH (SOLICITA Y RECIBE LA INSTRUCCION)
    t_instruccion instruccion = solicitarInstruccion(registro.PC,fd_conexion_memoria);
    
    // DECODIFICA LA INSTRUCCION Y LA EJECUTA
    decode_and_execute(instruccion);

    //CHEQUEA SI EN EL HILO DE INTERRUPCION LE LLEGO UNA INTERRUPCION

    //check_interrupt();
    
    //SINO LLEGO NADA, CONTINUA LA EJECUCION NORMALMENTE (IP+1 SI NO HAY JUMP)
    registro.PC = registro.PC + 1;
     i++;
        }
    }

- El while(i<3) esta hecho solo para que ejecute 3 instrucciones

**Comment by RaniAgus** [comment]
¡Buenas! La respuesta está en la cita que mencionabas:

> Al finalizar el ciclo, este ultimo (el PC) debera ser actualizado (sumarle 1) **si corresponde**

En el caso de JNZ, no corresponde sumarle uno, ya que como bien decís no se saltaría a la instrucción correcta.

Saludos
