### ISSUE TITLE
Tamaño de los registros en instrucciones SUM, SUB, etc.

### ISSUE THREAD

**Issue by tomipodo** [sisoputnfrba/foro#3589]
Buenas, una consulta. Para las instrucciones como SUM y SUB, que se pasan dos registros. Puede pasar que, por ejemplo, se envíe SUM AX EAX? El primer registro pasado es AX (8 bytes) y el segundo es EAX (32 bytes). Habría que sumarle 32 bytes a un registro de 8 bytes. En el caso de que esto sea posible, que se debe hacer en tal caso? 
Gracias, saludos.

**Comment by LeandroCarbajales** [comment]
Buenas!
Probablemente te sirva la misma respuesta que #3565. Ambos son valores numéricos por lo que deberían poder sumarlos y restarlos sin problemas.

**Comment by tomipodo** [comment]
Perfecto, ahí lo leí, muchas gracias. En el caso de que se ejecute, por ejemplo: SUM AX EAX y AX = 255 y EAX = 3.
AX debería quedar en 2 no?

**Comment by iago64** [comment]
Buenas! Cómo va?

Tranqui, no vamos a pasarnos de los limites de los tipos de datos.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas @tomipodo !
Quedó resuelta la duda?

**Comment by tomipodo** [comment]
Sí, muchas gracias. Perdón pensé que ya lo había cerrado.
