### ISSUE TITLE
Inicializacion PCB

### ISSUE THREAD

**Issue by GabrielIacomini** [sisoputnfrba/foro#3590]
Buenas!, tenemos algunas consultas acerca de la creación de los procesos y su respectiva PCB.
Como primera duda, no estamos seguros si es correcto inicializar el PC en 0 en la misma estructura y luego ir incrementándolo.
Y luego, los registros como se inicializan? 

Esas serian nuestras dudas, gracias!

**Comment by GabrielIacomini** [comment]
En como se inicializan los registros me refiero a que valor le asignamos antes de operar con ellos, no había quedado muy claro.

**Comment by mefederico** [comment]
Hola buenas!

El program counter (también llamado `instruction pointer`) cuando empieza tiene que apuntar a la primera instrucción, esto lo pueden implementar como prefieran, pero en la implementación de JNZ en el parámetro de instrucciones estas se cuentan desde el 0. Esto porque en la realidad las instrucciones van en el espacio de memoria de usuario y el PC no es más que un offset de la misma que empieza en 0

Sobre como inicializar los demás registros, lo normal es hacerlo con 0's en nuestros test no vamos a operar con registros que no hayamos asignado un valor arbitrario previamente

Saludos!
