### ISSUE TITLE
Cola de exit en chekpoint 2

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3591]
Buenas! queria preguntar si se puede implementar la cola de exit ya en este checkpoint, por que la verdad que nos estamos haciendo toda una ingeniera en liberar todos los pcbs en todos los casos que deberia pasar a exit.
Entiendo que el planificador de largo plazo va en el checkpoint 3 pero creeria que lo mas importante es la transicion de new a ready con el grado de multiprogramacion y eso.

Muchas gracias.

**Comment by mefederico** [comment]
Hola buenas!
Obvio, el alcance del checkpoint es lo mínimo que tienen que tener, si quieren/pueden extenderse es mucho mejor para ustedes de esta forma llegar más holgados al final del TP

saludos!
