### ISSUE TITLE
list_get commons listas

### ISSUE THREAD

**Issue by VEBravo** [sisoputnfrba/foro#3592]
Buenas! En las commons de listas hay una funcion que es list_get que devuelve un nodo de la lista dependiendo el index. El primer elemento de la lista sería el 0 no?

**Comment by RaniAgus** [comment]
Podés corroborarlo revisando los [unit tests de `t_list`](https://github.com/sisoputnfrba/so-commons-library/blob/master/tests/unit-tests/test_list.c), o también armando un proyectito simple y probando:

```c
#include <commons/collections/list.h>
#include <stdio.h>

int main() {
    t_list *lista = list_create();

    list_add(lista, "Primer elemento");
    list_add(lista, "Segundo elemento");
    list_add(lista, "Tercer elemento");

    puts(list_get(lista, 1));

    list_destroy(lista);
    return 0;
}

```

Saludos

**Comment by VEBravo** [comment]
Ah muy bien, lo voy a probar con eso. Gracias. Perdón por lo del tag
