### ISSUE TITLE
IO_STDIN_READ

### ISSUE THREAD

**Issue by ElielBejar** [sisoputnfrba/foro#3593]
Buenas! Quisiera saber si entendí bien que desde el módulo interfaz cuando se ejecuta la instrucción stdin_read, el parametro de registro_tamaño es en bytes y lo que tengo que hacer es, del texto que me pasaron por consola, limitar esa cadena al tamaño de ese parámetro? 
Además, quería saber si registro_tamaño incluye el byte que ocupa el fin de cadena '/0' o solo los bytes de los caracteres que el usuario ingrese sin contar el centinela? 

Por ejemplo si escribo "interfaz" en consola y registro_tamaño es 3, si considera al centinela, el texto para enviar a memoria sería "in" porque el tercer byte sería del caracter "/0" pero si no considera al centinela entonces el texto a envíar a memoria sería "int". 

Espero se haya entendido mi duda y desde ya muchas gracias!

### 📔 Citas del enunciado/videos

Desde CPU dice: 
IO_STDIN_READ (Interfaz, Registro Dirección, Registro Tamaño): Esta instrucción solicita al Kernel que mediante la interfaz ingresada se lea desde el STDIN (Teclado) un valor cuyo tamaño está delimitado por el valor del Registro Tamaño y el mismo se guarde a partir de la Dirección Lógica almacenada en el Registro Dirección.

Desde IO dice:
Las interfaces STDIN no van a esperar ninguna unidad de trabajo, ya que las mismas van a quedarse esperando que el alumno ingrese un texto por teclado. Este texto se va a guardar en la memoria a partir de la dirección física indicada en la petición que recibió por parte del Kernel.

**Comment by mefederico** [comment]
Hola buenas! 

No se toma en consideración el `\0` ni se lo deben agregar. En caso que se ingresen datos de más si deben truncarlo. Y no se van a ingresar datos de menos

Saludos!

**Comment by FredeHG** [comment]
Hola buenas, quedo resuelta la duda?
 Podemos cerrar el issue?
 
Saludos!

**Comment by ElielBejar** [comment]
Hola que tal! Sisi Perfecto, aclaró mi duda, gracias!
