### ISSUE TITLE
Creacion de PCB y pasaje de NEW a READY previo a planificar

### ISSUE THREAD

**Issue by nicoopenna** [sisoputnfrba/foro#3595]
En base al próximo checkpoint, el punto del modulo de Kernel que dice: **Es capaz de crear un PCB y planificarlo por FIFO y RR.** Generamos una estructura de PCB, una función que los crea, pero no tengo del todo presente como puedo hacer para que constantemente se puedan ir creando y planificando, y como se debe manejar. Estas funciones hoy las ejecutaríamos en el main, entiendo que a través de algún hilo, pero no lo tengo claro tampoco. Antes de avanzar con la planificación de los procesos quería entender si estábamos haciendo bien la creación de los PCBs y si teniamos todos los datos necesarios.

Use las commons de Colas, con algunas validaciones en base al enunciado. Lo tengo separado en 2 archivos kernel.c y kernel.h.  Los estados posibles los tengo en los utils en estados.h.

### 📝 Código relevante
```
estados.h
typedef enum {
    NEW,
    READY,
    BLOCKED,
    EXEC,
    EXIT
} estado_proceso;

kernel.h
typedef struct
{
    int PID;
    uint32_t program_counter;
    int quantum;
    CPU_Registers cpu_registers;
    estado_proceso estado;
} PCB;

kernel.c
int main(int argc, char *argv[])
{
    decir_hola("Kernel");

    crear_logger();
    crear_config();

    // Creo la cola que voy a usar para guardar mis PCBs
    cola_new = queue_create();
    cola_ready = queue_create();

    // Creo un PCB de Quantum 2
    crear_pcb(2);
    crear_pcb(1);
    mover_procesos_ready();
}

// Requisito Checkpoint: Es capaz de crear un PCB y planificarlo por FIFO y RR.
void crear_pcb(int quantum)
{
    PCB *pcb = malloc(sizeof(PCB));
    if (pcb == NULL)
    {
        printf("Error al crear el PCB\n");
        return NULL;
    }
    // Incrementar el PID y asignarlo al nuevo PCB
    ultimo_pid++;
    pcb->PID = ultimo_pid;
    pcb->program_counter = 0;
    pcb->quantum = quantum;
    pcb->estado = NEW;
    // El PCB se agrega a la cola de los procesos NEW
    queue_push(cola_new, pcb);
    // Crear un buffer para almacenar el mensaje con el último PID
    char mensaje[100];
    // Usar sprintf para formatear el mensaje con el último PID
    sprintf(mensaje, "Se crea el proceso %d en NEW\n", ultimo_pid);
    log_info(logger, mensaje);
}
/*En caso de que el grado de multiprogramación lo permita, los procesos creados podrán pasar de la cola de NEW a la cola de READY,
caso contrario, se quedarán a la espera de que finalicen procesos que se encuentran en ejecución*/
void mover_procesos_ready()
{
    // Obtener el grado de multiprogramación del archivo de configuración
    int grado_multiprogramacion = config_get_string_value(config, "GRADO_MULTIPROGRAMACION");

    // Calcular la cantidad de procesos en la cola de NEW y en la cola de READY
    int cantidad_procesos_new = queue_size(cola_new);

    int cantidad_procesos_ready = queue_size(cola_ready);

    // Verificar si el grado de multiprogramación lo permite
    if (cantidad_procesos_ready < grado_multiprogramacion)
    {
        // Mover procesos de la cola de NEW a la cola de READY
        while (cantidad_procesos_new > 0 && cantidad_procesos_ready < grado_multiprogramacion)
        {
            // Seleccionar el primer proceso de la cola de NEW
            PCB *proceso_nuevo = queue_peek(cola_new);
            // Borro el proceso que acabo de seleccionar
            queue_pop();

            // Cambiar el estado del proceso a READY
            proceso_nuevo->estado = READY;

            // Agregar el proceso a la cola de READY
            queue_push(cola_ready, proceso_nuevo);
            cantidad_procesos_ready++;

            // Reducir la cantidad de procesos en la cola de NEW
            cantidad_procesos_new--;
        }
    }
    if (cantidad_procesos_new == 0)
    {
        printf("Ya no hay más procesos en la cola de NEW.\n");
    }
    else
    {
        printf("El grado de multiprogramación máximo ha sido alcanzado. %d procesos permanecerán en la cola de NEW.\n",cantidad_procesos_new);
    }
}
```

**Comment by mefederico** [comment]
Hola buenas!

La creación de procesos en kernel se realiza mediante la consola interactiva, por lo cual deberían poder implementarla y crear los procesos con ella

Y sobre la estructura del PCB con que tenga los datos mínimos ya deberían poder implementar toda la planificación, si requieren algo extra son libres de agregarlo

Saludos!

**Comment by mefederico** [comment]
Citando el enunciado en la parte de [creación de procesos](https://docs.google.com/document/d/1-AqFTroovEMcA1BfC2rriB5jsLE6SUa4mbcAox1rPec/edit#heading=h.cetbpcw9maei)

> En caso de que el grado de multiprogramación lo permita, los procesos creados podrán pasar de la cola de NEW a la cola de READY, caso contrario, se quedarán a la espera de que finalicen procesos que se encuentran en ejecución.

Van a tener que chequearlo cuando cambie el grado de multiprogramación de la forma que les parezca más apropiado/fácil

**Comment by nicoopenna** [comment]
Buen dia, te hago otra consulta, el archivo de pseudocodigo que va a tener las instrucciones del proceso, podria guardarse dentro del PCB o se debe enviar por separado en otra estructura? Es decir, al CPU, podria enviarle solo el PID, y el path al archivo en una estructura?

**Comment by iago64** [comment]
Buenas! Cómo va?

La idea es que el archivo de pseudocódigo lo tengan abierto en la memoria y a medida que la CPU pide las instrucciones se las van mandando de a 1, despues si en el PCB tienen el path del archivo o el PID, depende de la implementación de cada grupo.
Personalmente creo que ya al llegarles el iniciar desde el Kernel podrían tener una lista de "procesos" donde tengan cada PID y el listado de instrucciones ya cargado y _separado_ por instrucciones.

Saludos.-

**Comment by FredeHG** [comment]
Hola @nicoopenna quedo resuelta la duda? Podemos cerrar el issue?

**Comment by nicoopenna** [comment]
Hola, buen dia, disculpen no vi la respuesta. Si, me queda claro.
Gracias y saludos!
