### ISSUE TITLE
Solicitud de instrucciones de CPU a Memoria

### ISSUE THREAD

**Issue by GabrielIacomini** [sisoputnfrba/foro#3596]
Buenas! tenemos una duda acerca de como es la solicitud de instrucciones entre la CPU y la Memoria. Tenemos un archivo de instrucciones, y ese archivo es recibido por la memoria para luego guardar esas instrucciones en una lista de instrucciones. Ahora viene nuestra duda, la CPU le especifica la cantidad de instrucciones que va a ejecutar, a través del program counter? y ese program counter como va siendo incrementado ?

Gracias !

**Comment by mefederico** [comment]
Hola buenas!

Citando el enunciado, en la seccion de CPU [fetch](https://docs.google.com/document/d/1-AqFTroovEMcA1BfC2rriB5jsLE6SUa4mbcAox1rPec/edit#heading=h.q2snlo6kh4e9)

> Fetch
La primera etapa del ciclo consiste en buscar la próxima instrucción a ejecutar. En este trabajo práctico cada instrucción deberá ser pedida al módulo Memoria utilizando el Program Counter (también llamado Instruction Pointer) que representa el número de instrucción a buscar relativo al proceso en ejecución. Al finalizar el ciclo, este último deberá ser actualizado (sumarle 1) si corresponde.


Se indica que debe pedir de a una instruccion, y el incremento se hace de a uno, con la excepcion de la instruccion JNZ que actualiza el PC, issue relacionado: https://github.com/sisoputnfrba/foro/issues/3588

Saludos!

**Comment by GabrielIacomini** [comment]
Buenisimo graciass!
