### ISSUE TITLE
Dudas sobre funcionamiento de memoria

### ISSUE THREAD

**Issue by nicolasvultaggio** [sisoputnfrba/foro#3597]
Tengo MUCHAS dudas sobre como va a funcionar la memoria, mas o menos tengo unas ideas pero siento que falta teoría para entender como implementarlo:

Yo lo que entiendo es que la memoria va a recibir peticiones de Kernel para:
cuando se cree un proceso, se abra el archivo de pseudocodigo y se lean las instrucciones, estas instrucciones se tienen que guardar en alguna estructura para ir devolviendolas a la cpu a medida que vaya pidiendolas.

Cuando la cpu pide una instruccion, se usa el pid y el pc del la informacion que nos pasa la cpu para buscar la instruccion de dicho proceso.

![image](https://github.com/sisoputnfrba/foro/assets/131707089/7d4f4730-c07e-4ad7-89e8-6fbedbb707d6)

Entonces leo eso y pienso, como guardamos las instrucciones? bueno, se supone que la memoria solo conoce STRINGS como instrucciones, entonces, las paginas son simplemente una cantidad de bytes fija que se usar para guardar los strings de instrucciones continuamente.

Entonces, ese (void*) que dice que es una parte de la estructura de la memoria, es el lugar donde se guardan los marcos, o sea las direcciones fisicas que contienen instrucciones a utilizar mas rapido.

Pero despues menciona las tablas de paginas, y eso me hace pensar, hay que simular una memoria externa que, esta si, guarda TODOS LOS procesos que se conocen, o sea las direcciones logicas? Se supone que, primero se debería chequear en una tabla de páginas, si la página que contiene una instruccion esta guardada en un marco, o sea una direccion física, y si no, buscarla en la memoria externa, y chequear si hay que reemplazar el contenido del marco, que HACE la mmu de la cpu? y la TLB? como se relacionan con la tabla de paginas?

en sí mi duda es, como es que se supone que secuencialmente deben trabajar la cpu, (o sea, la mmu y la tlb) y la memoria (tabla de paginas) cada vez que se quiere buscar una instruccion, como es que se usa esta traduccion de direcciones logicas a físicas, porque son conceptos que recuerdo de arquitectura, pero ahora mismo no entiendo muy bien como aplicar.

todavía vamos a ver conceptos teóricos en clase sobre esto? porque esto que estoy queriendo saber es super necesario para el checkpoint dos.

**Comment by nicolasvultaggio** [comment]
sobre esa ultima pregunta que tengo, es para saber, específicamente qué partes teoricas son necesarias para el checkpoint 2, sobre la secuencia que pregunto

**Comment by mefederico** [comment]
Hola buenas!

Como bien dice el enunciado en la sección de [Memoria instrucciones](https://docs.google.com/document/d/1-AqFTroovEMcA1BfC2rriB5jsLE6SUa4mbcAox1rPec/edit#heading=h.8fe1iyjh7574)

> generar las estructuras que el grupo considere necesarias para poder devolver las instrucciones de a 1 a la CPU según ésta se las solicite por medio del Program Counter.

Esto se refiere a que las instrucciones van a estar en estructuras aparte del espacio de usuario, a diferencia de como sucede en la realidad en donde las instrucciones si están en el espacio de usuario y el PC es un puntero de dirección lógica donde esta la siguiente instrucción

La parte de espacio de usuario y paginas, lo que hace la MMU y demás, es necesario para el 3er checkpoint y lo van a ver después del primer parcial

Saludos!

**Comment by mefederico** [comment]
Para completar mi respuesta, en el alcance del tp la memoria de usuario está destinada a las variables de los programas.

Si igualmente quieren/pueden avanzar con esta parte del tp pueden leer el Capítulo 8 del Silberschatz 

Te dejo un issue que tiene una duda puntual de memoria capaz eso te aclare para que es cada cosa https://github.com/sisoputnfrba/foro/issues/3566

Ahora si, saludos!

**Comment by nicolasvultaggio** [comment]
buenisimoo, me re sirvio esa respuesta del otro issue, muchas gracias!

**Comment by FredeHG** [comment]
Cerremos el issue una vez que quedan las dudas saldadas, saludos!
