### ISSUE TITLE
Commons t_queue me tira segfault en el pop 

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3599]
Buenas! meprobando el tema de finalizar proceso en cualquier cola y en cualquier instante, nos salto que al hacer pop las colas pueden estar vacias y para sorpresa tiraba segfault al hacer pop a una cola vacia, por ahora fuimos agregando varios if preguntando por el largo de la cola en varios lados, pero quizas es mejor si en mi funcion queue_sync_pop pregunto por el largo de la cola y devuelvo null para evitar esto. 
Estamos cometiendo algun error o esta funcionalidad es intencional?

```c
static void *list_remove_indirect(t_list *self, t_link_element **indirect) {
	t_link_element *element = list_unlink_element(self, indirect);
	void *data = element->data;
	free(element);
	return data;
}

```

creeria que es ahi si ese list_unlink element te da null ahi te tira el segfault

**Comment by RaniAgus** [comment]
¡Buenas! El comportamiento es correcto: si intentás quitar un elemento que no existe el programa falla al intentar acceder a un campo de un puntero nulo.

¿Estás seguro que querés que tu función wrapper pueda retornar `NULL`? Cuidado con eso porque deben ser prolijos desde cualquier lugar que la usen y contemplar ese escenario adecuadamente porque sino podrían tener el segfault en otros lugares.

Chequear si la queue está vacía puede no necesariamente ser la solución. También cuentan como alternativa el hecho de pensar a la queue como un **recurso** compartido del cual un hilo es **productor** (va pusheando valores a la lista) y el otro es **consumidor** (va pulleando dichos valores). Si ya vieron sincronización en la teoría probablemente les suene este concepto.

Entonces el consumidor simplemente se bloquea hasta que hayan nuevos valores, y a medida que el productor los va insertando éste le va dando luz verde para consumir la queue sin disparar ningún error ni estar constantemente chequeando que no esté vacía. 

De todas formas, repito, es solo una alternativa más, quizás para su caso les sirva solamente chequear si la queue está vacía o no, eso es decisión de implementación suya y cualquiera va a estar bien siempre y cuando no tengan esperas activas o memory leaks.

Saludos

**Comment by GonTurri** [comment]
No, me gustaría hacerte caso para aprovechar tu buen juicio, hicimos ese semáforo por ejemplo para la cola de ready, pero no lo planteamos para las demás colas. Además ese semáforo de ready ya lo estamos manejando entre 3 hilos y aveces se nos generan como "condiciones de carrera" en el semáforo, así que como que rompe el esquema de productor consumidor. O quizás estoy medio flojo con la teoría de sincronización 

Seria cada vez que agrego a la cola 
sem_post(sem_cola)

Cada vez que popeo de la cola 
sem_wait(sem_cola)

Otra vez por ejemplo en finalizar proceso por Pid tendría que hacer ese wait y al tener al planificador en otro hilo puede ser que el kernel haga wait antes y se me bloquee la consola

Espero no haberte abombado con todo esto

**Comment by iago64** [comment]
Buenas! Cómo va?

Si se te estaban dando condiciones de carrera en semáforos es posible que te falte repasar un poquitin la teoría de sincro, igual, algo bastante interesante de las "colas de planificación" es que si bien por definición son colas porque el primero que entra es el primero que debería salir, siempre pueden jugar con las listas de las commons que les pueden permitir cosas como iterarlas y revisar cada elemento con funciones como `list_iterate()`.

**Comment by GonTurri** [comment]
Está bien,trataré de pensar más y cualquier cosa mando otro issue
