### ISSUE TITLE
Duda con funcion list_get_maximum

### ISSUE THREAD

**Issue by GregorioOndjian** [sisoputnfrba/foro#3600]
Buenas, estoy haciendo la parte del algoritmo de sustitución de la TLB, mas especificamente el algoritmo LRU.
Tengo algunas dudas con la funcion list_get_maximum: que en las commons esta asi:

```c
       /*
	* @fn    list_get_maximum
	* @brief Retorna el maximo de la lista según el comparador
	*
	* @note El comparador devuelve cuál es el máximo de dos valores
	*/
	void *list_get_maximum(t_list* self, void* (*maximum)(void*, void*));
```
Por un lado no entiendo bien dnd me devuelve el maximo y de que forma(si me devuelve el index o que) ya que la funcion es void, por el otro, el comparador seria la funcion que hago yo para comparar 2 valores especificos no? y deberia ponerlo en la partecita que dice (*maximum).
Por ultimo, me dan dudas los void de la ultima parte. Esos siempre se dejan tal cual?
Desde ya muchas graciass (perdon por preguntar tanto je).

**Comment by FredeHG** [comment]
Hola buenas!

Vamos por parte, lo primero para hacer cita de código es tres de estas comillas y no las que pusiste ```

Ahora con la consulta: la función, no devuelve `void`, sino que devuelve `void *`  por lo que te devolvería el struct o lo que sea que hayan guardado en la lista, un `void*` es un puntero a una posición de memoria cualquiera

Una cosa divertida de las commons es que tienen test donde podes ver como usar las funciones https://github.com/sisoputnfrba/so-commons-library/blob/d22eb0076cc863bcbb7edbdf47ef43e6d434ffc6/tests/unit-tests/test_list.c#L783

Ahí vas a ver que el segundo parámetro es una función que recibe 2 elementos de lo que sea que hayas guardado en la lista y retorna cual es la más grande

Saludos!

**Comment by GregorioOndjian** [comment]
Claro, buenísimo ahora lo miro bien. Muchas graciass.

**Comment by iago64** [comment]
Buenas @GregorioOndjian ! 

Solo para checkear, quedo resuelta la duda o dejas el issue pendiente para checkear si funciona todo y después si todo sale bien lo cerramos?

Saludos.-

**Comment by GregorioOndjian** [comment]
Dejo el issue pendiente para cuando lo vea bienn.
Graciass
