### ISSUE TITLE
Diferencias entre Programs Counters

### ISSUE THREAD

**Issue by eonishi** [sisoputnfrba/foro#3602]
Buenas, tenia una duda con respecto al program counter. En el enunciado cuando se habla de los datos minimos que debe de tener el PCB menciona la existencia de un PC. Después en el módulo de CPU cuando hablan de los registros del mismo vuelven a mencionar la existencia de un PC. Mi duda viene por ese lado, 
+ ¿tienen alguna relación directa uno con otro?
+ ¿es necesario declararlo dos veces (teniendo en cuenta que los propios registros estarán dentro del PCB)?
+ ¿son el mismo PC?
+ ¿Si no son el mismo o son el mismo pero necesito diferenciarlo de alguna forma, por qué necesitaria hacerlo?

### 📔 Citas del enunciado/videos
> Modulo Kernel:
> Program Counter: Número de la próxima instrucción a ejecutar.

> Modulo CPU:
> Registro | Tamaño | Tipo de dato | Descripcion
> PC &emsp;&emsp;&nbsp;| 4 bytes &nbsp;| uint32_t  &emsp;&emsp; | ...

### 💭 Soluciones posibles
_suponiendo que son el mismo:_ Podria omitir la existencia el propio registro PC dentro de la estructura registros_t y dejarla por "fuera" dentro de la estructura pcb_t, de igual manera el CPU va a recibir el PCB completo.
```
typedef struct{
(...) 
} registros_t;

typedef struct{
(...)
pc;
registros_t;
}
```

**Comment by iago64** [comment]
Buenas! Cómo va?

Aprovecho que dejaste las preguntas listadas y te las voy contestando una por una:

¿tienen alguna relación directa uno con otro? 
Son el mismo registro

¿es necesario declararlo dos veces (teniendo en cuenta que los propios registros estarán dentro del PCB)?
No, pero es importante que al momento de hacer SET se pueda pisar el valor del PC

¿son el mismo PC?
Si

¿Si no son el mismo o son el mismo pero necesito diferenciarlo de alguna forma, por qué necesitaria hacerlo?
Son el mismo, lo aclaramos 2 veces porque del lado kernel nos importa que nos indica que instrucción es la que sigue, pero despues en la CPU queremos que se pueda cambiar su valor, con alguna de las instrucciones JNZ o SET.

Saludos.-
