### ISSUE TITLE
Kernel - Eliminación Proceso

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3603]
Buenas noches,
Cuando la consigna en la parte de eliminación de procesos de kernel dice "Ante la llegada de un proceso al estado de EXIT (ya sea por solicitud de la CPU, por un error, o por
ejecución desde la consola del Kernel), el Kernel deberá solicitar a la memoria que libere todas las estructuras asociadas al proceso y marque como libre todo el espacio que este ocupaba". Mis dudas son:

1) ¿Cuál sería un ejemplo de un proceso que llega a exit por un error? ¿Qué tipos de errores? Porque errores en los archivos de pseudocodigo entiendo que no pueden haber.

2)Entiendo que ante la solicitud del kernel memoria debe eliminar las estructuras asociadas al proceso, por ejemplo, la estructura en donde hayamos guardado las instrucciones que leimos del archivo de pseudocodigo de ese proceso. Pero no me queda claro lo de marcar como libre el espacio que el proceso ocupaba, ¿como sería eso? Por ahí no es cosa del checkpoint 2 todavía y por eso no me queda del todo claro.

**Comment by iago64** [comment]
Buenas! Cómo va?

Errores que finalicen un proceso son varios, por ejemplo que hagas un WAIT o un SIGNAL de un recurso que no existe, que quieras hacer una IO de una interfaz desconectada o que no admite esa operación, como por ej pedirle un `IO_STDIN_READ` a una interfaz genérica.

La segunda pregunta es normal que estes lleno de dudas porque es problema de mas adelante, cuando tengan tablas de páginas y demas estructuras, por ahora solo les alcanza con romper la relación entre el PID y el archivo de pseudocódigo.

Saludos.-

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Para nada, de hecho es una buena idea que cada petición que le hagan a la memoria este acompañada del PID siempre que se pueda.

2.- En este caso, por como lo plantearon, si, alcanzaría con eliminar ese proceso de la lista global.

Saludos.-

**Comment by rood8592** [comment]
Ok, muchas gracias y saludos!
