### ISSUE TITLE
Duda sobre el uso de hilos y la comunicacion con socket

### ISSUE THREAD

**Issue by MartinVulta** [sisoputnfrba/foro#3605]
Buenas, tengo una duda bastante grande, y es que, si se fijan en el codigo que proporcionó mi hermano en el issue #3563 , basicamente lo que tenemos hecho es, que cada modulo tenga distintos hilos que simplemente atiendan las conexiones bidireccionales con cada modulo conectado, o sea, si se fijan bien lo que hace, estos hilos estan constantemente haciendo recv de algun codigo de operacion para luego, entender como tratarlo.
Hasta ahí todo bien, pero hay algo que no me cierra con el funcionamiento de los socket, si yo tengo un hilo que puede estar todo el tiempo haciendo recv en un socket bidireccional, o sea, una funcion BLOQUEANTE, que pasa si otro hilo del mismo modulo, al mismo tiempo, hace send() para enviar algo a traves de la conexion? El otro modulo que recibe el mensaje y tambien esta en recv dentro de un respectivo hilo, recibe el mensaje correctamente? Porque, la idea de nuestro grupo era tener hilos que simplemente se encarguen de ESCUCHAR esas conexiones, pero no necesariamente implementar la logica con la que utilizan la informacion recibida, simplemente guardan la informacion en variables globales para que otros hilos puedan usar esas variables.

Me temo que si los socket no son capaces de hacer lo que propongo, vamos a tener que descartar esta idea de hilos "escuchantes", y empezar a pensar como coordinar que distintos hilos no choquen en el uso de estos socket, o quizas aún si los sockets no son capaces de realizar esto, hay alguna manera de hacer esta idea de los hilos escuchantes se pueda hacer, para así no descartar todo lo que tenemos. Muchas gracias y buen viernes!!

**Comment by iago64** [comment]
Buenas! Cómo va?

Solo por mera curiosidad, aparte de leer la guía de sockets, ¿viste el video que esta al principio de la misma?
Un poco ahi y lo que se pretende con la realización del TP, es que entiendan como funcionan los sockets, que resumiéndolo rápido es una especie de caño donde vos mandas algo de un extremo al otro del caño y del otro lado tenes a alguien esperando recibir eso que mandaste. Una vez que vos mandaste algo por el caño, el caño queda disponible para que mandes más cosas y estas cosas se van a ir acumulando en un `buffer` del sistema operativo que vos vas a ir leyendo a medida que hagas `recv()`.

Ahora bien, el planteo de tener un hilo que solo escucha y no hace nada mas que dejar las cosas en una variable global, es poco eficiente por decirlo de una forma académica, ya que lo que terminas teniendo es un paso mas de sincro para decirle a otro hilo: _Che tenes algo en la variable, fijate que haces_, por eso capaz que trataría de evolucionar la idea del hilo que "escucha" y veas de sumarle algo de lógica.

Por otro lado no estoy del todo seguro, pero es muy probable que mientras estás haciendo `send()` en un thread no puedas estar haciendo `recv()` en otro ya que ambas operaciones afectan al mismo `File Descriptor` del socket, por lo que replantearía la estrategia y definiría mejor el protocolo de comunicación para que las operaciones tengan un orden.

Saludos.-

P.D: El usar la analogía del caño es porque justamente el error que te da `send()` cuando falla es `broken pipe`

**Comment by nicolasvultaggio** [comment]
buenas, soy yo el hermano, y teníamos la misma duda con tincho, creo que incluso si mantenemos esa estrategia, la de los hilos escuchantes, sería complicarlo innecesariamente, sería más facil poner a escuchar un socket cuando sea necesario y listo

**Comment by iago64** [comment]
Buenas! Cómo va?

Justamente eso de "poner a escuchar" el socket o también conocido como dejarlo colgado en un `recv()` es parte de definir bien el protocolo y si, es mucho mas simple porque se ahorran una buena cantidad de sincro.

Saludos.-
