### ISSUE TITLE
Problema con string_split

### ISSUE THREAD

**Issue by tomipodo** [sisoputnfrba/foro#3606]
Buenas! Estamos recibiendo el motivo de desalojo desde la CPU al Kernel, por lo que desde la CPU enviamos la instrucción completa (por ej: IO_GEN_SLEEP GENERICA 10) y el Kernel debe separar la instrucción de los parámetros.
Esta es nuestra implementación
```c
    log_info(logger, "Motivo: %s", motivo_de_desalojo);
    char** substrings;
    char* instruccion_de_motivo_string;
    if(motivo_de_desalojo[strlen(motivo_de_desalojo) -1] == '\n') motivo_de_desalojo[strlen(motivo_de_desalojo) -1] = '\0';
    if(string_contains(motivo_de_desalojo, " ")){
        substrings = string_split(motivo_de_desalojo, " ");
        instruccion_de_motivo_string = substrings[0]; //En esta línea nos sale un segmentation fault
    } else {
        instruccion_de_motivo_string = motivo_de_desalojo;
    }
    op_code instruccion_de_motivo = string_to_opcode(instruccion_de_motivo_string);
    log_info(logger, "Instruccion: %s", instruccion_de_motivo_string);
```
El if lo hacemos porque cuando llega un EXIT, no hay que hacer el string_split. 
Así están las variables al momento que salta la excepción:
![image](https://github.com/sisoputnfrba/foro/assets/70075163/ec166053-fc13-4f09-a73e-9b65d2bc0cc3)
Gracias, saludos!

**Comment by FredeHG** [comment]
Hola buenas! 

Probaste correrlo con [valgrind](https://docs.utnso.com.ar/guias/herramientas/valgrind#tutorial-de-valgrind-y-helgrind)? Que te dice?

**Comment by fedenimi** [comment]
Hola, qué tal? Soy del mismo grupo que Tomi.  Lo corrimos con valgrind y el problema ese desaparecía y podía hacer perfecto el log de la última línea y todo. Agregamos un log entre el string_split y la línea en la que se rompe y ahí corrió bien también en VSC, por lo que después sacamos el log, y exactamente el mismo código que se rompía, ahora empezó a funcionar bien. Por lo que si bien en este momento parece resuelto, no entendemos por qué y si el problema puede llegar a volver. Saludos

**Comment by FredeHG** [comment]
Tal vez el problema era de compilación de los cambios, realmente sin verlo me es muy complicado saber que les puede estar pasando

**Comment by tomipodo** [comment]
Probablemente haya sido un problema de compilación, de todas maneras hoy a la mañana fuimos al soporte y pasó lo que comentó antes Fede. Muchas gracias!
