### ISSUE TITLE
Duda caso al finalizar un proceso desde consola estando bloqueado

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3607]
Buenas! venimos del soporte con esta duda que nos dijeron que la plasme en un issue para generar consenso sobre la siguiente situcacion.

Imaginemos que tengo una interfaz Int1 de tipo generica conectada y dos proceso p1 y p2 que le pidieron dormir 30 segundos.
Acto seguido el kernel va a pasar a ambos a la cola de bloqueados y la interfaz se pone a trabajar(dormir)
Si mientras esta trabajando se nos ocurre finalizar por consola el proceso 1 lo que va a pasar es que la interfaz sigue durmiendo por primera vez (peticion de proceso 1) y en algun momento le va a mandar un mensaje al kernel diciendo termine!
El tema es que una vez en el kernel lo que hacemos es cuando me llega un mensaje de fin de interfaz es hacer un pop de la cola de bloqueados y entonces ahi haria un pop del proceso 3 cuando no corresponde pues la interfaz aun no atendio al proceso 3

Me adelanto un poco pero lo mismo pasaria con las instancias de los recursos que teoricamente simbolizan la cantidad de procesos bloqueados por ese recurso, pero si de la nada se me ocurre mandar algun proceso a exit deberia como hacerle un ++ a ese recurso sin hacer el signal

### 💭 Soluciones posibles
Lo que se nos ocurrio para solucionar con interfaces es que esta al mandar el mensaje DONE le mande al kernel el pid del proceso y que el kernel pueda chusmear la cola de bloqueados correspondiente para ver si el primero en la cola coincide con el pid, caso contrario no hace el pop.

Pero bueno como el enunciado no aclara mucho sobre este caso, dejo el issue para que nos indiquen como se procede ante este caso

**Comment by iago64** [comment]
Buenas! Cómo va?

Honestamente no habíamos pensado una prueba tan compleja, así que, gracias! Vamos a tenerlo en cuenta jeje....
Fuera de chiste, tranqui, **no vamos a matar por la consola del kernel a ningún proceso que se encuentre bloqueado en una interfaz de IO** sea cual sea el tipo de interfaz.
Lo que seguro que va a pasar es utilizar el finalizar proceso para algún proceso que se encuentren bloqueados por algún recurso de los que se solicitan con la instrucción WAIT.

Saludos.-

**Comment by GonTurri** [comment]
Bueno, confio en tu palabra. Pero el el caso del wait habria que hacerle un ++ o no?

**Comment by iago64** [comment]
Buenas!

Un ++ o un -- según como tengas modelado el valor del recurso y si corresponde liberar los recursos que tenga tomados el proceso que acabas de matar.

Saludos.-
