### ISSUE TITLE
Conexiones entre módulos.

### ISSUE THREAD

**Issue by DanielKesel** [sisoputnfrba/foro#3608]
Buenas tardes ¿cómo están? Tenemos las siguientes dudas:
**¿Cómo bootear el SO?**
Se sabe que primero tiene que bootear Memoria, después CPU, después Kernel y despues I/O, pero cómo llegamos a bootear memoria sin I/O?
En consecuencia a eso, cuando inicia el programa está bien que la memoria se quede esperando al kernel primero y luego a la cpu? una vez que el sistema esté andando, la memoria tiene que ser capáz de recibir peticiones del kernel/cpu/io al mismo tiempo mediante hilos?

Muchas gracias y saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

Tanto el Kernel como la Memoria, tienen que ser capaces una vez iniciados, recibir **en cualquier momento** nuevas conexiones de las interfaces de IO.

Saludos.-

**Comment by FredeHG** [comment]
Hola @DanielKesel 
Quedo resuelta la duda? 

Si es así podemos cerrar el issue?

**Comment by DanielKesel** [comment]
Perdón por la demora en responder!.
Muchas gracias, me quedó claro que una vez iniciados hay que buscar la forma para que en cualquier momento poder recibir nuevas conexiones.
Solo que no me queda claro si está bien que al iniciar la memoria o sea en el momento 0 que se enciende la memoria espere a un modulo en especifico y no avance hasta que se satisfaga esa conexión y luego abre los procedimientos para realizar las multiples conexiones.

**Comment by FredeHG** [comment]
Si, el orden del start up de las aplicación lo definen ustedes, una vez que ven su aplicativo ok, recién en ese momento empiezan las pruebas

**Comment by DanielKesel** [comment]
Genial chicos, doy por cerrado dale?
Muchas gracias!
