### ISSUE TITLE
Pasarle parámetro a un hilo

### ISSUE THREAD

**Issue by jotab0** [sisoputnfrba/foro#3609]
Buenas! Necesito saber si está bien la sintaxis del hilo teniendo en cuenta que necesito pasarle un parámetro creado antes para que ejecute bien.

El objetivo es que cree un hilo para cada conexión nueva por parte de las interfaces I/O
### 🔎 Búsqueda en foros

Por lo que tengo entendido el argumento se pasa en la función ` pthread_create(...)` pero por las dudas me gustaría que lo chequeen para poder implementarlo en el resto de los módulos que lo necesitan
### 📝 Código relevante

**Esto está en mi kernel.c, fd_kernel es global**
`fd_kernel = iniciar_servidor(PUERTO_ESCUCHA, kernel_logger, "!! Servidor ENTRADA-SALIDA iniciado !!");
`
```
void esperar_conexiones_entradasalida(){
	while(1){
        
        int *fd_conexion_entradasalida = malloc(sizeof(int));
        *fd_conexion_entradasalida = esperar_cliente(fd_kernel, kernel_logger, "ENTRADA-SALIDA");

        pthread_t hilo_entradasalida;
        int err = pthread_create(&hilo_entradasalida, NULL,(void*)esperar_entradasalida_kernel, (int*)fd_conexion_entradasalida);
        if (err!=0){
            perror("Fallo de creación de hilo_entradasalida(kernel)\n");
            exit(-3);
        }
        pthread_detach(hilo_entradasalida);

    }
}

void esperar_entradasalida_kernel(int* fd_conexion_entradasalida){
    int estado_while = 1;
	t_list* lista;
    while (estado_while) {
		log_trace(kernel_logger,"KERNEL: ESPERANDO MENSAJES DE E/S...");
        int cod_op = recibir_operacion(*fd_conexion_entradasalida);
		switch (cod_op) {
		case MENSAJE:
		 	recibir_mensaje_tp0(*fd_conexion_entradasalida,kernel_logger);
			break;
		case PAQUETE:
			lista = recibir_paquete(*fd_conexion_entradasalida);
			log_info(kernel_logger,"Me llegaron los siguientes mensajes:\n");
			list_iterate(lista,(void*)iterator);
			break;
		case -1:
			log_error(kernel_logger, "E/S se desconecto. Terminando servidor");
			estado_while = 0;
            break;
		default:
			log_warning(kernel_logger,"Operacion desconocida de E/S");
			break;
		}
	}
}
```

Aguardo su respuesta,

Gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Voy a sonar feo y quizas bastante mala leche, pero si queres validar sintaxis compilá el programa y si tenes dudas de si lo que hiciste anda, ejecutalo, los ayudantes no somos ni compiladores ni debuggers biológicos de C.

Ahora si, si llegaste a esta parte de la respuesta viene la parte amigable, la idea es que no codeen por codear sin compilar cada tanto y mucho menos sin ir probando lo que hacen, ya que a diferencia de lo que pueden ser tps más acotados como un tp de algoritmos, el TP de SisOp es un TP largo, complejo y que requiere que avancen de a poco haciendo funciones chicas y probando que eso que hicieron funciona y no rompe lo anterior, por eso que la respuesta mala onda al final del día termina siendo un poco lo mas eficiente, porque sin ir mas lejos, entre la duda y la respuesta pasaron 3 horas, que si lo compilas y lo ejecutas se reduce a 5 / 10 minutos.

Saludos.-

**Comment by FredeHG** [comment]
Hola @jotab0 
Puediste probarlo como te comento Dami?

**Comment by jotab0** [comment]
Sisi perfecto. Gracias!
