### ISSUE TITLE
Creacion de archivo en DIALFS

### ISSUE THREAD

**Issue by diegohcanetti** [sisoputnfrba/foro#3611]
### 📔 Citas del enunciado/videos
>Al momento de crearse un archivo, va a comenzar ocupando un bloque del FS aunque su tamaño sea 0 y luego el mismo se podrá extender o disminuir por medio de de la función IO_FS_TRUNCATE.

El primer bloque que se ocupa va a ser el bloque_inicial en la metadata del archivo nuevo? Ya que aunque el archivo tenga como tamaño 0, siempre va a empezar ocupando un bloque en el filesystem. Yo por el momento había puesto el bloque inicial como vacío "", pero esto podría llegar a ser erróneo.

**Comment by iago64** [comment]
Buenas! Cómo va?

Exacto, el primer bloque que le reservan es el que tienen que poner como bloque inicial en el archivo de metadata.

Saludos.-

**Comment by diegohcanetti** [comment]
Perfecto, muchas gracias
