### ISSUE TITLE
Memoria como cliente

### ISSUE THREAD

**Issue by lucasvazz16** [sisoputnfrba/foro#3612]
Hola, con mi grupo teníamos dudas acerca de agregar al archivo de configuración del CPU un puerto para que la memoria se conecte como cliente a nuestra CPU, ya que en el enunciado dice que la memoria debería enviarnos las instrucciones y no sabríamos por dónde recibirlas en otro caso. 

### 📔 Citas del enunciado/videos
Memoria de Instrucciones
Esta parte de la memoria será la encargada de obtener de los archivos de pseudo código las instrucciones y de devolverlas a pedido a la CPU.
Al momento de recibir la creación de un proceso, la memoria de instrucciones deberá leer el archivo de pseudocódigo indicado y generar las estructuras que el grupo considere necesarias para poder devolver las instrucciones de a 1 a la CPU según ésta se las solicite por medio del Program Counter.
Ante cada petición se deberá esperar un tiempo determinado a modo de retardo en la obtención de la instrucción, y este tiempo, estará indicado en el archivo de configuración.

### 💭 Soluciones posibles
Talvez se puede usar el puerto de dispatch (entiendo que es exclusivo para el kernel) o hay alguna forma de que la memoria como server pueda mandar cosas a su cliente.

**Comment by iago64** [comment]
Buenas! Cómo va?

Creo que tenemos que ajustar un concepto importante y es la definición de "cliente" y de "servidor".
Un cliente es aquel que se conecta y el servidor es aquel que recibe las conexiones, ahora al momento de que la conexión está establecida, cualquiera de los 2 le puede mandar cosas al otro, independientemente de quien haya llamado a la funcion `connect()` y quien a `accept()`.

Dicho lo anterior, no tiene sentido que se compliquen tanto con el hecho de agregarle un nuevo puerto a la CPU, simplemente pueden conectarse a la memoria, hacer el handshake y dejar a la memoria a la espera de las peticiones de las instrucciones (u operaciones) por parte de la CPU.

Saludos.-

**Comment by lucasvazz16** [comment]
Genial, gracias.
