### ISSUE TITLE
Duda sobre archivo y busqueda de instrucciones

### ISSUE THREAD

**Issue by JoaquinBergara** [sisoputnfrba/foro#3613]
Hola buenas noches! Tenemos una duda sobre la creacion de la estructura global (que en realidad es una lista) y la busqueda de instrucciones en Memoria. Nosotros para probar pusimos que la estructura de instrucciones se cree en el hilo de Memoria-CPU (del lado de memoria), despues de crearla comienza a enviarle las instrucciones a CPU. Pero lo correcto seria que la creacion de la estructura este del lado del hilo de Memoria-Kernel. Nuestra duda es la siguiente: que pasa si accede primero al hilo de memoria-cpu antes de que el hilo de memoria-kernel haya creado la estructura con las instrucciones

    void conexionCPU(void* info_fd)
    {
        info_fd_cpu* fd_recibido = info_fd;
        int fd_cpu = fd_recibido->fd;
        free(fd_recibido);

        int retardo = config_get_int_value(config,"RETARDO_RESPUESTA");
        agregar_proceso_lista(14,"codigoPrueba.txt"); //ESTO DEBERIA IR EN EL HILO MEMORIA-KERNEL

        int codigoOperacion;
        while(1)
        {
            codigoOperacion = recibir_operacion(fd_cpu);

            if(codigoOperacion == -1)
            {
                log_error(logger,"Error al recibirOperacion");
                return;
            }

        switch (codigoOperacion) {
            case INSTRUCCION:
                char* valor_pc = recibir_mensaje(fd_cpu,logger);
                uint32_t pc_recibido = atoi(valor_pc);
                usleep(retardo*1000);
                t_proceso* proceso = list_get(instrucciones_procesos,0);
                enviar_mensaje((proceso->instrucciones)[pc_recibido],fd_cpu,INSTRUCCION);
                free(valor_pc);
                break;
         ...
    }

**Comment by RaniAgus** [comment]
¡Buenas! Ese escenario que planteás no es posible porque la inicialización del proceso ocurre en el estado NEW, y para llegar a EXEC es necesario que dicho proceso esté listo para ejecutar (o sea, READY). Justamente, si la memoria está cargando las estructuras necesarias para ejecutar el proceso, el mismo no va a estar listo aún. Saludos

**Comment by JoaquinBergara** [comment]
Cierto, no nos habiamos dado cuenta, gracias!!
