### ISSUE TITLE
Función list_destroy_and_destroy_elements, qué recibe como segundo parámetro?

### ISSUE THREAD

**Issue by VEBravo** [sisoputnfrba/foro#3614]
La función que se encuentra en las commons en list.h, qué recibe como segundo parámetro además del puntero a la lista?

**Comment by RaniAgus** [comment]
¡Buenas! Recibe una función que es usada para liberar cada elemento. Esto es porque probablemente guardes en ella punteros a structs reservados con `malloc()` y hay muchos casos en los cuales necesitás liberarlos junto con una lista.

¿Por qué no usa `free()` y listo? Porque puede ser que tu struct tenga punteros a otras estructuras también reservadas con `malloc()`, las cuales si no las liberamos también tendremos memory leaks.

Saludos

**Comment by VEBravo** [comment]
Entiendo, y suponiendo esto, si tengo esta función que libera un nodo lista
`void destroy_nodo_instruccion(nodo_instruccion* nodo_instruccion)
{
	free(nodo_instruccion->instruccion);
	free(nodo_instruccion);
}`

`list_destroy_and_destroy_elements(lista_instrucciones, destroy_nodo_instruccion (*acá*) );`

En este caso no tengo un nodo instruccion creado sino que son los nodos que están dentro de lsita_instrucciones, entonces, qué parametro debería pasarle a destroy_nodo_instrucción dentro de list_destroy_and_destroy elements?

**Comment by VEBravo** [comment]
Otro, por ejemplo acá, en la funcion list_find
`void* list_find(t_list *self, bool(*condition)(void*)) {
	t_link_element **indirect = list_get_indirect_by_condition(self, condition);
	return (*indirect) != NULL ? (*indirect)->data : NULL;
}`
De qué manera debería pasarle la condición? Claramente mi problema está en no entender cómo pasarle el parámetro

**Comment by RaniAgus** [comment]
Esas funciones reciben por parámetro un puntero a función: https://docs.utnso.com.ar/guias/programacion/punteros#extra-punteros-a-funciones

No tiene sentido llamar a la función usando `()` porque entonces le estarías pasando el retorno de la función como parámetro, no la función en sí

**Comment by VEBravo** [comment]
Entiendo cómo funciona, pero en el link que me enviaste la función de ejemplo no recibe nada como parámetro:

`int main(int argc, char **argv) {
     char inicial = 'a';
     bool nombreEmpiezaCon(t_alumno *alumno){
              return alumno->nombre[0] == inicial;
     }
     //... inicializar lista ...
     t_alumno *filtrados = filtrarPorCriterio(alumnos, nombreEmpiezaCon);

     return 0;
}`

Le manda directamente nombreEmpiezaCon sin parámetros. Pero la función list_find
`void* list_find(t_list *self, bool(*condition)(void*)) {
	t_link_element **indirect = list_get_indirect_by_condition(self, condition);
	return (*indirect) != NULL ? (*indirect)->data : NULL;
}`
Me pide un bool(*condition)(void*)
Muestro cómo la estoy usando, capaz ayuda
`void eliminar_proceso_lista_procesos(t_list* lista_de_procesos, t_pcb pcb, t_log* logger){
	bool coincide_pcb(nodo_lista_de_procesos* proceso){
			return proceso->PID == pcb.ID;
	}

	void destroy_nodo_instruccion(nodo_instruccion* nodo_instruccion)
	{
		free(nodo_instruccion->instruccion);
		free(nodo_instruccion);
	}

	nodo_lista_de_procesos* proceso_a_eleiminar = list_find(**lista_de_procesos, coincide_pcb**);
	list_destroy_and_destroy_elements(proceso_a_eleiminar->lista, destroy_nodo_instruccion);
}`

Y ahí me está diciendo esto:
passing argument 2 of ‘list_find’ from incompatible pointer type [-Wincompatible-pointer-types]

**Comment by FredeHG** [comment]
Hola buenas!

Ese mensaje que te está dando es un warning, donde C te está preguntando amablemente si sabes lo que estás haciendo pero para entender el mensaje tenemos que pensar lo siguiente:

   La firma de `filtrarPorCriterio` si está pidiendo parámetro, incluso la firma es prácticamente igual a la que te pide `list_find`
```C
t_alumno *filtrarPorCriterio(t_alumno *listaAlumnos, bool (*criterio)(t_alumno*))
```

Pero cual es la diferencia entre 
`bool (*criterio)(t_alumno*)` y `bool(*condition)(void*)`?

y mas importante comparar las diferencias entre lo que pide y lo que se le pasa en ambos casos:
`bool nombreEmpiezaCon(t_alumno *alumno)` y `bool coincide_pcb(nodo_lista_de_procesos* proceso)` 

Donde pide que el parámetro de la función sea `t_alumno*`  se le pasa una función que recibe `t_alumno*` pero donde pide que sea `void*` se le pasa una función que recibe `nodo_lista_de_procesos*`

Eso a C le suena raro, te lo va a dejar hacer pero te lo avisa como warning para que sepas que algo raro hay

Hay una forma de indicarle a C que sabes lo que haces, y en este caso tenes 2 opciones para sacar el warning

1. Castear la función que vas a pasar como parámetro a `(bool (*)(void*))` o recibir `void*` en tu función y luego castear ese `void*` a `nodo_lista_de_procesos*`

Espero que está explicación concisa + la guía de punteros que compartió Agus te sirva para entender un poco mejor el mundo de los punteros de C

Saludos!

**Comment by VEBravo** [comment]
Hola! Muchas gracias, terminé casteando el void* a nodo_lista_de_procesos. Eso me terminó solucionando todo, muchas gracias. No deja de ser algo extraño pasar punteros a funciones y castear datos de tipo void*, más cuando es la primera vez que lo hago jajajajaj, pero la explicación y el link ayudaron mucho! :D Saludos a ambos.
Tiro como extra que estaría bueno hacer una función que devuelva el index de un elemento mediante una condición, estuve viendo las commons y lo más similar es la función list_find, que cumple con la condición pero no encontré manera de que devuelva el index sin modificarla (cosa que no hice)

**Comment by iago64** [comment]
Buenas!

Gracias por la recomendación, lo anotamos para verlo una vez finalizado el cuatri ya que no hacemos cambios en las commons en medio de los cuatrimestres para evitar cualquier tipo de inconveniente con los TPs.

Respecto a la duda, quedo resuela?

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Me sumo solo para preguntar: ¿para qué querrías obtener un índice dada una condición? ¿Es para hacer una operación sobre la lista inmediatamente después? Porque tenemos varios casos ya cubiertos:

- Reemplazar el primero que cumpla la condición: `list_replace_by_condition`
- Quitar el primero que cumpla la condición: `list_remove_by_condition` y `list_remove_and_destroy_by_condition`
- Quitar todos los que cumplan una condición: `list_remove_and_destroy_all_by_condition`

Si es para implementar la función `eliminar_proceso_lista_procesos` que pasaste antes, quizás lo mejor sea usar directamente `list_remove_and_destroy_by_condition`.

Saludos

**Comment by VEBravo** [comment]
Claro, pasa que como tenía una lista de listas el `list_remove_and_destroy_by_condition` tenía que eliminar también la lista que estaba dentro con todos los elementos. Entonces terminé usando list_find o una de esas para obtener el puntero al nodo y usar el list_destroy_and_destroy_elements.
En resumen, quedó solucionado.
Muchas gracias chicos, una vez más.

**Comment by FredeHG** [comment]
Excelente, si queda solucionado cerremos el issue!
