### ISSUE TITLE
CPU-INTERRUPT

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3615]
Buenas noches, tenemos una duda con respecto a la recepción de interrupciones del lado del CPU. Nosotros en el tp hicimos un hilo para interrupt en cpu que tiene un recv bloqueante que se queda ahi esperando una interrupcion del kernel. La duda que tenemos es como pedirle básicamente al hilo la información de si le llego algo de kernel o no (check interrupt), para ver si seguir ejecutando o devolver contexto, y que luego el hilo no se caiga también, que siga con el recv bloqueante. Estamos muy perdidos en como pedirle información al hilo basicamente.
Y otra duda con respecto a las interrupciones, cuando nos llega una, ¿el motivo de desalojo seria "INTERRUPCION"? ¿No hay tipo de interrupciones o si?

**Comment by RaniAgus** [comment]
¡Buenas!

Quizás consultar si hubo interrupciones no sea algo que se pide de un hilo al otro, sino más bien algo que un hilo le deja al otro en un lugar común para que lo lea cuando haga falta. Según lo visto en la teoría, ¿se te ocurre dónde podría ser ese lugar común?

Por otro lado, los motivos por los cuales un proceso es interrumpido los pueden encontrar en el enunciado del módulo Kernel.

Saludos

**Comment by rood8592** [comment]
Gracias, se nos ocurrió crear una variable de hay_interrupción (int), que el hilo interrupt cambiar su valor si le llega a 1 algo sino se queda en 0, y en el hilo main se llama a la función checkInterrupt que chequea el valor de esa variable. Tenemos varias dudas:
1) ¿Habría que aplicar conceptos de sincronización ya? Porque el hilo main esta leyendo y el hilo interrupt esta escribiendo sobre esa variable. ¿Podría llegar a pasar que le llegue una interrupción justo cuando hace check interrupt y que no llegue a leerlo bien o algo asi?
2)¿Qué sucede si nos llega una interrupción mientras estamos ejecutando la ultima instruccion exit o algo de una interfaz, que implique desalojar el proceso mas allá de la interrupción, el motivo de desalojo sería lo correspondiente a la instruccion (ej. motivoDesalojo: exit)? Porque no habría checkInterrupt en ese caso porque el programa ya terminó. Al menos asi lo planteamos hasta ahora, si hay una instruccion que implique desalojar el proceso, nuestro programa no hace el checkInterrupt.
3) Otra duda con respecto al motivo de desaolojo es: en el caso de los desalojos por wait, signal, io_gen_sleep sabemos que deben ser informados a kernel desde cpu. Pero los que son de interrupción (ej. Fin Quantum) los conoce ya kernel de antemano, por eso manda la interrupción. ¿En ese caso cpu no sería el que comunica el motivo de desalojo, no? Sino que kernel ya lo sabe.

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- No esta de mas un mutex para estar 100% tranquilos de que no va a pasar de que el hilo main esta leyendo en medio de la actualización del hilo de interrupt.

2.- Nada, si les llega una interrupción en EXIT o una instrucción que desaloja la CPU ahi nomas en el check interrupt tienen que marcar como "vista" la interrupción aunque lo desalojaron antes por la instrucción en si misma.

3.- Depende muchísimo de como implementaron el Kernel, ya que pueden tener un Kernel que manda la interrupción y se olvida y cuando le llega el PCB desde la CPU necesaita saber por que lo desalojaron o pueden hacer que el Kernel sepa de antemano que mando una interrupción pero en el caso que el kernel sabe y recuerda que mando la interrupción, que pasa si justo la instrucción que desalojó el PCB era un IO_GEN_SLEEP? 

Saludos.-

**Comment by rood8592** [comment]
¿En el punto 3 te referis a qué pasa si el kernel sabe de antemano porque mandó la interrupcion pero antes de que llegue la cpu a chequearla esta  necesita ser desalojado por otra instruccion, el de una interfaz por ejemplo? Entonces el motivo de desalojl cambia y ya no es por la interrupción.

**Comment by RaniAgus** [comment]
¡Buenas @rood8592! ¿Se entendió a lo que apunta Dami? Saludos

**Comment by rood8592** [comment]
Sisi, perfecto. Cierro el issue.
