### ISSUE TITLE
Proceso

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#3616]
Hola una pregunta, esta parte de la consigna es en el modulo memoria. Queria preguntar si hay algunos datos o alguna estructura que tengamos que tener como referencia, porque estoy un poco perdido en que datos tendria que contener. El pcb nosotros lo creamos en Kernel y lo enviamos a cpu, pensabamos hacer lo mismo en memoria pero no sabemos si estaria bien. Gracias de antemano

### 📔 Citas del enunciado/videos
![image](https://github.com/sisoputnfrba/foro/assets/112731246/afe12797-04d4-4809-a1ca-964093c34cd3)

**Comment by iago64** [comment]
Buenas! Cómo va?

En principio las estructuras administrativas que pueden hacer en memoria, a menos que sean recursantes, es solo la que asocia un PID con el archivo de pseudocódigo al cual le van a ir pidiendo las instrucciones desde la CPU.

Saludos.-
