### ISSUE TITLE
Round Robin con temporal de las commons usa espera activa

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3617]
Buenas! para implementar el round robin se nos ocurrio usar el temporal de las commons mas o menos de la siguiente manera

```c
    timer = temporal_create();
    do
    {
        if (DONE_BEFORE_QUANTUM)
        {
            temporal_stop(timer);
            time_elapsed = temporal_gettime(timer);
            temporal_destroy(temporal);
            break;
        }
    } while (temporal_gettime(timer) < pcb->quantum);
   if(!DONE_BEFORE_QUANTUM) send_interrupt();
      temporal_destroy(timer);
```

Tendriamos este loop en un hilo con un semaforo activado por el planificador cuando arranca un proceso a ejecutar, el tema es que cuando le ponemos quantum muy largo se queda mucho tiempo maquinando y se traba toda la compu
Me gustaria saber si esta espera activa es aceptable, o si es un pecado, y ademas tambien saber cuales son tiempos razonables de quantum y retardo de memoria

Desde ya muchas gracias

**Comment by RaniAgus** [comment]
¡Buenas! Lo que hace ese bucle es lo que se conoce como **espera activa** y, tal y como mencionás, la compu se traba porque la CPU deja constantemente al proceso Kernel en EXEC impidiendo la ejecución del resto de procesos del sistema y haciendo un total desperdicio de recursos.

Es por esto que, como habrán visto o verán en la teoría, existen mecanismos para bloquear el hilo de ejecución y desbloquearlo ante un determinado evento. En este caso, como el evento es solo el paso del tiempo, quizás lo mejor sea usar un `sleep()`.

Por otro lado, `t_temporal` les puede servir más que nada si el algoritmo requiere alguna métrica sobre el tiempo que estuvo el proceso en EXEC (o algún otro estado). Justo este TP no los tiene, así que no creo que sea el caso.

En definitiva, sí, es motivo de desaprobación del TP tener esperas activas... después si es pecado o no depende de la religión de cada uno (?

Saludos

**Comment by iago64** [comment]
Buenas! cómo va?

La premisa número 1 de los hilos es que creamos un hilo cuando **_mi proceso se tiene que bloquear esperando algo y tengo que seguir haciendo otras cosas_**
Ese algo puede ser un mensaje desde un socket como por ejemplo el hilo de interrupt de la CPU o el hilo que se crea para manejar las IO.
Ahora bien, si uds tienen que por ej esperar que pase un tiempo y a la par tienen que hacer otras cosas, ahí es donde pueden por ejemplo crearse otro hilo que pueden llamar `hilo_quantum` y esperar a que pase el tiempo para mandar la señal de interrupt a la CPU.

Saludos.-

**Comment by GonTurri** [comment]
Justamente tenemos ese hilo quantum pero me parece que hace falta crear uno cada vez que un proceso que llega a exec porque no puedo reiniciar el hilo una vez que ya replanifique. Sería hacer un hilo que haga el sleep, se fije si corresponde interrumpir y termine. 
Si no hacemos esto inevitablemente con el sleep se va calcular mal el quantum del proceso que entró después en el caso de que no haya finalizado por fin de quantum

**Comment by iago64** [comment]
Buenas! Cómo va?

Ya que hablamos de religiones... en el código podemos jugar a ser un ser superior y todo aquello que creamos, lo podemos destruir... [`pthread_cancel()`](https://man7.org/linux/man-pages/man3/pthread_cancel.3.html) es el poder que te esta faltando.

Saludos.-

**Comment by GonTurri** [comment]
jajaja perfecto, justo en el soporte habiamos planteado algo asi pero nos llevaron por otro lado, muchisimas gracias por la tolerancia
