### ISSUE TITLE
Con que valor debería inicializar los bloques ocupados por los archivos nuevos?

### ISSUE THREAD

**Issue by diegohcanetti** [sisoputnfrba/foro#3618]
### 📔 Citas del enunciado/videos
>Creación de archivos
Al momento de crearse un archivo, va a comenzar ocupando un bloque del FS aunque su tamaño sea 0 y luego el mismo se podrá extender o disminuir por medio de de la función IO_FS_TRUNCATE.

Para probar la inicializacion lo estamos haciendo con 'a'. Sin embargo queriamos saber si la idea es que sea con '\0'
![imagen](https://github.com/sisoputnfrba/foro/assets/102698705/0f5fdb03-e65f-4aeb-9778-72eb84717391)

Otra pregunta, en el enunciado además se menciona que aunque el tamaño del archivo nuevo sea 0, siempre ocupa un bloque. Sin embargo, si el tamaño de un bloque es por ejemplo 64 bytes, no debería de comenzar siempre ocupando 64 bytes?

**Comment by FredeHG** [comment]
Hola buenas! 

El tamaño de un archivo esta definido por la cantidad de datos que tiene escritos, por lo que no necesariamente va a ser múltiplo del tamaño de bloque, lo que si se pide es que al momento de crear un archivo se ocupe un bloque con el consiguiente cambio en el bitmap para marcar el bloque como ocupado y la creación del archivo metadata indicando el numero de bloque

Sobre la inicialización del archivo de bloques lo normal es hacerlo con `\0`, que como pueden ver en la imagen que comparten no es más que el valor 00. Pero nada te limita es usar cualquier carácter como `centinela`

Saludos!

**Comment by diegohcanetti** [comment]
Me quedo clarísimo, muchas gracias
