### ISSUE TITLE
Cantidad Caracteres 

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#3619]
Hola buenas tardes. Queria preguntar cuantos caracteres puede tener como maximo un archivo de instrucciones. Y tambien queria preguntar si las unicas instrucciones que pueden mandar son las que aparecen en la consigna en la parte de execute del modulo CPU. Saludos

**Comment by FredeHG** [comment]
Hola buenas!

No entiendo a que te réferis cuantos caracteres puede tener como máximo un archivo de instrucciones. Puede tener muchas instrucciones no tendrías limite, en cuanto a la longitud de cada instrucción, puede tener cualquier longitud, pero no vamos a testear un 

`IO_FS_WRITE Int4 archivo_con_nombre_super_largo_buscando_romper_el_buffer_de_los_alumnos_de_2024_1er_cuatrimestre_de_la_carrera_ingenieria_en_sistemas_de_la_informacion_cursando_sistemas_operativos.txt AX ECX EDX`

Por otro lado si usan punteros `char*` para guardar las instrucciones van a poder tener prácticamente toda la longitud humanamente posible

Si, solo van a tener las instrucciones que están en la consigna.

Saludos!
