### ISSUE TITLE
Duda sobre como se compactan los bloques

### ISSUE THREAD

**Issue by ParedesMicaela** [sisoputnfrba/foro#3620]
### 📔 Citas del enunciado/videos
Compactación
Puede darse la situación que al momento de querer ampliar un archivo, dispongamos del espacio disponible pero el mismo no se encuentre contiguo, por lo que vamos a tener que compactar nuestro FS para agrupar los bloques de los archivos de manera tal que quede todo el espacio libre contiguo para el archivo que se desea truncar. 

Hola buenas! Tenia unas consultas con respecto a la compactación. A modo de ejemplo para que se entienda más hice este dibujo:
<img width="304" alt="Captura de pantalla 2024-04-28 160033" src="https://github.com/sisoputnfrba/foro/assets/83614884/ea69c4f0-1a1b-423c-a333-c883ed127f12">

1. Cuando yo compacto, compacto todo el fs o compacto solamente los bloques libres que necesito para ampliar el archivo? Por ejemplo si el archivo3 necesita ampliarse 2 bloques esos 2 bloques libres los compacto asi y luego se los doy al archivo?
<img width="303" alt="Captura de pantalla 2024-04-28 160132" src="https://github.com/sisoputnfrba/foro/assets/83614884/7c2bb528-978b-4d64-b2f5-89994619f9f0">

O deberia compactar todos los bloques libres al comienzo y mover el archivo que pidio la compactacion?
<img width="305" alt="Captura de pantalla 2024-04-28 160744" src="https://github.com/sisoputnfrba/foro/assets/83614884/7b7ccc54-2461-4c99-b18d-c5b4a0169ca9">

2. Si el archivo1 necesita 2 bloques se asignan los bloques 1 y 2 por estar contiguos al archivo1 o los bloques tienen que estar contiguos luego del ULTIMO bloque del archivo1?

En cualquier caso entiendo que tendria que mover todos los bloques cuando compacto. Agradecería si me ayudan con alguna de estas dudas para entender un poco más cómo sería la compactacion, gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

La compactación no la definimos ya que no hay una única forma correcta de hacerla y es algo que nos van a tener que decir al momento de las evaluaciones para saber como es que lo resolvieron.

La forma que estas planteando de compactar todo y parar de mover bloques al momento de llegar al archivo que se tiene que compactar me parece de lo mas simple de implementar y que puede estar muy bueno, pero nuevamente sostengo, si otro grupo lo hace de otra forma y resuelve el problema, va a ser igual de válido y de última sera pregunta de coloquio que nos expliquen los motivos de por que lo pensaron en resolver asi.

Saludos.-

**Comment by ParedesMicaela** [comment]
AAA buenísimo entonces lo implemento así que es mas fácil, gracias!!
