### ISSUE TITLE
Consulta sobre la parte de Kernel en el enunciado

### ISSUE THREAD

**Issue by benitezcamila** [sisoputnfrba/foro#3622]
Hola! con nuestro grupo tenemos algunas dudas sobre el enunciado. Sobre la parte de kernel en la que dice 

>"Una vez seleccionado el siguiente proceso a ejecutar, se lo transicionará al estado EXEC y se enviará su Contexto de Ejecución al CPU a través del puerto de dispatch, quedando a la espera de recibir dicho contexto actualizado después de la ejecución, junto con un motivo de desalojo por el cual fue desplazado a manejar."
1) Cuando menciona que se selecciona el siguiente proceso a ejecutar se refiere al primero de la cola de ready o deberíamos poder pasar un proceso en particular por parámetro? 
2) Cuando dice que se debe devolver el contexto post-ejecución incluído el motivo del desalojo, el motivo puede ser que el proceso finalizó? o únicamente habría que desalojarlo por fin de quantum o bloqueos? 
3) Esto es más sobre el código en sí, debería romper si le hacemos un stop a un t_temporal que ya había sido detenido antes?

**Comment by LeandroCarbajales** [comment]
Buenas!
Te respondo por punto:
1- El siguiente proceso a ejecutar es el que dicta el algoritmo, en el caso de FIFO y RR es el primero de la cola ready como bien marcás, en el caso de VRR sería el primero de la cola ready prioritaria.
2- El contexto de ejecución puede ser devuelto por varios motivos, los cuales están definidos en el módulo CPU, entre ellos, exit (finalizó), desalojo por fin de quantum, un pedido al kernel, un error, etc.

3- Te repregunto, en qué contexto están usando t_temporal para que quieran detenerlo 2 veces?

**Comment by lucasvazz16** [comment]
Hola, soy del grupo de Camila. El tema del "t_temporal" usado dos veces lo barajamos como idea que surgió para tener dos formas de detener el contador. Una sería mediante un "sleep" en milisegundos con el valor del quantum, y la otra sería porque el CPU lo desalojó debido a que se bloqueó u otra razón. Entonces, en el caso de la segunda opción, se detendría por esa razón y cuando termine el sleep se detendría por segunda vez. Consultamos para saber si era posible pero la verdad hasta el momento no lo implementamos.

**Comment by LeandroCarbajales** [comment]
Sigue sin quedarme claro para qué usarían ese contador t_temporal en el caso del quantum.
Una vez que el sleep() termina ya saben que pasó el tiempo del quantum, igualmente pueden realizar algún chequeo extra (por ej, que el proceso que iban a desalojar sigue en ejecución) antes de enviar el mensaje de interrupt.
Si prefieren ir por el lado de "cortar el timer", cuando un proceso deja la CPU voluntariamente y por lo tanto ya saben que no quieren enviar el interrupt, pueden cancelar el hilo que estaba haciendo el sleep con `pthread_cancel()`.

**Comment by benitezcamila** [comment]
Si, tiene más sentido, nos quedó más claro. Gracias!
