### ISSUE TITLE
Interfaz grafica

### ISSUE THREAD

**Issue by beluromeo** [sisoputnfrba/foro#3623]
### 💭 Soluciones posibles

Hola buenas noches, disculpen la molestia pero me encuentro con mi equipo realizando todo para el segundo checkpoint. Al dividirnos las tareas me quedo designada el desarrollo de la interfaz grafica. Sinceramente no entiendo que es lo que tengo que hacer, necesito por favor ayuda, pasos a seguir, que es lo que tengo que hacer porque ni lo comprendo. Por favor ayuda

**Comment by beluromeo** [comment]
Nuevamente disculpen las molestias, gracias a todos que termien bien el finde

**Comment by LeandroCarbajales** [comment]
Buenas noches!
Entiendo que quisiste escribir "interfaz **genérica**", refiriéndote al tipo de interfaz de I/O pedida para el checkpoint 2 😄 

En primer lugar, algo que me llamó la atención y me sirve como recomendación para el grupo es:
> "Al dividirnos las tareas me quedo designada el desarrollo de la interfaz grafica. Sinceramente no entiendo que es lo que tengo que hacer..."

Una buena práctica de trabajo en equipo (no solo en la facultad, sino en la vida profesional también) es, al dividirse tareas, tener una puesta en común para asegurarse que todos tienen una idea de por dónde empezar y poder justamente trabajar en paralelo.

Suponiendo que es una duda de todo el equipo paso a responder.
Siguiendo las pautas del enunciado, las interfaces de I/O de este trabajo tienen todas una misma implementación de base que es:
 1 - Me conecto al Kernel
 2 - Espero que me mande un mensaje (operación a realizar)
 3 - Atiendo el mensaje (realizo la operación)
 4 - Le respondo que terminé.
 5 - Vuelvo al paso 2
En el caso de la interfaz genérica, la "operación" a realizar no es más que esperar una cantidad de tiempo dada por el archivo de configuración.

Les sirve la respuesta?
Saludos!
     Lean

**Comment by beluromeo** [comment]
Hola Leandro muchisimas gracias por tu respuesta, por ayudarnos.
Graciassss

**Comment by karengrams** [comment]
¡Buenas @beluromeo!

Debido que la duda fue resuelta, cierro el issue. Cualquier otra consulta, no dudes en abrir otro issue, o nos vemos en un sábado de soporte.

¡Saludos!

Kar.
