### ISSUE TITLE
Separación de contenido en varias paginas

### ISSUE THREAD

**Issue by santi-p98g** [sisoputnfrba/foro#3624]
Buenas! espero que ande todo bien.

Quería hacer 2 consultas, ya que arrancamos a testear cosas de memoria y van surgiendo dudas.

1) Con respecto a las instrucciones de lectura de memoria como 'IO_STDOUT_WRITE', en el caso de querer leer un tamaño mayor al del tamaño de pagina/marco, con referencia a lo que hablamos para la escritura acá: [https://github.com/sisoputnfrba/foro/issues/3566](url) ? 
Si la DL comienza en la PAG4 que está en MARCOX, debo seguir leyendo la PAG5-MARCOY, y así sucesivamente respetando el orden de las paginas y los marcos en donde ellas se encuentran? 
Ó hay que leer cierta cantidad de bytes del void* contiguamente?
Supongo que obviamente hay que hacer el manejo como la primera opción, ya que si no accedería un proceso al espacio de otros, pero pregunto por las dudas ya que quizás es lo que se quiere hacer con esa instrucción.

2) Al separar strings, hicimos fácil porque directamente se toma el contenido que se quiere tomar del char* para una pagina y se lo guarda en el marco.
Pero qué pasa en el caso de que un entero no entre en un marco/página? Siendo las paginas por ejemplo de 2B ó escribiendo desde el ultimo desplazamiento de un marco?
Ya que contemplamos ese caso y no sabemos como hacer para 'dividir' un entero, si hay que operar bit a bit, o si me estoy yendo a casos muy específicos que no van a aparecer en las pruebas del TP.

Muchas gracias como siempre! Saludos y buen comienzo de semana :)

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- La opcioń correcta es la primera que planteas, tienen que ir pegando el contenido entre las páginas del proceso, independientemente de como esten repartidas en los marcos.

2.- Los enteros es algo relativamente facil, porque los enteros de 1 byte (`uint8_t`), es decir, los registros AX, BX, CX y DX nunca van a tener que separarlos ya que ocupan 1 byte, ahora los de 4 bytes como EAX, EBX, etc lo que pueden hacer es algo tan simple como "olvidarse" que son un `uint32_t` y por ejemplo tener una variable un `uint32_t *` apuntando al registro que despues la castean a un `void *` y despues es hacer los `memcpy()` de toda la vida de acuerdo a los bytes que correspondan poner en cada página.

Saludos.-
