### ISSUE TITLE
Error al iniciar la VM

### ISSUE THREAD

**Issue by lperezpersico** [sisoputnfrba/foro#3625]
holaa, escribo porque recién al intentar abrir la VM se me queda ahí esperando que yo escriba algún comando. Es raro porque vengo trabajando hace un mes y nunca tuve problema, y no cambié la configuración de nada.
![Captura de pantalla 2024-04-29 110641](https://github.com/sisoputnfrba/foro/assets/164270711/53c8eefb-5572-4d07-95f5-b7311d7c4439)

**Comment by karengrams** [comment]
¡Buenas @lperezpersico!

¿Cómo va? Espero que bien. Pareciera que se corrompieron un par de archivos de la VM, y se ve que eran los del file-system.

> En criollo, se ve que algunos archivos 💥 , y por eso no se puede iniciar la VM.

Recomendaria que corras el siguiente comando (que eventualmente es el que te dice que corras):
```bash
> fsck /dev/mapper/ubuntu--vg--ubuntu--lv
```

P.D.: si queres entender un poco el trasfondo del porqué puede ser que haya pasado esto, te dejo el siguiente [link](https://www.linuxquestions.org/questions/linux-newbie-8/problems-with-root-file-system-4175663569/) para que chusmees.

¡Quedo atenta al progreso! Y obviamente, si no funciona también.

Kar.

**Comment by lperezpersico** [comment]
ahí pude! mil gracias

**Comment by karengrams** [comment]
Aló (yo otra vez).

¡Buenisimo @lperezpersico! Cierro el issue.

¡Nos vemos!

Kar.
