### ISSUE TITLE
Duda sobre cómo se muestran los procesos al pausar la planificación

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3626]
Buenas, al pausar la planificación entiendo que el enunciado dice que se deben frenar todas las transiciones salvo el proceso que se está ejecutando. Pero cuando este termina y yo le doy a mostrar proceso por estado. Les gustaría que ese proceso no aparezca en ningún estado o aparezca como que sigue ejecutando cuando en verdad ya desalojó? 
Así ya vamos acomodando bien el pop de la cola de exec

Desde ya muchas gracias

**Comment by RaniAgus** [comment]
¡Buenas! Como se frenan las transiciones de estado estimo que lo más adecuado sería seguirlo mostrando en EXEC. Incluso, si justo fue desalojado por una syscall, técnicamente aún está en EXEC pero ejecutando en modo Kernel, solo que para el TP representamos los cambios de modo devolviendo el PCB al módulo que lo representa y son instantáneos. Saludos
