### ISSUE TITLE
Cpu y Memoria

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#3627]
Hola buenas tardes. Tengo dos preguntas: 
1) En mi tp cuando se pasa el path por consola en iniciar_proceso, memoria lo recibe y lee todo el archivo una sola vez y guarda todas las instrucciones en una lista que despues mete dentro de una estructura proceso que tiene tambien el pid y el path. Eso estaria bien? o habria que abrir el archivo recien cuando cpu pide una instruccion?

2) Tambien tengo una duda con la conexion entre cpu y memoria, yo lo pense asi: Cpu tiene una funcion que se llama pedir_instruccion donde le pasamos el pid y el program counter a memoria para que nos busque primero en la lista general de proceso por el pid y despues dentro de ese proceso, con el PC busque la instruccion en la lista que tiene cada proceso y devuelva esa instruccion a cpu. Y asi cpu tendria que ir pidiendo una instruccion a la vez, esto cumpliria con la consigna y estaria bien? Saludos y Gracias de antemano

**Comment by RaniAgus** [comment]
¡Buenas!

1. Sí, de hecho es el approach más correcto. Sería como cargar en memoria el segmento de código del proceso, solo que en este caso se lo simplificamos dejándolo en una estructura de datos separada del espacio contiguo de usuario.
2. Sí, está buenísimo si pueden abstraer la comunicación por sockets a un simple llamado a una función que por debajo se encargue de toda la lógica de serialización y deserialización de los mensajes. También es correcto ir pidiendo una instrucción por vez, ya que en teoría la CPU tiene un almacenamiento muy limitado que solo permite cargarle una instrucción en la etapa de fetch. En otras palabras, sería incorrecto desde la teoría cargar toda la lista de instrucciones en CPU.

Saludos

**Comment by JoaquinCoaricona** [comment]
Gracias. Tengo un problema al devolver la instruccion (lo de la pregunta 2), voy armar otro issue.
