### ISSUE TITLE
Creacion de Procesos

### ISSUE THREAD

**Issue by BrunoBarlari** [sisoputnfrba/foro#3629]
## Creacion de procesos
Tengo una duda sobre los procesos, en la consigna dice que el Kernel se encarga de la creacion y eliminacion de procesos. 

*"Creación de Procesos
Ante la solicitud de la consola de crear un nuevo proceso el Kernel deberá informarle a la memoria que debe crear un proceso cuyas operaciones corresponderán al archivo de pseudocódigo pasado por parámetro, todos los procesos iniciarán sin espacio reservado en memoria, por lo que solamente tendrán una tabla de páginas vacía."*

Pero en un issue lei que es una **simulacion** de un proceso, no un proceso en si **fork()**. A que se refiere con esto? como creo un proceso sin crearlo? y que modulo deberia "crearlo"?

**Comment by RaniAgus** [comment]
¡Buenas! Se crean de la misma forma que en un TP de Algoritmos/PdeP/etc, en los cuales de acuerdo al enunciado podrías tener una estructura que represente a una persona:
```c
#include <string.h>

typedef struct {
  char *nombre;
  int edad;
} t_persona;

t_persona *persona_create(char *nombre, int edad) {
  t_persona *persona = malloc(sizeof(t_persona));
  persona->nombre = strdup(nombre);
  persona->edad = edad;
  return persona;
}

void persona_destroy(t_persona *persona) {
  free(persona->nombre);
  free(persona);
}
```

Y al llamar a `persona_create` no necesitarías crear una persona real, ni tampoco al llamar `persona_destroy` la estarías destruyendo 😄

En este caso, crear un proceso es inicializar una estructura que contenga todos los datos necesarios para representarlo (la cual, desde la teoría llamamos Process Control Block, o por su sigla PCB) y, si te gusta ser prolijo, podés ir armando operaciones asociadas para manipular dicha estructura como `create`, `destroy`; para luego usarlas a lo largo del ciclo de vida de un proceso (que, una vez listo para ejecutar, es seleccionado para ejecutarlas de acuerdo al algoritmo de planificación configurado hasta finalizar).

También no te olvides de la parte de informar al módulo Memoria para que éste cargue el archivo con el listado de instrucciones.

¿Queda clara la idea?

Saludos

**Comment by LeandroCarbajales** [comment]
Buenas @BrunoBarlari !
Te sirvió la respuesta de @RaniAgus ? Te resuelve la duda?

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, ante cualquier consulta pueden reabrirlo o abrir uno nuevo. Saludos
