### ISSUE TITLE
list_get y puntero a estructuras y strtok()

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#3630]
Hola buenas. Estoy teniendo este problema al devolver un puntero a una estructura. List_get me devuelve un puntero a una estructura que guardo en instruccionPC, el puntero llega bien. Cuando abro instruccionPC que es el puntero que la recibe, los campos de int llegan bien, son los de length, pero los de char llegan con "" en opcode deberia llegar un string. Y cuando los quiero imprimir no sale nada. Que tendria que hacer para que se puedan imprimir? adjunto lo que me sale en el debug. 

```
	instruccionPC = list_get(procesoBuscado->lista_de_instrucciones,pc);
	
	printf(" \n %s \n",instruccionPC->opcode); 

```
Lo de Debug
![image](https://github.com/sisoputnfrba/foro/assets/112731246/73196234-826b-40d2-ae9d-c4d160f9945f)

Asi se ve antes de guardarlo en la lista:
![image](https://github.com/sisoputnfrba/foro/assets/112731246/ba7e35ec-00a7-4267-8527-e25875d5e57a)
 
Una vez dentro de la lista ya no puedo ver el contenido pero la direccion esta bien creo:
![image](https://github.com/sisoputnfrba/foro/assets/112731246/6d92dce3-ad78-4084-9787-8edb966ced58)

**Comment by RaniAgus** [comment]
¡Buenas! El problema seguramente no está en list_get ya que, por lo que veo ahí, se está devolviendo un puntero a la misma dirección de memoria que se leyó (`0x7ffff0001f30`).

También veo que el puntero hacia el `opcode` sigue siendo el mismo (`0x7ffff0000de0`), pero lo único que cambió es el contenido al que apunta dicho puntero. Esto solo puede deberse a que lo estén modificando desde otro lado o haciendo un `free()` en donde quizás no debían.

Entonces, de ahí me surge la pregunta: ¿cómo están inicializando el struct instrucción? ¿De dónde sale el puntero que le asignan a la estructura?

Saludos

**Comment by JoaquinCoaricona** [comment]
![image](https://github.com/sisoputnfrba/foro/assets/112731246/e15bc4c4-8581-453b-8e91-ab9dc37f380e)
este es el codigo completo

**Comment by RaniAgus** [comment]
Me refería al momento en el que guardan el puntero a la lista, no cuando lo recuperan. De todas formas, un detalle: creo que la operación que querían hacer es `list_find()` la cual les devuelve el primer elemento que cumpla con la condición. Ojo con `list_filter()` ya que éste crea una nueva lista con los elementos filtrados, por lo que necesitarían liberarla con `list_destroy()` para evitar memory leaks.

Por otro lado, porfa no suban capturas de pantalla por todas las razones que contamos en el [readme del repositorio](https://github.com/sisoputnfrba/foro/blob/master/README.md).

**Comment by JoaquinCoaricona** [comment]
```
t_instrucciones *instruccionREC = malloc(sizeof(t_instrucciones));
instruccionREC->lista_de_instrucciones = list_create();
list_add((instruccionREC->lista_de_instrucciones),ptr_inst);

```

estas son lineas de codigo que estan separadas por un while,la segunda de la tercera, en el while se carga ptr_inst y depues lo guardamos en la lista que esta dentro de instruccionREC. Entre la linea 1 y la 2 se cargan los otros campos de instruccionREC

**Comment by RaniAgus** [comment]
Nono, la lista está bien 😅, me refería a lo que guardan en ella, o sea `ptr_inst` en su caso.

Repito, ¿cómo están inicializando el struct instrucción? ¿De dónde sale el puntero que le asignan a la estructura?

**Comment by JoaquinCoaricona** [comment]
![image](https://github.com/sisoputnfrba/foro/assets/112731246/6da34aea-72b3-45ef-8789-ff3e7838f8a9)

Es todo este codigo dentro de un while, pero asi lo carga y lo agrega. Arriba esta la foto que puse en la primera respuesta de como antes de hacer el list_add aparece bien cargado ptr_inst
```
t_instruccion_unitaria *ptr_inst = malloc(sizeof(t_instruccion_unitaria));

        char *token = strtok(cadena," ");
        ptr_inst->opcode = token;
        ptr_inst->opcode_lenght = strlen(ptr_inst->opcode) + 1;
        
        ptr_inst->parametros[2] = NULL;
        ptr_inst->parametros[0] = NULL;
        ptr_inst->parametros[1] = NULL;

		token = strtok(NULL, " ");
		int n = 0;
		while(token != NULL)
		{
			ptr_inst->parametros[n] = token;
			token = strtok(NULL, " ");
			n++;
		}

		if(ptr_inst->parametros[0] != NULL){
			ptr_inst->parametro1_lenght = strlen(ptr_inst->parametros[0])+1;
		} else {
			ptr_inst->parametro1_lenght = 0;
		}
		if(ptr_inst->parametros[1] != NULL){
			ptr_inst->parametro2_lenght = strlen(ptr_inst->parametros[1])+1;
		} else {
			ptr_inst->parametro2_lenght = 0;
		}
		if(ptr_inst->parametros[2] != NULL){
			ptr_inst->parametro3_lenght = strlen(ptr_inst->parametros[2])+1;
		} else {
			ptr_inst->parametro3_lenght = 0;
		}

		list_add((instruccionREC->lista_de_instrucciones),ptr_inst);
		free(cadena);
```

**Comment by RaniAgus** [comment]
¡Ahí está! [`strtok()`](https://www.man7.org/linux/man-pages/man3/strtok.3.html) es una función medio rara que lo que hace es pisar el delimitador (o sea, el espacio) con un caracter `'\0'` y retornar el puntero al siguiente token: https://systems-encyclopedia.cs.illinois.edu/articles/c-strtok/

O sea que todos los punteros que va devolviendo pertenecen a la `cadena` que están liberando al final, con lo cual nada les garantiza que esa memoria no se termine pisando más adelante por otras funciones que reservan memoria con `malloc()`.

En general no recomendamos usar esa función ya que tiene bastantes [problemas de diseño](https://stackoverflow.com/a/44336960). En su lugar preferimos que usen el `string_split()` de las commons ya que devuelve directamente nuevos punteros sin modificar la cadena que recibe.

Sin embargo, en este caso para no romper con lo que ya tienen implementado, creo que lo más sencillo va a ser hacer una copia de cada string devuelto por `strtok()` usando `strdup()`:

```c
char *token = strdup(strtok(cadena," "));

//...

token = strdup(strtok(NULL, " "));
```

De esta forma, los punteros devueltos van a seguir existiendo aún luego de haber liberado la `cadena`.

Saludos

**Comment by JoaquinCoaricona** [comment]
Ahi me funciono, muchas gracias. Esto me dio 3 preguntas:
-Entonces si no estaria dentro de un while la solucion hubiera sido no liberar candena no? 
-Al estar en un bucle, ese espacio cadena que se liberaba al final de cada ciclo y se reservaba al inicio podria haber sido el mismo y pisado en cada ciclo no?
-Esos string split los tengo que liberar igualmente no? 
De nuevo muchas gracias, me sirvio. Sabia que strtok ponia los barra cero pero no me hubiera dado cuenta que se podria estar pisando la misma zona

**Comment by RaniAgus** [comment]
¡Buenas! Me sumo solo para responder esta pregunta:

> Entonces si no estaria dentro de un while la solucion hubiera sido no liberar candena no?

Es buena la pregunta, en realidad no tiene nada que ver el hecho de estar en un `while` o no, de hecho otra solución podría haber sido quitar el `free(cadena)` y no usar `strdup()`.

El tema ahí es que al momento de liberar la estructura deberías evitar liberar los `ptr_inst->parametros[n]`, ya que éstos son solo desplazamientos de la `cadena` que ahora quedarían guardados en `ptr_inst->opcode`.

De hecho, si se fijan con el debugger probablemente vean que `cadena` y `ptr_inst->opcode` apuntan a la misma dirección de memoria.

Saludos
