### ISSUE TITLE
Interrupciones

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#3632]
Hola buenas. Queria preguntar si las interrupciones de cpu tienen que funcionar para el checkpoint 2? 
Desde ya muchas gracias

**Comment by tomasmartinez02** [comment]
Buenas! Cito a los objetivos de el checkpoint 2 en kernel:

> Es capaz de crear un PCB y planificarlo por FIFO y RR.

Si debe ser capaz de crear un PCB y planificarlo por RR, necesariamente debe funcionar la interrupción por fin de quantum.
Saludos!
