### ISSUE TITLE
Mantener hilo main vivo

### ISSUE THREAD

**Issue by papiness77** [sisoputnfrba/foro#3633]
Buenas, esta bien mantener el hilo  main vivo haciendo un while infinito al final del mismo o es algo que se puede hacer de otra forma?

**Comment by RaniAgus** [comment]
¡Buenas! Esto está **muy** mal ya que tienen un hilo consumiendo ciclos de CPU sin hacer nada, lo cual incrementa el uso de CPU al 100%. Y citando lo que mencionamos en la [charla de threads y sincro](https://docs.utnso.com.ar/guias/linux/threads) (que les recomiendo chusmear):

> "CPU al 100%" es igual a "nos vemos el cuatrimestre que viene"

¿Qué pueden hacer? Bueno, lo más sencillo sería que, teniendo una función que nunca termina de ejecutar (por ejemplo, en Kernel, el hilo que atienda conexiones de IO):

```c
void esperar_conexiones_io() {
  int socket_escucha = iniciar_servidor(...);

  while (true) {
     // El hilo se bloquea hasta que se conecte un cliente, no hay espera activa
     int conexion_io = accept(socket_escucha, NULL, NULL);

     // ... atender la conexión
  }
}
```

En lugar de crear un hilo para usarla y tener que de alguna forma trabar el hilo main para que no termine:
```c
int main() {
   // ... otras cosas

   pthread_t thread_esperar_conexiones_io;
   pthread_create(&thread_esperar_conexiones_io, NULL, esperar_conexiones_io, NULL);
   pthread_detach(thread_esperar_conexiones_io);

   while(true); // ESPERA ACTIVA!!!

   return 0;
}
```

Lo que pueden hacer es simplemente llamar la función, por lo que su hilo main nunca va a terminar:

```c
int main() {
   // ... otras cosas

   esperar_conexiones_io();

   return 0;
}
```


Saludos

**Comment by papiness77** [comment]
Perfecto, quedo claro gracias
