### ISSUE TITLE
Uso de commons/temporal ahora para Virtual Round Robim

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3634]
Buenas! vengo por la revancha del issue #3617 que nos dijeron que no habia que usar el temporal en ningun lado pero creo que aca puede ser de utilidad. 
Para retomar un poco, asi nos quedo el round robin luego de sus correcciones

```c
void esperar_a_cpu_round_robin(pcb){
    pthread_create(hilo_quantum);
    pthread_detach(hilo_quantum);
    esperar_a_que_cpu_desaloje(pcb);
    pthread_cancel(hilo_quantum);
}

void hilo_quantum(pcb){
  sleep(pcb->quantum);
  send_interrupt();
}
```

Tanto si desaloja por fin de quanutm como por otro motivo lo maneja en la funcion esperar_a_que_cpu_desaloje;
Dato de color tambien probamos mover el pthread cancel dentro de esa funcion para rebajar la latencia pero no se si es muy importante.

Con el codigo anterior entonces propongo para el virtual round robin:

```c
temporal timer;
int ms_transcurridos;

//globales del archivo

void esperar_a_cpu_vritual_round_robin(pcb){
    timer = temporal_create();
    esperar_a_cpu_round_robin(pcb);
    temporal_stop(timer);
    ms_transcurridos = temporal_gettime(timer);
    temporal_destroy(timer);
}

// en alguna otra parte, mismo archivo

void mover_a_bloqueados_vrr(pcb){
  if(ms_transcurridos < pcb->quantum){
       pcb->quantum -= ms_transcurridos;
       // mandar pcb a ready+
        return;
   }
  //mandar a ready comun
}
```

si bien tampoco busque mucho, no vi ningun otro tp anterior que haya que hacer virtual round robin entonces probe logear algunos valores de ms_transcurridos para que vean. Pruebas hechas con quantum de 5000 y retardo de memoria de 700

```
Los que salieron por fin de quantum:

[DEBUG] 13:46:13:360 Kernel/(2821:2825): ms pasados: 5636
[DEBUG] 13:46:19:003 Kernel/(2821:2825): ms pasados: 5641
[DEBUG] 13:46:35:922 Kernel/(2821:2825): ms pasados: 5631

Los que se bloquearon por interfaz o recurso:

[DEBUG] 13:45:37:859 Kernel/(2821:2825): ms pasados: 3234
[DEBUG] 13:45:28:975 Kernel/(2821:2825): ms pasados: 4027


Los que terminaron por EXIT:
[DEBUG] 13:45:53:997 Kernel/(2821:2825): ms pasados: 4851
[DEBUG] 13:46:07:720 Kernel/(2821:2825): ms pasados: 2424
[DEBUG] 13:46:48:852 Kernel/(2821:2825): ms pasados: 812
```

Como dije antes del phtread_cancel tambien probamos frenando el timer justo despues del recv y hay una diferencia de aprox 400 milisegundos, pero no se si es tan grave porque con el retado de memoria como mucho ejecutarian una instruccion menos, y por como esta hecho el ciclo de instruccion como minimo se ejecuta una instruccion (aunque le llegue quantum de 1).

Que opinan de esta solucion?  Desde ya muchas gracias

**Comment by RaniAgus** [comment]
¡Buenas! Me corrijo sobre lo que dije en el issue:

> Por otro lado, t_temporal les puede servir más que nada si el algoritmo requiere alguna métrica sobre el tiempo que estuvo el proceso en EXEC (o algún otro estado). ~~Justo este TP no los tiene, así que no creo que sea el caso.~~

Sí, para VRR puede ser muy útil usar `t_temporal` para poder calcular la métrica de cuánto tiempo estuvo el proceso en EXEC. Mala mía, lo había comentado pensando solo en FIFO y RR 😅 

Saludos

**Comment by GonTurri** [comment]
Entonces esto estaría bien a pesar del error de milisegundos o hay que ajustar algo más ?

**Comment by RaniAgus** [comment]
Tranqui, no se preocupen por eso, las pruebas van a estar diseñadas para que sean determinísticas contemplando que puede haber un error en milisegundos. Saludos
