### ISSUE TITLE
Error al enviar el Path a Memoria

### ISSUE THREAD

**Issue by elin-winter** [sisoputnfrba/foro#3636]
Holaa, con mi grupo ya llegamos al punto de demencia porque el path que le enviamos a memoria llega como un "/0001" y no importa que hagamos, no cambia. Intentamos rehacer la función que lo envía, que lo recibe, todo de nuevo 5 veces, además de probarlo todo con debug otras 45 y no encontramos el error. 

Les copiamos el código y humildemente pedimos ayuda, la necesitamos. 

### 📝 Código relevante

Struct de proceso_memoria:

```
typedef struct {
   uint32_t PID;
   char* path;
} proceso_memoria;
```

De parte del Kernel (enviamos estructura_proceso a memoria, la función sigue pero no es relevante al issue):

```
void iniciar_proceso(t_log* logger, char* path, int conexion_memoria, int conexion_cpu, t_list* cola_new, t_list* cola_ready) {
		
        t_paquete* proceso = crear_paquete(CREAR_PROCESO);
        t_pcb* PCB = nuevo_PCB();
        proceso_memoria* estructura_proceso = malloc(sizeof(proceso_memoria));
        
        //list_add(cola_new, PCB);

		estructura_proceso->PID = PCB->PID;
        estructura_proceso->path = path;
		
        agregar_a_paquete(proceso, estructura_proceso, sizeof(proceso_memoria));
        enviar_paquete(proceso, conexion_memoria);
        
        //agregar_a_paquete(proceso, &PID, sizeof(uint32_t));
		//agregar_a_paquete(proceso, path, strlen(path) + 1);
        
        //planificar_FIFO(logger, cola_new, PCB, conexion_memoria, conexion_cpu);
        
		eliminar_paquete(proceso);
```

De parte de Memoria (recibe el paquete enviado, la función sigue pero no es relevante al issue):

```
case CREAR_PROCESO:

                estructura_proceso = malloc(sizeof(t_contenido_instruccion));

                log_info(logger, "Recibí un proceso de %s... \n", mem_serv_name);
                // Recibir el paquete del cliente
                t_list* valores = recibir_proceso_memoria(kernel_socket);
```

Función recibir_proceso_memoria (definida en shared):

```
t_list* recibir_proceso_memoria(int socket_cliente) {
    int size = 0;
    t_list* valores = list_create();
    uint32_t* PID = malloc (sizeof(uint32_t));
	int offset = 0;
    void* buffer = recibir_buffer(&size, socket_cliente);

    // Deserializar el PID
    memcpy(PID, buffer, sizeof(uint32_t));
    list_add(valores, PID);    // Deserializar el path
   int path_size = size - sizeof(uint32_t);
	
    // Crear un buffer para los datos y copiar los datos desde el buffer recibido
    char* path = malloc(path_size + 1); // +1 para el carácter nulo al final
    memcpy(path, buffer + sizeof(uint32_t), path_size);
    path[path_size - 1] = '\0'; // Asegurarse de que la cadena esté terminada en nulo
	list_add(valores, path);
    free(buffer);

    return valores;
}
```

### 🐛 Cómo reproducir el error

Paso captura de pantalla de como se ve el debug:

Aquí como lo enviamos a memoria, el path dice claramente "archivito.txt" (como fue ingresado por consola)

![image](https://github.com/sisoputnfrba/foro/assets/164521483/55ab62ff-1c42-4fab-b3b2-6ce279f9f922)

Acá la función recibir_proceso_memoria (previo a la asignación del path, solo con asignación de PID, que ya ocurre erróneamente porque debería ser 1 y no 16, no sabemos por qué ocurre eso tampoco pero seguro están conectados)

![image](https://github.com/sisoputnfrba/foro/assets/164521483/5f484b0e-4a51-47f2-9266-3698fe06a12e)

Por último, la función recibir_proceso_memoria cuando asigna el valor al path:

![image](https://github.com/sisoputnfrba/foro/assets/164521483/b79c36c9-43dd-458c-a779-5859dd84dbbd)

Cualquier ayuda es más que agradecida, no damos más jaja

**Comment by RaniAgus** [comment]
¡Buenas! Les recomiendo pegarle una leída a la [guía de serialización](https://docs.utnso.com.ar/guias/linux/serializacion) haciendo foco en la parte de estructuras dinámicas. Saludos

**Comment by RaniAgus** [comment]
¡Buenas @elin-winter! ¿Pudieron leer la guía? Se las mencioné porque en ella se explica cómo resolver varios problemas que vi, por ejemplo el hecho de que están enviando un struct que contiene **punteros** (y, posiblemente, **padding**), por lo que creo que es mucho mejor para ustedes leer una guía que ya contiene todos los conceptos explicados detalladamente, antes que cualquier resumen que yo les pueda intentar redactar al respecto en una respuesta a un issue.

También porfa si van a reutilizar funciones del TP0 tengan en cuenta lo que hacen ya que `agregar_a_paquete()` podría no necesariamente estar haciendo lo que quieren hacer para este caso en particular.

Saludos

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, ante cualquier consulta pueden reabrirlo o abrir uno nuevo. Saludos
