### ISSUE TITLE
Lo que pasa con las colas de estados cuando se detiene le proceso.

### ISSUE THREAD

**Issue by MartinVulta** [sisoputnfrba/foro#3637]
Hola buenas tardes, tengo una duda.
En el enunciado, en la pág. 12 que habla de la función DETENER_PLANIFICACION, especifica que se pausa las planificaciones en CP y LP, por lo que no se mandan mas procesos de READY a EXEC y tampoco se agregan nuevos a NEW y READY; además dice que los procesos en BLOC no se agregan a READY. Mi pregunta es, que se hace con los procesos que ya estaban en NEW y en READY, los "borramos" o los dejamos en las colas.
Desde ya muchas gracias.

**Comment by LeandroCarbajales** [comment]
Buenas!
Los procesos quedan en las colas en que están, no se borran, justamente la idea es poder en un momento dado revisar el estado del sistema deteniendo la planificación y luego poder imprimir "procesos_estado" en ese momento "congelado".

Te resuelve la duda?
Saludos!
      Lean

**Comment by MartinVulta** [comment]
Si muchas gracias
