### ISSUE TITLE
Instrucciones Cpu

### ISSUE THREAD

**Issue by tomassagrada** [sisoputnfrba/foro#3640]
Buenas para ejecutar las instrucciones en CPU había pensado utilizar un switch para dividir en casos de instrucción, pero para la parte de ejecutar la instrucción en registros específicos tendría que hacer un caso para cada posibilidad de cada instrucción con cada registro en cada orden? o hay algún detalle del pcb o memoria que me facilite los registros (para no tener que hacer este lio) 

💭 Soluciones posibles
Utilizar un switch para cada caso de instrucción y dentro de esas casos, utilizar IFs para los distintos casos de registros.

**Comment by iago64** [comment]
Buenas! Cómo va?

Un switch es una solución que puede funcionar, pero vos lo que estas buscando es asociar una `clave` con un `valor`, por las dudas, en las commons, casualmente hay una estructura que te puede ayudar a resolver tu problema, te recomiendo que la revises antes de complicarte tanto generando código spaguetti.

Saludos.-

**Comment by tomassagrada** [comment]
Perfecto Gracias

**Comment by tomassagrada** [comment]
Perfecto, Gracias.

**Comment by tomassagrada** [comment]
Buenas la estructura de la que hablas es el "typedef enum": para hacer que la clave obtenga un valor que yo pueda usar en el switch?. Aunque eso solo daría la posibilidad de usar el switch no se si solucionaría el problema del código spaguetti, seguramente entonces me este confundiendo.

**Comment by iago64** [comment]
Buenas! Cómo va?

Me refería a el [dictionary](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/collections/dictionary.h), de todas formas, si queres usar `switch` o muchos `if` anidados podes hacerlo, el problema va a ser seguir ese código a futuro.

Saludos.-

**Comment by tomassagrada** [comment]
Perdón que vuelva a preguntar, ultima cosa, hay alguna parte que contenga (alguno de los documentos con información o algún video) información sobre esto de los diccionario o me conviene buscar en internet para informarme. (se que en los commons habla de un poco como utilizar algunas funciones, pero me refiero para tratar de entenderla mejor para saber como manejarlo).

**Comment by RaniAgus** [comment]
¡Buenas! Los [unit tests](https://github.com/sisoputnfrba/so-commons-library/blob/master/tests/unit-tests/test_dictionary.c) son un buen lugar por dónde empezar. Saludos

**Comment by tomassagrada** [comment]
Mil gracias, un saludo.
