### ISSUE TITLE
Recorrido del proceso por Kernel, Memoria y CPU

### ISSUE THREAD

**Issue by tiagoclur** [sisoputnfrba/foro#3641]
Hola ¿qué tal? Revisando los puntos a llegar en el segundo checkpoint, nos surgieron dudas con el esquema que teníamos entendido en cuanto a la creación de un proceso y su recorrido a lo largo de los módulos. Lo que nosotros pensamos es que:

- Primero la consola interactiva le envía la orden a Kernel de crear un nuevo proceso.
- Kernel envía a memoria la dirección del archivo de pseudocódigo que contiene las instrucciones del proceso que se pidió crear.
- A su vez Kernel manda el PCB a CPU. 
- CPU envía el Program Counter a memoria para que la misma le retorne la instrucción a ejecutar (según el valor del mismo) y luego el proceso continua.

¿Es correcta la forma de encarar el sistema?

**Comment by iago64** [comment]
Buenas! Cómo va?

En principio si, es una forma correcta.
Lo que si tienen que tener en cuenta es que al momento de enviar el PCB a la CPU, la misma no tiene que estar ejecutando ningún otro proceso.

Saludos.-

**Comment by tiagoclur** [comment]
Buenísimo.
Una última duda, el tema del archivo de pseudocódigo, ¿Tiene que existir de antemano o lo genera el Kernel? ¿Lo tenemos que escribir nosotros? ¿Hay procesos prexistentes?

**Comment by iago64** [comment]
Buenas!

El archivo de pseudocódigo va a existir de antes, se los vamos a dar en un repositorio.

Saludos.-
