### ISSUE TITLE
Descarga de la grafica.vdi

### ISSUE THREAD

**Issue by LucasFis** [sisoputnfrba/foro#3642]
Hola, que tal? tengo este problema de que cuando descargo la grafica se corrompe la descarga y no puedo instalar la maquina virtual xubuntu. No se que sea que lo evite pero estuve un rato descargando cosas y no podia hacerlo funcionar

**Comment by MiltonMartorello** [comment]
Holis. No se termina de descargar? o se descarga y al extraer el zip el archivo aparece corrupto?
Tal vez como alternativa tu grupo te lo pueda facilitar?
Otra alternativa es que tu grupo exporte su máquina virtual y te la suba a algun lado
Te tiro varias alternativas para que vayas atacando distintos frentes.

**Comment by LucasFis** [comment]
sii le dije a un amigo que me pase en un pendrive y fue no se que onda, gracias pa
