### ISSUE TITLE
Tamaño del archivo bloques.dat

### ISSUE THREAD

**Issue by ElielBejar** [sisoputnfrba/foro#3643]
Hola que tal! Tengo dudas respecto a la creación del file system: El archivo de bloques.dat y el de bitmap.dat tienen que estar creados previamente antes de ejecutar los diferentes módulos. Entendí bien? y la otra duda es que, cuando me piden que el archivo bloques.dat tenga el tamaño determinado por BLOCK_SIZE * BLOCK_COUNT, no encuentro una forma para hacer eso. Puedo crear el archivo pero no se donde puedo encontrar alguna función o alguna implementación para determinar el tamaño del archivo.

### 📔 Citas del enunciado/videos

El primero va a ser nuestro archivo de bloques (bloques.dat) el cual va a ser un archivo de tamaño definido mediante 2 parámetros del archivo de configuración: BLOCK_SIZE y BLOCK_COUNT, y el tamaño del archivo va a ser BLOCK_SIZE * BLOCK_COUNT.

**Comment by f-and** [comment]
Buenas, hay varias formas de definir el tamaño de un archivo, la mas basica de todas seria [ftruncate](https://pubs.opengroup.org/onlinepubs/007908799/xsh/ftruncate.html), o el System Call [truncate](https://man7.org/linux/man-pages/man2/truncate.2.html).

**Comment by ElielBejar** [comment]
Dale perfecto, gracias!

**Comment by RaniAgus** [comment]
¡Buenas @ElielBejar! Paso a patrullar para avisar (para la próxima) que si la duda ya fue resuelta pueden cerrar el issue 👮🏻‍♂️

Si en un futuro ven que algo no terminó de cuadrar pueden tomarse la libertad de reabrirlo o abrir uno nuevo referenciando éste. 

¡Saludos!
