### ISSUE TITLE
FIFO - Simultaneidad de eventos

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3644]
Buenas, tenía una duda con respecto al algoritmo FIFO. Del la teoría sabemos que ante la simultaneidad de eventos FIFO le da prioridad a uno que este viniendo de BLOCKED, luego uno de NEW y finalmente el proceso más chico. En este TP,¿Podría ocurrir algo así en el que se tenga que decidir quien ejecuta primero? Más que nada porque como todo se ejecuta de manera concurrente siempre va haber uno que haya llegado primero y va estar al principio en la cola de ready.

**Comment by LeandroCarbajales** [comment]
Buenas!
Como bien mencionás, eso no ocurre en el TP ya que sabés exactamente en qué orden llegaron los procesos a ready.

La única razón que ocurre eso en los ejercicios es porque se trabaja con tiempos muy poco granulares, FIFO en sí como algoritmo no le da prioridad a nada, sino que ponemos una puesta en común basándonos en la teoría de en qué orden llegarían a la cola dado que el ejercicio no nos da suficiente información.
Tendrías el mismo problema que en los ejercicios solamente si tuvieras, por ejemplo, un sistema con una lista desordenada y tiempos de llegada redondeados a segundos, probablemente te queden varios elementos en esa lista con el mismo segundo de tiempo de llegada entonces buscarías algún criterio para determinar cuál llegó primero.

Te aclara la duda?
Saludos!
     Lean

**Comment by rood8592** [comment]
Si perfecto, muchas gracias.
