### ISSUE TITLE
Procesos

### ISSUE THREAD

**Issue by MaCejas** [sisoputnfrba/foro#3645]
Buenas tardes, tenemos bastantes dudas sobre el formato que deberían tener los procesos, no terminamos de entender que debería contener el archivo del proceso y como tiene que interpretarlo la memoria. Gracias

**Comment by FredeHG** [comment]
Hola buenas!

Se refieren al path que le [envia kernel](https://docs.google.com/document/d/1-AqFTroovEMcA1BfC2rriB5jsLE6SUa4mbcAox1rPec/edit#heading=h.cetbpcw9maei) a memoria al momento de crear un proceso?

En la parte del enunciado que dice [ejemplo de instrucciones a interpretar](https://docs.google.com/document/d/1-AqFTroovEMcA1BfC2rriB5jsLE6SUa4mbcAox1rPec/edit#heading=h.i8zdk7fpdqzg) está lo que va a contener el archivo que tiene que leer memoria

La idea es que memoria lea ese archivo asocie de alguna forma PID con ese archivo y este listo a que CPU le solicite las instrucciones de a una en la etapa de [fetch](https://docs.google.com/document/d/1-AqFTroovEMcA1BfC2rriB5jsLE6SUa4mbcAox1rPec/edit#heading=h.q2snlo6kh4e9)

Saludos!

**Comment by OreNoe** [comment]
Buenas! Una consulta, el mismo el archivo que el Kernel le pasa a la memoria es el mismo que deberia estar en el archivo de configuracion de la memoria?
Ahora que lo pienso, seguro son dos cosas diferentes pero no termino de entender para que seria el campo "PATH_INSTRUCCIONES" dentro de la configuracion de la memoria.

Muchas gracias y buen finde!

**Comment by FredeHG** [comment]
El `PATH_INSTRUCCIONES` de memoria es la carpeta en la que van a estar las instrucciones

Entonces kernel les puede mandar algo tal que así:
CREAR_PROCESO prueba-base/proceso_1

Y ustedes buscaria prueba-base/proceso_1 concatenando PATH_INSTRUCCIONES y ese string

usando el ejemplo para PATH_INSTRUCCIONES del archivo de configuración les quedaria algo asi

`/home/utnso/scripts-pruebas/prueba-base/proceso_1`

Saludos!

**Comment by FredeHG** [comment]
Hola, si ya esta resuelta la duda, podemos cerrar el issue?

**Comment by MaCejas** [comment]
si, muchas gracias
