### ISSUE TITLE
Formato Instrucciones

### ISSUE THREAD

**Issue by tomassagrada** [sisoputnfrba/foro#3647]
Buenas, estaba tratando de implementar los diccionarios para encarar la parte del pasaje de instrucciones de memoria a CPU, pero me surgió la duda sobre que tipo de dato serian esas instrucciones o si son por ahí estructuras. Porque la memoria consigue la instrucción del archivo de pseudocodigo (que por lo que leí viene pre armado) pero no se que tipo de datos contiene ese archivo o que tipo de archivo es en si el que contiene las instrucciones. 

### 💭 Soluciones posibles
Puede ser que sean una clave las instrucciones o que sean direcciones.

**Comment by FredeHG** [comment]
Hola buenas!

En [esta sección del enunciado](https://docs.google.com/document/d/1-AqFTroovEMcA1BfC2rriB5jsLE6SUa4mbcAox1rPec/edit#heading=h.i8zdk7fpdqzg) está tu respuesta

Saludos!

**Comment by tomassagrada** [comment]
Creo que entendí gracias. Un saludo
