### ISSUE TITLE
Dudas relacion Kernel-Cpu 

### ISSUE THREAD

**Issue by Elias318** [sisoputnfrba/foro#3648]
Tenemos dudas con como seria la relación Kernel-cpu. Si CPU es el que hace la planificación que le manda Kernel o si Kernel hace la planificación ( Como se la comunica a CPU en tiempo de ejecución?). 
No entendemos como usa "interrupt" y "dispatch" el modulo Kernel para comunicarse con CPU.
Gracias.

**Comment by FredeHG** [comment]
Hola buenas!

Primero `<!-- -->` lo que escribas entre estos símbolos no se va a ver para los que leemos el issue salvo que, como hice yo, editemos tu issue y lo saquemos

Ahora con la consulta, el CPU es el que ejecuta las instrucciones de un proceso y el Kernel es el que se encarga de planificar que procesos tienen que ir a CPU y también de manejar las peticiones a entrada salida

En ese rol de gestor el Kernel debe mediante el hilo `dispatch`, enviar cual es el PCB que debe ejecutar el CPU, el CPU empieza a ejecutar las instrucciones (ver [ciclo de instrucción enunciado](https://docs.google.com/document/d/1-AqFTroovEMcA1BfC2rriB5jsLE6SUa4mbcAox1rPec/edit#heading=h.tsl81dts8f7)), el socket `interrupt `se utiliza para que el kernel le pueda decir al CPU que desaloje al proceso que esta ejecutando actualmente

A su vez un programa que se esta ejecutando por el CPU puede requerir un manejo de [interfaz ](https://docs.google.com/document/d/1-AqFTroovEMcA1BfC2rriB5jsLE6SUa4mbcAox1rPec/edit#heading=h.k0s8gmrdihuh)o de [recursos](https://docs.google.com/document/d/1-AqFTroovEMcA1BfC2rriB5jsLE6SUa4mbcAox1rPec/edit#heading=h.o4dclr11f6x2)

Espero que esto más o menos les sirva para orientarse en la interacción kernel-cpu

Saludos

**Comment by RaniAgus** [comment]
¡Buenas @Elias318! ¿Te sirvió la respuesta de Fede? Saludos

**Comment by Elias318** [comment]
Hola que tal, sisi me sirvió. Disculpen que me olvide de cerrar el issue
