### ISSUE TITLE
Pantallazo azul en la Etapa 4!

### ISSUE THREAD

**Issue by VinixHub** [sisoputnfrba/foro#3649]
**Buenos días/tardes/noches a todo aquel que haya llegado a mi Issue.**
 Como dice el título, me salta el pantallazo azul durante la etapa 4 y por consecuente un reinicio de la PC.
 Siendo más específico, me encuentro en la parte donde debo hacer el 'Despliegue del repositorio': al momento de repetir los pasos, durante la ejecución del ítem 2 (_clonar su propio fork del TP0_), una vez hecha la SSH key verifico que esté todo configurado correctamente con el comando "ssh -T git@github.com", pero al momento de darle 'enter' (y_a sea en la terminal de la VM server, VM con interfaz gráfica o inclusive sin la VM_) se me traba por un instante y salta el pantallazo azul! 
 Les dejo imagen del pantallazo azul en cuestión (_es el mismo que me aparece si ejecuto el comando tanto en mi Windows como en ambas VMs_): 

![pantallazo-azul](https://github.com/sisoputnfrba/foro/assets/67282200/4b1c8e0b-59e8-4c5c-94bc-193c7fa424f9)

**Comment by iago64** [comment]
Buenas! Cómo va?

Revisando rapido en internet, encontramos que esto parece ser un problema reciente de las últimas build: https://forums.virtualbox.org/viewtopic.php?t=111418

Esto al ser un problema que no teníamos mapeado no nos queda mucho mas que probar las alternativas que recomiendan en el post que es cambiar el adaptador de red de Bridged Network (Adaptador puente si lo tenes en español), de hecho lo dicen en l a misma página de Virtual Box: 

![image](https://github.com/sisoputnfrba/foro/assets/1622109/bc4ff896-ecc7-4b50-b448-c21741cbecbd)

Lo que podes intentar es bajar la version 7.0.14 de la página de las [Old Builds de Virtual Box](https://www.virtualbox.org/wiki/Download_Old_Builds_7_0)

Por favor proba con alguna de las opciones y comentanos.

Saludos.-

**Comment by VinixHub** [comment]
Hola Damian! sos un genio man. **Cambie la versión de la Build nada más** y fue más que suficiente. Muchas gracias por el soporte!

**Comment by RaniAgus** [comment]
¡Buenísimo! Dejo un pin en el issue por si lo llegamos a encontrar en un futuro cercano
