### ISSUE TITLE
Duda sobre registros del cpu

### ISSUE THREAD

**Issue by iah-herrera** [sisoputnfrba/foro#3651]
Buenas noches, nos surgió la duda de si son necesarios los registros del tipo flag que utiliza el cpu para marcar el carry , overflow, etc. 
No lo vimos en el enunciado y queríamos saber si podía llegar a pasar que una resta de negativo o que una suma exceda el tamaño máximo del registro entre otros.

**Comment by iago64** [comment]
Buenas! Cómo va?

En el TP fuimos por una versión mas simplificada y no vamos a tener ni carry ni overflow y para eso les dejamos los registros detallados en el [enunciado](https://docs.google.com/document/d/1-AqFTroovEMcA1BfC2rriB5jsLE6SUa4mbcAox1rPec/edit#heading=h.g8wwscbuoevu).

Saludos.-

**Comment by iah-herrera** [comment]
Perfecto, muchas gracias!

Cierro issue
