### ISSUE TITLE
sobre virtual round robin

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3653]
Buenas! en la teoria vimos que el virtual debe beneficiar a los proceso IO bound, pero al menos por como lo tenemos hecho ahora, tambien beneficiaria a los procesos que se bloquean por recursos. 
Esto es correcto o solo se deben beneficiar a los procesos que utilizaron E/S?

Otra cosita mas que va por el mismo tema, cuando usamos VRR y el proceso desaloja por signal o wait y luego retoma ejecucion, el quantum lo podemos reiniciar o debemos reinsertarlo en la cpu con menos quantum?
(Por como lo tenemos ahora, se reinsertaria con el ultimo quantum con el que llego. Puede ser menor o igual al del config)

Desde ya muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

Una pregunta, ¿Cómo implementaste el VRR? 
Porque en el TP sería bastante simple separar los procesos que se bloquearon por `IO_*` de las que son por `WAIT` ya que la cola de prioridad de VRR solo aplica a aquellos procesos que estuvieron en una I/O y que además van a contar con un Quantum disponible de `Q'` que es el resultado de la resta del Quantum `Q` y el `tiempo que estuvo en exec`.

Saludos.-

**Comment by GonTurri** [comment]
todo esto arranca de que usamos la misma estructura de cola de bloqueados para las interfaces y los recursos porque nos parecio mas comodo, la cual es esta

```c
typedef struct
{
    char *resource_name;
    union
    {
        int fd;
        int instances;
    };
    sem_t sem_process_count;
    t_sync_queue *block_queue;
} t_blocked_queue;
```

y la logica de reducir el quantum la haciamos cuando pasa de ready a bloquedo entonces no distingue, pero tranquilamente lo podemos filtrar y ya.
Entonces con tu respuesta me queda claro que cuadno me bloqueo por wait a un recurso no debo mandarlo a ready+
Pero todavia tengo la segunda duda que tambien aplicaria para round robin la cual es: 
Si me desalojo por signal o wait no bloqueante, cuando le devuelvo la ejecucion. puedo resetearle el quantum o debe "acordarse cuanto le queda" para que sea mas justo?

**Comment by iago64** [comment]
Buenas!

Si te bloqueas por un WAIT a un recurso, efectivamente, no va a READY con prioridad, recordemos que el espíritu de VRR es darle mas prioridad a los procesos IO Bound.

El tema del "desalojo" por un signal o un wait que no te termina bloqueando, en realidad es una syscall y para estos casos no deberían reiniciar el Quantum.

Saludos.-
