### ISSUE TITLE
Interfaces

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#3654]
Hola buenas una pregunta. En la conexion kernel e interfaz. Cuando el kernel le manda un sleep a una interfaz, se tiene que quedar esperando a que la interfaz le responda que ya esta disponible de nuevo? 

Y tambien tenia otra duda con las interfaces: Yo cuando me llegue una instruccion de interfaz en CPU lo que hago es devolver un paquete a kernel que tenga el PCB actualizado, el  nombre de la interfaz y el tiempo. Del lado del Kernel recibo el paquete y tenia pensado que a partir de ahi se llame a una funcion que actualice el estado de la interfaz en una lista global que tiene el kernel, que le ponga que esta ocupada y que cree un hilo para hacer el envio a la Interfaz de el sleep y que en el mismo hilo tenga un Recv bloqueante que se quede esperando la respuesta asi cuando la interfaz responde, el hilo en kernel actualiza la lista general de las interfaces y despues el hilo se cerraria. Estaria bien esto de usar un hilo? o es una forma rebuscada? Desde ya muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

Si, el Kernel tiene que esperar la respuesta de la interfaz, ya que cuando la I/O termina, tiene que pasar a READY nuevamente.
La idea de usar un hilo para esperar a la respuesta de la interfaz es una muy buena solución, ya que de otra forma tendrías que ver como te enteras sin estar en una espera activa de que la interfaz terminó.

Saludos.-
