### ISSUE TITLE
Duda instrucción SUB

### ISSUE THREAD

**Issue by Ivanabete** [sisoputnfrba/foro#3655]
Tenemos una duda con la instrucción "SUB". ¿Qué comportamiento debería tener al restarle un registro que contiene un valor más grande a uno que contiene un valor maś chico?

```
void SUB(registrosCPU registroDestino, registrosCPU registroOrigen){
    void *reg_destino = obtenerRegistro(registroDestino);
    void *reg_origen = obtenerRegistro(registroOrigen);

    if (reg_destino == NULL || reg_origen == NULL) {
        printf("Error: Uno o ambos registros no válidos.\n");
        return;
    }

    size_t tam_destino = tamanioRegistro(registroDestino);
    size_t tam_origen = tamanioRegistro(registroOrigen);


    switch (tam_destino) { 
        case sizeof(uint8_t):
            switch(tam_origen){
                case sizeof(uint8_t):
                    *(uint8_t *)reg_destino -= *(uint8_t *)reg_origen; break;
                case sizeof(uint32_t):
                    *(uint8_t *)reg_destino -= *(uint32_t *)reg_origen; break; // Se puede hacer esto?
            }
            break;
        case sizeof(uint32_t):
            switch(tam_origen){
                case sizeof(uint8_t):
                    *(uint32_t *)reg_destino -= *(uint8_t *)reg_origen; break;
                case sizeof(uint32_t):
                    *(uint32_t *)reg_destino -= *(uint32_t *)reg_origen; break;
            }
            break;
    }
}
```

Ej 1:
AX = 20
BX = 30
SUB(AX,BX)
En este caso, donde ambos registros son de 8 bits, la instrucción SUB guarda como resultado en el AX el valor "246".

Ej 2:
EAX = 20
BX = 30
SUB(AX,BX)
En este caso, donde el registro donde se almacena la resta es de 32 bits, y el registro restado es de 8 bits, la instrucción SUB guarda como resultado en el EAX el valor "-10".

¿En alguno de los casos el comportamiento es correcto? ¿Deberíamos contemplar algo para corregir estos casos?

Tampoco entendemos por qué se guarda en el EAX valor "-10", si el tipo de dato uint32_t es unsigned.

Desde ya, muchas gracias.

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va?

> ¿En alguno de los casos el comportamiento es correcto? ¿Deberíamos contemplar algo para corregir estos casos?

Siguiendo la línea de lo que comentaban Dami y Lean en https://github.com/sisoputnfrba/foro/issues/3589, un overflow no es un caso que vayamos a contemplar en las pruebas.

> Tampoco entendemos por qué se guarda en el EAX valor "-10", si el tipo de dato uint32_t es unsigned.

Probablemente esto tenga que ver con cómo leen el valor y no con cómo esté almacenado: si usan `%d`, éste va a leer el entero como un número signado incluso aunque _en teoría_ el valor que tienen guardado es supuestamente sin signo (en realidad, en el fondo son simplemente bytes que `printf()` interpreta).

Lo correcto sería usar `%u`, les muestro el ejemplo opuesto:

```c
#include <stdio.h>
#include <stdint.h>

int main(int argc, char* argv[]) {
    uint32_t a = UINT32_MAX - 9;

    printf("signado: %d\n", a);
    printf("sin signo: %u\n", a);

    return 0;
}
```

```
signado: -10
sin signo: 4294967286
```

Por último, quisiera hacer una observación sobre el código: ¿cómo tienen implementado `tamanio_registro()`? 

Pregunto porque, en caso de que estén usando el operador `sizeof`, tengan en cuenta que lamentablemente éste se calcula en tiempo estático (o sea, al compilar el código), por lo que siempre les va a devolver el mismo valor independientemente de lo que le pasen.

También, en el momento en el que ustedes guardan un puntero en un `void *` están perdiendo la referencia sobre el tipo de dato al que apuntan. Pueden castear para "recuperarlo" cuando ya saben cuál es (como probablemente hagan con las listas), pero C no guarda en memoria ninguna información sobre los tipos de dato que contienen a diferencia de otros lenguajes.

Saludos

**Comment by RaniAgus** [comment]
Ahhh está perfecto como lo plantearon! Al ser un enum ya pueden determinar el tamaño, excelente 👏🏻 

Cierro el issue entonces
