### ISSUE TITLE
Que errores puede tirar la memoria? 

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3656]
Buenas! tenemos unas dudas al ver el log minimos del kernel:

> Fin de Proceso: “Finaliza el proceso <PID> - Motivo: <SUCCESS / INVALID_RESOURCE / INVALID_WRITE>”

Que seria un Invalid Write? se refiere al segment fault? (cuando un proceso quiere acceder a una pagina que no es suya)

Cuales son los errores posibles que puede tirar la memoria y como debe manejarlos? 
Hay algun otro motivo por el cual puede finalizar un proceso aparte de estos o interfaz invalida?

@mesaglio

**Comment by iago64** [comment]
Buenas! cómo va?

Gracias por la observación, si, eventualmente faltaría el motivo OUT_OF_MEMORY.
El tema de acceder a una página que no es suya no sería factible a menos que hagan mal la traducción de direcciones lógicas a físicas.
Por otro lado, todas las pruebas van a calcularse para que nunca se pasen del espacio de direcciones que tienen reservado.

Saludos.-

**Comment by GonTurri** [comment]
Gracias! pero entonces ese invalid read que dice el log obligatorio no existe??

**Comment by iago64** [comment]
Buenas!

Si te referís al INVALID_WRITE, fue un error de copy-paste que se nos pasó también, vino de arrastre de que copiamos los logs obligatorios del TP pasado que nos dieron buenos resultados para seguir la ejecución del TP.
Igual no dejan de ser ejemplos, lo que queremos con el log es que nos digan el motivo que lo mando a EXIT, como por ejemplo:

- **SUCCESS**: El proceso ejecuto la instrucción exit lo mas bien
- **INVALID_RESOURCE**: El proceso pidió una operación sobre un recurso que no existe
- **INVALID_INTERFACE**: El proceso pidió una operación sobre una interfaz que no existe o del tipo incorrecto (aca pueden diferenciarlos si quieren)
- **OUT_OF_MEMORY**: El proceso ejecuto un resize y no había mas espacio en memoria.

Saludos.-

**Comment by GonTurri** [comment]
Perfecto excelente muchas Gracias, no molesto mas
