### ISSUE TITLE
Duda sobre la funcion list_destroy_and_destroy_elements

### ISSUE THREAD

**Issue by santiparis** [sisoputnfrba/foro#3657]
Hola, tenía una duda sobre la función list_destroy_and_destroy_elements, pide un argumento que dice void(*element_destroyer)(void*). Qué debería ser este elemento? Según lo que entiendo debería ser una función para destruir el tipo de elemento que hay en la lista, pero como lo implemento?

Muchas gracias

**Comment by FredeHG** [comment]
Hola buenas o/

Una cosa divertida de las commons es que tienen test donde podes ver como usar las funciones https://github.com/sisoputnfrba/so-commons-library/blob/d22eb0076cc863bcbb7edbdf47ef43e6d434ffc6/tests/unit-tests/test_list.c#L81

En este caso no hay un test especifico pero si un ejemplo de uso

Otra cosa que también recomiendo es leer la guía de puntero, específicamente la parte de punteros de [funciones](https://docs.utnso.com.ar/guias/programacion/punteros#extra-punteros-a-funciones)

También te dejo un issue relacionado sobre esta misma función de las commons https://github.com/sisoputnfrba/foro/issues/3614 

Espero que todo este material sea suficiente para que puedan entender esa función de las commons

Saludos!

**Comment by RaniAgus** [comment]
¡Buenas @santiparis! ¿Te sirvió la respuesta de Fede? Saludos

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, ante cualquier consulta pueden reabrirlo o abrir uno nuevo. Saludos
