### ISSUE TITLE
Consulta del PATH en EJECUTAR_SCRIPT

### ISSUE THREAD

**Issue by VEBravo** [sisoputnfrba/foro#3658]
Consulta, en esta parte del enunciado del módulo kernel dice lo siguiente:
 Ejecutar Script de Instrucciones: Se encargará de abrir un archivo de instrucciones el cual se
 encontrará en la máquina donde corra el Kernel contendrá alguna de las siguientes 5
 Instrucciones y que las deberá ejecutar una a una hasta finalizar el archivo.
 Nomenclatura: **EJECUTAR_SCRIPT [PATH]**
Ese ejecutar_script, de qué manera va a ser escrito:
   EJECUTAR_INSTRUCCION [kernel/memoria/123]
   EJECUTAR_SCRIPT kernel/memoria/123
Capaz es algo obvio pero me cambia mucho entender eso
Lo mismo para FINALIZAR_PROCESO:
   FINALIZAR_PROCESO [5]
   FINALIZAR_PROCESO 5
Porque saber si están los corchetes o no en la instruccion me cambia

**Comment by FredeHG** [comment]
Hola buenas!

Es sin los corchetes, y las instrucciones que puede contener el archivo son las que están en la sección de [funciones por consola](https://docs.google.com/document/d/1-AqFTroovEMcA1BfC2rriB5jsLE6SUa4mbcAox1rPec/edit#heading=h.xovsb05cxhs7)

Entre las cuales NO se encuentra EJECUTAR_INSTRUCCION.

Saludos!

**Comment by VEBravo** [comment]
Perfecto!
