### ISSUE TITLE
Duda sobre memoria y planificacion 

### ISSUE THREAD

**Issue by Lisandrogq** [sisoputnfrba/foro#3659]
Buenas, queríamos hacer dos consultas de enunciado.

La primera es respecto al modulo memoria: ¿Que se almacena en la _'memoria del so'_ (la estructura que almacena los datos del so)?

Por lo que pude ver en el siguiente #3571, esta no debe guardar el codigo del proceso en la _'memoria del so'_ , sino que debemos determinar alguna estructura dentro del modulo memoria para guardar/leer el archivo del codigo fuente de cada proceso.

Ademas, creemos que los PCBs deben estar en el modulo kernel para poder planificarlos.

Por lo tanto, concluimos que lo unico que se almacena en la  _'memoria del so'_  es los datos propios de la ejecucion de cada proceso. Es esto correcto?

La segunda pregunta esta relacionada con esta primera, ya que afectaría lo que se almacena en la  _'memoria del so'_ : ¿ Es correcto almacenar los PCBs en alguna estructura del modulo Kernel?

**Comment by FredeHG** [comment]
Hola buenas! 

Es correcto, lo que llamas `memoria del so` es la memoria de usuario entiendo, seria la memoria de las variables de los programas y esta reservada solamente a estas variables y no hay que usarla para otra cosa

Te dejo un issue relacionado que está bueno para entender esta memoria https://github.com/sisoputnfrba/foro/issues/3566

Si, seria correcto almancenar los PCB en una estructura del modulo Kernel, pero tal vez leyendo el modulo Kernel y que hace con los PCB se les venga a la menta almacenarlo en distintas estructuras segun el estado del proceso ;)

Saludos!

**Comment by Lisandrogq** [comment]
Muchas gracias Fede, Clarisimo!
