### ISSUE TITLE
Duda sobre parámetros de instrucciones

### ISSUE THREAD

**Issue by feedesilva** [sisoputnfrba/foro#3660]
Buenas! estamos con la duda de donde se reciben los parámetros de las instrucciones en cpu.
En fetch entendemos que lo único que se recibe es el código de instrucción, y en execute vemos que instrucción es y cómo se ejecuta. 
Lo que no terminamos de entender es si los parámetros que tienen las instrucciones se reciben en fecth o en decode

**Comment by FredeHG** [comment]
Hola buenas!

En el fetch se obtiene toda la instruccion, en el formato que lo ven en el [ejemplo de instrucciones a interpretar](https://docs.google.com/document/d/1-AqFTroovEMcA1BfC2rriB5jsLE6SUa4mbcAox1rPec/edit#heading=h.i8zdk7fpdqzg) del enunciado

Saludos!

**Comment by feedesilva** [comment]
Perfecto, gracias!
