### ISSUE TITLE
Implementar mutex a los sockets

### ISSUE THREAD

**Issue by papiness77** [sisoputnfrba/foro#3661]
Buenas, tengo entendido que a la hora de hacer un send o un recv de una conexion lo puede hacer solo 1 hilo a la vez porque sino bloquearian el "pipe" de la conexion. Entonces estaba pensando en implementar eso haciendo un struct que tenga un mutex y un puntero a una funcion, que puede ser cualquier funcion a ejecutar. Esta bien hacer esto? Y  creo que un problema es que a la hora de pasar la funcion tengo que especificar cuantos parametros recibe, la solucion seria decir que recibe un void* y ahi serializar los datos que recibe supongo. Porque sino la otra posibilidad es poner los mutex directamente en todos los lados donde llamas a las funciones y te podes olvidar de algunos ademas de que queda feo. Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

En que momento estarías teniendo 2 hilos tratando de acceder al mismo socket? A veces es fundamental antes de querer implementar algo encontrar el motivo que nos haga implementarlo y el contexto que nos rodea a ver si podemos no complicarnos la vida.
La pregunta viene porque un puntero a función y un parámetro `void*` en la teoría es hermoso pero en la realidad se pone áspero para implementarlo y que no tenga errores.

Saludos.-
