### ISSUE TITLE
Serializacion y envio de procesos

### ISSUE THREAD

**Issue by Cpallmieri** [sisoputnfrba/foro#3662]
Tenemos un problema a la hora de serializar. Cuando serializamos una estructura con un codigo de operacion este llega a destino con unos valores que no son. Dejo abajo el codigo que puede ayudar a ver el error.

### 📝 Código relevante

como se llena el buffer:
```C
void proceso_llenar_buffer(t_buffer *buffer, t_proceso *proceso) {
    // Calcula el tamaño total necesario para almacenar los datos del proceso en el buffer

    int nombre_length = strlen(proceso->nombre) + 1;
    int path_length = strlen(proceso->path_instrucciones) + 1;

    buffer->size = sizeof(op_code) + sizeof(int) + nombre_length + path_length;

    // Asigna memoria para el buffer
    buffer->stream = malloc(buffer->size);

    if (buffer->stream == NULL) {
        printf("Error para asignar memoria al buffer");
        return;
    }

        int offset = 0;  // Reinicia el offset
    memcpy(buffer->stream, &(proceso->cod_op), sizeof(op_code));
    offset += sizeof(op_code);

    memcpy(buffer->stream + offset, &(proceso->id), sizeof(int));
    offset += sizeof(int);

    memcpy(buffer->stream + offset, proceso->nombre, nombre_length);
    offset += nombre_length;

    memcpy(buffer->stream + offset, proceso->path_instrucciones, path_length);
}
```

Como se crea el proceso:
```C
t_proceso *proceso_crear(int id, char *nombre, char *path_instrucciones) {
    t_proceso *proceso = malloc(sizeof(t_proceso));

    if (proceso == NULL) {
        printf("Error para asignar memoria al proceso");
        return NULL;
    }

    // Asigna memoria para copiar las cadenas de nombre y path_instrucciones
    proceso->nombre = malloc(strlen(nombre) + 1);

    if (proceso->nombre == NULL) {
        printf("Error para asignar memoria al nombre del proceso");
        free(proceso);
        return NULL;
    }

    strcpy(proceso->nombre, nombre);

    proceso->path_instrucciones = malloc(strlen(path_instrucciones) + 1);

    if (proceso->path_instrucciones == NULL) {
        printf("Error para asignar memoria al path de instrucciones del proceso");
        free(proceso->nombre);
        free(proceso);
        return NULL;
    }

    strcpy(proceso->path_instrucciones, path_instrucciones);

    proceso->id = id;
    proceso->cod_op = PROCESO;

    return proceso;
}
```
Cuando se ejecuta todo el codigo la memoria del stream se ve así:
![image](https://github.com/sisoputnfrba/foro/assets/102747342/b9ff36d1-c341-415e-b285-b5f0a02e2ecf)
El cpu lo recibe de esta manera
![image](https://github.com/sisoputnfrba/foro/assets/102747342/d4581470-73d0-4451-8548-eec61798b18b)

Cpu:
```C
 while (1) {
        int cod_op = recibir_operacion(nuevo_socket_dispatch);

        switch (cod_op) {
            case PROCESO:
                // paquete_de_proceso = recibir_proceso(nuevo_socket_dispatch, logger);
                log_info(logger, "Me llego un paquete con un proceso:\n");
                break;
            case -1:
                log_error(logger, "el cliente se desconecto. Terminando servidor");
                return EXIT_FAILURE;
            default:
                log_warning(logger, "Operacion desconocida. No quieras meter la pata");
                break;
        }
    }
```
Recibir proceso
```C
int recibir_operacion(int socket_cliente) {
    int cod_op;
    if (recv(socket_cliente, &cod_op, sizeof(int), MSG_WAITALL) > 0) {
        return cod_op;
    } else {
        close(socket_cliente);
        return -1;
    }
}
```

**Comment by FredeHG** [comment]
Hola buenas! 

Lo primero pegarle una mirada a la guía de [serialización](https://docs.utnso.com.ar/guias/linux/serializacion#objetivo) porque tal vez en la vorágine de reutilizar código del tp0 hay conceptos que no están teniendo en cuenta a la hora de poder depurar el código que están copiando

Como sabrán entender con la vista limitada que tengo del código tengo que imaginar como implementaron ciertas partes, pero voy a hacer mi mejor esfuerzo por darles herramientas para que puedan entender y solucionar que les está pasando

Primero veo que están loggeando `Operacion desconecida...` lo que estaría muy bueno es saber que valor específicamente es operación desconocida, es decir que `op_code` se leyó del socket, ese valor que se lee tiene sentido con algo de lo que específicamente enviaron?

El stream a simple vista se ve bien no? 
Digamos podemos leerlo sin mayores problemas, 00 00 00 00 es un numero que vale 0, lo que me da a entender que PROCESO es el valor 0 de un enum, por lo que imagino que ocupa 4 bytes, 

lo hace? que les dice sizeof del enum `op_code`?

Luego vemos un 43 que al estar codificado en binario es un numero hexa es el valor 67, (esta en litte endian la notación que ya les debe sonar de arquitectura) me suena raro a mi ese numero, pero ustedes me dirán si al process_id le pusieron el numero 67 o no, si no lo hicieron algo raro esta pasando ahí, "huele mal" y finalmente están sus strings `proceso 1` y `ruta que no existe`

Entonces es claro que el problema está del otro lado, no? no????

Bueno vamos del otro lado, lo primero que pregunto es PROCESO del otro lado es el mismo enum no? ese switch usa el mismo op_code o en su defecto la definición del enum es la misma, no?

Y acá para empezar a debuggear en fino algo muy útil es sacar su código de lado, y pedirle al socket que les de la info en cruda para ustedes poder analizarla

yo lo que haría es contar la longitud del stream que quiero mandar y hacer un recv de ese tamaño, como? 

fácil 
```C
void* puntero;
recv(socket_cliente, puntero, {tam de lo que enviaron}, MSG_WAITALL);
```

En este caso enviaron
00 00 00 00 43 00 00 00 y los string que no los voy a escribir en hexa, no estoy tan limado... a esta hora al menos
seria 29 de los string (si conte bien) + 8 de los int = 37

Y con eso la línea del recv le ponen un 37, luego del recv con un breakpoint pueden ver que llega del socket

Y ahí el rey está desnudo, ya no hay mas secretos van a tener lo que mandaron y lo que reciben y tiene que ser igual, si no es igual, tienen que ver si están realmente enviando lo que dicen enviar o si están haciendo lio con un puntero o algo similar

si es igual, pues nada poner a ver como están interpretando ese dato que les llego

Mis 3 pesos van a que no están enviando bien dado que el recibir operación es del tp0 y un 00 00 00 00 lo va a interpretar si o si como un 0. Y dudo que tengan PROCESO 2 veces declarados


Agradezcan que este [álbum](https://www.youtube.com/watch?v=NvvnmtMkOWw&list=PL13WQM-VUiIHoXmLvnYghRlMQb0dXXTO6) dura lo suficiente como para que yo me haya puesto a escribir todo esto

Espero que les sea de utilidad, disfruten los días de lluvia que se vienen para serializar todo lo que se pueda serializar

Saludos!

**Comment by Cpallmieri** [comment]
Pude resolverlo, cierro el issue, muchas gracias!!
