### ISSUE TITLE
Duda sobre Logs de motivos de finalacion de un proceso

### ISSUE THREAD

**Issue by ThiagoGonzalezz** [sisoputnfrba/foro#3663]
Buenass, agrego una duda al issue #3656 . En caso de que se finalice un proceso por el comando de la consola del kernel,  y que por esta razón se envia el proceso a exit. Cual seria el motivo que debería loggear?

**Comment by iago64** [comment]
Buenas! Cómo va?

Como se dijo en el issue, la idea es que pongan el motivo, en el caso de una finalización por consola del Kernel, pueden poner SUCCESS o pueden poner CONSOLA_KERNEL y en ambos casos va a estar bien, total vamos a saber que lo matamos nosotros.

Saludos.-

**Comment by ThiagoGonzalezz** [comment]
Quedo claro, muchas gracias.
