### ISSUE TITLE
conexion de cpu con memoria

### ISSUE THREAD

**Issue by BrianVillarroel94** [sisoputnfrba/foro#3664]
Hola necesitamos ayuda la con la conexion de  de Cpu con me Memoria, corrimos el resto de lso modulos y no tuvimos problema y cuando realizamos RUN en CPU nos muestra el error "EXCEPTION HAS ACURREND. (SEGMENTATION FAULT)

![segmentation fault](https://github.com/sisoputnfrba/foro/assets/112217453/1325cf5c-b070-4fd3-954b-a6688a564441)

![segmentation fault-1](https://github.com/sisoputnfrba/foro/assets/112217453/1bdfc7b4-ac0f-416e-964c-11a2d02d6956)

**Comment by FredeHG** [comment]
Hola buenas!

Como sabrás entender a nosotros un screenshot que dice segmentation faul nos dice bastante poco y en la segunda screenshot nos tapas la salsa.

Pero para todos los problemas de este tipo tenemos una herramienta ideal! [Valgrind](https://docs.utnso.com.ar/guias/herramientas/valgrind#tutorial-de-valgrind-y-helgrind)

Que también la podes ejecutar haciendo `make memcheck` parado en el modulo que este fallando, si queres proba con eso trata de entender que dice y si no te sale volve a este issue y pásanos que es lo que dice valgrind

Saludos!

**Comment by RaniAgus** [comment]
¡Buenas @BrianVillarroel94! ¿Te sirvió la respuesta de Fede? Saludos

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, ante cualquier consulta pueden reabrirlo o abrir uno nuevo. Saludos
