### ISSUE TITLE
pequeña consulta sobre el tiempo de unidad de trabajo en interfaces genericas

### ISSUE THREAD

**Issue by nicolasvultaggio** [sisoputnfrba/foro#3665]
IO_GEN_SLEEP (Interfaz, Unidades de trabajo)

esas unidades de trabajo en que unidad de tiempo vienen? en milisegundos? segundos?
yo habia pensado una cosa así para aplicarlas,

```
char * instruccion = recibir_instruccion_de_kernel(); 
char ** elementos_de_instruccion = string_split(instruccion , " ");
usleep((__useconds_t) atoi(elementos_de_instruccion[2]);
``` 

suponiendo que, bueno, esas unidades de trabajo vienen en milisegundos a esperar, pero bueno, si vienen en segundos, esto estaría mal.
Dicho esto, ¿para que hace falta levantar del archivo de configuracion el tiempo_unidad_trabajo? no se supone que eso depende del valor de la instruccion? o el valor del config se tiene que multiplicar al de la instruccion? eso basicamente, no entiendo para que se usa el tiempo_unidad_trabajo levantado del config para esperar esa cantidad de tiempo. Muchas gracias, buen finde, no hace falta la respuesta hoy, porque es domingo, mil perdones. Un saludo.

**Comment by FredeHG** [comment]
Hola buenas!

El segundo parámetro del IO_GEN_SLEEP es la cantidad de unidades de trabajo que tiene que esperar, y el archivo de configuración es lo que dura 1 unidad de trabajo, con esto en mente el tiempo de espera es unidades de trabajo * tiempo por unidad de trabajo, es decir, segundo parámetro * TIEMPO_UNIDAD_TRABAJO

Yo gasto mi domingo como quiero (?)

Saludos!

**Comment by nicolasvultaggio** [comment]
jajajja ahi entendí, muchas gracias profe, me quedo claro
