### ISSUE TITLE
pequeña duda sobre el funcionamiento de mutex

### ISSUE THREAD

**Issue by nicolasvultaggio** [sisoputnfrba/foro#3668]
Si los procesos A y B quedan bloqueados por un mutex , pero supongamos que A se bloqueó antes que B, eso quiere decir que cuando se habilite el mutex, A entrará a la sección critica primero y B tendrá que esperar a  que A habilite el mutex?

**Comment by RaniAgus** [comment]
¡Buenas! Como los hilos de la biblioteca pthread son manejados por el sistema operativo (KLTs), en caso de que haya más de un hilo esperando adquirir el lock, el orden en el que se despierten va a depender del algoritmo de planificación:

> The pthread_mutex_unlock() function shall release the mutex
       object referenced by mutex. [...] If there
       are threads blocked on the mutex object referenced by mutex when
       pthread_mutex_unlock() is called, resulting in the mutex becoming
       available, **the scheduling policy shall determine which thread
       shall acquire the mutex**.

Link: https://man7.org/linux/man-pages/man3/pthread_mutex_lock.3p.html

De todas formas, dudo mucho que para implementar el TP haya algún caso en el que necesiten que el orden sea determinístico.

Saludos

**Comment by nicolasvultaggio** [comment]
o sea, básicamente, no hay forma de determinar cual entrará primero.
En este caso estaba intentando implementar una solución a un problema en el que justo sí es determinístico,:

cuando el kernel, en planificación a largo plazo (en un hilo que atiende respuesta de dispatch), recibe una petición a una io, debe verificar si existe y si acepta la instrucción (si no cumple alguna lo manda a exit), si la cumple, manda el proceso a blocked de esa interfaz: Y ACÁ ME SURGEN DOS OPCIONES PARA RESOLVER:

1)cuando manda el proceso a cola de blocked DE ESA INTERFAZ, tiene que iniciar un hilo  que se encargue de esperar a que esa interfaz esté habilitada CON MUTEX, y cuando se habilite este mutex, hace la petición a la interfaz, y se queda esperando la respuesta, cuando la interfaz devuelve la respuesta, el hilo, debe marcar a la interfaz como habilitada (signal al  mutex de renglón de arriba), y además habilitar semáforo del hilo de la vuelta a blocked (es otro hilo que cada vez q se lo habilita, hace pop de blocked y lo envía a su lista correspondiente)

EL PROBLEMA CON esto es, que si una petición  de un proceso A se demora mucho, supongamos que hasta ese momento venía esperando otro proceso B para usar la interfaz, y en un momento dado, otro proceso C hace una petición a la misma interfaz, puede pasar que cuando A libere la interfaz, se atienda la petición de C antes que la de B, que ya venía esperando de antes, rompiendo el FIFO del manejo de IO.

la otra solución que se me ocurrió recién recién, pero creo que es mas complicada es:

cuando se encola el pcb en blocked, aumentar un semáforo (este sem es igual a la cantidad de procesos en blocked, o sea, habrá uno de estos semáforos por interfaz, este semáforo debe crearse básicamente cuando se conecta una interfaz a kernel).
este semáforo se esta esperando en OTRO HILO (creado al conectarse la interfaz) que hace while infinitamente, pero se quedará bloqueado si no hay procesos en blocked, si hay uno o mas, agarra el primer pcb de la cola, procesa su instrucción con la interfaz y cuando recibe respuesta de interfaz lo encola en su lista correspondiente según el algoritmo (repite ciclo)

EL PROBLEMA CON ESTA ES, si bien no rompe el fifo, porque atiende las peticiones de a una y en orden, tiene que crear un semáforo dinámicamente (no puede ser una variable global como siempre porque, no se sabe cuantas interfaces van a conectarse), y además este semáforo lo tendrá que utilizar un hilo que se crea al mismo instante que ese semáforo, entonces me rompe la cabeza eso, si pueden crearse semáforos dinámicos y pasarse por parámetro a hilos.

Básicamente, estoy entre esas dos opciones, ambas tienen aspectos que no me cierran, yo creo que me inclino un  más por la segunda opción, pero igual no se si los problemas que planteo para cada una tienen solución, por lo menos creo que para la primera no hay solución.

Muchas gracias por el tiempo, agradezco mucho la ayuda que me dan, buen Lunes. Un saludo!

**Comment by iago64** [comment]
Buenas! Cómo va?

Creo que estas sobrediseñando muchísimo la solución de las interfaces y eso te lleva a hacerte preguntas muy copadas sobre como estan implementados los semáforos en linux, pero te complican la resolución, por eso voy a ir por el camino mas feliz que es simplificar la implementación del TP y dejar las dudas existenciales para mas tarde.

La idea de las interfaces es que van a tener alguna estructura que funcione como una cola de bloqueados y que le manden de a 1 a la interfaz los pedidos de ejecución, por lo que, ahi tenemos el primer _productor consumidor_ claro del TP, donde por un lado el _hilo del planificador de corto plazo_ va a ir dejando los procesos en `BLOCK` y por otro un hilo que va a mandar a ejecutar a la interfaz los diferentes procesos, esto es un poco lo que vos planteaste en tu segunda solución donde el problema que encontraste es que tendrías semáforos dinámicos.
Aca es donde yo te pregunto, ¿No tenes alguna estructura _dinámica_ que puedas dejar como varaible global y que te permitirta crear bajo demanda entradas donde tengas una estructura con los datos que te sirven para la interfaz? Estos datos pueden ser algo asi como:
- Nombre de la interfaz
- Tipo de interfaz
- Semáforos asociados
- Cualquier cosa que necesites

Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas!
Exactamente, la opción 1 no es la indicada ya que los mutex no te garantizan un orden, sino solamente que accedan uno a la vez a la región crítica.

Como te recomendó @iago64, la opción 2 está mucho mejor encaminada, es prácticamente igual a un ejercicio de sincro tipo "productor-consumidor".

**Comment by nicolasvultaggio** [comment]
EXCELENTE.
Me quedó clarísimo lo del productor-consumidor, es la misma idea que en los ejercicios de sincronización.
Con respecto a la primer respuesta, y en cuanto a la pregunta que me hace @iago64 , de hecho, yo había pensado que, cuando se conecte la interfaz a kernel, el kernel tenga que "almacenar" la existencia de esta interfaz en una lista dinámica de interfaces, que sirve básicamente para que el kernel la conozca. Entonces, sumando a la ESTRUCTURA PROPUESTA, yo podría hacer que los ELEMENTOS de esa lista sean como LOS QUE SE ME PROPONE (nombre, tipo, semáforos, etc.), de esta forma, al estar todos los valores en el heap, varios hilos podrían acceder a sus valores, la estructura funciona como una variable global. Entonces cuando yo delegue ese hilo que, de a uno, va ejecutando operaciones en la interfaz , podría pasarle por parámetro esta estructura dinámica sugerida (el elemento de la lista), para que la desglose y se ponga a hacer el WHILE mencionado con los semáforos que contenga.  
¿ESTO que acabo de explicar es lo que en la pregunta, se refiere como una 

> estructura dinámica que puedas dejar como variable global y que te permita crear bajo demanda entradas donde tengas una estructura con los datos que te sirven para la interfaz

?

**Comment by iago64** [comment]
Buenas! Cómo va?

Efectivamente una lista es la estructura que te decía que pueden tener de manera global y que a partir de ahi puedan tener toda la info, incluidos los semáforos, de una interfaz.

Saludos.-

**Comment by nicolasvultaggio** [comment]
muchas gracias por la ayuda, de verdad. Buena semana.
