### ISSUE TITLE
Duda  DIALFS: mmap y msync

### ISSUE THREAD

**Issue by GregorioOndjian** [sisoputnfrba/foro#3669]
Buenas, el sabado pasado estuvimos haciendo unas consultas en soporte acerca de como encarar el tema del bitmap en dialFS. Nos comentaron que nos convenia utilizar por un lado, para manejar el bitmap en si, las funciones de bitarray que estan en las commons, por otro nos dijieron que habría que guardar ese bitarray en un arrchivo. Nos explicaron que podiamos mapear el archivo en memoria y luego cada vez que lo cambiaramos sincronizarlo con la funcion msync. Es correcto?
Mi duda viene por el lado de que si tengo que poner el bitarray en el archivo, como lo hago? o si tengo que encarar el tema del bitrray por otro lado.

**Comment by iago64** [comment]
Buenas! Cómo va?

El bitmap lo tienen que guardar en un archivo ya que si no lo hacen, simplemente pierden la persistencia que es la idea de tener un File System, ahora la forma en la que lo hagan puede variar de acuerdo a como lo quieran hacer.
Utilizar `mmap()` para tener el contenido del archivo en memoria y poder crear el bitarray a partir de ahí es una opción válida y la de utilizar `msync()` para forzar que se guarde en el archivo también es válida, aunque no es tan necesario porque en la VM no suelen tener tanta carga de trabajo en el disco como para que el proceso se demore en actualizar los cambios.

Saludos.-

**Comment by GregorioOndjian** [comment]
Buenisimo, muchísimas graciass.
