### ISSUE TITLE
Comando consola: PROCESOS_ESTADO

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3670]
Buenas, tengo una duda con respecto al comando que se menciona en el tiulo del issue. Como se deberian imprimir los procesos en BLOCKED?
Por cada IO o recurso:
IO1:P4,P5
IO2:P6,P7
RA:P1,P2
¿O en un blocked general que agrupe a todos (no sé en que orden deberian ir P1,P2,P4,P5,P6,P7)? También podría ser una cola de bloqueados general en donde esten los procesos que están actualmente utilizando la IO y mostrar unicamente esa cola y los que están en espera dejarlos en la cola de cada IO o recurso y no mostrarlos. Creo que esto ultimo no estaría bien igual porque no se estarían mostrando algunos procesos.

**Comment by iago64** [comment]
Buenas! Cómo va?

No hay problema, pueden poner los bloqueados por recurso siempre que se entienda que están en el estado Blocked.

Saludos.-

**Comment by rood8592** [comment]
Gracias!
