### ISSUE TITLE
¡¿Cspec corre los test concurrentemente?!

### ISSUE THREAD

**Issue by Mimito164** [sisoputnfrba/foro#3671]
![](https://i.pinimg.com/originals/f7/32/95/f732954f644b8a4aa70f0da04eb287d2.jpg)
...... fin de la pregunta 😁.

Estuve haciendo algunas pruebas que involucran un mutex para alguna sección crítica, pero tuve un problema de integridad de datos. Probe corriendo los test de a uno a la vez y todos pasaron, pero corriendo todos en simultáneo la mayoría no pasaron.

No se si tenga que cambiar mi estrategia de cómo es que uso los semáforos, por ejemplo liberando el mutex ni bien termine de usar la sección critica, o si hay alguna opción de cspec para correr los test secuencialmente.

**Comment by iago64** [comment]
Buenas! Cómo va?

Justo C-Spec es algo sobre lo que no tenemos tanto control y siendo que es un framework que está pensado para pruebas sencillas, yo te diría que no pierdas la cabeza con el hecho de que algo con semáforos no funcionó como esperabas y que enfoques tus esfuerzos en usar cspec para pruebas unitarias simples como por ej validar que operas bien los archivos en un DialFS o que calculas correctamente direcciones de memoria y demas y que las pruebas de integración las hagas siguiendo el caso de uso del TP.

Saludos.-

**Comment by Mimito164** [comment]
Muchas gracias Damian
