### ISSUE TITLE
Tengo problema para encontrar bibliotecas!

### ISSUE THREAD

**Issue by fmigliavacca** [sisoputnfrba/foro#3673]
Hola, comento mi situación, yo venía haciendo el tp de lo más bien, compilaba y ejecutaba correctamente y por un motivo necesité eliminar el repo y volver a clonarlo. El problema es que cuando volví a clonarlo ya no me encontraba la biblioteca utils, y yo supongo que es por que no me encuentra las commons. Adjunto foto de lo que me salta
![image](https://github.com/sisoputnfrba/foro/assets/163766676/996dc572-df43-4931-8777-a3f98e9dd351)
Honestamente no sé qué pueda ser pero capaz alguno ya tuvo un problema similar y tienen más cancha para ayudarme :)
Aclaro por las dudas que tengo las commons instaladas y todo al día y que en otras 2 máquinas con configuraciones similares el tp ejecuta correctamente. O sea, que esto es 100% seguro que es a raíz de haber borrado el repo

**Comment by FredeHG** [comment]
Hola buenas!

Es posible que la ruta en la que tengas el tp tiene un espacio? 

Hay un issue donde encontraron un problema similar https://github.com/sisoputnfrba/foro/issues/3492

Saludos!

**Comment by fmigliavacca** [comment]
Como va! No, no es el caso
![image](https://github.com/sisoputnfrba/foro/assets/163766676/74001a0b-9609-44d8-9785-9232aeea8cb4)
Alguna otra posible solución? Como digo, antes tenía el tp copiado en la misma ruta, todo igual

**Comment by iago64** [comment]
Buenas! Cómo va?

Honestamente con las capturas de pantalla recortadas hay muy poco que podamos hacer, te puedo pedir si subís todo el output que genera cuando tiras el `make all`? Asi tenemos mas contexto y vemos realmente que es lo que esta pasando.
Porque acabo de bajarme su repo y la memoria de la rama main compiló sin problemas.

Saludos.-

**Comment by fmigliavacca** [comment]
Al final desinstale e instale las commons devuelta y no funcionaba. Reinicie la compu un par de veces y funco, debe haber sido un bug. Gracias por la ayuda igualmente! Cierro el issue
