### ISSUE TITLE
Kernel: Finalizar proceso

### ISSUE THREAD

**Issue by Mimito164** [sisoputnfrba/foro#3675]
Necesito saber si la instrucción de consola: `FINALIZAR_PROCESO` puede llegar a ser ejecutada con la planificación habilitada.

Segun este issue #3225 la instrucción debe ser capaz de finalizar un proceso en todos los estados. Pero si está habilitada la planificación, puede ser un inconveniente muy importante, porque puede ser que justo haya sacado un proceso de una lista y nunca encontrar el proceso porque quedó en medio de una transición.

### 💭 Soluciones posibles

**Suponiendo que la función `FINALIZAR_PROCESO` es capaz de ser ejecutada mientras está habilitada**:

El primer approach que se puede hacer es lo que dije antes. Se busca en cada lista si está el proceso que se desea eliminar, una vez se encuentra en alguna lista, se lo saca de la lista, se liberan los recursos y memoria y fin.
Pero el problema es el de las transiciones mencionado anteriormente.

Un segundo approach sería agregar el pid a una blacklist y cada vez que se desee transicionar un pcb se chequea si está en la blacklist, si está en la blacklist se elimina, si no está en la blacklist se le permite realizar la transición.
Pero el problema en este caso es que si se trata de un proceso que esta en deadlock nunca va a transicionar. Y un segundo problema es que cuando uno ejecuta `FINALIZAR_PROCESO` espera a que el proceso se elimine del sistema liberando espacio en memoria y permitiendo que nuevos procesos ingresen, pero con esta solución esto no pasa, hasta que el proceso no transicione no se va a poder eliminar, lo que puede llegar a ser un problema.

Un tercer approach sería hacer un híbrido entre el primer y segundo approach. Por un lado se leen las listas y por otro se revisan todas las transiciones. En este caso el único problema sería codearlo 😢. Todavía no se me ocurre bien como hacer esto.

**Comment by FredeHG** [comment]
Hola buenas!

Te voy a responder lo mismo que en otro issue así que directamente te lo paso https://github.com/sisoputnfrba/foro/issues/3672

Aunque me gusta la solución hibrida 😄 

Saludos!
