### ISSUE TITLE
Tipos de variables para instrucciones

### ISSUE THREAD

**Issue by tomassagrada** [sisoputnfrba/foro#3676]
Buenas, para las instrucciones yo por lo que vi supuse que las variables podían ser registros (numéricas), de interfaces (que es depende como las identifiquemos), de nombres de archivos (texto) y no se si me estaría faltando algún tipo (porque cosas como los recursos dependen de como las identifiquemos no?). 

Aclaración: Pregunto porque estoy haciendo el diccionario y tengo pensado filtrar la ejecución según el tipo de instrucción basándome en sus variables
![image](https://github.com/sisoputnfrba/foro/assets/143655825/af40b82b-8def-43c8-b346-241e2b9dbdd0)
así pero filtrado con probablemente casos de switch

**Comment by FredeHG** [comment]
Hola buenas!

Los recursos serian de está forma WAIT RECURSO_1 como se puede ver en los [ejemplos de instrucciones](https://docs.google.com/document/d/1-AqFTroovEMcA1BfC2rriB5jsLE6SUa4mbcAox1rPec/edit#heading=h.i8zdk7fpdqzg)

Podrías igualmente tomar todas las variables como `void*` y que la función de tu diccionario sepa castearlas o que los parámetros sean una estructura que tenga los tipos y cantidades de instrucciones máximas y tu función tome de esa estructura lo que necesita conseguir, con sus clausulas de guarda para poder retornar si algo necesario no llego

Esta muy bueno usar un diccionario porque te da una escalabilidad en el código interesante, pero no es como que vayas a utilizarla en este TP

Como no veo una pregunta puntual en el issue decime si hay algo más particular en lo que te pueda ayudar :D 

Saludos!

**Comment by tomassagrada** [comment]
Gracias, era para ver si masó menos si me faltaban algunas variables. Si tomase las variables como *void me ahorraría el tener tantos casos y funciones distintas no?
