### ISSUE TITLE
Implementación de TIEMPO_UNIDAD_TRABAJO

### ISSUE THREAD

**Issue by ElielBejar** [sisoputnfrba/foro#3677]
Hola que tal! Tengo una duda en C sobre como implementar una función para que el tiempo de uso de una interfaz sea la indicada por las unidades de trabajo. Quisiera saber si hay una función para esperar una cantidad de tiempo o tengo que usar un cronometro de las commons y pararlo cuando haya llegado al tiempo que tiene que esperar.

Por ejemplo si se va a usar una interfaz io_gen_sleep que tiene que esperar 2 unidades de 1000 milisegundos, como hago en C para que exactamente espere ese tiempo?

Despues, tengo una pequeña duda más sobre el fylsistem. No terminé de entender si tiene que haber un filesystem para cada interfaz dialfs que se conecte o un solo filesystem para todas las interfaces dialfs?

Desde ya gracias! Y perdón que las anteriores veces no cerré el issue, pensé que solo lo podían hacer los profesores. Saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

La función que estas buscando en [`usleep()`](https://man7.org/linux/man-pages/man3/usleep.3.html), solamente tenes que tener en cuenta que `uslee()` opera en microsegundos, por lo que para usar milisegundos, tendrías que multiplicarlo x1000

Saludos.-

**Comment by ElielBejar** [comment]
Dale gracias! Y después la duda esa del filesystem como sería? tengo que tener un archivo bloques.dat por cada interfaz dialfs que se conecte o solo una y todas las interfaces dialfs conectadas interactuan con él?
