### ISSUE TITLE
Inconveniente con Conexion entre Modulos

### ISSUE THREAD

**Issue by Sebastian-Faingerch** [sisoputnfrba/foro#3680]
Buenas, estamos teniendo inconvenientes a la hora de conectar el servidor de Memoria, con el cliente del Kernel. A nosotros nos funcionaba pero al reestructurar el trabajo practico para que quede mas legible y comprensible no entendemos el porque nos entrega estos valores que no coinciden con los que veniamos trabajando.

### 📝 Código relevante
```C
int conectarMemoria() {

    int conexion_memoria;
    char* ip;
    char* puerto_memoria;
    char* valor;

	ip= config_get_string_value(config_kernel,"IP_MEMORIA");
	puerto_memoria=config_get_string_value(config_kernel,"PUERTO_MEMORIA");
    valor = config_get_string_value(config_kernel, "CLAVE");

    // Loggeamos el valor de config

    log_info(logger_kernel, "Valor leido de la config: %s", valor);

    // Creamos una conexion hacia el servidor

    conexion_memoria = crear_conexion(ip, puerto_memoria);

    // Enviamos al servidor el valor de CLAVE como mensaje

    enviar_mensaje(valor, conexion_memoria);

    if (conexion_memoria <= 0){
        log_info(logger_kernel, "No se pudo establecer una conexion con la Memoria\n");
    }
    else{
		log_info(logger_kernel, "Conexion con Memoria exitosa");
    }

    // Haciendo handshake

    int handshake = KERNEL;
	bool confirmacion;

	send(conexion_memoria, &handshake, sizeof(int),0);		//ATADO CON ALAMBRE
	recv(conexion_memoria, &confirmacion, sizeof(bool), MSG_WAITALL);

	if(confirmacion)
		printf("Conexion con memoria exitosa");
	else
		printf("ERROR: Handshake con memoria fallido");

    paquete(conexion_memoria);

    conexiones++;

     terminar_programa(conexion_memoria, logger, config_kernel);
    }
    
int atenderKernel() {

        logger = log_create("logServerMemoria.log", "SV_MEMORIA", 1, LOG_LEVEL_DEBUG);

        char *puerto = config_get_string_value(config_memoria, "PUERTO_ESCUCHA");

	    int server_memoria = iniciar_servidor(puerto);
	    log_info(logger, "Servidor listo para recibir al cliente");
	    int cliente_memoria = esperar_cliente(server_memoria);
		printf("cliente memoria: %d\n", cliente_memoria);
	    t_list* lista;
	    while (1) {
		    int cod_op = recibir_operacion(cliente_memoria);
		    switch (cod_op) {
		    case MENSAJE:
			    recibir_mensaje(cliente_memoria);
			    break;
		    case PAQUETE:
			    lista = recibir_paquete(cliente_memoria);
			    log_info(logger, "Se conecto correctamente a Memoria\n");
			    break;
		    case -1:
			    log_error(logger, "el cliente se desconecto. Terminando servidor");
			    return EXIT_FAILURE;
		    default:
			    log_warning(logger,"Operacion desconocida. No quieras meter la pata: %d", cod_op);
			    break;
		        }
	}
	return EXIT_SUCCESS;
    }
```

### 🐛 Cómo reproducir el error

Ejecutamos la carpeta Memoria primero, y luego la Carpeta Kernel y ocurre dicho error.
En los logs se pueden ver como ponemos el codigo de operacion para entender mejor porque ocurria esto

### 💻 Logs

[INFO] 18:15:56:213 SV_MEMORIA/(7588:7600): Servidor listo para recibir al cliente
[INFO] 18:15:56:230 SV_MEMORIA/(7588:7601): Servidor listo para recibir al cliente
[INFO] 18:15:56:232 SV_MEMORIA/(7588:7602): Servidor listo para recibir al cliente
[WARNING] 18:16:08:636 SV_MEMORIA/(7588:7600): Operacion desconocida. No quieras meter la pata: 11
[WARNING] 18:16:08:636 SV_MEMORIA/(7588:7600): Operacion desconocida. No quieras meter la pata: 544829267
[WARNING] 18:16:08:636 SV_MEMORIA/(7588:7600): Operacion desconocida. No quieras meter la pata: 1852990795
[WARNING] 18:16:08:639 SV_MEMORIA/(7588:7600): Operacion desconocida. No quieras meter la pata: 134245477

**Comment by RaniAgus** [comment]
¡Buenas! ¿En `atenderKernel()` se está llamando a alguna función que atienda el handshake? También me hace ruido que en `conectarMemoria()` estén llamando a `enviar_mensaje()` antes de realizar el handshake, en lugar de después.

Saludos

**Comment by Sebastian-Faingerch** [comment]
`int conectarMemoria()
{

    int conexion_memoria;
    char *ip;
    char *puerto_memoria;
    char *valor;

    ip = config_get_string_value(config_kernel, "IP_MEMORIA");
    puerto_memoria = config_get_string_value(config_kernel, "PUERTO_MEMORIA");
    valor = config_get_string_value(config_kernel, "CLAVE");

    // Loggeamos el valor de config

    log_info(logger_kernel, "Valor leido de la config: %s", valor);

    // Creamos una conexion hacia el servidor (socket y connect)

    conexion_memoria = crear_conexion(ip, puerto_memoria);

    // Enviamos al servidor el valor de CLAVE como mensaje

    enviar_mensaje(valor, conexion_memoria);

    if (conexion_memoria <= 0)
    {
        log_info(logger_kernel, "No se pudo establecer una conexion con la Memoria\n");
    }
    else
    {
        log_info(logger_kernel, "Conexion con Memoria exitosa");
    }

    // Empieza el handshake

    size_t bytes;

    int32_t handshake = 1;
    int32_t result;
     uint32_t resultOk=0;
    bytes = send(conexion_memoria, &handshake, sizeof(int32_t), 0);
    bytes = recv(conexion_memoria, &result, sizeof(int32_t), MSG_WAITALL);

    if (result == resultOk)
    {
        // Handshake OK
        printf("Conexion con MEMORIA exitosa");
    }
    else
    {
        printf("ERROR: Handshake con MEMORIA fallido");
    }
    // Fin de handshake
    paquete(conexion_memoria);

    conexiones++;

    terminar_programa(conexion_memoria, logger, config_kernel);
}`
`int atenderKernel() {

        logger = log_create("logServerMemoria.log", "SV_MEMORIA", 1, LOG_LEVEL_DEBUG);

        char *puerto = config_get_string_value(config_memoria, "PUERTO_ESCUCHA");

	    int server_memoria = iniciar_servidor(puerto); 
	    log_info(logger, "Servidor listo para recibir al cliente");
	    int cliente_memoria = esperar_cliente(server_memoria);

		
	    t_list* lista;
	    while (1) {
		    int cod_op = recibir_operacion(cliente_memoria);
		    switch (cod_op) {
		    case MENSAJE:
			    recibir_mensaje(cliente_memoria);
			    break;
		    case PAQUETE:
			    lista = recibir_paquete(cliente_memoria);
			    log_info(logger, "Me llegaron los siguientes valores:\n");
			    break;
		    case -1:
			    log_error(logger, "el cliente se desconecto. Terminando servidor");
			    return EXIT_FAILURE;
		    default:
			    log_warning(logger,"Operacion desconocida. No quieras meter la pata");
			    break;
		        }
	}
	return EXIT_SUCCESS;
    }`


Ahi pusimos el handshake de la manera mas legible y lo mas acorde al docs de utnso pero el mensaje es el mismo en el servidor

consola memoria:
INFO] 00:56:51:194 SV_MEMORIA/(28181:28185): Servidor listo para recibir al cliente
[INFO] 00:56:51:207 SV_MEMORIA/(28181:28186): Servidor listo para recibir al cliente
[INFO] 00:56:51:212 SV_MEMORIA/(28181:28187): Servidor listo para recibir al cliente
[WARNING] 00:57:12:057 SV_MEMORIA/(28181:28185): Operacion desconocida. No quieras meter la pata
[WARNING] 00:57:12:057 SV_MEMORIA/(28181:28185): Operacion desconocida. No quieras meter la pata
[WARNING] 00:57:12:058 SV_MEMORIA/(28181:28185): Operacion desconocida. No quieras meter la pata
[WARNING] 00:57:12:060 SV_MEMORIA/(28181:28185): Operacion desconocida. No quieras meter la pata

consola kernel: 
[INFO] 00:57:12:054 KERNEL/(28316:28329): Valor leido de la config: Soy Kernel
[INFO] 00:57:12:058 KERNEL/(28316:28329): Conexion con Memoria exitosa

**Comment by Tomas-Perez** [comment]
Buenass, estuvimos depurando el código y creo que el error viene de la función `recibir_operacion()` que es la que nos devuelve el valor a usar en el switch de `atenderKernel()` que siempre termina cayendo en el case default.
Probando la función `recibir_operacion()` y viendo que es lo que devuelve, notamos que devuelve valores triviales. Dejo la función y lo que devuelve la consola.

```
int recibir_operacion(int socket_cliente) {
    int cod_op;
    int bytes_recibidos = 0;
    
    while (bytes_recibidos < sizeof(int)) {
        int bytes_actual = recv(socket_cliente, ((char*)&cod_op) + bytes_recibidos, sizeof(int) - bytes_recibidos, 0);
        if (bytes_actual <= 0) {
            if (bytes_actual == 0) {
                fprintf(stderr, "El cliente se desconectó inesperadamente\n");
            } else {
                perror("Error al recibir código de operación");
            }
            close(socket_cliente);
            return -1;
        }
        bytes_recibidos += bytes_actual;
    }

    printf("Código de operación recibido: %d\n", cod_op);
    return cod_op;
}
```
Vuelvo a dejar la funcion `atenderKernel()` donde estuve haciendo algunas pruebas:

```
int atenderKernel()
{

	logger = log_create("logServerMemoria.log", "SV_MEMORIA", 1, LOG_LEVEL_DEBUG);

	char *puerto = config_get_string_value(config_memoria, "PUERTO_ESCUCHA");

	int server_memoria = iniciar_servidor(puerto);
	log_info(logger, "Servidor listo para recibir al cliente");
	int cliente_memoria = esperar_cliente(server_memoria);

	// t_list* lista;
	while (cliente_memoria)
	{
		// int cod_op = recibir_operacion(cliente_memoria); // CUANDO FUNCIONE DESCOMENTAR
		switch (0)
		{ // aca deberia ir cod_op pero devuelve valores random, puse 0 para probar si llega la "clave" del kernel.config
		case MENSAJE:
			recibir_mensaje(cliente_memoria);
			break;
		case PAQUETE:
			// lista = recibir_paquete(cliente_memoria);
			log_info(logger, "Me llegaron los siguientes valores:\n");
			break;
		case -1:
			log_error(logger, "el cliente se desconecto. Terminando servidor");
			return EXIT_FAILURE;
		default:
			log_warning(logger, "Operacion desconocida. No quieras meter la pata");
			break;
		}
	}
	return EXIT_SUCCESS;
}
```

CONSOLA MEMORIA (PROBANDO VALORES DE RECIBIR_OPERACION():

codigo de operacion 11[WARNING] 13:08:46:543 SV_MEMORIA/(8638:8653): Operacion desconocida. No quieras meter la pata
codigo de operacion 544829267[WARNING] 13:08:46:543 SV_MEMORIA/(8638:8653): Operacion desconocida. No quieras meter la pata
codigo de operacion 1852990795[WARNING] 13:08:46:543 SV_MEMORIA/(8638:8653): Operacion desconocida. No quieras meter la pata
codigo de operacion 16804965[WARNING] 13:08:46:550 SV_MEMORIA/(8638:8653): Operacion desconocida. No quieras meter la pata

CONSOLA MEMORIA (HABIENDO HECHO LA MODIFICACION QUE MOSTRE ARRIBA PARA QUE MANDE MSJ):
INFO] 13:30:09:303 SV_MEMORIA/(12315:12327): Servidor listo para recibir al cliente
[INFO] 13:30:19:665 SV_MEMORIA/(12315:12327): Me llego el mensaje: Soy Kernel

CONSOLA KERNEL:
[INFO] 13:30:19:663 KERNEL/(12437:12442): Valor leido de la config: Soy Kernel
[INFO] 13:30:19:670 KERNEL/(12437:12442): Conexion con Memoria exitosa

**Comment by RaniAgus** [comment]
¡Buenas! Repito una vez más las dos preguntas que hice antes:

1) En `conectarMemoria()` me hace ruido que estén llamando a `enviar_mensaje()` antes de realizar el handshake, en lugar de después.

2) ¿En atenderKernel() se está llamando a alguna función que atienda el handshake? Desde acá no veo que ninguna función lo haga.

También agrego una pregunta más:

3) Noto que "11" coincide con la longitud del string "Soy Kernel" incluyendo el '\0' del final. ¿Es posible que estén enviando el mensaje sin el opcode delante?

Saludos

**Comment by RaniAgus** [comment]
¡Buenas @Sebastian-Faingerch @Tomas-Perez! ¿Pudieron revisar lo que les comentaba? Saludos

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, ante cualquier consulta pueden reabrirlo o abrir uno nuevo. Saludos
