### ISSUE TITLE
Duda sobre IOs-KERNEL

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3683]
Buenas, 
Teníamos una duda con respecto a la cola de procesos bloqueados, nosotros pensamos crear una lista global de bloqueados, en la cual cada vez que se conecta interfaz se crea una elemento del siguiente tipo:

    typedef struct 
    {
        char* nombre;
        int tipo_interfaz;
        int fd_interfaz;
        t_queue* cola_procesos_blocked;
    } t_list_io;

La cola de cada interfaz en principio estaría vacía, nosotros tenemos un hilo que se encarga de mandar el proceso a execute, quedarse esperando el contexto del mismo con el motivo de desalojo para decidir a donde mandarlo (exit, blocked). El tema es que, por ejemplo, si recibimos un "IO_GEN_SLEEP int1 10", con el int1 podría acceder a la lista y agregarlo a la cola del t_list_io correspondiente (siempre que se cumpla que existe la IO y admite la operacion, este chequeo lo hacemos en el mismo hilo que recibe el contexto con el motivo). Cómo se podría mandar esa información al otro hilo que queremos crear, que se encargaría de manejar la cola de bloqueados para mandar las solicitudes a las IO, porque lo único que esta agregado ahí es el PCB que solicito la operacion, y dentro de la estructura del PCB no hay nada del tiempo ni de los parametros de las operaciones de todas las IO. 
Tampoco sabemos como manejar el hilo que maneja la cola de bloqueados, porque, por ejemplo, la cola de execute es bastante simple ya que es un while(1) que se le avisa mediante un semaforo que ingreso un proceso a su cola, este procede a hacerle pop, mandarlo a la cpu, esperar a recibir el contexto actualizado y asi sucesivamente.
El problema con el hilo que maneja los bloqueados es que, no esta manejando una cola, sino una lista de colas. No sabemos con que criterio manejarla, que sucedería si, por ejemplo, hay dos interfaces [int1,int2] y lo manejamos por FIFO, hasta que la cola de int1 no se libere no pasamos a int2, si no nos paran de llegar procesos a la cola de la int1 nunca podremos pasar a la siguiente. Disculpas si las preguntas no se entienden, estamos muy perdidos en como manejar esta parte.

PD: También consideramos conveniente aclarar que en Kernel se crea un hilo por cada IO conectada pero pensamos que ahí dentro no puede haber mucho más que un recv que nos de el ok cuando termine de ejecutar la solicitud pedida.
PD2: Para el manejo de la lista dd colas, se nos ocurre utiliza un while 1 bloqueado por algun tipo de semaforo que nos indique si hay algun proceso en blocked, eso si tendría que recorrer toda la lista uno por uno a ver a que interfaz se le solicitó algo, si hay 10 interfacez conectadas por ejemplo.

**Comment by iago64** [comment]
Buenas! Cómo va?

Por lo que planteas tienen un lindo productor-consumidor para la planificación de corto plazo y la duda viene dada por el hecho de tener 1 hilo para todas las interfaces, ¿Estoy en lo cierto? Si estoy en lo cierto y sin ver el código te pregunto 
¿Qué tanto se les complica por ejemplo que el hilo que tiene el `recv()` del IO, ademas de eso, trabaje sobre la cola de bloqueados de esa IO? 
Lo pienso desde el punto en el que uds despiertan el hilo y este mientras tenga cosas en la queue de bloqueados de esa interfaz manda, se queda esperando la respuesta, mueve el proceso a ready y vuelve a empezar.

Saludos.-

**Comment by rood8592** [comment]
Nos parece muy buena la idea de que cada hilo de IO maneje su propia cola de bloqueados pero nos surgiria un conflicto con la forma en la que manejamos el detener la planificación. Mando una porción del codigo de Planificador de largo plazo:

    void atender_estados_new(){

    
    while(1){

        sem_wait(&proceso_en_cola_new);
        if(!planificacion_iniciada){
            break;
        }
        sem_wait(&grado_de_multiprogramacion);
        t_pcb* pcb_auxiliar = squeue_pop(lista_procesos_new);
        cambiar_a_ready(pcb_auxiliar);
        sem_post(&proceso_en_cola_ready);
        //Una vez que pasa los estados de new a ready
        log_info(logger, "PID: %d - Estado Anterior: NEW - Estado Actual: READY", pcb_auxiliar->pid);

    }
    }


    void iniciar_PLP(){
    pthread_t hilo_plp; //hilo del planificador de largo plazo, para atender estados en new
    pthread_create(&hilo_plp, NULL, (void *) atender_estados_new, NULL);
    pthread_detach(hilo_plp);
    }

La variable planificación_iniciada es modificado por el comando "detener planificacion", de manera que cuando se accióna finalizan todos los hilos y vuelven a ser creados al iniciar la planificación. No sé si podriamos hacer algo de esta indolé con los hilos de IO, los cuales son creados a demanda.  Se me ocurre que quizas podriamos guardarnos los file_descriptors de cada uno y volver a crear todos los hilos con sus fd_correspondientes, no sé si es algo posible o pensar en otra forma de encarar el tema de las colas de la IOs, o el tema del del detener la planificación.

**Comment by iago64** [comment]
Buenas!

Siento que se están comprando un temita mucho más grande de lo que parece con el detener planificación y estos hilos, ya que eventualmente lo que deberías frenar con el detener planificación es el pasaje entre las diferentes colas, no necesariamente tienen que salir a matar cuanto hilo anda dando vueltas.

Saludos.-

**Comment by mefederico** [comment]
Hola! 

Justo pasaba por acá y no pude evitar leer el codigo independientemente si van con esta solución o no, tengan mucho cuidado con salir de una región critica o en un productor consumidor de marcar algo como consumido que luego no lo consuman, se van a volver locos buscando que puede estar fallando

```C
    while(1){

        sem_wait(&proceso_en_cola_new); ----> Hacen el wait
        if(!planificacion_iniciada){
            break; -------------------> Se van sin haber sacado nada de la cola de new
        }
        sem_wait(&grado_de_multiprogramacion);
        t_pcb* pcb_auxiliar = squeue_pop(lista_procesos_new);
        cambiar_a_ready(pcb_auxiliar);
        sem_post(&proceso_en_cola_ready);
        //Una vez que pasa los estados de new a ready
        log_info(logger, "PID: %d - Estado Anterior: NEW - Estado Actual: READY", pcb_auxiliar->pid);

    }
```

**Comment by rood8592** [comment]
Hola, igualmente tomamos la recomendacion de @iago64 y quitamos esa forma de detener la planificación. Añadimos un nuevo semaforo por cada hilo que realice un pasaje de estado (inicializados en 0), por ejemplo, en vez de ese if con break, ahora hay un sem_wait(&planificación_new_iniciada) y un sem_post del mismo semaforo al final del while(1) para que no se detenga a si mismo. Lo que si me gustaría preguntarles es sobre la forma en la que hicimos el detener planificación. Basicamente tenemos, por ahora, tres semaforos que controlan que se haya iniciado la planificación (uno de new que mencioné antes, uno de ready y otro de exec), el iniciar_planificación lo que hace es hacerle post a estos tres semaforos. Luego, el detener, en un principio le habia hecho tres waits y no funcionaba del todo bien, primero porque se quedaba parada la consola hasta que se le dejará al la funcion hacer los tres waits, aparte de otras cosas como, por ejemplo, que no se pausaba el motivo de desalojo y muchas veces incluso kernel mandaba un proceso extra a la cpu. Asumo que esto ultimo es por el orden en el que estaban los wait, seguramente el que paraba exec estaba último y era bloqueado por los dos de arriba. Para solucionar esto, se nos ocurrió crear tres hilos cuya unica función es mandarle cada wait para que lo hagan cuando puedan hacerlo y el wait que estuviera más arriba no bloqueara a los otros dos, en el momento en el que los hilos hacen el wait que les corresponde se liberan. Por ahora funciona todo bien de ésta última forma pero queríamos preguntar si esta permitido utilizar hilos para estas cosas porque entiendo que es una de las cosas que revisan en las prubeas con htop, hilos que se crean, eliminan, etc.

**Comment by rood8592** [comment]
Otra duda de implementación que tenemos esta más relacionado con lo de las diferentes colas de IOs. Nosotros pensamos en plantear que cada hilo de IO que se crea en kernel se encargue de mandar las solicitudes al IO, recibir el ok, y pasar los procesos a ready. Para las genéricas, por ejemplo, se nos ocurrió que sus colas estén conformadas por elementos del siguiente tipo:

    typedef struct
    {
    int tiempo_sleep;
    t_pcb* pcb;
    }elemento_io_generica;

De modo que cuando el hilo de esa IO acceda a la cola, lea el tiempo y el pid, se los mande a su IO correspondiente con un send, haga recv esperando el ok de la IO para proceder a hacerle pop al elemento mandando el pcb a ready y repitiendo el ciclo si tiene más elementos en la cola. Una pregunta adicional, si no quiero eliminar el pcb dentro del struct porque justamente lo quiero mandar a ready, cuando hago pop deberia hacerle free unicamente al elemento como tal, o no? Me refiero a lo siguiente:

    elemento_io_generica* auxiliar = pop(cola_io);
    push_a_ready(auxiliar->pcb);
    free(auxiliar);

**Comment by RaniAgus** [comment]
¡Buenas! Exactamente, eso lo que hace es liberar únicamente el pedacito de memoria apuntado por `auxiliar` sin importar lo que haya dentro. Entonces, si hay o no un puntero a un `pcb` que ya hayas guardado en otro lado no pasa nada, no lo va a liberar recursivamente.

De hecho, en el caso opuesto de que _sí_ quisieras liberar el `pcb`, tendrías que llamar a `free()` pasándoselo antes de liberar la propia estructura:

```c
free(auxiliar->pcb);
free(auxiliar);
```

Saludos

**Comment by RaniAgus** [comment]
¡Buenas @rood8592! ¿Quedó clara la idea? Saludos

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, ante cualquier consulta pueden reabrirlo o abrir uno nuevo. Saludos
