### ISSUE TITLE
Memoria de instrucciones

### ISSUE THREAD

**Issue by Miranda-03** [sisoputnfrba/foro#3686]
Buenas, estuve teniendo algunas dudas sobre el módulo memoria, las cuales fui solucionando con algunos issues (#3641 #3666 #3681), solo hay algo que no me cierra.

Lo que tengo entendido es que existirán dos tipos de memoria: la memoria de instrucciones y la memoria con paginación simple. Luego, si no me equivoco, la primera "memoria"  no será más que un tipo de dato (como un struct o un array) en donde guarde las instrucciones que leo del archivo, siendo así un lugar cuya única función sea devolver instrucciones que pueden afectar o no a la otra memoria.

Suponiendo que lo que dije es correcto, mi duda es: el tipo de dato de la memoria de instrucciones tiene que ser sobreescrito cada vez que un proceso se tenga que ejecutar en el CPU o tengo que guardar el conjunto de instrucciones de cada proceso que esté vivo e identificarlo con el PID.

### 📔 Cita del enunciado

>Memoria de Instrucciones
Esta parte de la memoria será la encargada de obtener de los archivos de pseudo código las
instrucciones y de devolverlas a pedido a la CPU.
Al momento de recibir la creación de un proceso, la memoria de instrucciones deberá leer el archivo
de pseudocódigo indicado y generar las estructuras que el grupo considere necesarias para poder
devolver las instrucciones de a 1 a la CPU según ésta se las solicite por medio del Program Counter.
Ante cada petición se deberá esperar un tiempo determinado a modo de retardo en la obtención de
la instrucción, y este tiempo, estará indicado en el archivo de configuración.
Esquema de memoria y Estructuras
La memoria al trabajar bajo un esquema de paginación simple estará compuesta principalmente por
2 estructuras principales las cuales son:
●
 Un espacio contiguo de memoria (representado por un void*). Este representará el espacio
de usuario de la misma, donde los procesos podrán leer y/o escribir.
●
 Las Tablas de páginas.

**Comment by RaniAgus** [comment]
¡Buenas! De la misma forma que en un sistema operativo real vos tendrías un segmento de código cargado en Memoria para cada proceso, en el TP a modo de simplificación el "código" está cargado en una estructura de datos que definan ustedes para que, luego, al momento de ejecutar la siguiente instrucción, la Memoria solo necesite PID y PC para encontrarla y cargarla en CPU en la etapa de _fetch_. Saludos

**Comment by Miranda-03** [comment]
Listo, muchas gracias. Cierro el issue
