### ISSUE TITLE
Sobre el envio de paquetes y serializacion

### ISSUE THREAD

**Issue by servasquezlizana** [sisoputnfrba/foro#3687]
Buenos dias.
En nuestro grupo se esta dando un debate con respecto a si se puede o no enviar varios paquetes seguidos. 
Leyendo el siguiente texto sacado de la [guia de sockets](https://docs.utnso.com.ar/guias/linux/sockets)

![image](https://github.com/sisoputnfrba/foro/assets/164660453/c31be78a-b281-4d4a-b555-9bdcd6658ee6)

Unos creen que no se puede enviar varios paquetes seguidos ya que no se puede garantizar el orden de llegada y que por eso debemos agregar la informacion de esos paquetes a uno solo, serializar y enviar. En cambio, otros piensan que la serializacion salvaguarda ese inconveniente, pudiendo enviar varios paquetes bajo la logica de:

enviar_informacion1:
crear paquete1, agregar "informacion1", serializar, enviar paquete1, eliminar paquete1

enviar_informacion2:
crear paquete2, agregar "informacion2", serializar, enviar paquete2, eliminar paquete2

¿Se puede enviar varios paqutes seguidos bajo esa logica?¿Se debe enviar toda la informacion en un paquete?
¿Cuales de estos casos es mas conveniente aplicar, por ejemplo, si se quiere enviar informacion de una instruccion y el PCB?

Espero que se haya entendido la consulta y los ejemplos dados.

Saludos.

**Comment by FredeHG** [comment]
Hola buenas!

Si podrían también los insto a probarlo. pero lo interesante seria saber porque necesitan enviar 2 mensajes y no pueden juntarlos en uno solo. Si estas necesitando enviar 2 cosas siempre juntas algo muy cómodo es modelarlas como una sola estructura para poder hacer esto mismo

**Comment by servasquezlizana** [comment]
Vamos hacer todo via un paquete. Gracias! Saludos.

**Comment by iago64** [comment]
Buenas! Si la duda esta resuelta por favor no se olviden de cerrar el issue.
