### ISSUE TITLE
Tomar variables de tipo *void

### ISSUE THREAD

**Issue by tomassagrada** [sisoputnfrba/foro#3688]
Buenas estaba pensando en tomar las variables (excepto la instruccion) recibidas de memoria como `*void`, para así no tener tantos casos de funciones (estoy usando diccionarios con funciones que realizan las instrucciones) de esa manera puedo aplicar las instrucciones y realizar lo necesario con el resultado (en caso de ser numerico). Las instrucciones de memoria en nuestro programa llegarían como un `char*` y en cpu se separan en partes, en el caso de las instrucciones con registros serían la instrucción, el registro o valor y el otro registro o valor. Mi duda llega en la parte dentro de las funciones porque si yo utilizo la variable como `void*` por ejemplo que contenga el nombre de un registro (AX) quiero saber si yo podría usar esa variable como ese registro, osea si puedo asociar de alguna manera mi variable al valor de AX, para operar con ese valor y después si podría guardar el resultado de la operación nuevamente en el AX (del proceso). 

Contexto de registros: los registros los tomaba como un puntero a registro qué me llega en el pcb de cada proceso. (No se si esta bien esta manera).

**Comment by FredeHG** [comment]
Hola buenas!

Voy a intentar responder lo mejor que pueda, si en algo no te seguí por favor no dudes en re preguntar

> puedo asociar de alguna manera mi variable al valor de AX

Podes asociarlo de la misma forma que estas asociando instrucciones a funciones, un diccionario. Al final las funciones y las variables para C no es más que un puntero

Sobre el tipo de void*, un poco lo mismo todo es un puntero en C así que podrías pasar de char* a void* a int* a lo_que_sea*

Ahora sobre manejar las instrucciones, finalmente si tienen todas las funciones en un diccionario imagino que lo que quieren lograr es hacer 
```C
funcion = dictionary_get(funciones, nombre_insctruccion);
funcion(paremetro1, parametro2);
```

Bueno una cosa que podrías hacer es crear una estructura que agrupe todos los parámetros, y ya cada función saca de esa estructura los parámetros que necesita

Quedando algo así:
```C
funcion = dictionary_get(funciones, nombre_insctruccion);
funcion(paremetros);
```

Espero haberte seguido con tu duda
Saludos!

**Comment by tomassagrada** [comment]
si me sirvió, mas tarde voy a probar lo de la estructura porque creo que puede simplificar mucho, muchas gracias.
