### ISSUE TITLE
RR

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#3689]
Hola buenas tengo una duda con el Round Robin, yo tengo una funcion que te obtiene el sigueinte de la lista de ready y lo manda a ejecutar a cpu, hace un sleep del quantum y despues envia la interrupcion. Mi duda es que pasaria en el caso que el proceso termine antes que el quantum: 
1) Tenemos que considerar ese caso? porque se estaria esperando de mas y la cpu estaria sin ejecutar nada un tiempo. En caso que no haya que considerarlo yo tenia pensado que una vez que termine de ejecutar el sleep, se fije si el proceso que se envio sigue en cpu y asi decidir si tiene que enviar la interrupcion o no. Con esto estaria bien en este caso?
2) Por otro lado, caso que tengamos que considerarlo, como podriamos frenar el usleep? Lei en otro issue que hacian un hilo aparte para el quantum, esa seria la unica alternativa?

**Comment by LeandroCarbajales** [comment]
Buenas!
1- Sí, tienen que considerar ese caso, de hecho es un caso muy normal y les da el pié para implementar el VRR.
2- No es la única alternativa pero tener un hilo aparte es lo más ordenado si el hilo que mandó a ejecutar luego queda bloqueado en el recv() esperando a que cpu devuelva. El hilo en sí se puede finalizar preventivamente con `pthread_cancel`, otra opción es, como bien mencionás en el punto 1, que ese mismo hilo haga chequeos extra (por ejemplo, que el proceso aun no dejo la cpu) antes de enviar el mensaje de interrupt.

Te aclara las dudas?
Saludos!
    Lean

**Comment by JoaquinCoaricona** [comment]
Buenas, si muchas gracias.
