### ISSUE TITLE
Valor de los registros en las pruebas

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3690]
Buenas! entiendo que las pruebas que subieron son como de juguete para que vayamos probando, pero no haria falta en los logs minimos algo que te diga los valores de los registros porque si no como se dan cuenta de si se hicieron bien los sets, sums etc ?(aparte de usando jnz)

**Comment by iago64** [comment]
Buenas! Cómo va?

Si quieren agregarse algunos logs no hay problema, para las pruebas finales los valores de los registros si los asignan mal lo más probable es que terminen pegándose una vuelta desde Campus hasta Medrano con las direcciones de memoria 😉 

Saludos.-
