### ISSUE TITLE
Sockets

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#3691]
Buenas una pregunta, si yo tengo dos hilos y uno de los hilos esta escuchando un socket con el recv, desde el otro hilo se podria enviar algo a traves del mismo socket? O tendria que hacer un mutex entre ambos hilos? Desde ya muchas gracias

**Comment by FredeHG** [comment]
Hola buenas!

La pregunta en este caso es, 
Por que se quieren complicar tanto la comunicación? o que necesidad tienen que hacer eso les resolvería esa necesidad?

**Comment by FredeHG** [comment]
Como poder vas a poder si, pero el planificador de corto plazo no va a enviar un proceso por dispatch si ya hay un proceso en CPU ejecutando, por lo tanto recibir el proceso de CPU y enviar al CPU un pcb nuevo es algo que se puede hacer monohilo y no necesariamente con multiples hilos

**Comment by FredeHG** [comment]
El problema que podrías tener con concurrencia es que por algún motivo de race condition envíes un nuevo proceso a la CPU cuando todavía esta corriendo uno actualmente, siendo que la CPU no puede correr más de un proceso o cualquier otro problema derivado de tener 2 threads haciendo algo que podría considerarse monohilo

La implementación particular que hagan no es un tema a evaluar concretamente, podrían hacer un thread por línea de código si así quisieran. (no lo hagan)
