### ISSUE TITLE
Consulta implementacion Estado BLOCKED

### ISSUE THREAD

**Issue by LainoRamiro** [sisoputnfrba/foro#3693]
Hola! Quería consultar por el tema de la implementación de las colas de bloqueo.
Según el enunciado, deben existir múltiples colas de bloqueo por cada interfaz IO o recurso. 
Originalmente pensábamos hacerlo con una lista que contenga como elementos las diferentes colas de cada interfaz o recurso. Después revisando las commons, se nos ocurrió usar un diccionario, en el cual la clave seria el nombre de la interfaz o recurso, y el valor, las diferentes colas.
Tenemos el debate de si es posible utilizar un diccionario para implementar el estado de BLOCKED que tiene múltiples colas, y si es posible, si es mas ventajoso o mejor que la lista con sub-colas.
Gracias y saludos!

PD: no se si este Issue corresponde a preguntas de enunciado o de programación en C.

**Comment by iago64** [comment]
Buenas! Cómo va?

El tema de las estructuras depende muchísimo de lo que a uds les resulte mas cómodo de utilizar, no vamos a decirles que esta mal o que si o si tienen que ser `t_queue`, dicho lo anterior, si con un diccionario les resulta mas cómodo porque tienen el string que les identifica la queue y despues de ahi desprenden la lista de bloqueados para ese recurso / interfaz, denle para adelante.

Saludos.-

**Comment by LainoRamiro** [comment]
Si, más que nada porque para armar la lista con sub-colas, habíamos pensado que la lista debería tener una estructura que contenga el puntero a la cola y una identificación de la interfaz, ya que la lista no va a estar en orden y las colas de bloqueo de interfaces pueden crearse, modificarse y eliminarse todo el tiempo, por lo que habría que ver también como hacer la búsqueda para obtener la cola, por ejemplo cuando nos llegue la petición de parte de la CPU para encolar la PCB por IO o recurso, o para pasar de estados blocked a ready cuando ya se ejecuto la IO.

Desde ya muchas gracias por responder, vamos a tener en cuenta lo que resulte nos resulte mas cómodo.
Saludos! :)

**Comment by iago64** [comment]
Buenas!

Si la duda esta resuetla no se olviden de cerrar el issue.

Saludos.-
