### ISSUE TITLE
Inconveniente con Conexion

### ISSUE THREAD

**Issue by AgustinaGuitman** [sisoputnfrba/foro#3694]
Buenas, estamos teniendo inconvenientes a la hora de conectar el servidor de Memoria, con Kernel, CPU dispatch y CPU interrupt. A nosotros nos funcionaba pero al reestructurar el trabajo practico para que quede mas legible y comprensible no entendemos el porque nos devuelve estos errores que no coinciden con los que veniamos trabajando.

### 📝 Código relevante
```c
int main(int argc, char *argv[1])
{

	config_memoria = iniciar_config("memoria.config");
	logger_memoria = iniciar_logger("memoria.log", "MEMORIA");

	conexiones = 0;

	// Creacion de hilos

	pthread_t t1, t2, t3, t4;

	pthread_create(&t1, NULL, (void *)atenderKernel, NULL);
	pthread_create(&t2, NULL, (void*) atenderCpu, NULL);
	pthread_create(&t3, NULL, (void*) atenderInterfaz, NULL);
	//pthread_create(&t4, NULL, (void*) leer_consola, NULL);

	pthread_join(t3, NULL);

	log_destroy(logger_memoria);
	config_destroy(config_memoria);

	liberar_conexion(atenderKernel);
	liberar_conexion(atenderCpu);
	liberar_conexion(atenderInterfaz);

	return 0;
}
```
la función que llama el hilo
```c
int atenderInterfaz()
{

	logger = log_create("logServerMemoria.log", "SV_MEMORIA", 1, LOG_LEVEL_DEBUG);

	char *puerto = config_get_string_value(config_memoria, "PUERTO_ESCUCHA");

	int server_memoria = iniciar_servidor(puerto);
	log_info(logger, "Servidor listo para recibir al cliente");
	int cliente_memoria = esperar_cliente(server_memoria);

	t_list *lista;
	while (1)
	{
		int cod_op = recibir_operacion(cliente_memoria);
		switch (cod_op)
		{
		case MENSAJE:
			recibir_mensaje(cliente_memoria);
			break;
		case PAQUETE:
			lista = recibir_paquete(cliente_memoria);
			log_info(logger, "Me llegaron los siguientes valores:\n");
			break;
		case -1:
			log_error(logger, "el cliente se desconecto. Terminando servidor");
			return EXIT_FAILURE;
		default:
			log_warning(logger, "Operacion desconocida. No quieras meter la pata");
			break;
		}
	}
	return EXIT_SUCCESS;
}
```
acá esta nuestra iniciar servidor, no creo que el problema esté acá porque cuando lo usamos en otros módulos anda bien pero para dar un mejor contexto lo mando.

```c
int iniciar_servidor(char* puerto) {
    struct addrinfo hints, *server_info;

    memset(&hints, 0, sizeof(hints));
    hints.ai_family = AF_INET;
    hints.ai_socktype = SOCK_STREAM;
    hints.ai_flags = AI_PASSIVE;

    if (getaddrinfo(NULL, puerto, &hints, &server_info) != 0) {
        perror("Error en getaddrinfo");
        return -1;
    }

    int socket_servidor = socket(server_info->ai_family, server_info->ai_socktype, server_info->ai_protocol);
    if (socket_servidor == -1) {
        perror("Error al crear socket del servidor");
        freeaddrinfo(server_info);
        return -1;
    }

    if (bind(socket_servidor, server_info->ai_addr, server_info->ai_addrlen) == -1) {
        perror("Error en bind");
        close(socket_servidor);
        freeaddrinfo(server_info);
        return -1;
    }

    if (listen(socket_servidor, SOMAXCONN) == -1) {
        perror("Error en listen");
        close(socket_servidor);
        freeaddrinfo(server_info);
        return -1;
    }

    freeaddrinfo(server_info);
    return socket_servidor;
}
```
### 🐛 Cómo reproducir el error
Cuando ejecutamos memoria ocurre este error.

### 💻 Logs
```
Error en bind: Address already in use
Error en bind: Address already in use
[INFO] 12:01:49:860 SV_MEMORIA/(11364:11392): Servidor listo para recibir al cliente
[INFO] 12:01:49:861 SV_MEMORIA/(11364:11393): Servidor listo para recibir al cliente
Error al aceptar conexión del cliente: Bad file descriptor
Error al recibir código de operación: Bad file descriptor
[ERROR] 12:01:49:872 SV_MEMORIA/(11364:11393): el cliente se desconecto. Terminando servidor
[INFO] 12:01:49:862 SV_MEMORIA/(11364:11394): Servidor listo para recibir al cliente
Error al aceptar conexión del cliente: Bad file descriptor
Error al recibir código de operación: Bad file descriptor
[ERROR] 12:01:49:877 SV_MEMORIA/(11364:11394): el cliente se desconecto. Terminando servidor
[1] + Done                       "/usr/bin/gdb" --interpreter=mi --tty=${DbgTerm} 0<"/tmp/Microsoft-MIEngine-In-bqoh5vae.rro" 1>"/tmp/Microsoft-MIEngine-Out-hfzevmvn.mt3"
```

**Comment by RaniAgus** [comment]
¡Buenas! Si usan el [debugger](https://docs.utnso.com.ar/guias/herramientas/debugger) van a ver que la variable `server_memoria` les retorna `-1` porque tienen este error:

```
Error en bind: Address already in use
```

Quizás convendría cambiar la estrategia de manejo de errores en `iniciar_servidor()`: en caso de no poder iniciar un servidor probablemente lo más apropiado sea directamente hacer un `exit()`, en lugar de retornar y seguir ejecutando cosas con un file descriptor inválido:

```
Error al aceptar conexión del cliente: Bad file descriptor
Error al recibir código de operación: Bad file descriptor
```

Dicho esto, el error en `bind()` se debe a que, una vez finaliza un proceso (o se llama a `close()`), el sistema operativo tarda unos 30 segundos en liberar el socket como medida de seguridad. Pueden leer más al respecto acá: https://github.com/sisoputnfrba/foro/issues/1624#issuecomment-611745367

Saludos

**Comment by AgustinaGuitman** [comment]
Hola, muchas gracias por tu respuesta. Lamentablemente sigo media mareada porque cuando llamamos a liberar_conexion(); desde el main, hacemos un close(socket_cliente);. Si el sistema operativo tarda 30 segundos en liberar el socket, nos convendría hacer 3 sockets distintos para que así la memoria pueda atender a Kernel, CPU interrupt y CPU dispatch o seguiríamos teniendo problemas porque el puerto sigue siendo el mismo y no puede atender a los 3 a la vez?

**Comment by iago64** [comment]
Buenas!

El problema no es que el socket quede bindeado un rato al proceso por mas que el proceso haya muerto, si no que el problema esta en que uds continuan ejecutando a pesar de que no pudieron hacer algo fundamental para su proceso que es levantar el servidor.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Sobre la duda acerca de los múltiples sockets, cito la sección de [accept y connect](https://docs.utnso.com.ar/guias/linux/sockets#accept-y-connect) de la guía de sockets:

> Una vez que el cliente fue aceptado, `accept()` retorna un **nuevo** socket (file descriptor) que representa la conexión BIDIRECCIONAL entre ambos procesos.
> Esto quiere decir nuestro `fd_escucha` no va a ser el que participe de dicha comunicación, solamente tiene la responsabilidad de quedarse escuchando nuevas conexiones y aceptarlas.

Saludos

**Comment by AgustinaGuitman** [comment]
@RaniAgus Muchas gracias, me quedó muy claro.
Saludos
