### ISSUE TITLE
Falla con getline a la hora de leer un stream enviado por socket.

### ISSUE THREAD

**Issue by KevinQ73** [sisoputnfrba/foro#3695]
Primero que nada, buenos días.

Tengo un problema con `getline` que lo quiero usar a la hora de que Kernel solicite crear un proceso y le mande a memoria tanto el PCB del nuevo proceso y el archivo pseudocodigo. La idea que teníamos era, desde kernel, serializar el PCB y enviar el stream del archivo todo junto en un paquete a memoria donde este lo deserializa al PCB y luego con getline obtenemos las instrucciones para luego almacenarlo en un t_list que después se lo enviaría a CPU. 

El problema está a la hora de que entra al getline, tira segmentation fault y cuando revisamos al stream `pseudocodigo` este da `cannot access memory` y tira el segmentation fault. El PCB se deserializa correctamente, y al revisar el `memory.bin` de lo enviado, se ve en el decoded text el texto del archivo, así que supongo que el error estaría en como manejamos el stream una vez llegado a memoria, pero no entendemos en donde estaría la falla, espero puedan darnos una mano. Muchas gracias

#### LADO KERNEL

```
void* peticion_crear_proceso(){

    t_pcb* pcb = create_pcb(15);// EL PID POR AHORA ES HARDCODEADO
    log_info(kernel_log,"Se crea el proceso %i en NEW", pcb->pid);

    void* pcb_a_enviar;
    int tamanio_stream;

    pcb_a_enviar = serializar_pcb(pcb, &tamanio_stream);
 
    t_paquete* paquete_proceso = crear_paquete(CREAR_PROCESO);

    agregar_a_paquete(paquete_proceso, pcb_a_enviar, sizeof(t_pcb));

    FILE *archivo_abierto = fopen("./files/INSTRUCCION", "rb");
    if (archivo_abierto == NULL) {
        perror("Error al intentar abrir el archivo");
        exit(EXIT_FAILURE);
    }

    int tamanio = tamanio_archivo(archivo_abierto);

    char *buffer_file = (char *)malloc(tamanio);
    if (buffer_file == NULL) {
        perror("Error de asignación de memoria");
        fclose(archivo_abierto);
        exit(EXIT_FAILURE);
    }

    int bytes_leidos = fread(buffer_file, 1, tamanio, archivo_abierto);
    if (bytes_leidos != tamanio) {
        perror("Error al leer el archivo");
        fclose(archivo_abierto);
        free(buffer_file);
        exit(EXIT_FAILURE);
    } else {
        agregar_a_paquete(paquete_proceso, buffer_file, bytes_leidos);
    }
    
    enviar_paquete(paquete_proceso, socket_memoria);
    log_debug(kernel_log, "SE ENVIO PAQUETE");
    
    int resultEnvioPaquete;
    recv(socket_memoria, &resultEnvioPaquete, sizeof(int), MSG_WAITALL);
    
    if(resultEnvioPaquete == 10){
        log_debug(kernel_log, "PROCESO CREADO EXITOSAMENTE");
    } else {
        log_warning(kernel_log, "FALLO");
    }

    fclose(archivo_abierto);
    free(pcb);
    eliminar_paquete(paquete_proceso);
    return EXIT_SUCCESS;
}
```

#### LADO MEMORIA

```
case CREAR_PROCESO:
        int size;
	int desplazamiento = 0;
	void * buffer;
	t_list* instrucciones = list_create();
	int tamanio;
        
        buffer = recibir_buffer(&size, socket_kernel);
	    
	memcpy(&tamanio, buffer + desplazamiento, sizeof(int));
	desplazamiento+=sizeof(int);
	t_pcb* pcb = malloc(tamanio);

	memcpy(pcb, buffer+desplazamiento, tamanio);
        pcb = deserializar_pcb(buffer+desplazamiento, pcb);
	desplazamiento+=tamanio;

        memcpy(&tamanio, buffer + desplazamiento, sizeof(int));
	desplazamiento+=sizeof(int);
	FILE* pseudocodigo = (char*)malloc(tamanio);

        memcpy(pseudocodigo, buffer+desplazamiento, tamanio);
        leer_pseudocodigo(instrucciones, tamanio, pseudocodigo);
	desplazamiento+=tamanio;
            
        log_info(memoria_log, "PID del proceso: %i", pcb->pid);

	free(buffer);
        send(socket_kernel, &operationOK, sizeof(int), NULL);
        break;

char** parsear_instruccion(char* instruccion){

	char** instruccion_parseada = string_split(instruccion, " ");

	return instruccion_parseada;
}

void leer_pseudocodigo(t_list* lista_instrucciones, int tamanio, FILE* pseudocodigo){

	char* instruccion = NULL;
	size_t len = 0;

	while ((getline(&instruccion, &len, pseudocodigo)) != -1){              <<---- Acá tira segmentation fault
		
		int largo = strlen(instruccion);
		if(instruccion[largo - 1] == '\n') 
		{
			instruccion[largo - 1] = '\0';
		}

		log_debug(memoria_log, "Se leyó la siguiente instrucción: %s", instruccion);

		char** instruccion_parseada = parsear_instruccion(instruccion);

		list_add(lista_instrucciones, instruccion_parseada);
	}
	free(instruccion);
}
```

### 💻 Logs

Así se ve el `pseudocodigo` una vez recibido.

![Screenshot 2024-05-09 113352](https://github.com/sisoputnfrba/foro/assets/82183566/27a4e365-8f5b-4e74-bc75-17ee9d431ae3)

Así se ve en `memory.bin`.

![Screenshot 2024-05-09 114609](https://github.com/sisoputnfrba/foro/assets/82183566/4f3249ba-42ca-407b-a71a-8ea2493808e1)

**Comment by mefederico** [comment]
Hola buenas! 

Capaz no te responda la duda puntual que tengas ahora pero la idea es que kernel le pase a memoria solamente el path del archivo y ustedes en memoria con ese path encuentren el archivo de instrucciones que va a estar en `PATH_INSTRUCCIONES` que es una variable del config file de memoria

Ustedes pueden definir el PATH_INSTRUCCIONES donde quieran, pero es memoria quien abre el archivo y no kernel

Espero te sirva la respuesta
Saludos!

**Comment by RaniAgus** [comment]
¡Buenas! Respondiendo a la pregunta puntual, veo un problema bastante grave acá:

```c
FILE* pseudocodigo = (char*)malloc(tamanio);

memcpy(pseudocodigo, buffer+desplazamiento, tamanio);
leer_pseudocodigo(instrucciones, tamanio, pseudocodigo);
desplazamiento+=tamanio;
```

Primero porque lo que están recibiendo por sockets no es un `FILE*`, sino que lo que reciben es un array de `char`s con el _contenido_ del archivo. De hecho, no podrían recibir un `FILE*` plano y hacer algo útil con eso, ya que es solo una referencia a un archivo abierto por otro proceso (que incluso podría estar en otra máquina).

En definitiva, el contenido al que apunta la variable `pseudocodigo` es:

```c
char* pseudocodigo = malloc(tamanio);
```

Entonces, de acá en adelante podrán notar que si intentan pasarle un string a `getline()` _cosas raras_ pueden pasar. 😅 

De todas formas, como bien dijo Fede, lo que dice el enunciado es que deben pasar únicamente la ruta hacia el archivo, no su contenido.

Saludos

**Comment by KevinQ73** [comment]
Hola! Después de leer sus respuestas reenfoque la implementación según la aclaración que hicieron sobre lo que pide el enunciado y salió con fritas. 

Agradezco mucho su aporte, que tengan buen día.

**Comment by FredeHG** [comment]
Genial! 

Si la duda está resuelta cerremos el issue

Saludos!
