### ISSUE TITLE
Duda sobre WAIT

### ISSUE THREAD

**Issue by ManuRodri01** [sisoputnfrba/foro#3697]
Buenas, tengo un par de dudas respecto a la instrucción WAIT.
La primera es, en caso de hacer el wait y que el proceso no deba bloquearse; debe ir a ready o ser mandado de vuelta al procesador (como sucede con signal).
La segunda es, al finalizar un proceso que se encuentra bloqueado por un recurso hay que hacerle un ++ al valor del recurso, como dice en [#3607](https://github.com/sisoputnfrba/foro/issues/3607). Si finalizo un proceso que no esta bloqueado, pero que tomo una instancia de algún recurso y no la devolvió aun (no hizo un signal); debo devolverla al momento de finalizarlo, no?

Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Si al hacer WAIT no se tienen que bloquear vuelve a EXEC.

2.- Si, al finalizar un proceso siempre siempre siempre tiene que devolver los recursos que tomó, independientemente de si esta en ready, exec o block.

Saludos.-

**Comment by GonTurri** [comment]
Buenas, me llamó la atención esta pregunta. Entonces si hizo signal sin hacer wait y lo finalizó también hay que hacerle un correspondiente -- al recurso?  Podes aclarar todos los casos de esto? Porque en el issue viejo yo pensaba que solo era si estaba bloqueado y el enunciado no menciona nada al respecto

**Comment by iago64** [comment]
Buenas @GonTurri 

Si el proceso al finalizar **no esta reteniendo instancias** no tenes que hacer nada, es decir, que si solo hizo signal no hay ningun recurso _asignado_ a ese proceso.

Saludos.-

**Comment by GonTurri** [comment]
Disculpa que te repregunte pero asumi que no entiendo nada de sistemas operativos. 
Si retengo multiples instancias de un recurso las tengo que liberar todas me imagino?
y se liberan solo si lo mato como si fuese SIGKILL? o tambien cuando el proceso termina por su cuenta le libero los recursos?

**Comment by iago64** [comment]
@GonTurri Cómo va?
Si, se puede pasar del "máximo" porque lo que tenes en la config es el valor inicial.
P.D: Ojo con la premisa de "No entiendo nada porque en 1 semana es el parcial y justo entra esta parte de procesos y recursos"

@ManuRodri01 
Es una buena pregunta, porque no está aclarado en el enunciado, pero justamente no lo aclaramos porque el comportamiento no está del todo definido incluso en la biblioteca `semaphore.h` que es la que tomamos de ejemplo, por lo que para simplificar la implementación aun alejándonos de la teoría, vamos a considerar para el tp que un proceso libera el recurso en el momento en el que hace SIGNAL al recurso el mismo proceso.

Saludos.-

**Comment by ManuRodri01** [comment]
Oka, muchas gracias. Cierro el issue
