### ISSUE TITLE
Consulta espera activa

### ISSUE THREAD

**Issue by AgostinoG** [sisoputnfrba/foro#3698]
Buenass, una consulta rápida, este codigo sufre de espera activa?

![image](https://github.com/sisoputnfrba/foro/assets/164388209/bde91bb6-3cd6-467c-aba0-8f42acd3f7d8)

**Comment by Champa123** [comment]
No veo ese problema, es decir eventualmente el while dejara de dar por true la condicion y esa porcion del codigo deja de ejecutarse.  Lo que ejecutaria hasta llenar la cola de ready, luego saldria de la condicion del while, siguiendo con el codigo.

Lo que si veo es que no checkeas si la queue de new tiene elementos, estarias intentando hacer un pop de una queue vacia si tenes lugar en la de ready y vacia la new (Desconozco como interpreta eso la commons pero huele a Segmentation Fault)

**Comment by iago64** [comment]
Buenas! Cómo va?

Gracias @Champa123 por las observaciones, efectivamente si haces pop a una queue vacía va a explotar feo.
De todas formas, si esa funcion `newaReadiFIFO()` no tiene ningun semáforo puede que tengas algun temita de sincro en la queue de ready.

Por último y no menos importante, ni los ayudantes ni los docentes somos compiladores humanos de C, la mejor respuesta para ver si algo tiene espera activa es correrlo y ver si empezas a consumirte toda la cpu.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @AgostinoG! ¿Te sirvió la respuesta de Dami? Saludos

**Comment by AgostinoG** [comment]
Buenas, sisi me sirvió. Muchas gracias! Cierro el issue!
