### ISSUE TITLE
Tiempo en Logs

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#3699]
Hola buenas. Tengo una duda con el quantum en Round Robin. Yo estoy probando con un retardo en la respuesta de memoria a cpu por cada instruccion de 1 segundo. Y el quantum es de 2 segundos.  El problema es que me esta pasando esto que mando en los logs. Tengo un hilo para el usleep de quantum. El hilo compara despues del usleep si el pid que tiene es el mismo que esta en una variable global que tiene el pid en ejecucion. Esa variable global se actualiza apenas reciben un pcb por dispatch y cuando se envia uno por el planificador de corto plazo. El archivo que estoy probando tiene 4 instrucciones entonces hace un quantum, vuelve y despues vuelve a ir a cpu y justo al final del quantum llega al exit tambien y me esta pasando que se envia la interrupcion desde kernel pero cpu ya la estaba devolviendo entonces hay interrupciones que estan yendo de mas. No se de que forma podria solucionar esto. Desde ya muchas gracias

PD: Recien lo probe con varios procesos que ejecutan el mismo archivo de instrucciones. Y me pasa que todos finalizan bien, en orden, pero algunos envian esta interrupcion de mas y otros no, pero en la mayoria de los casos la interrupcion se envia, pero al devolver el pcb lo devuelven por el motivo correcto de instruccion EXIT.

### 💻 Logs
`[INFO] 02:53:12:519 kernel/(28327:28729): Envio Interupcion 0`
`[INFO] 02:53:12:520 kernel/(28327:28333): LLEGO UN PCB`
`[INFO] 02:53:12:520 kernel/(28327:28333): Motivo Recibido : INSTRUCCION EXIT`

**Comment by iago64** [comment]
Buenas!

El comportamiento que estan teniendo es el correcto. 
Si envían la interrupción y justo estan desalojando el proceso por cualquier motivo, puede ser EXIT o cualquier IO_* lo que pueden hacer ahí es marcar el flag de interrupción como que ya la atendieron y listo, ya que el motivo de desalojo no es la interrupción si no que es la instrucción.

Saludos.-

**Comment by JoaquinCoaricona** [comment]
OK muchas gracias.
