### ISSUE TITLE
Diferencia Ejecucion 

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#3700]
Hola buenas. Tengo este problema con los quantums y el Program Counter en round Robin. En este caso el retardo de devolucion de cada instrucion de memoria a cpu es 1 segundo. El quantum son 2 segundos. El quantum se calcula en un hilo, en caso que al final del usleep, el pidEjecutando (que es una variable gloabal) sea el mismo que el pid que se le paso al hilo, se envia la interrupcion. Si es distinto significa que cambio y entonces no se manda la interrupcion, se imprime que finalizo antes del quantum.

En este caso lo que hice fue: Primero pare toda la planificacion. Despues Cargue 12 procesos nuevos (tengo el grado de multiprogramacion en 10) , y despues de eso inicie la planificacion. Los 12 procesos los cree con el mismo path, osea que todos van a hacer lo mismo. El problema es que a veces cuando vuelven despues de la interrupcion por fin de quantum, algunos vuelven con el Program counter en 3 y otros en 4, solo una instruccion de diferencia. Por ejemplo en este caso todos los anteriores al PID 4 habian vuelto con PC = 3, el PID 4 tambien tuvo el PC asi, pero despues el PID 5 ya tenia el PC en 4. Despues de ahi en adelante vinieron 2 mas con el PC en 4 y despues ya empezo a variar algunos en 3 y otros en 4. Pero siempre entre esos dos valores.

Una diferencia que vi es que desde que se envio la interrupcion al PID 4 hasta que se devolvio el PCB por la interrupcion de fin de quantum, paso muy poco tiempo, pero esa diferencia en el caso del PID 5 duro mucho mas, entiendo que esto pudo haber pasado porque la interrupcion llego cuando ya habia pasado la fase de control de interrupciones en CPU. 

Mi duda es si esto es algo que puede pasar o deberian dar todos estrictamente igual al estar ejecutando las intruccciones del mismo archivo. 
Por las dudas aclaro que tengo otro problema parecido pero en otro sentido, lo mande en otro issue: #3699
Desde ya muchas gracias.

### 💻 Logs
[INFO] 03:51:45:686 kernel/(35466:35474): Cambio De Estado Proceso 4 a 2 //esto es que 4 paso a exec

[INFO] 03:51:47:697 kernel/(35466:36064): Envio Interupcion 4
[INFO] 03:51:47:698 kernel/(35466:35472): LLEGO UN PCB POR FIN DE QUANTUM
[INFO] 03:51:47:699 kernel/(35466:35472): Motivo Recibido : Fin de Quantum
[INFO] 03:51:47:699 kernel/(35466:35472): PID RECIBIDO : 4
[INFO] 03:51:47:699 kernel/(35466:35472): PC RECIBIDO : 3
[INFO] 03:51:47:699 kernel/(35466:35472): ESTADO PROCESO: 2
[INFO] 03:51:47:699 kernel/(35466:35472): REGISTRO AX : 2
[INFO] 03:51:47:699 kernel/(35466:35472): REGISTRO BX : 3
[INFO] 03:51:47:699 kernel/(35466:35472): Se agrega el proceso: 4 a ready 

[INFO] 03:51:47:700 kernel/(35466:35474): Cambio De Estado Proceso 5 a 2 //esto es que 5 paso a exec

[INFO] 03:51:49:702 kernel/(35466:36082): Envio Interupcion 5
[INFO] 03:51:50:703 kernel/(35466:35472): LLEGO UN PCB POR FIN DE QUANTUM
[INFO] 03:51:50:703 kernel/(35466:35472): Motivo Recibido : Fin de Quantum
[INFO] 03:51:50:703 kernel/(35466:35472): PID RECIBIDO : 5
[INFO] 03:51:50:703 kernel/(35466:35472): PC RECIBIDO : 4
[INFO] 03:51:50:703 kernel/(35466:35472): ESTADO PROCESO: 2
[INFO] 03:51:50:703 kernel/(35466:35472): REGISTRO AX : 5
[INFO] 03:51:50:703 kernel/(35466:35472): REGISTRO BX : 3
[INFO] 03:51:50:703 kernel/(35466:35472): Se agrega el proceso: 5 a ready

**Comment by iago64** [comment]
Buenas! Cómo va?

Al estar trabajando con tiempos y no con instrucciones es posible que tengamos casos donde el quantum llega justo una instrucción antes.
De todas formas para las pruebas vamos a calcular las cosas con suficiente margen para minimizar estas situaciones lo mas posible.

Saludos.-

**Comment by JoaquinCoaricona** [comment]
Ok. Muchas Gracias
