### ISSUE TITLE
Multiprogramacion

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#3701]
Hola buenas. Tengo una duda con la multiprogramacion. Yo tengo entendido que representa la cantidad de procesos que puedo tener en ready, mas el que se esta ejecutando. Si por ejemplo originalmente es 10, cada vez que agrego un proceso a ready le hago un wait al semaforo contador. Mi pregunta es: cuando ingresamos un valor de multiprogramacion por consola, tenemos que hacer que esos 10 que eran originalmente pasen a ser el nuevo valor ingresado? es decir que si ingresan 8, seria hacer dos waits al semaforo (sin importar si  seguia en 10 o no ). O a lo que se refieren es al valor del semaforo, que si por ejemplo estaba en 2 (mas alla que su valor original es 10) tendriamos que llevarlo al valor que ingresaron por consola. Gracias de antemano

**Comment by iago64** [comment]
Buenas! Cómo va?

Primero que nada una pequeña aclaración, el grado de multiprogramación contempla los estados READY, EXEC y BLOCK.

Dicho lo anterior, en caso de que se reduzca el grado de multiprogramación si hay mas procesos en el sistema simplemente deberían esperar a que estos terminen antes de meter mas procesos desde la cola de NEW, no es necesario que se la compliquen de mas.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @JoaquinCoaricona! ¿Te sirvió la respuesta de Dami? Saludos

**Comment by JoaquinCoaricona** [comment]
> Buenas! Cómo va?
> 
> Primero que nada una pequeña aclaración, el grado de multiprogramación contempla los estados READY, EXEC y BLOCK.
> 
> Dicho lo anterior, en caso de que se reduzca el grado de multiprogramación si hay mas procesos en el sistema simplemente deberían esperar a que estos terminen antes de meter mas procesos desde la cola de NEW, no es necesario que se la compliquen de mas.
> 
> Saludos.-

Hola buenas, me surigio una duda con esto. Yo tengo un semaforo contador que habilita la entrada de procesos a la cola ready. Cada vez que un proceso llega a la cola de exit hace un post al semaforo de multiprogramacion. Mi idea para implementar esto era que cuando el nuevo valor sea mayor al grado de multiprogramacion entonces hago la cantidad de signal que marque la diferencia entre esos dos valores. Y en caso que el nuevo valor sea menor, hacemos lo mismo pero con waits.
El caso particular que pense que podria darse es que si por ejemplo el grado de multiprogramacion es 3, y el semaforo vale 0 porque ya entraron los 3 procesos a ready, si en ese momento se baja el grado de multiprogramacion a 1, al hacer los dos waits quedaria el semaforo en -2, y a medida que los 3 procesos vayan llegando a EXIT cuando lleguen los 3 entonces quedaria establecido el nuevo valor en 1. Mi pregunta es si a esto es a lo que se referian con esta parte:

`Dicho lo anterior, en caso de que se reduzca el grado de multiprogramación si hay mas procesos en el sistema simplemente deberían esperar a que estos terminen antes de meter mas procesos desde la cola de NEW, no es necesario que se la compliquen de mas.`

Y si esta forma de pensarlo cumpliria con la consigna. Desde ya muchas gracias

**Comment by f-and** [comment]
Hola Joaquin, fijate que a lo mejor te puede generar problemas esta lógica, dependiendo de como estes planteandolo, porque si el semáforo ya esta bloqueado como en tu ejemplo, llamar a la cantidad de waits requeridos para bajar su valor al correcto seria ineficiente (por ejemplo tendrias que armar un hilo por cada wait ya que te lo trabaria).

**Comment by JoaquinCoaricona** [comment]
> Hola Joaquin, fijate que a lo mejor te puede generar problemas esta lógica, dependiendo de como estes planteandolo, porque si el semáforo ya esta bloqueado como en tu ejemplo, llamar a la cantidad de waits requeridos para bajar su valor al correcto seria ineficiente (por ejemplo tendrias que armar un hilo por cada wait ya que te lo trabaria). 

Hola buenas. En mi caso, cada vez que un proceso llega a exit se hace un post al semáforo. En caso que el semáforo este bloqueado por ejemplo en 0, al querer bajar a 1 el grado de multiprogramación le haría dos waits y el semáforo quedaría en -2. Pero cuando los 3 procesos que ya estaban en ready, lleguen a exit harían 3 post al semáforo y lo dejarían en 1 que es el nuevo grado de multiprogramación. Lo pensé asi, pero no entiendo de qué forma podría pasar lo que dijiste.

**Comment by f-and** [comment]
Osea, consideralo desde el lado practico, como harias esos waits? Considera que es una acción bloqueante, por lo que, si el semaforo como en tu ejemplo esta en 0 (bloqueado), y haces un wait, solo vas a trabar ese hilo, y no vas a poder continuar.

**Comment by JoaquinCoaricona** [comment]
> Osea, consideralo desde el lado practico, como harias esos waits? Considera que es una acción bloqueante, por lo que, si el semaforo como en tu ejemplo esta en 0 (bloqueado), y haces un wait, solo vas a trabar ese hilo, y no vas a poder continuar.

Claro, ahí entendí, pero entonces a qué proceso o forma de pensarlo se referían con lo de dejar terminar a los que están?

**Comment by JoaquinCoaricona** [comment]
Buenas, entiendo pero creo que habria otro problema. Cuando tengo el grado de multiprogramacion en 3 por ejemplo y cargo 6 procesos entrarian 3 a ready, entonces el semaforo quedaria en 0. Despues bajo el grado de multirprogramacion a 1 y cada vez que uno llega a exit tendria que hacer la validacion. Entonces cundo el primero llega a exit hace un post porque 0 < 1 e inmediatamente hace el post el otro proceso que estaba esperando entrar a ready entra y deja el semaforo de vuelta en 0, entonces cuando los otros lleguen a exit van a cumplir siempre la condicion y el grado de multiprogramacion seguiia en 3

**Comment by f-and** [comment]
Tenes razon che, pero creo que ahi ya ves la alternativa que queda, podes agarrar un contador, y cuando reducis el grado de multiprogramación, pones siguiendo el ejemplo, el contador en 2 (diferencia entre el viejo y el nuevo), e ir bajandolo a medida que vayas salteandote signals para no tener este problema.

**Comment by JoaquinCoaricona** [comment]
Sisi estaba pensandolo asi, ya lo pude arreglar. Muchas gracias
