### ISSUE TITLE
Modulo memoria

### ISSUE THREAD

**Issue by octavaliente** [sisoputnfrba/foro#3704]
Hola buenas tardes. Estamos teniendo dudas sobre el enunciado en la parte del modulo de memoria, concretamente en las lineas marcadas.
> Memoria de Instrucciones
> Esta parte de la memoria será la encargada de obtener de los archivos de pseudo código las instrucciones y de devolverlas a pedido a la CPU.
> Al momento de recibir la creación de un proceso, la memoria de instrucciones deberá leer el archivo de pseudocódigo indicado y generar las estructuras que el grupo considere necesarias para poder devolver las instrucciones de a 1 a la CPU según ésta se las solicite por medio del Program Counter.
> Ante cada petición se deberá esperar un tiempo determinado a modo de retardo en la obtención de la instrucción, y este tiempo, estará indicado en el archivo de configuración.
> Esquema de memoria y Estructuras
> La memoria al trabajar bajo un esquema de paginación simple estará compuesta principalmente por 2 estructuras principales las cuales son:
> Un espacio contiguo de memoria (representado por un void*). Este representará el espacio de usuario de la misma, donde los procesos podrán leer y/o escribir.
> Las Tablas de páginas.
> Es importante aclarar que cualquier implementación que no tenga todo el espacio de memoria dedicado a representar el espacio de usuario de manera contigua será motivo de desaprobación directa, para esto se puede llegar a controlar la implementación a la hora de iniciar la evaluación.
> El tamaño de la memoria siempre será un múltiplo del tamaño de página.

Leyendo otros issues se habla de una parte que tiene memoria de paginacion y otra parte para los archivos, leerlos y escribirlos. De ahi surgen varias preguntas, la primera es para que necesitariamos tener dos partes en la memoria, y la otra es que guardar en la paginacion. 
Entendemos que podriamos realizar una especie de lista para poder almacenar las lineas de pseudocodigo y que CPU las solicite (segun los issue vimos que con bitarray) y por otro lado no entendemos si esto se debe implementar con paginacion. Siendo ese caso como podemos iniciar con esta forma de ordenar la memoria? Deberiamos consumir el archivo guardando en cada pagina (o mas de una) una linea del pseucodigo?

**Comment by FredeHG** [comment]
Hola buenas!

Cuando nos referimos a 2 memorias o 2 partes, es que una parte es la memoria de usuario, es decir, una memoria continua como es la ram. Y la otra es una memoria como la que están acostumbrados a programar, que el sistema operativo se dedica a gestionar

Bueno en la de usuario ustedes van a ser ese sistema operativo y nosotros vamos a ser los programadores que no se dedican a gestionarla

Ahora, que se guarda en la paginación o en la memoria de usuario? Las variables de los programas! pero vuelvo a citar un issue que me encanta https://github.com/sisoputnfrba/foro/issues/3566 donde pueden ver que es lo que se va a guardar

Y sobre bitarray, vuelvan a leer porque solo exigimos la implementacion de bitmap en file system, pero son libres de usarlo donde lo consideren útil.

Espero les sirva la respuesta!
Saludos!

**Comment by RaniAgus** [comment]
¡Buenas @octavaliente! ¿Te sirvió la respuesta de Fede? Saludos

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, ante cualquier consulta pueden reabrirlo o abrir uno nuevo. Saludos
