### ISSUE TITLE
Archivos de Pseudocódigo

### ISSUE THREAD

**Issue by VinixHub** [sisoputnfrba/foro#3705]
**Buenos días/tardes/noches a todo aquel que haya llegado al issue.**
  Nos encontramos con mis compañeros queriendo hacer el módulo de memoria y nos quedamos atorados con los archivos de pseudocódigo. Por lo que pudimos averiguar de los Issues #3464 y #3647 son archivos.txt (_que estarán en algún directorio dentro del tp_) que incluyen las instrucciones que nuestro proceso debe hacer a la hora de ejecutarse.
**Entonces, nuestras consultas son:** 
- Deberíamos hacer un archivo.txt para c/ proceso? 
- Hay ejemplos de años anteriores para ver bien cómo es que se hace? 
- En el 2do párrafo del encabezado 'Memoria de Instrucciones' dice:
> Al momento de recibir la creación de un proceso, la memoria de instrucciones deberá leer el archivo de pseudocódigo indicado y generar las estructuras que el grupo considere necesarias para poder devolver las instrucciones de a 1 a la CPU según ésta se las solicite por medio del Program Counter.

   A qué tipo de estructuras se refiere?

**Comment by mefederico** [comment]
Hola buenas!

Te respondo en orden!

Va a ver multiples archivos de pseudocódigo, pero podrías tener mas de un proceso corriendo con el mismo archivo de pseudocódigo, de la misma forma que en su computadora pueden abrir N veces el navegador o el bloc de notas.

Ya tienen ejemplos de pseudocódigo actuales [acá](https://github.com/sisoputnfrba/c-comenta-pruebas)

Cualquier estructura que definan ustedes como equipo con la cual puedan responderle al CPU cual es la instrucción siguiente de un proceso puntual.

Espero haber resuelto las dudas, cualquier cosa re-pregunten 😄 
Saludos!

**Comment by VinixHub** [comment]
Muchísimas gracias fede por el soporte. No tomamos en cuenta el ejemplo que diste y no habíamos encontrado esos ejemplos, así que de nuevo muchas gracias.
Y respecto a las estructuras quedó entendido (_cualquier cosa, repreguntamos jeje_).
