### ISSUE TITLE
Orden al chequear si llego una interrupcion y recibir una interrupcion?

### ISSUE THREAD

**Issue by papiness77** [sisoputnfrba/foro#3706]
Hola, la duda como dice el titulo es si tiene que haber un orden entre esos dos ejecuciones. Es decir solo puedo recibir una nueva interrupcion si ya se chequeo la anterior no? Porque sino podria pasar que una interrupcion se paso por alto. Y solo tengo que chequear si hay interrupcion si el codigo ya paso por recibir interrupcion. Estaba pensando en hacer un semaforo inicializado en 1,  haria un wait a este semaforo  antes de la parte donde recibo la interrupcion y en la parte que chequeo si hay interrupcion iba a hacer un if si el semaforo es 0 o menor ahi entro a chequear la interrupcion y al final hago un sem_post. Hago el if para que si no me llega ninguna interrupcion no este haciendo sem_post al semafor hasta el infinito. Saludos

**Comment by LeandroCarbajales** [comment]
Buenas!
No se si estoy entendiendo bien el caso que planteas, pero tu pregunta viene por el lado de que durante la ejecución de un proceso lleguen más de una interrupción? Cómo se te ocurre en este TP que pueda ocurrir eso?

**Comment by papiness77** [comment]
Buenas, un caso no podria ser que llegue una interrupcion para finalizar el proceso por la consola de kernel y tambien en ese intervalo llega una interrupcion por desalojo de RR. La consulta basicamente es que en ese caso no tendria que dejar pasar a la segunda interrupcin sin haber atendido la primera. Quizas despues se dealoja el proceso y atiendo la segunda interrupcion pero como veo que el PID del proceso en ejecucion no es el mismo la descarto.

**Comment by LeandroCarbajales** [comment]
Buenas!
Claro, directamente no debería atender esa "segunda" interrupción si ya no es válida, otra opción que podés plantear para no tener ese caso es cancelar el envío de la interrupción de fin de Q para ese proceso si en definitiva vas a enviar otra para finalizarlo :)

Te aclara la duda?

**Comment by papiness77** [comment]
SI, muchas gracias Lean
