### ISSUE TITLE
Desconexión de módulos

### ISSUE THREAD

**Issue by julienf04** [sisoputnfrba/foro#3707]
#### El contexto de mi duda es el siguiente:

Una vez que todos los módulos ya están conectados y funcionando, se me ocurrió que podría ocurrir el siguiente caso:
¿Qué pasa si por ejemplo el módulo CPU termina su ejecución inesperadamente debido a un factor externo (como por ejemplo, apagar la compu o VM que está ejecutando ese módulo) y después de un rato intenta conectarse nuevamente a los demás módulos?
Lo mismo podría pasar con el Kernel o con la Memoria.

#### Entonces, mi duda es:

¿Mi sistema distribuido debería tener alguna estrategia para restablecerse y seguir funcionando "correctamente" en caso de que algún módulo (excepto IO) se desconecte inesperadamente?

**Comment by FredeHG** [comment]
Hola buenas!

No hace falta contemplar esas cosas, no se van a probar

si algo inesperado pasa, bajan todo (si lo necesitan) y ejecutan de nuevo

Saludos!
