### ISSUE TITLE
Crear proceso que no existe

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3708]
Buenas! se debe contemplar el caso de que ustedes ejecuten el comando de kernel INICIAR_PROCESO con un path que no existe en memoria??

Y ya que estamos hablando de esto me llama la atencion el tema de los espacios intermedios, al menos como los que reciben numeros usamos **atoi** esta funcion te los saca pero con INICIAR_PROCESO no pasaria eso si pongo muchos espacios y despues el nombre del path (no lo puedo poner porque github me saca los espacios)

Desde ya muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

No, no se va a probar ese caso.

Saludos.-
