### ISSUE TITLE
Duda sobre implementación de interfaces.

### ISSUE THREAD

**Issue by KevinQ73** [sisoputnfrba/foro#3709]
Buenos días, disculpen si los molesto un domingo.

Tengo una duda sobre la implementación de las interfaces. Me pide que al iniciar una interfaz, me pida por parámetro un nombre único y el archivo config. Acá la duda que tenemos son suposiciones de como obtener los parámetros que hay que enviar a una posible función `void iniciar_interfaces(char* nombre, t_config* config_de_interfaz);`

### 📔 Citas del enunciado/videos
>Al iniciar una Interfaz de I/O la misma deberá recibir 2 parámetros:
>- Nombre: Este nombre será único dentro del sistema y servirá como identificación de la Interfaz dentro del TP.
>- Archivo de Configuración

- Versión 1: Si al momento de iniciar la interfaz, te pida por consola que tipees el nombre (y haga la verificación de que sea único) y el nombre del archivo config a buscar en una carpeta con n interfaces.
- Versión 2: Que el nombre esté en el config y los configs estén cargados como argumentos del main, y yo pasarle no sé, el número de ubicación en el array. (Acá tengo otra suposición que tengo es que, en caso de tener n configs en el array de argumentos, y mientras estoy ejecutando quiero agregar un nuevo config a la carpeta donde están ubicados, debería modificar el array de argumentos para que la nueva instancia del módulo pueda leerlo).
- Versión 3: Abandonar la carrera. Na mentira, hay que hacer bromas en este domingo gris.

No sé si nos estamos haciendo mucho lío y talvez hay algo más simple que también lo sea a la hora de abrir n interfaces, espero puedan orientarnos un poco.

**Comment by RaniAgus** [comment]
¡Buenas! Tienen como alternativas:
a) Ingresar los valores por consola con `readline()`:
```
$ ./bin/entradasalida
Ingrese el nombre de la I/O: Int1
Ingrese el archivo de configuración: ./cfg/generica.config
```
b) Pasar ambos como [argumentos para el main](https://docs.utnso.com.ar/guias/programacion/main):
```
$ ./bin/entradasalida Int1 ./cfg/generica.config
```
Creo que para el desarrollo les va a convenir más la segunda que la primera, ya que podrían configurar VSCode para que le pase unos argumentos por defecto en lugar de tener que andar tipeando los valores cada vez que quieran reiniciar el debugger.

En cuanto a la verificación de que el nombre sea único, estaría piola hacerla pero no es estrictamente necesaria. Para las pruebas siempre vamos a elegir nombres únicos.

Saludos

**Comment by KevinQ73** [comment]
Excelente! Muchas gracias por la respuesta.

**Comment by KevinQ73** [comment]
Buenas, me surgió otra duda.

En caso de que una instrucción sea `IO_GEN_SLEEP Int2 20` y Int2 sea de tipo STDIN, Kernel debería avisarle a Int2 de la operación y este avisar que no puede realizarlo y decirle a Kernel que matar el proceso o debería haber un chequeo previo?

**Comment by KevinQ73** [comment]
Disculpen, acabo de leer la parte del enunciado que menciona justamente eso XD. Gracias de todos modos
