### ISSUE TITLE
Duda conexiones e hilos

### ISSUE THREAD

**Issue by OreNoe** [sisoputnfrba/foro#3711]
Buenas! Estamos teniendo un problema con las conexiones en el tp. 
Nosotros creamos un hilo para cada cliente que se conecta al servidor. Pero resulta que cuando probamos enviar dos mensajes seguidos para que los reciba el servidor, después de que el hilo está creado y entra en la función atender_cliente(socket), los siguientes mensajes que llegan se leen mal o directamente no llegan.

Muchas gracias!
#### Del lado de la memoria
```c
int main(int argc, char *argv[])
{
    iniciar_config();
    socket_servidor_memoria = iniciar_servidor(logger_memoria, PUERTO_MEMORIA, "MEMORIA");

    while (1)
    {
        pthread_t thread;
        int socket_cliente = esperar_cliente(socket_servidor_memoria, logger_memoria);
        pthread_create(&thread, NULL, atender_cliente, (void *)(long int)socket_cliente);
        pthread_detach(thread);
    }

    terminar_programa(socket_servidor_memoria, logger_memoria, config_memoria);

    return 0;
}
```

```c
void *atender_cliente(void *socket_cliente)
{
    t_paquete *paquete = malloc(sizeof(t_paquete));
    paquete->buffer = malloc(sizeof(t_buffer));
    
    while (1){
        paquete = recibir_paquete((int)(long int)socket_cliente);

        if (paquete == NULL) {
            log_info(logger_memoria, "Se desconecto el cliente");
            break;
        }
        uint32_t pid, pc;
        t_instruccion *instruccion = malloc(sizeof(t_instruccion));
        
        op_code codigo_operacion = paquete->codigo_operacion;
        t_buffer *buffer = paquete->buffer;

        switch (codigo_operacion){
            ...                
            case CREAR_PROCESO:
                char *path;

                t_solicitudCreacionProcesoEnMemoria *solicitud = malloc(sizeof(t_solicitudCreacionProcesoEnMemoria));

                solicitud = deserializar_solicitud_crear_proceso(buffer);
                log_info(logger_memoria, "Se recibio un mensaje para crear un proceso con pid %d y path %s", solicitud->pid, solicitud->path);
                crear_proceso(procesos, solicitud->pid, solicitud->path);

                printf("proceso creado\n");
            break;
                ...
        }
        eliminar_paquete(paquete);
    }
    return NULL;
}
```

#### Del lado del cliente

```c
t_paquete *paquete = crear_paquete(CREAR_PROCESO);

    char *path = "test.txt";
    uint32_t pid = 5;
    t_solicitudCreacionProcesoEnMemoria *ptr_solicitud = malloc(sizeof(t_solicitudCreacionProcesoEnMemoria));
    ptr_solicitud->pid = pid;
    ptr_solicitud->path_length = strlen(path) + 1;
    ptr_solicitud->path = path;
    t_buffer *buffer = serializar_solicitud_crear_proceso(ptr_solicitud);
    paquete->buffer = buffer;
    enviar_paquete(paquete, conexion);
    log_info(logger, "Se envio el paquete con el pid %d y el path %s", pid, path);
    eliminar_paquete(paquete);

    // Envio otro crear proceso

    t_paquete *paquete2 = crear_paquete(CREAR_PROCESO);
    char *path2 = "test2.txt";
    uint32_t pid2 = 6;
    t_solicitudCreacionProcesoEnMemoria *ptr_solicitud2 = malloc(sizeof(t_solicitudCreacionProcesoEnMemoria));
    ptr_solicitud2->pid = pid2;
    ptr_solicitud2->path_length = strlen(path2) + 1;
    ptr_solicitud2->path = path2;
    t_buffer *buffer2 = serializar_solicitud_crear_proceso(ptr_solicitud2);
    paquete2->buffer = buffer2;
    enviar_paquete(paquete2, conexion);
    log_info(logger, "Se envio el paquete con el pid %d y el path %s", pid2, path2);
    eliminar_paquete(paquete2);
```
#### Logs de la memoria (servidor)
```
[INFO] 01:14:29:550 MEMORIA/(19859:19859): Se conecto un cliente!
codigo de operacion: 2
[INFO] 01:14:29:551 MEMORIA/(19859:20700): Se recibio un mensaje para crear un proceso con pid 5 y path test.txt
proceso creado
[INFO] 01:14:29:552 MEMORIA/(19859:20700): Se recibio un mensaje de un modulo desconocido
codigo de operacion: 825569328
[INFO] 01:14:29:555 MEMORIA/(19859:20700): Se recibio un mensaje de un modulo desconocido
codigo de operacion: 393216
[INFO] 01:14:29:571 MEMORIA/(19859:20700): Se recibio un mensaje de un modulo desconocido
[INFO] 01:14:29:571 MEMORIA/(19859:20700): Se desconecto el cliente
```

#### Logs cliente
```
[INFO] 01:14:29:550 TEST/(20684:20684): Se envio el paquete con el pid 5 y el path test.txt
[INFO] 01:14:29:550 TEST/(20684:20684): Se envio el paquete con el pid 6 y el path test2.txt
```

**Comment by RaniAgus** [comment]
¡Buenas! Me suena a que podría llegar a tener que ver con una disparidad entre la cantidad de bytes que envían de un lado y la cantidad que reciben del otro.

Les recomiendo que desde el [debugger](https://docs.utnso.com.ar/guias/herramientas/debugger) agreguen un breakpoint justo antes del `send()` para corroborar que estén enviando la cantidad de bytes que reciben del otro lado con `recv()`.

Pueden usar el inspector de memoria de VSCode para ver los bytes que se envían de un lado y los que se reciben del otro: https://github.com/sisoputnfrba/foro/issues/3459#issuecomment-2043302751

También estaría bueno que el log `Se recibio un mensaje de un modulo desconocido` imprima el código de operación que (dice) haber recibido, aunque también pueden usar el debugger para chequear de dónde puede estar saliendo.

Si no funciona, ¿podrían mostrarnos las funciones `deserializar_solicitud_crear_proceso()` y `deserializar_solicitud_crear_proceso()` para más contexto?

Por otro lado, un detalle más (no relacionado con el problema), veo que del lado del servidor repiten varias veces lo siguiente:
```c
    t_paquete *paquete = malloc(sizeof(t_paquete));
    paquete = recibir_paquete((int)(long int)socket_cliente);
```
- Primero hacen `malloc()` para reservar memoria en el heap y guardar la dirección de memoria (que es un número entero como, por ejemplo, `0x123`).
- En la siguiente línea, pisan ese puntero con otro valor retornado de una función (por ejemplo, `0x456`).

Lo que ocurre acá es que la memoria que reservaron en el primer paso (que se encuentra en `0x123`) no está en uso, y perdieron la referencia ya que la pisaron con el valor `0x456`, lo cual es un memory leak.

La solución es simplemente usar el puntero que les retornó la función:

```c
    t_paquete *paquete = recibir_paquete((int)(long int)socket_cliente);
```

Saludos

**Comment by OreNoe** [comment]
Ahi estuvimos viendo y la primera vez que manda anda todo ok pero la segunda vez que le llegan cosas al servidor parece que lee basura. Lo vimos con el debugger y el inspector de memoria 

#### Del lado del cliente 
Parece hacer todo bien
![image](https://github.com/sisoputnfrba/foro/assets/71676290/c29c1f14-834c-4057-8a74-9117f0cc3927)

#### Del lado del servidor
![image](https://github.com/sisoputnfrba/foro/assets/71676290/388ccb57-0b7e-4553-a3e6-28310d2c819b)

Este seria el codigo de serializacion y deserializacion de las solicitudes de procesos

```c
t_buffer *serializar_solicitud_crear_proceso(t_solicitudCreacionProcesoEnMemoria *solicitud)
{
	t_buffer *buffer = crear_buffer();

	buffer_add(buffer, &solicitud->pid, sizeof(uint32_t));
	buffer_add(buffer, &solicitud->path_length, sizeof(uint32_t));
	buffer_add(buffer, solicitud->path, solicitud->path_length);

	return buffer;
}

t_solicitudCreacionProcesoEnMemoria *deserializar_solicitud_crear_proceso(t_buffer *buffer)
{
	t_solicitudCreacionProcesoEnMemoria *solicitud = malloc(sizeof(t_solicitudCreacionProcesoEnMemoria));
	buffer->offset = 0;

	buffer_read(buffer, &solicitud->pid, sizeof(uint32_t));
	buffer_read(buffer, &solicitud->path_length, sizeof(uint32_t));
	solicitud->path = malloc(solicitud->path_length);
	buffer_read(buffer, solicitud->path, solicitud->path_length);
	return solicitud;
}
```

**Comment by RaniAgus** [comment]
Hmmm... ¿Y qué onda con el `send()` y los `recv()`? ¿Pudieron poner un breakpoint para chequear que la cantidad de bytes que envían y reciben coincida con la que esperan enviar y recibir? Me huele a que se están mandando bytes de más en el primer `send()` y del otro lado no se están recibiendo hasta atender el 2do mensaje.

**Comment by OreNoe** [comment]
Ahí está, estábamos enviando más bytes de los que recibiamos. Gracias!
