### ISSUE TITLE
DUDAS CON MANEJO DE RECURSOS

### ISSUE THREAD

**Issue by nicolasreypc** [sisoputnfrba/foro#3712]
Encontre un issue que respondio mis anteriores dudas pero me surgio una nueva, en caso de que un proceso se bloquee por wait y tenga quantum todavia, al desbloquearse debe ir a la cola prioritaria no? (todo esto en el caso de VRR)

**Comment by LeandroCarbajales** [comment]
Buenas @nicolasreypc !
Quedó resuelta la duda con el último comment del issue citado?
