### ISSUE TITLE
Acción a tomar por Kernel ante desconexión de IO

### ISSUE THREAD

**Issue by KevinQ73** [sisoputnfrba/foro#3714]
Buenas, leyendo el enunciado, quedé con la duda de que debería hacer Kernel en caso de que un proceso que esté utilizando una interfaz IO, este se desconecte mientras esté ejecutando la rutina de dicha operación y no llegue a finalizarlo. Lo más certero que se me viene a la cabeza es que lo mande a EXIT de una, pero prefiero ver que me responden ustedes.

### 📔 Citas del enunciado/videos
> Toda interfaz de I/O puede conectarse y desconectarse en tiempo de ejecución.

Entiendo según el issue #3456 sobre la verificación antes de mandar la operación a IO, pero me sigue haciendo ruido sobre que pasa si se desconecta mientras hacia su trabajo y no llega a finalizarlo. ¡Espero su respuesta!

**Comment by iago64** [comment]
Buenas! Cómo va?

Es una prueba que no tenemos pensada hacer, pero si quieren mandarlo a EXIT ante alguna desconexión random esta perfecto.

Saludos.-
