### ISSUE TITLE
Se pueden crear interfaces con el mismo nombre ?

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3715]
Buenas! Quería saber si tenemos que contemplar que se creen por ejemplo dos interfaces con el mismo nombre y distinto tipo por ejemplo. No sé bien cómo funcionará el `t_dictionary` en estos casos. Pero al menos probándolo sin querer si pasaba esto, nuestro tp lo procesaba mal

**Comment by iago64** [comment]
Buenas! Cómo va?

Cito al enunciado:

> Al iniciar una Interfaz de I/O la misma deberá recibir 2 parámetros:
>- Nombre: **Este nombre será único dentro del sistema** y servirá como identificación de la Interfaz dentro del TP.
>- Archivo de Configuración

Saludos.-
