### ISSUE TITLE
Servidores pierden el file descriptor del cliente luego de salir del hilo que hace el handshake

### ISSUE THREAD

**Issue by ArielRotolo** [sisoputnfrba/foro#3716]
Buenas, en mi grupo nos encontramos con una pequeña discusión acerca de como manejar la lógica de enviar y recibir comandos de otros módulos cuando estamos en un hilo que funciona como servidor.

### Descripción del problema
Debido a que la conexión de los servidores tiene que manejarse en hilos para que no sean bloqueantes surge un problema luego de aceptar una conexión, por ejemplo aceptamos una conexión del Kernel siendo la Memoria el servidor, se crea un hilo que hace el handshake con el Kernel y dentro de esta función de handshake puede haber dos opciones:

1. La primera es inmediatamente luego del handshake sin salir del hilo se llama a otra función que según el modulo conectado hace un Switch para ejecutar una función especifica para manejar el modulo (la memoria sabe que modulo se conecto porque cada uno tiene un handshake en particular, entonces dependiendo del modulo entra a un Case distinto del Switch).

2. La segunda es salir del hilo después de completarse el handshake y tratar de hacer el manejo de comandos desde el main del servidor, la memoria en este caso.

La discusión surge de que por ahora la única forma sencilla que encontramos de implementarlo es manejar los comandos inmediatamente llamando una función en el hilo que hace el handshake, pero esta solución no parece muy practica para algunos porque se considera que el código esta muy metido adentro de funciones que llaman a otras funciones encadenadas y todavía faltan agregar muchas mas!

Y el problema es que de la segunda forma no podemos encontrar el método para hacerlo simple, dado que al salir del hilo que acepta la conexión el file descriptor de la conexión se pierde, tampoco es posible solucionarlo rápido con variables globales porque las funciones para aceptar_clientes, handshake y otras son compartidas entonces la puede ejecutar la memoria, el kernel o la cpu, esto generaría conflictos. Lo que se me ocurre seria guardar los file descriptor junto con el modulo que se conecto en una lista con una estructura especial, pero no se si es mucho dolor de cabeza innecesario o es mejor que la primera opción.

Sugerencias?

### 📝 Código relevante - Por ahora lo tenemos implementado de la primera forma
```C
// Este handshake se ejecuta en un hilo que es creado despues del accept() y es unico por cada modulo conectado
int handshake_con_cliente(int socket_cliente) {
    modulos_t modulo_conectado = ERROR; // Esto es un enum que identifica el modulo que se conecto
    int32_t rta_handshake = 0;

    if(recv(socket_cliente, &modulo_conectado, sizeof(modulos_t), MSG_WAITALL) < 0) {
        perror("Error en handshake");
        close(socket_cliente);
        return EXIT_ERROR;
    }
    // modulo_conectado deberia leer un enum distinto dependiendo del modulo que se conecto asi podemos identificarlo
    if(modulo_conectado < 0 || modulo_conectado >= ERROR)
        rta_handshake = -1;

    ssize_t bytes_send = send(socket_cliente, &rta_handshake, sizeof(int32_t), 0);

    if(bytes_send < 0 || rta_handshake != 0) {
        perror("Error en handshake");
        close(socket_cliente);
        return EXIT_ERROR;
    }
    // No salgo del hilo para no perder el socket_cliente y espero recibir o enviar comandos del modulo conectado
    manejar_comandos(modulo_conectado, socket_cliente);

    return EXIT_OK;
}

// Dentro de cada case en vez de un printf se ejecutaria una función distinta dependiendo del modulo
void manejar_comandos(modulos_t modulo, int socket_cliente) {

    switch (modulo) {
        case CPU:
            puts("CPU conectada...\n");
            break;
        case KERNEL:
            puts("KERNEL conectado...\n");
            break;
        case GENERIC:
            puts("Interfaz GENERIC conectada...\n");
            break;
        case STDIN:
            puts("Interfaz STDIN conectada...\n");
            break;
        case STDOUT:
            puts("Interfaz STDOUT conectada...\n");
            break;
        case DIALFS:
            puts("Interfaz DIALFS conectada...\n");
            break;
        default:
            puts("Error!\n");
            exit(EXIT_ERROR);
    }
}
```

**Comment by ArielRotolo** [comment]
Hola Leandro!

Me imagino que primero hay que guardar en una lista una estructura que tenga el file descriptor, el enum del módulo y de alguna manera el nombre en caso que sea una interfaz porque podemos tener 2 genericas y hay que diferenciarlas, el enum solo no alcanzaría necesitamos el nombre también.

Después en el main habría que leer de esa lista uno por uno y disparar un hilo por cada conexión para que se pueda hacer todo sin bloquear el programa.

Pero justamente esa es mí duda si no sería algo extremadamente complicado cuando la primera opción parece más sencilla a simple vista. Tampoco se del todo si la primera opción tiene desventajas o complicaciones que nos puedan traer a futuro.

Tengo miedo de elegir una que nos complique la vida más adelante...

**Comment by LeandroCarbajales** [comment]
Buenas!
Si de una forma u otra al final van a crear un hilo por cada conexión, la forma resumida en que veo las 2 opciones que plantean en el primer mensaje es:

opción 1: se conecta un cliente, crean un hilo para que lo atienda indefinidamente (handshake + otros pedidos)
opción 2: se conecta un cliente, crean un hilo para el handshake, finalizan el hilo, crean otro hilo para que atienda sus próximos pedidos indefinidamente, incluyendo tener la misma cantidad de funciones dentro de funciones que la opción 1 pero con más pasos.

En ambos casos algun hilo (imagino que el mail) debería mantenerse escuchando nuevas conexiones, creo que está muy clara cual es la opción más simple.

Si les preocupa tener funciones dentro de funciones dentro de funciones, es lo más normal del mundo 😄 . En la vida profesional este proyecto es de mediano tirando a chico, se van a encontrar con códigos mucho más grandes con muchas más funciones dentro de funciones, justamente ahí está la habilidad de ser lo más organizado y expresivo posible con los nombres de las funciones, variables, etc.

**Comment by ArielRotolo** [comment]
Bueno al parecer la segunda opción es una complicación sin mucho sentido, perfecto.

La duda que queda en algunos es si hacer un switch que identifique cada módulo y en base a eso ejecute una función distinta (dónde adentro va a esperar un comando) es un error de diseño y sería mejor usar un código de operación recibido para identificar que comando se debe ejecutar en el servidor directamente.

**Comment by ArielRotolo** [comment]
Pensando un poco tal vez al no poder volver al main y quedar en el hilo ya no se tiene acceso al log por ejemplo o cualquier otra variable que necesitemos en el futuro. Capaz eso podría traer problemas o no?

**Comment by LeandroCarbajales** [comment]
> La duda que queda en algunos es si hacer un switch que identifique cada módulo y en base a eso ejecute una función distinta (dónde adentro va a esperar un comando) es un error de diseño y sería mejor usar un código de operación recibido para identificar que comando se debe ejecutar en el servidor directamente.

Por suerte no evaluamos diseño a nivel código en C por lo que pueden hacerlo de la manera más práctica para ustedes :)
Pero por qué les parece un error de diseño? Qué problema creen que les traería?

Entiendo que ahora están rotando entre 2 opciones algo así:
opción 1: No importa con qué módulo estén hablando, atenderlo con una función que sepa recibir y realizar todas las operaciones posibles.
opción 2: Una vez hecho el handshake y por lo tanto saben qué módulo (o tipo de interfaz) se conectó, tener un switch previo para llamar a una función que solamente sepa atender y realizar las operaciones de ese módulo.

No veo mayores diferencias entre una y otra más allá de tener las mismas funciones divididas de distinta manera, aunque la 2da probablemente les sirva para tener funciones y switches más chicos, que en general son más fáciles de entender , de extender y de dividirse entre el equipo. (por ejemplo, funcAtenderSTDOUT() sería una función simple ya que atendería un solo tipo de operación, mientras otro trabaja en funcAtenderSTDIN, etc.) 

> Pensando un poco tal vez al no poder volver al main y quedar en el hilo ya no se tiene acceso al log por ejemplo o cualquier otra variable que necesitemos en el futuro. Capaz eso podría traer problemas o no?

Por el tema del log y otras variables, si las necesitan en muchos hilos a la vez, probablemente quieran usar variables globales :)

**Comment by ArielRotolo** [comment]
Era más una suposición de que podría traer problemas pero no saben explicar el porque así que bueno, me quedo con la opción ya implementada que parece la más práctica.
Muchas gracias por la ayuda Leandro!

**Comment by ArielRotolo** [comment]
Buenas noches @LeandroCarbajales, vuelvo a abrir el issue porque efectivamente surgió un problema... 

Como ya mencioné antes nosotros tenemos el handshake con el cliente dentro de servidor.h que se encuentra en un directorio "utils" el cual es compartido por todos los módulos que actúan de servidor (memoria, cpu y kernel) ya que todos utilizan las mismas funciones. Ahora bien, tal cual expliqué, después del handshake se llama a la función manejar_comandos que tiene un switch y dependiendo de la conexión ejecutaría distintas funciones para hablar con el modulo conectado.

Bueno ese es el problema justamente al tratar de implementar estas funciones todas se encuentran dentro de la carpeta compartida utils/ por estar en servidor.h entonces se pierde totalmente las variables necesarias del resto de los módulos, por ejemplo los loggers que al estar todos en un directorio si se utiliza una variable global se puede asignar a 1 no más, por supuesto se puede hacer una variable global por cada modulo pero ahora todo el código del proyecto estaría manjandose dentro de este servidor.h en la carpeta compartida utils/ perdiendo toda la modularidad del programa y es un lio.

Por ejemplo si corro el servidor desde memoria/ donde dentro tiene su main.h con todo lo necesario el código una vez que ejecuto la función en servidor.h no tiene acceso de vuelta a lo que estaba en main.h y si quiero incluir memoria/main.h, cpu/main.h, kernel/main.h en servidor.h hay conflictos de compilación y mil problemas más. Todo esto porque quiero evitar repetir lógica y copiar varias veces las mismas funciones en cada modulo para ejecutar un handshake distinto en cada uno, pero hasta ahora veo que es la única opción viable.

No sé si supe explicarlo bien porque es medio complicado en el aire sin mostrar todo el proyecto completo, cualquier cosa reformulo la pregunta.

**Comment by RaniAgus** [comment]
¡Buenas!

1) Quizás te convenga que la función `manejar_comandos` se ejecute afuera de `handshake_con_cliente`, y sea específica de cada módulo:

```c
modulos_t modulo = handshake_con_cliente(socket_cliente);
manejar_comandos(modulo, socket_cliente);
```

Justo acá no creo que haga falta meter un struct intermedio, ya que el socket viene de la función que llama a `manejar_comandos`, pero como tip no está mal crear todos los struct necesarios para su TP: si necesitan que una función devuelva 2 o más cosas, pueden hacer:

```c
typedef struct {
    char *nombre;
    char *apellido;
} persona_t;

persona_t messi() {
    persona_t p;
    p.nombre = strdup("Lionel Andrés");
    p.apellido = strdup("Messi");
    return p;
}

persona_t p = messi();
hacer_otra_cosa(p.nombre, p.apellido);
```

2) Como todos los módulos van a tener un log obligatorio, quizás les convenga dejar la variable global y la lógica de inicialización directamente en utils.

Saludos

**Comment by ArielRotolo** [comment]
Buenas, si de eso justamente se trataba el issue originalmente, el handshake con el cliente se ejecuta en un thread luego del accept que a su vez el accept se ejecuta en un thread con un while que espera conexiones. Entonces no hay forma de salir del handshake retornando un valor. Todo esto del while infinito es para el caso de las interfaces que se pueden conectar en cualquier momento y cualquier cantidad por lo que esté thread nunca termina. Ahora en un rato paso el código del que estoy hablando para que se entienda mejor.

**Comment by ArielRotolo** [comment]
```C
int aceptar_clientes(int socket_servidor) { // esta función la invoca thread_aceptar_clientes()

    while(1) {

        int* socket_cliente = malloc(sizeof(int));

        if (socket_cliente == NULL) {
            perror("Error en malloc()");
            return EXIT_ERROR;
        }

        *socket_cliente = accept(socket_servidor, NULL, NULL);

        if (*socket_cliente < 0) {
            perror("Error en accept()");
            free(socket_cliente); // Libera la memoria en caso de error
            continue;
        }

        pthread_t thread;

        if (pthread_create(&thread, NULL, thread_handshake_con_cliente, socket_cliente)) {
            perror("Error en pthread_create()");
            close(*socket_cliente); // Cierro el socket del cliente en caso de error
            free(socket_cliente); // Libera la memoria en caso de error
            continue;
        }

        pthread_detach(thread);
    }

    close(socket_servidor);

    return EXIT_OK;
}
```

**Comment by RaniAgus** [comment]
¡Buenas! Si la función `aceptar_clientes` es genérica y quieren compartirla entre módulos pueden cambiar la firma para llamar a una función que reciba por parámetro:

```c
int aceptar_clientes(int socket_servidor, void (*manejar_conexion)(int *));
```

```c
pthread_create(&thread, NULL, (void *)manejar_conexion, socket_cliente);
```

Entonces ahí sí cáda módulo puede pasarle una función específica para manejar dicha conexión:

```c
void manejar_conexion_a_kernel(int *socket_cliente) {
  // ...
}

aceptar_clientes(socket_servidor, manejar_conexion_a_kernel);
```

**Comment by ArielRotolo** [comment]
Hola, emm si eso ya lo había pensado pero estamos en la misma porque el thread_aceptar_clientes parte de una función compartida entre todos los módulos servidores. Al final por tratar de evitar repetir lógica me complique la vida, es mucho mas fácil que cada modulo maneje el servidor con funciones personalizadas que querer hacerlo todo desde una librería compartida, ya que surgen muchos problemas.

**Comment by iago64** [comment]
Buenas! Cómo va?

Si, a veces aunque duele, no queda otra que _repetir_ algo de lógica para no complicarse a futuro.

Saludos.-
