### ISSUE TITLE
Fallo en envio de path de kernel a memoria

### ISSUE THREAD

**Issue by AgustinCarlanaRivero** [sisoputnfrba/foro#3717]
Buenas, estamos teniendo un problema a la hora de crear un nuevo proceso, mas precisamente, en el envio de un path de Kernel a Memoria, para que esta guarde las lineas del archivo en una lista. Esto funcionaba perfectamente, pero, habia un pequeño problema: Kernel le enviaba el path a Memoria y después seguía a lo suyo. Entonces después quería ejecutar ese mismo proceso, le mandaba el PCB a CPU, y luego CPU le pedía las instrucciones a memoria, las cuales todavia no habia terminado de cargar (o eso creemos que sucedia, puesto que si pausabamos el cpu en el debugger y esperabamos a que memoria guarde todo, al reanudar CPU funcionaba perfecto).
Como solución, se nos ocurrió que memoria mande una notificación a kernel de que terminó de cargar el path en su lista, entonces kernel esperaria a recibir esa confirmacion para continuar. Sin embargo, por algún motivo que no logramos sacar, se queda todo pausado! Puede ser que estemos usando mal los semáforos y eso produciese un deadlock?
Datos importantes: Memoria loguea que agrega las instrucciones a la lista 1 vez, osea que el proceso lo recibe y luego ejecuta lo que sigue perfectamente. También si en el debugger pausamos Kernel y lo reanudamos cuando se traba todo, anda y puede ejecutar 1 proceso. Es decir, todo da a entender que el problema está en Kernel a la hora de recibir la notificación.

### 📝 Código relevante

Aclaración: todos los semáforos son inicializados en 0 en la función main (salvo los mutex que son inicializados en 1).

### Kernel

**Crear PCB (la ejecuta el hilo principal):**

```
void crear_pcb(char* path) {
	t_pcb* pcb = malloc(sizeof(t_pcb));
	pcb->pid = contador_pid;
	contador_pid++;
	pcb->pc=0; 
	pcb->registros.ax=0;
	pcb->registros.bx=0;
	pcb->registros.cx=0;
	pcb->registros.dx=0;
	pcb->registros.eax=0;
	pcb->registros.ebx=0;
	pcb->registros.ecx=0;
	pcb->registros.edx=0;
	pcb->registros.si=0;
	pcb->registros.di=0;
	pcb->quantum =0; // Es el q que "guarda" con VRR, todavia no lo usamos
	pcb->estado= NEW;
   
	push_cola_mutex(cola_new, pcb); // ingresar a cola new
	//log_debug(logger_kernel, "Se crea el proceso %d en NEW", pcb->pid); 

	push_cola_mutex(cola_path, path);
	sem_post(&sem_memoria);
	sem_wait(&sem_cargado);
	
	pasar_a_ready(); // No es relevante

}
```

**Dentro del hilo de Kernel que se conecta a Memoria:**

```
while(1){
	sem_wait(&contador_memoria);
	t_proceso proceso;
	proceso.path = pop_cola_mutex(cola_path);
	proceso.size = strlen(proceso.path) + 1;
	enviar_proceso(conexion, proceso);

	t_paquete *paquete = malloc(sizeof(t_paquete));
	paquete->buffer = malloc(sizeof(t_buffer));
	log_info(logger, "Voy a recibir un paquete");
	recibir_paquete(conexion, paquete);
	switch (paquete->codigo_operacion)
	{
		case 0:
			log_info(logger, "Notificación recibida de Memoria");
			break;

		case -1:
			log_error(logger, "El cliente se desconecto. Terminando servidor");
			exit(EXIT_FAILURE);

		default:
			log_warning(logger, "Operacion desconocida");
			break;
	}
	liberar_paquete(paquete);
	sem_post(&contador_cargados);
}
```

### Memoria

**Dentro del hilo del servidor**

```
while(1){
	t_paquete *paquete = malloc(sizeof(t_paquete));
	paquete->buffer = malloc(sizeof(t_buffer));
	log_info(logger, "Voy a recibir un paquete");
	recibir_paquete(cliente_fd, paquete);

	switch (paquete->codigo_operacion)
	{
		case 1: // No es relevante
			
		case 3: // El opcode de PROCESO es 3
			t_proceso* proceso = recibir_proceso(paquete);
			t_list* lista_instrucciones_nueva = list_create();
			cargar_instrucciones(logger, proceso, lista_instrucciones_nueva);
			agregar_a_lista(lista_instrucciones_nueva);
			enviar_notificacion(cliente_fd, 0);
			// list_destroy(lista_instrucciones_nueva);
			free(proceso);
			break;

		case -1:
			log_error(logger, "El cliente se desconecto. Terminando servidor");
			exit(EXIT_FAILURE);

		default:
			log_warning(logger, "Operacion desconocida");
			break;
	}
	liberar_paquete(paquete);
}
```

**Función enviar_notificación**

```
void enviar_notificacion(int conexion, int op_code){
	
	t_paquete* paquete = crear_paquete(op_code, 0); // 0 = size de paquete

	// paquete->buffer->offset = 0; // por las dudas?

	enviar_paquete(conexion, paquete);
	
	liberar_paquete(paquete); // free() de todo
}
```

Hay funciones que son llamadas adentro de estas funciones, pero tampoco quiero que este sea un post infinito. En caso de ser necesarias, las mando, o mando todo el código, como me digan.

Desde ya, muchas gracias por la ayuda!

**Comment by AgustinCarlanaRivero** [comment]
Ok, en difinitiva Kernel se quedaba esperando a recibir el stream del paquete, y como memoria no le envia ninguno entonces se quedaba esperando para siempre.  Pusimos que el stream solo se envia si el size es 0, y anda. Igualmente, es una buena solución? O sería mejor mandarle un NULL en el stream, no enviarle la notificación como paquete, o alguna otra implementación?

**Comment by RaniAgus** [comment]
¡Buenas! Conceptualmente, el proceso debe seguir en `NEW` hasta que:
1) El grado de multiprogramación le permita avanzar
2) Estén cargadas las instrucciones en Memoria

Si el proceso no tiene cargadas sus instrucciones en Memoria, no debería estar READY ya que, justamente, no está listo para ejecutar.

Más allá de eso, si eligen enviar la respuesta de "OK" de la memoria en un paquete usando solo el opcode, o con un "0" extra para indicar que el _payload_ viene vacío, es un detalle de implementación del grupo en el cual no tenemos opinión al respecto. Dependiendo de cómo quieran reutilizar lógica les puede quedar más cómoda una u otra forma de mandar el mensaje y ambas van a estar bien 👍🏻 

Saludos

**Comment by AgustinCarlanaRivero** [comment]
Esta bien, gracias! Cierro issue.
