### ISSUE TITLE
IO del mismo tipo conectadas al mismo tiempo.

### ISSUE THREAD

**Issue by LainoRamiro** [sisoputnfrba/foro#3718]
Hola, tengo una duda pequeña por el tema de si es posible que se puedan conectar al mismo tiempo 2 interfaces de IO del mismo tipo, obviamente con distinto nombre porque el nombre es único. Nos surgió esta duda porque el enunciado no lo menciona explícitamente.
Ejemplo: 2 genéricas, 3 stdin, 3 stdout conectadas al mismo tiempo.
Saludos!

**Comment by LeandroCarbajales** [comment]
Buenas!
Así es, no hay ninguna limitación en la cantidad de interfaces conectadas de cada tipo, tranquilamente podrías tener esa combinación por ejemplo.

**Comment by LainoRamiro** [comment]
Listo, entonces gracias por aclarar la duda. Saludos! :)
