### ISSUE TITLE
Como se guardan los strings en memoria

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3719]
Buenas! quizas me estoy adelantando un poco pero me llama la atencion esta imagen donde guardan un string

<img width="346" alt="Screenshot 2024-05-15 at 10 33 47 AM" src="https://github.com/sisoputnfrba/foro/assets/129446739/e8affdc7-1ca2-42ba-83af-a3650f2f8e9d">

No puedo evitar notar que no se guarda el '\0' entonces me gustaria preguntar si este hay que guardarlo o no en memoria/
 
Asumiendo que no, entonces me gustaria saber como se maneja el envio de mensajes con las interfaces de STDIN y STDOUT

#### Todo esto asumiendo que todo lo que sale y entra a memoria lo voy a manejar como string (ascii)

1) En la interfaz stdin habria que mandarle los caracteres sin el '\0' esto no parece tener mucha complejidad

En la interfaz stdout tengo varias opciones:

1) Desde la memoria , enchufarle un '\0' a lo que lei y le mando el string armadito a la interfaz

2) En la interfaz una vez recibidos los bytes, manejarlos ahi y meterle un '\0' al final

3) no hacer nada, pero el valgrind me tira un invalid read of 1

**Comment by mefederico** [comment]
Hola buenas!

Efectivamente la idea es que no guarden el `\0`, en memoria la idea es que manejes todo como un array de bytes, pero un array de char para C es lo mismo solo cambia como interpreta el dato a la hora de leerlo

Sobre la interfaz stdout solución 1 y 2 resuelve el problema pero la diferencia radica principalmente es un tema de quien te parece más lógico y cómodo que maneje el formato del dato, el modulo encargado de mostrarlo o el modulo que solamente almacena y responde.

Evitaría la opción 3 dado que el problema no es el mensaje de valgrind, si no el invalid read en si mismo.

Saludos!
