### ISSUE TITLE
Todos los programas terminan con la instruccion EXIT del CPU?

### ISSUE THREAD

**Issue by papiness77** [sisoputnfrba/foro#3720]
Buenas, consulto esto ya que si no fuese asi tendria que considerar el caso de que el PC apunta a una instruccion NULL y avisarle al kernel cuando devuelva este proceso que el mismo no tenia mas instrucciones para ejecutar, comparado con avisarle al kernel que el proceso dejo de ejecutar por un EXIT. Saludos!

**Comment by mefederico** [comment]
Hola buenas!

Todos nuestros programas van a estar correctamente escritos, no tienen necesidad de implementar estos controles, pero son libres de hacerlo igualmente.

Saludos!
