### ISSUE TITLE
Manejo de IOs en kernel

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3721]
Buenas tardes,
En un issue anterior pregunte acerca del manejo de las distintos IOs en kernel, me recomendaron que cada hilo de la IO maneje su propia cola en la lista global que ibamos a crear para estas. Para poner un poco en contexto, nosotros creamos una lista global en kernel y cada vez que se conecta una IO se crea un elemento en dicha lista que dentro tiene una cola. Nuestras dudas son:

1-En el siguiente struct queríamos agregar un semáforo por cada IO de manera que cuando se le agregue un elemento a su cola, este sea avisado. EL problema es que la cola de las IOs estan dentro de la lista global, entonces se nos ocurrió hacer el mutex, pero qué sucedería si no se le agrego ningún elemento a la cola de esa IO, esta hace el mutex de la lista y se queda bloqueante en el semaforo hasta que alguien le agregue un elemento. Tampoco creemos poder verificar el valor del semaforo antes del mutex ya que ya estamos accediendo a la lista global mientras tranquilamente puede estar accediendo otra IO al mismo tiempo.

     typedef struct 
    {
        char* nombre_interfaz;
        int tipo_interfaz;
        int fd_interfaz;
        t_queue* cola_procesos_blocked;
    } t_list_io;

**Comment by RaniAgus** [comment]
¡Buenas! Apuntar a la lista de `t_list_io` puede que sea útil solamente para el hilo productor (el que busca la interfaz y agrega elementos a la queue); pero no así para los hilos consumidores (que, según entiendo, habría uno por cada IO) ya que siempre tendrían que ir a buscar el mismo `t_list_io` en la lista.

Entonces, los hilos de cada IO podrían, en lugar de ir a buscar su struct a la lista todo el tiempo, simplemente ya contar con una referencia al suyo y consumir solamente de la queue sin leer desde la lista global. Un ejemplo en pseudocódigo:

```js
void atender_io(t_list_io *io) {
  wait(mutex_lista_global)
  add(lista_global, io)
  signal(mutex_lista_global)

  while(true) {
      wait(io->semaforo_cola_procesos_blocked)
      pcb = pop(io->cola_procesos_blocked)

      respuesta_ok = ejecutar_io(io->fd_interfaz, pcb)
      if (respuesta_ok) {
         ...
      } else {
         ...
         break
      }
  }
  
  wait(mutex_lista_global)
  remove(lista_global, io)
  signal(mutex_lista_global)
}
```
El lock de la lista global solo lo tomarías para agregar o quitar elementos de la misma cuando se conecta y cuando se desconecta, pero luego no lo necesitarías tomar para cada elemento que se pushea a la queue. Para eso tendrías el otro semáforo (y quizás algo más?)

Saludos

**Comment by rood8592** [comment]
Gracias por el codigo de ejemplo ¿Entonces no estaría mal que cada hilo de IO mantenga la referencia a su elemento de la lista y trabaje con eso unicamente sin necesidad de hacer el mutex a la lista global? Y ahora que lo pienso ¿No necesitaria un mutex también cada cola de IO? Porque cuando manejamos el motivo de desalojo le estamos ingresando elementos y cads hilo de IO va estar sacando también sus respectivos elementos.
Y otra duda con respecto a la lista global: En kernel también tenemos hecho en el hilo que maneja el motivo de desalojo que busca en la lista de interfaces a la interfaz que leemos de la instrucción de CPU (este ve si existe y si existe, ve si admite la opcion solicitada, retorna true o false dependiendo del caso), aca si sería necesario el mutex de la lista global, no? Porque estoy recorriendo toda la lista en busca de la interfaz.

**Comment by RaniAgus** [comment]
> ¿Entonces no estaría mal que cada hilo de IO mantenga la referencia a su elemento de la lista y trabaje con eso unicamente sin necesidad de hacer el mutex a la lista global?

Claro, cada hilo de I/O no está constantemente modificando la lista (solo lo hace al iniciar y finalizar una I/O), así que no debería mantener el lock de un recurso que no está utilizando.

> ¿No necesitaria un mutex también cada cola de IO? Porque cuando manejamos el motivo de desalojo le estamos ingresando elementos y cads hilo de IO va estar sacando también sus respectivos elementos.

¡Exactamente! Era eso a lo que me refería con "quizás algo más" :P

> En kernel también tenemos hecho en el hilo que maneja el motivo de desalojo que busque en la lista de interfaces a la interfaz que leemos de la instrucción de CPU (este ve si existe y si existe, ve si admite la opcion solicitada, retorna true o false dependiendo del caso), aca si sería necesario el mutex de la lista global, no? Porque estoy recorriendo toda la lista en busca de la interfaz.

Correcto, si bien ese hilo solo hace operaciones de lectura, como puede haber otro hilo haciendo operaciones de escritura sobre ese mismo recurso (la lista) sí necesitarían mutua exclusión.

> Estoy pensando en que podría haber una lista secundaria "paralela" a la otra y que esta secundaria solo tenga nombre y operaciones admitidas pero no sé si aporta algún beneficio que buscar en la otra lista nomás.

Pienso igual: buscar la interfaz en una lista y leerla es una operación rapidísima. Además con la lista duplicada te estarías comprando el problema de necesitar mantenerla consistente con la original, por lo que no te salvarías de tener un mutex para protegerla de tener otro hilo modificándola.

Como regla general, no intenten hacer mini-optimizaciones "por las dudas", siempre que puedan mantener el código simple mejor va a ser para ustedes.

**Comment by rood8592** [comment]
Muchas gracias! Creo que logramos terminar el manejo de IOs en kernel, al menos por ahora funciona todo bien 😅

**Comment by rood8592** [comment]
Buenas tardes,
Tenemos una duda con respecto al manejo de la desconexión de la IO. Nosotros hicimos el while(1) en cada hilo de IO que maneja su propia cola y sus solicitudes. El problema que tenemos es que no sabemos bien como manejar el tema de la desconexión, nuestras dudas son:

1-Pensabamos ponernos antes de que entre al semáforo como lo que se ve comentado con un recv MSG_PEEK, pero este es bloqueante y el problema que puede haber es que se va quedar ahí bloqueante para siempre a menos que se desconecte la IO y sino se desconecta se va quedar bloqueada no pudiendo realizar solicitudes.
2-También pensamos en usar select o algo por el estilo antes del primer sem_wait pero que sucedería si se agrega un proceso a la cola de esa IO y luego se desconecta? O es un caso muy borde?

**Comment by RaniAgus** [comment]
¡Buenas! Tanto `send()` como `recv()` tienen valores de retorno en caso de que el par se haya desconectado. Pueden aprovechar de usarlos para corroborar si la interfaz sigue conectada o no y, en caso de ser así, quitarse de la lista, mandar a todos los procesos que queden en la queue a EXIT y finalizar. 

Para `send()` deberán usar el flag `SIGPIPE` para evitar que les arroje una señal al intentar escribir en un socket desconectado.

Saludos

**Comment by rood8592** [comment]
Ok, se me resolvió la duda de que sucede si se desconecta una interfaz con procesos pendientes pero que sucedería en el caso en donde no agreguemos más procesos a la cola de esa IO y la desconectemos. No se quedaría trabado en el sem_wait de hay proceso cola( el cual utilizamos para darle aviso de que ingreso un nuevo proceso a su cola)? Hasta que no le metamos un proceso y hagamos post a ese semaforo, el hilo seguira levantado y la interfaz seguirá estando en la lista.

**Comment by iago64** [comment]
Buenas!

El tema de que solo puedan atender de a 1 interfaz, si por ejemplo les mandamos una IO_GEN_SLEEP que tarda 30 minutos y atras muchas de STDOUT que son rapidas, van a quedarse esperando a la de IO_GEN_SLEEP durante 30 minutos antes de desbloquear a los que hacen las IO cortas en las otras? Si eso es asi, esta mal.

Respecto al tema de las desconexiones de las IO, no tenemos planeado desconectar una IO si tienen procesos encolados, si llega a pasar por algun evento externo (lease alguien de la fila de adelante les patea el cable de power o el cable de red de la PC) **no lo vamos a considerar como un error**.

Saludos.-

**Comment by iago64** [comment]
Buenas! Cómo va?

Algo que no me termina de quedar claro a ver si lo podemos poner en orden, si por ejemplo tienen una interfaz que se desconecta:
en primer lugar si no le llegan procesos desde el kernel no se enteran? Eso no sería problema, de ultima queda un thread ahi medio al pedo, no es la muerte de nadie.

Ahora, ¿Qué pasa si les llega un proceso que si quiere usar la interfaz? ¿Lo encolan y lo intentan mandar a ejecutar, ahi se enteran de se les desconecto la interfaz? Si eso es así, tampoco hay problema.

El espíritu de las conexiones y desconexiones de las interfaces es que puedan ser en tiempo de ejecución, ahora si no se enteran en el instante **exacto** que se les desconecta no hay problema.

Saludos.-

**Comment by rood8592** [comment]
Claro exactamente, lo primero que planteas sucede por el semáforo que se queda esperando a que entre un proceso a la cola de esa IO, por lo cual si nunca más se le mandan procesos, quedaría ese hilo ahí colgado. Por otro lado, si llega un proceso a la cola de esa interfaz que se quedo bloqueada en ese semaforo pero ya se desconectó, la desconexión la detectaríamos a la hora de intentar realizar el send, mandaríamos ese proceso a exit y ahí si el hilo finalizaría.

**Comment by iago64** [comment]
Buenas! Cómo va?

Excelente, entonces no tienen ningún problema, la solución que tienen cumple con las condiciones que esperamos.

Saludos.-

**Comment by rood8592** [comment]
Ok, muchas gracias!
