### ISSUE TITLE
Interrupciones

### ISSUE THREAD

**Issue by lucasciola1** [sisoputnfrba/foro#3724]
Buenas noches, con mi grupo trabajando en la planificación nos surgió la siguiente duda: En caso de FIFO, como indica el CPU a Kernel que ya termino de ejecutar todas las instrucciones del proceso, y que el Kernel debe mandarle otro nuevo.

Muchas Gracias

**Comment by FredeHG** [comment]
Hola buenas!

Citando el enunciado en la parte del [CPU](https://docs.google.com/document/d/1-AqFTroovEMcA1BfC2rriB5jsLE6SUa4mbcAox1rPec/edit)

> Durante el transcurso de la ejecución de un proceso, se irá actualizando su Contexto de Ejecución, que luego será devuelto al Kernel bajo los siguientes escenarios: finalización del mismo (instrucción EXIT o ante un error), solicitar una llamada al Kernel, o deber ser desalojado (interrupción).

Por lo que al leer una instrucción de exit o cualquiera de las otras condiciones mencionadas devolverías por el puerto dispatch el contexto de ejecución, esto aplica también para RR o VRR

Saludos!
