### ISSUE TITLE
Instrucción JNZ y posible bucle

### ISSUE THREAD

**Issue by FacundoStancanelliUTN** [sisoputnfrba/foro#3725]
Buenas noches, como están?
Con mi grupo, en la parte de ejecución de instrucciones, nos surgió una duda en cuanto a JNZ. Si por ejemplo hacemos un JNZ a la instrucción 4 como detalla el ejemplo, no tendríamos un bucle infinito? Habría que tener un control para no tenerlo?
![C - Comenta- v1 2 - Documentos de Google - Google Chrome 19_5_2024 21_05_03](https://github.com/sisoputnfrba/foro/assets/129307586/8fe45d1b-03be-43e9-b52d-bfde205dbfe4)

Desde ya muchas gracias.

Saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

Los bucles infinitos pueden existir y no hay problema, no tienen que controlarlos, justamente para una prueba fácil de los algoritmos de RR y VRR tener uno o varios procesos de pocas líneas que están en bucle infinito es lo más fácil 😉 

Saludos.-

**Comment by FacundoStancanelliUTN** [comment]
> Buenas! Cómo va?
> 
> Los bucles infinitos pueden existir y no hay problema, no tienen que controlarlos, justamente para una prueba fácil de los algoritmos de RR y VRR tener uno o varios procesos de pocas líneas que están en bucle infinito es lo más fácil 😉
> 
> Saludos.-

Todo bien por acá!
Buenísimo! Muchas gracias dami!
Saludos 😊
