### ISSUE TITLE
Prueba son un "SET PC"

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3726]
Buenas, teníamos una duda con respecto a uno de los archivos de pruebas, qué debería suceder si se ejecuta la siguiente prueba, debería volver a kernel con la causa error debido a que intentó modificar el PC?:
![image](https://github.com/sisoputnfrba/foro/assets/113353333/9e22ef50-d0e2-4147-9bfa-27b59080cb56)
Gracias.

**Comment by RaniAgus** [comment]
¡Buenas! Como está especificado en un ejemplo del enunciado, sí es posible hacerle SET al program counter. Vendría a ser el equivalente a la instrucción JMP (jump) de assembly. Saludos

**Comment by rood8592** [comment]
Gracias, y el tema de los SUM, SUB debe ser posibles realizarle esas acciones a los registros: PC, SI, DI? :
Ejemplos:
SUM PC AX
SUB AX PC
SUM SI DI
SUM SI AX
Porque nosotros solo lo hicimos teniendo en cuenta los registros generales.

**Comment by rood8592** [comment]
Ok, muchas gracias!!
