### ISSUE TITLE
sobre list_find()

### ISSUE THREAD

**Issue by nicolasvultaggio** [sisoputnfrba/foro#3727]
Hola! Buenos días!

Tengo una pregunta sobre el funcionamiento de list_find, de las commons, si bien entiendo como funcionan sus parámetros, mi duda es más sobre los valores que devuelve, entiendo que devuelve un puntero.
Mi pregunta es, si maneja el caso en el que la lista que se ingresa por parámetro está vacía, y en ese caso, que devuelve? debería devolver un puntero nulo no? esto también sería lo que devuelve en caso que la lista no este vacía pero no encuentre un elemento que cumpla la condición?
Y lo otro, es si REMUEVE el elemento de la lista o simplemente devuelve su valor, porque yo simplemente quiero el valor, no removerlo de la lista.
Se que quizás es una pregunta pava, pero intenté buscar en otros issues, pero todas las dudas eran sobre como se implementaba la función, el cual no es mi caso. Buen lunes.

**Comment by f-and** [comment]
Buenas Nicolas! No hay ninguna pregunta pava, solo preguntas faciles de responder ;)
En cuanto a la primera podes fijarte en la lógica de las commons en su repo [aca](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/collections/list.c) pero para responderte, si efectivamente, la función list_find retorna lo siguiente:
`return (*indirect) != NULL ? (*indirect)->data : NULL;`
Si no viste antes la lógica ternaria, esto seria: Si el puntero encontrado es distinto de NULL, enviar la información encontrada, sino retornar NULL.
Por lo tanto, para ambos casos (lista vacia, o condición no cumplida) se retorna un puntero núlo.
Y para la otra pregunta, no REMUEVE el elemento de la lista (haria una cosa completamente distinta a lo que dice hacer en ese caso jaja) solo te devuelve el puntero de la información de ese campo. Ojo que este es el puntero original, por lo que si queres usar despues esa información y modificarla vas a modificarla en la misma lista, asi que considera eso cuando la traigas y la modifiques.

**Comment by nicolasvultaggio** [comment]
PERFECTO, con respecto a la primer pregunta, entendí completamente, muchas gracias.
Y con la segunda, creo que entendí, no me devuelve un puntero a una copia de esa información, si no un puntero a ese dato del elemento, por lo tanto, si lo modifico, modifico la lista. Buenísimo entonces, me vino bárbaro esa ultima aclaración porque si no hubiese hecho horrores jaja, muchas gracias!! Cierro el issue, un saludo

**Comment by nicolasvultaggio** [comment]
perdon, estoy siguiendo la información del issue #69 

![image](https://github.com/sisoputnfrba/foro/assets/131707089/60e80e54-f75e-4e34-8946-d33e7322a67d)

(no copio el texto así se ven los colores)
por algún motivo, en la linea del return de interfaz_con_nombre, no me estaría detectando a un_nombre, aún estando pasada por parámetro, debería esta en el scope de ese subprograma, no entiendo por que no me lo detecta, salvo que, tenga un error de concepto para implementar list_find()

**Comment by f-and** [comment]
Hmmm, te fijaste de definir la función fuera de `interfaz_existe_y_esta_conectada`? Porque [C no tiene implementado de base lo que son funciones definidas dentro de funciones](https://gcc.gnu.org/onlinedocs/gcc/Nested-Functions.html) por lo que tendrias que verificar el compilador y sus opciones para ver si estas incluyendo esta extensión. De paso, sabes si la función se ejecuta correctamente por fuera del `list_find`? Osea con una prueba del tipo `interfaz_con_nombre(MODEM, "modem") o algo semejante.

**Comment by nicolasvultaggio** [comment]
si, tengo definida a interfaz_con_nombre en el kernel.h, esto no tiene que ser así?
como chequeo si tengo esa extension que se me menciona en el compilador?

**Comment by RaniAgus** [comment]
¡Buenas! Me sumo para aclarar que el compilador que usamos es `gcc` el cual sí incluye la funcionalidad de nested functions (funciones dentro de funciones). De hecho tenemos un [video](https://www.youtube.com/watch?v=1kYyxZXGjp0) explicando cómo usarlas.

No te preocupes por los colores que muestra el editor de texto. Eso se debe a que, como dijo Fede, las nested functions no son una feature del estándar de C, sino que más bien son una extensión de GCC la cual VSCode no reconoce.

Los únicos errores que cuentan son los de compilación. No importa lo que muestre el editor de texto siempre y cuando al compilar no encuentren errores, y al usar nested functions no deberían encontrarlos.

Saludos

**Comment by nicolasvultaggio** [comment]
ah okey, me quedo mas tranquilo, voy a ver bien el video este para entender bien como funciona, me sirve mucho.
por ahora cierro el issue, muchas gracias a los dos!!!

**Comment by nicolasvultaggio** [comment]
![image](https://github.com/sisoputnfrba/foro/assets/131707089/4d2d05b0-cd15-414a-8342-55a8fa27ca93)

bueno, lo debuggeo y la consola si me devuelve esto:


> src/kernel.c:350:37: error: request for member ‘nombre’ in something not a structure or union

**Comment by f-and** [comment]
Fijate que tenes que [castear](https://es.stackoverflow.com/questions/230063/duda-con-casting-de-una-funci%C3%B3n-en-c) la interfaz con su tipo adecuado. Ahi estas pasandole un void * por lo tanto la expresión `una_interfaz->nombre` no esta llamando a una estructura interfaz, sino simplemente al puntero donde esta dicha interfaz, por lo que es como si no supiera que es un struct, y por eso no reconoce la variable nombre.
La sintaxis seria algo así como `((interfaz *)una_interfaz)->nombre`.

**Comment by nicolasvultaggio** [comment]
perfecto, agregue lo siguiente y me funcionó

`element_interfaz * una_interfaz_c = (element_interfaz*) una_interfaz;`

muchas gracias por la ayuda
