### ISSUE TITLE
Inicialización de un mutex con todos sus parámetros

### ISSUE THREAD

**Issue by fmarkiw** [sisoputnfrba/foro#3728]
Buenas tardes, averiguando por la declaración e inicialización de los mutex me encontré con la siguiente función

int   pthread_mutex_init(pthread_mutex_t *restrict, const pthread_mutexattr_t *restrict);

el segundo parámetro de la misma está siempre en NULL en las implementaciones que veo pero nunca explican por qué y leí que sería necesario ponerle un valor determinado para poder compartir el mutex entre hilos (esa es mi intención). Pero la verdad que no entiendo la documentación que es super escueta y difícil de leer. ¿Hace falta ese segundo parámetro o con dejarlo en NULL puedo avanzar?

Desde ya, gracias.

**Comment by LeandroCarbajales** [comment]
Buenas!
A efectos de implementar el TP no es necesario que seteen ningún atributo en particular para los pthread_mutex, por lo que pueden dejar ese parámetro en NULL (que serían los atributos default), no necesitan ningún atributo extra para que los mutex funcionen entre hilos del mismo proceso (no confíes en mí, probalo).

Si te da curiosidad, [este post de stackoverflow](https://stackoverflow.com/a/4252090) tiene links a la documentación y una breve explicación de todos los posibles atributos que modifican el comportamiento del semáforo, entre ellos que el semáforo pueda utilizarse por hilos de otros procesos.

Te aclara las dudas?
Saludos!
     Lean

**Comment by fmarkiw** [comment]
Clarísimo, gracias
