### ISSUE TITLE
Problema con .json en VS Code

### ISSUE THREAD

**Issue by EtienneZimmerman** [sisoputnfrba/foro#3729]
Buenas! Estoy teniendo un problema para probar mi código corriéndolo en Visual Studio.
Venía usando VS Code y compilando desde el apartado "Run and Debug" del mismo sin ningún problema. Cuando quise probar de nuevo para correrlo, me tiró el siguiente error.

![1](https://github.com/sisoputnfrba/foro/assets/103065205/90038b68-4f3e-4b78-937c-7520721f663b)

Si le doy a "Debug anyway", me tira lo siguiente:

![2](https://github.com/sisoputnfrba/foro/assets/103065205/2e45cadf-da70-4ccf-97ba-01cb56d0e03e)

Pero el .json está tal cual estaba previamente
![3](https://github.com/sisoputnfrba/foro/assets/103065205/fd3e052f-0fbb-49aa-8c7e-1b4e412274bf)

Vi en otro issue que podía ser por el nombre (aunque no hay espacios en él), así que lo cambié. Sin embargo, el error persiste.

También probé en otra branch, que funciona para mis compañeros, y no es capaz de ubicar el .json, diciéndome lo siguiente:

![4](https://github.com/sisoputnfrba/foro/assets/103065205/e7fc54a0-6846-44b4-9de5-27435353c303)

Si abro una terminal y tiro un "make", este ejecuta sin problema alguno. 
Lo único que pienso que pudo haber pasado en el medio es alguna actualización de VSC, aunque no recuerdo con exactitud si empezó a suceder luego de actualizarlo.

Gracias.

**Comment by mefederico** [comment]
Hola buenas!

con el repositorio recién clonado y abriendo como `workspace` te pasa lo mismo?

**Comment by EtienneZimmerman** [comment]
Eso me funcionó! Muchas gracias :) !!

**Comment by EtienneZimmerman** [comment]
-
