### ISSUE TITLE
Duda memoria

### ISSUE THREAD

**Issue by nicolasreypc** [sisoputnfrba/foro#3731]
Buenas, en el enunciado se dice que los procesos comienzar sin espacio en memoria de usuario, esto quiere decir que el proceso va a tener que ejecutar un resize y que se le cree una tabla de paginas, antes de tener y poder utilizar espacio de memoria?

**Comment by iago64** [comment]
Buenas! Cómo va?

El momento de cuando creen la tabla de páginas lo pueden definir uds.
Despues el tema del resize, si, primero vamos a hacer un resize y despues de eso vamos a poder usar la memoria y por las dudas aclaro antes de que se la compliquen, **no vamos a probar ningun script que quiera usar memoria sin antes hacer el resize**.

Saludos.-

**Comment by nicolasreypc** [comment]
gracias!
