### ISSUE TITLE
Funcionamiento de Interfaces Entrada Salida y Kernel

### ISSUE THREAD

**Issue by FedericoGSantoro** [sisoputnfrba/foro#3733]
Hola, no vi que la pregunta este o no me sirvió para entender los que si vi. Mi pregunta esta relacionada con todo el tema de las interfaces IO y Kernel.

1. Cuando una interfaz es creada tiene que indicársele el nombre único que va a tener, supongamos "Interfaz1" no? Además del path hacia el archivo de configuración, esta interfaz debería leer el archivo de config, fijarse que tipo de interfaz es, y después leer solo los campos del archivo que le interesa no?

2. Cuando la interfaz es creada, esta se conecta automáticamente a Kernel diciendo el nombre de esta interfaz entiendo (Ósea Interfaz1) y nada mas? No se pasa el tipo de interfaz ni nada? Kernel que hace con eso? lo guarda en una lista de interfaces disponibles o una cola de interfaz especifica dependiendo de que tipo de interfaz es?

3. Y si un proceso es bloqueado, se consulta que exista esa Interfaz1, que este conectada y que admita la operación dice, si la Interfaz1 esta siendo usada como interfaz genérica, y hay otro proceso que quiere usar a Interfaz2 que también es genérica, tendría que bloquear el primer proceso hasta que este disponible la interfaz y enviar el otro proceso, que usa Interfaz2, a utilizar la interfaz esa no? Seria mas correcto que en vez de una cola de bloqueados sea una lista entonces?

4. Y por ultimo, si la interfaz termina de hacer lo que debe hacer, no debería de finalizar no? Podría seguir ejecutándose esperando una instrucción nueva por parte de Kernel.

### 📔 Citas del enunciado/videos
>Todas las interfaces de I/O tendrán un único nombre que las identificará en el sistema, este nombre deberá ser consultado al momento de que una Interfaz se conecte al Kernel . Como este nombré será único se utilizará en los programas para identificar a la Interfaz.

>De cumplirse todos los requisitos anteriores, el Kernel enviará el proceso al estado BLOCKED y a partir de este punto pueden darse 2 situaciones:
1.El caso en el que la interfaz de I/O esté libre: En este caso el Kernel deberá solicitar la operación al dispositivo correspondiente. 
5.En el caso de que exista algún proceso haciendo uso de la Interfaz de I/O, el proceso que acaba de solicitar la operación de I/O deberá esperar la finalización del anterior antes de poder hacer uso de la misma.

### 💭 Soluciones posibles
Pensamos varias alternativas a esto, usar diccionarios, colas, listas, etc.
Podría ser que sea una lista de procesos bloqueados y que se vaya recorriendo todos los procesos en orden, que se revise si la interfaz que necesitan esta disponible (Esto podría estar en un diccionario que tiene colas para cada tipo de interfaz, dentro de cada cola se tiene una estructura interfazConectada por cada interfaz, indicando el nombre de la interfaz y si esta en uso) y si no lo esta que la use. Por otro lado si no esta disponible porque esta siendo usada se revisa el siguiente elemento de la lista. Al momento de llegar el mensaje de la interfaz de que termino de hacer lo que se le pide entonces se saca el proceso de la lista y se envía a Ready. Podría ser así?

**Comment by f-and** [comment]
Buenas Fede, te contesto una por una:
1. Si, esto lo indica el enunciado en la parte de I/O, cada interfaz que uses va a necesitar su config asociado:

> Al iniciar una Interfaz de I/O la misma deberá recibir 2 parámetros:
> - Nombre: Este nombre será único dentro del sistema y servirá como identificación de la Interfaz dentro del TP.
> - Archivo de Configuración

Y despues si, de estos archivos de configuración se va a sacar unicamente los campos que requiera el tipo de interfaz (una interfaz genérica no va a necesitar del campo BLOCK_SIZE o BLOCK_COUNT).

2. Si, la interfaz se va a conectar al Kernel y el Kernel guarda la información pertinente de la misma, porque la va a necesitar usar para las instrucciones que lo requieran, requiriendo el nombre para validar con los parametros de la instrucción y el tipo para validar si la instrucción es valida para la interfaz correspondiente:

> Al recibir una petición de I/O de parte de la CPU primero se deberá validar que exista y esté conectada la interfaz solicitada, en caso contrario, se deberá enviar el proceso a EXIT.
> En caso de que la interfaz exista y esté conectada, se deberá validar que la interfaz admite la operación solicitada, en caso de que no sea así, se deberá enviar el proceso a EXIT.

En cuanto a las listas eso lo van a manejar ustedes si prefieren tenerlas separadas o en una misma bolsa.

3. Si una interfaz esta siendo utilizada por un proceso, y otro proceso quiere utilizarla, este cambia a estado BLOCKED y deberá esperar a que el primer proceso haya terminado de utilizarla para poder accederla, todo esto estaria "desconectado" del ciclo de procesamiento, se seguirian enviando procesos a EXEC y si alguno requiere otra interfaz distinta que esta libre no habria problema en asignarla. Esta espera de la primera interfaz va a ser realizada en una cola por necesitar realizarse en FIFO, pero esta cola solo va a estar asociada a la interfaz en cuestión, no tiene que estar vinculada a otra interfaz porque no se espera el uso total de cualquier interfaz.

4. Si, la interfaz se mantiene conectada hasta desconectarse manualmente.

**Comment by FedericoGSantoro** [comment]
Okk me quedo con el punto 3.
Lo que habíamos hecho es que cuando vuelve el proceso de la CPU, chequearíamos lo de la interfaz si existe y eso y lo enviamos a la cola de bloqueados donde otro hilo se encarga de enviarle a las interfaces correspondientes lo que deben hacer para tal proceso, pero todos los procesos siempre estarían en bloqueados, estaría bien eso?
También debería crear entonces una cola para cada interfaz única donde estarían los procesos que la requieran utilizar? O entendí mal?

**Comment by f-and** [comment]
Claro, lo plantean como un hilo que maneje esos casos, pero si, necesitarian crear una cola para cada interfaz para poder manejar individualmente los procesos que van a necesitar cada una de ellas. Porque sino estarian en una situación donde por ejemplo, tienen un proceso usando el mouse, y otro proceso esperando para usarlo pero el teclado, la pantalla y los parlantes quedan todos trabados porque salen de la misma cola.

**Comment by FedericoGSantoro** [comment]
Okk entonces, se me ocurre tener un diccionario que adentro tiene 4 listas, una para cada tipo de interfaz y dentro de cada lista se van ingresando unas structs de interfazConectada que tiene como campos, el nombre, el tipo de interfaz, su disponibilidad y una cola de procesos donde estarían los procesos que requieren utilizar esta interfaz especifica, puede ser una estructura así?

Al volver el proceso de CPU ingresaría el proceso en la cola especifica de cada IO (si existe y eso) y en la cola de bloqueados, después se le enviaría a la IO el pid del proceso (cuando le toque a este por FIFO) con la instrucción a ejecutar y sus parámetros, cuando termina la IO y devuelve el pid que termino de ejecutar entonces sacaría el proceso de la cola de bloqueados y lo enviaría a Ready.

Algo así estaría bien pensado?

**Comment by f-and** [comment]
En cuanto al primer parrafo, si, ya es una decisión que tomaran ustedes en cuanto a la estructura del programa, no hay una respuesta incorrecta a eso (a menos que no ande ;) ). Y encuanto al segundo si, masomenos asi seria el proceso. Si te queda alguna duda no dudes en preguntar!

**Comment by FedericoGSantoro** [comment]
Genial gracias!
