### ISSUE TITLE
Modulo de Memoria (Planificacion)

### ISSUE THREAD

**Issue by NicolasGonzaloTorre** [sisoputnfrba/foro#3734]
buenas, hace tiempo estamos intentando codear el modulo de memoria para el segundo checkpoint pero no logro terminar de entender el enunciado en general. Estamos perdidos y no sabemos bien que deberiamos hacer ¿podrian encaminarnos?

>Módulo Memoria:
Se encuentra creado y acepta las conexiones.
Es capaz de abrir los archivos de pseudocódigo y envía las instrucciones al CPU.

**Comment by f-and** [comment]
Buenas Nicolas, podras ser un poco mas especifico con la consulta? De paneo general las conexiones son las mismas que hicieron para el TP0 y para los otros modulos. Y el tema de los archivos de pseudocodigo son los archivos de prueba que se cargan cuando el Kernel inicia un proceso, el mismo se indica en el enunciado en la parte de memoria:
> Al momento de recibir la creación de un proceso, la memoria de instrucciones deberá leer el archivo de pseudocódigo indicado y generar las estructuras que el grupo considere necesarias para poder devolver las instrucciones de a 1 a la CPU según ésta se las solicite por medio del Program Counter.
Que seria lo que los estaria trabando? O que es lo que no pueden entender del enunciado?

**Comment by NicolasGonzaloTorre** [comment]
nos estaria trabando el tema de leer el pseudocodigo

**Comment by f-and** [comment]
El pseudocodigo lo tienen que considerar como leer archivos, cuando se inicia un proceso mediante el comando de Kernel `Iniciar Proceso [PATH]`, se le debe enviar a Memoria este PATH que va a indicar la ubicación de un archivo de texto en el que se encuentran las instrucciones. Memoria se va a tener que encargar de abrir este archivo y leerlo almacenandolo en un esquema de paginación simple con las estructuras que crean necesasarias para despues poder recibir pedidos del CPU para retornarle la linea solicitada. Esto hasta que el Kernel le informe que se terminó el proceso que en cuyo caso se marcan como libres los frames donde se escribieron las lineas.
De esto hay algo en especifico que los este trabando?

**Comment by LeandroCarbajales** [comment]
Buenas @NicolasGonzaloTorre !
Pudieron plantear esto que comentó @f-and o pudieron verlo en soporte?

**Comment by LeandroCarbajales** [comment]
Cierro el issue por inactividad, cualquier cosa lo vuelven a abrir.
