### ISSUE TITLE
sobre los procesos bloqueados y la desconexion de una interfaz

### ISSUE THREAD

**Issue by nicolasvultaggio** [sisoputnfrba/foro#3735]
> Toda interfaz de I/O puede conectarse y desconectarse en tiempo de 

supongamos que debo realizar una peticion IO, verifico que la interfaz exista y este conectada, y bloqueo el proceso, y luego de ese momento, la interfaz se desconecta, que hago con todos esos procesos bloqueados, debo finalizarlos? 
o se quedaran bloqueados hasta que la interfaz vuelva a conectarse?
lo que me lleva a otra pregunta del enunciado: ¿una interfaz se conecta y desconecta sucesivamente?, o sea, pasa de estar conectada a desconectada, y luego se puede volver a conectar? o una vez que se conecta, solo se desconecta una vez y luego no se puede volver a conectar mas?

**Comment by iago64** [comment]
Buenas! Cómo va?

Honestamente es un escenario que no tenemos planeado probar, pero es verdad que los accidentes ocurren y alguna que otra vez alguien en el labo sin querer pudo haber llegado a desenchufar una PC, con lo cual, si pueden finalizar todos los procesos bloqueados para esa interfaz sería un golazo.

Saludos.-

**Comment by nicolasvultaggio** [comment]
claro, entonces la idea es que una interfaz se conecta en cualquier momento, se puede desconectar en cualquier momento, pero no es que después de eso se puede volver a conectar.
Mi duda con esto es porque quizás, al desconectarse la interfaz, el kernel tenía que seguir guardando su información en  la lista de interfaces conectadas, así como sus procesos bloqueados y demás información, que permanece "congelada"

**Comment by iago64** [comment]
Buenas!

Se puede dar que una interfaz se conecte, se desconecte y se vuelva a conectar, pero no tienen que guardar info de nada.

Saludos.-

**Comment by nicolasvultaggio** [comment]
perfecto, perdón, me había olvidado de cerrar el issue, muchas gracias!
