### ISSUE TITLE
Error de direccion

### ISSUE THREAD

**Issue by lucasciola1** [sisoputnfrba/foro#3736]
Buenas, estamos teniendo un problema a la hora de asignar un path de una estructura a otra. La variable path queda con el siguiente valor.

![image](https://github.com/sisoputnfrba/foro/assets/164528763/e5c08e50-e927-47da-bbb0-0cd400bded24)

Tenemos dos estructuras, una solo con el PID, path y path_lenght que enviamos a memoria, y la otra del PCB completo.
```c
typedef struct
{
    uint32_t PID;
    uint32_t program_counter;
    uint32_t quantum;
    estado_proceso estado;
    registrosCPU contexto;
    uint32_t path_lenght;
    char* path;
} PCB;

//Estructura de datos del proceso

typedef struct
{
    uint32_t PID;
    uint32_t path_lenght;
    char* path;
    
} nuevoProceso;
```
El codigo donde transferimos es el siguiente:
```c
void solicitudProceso(){
    char* input = readline("Ingrese el Path con las instrucciones: ");
    nuevoProceso* new;
    new->path = input;
    new->path_lenght = strlen(input);
    new->PID = ultimo_pid;
    ultimo_pid++;
    enviarProcesoMemoria(new,fd_memoria);
    PCB* proceso;
    proceso->PID = new->PID;
    proceso->program_counter = 0;
    proceso->quantum = 0;
    proceso->estado = NEW;
    proceso->path_lenght = new->path_lenght;
    proceso->path = new->path;
    queue_push(cola_new, proceso);
}
```
El error se produce al querer pasar el Path desde new hacia proceso, ya que el valor de path queda con el error antes mencionado.

Muchas Gracias

**Comment by f-and** [comment]
Buenas Lucas! Para saber, `path`, como se usa en `enviarProcesoMemoria`? Porque si algo lo modifica ahi adentro, podria estar limpiandolo o cambiando el puntero.

**Comment by iago64** [comment]
Buenas! Cómo va?

Para sumar a la pregunta de Fede y por mera curiosidad, el error lo tienen solo en el debugger, pero si imprimen los valores los ven bien? O si intentan por ejemplo hacer un `printf()` les explota y/o imprime fruta? Probaron haciendo un `string_copy()` de lo que leen con `readline()` hacia una nueva variable?

Esto se los pregunto porque justamente lo que se pone medio áspero es que están laburando con `char *`, y los punteros en C son el principal enemigo con el cual tenemos que cuidarnos de no andar asignando alegremente, porque por ej si alguien hace un free de ese puntero, podemos darnos cuenta mucho después y no tenemos ni idea de donde nos mandamos la cagada.

Saludos.-

**Comment by lucasciola1** [comment]
Buenas, este es el codigo de enviarProcesoMemoria

void enviarProcesoMemoria (nuevoProceso* proceso, int socketDestino){
    //Creamos un Buffer
    t_buffer* buffer = malloc(sizeof(t_buffer));
    //Calculamos su tamaño
    buffer->size = sizeof(uint32_t)*2 + proceso->path_lenght + 1;
    buffer->offset = 0;
    buffer->stream = malloc(buffer->size);
    //Movemos los valores al BUFFER
    memcpy(buffer->stream + buffer->offset, &proceso->PID, sizeof(uint32_t));
    buffer->offset += sizeof(uint32_t);
    // Para el nombre primero mandamos el tamaño y luego el texto en sí:
    memcpy(buffer->stream + buffer->offset, &proceso->path_lenght, sizeof(uint32_t));
    buffer->offset += sizeof(uint32_t);
    memcpy(buffer->stream + buffer->offset, proceso->path, proceso->path_lenght);
    //Creamos un Paquete
    t_paquete* paquete = malloc(sizeof(t_paquete));
     // Podemos usar una constante por operación
    paquete->codigo_operacion = CREAR_PROCESO;
    paquete->buffer = buffer; 
    //Empaquetamos el Buffer
    void* a_enviar = malloc(buffer->size + sizeof(uint8_t) + sizeof(uint32_t));
    int offset = 0;
    memcpy(a_enviar + offset, &(paquete->codigo_operacion), sizeof(uint8_t));
    offset += sizeof(uint8_t);
    memcpy(a_enviar + offset, &(paquete->buffer->size), sizeof(uint32_t));
    offset += sizeof(uint32_t);
    memcpy(a_enviar + offset, paquete->buffer->stream, paquete->buffer->size);
    // Por último enviamos
    send(socketDestino, a_enviar, buffer->size + sizeof(uint8_t) + sizeof(uint32_t), 0);

    // No nos olvidamos de liberar la memoria que ya no usaremos
    free(a_enviar);
    free(paquete->buffer->stream);
    free(paquete->buffer);
    free(paquete);
}

Y para la otra pregunta, los printf de path me tiran seg fault. Gracias

**Comment by RaniAgus** [comment]
Mmm... Raro. ¿Qué les aparece al intentar correrlo con [Valgrind](https://docs.utnso.com.ar/guias/herramientas/valgrind)? Me suena a que quizás se esté corrompiendo la memoria en otro hilo y eso les esté pisando justo el contenido de ese struct.

También, algo no relacionado: cuidado que acá están reservando memoria para `path_length + 1`
```c
buffer->size = sizeof(uint32_t)*2 + proceso->path_lenght + 1;
```
Y más adelante están copiando solo `path_length`
```c
memcpy(buffer->stream + buffer->offset, proceso->path, proceso->path_lenght);
```

Saludos

**Comment by lucasciola1** [comment]
Ahora voy a probar el valgrind, respondiendo a la otra pregunta, el readline guarda bien el dato ya que cuando asigno el valor a la variable new->path el valor es correcto, pero al pasar el valor desde new->path hacia proceso->path figura ese error de memoria.

**Comment by lucasciola1** [comment]
Buenas, estoy teniendo problemas a la hora de usar Valgrind, vi la charla y la guia y cuando hago click derecho sobre el proyecto y pongo "profiling tools", no me figura ninguna herramienta para hacer el profiling, unicamente me aparece "profiling tools configuration". Intente correrlo por consola con los comandos que se indican en la guia y esta es la respuesta que recibo.

![image](https://github.com/sisoputnfrba/foro/assets/164528763/aa83ae9a-f1d3-47ef-9aa5-8ec76a0c44f4)

**Comment by f-and** [comment]
Lucas, para saber, el nombre del ejecutable es ese? Porque para ejecutarlo tendrias que elegir el ejecutable del modulo a probar (por ejemplo: `valgrind ./mi-tp/cpu/cpu.exe`)

**Comment by lucasciola1** [comment]
Era eso, no estaba ejecutandolo en el .exe, ahora que pude resolver esto, les mando la captura del Valgrind corriendo el Kernel donde me saltaba el error de memoria por el que abri el issue en un principio. Saluos y gracias

![image](https://github.com/sisoputnfrba/foro/assets/164528763/f661891d-fbe0-4416-b8bd-8145c969b3f1)

**Comment by RaniAgus** [comment]
Viendo la captura de pantalla noto que quizás lo estás corriendo desde Eclipse usando el working directory equivocado, ya que está intentando leer una config que es `NULL` (`0x0`):

![image](https://github.com/sisoputnfrba/foro/assets/39303639/3b9e478a-5530-4d5c-bc59-ad419141ebea)

Asumo que es porque no estás pudiendo cargar la config correctamente en un paso previo y no están validando el valor de retorno de `config_create` como sugerimos en el TP0, entonces en un paso siguiente les está fallando la lectura del config.

**Comment by lucasciola1** [comment]
Mil disculpas pero no entiendo la relación de las configs con el error de memoria que estamos teniendo. Además, viendo ese error me parece rarísimo ya que todos los valores que sacamos de las configs (puertos, IPs, etc) funcionaron bien cuando quisimos utilizarlos. Muchas gracias por la respuesta.

**Comment by lucasciola1** [comment]
Ya lo pude solucionar, muchas gracias
