### ISSUE TITLE
modulo de memoria checkpoint 2

### ISSUE THREAD

**Issue by mSpadoni** [sisoputnfrba/foro#3737]
hola buenas noches, tengo una duda sobre las conexiones de la memoria con los demás módulos, la parte de acceso a tabla de paginas a que modulo se conecta??

**Comment by RaniAgus** [comment]
¡Buenas! La tabla de páginas es la misma que se ve en teoría y sirve para lo mismo que en la teoría: a partir del pid y el número de página de un proceso devuelven el marco en donde se encuentra dicha página. 

Esto les va a servir cuando la CPU tenga que traducir direcciones lógicas a físicas, lo cual está especificado en la sección [MMU](https://docs.google.com/document/d/1-AqFTroovEMcA1BfC2rriB5jsLE6SUa4mbcAox1rPec/edit#heading=h.q1twu0jdsrm) de dicho módulo.

Saludos

**Comment by mSpadoni** [comment]
gracias
