### ISSUE TITLE
Problemas al Encarar los tiempos en planificación

### ISSUE THREAD

**Issue by Dummatt** [sisoputnfrba/foro#3739]
¡Buenos días! tengo una duda en parte del enunciado, y en parte de programación en C, y opté por realizar dicha consulta en esta categoría.
Estamos considerando como funciona exactamente la planificación en C, suponiendo que en cualquier momento puede entrar un nuevo proceso en estado NEW por parte del usuario gracias a la consola interactiva. Esto es debido a que, una vez iniciada la planificación en Kernel, irá a su ritmo sin detenerse. Razón por la cual creemos que si un nuevo proceso entra, será luego de que los demás acabe. Esto es encarado por la función:
```c
void* planificacion_de_procesos(string estado/**Leeria el estado del archivo config*/){
    if(estado == "FIFO"){
        planificacion_fifo();
    }else if(estado == "RR"){
        planificacion_rr();
    }
} 
```
Obviamente creemos que algo está mal, pero no sabemos definir que es. ¿Cómo hacemos para mantener un control de los procesos que entran en X tiempo? usando Semáforos será complicado, ya que con todo proceso que entra, estos semáforos se verán afectados tanto por su tiempo de entrada como por las ráfagas que tienen, lo que nos resulta imposible de encarar de una forma cómoda. 
¿O estamos encarando mal el enunciado, y en su lugar cuando entra un nuevo proceso se tiene que ejecutar independientemente de los que ya estaban planeados?

**Comment by iago64** [comment]
Buenas! Cómo va?

Esta consulta entra entre medio de la programación en C y el enunciado, por eso les sume la etiqueta de enunciado.
Respecto al enunciado, traten de leer un poco mas allá del if que subieron, ya que uds estan omitiendo que en el TP hay 2 planificadores, uno de Largo Plazo que les va a controlar los procesos que entran al sistema y despues uno de corto plazo que es este planificador que va a poder cambiar entre FIFO, RR y VRR.

Respecto a como implementarlo, traten de hacer la analogía con lo que vieron en la teoría, uds tienen que tener diferentes colas de planificación y el kernel tiene que ir moviendo procesos entre las diferentes colas de planificación, en principio guardan los PCB en NEW, despues si el PLP los deja lo pasan a READY y de ahí empieza el juego del PCP que va a variar segun el algoritmo que este configurado en la config.

Respecto a como tienen el control de las cosas que van ingresando, deberían plantear la posibilidad de agregar cosas en tiempo de ejecución a estas colas de planificación.

Por último como para cerrar la primer parte de la respuesta porque es muy probable que se les planteen nuevas dudas, no hay una forma cómoda o facil de hacer el TP, el mismo conlleva que piensen las cosas traten de hacer los paralelos con lo que ven en la teoría, escriban algo de código en base a lo que vieron en la teoría y traten de ver si ejecutando ese código si llegan a un resultado que es lo que estaban esperando y si eso no funciona, es posible que consultarnos mas puntualmente por errores de código o por cuestiones de diseño y que de nuestra se de el caso de que tengan que cambiar algo o en el peor de los casos descartar eso que hicieron y volver a empezar.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas @Dummatt 
Les sirvió la respuesta de @iago64 o pudieron verlo en soporte?

**Comment by LeandroCarbajales** [comment]
Cierro el issue por inactividad, cualquier cosa lo vuelven a abrir.
