### ISSUE TITLE
Finalizar Proceso

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#3740]
Hola buenas tengo unas preguntas sobre el comando finalizar proceso: 

1) Podria darse el caso en que haya que finalizar un proceso que esta en la cola de prioridad del VRR? 
2) Tambien queria preguntar si cuando hagan las pruebas, van a Pausar la planifiacion antes de eliminar un proceso

Desde ya muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Si, es re posible.
2.- No necesariamente, puede ser que tiremos el FINALIZAR_PROCESO sin pausar la planificación, pero de ultima si no le encuentran la vuelta y es necesario pausar la planificación para finalizar un proceso, lo avisan al momento de la corrección y no va a ser un problema.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas @JoaquinCoaricona !
Te sirvió la respuesta de @iago64 ?

**Comment by JoaquinCoaricona** [comment]
Sisi me olvidé cerrarlo.
