### ISSUE TITLE
Problema con struct: error: unknown type name ‘KERNEL_CONFIG’ 

### ISSUE THREAD

**Issue by leoojuncos** [sisoputnfrba/foro#3742]
Al debugear el _kernel_utils.c_ nos salto ese error, lo cual no termino de entender ya que al inicio del codigo tenemos el include del _kernel.h_.

### 📝 Código relevante

**KERLEN_UTILS.C**
```c
#include "kernel.h"

t_log* kernel_logger;
KERNEL_CONFIG* kernel_config;

int socket_kernel;
int socket_CPU;
int socket_entradaSalida;
int socket_memoria;
```
...

**KERNEL.H**
```c
#ifndef KERNEL_H_
#define KERNEL_H_

#define PATHKERNEL "/home/utnso/tp-2024-1c-Los-Gominolas/kernel/kernel.config"

#include "kernel_utils.c"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <commons/log.h>
#include <commons/config.h>

#include <utils/utils.h>
#include <pthread.h>
#include <readline/readline.h>

//#include "consola.c"

// -------------------------- CONEXIONES --------------------------

void iniciar_servidor_KERNEL();

void conectar_CPU_dispatch();
void conectar_CPU_interrupt();
void conectar_MEMORIA();

void esperar_conexion_EntradaSalida();
void escuchar_EntradaSalida();

// -------------------------- COONFIGURACION --------------------------
t_log* kernel_logger;
void iniciar_logger_KERNEL();

extern int socket_memoria;
extern int socket_CPU;
extern int socket_entradaSalida;
extern int socket_kernel;

int kernel_fd;
int entradaSalida_fd;
int memoria_fd;
int cpu_fd_dispatch;
int cpu_fd_interrupt;

typedef struct {
    char* PUERTO_ESCUCHA;
    char* IP_MEMORIA;
    char* PUERTO_MEMORIA;
    char* IP_CPU; 
    char* PUERTO_CPU_DISPATCH;
    char* PUERTO_CPU_INTERRUPT;
    char* ALGORITMO_PLANIFICACION;
    int QUANTUM;
    char** RECURSOS;
    char** INSTANCIAS_RECURSOS;
    int GRADO_MULTIPROGRAMACION;
} KERNEL_CONFIG;

KERNEL_CONFIG* kernel_config;
extern KERNEL_CONFIG kernelConfig;

void inciar_config_KERNEL(char* path)
void completar_config_KERNEL(KERNEL_CONFIG* config);
```

### 🐛 Cómo reproducir el error

Debugeamos el _kernel.c_, que implementa funciones del utils del modulo, y alli es donde nos saltaron los errores

**Comment by RaniAgus** [comment]
¡Buenas! Primero que nada, asumo que el error es en realidad de **compilación**. Aclaro esto porque el uso del debugger es con el código en **ejecución**, o sea, posterior a haber compilado exitosamente. 

Dicho esto, en C no pueden hacer `#includes` circulares (o sea, incluir A->B, B->C y C->A), ni tampoco es recomendable incluir archivos ".c" ya que justamente incluyen muchas declaraciones de variables que, si se incluyen en más de un archivo, el compilador les puede arrojar un error de doble definición.

En la guía de buenas prácticas pueden encontrar más tips sobre cómo modularizar el código: https://docs.utnso.com.ar/guias/programacion/buenas-practicas#modularidad

¿Cómo pueden solucionarlo?

Primero, quitaría este include de `kernel.h`:

```c
#include "kernel_utils.c"
```

Si esto no lo resuelve, agarraría todas las definiciones que necesitan ambos archivos y las dejaría en un tercer header que sea incluido por ambos. De esta forma ya no habría más dependencias circulares ya que te queda: A->C y B-C.

Saludos
