### ISSUE TITLE
Estrategia de hilos en el Kernel

### ISSUE THREAD

**Issue by KirkSH** [sisoputnfrba/foro#3743]
Hola. Mis dudas son sobre cómo armar los hilos para el Kernel.

1)  ¿Es necesario que mientras se está realizando unas de las operaciones solicitadas por consola, el kernel sea capaz de empezar otra operacion por consola? (osea, ¿es necesario tener hilos bajo demanda para cada operación por consola solicitada?)
¿O simplemente se puede poner un ciclo y que realize una y luego otra?

2)  ¿Está bien tener un hilo que se ocupe de recibir las syscalls desde el cpu, otro que planifique en corto plazo, y otro qué maneje el quantum?

**Comment by Champa123** [comment]
Me sumo a la consulta del compañero, venia a consultar cual es el comportamiento esperado a la hora de interactuar con la consola. Por ejemplo: si tengo la plani detenida puedo crear procesos y luego iniciarla? 
En mi comprension no deberia poner el estado en NEW pero actualmente bloqueo el hilo de la consola en ese step, deberia poder iniciar multiples procesos por mas que no finalice el paso de agregarlos a la cola de NEW? 
Lo mismo con otras operaciones, por ejemplo finalizar un proceso tambien lo dejo bloqueado en el step de encontrar el pcb y moverlo a la cola de EXIT.

**Comment by iago64** [comment]
Buenas! Cómo va?

Respecto al punto 1, podrían tener un ciclo que procese una operación atras de la otra, pero te tengo que hacer una consulta respecto a punto de la consola, cuanto tardarías en procesar una instrucción de consola? 
Te lo pregunto porque nosotros asumimos que el iniciar proceso por ejemplo es solamente eso, crear el pcb, ponerlo en new y despues que los planificadores hagan su trabajo en segundo plano y la consola ya esta lista de nuevo.

El punto 2, si, pueden tener **todos los hilos que necesiten**, traten de no crear hilos por crearlos, pero si a uds les sirve y les ayuda tener esa división esta mas que perfecto.

Sobre la pregunta de @Champa123 Idealmente si, la consola debería poder crear nuevos procesos y dejarlos en NEW, ya que el detener la planificación es que no hay transiciones entre estados.

Saludos.-

**Comment by KirkSH** [comment]
Ok. Muchas gracias. Si, es ínfimo el tiempo que se tarda procesando una instrucción de consola.
