### ISSUE TITLE
dudas sobre el checkpoint 2 

### ISSUE THREAD

**Issue by mSpadoni** [sisoputnfrba/foro#3744]
hola buenas noches, para este checkpoint en el modulo de memoria, tenemos que hacer la parte del enunciado "esquema de memorias y estructuras" o únicamente leer el archivo del pseudocódigo??

**Comment by mefederico** [comment]
Hola buenas! 

Unicamente se pide que el modulo sea capaz leer el archivo y responderle a CPU cual es la siguiente instrucción

`esquema de memorias y estructuras` queda para el siguiente checkpoint que lo van a poder resolver con lo que empiezan a ver en el teoría ahora mismo

Saludos!

**Comment by mSpadoni** [comment]
gracias, y otra duda con la parte de comunicación con kernel, CPU y I/O, no hay que hacer cada una de las funcionalidades,no??
ósea por ejemplo con finalizar un proceso en donde tenemos que liberar el espacio de memoria de un proceso, eso no se hace en esta entrega, no??

**Comment by mefederico** [comment]
Claro, las funciones que queden por fuera del checkpoint no requieren implementarse, ni tampoco la mensajeria necesaria para estas funcionalidades

**Comment by mSpadoni** [comment]
joya, muchas gracias

**Comment by iago64** [comment]
Buenas! 
Si la duda esta resuelta cierren el issue.
Saludos.-
