### ISSUE TITLE
DUDA EXIT

### ISSUE THREAD

**Issue by nicolasreypc** [sisoputnfrba/foro#3745]
Buenas, tenia la duda de si hay que liberar los recursos de un proceso tambien cuando este llega a exit por condiciones normales (intruccion EXIT), o se entiende que el proceso cuando termina en condiciones normales ya ha liberado todos los recursos que tenia asignados?

**Comment by iago64** [comment]
Buenas! Cómo va?

No importa el motivo por el que llegue a EXIT, siempre tienen que liberar los recursos que le queden asignados.

Saludos.-
