### ISSUE TITLE
Duda ajuste de tamaño de proceso (resize)

### ISSUE THREAD

**Issue by nicolasreypc** [sisoputnfrba/foro#3746]
Buenas, tengo la duda de si el valor pasado a resize es el nuevo tamaño del proceso en bytes o de si es el tamaño a ampliarse en caso de ser positivo, y a reducirse en caso de ser negativo (Siempre en bytes). 
Lo modele de la primera manera, entendiendo que si el proceso ocupa 32 bytes y en cpu se ejecuta resize 16, el tamaño del proceso pasara a ser 16.
En caso de ser de la segunda forma se deberia ejecutar resize -16, por si no me explico bien.

**Comment by LeandroCarbajales** [comment]
Buenas!
Es como tenés modelado, el tamaño que se pasa es el valor final, no se pasarán valores negativos.

**Comment by nicolasreypc** [comment]
Muchas gracias!
