### ISSUE TITLE
Duda registros cpu en PCB

### ISSUE THREAD

**Issue by KirkSH** [sisoputnfrba/foro#3749]
Hola. En la parte de PCB del enunciado, refiriéndose a los registros del cpu, menciona:

_"Registros de la CPU: Estructura que contendrá los valores de los registros de uso general de la CPU."_

con **registros de uso general** se refiere exclusivamente a los terminados en 'X', (AX, BX, etc.) ¿verdad?
Osea, quedan excluidos el SI y el DI.

**Comment by f-and** [comment]
Buenas Kirk! No te preocupes mucho por eso, considera que son todos los registros del CPU, por lo que el SI y el DI tambien estarian en el PCB, por que sino no lo podrias persistir, o peor aun generarias problemas como un proceso modificandole a otro estos registros.

**Comment by LeandroCarbajales** [comment]
Como dato agrego que igualmente SI y DI son registros de propósito general :)

**Comment by KirkSH** [comment]
Oka. Gracias.
