### ISSUE TITLE
tipo de datos de las instrucciones

### ISSUE THREAD

**Issue by mSpadoni** [sisoputnfrba/foro#3751]
hola, tengo una duda con el pseudocodigo, el problema que tengo es que no se que tipo de dato va tener la instrucción o sus componentes, ya que por ejemplo puedo tener una instrucción  SET AX 1 o SUM EDX EBX, y EDX y AX son tipos de datos diferentes y por ende no puedo guardar los 2 al mismo tiempo en una estructura, debería usar void*  paracada 1??.

y otra duda es con programan counter, ósea esto debe contener una especie de identificador para la siguiente instrucción o contiene la instrucción tal cual??

**Comment by f-and** [comment]
Buenas Spadoni, para contestar cada pregunta:
1. Si te queres hacer un poquito de lio con los structs [haaaay una manera de tener mas de un tipo y que vaya variando](https://en.cppreference.com/w/c/language/union), pero en general no se si la solución es meterse con structs, considera que C puede ser muy suelto con los tipos, y que van a estar manejando solo 2 tipos de datos (uint8_t (que es basicamente un char ;) )y uint32_t), por lo que por ejemplo el siguiente codigo anda perfecto:

```c
#include <stdio.h>
#include <stdint.h>

int main()
{
    uint32_t test1 = 1;
    uint8_t test2 = 2;
    uint8_t test3 = test1 + test2;
    char test4 = 'a';
    test2 = test4;
    printf("%d %d %d", test1 + test2, test3, test4);
    return 0;
}
```

2. Program Counter es como se ve en Arquitectura, es un contador nada mas, este va a ser utilizado por Memoria para traerle la linea especificada de codigo pero esto no significa que haya alguna conexión mas profunda entre ambos.

**Comment by mSpadoni** [comment]
no entendi lo del codigo

**Comment by mSpadoni** [comment]
osea que unit_32 y unit_8 son un char y para extraerlos puedo directamente usar una variable tipo char??

**Comment by f-and** [comment]
Lo que apunto con el codigo es que C sabe manejar los distintos tipos de datos entre ellos, podes sumar un uint32_t (osea un int sin signo de 32 bits) con un uint8_t (int sin signo de 8 bits) y no habria problema en la mayor parte de los casos, y que un char es un [caracter ASCII](https://elcodigoascii.com.ar/) para C por lo tanto se puede comparar a un uint8_t, porque tienen el mismo tamaño.
Y para la pregunta, no, no son un char sino que el uint8_t tiene el mismo tamaño que el char, pero no el uint32_t, por lo que no podrias usar un char para extraer el uint32_t.

**Comment by mSpadoni** [comment]
y SUM por ejemplo que es??

**Comment by mSpadoni** [comment]
entonces por ejemplo podría guardar cada una de estas instrucciones en una lista y luego cuando paso el programan counter a la memoria buscar en esta lista la instrucción necesaria, esta bien??

**Comment by f-and** [comment]
Si, totalmente, como ustedes guarden estas instrucciones no es un problema, lo unico que se necesita es que se envien una por una de Memoria al CPU.

**Comment by mSpadoni** [comment]
ahora, perdón por preguntar mucho, pero sigo sin entender bien el tema del program counter, se que contiene la dirección de memoria de la próxima instrucción a ejecutar pero no entiendo como identificaría mis instrucciones en el programa, se podría usar una especie de identificador para cada instrucción??

**Comment by f-and** [comment]
No hay problema, estamos para ayudar, el PC vos tenes que verlo como un contador nada mas, siguiendo el ejemplo de la lista, cada numero va a tener asignado una instrucción respectiva, pero esto por la linea de código, siguiendo el ejemplo del enunciado:
```
SUM AX BX
SUB AX BX
MOV_IN EDX ECX
MOV_OUT EDX ECX
```
Cuando se carguen en la lista, considerando que empieza en 0, cada linea va a tener un número asociado:
0 = SUM AX BX 
1 = SUB AX BX
2 = MOV_IN EDX ECX
3 = MOV_OUT EDX ECX

Por lo tanto cuando CPU le pida a Memoria una instrucción, pasandole el Program Counter valiendo 0, Memoria le tendria que devolver la instrucción "SUM AX BX", despues si le pide la instrucción con Program Counter 3, le enviaria la instrucción "MOV_OUT EDX ECX".

**Comment by mSpadoni** [comment]
joya, muchisimas gracias y tene linda tarde
