### ISSUE TITLE
Duda peticiones de kernel a memoria

### ISSUE THREAD

**Issue by GonzaloFernandez20** [sisoputnfrba/foro#3753]
Hola buenas tardes! con mi grupo nos surgió una duda respecto al manejo de peticiones entre Kernel y Memoria.
Cuando kernel solicita la creación de un nuevo proceso a Memoria, podría crear seguidamente otro proceso antes de que memoria confirme que se cargaron las instrucciones o es secuencial? es decir, crea un proceso, recibe la confirmación y recién ahí puede crear otro proceso, de modo que se bloquea consola hasta la confirmación.

**Comment by f-and** [comment]
Buenas Gonzalo! La parte de preparar el proceso del lado de Memoria se haria despues de la creación del mismo, considera que, por ejemplo, si mandamos un Script por el comando `EJECUTAR_SCRIPT` que abra dos procesos, secuencialmente, estos van a entrar en el planificador a largo plazo y recien ahi se enviarian uno por uno a memoria, por eso tendrias una cola de procesos en NEW para que se vayan preparando en Memoria y mandando a READY cuando recibamos el OK de Memoria, pero de esto ya se encargaria el PLP, no la consola interactiva.

**Comment by GonzaloFernandez20** [comment]
Muchas gracias!!
