### ISSUE TITLE
Solicitar instrucciones de Memoria

### ISSUE THREAD

**Issue by beluromeo** [sisoputnfrba/foro#3754]
Hola buenas tardes, disculpen la molestia pero ya que con mis compañeros nos dividimos las tareas para realizar el tp, las ultimas que me tocaron a mi fueron la de Solicitar instrucciones de Memoria y Ejecutar un ciclo básico de instrucción. Con la primera mencinada es con la que tengo dudas ya que no logro entender bien lo que tengo que hacer. Disculpen nuevamente seguro es algo no muy complicado pero prefiero preguntar y hacerlo bien a que hacer algo que no sea y perjudicar a mi equipo.

### 📔 Citas del enunciado/videos
Solicitar instrucciones de Memoria y Ejecutar un ciclo básico de instrucción

**Comment by iago64** [comment]
Buenas! Cómo va?

Uds en memoria van a tener los diferentes archivos con los scripts de prueba que tienen una instrucción por cada linea, entonces el solicitarle la instrucción a memoria lo que hace es decirle de que archivo y que línea del archivo deberían obtener.
El número de línea lo van a tener de la mano del Program Counter (Registro PC de la CPU).

Respecto al ciclo de instrucción es un poco los pasos que estan en el enunciado:
- En primer lugar hacer el Fetch de la instrucción, es decir, pedirle a memoria.
- En segundo lugar decodificar que instrucción es, esto lo pueden saber ya que las líneas de texto que les va a devolver memoria las pueden separar por espacios y el primer string que obtienen es la instrucción
- En tercer lugar lo que tienen que hacer es ejecutar la instrucción propiamente dicha, aca va a depender de la instrucción que detectaron en el paso 2, para saber que tienen que hacer
- Por último en 4to lugar tienen que checkear si el módulo Kernel les envió alguna interrupción.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas @beluromeo !
Les sirvió la respuesta de @iago64 o pudieron verlo en soporte?

**Comment by LeandroCarbajales** [comment]
Cierro el issue por inactividad, cualquier cosa lo vuelven a abrir.
