### ISSUE TITLE
pequeña duda sobre el uso de la consola con distintos hilos

### ISSUE THREAD

**Issue by nicolasvultaggio** [sisoputnfrba/foro#3755]
Buenas, estaba siguiendo con el módulo de interfaces, y me surgió una duda:

Como se entera la interfaz que debe desconectarse? Yo había pensado en que la interfaz realice paralelamente todo el procesamiento funcional que sea necesario, y que en el hilo principal, se encargue de esperar el ingreso de algun comando por consola para liberar toda la información usada en el programa (como por ejemplo, cerrar los sockets que necesite, etc.) , el tema con esto es, como usan distintos hilos la consola? si son dos hilos del mismo proceso (en este caso la interfaz), usan la misma consola? Supongo que en ese caso, la consola sería como un recurso que se otorga al hilo, y que por lo tanto habría que sincronizar con mutua exclusión, para que dos hilos distintos no requieran usar la consola al mismo tiempo.

O, al momento de hacer la prueba, se puede abrir una consola para cada hilo? de forma que no tengan que sincronizarse. Esto es posible?

**Comment by FredeHG** [comment]
Hola buenas!

Simplemente vamos a hacer `ctrl + c` o cerrar la terminal donde este ejecutando y listo

Saludos!

**Comment by iago64** [comment]
Buenas!

Si por la consola te referis a leer desde el teclado en una terminal, solo 1 hilo puede bloquear la terminal a la vez.
Si tu pregunta viene por el lado de escribir, ahi si no hay  problema, no hace falta que sincronicen nada, al igual que para los logs.

Saludos.-

**Comment by nicolasvultaggio** [comment]
gracias!, sí, me refería a la primera opción, buen finde!
