### ISSUE TITLE
Problema al enviar procesos de Kernel a Memoria

### ISSUE THREAD

**Issue by lucasciola1** [sisoputnfrba/foro#3756]
Buenas, estoy teniendo un problema a la hora de enviar una estructura "nuevoProceso" hacia memoria. Antes de copiar los valores al buffer, las variables se encuentran en su valor correcto. Luego de enviar, cuando memoria recibe y deserializa, el path_lenght queda en 0, haciendo que tampoco se pueda recibir el path.

### 📝 Código relevante
```C
void solicitudProceso(){
    char* input = malloc(sizeof(input));
    input = readline("Ingrese el Path con las instrucciones: ");
    nuevoProceso* new = malloc(sizeof(nuevoProceso));
    new->path = input;
    new->path_lenght = strlen(input);
    new->PID = ultimo_pid;
    ultimo_pid++;
    enviarProcesoMemoria(new,fd_memoria);
```

```C
void enviarProcesoMemoria (nuevoProceso* proceso, int socketDestino){
    //Creamos un Buffer
    t_buffer* buffer = malloc(sizeof(t_buffer));
    //Calculamos su tamaño
    buffer->size = sizeof(uint32_t)*2 + proceso->path_lenght +1;
    buffer->offset = 0;
    buffer->stream = malloc(buffer->size);
    //Movemos los valores al BUFFER
    memcpy(buffer->stream + buffer->offset, &proceso->PID, sizeof(uint32_t));
    buffer->offset += sizeof(uint32_t);
    // Para el nombre primero mandamos el tamaño y luego el texto en sí:
    memcpy(buffer->stream + buffer->offset, &proceso->path_lenght, sizeof(uint32_t));
    buffer->offset += sizeof(uint32_t);
    memcpy(buffer->stream + buffer->offset, proceso->path, proceso->path_lenght);
    //Creamos un Paquete
    t_paquete* paquete = malloc(sizeof(t_paquete));
     // Podemos usar una constante por operación
    paquete->codigo_operacion = CREAR_PROCESO;
    paquete->buffer = buffer; 
    //Empaquetamos el Buffer
    void* a_enviar = malloc(buffer->size + sizeof(uint8_t) + sizeof(uint32_t));
    int offset = 0;
    memcpy(a_enviar + offset, &(paquete->codigo_operacion), sizeof(uint8_t));
    offset += sizeof(uint8_t);
    memcpy(a_enviar + offset, &(paquete->buffer->size), sizeof(uint32_t));
    offset += sizeof(uint32_t);
    memcpy(a_enviar + offset, paquete->buffer->stream, paquete->buffer->size);
    // Por último enviamos
    send(socketDestino, a_enviar, buffer->size + sizeof(uint8_t) + sizeof(uint32_t), 0);

    // No nos olvidamos de liberar la memoria que ya no usaremos
    free(a_enviar);
    free(paquete->buffer->stream);
    free(paquete->buffer);
    free(paquete);
}
```
Por el lado de memoria
```C

t_paquete* recibirPaquete (int socketCliente){
    t_paquete* paquete = malloc(sizeof(t_paquete));
    paquete->buffer = malloc(sizeof(t_buffer));
    // Primero recibimos el codigo de operacion
    recv(socketCliente, &(paquete->codigo_operacion), sizeof(uint8_t), 0);
    // Después ya podemos recibir el buffer. Primero su tamaño seguido del contenido
    recv(socketCliente, &(paquete->buffer->size), sizeof(uint32_t), 0);
    paquete->buffer->stream = malloc(paquete->buffer->size);
    recv(socketCliente, paquete->buffer->stream, paquete->buffer->size, 0);
    log_info(memoria_logger, "Nuevo paquete recibido");
    return paquete;
}
```
```C
void deserializarPaquete (t_paquete* paquete){
    //Deserializamos el Payload
    nuevoProceso* proceso = malloc(sizeof(nuevoProceso));
    void* stream = paquete->buffer->stream;
    // Deserializamos los campos que tenemos en el buffer
    memcpy(&(proceso->PID), stream, sizeof(uint32_t));
    stream += sizeof(uint32_t);
    // Por último, para obtener el nombre, primero recibimos el tamaño y luego el texto en sí:
    memcpy(&(proceso->path_lenght), stream, sizeof(uint32_t));
    stream += sizeof(uint32_t);
    proceso->path = malloc(proceso->path_lenght);
    memcpy(proceso->path, stream, proceso->path_lenght);

    log_info(memoria_logger,"Se recibio el Proceso");
    free(paquete);
    return proceso;

}
```

### 🐛 Cómo reproducir el error
El debugger  en el momento en que la variable que se le pasa como parametro a enviarProcesoMemoria es:

![image](https://github.com/sisoputnfrba/foro/assets/164528763/7343a7f5-4a01-4c24-bf09-776c43f8453e)

y al recibirlo memoria :

![image](https://github.com/sisoputnfrba/foro/assets/164528763/85923901-e2bd-4da8-8296-8374ac747e56)

**Comment by lucasciola1** [comment]
Buenas, ahi probes eso, la variable "a_enviar" antes del send, se encuentra asi:
![image](https://github.com/sisoputnfrba/foro/assets/164528763/d0364010-9b68-4643-9b63-f5386e209577)
Y al recibirse el buffer en memoria:
![image](https://github.com/sisoputnfrba/foro/assets/164528763/53db1674-4b0a-4b60-8f40-9ee2ad3a3d86)

**Comment by lucasciola1** [comment]
Ahh, disculpa, ahora te los adjunto!
Antes del send:
![image](https://github.com/sisoputnfrba/foro/assets/164528763/84e76a3b-fa77-4fb7-8be2-15e2a59b7486)
Cuando memoria recibe el paquete:
![image](https://github.com/sisoputnfrba/foro/assets/164528763/fe4002ea-c705-4342-8751-cd211445cb02)

**Comment by f-and** [comment]
Buenas, para saber, codigo de proceso y el buffer size llegan bien? Y si se enviaran sin el buffer?

**Comment by f-and** [comment]
Ah ignora esa segunda era mas por si llegaba todo bien, te hago otra consulta, el codigo de operación lo recibis recien en recibirPaquete?

**Comment by lucasciola1** [comment]
Si, lo recibo junto a todo el paquete en esa funcion.

**Comment by f-and** [comment]
Ok, y para saber, que estoy buscando descartar todo, el codigo CREAR_PROCESO, es distinto de 0? Para saber si no te esta llegando solo 0s al principio y el resto queda como información basura

**Comment by lucasciola1** [comment]
Buenas es de un typedef enum, no se exactamente como poder saber si es 0 o no. Gracias

**Comment by mefederico** [comment]
Te paso a explicar como leer la trama hexa que compartiste y lo que creo que esta pasando, de tu lado vas a tener que ver en el código si lo que digo esta bien

Primero lo que tenes a la izquierda es la memoria en Hexa (cada par de caracteres es 1 byte) por eso el programa te lo separa

Primero el código de operación CREAR_PROCESO es el primer valor de tu enum? 

Porque pregunto esto?
Porque en `recibirPaquete` lo primero que lees es un `sizeof(uint8_t)` eso es un 1 byte (un par de HEXA) entonces asumo que es el primer valor de tu enum codigo_paquete o whatever le hayan puesto de nombre

Luego leen 4 bytes (uint32_t) eso lo ves como 14 00 00 00 (little endian)
Así que es 14 hexa que leído como decimal es 20, y en enviar paquete si no cuento mal eso esta bien
PID -> 4 
path_length -> 4
path -> archivo.txt\0 -> 12
= 20

entonces seguimos 4 más (el PID) imagino que es 0
4 más 0B 00 00 00 -> little endian 00 00 00 0B -> 0B -> 11  = archivo.txt sin el +1, en algún lado les falta agregarlo o lo sumaron en un lado y en otro no

y si leen 11 más tienen el texto archivo.txt

Excelente mas o menos del lado antes de enviar está todo legible

Pero del otro lado??? 
Estaría interesante ver si el size se esta pudiendo leer bien o directamente lee 0


Sabiendo que la longitud de lo que envías recomiendo mucho sacar cualquier código del medio y leer directo del socket y ver en crudo que llega

```C
void* puntero;
recv(socket_cliente, puntero, {tam de lo que enviaron}, MSG_WAITALL);
```

El tamaño que están enviando si no me fallan las matematícas es 20 + 1 + 4 = 25

Así que leen eso y fíjense con el debugger si pueden hacer lo mismo que hice yo antes en el lado del Kernel pero ahora en el lado de memoria

Ahora estoy medio complicado con el laburo así que no le pude dar mucha forma a la respuesta
https://github.com/sisoputnfrba/foro/issues/3662 les dejo un issue parecido donde me inspire más


Pero ahora el álbum recomendado es [immunity](https://www.youtube.com/watch?v=sVefn-AXoZw)

Saludos!

**Comment by mefederico** [comment]
Me falto decir lo que creeeeeo que esta pasando es que no están enviando bien la data, el `paquete->buffer->size` antes de enviar chequearia si esta bien ese size, también veo que usan medio indiscriminado el buffer->size vs el paquete->buffer->size, tendria cuidado que en todo momento tengan los valores esperados

Y si es del otro lado, me parece raro porque viendo el código se ve bien a simple vista

**Comment by lucasciola1** [comment]
Buenas, ahí estuve probando hacer el recv con el size que sabemos que nos están enviando y el binario es el siguiente:

![image](https://github.com/sisoputnfrba/foro/assets/164528763/03f5643b-68fe-44bb-a044-140ae9cc41c6)

También chequee los tamaños de buffer->size y paquete->buffer->size y los dos están en 20 , es decir, el valor correcto, al que luego se le suman 5 bytes por las estructuras del paquete.

**Comment by f-and** [comment]
Para saber Lucas, no hay ningun send anterior a este que se haga? Porque si justamente te estan llegando datos basura puede ser algun dato anterior que haya quedado sin recibir, o enviado erroneamente a memoria.

**Comment by mefederico** [comment]
Para agregar a la pregunta, le hiciste malloc a `puntero` me falto eso en mi codigo

**Comment by lucasciola1** [comment]
> Para agregar a la pregunta, le hiciste malloc a `puntero` me falto eso en mi codigo

No lo habia hecho, ahi probe y el bin es este:
![image](https://github.com/sisoputnfrba/foro/assets/164528763/84182a86-b97a-4b91-ac85-d1aca0dddb96)



> Para saber Lucas, no hay ningun send anterior a este que se haga? Porque si justamente te estan llegando datos basura puede ser algun dato anterior que haya quedado sin recibir, o enviado erroneamente a memoria.

Si, antes esta esta funcion: 
```
void enviarHandshake (handshake codop, int socketDestino){
	void* buff = malloc(sizeof(uint8_t));
	send(socketDestino, buff ,sizeof(u_int8_t), 0);
}
```

y por el lado de memoria: 

```
void recibir_handshake (int socketCliente){
    handshake* codop = malloc(sizeof(uint8_t));
    //Recibimos el codigo de operacion
    recv(socketCliente, &codop, sizeof(uint8_t), 0);
    return codop;
}
```

**Comment by lucasciola1** [comment]
Ahi saque el send y recv que estaban antes de este, ahora el bin al recibir el proceso en memoria es este:
![image](https://github.com/sisoputnfrba/foro/assets/164528763/dbb13d86-5a37-414c-9db2-85d3d9e39101)

**Comment by f-and** [comment]
Lucas, si podes pasate mañana por el soporte para que lo veamos en vivo, porque honestamente no estaria viendo que puede ser el error. Va de la mano de que estas recibiendo información basura en vez de los datos que necesitas, pero esta información no pareceria salir de un lugar en especifico

**Comment by LeandroCarbajales** [comment]
Buenas! @lucasciola1 
Pudieron resolver esto en soporte?
