### ISSUE TITLE
Duda instruccion MOV_IN

### ISSUE THREAD

**Issue by uriGrif** [sisoputnfrba/foro#3757]
Tengo una duda sobre la funcion MOV_IN. Supongamos que mi memoria tiene paginas de 4 bytes, y yo quiero leer un dato que se encuentra en la direccion logica 2, (es decir, justo en la mitad de la primera pagina).

Si yo tengo las siguientes instrucciones en un programa:
SET AX 2
MOV_IN EAX AX

Asi yo quiero guardar lo que haya en la posicion 2 de la primera pagina (ignoremos el calculo de direccion fisica) en el registro EAX, que tiene 4 bytes. Entonces, me trae los 4 bytes necesarios para llenar el registro o 1 solo byte? Porque si quisiera traer los 4, los primeros 2 estarian en un frame, y los otros 2 estarian en otro frame, obligándome a recalcular las direccion fisica.

Un problema similar podria ocurrir con un MOV_OUT, tambien usando registros de mas de un byte.

### 📔 Citas del enunciado/videos
MOV_IN (Registro Datos, Registro Dirección): Lee el valor de memoria correspondiente a la Dirección Lógica que se encuentra en el Registro Dirección y lo almacena en el Registro Datos.

### 💭 Soluciones posibles
1. La memoria siempre lee y escribe de a un byte, entonces si hiciera las instrucciones de arriba, me quedaria el registro EAX con 3 bytes vacios. Y si lo hiciera con un MOV_OUT, truncaria el valor del registro de 4 bytes
2. Busco los 4 bytes, pero para cada uno tendria que recalcular la direccion fisica a ver si, por estar en otra pagina, esta en otro frame completamente distinto.

**Comment by GonTurri** [comment]
Pregunta adicional relacionado con esta, cuando nos enfrentamos a un dato que ocupe mas de una pagina ,si bien dice que tenemos que manejarlo nosotros, no nos queda bien claro el intercambio entre memoria y cpu.
porque aca el compañero entiendo que para cualquier acceso a memoria hay 2 mensajes involucrados: 
1) le pido el acceso a la tabla de paginas cpu le manda nro pagina memoria le devuelve a cpu el marco
2) cpu le manda para escribir a la memoria con el marco obtenido

yo pensaba que lo podia hacer todo en memoria pero me parece que lo correcto teoricamente como lo hace el so pero para todas las lecturas/escrituras multipagina la verdad que se vuelve bastante tedioso,
si no otra opcion un poquito mas facil es que la memoria te devuelva todo tu tabla de paginas (no se si el enunciado lo permite)
y tambien para todo lo que es tema interfaces te la complica bastante

**Comment by iago64** [comment]
Buenas! Cómo va?

Respecto a la pregunta de MOV_IN (y que aplica también a cualquier operación con memoria como MOV_OUT, COPY_STRING, etc) en el enunciado en la parte de MMU se aclara que:

> Es importante tener en cuenta en este punto que una Dirección Lógica va a pertenecer a una página en cuestión, pero el contenido a leer o escribir puede ser que ocupe más de una página

Y luego del ejemplo también hay una oración que cierra el punto diciendo:

> Es trabajo del grupo contemplar y manejar estos casos correctamente.

Con lo cual ahi, la opción de leer solo 1 byte, descartada por completo, y la segunda opción de leer de a 1 byte, puede ser posible, no es la óptima, pero puede funcionar, capaz si hacen algunos cálculos extra pueden ir leyendo de a porciones más grandes.


Respecto a la pregunta de @GonTurri, es responsabilidad de la MMU hacer los cálculos de las direcciones, capaz si sabes de antemano que lo que queres leer / escribir ocupa más de una página, podes pedirle las direcciones de las N páginas que tenes que leer / escribir y en base a eso realizar todos los cálculos que hagan falta.

Saludos.-

**Comment by GonTurri** [comment]
Ok! creo que voy entendiendo un cachito más pero me gustaría tenerlo más claro, entonces:

Desde la CPU calculo de Antemano cuantas páginas voy a querer leer o escribir. Le mando n sends a memoria pidiendo todos los marcos que vaya a usar 
Y después si implemento un mensaje que sea solo "escribir marco" o "leer marco" también tengo que mandar ese n veces 

Está bien pensada así la lógica ?? O hay una manera de agruparlo un poquito más. Viendo algunas implementaciones vi que usan **memcpy()** para ir escribiendo en la ram pero no creo que te puedas pasar de un marco ahí

**Comment by iago64** [comment]
Buenas! Cómo va?

El tema de hacer N `send()` para obtener las direcciones es una forma, otra que también puede leer o escuchar de algún compañero es que le mandan en un solo `send()` todas las páginas de las cuales quieren obtener el marco y lo copado es que ambas implementaciones están bien (siempre y cuando tengan el log obligatorio de los accesos a tabla de páginas)

Después a la hora de escribir, pueden mandarle a la memoria los fragmentos a escribir en cada marco con la dirección física que calcularon, el tamaño de lo que tiene que escribir en esa dirección física y el contenido a escribir y de nuevo, pueden hacer uno por uno o pueden hacerlo todo en un solo mensaje, ahi por favor no se la compliquen de mas, busquen la forma que mas fácil les resulte.

Saludos.-
