### ISSUE TITLE
Uso de registros en instrucciones. Direcciones lógicas.

### ISSUE THREAD

**Issue by elpanchi05** [sisoputnfrba/foro#3758]
Buenas! Nos encontramos con varias dudas con respecto a los registros y direcciones lógicas. No queremos perder de vista ciertos casos posibles pero tampoco queremos perder tiempo contemplando casos que no son necesarios.

Las DL tienen un tamaño fijo? Se pueden alojar en cualquier registro?
El tamaño de página siempre es múltiplo de 4 bytes? O puede ocurrir que sea menor al de un registro?

Específicamente MOV_IN/MOV_OUT: admiten cualquier registro?
En MOV_IN, se lee siempre una página o se lee la cantidad de páginas equivalente al tamaño del registro destino?
En MOV_OUT, se escribe la cantidad de páginas equivalente al tamaño del registro origen? 

Nuestra idea es que CPU solicite los marcos de las páginas a leer/escribir y los envíe a memoria junto a los contenidos, si corresponde. El buffer tendría sucesivos [Marco|Contenido] para una escritura. Si hubiera que escribir menos de una página (cuándo ocurriría, exceptuando el caso de COPY_STRING?), el último contenido estaría precedido de su tamaño. Memoria solo accedería a la tabla de páginas cuando CPU le pide los marcos.

### 💭 Soluciones posibles
Creemos que lo más normal sería que el tamaño de página sea múltiplo de 4 bytes y el de las direcciones lógicas 4 bytes. En cuanto a los registros, según el archivo de instrucciones de ejemplo de la consigna, cualquier registro puede aparecer en cualquier instrucción, lo cual nos trae las dudas mencionadas.

**Comment by iago64** [comment]
Buenas! Cómo va?

Las direcciones lógicas pueden almacenarse en cualquier registro, lo bueno es que podés asignarle un valor de un `uint8_t` a un `uint32_t`, esto lo podés revisar rápido con un programita del estilo de:

```c
#include <stdio.h>
#include <stdint.h>

int main()
{
    uint8_t ax = 4;
    uint32_t eax = 0;
    printf("El valor de AX es %d y el valor de EAX es %d \n", ax, eax);
    eax = ax;
    printf("El valor de AX es %d y el valor de EAX es %d \n", ax, eax);
    return 0;
}
```

Las instrucciones MOV_IN y MOV_OUT admiten cualquier registro y uds tienen que poder ver si el registro es de 1 byte o de 4 bytes.

Por último, la idea es que si leen o escriben en la memoria, le pasen la dirección exacta (base del frame + desplazamiento) y no todo el frame, ya que uds no saben que mas hay en ese frame al momento de leer o escribir y no tiene sentido traerse todo a CPU.

Saludos.-

**Comment by elpanchi05** [comment]
Me equivoqué. Sí, en realidad enviamos las direcciones físicas. Perfecto, muchas gracias! :)
