### ISSUE TITLE
Problema con Visual Studio

### ISSUE THREAD

**Issue by JuanTerri** [sisoputnfrba/foro#3759]
No se me abre visual studio de ninguna manera, usando la consola, dando doble click, dando click derecho y aprentando abrir. Lo elimino lo quiero reinstalar y me sale descarga fallida.
Saque el VS del escritorio y a la hora de querer volver agregarlo también me tira un error.
Todo esto sin que yo haya hecho ningun cambio en configs ni nada, me estuvo andando perfecto hasta hace 3 horas donde no me dejaba ejecutar el VS, entonces quise cerrar y volver a abrir y nunca mas abrió.

Uno de los errores que me aparece es cuando quiero abrirlo "Failed to execute default terminal emulator"
Otro de los errores cuando lo quise volver a agregar a escritorio (el acceso directo) fue "Unable add launcher to desktop, error splicing file: No space left on device " como si no tuviera espacio, lo cual me parece absurdo.

**Comment by RaniAgus** [comment]
Buenas, ¿si lo intentás ejecutar desde la consola qué te aparece? El comando es:
```
code
```

Sino, también podés probar de desinstalarlo e instalarlo como snap:

```
sudo apt remove code
sudo snap install code --classic
```

Saludos
