### ISSUE TITLE
Leer el archivo de pseudocodigo

### ISSUE THREAD

**Issue by mSpadoni** [sisoputnfrba/foro#3761]
hola buenas noches, estaba trabajando en el modulo de memoria y me agarraron dudas con este codigo

```C
void atender_kernel_dispatch()
{
    t_buffer *un_buffer;
    bool control_key = 1;
    while (control_key)
    {
        int cod_op = recibir_operacion(socket_kernel_dispatch);
        switch (cod_op)
        {
        case MENSAJE:
            //
            break;
        case PAQUETE:
            //
            break;
        case RECIBIR_PCB:
           un_buffer=recibir_buffer(socket_kernel_dispatch);
           atender_recibir_pcb(un_buffer);
           destruir_buffer(un_buffer);
        case -1:
            log_error(cpu_logger, "Se desconecto kernel-dispatch");
            control_key = 0;
            break;
        default:
            log_warning(cpu_logger, "Operacion desconocida de kernel-dispatch");
            break;
        }
    }
};
```

**Comment by mSpadoni** [comment]
lo que tiene que hacer el código es leer una linea del pseudocodigo y guardar lo que leyó en interrupción para posteriormente agregarla a una lista, y así con todas las líneas, funcionaria??

**Comment by mSpadoni** [comment]
pregunto por que siempre use structs con archivos y no estoy muy seguro como hacerlo con un string

**Comment by iago64** [comment]
Buenas! Cómo va?

Te hago una pregunta, ¿En que parte de todo ese código que pegaste, estas abriendo el archivo?
Por otro lado, ¿Qué variable sería interrupción? No la veo escrita en el código.
Si lo que necesitas es abrir un archivo y leerlo, arranquemos por eso, arranca investigando funciones como [`open()`](https://man7.org/linux/man-pages/man2/open.2.html) o [`fopen()`](https://man7.org/linux/man-pages/man3/fopen.3.html) y después funciones del estilo de lectura de archivos como [`fread()`](https://man7.org/linux/man-pages/man3/fwrite.3.html).

Lo copado de C es que vos podes leer toda la estructura de un saque y guardarte eso en una variable y despues tratar esa variable como si fuese un gran string al cual le podes ir pasando funciones como [`string_spit()`](https://github.com/sisoputnfrba/so-commons-library/blob/d22eb0076cc863bcbb7edbdf47ef43e6d434ffc6/src/commons/string.h#L200) y con eso separas las líneas del archivo de pseudocódigo.

Saludos.-

**Comment by mSpadoni** [comment]
perdón, me equivoqué de código y no me di cuenta
```
#include "abrir_archivo.h"

void abrir_archivo(const char *file)
{
    FILE *pseudocodiogo = fopen(file, "rb");
    if (pseudocodiogo != NULL)
    {
        char *instruccion;
        lista_de_instrucciones = list_create();
        while ((fread(&instruccion, (strlen(instruccion) + 1), 1, pseudocodiogo)) == 1)
        {
            list_add_in_index(lista_de_instrucciones, contador, instruccion);
            contador++;
        }
    }
    else
    {
        log_error(mem_logger, "No se pudo abrir el archivo");
        exit(1);
    }

    fclose(pseudocodiogo);
};
```

**Comment by mSpadoni** [comment]
también me equivoque con interrupción es instrucción y el file es la ubicación del archivo de pseudocodigo, entonces si agrego esa función de string_spit() para separar las lineas, estaría bien??

**Comment by mSpadoni** [comment]
y otra cosa,  esa función es un char**, que es eso exactamente??

**Comment by mSpadoni** [comment]
y algo mas, leí la función que me pasaste y no comprendo si te genera una especie de arreglo con las partes que separa, es eso?

**Comment by f-and** [comment]
Buenas! La mejor manera de fijarse si esta bien es probando que ande jajaja!
Yendo a lo tangible igual, a simple vista pareceria bien, hay algunas cosas como el fopen con modo "rb" ya que estas abriendo algo que no se va a leer en binario y tiene terminadores de linea (\n), y tambien te recomendaria usar [feof()](https://man7.org/linux/man-pages/man3/feof.3.html) en vez de la condición en el while para claridad del codigo, pero en general se veria bien, habria que probarlo unicamente.

**Comment by RaniAgus** [comment]
¡Buenas! Me sumo solo para decir que si les sirve pueden usar el debugger para seguir la función línea por línea y ver que vaya cumpliendo con lo esperado. Saludos
