### ISSUE TITLE
Tabla de páginas vacia

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3762]
Buenas,
Cuando se crea un proceso en Kernel dice que debe tener una tabla de páginas "vacía". Nosotros creamos una tabla que tiene en cada posición "Marco" y "Validez" inicializados en -1s y 0s respectivamente. La cantidad de entradas de la tabla se corresponde con el nro de marcos total de la memoria. ¿Esto estaría bien? Nos confunde un poco lo del "vacío", por eso pensamos en que el hecho de que un proceso tenga todos los marcos en -1 y validez en 0 se lo podría interpretar de esa manera y por eso hicimos todo inicializado en esos valores.

**Comment by iago64** [comment]
Buenas! Cómo va?

Creo que se te estan mezclando un par de conceptos, la tábla de páginas es una estructura propia de cada proceso, donde vos deberías tener 1 entrada por cada página que puede tener tu proceso, entonces lo que te termina quedando es una tabla mas o menos asi:


|Página|Frame|
|---|---|
|0|4|
|1|5|
|2|45|

Entonces si vos te creas una tabla con una entrada por cada frame disponible, medio que invertis el orden y es un bardo despues, porque tenes que recorrer un monton para encontrar el número de página, de hecho, esta "tabla" la pueden modelar con una `t_list` de números donde despues pueden hacer un `list_get()` y obtener por posición en la lista que frame corresponde y casualmente las listas de las commons arrancan en 0, con lo cual es una correlación directa con el número de página ;)

Saludos.-

**Comment by rood8592** [comment]
Entiendo, lo trajimos de la teoría lo de la cantidad de entradas, que nos dijeron que el tamaño debía ser el suficiente para que cada proceso pudiera direccionar toda la memoria. Por ahí escuchamos mal también igual, de todas formas, seguiremos el consejo de la lista.
Gracias.

**Comment by iago64** [comment]
Buenas! Cómo va?

No dije que estuviera del todo mal la implementación, simplemente se las quise simplificar un poco con las `t_list`, pero si ya lo tienen andando, pueden seguir con eso.

Respecto al bit de validez, si tienen una entrada por cada página valida no les hace falta, ahora si mantienen la tabla de páginas del tamaño de toda la memoria, si tiene sentido porque van a tener entradas inválidas.

Saludos.-

**Comment by rood8592** [comment]
Perfecto, muchas gracias.

**Comment by FredeHG** [comment]
Hola buenas! 

Si la duda esta saldada cerremos el issue!

Saludos!
