### ISSUE TITLE
Hilos para el quantum de round robin

### ISSUE THREAD

**Issue by AgustinaGuitman** [sisoputnfrba/foro#3763]
Buenas, intentando hacer el round robin me puse a leer los issues del foro y veo que para controlar el quantum de los procesos que se planifican por RR se hace un hilo aparte (como por ejemplo este issue #2838 ). Tengo dudas de para qué serviría hacer ese hilo nuevo. Nosotros pensamos en usar calculate_delta_ms para que tome el tiempo y se lo reste al quantum.

### 📝 Código relevante
```c
void* ejecutar_porRR(){
		t_temporal* temporal = 0;
		pcb* proceso_a_ejecutar = (pcb*) queue_pop(cola_de_ready);
		int64_t quantum_remanente = proceso_a_ejecutar->quantum - calculate_delta_ms(temporal);
		
		while(quantum_remanente>0){
			pasar_a_running(proceso_a_ejecutar);
		}
		if(tiempo_remanente == 0){
			desalojar_fin_quantum(proceso_a_ejecutar);
		}
	}
```

**Comment by RaniAgus** [comment]
¡Buenas! No es válido que el hilo esté constantemente chequeando si terminó el quantum porque sería una espera activa: el proceso Kernel estaría usando ciclos de la CPU de la VM únicamente para preguntar "¿terminó el quantum?", "¿terminó el quantum?". Y esto, el tener picos de uso de CPU, es motivo de desaprobación.

Entonces, la solución sería que un hilo se bloquee por un cierto tiempo (con un `sleep()`) hasta que llegue el fin de quantum y recién ahí envíe la interrupción si es que el proceso todavía no desalojó la CPU. Esto lo tendrías que hacer en un hilo aparte porque el proceso podría desalojar la CPU antes del fin de quantum, por lo que no es válido esperar a que termine el quantum para atender el desalojo.

¿Se entiende la idea?

Saludos

**Comment by AgustinaGuitman** [comment]
Se entendió perfecto, muchas gracias!
