### ISSUE TITLE
Hora limite para entrega checkpoint 2

### ISSUE THREAD

**Issue by Lopez-AN** [sisoputnfrba/foro#3764]
Buenos dias.

Lo dicho en el título, quisieramos saber cual es la hora limite para taggear el checkpoint 2.
Nuestra duda es si se cierra a las 0:00 del sabado (o sea hay que terminarlo a la noche del viernes)
O si tenemos todo el sabado para terminar la entrega.

Gracias

**Comment by RaniAgus** [comment]
¡Buenas! Misma respuesta que para el checkpoint 1 (https://github.com/sisoputnfrba/foro/issues/3544), el tiempo límite es el sábado a las 23:59:59:999. Saludos

**Comment by Lopez-AN** [comment]
Muchas gracias por la aclaracion!
