### ISSUE TITLE
Duda Memoria de Instrucciones y CPU

### ISSUE THREAD

**Issue by yaanel** [sisoputnfrba/foro#3765]
Hola! Buenas, tenemos una duda acerca de qué módulo es el indicado para cambiar las instrucciones leídas como un char a una instrucción. Porque habíamos entendido que la memoria, al tener una parte llamada memoria de instrucciones, era quien realizaba esta traducción por así decirlo y le enviaba a CPU la instrucción ya en formato instrucción. Sin embargo, leímos un issue #3754 y no estamos tan seguros ahora. Agrego, nosotros entendimos que era Memoria quien hacía esto ya que en la sección Memoria de Instrucciones se habla de tener las "estructuras necesarias" para poder mandar las instrucciones

**Comment by yaanel** [comment]
Agrego, nosotros entendimos que era Memoria quien hacía esto ya que en la sección Memoria de Instrucciones se habla de tener las "estructuras necesarias" para poder mandar las instrucciones.

**Comment by f-and** [comment]
Buenas yaanel, para contestar a tu consulta, la idea seria que el CPU la decifre, como se especifica en el ciclo de instrucción del mismo:

> Esta etapa consiste en interpretar qué instrucción es la que se va a ejecutar y si la misma requiere de una traducción de dirección lógica a dirección física.

La mención de estructuras necesarias se da ya que ustedes pueden manejar la instrucción como ustedes quieran, enviarla en varios strings, enviarla en un string entero, enviarla con un header, etc., pero al llegar al CPU, este si o si debe recibirlas como strings ya que, considerando el caso que le envie la instrucción `SUM AX BX`, decompuesta en "formato instrucción" simplemente seria codigos (SUM = 1, AX = 3, BX = 0 por ejemplo), porque no le pueden llegar funciones u operaciones por mensaje, solo le puede llegar información a decodificar.

**Comment by yaanel** [comment]
Perfecto, muchas gracias! Cierro el issue :D
