### ISSUE TITLE
Envio de instrucciones a CPU

### ISSUE THREAD

**Issue by FranEnriquez** [sisoputnfrba/foro#3766]
Buenas!
Quería consultar una duda que nos surgió con respecto a la forma en la que memoria envía las instrucciones a la CPU.
Una vez leído el pseudocódigo, entiendo que memoria debe mandar las líneas de instrucciones sin interpretar (solo como strings), pero ¿también debe indicar que numero de línea corresponde a cada una o eso es algo que debe hacer la CPU al interpretarlas?
Desde ya muchas gracias!!
Espero haber sido claro jeje.

**Comment by iago64** [comment]
Buenas! Cómo va?

Es la CPU la que le va a pedir las instrucciones a memoria y es la CPU la que les va a indicar que línea del archivo le tienen que mandar.

Saludos.-

**Comment by FranEnriquez** [comment]
Ahhhhh, perfecto!
Muchisimas gracias y buenas noches!!
