### ISSUE TITLE
Duda sobre log "ingreso a ready" 

### ISSUE THREAD

**Issue by Elias318** [sisoputnfrba/foro#3767]
Buenas, tenia duda si en la parte que dice "LISTA DE PIDS hay que mandar el PID de cada proceso que se manda a ready o si ponemos la cantidad de procesos que se mandan a esta cola. 

### 📔 Citas del enunciado/videos

_Ingreso a ready: "Cola Ready COLA: [LISTA DE PIDS]" _

**Comment by tomasmartinez02** [comment]
Buenas!
En el log que mencionas, cada vez que un proceso ingrese a la cola de ready, se debe listar los PIDs de aquellos procesos que se encuentren en el mismo estado. En el caso del VRR hay dos colas, es por esto que el enunciado marca:

> Ingreso a Ready: “Cola Ready COLA: [LISTA DE PIDS]”

Entonces, en el caso del algoritmo VRR debes especificar a cuál de las 2 colas del estado ready ingresó el proceso y listar aquellos que se encuentren encolados en la misma.
Saludos!

**Comment by LeandroCarbajales** [comment]
Buenas @Elias318 !
Te sirvió la respuesta de @tomasmartinez02, te resuelve la duda?

**Comment by LeandroCarbajales** [comment]
Cierro el issue por inactividad, cualquier cosa lo vuelven a abrir.
