### ISSUE TITLE
¿Dónde se alojan las instrucciones?

### ISSUE THREAD

**Issue by julienf04** [sisoputnfrba/foro#3769]
### 📔 Citas del enunciado (del módulo de Memoria)

1. Al momento de recibir la creación de un proceso, la memoria de instrucciones deberá leer el archivo de pseudocódigo indicado y generar las estructuras que el grupo considere necesarias para poder devolver las instrucciones de a 1 a la CPU según ésta se las solicite por medio del Program Counter.

2. Un espacio contiguo de memoria (representado por un void*). Este representará el espacio de usuario de la misma, donde los procesos podrán leer y/o escribir.

### ❓ Duda

Cuando el módulo de Memoria deba leer un archivo de pseudocódigo perteneciente a un proceso, sus instrucciones (junto con sus parámetros) deberían estar alojadas en el espacio contiguo de memoria del usuario (el void*), o deberían estar alojadas en otras estructuras que decidamos con mi grupo por fuera de ese espacio contiguo, o es decisión nuestra?

**Comment by FredeHG** [comment]
Hola buenas! 

Tienen que usar estructuras por fuera del espacio contiguo de memoria

Saludos!
