### ISSUE TITLE
problemas con list_find

### ISSUE THREAD

**Issue by mSpadoni** [sisoputnfrba/foro#3770]
```C

t_proceso *encontrar_proceso(t_list *lista, uint32_t pid_cpu){
    void* soy_proceso_buscado(t_proceso * proceso){
        return (proceso.pid == pid_cpu);
     }

     list_find(lista,(void*)soy_proceso_buscado)
};
```

**Comment by mSpadoni** [comment]
hola, estaba haciendo este codigo para buscar un proceso en una lista y me gustaria saber si la logica esta bien

**Comment by FredeHG** [comment]
Hola buenas!

Como te imaginaras los ayudantes no somos compiladores de C con vida, ya me gustaría también te digo, por lo que la mejor forma de saber si una lógica esta bien es probándola, create una lista con n t_procesos y fíjate si encuentra uno en particular

Por lo demás, a simple vista se ve bien el código

Saludos!

**Comment by mSpadoni** [comment]
perdoname, lo pude resolver y me olvide de cerrar el issues
