### ISSUE TITLE
Condiciones para que un proceso pase a blocked

### ISSUE THREAD

**Issue by AgustinaGuitman** [sisoputnfrba/foro#3771]
Buenas, estamos tratando de cerrar el checkpoint 2 y queríamos preguntar si la única condición para que un proceso entre al estado bloqueado es que una interfaz de I/O se quiera conectar al kernel y que se cumplan las condiciones para que se pueda conectar. 

### 📔 Citas del enunciado/videos

> Al recibir una petición de I/O de parte de la CPU primero se deberá validar que exista y esté conectada la interfaz solicitada, en caso contrario, se deberá enviar el proceso a EXIT.
> En caso de que la interfaz exista y esté conectada, se deberá validar que la interfaz admite la operación solicitada, en caso de que no sea así, se deberá enviar el proceso a EXIT.

> De cumplirse todos los requisitos anteriores, el Kernel enviará el proceso al estado BLOCKED

>

**Comment by iago64** [comment]
Buenas! Cómo va?

Las condiciones son 2:
- Tienen la interfaz conectada previo a que llegue la petición de IO
- La interfaz acepta la operación que quieren hacer

Si **no** se cumplen ambas condiciones, el proceso pasa a EXIT en lugar de a BLOCK.

Saludos.-

**Comment by mefederico** [comment]
Hola!

Pasaba por acá casualmente solo por agregar, también un proceso puede estar BLOCK por el manejo de recursos como se especifica en el [enunciado](https://docs.google.com/document/d/1-AqFTroovEMcA1BfC2rriB5jsLE6SUa4mbcAox1rPec/edit#heading=h.o4dclr11f6x2) 

Saludos!

**Comment by RaniAgus** [comment]
¡Buenas @AgustinaGuitman! ¿Te sirvieron las respuestas de Dami y Fede? Saludos

**Comment by AgustinaGuitman** [comment]
Buenas, se entendió perfecto. Muchas gracias
