### ISSUE TITLE
Consola Interactiva Kernel: Finalizar Proceso

### ISSUE THREAD

**Issue by FedericoGSantoro** [sisoputnfrba/foro#3772]
Buenas, es una pregunta rapida ya que el enunciado no aclara demasiado y revisando algunos issues no vi ninguno que respondiera mi duda.
Comento, probamos muchas formas para realizar este finalizar proceso, cada una generaba un problema y cuando probabamos otra solucion tambien encontrabamos un nuevo problema. 

Mi pregunta es como se realizaria este finalizar proceso, tiene que ser una finalizacion instantanea o puede tardar? (Por ejemplo tengo proceso 1, 2 y 3 en la cola, quiero eliminar el 3, tiene que ser al instante o puedo esperar a que haga el 1 lo que tiene que hacer, despues el 2 y cuando ve que hace con 3 lo elimina) 

Y segundo, alcanza con que lo envie a la cola de exit (que se encarga de liberar la memoria) o lo elimino instantaneamente sin enviarlo a esa cola y esperando que sea su turno en dicha cola de exit?

### 📔 Citas del enunciado/videos
>Finalizar proceso: Se encargará de finalizar un proceso que se encuentre dentro del sistema. Este mensaje se encargará de realizar las mismas operaciones como si el proceso llegara a EXIT por sus caminos habituales (deberá liberar recursos, archivos y memoria).
Nomenclatura: FINALIZAR_PROCESO [PID]

**Comment by ArielRotolo** [comment]
Perdón que me meta 😁 pero tengo la misma duda, más que nada porque al usar las Queue de la librería commons no se puede acceder a un elemento en la mitad de la cola sin sacar a todos los que están por delante. 

Por lo que al querer eliminar un proceso que está en la mitad de la cola de ready no se puede hasta que llegue el momento de ejecutar ese proceso.

**Comment by iago64** [comment]
Buenas! Cómo va?

El FINALIZAR_PROCESO tiene que ser instantáneo y tienen que mandarlo a EXIT para que libere todos los recursos.
Respecto al tema de usar las `t_queue` de las commons que pregunta @ArielRotolo, tienen 2 opciones:

1- Juegan a las Torres de Hanoi 
2- En lugar de `t_queue` usan `t_list` y aprovechan el [`list_remove_by_condition`](https://github.com/sisoputnfrba/so-commons-library/blob/d22eb0076cc863bcbb7edbdf47ef43e6d434ffc6/src/commons/collections/list.h#L201)

Saludos.-

**Comment by FedericoGSantoro** [comment]
Ok comento lo que hicimos a ver que tal parece.

Lo que hicimos fue detener la planificación para que los procesos no se muevan entre las colas, después en cada cola buscamos si estaba el proceso, pero accediéndolo no por la cola, si no por la lista dentro de la cola y usando esa 
[list_remove_by_condition](https://github.com/sisoputnfrba/so-commons-library/blob/d22eb0076cc863bcbb7edbdf47ef43e6d434ffc6/src/commons/collections/list.h#L201)  que decís.

Si esta ejecutándose en CPU, mandamos interrupción y agregamos el pid a una lista de procesos a terminar, cuando vuelve el pcb de CPU chequea si esta en la lista y si lo esta lo manda a EXIT.
El tema es cuando esta en las colas de cada interfaz entrada salida, debería revisar todas las colas o puedo hacer esto mismo y que el proceso antes de enviarlo a la interfaz lo mande a EXIT? Además que si ya lo esta ejecutando en alguna IO, debería esperar a que vuelva o como? 

Estamos perdidos con como implementar bien esto porque además tenemos un problema con semáforos, nosotros cuando creamos un pcb nuevo (porque iniciamos un proceso) hacemos un sem_post(&colaNew) y el hilo que maneja la cola de new tiene un sem_wait(&colaNew), entonces cuando creamos un pcb se desbloquea ese hilo que se fija si puede enviar el pcb de la cola de NEW a READY, el tema es el siguiente:
Imaginemos que tenemos 4 procesos en NEW por lo tanto tenemos el semáforo colaNew en 4, si nosotros eliminamos un proceso nos quedan 3 procesos en NEW pero igualmente nos queda el semáforo colaNew en 4, y cuando haga el 4 queue_pop va a tirar segmentation fault. Alguna ayuda de como encarar este problema?

**Comment by iago64** [comment]
Buenas! Cómo va?

Si justo se da la casualidad de que matamos algún proceso que está en una IO, simplemente esperen a que vuelva de la IO para mandarlo a EXIT, no hace falta que se compliquen tanto la vida.

Sobre el problema de los semáforos de la cola de new, se me ocurren al menos 2 alternativas:

1- La más simple, háganle el wait si matan a uno que está en NEW ya que eventualmente no deberían ir más allá de 0 porque tienen al menos 1 proceso en NEW que es el que están matando.
2- La menos amigable, armar una estructura custom que tenga un mutex, la queue y la cantidad de procesos y jugar con el hecho de bloquear el mutex según haga falta para que no le hagan `queue_pop()` a la queue de NEW.

Saludos.-

**Comment by FedericoGSantoro** [comment]
Okk entonces, para resumir, si el proceso esta en alguna cola de new o ready lo mando a exit instantaneamente, si esta en exec mando una interrumpcion a cpu y cuando vuelva lo mando a exit y si esta en la cola de bloqueados espero a que la IO me indique que termino de procesar la peticion de ese proceso para mandarlo a exit no? Si esto esta bien podes cerrar el issue y gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Tal cual, no pudiste hacer un mejor resumen de como manejar el finalizar proceso desde la consola del kernel.

Saludos.-
