### ISSUE TITLE
Problema con el codigo de operacion de CPUa Memoria! 

### ISSUE THREAD

**Issue by EzeeSavva** [sisoputnfrba/foro#3773]
Buenas tardes, estaria teniendo complicaciones con respecto a los hilos de la CPU y Memoria, que estoy tratando de pasarle el IP desde CPU hacia Memoria a traves de un paquete, que haciendo el debugger, llega al codigo de operacion, y no se recibe correctamente despues del recv, es decir, que el codigo de operacion queda en 0, es decir, que returna -1, y nos da error. 

CPU:

MEMORIA: 
Esto es los hilos de memoria que ejecutan el atender_cliente.
```c
int esperar_cliente(int socket_servidor)
{
	// Quitar esta línea cuando hayamos terminado de implementar la funcion
	// assert(!"no implementado!");
	// Aceptamos un nuevo cliente

	while (1)
	{
		pthread_t thread;
		int *fd_conexion_ptr = malloc(sizeof(int));
		*fd_conexion_ptr = accept(socket_servidor, NULL, NULL);
		pthread_create(&thread, NULL, (void *)atender_cliente, fd_conexion_ptr);
		log_info(logger, "Se conecto un cliente!");
		pthread_detach(thread);
		log_info(logger, "Cliente desconectado!");
	}
	return socket_servidor;
}
```
En donde atender_cliente conlleva: 
```c
int atender_cliente()
{
	int contador=0;
	t_list* lista;
	while (1) {
		int cod_op = recibir_operacion(socket_cliente);
		switch (cod_op) {
		case MENSAJE:
			recibir_mensaje(socket_cliente);
			break;
		case PAQUETE:
			lista = recibir_paquete(socket_cliente);
			log_info(logger, "Me llegaron los siguientes valores:\n");
			list_iterate(lista, (void*) iterator);
			break;
		case PETICION_INSTRUCCION:
		    t_buffer* buffer = recibiendo_paquete(socket_cliente);
		    atender_peticion_de_instruccion(buffer);
		    t_proceso* proceso = crear_proceso(pid, sizeof(buffer));
	
			break;
		case -1:
			log_error(logger, "el cliente se desconecto. Terminando servidor");
			return EXIT_FAILURE;
		default:
			log_warning(logger,"Operacion desconocida. No quieras meter la pata");
			break;
		}
	}
}
```
Hasta aca ejecuta correctamente, el problema es cuando entra a atender_cliente y hace `int cod_op = recibir_operacion(socket_cliente);`
que estaria entrando y:
```c
int recibir_operacion(int *socket_cliente)
{
	int cod_op;
	if (recv(*socket_cliente, &cod_op, sizeof(int), MSG_WAITALL) > 0)
		return cod_op;
	else
	{
		close(*socket_cliente);
		return -1;
	}
}
```
devuelve -1, es decir que termina tirando un log de el cliente se desconecto.

CPU: 
Llama a la funcion:
```c
int atender_cpu_memoria(void)
{
	/* establecimiento de conexion con otros modulos */
	conexion_memoria = crear_conexion(ip_memoria,puerto_memoria);
	t_paquete* enviar_ip = crear_paquete_memoria();
	enviar_paquete(enviar_ip, conexion_memoria);
		int cod_op = recibir_operacion(conexion_memoria);
		t_buffer* unBuffer;
		switch(cod_op)
			{
				case PETICION_INSTRUCCION:
					unBuffer = recibiendo_paquete(conexion_memoria);
					atender_recepcion_de_instruccion(unBuffer);
					free(unBuffer);
					break;
			}
		//Eliminar paquete
	eliminar_paquete(enviar_ip);
}
```
que le envia el paquete a memoria, y luego, cuando lo envia, llega el paquete a memoria y ocurre el problema.
```c
t_paquete* crear_paquete_memoria(void)
{
	t_paquete* paquete = malloc(sizeof(t_paquete));
	paquete->codigo_operacion = PETICION_INSTRUCCION;
	crear_buffer(paquete);
	return paquete;
}
```
Esta es la funcion de crear el paquete de CPU, que PETICION_INSTRUCCION = 2. Es decir que tendria que llegarle un 2 a memoria para que entre al codigo de operacion en memoria.

Espero su respuesta atentamente.

**Comment by iago64** [comment]
Buenas! Cómo va?

Por favor no se olviden de formatear el código, porque si no es mas complicado aun seguir el texto del issue.
Respecto al tema de lo que les está pasando, tengo algunas preguntas como para descartar el problema:

1. Debuguearon y vieron que **en todos** los mensajes están pasando bien los size de las cosas que están mandando?
2. Cuando el `recv()` les devuelve -1 significa que hubo un problema, sabían de la existencia de [`perror()`](https://man7.org/linux/man-pages/man3/perror.3.html) que les puede dar mas info acerca del error?
3. Tuvieron en cuenta que las funciones del TP0 están pensadas para enviar strings y que si por ejemplo no reciben todos los strings les queda basura en el buffer?

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @EzeeSavva! ¿Te sirvió la respuesta de Dami? Saludos

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, ante cualquier consulta pueden reabrirlo o abrir uno nuevo. Saludos

**Comment by EzeeSavva** [comment]
Buenas, disculpen no habia visto ninguno de sus mensajes, estuve un poco ocupado, utilize el perror luego de que me lo comentaran ya que no lo conocia, y me manda que el buffer esta vacio, el problema entonces es que no se esta enviando el mensaje correctamente, no?  Utilize el prror arregle eso, que al parecer lo hardcodea, ahora debugueandolo encuentro que llega el codigo de operacion correctamente, el size es = 0, el buffer llega todo bien, pero entra en -1, nose si sea problema de que el socket_cliente lo esta tomando mal.

![Codigo de op](https://github.com/sisoputnfrba/foro/assets/164695989/05f42cbe-aa1a-4768-a3a2-dfb03e8896c4)

Esto me tira en el debug, asi que nose que hacer jeje

**Comment by RaniAgus** [comment]
¡Buenas! Lo que comentaba Dami sobre `perror()` es que el truco de esta función es que te imprime por pantalla el error de la función anterior. Entonces, si `recv()` te devolvió `-1` vos podés hacer algo como:
```c
int bytes = recv(...);
if (bytes == -1) {
   perror("fallo en el recv");
}
```
Y por pantalla te va a mostrar algo tipo:
```c
fallo en el recv: Bad file descriptor
```

Por otro lado, volviendo un paso atrás veo lo siguiente:

Primero, están creando un hilo pasándole un puntero al socket por parámetro:
```c
int *fd_conexion_ptr = malloc(sizeof(int));
*fd_conexion_ptr = accept(socket_servidor, NULL, NULL);
pthread_create(&thread, NULL, (void *)atender_cliente, fd_conexion_ptr);
```

Luego, en `atender_cliente()` la función no recibe parámetros y en su lugar están usando una variable `socket_cliente` que no sé de dónde sale (entiendo que sería global).

Lo correcto sería recibir ese parámetro que pasaron y usarlo desreferenciándolo con `*`:

```c
int atender_cliente(int *fd_conexion_ptr) {
   int socket_cliente = *fd_conexion_ptr;
   free(fd_conexion_ptr);
   // ...
}
```


Saludos

**Comment by iago64** [comment]
@EzeeSavva Cómo va?

Te sirvió la respuesta de @RaniAgus?

Saludos.-

**Comment by EzeeSavva** [comment]
Buenas. si funciono la solución al el error, ahora estoy teniendo problemas para codear la parte de enviar el código de operación de la cpu a memoria, por al parecer lo recibe bien, pero no entra al case del switch, y pasa directamente a crear otro hilo y pasa a un recv de la cpu, un poco complejo entenderlo mas que nada ya que no están viendo el código, tal vez me conviene preguntarlo por una consulta por discord, pero cualquier cosa vuelvo a mandar una solicitud, desde ya muchas gracias por la solución y disculpen las molestias!!

**Comment by iago64** [comment]
Buenas!

Podes de ultima pasar el código y que lo veamos ya que estamos a lunes y el soporte virtual y/o presencial va a ser el sábado.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue ya que lo vimos en soporte. Había un par de problemas:

1) Desde CPU se estaba haciendo `send()` de una cadena de 8 bytes con dos `int`: un código de operación `2` y un buffer size `0`

2) Del lado de Memoria, se estaba recibiendo al revés, o sea:

```c
		lista = recibir_paquete(socket_cliente);
		int cod_op = recibir_operacion(conexion_memoria);
```

Entonces al recibir paquete se interpretaba como si fuera un buffer de `2` bytes, y luego de leer esos 2 se quedaba bloqueado en `recibir_operacion()`.

3) Del lado de Memoria se esperaba recibir dos `int` con PID y PC pero CPU nunca los enviaba. Para eso estaría bueno tener una función tipo:

```c
void agregar_peticion_instruccion_a_paquete(t_paquete *paquete, int pid, int pc);
```

Que funcione similar a `agregar_a_paquete` pero con los parámetros correctos.

Saludos
