### ISSUE TITLE
funcionamiento del planificador a corto/largo plazo + Cola exit posible.

### ISSUE THREAD

**Issue by Dummatt** [sisoputnfrba/foro#3774]
¡Buenas noches! Tengo una duda con el enunciado, principalmente en la parte Kernel.
Suponiendo que en Kernel se separa la planificador de corto plazo y de largo plazo ¿Deberíamos de hacer que la liberación de Procesos SI O SI lo haga largo plazo, o lo puede hacer directamente corto plazo en el momento que un proceso pasa a estado EXIT?
También quería saber si se puede presentar un caso en donde dos o más procesos acaben en EXIT, bajo la idea de que el planificador de corto plazo planifica solamente con los procesos que están en la cola READY, y que de esta cola dos o más procesos podrían acabar en estado EXIT según la planificación (siempre en FIFO, rara vez en RR y VRR).

**Comment by iago64** [comment]
Buenas! Cómo va?

Respecto a quien manda al proceso a EXIT, no hay problema si lo hace el Planificador de Corto Plazo, siempre y cuando le avise al de largo plazo que le dejo disponible el espacio por si tiene procesos en NEW esperando por entrar.

Respecto a EXIT, es una queue, eventualmente va a tener varios procesos a lo largo de la ejecución, traten de no complicarsela mucho y usen una `t_list` de las commons para los estados y en el caso de EXIT, siempre que un proceso llegue a ese estado asegurense de pedirle a memoria que libere el espacio asignado y que el proceso no tiene tomado ningún recurso.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas @Dummatt ?
Te sirvió la respuesta de @iago64 ? Te resuelve la duda?

**Comment by papiness77** [comment]
Buenas, me sumo con una consulta relacionada al issue. Si o si tiene que haber una cola de exit? Yo lo que venia haciendo cuando un proceso llega a exit es sacarlo de la cola donde se encontraba y eliminar todas sus estructuras en kernel y en memoria. Osea en mi sistema no podrias imprimir los procesos que estan en exit. Saludos

**Comment by iago64** [comment]
@papiness77 Si, tiene que existir la cola de EXIT.

**Comment by papiness77** [comment]
Y antes de entrar a esa queue tengo que eliminar sus estructuras en memoria y verificar que no tenga recursos?

**Comment by iago64** [comment]
Buenas!

Si lo liberas antes o después de meterlo en la queue es más o menos lo mismo, lo importante es que queden en la cola de EXIT y liberen los recursos que tenían retenidos.

Saludos.-

**Comment by papiness77** [comment]
Y de esa cola en algun momento saco los procesos o se dejan ahi, hasta que termine de ejecutar el modulo?

**Comment by iago64** [comment]
Buenas!

Se quedan ahi hasta que matemos el proceso.

Saludos.-

**Comment by FredeHG** [comment]
Hola @papiness77 te sirvió la respuesta de Dami?

 Podemos cerrar el issue?

**Comment by papiness77** [comment]
Buenas, yo no cree el issue. Si me sirvio, muchas gracias!!

**Comment by LeandroCarbajales** [comment]
Genial, cierro el issue entonces :)
