### ISSUE TITLE
Creacion de IOs

### ISSUE THREAD

**Issue by Lisandrogq** [sisoputnfrba/foro#3776]
Buenas, tenemos una pequeña consulta respecto a las IOs.
Por lo que ví en varios issues, estas son distintos hilos de un mismo proceso, ahora, esto me genera algunas dudas:

Como se crean las IOs? por la terminal de este proceso?
No se volvería un tanto problematico el uso compartido de la terminal en la que corre el proceso? quiero decir, si varíos stdin/stdout quieren leer/escribir la terminal al mismo tiempo, o incluso si las IOs se crean por la terminal de este proceso, podría haber inconsistencias.

Es por esto que se me ocurre que distintas IOs serían distintos procesos de un mismo programa, pero no vi esta alternativa plasmada en ningun issue. 

Cual de las dos implementaciones sería la correcta?

**Comment by iago64** [comment]
Buenas! Cómo va?

Van a correr varios procesos de IO con sus respectivas configs y por lo tanto, van a tener que correrlos en terminales diferentes.

Saludos.-

**Comment by Lisandrogq** [comment]
Genial, gracias
