### ISSUE TITLE
Detener Planifiacion y Finalizar Proceso

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#3778]
Hola buenas. Tengo una duda sobre como van a detener la planificacion en las pruebas.

En mi caso la primera parte de todos los algoritmos de planificacion es asi: el lock mutex que esta en el medio se usa para detener la planicacion, el unlock se hace recien una vez que se envio el proceso a CPU y despues mientras el proceso esta en cpu, esta parte queda bloqueda por el semaforo `short_term_scheduler`, recien cuando vuelve de cpu se le hace un signal al `short_term_scheduler`. El problema es que cuando tengo un solo proceso y ese termina, al salir deja el signal al semaforo `short_term_scheduler` y entonces termina entrando en esta zona y lo frena el `sem_wait(&sem_ready);`. Lo frena ahi hasta que llega un proceso nuevo creado por consola, ahi recibe un signal y sigue el proceso. Pero en caso que no llegue un proceso por consola, sino que se ingrese DETENER_PLANIFICACION ahi se traba el hilo de consola. 
Cuando ingresan Detener Planificacion se hace un lock mutex al hilo planificadorCortoPlazo y tambien al de largo plazo(pero el de largo plazo no esta generando un problema). El problema se da aca porque este hilo ya hizo el lock y esta bloqueado dos lineas despues y no llega al unlock y de esta forma queda bloqueada la consola. El unico caso donde no pasa esto, es cuando se hace ingresa detener planificacion mientras el proceso esta ejectuandose en cpu.
 

```
void planificador_corto_plazo_Virtual_RoundRobin(){
    
    t_pcb *proceso = NULL;

    sem_wait(&short_term_scheduler_semaphore);//esto es para despertar al planificador de corto plazo
    pthread_mutex_lock(&m_planificador_corto_plazo);
    log_info(logger,"Paso el semaforo DetenerPlanifiacion y esta en Semwait(semReady)");
    sem_wait(&sem_ready); //aclaracion esto estaba dado vuelta antes, aclaracion hecha en fifo
    
```
Antes lo tenia al reves, primero los dos wait, y al final el mutexLock, pero de esta forma cuando eliminaba un proceso de ready o de la cola prioridad, no le podia hacer el wait al semaforo contador de procesos en ready desde el hilo de consola, porque en este hilo ya se habia bloqueado en el wait del semaforo contador ready esperando a que ingrese otro proceso a la cola de ready.

**Comment by iago64** [comment]
Buenas! Cómo va?

El objetivo de detener la planificación no es otro que el de poder tirar un PROCESO_ESTADO y no comernos la posibilidad de que justo estemos agarrando un proceso que esta cambiando de estado.

Las pruebas van a ser bastante similares a las de custrimestres anteriores, donde detener la plani era para iniciar varios procesos (aunque esto tambien lo podemos hacer desde el ejecutar script de la consola del kernel), listar los procesos por estados o para finalizar procesos si es que no pueden finalizar procesos sin detener la plani en el medio.

Saludos.-

**Comment by JoaquinCoaricona** [comment]
Buenas estuve viendo algunas pruebas del tp anterior y vi esta prueba:
![image](https://github.com/sisoputnfrba/foro/assets/112731246/4b3e6073-99a7-42f7-a764-7c5169699751)
En mi caso si yo espero a que finalicen los procesos no puedo pausar la planifiacion porque ya el hilo de planificador de corto plazo ya entro en ese mutexLock y la consola queda bloqueada. Pero tampoco podria dar vuelta ese mutex y poner primero el wait(sem ready) porque ese es el semaforo contador de procesos en ready y cuando elimino un proceso en ready le hago un wait para que este actualizado.

**Comment by iago64** [comment]
Buenas! Cómo va?

A veces el problema viene dado por el contexto de lo que esta pasando, si te fijas la linea inmediatamente siguiente a DETENER_PLANIFICACION, decía justamente `INICIAR_PROCESO MEMORIA_2 64 1 (Nota: Ejecutarlo 4 veces)` que es justo una de las cosas que aclaré en mi respuesta anterior que podemos hacerlo con el EJECUTAR_SCRIPT.

En esa misma prueba hay algo bastante interesante un par de línas mas abajo que es que detenemos la planificación, finalizamos procesos, cambiamos el grado de multiprogramación, iniciamos un nuevo proceso y reanudamos la planificación, esto es un poco el espíritu de iniciar / detener la planificación. Poder hacer cosas en el medio de la ejecución y que en el medio no tengamos cosas pasando que nos cambian el estado del sistema.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas @JoaquinCoaricona !
Te sirvió la respuesta de @iago64 ? Quedó resuelta la duda?

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, ante cualquier consulta pueden reabrirlo o abrir uno nuevo. Saludos
