### ISSUE TITLE
Sintaxis y semántica de los archivos de pseudocódigo

### ISSUE THREAD

**Issue by julienf04** [sisoputnfrba/foro#3779]
### Buenas!

Algunas dudas respecto a la sintaxis y semántica de los archivos de pseudocódigo:

1. ¿Un archivo de pseudocódigo puede tener saltos de línea sin ninguna instrucción o se considera un error de sintaxis? Por ejemplo, el siguiente pseudocódigo, ¿es válido?

    ```
    SET AX 1
    
    SET BX 1
    SUM AX BX
    
    EXIT
    ```

2. ¿Debemos poder manejar que se intente ejecutar una instrucción inexistente? Por ejemplo, el siguiente pseudocódigo, ¿es válido (en la tercer instrucción se asigna el PC en 10, pero el archivo solo tiene 4 instrucciones) y deberíamos poder hacer algo al respecto (como finalizar el proceso por ejemplo)?

    ```
    SET AX 1
    SET BX 1
    SET PC 10
    EXIT
    ```

3. ¿Puede ocurrir que se terminen las instrucciones de un archivo de pseudocódigo y nunca haya ejecutado un EXIT? Por ejemplo, el siguiente pseudocódigo, ¿es válido y deberíamos poder hacer algo al respecto (como finalizar el proceso por ejemplo)?

    ```
    SET AX 1
    SET BX 1
    SET CX 5
    ```
------------

En las pruebas preliminares no se da ninguno de estos casos, pero me surgió la duda de si deberíamos contemplarlos.

**Comment by iago64** [comment]
Buenas! Cómo va?

Cito el enunciado:
> Al momento de realizar las pruebas, ninguna instrucción contendrá errores sintácticos ni semánticos

Vos estas describiendo en el caso 1 un error sintáctico porque nunca aclaramos que podían tener espacios entre medio y en el caso 2 un escenario de errores semánticos ya que si el script tiene 4 instrucciones el PC como máximo debería llegar a 3 (considerando que siempre arranca en 0).
El caso 3 es el más realista ya que si por ejemplo revisas el repositorio de pruebas, hay un script que tiene el EXIT pero es una instrucción a la cual nunca vas a llegar ([script_solo_cpu_3](https://github.com/sisoputnfrba/c-comenta-pruebas/blob/main/preliminares/script_solo_cpu_3)). 

Saludos.-

**Comment by julienf04** [comment]
Gracias! Los casos 1 y 2 me quedaron claros, pero sigo con dudas del caso 3.

El ejemplo adjunto que dejaste no llegaría a EXIT porque se quedaría en un loop infinito, pero mi duda respecto al caso 3 sería otra.

------------

Volviendo al ejemplo del caso 3, donde el archivo tiene solo esas 3 instrucciones:

- Luego de ejecutar la tercera instrucción, el PC tendría el valor de 3 (porque comienza en 0).
- Cuando la CPU, en la fase fetch, le pida la cuarta instrucción a la memoria, no existiría esa cuarta instrucción, porque solamente tiene 3 instrucciones el archivo y no ejecutó ningún EXIT.

Por lo tanto, ¿se consideraría un error semántico que la CPU intente pedir una instrucción inexistente debido a que no encontró un EXIT antes para finalizar el proceso?

**Comment by iago64** [comment]
Buenas! Cómo va?

Releyendo mi respuesta, estuve medio flojo en la explicación.
La idea es que siempre van a tener la instrucción de EXIT aun en los casos como el que pase que nunca lleguen, y si no esta es un error semantico y van a tener total libertad de crearnos un issue diciendonos: **Esta mal la prueba** :smile: 

Saludos.-

**Comment by julienf04** [comment]
Muchas gracias! Ahora sí, clarísimo todo!
