### ISSUE TITLE
Consulta sobre el Modulo de Memoria y el acceso al espacio de usuario

### ISSUE THREAD

**Issue by AAMazzini03** [sisoputnfrba/foro#3780]
Buenas, tengo una consulta debido a que en el enunciado me dice que un log obligatorio es el siguiente:
Acceso a espacio de usuario: “PID: <PID> - Accion: <LEER / ESCRIBIR> - Dirección física: <DIRECCION_FISICA>” - Tamaño <TAMAÑO A LEER / ESCRIBIR>
Para los otros logs no tengo problema ya que recibo los PID, pero en estos 2 procesos no los he necesitado así que no lo había puesto como algo que me tenían que enviar CPU/IO cuando querían acceder al espacio de usuario.
Mi duda es la siguiente, ¿Qué tengo que hacer para obtener el PID?

### 📔 Citas del enunciado

Acceso a espacio de usuario
Esta petición puede venir tanto de la CPU como de un Módulo de Interfaz de I/O, es importante
tener en cuenta que las peticiones pueden ocupar más de una página.
El módulo Memoria deberá realizar lo siguiente:

Ante un pedido de lectura, devolver el valor que se encuentra a partir de la dirección física
pedida.

Ante un pedido de escritura, escribir lo indicado a partir de la dirección física pedida. En caso
satisfactorio se responderá un mensaje de ‘OK’.
Cada petición tendrá un tiempo de espera en milisegundos definido por archivo de configuración.

### 💭 Posible Solución

Lo mas sencillo me parece a mi que es agregarlo a la función de escribir/leer en espacio de usuario y que CPU/IO se encarguen de obtener el PID cuando quieran usar mi funcionalidad.

**Comment by iago64** [comment]
Buenas! Cómo va?

Asumimos que en todos los mensajes van a decir que proceso está solicitando las cosas, por lo que la respuesta más "simple" sería que agreguen el campo del PID en los mensajes.

Saludos.-

**Comment by AAMazzini03** [comment]
Gracias. Hago eso entonces.
