### ISSUE TITLE
Datos a guardar en memoria

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3781]
Buenas noches,
Teníamos una duda con respecto a memoria y es el tema de que datos yo puedo guardar en el void* de espacio de usuario, tengo entendido que puedo guardar cadena de caracteres, caracteres o números. Pregunto para que podamos definir si x dato entra en una página o no. Por ej, si tuviéramos pagina de 1 byte, el numero 260 no se podría guardar en una sola, necesitaríamos dos paginas, un carácter si se podría y una cadena se podría de a un carácter por página.
También queremos saber a que se refiere lo de que el espacio de usuario debe ser contiguo ya que lo mencionan bastante en la consigna ¿Cuál sería un ejemplo básico en donde no se este cumpliendo este requerimiento de consigna? Nosotros el espacio de usuario lo pensamos como un void* que tiene un malloc(cant_bytes_del_config) que se crea cuando se levanta memoria y trabajamos con ese void*.

**Comment by iago64** [comment]
Buenas! Cómo va?

Si, depende de uds saber que tamaño tienen que leer / escribir, igual si te pones a revisar en detalle, vas a encontrar que no son muchos los casos de uso:
- Todos los MOV_IN / MOV_OUT van a ser de 4 bytes, con la excepción de que el registro datos sea AX, BX, CX, DX donde pasan a ser de 1 byte 
- Los COPY_STRING y los IO_* tienen el tamaño como uno de los parámetros, asi que deberían encargarse de usarlo en la MMU para calcular las direcciones y despues enviarlo para donde sea que lo necesiten.

Saludos.-

**Comment by rood8592** [comment]
Y una ultima duda, en el ejemplo del ECX que pusiste que dividimos los 4 bytes en 2-2. ¿Existen herramientas de C que nos ayuden a manejar esa division o debemos manejarlo como cadena de bits? Colocando los primeros 2 bytes (16bits) del numero en una posicion de nuestra memoria y los otros 2 en otra posicion de memoria y a la hora de recuperar el numero tendriamis que concatenar los primeros 16bits con los otros 16 y así recuperar el numero.

**Comment by iago64** [comment]
Buenas! Cómo va?

Algo sumamente hermoso y a la vez doloroso de C es que todo es memoria y todo se puede "castear" y podes jugar con la aritmética de punteros, entonces por ejemplo podes hacer cochinadas como la siguiente y va a funcionar:

```c
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>

int main()
{
    
    uint32_t registro_ecx = 64;
    uint32_t registro_ecx_reconstruido = 0;
    
    void* registro_ecx_parte_1 = malloc(2);
    void* registro_ecx_parte_2 = malloc(2);
    
    void* registro_ecx_puntero = &registro_ecx;
    void* registro_ecx_reconstruido_puntero = &registro_ecx_reconstruido;
    
    memcpy(registro_ecx_parte_1, registro_ecx_puntero, 2);
    memcpy(registro_ecx_parte_2, registro_ecx_puntero + 2, 2);
    
    printf("El valor de ECX completo es: %d \n", registro_ecx);
    printf("El valor de ECX antes de reconstruirlo: %d \n", registro_ecx_reconstruido);
    
    memcpy(registro_ecx_reconstruido_puntero, registro_ecx_parte_1, 2);
    memcpy(registro_ecx_reconstruido_puntero + 2, registro_ecx_parte_2, 2);
    
    printf("El valor de ECX despues de reconstruirlo: %d \n", registro_ecx_reconstruido);

    return 0;
}
```
Si te fijas en el programa de ejemplo lo que hago basicamente es tener un `void*` para castear el `uint32_t` a algo con lo que puedo jugar y despues con un par de `memcpy()` resuelvo este problema de copiar el número de a partes, incluso si queres hacerlo mas cochino aún C te permite jugar con los datos y tener punteros a los mismos y castear la memoria de la siguiente manera y por ejemplo ver si estas guardando los valores en Little Endian o Big Endian que eventualmente al momento de reconstruir los datos:

```c
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>

int main()
{
    
    uint32_t registro_ecx = 2147483647;
    uint32_t registro_ecx_reconstruido = 0;
    
    void* registro_ecx_parte_1 = malloc(2);
    void* registro_ecx_parte_2 = malloc(2);
    
    void* registro_ecx_puntero = &registro_ecx;
    void* registro_ecx_reconstruido_puntero = &registro_ecx_reconstruido;
    
    memcpy(registro_ecx_parte_1, registro_ecx_puntero, 2);
    memcpy(registro_ecx_parte_2, registro_ecx_puntero + 2, 2);
    
    printf("El valor de ECX completo es: %d \n", registro_ecx);
    printf("El valor de ECX antes de reconstruirlo: %d \n", registro_ecx_reconstruido);
    
    uint16_t* medio_ecx_parte_1 = registro_ecx_parte_1;
    uint16_t* medio_ecx_parte_2 = registro_ecx_parte_2;
    
    printf("El valor de la primer mitad de ECX: %d \n", *medio_ecx_parte_1);
    printf("El valor de la segunda mitad de ECX: %d \n", *medio_ecx_parte_2);
    
    memcpy(registro_ecx_reconstruido_puntero, registro_ecx_parte_1, 2);
    memcpy(registro_ecx_reconstruido_puntero + 2, registro_ecx_parte_2, 2);
    
    printf("El valor de ECX despues de reconstruirlo: %d \n", registro_ecx_reconstruido);

    return 0;
}
```

E incluso si andas con ganas podes jugar con partirlo de a  pedacitos de 1 byte
```c
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>

int main()
{
    
    uint32_t registro_ecx = 2147483647;
    void* registro_ecx_puntero = &registro_ecx;
    
    printf("El valor de ECX completo es: %d \n", registro_ecx);
    
    uint8_t* ecx_parte_1_4 = registro_ecx_puntero;
    uint8_t* ecx_parte_2_4  = registro_ecx_puntero + 1;
    uint8_t* ecx_parte_3_4  = registro_ecx_puntero + 2;
    uint8_t* ecx_parte_4_4  = registro_ecx_puntero + 3;
    
    printf("El valor del primer 1/4 de ECX %d \n", *ecx_parte_1_4);
    printf("El valor del primer 2/4 de ECX %d \n", *ecx_parte_2_4);
    printf("El valor del primer 3/4 de ECX %d \n", *ecx_parte_3_4);
    printf("El valor del primer 4/4 de ECX %d \n", *ecx_parte_4_4);

    return 0;
}
```

Saludos.-

**Comment by rood8592** [comment]
Muchas gracias por los ejemplos! ¿Entonces sería valido utilizar este tipo se soluciones o similares y sería valido?. Y se podría implementar algo así:
```
uint32_t registro_ecx= 2147463345;
uint32_t registro_ecx_reconstruido = 0;
void* espacio = malloc(128);
void* registro_ecx_puntero = &registro_ecx;
void* registro_ecx_reconstruido_puntero = &registro_ecx_reconstruido;
memcpy(espacio,registro_ecx_puntero,2);
memcpy(espacio+126,registro_ecx_puntero+2,2);
//Reconstrucción
memcpy(registro_ecx_reconstruido_puntero, espacio, 2);
memcpy(registro_ecx_reconstruido_puntero + 2,espacio+126, 2);
//printear reconstruido
```

Esto lo pregunto porque entiendo que la pagina 0 puede estar en el frame 0 y la pagina 1 en el frame 120 por ej.

**Comment by rood8592** [comment]
Con respecto a lo de los bytes ¿eso ocurre tanto para lectura como escritura? Entiendo que si el registro pesa 4 bytes debo guardar 4 bytes (esto para el MOV_OUT), y qué sucede si lo que quiero leer lo quiero almacenar en un registro que pesa 4 bytes, también solo me debe importar el 4 y siempre leer 4? 
Lo que yo entiendo es:
MOV_IN AX EAX entonces voy a leer 1 byte sin excepción
MOV_IN EAX CX entonces voy a leer 4 bytes sin excepción

**Comment by iago64** [comment]
Buenas!

Aplica tanto para lecturas como para escrituras, vos tenes que poder guardar el registro en la memoria y despues al momento de leerlo tenes que poder reconstruirlo tal cual estaba antes de que lo lleves a memoria.

Saludos.-

**Comment by rood8592** [comment]
Perfecto, gracias!
