### ISSUE TITLE
Duda con las STDIN

### ISSUE THREAD

**Issue by EstebanHurtado0** [sisoputnfrba/foro#3782]
La direccion fisica indicada, se la envia kernel a entradasalida y entradasalida se la manda a memoria, o kernel se la indica directamente a memoria

### 📔 Citas del enunciado/videos

> Este texto se va a guardar en la memoria a partir de la dirección física indicada en la petición que recibió por parte del Kernel.

### 💭 Soluciones posibles

Kernel le envia la direccion a entradasalida y entradasalida manda el texto y la direccion a memoria

**Comment by LeandroCarbajales** [comment]
Buenas!
Kernel se la envía a la interfaz para que la misma luego pueda decirle a Memoria dónde guardar el texto ingresado.

**Comment by EstebanHurtado0** [comment]
Perfecto, muchas gracias!
