### ISSUE TITLE
Duda DETENER_PLANIFICACIÓN

### ISSUE THREAD

**Issue by thomyluca** [sisoputnfrba/foro#3783]
Buenas tardes, estamos teniendo dudas desarrollando el comando DETENER_PLANIFICACION. Al momento de detenerla, lo que estamos haciendo es cancelar/matar los hilos que manejan la planificación de corto y largo plazo. Al hacer esto nos surgen algunas dudas, es correcta esta implementación? o seria mas sencillo/mejor hacerlo con semaforos que no permitan al planificador de largo plazo continuar ejecutando?

Por otro lado al hacerlo con cancelacion de hilos nos surgen la duda de cuando hacerlo, ya que cuando detenemos la plani con un pcb ejecutandose y esperamos que vuelva de la cpu, cuando vuelve, si no lo pasamos a ninguna cola y lo dejamos en la de exec como dice la consigna, luego al reanudar la planificacion va a reanudar desde el principio y y no va a tener manera de desalojar ese pcb de exec pq no lo conoce, y de esta forma ejecutaria otro. 

### 📔 Citas del enunciado/videos
>Detener planificación: Este mensaje se encargará de pausar la planificación de corto y largo plazo. El proceso que se encuentra en ejecución NO es desalojado, pero una vez que salga de EXEC se va a pausar el manejo de su motivo de desalojo. De la misma forma, los procesos bloqueados van a pausar su transición a la cola de Ready.

### 💭 Soluciones posibles
Hacer un if cada vez que se inicie el planificador y si hay procesos en la cola de exec saltearse la parte de planificarlo por corto plazo y directamente atender el motivo de desalojo de este proceso. El tema es donde hacer que continue y como hacerlo, porque pasa que cuando detenemos y reanudamos la planificación, el hilo del quantum no se crea nuevamente (se crea uno por cada proceso que estaba en exec)

**Comment by kenzogrosvald** [comment]
Hola @thomyluca,

Desde mi punto de vista, es un despropósito que estes bajando y levantando hilos, si simplemente con un sem_wait en un hilo y luego un sem_post desde otro hilo podes bloquear y reanudar la planificación cuando tengas una necesidad de seguir planificando, dada la implementación apropiada. 

Tambien recorda que la planificación debe realizarse bajo determinados eventos, y no tiene que estár continuamente ejecutando sin razon porque ocupa recursos sin sentido.

Ojalá esto te ayude.

Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

Concuerdo en parte con lo que dice @kenzogrosvald de que es un poco mucho el matar hilos y levantarlos, pero tambien es una de las implementaciones posibles que vimos cuando diseñamos el TP.
La mayoría suele optar por jugar con semáforos para "bloquear" los hilos de forma controlada, pero si con el if que planteas funciona creo que funcionaría bastante bien, lo único que me preocupa un poco es el tema de los `recv()` que tienen en curso al momento de achurar los hilos, eso puede ser algo "aspero" si no lo controlan bien.

Saludos.-

**Comment by thomyluca** [comment]
Gracias a ambos! Probaremos de las 2 formas y veremos cual es la más eficiente, si surgen nuevas dudas reabro el issue.
Saludos!
