### ISSUE TITLE
Duda sobre implementación de interfaces

### ISSUE THREAD

**Issue by VinixHub** [sisoputnfrba/foro#3786]
Buenos días/tardes/noches a todo aquel que haya llegado a mi Issue.
**Mi consulta sobre la implementación de las interfaces es la siguiente:** 

Estuvimos leyendo sobre cómo se implementan correctamente las interfaces y lo que hicimos para el checkpoint 2 está terriblemente mal (jeje); lo que quiero consultar es si mi nuevo razonamiento sobre la implementación de las mismas sería el correcto.

Y no sabemos cómo implementar esta parte del enunciado correctamente (_para la interfaz genérica_):
> Al leer el archivo de configuración solo le van a importar las propiedades de:
>- TIPO_INTERFAZ
>- TIEMPO_UNIDAD_TRABAJO
>- IP_KERNEL
>- PUERTO_KERNEL

Lo que interpretamos es que cuando le solicitamos al módulo I/O hacer, en este ejemplo IO_GEN_SLEEP, solo le van a importar esas 4 propiedades, pero no entendemos porque esas 4; 'TIEMPO_UNIDAD_TRABAJO' se lo estamos enviando, en teoría, por parámetro, por ejemplo.

### 💭 Soluciones posibles
**Nuevo razonamiento:** gracias al issue #3733 nos quedó algo como:
1. Módulo I/O genera una interfaz con lo solicitado en el TP (config y nombre único) y lo envía a Kernel para que lo guarde.
2. CPU (cuando deba hacer uso de las interfaces), le solicita a Kernel que haga la operación que deba hacer (mandándole una interfaz hecha en el CPU y lo que deba mandar).
3. Kernel verifica que la interfaz que tenía guardada y la que le envían estén 'bien' y le envía a I/O que haga la operación solicitada

**Comment by iago64** [comment]
Buenas! Cómo va?

La solución posible esta muy bien.

Saludos.,-

**Comment by VinixHub** [comment]
Hola iago! joya, gracias por la respuesta!
Y sobre la 2da consulta?
