### ISSUE TITLE
Acceso a una dirección de memoria inválida

### ISSUE THREAD

**Issue by julienf04** [sisoputnfrba/foro#3787]
### Buenas!

Una duda con respecto al momento en el que un proceso intenta acceder a una dirección de memoria:

¿Qué pasaría si una instrucción de pseudocódigo intenta acceder a una posición de memoria inválida?

Por ejemplo, en el siguiente código se está intentando leer 4 bytes (porque EAX ocupa 4 bytes) a partir de la dirección lógica 8. Como debe leer 4 bytes, leería las direcciones lógicas 8, 9, 10 y 11, pero el proceso dispone solamente de 10 bytes de memoria de usuario, es decir, la última posición válida es la 9.

	RESIZE 10
    SET EBX 8
    MOV_IN EAX EBX
    EXIT

¿Qué deberíamos hacer ante esta situación, o directamente es un caso que nunca se debería dar en las pruebas?

**Comment by kenzogrosvald** [comment]
Hola @julienf04,

Es mi opinion que dado que estamos trabajando con una simulación de un sistema operativo con paginación simple, lo lógico sería que establezcas una verificación para contemplar este caso, y lances una excepción de `segmentation fault` cuando ocurra si la pagina a la que quiere acceder el proceso no le pertenece.

Lo mismo que sucedería en C.

Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

@julienf04 Quedate tranquilo que ese escenario no lo vamos a probar y no tiene sentido que te compliques con eso, ya que para complicarse tienen la posibilidad de que un registro les quede partido entre 2 páginas.

@kenzogrosvald tené cuidado con confundir las preguntas, lo que pregunto Julian es si se pasa del "limite" definido en el proceso despues del `RESIZE`, pero en ningun momento mencionó el tamaño de la página.
Si fuera una página de exactos 10 bytes si rompería, pero si por ejemplo usamos páginas de 64 bytes no estas accediendo a una página inválida.

Saludos.-

**Comment by kenzogrosvald** [comment]
Hola @iago64,

Gracias por la aclaración.

Saludos

**Comment by julienf04** [comment]
Muchas gracias!
