### ISSUE TITLE
RESIZE: Ampliación y Reducción de un proceso

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3788]
Buenas tardes,
Tenemos un par de dudas con respecto al RESIZE:
0-Al iniciar un proceso que tiene su tabla de paginas vacia, antes de hacer un MOV_OUT por ejemplo, debo hacer un RESIZE que me permita almacenar lo de esa instrucción o se va asignando espacio al proceso a medida que escribe en memoria?
1-Nosotros en memoria, cuando se desea ampliar un proceso, vemos si hay suficiente espacio para todo lo que pide y si no hay retornamos OUT OF MEMORY. ¿Esto está bien o debo ampliarlo hasta que me deje memoria y luego retornar el OUT OF MEMORY?
2- ¿El tema de la asignación de marcos en memoria es aleatorio?
3- ¿A la hora de reducir un proceso, si yo tengo un proceso con 2 paginas de 4 bytes, en total 8 y hago un RESIZE 5, me quedaría una pagina, no es así?
3.1-¿Qué se deben hacer con los datos que quedaron en esos 3 bytes que mi proceso ya no tiene? ¿Dejarlo como están en memoria?
3.2-¿Qué pasa si yo tenia un dato que ocupaba los 8 bytes por ejemplo, un cadena de 8 caracteres y hago ese RESIZE 5, voy a perder información? ¿Debemos manejar estos casos o no es algo que se vaya a hacer en las pruebas? ¿O culpo al usuario? jajaj

**Comment by rood8592** [comment]
Perfecto, muchas gracias!!

**Comment by FredeHG** [comment]
Si ya está resuelta la duda por fa cerremos el issue. Saludos!
