### ISSUE TITLE
Duda con manejo de recursos y RR

### ISSUE THREAD

**Issue by Fran123445** [sisoputnfrba/foro#3789]
Hola. Estaba viendo como implementar el manejo de recursos y me surgio una duda con RR.
Es necesario contemplar el caso de que a un proceso que vuelve al kernel desalojado por signal se le termine el quantum mientras se le esta sumando 1 al recurso? O sea, que en la (pequeña) ventana de tiempo en el que el kernel le hace el ++ al recurso justo se termine el quantum del proceso.
Esto de movida, por como tengo hecho el manejo del quantum (codigo abajo), me genera 2 problemas:

- La CPU va a recibir una interrupcion por fin de quantum cuando no esta ejecutando nada
- Si el proceso vuelve a la CPU entonces va a seguir ahi de forma "indefinida" sin respetar el algoritmo, ya que no va haber un hilo que le vaya a mandar la interrupcion

Tambien mas desde lo conceptual no estoy seguro de que el quantum tenga que seguir corriendo durante ese tiempo, ya que no esta realmente ejecutando algo en la CPU, pero no se si eso alcanza al TP.

```
void esperarQuantumCompleto(PCB* proceso) {
    usleep(proceso->quantum*1000);
    enviarInterrupcion(proceso->PID);

    procesoInterrumpido = 1;
}

void esperarVuelta(PCB* proceso) {
    pthread_t esperaQuantum;
    pthread_create(&esperaQuantum,
						NULL,
						(void*) esperarQuantumCompleto,
						proceso);

    sem_wait(&llegadaProceso);

    if (procesoInterrumpido) {
        pthread_join(esperaQuantum, NULL);
        procesoInterrumpido = 0;
        return;
    }

    pthread_cancel(esperaQuantum);
    procesoInterrumpido = 0;
}
```

### 📔 Citas del enunciado/videos

>A la hora de recibir de la CPU un Contexto de Ejecución desalojado por WAIT, el Kernel deberá
verificar primero que exista el recurso solicitado y en caso de que exista restarle 1 a la cantidad de
instancias del mismo. En caso de que el número sea estrictamente menor a 0, el proceso que realizó
WAIT se bloqueará en la cola de bloqueados correspondiente al recurso.
A la hora de recibir de la CPU un Contexto de Ejecución desalojado por SIGNAL, el Kernel deberá
verificar primero que exista el recurso solicitado, luego sumarle 1 a la cantidad de instancias del
mismo. En caso de que corresponda, desbloquea al primer proceso de la cola de bloqueados de ese
recurso. Una vez hecho esto, se devuelve la ejecución al proceso que peticiona el SIGNAL.

### 💭 Soluciones posibles

Lo que se me ocurrio es poner un sem_wait(&procesoEnCPU) justo antes de enviarInterrupcion y chau, creo que eso me solucionaria el problema, suponiendo que el quantum siga corriendo mientras el proceso esta en el Kernel por signal (o wait de un recurso disponible, para el caso).

**Comment by iago64** [comment]
Buenas! Cómo va?

Solo para corroborar algo, uds cuando le piden al Kernel un SIGNAL / WAIT cortan por completo el ciclo de instrucción?
Me parece que están dándole una vuelta de mas al asunto, debería ser algo bastante mas simple, ya que al momento de ejecutar SIGNAL o WAIT en el ciclo de instrucción deberían estar en la etapa de execute y una vez que vuelvan ahi recién deberían checkear si tienen interrupciones.
Algo que pueden agregar por ejemplo a las interrupciones es el PID que quieren interrumpir, entonces con eso, si vuelven terminan el execute y es el mismo PID lo desalojan.
En el caso donde por ejecutar un WAIT se bloquean y mandan otro proceso a la CPU, lo que hacen es revisar si el PID a interrumpir es el mismo PID que mandaron y si no, aca no paso nada señores, no hubo interrupción de nada.

Como dato final, algo importante que tienen que tener en cuenta, es que el quantum en este TP es algo "simbólico" y que en la realidad es muchísimo más complejo porque las funciones como WAIT o SIGNAL para manejar semáforos incluyen un montón de cosas que en el TP no las tenemos en cuenta porque estarían todo el cuatrimestre solo para implementar esa función.

Saludos.-

**Comment by Fran123445** [comment]
> Solo para corroborar algo, uds cuando le piden al Kernel un SIGNAL / WAIT cortan por completo el ciclo de instrucción?

Todavia no empezamos a implementarlo pero me parece que con lo que dijiste mas o menos veo como viene la mano. 
Para ver si entendi: cuando haya que ejecutar una instruccion SIGNAL / WAIT, en la etapa execute la CPU le devuelve el proceso al Kernel y se queda, dentro de la misma etapa execute, esperando a que el Kernel le devuelva el proceso. Cuando el Kernel le devuelva a la CPU el proceso, esta hace el check interrupt y si hubiera una interrupcion correspondiente a ese PID lo devuelve al Kernel. En caso de que el proceso que envio la CPU se hubiera bloqueado por WAIT y el Kernel hubiera enviado otro proceso, la CPU veria que los PID son distintos y el nuevo proceso seguiria ejecutandose sin problema, correcto?

**Comment by iago64** [comment]
Buenas! Cómo va?

Exactamente como lo dijiste.

Saludos.-

**Comment by Fran123445** [comment]
Perfecto, muchas gracias!
