### ISSUE TITLE
Marcos y bitmap

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3790]
Buenas,
Tenemos una duda con respecto al bitmap y el tema de los marcos. Nosotros en la teoría vimos que para controlar el tema de los marcos libres se utiliza un array de bits (teniendo uno por cada marco). Habiendo visto esto, nos tiramos de cabeza a la biblioteca de bitarrays de la commons que pensamos que era para tal fin y hicimos algo así:

    void* user_space = malloc(tam_memoria);
    int cant_marcos=tam_memoria/tam_pagina;
    t_bitarray* bitmap=  
     bitarray_create_with_mode(user_space,cant_marcos/8,LSB_FIRST);

Con eso teniamos un bitarray con cantidad de bits que coincidia con la cantidad de marcos. No estamos muy seguros de si esta bien utilizado el bitarray de esta manera, si se utiliza para estos fines, etc y después vimos en un issue que dicen que no es necesario y/o obligatorio utilizar bitmap para memoria y solo se pide para dialFS. Con estos nos quedaron varias dudas: ¿Sería suficiente utilizar un array de bits común para el tema de los marcos libres? ¿Se podría utilizar un bitarray? ¿Que ventajas y/o desventajas tendría sobre el array común? ¿Esta bien utilizado y/o implementado el bitarray como está en el código?

**Comment by mefederico** [comment]
Hola buenas!

Un array de bits es un bitarray, en C no podes declarar una variable como bit[] así que solo te queda como alternativa usar la lib o algo similar custom a lo que hace la lib

Si, pueden utilizar bitarray

La única forma de saber si algo esta bien implementado o no es compilar y probar, nosotros no somos compiladores humanos, para mi desgracia, pero a simple vista lo veo bien, te diría que tengas cuidado cuando el numero no da redondo hacer que redondee para arriba

Saludos!

**Comment by rood8592** [comment]
Nuestra duda del bitarray venia por el lado de los parametros, por ej, el primer parametro que nosotros le pasamos es el espacio de usuario que piden en la consigna del tp en memoria ¿Está bien pasado esto o habría que pasarle otro void* con nombre "bitmap_user_space"? Y si está bien pasarle el user_space, ¿Por qué deberiamos pasarle ese dato? ¿De qué forma utilizará el bitmap el void* del user_space? Si al fin y al cabo nosotros, manualmente, con set y clean podemos fijar en 1 o 0 cada bit para indicar si un marco esta libre u ocupado a medida que vamos manipulando el espacio de usuario.

**Comment by RaniAgus** [comment]
¡Buenas! El primer parámetro que recibe `bitarray_create_with_mode()` es un puntero a la memoria que se va a usar para el **bitmap**, por lo que no es correcto pasarle el espacio de usuario ya que, cuando quieran usar `bitarray_set_bit()` y `bitarray_clean_bit()`, van a estar modificando el espacio de usuario.

Lo correcto sería pasarle una porción de memoria distinta que mida `cant_marcos/8`, ya que ésta les va a servir para determinar si un marco está libre o no usando `bitarray_test_bit()`.

Saludos

**Comment by rood8592** [comment]
Gracias, y el tema del LSB o MSB no lo tenemos muy claro tampoco, me cambia algo en este contexto utilizar uno u otro?

**Comment by rood8592** [comment]
Buenas, gracias por las aclaraciones. Entonces ese ```void*``` que le asigno al ```bitarray_create_with_mode()``` una vez que queda unido al bitarray creado importa utilizarlo de alguna manera? O solo me importa utilizar el ```t_bitarray*``` creado a partir de ese ```void*```? A lo que me refiero es ¿La unica función de ese ```void*``` fue apartarle un lugar a nuestro ```t_bitarray*``` y despues lo unico que manipularemos o nos será de utilidad es ese ```t_bitarray*``` creado? Nosotros hicimos una función en donde dentro se crea el ```void*``` se hace el ```bitarray_create_with_mode()``` asignandole ese void y se retorna el ```t_bitarray```.
Y otra duda con respecto a lo que dijo @mefederico: "te diría que tengas cuidado cuando el numero no da redondo hacer que redondee para arriba". ¿Qué sucederia en un caso como el siguiente donde la cantidad de marcos no es multiplo de 8?
Tam_memoria =480
Tam_pagina=32
En total 15 marcos, 15/8 redondeado sería 2, con lo cual el bitmap tendría 2x8 bits. Si yo a un proceso le asigno el marco 15, sería 15*8=480 y el marco empezaría ahí, me desplazo un poco y me salgo del espacio reservado que sería de 480, lo cual podría producir un seg_fault. No pasaría si fuera 512, ya que el ultimo marco tendría los 32 bytes necesarios para desplazarse cuanto quiera.

**Comment by RaniAgus** [comment]
> Entonces ese void* que le asigno al bitarray_create_with_mode() una vez que queda unido al bitarray creado importa utilizarlo de alguna manera? O solo me importa utilizar el t_bitarray* creado a partir de ese void*?

Lo segundo: una vez metés el `void *` dentro del `t_bitarray *` ya forma parte del bitarray. No deberías modificarlo por afuera ya eso te estaría modificando los valores del bitarray.

> A lo que me refiero es ¿La unica función de ese void* fue apartarle un lugar a nuestro t_bitarray* y despues lo unico que manipularemos o nos será de utilidad es ese t_bitarray* creado?

Correcto. Lo piola de tenerlo parametrizado es que la memoria puede ser reservada por `malloc()` o también por `mmap()`, lo cual está bueno en el caso de utilizar un bitmap para el File System: te mapeás el archivo a memoria y lo manipulás usando las commons :D

> Nosotros hicimos una función en donde dentro se crea el void* se hace el bitarray_create_with_mode() asignandole ese void y se retorna el t_bitarray

> ¿Qué sucederia en un caso como el siguiente donde la cantidad de marcos no es multiplo de 8?
> Tam_memoria =480
> Tam_pagina=32
> En total 15 marcos, 15/8 redondeado sería 2, con lo cual el bitmap tendría 2x8 bits. 

Sí, 15/8 redondeado da 2, peeero `15 / 8` con enteros da 1:

```c
#include <stdio.h>
#include <string.h>

int main() {
    int n = 15 / 8;
    printf("15 / 8 = %d\n", n);
    return 0;
}
```
```
$ gcc main.c
$ ./a.out 
15 / 8 = 1
```

De ahí la observación de Fede sobre tener cuidado en caso de que el número no dé redondo: deberías sumarle uno para que funcione el redondeo hacia arriba.

Saludos

**Comment by rood8592** [comment]
Claro claro, eso lo entendí, mi duda principal era que une vez redondeado siguiendo con el mismo ejemplo: Si yo a un proceso le asigno el marco 15 (bit numero 15 empezando en 0) sería 15(marco)*32(tam_pagina)=480 y el marco empezaría ahí, si me desplazo un poco, me salgo del espacio reservado para user_space que sería de 480, lo cual podría producir un seg_fault. No pasaría si fuera 512, ya que el ultimo marco tendría los 32 bytes necesarios para desplazarse cuanto quiera. Osea en resumen, al redondear se añadio un marco que por ahí el user_space no lo tiene, al menos no en su totalidad. Por ahí yo a un proceso le asigno ese marco porque el bit lo marca como libre pero es un espacio de direcciones que a mi malloc(480) del user_space no le pertenece.

**Comment by RaniAgus** [comment]
No debería haber problema porque solo deberías hacer `bitarray_test_bit(bitarray, n)` con un `n` máximo de `cant_paginas - 1`. En el ejemplo, ya sabés que el `n` máximo sería `15 - 1 = 14` por lo que nunca deberías asignar "sin querer" el bit `15`, ya que parás de iterar al llegar a `14`.

En cambio, sí hay problema cuando el bitarray es más chico que el `n` máximo, porque `bitarray_test_bit(bitarray, n)` estaría leyendo una posición de memoria por afuera del `malloc()` que hiciste para el bitmap. En el ejemplo, esto ocurriría para todos los `n` que estén entre `8` y `14` inclusive.

Saludos

**Comment by nicolasvultaggio** [comment]
pregunta, estuve leyendo y perdón que me meta, en resumen:

no hay problema que el bitarray termine siendo de un numero de posiciones mayor a la cantidad de paginas, ya que solo se debería iterar hasta esta cantidad límite.
el problema es cuando al redondear, se asigne un bitarray de MENOR cantidad de elementos que la cantidad de marcos, ya que al iterar podría acceder a espacios de memoria no correspondientes. 
¿como podríamos entonces asegurarnos de siempre redondear para arriba?

**Comment by RaniAgus** [comment]
¡Buenas, @nicolasvultaggio! El problema de redondear para arriba es bastante común, por lo que haciendo una búsqueda rápida en StackOverflow encontré una posible solución: https://stackoverflow.com/a/2422722 :)

Tip para la próxima: porfa si van a referirse a un issue cerrado, háganlo en un nuevo issue como indicamos en las [normas del foro](https://github.com/sisoputnfrba/foro/blob/master/README.md). Justo vi la notificación de casualidad porque había respondido acá y estaba en GitHub, pero sino, internamente la única forma de enterarnos que hay una nueva consulta es por medio de un evento que se dispara cada vez que se abre (o reabre) un issue, así que tu consulta podría haber quedado en la nada 😞 

Saludos

**Comment by nicolasvultaggio** [comment]
muchas gracias!
