### ISSUE TITLE
Duda sobre que hacer si al proceso no le quedan mas paginas

### ISSUE THREAD

**Issue by ManuRodri01** [sisoputnfrba/foro#3791]
Buenas, tengo una consulta sobre que hacer cuando al proceso ya no le quedan mas paginas. Supongamos un proceso que tiene 6 paginas e intenta escribir algo en su ultima pagina, pero no le alcanza con eso y necesita una pagina mas; pero como era la ultima pagina, no se puede seguir escribiendo en la siguiente.
En este caso, se devuelve un Out of Memory y se finaliza el proceso o se hace otra cosa?

Saludos

**Comment by mefederico** [comment]
Hola buenas! 

No es un caso que vayamos a probar pero si es una buena solución devolver Out of Memory

Saludos!

**Comment by ManuRodri01** [comment]
Muchas Gracias
