### ISSUE TITLE
pequeñas dudas sobre el funcionamiento de la memoria

### ISSUE THREAD

**Issue by nicolasvultaggio** [sisoputnfrba/foro#3792]
Buenas, este finde estuve leyendo bien toda la teoría de memoria para la materia, pero sin embargo cuando intento "transferirlo" al tp, me surgen algunas dudas sobre que es lo que se quiere que hagamos.

1. Primeramente, en clase vimos (o en realidad, lo que yo entendí) que la tabla de páginas podría ser UNA POR proceso, y que esta se encuentre en el pcb (no es el caso del tp), también puede haber una por proceso pero que se encuentre en la memoria RAM, en alguna estructura que queramos, y la otra opción es que sea UNA sola tabla de páginas para todos los procesos, una que indique por ejemplo, para cada página, si tiene un marco asignado y si es esto cierto, qué marco es y que proceso lo tiene asignado. Bueno, mi  primera duda es si lo que se busca que nosotros hagamos en este tp es esta tercera opción, o sea, una sola tabla de paginas para todas las paginas (y por lo tanto, todos los procesos).

> Creación de Procesos
Ante la solicitud de la consola de crear un nuevo proceso el Kernel deberá informarle a la memoria que debe crear un proceso cuyas operaciones corresponderán al archivo de pseudocódigo pasado por parámetro, todos los procesos iniciarán sin espacio reservado en memoria, por lo que solamente tendrán una tabla de páginas vacía.

Esta parte, sin embargo, parece indicar que hay una sola tabla de paginas por proceso, o sea, la segunda opción.

2. Si todos los procesos se inician sin espacio asignado en memoria, ¿Cómo hacen los procesos para que tener marcos a disposición? Cada vez que quieran escribir en espacio usuario y haya marcos libres, se les otorga este espacio? Si esto fuera así, para que serviría la siguiente operación? Porque no hay ninguna instrucción de pseudocódigo que les permita reservar una cierta cantidad de marcos inicialmente

> RESIZE (Tamaño): Solicitará a la Memoria ajustar el tamaño del proceso al tamaño pasado por parámetro. En caso de que la respuesta de la memoria sea Out of Memory, se deberá devolver el contexto de ejecución al Kernel informando de esta situación.

3. Se asume que las páginas pueden reubicarse en memoria, cada vez que el proceso pase a ejecutarse, como es ideal en la teoría? o una vez que se le asigna un marco a un proceso, hasta que este finalice o lo libere por medio de otra instrucción,  lo "mantiene", pudiendo generar los conflictos en la escritura o lectura (que la MMU debe poder detectar)?

4. En STDIN y STDOUT, el que realiza la traducción de dirección lógica a física sigue siendo la MMU, y posteriormente se la pasa a la interfaz? o la interfaz debe recibir la dirección lógica?

**Comment by nicolasvultaggio** [comment]
Perfecto! Muchas gracias, ya no me quedan mas dudas.
Con respecto a la pregunta del 3),  con "conflictos" me refería a que la MMU maneje los casos en los que un proceso A quiera escribir en una pagina que le se le haya sido asignada a otro proceso B, y por eso de alguna forma de debería finalizar el proceso A. Pero en realidad no tengo ninguna pregunta con respecto a esto, era simplemente para aclarar a donde quería llegar.

Buena semana!

**Comment by mefederico** [comment]
La tabla de paginas, es por proceso, por lo que no vas a tener un proceso queriendo usar la pagina de otro proceso, si te va a dar el mismo numero de pagina pero el al usar pid + numero de pagina es distinto el marco y no deberias tener ningun problema o conflicto

**Comment by nicolasvultaggio** [comment]
si, tenes razón, evidentemente me confundí en algo y no se por qué pensé que se podía dar ese conflicto, pero entiendo lo que decís, muchas gracias.

**Comment by nicolasvultaggio** [comment]
perdón, hago una pregunta cortita, las direcciones lógicas de las instrucciones vienen en binario o en decimal?

**Comment by mefederico** [comment]
Si, en decimal

**Comment by LeandroCarbajales** [comment]
Buenas @nicolasvultaggio !
Quedó resuelta la duda?

**Comment by nicolasvultaggio** [comment]
si! mil perdones no volvi a abrir el foro, muchas gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Algo interesante de C es que podés hacer aritmética de punteros, con lo cual, vos podés hacer por ejemplo

```c
void * memoria = malloc(4096);
```

Y a esa variable sumarle 10 `memoria + 10` y va a ser lo mismo que si hicieras `memoria[10]`

Saludos.-

**Comment by nicolasvultaggio** [comment]
claro, sí, pero con respecto al resto, sobre la forma de una dirección lógica y una dirección física, tiene sentido? es por ahí? o sea son números de bytes?

**Comment by iago64** [comment]
Buenas! Cómo va?

Exacto, las direcciones lógicas van a venir en número decimales porque laburar hexa en C es una patada en los dientes, entonces van a tener que aplicar las cuentas que les dejamos en el enunciado para simplificarse la vida.
Con el número de página van a obtener el frame y depues a eso le van a tener que sumar el desplazamiento o el resto de la división de `dirección lógica / tamaño página`.

Saludos.-

**Comment by nicolasvultaggio** [comment]
joya, ya no me quedan mas dudas, muchas gracias
