### ISSUE TITLE
error 403 github 

### ISSUE THREAD

**Issue by luchito12** [sisoputnfrba/foro#3793]
hola buenas hace unas semanas se me presento este error en particular el **error 403**, en su momento no le di importancia ya que podía hacer los comits desde el visual y los pull también,  trate de solucionarlo creando una nueva tokken, borrando todas las tokken pero no funciono nada, no solo que no puedo clonar el repo, sino que tampoco puedo hacer push y pull me tira el mismo error,  hago este issue ya que llego el dia en el que visual no me deja hacer un pull ya que me tira un  warning  el cual dice **please your clean repository working tree before checkout**, asi que nada me estoy viendo inhabilitado para trabajar ya que no puedo actualizar los últimos cambios que hicimos con mi equipo.

### 🔎 Búsqueda en foros
 busque en los foros y no encontré nada similar, en Internet y en youtube las soluciones al problema son bastantes diferentes entre si y constan en cambiar archivos y agregar direcciones,  prefiero consultar antes que andar modificando y metiendo mano en archivos y que después me tiren otros errores   

### 📝 Pasos para reproducir el error
básicamente desde que arranque la cursada podía hacer los clone pull y push sin problema es mas en otras materias no tuve este problema con los repositorios 

### 💻 Logs
 dejo captura de pantalla con el error 
![problema 403](https://github.com/sisoputnfrba/foro/assets/82194770/de1a450e-0cd0-4b1d-be67-3c3dac91c128)

**Comment by luchito12** [comment]
buenas ya pude hacer el pull desde el visual así que puedo seguir trabajando como venia, no obstante si saben como solucionar ese error me vendría bien desde ya muchas gracias

**Comment by RaniAgus** [comment]
¡Buenas! Podés probar de seguir esta nueva sección del TP0: https://docs.utnso.com.ar/primeros-pasos/tp0#configurar-las-credenciales-de-git

Y luego clonarte el repo usando SSH:
```
git clone git@github:sisoputnfrba/tp-2024-1c-grupo-s.o-2024.git
```

Saludos

**Comment by luchito12** [comment]
muchas gracias

**Comment by RaniAgus** [comment]
¡Buenísimo! Recuerden que si la duda ya fue resuelta pueden cerrar el issue 👮🏻‍♂️
