### ISSUE TITLE
Duda sobre implementación de bitmap

### ISSUE THREAD

**Issue by ElielBejar** [sisoputnfrba/foro#3794]
Buenas! Estuve viendo en el foro que implementan las funciones mmap y msync para mantener el bitarray actualizado en el archivo bitmap.dat. Lo que no me queda claro es que es lo que hacen esas funciones y si yo puedo usar mmap relacionando el char* bitarray de mi struct t_bitarray con el archivo bitmap.dat de esta forma: 
```
memoria_archivo = mmap(NULL, tamanio_bytes_bitmap, PROT_READ | PROT_WRITE, MAP_SHARED,archivo_bitmap, 0);
bitmap = bitarray_create_with_mode(memoria_archivo, tamanio_bytes_bitmap, MSB_FIRST);
msync(memoria_archivo, tamanio_bytes_bitmap, MS_SYNC);

```
memoria_archivo es un void* y bitmap es un t_bitarray.

de la forma que puse recién supongo que lo que hace es sincronizar memoria_archivo con el archivo bitmap.dat, los ceros y unos del bitarray van a estar guardados justamente en memoria_archivo y cuando pongo msync guardo los cambios y paso los ceros y unos al archivo. Es correcto o lo estoy interpretando mal? Sino de que otra forma se podría hacer? Desde ya gracias!
```
```
### 🔎 Búsqueda en foros

Investigé por el foro y vi en el issue  #3682 y en el issue #3669

**Comment by ElielBejar** [comment]
UP
proporciono también un codigo que hice pero no funciona por un segmentation fault. 
```
archivo_bitmap = crear_archivo(nombre_archivo);
    size_t tamanio_bytes_bitmap = /*inout_config.block_count*/1024/8;
    char* memoria_bitmap = (char*) mmap(NULL, tamanio_bytes_bitmap, PROT_READ | PROT_WRITE, MAP_SHARED, fileno(archivo_bitmap), 0);
    if(memoria_bitmap == MAP_FAILED) {
    perror("Error al mapear el archivo en memoria");
    fclose(archivo_bitmap); // Cerrar el archivo antes de salir
    return;
}
    log_info(logger, "Direccion de memoria %d: ", memoria_bitmap);
    bitmap = bitarray_create_with_mode((char*)memoria_bitmap, tamanio_bytes_bitmap, LSB_FIRST);
    msync(memoria_bitmap, tamanio_bytes_bitmap, MS_SYNC);
```
La dirección de memoria de memoria_bitmap es un numero negativo random pero me compila, se crea el archivo y todo pero si intento escribir en memoria_bitmap salta el error por eso mismo

**Comment by iago64** [comment]
Buenas! Cómo va?

Justamente si una dirección de memoria es un número negativo es que algo está mal.
Probaste ejecutarlo con Valgrind para que te tire algo mas de info acerca del problema? Podes ejecutarlo y pasarnos el output de Valgrind **en texto**

Saludos.-

**Comment by iago64** [comment]
Buenas! Cómo va?

Si, esta bien que aparezca en hexa porque justamente no podes ver bit a bit.
Otra opción que pueden usar es `hexdump` o `xxd` que son tools de la terminal para ver archivos binarios en hexa.

Saludos.-

**Comment by ElielBejar** [comment]
Perfecto! Voy a probarlo dale, gracias! Saludoss, cierro el issue
