### ISSUE TITLE
Manejo de recursos -> SIGNAL antes que WAIT?

### ISSUE THREAD

**Issue by ErikOteo** [sisoputnfrba/foro#3795]
Buenas!! Estamos viendo el tema de manejo de recursos y nos surgió la duda de si en las pruebas un proceso va a poder hacer un SIGNAL a un recurso antes que hacerle WAIT? 

Es decir cuando un proceso hace un WAIT a un recurso -> Se le asigna el recurso al proceso (cuando el recurso este disponible), este proceso previamente puede hacer un SIGNAL a ese recurso y se le va a desasignar.

Pero si el proceso hace un SIGNAL antes de hacer WAIT -> no se le podría desasignar el recurso porque no lo tenia asignado y además pasaría que los recursos podrían tener mas instancias que las iniciales. Por ejemplo, si las instancias iniciales de un recurso son 4 y un proceso hace un SIGNAL de ese recurso pasaría a tener 5 instancias.

La consulta es si es que en las pruebas van a hacer un SIGNAL antes de hacer WAIT y si es que nosotros tenemos que dejar que eso pase o si es que tenemos que detectar que un proceso esta queriendo hacer SIGNAL de un recurso que no tiene? Y en ese caso como tenemos que manejarlo?

**Comment by mefederico** [comment]
Hola buenas! 

Si, se pueden hacer SIGNAL sin WAIT y no hay ningún problema con tener mas recursos que los iniciales ya que son solamente eso, instancias iniciales

Saludos!

**Comment by mefederico** [comment]
Hola, te sirvió la respuesta? Podemos cerrar el issue?

**Comment by ErikOteo** [comment]
Si, perfecto, muchas gracias!!

**Comment by iago64** [comment]
Si la duda esta resuelta, no se olviden de cerrar el issue.
