### ISSUE TITLE
void* y stdin

### ISSUE THREAD

**Issue by fmigliavacca** [sisoputnfrba/foro#3796]
Buenas, tengo una consulta a la hora de recibir las interfaces STDIN por parte de memoria. Cuando i/o me pasa la dirección física y la cadena,  yo debo guardar la cadena dentro del espacio de memoria datos? O sea el void*? Si es así, cómo se hace para que la direc física que me pasan, o sea un int que representa un puntero, se guarde en esa dirección DENTRO del void* generado en el módulo de memoria, o sea el void* de datos? Xq mi duda en realidad nace de que si yo simplemente hiciera memcpy del char* a la dirección física que me pasaron, capaz esa dirección física no pertenece al gran malloc(cantidad de bytes de memoria sacados del memoria.config) y me lo copia en cualquier lado. Otra opción es que me aseguren que esa dirección física que me pasa la interfaz, SI o SI pertenece a ese gran malloc, o sea el void* de datos. Espero no haber mareado de más con los intentos de aclaraciones, espero su respuesta, Saludos!.

**Comment by fmigliavacca** [comment]
Okay, o sea que las direcciones físicas que siempre me den, siempre van a ser "relativas" al void* principal, verdad?

**Comment by RaniAgus** [comment]
Verdad.

**Comment by iago64** [comment]
@fmigliavacca Te sirvio la respuesta de @RaniAgus?

Saludos.-

**Comment by LeandroCarbajales** [comment]
Cierro el issue por inactividad.
