### ISSUE TITLE
Duda comunicacion IO-kernel

### ISSUE THREAD

**Issue by Lisandrogq** [sisoputnfrba/foro#3798]
Buenas, tengo una breve consulta respecto a una posible situacion de conflicto:

Se me ocurrio que podría llegar a suceder que una IO avise a kernel que termino su tarea y simultaneamente el kernel este escribiendo en el mismo socket de esa IO(para pedirle otra tarea). Creo que esta situacion generaría errores ya que se pisarían los datos mutuamente, por eso pregunto ¿Debemos contemplar esta situacion? 

En caso de que debamos contemplarlo se me ocurre que una posible solucion sea que la comuniacion se de en 2 sockets, uno para que la IO avise que termino y otro para que el kernel pida nuevas tareas.

**Comment by RaniAgus** [comment]
¡Buenas! No hay problema, todos los sockets tienen 2 búferes: uno para enviar bytes ("send buffer") y otro para recibir bytes ("recv buffer"). Entonces, si ambos módulos A y B están haciendo `send()` a la vez:

- A está escribiendo en el send buffer de A y en el recv buffer de B
- B está escribiendo en el send buffer de B y en el recv buffer de A

Fuente: https://unix.stackexchange.com/a/610059

Saludos

**Comment by Lisandrogq** [comment]
Ahh genial! Gracias Agus
