### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by tomipodo** [sisoputnfrba/foro#3799]
Buenas nos surgió una duda acerca del error out of memory.
El enunciado dice lo siguiente:
RESIZE (Tamaño): Solicitará a la Memoria ajustar el tamaño del proceso al tamaño pasado por parámetro. En caso de que la respuesta de la memoria sea Out of Memory, se deberá devolver el contexto de ejecución al Kernel informando de esta situación.
Entendemos, entonces, que la CPU le envía el contexto con este motivo al Kernel, pero que debe realizar el Kernel ante esta situación?

**Comment by iago64** [comment]
Buenas! Cómo va?

Cuando la Memoria te conteste con el error Out Of Memory, la CPU le tiene que devolver el Contexto de ejecución al Kernel y el Kernel cuando le llega el contexto con el error de Out of Memory, simplemente tiene que mandar a EXIT el proceso (como si hubiera ejecutado EXIT)

Saludos.-

**Comment by tomipodo** [comment]
Perfecto gracias. No es necesario que el kernel vuelva a enviarle a la CPU que el proceso fue a EXIT para que esta le avise a la memoria, no? Podemos simplemente, cuando a la CPU le llega out of memory, hacer que la CPU le diga a la memoria que elimine el proceso (ademas de avisarle al Kernel)?

**Comment by LeandroCarbajales** [comment]
Buenas!
Cito al enunciado, módulo Kernel:

> Eliminación de Procesos
Ante la llegada de un proceso al estado de EXIT (ya sea por solicitud de la CPU, por un error, o por ejecución desde la consola del Kernel), el Kernel deberá solicitar a la memoria que libere todas las estructuras asociadas al proceso y marque como libre todo el espacio que este ocupaba.

Es responsabilidad del módulo Kernel la finalización de los procesos y de avisarle al módulo Memoria que libere las estructuras necesarias, no debe hacerlo el módulo CPU ya que estarías pidiéndole a la Memoria que libere un Proceso que el Kernel aun no decidió finalizar.

**Comment by tomipodo** [comment]
Ah claro, se me pasó esa parte, mil gracias
