### ISSUE TITLE
Dirección física en Memoria

### ISSUE THREAD

**Issue by julienf04** [sisoputnfrba/foro#3800]
### Buenas!

------------

#### Contexto

Tengo una duda con respecto a las peticiones que hace la CPU o una interfaz I/O para leer o escribir en la memoria de un proceso.

En el enunciado, en el módulo de Memoria dice:

> - Ante un pedido de lectura, devolver el valor que se encuentra a partir de la dirección física pedida.
> - Ante un pedido de escritura, escribir lo indicado a partir de la dirección física pedida. En caso satisfactorio se responderá un mensaje de ‘OK’.

Según lo anterior: "**la** dirección física pedida".

------------

#### Duda

¿Solamente se le debe pedir a la Memoria 1 dirección física por petición?

------------

#### ¿Por qué me surgió la duda?

En el módulo de CPU dice:

> Es importante tener en cuenta en este punto que una Dirección Lógica va a pertenecer a una página en cuestión, pero el contenido a leer o escribir puede ser que ocupe más de una página

Entonces, tengo que tener en cuenta que al módulo Memoria se le tiene que pasar la dirección física, pero también tengo que tener en cuenta que puedo necesitar escribir o leer varias páginas (es decir, varios frames de la memoria de usuario).

Para contemplar esos dos puntos del enunciado, se me ocurren dos implementaciones diferentes, pero una de ellas (la cual considero que es la más rápida en cuanto a tiempo de ejecución según el análisis que hice) no sería válida si la respuesta a la duda es **"SÍ"**, ya que esa implementación requiere que pueda mandarle a la Memoria 1 *__o más__* direcciones físicas. La cantidad de direcciones físicas que le mande dependería de la cantidad de frames que debería leer o escribir para una única instrucción de pseudocódigo.

**Comment by LeandroCarbajales** [comment]
Buenas!
La respuesta a la duda es "SÍ" (una [dirección, tamaño] por pedido), justamente para explicitar que en definitiva estás haciendo más accesos a memoria (con sus correspondientes retardos).

**Comment by julienf04** [comment]
Buenísimo, entonces descarto esa idea de implementación que tenía, graciaaasss!
