### ISSUE TITLE
Dudas sobre resize

### ISSUE THREAD

**Issue by ManuRodri01** [sisoputnfrba/foro#3801]
Buenas, tengo 2 dudas sobre el comportamiento de resize.
La primera, supongamos que mis paginas son de 4 Bytes; si yo hago un resize(10) se me van a dar 3 paginas. Si después se hace un resize(12), no debería hacer nada, no? Xq con las tres paginas anteriores ya tengo los 12 bytes.
Lo mismo pero al revés, si tengo un resize(12) y después otro resize(10); no debería hacer nada.

Lo otro es una duda sobre eliminar las paginas a la hora de reducir un proceso. En el enunciado dice 

> Se reducirá el mismo desde el final, liberando, en caso de ser necesario, las páginas que ya no sean utilizadas (desde la última hacia la primera).

Hay una forma de saber que paginas ya no están siendo utilizadas o solo hay que ir liberando las paginas desde la ultima a la primera en general?

Saludos

**Comment by LeandroCarbajales** [comment]
Buenas!

>  La primera, supongamos que mis paginas son de 4 Bytes; si yo hago un resize(10) se me van a dar 3 paginas. Si después se hace un resize(12), no debería hacer nada, no? Xq con las tres paginas anteriores ya tengo los 12 bytes.
Lo mismo pero al revés, si tengo un resize(12) y después otro resize(10); no debería hacer nada.

Exactamente! 

> Hay una forma de saber que paginas ya no están siendo utilizadas o solo hay que ir liberando las paginas desde la ultima a la primera en general?

Claro! Viene con la misma lógica que lo anterior, teniendo páginas de 4 bytes y ya hiciste un resize(12), tenés 3 páginas (0, 1 y 2).
Si ahora hacés un resize (4) tendría que quedarte una sola página liberando desde la última hacia la primera, por lo que solamente te quedarías con la página 0.

Te resuelve la duda?
Saludos!
      Lean

**Comment by ManuRodri01** [comment]
Sisi, todo claro. Muchas gracias.
