### ISSUE TITLE
Archivo pseudocodigo Planificador Largo Plazo

### ISSUE THREAD

**Issue by lucasvazz16** [sisoputnfrba/foro#3802]
Hola, tengo una duda con respecto al archivo de pseudocódigo. Principalmente, me gustaría saber cómo se va a proporcionar este archivo. ¿Nos llegaría una ruta al archivo o que exactamente? ¿De donde nos llega? Además vi que en el archivo de config del modulo memoria, existe un campo que es "PATH_INSTRUCCIONES" ¿Esto ultimo tiene algo que ver?
### 📔 Citas del enunciado/videos

Creación de Procesos
Ante la solicitud de la consola de crear un nuevo proceso el Kernel deberá informarle a la memoria que debe crear un proceso cuyas operaciones corresponderán al archivo de pseudocódigo pasado por parámetro, todos los procesos iniciarán sin espacio reservado en memoria, por lo que solamente tendrán una tabla de páginas vacía.

**Comment by LeandroCarbajales** [comment]
Buenas!
Los archivos de pseudocódigo para las pruebas se proporcionarán en [este repo](https://github.com/sisoputnfrba/c-comenta-pruebas), aunque obviamente pueden crear los suyos propios para probar su TP a medida que lo desarrollan.

Como indica la descripción del campo PATH_INSTRUCCIONES de la config de Memoria: `Carpeta donde se encuentran los archivos de pseudocódigo.`, es decir, el mismo debería tener el path de la carpeta donde tienen los archivos. Por ejemplo (tomado del enunciado) `/home/utnso/scripts-pruebas`. Si se clonan el repo y no quieren cambiarle el nombre pueden cambiar ese path a algo como `/home/utnso/c-comenta-pruebas`.

Luego, al momento de crear el proceso, les pueden pasar el path `preliminares/script_io_basico_1` (relativo a la carpeta donde están parados).

Te resuelve las dudas?

**Comment by lucasvazz16** [comment]
Sisi, muchas gracais.
