### ISSUE TITLE
Resize

### ISSUE THREAD

**Issue by fmigliavacca** [sisoputnfrba/foro#3803]
![image](https://github.com/sisoputnfrba/foro/assets/163766676/73308819-7cfa-437d-9a2a-72916f9e3ca8)
Hola, tengo duda con esta instrucción de CPU.  Cómo puede ser que ajuste el tamaño asignado al proceso?? Si los procesos no tienen tamaño en el void* de datos, solo entran datos, o no? O es que cada uno de esos datos que entra pertenece a un proceso y debo tenerlos separados en una estructura aparte dentro de la tabla de paginas?

**Comment by LeandroCarbajales** [comment]
Buenas!
Me hace un poco de ruido esta frase
> debo tenerlos separados en una estructura aparte dentro de la tabla de paginas

Te referís a que tienen una sola tabla de páginas?

**Comment by fmigliavacca** [comment]
O sea, yo lo que había pensado era: la consigna me pide una tabla de páginas, dentro de esa tabla (una lista), cada nodo tiene el numero de pagina, el frame asignado, y el proceso al que pertenece. Teniendo en cuenta esto, no sé qué es el tamaño del proceso, la cantidad de frames que ocupa todos los datos de un proceso específico? Y esos datos son las cosas que  voy guardando que me pasan por medio de CPU e interfaces STDIN ?

**Comment by LeandroCarbajales** [comment]
Te recomiendo pegarle una leída/repasada a paginación nuevamente para tenerlo fresco, ya que se tiene una tabla de páginas por proceso, y el "tamaño del proceso" es justamente la cantidad de **páginas** que un proceso ocupa, para tus estructuras podría significar la cantidad de entradas en tu lista de páginas para ese proceso. Luego, al liberar páginas sus frames correspondientes además quedarían libres.

**Comment by fmigliavacca** [comment]
Gracias
