### ISSUE TITLE
Módulo CPU: MMU, datos necesarios

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3804]
Buenas, 
Si necesitamos algún dato de memoria como el "TAM_PAGINA", estaría mal ponerlo en el config de cpu, además de en el config de memoria? También pensamos mandarlo en el handshake, pero nos resultá más facil añadirlo al config.

**Comment by LeandroCarbajales** [comment]
Buenas!
Pasárselo al momento del handshake les va a facilitar no tener que estar cambiando 2 configs con el mismo valor durante las pruebas, con la posibilidad de equivocarse y explote todo debido a que CPU tenga un tam_pagina distinto a Memoria :)

**Comment by rood8592** [comment]
Ok, gracias @LeandroCarbajales !!
