### ISSUE TITLE
Asignacion de memoria a proceso

### ISSUE THREAD

**Issue by fmigliavacca** [sisoputnfrba/foro#3805]
Buenas, tengo un par de consultas:
1- Cuando un proceso arranca, arranca sin espacio en memoria, verdad? Recién obtiene páginas cuando hace el primer resize, verdad?
2- Si es así, la tabla de páginas debería hacerla en cuanto leo el archivo de pseudocódigo (o sea cuando apareció el nuevo proceso), o luego del primer resize?
3- Las direcciones lógicas que se utilizan en instrucicones como MOV IN por ejemplo, cómo están compuestas? Número de página + desplazamiento ? Y a memoria ya le llegan directamente las direcciónes físicas? O CPU le pasa la página a memoria, memoria obtiene la dirección física del marco, le pasa el marco a CPU, y CPU calcula la dirección física sumandole el desplazamiento y se la envía a memoria?

**Comment by LeandroCarbajales** [comment]
Buenas!
1- Sí
2- Cuando se crea el proceso, a efectos de implementación además te ahorrarías un if :)
3- Las direcciones lógicas son simplemente un número.

> O CPU le pasa la página a memoria, memoria obtiene la dirección física del marco, le pasa el marco a CPU, y CPU calcula la dirección física sumandole el desplazamiento y se la envía a memoria?

Claro, a Memoria le puede llegar el pedido de CPU de que le diga a qué marco corresponde una página o directamente para accedar a una dirección física, esto es equivalente como se ve en clases, donde en paginación para acceder a memoria terminas accediendo 2 veces (1 para traducir la dirección y 1 el acceso al dato en sí)

**Comment by fmigliavacca** [comment]
2- Perfecto, medio redundante pero para confirmar nomas, el proceso se crea cuando leo el archivo de psuedocódigo, no?
3- Claro, pero pregunto cómo están compuestas para saber cómo hago para convertirlas en direcciones físicas en el Tp

**Comment by iago64** [comment]
Buenas! Cómo va?

2.- Si
3.- Cito el enunciado:

> Como en el lenguaje C los números enteros se operan independientemente de su base numérica, la operatoria puede desarrollarse de la siguiente forma:
número_página = floor(dirección_lógica / tamaño_página)
desplazamiento = dirección_lógica - número_página * tamaño_página

Saludos.-

**Comment by fmigliavacca** [comment]
Muchas gracias, no había visto esa parte del enunciado. Saludos!
