### ISSUE TITLE
STDIN y memoria

### ISSUE THREAD

**Issue by fmigliavacca** [sisoputnfrba/foro#3806]
Tengo una consulta, cuando me llega la dirección física del stdin más la cadena a guardar, existe la posibilidad que al hacer el void* data + direcFisica (la del stdin) sea un marco asignado a otro proceso? Los char provenientes de los STDIN deben guardarse en una tabla de páginas nueva? Si es así, a qué proceso se le asigna?

**Comment by LeandroCarbajales** [comment]
> cuando me llega la dirección física del stdin más la cadena a guardar, existe la posibilidad que al hacer el void* data + direcFisica (la del stdin) sea un marco asignado a otro proceso?

Estarías realizando mal la traducción de direcciones en CPU si ese fuera el caso.

> Los char provenientes de los STDIN deben guardarse en una tabla de páginas nueva? Si es así, a qué proceso se le asigna?

No se a qué te referís con guardar los char provenientes en una tabla de páginas. Se escribirían en los marcos correspondientes a las páginas del proceso que originó el STDIN.

**Comment by fmigliavacca** [comment]
Respecto a la segunda respuesta, claro, STDIN me manda una dirección física y un string que pretende que guarde en esa dirección física. Lo que digo es, esa dirección física, es un marco, que se supone que debe pertener a la tabla de paginas del proceso que originó la stdin, okay. Entonces, la STDIN cuando se crea, ya directo pide cuantos marcos va a necesitar y los pongo en su tabla de páginas? El proceso generado por el STDIN hace que el STDIN me pase el PID? O me lo pasa kernel? O primero se crea el STDIN y en algún momento ese STDIN hará un resize como cualquier otro proceso y ahí asignaré sus marcos y cuando me pida guardar la cadena la guardaré en uno de esos marcos?

**Comment by iago64** [comment]
Buenas! 

No, las páginas ya las van a tener reservadas previamente con un llamado a RESIZE del proceso.
Lo único que tienen que hacer en la interfaz STDIN con el string que ingresan por teclado es mandárselo a la memoria para que esta lo escriba en la dirección que corresponde, es decir, la que calculo previamente la CPU.

Saludos.-

**Comment by fmigliavacca** [comment]
Perfecto, entonces, la llamada a la stdin es parte de un proceso que previamente hizo un resize. Entonces io le manda a memoria la dirección física exacta, que previamente obtuvo al pasarle a CPU la dirección lógica o algo así y la mmu le devolvió la física que esta le envió a memoria, correcto?

**Comment by iago64** [comment]
Exactamente
