### ISSUE TITLE
Acerca de los retardos en memoria

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3807]
Buenas dejo un par de citas del enunciado seguido de una rafaga de preguntas binarias

### 📔 Citas del enunciado/videos

> Acceso a espacio de usuario
> Esta petición puede venir tanto de la CPU como de un Módulo de Interfaz de I/O, es importante tener en cuenta que las peticiones pueden ocupar más de una página.
> El módulo Memoria deberá realizar lo siguiente:
> Ante un pedido de lectura, devolver el valor que se encuentra a partir de la dirección física pedida.
> Ante un pedido de escritura, escribir lo indicado a partir de la dirección física pedida. En caso satisfactorio se responderá un mensaje de ‘OK’.
> Cada petición tendrá un tiempo de espera en milisegundos definido por archivo de configuración

> Acceso a tabla de páginas
> El módulo deberá responder el número de marco correspondiente a la página consultada.
> 

> Ajustar tamaño de un proceso
> Al llegar una solicitud de ajuste de tamaño de proceso (resize) se deberá cambiar el tamaño del proceso de acuerdo al nuevo tamaño. Se pueden dar 2 opciones:
> Ampliación de un proceso
> Se deberá ampliar el tamaño del proceso al final del mismo, pudiendo solicitarse múltiples páginas. Es posible que en un punto no se puedan solicitar más marcos ya que la memoria se encuentra llena, por lo que en ese caso se deberá contestar con un error de Out Of Memory.
> Reducción de un proceso
> Se reducirá el mismo desde el final, liberando, en caso de ser necesario, las páginas que ya no sean utilizadas (desde la última hacia la primera).
> 

> 

> Ante cada petición se deberá esperar un tiempo determinado a modo de retardo en la obtención de la instrucción, y este tiempo, estará indicado en el archivo de configuración.

De todas esta citas me queda claro que si tiene que haber retardo en el pedido de instrucciones y en el acceso al espacio de usuario pero:

1) hay retardo en acceso a tabla de paginas?
2) hay retardo en ajuste de tamaño de preoceso?
3) hay algun retardo mas que me comi?

**Comment by iago64** [comment]
Buenas! Cómo va?

Justamente está en el enunciado y lo citaste: 

> Ante cada petición se deberá esperar un tiempo determinado a modo de retardo en la obtención de la instrucción, y este tiempo, estará indicado en el archivo de configuración.

No importa lo que te pidan, vos le aplicas el retardo.

Saludos.-

**Comment by GonTurri** [comment]
ah ok pero entonces tambien en las operaciones de kernel de crear y finalizar proceso tambien? todas absolutamente todas?

**Comment by iago64** [comment]
Si, a todo, no te la compliques de más.
