### ISSUE TITLE
Duda sobre el log de ampliación de memoria

### ISSUE THREAD

**Issue by ManuRodri01** [sisoputnfrba/foro#3808]
Buenas, esta es una duda muy simple. El log 

> Ampliación de Proceso: “PID: <PID> - Tamaño Actual: <TAMAÑO_ACTUAL> - Tamaño a Ampliar: <TAMAÑO_A_AMPLIAR>” 

Se pone siempre que se intenta hacer una ampliación o si efectivamente se hace. Por ejemplo, si yo hago un resize(40) y la respuesta es Out of Memory; debería hacer el log por el intento de ampliación o no debería realizarlo porque no fue efectiva la ampliación?

Saludos

**Comment by LeandroCarbajales** [comment]
Buenas!
Ante la duda hagan el log igualmente, luego podremos corroborar que esa petición desencadenó el error que termina en la finalización del proceso.

**Comment by ManuRodri01** [comment]
Muchas gracias
