### ISSUE TITLE
Reducción de memoria

### ISSUE THREAD

**Issue by SantiPetro** [sisoputnfrba/foro#3810]
Buenas, como va? Nos surgió una duda con esta parte del enunciado: "Reducción de un proceso: Se reducirá el mismo **desde el final**, liberando, en caso de ser necesario, las páginas que ya no sean utilizadas (**desde la última hacia la primera**)." 

No entendemos si tenemos que reducir el tamaño desde el último marco de la memoria hasta el primero (obviamente buscando los marcos que sean del proceso) o ir liberando desde lo último que se agregó de ese proceso hasta lo primero.

Muchas gracias! Saludos.

**Comment by LeandroCarbajales** [comment]
Buenas!
Te daría la misma respuesta que en #3801 .

Avisame si te sirve la respuesta o quedan más dudas.
Saludos!
     Lean

**Comment by SantiPetro** [comment]
Hola Lean, como vas?
Claro, lo que no entendemos es si el orden en el que se eliminan es dependiendo del número de marco (de mayor a menor) o si el orden depende de como se fueron asignando las páginas. Por ej: si primero asigno 0, después 1 y 2. ¿Elimino primero 0 o 2?

**Comment by SantiPetro** [comment]
Bárbaro. Muchas gracias Lean!

**Comment by LeandroCarbajales** [comment]
Joya! Cierro el issue ya que supongo la duda fue resuelta :)
