### ISSUE TITLE
Dudas sobre memoria

### ISSUE THREAD

**Issue by tomipodo** [sisoputnfrba/foro#3811]
Buenas, como andan? Tengo algunas dudas sobre la memoria.
1. No me queda claro si la dirección física que obtiene la MMU, es una dirección relativa al proceso o es la dirección fisica de la memoria. Entiendo que la dirección física es el número de página y el desplazamiento por separado, relativos al proceso, no? Porque la CPU no puede saber en que marco se guarda el proceso. 
2. Al hacer un MOV_OUT reg_direccion reg_datos, si por ejemplo, el reg_datos es EAX = 3, este es un uint32_t pero el 3 no pesa 4 bytes. No entiendo si cuando lo guardo en la dirección pedida tengo que guardar 4 bytes o simplemente lo que pese el valor (en este caso el 3) 
 
Gracias, saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- La dirección fisica es la dirección del _frame_ + desplazamiento.

2.- Tenes que guardar los 4 bytes, la forma mas facil para no complicarse es trabajarlo como un puntero a algo de 4 bytes, entonces vos simplemente copias memoria sin preocuparte que tenes ahi.

Saludos.-

**Comment by tomipodo** [comment]
Claro, respecto a la pregunta 1, porque me estuve mareando bastante con esto:
La CPU le tiene que pedir los frames de esas páginas del proceso a la memoria para calcular la dirección física, no?

**Comment by iago64** [comment]
Buenas! Cómo va?

Exacto. la CPU le pide a la memoria los frames correspondientes para calcular las direcciones físicas.

Saludos.-

**Comment by tomipodo** [comment]
Bárbaro, muchisimas gracias. Saludos!
