### ISSUE TITLE
interfaces STDIN + múltiples interfaces al mismo tiempo

### ISSUE THREAD

**Issue by fmarkiw** [sisoputnfrba/foro#3812]
El enunciado dice lo siguiente:
"Las interfaces STDIN no van a esperar ninguna unidad de trabajo, ya que las mismas van a quedarse
esperando que el alumno ingrese un texto por teclado. Este texto se va a guardar en la memoria a
partir de la dirección física indicada en la petición que recibió por parte del Kernel."

La duda es: ¿Qué hago si de kernel me llega el pedido de crear n interfaces STDIN una detrás de la otra? El problema es que como STDIN depende de la terminal en una máquina física (y ésta solamente posee una terminal) y necesito esperar a que por dicha terminal se ingrsen valores, no podría atender a la interfaz m+1 hasta que la m no halla recibido un valor por terminal.

Pensé en que el uso de la terminal dependería de un semáforo para asegurar que lo que escribas lo lea la interfaz que le corresponda y que no cambie la interfaz mientras estás queriendo tratar con otra. Otra alternativa sería una lista de interfaces activas queriendo usar la terminal y que se les vaya habilitando el uso mediante FIFO.

De ésta duda se desprende otra: ¿Puedo tener n pedidos para usar una interfaz específica? de ser así ¿habría que poner a los pedidos de uso de dicha interfaz en una cola y a medida que se atiendan se va iterando por la cola?

Aclaro por las dudas que un ejemplo sería tener una interfaz llamada INT34 que recibe 5 pedidos que llegan de kernel uno detrás del otro para usarla.

Desde ya, muchas gracias.

**Comment by iago64** [comment]
Buenas!

Respecto a las multiples STDIN, la respuesta es la misma que para el issue #3776

Respecto a los múltiples pedidos, las interfaces trabajan mono hilo, es decir, atienden de a 1 los pedidos, por lo que es responsabilidad del kernel encolar las peticiones y mandarselas de a 1 a la interfaz cuando esta le avise que termino con el pedido anterior.

Saludos.-

**Comment by fmarkiw** [comment]
Listo, muchas gracias por responder. 

Algo que no me había terminado de quedar en claro tampoco era que en realidad el kernel no instancia a las interfaces. Se levantan las interfaces cada una por su cuenta en distintas terminales con distintos archivos de config y distintos nombres y los programas hacen referencia a esas interfaces. Gran parte de la confución venía por ese lado.

**Comment by iago64** [comment]
Si la duda esta resuelta, no se olviden de cerrar el issue.
