### ISSUE TITLE
Duda sobre la TLB

### ISSUE THREAD

**Issue by julienf04** [sisoputnfrba/foro#3813]
### Buenas!

Tengo una duda con respecto al momento en el que la MMU se debe fijar en la TLB si tiene la info de la página solicitada (TLB Hit) o no (TLB Miss).

Según un funcionamiento más real de una MMU (hasta donde sé):

1. Se le solicita la info de la página a la Memoria.
2. Inmediatamente después de hacer la solicitud del paso 1, se fija si está en la TLB. Si lo está (TLB Hit), se cancela la solicitud a memoria, y sino espera a que llegue la info de la pagina para ponerla en la TLB.

Según como está escrito el enunciado, interpreto que la secuencia debe ser al revés:

1. Se fija si se encuentra la info de la página en la TLB.
2. Si no se encuentra, la pide a memoria.

El funcionamiento más real de un sistema difiere con mi interpretación del enunciado, entonces, ¿cuál secuencia es la que debería implementar?

**Comment by iago64** [comment]
Buenas! Cómo va?

Tienen que implementar lo que esta en el enunciado.

Recuerden que:

> Debido al fin académico del trabajo práctico, los conceptos reflejados son, en general, versiones simplificadas o alteradas de los componentes reales de hardware y de sistemas operativos vistos en las clases, a fin de resaltar aspectos de diseño o simplificar su implementación.

Saludos.-

**Comment by julienf04** [comment]
Graciasss!
