### ISSUE TITLE
Posibles Fallas relacionadas con Dirección Lógica errónea

### ISSUE THREAD

**Issue by DamianBlum** [sisoputnfrba/foro#3814]
# Dirección Lógica errónea
Problema: queríamos saber con mi equipo si podían pasar estas dos situaciones que ya dependen de la dirección lógica que se ponga en la instrucción:

- Que ponga una dirección lógica que refiera a una pagina que no tiene
ejemplo con paginas de 4 bytes, resize 10 me da 3 paginas y EAX al hacer en la MMU el calculo de la pagina le va a dar una que no tiene
> SET EAX 1240 
> SET BX 1 
> RESIZE 10 
> MOV_OUT(EAX,BX)

-Que ponga una dirección lógica que refiere a una pagina que tiene pero ya no (también paginas de 4 bytes)
>SET EAX 7
> SET BX 1
> RESIZE 10
> RESIZE 4
> MOV_OUT(EAX,BX)

En estos caso, tengo que asumir que en las pruebas la dirección lógica puede ser cualquier cosa o que tendría que tener en cuenta?
Muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

Esas situaciones no se tienen que tener en cuenta, no vamos a hacer pruebas con direcciones de memoria inválidas.

Saludos.-

**Comment by DamianBlum** [comment]
Dale, muchas gracias!
