### ISSUE TITLE
logs de lectura escritura de cpu

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3815]
Buenas! no entiendo muy bien como quieren que implementemos este log, mas que nada en el caso de lectura escritura multipagina. 

### 📔 Citas del enunciado/videos

> Lectura/Escritura Memoria: “PID: <PID> - Acción: <LEER / ESCRIBIR> - Dirección Física: <DIRECCION_FISICA> - Valor: <VALOR LEIDO / ESCRITO>”.

En el caso de leer escribir mas de una pagina ustedes quieren que vayamos logeando de a pedacitos por ejemplo:
PID: 5- Acción: LEER - Dirección Física: 10 - Valor: UT
PID: 5- Acción: LEER - Dirección Física: 12 - Valor: NSO

quieren que una solo log global desde la direccion inicial solicitada como por ejemplo

PID: 5- Acción: LEER - Dirección Física: 10- Valor: UTNSO

Desde ya muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

Idealmente la primera opción, pero si no les queda otra porque lo implementaron de una forma muy compleja la segunda opción nos sirve de todas formas.

Saludos.-

**Comment by GonTurri** [comment]
Ok! Creo que lo deberíamos poder hacer sin problemas, cualquier cosa vuelvo a preguntar. Para validar, entonces el void* que vaya a leer/escribir desde CPU lo voy a logear de esta forma con un formato %s no?

**Comment by iago64** [comment]
Buenas!

No, los valores de los logs son en su mayoría números por lo que tenes que imprimirlos con `%d` y el caso del copy-string que ahi si es un string y va con `%s`

Saludos.-

**Comment by GonTurri** [comment]
OK! vamos viendo. Pero entonces este log tambien iria en cpu en las instrucciones IO_STDIN_READ/IO_STDOUT_WRITE?
o solo para MOV_IN MOV_OUT y COPY_STRING

Muchas gracias!

**Comment by iago64** [comment]
No son obligatorios en las IO, si los quieren agregar no hay problema.
