### ISSUE TITLE
Dudas log_debug + error al inicializar modulos (desconexion repentina)

### ISSUE THREAD

**Issue by GianLema** [sisoputnfrba/foro#3816]
Buenass, teniamos dos consultas con mi grupo a ver si nos pueden ayudar:

1) al correr/inicializar los modulos (luego de la 1ra vez) algunos se suelen desconectar por si solos. En un soporte pasado hablamos con Milton quien nos conto que probablemente era que los logs se bloqueaban si es que a nuestro código nos saltaba un error y cosas feas y nos recomendó agregar un if antes de las funciones de inicializar los modulos para que no se bloqueen (adjunto el if para dar contexto):

![Captura de pantalla 2024-06-01 112306](https://github.com/sisoputnfrba/foro/assets/129530201/a11833c1-0dec-4030-9487-b8ab2deeb796)
```c
int main(int argc, char** argv) {
     if (argc < 2) {
         fprintf(stderr, "Uso: %s <ruta_archivo_configuracion>\n", argv[0]);
     }
     inicializar_kernel();
     return EXIT_FAILURE;
 }
void inicializar_kernel(){   ...
```

CORRECCION!! ADJUNTE OTRO IF:
```c
if(setsockpt(socket_cliente, SOL_SOCKET, SO_REUSEADOR, &(int){1}, sizeof(int)) < 0)
herror("setsockopt(SO_REUSEADOR) failed");
```
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

2) para no tener 847396187 logs de control aparte de los minimos y obligatorios, decidimos utilizar "log_debug" para nuestros logs propios. El tema es que no se muestran en pantalla ni sabemos si se deberían mostrar en pantalla siquiera. Como los implementamos? Como funcionan realmente? Que resultado deberíamos esperar si no es un mensaje en la terminal?

![Captura de pantalla 2024-06-01 113817](https://github.com/sisoputnfrba/foro/assets/129530201/b0d0ecb9-55e0-422d-ba88-a991190beda3)

```c
log_info(log_kernel,"DESPUES FINALIZAR PROCESO COLA READY: %d",queue_size(cola_ready));
        promover_proceso_new_a_ready_post_fin();
    }
    if(buscar_finalizar_por_pid(cola_blocked, pid) == false) {
        log_debug(log_kernel,"no se ha encontrado el proceso");
    }else{
        log_debug(log_kernel,"PROCESO %d FINALIZADO",pid);
        promover_proceso_new_a_ready_post_fin();
```

**Comment by iago64** [comment]
Buenas! Cómo va?

Vamos por orden de las preguntas

1.- Un log no debería traerles ningún problema con las conexiones a menos que manden a loguear algo que les genere un segment fault.
Las desconexiones, se dan de manera "aleatoria" o es algo que pueden debuguearlo? Porque capaz están teniendo algún `close()` que no estan viendo.


2.- El tema de los log level, importa mucho como los creen, es decir, cuando hacen el llamado a la función `log_create()` es fundamental lo que le pasen al último parámetro que es el `log_level`, fijense que es un enum que esta en el [log.h](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/log.h)

Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas @GianLema !
Pudieron ver la respuesta de @iago64 ? Les resuelve las dudas?

**Comment by GianLema** [comment]
Sisi mildis, lo de los log debug entendimos y lo primero creo que es mejor presentarlo en algun soporte. Gracias!
