### ISSUE TITLE
IOs: Desconexión temporal

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3817]
Buenas, en nuestro TP cuando iniciamos una interfaz, por ej, una generica, la misma se conecta a kernel y memoria. Bueno, en el caso de la IO generica, se queda esperando solicitudes de kernel y va retornando cuando termina. Si queremos desconectar la interfaz presionamos ctrl+c. Mi pregunta es si en algún momento van a querer simular la desconexión "temporal" de una interfaz, osea que quieran desconectarla momentáneamente y luego volver a conectar la misma con el mismo nombre. Esto en nuestro TP, al menos como esta ahora, no funcionaria del todo bien porque: 
1)La única forma de desconectar la interfaz es con "ctrl+c", si se quisiera simular una reconexión de la misma, se tendría que conectar abriendo otra consola o en la misma en la que finalizamos la anterior con el mismo nombre lo cual traería problemas en kernel por lo que comente en otro issue (el #3721, esta casi al final del mismo), en donde kernel no detecta la desconexión de una interfaz a menos que se le mande un proceso por error.
2) Justamente en nuestro tp la interfaz se desconecta con ctrl+c, no hay ningún comando "DESCONECTAR_INTERFAZ" que permita dejar levantado el programa de la interfaz para luego hacer "CONECTAR_INTERFAZ". Algo así como el iniciar y detener planificación. La unica forma de llegar a "simularlo" es como mencione en el punto 1, instanciando otra consola y poniendo el mismo nombre lo cual trae problemas en la gestion de IOs en kernel.

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- "El problema" lo van a tener independientemende de si es en la misma terminal o es en otra, ya que uds no tienen forma de enterarse que se les desconectó una interfaz a menos que le pidan algo o justo esten en el intervalo entre que mandan algo y estan esperando la respuesta y ahi, no sería problema, como les dijimos en el otro issue, ese comportamiento no representa un problema lógico para el funcionamiento del TP.

2.- No hacía falta que tuvieran ese comando, con lo cual, esta bien como estan planteando la "simulación", eventtualemente lo que puede pasar es que esten ejecutando manden algo a una interfaz, esta termine, se desconecte, se le mande otro proceso, no puedan hacer nada porque la interfaz esta desconectada, despues de eso la conecten nuevamente y despues manden un 3er proceso que intente ejecutar algo y pueda porque esta la interfaz conectada nuevamente.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas @rood8592 !
Pudieron ver la respuesta de @iago64 ? Les resuelve las dudas?

**Comment by LeandroCarbajales** [comment]
Cierro el issue por inactividad, cualquier cosa pendiente lo vuelven a abrir.
