### ISSUE TITLE
Kernel: Manejo Recursos

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3818]
Buenas, 
Tenemos un par de dudas con respecto al manejo de recursos en kernel y son las siguientes:
1) Si yo tengo un recurso con dos instancias iniciales y tengo 12 procesos que le hacen wait a dicho recurso y ninguno le hace signal. Eso significa que los dos primeros que lleguen podrán utilizarlo y los otros 10 quedaran bloqueados con el numero de instancias en -10, como se haría para que empiecen a salir de la cola de bloqueados? ¿Si hay algún proceso que le hace un unico signal a dicho recursos no alcanzaría, no es así? ¿Necesitaría mínimo 11 signals para salir de esa situación y que se desbloquee al menos un proceso? O bueno si los dos procesos que agarraron una instancia del mismo finalizan quedaría, si no me equivoco en -8 el nro instancias (no estoy seguro del -8, lo pregunto en la duda nro 3).
2) Si yo tengo un proceso que hace un wait y posteriormente un signal pero no dejo que éste ultimo se haga porque finalizo prematuramente ese procesos desde consola, debo liberar todos los recursos a los que haya hecho wait (tanto los que no deje que se liberen con signal como los recursos a los cuales el proceso no les iba hacer signal de todas formas), no es así? ¿Y lo mismo pasaría para un proceso que hace puros waits y llega a exit de manera normal?
3) Tomando de ejemplo la situación del punto 1, cuando esos dos procesos que llegaron primero terminen, solo se liberan 2 instancias de dicho recurso que tomaron, no es así? Suponiendo que cada uno hizo un único wait del mismo. Es decir que el numero de instancias de dicho proceso quedaría en -8.

**Comment by iago64** [comment]
Buenas! Cómo va?

Antes que nada gracias por numerar las preguntas, segundo ~Francia~ vamos con las respuestas:

1.- Se van a empezar a liberar a medida que terminen los procesos, al momento que terminen los 2 primeros, al ir a EXIT el kernel les "expropia" los recursos y por lo tanto "ejecuta" SIGNAL y va desbloqueando los que estan bloqueados.

2.- Exacto, si hiciste WAIT a un recurso, y no llegaste a hacerle SIGNAL porque algo malo paso, como por ej, hiciste un RESIZE y tiraste un `Out of memory`, al llegar a EXIT el Kernel "ejecuta" ese SIGNAL que no hiciste.

3.- Si, a medida que van finalizando van liberando esos recursos por lo tanto es como si ejecutaran el SIGNAL correspondiente y por lo tanto empiezan a desbloquear.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas @rood8592 !
Pudieron ver la respuesta de @iago64 ? Les resuelve las dudas?

**Comment by LeandroCarbajales** [comment]
Cierro el issue por inactividad, cualquier cosa pendiente lo vuelven a abrir.

**Comment by rood8592** [comment]
Buenas, hay algo que no me queda claro. El numero de instancias de un recurso puede ser, por ejemplo, -10 lo cual significaria que tengo 10 procesos bloqueados esperando ese recurso. En caso de que algun otro me haga UN SOLO SIGNAL, yo ya puedo desbloquear al primero que este en la cola incrementando el valor a -9? O el numero de instancias debe ser mayor a 0 para yo poder desbloquear al siguiente proceso que este en la cola?
