### ISSUE TITLE
Se me reinicia la PC cada vez que abro la VM.

### ISSUE THREAD

**Issue by MartinVulta** [sisoputnfrba/foro#3819]
Hola buenas noches, mi problema es que cada vez que abro la VM, a los pocos minutos se me apaga la PC y me aparece la pantalla azul de error. Nada, no puedo trabajar básicamente. Ya probe reiniciandola tanto la PC como la VM una banda de veces, le cambia las especificaciones, y, como se me cerraba muchas veces, tuve que reparar los archivos de esta. A lo mejor debería crear otra VM.

### 📦 Especificaciones de la VM
- Versión de VirtualBox: la ultima
- Memoria RAM asignada: 2048 MB

### 🖥️ Especificaciones del host
- Sistema Operativo y versión: Windows 10
- Memoria RAM: 16GB
- Procesador: AMD Ryzen 5 3500 6-Core Processor

### 💻 Logs

![Si obtuviste por consola o por pantalla algo que pueda ayudar a darnos más contexto, no subas capturas de pantalla, copiá el texto y pegalo acá. Podés darle formato código con (Ctrl + 'e'). Si el output es muy extenso, sentite libre de adjuntar un archivo de texto en su lugar.](https://support.content.office.net/en-us/media/4c10ecfd-3008-4b00-9f98-d41b6f899c2d.png)

**Comment by iago64** [comment]
Buenas! Cómo va?

Consulta, por esas casualidades tenes algun mensaje de error o algo o simplemente inicias la VM y se reinicia la PC sin nada mas ni un blue screen o algo?

Saludos.-

**Comment by MartinVulta** [comment]
Ah veces apenas la inicio ya se me reinicia la PC, CON el blue screen, y otras veces logro trabajar un poco y de la nada blue screen

**Comment by iago64** [comment]
Buenas!

Por esas remotísimas casualidades podrías intentar sacarle una foto o copiar el error del blue screen? Porque me suena a que es algún tema de errores entre Windows y Virtual Box y eso es complicado de seguir por el foro y menos sin ver ningún error.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Veo que gran parte del texto estaba entre `<!--` y `-->`, los cuales son comentarios HTML y no se van a renderizar en el issue.

¿El blue screen es el que nos mostrás en la imagen? ¿El error es `MANUALLY_INITIATED_CRASH`? Pregunto porque el link a la imagen parece venir de una página de Microsoft.

También, ¿podrías especificar la versión de VirtualBox? Ya que con decir "la última" es una descripción bastante vaga: cada pocos meses salen versiones nuevas, por lo que quizás era "la última" al momento de descargarla pero no ahora.

Esto lo pregunto porque la versión 7.0.16 tiene un problema de BSOD que se resolvió hace re poquito en la 7.0.18: https://github.com/sisoputnfrba/foro/issues/3649#issuecomment-2123014034

**Comment by MartinVulta** [comment]
Hola, uh no me di cuenta de los comentarios.
Esa no es la pantalla que me aparece a mi (no le puedo sacar captura porque la PC se me esta reiniciando), es el tipo de error que me aparece, cuya captura la saque de la pagina de microsoft, a la que entre porque en la pantalla azul que me da a mi ponia ese link.
Ah y la version que tengo es 7.0.14 r161095, la llame 'la ultima' porque en su momento (al inicio de este curso en marzo), habia bajado la ultima version del momento, no se si la actualizaron.
Desde ya muchas gracias.

**Comment by iago64** [comment]
A la vista de las nuevas evidencias, te diría que pruebes de desinstalar completamente Virtual Box, reinicies la PC e instales desde 0 la última version posta posta.

Saludos.-

**Comment by MartinVulta** [comment]
ok muchas gracias
