### ISSUE TITLE
Hilos: ¿detach o join?

### ISSUE THREAD

**Issue by MariaSolGaraventa** [sisoputnfrba/foro#3820]
Buenas noches! Quería saber bien cuál era la diferencia entre `pthread_join()` y `pthread_detach()`, y cuando conviene usar cada uno o cómo combinarlos.

Busqué en el foro y no hay respuesta que me aclare directamente la duda, y la charla tampoco, y la descripción que da en `threads.h` tampoco. Muchos "y", jaja. 

Gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Te recomiendo que veas el video de la [Charla de Threads y Sincronización](https://docs.utnso.com.ar/guias/linux/threads) que es donde explicamos el tema y si no mal recuerdo hasta damos algunos ejemplos.

Saludos.-

**Comment by MariaSolGaraventa** [comment]
Mmmm... Lo volví a ver y sigo con dudas. Si tengo varios hilos de conexión con distintos módulos, ¿podría hacer todos `detach` y para el último hilo hacer un `join`, cosa de que no se me termine el programa? ¿O hay alguna ventaja de los `join` que debería aprovechar (o al revés)?

**Comment by iago64** [comment]
Buenas!  Cómo  va?

Mientras el hilo `main` no muera podes hacer todos los demás hilo `detach`.

Saludos.-

**Comment by MariaSolGaraventa** [comment]
Buenísimo, intentamos. Cualquier cosa abriremos otro issue :). Gracias!!
