### ISSUE TITLE
TLB: dato ocupa varías paginas

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3821]
Buenas,
Tengo una duda con respecto a la TLB. Cuando yo tengo un dato que ocupa más de una página, supongamos que ocupa 6 y tres estan en la tlb y los otros 3 no. Debo loggear 3 "TLB-HIT", 3 "TLB-MISS" y luego los 3 que fueron MISS añadirlos a la TLB?

**Comment by iago64** [comment]
Buenas!

Si, en el caso que mencionas si, igual como consejo, vean cada traducción como una operación aislada, es decir, si tienen que traducir las direcciones de 3 páginas, véanlas como 3 traducciones independientes, entonces eso les va a simplificar el hecho de la TLB y los accesos a las tablas de páginas.

Saludos.-

**Comment by rood8592** [comment]
Buenas, por ahora tenemos pensado el siguiente paso a paso (al menos para escritura en memoria):
1) Averiguamos el nro pagina de la direccion logica pasada, dependiendo de lo que nos reste en esa primer pagina (tam_pagina- desplazamiento) y el tamaño del dato, vemos si entra todo en esa pagina o necesito más (averiguo cuantas necesito en total). Teniendo el nro paginas totales que necesito, si la dir. logica me lleva a la pagina 40 y necesito 4 paginas, entonces necesito la 40, 41, 42 y 43.
2) Voy viendo de las que necesito si estan en la tlb, si están (TLB HIT) me guardo su marco en una lista aparte, si no están (TLB MISS) y las agrego a un paquete para mandarselo a memoria.
3)Memoria lo recibe y me devuelve un paquete con las paginas y sus marcos asociados.
4)Todas las que me devolvio memoria en un paquete las voy agregando una por una a la TLB (me guardo la lista generada por recibirPaquete del tp0)
5)Luego junto ambas listas, de las que estaban en la TLB y las que no, me aseguro que quede ordenada la lista por pagina.
6)Esta lista se la pasamos a una funcion encargada de armar structs que contienen (direccionFisica, base y tamaño) y agregarlos a un paquete a enviar a memoria. El paquete contendrá primero el dato a escribir y luego una cadena struct con los datos mecionados que dependera de en cuantas partes se dividio el dato. En el punto 5 aclaro que la lista debe estar ordenada para que la direccion fisica de la primera pagina se calcule de forma correcta teniendo en cuenta que es en la unica en la que el desplazamiento podria no ser 0, en la contiguas a ellas que necesite para almacenar el dato el desplazamiento será 0 ya que las utilizare desde el principio.
Lo mando para ver si no nos estamos haciendo mucho lio con esto de las traducciones y la TLB.

**Comment by iago64** [comment]
Buenas! Cómo va?

No es precisamente lo más aislado que se me ocurre porque después arman un paquete con todos los pedidos a la memoria, pero si eso les funciona y hacen todos los retardos correspondientes a los distintos accesos a memoria lo pueden dejar así

Saludos.-

**Comment by GonTurri** [comment]
Buenas! Me sumo sobre el último comentario que dijiste. Si en un acceso a espacio de usuario están involucrados por ejemplo 3 marcos. Entonces tendríamos que hacer 3 retardos de memoria? O eso solo se hace para el acceso a la tabla de páginas?

**Comment by rood8592** [comment]
Me surgió otra duda: ¿el retardo es solo para "Acceso a espacio de usuario"? ¿o para todas las solicitudes? Si es para todas las solicitudes, entonces bastaría con la solución que plantee, que la lista se recorra teniendo en cuenta ese retardo elemento por elemento?

**Comment by LeandroCarbajales** [comment]
@GonTurri Pensalo de esta manera, si estás accediendo a 3 marcos distintos, estás haciendo 3 peticiones a memoria, y bajo la lógica del enunciado son 3 retardos. Por ende, esto aplica tantos para el acceso a tablas, como para el acceso a espacio de usuario.

@rood8592 El retardo es para todos los pedidos a la memoria. Acabamos de publicar una errata ya que nos dimos cuenta que no estaba lo suficientemente claro en el enunciado.

**Comment by LeandroCarbajales** [comment]
Por las reaccione asumo que las dudas están resueltas :)
Cierro el issue, cualquier cosa lo vuelven a abrir.
