### ISSUE TITLE
Dudas sobre la TLB

### ISSUE THREAD

**Issue by julienf04** [sisoputnfrba/foro#3822]
### Buenas!

Tengo unas dudas sobre el algoritmo de reemplazo y las políticas que debe seguir la TLB.

1. ¿La TLB puede almacenar referencias válidas a páginas de un proceso que no esté en ejecución?

Si la respuesta 1 es sí:

2. Cuando un proceso llega a EXIT, las referencias a sus páginas en la TLB serían datos basura. ¿Debemos reemplazar primero las entradas que contengan datos basura y, en caso de que no haya ninguna, usar el algoritmo de reemplazo, o debemos seguir el algoritmo de reemplazo **SIEMPRE**, ignorando que haya datos basura en la TLB?

3. ¿La TLB debe seguir una política de reemplazo local (sólo pueden ser reemplazadas las entradas con datos basura y las entradas del mismo proceso que generó el Page Fault) o de reemplazo global (puede ser reemplazada cualquier entrada de la TLB, sin importar de qué proceso sea)?

**Comment by iago64** [comment]
Buenas! Cómo va?

Si, la TLB puede tener referencias de otros procesos que no es el que esta en EXEC en ese momento.

La implementación de la TLB es "la más simple", es decir, utiliza reemplazo global, entonces no les importa de que proceso es, uds reemplazan y ya independientemente de que tengan procesos que llegaron a EXIT, ya que en algún momento esas entradas se van a reemplazar.

Saludos.-

**Comment by julienf04** [comment]
Graciass!!
