### ISSUE TITLE
Un proceso se bloquea ante un TLB Miss?

### ISSUE THREAD

**Issue by julienf04** [sisoputnfrba/foro#3824]
### Buenasss!

Si ocurre un TLB Miss, ¿el proceso debe bloquearse (el estado del proceso pasa a bloqueado) hasta que la referencia a la página consultada se encuentre en la TLB?

**Comment by iago64** [comment]
Buenas! Cómo va?

No se tiene que bloquear.

Saludos.-

**Comment by julienf04** [comment]
Gracias! ;)
