### ISSUE TITLE
Acceso a espacio usuario

### ISSUE THREAD

**Issue by fmigliavacca** [sisoputnfrba/foro#3825]
Hola! Tengo una duda sobre el acceso a espacio usuario por parte del módulo de memoria. 
1-  Tengo entendido que la complejiad de la paginación simple a la hora de codear en el tp, es que si por ejemplo, me piden que guarde una cadena de 16 bytes y tengo paginas de 8 bytes, voy a necesitar 2 paginas. Entonces si la dirección física que me pasaron es el marco 1, yo debería copiar los primeros 8 bytes en el marco 1, y qué debería hacer con los otros 8 bytes? Copiarlos en la próxima página disponible más cercana? O sea, si el marco 1 era la página 24 en mi tabla de páginas, yo debería copiar los otros 8 bytes en la página 25 por ejemplo? Aunque la página 25 tenga por ejemplo el numero de marco 100? O no hay ningún criterio para elegir qué página utilizar para los otros 8 bytes? 
2 - Por ejemplo si yo tuviera estos mismos 16 bytes de cadena y tengo el problema de donde almacenar los otros 8, cómo sé que el marco donde decida almacenar los otros 8 bytes estén vacios y no contengan otros datos? Debería hacer una estructura donde almacenar qué páginas asignadas a mi proceso contienen datos y cuales no? Y después, cómo sabría CPU que yo almacené esos 16 bytes en dos páginas distintas? Y que cuando quiera acceder a ese dato, me va a tener que pedir esas dos páginas?
3 - Otra pregunta, es posible que la dirección física que me pasen no sea la posición 0 de un marco? O sea que la dirección física sea marco + desplazamiento y desplazamiento no valga 0? Yo supongo que si pero por las dudas pregunto.

**Comment by LeandroCarbajales** [comment]
Buenas!
1- Si vos querés guardar una cadena de 16 bytes, en definitiva querés modificar 16 bytes de tus DL, la primer dirección lógica es la que te viene en la instrucción, la última sería DL+15. Por la lógica misma de paginación (y siguiendo tu ejemplo de páginas de 8 bytes y comenzando en la página 24), la última dirección lógica caería en la página 25. Qué significa esto? Que para ejecutar esa instrucción, terminarás haciendo más de una petición a memoria (ya que estás queriendo acceder a más de una página), cada una con su respectiva traducción de direcciones, y cada página puede estar en cualquier marco de la Memoria.

2- Las mismas DL siempre se mapean a las mismas DF, por lo tanto, si no escribiste nada en esas DL no estarías pisando nada. Igualmente esto no es algo que necesiten chequear, la memoria está para usarse a gusto y piacere, incluído usarla "mal" y pisar otros datos. El módulo memoria no tiene por qué saber nada de esto, la CPU debe saber pedirle los datos que quiere.

3- Sí, de hecho es un caso muy normal, siguiendo esta lógica, expando tu ejemplo inicial. Si tenés una cadena de 16 bytes y páginas de 8 bytes pero querés guardarla comenzando "por la mitad" de una página (offset 4). Esta cadena estaría repartida en 3 páginas distintas en lugar de 2.

**Comment by fmigliavacca** [comment]
1- Ahhh entonces con ese mismo ejemplo, si se guardó todo el dato de 16 bytes y la memoria quiere acceder a ese dato, ya no bastaría con hacer una sola petición especificando el principio de la dirección lógica y el tamaño? Debería hacer por lo menos dos peticiones? O con un solo send yo desde memoria ya debería pasarle el dato completo? Xq poder, se puede

**Comment by LeandroCarbajales** [comment]
Sí, poder se puede. Mientras cumpla con el criterio de que estás haciendo 3 accesos a espacio de usuario (con sus respectivos logs y retardos) pueden implementarlo como mejor crean conveniente.

**Comment by LeandroCarbajales** [comment]
Buenas! @fmigliavacca 
Quedó resuelta la duda? Se puede cerrar el issue?

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, ante cualquier consulta pueden abrir uno nuevo referenciando éste. Saludos
