### ISSUE TITLE
Manejo de memoria: LIttle Endian vs Big Endian

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3826]
Buenas! vengo luego de realizar una primera iteracion de las instrucciones que leen y escriben a memoria y me encontre con algo bastante peculiar con los tipos de dato.

Para empezar comentar que en la instruccion `SET` al menos nosotros recibimos un string ponele "1" y lo casteamos a int usando la funcion `atoi`, luego lo guardamos en el registro correspondiente.

Pero ahora lo interesante es que cuando queremos guardar en memoria un registro por ejemplo: si hago:
```
RESIZE 20
SET AX 0
SET EBX 2864434397
MOV_OUT AX EBX
EXIT
```
(paginas de 4 bytes)

donde 2864434397 representa en hexa el nro AABBCCDD

se nos esta guardando en memoria en little endian, de la siguiente forma: 

| Pagina    | Valor |
| --- | --- |
| 0  | DDCCBBAA  |

Al menos probando recuperar por ejemplo un byte de la DL=0 nos devuelve DD, la DL=1 nos devuelve CC y asi.

Cabe recalcar que tanto en la instruccion SET como en la lectura escritura de memoria usamos `memcpy()` 

Lo mismo por ejemplo si busco la traduccion a decimal de **'hola'** le hago un set a un registro con ese decimal y luego lo quiero imprimir con la interfaz stdout se me imprime **'aloh'**

Lo que nos confunde es si este comportamiento es el esperado o si estamos haciendo algún desastre, y no terminamos de comprender si se debe a que los registros son de tipo numerico o si hay algun error en la implementacion de nuestro tp 

Entiendo que es correcto a nivel arquitectura que los numericos se guarden en little endian y los strings en big endian, y ademas recuerdo en otra ocasion, que nos mencionaron que en la "memoria de mentira" del tp no se distinguen los tipos de datos, con lo cual no se si seria correcto, por ejemplo, que si sé que voy a leer un entero leerlo de atras para adelante. 
En nuestra implementacion la lectura siempre se realiza en una especie de big endian, arrancando por la primer pagina y terminando por la ultima.

Desde ya muchas gracias

**Comment by LeandroCarbajales** [comment]
Buenas!
Lo importante es que si hacés MOV_OUT de un número, y luego hacés MOV_IN, obtengas ese mismo número.
Efectivamente, la memoria es un void*, son bytes, el tipo de dato se lo das vos cuando los interpretas :)

**Comment by GonTurri** [comment]
Eso significa que me puedo quedar tranquilo ? Jajaj. me serviría si me podes dar un ejemplo de cómo guardar un string usando números o algo así para entender mejor.
Además siguiendo con el ejemplo de arriba si yo quiero leer de a un byte con los registros AX BX CX y DX
Y les asigno las dl 0;1;2 y 3
Voy a obtener:
AX = DD
BX = CC
CX = BB
DX = AA

Cómo que te reconstruye el número pero me se me hace que tendrían que estar al reves los valores de esos registros. Si le pongo mov_in con un registro de los extendidos ahi si se guarda exactamente lo mismo

**Comment by iago64** [comment]
Buenas! Cómo va?

Lo lindo de sistemas es que no tenes que creerle a nadie a ciegas, siempre lo podés probar, por eso que te recomiendo que hagas la prueba de guardar el dato y recuperarlo, si guardas el número 47 y recuperas el número 47 está bien, si recuperas otra cosa, está mal.

Saludos.-

**Comment by GonTurri** [comment]
Entiendo, pero eso estoy diciendo. Yo le quiero guardar el equivalente en decimal para "hola" y estoy recuperando "aloh" para recuperar "hola" tengo que ponerle un decimal pensando en que los dígitos hexa van a estar en little endian. Y además en el caso que guardo un número decimal multybyte con un registro extendido, y luego quiero recuperar de a bytes con los registros no extendidos, se me  recupera en orden inverso. Espero se me esté entendiendo y gracias por el seguimiento.

**Comment by iago64** [comment]
Buenas!

El problema es que estas queriendo guardar el decimal de un texto y para texto tenemos registros especiales y 2 interfaces (STDIN y STDOUT) para probarlo, eventualmente si quisiéramos hacer una prueba de alterar algún texto en memoria, usaríamos los registros AX, BX, CX y DX que son de 1 byte y pisan un solo caracter.

Saludos.-

**Comment by GonTurri** [comment]
Perfecto, cuando ingreso un string por teclado y lo recupero por monitor se me imprime lo mismo así que supongo vamos bien. Voy a probar esos casos de cambiar de a un carácter a ver qué onda. Muchas gracias !!
