### ISSUE TITLE
Sincronización de interrupciones por WAIT y QUANTUM en RR

### ISSUE THREAD

**Issue by Jzorreguieta** [sisoputnfrba/foro#3827]
Buenas! Estamos teniendo un inconveniente con el RR (Round Robin). Decidimos, para asegurarnos de que no hayan problemas, que el Kernel no cuente el quantum desde que recibe una solicitud por parte del CPU para tratar alguna instrucción (IO, WAIT, SIGNAL, EXIT) hasta que termine de tratarla (haga o no un pedido de desalojo), y cuando el CPU está tratando con una interrupción (que en tal caso, si por ejemplo el CPU está tratando con una interrupción por QUANTUM, el Kernel no cuente el quantum hasta que el CPU termine con la interrupción e inicie a ejecutar instrucciones). 
Al parecer al ejecutar un proceso, se nos da esta situación:
- Ingresa el proceso a EXEC.
- Se envía el proceso a CPU.
- El CPU comienza a ejecutar las instrucciones hasta que termine el quantum en Kernel.
- Justo antes de que termine el quantum, se comienza a ejecutar la instrucción WAIT.
- Se genera una interrupción por QUANTUM, pero el CPU todavía no terminó de ejecutar el WAIT, por lo que tiene que esperar.
- El CPU le envía un paquete a Kernel con Contexto de Ejecución, motivo y recurso.
- El Kernel lo recibe y deja de contar el quantum.
- El Kernel hace un pedido de desalojo al CPU (llega como interrupción para que se vacie el pcb que se estaba ejecutando en CPU).

El inconveniente es que la interrupción por QUANTUM podrá ser tratada una vez se haya terminado de ejecutar el WAIT, pero acá están habiendo 2 interrupciones a tratar: por QUANTUM y por WAIT.  Cuando ejecutamos nuestro código trata la interrupción por QUANTUM, se termina de ejecutar la primera instrucción del siguiente proceso, y trata la interrupción por WAIT.

Por lo que querríamos saber qué podríamos hacer en este tipo de casos. 

### 📔 Citas del enunciado/videos

"Check Interrupt
En este momento, se deberá chequear si el Kernel nos envió una interrupción al PID que se está ejecutando, en caso afirmativo, se devuelve el Contexto de Ejecución actualizado al Kernel con motivo de la interrupción. Caso contrario, se descarta la interrupción."

### 💭 Soluciones posibles

Que se trate una sola interrupción, o que se pueda sincronizar todo para que, en este caso específico, CAPAZ salga todo bien (pero esto no significa que no vaya a traer más problemas a futuro).

**Comment by LeandroCarbajales** [comment]
Buenas!
Me hacen ruido un par de cosas para tener en clara la situación.

Con respecto al orden de eventos:

> Se genera una interrupción por QUANTUM, pero el CPU todavía no terminó de ejecutar el WAIT, por lo que tiene que esperar.
El CPU le envía un paquete a Kernel con Contexto de Ejecución, motivo y recurso.
    **El Kernel lo recibe y deja de contar el quantum.**
    **El Kernel hace un pedido de desalojo al CPU (llega como interrupción para que se vacie el pcb que se estaba ejecutando en CPU).**

Si ya se envió la interrupción por fin de quantum (y de hecho le llegó a CPU) no entiendo exactamente a qué se refiere con "deja de contar el quantum".
Con respecto al último ítem, si la CPU ya devolvió el contexto de ejecución por llamar a WAIT, no entiendo a qué se refiere con enviar una "interrupción por wait".
 - Si el WAIT debiera bloquear al proceso, el módulo Kernel puede hacerlo inmediatamente y enviarle otro contexto de ejecución a CPU, ante este evento el mismo puede descartar el fin de Q recibido dado que ya cambió de proceso.
 - Si el WAIT no bloquea al proceso, se devuelve el contexto de ejecución del mismo proceso y el mismo tendrá un fin de Q al finalizar la instrucción.

**Comment by Jzorreguieta** [comment]
Buenas!! Ya me respondió con lo último que dijo pero le aclaro. En cuanto al primero, me equivoqué yo al escribir que deja de contar el quantum porque, como bien dijiste, ya había terminado. En cuanto a lo segundo, me faltó explicarme. 
Nosotros hicimos que cuando el CPU ejecute la instrucción WAIT, este le envíe el paquete con pcb, motivo y recurso. Cuando el Kernel lo recibe, este actualiza el pcb del proceso en EXEC (ambos de mismo PID) y hace la asignación del recurso. Mientras tanto, el CPU queda a la espera de un mensaje de parte del Kernel que le diga si continua ejecutando las demás instrucciones del proceso en CPU o si tiene que borrar el que está ejecutando. En el segundo caso, el Kernel generaría una interrupción, que luego en CPU se chequea que tenga el mismo PID que el proceso en ejecución y borra dicho proceso, quedando a la espera de uno nuevo.

**Comment by LeandroCarbajales** [comment]
Ok, ahora entiendo su implementación :)
En mi opinión lo de enviar una interrupción extra (asumo por el puerto interrupt) tranquilamente puede funcionar pero veo que genera más ruido en la comunicación. Si en definitiva la CPU va a esperar que le envíe un nuevo contexto de ejecución (por el puerto dispatch) tenés los mismos 2 casos: si vuelve el mismo PID sigue de donde estaba, si es otro arranca con el nuevo.
