### ISSUE TITLE
Duda con Planificador de corto plazo e hilos.

### ISSUE THREAD

**Issue by Lopez-AN** [sisoputnfrba/foro#3828]
Buenos días que tal 

Con mi grupo tenemos la duda de implementación la cual consiste en si se puede usar DOS hilos para manejar el planificador de corto plazo, o solo se permite un hilo para manejar las colas listo > ejecución > bloqueado.

La dificultad que encontramos en un solo hilo es que, si un proceso vuelve de IO mientras el hilo del planificador corto plazo está esperando que CPU termine el dispatch, el proceso que volvió de IO sigue en la cola de bloqueado hasta el planificador se desocupe y lo atienda.

Se nos ocurrió dos soluciones 

**1.**  (la que implementamos):  que el planificador de corto plazo use dos hilos, uno para atender la cola de listos y otra que maneja las colas de bloqueados.

**2.** Que el envió a dispatch no sea bloqueante y en todo caso al volver el proceso luego de ejecutar o ser interrumpido avise mediante semáforo al hilo del planificador corto plazo para que lo atienda.

**En resumen la duda es si la solución de dos hilos la considera valida**

desde ya gracias.

**Comment by LeandroCarbajales** [comment]
Buenas!
Pueden crear todos los hilos que crean necesarios.

Saludos!
     Lean

**Comment by Lopez-AN** [comment]
gracias!
