### ISSUE TITLE
logs de resize

### ISSUE THREAD

**Issue by fmigliavacca** [sisoputnfrba/foro#3829]
Hola buenas! tengo una consulta medio pava, cuando hago este log 
![image](https://github.com/sisoputnfrba/foro/assets/163766676/64a7c945-4cdd-429c-950d-4202c2e0d045)
en tamaño actual y tamaño a ampliar debo poner el numero de frames o los bytes? Y en tamaño a ampliar es el tamaño nuevo? O la diferencia entre el tamaño nuevo y el tamaño viejo?

**Comment by f-and** [comment]
Buenas! En ambos vas a tener que poner el número de bytes, y si, vas a tener que calcular la diferencia entre el tamaño viejo y el nuevo para indicar cuanto se reduce o amplía el tamaño del proceso.

**Comment by LeandroCarbajales** [comment]
Buenas! @fmigliavacca 
Quedó resuelta la duda? Se puede cerrar el issue?

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, ante cualquier consulta pueden abrir uno nuevo referenciando éste. Saludos
