### ISSUE TITLE
MANEJO de HILOS y SOCKETS

### ISSUE THREAD

**Issue by FelipeRuizDiaz** [sisoputnfrba/foro#3831]
Holaaa, buen dia! Como va? 

Estoy teniendo una duda teórica sobre el manejo de hilos y sockets. 

Estuve leyendo el issue https://github.com/sisoputnfrba/foro/issues/3661 respondido por @iago64 ,  y se genera la pregunta: "En que momento estarías teniendo 2 hilos tratando de acceder al mismo socket?", y mi duda aparece ante esta situación:

A cada petición de la io por parte de la CPU la gestionamos con hilos a través del KERNEL; y cada hilo (gracias a las validaciones) conoce el socket  de la interfaz que se está pidiendo. A la hora de validar si la interfaz se encuentra conectada, lo que hicimos fue hacer como un "mini-handshake" utilizando el socket, que por ejemplo envía un bool y espera que se le responda para continuar.

¿Que pasaría si mas de un hilo quiere hacer este pequeño handshake a la vez? 
Si 2 hilos están esperando ese mensaje con un recv, cuando la io me envíe la respuesta, ¿Cómo me aseguro de que lo está recibiendo el hilo correcto? 
¿Es posible que estos dos recv actúen de forma simultánea sin generar inconsistencias a la hora de recibir estos mensajes? ¿Que pasa si un recv me agarra el mensaje que era para el otro recv? (Quizas esta última pregunta este mal planteada ya desde la teoría).

### 📝 Código relevante
```

bool esta_conectada_la_interfaz(t_interfaz* interfaz, t_pcb* pcb){
    t_paquete* paquete = crear_paquete(ESTOY_CONECTADO);  //code op
    agregar_algo_a_paquete(paquete, true);
    int bytes = sizeof(uint32_t) * 2 + sizeof(bool);
	void* a_enviar = serializar_paquete(paquete, bytes);
	int err = send(fd_entradasalida, a_enviar, bytes, MSG_NOSIGNAL);  //manejo de desconexiones
 
    if(err == -1){
        log_error(kernel_logger,"La interfaz %s no se encuentra conectada.", interfaz->nombre);
        //enviar_proceso_a_exit(pcb);
        return false;
    }else{
        bool respuesta = recibir_mensaje(fd_entradasalida); // es solo un recv
        return respuesta;
    }
}
```

Para solucionar esto me hice mucho la cabeza e hice que todos estos mensajes no se puedan hacer tan facil como un send y recv en medio de la validación; sino que si o si, estos mensajes se hacen a través de paquetes con su respectivo code_op.

Estoy teniendo el mismo inconveniente para el fin de estas peticiones de io, ya que para gestionar los mensajes de las io hacia el kernel, pienso que es necesario que lo hagan con paquetes con su code_op. (Tengo dudas con esto ya que no me parece correcto tener que enviarle el pcb al io para que despues me lo devuelva y poder seguir trabajando con él).

### 📝 Código relevante
```

void atender_kernel_entradaSalida(){
    bool control_key = 1;
    while (control_key) {
        int cod_op = recibir_operacion(fd_entradasalida);
        t_paquete* paquete = recibir_paquete(fd_entradasalida);
        void* buffer = paquete->buffer;
        switch (cod_op)
        {
        case ESTOY_CONECTADO:
                char* instruccion = malloc(sizeof(char));
                t_list* instrucciones_posibles;
                instrucciones_posibles = list_create();

                t_pcb* pcb = recibir_pcb(paquete);
                leer_algo_del_stream(buffer, instrucciones_posibles, sizeof(t_list));
                instruccion = leer_string_del_stream(buffer);

                validar_interfaz_admite_instruccion(pcb, instrucciones_posibles, instruccion); 
            break;
        case FIN_PETICION: 
                t_pcb* un_pcb = recibir_pcb(paquete);
                desbloquear_proceso(un_pcb);       
            break;
        }
    eliminar_paquete(paquete);    
    }
} `
```

Estoy seguro que es un error teórico mío, pero quiero saber si está bien usar esos recv sin tener inconsistencias y que no pase nada, o si es estrictamente necesario manejar todos los envios de mensajes entre módulos con paquetes y códigos de operación.

Desde ya, muchas gracias.

**Comment by f-and** [comment]
Buenas Felipe! Creo que estas cayendo en el mismo problema que menciona Dami con esa pregunta,  ¿por qué habría dos hilos validando la existencia de una interfaz?
Considerando que dos procesos quieran acceder a una misma interfaz a la vez, el primero que llegue sera el que trabe a esa interfaz por lo que ningún otro proceso debería poder mandarle mensajes y esto ocurriría antes de cualquier validación, por lo que nunca deberías tener más de un recv para cada interfaz.

**Comment by FelipeRuizDiaz** [comment]
Hola @f-and !! 
Entonces un solo hilo me va a manejar todos los procesos que quieran utilizar a esa interfaz. 

Por lo que tenía entendido, me pueden llegar muchos pedidos de io, y para gestionar eso, primero tenía que hacer las validaciones para después agregarlo a la cola de procesos bloqueados. Cuando la interfaz se liberaba, tomaba a cada uno de ellos y lo mandaba a ejecutar nada más. Esto me hizo poner en duda lo de los recv.

Pero ahora lo que entendí fue que apenas me llegue un proceso para ejecutar io, lo mando a la cola de procesos blocked de esa io, y le mando un signal a la interfaz que maneja el kernel de que le agregué algo. La interfaz hace wait, hace pop y recién ahí se pone a validar las cosas y hace mas o menos lo que hizo @RaniAgus en el issue https://github.com/sisoputnfrba/foro/issues/3721

De esta manera, como dijiste vos, el proceso que tome la interfaz de la cola con el "pop", va a ser el que trabe a esa interfaz.

Con esto, me surgió otra duda de si conviene mantener una cola de procesos bloqueados para cada io, y tambien a la vez la lista de bloqueados para cada proceso; o unificar eso y que si el proceso se encuentra en la cola de io, es porque efectivamente está bloqueado. De esta manera no tendría que tener dos listas de blocked en simultaneo, lo que sería un poco mas dificil de mantener. (Esto tambien se habla en el mismo issue de arriba).
Ahora bien, no se si conviene NO tener la lista de procesos bloqueados, por si mas adelante en el manejo de recursos se utiliza alli.

**Comment by f-and** [comment]
Tengo que hacer la aclaración importante que si, al menos la validación de si existe y esta conectada la interfaz y la validación de si admite la instrucción se deberían hacer previo a pasar el proceso a BLOCKED, pero para el caso que planteas (un proceso ya esta bloqueando la interfaz), con comprobar que hay un proceso tomando la interfaz se valida que ya esta conectada.
De ahí la otra duda: Para los procesos bloqueados van a tener una cola por cada interfaz y por cada recurso manejado por el Kernel, no creo que necesiten una lista global de procesos bloqueados.

**Comment by FelipeRuizDiaz** [comment]
Lo de la lista global de procesos bloqueados lo entendí perfecto. 

Okey, entonces si la validación se hace antes, me quedaría asi:

. un proceso quiere utilizar la io (mensaje de cpu al kernel)
. valido si existe **(obtengo la interfaz)**   //valido una petición a la vez
. valido si admite la instruccion    
. valido si esta conectada (necesito hacer el **mini-handshake**)
. lo mando al hilo que lo gestiona a los procesos validados
. agrego el proceso a la cola de blocked
. aviso que agregue el proceso
. la io del kernel hace el wait y pop, y ejecuta ese proceso
. me quedo esperando a la finalizacion del mismo (**fin de peticion**)
. desbloqueo el proceso
. cuando termina, vuelvo a esperar el wait

Desde que **obtengo la interfaz**, hasta que se recibe el **mini-handshake**, el control total que tiene la io-kernel está centrado sobre este proceso en particular, osea que los únicos mensajes que se van a enviar los puede recibir solo él y no otro proceso; y si otro proceso me pide hacer io, va a tener que esperar a que termine esta sección (porque no es un hilo).

Pero a la vez, en el **fin de peticion** también tengo que esperar a que la interfaz me envie un mensaje, por lo que puedo estar esperando un mensaje del mini-handshake en un proceso, y a la vez en otro hilo estar esperando a que finalice la petición.

`"En que momento estarías teniendo 2 hilos tratando de acceder al mismo socket?"`
En mi cabeza esta situación ocurre acá cuando tenes que validar la petición y a la vez esperas a que finalice. Tengo 2 hilos que esperan algo de la io en el mismo momento. Quizas tengo que gestionar todo de otra manera para que esto no suceda; pero si desde validar hasta la finalización solo tiene el control un proceso, no me sirve de nada la lista de bloqueados de la io. 

Perdón por ser tan insistente con la pregunta, pero me siguen quedando dudas con el tema de en que momento se hacen las validaciones y cuando se ejecuta realmente ese proceso.

**Comment by FelipeRuizDiaz** [comment]
Creo que mi duda teórica principal está en esta situación:

Si yo envío a la interfaz un sleep de 4 horas, debo esperar con un recv a que la interfaz me avise que terminó esa petición.

Y si ahora quero hacer un mini-handshake entre kernel-io, tengo entendido que el send lo va a poder hacer bien, pero a la hora de querer hacer el recv, este "canal/medio de comunicación" va a estar ocupado. La verdad no se si tira error o si espera esas 4 horas para recién poder hacer este segundo recv.

Leí el issue #3798 y entendí eso.

**Comment by iago64** [comment]
Buenas!

Podes tener 2 hilos accediendo al mismo socket, pero eso no quita que no te estes comprando un lindo quilombo de sincro.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Me sumo para agregar que si la interfaz se desconecta tanto `send()` como `recv()` fallan, por lo que contando con esta info podrías incluir una lógica de manejo de desconexiones sin necesidad de un "mini-handshake" previo que involucre un ida y vuelta (con el problema de sincro que eso conlleva). Saludos

**Comment by FelipeRuizDiaz** [comment]
Entiendo que si tengo dos hilos queriendo enviar mensajes utilizando el mismo socket me traería problemas de condicion de carrera y eso lo debería tratar con sincro.

Para solucionar el manejo de desconexiones, lo que hice fue agregarle un bool a la estructura de la io de si esta conectada o no, y esta es cambiada unicamente cuando se envía la petición a ejecutar. Por lo cual, si la io se desconectó manejo los erroes desde ahi, y así me ahorro el problema de hacer ese mini-handshake. 

Me di cuenta que también tenía un concepto errado del diagrama de 5 estados, ya que pensaba que varios procesos me iban a estar validando a la vez (en execute), cuando en realidad solo un proceso puede estar en execute. Entonces esta validación la hacen uno a la vez, y recién ahi se pasa a blocked. Después de eso manejo las periciones con la cola de blocked y así ya no tengo esa "simultaneidad de recv" que plantee antes erroneamente.

Muchas gracias por las respuestas!! Saludos.

**Comment by iago64** [comment]
Excelente! Si la duda esta resuelta no olviden cerrar el issue :)
