### ISSUE TITLE
Proteccion de area de instrucciones de procesos

### ISSUE THREAD

**Issue by Lopez-AN** [sisoputnfrba/foro#3832]
Buenas que tal, tenemos una consulta referente a instrucciones que escriben en una direccion fisica de la memoria como por ejemplo MOV_OUT

Los procesos al crearse en memoria graban sus instrucciones al comienzo de su espacio de memoria, deberiamos proteger este espacio de una escritura por parte de instrucciones como mov_out para evitar la corrupcion de esas instrucciones? Por ejemplo devolviendo un error de violacion de acceso?

Ejemplo:

![image](https://github.com/sisoputnfrba/foro/assets/15198397/1488cbcb-9e29-4c84-a583-031d5a1af211)

**Comment by RaniAgus** [comment]
¡Buenas! A modo de simplificación, en este TP el área de instrucciones está **por fuera** del área de espacio de usuario. Esto lo pueden notar ya que en la página 22 aparecen ambos apartados en dos títulos diferentes: "Memoria de Instrucciones" y "Esquema de memoria y Estructuras".

Es decir que una escritura sobre la dirección lógica 28 dentro de un proceso de tamaño 250 bytes es un caso perfectamente válido y no debería corromper ninguna instrucción.

Saludos

**Comment by Lopez-AN** [comment]
Hola! gracias por responder, te consulto una cosita mas para estar seguros antes de refactorear....

el espacio de instrucciones de cada proceso va POR FUERA de ese bloque contiguo void* que se divide en marcos?
o sea en los marcos contenidos en ese bloque void* NO guardamos instrucciones?

Saludos!

**Comment by RaniAgus** [comment]
Así es. Repito, esto es solo una simplificación que hacemos al TP ya que queremos que puedan resolverlo de manera iterativa incremental, pero para las pruebas vamos a asumir que va a estar implementado de esta forma.

Saludos

**Comment by Lopez-AN** [comment]
quedo clarisimo gracias!
