### ISSUE TITLE
Sobre el funcionamiento de COPY_STRING

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3833]
Buenas! La pregunta es referida a cómo sería el flujo de la instrucción pues se podría pensar como:
1) le mando todo a memoria de un saque, y hace todo en memoria la lectura y escritura
2) hago como una especie de mov_in seguido de mov_out pero acá no tendría ningún registro para guardarme el valor del string como tal. Podemos usar un buffer y para el tp andaría 10 puntos pero no sé si teóricamente eso sería correcto .
Desde ya muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

Pueden implementarlo de ambas maneras, siempre y cuando respeten que si tienen que acceder a mas de una página, tengan los diferentes accesos tanto para las traducciones como para los accesos a las páginas.

Saludos.-
