### ISSUE TITLE
Duda Copy_String y Log Obtener Marco

### ISSUE THREAD

**Issue by ManuRodri01** [sisoputnfrba/foro#3834]
Buenas tengo una duda con una parte de esta instrucción. El enunciado dice 

> Toma del string apuntado por el registro SI y copia la cantidad de bytes indicadas en el parámetro tamaño a la posición de memoria apuntada por el registro DI. 

La duda es con el registro SI. Este registro tiene la dirección lógica donde esta el string o tiene el string guardado?

La otra duda es, el log "Obtener Marco", se pone también cuando el marco se obtiene de la tlb o solo al pedirlo en memoria?

Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

1: Cito al enunciado:

> SI | 4 bytes | uint32_t | Contiene la dirección lógica de memoria de origen desde donde se va a copiar un string.
DI | 4 bytes | uint32_t | Contiene la dirección lógica de memoria de destino a donde se va a copiar un string.

2.- Pueden ponerlo en ambos casos y no hay problema, total para saber si es de la TLB ya vamos a tener justo antes el TLB Hit.

Saludos.-

**Comment by ManuRodri01** [comment]
Muchas gracias
