### ISSUE TITLE
Duda sobre el filesystem

### ISSUE THREAD

**Issue by ElielBejar** [sisoputnfrba/foro#3835]
Hola buenas! Tengo una duda sobre el filesystem y el dialfs. Quería saber si el filesystem  se tiene que quedar guardado(osea sus archivos guardados y su archivo bitmap guardado) en caso de que se desconecte la interfaz dialfs correspondiente y que si se vuelve a conectar ese mismo dialfs se recuperen todos los datos por medio de esos archivos(bitmap.dat, bloques.dat y los archivos creados por las instrucciones io_fs_create).

Desde ya gracias y saludos!

**Comment by iago64** [comment]
Buenas!

Si, es la idea de un FS, que tenga persistencia y que puedas apagar o en este caso desconectar y volver a prender / conectar y los archivos sigan ahi.

Saludos.

**Comment by ElielBejar** [comment]
Dale perfecto gracias!
