### ISSUE TITLE
Dudas en Memoria

### ISSUE THREAD

**Issue by OreNoe** [sisoputnfrba/foro#3836]
Buenas! Estamos con una duda en mi grupo. A la hora de recibir una direccion fisica en la memoria, se recibe un numero decimal? O se recibe marco y offset por separado. 
Si es que lo recibimos como un numero decimal, como deberiamos hacer para obtener el marco y el offset?

Asi?
```
nro_marco = floor(dir_fisica/tam_pagina)
offset = dir_fisica - nro_marco*tam_pagina
```

Tambien estamos con una duda sobre como es que la MMU obtiene el tamaño de las paginas. Deberia mandarselo la memoria? o por parametro de configuracion? 
Saludos!

**Comment by LeandroCarbajales** [comment]
Buenas!
Para qué querrías tener la dirección física separada en [marco, offset] en la memoria? La dirección física ya representa la posición (byte) de la memoria desde donde leer/escribir.
El tamaño de página puede pasárselo la Memoria a la CPU en el momento del handshake.
