### ISSUE TITLE
Duda MOV_IN y MOV_OUT

### ISSUE THREAD

**Issue by tomipodo** [sisoputnfrba/foro#3837]
Buenas! Cómo les va?
Nos surgió una duda probando el MOV_IN y el MOV_OUT.
Probamos el siguiente pseudocódigo:
```
RESIZE 100
SET EAX 34
SET EBX 48
MOV_OUT EAX EBX
MOV_IN ECX EAX
SET EBX 104
MOV_OUT ECX EBX
MOV_IN DX ECX
EXIT
```

En este caso, en la dirección 34 se guarda el 48. Y luego en la dirección 48 se guarda el 104. Nuestro problema surge cuando intentamos hacer MOV_IN DX ECX. Ya que el DX ocupa 1 byte y el 104 se guardo en memoria como 4 bytes, algo así:

| Dirección | Valor|
| ------------- | ------------- |
| 48| 0  |
| 49| 0 |
| 50| 0 |
| 51| 104|

Se guarda así porque nosotros pensamos en escribir los datos de a 1 byte y en big endian, tomando primero los 3 bytes de cero y último el 104 (en este caso). Nos pareció lo más fácil para no hacernos lío con los tipos de datos, no sabemos si es correcta esta implementación. 
En resumen, en el DX se guarda un 0. Queremos saber si esto es un problema de nuestra implementación, o si tiene sentido con este pseudocódigo que pase esto.

**Comment by iago64** [comment]
Buenas! Cómo va?

Eso no va a ser un problema, las pruebas las estamos escribiendo teniendo en consideración los diferentes largos de los tipos de dato.

Saludos.-

**Comment by tomipodo** [comment]
Buenísimo, nos quedamos tranquilo. Gracias!
