### ISSUE TITLE
Duda sobre aclaracion memoria

### ISSUE THREAD

**Issue by Lisandrogq** [sisoputnfrba/foro#3838]
Buenas, traigo una pequeña duda respecto a la siguiente aclarcion en el modulo memoría:
> Es importante aclarar que **cualquier implementación que no tenga todo el espacio de memoria dedicado a representar el espacio de usuario de manera contigua será motivo de desaprobación directa,** para esto se puede llegar a controlar la implementación a la hora de iniciar la evaluación.

No termino de entender de que forma no se tendría todo el espacio de usuario de manera contigua, es decir, utilizando bitarray de las commons no tengo forma de decidir si se almacena de forma contigua o no(creo que se hace de forma continua por ser un array).
Por esto pregunto ¿Esta aclaracion es para que utilicemos bitarray para representar la memoria de usuario?

**Comment by LeandroCarbajales** [comment]
Buenas! Está aclarado justo encima de ese párrafo, cito:

> Un espacio contiguo de memoria (representado por un void*). Este representará el espacio de usuario de la misma, donde los procesos podrán leer y/o escribir.

La memoria no es más que un vector de bytes, un void* es lo más cercano a ese concepto.
No tenerlo todo contiguo sería por ejemplo tener varios void* es una estructura tipo [nro_frame: int, datos: void*]

**Comment by Lisandrogq** [comment]
Genial
