### ISSUE TITLE
La STDIN recibe muchas direcciones físicas?

### ISSUE THREAD

**Issue by tomipodo** [sisoputnfrba/foro#3840]
Buenas! Como va? 
Teníamos una duda a la hora de realizar IO_STDIN_READ.
Entendemos que va a llegar una dirección lógica y un tamaño. Cuando la CPU calcula la dirección física correspondiente a la DL, puede ocurrir que haya más de una dirección física, no es así? Ya que si DL + Registro_tamanio > tamaño de la página, el valor a leer del teclado, ocupará más de una página.
Entonces la duda que nos surgió es si la CPU debe mandarle todas las direcciones físicas al kernel o como se manejaría esta situación? 
Gracias, saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

Si, si se pasa de 1 página, la CPU tiene que mandarle todas las direcciones físicas al Kernel para que este se las pueda pasar a la interfaz.

Saludos.-

**Comment by tomipodo** [comment]
Excelente. Y, otra consulta en base a esto. Si el Kernel le manda muchas direcciones físicas con el tamaño de cada una a la IO, sería correcto plantear que la IO le pida a la memoria leer cada dirección por separado, y que después la misma interfaz se encargue de "juntar" lo leído?

**Comment by iago64** [comment]
Buenas! Cómo va?

Si.

Saludos.-

**Comment by tomipodo** [comment]
Bárbaro, muchas gracias por contestar tan rápido.
Saludos!
