### ISSUE TITLE
Duda sobre quien le manda el PID a memoria

### ISSUE THREAD

**Issue by EstebanHurtado0** [sisoputnfrba/foro#3841]
Buenas, teníamos una duda sobre quien le manda el PID a memoria, para que pueda guardar el texto y en que pagina guardar en base a la dirección física que le indica, ya que si el string ocupara mas de una pagina, necesitaría ubicar la primer pagina para guardar a partir de esas las otras paginas de manera contigua, Para acceder a ese numero de pagina memoria necesita el PID, quien se lo pasa?

**Comment by LeandroCarbajales** [comment]
Buenas!
Para cualquier petición de CPU a Memoria, la CPU le puede indicar el PID.
Para cualquier petición de Kernel a Memoria, el Kernel le puede indicar el PID.

Te aclara la duda?
Saludos!
     Lean

**Comment by ArielRotolo** [comment]
Buenas, no sería más práctico que la memoria guarde el pid junto con la cantidad de páginas que tiene asignadas? O también se podría tener un diccionario que use de key el pid del proceso.

**Comment by LeandroCarbajales** [comment]
@ArielRotolo 
Ambas son buenas soluciones para sus estructuras, pero seguramente necesiten enviar el PID en las peticiones igualmente para poder hacer uso de ellas :)
