### ISSUE TITLE
Duda sobre Interfaces STDIN y STDOUT

### ISSUE THREAD

**Issue by lewislee0920** [sisoputnfrba/foro#3842]
![image](https://github.com/sisoputnfrba/foro/assets/62365146/c096c375-bbb5-4877-af8d-c8659a14b88b)
![image](https://github.com/sisoputnfrba/foro/assets/62365146/b2c8b0a3-99e3-4586-ae81-85d0c4046281)

Buenas, tengo una duda sobre este dos interfaces. En STDIN dice que realiza IO_STDIN_READ pero lo que hace es escribir por teclado y alamcenar eso en la memoria mientras que en STDOUT se realiza IO_STDOUT_WRITE pero lo que hace es leer lo que esta en memoria y mostrar por pantalla. No estan cambiados los contextos de estos interfaces?

**Comment by LeandroCarbajales** [comment]
Buenas!
No están cambiados. 
Por un lado estás leyendo de la interfaz STDIN (que implica "leer" del teclado y escribirlo en memoria). Esto es análogo a cualquier variante de las syscalls **read**, **fread**, etc.
Por el otro estás escribiendo en la interfaz STDOUT (que implica leer de memoria y "escribirlo" en pantalla). Esto es análogo a las syscalls **write**, **fwrite**, etc. sobre el archivo stdout

**Comment by lewislee0920** [comment]
Dale entendi ahora, gracias por la ayuda
