### ISSUE TITLE
Tabla de paginas x proceso

### ISSUE THREAD

**Issue by FeliFemenia** [sisoputnfrba/foro#3844]
Buenas. Tengo dos dudas sobre el modulo de memoria. 
1- Tengo entendido que las instrucciones que se encuentran en el archivo de pseudocódigo, que puede leer el modulo de memoria cuando el kernel le pasa el path (en la creación de un nuevo proceso), no necesitan ser almacendas en el espacio de memoria (osea el void*). Estoy entendiendo bien?

2- La lista de paginas (de cada proceso) la puedo guardar como un dato mas en el pcb? o debe estar en memoria? 

### 💭 Soluciones posibles
1- En caso de que haya entendido bien, se me había ocurrido que para almacenar las instrucciones de cada archivo de pseudocódigo, podía hacer una lista de listas, en la que cada nodo de la primer lista sea el PID, y que de ese nodo se desprenda otra lista con las instrucciones y que se pueda acceder con el Program Counter al nodo correspondiente. 

2- En caso de que se pueda guardar en el PCB, se me habia ocurrido que con el numero de pagina que calculamos a partir de la direccion logica, con eso buscar en la lista, que en cada nodo tendria el numero de marco correspondiente a ese numero de pagina. Con esto ya podriamos calcular la direccion fisica. 
En caso de que sea en memoria, hariamos algo parecido pero con una lista de listas, implicando un acceso mas a memoria.

**Comment by RaniAgus** [comment]
¡Buenas!

1. Sí, a modo de simplificación, en este TP la memoria ocupada por las instrucciones se encuentra por afuera del espacio de usuario.

2. No, debe sí o sí estar en memoria. Tengan en cuenta que en la vida real el espacio de almacenamiento de la CPU es muy chico, por lo que no es posible guardar una tabla de páginas completa. Además, justamente la gracia de contar con una caché TLB es agilizar ese proceso de traducción de dirección lógica a física ahorrandose un acceso a memoria. Si vos tuvieras almacenamiento infinito en la CPU y pudieras guardarte todas las tablas de páginas, no necesitarías TLB.

Saludos

**Comment by FeliFemenia** [comment]
Buenisimo. Muchas gracias!!

**Comment by RaniAgus** [comment]
¡Por nada! Recuerden que si la duda ya fue resuelta pueden cerrar el issue 👮🏻‍♂️
