### ISSUE TITLE
Uso correcto de semaforos

### ISSUE THREAD

**Issue by GabrielIacomini** [sisoputnfrba/foro#3845]
Hola buenas!! Estoy teniendo un problema, principalmente a la hora de implementar semaforos en 2 archivos .c distintos. Mi duda va por el lado de si existe la posibilidad de que los valores de los semaforos no cambien. En mi caso, tengo un archivo consolaKernel.c y otro planificacionKernel.c, y un semaforos.c y .h donde los inicializo y los declaro. 

Pero me esta pasando que al hacer un wait en por ejemplo en el archivo planificacionKernel.c, y hacer un post en el archivo consolaKernel.c, no se me "postea" el semaforo.

Quizá haya alguna parte de implementación que me estoy comiendo y es lo que me hace problema. Espero se haya entenido mi duda. Gracias!

**Comment by RaniAgus** [comment]
¡Buenas! No deberían tener problemas por trabajar en dos archivos distintos. Tengo dos preguntas:

1. ¿Los `semaforos.c` y `semaforos.h` tienen inicializadas las variables globales como recomendamos [acá](https://docs.utnso.com.ar/guias/programacion/buenas-practicas#%C2%BFy-las-variables-globales)?

2. ¿Usaron el debugger para corroborar que efectivamente se ejecuta el `sem_post()` y el `sem_wait()` y el código no está entrando por algún otro caso?

Saludos

**Comment by GabrielIacomini** [comment]
Hola Agus, al final estaba declarando mal las variables globales, ahi lo implemente como me mencionaste y anda de diez. Mil gracias por responder rapido. Cierro issue!

**Comment by GabrielIacomini** [comment]
Buenas, recien probando el codigo, estamos teniendo problemas con un semaforo. Lo implementamos segun la guia que me paso Agus, pero el semaforo sigue en 0, cuando en realidad lo estamos inicializando en otro valor

```
#include "semaforo.h"

sem_t siguiente_proceso;
sem_t sem_procesos_en_new;
sem_t sem_grado_multiprogramacion;

void inicializar_sem ()
{
    sem_init(&siguiente_proceso, 0, 0);
    sem_init(&sem_procesos_en_new, 0, 0);
    sem_init(&sem_grado_multiprogramacion, 0, 10);
}
```

```
#ifndef SEMAFORO_H_
#define SEMAFORO_H_

#include "semaphore.h"
#include "pthread.h"

extern sem_t sem_instruccion;
extern sem_t sem_procesos_en_new;
extern sem_t sem_grado_multiprogramacion;

void inicializar_sem ();

#endif /* SEMAFORO_H_ */
```

![image](https://github.com/sisoputnfrba/foro/assets/164112858/a222689c-fde6-4259-805b-b380b09f462d)

La variable valor_multiprog es el valor del semaforo que no nos esta funcionando
`int valor_multiprog = sem_getvalue(&sem_grado_multiprogramacion, &valor_multiprog);`

**Comment by LeandroCarbajales** [comment]
Buenas!
Te recomiendo revisar la definición de [sem_getvalue](https://linux.die.net/man/3/sem_getvalue).

El mismo pone el valor del semáforo en la variable pasada como 2do parámetro:
> Description
> sem_getvalue() places the current value of the semaphore pointed to sem into the integer pointed to by sval. 

Luego retorna 0 si salió todo bien:
> Return Value
> sem_getvalue() returns 0 on success; on error, -1 is returned and errno is set to indicate the error. 

En tu caso estás asignando el valor de retorno (0) a la misma variable que pasas como parámetro.
Normalmente esta función no tiene errores salvo que no inicialicen el semáforo por ejemplo, por lo que no es crítico que chequeen el valor de retorno.

**Comment by GabrielIacomini** [comment]
Ahi corregimos eso, igualmente creemos que el semaforo no se esta iniciando bien, porque deberia bajar una unidad el grado de multiprogramacion, pero se queda bloqueado cuando llega a esa parte del codigo

```
void procesos_a_ready (t_listas* Lista)
{
 
    int grado_de_multiprog = config_kernel->GRADO_MULTIPROGRMACION;

    int valor_multiprog = sem_getvalue(&sem_grado_multiprogramacion, &grado_de_multiprog);

    while (1){
        
        //ESPERO QUE ME HABILITEN DESDE CONSOLA
        sem_wait(&sem_procesos_en_new);
        
        pthread_mutex_lock (&mx_cola_new);
        Lista->cant_procesos_NEW = list_size(Lista->new);
        pthread_mutex_unlock (&mx_cola_new);

        pthread_mutex_lock (&mx_cola_ready);
        Lista->cant_procesos_READY = list_size(Lista->ready);
        pthread_mutex_lock (&mx_cola_ready);
        
        //BAJO EL GRADO DE MULTIPROGRAMACION
        sem_wait(&sem_grado_multiprogramacion); <-- acá

        //SACO DE LA COLA DE NEW
        pthread_mutex_lock(&mx_cola_new);
        t_pcb* proceso_ready = list_remove(Lista->new, 0);
        pthread_mutex_unlock(&mx_cola_new);

        //CAMBIO EL ESTADO DEL PROCESO: NEW -> READY
        proceso_ready->estado = READY;

        //AGREGO A LA COLA DE READY
        pthread_mutex_lock(&mx_cola_ready);
        list_add(Lista->ready, proceso_ready);
        pthread_mutex_unlock(&mx_cola_ready);

        log_info(logger, "Cola Ready :\n"); 
        void* iterator = list_iterator_create(Lista->ready);
        while (list_iterator_has_next(iterator)) {
            t_pcb* proceso_iterar = list_iterator_next(iterator);
            log_info(logger, "PID: %d", proceso_iterar->PID);
        }
        list_iterator_destroy(iterator);

        log_info(logger, "PID: %d - Estado Anterior: %s - Estado Actual: %s\n", proceso_ready->PID, "NEW", "READY");

        Lista->cant_procesos_READY += 1;
        Lista->cant_procesos_NEW -= 1;

        // LE MANDO AL PLANIFICADOR QUE HAY UN PROCESO EN READY
        sem_post(&siguiente_proceso);
    
    }

}   
```

este procesos a ready esta en un hilo, que luego llamamos dentro del algortimo de planificacion

```
void iniciar_plani_largo (t_listas* Listas)
{
    pthread_t plani_largo;
    pthread_create (&plani_largo, NULL, procesos_a_ready, (void*) Listas);
    pthread_detach (plani_largo);
}
```

Espero se haya entendido la duda, si se fue mucho del contexto del issue abro uno nuevo :)
