### ISSUE TITLE
Cantidad de Bytes a escribir

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#3846]
Hola buenas. Tengo una pregunta del módulo memoria, en el caso de MOV_IN y MOV_OUT solo podrían darse casos en los que haya que escribir o leer 4 bytes o 1 byte, es así?
 
Leyendo otros issues me surgió otra duda, leí que hablaban de Big endian o Little endian. Estuve buscando información pero no termino de entender si sería necesario o no para el TP, busqué en la consigna y no encontré una aclaración. Tendríamos que tener en cuenta eso?

**Comment by RaniAgus** [comment]
¡Buenas!

> Tengo una pregunta del módulo memoria, en el caso de MOV_IN y MOV_OUT solo podrían darse casos en los que haya que escribir o leer 4 bytes o 1 byte, es así?

Los registros miden 8 o 32 bits, así que sí.

> Leyendo otros issues me surgió otra duda, leí que hablaban de Big endian o Little endian. Estuve buscando información pero no termino de entender si sería necesario o no para el TP, busqué en la consigna y no encontré una aclaración. Tendríamos que tener en cuenta eso?

No se preocupen, como dijo Dami en https://github.com/sisoputnfrba/foro/issues/3837#issuecomment-2146424628, no es algo que vayamos a evaluar. Yo les recomendaría que dejen que los `uint` se guarden en el orden que más le guste a su arquitectura :)

Saludos
