### ISSUE TITLE
Duda VRR

### ISSUE THREAD

**Issue by AgustinaGuitman** [sisoputnfrba/foro#3847]
Buenas, estamos tratando de hacer el VRR y tenemos dudas. 
Hasta ahora tenemos una función que lo único que hace es pasar al proceso del estado ready al exec. Para el round robin creamos un hilo aparte que usa usleep y cuando se despierta desaloja el proceso. Para el VRR  no queremos usar usleep porque queremos que este atento a si vuelve de cpu. Leyendo el issue #3634  vimos que una buena idea es usar temporal para que cuente cuanto tiempo pasa en cpu . No estamos seguros si nos conviene usar el t_temporal desde la función pasar a running o si es mejor hacer un hilo que controle el quantum y si es que volvió de cpu antes que termine su quantum.

**Comment by RaniAgus** [comment]
¡Buenas!

>  Para el VRR no queremos usar usleep porque queremos que este atento a si vuelve de cpu

Ojo que este caso se puede dar tanto para RR como para VRR: la CPU te puede devolver el PCB antes del fin de quantum con un motivo de desalojo distinto.

> Leyendo el issue 3634 vimos que una buena idea es usar temporal para que cuente cuanto tiempo pasa en cpu

Sí, muy probablemente les sirva ya que funciona como cronómetro. Al detenerlo, podés obtener el tiempo que estuvo en EXEC y actualizar su quantum para enviarlo a Ready+

> No estamos seguros si nos conviene usar el t_temporal desde la función pasar a running o si es mejor hacer un hilo que controle el quantum y si es que volvió de cpu antes que termine su quantum.

Creo que desde la función que pasa a running y hace el `recv()` está bien. O sea, les quedaría algo como:

1. `send()` a la conexión de dispatch
2. Iniciar temporal
3. `recv()` de la conexión de dispatch
4. Detener temporal

También podrían iniciar el temporal antes del `send()`, a fines prácticos es indistinto.

Saludos

**Comment by NazarenoLopez** [comment]
> Ojo que este caso se puede dar tanto para RR como para VRR: la CPU te puede devolver el PCB antes del fin de quantum con un motivo de desalojo distinto.

Buenas! Una consulta, si me llega el contexto de ejecución de CPU mientras está en sleep, y "pierdo" esos micro segundos, pero luego no envío la interrupción porque ya me llegó el contexto, está ok esto?

Gracias

**Comment by AgustinaGuitman** [comment]
Hola, muchas gracias por la respuesta. Respecto a esto: 
> Ojo que este caso se puede dar tanto para RR como para VRR: la CPU te puede devolver el PCB antes del fin de quantum con un motivo de desalojo distinto.

me dejaste pensando y viendo nuestro código no contempla ese caso ya que hacemos `usleep(quantum()*1000); ` y después desalojamos el proceso si es que no volvió de cpu y si es el proceso que esta en ejecución: 
```
 if(regreso_de_cpu == 0 && proceso_en_ejecucion->pid == pcb->pid)
{
		desalojar_proceso(RR);
		log_info(logger,"PID: <%d> - Desalojado por fin de Quantum",pcb->pid);

}

```
Se me ocurre hacer un while que este controlando que el proceso no haya vuelto de cpu pero creo que va a tener mucha espera activa. ¿Tendrás alguna recomendación?

**Comment by AgustinaGuitman** [comment]
Hola, muchas gracias por la respuesta. Lo pudimos solucionar pero ahora tenemos dudas de si es una buena idea poner la estructura t_temporal como parte del pcb ya que por un lado ayudaría a guardar los tiempos consumidos en el VRR pero es inútil para el FIFO y el RR.

**Comment by NazarenoLopez** [comment]
> @NazarenoLopez No, deberías recibir el PCB inmediatamente ya que la diferencia podría no ser de microsegundos. Por ejemplo, si tenés un quantum muy grande (15000ms) y tu proceso ejecuta EXIT antes (en 2000ms) estarías desperdiciando bastante tiempo de CPU, además de no cumplir con el algoritmo RR visto en la teoría.

No entendí a que te referis con recibir el PCB inmediatamente. Podrías explicarme devuelta? 
Porque tiempo de cpu?Gracias

**Comment by RaniAgus** [comment]
¡Buenas @AgustinaGuitman y @NazarenoLopez! 

> Hola, muchas gracias por la respuesta. Lo pudimos solucionar pero ahora tenemos dudas de si es una buena idea poner la estructura t_temporal como parte del pcb ya que por un lado ayudaría a guardar los tiempos consumidos en el VRR pero es inútil para el FIFO y el RR.

Sí, pueden agregarlo, de hecho en el enunciado aparece el quantum entre los campos del PCB:

_- Quantum: Unidad de tiempo utilizada por el algoritmo de planificación VRR._

> No entendí a que te referis con recibir el PCB inmediatamente. Podrías explicarme devuelta?
Porque tiempo de cpu?Gracias

- Tenés configurada planificación RR con quantum de 15000ms
- Iniciás 2 procesos en el t=0
- El primer proceso fue a Exec en el t=0 y ejecutó una ráfaga de 2000ms antes de ser desalojado por EXIT
- El segundo proceso **tiene** que ir a Exec en t=2000ms, no esperar hasta el fin de quantum que sería t=15000ms

O sea, el Kernel debe recibir el PCB inmediatamente al momento en el que fue desalojado (t=2000ms) y no cuando se produzca el fin de quantum (t=15000ms).

Si el proceso esperara a que termine el quantum, habría un total de 13000ms en los cuales el CPU quedaría sin ejecutar nada cuando en realidad hay procesos listos para ejecutar, por eso digo que estás desaprovechando ese tiempo de ejecución en CPU, además de no cumplir con lo que se explica en la parte teórica de la materia.

Saludos

**Comment by RaniAgus** [comment]
Buenas @AgustinaGuitman y @NazarenoLopez, ¿quedaron claras las respuestas? Saludos

**Comment by AgustinaGuitman** [comment]
Buenas, si muchas gracias. @NazarenoLopez si te parece cierro el issue. Saludos

**Comment by LeandroCarbajales** [comment]
Cerramos el issue dado que está resuelta la duda original, cualquier cosa abren uno nuevo :)
