### ISSUE TITLE
Segmentation fault con funcio de commons 

### ISSUE THREAD

**Issue by Elias318** [sisoputnfrba/foro#3848]
Al iniciar los módulos me aparece segmentatio fault con una función de las commons que no usamos en ningún momento. Que hacemos en estos casos ? 
Adjunto foto con el código donde ocurre el problema y arriba se puede ver la ruta.
Muchas Gracias.

### 📝 Código relevante
![image](https://github.com/sisoputnfrba/foro/assets/72205645/03642f5d-0074-4ff3-b287-60c66b14e48e)

**Comment by f-and** [comment]
Buenas, para saber, pudiste correr el código con [valgrind](https://docs.utnso.com.ar/guias/herramientas/valgrind)? Porque la función que pasaste es una función utilizada en varias partes del código de las commons de listas, por lo que puede ser llamado por otras funciones. 
En sí el error puede ser causado por tener una lista que tiene elementos que fueron borrados sin sacarlos de la misma por lo que el `element->next` esta llamando a datos basura.

**Comment by RaniAgus** [comment]
¡Buenas! Me sumo para agregar que también pueden ver el stack trace (o sea, la pila de llamados a funciones) en la sección "Call Stack":

![image](https://github.com/sisoputnfrba/foro/assets/39303639/798dfa78-f8c4-4b5b-abc2-05919149f4af)

Por ejemplo, acá si bien me está fallando la misma línea, se ve bien que estoy llamando a `list_remove()` en la línea 7 de mi archivo `main.c`. Si hago click ahí:

![image](https://github.com/sisoputnfrba/foro/assets/39303639/87c997f2-7bff-490a-97a1-69e7377b8eea)

Me va a llevar a la línea donde está el error: en mi caso estoy intentando quitar un elemento de una lista vacía.

Saludos

**Comment by RaniAgus** [comment]
¡Buenas @Elias318! ¿Te sirvieron las respuestas? Saludos

**Comment by Elias318** [comment]
Hola sisi perdon.Muchas Gracias
