### ISSUE TITLE
ayuda con list_find() de las commons

### ISSUE THREAD

**Issue by KirkSH** [sisoputnfrba/foro#3849]
Hola. Se me dificulta usar varias funciones de listas de la commons, porque las funciones closure reciben 1 parametro, en vez de 2, como yo estaba acostumbrado de algoritmos, jiji.

Viendo las unit-test, veo esto:

```
            it("should find the first value that satisfies a condition") {

                t_person *find_someone_by_name(char *name) {
                    int _is_the_one(t_person *p) {
                        return string_equals_ignore_case(p->name, name);
                    }

                    return list_find(list, (void*) _is_the_one);
                }
```

¿Esto de definir una funcion dentro de otra es legal en C? O capaz estoy entendiendo mal, me pareció que eso hace ese cacho de código.
Pregunto desde el desconocimiento, y porque no se me ocurre una forma de usar list_find() de manera efectiva.

**Comment by f-and** [comment]
Buenas! Te dejo [acá](https://github.com/sisoputnfrba/foro/issues/3727#issuecomment-2120939879) una respuesta de Rani a un  issue similar, pero la corta es:
El compilador que usamos para el TP (gcc), tiene [extensiones](https://gcc.gnu.org/onlinedocs/gcc/C-Extensions.html) integradas que agregan funcionalidades a C, entre las que está justamente la [anidación de funciones](https://gcc.gnu.org/onlinedocs/gcc/Nested-Functions.html). Visual Studio tiende a no querer estas extensiones por lo que te puede marcar un error donde no lo hay, y no evaluamos si el código cumple o no con el formato de C Estándar.
Por lo que, respondiendo a tu ejemplo, podrías implementar algo semejante, una función que tenga anidada la función closure con el parámetro insertado adentro.

**Comment by KirkSH** [comment]
Ok. Entiendo. Muchas gracias.
