### ISSUE TITLE
Manejo del WAIT

### ISSUE THREAD

**Issue by tomassantolaria** [sisoputnfrba/foro#3850]
Buenas, tengo una duda que puede llegar a ser media obvia.
Cuando el Kernel recibe de la CPU el Contexto de Ejecución desalojado por WAIT y el recurso al que se le aplico no se bloquea porque sigue teniendo instancias disponibles, yo debo restarle 1 a la cantidad de instancias y seguido a esto enviarle de vuelta el contexto de ejecución a la CPU?

**Comment by LeandroCarbajales** [comment]
Exacto!

Saludos.

**Comment by tomassantolaria** [comment]
Gracias! Saludoos
