### ISSUE TITLE
Problemas con msync

### ISSUE THREAD

**Issue by GregorioOndjian** [sisoputnfrba/foro#3851]
Buenas, con mi grupo seguimos teniendo problemas con el tema de la sincronizacion: hasta ahora lo que pudimos hacer es crear el bitmap y mapear solo la estructura de 0 y 1 en memoria o por lo menos eso es lo que creemos.
El problema es que, a la hora de crear un nuevo archivo en donde luego de crearlo debemos modificar el bitmap, no logramos sincronizar correctamente el bitmap modificado a memoria.
Es como que luego de modificar el bimap realizamos el msync y no hace ningun cambio en el archivo.

### 📝 Código relevante

```c
void crear_archivo_bitmap(){
    char path[256];
    strcpy(path, "bitmap.dat");
    FILE* archivoBitmap = fopen(path, "wb+");
    if (archivoBitmap == NULL){
        log_error(logger, "Error al abrir/crear el archivo bitmap de bloques.");
        exit(EXIT_FAILURE);
    }

    int tamanioBitmap = config.block_count / 8;
    char data[tamanioBitmap];
    memset(data, 0, tamanioBitmap);  // Inicializa el array a 0
    bitmap = bitarray_create_with_mode(data, sizeof(data), LSB_FIRST);

    // Redimensionar el archivo para mmap
    fflush(archivoBitmap);
    ftruncate(fileno(archivoBitmap), tamanioBitmap);

    // Usar mmap para mapear el archivo a memoria
    archivo_bitmap = mmap(NULL, tamanioBitmap, PROT_READ | PROT_WRITE, MAP_SHARED, fileno(archivoBitmap), 0);
    if (archivo_bitmap == MAP_FAILED) {
        log_error(logger, "Error al mapear el archivo bitmap.");
        fclose(archivoBitmap);
        bitarray_destroy(bitmap);
        exit(EXIT_FAILURE);
    }

    msync(archivo_bitmap, tamanioBitmap, MS_SYNC);

    // Limpiar
    //munmap(archivo_mmap, tamanioBitmap);
    fclose(archivoBitmap);
}

void crearArchivo(char* nombre){
	log_debug(logger, "entre a crearArchivo");
	usleep(config.tiempo_unidad_trabajo_milisegundos);

    /*char path[256];
    strcpy(path, "bitmap.dat");
    FILE* archivoBitmap = fopen(path, "rb+");

    if (archivoBitmap == NULL){
        log_error(logger, "Error al abrir/crear el archivo bitmap de bloques.");
        exit(EXIT_FAILURE);
    }*/
	
    int primerBloqueLibre = obtenerPrimeraPosicionLibre(bitmap);
    log_debug(logger, "Bloque libre %d ", primerBloqueLibre);
    bitarray_set_bit(bitmap, primerBloqueLibre);
    int tamanioBitmap = config.block_count / 8;
    log_debug(logger,"el primer bit es: %d", bitarray_test_bit(bitmap,0));
    if (msync(archivo_bitmap, tamanioBitmap, MS_SYNC) == -1) {
    log_error(logger, "Error al sincronizar el archivo bitmap.");
    }
	//fclose(archivoBitmap);

    t_config* archivo;
    char direccion[256];
    strcpy(direccion, "./fs/");
    strcat(direccion, nombre);
    FILE* archivoNuevo = fopen(direccion, "w");
	char* bloqueInicialEnChar = itoa(primerBloqueLibre);
    archivo = config_create(direccion);

    config_set_value(archivo, "TAMANIO_ARCHIVO", "0");
    config_set_value(archivo, "BLOQUE_INICIAL", bloqueInicialEnChar);
    config_save(archivo);

    config_destroy(archivo);

    fclose(archivoNuevo);
    log_debug(logger, "Crear Archivo: %s ", nombre);
}
```
En el crear archivo bitmap creamos el bitarray y luego lo mappeo a memoria. En el crear archivo, creo el archivo, modifico el bitarray y luego intento hacer el msync.

Un saludo.

**Comment by RaniAgus** [comment]
¡Buenas! Veo un par de cuestiones:

1. Primero, le están pasando al `t_bitarray` un bloque de memoria en el stack, el cual es liberado automáticamente una vez la función retorna:

```c
char data[tamanioBitmap];
bitmap = bitarray_create_with_mode(data, sizeof(data), LSB_FIRST);
```

2. En una variable completamente distinta y desconectada del bitmap, están guardando un puntero a la memoria mapeada:

```c
archivo_bitmap = mmap(NULL, tamanioBitmap, PROT_READ | PROT_WRITE, MAP_SHARED, fileno(archivoBitmap), 0);
```

Dado esto, no existe ninguna chance de que el `msync()` haga algo, ya que cualquier llamado a `bitarray_set_bit()` va a modificar una porción de memoria completamente distinta a la mapeada.

Lo correcto sería simplemente pasarle a `bitarray_create()` el puntero a la memoria mapeada.

Saludos

**Comment by GregorioOndjian** [comment]
Buenass, ahi hice lo que me aconsejaste y funcionó! :) el tema es que nose si lo esta haciendo correctamente, es mas un tema de interpretación de lo que termina poniendo en el archivo.
Ahora lo que hacemos es crear 2 archivos nuevos, lo que esperabamos es que en en archivo quede "1100 0000 0000 ...", pero en lugar de eso queda "0300 0000 0000" esta bien?
![image](https://github.com/sisoputnfrba/foro/assets/82954160/30ed15bd-0d91-4766-a533-e8c6db2d1674)

**Comment by RaniAgus** [comment]
`xxd` te muestra cada byte en **hexadecimal**, por lo que el binario `0000 00011 0000 0000` se puede observar como `0300` en el dump (o sea, ta bien :D).

Por otro lado, se está guardando como `000000011` en lugar de `11000000` porque el bitarray está inicializado como `LSB_FIRST`:

```c
	/**
	 * @brief Define el orden bajo el cual se guardarán los bits a la hora de llenar los bytes.
	 * @note  La mayoría de las implementaciones de bitmap usan LSB_FIRST. Si no estás seguro
	 *        de cuál usar, probablemente quieras usar esta.
	 */
	typedef enum {
		/**
		 *  @brief   Completa los bits en un byte priorizando el bit menos significativo:
		 *  @example 00000001 00000000
		 */
		LSB_FIRST,
		/**
		 *  @brief   Completa los bits en un byte priorizando el bit más significativo:
		 *  @example 10000000 00000000
		 */
		MSB_FIRST
	} bit_numbering_t;
```

Saludos

**Comment by GregorioOndjian** [comment]
Buenisiimoo, muchisimas graciass. Un saludo!
