### ISSUE TITLE
Kernel: manejo recursos, duda issue previo

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3852]
Buenas, me quedo una duda del issue #3818, no me deja reabrirlo, por eso abro uno nuevo. Cuando en la consigna dice:

- - -
A la hora de recibir de la CPU un Contexto de Ejecución desalojado por SIGNAL, el Kernel deberá verificar primero que exista el recurso solicitado, luego sumarle 1 a la cantidad de instancias del mismo. En caso de que corresponda, desbloquea al primer proceso de la cola de bloqueados de ese recurso. Una vez hecho esto, se devuelve la ejecución al proceso que peticiona el SIGNAL.
- - - 

¿El "En caso de que corresponda..." sería cuando la cantidad de instancias es mayor a 0, o cuando hay un elemento en la cola de bloqueados?

**Comment by RaniAgus** [comment]
¡Buenas @rood8592! ¿Te sirvió la respuesta de Fede? Saludos

**Comment by rood8592** [comment]
Si, gracias.

**Comment by rood8592** [comment]
Buenas, reabro el issue porque me surgio una duda con respecto a los recursos. Si yo tengo una instancia de un recurso, un proceso la toma, luego otro la quiere tomar y se bloquea, el primer proceso que la tomó no la libera pero si termina, con lo cual debemos expropiar sus recursos, en ese momento se desploquearía el otro proceso que estaba bloqueado? O este ultimo debe esperar un signal si o si?

**Comment by FredeHG** [comment]
Hola buenas!

Tienen que desbloquear la cantidad de procesos como de instancias de recursos libere el proceso que se termina o hasta que te quedes sin procesos bloqueados, lo que pase primero. Si te quedas sin procesos bloqueados empiezan a subir la cantidad de instancias disponibles

Saludos!

**Comment by rood8592** [comment]
Perfecto, muchas gracias! Cierro el issue!
