### ISSUE TITLE
Responsabilidades CPU-MEMORIA

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3853]
Buenas, 
Tenemos una duda con respecto a las responsabilidades que debería tener cada modulo. Nosotros a memoria, cuando queremos realizar una escritura  de un dato que esta dividido en N partes, le mandamos N solicitudes y cada una contiene el dato ENTERO, dirección fisica, la base y el tamaño. Para que despues memoria haga un memcpy desde (base) y hasta (tamanio) que se le indique, esto estaría bien? ¿O debería mandarle el fragmento del dato y no el dato entero, lo cual eliminaría la necesidad de mandarle la base? Me refiero a que CPU sea la encargada de partir el dato.

**Comment by LeandroCarbajales** [comment]
A efectos de funcionamiento del TP da casi lo mismo.
Si lo estuviera haciendo yo, lo "partiría" en la CPU ya que ya tengo todos los datos que necesito como la base, etc. y así le tengo que mandar menos cosas a Memoria (menos para serializar, etc). Luego la Memoria también tendría una lógica más simple a la hora de manejar ese mensaje (que de por sí ya es un módulo con muchas estructuras).

**Comment by rood8592** [comment]
Ok, gracias. Otra duda, tenemos pensado en el caso de una escritura, conseguir primero todos los marcos (ya sea de la tlb o de la memoria, dependiendo del HIT o MISS) yendo uno por uno. Una vez que tengamos todos los marcos, procedemos a mandar n solicitudes, dependiendo de en cuanto este partido el dato ¿Estaría bien así o se debería por cada marco obtenido ya enviar la solicitud de escritura que le corresponde a dicho marco? 
Por ej, si un dato esta partido en n partes, nuestro orden es:
1- Consulto si la primer pagina está en la tlb o no, si está lo agrego a una lista de marcos, si no está, se lo pido a memoria, espero que me lo devuelva y lo agrego a la lista, así sigo con las paginas que le sigan hasta tener todas.
2- Cuando ya tengo todos los marcos, procedo a mandar cada fragmento a memoria en una solicitud distinta (n marcos implica n solicitudes).

**Comment by LeandroCarbajales** [comment]
Da igual, ambas opciones están bien. Si ya lo tienen implementado de esa manera y les funciona genial :)

**Comment by rood8592** [comment]
Perfecto, gracias @LeandroCarbajales!
