### ISSUE TITLE
Cantidad de recursos

### ISSUE THREAD

**Issue by jotab0** [sisoputnfrba/foro#3855]
Buenas! Tengo una duda con respecto al manejo de los recursos:

La cantidad de recursos que vienen en el archivo config podría variar? Porque dependiendo de si varía o no tengo 2 soluciones, una bastante más compleja que la otra.

Entiendo que en un contexto real sin dudas variaría, pero no sé si está dentro del alcance de este trabajo, por eso me gustaría primero que me respondan como sería para poder continuar. 

Por las dudas aclaro, por más que sea obvio, que no me refiero a la variación en la cantidad de instancias de cada recurso sino a los recursos en sí. Por ejemplo sumar un recurso más que se llame RD.

Saludos!

**Comment by LeandroCarbajales** [comment]
Buenas!
No está dentro del alcance de este trabajo crear más recursos de los que están dados en la config del kernel.

Saludos!
     Lean

**Comment by LeandroCarbajales** [comment]
Buenas @jotab0 !
Quedó resuelta la duda? Se puede cerrar el issue?

**Comment by jotab0** [comment]
Hola @LeandroCarbajales! Si obvio, muchas gracias, buen fin de semana.

**Comment by jotab0** [comment]
Se me sumó una consulta más.

Me parece que voy a armar una lista global con los recursos disponibles donde cada uno es un struct con su nombre y un semáforo propio.

Cada vez que se haga un signal de determinado recurso se va a buscar en la lista ese mismo y se hará sem_post en su semáforo correspondiente. En el caso del wait lo mismo solo que llamando a sem_wait.

Debería agregar un mutex para acceder a la lista? Y si lo agrego, no correría riesgo de que ocurra deadlock? Por ejemplo, si entré a la lista y llamo a sem_wait y se bloquea porque no hay más instancias, en este caso nunca se saldría del mutex.

**Comment by RaniAgus** [comment]
¡Buenas! ¿La lista va a ser modificada durante la ejecución del Kernel? ¿O simplemente los hilos van a acceder a ella para buscar los recursos, o sea, solo van a hacer lecturas (sin agregar o quitar elementos)? Saludos

**Comment by jotab0** [comment]
Hola @RaniAgus !

Los hilos van a hacer únicamente signal (sem_post) y wait (sem_wait) sobre el semáforo propio de cada recurso de la lista, pero la lista en sí una vez que esté armada no se van a quitar ni añadir elementos. 

Yo entiendo que como se va a operar sobre semáforos no debería ser necesario agregar un mutex ya que justamente los semáforos están para sincronizar. Pero igual de alguna manera se están "modificando" los datos de los elementos de la lista (se incrementan o decrementan los semáforos), de acá surgrió mi duda.

**Comment by RaniAgus** [comment]
> Yo entiendo que como se va a operar sobre semáforos no debería ser necesario agregar un mutex ya que justamente los semáforos están para sincronizar. 

Exacto!

> Pero igual de alguna manera se están "modificando" los datos de los elementos de la lista (se incrementan o decrementan los semáforos)

Sí, pero justamente hacer `sem_post()` y `sem_wait()` a un semáforo son operaciones thread-safe. Si no lo fueran, no podrías tener un semáforo como variable global, porque lo estarías modificando al usarlo.

Saludos

**Comment by jotab0** [comment]
Genial @RaniAgus, todo clarísimo.

Si quieren pueden cerrar el issue, buen comienzo de semana.

**Comment by RaniAgus** [comment]
¡Buenísimo! Recuerden que si la duda ya fue resuelta pueden cerrar el issue 👮🏻‍♂️
