### ISSUE TITLE
Parseo de pseudocodigo en Memoria o CPU

### ISSUE THREAD

**Issue by ArielRotolo** [sisoputnfrba/foro#3856]
Buenas tardes, probablemente esto ya se planteo pero no encontré un issue con esta consulta.

La consulta seria quien es el encargado de parsear el pseudocodigo, a lo que me refiero es cuando la memoria lee el pseudocodigo linea por linea y se lo tiene que mandar a la cpu hay 2 opciones. 
1 - Enviar una estructura serializada que la memoria conoce y va llenando con: tipo de instrucción, tipo de registro, variable, recurso, etc, por lo que la memoria haría todo ese trabajo de parseo o "interpretación".
2 - Directamente a la memoria no le interesa y manda la linea entera como un string hasta el \n sin contexto alguno y la cpu es totalmente la encargada de saber que es que. Por supuesto hay que serializar el string para que la cpu sepa el tamaño que recibe.

Desde un punto de vista conceptual parece que lo mas realista seria que la CPU se encargue de separar cada cosa en base a la linea que recibió, pero tranquilamente se podría implementar en la memoria en este caso.

**Comment by LeandroCarbajales** [comment]
Buenas!
Como bien mencionás tranquilamente se podría implementar en la Memoria, a efectos del trabajo no hay ninguna restricción al respecto y queda a criterio del grupo.

Como análisis personal simplemente, creo que tener una estructura compartida entre la Memoria y la CPU es complicarse de más. Si ese trabajo lo hace la CPU sería exactamente el mismo parseo que haría la Memoria pero sin tener la estructura compartida ya que Memoria esa estructura no la usaría para nada más que para enviarla a CPU. Por otro lado, serializar un string es más fácil y menos propenso a errores que serializar esa estructura parseada que contiene distintos tipos de datos según cada instrucción.

Espero les sirva mi análisis.
Saludos!
     Lean

**Comment by ArielRotolo** [comment]
Perfecto, muchas gracias Leandro!
