### ISSUE TITLE
Puede la CPU juntar lo leído del STDOUT_WRITE?

### ISSUE THREAD

**Issue by tomipodo** [sisoputnfrba/foro#3857]
Buenas! Cómo va? 
Tenemos una duda con el IO_STDOUT_WRITE. Cuando nos llega esta instrucción para leer de memoria una cierta cantidad de bytes y mostrarlas por la respectiva interfaz, podemos leer desde la CPU (siempre teniendo en cuenta que pueden ser varias páginas) y enviarle el dato leído al Kernel para que este se lo envíe a l interfaz? O la interfaz es la que debe conectarse con la memoria?

Gracias, saludos!

**Comment by LeandroCarbajales** [comment]
Buenas!
Cito al enunviado:

> Interfaces STDOUT
Las interfaces STDOUT se conectan a memoria para leer el valor que se encuentra en la o las direcciones físicas pedidas y mostrar el resultado por pantalla.

Te aclara la duda?
Saludos!
        Lean
