### ISSUE TITLE
error al clonar de nuevo el repositorio

### ISSUE THREAD

**Issue by nicolasvultaggio** [sisoputnfrba/foro#3858]
Tengo un problema:

a mí me venía pasando que cada tanto abría el respositorio, y cuando ejecutaba cualquier comando de git para ponerme a trabajar:
y me devolvía este tipo de error:

> error: object file .git/objects/15/e14ee0170c47db4c84cbb546c40a6f129b4a40 is empty
fatal: loose object 15e14ee0170c47db4c84cbb546c40a6f129b4a40 (stored in .git/objects/15/e14ee0170c47db4c84cbb546c40a6f129b4a40) is corrupt

entonces yo lo que hacía era borrar la carpeta y volver a clonar el respositorio de nuevo, pero ahora me aparecio lo siguiente:

![image](https://github.com/sisoputnfrba/foro/assets/131707089/94fe0cb0-5252-49f1-84e4-2d0607c7c510)

que significa esto?

**Comment by RaniAgus** [comment]
¡Buenas! Para la próxima, porfa copien y peguen el texto ya que, como contamos en el README del foro, si alguien intenta usar el buscador e ingresa `fatal: unable to get credential storage lock in 1000 ms: File exists` no va a poder encontrar el issue ya que GitHub (aún) no reconoce el texto en imágenes 👮🏻‍♂️ 

Dicho esto, haciendo una búsqueda rápida entiendo que podría ser un problema con lo que usa git para almacenar las credenciales. Mi recomendación es primero probar con esta solución: https://stackoverflow.com/a/37692956

Si no funciona, te diría intentar utilizar SSH para clonar el repo siguiendo la sección [Configurar las credenciales de Git](https://docs.utnso.com.ar/primeros-pasos/tp0#configurar-las-credenciales-de-git) del TP0, la cual redactamos hace poquito. Este método también tiene la ventaja de que las claves nunca expiran, a diferencia de los access tokens.

Saludos
