### ISSUE TITLE
Duda Logs

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#3859]
Hola buenas tengo una pregunta con estos logs, el log de obtener marco se tiene que mostrar cuando busco el marco en memoria solamente? o tambien deberia mostrarlo cuando hago un TLB hit?
![image](https://github.com/sisoputnfrba/foro/assets/112731246/748b9d7e-c30e-461d-90ba-a66acef14bca)

**Comment by LeandroCarbajales** [comment]
Buenas!
Recuerden que pueden buscar en issues cerrados anteriormente. Fue respondido en #3834.

Saludos!
       Lean
