### ISSUE TITLE
Pruebas de memoria

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3860]
Buenas! vengo a pedir si por favor podrían inventar algunas pruebas de memoria. Si bien estamos intentando probar la mayoría de los casos, lo mas probable es que se nos escapen varios

Muchas gracias !

**Comment by iago64** [comment]
Buenas! Cómo va?

Ya vamos a sacar algunas pruebas preliminares de memoria y planificación, seguramente la semana que viene se publiquen.

Saludos.-
