### ISSUE TITLE
Uso de bitarray

### ISSUE THREAD

**Issue by lperezpersico** [sisoputnfrba/foro#3862]
Hola! Estaba intentando implementar la parte de memoria, y vi que recomendaban usar la Bitarray de las commons. Leí este issue #3790 pero igualmente me quedaron dudas sobre la creación del bitarray para saber que marcos están libres. 
Decían que:

>  El primer parámetro que recibe bitarray_create_with_mode() es un puntero a la memoria que se va a usar para el bitmap, por lo que no es correcto pasarle el espacio de usuario ya que, cuando quieran usar bitarray_set_bit() y bitarray_clean_bit(), van a estar modificando el espacio de usuario.
> 
> Lo correcto sería pasarle una porción de memoria distinta que mida cant_marcos/8, ya que ésta les va a servir para determinar si un marco está libre o no usando bitarray_test_bit().

Cuando dice que debo pasarle un puntero a la memoria que voy a usar. Sería un puntero al void* del espacio de usuario? 
Tampoco entiendo por qué deberia hacer la cant_marcos/8

Espero que se hayan entendido las consultas, es que ando medio perdida con este tema. Gracias!

**Comment by f-and** [comment]
Buenas! Para responder:
El bit_array sirve para lo que seria un bitmap de los marcos, osea un array del tamaño de la cantidad de marcos donde cada bit representa un marco y su estado representa si el marco esta libre o no. Por lo que tendrias que crear un void * separado del espacio de usuario para eso, y este va a tener un tamaño de cant_marcos/8 porque considera que el tamaño es en bytes (8bits por byte), y el bit array va a manejarse bit a bit, por lo que por cada byte que tengas, podras considerar el estado de 8 marcos.
Luego este bit_array va a tener que manejarse en paralelo al espacio de usuario para marcar cuales marcos estan disponibles y cuales no.

**Comment by f-and** [comment]
Si, ese es un código valido.

**Comment by lperezpersico** [comment]
muchas gracias!! <3
