### ISSUE TITLE
Chequear Interrupcion

### ISSUE THREAD

**Issue by tomassagrada** [sisoputnfrba/foro#3864]
Buenas, el manejo de interrupciones en el trabajo esta planteado de manera que el CPU ejecuta las instrucciones del proceso, mientras el canal de interrupt esta atento a la llegada de una señal (que seria digamos un send del kernel que no contiene nada especifico) la cual hacer que una cierta flag cambie y que cuando la CPU termine con la instrucción que estaba devuelva el CDE debido al cambio de valor en la flag, el cual si no recibía nada dejaba que CPU siga ejecutando con el mismo proceso. Queríamos revisar que esta manera sea correcta, para saber si deberíamos cambiarlo. Otra duda que tenia era si al enviar a kernel la instrucción wait o signal debería a su vez desalojarse a ese proceso no?

**Comment by mefederico** [comment]
Hola buenas!

Sobre como implementen la interrupción si con un flag o lo que sea, es a conveniencia de ustedes, lo que si tiene que pasar es que el kernel manda la señal por interrupt para desalojar a un proceso y en el CPU cuando llega al ciclo de instrucción de `check interrupt` el CPU tiene que tratar la interrupción desalojando al proceso si corresponde.

al enviar wait o signal el proceso debe volver al kernel, y como bien lo indica el [enunciado](https://docs.google.com/document/d/1-AqFTroovEMcA1BfC2rriB5jsLE6SUa4mbcAox1rPec/edit#heading=h.o4dclr11f6x2), en caso de signal vuelve el mismo proceso a ejecutar, en caso de wait si hay recursos disponibles vuelve a ejecutar sino, se bloquea

Saludos!

**Comment by tomassagrada** [comment]
todo clarísimo, muchas gracias.
