### ISSUE TITLE
Locación Tablas de Paginas

### ISSUE THREAD

**Issue by 87nsilva** [sisoputnfrba/foro#3865]
Como vi en ya en otro issue, las tablas de paginas no van en el espacio de memoria de usuario. ¿Es posible ubicar la tabla de páginas de un proceso dentro del mismo? Así uno se ahorra una estructura separada y es más sencillo acceder a ella.

### 💭 Soluciones posibles

Así es como pensaba que podia utilizar la tabla integrada al proceso
`typedef struct{
int pid;
t_list* instrucciones;
t_list* filas_tabla;
}proceso;`

**Comment by mefederico** [comment]
Hola buenas! 

Entiendo que ese struct es algo que mantienen en el modulo de memoria, si podrían tenerlo de esa forma sin problemas!

Saludos
