### ISSUE TITLE
Duda MOV_IN

### ISSUE THREAD

**Issue by lperezpersico** [sisoputnfrba/foro#3866]
hola! Tenía una duda sobre las instrucciones MOV_IN y MOV_OUT. 
Como el enunciado dice debemos contemplar qué hacer si lo que queremos leer/escribir ocupa más de una página, pero mi duda es en MOV_IN cuando cpu le pide a memoria que me envíe los datos que están en cierto marco para que la cpu los lea y guarde en el registro correspondiente, por qué me enviaría más de lo que ocupa una página si cada marco es del mismo tamaño que una página?
O sea, entiendo en el caso de que se quiera escribir en memoria, refiriéndome a MOV_OUT, pero no lo entiendo cuando se quiere leer. 
No sé si se me entendió o me enrede mucho, pero bueno, gracias!

**Comment by mefederico** [comment]
Hola buenas! 

Si los marcos y las paginas ocupan lo mismo, pero un registro no ocupa lo mismo que un marco o pagina

Y por otro lado, si yo quiero leer de memoria `HOLA`, el mismo se encuentra entre 2 marcos porque no empieza en el inicio de un marco

La direcciones física que recibís para leer el primer byte es 11 y luego tendrías que recibir otra que sea 4 para leer los 3 bytes restantes



Marco | Contenido
-- | --
0 | `    `
1 | `OLA `
2 | `   H`
3 | `    `
4 | `    `

Espero que quede claro

Saludos!

**Comment by lperezpersico** [comment]
Claro, pero lo que yo no entiendo es si yo en MOV IN le mando la dirección física a memoria de lo que quiero leer, por ejemplo, 11 y memoria lee y envía el byte H. Cómo sabe luego que debe mandarme lo restante? Si únicamente le mandé 1 direccion fisica. Supongo que debería recalcularla en CPU y ahí perdirle lo restante, pero cómo hago ese nuevo cálculo?

**Comment by Acosta-Tomas** [comment]
Buenas, tenia una duda similar con respecto a MOV_IN y MOV_OUT. Lo que entiendo es que en ambas instrucciones lo que se recibe es el registro donde se encuentran las direcciones logicas.
Si tenemos la instruccion **MOV_IN EAX EBX** entonces en EAX hay una direccion logica y en EBX hay otra direccion logica que estan previamente cargadas, donde lo que se copia es un byte ya que buscamos solamente eso. No deberia haber varias paginas involucradas en dicha instruccion no?

**Comment by lperezpersico** [comment]
hola! cómo va?
Vuelvo a escribir porque quería aclarar unas dudas que no me habían quedado del todo claras todavía.

1- Al hacer una escritura en memoria, si yo calculo que los datos a escribir me van a tomar más de una página, sé que cuando calculo la primera dirección física debo hacerlo con el marco correspondiente a la página y el desplazamiento dado en la dirección lógica. 
Pero cuando tengo que volver a calcular la dirección física de lo que me queda por escribir en memoria, sé que debo buscar el marco correspondiente a la página contigua a la anterior, pero el desplazamiento sería 0? O sea, debo considerar que comienza a escribir al comienzo de la nueva página?

2- Mi otra consulta es sobre la lectura, cómo sé yo cuánto espacio en memoria ocupa lo que debo leer? Es decir, sé que debo leer la dirección física que obtengo a partir de la dirección lógica del registro, pero cómo sé si eso que leo está ocupando más de una página? 
Mi duda surge porque más arriba Fede decía que me puede ocupar más de una página lo que debo leer, por ende debo calcular más de una dirección física, pero sigo sin comprender como saber el tamaño total de lo que debo leer.
Desde ya, muchas gracias!!

**Comment by mefederico** [comment]
Hola, 

1. Si, comienza en el 0 de la otra pagina

2. En el caso de MOV_IN tienen que leer el tamaño del registro de datos que tengas como primer parámetro.
En el caso de COPY_STRING se te pasa el tamaño a leer
En el caso de IO_STDIN_READ tienen que leer la cantidad de bytes que indica el registro que reciben en el parámetro "registro tamaño" está vez es el contenido y no el tamaño del registro

Entonces si yo estoy en el ultimo byte de una pagina y tengo que leer 4 bytes, ya me doy cuenta que tengo que leer más de una pagina. Como en el ejemplo que está mas arriba

Espero que quede mas claro con esto 😃 

Saludos!

**Comment by lperezpersico** [comment]
Mil gracias, ahí lo entendí. Cierro el issue entonces :)
