### ISSUE TITLE
Separación de DFS dado un dato mas grande que la pagina

### ISSUE THREAD

**Issue by santi-p98g** [sisoputnfrba/foro#3867]
Buenas!

Quería consultarles sobre el tema de la memoria, ya que es algo que hicimos hace un tiempo y ahora estamos leyendo varios issues de esto.

Al momento se recibir una escritura que supere el tamaño de pagina, por ejemplo 16B en paginas de 4B que requieren 4 marcos para escribir el contenido. Lo que nosotros hicimos fue mandarle a la memoria desde cpu/mmu la primera DF, y memoria se encargaba de hacer la división del dato en los marcos y de corresponder las DFs de los siguientes marcos a escribir.

Es requerido que la cpu al necesitar por ejemplo 4 marcos, deba mandar 4 accesos a memoria? Porque la instrucción es una sola viendolo del lado de cpu. 
O manejandolo de la memoria a efectos prácticos es lo mismo? 
Porque en teoría los accesos a espacio de usuario se manejan desde ella.

Espero haberme explicado. 
Gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Tu pregunta se parece mucho a la del issue #3861 que ya esta resuelto.

Saludos.-

**Comment by santi-p98g** [comment]
Si, lo lei
Pero una cosa es mandar DFs de a una, o una lista de DFs
Y otra cosa es mandar la primera DF y que memoria haga todo el resto de division y busqueda de las otras DFs. 
porque en el primer caso se usa la tlb para todas las DFs y en el segundo solo para la primera.

Por eso va la pregunta

**Comment by iago64** [comment]
Buenas! Cómo va? 

La idea es que las DF las resuelva la CPU y despues se las manden a la Memoria, por eso es que esta la aclaración en la parte de la MMU de la CPU y no en la memoria. 

Saludos.-
