### ISSUE TITLE
Segmentation fault (core dumped) en consola

### ISSUE THREAD

**Issue by camisanchez** [sisoputnfrba/foro#3871]
Hola, como están?

Estamos probando la ejecución de un script mediante consola usando la función main, y al momento de ejecutarla cuando tiene que realizar la creación del PCB, previo a invocar la función crearPCB() nos lanza Segmentation fault (core dumped).

Archivo main.c

```
PCB* crearPCB() {
    printf("Creando PCB...");
    PCB* nuevoPCB = malloc(sizeof(PCB)); //reserva de memoria
	 if (nuevoPCB == NULL) {
        // Manejar error de asignación de memoria
        return NULL;
    }

    nuevoPCB -> PID = generarPID(); // asigno pid - al hacerlo incremental me aseguro de que sea único el pid
    nuevoPCB -> pc = 0; // contador en 0
    nuevoPCB -> quantum = quantum;//quantum generico tomado de kernel.config
	nuevoPCB -> estado = NEW;
    
	//list_add(lista_NEW, 0);
    printf("Se creó el PCB del nuevo proceso, PID %d", nuevoPCB->PID);
	// Logueo la creación del PCB
    char mensaje[100];
    printf(mensaje, "Se creó el PCB del nuevo proceso, PID %d", nuevoPCB->PID);
    log_info(logger, "%s", mensaje);
    
    return nuevoPCB;
}

PCB t_pcb;

int main(int argc, char *argv[]) {

    cargar_configuracion(archivo_configuracion);

    while (1)
    {
        linea = readline(">");

        if (linea)
        {
            add_history(linea);
        }
// PASO 1 - Se ejecutarán los scripts indicados en las pruebas 
        
        if (!strncmp(linea, "EJECUTAR_SCRIPT ", 16))
        { // ejecutar script de comandos
            path_script = strdup(linea + strlen("EJECUTAR_SCRIPT "));
            printf("Se esta ejecutando el script del siguiente path: %s\n", path_script);
            
            PCB* recibido = malloc(sizeof(PCB)); //reserva de memoria
            recibido = crearPCB();
            printf("Se creo un nuevo proceso: %d\n", recibido->PID);
            free(path_script);
            free(linea);
        }
```

Buscamos en el foro algún caso de Segmentation fault y no encontramos ninguno similar.

Quedamos atentos,
Muchas gracias!

@AylenAnchart @TRLaise

**Comment by mefederico** [comment]
Hola buenas! 

Probaste usar [valgrind](https://docs.utnso.com.ar/guias/herramientas/valgrind#tutorial-de-valgrind-y-helgrind)? 
Es posible que te de mas info al respecto, si no entendes lo que te esta diciendo podes volver a este issue y lo vemos juntos 😄 

Saludos!

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue ya que lo vimos en soporte: en esta línea le estaban pasando un string sin inicializar a `printf()`

```c
    char mensaje[100];
    printf(mensaje, "Se creó el PCB del nuevo proceso, PID %d", nuevoPCB->PID);
    log_info(logger, "%s", mensaje);
```

Pero para formatear un string en realidad asumo que la idea era usar `sprintf()`, aunque no es una función tan cómoda para formatear strings como sí lo es `string_from_format()` de las commons. De todas formas, las funciones de `log.h` ya proveen formato printf-like, por lo que alcanza con hacer:

```c
    log_info(logger, "Se creó el PCB del nuevo proceso, PID %d", nuevoPCB->PID);
```

Saludos
