### ISSUE TITLE
Duda sobre Direccion Logica

### ISSUE THREAD

**Issue by juancruznaimo** [sisoputnfrba/foro#3872]
Buenas, tengo una duda sobre la direccion logica. No me termina de quedar en claro la estructura

>A la hora de traducir direcciones lógicas a físicas, la CPU debe tomar en cuenta que el esquema de memoria del sistema es de Paginación. Por lo tanto, las direcciones lógicas se compondrán de la siguiente manera:
[número_pagina | desplazamiento]
Estas traducciones, en los ejercicios prácticos que se ven en clases y se toman en los parciales, normalmente se hacen en binario. Como en el lenguaje C los números enteros se operan independientemente de su base numérica, la operatoria puede desarrollarse de la siguiente forma:
número_página = floor(dirección_lógica / tamaño_página)
desplazamiento = dirección_lógica - número_página * tamaño_página

Osea yo tendría la dirección lógica que tiene dos campos: numero_pagina y desplazamiento. pero para calcular este número de pagina necesito la direccion logica. No entiendo cómo haría esto porque quedaria como recursivo.

>número_página = floor(dirección_lógica / tamaño_página) 

Esta direccion logica, es un registro? o como obtengo ese valor?

Gracias

**Comment by LeandroCarbajales** [comment]
Buenas!
Es la misma lógica que en un ejercicio de paginación que vemos en clases. La DL no es más que un número (que en este trabajo viene como parámetro en la instrucción de pseudocódigo a ejecutar), pero el mismo debe interpretarse como [num_pag, offset] para poder traducirlo a DF.
¿Cómo "dividimos" ese número en esas 2 partes? Con las cuentas que citaste del enunciado (las mismas que en los ejercicios) :)

Te aclara la duda?
Saludos!
       Lean

**Comment by juancruznaimo** [comment]
Sí perfecto 

Gracias!

**Comment by LeandroCarbajales** [comment]
Si la duda está resuelta recuerden cerrar el issue por favor :)
