### ISSUE TITLE
Duda de Paginación

### ISSUE THREAD

**Issue by yaanel** [sisoputnfrba/foro#3873]
Hola! Tengo varias consultas:
Entiendo que cuando Memoria recibe la creación del proceso por parte del Kernel, tiene que iniciar ese proceso sin páginas y, por ende, también debe iniciar una Tabla de Páginas de ese proceso vacía. Luego, entiendo que CPU manda la instrucción _resize_ del proceso para aumentar o disminuir el tamaño del proceso. Lo que no me termina de quedar en claro es si con el resize creo las páginas y ahí directamente las asigno a la Memoria Contigua como frames.
Además, otra pregunta que tengo es: si tengo una estructura que representa el proceso y tiene como datos el PC, el PID y otras cosas. El tamaño del proceso a modificar, ¿sería el tamaño de toda esa estructura? ¿O debería ser un dato dentro de la estructura del proceso que indique el tamaño? Si fuera esto último, ¿el tamaño con el que debería empezar sería cero?
Muchas gracias!

**Comment by LeandroCarbajales** [comment]
Buenas!
Respondo por punto:

> Lo que no me termina de quedar en claro es si con el resize creo las páginas y ahí directamente las asigno a la Memoria Contigua como frames.

Exacto!

> El tamaño del proceso a modificar, ¿sería el tamaño de toda esa estructura? ¿O debería ser un dato dentro de la estructura del proceso que indique el tamaño? Si fuera esto último, ¿el tamaño con el que debería empezar sería cero?

Solamente contemplamos el tamaño de los datos a guardar en el espacio de usuario, no el resto de estructuras administrativas, tranquilamente pueden tener un campo "tamaño" dentro de la misma. Y efectivamente, a efectos prácticos ese tamaño comenzaría en cero.

Te aclara las dudas?
Saludos!
     Lean

**Comment by yaanel** [comment]
Si! Me aclara bastante, pero me surgieron más preguntas ji
La memoria contigua, representada como un void*, la pensaba representar con un array y que cada elemento de ese array sea un frame de la memoria. ¿Eso estaría bien? Si es así, ¿en el frame se guardan páginas por ejemplo [Pag 1 Proceso A, Pag 2 proceso B] ó se guardaría directamente la información de esas páginas y sé cuál contenido pertenece a qué página de qué proceso a partir de la Tabla de Páginas de cada proceso?

**Comment by LeandroCarbajales** [comment]
Buenas!
Justamente la aclaración de que deba ser representada como un void*, es para que no lo representen de otra manera que no sea un void* ya que es la representación más parecida a la realidad (un vector de bytes).
En ese void* solamente vas a guardar lo que pidan los procesos del sistema. Todo el resto de la info la tenés en tus otras estructuras (tablas de página, bitarray, etc.)

**Comment by yaanel** [comment]
Claro, pero el array de void* estaría bien si lo interpreto como que está indexado por marco?

**Comment by LeandroCarbajales** [comment]
Es que no es un array de void*, es un solo void*, sin ningun tipo de estructura interna.
Lo que sí podrías tener indexado por marco es tu estructura que administre qué marcos están libres y ocupados por ejemplo.

**Comment by yaanel** [comment]
Creo que ahí entendí más, perfecto! Gracias :D

**Comment by LeandroCarbajales** [comment]
Un placer!
Si la duda quedó resuelta no olvides cerrar el issue. Cualquier cosa se puede volver a abrir.

**Comment by ArielRotolo** [comment]
Perdón que me meta pero me surgió la duda @LeandroCarbajales

Tiene sentido que al crear el proceso tenga 0 páginas y la tabla de páginas que sea NULL? Yo tenía implementado por defecto asignar 1 página al crearse para hacer al menos 1 malloc ya que con la instrucción resize hacía un realloc de la page table, está mal?
