### ISSUE TITLE
Duda sobre memoria

### ISSUE THREAD

**Issue by KevinQ73** [sisoputnfrba/foro#3874]
Buenas noches!, tengo una duda acerca de que es lo que realmente se guarda en los marcos de la memoria y como gestionarlo a la hora de asignarle páginas. Según el issue #3566 van a ir los datos de las variables como un string, pero entonces me surgen dudas de que es lo que tengo que obtener de las instrucciones del proceso, por eso supongo esto:

- Memoria lee las instrucciones desde el path cuando se lo requiera y con eso, suponiendo que spliteo cada `char* instrucción` en un `char** instrucción[]` y eso lo almaceno todo en una lista. Entonces a la hora de asignarle páginas a un nuevo proceso debo recorrer esa lista e ir agarrando todo valor tanto numérico como string haya como variable después del llamado de X instrucción y pasarlo todo a un void* del tamaño correspondiente a las variables, y luego a eso almacenarlo en sus respectivas páginas y marcos, ignorando si se pasa por parámetro un AX, EDX, o X registro pero si almacenar en la memoria 20 si se pasa por ejemplo `SET AX 20` o 2 si se pasa `JNZ CX 2`.

Espero haberme expresado bien, cualquier cosa estoy a la espera.

**Comment by iago64** [comment]
Buenas! Cómo va?

No, las instrucciones no tienen que cargarlas en el espacio de usuario.

Saludos.-
