### ISSUE TITLE
Por defecto 1 pagina al crear proceso o está mal?

### ISSUE THREAD

**Issue by ArielRotolo** [sisoputnfrba/foro#3875]
Me surgió la duda del issue #3873 que acaba de cerrar @LeandroCarbajales

Tiene sentido que al crear el proceso tenga 0 páginas y la tabla de páginas que sea NULL? Yo tenía implementado por defecto asignar 1 página al crearse para hacer al menos 1 malloc ya que con la instrucción resize hago un realloc de la page table, está mal?

Mi implementación es algo de este estilo:
```C
typedef struct {
    int marco;
    bool asignada;
} Page_table_t; // Tabla donde el indice de pagina representa el marco y si está asignado o no

typedef struct {
    uint16_t pid;
    uint32_t cant_paginas;
    Page_table_t* pagina; // Tabla de paginas
    t_list *instrucciones; // Lista con las instrucciones cargadas del pseudocodigo
} Proceso_t;

void crear_proceso(uint16_t pid, uint32_t cant_paginas, t_list *instrucciones) {

    Proceso_t* proceso = malloc(sizeof(Proceso_t));
    proceso->pid = pid;
    proceso->cant_paginas = cant_paginas;
    proceso->pagina = malloc(cant_paginas * sizeof(Page_table_t));
    proceso->instrucciones = instrucciones;

   for (uint32_t i = 0; i < cant_paginas; i++) {
        proceso->pagina[i].marco = -1; // Al crearse el proceso no tiene marcos asignados a la memoria
        proceso->pagina[i].asignada = false;
    }
   // ....
}
```

**Comment by iago64** [comment]
Buenas! Cómo va?

Cito el enunciado:

> Ante la solicitud de la consola de crear un nuevo proceso el Kernel deberá informarle a la memoria que debe crear un proceso cuyas operaciones corresponderán al archivo de pseudocódigo pasado por parámetro, todos los procesos iniciarán sin espacio reservado en memoria, por lo que solamente tendrán una tabla de páginas vacía.

Resumiendo, si, está mal, no tienen que reservar ninguna página.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas!
Como tip para tu situación de hacer malloc() y realloc(), no sería más sencillo que tu tabla de páginas sea un `t_list*` donde cada elemento de la misma sea un `page_table_t`?
De esa manera te ahorrarías el "cant_paginas", podrías inicializarla vacía sin problema y además te simplificaría la lógica de agregar/quitar páginas ante un resize.

**Comment by ArielRotolo** [comment]
Buen día! Tenés razón Leandro es mucho más práctico con una lista no se porque no se me ocurrió antes 🤦. Muchas gracias!
