### ISSUE TITLE
Dudas Escribir y Leer en Memoria

### ISSUE THREAD

**Issue by ThiagoPerez12** [sisoputnfrba/foro#3876]
Tengo una duda donde seguramente tengo un error conceptual pero no detecto la solución. A la hora de escribir la memoria, si lo que hay que escribir ocupa más que un marco, entiendo que debería buscar la siguiente pagina y seguir escribiendo en el marco de esta "siguiente pagina". El tema viene con si existe la posibilidad de que este nuevo marco ya este escrito y entonces no podría escribir en este ya que lo que tengo que escribir no estaría "continuo" a no ser que guarde el offset donde se empieza a escribir en el nuevo marco. O no hay posibilidad de que por ejemplo se haya escrito en el marco de la pagina 1 y ahora me piden escribir sobre la pagina 0?.

**Comment by iago64** [comment]
Buenas! Cómo va?

Los datos van en **páginas contiguas** del mismo proceso, ahora el tema de en que marco van a quedar depende de como se reserven.
Otra cosa importante, es que la memoria no tiene que "preocuparse" por "pisar" los datos, ya que eso va a ser problema de los scripts que les disponibilicemos.

Saludos.-
