### ISSUE TITLE
Duda CPU y Memoria con MOV_IN y MOV_OUT

### ISSUE THREAD

**Issue by Ivanabete** [sisoputnfrba/foro#3877]
Buenas, unas consultas con respecto a las instrucciones MOV_IN y MOV_OUT.

1. Cuando CPU le manda una dirección física a memoria, por ejemplo, para una lectura (o sea, la instrucción MOV_IN), ¿hasta dónde habría que leer?

Por ejemplo:
![image](https://github.com/sisoputnfrba/foro/assets/129530018/9636d8f5-b65f-425b-b5f3-3c2ef5250aa9)
En este caso, supongamos que CPU hizo la traducción de dirección lógica a física y dio 1.
Una vez que nos paramos en la DF 1, ¿cómo sabe la memoria hasta donde tiene que leer? 
Se me ocurren 3 posibles opciones:
- ¿Leería solo la "U"? o
- ¿Leería hasta el fin de página? o 
- ¿Leería hasta donde le indiquemos, pudiendo ser, por ejemplo "URSADA" lo que queremos leer? 
De ser el tercer caso, ¿cómo le indico que quiero que lea hasta esa "A" final?

2. A la hora de hacer un MOV_OUT, ¿se sobrescribe la información ya existente en esa dirección física particular?

**Comment by mefederico** [comment]
Hola buenas! 

Lee hasta el tamaño del registro de datos

Y en caso de escritura se escribe todo lo que este en el registro de datos, y si se pisa lo que este antes

Saludos!

**Comment by Ivanabete** [comment]
Buenas! Me surgieron unas dudas que no tiene mucho que ver con las anteriores, pero si tiene que ver con las instrucciones MOV_IN y MOV_OUT.

1. Los registros de datos con los que trabajamos, si no me equivoco, son todos numéricos. ¿Implica esto que en memoria voy a tener únicamente datos numéricos (por más de que la memoria sea un void*)?
De no ser así, supongamos que yo leí en memoria "HOLA":
1.1 ¿Cómo lo meto a un registro? 
¿Lo casteo al tipo de dato del registro y hago la asignación (suponiendo que mi registro de datos es de 4 bytes, algo así como: registro_datos  = (uint32_t*) valor_leido)? 
¿Debería usar la instrucción SET para eso mismo? 
1.2 ¿Cómo leería yo después ese dato para escribirlo en memoria usando MOV_OUT? ¿Lo leería como un "HOLA" o como un entero?
De ser un entero, supongo que sería un entero con los valores ASCII de cada uno de los caracteres. Para escribirlo en memoria, ¿debería transformar esos ASCII en caracteres otra vez y ahí escribir?


2. Esta duda surge de haber leído el issue #3866.
Me gustaría tomar el mismo ejemplo, donde quiero leer "HOLA" y tengo "H" y "OLA" en páginas distintas. 
Si yo estoy recibiendo una única dirección lógica como parámetro de MOV_IN, ¿cómo puedo saber que tengo que acceder a dos marcos distintos?

**Comment by RaniAgus** [comment]
¡Buenas!

> Los registros de datos con los que trabajamos, si no me equivoco, son todos numéricos. ¿Implica esto que en memoria voy a tener únicamente datos numéricos (por más de que la memoria sea un void*)?

1. Voy a responder tu pregunta con el siguiente ejemplo:

```c
#include <stdio.h>

int main() {
    int entero1 = 0x616C6F48;
    int entero2 = 0x6E754D20;
    int entero3 = 0x6F64;

    puts(&entero1);

    return 0;
}
```

Creo tres variables numéricas y luego le paso a `puts()` un puntero a la primera de ellas. ¿Va a leer los números? ¿Va a hacer un casteo? Probemos:

```bash
$ gcc -o ejemplo ejemplo.c
$ ./ejemplo
Hola Mundo
```

Imprime un texto "Hola Mundo", ¿a qué se debe esto? La memoria siempre está compuesta por bytes. Binarios: ceros y unos. ¿Entonces cómo hacemos para escribir caracteres alfanuméricos? Esa pregunta probablemente ya la hayan respondido en Arquitectura, habrán visto que existe una tabla que asocia un valor entero con un caracter: la tabla ASCII.

Entonces, si inspeccionamos la memoria asignada a estas tres variables vamos a ver lo siguiente:

![image](https://github.com/sisoputnfrba/foro/assets/39303639/6d152a19-4e3e-44d9-a844-59f2367e3f1c)

A la izquierda están los valores de las 3 variables de forma contigua: `0x616C6F48` es `48 6F 6C 61` (porque está en Little Endian) y así. A la derecha, está exactamente lo mismo pero interpretado como caracteres ASCII: el `48` en hexa es la `H`, el `6F` es la `o`, etc.

Entonces, en este caso, `puts()` simplemente va leyendo la memoria byte a byte e interpretándola como caracteres ASCII hasta frenar en un `00`, que es el caracter `'\0'`.

Bueno, así como se lee y escribe la memoria en C, también va a ser igual en nuestro TP. Los bytes leídos por la interfaz STDIN son caracteres ASCII y se guardan en el `void*` de memoria como lo que son: bytes. Bytes que pueden interpretarse como caracteres.

De la misma forma es que nosotros los vamos a leer o escribir en los registros: si mide 1 byte (uint8_t), copiamos 1 byte (ej: `H`, que sería el número `72`); si mide 4 bytes (uint32_t), copiamos 4 bytes (ej: `Hola`, que sería el número `1634496328`). Para esto no necesitamos hacer ninguna magia de casteos, alcanza con simplemente usar `memcpy()`.

> Si yo estoy recibiendo una única dirección lógica como parámetro de MOV_IN, ¿cómo puedo saber que tengo que acceder a dos marcos distintos?

2. Sabiendo el tamaño de página, la cantidad de bytes a leer y el desplazamiento dentro de la página ya vas a tener todo lo necesario para saber que vas a tener que leer de más de una. 

Ejemplo: Con tamaño de página 32, si yo quiero leer la dirección lógica 30 y guardarla en `EAX`, ya sé que:

- Número de página: 0
- Desplazamiento: 30
- Tamaño a leer: 4

30 + 4 se va más allá del tamaño de página, entonces voy a necesitar leer de la 0 y de la 1.

> ¿El tamaño de las direcciones físicas necesita ser calculado? sta duda es más que nada para saber si tratar las direcciones físicas como "uint32_t" o como "int", o si es indiferente.

3. No hace falta, con un `int` les va a sobrar ya que no vamos a usar una memoria tan grande (la VM se quedaría sin memoria sino 😅) pero quizás un `uint32_t` sea lo más correcto ya que no existen las direcciones físicas negativas :P

> ¿Cualquier registro podría ser un registro dirección? En ese caso, las direcciones lógicas podrían ser de 1 byte o 4 bytes, ¿correcto? ¿Me influye eso en la dirección física?

4. No veo por qué influiría, o sea, es cierto que un registro de 1 byte puede abarcar menos memoria que uno de 4 bytes, pero la separación entre número de página y desplazamiento es la misma, siempre teniendo en cuenta el tamaño de página.

Saludos

**Comment by Ivanabete** [comment]
Perfecto! Muchas gracias.
Me quedó todo mucho más claro, pero todavía me gustaría confirmar una cosa con respecto a la pregunta 2.
Sigo tomando como ejemplo el caso de querer leer "HOLA".


Me gustaría saber si las siguientes afirmaciones son correctas:
1. Si yo tuviera "___H" en el marco 2 y "OLA_" en el marco 1, necesitaría de 2 invocaciones de "MOV_IN", con direcciones lógicas distintas.

2. Si "___H" estuviera en el marco 2 y "OLA_" estuviera en el marco 4, también necesitaría de 2 invocaciones de "MOV_IN" por un caso similar al anterior.

3. Si tuviera "___H" en el marco 1 y "OLA_" en el marco 2, necesitaría de 1 sola invocación de "MOV_IN", con su respectiva dirección lógica. La dirección física debería darme 7 (tamaño de página de 4 bytes) y, si quisiera guardarlo en EAX, leería 4 bytes, entonces ahí tendría el "HOLA".

**Comment by mefederico** [comment]
Hola! 

El programa siempre va a hacer un solo `MOV_IN`, que por dentro el `CPU` va a tener que hacer 1 o más traducciones de `DL` a `DF` y por lo tanto enviar a la memoria una o varias peticiones de lectura, con el respectivo tiempo de retardo

Pensemos en términos de paginas donde el valor siempre esta continuo

Página | Contenido
--| --|
0 | `HOLA`  -> Tengo que traducir una sola DL a DF y leer una sola vez
1 | `    `

Página | Contenido
--| --|
0 | `   H`  -> Primera traducción
1 | `OLA ` -> Segunda traducción

Ahora lo lo único que va a variar en el caso 2 es cuando le preguntes a memoria donde está la pagina 0 y 1, te va a dar 2 marcos, que pueden o no estar consecutivos pero eso no te importa.

Saludos!

**Comment by Ivanabete** [comment]
Hay algo que no me termina de quedar claro.

Cuando se hace la invocación del MOV_IN, espera como parámetros un registro de datos y un registro dirección que contiene la dirección lógica. 
MOV_IN (Registro Datos, Registro Dirección)

Entonces, ¿cómo puede ser que yo a partir de una única DL (obtenida del registro dirección) haga más de una traducción a DF distintas?

**Comment by RaniAgus** [comment]
Volvemos una vez más al ejemplo. Teniendo configurado `TAMANIO_PAGINA=32` y yo quiero ejecutar este `MOV_IN`:
```
SET EAX 30
MOV_IN EBX EAX
```
- En `EAX` tengo guardada la dirección lógica 30
- La longitud a leer va a ser el tamaño de `EBX`, o sea 4
- Entonces tengo que leer desde el byte 30 hasta el 33, teniendo tamaño de página 32

Con esto ya puedo saber que las páginas que tengo que pedir son la 0 y la 1, porque `30 / 32 = 0` y `33 / 32 = 1`.

**Comment by Ivanabete** [comment]
Perfecto, creo que con eso ya puedo avanzar.

Vuelvo a cerrar el issue por ahora. Muchas gracias.
