### ISSUE TITLE
duda sobre liberacion de recursos al finalizar

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3878]
Buenas! vengo a hacer un poco de memoria del issue #3697 porque ahora pobrando algunos casos nos confundimos un toque.

Hicimos un ejemplo tipo parcial de la teoria donde hay que sincronizar varios procesos para que se escriba C-A-S-A infinitamente
les adjunto el pseodocodigo:

PROCESO A:

```
RESIZE 1
SET AX 97
SET SI 1
MOV_OUT SI AX
WAIT A
IO_STDOUT_WRITE Int1 SI SI
SIGNAL CS
JNZ AX 4
EXIT

```

PROCESO C
```
RESIZE 1
SET BX 99
SET AX 1
SET SI 0
MOV_OUT SI BX
WAIT C
WAIT CS
IO_STDOUT_WRITE Int1 SI AX
SIGNAL A
SIGNAL S
JNZ AX 5
EXIT
```

PROCESO S
```
RESIZE 1
SET AX 1
SET BX 115
SET SI 2
MOV_OUT SI BX
WAIT S
WAIT CS
IO_STDOUT_WRITE Int1 SI AX
SIGNAL A
SIGNAL C
JNZ AX 5
EXIT
```
Los mov_out no son muy importantes, es solo para poder imprimir las letras.

En Kernel definimos a los recursos con los valores: `[A=0,C=1,S=0,CS=1]`

Luego ejecutamos el siguiente script:
```
DETENER_PLANIFICACION
INICIAR_PROCESO s
INICIAR_PROCESO a
INICIAR_PROCESO c
INICIAR_PLANIFICACION
```

Le dejo hacer varias vueltas y nos imprime casa varias veces: 

```
PID: 3 - Operacion: IO_STDOUT_WRITE
MEMORY VALUE: c
 PID: 2 - Operacion: IO_STDOUT_WRITE
MEMORY VALUE: a
 PID: 1 - Operacion: IO_STDOUT_WRITE
 MEMORY VALUE: s
 PID: 2 - Operacion: IO_STDOUT_WRITE
MEMORY VALUE: a
 PID: 3 - Operacion: IO_STDOUT_WRITE
 MEMORY VALUE: c
PID: 2 - Operacion: IO_STDOUT_WRITE
MEMORY VALUE: a
PID: 1 - Operacion: IO_STDOUT_WRITE
MEMORY VALUE: s
PID: 2 - Operacion: IO_STDOUT_WRITE
MEMORY VALUE: a
```

Luego procedemos a finalizar a los 3 procesos por consola. Entonces por lo que habia quedado del issue #3697  como ningun recurso hace signal de lo que el esta reteniendo voy a terminar con muchas mas instancias en todos los recursos de las que habia inicialmente

En una prueba quedo: `[A=3,C=3,S=2,CS=5]` dado que por ejemplo, para el proceso A, él tenia tomadas tres instancias del recurso A, no sabe si otro proceso hizo signal ni nada.

Entonces la pregunta es si este comportamiento y estos valores son correctos o tendrian que quedar como estaban al inicio?? porque me acuerdo del issue anterior pero no me terminan de cerrar estos valores.

Perdon que se me hizo muy largo y muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

Honestamente me da la sensación que la estas rebuscando demasiado, no es una prueba que tengamos pensada, pero si te deja más tranquilo, al ser comportamiento no definido del lado del semáforo, no me parece que este mal el resultado que están obteniendo.

Saludos.-

**Comment by GonTurri** [comment]
Gracias me quedo tranquilo entonces. Me pondré a revisar la teoría por si las dudas
