### ISSUE TITLE
Tamaño de Lectura

### ISSUE THREAD

**Issue by S4n7i29** [sisoputnfrba/foro#3879]
Buenas! Tenía una duda sobre stdin_read. Cito lo preguntado en #3593  Si lo que el usuario pasa por consola (que debe ser escrito posteriormente en memoria) sobrepasa el tamaño total indicado, deberíamos tirar un error o simplemente leer (y escribir en memoria) hasta que lleguemos al tamaño pasado (ignorando los caracteres que sobren).

Y sobre el caso en el que el usuario escriba menos de lo "requerido", habiendo leído una de las respuestas al issue citado, en la cual se decía que no se iba a pasar menos, no tenemos en cuenta ese caso? O tendríamos que hacer algún tipo de validación, teniéndolo en cuenta?

Muchas gracias!

**Comment by mefederico** [comment]
Hola buenas! 

Más o menos las consultas están resueltas en ese issue, pero lo que deberían hacer es truncar el dato, es decir ignorar los caracteres que sobren. Para esto pueden hacer substring o en el send a memoria poner el tamaño recibido y solo se van a mandar hasta esos caracteres, pero implementaciones posibles hay infinitas así que las que más les guste/funcione/salga/compile va a estar bien.

No vamos a ingresar datos de menos, si por comodidad ustedes quieren manejarlo ya que dejarlo romper de forma no controlada puede dar dolores de cabeza, simplemente controlen que si el dato es menor lo pidan de nuevo o tiren un error y terminen la IO. Lo que les quede más cómodo.

Yo iría por la primer opción que es mas amable con el error humano.

Saludos!

**Comment by mefederico** [comment]
Hola @S4n7i29 te sirvio la respuesta?
Podemos cerrar el issue?

Saludos!

**Comment by S4n7i29** [comment]
> Hola @S4n7i29 te sirvio la respuesta?
> 
> Podemos cerrar el issue?
> 
> 
> 
> Saludos!

Sii, me re sirvió. Pensé que había respondido, me olvidé, mil disculpas.
