### ISSUE TITLE
Pequeñas consultas de escritura en memoria

### ISSUE THREAD

**Issue by AgustinCarlanaRivero** [sisoputnfrba/foro#3880]
Hola, buenas. En la consigna dice: _Ante un pedido de escritura, escribir lo indicado a partir de la dirección física pedida. En caso satisfactorio se responderá un mensaje de ‘OK’._
Ante esto tenemos 2 dudas:
1 - Literalmente tiene que responder “Ok” al cpu, o es simbolico y por ejemplo puede responder solo un opcode?
2 - Y bajo que circunstancias no sería satisfactoria la escritura? Se contemplará eso en las pruebas?
Muchas gracias de antemano.

**Comment by RaniAgus** [comment]
¡Buenas! Es solo una forma de decir que es una petición sincrónica, o sea, se envía el pedido de escritura y se espera a que se complete antes de continuar. Saludos

**Comment by AgustinCarlanaRivero** [comment]
Perfecto, muchas gracias
