### ISSUE TITLE
Comunicacion entre interfaces y memoria

### ISSUE THREAD

**Issue by fmigliavacca** [sisoputnfrba/foro#3881]
Hola! Tengo una duda con las instrucciones MOV_IN y MOV_OUT, estaría bien que yo decida que cuando a la CPU le llega esa instrucción, esta obtenga la dirección física, luego se la pase a Kernel, y Kernel le pase la dirección y el PID a la interfaz? Para que la interfaz sea la que le pase el PID a memoria? Si no es así, quién estaría correcto que le pase el PID a memoria?

**Comment by iago64** [comment]
Buenas! Cómo va?

Las instrucciones MOV_IN y MOV_OUT son de comunicación directa entre Memoria y CPU, no deberían pasar por el Kernel.

Saludos.-

**Comment by fmigliavacca** [comment]
Disculpa, la duda más bien era con las instrucciones de CPU para llamar a las interfaces stdin y stdout, me confundí con las instrucciones pero la pregunta es la misma

**Comment by iago64** [comment]
Buenas! Cómo va?

En las instrucciónes para llamar a STD_IN y STD_OUT si tenes que pasar por el kernel porque no tenes conexión directa CPU - Interfaz.

Saludos.-
