### ISSUE TITLE
Duda sobre Wait

### ISSUE THREAD

**Issue by fedenimi** [sisoputnfrba/foro#3883]
Hola, qué tal? Tengo una consulta acerca de cómo se debe manejar el caso en el que un proceso hace wait a un recurso y no necesita bloquearse. Yo en soporte había entendido que el proceso tenía que ir ready, pero estoy viendo issues en el foro que dicen que el proceso debe volver a exec. Quisiera saber si entendí mal o si cualquiera de las dos opciones sería correcta. Muchas gracias y saludos.

**Comment by iago64** [comment]
Buenas! Cómo va?

Si no se bloquea tiene que volver a EXEC.

Saludos.-

**Comment by fedenimi** [comment]
Ok perfecto, gracias!
