### ISSUE TITLE
Duda sobre WAIT y SIGNAL

### ISSUE THREAD

**Issue by LeonelArianContreras** [sisoputnfrba/foro#3884]
Hola! Cómo va? Estábamos viendo cómo gestionar bien el WAIT o el SIGNAL, y nos surgió una duda con respecto a qué pasa si el proceso hace un WAIT pero este mismo finaliza sin hacerle un SIGNAL antes (si es que puede llegar pasar). Cómo podríamos saber, una vez que se solicita el EXIT, si el proceso a finalizar tiene asignado un recurso? Porque tenemos planteado que desde CPU se manda el pcb junto al recurso requerido, o sea, lo manejamos como un char*,  y una vez se procesa el WAIT o el SIGNAL, perdemos el registro de ese recurso (básicamente, cuando llegaría a EXIT, no sabemos cuál es el recurso asignado). Si todo lo previamente dicho puede ocurrir, sería conveniente agregar los recursos en la pcb? Mil gracias de antemano!

**Comment by mefederico** [comment]
Buenas!

Si, al finalizar tienen que liberar los recursos que tienen tomados con un WAIT. Como mantengan el control de cuantos recursos tiene un proceso dado es decisión del equipo y no nos metemos en como lo implementen. Lo que les quede más cómodo y les funcione de la mejor manera va a estar bien

Solo por recomendación no piensen que TODO tiene que estar en el PCB necesariamente, pueden usar estructuras auxiliares.

Saludos!

**Comment by LeonelArianContreras** [comment]
Buenisimo, mil gracias !
