### ISSUE TITLE
con respecto a la finalizacion de procesos bloqueados

### ISSUE THREAD

**Issue by nicolasvultaggio** [sisoputnfrba/foro#3885]
Entiendo que si se pide finalizar un proceso que en ese momento esta bloqueado, se debería esperar a que ese proceso vuelva a la cola ready para poder finalizarlo correctamente.
Pero en el caso en los que justo ese proceso esta ejecutandose, y en ese ciclo de instruccion justo se ejecuta una syscall bloqueante (que devuelve el pcb a kernel, justamente antes de poder hacer check interrupt), que hacemos con la interrupcion de finalizar el proceso? la descartamos?

**Comment by mefederico** [comment]
Hola buenas!

Si el proceso está en al cola de bloqueados lo tienen que poder finalizar sin problemas, lo que se dijo en otros issues es si el proceso JUSTO estaba ejecutando una IO, en ese caso si, se espera que el proceso termine su IO.

Para el caso que justo hace un WAIT o SIGNAL, le dejan hacer eso y lo matan en cuanto puedan (incluso dejarlo volver para terminar su ciclo de instrucción si les es más cómodo). En el caso que haya vuelto para hacer una IO lo pueden desalojar antes de que se vaya a la IO

Y sobre si les queda una interrupción colgada, citando el enunciado:

> En este momento, se deberá chequear si el Kernel nos envió una interrupción al PID que se está ejecutando, en caso afirmativo, se devuelve el Contexto de Ejecución actualizado al Kernel con motivo de la interrupción. Caso contrario, se descarta la interrupción.

Si la interrupción no les corresponde la descartan

Saludos!

**Comment by Lisandrogq** [comment]
Buenass, me sumo a este issue porque creo que no corresponde abrir uno nuevo por esta pequeña pregunta relacionada a este fragmento de la respuesta:
>  lo que se dijo en otros issues es si el proceso JUSTO estaba ejecutando una IO, en ese caso si, se espera que el proceso termine su IO.

Nosotros no tuvimos mayores problemas en poder finalizar un proceso que estaba utilizando una IO (no esperamos a que termine su IO). Obligatoriamente debemos esperar a que termine la IO para finalizarlo? o es solo una recomendacion para facilitar la implementacion?

**Comment by FredeHG** [comment]
Hola lisandro!

No hace falta que esperen, simplemente en otros issues y según las implementaciones particulares se les permitió esa implementacion, si ustedes pueden realizar la finalización sin tener que esperar que vuelva está perfecto

Saludos

**Comment by nicolasvultaggio** [comment]
> Y sobre si les queda una interrupción colgada, citando el enunciado:
> 
> > En este momento, se deberá chequear si el Kernel nos envió una interrupción al PID que se está ejecutando, en caso afirmativo, se devuelve el Contexto de Ejecución actualizado al Kernel con motivo de la interrupción. Caso contrario, se descarta la interrupción.
> 
> Si la interrupción no les corresponde la descartan


claro, yo me refería mas al caso en el que, como el proceso que se pidió finalizar todavía esta en cpu, porque esta ejecutando su ciclo de instrucción (supongamos antes de execute), entonces el kernel le pide el desalojo a la cpu. Mientras, el proceso seguía su ciclo de instrucción y ejecuto la syscall bloqueante, DESALOJANDOSE de la cpu después de que haya llegado la interrupción, pero antes de que esta se atienda. Entonces, en ese caso, cuando chequea la interrupción, esta finalización del proceso se ignora? se que quizás lo que cité es literalmente la respuesta a lo que estoy preguntando, pero es que me suena muy raro descartar una interrupción de finalizar un proceso solo porque justo estaba ejecutando una syscall bloqueante. O sea, yo con eso que dice el enunciado pensé que incluía más que nada a los desalojos por fin de quantum, no a la finalización de un proceso.

**Comment by mefederico** [comment]
Hola! 

El proceso lo van a tener que finalizar si o si, ahora si van a hacerlo con esa interrupción o ya que lo tienen en kernel lo matan sin usar esa interrupción es a gusto de ustedes

En caso de hacer la syscall y el proceso se bloquee, se tiene que finalizar y no quedar bloqueado.

Me pude explicar?
Saludos!

**Comment by nicolasvultaggio** [comment]
okey, perfecto!
