### ISSUE TITLE
Duda Asignación de Páginas a Frames 

### ISSUE THREAD

**Issue by yaanel** [sisoputnfrba/foro#3886]
Hola! Tengo una duda. Cuando Memoria recibe un resize, en caso de que sea para aumentar el tamaño del proceso, agrega esa "N" cantidad de páginas a la tabla de páginas del proceso. Entonces, ¿es en ese momento que se asignan esas nuevas páginas a los frames en memoria contigua? Si es así, cuando creo las páginas y están vacías, al momento de asignarles frames, ¿debería agregar como contenido "NULL" a los frames al estar las páginas vacías? ¿O con solo modificar el bitarray y marcar la página cómo ocupada ya estaría?
O sea, si hay una página vacía en un marco en memoria, ¿cuál sería el indicativo?
Gracias :D

**Comment by mefederico** [comment]
Hola buenas! 

Trato de responder de la mejor manera porque hay varios conceptos en la misma pregunta:

Primero: La memoria no sabe el concepto de si la memoria esta vacía, no conoce lo que es un contenido valido o no, solo tiene que saber si un marco esta ocupado o no y que pagina tiene ocupado ese marco

Es más en el enunciado aclara que no tienen que "limpiar" las paginas a liberarlas

> Esta petición podrá venir solamente desde el módulo Kernel. El módulo Memoria, al ser finalizado un proceso, debe liberar su espacio de memoria (marcando los frames como libres pero sin sobreescribir su contenido).

Ahora cuando se hace un resize, si, a la tabla de paginas asociada al proceso se le agrega una entrada, y para esto, es OBLIGATORIO asignarle un marco.

> al momento de asignarles frames, ¿debería agregar como contenido "NULL" a los frames al estar las páginas vacías?

No, no tienen que tocar los datos que estaban en el frame.

Las paginas no se marcan como ocupadas o libres, las tenes o no las tenes, los frames son los que están libres o no.

Espero que se entienda 😄 

Saludos!

**Comment by yaanel** [comment]
Gracias por responder! Entonces, cuando se hace un resize, marco los frames como ocupados (sin modificar el contenido ni inicializarlo) en un bitarray, asigno esos frames a las páginas correspondientes de la tabla de páginas de ese proceso y estaría entonces?
Gracias nuevamente :D

**Comment by mefederico** [comment]
Exactamente, y en caso de no tener marcos disponibles para el resize, tienen que devolver Out of Memory como dice el [enunciado](https://docs.google.com/document/d/1-AqFTroovEMcA1BfC2rriB5jsLE6SUa4mbcAox1rPec/edit#heading=h.tfqn49hcwh8v)

De nada!

**Comment by yaanel** [comment]
Gracias, perfecto!
