### ISSUE TITLE
duda con el epacio de usuario

### ISSUE THREAD

**Issue by mSpadoni** [sisoputnfrba/foro#3887]
hola buenas noches, hay algo que no entendí sobre el espacio de usuario, en esta variable debemos guardar los string que queremos escribir en memoria por ejemplo o es la misma memoria con los frames que necesitamos??

**Comment by mSpadoni** [comment]
ósea con guardar el string me refiero a que lo guardamos en ese espacio de usuario para luego cargarlo en la pagina que le corresponde

**Comment by mSpadoni** [comment]
y en el caso que sea la memoria en si, como hago para agregar cada dato en los frames?? porque estaba leyendo otros issues y vi que esto no se podia

**Comment by mSpadoni** [comment]
si es el la memoria, como hago para guardar los datos en cada frame?, los voy cargando de a uno?? y si es lo ultimo, como hago para diferenciar cual es cada frame??

**Comment by mefederico** [comment]
Hola buenas!

No termino de entender la pregunta y siento que estas confundiendo el concepto de frame

Lo que ustedes tienen en memoria es un `malloc(tam_memoria)` esa memoria esta "virtualmente" dividida en frames, en cuantos? En `tam_memoria` / `tam_frame` o `tam_pagina` que es lo mismo.

Entonces cuando te llegue una petición de escritura te va a llegar algo como "Escribime `HOLA` en la dirección física 10" (acá ustedes definen como van a estructurar esta petición) y la memoria va a agarrar el puntero del malloc, con magia de aritmetica de punteros, dejo un gran comment de Dami que estaba inspirado se ve explicando la aritmetica https://github.com/sisoputnfrba/foro/issues/3781#issuecomment-2133708741, van a poder ir escribiendo en esa memoria

Espero que esto te sirva!
Saludos!

PD: Podes editar el body del issue para no estar haciendo comentarios anidados, por si queres hacer aclaraciones ni bien terminas de postear el issue, tal vez es mejor editarlo y darle más forma. Incluso tu issue se me paso porque vi que tenia un comentario y asumí que otro ayudante/profesor lo había tomado 😄

**Comment by mSpadoni** [comment]
muchas gracias.
también tengo otra duda:
En caso en que el CPU me pase un dato que ocupa mas de una pagina (paginas de 4bytes y un dato de 16 bytes por ejemplo), yo entiendo que la primera parte de ese dato lo voy a tener que guardar en la dirección lógica que obtengo a partir de la dirección física que me pasa CPU, pero el a la otra parte lo voy a tener que guardar en 2 paginas y la duda que tengo es como va hacer la CPU para saber donde guarde el resto ¿tengo que pasarle la dirección física de esas paginas?

**Comment by RaniAgus** [comment]
¡Buenas!

> En caso en que el CPU me pase un dato que ocupa mas de una pagina (paginas de 4bytes y un dato de 16 bytes por ejemplo)

¡Alto ahí! CPU _nunca_ le va a pasar a Memoria un dato que deba escribirse o leerse en varias páginas/frames. Antes de eso, debió haber "partido" dicho dato y hecho las traducciones de dirección lógica a física que necesite, de la misma forma que en el ejemplo de este issue: https://github.com/sisoputnfrba/foro/issues/3877#issuecomment-2156780059

> yo entiendo que la primera parte de ese dato lo voy a tener que guardar en la dirección lógica que obtengo a partir de la dirección física que me pasa CPU

Al momento de leer o escribir en espacio de usuario, la CPU va a pasar:
- Dirección física
- Tamaño
- Valor

Y la Memoria *no* va a convertir la dirección física a lógica (de ser así, ¿para qué la MMU la convirtió de lógica a física en un principio?), sino que simplemente va a hacer una escritura o una lectura similar a lo que hace `memcpy()`:

```c
// para leer
memcpy(valor, inicio_memoria + direccion_fisica, tamanio);

// para escribir
memcpy(inicio_memoria + direccion_fisica, valor, tamanio);
```

Saludos

**Comment by mSpadoni** [comment]
gracias
