### ISSUE TITLE
duda almacenamiento en registro al leer mas de una pagina MOV_IN

### ISSUE THREAD

**Issue by mvargassoto** [sisoputnfrba/foro#3888]
Hola, buenas noches, tengo una duda con respecto al caso en el que me doy cuenta desde CPU que debo leer mas de una pagina, entiendo por lo que lei en varios issues de que manera darme cuenta, pero no estoy pudiendo cerrar la idea de como escribir en mi registro de 4 bytes (supongamos), cual seria la secuencia de pasos en ese caso? como manipulo el registro a partir de los valores que leo de cada pagina? ya que son bytes separados. Gracias!

**Comment by mefederico** [comment]
Hola buenas!

Te hago otra pregunta, como estas haciendo cuando haces una sola lectura? 
Y cuando serializan un mensaje para mandar por socket a otro modulo, como lo hacen? 

A lo que quiero llegar es que la implementacion es similar, tienen que hacer manejo de bytes con memcpy o similar para lograr guardar los bytes que leen en el orden que corresponde en el registro que corresponde, se entiende?

Saludos!

**Comment by mvargassoto** [comment]
Se entiende, gracias!

**Comment by mefederico** [comment]
Justo respondiendo otro issue di con este comment de dami https://github.com/sisoputnfrba/foro/issues/3781#issuecomment-2133708741 que te puede ser muy útil para el manejo de aritmética de punteros

**Comment by mvargassoto** [comment]
- buenas, retomando el issue, vi este comentario https://github.com/sisoputnfrba/foro/issues/3757#issuecomment-2128335100 y me generó dudas que no me plantee antes, entiendo como lei en otros issues que:

  - si desplazamiento + bytes de registro > tamanio de pagina entonces se que tengo que traerme la pagina referenciada por la DL y su contigua 

  con esa logica y teniendo en cuenta que los tamaños de registros estan fijos entre 1 y 4 bytes, estaba considerando solo dos casos para los registros de 4 bytes, que deba traer una pagina o una y su contigua. Estoy omitiendo otros casos posibles? cuando se podrían dar mas de 2 peticiones de paginas? se que se puede dar si usamos tamaño de pagina de 2 bytes y el registro es de 4, per no me imagino otro caso para la lectura
  
  Entiendo que en COPY_STRING si se elige implementar usando mov_in mov_out se iria leyendo tambien de hasta 2 paginas en el caso de usar un registro de 4 bytes asi que tampoco veria la situacion de traerse mas de dos paginas.

**Comment by mvargassoto** [comment]
Lo primero, super clara la explicacion de como manipular los bytes de llegada dentro del registro a usar. Gracias

> Buenas! Cómo va?
> 
> El tema de hacer N `send()` para obtener las direcciones es una forma, otra que también puede leer o escuchar de algún compañero es que le mandan en un solo `send()` todas las páginas de las cuales quieren obtener el marco y lo copado es que ambas implementaciones están bien (siempre y cuando tengan el log obligatorio de los accesos a tabla de páginas)
> 
> Después a la hora de escribir, pueden mandarle a la memoria los fragmentos a escribir en cada marco con la dirección física que calcularon, el tamaño de lo que tiene que escribir en esa dirección física y el contenido a escribir y de nuevo, pueden hacer uno por uno o pueden hacerlo todo en un solo mensaje, ahi por favor no se la compliquen de mas, busquen la forma que mas fácil les resulte.
> 
> Saludos.-

- leyendo este comentario del issue https://github.com/sisoputnfrba/foro/issues/3757 se me generaron dudas con respecto a casos a contemplar cuando se lee en MOV_IN
 Siguiendo la logica de: desplazamiento + tam registro (4 bytes ej) > tamaño pagina => traigo dos paginas , la segunda contigua a la primera, me puse a pensar **¿en qué casos debería traerme más de dos paginas, o sea, hacer mas de 2 peticiones de marcos?**. Entiendo que se puede dar teniendo el registro de 4 bytes y un tamaño de pagina de 2 bytes, pero mas allá de es unico caso no veo otro.
 - Por otro lado, si el motivo de los n send() es COPY_STRING, si elijo implementar la funcion usando MOV_IN MOV_OUT tampoco veo el caso en donde traer mas de 2 paginas, lo que tendria son n ciclos de llamados a MOV (dependiendo de la cantidad de bytes pasadas por parametro) pero usando un registro de 4 bytes. **¿Tiene sentido esa implementacion ó hay errores conceptuales?**
 
Perdon si estan siendo preguntas repetitivas por fallas conceptuales pero en la practica me estan surgiendo dudas que en la teoría no las tenia en cuenta

**Comment by mefederico** [comment]
Hola buenas! 
Genial que te haya servido el comentario de dami, realmente esta para hacerlo docu directamente

Sobre el caso de cuando tendrías que traer más de un marco, en este issue se hablo bastante del tema
https://github.com/sisoputnfrba/foro/issues/3877 seguro te saca la duda

Me genera curiosidad como harías para usar N MOV_IN y MOV_OUT, dado que esa función toca registros y no deberías editar el valor de ningún registro en COPY_STRING, solamente copiar el string

si te referís al llamado que hace CPU cuando tiene que hacer un MOV_IN o un MOV_OUT, que seguramente lo tienen implementado como algo del tipo "Leeme X bytes de esta DF", en ese caso si estaría bien conceptualmente la implementación

También se escribe y lee más de una pagina en las IO

Espero que no se me haya pasado ninguna pregunta este lunes fue duro 😄 

Saludos!

**Comment by mvargassoto** [comment]
Buenisimo Fede, voy a leer el issue. Con respecto a lo de COPY_STRING si, me exprese mal jajaja, es la idea de hacer n veces ese ida y vuelta con memoria pero sin usar un registro propio de la cpu

muchas gracias por despejar las dudas! cierro issue
