### ISSUE TITLE
Dudas Instrucciones - Paginación.

### ISSUE THREAD

**Issue by DanielKesel** [sisoputnfrba/foro#3889]
Hola!! Como están?
Tenemos un par de dudas con respecto a paginación.
Actualmente (sin paginación desarrollada) tenemos funcionando el tema que la memoria guarde las instrucciones (previamente dadas por el path enviado por kernel) en un array y estas quedan a disposición de la CPU que las irá pidiendo con el PC que hará referencia al index requerido.
Ahora que tenemos que implementar paginación simple: 
1- ¿Las instrucciones tienen que guardase en el proceso de paginación también? 
2- A- En el caso que si ¿Como se acceden individualmente a estas instrucciones? Teniendo en cuenta que dependiendo la cantidad de instrucciones pueden ser la cantidad de paginas que se le da a la tabla.
2- B- En el caso que no ¿Hay que calcular la cantidad de instrucciones que va a usar el proceso para darle un tamaño que va a ocupar el proceso en la paginación (cuantas paginas hay que usar)?
3- Puede ser que solo se use la paginación para tratar las instrucciones de MOV y las STDIN y STDOUT? en el caso B.

**Comment by LeandroCarbajales** [comment]
Buenas!
No, las instrucciones están en el enunciado por separado del esquema de memoria, esto significa que para este trabajo no forman parte del tamaño del proceso ni ocupan lugar en el espacio de memoria justamente para que no tengan que rehacer algo ya funcionando.
En resumen:
1- no
2B- no
3- Cualquier escritura/lectura sobre el espacio de memoria va a tener que tener en cuenta el esquema de paginación para poder traducir las direcciones lógicas a físicas :)

Te aclara la duda?
Saludos!
      Lean

**Comment by DanielKesel** [comment]
Gracias por la pronta respuesta.
Todavía tenemos dudas con lo siguiente:
1- ¿Entonces al momento de ejecutar una instrucción (ej MOV_IN) recién ahí sabríamos cuantas paginas vamos a reservar? 
2- Si tuviésemos un archivo de pseudocodigo sin ninguna instrucción MOV ni STDIN etc. Iniciaríamos la estructura de paginación y no haríamos nada con ella?

**Comment by RaniAgus** [comment]
¡Buenas!
1- No, para agregar o quitar entradas en la tabla de páginas del proceso existe la instrucción `RESIZE`
2- Los procesos siempre inician sin páginas y, a menos que haya un `RESIZE`, eso no va a cambiar

Saludos

**Comment by DanielKesel** [comment]
Buenisimo,
Nos queda una duda más y creeríamos que sería la ultima:
En el archivo de pseudocodigo que nos dan en el enunciado de ejemplo tenemos la siguiente secuencia de instrucciones:

> SET AX 1
> SET BX 1
> SET PC 5
> SUM AX BX
> SUB AX BX
> MOV_IN EDX ECX
> MOV_OUT EDX ECX
> RESIZE 128

es decir el MOV_IN y MOV_OUT están antes del RESIZE... Entonces nuestra duda es ¿Como hace el MOV_IN y el MOV_OUT si el programa no tiene paginas hasta el resize?

**Comment by DanielKesel** [comment]
Gracias!! quedo todo clarisimo.
Saludos!
