### ISSUE TITLE
Duda incremento del PC

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3892]
Buenas! quizas llegue medio tarde con esta duda pero mejor tarde que nunca.

Dado este pseudocodigo:

```
0 SET PC 3
1 SET AX 5
2 SET BX 2
3 SUM AX BX
4 SUB AX BX
5 EXIT

```

Una vez realizada el la primera instruccion. La siguiente instruccion a ejecutar debe ser la 3, la 4 o da lo mismo ??
Espero se haya entendido y muchas gracias

**Comment by RaniAgus** [comment]
¡Buenas! `SET PC 3` setea el Program Counter en 3, por lo que la siguiente instrucción a ejecutar debe ser la 3. Sino no habría forma de saltar a la instrucción 0 😅 

Saludos

**Comment by GonTurri** [comment]
tiene muchisimo sentido lo que estas diciendo. Yo hacia la pregunta por el lado de que, suponiendo que sumamos el PC luego del execute, a menos que haya un if o algo por el estilo no funcionario del todo. Entonces puedo acomodar el ++ del pc a gusto para que ande bien?

**Comment by iago64** [comment]
Buenas! cómo va?

Si, pueden acomodar el incremento del PC a gusto, o pueden salir por la solución crota y poner un if para ver si la ultima instrucción fue un SET PC y listo.

Saludos.-

**Comment by GonTurri** [comment]
Muchisimas gracias. Queria que me lo cofirmara alguno de ustedes :)
