### ISSUE TITLE
problema con la funcion obtener_proceso_por_id

### ISSUE THREAD

**Issue by GianLema** [sisoputnfrba/foro#3893]
estamos teniendo problemas con que la sig funcion en memoria encuentre y devuelva un proceso junto con sus instrucciones, filtrandolo por su pid, cuando cpu lo pide en el fetch. Procedo a mostrar el contexto en el que la llamamos a la funcion y varias iteraciones de la funcion misma(copiado de github del ultimo commit, osea que hay cosas que removimos junto con las que agregamos, pero el error en todas es el mismo):
```c
void enviar_instruccion_a_cpu(t_buffer* un_Buffer){
	int pid = extraer_int_buffer(un_Buffer);
	uint32_t pc = extraer_uint32_t_buffer(un_Buffer);
	log_info(log_memoria, "pid es %d y pc es %d", pid, pc);
	int pos = 0;
	char* prox_instruccion;
	t_proceso* proceso = obtener_proceso_por_id(pid);
	//log_info(log_memoria, "%d", list_size(lista_procesos_recibidos));
	log_info(log_memoria, "%d", lista_procesos_recibidos->head->data);
	t_list* aux = malloc(sizeof(proceso->instrucciones)); // CON LIST_CREATE OCURRE EL MISMO PROBLEMA, SEGMENTATION FAULT
	list_add_all(aux,proceso->instrucciones); // problema al iniciar_planificacion
	while(pos != pc){
@@ -67,18 +70,37 @@ void enviar_instruccion_a_cpu(t_buffer* un_Buffer){
	free(aux);
}

/*t_proceso * buscar(t_list lista,int pid){
    while ( lista->head != NULL && lista->head->data->pid != pid){
        lista->head = lista->head->next;
    }
    return lista->head->data;
}*/

bool comparar_pid(void* elemento, int pid_buscado) {
    t_proceso* proceso = (t_proceso*) elemento;
    int pid = pid_buscado;
    return proceso->pid == pid;
} 

t_proceso* obtener_proceso_por_id(int pid){
	t_proceso* proceso_encontrado = malloc(sizeof(t_proceso));
	bool _buscar_el_pid(void* elemento){
t_proceso* obtener_proceso_por_id( int pid){
    t_proceso* un_proceso = malloc(sizeof(t_proceso));
    t_proceso* proceso_encontrado = list_find(lista_procesos_recibidos, (void*) comparar_pid(un_proceso, pid)); 
    return proceso_encontrado ;
}

/*bool _buscar_el_pid(void* elemento, int pid){
    return (((t_proceso*)elemento)->pid == pid);
	}
t_proceso* obtener_proceso_por_id(int pid){
	t_proceso* proceso_encontrado = malloc(sizeof(t_proceso));
	
    proceso_encontrado = list_find(lista_procesos_recibidos, (void*)_buscar_el_pid);
	
    if(proceso_encontrado == NULL){
        log_error(log_memoria, "PID<%d> No encontrado en la lista de procesos", pid);
		free(proceso_encontrado);
    }
    return proceso_encontrado;
}
}*/

```
![image](https://github.com/sisoputnfrba/foro/assets/129530201/3339a38b-51d1-41d7-a0b2-e597106879f2)

![image](https://github.com/sisoputnfrba/foro/assets/129530201/978f3dee-f533-4626-9692-0d727ae03d2a)

![image](https://github.com/sisoputnfrba/foro/assets/129530201/00cfe5a4-6f14-4bf4-a8a0-20fe51c25142)

**Comment by RaniAgus** [comment]
¡Buenas! En primer lugar, les recomiendo formatear el código siguiendo la guía básica de formato con:

\`\`\`c
El código en C
\`\`\`

Porque sino se nos complica un toque leer el código a simple vista. Ahí les edité el issue para que vean cómo queda formateado.

En segundo lugar, y mucho muy importante: **los ayudantes no somos compiladores humanos**, y como humanos también se nos complica entender el código si éste incluye la sintaxis de git diff. Por favor, ayúdennos a ayudarles y muéstrennos solamente la última iteración de su código, con eso ya nos alcanza para poder dar una mano.

En tercer lugar, necesitaríamos saber **cuál** es el error: ¿ocurre al intentar compilar el código? ¿o la función no ejecuta como esperaban? En caso de ser este último, ¿qué esperaba que devuelva y qué les devuelve? Con solo decirnos que "están teniendo problemas" no nos alcanza para entender en qué momento está ocurriendo, y a qué puede deberse.

Dicho esto, ¿podrían, por favor, pasarnos solamente la última versión de la función que está teniendo el problema y contarnos cuál es dicho problema? También nos serviría contar con la estructura de `t_proceso`, para más contexto.

Saludos

**Comment by GianLema** [comment]
hola buenas. gracias por la ayuda, ya lo pudimos solucionar!
