### ISSUE TITLE
Duda io_fs_write

### ISSUE THREAD

**Issue by AAMazzini03** [sisoputnfrba/foro#3894]
Hola que tal! Tenía una duda sobre la función io_fs_write. Quería saber si para poder escribir en un archivo primero tengo que hacer io_fs_truncate y darle el tamaño de lo que quiero escribir o puedo escribir y una vez que termino, el archivo se tiene que truncar solo al tamaño de lo que escribí?
Saludos!

**Comment by RaniAgus** [comment]
¡Buenas! Solamente se debe truncar el archivo ante un llamado a `IO_FS_TRUNCATE`. Saludos

**Comment by AAMazzini03** [comment]
Ok gracias
