### ISSUE TITLE
Problema con STDOUT en Memoria

### ISSUE THREAD

**Issue by 87nsilva** [sisoputnfrba/foro#3896]
Hola, como va? Queríamos saber si el siguiente valor es correcto, porque nos devuelve Segmentation Fault en la linea de get de la función mandar_lista_actualizado

### 📝 Código relevante
``` 
if(opcode == DIRECCION_FISICA_LEER){
			usleep(config.retardo_respuesta);
			int direccion_fisica_leer = recibir_numero(conexion_entradasalida);
			log_debug(logger, "recibo direccion fisica %d",direccion_fisica_leer);
			op_code codigoLeer = recibir_operacion(conexion_entradasalida);
			int bytes_a_leer  = recibir_numero(conexion_entradasalida);
			log_debug(logger, "bytes a leer %d",bytes_a_leer);
			uint32_t* direccion_valor;
			uint32_t valor_leido;
			t_list* valores_leidos = list_create();
			for (int i = direccion_fisica_leer; i < direccion_fisica_leer + bytes_a_leer; i++){
				
				direccion_valor = (uint32_t*)((char*)memoria_usuario + i);
				valor_leido = *direccion_valor;
				log_debug(logger, "añadi a la lista %d",valor_leido);
				list_add(valores_leidos,valor_leido);
			}
			mandar_lista_actualizado(conexion_entradasalida,valores_leidos,RESPUESTA_DIRECCION_FISICA_LEER);
		}


void mandar_lista_actualizado(int socket, t_list* lista_enviable, op_code codigo) {
    t_buffer* buffer = malloc(sizeof(t_buffer));
    buffer->size = list_size(lista_enviable) * sizeof(int);
    buffer->stream = malloc(buffer->size);

    int offset = 0;
    int tamanio = list_size(lista_enviable);
    for (int i = 0; i < tamanio; i++) {
        int elemento = *(int*)list_get(lista_enviable, i);  Acá tenemos el problema
        memcpy(buffer->stream + offset, &elemento, sizeof(int));
        offset += sizeof(int);
    }

    t_paquete* paquete = malloc(sizeof(t_paquete));
    paquete->codigo_operacion = codigo;
    paquete->buffer = buffer;

    void* a_enviar = malloc(buffer->size + sizeof(int) + sizeof(uint32_t) + buffer->size);
    offset = 0;
    memcpy(a_enviar + offset, &(paquete->codigo_operacion), sizeof(int));
    offset += sizeof(int);
    memcpy(a_enviar + offset, &(paquete->buffer->size), sizeof(uint32_t));
    offset += sizeof(uint32_t);
    memcpy(a_enviar + offset, paquete->buffer->stream, paquete->buffer->size);

    send(socket, a_enviar, buffer->size + sizeof(int) + sizeof(uint32_t), 0);

    free(a_enviar);
    free(buffer->stream);
    free(buffer);
    free(paquete);
}
```

Las instrucciones del proceso:
SET AX 2
SET EDX 3
SET BX 1
SET CX 5
SET ECX 2
SUM CX BX
SUB AX BX
SUB CX AX
RESIZE 128
COPY_STRING 8
MOV_IN EDX ECX
IO_STDOUT_WRITE BUENO EDX AX
EXIT

### 💻 Logs
[DEBUG] 19:31:46:587 MEMORIA/(20211:20475): Mande instruccion IO_STDOUT_WRITE BUENO EDX AX
[DEBUG] 19:31:47:498 MEMORIA/(20211:20468): recibi el op code 10
[DEBUG] 19:31:47:508 MEMORIA/(20211:20468): recibo direccion fisica 3
[DEBUG] 19:31:47:550 MEMORIA/(20211:20468): recibi el op code 9
[DEBUG] 19:31:47:551 MEMORIA/(20211:20468): bytes a leer 1
[DEBUG] 19:31:47:551 MEMORIA/(20211:20468): añadi a la lista 1700929590
[DEBUG] 19:31:47:552 MEMORIA/(20211:20468): añadi a la lista 1700929590

**Comment by RaniAgus** [comment]
¡Buenas! `list_add()` espera como segundo parámetro un puntero al dato, y veo que ustedes le están pasando un `int` acá:

```c
uint32_t valor_leido;
valor_leido = *direccion_valor;
list_add(valores_leidos, valor_leido);
```

Por lo que este casteo es incorrecto, ya que lo que guardan ahí no es un puntero, sino un entero:

```c
int elemento = *(int*)list_get(lista_enviable, i);
```

Entonces, si el valor que leyeron es, por ejemplo, `3`, al intentar desreferenciar el puntero van a estar intentando acceder a la dirección `0x3`, de ahí el segmentation fault.

Un fix rápido sería reservar y pasarle a la lista un puntero:
```c
uint32_t* valor_leido = malloc(sizeof valor_leido);
*valor_leido = *direccion_valor;
list_add(valores_leidos, valor_leido);
```

Saludos

**Comment by RaniAgus** [comment]
¡Buenas @87nsilva! ¿Les sirvió la respuesta? Saludos

**Comment by 87nsilva** [comment]
Si! Mil disculpas, me olvidé de contestar. Muchísimas gracias!
