### ISSUE TITLE
Flujo de instrucciones de i/o

### ISSUE THREAD

**Issue by inaaranza** [sisoputnfrba/foro#3897]
Buenas! Me surgieron dudas sobre el flujo de trabajo con las instrucciones de i/o y las maneras de resolver algunos casos.

Usando de ejemplo una instrucción I/O_STDIN_READ: La instruccion le llega a cpu, este le avisa a kernel para realizar la instruccion y luego kernel le avisa a la i/o. El Kernel serializa esta instruccion con el nombre instruccion,
los parametros de la instruccion para luego para mandarla a i/o? Luego la i/o lo deserializa y realiza los chequeos necesarios (como por ejemplo ver si la puede hacer)? La/las direcciones de memoria de la instruccion IO_STDIN_READ,
las envia el kernel serializada? ¿Cuantos bytes podría ocupar? El texto ingresado por el alumno, se guarda directamente
en la memoria? O se lo devuelve a kernel y kernel lo escribe en memoria?

Muchas gracias!

**Comment by f-and** [comment]
Buenas! 
Primero de todo, si se tendría que enviar los parámetros junto con la instrucción, o al menos los parámetros necesarios (Todas las instrucciones tienen el nombre de la interfaz pero no le sirve a la misma recibir su propio nombre).
Segundo, la interfaz se debe ocupar de la conexión respectiva a la Memoria, esto para todos los casos, para esto podes fijarte la arquitectura del sistema. 
Finalmente, para el ejemplo de IO_STDIN_READ (y para el IO_STDOUT_WRITE y otros), los mismos parámetros ya fijan la dirección de escritura/lectura en memoria, y el tamaño a escribir/leer, el Kernel lo va a recibir traducido de una dirección lógica a una física por el CPU y le debe pasar este dato a la interfaz correspondiente.

**Comment by inaaranza** [comment]
Perfecto! Muchas gracias :)

**Comment by inaaranza** [comment]
Perfetco! Muchas gracias:)
