### ISSUE TITLE
Duda con STDOUT

### ISSUE THREAD

**Issue by iskr889** [sisoputnfrba/foro#3898]
Hola queria preguntar si STDOUT se conecta con el kernel o no? por lo que tengo entendido por el enunciado, STDOUT se comunica solo con memoria, pero no deja muy en claro si necesita comunicarse con el kernel y mandarle el nombre de la interfaz al igual que STDIN.

**Comment by RaniAgus** [comment]
¡Buenas! Cito varias partes del enunciado, en las que se detalla cómo interactuar con la interfaz STDOUT.

1. En CPU, en la etapa de fetch, se obtiene la instrucción `IO_STDOUT_WRITE`:

> IO_STDOUT_WRITE (Interfaz, Registro Dirección, Registro Tamaño): Esta instrucción solicita al Kernel que mediante la interfaz seleccionada, se lea desde la posición de memoria indicada por la Dirección Lógica almacenada en el Registro Dirección, un tamaño indicado por el Registro Tamaño y se imprima por pantalla.

2. De ahí, el PCB vuelve al Kernel con el motivo de desalojo, las direcciones físicas a leer y sus tamaños, y en Kernel el manejo es el siguiente:

> Al recibir una petición de I/O de parte de la CPU primero se deberá validar que exista y esté conectada la interfaz solicitada, en caso contrario, se deberá enviar el proceso a EXIT.

Ya, de por sí, esto significa que la interfaz debe estar conectada y con su nombre que la identifica unívocamente

> De cumplirse todos los requisitos anteriores, el Kernel enviará el proceso al estado BLOCKED y a partir de este punto pueden darse 2 situaciones:
> 1. El caso en el que la interfaz de I/O esté libre: En este caso el Kernel deberá solicitar la operación al dispositivo correspondiente. 
> 2. En el caso de que exista algún proceso haciendo uso de la Interfaz de I/O, el proceso que acaba de solicitar la operación de I/O deberá esperar la finalización del anterior antes de poder hacer uso de la misma.

Es decir, es el Kernel el que dispara el evento de leer en Memoria e imprimir por pantalla, dejando al proceso en estado BLOCKED.

3. Dicho módulo, una vez Kernel inicia la operación de I/O, se encarga de leer las direcciones físicas e imprimirlas:

> Las interfaces STDOUT se conectan a memoria para leer el valor que se encuentra en la o las direcciones físicas pedidas y mostrar el resultado por pantalla. La instrucción para realizar esto es: IO_STDOUT_WRITE

Espero que este repaso les haya sido de ayuda.

Saludos

**Comment by ParedesMicaela** [comment]
Buen dia! Yo también estoy un poco mareada con el tema de las interfaces y memoria. Suponiendo que me llega la instrucción IO_STDIN_READ y que tengo que acceder a distintas paginas para escribir. Yo busco en la TLB si tengo las direcciones físicas de esas paginas para no hacer accesos a memoria, se las mando al kernel en el PCB junto con el tamaño a leer de cada una, el kernel le manda esas direcciones y tamaños a la IO y esta ultima le manda una por una las peticiones a memoria?

Si es así, en el caso de que no tenga las páginas en la TLB no voy a estar haciendo un montón de accesos a memoria? Primero para buscar las direcciones y después para mandarla a escribir? Capaz estoy diciendo cualquiera porque me confunde un poco

**Comment by LeandroCarbajales** [comment]
Buenas @ParedesMicaela
Es exactamente como lo describís en el primer párrafo :)

> Si es así, en el caso de que no tenga las páginas en la TLB no voy a estar haciendo un montón de accesos a memoria? 

¿Qué serían "un montón" de accesos a memoria? Por ejemplo si tuvieras que acceder a 3 páginas y ninguna estuviera en TLB, tendrías que hacer 3 accesos a memoria para traducir las 3, es lo esperado :)
Luego la interfaz haría 3 accesos también para leer/escribir, fijate que en este peor caso son 2 accesos por cada página que es igual a como lo vemos en los ejercicios.

@iskr889 Te sirvió la respuesta de @RaniAgus ?

**Comment by ParedesMicaela** [comment]
aaaa buensiimo, sii 2 accesos no es tanto jaja cuando estaba haciendo el issue me parecia mas quilombo, gracias!

**Comment by LeandroCarbajales** [comment]
Genial.
Cierro el issue, cualquier cosa lo vuelven a abrir.
