### ISSUE TITLE
Retardo solicitudes en memoria

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3899]
Buenas, viendo que actualizaron el tema del retardo en memoria nos surgió una duda. Antes cuando ingresábamos en Kernel el comando "INICIAR_PROCESO" la respuesta era instantánea y permitía rápidamente volver a escribir otro comando, ahora como le añadimos el retardo, consola se queda "colgada" ese retardo hasta que memoria le contesta si creo todas las estructuras para ese proceso o si el pseudocódigo pasado es invalido ¿Esto estaría bien o deberíamos manejarlo en otro hilo para que la consola no se quede "colgada" ese breve periodo de tiempo?

**Comment by mefederico** [comment]
Hola buenas! 

Si debería ser otro hilo el encargado de la creación de proceso, la consola únicamente recibe los comandos, no debería quedar colgada en ningún momento.

 Y más conceptualmente es el planificador de largo plazo el que hace la transición de new a ready y si el grado de multiprogramación lo permite recién le pide a memoria crear las estructuras necesarias, para este TP en particular no hay diferencias si lo hacen ni bien llega el proceso a new o recién cuando se va a mover, pero bueno desde lo conceptual se responde mejor la pregunta
 
 Saludos!

**Comment by rood8592** [comment]
Buenas, nos surge un problema con respecto a lo de la creación de procesos. Nosotros pensamos en crear un hilo por cada crear proceso en kernel pero, por como lo habiamos hecho, a la hora de crear un proceso kernel se queda esperando una respuesta con un recv() de si el archivo es valido o no lo es: si es invalido se descarta el pcb y se recupera su pid, y si es valido es la señal que nos da memoria de que ya creo todas las estructuras. El problema es que si yo instancia multiples hilos, habrá multiples recv() ¿Qué me garantiza que cada recv() reciba el resultado del pid que le corresponda? Me refiero a que por ahí el pid2 se creo exitosamente pero su recv() recibe el resultado del pid3 que fue error y termina descartando nuestro pid2.
Igualmente esto del archivo invalido o que memoria me envie un resultado lo hicimos nosotros, no lo pedía la consigna como tal así que, de ultima, lo podemos sacar, aunque, en realidad, lo habíamos hecho para esperar a que memoria nos resppnda un ok, lo cual significaría que ya están todas las estructuras creadas asociadas a ese proceso y lo podríamos pasar a ready.

**Comment by rood8592** [comment]
Buenas, se nos ocurrió meterlo en un único hilo, el que se encarga del pasaje de new a ready asi maneja un recv a la vez pero me surge otra duda ¿Qué pasa si al finalizar un proceso queremos recibir de memoria también una confirmación o algo de que ya elimino todo, también habria un recv en el hilo que se encarga de eso? No podría haber conflictos habiendo 2 recvs en dos hilos distintos con el mismo socket (uno de crear y otro de finalizar proceso), podría pasar algo parecido a lo que mencione en mi comentario anterior?

**Comment by iago64** [comment]
Buenas! Cómo va?

Si tienen multiples recv() pueden tener una condición de carrera muy complicada de resolver, les recomiendo de cara a las pruebas que corran de a 1 las creaciones, total no deberían tardar mucho en crear los procesos.

Saludos.-

**Comment by rood8592** [comment]
Muchas gracias por la pronta respuesta. Entiendo que eso solucionaría lo de los múltiples hilos con un recv() del mismo socket que se nos habia ocurrido para crear los procesos, me surgen varias dudas:
1) Si yo atiendo de a uno las creaciones lo que va pasar es que la transición a ready va depender del tiempo que tarde la memoria en responderme, si le ponemos un retardo alto, el tiempo que tarda en hacer la transición va ser alto ¿Habría algún problema con esto?
2) Yo tengo por un lado un hilo que corre de a uno las creaciones con un recv(fd_memoria) pero por otro lado hay otro hilo que finaliza los procesos y también hace un recv(fd_memoria), creo que se generaría un posible problema ahí también ¿Es necesario éste ultimo recv() en el finalizar proceso, o solo nos encargamos de hacer el send para que memoria nos libere las estructuras de x proceso y no nos interesa recibir ningún ok ni nada? O sea hacemos el send únicamente, no como cuando creamos un proceso que tenemos un send seguido de un recv.

**Comment by mefederico** [comment]
Hola! 

1. Lo tenemos contemplado obvio, es parte del pasaje.
2. Podrías usar una solución como la que deben tener para que se conecten multiplés IO a Kernel, en otras palabras, [multiplexar](https://docs.utnso.com.ar/guias/linux/sockets#multiplexando-ando) o cualquier solución imaginativa como la que propones, aunque siempre está bueno recibir un OK a los mensajes y no asumir que las cosas andan bien. Al alcance del TP es suficiente

Saludos!

**Comment by rood8592** [comment]
Perfecto, gracias. Me surgió otra duda ahora con lo de multiplexación, en memoria tenemos un único hilo que maneja las peticiones que vienen de kernel (crear y finalizar proceso) y las va atender de a uno y en orden indeterminado por el tema de que los sends no llegan en orden. Por lo que mencionas supongo que al alcance del tp no haría falta multiplexarlo pero por las dudas repregunto.

**Comment by iago64** [comment]
Buenas! Cómo va?

En la memoria con un solo hilo alcanza para las peticiones del kernel.

Saludos.-
