### ISSUE TITLE
Log obligatorio CPU, STDOUT y STDIN

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3900]
Buenas,
Teníamos varias dudas, una es con respecto a un log obligatorio y las otras con respecto a las interfaces:

1) ¿El log obligatorio en CPU de leer y escribir, se busca que el log muestre el dato completo, no? O sea no los fragmentos. Por ej, si yo hago una escritura del numero 3456, quiero ver ese numero en el log y si quiero leerlo y este está dividido en varias paginas, primero recupero todos los fragmentos para hacer el log con el número reconstruido.
2) ¿Tanto STDIN y STDOUT trabajaran con strings? O sea su fin es guardar texto en memoria y leer texto desde memoria. Pregunto más que nada porque, por ej, la interfaz que lee pide mostrar el dato en pantalla. Supongo que ahí debemos reconstruir el dato antes de mostrarlo, agregarle el \0 que no guardamos en memoria, y debemos imprimirlo como string en pantalla, osea con un %s

**Comment by mefederico** [comment]
Hola buenas!

1. Es por cada lectura que hagan en memoria por eso se loggea también la dirección física, en tu ejemplo nos interesa leer de que parte leyeron cada pedazo. Si el 34 estaba en el marco 0 offset 2 y el 56 estaba en el marco 10 offset 0, suponiendo páginas de 4 bytes para este ejemplo.

2. Si, manejan bytes mostrables por pantalla en el caso de STDOUT (aka texto) y en el caso de STDIN el texto es lo que te deja escribir la consola.

Saludos!

**Comment by rood8592** [comment]
Buenas, gracias. Con respecto al punto 1 aplica lo mismo para escritura?

**Comment by iago64** [comment]
Buenas! Cómo va?

Si, aplica.

Saludos.-

**Comment by rood8592** [comment]
Perfecto, gracias.

**Comment by rood8592** [comment]
Buenas, estamos haciendo lo del log obligatorio en cpu de leer y escribir y nos pasa algo raro con el siguiente pseudocodigo:

```
SET EAX 3
SET EBX 56458
SET ECX 10
SET AX 3
RESIZE 25
MOV_OUT EAX EBX
MOV_IN ECX AX
EXIT
```

Logs en PC=5 en CPU:
```
[INFO] 12:31:02:624 MODULO CPU-OBL/(6706:6706): Fetch Instruccion: "PID: 0 - FETCH - Program Counter: 5".
[INFO] 12:31:03:125 MODULO CPU-OBL/(6706:6706): Obtener Marco: "PID: 0 - OBTENER MARCO - Página: 1 - Marco: 0".
[INFO] 12:31:03:625 MODULO CPU-OBL/(6706:6706): Obtener Marco: "PID: 0 - OBTENER MARCO - Página: 2 - Marco: 1".
[INFO] 12:31:03:625 MODULO CPU-OBL/(6706:6706): Escritura Memoria: "PID: 0 - Acción: ESCRIBIR - Dirección Física: 3 - Valor: -253192054".
[INFO] 12:31:04:126 MODULO CPU-OBL/(6706:6706): Escritura Memoria: "PID: 0 - Acción: ESCRIBIR - Dirección Física: 4 - Valor: -268435236".
[INFO] 12:31:04:632 MODULO CPU-OBL/(6706:6706): Instruccion Ejecutada: "PID: 0 - Ejecutando: MOV_OUT EAX EBX".
```
Cuando logueabamos el dato entero no sucedía esto, para lectura tampoco ya que lo reconstruíamos en su totalidad antes de mostrarlo ¿Cómo se espera que se loguee el número 56458 en este ejemplo?

**Comment by iago64** [comment]
Buenas! Cómo va?

"El problema" que tienen es que el valor que estan pasando en ese log esta partido y por eso se ve fiero, ahi los números nosotros los tenemos contemplados, pero si uds quieren para estar mas tranquilos, pueden agregarse un log extra que diga algo asi como el valor escrito es NNNN pueden hacerlo.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Siguiendo con lo que decía Dami sobre pasarle valores "partidos" a un log, ahí hice una prueba de cómo se ven ver ambos valores almacenados en la memoria:

```c
#include <stdio.h>
#include <string.h>
#include <commons/memory.h>

int main() {
        int expected = 56458;
        int got = -253192054;

        mem_hexdump(&expected, 4);
        mem_hexdump(&got, 4);

        return 0;
}
```

Y lo que me imprimió fue lo siguiente:

```
$ gcc main.c -lcommons
$ ./a.out

0x00000000: 8a dc 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|

0x00000000: 8a 98 e8 f0 00 00 00 00  00 00 00 00 00 00 00 00  |................|
```

A partir de acá podemos notar un par de cosas:

1) Parecen estar funcionando bien el `MOV_OUT` y el `MOV_IN`:
- En el `MOV_OUT` parece ser que se guarda en memoria el hexa `8a dc 00 00`, el cual viene del registro `EAX`.
- En el `MOV_IN` se está leyendo el `8a` y guardándose en `AX`. Tengan en cuenta que solo se va a copiar el primer byte, ya que el registro `AX` mide 1 byte.

2) Al imprimir el valor, parece ser que está leyendo más bytes de lo que debería: en lugar de leer solo `8a`, se está leyendo la memoria que está contigua a eso, de ahí sale el valor `8a 98 e8 f0`.

Entonces, ¿cómo lo podemos resolver? Usando un formato distinto según la instrucción que ejecutemos, y el registro que estemos usando:

- Si es un registro de 1 byte, mandamos a imprimir un `uint8_t`:

```c
uint8_t valor = ...;
log_info(logger, "Valor leido: %d", valor);
```

- Si es un registro de 4 bytes, mandamos a imprimir un `uint32_t`:

```c
uint32_t valor = ...;
log_info(logger, "Valor leido: %d", valor);
```

- Si la instrucción es COPY_STRING, reconstruimos el `char*` y lo imprimimos:

```c
uint32_t tamanio = ...;
char *valor = ...;

log_info(logger, "Valor leido: %.*s", tamanio, valor);
```

Saludos

**Comment by RaniAgus** [comment]
PD: Tanto para STDOUT como STDIN la CPU no va a ser quien haga la lectura y escritura a Memoria, sino que las interfaces lo harán, así que no tendría por qué aparecer este log obligatorio.

**Comment by rood8592** [comment]
Buenas, gracias Agus y Dami. Creo que descubrimos el error y es que estabamos creando un int* al que le reservabamos a veces 1 byte unicamente :skull:.

Ahora creemos que funciona correctamente, corrimos el siguiente pseudocódigo (del ejemplo que dio agus) con paginas de 4bytes. La dirección lógica va ser la 3 (valor registro DX) con lo cual el dato se va dividir en 1byte en la primera pagina y los 3bytes restantes en la 2da. Guardaremos primero el valor de EBX en esa dirección lógica, para después recuperar el primer byte y guardarlo en AX.

```
SET EBX 56458
SET DX 3
RESIZE 25
MOV_OUT DX EBX
MOV_IN AX DX
EXIT
```

Logs obtenidos:

```
[INFO] 19:17:00:150 MODULO CPU-OBL/(3474:3474): Fetch Instruccion: "PID: 0 - FETCH - Program Counter: 3".
[INFO] 19:17:00:672 MODULO CPU-OBL/(3474:3474): Obtener Marco: "PID: 0 - OBTENER MARCO - Página: 1 - Marco: 0".
[INFO] 19:17:01:177 MODULO CPU-OBL/(3474:3474): Obtener Marco: "PID: 0 - OBTENER MARCO - Página: 2 - Marco: 1".
[INFO] 19:17:01:177 MODULO CPU-OBL/(3474:3474): Escritura Memoria: "PID: 0 - Acción: ESCRIBIR - Dirección Física: 3 - Valor: 138".
[INFO] 19:17:01:678 MODULO CPU-OBL/(3474:3474): Escritura Memoria: "PID: 0 - Acción: ESCRIBIR - Dirección Física: 4 - Valor: 220".
[INFO] 19:17:02:187 MODULO CPU-OBL/(3474:3474): Instruccion Ejecutada: "PID: 0 - Ejecutando: MOV_OUT DX EBX".
[INFO] 19:17:02:717 MODULO CPU-OBL/(3474:3474): Fetch Instruccion: "PID: 0 - FETCH - Program Counter: 4".
[INFO] 19:17:03:231 MODULO CPU-OBL/(3474:3474): Obtener Marco: "PID: 0 - OBTENER MARCO - Página: 1 - Marco: 0".
[INFO] 19:17:03:754 MODULO CPU-OBL/(3474:3474): Lectura Memoria: "PID: 0 - Acción: LEER - Dirección Física: 3 - Valor: 138".
[INFO] 19:17:03:754 MODULO CPU-OBL/(3474:3474): Instruccion Ejecutada: "PID: 0 - Ejecutando: MOV_IN AX DX".

```

El valor que se guarda es ```8a dc 00 00``` con lo cual los logs tienen sentido, 8a es 138 y dc es 220. Luego al leerlo, se lee solo el primer byte 8a y coincide el valor, el 138 y se lo guarda en AX ¿Esto es correcto?

Una última pregunta, los logs de "ESCRIBIR" o "LEER", en este caso el de escritura son 2, porque ocupa 2 paginas y tengo 2 direcciones físicas. Si un dato que quiero leer o escribir ocupa 3 paginas, serían 3 logs de este tipo, no? y así sucesivamente.

**Comment by iago64** [comment]
Buenas! Cómo va?

Efectivamente si tienen sucesivas lecturas / escrituras de mas de 1 página deberían tener los correspondientes logs.
Y si, lo que te pasa con lo de `8a dc 00 00` es justamente la idea, que se traigan el primer byte de la memoria.

Saludos.,-

**Comment by rood8592** [comment]
Perfecto gracias!!
