### ISSUE TITLE
Duda prueba planificación

### ISSUE THREAD

**Issue by ManuelGarciaF** [sisoputnfrba/foro#3901]
Buenas, tenia una duda con respecto a la prueba de planificación, donde dice en los resultados esperados de RR:

> En RR finalizan PLANI_1, PLANI_3 y luego PLANI_2, **el cual es desalojado 2 veces por fin de quantum**. PLANI_4 continúa ejecutando. 

PLANI_2 es:
```
SET AX 1
IO_GEN_SLEEP SLP1 1
SET BX 1
IO_GEN_SLEEP SLP1 1
SET CX 1
IO_GEN_SLEEP SLP1 1
SET DX 1
IO_GEN_SLEEP SLP1 1
SET EAX 1
IO_GEN_SLEEP SLP1 1
SET EBX 1
IO_GEN_SLEEP SLP1 1
SET ECX 1
IO_GEN_SLEEP SLP1 1
SET EDX 1
EXIT
```
Y tenemos un Quantum de 2750 con 1000 de retardo, por lo que PLANI_2 nunca es desalojado por fin de quantum, siempre llega a hacer IO. ¿Esta bien esto?

**Comment by RaniAgus** [comment]
¡Buenas! Fue un typo, `PLANI_3` es el que es desalojado 2 veces por fin de quantum. Gracias por notarlo, ya fue corregido. Saludos

**Comment by ManuelGarciaF** [comment]
Ah perfecto, gracias
