### ISSUE TITLE
Detener_planificación, prioridad sem_wait()

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3902]
Buenos días,
Tenía una duda con respecto a como encaramos el "DETENER_PLANIFICACION", básicamente creamos un semáforo nuevo por cada cola (new, ready, exec, blocked) inicializados en 0, a los cuales se les hace post cuando se ingresa "INICIAR_PLANIFICACIÓN". En la práctica, al menos hasta ahora, funciona correctamente pero me surgió una duda viendo el código.

Iniciar planificación:
```
void iniciar_planificacion(){
    if(!planificacion_iniciada){
    //printf("iniciar_planificacion \n");
    planificacion_iniciada = true;
    
    sem_post(&planificacion_new_iniciada);
    sem_post(&planificacion_ready_iniciada);
    sem_post(&planificacion_exec_iniciada);
    sem_post(&planificacion_blocked_iniciada);
    log_info(logger, "Planificación %s iniciada", config_get_string_value(config, "ALGORITMO_PLANIFICACION"));
    }
}
```

Detener planificacion:
```
void detener_planificacion(){
    //printf("detener_planificador \n");
    if(planificacion_iniciada)
    {
        planificacion_iniciada = false;
        
        pthread_t detener_new, detener_ready, detener_exec, detener_blocked;
        pthread_create(&detener_new,NULL,(void*) detener_cola_new,NULL);
        pthread_create(&detener_ready,NULL,(void*) detener_cola_ready,NULL);
        pthread_create(&detener_exec,NULL,(void*) detener_cola_exec,NULL);
        pthread_create(&detener_blocked,NULL,(void*) detener_cola_blocked,NULL);
        pthread_detach(detener_new);
        pthread_detach(detener_ready);
        pthread_detach(detener_exec);
        pthread_detach(detener_blocked);
        
        
        log_info(logger, "Se detuvo la planificacion");
    }else
    {
        log_info(logger,"la plani esta pausada ya");
    }
    
}
void detener_cola_new(void* arg)
{
    sem_wait(&planificacion_new_iniciada);
}
void detener_cola_ready(void* arg)
{
    sem_wait(&planificacion_ready_iniciada);
}
void detener_cola_exec(void* arg)
{
    sem_wait(&planificacion_exec_iniciada);
}
void detener_cola_blocked(void* arg)
{
    sem_wait(&planificacion_blocked_iniciada);
}
```
Función del hilo que maneja la cola de new:
```
void atender_estados_new(){

    
    while(1){

        sem_wait(&proceso_en_cola_new);
        /*if(!planificacion_iniciada){
            break;
        }*/
        sem_wait(&planificacion_new_iniciada);
        sem_wait(&grado_de_multiprogramacion);
        t_pcb* pcb_auxiliar = squeue_pop(lista_procesos_new);
        cambiar_a_ready(pcb_auxiliar);
        sem_post(&proceso_en_cola_ready);
        sem_post(&planificacion_new_iniciada);
        //Una vez que pasa los estados de new a ready
        log_info(logger, "PID: %d - Estado Anterior: NEW - Estado Actual: READY", pcb_auxiliar->pid);

    }
}
```

Cuando ingresamos el comando de "DETENER_PLANIFICACION" se crean 4 hilos, una de la razones para crear hilos es que la consola no se quede colgada y la razón por la que se crean 4 hilos en vez de 1 es para que los waits no tengan que reallizarse en un orden determinado, pudiendo un wait bloquear a la realización del siguiente, por ello estan en hilos independientes.
Luego, para poner un ejemplo, en la cola de new, al principio chequeamos este semaforo haciendole wait y al final le hacemos post para que este hilo no detenga la planificacion por su cuenta y se "bloquee a si mismo". Mi duda es:

1- Si yo lanzo el comando cuando el hilo de "atender_estado_new" esta en cambiar_a_ready por ejemplo. Ya tengo un wait esperando en un hilo para parar la plani por el comando que escribí, cuando se llega al post en la funcion atender_estado_new ¿Algo me asegura que el wait lo hará el hilo creado para detener la plani y NO lo hará el que está al principio de mi funcion "atender_estado_new" que está al principio de mi while(1)? ¿O no es determinístico y podría llegar a pasar que el wait sea realizado por el "atender_estado_new" y no por el hilo creado para detener la plani lo cual implicaría que se realizaría una iteración más, un pasaje extra entre new-ready? ¿Podría pasar incluso que realice varía iteraciones más ignorando mi otro hilo en donde solo hay un wait de dicho semáforo (función "void detener_cola_new")?

2- De paso pregunto si en el TP la planificación debe venir iniciada por defecto.

**Comment by RaniAgus** [comment]
¡Buenas!

1- Al ejecutar `sem_post()` se despierta uno de los hilos que estén en `sem_wait()` de ese mismo semáforo en el momento, por lo que dudo muchísimo que este primer hilo que hizo `sem_post()` llegue a ejecutar `sem_wait()` a tiempo como para entrar en la fila y "colarse", así que lo veo bien. De todas formas, pueden probarlo.

2- Como prefieran, en cualquier caso la iniciaremos o la detendremos dependiendo de lo que requiera la prueba.

Saludos

**Comment by RaniAgus** [comment]
¡Buenas @rood8592! ¿Les sirvió la respuesta? Saludos

**Comment by rood8592** [comment]
Sisi, gracias @RaniAgus !

**Comment by RaniAgus** [comment]
¡Buenísimo! Recuerden que si la duda ya fue resuelta pueden cerrar el issue 👮🏻‍♂️
