### ISSUE TITLE
Sobre el config del modulo IO

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3904]
Buenas! ahora viendo las pruebas me entra un toque la duda respecto al config de las interfaces. Nosotros por ejemplo haciamos que siempre se conecte a memoria sin importar el tipo de interfaz. Pero ahora pensandolo, ustedes podrian pasarnos un config de interfaz generica sin puerto memoria y que esta no realize la conexion??

Entonces habria que, segun el tipo, recien ahi hacer las conexiones y todo el resto? o podemos asumir que todos los campos del config van a al menos van a aparecer, por ejemplo si yo hago `config_has_property(2)` me devuelve true, porque te tira segfault alguna de las funciones del `config.h` si no tiene seteada la property un archivo. 

Muchas gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Las configuraciones de IP y Puerto no se las damos en los archivos de config del documento de pruebas porque dependen de la pc, pero uds pueden agregarlas sin problemas.

Saludos.-

**Comment by GonTurri** [comment]
perdon, no me explique bien. mi pregunta es si nostros podriamos tener un config de este estilo
```
TIPO_INTERFAZ=GENERICA
TIEMPO_UNIDAD_TRABAJO=50
IP_KERNEL=127.0.0.1
PUERTO_KERNEL=8888
IP_MEMORIA=127.0.0.1
PUERTO_MEMORIA=9999
```

y la otra pregunta es si la interfaz generica debe conectarse o no a memoria

**Comment by iago64** [comment]
Buenas! Cómo va?

Pueden tener los archivos de config completos si quieren aunque tengan datos basura, nosotros en el doc de pruebas, que de hecho ya tienen un doc de pruebas preliminares, le vamos a poner los datos que nos interesan, el resto com IPs o demas configs que no hacen a la prueba, pueden ponerle los valores que quieran.

Por otro lado, si la config genérica se conecta a memoria no nos cambia en lo mas minimo, mientras haga el sleep como esta definido en la especificación de la interfaz, somos todos felices.

Saludos.-
