### ISSUE TITLE
Apagar Interface

### ISSUE THREAD

**Issue by AGanem** [sisoputnfrba/foro#3905]
Buenas!
Cómo va?

Quería saber como se terminan o se apagan las interfaces. Actualmente las tenemos conectadas al módulo que corresponda y cuando se pierde la conexión, nos tira un segmentatión fault, lo cual no nos da tiempo a liberar la memoria alocada. 

Se me ocurre que podemos agregar un comando que sea lea por consola, para poder terminar correctamente una interface. Es esto correcto? O deberíamos reaccionar al evento de una perdida de conexión para liberar todo?

Saludos.

**Comment by RaniAgus** [comment]
¡Buenas! Las interfaces se desconectan finalizando el proceso con Ctrl+C.

Para manejar las desconexiones pueden validar el valor de retorno de algún `send()` o `recv()` contra dicha interfaz: si retorna una cantidad de bytes menor a la que esperaban enviar o recibir, muy probablemente se deba a una desconexión.

Saludos

**Comment by ManuelGarciaF** [comment]
Una duda respecto a esto, es necesario que la interfaz se marque como desconectada inmediatamente cuando se corta el proceso? Actualmente lo tengo implementado checkeando solamente cuando algun proceso intenta hacer IO contra esa interfaz, asi que si haces PROCESO_ESTADO sigue apareciendo hasta que alguien intente usarla, esta mal?

**Comment by RaniAgus** [comment]
¡Buenas @ManuelGarciaF! Seré breve (?

> es necesario que la interfaz se marque como desconectada inmediatamente cuando se corta el proceso?

No es necesario

> Actualmente lo tengo implementado checkeando solamente cuando algun proceso intenta hacer IO contra esa interfaz, esta mal?

Está bien

> si haces PROCESO_ESTADO sigue apareciendo hasta que alguien intente usarla

Al ingresar el comando `PROCESO_ESTADO` deberías ver el estado de los procesos, no de las interfaces conectadas

Saludos

**Comment by ManuelGarciaF** [comment]
Ah perfecto gracias, con lo de PROCESO_ESTADO me referia a que aparece la cola de bloqueados de esa interfaz.

**Comment by RaniAgus** [comment]
¡Buenas @AGanem! ¿Les sirvió la respuesta? Saludos

**Comment by AGanem** [comment]
En mi caso, si. Muchas gracias.

**Comment by RaniAgus** [comment]
¡Buenísimo! Recuerden que si la duda ya fue resuelta pueden cerrar el issue 👮🏻‍♂️
