### ISSUE TITLE
Finalizar proceso bloqueado

### ISSUE THREAD

**Issue by ManuRodri01** [sisoputnfrba/foro#3906]
Buenas, tengo un par de dudas sobre que hacer bien al finalizar un proceso bloqueado.

1) Al finalizar un proceso, este devuelve las instancias de los recursos que todavía no había devuelto; si las instancias son <=0, entonces desbloquea un proceso. Ahora, imaginemos que tenemos P1 y P2 bloqueados por RA, y por lo tanto las instancias = -2. Si ahora finalizamos P2, le devuelve una instancia a RA y como las instancias <= 0 desbloquea al P1. Pero como P2 esta siendo finalizado también lo tiene que sacar de la cola de bloqueados, entonces quedaría RA sin procesos bloqueados pero con las instancias = -1.
Se me ocurren dos soluciones:
1.1) Sumar 2 a las instancias del recurso, una por el que se desbloqueo y otra por el finalizado.
1.2) Sumar 1 instancia como se hace normalmente, y hacemos que el proceso que se "desbloquea" es el proceso que se esta finalizando.

2) Estaba viendo el issue #3885 y vi que decían que si el proceso sale del CPU por un wait o por un signal hay que dejarlo hacer eso y finalizarlo cuando sea conveniente. Nosotros lo tenemos implementado de que finalizar_proceso tiene la máxima prioridad posible y si el proceso que sale de la CPU es el que se tiene que finalizar, no lo deja hacer nada; lo finaliza directamente. Esta mal implementado como lo hicimos nosotros?

Saludos y perdon por el issue tan largo

**Comment by f-and** [comment]
Buenas Manu
1. Fijate que hay un error en ese ejemplo, ya que si tanto P1 como P2 están bloqueados, ninguno tendría un recurso para dar. Ambos estarían bloqueados en un Wait, por lo que, o no hay instancias del recurso (empieza con instancia = 0), o hay otro proceso con la o las instancias del recurso. En cambio, si P2 tuviera el recurso RA y P1 estaría bloqueado por el mismo, la cantidad de instancias sería -1 (considerando que solo hay una instancia de RA), por lo que cuando termina P2, se le daría la instancia a P1 y la cantidad de instancias quedaría en 0, hasta que P1 haga Signal o se termine.
2. El caso que listas es un caso muy borde que no vamos a revisar mucho, podes fijarte en las pruebas que no se da un caso así, la recomendación que tira Fede más que nada es para que les ayude en la implementación, pero si ustedes ya lo tienen implementado de otra manera no se preocupen al respecto.

**Comment by ManuRodri01** [comment]
Te re-pregunto para ver si esta vez me queda mas claro. 
En el issue #3607 dice que al finalizar un proceso bloqueado por un wait se le hace un ++ a ese recurso. Entonces, lo que se debería hacer es hacerle un ++ al recurso que te tenia bloqueado y retirar el proceso de la cola de bloqueados; sin desbloquear ningún proceso de este recurso. Después, devolvemos todas las instancias de los recursos que había tomado sin bloquearse y se desbloquean procesos en caso de que corresponda.

Así estaría bien o hay algo mal?

**Comment by f-and** [comment]
Ahí no habría nada mal, pero no es como la situación original, se le hace un ++ al recurso, porque deja de haber un proceso esperando esa instancia, pero a su vez este ++ no representa una instancia "real" del recurso, por lo que no se debería desbloquear ningún proceso tal como mencionas. Y después la parte de liberar recursos es correcta.

**Comment by ManuRodri01** [comment]
Listo, ahora si; todo re claro. Muchas gracias
