### ISSUE TITLE
Duda dialFS

### ISSUE THREAD

**Issue by EstebanHurtado0** [sisoputnfrba/foro#3907]
Buenas, al momento de crearse los archivos del FS, siempre se crearan en 0 y con 1 bloque de memoria y después modificaríamos su tamaño, o puede darse el caso de crearse ya asignándole el tamaño de BLOCK_SIZE * BLOCK_COUNT?

###📔 Citas del enunciado/videos
Creación de archivos
Al momento de crearse un archivo, va a comenzar ocupando un bloque del FS aunque su tamaño sea 0 y luego el mismo se podrá extender o disminuir por medio de de la función IO_FS_TRUNCATE.

**Comment by RaniAgus** [comment]
¡Buenas! La instrucción para crear un archivo es la siguiente:

> **IO_FS_CREATE** (Interfaz, Nombre Archivo): Esta instrucción solicita al Kernel que mediante la interfaz seleccionada, se cree un archivo en el FS montado en dicha interfaz.

No tiene ningún parámetro para crearlo con un tamaño específico, por lo que arrancan con tamaño 0.

Saludos

**Comment by EstebanHurtado0** [comment]
Gracias, ya entendí, tenia un error de concepto. Cierro el issue!
