### ISSUE TITLE
Duda sobre el manejo del quantum

### ISSUE THREAD

**Issue by GabrielBorre** [sisoputnfrba/foro#3908]
Buenas tardes! Como están? Nos gustaría hacer una consulta sobre el manejo del quantum, dado que estuvimos mucho tiempo pensando e investigando en el foro, pero lamentablemente no encontramos ninguna respuesta que nos ayude a terminar de resolver el problema.

Nosotros pensamos que el quantum de un proceso debe ser controlado desde el lado del kernel, utilizando un hilo que ejecute las siguientes líneas:
```
void* manejo_de_quantum(void* args){
    const char* mensaje="FIN QUANTUM";
    int quantum=config_get_int_value("kernel.config","QUANTUM");
    usleep(quantum);
    send(conexionCPUInterrupt,mensaje, strlen(mensaje)+1,0);
    return NULL;

}
```

El problema que tiene esta estrategia es que si, por ejemplo, el quantum= 5,  hay un proceso que  dura  1 (una) unidad de tiempo en la CPU y además existe otro proceso que va a durar 5 unidades de tiempo en CPU, este útlimo proceso se desalojaría por fin de quantum cuando haya finalizado su cuarta unidad de tiempo en CPU. Esto sería incorrecto, dado que debería ejecutar hasta que se agote su quantum (5 unidades de tiempo, según el ejemplo). 

Pensábamos resolverlo con semáforos para garantizar algún tipo de sincronización entre procesos, pero nos dimos cuenta de que la funcion usleep(int n) va a esperar siempre una cantidad "n" de milisegundos, independientemente de los semáforos que utilicemos.

Si nos pudieran dar una pista, vamos a estar muy agradecidos.

Desde ya, muchísimas gracias!

**Comment by RaniAgus** [comment]
¡Buenas! Para resolverlo probablemente les sirva esta respuesta de Dami en: https://github.com/sisoputnfrba/foro/issues/3617#issuecomment-2081285298 Saludos

**Comment by GabrielBorre** [comment]
Buenas, Agus! Muchisimas gracias por tu respuesta! Y disculpas por no haber leido ese issue! Saludos

**Comment by RaniAgus** [comment]
¡No hay de qué! Recuerden que si la duda ya fue resuelta pueden cerrar el issue 👮🏻‍♂️
