### ISSUE TITLE
Error en enunciado - Path inncesario en memoria

### ISSUE THREAD

**Issue by diegohcanetti** [sisoputnfrba/foro#3909]
Revisando el enunciado recién me doy cuenta que nunca se utiliza este path mencionado en el config
<html><body>
<div dir="ltr" style="margin-left:0pt;" align="center" id="docs-internal-guid-49e25b7b-7fff-5d04-4c90-c223ab448b47">
PATH_INSTRUCCIONES | String | Carpeta donde se encuentran los archivos de pseudocódigo.

</div>
</body>
</html>

**Comment by f-and** [comment]
Buenas Diego! Ese Path se debería usar, porque de no ser así, de donde se leerían los archivos?

**Comment by diegohcanetti** [comment]
Desde el path que nos manda el proceso al hacer INICIAR_PROCESO

**Comment by f-and** [comment]
Si, pero, si te manda /scripts-memoria/IO_A por ejemplo, lo vas a leer directamente? (osea /script-memoria/IO_A que no seria ideal que exista para Linux), o desde la ubicación relativa desde donde ejecutaste la memoria? (seguramente /home/utnso/tp-equipo/memoria/bin/ que no tendría la carpeta correcta seguramente)
Para justamente solucionar estos dos casos, se les da el PATH_INSTRUCCIONES para que tengan una dirección fija de donde buscar los archivos.

**Comment by GonTurri** [comment]
Buenas! @f-and me sumo a esta duda con este último comentario que hiciste. Nosotros vamos a levantar a los módulos parados en la carpeta bin o en la carpeta padre ya sea kernel memoria etc.
Depende ahí te pregunto, si hay  que usar rutas absolutas o relativas para abrir los distintos archivos?

**Comment by iago64** [comment]
Buenas! Cómo va?

Les damos la idea de las rutas absolutas para que no tengan problemas, si quieren usar rutas relativas es decisión del grupo pero recuerden que tienen que configurar todo el ambiente para las pruebas en 10 minutos, si empiezan con problemas por las rutas relativas se les pueden pasar volando los 10 minutos.

Saludos.-

**Comment by GonTurri** [comment]
Gracias! Me pongo a leer los docs ya mismo :) muy amable

**Comment by f-and** [comment]
Aprovecho y dejo rápido por acá la [guía de rutas](https://docs.utnso.com.ar/guias/consola/rutas) de la materia así lo tienen a mano!

**Comment by diegohcanetti** [comment]
Aaa no lo tomabamos en cuenta, muchas gracias
