### ISSUE TITLE
Dudas conceptuales sobre paginación. Tabla de páginas y marcos de memoria

### ISSUE THREAD

**Issue by tiagoclur** [sisoputnfrba/foro#3911]
Hola, ¿cómo están? Tengo un par de dudas conceptuales conforme al manejo de la memoria de usuario y paginación. Después de leer bastante llegué a algunas conclusiones pero me terminaron quedando algunas preguntas:
Entendí que cada proceso tiene su propia tabla de páginas, en donde se especifica cada página que contiene el proceso y en que marco de la memoria está ubicado. Ahora, ¿cómo represento la ubicación de la página en el marco? ¿Hacemos un bimap? Los marcos los cree como una lista con x cantidad de elementos vacíos (según el tamaño de la página y de la memoria). ¿Cómo colocamos la página dentro de los marcos? 
También según leí en el foro, la tabla de páginas de un proceso apenas creado es vacía hasta que CPU hace un resize, ¿eso significa que la creación de un proceso no puede tener influencia sobre los marcos hasta que CPU mande el resize?

**Comment by tiagoclur** [comment]
Hola, la memoria principal es un espacio contiguo dado por un malloc con el tamaño obtenido de la configuración. Con frames me refería a la lista representativa del bitarray en el que están representados todos los marcos, junto a un bool que validan su ocupación o no. Ahora, para eventualmente asignar la cantidad de bits de un proceso a la memoria, lo tenemos que hacer asignándoselo a la memoria principal según la dirección física requerida, ¿no? O sea, calculamos la página que se le tiene que asignar y con ello, el offset, y ahí se colocaría en la memoria principal.

**Comment by mefederico** [comment]
Hola, 

   No te sigo en 

> lista representativa del bitarray en el que están representados todos los marcos

Podrías pegar como tienen definida la estructura?

Las paginas se asignan al momento de hacer un resize y no al momento de escribir o leer, siempre antes de operaciones de lectura o escritura van a tener al menos un resize como pueden chequearlo en las [pruebas pre-eliminares](https://www.utnso.com.ar/1c2024-pruebas-preliminares-y-cambios-de-grupos/) 

Por otro lado te dejo un issue donde se explica como se hace la escritura https://github.com/sisoputnfrba/foro/issues/3887#issuecomment-2159564592

Espero te sirva,
Saludos

**Comment by tiagoclur** [comment]
La lista nomás es un array representativo de los marcos libres y ocupados.
`c
int frames_totales = config_memoria.tam_memoria/config_memoria.tam_pagina;
bitmap_frames = list_create();
for(int i = 0; i<frames_totales; i++){
    list_add_in_index(bitmap_frames, i, false);
}
`
La memoria contigua la declaré así:
`c
memoria_general = malloc(config_memoria.tam_memoria);
`

Ya igual más o menos entendí. Kernel me pasa nomás el PID del proceso para el cual tengo que hacer una tabla de páginas, pero lo cargo vacío. Una vez que CPU me manda el resize, obtengo el tamaño del proceso y en base a eso, obtengo la cantidad de páginas que tiene el proceso. Ahí tengo que ver donde cargar el proceso en base a los marcos libres u ocupados que tenga en el array. 

Una duda que me surgió, ¿qué cargamos específicamente en la memoria contigua para representar al proceso? Podemos poner un numero del tamaño correspondiente de la página y listo?

**Comment by tiagoclur** [comment]
Por ejemplo, me queda que el proceso cuyo PID = 2 tiene 3 páginas (0, 1, 2) y quiero cargar la página 0 en el marco 5 (porque es el que tengo libre). 
Suponiendo que cada página pesa 64, debería hacer:
```c
memcpy(memoria_general+320, 1, 64);
``` 
Va por ahí?

**Comment by mefederico** [comment]
Hola buenas! 

Al momento del resize no tienen que asignar nada y en ningún momento tienen que vaciar la memoria previo a ninguna asignación.

Las escrituras se van a realizar con operaciones que vengan de CPU o de las IO

Que van a llegar como una DF + tamanio del contenido + contenido

```C
void* dato;
// Asignacion de valor a dato
memcpy(memoria_general+DF, dato, tamanio);
```

Saludos!

**Comment by tiagoclur** [comment]
Claro, eso sería en una solicitud de escritura. ¿Entonces en el resize lo único que se hace es determinar cuantas páginas tiene el proceso?

**Comment by iago64** [comment]
Si

Saludos.-

**Comment by tiagoclur** [comment]
Última pregunta, y con esto ya cierro el issue. Si en la solicitud de escritura, me piden guardar x valor del byte 20 al 40. (O sea, la dirección física es 20 y el tamaño también es 20) y el proceso tiene cuatro páginas de 16 bytes, ¿tendría que usar las páginas 2 y 3 del proceso en cuestión? (teniendo en cuenta que la segunda página va desde 16 a 31 y la tercera de 32 a 47).

**Comment by tiagoclur** [comment]
¿O al ser sobre la memoria contigua y no tener ninguna página del proceso ocupada, serían nomás las dos primeras páginas de la tabla de páginas del proceso?

**Comment by iago64** [comment]
Buenas!

Tienen que guardar en las **páginas** correspondientes, en este caso 2 y 3.

Saludos.-

**Comment by tiagoclur** [comment]
Perfecto, ya se entendió más o menos todo. Graciasss
