### ISSUE TITLE
Race condition logger

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3913]
Buenas,
Tenemos una duda con el logger. Cuando corremos helgrind nos detecta muchas race condition sobre este, deberiamos ponerle un mutex? Entendemos que influye sobre el orden en el que se muestran los logs muchas veces pero no mucho más que eso creemos.
Tenemos un logger global en kernel utilizado por distintos hilos.

**Comment by mefederico** [comment]
Hola buenas! 

Helgrind detecta las posibles race conditions a la vista de helgrind el log es un recurso que están usando muchos threads a la vez pero es realmente un problema para nosotros?

Pensemos 🤔 

La definición de condición de carrera es:

> Una condición de carrera es un comportamiento del software en el cual la salida depende de un orden de ejecución de eventos que no se encuentran bajo control y que puede provocar resultados incorrectos

Si tomamos el log como "la salida" parece que nos aplica peeeeero

Que hacemos con el log? Solamente escribimos, cada iteración que tenemos con el mismo es escribir algo y listo, podría considerarse atómica

Entonces llega un thread escribe y luego llega otro y escribe y etc.

Si le agregamos un semáforo que va a pasar?
llega uno reserva escribe libera, llega otra reserva escribe libera, etc.

O sea, con semáforos no estarías solucionando nada, seguirías teniendo el mismo comportamiento.

En el log que queremos ver? En que momento pasan las cosas, es lógico que haya threads que llegan antes que otros a loggear porque justamente están haciendo las cosas antes que los demás

Por lo que nuestra salida es justamente ese caos de cosas pasando a la vez y es totalmente esperable que el orden de los logs dependa de quien llego primero a loggear

tl;dr Está bien que los logs estén desordenados dado que se están haciendo muchas cosas en paralelo

Saludos!

**Comment by rood8592** [comment]
Dale, muchas gracias!
