### ISSUE TITLE
Que hacer al no poder crear u ampliar un archivo con FS

### ISSUE THREAD

**Issue by ManuRodri01** [sisoputnfrba/foro#3915]
Buenas, tenia una duda sobre que es lo que deberíamos hacer si no hay bloques suficientes a la hora de crear o ampliar un archivo.
Se debería finalizar el proceso? Y si es así, cual seria el motivo de finalización (Para el logger)?

Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

Es un escenario que no vamos a probar.

Saludos.-

**Comment by ManuRodri01** [comment]
Oka, muchas gracias
