### ISSUE TITLE
Tamaño Mínimo de Páginas

### ISSUE THREAD

**Issue by yaanel** [sisoputnfrba/foro#3916]
Buenas!
Tenemos una duda con el tamaño de página mínimo que puede tener nuestra memoria.
Esto es más que nada porque, por ejemplo, el caso en el que la memoria tenga marcos de 2 bytes (y en consecuencia, páginas de 2 bytes) trae complicaciones extra a la hora de la implementación de las instrucciones MOV_IN y MOV_OUT.

¿Por qué es esto?
Si las páginas tuvieran un tamaño mínimo >=4, yo sabría que al hacer un MOV_IN voy a leer contenido en como máximo 2 páginas. (E implementamos la instrucción dicha teniendo en cuenta esto).
Ahora, si el tamaño de página mínimo fuera = 2, podría existir el caso en el que se tenga que leer el contenido de hasta 3 páginas, siendo este el único caso en el que va a pasar eso.
(Por ejemplo, DL 29, habría que leer el contenido asociado a las páginas 14, 15 y 16).
Agrego: leímos en un issue que el tamaño mínimo de las páginas va a ser mayor a un byte, pero de igual forma nos gustaría saber cuál puede ser el tamaño mínimo por el caso mencionado. 
Gracias :D!

**Comment by mefederico** [comment]
Hola buenas! 

Tal vez en MOV_IN y MOV_OUT puedan tener ese caso contemplado pero con `COPY_STRING, IO_STDIN_READ, IO_STDOUT_WRITE, IO_FS_WRITE, IO_FS_READ` igual les va a pasar que tengan que leer un numero indeterminado de marcos, por lo que el problema que se ahorren ahora en MOV_IN y MOV_OUT se lo van a volver a encontrar. Por lo que les recomendaría no jugar mucho con esa variable. El tamaño mínimo de pagina va a ser  `>= 1`

Saludos!

**Comment by yaanel** [comment]
Bueno! Muchas gracias :D!
