### ISSUE TITLE
Duda cuantas ráfagas consume un proceso

### ISSUE THREAD

**Issue by jkarabin** [sisoputnfrba/foro#3917]
Hola, con mi grupo teníamos la siguiente duda: ¿Cómo sabemos cuantas ráfagas consume un proceso? ¿Sería una ráfaga por cada instrucción?

### 💭 Soluciones posibles
¿Las estimamos? 
¿Sería una iteración del ciclo de instrucción? 
¿Una línea del script de instrucciones?

**Comment by RaniAgus** [comment]
¡Buenas! Una ráfaga es un corto período en el cual un proceso es planificado para hacer uso de la CPU. 

En la parte teórica, este período de se mide en unidades discretas usando ciclos de CPU, pero en el TP (al igual que en un sistema operativo real) se usa un período de tiempo. Es por esto que, por ejemplo, el Quantum está definido como un tiempo en milisegundos.

Quizás no les sirva de mucho saber cuántas _ráfagas_ ejecuta un proceso. Lo que sí les va a servir es cuánto _tiempo_ de uso de CPU ocupó la última ráfaga, la cual inicia cuando el proceso pasa a EXEC y finaliza cuando éste debe salir de dicho estado.

Para esto, pueden utilizar `commons/temporal.h`, el cual incluye como TAD un cronómetro que pueden iniciar cuando inicie la ráfaga y detenerlo cuando finalice.

Saludos

**Comment by jkarabin** [comment]
Gracias!
