### ISSUE TITLE
Duda sobre procedimiento ante un fallo en la escritura

### ISSUE THREAD

**Issue by Lisandrogq** [sisoputnfrba/foro#3919]
Buenas, traigo una breve consulta ,que se debe hacer ante un fallo en la escritura, como por ejemplo, tratar de escribir mas allá del ultimo frame asignado? Una opcion es terminar el programa de manera similar a la situacion de OUT_OF_MEMORY.

En la consigna solo encontre esta parte que habla unicamente de la situacion favorable, debemos asumir que no pasara?
> Ante un pedido de escritura, escribir lo indicado a partir de la dirección física pedida. En caso satisfactorio se responderá un mensaje de ‘OK’.

Saludos

**Comment by LeandroCarbajales** [comment]
Buenas!
Exactamente, no pasará, si fuera así avísennos ya que estarían mal calculadas las pruebas.

Si los hace quedar más tranquilos igualmente pueden tirar OUT_OF_MEMORY en ese caso. Solamente como aclaración, el error no sería a la hora de escribir sino a la hora de traducir la dirección, cuando CPU le pregunte a Memoria "en qué marco está x página?", la memoria le respondería algo como "ERROR, en ninguno".

Saludos!
      Lean

**Comment by Lisandrogq** [comment]
Genial, gracias!
