### ISSUE TITLE
Memoria - Duda Out of Memory (resize) / tamaño de escritura / que hacer durante retardo

### ISSUE THREAD

**Issue by Brai93** [sisoputnfrba/foro#3920]
Buenas, tengo varias dudas sobre el modulo memoria,

RETARDO
1. Actualmente tengo un hilo que escucha peticiones, y cuando llega por ejem un pedido de instruccion desde CPU realiza el retardo y luego responde pero de una forma "estructurada". Mi pregunta seria, durante este retardo (utilizo usleep), memoria deberia continuar haciendo otra cosa??

TAMAÑO DE LEIDA/ESCRITURA
2. En los casos de lectura/guardar en memoria, el tamaño de lo leido siempre es uint32_t (tamaño de registro)???  o tambien puede ser uint8_t? 

RESIZE
4. Esta duda me surgio por los casos Out of Memory, en este caso si tengo por ejemplo 1 marco libre y me llega un resize pidiendo 2 marcos mas, deberia llenar el marco libre primero o directamente rechazar la operacion avisando a cpu?
5. Esto me surgio leyendo una issue--> Lei que se espera que siempre al crear una pagina durante un resize se espera que se le asigne un marco. En este caso podemos suponer que hay un maximo de paginas igual a la cantidad de marcos existentes ?(suponiendo que si hay un kill_process se eliminan las paginas asociadas a este)

Muchas gracias por su respuestas!
Saludos.-

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- De CPU no deberías hacer nada porque la misma va a estar esperando la respuesta de memoria, ahora si te llega algo de Kernel o de las interfaces de IO si deberías atenderlas.

2.- El tamaño depende de lo que te manden, puede ser un uint32_t, un uint8_t, x bytes, todo va a estar sujeto a como implementen las estructuras.

3.- :eyes:

4.- Rechazas directamente porque no tenes suficientes marcos para resolver el pedido.

5.- Si, eventualmente un proceso solo puede ocupar toda la memoria y esta bien, si les llega un resize de tamaño mayor a la memoria total pueden rechazarlo de una sin controlar nada mas.

Saludos.-

**Comment by EstebanGL** [comment]
> 1.- De CPU no deberías hacer nada porque la misma va a estar esperando la respuesta de memoria, ahora si te llega algo de Kernel o de las interfaces de IO si deberías atenderlas.

Pero si el enunciado dice que cuando te llega una petición de CPU sobre alguna instrucción o algo de I/O tenes que esperar un tiempo antes de dar una respuesta.

**Comment by Brai93** [comment]
Gracias Dami!

> 2.- El tamaño depende de lo que te manden, puede ser un uint32_t, un uint8_t, x bytes, todo va a estar sujeto a como implementen las estructuras.

Por el punto 2 entiendo que son 2 casos:
-Peticion del tipo IO (STDIN / STDOUT), en las que memoria recibe los bytes a leer/escribir por parametro
-Peticion directa de CPU (MOVIN /MOVOUT), en las que puede ser solo un uint32 o un uint8, es correcto? (corresponderia al tamaño de registro)

El resto de los puntos me re ayudo tus comentarios.

GRACIAS!

**Comment by FredeHG** [comment]
Hola @EstebanGL !

En memoria si deben hacer el sleep, usleep está bien, solamente tienen que multiplicar el numero por 1000 para pasar de microsegundos a milisegundos 

Ref. https://man7.org/linux/man-pages/man3/usleep.3.html

Saludos!

**Comment by FredeHG** [comment]
Hola @Brai93 !

No te olvides de COPY_STRING, FS_WRITE y FS_READ

En MOV_IN, MOV_OUT si van a leer los tamaños de los registros como máximo.
Les recomendaría que prueben escribir un numero y poder recuperarlo exactamente igual, para confirmar que los casteos que hagan estén bien

Saludos!

**Comment by RaniAgus** [comment]
Buenas @Brai93 y @EstebanGL, ¿quedaron claras las respuestas de Fede? Saludos

**Comment by EstebanGL** [comment]
Buenas, sisi yo nomas queria aclarar lo del sleep. Gracias

**Comment by RaniAgus** [comment]
¡Buenas @Brai93! Cierro el issue por inactividad, ante cualquier consulta pueden abrir uno nuevo. Saludos
