### ISSUE TITLE
Problema bitarray

### ISSUE THREAD

**Issue by fmigliavacca** [sisoputnfrba/foro#3922]
Buenas, estoy teniendo problemas para usar tamaños de memoria y tamaños de pagina que den frames no multiplos de 8, me pasa esto: 
![image](https://github.com/sisoputnfrba/foro/assets/163766676/4fca33b7-b750-4e3a-bc97-995186798fa7)
![image](https://github.com/sisoputnfrba/foro/assets/163766676/62c37a5c-2be7-4d65-9279-821a0e22d119)
Tengo ese config que debería darme 10 marcos, pero me da 8, cómo puedo solucionar este problema?

**Comment by iago64** [comment]
Buenas! Cómo va?

Dado que los ayudantes no somos compiladores humanos y como ademas parece que  no leíste el comentario tan amable que tenemos en el template de issue que dice algo asi como:

> No subas capturas de pantalla, copiá el código relevante a tu problema y pegalo acá. Podés darle formato código con (Ctrl + 'e').

Lo único que te pregunto es, probaste debugueando? viste que valores te devuelve despues de llamar a `ceil()`?

Saludos.-

**Comment by f-and** [comment]
Buenas!
Si, es el bitarray_create fijate que tendrías que pasarle el `largoCadenaBytes` en vez de realizar la división de nuevo, ya que seguramente el `(tamanioBitArray)/8` seguro le hace un `floor()` en vez del `ceil()` que hiciste.

**Comment by fmigliavacca** [comment]
Claro, esto por qué ocurriría? Siempre el valor que meto en en createwithmode se multiplica por 8, no? Esto lo hace xq calcula que sea un byte?

**Comment by f-and** [comment]
Esto ya va más a como C directamente maneja el cambio de Float a Int, porque fijate que lo que estarías pasandole al `bitarray_create` es un Float, cuando deberia recibir un Int, y ahí C tiene que decidir que hacer al respecto, usualmente te tiraría un error o warning, pero para este caso decide simplemente hacer un `floor()` y continuar.
En cuanto al tema de multiplicar o no por 8, tengo que decir que no afecta mucho al bitarray (en realidad, [nada mas se usa para imprimirte el tamaño](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/bitarray.c) ;) ), lo que le importa más que nada al bitarray es la variable `cadena` que tenga el malloc de tamaño correcto, lo demas no hace verificaciones, y para tu caso lo marcas bien.
