### ISSUE TITLE
Pequeña consulta de paginación

### ISSUE THREAD

**Issue by AgustinCarlanaRivero** [sisoputnfrba/foro#3923]
Hola, solo tengo una duda. La cantidad de entradas que puede tener la tabla de paginas de cada proceso es la misma que la cantidad de marcos total que hay en la memoria? O hay algún límite?
Saludos.

**Comment by LeandroCarbajales** [comment]
A efectos del trabajo no hay ningún límite definido. Sin embargo, como bien marcas, la cantidad total de marcos te va a limitar indefectiblemente.

Saludos!
     Lean

**Comment by LeandroCarbajales** [comment]
En mi opinión usar una lista es mucho más amigable que un array para este caso :)

> si un proceso pide mas memoria de la que hay, habría Out of Memory. Pero, se le asigna el espacio q se puede asignar, o no se asigna nada de nada?

Si igualmente ese proceso va a finalizar debido al OOM, le asignes los marcos o no, se van a liberar todos sus marcos inmediatamente. Por lo que capaz lo más simple sea no asignarle nada y tirar el OOM de una.

**Comment by AgustinCarlanaRivero** [comment]
Perfecto, muchas gracias!
