### ISSUE TITLE
Duda TLB 

### ISSUE THREAD

**Issue by Santi24308** [sisoputnfrba/foro#3924]
Con respecto a la implementación de la TLB, con mi grupo, tenemos la siguiente duda:
Entendemos que en la TLB se almacenan traducciones de páginas  para evitar tener que calcularlas otra vez y optimizar el proceso.
Ahora el punto está en que no estamos seguros si la TLB  se "reinicia" con el cambio de contexto (según la teoría esto funciona así) o no. Según enunciado entendemos que esto NO pasa porque al contemplar que la "víctima" a desalojar/reemplazar puede ser una traducción de un proceso diferente al que se está ejecutando, implica que no hubo un reinicio al cambiar el contexto de ejecución

Enunciado
>"Por último, se agregará la nueva entrada a la TLB, si la misma se encuentra llena se deberá reemplazar siguiendo el algoritmo configurado, pudiendo elegir como víctima cualquier otra entrada (incluso de otro proceso)."

Video ->1:26:20 
https://www.youtube.com/watch?v=MTnPYWIJ9zM&list=PL6oA23OrxDZDQEFo7aKBceotX48vLmQYA&index=29

**Comment by LeandroCarbajales** [comment]
Buenas!
La parte de la clase que mencionás es correcta en una TLB sin PID donde como bien dice "se tiene solamente las traducciones del proceso en ejecución", por lo que limpiarla es absolutamente necesario ante cada cambio de contexto.
En este trabajo así como en muchos ejercicios de la teoría no es necesario limpiar la TLB en un cambio de contexto ya que la misma tiene el PID en cada entrada. Podrían considerar limpiar las entradas correspondientes cuando un proceso finaliza ya que las mismas nunca se usarían, pero igualmente serían reemplazadas tarde o temprano por lo que tampoco es absolutamente necesario.

**Comment by Santi24308** [comment]
Perfecto, super claro. Muchas gracias
