### ISSUE TITLE
duda sobre los retardos en memoria

### ISSUE THREAD

**Issue by mSpadoni** [sisoputnfrba/foro#3925]
hola tengo una duda con los retardos en memoria, estos deben ir antes o después de recibir el buffer??
o cuando le mando una respuesta kernel por ejemplo

**Comment by LeandroCarbajales** [comment]
Buenas!
Es completamente indiferente en qué momento de la atención esperan el tiempo de retardo.

Saludos!
      Lean

**Comment by mSpadoni** [comment]
'''
#include "memoria_kernel.h"

void atender_kernel()
{
    t_buffer *un_buffer;
    bool control_key = 1;
    while (control_key)
    {
        int cod_op = recibir_operacion(socket_kernel);
        switch (cod_op)
        {
        case MENSAJE:
            //
            break;
        case PAQUETE:
            //
            break;
        case CREAR_PROCESO:
           usleep(retardo_respuesta);
           un_buffer = recibir_buffer(socket_kernel);
           t_proceso *proceso = atender_crear_proceso(un_buffer);
           list_add(lista_de_procesos, proceso);
           free(proceso);
           destruir_buffer(un_buffer);
           break;
        case -1:
            log_error(mem_logger, "Se desconecto kernel");
            control_key = 0;
            break;
        default:
            log_warning(mem_logger, "Operacion desconocida de kernel");
            break;
        }
    }
};
'''

**Comment by mSpadoni** [comment]
gracias
