### ISSUE TITLE
Duda Memoria

### ISSUE THREAD

**Issue by yaanel** [sisoputnfrba/foro#3926]
Hola! Tengo una duda acerca de Memoria. No me queda muy en claro cómo es que Memoria recibe los datos para poder escribirlos en ella y en qué tipo de dato los envía a CPU y a IO.
1. En el momento en el que se recibe un MOV_OUT: siendo que son valores de registros, ¿se recibe esa información a escribir en void* o en entero? 
2. Por otro lado, cuando se quiere escribir una cadena de caracteres, tanto para COPY_STRING como para STDIN y DIAL_FS: ¿se recibe el texto a escribir en Memoria como un char* o como su ASCII? Leí el issue #3877 en el que se mencionan que se leen bytes, pero no me termina de cerrar cómo es que recibo la información para guardarlo en el void*. En caso de que reciba ASCII, en la Memoria Contigua ¿yo solo voy a escribir enteros que representan bytes?
3. Además, quería preguntar, en el caso de MOV_IN, DIALFS y STDOUT ¿en qué tipo de dato mando la información leída?
Muchas gracias :D!

**Comment by RaniAgus** [comment]
¡Buenas!

> ¿se recibe esa información a escribir en void* o en entero?

1. Cualquiera de las dos opciones es viable. Te recomendaría usar un `void*` así pueden reutilizar la solicitud de escritura a cualquier porción de bytes, o sea, siempre enviar: `(void* valor, uint32_t tamanio, uint32_t direccion_fisica)`.

Con esto les queda implementada la escritura para 3 instrucciones (`MOV_IN`, `COPY_STRING` y `IO_STDIN_READ`) al precio de una 😄

> tanto para COPY_STRING como para STDIN y DIAL_FS: ¿se recibe el texto a escribir en Memoria como un char* o como su ASCII?

4. Es redundante. Un `char` **es** su representación en ASCII. A eso apunta el comentario del issue: vos podrías escribir el texto "Hola Mundo" y su primer byte va a ser el ASCII del caracter `H`.

> Además, quería preguntar, en el caso de MOV_IN, DIALFS y STDOUT ¿en qué tipo de dato mando la información leída?

5. Lo mismo que al escribir: pueden utilizar un tipo de dato específico o generalizarlo en `void*` y dejar que cada módulo la interprete como necesita 👍🏻 

Saludos

**Comment by yaanel** [comment]
Perfecto! Te quiero repreguntar sobre el punto 2 y 3.
Sobre el punto 2: Entonces, ¿recibir el char* o el entero del ASCII es equivalente? 
Cuando reciba una cadena, ¿debería recibirla caracter a caracter o recibir el ASCII de toda la cadena? Porque al recibir el ASCII de toda la cadena, estuve teniendo problemas al interpretarlo como el char* que verdaderamente es.
Sobre el punto 3: ¿Cómo es que puedo interpretar un void*  recibido siendo que cada módulo va a estar corriendo en distintas computadoras y ese void* representa un puntero que apunta a una dirección de memoria que en mi computadora no apunta necesariamente al mismo dato?
Gracias!

**Comment by RaniAgus** [comment]
Sip, es correcto que tanto un `char*` como un `void*` son solo direcciones de memoria del proceso de Linux en donde ir a buscar el dato.

A lo que me refería es que lo que transportan por sockets es el contenido al que apuntan.

Ese contenido, si bien desde un módulo puede interpretarse como caracteres ASCII, son simplemente bytes, y Memoria puede interpretarlos como tales

**Comment by yaanel** [comment]
Perfecto! Mil gracias :D
