### ISSUE TITLE
Consulta sobre multiples hilos en la conexion Memoria-IO

### ISSUE THREAD

**Issue by Champa123** [sisoputnfrba/foro#3928]
Para atender las peticiones de las interfaces en memoria creamos multiples hilos 

```
void *abrirSocketIO()
{
    // Necesito crear un thread por cada socket que se conecte de IO
    int socket;
    while (1)
    {
        socket = esperar_cliente(socket_memoria);
        uint32_t resultOk = 0;
        uint32_t resultError = -1;
        uint32_t respuesta;
        recv(socket, &respuesta, sizeof(uint32_t), MSG_WAITALL);
        if (respuesta == 1)
            send(socket, &resultOk, sizeof(uint32_t), 0);
        else
            send(socket, &resultError, sizeof(uint32_t), 0);

        pthread_t thread_atender_io;
        pthread_create(&thread_atender_io, NULL, atender_cliente_io, (void *)&socket);
        pthread_detach(thread_atender_io);
    }
    return "";
}
```
Entonces cada hilo deberia tener su propio file descriptor de esa conexion. 

Cuando intento de ejecutar un script teniendo 2 interfaces levantadas pareciera que esta teniendo un bloqueo entre los hilos.
Pueden los recv bloquearse entre si ??

Basicamente se queda bloqueado recibiendo el mensaje enviado por las interfaces. Si ejecuto de 1 interfaz a la vez veo que funciona correctamente.

**Comment by Champa123** [comment]
Clave me faltaba el Malloc! Gracias!

**Comment by RaniAgus** [comment]
¡Buenas @Champa123! Paso a patrullar para avisar (para la próxima) que si la duda ya fue resuelta pueden cerrar el issue 👮🏻‍♂️

Si en un futuro ven que algo no terminó de cuadrar pueden tomarse la libertad de abrir uno nuevo referenciando éste. 

¡Saludos!

**Comment by Champa123** [comment]
Gracias, colgue en cerrarlo!
