### ISSUE TITLE
Dudas intro file system

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3930]
Como va? me surgen varias dudas ahora que podemos arrancar con la interfaz FS

1) Primero vi que en el tp anterior estaban las Instrucciones FOPEN y FCLOSE, pero este año no estan. Eso quiere decir entonces  que todos los archivos que creemos estan siempre abiertos y todos los procesos tienen acceso total a todos los archivos?

2) Me imagino que el FCB esta representando con el archivo de metadata, la duda aca es si esto lo tenemos que cargar en memoria (la memoria posta)  y tenerlo como en una lista auxiliar de archivos abiertos y despues ir persistiendolos con mmap y msync, o si directamente cada vez que quiera acceder a la metadata accedemos al archivo y listo

3) Si la persistencia tanto del archivo de bloques como el archivo bitmap se hace de manera sincronica, por ejemplo, cada vez que modificamos la rereferncia de memoria hacer mysnc. O si se hace de forma asincronica (cada n segundos hacer mysnc) 

4) Si hago CREATE de un archivo ya existente o DELETE de un archivo que no existe, como se manejan esos casos?

**Comment by f-and** [comment]
Buenas!
1. Si, ya que se tomaría practicamente como vienen haciendolo como memoria (no me citen en esto por favor ;P) pero con pasos extra (validar el archivo de metadata de cada archivo, compactar, etc.), cualquier proceso podría leer y escribir cualquier archivo creado.
2. Para esta pregunta cito la nota al pie del TP en la sección de DialFS:
> Estos archivos de metadata tienen una similitud con los archivos de configuración de los módulos, por lo que recomendamos utilizar las commons propias de config para operarlos.
Básicamente, van a estar constantemente usando las funciones de config para abrir, leer, posiblemente modificar, y luego cerrar los archivos de metadata que van generando, no se preocupen con el mmap y msync con eso.
3. Les recomendamos a mil hacerlo de modo sincrónico, ya que hacerlo de modo asincrónico puede causarles excesivos problemas. A su vez va a ser mucho más natural hacerlo sincrónicamente ya que se va a ir interactuando con el archivo de bloques y el bitarray de forma secuencial, no va a haber casos donde tengan a más de un hilo manejando uno u el otro.
4. Diría por ahora que lo manejen como prefieran, seguramente no se vaya a probar ya que no se especificó en el enunciado. Pueden dejar un mensaje de Warning avisando que no se realiza nada, o pueden retornar el proceso y mandarlo a EXIT.

**Comment by GonTurri** [comment]
Muchas gracias por todo!
