### ISSUE TITLE
Duda Recursos

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#3932]
Hola tengo una pregunta. Si yo tengo 0 instancias de un recurso y llega un wait de ese. Entonces resto 1 y queda en -1, despues el proceso se bloquea. En ningun momento le asigne una instancia y tampoco guarde registro de esa asignacion de instancia en la tabla que tengo (porque no hubo asignacion). Una vez el proceso bloqueado, lo finalizo por consola. Al finalizar no libera ningun recurso porque nunca le fue concedido. Este funcionamiento estaria bien? porque me confundio la consigna

**Comment by f-and** [comment]
Buenas Joaquin! Te paso el issue #3906 donde contestamos esto, pero la corta es: No, se "liberaria" o más bien se sumaria un 1 a la instancia, porque si no lo agregas la cantidad de instancias te queda en -1, que no tendría sentido ya que ningún proceso esta esperando bloqueado.
Saludos!

**Comment by JoaquinCoaricona** [comment]
Ok, me surgio una pregunta con el signal. En el signal solo tenemos que liberar un proceso bloqueado cuando el numero de instancias es menor a 0 estrictamente?
Porque habia leido en un issue que primero se hace el ++ o el -- (en el wait). Y despues se bloquea o desbloquea procesos. Entonces en el signal, si yo tenia un recurso en 0, vino un wait y se bloqueo ese proceso, yo dejo al recurso en -1, ahora cuando venga un signal yo le hago ++ y queda en 0 y despues hago el control y como no es menor estricto a 0, no libere el proceso bloqueado

**Comment by JoaquinCoaricona** [comment]
Ok gracias entendi un poco mejor, pero me surgio  una duda con esto en la prueba de deadlock. Como yo no guardo registro de la asignacion si el proceso se bloquea (porque no hay asignacion en ese caso). Cuando en la prueba llegamos a un deadlock, quedan 4 procesos bloqueados, entonces finalizo uno que libera a los otros. Vi que cada proceso haria dos waits y dos signals de los mismos recursos. Osea P1 lo haria sobre R1 y R2 y asi cada uno tendria un par. Entonces como solo pudieron hacer el primer wait y el segundo no, en el segundo no hubo asignacion del recurso. 
Cuando hago los signals siempre me fijo en la tabla de recursos asignados si hay alguno que cumpla con el par (nombre Recurso y pid que lo pidio) porque seria la segunda parte del par wait, signal. Pero como en este caso el wait salio mal entonces  al buscar en esta tabla no va a encontrar nada. Mi duda es si este seria la forma de ejecucion correcta de la prueba y si esta ultima situacion se daria en 3 casos. Serian 4 pero el que finalizamos por consola no llega a los dos signals del final.  Desde ya gracias

**Comment by f-and** [comment]
Considerando únicamente el primer proceso, LOCK_A, este primero de todo hace un WAIT del recurso RA, que tiene una instancia, por lo que se lo guarda y sigue adelante, luego, hace un WAIT del recurso RB, que tiene 0 instancias, por lo que pasaria a esperar este recurso y la cantidad de instancias pasaria a -1. Si este es el proceso que terminas por consola, lo que pasaria seria que:
El recurso RA se libera como si hiciera un SIGNAL, desbloqueando si es que hay el proceso que haya solicitado ese recurso.
Y El recurso RB se "libera" pero sin desbloquear a nadie, solo se saca de la cola de bloqueados del recurso y se aumenta la cantidad de instancias +1.
Asi se entiende como seria el procedimiento?
En si, el proceso que termines nunca va a ejecutar otras instrucciones que la ultima que hizo porque se manda a EXIT directamente. Y para contestar, la prueba de Deadlock se tiene que poder resolver cualquiera que sea el proceso terminado.

**Comment by JoaquinCoaricona** [comment]
Ok, pero una pregunta. Cuando haces un wait y te bloqueas no guardas un registro de recurso asignado porque no se asigno. Entonces si despues te desbloquean y mas despues haces el signal de ese proceso que no recibiste pero en teoria lo ibas a recibir (por eso haces el signal). Entonces estas haciendo un ++ a la instancia pero sin haber tenido una asignada. Este caso se da  3 veces en la prueba? porque se bloquean los 4 procesos y solo 3 llegan a los signals finales donde creo que pasaria esto.

**Comment by f-and** [comment]
Creo que te estas mareando al respecto, cuando uno hace Wait hay dos etapas:
1. Verificar y trabarse, osea que si hay al menos una instancia, seguir, si no bloquearse
2. Recibir la instancia y continuar
En la prueba de Deadlock, todos los procesos quedan en un principio adentro de la primera etapa, por lo que cuando se termina alguno no se libera el recurso que esta esperando, solo se reduce la cola de espera, pero si otro proceso hace un signal, cuando desbloquea al primer proceso, también le esta dando la instancia (como un pasamanos por así decir). Cuando ese proceso ahora hace el segundo Signal, lo que haría es agregar una instancia y sacarla si la tenia asignada.
Por lo tanto, al menos en la prueba de Deadlock, siempre que se hace un Wait y luego un Signal, este es practicamente un pasamanos de recursos (el Wait solicita un recurso, y el Signal se lo da). Cuando termina la prueba tendria que quedarte la misma cantidad de recursos que la que tuviste en un principio (1, 1, 1 y 1).

**Comment by JoaquinCoaricona** [comment]
Si yo tengo un recurso en 0, y despues viene un proceso y lo deja en -1 y se queda bloqueado. Ponele que otro proceso hace un signal y lo desbloquea. En ese caso el primer proceso que fue desbloqueado, se le tiene que asignar el recurso? o solamente se lo desbloquea?

**Comment by f-and** [comment]
Claro, se le asigna un recurso, porque justamente para eso pidio el Wait jaja
