### ISSUE TITLE
resize: memoria 

### ISSUE THREAD

**Issue by mSpadoni** [sisoputnfrba/foro#3933]
hola tengo algunas dudas con el riesize en memoria

1) leyendo este issues https://github.com/sisoputnfrba/foro/issues/3886#issuecomment-2156878871 me agarro la duda si esta bien usar un bit de presencia  para indicar que la pagina esta en memoria y que cuando se tenga que escribir algo en memoria ese bit se ponga en 1 y recién ahí el frame del bitmap se ponga como ocupado, esto por si llego a tener un frame con 2 paginas asignadas de distintos procesos ¿o eso ya no es parte de la paginación simple?

2) con el tema de out of memory,¿ debo devolver out of memory tal cual a la cpu o podría ser un string que lo represente?

3) La ultima duda que tengo es que si yo por ejemplo le asigno una pagina de un determinado proceso a un frame, escribo en esta y luego finalizo ese proceso ¿Cuándo le asigno otra pagina a ese frame debo de reescribir su contenido para que no tenga nada o eso lo hago cuando me manden una peticion de escritura?

4) otra duda mas, sobre list_add_index() ¿puedo agregar primero un elemento al índice 1 por ejemplo y luego al 30 o eso no es posible?

**Comment by LeandroCarbajales** [comment]
Buenas!
1- No estaría bien ya que la idea es que por defecto cada frame solamente tenga una página asignada. Compartir memoria (frames) es parte de paginación simple pero no está contemplado en este trabajo.

2- Puede ser cualquier mensaje que para ustedes signifique out of memory.

3- No es necesario "borrar" el contenido de la página al liberar el frame.

4- Mi recomendación es que lo pruebes :)

**Comment by mSpadoni** [comment]
gracias

**Comment by mSpadoni** [comment]
hola, otra cosa mas, el bit de modificado tampoco esta contemplado no?

**Comment by LeandroCarbajales** [comment]
Te lo pregunto a vos :). Para qué usarías el bit de modificado?

**Comment by iago64** [comment]
Buenas! Cómo va?

Para que te sirve el bit de modificado si no tenes memoria virtual?

Saludos.-

**Comment by LeandroCarbajales** [comment]
Nos falta mutua exclusión con @iago64 😛
