### ISSUE TITLE
Tipos de errores escritura, lectura y modificacion de tamaño en memoria

### ISSUE THREAD

**Issue by LucianoKremer** [sisoputnfrba/foro#3935]
Hola! Buenas Tardes. 

Tenia una consulta, en el enunciado dice que en caso de que no haya espacio suficiente en memoria al hacer resize se arroje out of memory, hasta acá todo bien. Ahora la duda que me surgió es, en caso de que por ejemplo intente escribir algo que supere el tamaño asignado, solicite una pagina que no esta creada en memoria para escribir o leer se supone que deberia arrojar un error. Deberia contemplar estos casos? Nosotros lo incluimos dentro de out_of_memory, pero quiza seria mas acertado un page_fault o ¿Tendria que llamar al error de una manera en particular? 

Un caso particular es por ejemplo que solicite una pagina cuando el proceso no tiene asignado marcos, o no los suficientes como para alcanzar esa pagina. En nuestro caso a la hora de transformar la dirección lógica a física si hay un error de este estilo devolvemos un marco = -1, al detectar esto lo categorizamos como "out of memory", aunque quizá deberíamos hacerlo de otra manera.

Nos pasamos alguna información por alto? O como deberíamos manejar estos casos?

Saludos! Luciano.

**Comment by LucianoKremer** [comment]
Replantee un par de cosas y decidí separar estos errores entre "out_of_memory" para el resize y "access_denied" para los demás casos.

**Comment by LeandroCarbajales** [comment]
Buenas!
Tu planteo está perfecto y pueden devolver el error con el mensaje que quieran (aunque page_fault sería el menos indicado dado que es un concepto de memoria virtual).
Sin embargo, en el enunciado no está contemplado ese caso, y como respondimos varios issues esta semana, no se probará y de hecho pueden chequearlo en las pruebas publicadas :)

Saludos!
      Lean
