### ISSUE TITLE
Dudas: recursos y registros SI y DI

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3936]
Buenas, tenemos dudas con respecto a recursos y uno adicional sobre los registros SI y DI:

1 - De otro hilo, el #3697, se aclaró que "vamos a considerar para el tp que un proceso libera el recurso en el momento en el que hace SIGNAL al recurso el mismo proceso". Esto tiene sentido si el pseudocódigo es:
```
WAIT R1 
SIGNAL R1 
EXIT
```
Ahí consideramos que lo libero, si fuera:
```
SIGNAL R1
WAIT R1
EXIT
```
Ahí consideramos que lo liberó o no? Por como está hecho nuestro tp ahora se contempla solo el primer caso, y cualquier proceso que haga wait sin **posterior** signal y finalice debe liberar dicha instancia.

2 - ¿SI y DI solo serán utilizados con SET y COPY_STRING? ¿O puede ser utilizados por mov_in y/o mov_out? ¿En qué escenarios se utilizarían con mov_in y mov_out?

**Comment by f-and** [comment]
Buenas!
1. En realidad, en el segundo caso, considerarías que lo liberas dos veces, ya que el primer Signal, sin un Wait previo, esta generando una instancia del aire, y sumandola a las instancias del recurso, el Wait siguiente lo esta tomando, y el Exit lo liberaria de nuevo, por lo tanto te quedaría una instancia más que cuando empezaste.
En cambio, el primer código que pones solo liberaría el recurso una vez, ya que estaria solicitando un recurso, luego soltandolo, y con eso termina el proceso sin recursos para liberar.

2. SI y DI sirven como registros en general, tranquilamente se podrían usar como se usaria el EAX o el EBX. Por lo que en las situaciones donde usarias MOV_IN o MOV_OUT con EAX, podrias usar SI o DI (o también se podrían usar en SUM, SUB, JNZ, etc). Su único uso especial es en COPY_STRING que es donde se utilizan forzadamente esos dos registros.

**Comment by rood8592** [comment]
Gracias, con el registro PC pasaría lo mismo? O sea se puede utilizar en sub, sum, jnz, mov_in, mov_out, io_stdin_read, etc.

**Comment by iago64** [comment]
Buenas! 

Para el PC solo vamos a hacer SET, no somos taaan rebuscados aun.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @rood8592! ¿Quedó clara la respuesta de Dami? Saludos

**Comment by rood8592** [comment]
Me surgio otra duda, cuando modifican el PC con set debemos despues sumarle 1 al PC como hacemos cuando terminamos de ejecutar otras instrucciones o no hay que sumarle?

**Comment by RaniAgus** [comment]
Misma respuesta que en https://github.com/sisoputnfrba/foro/issues/3892#issuecomment-2158889332

**Comment by rood8592** [comment]
Ok, muchas gracias!
