### ISSUE TITLE
Duda sobre Signal

### ISSUE THREAD

**Issue by GonzaloFernandez20** [sisoputnfrba/foro#3938]
Buenas, leyendo issues sobre el tema, vimos que algunos se aclaraba que se podia dar el caso de un proceso que haga un signal(recurso1) sin antes haber hecho un wait(recurso1). 
Entonces nos surgio la duda de que pasa exactamente en ese caso. 
1) Si ningun otro proceso hizo un wait de ese recurso, creemos que lo unico que sucederia con ese signal es que se crea otra instancia del recurso (++ a la cantidad de instancias).
2) Que pasa si otro/s proceso/s diferentes a este hicieron un wait del mismo recurso y todavia no hicieron el respectivo signal?. Cuando el proceso haga signal, sostenemos que lo unico que hace es crear una nueva instancia? o tiene que liberar a alguna de las instancias que tomaron los procesos previos? Y en caso de que sea asi, como elegimos que instancia liberar?. 

Como aclaración: Nosotros en nuestra implementacion llevamos el registro de que procesos tienen recursos para liberarlos en caso de que finalicen y no los hayan liberado. 

Cita del enunciado: 

A la hora de recibir de la CPU un Contexto de Ejecución desalojado por SIGNAL, el Kernel deberá verificar primero que exista el recurso solicitado, luego sumarle 1 a la cantidad de instancias del mismo. En caso de que corresponda, desbloquea al primer proceso de la cola de bloqueados de ese recurso. Una vez hecho esto, se devuelve la ejecución al proceso que peticiona el SIGNAL.

**Comment by f-and** [comment]
Buenas Gonzalo, para contestar ambas a la vez:
Si, en cualquier situación, un Signal sin un Wait previo es practicamente generar una instancia del aire, cabe mencionar que ningún proceso toca los recursos de otro. Lo que se tienen que fijar siempre que hagan un Signal, haya hecho un Wait antes o no, es que si hay al menos un proceso esperando en la cola, tiene que liberarlo y "asignarle" ese recurso. Y para elegir que proceso liberar, tienen que manejar una cola, ya que los recursos se encolan en formato FIFO, el primer proceso que haga un Wait cuando no hay instancias disponibles tiene que ser el primer proceso en ser asignado y desbloqueado cuando llegue un Signal.

**Comment by GonzaloFernandez20** [comment]
Quedo claro! muchas gracias!
