### ISSUE TITLE
Pasarle PID a memoria para las interfaces

### ISSUE THREAD

**Issue by fmigliavacca** [sisoputnfrba/foro#3940]
Hola! Tengo una duda y me gustaría confirmarlo, está bien si cuando cpu le llega una instrucción de una interfaz, kernel le pasa el pid a la interfaz, y la interfaz se la pase a memoria? Xq es mucho más cómodo, quería confirmar si se podía, supongo que sí porque es una cuestión meramente de estructuras administrativas. Saludos!

**Comment by iago64** [comment]
Si, está bien.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @fmigliavacca! ¿Quedó clara la respuesta de Dami? Saludos

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, ante cualquier consulta pueden abrir uno nuevo. Saludos
