### ISSUE TITLE
Archivo bloques.dat

### ISSUE THREAD

**Issue by EstebanHurtado0** [sisoputnfrba/foro#3941]
Hola, tengo dudas sobre las dialFS y no se bien por donde arrancar.

1)En las interfaces dialFS vamos a contar con 3 archivos que se detallan en el enunciado, cuando iniciamos una interfaz hay que abrirlos, en que modo se abren?

2) Al momento de iniciar el FS el archivo bloques.dat tiene ese tamaño? Es decir,ya esta cargado? O lo iniciamos en 0 y en caso de que se lo escriba, su tamaño máximo será este.

**Comment by FredeHG** [comment]
Hola buenas! 

1. En modo escritura lectura
2. No entiendo que seria "ese tamaño", pero va a tener el tamaño como bien dice el enunciado ` BLOCK_SIZE * BLOCK_COUNT`, al crearlo inicialícenlo como quieran, 0 estaría bien. 

Solo mencionar que si el FS al iniciar el proceso ya esta creado no lo tienen que borrar, sino que ser capaces de seguir operando con ese mismo. Al igual que hace un FS normal, dado que somos personas muy egoístas y nos gusta que al prender y apagar nuestras computadoras nuestra información no se pierda.


Saludos!
