### ISSUE TITLE
Duda simulando escritura y lectura en memoria contigua

### ISSUE THREAD

**Issue by Ivanabete** [sisoputnfrba/foro#3942]
Buenas!
Me armé un código aparte del TP para poder hacer algunas pruebas y poder entender mejor el tema de la lectura/escritura en la memoria contigua.
Básicamente, la idea del código de prueba es escribir un void* (suponiendo que lo recibí de algún modulo e independientemente de lo que representen esos bytes) en el void* que sería la memoria contigua.

### 📝 Código relevante

```C
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>

int tamanio_pagina = 64;

void* memoria_contigua;

void prueba_escritura(uint32_t , uint32_t , void*);
void prueba_lectura(uint32_t , uint32_t);

int main()
{
    memoria_contigua = malloc(1024);

    // Supongamos que dir_fisica, valor_recibido y tamanio me llegaron desde otro modulo.

    //void* valor_recibido = 1634496328;
    //void* valor_recibido = 72;
    void* valor_recibido = "Hola";

    uint32_t dir_logica = 1; 
    int número_página = floor(dir_logica / tamanio_pagina);
    int desplazamiento = dir_logica - número_página * tamanio_pagina; 
    // Calculo la dir_fisica para usar un valor más "realista", pero como dice arriba, supongamos que la recibí.
    int dir_fisica = 2 * tamanio_pagina + desplazamiento; // Supongamos que la página estaba en el marco 2
    printf("La direccion física es: %d \n", dir_fisica);

    uint32_t tamanio = 4; 

    // SIEMPRE va a entrar en el marco el contenido que me manden (los otros modulos se encargan de mandar los datos de tal manera)
    prueba_escritura(dir_fisica, tamanio, valor_recibido);
    prueba_lectura(dir_fisica, tamanio);

    free(memoria_contigua);

    return 0;
}


void prueba_escritura(uint32_t dir_fisica, uint32_t tamanio_escritura, void* valor_recibido){
    //void* valor_a_escribir = &valor_recibido;
    //memcpy(memoria_contigua + dir_fisica, valor_a_escribir, tamanio_escritura);
    memcpy(memoria_contigua + dir_fisica, valor_recibido, tamanio_escritura); // Escribo el dato en memoria
}

void prueba_lectura(uint32_t dir_fisica, uint32_t tamanio_lectura){

    void* contenido_agregado_a_memoria = malloc(tamanio_lectura);

    memcpy(contenido_agregado_a_memoria, memoria_contigua + dir_fisica , tamanio_lectura); // Lo leo

    printf("Valor final de la memoria: %d \n", *(int*)contenido_agregado_a_memoria);
    puts(contenido_agregado_a_memoria);
}
```
El código tiene muchos comentarios como para que se entienda que hay muchas cosas que se suponen de antemano, dado a que el código es un más bien un prototipo y no algo que vaya a implementar directamente así en el TP.

### 🐛 Cómo reproducir el error

1. Si el void* apunta a una cadena de caracteres (char*) ("Hola" en este caso), me basta con hacer esto:
```C
 void prueba_escritura(uint32_t dir_fisica, uint32_t tamanio_escritura, void* valor_recibido){
    memcpy(memoria_contigua + dir_fisica, valor_recibido, tamanio_escritura); 
}
```

El problema con esto, es que si ese valor_recibido, en vez de apuntar a una cadena de caracteres (char*) apuntara a un entero (uint32_t) (1634496328 en este caso), a la hora de hacer la escritura me tira segmentation fault.

2. Intentando solucionar el problema anterior, puedo solucionar el segmentation_fault cuando el void* apunta al entero implementando esto: 
```C
void prueba_escritura(uint32_t dir_fisica, uint32_t tamanio_escritura, void* valor_recibido){
    void* valor_a_escribir = &valor_recibido;
    memcpy(memoria_contigua + dir_fisica, valor_a_escribir, tamanio_escritura);
}
```
Sin embargo, cuando hago eso, si el valor_recibido fuera un puntero que apunta a un char*, el dato no se escribe correctamente.

Lo que imprime prueba_lectura cuando el void* apunta a "Hola": 
Valor final de la memoria: 1431658504 
`UU

Entonces, mis preguntas son:
1. ¿Por qué pasa el segmentation fault en el caso 1?
2. ¿Por qué se da la escritura errónea en el caso 2?
3. ¿Cómo podría solucionar esto? 

Como dije al principio, la idea sería poder tener una única función que escriba en memoria, independientemente de lo que reciba del void*.

Desde ya, muchas gracias.

**Comment by FredeHG** [comment]
Hola buenas! 

`void* valor_recibido = 1634496328;`
Acá le estas diciendo que apunte a la posición de memoria `1634496328` y no que guarde el numero 1634496328.

Es como que en vez de hacer malloc y que te devuelva una posición de memoria valida, le dijiste a C está es tu posición de memoria, y bueno cuando haces memcpy esa posición de memoria nunca se te asigno a vos y por eso te da `segmentation fault`

Y cuando haces 

```C
void prueba_escritura(uint32_t dir_fisica, uint32_t tamanio_escritura, void* valor_recibido){
    void* valor_a_escribir = &valor_recibido;
    memcpy(memoria_contigua + dir_fisica, valor_a_escribir, tamanio_escritura);
}
```

Le estas pidiendo la posición de memoria, y no lo apuntado por. Por eso te anda, pero en el string te deja de andar porque tu valor está en lo apuntado por y no es el apuntado

![image](https://github.com/sisoputnfrba/foro/assets/38965532/97e438de-5ec7-4874-91fd-38bcb69c2111)
VS
![image](https://github.com/sisoputnfrba/foro/assets/38965532/30aae88b-1c40-435c-b0d4-48f496819a3d)

Te invito a probarlo y te dejo un comment de dami que me parece excelente para aprender a manejar estas cosas https://github.com/sisoputnfrba/foro/issues/3781#issuecomment-2133708741

Saludos!

**Comment by FredeHG** [comment]
Te dejo el printf para no hacer lo que nos quejamos que nos hacen cuando mandan foto de codigo 🤪 

```C
    void* valor_recibido = "Hola";
    printf("puntero %p \n", valor_recibido);
```

```C
    void* valor_recibido = 1634496328;
    printf("puntero %p \n", valor_recibido);
```

**Comment by Ivanabete** [comment]
Muchas gracias por la respuesta!

Ese comment de Dami es excelente, ya lo había leído y me ayudó muchísimo a entender como manejar el memcpy, fue super útil para hacer la instruccion de MOV_IN (para guardarme las cosas en el registro).
Incluso fue gracias a ese comment que empecé a hacer estas pruebas, para ver qué funciona y qué no para poder implementar la escritura y la lectura en memoria.

Ahí probé los printf que me decís y me doy cuenta de qué falla. 


Si es que entendí bien: 

Para el caso del entero, yo necesito el contenido apuntado.
O sea, tendría que tener algo como: 
```
 uint32_t valor_entero = 1634496328;
 void* valor_recibido = &valor_entero;
```

Pero para el caso del char*, al ya ser un puntero en sí mismo, no necesito hacer eso:
`void* valor_recibido = "Hola";`

Nuestra función para leer lo recibido es la siguiente:
```
int read_buffer_tamanio (t_buffer* buffer){
	int size_data;
	memcpy(&size_data, buffer->stream, sizeof(int));
	return size_data;
}
void buffer_read(t_buffer* buffer, void* data) {

    int size_data = read_buffer_tamanio(buffer);
    memcpy(data, buffer->stream + sizeof(int), size_data);

    uint32_t nuevo_size = buffer->size - size_data - sizeof(int);
    void* nuevo_stream = malloc(nuevo_size);
    memcpy(nuevo_stream, buffer->stream + size_data + sizeof(int), nuevo_size);

    free(buffer->stream);
    buffer->size = nuevo_size;
    buffer->stream = nuevo_stream;
}
```

Entonces, sería trabajo de quien me mande los datos enviarme un void* con la forma `void* valor_recibido = &valor_entero;` o uno con la forma `void* valor_recibido = "Hola";` y no mi trabajo cuando los recibo de ver si le pongo el '&' o no, ¿correcto?
(Espero que se entienda la pregunta, hasta a mí me costó bastante entender qué es lo que quería preguntar)

**Comment by mefederico** [comment]
Si, pero tienen que tener cuidado que si haces &variable_local, en cuanto la función donde está declarada la variable local se muere y vas a tener problemas

Si hacen el memcpy antes que la función termine no van a tener problema, en tal caso la solución seria:

```C
uint32_t * variable = malloc(sizeof(uint32_t));
*variable = valor_uint32_t;
```

Saludos!

**Comment by Ivanabete** [comment]
Perfecto, creo que de momento, mi duda quedó resuelta.
Cualquier cosa reabro el issue.

Muchas gracias!
