### ISSUE TITLE
Duda sobre como cargar el file system

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3943]
Como va? ahi estuve leyendo que si los archivos de bitmap y de bloques ya existen no habria que pisarlos para poder seguir trabajando sobre eso. Pero podria pasar que en el config se levante el mismo file sysem con el mismo pahtbase pero se le cambien las dimensiones al archivo de bloques? Como se procede en estos casos?
Desde ya muchas gracias

**Comment by FredeHG** [comment]
Hola buenas!

No vamos a probar eso, no somos tan malos... Aún

Si lo quieren controlar por si hay un error en las pruebas o si cargan mal algún config para poder darse cuenta, con un lindo mensaje de error y terminar la interfaz estaría bien.

Saludos!
