### ISSUE TITLE
pequeña duda de enunciado sobre STDIN y STDOUT

### ISSUE THREAD

**Issue by nicolasvultaggio** [sisoputnfrba/foro#3944]
> IO_STDIN_READ (Interfaz, Registro Dirección, Registro Tamaño): Esta instrucción solicita al Kernel que mediante la interfaz ingresada se lea desde el STDIN (Teclado) un valor cuyo tamaño está delimitado por el valor del Registro Tamaño y el mismo se guarde a partir de la Dirección Lógica almacenada en el Registro Dirección.

> IO_STDOUT_WRITE (Interfaz, Registro Dirección, Registro Tamaño): Esta instrucción solicita al Kernel que mediante la interfaz seleccionada, se lea desde la posición de memoria indicada por la Dirección Lógica almacenada en el Registro Dirección, un tamaño indicado por el Registro Tamaño y se imprima por pantalla.

ese "tamaño" indicado por el registro tamaño, incluye al caracter nulo?

o sea, suponiendo que registro tamaño vale 5 y aca me surjen 3 opciones

1. En realidad nosotros tendremos que leer 4 caracteres asegurando el ultimo espacio para el carácter nulo?

2. Debemos leer 5 caracteres y reservar un byte mas de la cantidad pedida (o sea, en total, 6) para el carácter nulo?

3. Debemos leer 5 caracteres, sin dar importancia al carácter nulo

**Comment by iago64** [comment]
Buenas! Cómo va?

Muy buena pregunta, pero la cosa es simple, si les pedimos que lean 20 bytes (o caracteres en este caso), tienen que leer 20 bytes y guardar 20 bytes en la memoria y va a ser problema del STD_OUT de cuando les digamos que escriban el reservar 21 y agregar el `'\0'`  al final.

Saludos.-

**Comment by nicolasvultaggio** [comment]
esa resolucion no podría causar que se escriba en un espacio que no le corresponde al proceso? como previamente se indico  aquí  https://github.com/sisoputnfrba/foro/issues/3863#issuecomment-2163016424 se supone que antes de delegar a STDOUT, deben calcularse cuantas paginas en total deberían escribirse, ahora, de esta forma STDOUT no podría escribir el '\0' en una pagina que no le pertenece? Creo que esto tendría solución si se considera este byte "de más" a la hora de calcular cuantas direcciones lógicas se escribirán

**Comment by iago64** [comment]
Buenas!

Creo que me expresé mal y por eso la confusión, lo que yo decía es que le pidas a la memoria el tamaño que te indican, por ej 4 bytes para leer el `HOLA`, pero despues para imprimirlo por pantalla lo copies en un buffer de 5 bytes cosa de poder agregarle el `\0` y que no vuele por los aires.

Saludos.-

**Comment by nicolasvultaggio** [comment]
claro, entonces, para aclarar, no escribimos el byte '\0' en memoria, solo lo incluimos a la hora de escribir por pantalla

**Comment by iago64** [comment]
Exacto :)

**Comment by nicolasvultaggio** [comment]
muchas gracias capo, me resolviste muchas dudas, buen finde!
