### ISSUE TITLE
Log minimo de memoria

### ISSUE THREAD

**Issue by GonzaloFernandez20** [sisoputnfrba/foro#3945]
Buenas, como van?
En el enunciado uno de los logs minimos de memoria es el siguiente:

**Creación / destrucción de Tabla de Páginas**: “PID: <PID> - Tamaño: <CANTIDAD_PAGINAS>”

1) Queria saber qué tomamos por creación, porque como tal la tabla de paginas se crea una vez y vacía entoces <CANTIDAD_PAGINAS> seria 0.  Estaría bien eso?

 2) Tambien se debería mostrar cada vez que cambia la cantidad de paginas?

3) Despues para la destruccion tambien sería solo cuando se elimina el proceso? y entonces <CANTIDAD_PAGINAS> seria las paginas que tenia la tabla antes de destruirse?

**Comment by GonzaloFernandez20** [comment]
Y una duda mas, en el caso de que en un resize no haya que aumentar ni disminuir tamaño. Como un ejemplo que se dio en un issue previo: Paginas de 4 bytes, primero hago un resize(10) y después un resize(12). en ambos casos la cantidad de paginas queda en 3.
En este caso ni el log de ampliación ni reducción se aplicarían, no? Que se haria en este caso?

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Si, cuando la crean es 0 ese log medio que no nos preocupa, pero nos importa el final cuando la destruyen.

2.- No, solamente en la creación y destrucción, nosotros ya tenemos las cuentas armadas de cuanto deberían dar esos logs.

3.- Exacto, son las páginas al momento de limpiar la tabla y son todas las páginas que tenia reservadas el proceso al momento de eliminarse.

4.- Los logs de ampliación / reducción reciben el tamaño no la cantidad de páginas, asi que si, esos logs tienen que estar.

Saludos.-

**Comment by GonzaloFernandez20** [comment]
Hola, gracias por la respuesta, nos quedo una duda respecto a lo ultimo:

"Los logs de ampliación / reducción reciben el tamaño no la cantidad de páginas, así que si, esos logs tienen que estar."

Sabemos que el log te muestra el tamaño a reducir o ampliar, es decir, una diferencia respecto al valor actual. Pero en el caso de que no tenga que reducir ni ampliar porque el tamaño pedido es equivalente al que ya tiene. Que se debe mostrar en ese caso?
O sea en el ejemplo anterior el tamaño del proceso es 12, pero cuando yo hago un resize(12), no modifica nada porque ya tenia ese valor por el resize(10) previo.

**Comment by iago64** [comment]
No vamos a probar el caso de un resize del mismo tamaño del proceso.

Saludos.-

**Comment by GonzaloFernandez20** [comment]
Muchas gracias por la respuesta!
