### ISSUE TITLE
Se me rompe el Log_Info en una situación puntual.

### ISSUE THREAD

**Issue by DanielKesel** [sisoputnfrba/foro#3946]
Holaa cómo están?
Estoy teniendo un problema con un log_info que se me rompe y me arroja la consola el error:  **free(): invalid pointer**
El problema está únicamente luego que la CPU lea y ejecute la instrucción de STDOUT.
El flujo nuestro es el siguiente:

1. Cpu envía PC a memoria en la linea abajo hay un log_info(logger, "PC enviado") 
2. Memoria se fija que instrucción corresponde al la posición del PC y le envía la instrucción STDOU_WRITE registro1 registro2
3. CPU lo recibe y la ejecuta.
4. CPU le envía a Kernel
5. Kernel le avisa a la IO (con todas sus validaciones etc)
6. IO verifica si la puede ejecutar y le pide a memoria lo que tiene que leer por consola en tal dirección y tal tamaño
7. Memoria se lo envía a la IO
8. IO lo imprime por pantalla.

En el punto 4, luego que CPU le envía a kernel la instrucción, ahí la cpu sale de la ejecución y sigue con su ciclo de instrucciones. 
Cuando la CPU vuelve a pedir la insturcción con el siguiente PC, al entrar en el log_info se rompe y me tira **free(): invalid pointer** ABORTED.

Me estoy rompiendo la cabeza y no encuentro como solucionarlo. Solo tira ese error luego de leer la instrucción STDOUT y no con otra.

Por favor confirmenme si necesitan que les pasé algún segmento de codigo, por el momento quizá pueden tirarme un centro y lo pueda resolver.

Les paso print de pantalla de como se ve la consola ejecutando los 4 modulos (kernel, cpu, memoria y 1 sola instancia de IO).

![image](https://github.com/sisoputnfrba/foro/assets/82064789/a57c85a5-fb05-4a46-bce3-837610cd13f7)

Muchas gracias!

**Comment by DanielKesel** [comment]
PD: No usamos VALGRIND

**Comment by iago64** [comment]
Usen Valgrind y si no entienden el output pasenlo en texto

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Me sumo solo para pedirles encarecidamente que antes de subir un issue usen el debugger de VSCode y también Valgrind ya que son herramientas que les proveen información muchísimo más valiosa que ejecutar todo desde consola.

Sin ellas, es imposible que puedan garantizar que realmente el problema está ocurriendo en un `log_info`, porque de hecho es imposible saber en qué línea ocurrió el error. Los ayudantes no somos seres especiales que pueden adivinar qué está mal en su código si ni siquiera nos saben decir en qué línea está ocurriendo el error y el contexto del mismo.

En base a esto, porfa abran un nuevo issue una vez hayan agotado estas instancias previas.

Saludos
