### ISSUE TITLE
Se resuelven peticiones de IO mientras esta detenida la planificacion? 

### ISSUE THREAD

**Issue by Lisandrogq** [sisoputnfrba/foro#3947]
Buenass 
Que debe suceder en el caso en que detenemos la planificacion y hay varios procesos bloqueados por una IO? Planteo 2 alternativas

1.  Nuestra implementacion: cuando el kernel sea notificado de que termino una IO, este intentara desbloquear al proceso antes de envíar al siguiente, como la planificacion esta detenida, no se envíara nada(hasta q se desbloquee).

2. Esta es mas rebuscada, pero puede cumplir con la "definicion" de detener planificacion: al ser notificado por el fin de una IO, si la planificacion se encuentra detenida, no desbloquearía al proceso pero si enviaría al siguiente a utilizar la io. Ambos procesos seguirían en blocked, pero cuando se reanude la planificacion, irían automaticamente a ready.

La segunda alternativa la veo muy dificil de implementar, por eso pregunto, es correcta la primera?

**Comment by RaniAgus** [comment]
¡Buenas! Su implementación (la 1) es la correcta, ya que cada dispositivo solamente puede atender a un proceso a la vez. Si se pausa la transición de dicho proceso a READY, no debería enviarse un siguiente ya que todavía hay uno en BLOCKED ocupando dicha interfaz. Saludos

**Comment by Lisandrogq** [comment]
Genial, gracias
