### ISSUE TITLE
duda con resize

### ISSUE THREAD

**Issue by mSpadoni** [sisoputnfrba/foro#3948]
hola buenas tardes, estab viendo en unos issues que si voz haces un resize(10) y luego de 12 te quedan la misma cantidad de paginas (en el caso de paginas de 4bytes), pero el tamaño del proceso en el caso de del primer resize va a ser 10 y no 12? y en el caso que sea 10, significa que el el proceso solo puede ocupar 10bytes en la memoria continua y hay fragmentación interna?

desde ya muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

El proceso va a ocupar N páginas y si, va a tener fragmentación interna a menos que en las pruebas justo se de que el resize ocupe la página al completo, pero eso no es ningun problema, ya que uds le asignan el frame completo al proceso.

Saludos.-
