### ISSUE TITLE
Consulta requisitos: Checkpoint 3

### ISSUE THREAD

**Issue by LucianoKremer** [sisoputnfrba/foro#3949]
Hola! Buenas Tardes.
Quería consultar si las funcionalidades de la TLB están incluidas dentro de lo solicitado en el checkpoint 3, así ya puedo realizar el tag (La TLB ya la tenemos programada pero nos falta teastearla y probarla con varios casos).
Saludos!

**Comment by LucianoKremer** [comment]
Por otro lado también quería consultar si la TLB es única por proceso o se comparte entre los mismos.

**Comment by iago64** [comment]
Buenas! Cómo va?

Para el check no vamos a ejecutar pruebas asi que aunque les falte testearla pueden mandar el tag :)
Respecto a los reemplasos, capaz nos quedo muy al final del último parrafo, peor citando al enunciado:

> Al momento de obtener el número de página se deberá consultar en la TLB si se tiene la información de la misma. En caso afirmativo (TLB Hit) se deberá devolver la dirección física (o frame) correspondiente, en caso contrario, se deberá informar el TLB Miss y se deberá consultar a la memoria para obtener el frame correspondiente a la página buscada. Por último, se agregará la nueva entrada a la TLB, **si la misma se encuentra llena se deberá reemplazar siguiendo el algoritmo configurado pudiendo elegir como víctima cualquier otra entrada (incluso de otro proceso).**

De lo remarcado en negrita se supone (o al menos nosotros suponemos) que se entendía que la TLB es compartida y el reemplazo es global.

Saludos.-

**Comment by LucianoKremer** [comment]
A buenisimo, entonces esta bien como la modele. Ya a la noche hacemos el tag!

**Comment by iago64** [comment]
Excelente, si la duda esta resuelta, no se olviden de cerrar el issue :)

Saludos.-
