### ISSUE TITLE
Error en el documento de pruebas

### ISSUE THREAD

**Issue by ManuelGarciaF** [sisoputnfrba/foro#3950]
Buenas, en esta parte del documento de pruebas (prueba de memoria y TLB), no se supone que los comandos digan `INICIAR_PROCESO /scripts_memoria/MEMORIA_n` ?

 ![image](https://github.com/sisoputnfrba/foro/assets/46934491/8bb08277-f0b4-49b8-823f-361d56508c65)

**Comment by RaniAgus** [comment]
¡Buenas! Es correcto, ya fue corregido, gracias :D

**Comment by ManuelGarciaF** [comment]
perfecto graciass
