### ISSUE TITLE
Logs cambio de estado

### ISSUE THREAD

**Issue by papiness77** [sisoputnfrba/foro#3951]
Buenas, tenia la duda para que cambios de estado hay que hacer este log:
Cambio de Estado: “PID: <PID> - Estado Anterior: <ESTADO_ANTERIOR> - Estado Actual: <ESTADO_ACTUAL>”

Porque algunos de los otros logs de kernel transminten ya la informacion de algunos estados, como el de motivo de bloqueo. Saludos

**Comment by RaniAgus** [comment]
¡Buenas! El log de cambio de estado se debe imprimir ante cualquier cambio de estado. Saludos
