### ISSUE TITLE
Tamaño en bloques al crear un archivo

### ISSUE THREAD

**Issue by Lisandrogq** [sisoputnfrba/foro#3952]
Buenas, traigo una pequeña cosita que me hace ruido respecto a la creacion de archivos:

> **Creación de archivos**
Al momento de crearse un archivo, va a comenzar ocupando un bloque del FS aunque su tamaño sea 0 y luego el mismo se podrá extender o disminuir por medio de de la función IO_FS_TRUNCATE.

Porque el tamaño es 0 y no 1? si tuviera dos bloques, su tamaño sería 1? 
La posible respuesta que se me ocurre es que si tenes un bloque asignado, tu tamaño puede ser 0 o 1, dependiendo si recien fuiste creado sin previo IO_FS_TRUNCATEo si ya te hicieron IO_FS_TRUNCATE

**Comment by mefederico** [comment]
Hola buenas! 

El tamaño del archivo se mide en bytes

Saludos!

**Comment by Lisandrogq** [comment]
Aaah genial, yo me había quedado con lo que ví en clase, donde el FCB tenia(para asginacion continua) el bloque inicial y la cantidad de bloques
Gracias!!
