### ISSUE TITLE
Memoria: casos excepcionales en el acceso a espacio de usuario

### ISSUE THREAD

**Issue by facundo-gs** [sisoputnfrba/foro#3954]
<p>Buenas tardes,</p>
<p>Tenemos dos preguntas sobre el comportamiento del sistema en relación al acceso al espacio de usuario que no parecen haber surgido en los issues:</p>
<ol>
  <li>Escritura: Podría ocurrir que el dato a escribir exceda el tamaño asignado al proceso? <br>Según el issue: #3731, entendemos que esto no debería suceder. Podrían confirmarlo?</li>
  <li>Lectura: Es posible que una lectura exceda el espacio de usuario? En caso afirmativo, ¿deberíamos proceder de alguna forma en particular?</li>
</ol>

Gracias!

**Comment by mefederico** [comment]
Hola buenas! 

1. No va a pasar, si igualmente quieren controlarlo, tiren un out of memory
2. No, no va a pasar. 

Cuando digo que no va a pasar, me refiero a que nuestros programas van a usar direcciones lógicas validas y si ustedes hacen bien las traducciones a direcciones físicas todo va a funcionar correctamente. Si hacen mal la traducción por lo que sea, les puede pasar que se pasen, pero ese caso corre por su cuenta

Saludos!
