### ISSUE TITLE
Sobre cómo levantar el pathbase DIALFS

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3955]
Buenas! La duda es si los directorios del pathbase se deben crear antes de cada ejecución o si se crean en tiempo de ejecución. Por ejemplo si quiero que mi pathbase sea /home/utnso/tpcito/entradasalida/fs

Y además quiero que los archivos de metadata se guarden en otro directorio /home/utnso/tpcito/entradasalida/fs/archivos

Estos directorios podrían no existir? O siempre van a estar creados pre ejecución?

Muchas gracias!

**Comment by mefederico** [comment]
Hola buenas!

En la primera ejecución no van a existir, si ya existen ustedes tienen que poder leerlos y trabajar con los mismos

Saludos!
