### ISSUE TITLE
Detener planificación y finalizar proceso

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3956]
Buenas, en nuestro tp cuando detenemos la planificación se detienen todas las transiciones, a menos que se finalice un proceso con el comando que este en NEW o READY, para BLOCKED pasa lo mismo si la interfaz no es la que esta utilizando la interfaz en ese momento, y en execute SI se espera  a iniciar la planificación nuevamente para tratar el motivo de interrupción por usuario.
Basicamente las transiciones que ocurren con la plani detenida cuando se finaliza un proceso desde consola son:
-COLA NEW -> EXIT
-COLA READY -> EXIT
-COLA BLOCKED -> EXIT si no está usando la interfaz, si la está usando se espera a que termine y a que se inicie la planificación nuevamente, parecido a la situación de execute.

¿Esto estaría bien? ¿O es algo importante que debemos corregir?

**Comment by iago64** [comment]
Buenas! Cómo va?

Esta bien como lo implementaron.

Saludos.-

**Comment by rood8592** [comment]
Buenas, ahora nos surgio una duda. En las pruebas preliminares cuando hicimos la prueba de deadlock sin detener la plani ocurria lo esperado, que los otros procesos continuaban. Deteniendo la plani, cuando ocurria el deadlock también , lo que pasa es que las transiciones de los procesos bloqueados a ready se hacian con la plani detenida, esto estaría mal?

En resumen: 

Sin detener la plani: Ocurria un deadlock, finalizabamos un proceso y seguian las otros.

Deteniendo la plani luego del deadlock: El proceso finalizado pasaba a exit y los bloqueados pasaban a ready con la plani detenida y hasta ahí llegaba la cosa hasta que volvieramos a activar la plani.

**Comment by iago64** [comment]
Buenas! Cómo va?

Las pruebas son preliminares, eventualmente van a faltar mas pruebas de cara a la entrega final, no se olviden de eso.
Aclarado lo anterior, esta bien que puedan finalizar sin detener, de hecho en la prueba no les pedimos que detengan la planificación, si les funciona también con la planificación detenida es un plus pero que no nos preocupa testear.

Saludos.-

**Comment by rood8592** [comment]
Pero entoces, no deberia preocuparnos que, luego de ocurrido el deadlock, deteniendo la planificación, cuando finalizamos un proceso y este libera sus recursos, los otros procesos ,que estaban en deadlock junto a él, realizen su transición a la cola de READY con la planificación aún detenida?

**Comment by iago64** [comment]
Buenas! Cómo va?

No, no se tienen que preocupar.

Saludos.-

**Comment by rood8592** [comment]
Ok, gracias.
