### ISSUE TITLE
Duda sobre entrada-salida STDIN

### ISSUE THREAD

**Issue by moracontreras** [sisoputnfrba/foro#3957]
Hola! 
En mi código había hecho que entrada-salida le pida al alumno que ingrese un texto mediante su consola, io lo lee y se lo pasa a memoria. Sin embargo, hoy en el soporte me dijeron que estaba errada, que el texto debe ingresarse a través de la consola de kernel. Lo que no me quedó claro es si es a partir de la consola normal o si es con la consola interactiva. 
Les dejo el enunciado.
>Las interfaces STDIN no van a esperar ninguna unidad de trabajo, ya que las mismas van a quedarse esperando que el alumno ingrese un texto por teclado. Este texto se va a guardar en la memoria a partir de la o las direcciones físicas indicadas en la petición que recibió por parte del Kernel.

Desde ya, muchas gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

El texto lo tienen que ingresar en la terminal donde este corriendo el proceso de IO_STDIN, por lo que lo que tenías implementado está bien, debió ser un tema de un mal entendido.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @moracontreras! ¿Quedó clara la respuesta de Dami? Saludos

**Comment by moracontreras** [comment]
> ¡Buenas @moracontreras! ¿Quedó clara la respuesta de Dami? Saludos 

Hola! Si, perfecto, muchas gracias ☺️

**Comment by RaniAgus** [comment]
¡Buenísimo! Recuerden que si la duda ya fue resuelta pueden cerrar el issue 👮🏻‍♂️
