### ISSUE TITLE
Error al correr sin valgrind y sin errores con valgrind

### ISSUE THREAD

**Issue by DanielKesel** [sisoputnfrba/foro#3958]
Hola que tal? en el issue https://github.com/sisoputnfrba/foro/issues/3946 me animaron a ponerme a tiro con Valgrind para detectar donde y por qué podría estar teniendo el problema "free invalid pointer". El problema que tengo ahora es que aunque no lo crean, cuando lo corro con Valgrind no me tira el error y el programa se ejecuta correctamente, me río para no llorar.
Ya no se que hacer.

Saludos!

**Comment by f-and** [comment]
Buenas! Cuando decís que corrió sin error, no te apareció nada fuera de lo común? Fíjate que Valgrind debería avisarte ante cualquier error posible, lo corriste con todas las variables indicadas en la [guía de Valgrind](https://docs.utnso.com.ar/guias/herramientas/valgrind)?
De paso fíjate que hay una opción de guardar el log en un archivo txt, si podes pasalo asi tenemos mas info de lo que te ocurre.

**Comment by DanielKesel** [comment]
No me apareció nada te juro. Si corrí todo con valgrind --track-origins=yes --leak-check=yes --log-file=log_valgrind.txt.
Te paso el archivo de la respuesta de valgrind de la CPU (que es donde tenía el problema)
[VALGRIND_CPU.txt](https://github.com/user-attachments/files/15855584/VALGRIND_CPU.txt)

**Comment by DanielKesel** [comment]
Perdón o sea cuando digo que no apareció nada me refiero que no me apareció nada relacionado con el error de invalid pointer que tengo cuando lo corro sin valgrind, después obvio que si el log de valgrind me arroja algunos memory leaks.

**Comment by iago64** [comment]
Buenas! Cómo va?

Antes que nada, el siguiente mensaje va a leerse muy muy mala onda, pero quiero que sepas que es todo lo contrario.

Dicho lo anterior: El invalid pointer como tal no lo vas a tener en Valgrind, ya que Valgrind entiende que la cagaste con un puntero, te lo va a "parrchear" en la ejecución y en su lugar te va a dar la info de todos los lugares en donde metiste la pata hasta el cogote, por eso si revisas el archivo que pasaste tenemos:

- 9 [`Invalid write of size`](https://docs.utnso.com.ar/guias/herramientas/valgrind#invalid-write-of-size)
- 14 `Invalid read of size`
- 11 [`Conditional jump or move depends on uninitialised value`](https://docs.utnso.com.ar/guias/herramientas/valgrind#conditional-jump-or-move-depends-on-uninitialised-values)
- 3 `Use of uninitialised value of size`

Todas esas cosas son potenciales problemas que tenes en tu código y que te pueden desembocar en algo mas jodido como ser un invalid pointer o un segment fault, con lo cual, primero que nada armate de paciencia porque esto va a se un trabajo largo, empeza a **revisar y corregir** uno por uno los errores, de los cuales te deje los links de la guía de Valgrind, el de invalid write podes usarlo también para los invalid read. Los de `Use of uninitialised value of size` también son graves, pero posiblemente vengan de la mano de alguno de los otros.

Algo importante, en el output de valgrind tenes exactamente la línea de código en la cual haces el llamado de la función que esta explotando, por ejemplo `by 0x10CA1B: executeOperations (operations.c:179)` y con eso podes usar el debugger para poner un breakpoint en ese punto y ver que valores tenes en las variables.

Cuando Fede te dijo que veas la guía no fue para que nos tires el output de Valgrind sin analizarlo, la idea es que veas el output, veas donde te dice que falla y si no podes resolverlo con la guía ahi si nos digas:

_Che tengo este <Inserte error de valgrind> que me lo marca en la siguiente parte del código <Inserte snippet de código copy-pasteado> y me cuesta entender el origen del problema_. 

Al final del día uds son quienes conocen su código, saben que quisieron hacer en las funciones y los ayudantes estamos para ayudarlos (valga la redundancia) a que aprendan a valerse por su cuenta, si los llevamos de la mano y les arreglamos los problemas, el problema en serio va a venir en las últimas 96 / 120hs antes de las entregas cuando sean 50 o 60 grupos corrigiendo errores del TP y donde por mas buena voluntad que le pongamos todo el equipo de ayudantes, no vamos a poder contestarles todas las dudas porque el tiempo y los ayudantes somos recursos finitos, entonces el hecho de que se puedan valer por sus propios medios va a marcar la diferencia entre arreglar un problema, seguir con las pruebas y finalmente aprobar el TP o quedarse estancados y no poder presentar el TP y en caso de que sea la última fecha, que tristemente terminen recursando.

Saludos.-

**Comment by DanielKesel** [comment]
Buen día @iago64, el problema de raiz nuestro es que no empezamos a usar Valgrind desde el inicio del TP, de hecho lo empecé a usar ayer, y si bien no es algo dificil de usar (y aparte está la guía), como todo, lleva su "tiempito de práctica". Y como yo no sabía que Valgrind "parcheaba" el error, vi los mensajes de salida pero no me di cuenta de ese que vos me marcás, asi que obviamente te agradezco por haberte tomado el trabajo de leerlo todo y marcarme el error puntual. Y respecto a todo lo que dijiste después no lo sentí mala onda, me parece bien y gracias por la sinceridad. Ahora de acá a las entregas finales tenemos que ponernos todos a tiro con valgrind y solucionar todos los memory leaks y demás errores.

Ahora voy a ir probando eso que me dijiste y ante cualquier consulta abro otro issue.

Muchas gracias!
Saludos
