### ISSUE TITLE
Dudas varias de CPU sobre instrucciones, lógica y comunicación con memoria. 

### ISSUE THREAD

**Issue by tomassagrada** [sisoputnfrba/foro#3959]
Hola buenas tardes, tuve que cambiar como pensaba muchas cosas hoy después de enterarme de algunas cosas gracias al soporte, y me surgieron varias dudas de si lo que estoy pensando ahora es correcto y algunas otras dudas:

1_El tamaño de las paginas se lo pido a memoria y lo guardo al principio?
2_ esta bien esta análisis?: me llega la dirección lógica, de ahí saco el numero de pagina que es con (DL/Tamaño de las paginas) me va a dar un numero, este lo resto a la DL y eso seria el offset/despl. Ese numero de pagina yo necesito el NRO marco del mismo, para eso mando la pagina a la TLB y averiguo. Si yo tengo ese numero de marco TLB HIT y lo devuelvo al MMU. si yo no lo tengo TLB MISS y le mando a memoria el numero de pagina del que necesito el marco. con ese NRO de marco, tamaño de marco (es el mismo que el tamaño de pagina) y el offset/despl calculo la DF de la siguiente manera DF= Nro Marco * Tamaño Marco + offset/despl.
Ahora, existe un caso en el que yo no voy a enviar una sola DF, ya que no entra todo el dato que escribo en una sola pagina. para eso yo antes de empezar el calculo de DF averiguo si lo que yo voy a escribir entra en una pagina (comparo el tamaño de pagina con la longitud del string, además tengo en cuenta donde se empieza a escribir de esa pagina), en el caso de que lo que se escriba ocupe mas de el tamaño de la pagina o que necesite mas de una pagina por alguna razón (ej, podría ser que empiece a escribir en la mitad de una de las paginas y lo que escriba si entraría en toda una pagina pero no escribiéndolo a partir de la mitad, así que para el calculo tengo que tener en cuenta el offset también) voy a calcular mas de una dirección física, calcularía la de la pagina "base" y la de las continuas necesarias para que entre todo lo escrito. 
3_ Cuando yo envió la dirección física a memoria y es el caso en que tengo mas de una dirección física debería mandarle 3 paquetes distintos cada uno con la dirección física y separar el string para cada paquete, o enviar todo en un paquete incluidas las 3 DF y el string a escribir?
4_ leí el issue "duda MOV_IN" en el cual se hablaba de la parte en la que por ahí lo que se lee no seria solo una DF, pero sigo sin entender como sabría CPU que tiene que enviar mas de una DF, ya que recibe la DL donde debería leer pero que es lo que le indica cuanto va a tener que leer?
5_ Estas preguntas surgen que hoy por el soporte me di cuenta que muchas de las cosas que había pensado eran erróneas (por eso también quiero preguntar para que no me vuelva a pasar), o sea estaba pensando mal las instrucciones para comunicarme con memoria, que es conveniente que haga con respecto al TAG: 
	1_ taggear el código hecho "mal" con comentarios sobre las cosas que tengo y estoy corrigiendo.
	2_ taggear el código con las cosas mal hechas comentadas en los cambios a hacer y las correcciones a la mitad que estoy haciendo 
            (o sea pushear las correcciones que estoy haciendo mas allá de que hayan cosas sin terminar de corregir).
	3_ taggear con las cosas mal simplemente.
(lo errores son sobre todo de estructura teórica por lo tanto el cambio va a ser sobre todo interno. o sea la estructura de como esta todo armado esta "bien" pero tengo que cambiar la parte de cada instrucción teniendo en cuenta que el error estaba sobre todo en las mismas)

**Comment by tomassagrada** [comment]
Perdón, una cosa que me di cuenta sobre la pregunta 4 puede ser que sea con el despl?

**Comment by mefederico** [comment]
Hola buenas!

1. Si.
2. La cuenta del offset/desplazamiento de la DL te falto multiplicar el numero de pagina * tam_pagina. El resto, si
3. Como prefieran, pero tienen que hacer un retardo por escritura/acceso.
4. Por favor, si vas a citar un issue pone el link. Va a leer la cantidad de bytes del tamaño del registro donde tiene que guardar el dato, si es de 1 byte, solo va a leer de una DF, pero si es de 4 bytes y está al final de una página va a tener que leer 2 DF.
5. El lo que taggeen marca un avance, ese código no es ni mucho menos necesario que sea el final, incluso media hora antes de la entrega los puede poseer Dennis Ritchie y re codear todo el TP (seria sospechoso). Por lo que si no tienen tiempo de arreglar todo ahora y quieren dejarse comentarios de lo que falta y taggear eso va a estar ok. Si quieren avanzar lo que puedan y taggear eso también va a estar ok.

Espero haberte ayudado

Saludos!

**Comment by tomassagrada** [comment]
buenas no me di cuenta lo de citar el issue perdón. Me quedo una duda sobre la pregunta 4, o sea yo voy a tener dos tamaños posibles entonces no? por que los registros pueden ser solo de 2 tipos distintos.

**Comment by mefederico** [comment]
Sin problema

1. Si, de 1 byte o de 4 bytes.

2: 

Si, a partir de una dirección lógica tienen que conseguir las distintas direcciones físicas.
El offset solo te va a importar en la primer dirección, en las siguientes vas a empezar en el inicio de la pagina/marco

Te dejo un issue donde se hablo del tema https://github.com/sisoputnfrba/foro/issues/3877 especialmente estos 2 comments https://github.com/sisoputnfrba/foro/issues/3877#issuecomment-2156441267 https://github.com/sisoputnfrba/foro/issues/3877#issuecomment-2156780059

Saludos!

**Comment by tomassagrada** [comment]
Perfecto, voy a revisar el issue que me dejaste y tratar de ir trabajando con todo. mil gracias
