### ISSUE TITLE
Log de CPU

### ISSUE THREAD

**Issue by abrilvallecillo** [sisoputnfrba/foro#3960]
Buenas tardes, tenemos dudas con uno de los log de CPU, con el que dice " Lectura/Escritura Memoria: “PID: <PID> - Acción: <LEER / ESCRIBIR> - Dirección Física: <DIRECCION_FISICA> - Valor: <VALOR LEIDO / ESCRITO>”. " ya que  no entendemos si hay que hacer uno de estos por cada dirección física, o solo por una.
Desde ya muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

Es un log por cada dirección física, por lo que si un dato va a 2 páginas diferentes, tienen 2 direcciones físicas diferentes y por lo tanto 2 logs.

Saludos.-

**Comment by GorinoManuel** [comment]
Hola, soy su compañero de grupo. Entonces si a ese dato necesita 2 páginas, lo que va a mostrar es el valor del dato completo?

**Comment by GorinoManuel** [comment]
Es decir, si el dato es muy grande y tiene que ocupar 2 páginas, al hacer este log para cada dirección física va a mostrar el dato completo?

**Comment by iago64** [comment]
Buenas! Cómo va?

Vas a tener 2 logs de las 2 traducciones, una para el "final" de la página N y otro para el principio de la página N+1.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @abrilvallecillo y/o @GorinoManuel! ¿Quedó clara la respuesta de Dami? Saludos

**Comment by GorinoManuel** [comment]
Hola si, nos quedó claro!

**Comment by RaniAgus** [comment]
¡Buenísimo! Recuerden que si la duda ya fue resuelta pueden cerrar el issue 👮🏻‍♂️
