### ISSUE TITLE
duda con string_split()

### ISSUE THREAD

**Issue by mSpadoni** [sisoputnfrba/foro#3961]
hola buenas noches, tengo una duda con string split, como hago para leer el elemento de una posición?? por ejemplo la 0

**Comment by mefederico** [comment]
Hola buenas!

Una cosa que me gusta de las commons es que tienen test! 
https://github.com/sisoputnfrba/so-commons-library/blob/d22eb0076cc863bcbb7edbdf47ef43e6d434ffc6/tests/unit-tests/test_string.c#L196

Ahí pueden ver como se usan y por consiguiente como están accediendo a cada elemento

Saludos!

**Comment by mSpadoni** [comment]
gracias
