### ISSUE TITLE
De donde salen las direcciones lógicas

### ISSUE THREAD

**Issue by joaquinbarreiro23** [sisoputnfrba/foro#3962]
Buenas, estoy viendo de hacer la parte de paginación y conectarla con el CPU, y para esto tengo que usar las direcciones lógicas, lo que no termino de entender es de donde salen estas mismas, en un issue anterior el #3872 dicen que " La DL no es más que un número (que en este trabajo viene como parámetro en la instrucción de pseudocódigo a ejecutar)", pero las instrucciones de ejemplo que veo en el TP son por ejemplo: SUM AX BX, SET BX 1, no veo donde este o donde se genere esta dirección lógica.

**Comment by mefederico** [comment]
Hola buenas! 

Voy a usar de ejemplo uno de los [scripts de prueba ](https://github.com/sisoputnfrba/c-comenta-pruebas/blob/main/scripts_memoria/MEMORIA_1)
```Assembly
SET AX 0
SET BX 1
SET CX 2
SET DX 3
SET EAX 0
SET EBX 32
SET ECX 64
SET EDX 96
RESIZE 128
MOV_OUT EAX AX
```

Como podes ver se hace `SET EAX 0` y `SET AX 0`, luego se hace `MOV_OUT EAX AX`

Bueno la dirección lógica de este ejemplo, es 0! 

Saludos!

**Comment by joaquinbarreiro23** [comment]
Muchas gracias!! ahí con eso lo pude entender
