### ISSUE TITLE
Resultados esperados en memoria

### ISSUE THREAD

**Issue by FacundoStancanelliUTN** [sisoputnfrba/foro#3963]
Buenas! Que tal! Me surgio una duda viendo el documento de pruebas, mas especificamente la seccion de Memoria. Cual ese el resultado esperado cuando ejecutamos INICIAR_PROCESO /scripts_memoria/MEMORIA_2?

El valor que tiene que traer el log leer es: 
[INFO] 21:50:07:519 LOG_OBLIGATORIO_CPU/(108868:109122): PID: 1 - Acción: LEER - Dirección Física: 30 - Valor: 10
Y deben haber dos logs de escrituras (en diferentes direcciones fisicas)?

Desde ya gracias.
Saludos!

### 👎 Comportamiento obtenido

[INFO] 21:48:30:716 LOG_OBLIGATORIO_CPU/(107669:107962): PID: 2 - FETCH - Program Counter: 0
[INFO] 21:48:30:716 LOG_OBLIGATORIO_CPU/(107669:107962): PID: 2 - Ejecutando: RESIZE - [128 ]
[INFO] 21:48:30:717 LOG_OBLIGATORIO_CPU/(107669:107962): PID: 2 - FETCH - Program Counter: 1
[INFO] 21:48:30:717 LOG_OBLIGATORIO_CPU/(107669:107962): PID: 2 - Ejecutando: SET - [DX 30 ]
[INFO] 21:48:30:717 LOG_OBLIGATORIO_CPU/(107669:107962): PID: 2 - FETCH - Program Counter: 2
[INFO] 21:48:30:717 LOG_OBLIGATORIO_CPU/(107669:107962): PID: 2 - Ejecutando: SET - [AX 4 ]
[INFO] 21:48:31:722 LOG_OBLIGATORIO_CPU/(107669:107962): PID: 2 - FETCH - Program Counter: 3
[INFO] 21:48:31:722 LOG_OBLIGATORIO_CPU/(107669:107962): PID: 2 - Ejecutando: MOV_OUT - [DX AX ]
[INFO] 21:49:52:351 LOG_OBLIGATORIO_CPU/(108868:109122): PID: 1 - FETCH - Program Counter: 0
[INFO] 21:49:52:352 LOG_OBLIGATORIO_CPU/(108868:109122): PID: 1 - Ejecutando: SET - [EAX 0 ]
[INFO] 21:49:53:353 LOG_OBLIGATORIO_CPU/(108868:109122): PID: 1 - FETCH - Program Counter: 1
[INFO] 21:49:53:353 LOG_OBLIGATORIO_CPU/(108868:109122): PID: 1 - Ejecutando: SET - [EBX 10 ]
[INFO] 21:49:54:355 LOG_OBLIGATORIO_CPU/(108868:109122): PID: 1 - FETCH - Program Counter: 2
[INFO] 21:49:54:355 LOG_OBLIGATORIO_CPU/(108868:109122): PID: 1 - Ejecutando: SET - [EDX 0 ]
[INFO] 21:49:55:367 LOG_OBLIGATORIO_CPU/(108868:109122): PID: 1 - FETCH - Program Counter: 3
[INFO] 21:49:55:368 LOG_OBLIGATORIO_CPU/(108868:109122): PID: 1 - Ejecutando: SET - [ECX 1 ]
[INFO] 21:49:56:373 LOG_OBLIGATORIO_CPU/(108868:109122): PID: 1 - FETCH - Program Counter: 4
[INFO] 21:49:56:373 LOG_OBLIGATORIO_CPU/(108868:109122): PID: 1 - Ejecutando: SET - [DX 30 ]
[INFO] 21:49:57:376 LOG_OBLIGATORIO_CPU/(108868:109122): PID: 1 - FETCH - Program Counter: 5
[INFO] 21:49:57:376 LOG_OBLIGATORIO_CPU/(108868:109122): PID: 1 - Ejecutando: RESIZE - [60 ]
[INFO] 21:49:58:379 LOG_OBLIGATORIO_CPU/(108868:109122): PID: 1 - FETCH - Program Counter: 6
[INFO] 21:49:58:379 LOG_OBLIGATORIO_CPU/(108868:109122): PID: 1 - Ejecutando: MOV_OUT - [DX EBX ]
[INFO] 21:50:07:519 LOG_OBLIGATORIO_CPU/(108868:109122): PID: 1 - Acción: ESCRIBIR - Dirección Física: 30 - Valor: 10
[INFO] 21:50:07:519 LOG_OBLIGATORIO_CPU/(108868:109122): PID: 1 - Acción: ESCRIBIR - Dirección Física: 0 - Valor: 10
[INFO] 21:50:07:519 LOG_OBLIGATORIO_CPU/(108868:109122): PID: 1 - FETCH - Program Counter: 7
[INFO] 21:50:07:519 LOG_OBLIGATORIO_CPU/(108868:109122): PID: 1 - Ejecutando: MOV_IN - [EAX DX ]
[INFO] 21:50:07:519 LOG_OBLIGATORIO_CPU/(108868:109122): PID: 1 - Acción: LEER - Dirección Física: 30 - Valor: 10
[INFO] 21:50:08:520 LOG_OBLIGATORIO_CPU/(108868:109122): PID: 1 - FETCH - Program Counter: 8
[INFO] 21:50:08:520 LOG_OBLIGATORIO_CPU/(108868:109122): PID: 1 - Ejecutando: SUB - [EBX ECX ]
[INFO] 21:50:09:533 LOG_OBLIGATORIO_CPU/(108868:109122): PID: 1 - FETCH - Program Counter: 9
[INFO] 21:50:09:533 LOG_OBLIGATORIO_CPU/(108868:109122): PID: 1 - Ejecutando: SET - [EAX 0 ]
[INFO] 21:50:10:535 LOG_OBLIGATORIO_CPU/(108868:109122): PID: 1 - FETCH - Program Counter: 10
[INFO] 21:50:10:535 LOG_OBLIGATORIO_CPU/(108868:109122): PID: 1 - Ejecutando: EXIT - []

**Comment by FacundoStancanelliUTN** [comment]
Tambien aprovecho y consulto si el log de ACCION: ESCRIBIR esta bien que aparezca dos veces con el valor: 10 (entiendo que si, pero quizas hay que ponerlo de otra manera)

**Comment by FacundoStancanelliUTN** [comment]
(tambien tener en cuenta que nos faltan algunos logs aun, pero la duda principal radica si en la parte de lectura y escritura de la variable es correcto el resultado)

**Comment by iago64** [comment]
Buenas! Cómo va?

En el caso del segundo script de memoria, es simplemente que pueden recuperar el valor que queda partido entre 2 páginas sin problemas.
Tene en cuenta que son pruebas preliminares, posiblemente en un futuro usemos ese valor para algún loop con JNZ y si recuperan mal el valor el loop se pase de rosca o peor, ni ejecute.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @FacundoStancanelliUTN! ¿Quedó clara la respuesta de Dami? Saludos

**Comment by FacundoStancanelliUTN** [comment]
Buenas como va! Perdon, no estuve con la compu este finde largo.
Gracias por la respuesta.
Consulta, pero el valor obtenido "10", en este caso, es correcto?

**Comment by RaniAgus** [comment]
¡Buenas! Esto lo pueden deducir siguiendo el script. Si yo guardo el valor `10` en EBX:

```
SET EBX 10
```
Luego lo dejo en memoria en una dirección:
```
MOV_OUT DX EBX
```

Y por último leo dicha dirección
```
MOV_IN EAX DX
```

Sí, está bien que valga `10`.

Saludos

**Comment by FacundoStancanelliUTN** [comment]
Impecable, gracias Agus!
Saludos.
