### ISSUE TITLE
Duda sobre la relación entre Kernel, Interfaces y el módulo de I/O

### ISSUE THREAD

**Issue by Joaquinnicolasrossi** [sisoputnfrba/foro#3964]
Buenas noches, con mi grupo tenemos una consulta sobre el manejo de I/O del Kernel, que deriva en una duda sobre la razón de ser del módulo de I/O como tal.

Según tenemos entendido, el módulo de I/O se encarga de leer los archivos de config que le llegan y en base a eso crear las interfaces con los datos pertinentes. Una vez hecho esto, las interfaces intentan conectarse al Kernel. Ahora bien, nosotros decidimos mandar desde el módulo de I/O el nombre de la interfaz y el tipo (para posteriores chequeos) hacia el Kernel, y el Kernel de su lado crea un hilo por cada interfaz que se le conecta y crea su propio struct de cada interfaz (con los campos que son de interés para el Kernel + los recibidos del módulo de I/O). Parecido a lo planteado en el issue #3721 

Llegados a este punto, no sabemos cómo seguir, ya que el Kernel es el que maneja el socket de conexión de las I/O y a la vez el que las "mantiene vivas", entonces según nuestra lógica cuando el CPU mande una instrucción para que una interfaz la realice, el Kernel tendría que manejar toda la lógica de la operación como tal (ejemplo: usleep(1000)).

### 📔 Adjunto código
```
// Este switch case ya esta dentro de su propio hilo de atender al modulo de I/O
case CREAR_INTERFAZ:
            t_buffer *buffer = recibir_buffer(socket_interfaz);
            char *nombre_interfaz = extraer_string_de_buffer(buffer);
            char *tipo_interfaz = extraer_string_de_buffer(buffer);

            pthread_t thread;
            int *socket_conexion_interfaz = malloc(sizeof(int));
            *socket_conexion_interfaz = accept(socket_escucha, NULL, NULL);

            t_manejo_io *args = malloc(sizeof(t_manejo_io));
            args->nombre = nombre_interfaz;
            args->tipo = tipo_interfaz;
            args->socket = (int) socket_conexion_interfaz;

            pthread_create(&thread, NULL, (void *)crear_interfaz, (void *)args);
            pthread_detach(thread);
            break;

```
```
void crear_interfaz (void* args) {

    t_manejo_io* datos_io = (t_manejo_io*) args;

    int fd_interfaz = datos_io->socket;
    char* nombre_interfaz = datos_io->nombre;
    char* tipo_interfaz = datos_io->tipo;

    t_interfaz_kernel *interfaz = malloc(sizeof(t_interfaz_kernel));
    t_list *cola_block = list_create();

    interfaz->nombre = nombre_interfaz;
    interfaz->tipo = tipo_interfaz;
    interfaz->socket = fd_interfaz;
    interfaz->cola_block_asignada = cola_block;
    pthread_mutex_init(&interfaz->mutex_asignado, NULL);

    pthread_mutex_lock(&mutex_lista_io);
    list_add(lista_io_conectadas, interfaz);
    pthread_mutex_unlock(&mutex_lista_io);

    // Aca es donde se tendria que quedar esperando a recibir una instruccion del kernel, 
    // pero el tratado de la instruccion tambien se realizaria aca mismo (modulo kernel) por nuestra logica
}
```

### 💭 Soluciones posibles (no estamos muy seguros)
1. Mandarle al modulo de I/O el socket de la conexion para que ese modulo se encargue del tratado de las instrucciones por cada I/O.
2. Plantearlo de otra forma completamente distinta que no se nos ocurre 😔

**Comment by mefederico** [comment]
Hola buenas! 

El modulo IO no sé encarga de crear interfaces ES una interfaz, cual? La que le diga el archivo de configuración y para tener varias simplemente tienen que ejecutar de nuevo el modulo con otro archivo de configuración y/o otra nombre

La parte del struct lo hicieron genial

Ahora porque el kernel debería hacer la lógica? 
Desde CPU se dan cuenta que tienen que resolver una instrucción de IO, le dan el contexto de ejecución al Kernel, el Kernel conoce las IO... Manden la instrucción a la IO que corresponde! 

Y está se encarga de ejecutar la lógica (sleep, FS, etc)

Espero que haya quedado un poco más claro

Saludos!

**Comment by Joaquinnicolasrossi** [comment]
Ahhhhh, creo que nos queda claro lo que tendríamos que hacer entonces. Pensamos que entonces en el lugar donde está mi comentario en el código (luego de crear la interfaz) debería haber un while 1 recv que esté esperando la respuesta de la I/O que habría terminado la instrucción que le mandamos previamente (desde otro lado donde manejamos la conexion con el cpu). Estaríamos yendo por buen camino?

**Comment by iago64** [comment]
Buenas! Cómo va?

La idea es que ese hilo que crean para "crear" la interfaz, ahora en lugar de hacer toda la lógica de las interfaces, lo que haga sea algo tan simple como mandarle los pedidos a la IO y quedarse esperando las respuestas para después mover los procesos de BLOCK a READY.

Saludos.-

**Comment by Joaquinnicolasrossi** [comment]
Clarisimo, muchas gracias a ambos!
