### ISSUE TITLE
Qué se almacena en MEMORIA?

### ISSUE THREAD

**Issue by MarianoAmirLuna** [sisoputnfrba/foro#3966]
Buenas nosotros en un principio entendimos que lo único que se tiene que guardar en memoria (en el void* de 4096bytes) tienen que ser todas las instrucciones asociadas al proceso, pero después nos empezaron a agarrar dudas si es que realmente estas van ahí o no, mi duda es que es lo se debe guardar en memoria? las instrucciones, los PCB's, los registros o los datos a medida que se van ejecutando las instrucciones en el programa.

**Comment by FredeHG** [comment]
Hola buenas!

La ultima es la correcta, a medida que se ejecutan las instrucciones hay algunas que hacen lecturas o escrituras en memoria. Como MOV_IN o MOV_OUT 

Saludos!

**Comment by MarianoAmirLuna** [comment]
Esta bien, gracias por aclarar nuestras dudas.
