### ISSUE TITLE
String cambia de valor

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#3967]
Hola buen dia. Tengo un problema con un string leido con config_get_string_value. La variable es esta y solo aparece en estos casos
![image](https://github.com/sisoputnfrba/foro/assets/112731246/2d1ac638-aa58-42a4-9991-367bf0d17e9b)
En mi tp, en el modulo de cpu tengo un archivo main.c y otro que es operaciones.c, los dos tienen su .h. La forma en que estan incluidos es asi: main.c incluye a main.h . Y main.h incluye a operaciones.h . Por otro lado, operaciones .c incluye a operaciones.h
Yo la declaracion la hice asi: defini la variable global char * en main.c porque es donde hago el config get string value, y despues hice el extern char * en operaciones.h. Lo defini asi porque en todos los otros casos que tuve que hacer algo parecido los tengo definidos asi y funciona. 
En main.c cuando leo el config, se guarda bien el string. 
![image](https://github.com/sisoputnfrba/foro/assets/112731246/45d8fcc7-a64a-4fc8-882f-57ac180430ea)
Pero cuando quiero hacer las comprobaciones en operaciones.c es como que se perdio el valor y ahora ya no esta el string.
Y eso hace que no funcionen las comprobaciones.
![image](https://github.com/sisoputnfrba/foro/assets/112731246/281db641-7747-466d-8505-bbfe1ed58719)

El strdup que hago es la solucion que encontre. Crear otro string que se declare en operaciones.c y que este declarado en operaciones.h como un extern char * Despues, en el main.c le hago el strdup y esto si funciona. Lo podria haber dejado asi porque funciona pero no se porque no funciono lo anterior y no se si es un problema mas grave. Desde ya muchas gracias

PD: el strdup no esta generando el problema, porque antes de poner eso ya estaba fallando

**Comment by RaniAgus** [comment]
¡Buenas! ¿En algún lado estás ejecutando `config_destroy()`?

Mi pregunta se debe a que el puntero devuelto por `config_get_string_value` pertenece a la estructura interna de `t_config`, por lo que si hacen `config_destroy()` van a liberar ese puntero.

Entonces, de ahí, tienen dos soluciones posibles:

1. Usar `strdup()`/`string_duplicate()` para obtener el valor:

```c
algoritmoTLB = string_duplicate(config_get_string_value(config, "ALGORITMO_TLB");
```

2. No destruir el config.

Saludos

**Comment by JoaquinCoaricona** [comment]
Hola buenas. Si, era el config. Muchas Gracias
