### ISSUE TITLE
Consulta sobre compactacion

### ISSUE THREAD

**Issue by MartoSimon** [sisoputnfrba/foro#3968]
Buenas, todo bien?

Teniamos una duda con respecto a la compactación, nosotros lo habíamos pensado hacer usando el bitmap y también teniendo un "soporte" con una lista de structs que tendria el nombre del archivo, el bloque inicial y el tamaño del archivo. La lista relacionaría el bitmap con el contenido de los archivos txt.

¿Se puede realizar esta implementación o tenemos que buscar otra forma?

Saludos!

**Comment by RaniAgus** [comment]
¡Buenas! Lo veo bien siempre y cuando recuerden mantener actualizada esa estructura con los archivos de metadata. De otra forma, los datos no persistirían luego de tirar abajo el módulo y levantarlo de nuevo, lo cual es justamente el propósito de contar con un módulo File System. Saludos

**Comment by MartoSimon** [comment]
Perfecto, muchas gracias.
Te hago una última consulta, porque estamos queriendo reducir los archivos con el truncar pero la cuenta no nos esta saliendo bien, ya que deberia de estar redondeando para arriba pero redondea para abajo (en este caso 180/64 da 2,8 y deberia redondear en 3 pero redondea en 2):

```c
int cantBloquesNuevo = ceil(tamanioNuevo/config.block_size);
log_debug(logger, "cantidad bloques nuevos %d %d %d",cantBloquesNuevo,tamanioNuevo,config.block_size );
```

y esto nos devuelve:
```c
[DEBUG] 15:21:56:817 ENTRADASALIDA/(25133:25133): cantidad bloques nuevos 2 180 64
```

**Comment by RaniAgus** [comment]
¡Buenas! Esto se debe a que el dividendo es un `int`, entonces el resultado de la división `tamanioNuevo / config.block_size` es convertido a `int` antes de pasárselo a `ceil()`.

La solución es hacer que `tamanioNuevo` sea un `double`, ya sea cambiando el tipo de la variable o haciendo el siguiente casteo:

```c
int cantBloquesNuevo = ceil(((double)tamanioNuevo) / config.block_size);
```

Saludos

**Comment by MartoSimon** [comment]
Buenisimo, nos funciona perfecto ahora.

Muchas gracias!
