### ISSUE TITLE
Posible memory leak en las commons

### ISSUE THREAD

**Issue by Lopez-AN** [sisoputnfrba/foro#3969]
Buenas, corriendo el valgrind para detectar posibles memory leaks, nos encontramos con este, el cual sospechamos que es producido por las commons, en particular con la funcion config_get_array_value.

Queriamos saber si efectivamente es asi, o estamos interpretando algo mal

![image](https://github.com/sisoputnfrba/foro/assets/15198397/ad2de4c6-407d-4cf1-bd68-ba5d50dc4187)

**Comment by RaniAgus** [comment]
¡Buenas! No, las commons no tienen un memory leak. Ustedes deben liberar el puntero devuelto por `config_get_array_value()` usando `string_array_destroy()`.

Ante cualquier duda sobre el uso de una función de las commons, les aconsejo revisar los [unit tests](https://github.com/sisoputnfrba/so-commons-library/blob/master/tests/unit-tests/test_config.c#L105).

Saludos

**Comment by Lopez-AN** [comment]
gracias, no habiamso visto esa funcion para liberar
