### ISSUE TITLE
BitArray en I/O DialFS 

### ISSUE THREAD

**Issue by nsantero** [sisoputnfrba/foro#3970]
Hola estuve leyendo el issue #3862 sobre el uso de bit array en memoria y me genero dudas sobre como usarlo en el caso de la interfaz DialFS. Por lo que entiendo del otro issue podemos usar un codigo como: 

```c
int cantidad_marcos = config_memoria->TAM_MEMORIA / config_memoria->TAM_PAGINA;

void* memoria_usuario = malloc (config_memoria->TAM_MEMORIA);

void* bitmap_memoria_usuario = malloc (cantidad_marcos/8);

t_bitarray* mapa_de_bits = bitarray_create_with_mode (bitmap_memoria_usuario, cantidad_marcos/8, LSB_FIRST);
```

para tener el manejo de esto en memoria. El tema es que en el enunciado dice que tenemos que tener dos archivos bloques.dat y bitmap.map:

"El primero va a ser nuestro archivo de bloques (bloques.dat) el cual va a ser un archivo de tamaño definido mediante 2 parámetros del archivo de configuración: BLOCK_SIZE y BLOCK_COUNT, y el tamaño del archivo va a ser BLOCK_SIZE * BLOCK_COUNT.
El segundo archivo va a ser un archivo que va a contener un bitmap (bitmap.dat) indicando que bloques se encuentran libres y que bloques se encuentran ocupados dentro de nuestro FS, cualquier implementación que no utilice un bitmap será considerada una implementación equivocada y por consiguiente no se aprobará esa entrega del TP.
"

Mi pregunrta es como puedo pasar a usar las funciones del commos trabajando con los bit array dentro de archivos.

**Comment by RaniAgus** [comment]
¡Buenas! Para ello les recomiendo investigar sobre el uso de la función [`mmap()`](https://man7.org/linux/man-pages/man2/mmap.2.html). Saludos

**Comment by RaniAgus** [comment]
¡Buenas @nsantero! ¿Les sirvió la respuesta? Saludos

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, si les quedó alguna duda pueden abrir uno nuevo referenciando éste. Saludos
