### ISSUE TITLE
Implementación FS

### ISSUE THREAD

**Issue by inaaranza** [sisoputnfrba/foro#3972]
Buenas! Tengo unas duda sobre la implementación del FS.

Al iniciar una i/o de tipo DialFS se debería ejecutar dentro del código funciones que creen archivos de bloques, bitmap y metadata? Osea, al ejecutar una i/o con interfaz DialFS ahí deberian aparecer esos 3 archivos? Cada i/o de tipo DialFS que se ejecuta debería también crear sus 3 archivos (bloques, bitmap, metadata)

Muchas gracias :)

**Comment by RaniAgus** [comment]
¡Buenas! Tengan en cuenta que todos los archivos del File System deben persistir entre ejecuciones, esto es, si tiramos abajo el módulo con `Ctrl`+`C` y lo volvemos a levantar, los archivos deben mantenerse tal y como están.

Dicho esto,
- Los archivos de metadata solamente se crean al ejecutar `IO_FS_CREATE`
- En cuanto a los de bloques y bitmap, no es necesario crearlos en caso de que no existan, pero estaría bueno hacerlo desde código para agilizar las pruebas :)

Saludos

**Comment by RaniAgus** [comment]
¡Buenas @inaaranza! ¿Les sirvió la respuesta? Saludos

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, si les quedó alguna duda pueden abrir uno nuevo referenciando éste. Saludos
