### ISSUE TITLE
Duda configs DialFs

### ISSUE THREAD

**Issue by ManuRodri01** [sisoputnfrba/foro#3973]
Buenas, teníamos una duda al momento de levantar los archivos del dialFs. 
Cada dialFS va a tener su propio archivo config? Porque si comparten uno entre varias, al momento de crear los archivos en el path del config se sobrescribirían entre ellos (El bloques.dat de la interfaz2 borraria el de la interfaz 1, etc).

La otra solucion que se  me ocurre es que los archivos tengan un nombre especial, por ejemplo Interfaz1_bloques.dat, Interfaz2_bloques.dat, etc.

Saludos

**Comment by RaniAgus** [comment]
¡Buenas! Tengan en cuenta que todos los archivos del File System deben persistir entre ejecuciones, esto es, si tiramos abajo el módulo con `Ctrl`+`C` y lo volvemos a levantar, los archivos deben mantenerse tal y como están.

Por lo tanto, ese "momento de crear los archivos en el path del config" al que hacen referencia solo pueden implementarlo en caso de que estos archivos no existan.

Por otro lado, no vamos a evaluar el caso de montar dos DialFS en la misma carpeta.

Saludos

**Comment by ManuRodri01** [comment]
Oka, muchas gracias.
