### ISSUE TITLE
Dudas de conexión y manejo de sockets I/O en kernel

### ISSUE THREAD

**Issue by LucianoZunino** [sisoputnfrba/foro#3975]
Hola Buenos días. Estuvimos viendo los issues #3964,  #3721 y #3831 (entre otros), pero aun tenemos dudas de como proceder con la conexión de i/o 's . Ahora mismo nuestra solución funciona con una sola I/O conectada, pero nuestro problema radica en que tenemos un solo puerto de kernel en el config para escuchar todas las interfaces y no sabemos bien como crear o inicializar un socket por cada i/o que se solicite conectarse a kernel.

Alternativa solución 1: se nos había ocurrido agregar mas puertos en el config para escuchar cada interfaz, pero no sabemos si es legal.
Alternativa solución 2: Tener una lista global donde cada interfaz de i/o pueda agregar el socket de conexión entre i/o y kernel.

Estamos entendiendo bien el tema de conexiones o habría que plantearlo de otra manera?

**Comment by RaniAgus** [comment]
¡Buenas! Como probablemente hayan visto en la [guía de sockets](https://docs.utnso.com.ar/guias/linux/sockets#accept-y-connect), la cual sirve para realizar el TP0 de principios de cuatrimestre, el socket que se `bind()`ea a un puerto es únicamente de escucha. Al realizar `accept()`, se devuelve un nuevo socket el cual representa la conexión bidireccional con el otro proceso, y cuya comunicación ocurre en otro puerto disponible.

Entonces, para atender múltiples conexiones, lo cual es requisito del checkpoint 1, únicamente se tienen que guardar los sockets devueltos por `accept()`.

Saludos
