### ISSUE TITLE
Duda acerca de mov_in

### ISSUE THREAD

**Issue by FacundoStancanelliUTN** [sisoputnfrba/foro#3976]
Buenas, como están?
Tenemos tres dudas acerca del mov_in y las lecturas en memoria. Estuvimos revisando este issue #3877 
1) La cantidad de bytes en memoria son siempre contiguas no?
2) Si por ejemplo tengo:
SET EAX 30
MOV_IN EBX EAX
Con un tamaño de pagina = 32 bytes

Yo leería 4 bytes **contiguos** en memoria desde la posición 30? Si esto es así, porque debería calcular que voy a leer 2 paginas distintas? No seria lo mismo leer en memoria desde el byte 30, 4 bytes contiguos?
3) Si por ejemplo yo quiero guardar 50 bytes (ejemplo) en marcos de 30, pero los marcos libres que me quedan son el 1 y el 4. Yo guardaría 30 en el marco 1 y 20 restantes en el marco 4, cierto? Ahora bien, si yo quiero hacer un MOV_IN para recuperar dicha información; como reconozco que dicha información no quedo contigua y debo conocer que la primer parte quedo en el 1 la segunda en el 4to y buscarla allí? Este caso podría ocurrir, o siempre serian contiguas las lecturas?

Desde ya gracias.
Saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Si los bytes son contiguos, por eso tienen que reservar un gran malloc al principio de la ejecución del módulo memoria.
2.- No, porque justamente tu tamaño de página es 32, es decir que vas a leer bytes 30 y 31 de la página 0 y despues los bytes 0 y 1 de la página 1.
3.- Vos tenes que guardar las cosas en páginas, entonces lo que termina importando es como tenes asignadas las páginas del proceso, puede ser que asignes primero el marco 4 y despues el 1

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Me sumo solo para agregar este comment con un ejemplito de cómo debería ser el cálculo _en CPU_: https://github.com/sisoputnfrba/foro/issues/3863#issuecomment-2163016424

**Comment by FacundoStancanelliUTN** [comment]
Buenas! Como va?
Muchas gracias desde ya por sus atentas respuestas.
Clarisimo eso (muchas gracias por ese issue adjunto @RaniAgus. Mi duda ahora es, nosotros en cpu enviamos (haciendo los cálculos de paginas y demas) un listado de direcciones físicas para escribir los bytes, y luego memoria sabrá recibirlo y escribir los N byes a partir de cada una de ellas, eso esta claro y lo tenemos así.
Mi duda es más que nada en el mov in, o en las lecturas en memoria. Si yo tengo que leer 4, 10 o 40 bytes x ejemplo, porque me interesaría la cantidad de páginas y por ende, los marcos en memoria? El mov in sólo no se encarga de leer N bytes **contiguos** en memoria a partir de cierta dirección física? Por que es necesario hacer algún cálculo (más allá de la conversión entre dir lógica a física)
Gracias desde ya

**Comment by RaniAgus** [comment]
Si bien los bytes a leer o escribir van a estar contiguos de forma lógica (ej: leer desde la dirección 30 hasta la 33), puede que justo caigan al final de una página y al principio de otra, y esto hace que estén en marcos distintos, lo cual requiere distintas traducciones

**Comment by FacundoStancanelliUTN** [comment]
Claro ahí va. Esa es mi duda. Pará la escritura super claro eso (porque incluso puede caer en otro marco distinto, no necesariamente el siguiente, no?) Pero en las lecturas, porque no puede ser indistinto los marcos que tengo que leer?
Si estoy en la dirección física 1 (por ejemplo) y cpu me dijo que tengo q leer 4 bytes, para la memoria es indistinto en q página o marco estoy, ya que debería agarrar la dirección física y sumarle 4 bytes no? Quizás hay algo que no me queda claro aun

**Comment by FacundoStancanelliUTN** [comment]
Pero para nosotros es independiente cuantas páginas debo leer, solo le digo a memoria cuántos bytes debe leer a partir de que posición física, y memoria lee (no importa si los marcos son de 4 bytes y debo leer 41 bytes, que sean 10 marcos, sino que a la dir física directamente le sumamos 41, hacemos el memcpy de todo eso y listo).

**Comment by RaniAgus** [comment]
Perdón pero no entendí por qué harían una diferenciación entre `MOV_IN` y `MOV_OUT`. Ambos funcionan igual en cuanto al cálculo de las direcciones y los tamaños a leer o escribir: reciben una dirección lógica y el tamaño es el del registro.

Por ejemplo, teniendo tamaño de página 32:
```
SET EAX 18122022
SET AX 30
MOV_OUT AX EAX
MOV_IN EBX AX
```

- `MOV_OUT` va a disparar 2 peticiones de lectura:
   1. En el marco correspondiente a la página 0 con offset 30
   2. En el marco correspondiente a la página 1 con offset 0
- `MOV_IN` va a disparar 2 peticiones de escritura, ambas en los mismos lugares que el caso anterior

**Comment by FacundoStancanelliUTN** [comment]
Bien. Claro. Lo que no entiendo es porque es necesario hacer dos peticiones en el mov in, si sabes que vas a leer 4 bytes, porque no te es indistinto los marcos y páginas? Si vos te posocionas en memoria en el espacio de usuario, en la dirección física 30, y agarras 4 bytes para adelante, no te daría el mismo resultado que leer dos veces 2 bytes siendo que las lecturas son siempre contiguas en memoria? (Cuando digo contiguas me refiero a que si vos haces una petición de lectura en la dirección física 30, de 4 bytes, no vas a leer 2 bytes en el marco (ejemplo 4) que esta esa dirección y otros 2 en otro marco (ejemplo el 80)

**Comment by FedericoGSantoro** [comment]
Hola @RaniAgus, como estas, pregunta para ver si estamos en la misma pagina, como se deberían de guardar los datos en la memoria mediante la instrucción de mov_out o mov_in o alguna interfaz o lo que sea? Podría ser que cada carácter alfanumérico ocupe 1 solo byte?
Yo había razonado de esa forma, entonces diciéndolo así nomas, lo que se tendría es una matriz prácticamente que representaría la memoria, donde utilizas el primer numero para acceder al numero de marco y el segundo para acceder al byte de ese array (siendo esto el offset). Si quiero guardar el numero 22 en una pagina de 5 bytes justo en el ultimo byte digamos quedaría así:
| Marco | Dato |
|--------|--------|
| 0 | [X,X,X,X,X] |
| 1 | [X,X,X,X,2] |
| 2 | [2,X,X,X,X] | 

Siendo X un dato poco importante en este caso, estaría bien pensarlo de esta manera? (Obviamente que es una idea simple, seria mejor usar lista en vez de array, etc.)

Gracias!

**Comment by RaniAgus** [comment]
Voy a enumerar las respuestas ya que sino se me va a complicar responderlas todas.

1. Probablemente en la teoría hayan visto que un proceso puede tener asignadas 2 páginas pero no tienen por qué estar asignadas en marcos contiguos dentro del espacio de usuario, por ejemplo:

| Página | Marco (Inicio) |
|-|-|
| 0 | 2 (64) |
| 1 | 5 (160) |

Acá, para leer o escribir 4 bytes desde la dirección **lógica** `30`, los primeros 2 bytes hay que escribirlos partiendo de la dirección **física** `94` y los 2 restantes desde la dirección **física** `160`.

Dejé el inicio del marco entre paréntesis para que puedan seguir la cuenta a ojo, pero es básicamente `numero_marco * tam_pagina` ya que los marcos **sí son contiguos**: el marco 0 arranca en la dirección **física** `0`, el marco 1 en la dirección **física** `32`, y así.

2. El enunciado especifica que el espacio de usuario debe ser contiguo y representado por un único `void*`, y aclara:

> Es importante aclarar que **cualquier implementación que no tenga todo el espacio de memoria dedicado a representar el espacio de usuario de manera contigua será motivo de desaprobación directa**, para esto se puede llegar a controlar la implementación a la hora de iniciar la evaluación.

Por lo que utilizar una matriz o listas es una implementación errónea. De hecho hasta lo estarían complejizando porque en realidad deberían recibir de CPU una dirección física a la que ustedes simplemente hacen:

```c
memcpy(inicio_memoria + direccion_fisica, valor, tamanio); // para escribir

memcpy(valor, inicio_memoria + direccion_fisica, tamanio); // para leer
```

3. En cuanto a qué se almacena en memoria:
- Los registros almacenan datos de tipo `uint8_t` o `uint32_t`, por lo que `MOV_IN` y `MOV_OUT` deben escribir en memoria dichos bytes. Por ejemplo, el 22 vendría a pisar un byte con el valor `16` en hexa si viene de un registro de 1 byte, o los bytes `16 00 00 00` si el valor viene de un registro de 4 bytes
- Para `STDIN` y `STDOUT`, se lee y escribe la representación en ASCII de una cantidad n de caracteres definida por parámetro. Por ejemplo, si quiero escribir 4 bytes e ingreso `"HOLA"`, en el espacio de usuario se va a escribir `48 4F 4C 41`.

Para esto, como está explicado más en detalle en el issue que citaba tu compañero, quédense tranquilos, no es necesario hacer ninguna conversión, ya que _todo en C son bytes_: https://github.com/sisoputnfrba/foro/issues/3877#issuecomment-2156281836.

**Comment by FedericoGSantoro** [comment]
Ok, hablando del 3, no puedo tomar como que el 22 es 2 (1 byte) y 2 (1 byte) da igual de que registro venga? Y lo guardo cada uno en una posición. Porque yo podría guardar los datos de un registro uint32_t y querer leerlo con un registro de uint8_t, y debería de poder entiendo, entonces tomo cada numero como un uint8_t (que representa 1 byte) y nada mas. Si quiero leer 22, agarro el 2 y después agarro el 2 (en dos lecturas distintas) y combino sus bytes para obtener el 22, estaría mal pensarlo así?

**Comment by RaniAgus** [comment]
No, los registros contienen valores en `uint8_t` o `uint32_t`, por lo que si yo le hago `SET` a un registro del valor `22`, lo que se guarda es un entero no signado, no su representación en ASCII.

Si yo quisiera setearle el ASCII `"22"` a un registro con `SET`, éste debería ser de 4 bytes (ya que con 1 no me alcanza), y debería ser algo como:

```
SET EAX 12850
```

Ya que `12850` en bytes sería `32 32 00 00`, y el número `0x32` en hexa representa el caracter ASCII `'2'`.

**Comment by FedericoGSantoro** [comment]
Lo que no capto yo, es como separo ese 22 para cada numero guardarlo, ya que si no entra en el primer marco todo, debería separarlo, para este caso especifico pensé algo del estilo:

    // Escritura en memoria
    uint32_t valorGuardar = *(uint32_t*) registro; //  registro = 22
    uint8_t valorGuardar1 = valorGuardar / 10;  // Decena
    uint8_t valorGuardar2 = valorGuardar % 10;  // Unidad
    enviarMemoria(paquete); // Aca estan los valorGuardar1 y 2 con el tamaño
    
    // Esto en memoria
    memcpy(inicio_memoria + direccion_fisica, &valorGuardar1, 1); 
    memcpy(inicio_memoria + direccion_fisica, &valorGuardar2, 1);

    // Lectura desde memoria
    uint8_t valor1, valor2;

    memcpy(&valor1, inicio_memoria + direccion_fisica, 1);
    memcpy(&valor2, inicio_memoria + direccion_fisica, 1);
    enviarCPU(paquete); 
    
    //En cpu de desempaqueta y se hace:
    int valorFinal = valor1 * 10 + valor2;

Considerando direccion fisica como la direcciones que corresponde, y si el numero es mas grande entonces se hacen mas calculos para obtener cada numero por separado.
En los casos de cadenas de caracteres si, simplemente cada caracter ocupa 1 byte y listo

**Comment by iago64** [comment]
Buenas! Cómo va?

Creo que lo que estas buscando es algo que ya respondí en el [issue 3781](https://github.com/sisoputnfrba/foro/issues/3781#issuecomment-2133708741), por estas cosas les recomendamos siempre que revisen los issues cerrados, así no tienen que comerse la espera de que algún ayudante este libre y revisando el foro.

Saludos.-

**Comment by FedericoGSantoro** [comment]
Claro pero eso es lo que estoy preguntando, si al momento de guardar en memoria (al igual que leer) puedo asumir que cada numero que guarde ocupa 1 byte, al igual que cada letra de un string ocupa 1 byte.

**Comment by RaniAgus** [comment]
Repito lo que dije un par de comentarios atrás: los números que recibe `SET` NO son caracteres ASCII, son números enteros que se escriben en sistema decimal pero al guardarse (como cualquier `int`) se guardan en binario.

Por ejemplo, el 22 en binario es `10110`, lo cual encaja perfectamente en un byte como `0001 0110` y en hexadecimal es el `16` que mencionaba más arriba.

También repito, como mencionamos en otros issues, no tienen por qué hacer ningún casteo ni conversión para poder lograr esto, alcanza simplemente con usar un par de `memcpy()`s ya que en C toda la memoria está en binario, son simplemente bytes.

**Comment by FedericoGSantoro** [comment]
Ósea, para cerrar, si yo quiero guardar un valor hasta 255 lo hago en 1 byte, si quiero guardar mas tengo que ver cuantos bytes necesito y guardarlo en la cantidad necesaria? por ejemplo 256 seria en 2 bytes. Estaría bien eso?

**Comment by iago64** [comment]
Buenas! Cómo va?

Los registros tienen tamaños definidos, no de olvides de la tabla que esta en el enunciado sobre los [Registros de la CPU](https://docs.google.com/document/d/1-AqFTroovEMcA1BfC2rriB5jsLE6SUa4mbcAox1rPec/edit#heading=h.g8wwscbuoevu)

Saludos.

**Comment by RaniAgus** [comment]
Estos valores que recibe `SET` se guardan en un registro que puede medir 1 o 4 bytes.

Dependiendo de cuánto mida el registro, les va a quedar `16` o `16 00 00 00`. Esto ya lo hace C cuando asignan:

```c
uint8_t ax = 22;
uint32_t eax = 22;
```

Luego, cuando les toque ejecutar un `MOV_IN` o un `MOV_OUT`, la forma de extraer esos bytes de los registros es simplemente con un `memcpy()` del tamaño del registro.

O sea, `MOV_IN` y `MOV_OUT` no tienen ni idea de si lo que se está guardando es mayor ni menor a 255.

**Comment by FedericoGSantoro** [comment]
Okk, por mi parte ya estaría gracias, pero no puedo cerrar yo el issue jaja

**Comment by LeandroCarbajales** [comment]
Siendo que son del mismo equipo, entiendo que las dudas están resueltas por igual, por lo que cierro el issue :)
