### ISSUE TITLE
Duda Interfaz

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#3977]
Hola buenas tardes. Tengo unas dudas de la parte de interfaz FileSystem.
Yo por lo que entendi, tendriamos que poner la direccion de una carpeta en el config. Y dentro tendriamos que ver si existen los archivos bloques.dat y bitmap.dat, en caso que no existan crearlos. Y despues cada vez que hagan un create, tenemos que crear un archivo con el nombre que nos pasan. 
Mi duda primera duda es si esto es realmente asi o si hay algo que entendi mal. Y despues queria preguntar por el path que pasamos, ese path va a estar creado? o tenemos que poder crear algunas carpetas que falten?
Gracias de antemano

**Comment by RaniAgus** [comment]
¡Buenas!

> Yo por lo que entendi, tendriamos que poner la direccion de una carpeta en el config. Y dentro tendriamos que ver si existen los archivos bloques.dat y bitmap.dat, en caso que no existan crearlos. Y despues cada vez que hagan un create, tenemos que crear un archivo con el nombre que nos pasan.
Mi duda primera duda es si esto es realmente asi o si hay algo que entendi mal. 

Sí, es realmente así.

> Y despues queria preguntar por el path que pasamos, ese path va a estar creado? o tenemos que poder crear algunas carpetas que falten?

Pueden manejarlo como prefieran: 
a) asumir que siempre va a estar creado
b) chequear que exista y, de no ser así, fallar
c) chequear que exista y, de no ser así, crearlo

Personalmente creo que la b) sería lo mejor para detectar rápido cualquier dedazo al editar la config, pero no vamos a evaluar eso. Todas las pruebas son asumiendo que las configs son correctas (y, de encontrar alguna prueba con configs erróneas, avísennos).

Saludos

**Comment by JoaquinCoaricona** [comment]
Ok gracias. Me surgio una pregunta sobre la consigna, en esta parte: 

> El primero va a ser nuestro archivo de bloques (bloques.dat) el cual va a ser un archivo de tamaño definido mediante 2 parámetros del archivo de configuración: BLOCK_SIZE y BLOCK_COUNT, y el tamaño del archivo va a ser BLOCK_SIZE * BLOCK_COUNT.

Como podria hacer para establecer el tamaño del archivo? Hay alguna funcion especifica que tengamos que usar para esto?

**Comment by iago64** [comment]
Buenas! Cómo va?

Se que va a sonar medio mala onda la respuesta, pero Google y/o Chat GPT por ahora hasta donde sabemos no mataron a nadie, por lo tanto, siempre que tengan estas dudas simples antes de perder tiempo esperando que algun ayudante les conteste, recurran a algo mas rapido como las opciones que les pase antes.

Dicho lo anterior, podes investigar la función [`ftruncate()`](https://linux.die.net/man/2/ftruncate)

Saludos.-

**Comment by JoaquinCoaricona** [comment]
Hola buenas. Si, ya estuve averiguando sobre esa funcion pero deje el issue por las dudas, por si habia otra funcion recomendada para usar.
