### ISSUE TITLE
Duda con el funcionamiento de VRR y el quantum restante

### ISSUE THREAD

**Issue by ErikOteo** [sisoputnfrba/foro#3978]
Buenas!! Tenemos una duda con la ejecución del algoritmo VRR 

La situación que nos genera la duda es la siguiente:
- Esta ejecutando un proceso, se termina el quantum y entonces kernel manda la interrupción a CPU.
- CPU deja que se termine de ejecutar la instrucción para interrumpir el proceso.
- Esa instrucción bloquea el proceso
- CPU ignora la interrupción porque el proceso ya no esta ejecutando

La duda es cuando el proceso se desbloquee tiene que entrar a READY con prioridad? Y en ese caso que Quantum le tiene que dar el planificador a ese proceso la próxima vez que se lo quiera mandar a ejecutar?

**Comment by LeandroCarbajales** [comment]
Buenas!
Suponiendo que quisieras enviarlo a la cola con prioridad con su Q restante, si Kernel ya mandó la interrupción con fin de Q cuánto sería su Q restante?

**Comment by ErikOteo** [comment]
Su Q restante seria cero. Así que si lo manda a ejecutar, lo interrumpiría casi instantáneamente, pero el proceso llegaría a ejecutar una sola instrucción (ya que CPU espera a que termine el ciclo de instrucción para atender la interrupción).

**Comment by LeandroCarbajales** [comment]
Claro, pero tendría sentido enviarlo a la cola de prioridad si en definitiva el proceso agotó todo su quantum?
Siguiendo la misma idea que en los ejercicios que vemos en clase, no tendría más sentido que el proceso vuelva a la cola "normal" con el Q inicial?

**Comment by ErikOteo** [comment]
Entiendo que si, porque por mas que el proceso haya dejado de ejecutar porque se bloqueo y NO por la interrupción, de todas formas la interrupción fue enviada y el quantum se termino. Pero teníamos las duda y preferimos preguntar. Gracias.
