### ISSUE TITLE
Duda sobre la TLB

### ISSUE THREAD

**Issue by JoaquinMartinezUtn** [sisoputnfrba/foro#3979]
Buenas, tengo una consulta sobre la cantidad de entradas de la tlb que viene definida en el archivo de configuración de la cpu.
No estaría entendiendo bien qué rol cumpliría esa cantidad. Si es la cantidad de elementos que se pueden guardar dentro de la tlb, o sea de traducciones, si por ejemplo hay 32 entradas solo se pueden almacenar 32 traducciones. O si representa la cantidad de páginas que se encuentran dentro de la memoria.
Desde ya muchas gracias, entiendo que es una pregunta muy básica pero no logro entenderlo.
Saludos.

**Comment by RaniAgus** [comment]
¡Buenas! Una entrada de una tabla es lo mismo que un elemento. La utilidad que tiene es que cuando se llene dicha tabla y quieran almacenar una nueva entrada van a tener que reemplazar otra usando el algoritmo configurado de la misma forma que practicaron en la parte teórica de la materia. Saludos

**Comment by JoaquinMartinezUtn** [comment]
Ahh perfecto, muchas gracias.
