### ISSUE TITLE
Proceso llega a exit, dudas dialFS

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3980]
Buenas,
Tenemos una duda con respecto al tema de la liberación de recursos cuando un proceso llega a exit. Entendemos que puede liberar recursos, si tomó instancias que no devolvio en kernel, memoria por el tema de la tabla de pagina y demás:

1- Pero cuando dice "liberar archivos" se refiere a liberar los archivos que un proceso puede tener en un dialFS o a otra cosa? 

2- De paso pregunto si una misma interfaz dialFS puede ser utilizado por distintos procesos como las demás (supongo que si) o solo le corresponde a uno.

3- Si una misma interfaz fs puede interactuar con varios pids ¿Debemos manejar el tema de que un proceso no escriba en el archivo de otro proceso?

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- TL-DR: No se preocupen, fue un error de copy-paste en la descripción del enunciado.
Explicación: Viste que es una buena practica reciclar? Bueno, en el TP reciclamos la idea de la consola de TPs anteriores donde si teniamos un FS mas completo que tenia la idea de tener un puntero al archivo para saber a donde leer/escribir pero en este TP lo simplificamos.

2.- Como todas las interfaces, atienden de a 1 las peticiones pero las peticiones pueden venir de cualquier proceso.

3.- No, simplemente dejenlos escribir sin problema, no queremos que se compliquen con temas de permisos, eso va a ser tema capaz para otro TP.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @rood8592! ¿Te sirvió la respuesta de Dami? Saludos

**Comment by rood8592** [comment]
Sisi, gracias! Cierro el issue.
