### ISSUE TITLE
Sobre dimensiones del archivo de bloques y bitmap

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3982]
Buenas! ahi vi de chusma en otro issue que recomendaron el uso de `ftruncate()` y me prendio algunas luces. 
 Primero porque nosotros para crear el archivo de bloques le mandamos de una con un `fwrite()` del tamanio del fs y listo. Esto es correcto?

Y despues se me ocurrio que ustedes podrian, a partir del mismo pathbase, cambiarle las dimensiones al los archivos de bloques y bitmap correspondientes y ahi quizas si corresponderia usar `ftruncate()` aunque no se que tanto molestaria que queden mas bloques sin usar al final del archivo. Este caso se debe contemplar??

Espero se me haya entendido y muchas gracias!

**Comment by f-and** [comment]
Buenas, por un lado, como siempre decimos, mientras que ande el TP pueden hacer un fread por lo que nos concerne, si se levantan los archivos correctamente. Recomendamos ftruncate, porque es la solución mas recta, pero si hacen el fwrite y sale todo bien sin sobreescribir nada entonces perfecto!

Por el otro lado, no, un ayudante no va a hackear su computadora durante la entrega para cambiar cosas, nos gustaria, pero la mayoria aun no cursamos ciberseguridad ;) Los archivos de FS los van a crear ustedes, seguramente desde 0, y la unica validación que tienen que hacer es en el caso que exista y tenga un tamaño distinto al solicitado cambiar el tamaño del archivo al correcto.

Saludos.-

**Comment by GonTurri** [comment]
Perdon, me perdi un poquito a ver si puedo entender lo que me dijiste. Entonces al levantar el file system siempre hago ftruncate ya sea exista o no  por si las dudas. Y despues estaria necesitando el fwrite puesto que me gustaria poner todos los bloques en 0 al inicio, pero masomenos es hacer: 
```c
// caso no existe file system
f = fopen("bloques.dat","wb+");
ftruncate(f,tamanio_fs);
fwrite( 0 * tam_fs en f)

// mas cosas

fclose(f)

// caso ya existe el fs

f = fopen("bloques.dat","rb+");
ftruncate("bloques.dat",tamanio_fs);

// hacer cosas

fclose(f);
```

algo asi? puede ser que no este entendiendo del todo

**Comment by GonTurri** [comment]
ahi estuve leyendo el manual,  estabamos haciendo lo mismo pero mas a manopla. Muchas gracias!
