### ISSUE TITLE
Retardos de Memoria

### ISSUE THREAD

**Issue by julienf04** [sisoputnfrba/foro#3983]
### Buenas!

Nos surgió unas dudas relacionadas a los retardos de Memoria.

1) Supongamos el caso en el que lleguen 2 peticiones de Kernel hacia Memoria "muy rápido", como por ejemplo 2 peticiones de de creación de proceso, ¿qué se debe hacer?

a) Esperar el retardo por el proceso 1, crear el proceso 1, esperar el retardo por el proceso 2, crear el proceso 2.

b) Esperar el retardo por los procesos 1 y 2 (la espera del retardo ocurre simultáneamente), crear los procesos 1 y 2 simultáneamente (excepto en secciones críticas).

2) ¿Y si llega una peticion de Kernel y luego una de CPU casi "al mismo tiempo"?, como por ejemplo una petición creación de proceso de Kernel y luego una petición de instrucción de CPU, ¿qué se debe hacer?

a) Esperar el retardo por la creación del proceso, crear el proceso, esperar el retardo por la petición de la instrucción, devolver la instrucción.

b) Esperar el retardo por la creación del proceso y la petición de la instrucción (la espera del retardo ocurre simultáneamente), crear el proceso y devolver la instrucción simultáneamente.

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Opción A

2.- Las operaciones de Kernel, CPU e Interfaces no deberían "estorbarse", es decir, si tenes una petición de Kernel y una de CPU "al mismo tiempo" deberías asegurarte solo de sincronizar las secciones criticas.

Como corolario de las 2 respuestas, pensa cada petición de forma independiente y espera el retardo correspondiente a cada una sin preocuparte por que otras cosas estan pasando.

Saludos.-

**Comment by julienf04** [comment]
Muchas gracias!!!
