### ISSUE TITLE
Finalización del sistema

### ISSUE THREAD

**Issue by julienf04** [sisoputnfrba/foro#3984]
### Buenas!

¿En las pruebas se va a probar o tener en cuenta que el sistema pueda finalizar correctamente? Es decir, que todos los módulos puedan bajarse de forma ordenada tras dar una órden.

**Comment by iago64** [comment]
Buenas! Cómo va?

No, cuando bajamos los procesos entre pruebas le tiramos, mejor dicho les pedimos que tiren, Ctrl + C a cada proceso.

Saludos.-

**Comment by julienf04** [comment]
Muchas gracias!!! Nos facilita todo bastante entonces
