### ISSUE TITLE
Consulta de Bloques

### ISSUE THREAD

**Issue by AyluDubini** [sisoputnfrba/foro#3986]
Buenas, tengo una duda con los bloques de datos de los archivos. Donde deberían guardarse? Porque no tenemos una estructura de memoria virtual o disco duro, tampoco manejamos un módulo de FileSystem.

Los bloques deberían guardarse en los marcos de la memoria? O deberían guardarse dentro del archivo "Bloques.dat"? Esto último lo interpreto del enunciado "El primero va a ser **nuestro archivo de bloques** (bloques.dat)"

**Comment by RaniAgus** [comment]
¡Buenas! Así como en Memoria el espacio de usuario está formado por un único `void*` (o sea, un array de bytes) organizado en frames contiguos, en el módulo DialFS el "disco" del FileSystem es un único archivo binario bloques.dat (o sea, también un array de bytes) organizado en bloques contiguos. Saludos
