### ISSUE TITLE
Duda al borrar archivo montado en el FS

### ISSUE THREAD

**Issue by nicolasreypc** [sisoputnfrba/foro#3987]
Buenas, tengo la duda de si al ejecutar IO_FS_DELETE "archivo", ademas de marcar los bloques como libres en el bitmap y borrar el archivo metadata; tambien se deben setear los bloques de "bloques.dat" con ceros por ej.

Tambien tengo la duda de si es indiferente crear los archivos en modo texto ("w"), o si es necesario hacerlo en binario ("wb").

**Comment by iago64** [comment]
Buenas! Cómo va?

Con marcar los bloques libres y eliminar el archivo de metadata alcanza.
Respecto a los archivos, los de metadata es indistinto, en el caso del de bloques y el de bitmap si les conviene abrirlos con `wb` 

Saludos.-

**Comment by nicolasreypc** [comment]
Muchas gracias!
