### ISSUE TITLE
Problema con el sleep en cantidades no exactas de segundos

### ISSUE THREAD

**Issue by DamianBlum** [sisoputnfrba/foro#3988]
Quería consultar una duda sobre el sleep, porque en las pruebas que nos pasaron ya por ejemplo se usa de quantum 2750 ms y en base a eso da distintas interrupciones por fin de quantum, lo que me esta pasando es que esta ocurriendo una interrupcion por fin de quantum y leyendo los logs vi que parece que no hace el sleep como quiero, o lo estoy entendiendo mal quizas, no se.

### 🔎 Búsqueda en foros

Segun busque se puede poner por ejemplo 2.75 segundos en el sleep pero viendo los tiempos sigue haciendolo en 2 segundos
No se si tendria que poner el quantum redondeado a 3 segundos?

### 📝 Código relevante

```
    log_info(logger, "Iniciando servidor de memoria");
    sleep(2);
    log_info(logger, "Pasaron 2 segundos");
    sleep(2.75);
    log_info(logger, "Pasaron 2,75 segundos");
    sleep(3);
    log_info(logger, "Pasaron 3 segundos");
```

### 💻 Logs

[INFO] 17:25:26:432 MEMORIA/(3844:3844): ---------- INICIO DEL LOG EN MODO DEBUG ----------
[INFO] 17:25:26:433 MEMORIA/(3844:3844): Iniciando servidor de memoria
[INFO] 17:25:28:433 MEMORIA/(3844:3844): Pasaron 2 segundos
[INFO] 17:25:30:434 MEMORIA/(3844:3844): Pasaron 2,75 segundos
[INFO] 17:25:33:435 MEMORIA/(3844:3844): Pasaron 3 segundos

**Comment by LeandroCarbajales** [comment]
Buenas!
Si no recuerdo mal no solo el quantum sino también todos los tiempos de retardo están en milisegundos. Pueden usar la variante [usleep](https://man7.org/linux/man-pages/man3/usleep.3.html) que tiene precisión en microsegundos.
Por ejemplo:
```c 
usleep(2750 * 1000)
```

Saludos!
      Lean

**Comment by DamianBlum** [comment]
Dale muchas gracias Lean!, ahí cambio al usleep entonces
