### ISSUE TITLE
duda compactacion

### ISSUE THREAD

**Issue by nicolasreypc** [sisoputnfrba/foro#3989]
Buenas, tratando de plantear la compactacion de archivos en el FS me surgio la duda de si sera evaluda la eficiencia del algoritmo que usemos, o solo que termine cumpliendo la tarea de compactar propiamente?

Porque la forma en la que pensamos hacerlo es tener una lista con los nombres de los archivos, y a la hora de compactar recorrer todos dejando el archivo que se quiere compactar al final, y luego todos los bloques libres. Pero tal vez no sea la mejor forma en terminos de eficiencia...

**Comment by iago64** [comment]
Buenas! Cómo va?

No les dimos lineamientos de como compactar, por lo que no vamos a evaluar que tan eficiente sean, de hecho, es parte del aprendizaje que piensen alguna forma y despues charlemos en el coloquio de la forma en la que lo resolvieron.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @nicolasreypc ! ¿Les sirvió la respuesta de Dami? Saludos
