### ISSUE TITLE
Acceso a archivos del file system

### ISSUE THREAD

**Issue by ElielBejar** [sisoputnfrba/foro#3990]
Hola que tal! Hoy en clase vi sobre la coherencia y seguridad de los datos al acceder a los archivos y me surgieron unas dudas sobre como sería en este TP.

Mi principal duda es si en caso que haya mas de un dialfs, pueda llegar a darse que esas interfaces dialfs accedan a un mismo archivo(tendrían que tener el mismo path base)? Eso puede llegar a pasar? o siempre van a tener un path diferente en los archivos de configuración? Porque si es así podría haber problemas con los accesos a esos archivos y habría que usar algún mecanismo de mutua exclusión  para cada archivo.

Y también, aprovecho a preguntar, si puede llegar a haber problemas con que dos procesos lean y escriban en archivos con el mismo file system? Entiendo que no porque la interfaz atiende de a una las instrucciones que le van llegando pero pregunto por las dudas.

Desde ya gracias y buenas tardes!

**Comment by iago64** [comment]
Buenas! Cómo va?

No vamos a testearles que 2 DialFS accedan a los mismos archivos, en el peor de los casos eran 2 FS completamente distintos con su set de archivos.

Que 2 procesos lean y/o escriban archivos del mismo DialFS es algo que ya vieron a principio del cuatrimestre y es un problema de sincro de los procesos no del FS.

Saludos.-

**Comment by ElielBejar** [comment]
Buenísimo, entendí. Gracias!
