### ISSUE TITLE
Duda implementación vrr

### ISSUE THREAD

**Issue by lseijasferraudo** [sisoputnfrba/foro#3991]
buenos días quería saber como es que funciona la implementación del ver en el tp.
¿las colas auxiliares funcionan como un fifo o de que manera deberían funcionar ?

**Comment by lseijasferraudo** [comment]
ósea la ready, como la ready aux seria fifo entonces no ? si es así no tendría otra duda

**Comment by iago64** [comment]
Buenas! Cómo va?

Es así, VRR de hecho esta pensado para aprovechar el quantum restante del proceso por lo que se implementa igual que en  RR normal, FIFO y desalojan por una interrupción.

Saludos.-
