### ISSUE TITLE
Sobre implementacion de compactacion

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3992]
Como va? ya vi que dejaron como 4 dudas sobre esto pero, despues de una primera iteracion, la verdad es que el algoritmo de compactacion que nos quedo abusa mucho de la memoria de la VM y es practicamente imposible de implementar en un SO y FS real. Si bien en este issue #3989 dicen que da igual la implementacion la verdad es que me hace un poco de ruido por lo que dije arriba. 
Mas que nada para no llevarnos ninguna sorpresa en el coloquio, nos gustaria saber si habria que darle una vuelta de rosca al algoritmo para que quede masomenos parecido a lo que hace el disco posta, o si podemos hacer lo que sea mientras funcione.

Muchas gracias como siempre por su atención

**Comment by LeandroCarbajales** [comment]
Buenas!
La única sorpresa en el coloquio sería que no sepan explicar cómo lo implementaron :)
Si luego también pueden decirnos por qué creen que no es una buena implementación mejor aun.

En resumen, misma respuesta que en el issue citado.

Saludos!
      Lean
