### ISSUE TITLE
Duda sobre IO_FS_TRUNCATE

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#3993]
Buenas! en esta instrucción una vez le asingo/libero bloques a ese archivo, tengo que escribir '\0' en esos bloques o puede quedar basura como en el caso de la memoria? 

Muchas gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

No es algo que tengamos pensado testear, si lo quieren hacer son libres de hacerlo.

Saludos.-
