### ISSUE TITLE
Filesystem y accesos a bloques

### ISSUE THREAD

**Issue by fmigliavacca** [sisoputnfrba/foro#3994]
Hola! buenas noches! Quería hacerles unas consultas 
1- Hay una forma CORRECTA de acceder a los bloques cuando uno pretende leer un archivo del fs?. Yo pensé dos formas, la primera podría ser haciendo una estructura externa tipo lista que le paso por puntero a cada hilo de interfaz FS la misma. Esta lista podría contener un nodo por cada archivo dentro del fs, y esos nodos tener adentro otra lista con todos los bloques que ocupó ese archivo. Sería como un inodo, pero dentro de una lista en vez de dentro del archivo de bloques. Otra opción que pensé más rustica sería poner al final de cada bloque un puntero al próximo bloque (en caso de ocupar más de uno). Si me podrían confirmar si ambas son válidas, o ninguna o alguna si, les super agradecería. 
2- Otra consulta, en un bloque debería poder poner información de dos archivos distintos? O un bloque siempre le pertenece a un solo archivo análogamente como las páginas y los procesos?.  
3- Último pero no menos importante, cómo se pretende que haga el archivo de bitmap? Yo pensé en crear el archivo y asignarle de tamaño cantidadDeBloques * sizeof(int) y llenarlos todos en uno al principio, como si estuvieran vacios. Pero supongo que está errado xq no sería "bit"map ya que ocupo 4 bytes por espacio. Hay alguna otra forma de implementarlo más correcta o esa es válida?.
Saludos y gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- La idea de que un archivo tenga asignación contigua es que TODOS sus bloques esten uno atras del otro y ordenados, por lo que no te haría falta ninguna lista ni ningun puntero extra.

2.- **NO**, un bloque es de un solo archivo y de hecho en el caso de asignación contigua todos los bloques de un archivo estan todos juntos uno atras del otro, por eso con tener la referencia al primer bloque te alcanza.

3.- El bitmap es una estructura en la cual cada bit representa un estado (libre con 0, ocupado con 1), la forma de implementarlo para que no se rompan la cabeza la tienen resuelta en parte con el `t_bitarray` de las commons, lo único que les restaría sería ver como guardar ese dato en un archivo pero eso si te fijas en el foro hay varias soluciones ya que es una estructura que usamos en el 90% de los cuatrimestres.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @fmigliavacca ! ¿Les sirvió la respuesta de Dami? Saludos

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, si les quedó alguna duda pueden abrir uno nuevo referenciando éste. Saludos
