### ISSUE TITLE
Msync en dialFS

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#3995]
Buenas, 
En dialFS nosotros hicimos variables globales tanto el ```void*``` que corresponde al ```bloques.dat``` y lo mismo con el ```void*``` que forma parte del bitarray. Al momento de levantar el dialFS, suponiendo que los archivos .dat ya existen, realizamos un mapeo a esos ```void*``` y cerramos los archivos. Lo que nos resulta raro es que después de haber hecho los ```fclose``` sigue surgiendo efecto los msync, ¿Esto es normal o no deberíamos hacerlo? Valgrind tampoco vemos que nos diga nada.

**Comment by LeandroCarbajales** [comment]
Buenas!
Buscando en el [man page de mmap](https://man7.org/linux/man-pages/man2/mmap.2.html) dice:

> After the mmap() call has returned, the file descriptor, fd, can
       be closed immediately without invalidating the mapping.
       
Saludos!
