### ISSUE TITLE
dudas con la escritura y lectura en mov_int y mov_put

### ISSUE THREAD

**Issue by nicolasvultaggio** [sisoputnfrba/foro#3998]
Pregunta basada en el issue #3877
> De la misma forma es que nosotros los vamos a leer o escribir en los registros: si mide 1 byte (uint8_t), copiamos 1 byte (ej: H, que sería el número 72); si mide 4 bytes (uint32_t), copiamos 4 bytes (ej: Hola, que sería el número 1634496328). Para esto no necesitamos hacer ninguna magia de casteos, alcanza con simplemente usar memcpy().

yo entiendo que en toda la memoria, entonces, se escriben CARACTERES, porque se escribe de a bytes.
pero entonces, como puedo escribir estos caracteres leídos en los registros numéricos que se recomendó que sean de tipo uint8_t y uint32_t? 
por ejemplo, supongamos que yo de memoria leo el numero "hola", sé que es un número que pesa 4 bytes, pero entonces los registros del pcb no deberían ser del tipo char* para guardar caracteres? o hay que hacer una conversión de ese "hola" a un número para guardarlo como tipo uint32_t en el registro?
De la misma forma, cuando leemos un registro ya sea un uint8_t o un uint32_t, deberíamos hacer una conversión a tipo char* para escribirlo en memoria? o sea transformar el 1634496328 a tipo "hola" para poder escribirlo como caracteres? esta parte me deja dudas.

en resumen, lo que no me cierra es cuando se dice "Para esto no necesitamos hacer ninguna magia de casteos, alcanza con simplemente usar memcpy()" , ¿por que es esto así? sí solo se usase un mempcpy, no rompería al intentar guardar un "hola" en una variable de tipo uint32_t?

**Comment by nicolasvultaggio** [comment]
actualizo: estuve usando chatgpt para intentar resolver esta duda y me propuso este ejemplo

```#include <stdio.h>
#include <stdint.h>
#include <string.h>

int main() {
    // Cadena de 4 caracteres
    char str[4] = "ABCD";

    // Asegurarse de que la cadena tiene 4 bytes
    uint32_t num;
    memcpy(&num, str, sizeof(num));

    // Imprimir el valor numérico
    printf("El valor uint32_t es: %u\n", num);
    printf("El valor uint32_t en hexadecimal es: 0x%X\n", num);

    return 0;
}
```

lo que hace entonces abajo es imprimirlo de distintas maneras?
si yo agarro un uint32_t puedo imprimirlo en patalla como una cadena hexadecimal con %X o imprimirla como su valor numerico con %u (o %d si se tratase de un int)??

**Comment by mefederico** [comment]
Hola buenas! 

Si, el `%algo` indica como interpretar los bytes nomas, el dato en si mismo es el mismo

Te dejo un comment de dami https://github.com/sisoputnfrba/foro/issues/3781#issuecomment-2133708741 que explica también como es esta magia de bytes y como trabajar los uint32_t

Saludos!

**Comment by mefederico** [comment]
Me quedo sin responder esto:

>  ¿por que es esto así? sí solo se usase un mempcpy, no rompería al intentar guardar un "hola" en una variable de tipo uint32_t?

 
 Porque en C todo son bytes, el tipo de una variable solo le dice como interpretar esos bytes, el texto "hola" es una convención humana ascii que le dio ese valor a los bytes
 
`68 6F 6C 61`

Que también es una convención humana para los 0 o 1 que realmente representan esos "bytes"

entonces cuando haces memcpy de una simplemente agarrar los 0 o 1 y los pones en otra porción de memoria que luego según el tipo de variable se interpreta como "hola" o un numero enorme en decimal o un struct o una posición de memoria

Ahora si, saludos!

**Comment by nicolasvultaggio** [comment]
buenísimo, muchas gracias, lo de los bytes me quedó claro.
perdón, justo edité el comentario (supongo que después de la respuesta) y agregué otra pregunta al final.

la dirección lógica del registro dirección, se interpreta directamente como un número de byte? porque nosotros, al interpretar como que viene de esta manera, la usamos para hacer operaciones matemáticas así de una. Tendríamos que enfocarnos en NO leer esos bytes como caracteres  para poder operar de manera correcta?

**Comment by nicolasvultaggio** [comment]
perfecto! para cerrar dudas:

- los números que leen y escriben mov_in y mov_out respectivamente, en MEMORIA son simplemente números bytes, por lo que podrían escribirse o leerse usando memcpy, no hace falta casteo alguno. Aunque logicamente son NÚMEROS.

- EN STDIN Y STDOUT, son LOGICAMENTE caracteres, por eso se pueden imprimir por pantalla e ingresar por teclado.

-  >Es un numero en representación decimal

Entonces en https://github.com/sisoputnfrba/foro/issues/3781#issuecomment-2133708741, cuando se dice que 
`uint32_t registro_ecx= 2147463345; `
2147463345 es directamente el número de byte de la direccón logica

perdón por tantas preguntas, es que prácticamente estoy haciendo todos los módulos del tp jjaj :(

**Comment by mefederico** [comment]
No hay problema estoy para ayudar! Podes hacer todas las preguntas que necesites para entender el problema

- Son bytes, al alcance del desarrollo del TP no requieren saber otra cosa, ahí van a haber DL o simplemente datos operables, por simplificación podes decir que son números.

- Si, van a ser caracteres imprimibles por pantalla. Básicamente bytes con un rango definido por la ascii table.

Depende el ejemplo puntual, pero una DL es un numero al cual le podemos hacer 2 operaciones como indica el [enunciado](https://docs.google.com/document/d/1-AqFTroovEMcA1BfC2rriB5jsLE6SUa4mbcAox1rPec/edit#heading=h.q1twu0jdsrm)

> número_página = floor(dirección_lógica / tamaño_página)
desplazamiento = dirección_lógica - número_página * tamaño_página

Al remarcar mucho que todo es lo mismo y son simplemente bytes no lo hago por mantenerme a la teoría, sino que es la forma de simplificar los conceptos y puedas operar todo como lo mismo.

Los valores que tomen los registros es un tema de nuestras pruebas ustedes tienen que tratarlos de forma transparente. Nosotros nos encargamos mediante SET, SUM, etc de darle valores correctos

**Comment by nicolasvultaggio** [comment]
perfecto, muchas gracias MAESTRO! buen jueves!
