### ISSUE TITLE
No puedo hacer list_remove_element con el numero 0

### ISSUE THREAD

**Issue by DamianBlum** [sisoputnfrba/foro#3999]
Queriamos eliminar un id de una lista en la cual este id es 0, el list_remove_element lo elimina correctamente de la lista pero devuelve la funcion false

### 📝 Código relevante

**_Código que no funciona_**
  
```
 t_list *lista = list_create();
   list_add(lista, 0);
    list_add(lista, 4);
    bool seElimino=list_remove_element(lista, 0);
    if (seElimino){
        log_info(logger, "Se elimino el elemento de la lista");
    }
    else{
        log_info(logger, "No se elimino el elemento de la lista");
    }
```

**_Código que si funciona_**
```
  t_list *lista = list_create();
    list_add(lista, 1);
    list_add(lista, 4);
    bool seElimino=list_remove_element(lista, 1);
    if (seElimino){
        log_info(logger, "Se elimino el elemento de la lista");
    }
    else{
        log_info(logger, "No se elimino el elemento de la lista");
    }
```

### 💻 Logs

_**Cuando lo ejecuté con el id 0**_
`[INFO]` 18:55:10:380 MEMORIA/(11541:11541): No se elimino el elemento de la lista `

_**Cuando lo ejecuté con el id 4**_
`[INFO]` 18:55:10:380 MEMORIA/(11541:11541): Se elimino el elemento de la lista`

**Comment by f-and** [comment]
Buenas Damian!
Para darte la respuesta corta, ¿de qué es esta lista? Porque a lo mejor les conviene usar la función [`list_remove_by_condition`](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/collections/list.h#L201), ya que el `list_remove_element` busca directamente al valor, y a lo mejor tiene que acceder a una estructura para saber el PID (por ejemplo `pcb->pid`); o la función [`list_remove`](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/collections/list.h#L180), que elimina el elemento de la lista en el índice 0 (osea el id en su caso).

La respuesta larga es: ¡Lo bueno de las commons es que podes [fijarte directamente como funciona el código!](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/collections/list.c#L98)
Fijate que, para empezar, la función recibe como parámetros la lista (como `t_list *self`) y un elemento (como **`void *element`**, importante que es un void *). Este elemento se busca en la lista igualándolo con cada otro elemento hasta encontrar uno que tenga la misma dirección (ya que es un void *), por lo tanto, viendo tus ejemplos, tiene sentido que no se elimine el elemento 0, porque, primero, se agrega a la tabla un elemento con **dirección 0**, que para empezar estaría mal por ser la dirección `NULL`, y segundo se intenta eliminar un elemento con la dirección 0, osea NULL, como nadie tiene esa dirección, te devuelve el error. Un código que sí funcionaria para **el caso de cargar números enteros en una lista** seria:

```c
int id = 0;
list_add (lista, &id);
list_remove_element (lista, &id);
```

Ya que estas leyendo la dirección de una variable `id` que tiene un valor 0.

No es algo que les pidamos o que tengan que aprender para los parciales o para la materia en sí, pero un consejo general es que si tienen alguna duda de como implementar una librería programada por alguien más fíjense la documentación del programa para darse una idea. 

Saludos.-

**Comment by DamianBlum** [comment]
ahh, ya entendi, muchas gracias!
