### ISSUE TITLE
Sobre Signal 

### ISSUE THREAD

**Issue by jotab0** [sisoputnfrba/foro#4000]
Buenas noches! 

Me surgió una duda en cuanto al manejo de los recursos:

Un proceso puede hacer signal aún cuando no tiene el recurso asignado o tiene que haber hecho previamente wait para poder hacerlo?

Entiendo que sí, pero como no lo aclara en el enunciado quería corroborarlo.

Saludos!

**Comment by mefederico** [comment]
Hola buenas! 

Si, si puede hacer signal sin tener el recurso asignado.

Saludos!

**Comment by jotab0** [comment]
Genial gracias! Buen finde
