### ISSUE TITLE
Consulta Con pruebas preliminares 

### ISSUE THREAD

**Issue by nicolasreypc** [sisoputnfrba/foro#4001]
Buenass, quería consultar si habrá una segunda tanda de pruebas preliminares, con un mayor nivel de exigencia o en las que se incluyan pruebas del FS. O hacer esto queda a disposición del grupo?

**Comment by iago64** [comment]
Buenas! Cómo va?

Para pruebas específicas del FS pueden ir pensándolas uds, nosotros cuando publiquemos las pruebas con FS seguramente sean las finales.

Saludos.-
