### ISSUE TITLE
Duda sobre el desplazamiento de la MMU

### ISSUE THREAD

**Issue by JoaquinMartinezUtn** [sisoputnfrba/foro#4002]
Buenas, tengo una duda sobre el uso del desplazamiento.
Como bien dice el enunciado una vez que se obtiene la direccion logica se calcula lo siguiente:
número_página = floor(dirección_lógica / tamaño_página)
desplazamiento = dirección_lógica - número_página * tamaño_página

Ahora bien, no le encuentro un uso a desplazamiento y entiendo que hay algo que no estoy viendo. Ya que una vez que consigo el frame(marco) de la dirección física (esta se obtiene con el pid y página sin necesidad de usar el desplazamiento) mediante la tlb ya sea que esté o se tenga que pedir a memoria y luego actualizar la tlb. Y por último retorna ese frame como la traducción de la memoria lógica, al menos eso entiendo de esta parte del enunciado “En caso afirmativo (TLB Hit) se deberá devolver la dirección física (o frame)”.

Ahora, lo que me hace dudar es que en ningún momento estoy utilizando el desplazamiento, entonces no entiendo que estoy haciendo mal.

Será que la traducción de dirección lógica a física tiene que retornar lo siguiente; marco * tam_pagina + desplazamiento ?

Desde ya, muchas gracias.
Saludos.

**Comment by LeandroCarbajales** [comment]
Buenas!

> Será que la traducción de dirección lógica a física tiene que retornar lo siguiente; marco * tam_pagina + desplazamiento ?

Exactamente! Es igual que en cualquier ejercicio de paginación visto en clases.
La DL se interpreta como página y desplazamiento, por lo que luego ese desplazamiento hay que sumarlo al marco obtenido como bien marcás, de lo contrario estarías accediendo siempre al primer byte de la página/marco.

Te aclara la duda?
Saludos!
      Lean

**Comment by JoaquinMartinezUtn** [comment]
Ah perfecto, me comi esa parte de la teoria. Muchas gracias.
