### ISSUE TITLE
Dialfs - Puntero Archivo

### ISSUE THREAD

**Issue by AGanem** [sisoputnfrba/foro#4003]
Buenas!
Cómo estás?

Quiero ver si entendí bien lo que significa el puntero archivo:

Lo estoy tomando como la cantidad de bytes desde el inicio del archivo a leer/escribir (distinto del archivo bloques.dat).
Por ejemplo:
Tamaño bloque = 10 bytes
Bloque inicial del archivo = 3
Puntero archivo = 4
Esto quiere decir que dentro del archivo de bloques (bloques.dat) el puntero está apuntando el byte 24?

Saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

Los punteros a los archivos parten del byte 0 **del archivo**, con lo cual, si tenes bloques de 10 bytes y el bloque inicial del archivo es el 3, considerando que **arrancamos a contar siempre desde 0**, estarías en el byte 4 del archivo o en el **byte 34 del archivo de bloques**.

Saludos.-

**Comment by AGanem** [comment]
Si, perfecto. Se arranca desde 0. Muchas gracias.
