### ISSUE TITLE
Duda conceptual FS

### ISSUE THREAD

**Issue by Santi24308** [sisoputnfrba/foro#4004]
Buenas, estoy un poco perdido a la hora de pensar, desde lo conceptual, como estructurar la parte de file system.

 Entiendo por otros issues y por enunciado que , desde que se crea una instancia i/o filesystem , es conveniente crear dos archivos (bloques.dat y bitmap.dat propio de esa instancia FS) para poder gestionar futuros archivos que se puedan llegar a crear (el primero no me queda claro como seria su funcionamiento y el segundo se que es para saber si un bloque esta o no ocupado ). Ademas estos archivos previos, no deberia perder su contenido al tirar el modulo abajo.  
 
 Ahora bien, dicho esto, por un lado mi duda esta en el funcionamiento de este primer archivo que se deberia crear "previamente" a que llegue una instruccion FS. Se que va a representar el espacio total que existe para almacenar bloques pero no se si es que de alguna forma tengo que ir "cargandole" los bloques a este archivo siempre y cuando estos no excedan su espacio limite .
 
 Por otro lado, a la hora de recibir un IO_FS_CREATE se que me deberia crear un archivo ocupando un solo bloque. Con respecto al tamanio inical de estos archivos todos se inicializan con tamanio nulo pero ocupando un bloque?
 
 Y por ultimo,tiene que ver con la modelizacion de un archivo. Entiendo que cada archivo creado tendra un metadata (el enunciado dice que es un archivo pero yo lo veo como un struct) que contendra bloque inicial y tamanio de archivo. En la teoria dice que el FCB es algo fundamental para la gestion de los archivos. Es necesario crearlos con todos los campos  necesarios (FCB) o unicamente con el metadata alcanzaria?
 
 Espero no preguntar burradas pero estoy medio en un cumple (si me ven con un solo ojo). Gracias de antemano !

**Comment by iago64** [comment]
Buenas! Cómo va?

Voy citando tu issue y contestando parrafo por parrafo asi es mas seguible la respuesta :)

> Entiendo por otros issues y por enunciado que , desde que se crea una instancia i/o filesystem , es conveniente crear dos archivos (bloques.dat y bitmap.dat propio de esa instancia FS) para poder gestionar futuros archivos que se puedan llegar a crear (el primero no me queda claro como seria su funcionamiento y el segundo se que es para saber si un bloque esta o no ocupado ). Ademas estos archivos previos, no deberia perder su contenido al tirar el modulo abajo.

No es conveniente, es necesario que creen los archivos para que el DialFS funcione.
En el caso del archivo de bloques.dat es una simulación de los bloques de un archivo, por lo que todos los datos que escribas en el FS va a terminar escrito ahi.


> Ahora bien, dicho esto, por un lado mi duda esta en el funcionamiento de este primer archivo que se deberia crear "previamente" a que llegue una instruccion FS. Se que va a representar el espacio total que existe para almacenar bloques pero no se si es que de alguna forma tengo que ir "cargandole" los bloques a este archivo siempre y cuando estos no excedan su espacio limite .

Si, ambos archivos deben crearlos ni bien inicia el módulo, en caso de que no exista, si existen simplemente levantan lo que encuentran.
En el caso del archivo de bloques.dat como dije en la respuesta anterior, **todo** lo que se escriba en el FS va a guardarse ahi, el tema es saber en que posición, entonces ahi vamos a la última respuesta.

> Por otro lado, a la hora de recibir un IO_FS_CREATE se que me deberia crear un archivo ocupando un solo bloque. Con respecto al tamanio inical de estos archivos todos se inicializan con tamanio nulo pero ocupando un bloque?

Efectivamente, creas el archivo, le asignas 1 bloque peeero el tamaño es 0 porque todavía no te llegó un truncate.

> Y por ultimo,tiene que ver con la modelizacion de un archivo. Entiendo que cada archivo creado tendra un metadata (el enunciado dice que es un archivo pero yo lo veo como un struct) que contendra bloque inicial y tamanio de archivo. En la teoria dice que el FCB es algo fundamental para la gestion de los archivos. Es necesario crearlos con todos los campos necesarios (FCB) o unicamente con el metadata alcanzaria?

El FCB es un archivo "similar" a los archivos de config que tienen 2 datos, bloque inicial y tamaño del archivo, cuando decimos similar es porque la idea es que los lean / escriban con las funciones de las configs de las commons y que no se vuelvan locos con eso.
La idea de estos archivos es que uds tengan la información necesaria para saber donde empieza y donde "termina" un archivo, donde termina lo pueden calcular utilizando el bloque inicial y el tamaño que viene dado en bytes.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @Santi24308 ! ¿Les sirvió la respuesta de Dami? Saludos

**Comment by Santi24308** [comment]
Buenas,disculpen la tardanza. Primero que nada gracias, me sirvió el hecho de trabajar el metadata como config y en cuanto a los otros dos archivos estoy más orientado.Si bien todavía tengo un vacío en cuanto a cómo trabajar el bloque.dat voy a seguir la pista de tener "posiciones" para ir cargando estos bloques. De nuevo, muchas gracias

**Comment by f-and** [comment]
Buenas Santi! Si necesitas mas ayuda con el archivo bloques.dat te recomiendo pegarle una ojeada a los issues #3263 y #3830, donde hablamos un poco al respecto, pero la corta es que tienen que manejar el bloques.dat como manejan la memoria, van a tener un cacho de void* mallocqueado con el tamaño de bloque por la cantidad de bloques, y este lo vas a vincular al archivo en sí mediante la función mmap (teniendo el archivo el mismo tamaño que el void*), de ahí, cada vez que modifiques el void* se va a modificar el archivo directamente. (Esto es lo más fácil igual, si quieren podrían trabajar con fwrite y fread, pero la idea en sí es eso, un archivo binario que se modifica activamente.
Avisa si te sirvio esta respuesta, y cualquier duda profundizamos. 
Saludos.-
