### ISSUE TITLE
Ruta de archivos fs

### ISSUE THREAD

**Issue by tomipodo** [sisoputnfrba/foro#4005]
Buenas! Cómo andan?
Estabamos haciendo el bloques.dat y nos surgió una duda. Vemos que el path de ejemplo es este: /home/utnso/dialfs.
La carpeta dialfs la debemos crear a mano? O las carpetas que no existan tienen que crearse automaticamente dependiendo del path que nos llegue?

Muchas gracias, saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

Como bien dijiste es un ejemplo, uds pueden crear las carpetas que quieran mientras después en la entrega nos digan donde están los archivos bitmap.dat, bloques.dat y los fcb.

Saludos.-

**Comment by tomipodo** [comment]
Genial, entonces solo para confirmar: todas las carpetas deberían estar creadas de antemano, no?
Saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

Si

Saludos.-

**Comment by tomipodo** [comment]
Bárbaro gracias!
