### ISSUE TITLE
Kernel: Logs mínimos y obligatorios. Ingreso a Ready.

### ISSUE THREAD

**Issue by eitan-wajsberg** [sisoputnfrba/foro#4006]
¡Hola, buenas tardes!

Tengo una consulta sobre los logs mínimos y obligatorios del Kernel, específicamente en el log de "Ingreso a Ready", cuyo formato es el siguiente: "Cola Ready / Ready Prioridad: [< LISTA DE PIDS >]". ¿Cuál de estos ejemplos de uso es el correcto?

1. "Cola Ready: [0 1 2]" y luego otro log con "Ready Prioridad: [3 4]".
2. "Cola Ready / Ready Prioridad: [0 1 2 3 4]".

**Comment by RaniAgus** [comment]
¡Buenas! Solamente el log con la queue a la que ingresó es suficiente, es decir:
a. Si ingresó a Ready: "Cola Ready: [0, 1, 2]"
b. Si ingresó a Ready+: "Cola Ready Prioridad: [3, 4]"

Saludos

**Comment by eitan-wajsberg** [comment]
Perfecto, gracias!
