### ISSUE TITLE
Consulta varios FS en una misma computadora

### ISSUE THREAD

**Issue by papiness77** [sisoputnfrba/foro#4007]
Buenas, la consulta es si se puede tener eso. Por ejemplo yo estaba pensando en que tendria varias carpetas cada una llamada con el nombre que le doy a la interfaz y cada una de esas carpetas tendria su archivo bloques.dat, el bitmap y los archivos de metadata, de los files que es duenio esa interfaz.

De esto me surgio otra duda, y es relacionada con las configs. Porque yo cuando cierro el modulo quiero que las carpetas esas contengan la informacion y no la pierdan. Y si quiero volver a acceder a este modulo lo haria ingresando el nombre de la interfaz (que seria el nombre de la carpeta donde estan el bitmap y lo demas), por la consola cuando inicio el modulo. Y ahi tambien yo ingreso por consola el archivo config que va a usar el modulo porque hay varios tipos de config. Entonces que tendria que hacer si en ese archivo de config el block size y el block count son distintos de los originalmente asignados a esta interfaz? Achico el archivo de bloques.dat perdiendo informacion que tenia? Entonces ahi me quedarian archvios de metadata que son inutiles.

**Comment by RaniAgus** [comment]
Buenas,

> Por ejemplo yo estaba pensando en que tendria varias carpetas cada una llamada con el nombre que le doy a la interfaz y cada una de esas carpetas tendria su archivo bloques.dat, el bitmap y los archivos de metadata, de los files que es duenio esa interfaz.
> De esto me surgio otra duda, y es relacionada con las configs. Porque yo cuando cierro el modulo quiero que las carpetas esas contengan la informacion y no la pierdan. Y si quiero volver a acceder a este modulo lo haria ingresando el nombre de la interfaz (que seria el nombre de la carpeta donde estan el bitmap y lo demas), por la consola cuando inicio el modulo.

Sí, podrías tener distintos DialFS, pero la ruta en donde se encuentran depende de la variable `PATH_BASE_DIALFS` configurada, no del nombre de la interfaz.

> Entonces que tendria que hacer si en ese archivo de config el block size y el block count son distintos de los originalmente asignados a esta interfaz? Achico el archivo de bloques.dat perdiendo informacion que tenia? Entonces ahi me quedarian archvios de metadata que son inutiles.

No creemos que tenga ningún valor el probar ese caso. Si queremos cambiar el tamaño del File System les vamos a pedir borrar los archivos de la prueba anterior o, sino, cambiar la ruta en donde esté montado, lo que les sea más cómodo.

Saludos
