### ISSUE TITLE
Errores que podrían hacer que la CPU devuelva el contexto

### ISSUE THREAD

**Issue by rochoacharlin** [sisoputnfrba/foro#4008]
¡Buenas! 
Tengo una duda con respecto a  la devolución del contexto desde la CPU al kernel. Se dice que una de las causas puede ser un error, ¿pero qué error podría ser ese además del out of memory recibido de la memoria?

### 📔 Citas del enunciado/videos
Durante el transcurso de la ejecución de un proceso, se irá actualizando su Contexto de Ejecución, que luego será devuelto al Kernel bajo los siguientes escenarios: finalización del mismo (instrucción EXIT o **ante un error**), solicitar una llamada al Kernel, o deber ser desalojado (interrupción).

**Comment by RaniAgus** [comment]
¡Buenas! Es una generalización: para este TP, el único error posible es Out Of Memory. Saludos

**Comment by rochoacharlin** [comment]
¡Gracias!
