### ISSUE TITLE
DIALFS: pasarse del EOF al escribir o leer bloques

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#4009]
Buenas! 
Quería preguntar por si las dudas si hay que atrapar a algún proceso que quiera acceder a bytes que se pasen del tamaño de archivo; esto podría darse de las siguiente forma:
pongo en el registro tamaño un tamaño superior a (tam archivo - puntero archivo) esto se puede lograr poniendo el puntero muy grande o con un registro tamaño muy grande.
Al ejecutar esta instrucción el modulo file system escribe o lee en el archivo de bloques pero estamos accediendo a uno o mas bloques que no le pertenecen al archivo.

Entonces la pregunta es si efectivamente se debe checkear esto o se puede obviar. 

Muchas gracias como siempre

**Comment by mefederico** [comment]
Hola buenas!

No vamos a probar ese caso, si quieren chequearlo para poder detectar alguna inconsistencia pueden hacerlo simplemente loggeando el caso como un error y manejar como más prefieran la continuación del programa, incluso terminando el FS con un exit

Saludos!

**Comment by GonTurri** [comment]
Dale gracias fede
