### ISSUE TITLE
Duda compactaci{on FS y manejo de excepciones.

### ISSUE THREAD

**Issue by Lopez-AN** [sisoputnfrba/foro#4010]
Buenas tardes.

Tengo la siguiente duda con la compactación.

Cuando tenemos un archivo que necesita aumentar su tamaño con truncate, luego de compactar y trasladarlo al area contigua, el sitio donde estaba originalmente queda un hueco...
¿Esto imagino no estaría bien?  ¿Como podríamos resolverlo?  Lo único que se me ocurre es mandar los bloques del archivo en cuestión a una variable en memoria, marcar como libres los bloques donde está el archivo, compactar y luego volcar el archivo al area contigua.

Adjunto una captura de ejemplo 
![image](https://github.com/sisoputnfrba/foro/assets/15198397/250077d8-3653-4553-b59b-7b94ea3a64cb)

Y por último queríamos saber que hacer en caso de excepciones en el FS, por ejemplo, intentar escribir más datos del tamaño del archivo, crear  un archivo que ya existe, o si nos quedamos sin bloques libres en el FS...  en esos casos deberíamos avisarle al kernel que hubo una excepción para mandar a salida el proceso??

Desde ya gracias!

**Comment by mefederico** [comment]
Hola buenas! 

No está definido como hacer la compactación así que pueden implementarla como más les parezca, en el coloquio nos tendrán que explicar como la hicieron y porqué. Por lo pronto esa implementación estaría bien, pero tendrías que considerar que tal vez tengas que utilizar ese bloque también para el archivo, así que eventualmente también lo van a tener que mover

Creo que no hace falta levantar todos los bloques juntos a memoria, pero es parte de como lo implementen y va a estar bien lo que hagan

Saludos!

**Comment by Lopez-AN** [comment]
gracias!
