### ISSUE TITLE
Tamaño especificado en metadata

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#4011]
Buenas,
Tenía dos dudas con respecto al tamaño, suponiendo bloques de 32 bytes:
1- Cuando creamos un archivo debemos asignarle un bloque pero poner que tiene tamaño 0 igualmente. Si se le hace un truncate a 20bytes, debemos poner que su tamaño ahora es 20bytes o 32bytes?

2- Es parecida a la uno, cuando un archivo tiene 64 bytes, osea dos bloques y hace un truncate de 65, el tamaño que tenemos que poner en el config es 65 o 32*3=96?

**Comment by RaniAgus** [comment]
¡Buenas! En ambos casos deben poner el tamaño al cual fue truncado, es decir:
1. 20 bytes
2. 65 bytes
Saludos

**Comment by rood8592** [comment]
Gracias y para memoria aplica lo mismo? Porque el log del resize no lo hicimos de esa manera. Si se hace un resize 20, el tamaño actual que tira el log es 0 y el tamaño a ampliar 20 pero cuando se hace un resize nuevamente a 34, por ej, el log tira que el tamaño actual es 32 (32*1) y el tamaño ampliar 2 (34-32). Porque el actual se calcula como tam_pagina*cant_paginas. Todo esto suponiendo paginas de 32 bytes.

**Comment by RaniAgus** [comment]
No hace falta que lo cambien en Memoria si lo tienen así.

**Comment by rood8592** [comment]
Perfecto, gracias!!
