### ISSUE TITLE
Duda registro puntero en FS

### ISSUE THREAD

**Issue by EstebanHurtado0** [sisoputnfrba/foro#4012]
Hola, en el enunciado nos dice que se escribe en un archivo a partir del registro puntero, ese registro puntero son bytes que indican desde donde escribir. Pero la duda es, ese registro indica a partir del primer bloque? o es a partir del inicio del archivo?
Otra duda. puede ser que nos den para escribir algo que sea mas grande que el tamaño del archivo?

**Comment by mefederico** [comment]
Hola buenas! 

Indica desde donde inicia el archivo, es decir, desde tam_bloque * bloque_inicial + puntero = desde ahi empiezo a escribir

No, no vamos a escribir algo más grande que el tamaño del archivo, ni nos vamos a pasar del tamaño del archivo. Si quieren manejar la situación en este issue hay una opción de como manejarlo https://github.com/sisoputnfrba/foro/issues/4009

Saludos!

**Comment by EstebanHurtado0** [comment]
Gracias
