### ISSUE TITLE
Loggear valor numérico de 3 bytes

### ISSUE THREAD

**Issue by rochoacharlin** [sisoputnfrba/foro#4013]
¡Hola!
Estaba viendo el issue #3900, donde dice que cada fragmento que se lee/escribe (entre CPU y memoria) debe loggearse, y noté que el valor de un uint32_t podría llegar a ser dividido en 3 bytes en una página y 1 byte en otra página. En el MOV_OUT, esta cantidad de bytes que estamos dividiendo del dato inicial la guardamos en un void* que luego le enviamos a la memoria para que escriba los bytes. Mi duda es cómo hacer para poder registrar en el log el valor numérico de esos 3 bytes que escribí.

### 📝 Código relevante
Por ejemplo:
```c
int main(int argc, char *argv[])
{
    uint32_t *num = malloc(sizeof(uint32_t));
    *num = 123;
    void *primera_parte_3_bytes = malloc(3);
    void *segunda_parte_1_byte = malloc(1);
    memcpy(primera_parte_3_bytes, num, 3);
    memcpy(segunda_parte_1_byte, num+3, 1);
    log_info(logger, "primera parte (3 bytes): %?????", primera_parte_3_bytes); // <--- acá cómo hago?
    log_info(logger, "segunda parte (1 byte): %d", *(uint8_t *)segunda_parte_1_byte);

    return 0;
}
```

**Comment by mefederico** [comment]
Hola buenas! 

Podes hacer como esta en este comentario de dami https://github.com/sisoputnfrba/foro/issues/3781#issuecomment-2133708741 que explica como reconstruir un valor, pero si nos detenemos antes y solo hacemos el primer memcopy

```C
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>

int main()
{
    
    uint32_t registro_ecx = 64;
    uint32_t registro_ecx_reconstruido = 0;
    
    void* registro_ecx_parte_1 = malloc(2);
    void* registro_ecx_parte_2 = malloc(2);
    
    void* registro_ecx_puntero = &registro_ecx;
    void* registro_ecx_reconstruido_puntero = &registro_ecx_reconstruido;
    
    memcpy(registro_ecx_parte_1, registro_ecx_puntero, 2);
    memcpy(registro_ecx_parte_2, registro_ecx_puntero + 2, 2);
    
    printf("El valor de ECX completo es: %d \n", registro_ecx);
    printf("El valor de ECX antes de reconstruirlo: %d \n", registro_ecx_reconstruido);
    
    memcpy(registro_ecx_reconstruido_puntero, registro_ecx_parte_1, 2);
    // Sacamos este
    //memcpy(registro_ecx_reconstruido_puntero + 2, registro_ecx_parte_2, 2);
    
    printf("El valor de ECX despues de reconstruirlo: %d \n", registro_ecx_reconstruido);

    return 0;
}
```

podrían imprimir sin problemas todos los números parciales que quieran, los invito a probar ese snip de código con las variantes que necesiten

Saludos!

**Comment by rochoacharlin** [comment]
Genial, ahí pude hacerlo. ¡Muchas gracias y saludos!
