### ISSUE TITLE
Tamaño archivo en el metadata

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#4014]
Hola buenas tengo una pregunta con el valor que tiene que tener TAMANIO_ARCHIVO en el metadata cuando creamos el archivo.
Tendria que tener el tamaño de un bloque? O un 0?

> Creación de archivos
> Al momento de crearse un archivo, va a comenzar ocupando un bloque del FS aunque su tamaño sea 0 y luego el mismo se podrá extender o disminuir por medio de de la función IO_FS_TRUNCATE.

**Comment by mefederico** [comment]
Hola buenas! 

Tienen que poner 0
Issue relacionado -> https://github.com/sisoputnfrba/foro/issues/4011
 
Saludos!
