### ISSUE TITLE
Duda read en FS

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#4015]
> IO_FS_READ (Interfaz, Nombre Archivo, Registro Dirección, Registro Tamaño, Registro Puntero Archivo): Esta instrucción solicita al Kernel que mediante la interfaz seleccionada, se lea desde el archivo a partir del valor del Registro Puntero Archivo la cantidad de bytes indicada por Registro Tamaño y se escriban en la Memoria a partir de la dirección lógica indicada en el Registro Dirección.

Hola buenas tengo una duda aca con el registro puntero. Este registro indicaria el desplazamiento dentro del archivo? Es decir, tendriamos que tomar el bloque inicial del archivo y sumarle el registro puntero para saber desde donde  empezar a leer?

**Comment by RaniAgus** [comment]
¡Buenas!

> Hola buenas tengo una duda aca con el registro puntero. Este registro indicaria el desplazamiento dentro del archivo?

Sí

>  Es decir, tendriamos que tomar el bloque inicial del archivo y sumarle el registro puntero para saber desde donde empezar a leer?

Exactamente

Saludos

**Comment by JoaquinCoaricona** [comment]
Gracias
