### ISSUE TITLE
Duda sobre el MOV_OUT

### ISSUE THREAD

**Issue by BranVallejo** [sisoputnfrba/foro#4016]
Hola buenas tardes, cuando hago el MOV_OUT y escribo en memoria un uint32_t ¿Hay que contemplar el caso en el que medio numero me quede en una pagina y medio en otra? Porque estaba pensado que me pueden quedar 2 bytes disponibles en la pagina y necesite cargar un uint_32, entonces tengo que copiar mitad en una pagina y mitad en otra o directamente salto a la siguiente y lo copio completo? ¿O esto solo se aplica al COPY_STRING?

**Comment by mefederico** [comment]
Hola buenas! 

Tienen contemplar el caso de escribir un pedazo en una pagina y el resto en otra

Saludos!

**Comment by f-and** [comment]
Buenas! Aprovecho para ponerme un poco en modo 👮‍♂️ y pedir que se fijen los issues anteriores, ya que es una duda que se respondió ampliamente antes, por ejemplo [acá](https://github.com/sisoputnfrba/foro/issues/3781#issuecomment-2133438028), [acá](#3963), [acá](https://github.com/sisoputnfrba/foro/issues/3877#issuecomment-2156281836), [acá](https://github.com/sisoputnfrba/foro/issues/3976#issuecomment-2176779815) (para MOV_IN aunque responde lo mismo), y [acá](https://github.com/sisoputnfrba/foro/issues/3854#issuecomment-2150663690), solo por buscar unos casos similares.
Obvio sin ofensa, vamos a estar siempre para contestar, pero fijense así no se quedan esperando una respuesta por si no estamos! :)

**Comment by BranVallejo** [comment]
Gracias por la ayuda, cierro el issue.
