### ISSUE TITLE
Implementación de la compactación

### ISSUE THREAD

**Issue by nicolasvultaggio** [sisoputnfrba/foro#4017]
Buenas, me surgieron algunas dudas sobre QUÉ ES VÁLIDO y qué NO es válido a la hora de compactar y resolver cualquier problema sobre el espacio contiguo, el enunciado dice lo siguiente:

> Puede darse la situación que al momento de querer ampliar un archivo, dispongamos del espacio disponible pero el mismo no se encuentre contiguo, por lo que vamos a tener que compactar nuestro FS para agrupar los bloques de los archivos de manera tal que quede todo el espacio libre contiguo para el archivo que se desea truncar. Luego de compactar el FS, se deberá esperar un tiempo determinado por el valor de configuración de RETRASO_COMPACTACION para luego continuar con la operación de ampliación del archivo.

es válida una implementación en la que NO SOLO se compacte al querer agrandar el tamaño de un archivo, si no también cuando se le desasignan bloques? Esto con el objetivo de no dejar "huecos" o, mejor dicho, bloques libres entre bloques asignados:

por ejemplo: supongamos que al archivo violetita le queremos quitar dos bloques

![image](https://github.com/sisoputnfrba/foro/assets/131707089/d0b81284-f060-4618-b41b-968e7b940777)

otra pequeña duda que me surgio, si queremos escribir muchos bloques que sabemos que estan contiguos, se pueden escribir distintos bloques de distintos archivos en un solo fwrite, o es inválido? o sea, si o si tienen que escribirse archivo por archivo?

y despues para asignar, podría ser una cosa así: (se compacta también)

![image](https://github.com/sisoputnfrba/foro/assets/131707089/8f3a25cb-82f4-456b-b223-fc3c7e2eec00)

buen finde! perdón que no pude hacer la pregunta en la queue de discord hoy, tuve clase a esa hora :(

**Comment by RaniAgus** [comment]
¡Buenas!

> es válida una implementación en la que NO SOLO se compacte al querer agrandar el tamaño de un archivo, si no también cuando se le desasignan bloques? Esto con el objetivo de no dejar "huecos" o, mejor dicho, bloques libres entre bloques asignados

No es válido. Recordemos que la compactación es una operación extremadamente lenta, por lo que no queremos hacerla a menos que sea estrictamente necesario.

> otra pequeña duda que me surgio, si queremos escribir muchos bloques que sabemos que estan contiguos, se pueden escribir distintos bloques de distintos archivos en un solo fwrite, o es inválido? o sea, si o si tienen que escribirse archivo por archivo?

`IO_FS_WRITE` recibe por parámetro un único archivo, por lo que no debería darse el caso en el que quieras escribir varios en una única operación.

> y despues para asignar, podría ser una cosa así: (se compacta también)

Todos estos pasos:

![image](https://github.com/sisoputnfrba/foro/assets/39303639/11a1129a-cdfa-4b4b-8170-9369db035c4d)

Serían una implementación válida de compactación 👍🏻
La misma se dispara con un `IO_FS_TRUNCATE`, no con un `IO_FS_WRITE`, ya que es lo que les permite poder ampliar el tamaño del archivo:

![image](https://github.com/sisoputnfrba/foro/assets/39303639/55d3b8b5-7b4b-45c9-b073-52ee058baeba)

Saludos

**Comment by nicolasvultaggio** [comment]
buenisimo, muchas graciass!!!
