### ISSUE TITLE
FS WRITE

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#4018]
Hola buenas tengo una duda sobre algo que pasa cuando verifico si se escribio bien en la interfaz algo que llego por esa instruccion.

La variable cantydadBytesMalloc vale 16. En la interfaz escribi 16 bytes que son el string "HOLA COMO ESTASX", no incluye al barra 0 porque eso lo agrego yo despues justamente para este tipo de casos. Yo guardo en ese char * lo que copie y como quizas no termina con un barra 0, entonces en el malloc agrego un espacio y despues pongo el barra 0 para poder tener el string justo 
y poder loggearlo. Pero al hacer el mecpy de 16 bytes aparecen caracteres de mas. Es cierto que yo tengo ese byte libre donde despues pongo el barra 0 pero me parece raro que se agreguen 4 letras.
Despues de eso creo que esta funcionando bien porque esto solo lo hago para loggear si lo que escribi esta bien y como pongo el barra 0 manualmente se termina loggeando bien, pero esto me hacia dudar porque no se porque podria pasar.
Este es el codigo:
```C
     char *reservaParaLoggear = malloc(cantidadBytesMalloc + 1);
    //Copio el contenido justo, copio desde el void* del mmap osea desde el contenido
    //directo del archivo y lo guardo en la reserva que hice para loggear
    memcpy(reservaParaLoggear,punteroADondeTengoQueEscribirLoQueLeoDeMemoria,cantidadBytesMalloc);
    //Establezco el ultimo bytes con el barra 0 para poder loggearlo con %s
    reservaParaLoggear[cantidadBytesMalloc] = '\0';
    //Loggeo
    log_info(logger,"%s",reservaParaLoggear);
    //Libero la memoria que solo pedi para loggear que todo haya salido bien
    free(reservaParaLoggear);

```
Asi es como se ve al debuggear
![image](https://github.com/sisoputnfrba/foro/assets/112731246/391dd5d6-06ad-4e7b-90f4-56e1c3608c52)

En el archivo bloques.dat creo que se estan escribiendo bien las cosas. El ERROR ERROR lo puse yo para hacer una comprobacion
antes.
`memcpy(contenidoFS + 16,"ERROR ERROR",12);`
```Prolog
utnso@utnso:~$ cd FileSystem/

utnso@utnso:~/FileSystem$ xxd bloques.dat 

00000000: 484f 4c41 2043 4f4d 4f20 4553 5441 5358  HOLA COMO ESTASX

00000010: 4552 524f 5220 4552 524f 5200 0000 0000  ERROR ERROR.....

00000020: 0000 0000 0000 0000 0000 0000 0000 0000  ................
```
Si en vez de copiar 16 bytes como estaba en el memcpy anterior, pongo 15 entonces no se copia la X y tampoco se copian las 4 letras que aparecieron despues
![image](https://github.com/sisoputnfrba/foro/assets/112731246/bc089904-60bb-4753-a866-7453644dea51)

Si en el malloc no reservo un byte extra para poner el barra 0 y solo pongo los 16 entonces pasa lo mismo, aparecen esas 4 letras 
![image](https://github.com/sisoputnfrba/foro/assets/112731246/08cd1975-ac02-47ba-91f3-04760915d200)

Por las dudas, el puntero lo armo asi:
```
int posicionInicioArchivo = bloque_inicial * block_size;
void *punteroADondeTengoQueEscribirLoQueLeoDeMemoria = contenidoFS + posicionInicioArchivo + registroPuntero;
```

**Comment by mefederico** [comment]
Hola buenas!

Cuando ves el hexdump del debugger lo que estas viendo es la memoria de la computadora, más precisamente la sección que se asigno a tu programa. Cuando se habla que es continuo no es mentira, tienen toda la información de tu programa ahí

Si pones el cursor sobre la variable del debugger en `reservarParaLoggear` te aparece un símbolo de un archivo binario, si lo clickeas te extiende la memoria si bajas sobre ese archivo vas a empezar a ver el stack de memoria de tu código

Sabiendo esto, que está pasando?
 Bueno lo más probable es que como esa variable es un `char*` el debugger intenta mostrarte todo hasta el primer \0 (fin de cadena) que encuentre, como no se lo pusiste (al momento que mandas las fotos del debugger) continua hasta que eventualmente encuentra un \0.

Por que si copio solo 15 caracteres no muestra datos de más?
Bueno posiblemente sea solo una coincidencia que antes de copiar la X ahí había un \0

Por que es tan consistente entre las distintas veces que corro el programa?
Paginación y caches, el SO trata de poner todo siempre en el mismo lugar

Por que justo `tura`?
Posiblemente tu programa en algún momento reservo memoria para alguna palabra terminada en `tura`, o tienen una variable local con una valor similar y por eso aparece eso.

Ya que agregas el \0 no vas a tener ningún problema en el logger

TL;DR El debugger al ver que es una variable `char*` intenta mostrarlo como una cadena de caracteres hasta encontrar un \0 como no se lo pusiste continua leyendo cosas hasta que encuentra \0 o el SO se lo permita

Saludos!

**Comment by JoaquinCoaricona** [comment]
Muchas gracias. Tengo una duda mas pero es de enunciado, abro otro issue
