### ISSUE TITLE
DUDAS CON SEMÁFOROS Y GRADO DE MULTIPROGRAMACIÓN

### ISSUE THREAD

**Issue by manugomezp** [sisoputnfrba/foro#4019]
Hola, buenas! estamos intentando resolver el cambio de grado de multiprogramación y tenemos una duda con respecto al uso de semáforos.
El grado de multiprogramación lo manejamos con un semáforo. Nuestro problema se encuentra al intentar disminuir el mismo durante la ejecución, estando el grado de multiprogramación está al máximo. Por ejemplo, iniciar el sistema con un grado de multiprogramación 10, enviarle 50 programas iguales, y una vez que hayan entrado 10 al circuito del planificador corto, bajar el grado de multiprogramación a 5. En ese caso, cuando empezamos a matar procesos, en lugar de matar 5 y que queden los 5 restantes, entran un par más (provenientes de new) disminuyendo el grado de multiprogramación paulatinamente a 9, 8, 7... y terminamos ejecutando hasta el proceso 14/15 para que solo haya 5 en el circuito. Esto no sucede cuando decidimos aumentar el grado de multiprogramación en ejecución, lo cual funciona perfecto. Nuestra sospecha es que el semáforo consume y almacena en la cola que pertenece al struct del semáforo y esos procesos almacenados son los que luego son agregados al circuito sin que corresponda. Queríamos saber si hay forma de evitar este comportamiento, ya sea modificando la lógica del programa o mediante otra estrategia para la implementación.

**Comment by LeandroCarbajales** [comment]
Buenas!
Lo más simple que se me ocurre para el caso de reducir el grado de multiprogramación sería, siguiendo tu ejemplo de tenerlo inicialmente en 10 y reducirlo a 5, es que los primeros 5 procesos que finalicen no le hagan signal() al semáforo de grado de multiprogramación, de esta manera no pasaría ninguno de los que esté en new.

**Comment by manugomezp** [comment]
Intentamos eso y también otras cosas pero todavía no pudimos lograr que funcione bien. El sábado vamos a consultarlo en soporte. Cierro el issue. Cualquier cosa lo vuelvo a abrir para repreguntar. Gracias por la respuesta! Saludos.
