### ISSUE TITLE
Dudas sobre memoria

### ISSUE THREAD

**Issue by lseijasferraudo** [sisoputnfrba/foro#4020]
Buenos días quería consultar un par de temas de la memoria, 
ya que estaba con problemas para plantearlo:
1. al momento de plantear como vamos a hacer la memoria seria
void* memoria = malloc(tam_mamoria);
y no sabíamos si debíamos crear una lista de paginas para la memoria o solo
para los procesos

2. en la instrucción mov_in no termino de entender bien como funcionaria, que seria el registro
de datos y el registro de dirección que recibiría ?

3. Al momento de guardar las instrucciones que se encuentran en los los scripts de memoria, creamos un
diccionario similar a esto:   { PID : INSTRUCCIONES[] } dentro de memoria.
La CPU al solicitar una instruccion a la memoria, le pasa el PC con su PID y esta le responde gracias a la
estructura creada anteriormente. 
En nuestro buffer de memoria (void*) con un tamanio de malloc(TAM_MEMORIA) hay que poner las instrucciones 
que leo de cada script o ya con la estructura que creamos esta bien?

**Comment by mefederico** [comment]
Hola buenas o/

1. Los procesos son los que tienen paginas, tendrían una tabla de páginas por proceso. La memoria tiene marcos, antes de pensar en que agregar piensen en que necesidad tienen y como lo resolverían, si necesitan o no una lista de páginas/marcos.
2. Como bien dice el enunciado, el registro de datos es donde van a tener que guardar el dato que leen de la DL de la memoria

Los registros están especificados en esta parte del [enunciado](https://docs.google.com/document/d/1-AqFTroovEMcA1BfC2rriB5jsLE6SUa4mbcAox1rPec/edit#heading=h.g8wwscbuoevu)
Pasar de DL a DF para poder pedirle a la memoria el dato a leer está en esta parte del [enunciado](https://docs.google.com/document/d/1-AqFTroovEMcA1BfC2rriB5jsLE6SUa4mbcAox1rPec/edit#heading=h.q1twu0jdsrm) 

Tal vez este issue te ayude a entender más estas interacciones https://github.com/sisoputnfrba/foro/issues/3566
También están las pruebas pre-eliminares donde pueden ver ejemplos reales de como vamos a probar esos comandos https://github.com/sisoputnfrba/c-comenta-pruebas y de secuencias validas de los distintos comandos

3. Como bien dice el [enunciado](https://docs.google.com/document/d/1-AqFTroovEMcA1BfC2rriB5jsLE6SUa4mbcAox1rPec/edit#heading=h.8fe1iyjh7574) 

> Al momento de recibir la creación de un proceso, la memoria de instrucciones deberá leer el archivo de pseudocódigo indicado y generar las estructuras que el grupo considere necesarias para poder devolver las instrucciones de a 1 a la CPU según ésta se las solicite por medio del Program Counter.

Su implementación está perfecta, las instrucciones no tienen que estar en la memoria principal.

Espero que los links te sean de utilidad, cualquier cosa podes seguir preguntando!

Saludos!
