### ISSUE TITLE
Direcciones fisicas

### ISSUE THREAD

**Issue by tomassagrada** [sisoputnfrba/foro#4021]
Buenas, me surgieron algunas dudas respecto a las traducciones sobre todo de múltiples direcciones físicas:

1_ Cuando me llega una instrucción de IO en la cual se debe leer o escribir en memoria, yo no voy a saber que es lo que se va a escribir, entonces en que me baso para saber cuantas paginas va a ocupar, lo que pensé es que podría tenerse en cuenta el tamaño máximo para ambos casos, pero para el caso de escritura si se utiliza menos que ese tamaño, IO debería administrar que direcciones físicas usar y cuales no le hacen falta, pero para ello necesitaría poder "dividir" lo que se escriba según el tamaño de las paginas, pensé que podría mandarle el tamaño de pagina cuando sea el caso de que lo necesite, pero no se si esto esta bien desde el punto de vista de la consigna.

2_ mi otra duda viene también por la parte de que estoy entre dos opciones de métodos para escribir o leer en memoria en casos de múltiples dir físicas, uno es en el que yo separo la palabra y envió a memoria una dir física con un pedazo de palabra y así hasta completar lo que se tenga que escribir (lo mismo para leer e ir yo "armando"  la palabra). La otra manera es en la que le mando la palabra a memoria, todas las dir físicas y ya memoria se encarga de ver como distribuye la palabra, el problema es que no se cual seria la mas correcta en términos de consigna. Además el problema de la primera es que vuelve a que IO necesita el tamaño de la pagina, y bueno caigo en la misma duda que en la anterior pregunta. 

Desde ya gracias y un saludo.

**Comment by mefederico** [comment]
Hola buenas! 

1. No vamos a ingresar datos de más ni de menos. Si quieren poner el control pueden pedir que el usuario reingrese los datos! Para hacer las traducciones de DL y DF usan el tamaño a leer que es parámetro

2. Como ustedes prefieran, lo único que tienen que respetar son los retardos de memoria para cada tipo de mensaje. Yo cortaría el contenido desde CPU también creando un mensaje parecido a "escribí en la dirección X el contenido Y de L longitud"

Saludos!

**Comment by RaniAgus** [comment]
¡Buenas! Me sumo solo para recomendarte chusmear este issue relacionado: https://github.com/sisoputnfrba/foro/issues/3863#issuecomment-2162963947 Saludos

**Comment by tomassagrada** [comment]
Listo ahora ya se como hacer, gracias por las respuesta y gracias por el issue.
