### ISSUE TITLE
FS

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#4022]
Hola buenas tengo una duda sobre el FS. Podria pasar que cuando manden a escribir o leer algo en el FS se pasen del tamaño del archivo? por ejemplo el archivo tiene solo 1 bloque de 200 bytes y mandan a escribir o leer 10 bytes con un registro puntero de 195. Entonces habria 5 que estarian de mas. Estos casos se podian dar? o siempre se va a mantener dentro del espacio que tiene el archivo. Gracias

**Comment by mefederico** [comment]
Hola buenas! 

No, no es algo que queramos probar. Vamos a hacer lecturas validas solamente.

Saludos!

**Comment by JoaquinCoaricona** [comment]
Gracias
