### ISSUE TITLE
Duda sobre la asignación de marcos a las páginas y la memoria contigua

### ISSUE THREAD

**Issue by ValentinaThiwissen** [sisoputnfrba/foro#4023]
Hola, ¿qué tal? Les escribimos por una consulta que tenemos con el módulo de memoria. La manera en la que nosotros afrontamos la consigna fue así:

1. Primero, Kernel nos avisa sobre la creación de un proceso, por lo que cargamos a una tabla global de páginas un proceso nuevo con una lista de páginas vacías.
2. CPU nos manda un resize con el PID del proceso ya creado por Kernel, donde nos indica el tamaño del proceso, y calculamos la cantidad de páginas posibles que puede tener en base al tamaño recibido de CPU y el tamaño predefinido en el config de memoria.

Ahora, nosotros teníamos la duda de si, por ejemplo: Si CPU o I/O nos manda una solicitud de escritura, para un proceso que tiene 3 páginas de 20 bytes, que va desde la dirección física del byte 15 al 35:

- Tenemos que escribir el valor que nos manden en la memoria contigua según las direcciones recibidas (O sea escribimos en la memoria contigua de 15 a 35 y ya está)
- Tenemos que asignar las páginas 1 y 2 del proceso a los marcos libres de la memoria contigua y escribir el valor en donde tengamos espacio disponible (O sea, nos quedan las páginas del proceso 1 y 2 ocupadas en, por ejemplo, los dos primeros marcos de la memoria contigua, que serían los dos que tenemos libres)

En el caso de que sea el primero, nos encontramos con la duda de entonces: ¿Cuándo se asignan las páginas a los marcos?

Espero que más o menos se entienda todo.

Saludos!

**Comment by LeandroCarbajales** [comment]
Buenas!
Los marcos se asignan al momento de hacer el resize, no al momento de leer/escribir.
Luego, en tu ejemplo, lo más probable es que te pidan 2 escrituras por separado ya que los marcos asignados a esas 2 páginas no tienen por qué estar contiguos.

**Comment by ValentinaThiwissen** [comment]
Genial, gracias! Entonces, ¿todas las páginas se asignan automáticamente a los marcos apenas viene una instrucción de resize?

**Comment by LeandroCarbajales** [comment]
>  ¿todas las páginas se asignan automáticamente a los marcos apenas viene una instrucción de resize?

Exactamente!

> ¿Eso no significaría que las páginas nunca estarían desocupadas?

A qué te referís con "desocupadas"?

**Comment by ValentinaThiwissen** [comment]
Con desocupadas me refiero a que no tengan un marco asignado en la memoria general.
Otra consulta, qué pasaría con las páginas de un proceso cuándo kernel nos pida desocupar?

**Comment by LeandroCarbajales** [comment]
> Con desocupadas me refiero a que no tengan un marco asignado en la memoria general.

Si no tuvieran un marco asignado en la memoria sería inutilizables dado que no hay un esquema de memoria virtual o paginación bajo demanda.

> qué pasaría con las páginas de un proceso cuándo kernel nos pida desocupar?

Se marcarían sus correspondientes frames como libres.

**Comment by ValentinaThiwissen** [comment]
Genial, muchas gracias!
