### ISSUE TITLE
Dudas de FS

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#4024]
Hola buenas, tengo algunas preguntas sobre el tamaño de los archivos en FS y como guardarlos.
Si por ejemplo tenemos bloques de 1024 y creamos un archivo nuevo. Entonces tendria un bloque reservado y el tamaño en su metadata diria 0. Pero entonces si por ejemplo lo truncamos a 500 tendriamos que hacer lo mismo que en memoria de marcar como que ocupa un bloque redondeandolo? Y como ocupa un bloque, tendriamos que poner en el metadata 1024 o 500? Y en caso que sea 500, en el void * desperdiciariamos los bytes restantes?   Desde ya muchas gracias

**Comment by LeandroCarbajales** [comment]
Buenas!
En el archivo metadata le marcas que tiene un tamaño de 500, pero en definitiva tiene un bloque asignado, como bien marcas el resto simplemente se desperdiciaría (fragmentación interna).
Saludos!

**Comment by JoaquinCoaricona** [comment]
Ok gracias Profe
