### ISSUE TITLE
Pregunta sobre TIEMPO_UNIDAD_TRABAJO de DIALFS 

### ISSUE THREAD

**Issue by lewislee0920** [sisoputnfrba/foro#4025]
Buenas, 
queria preguntar sobre este parte de enunciado:
![image](https://github.com/sisoputnfrba/foro/assets/62365146/47e371e0-541c-42f4-9a0b-d7205d3a8c64)
Dicen que "siempre va a consumir una aunidad de tiempo TIEMPO_UNIDAD_TRABAJO" pero significa que vamos a tener que hacer un usleep de TIEMPO_UNIDAD_TRABAJO antes cada instrucciones de IO_FS_CREATE, IO_FS_DELETE, IO_FS_TRUNCATE, IO_FS_WRITE y IO_FS_READ?

**Comment by iago64** [comment]
Buenas! Cómo va?

Si.

Saludos.-
