### ISSUE TITLE
Duda Detener Planificacion

### ISSUE THREAD

**Issue by FeliFemenia** [sisoputnfrba/foro#4026]
Buenas, me surgió una duda mientras estaba desarrollando el comando de DETENER_PLANIFICACION del kernel. 
Cuando detenemos la planificación, tengo entendido que se frena el paso de los pcbs que estaban en blocked a ready. Pero suponiendo el caso de que tengo dos procesos que quieren hacer un io generica. Cuando uno terminar de dormir la cantidad de tiempo indicada, el otro pcb deberia de igual manera hacer la io? o tendria que esperar a que se active la planificacion para que pueda hacer la io?
Suponiendo que si, me quedarian esos dos procesos esperando a activar la planificacion nuevamente para poder pasar a la lista ready. 

Otra duda que me surgio es, la transicion hacia exit tmb se tiene que detener? osea de cualquier estado a estado exit.

**Comment by RaniAgus** [comment]
¡Buenas! Misma respuesta que en: https://github.com/sisoputnfrba/foro/issues/3947 Saludos

**Comment by FeliFemenia** [comment]
Oka gracias, no la habia leido es issue, mil disculpas!
