### ISSUE TITLE
Sobre el funcionamiento de las listas

### ISSUE THREAD

**Issue by jotab0** [sisoputnfrba/foro#4027]
Buenas! 

Me surgió una duda en cuanto al funcionamiento de las listas:

```
parametro = extraer_int_del_buffer(un_buffer);
list_add(un_pcb->pedido_a_interfaz->datos_auxiliares_interfaz,&parametro);
```

Si yo agrego de esta manera un valor a la lista y parametro es una variable local, se pierde el contenido de la lista? Lo consulto porque por ejemplo cuando se agrega a una lista algo a través de un puntero, si posteriormente uno hace free del puntero se pierde el valor de la lista (se vuelve basura).

### 📝 Código relevante

Hice algunas pruebas para ver como funciona pero no entiendo por qué:

```
void agregar_valor_a_lista(t_list* una_lista){
    int valor = 4;
    list_add(una_lista,&valor);   
}

    int* un_puntero = malloc(sizeof(int));
    int a = 2;
    *un_puntero = a;
    list_add(una_lista, un_puntero);
    
    free(un_puntero);

    agregar_valor_a_lista(una_lista);

    int* numero_extraido = list_get(una_lista,0);
    printf("1er Numero extraido %d\n",*numero_extraido);
    numero_extraido = list_get(una_lista,1);
    printf("2do Numero extraido %d\n",*numero_extraido);
```
Consola imprime:

_1er Numero extraido 879867156 (Basura por el free)
2do Numero extraido 4 (Está ok por más que la variable que agregué fuera local en la función)_

**Comment by mefederico** [comment]
Hola buenas!

Cuando haces un malloc se te asigna una porción de memoria dinámica que cuando se haces free es más probable que el SO la utilice para otra cosa.

Cuando haces lo mismo con variables locales eso está en stack de tu programa y es espacio de memoria que va a estar usando tu programa nomas por lo que si no haces muchas mas cosas ese valor es posible que no se modifique. Igualmente cuando se termina tu función el lugar donde estaba el 4 de la variable local `valor` deja de estar reservado para ese 4 por lo que cualquier llamado a otra función o cualquier operación va a variar tu valor haciendo que lo que este guardado en la lista no tenga sentido ni consistencia alguna.

Saludos!

**Comment by jotab0** [comment]
Perfecto, entonces por lo que interpreto debería manejar todo lo que se agregue a una lista con malloc. 

Y última consulta, **list_destroy()** sería equivalente a hacer el free que tengo que hacer para la memoria solicitada en cada puntero usado para agregar un elemento a la lista?

Gracias Fede

**Comment by mefederico** [comment]
El list_destroy solamente hace free a la estructura de la lista pero no a los elementos, para hacer free a los elementos tienen que usar [list_destroy_and_destroy_elements](https://github.com/sisoputnfrba/so-commons-library/blob/d22eb0076cc863bcbb7edbdf47ef43e6d434ffc6/src/commons/collections/list.h#L52) 

Que recibe una función "element_destroyer" que tiene que saber como hacer `free` a lo que sea que están guardando. 
Pueden ver un ejemplo de uso acá https://github.com/sisoputnfrba/so-commons-library/blob/d22eb0076cc863bcbb7edbdf47ef43e6d434ffc6/tests/unit-tests/test_list.c#L38

Saludos!

**Comment by jotab0** [comment]
Clarísimo, gracias fede, que termines bien el finde,

Cierro el issue.
