### ISSUE TITLE
Proceso, no pertenece a ningun estado por un periodo de tiempo

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#4028]
Buenas! queria preguntar que tan grave es que un proceso me quede "en el aire" y que no aparezca en proceso estado si le pongo en el momento justo. Para que se entienda un poco mas, les pongo una aproximacion de lo que hace nuestro codigo
```c
void planificador_largo_plazo(logger){
// hacer cosas
pcb = queue_pop(cola_new)
mandar_a_memoria_para_crear_proceso(pcb);
// esta ultima linea equivale a hacer un sleep de RETARDO_MEMORIA
queue_push(cola_ready_pcb);
// mas cosas
}
```

entonces si justo le doy a `PROCESO_ESTADO` cuando esta en la parte de mandar a memoria, ese pcb no va a aparecer.

Si esto es muy grave lo que se puede hacer es primero un `queue_peek()`, para esperar que haga lo de memoria y despues un `queue_push()`, pero si no es tan grave prefiero dejarlo como esta para no crear nuevos errores en el codigo.

Muchas gracias y que terminen bien el domingo

**Comment by LeandroCarbajales** [comment]
Buenas!
Probablemente hayan 50 cosas más graves que esas. Por un lado es muy poco probable que ocurra y si ocurre sería tan simple como correr proceso_estado nuevamente.

Saludos!

**Comment by GonTurri** [comment]
Gracias muy amable
