### ISSUE TITLE
Duda sobre diferencias de milisegundos

### ISSUE THREAD

**Issue by LeonelArianContreras** [sisoputnfrba/foro#4029]
Hola! Perdón que moleste un domingo a la noche. Teníamos duda acerca de un caso en particular que nos está ocurriendo. Hay a veces (cuando usamos Quantum = 2000, por ejemplo) que se nos pasa 1s aproximadamente entre que se envía la PCB a CPU y vuelve a Kernel. Esto nos pasa cuando arranca a ejecutar otra instrucción justo milisegundos antes de que llegue la interrupción por quantum o cuando se está ejecutando una instrucción que requiere de Memoria. Mil gracias, desde ya!

**Comment by iago64** [comment]
Buenas! Cómo va?

Cual sería la duda puntualmente? 
Por otro lado, por las dudas revisen las [Pruebas Preliminares](https://faq.utnso.com.ar/tp-c-comenta-pruebas) donde para evitar estas situaciones tan bordes en la prueba de plani, donde nos interesa controlar bien cuanto ejecutan pusimos un valor que no es redondo un múltiplo de los retardos de memoria.

Saludos.-

**Comment by LeonelArianContreras** [comment]
Nos referimos a que, por ejemplo, cuando se ejecuta un SET y luego un RESIZE (que requiere de Memoria), se nos desfasa 1s del quantum de 2000, ya que la interrupción llegaría a mitad de esta instrucción. Igualmente muchísimas gracias por la info

**Comment by RaniAgus** [comment]
¡Buenas! Es correcto y, de hecho, es como funciona la CPU: no hay forma de atender las interrupciones _inmediatamente_, o mejor dicho, el momento más inmediato que existe es la etapa de "check interrupt". 

Quizás en nuestras pruebas pueden estar un poco desproporcionados estos tiempos, pero es completamente esperable en un sistema operativo real que el proceso sea desalojado un tantito después de haber enviado la señal de interrupción por fin de quantum.

Saludos

**Comment by LeonelArianContreras** [comment]
Ah listo, mil gracias!!
