### ISSUE TITLE
Duda Finalizar proceso

### ISSUE THREAD

**Issue by FeliFemenia** [sisoputnfrba/foro#4030]
Buenas, algunas consultas, en el comando de la consola de kernel de FINALIZAR PROCESO
1- Nosotros para implementarlo lo que hacemos es frenar la planificación, buscamos el pid en la listas y cuando lo encontramos lo eliminamos y volvemos a activar la planificación. Esta implementación seria valida?

2- La otra duda que tenemos es, si justo el proceso que se quiere eliminar es el que esta ejecutando en el procesador, debería desalojarlo para eliminarlo? o esperar a que se desaloje por algún motivo (quantum, syscall, etc) y recién ahí eliminarlo?

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Esta bien la implementación.

2.- Deberían mandarle la interrupción para desalojarlo y eliminarlo.

Saludos.-

**Comment by FeliFemenia** [comment]
Buenas. Gracias!
