### ISSUE TITLE
Duda dialFS: eliminar archivo y compactacion

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#4031]
Buenas,
Tenemos una duda sobre que debemos hacer cuando eliminamos un archivo o cambiamos la ubicación de sus datos en bloques.dat cuando se hace compactación ¿Debemos vaciar la memoria que ocupaba? 
Porque, por ejemplo, ahora si creamos un archivo y le añadimos 2 bloques (0 y 1) y escribimos algo en el primer bloque, después lo borramos y creamos otro al que se le asigna el mismo bloque inicial 0 ya va venir con algo escrito a menos que se sobreescriba con algo nuevo.

**Comment by RaniAgus** [comment]
¡Buenas! Para las pruebas no vamos a fijarnos en eso (en el enunciado ese comportamiento no está especificado), así que si quieren pueden pisarlos con ceros. Eso sí, en un file system real eso no ocurre ya que la escritura es una operación bastante cara, y si el sistema operativo no nos lo pide no deberíamos hacerlo :)

Saludos

**Comment by RaniAgus** [comment]
¡Buenas @rood8592 ! ¿Les sirvió la respuesta? Saludos

**Comment by rood8592** [comment]
Sip, gracias!
