### ISSUE TITLE
Duda de finalización de interfaz DialFS y levantar varias interfaces

### ISSUE THREAD

**Issue by twinik** [sisoputnfrba/foro#4032]
Buenas, tenia un par de consultas:

1- Supongamos que con la Int1 de tipo DIALFS creo 3 archivos como notas.txt, notas2.txt y notas3.txt. Cuando cierro la interfaz con CTRL+C  se tendrían que borrar esos archivos creados por esa interfaz?

2- Y suponiendo que levanto 2 interfaces DIALFS: Int1 e Int2, tendría que poder crear archivos con el mismo nombre pero cada archivo de distinta interfaz? Ejemplo: Int1 crea notas.txt y después Int2 crea otro archivo llamado notas.txt. Estos se guardarían todos en la misma PATH_BASE_DIALFS? O cada interfaz adentro de ese path tiene una subcarpeta?

Gracias, saludos.

**Comment by RaniAgus** [comment]
¡Buenas!

1- No, al ser un File System justamente queremos los archivos puedan recuperarse entre ejecuciones :)
2- Cada interfaz debe estar montada sobre distintos `PATH_BASE_DIALFS`

Saludos

**Comment by RaniAgus** [comment]
Tranqui no hay preguntas boludas, solo boludos que no preguntan! Abrazo
