### ISSUE TITLE
Uso del valor nombre_archivo en IO_FS_WRITE y IO_FS_READ

### ISSUE THREAD

**Issue by papiness77** [sisoputnfrba/foro#4033]
La descripcion de  IO_FS_WRITE dice esto :
 Esta instrucción solicita al Kernel que mediante la interfaz seleccionada, se lea desde Memoria la cantidad de bytes indicadas por el Registro Tamaño a partir de la dirección lógica que se encuentra en el Registro Dirección y se escriban en el archivo a partir del valor del Registro Puntero Archivo.

Como lo entiendo yo con el valor que se encuentra en Registro Puntero Archivo, se lo sumaria al offset de mi archivo de bloques.dat usando seek y este offset lo sumo desde la posicion cero del archivo. Entonces como no sabia para que se usa el nombre de archivo, me surgio la duda si tengo que verificar si este puntero se encuentra en la zona aceptada del archivo que me mandan a escribir. Sacando gracias al nombre el primer bloque y el size. Y si no hay que hacer esta verificacion de que me sirve tener el nombre?

**Comment by RaniAgus** [comment]
¡Buenas! El Registro Puntero Archivo es un desplazamiento partiendo del inicio del **archivo**, no del File System. El archivo arranca en `TAMANIO_BLOQUE * BLOQUE_INICIAL`, y este segundo dato se extrae del archivo metadata correspondiente. Es por esto que necesitamos el nombre del archivo, ya que distintos archivos van a tener distintos metadata y, por ende, distintos `BLOQUE_INICIAL`.

Saludos

**Comment by papiness77** [comment]
Dale gracias, y tengo que verificar si el puntero se sale del tamanio del archivo?

**Comment by iago64** [comment]
Buenas! Cómo va?

No, todas las lecturas y escrituras van a ser dentro del tamaño definido del archivo.

Saludos.-
