### ISSUE TITLE
Hay alguna prueba disponible de Filesystem?

### ISSUE THREAD

**Issue by diegohcanetti** [sisoputnfrba/foro#4034]
Hola buenas tardes, estoy armando este issue ya que con nuestro equipo queríamos ya ir probando a fondo la IO_DIALFS y queríamos saber si ya tienen alguna prueba armada para esta interfaz. Obviamente entendemos que a tan poco tiempo de la primer entrega (y segundo parcial) estén ocupados, por lo tanto, si la respuesta a este issue es: "Aún no están disponibles", comprenderemos eso.

**Comment by iago64** [comment]
Buenas! Cómo va?

Aun no esta redactada la prueba de FS ni la de estabilidad general, pero te puedo dar una idea de como probarlo un poco:

Armarse un script que haga lo siguiente:
Crear un archivo y truncarlo a un tamaño de mas de 3 bloques (5, 6, 8, 10, da igual)
Hacer un STDIN para leer desde teclado e ingresar un texto que ocupe al menos 3 bloques,
Hacer el IO_FS_WRITE de ese texto.
EXIT

Bajar el FS
Levantar el FS

Tener un segundo script que:
Haga un IO_FS_READ del archivo que crearon antes
Pase por un STDOUT para imprimir el texto y validar que esta tal cual lo escribieron.
EXIT

Despues para la compactación es facil, creen 3 archivos, y traten de truncar el del medio a un tamaño de mas de un bloque.

Si con todo eso pasan las pruebas, listo, no deberían tener problemas con las pruebas de FS que estamos armando.
Saludos.-

**Comment by diegohcanetti** [comment]
Muchas gracias Dami por todas estas pruebas :)!!!
