### ISSUE TITLE
Sobre el uso de las funciones de dirent.h

### ISSUE THREAD

**Issue by GorinoManuel** [sisoputnfrba/foro#4035]
Hola queremos cargar los nombres de los archivos al iniciar el DialFS en una lista para así tenerlos a mano a la hora de compactar. Esta lista también se iría actualizando a medida que se crean o destruyen los archivos.  

Con esto pregunto, podemos usar las funciones de dirent.h?
Esto es porque vimos algunos ejemplos de su uso, los que agrego en la parte de Búsqueda en foros

### 📚 Documentación oficial
https://www.man7.org/linux/man-pages/man3/opendir.3.html

### 🔎 Búsqueda en foros
https://www.programacion.com.py/escritorio/c/directorios-y-ficheros-en-c-linux
https://www.youtube.com/watch?v=Gbmk-ENweZI

**Comment by diegohcanetti** [comment]
Hola buenas cómo va, no soy ayudante, pero se me ocurre que podrías usar algo de las commons como los diccionarios. En este diccionario podrías usar el nombre del archivo como key y el archivo en como tal como elemento, de esta manera cada vez que necesites X archivo, lo buscas por su nombre(key).
