### ISSUE TITLE
Archivos FS

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#4036]
Hola buenas. Tengo una pregunta sobre los archivos FS y la compactacion. En mi caso para la compactacion uso una lista en la que tengo un registro de los archivos creados, su bloque inicial y los bloques que ocupa. Pero en esta lista se guardan los archivos a medida que son creados osea que si yo desconecto la interfaz se pierden los datos. Y si la vuelvo a levantar la compactacion fallaria. Mi pregunta es si tendriamos que tener en cuenta este caso o solamente vamos a compactar en la misma instancia en la que creamos los archivos y no en las que siguen. 
En caso que tengamos que tener en cuenta este caso tendriamos que buscar dentro de la carpeta del path todos los archivos que haya, abrirlos y cargar sus datos en la lista? o podriamos tener un archivo aparte con los registros de los archivos que tenemos para abrirlo siempre y llenar la lista al momento de levantar la interfaz.

**Comment by RaniAgus** [comment]
¡Buenas!
1- Justamente al ser un File System es **fundamental** que los archivos puedan recuperarse entre ejecuciones, de hecho la prueba más básica que hagamos va a incluir esto como mínimo: https://github.com/sisoputnfrba/foro/issues/4034#issuecomment-2187284956
2- Sí, tendrían que buscar dentro de la carpeta del path todos los archivos que haya, abrirlos y actualizar su bloque inicial de ser necesario. Es por esto que se encuentran en un formato compatible con `commons/config.h`: para que puedan usar las commons para leerlos y actualizarlos fácilmente :)

Saludos

**Comment by JoaquinCoaricona** [comment]
Hola buenas. Las pruebas de ese issue las pude hacer y no hubo problema porque en el caso de compactacion no bajaron y levantaron el FS. Solo hicieron eso en el de leer. Mi pregunta iba mas a eso. Para leer no hay problema en mi implementacion, podemos bajar y levantar el FS. El problema vendria con compactacion pero si lo van a hacer como en el issue, sin bajar ni levantar Fs entonces no tendria problemas. En las pruebas, si hacen compactacion, va a ser sin bajar ni levantar el FS?

**Comment by iago64** [comment]
Buenas! cómo va?

No vamos a bajarles el FS a mitad de la compactación.
Respecto a buscar los archivos, no hay nada en las commons, pero pueden recurrir a cualquier biblioteca estandar de C.

Saludos.-

**Comment by RaniAgus** [comment]
Aclaro por las dudas, si bien no vamos a bajarles el FS en medio de una compactación, sí debería ser capaz de compactar luego del reinicio

El File System debe ser completamente funcional reiniciándolo todas las veces que sean necesarias, siempre y cuando arranque en un estado consistente.

**Comment by JoaquinCoaricona** [comment]
Gracias por las respuestas, entonces solo para terminar de aclarar

> No vamos a bajarles el FS a mitad de la compactación. Respecto a buscar los archivos, no hay nada en las commons, pero pueden recurrir a cualquier biblioteca estandar de C.
1) Solo bajarian el FS en las pruebas de leer o escribir en el FS? como en la primer prueba del issue #4034
2) Cuando prueben la compactacion, la van a hacer en el mismo archivo de instrucciones en el que crearon todos los archivos del FS? Y sin bajar el FS? como en la segunda prueba del issue

3) Entonces considerando que solo uso la lista en la compactacion y no para operaciones de lectura/escritura donde abro el archivo que especifican por parametro directamente, no tendria que rellenar esa lista buscando en el directorio y abriendo todos los archivos al inicio del FS, no?

> El File System debe ser completamente funcional reiniciándolo todas las veces que sean necesarias, pero siempre vamos a probar que arranque en un estado consistente.
Entiendo, igualmente voy a averiguar sobre eso

**Comment by RaniAgus** [comment]
1. Solo vamos a bajar el FS una vez el estado quede consistente, o sea, no les vamos a bajar el FS en medio de una lectura, una escritura, una compactación o cualquier otra operación
2. Cualquier proceso debería poder disparar una compactación al intentar truncar un archivo. Repito una vez más, luego de bajar un DialFS y levantar otro sobre una carpeta existente debería poder hacerse cualquier operación: crear, truncar, escribir, leer y borrar archivos.
3. Para las pruebas es válido tener levantada una lista con todos los archivos en memoria, como también puede ser válido leer todos los archivos al momento de tener que compactar. Dejamos a su criterio evaluar qué ventajas y desventajas tiene el hacerlo de una u otra forma y por qué sería mejor uno u otro (es una linda pregunta de coloquio 😉)
