### ISSUE TITLE
Setear IP Memoria en módulo memoria

### ISSUE THREAD

**Issue by AGanem** [sisoputnfrba/foro#4037]
Hola Buenas!!

Cómo están?

Cómo le seteamos la ip a la memoria? Según el enunciado no viene en el archivo de configuración.

Hoy se la estamos hardcodeando asi: address.sin_addr.s_addr = inet_addr("127.0.0.1");

Se la podemos pasar por parámetro al momento de ejecutar como hacemos con la configuración?
./memoria ../memoria.config  "127.0.0.1"

**Comment by RaniAgus** [comment]
¡Buenas! Como explicamos en la [guía de sockets](https://docs.utnso.com.ar/guias/linux/sockets#socket) (lectura necesaria para hacer el TP0 a principio de cuatrimestre), no es necesario configurar una IP a la hora de levantar un servidor. Alcanza con indicar únicamente el puerto.

¿Por qué motivo están usando `inet_addr()` para parsear direcciones? En la guía recomendamos usar `getaddrinfo()` ya que tiene una API más sencilla de usar. ¿Hay algún caso en el que no les haya servido?

Saludos

**Comment by AGanem** [comment]
Hola! Gracias por responder.  Ya actualizamos el código para usar getaddrinfo(), El server levanta sin problemas, sin embargo no sabemos que ip es la que se configuró.
 Hicimos esto para tratar de verla :
 inet_ntop(server_info->ai_family, server_info->ai_addr, ip_str, sizeof(ip_str));
 log_info(logger_memoria, "Servidor MEMORIA está escuchando en %s:%d...\n", ip_str, cfg_memoria->PUERTO_ESCUCHA);
 Se muestra lo siguiente:
"Servidor MEMORIA está escuchando en 2.0.31.66:8002..."

Cuando, conectamos las interfaces, kernel y cpu, lo hacen sin problemas siendo que el config de cada uno trae la ip 127.0.0.1 (todo en la misma maquina virtual)

Estas dudas se nos disparan a partir de que pensamos que cada modulo se despliega en una computadora diferente dentro del laboratorio y debería ser necesario saber la ip de la memoria. Es así? Saludos.

**Comment by RaniAgus** [comment]
¡Buenas! Sí, en ese caso probablemente les sirva volver a leer la [etapa 4 del TP0](https://docs.utnso.com.ar/primeros-pasos/tp0#etapa-4-desplegar-en-la-ubuntu-server), ya que ahí está explicado cómo practicar un despliegue similar a la entrega.

Si ya van a arrancar a ver qué onda con el despliegue, también pueden arrancar chusmeando la [guía](https://docs.utnso.com.ar/guias/herramientas/deploy) al respecto.

**Comment by AGanem** [comment]
Dale! Muchas gracias!
