### ISSUE TITLE
Parámetro Registro Puntero Archivo en IO_FS_READ y WRITE

### ISSUE THREAD

**Issue by VEBravo** [sisoputnfrba/foro#4038]
Buenas! Estaba viendo las operaciones fs write y read y no estoy seguro de qué tipo de dato sería Registro Puntero Archivo. Me podrían dar una mano? Me sería de mucha ayuda si brindan una operación de ejemplo de cómo serían en el script del proceso.

### 📔 Citas del enunciado
>IO_FS_WRITE (Interfaz, Nombre Archivo, Registro Dirección, Registro Tamaño, Registro
Puntero Archivo): Esta instrucción solicita al Kernel que mediante la interfaz seleccionada, se
lea desde Memoria la cantidad de bytes indicadas por el Registro Tamaño a partir de la
dirección lógica que se encuentra en el Registro Dirección y se escriban en el archivo a partir
del valor del Registro Puntero Archivo.
IO_FS_READ (Interfaz, Nombre Archivo, Registro Dirección, Registro Tamaño, Registro
Puntero Archivo): Esta instrucción solicita al Kernel que mediante la interfaz seleccionada, se
lea desde el archivo a partir del valor del Registro Puntero Archivo la cantidad de bytes
indicada por Registro Tamaño y se escriban en la Memoria a partir de la dirección lógica
indicada en el Registro Dirección.

### 💭 Soluciones posibles
Pensé que como era el puntero a un archivo era el bloque inicial * tamaño bloque + desplazamiento y representarlo como un int (bytes).

**Comment by f-and** [comment]
Buenas! 
Considerá que a lo mejor no se quiere leer todo el archivo a memoria, para ese uso esta el registro puntero archivo.
Para dar un ejemplo:
Se tiene el archivo prueba.txt que tiene escrito: RESPUESTAS_PARCIAL:1A2B3B4D
Pero se tiene una memoria mucho menor que el tamaño del archivo, por lo que se quieren cargar las respuestas del parcial, pero no el resto, porque ocuparía toda la memoria. En ese caso se haría (considerando que todo número que pongo es un registro con ese valor almacenado):
IO_FS_WRITE Interfaz: DISCO Archivo: prueba.txt Dirección: 0 (No tenemos nada más en memoria) Tamaño: 8 (queremos cargar los 8 caracteres) Puntero Archivo: 19 (se lee desde el 1 en adelante)
Con eso debería poder leerse. Para el caso de escritura seria lo mismo a la inversa, yo quiero escribir respuestas nuevas porque se que ya tienen las anteriores, por lo que hago:
IO_FS_READ Interfaz: DISCO Archivo: prueba.txt Dirección: 8 (Supongamos que en memoria despues de las respuestas leidas tengo otras nuevas) Tamaño: 8 Puntero Archivo: 19 (se **escribe** desde el 1 en adelante)

Espero te haya servido!
Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @VEBravo ! ¿Les sirvió la respuesta de Fede? Saludos

**Comment by VEBravo** [comment]
Hola! Muchas gracias por la respuesta, fue muy útil. Perdón por no responder, lo leí del mail y me colgué. :D
