### ISSUE TITLE
Duda Mov_in Mov_Out

### ISSUE THREAD

**Issue by tomassagrada** [sisoputnfrba/foro#4039]
Mi, duda era para confirmar si tenia esto bien como lo había pensado, y es que cuando se habla de que lee en la dirección que tiene uno de los registros y después lo almacena en otro, pero cuando habla de almacenar en otro registro se refiere a almacenar en el registro en si o en la dirección de ese otro registro? Por que si lo que se leyese fuesen palabras no tendría sentido almacenarlas en un registro (o sea no encaja el tipo, a menso que se traduzca de alguna forma).

### 📔 Citas del enunciado/videos
MOV_IN (Registro Datos, Registro Dirección): Lee el valor de memoria correspondiente a la Dirección Lógica que se encuentra en el Registro Dirección y lo almacena en el Registro Datos.
MOV_OUT (Registro Dirección, Registro Datos): Lee el valor del Registro Datos y lo escribe en la dirección física de memoria obtenida a partir de la Dirección Lógica almacenada en el Registro Dirección.

**Comment by f-and** [comment]
Buenas Tomas!
Para responderte, es como la primera opción que decís, el MOV_OUT lee de un registro a la memoria, y el MOV_IN lee de la memoria a un registro. Pero además fijate el Issue https://github.com/sisoputnfrba/foro/issues/3781#issuecomment-2133708741, en el que Dami explica ampliamente lo que puede ser manejar palabras con la memoria y registros, porque van a poder manejar cierta traducción entre caracteres y dígitos, en la prueba de memoria se ve un poco de eso también (cuando se mueven números que parecen aleatorios como 54 o 39, [pueden ser caracteres también!](https://elcodigoascii.com.ar/)). 
Saludos.-

**Comment by tomassagrada** [comment]
Perdón que respondí tarde estuve cursando y afuera recién puedo responder, o sea no me queda claro entonces como abordar algunos casos, por que por ejemplo si yo puedo recibir tanto letras como números de la lectura en memoria, a la hora de guardarlo en un registro tendría q hacer la traducción, y después a la hora de escritura tengo que traducirlo a letras para mandarlo a memoria o lo dejo numérico? y el tamaño que le mando varia si son números no? por que un carácter valdría lo mismo que 2 números. no?

**Comment by f-and** [comment]
No hay problema, no hay un tiempo de respuesta para contestar (a menos que sean 1/2 semanas jaja).
No es necesario hacer una traducción, solamente hay que mover espacios a otros espacios, por ejemplo el siguiente código:

```c
uint8_t numero = 70;
char letra = numero;
printf("%c %d\n", letra, numero);
printf("%d %c", letra, numero);
```

Es un código valido (no me acuerdo si el printf es así igual :P), te terminaria resultando que, al imprimir cualquiera de las dos cosas, como número o como letra, tendran el mismo resultado. Esto es porque, como decia, todo número tiene una letra asociada (practicamente), según el código ASCII. Lo importante para ustedes es que 1 char = 1 uint8_t = 1 byte. Por lo que respondiendo a tu última pregunta, un caracter no "vale" un número, sino que, dependiendo del tipo de número, se pueden meter varios bytes, o caracteres en un número; por ejemplo, 1095520072 es HOLA en ASCII si te pones a analizarlo:

```c
uint8_t test[5] = {72, 79, 76, 65, 0};
uint32_t * test2 = (uint32_t *)&test;
printf("%d\n", *test2);
printf("%s", test);
```

Por lo que, para contestar integramente, no hay que traducir de una manera a otra, vos si recibís números o recibís caracteres, estas recibiendo bytes, como representas esos bytes depende de lo que quieras hacer, pero cuando los moves a registros pueden usarse como números, y cuando los lees en secuencia los podes leer como caracteres, pero son bytes.

**Comment by tomassagrada** [comment]
Ahí creo que lo entiendo mejor. O sea a mi no me va a importar el tipo de dato que me llega si no que lo veo como bytes o sea me fijo en el tamaño a la hora de enviar o recibir simplemente, y lo guardo "como viene". 
Pero creo que me sigue sin quedar claro algo, por que viendo esto para MOV_IN y MOV_OUT lo que recibo o envió siempre va a respetar el tamaño del registro que envía o reciba, por lo tanto el parámetro de tamaño a enviar e memoria esta claro. Pero ahora me surge una duda a partir de esto con la instrucción copy string, y es simplemente que tipo va a ser el tamaño, por que si son simplemente bytes puedo recibir lo que leo y escribirlo enviando como tamaño el mismo que use para leer.

**Comment by f-and** [comment]
Fijate que el COPY_STRING en realidad se maneja todo adentro de la memoria, solo se usan los registros de SI y DI para indicar las direcciones lógicas que se quieren copiar a donde, y el tamaño como un delimitador, por lo que únicamente habría que hacer un memcpy de la dirección dada, con el tamaño dado, a la otra dirección, por lo que si, el tamaño que lees es el tamaño que escribir.

Para contestar a tu segunda pregunta, se puede leer de ambas maneras, como cite en el ejemplo de arriba, si vos le pedís a un char que sea un uint8_t lo va a ser, y si le pedís a un uint8_t que sea un char lo va a ser también, lo que te sirva para verlo vas a poder verlo de esa manera; para el TP en sí, realmente no hay muchos casos donde se use los bytes como números individuales por fuera del MOV_OUT/IN, por lo que podes tomarlos como ASCII, pero siempre recordando que son bytes que pueden ser lo que sea y teniendo en cuenta el uso que le estas dando a esos bytes, te sirve considerarlos como números para COPY_STRING? seguramente no, pero te sirve considerarlos como números para MOV_OUT? Si.

En cuanto a la pregunta de MMU, como te parezca, si crees que no esta en nada relacionado a este Issue pasalo a otro y cerramos este cuando entiendas este tema!

**Comment by tomassagrada** [comment]
Bueno me quedo claro, voy a tratar de corregirlo en el código ahora. muchas gracias
