### ISSUE TITLE
Duda archivos del FS

### ISSUE THREAD

**Issue by FeliFemenia** [sisoputnfrba/foro#4040]
Buenas, una consulta con respecto a los archivos de metadata.dat y el de bitmap.dat.
1- La pregunta seria si esos archivos ya tendrían que creados en la maquina y solo deberíamos accederlos? o los tendríamos que nosotros crear en tiempo de ejecución?
2- El archivo bitmap.dat, en caso de ya estar creado, tengo entendido que nosotros lo deberíamos llenar con un bitmap, estoy entendiendo bien?
3- Suponiendo que los archivos metadata ya estén creados en el sistema, la operación de crear archivo del fs, seria agregar ese archivo al bloques.dat?

**Comment by f-and** [comment]
Buenas Feli!
1. Tendrian que crearlos en tiempo de ejecución, cada vez que se crea un archivo nuevo, y levantar el bitmap al inicio del FS.
2. Si, el bitmap.dat es solo la persistencia del bitmap de bloques que tienen que manejar, por lo que quedaria el bitmap adentro del archivo.

**Comment by FeliFemenia** [comment]
Buenas, entendido. Muchas gracias!

**Comment by f-and** [comment]
@FeliFemenia te recuerdo que si tu duda está resuelta cierres los issues por favor, con este mensaje cierro este, pero te aviso para la prox.
