### ISSUE TITLE
pequeña duda sobre los metadata

### ISSUE THREAD

**Issue by nicolasvultaggio** [sisoputnfrba/foro#4041]
Buenas, me surgieron algunas dudas sobre los archivos de metada.
Al principio solo conocemos el nombre de este archivo, entonces:
Estos deben ser simplemente archivos DE TEXTO? 
O sea, es válido crearlos con fopen en modo escritura "w"?

o sea, lo unico que debe escribirse en ese fwrite es:

"BLOQUE_INICIAL=nro_bloque\nTAMANIO_ARCHIVO=0"

suponiendo que nro_bloque se haya previamente en el bitmap, deberíamos transformar su valor numerico cadena de texto:
por ejemplo 25 -> "25"

En base a esto, las funciones de las commons sobre los config básicamente funcionan sobre cualquier archivo de texto? porque se recomienda el uso de las commons para trabajar con los metadata según el enunciado.
Muchas graciass

**Comment by iago64** [comment]
Buenas! Cómo va?

Si los archivos de metadata son de tipo texto, con lo cual pueden abrirlos como quieran.

La recomendación de las commons es simplemente una recomendación si no les sirve pueden no usarlas y trabajan sobre cualquier archivo de texto peero que tenga la caracteristica de que todo lo que tiene el archivo son diferentes lineas con el siguiente formato: `CLAVE=VALOR`.

Saludos.-

**Comment by nicolasvultaggio** [comment]
perfecto! entendí

entonces , para cualquier implementación que hagamos
suponiendo que nro_bloque se haya previamente en el bitmap, deberíamos transformar su valor numerico cadena de texto:
por ejemplo 25 -> "25"?

**Comment by iago64** [comment]
Buenas!

Algo copado de las commons es que el código esta público y lo pueden analizar por uds mismos, por ejemplo el código de [config.c](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/config.c) te muestra que `config_set_value` revienta la entrada del diccionario de claves que tiene la config y la regenera con el valor que le pases y si no existe, no pasa nada porque la crea :)

Saludos.-

**Comment by nicolasvultaggio** [comment]
si, la estuve viendo pero es un código que me costó mucho entender y me terminé llevando bastantes dudas, por eso me las quise sacar con el foro jaja. Muchas gracias por la ayuda!

**Comment by nicolasvultaggio** [comment]
de verdad, perdón por la molestia, pero entonces, por lo que leí del config.c:

cuando lo usabamos para la configuracion del modulo, el archivo de texto ya existía de antemano, dependía de la configuración del modulo dada por las pruebas

pero entonces, por lo que entendí, cuando a config_create le pasamos el path de un archivo que todavía no existe, config_create lo crea, correcto?

**Comment by Lisandrogq** [comment]
Que haces nico!
config_create te devuelve null si no existe el archivo. Esto lo podes ver en el [.h](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/config.h) de las librerías para ahorrarte tiempo.
Nosotros lo q hacemos es crearlo con `fopen(path, "w")`, el parametro "w" es para crear el archivo

**Comment by nicolasvultaggio** [comment]
buenísimo, muchas gracias!!
