### ISSUE TITLE
Duda sobre cuando compactar

### ISSUE THREAD

**Issue by ManuelGarciaF** [sisoputnfrba/foro#4042]
Buenas, estuve viendo el tema de la compactacion en dialfs y me surgió una duda sobre en que casos hay que compactar:

### 📔 Citas del enunciado/videos
En el enunciado dice que "Puede darse la situación que al momento de querer ampliar un archivo, dispongamos del espacio disponible pero el mismo no se encuentre contiguo"
Es necesario compactar siempre que no hay espacio disponible despues del archivo actual? o podemos, en el caso que haya suficiente espacio contiguo disponible en otro lado, moverlo ahi sin compactar?

Por ejemplo, en esta parte de un dibujo que vi en otro issue (#4017):
![image](https://github.com/sisoputnfrba/foro/assets/46934491/19dc5ee7-f6f3-488b-bb84-ffe97691fa6d)

Se puede ver que hay suficiente espacio disponible a la derecha, no seria posible simplemente mover el archivo al final y no compactar?

**Comment by ManuelGarciaF** [comment]
Gracias por la respuesta, entonces en esta situación tambien sería correcto compactar (mover todos los archivos)? Digo ya que sería mas simple la implementación si siempre que no tenes espacio al final del archivo haces el proceso de compactar, en vez de checkear que no haya espacio en algun lado como planteaba antes.

**Comment by iago64** [comment]
Buenas! Cómo va?

Si, en el caso que planteas es correcto compactar o mover al final, en ambos casos la idea es que si o si tienen que mover el archivo porque al ampliarlo no puede estar contiguo.

Saludos.-

**Comment by ManuelGarciaF** [comment]
Perfecto muchisimas gracias!
