### ISSUE TITLE
Duda de en q formato guardar en memoria

### ISSUE THREAD

**Issue by FeliFemenia** [sisoputnfrba/foro#4043]
Buenas, hoy con mi equipo estábamos realizando la prueba preliminar de IOS, y nos dimos cuenta que el mov out ingresa valores numéricos pero que cuando se muestran en pantalla deben ser caracteres. Nos encontramos con el problema de que nuestro tp imprimió números. 

Nosotros guardamos y leemos de memoria todo en formato char* y lo hacemos de la siguiente manera: 
`void agregar_dato_a_pagina(int direccion_fisica, char* dato){
    pthread_mutex_lock(&mutex_void);
    memcpy(espacio_memoria + direccion_fisica, dato, strlen(dato));
    pthread_mutex_unlock(&mutex_void);
}`

`char* leer_dato_de_pagina(int tamanio, int direccion_fisica){
    char* dato = malloc(tamanio);
    pthread_mutex_lock(&mutex_void);
    memcpy(dato, espacio_memoria + direccion_fisica, tamanio);
    pthread_mutex_unlock(&mutex_void);
    return dato;
}`

La pregunta seria si, cuando opera un mov_out, previamente debería convertirlo al carácter correspondiente? o guardarlo en formato int y de alguna manera cuando lo leo de memoria detectar eso y hacer la conversión para mandarlo a la IO stdout?

Asi hacemos la impresion en stdout: 

` for(int i = 0; i < cant_accesos; i++){
            direccion_fisica = list_get(lista_df, i);
            tamanio = list_get(lista_tam, i);
            send_dos_int(direccion_fisica, tamanio, memoria_fd, IO_STDOUT_WRITE);//FALTA HACER EL ENUM MEMORIA-IO

            tamanio_total += tamanio;

            subString = recv_notificacion(memoria_fd);
            subString[tamanio] = '\0';

            string_append(&texto_leido, subString);
 }`

2- Otra duda que tenemos es si el tamaño pasado en la instruccion resize debe ser multiplo del tamaño de pagina.

**Comment by RaniAgus** [comment]
¡Buenas! No deben hacer hacer absolutamente ninguna conversión. Les recomiendo leer https://github.com/sisoputnfrba/foro/issues/3877#issuecomment-2156281836 y https://github.com/sisoputnfrba/foro/issues/3781#issuecomment-2133708741 para entender mejor qué guardan los registros, la memoria y las interfaces.

TLDR: Son bytes :)

Saludos

**Comment by RaniAgus** [comment]
PD: Un dato de color - en markdown podés darle formato a un bloque de código (de más de una línea) usando tres comillas invertidas arriba y abajo (si le agregás una "c"  lo interpreta como código C y lo colorea), así:

\`\`\`c
printf("¡Hola mundo!\n");
\`\`\`

Esto se va a imprimir de esta forma:

```c
printf("¡Hola mundo!\n");
```

**Comment by FeliFemenia** [comment]
Buenas, muchas gracias!
Gracias por lo del markdown tmb, no lo sabia jaja.
