### ISSUE TITLE
Pequeña consulta con el conteo de marcos y páginas

### ISSUE THREAD

**Issue by tiagoclur** [sisoputnfrba/foro#4044]
Hola, ¿qué tal? Hago una pregunta capaz medio tonta, pero es importante porque podría provocar un desfasaje a la hora de ejecutar pruebas.

En el módulo de memoria, la primer página de cada proceso y el primer marco de la memoria contigua: ¿Se cuenta desde 0 o desde 1?

Saludos.

**Comment by mefederico** [comment]
Hola buenas! 

Lo normal es desde 0, pero como ustedes manejan todas las cuentas si son prolijos no van a tener problemas

Saludos!

**Comment by tiagoclur** [comment]
Dale perfecto, gracias!
