### ISSUE TITLE
MMU

### ISSUE THREAD

**Issue by tomassagrada** [sisoputnfrba/foro#4045]
Buenas, tenia una duda sobre el caso en que tengo múltiples direcciones físicas, por que mi idea en realidad es traducirlas y pasarlas de a una a memoria y también armar un vector para el caso de las instrucciones de IO (que además también como duda no estoy tan seguro si se puede mandar en paquetes vectores de enteros, supongo que si igual), lo que ahora tenia era en realidad dentro de la instrucción verificar cuantas dir físicas voy a necesitar y llamar a la MMU tantas veces como direcciones necesite, el problema es que en ese caso dentro de la instrucción estoy sacando el offset (que lo necesito para saber cuantas paginas voy a ocupar) y los números de pagina. Lo que creo que seria mejor en cuanto consigna es que mande el vector de dir fisicas a la MMU y esta me lo rellene, pero mi problema para plantear eso es la inicialización del mismo, por que yo no se cuantas dir voy a tener antes de mandarlo. A lo que iba mi duda es si la manera en que lo estoy haciendo esta mal en términos de consigna. 

Desde ya gracias y un saludo.

**Comment by RaniAgus** [comment]
¡Buenas! Dado un tamaño de página, un offset y un tamaño de escritura deberías poder obtener la cantidad de páginas a escribir o leer :)

Recuerden que cada acceso a Memoria debe tener su propio retardo, por lo que si CPU o IO hacen 3 accesos deberían haber 3 retardos. Teniendo eso en cuenta, es indistinto si envían todas las consultas en un array o si las envían una a una, a fines prácticos la prueba va a terminar devolviendo lo mismo.

Saludos

**Comment by tomassagrada** [comment]
sisi, o sea yo pude conseguir la cantidad de paginas, pero preguntaba por que por ahí estaba mal la manera en que lo hacia, debido al calculo del offset y del numero de pagina por fuera del MMU.

**Comment by RaniAgus** [comment]
¿A qué te referís exactamente con "por fuera de la MMU"? ¿Están realizando el cálculo en un módulo por fuera de CPU?

**Comment by tomassagrada** [comment]
Nono, me exprese mal o sea en realidad arme una función que cumple la función de MMU, pero de esta manera la llamo desde mi instrucción con el numero de pagina y offset ya calculado., o sea que solo buscaría el numero de marco y sacaría la dir física.

**Comment by tomassagrada** [comment]
Muchas gracias, un saludo.

**Comment by NazarenoLopez** [comment]
Una consulta sobre la MMU, el tamaño de las páginas se espera que memoria se lo mande a CPU apenas se conecte o de que manera le comunicamos el tamaño de las paginas? Gracias :-)

**Comment by tomassagrada** [comment]
Buenas, reabro el issue por que si no no se si les aparece tu mensaje en el foro. Además te mando este issue https://github.com/sisoputnfrba/foro/issues/3959 en el que pregunte lo mismo, si no me equivoco, que vos.

**Comment by iago64** [comment]
Buenas!

Efectivamente, la respuesta a la pregunta 1 del issue #3959 es la misma respuesta para la pregunta de @NazarenoLopez.
Igual en estos casos, lo mejor es que creen issues nuevos o mejor aun que busquen en los issues cerrados.

Saludos.-

**Comment by NazarenoLopez** [comment]
Hola Muchas gracias por la ayuda. No había podido encontrar esa info antes!

**Comment by iago64** [comment]
Buenisimo! Resuelta la duda, cerramos nuevamente el issue.
