### ISSUE TITLE
Duda del COPYSTRING

### ISSUE THREAD

**Issue by joaquinbarreiro23** [sisoputnfrba/foro#4046]
Hola buenas, por lo que tengo entendido el copystring lo que hace es copiar un string el cual esta en memoria a otra posición de memoria en base a las direciones logicas de SI y DI, pero lo unico que escribo en memoria son datos del tipo uint32_t y uint8_t, no entiendo como es que llegan los strings a memoria para que despues los pueda copiar.
Desde ya muchas gracias!

**Comment by RaniAgus** [comment]
¡Buenas! Te recomiendo revisar este comment: https://github.com/sisoputnfrba/foro/issues/3877#issuecomment-2156281836 y si quedó alguna duda avisanos :) Saludos

**Comment by f-and** [comment]
Buenas @joaquinbarreiro23! Te sirvió la respuesta de Agus?

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, si les quedó alguna duda pueden abrir uno nuevo referenciando éste. Saludos
