### ISSUE TITLE
Duda Teorica-Practica Planificacion

### ISSUE THREAD

**Issue by Sancho6446** [sisoputnfrba/foro#4047]
Leyendo el enunciado nos surgió la duda de cuando debería planificar nuestro sistema, ya que lo que vimos en la teoría es que el sistema planifica cuando interviene el S.O (Syscall o interrupciones) y no sabemos cómo esto se traduciría a nuestro tp.  Como lo tenemos actualmente es que se planifica antes de mandar un proceso a ejecutar sería esto correcto?Debemos hacer que solo se planifique cuando hay interrupciones, ya que syscalls no hay? Podemos planificar en más momentos aunque teóricamente no sería lo acertado?.

📔 Cita del enunciado
"De esta manera, una implementación que contradiga lo visto en clase o lo escrito en el documento es motivo de desaprobación del trabajo práctico."

**Comment by RaniAgus** [comment]
¡Buenas! Es una buena pregunta de coloquio. Por supuesto que en el TP hay _system calls_ ya que el módulo Kernel es _llamado_ realizar operaciones que un proceso en modo usuario no tiene permisos para hacerlo. Dicho esto y sabiendo lo que mencionabas de que el sistema planifica ante syscalls o interrupciones, les devuelvo la pregunta: ¿qué syscalls podrían identificar en el TP? Saludos

**Comment by Sancho6446** [comment]
Buenass, se nos mezclaron varios conceptos, las I/O son syscall, también Exit , wait  y signal entonces estaría bien si cuando pasan algunas de estas cosas ponemos a los procesos en la cola de ready o ready+ según corresponda? Porque nosotros como lo tenemos es de esta forma, que cuando llega alguna de estas cosas agregamos el proceso al final de las cola de ready ya que todas usan FIFO de alguna forma entonces nunca re-organizamos la cola, solo sacamos del principio o metemos al final, esto cuenta como planificar? Porque como entendemos planificación es reorganizar la cola. Pero en nuestra caso está siempre ordenada porque siempre agregamos al final y sacamos del principio.

**Comment by RaniAgus** [comment]
Planificar abarca mucho más que eso: es asignar recursos para realizar tareas. Los procesos compiten por procesamiento de CPU, operaciones de IO, etc. y el planificador se encarga de determinar a quién le toca hacer lo suyo.

Reordenar la cola de READY no es un fin en sí mismo, es un medio para lograr el objetivo que es planificar a los procesos, y ese fin va más allá del algoritmo que usen.

**Comment by Sancho6446** [comment]
Entonces, estaría bien teóricamente si cuando hay una syscall o una interrupción yo los añado a la cola de ready? Porque esto sería la forma de asignar los recursos , aunque los utilizan más adelante cuando sea su turno.

**Comment by RaniAgus** [comment]
Por supuesto, ¿por qué estaría mal teóricamente? Si es justamente lo que ven en la parte teórica de la materia: al haber una cantidad limitada de CPUs y una cantidad mayor de procesos compitiendo por utilizar ese recurso, la cola de _READY_ es una "lista de espera" de todos los que están _listos_ para hacerlo

**Comment by Sancho6446** [comment]
Perfecto muchas gracias!!
