### ISSUE TITLE
Consulta rapida: Dos o más interrupciones al mismo proceso en la CPU

### ISSUE THREAD

**Issue by ArielRotolo** [sisoputnfrba/foro#4048]
Buenas noches, me surgió una duda acerca de que pasaría si el Kernel quiere matar un proceso por lo que enviá una interrupción de FINALIZAR pero en el tiempo que la CPU está por ejemplo en la etapa fetch esperando recibir una instrucción de la memoria... Al proceso se le termina el Quantum por lo que el Kernel enviá otra interrupción. Tenemos que tener en cuenta este caso?

**Comment by f-and** [comment]
Buenas, es un caso muy borde, seguramente no se va a probar ya que requeriría de una precisión muy buena para calcular como enviar la interrupción de finalización.
Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Me sumo solo para decir que probablemente hayan visto que las interrupciones en la CPU pueden tener prioridades. Así que, en caso de que quieran implementarlo, ¿qué interrupción es más prioritaria? ¿Fin de quantum o finalizar proceso? Saludos

**Comment by ArielRotolo** [comment]
Perfecto, me imagino que el finalizar proceso tiene prioridad pero la verdad no quiero complicarme más la existencia, por ahora lo dejamos así jajaja.Y si sobra el tiempo implementaremos la prioridad de interrupciones. Gracias :)
