### ISSUE TITLE
Duda prueba de planificacion e interrupciones 

### ISSUE THREAD

**Issue by Sancho6446** [sisoputnfrba/foro#4049]
Buenas noches
Nuestra duda viene dada por el Quantum y los milisegundos de este y cuando le llega la interrupcion ya que algunas veces ejecuta una instruccion de mas. 

### 👍 Comportamiento esperado
En la prueba de planificacion tanto en VRR y RR, se espera que un proceso sea desalojado por Quantum una X cantidad de veces.

"En RR finalizan PLANI_1, luego PLANI_3 (el cual es desalojado 2 veces por fin de quantum) y por último PLANI_2. PLANI_4 continúa ejecutando. 
En VRR finalizan en el mismo orden que RR, pero PLANI_3 es desalojado 3 veces por fin de quantum.
"

### 👎 Comportamiento obtenido
Al hacer las respectivas pruebas llegamos a que en algunas ejecuciones PLANI_3 termina siendo desalojado uan vez mas de la esperada debido a este problea de Quantum.

Deberiamos arreglar este error? Ya que en estos issues: #3700 #3775 #3634 se menciona que las pruebas no van a tener este aspecto en cuanta entonces talvez no es importante estas X cantidad de desalojos en la prueba de planificacion. Tambien solo pasa en algunas ejecuciones y se nos ocurre que cuando sea distribuido y todo mas lento este error sea mas propenso a que pase.

**Comment by RaniAgus** [comment]
¡Buenas! La prueba está pensada para ser determinística. Repasemos el código de PLANI_3

- El quantum está configurado en (casi) 3 segundos 
- El tiempo de retardo por petición a Memoria es de 1 segundo
- PLANI_3 en FIFO ejecuta 2 ráfagas de 5 instrucciones (es decir, 5 segundos)

Entonces:
- En RR, ejecuta (3 + 2) y (3 + 2) -> 2 desalojos
- En VRR, ejecuta (3 + 2 + 1) y (3 + 2) -> 3 desalojos

Les recomendaría reconstruir el Gantt en base a los logs y evaluar en dónde estaría ocurriendo el problema que hace que la ejecución no sea determinística.

Saludos

**Comment by Sancho6446** [comment]
Dale muchas gracias, y una última cosa nosotros usamos el timer de las commons para el Quantum, cuando sea distribuido esto no nos puede traer problemas ya que tal vez la comunicación tarda más al estar en computadoras separadas o al ser parte de la misma red no cambia mucho la velocidad de comunicación?

**Comment by RaniAgus** [comment]
¡Buenas! Al tratarse de una red interna las comunicaciones son rapidísimas. 

Solo si tuvieran que salir a internet podrían haber problemas de ese estilo, por ejemplo si intentan usar `ngrok` o alguna herramienta similar las pruebas les pueden dar distinto.

Saludos

**Comment by Sancho6446** [comment]
Perfecto, gracias.
