### ISSUE TITLE
config kernel y consola interactiva

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#4051]
Buenas, quería preguntar por qué en memoria tenemos un parametro en el config que indica el path de pseudocodigos pero en kernel no tenemos una de path a los scripts. ¿Es porque estos estarán siempre en la carpeta de kernel, en una subcarpeta llamada "scripts"?

**Comment by RaniAgus** [comment]
No está especificado en el enunciado en qué carpeta van a encontrarse los scripts y tampoco es relevante a los contenidos de la materia. Como está especificado al principio del enunciado, _en caso de que el grupo requiera de algún parámetro extra, podrá agregarlo_ al archivo de configuración.

**Comment by rood8592** [comment]
Ok y otra duda sobre kernel y es que se nos mezclan los logs con la consola interactiva, o sea se puede seguir escribiendo pero a veces resulta molesto que estas escribiendo un comando y te interrumpe un log de kernel, aunque despues puedas seguir y completar el mismo. Creo que la solución más sencilla seria ver los logs de kernel desde el archivo .log y no logearlos por consola, al menos solo en kernel porque en cpu, memoria, etc no existe este problema pero no sé que es lo que esperan en las pruebas con respecto a esto.

**Comment by rood8592** [comment]
PD: Ahora que lo pienso no sé como sería posible eso de leerlo desde el .log en la vm de las pruebas porque en la vm con interfaz grafica es facil, lo podes ver desde el mismo visual y se va actualizando en "tiempo real".

**Comment by RaniAgus** [comment]
Buena pregunta, en la [guía de Bash](https://docs.utnso.com.ar/guias/consola/bash) les dejamos un montón de comandos útiles, entre ellos `tail -f` y `less +F`. Ambos sirven para visualizar logs en tiempo real.

También, para prepararse para la entrega, tenemos la [guía de despliegue de TP](https://docs.utnso.com.ar/guias/herramientas/deploy)

**Comment by rood8592** [comment]
Perfecto, gracias Agus!
