### ISSUE TITLE
Dudas varias despliegue y laboratorios

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#4052]
Buenas, hoy fuimos al labo de medrano para probar el tp pero no pudimos por un corte de luz pero nos surgieron varias dudas para ir algún dia de la prox semana:

1 - Agarramos unas maquinas que no tenian instlado el putty en el laboratorio rojo y no podiamos instalarlo porque pedia contraseña de administrador (si contaba con las vms sin interfaz grafica de 2022). Por ahí no son las computadoras que utilizan para las pruebas y esa es nuestra duda, en cual labo suelen probar los tps y con que PCs?

2 - Si hay un labo cerrado, que hoy era el naranja, podemos pedir que lo abran o debe pedirlo si o si un profesor? Nos dejaron pasar al rojo porque el profe que habia reservado nos permitio entrar porque habias PCs libres pero nos olvidamos de preguntar si nos podian abrir el labo naranja.

3 - Nada que ver pero veo que hablan mucho de chmod en algunos issues del años previos y está en la guia de bash ¿Para qué nos puede servir para el despliegue del TP?

**Comment by f-and** [comment]
Buenas!
1. Normalmente solemos settear las computadoras, igual, y esto solo como consejo, pueden usar [SSH](https://learn.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse?tabs=gui#connect-to-openssh-server) para conectarse directamente a las maquinas virtuales, Putty no es requerido, y a su vez, no es requerido instalar Putty ya que este permite descargar versiones portables para ejecutar sin instalar! 
2. Esto por fuera de la cátedra, los labos de Sistemas pueden ser solicitados directamente al Departamento de Sistemas, se envía un mail antes de la fecha y se los reserva.
3. No creo que esté relacionado con el despliegue en sí, si hay algún problema de permisos les sirve para eso, pero seguramente no sea algo que tengan que memorizar para la entrega.
Saludos.-

**Comment by rood8592** [comment]
Gracias y relacionado a la primera duda  en la guia de despliegue dice que nos pueden pedir instanciar más consolas sobre la misma VM por lo que entiendo tendrán la misma IP pero distinto puerto. Esto implicaria abrir otra consola de powershell y hacer un @ssh con la misma ip o tirar el comando tmux y screen en la consola que ya tenemos? Porque en la que es con interfaz grafica simplemente hacemos click izquierdo en la consola y seleccionamos split vertical o horizontal.

**Comment by f-and** [comment]
Tmux, si mal no recuerdo, no anda para las VM servidor, ni tampoco para los SSH, por lo que lo recomendable es que abran otro Powershell y corran el mismo comando, eso si, SSH admite más de una conexión por puerto, por lo que pueden usar el mismo puerto para abrir más de una consola.

**Comment by RaniAgus** [comment]
¡Buenas! Me sumo solo para aclarar que el puerto por el cual uno se conecta por SSH es siempre el puerto 22, y no hace falta especificarlo:

```
ssh utnso@192.168.0.142
```

Una vez conectados, es como si tuvieran interfaz gráfica y abrieran una terminal desde la VM.

Saludos

**Comment by rood8592** [comment]
Ok, gracias @RaniAgus y @f-and !
