### ISSUE TITLE
Duda sobre persistencia de archivos del FS

### ISSUE THREAD

**Issue by nicolasreypc** [sisoputnfrba/foro#4053]
Buenas, tengo la duda de si se debe poder acceder a un archivo que fue creado en una ejecucion pasada... , en caso de que la respuesta sea si, es recomendable tener un archivo que contenga todos los nombres de los metadatas creados. Con el objetivo de poder referenciar a estos metadatas? Esto se debe a que en mi implementacion actual, para poder hacer la compactacion tengo una lista con los nombres de los archivos, y para mantener esta actualizada deberia guardar los nombres de los archivos de ejecuciones pasadas en un archivo.

**Comment by RaniAgus** [comment]
¡Buenas! Cuando creen los archivos ya va a existir un archivo con sus nombres, y éste es el directorio en el que se guardan :D
Pueden investigar alguna forma de leer todos los nombres de los archivos que se encuentren en la carpeta base del DialFS desde C.

Saludos

**Comment by nicolasreypc** [comment]
okey. Podemos implementar la biblioteca <dirent.h>?
Para usar las funciones  'opendir, readdir y closedir'

**Comment by RaniAgus** [comment]
Como dicen las [normas del TP](https://docs.utnso.com.ar/primeros-pasos/normas-tp#aclaraciones-sobre-el-desarrollo), pueden usar cualquier biblioteca instalada en las VMs.

El header `<dirent.h>` forma parte de la libc (la biblioteca estándar de C), así que pueden usarlo 👍🏻 

Saludos

**Comment by nicolasreypc** [comment]
graciass
