### ISSUE TITLE
Duda sobre lote de pruebas finales.

### ISSUE THREAD

**Issue by Lopez-AN** [sisoputnfrba/foro#4055]
buenos dias.

Con mi grupo queriamos saber cuando va a estar disponible el lote de pruebas final. Ya hace algunos dias tenemos el tp "terminado" y deseariamos poder hacer los test con tiempo antes de la entrega por si surge algun bug grave.

Imagino que los demas grupos tendran la misma inquietud

Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

Las pruebas se van a estar publicando en estos días, al mas tardar el día 6.

Saludos.-

**Comment by Lopez-AN** [comment]
gracias, saludos
