### ISSUE TITLE
DUDA BITMAP FS

### ISSUE THREAD

**Issue by bautistaiglesias** [sisoputnfrba/foro#4056]
Buen día, una consulta sobre el bitmap del FS.
1- Es necesario manejar el bitmap del FS con la función mmap (o sea mapeando el archivo en memoria)?  o se puede manejar con un bitmap del tipo t_bitarray* y con la función msync sincronizar los cambios en el archivo?
2- Estaría mal hecha la implementación del FS si tengo una lista de fcbs y cuando llegue alguna operación consulto los datos ahí, y en caso de que se necesite modificarlos, modificar el fcb y además el archivo metadata correspondiente?

**Comment by RaniAgus** [comment]
¡Buenas!
1- ¿Cómo harías para usar `msync()` sin usar `mmap()`? Justamente el primero sirve para sincronizar memoria mapeada por el segundo. Por otro lado, `t_bitarray` permite manipular cualquier tipo de memoria, así que podrían usar memoria mapeada.

2- Estaría bien, pasaría las pruebas 👍🏻. Luego en el coloquio pueden contarnos por qué lo implementaron así y qué ventajas o desventajas tendría con otras alternativas 😉

Saludos

**Comment by bautistaiglesias** [comment]
Gracias, respecto a la primera pregunta ya lo solucione, saludos!
