### ISSUE TITLE
Duda relacion archivo - bloques.dat - Memoria en FS read/write

### ISSUE THREAD

**Issue by mvargassoto** [sisoputnfrba/foro#4057]
Buenas! tengo una duda con respecto a la secuencia a cumplir en las instrucciones FS read/write, cito el caso FS read:

>  Esta instrucción solicita al Kernel que mediante la interfaz seleccionada, se lea desde Memoria la cantidad de bytes indicadas por el Registro Tamaño a partir de la dirección lógica que se encuentra en el Registro Dirección y se escriban en el archivo a partir del valor del Registro Puntero Archivo.

1. Lo que entiendo es que voy a leer una cadena de bytes de Memoria, una vez que la tenga la voy a escribir en bloques.dat y en el archivo de usuario (que entiendo que siempre son .dat, menos el metadata del mismo), esto es asi?
En el caso de FS write termina siendo la misma duda pero a la inversa

1.2 - Si tengo que escribir exactamente lo mismo tanto en archivo de usuario como en bloques.dat entonces podria usar de alguna manera mmap ahi tambien, no?

**Otras dudas FS**

2. Puede pasar que el usuario en una instruccion intente usar FS create con un archivo existente, cuando se da ese caso la manera de proceder seria levantar el archivo existente, ver en el metadata del mismo el tamaño que se le asigno y volver a cargar toda su info en bloques.dat, seria asi? en caso de ser asi, y si cuando reinicio FS bloques.dat ya esta cargado? como recupero la relacion o el enlace de cada archivo con bloques.dat (sus asignaciones anteriores)? Me marean esos casos sabiendo que FS tiene que poder reiniciarse y mantener el progreso anterior

3. Que los archivos se mantengan siempre abiertos y con libre acceso a todos los usuarios seria la idea, no? mas que nada para trabajar a partir de eso con estructuras

4. Relacionado a la anterior, que tan optimo seria eso, porque al final siempre ejecutamos de a un proceso, tambien tenemos un solo modulo FS, entonces nunca se daria el caso en donde dos procesos usen exactamente al mismo tiempo un archivo, no podria simplemente abrir el archivo cuando un proceso lo pide y cuando el mismo termina su solicitud cerrarlo (al que llego por instruccion)?

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Los archivos les pudimos `.dat` pero la extensión es una convención que solo importa en windows, a linux le da lo mismo y puede ser `.dat`, `.pep` o `.utnso`, lo importante es que los archivos de metadata se puedan leer como si fueran un archivo de config y el de bloques si sea tipo binario porque van a guardar tanto números (lo que esta en los registros de la CPU) como strings.

1.2.- Si quieren usar `mmap()` esta perfecto.

2.- No vamos a pboar el caso de crear un archivo existente.

3.- Si, de hecho este FS es sumamente simple y la idea es que no se compliquen con nada de permisos.

4.- No vamos a probar la concurrencia de accesos a los archivos, el foco del FS es que entiendan los pros y contras de la asignación contigua, para permisos y demas necesitaríamos mucha mas metadata que no tenemos a propósito.

Saludos.-

**Comment by mvargassoto** [comment]
Muchas gracias por las aclaraciones!, te tengo joder con una que no entendí perdón, la número 1, entiendo que el archivo de usuario entonces tiene cualquier extensión, lo que si no me queda claro es, por ejemplo en FS write, además de escribir en bloques.dat y actualizar todo lo que eso implique, tengo que escribir exactamente lo mismo en el archivo de usuario, no? Pero a partir del puntero archivo que me llega desde la instrucción

**Comment by iago64** [comment]
Buenas! Cómo va?

La info que leen de memoria la escriben en el archivo de bloques.dat solamente.

Saludos.-

**Comment by mvargassoto** [comment]
Todo claro, muchas gracias!
