### ISSUE TITLE
Duda de accesos a Ready

### ISSUE THREAD

**Issue by LeonelArianContreras** [sisoputnfrba/foro#4058]
Hola! Estamos teniendo problemas con respecto a los tiempos de acceso a Ready. Por ejemplo, cuando usamos RR con un quantum de 2000 ms (con 3000ms llegan a cumplir bien el orden), y ejecutamos un script de 5 procesos (0-4), los primeros cuatro ingresan a ready, pero el proceso 0 ejecuta y llega a meterse de vuelta a la cola por fin de quantum antes de que el último, el 4, ingrese por primera vez. De modo que el orden en el que ejecutan es 0-1-2-3-0-4-1-2-3 ... Sé que quizá a estas alturas suene a que el problema ya debería estar resuelto, pero se nos pasó de largo sinceramente. Gracias de antemano!

**Comment by iago64** [comment]
Buenas! Cómo va?

En primer lugar, lo que estan haciendo esta bien igual, te resuelvo el problema mas fácil, corrieron las pruebas preliminares?
Para ver estos comportamientos que esperamos que sean deterministicos tenemos calculados los retardos y usamos solamente 3 procesos, la prueba de muchos procesos vamos a buscar otras cosas y no controlar como se manejaron con los tiempos de RR / VRR.

Saludos.-

**Comment by LeonelArianContreras** [comment]
Gracias por responder! Entonces no habría problema con el orden de ejecución siempre y cuando se respete el algoritmo y cumpla con los resultados de las pruebas? Perdón que repregunte, pero es para quedarnos tranquilos.

**Comment by iago64** [comment]
Buenas! Cómo va?

Te recomiendo que revises de nuevo las pruebas en el siguiente link: [Pruebas Preliminares](https://faq.utnso.com.ar/tp-c-comenta-pruebas), para las pruebas de RR y VRR ahi están detallados los resultados esperados.

Saludos.-
