### ISSUE TITLE
Duda sobre IO_FS_READ

### ISSUE THREAD

**Issue by lewislee0920** [sisoputnfrba/foro#4060]
Buenas, cuando corremos la instruccion de IO_FS_READ, tenemos que abrir el archivo y leer el contenido que apunta desde el puntero archivo y copialo a memoria o sera que leamos desde el bloques.dat (El variable que basicamente usa el mmap) y copia lo que esta hay directamente a memria sin tener que abrir el archivo?

**Comment by iago64** [comment]
Buenas! Cómo va?

Tienen que leer el contenido del bloques.dat directamente, en este TP no tenemos nada parecido a la apertura de archivos, de hecho no existe la instrucción IO_FS_OPEN o similar.

Saludos.-

**Comment by lewislee0920** [comment]
Gracias
