### ISSUE TITLE
Direcciones Físicas escribiendo un tamaño mayor a una pagina.

### ISSUE THREAD

**Issue by lucasluna068** [sisoputnfrba/foro#4061]
Buenas, tengo una consulta respecto a la escritura en espacio de usuario al momento de querer escribir en una pagina un valor mayor a su tamaño. Entiendo como funciona la distribución del dato gracias al issue #3566 y que la MMU es la encargada de hacer la traducción de una Dirección lógica a física. Ahora, al momento de querer escribir en una pagina mas de lo que en esta entra, tengo que pasar a la siguiente (Ya sea IO o CPU el que quiere escribir en memoria).

El manejo de "Escribir en la siguiente" por falta de espacio en la pagina, es tarea de la MMU, creando nuevamente una dirección física? o es tarea de la memoria separar y que quede bien distribuidos en sus paginas? Entiendo que es la primera.

En el primer caso, por ejemplo, terminaría teniendo que enviarle de CPU a IO, varias direcciones físicas y cuanto escribir en ellas para que pida la escritura/lectura a la memoria en cada una de esas DF.

Y en el segundo, desde la memoria, podría calcular a que proceso corresponde el marco de la DF y fijarme cual es la siguiente pagina para escribir en ella.

Desde ya muchísimas gracias! Espero haberme explicado bien.

**Comment by RaniAgus** [comment]
¡Buenas! Misma respuesta que en: https://github.com/sisoputnfrba/foro/issues/3863#issuecomment-2163016424

TL,DR: Esta es la opción correcta:

> terminaría teniendo que enviarle de CPU a IO, varias direcciones físicas y cuanto escribir en ellas para que pida la escritura/lectura a la memoria en cada una de esas DF.

Saludos

**Comment by lucasluna068** [comment]
Muchísimas gracias. Entendido! Saludos!
