### ISSUE TITLE
Read/Write - Duda sobre traduccion de multiples paginas

### ISSUE THREAD

**Issue by Brai93** [sisoputnfrba/foro#4062]
Buenas,

Queria confirmar unas dudas sobre la lectura/escritura de una instruccion en el caso que el "contenido" consuma varias paginas:

1. Entiendo que debemos tomar en cuenta el offset para calcular la cantidad de paginas a consumir, es correcto?? En el sentido que por ejemplo puedo tener por cfg paginas de 4b y un contenido a escribir de 5b... por lo que dependiendo del offset podria terminar escribiendo 2 o 3 paginas.

2. Es correcto suponer que al realizar numero_pagina = floor(dir_logica / PAGE_SIZE), en el caso de multiples paginas, la pagina siguiente seria numero_pagina+1?? Esto surge de que una instruccion tiene una DL solamente. NOTA: Se utiliza una tabla de paginas por proceso, donde las paginas siempre comienzan del 0....100

3. Suponiendo que tenga un TLB HIT sobre un proceso que tuvo un resize disminuyendo su tamaño, cual seria el comportamiento esperado en estos casos?? ya que en este caso podria invadir el espacio de otro proceso o bien que no sea asociado a ninguno.

Muchas gracias por su ayuda!

**Comment by RaniAgus** [comment]
¡Buenas!

1. Sí, según el offset podrías necesitar una página más o no

2. Sí, podría decirse las páginas están "contiguas" de forma lógica (o sea, primero viene la 0, luego la 1 y así...). Este comment les puede servir: https://github.com/sisoputnfrba/foro/issues/3863#issuecomment-2163016424

3. No vamos a probar segmentation faults. De todas formas está muy buena la pregunta: luego de hacer resize deberías ser capaz de invalidar esas entradas de TLB, ya que al conocer el tamaño del proceso podés saber hasta qué número de página llega.

Saludos

**Comment by Brai93** [comment]
Una ultima consulta...

Siguiendo esta respuesta y el hilo del comentario:

> 2. Sí, podría decirse las páginas están "contiguas" de forma lógica (o sea, primero viene la 0, luego la 1 y así...). Este comment les puede servir: [pequeñas dudas sobre la escritura en memoria #3863 (comment)](https://github.com/sisoputnfrba/foro/issues/3863#issuecomment-2163016424)


En caso de tener un proceso con 3 paginas de  4 bytes, y una instruccion q pide escribir en la pagina 2, por 9 bytes (3 paginas), como deberia responder?
La "pagina 3" de la instruccion deberia escribirse en la pagina 1 del proceso o responder un OUT_OF_MEMORY (anulando la operacion)? La consulta surge porque si la mmu asume que el contenido deberia ser copiado en la pagina siguiente, haria una peticion de frame inexsistente a memoria

Gracias!

**Comment by RaniAgus** [comment]
Eso sería otro caso de segmentation fault: estarías intentando escribir en una página que no está reservada, entonces la Memoria te devuelve que no existe el frame y ese proceso no podría continuar.

Como expliqué en el comentario citado, no tendría sentido "pegar la vuelta" y dejarlo en la página inicial porque el contenido quedaría desparramado en otro rango de direcciones lógicas. Además un resize para aumentar el tamaño te rompería todo lo guardado.

**Comment by Brai93** [comment]
Entiendo, seria otro caso border que podemos evitar pero no son necesarios entonces.

Muchas gracias por tus respuestas Agus, con esto puedo seguir! :)
