### ISSUE TITLE
Ingresar comandos en tiempo de ejecucion

### ISSUE THREAD

**Issue by GabrielIacomini** [sisoputnfrba/foro#4063]
Hola buenas !! Con mi grupo nos encontramos con una duda acerca de como seria posible ingresar comandos en la consola del Kernel en tiempo de ejecución. Esto se debe a que se nos esta complicando ingresarlos para probar detener la planificación y demás, ya que los logs nos imposibilitan ingresar los comandos. No estamos seguros de como podríamos implementarlo.
Una solución posible, que creemos que no es correcta, es que la consola esté en una terminal distinta y en otra se muestren los logs. 
Graciass.

**Comment by mefederico** [comment]
Hola buenas! 

Pueden configurar que los logs solo se manden a un archivo y para leer los logs en otra consola pueden hacer lo que recomienda Agus en este otro https://github.com/sisoputnfrba/foro/issues/4051#issuecomment-2196770156

Saludos!

**Comment by GabrielIacomini** [comment]
Ahi estuve viendo, decis que cambiemos el LOG_LEVEL para no visualizarlos en la terminal y despues ir tirando tail -f <archivo..log> y poder ir viendo los logs ?

**Comment by GabrielIacomini** [comment]
No dije nada, es solamente cambiar el bool del log_create a 0 no ?

**Comment by GabrielIacomini** [comment]
Listo, ahi ya pude mil graciass
