### ISSUE TITLE
 Cantidad de desalojos en RR

### ISSUE THREAD

**Issue by MilagrosCuevas** [sisoputnfrba/foro#4064]
Hola! Tengo una duda con las pruebas de planificación. 
### 📔 Citas del documento de pruebas

[Resultados Esperados](https://docs.google.com/document/d/1fggUfh9Kj9E8ngDOF6m7nmaMU8g5pr0szhV-0TMaRNE/edit#heading=h.7n5hdaymbtd0)
"En RR finalizan PLANI_1, luego PLANI_3 (el cual es desalojado 2 veces por fin de quantum) y por último PLANI_2. PLANI_4 continúa ejecutando." 

¿Los demás procesos pueden también ser desalojados o no debería?

### 👍 Comportamiento esperado
El documento solo especifica que PLANI_3 es desalojado 2 veces. 

### 👎 Comportamiento obtenido
PLANI_3 fue desalojado 2 veces y los demás procesos también fueron desalojados en algún momento por fin de quantum.

**Comment by iago64** [comment]
Buenas! Cómo va?

Lo que nos importa de RR es justamente el orden en el que terminan (PLANI_1, PLANI_3, PLANI_2) y que PLANI_3 fue desalojado 2 veces por quantum, mientras que en VRR la diferencia es que PLANI_3 es desalojado 3 veces por quantum.

Saludos.-

**Comment by MilagrosCuevas** [comment]
Gracias!
