### ISSUE TITLE
DUDA COMPACTACION

### ISSUE THREAD

**Issue by bautistaiglesias** [sisoputnfrba/foro#4065]
Buenas noches, tengo una consulta sobre compactación.

1- Al momento de hacer la compactación, se me ocurrió crear un archivo auxiliar para copiar todo el archivo original y poder guardar el contenido sin perderlo, y una vez copiado todo empezar a escribir en el archivo original pero haciendo la compactación. Esto sería una implementación valida o debería buscar otra forma de realizarlo?

**Comment by iago64** [comment]
Buenas! Cómo va?

Si, es una implementación válida, solo tené en cuenta que "desventaja" le ves a esa forma de hacerlo para conversarlo en el coloquio.

Saludos.-
