### ISSUE TITLE
Duda con segmentation fault

### ISSUE THREAD

**Issue by lewislee0920** [sisoputnfrba/foro#4067]
Buenas, si tengo una funcion que manda una paquete y recibe al otro para confirmacion. Este funcion funciona sin problema en una funcion pero en otro me esta tirando segmentation fault. Que puede ser la problema en este caso?

**Comment by iago64** [comment]
Buenas! Cómo va?

Como dijimos muchísimas veces, los ayudantes por desgracia adivinos no somos, podemos entender el problema con algo de contexto, con lo cual, antes que nada, ¿Lo corrieron con Valgrind para ver si no estan mandandose alguna cagada con la memoria? Si lo corrieron con valgrind y no entienden el output, ¿Nos lo podrías pasar diciendonos que parte no se entiende y el código de la función que esta fallando?

Saludos.-

**Comment by lewislee0920** [comment]
Buenas, podia solucionarlo para elsiguiente muestro el codigo tmb
