### ISSUE TITLE
IO_FS_WRITE

### ISSUE THREAD

**Issue by VEBravo** [sisoputnfrba/foro#4068]
Buenas! La instrucción io_fs_write, en caso de que se quiera escribir desde una posición dentro del archivo pero un tamaño mayor a lo que queda del archivo, qué se debería hacer?
1. Escribir la parte que entra en el archivo y cortar al llegar al final
2. No hacer la escritura
3. Pensé en truncar, pero por lo que tengo entendido esto solo se hace mediante la instrucción

### 📔 Citas del enunciado/videos
IO_FS_WRITE (Interfaz, Nombre Archivo, Registro Dirección, Registro Tamaño, Registro 
Puntero Archivo): Esta instrucción solicita al Kernel que mediante la interfaz seleccionada, se 
lea desde Memoria la cantidad de bytes indicadas por el Registro Tamaño a partir de la 
dirección lógica que se encuentra en el Registro Dirección y se escriban en el archivo a partir 
del valor del Registro Puntero Archivo.

**Comment by mefederico** [comment]
Hola buenas! 

No es un caso que vayamos a probar, si quieren detectarlo por si hay algo mal en la prueba y/o su código pueden loggear el error y terminar la IO si les parece conveniente

Saludos!

**Comment by VEBravo** [comment]
Ah okey! Muchas gracias
