### ISSUE TITLE
Duda de segmentation fault

### ISSUE THREAD

**Issue by lewislee0920** [sisoputnfrba/foro#4069]
![image](https://github.com/sisoputnfrba/foro/assets/62365146/a32bd19f-d014-41be-b8e4-35980e12c0bc)
Buenas, en caso de que me da segmentation fault en este situiacion, como puedo saber que exactamente es la problema? porque este funcion si esta funcionando en otros partes pero en una sola esta tirando error. 

![image](https://github.com/sisoputnfrba/foro/assets/62365146/7ee6ea68-ba59-4796-bd4f-74d9cb2b0c29)
es en la funcion de traduccion_logica que esta produciendo el error.

![image](https://github.com/sisoputnfrba/foro/assets/62365146/b38ca1dd-a4d0-42e3-a979-ef012b4a7bee)

**Comment by lewislee0920** [comment]
Despues que se encuentra la parte de dirFisica = traduccionLogica() no se avanza

**Comment by RaniAgus** [comment]
¡Buenas! Para encontrar la posible causa del problema te recomiendo usar el debugger para seguir el estado de las variables que le pases a la función que falla (en este caso, `list_get`).

También pueden usar Valgrind para detectar errores de manejo de memoria, o Helgrind para detectar posibles condiciones de carrera. Pueden encontrar una guía al respecto en el sitio docs.

Saludos

**Comment by RaniAgus** [comment]
PD: Si necesitan una ayuda más concreta, porfa ayúdennos a ayudarles siguiendo los [lineamientos del foro](https://github.com/sisoputnfrba/foro/blob/master/README.md)

**Comment by lewislee0920** [comment]
ok, gracias por la ayuda
