### ISSUE TITLE
Pruebas en la entrega

### ISSUE THREAD

**Issue by tomipodo** [sisoputnfrba/foro#4070]
Buenas! Cómo andan?
Una consulta, nos van a mandar las pruebas que realizaremos en la entrega del TP antes de la entrega, o serán "sorpresa"?
Creíamos que no las mandaban, pero leyendo la guía del despliegue vimos que está bueno tener las config preparadas de antemano. Sin tener las pruebas antes del día de la entrega no podríamos tener las configs preparadas, por eso la duda.
Muchas gracias.
Saludos!

**Comment by RaniAgus** [comment]
¡Buenas! Sí, va a haber un documento de pruebas (de hecho, ya hay uno de pruebas preliminares). El ayudante puede decidir en el momento si hacer una leve modificación a la prueba en casos particulares, pero las que figuran en el documento son nuestra "base".

Entonces, les recomendamos fuertemente tener las configs preparadas para todas las pruebas del documento, así cuando pasemos de una prueba a la otra no perdamos 5 minutos en editar configs.

Saludos

**Comment by tomipodo** [comment]
Ah genial! No sabíamos que se iba a probar exactamente eso (o por lo menos con esas configs).
Muchas gracias!
