### ISSUE TITLE
Prueba de IO_FS_READ

### ISSUE THREAD

**Issue by lewislee0920** [sisoputnfrba/foro#4072]
Buenas, me esta saliendo segmentation fault pero no podia ver que esta mal en el codigo. por caso el prueba estaria mal? En caso de que si es como hago la prueba? El segmentation fault se genera cuando trata de buscar una marco de pagina en el tabla de pagina porque la pagina a buscar tiene rango fuera de tabla de paginas. 
![image](https://github.com/sisoputnfrba/foro/assets/62365146/182b336b-9c27-4582-a837-43426d0d8ea6)

**Comment by RaniAgus** [comment]
¡Buenas! La definición de `IO_FS_READ` es la siguiente:

> **IO_FS_READ** (Interfaz, Nombre Archivo, Registro Dirección, Registro Tamaño, Registro Puntero Archivo): Esta instrucción solicita al Kernel que mediante la interfaz seleccionada, se lea desde el archivo a partir del valor del Registro Puntero Archivo la cantidad de bytes indicada por Registro Tamaño y se escriban en la Memoria a partir de la dirección lógica indicada en el Registro Dirección.

Por lo tanto, en orden, requiere de:

1. Que haya un dispositivo de Entrada/Salida tipo DialFS llamado `"DIALFS"` conectado.
2. Que ya exista un archivo llamado `archivo_prueba.txt` en la ruta base del DialFS conectado.
3. Como el registro dirección es `AX` y vale 4 y el registro tamaño es `ECX` y vale 5, esto implica que se va a leer desde la dirección 4 hasta la 8 inclusive. Es decir, tu proceso debería tener un tamaño de 9 bytes como mínimo en Memoria.
4. Como el registro puntero archivo es `EDX` y vale 12 y el registro tamaño es `ECX` y vale 5, el archivo antes mencionado debe tener un tamaño mínimo de 17 bytes.

Una vez más, los invito a leer los [lineamientos del foro](https://github.com/sisoputnfrba/foro/blob/master/README.md), ya que hay sugerencias sobre consejos que nos ayudan a poder ayudarles.

Saludos

**Comment by lewislee0920** [comment]
ah perdon olvidava del lineamiento, poximo seguro hago con formato
