### ISSUE TITLE
Persistencia de los archivos de metadata del FS

### ISSUE THREAD

**Issue by nsantero** [sisoputnfrba/foro#4073]
Hola, estaba pensando la implementación del algoritmo de compactación del FileSystem y me surgio una duda con respecto a la persistencia en memoria de los archivos de metadata. Cada vez que se corre este algoritmo deberia buscar en memoria la metadata de todo los archivos para saber a cual pertenecen los bloques ocupados y poder actualizarlos. Pense una implementacion con un struct 
```c
typedef struct 
{
    char* nodo_path;
    off_t nodo_offsetBloqueInicial;
    int nodo_tamanioEnBytes;
} NodoFs;
```
pero esto solo me serviria para guardar los archivos creados antes de la coneccion del FS.
Pense como otra solucion tener un archivo donde se guarden los nombres de todos los archivos de metada q se hayan creado. Creo que esta implementacion estaria mejor, complementado a la del struct(que vi en otra issue que la usaban con una lista). El tema es que para esto me convendria poner un tamaño maximo al nombre de los archivos para poder leer el archivo con los nombres mas facil y no se si esto entraria en comflicto con el enunciado y pruebas del tp.

**Comment by RaniAgus** [comment]
¡Buenas! No deberías necesitar crear otro archivo extra, ya existe uno que contiene todos los nombres de los archivos de metadata, y ese es el directorio en el que están guardados 😄 

Pueden investigar alguna forma de leer todos los nombres de los archivos que se encuentren en la carpeta base del DialFS desde C. Como dicen las [normas del TP](https://docs.utnso.com.ar/primeros-pasos/normas-tp#aclaraciones-sobre-el-desarrollo), pueden usar cualquier biblioteca instalada en las VMs. Si surge alguna duda o problema y no logran resolverlo avísennos y lo vemos.

Saludos

**Comment by RaniAgus** [comment]
¡Buenas @nsantero ! ¿Les sirvió la respuesta? Saludos

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, si les quedó alguna duda pueden abrir uno nuevo referenciando éste. Saludos
