### ISSUE TITLE
Errata prueba IO

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#4074]
Buenas! no quiero molestar mucho con esto pero voy mandando para evitar problemas en la entraga
En la prueba IO se les traspapelaron cosas del tp anterior, no se si el objetivo era retocarla un poquito o que quede como estaba antes

Ya que estamos aprovecho el mismo issue para la prueba de Salvations Edge. Dice de cambiar el grado de multiprogramacion a 10, pero ya arranca en 10, por lo tanto no haria nada esto

**Comment by RaniAgus** [comment]
¡Buenas! Por _cosas_ del TP anterior entiendo que te referís al algoritmo "PRIORIDADES", ¿cierto?

De ser así, ya está corregido, de todas formas el algoritmo que usen no debería afectar lo que se imprime por pantalla en esa prueba.

Lo otro en un rato lo revisamos, gracias por notarlo, saludos

**Comment by GonTurri** [comment]
Hola, como va?
Tambien se perdio el input que habia antes, si no me falla la memoria era escribir WAR NEVER CHANGES...  y despues Sistemas Operativos 2c2023

> Iniciar los módulos.
> Ejecutar los siguientes comandos en la consola del Kernel
> EJECUTAR_SCRIPT /scripts_kernel/PRUEBA_IO
> Esperar a que finalicen 3 procesos y cortar la prueba.
> Cambiar el algoritmo de planificación a RR y volver a ejecutar. 
> Esperar a que finalicen 3 procesos y cortar la prueba.
> Cambiar el algoritmo de planificación a VRR y volver a ejecutar.
> Esperar a que finalicen 3 procesos y cortar la prueba.
> 

Ademas no se porque habria que hacer el cambio a VRR ahi?

Saludos!

**Comment by GonTurri** [comment]
Buensa! reabro por dos cositas primero en el input de la preuba IO

> Ingresar los siguientes textos sin comillas:
> Para IO_A, “WAR NEVER CHANGES...”
> Para IO_C, “Sistemas Operativos 1c2024”

el input original de IO_C era "Sistemas Operativos 2c2023" solo por si las dudas

Y despues en la prueba de memoria el script MEMORIA_2 

```
SET EAX 0
SET EBX 10
SET EDX 0
SET ECX 1
SET DX 30
RESIZE 60
MOV_OUT DX EBX
MOV_IN EAX DX
SUB EBX ECX
SET EAX 0
EXIT
```

Se van a dar cuenta si esta bien hecha solo por los logs? o habria que agregarle un JNZ ahi??

paso un ejemplo como se podria agregar


```
SET EAX 0
SET EBX 10
SET EDX 0
SET ECX 1
SET DX 30
RESIZE 60
MOV_OUT DX EBX
MOV_IN EAX DX
SUB EBX EAX
JNZ EBX 0
SET EAX 0
EXIT
```

Como siempre, muchas gracias y nos vemos mañana!
