### ISSUE TITLE
Errata prueba FS

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#4075]
Buenas ahora vengo para revisar el comportamiento de la prueba de FS, 
Primero que los primeros dos procesos me estan compactando varias veces porque estan creando varios archivos y nuestro FS le asigna el primer bloque contiguo, entonces si los crean antes de truncar, inevitablemente va a compactar. De todos modos creo que esto no es muy grave. 
El temita es lo que me imprime el monitor:

```
[INFO] 12:45:46:183 entradasalida/(2776:2776): MEMORY VALUE: Fallout 76
Fallout 1
Fallout 2
Fallout 3
Fallout: New Vegas
Fallout 4
[INFO] 12:45:50:182 entradasalida/(2776:2776): PID: 1 - Operacion: IO_STDOUT_WRITE
[INFO] 12:45:50:683 entradasalida/(2776:2776): MEMORY VALUE:
```

creo que aca hay un pifie porque el archivo salida.txt me lo lee al reves y el cronologico no se imprime nada. Me parece que la intencion era que salida.txt se lea el texto original y en cronologico se lea, asumo que por el orden cronologico del fallout, si bien nunca lo jugue.

```
IO_FS_WRITE FS salida.txt CX EAX CX
SET SI 59
SET DI 80
COPY_STRING 10
SET BX 90
MOV_OUT BX AX
SET SI 0
SET DI 91
COPY_STRING 59
SET ECX 80
IO_FS_WRITE FS salida.txt ECX EAX CX
```

aca en FS_1 esta escribiendo en salida dos veces imagino que la gracia era que el segundo IO_FS_WRITE fuese en cronologico

Muchas gracias y disculpen si no entendi algo y me mande de cabeza

**Comment by iago64** [comment]
Buenas! Cómo va?

Si te digo que copy-paste sale mal? en el IO_FS_WRITE tendría que haber puesto cronológico en el segundo y un problema en la interfaz silla-teclado hizo que quede salida.txt.

En el último commit del repo de las pruebas esta arreglado, mil gracias por la observación

Saludos.-

**Comment by GonTurri** [comment]
Un placer, todo con tal de no ser el conejillo de indias de la entrega :(
Entonces, pasa algo si compacta mas veces de lo esperado en la creacion de los archivos o es algo que tenga que revisar?
Cuando haces 2 create seguidos le asigno el bloque 0 a uno y el bloque 1 al otro Invetiblamente cuando trunque el primero va a compactar

Saludos!

**Comment by rood8592** [comment]
Buenas, me sumo a la duda porque nosotros también, como no especificaban algoritmos en la consigna, dejamos hecho un "primer ajuste" en dialFS.

**Comment by iago64** [comment]
Buenas! Cómo va?

La compactación en el truncate de los 2 primeros archivos _está bien si se da, como también está bien si no se da_, porque como no les dijimos la forma de asignar los bloques puede ser que algun grupo penso una idea muy rebuscada y hace que al menos en los primeros 4 archivos no se tenga que compactar y solo se de la compactación cuando hacen el truncate de `pesado.txt`.

Saludos.-

**Comment by GonTurri** [comment]
Buenísimo! De paso aprovecho este hilo para también decirte que pude probar la nueva versión de la salvations y parecería que ahora va bien 👀👀👀
De todas formas todavía no lo probé distribuido así que seguro volveré con más problemas.
Ya hay alguna distribución establecida para los módulos o eso se ve en el momento ?

**Comment by iago64** [comment]
Buenas! Cómo va?

La distribución va a depender un poco de la cantidad de grupos anotados y de las máquinas que tengamos con la VM funcionando el día de la entrega, pero minimo van a ser 2 maquinas.
Para las pruebas lo que pueden probar es tener Kernel y CPU en una maquina, Memoria en otra y las interfaces de IO repartidas entre ambas maquinas para que les sea mas facil de levanta.

Saludos.-
