### ISSUE TITLE
Error deploy

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#4076]
Buenas, estamos teniendo un problema con el deploy y es el que se muestra en la imagen. No sabemos si es porque a principio de año los.h los mandamos a una carpeta distinas pero no tocamos nada del makefile.
![20240704_134553](https://github.com/sisoputnfrba/foro/assets/113353333/eade6a87-eb2d-4f81-b49e-23aa6971909a)

**Comment by f-and** [comment]
Buenas, para saber, como ejecutaron el so-deploy? Porque a lo sumo algo se pudo configurar erroneamente y te salto el mensaje informativo.

**Comment by rood8592** [comment]
![image](https://github.com/sisoputnfrba/foro/assets/113353333/949a95c1-0bf6-42f1-a9fa-44097d103460)

La carpeta deploy se crea y hacemos cd pero despues cuando ponemos el comando de cualquiera de esas 3 formas que se muestran nos tira ese error de la foto. Lo raro es cuando lo ponemos tal cual como viene con "tp-{año}-{cuatri}-{grupo}" clona las commons pero despues obviamente tira error porque no encuentra el repo.

**Comment by RaniAgus** [comment]
¿Ingresaron algún token que hayan generado cuando git les pidió usuario y password? Al ser un repo privado, es necesario autenticarse

**Comment by rood8592** [comment]
Es que no nos pidió porque se queda en esa pantalla extraña que nos deja escribir pero cuando intentamos hacerlo ppniendo el usuario primero se corta y vuelve a ppnerse la consola esperando otro comando distinto. Tipo: utnso@utnso:$_

**Comment by rood8592** [comment]
Por ahí tiene algo que ver que tengamos varias ramas en el repo (?

**Comment by RaniAgus** [comment]
CREO QUE YA SÉ POR QUÉ
![image](https://github.com/sisoputnfrba/foro/assets/39303639/3828478b-56da-4597-a880-8a4440b36676)

Su grupo se llama tp-2024-1c`-H`obbits, entonces entra en esa condición porque entiende que estás intentando ejecutar el help 🤦🏻‍♂️ 

En un rato sale fix

**Comment by f-and** [comment]
Igual esa pantalla es un comando de Linux llamado [Less](https://man7.org/linux/man-pages/man1/less.1.html), tiene caracteres raros por un problema de formateo que ya mandó a arreglar Agus, pero les muestra lo mismo que el [readme.md](https://github.com/sisoputnfrba/so-deploy/blob/master/README.md) del deploy practicamente. Lo importante es que pueden salir de esa pantalla con la letra 'q'.

**Comment by RaniAgus** [comment]
Ya está listo el fix, hagan un `git pull` del repo `so-deploy` y tendrán la última versión con esos detalles corregidos.

**Comment by rood8592** [comment]
Muchas gracias! Pudimos hacer funcionar el deploy en el labo.
