### ISSUE TITLE
Deadlock en Salvations edge

### ISSUE THREAD

**Issue by ManuRodri01** [sisoputnfrba/foro#4077]
Buenas, tenia una duda respecto al deadlock que debería ocurrir en el Salvations Edge.

Nuestro programa realiza bien la prueba de deadlock, pero al momento de correr el salvations edge todo corre bien pero los 4 procesos de lock no terminan en deadlock.
Revisando los logs, vemos que, al haber otros procesos en el sistema, no se da la ejecución correcta para que ocurra un deadlock; por ejemplo, el LOCK_A finaliza correctamente antes de que el LOCK_C y LOCK_D pasen de New a Ready.

Teniendo en cuenta que el sistema pasa bien la prueba de deadlock y el salvations edge parece ser una prueba para testear Memory leaks y esperas activas; es absolutamente necesario que los procesos queden en deadlock o es algo a lo que no tendríamos que darle tanta importancia?

Gracias y perdón por la pregunta tan rara.

**Comment by iago64** [comment]
Buenas! Cómo va?

Nos lo llevamos para analizarlo y seguramente hagamos algun ajuste, por el momento de esa prueba no se preocupen mucho, solo busca encontrar esperas activas y memory leaks.

Saludos.-

**Comment by ManuRodri01** [comment]
Dale, muchas gracias
