### ISSUE TITLE
Prieba Salvation's Edge y FS

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#4079]
Buenas, el config de FS está bien configurado en Salvation's Edge? Porque dice que el tipo de interfaz es STDOUT.
Y en FS dice que FS_1 crea dos archivos y escribe en ellos pero puede ser que haga dos IO_FS_WRITE sobre el mismo archivo?

**Comment by rood8592** [comment]
Y otra cosa del salvations edge. Que se espera que hagamos con la IO que pide algo por teclado? debe ingresarse apenas lo pide o dejarlo ahi colgado?

**Comment by rood8592** [comment]
Porque tuvimos el problema de que no quedaron en deadlock los procesos en salvation edge pero si lo hicieron en la prueba especial de deadlock y estamos viendo donde pudo haber fallado porque son muchas cosas las que pueden pasar. Basicamente todo lo que le de tiempo a IO_1 a ser elegido nuevamente por estar en ready+ y que IO_2 no lo pueda bloquear por estar en ready.

**Comment by iago64** [comment]
Buenas! Cómo va?

Ahi ajustamos la prueba un toque porque el objetivo era validar las esperas activas y memory leaks.

Saludos.-
