### ISSUE TITLE
Sobre ips de configs de la entrega

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#4080]
Buenas! Ya me tome el tiempo de probarlo distribuido. Mi duda es si los en los 10 minutos iniciales está incluido de setear la IP a todas las configs. O solo a las de la prueba 1 
Primero porque, salvo en entradasalida tengo un config distinto por cada prueba por cada módulo entonces es medio un laburito y además no se a ciencia cierta que interfaces voy a levantar en qué compu, entonces quizás me conviene editar ese config cuando sepa en el momento donde lo voy a levantar.

Otra pregunta es si en los módulos que están en la misma máquina (por ej kernel y CPU) puedo dejar la IP de localhost o poner la IP obtenida (lo probé y da lo mismo) esto ahorra un poco de tiempo

**Comment by f-and** [comment]
Buenas Gon! 

Si, estaria incluido setear las ips individuales, por lo tanto van a necesitar configurar cada una, para esto recomiendo buscar una manera rapida, ya sea un programa suyo o un script, que puedan usar para automatizarlo (considerando que todos los archivos de configuración son .config podrían buscar una manera de abrir todos los archivos config y modificar las lineas IP_MODULO). 

Para los módulos en sí, consideren que masomenos (considerando que tengamos las computadoras para hacerlo) se les dara una computadora por módulo (Kernel, CPU, Memoria, e Interfaces) así que van a poder configurar todo desde el momento en el que se les dan las computadoras (igual pueden configurarlo como quieran, si quieren correr ciertas interfaces en distintas computadoras no hay problema).

En cuanto a la IP de localhost, como prefieran, lo único necesario es que se conecten entre ellos los módulos.

Saludos.-

**Comment by GonTurri** [comment]
Mm me mataste con eso jaja.
Te pregunto en tu experiencia es mejor un código en c? O un script?
En el primer caso no sabría cómo compilarlo en conjunto con el tp y eso, quizás creando otro módulo.
O será el momento de invocar al gran gpt?

**Comment by iago64** [comment]
Buenas! Cómo va?

Siempre pueden invocar al gran Chat GPT para que les resuelva las dudas con algun script, igual otra opción muy linda que pueden probar es usar winscp y pasarse los archivos desde una PC con windows, entonces los editan con cualquier editor en 2 patadas (ej VSCode) y se pasan los archivos con las IPs.

Saludos.-

**Comment by GonTurri** [comment]
Buenas, no entendí nada de lo que dijiste. Me pongo a ver todas las opciones que me dijeron y cuando lo tenga más cocinado vuelvo a preguntar 
Buen finde!

**Comment by tomasmartinez02** [comment]
Buenas! Reabro el issue para agregar a lo que te dijeron los chicos antes, en so-deploy existe el archivo configure.sh que básicamente trabaja con un clave-valor agilizándote el cambio de las IP, indaga un poco pero te va a servir, te dejo el link.
[https://github.com/sisoputnfrba/so-deploy/blob/master/configure.sh](url)
Saludos!

**Comment by GonTurri** [comment]
Como va? ahi lo vi un poquito y esta bueno, despues intento probarlo bien.
Lo que si una cosa que me olvide de decir antes, es que por un tema de conveniencia de rutas, preferiria mover el tp y las commons al home porque cuando las clono en el deploy se me clonan adentro de la carpeta `so-deploy` 
Lo que si ahora viendo este configure.sh al menos para correrlo el tp tiene que estar adentro del so-deploy para que ande.
Podria, por ejemplo, ejecutar el script y despues mover los directorios? o me recomiendan por si las dudas no tocar nada?

Cuando lo probe movi tanto el tp como las commons al home (mas que nada por tema de vagancia) y para poder clonar el repo de las pruebas en home tambien

Muchas gracias por todo

**Comment by iago64** [comment]
Buenas! Cómo va?

Pueden hacer lo que les resulte más simple para levantar el TP en el menor tiempo posible.

Saludos.-
