### ISSUE TITLE
Duda sobre el retgistro PC en pruebas finales

### ISSUE THREAD

**Issue by NicoferUtn** [sisoputnfrba/foro#4081]
Hola, buenas tardes. 
Con mi grupo teniamos una duda acerca las pruebas finales. Ya que en nuestra pcb tenemos 1 program counter y en los resgistros tenemos PC como un registro independiente.   

En las pruebas "CIRCLE" la ultima instruccion es SET PC 0, no entendemos si tiene que volver a arrancar creando asi un bucle infinito o pasar a EXIT y el SET PC se tome como un registro mas. Gracias.

"Pruebas CIRCLE"
SET AX 1
SET EAX 0
RESIZE 64
MOV_OUT EAX AX
MOV_IN BX EAX
SUM EAX AX
MOV_OUT EAX BX
MOV_IN CX EAX
SUM EAX AX
MOV_OUT EAX CX
MOV_IN DX EAX
SUM EAX AX
MOV_OUT EAX DX
MOV_IN AX EAX
RESIZE 0
SET PC 0
EXIT

**Comment by NicoferUtn** [comment]
Gracias por responder. Solo para que quede claro,  entraria en un bucle, no? Entonces tendriamos un Program Counter demas? Si es asi cual utilizariamos el de los registros o el de la PCB ??

**Comment by RaniAgus** [comment]
El Program Counter es un registro de la CPU, es uno solo y siempre se usa el mismo.

**Comment by NicoferUtn** [comment]
Dale mil gracias agus !!
