### ISSUE TITLE
INICIAR_PROCESO para las pruebas

### ISSUE THREAD

**Issue by tomipodo** [sisoputnfrba/foro#4083]
Buenas, cómo andan?
Tenemos una breve consulta acerca de la instrucción INICIAR_PROCESO.
En las pruebas vemos que los comando se ejecutan de esta manera:
INICIAR_PROCESO /scripts_memoria/[path]
Nosotros siempre lo ejecutamos sin el '/' que está antes de scripts_memoria, ya que hacemos el fopen directamente. Con nuestra implementación las pruebas no funcionarían, entonces para probar, le sacamos el '/'. 
Debemos hacer que funcione tal cual está en las pruebas? 
Saludos, gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Si es solo ese temita del caracter / no se preocupen, pueden hacer esa pequeña modificación en los scripts de manera local.

Saludos.-

**Comment by tomipodo** [comment]
Buenisimo, muchas gracias
