### ISSUE TITLE
Duda orden compactacion

### ISSUE THREAD

**Issue by FeliFemenia** [sisoputnfrba/foro#4084]
Buenas, tengo algunas duda sobre la compactacion que hay que hacer en el FS.
1- Cuando hay que truncar un archivo y no tiene la cantidad de bloques necesarios contiguos, nosotros lo que hacemos es buscar si en algun otro lado del FS hay esa cantidad de bloques de manera contigua (la cant de bloques que ya tenia el archivo + los nuevos bloques). Eso estaria bien? o ya una vez que detecto que no tiene bloques contiguos tendria que compactar?
2- Cuando hago la compactacion hay algun orden en que tienen que quedar los archivos? porque nosotros ahora mismo agarramos el primer fcb de la lista que tenemos y lo pasamos adelante de todo, despues agarramos el otro fcb y lo ponemos atras del anterior y asi sucesivamente y dejando en ultimo lugar al fcb que tenemos que truncar. Tendrian que quedar los archivos de tamaños mas chico adelante y despues los de tamaño mas grande?

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- La estrategia que planteas es válida, pero aun así tienen que hacer el retardo de compactación.

2.- Ningún problema mientras uds puedan después encontrar los archivos no hay problema alguno en como queden.

Saludos.-

**Comment by FeliFemenia** [comment]
Ok buenisimo. Una consulta. El valor del puntero archivo, seria por ejemplo el byte numero 1000 del archivo que haya que escribir o leer no? no un puntero archivo del archivo de bloques. Osea me refiero a que el puntero archivo no va a ser el byte 1000 del archivo bloques.dat, sino que es el byte 1000 del archivo notas.txt por ejemplo, que podria ser el byte 3000 del archivo bloques.dat.

**Comment by RaniAgus** [comment]
¡Buenas! Es correcto. Saludos
