### ISSUE TITLE
Duda sobre prueba de FS_1

### ISSUE THREAD

**Issue by lewislee0920** [sisoputnfrba/foro#4085]
Buenas, estube probando las pruebas de FS, pero para hacer la prueba FS_1 tenia que conectar con FS.config y ademas de eso con el teclado.config tambien por la instruccion de IO_STDIN_READ TECLADO CX EAX. Mi duda es, como conectar con los dos configs para la prueba? O existe algun otro manera para resolver este problema?

FS_1:

SET AX 10
SET BX 80
IO_FS_CREATE FS salida.txt
IO_FS_CREATE FS cronologico.txt
IO_FS_TRUNCATE FS salida.txt BX
IO_FS_TRUNCATE FS cronologico.txt BX
RESIZE 160
SET CX 0
SET DX 9
SET EAX 69
IO_STDIN_READ TECLADO CX EAX
MOV_OUT DX AX
SET DX 19
MOV_OUT DX AX
SET DX 29
MOV_OUT DX AX
SET DX 48
MOV_OUT DX AX
SET DX 58
MOV_OUT DX AX
IO_FS_WRITE FS salida.txt CX EAX CX
SET SI 59
SET DI 80
COPY_STRING 10
SET BX 90
MOV_OUT BX AX
SET SI 0
SET DI 91
COPY_STRING 59
SET ECX 80
IO_FS_WRITE FS cronologico.txt ECX EAX CX
EXIT

**Comment by lewislee0920** [comment]
Vi los otros issues pero no entendi bien como solucionar la prueba de conexion multiples

**Comment by RaniAgus** [comment]
¡Buenas! No entendí la duda, `FS` y `TECLADO` son dos instancias distintas de entrada salida, ambas con distintos archivos de configuración, ¿por qué querrías usar dos configs a la vez? Saludos

**Comment by lewislee0920** [comment]
Osea, no sera que tenemos que conectar con el teclado.config para correr la instruccion de IO_STDIN_READ TECLADO CX EAX?

**Comment by RaniAgus** [comment]
Las dos instancias de entrada salida ya deberían estar iniciadas y conectadas antes de correr la prueba.

**Comment by lewislee0920** [comment]
Tenemos que conectar con el FS.codale muchas graciasnfig
