### ISSUE TITLE
Consumir unidad de tiempo en FS

### ISSUE THREAD

**Issue by EstebanHurtado0** [sisoputnfrba/foro#4088]
Buenas, sabemos que ante cada petición de FS tenemos que consumir una unidad de tiempo de trabajo, nosotros esto lo hacemos con usleep(), pero puede hacerse con sleep() que solucion seria la correcta?

**Comment by iago64** [comment]
Buenas! Cómo va?

Lo tienen que hacer con `usleep()` que usa microsegundos ya que `sleep()` lo hace en segundos.

Saludos.-
