### ISSUE TITLE
TIEMPO_UNIDAD_TRABAJO en STD

### ISSUE THREAD

**Issue by FelipeRuizDiaz** [sisoputnfrba/foro#4089]
Hola buenas noches! 

Una pregunta: ¿Hace falta tener el TIEMPO_UNIDAD_TRABAJO para los STD? En el enunciado del TP no indica que tengamos que hacer nada con ellos.

### 📔 Citas del enunciado del TP

Interfaces STDIN
--
Las interfaces STDIN no van a esperar ninguna unidad de trabajo, ya que las mismas van a quedarse esperando que el alumno ingrese un texto por teclado. 

Al leer el archivo de configuración solo le van a importar las propiedades de:
TIPO_INTERFAZ
IP_KERNEL
PUERTO_KERNEL
IP_MEMORIA
PUERTO_MEMORIA

Interfaces STDOUT
--
Al leer el archivo de configuración solo le van a importar las propiedades de:
TIPO_INTERFAZ
IP_KERNEL
PUERTO_KERNEL
IP_MEMORIA
PUERTO_MEMORIA

### 📔 Citas del documento de pruebas

MONITOR.config
--
TIPO_INTERFAZ=STDOUT
TIEMPO_UNIDAD_TRABAJO=50

TECLADO.config
--
TIPO_INTERFAZ=STDIN
TIEMPO_UNIDAD_TRABAJO=250

**Comment by f-and** [comment]
Buenas, si, no es necesario.

**Comment by FelipeRuizDiaz** [comment]
Perfecto, gracias!
