### ISSUE TITLE
Possibly lost valgrind

### ISSUE THREAD

**Issue by Barlita03** [sisoputnfrba/foro#4090]
Hola, como estan ? Al ejecutar el codigo con valgrind me esta marcando el siguente possibly lost:

2,304 bytes in 1 blocks are possibly lost in loss record 108 of 134
==14519==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==14519==    by 0x4005D97: malloc (rtld-malloc.h:56)
==14519==    by 0x4005D97: _dlfo_mappings_segment_allocate (dl-find_object.c:217)
==14519==    by 0x4005D97: _dl_find_object_update_1 (dl-find_object.c:671)
==14519==    by 0x4005D97: _dl_find_object_update (dl-find_object.c:804)
==14519==    by 0x400ECCF: dl_open_worker_begin (dl-open.c:735)
==14519==    by 0x4B2BA97: _dl_catch_exception (dl-error-skeleton.c:208)
==14519==    by 0x400DF99: dl_open_worker (dl-open.c:782)
==14519==    by 0x4B2BA97: _dl_catch_exception (dl-error-skeleton.c:208)
==14519==    by 0x400E34D: _dl_open (dl-open.c:883)
==14519==    by 0x4B2BE00: do_dlopen (dl-libc.c:95)
==14519==    by 0x4B2BA97: _dl_catch_exception (dl-error-skeleton.c:208)
==14519==    by 0x4B2BB62: _dl_catch_error (dl-error-skeleton.c:227)
==14519==    by 0x4B2BF36: dlerror_run (dl-libc.c:45)
==14519==    by 0x4B2BF36: __libc_dlopen_mode (dl-libc.c:162)
==14519==    by 0x4ADC610: __libc_unwind_link_get (unwind-link.c:50)
==14519==    by 0x4ADC610: __libc_unwind_link_get (unwind-link.c:40)

Es muchisima memoria y no se donde ni por que esta siendo ocacionado, si alguien entiende que quiere decir se agradece la ayuda.

**Comment by iago64** [comment]
Buenas! Cómo va?

A priori te puedo pedir que subas todo el output de valgrind en un archivo?
Porque con este poco contexto se nos complica un monton adivinar de por donde puede venir el origen.

Saludos.-

**Comment by Barlita03** [comment]
Dale, aca te lo adjunto.
[valgrind.log](https://github.com/user-attachments/files/16122217/valgrind.log)

**Comment by iago64** [comment]
Buenas! Cómo va?

Ahora con el log completo te puedo dar una explicación mas completa :)
Los possibliy lost quiere decir que como vos cortaste abruptamente con Ctrl + C (SIGINT) tenias reservadas cosas que "capaz se perdian" eso por ejemplo si te fijas es memoria administrativa que uso pthread al momento de crear los hilos, esto lo ves en el siguiente fragmento:

```
==26173==    by 0x4A4C7B4: allocate_stack (allocatestack.c:430)
==26173==    by 0x4A4C7B4: pthread_create@@GLIBC_2.34 (pthread_create.c:647)
==26173==    by 0x10E520: crearHiloPlanificador (inicioYFin.c:178)
==26173==    by 0x10ACB8: main (main.c:41)
```

Dicho lo anterior, no te preocupes, por eso no es lo grave de los Memory Leaks si no por el contrario lo que importa es que no tengas definitely lost ni indirectly lost.

Saludos.-

**Comment by Barlita03** [comment]
Uhhh joya, muchisimas gracias.
