### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#4091]
Buenas, tengo dos dudas con respecto a los logs:

1- Cuando fuimos al laboratorio y probamos el TP con 3 maquinas a veces los logs no se imprimian hasta que le dabamos un enter a la consola de powershell. Esto pasaba tanto si imprimiamos los logs en la consola, como si no lo haciamos y los veiamos en tiempo real directo desde el archivo con tail o less. Eso es normal que suceda?
2-En CPU tenemos dos archivos de logs, uno tiene los obligatorios y otro los nuestros. Sin embargo, pusimos que los dos se impriman en consola por lo que se mezclan igual. Igualmente no tenemos muchos logs propios más alla de la conexión inicial ¿Lo dejamos así o los vemos en consolas separadas con tail? ¿O dejamos que solo el obligatorio imprima por consola y otro lo vemos con tail o less?

**Comment by f-and** [comment]
Buenas
1. No seria normal, pero a su vez puede ser un quirk de usar powershell, deberían poder usar Putty en la entrega que no debería tener ese Issue (igual por si las dudas prueben en una máquina distinta usar tanto powershell como Putty para ver si ocurre por la computadora, el programa, o el TP), igual no seria problema ya que si se va registrando con los timestamps correctos vamos a poder verificar bien las pruebas.
2. Para esto, les recomendaría personalmente pasar todo lo de su Log propio al Log principal con código LOG_LEVEL_DEBUG o LOG_LEVEL_TRACE así a la hora de llevarlo a la entrega (considerando que lo tienen todo listo) pueden simplemente cambiar el nivel de loggeo y se obviarían todos los loggeos que hicieron ustedes. Pero no debería haber problema tampoco, con un tail o less como dicen bastaría.

**Comment by rood8592** [comment]
Ok, quedo claro el punto 2. Con respecto al punto 1 nos pasaba en dos maquinas distintas del labo rojo, putty no pudimos usar porque muchas no lo tienen instalado, intentamos buscar el portable pero no lo encontramos y por eso en otro issue nos habian recomendado usar powershell y ssh. Esto no nos pasó nunca cuando lo probabamos local con la VM con interfaz y consola de linux. 
Igualmente las pruebas funcionaron, si veiamos que faltaban imprimir algunos logs, le dabamos enter y salian pero más alla de eso no pasaba otra cosa.

**Comment by rood8592** [comment]
Agrego otra pregunta: ¿en la entrega final usaremos putty o podemos usar powershell? Pregunto porque algunas maquinas del labo no reconocen el ssh y no se puede instalar a menos que seas administrador. Además, el despliegue lo practicamos con powershell en el labo. De última, si en la entrega final es si o si con putty probaremos usar ese programa.

**Comment by iago64** [comment]
Buenas! Cómo va?

Las pruebas van a ser con putty que no necesariamente tienen que instalarlo, tiene una version portable.

Saludos.-

**Comment by f-and** [comment]
Para responder a lo primero: Prueben si pueden levantar la VM sin interfaz gráfica, y conectense desde Putty, a ver si ocurre el mismo error. De paso, la versión portable de Putty la pueden hallar [acá](https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html) en la sección de "Alternative binary files". 

Para lo segundo, van a usar Putty, antes de las entregas nos encargamos de preparar las máquinas para que tengan todo lo necesario, si en alguna llega a faltar les vamos a dar soporte en el momento. El Powershell se los recomendamos como una medida provisoria ya que es la misma idea (conectarse a una VM virtual desde una máquina física).

**Comment by RaniAgus** [comment]
Sí, y de hecho también pueden duplicar la sesión haciendo click derecho en la barra superior de la ventana: 
![image](https://github.com/sisoputnfrba/foro/assets/39303639/04b74328-dfa9-449a-9dee-c5ad181ecab4)
