### ISSUE TITLE
Posible falta de memoria para ejecutar "Prueba Salvation's Edge"

### ISSUE THREAD

**Issue by htravado** [sisoputnfrba/foro#4092]
Según se detalla en la guía de pruebas el modulo de memoria debería tener la siguiente asignación:

```
TAM_MEMORIA=1024
TAM_PAGINA=32
RETARDO_RESPUESTA=100
```

Lo que nos resulta en 32 frames totales. 
Dado que habría 30 procesos ejecutando y algunos necesitan mas de un frame es imposible ejecutar todos al mismo tiempo provocando que se cierren por "OUT_OF_MEMORY"

El problema se soluciona asignando mas memoria, en mi caso, con 2048 bytes fue suficiente para que ejecutaran simultáneamente todos los procesos.

**Comment by iago64** [comment]
Buenas! Cómo va?

Transferí el issue del repo de las pruebas al repo general para que a todos les lleguen los mensajes por si las dudas.
Si, la prueba queda corta de memoria no hay problema, total con 15 procesos ya nos alcanza para validar las esperas activas y memory leaks o si gustan pueden ampliar la memoria al doble o el triple para mas concurrencia.

Saludos.-

**Comment by htravado** [comment]
Excelente, yo fui por agrandar la memoria, me gusta la adrenalina jajajaj.
Saludos!
