### ISSUE TITLE
Posible bug en script PIRAMID y CUBE

### ISSUE THREAD

**Issue by htravado** [sisoputnfrba/foro#4093]
Al comienzo de los script se setea el registro BX y EBX en 0 por lo que se asume que ambos deberían marcar el comienzo de la cadena.
Pero antes de escribir el primer caracter de la cadena se incrementa el registro BX por lo que el primer caracter de la cadena lo escribe en la dirección lógica 1. Al final de script ejecuta la instrucción `IO_STDOUT_WRITE MONITOR EBX DX` por lo que el primer caracter de la cadena esta apuntando a un caracter con contenido indeterminado.

Una posible solución seria eliminar el incremento del registro BX en la linea 7 de ambos scripts para que la cadena se comience a escribir desde la dirección lógica 0.

[Linea 7 PIRAMID](https://github.com/sisoputnfrba/c-comenta-pruebas/blob/04df66f167aac027a4749ab645f78226d7a7f752/scripts_memoria/PIRAMID#L7)

[Linea 7 CUBE](https://github.com/sisoputnfrba/c-comenta-pruebas/blob/04df66f167aac027a4749ab645f78226d7a7f752/scripts_memoria/CUBE#L7)

**Comment by iago64** [comment]
Buenas! Cómo va?

Transferí el issue del repo de las pruebas al repo general para que a todos les lleguen los mensajes por si las dudas.
Si, es verdad, nos quedo un incremento de mas, es el problema de completar con una regex, gracias por el aviso.

Saludos.-

**Comment by htravado** [comment]
Excelente! Cierro el issue entonces.. Gracias a vos!
