### ISSUE TITLE
Duda log obligatorio en la memoria "Acceso a espacio de Usuario"

### ISSUE THREAD

**Issue by ArielRotolo** [sisoputnfrba/foro#4095]
Buenas, revisando los logs obligatorios de la Memoria me surgió una duda, según la instrucción "Acceso a espacio de usuario" la petición puede ser recibida tanto por una interfaz IO como por la CPU, según interpreté esta instrucción no tiene asociada un pid de un proceso ya que a la memoria realmente no le importa si un proceso o que cosa le pide acceso para leer o escribir al espacio de usuario, menos en el caso de una interfaz como stdin o stdout, pero según el enunciado el log obligatorio de esta instrucción es:

**Acceso a espacio de usuario: “PID: <PID> - Accion: <LEER / ESCRIBIR> - Direccion fisica: <DIRECCION_FISICA>” - Tamaño <TAMAÑO A LEER / ESCRIBIR>**

Donde uno de los parámetros a loggear es el pid del proceso, esta bien esto? Que pid logueo si recibo una escritura/lectura de STDIN o STDOUT que en el enunciado de las IO nunca indican que reciben el PID de un proceso desde el Kernel.

**Comment by f-and** [comment]
En realidad ☝️ 🤓 , si necesitan el PID, ya que uno de los logs obligatorios de I/O es justamente:

> “PID: <PID> - Operacion: <OPERACION_A_REALIZAR>”

Por lo tanto vas a requerir que el Kernel le pase el PID a la interfaz (además, dependiendo de como manejes la interacción entre Kernel e Interfaz te puede servir tener el PID para saber que proceso desbloqueas).

**Comment by ArielRotolo** [comment]
Buenas! Uhh 🤦 se me pasó eso.

Muchas gracias por la ayuda!
