### ISSUE TITLE
Duda sobre nombre de Interfaces

### ISSUE THREAD

**Issue by mamusante** [sisoputnfrba/foro#4097]
Hola, no llego a entender lo de los nombres de las interfaces. Los nombres seran Int2, Int2 y asi? Y en caso de ser asi, cuando una interfaz se conecta a kernel le tiene que decir su nombre y tipo de interfaz o solo el tipo de interfaz y el nombre se lo asigna el kernel arrancando con Int1, Int2, etc a medida q se van conectando?

**Comment by mefederico** [comment]
Hola buenas!

El nombre de la interfaz se ingresa al iniciar la interfaz como parámetro de main. Si, la interfaz tiene que comunicar su nombre al kernel.

Si miran el [documento de las pruebas](https://docs.google.com/document/d/1XsBsJynoN5A9PTsTEaZsj0q3zsEtcnLgdAHOQ4f_4-g/edit) en la aclaración están los nombres que tienen que asignar

> En las configuraciones de las Interfaces el nombre de la interfaz es el nombre del archivo .config de la misma, es decir, si el config se llama IO_1.config el nombre de la interfaz deberá ser IO_1

Saludos!
