### ISSUE TITLE
Algunas dudas del FS

### ISSUE THREAD

**Issue by ElielBejar** [sisoputnfrba/foro#4098]
Buenas! Tengo unas dudas sobre la interfaz IO que me quedaron. 
1) El path base donde van a estar los archivos tiene que existir previamente o si no existe lo tengo que crear? Por ejemplo si cuando leo del config: PATH_BASE_DIALFS=/home/utnso/dialfs y ese directorio no existe, lo tengo que crear dentro del código del módulo de IO? o tengo que asumir que ya va a venir creado.
2)  En caso de que quiera expandir un archivo y no haya tamaño disponible en el FS incluso aunque compacte, le debería avisar a kernel o a memoria sobre que no se pudo truncar? 
3) Lo mismo con IO_FS_WRITE  e IO_FS_READ. Si se quiere escribir el archivo pero se pasa del tamaño asignado al archivo o si quiero leer el archivo y me paso del tamaño asignado, tengo que avisarle a kernel o a memoria? como un OUT_OF_MEMORY pero para el FS

Desde ya gracias!

**Comment by mefederico** [comment]
Hola buenas!

1. Lo pueden crear a mano con comandos y no tener que validar desde el programa.
2. No vamos a probar ese caso, si quieren tener un chequeo pueden simplemente loggear el error para ver si algo de su código o las pruebas está mal.
3. Misma respuesta, no vamos a probar ese caso, si quieren poner el chequeo por si algo se está ejecutando mal/está mal la prueba poder detectarlo fácilmente, adelante.

Saludos!

**Comment by ElielBejar** [comment]
Buenísimo gracias!!
