### ISSUE TITLE
Consulta detección deadlock

### ISSUE THREAD

**Issue by AgustinaGuitman** [sisoputnfrba/foro#4099]
Buenas, estamos viendo las pruebas y nos surgió una duda: ¿la detección de deadlock en los archivos debería hacerla kernel o interfaz? Nos suena que kernel es quien debería ser responsable de la detección de los deadlocks pero interfaz es quien trabaja con los archivos y tiene un mayor control de lo que va pasando. 

Desde ya muchas gracias.

**Comment by GorinoManuel** [comment]
Hola, no soy ayudante, pero si te fijas la idea de las pruebas es que se queden en deadlock y finalices algún proceso con el comando FINALIZAR_PROCESO <PID>

**Comment by mefederico** [comment]
Hola buenas! 

Exactamente como comenta @GorinoManuel, en este TP no hay detección de deadlock automática, es algo que vamos a observar con los logs y una vez confirmamos el caso queremos poder eliminar algún proceso implicado en el deadlock y que el mismo se libere.

Saludos!

**Comment by AgustinaGuitman** [comment]
Hola, muchas gracias! Osea que cada vez que haya un pedido de recursos o archivos tenemos que llamar a una función que haga un chequeo y vea si hay alguno que esta en deadlock, si hay lo único que hacemos es un log que diga que hay deadlock, no?

**Comment by mefederico** [comment]
Hola, no. Ustedes no tienen que hacer nada con los deadlocks, los ayudantes nos vamos a dar cuenta con el comando "PROCESO_ESTADO" y viendo que efectivamente no están yendo a la CPU por estar en deadlock

**Comment by AgustinaGuitman** [comment]
Perfecto, muchísimas gracias. 
Saludos
