### ISSUE TITLE
Proceso en Manejo de Interfaces

### ISSUE THREAD

**Issue by milagrosvera** [sisoputnfrba/foro#4100]
Buenas, estamos terminando de resolver lo de manejo de interfaces en kernel y tenemos una duda cuando recibimos la notificación para desbloquear al proceso, como sabemos que proceso sacar de la lista de bloqueados, dado que cuando solicitamos la operación a interfaz sólo mandamos los parámetros necesarios (no hay información sobre el pcb).

Desde ya muchas gracias.

### 📔 Citas del enunciado/videos

De cumplirse todos los requisitos anteriores, el Kernel enviará el proceso al estado BLOCKED y a partir de este punto pueden darse 2 situaciones:
El caso en el que la interfaz de I/O esté libre: En este caso el Kernel deberá solicitar la operación al dispositivo correspondiente. 
En el caso de que exista algún proceso haciendo uso de la Interfaz de I/O, el proceso que acaba de solicitar la operación de I/O deberá esperar la finalización del anterior antes de poder hacer uso de la misma.
Una vez la operación finalice, **el Kernel recibirá una notificación y desbloqueará dicho proceso para que esté listo para continuar con su ejecución** cuando le toque según el algoritmo.

**Comment by mefederico** [comment]
Hola buenas!

Tienen que desbloquear el proceso que realizó la petición a la interfaz, recordando que la interfaz solo puede procesar de a un proceso por vez.

Como implementar esto?
Bueno hay múltiples formas de hacerlo, definan cual les parece más fácil/conveniente de aplicar

Si tienen una cola por interfaz, simplemente seria quitar el siguiente elemento de la cola por ejemplo, pero esto depende de la implementación propia de cada equipo

Saludos!

**Comment by f-and** [comment]
Buenas!
Me meto solo para agregar que también es parte de la info necesaria el PID, ya que [uno de los logs obligatorios lo requiere](https://github.com/sisoputnfrba/foro/issues/4095#issuecomment-2213151342), por lo que pueden usar eso para saber que proceso desbloquear.
Saludos.-

**Comment by mefederico** [comment]
Ojo no es por tipo de interfaz que puede procesar de a una, sino por interfaz, es decir el nombre único

**Comment by milagrosvera** [comment]
Perfecto, ahí creo que lo resolvimos.Muchas gracias!
