### ISSUE TITLE
Duda sobre log de kernel llegada a cola Ready/Ready plus

### ISSUE THREAD

**Issue by GorinoManuel** [sisoputnfrba/foro#4101]
Hola, tengo una duda sobre el log que cito, ya que por el momento ese log lo hacemos mostrando los pids pero no en el orden en el cual están en la cola. Esto es, si están en ready 1,2,3 y está 3 al principio de la cola muestra:
Cola Ready: 1, 2, 3,

Mi duda es si esto está bien o si debemos modificarlo.
### 📔 Citas del enunciado/videos
Cola Ready / Ready Prioridad: [<LISTA DE PIDS>]

**Comment by mefederico** [comment]
Hola buenas! 

Me genera más curiosidad como hicieron para que no les muestre el orden de la cola, lo ideal es que se muestre en orden porque va a permitir saber que es lo que está pasando fehacientemente con el sistema. Así que si lo pueden hacer que muestre el orden estaría bueno

Saludos!

**Comment by GorinoManuel** [comment]
Bueno, ahí ya lo arreglamos para que se vea bien. Cierro el issue.
