### ISSUE TITLE
Prueba FS: problema con el tamaño máximo de un texto

### ISSUE THREAD

**Issue by DamianBlum** [sisoputnfrba/foro#4102]
mi problema surgió en el caso que me pasen un texto por el teclado con el tamaño máximo, ya que en la prueba de FS se me corto en "Fallout 7"
¿En la Memoria Ram, tiene que ir el \0?¿Es parte de un char* o es algo que no formo y solo tomo los caracteres del mismo?

**Comment by mefederico** [comment]
Hola buenas! 

No tienen que tomar en cuenta el \0, solamente lo tienen que agregar a la hora de intentar mostrar un dato por STDOUT, pero no lo tienen que guardar.

Saludos!

**Comment by DamianBlum** [comment]
Dale, muchas gracias
