### ISSUE TITLE
Se cambia el archivo

### ISSUE THREAD

**Issue by FeliFemenia** [sisoputnfrba/foro#4103]
Buenas, una consulta. Cuando creo el archivo bitmap.dat y lo mapeo a memoria, le quiero copiar el bitmap que uso del tipo t_bitarray, nose porque como que se me rompe el archivo.  Estamos mapeando el archivo a memoria y luego en la funcion sincronizar_bitmap lo unico que hacemos es hacerle un memsync para que se guarde el contenido que tiene en memoria mapeada el archivo. Porque puede ser que se me este rompiendo al hacer el memcpy?

```
void crear_bit_map(){

    tamanio_bit_map = block_count / 8;
    void* bits = malloc(tamanio_bit_map);

    bit_map = bitarray_create_with_mode(bits, tamanio_bit_map, LSB_FIRST);

    char* path = string_new();
    string_append(&path, path_base_dialfs);
    string_append(&path, "bitmap.dat"); 

    bool ya_creado = true;

    if(!file_exists_in_directory(path_base_dialfs, "bitmap.dat")){
        FILE* archivo_bitmap = fopen(path, "wb");
        fclose(archivo_bitmap);

        for(int i=0; i < block_count; i++){//Empiezan en FALSE todos
            bitarray_clean_bit(bit_map,i);  //False = Libre(clean), True = Ocupado(setted)
        }

        ya_creado = false;
    }

   fd_bit_map = open("/home/utnso/dialfs/bitmap.dat", O_RDWR, S_IRUSR | S_IWUSR);//Se supone q el archivo ya existe, sino da error

    if (fd_bit_map == -1) {
        perror("Error al abrir o crear el archivo");
        terminar_ENTRADASALIDA();
        exit(EXIT_FAILURE);
    }

    if (ftruncate(fd_bit_map, tamanio_bit_map) == -1) {
        perror("Error al truncar el archivo");
        close(fd_bit_map);
        terminar_ENTRADASALIDA();
        exit(EXIT_FAILURE);
    }

     t_bitarray*  fs = mmap(NULL, tamanio_bit_map, PROT_READ | PROT_WRITE, MAP_SHARED, fd_bit_map, 0);
    if (fs == MAP_FAILED) {
        perror("Error en mmap");
        close(fd_bit_map);
        terminar_ENTRADASALIDA();
        exit(EXIT_FAILURE);
    }
    
     if(ya_creado){
         memcpy(bit_map, fs, tamanio_bit_map);
     }else{
         memcpy(fs, bit_map, tamanio_bit_map);
         sincronizar_bitmap();
     }
}
```

**Comment by f-and** [comment]
Buenas!

Fijate que el memcpy en sí está copiando una parte cortada del bit_map, ya que, el bit_map es un t_bitarray que tiene más que los bits. 

Y para saber, porqué estas manteniendo una versión duplicada del bit_map en fs? Con asignarle un mmap a la variable bits debería ser suficiente, total la instancia del bitarray la podes levantar en cada corrida, lo único que requiere persistencia son los bits. 

Además, y esto es una consulta de molesto, vi que en una versión anterior el fd_bit_map estaba definido como un t_bitarray, esto lo cambiaron en el código? Porque en realidad, el open retorna un int, por lo que les puede generar líos considerarlo un puntero y encima un puntero de otro tipo que no es el filedes.

Por ultimo, para futuras consultas, fíjense que si ponen el nombre del lenguaje al principio del code snippet les pone mejor el código, así no nos hacemos lio leyendo código a la Noir.

Así:
\`\`\`c
\*código\*
\`\`\`

Saludos.-

**Comment by FeliFemenia** [comment]
Buenas. 
1- Hace un rato lo hice andar pero solo guardando en el archivo bitmap.dat el bitarray del bitmap. Tendria que guardar toda la estructura en el archivo no?
2- No entiendo a que te referis con lo de mantener una version duplicada del bit_map? yo lo que hago cada vez que creo levanto una instacia del fs, es crear una bitarray para ver que bloques estan libres y cuales ocupados (por ahi lo estoy haciendo mal jaja). 
3- Sisi justo lo cambie por eso, porque me di cuenta que no era esa la variable que tenia ese tipo. 

Disculpas por no poner el codigo en c asi se hacia mas facil la lectura.

**Comment by f-and** [comment]
1. No es necesario guardar toda la estructura, ya que en sí, la estructura solo el bitmap y unos datos informativos que, o son los predeterminados (como indicar si es LSB o MSB), o son datos que ya cargas de otro lado, como el tamaño, pero si se te hace más fácil, seria hacer el memcpy que haces pero en vez de usar tamanio_bitmap usarías el tamaño del struct y appendearias el bitarray.

2. Por duplicado me refiero a que justamente, el chequeo (ya_creado) en sí es redundante, ya que crees el bitarray o lo cargues, vas a tener los bits ya preparados en la variable a la que asignes el bitmap.

y no hay problema con lo del código, es solo informativo ;)

**Comment by FeliFemenia** [comment]
Ah bueno, veo de implementarlo asi con toda la estructura entonces. Y lo de ya creado ahora entendi a lo que ibas jaja. Tenes razon. Muchas gracias!
