### ISSUE TITLE
Liberación de recursos - Memory leaks

### ISSUE THREAD

**Issue by LucianoKremer** [sisoputnfrba/foro#4107]
Hola! Buenas tardes, estábamos pasando valgrind y solucionando memory leaks, el tema es que queremos liberar las listas, pero no sabemos que seria "element_destroyer", probamos con un par de opciones, pero no sabemos como liberar la lista y sus elementos sin que explote todo jeje. Como seria?

Saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

El `element_destroyer` es una función que sabe como liberar el elemento de la lista y que recibe como parámetro un puntero a ese tipo de dato, igual eso lo pueden ver en los tests de las commons como para darse una idea.

Saludos.-
