### ISSUE TITLE
Duda Detener Planificacion

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#4108]
> Detener planificación: El proceso que se encuentra en ejecución NO es desalojado, pero una vez que salga de EXEC se va a pausar el manejo de su motivo de desalojo. 
> Nomenclatura: DETENER_PLANIFICACION

Hola tengo una duda de esta parte de la consigna, en mi caso cuando un proceso vuelve a kernel desde cpu por un desalojo entra por un switch y ahi se deserealiza el mensaje y se imprime el motivo. Pero si la planificacion se detiene, entonces se queda trabado al principio del switch y solo se imprime que llego un proceso a kernel pero el motivo no se llega a imprimir por  lo que dije antes. Esto pasa porque una vez que lo cargamos en el nuevo estado se imprime el cambio de estado y el motivo por el que llego (lo hice asi para que quede mas ordenado), entonces  como el semaforo lo corta al inicio no se podria ver el motivo porque la planificacion esta detenida. Pero cuando se reanude, lo primero que se veria seria el motivo y el cambio de estado. Esto estaria bien? Desde ya gracias

**Comment by f-and** [comment]
@JoaquinCoaricona, para saber les sirvió la respuesta? Así cerramos el issue.
