### ISSUE TITLE
Manejo de recursos

### ISSUE THREAD

**Issue by BorquezBelli** [sisoputnfrba/foro#4109]
Hola, en la parte de manejo de recursos, independientemente de si se lee WAIT/SIGNAL, como en el enunciado dice "_desalojado por..._", yo debo de bloquear ese proceso, modificar la instancia y desbloquearlo?
Me surge la duda porque si lo bloqueo, se mete otro proceso a EXEC y cuando modifique la instancia me queda en READY, pero tiene que esperar a que termine de ejecutar el nuevo proceso que se metió, esta bien planteado así?

### 📔 Citas del enunciado
"A la hora de recibir de la CPU un Contexto de Ejecución **desalojado** por WAIT..."
"A la hora de recibir de la CPU un Contexto de Ejecución **desalojado** por SIGNAL..."

### 💭 Soluciones posibles
Por las dudas trato de detallarlo un poco mas
RC=1, RA=1

Proceso 0
WAIT RC
WAIT RA
...
EXIT

Proceso 1
...

Paso a paso:
1. P0 va EXEC
2. hace WAIT RC
3. lo mando BLOCK
4. se mete P1 en EXEC, mientras resto RC del P0
5. termina P1
6. sigue P0 con WAIT RA
7. ...

Asi estaria bien? Lo que me hace ruido es tener que bloquearlo para modificar el recurso, pero es como lo interpreto del enunciado

O deberia tener que hacer
1. P0 en EXEC
2. hace WAIT RC
3. sigue hasta hacer EXIT
4. entra P1 a EXEC

**Comment by f-and** [comment]
Buenas Borquez!

Citando el enunciado:

> En caso de que el número [de instancias] sea estrictamente menor a 0, el proceso que realizó WAIT se bloqueará en la cola de bloqueados correspondiente al recurso.

> Una vez [procesado el SIGNAL], se devuelve la ejecución al proceso que peticiona el SIGNAL.

Por lo que, por un lado, el proceso no pasa a estar bloqueado en SIGNAL, y en WAIT solo pasa a estar bloqueado luego de que se haya verificado que existe el recurso y no hay instancias.

En el ínterin, el proceso técnicamente esta aún en EXEC, ya que aun no se sabe si se va a bloquear o no.

**Comment by BorquezBelli** [comment]
Ok, muchas gracias ya me quedo claro!
