### ISSUE TITLE
Aclaracion

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#4110]
> Aclaraciones
> Ir ejecutando los comandos que el ayudante evaluador indique.
> A intervalos regulares ejecutar los siguientes comandos en la consola del Kernel
> DETENER_PLANIFICACION
> PROCESO_ESTADO
> INICIAR_PLANIFICACION

Buenas, una pregunta. Aca en la prueba de Salvations Edge dice que el ayudante nos va a decir que vayamos ejecutando algunos comandos. Queria preguntar que comandos nos podria pedir? Pregunto para poder probarlo y ver que no falle nada. 

Pense que podrian ser los de abajo pero como estan en otro punto quizas no se refieren a esos.

**Comment by f-and** [comment]
Buenas!
Además de los comandos que tienen en Kernel, vamos a fijarnos con algunos comandos de Linux, como htop, como esta corriendo cada módulo para verificar que no haya ningún memory leak o espera activa!
Saludos.-

**Comment by JoaquinCoaricona** [comment]
Ahhh ok. Una pregunta, como podria verificar las esperas activas? Los memory leaks si,pero las esperas activas no se como detectarlas

**Comment by f-and** [comment]
Y, es como lo vieron en la teoría, una espera activa es una espera que ejecuta instrucciones "basura" (como un `while(1)`) mientras espera, por lo que el CPU estaría quemando ciclos al ejecutar esta espera, lo veríamos como un uso elevado del CPU por parte del proceso.

**Comment by JoaquinCoaricona** [comment]
Claro me referia a como detectarlas,  osea quee tendria que buscar algun comando para ver el uso de CPU?

**Comment by f-and** [comment]
Con htop ya te podes fijar que onda, es como el Task Manager de Windows masomenos

**Comment by JoaquinCoaricona** [comment]
Gracias
