### ISSUE TITLE
Duda Prueba 

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#4111]
Hola buenas tengo una pregunta en la prueba de Salvations Edge.

> Esperar a que finalicen todos los procesos salvo aquellos que están en un loop infinito.

Aca habla de algunos procesos que  no esten en loop infinito, queria preguntar a que procesos se refieren. Porque estuve viendo el codigo y todos tienen un SET PC 0 al final

**Comment by f-and** [comment]
Buenas Joaquin!
Quedo de una versión vieja donde habían otros jobs, todos los procesos deberían hacer un loop infinito.
Saludos.-
