### ISSUE TITLE
Dudas sobre el funcionamiento de la TLB al achicar un proceso

### ISSUE THREAD

**Issue by ManuelGarciaF** [sisoputnfrba/foro#4112]
Buenas, tenía una duda sobre qué sucede cuando achicamos un proceso con sus entradas de la TLB, debemos calcular el numero de paginas que le quedaría al ser achicado y remover todas las entradas erroneas?

**Comment by mefederico** [comment]
Hola buenas! 

No hay pruebas con resize para abajo y eventual escritura, por lo que no van a tener problema de un acceso invalido por no limpiar la TLB. Pero si es una buena idea limpiar la tabla de paginas, dejo un issue asociado https://github.com/sisoputnfrba/foro/issues/4062

Saludos!

**Comment by ManuelGarciaF** [comment]
Gracias, lo que dice en el issue ese es lo que termine haciendo, me pasaba que si no invalidaba las entradas explotaba todo en salvation's edge ya que los procesos que se van agrandando y achicando terminaban con entradas viejas incorrectas en la TLB que se usaban cuando el proceso volvia a crecer.
