### ISSUE TITLE
Duda de pruebas en VMs y SSH

### ISSUE THREAD

**Issue by JoaquinMariosa** [sisoputnfrba/foro#4113]
Buenas! Con nuestro grupo leyendo los issues #4052 y #4075, decidimos hacer las pruebas con dos VM (clonadas), una de CPU conectando con SSH en una Powershell de Windows a Kernel, y la otra VM con Memoria y el mismo comando de SSH con las IOs, queriamos saber si esta bien la idea de ejecutar algunos modulos con SSH ya que mañana vamos a probar el TP en los laboratorios de Medrano y pensamos hacerlo de la misma manera, o entendimos mal los issues y deberia ejecutarse de otra manera. Muchas gracias!
![prueba-vms](https://github.com/sisoputnfrba/foro/assets/134443307/75f9c78a-d881-446d-b8bd-31828e6ea1b8)

**Comment by RaniAgus** [comment]
¡Buenas! Es correcto, de hecho tenemos una [guía de despliegue](https://docs.utnso.com.ar/guias/herramientas/deploy) con tips para la entrega. Saludos

**Comment by JoaquinMariosa** [comment]
Perfecto! Ademas, para las pruebas subimos la carpeta de scripts_kernel y scripts_memoria al repositorio del TP, no hay problema con eso no?

**Comment by RaniAgus** [comment]
No hay problema! Pueden subir todo lo que necesiten al repo excepto bibliotecas de terceros no desarrolladas por la cátedra o binarios. De hecho, en la guía de despliegue les recomendamos tener listas las configs de las pruebas para agilizar la entrega

**Comment by JoaquinMariosa** [comment]
Joya, mil gracias!
