### ISSUE TITLE
Copy_String

### ISSUE THREAD

**Issue by tomassagrada** [sisoputnfrba/foro#4114]
Buenas, nos surgió una duda sobre Copy_String, por que lo que tenemos hecho era mandándole a memoria a la vez una dirección para leer y una para escribir con un solo tamaño. Pero que pasaría si por ejemplo fuesen paginas de 4 bytes, la lectura fuese 3 bytes desde el inicio de una pagina y la escritura fuese a partir la mitad de otra pagina? tendría que fijarme y pasar, si es necesario, mas de 1 dirección de escritura por cada dirección de lectura?. La idea de hacerlo de esta forma era no tener que ir guardando el contenido leído en memoria ni en CPU, si no que ir leyendo y escribiendo cuando se lee (teniendo en cuenta que 1 sola instrucción puede pedir mas de una dirección).

Desde ya gracias. 

Un agregado, las fechas para asistir a entregar se pueden usar las 3 o hay un limite?

**Comment by RaniAgus** [comment]
¡Buenas!
1) Sí, está contemplado en la sección "MMU" del enunciado. De hecho, no es el único caso: también podría pasar en `MOV_IN` y `MOV_OUT`
2) Sí, pueden presentarse a las 3 entregas

Saludos

**Comment by tomassagrada** [comment]
Perdón, o sea como que podría pasar en MOV_IN y MOV_OUT, en esas instrucciones solo hay lectura o escritura pero no se mezclan o no?

**Comment by RaniAgus** [comment]
Me refería a que puede pasar que una lectura o una escritura queden en más de una página. Ejemplo: si tengo tamaño de página 16 y quiero leer/escribir desde la dirección lógica 14 un registro de 4 bytes, va a caer una mitad en la página 0 y la otra mitad en la 1.

**Comment by tomassagrada** [comment]
ah sisi, eso lo tenia en cuenta. Mi pregunta refería mas para el caso de copy string si la relación de lectura escritura iba a ser equivalente en cuanto a usos de paginas. Por ejemplo podría pasar que yo lea 3 bytes de una pagina, pero que después yo empiece a escribir esos 3 bytes en la mitad de otra pagina y me queden distribuidos entre 2 paginas?

**Comment by RaniAgus** [comment]
Sí, los offset dentro de la página pueden ser distintos, por lo que hacer n lecturas no tendría por qué disparar el mismo número de escrituras. Pueden ser más, o pueden ser menos

**Comment by tomassagrada** [comment]
perfecto, muchas gracias.
