### ISSUE TITLE
DUDA STDIN STDOUT RESPECTO A RESPETAR ESPACIO DE PROCESOS

### ISSUE THREAD

**Issue by papiness77** [sisoputnfrba/foro#4115]
La duda es si cuando en stdin o stdout me llega  una direccion fisica que por ejemplo esta a la mitad de un marco y tengo que leer mas de la mitad y pasarme a otro marco. SI estos dos marcos son de procesos distintos lo tengo que escribir igual? O la idea es que escriba en los marcos de solo el proceso que pidio la operacion IO

**Comment by RaniAgus** [comment]
¡Buenas! Ese escenario no debería darse nunca, ya que en este punto la CPU ya realizó la traducción de la dirección lógica y el tamaño total en "n" direcciones con sus tamaños correspondientes. Entonces, cuando la IO reciba esas direcciones y tamaños, ya estamos seguros que le pertenecen al proceso.

Saludos
