### ISSUE TITLE
Finalizar Proceso en Prueba Planificacion

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#4116]
Hola buenas. Tengo una pregunta sobre la finalizacion del proceso que esta en loop en la prueba de planificacion. En mi caso cuando finalizo un proceso mando la interrupcion pero  en la prueba de VRR me paso que tuve que hace finalizar_proceso 3 veces en algunos casos porque la interrupcion que iba por fin de quantum llegaba antes que la interrupcion que se manda por el comando. Y en estos casos el proceso se estaba devolviendo a kernel y la interrupcion por finalizacion de proceso no se cumplloa. Entonces cuando el proceso vuelve a kernel no entra a exit sino que vuelve a la cola de ready porque volvio por fin de quantum. Podria pasar esto?

No pasa siempre, pero dependiendo en que momento pongas finalizar proceso se puede llegar a dar. Lo probe en varios intentos  y en una sola me paso 3 veces

**Comment by mefederico** [comment]
Hola buenas! 

Deberian poder indicarle al Kernel que el proceso no va a READY sino que a EXIT

Saludos!

**Comment by f-and** [comment]
@JoaquinCoaricona, para saber les sirvió la respuesta? Así cerramos el issue.
