### ISSUE TITLE
Problema con escribir bloques en DialFS

### ISSUE THREAD

**Issue by iskr889** [sisoputnfrba/foro#4117]
Hola que tal, tuvimos un problema programando la interfaz DialFS. Una de las funciones que estamos haciendo es "escribir_bloques" y creemos que hay un problema en ella ya que por alguna razón los bloques no retienen la información que les damos y en la consola nos aparecen como vacíos. Queríamos saber qué estamos haciendo mal.

### 📝 Código relevante

void escribir_bloques(int primer_bloque, size_t tam_archivo, int puntero_archivo, char* texto){
    
    int bloques_necesarios = ceil(strlen(texto) / tamanio_bloques);
    
    if(tam_archivo < strlen(texto)){
        log_error(logger, "El texto es mas grande que el archivo");
        exit(EXIT_FAILURE);
    }

    int bloque = obtener_inicio_bloque(primer_bloque);

    int posicion = bloque + puntero_archivo;

    for (int i = 0; i < bloques_necesarios; ++i) {
        
        int offset = posicion * tamanio_bloques + i * tamanio_bloques;
        
        int longitud_copia = (strlen(texto) - i * tamanio_bloques < tamanio_bloques) ? (strlen(texto) - i * tamanio_bloques) : tamanio_bloques;
        
        memcpy(&bufferBloques[offset], &texto[i * tamanio_bloques], longitud_copia);
    }

    msync(bufferBloques, tamanio_bloques * cantidad_bloques, MS_SYNC);
}

**Comment by mefederico** [comment]
Hola! 

Se me hace bastante complicado saber que puede estar pasando pero les recomiendo hacer un programa simple que escriba en el inicio de un bloque una palabra hardcodeada y hacer el msync, para ver si eso si lo pueden ver en el archivo y empezar a iterar desde ahí a la solución más completa

Para ver si el problema que tienen es en las cuentas o en que parte específicamente está fallando

Saludos!

**Comment by karengrams** [comment]
¡Buenas @iskr889!

¿Cómo va? Espero que bien. ¿Cómo fue con lo que menciono @mefederico? ¿Pudieron solucionarlo en estos días? ¿Pueden comentarnos un poco más de info? Como el stacktrace que les indica el debugger, o los logs. 

¡Nos vemos!

Kar.
