### ISSUE TITLE
Uso de CPU

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#4118]
Hola en la prueba de Salvations Edge, mientras la estoy corriendo, tengo este uso de CPU. Estaria bien?
![image](https://github.com/sisoputnfrba/foro/assets/112731246/795bb6da-6df0-4766-81b4-89b248f8ed5a)

Por otro lado algo que me pasa siempre que hago htop, es que me aparece 133% o algo asi y en el mismo momento baja a 4 o numeros como el de la foto, no se si es normal o no, pero durante las pruebas el valor es el de la foto. 
Desde ya gracias

**Comment by mefederico** [comment]
Hola buenas! 

El valor de 133% te aparece solo al abrir htop sin ningún modulo de su tp levantado?

Por otro lado si esos números son normales, una espera activa haría que la CPU se pegue contra el 100% y no baje del 90% al menos de forma cíclica, esto lo podes ver poniendo un while(1) en algún lado del código para comprobar como se ve en htop.

Con htop, como pueden ver en la imagen que compartís, también te deja ver la memoria, recomiendo correr el programa sin valgrind ver con cuanta memoria empiezan la prueba, dejarlo un rato y ver cuanta memoria esta usando, si aumenta consistentemente tienen un problema, si es estable están perfecto!

Saludos!

**Comment by JoaquinCoaricona** [comment]
Buenas, al final segui probando unas cuantas veces mas esa misma prueba y me paso que a la tercera empezaba a subir el porcentaje de CPU, no es que se mantenia en 100 pero llegaba a 80 y despues bajaba a 30 y asi seguia variando.
En mi caso solo tengo while(1) pero que se quedan bloqueados en las funciones bloqueantes, no son while(1) que se ponen a comprobar todo el tiempo.
Por otro lado todavia tengo algunas cosas para arreglar de memory leaks pero como en otras pruebas eran pocos kb lo deje asi, pero aca como es repetitivo, llega a ser mayor la memoria perdida. Esto de la memoria puede hacer que aumente el porcentaje de CPU? o es aparte?

**Comment by mefederico** [comment]
Me llama la atención que llegue a 80%, para este tipo de tps no suele ser lo normal, una pregunta que puede salir es porque creen que puede darse? Que proceso que su TP haga es muy exigente en nivel de CPU? 

Cuando dije poner un while(1) me refería a uno nuevo una linea `while(1);` 

El memory leak pocos KB es mucha memoria, piensen en la memoria que ustedes allocan, suelen cosas de 4 bytes, capaz alguna palabra de 30-64 bytes, ahora cada KB es 1024 bytes, unos 20-200 ordenes de magnitud más alto. Lo importante es ver si no hay una perdida constante, en pruebas más cortas el leak se camufla con la memoria que requiere el sistema solamente para empezar

La duración de la prueba depende, la solemos dejar 5-15 minutos, depende de lo que veamos. La idea es que aparezcan los problemas propios de muchas iteraciones

**Comment by mefederico** [comment]
Hola buenas! 

Podemos dar por cerrado este issue?
