### ISSUE TITLE
Misma IP en las VMs de la facultad

### ISSUE THREAD

**Issue by tomipodo** [sisoputnfrba/foro#4121]
Buenas! Cómo andan? 
Hoy fuimos a probar el TP al labo de Medrano con 4 computadoras distintas y 2 VMs tenían la misma IP. Teníamos miedo de que las conexiones se hagan mal y directamente prendimos otra compu y usamos esa para probar (tenía una IP distinta). Queremos saber si puede llegar a pasar que en la entrega 2 VMs tengan la misma IP? 
Gracias, saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

No se preocupen, es algo que no va a pasarles el día de la entrega. 
A veces pasa que como las Pcs del labo las usan durante semana sin supervisión quedan con cualquier config en virtualbox, por eso para las entregas revisamos siempre que todas las máquinas tengan distintas IPs.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Si les vuelve a pasar intenten resolverlo [de la misma forma que en el TP0](https://docs.utnso.com.ar/primeros-pasos/tp0#resolver-conflictos-de-red). Saludos

**Comment by tomipodo** [comment]
Genial, muchas gracias!
