### ISSUE TITLE
Salvations Edge

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#4122]
Hola en salvations Edge varios procesos finalizan por out of memory. Esto estaria bien? porque en otro issue habian dicho que ninguno finalizaba porque estaban todos en loop.

**Comment by iago64** [comment]
Buenas! Cómo va?

Si, es algo que nos quedó de la vieja versión de la prueba, vamos a actualizar el doc para que la memoria alcance para todo, pueden ponerle 4096 de tamaño de memoria asi entran todos los procesos sin problemas.

Saludos.-

**Comment by JoaquinCoaricona** [comment]
Okok y una pregunta. Cuando dice que cada tanto vamos a ejecutar instrucciones que nos piden los ayudantes, esas instrucciones serian de linux? osea htop y esas? Porque despues nombra aparte las propias del TP. detener,iniciar planificacion y la de Proceso_estado

**Comment by iago64** [comment]
Buenas! Cómo va?

Las instrucciones que se les pueden pedir son justamente algunas de esas 3 instrucciones para ver como viene el tema de los procesos y a lo sumo se puede sumar en una terminal donde no este corriendo ningun proceso un htop para ver el consumo de memoria y/o CPU.

Saludos.-

**Comment by rood8592** [comment]
Buenas, con respecto a esta prurba que se debería hacer con el teclado, dejarlo ahí colgado o ir ingresando cadenas a medida que las va pidiendo?

**Comment by iago64** [comment]
Buenas!

Buen punto, en los casos del teclado simplemente ingresan un caracter y le dan al enter cuando se los pida, total la idea es probar que no se comen la memoria serializando / de serializando esos mensajes.

Saludos.-

**Comment by mefederico** [comment]
Hola buenas! 

Quedaron las dudas resueltas? Podemos cerrar el issue?

Saludos
