### ISSUE TITLE
Duda en IO_STDIN_READ sobre si ingresar texto antes o después de que llegue un proceso

### ISSUE THREAD

**Issue by GorinoManuel** [sisoputnfrba/foro#4123]
Hola, quería preguntar si las STDIN desde que inician deben esperar a que el usuario ingrese el texto o si lo piden una vez que un proceso lo solicitó? 
Por el momento nosotros lo implementamos de forma que primero un proceso solicite hacer la operación y recién ahí pide que ingrese  el texto.

### 📔 Citas del enunciado/videos
Las interfaces STDIN no van a esperar ninguna unidad de trabajo, ya que las mismas van a quedarse esperando que el alumno ingrese un texto por teclado.

**Comment by mefederico** [comment]
Hola buenas!

Efectivamente solamente solicitan el ingreso de datos cuando un proceso hace el pedido

Saludos!

**Comment by GorinoManuel** [comment]
Ah bueno, muchas gracias por aclarar!
