### ISSUE TITLE
VMs labo

### ISSUE THREAD

**Issue by rood8592** [sisoputnfrba/foro#4124]
Buenas,
Hoy fuimos al labo y a veces en una de las maquinas sin que esten los modulos correspondientes levantados (o cuando probamos pero ya habiamos dado de baja los mismos) el uso de la cpu era alto, en añgunos casos llegaba a 100%. Y la memoria saltaba de 176 a 240 y se quedaba asi un rato y despues como que se estabilizaba todo. ¿Por qué puede pasar esto?

**Comment by mefederico** [comment]
Hola buenas! 

No se si otro ayudante tiene una información extra sobre esto, yo no tuve acceso a los laboratorios, pero lo que recuerdo es que hay un proceso que updatea paquetes que está corriendo de fondo que esta haciendo las validaciones, inicia y termina. Al menos eso recuerdo de la ultima entrega, de cualquier modo nosotros miramos el htop y vemos que proceso esta usando el CPU y la memoria, solo tomamos en cuenta los procesos del TP obviamente

Saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

Algo importante que suele pasar a lo largo del cuatrimestre es que los laboratorios tienen nulo control de lo que hacen con las VMs, por eso los ayudantes solemos ir antes para dejar todo configurado de manera tal que las VMs para la entrega estan en optimas condiciones.

Esto que comenta Fede es algo que nos paso en otros cuatrimestres, pero eso es fácil de ver si filtran solo por sus procesos en el htop.

Saludos.-
