### ISSUE TITLE
Algoritmos de reemplazo TLB

### ISSUE THREAD

**Issue by joaquingandola** [sisoputnfrba/foro#4125]
Buenas, tengo una consulta sobre el enunciado. Se menciona que los algoritmos de reemplazo de la TLB "podrán" ser FIFO y LRU, esto se refiere a que deberíamos elegir a uno de los dos, o que se puede elegir alguno de los dos en tiempo de ejecución?

Enunciado: 
La cantidad de entradas y el algoritmo de reemplazo de la TLB se indicarán por archivo de configuración de la CPU. La cantidad de entradas de la TLB será un entero (pudiendo ser 0, lo cual la deshabilitará), mientras que los algoritmos podrán ser:
FIFO
LRU

**Comment by mefederico** [comment]
Hola buenas! 

El algoritmo de reemplazo se cambia al iniciar el modulo solamente, esto también lo pueden validar en el documento de pruebas

Saludos!

**Comment by joaquingandola** [comment]
Buenisimo gracias!!

**Comment by joaquingandola** [comment]
Buenisimo gracias!!
