### ISSUE TITLE
Duda sobre IO_FS_WRITE

### ISSUE THREAD

**Issue by moracontreras** [sisoputnfrba/foro#4126]
Hola! Todo bien?
Les hago una consulta que me surgió a la hora de escribir un archivo. Los pasos que sigo son los siguientes
1) verificar que exista todo lo necesario
2) verificar si lo que se desea escribir ocupa menos que un bloque
2a) en caso de que si, verifico si entra en el espacio libre del ultimo bloque ya asignado al archivo. si si joya, sino salto a 3).
2b) en caso de que ocupe mas, me fijo en el bitmap si el bloque siguiente a los ya asignados al archivo esta libre. si no, compacto y vuelvo a empezar. si si:
3) lo que hacia era particionar el texto para que se escriba lo que entre en lo sobrante del ultimo bloque ya asignado al archivo y el resto en el sigueinte bloque. pero es necesario? o sea en realidad en bloques.dat se simulan los bloques pero en definitiva si puedo escribir todo de corrido. entiendo que verificar lo del bitmap si es necesario pero capaz fraccionar el texto no

Desde ya, muchas gracias!

**Comment by mefederico** [comment]
Hola! Todo bien 😃 

Ustedes no tienen que asignar más espacio a un archivo en write, por lo cual tampoco van a tener que compactar al intentar hacer un write, esto solo es posible al hacer resize

A la hora de escribir tengan en cuenta que no siempre escriben al final del bloque, tampoco pueden saber el concepto de hasta donde esta escrito un bloque, todo eso lo maneja el programa que nosotros les damos en las pruebas.

Para saber desde donde escribir es que sirve el puntero registro, que lo que tienen que hacer es:
`bloque_inicial * tamaño_bloque + registro_puntero` con esa cuenta es desde donde tienen que escribir en bloques.dat

y como bien indicas en el punto 3, no necesitan particionar el texto dado que los bloques son continuos

Saludos!

**Comment by moracontreras** [comment]
entonces no debería verificar que entre en los bloques que ya están asignados?

**Comment by mefederico** [comment]
No es algo que vayamos a probar, pueden verificarlo para confirmar que no hay un error en su código y en caso que no entre en el espacio ya asignado pueden loggear un error para identificar el caso rápidamente y poder corregirlo. O corregir nuestras pruebas porque somos humanos y nos podemos equivocar

El chequeo seria `registro_puntero + cantidad_bytes_escribir < tamaño_archivo`

**Comment by moracontreras** [comment]
perfecto, muchisimas gracias!

**Comment by moracontreras** [comment]
perdón, última pregunta al respecto, está bien agregarle siempre un byte al strlen(texto) para el barra n a la hora de escribirlo en el archivo? creo que no porque si lo escribo en el medio del archivo no deberia ir ahí el barra n pero por las dudas pregunto

**Comment by mefederico** [comment]
No hay problema con la cantidad de preguntas jaja estoy/estamos para ayudar incluso por la fecha que es estoy tratando de responder lo antes posible para que puedan desarrollar sin trabas, lo que si ya tengo que salir por lo que respondiendo en el momento es posible que sí sea la ultima 😄 

No tienen que agregar ningún \n ni a la hora de escribir en archivos ni en la memoria. Para lo único que tienen que agregar un \n es a la hora de mostrar por pantalla en STDOUT

Saludos!

**Comment by moracontreras** [comment]
perfecto, muchísimas gracias federico!
