### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by lperezpersico** [sisoputnfrba/foro#4129]
buenas! Estoy teniendo un problema con la prueba de FS. La primera parte funciona todo bien pero cuando tiro abajo los módulos y los vuelvo a levantar me tira siempre un segmentation fault en un hilo que ya usé para hacer la primera parte, por eso me parece raro, porque nunca había causado problema. Es en la línea del pthread_create. Saben qué podrá ser? Gracias!
```
void interfaz_dialfs (t_queue* cola)
{
    pthread_t hilo_dialfs;
    t_io_args* args_dialfs = malloc(sizeof(t_io_args));
    args_dialfs->cola = cola;
    //args_dialfs->comparador_vrr = comparador_vrr;
    pthread_create(&hilo_dialfs, NULL, atender_int_dialfs, (void *) args_dialfs);
    pthread_detach(hilo_dialfs);
}
```

**Comment by iago64** [comment]
Buenas! Cómo va?

Fijate de correr con Valgrind porque asi en el aire es como tratar de adivinar como va a estar el clima, hay demasiadas variables posibles y sin nada seguro es complicado.

Saludos.-

**Comment by lperezpersico** [comment]
ahí lo corrí con valgrind y encontré el error! Gracias
