### ISSUE TITLE
Duda sobre compactar

### ISSUE THREAD

**Issue by lewislee0920** [sisoputnfrba/foro#4132]
Buenas, tengo una duda sobre la prueba de compactar. 
Hice la función compactar para liberar todos los bits del bitarray y asignar nuevos bits para cada archivo y escribir el nuevo bloque_inicial en su archivo de metadatos. Como el formato es como tal, en lugar de compactar en código de FS_4 solo lo hará en los códigos anteriores. (Por ejemplo si anteriormente el archivo estaba almacenado en 11 (archivo 1) 00 1(archivo2) 000 11111(archivo3) 111 (archivo4), cuando intento truncar el archivo2 y tengo que compactarlo, la función dejará la matriz de bits de la siguiente manera: 11(archivo1) 11111(archivo3) 111(archivo4) 1(archivo2) 00000) Mi pregunta es, compacando el bitarray antes de que se pide en FS_4 no sera la razon de desaprobacion no? o Es importante compactar solo en ese momento? Si explico como funciona mi version estaria sin problema?

**Comment by f-and** [comment]
Buenas Lewis! 
Primero de todo, en la prueba se puede llegar a compactar antes, específicamente en el FS_1, como se destaca [acá](https://github.com/sisoputnfrba/foro/issues/4075#issuecomment-2209928702), que no habría problema. Pero lo importante es que también, si o si, se compacte en el FS_4. Eso ocurre? O se compacta en otro FS?

**Comment by lewislee0920** [comment]
Durante la instruccion de truncate archivo2 si se compacta

**Comment by lewislee0920** [comment]
Pero estoy teniendo un error con eso tambien. 

Esto es mi codigo de compactar:
```
void compactar(t_bitarray *bitarray, char* nombre_archivo_a_truncar, int tamano_nuevo, int tamano_actual){

    char* nombre_archivo;
    char* path_archivo;
    char* path_archivo_a_truncar;
    
    int bloque_inicial = 1;
    int tamano;
    int bloques_ocupados;
    int cantidad_archivos_en_lista = list_size(lista_archivos);
    int cant_archivos_leidos = 0;

    int bloque_fin_ocupado;
    int tamano_bloques_ocupados;

    //Sacar de la lista el arhcivo a truncar para poner dicho archivo en el ultimo despues
    for (int i = 0; i < cantidad_archivos_en_lista; i++) {
        char* archivo_actual = list_get(lista_archivos, i);
        
        if (strcmp(archivo_actual, nombre_archivo_a_truncar) == 0) {
            list_remove(lista_archivos, i);
            free(archivo_actual);
            cantidad_archivos_en_lista--;
            i--; 
        }
    }

    //Una lista temporal 
    t_list* lista_temp = list_create();

    log_info(logger, "Liberando todos los bits en el bitarray.");

    //liberar todos los bits en bitarray que voy a reocuparlo con metadata nuevo
    hacer_libre_bloques(bitarray, 0, block_count);

    verifcar_los_bits_ocupado(bitarray);

    log_info(logger, "Bits en el Bitarray liberado.");

    //Actualizar todos los archivos de metadata para usarlo despues en posicionar el bitmap.dat y bloques.dat
    while(cantidad_archivos_en_lista > cant_archivos_leidos){
        
        tamano = 0;

        //LIST_GET_FIRST NOT RETURNING ANYTHING. SINCE THE BEGININNG ITS ONLY TWO FILES BUT BEGIN COMPACTING ALREADY??
        nombre_archivo = (char *)list_remove(lista_archivos, cant_archivos_leidos);

        log_info(logger, "Archivo a mover: %s", nombre_archivo);

        //Path de archivo a Borrar
        asprintf(&path_archivo, "%s/%s", path_archivo_comun, nombre_archivo);

        //Abrir archivo para leer el bloque inicial y tamano 
        FILE *archivo = fopen(path_archivo, "r+");
        if (archivo == NULL) {
            log_info(logger,"Error abriendo el archivo");
            exit(EXIT_FAILURE);
        }

        //Leer y guardar Bloque Inicial
        fprintf(archivo, "BLOQUE_INICIAL=%i\n", bloque_inicial);

        log_info(logger, "Nuevo bloque incial de archivo %s: %i", nombre_archivo, bloque_inicial);

        //Leer tamano
        fscanf(archivo, "TAMANIO_ARCHIVO=%i\n", &tamano);

        log_info(logger, "TAMANO: %i", tamano);

        //Buscar cantidad de bloques ocupados por el archivo
        if(tamano < block_size) {
            bloques_ocupados = 1;
        }else{
            bloques_ocupados = (tamano + block_size - 1) / block_size; 
        }

        log_info(logger, "Bloque ocupado: %i", bloques_ocupados);

        bloque_fin_ocupado = bloque_inicial + bloques_ocupados - 1;

        log_info(logger, "Ocupando bloques en bitmap.dat");

        //Ocupar bits en bitarray
        for(int i = bloque_inicial - 1; i < bloque_fin_ocupado; i++){
            bitarray_set_bit(bitarray, i);
            bloques_libres = bloques_libres - 1;
        }

        //actualiza el bloque_inicial para ponerlo a siguiente archivo
        bloque_inicial += bloques_ocupados;
        
        log_info(logger, "Nuevo bloque incial para la siguiente archivo a compactar: %i", bloque_inicial);

        log_info(logger, "Agregando el archivo a lista temproal y eliminando del lista principal");

        //Agregar en lista_temp y borrar de la lista principal ya que hizo lo que tengo que a este archivo
        //Despues se agrega de nuevo hasi que no hay problema
        list_add(lista_temp, nombre_archivo);

        cant_archivos_leidos++;

        //Para proxima loop hago null dichos variables
        path_archivo = NULL;

        free(path_archivo);
        fclose(archivo);
    }

    //Aca estoy haciendo esto para archivo que tengo que truncar
    log_info(logger, "Archivo a mover: %s", nombre_archivo_a_truncar);

    //Path de archivo a Borrar
    asprintf(&path_archivo_a_truncar, "%s/%s", path_archivo_comun, nombre_archivo_a_truncar);

    //Abrir archivo para leer el bloque inicial
    FILE *archivo_a_truncar = fopen(path_archivo_a_truncar, "r+");
    if (archivo_a_truncar == NULL) {
        log_info(logger,"Error abriendo el archivo");
        exit(EXIT_FAILURE);
    }

    ftruncate(fileno(archivo_a_truncar), 0);

    //Volver al incio de archivo
    rewind(archivo_a_truncar);

    //Leer y guardar Bloque Inicial
    fprintf(archivo_a_truncar, "BLOQUE_INICIAL=%i\n", bloque_inicial);

    log_info(logger, "Bloque Inicial de archivo despues de mover: %i", bloque_inicial);

    //Leer tamano
    fprintf(archivo_a_truncar, "TAMANIO_ARCHIVO=%i\n", tamano_nuevo);

    log_info(logger, "Tamano de archivo despues de mover: %i", tamano_nuevo);

    //Buscar cantidad de bloques ocupados por el archivo
    if(tamano_nuevo < block_size) {
        bloques_ocupados = 1;
    }else{
        bloques_ocupados = (tamano_nuevo + block_size - 1) / block_size; 
    }

    if(bloque_inicial + bloques_ocupados < block_count){

        bloque_fin_ocupado = bloque_inicial + bloques_ocupados - 1;

        //Ocupar bits en bitarray
        for(int i = bloque_inicial - 1; i < bloque_fin_ocupado; i++){
            bitarray_set_bit(bitarray, i);
            bloques_libres = bloques_libres - 1;
        }

        //Agrego el archivo a truncar devuelta a la lista
        list_add(lista_temp, nombre_archivo_a_truncar);

        //Como despues de while es vacio hago esto para volver a contener los archivos que tenia anteriormente actualizado
        lista_archivos = lista_temp;
    }else{
        log_info(logger, "No hay suficiente espacio despues de compactar tambien.");
        ftruncate(fileno(archivo_a_truncar), 0);

        //Volver al incio de archivo
        rewind(archivo_a_truncar);

        //Escribir en el archivo el tamano nuevo 
        fprintf(archivo_a_truncar, "BLOQUE_INICIAL=%i\n", bloque_inicial);
        fprintf(archivo_a_truncar, "TAMANIO_ARCHIVO=%i\n", tamano_actual);
    }

    fclose(archivo_a_truncar);
    free(path_archivo_a_truncar);
}
```

Pero dentro de while loop cuando trata de sacar el tamano de segundo archivo no se puede y ademas de eso se va escribiendo en el archivo el valor de de tamano de primer archivo. Ahora probe poniendo un tmanao = 0 en el inicio del loop pero en vez del tamano del archivo anterior se va poniendo el 0 que defini en el inicio del loop.

**Comment by f-and** [comment]
No claro, el archivo2 no debería llamar a compactar el FS porque solo se le trunca el tamaño a 10 bytes, que es menor al tamaño de un bloque (16) por lo que no debería haber compactación ahí.
Probaste correr el FS con Valgrind? a lo mejor algún valor se está setteando erroneamente.

**Comment by lewislee0920** [comment]
```
SET AX 0
SET BX 250
SET CX 70
IO_FS_CREATE FS pesado.txt
IO_FS_TRUNCATE FS pesado.txt BX
IO_FS_DELETE FS archivo1.txt
IO_FS_TRUNCATE FS archivo2.txt CX
SET DX 0
EXIT
```

Pero como setea el cx a 70 y despues ahace truncar a archivo2 a tamano de 70 no sera que tiene que compactar?

**Comment by lewislee0920** [comment]
Tengo entendi que hay que compactar porque antes su tasmano fue 10 y ahora es 70 y debe agrandar el archivo. Pero como esta dentro de otros blopques ocupados hay que compactar

**Comment by f-and** [comment]
Ah claro, como habías dicho que se compactaba antes del FS_4 había entendido que hablabas de la ejecución del FS_2, sí, en el FS_4 se tiene que compactar cuando se agranda el archivo2 ahí donde mencionas.

**Comment by lewislee0920** [comment]
nono osea que en caso de FS_1, cuando hace truncate a salida.txt y cronologico.txt hay si compacta ya que salida.txt esta ocupando bloque1 y cronologico.txt el bloque2. Como bloque2 esta ocupado se va compactando poniendo cronologico.txt a blopque 1 y salida.txt a bloque2 y hay se agranda

**Comment by lewislee0920** [comment]
en el FS_2 nunca se compacta

**Comment by lewislee0920** [comment]
Y lo que preguntaba sobre: 
"Pero dentro de while loop cuando trata de sacar el tamano de segundo archivo no se puede y ademas de eso se va escribiendo en el archivo el valor de de tamano de primer archivo. Ahora probe poniendo un tmanao = 0 en el inicio del loop pero en vez del tamano del archivo anterior se va poniendo el 0 que defini en el inicio del loop."

Esto que seria la problema? Estoy medioconfucndido porque no se copia el tamano de segundo archivo dentro de loop bien

**Comment by lewislee0920** [comment]
```
BLOQUE_INICIAL=13
TAMANIO_ARCHIVO=250
```

```
BLOQUE_INICIAL=6

TAMANIO_ARCHIVO=250
```

Osea antes de prueba de FS_4 el contneido de archivo de metadata para pesado.txt es como muestra en el primer codigo. Pero en el ultimo instruccion de FS_4: IO_FS_TRUNCATE FS archivo2.txt CX
Ocurre el evento de compactacion durante el segundo while cuando trata con pesado.txt, se va escribiendo como el de segundo codigo y produce un segmentation fault

**Comment by lewislee0920** [comment]
```
int result = fscanf(archivo, "TAMANIO_ARCHIVO=%i\n", &tamano);
        if (result != 1) {
            log_info(logger, "Error leyendo TAMANIO_ARCHIVO en el archivo: %s", path_archivo);
            exit(EXIT_FAILURE);
        }
```

Probe poniendo esto en lugar de fscan para tamano y aparece:
`Error leyendo TAMANIO_ARCHIVO en el archivo: /home/utnso/dialfs///pesado.txt`

**Comment by iago64** [comment]
Buenas! Cómo va?

En la compactación no hay una única forma de hacer las cosas, lo que nos importa como objetivo del TP es que encuentren una forma de mover los datos de los archivos para hacerle lugar a los archivos que están queriendo ampliar, si para hacerlo lo hacen sobre el mismo archivo o si se copian todo el contenido a otro archivo y después lo ordenan nos da igual, siempre y cuando entiendan que ventajas y que desventajas les genera hacerlo de una u otra forma.
Como nosotros no les dijimos de que forma tienen que asignar los bloques, también puede darse el caso de que como decía Fede en algunos casos puede haber o no compactación, entonces en esta situación, lo único que estamos 100% seguros es que cuando corran FS_4 vamos a tener una compactación si o si.

Saludos.-

**Comment by lewislee0920** [comment]
Buenas, ya estoy con esa parte pero sigo conlo de que enmi while loop no me deja leer el tamano_archivo de segundo archivo. Osea en el primer instancia de while loop, lea los valores desedaos y todo se ejecuta bien. Pero cuando voy al segundo instancia, se falla leer el valor de tamano_archivo del archivo.

**Comment by iago64** [comment]
Buenas! Cómo va?

Por las dudas, lo corriste con valgrind? Porque el hecho de que tengas un error que no puedas resolver debugueandolo me da la pauta de que es algún error en el manejo de la memoria.

Saludos.-

**Comment by lewislee0920** [comment]
si probe con valgrind y me tira errores con memoria. Gracias por la ayuda
