### ISSUE TITLE
Uso de PuTTY al desplegar en labo

### ISSUE THREAD

**Issue by bcochon** [sisoputnfrba/foro#4134]
Hola, tenía una duda respecto al uso de PuTTY. Cuando intentamos usarlo en el labo para facilitar el portapapeles en la consola no podíamos hacerlo funcionar, obteníamos errores inesperados (incluso siguiendo el mismo paso a paso que a otros grupos presentes en el laboratorio les había funcionado). Resolvimos el inconveniente duplicando la consola en powershell mediante el comando _ssh_, como se hacía al final del TP0. Eso nos dejó desplegar y correr nuestro sistema perfectamente.
Quería saber si hay algún inconveniente en prescindir de PuTTY y manejarnos de esta forma. Principalmente porque no creo que tengamos oportunidad de familiarizarnos con PuTTY antes de la entrega de este sábado a la que apuntamos. Saludos

**Comment by f-and** [comment]
Buenas!
Que raro el error, qué les causaba? Qué cosa querían copiar?
No debería haber problema con usar `ssh`, igual para el día de la entrega vamos a preparar las computadoras para que no haya ningún inconveniente con PuTTY o las VMs, por lo que si llega a ocurrir algo así durante la entrega pueden simplemente levantar la mano y podemos ayudarlos.
Saludos.-

**Comment by f-and** [comment]
Ah bueno, si no se preocupen que seguro si pasa lo arreglamos!
Si no quedó ninguna duda, cierro el issue.
Saludos.-
