### ISSUE TITLE
Duda pendrive entrega

### ISSUE THREAD

**Issue by GonTurri** [sisoputnfrba/foro#4135]
Buenas! espero este ya sea de los ultimos issues :( 

Queria preguntar si podiamos llevar un pendrive con un txt para  ir copiando los comandos a ejecutar (y el token) o si los tenemos que ir a buscar desde github u otro lado

Muchas gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Yo personalmente no soy partidario de andar usando pendrives en pcs semipublicas, pero para tener un txt con los tokens y/o comandos pueden hacerlo.

Saludos.-

**Comment by GonTurri** [comment]
Buenas, entonces me recomendas tener el token subido al repo? (pegriloso) y si no sera copiarlo a manopla pero lleva tiempo

**Comment by iago64** [comment]
Buenas! Cómo va?

Algo un poco mas seguro es iniciar sesión con el mail de la facultad que ante cualquier inconveniente siempre se puede recuperar y tener un mail con toda la info necesaria 😉 

Saludos.-

**Comment by GonTurri** [comment]
Buenas, acá después de cursar ciberseguridad hay arduos debates asi que ya veremos que hacer. Muchas gracias!
