### ISSUE TITLE
Conexión y desconexión de interfaces.

### ISSUE THREAD

**Issue by nsantero** [sisoputnfrba/foro#4136]
Hola como están? Estábamos definiendo las conexiones de IO y kernel, no nos queda claro el tema de las interfaces. En la parte de kernel el enunciado dice: "Toda interfaz de I/O puede conectarse y desconectarse en tiempo de ejecución. No se evaluará el caso en que una interfaz se desconecte estando ocupada por un proceso.". No nos queda claro el caso de desconexión de una interfaz. El enunciado no solicita una consola como el caso de kernel y las interfaces se inician por parámetros de main del modulo interfaz por lo que leímos en otros issues. Como será la prueba de desconexión de interfaces? 

Nosotros ahora mismo modelamos un struct en kernel para guardar las interfaces conectadas en una lista. Al momento de iniciar IO, recibe por parámetro los nombre de las interfaces y le envía a kernel la información. Consideramos que toda interfaz conectada esta en esta lista, y que una desconexión es salir de la misma. El tema es cuando le envia IO que se desconecto una interfaz.

El struct mencionado es el siguiente:
```typedef struct{
    char* nombre;
    Tipos_Interfaz tipo;
    int ocupada;//Funciona como bool
    int solicitudesEnCola;//Funciona como bool
    int pidActual;
}Interfaces_conectadas_kernel``

**Comment by iago64** [comment]
Buenas! Cómo va?

Las interfaces se desconectan de la forma mas simple que puede haber, tirando `Ctrl + C` en la terminal donde corre la interfaz.
Después como se van a enterar uds que la interfaz se desconectó? Cuando quieran mandarle algo y el `send()` les falle por broken pipe.

Saludos.-

**Comment by nsantero** [comment]
Okey, entonces con como lo veníamos planteando nosotros cortamos el programa con las IO se y se desconectarían todas las interfaces. Ahí nos surge la duda de si deberían correr cada una en una terminal aparte?

**Comment by iago64** [comment]
Buenas! cómo va?

Si, cada IO es un proceso aparte.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @nsantero! ¿Les sirvió la respuesta de Dami? Saludos

**Comment by iago64** [comment]
Cerramos el issue por inactividad.
