### ISSUE TITLE
Problema fs write

### ISSUE THREAD

**Issue by FacundoStancanelliUTN** [sisoputnfrba/foro#4138]
Buenas noches, como estan?
Genero esta duda ya que estamos con un problema en IO_FS_WRITE.
Estamos generando con mmap el bloques.dat:
`
bloques_datos_addr = mmap(NULL, BLOCK_COUNT * BLOCK_SIZE, PROT_READ | PROT_WRITE, MAP_SHARED, fd_bloque_de_datos, 0);
    `
Y luego, utilizamos msync para la sincronizacion de dicho espacio en memoria con el archivo en disco.
```
  if (msync(addr, length, MS_SYNC) == -1) {
        perror("msync");
        exit(EXIT_FAILURE);
    }
```

El problema detectado, es que a la hora de hacer una escritura y hacer el msync, el void* no tiene mas informacion y no se escribe nada en el archivo (en la captura se puede ver como luego de hacer el msync, la ultima linea del debugger, no hay nada en ese char* que antes si habia):

![Operativos Facu  Corriendo  - Oracle VM VirtualBox 11_7_2024 22_38_09](https://github.com/user-attachments/assets/4e474fc5-19c5-40df-bccc-9b3b2aca0f14)

Lo extraño es que con el bitmap no tuvimos ningun problema.
Por donde puede venir este error?

Desde ya muchas gracias.
Saludos!

**Comment by FacundoStancanelliUTN** [comment]
Sumo otro detalle. La forma en que abrimos el archivo es la siguiente:

```
    if (access(path_bloques_de_datos, F_OK) == -1) { //validar si no existe el archivo
        fd_bloque_de_datos = open(path_bloques_de_datos, O_RDWR | O_CREAT, S_IRUSR | S_IWUSR);
        if (fd_bloque_de_datos == -1) {
            perror("Error al abrir bloques.dat");
            exit(EXIT_FAILURE);
        }
        if (ftruncate(fd_bloque_de_datos, BLOCK_COUNT) == -1) {
            perror("Error al truncar bloques.dat");
            exit(EXIT_FAILURE);
        }
    } else {
        fd_bloque_de_datos = open(path_bloques_de_datos, O_RDWR | O_CREAT, S_IRUSR | S_IWUSR);
    }

    bloques_datos_addr = mmap(NULL, BLOCK_COUNT * BLOCK_SIZE, PROT_READ | PROT_WRITE, MAP_SHARED, fd_bloque_de_datos, 0);
```

**Comment by iago64** [comment]
Buenas! Cómo va?

Por las dudas, lo corriste con Valgrind? Porque si venias haciendo las cosas bien y de repente no hay info, me suena a que algun puntero no esta apuntando a donde tiene que apuntar y no te explotó de milagro.

Saludos.-

**Comment by FacundoStancanelliUTN** [comment]
Gracias por la respuesta dami!
No, no lo corrimos con valgrind. Consulta, que tipo de informacion podriamos sacar en este caso con valgrind?
Desde ya gracias.
Saludos!

**Comment by FacundoStancanelliUTN** [comment]
La logica adjunta en las imagenes, es correcta? La forma que estamos haciendo el memcpy?

**Comment by iago64** [comment]
Buenas! Cómo va?

Y mira, valgrind te va a decir rápidamente si metiste la pata con los punteros y te lo va a decir con un hermoso `Invalid read/write of size...`

Respecto a la pregunta del memcpy, no soy un compilador humano y me falta la mitad de la línea de código, lo mejor que podés hacer correrlo con valgrind y apoyarte en el debugger, igual si se les rompe todo post memcpy() tienen todos los números comprados para haber metido la pata con un puntero.

Saludos.-

**Comment by FacundoStancanelliUTN** [comment]
Todo bien!
Ah buenisimo!

Ahi me di cuenta igualmente que era!! 
En el truncado estaba poniendo esto:
```
if (ftruncate(fd_bloque_de_datos, BLOCK_COUNT) == -1) {
            perror("Error al truncar bloques.dat");
            exit(EXIT_FAILURE);
 }
```
Y lo estaba haciendo por el BLOCK_COUNT en lugar de hacerlo por BLOCK_COUNT * BLOCK_SIZE.
Con eso nos funciono :) 
![Operativos Facu  Corriendo  - Oracle VM VirtualBox 11_7_2024 23_41_51](https://github.com/user-attachments/assets/0b57c83e-df19-4db7-b0c4-41cd8101187e)

Desde ya muchas gracias!
