### ISSUE TITLE
Memoria contigua

### ISSUE THREAD

**Issue by christianMakinson95** [sisoputnfrba/foro#4140]
Buenas noches,
Quería confirmar algo de memoria. Segun algunos posteos que leimos, entendimos que "memoria contigua" referia a que la asignacion y manejo de paginas/marcos se hacia con direcciones contiguas de memoria. Sin embargo, nos entro la duda de lo siguiente:
Las paginas de un mismo proceso deben estar en marcos contiguos SIEMPRE? Es decir que si tenemos el siguiente caso
marco 0 -> pag 1 PID 1
marco 1 -> pag 2 PID 1
marco 2 -> pag 1 PID2

y se hace un resize de PID 1 que requiera una pagina mas.
Deberia quedar:
A) 
marco 0 -> pag 1 PID 1
marco 1 -> pag 2 PID 1
marco 2 -> pag 3 PID 1
marco 3 -> pag 1 PID2

o B)
marco 0 -> pag 1 PID 1
marco 1 -> pag 2 PID 1
marco 2 -> pag 1 PID2
marco 3 -> pag 3 PID1

Desde ya muchas gracias

**Comment by mefederico** [comment]
Hola buenas! 

Seria B, no tienen que hacer movimientos de marcos en memoria como si fuera una "compactación" por continua nos referimos a que todos los bytes de la memoria se tienen que manejar desde un void*

Ya luego los marcos y que paginas de que proceso tiene cada marco no va a ser continuo

Saludos!

**Comment by christianMakinson95** [comment]
Muchisimas gracias! buen fin de semana
