### ISSUE TITLE
Duda sobre los casos definitly lost de valgrind

### ISSUE THREAD

**Issue by lewislee0920** [sisoputnfrba/foro#4141]
Buenas, las pruebas todo corre bien sin problema y ademas de eso cuando corre el valgrind no detacta ningun error. Pero si hay algunas definitely lost. Estos se importa? o no es importante?

**Comment by mefederico** [comment]
Hola buenas! 

Todo depende, pero si, un memory leak es importante. Si corren su tp y constantemente están perdiendo memoria es un motivo para no aprobar la entrega. En la entrega se corre alguna prueba compleja y se observa con htop con que memoria empieza el programa y si de a poco va consumiendo cada vez más, si eso pasa, entonces tienen un leak

Y la forma que tienen ustedes de encontrarlo es con valgrind con definitly lost

Saludos!

**Comment by lewislee0920** [comment]
dale muchas gracias.
