### ISSUE TITLE
Logs kernel Ingreso a Ready

### ISSUE THREAD

**Issue by LainoRamiro** [sisoputnfrba/foro#4143]
Hola! Quería consultarles por el log del kernel Ingreso a Ready. En FIFO y RR, si yo tengo un proceso que ingresa a READY, entonces se debería mostrar el log de la siguiente manera:
“Cola Ready: [1, 2, 3]”

La duda surge si en el caso de VRR deberíamos en el caso de que pase un proceso a la Cola Ready mostrarlo como:
“Cola Ready: [7, 8, 9]” mostrando solo los procesos de la Cola Ready;
y si pasa un proceso a la Cola Ready Prioridad como:
“Cola Ready Prioridad: [10, 11, 12]” mostrando solo los procesos de la Cola Ready Prioridad. Es esta la forma que se pide?

Por cierto el proceso en Cola Ready Prioridad debería tener como estado READY? Pregunto por mi parte porque vi que a la cola de prioridad en los apuntes se le nombra como cola auxiliar de bloqueados.

**Comment by f-and** [comment]
Buenas, si, es como decís tiene que haber dos logs en el caso de VRR. Y estos pueden tener estado READY o READY PRIORIDAD, no debería haber problema con eso.
Saludos.-

**Comment by LainoRamiro** [comment]
Listo entonces ya lo entendí, gracias por responder, saludos! :)
