### ISSUE TITLE
Rutas

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#4144]
Hola buenas, una pregunta. Yo en mi tp tengo rutas absolutas, home/utnso y asi. Osea tengo las carpetas de prueba en la raiz y despues el tp en escritorio. El tema es que por lo que vi, la vm server no es igual. Entonces tengo que cambiar todo a una nueva ruta raiz? o deberia usar relativas?

**Comment by iago64** [comment]
Buenas! Cómo va?

La prueba tiene que andar en la VM server, cualquiera de las 2 opciones si funciona en la VM server van a estar bien.

Saludos.-

**Comment by JoaquinCoaricona** [comment]
Ok. Una pregunta, en esos 10 minutos que tengo para empezar con el despligue. Solo tendriamos que tener configurado todo para la primer prueba? Pregunto porque tengo que cambiar la ip de todos los config y quizas para los de entrada salida tenga que cambiarlos en las pruebas que siguen a medida que vaya avanzando

**Comment by iago64** [comment]
Buenas! Cómo va?

Los 10 minutos son para el deploy inicial, igual las IPs pueden usar el repo de [So-Deploy](https://github.com/sisoputnfrba/so-deploy)

Saludos.-

**Comment by JoaquinCoaricona** [comment]
ok entonces si pasamos la primer prueba, despues tendriamos un tiempo para preparar los configs para la segunda y asi?

**Comment by iago64** [comment]
Buenas! Como va?

Idealmente ese tiempo tiene que tender a 0, lo único que tendrían que tener que cambiar son las IPs, el resto de cosas ya las tienen.

Saludos.-

**Comment by JoaquinCoaricona** [comment]
Buenas, yo no pude implementar lo de tener varios configs y pasarlos por parametro, no lo implemente antes porque crei que era una sugerencia. No pasa nada si no llego a agregarlo?

**Comment by iago64** [comment]
Buenas! Cómo va?

Mientras no estén 10 minutos entre prueba y prueba no hay problema.

Saludos.-
