### ISSUE TITLE
Ejecutar las pruebas

### ISSUE THREAD

**Issue by IanR4** [sisoputnfrba/foro#4145]
Tenemos una pregunta acerca de cómo se van a realizar las cosas el dia de la entrega. La duda es si cada modulo se ejecuta en una computadora o en una puedo ejecutar varios modulos.

**Comment by IanR4** [comment]
Eso de configurar dos modulos en una computadora, como seria? No habria problemas con el uso de la ip?

**Comment by iago64** [comment]
Buenas! Cómo va?

Mientras los procesos se levanten en puertos diferentes no hay ningun problema.

Saludos.-
