### ISSUE TITLE
Duda sobre Valgrind

### ISSUE THREAD

**Issue by lewislee0920** [sisoputnfrba/foro#4146]
Buenas,
Queria saber si durante  la prueba, corremos con valgrind ./bin/entradasalida FS filesystem.config y si todo funciona y no hay ningun definitily lost entonces seria aprobado el tp? o se corre alguna instruccion mas con valgrind?

**Comment by iago64** [comment]
Buenas! Cómo va?

**Las pruebas se corren sin Valgrind**, los memory leaks los validamos viendo el consumo de memoria en `htop`

Saludos.-

**Comment by lewislee0920** [comment]
el htop como veo?

**Comment by lewislee0920** [comment]
==33174== 
==33174== HEAP SUMMARY:
==33174==     in use at exit: 2,265 bytes in 41 blocks
==33174==   total heap usage: 2,091 allocs, 2,050 frees, 186,400 bytes allocated
==33174== 
==33174== LEAK SUMMARY:
==33174==    definitely lost: 0 bytes in 0 blocks
==33174==    indirectly lost: 0 bytes in 0 blocks
==33174==      possibly lost: 0 bytes in 0 blocks
==33174==    still reachable: 2,265 bytes in 41 blocks
==33174==         suppressed: 0 bytes in 0 blocks
==33174== Rerun with --leak-check=full to see details of leaked memory
==33174== 
==33174== For lists of detected and suppressed errors, rerun with: -s
==33174== ERROR SUMMARY: 250 errors from 34 contexts (suppressed: 0 from 0)

cuando corre el valgrind aparece asi. Estaria bien?

**Comment by iago64** [comment]
Buenas! Cómo va?

`htop` es un programa de terminal que les muestra el uso de memoria y cpu de los procesos, pueden probarlo desde una terminal limpia en la vm con entorno grafico.

Respecto al output de valgrind ultimo que mandaste, si esta bien.
Saludos.-

**Comment by lewislee0920** [comment]
dale gracias
