### ISSUE TITLE
Duda sobre conexiones

### ISSUE THREAD

**Issue by ignacioRodriguezM** [sisoputnfrba/foro#4149]
Buenas, a nuestro grupo nos funcionan todas las pruebas pero luego de ejecutar varias veces todos los modulos, a veces a la hora de conectar kernel con el resto de modulos, éste se cae y hace que tengamos que correr todos los modulos de vuelta lo cual nos lleva un tiempo, como podriamos solucionarlo?

**Comment by iago64** [comment]
Buenas! Cómo va?

Que sería que levantar todo de vuelta les lleva un tiempo? tienen que esperar porque el socket queda bindeado? Si es eso no hay problema, esta contemplado.

Saludos.-
