### ISSUE TITLE
Duda config salvation's edge

### ISSUE THREAD

**Issue by EstebanHurtado0** [sisoputnfrba/foro#4150]
Hola!, como andan? tengo una duda con el config de teclado en la prueba Salvation's edge, ya que en las anteriores pruebas el tiempo de trabajo es distinto, se espera que lo cambiemos antes de ejecutar la prueba? o es un error del enunciado? gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

Cada prueba tiene sus tiempos y sus configuraciones, les recomendamos que dejen los archivos de config preparados en su repo cosa de que solo tengan que cambias las IPs en el laboratorio.

Saludos.-
