### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#4153]
Hola buenas queria preguntar como harian para ver los reemplazos de la TLB en las pruebas de memoria y TLB . Yo solo puse los logs obligatorios.
![image](https://github.com/user-attachments/assets/5c287cb0-3961-4c85-8a27-cfa67f6aca66)
Lo verian con los HITS y MISS de la TLB

**Comment by RaniAgus** [comment]
¡Buenas! Los veríamos con los logs de CPU:
![image](https://github.com/user-attachments/assets/84e3b008-24ba-4c91-97a7-c1bcae4657a2)
Y de Memoria:
![image](https://github.com/user-attachments/assets/d94666de-156a-4680-a24d-1dfbc29c6f52)

Saludos

**Comment by RaniAgus** [comment]
PD: Es correcto implementar **solamente** los logs obligatorios en un archivo:
![image](https://github.com/user-attachments/assets/9c9f8fcb-803a-42ba-8fc9-8f72dcf3f913)

Si necesitan agregar otros, asegúrense que queden en un archivo aparte o, alternativamente, ocúltenlos usando los niveles de logueo para que no se impriman en la prueba.
