### ISSUE TITLE
Problema Terminal Kernel

### ISSUE THREAD

**Issue by FedericoGSantoro** [sisoputnfrba/foro#4155]
Buenas, como están? Vengo con un problemita.
No se por que pero de vez en la terminal que ejecuta kernel se "rompe". Puedo seguir escribiendo pero no me muestra que se escribe, ejecuta sin problema de todas formas todo lo que le digas pero no entiendo por que pasaría esto, no se si es por un problema de hilos (tengo la consola interactiva en un hilo separado, no se si afecta). Para arreglarlo necesito reiniciar la consola completa y si es en la maquina virtual de ubuntu (sin interfaz grafica) creo que solo reiniciando la maquina virtual.
No se que contexto o que decirles para que puedan intentar ayudarme. 
Gracias!

### 🔎 Búsqueda en foros
No encontré algo que me ayude.

### 📝 Código relevante
No se que pegar.

### 🐛 Cómo reproducir el error
Si yo inicializo kernel y después hago un ctrl+c en cualquier momento para detenerla, es probable que se arruine la interfaz de la terminal.

**Comment by iago64** [comment]
Buenas! Cómo va?

Esto a veces puede pasar si justo se imprime algún caracter no imprimible y queda este como el último caracter impreso, por las dudas, si utilizas putty o algun cliente de ssh externo tambien te pasa?
Por otro lado, en el kernel por favor asegurate de tener puesto que los logs se manden a un archivo solamente, para evitarte que algun print del logger sea el que te complica las cosas.

Saludos.-

**Comment by FedericoGSantoro** [comment]
Buenas, todo bien.

Estamos probando en putty y se rompe, en la terminal de visual también.
Los logs los puse para que no se impriman en la terminal desde el inicio.
Acabo de pensar que podría ser que hay problema del hilo que ejecuta la consola, tipo, cuando hago ctrl+c que termine el hilo principal y que tenga conflicto al terminar el hilo de la consola y genere este problema. Podría ser posible?

**Comment by iago64** [comment]
Buenas! Cómo va?

Es posible que quede medio cruzada la consola, igual para la prueba lo que pueden abrir de ultima otra consola de putty entre prueba y prueba asi se quedan tranquilos de que siempre ven lo que se escribe :)

Saludos.-

**Comment by FedericoGSantoro** [comment]
Bueno genial gracias!
