### ISSUE TITLE
Tiempos

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#4156]
Hola buenas. Lo estoy probando en varias maquinas en mi casa y lo que me pasa es que a veces es como que funciona lento. Osea tengo kernel en una computadora y cuando hago Iniciar proceso es como que tarda en que en la otra maquina empiece a correr el proceso en cpu tampoco es que mucho pero unos dos o tres segundos. Esto es normal por estar probandolo asi? o deberia ser rapido?

**Comment by JoaquinCoaricona** [comment]
Recien me paso por ejemplo que en la prueba de desalojo de VRR me tenia que desalojar 3 veces y lo desaolojo 2. Pero ahora lo volvi a probar y funciona bien

**Comment by JoaquinCoaricona** [comment]
Se que estoy escribiendo mucho pero recien vi otra cosa. Es que yo levanto cpu y memoria en una computadora. En otra levanto kernel. Bueno recien levante kernel y tardo como 5 segundo en que me aparezca lo de que la consola esta disponible, es como que se pone lento en la conexion pero demora mucho.

**Comment by JoaquinCoaricona** [comment]
Sigo probando y me acaba de pasar que por 45 segundos se me congelaron todos los modulos, osea los 4 modulos se congelaron. Esto puede ser un tema de mi wifi? o deberia funcionar bien?

**Comment by iago64** [comment]
Buenas! Cómo va?

Si no sabemos que prueba estas ejecutando, es muy dificil que podamos darte alguna respuesta certera, con lo cual algunas respuestas que podemos dar en base a los 4 mensajes son:

1. Puede andar mal por el wifi? Si, mas si tenes poca señal en alguno de los dispositivos o si tenes al resto de tu familia usando wifi para otras cosas como ver streaming de video
2. Que la consola tarde en levantar puede depender tambien de como este la pc, si lo estas levantando en una pc con pocos recursos o un disco rigido mecanico muy lento podes ver que las cosas demoren mas
3. El tema de Quantums y demas, un poco mas de lo mismo, si tenes la red cargada, las maquinas que estan ahorcada de recursos lo mas probable es que tengas cuellos de botella por todos lados, si corrías todo en una sola máquina fisica pero con 2 virtuales te funcionaba bien?

Saludos.-

**Comment by JoaquinCoaricona** [comment]
No probe eso de las dos virtuales en una sola maquina. SI funciona bien ahi entonces funcionaria bien en la entrega?

**Comment by iago64** [comment]
Buenas! Como va?

No puedo garantizarte que ande bien, solo te digo que estas eliminado la problemática de una red lenta por estar sobrecargada.

Saludos.-
