### ISSUE TITLE
STDIN  guardado de texto

### ISSUE THREAD

**Issue by LainoRamiro** [sisoputnfrba/foro#4157]
Hola, quería consultarles por el tema de la Prueba de IO que no nos está resultando, pensamos que puede ser un tema del texto de si se debe guardar el /0 del texto en la memoria o no. Y si hay que tenerlo también en cuenta en el kernel y la CPU.
Saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

El '\0' no tienen que tenerlo en cuenta ni guardarlo en la memoria, lo que si no se olviden de agregarlo antes de imprimirlo para que no les explote.

Saludos.-

**Comment by LainoRamiro** [comment]
Listo entonces, muchas gracias! Saludos! :)
