### ISSUE TITLE
duda con semaforos

### ISSUE THREAD

**Issue by mSpadoni** [sisoputnfrba/foro#4159]
hola, podría usar semáforos para indicar que un modulo debe esperar a que otro termine su trabajo antes de continuar??, por ejemplo con resize en donde cpu tiene que esperar que memoria le mande ok o out of memory

y otra cosa mas, en el caso del copy string, podemos crear un caso especial en la función que utilizamos para ejecutar el move in y move out para no tener que hacer devuelta la traducción de DL a DF??

**Comment by iago64** [comment]
Buenas! Cómo va?

Estas teniendo en cuenta que los semáforos son algo que no podes compartirlos entre procesos que corren en **distintas máquinas**?

Para el caso de COPY_STRING, las traducciones tienen que estar si o si, tanto en SI como en DI tenes direcciones lógicas, tenes que traducirlas a físicas o vas a copiar cualquier cosa en cualquier lado.

Saludos.-

**Comment by mSpadoni** [comment]
´si estoy teniendo en cuenta que los semáforos no pueden estar en distintas maquinas, yo me refiero a que el semáforo se va activar justo después que el modulo (ej: cpu) reciba algo de otro modulo, pero todos los semaforos van estar en el mismo modulo 

```void ejecutar_resize(char tamanio [20]){
    t_buffer *un_buffer = crear_buffer();
    agregar_int_a_buffer(un_buffer, atoi(tamanio));
    agregar_uint32_a_buffer(un_buffer, pcb->pid);

    t_paquete *paquete = crear_super_paquete(AJUSTAR_TAMANIO, un_buffer);
    enviar_paquete(paquete, socket_memoria);

    eliminar_paquete(paquete);
}

void procesar_resultado_resize(char* resultado){
    if (strcmp(resultado, "Out of Memory") == 0)
    {
        pcb->motivo_exit = OUT_OF_MEMORY;
        t_buffer *buffer = crear_buffer();
        agregar_pcb_a_buffer(buffer, pcb);
        agregar_cop_a_buffer(buffer, CAMBIAR_ESTADO);
        agregar_estado_a_buffer(buffer, FINISH_ERROR);

        t_paquete *paquete = crear_super_paquete(ENVIO_PCB, buffer);
        enviar_paquete(paquete, socket_kernel_dispatch);

        eliminar_paquete(paquete);
    }
    else if (strcmp(resultado, "Ok") == 0)
    {
        log_info(cpu_logger, "RESIZE exitoso");
        aux_resize = 1;
        //
    }
    else
    {
        log_error(cpu_logger, "Registro invalido");
    }
}

case RESULTADO_AJUSTE_TAMAÑO_2:
            un_buffer = recibir_buffer(socket_memoria);
            char *resultado = extraer_string_de_buffer(un_buffer);
            procesar_resultado_resize(resultado);
            sem_post(&sem_resize);
            break;
```
algo asi por ejemplo (lo del case es una parte de otro codigo)

**Comment by mSpadoni** [comment]
si, estoy teniendo en cuenta que deben estar en la misma MV, yo a lo que me refiero es si puede haber un semáforos justo después que un modulo reciba algo de otro modulo, esto para indicarle que tiene que esperar a que el segundo modulo haga su trabajo para continuar, pero los semáforos van a estar todos en el mismo modulo

**Comment by iago64** [comment]
Buenas! Cómo va?

Si vos mandas algo a un módulo y tenes que esperar la respuesta, podes bloquearte en el `recv()` que es una función bloqueante, ya con eso te alcanzaría para esperar que el otro módulo haga lo que tenga que hacer.
Igual si estas teniendo en cuenta que no podes compartir semáforos entre pcs, listo, podes usar lo que consideres o lo que te resuelva el problema.

Saludos.-

**Comment by mSpadoni** [comment]
joya, muchísimas gracias
