### ISSUE TITLE
Duda con COPY_STRING

### ISSUE THREAD

**Issue by mSpadoni** [sisoputnfrba/foro#4162]
Hola buenas noches, una duda con COPY_STRING, este solo va leer de memoria valores que son string no?? ósea no existe la posibilidad que justo en la DF de SI haya un uint32 o uint8

**Comment by mefederico** [comment]
Hola buenas! 

Todos los datos de la memoria son bytes, ustedes no tienen porque saber que es lo que se esta escribiendo, lo que conocemos como "string" o mejor dicho `char` son unos números que están en un rango especifico (ascii table). 

Dejo unos comments donde esto se hablo: https://github.com/sisoputnfrba/foro/issues/3877#issuecomment-2156281836 https://github.com/sisoputnfrba/foro/issues/3998#issuecomment-2181402959

Saludos!

**Comment by mSpadoni** [comment]
gracias, y me agarro otra duda si yo guardo directamente unuint_32 en el espacio usuario y luego lo quiero leer como un string por esto mismo de que son no habría problema con hacer este pasaje, no? ósea en el espacio usuario no me tengo que encargar de pasar los a datos a bytes y recién ahí escribirlo, eso me lo hace memcpy.

**Comment by mSpadoni** [comment]
gracias

**Comment by f-and** [comment]
Buenas! No hay un pasaje explicito, solo almacenas 4 bytes en el espacio de usuario, y despues los lees. Si queres fijate las pruebas de IO en las cuales hacemos este tipo de juego pero con UInt8_t.
Saludos.-
