### ISSUE TITLE
Pregunta Helgrind

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#4163]
Hola buenas, helgrind me marco este error:
==6617== 
==6617== ----------------------------------------------------------------
==6617== 
==6617==  Lock at 0x118440 was first observed
==6617==    at 0x4854BFE: pthread_mutex_init (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==6617==    by 0x111EFC: initialize_queue_and_semaphore (long_term_scheduler.c:66)
==6617==    by 0x10AE0F: main (main.c:97)
==6617==  Address 0x118440 is 0 bytes inside data symbol "m_dispatch_kernel_Llegada_Procesos"
==6617== 
==6617==  Lock at 0x1182C0 was first observed
==6617==    at 0x4854BFE: pthread_mutex_init (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==6617==    by 0x111E84: initialize_queue_and_semaphore (long_term_scheduler.c:60)
==6617==    by 0x10AE0F: main (main.c:97)
==6617==  Address 0x1182c0 is 0 bytes inside data symbol "m_planificador_corto_plazo"
==6617== 
==6617== Possible data race during write of size 1 at 0x4B6AD45 by thread #3
==6617== Locks held: 1, at address 0x118440
==6617==    at 0x10C13F: fetch_pcb_actualizado (main.c:725)
==6617==    by 0x10B338: manage_request_from_dispatch (main.c:270)
==6617==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==6617==    by 0x4964AC2: start_thread (pthread_create.c:442)
==6617==    by 0x49F5A03: clone (clone.S:100)
==6617== 
==6617== This conflicts with a previous read of size 1 by thread #5
==6617== Locks held: 1, at address 0x1182C0
==6617==    at 0x48569BF: memcpy@GLIBC_2.2.5 (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==6617==    by 0x1132BA: add_to_packet (protocol.c:47)
==6617==    by 0x112F0E: enviar_proceso_cpu (short_term_scheduler.c:367)
==6617==    by 0x1126D2: planificador_corto_plazo_FIFO (short_term_scheduler.c:76)
==6617==    by 0x11250F: planificadorCortoPlazo (short_term_scheduler.c:13)
==6617==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==6617==    by 0x4964AC2: start_thread (pthread_create.c:442)
==6617==    by 0x49F5A03: clone (clone.S:100)
==6617==  Address 0x4b6ad45 is 21 bytes inside a block of size 48 alloc'd
==6617==    at 0x484A919: malloc (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==6617==    by 0x112F4A: initializePCB (short_term_scheduler.c:375)
==6617==    by 0x10BEDC: create_process (main.c:642)
==6617==    by 0x111BD8: levantar_consola (consola.c:44)
==6617==    by 0x10B0CE: main (main.c:162)
==6617==  Block was alloc'd by thread #1
==6617== 
==6617== ----------------------------------------------------------------

Segun lo que estuve averiguando quiere decir esto: 

Condición de carrera:

Escritura de tamaño 1 en 0x4B6AD45 por el hilo #3:

Bloque de memoria afectado: 21 bytes dentro de un bloque de 48 bytes asignado con malloc.
Ocurre en fetch_pcb_actualizado (línea 725, main.c).
Llamado por manage_request_from_dispatch (línea 270, main.c).
Bloque de memoria asignado en initializePCB (línea 375, short_term_scheduler.c).

Lectura de tamaño 1 en 0x4B6AD45 por el hilo #5:

Ocurre en memcpy en add_to_packet (línea 47, protocol.c).
Llamado por enviar_proceso_cpu (línea 367, short_term_scheduler.c).
Bloque de memoria asignado en initializePCB (línea 375, short_term_scheduler.c).

Yo tengo una variabe global del tipo estructura pcb, cuando creo un proceso le asigno los valores y despues cuando mando el proceso a cpu me guardo el puntero en una variable global de tipo puntero, cuando el proceso llega de cpu ahi se llama a la funcion de fetch pcb y se actualizan los valores del puntero global que tengo con lo que llego. Esto creo que funciona bien. Mi pregunta es si helgrind marco esta posible condicion de carrera porque vio que la lectura y escritura paso realmente al mismo tiempo o si lo marco porque cree que puede llegar a pasar. Porque me parece raro que crea que puede llegar a pasar porque las funciones se llaman en momentos distintos y creo que nunca al mismo tiempo. Desde ya muchas gracias

**Comment by karengrams** [comment]
¡Muy buenas @JoaquinCoaricona!

¿Cómo estas? Espero que muy bien. Partiendo un poco de la base de tu explicación, y no tanto sobre los logs de Halgrind, el hecho de que tengas una variable global que sea posiblemente accedida por dos procesos/hilos (o más), sin haber puesto un posible sémaforo o un método para un acceso más seguro, puede aumentar las chances de que tengas una condición de carrera. ¿Esto quiere decir que haya una condición de carrera? No necesariamente. Puede que en ningún momento de la ejecución de tus programas, se dio el peor de los escenarios (tocamos madera para que no pase). 

Vos mencionas que las funciones se llaman en momentos distintos, y que nunca al mismo tiempo; sin embargo, dejame retrucarte, que en tiempos de ejecución, los hilos son más rápidos de lo que pensamos (dentro del TP, hay bastantes y al momento de la ejecución de las pruebas finales, dejame decirte que vamos a probarlos a fondo) y a pesar de que nosotros pensamos que algo es secuencial, capaz en realidad no lo es. 
Y si tenemos una variable global, que puede en algún momento llegar a ser modificada y/o al mismo tiempo ser leida por otro proceso/hilo, entonces tenemos una condición de carrera.

> Recomiendo fuertemente que corran las pruebas finales para ver si tienen resultados erraticos (que a veces dan bien y otras veces dan mal). 

Ahora, respondiendo sobre lo de Helgrind, lo marco porque puede que en algún momento exista una condición de carrera y los resultados no sean los esperados.

Espero que esto haya respondido tu pregunta.

¡Nos vemos!

Kar.

**Comment by JoaquinCoaricona** [comment]
Hola buenas yo corri todas las pruebas varias veces y por ahora me dieron bien. Con lo de los tiempos, el llamado a las funciones es asi: Las dos funciones que nombra helgrind son las de envio  y recepcion del proceso. En la de envio me marca el problema en la funcion de agregar a paquete y al recibirlo me marca error en los memcpy. No hay un semaforo como tal porque mi idea era que cuando un hilo envia el proceso el otro esta bloqueado en la funcion bloqueante de socket esperando un mensaje. Entonces por eso yo pense que con esa sincronizacion estaria bien. Funcionaria asi: tengo un hilo que se queda escuchando el socket de conexion kernel cpu y otro que envia informacion por ahi. Al inciar el programa se envia el primer proceso a cpu y ese hilo queda trabado en un semaforo, este semaforo solo se habilita desde el otro hilo que esta bloqueado en la funcion bloqueante esperando el mensaje desde cpu, cuando llega de la cpu esta funcion que estaba esperando hace la recepcion y actualiza ese puntero global y recien una vez que termina de hacer eso habilita el semaforo de la otra para que envie otro si es que hay. Al hacerlo en tiempos distintos me parecio raro que helgrind lo marque como un posible error porque estan separados por una funcion bloqueante de sockets y ademas por ese semaforo que habilita el envio. 
Las pruebas ya las corri en una maquina sola, en una sola maquina con dos clonadas y en dos pc separadas. Tambien las corri en la prueba del sabado y al ser un proceso que se hace tantas veces crei que no iba a haber problemas por eso esto me parecio raro porque incluso como decia antes hay una funcion bloquente y tambien un semaforo aunque este semaforo no es directo sobre esa parte precisa de codigo

**Comment by karengrams** [comment]
¡Aló @JoaquinCoaricona!

Entiendo lo que comentas, que la función sea bloqueante no te asegura que otro hilo/proceso quiera acceder a las variables de utiliza la función, no se si me explique bien... en criollo, si bien la comunicación esta esperando a que nos devuelva algo el socket, tenes algo global que puede ser modificado en el medio y otro hilo/proceso lo puede leer antes o después de esa modificación, o incluso modificar, recordemos que nadie nos limita la modificación de las variables. 

En esto tienen que hacer ustedes, como grupo, un poco el trade-off (nota al pie de página: trade-off significa "sacrificar" o decidir algo, modificando las variables que tienen en juego, es este caso seria el tiempo y las probabilidades de que suceda la condición de carrera para que el comportamiento erratico pase) de que decisión tomar. La realidad es que nosotros no vamos a correr Halgrind en ningún momento ni tampoco Valgrind (aunque si vamos a prestar atención a los memory leaks, y a las condiciones de carrera que si se hagan presentes). 

Tal como te mencione, replicaria el escenario que se presentaria en la entrega de operativos (podes hacerlo con tus compañer@s con maquinas virtuales hosteadas en algun server en la nube, si no se pueden juntar, o si tienen dos computadoras, se contentan en una misma red).

¿Con esto queda un poquito más claro? ¡Quedo atenta!

Kar.

**Comment by JoaquinCoaricona** [comment]
Hola, yo corri las pruebas del tp en dos maquinas diferentes pero conectadas a la misma red, en mi casa. Pero eso de hosteadas en algun server en la nube no sabia que se podia hacer, tienen algun lugar para leer sobre eso? Porque busque pero no se si es la forma correcta. En la entrega tuve un error que  despues corriendolo en local no me paso nunca y tambien en dos masquinas separadas tampoco me paso, con eso de dos maquinas hosteadas en la nube se podria aproximar al nivel de lentitud del laboratorio de medrano?

**Comment by iago64** [comment]
Buenas! Cómo va?

De primera mano olvidate de hostear cosas en la nube, no es algo trivial y te podes complicar la existencia mas de lo que parece.
Respecto a como replicar el labo, bueno, hay 2 alternativas fáciles:

- La primera es ir a labo entre semana, en la semana del 15 al 20 de julio no es posible porque hay receso invernal y la facultad esta cerrada.
- La segunda opción mas accesible es teniendo 2 **máquinas fisicas distintas** con la VM server con el adaptador de red en modo bridge (puente) en una misma red y de ser posible conectadas por cable de red para evitarte los problemas de que la señal de WiFi te llegue medio al limite y tengas cortes en el medio.

Saludos.-

**Comment by JoaquinCoaricona** [comment]
Sisi tambien lo probe asi

**Comment by RaniAgus** [comment]
@JoaquinCoaricona sobre este comentario:

> 2. Yo lo probe asi muchas veces y me funciono aca pero en el laboratorio no me funciono

Es imposible que se deba al entorno ya que las VMs instaladas en el laboratorio son las mismas que les proveemos en el sitio de la cátedra.

Tanto correrlas en máquinas distintas dentro de la misma red, o en la misma máquina con 2 VMs clonadas debería ser suficiente para poder reproducir el entorno. Es justamente una de las razones principales por las cuales proveemos dichas VMs.

Asegúrense de seguir los mismos pasos que siguieron en la entrega dentro de las VMs server para poder reproducir el error.

Saludos

**Comment by JoaquinCoaricona** [comment]
Para ver si es de concurrencia deberia usar helgrind en la prueba que fallo no?

**Comment by RaniAgus** [comment]
Helgrind es una herramienta que te ayuda a determinar posibles condiciones de carrera, y pueden usarla para correr cualquier binario incluyendo el que compilaron para el TP en la VM server.

**Comment by JoaquinCoaricona** [comment]
Entonces para los problemas de concurrencia deberia hacerlo de otra forma? Debuggeando?

**Comment by iago64** [comment]
Buenas! Cómo va?

En resumen, si, debug y de ultima si tenes alguna situación de que dependiendo de la ejecución anda o no en un mismo proceso, ahi si usa helgrind en ese proceso a ver si no tenes una condición de carrera.
Igual repasando el issue, capaz un mutex "por las dudas" en donde te marco la primer condición de carrera del Kernel no estaría mal, sería mejor un poco mas de analisis, pero a priori, podes probar con eso.

Saludos.-

**Comment by JoaquinCoaricona** [comment]
Ok entiendo, igual el problema no fue en esto, fue en la prueba de LRU. Entonces lo tendria que probar unas cuantas veces en el laboratorio y ver que de bien en todas, no se si se puede dar un numero especifico pero en caso que haya problemas de concurrencia como me dijeron, que a veces funciona y falla, cuantas veces deberia probarlo aproximadamente? Yo voy a probarlo todas las que pueda pero para tener una base

**Comment by iago64** [comment]
Buenas! Cómo va?

Entonces recapitulando, tu problema no es con helgrind si no un problema de que la prueba de LRU no dió bien, eso es para verlo en otro issue pero sería bueno que eventualmente analices que fue lo que falló en la prueba y si no entendes como arreglarlo ahi abras el issue.

Saludos.-

**Comment by JoaquinCoaricona** [comment]
Ya analice lo que me fallo en la prueba y no encontre nada, p
