### ISSUE TITLE
RESIZE 0

### ISSUE THREAD

**Issue by ArielRotolo** [sisoputnfrba/foro#4164]
Buenas, tengo una duda con la instrucción mencionada corriendo la prueba de Salvation's Edge:

RESIZE 0: Significa asignar 0 bytes osea no hacer nada en la memoria, o significa borrar todas las paginas asignadas y dejar el proceso con 0 memoria?

**Comment by f-and** [comment]
Buenas! Efectivamente es lo segundo. RESIZE le asigna al proceso los bytes solicitados, ya sea restandole o agregandole bytes.
Saludos.-

**Comment by ArielRotolo** [comment]
Perfecto, muchas gracias!
