### ISSUE TITLE
Consulta de HTOP

### ISSUE THREAD

**Issue by Gaston-Erazo18** [sisoputnfrba/foro#4165]
Al correr la  Prueba Salvation's Edge, abrimos el HTOP, dejamos correr la prueba por un tiempo y  nos muestra la siguiente información.

![image](https://github.com/user-attachments/assets/71286077-0205-499e-81e8-692e47e1f226)

Queremos saber si la información mostrada es normal o esta bien. 
Saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

Por las dudas consulto, ¿Están corriendo desde la terminal de vecode? Porque eso puede estar sumandoles consumo de memoria, les recomiendo que corran los módulos directo desde una terminal.
De todas formas me preocupa un poco el proceso que les esta consumiendo un **200%** de CPU, a priori me da que pensar que tienen algunas esperas activas dando vueltas.

Saludos.-

**Comment by Gaston-Erazo18** [comment]
![image](https://github.com/user-attachments/assets/a5b58daf-f25a-469d-aa77-e58c6a66d659)
Lo volvimos a correr y ahora nos tira mas normal creo.

**Comment by iago64** [comment]
Buenas! Cómo va?

No se ve bien la captura y no logro identificar si estan corriendo los procesos, pero volviendo sobre la premisa de que las esperas activas son el uso de la CPU elevada y en el caso de la memoria, lo que tenes que ver es que no crezca el consumo de manera indiscriminada.
Las pruebas las corremos en la VM server justamente porque ahí no tenes tantos procesos que puedan estorbar.

Saludos.-

**Comment by Gaston-Erazo18** [comment]
OK, gracias por contestar, cierro issue :)
