### ISSUE TITLE
Desconexión de interfaces

### ISSUE THREAD

**Issue by ArielRotolo** [sisoputnfrba/foro#4167]
Buenas, estaba probando la desconexion de las interfaces y ocurre el problema de que al desconectarse una interfaz con ctrl-c no se cierra el socket correctamente con close() por lo que el sistema operativo tarda varios segundos o hasta 1 min en detectar y cerrar la conexión. Lo que provoca que ese minuto si el kernel comienza a ejecutar uno de los procesos que necesita esa interfaz inexistente no llegue a detectar la desconexión y rompa el programa.

Hay que tener en cuenta esto?

**Comment by iago64** [comment]
Buenas! Cómo va?

Esto es algo  que siempre tenemos en cuenta en las entregas y que sabemos que puede pasar, si es lo único que les queda del TP revisenlo, si no enfoquense en que el resto de cosas funcionen y si les sobra tiempo revisen esto.

Saludos.-

**Comment by ArielRotolo** [comment]
Genial, muchas gracias!
