### ISSUE TITLE
Detectar desconexion de IO con send

### ISSUE THREAD

**Issue by AgustinCarlanaRivero** [sisoputnfrba/foro#4168]
Hola, buenas. Para poder aplicar la desconexión de interfaces en tiempo de ejecución, decidí optar por evaluar lo que retorna el send a la interfaz. Sin embargo, por mas que este haciendo el send a una interfaz a la que le hice ctrl + c, send devuelve la cantidad de bytes enviados! Por lo que estuve viendo, debería retornar -1, pero nunca lo hace. También probe esperar 1 minuto luego de la desconexión (por si el problema era que no le daba tiempo suficiente al socket como para que se cerrase), pero tampoco anduvo.

### 📚 Documentación oficial
https://man7.org/linux/man-pages/man2/sendto.2.html

### 🔎 Búsqueda en foros
En el issue #3721 mencionan que habria que usar en el send la flag `SIGPIPE`, pero eso no figura como flag en la documentación del send. Imagino que capaz se referian a MSG_NOSIGNAL, pero probamos y sigue sin andar.

### 📝 Código relevante
```
ssize_t bytes = send(conexion, a_enviar, paquete->buffer->size + sizeof(uint32_t) + sizeof(uint32_t), MSG_NOSIGNAL);
if(bytes == -1){ // Nunca entra acá
	printf("Error en send: %s\n", strerror(errno));
	free(a_enviar);
	return -1;
}
```

**Comment by iago64** [comment]
Buenas! Cómo va?

Solo por preguntar, leiste la documentación oficial que citaste? Porque si te fijas, el flag de MSG_NOSGINAL dice lo siguiente:

> MSG_NOSIGNAL (since Linux 2.2)
              Don't generate a SIGPIPE signal if the peer on a stream-
              oriented socket has closed the connection.  The EPIPE
              error is still returned.  This provides similar behavior
              to using [sigaction(2)](https://man7.org/linux/man-pages/man2/sigaction.2.html) to ignore SIGPIPE, but, whereas
              MSG_NOSIGNAL is a per-call feature, ignoring SIGPIPE sets
              a process attribute that affects all threads in the
              process.

Con lo cual, si tenes ese flag en tu código, no vas a tener el SIGPIPE que comentamos en el issue que citas.

Saludos.-

**Comment by AgustinCarlanaRivero** [comment]
A ver, si, me parecia raro. Pensé "usar este flag no sería todo lo contrario?". Pero fue mas que nada por probar algo, porque originalmente llamaba al send sin ningún flag (o sea, 0), y no retornaba -1.

**Comment by iago64** [comment]
Buenas! Cómo va?

Es raro lo que comentas, porque de hecho en la misma doc te dice al final de los errores:

> EPIPE  
The local end has been shut down on a connection oriented socket.  In this case, the process will also receive a SIGPIPE unless MSG_NOSIGNAL is set.

Por las dudas como prueba, podes ver el tema de conectar una interfaz genérica, desconectarla y después correr un script que haga un llamado a esa interfaz debugueando el kernel para ver bien los valores que te retorna la función.

Saludos.-

**Comment by AgustinCarlanaRivero** [comment]
Es que es lo que probé, y me retorna exactamente la cantidad de bytes enviados. Para confirmar, hace falta esperar 1 minuto luego de desconectar la IO, no? Y algo que pensé que podría estar pasando es que de alguna forma el socket, pese a que espere mas de 1 minuto, no se desconecte.

**Comment by iago64** [comment]
Buenas!

Si, posiblemente si lo mastaste con Ctrl + C el SO al instante no te reconozca la caida del socket y por eso siga teniendo el buffer donde recibe los mensajes.

Saludos.-

**Comment by AgustinCarlanaRivero** [comment]
Bueno, no logro hacer que ande... Pese a esperar 1 minuto, y ver que onda los puertos con sudo lsof -i, cuando el send debería retornar -1 no lo hace. Podría encararlo de otra forma, pero me parece extraño que esto no ande. Explico el proceso de lo que hago:

1) Abro todos los modulos, incluida la IO.
2) Hago sudo lsof -i para ver los puertos
![image](https://github.com/user-attachments/assets/3cf5e036-12ad-4e68-bb0b-d55594a2a836)
Los ultimos 2 puertos son los de la IO (el de kernel y el de memoria)
3) Hago ctrl + c a la IO, y valgrind dice "Process terminating with default action of signal 2 (SIGINT)"
4) Espero 5 minutos y me fijo nuevamente los puertos
![image](https://github.com/user-attachments/assets/ff578f06-5f84-447b-98c8-a6cd40088ac5)
Me llama la atencion que digan CLOSE_WAIT un par.... Capaz sea por eso?
5) Ejecuto un script en kernel que llama a la IO en cuestión
6) En el debugger podemos ver que send no retorna -1, si no la cantidad de bytes supuestamente enviados a la interfaz que ya no existe.
![image](https://github.com/user-attachments/assets/014e40b8-9842-4dab-beff-d641d824d0e7)

Estoy en un punto muerto respecto a resolver esto, asi que desde ya gracias por la ayuda.

**Comment by iago64** [comment]
Buenas! Cómo va?

El CLOSE_WAIT lo que te dice es que está esperando que el SO cierre el socket, de todas formas, trata de no complicarte mucho, dejalo asi ya que en las pruebas en el único momento donde vamos a desconectar las cosas es en la prueba de FS.

Saludos.-

**Comment by AgustinCarlanaRivero** [comment]
Pero eso no significa que no nos va a salir bien esa prueba entonces?

**Comment by iago64** [comment]
Buenas! Cómo va?

Al contrario, la prueba de FS es la única donde se desconecta una interfaz intencionalmente, con lo cual si el único único problema del TP es ese sigan revisandolo pero si tienen otras cosas de las pruebas que no les pasan, enfoquense en eso.

Saludos.-

**Comment by AgustinCarlanaRivero** [comment]
Creo que llegamos a tiempo con todo, pero bueno, lo patearemos para adelante entonces... Saludos
