### ISSUE TITLE
PC en SET

### ISSUE THREAD

**Issue by tomassagrada** [sisoputnfrba/foro#4169]
Buenas, teníamos una pregunta sobre el PC, si es que deberíamos tenerlo en cuenta como un posible registro para instrucciones como SET, SUM, ETC. O si su valor solo va cambiando con el avance de las instrucciones y con JNZ. 

Desde ya gracias.

**Comment by iago64** [comment]
Buenas! Cómo va?

Si, al PC se lo puede setear con SET y en ese caso no tendrían que actualizarlo, de hecho en las pruebas lo usamos para tener loops infinitos.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Me sumo solo para agregar las citas al enunciado:
![image](https://github.com/user-attachments/assets/42e80609-e384-4a63-8e3d-769a7a215dcb)
![image](https://github.com/user-attachments/assets/bc19d507-9482-40c2-ba2f-092b2f0d63af)


Saludos

**Comment by tomassagrada** [comment]
Claro, mil disculpas. Gracias, una cosa sobre eso de no actualizarlo. Te réferis a que si por ejemplo el PC era 2 lo sumo a 3 y ejecuto a la instrucción SET queda por ejemplo en 5 y continuo a partir de ahí no?. Aprovecho para preguntar una cosita mas también que es si el PC debería inicializarse en 0 o 1, me genera duda por que en todos empieza en 1, pero hay un ejemplo de pruebas de procesos en que se lo SETEA al PC en 0, por lo que por ahí surgiría un error intentando después buscar la instrucción con PC en 0.

**Comment by RaniAgus** [comment]
> Gracias, una cosa sobre eso de no actualizarlo. Te réferis a que si por ejemplo el PC era 2 lo sumo a 3 y ejecuto a la instrucción SET queda por ejemplo en 5 y continuo a partir de ahí no?

Sí, misma respuesta que en: https://github.com/sisoputnfrba/foro/issues/3892#issuecomment-2158889332

> el PC debería inicializarse en 0 o 1, me genera duda por que en todos empieza en 1, pero hay un ejemplo de pruebas de procesos en que se lo SETEA al PC en 0, por lo que por ahí surgiría un error intentando después buscar la instrucción con PC en 0.

El PC (también llamado IP, Instruction Pointer) es un desplazamiento del inicio de las instrucciones, por lo que arranca en 0 como cualquier array. ¿A qué te referís con que "en todos empieza en 1"?

Saludos

**Comment by tomassagrada** [comment]
Nada ya me quedo claro con el otro issue, Graciasss.
