### ISSUE TITLE
LOG CPU escritrua/lectura

### ISSUE THREAD

**Issue by tomassagrada** [sisoputnfrba/foro#4170]
Buenas, en nuestro trabajo desde CPU se envía un array de direcciones físicas a memoria para que escriba o lea lo que se le indica. La pregunta era si en este LOG esta bien poner todas las direcciones físicas (suponiendo que es el caso en que hay mas de 1) en la parte que la pide?, una vez que memoria nos confirma que la lectura/escritura fue exitosa. 

### 📔 Citas del enunciado/videos
![image](https://github.com/user-attachments/assets/b1c897c8-ae44-44b4-9c6e-16157f6a8cb0)

**Comment by RaniAgus** [comment]
¡Buenas! Me parece bien cambiarlo para juntar todas las direcciones físicas y reconstruir el valor leído en un solo log solo desde el lado de CPU. Saludos

**Comment by tomassagrada** [comment]
Buenísimo, muchas gracias y un saludo.
