### ISSUE TITLE
Duda ejecutar script

### ISSUE THREAD

**Issue by AgustinaGuitman** [sisoputnfrba/foro#4171]
Buenas, estamos intentando correr el script PRUEBA_PLANI y tenemos problemas. Para los scripts hicimos una función que lea el archivo y vaya separando los distintos comandos cada vez que encuentra un salto de línea. Luego lo mandamos a una función para que  interprete cada comando del archivo y tome el código de operación y los parametros que necesita. El primer comando del script (en el caso de PRUEBA_PLANI sería INICIAR_PROCESO /scripts_memoria/PLANI_1) se interpreta y ejecuta bien pero el resto nunca llega a ser interpretado ni ejecutado. 
  

```c
void leer_consola(t_log* nada){ 
		while(conexiones<4);
		 printf("Ingresar un comando por consola: ");
		char* leido;
		leido = readline(">");

        t_comando* comando_leido;
        
        comando_leido = malloc(sizeof(t_comando));
        // creamos una lista y se la asignamos a parametros
        comando_leido->parametros = list_create();
        interpretar_c(comando_leido,leido);
        acciones_consola(comando_leido);
        
}

```

```c
 void interpretar_c(t_comando* comando_l, char* leido)
{
    char**leido_separado = string_split(leido," ");

    if(strcmp(leido_separado[0], "EJECUTAR_SCRIPT")==0){
        comando_l->cod_op = EJECUTAR_SCRIPT;
        //aca nos pasan el path
     
    }

    else if(strcmp(leido_separado[0], "INICIAR_PROCESO")==0){
        comando_l->cod_op = INICIAR_PROCESO;
        //aca nos pasan el path
        char* path = malloc(strlen(leido_separado[1])+1);
    
        printf("\n\nPRUEBA Cod op: %d path: %s\n\n", comando_l->cod_op, path);
    }
}
void acciones_consola(t_comando* comando_leido)
{
    
    switch(comando_leido->cod_op)
        {
            case EJECUTAR_SCRIPT:
       
                char* path_script = list_get(comando_leido->parametros,0);
				
                printf("%s\n",path_script_completo);
                interpretar_script(path_script_completo);
                
                break;
int interpretar_script(char* path_script)
{
    FILE *archivo;
    char *cadena;
    t_comando* comando_script;
    comando_script->parametros = list_create();
    
    // Abrimos archivo 
    // Leemos el archivo li­nea por linea y concatena las lineas en un solo string
     while(fgets(linea, MAX_LENGTH, archivo) != NULL && contador < MAX_LINES){
        strcat(cadena, linea);
        contador++;
    }

    fclose(archivo);

    // Utilizamos string_split para dividir la cadena por saltos de li­nea
 

	printf("Cantidad de comandos en el script: %d\n\n",contador);
    for (int i = 0; i < contador; i++) {
   
        interpretar_c(comando_script,lineas[i]); 
        //printf("%d) %s\n",i, lineas[i]);
        acciones_consola(comando_script);

	// Limpiamos los parámetros después de cada uso
        limpiar_parametros_comando(comando_script);
        free(lineas[i]); // pensamos que liberar una a una las lineas nos iban a solucionar el problema
    }

    // Liberamos la mem
    list_destroy(comando_script->parametros);
    free(comando_script);


 
}
```

**Comment by iago64** [comment]
Buenas! Cómo va?

Probaron debugueando el código viendo que valor tiene la variable `comando_script` que le pasan a la funcion `acciones_consola()`? Por otro lado si lo debuguearon y ven que los valores cambian, probaron con Valgrind a ver si entre todos esos `malloc()` y `free()` no estan liberando alguna dirección mal?

Saludos.-

**Comment by AgustinaGuitman** [comment]
Buenas! Perdón la tardanza pero estuvimos probando lo que nos dijiste y nos dimos cuenta que el problema es que cuando se hace el primer iniciar_proceso se deja de leer los otros comandos del script. Probamos modificando el script para que quede así 
```
MULTIPROGRAMACION 4 
INICIAR_PROCESO /scripts_memoria/PLANI_1
```

e hizo el cambio de multiprogramción y después inició con el proceso. Creo que estamos teniendo el problema que se esta leyendo y espera a la finalización de ese comando para leer el próximo, no sabemos si la solución es usar hilos o si hay alguna otra opción. 
Desde ya muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

La opción de crear un hilo no es mala, pero pueden esperar que termienen el comando anterior antes de ejecutar el siguiente, de todas formas el INICIAR_PROCESO, solo deberían hacer eso, iniciarlo y nada mas, una vez iniciado pasan al siguiente comando.

Saludos.-

**Comment by AgustinaGuitman** [comment]
Buenas, ahí anduvo. Mil gracias!
