### ISSUE TITLE
duda con la planificacion

### ISSUE THREAD

**Issue by mSpadoni** [sisoputnfrba/foro#4173]
hola buenas tardes, puede llegar a ocurrir que un proceso nuevo se cree mientras se este ejecutando una planificación o siempre van a terminar la planificación antes que se cree un nuevo proceso??

**Comment by RaniAgus** [comment]
¡Buenas! En el enunciado no se especifica ninguna restricción al comando `INICIAR_PROCESO`, por lo tanto, ¿por qué no se podría? Saludos

**Comment by mSpadoni** [comment]
ok, gracias
