### ISSUE TITLE
Problema al hacer memcheck

### ISSUE THREAD

**Issue by moracontreras** [sisoputnfrba/foro#4174]
Hola! Todo bien? Al hacer make memcheck en memoria, cpu y kernel todo anda bien, pero al hacerlo en entradasalida me salen los errores que están a continuación. Estuve leyendo y por lo que entendí podría ser algo de permisos de la VM. 

![Imagen de WhatsApp 2024-07-17 a las 21 15 33_dafce704](https://github.com/user-attachments/assets/47009949-1432-44cf-8360-e6ee3aee8a0c)

**Comment by RaniAgus** [comment]
¡Buenas! Se me complica muchísimo saber qué puede haber salido mal sin ningún contexto sobre el código.

¿De dónde puede haber salido ese mensaje de "Error al crear..."? 

Saludos

**Comment by moracontreras** [comment]
Sinceramente no tengo idea, hay algún pedazo de código específico que pueda enviarte que te de a entender el contexto?

**Comment by RaniAgus** [comment]
¿De dónde puede haber salido ese mensaje de "Error al crear..."?

**Comment by f-and** [comment]
Buenas, me meto solo para consultar, si ejecutas un I/O sin el makefile, osea con `./bin/entradasalida`, te tira el mismo error? Porque por los logs que pasaste, parece que es algo dentro del mismo código de entradasalida, y no algo externo como sería el memcheck o el start.

**Comment by moracontreras** [comment]
Al ejecutar IO desde el visual, desde run and debug no me tira errores, me los tira solo al hacerlo con makefile. Sin embargo, probe en la terminal haciendolo como me dijiste y me devuelve esto
![image](https://github.com/user-attachments/assets/9e5a206c-9ca5-4838-a0c4-3cb7812ebd11)
Respecto a lo de "Error al crear..." lo busqué en todos los archivos y no está. 
![Imagen de WhatsApp 2024-07-17 a las 23 30 49_b5cb78fe](https://github.com/user-attachments/assets/43786a7d-6423-4a99-8bb9-9d694739e832)

**Comment by RaniAgus** [comment]
Veo dos líneas en hello.c que dicen "Error al crear" y reciben una variable por parámetro. ¿Hay alguna de ellas que se esté llamando desde el main de IO?

**Comment by moracontreras** [comment]
Interpreté que debía buscar algo que dijera LESSOPEN como dice el error inicial. Esas dos líneas a las que haces referencia corresponden al logger y al config. Ambas están en funciones que son llamadas en el main de los cuatro módulos. 
![image](https://github.com/user-attachments/assets/d164bc3c-3477-4664-b044-d9f7150a2ddd)

**Comment by RaniAgus** [comment]
¡Buenísimo! ¿De dónde viene la variable `modulo`? Es decir, ¿qué están pasando ahí?

**Comment by moracontreras** [comment]
O sea en realidad en la del config se pasa una ruta recibida por parámetro y en la del logger es directo el nombre del archivo
![image](https://github.com/user-attachments/assets/8540db94-c641-4733-8e58-5ff8f59c3c44)

**Comment by RaniAgus** [comment]
Ok, entonces al ejecutar desde la consola deberías pasarle los parámetros a main de la misma forma que tu compañero/a lo haya hecho siguiendo la guía de argumentos para main: https://docs.utnso.com.ar/guias/programacion/main

Para usar Valgrind pueden pasar los mismos argumentos de la forma que está explicada en la guía de Valgrind:  https://docs.utnso.com.ar/guias/herramientas/valgrind#%C2%A1buenisimo-%C2%BFcomo-lo-compro

Creo que podíamos haber evitado tantas vueltas si primero se consultaran entre compañeros de equipo, ya que es su código, por lo que saben cómo interpretarlo mucho mejor que nosotros (que necesitamos de varios fragmentos para poder entender el contexto y recién ahí dar con el clavo de dónde puede estar el problema).

Saludos

**Comment by moracontreras** [comment]
Disculpame, lo hablé con mis compañeros y ninguno de nosotros logramos llegar a esa conclusión. Estamos acostumbrados a ejecutar con run y debug y esos parametros los tengo en el jason. 
Gracias!

**Comment by iago64** [comment]
Buenas!

Creo que es importante que me sume a este issue, porque por lo que vengo revisando hay varias cosas importantes, los ayudantes entendemos que estamos en la recta final del cuatrimestre, estan poniendole toda la garra para poder terminar el TP, pero por favor, ayudenos a ayudarlos, esto incluye desde dar el contexto necesario en los issues hasta **no subir capturas de código** ya que en este caso mas o menos las cosas se podían entender porque era poco, pero si llegan a tener algun problema con más código con capturas no podemos hacer copy-paste para probarlo nosotros.

Saludos.-

**Comment by RaniAgus** [comment]
¡De nada! Avísennos si lo pudieron ejecutar y, de ser así, siéntanse libres de cerrar el issue
