### ISSUE TITLE
Duda sobre memoria

### ISSUE THREAD

**Issue by ElielBejar** [sisoputnfrba/foro#4175]
Buenas! Estabamos cerrando el tp y me surgió una duda cuando estabamos haciendo las pruebas ¿Está mal guardar en memoria las cosas como char (respetando los marcos y lo que dice el tp) y usar funciones como memcpy para guardar la información? El espacio de memoria está dado por un void*.

Desde ya gracias!!

**Comment by iago64** [comment]
Buenas! Cómo va?

Una pregunta importante, si lo guardan como char, como van a hacer con los números? La idea de que sea un `void*` es que no tengan que "pensar" en tipos de dato.

Saludos.-

**Comment by AAMazzini03** [comment]
void escribir_memoria(int socket_cliente, int direccion_fisica, char* info, int pid){

	int tamanio_pagina = atoi(memoria_config.tam_pagina);
	int tamanio = strlen(info);
    int tamanio_escribir = tamanio;
	int desplazamiento = direccion_fisica % tamanio_pagina;
	bool hubo_error = false;

	int marco = direccion_fisica / tamanio_pagina;

	sem_wait(&sem_mutex_memoria);

	while (tamanio > 0) {

		if (marco >= 0){
			
			// calculo el espacio disponible en la página actual y veo
			// los bytes que tengo que escribir
			int espacio_disponible = tamanio_pagina - desplazamiento;
			int bytes_a_escribir = tamanio < espacio_disponible ? tamanio : espacio_disponible;
			
			// escribo los bytes en la memoria
			char* registro = string_duplicate(info);
			memcpy(espacio_memoria + (marco * tamanio_pagina) + desplazamiento, registro, bytes_a_escribir);
			free(registro);
			
			// avanzo en el puntero los bytes ya escritos en memoria
			info += bytes_a_escribir;
			
			// actualizo los contadores
			tamanio -= bytes_a_escribir;
			desplazamiento = 0;

			if(tamanio > 0) {
				int marco_aux = obtener_siguiente_marco(pid, marco);
				//log_info(logger, "PID: %d - marco_act: %d - marco_sig: %d", pid, marco, marco_aux);
				marco = marco_aux;
			}

		} else if (marco == -1) {
			
			// ocurrio un error al buscar el marco
            hubo_error = true;
            break;
        }
		
	}
	
	sem_post(&sem_mutex_memoria);

	if (hubo_error) {
		log_error(logger, "Error obteniendo el marco para el PID %d, MARCO %d", pid, marco);
		enviar_mensaje("OUT_OF_MEMORY", socket_cliente);
    } else {
		log_info(logger, "PID: %d - Accion: ESCRIBIR - Direccion fisica: %d - Tamanio: %d",pid, direccion_fisica, tamanio_escribir);
		enviar_mensaje("OK", socket_cliente);
	}
}

lo hicimos así, cuando cpu manda a guardar un numero se transforma ese numero a un string y se lo guarda. Funcionar funciona por que pasa todas las pruebas, pero nos entro la duda de que este mal conceptualmente. Todo se guarda en espacio_memoria que es un void*.

**Comment by iago64** [comment]
Buenas! Cómo va?

Esta mal, porque si grabamos un número mayor a 9999, en lugar de ocupar 4 bytes, van a ocupar 5 o mas.

Saludos.-

**Comment by AAMazzini03** [comment]
ok gracias

**Comment by RaniAgus** [comment]
¡Buenas! Paso a patrullar para avisar (para la próxima) que si la duda ya fue resuelta pueden cerrar el issue 👮🏻‍♂️

Si en un futuro ven que algo no terminó de cuadrar pueden tomarse la libertad de abrir uno nuevo referenciando éste. 

¡Saludos!
