### ISSUE TITLE
Promocion del TP

### ISSUE THREAD

**Issue by IanR4** [sisoputnfrba/foro#4176]
Buenas, se que no es la etiqueta adecuada pero no hay una que se adapte a mi duda. La consulta es que cuando dimos el coloquio, el profesor no nos dio una nota numerica, solo dijo que estamos aprobado y no se si con eso alcanza para promocionar la materia (tengo los dos parciales con mas de 8).  
Hable con un compañero y a ellos les preguntaron antes de dar el coloquio si estaban para promocionar o no, cosa que a nosotros no nos pregunto. 

### 📔 Citas del enunciado/videos
>Para la promoción de la materia, además de los requerimientos de la parte teórica de la materia, el mismo deberá aprobar el trabajo práctico con una nota final de 8 (ocho) o superior en la instancia de coloquio.
>
Sacado en el regimen de promocion de las normas del trabajo practico.

**Comment by RaniAgus** [comment]
¡Buenas! Para consultas administrativas pueden enviarnos un mail a inscripciones@utnso.com.ar

Saludos
