### ISSUE TITLE
Duda Prueba Planificación

### ISSUE THREAD

**Issue by yaanel** [sisoputnfrba/foro#4177]
Buenas! Tengo una pregunta acerca de la Prueba Planificación en el momento que hay que probar con VRR.  Se menciona que se deben finalizar los 3 procesos y "finalizar la prueba". Quería preguntar si antes de finalizar la prueba habría que finalizar el proceso PLANI_4. 
Si no hay que finalizar el proceso PLANI_4 y hay que hacerlo directamente finalizando la prueba: yo al tocar enter en la consola de Kernel para finalizar la prueba, CPU y Memoria siguen corriendo. ¿Esto debería ser así? O deberían terminar todos los módulos en conjunto.
Gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Esto es como regla general, cuando decimos _finalizar la prueba_ nos referimos a matar todos los módulos.

Saludos.-

**Comment by yaanel** [comment]
Gracias por responder! Pero me surgió una duda, al matar el módulo Kernel, finaliza Kernel pero sigue ejecutándose CPU y Memoria. ¿Alcanza con hacer Ctrl+C en las consolas de CPU y Memoria respectivamente o al finalizar Kernel deberían finalizar CPU y Memoria también?

**Comment by iago64** [comment]
Buenas! Cómo va?

Con hacer `Ctrl + C` en cada consola alcanza.

Saludos.-

**Comment by yaanel** [comment]
Perfecto!! Muchísimas gracias, cierro el issue :D
