### ISSUE TITLE
Resultado  Prueba

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#4178]
Hola buenas, queria preguntar por esta prueba.
![image](https://github.com/user-attachments/assets/848cf7c6-79e9-45c7-b41f-377df6478375)

Seria dentro de la prueba de Memoria y TLB. La primera de las pruebas con LRU. 

Queria preguntar si esto que se imprime en cpu es el resultado esperado. Hice el ejercicio a mano, pero por las dudas queria verificar que este bien porque yo estoy tomando esto como lo esperado. Deje solo los logs que tienen que ver con la TLB

[INFO] 21:15:18:888 CPU/(3465:3465): PID: 0 - TLB MISS - Pagina: 0
[INFO] 21:15:19:893 CPU/(3465:3465): PID: 0 - TLB MISS - Pagina: 1
[INFO] 21:15:20:918 CPU/(3465:3465): PID: 0 - TLB MISS - Pagina: 2
[INFO] 21:15:21:922 CPU/(3465:3465): PID: 0 - TLB MISS - Pagina: 3

[INFO] 21:15:23:928 CPU/(3465:3465): PID: 0 - TLB HIT - Pagina: 1
[INFO] 21:15:24:929 CPU/(3465:3465): PID: 0 - TLB HIT - Pagina: 2

[INFO] 21:15:28:951 CPU/(3465:3465): PID: 0 - TLB MISS - Pagina: 4
[INFO] 21:15:29:955 CPU/(3465:3465): PID: 0 - TLB MISS - Pagina: 5

[INFO] 21:15:34:974 CPU/(3465:3465): PID: 0 - TLB HIT - Pagina: 1
[INFO] 21:15:35:976 CPU/(3465:3465): PID: 0 - TLB HIT - Pagina: 2

[INFO] 21:15:36:980 CPU/(3465:3465): PID: 0 - TLB MISS - Pagina: 6
[INFO] 21:15:37:982 CPU/(3465:3465): PID: 0 - TLB MISS - Pagina: 7

**Comment by iago64** [comment]
Buenas! cómo va?

Pareciera estar bien, sería mas útil tener el log completo, pero la diferencia entre FIFO y LRU radica en que hay mas hits en LRU que en FIFO.

Saludos.-

**Comment by JoaquinCoaricona** [comment]
Hola buenas, aca esta el log completo, crei que el anterior iba a ser mas claro. Lo mando porque queria estar seguro que esta bien porque es la prueba en la que me fue mal en la primer entrega. Desde ya muchas gracias

[INFO] 01:25:28:200 CPU/(3647:3647): Fetch Instrucción: PID: 0 - FETCH - Program Counter: 1
[INFO] 01:25:28:278 CPU/(3647:3647): Instrucción Ejecutada: PID: 0 - Ejecutando: SET - AX 0
[INFO] 01:25:29:279 CPU/(3647:3647): Fetch Instrucción: PID: 0 - FETCH - Program Counter: 2
[INFO] 01:25:29:279 CPU/(3647:3647): Instrucción Ejecutada: PID: 0 - Ejecutando: SET - BX 1
[INFO] 01:25:30:282 CPU/(3647:3647): Fetch Instrucción: PID: 0 - FETCH - Program Counter: 3
[INFO] 01:25:30:282 CPU/(3647:3647): Instrucción Ejecutada: PID: 0 - Ejecutando: SET - CX 2
[INFO] 01:25:31:283 CPU/(3647:3647): Fetch Instrucción: PID: 0 - FETCH - Program Counter: 4
[INFO] 01:25:31:283 CPU/(3647:3647): Instrucción Ejecutada: PID: 0 - Ejecutando: SET - DX 3
[INFO] 01:25:32:284 CPU/(3647:3647): Fetch Instrucción: PID: 0 - FETCH - Program Counter: 5
[INFO] 01:25:32:284 CPU/(3647:3647): Instrucción Ejecutada: PID: 0 - Ejecutando: SET - EAX 0
[INFO] 01:25:33:290 CPU/(3647:3647): Fetch Instrucción: PID: 0 - FETCH - Program Counter: 6
[INFO] 01:25:33:291 CPU/(3647:3647): Instrucción Ejecutada: PID: 0 - Ejecutando: SET - EBX 32
[INFO] 01:25:34:291 CPU/(3647:3647): Fetch Instrucción: PID: 0 - FETCH - Program Counter: 7
[INFO] 01:25:34:291 CPU/(3647:3647): Instrucción Ejecutada: PID: 0 - Ejecutando: SET - ECX 64
[INFO] 01:25:35:292 CPU/(3647:3647): Fetch Instrucción: PID: 0 - FETCH - Program Counter: 8
[INFO] 01:25:35:292 CPU/(3647:3647): Instrucción Ejecutada: PID: 0 - Ejecutando: SET - EDX 96
[INFO] 01:25:36:294 CPU/(3647:3647): Fetch Instrucción: PID: 0 - FETCH - Program Counter: 9
[INFO] 01:25:36:294 CPU/(3647:3647): Instrucción Ejecutada: PID: 0 - Ejecutando: RESIZE - 128
[INFO] 01:25:37:297 CPU/(3647:3647): Fetch Instrucción: PID: 0 - FETCH - Program Counter: 10
[INFO] 01:25:37:298 CPU/(3647:3647): Instrucción Ejecutada: PID: 0 - Ejecutando: MOV_OUT - EAX AX
[INFO] 01:25:37:298 CPU/(3647:3647): PID: 0 - TLB MISS - Pagina: 0
[INFO] 01:25:37:298 CPU/(3647:3647): Obtener Marco: PID: 0 - OBTENER MARCO - Página: 0 - Marco: 0
[INFO] 01:25:37:298 CPU/(3647:3647): PID: <0> - Acción: ESCRIBIR - Dirección Física: 0 - Valor: 0
[INFO] 01:25:38:299 CPU/(3647:3647): Fetch Instrucción: PID: 0 - FETCH - Program Counter: 11
[INFO] 01:25:38:299 CPU/(3647:3647): Instrucción Ejecutada: PID: 0 - Ejecutando: MOV_OUT - EBX AX
[INFO] 01:25:38:299 CPU/(3647:3647): PID: 0 - TLB MISS - Pagina: 1
[INFO] 01:25:38:299 CPU/(3647:3647): Obtener Marco: PID: 0 - OBTENER MARCO - Página: 1 - Marco: 1
[INFO] 01:25:38:301 CPU/(3647:3647): PID: <0> - Acción: ESCRIBIR - Dirección Física: 32 - Valor: 0
[INFO] 01:25:39:302 CPU/(3647:3647): Fetch Instrucción: PID: 0 - FETCH - Program Counter: 12
[INFO] 01:25:39:302 CPU/(3647:3647): Instrucción Ejecutada: PID: 0 - Ejecutando: MOV_OUT - ECX AX
[INFO] 01:25:39:302 CPU/(3647:3647): PID: 0 - TLB MISS - Pagina: 2
[INFO] 01:25:39:302 CPU/(3647:3647): Obtener Marco: PID: 0 - OBTENER MARCO - Página: 2 - Marco: 2
[INFO] 01:25:39:303 CPU/(3647:3647): PID: <0> - Acción: ESCRIBIR - Dirección Física: 64 - Valor: 0
[INFO] 01:25:40:309 CPU/(3647:3647): Fetch Instrucción: PID: 0 - FETCH - Program Counter: 13
[INFO] 01:25:40:309 CPU/(3647:3647): Instrucción Ejecutada: PID: 0 - Ejecutando: MOV_OUT - EDX AX
[INFO] 01:25:40:309 CPU/(3647:3647): PID: 0 - TLB MISS - Pagina: 3
[INFO] 01:25:40:310 CPU/(3647:3647): Obtener Marco: PID: 0 - OBTENER MARCO - Página: 3 - Marco: 3
[INFO] 01:25:40:310 CPU/(3647:3647): PID: <0> - Acción: ESCRIBIR - Dirección Física: 96 - Valor: 0
[INFO] 01:25:41:347 CPU/(3647:3647): Fetch Instrucción: PID: 0 - FETCH - Program Counter: 14
[INFO] 01:25:41:348 CPU/(3647:3647): Instrucción Ejecutada: PID: 0 - Ejecutando: SET - DX 64
[INFO] 01:25:42:351 CPU/(3647:3647): Fetch Instrucción: PID: 0 - FETCH - Program Counter: 15
[INFO] 01:25:42:351 CPU/(3647:3647): Instrucción Ejecutada: PID: 0 - Ejecutando: MOV_IN - BX EBX
[INFO] 01:25:42:351 CPU/(3647:3647): PID: 0 - TLB HIT - Pagina: 1
[INFO] 01:25:42:356 CPU/(3647:3647): PID: <0> - Acción: LEER - Dirección Física: 32 - Valor: 0
[INFO] 01:25:43:358 CPU/(3647:3647): Fetch Instrucción: PID: 0 - FETCH - Program Counter: 16
[INFO] 01:25:43:358 CPU/(3647:3647): Instrucción Ejecutada: PID: 0 - Ejecutando: MOV_IN - CX ECX
[INFO] 01:25:43:358 CPU/(3647:3647): PID: 0 - TLB HIT - Pagina: 2
[INFO] 01:25:43:359 CPU/(3647:3647): PID: <0> - Acción: LEER - Dirección Física: 64 - Valor: 0
[INFO] 01:25:44:361 CPU/(3647:3647): Fetch Instrucción: PID: 0 - FETCH - Program Counter: 17
[INFO] 01:25:44:361 CPU/(3647:3647): Instrucción Ejecutada: PID: 0 - Ejecutando: RESIZE - 256
[INFO] 01:25:45:363 CPU/(3647:3647): Fetch Instrucción: PID: 0 - FETCH - Program Counter: 18
[INFO] 01:25:45:363 CPU/(3647:3647): Instrucción Ejecutada: PID: 0 - Ejecutando: SET - EAX 128
[INFO] 01:25:46:366 CPU/(3647:3647): Fetch Instrucción: PID: 0 - FETCH - Program Counter: 19
[INFO] 01:25:46:366 CPU/(3647:3647): Instrucción Ejecutada: PID: 0 - Ejecutando: SET - EBX 160
[INFO] 01:25:47:367 CPU/(3647:3647): Fetch Instrucción: PID: 0 - FETCH - Program Counter: 20
[INFO] 01:25:47:368 CPU/(3647:3647): Instrucción Ejecutada: PID: 0 - Ejecutando: MOV_OUT - EAX DX
[INFO] 01:25:47:368 CPU/(3647:3647): PID: 0 - TLB MISS - Pagina: 4
[INFO] 01:25:47:368 CPU/(3647:3647): Obtener Marco: PID: 0 - OBTENER MARCO - Página: 4 - Marco: 4
[INFO] 01:25:47:369 CPU/(3647:3647): PID: <0> - Acción: ESCRIBIR - Dirección Física: 128 - Valor: 64
[INFO] 01:25:48:373 CPU/(3647:3647): Fetch Instrucción: PID: 0 - FETCH - Program Counter: 21
[INFO] 01:25:48:374 CPU/(3647:3647): Instrucción Ejecutada: PID: 0 - Ejecutando: MOV_OUT - EBX DX
[INFO] 01:25:48:374 CPU/(3647:3647): PID: 0 - TLB MISS - Pagina: 5
[INFO] 01:25:48:374 CPU/(3647:3647): Obtener Marco: PID: 0 - OBTENER MARCO - Página: 5 - Marco: 5
[INFO] 01:25:48:376 CPU/(3647:3647): PID: <0> - Acción: ESCRIBIR - Dirección Física: 160 - Valor: 64
[INFO] 01:25:49:378 CPU/(3647:3647): Fetch Instrucción: PID: 0 - FETCH - Program Counter: 22
[INFO] 01:25:49:378 CPU/(3647:3647): Instrucción Ejecutada: PID: 0 - Ejecutando: SET - EAX 40
[INFO] 01:25:50:379 CPU/(3647:3647): Fetch Instrucción: PID: 0 - FETCH - Program Counter: 23
[INFO] 01:25:50:379 CPU/(3647:3647): Instrucción Ejecutada: PID: 0 - Ejecutando: SET - EBX 80
[INFO] 01:25:51:381 CPU/(3647:3647): Fetch Instrucción: PID: 0 - FETCH - Program Counter: 24
[INFO] 01:25:51:381 CPU/(3647:3647): Instrucción Ejecutada: PID: 0 - Ejecutando: SET - ECX 192
[INFO] 01:25:52:385 CPU/(3647:3647): Fetch Instrucción: PID: 0 - FETCH - Program Counter: 25
[INFO] 01:25:52:385 CPU/(3647:3647): Instrucción Ejecutada: PID: 0 - Ejecutando: SET - EDX 224
[INFO] 01:25:53:387 CPU/(3647:3647): Fetch Instrucción: PID: 0 - FETCH - Program Counter: 26
[INFO] 01:25:53:387 CPU/(3647:3647): Instrucción Ejecutada: PID: 0 - Ejecutando: MOV_OUT - EAX DX
[INFO] 01:25:53:387 CPU/(3647:3647): PID: 0 - TLB HIT - Pagina: 1
[INFO] 01:25:53:388 CPU/(3647:3647): PID: <0> - Acción: ESCRIBIR - Dirección Física: 40 - Valor: 64
[INFO] 01:25:54:390 CPU/(3647:3647): Fetch Instrucción: PID: 0 - FETCH - Program Counter: 27
[INFO] 01:25:54:390 CPU/(3647:3647): Instrucción Ejecutada: PID: 0 - Ejecutando: MOV_OUT - EBX DX
[INFO] 01:25:54:390 CPU/(3647:3647): PID: 0 - TLB HIT - Pagina: 2
[INFO] 01:25:54:391 CPU/(3647:3647): PID: <0> - Acción: ESCRIBIR - Dirección Física: 80 - Valor: 64
[INFO] 01:25:55:393 CPU/(3647:3647): Fetch Instrucción: PID: 0 - FETCH - Program Counter: 28
[INFO] 01:25:55:393 CPU/(3647:3647): Instrucción Ejecutada: PID: 0 - Ejecutando: MOV_OUT - ECX DX
[INFO] 01:25:55:393 CPU/(3647:3647): PID: 0 - TLB MISS - Pagina: 6
[INFO] 01:25:55:393 CPU/(3647:3647): Obtener Marco: PID: 0 - OBTENER MARCO - Página: 6 - Marco: 6
[INFO] 01:25:55:394 CPU/(3647:3647): PID: <0> - Acción: ESCRIBIR - Dirección Física: 192 - Valor: 64
[INFO] 01:25:56:396 CPU/(3647:3647): Fetch Instrucción: PID: 0 - FETCH - Program Counter: 29
[INFO] 01:25:56:396 CPU/(3647:3647): Instrucción Ejecutada: PID: 0 - Ejecutando: MOV_OUT - EDX DX
[INFO] 01:25:56:396 CPU/(3647:3647): PID: 0 - TLB MISS - Pagina: 7
[INFO] 01:25:56:397 CPU/(3647:3647): Obtener Marco: PID: 0 - OBTENER MARCO - Página: 7 - Marco: 7
[INFO] 01:25:56:397 CPU/(3647:3647): PID: <0> - Acción: ESCRIBIR - Dirección Física: 224 - Valor: 64

**Comment by RaniAgus** [comment]
¡Buenas! Si resolvieron el ejercicio a mano y les dio bien, pueden estar tranquilos en que les dio bien 😌 

Si encuentran alguna discrepancia o algún resultado que no coincida con el esperado, traten de analizar el motivo por el cual les dio distinto. Si no encuentran forma de solucionarlo, recién ahí suban un issue con la duda y el análisis que hayan hecho y con gusto les ayudamos.

Este foro es para ayudarlos con dudas puntuales, no para recibir resultados y determinar si son correctos o no.

Saludos

**Comment by JoaquinCoaricona** [comment]
Buenas. No es que no haya hecho el analisis, lo hice varias veces. Esta prueba es en la que me desaprobaron en la primer entrega, en el momento no me acordaba mucho de LRU asi que lo deje para revisar en casa. Al volver a probarlo en casa me dio este resultado y despues de probarlo varias veces de distintas formas me dio el mismo resultado que coincide con lo que hice a mano. Desde la entrega no cambie codigo en esa parte y me sigue dando lo mismo. Por eso queria saber si esto estaba bien o no. Saludos

**Comment by JoaquinCoaricona** [comment]
Yo creia lo mismo cuando se estaba ejecutando y por las dudas le pregunte al ayudante si me dejaba ver el config, hice cat y estaba puesto LRU
