### ISSUE TITLE
Comandos en consola entrecortados

### ISSUE THREAD

**Issue by facutomasetti** [sisoputnfrba/foro#4179]
Buenas, tengo una duda sobre la consola interactiva. Cuando inicio un proceso, empieza a correr normalmente en la consola. Pero cuando quiero escribir un nuevo comando se escribe entrecortado. De todos modos, al terminar de escribir el comando y darle "enter" lo ejecuta sin ningún problema. Es decir, cumple con la función pero no se ve bien. 
Una posible causa del problema es que los logs de la ejecución del proceso se escriben en la misma pantalla que la de los comandos. Una posible solución sería crear una consola sola para los comandos? 

Adjunto foto de cómo se ve en la terminal. 
![consola](https://github.com/user-attachments/assets/a935d9e6-a1f3-45f7-99f1-c470b2880026)

**Comment by iago64** [comment]
Buenas! Cómo va?

Eso es porque estas imprimiendo los logs por pantalla cosa que podes deshabilitar en el momento que creas el log, después el contenido del mismo se puede ver en otra terminal haciendo `tail -f` y pasándole como parámetro el archivo del log.

Saludos.-

**Comment by facutomasetti** [comment]
Entiendo, gracias por la ayuda. Cierro el issue
