### ISSUE TITLE
Prueba FS

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#4180]
Hola buenas, en las pruebas de FS tuve estos resultados. Creo que tienen sentido y la separacion de los archivos la calcule y me dio algo que creo que esta bien pero queria confirmar que sean los resultados esperados porque me dijeron que en la prueba revisan el bitmap y los bloques. 
Los bloques me dieron esto
![image](https://github.com/user-attachments/assets/92830e53-dc50-42b8-83f0-88a680ba9b7d)

Y el bitmap me dio asi:
Por las dudas, el bitmap lo hice en LSBFirst
![image](https://github.com/user-attachments/assets/31e25032-bfc7-4a51-b49b-9e704b3ec92a)

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cuál sería la duda que requiera de soporte? ¿Hay algo que no coincida con lo que está especificado en el documento de pruebas? Saludos

**Comment by JoaquinCoaricona** [comment]
Queria ver si el bitmap esta bien, porque lo intente hacer a mano pero me confunde y lo intente hacer con chatgpt pero me da distintos resultados

**Comment by RaniAgus** [comment]
Como futuros ingenieros, en esta instancia determinar si es correcta o no la implementación que hicieron es tarea suya. 

La utilidad de este foro es darles una mano a la hora de resolver problemas, no que nos den un resultado y les digamos si está bien o está mal. Para eso existe la instancia evaluatoria.

Si necesitan una mano para interpretar el bitmap, un tip que les puede servir es que el sistema hexadecimal "agrupa" bits de a cuatro, es decir: `7fff` es igual a `0111 1111 1111 1111`, ya que:

`0111` en binario es 7 en decimal y hexa

`1111` en binario, 15 en decimal y `f` en hexa

¿Se entiende la idea?

Saludos

**Comment by JoaquinCoaricona** [comment]
Ok pero entonces
Si yo tengo `ffff` ->seria `1111 1111 1111 1111` 
a) estos serian los primeros bloques? osea del 0 al 15?
Y despues deberia analizar por separado a los restantes osea
`7fff` -> `0111 1111 1111 1111` b) aca el 0 seria el bloque 31?

**Comment by iago64** [comment]
Buenas! Cómo va?

Algo interesante de las cosas de programación es que **siempre** podemos hacer un ejemplo acotado para probar y despejarnos las dudas, es decir, podes agarrar hacerte un main de un par de lineas y que escriba bits específicos de un bitmap y ver como se representan.

Saludos.-

**Comment by JoaquinCoaricona** [comment]
Entiendo, en el TP durante la compactacion se va imprimiendo el estado en el que queda cada bloque, pero la forma en que se escriben los datos en el archivo me parece rara o por lo menos confusa, se que el bitarray se esta escribiendo como lo veo en los logs pero queria entender bien la forma en que se guarda en el archivo. Igualmente gracias
