### ISSUE TITLE
Tamanio STDIN

### ISSUE THREAD

**Issue by nsantero** [sisoputnfrba/foro#4181]
Hola como estan, estabamos probrando la implementacion de STDIN_READ y nos surgio una duda, si el tamaño es por ejemplo 2, va a ser dos caracteres y el \0, o va a ser un caracter y el \0?

**Comment by RaniAgus** [comment]
¡Buenas! Si el tamaño es 2, van a ser 2 caracteres. Es decir, el caracter nulo no se guarda. Saludos

**Comment by nsantero** [comment]
Okaa, gracias!

**Comment by iago64** [comment]
Si la duda esta resuelta cerramos el issue.
