### ISSUE TITLE
Horario

### ISSUE THREAD

**Issue by JoaquinCoaricona** [sisoputnfrba/foro#4182]
Hola buenas. Este lunes queria ir a probar el TP al laboratorio pero como no son dias de clases normales queria preguntar desde que hora puedo ir o si hay algun horario especifico? Desde ya muchas gracias

Se que esa etiqueta no va, pero no habia otra

**Comment by iago64** [comment]
Buenas! Cómo va?

Nosotros no manejamos el laboratorio y solamente reservamos las fechas de entregas, con lo cual el resto de días que se encuentre abierto depende 100% del departamento de sistemas, con lo cual te recomiendo que los contactes por mail o llames por teléfono directamente al laboratorio antes de ir.

Saludos.-

**Comment by JoaquinCoaricona** [comment]
Gracias
