### ISSUE TITLE
Quantum y Manejo de recursos

### ISSUE THREAD

**Issue by LainoRamiro** [sisoputnfrba/foro#4183]
Hola, estaba revisando el TP y vi el issue #3653 de nuevo y me quedé recalculando. Quería ver si el análisis que estoy haciendo cuando se manejan recursos y se tiene RR o VRR es el correcto.

En RR cuando un proceso es desalojado de la CPU por hacer WAIT y se devuelve el contexto de ejecución al Kernel, si hay instancias del recurso, entonces el proceso sigue en estado EXEC y el hilo que cuenta el quantum NO se cancela y se manda a la CPU. En el caso de no haber instancias, el proceso se bloquea. 
La pregunta es si en VRR cuando el proceso se bloquea por no tener instancias de recurso, lo que se debe hacer es guardar el tiempo restante del quantum del proceso, o sea NO reiniciarlo al valor del archivo config. Es esta la forma correcta? Hay algo erróneo o que no tenga sentido en lo que pensé?

Saludos! :)

**Comment by FredeHG** [comment]
Hola buenas!

Citando a Dami en el issue que mencionas

> Si te bloqueas por un WAIT a un recurso, efectivamente, no va a READY con prioridad, recordemos que el espíritu de VRR es darle mas prioridad a los procesos IO Bound.

https://github.com/sisoputnfrba/foro/issues/3653#issuecomment-2094546680

Creo que eso responde bien la pregunta 

Saludos!

**Comment by LainoRamiro** [comment]
Ahhh listo entonces, gracias por responder, no leí bien esa parte! Saludos! :)
