### ISSUE TITLE
Duda salvations edge. Out of memory, aborted core dump y segmentation faults

### ISSUE THREAD

**Issue by FacundoStancanelliUTN** [sisoputnfrba/foro#4184]
Buenas! Que tal, como estan?
Venimos con algunas dudas respecto a la prueba de SALVATIONS_EDGE.
Luego de unos minutos de ejecución, estamos teniendo estos resultados en el monitor de IO:
<img width="806" alt="Captura de pantalla 2024-07-20 a la(s) 6 18 42 p  m" src="https://github.com/user-attachments/assets/546ce6ee-05aa-42ba-a3b4-3447294753a7">

Ademas, en kernel, vemos que algunos procesos se finalizan por OUT_OF_MEMORY (Aun teniendo la nueva configuracion de TAM_MEMORIA=4096
TAM_PAGINA=32
RETARDO_RESPUESTA=100.
Si le agregamos mas memoria, no nos pasa).

Es esto correcto?
Cuantos mensajes de Aborted (core dump) deben figurar? Y cuantos mensajes de Segmentation Fault (core dump)?

Gracias.
Saludos!

**Comment by FacundoStancanelliUTN** [comment]
Por otro lado. (tiene que ver con pruebas pero no tanto con el documento de pruebas como tal :))
Para ir al laboratorio, debemos reservar en algun lado? O nos anunciamos y podemos pasar?

**Comment by iago64** [comment]
Buenas! Cómo va?

Los textos que vos decis, por casualidad, no será lo que estas leyendo de memoria no? Fijate que el proceso sigue ejecutando y cualquiera de esos 2 errores, suelen ser finalización automática del proceso.
Los mensajes van a repetirse eternamente hasta que corte la prueba ya que todo esta en un "`while(1)`"

Respecto al laboratorio, misma respuesta que en el issue #4182 

Saludos.-

**Comment by FacundoStancanelliUTN** [comment]
Todo bien por aca!
Disculpa, no vi ese issue acerca del laboratorio. Gracias!

En cuanto a los textos, si! Esos son los textos que se "recuperan" de memoria y se muestran en el monitor. Si, entiendo que van a repetirse porque como decis vos, estan en loop.

Mi duda era, que hay algunos procesos en esta prueba que terminan por out of memory con la config actual (aunque si le ponemos mas memoria no finalizan por out of memory), es eso correcto?

Por otro lado, en cuanto a los textos, hay alguna cantidad que tienen que aparecer del Aborted (core dump)? Porque claro, luego de tirar esos 4 o 5, muestra en ese loop ese texto de segmentation fault

**Comment by iago64** [comment]
Buenas!

Los procesos que terminan por out of memory los pueden resolver poniendo 16384 de tamaño de memoria, igual mientras tengan unos cuantos dando vueltas con el tema de ir y venir de la cpu está bien, en la prueba esa lo que nos importa es ver esperas activas (consumo elevado de CPU) y memory leaks (que la memoria utilizada no crezca indefinidamente).

Es importante que esta prueba la corran en la vm server porque en la vm con entorno grafico ya con solo tener el vscode el consumo de memoria y cpu es elevado y capaz se pegan un cagazo importante cuando nada que ver.

Saludos.-

**Comment by FacundoStancanelliUTN** [comment]
Bien perfecto! Si, habiamos puesto un poquito mas de memoria y siguio todo bien, impecable.

> 
Es importante que esta prueba la corran en la vm server porque en la vm con entorno grafico ya con solo tener el vscode el consumo de memoria y cpu es elevado y capaz se pegan un cagazo importante cuando nada que ver.

Si, nos paso jajajaja

Gracias!
Saludos!
