### ISSUE TITLE
Detener planificacion con RR/VRR

### ISSUE THREAD

**Issue by AgustinCarlanaRivero** [sisoputnfrba/foro#4185]
Hola, buenas. La consigna dice:
_Detener planificación: Este mensaje se encargará de pausar la planificación de corto y largo plazo. El proceso que se encuentra en ejecución NO es desalojado, [...]_
Esto implica que si se termina el quantum **no** se lanza la interrupción hasta que se reanude la planificación, o en ese caso sí se debería lanzar la interrupción, pero no se maneja el motivo de desalojo?

Saludos.

**Comment by iago64** [comment]
Buenas! cómo va?

Pueden mandar la interrupción, pueden recibir incluso el PCB de la CPU, pero no deberían hacer nada mas, ya que lo que se espera del detener planificación es que no se cambien los estados de los procesos.

Saludos.-

**Comment by AgustinCarlanaRivero** [comment]
Perfecto, gracias!
