### ISSUE TITLE
Sobre WAIT, y SIGNAL en RR/VRR

### ISSUE THREAD

**Issue by Joaquinnicolasrossi** [sisoputnfrba/foro#4186]
### 📔 Citas del enunciado/videos
>A la hora de recibir de la CPU un Contexto de Ejecución desalojado por WAIT, el Kernel deberá verificar primero que exista el recurso solicitado y en caso de que exista restarle 1 a la cantidad de instancias del mismo. En caso de que el número sea estrictamente menor a 0, el proceso que realizó WAIT se bloqueará en la cola de bloqueados correspondiente al recurso.

1) Mi duda sobre WAIT (en general) es la siguiente, en caso de que el recurso no quede bloqueado, se manda directamente a la cola de ready o vuelve al CPU para seguir ejecutando?

### 📔 Citas del enunciado/videos
>A la hora de recibir de la CPU un Contexto de Ejecución desalojado por SIGNAL, el Kernel deberá verificar primero que exista el recurso solicitado, luego sumarle 1 a la cantidad de instancias del mismo. En caso de que corresponda, desbloquea al primer proceso de la cola de bloqueados de ese recurso. Una vez hecho esto, se devuelve la ejecución al proceso que peticiona el SIGNAL.

2) En el caso de que el algoritmo de planificacion a utilizar sea RR deberia reiniciar el quantum del proceso una vez que lo devuelvo al CPU?

3) En el caso de que se este usando VRR, el quantum del proceso cuando lo devuelvo a CPU es el quantum restante de cuando llego por la instruccion SIGNAL, o deberia reiniciar su quantum?

**Comment by RaniAgus** [comment]
¡Buenas!
1. Misma respuesta que en: https://github.com/sisoputnfrba/foro/issues/3883#issuecomment-2156813271
2. Como mencionan Dami y Lean en https://github.com/sisoputnfrba/foro/issues/3455#issuecomment-2043555489, SIGNAL es una syscall, no es un "desalojo" real (el proceso nunca deja de estar en EXEC, solo cambia de modo usuario a modo kernel). Entonces, como el proceso sigue estando en EXEC, no deberían reiniciar su quantum. Sino, un proceso que ejecuta muchas syscalls podría dejar a otros en starvation, y eso no tendría sentido en RR o VRR.
3. Siguiendo con la respuesta 2, no deberías reiniciar su quantum.

Saludos

**Comment by Joaquinnicolasrossi** [comment]
Muchas gracias Agus!
