### ISSUE TITLE
Pequeña duda de log obligatorio

### ISSUE THREAD

**Issue by ArielRotolo** [sisoputnfrba/foro#4187]
Buenas, viendo los logs obligatorios de la memoria se pide el log:

Creación / destrucción de Tabla de Páginas: “PID: <PID> - Tamaño: <CANTIDAD_PAGINAS>”

Según lo interprete este log se ejecutaría cuando recibe un crear o finalizar proceso del kernel, el cual lleva a que siempre se cree el proceso con una cantidad de paginas 0 y se finalice con una cantidad X dependiendo si se hizo un resize o no.

La consulta es si estaría mal especificar en el log si se esta creando o destruyendo la tabla de paginas porque de la manera que está es medio confuso o tiene que respetarse al 100%, pensaba algo como:

"Creado PID: <PID> - Tamaño: <CANTIDAD_PAGINAS>"
"Finalizado PID: <PID> - Tamaño: <CANTIDAD_PAGINAS>"

**Comment by iago64** [comment]
Buenas! Cómo va?

El tema de la creación si, va a ser siempre con cantidad de páginas 0, en si nos importa más el de finalización para saber que tamaño tenía el proceso al momento de finalizar.

Saludos.-

**Comment by ArielRotolo** [comment]
Clarísimo, gracias!
