### ISSUE TITLE
Traducción en las pruebas finales

### ISSUE THREAD

**Issue by JoacoBarreiro23** [sisoputnfrba/foro#4188]
Hola buenas, me agarro la duda si una implementación que hice se podria coinciderar correcta, en la instruccion IO_STDOUT_WRITE, para simplificar las cosas se me ocurrio hacer una lectura byte a byte en la memoria pero lo cual requiere tantas traducciones como tamaño tenga el string a leer, en un principio pense que no seria mucho problema ya que al estar la TLB seria todo instantaneo pero en la Prueba IO no hay entradas en la misma, asi que solo queria saber si esta implementación se podria coinciderar correcta o hay que hacer un cambio para solo tener la cantidad de traducciones minimas y necesarias.
Desde ya muchas gracias!!

**Comment by iago64** [comment]
Buenas! Cómo va?

Esta muy lejos de la implementación ideal, ya que no solo estan teniendo muchos accesos a tabla de páginas si no que ademas tienen muchos accesos a espacio de usuario cuando no deberían, por lo que sería mucho mas correcto que dividan las lecturas / escrituras teniendo una por página / frame que leen.
Si tienen algun otro problema que les impida cumplir con lo pedido en las pruebas, ataquen esos problemas primero ya que esto mal que mal termina cumpliendo con lo pedido.

Saludos.-

**Comment by JoacoBarreiro23** [comment]
Perfecto queria saber eso nada mas, gracias!!
