### ISSUE TITLE
Duda RR y VRR

### ISSUE THREAD

**Issue by julienf04** [sisoputnfrba/foro#4189]
### Buenasss!

Tenemos una duda con respecto a una implementación que hicimos de los algoritmos de planificación RR y VRR.

Supongamos que estamos usando el algoritmo de planificación RR y hay 1 solo proceso en el sistema. Como hay 1 solo proceso, estaría en el estado de ejecución (suponiendo que no se bloquea nunca).

Según como lo tenemos implementado ahora, cuando al proceso en ejecución se le acaba el quantum, el Kernel le interrumpe a la CPU, y la CPU le envía el contexto al Kernel. Luego, el Kernel decide el próximo proceso a ejecutar. Esto ocurre siempre, incluso cuando no hay ningún otro proceso en la cola de ready.

Como estamos suponiendo que solo hay 1 proceso en el sistema, una vez que se desaloje el proceso, el Kernel decidiría que ese mismo proceso debería volver a ejecutar. Esto impacta en el rendimiento, ya que estaríamos desalojando el proceso en ejecución incluso cuando sabemos que va a volver a ejecutar el mismo.

Cuál sería la implementación ideal que se espera para este TP? Que se desaloje siempre, incluso cuando se sabe que el mismo proceso va a volver a ejecutar, o que directamente no se desaloje? Es necesario seguir la implementación ideal en este caso en concreto, o no tiene ninguna relevancia?

**Comment by LeandroCarbajales** [comment]
Buenas!

> Esto ocurre siempre, incluso cuando no hay ningún otro proceso en la cola de ready.

Esto es correcto, coincide con lo que se espera en la prueba al igual que en cualquier GANTT de un ejercicio de la guía/parciales.

Saludos!
       Lean
