### ISSUE TITLE
Duda sobre fin de quantum durante tiempo de espera de instruccion.

### ISSUE THREAD

**Issue by Joaquinnicolasrossi** [sisoputnfrba/foro#4190]
### 👍 Comportamiento esperado
Realizando la prueba de planificacion, el proceso 4 deberia entrar en un loop infinito, lo que sucede bien en FIFO. 

### 👎 Comportamiento obtenido

RR: Como dice el enunciado de la prueba, el proceso 3 deberia finalizar 2 veces por fin de quantum. El problema que estamos teniendo es que en un determinado momento, el proceso 4 es desalojado mientras se realiza el decode de la instruccion SET PC 0. Entonces el proceso es desalojado sin llevar a cabo la instruccion. Al no haber actualizado el PC, cuando vuelve a CPU ejecuta la instruccion EXIT. Entonces los procesos finalizan en el siguiente orden: 1 -> 3 -> 4 -> 2

```
[INFO] 22:36:57:470 LOG/(12308:12444): PID: 4 - FETCH - Program Counter: 4
[INFO] 22:36:58:218 LOG/(12308:12450): INTERRUPCION POR FIN DE QUANTUM
[INFO] 22:36:58:478 LOG/(12308:12444): PID: 4 - Ejecutando: SET - PC 0    // el log existe pero la instruccion no se lleva a cabo
[INFO] 22:36:58:478 LOG/(12308:12444): Recibí el contexto del proceso 2 y se inicia el ciclo de instruccion
[INFO] 22:36:58:478 LOG/(12308:12444): PID: 2 - FETCH - Program Counter: 10
[INFO] 22:36:59:479 LOG/(12308:12444): PID: 2 - Ejecutando: SET - EBX 1    
[INFO] 22:36:59:479 LOG/(12308:12444): PID: 2 - FETCH - Program Counter: 11
[INFO] 22:37:00:479 LOG/(12308:12444): PID: 2 - Ejecutando: IO_SGEN_SLEEP - SLP1 1    
[INFO] 22:37:00:480 LOG/(12308:12444): Recibí el contexto del proceso 4 y se inicia el ciclo de instruccion
[INFO] 22:37:00:480 LOG/(12308:12444): PID: 4 - FETCH - Program Counter: 5
[INFO] 22:37:01:481 LOG/(12308:12444): PID: 4 - Ejecutando: EXIT - 
```
Que deberiamos hacer cuando sucede una interrupcion de fin de quantum mientras el proceso esta esperando el RETARDO_INSTRUCCION?
Solcuiones posibles que pensamos:
1) Dejar que el proceso realice la instruccion y luego interrumpirlo
2) Que la espera del retardo de instruccion se de en otro lado, pero no estamos seguros.

**Comment by LeandroCarbajales** [comment]
Buenas!
Al igual que en cualquier ciclo de instrucción, el chequeo de interrupciones (o al menos actuar en consecuencia de una) se hace siempre como última etapa del ciclo. No deberían devolver el contexto de ejecución si aun no ejecutó la instrucción actual.

Les resuelve la duda?
Saludos!
       Lean

**Comment by Joaquinnicolasrossi** [comment]
Genial, muchas gracias.
