### ISSUE TITLE
Dudas sobre tipo de archivos a crear en el FS

### ISSUE THREAD

**Issue by mamusante** [sisoputnfrba/foro#4191]
Buenas, con mi grupo para la creacion de los archivos q se van a guardar en el FS decidimos usar los configs de la catedra para modificarlos mas facilmente. 
Teniamos la duda de si esta mal que los archivos que se creen sean .config o si no hay problema con eso. En las instrucciones que dicen nombre_archivo.txt nos manejamos internamente para cambiarle el nombre al archivo sin tener q tocar los scripts de las pruebas. Esta mal? o podemos usarlo asi

**Comment by LeandroCarbajales** [comment]
Buenas!
De hecho en el enunciado de DialFS les dejamos una nota al pié recomendando que usen las configs de las commons para operar sobre los mismos.

> Estos archivos de metadata tienen una similitud con los archivos de configuración de los módulos, por lo que recomendamos utilizar las commons propias de config para operarlos.

Saludos!
    Lean
