### ISSUE TITLE
Compactacion en prueba de FS

### ISSUE THREAD

**Issue by MeliBugallo** [sisoputnfrba/foro#4192]
Buenas!
Tenemos una duda acerca de la siguiente situación: se tiene que ampliar el archivo azul pero no hay los suficientes bloques libres al final de este sino al final de todo.

![image](https://github.com/user-attachments/assets/38034435-33c4-43dd-93e7-8cdace515d13)

Entendemos que la implementación de la compactación está a decisión del grupo pero queriamos asegurarnos de un par de cosas.
En caso de optar por la opcion 1, implica compactar siempre que no haya suficientes bloques libres contiguos al último bloque del archivo a ampliar aunque haya suficientes en otro lugar pudiendo realocar ahí el archivo como en la opcion 2. En la prueba de FS como primero se crean los archivos y despues se truncan, con este mecanismo y dados los scripts de la prueba termina habiendo una compactación por cada truncado (ampliar). Pero en los resultados de la prueba de fs solo se menciona una compactacion requerida.
1)¿Es correcto que se realice una compactación en esta situación o deberia darse la opcion 2?  
2) En caso de que no sea correcto compactar en la situacion planteada y vayamos por la opcion 2, es necesario realizar un retardo por la realocacion del archivo?
a) el retardo seria el mismo que en la compactación?
b) para confirmar: requiere del log de compactacion dado que no es una compactacio como tal?

**Comment by iago64** [comment]
Buenas! Cómo va?

Como bien dijiste, la compactación queda a criterio del grupo y pueden resolverlo de las 2 formas que planteas.
Es por estas diferencias en las posibles implementaciones que en las pruebas dijimos que al menos tiene que haber 1 compactación, ya que hay un archivo que es extremadamente pesado y no hay combinación posible que no haga que compacten,  pero si tienen mas compactaciones y/o movimientos de archivos no hay problema.

Lo único importante es que en cualquiera de los 2 escenarios, siempre apliquen el retardo de compactación, ya que ese retraso busca simbolizar todas las operaciones de lectura y escritura necesarias para mover el archivo.

Saludos.-

**Comment by MeliBugallo** [comment]
Muchas gracias
