### ISSUE TITLE
Duda cantidad de desalojos

### ISSUE THREAD

**Issue by daltplusplus** [sisoputnfrba/foro#4193]
buenas. 
Al ejecutar la pruebas de planificacion en nuestro tp la cantidad de desalojos varia. 
Me parecio logico que a un mismo proceso no le tome siempre la misma cantidad de tiempo el terminar y que a eso se deban distinta cantidad de desalojos por ejecucion.  
Pero en los resultados esperados se indica una cantidad especifica de desalojos para el proceso 3.
¿la cantidad de desalojos indicada es estimativa o no deberia variar la cantidad en nuestro tp?

### 👍 Comportamiento esperado

En VRR finalizan en el mismo orden que RR, pero PLANI_3 es desalojado 3 veces por fin de quantum.

### 👎 Comportamiento obtenido

los procesos finalizan en el orden esperado pero PLANI_3 es desalojado solo 2 veces por fin de quantum.

**Comment by FredeHG** [comment]
Hola buenas!

En este issue se habla de la cuenta que hicimos https://github.com/sisoputnfrba/foro/issues/4049 fíjense si están haciendo las mismas cuentas que nosotros

Saludos!

**Comment by mefederico** [comment]
Hola! 

Te sirvió la respuesta? Algo más en lo que te podamos ayudar?

Si no hay más preguntas, podrías cerrar el issue?

Saludos!

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, si les quedó alguna duda pueden abrir uno nuevo referenciando éste. Saludos
