### ISSUE TITLE
Problema con VS code

### ISSUE THREAD

**Issue by jotab0** [sisoputnfrba/foro#4195]
Buenas!

Estamos teniendo un problema con vs code, de repente no reconoce las variables:

![image](https://github.com/user-attachments/assets/53b10f39-d687-4585-a2b5-d263f8f234df)

Y tampoco nos deja buildear el trabajo: (Qieda cargando indefinidamente)

![image](https://github.com/user-attachments/assets/465a3984-831b-4f90-b11f-a57ec4c81c54)

Lo raro es que nos sucedió a un compañero y a mí al mismo tiempo, sin haber hecho ningún tipo de movimiento ni actualización de repos.

Necesitamos solucionarlo porque no podemos continuar trabajando y necesitamos ultimar detalles!

**Comment by Lord-Bardo** [comment]
Buenas, me esta pasando algo parecido. Lo pudieron solucionar?

**Comment by jotab0** [comment]
No por ahora no, mañana voy a preguntar por el grupo de SO a ver si alguno le pasó lo mismo y pudo resolverlo. 

Hace unas semanas mandaron esto pero no me funcionó, seguramente tenga que ver:

> Hola vscode lanzó una actualización hace un par de días, en linux ésta falla con lo cual no actualicen si usan linux. 
> Por otro lado, si instalaron por snap probablemente se les haya actualizado automáticamente, no lo desinstalen, pongan en la terminal: sudo snap revert code , y van a poder volver a la versión anterior del software. Si lo desinstalaron van a tener que descargar el paquete .snap desde la página de vscode e instalarlo manualmente con sudo snap install miPaquete.snap . Ojalá que no le haya pasado porque es muy desesperante no tener el editor ahora, buen finde.
> 

Cuando tiro eso en la consola me devuelve:

<img width="517" alt="image" src="https://github.com/user-attachments/assets/b9862baa-e294-41e8-9ce3-98d6d917212b">


Si tenés novedades antes que yo las espero, si no lo que tenga lo cuelgo acá.

**Comment by JuanCervini** [comment]
Hola, estoy con el mismo problema desde ayer... Alguien tiene idea como se soluciona o que puede estar pasando?

**Comment by SantiagoDopazo** [comment]
Yo estoy con el mismo problema tambien , quizas fue una actualizacion?

**Comment by RaniAgus** [comment]
¡Buenas @jotab0 @JuanCervini @SantiagoDopazo! ¿Podrían ejecutar el siguiente comando en la consola y devolvernos el output? Es para corroborar cuál es la versión afectada, así podemos revertir a una versión anterior:

```
code --version
```

Por el momento, `code` está instalado en las VMs provistas como apt package, no como snap (aunque puede que en futuras versiones lo revisemos), por lo que la forma de instalar una versión anterior sería especificándola de esta forma:

```
sudo apt update
sudo apt install code=<version>
```

La versión que viene instalada es la de [Agosto 2022](https://code.visualstudio.com/updates/v1_71), pero es un poco vieja. Si es un issue que apareció justo ahora, probaría con la de [Mayo 2024](https://code.visualstudio.com/updates/v1_90) así:

```
sudo apt update
sudo apt install --upgrade code=1.90.2-1718751586
```

Por si les interesa buscar otra versión, pueden elegir cualquiera de las listadas al ejecutar:

```
sudo apt update
apt-cache madison code
```

Saludos

**Comment by SantiagoDopazo** [comment]
1.71.2
74b1f979648cc44d385a2286793c226e611f59e7
x64
Estan es mi version de code

**Comment by JoacoBarreiro23** [comment]
Buenas, estoy teniendo el mismo problema que santiago y me tira exactamente lo mismo

**Comment by RaniAgus** [comment]
@SantiagoDopazo @JoacoBarreiro23 Oki, intentemos primero actualizando a la versión que les pasé más arriba a ver si eso lo soluciona. Recuerden primero cerrar todos los editores que tengan abiertos y luego chequear la versión de nuevo con `code --version`.

**Comment by SantiagoDopazo** [comment]
ahi actualice y por ahora parece que se arreglo

> @SantiagoDopazo @JoacoBarreiro23 Oki, es la versión de Agosto 2022, intentemos primero actualizando a la versión que les pasé más arriba a ver si eso lo soluciona. Recuerden primero cerrar todos los editores que tengan abiertos y luego chequear la versión de nuevo con `code --version`.

**Comment by JuanCervini** [comment]
Hola, seguí los pasos y parece estar solucionado, gracias!
Saludos

**Comment by JoacoBarreiro23** [comment]
Muchas gracias Agus ahi pude solucionar el problema!!

**Comment by SantiagoDopazo** [comment]
Muchas Gracias

**Comment by jotab0** [comment]
Excelente @RaniAgus! También pude solucionarlo con eso, muchas gracias.

**Comment by iago64** [comment]
Habiendo tenido la solución, cerramos el issue pero lo dejamos fijado por si a alguien mas le pasa :)
