### ISSUE TITLE
Duda sobre puntero registro archivo

### ISSUE THREAD

**Issue by moracontreras** [sisoputnfrba/foro#4196]
Hola! Cómo andan? 
Una consulta, en la siguiente función
>IO_FS_READ (Interfaz, Nombre Archivo, Registro Dirección, Registro Tamaño, Registro Puntero Archivo): Esta instrucción solicita al Kernel que mediante la interfaz seleccionada, se lea desde el archivo a partir del valor del Registro Puntero Archivo la cantidad de bytes indicada por Registro Tamaño y se escriban en la Memoria a partir de la dirección lógica indicada en el Registro Dirección.

el registro puntero archivo cuenta como los bytes que se desplaza desde la posición inicial del archivo o es considerada en bits? 
Ya que estoy hago otra pregunta, el tamaño del bloque está en bits pero se puede suponer que es un múltiplo de 8?

**Comment by moracontreras** [comment]
Buenísimo! Otra consulta, el tamaño de bloque que está en el config también es en bytes no?

**Comment by mefederico** [comment]
Hola buenas!

Exactamente, es en bytes.

Saludos!

**Comment by moracontreras** [comment]
Perfecto, muchas gracias!
