### ISSUE TITLE
Duda sobre excepciones

### ISSUE THREAD

**Issue by moracontreras** [sisoputnfrba/foro#4197]
Hola! Todo bien? 
Les hago una consulta, en FS debería considerar el caso en el que se me pide crear un archivo que ya está creado? Y el caso en el que me manden a escribir/leer un archivo que todavía no se creó?

**Comment by iago64** [comment]
Buenas! Cómo va?

No. Las pruebas ya estan subidas y pueden corroborar lo que se va a testear.

Saludos.-
