### ISSUE TITLE
Duda acerca de DIALFs

### ISSUE THREAD

**Issue by FacundoStancanelliUTN** [sisoputnfrba/foro#4198]
Buenas noches! Como están? Todo bien?

Me surgió una duda acerca de la creación de archivos de metadata, bloques.dat, bitmap, etc. A nosotros nos definen un PATH_BASE_DIALFS=/home/utnso/dialfs en el archivo de FS. Si no existe el directorio, lo debemos crear programáticamente? O podemos generarlo a mano previamente? Mas que nada porque en el enunciado **_creo_** que no lo aclara.

Gracias.
Saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

Pueden crear los archivos como mas facil les resulte.

Saludos.-

**Comment by FacundoStancanelliUTN** [comment]
Buenísimo dami! 
Gracias. 
Saludos!
