### ISSUE TITLE
Duda acerca de las pruebas

### ISSUE THREAD

**Issue by SebaR1** [sisoputnfrba/foro#4199]
Hola! Todo bien?
Tengo una consulta acerca de los comandos que puedan ser usados en las pruebas finales, más específicamente en finalizar_proceso. Se puede tener en cuenta que para finalizar un proceso previamente se tenga que usar detener_planificacion? O es una condición necesaria que pueda ser usado sin detener la planificación?
Esto en si es para la ultima prueba de Salvation's Edge, que dice que el ayudante puede pedir usar cualquier comando.

**Comment by iago64** [comment]
Buenas! Cómo va?

Idealmente deberían poder eliminar un proceso sin tener que detener la planificación, pero si no se puede no hay problema, lo avisan en el momento de la entrega y lo tenemos en cuenta.

Saludos.-

**Comment by SebaR1** [comment]
Perfecto, muchas gracias! Cierro issue.
