### ISSUE TITLE
Problema con htop al ejecutar los tests

### ISSUE THREAD

**Issue by IbireFidel** [sisoputnfrba/foro#4200]
Buenas, probando con las computadoras de Medrano, notamos que al iniciar el test de Salvations Edge con el htop iniciado solamente en kernel no anda correctamente el sistema. Por otro lado, si lo probamos sin el htop del kernel, todo funciona correctamente.

**Comment by iago64** [comment]
Buenas! Cómo va?

A que te referis con que no funciona correctamente?

Saludos.-

**Comment by IbireFidel** [comment]
Todo bien, vos? También notamos que sucede cuando abrimos htop en la máquina que corre memoria y cpu.
Si no lo ejecutamos con htop, el funcionamiento del salvations edge es el esperado, osea ejecutan todos los procesos con todos los modulos hasta que después de un tiempo el monitor de entradasalida devuelve un segmentation fault / aborted core dumped.
Pero cuando probamos todo con htop abierto, el sistema queda ejecutando solamente un proceso y no avanza: no se interrumpe por quantum.

**Comment by IbireFidel** [comment]
También aprovecho para preguntar si el día de la entrega, hay algún problema si abrimos htop una vez que ya iniciamos alguno de los tests. (ya que así no arroja ningún problema)

**Comment by iago64** [comment]
Buenas! Cómo va?

Solo por casualidad, los Segmentation Fault / Aborted core dumped, no seran los outputs que esta escribiendo correctamente la entrada salida no?

Respecto al tema del `htop`, podrías subir una captura en ambas situaciones? (Iniciando el tp con htop y otro iniciando htop despues de lanzar las pruebas) Porque htop no es mas que un monitor de recursos, no debería interferir en absolutamente nada con el tp.

Saludos.-

**Comment by IbireFidel** [comment]
-Sí, los outputs son los de entrada salida, por eso sería el comportamiento correcto.

-Descubrimos que no ocurre solamente con htop, sino simplemente con tener una terminal adicional abierta en cualquiera de las máquinas.

En esta imagen está el comportamiento erróneo al usar una terminal adicional, este caso con htop
![image](https://github.com/user-attachments/assets/7581662d-206e-4d29-8b6e-1dd4d7c37cc3)

En esta imagen el comportamiento correcto, ya que se van ejecutando los distintos procesos.
![image](https://github.com/user-attachments/assets/f2c59c23-1caf-4d5f-a929-91f21b74a4ff)

**Comment by iago64** [comment]
Buenas! Cómo va?

Es muy muy raro lo que les esta pasando, no debería afectar en absolutamente nada que tengan diferentes terminales, de hecho en las pruebas van a correr mas de 1 proceso por máquina por lo que deberían poder tener varias terminales abiertas.
Que pasa si levantan todas las terminales de todos los módulos en una misma pc? Que puertos estan usando para conectarse entre los módulos?

Saludos.-
