### ISSUE TITLE
Error de Conexion al Intentar conectar en distintas maquinas

### ISSUE THREAD

**Issue by martinAguirreRuiz** [sisoputnfrba/foro#4204]
Hola, estuvimos intentando probar el tp en varias VM server, pero no estamos pudiendo conectar Kernel. Cuando probamos Kernel , CPU y Memoria en una pc (cada una en una VM) y IO en otra pc anda, pero cuando probamos separar CPU, memoria y kernel el PC separadas kernel no se conecta, pero CPU y Memoria si.
Actualizamos las IPs siempre y los puertos coinciden.
Kernel tiene q hacer conexion de DISPATCH e INTERRUPT, dispatch a veces conecta, pero siempre falla en INTERRUPT.

Vimos los errores comunes de SO docs en despliegue, pero creemos que no es nada eso. Lo revisamos varias veces.

Cabe aclarar que cuando corremos el TP en la vm con grafica anda bien y todos los modulos se conectan sin problemas.

### 👍 Comportamiento esperado

==4532== Command: ./bin/kernel kernel_plani_fifo.config
==4532==
Hola desde Kernel!!
[INFO] 14:54:17:275 Kernel/(4532:4532): Se creo el struct config_kernel con exito
[INFO] 14:54:17:310 Kernel/(4532:4532): Conexión con el servidor CPU creada con éxito
ERROR DE CONEXION
Esperando 5 segundos para buscar al cliente...
Error al intentar conectar: Transport endpoint is already connected
==4532==
make[1]: *** [makefile:57: run] Error 1
make[1]: Leaving directory '/home/utnso/so-deploy/tp-2024-1c-No-me-quemes/kernel'
make: *** [makefile:53: start] Error 2

**Comment by RaniAgus** [comment]
¡Buenas! Como no contamos con el código que usaron, lo único que puedo asumir viene de este log:
```
Error al intentar conectar: Transport endpoint is already connected
```

Por cómo es el formato, entendería que viene de un llamado a la función `perror()`:
```c
perror("Error al intentar conectar");
```

El texto "Transport endpoint is already connected" proviene del valor de [errno](https://man7.org/linux/man-pages/man3/errno.3.html), una variable global[^1] que muchas syscalls usan para setear la razón del error. En muchos manuales aparece un texto del estilo:

> RETURN VALUE
>        ....
>        On error, -1 is returned, and [errno](https://man7.org/linux/man-pages/man3/errno.3.html) is set to indicate the error.

Buscando en la [tabla de códigos de error de errno](https://chromium.googlesource.com/chromiumos/docs/+/master/constants/errnos.md), entiendo que se trata del error 106: `EISCONN`. Para ese código de error, en el [manual de `connect()`](https://man7.org/linux/man-pages/man2/connect.2.html) figura lo siguiente:

> EISCONN
>              The socket is already connected.

Por lo tanto, yo buscaría en alguna parte del código si es posible que se termine llamando a `connect()` más de una vez dado el mismo socket.

Eso es lo único que les puedo decir con el contexto que nos dieron 🤷🏻‍♂️ 

Si no hubo suerte porfa **ayúdennos a ayudarles** proveyendo más contexto, un log podría significar mil cosas distintas dependiendo del código que hayan implementado.

Saludos

[^1]: En realidad no es una variable global, es más bien una macro que funciona como variable global con la particularidad de ser thread-safe.

**Comment by martinAguirreRuiz** [comment]
Hola, lo tenemos asi, el socket q retorna dsp lo ponemos como variable global. 

Esta funcion la llamamos desde kernel 2 veces, una para dispatch y otra para interrupt
int crear_conexion(char *ip, char *puerto)
{
	struct addrinfo hints;
	struct addrinfo *server_info;

	memset(&hints, 0, sizeof(hints));
	hints.ai_family = AF_INET;
	hints.ai_socktype = SOCK_STREAM;
	hints.ai_flags = AI_PASSIVE;

	getaddrinfo(ip, puerto, &hints, &server_info);

	// creamos el socket del cliente
	int socket_cliente = socket(server_info->ai_family,
								server_info->ai_socktype,
								server_info->ai_protocol);

	//conectamos el socket del cliente con el del servidor

	
	int conexion = connect(socket_cliente, server_info->ai_addr, server_info->ai_addrlen);
	
	// COMENTAR LAS SIGUIENTES LINEAS SI QUEREMOS PROBAR UN MODULO SOLO
	 if (conexion == -1){
	 	printf("ERROR DE CONEXION\n");
	 	printf("Esperando 5 segundos para buscar al cliente...\n");
    //  	sleep(5);
	//  	connect(socket_cliente, server_info->ai_addr, server_info->ai_addrlen);
	//  	if (connect(socket_cliente, server_info->ai_addr, server_info->ai_addrlen) == -1){
	//  		perror("Error al intentar conectar");
    //      	exit(1);
	//  	}
	}

	freeaddrinfo(server_info);
	//send_handshake(socket_cliente);
	return socket_cliente;
}

Desde CPU para las conexiones de DISPATCH e INTERRUPT tenemos esto

void server_para_kernel() // Atiendo al cliente
{
    socket_servidor_cpu = iniciar_servidor(config_cpu->puerto_escucha_dispatch, log_cpu);
    if (socket_servidor_cpu == -1)
    {
	    log_info(log_cpu, "ERROR: No se pudo iniciar CPU como servidor para KERNEL");
        exit(1);
    }

	log_info(log_cpu, "Esperando a KERNEL...");

    socket_cliente_kernel = esperar_cliente(socket_servidor_cpu, log_cpu);
}

// Server para recibir interrupciones de Kernel ---------------------------------------------------------------------------------------

void interrupcion_para_kernel()
{	
    socket_servidor_cpu = iniciar_servidor(config_cpu->puerto_escucha_interrupt, log_cpu);
    if(socket_servidor_cpu == -1)
    {
	    log_info(log_cpu, "Error: No se pudo iniciar CPU como servidor para Kernel");
        exit(1);
    }

	log_info(log_cpu, "CPU listo para recibir interrupcion de Kernel");
    socket_interrupt_kernel = esperar_cliente(socket_servidor_cpu, log_cpu);
}

**Comment by RaniAgus** [comment]
Asumiendo que su código tiene esas líneas descomentadas:

```c
	 if (conexion == -1){
	 	printf("ERROR DE CONEXION\n");
	 	printf("Esperando 5 segundos para buscar al cliente...\n");
    //  	sleep(5);
	//  	connect(socket_cliente, server_info->ai_addr, server_info->ai_addrlen);
	//  	if (connect(socket_cliente, server_info->ai_addr, server_info->ai_addrlen) == -1){
	//  		perror("Error al intentar conectar");
    //      	exit(1);
	//  	}
	}
```
Entendería que, entonces, el error que deberíamos revisar es cuando se realiza el primer connect, ¿podrían agregar el llamado a `perror()` ahí y revisar cuál sería el motivo según el error que se imprime? (de la misma forma que lo hice más arriba).

En cuanto a las líneas comentadas, pueden quitarlas, si por algún motivo falla `connect()` en la prueba les pediremos que vuelvan a ejecutar el módulo y listo :)

PD: Un dato de color - en markdown podés darle formato a un bloque de código (de más de una línea) usando tres comillas invertidas arriba y abajo (si le agregás una "c"  lo interpreta como código C y lo colorea), así:

\`\`\`c
printf("¡Hola mundo!\n");
\`\`\`

Esto se va a imprimir de esta forma:

```c
printf("¡Hola mundo!\n");
```

**Comment by martinAguirreRuiz** [comment]
Ahi volvimos a correr sacando esas lineas y con el p error , ahora nuestro codigo quedo asi:

```c
int crear_conexion(char *ip, char *puerto)
{
	struct addrinfo hints;
	struct addrinfo *server_info;

	memset(&hints, 0, sizeof(hints));
	hints.ai_family = AF_INET;
	hints.ai_socktype = SOCK_STREAM;
	hints.ai_flags = AI_PASSIVE;

	getaddrinfo(ip, puerto, &hints, &server_info);

	// creamos el socket del cliente
	int socket_cliente = socket(server_info->ai_family,
								server_info->ai_socktype,
								server_info->ai_protocol);

	//conectamos el socket del cliente con el del servidor

	if (socket_cliente == -1) {
        perror("Error al crear el socket");
        freeaddrinfo(server_info);
        return -1;
    }
	
	int conexion = connect(socket_cliente, server_info->ai_addr, server_info->ai_addrlen);
	

	if (conexion == -1) {
        perror("Error al conectar");
        close(socket_cliente);
        freeaddrinfo(server_info);
        return -1;
    }

    freeaddrinfo(server_info);
    
	//send_handshake(socket_cliente);
	return socket_cliente;
} 
```

Nos tiro este error en la consola

==2118== Command: ./bin/kernel kernel_plani_vrr.config
==2118==
Hola desde Kernel!!
[INFO] 17:30:32:446 Kernel/(2118:2118): Se creo el struct config_kernel con exito
[INFO] 17:30:32:480 Kernel/(2118:2118): Conexión con el servidor CPU creada con éxito
Error al conectar: Connection refused
[INFO] 17:30:32:491 Kernel/(2118:2118): ERROR: No se pudo establecer la interrupcion Kernel-CPU
==2118==
make[1]: * [makefile:57: run] Error 1
make[1]: Leaving directory '/home/utnso/so-deploy/tp-2024-1c-No-me-quemes/kernel'
make: * [makefile:53: start] Error 2

Podra ser un error de que inicializamos 2 veces a CPU como servidor para kernel y "reescribimos" la variable socket servidor cpu?, seria en este codigo

```c
void server_para_kernel() // Atiendo al cliente
{
    socket_servidor_cpu = iniciar_servidor(config_cpu->puerto_escucha_dispatch, log_cpu);
    if (socket_servidor_cpu == -1)
    {
	    log_info(log_cpu, "ERROR: No se pudo iniciar CPU como servidor para KERNEL");
        exit(1);
    }

	log_info(log_cpu, "Esperando a KERNEL...");

    socket_cliente_kernel = esperar_cliente(socket_servidor_cpu, log_cpu);
}

// Server para recibir interrupciones de Kernel ---------------------------------------------------------------------------------------

void interrupcion_para_kernel()
{	
    socket_servidor_cpu = iniciar_servidor(config_cpu->puerto_escucha_interrupt, log_cpu);
    if(socket_servidor_cpu == -1)
    {
	    log_info(log_cpu, "Error: No se pudo iniciar CPU como servidor para Kernel");
        exit(1);
    }

	log_info(log_cpu, "CPU listo para recibir interrupcion de Kernel");
    socket_interrupt_kernel = esperar_cliente(socket_servidor_cpu, log_cpu);
}
```

Lo raro es que si corremos en 3 vm server distintas CPU, memoria y kernel pero que estan en la misma PC (aunque cada una con distinta IP) no falla.  Pero al separar cualquiera de esos modulos si falla

**Comment by RaniAgus** [comment]
Wait a minute... Como podrán observar en los logs, ahora el mensaje de error es distinto:
```
Error al conectar: Connection refused
```

¿Podrían revisar la documentación para el error "Connection refused" primero porfi? 😌

**Comment by martinAguirreRuiz** [comment]
Cambiamos lo de la variable q se sobreescribia y lo pudimos conectar ahora entre dos server en dos pc distintas, pero a la 3era ya se rompio y no conecto mas.

Buscando la documentacion encontramos esto:

ECONNREFUSED
              A connect() on a stream socket found no one listening on
              the remote address.

A esa documentacion te referias? U otra?

**Comment by iago64** [comment]
Buenas! Cómo va?

Siguiendo un poco el hilo, lo que dice la documentación es bastante descriptivo no?

Saludos.-

**Comment by martinAguirreRuiz** [comment]
Si, entendemos el error, pero no sabemos como solucionarlo. Nos podrian dar una mano?

En esta funcion pusimos un for en el getaddrinfo para recorrer todas las conexiones posibles, pero no siempre funciona. 
Al final del main tenemos "liberar_conexion" tanto para los sockets de servidor como de clientes.

```c
int crear_conexion(char *ip, char *puerto) {
    struct addrinfo hints;
    struct addrinfo *server_info;
    struct addrinfo *p;
    int socket_cliente;
    int conexion;
    int status;

    // Inicializamos la estructura hints
    memset(&hints, 0, sizeof(hints));
    hints.ai_family = AF_INET;       // IPv4
    hints.ai_socktype = SOCK_STREAM; // TCP
    hints.ai_flags = 0;              // No usamos flags adicionales

    // Obtenemos información de la dirección del servidor
    if ((status = getaddrinfo(ip, puerto, &hints, &server_info)) != 0) {
        fprintf(stderr, "Error en getaddrinfo: %s\n", gai_strerror(status));
        return -1;
    }

    // Recorremos las direcciones posibles
    for (p = server_info; p != NULL; p = p->ai_next) {
        // Creamos el socket del cliente
        socket_cliente = socket(p->ai_family, p->ai_socktype, p->ai_protocol);
        if (socket_cliente == -1) {
            perror("Error al crear el socket");
            continue; // Intentamos con la siguiente dirección
        }

        // Conectamos el socket del cliente con el del servidor
        if (connect(socket_cliente, p->ai_addr, p->ai_addrlen) == -1) {
            perror("Error al conectar");
            close(socket_cliente);
            continue; // Intentamos con la siguiente dirección
        }

        // Conexión exitosa
        break;
    }

    // Liberamos la memoria de la información de la dirección
    freeaddrinfo(server_info);

    // Verificamos si hemos salido del loop sin éxito
    if (p == NULL) {
        fprintf(stderr, "Error: No se pudo conectar a ningún servidor\n");
        return -1;
    }

    return socket_cliente;
}
```

```c
int iniciar_servidor(char* puerto, t_log* logger)
{
	int socket_servidor;

	struct addrinfo hints, *servinfo;

	memset(&hints, 0, sizeof(hints));
	hints.ai_family = AF_INET;
	hints.ai_socktype = SOCK_STREAM;
	hints.ai_flags = AI_PASSIVE;

	getaddrinfo(NULL, puerto, &hints, &servinfo);

	// Creamos el socket de escucha del servidor
	socket_servidor = socket(servinfo->ai_family, servinfo->ai_socktype, servinfo->ai_protocol);

	if (setsockopt(socket_servidor, SOL_SOCKET, SO_REUSEADDR, &(int){1}, sizeof(int)) < 0) 
	{
    	log_error(logger, "setsockopt(SO_REUSEADDR) failed 2");
	}
	// Asociamos el socket a un puerto
	bind(socket_servidor, servinfo->ai_addr, servinfo->ai_addrlen);

	// Escuchamos las conexiones entrantes
	listen(socket_servidor, SOMAXCONN);

	freeaddrinfo(servinfo);
	log_trace(logger, "Listo para escuchar a mi cliente");

	return socket_servidor;
}
```

```c
void server_para_kernel() // Atiendo al cliente
{
    socket_servidor_dispatch = iniciar_servidor(config_cpu->puerto_escucha_dispatch, log_cpu);
    if (socket_servidor_dispatch == -1)
    {
	    log_info(log_cpu, "ERROR: No se pudo iniciar CPU como servidor para KERNEL");
        exit(1);
    }

	log_info(log_cpu, "Esperando a KERNEL...");

    socket_cliente_kernel = esperar_cliente(socket_servidor_dispatch, log_cpu);
}

// Server para recibir interrupciones de Kernel ---------------------------------------------------------------------------------------

void interrupcion_para_kernel()
{	
    socket_servidor_interrupt = iniciar_servidor(config_cpu->puerto_escucha_interrupt, log_cpu);
    if(socket_servidor_interrupt == -1)
    {
	    log_info(log_cpu, "Error: No se pudo iniciar CPU como servidor para Kernel");
        exit(1);
    }

	log_info(log_cpu, "CPU listo para recibir interrupcion de Kernel");
    socket_interrupt_kernel = esperar_cliente(socket_servidor_interrupt, log_cpu);
}
```

```c
//********* DESARROLLO DE LA CONEXIÓN KERNEL - CPU *********
int conexion_a_cpu(t_log* log_kernel, kernel_config* config_kernel){
    int conexion_kernel_cpu = crear_conexion(config_kernel->ip_cpu, config_kernel->puerto_cpu_dispatch);
    if(conexion_kernel_cpu == -1){
        log_info(log_kernel , "ERROR: No se pudo establecer la conexión Kernel-CPU");
        exit(1);
    }
    log_info(log_kernel , "Conexión con el servidor CPU creada con éxito");
    enviar_mensaje("Hola CPU, soy Kernel",conexion_kernel_cpu);
    return conexion_kernel_cpu;
}

//********* DESARROLLO DE LA INTERRUPCION KERNEL - CPU *********
int interrupcion_a_cpu(t_log* log_kernel, kernel_config* config_kernel){
    int interrupcion_kernel_cpu = crear_conexion(config_kernel->ip_cpu, config_kernel->puerto_cpu_interrupt);
    if(interrupcion_kernel_cpu == -1){
        log_info(log_kernel , "ERROR: No se pudo establecer la interrupcion Kernel-CPU");
        exit(1);
    }
    log_info(log_kernel , "Interrupcion de Kernel a CPU");
    enviar_mensaje("Se establecio conexion con CPU a traves del puerto Interrupt",interrupcion_kernel_cpu);
    return interrupcion_kernel_cpu;
}
```

Entendemos que supuestamente no hay nadie esperando la conexion de kernel (INTERRUPT), pero si tenemos el servidor esperando. Lo que nos confunde ademas es que algunas veces conecta sin problemas y otras veces no.

**Comment by RaniAgus** [comment]
Veo que en `iniciar_servidor` no hay ningún manejo de errores. ¿Es posible que esté arrojando algún fallo el `bind()` o el `listen()`?

Si alguno de esos falla, no va a haber nadie escuchando en el puerto y, por ende, nadie se va a poder conectar

**Comment by mamusante** [comment]
Hola, agregamos estas verificaciones en iniciar_servidor 

```c

int iniciar_servidor(char* puerto, t_log* logger)
{
	// Preparamos al receptor para recibir mensajes
	int socket_servidor;

	struct addrinfo hints, *servinfo;

	memset(&hints, 0, sizeof(hints));
	hints.ai_family = AF_INET;
	hints.ai_socktype = SOCK_STREAM;
	hints.ai_flags = AI_PASSIVE;

	getaddrinfo(NULL, puerto, &hints, &servinfo);


	// Creamos el socket de escucha del servidor
	socket_servidor = socket(servinfo->ai_family, servinfo->ai_socktype, servinfo->ai_protocol);

	if (setsockopt(socket_servidor, SOL_SOCKET, SO_REUSEADDR, &(int){1}, sizeof(int)) < 0) 
	{
    	log_error(logger, "setsockopt(SO_REUSEADDR) failed 2");
	}
	// Asociamos el socket a un puerto
	//chequear que no sea -1
	if(bind(socket_servidor, servinfo->ai_addr, servinfo->ai_addrlen) == -1)
	{
		log_error(logger, "No se pudo hacer correctamente el bind");
		log_error(logger, "Terminando servidor ...");
		exit(1);
	}

	// Escuchamos las conexiones entrantes
	//chequear que no sea -1
	if(listen(socket_servidor, SOMAXCONN) == -1)
	{
		log_error(logger, "No se pudo hacer correctamente el listen");
		log_error(logger, "Terminando servidor ...");
		exit(1);
	}

	freeaddrinfo(servinfo);
	log_trace(logger, "Listo para escuchar a mi cliente");

	return socket_servidor;
}

```

Igualmente no falla en esos, no aparece ninguno de esos mensajes de error , aparece esto:

[INFO] 13:03:05:800 Kernel/(2026:2026): Conexión con el servidor CPU creada con éxito
Error al conectar: Connection refused
Error: No se pudo conectar a ningún servidor
[INFO] 13:03:05:809 Kernel/(2026:2026): ERROR: No se pudo establecer la interrupcion Kernel-CPU
==2026==
make[1]: *** [makefile:57: run] Error 1
make[1]: Leaving directory '/home/utnso/so-deploy/tp-2024-1c-No-me-quemes/kernel'
make: *** [makefile:53: start] Error 2

Lo que nos parece raro es que por la conexion dispatch se conecta pero por la interrupt no, los logs de error que aparecen son los de esta funcion

```c

int crear_conexion(char *ip, char *puerto) {
    struct addrinfo hints;
    struct addrinfo *server_info;
    struct addrinfo *p;
    int socket_cliente;
    int conexion;
    int status;

    // Inicializamos la estructura hints
    memset(&hints, 0, sizeof(hints));
    hints.ai_family = AF_INET;       // IPv4
    hints.ai_socktype = SOCK_STREAM; // TCP
    hints.ai_flags = 0;              // No usamos flags adicionales

    // Obtenemos información de la dirección del servidor
    if ((status = getaddrinfo(ip, puerto, &hints, &server_info)) != 0) {
        fprintf(stderr, "Error en getaddrinfo: %s\n", gai_strerror(status));
        return -1;
    }

    // Recorremos las direcciones posibles
    for (p = server_info; p != NULL; p = p->ai_next) {
        // Creamos el socket del cliente
        socket_cliente = socket(p->ai_family, p->ai_socktype, p->ai_protocol);
        if (socket_cliente == -1) {
            perror("Error al crear el socket");
            continue; // Intentamos con la siguiente dirección
        }

        // Conectamos el socket del cliente con el del servidor
        if (connect(socket_cliente, p->ai_addr, p->ai_addrlen) == -1) {
            perror("Error al conectar");
            close(socket_cliente);
            continue; // Intentamos con la siguiente dirección
        }

        // Conexión exitosa
        break;
    }

    // Liberamos la memoria de la información de la dirección
    freeaddrinfo(server_info);

    // Verificamos si hemos salido del loop sin éxito
    if (p == NULL) {
        fprintf(stderr, "Error: No se pudo conectar a ningún servidor\n");
        return -1;
    }

    return socket_cliente;
}

```

```c
int conexion_a_cpu(t_log* log_kernel, kernel_config* config_kernel){
    int conexion_kernel_cpu = crear_conexion(config_kernel->ip_cpu, config_kernel->puerto_cpu_dispatch);
    if(conexion_kernel_cpu == -1){
        log_info(log_kernel , "ERROR: No se pudo establecer la conexión Kernel-CPU");
        exit(1);
    }
    log_info(log_kernel , "Conexión con el servidor CPU creada con éxito");
    enviar_mensaje("Hola CPU, soy Kernel",conexion_kernel_cpu);
    return conexion_kernel_cpu;
}

//********* DESARROLLO DE LA INTERRUPCION KERNEL - CPU *********
int interrupcion_a_cpu(t_log* log_kernel, kernel_config* config_kernel){
    int interrupcion_kernel_cpu = crear_conexion(config_kernel->ip_cpu, config_kernel->puerto_cpu_interrupt);
    if(interrupcion_kernel_cpu == -1){
        log_info(log_kernel , "ERROR: No se pudo establecer la interrupcion Kernel-CPU");
        exit(1);
    }
    log_info(log_kernel , "Interrupcion de Kernel a CPU");
    enviar_mensaje("Se establecio conexion con CPU a traves del puerto Interrupt",interrupcion_kernel_cpu);
    return interrupcion_kernel_cpu;
}

```

Si nos podrian ayudar a ver donde podemos poner otro log para encontrar el problema u otra idea para arreglar las conexiones, en la grafica anda bien.

**Comment by iago64** [comment]
Buenas! Cómo va?

Pueden pasar los valores de config que estan usando a la hora de correr las pruebas?

Saludos.-

**Comment by mamusante** [comment]
Configs de CPU

IP_MEMORIA=127.0.0.1
PUERTO_MEMORIA=8002
PUERTO_ESCUCHA_DISPATCH=8006
PUERTO_ESCUCHA_INTERRUPT=8007
CANTIDAD_ENTRADAS_TLB=32
ALGORITMO_TLB=FIFO

Configs de Kernel

PUERTO_ESCUCHA=8003
IP_MEMORIA=127.0.0.1
PUERTO_MEMORIA=8002
IP_CPU=127.0.0.1
PUERTO_CPU_DISPATCH=8006
PUERTO_CPU_INTERRUPT=8007
ALGORITMO_PLANIFICACION=FIFO
QUANTUM=2750
RECURSOS=[RECURSO]
INSTANCIAS_RECURSOS=[1]
GRADO_MULTIPROGRAMACION=10

Configs de memoria

PUERTO_ESCUCHA=8002
PATH_INSTRUCCIONES=/home/utnso/scripts-pruebas
TAM_MEMORIA=1024
TAM_PAGINA=32
RETARDO_RESPUESTA=1000

**Comment by iago64** [comment]
Buenas! Cómo va?

Gracias, ya al menos descartamos un tema de puertos cruzados jeje, ahora te pregunto otra cosa, con que configuración tienen las VMs? Te puedo pedir que subas una captura de la configuración de Red?

Saludos.-

**Comment by martinAguirreRuiz** [comment]
Ya lo solucionamos, Kernel se queria conectar a CPU antes de que se llegue a habilitar el puerto correspondiente de INTERRUPT. Pusimos un semaforo y listo, gracias.
