### ISSUE TITLE
Problema con ejecución de Salvation's Edge

### ISSUE THREAD

**Issue by zoemancini** [sisoputnfrba/foro#4205]
Hola, cómo están? Estamos teniendo un problema con el Salvation's Edge que no estamos pudiendo resolver. Todas las otras pruebas corren correctamente y los outputs son los esperados.

Lo que nos sucede es que la prueba falla de forma aleatoria. La arrancamos a correr y siempre corre un rato antes de tirarnos un Segmentation Fault (10-15 minutos corriendo). Detenemos la planificación y la volvemos a arrancar sin problemas durante la ejecución. Corrimos htop mientras la ejecutábamos para poder chequear el uso de memoria y cpu mientras la corremos, y la cpu no pasa de 10% mientras que la memoria queda clavada en un valor fijo. 
Luego de un rato (no es siempre la misma cantidad de tiempo) nos tira un seg fault, y la debuggeamos para poder encontrar qué produce el error y notamos que siempre pasa con el PID múltiplo de 3 (proceso CIRCLE)  y PC 6, y el segfault se produce porque le llega a memoria una petición de una página que no existe. 
El problema es que la petición de la página que no existe se produce porque en esa instrucción MOV_OUT en el registro EAX está el valor 111 (lo cual traduce a una página que no existe) cuando debería solamente tener un 1.
El proceso CIRCLE sólo lo corrimos y no lo pudimos hacer fallar.

Estamos un poco perdidos ya por dónde encarar el error, sobre todo porque sucede luego de mucho tiempo de correr la prueba y no hay una forma fácil de reproducirlo. Escribo este issue para ver si llegan a tener alguna idea o recomendación de lo que podemos intentar para solucionarlo.

Muchas gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

Es un error bastante raro, pero igual si el TP llega a estar 10 minutos corriendo y no tiene memory leaks ni nada esta bien, no se quemen mucho.

Saludos.-
