### ISSUE TITLE
Duda Registros CPU

### ISSUE THREAD

**Issue by juanandreacchio** [sisoputnfrba/foro#4206]
Buenas, teníamos una duda con los registros del cpu. Cada PCB tiene acceso/modifica a los mismos registros o cada PCB (suena medio raro pero nos surgió esa duda) tiene sus propios registros.
Es decir, el proceso A hace SET AX 1, cuando pase a ejecutar el proceso B AX tiene que estar en 1?
Saludos y Muchas Gracias

**Comment by iago64** [comment]
Buenas! Cómo va?

Los registros pertenecen al proceso.

Saludos.-

**Comment by juanandreacchio** [comment]
Perfecto, muchas gracias
