### ISSUE TITLE
Laboratorio: errores al conectar dos computadoras en un sentido, pero a la inversa no

### ISSUE THREAD

**Issue by mvargassoto** [sisoputnfrba/foro#4208]
Buenas, con mi grupo estuvimos probando en el laboratorio el TP, se probó de a dos computadoras 2 dias distintos. El primer dia no tuvimos problemas. Hoy probando en otras dos computadoras distintas nos encontramos con segmentations a la hora de levantar modulos, revisamos todo y al no haber cambios desde la ultima vez que probamos confiamos en que nuestro TP funciona correctamente y esta bien configurado, por lo que intercambiamos el par de modulos de una maquina con el otro par que estaba en la otra maquina y funcionó todo perfecto. Cómo deberiamos tratar esta situacion si pasa el dia de la entrega?

**Comment by mefederico** [comment]
Hola buenas! 

Es muy raro lo que comentas de cambiar de módulos en las maquinas solucione el problema, lo que te puedo decir que el día de las pruebas ustedes levantan las pruebas y corren el test que quieran para confirmar que todo anda, una vez esto recién comenzamos con las pruebas. Por lo que podrían switchear los módulos hasta que les funcione correctamente

Dicho esto, mañana es un día con histórico de grupos anotados por lo que el tiempo apremia

Saludos!

**Comment by mvargassoto** [comment]
buenisimo, muchas gracias por la aclaración!
