### ISSUE TITLE
Resultados no esperados en pruebas de FS

### ISSUE THREAD

**Issue by tomassantolaria** [sisoputnfrba/foro#4210]
Estamos teniendo un problema cuando corremos las pruebas de FS. Cuando lo corremos por primera vez nos da los resultados esperados. Pero cuando lo volvemos a correr nos devuelve un resultado distinto. En la primer ocasión nos borra bien el archivo1.txt y se escribe todo bien en el bloques.dat pero al correrlo de nuevo, el archivo1.txt se borra pero en el bloques.dat sigue ocupado su espacio.

Así nos figura el  bloques.dat después de correrlo por segunda vez.
![Captura de pantalla 2024-07-26 163732](https://github.com/user-attachments/assets/263d8830-dc47-4e0e-88df-8bf0d63c516d)

**Comment by iago64** [comment]
Buenas! Cómo va?

La prueba no se tiene que correr 2 veces, si la corres mas de 1 vez tenes que eliminar los archivos de metadata porque estarias intentando crear archivos que ya existen y eso no esta contemplado.

Saludos.-

**Comment by tomassantolaria** [comment]
Gracias
