### ISSUE TITLE
Consulta picos de CPU

### ISSUE THREAD

**Issue by AscarlatoUTN** [sisoputnfrba/foro#4211]
Buenas, con mi equipo estuvimos probando salvations edge, y dependiendo de la computadora que agarremos de los labos de medrano, en el módulo de KERNEL, en algunas podemos estar en un valor constante menor a 5% de uso de CPU, mientras que en otras cada tanto tenemos picos de 100%, pero se normaliza a bajos porcentajes rápidamente. Eso resultaría un problema?
Creemos no tener esperas activas

**Comment by iago64** [comment]
Buenas! Cómo va?

Solo para estar seguros, estan revisando que sean sus procesos y no alguno otro?

Saludos.-

**Comment by AscarlatoUTN** [comment]
No te puedo afirmar si es nuestro o no, pero al ser la VM server con ún sólo módulo, no se que tantos procesos puedan llegar a afectar...
En caso de ser nuestro, que tanto problema hay? De memoria vamos bien.

**Comment by iago64** [comment]
Buenas! Cómo va?

En principio para saber si es tu TP lo podes filtrar con `htop`, si es tu proceso el que tiene esos picos puede ser una espera activa, si es alguna cosa del SO en background que a veces pasa que por ej busca actualizaciones no hay problema.

Saludos.-

**Comment by AscarlatoUTN** [comment]
Imagino que será del SO, porque si fuera una espera activa, lo sufriría en todas las computadoras. Desde ya, muchas gracias. 
Saludos
