### ISSUE TITLE
Duda prueba Memoria y TLB (MEMORIA_2)

### ISSUE THREAD

**Issue by Ivanabete** [sisoputnfrba/foro#4212]
Buenas tardes!
Tengo una duda con la prueba de Memoria y TLB, específicamente con el que sería el proceso MEMORIA_2.
Busqué a ver si algún issue hablaba de esto pero no encontré ninguno.

"En la ejecución del proceso MEMORIA_2 se observa que puede recuperar correctamente el valor de la memoria que se encuentra en 2 páginas diferentes."

El proceso MEMORIA_2 es:
SET EAX 0
SET EBX 10
SET EDX 0
SET ECX 1
SET DX 30
RESIZE 60
MOV_OUT DX EBX
MOV_IN EAX DX
SUB EBX ECX
SET EAX 0
EXIT

Lo que no me queda claro es cómo se podría ver con esa prueba si se recuperó correctamente el valor que se encuentra en 2 páginas diferentes.
Primero, se carga el valor de EBX en la dirección lógica de DX.
Después, se carga en EAX lo que está en la dirección lógica de DX.
O sea, si todo funcionó bien, EBX == EAX.

Entonces, para poder verificar que el funcionamiento sea correcto, ¿no habría que hacer SUB EBX EAX y que la resta de 0?
No entiendo cuál es la idea del SUB EBX ECX.

Si intentáramos ver la reconstrucción del contenido de memoria a través de los logs no se llega a apreciar mucho, ya que como el dato se reconstruye en partes, no parece tener mucho sentido lo que hay en los logs, ya que serían "bytes sueltos".

Para sintetizar la duda, ¿cómo me doy cuenta si se recuperó correctamente el valor?

Desde ya, muchas gracias.

**Comment by iago64** [comment]
Buenas! Cómo va?

Es facil, tenes logs obligatorios que nos permiten ver que valores leen de la memoria.

Saludos.-
