### ISSUE TITLE
No aparece la consola interactiva

### ISSUE THREAD

**Issue by PabloV2003** [sisoputnfrba/foro#4213]
Estamos en Medrano corriendo las pruebas, se realizan todas las conexiones correctamente entre los modulos pero luego de ejecutar " ./bin/kernel kernel_deadlock.config" no aparece el ">" del readline de la consola. Cuando realizamos las pruebas en Visual Studio estas corren perfectamente.

Probamos igualmente pasar un script, como por ejemplo "EJECUTAR_SCRIPT /scripts_kernel/PRUEBA_DEADLOCK", y simplemente no pasa nada.

![Captura](https://github.com/user-attachments/assets/69fbc32e-7a4d-47fd-af77-1377bd84385d)

**Comment by iago64** [comment]
Buenas! Cómo va?

Si eso lo corren directamente en la terminal de la VM server en lugar de en putty también les pasa?

Saludos.-

**Comment by joaquingandola** [comment]
Buenas, estoy en el grupo de Pablo, sumo a lo que lo subió una captura de que efectivamente en el visual funciona todo. 
![image](https://github.com/user-attachments/assets/321839cd-c671-4a06-a88f-99854329bef9)

**Comment by RaniAgus** [comment]
¡Buenas! ¿Si corren el programa con Valgrind les aparece algún error de manejo de memoria en el hilo que atiende la consola? Saludos

**Comment by PabloV2003** [comment]
Hola! Ahi solucionamos el problema cierro el issue, muchas gracias.
