### ISSUE TITLE
Duda retardos de Memoria entre modulos.

### ISSUE THREAD

**Issue by lucasluna068** [sisoputnfrba/foro#4215]
Buenas, tengo una consulta con el retardo de la memoria. 

Las peticiones que se hacen a la memoria ya sea de Kernel, CPU y E/S. Deberían tener un tiempo de retardo entre si también? De panera sean "Excluyentes" los pedidos a memoria?

Es decir: retardo,  Pedido de Kernel, retardo, Pedido de CPU, retardo, Pedido de E/S1, retardo, Pedido de CPU, retardo, Pedido de E/S2, retardo... etc.

O se deberían poder manejar todos los pedidos de manera individual simultáneamente:
    -Retardo, Pedido de Kernel.
    -Retardo, Pedido de CPU, retardo, Pedido de CPU.
    -Retardo, Pedido de E/S1.
    -Retardo, Pedido de E/S2.

Estuve leyendo el issue #3983 y entiendo que cada petición se debe tomar de manera individual dentro del mismo modulo pero no me quedo claro si pueden ser a la vez entre distintos.

**Comment by iago64** [comment]
Buenas! Cómo va?

El retardo aplica a **todas** las peticiones a memoria y cada petición se maneja de manera independiente, no importa si vienen de CPU, Kernel o interfaces de I/O

Saludos.-

**Comment by lucasluna068** [comment]
Quedo claro! Muchísimas gracias!
