### ISSUE TITLE
Problemas al ejecutar varias interfaces

### ISSUE THREAD

**Issue by zakerik10** [sisoputnfrba/foro#4216]
Buenas

Tengo un problema al querer ejecutar las pruebas, por ejemplo la de FS, que utiliza 3 interfaces, la FS, TECLADO y MONITOR
Por cómo están hechas las cosas, cuando hago funcionar todo con una sola interfaz, funciona bien. Ejecuta todo lo que tiene que ejecutar, y termina si tiene que terminar.

El problema es cuando ya conecto varias interfaces

Pasa lo siguiente: Enciendo las 3 interfaces, conectan bien, ejecuto la prueba FS_1, que por io primero crea los 2 archivos salida.txt y cronologico.txt y después hace los IO_FS_TRUNCATE.

Lo que pasa y se ve por la consola de Kernel es lo siguiente:

```
iniciar_proceso scripts_memoria/FS_1
[INFO] 04:14:44:559 Kernel/(59769:59784): Se crea el proceso 1 en NEW
[INFO] 04:14:44:559 Kernel/(59769:59785): PID: 1 - Estado Anterior: NEW - Estado Actual: READY
[INFO] 04:14:44:560 Kernel/(59769:59785): Cola Ready: [ 1 ]
[INFO] 04:14:44:560 Kernel/(59769:59786): PID: 1 - Estado Anterior: READY - Estado Actual: EXEC

Me devolvio PCB PID: 1
El PCB salio por IO
[INFO] 04:14:44:735 Kernel/(59769:59787): PID: 1 - Estado Anterior: EXEC - Estado Actual: BLOCKED
[INFO] 04:14:44:737 Servidor/(59769:60606): La interfaz 'FS' está conectada

Algun IO terminó con algun PCB
Read 1: 1
[INFO] 04:14:44:738 Kernel/(59769:60202): PID: 1 - Estado Anterior: BLOCKED - Estado Actual: READY
[INFO] 04:14:44:738 Kernel/(59769:60202): Cola Ready: [ 1 ] 
[INFO] 04:14:44:738 Kernel/(59769:59786): PID: 1 - Estado Anterior: READY - Estado Actual: EXEC

Me devolvio PCB PID: 1
El PCB salio por IO
[INFO] 04:14:44:823 Kernel/(59769:59787): PID: 1 - Estado Anterior: EXEC - Estado Actual: BLOCKED
[INFO] 04:14:44:827 Servidor/(59769:60608): La interfaz 'FS' está conectada
```

Y hasta ahí llega

Básicamente ejecuta las primeras 2 instrucciones que tengan que ver con FS, que son los 2 IO_FS_CREATE, y no sigue ejecutando mas

Nos dimos cuenta que a partir de aca, la interfaz hace la devolución de cuando termina de trabajar, pero Kernel no reacciona, y no entendemos el por qué no lo hace

Esta función es la que se encarga de recibir a las interfaces que se van conectando
```
void server()
{
	int kernelFD = initServer(PUERTO_ESCUCHA);
	log_info(log, "Kernel ready to receive");
	while(1) {
		int clientFD = andHandshakeForAll(kernelFD);
		printf("Entro el socket %d\n", clientFD);
		addNewIo(clientFD);
		pthread_t tidProcessClient;
		pthread_attr_t attr;
		pthread_attr_init(&attr);
		pthread_create(&tidProcessClient, &attr, operate, (void*)&clientFD);
		pthread_detach(tidProcessClient);
	}
}
```

addNewIo es una función que se encarga de guardar el socket de la nueva interfaz para usarla mas adelante
Después creo un hilo para ejecutar las operaciones que se tenga que hacer con esa interfaz

Sospechamos que el problema puede estar por aca, por que probamos hacer pthread_join para ver que pasaba, pero se conectaba solo la primer interfaz, que en este caso era FS, pero las demás no, y asi si seguía ejecutándose lo demás, como el truncate que sigue en las instrucciones 

Tenemos el mismo problema en las pruebas de io, ya que tambien usa varias interfaces

**Comment by iago64** [comment]
Buenas! Cómo va?

El hecho de que solo les conectara una sola interfaz al poner `pthread_join()` viene de la mano de que esa función va a detener la ejecución hasta que termine le thread al cual le quieren hacer join.

Ahora les pregunto, intentaron debuguear la solución? me suena a que el problema que estan teniendo viene por el lado del `cliendFD` que al llegar al intentar hacer el recv() puede que lo hayan pisado, por las dudas revisen de no haber pisado las referencias.

Saludos.-

**Comment by zakerik10** [comment]
Pareciera que era ese el problema, se pisaban las variables

Lo solucionamos pasando por parámetro lo que se guarda en el addNewIo al operate.

Gracias.
Cierro issue.
