### ISSUE TITLE
DUDA RETRASO COMPACTACION

### ISSUE THREAD

**Issue by bautistaiglesias** [sisoputnfrba/foro#4217]
Buenas, es una pregunta sencilla pero me quiero asegurar, el retraso compactación lo tengo que hacer siempre que trunco un archivo, o solo cuando el archivo no tiene bloques contiguos, osea cuando lo muevo a otra parte del fs? obviamente ademas de hacerlo cuando realizamos la compactacion

**Comment by iago64** [comment]
Buenas! Cómo va?

Solo tienen que aplicar el retardo de comptactación cuando no tiene bloques contiguos y tienen que hacer algo, ya sea mover el archivo o compactar todo el FS.

Saludos.-

**Comment by tinchotricolor22** [comment]
> Buenas! Cómo va?
> 
> Solo tienen que aplicar el retardo de comptactación cuando no tiene bloques contiguos y tienen que hacer algo, ya sea mover el archivo o compactar todo el FS.
> 
> Saludos.-

Una pregunta super simple sobre esta. Se tiene que esperar en segundos o en milisegundos?
