### ISSUE TITLE
Duda prueba planificacion

### ISSUE THREAD

**Issue by FeliFemenia** [sisoputnfrba/foro#4218]
Buenas, una consulta con respecto a al prueba de planificación. Cuando ejecutamos la prueba con el algoritmos de la planificación VRR, el proceso con el script de PLANI_3 se debería desalojar 3 veces, pero a nosotros se nos desaloja solo 2 veces. 
De igual manera verificamos que se seleccionen bien los procesos (ósea que se agarre de la lista auxiliar cuando haya alguno) y que los quantums de los pcbs se vayan modificando. 
Nosotros creemos que el problema seria porque justo se llega a ejecutar una instrucción de mas. Habría algún problema con eso?

**Comment by iago64** [comment]
Buenas! Cómo va?

Por las dudas, se hicieron un gantt teniendo como "unidad" de tiempo las instrucciones? Ya que aprox cada instrucción debería tomarles 1 segundo (1000ms) y los quantum son de 2750ms, es decir que si cumplen bien los ciclios de instrucción deberían poder ejecutar 3 instrucciones.

Saludos.-

**Comment by FeliFemenia** [comment]
Buenas. Si hicimos el gantt, y los procesos ejecutan en el orden correcto. El problema que estamos teniendo es que por ejemplo, un proceso con quantum igual a 750, llega a ejecutar dos instrucciones. Es como que se mete una instrucción de mas.

**Comment by iago64** [comment]
Buenas! Cómo va?

Estamos de alineados si te digo que si tienen un retardo de 1000ms en las peticiones a memoria, no puede ser que estén entrando 2 instrucciones si mandan a ejecutar con un quantum de 750ms y que después de la primera deberían desalojar no?

Saludos.-

**Comment by FeliFemenia** [comment]
Buenas. es verdad. Veremos como solucionarlo, gracias!!
