### ISSUE TITLE
Inicialización del archivo bloques.dat

### ISSUE THREAD

**Issue by Luu19** [sisoputnfrba/foro#4219]
Buenas! Qué tal?
Quería saber si alguna forma de inicializar el bloques.dat en 0 o que esté "limpio", ya que cuando hacemos el comando `hexdump -C bloques.dat` si bien se ve el contenido que tiene que tener (Fallout, ...) también hay como contenido "basura" pero en el bitmap no se registra como que esté ocupado ese espacio, es decir que los archivos, según la información que guardamos en los configs, se inicializan en los bloques correctos.
Adjunto una parte del código:
```C
...
FILE* file = fopen("/home/utnso/dialfs/bloques.dat", "rb+"); 
    if (file != NULL){
        log_debug(logger, "el archivo %s ya existia", "bloque.dat");
        fclose(file);
    } else {
        file = fopen("/home/utnso/dialfs/bloques.dat", "wb+"); 
        log_debug(logger, "el archivo %s no existia", "bloque.dat");

        if (file == NULL){
            log_error(logger, "Error al inicializar bloques.dat");
            exit(EXIT_FAILURE);
        }

        size_t tamanio_bloques = config_IO->block_size * config_IO->block_count;
        if (ftruncate(fileno(file), tamanio_bloques) == -1) {
            log_error(logger, "Error al establecer el tamanio del archivo bloques");
            fclose(file);
            exit(EXIT_FAILURE);
        }
        fclose(file);
    }
```

Desde ya, muchas gracias ❤️

**Comment by iago64** [comment]
Buenas! Cómo va?

No hay ningún problema con que el archivo tenga basura, mientras que lo que uds graben este bien esta perfecto.

Saludos.-

**Comment by Luu19** [comment]
Buenísimo, muchas gracias Dami ❤️
