### ISSUE TITLE
Duda Planificación

### ISSUE THREAD

**Issue by FeliFemenia** [sisoputnfrba/foro#4221]
Buenas. Estamos corriendo la prueba de planificación, y cuando la ejecutamos con el algoritmo VRR, hay un momento que el proceso con PLANI_2 tiene que ejecutar una sola instrucción pero tiene un quantum entero (ósea de 2750).  El problema es que el proceso que debería pasar a ejecutar seria el PLANI_4, pero vuelve a ejecutar el PLANI_2 porque a pesar de hacer la entrada salida en genérica, el hilo que planifica hace el usleep como si PLANI_2 hubiera ejecutado el quantum entero. Entonces le da tiempo al PLANI_2 a ejecutar y meterse en la lista ready de prioridad. No sabríamos si esto es valido o no. Porque deberíamos como interrumpir un usleep y no sabríamos como hacerlo. 

Esta es la funcion del hilo planificacor: 

```c
case VRR:

                exec_global = verificar_lista_aux();

                if(exec_global -> contexto -> estado != EXEC){
                    log_info(logger_obligatorio,"PID: <%d> - Estado Anterior: <%s> - Estado Actual: <%s>", exec_global -> contexto -> pid, array_estados[exec_global -> contexto -> estado],array_estados[3]);
                    exec_global ->contexto -> estado = EXEC;
                }

                send_pcb(exec_global, cpu_dispatch_fd, EXEC_PCB);

                usleep(exec_global -> quantum * 1000);

                if(exec_global != NULL){
                    int_interrupcion = FIN_QUANTUM;
                    send(cpu_interrupt_fd,&int_interrupcion,sizeof(int),0);
                }
                break;
               
```

**Comment by iago64** [comment]
Buenas! Cómo va?

Es posible que el problema que esten teniendo venga por como actualizan esa variable de quantum cuando vuelven desalojados por una instrucción de IO?

Saludos.-

**Comment by FeliFemenia** [comment]
Buenas. Como va?
En realidad el problema no es que se actualice mal el quantum. Sino que por ejemplo un proceso tiene 4 instrucciones (no bloqueantes) con un quantum que permite ejecutar 3 instrucciones. Entonces va a ejecutar 3 instrucciones y luego se va a desalojar por fin de quantum. En la próxima vez que le toque ejecutar, va a tener un quantum completo otra vez, por lo que el usleep va a ser de un quantum de 3, pero en realidad el proceso va a usar solo una instrucción. 

Igualmente lo resolvimos de una manera, nose si será la mejor pero es la forma que vimos de solucionarlo. Lo que hicimos es hacer correr el usleep correspondiente adentro de un hilo y cuando termina preguntar (con 2 variables booleanas y un semaforo) si ese proceso ya fue desalojado (por otro motivo que puede ser su finalización o una syscall) antes que su quantum termine o no. Entonces si se desaloja el proceso antes que finalice el quantum, se hace un post del semáforo para que ingrese otro proceso al procesador (sin importar el quantum del anterior proceso porque ya no esta ejecutando mas). En caso de que el proceso no haya sido desalojado por otra cosa, el hilo que corrió el usleep hace un post del semáforo para desalojar al proceso por fin de quantum.

**Comment by iago64** [comment]
Buenas! 

Algo no me cuadra de lo que estan implementando, me estas diciendo que si por ejemplo el proceso A tiene 3 quantum, ejecuta 2 y se desaloja por IO, el proceso B que viene despues ejecuta solo el quantum restante que le quedaba al proceso A? Si es asi, estaría mal, el proceso B debería ejecutar sus 3 quantum y cuando vuelva a ejecutar el proceso A debería ejecutar 1 y desalojar.

Saludos.-

**Comment by FeliFemenia** [comment]
Buenas!

Nosotros como lo implementamos, si el proceso A tenia 3 de quantum y ejecuta 2 instrucciones una no bloqueante y otra de io, se desaloja y queda con un quantum de uno. Luego el proceso B ejecuta con un quantum de 3, no es que ejecuta con el quantum que le sobraba al proceso A. 

El problema que teniamos es que nosotros manejamos la interrupcion de desalojo con un usleep del lado de kernel. 
Entonces en el caso del proceso A cuando ejecutaba se iba a hacer un usleep de quantum 3, cuando el proceso A solo iba a ejecutar 2 instrucciones y se bloqueaba. Por ende iba a haber un tiempo de una instruccion en la que kernel no iba a pasar un proceso a ejecutar, porque el hilo de corto plazo estaba esperando a que se termine el usleep. 

Para eso lo solucionamos como puse arriba, teniendo en cuenta si el proceso A se habia desalojado antes de que se termine su quantum o no. Esto lo hicimos con el fin de que no haya ese retraso de "x" tiempo cuando en realidad el proceso ya habia sido desalojado.

**Comment by RaniAgus** [comment]
¡Buenas! Entonces, si entendí bien, lo que pasaba antes era más o menos lo siguiente:

<table>
<tr>
<td>
Hilo A
</td>
<td>
Hilo B
</td>
<td>
Hilo C
</td>
</tr>
<tr>
<td>

```js
while (true) {
  pcb = pop(ready) // bloqueante
  send(cpu_dispatch, pcb)
  sleep(quantum) // bloqueante
  send(cpu_interrupt)
}
```

</td>
<td>

```js
while (true) {
  pcb = recv(cpu_dispatch) // bloqueante
  // manejo del pcb...
  send(io, pcb)
}
```

</td>
<td>

```js
while (true) {
  pcb = recv(io) // bloqueante
  push(ready, pcb)
}
```

</td>
</tr>
</table>

> Supongamos que `pop(ready)` y `push(ready)` tienen internamente la lógica de separar en dos colas "ready" y "ready+"

Como bien decías, no deben haber ratos en los que la CPU quede idle si hay procesos en READY, entonces deberíamos poder atender inmediatamente tanto un `pop(ready)` como un `sleep(quantum)`, la solución es "partir" el hilo A en dos para que cada uno haga cada operación bloqueante en paralelo.

También por lo que comentan entiendo que el `send(cpu_interrupt)` solo se envía si no hubo un `recv(cpu_dispatch)` en el hilo B, lo cual está perfecto 👍🏻

Por último, un detalle es que el hilo A1 (el que tiene `pop(ready)`) y el B solo pueden ejecutar uno a la vez, ya que idealmente no deberían hacer `pop(ready)` si hay un proceso en EXEC, asi que una implementación más simple podría ser "combinar" ambos hilos:

```js
while (true) {
  pcb = pop(ready) // bloqueante
  send(cpu_dispatch, pcb)
  pcb = recv(cpu_dispatch) // bloqueante
  // manejo del pcb...
  send(io, pcb)
}
```

Igual esto último **no** es estructamente necesario, si mantienen ambos hilos separados y usan semáforos para que ejecuten alternadamente, las pruebas deberían dar igual que un VRR visto en la teoría, lo cual es lo importante para que esté bien 👍🏻

Saludos

**Comment by FeliFemenia** [comment]
Buenas. Muchas gracias por la respuesta. Ahora quedo todo mas claro.
