### ISSUE TITLE
Dudas FS: Esperar unidad de tiempo, achicar un archivo e inicializar bitarray

### ISSUE THREAD

**Issue by santgomez** [sisoputnfrba/foro#4223]
Hola buenas. Estaba terminando de cerrar todo lo relacionado al File System en mi TP y me surgieron unas dudas mientras repasaba lo que ya hice. Las enumero para que sean más fáciles de responder.

1) El enunciado menciona que las interfaces DialFS esperan una unidad de TIEMPO_UNIDAD_TRABAJO al ejecutar cualquier instrucción. Mi duda era ¿El usleep() correspondiente a esta espera debería hacerse antes o después de ejecutar dicha acción, o es indistinto? Lo que nosotros haciamos hasta ahora era este orden:
-Llega la orden a una interfaz DialFS de ejecutar una instrucción.
-La ejecuta.
-Espera 1 unidad de TIEMPO_UNIDAD_TRABAJO.
-Le avisa a Kernel que ya terminó de ejecutar.

Pero capaz la idea era que el usleep() se ejecute apenas le llega a la interfaz la instrucción a ejecutar.

2) ¿Se debe considerar la posibilidad de que, a través de la instrucción IO_FS_TRUNCATE, se quiera achicar el tamaño del archivo y, por lo tanto, liberar los bloques que el archivo ya no vaya a poder usar? Consulto porque no vi que el enunciado lo aclaré ni que aparezca un caso así en alguna prueba. Yo hasta ahora no había considerado esta posibilidad, y armé la ejecución del IO_FS_TRUNCATE de modo tal que siempre se espere que se vaya a aumentar el tamaño del archivo. Esta duda me surgió más que nada al leer los issues #4017 y #4119 , y ver que ahí hablaban un poco sobre desasignarle bloques a un archivo o achicar su tamaño.

3) ¿El bitarray que persistimos a través de archivo bitmap.dat debería inicializarse mediante el parámetro LSB_FIRST o MSB_FIRST, o da lo mismo? Yo siempre que inicializo el bitarray lo hago poniendo el parámetro MSB_FIRST ya que me queda más cómodo pensar que los bloques se ocupan empezando con el primer bloque lo más a la izquierda posible, y terminando con el ultimo bloque a la derecha del todo. Pero a la vez en las especificaciones de las commons se menciona que en la mayoría de implementaciones de bitmap se usa LSB_FIRST.

Dejo cita de la declaracion del typedef enum bit_numbering_t de las commons en bitarray.h :
>@brief Define el orden bajo el cual se guardarán los bits a la hora de llenar los bytes.
>@note  La mayoría de las implementaciones de bitmap usan LSB_FIRST. Si no estás seguro
>de cuál usar, probablemente quieras usar esta.

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Da igual el momento en el que hagan el `usleep()`, el mismo solo busca simular las diferencias de velocidades y traer la ejecución a tiempos humanos para poder entender lo que esta pasando.

2.- Debería considerarse, de todas formas las pruebas ya están subidas, pueden basarse en eso.

3.- Da lo mismo, mientras uds puedan lavantar un bitmap creado previamente por uds da lo mismo.

Saludos.-

**Comment by santgomez** [comment]
Gracias! Ya me quedó claro.
