### ISSUE TITLE
Duda orden de llegada Planificacion.

### ISSUE THREAD

**Issue by lucasluna068** [sisoputnfrba/foro#4225]
Buenas, estuvimos haciendo pruebas sobre VRR y RR en nuestro TP. 

Y tengo una duda como es el resultado esperado en la cantidad de ráfagas de CPU  y orden de ejecución. Ya que este se ve afectado por la "llegada de procesos a ready". Gracias al retardo de la memoria de 1 segundo al atender el KERNEL y el retardo de la memoria con el CPU (También de 1 segundo). (Nos realizamos un diagrama de Gantt para poder ver esto)

En el caso de PLANI_3 con VRR. Inicializan los procesos en orden 1,2,3,4. El proceso 1 ejecuta 3 ráfagas de CPU gracias al Quantum asignado. Pero al momento de salir el proceso 1 por fin de Quantum, llega la creación del proceso 4. Lo que, según entendimos, debería darle prioridad al proceso 1 en el orden de ejecución. (Esto ocurre así en nuestras pruebas).

Al momento de correr estas mismas pruebas, inicializando los procesos con la planificación detenida, los procesos primero se crean en memoria (En el instante 0 llegan todos) y desde ahí se realiza la planificación. Dando lugar a que en el momento de la vuelta del proceso 1 vaya al final de la cola y el proceso 4 tenga prioridad (Por haber estado antes en ready).

Mi consulta es mayormente con el primer caso. Esta bien que los procesos se creen a medida que van llegando con el retraso de la memoria? Y por lo tanto, tenga prioridad en la cola el proceso 1?

No estoy seguro si se entendió mi duda. No quise subir nuestro Gantt por las dudas. Pero creo que con eso se entendería mejor.

**Comment by iago64** [comment]
Buenas! Cómo va?

Si, esta bien que los procesos lleguen como se crean, ya que tenes el retardo de la memoria en ir aceptando cada proceso que se crea.

Saludos.-

**Comment by lucasluna068** [comment]
Muchisimas gracias!
