### ISSUE TITLE
Aborted (core dumped) en Pruebas de Salvation

### ISSUE THREAD

**Issue by matiasnu** [sisoputnfrba/foro#4226]
### 📔 Citas del documento de pruebas

Resultados esperados en pruebas de salvation.

### 👍 Comportamiento esperado

Estamos teniendo impresiones en pantalla visualizando la leyenda "Aborted (core dumped)" queriamos consultar si esto es un comportamiento esperado de la prueba y que este correcto imprimirlo.

**Comment by iago64** [comment]
Buenas! Cómo va?

Es uno de los output esperados, mas precisamente el del script Cube.

Saludos.-
