### ISSUE TITLE
Problema en prueba IO

### ISSUE THREAD

**Issue by AgustinaGuitman** [sisoputnfrba/foro#4227]
Buenas, estamos haciendo la prueba IO y nos esta pasando que cuando desalojamos un proceso por fin de quantum, este nunca llega a kernel y nos parece raro porque antes desalojamos otros procesos y continuo con su ejecución bien. 
Creemos que nunca vuelve de cpu ya que cuando ponemos PROCESO_ESTADO no nos aparece entre los procesos en ready. 
No sé si sirven los logs, cualquier cosa les podemos mandar parte de nuestro código.
Cualquier sugerencia se los agradeceríamos.
Saludos.

Esto es kernel:
```
[INFO] 16:05:19:639 KERNEL/(12249:12259): PID: <2> - Estado Anterior: READY - Estado Actual: EXEC


Solicitud de cpu
contexto 1
Listo desalojar
[INFO] 16:05:20:390 KERNEL/(12249:13039): PID: <2> - Desalojado por fin de Quantum
2 agarra bien el cod_op 44
listo desempaquetar contexto 2
[INFO] 16:05:20:558 KERNEL/(12249:12259): PID 2 Operacion recibida: 1431705031 

[INFO] 16:05:20:558 KERNEL/(12249:12259): PID: <2> - Estado Anterior: <EXEC> - Estado Actual: <READY>
[INFO] 16:05:20:558 KERNEL/(12249:12259): Cola Ready: [0,1,2]

[INFO] 16:05:20:558 KERNEL/(12249:12259): PID: <0> - Estado Anterior: READY - Estado Actual: EXEC


Solicitud de cpu
contexto 1
Listo desalojar
[INFO] 16:05:21:316 KERNEL/(12249:13050): PID: <0> - Desalojado por fin de Quantum

```
Esto es CPU:

```

[INFO] 16:05:19:537 CPU/(12115:12131): PID: <1> - OBTENER MARCO - Página: <0> - Marco: <8>
[INFO] 16:05:19:538 CPU/(12115:12131): PID: <1> - Dirección lógica: <3> - Dirección física: <131> - Página: <0> - Marco: <8>
[INFO] 16:05:19:538 CPU/(12115:12131): PID: <1> - Acción: <ESCRIBIR> - Dirección Física: <131> - Valor: <111>
[INFO] 16:05:19:639 CPU/(12115:12131): Me llego el mensaje: OK
[INFO] 16:05:19:639 CPU/(12115:12131): Proceso desalojado por motivo: 54
desempaquetar_contexto_ejecucion: proceso 2 

[INFO] 16:05:19:639 CPU/(12115:12131): PID: <2> - FETCH - Program Counter: <8>
INSTRUCCION FETCH COPY_STRING 26
[INFO] 16:05:19:740 CPU/(12115:12131): Program Counter actualizado: 9
 instruccion_decodificada->identificador DECODE 26
 instruccion_decodificada->identificador EXECUTE 26
[INFO] 16:05:19:740 CPU/(12115:12131): PID: <2> - Ejecutando: <COPY_STRING> - <26>
[INFO] 16:05:19:847 CPU/(12115:12131): PID: <2> - OBTENER MARCO - Página: <0> - Marco: <11>
[INFO] 16:05:19:847 CPU/(12115:12131): PID: <2> - Dirección lógica: <0> - Dirección física: <176> - Página: <0> - Marco: <11>
[INFO] 16:05:19:948 CPU/(12115:12131): PID: <2> - OBTENER MARCO - Página: <1> - Marco: <12>
[INFO] 16:05:19:948 CPU/(12115:12131): PID: <2> - Dirección lógica: <16> - Dirección física: <192> - Página: <1> - Marco: <12>
[INFO] 16:05:20:050 CPU/(12115:12131): PID: <2> - OBTENER MARCO - Página: <2> - Marco: <13>
[INFO] 16:05:20:050 CPU/(12115:12131): PID: <2> - Dirección lógica: <32> - Dirección física: <208> - Página: <2> - Marco: <13>
[INFO] 16:05:20:151 CPU/(12115:12131): PID: <2> - OBTENER MARCO - Página: <3> - Marco: <14>
[INFO] 16:05:20:151 CPU/(12115:12131): PID: <2> - Dirección lógica: <48> - Dirección física: <224> - Página: <3> - Marco: <14>
DESALOJAR PROC: pid_inter 2 pid 2
[INFO] 16:05:20:557 CPU/(12115:12131): Me llego el mensaje: DI��
[INFO] 16:05:20:558 CPU/(12115:12131): Proceso desalojado por motivo: 54
desempaquetar_contexto_ejecucion: proceso 0 

[INFO] 16:05:20:558 CPU/(12115:12131): PID: <0> - FETCH - Program Counter: <15>
DESALOJAR PROC: pid_inter 0 pid 0
```
y esto memoria:

```

 MOV_OUT BX AX
[INFO] 16:05:19:536 MEMORIA/(12007:12134): PID: <1> - Pagina: <0> - Marco: <8>
[INFO] 16:05:19:538 MEMORIA/(12007:12134): PID: <1> - Acción: <ESCRIBIR> - Dirección física: <131> - Tamaño <1>
[INFO] 16:05:19:639 MEMORIA/(12007:12134): BUSCANDO INSTRUCCION....

 COPY_STRING 26
[INFO] 16:05:19:846 MEMORIA/(12007:12134): PID: <2> - Pagina: <0> - Marco: <11>
[INFO] 16:05:19:947 MEMORIA/(12007:12134): PID: <2> - Pagina: <1> - Marco: <12>
[INFO] 16:05:20:049 MEMORIA/(12007:12134): PID: <2> - Pagina: <2> - Marco: <13>
[INFO] 16:05:20:151 MEMORIA/(12007:12134): PID: <2> - Pagina: <3> - Marco: <14>
[INFO] 16:05:20:151 MEMORIA/(12007:12134): PID: <2> - Accion: <LEER> - Direccion fisica: <176> - Tamaño <16>
[INFO] 16:05:20:252 MEMORIA/(12007:12134): PID: <2> - Accion: <LEER> - Direccion fisica: <192> - Tamaño <10>
[INFO] 16:05:20:355 MEMORIA/(12007:12134): La cadena leída es Sistemas Operativos 2c2023
[INFO] 16:05:20:355 MEMORIA/(12007:12134): PID: <2> - Acción: <ESCRIBIR> - Dirección física: <208> - Tamaño <16>
[INFO] 16:05:20:457 MEMORIA/(12007:12134): PID: <2> - Acción: <ESCRIBIR> - Dirección física: <224> - Tamaño <10>
[INFO] 16:05:20:558 MEMORIA/(12007:12134): BUSCANDO INSTRUCCION....

 SUM ECX EDX

```

 
### 💻 Logs
Lo corrimos con valgrind y nos dice esto:
==13553== Thread 2:
==13553== Invalid read of size 1
==13553==    at 0x484ED16: strlen (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==13553==    by 0x48EBD30: __vfprintf_internal (vfprintf-internal.c:1517)
==13553==    by 0x48FD499: __vsnprintf_internal (vsnprintf.c:114)
==13553==    by 0x486F3FF: _string_append_with_format_list (string.c:305)
==13553==    by 0x486E83F: string_from_vformat (string.c:74)
==13553==    by 0x486E440: _log_write_in_level (log.c:125)
==13553==    by 0x486E18F: log_info (log.c:91)
==13553==    by 0x10EFD0: recibir_mensaje (utils.c:433)
==13553==    by 0x10C2BF: copy_string (instrucciones.c:762)
==13553==    by 0x10AFA3: execute (instrucciones.c:161)
==13553==    by 0x10D819: ejecutar_proceso (cpu.c:236)
==13553==    by 0x10D439: atenderCpuDispatch (cpu.c:109)
==13553==  Address 0x4afd300 is 0 bytes after a block of size 0 alloc'd
==13553==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==13553==    by 0x10EEE1: recibir_buffer (utils.c:413)
==13553==    by 0x10EFA7: recibir_mensaje (utils.c:432)
==13553==    by 0x10C2BF: copy_string (instrucciones.c:762)
==13553==    by 0x10AFA3: execute (instrucciones.c:161)
==13553==    by 0x10D819: ejecutar_proceso (cpu.c:236)
==13553==    by 0x10D439: atenderCpuDispatch (cpu.c:109)
==13553==    by 0x4909AC2: start_thread (pthread_create.c:442)
==13553==    by 0x499AA03: clone (clone.S:100)
==13553== 
==13553== Invalid read of size 1
==13553==    at 0x484ED16: strlen (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==13553==    by 0x48EBD30: __vfprintf_internal (vfprintf-internal.c:1517)
==13553==    by 0x48FD499: __vsnprintf_internal (vsnprintf.c:114)
==13553==    by 0x486F44E: _string_append_with_format_list (string.c:310)
==13553==    by 0x486E83F: string_from_vformat (string.c:74)
==13553==    by 0x486E440: _log_write_in_level (log.c:125)
==13553==    by 0x486E18F: log_info (log.c:91)
==13553==    by 0x10EFD0: recibir_mensaje (utils.c:433)
==13553==    by 0x10C2BF: copy_string (instrucciones.c:762)
==13553==    by 0x10AFA3: execute (instrucciones.c:161)
==13553==    by 0x10D819: ejecutar_proceso (cpu.c:236)
==13553==    by 0x10D439: atenderCpuDispatch (cpu.c:109)
==13553==  Address 0x4afd300 is 0 bytes after a block of size 0 alloc'd
==13553==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==13553==    by 0x10EEE1: recibir_buffer (utils.c:413)
==13553==    by 0x10EFA7: recibir_mensaje (utils.c:432)
==13553==    by 0x10C2BF: copy_string (instrucciones.c:762)
==13553==    by 0x10AFA3: execute (instrucciones.c:161)
==13553==    by 0x10D819: ejecutar_proceso (cpu.c:236)
==13553==    by 0x10D439: atenderCpuDispatch (cpu.c:109)
==13553==    by 0x4909AC2: start_thread (pthread_create.c:442)
==13553==    by 0x499AA03: clone (clone.S:100)
==13553== 
[INFO] 16:20:35:778 CPU/(13553:13554): Me llego el mensaje: 
[INFO] 16:20:35:779 CPU/(13553:13554): Proceso desalojado por motivo: 54
desempaquetar_contexto_ejecucion: proceso 0 

[INFO] 16:20:35:779 CPU/(13553:13554): PID: <0> - FETCH - Program Counter: <15>
DESALOJAR PROC: pid_inter 0 pid 0
INSTRUCCION FETCH 
[INFO] 16:20:54:998 CPU/(13553:13554): Program Counter actualizado: 16
 instruccion_decodificada->identificador DECODE 39
 instruccion_decodificada->identificador EXECUTE 39
[INFO] 16:20:55:000 CPU/(13553:13554): se leyo mal el identificador

==13553== 
==13553== HEAP SUMMARY:
==13553==     in use at exit: 829 bytes in 78 blocks
==13553==   total heap usage: 3,755 allocs, 3,677 frees, 137,645 bytes allocated
==13553== 
==13553== LEAK SUMMARY:
==13553==    definitely lost: 285 bytes in 76 blocks
==13553==    indirectly lost: 0 bytes in 0 blocks
==13553==      possibly lost: 544 bytes in 2 blocks
==13553==    still reachable: 0 bytes in 0 blocks
==13553==         suppressed: 0 bytes in 0 blocks
==13553== Rerun with --leak-check=full to see details of leaked memory
==13553== 
==13553== For lists of detected and suppressed errors, rerun with: -s
==13553== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)

**Comment by iago64** [comment]
Buenas! Cómo va?

Esto tiene pinta de que mas que un problema de memoria, viene por el lado de que tienen que debuguear y ver si reciben bien la data desde la CPU y a partir de ahi ir viendo en el kernel si estan moviendo el pcb de manera correcta.

Saludos.-

**Comment by Sebastian-Faingerch** [comment]
Pudimos solucionarlo, era un problema de semaforos! Gracias por la respuesta, cierro el issue
