### ISSUE TITLE
Problemas modificando la capacidad de la memoria de la VM

### ISSUE THREAD

**Issue by OrianaIsabel** [sisoputnfrba/foro#4229]
Descargue la maquina virtual con las instrucciones del blog y configure la memoria con 8192MB como aparecia en los videos, pero resulta que es demasiada memoria y no puedo habilitar el portapapeles compartido ni realizar otras funciones. Cuando intente modificar la capacidad por medio de configuracion como aparece en los tutoriales me aparecia bloqueada, por lo que quisiera saber como modificar la capacidad de la memoria una vez creada la maquina virtual.

### 📦 Especificaciones de la VM
- Versión de VirtualBox: Oracle VM VirtualBox Administrador
- Memoria RAM asignada:

### 🖥️ Especificaciones del host
- Sistema Operativo y versión: Windows 11 Home
- Memoria RAM: 8,00 GB (7,75 GB usable)
- Procesador: Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz   1.20 GHz

**Comment by f-and** [comment]
Buenas, para poder configurar la memoria RAM y otras configuraciones la máquina virtual tiene que estar apagada, seguro eso te bloquea el slider. También puede ocurrir que la hayas cerrado guardando el estado:
![image](https://github.com/user-attachments/assets/16d19a62-f8a9-4fdd-849d-90d5b4bf22cd)
(La opción que dejé marcada)
Esto lo podes chequear yendo al Manager de VBox y fijandote si te deja descartar el estado guardado: 
![image](https://github.com/user-attachments/assets/9310c545-1c30-4764-adcb-413b1d88b1c0)
De ser así, simplemente borrando el estado guardado te debería poder dejar configurar la VM.
Saludos.

**Comment by OrianaIsabel** [comment]
Hola, gracias por la ayuda, lo hice sin el estado guardado y al final me di cuenta que no puedo cambiar la capacidad ya que la reduccion no esta implementada, me aparece este mensaje
![Captura de pantalla 2024-08-22 173718](https://github.com/user-attachments/assets/765d468e-2f35-4a76-b07f-87f4eff7452b)

**Comment by RaniAgus** [comment]
¡Buenas! La configuración a la que te estás refiriendo es la del disco duro (es decir, el almacenamiento secundario o permanente de la VM). De este no deberíamos preocuparnos ya que los 100GB son en realidad virtuales, no el tamaño real que, como podés ver en esta columna, es de 9GB:

![image](https://github.com/user-attachments/assets/b315b537-5f13-4c5e-b6e2-96d95a3aad42)

La configuración que estamos buscando es la de la Memoria RAM (es decir, el almacenamiento primario o volátil de la VM). Al mismo lo podés encontrar haciendo click en la ruedita de "Configuración":

![image](https://github.com/user-attachments/assets/99cdf85f-4108-4dbf-a9d6-8c5520cf265a)

Y moviéndose a la sección de "Sistema":

![image](https://github.com/user-attachments/assets/97501126-a9ae-4990-b39d-d413df7c494d)

Una pregunta, ¿la guía a la que hacías referencia es la de [conseguir un entorno Linux](https://docs.utnso.com.ar/primeros-pasos/entorno-linux)? Pregunto porque no encontré ninguna guía en los primeros pasos que sugiera subir tanto el tamaño de la RAM.

El valor que elijas siempre se tiene que encontrar dentro de la franja verde:
![image](https://github.com/user-attachments/assets/d83dd51c-10d5-44df-ba74-8fcefca33f2a)

Saludos

**Comment by OrianaIsabel** [comment]
Ahora si pude resolverlo, muchas gracias.
A lo que me referia era a un video que encontre que seguia los pasos de las guia, pero no esta en la pagina de sistemas operativos.

**Comment by RaniAgus** [comment]
¡Buenísimo! Una vez resuelta la duda siéntanse libres de cerrar el issue :)
