### ISSUE TITLE
Problema con el despliegue del tp0

### ISSUE THREAD

**Issue by ValenGriggio18** [sisoputnfrba/foro#4230]
Buenas, basicamente lo que me pasa es que llegué al final del tp0, y cuando en la máquina con interfaz gráfica (xubuntu) me abro dos terminales para simular cliente y servidor, se comunican perfectamente. Sin embargo cuando quiero hacer el despliegue en dos máquinas sin interfaz gráfica (clonando una de las dos) el módulo de cliente no encuentra la ruta del logger ni del config.
![image](https://github.com/user-attachments/assets/90a7999b-afa0-4154-b248-c9893352331e)

Lo que estoy haciendo es abrir las dos máquinas virtuales sin interfaz (ubuntu) con el virtualbox que tengo instalado en mi notebook, y mediante el comando ssh me las traigo para mi pc de escritorio para ver y moverme por la consola de forma más cómoda. Me abro dos "cmd" en la pc de escritorio, me traigo una máquina a cada cmd (ya checkie que tienen distinta ip con el método que mencionan en la etapa 4 del tp0) y ejecuto en cada una un módulo distinto. Al ejectuar el servidor no hay problema, se queda esperando, pero cuando trato de ejecutar el cliente luego de poner la ip de la máquina del server en las config, me tira lo de más arriba.

**Comment by ValenGriggio18** [comment]
![image](https://github.com/user-attachments/assets/1aeb799e-e33e-48f2-a2c8-8042c97693d0)
lo raro es esto, que yo me muevo a cliente en la maquina con interfaz grafica y tiro ls en consola, y me figura el archivito tp0.log
![image](https://github.com/user-attachments/assets/fb866182-306b-46e8-ab2c-c4212cc6d13a)
sin embargo cuando hago exactamente lo mismo en la consola de la maquina sin interfaz grafica, el archivito tp0.log no me figura, y justamente cuando trato de hacerle ./ al ejecutable es el mensaje que me tira, error al crear el logger.

**Comment by ValenGriggio18** [comment]
Acá adjunto como tengo la función iniciar logger, aunque como digo, el tp0 me anda bárbaro si hago la prueba en la xubuntu, el problema es que es como si no existiera el archivito tp0.log en las máquinas ubuntu, porque me tira no such filo or directory.
![image](https://github.com/user-attachments/assets/7b8d5985-f624-4fd1-8358-9ab28016bc9f)
![image](https://github.com/user-attachments/assets/93940ed1-eb70-4047-98a2-87e5a29d51df)
y acá muestro como funciona con la máquina virtual de interfaz gráfica
![image](https://github.com/user-attachments/assets/aef02952-526b-4e7d-b037-62bfcd08f507)

**Comment by RaniAgus** [comment]
¡Buenas! Pregunta: ¿el código que compilaste en la VM Server para iniciar logger es el mismo que está en la gráfica? Podés chequearlo abriendo el archivo con el comando `less`, ej:

```
less src/client.c
```

Saludos

**Comment by ValenGriggio18** [comment]
Buenas, lo acabo de checkear y si, al menos el código que involucra al logger del cliente es el mismo para ambas máquinas. Lo unico que se me ocurre es que sea un problema con la forma en la que setee la ruta del archivo log del cliente, pero ya probé varias rutas, probé dejando el path "tp0.log" o poniendo el path completo "/home/utnso/Desktop/tp0/client/tp0.log" y no hay manera.
#include "client.h"

int main(void)
{
	/*---------------------------------------------------PARTE 2-------------------------------------------------------------*/

	int conexion;
	char* ip;
	char* puerto;
	char* valor;

	t_log* logger;
	t_config* config;

	/* ---------------- LOGGING ---------------- */

	logger = iniciar_logger();

	// Usando el logger creado previamente
	// Escribi: "Hola! Soy un log"

	log_info(logger, "Hola! Soy un log");


	/* ---------------- ARCHIVOS DE CONFIGURACION ---------------- */

	config = iniciar_config();

	// Usando el config creado previamente, leemos los valores del config y los 
	// dejamos en las variables 'ip', 'puerto' y 'valor'

	ip = config_get_string_value(config, "IP");
	puerto = config_get_string_value(config, "PUERTO");
	valor = config_get_string_value(config, "CLAVE");

	// Loggeamos el valor de config

	log_info(logger, valor);


	/* ---------------- LEER DE CONSOLA ---------------- */

	leer_consola(logger);

	/*---------------------------------------------------PARTE 3-------------------------------------------------------------*/

	// ADVERTENCIA: Antes de continuar, tenemos que asegurarnos que el servidor esté corriendo para poder conectarnos a él

	// Creamos una conexión hacia el servidor
	conexion = crear_conexion(ip, puerto);

	// Enviamos al servidor el valor de CLAVE como mensaje
	enviar_mensaje(valor, conexion);

	// Armamos y enviamos el paquete
	paquete(conexion);
	

	terminar_programa(conexion, logger, config);

	/*---------------------------------------------------PARTE 5-------------------------------------------------------------*/
	// Proximamente
}

t_log* iniciar_logger(void)
{
	t_log* nuevo_logger;
	nuevo_logger = log_create("tp0.log", "Logger TP0", true, LOG_LEVEL_INFO);
	if(nuevo_logger == NULL){
		perror("Error al crear el logger");
		exit(EXIT_FAILURE);
	}
	return nuevo_logger;
}

t_config* iniciar_config(void)
{
	t_config* nuevo_config;
	nuevo_config = config_create("cliente.config");
	if(nuevo_config == NULL){
		perror("Error al crear la config");
		exit(EXIT_FAILURE);
	}
	return nuevo_config;
}

void leer_consola(t_log* logger)
{
	char* leido;

	// La primera te la dejo de yapa
	leido = readline("> ");
	log_info(logger, leido);

	// El resto, las vamos leyendo y logueando hasta recibir un string vacío

	while(strcmp(leido, "") != 0){
		free(leido);
		leido = readline(">>");
		log_info(logger, leido);
	}
	// ¡No te olvides de liberar las lineas antes de regresar!
	free(leido);

}

void paquete(int conexion)
{
	// Ahora toca lo divertido!
	char* leido;
	t_paquete* paquete = crear_paquete();

	// Leemos y esta vez agregamos las lineas al paquete
	leido = readline("> ");
	while(strcmp(leido, "") != 0){
		agregar_a_paquete(paquete, leido, strlen(leido)+1);
		free(leido);
		leido = readline("> ");
	}
	// ¡No te olvides de liberar las líneas y el paquete antes de regresar!
	free(leido);

	//ENVIO PAQUETE
	enviar_paquete(paquete, conexion);

	//elimino el paquete

	eliminar_paquete(paquete);

}

void terminar_programa(int conexion, t_log* logger, t_config* config)
{
	/* Y por ultimo, hay que liberar lo que utilizamos (conexion, log y config) 
	  con las funciones de las commons y del TP mencionadas en el enunciado */
	log_destroy (logger);  
	config_destroy(config);
	liberar_conexion(conexion);
}
Ahi te dejo mi archivo "client.c" entero a ver si encontrás algún problema
![image](https://github.com/user-attachments/assets/ec4c2ac0-7984-4e07-b2a4-2e859b180693)
y acá te dejo una imagen para que veas donde tengo ubicado el archivo tp0.log, quizás el problema sea la ubicacion del repo del tp0 en la maquina virtual, no lo sé.
Otra cosa que también pense es en la configuración de las VM server, se te ocurre que puede ser algo relacionado con eso?

**Comment by ValenGriggio18** [comment]
Bueno hice la vieja confiable y elimine las dos VM server, cree otras nuevas y ahi si pude crear la conexión sin problemas, habré pifiado en algo de la instalación de las commons en la VM o algo por el estilo, no le voy a dar mayor importancoa, muchas gracias igual.

**Comment by ValenGriggio18** [comment]
Done.
