### ISSUE TITLE
Problema interpretando el punto 4 del TP0

### ISSUE THREAD

**Issue by OrianaIsabel** [sisoputnfrba/foro#4232]
Del punto 4 del TP0 llegue hasta la configuracion de la conexion por SSH, pero al realizar el despliegue del repositorio no entiendo a que se refiere con no usar interfaz grafica, se refiere a que debo realizar todos los pasos en mi propio sistema y no en la maquina virtual?

### 📔 Citas del enunciado/videos
Despliegue del repositorio
Para desplegar el TP0 en la VM, vamos a repetir los mismos pasos que hicimos en la guía anterior y la etapa 1, pero sin interfaz gráfica. Es decir, vamos a:

Instalar la [so-commons-library](https://faq.utnso.com.ar/commons).
Clonar su propio fork del TP0.
Moverse a la carpeta client y server y compilar el código fuente ejecutando el comando make.

**Comment by iago64** [comment]
Buenas! Cómo va?

A lo que se refiere es que tienen que usarla línea de comandos para compilar y ejecutar el TP0, ya que de esa forma lo van a hacer el día de la entrega.

Saludos.-

**Comment by OrianaIsabel** [comment]
Hola, ya ahora si pude hacerlo muchas gracias.
