### ISSUE TITLE
Dudas de enunciado en Memoria y Filesystem

### ISSUE THREAD

**Issue by KevinQ73** [sisoputnfrba/foro#4233]
Buenas noches, tengo dos consultas sobre el enunciado del TP.

1) En la parte del archivo config de memoria, no debería haber un `PUERTO_FS` y `IP_FS` para poder conectarme con el módulo FILESYSTEM a la hora de realizar un memory dump? Ya que en el config del Filesystem declaramos un `PUERTO_ESCUCHA` que nunca mencionamos en el config de Memoria.

**_Config propuesto en el enunciado de MEMORIA:_**
>PUERTO_ESCUCHA=8002
TAM_MEMORIA=1024
PATH_INSTRUCCIONES=/home/utnso/scripts-pruebas
RETARDO_RESPUESTA=1000
ESQUEMA=FIJAS
ALGORITMO_BUSQUEDA=FIRST
PARTICIONES=[512, 16, 32, 16, 256, 64, 128]
LOG_LEVEL=TRACE

**_Config propuesto en el enunciado de FILESYSTEM:_**
>PUERTO_ESCUCHA=8003
MOUNT_DIR=/home/utnso/mount_dir
BLOCK_SIZE=64
BLOCK_COUNT=1024
RETARDO_ACCESO_BLOQUE=15000
LOG_LEVEL=TRACE

2) Es correcto este esquema de carpetas para lo que proponen?
```
.
├── kernel
├── cpu
├── memoria
├── filesystem
├── utils
└── mount_dir
    ├── files
    │   └── 1-0-12:51:59:331.dmp
    ├── bloques.dat
    └── bitmap.dat

```

No me queda muy claro donde va a estar el archivo que Memoria le pide crear a Filesystem, por lo que entendí, cuando memoria solicite crear un archivo para el dump, también se creara un archivo metadata con el mismo nombre en la carpeta `/files`

Enunciado Memoria:
>Al momento de recibir la operación de memory dump el módulo memoria deberá solicitar al módulo FileSystem la creación de un nuevo archivo con el tamaño total de la memoria reservada por el proceso y debe escribir en dicho archivo todo el contenido actual de la memoria del proceso. El archivo debe llamarse “<PID>-<TID>-<TIMESTAMP>.dmp”.
En caso de que el FileSystem responda con error, se devolverá el mismo mensaje al Kernel, en caso positivo, se responde como OK.

**_Enunciado Filesystem:_**
>Archivos de metadata: Estos archivos se encontrarán dentro de la carpeta /files, a partir del punto de montaje (MOUNT_DIR) y se tendrá 1 archivo por cada archivo que se cree en el FS, donde su nombre va a ser el nombre del archivo en el FS, por ej, 1-0-12:51:59:331.dmp. El contenido de estos archivos consistirá de el tamaño en bytes del archivo (SIZE) y el número de bloque que corresponde al bloque de índices (INDEX_BLOCK), un ejemplo del contenido puede ser el siguiente:
SIZE=4
INDEX_BLOCK=10

**Comment by iago64** [comment]
Buenas! Cómo va?

Respecto a la IP y puerto, ya estan agregadas.

Respecto al esquema del FS esta bien como lo planteas, con la única observación de que el mount_dir puede estar en cualquier lado ya que es una propiedad que va en la config del FS.

Saludos.-

**Comment by KevinQ73** [comment]
Dale, muchas gracias!. Cierro issue
