### ISSUE TITLE
Duda de si falta `IP_FILESYSTEM` en el doc

### ISSUE THREAD

**Issue by haytham2597** [sisoputnfrba/foro#4234]
### Duda
El módulo de `Memoria` no se encuentra la configuración del ip de `filesystem` sabiendo que en el diagrama  de `Arquitectura del sistema` la memoria se conecta al FileSystem en teoría.
Mi duda es: ¿Faltará el IP de Filesystem en el [archivo de configuración](https://docs.google.com/document/d/1KloOXfXQb_c1S3PKDEEywnArX9YB3aApqGVmpNgv9_Q/edit#heading=h.6jy02lt9hlna) en el Doc? incluyendo `PUERTO_FILESYSTEM`?

### 💭 Soluciones posibles

Crear cualquier IP y/o Puerto que difiera del resto de los módulos

**Comment by iago64** [comment]
Buenas! Cómo va?

Pueden agregar las propiedades que necesiten, igual ya se encuentra arreglado en el doc.

Saludos.-
