### ISSUE TITLE
"Consola interactiva" en enunciado

### ISSUE THREAD

**Issue by fernandodanielmaqueda** [sisoputnfrba/foro#4235]
¡Buenas!

Leyendo a nivel general el enunciado del TP me llamó la atención que en el apartado del Módulo Kernel se hace mención de una *"consola interactiva"* (dejo cita abajo), cuando no veo que en ningún otro lado vuelva a figurar nada por el estilo ni se den más detalles acerca de su implementación. ¿A qué se refiere con eso entonces?

### 📔 Citas del enunciado/videos
> El módulo Kernel, en el contexto de nuestro trabajo práctico, será el encargado de gestionar la ejecución de los diferentes procesos  que se generen por medio de su `consola interactiva`.

*(Página 9)*

### 💭 Soluciones posibles
Error de interpretación, error ó ambigüedad en el enunciado

**Comment by iago64** [comment]
Buenas! Cómo va?

Efectivamente, error de redacción, originalmente teníamos la idea de como en el TP pasado tener una consola, pero la descartamos y nos olvidamos de esa línea, este TP no tiene ninguna consola interactiva.

Saludos.-

**Comment by fernandodanielmaqueda** [comment]
¡Gracias por la aclaración!
Saludos.
