### ISSUE TITLE
Consulta sobre envío de CPU a Memoria

### ISSUE THREAD

**Issue by Bru-Nicolas-FRBA** [sisoputnfrba/foro#4236]
Buenas. Como estan? Mi nombre es Nico y formo parte del grupo Golazo. Queriamos hacer una consulta sobre el enunciado:

La pagina 15 de este dice que le debemos enviar a la CPU el PC para poder comenzar la etapa fetch del ciclo de instruccion:
>Fetch
La primera etapa del ciclo consiste en buscar la próxima instrucción a ejecutar. En este trabajo práctico cada instrucción deberá ser pedida al módulo Memoria utilizando el Program Counter (también llamado Instruction Pointer) que representa el número de instrucción a buscar relativo al proceso en ejecución. Al finalizar el ciclo, este último deberá ser actualizado (sumarle 1) si corresponde.

Pero luego en la pagina 20 nos dice que debemos devolverle la instrucción correspondiente al hilo Y al PC recibido:
>Obtener instrucción
Deberemos devolverle la instrucción correspondiente al hilo y al Program Counter recibido. Por ejemplo, si el hilo 3 del proceso 1 pide la instrucción número 4, deberemos devolver la 5ta instrucción del pseudocódigo correspondiente a ese hilo.

Teníamos la duda de si solo enviamos el PC o algún tipo de dato para referenciar el hilo (el TID por ejemplo)

**Comment by RaniAgus** [comment]
¡Buenas! Son dos solicitudes CPU->Memoria, cito fragmentos del enunciado:

1) Obtener contexto de ejecución

- CPU: Al momento de recibir un **TID** y **PID** de parte del Kernel la CPU deberá solicitarle el contexto de ejecución correspondiente a la Memoria para poder iniciar su ejecución.
- Memoria: Deberemos devolverle el contexto de ejecución completo para el **PID-TID** pedido: AX, BX, CD, DX, EX, FX, GX, HX, PC, base y límite.

2) Obtener instrucción

- CPU: La primera etapa del ciclo consiste en buscar la próxima instrucción a ejecutar. En este trabajo práctico cada instrucción deberá ser pedida al módulo Memoria utilizando el **Program Counter** (también llamado Instruction Pointer) que representa el número de instrucción a buscar relativo al proceso en ejecución.
- Memoria: Deberemos devolverle la instrucción correspondiente al **hilo** y al **Program Counter** recibido. Por ejemplo, si el hilo 3 del proceso 1 pide la instrucción número 4, deberemos devolver la 5ta instrucción del pseudocódigo correspondiente a ese hilo.

Entonces, el PC que le envían a Memoria en el paso 2) es el recibido en el paso 1).

Saludos
