### ISSUE TITLE
conexion memoria a filesystem (y duda con conexiones multihilo)

### ISSUE THREAD

**Issue by GianLema** [sisoputnfrba/foro#4237]
Buenas. Tenemos una duda con respecto a como memoria deberia conectarse a filesystem si no tiene el ip de filesystem en su config.
Una duda aparte es si tanto memoria para atender a kernel como fs para atender a memoria debe implementar un modelo de multiplexacion? osea con muchos puertos de escucha?

config memoria:
`PUERTO_ESCUCHA=8002`
`TAM_MEMORIA=1024`
`PATH_INSTRUCCIONES=/home/utnso/scripts-pruebas`
`RETARDO_RESPUESTA=1000`
`ESQUEMA=FIJAS`
`ALGORITMO_BUSQUEDA=FIRST`
`PARTICIONES=[512, 16, 32, 16, 256, 64, 128]`
`LOG_LEVEL=TRACE`

>levantará un servidor multihilo para esperar las peticiones por parte del módulo Kernel. Estas peticiones se deberán atender de manera concurrente teniendo 1 hilo por cada petición, el cual deberá finalizar luego de notificar el resultado de la misma al módulo kernel y de cerrar la conexión.

>Al iniciarse el módulo se iniciará un servidor multihilo que quedará a la espera de las peticiones del módulo Memoria, las cuales las deberá atender de manera concurrente teniendo 1 hilo para cada petición recibida el cual deberá finalizar al momento de concluida la petición, luego de notificar el resultado de la operación a la memoria y de cerrar la conexión.

**Comment by RaniAgus** [comment]
¡Buenas!

> Tenemos una duda con respecto a como memoria deberia conectarse a filesystem si no tiene el ip de filesystem en su config.

¿Están leyendo la última versión del doc? Ya fue actualizado en #4234

> Una duda aparte es si tanto memoria para atender a kernel como fs para atender a memoria debe implementar un modelo de multiplexacion? osea con muchos puertos de escucha?

Multiplexación no implica tener varios puertos de escucha, ya que por cada `accept()` lo que se devuelve es **un nuevo** socket conectado a través de un puerto disponible. Es recomiendo repasar la [guía de sockets](https://docs.utnso.com.ar/guias/linux/sockets), puntualmente la sección de `accept()` y `connect()`.

En cuanto a la implementación de los módulos, las solicitudes Kernel->Memoria y las Memoria->FileSystem son efímeras, es decir:

- El módulo A que hace la solicitud primero se **conecta**
- El módulo B que recibe la solicitud **acepta** la conexión
- A **envía** la solicitud
- B **recibe** la solicitud, la procesa y **envía** la respuesta
- A **recibe** la respuesta
- Ambos A y B **cierran** la conexión.

Saludos

**Comment by GianLema** [comment]
Ah muchas gracias por aclarar lo de la ip, como no lo vi en el historial de cambios asumi que seguia igual.

Con respecto a lo segundo, ya habiendo leido la guia y la parte de multiplexando ando tambien creo que quedo todo claro por ahora.

muchas graciass
