### ISSUE TITLE
Consulta carpeta FS

### ISSUE THREAD

**Issue by Bru-Nicolas-FRBA** [sisoputnfrba/foro#4238]
Buenos días, en el enunciado de FS en la pagina 24 se habla en el **bitmap.dat** de una carpeta MNT_DIR

>bitmap.dat:
Este archivo representará el bitmap del FS y contendrá 1 bit por cada bloque del archivo donde si el valor del bit es 0 indicará que el bloque se encuentra vacío y si su valor es 1 indica que el bloque se encuentra ocupado, por lo tanto, el tamaño de este archivo deberá ser BLOCK_COUNT / 8 (redondeado al valor superior). Este archivo se encontrará directamente en la carpeta **MNT_DIR**

Luego en el **bloques.dat** y **archivos metadata** se menciona la carpeta MOUNT_DIR

>bloques.dat: Este archivo será el archivo que contendrá tanto los bloques de datos como los bloques de índices de los diferentes archivos creados en el FS y su tamaño será BLOCK_COUNT * BLOCK_SIZE. Este archivo se encontrará directamente en la carpeta **MOUNT_DIR**

>Archivos de metadata: Estos archivos se encontrarán dentro de la carpeta /files, a partir del punto de montaje (**MOUNT_DIR**) y se tendrá 1 archivo por cada archivo que se cree en el FS, donde su nombre va a ser el nombre del archivo en el FS, por ej, 1-0-12:51:59:331.dmp. El contenido de estos archivos consistirá de el tamaño en bytes del archivo (SIZE) y el número de bloque que corresponde al bloque de índices (INDEX_BLOCK), un ejemplo del contenido puede ser el siguiente:

La carpeta mencionada en el **bitmap.dat** es MNT_DIR (una carpeta aparte) o esto es solo un error de tipeo y sigue siendo la misma MOUNT_DIR mencionada en el **bloques.dat** y **archivos metadata**

**Comment by f-and** [comment]
Buenas Nicolas!
Si, es un error de tipeo que habrá quedado, fijate que en archivo de configuración no se menciona este MNT_DIR, ustedes usen el MOUNT_DIR para todos los archivos.
Saludos.

**Comment by Bru-Nicolas-FRBA** [comment]
Muchas gracias
