### ISSUE TITLE
Problemas al Clonar el repositorio del TP0

### ISSUE THREAD

**Issue by Zamtyagho3** [sisoputnfrba/foro#4239]
Buenas noches, seguí las instrucciones como decía "utnso tp0" y creo que lo hice todo bien, pero al momento de clonar el repositorio de la forma que dicen las instrucciones me da este mensaje como resultado, de antemano gracias por su tiempo. 
![WhatsApp Image 2024-08-27 at 23 51 26_6b2a3024](https://github.com/user-attachments/assets/373ea838-648c-4dd4-af75-cd8c4191a341)

**Comment by RaniAgus** [comment]
¡Buenas! Disculpas, había un error en la guía, el comando a ingresar es:
```
git clone git@github.com:Zamtyagho3/tp0.git
```
(En lugar de `git@github` debería ir `git@github.com`, ya fue corregido)


Saludos

**Comment by Zamtyagho3** [comment]
Muchas gracias por tu pronta respuesta, buen descanso!

**Comment by RaniAgus** [comment]
¡Buenísimo! Recuerden que si la duda ya fue resuelta pueden cerrar el issue 👮🏻‍♂️
