### ISSUE TITLE
Problema con la ssh

### ISSUE THREAD

**Issue by jplopezsanchez** [sisoputnfrba/foro#4241]
![Captura de pantalla 2024-08-28 211850](https://github.com/user-attachments/assets/be68e705-569c-440b-9850-75b98e17c0af)

**Comment by jplopezsanchez** [comment]
Mi problema surge en la parte que se ve en la imagen, cuando voy a poner la key me dice permiso denegado, ya me fije y es exactamente la misma tanto en github como en la Vm y por las dudas las volví a escribir

**Comment by iago64** [comment]
Buenas! Cómo va?

Primero te recomiendo que leas las normas de uso del foro, ya que el texto que aparece en las imagenes el buscados no lo puede indexar y por lo tanto nadie puede buscar por el mismo error que estas teniendo.

En segundo lugar, te consulto, agregaste la key ssh privada al ssh-agent? Por las dudas te dejo la [página de github](https://docs.github.com/es/authentication/troubleshooting-ssh/error-permission-denied-publickey) con toda la info acerca del error que estas teniendo.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @jplopezsanchez ! ¿Te sirvió la respuesta de Dami? Saludos

**Comment by RaniAgus** [comment]
¡Buenas! Cierro el issue por inactividad, si les quedó alguna duda pueden abrir uno nuevo referenciando éste. Saludos
