### ISSUE TITLE
duda sobre el manejo de RR

### ISSUE THREAD

**Issue by nicolasvultaggio** [sisoputnfrba/foro#4242]
Hola! yo soy recusante del cuatrimestre pasado, y me surgió una duda con respecto al manejo del quantum, ya que es un problema que nos ocurrió el cuatrimestre pasado y que, antes de implementar el manejo de quantum en este cuatri, quería solucionar esta duda.
Bien sabemos que hay dos sockets entre kernel y cpu, mediante dispatch se envían los datos sobre el proceso a ejecutar en ese ciclo, y mediante interrupt, el cpu estará esperando la interrupción de parte del kernel para desalojar el proceso. 
Mi duda es más que nada con esta ultima parte, y con respecto a COMO es que el Kernel controla el quantum.
Lo que hicimos el cuatri pasado es que, el kernel envie los datos del proceso por dispatch, y además de quedarse esperando la respuesta del cpu con la "devolución", espere una cierta cantidad de tiempo con USLEEP, esta cantidad de tiempo viene definida justamente por el quantum, y luego de pasado este tiempo, el kernel, debía de alguna forma enterarse si el proceso fue desalojado o no por la cpu, y en el caso queNO haya sido desalojado todavía por alguna syscall, envíe la interrupción por el socket INTERRUPT.
Esta es la unica forma en la que yo personalmente veo posible hacer una implementación en la que tenga sentido mandar la interrupcion por el socket de interrupt,  sin embargo, es muy relativo ya que, depende de la velocidad la computadora del modulo cpu el numero de instrucciones que pueda realizar, y por lo tanto en algunas ejecuciones podrán haber desalojos de quantum y otras no, o sea, un quantum podría NO equivaler a UNA instruccion realizada como en los ejercicios practicos, podrían ser más.
Esto es un claro problema de sincronizacion que se resuelve con semaforos, sin embargo, estamos hablando de dos modulos distintos, quizas la forma en la que podrían coordinarse es si por cada ciclo de instruccion del cpu, este modulo le avise al kernel si hubo desalojo o no para que este aumente el quantum en 1, de esta forma asegurandonos de que SIEMPRE un quantum equivalga a una instruccion ejecutada. Pero de esta forma veo un poco inutil utilizar el socket interrupt.

En resumen, mi pregunta es, QUÉ es lo que se pretende que hagamos con el manejo de quantum? una implemencion usando usleep (en la que el quantum de las pruebas venga dado en milisegundos quizas), o tenemos que lograr que SÍ O SÍ, una instruccion realizada en la cpu equivalga a un quantum sincronizando los modulos kernel y cpu?

**Comment by LeandroCarbajales** [comment]
Buenas!
El quantum es una interrupción asincrónica (externa), y como tal, no se condice su llegada con una cantidad de instrucciones que ejecute la CPU. De hecho, cada instrucción puede tardar más o menos tiempo en ejecutar según cuántos pedidos a memoria tenga que hacer por ejemplo.

En algunos ejercicios prácticos se adjudica una cantidad de tiempo tal que coincidan el quantum con las instrucciones, pero es solamente a modo de simplificación para facilitar su lectura y resolución.

En resumen, la implementación que planteás es completamente válida, el quantum de hecho viene definido en milisegundos dentro de la configuración del módulo Kernel, y el mismo es completamente independiente del tiempo que se tarda en ejecutar cada instrucción en el módulo CPU.

Te aclara las dudas?
Saludos!
     Lean

**Comment by nicolasvultaggio** [comment]
okey, perfecto! me quedó claro, muchas gracias y buen fin de semana!
