### ISSUE TITLE
Archivo de config del Kernel: no tiene puerto de esucha propio

### ISSUE THREAD

**Issue by GabrielBorre** [sisoputnfrba/foro#4243]
Buenas! Cómo están?

Sobre el TP en GO:

 Tenemos una duda sobre el archivo de configuración de los diferentes módulos. Observamos que en el archivo de configuración del kernel no figura el puerto en el cual este módulo atenderá las peticiones de los diferentes módulos. 

Esto nos resulta raro, dado que por ejemplo, en CPU sí figura, el puerto en el cual este módulo esuchará las conexiones. 

Intuimos que el puerto de escucha del kernel tendrá el número del "port_kernel" que figura en el CPU. 

¿Es correcto lo que pensamos? ¿En el archivo de config del kernel debemos incluir el puerto de escucha en donde este atenderá las conexiones?

Desde ya, mil gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

Si, se nos pasó, pueden agregar el puerto como en los demás módulos.

Saludos.-

**Comment by GabrielBorre** [comment]
10/10 Dami, muchas gracias! Cierro el issue. Saludos!
