### ISSUE TITLE
Consulta colas multinivel

### ISSUE THREAD

**Issue by MartinSintas** [sisoputnfrba/foro#4245]
Buenas!! Tengo una duda acerca del enunciado sobre la planificación de colas multinivel en go:

Qué pasaría si en un RR, en caso de que esté ejecutando un hilo (de prioridad 2) y llegué un hilo de mayor prioridad (prioridad 1 por ejemplo) y lo desaloje. Que pasaría con el de prioridad 2 que fue desalojado?

Se iría al final de su cola o quedaría en el principio?

### 📔 Citas del enunciado/videos
![Screenshot_20240831_114718_Docs](https://github.com/user-attachments/assets/832ba9b6-76ec-4340-ac22-69311b3ab0f2)

**Comment by RaniAgus** [comment]
¡Buenas! Es una muy buena pregunta, ahí actualizamos el enunciado agregando una aclaración en el último ítem:

![image](https://github.com/user-attachments/assets/c46f946d-74a8-4803-875a-76b65c629bfc)

Saludos

**Comment by MartinSintas** [comment]
Genial, muchas gracias :D
