### ISSUE TITLE
Duda sobre obtener instrucción

### ISSUE THREAD

**Issue by Tomas-Perez** [sisoputnfrba/foro#4246]
Buenas! Tenia una duda de porque, en el siguiente ejemplo se devolvería la 5ta instrucción. Tampoco termino de entender si cada hilo tiene su propio archivo de pseudocódigo o si utilizan el de su proceso asociado (creo que es esta ultima opción).

### 📔 Citas del enunciado/videos
>Obtener instrucción
Deberemos devolverle la instrucción correspondiente al hilo y al Program Counter recibido. Por ejemplo, si el hilo 3 del proceso 1 pide la instrucción número 4, deberemos devolver la 5ta instrucción del pseudocódigo correspondiente a ese hilo.

**Comment by RaniAgus** [comment]
¡Buenas!
> Tenia una duda de porque, en el siguiente ejemplo se devolvería la 5ta instrucción

Esto se debe a que las instrucciones arrancan en 0. De la misma forma que la 5ta posición de un array es el índice 4, la 5ta instrucción se encuentra en la posición 4.

> Tampoco termino de entender si cada hilo tiene su propio archivo de pseudocódigo o si utilizan el de su proceso asociado (creo que es esta ultima opción).

Se encuentra aclarado en la sección "Execute" de CPU:
- **THREAD_CREATE** (Archivo de instrucciones, Prioridad)

Saludos
