### ISSUE TITLE
Listen para servidor con varias peticiones

### ISSUE THREAD

**Issue by inaaranza** [sisoputnfrba/foro#4249]
Buenas! Queria hacer una pregunta sobre conexiones. En el caso del modulo servidor que recibe peticiones de distintos clientes, ¿está bien que el socket de escucha sea el mismo para esperar las conexiones de todos los clientes?
Muchas gracias!

**Comment by RaniAgus** [comment]
¡Buenas! Sí, está bien, de hecho en la última sección de la [guía de sockets](https://docs.utnso.com.ar/guias/linux/sockets#multiplexando-ando) aparece un ejemplo al respecto. Recordá que por cada `accept()` se devuelve un nuevo socket que no está en modo escucha, sino en modo conectado.

- Socket de escucha -> Solo permite `accept()`ar conexiones
- Socket conectado -> Permite enviar (`send()`) y recibir (`recv()`) mensajes

Saludos

**Comment by inaaranza** [comment]
Bárbaro muchas gracias!! Cierro issue
