### ISSUE TITLE
Duda con FUSE

### ISSUE THREAD

**Issue by juanoubi6** [sisoputnfrba/foro#425]
Buenas, queria plantear una duda que tengo con el funcionamiento del proceso que va a correr con el FUSE y de FUSE en general: vos a ese proceso, al correrlo, le vas a tener que pasar un path que va a terminar siendo el punto de montaje. Cualquier peticion que vos hagas sobre un archivo que se encuentre en ese punto de montaje (y que esa peticion este definida en la estructura fuse_operations, como por ejemplo un read) va a ser manejada por el proceso corriendo fuse, y va a ejecutar la funcion que tengas asignada a esa peticion. 

Ejemplo de como creo que funciona:  voy a asociar en el proceso que corre fuse el punto de montaje /home/prueba que contiene el archivo test.txt. En fuse_operation asigno  .read = MiLectura , y lo que hace la funcion MiLectura es un printf de "hola". Entonces, cuando cualquier proceso quiere leer el archivo test.txt, el proceso con fuse maneja esa peticion de lectura (porque el archivo esta en el punto de montaje que defini)  y muestra por pantalla "hola".

Esto es asi o nada que ver?. Ademas, queria preguntar como puedo "testear" el ejemplo que nos pasaron. Llegue hasta correr el ejemplo y pasarle el punto de montaje (una carpeta vacia) y me creo dentro de esa carpeta el archivo "hello". Ahora queria leer ese archivo y que me diga la el tamaño (que es lo que supuestamente hace) pero no estoy pudiendo.

**Comment by mgarciaisaia** [comment]
@chrisgel15 ¿cuál decís?

**Comment by chrisgel15** [comment]
@mgarciaisaia Todo este thread! Muy útil y claro por todo lo que se discutió y tus explicaciones!!
