### ISSUE TITLE
Problema con Instalas los Guest Additions

### ISSUE THREAD

**Issue by MaximoPisciottano** [sisoputnfrba/foro#4250]
Estaba instalando los guest Additiond en la maquina virtual y al seguir los pasos no pasa nada al "insetar la imagen del CD del complemento de los invitados" en Dispositivos, y no se que hacer

### 🔎 Búsqueda en foros

Busque por los Issues pero ninguno tiene el error que tengo yo o eso entendí, la verdad no ando muy familiarizado con todo esto y bueno no se

**Comment by RaniAgus** [comment]
¡Buenas! ¿No te aparece el icono del dispositivo a la izquierda del escritorio para abrir la carpeta?

![image](https://github.com/user-attachments/assets/bbcc6034-518f-48f7-ad45-a5e888be17a7)

Saludos

**Comment by MaximoPisciottano** [comment]
Si, ahi me fije lo abri y ahi esta todo, ya pude instalar todo tranquilo, gracias igualmente

**Comment by RaniAgus** [comment]
¡Buenísimo! Recuerden que si la duda ya fue resuelta pueden cerrar el issue 👮🏻‍♂️
