### ISSUE TITLE
Duda sobre la bidireccionalidad de las conexiones de los módulos en Go

### ISSUE THREAD

**Issue by GabrielBorre** [sisoputnfrba/foro#4251]
### 🖋️ Descripción

Buenas! Como estan?

Tenemos una duda con respecto a la bidireccionalidad de las conexiones entre los módulos en Go

Nosotros tenemos una rutina en cada módulo que ejecutará una función que contendrá la lógica de un servidor, es decir, tendrá el objetivo de gestionar los diferentes mensajes que le lleguen. (adjunto código de la función ServerStart)

Esta función es gestionada por diversas funciones. Una de ellas será la encargada de recibir un mensaje, mostrarlo por pantalla y devolver un OK, si es que la conexión fue realizada con éxito.

Si el cliente se conectó correctamente, devolverá por pantalla un "200 OK" que entiendo que representa el mensaje enviado desde el servidor al que se conectó.

Las preguntas que yo me hago son : ¿Una vez que hicimos esto, ya tenemos garantizada la bidireccionalidad entre los módulos? ¿El "200 OK" que devuelve el cliente cuando se conecta correctamente con el servidor es garantía de que podrá funcionar como cliente y servidor ?

Adjunto imágenes de la función que ejecuta la rutina (ServerStart), la función que se encarga de hacer el "handle func " (Recibir Mensaje) y, por último, lo que se imprime en la pantalla del kernel cuando se intenta conectar con la CPU

Desde ya, muchas gracias!!

```Go
func ServerStart(port int) {

	mux := http.NewServeMux()

	// General del TP0
	mux.HandleFunc("/paquetes", server.RecibirPaquetes)
	mux.HandleFunc("/mensaje", server.RecibirMensaje)
	// Después agregaremos a piacere según que necesite escuchar el kernel
	fmt.Printf("Servidor escuchando en puerto: %d\n", port)

	err := http.ListenAndServe(":"+fmt.Sprintf("%v", port), mux)
	if err != nil {
		panic(err)
	}
}
```

```GO

func RecibirMensaje(w http.ResponseWriter, r *http.Request) {
	decoder := json.NewDecoder(r.Body)
	var mensaje Mensaje
	err := decoder.Decode(&mensaje)
	if err != nil {
		fmt.Printf("Error al decodificar mensaje: %s\n", err.Error())
		w.WriteHeader(http.StatusBadRequest)
		w.Write([]byte("Error al decodificar mensaje"))
		return
	}

	fmt.Println("Me llego un mensaje de un cliente")
	fmt.Printf("%+v\n", mensaje)

	w.WriteHeader(http.StatusOK)
	w.Write([]byte("ok"))
}
```

###  LOGS  
utnso@utnso:~/tp-2024-2c-GOlazo/kernel$ ./kernel
Archivo de config de KERNEL cargado
Servidor escuchando en puerto: 8001
respuesta del servidor: 200 OK^C
###

**Comment by nahuemazzeo** [comment]
Hola @GabrielBorre! Como andas?

Ehhm, creo que el problema que estamos teniendo es que estamos intentando hacer lo que se hace en C en Go y esto no esta tan bien. El objetivo del trabajo practico en Go es evolucionar nuestra forma de trabajar y "modernizar" nuestra solución de nuestro trabajo practico.

Dicho esto, empecemos a olvidarnos un poco "mensajes" y "paquetes" y empecemos a hablar de API's. Vamos a llamar a una API a cualquier tipo de mensaje que se requiera enviar desde el modulo A al modulo B. Toda API tiene unos parametros de entrada, ya sea porq query params o body, y puede tener parametros de salida, en el body (esto esta explicado en la seccion de [Protocolo HTTP](https://golang.utnso.com.ar/guias/programacion/http-protocol) de la guia de golang). Toda respuesta de una API tiene un codigo de retorno que normalmente indica que los numeros 2xx son OK, y 4xx o 5xx son de errores.

Ahora, yendo a nuestro TP, ¿que seria un ejemplo de una api?

1. Modulo Kernel solicita a Modulo Memoria que inicialice un proceso. Ejemplo: En memoria PUT /proceso
2. Modulo Kernel solicita a Modulo Memoria que finalice un proceso. Ejemplo: En memoria DELETE /proceso
3. Modulo Kernel solicita a Modulo CPU que ejecute un proceso. Ejemplo: En cpu PUT /proceso
4. Modulo Kernel solicita a Modulo CPU que desaloje un proceso. Ejemplo: En cpu DELETE /proceso
5. Modulo CPU indica a Modulo Kernel que "termino" de ejecutar un proceso.  Ejemplo En kernel POST /proceso

Entonces. Que vemos aca...

- No va a haber una "conexion" bidireccional permanentemente entre los modulos, cada modulo se conectará y ejecutará una api del otro modulo cuando lo requiera
- Cada "API" es un endpoint distinto que define el modulo destino (el que recibe el mensaje) y dependiendo el objetivo de la accion a realizar se realizara de manera sincrona o no. Osea, cuando tengamos pedidos que requieren realizar una ejecución prolongada entre la invocación y la finalizacion, vamos a tener dos metodos mientras que cuando necesitamos obtener un resultado en el momento para continuar la ejecución lo haremos en el momento. Por ejemplo, el modulo Kernel no deberia "esperar" a que CPU termine de ejecutar un proceso sino que cuando CPU realmente termine se lo notificara al Kernel por otra API. En contra partida cuando necesitamos "iniciar o finalizar un proceso en memoria", ahi se mantiene un sincronismo para poder obtener el resultado en el momento. Como definimos cuando hacer esto y cuando no, es decision de ustedes, dependiendo el camino que tomen es la facilidad que van a tener para resolver los distintos problemas.
- Ya no existe el concepto de "mensaje" y "paquete". Cada API tendra su propio "contrato" definido por un json (como se explica en la guia antes mencionada) y solo va a contener lo que realmente le corresponde. Ya no existe el "parsear" el mensaje para interpretar que tengo que hacer

En resumen, el ejemplo que me mostraste es correcto para verificar que un Modulo A puede llegar a un Modulo B ejecutando una API. El concepto de bidireccionalidad no va a existir porq cada vez que un Modulo A requiera algo del Modulo B deberia ejecutar una API definida por el Modulo B para su obtencion.

Espero poder haber solucionado o ejemplificado lo suficiente este tema. Cualquier duda no dudes en realizarla.

Saludos.

**Comment by GabrielBorre** [comment]
Hola Nahue! Cómo estás?

Muchísimas gracias por tomarte el tiempo de responder tan detallada y claramente! Se entendió perfecto. De verdad, gracias.

La única duda que me queda flotando es la siguiente: por el momento, nosotros implementamos la lógica de que un módulo consume la API de otro y este otro le responde con un 200 OK que, según lo que comprendí de lo que explicaste, significa que la solicitud se realizó exitosamente. Ahora bien, si esta lógica la replicamos en cada uno de los módulos, ¿bastaría para decir que cubrimos correctamente los requerimientos del Chekpoint 1? Por ejemplo, si el kernel consume una API expuesta por el CPU y este módulo le responde con un 200OK, pero no ocurre lo mismo al revés, ¿podríamos decir que estamos cumpliendo con el checkpoint?  Me suena a que no, porque ambos tienen que consumir una API expuesta por el otro, según lo que entiendo. 

De todas maneras, te consulto para despejar esa duda particular, en pos de cumplir integralmente con los objetivos del checkpoint.

Nuevamente, muchísimas gracias por tu respuesta anterior @nahuemazzeo !! Saludos

**Comment by nahuemazzeo** [comment]
Hola @GabrielBorre!

El objetivo del checkpoint es que todos esten exponiendo una api y que todos al levantarse se queden esperando que alguien los invoque

Saludos.

**Comment by GabrielBorre** [comment]
Genial @nahuemazzeo !! Muchisimas gracias por todas tus respuestas. Nos van a ser de mucha utilidad para pensar la manera en que tenemos que hacer las conexiones.
Cierro el issue. Saludos y gracias!
