### ISSUE TITLE
error en la inclusion de variables globales al modularizar mi kernel

### ISSUE THREAD

**Issue by nicolasvultaggio** [sisoputnfrba/foro#4252]
### 🖋️ Descripción

tal como dice el titulo, estaba intentando modularizar mi kernel, y para eso, tal como dice la guía https://docs.utnso.com.ar/guias/programacion/buenas-practicas
cree un globals.h y un globals.c para declarar y definir mis variables globales, respectivamente.
sin embargo, en algunos archivos, como en mi main.c, me reconoce las variables globales, y en otras no.

### 📚 Búsqueda en documentación/foros

lo unico que usé para esto es el apartado de buenas practicas de c

### 📄 Código relevante

se que ahora se vienen muchas partes de codigo, pero la idea es centrarse en los includes de cada modulo, no leer la logica de cada unos, solo hace falta saber que main y handle_connection incluyen variables globales en su codigo

les muestro mi codigo de mi globals.h y globals.c respectivamente

```
#ifndef GLOBALS_H_
#define GLOBALS_H_

#include <commons/log.h>
#include <commons/string.h>
#include <semaphore.h>
#include <stdio.h>
#include <stdlib.h>
#include <commons/config.h>
#include <pthread.h>
// CREO QUE CADA .H debe incluir este.h para conocer todos los tipos de datos y todas las variables globales

// o al menos, los tipos de datos que se usan en varios archivos, si o si 

typedef struct
{
    t_config *config;
    char *memory_ip;
    char *memory_port;
    char *cpu_ip;
    char *cpu_dispatch_port;
    char *cpu_interrupt_port;
    char *planning_algorithm;
    int quantum;
    char *log_level;
} t_kernel_config;

extern t_log *logger;

extern t_kernel_config *kernel_config;

extern int cpu_dispatch_connection; 
extern int cpu_interrupt_connection;
extern int memory_connection;

extern pthread_t thread_short_term;
extern pthread_t thread_long_term;
extern pthread_t thread_cpu_dispatch;
extern pthread_t planner_thread;

extern sem_t *sem_multiprogrammming_degree;
extern sem_t *sem_short_term_planner, *sem_long_term_planner;
extern sem_t *mutex_stopping_planner;


#endif

```
globals.c

```
#include "globals.h"

//aca hacemos que las variables globales tengan un espacio definido en memoria, de una vez x todas

int cpu_dispatch_connection=0;		
int cpu_interrupt_connection=0;		
int memory_connection=0;				

pthread_t thread_short_term=0;
pthread_t thread_long_term=0;
pthread_t thread_cpu_dispatch=0;
pthread_t planner_thread=0;

t_kernel_config* kernel_config=NULL;	

t_log *logger=NULL;	

sem_t *sem_multiprogrammming_degree=NULL;
sem_t *sem_short_term_planner=NULL;
sem_t *sem_long_term_planner=NULL;
sem_t *mutex_stopping_planner=NULL;



```

aquí mi main.c, donde no me marca ningun problema, ya que sin problema reconoce logger, kernel_config, cpu_dispatch_connection, cpu_interrupt_connection

```
#include "kernel.h"

int main() {
    kernel_config = create_kernel_config("configuration/kernel.config");

	logger = log_create("logs/kernel.log", "KERNEL", 1, LOG_LEVEL_TRACE);
	log_info(logger, "Kernel started");

    cpu_dispatch_connection = create_connection(logger, "CPU DISPATCH", kernel_config->cpu_ip, kernel_config->cpu_dispatch_port, TYPE_SOCKET_CLIENT);
	//send_header(cpu_dispatch_connection, KERNEL);

	cpu_interrupt_connection = create_connection(logger, "CPU INTERRUPT", kernel_config->cpu_ip, kernel_config->cpu_interrupt_port, TYPE_SOCKET_CLIENT);
	//send_header(cpu_interrupt_connection, KERNEL);
    init_connections();
    
	destroy_socket(cpu_dispatch_connection);
	destroy_socket(cpu_interrupt_connection);

    destroy_kernel_config(kernel_config);
    close_program(logger);

	return EXIT_SUCCESS;
}

void init_connections()
{
	pthread_create(&thread_cpu_dispatch, 0, (void *)handle_dispatch_connection, NULL);
	pthread_detach(thread_cpu_dispatch);

	pthread_t memory_handshake_thread; // lo creo aca porque es uno solo, esto verlo mas adelante
	pthread_create(&memory_handshake_thread, 0, (void *)memory_handshake, NULL);
	pthread_detach(memory_handshake_thread);

	pthread_create(&planner_thread, 0, (void *)planner_procedure, NULL); //hago join al hilo planificador para que no se me termine el main
	pthread_join(planner_thread,NULL);

}
```
kernel.h:

```
#ifndef KERNEL_MAIN_H_
#define KERNEL_MAIN_H_

#include <stdio.h> //ya en globals, podría sacarse de aqui?
#include <stdlib.h> //ya en globals, podría sacarse de aqui?
#include <string.h> 
#include <commons/log.h> //ya en globals, podría sacarse de aqui?
#include <commons/collections/list.h>

//a partir de aca, incluimos todos los modulos en el main
#include "handle_connection.h"
#include "config.h"
#include "utils.h"
#include "globals.h"
//#include "semaphore.h"
//#include "planners.h"
//#include "sockets.h"
//#include "process.h"

#endif
```
pero en otro modulo, tengo problemas, marca todas las variables globales en rojo y me dice
identifier "cpu_dispatch_connection" is undefinedC/C++(20) (para cpu_dispatch_connection)
mismo error para memory_connection, sin embargo, no ocurre para logger

```
#include "handle_connection.h"


void handle_dispatch_connection(void *args) //este puede ser el hio que recibe la respuesta cuando se desaloja el proceso
{
  
    while (1)
    {
        log_info(logger, "Listenning KERNEL - CPU_DISPATCH");
        header = receive_header(cpu_dispatch_connection);
        log_info(logger, "OPERATION RECEIVE (%s) FROM CPU_DISPATCH", translate_header(header));

        switch (header)
        {
        case -1:
            log_error(logger, "An error has Ocurred with CPU connection");
            return;

        default:
            log_error(logger, "Incorrect operation code (%s)", translate_header(header));
            return;
        }
    }
}


void planner_procedure(){
    while(1);//por ahora así para simular
}

void memory_handshake(){
    memory_connection = create_connection(logger, "MEMORY", kernel_config->memory_ip, kernel_config->memory_port, TYPE_SOCKET_CLIENT);
	bool memory_answer = send_handshake(memory_connection,KERNEL,MEMORY);
    if(memory_answer){
        log_info(logger,"Primer conexión establecida con memoria");
    }else{
        log_info(logger,"Error al conectar con memoria");
    }
    destroy_socket(memory_connection);
}
```

este es mi handle_connection.h

```
#ifndef KERNEL_HANDLE_CONNECTION_H_
#define KERNEL_HANDLE_CONNECTION_H_

#include "globals.h"
#include <stdio.h> //ya en globals, podría sacarse de aqui?
#include <stdlib.h>//ya en globals, podría sacarse de aqui?
#include <string.h> 
#include <commons/log.h>//ya en globals, podría sacarse de aqui?
#include <semaphore.h>//ya en globals, podría sacarse de aqui?
#include <pthread.h>//ya en globals, podría sacarse de aqui?

//incluimos las de utils
#include "sockets.h"
#include "serialization.h"
#include "operation_handler.h"
#include "process.h"

#include "kernel.h" //esto es necesario? creo que no
//#include "semaphores.h"
//#include "queues.h"
//#include "planners.h"


void handle_dispatch_connection(void *args);

void planner_procedure();

void memory_handshake();

#endif
```

### 🐛 Cómo reproducir el error

solo tengo el codigo que subi, y el editor de texto me marca en rojo las variables globales.

### 💻 Logs

no llegue a probar por consola

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by RaniAgus** [comment]
¡Buenas! ¿Probaste compilar desde VSCode como figura en [Mi primer proyecto C | Cómo compilar](https://docs.utnso.com.ar/primeros-pasos/primer-proyecto-c#como-compilar)? De ser así, ¿cuáles son los errores que aparecen? (En la misma guía hay una sección "Cómo reportar errores")

Saludos

**Comment by nicolasvultaggio** [comment]
no se, ahi otro amigo lo probo y no le marca los errores que me marca a mi, me parece que es el editor de texto el que le cuesta mucho con esto.
así tenemos organizado el trabajo
![image](https://github.com/user-attachments/assets/a336fdf4-6c4a-4c55-99df-2006004d2904)

**Comment by RaniAgus** [comment]
> no se, ahi otro amigo lo probo y no le marca los errores que me marca a mi, me parece que es el editor de texto el que le cuesta mucho con esto.

Si es un error del IDE, puede deberse a no haber importado el repo como Workspace. ¿Importaste el repo como figura en el README.md, en la sección "Importar desde Visual Studio Code"?

**Comment by nicolasvultaggio** [comment]
bueno, estoy debuggeando y me esta marcando un monton de errores en la inclusion de archivos, voy a ver si despues de corregir todo me sigue apareciendo, y si me sigue apareciendo, chequeo lo del IDE

**Comment by RaniAgus** [comment]
Ahí volví a revisar la imagen anterior y noté algo **muy importante**: la estructura que les proveemos solo permite guardar archivos fuente en la carpeta **src**, cito la guía de primer proyecto C

![image](https://github.com/user-attachments/assets/47159e82-b213-44ac-a7ee-c618ef557a81)

Si crean una carpeta `include` al lado de `src`, cosas raras pueden pasar (por ejemplo, no poder incluir headers de `utils`).

**Comment by nicolasvultaggio** [comment]
pregunta con eso, la configuracion para buscar por ejemplo 

#include "kernel.h" es, en el mismo directorio del .c que el que hace el include, o sí o sí es siempre el src? en el segundo caso, kernel.c y kernel.h deberían estar en src para que funcione

**Comment by RaniAgus** [comment]
Si usás `""`, la ruta va a ser relativa al archivo actual.

Si usás `<>`, la ruta va a ser relativa a cualquiera de las instaladas en el sistema, u otra extra que le pases al compilador.

En nuestro caso, vas a ver que al compilar se agrega un flag `-Isrc -I../utils/src`. Esto lo que hace es permitirte usar rutas relativas al `src` del módulo o del `utils`, como se muestra en el ejemplo de la guía de buenas prácticas.

**Comment by nicolasvultaggio** [comment]
okey, perfecto, por ahora cierro el issue porque se solucionaron los problemas, en caso de que vuelvan a ocurrir, lo abro, muchas gracias!
