### ISSUE TITLE
Consulta sobre sincronización de conexión de módulos

### ISSUE THREAD

**Issue by AgostinoG** [sisoputnfrba/foro#4253]
Buenas!

Tenemos una duda con respecto a la sincronización entre los servidores y los clientes. Nuestro problema es que las conexiones de cliente de un modulo se ejecutan antes de que iniciemos los servidores del resto. Estábamos pensando en varias opciones para sincronizarlo pero no estamos del todo seguros en como nos conviene encararlo. 

Desde ya, muchas gracias!

**Comment by nahuemazzeo** [comment]
Hola @AgostinoG! Como va?

No termino de entender la pregunta y que es lo que aplicaron y a que te referis con sincronizacion entre modulos.

Los modulos del trabajo practico estan descentralizados y separados en distintos procesos por lo que es muy complejo "sincronizarlos". Dicho eso, los modulos normalmente tienen un orden de ejecucion y eso lo define inicialmente el enunciado en cuanto a dependencias o en segunda instancia ustedes

Dicho eso, en nuestro trabajo práctico en Golang, los modulos son API's lo que los hace mas descentralizados. Les recomiendo leer la parte de Protocolo HTTP en el docs y sino leyendo el ticket que les adjunto 
#4251 

Lo que deberian hacer es que todos los modulos setupeen un endpoint al cual otro se conecte y luego iniciarlos en un orden para que se cumpla que Modulo A hable a B, B a C y C a D. Al final del dia todos tienen que terminar iniciados esperando que lleguen pedidos.

Al avanzar al checkpoint siguiente, esos pedidos van a empezar a desaparecer y ser reemplazados por los pedidos reales

Saludos.

**Comment by AgostinoG** [comment]
Buenísimo @nahuemazzeo, ahí nos quedó más claro. Muchas gracias! Cierro el issue.
