### ISSUE TITLE
Duda sobre el enunciado en Go

### ISSUE THREAD

**Issue by GabrielBorre** [sisoputnfrba/foro#4254]
### Lenguaje

Go

### Descripción

Buenos días! Cómo están? Tenemos una duda con respecto al enunciado de Go que nos gustaría despejar. 

En el módulo Kernel, sección "Planificador de corto plazo", Subtítulo "ejecución" (página 11),  el enunciado dice lo siguiente : 

### 📔 Citas del enunciado/videos

> Una vez seleccionado el siguiente hilo a ejecutar, se lo transicionará al estado EXEC y se enviará al módulo CPU el TID y su PID asociado a ejecutar, quedando a la espera de recibir (en una API expuesta por el Kernel) dicho TID después de la ejecución junto con un motivo por el cual fue devuelto.

### 💭 Soluciones posibles

La duda que nos surge está relacionada a si la traducción en código que nosotros estamos haciendo de esta parte del enunciado es correcta.

Nosotros tenemos dos structs declarados parcialmente (les vamos a ir agregando campos a medida que avancemos con el TP):
```Go
type PCB struct {
	PID    uint32    `json:"pid"`
	TCBS   []T_TCB   `json:"tcbs"`
	Mutexs []T_MUTEX `json:"mutexs"`
	Base   uint32    `json:"base"`
	Limite uint32    `json:"limite"`
}

type T_TCB struct {
	TID       uint32    `json:"tid"`
	Prioridad int       `json:"prioridad"`
	Estado    string    `json:"estado"`               //"NEW","READY","RUNNING","BLOCKED","EXIT", en mayuscula
	PCB       PCB       `json:"pcb"`                // el PCB es el PCB del proceso al que pertence el hilo
	regsCPU   []regsCPU `json:"regsCPU"`
}
```

La idea que nosotros tenemos en mente es la siguiente: cuando se crea un proceso, vamos a crear un PCB y un TCB con TID0, cuyo campo "PCB" apunte al PCB al que pertenece el hilo. 
Cuando necesitemos mandarle un hilo a ejecutar a la CPU, le vamos a pasar el TCB completo, el cual incluye al TID y, debido a que el TCB tiene como campo a un PCB creado, también le estaríamos pasando implícitamente el PID del proceso al que pertence dicho hilo.  

Nos resultaría más fácil trabajar con esta estructura completa (y no únicamente con el TID y el PID) porque, cuando la CPU requiera consultar el contexto de ejecución a memoria, directamente guardaríamos lo devuelto por ella en los campos correspondientes del TCB. 

Ahora bien, la pregunta que me hago es: ¿estaría bien pasarle esta estructura completa del Kernel a la CPU? ¿O únicamente debemos pasarle un PID y un TID del hilo próximo a ejecutar y solamente con esa información la CPU debe operar?

El enunciado creo que se inclina por esta segunda opción, pero me gustaría saber si podemos implementar la primera, ya que nos resultaría más fácil trabajar con una estructura completa y no con atributos aislados de la misma. 

Desde ya, muchas gracias y disculpas si la pregunta no es de las más brillantes!  
 

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by nahuemazzeo** [comment]
Hola @GabrielBorre! Como va?

Hablemos de lo que hacemos y lo que "debemos" hacer. El enunciado apunta a aplicar algunas de las "buenas practicas" que incluye que cada "pedido" debe tener lo minimo e indispensable para que el otro modulo pueda operar. Esto lleva a que la solucion deberia ser un endpoint que solo reciba tanto el PID como el TID.

En la vida real, en algunos casos, eso no pasa y se termina pasando por api's datos de mas o innecesarios que se podrian obviar. Que es lo q cambia, el trafico por red y sobre información innecesaria. En este caso es mucho, no.

Lo que si realmente me pregunto es, ¿Porque queres pasar esa estructura? Y si la respuesta es porq es mas "facil" me molestaria un poquito ya que la solución a eso son 5 lineas de codigo expresando un nuevo struct y eso haria que la API quede mas simple tanto para ustedes como para nostoros (recordando que pueden probar ese endpoint desde postman sin necesidad de tener todos los modulos).

Saludos.

**Comment by GabrielBorre** [comment]
Buenísimo Nahue @nahuemazzeo!  Muchísimas gracias por la respuesta tan clara!! 

Nos sirve mucho para pensar el resto de los endpoints que vamos a tener que establecer.

Cierro el issue

Saludos y gracias!!
