### ISSUE TITLE
[Enunciado]: conexión filsesystem con memoria

### ISSUE THREAD

**Issue by guadaabdel** [sisoputnfrba/foro#4255]
### Lenguaje

C

### Descripción

Hola, quisiera confirmar si durante el Checkpoint 1 es necesario establecer la conexión con el FileSystem, aunque no se intercambie información. Entiendo que la transmisión de datos ocurre cuando se realiza el memory dump, pero me pregunto si sería necesario tener esta conexión previa en funcionamiento antes de llegar a esa etapa, a pesar de que aún no se deba realizar el dump.

### 📔 Citas del enunciado/videos

Definir el Protocolo de Comunicación.

### 💭 Soluciones posibles

crear conexión con el filesystem sin que intercambien información

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by nahuemazzeo** [comment]
Hola @guadaabdel. El objetivo del checkpoint 1 es tener inicializados los 4 modulos y que se envie un mensaje entre los 4

Saludos.

**Comment by nahuemazzeo** [comment]
Buenas @guadaabdel. Queria confirmar si pudiste leer la respuesta y si quedo claro. Por favor si no hay otra pregunta cerrar el ticket

**Comment by paulorouss** [comment]
buenos tengo una duda con respecto a los envios de mensajes, para check 1, solo tendriamos que realizar las conexiones y enviar simplemente un mensaje random entre los modulos por el momento, como en el tp0??

**Comment by guadaabdel** [comment]
Muchas gracias por la aclaracion!
