### ISSUE TITLE
Duda sobre el enunciado en GO: Creación de procesos

### ISSUE THREAD

**Issue by GabrielBorre** [sisoputnfrba/foro#4257]
### Lenguaje

Go

### Descripción

Buenas noches! Cómo están?? Abro este issue porque no me termina de quedar clara una parte del enunciado de Go.

En la parte del Kernel, sección "planificador de largo plazo", subtítulo "Creación de Procesos" (página 9), el enunciado dice lo siguiente : 

### 📔 Citas del enunciado/videos

>Al llegar un nuevo proceso a esta cola (cola de New) y la misma esté vacía se enviará un pedido a Memoria para inicializar el mismo, si la respuesta es positiva se crea el TID 0 de ese proceso y se lo pasa al estado READY y se sigue la misma lógica con el proceso que sigue. Si la respuesta es negativa (ya que la Memoria no tiene espacio suficiente para inicializarlo) se deberá esperar la finalización de otro proceso para volver a intentar inicializarlo.

### 💭 Soluciones posibles

Hasta ahí, todo bien. El tema es que me surgen los siguientes razonamientos.

Si en la cola de NEW ya existe algún proceso y este no es el proceso inicial, esto implica que algún otro proceso (o hilo) realizó la syscall PROCESS_CREATE y, como consecuencia, el Kernel creó un proceso al que encoló en NEW. A su vez, según el enunciado, si el kernel inició un proceso, esto supone la generación de un hilo asociado al proceso con TID0, prioridad y archivo de insrucciones. Cito el enunciado (parte de "Syscalls",página 11):

>PROCESS_CREATE, esta syscall recibirá 3 parámetros de la CPU, el primero será el nombre del archivo de pseudocódigo que deberá ejecutar el proceso, el segundo parámetro es el tamaño del proceso en Memoria y el tercer parámetro es la prioridad del hilo main (TID 0). El Kernel creará un nuevo PCB y un TCB asociado con TID 0 y lo dejará en estado NEW.

Si volvemos al primer enunciado que cité, se menciona que para los procesos ubicados en la cola de NEW (es decir, por lo que entiendo, con un único hilo asociado de TID 0) de poder ser inicializados en memoria, el Kernel les creará nuevamente un hilo de TID 0  y se lo pasará al estado "Ready".

Las preguntas que me surgen son: ¿por qué el Kernel crea dos veces un TID 0 para un hilo asociado al mismo proceso (uno cuando se crea el proceso y otro cuando el proceso puede ser inicializado en memoria)? ¿No debería crear este hilo una vez, ya que el enunciado dice que los TID son únicos para los hilos asociados a un mismo proceso? ¿Qué estoy pensando mal?

Desde ya, muchas gracias!!!

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas!

Capaz lo que paso es que quisimos ser mas detallistas de lo que deberíamos haber sido y en eso se enroscó el tema.

Cuando decimos que la cola NEW tiene que estar vacía es porque puede ser que quieras crear un proceso y no tengas ninguna partición de memoria donde guardarlo entonces ese proceso se va a quedar ahí en NEW hasta que tenga espacio para entrar y por lo tanto, si después queres crear otro proceso nuevo, por más que tengas espacio en memoria, no va a entrar porque vas a tener al proceso más pesado bloqueándole la entrada.

En el momento que un proceso se puede crear porque tiene espacio en memoria, vos ya lo sacas de NEW porque el proceso esta creado y ahí es donde le creas su TID 0, en la syscall de PROCESS_CREATE tuvimos que aclarar tambien que todo proceso va a tener su TID 0, no te olvides que **los TID son relativos al proceso** y no a la ejecución global, por eso para casi todas las operaciones vas a tener que pasar la dupla PID - TID, ya que por ejemplo todo lo relacionado a memoria es asociado al proceso y no al thread.

Saludos.-

**Comment by GabrielBorre** [comment]
Genial Damián! Se entendió clarísimo. Mil gracias!!!

Cierro el issue. Saludos

**Comment by GabrielBorre** [comment]
Buenas Dami! Una consulta más y cierro de vuelta el issue. Quería consultar si lo que pensaba hacer es válido (aunque pueda ser conceptualmente incorrecto). 

Debido a que en la syscall PROCESS_CREATE la CPU le pasa por parámetro la prioridad del hilo main (TID 0), ¿podría crear la instancia del hilo con TID 0 en ese momento? Pregunto esto porque sería mucho más sencillo hacerlo de esta manera, ya que cuento de antemano con la prioridad que va a tener ese hilo main y lo único que debería hacer es agregarle ese dato al campo "Prioridad" dentro del Struct TCB.

En caso contrario, me debería guardar dicha prioridad en algún lado, para que una vez que el proceso tenga espacio en memoria, se cree la instancia del hilo con TID 0, debiendo buscar su prioridad asociada en algún registro que haya creado dentro del programa.

Si pudiera llevar a cabo la primera opción, podría simular que el TID 0 fue creado cuando el proceso tiene espacio en memoria, logeando la acción correspondiente. Pero, en realidad, la instancia del hilo habría sido creada antes ( en el momento de la creación del proceso). 

¿Puedo llevar a cabo esto?

Desde ya y nuevamente, muchas gracias!!

**Comment by nahuemazzeo** [comment]
Hola @GabrielBorre! Como estas? 

Entiendo que si lo creas "logicamente" sin planificarlo no hay problema. A que me refiero esto, que el TID 0 va a estar "creado" pero va a seguir en "new" hasta que pueda salir de esa cola (que es cuando realmente se deberia crear).

A fines practicos si lo creas en codigo cuando el PID sale de new o cuando lo vas a verificar para ver si sale cumple las condiciones de memoria para salir de esta cola inicialmente es indistinto siempre.

Saludos.

**Comment by GabrielBorre** [comment]
Nahue, excelente! Muchísimas gracias a vos y a Damián por la paciencia y las respuestas tan claras!!

Cierro el issue. Que tengan buen finde y gracias!
