### ISSUE TITLE
Orden de ejecucion módulos

### ISSUE THREAD

**Issue by tomyleca** [sisoputnfrba/foro#4258]
### Lenguaje

C

### Descripción

Buenass!
Me gustaría saber si a la hora de probar el tp los módulos van a ser ejecutados en el orden filesystem-memoria-cpu-kernel, o si este orden podría variar(lo que debería ser tenido en cuenta en el código). Por ej. si para el enunciado citado abajo habría que tener en cuenta que puede ser que el kernel se inicie antes que el cpu, lo que podría llevar a que este se conecte al socket destinado al cpu.

### 📔 Citas del enunciado/videos

"Al iniciar, esperará la conexión del módulo CPU y levantará un servidor multihilo para esperar las peticiones por parte del módulo Kernel"
(Módulo Memoria)

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Durante las pruebas uds van a ejecutarlas, así que uds van a definir el orden en el cual se van a levantar los módulos.

Saludos.-

**Comment by tomyleca** [comment]
Ok, graciass!
