### ISSUE TITLE
Memoria - Duda creacion de proceso

### ISSUE THREAD

**Issue by Brai93** [sisoputnfrba/foro#4259]
### Lenguaje

C

### Descripción

Buen dia!

Tenia una pequeña duda sobre la creacion del proceso en memoria. Si bien la teoria de PID - TID se entiende, me gustaria consultar de como funciona para traducirlo al codigo.

1. Al momento de matar un TID, es necesario que se vacie la memoria o solo la marcamos como disponible?
2. Cuando llega un process create, se envia memoria recibe el PID-TID-PATH-Tamaño relacionado a un TID 1 (PID1), en el caso de recibir otro pedido TID2 (PID1), podemos suponer que el Tamaño recibido por TID1 es diferente a TID2 por ende no seria el mismo espacio de memoria? 
3. Siguiendo a la pregunta anterior, tambien podemos entender que el path de instrucciones son independiente entre si?

Gracias!

Buen finde!!

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Cuando matas un TID no haces nada, acordate que la memoria es **del proceso**

2.- Misma respuesta que el 1, la memoria, y por ende, el tamaño son del proceso, los hilos que se creen van a compartir ese espacio de memoria

3.- Los path de instrucciones si corresponden a cada hilo.

Saludos.-

**Comment by Brai93** [comment]
Excelente. Muchas gracias por la respuesta!
