### ISSUE TITLE
Consulta sobre cantidad de prioridades

### ISSUE THREAD

**Issue by nicolasgalfione** [sisoputnfrba/foro#4260]
### Lenguaje

C

### Descripción

Buenas! Tengo la siguiente duda,

en el enunciado dice que vamos a tener una cola en ready correspondiente a cada nivel de prioridad que haya de los hilos, mi duda es si esos niveles de prioridad son variables o son fijos o como mucho cierta cantidad. Esta duda me surge ya que si por ejemplo fuesen solo 3 niveles puedo saber cuantas colas de ready necesito tener pero si la cantidad es variable no, tambien otra duda que tengo es si esos niveles que van a ir apareciendo son por ejemplo 0, 1, 2, 3, etc o puede pasar que en el sistema se cree un hilo con prioridad 0 y despues se cree uno con prioridad 2 haciendo que solo haya esas 2 prioridades en el sistema.

Mas que nada mi consulta es para saber como implementarlo, porque si puede variar la cantidad de prioridades, tendria que ir creando la lista de esas prioridades a medida que vaya apareciendo pero si fuera fija es mucho mas simple

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Las prioridades son variables, si un proceso crea un TID con una prioridad nueva, van a tener que agregar esa nueva cola de ready correspondiente a la prioridad según corresponda.

Saludos.-

**Comment by nicolasgalfione** [comment]
perfecto gracias!
