### ISSUE TITLE
duda sobre la creacion de procesos

### ISSUE THREAD

**Issue by nicolasvultaggio** [sisoputnfrba/foro#4261]
### Lenguaje

C

### Descripción

Me surgio una duda, el enunciado dice

> Al llegar un nuevo proceso a esta cola y la misma esté vacía se enviará un pedido a Memoria para inicializar el mismo, si la respuesta es positiva se crea el TID 0 de ese proceso y se lo pasa al estado READY y se sigue la misma lógica con el proceso que sigue. Si la respuesta es negativa (ya que la Memoria no tiene espacio suficiente para inicializarlo) se deberá esperar la finalización de otro proceso para volver a intentar inicializarlo.
> Al llegar un proceso a esta cola y haya otros esperando, el mismo simplemente se encola.

eso quiere decir que, si yo NO puedo crear un proceso porque no tengo espacio suficiente para crearlo, entonces debo DEJAR de intentar crear procesos hasta que se finalice cualquier otro (o sea, este proceso que no pudo crearse será el primero en intentar crear cuando se finalice otro proceso), o debo ponerlo al final de la cola new y seguir intentando con los demás procesos en la cola, en caso de que los haya?

Fui claro en las diferencias con las dos situaciones? 

aprovecho el issue para dejar dos minipreguntitas 
sem_init crea el semaforo en memoria dinamica? lo mismo con pthread_mutex_init, o debo reservar si o si el espacio con malloc?

Muchas gracias por la ayuda, buen finde!

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by RaniAgus** [comment]
¡Buenas!

> eso quiere decir que, si yo NO puedo crear un proceso porque no tengo espacio suficiente para crearlo, entonces debo DEJAR de intentar crear procesos hasta que se finalice cualquier otro (o sea, este proceso que no pudo crearse será el primero en intentar crear cuando se finalice otro proceso)

Esta opción es la correcta

> sem_init crea el semaforo en memoria dinamica? lo mismo con pthread_mutex_init, o debo reservar si o si el espacio con malloc?

Ambas funciones reciben un puntero a la dirección de memoria en donde quieran inicializar la estructura (y lo mismo para `_destroy` para liberarlas). Dicha dirección puede estar tanto en el heap como en data (o sea, ser una variable global).

Saludos

**Comment by nicolasvultaggio** [comment]
perfecto! todo claro, muchas gracias! buen domingo

**Comment by nicolasvultaggio** [comment]
perdon, me surgió otra pregunta al estar codeando, si el proceso no se puede crear hasta que haya espacio en memoria, entonces el hilo que intento crearlo se bloqueará o seguirá ejecutandose normalmente, sin importarle cuando se termine creando su proceso?

**Comment by SantiagoDopazo** [comment]
Hola buenas quizás quedo un mal entendido,

Cuando ocurre la syscall para la creación de un proceso, este pasa al estado NEW independientemente de si hay memoria disponible en ese momento. La solicitud de memoria se realiza recién cuando el proceso quiere pasar al estado READY. Por lo tanto, la planificación y ejecución del proceso no depende del hilo que lo creó. El hilo continúa su ejecución normalmente después de realizar la syscall, sin esperar a que el proceso creado tenga o no memoria disponible para ser planificado.

**Comment by nicolasvultaggio** [comment]
excelente, muchas gracias!!!
