### ISSUE TITLE
Syscall desde CPU

### ISSUE THREAD

**Issue by AGanem** [sisoputnfrba/foro#4262]
### Lenguaje

C

### Descripción

Buenas!
Cómo están? 

 En cpu cuando estoy procesando alguna syscall y tengo que notificar a kernel, el enunciado dice lo siguiente _"... se le deberá devolver el control al Kernel para que este actúe en consecuencia."_ esta comunicación debe realizarse por la socket/puerto de dispatch o interrupt? 

¿Existen  devoluciones desde CPU por el puerto interrupt hacia kernel? 
 Saludos.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by LeandroCarbajales** [comment]
Buenas!
Debería hacerse a través del puerto dispatch que es por el cual módulo Kernel estará esperando justamente que le envíen esa comunicación. El puerto interrupt, en cambio, el Kernel solamente lo utiliza para enviar las notificaciones de interrupt al módulo CPU.

Queda aclarada la duda?
Saludos!
     Lean

**Comment by AGanem** [comment]
Quedó claro. 
Gracias Lean.
