### ISSUE TITLE
Estructura de las direcciones de memoria

### ISSUE THREAD

**Issue by beniigc** [sisoputnfrba/foro#4266]
### 🖋️ Descripción

Mi duda es si para modelar las direcciones que se encuentran en la memoria y asi buscar instrucciones en ella deberiamos usar un vector o una lista. Si deberiamos usar un vector, que tamaño deberiamos establecer? muchas gracias

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by f-and** [comment]
Buenas, para saber, por direcciones, ¿te referís al espacio de memoria de usuario? Porque en ese caso no estarías manejando una estructura como una lista o un vector, ya que las direcciones que usarías serían simples punteros que se van calculando y usando a medida que los necesitas. 

En caso contrario, si te referís a la lista de instrucciones de pseudo código, te consulto a vos, ¿te sirve declarar un vector de tamaño fijo si no conoces la cantidad de instrucciones que vas a almacenar?

Saludos.

**Comment by beniigc** [comment]
genial, muchas gracias

**Comment by beniigc** [comment]
genial, gracias
