### ISSUE TITLE
Planificador a largo plazo

### ISSUE THREAD

**Issue by BalboRamiro** [sisoputnfrba/foro#4267]
### Lenguaje

Go

### Descripción

Buenas, tenemos varias dudas en cuanto al enunciado sobre el planificado de largo plazo y sus syscalls referidas.

1.  Cuando creamos un proceso y lo referenciamos con un hilo main 0, si memoria nos da el okey ¿Pasamos el hilo0 o el proceso a Ready? Pregunto esto porque en el planificador a corto plazo aplica los algoritmos con hilos pero al principio del enunciado dice que hay que planificar con los procesos de **READY**.

> Planificador de Corto Plazo
Los procesos que estén en estado READY serán planificados mediante uno de los siguientes algoritmos:

2. Cuando creamos un hilo ¿Lo referenciamos a un proceso? es decir, agregamos un argumento PID en la syscall **THREAD_CREATE** para despues ponerlo dentro del hilo que creemos, y asi queden relacionados. Nosotros en la estructura TCB le agregamos el PID por esto.

> THREAD_CREATE, esta syscall recibirá como parámetro de la CPU el nombre del archivo de pseudocódigo que deberá ejecutar el hilo a crear y su prioridad. Al momento de crear el nuevo hilo, deberá generar el nuevo TCB con un TID autoincremental y poner al mismo en el estado READY.

3. Cuando finalizamos un proceso en el enunciado no aclara que argumentos pasar, esto quiere decir que podemos agregarle los parametros que nos parezca a la Syscall **PROCESS_EXIT** o tenemos que hacer la funcion sin ningun argumento, si la respuesta es esta segunda opción, no sabriamos como llevar un proceso a **EXIT** si no nos dicen su PID.

> PROCESS_EXIT, esta syscall finalizará el PCB correspondiente al TCB que ejecutó la instrucción, enviando todos sus TCBs asociados a la cola de EXIT. Esta instrucción sólo será llamada por el TID 0 del proceso y le deberá indicar a la memoria la finalización de dicho proceso.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by BalboRamiro** [comment]
Okey, entonces cuando creo un proceso tengo que crear los hilos segun la lista de TIDs, con mi grupo pensabamos que los hilos en esa syscall quiza se podian crear independientemente de cuando se crea el proceso.

**Comment by RaniAgus** [comment]
Aclaro por las dudas, cuando se crea un proceso, éste va a tener un **único hilo** (el TID 0), cito el enunciado:

> **Creación de procesos**
> Se tendrá una cola NEW que será administrada estrictamente por FIFO para la creación de procesos. 
> Al llegar un nuevo proceso a esta cola y la misma esté vacía se enviará un pedido a Memoria para inicializar el mismo, si la respuesta es positiva **se crea el TID 0 de ese proceso y se lo pasa al estado READY y se sigue la misma lógica con el proceso que sigue.**

El resto de hilos se van creando cada vez que se llame `THREAD_CREATE`, si es que se llama (podrías tranquilamente tener un proceso monohilo y que finalice sin nunca llamar a `THREAD_CREATE`).

**Comment by BalboRamiro** [comment]
Perfecto, muchas Gracias.
