### ISSUE TITLE
Recomendación sobre respuesta sincrónica a solicitudes: GO

### ISSUE THREAD

**Issue by GabrielBorre** [sisoputnfrba/foro#4268]
### 🖋️ Descripción

¡Buenas tardes! ¿Cómo están? 

Me surgió una duda acerca de cómo prefieren que realicemos las solicitudes sincrónicas a los diferentes módulos en el lenguaje GO.

Tenemos dos opciones : 

1) En el mismo proceso en el que realizamos la solicitud al módulo podemos quedarnos esperando la respuesta de este último, bloqueando el proceso hasta que el módulo cliente reciba la respuesta.

2) Exponer una API en el módulo receptor para que el módulo servidor, una vez que haya procesado la solicitud, consuma la API del módulo cliente, enviándole la respuesta. Entiendo que si en esta opción utilizamos correctamente los semáforos, podríamos garantizar una sincronización en la petición, dado que los semáforos actuarían como elemento bloqueante.

Me gustaría saber cuál opción es recomendada por la cátedra o si, por el contrario, es indistinta cualquiera de estas dos líneas de implementación, en tanto y en cuanto el programa funcione.

 Desde ya, mil gracias!!

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Como va?

Elijan lo que les quede mas cómodo.
En Go al no tener una conexión permanente como la tendrian en C pueden darse esa llibertad de elegir.

Saludos.-

**Comment by GabrielBorre** [comment]
Buenas Dami!!

Genial, muchas gracias!!

Cierro el issue. Saludos
