### ISSUE TITLE
Consulta sobre creación de proceso inicial

### ISSUE THREAD

**Issue by AgustinHerzkovich** [sisoputnfrba/foro#4269]
### Lenguaje

Go

### Descripción

Hola, buenas tardes

Tenemos una consulta acerca de la creación del proceso inicial, ya que en el enunciado menciona que el tid 0 creado por este proceso debe contar con prioridad 0, pero como en el struct del pcb sólo tenemos la lista de tids, no sabemos cómo vincular cada tid del proceso con su tcb para modificar su prioridad.

Nosotros tenemos las siguientes estructuras:
```
type pcb struct {
	Pid       int32
	Tids      []int32
	Mutexs    []mutex

}

type tcb struct {
	Tid       int32
	Prioridad int32
}
```

Y al querer crear el proceso inicial, este crea el Tid 0 pero no sabemos cómo vincularlo con su tcb para asignarle una prioridad, ya que puede repetirse el tid entre distintos procesos.
Muchas gracias, saludos.

### 📔 Citas del enunciado/videos

> Al iniciar el módulo Kernel, se creará un proceso inicial para que éste lo planifique. Para poder inicializarlo se requerirá que el Kernel recibirá dos parámetros: el nombre del archivo de pseudocódigo que deberá ejecutar y el tamaño del proceso para ser inicializado en Memoria, el TID 0 creado por este proceso tendrá la prioridad máxima 0 (cero). (Página 8)

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Como va?

No te voy a dar una respuesta directa ya que este tipo de problemas los van a tener varias veces a lo largo del tp, por lo tanto te propongo un ejercicio.

Pensemos juntos ¿Qué estructura podemos tener en el pcb que pueda contener los TIDs?
Una pista, la tienen en el enunciado.

Ahora que estamos en el punto donde tenemos la estructura que en el pcb contiene los TIDs, hay una aclaración de como tienen que ser los TIDs, ahora despues uds pueden pensar por su cuenta lo siguiente:

Cumplo con la condición de que los TIDs son autoincrementales para cada PID, y tengo la estructura que pensé antes, por lo tanto, puedo extender uno poco el struct del PCB para tener mas info?

Saludos.-

Saludos.

**Comment by AgustinHerzkovich** [comment]
Muchas gracias.
