### ISSUE TITLE
Duda registros procesos

### ISSUE THREAD

**Issue by AgustinaGuitman** [sisoputnfrba/foro#4270]
### Lenguaje

C

### Descripción

Buenas, estamos pensando como implementar los registros de cpu para los procesos y para los hilos y queríamos verificar si nuestro razonamiento es correcto: al momento de crear un proceso se crea su hilo main y este hilo va a representar el proceso, por lo que nunca vamos a tener registros propios del proceso sino que va a haber un set de registros para cada hilo que se cree. 
Desde ya muchas gracias, saludos

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by f-and** [comment]
Buenas!
Para contestar citando de la sección del contexto de ejecución de Memoria:

> Contextos de ejecución
Se deberá almacenar, por cada PID del sistema, la parte del contexto de ejecución común para el proceso, en este caso, es la requerida para poder traducir las direcciones lógicas a físicas: **base y límite**.
Luego, por cada TID del sistema, se tendrán los registros de la CPU propios de cada hilo: **AX, BX, CX, DX, EX, FX, GX, HX y PC**. Siendo todos ellos inicializados en 0.

Por lo que, si, como decis van a manejar un set de registros por cada hilo.

Saludos.

**Comment by f-and** [comment]
Claro, en todo caso serian registros de hilos
