### ISSUE TITLE
Consulta sobre syscalls de MUTEX

### ISSUE THREAD

**Issue by LautaroRomero21** [sisoputnfrba/foro#4271]
### Lenguaje

C

### Descripción

al momento de recibir una syscall MUTEX_CREATE. no entiendo bien que seria el nombre que recibe al crearlo, en el enunciado pone un ejemplo de la siguiente imagen pero no entiendo si es un URL a un archivo? un char*? o que simularia

![image](https://github.com/user-attachments/assets/c652c4a3-bec8-402e-9fea-98063ce5bb57)

Pequeña pregunta extra: puede darse el caso de que se ejecute una syscall PROCESS_EXIT sin que hayan terminado todos los hilos de dicho proceso? (excepto del TID 0 obviamente)
### 📔 Citas del enunciado/videos

"MUTEX_CREATE: crea un nuevo mutex para el proceso sin asignar a ningún hilo. (Que un mutex esté sin asignar es el equivalente a que un semáforo contador tenga un valor de 1).
MUTEX_LOCK: se deberá verificar primero que exista el mutex **SOLICITADO** y en caso de que exista y el
mismo no se encuentre tomado se deberá asignar dicho mutex al hilo correspondiente"

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

TL-DR: El nombre que recibe al crearlo es el nombre que identifica al mutex y sería un `string`, o un `char*` si lo pensamos en C.

Explicación mas detallada: En cualquier lenguaje de programación la referencia al mutex lo tendríamos con la variable que hace referencia a la posición de memoria donde se crea y después el kernel internamente haría un montón de cosas para poder gestionarlo, pero en el TP queríamos que sea más simple y permitirles, por ejemplo, que puedan usar alguna de las colecciones de las commons que tienen la capacidad de almacenar cosas y buscarlas por una clave.
Siempre que hablamos del MUTEX solicitado es porque las operaciones de MUTEX van siempre con el nombre del mutex en cuestión.

Saludos.-
