### ISSUE TITLE
duda sobre syscalls PROCESS_CREATE y PROCESS_EXIT

### ISSUE THREAD

**Issue by LautaroRomero21** [sisoputnfrba/foro#4272]
### Lenguaje

C

### Descripción

process_create: el TID 0 de dicho proceso automaticamente se crea y se lo ingresa al proceso o debe primero hacer pedido a memoria para crear dicho hilo? (es decir, se trata como cualquier hilo posterior o este unico directamente es asignado sin precisar de la memoria?)
process_exit: puede darse el caso de recibir una syscall process_exit antes de que todos los hilos de dicho proceso hayan terminado? (salvo el TID 0 que es el que lo invoca obviamente), es decir, cuando reciba un PROCESS_EXIT debo verificar si hay algun hilo del mismo todavia en ejecucion aparte del TID 0?  

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by RaniAgus** [comment]
¡Buenas!

> process_create: el TID 0 de dicho proceso automaticamente se crea y se lo ingresa al proceso o debe primero hacer pedido a memoria para crear dicho hilo? (es decir, se trata como cualquier hilo posterior o este unico directamente es asignado sin precisar de la memoria?)

Como verán en el apartado de Memoria, las peticiones para crear un proceso y para crear un hilo tienen responsabilidades completamente distintas. Además, desde el lado de Kernel, la petición para crear el TID 0 se debe realizar solo si el proceso pudo ser creado.

Por ende, no, al crear un proceso la memoria no crea su hilo automágicamente, el Kernel debe solicitar su creación.

> process_exit: puede darse el caso de recibir una syscall process_exit antes de que todos los hilos de dicho proceso hayan terminado? (salvo el TID 0 que es el que lo invoca obviamente), es decir, cuando reciba un PROCESS_EXIT debo verificar si hay algun hilo del mismo todavia en ejecucion aparte del TID 0?

Sí. PROCESS_EXIT finaliza el proceso, por ende, todos sus hilos deben pasar a EXIT.

Saludos
