### ISSUE TITLE
Duda sobre handshakes en conexiones temporales

### ISSUE THREAD

**Issue by KirkSH** [sisoputnfrba/foro#4273]
### 🖋️ Descripción

Hola.
Nosotros tenemos implementados los handshakes con un código que el cliente envia, y un "ok" que el servidor responde (si esta ok), o un error caso contrario.
Nuestra duda es si para las conexiones temporales esto va a enlentecer mucho todo (en cuyo caso una posible solución sería que el handshake y la op. a realizar vaya en el mismo paquete), o si esa "comunicación extra" en cada conexión no perjudica en nada el buen funcionamiento del sistema.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by RaniAgus** [comment]
¡Buenas!

> Nuestra duda es si para las conexiones temporales esto va a enlentecer mucho todo o si esa "comunicación extra" en cada conexión no perjudica en nada el buen funcionamiento del sistema.

La respuesta sencilla es no: los mensajes que se envían por sockets tienen un delay de unos pocos milisegundos, solo están sujetos a la velocidad de la red. Y, al hacer las pruebas en una red local, la conexión es recontra estable, por lo que solo le suma unos pocos milisegundos (20, 30...).

> una posible solución sería que el handshake y la op. a realizar vaya en el mismo paquete

Tengan en cuenta que esto no es un handshake. Como explicamos en la [guía de sockets](https://docs.utnso.com.ar/guias/linux/sockets#send-y-recv), un handshake es simplemente un mensaje que se intercambian ambos nodos para saber en qué "protocolo" están trabajando antes de iniciar el intercambio de mensajes:

![image](https://github.com/user-attachments/assets/eb077f10-776b-413a-99dd-f3ed11812763)
> Más info: https://www.baeldung.com/cs/handshakes

Es una práctica _recomendada_, no obligatoria: en realidad podrían tranquilamente enviar y recibir mensajes y ya, pero la ventaja de hacer un handshake es detectar rápido un dedazo si alguien configura mal un puerto y se conecta al lugar equivocado.

Por ejemplo, yo no querría que Kernel haga su conexión de dispatch en el "server" de interrupt de CPU (o que se conecte a otro módulo). Entonces, una buena práctica sería tener un valor de enum para cada servidor escuchando para que el cliente le envíe ese valor como handshake y el server lo valide antes de empezar a intercambiar mensajes.

Saludos

**Comment by KirkSH** [comment]
Oka 👍. Muchas gracias por tan completa respuesta.
