### ISSUE TITLE
Duda con el momento de unos logs

### ISSUE THREAD

**Issue by KirkSH** [sisoputnfrba/foro#4274]
### Lenguaje

C

### Descripción

Las dudas son:
1.  El log de "Fin de Hilo", ¿es al momento de mandarlo a exit?, ¿o es ya dentro de exit, en el momento que memoria nos confirma su destrucción?
2. El log de "Fin de Proceso", ¿es al momento de que sus hilos se envían a exit?, ¿o es ya dentro de exit, en el momento que memoria nos confirma la destrucción de todos sus hilos?

### 📔 Citas del enunciado/videos

`Fin de Hilo: “## (<PID>:<TID>) Finaliza el hilo"`
`Fin de Proceso: “## Finaliza el proceso <PID>”`

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by f-and** [comment]
Buenas!
Para contestar a ambas te consulto a vos, te afecta tener el log en un lugar u otro? Se va a dar una posibilidad donde Memoria deje de andar por lo que los hilos/procesos no se puedan dar de baja?

Hilando fino, como la comunicación entre Kernel y Memoria no tiene retraso agregado, estas operaciones son instantaneas, por lo que no importaría, a ojos del ayudante/profesor que te evalúe el tp, si el log llega con un milisegundo de atraso o adelanto, siempre y cuando se coincida con la información que tenga el Kernel en ese momento (osea que el hilo o el proceso realmente se finalicen).

**Comment by KirkSH** [comment]
Entiendo. Muchas gracias.
