### ISSUE TITLE
KERNEL: Algoritmo de planificación en archivo de configuración

### ISSUE THREAD

**Issue by RemersaroRamiro** [sisoputnfrba/foro#4275]
### Lenguaje

C

### Descripción

Buenas, trabajando con el planificador de corto plazo en kernel nos surgió la siguiente duda acerca del ejemplo de archivo de configuración:
En la sección de archivo de configuración dice lo siguiente sobre el algoritmo de planificación:

> Define el algoritmo de planificación de corto plazo. (FIFO / PRIORIDADES / CMN).

Lo cual concuerda con el planificador de corto plazo, pero en el ejemplo de archivo de configuración marca lo siguiente:

> ALGORITMO_PLANIFICACION=VRR. 

Lo cual no corresponde con las opciones presentadas anteriormente. Además, en ninguna otra parte dentro de la sección de kernel se habla sobre Virtual Round Robin (Si del Round Robin normal dentro de las CMN pero entendemos que este no es dado por el archivo de configuración ya que forma parte del CMN)

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by f-and** [comment]
Buenas, es un typo que quedó del TP anterior, ahora lo corregimos, las tres opciones que tienen que manejar son las que pusiste, FIFO, PRIORIDADES, y CMN. Gracias por avisarnos!

**Comment by RemersaroRamiro** [comment]
Buenísimo, muchas gracias por la aclaración!
