### ISSUE TITLE
Dudas sobre syscalls

### ISSUE THREAD

**Issue by tolaDiego** [sisoputnfrba/foro#4276]
### Lenguaje

C

### Descripción

Buenas!!
Tengo un par de dudas respecto al enunciado:
1. El recurso del mutex create, lock y unlock que tipo de  datos es? por ahora lo tengo como char*
2. Respecto a cuando se envia el thread a bloqueado con la syscall **mutex_lock**. Planteo el siguiente escenario:
Estando del lado del kernel y asumiendo que el recurso ya esta asignado, si  me llega esta syscall lo envio a bloqueado en este momento? o primero le aviso a cpu por interrupt que se debe desalojar el thread ejecutando y recien, cuando cpu me envie por dispatch el tid, puedo enviarlo a bloqueado.
3. Sobre la syscall thread_join, podria darse el caso de que un threadA ejecute thread_join(threadB) y que B a su vez ejecute otro join a otro thread C y por ultimo que C haga thread_join(threadA)? 
4. Y cuando termina un thread al que se le hace join, el que ejecuto la intruccion de join vuelve a ready o se ejecuta inmediatamente despues de que termino el primero?

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Es el nombre de un mutex, tienen el ejemplo en la parte de CPU y es un `string` o `char *`
2.- El thread se desaloja en el momento que ejecuta la syscall, por lo tanto no tenes que interrumpir nada, lo moves a block y después a la CPU le mandas el próxima thread a ejecutar.
3.- Puede darse el caso y no habría problema, simplemente esos 3 hilos quedarían en deadlock.
4.- El thread que ejecuto join vuelve a ready, el comportamiento esperado es el mismo comportamiento que el que tienen con `MUTEX_UNLOCK`.

Saludos.-

**Comment by tolaDiego** [comment]
Gracias!
De la respuesta a la segunda pregunta me surge otra duda.
![image](https://github.com/user-attachments/assets/f233a95e-e641-442e-b2af-b5a53ce1e195)
![image](https://github.com/user-attachments/assets/53b43c80-505b-45c5-8053-a1aff6efe0a5)
Cuando en el enunciado dice que " primero se debe verificar si existe el mutex..." (o thread para hacer el join),
cpu primero deberia preguntarle a kernel si existe y segun la respuesta decide si debe mandar realmente la syscall (lock o join)o continuar ejecutando el mismo hilo?

**Comment by iago64** [comment]
Buenas! Cómo va?

Pensemos juntos un poco, las validaciones, ¿Las hace la CPU o las hace el Kernel? ¿Tiene sentido que la CPU entienda que tiene que revisar cosas que ni sabe que existen?

Citando al enunciado en la parte de CPU encontramos:

> Las siguientes instrucciones se considerarán _Syscalls_ ya que se deberá actualizar el contexto de ejecución en el módulo Memoria y se le deberá devolver el control al **Kernel** para que este actúe en consecuencia.

Con lo cual, las validaciones que mencionaste, son validaciones que debe hacer el Kernel y no la CPU.

Saludos.-

**Comment by tolaDiego** [comment]
Gracias.
