### ISSUE TITLE
Archivo pseudocodigo y memoria

### ISSUE THREAD

**Issue by JuanTerri** [sisoputnfrba/foro#4277]
### Lenguaje

C

### Descripción

el archivo de pseudocodigo con el que se inicializa kernel, se debe mandar a memoria? tengo entendido que en el archivo van a estar todas las instrucciones que se tienen que ir ejecutando, por ende calculo que se debe mandar a memoria. Luego de esto, memoria deberia deserializar y guardarse todas las instrucciones? En ese caso, el campo "PATH_INSTRUCCIONES" que esta en memoria.config, ¿para que puede servir? Pense por un momento que en ese path se van a guardar las instrucciones, pero en ese caso estarian guardados en disco y no se encontrarían en la memoria

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

El `PATH_INSTRUCCCIONES` es el directorio donde van a estar los archivos de pseudocódigo, en máquina que ejecute la memoria.
Despues en el kernel y en las instrucciones para crear procesos e hilos les vamos a pasar un path relativo a ese punto de `PATH_INSTRUCCIONES` para que puedan encontrar el archivo correspondiente.

Visto en un ejemplo si tenemos 2 archivos de instrucciones:
`/home/utnso/instrucciones-tp/prueba-1/hiloConMuchasIO`
`/home/utnso/instrucciones-tp/prueba-1/hiloSoloCPU`

Y el valor de `PATH_INSTRUCCIONES` es `/home/utnso/instrucciones-tp`
Después nosotros les vamos a pasar por ejemplo `/prueba-1/hiloConMuchasIO` o `/prueba-1/hiloSoloCPU` como parámetro del kernel.

Saludos.-

**Comment by JuanTerri** [comment]
Perfecto, muchas gracias. Saludos.
