### ISSUE TITLE
Duda sobre multiples conexiones para cada petición

### ISSUE THREAD

**Issue by ahuarca** [sisoputnfrba/foro#4278]
### 🖋️ Descripción

Wenas, teniamos una duda sobre las conexiones de las peticiones entre Kernel y Memoria, ya que el enunciado dice:

EN MEMORIA
![image](https://github.com/user-attachments/assets/c01faf67-4d9d-483c-974f-913c559a9b99)

EN KERNEL

![image](https://github.com/user-attachments/assets/a8d57f47-2fc9-4d0c-a8ea-47e843f30613)

Ya teniendo las conexiones inicializadas entre todos los módulos, se deberían realizar  las conexiones secundarias para cada una de las peticiones de Kernel a Memoria y que luego finalicen, o sea creamos hilos sólamente en el modulo de Memoria y que kernel no tenga hilos para cada petición / socket que se genere,  sino que verifiquen de alguna manera ya sea un while o un if, que el codigo de operacion sea válido y que se haga una conexión dentro de esa verificación que espera la respuesta y que luego finalicé la conexión 

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Me parece que el check de lineamientos del foro lo marcaste sin leer, porque esta el punto de **Desaconsejamos el uso de capturas de pantalla**.

Dicho lo anterior y ahora si respondiendo a la duda:
No tenes forma de crear multiples conexiones tanto en Kernel como en Memoria si no crear múltiples hilos en ambos lados, ya que vos desde el Kernel harías un `send()` e inmediatamente despues te bloquearías en un `recv()` y por lo tanto no podrías ejecutar nada mas en ese hilo.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas! Me sumo solo para decir que en Memoria la implementación de hilos es más clara (1 hilo por cada solicitud del Kernel), pero en cambio en Kernel la decisión de cuándo crear un hilo y cuándo utilizar el existente debe ser de ustedes.

Como bien dijo Dami, cada vez que uno haga `recv()` de una respuesta de Memoria ese hilo se va bloquear. Esto significa que si implementan, por ejemplo, la creación de procesos y ejecutar un memory dump en un mismo hilo, la primera operación va a bloquear a la segunda, y eso no es lo que debería ocurrir ya que ambas se deberían poder realizar concurrentemente.

Dicho esto, una forma de encarar el problema de _cuántos hilos debe tener Kernel_ es plantear la solución a **alto nivel**, parecido a un ejercicio de sincro: una tablita con los hilos, las funciones a ejecutar en cada uno y las estructuras administrativas compartidas entre sí.

Esto ayuda a no enfrascarse en los detalles de cómo implementarlo en código, que suele tener un montón de líneas, y pensar al módulo como un todo de la misma forma en la que vienen practicando los ejercicios de sincro, con la diferencia de que en este caso no tienen los hilos ya creados, sino que son ustedes los encargados de decidir cuántos hilos usar y en dónde poner cada acción. Es como redactar el ejericio de sincro y resolverlo.

Una vez tengan hecho eso y que más o menos _compile en hoja_, esa guía les va a servir para luego ir de a poco implementando la solución en código. Para no spoilear a los demás grupos, siéntanse libres de pasar por soporte los sábados si tienen alguna duda particular sobre la solución que ustedes hayan planteado, y dejemos el foro para consultas generales de enunciado o de programación en C.

Saludos

**Comment by ahuarca** [comment]
Hola!!
 Aaaah, ahí me quedo más claro como sería la dinámica entre Kernel y
Memoria, muchas gracias por las aclaraciones a ambos, creo que ya tenemos
una forma de encararlo, y mucha gracias por el tip de hacer la
sincronización primero en hoja!!!
