### ISSUE TITLE
Puerto CPU Interrupt: Enunciado n GO

### ISSUE THREAD

**Issue by GabrielBorre** [sisoputnfrba/foro#4279]
### Lenguaje

Go

### Descripción

Buenos días! Cómo están?

Tengo una consulta sobre el enunciado en Go.

En el archivo de configuración de ejemplo del Kernel solo se incluye un solo puerto de la CPU (a diferencia del enunciado en C, en donde se incluyen los puertos dispatch e interrupt de la CPU). 

La pregunta es: ¿podemos utilizar este único puerto para mandarle a la CPU los hilos a ejecutar y además enviar las interrupciones? ¿O debemos obligatoriamente (como es en el caso de C) agregar el puerto de las interrupciones para que estas se envíen, utilizando el puerto interrupt?

Desde ya, muchas gracias!

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by RaniAgus** [comment]
¡Buenas! Tenemos un único puerto ya que con HTTP es más fácil diferenciar ambas funcionalidades agrupando por ruta (ej: `POST /dispatch` y `POST /interrupt`).

Para C también se podría utilizar un único puerto para ambas conexiones ya que por cada `accept()` se devuelve un nuevo socket, y con un handshake se podría identificar qué funcionalidad se conectó. Utilizar distintos puertos es solamente una simplificación para evitar tener que implementar dicho handshake.

Saludos

**Comment by GabrielBorre** [comment]
Excelente, Agus! Clarísima la respuesta!

Mil gracias!!

Saludos y buena semana. Cierro el issue
