### ISSUE TITLE
¿Se pueden usar "Query parameters" en el TP?

### ISSUE THREAD

**Issue by tomaspauzasager** [sisoputnfrba/foro#4281]
### Lenguaje

Go

### Descripción

Hola, buen día.
Nos estabamos preguntando si se puede hacer uso de los query parameters para la comunicación entre modulos. 
Desde ya muchas gracias. 

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Como poder, pueden usarlos, traten nomas de no complicarse la vida, si necesitan mucha info capaz les convenga usar un body y un POST :)

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @tomaspauzasager! ¿Les sirvió la respuesta de Dami? Saludos

**Comment by iago64** [comment]
Cerramos el issue por inactividad.
