### ISSUE TITLE
Peticiones Kernel-Memoria

### ISSUE THREAD

**Issue by inaaranza** [sisoputnfrba/foro#4282]
Buenas! Hago una consulta sobre la forma de conexión del kernel con la memoria.

Cuando se ejecuta el kernel y conecta con memoria, ¿debe mantener esa conexión abierta y para cada peticion abrir una nueva conexion? ¿O la conexión inicial, cuando se ejecuta el modulo, también se debe cerrar y luego abrir una conexión para cada petición? 

Muchas gracias :)

**Comment by RaniAgus** [comment]
¡Buenas! Para entender mejor la duda, tengo un par de preguntas que estaban (algunas como opcionales, otras como obligatorias) en el issue form inicial: ¿La pregunta es sobre el enunciado en C o el de Go? ¿A qué parte del enunciado se refieren cuando hablan sobre una conexión inicial entre Kernel y Memoria?

Saludos

**Comment by inaaranza** [comment]
Hola Agus!

Perdon que no dejé las cosas que estaban marcadas obligatorias. Hablo del enunciado en C y en la conexión inicial me refiero a cuando se levanta el módulo de kernel. Al levantarse el módulo entiendo que le tiene que pasar a memoria el archivo de pseudocodigo y tambien el tamaño del proceso inicial. El acto de inicial el modulo y enviar el paquete con esas cosas lo tomo como "la conexión inicial". Mi pregunta es si esa conexión se debe dar de baja y luego ante cada peticion iniciar una nueva, o si esa "conexión inicial" se mantiene y luego se abren otras para el resto de peticiones.

Saludos :)

**Comment by RaniAgus** [comment]
Oh, entiendo! En realidad no hay tal conexión inicial: El thread 0 del proceso 0 puede tratarse de igual forma que cualquier otro proceso y cualquier otro hilo ya que, como verán a lo largo del enunciado, todos los procesos tienen un tamaño inicial y un archivo de pseudocódigo para el TID 0. La única diferencia es que este hilo siempre tendrá prioridad 0.

Entonces, en realidad, no deben tratar al primer proceso como un caso particular con una conexión particular con Memoria, simplemente es un proceso más que dispara conexiones efímeras igual que el resto :)

Saludos

**Comment by inaaranza** [comment]
Buenisimo Agus! Muchas gracias :)

Saludos
