### ISSUE TITLE
Duda con respecto al planificador Colas Multinivel

### ISSUE THREAD

**Issue by zakerik10** [sisoputnfrba/foro#4283]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas.
Tengo una duda con respecto a Colas Multinivel.
Dice que el algoritmo entre colas es sin desalojo, y que cada cola usa Round Robin. Quiero saber si lo que creo que hay que hacer es correcto:
Si tengo varias colas creadas, agarro la de mayor prioridad, y ejecuto todos los procesos que esta tenga hasta que se vacíe la cola.
Teniendo en cuenta que dentro de la cola, se van cambiando los procesos a ejecutar por el algoritmo RR, según el Quantum
Cuando termino de ejecutar todos los procesos de la cola, agarro otra cola, teniendo en cuenta su prioridad, y asi sucesivamente.

### 📔 Citas del enunciado/videos

Colas Multinivel
Se elegirá al siguiente hilo a ejecutar según el siguiente esquema de colas multinivel:
- Se tendrá una cola por cada nivel de prioridad existente entre los hilos del sistema.
- El algoritmo entre colas es de prioridades sin desalojo.
- Cada cola implementará un algoritmo Round Robin con un quantum (Q) definido por archivo de configuración.
- Al llegar un hilo a ready se posiciona siempre al final de la cola que le corresponda.

### 📝 Normas del foro

- [x] Leí los lineamientos del foro

**Comment by LeandroCarbajales** [comment]
Buenas!
Veo correcta tu interpretación :)
Como único comentario puedo hacer que siempre chequeen las prioridades/colas que existan a la hora de replanificar, ya que al ejecutar un hilo quizás creó otro de mayor prioridad (teniendo ahora una nueva cola), por lo que al salir por fin de Q o bloquearse debería ahora ejecutar el más prioritario y no el que le sigue en su misma cola.

Te aclara la duda?
Saludos!
 Lean

**Comment by zakerik10** [comment]
Okey, mi duda tambien venia por el lado de que se tenia que vaciar la cola, antes de pasar a otra. Pero si aparece otra cola de mayor prioridad, aunque siga teniendo procesos a ejecutar, paso a la otra cola.
Ya quedo entendido, muchas gracias.
