### ISSUE TITLE
Duda sobre parametros de las syscalls 

### ISSUE THREAD

**Issue by tomyleca** [sisoputnfrba/foro#4285]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas! Teniamos unas dudas respecto a las syscalls. Los parametros que figuran en el enunciado son los parametros minimos que se le deben a pasar o son los únicos? Porque estamos teniendo problemas para codear el THREAD_CREATE sin poder pasarle a que proceso pertenece el hilo como parametro.

### 📔 Citas del enunciado/videos

"THREAD_CREATE, esta syscall recibirá como parámetro de la CPU el nombre del archivo de pseudocódigo que deberá ejecutar el hilo a crear y su prioridad. Al momento de crear el nuevo hilo, deberá generar el nuevo TCB con un TID autoincremental y poner al mismo en el estado READY."

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by SantiagoDopazo** [comment]
Hola buenas,
Recuerden que cada proceso es responsable de crear y gestionar sus propios hilos. Los hilos siempre pertenecen al contexto del proceso que los creó y comparten con él recursos como el código, los datos, el heap y algunas secciones del PCB. Otro proceso, ajeno a estas estructuras, no tiene la capacidad de crear hilos dentro de ese proceso, ya que los hilos están vinculados al espacio de direcciones y recursos del proceso que los contiene.
Esto ya tómalo con pinzas pero creo que ningún sistema operativo te va a dejar crear hilos de un proceso a partir de otro seria un falta muy grave de seguridad y una manera muy complicada de gestionarlos.

**Comment by iago64** [comment]
Buenas! Cómo va?

Para sumar a la respuesta de Santi, algo copado, por asi decirlo, es que en este TP al tener una sola CPU, por lo tanto, el Kernel debería tener en algun lugar registro de que _proceso e hilo_ estan ejecutando en la CPU al momento que te llega la syscall.

Saludos.-

**Comment by tomyleca** [comment]
Perfecto, ahi quedo mas claro. Graciass!
