### ISSUE TITLE
Duda sobre Kernel y Memoria

### ISSUE THREAD

**Issue by RodrigoSarmiento** [sisoputnfrba/foro#4288]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Hola, teníamos unas consultas sobre el enunciado que queríamos saber si nos podían responder:

* Debemos guardar el TCB en la imagen del PCB?
* Debemos guardar Procesos en la memoria simulada del sistema o solo van a estar en un array en kernel?
* Puede cambiar el algoritmo de planificación del kernel durante la ejecución???
* Existen prioridades para las interrupciones?

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Voy contestando las dudas:

> Debemos guardar el TCB en la imagen del PCB?

Si por imagen te referis al espacio de usuario no, los TCB y PCB residen en el Kernel y en la memoria de sistema tienen los contextos de ejecución.

> Debemos guardar Procesos en la memoria simulada del sistema o solo van a estar en un array en kernel?

Misma respuesta anterior, en la parte de memoria del sistema del módulo memoria van a tener los contextos de ejecución y los archivos de pseudocódigo, la parte de usuario la van a usar para los datos que vamos a escribir lo leer con las operaciones de READ_MEM y WRITE_MEM.

> Puede cambiar el algoritmo de planificación del kernel durante la ejecución???

No, una vez iniciados los procesos no cambiamos los configs hasta que los finalicemos.

> Existen prioridades para las interrupciones?

No, eso lo dejamos para otro TP 😉 

Saludos.-

**Comment by RodrigoSarmiento** [comment]
Ah buenisimo gracias, ya nos quedo todo claro.

**Comment by RodrigoSarmiento** [comment]
Ah buenisimo gracias, ya nos quedo todo claro.
