### ISSUE TITLE
Consulta sobre el modulo kernel

### ISSUE THREAD

**Issue by Nardelli-Federico** [sisoputnfrba/foro#4289]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Con mi grupo no terminamos de entender la cola READY, estamos en duda si es una cola de hilos o una cola de cola de hilos

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by SantiagoDopazo** [comment]
Hola Buenas!

Dependiendo del algoritmo de planificación que definan en el archivo de configuración, deberán adaptar la estructura de las colas. Algunas recomendaciones:

**FIFO y Prioridades**: Van a poder trabajar con una sola cola de hilos,

**Colas Multinivel**: En este caso, necesitarán implementar varias colas, cada una representando un nivel de prioridad. 

Sobre la cola de colas de hilos se están complicando mas de la cuenta así que no recomiendo que usen una estructura así.

Aclaro que si no encuentran una implementación concreta en el enunciado, pueden elegir la que les parezca más conveniente para el grupo, siempre y cuando respete el esquema planteado en el enunciado.

Cualquier duda, vuelvan a consultar

**Comment by Nardelli-Federico** [comment]
Muchas gracias
y sobre las prioridades, tenemos que asumir que puede haber prioridades "infinitas"? o tenemos un numero finito de prioridades?

**Comment by iago64** [comment]
Buenas! Cómo va?

Si, las prioridades son dinámicas (infinitas no, pero si que pueden tener en una prueba prioridades 0, 1, 2 y 3 y otra con prioridades 0, 2, 6, 45, 123123)

Saludos.-

**Comment by SantiagoDopazo** [comment]
te dejo un issue anterior que habla del tema: https://github.com/sisoputnfrba/foro/issues/4260

**Comment by Nardelli-Federico** [comment]
Okay muchísimas gracias, nos sirvió un montón
