### ISSUE TITLE
duda sobre las colas de estados

### ISSUE THREAD

**Issue by nicolasvultaggio** [sisoputnfrba/foro#4290]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

tengo una pregunta sobre los distintos estados y sobre que es lo que deberían "almacenar" cada uno

tengo entendido que el estado new debería almacenar los pcbs de los procesos a crear, luego new, block y exec almacenan TCBs ya que sirven para la planificacion a corto plazo de los hilos, pero la cola exit, que almacena? ya que se pide, al finalizar un hilo o un proceso, liberar el tcb y el pcb respectivamente, entonces qué es lo que se envia a exit? 

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Por como describís el problema, me da la sensación de que tu forma de pensar es que los estados son cajas donde guardas las cosas PCBs y/o TCBs, en este caso. Ahora pensémoslo desde otro enfoque, que te parece si vemos al estado como una descripción de lo que está pasándole a ese TCB y/o PCB en ese momento, entonces ahi es donde podemos ver por ejemplo que:

NEW: Es un estado donde no tenes las cosas para ejecutar, como por ejemplo la memoria no te creó el contexto de ejecución

READY: Es un estado que te dice que quien lo tiene está esperando para ejecutar, está en la fila.

BLOCK: Este estado te dice que el PCB o TCB está esperando que se complete una acción para poder volver a estar listo, en la vida real puede ser por ejemplo que te cierre el resumen de la tarjeta para hacer la próxima ~bolucompra~ compra totalmente innecesaria pero que vas a hacer porque sos un adulto independiente.

EXIT: Es ese estado donde ya está, ya terminaste, no tenes más nada que hacer en el sistema, aca con que tengas las referencias de PID / TID que llegaron alcanza y sobra.

Saludos.-

**Comment by nicolasvultaggio** [comment]
okey perfecto, me ayudo esa forma de pensar el problema,muchas gracias!!!
