### ISSUE TITLE
Consulta sobre manejo de la planificación.

### ISSUE THREAD

**Issue by facundo-slaibe** [sisoputnfrba/foro#4291]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Al momento de implementar el planificador de corto plazo nos encontramos con un problema al asociar los tids con su pid padre correspondiente. 

Por lo que entendemos, por ejemplo al planificar por FIFO a nosotros solo nos interesa el orden de llegada de los hilos, no de los procesos, por ende, la cola de ready posee únicamente los tcbs a ejecutar. El problema con esto es que al poseer únicamente los tcbs perdemos el dato de a que pid están asociados.

La pregunta seria si es teóricamente correcto que los tcbs tengan el pid del padre asociado.

Muchas gracias!

### 📔 Citas del enunciado/videos

TCB

> El TCB será la estructura base que utilizaremos dentro del Kernel para administrar los hilos de los diferentes procesos.

- > TID: Identificador del hilo.

- > Prioridad: Es la prioridad del hilo dentro del sistema.

### 💭 Soluciones posibles

1. Una solución que planteamos es agregar a la estructura del tcb un campo extra que sea pid del padre. El problema es que no estamos seguros de si esto es teóricamente correcto. Tampoco sabemos si es correcto, ya que, el enunciado no dice que podemos agregar un dato mas de los que especifica el enunciado para el tcb.

2. Otra forma podría llegar a ser que la cola ready sea únicamente de pcbs y que al momento de planificar se fije en todos los tids que tiene cada proceso, pero nos parece mas complejo.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Pueden sumarse la referencia del PID del proceso al cual pertenece cada TCB si esto les facilita el trabajo.

Saludos.-

**Comment by facundo-slaibe** [comment]
Perfecto! Muchas gracias
