### ISSUE TITLE
Consulta sobre actualizar contexto de ejecucion y uso de los archivos de pseudocodigo

### ISSUE THREAD

**Issue by Ranico1** [sisoputnfrba/foro#4292]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

Buenas tardes, junto a mi grupo teniamos dudas sobre dos partes del enunciado en Go. 
- La primera de ellas referida al uso de los archivos de pseudocodigo a la hora de almacenar las instrucciones, ya que nos resulta ambiguo si el enunciado busca que ademas de almacenar las instrucciones correspondientes al hilo, se almacene el path al archivo. En el caso de que no se almacene, cual es la procedencia del path propio del archivo. 
- La segunda apuntada a la actualizacion de los registros pedida por CPU, la cual tenemos la duda si debe realizarse luego de cada lectura de instruccion o a que hace referencia esa parte del enunciado. 

### 📔 Citas del enunciado/videos

- Archivos de pseudocódigo
Por cada TID del sistema, se deberá leer su archivo de pseudocódigo y guardar de forma estructurada las instrucciones del mismo para poder devolverlas una a una a pedido de la CPU. Queda a criterio del grupo utilizar la estructura que crea conveniente para este caso de uso.

- Actualizar contexto de ejecución
Deberemos actualizar los registros de la CPU propios del hilo en su estructura correspondiente y responder la petición como OK.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

> La primera de ellas referida al uso de los archivos de pseudocodigo a la hora de almacenar las instrucciones, ya que nos resulta ambiguo si el enunciado busca que ademas de almacenar las instrucciones correspondientes al hilo, se almacene el path al archivo. En el caso de que no se almacene, cual es la procedencia del path propio del archivo.

No hace falta que se guarden el path, lo que les damos es la total libertad de leer el archivo de pseudocódigo como mas simple les resulte, ya que capaz un grupo se guarda un array con las instrucciones y ya esta, capaz otro grupo solo guarda el path y cada acceso abre el archivo y busca la linea correspondiente, a fines prácticos no nos cambia el resultado de las pruebas.

> La segunda apuntada a la actualizacion de los registros pedida por CPU, la cual tenemos la duda si debe realizarse luego de cada lectura de instruccion o a que hace referencia esa parte del enunciado.

En el momento que la CPU va a desalojar el proceso, independientemente de si es por un error, una syscall o una interrupción, ahi tienen que actualizar el contexto de ejecución en la Memoria y por eso les decimos que tienen que actualizar los registros de la CPU, porque eso es el contexto de ejecución del Hilo.

Saludos.-
