### ISSUE TITLE
Pcb en memoria

### ISSUE THREAD

**Issue by AgustinHerzkovich** [sisoputnfrba/foro#4293]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

Hola, buenas tardes:
1) El PCB se almacena en memoria? 
2) Qué debe mandarle kernel a memoria para inicializar un proceso?
Muchas gracias, saludos.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by RaniAgus** [comment]
¡Buenas!

1. No, lo único que debe almacenarse en Memoria es lo especificado en las secciones "Memoria del Sistema" y "Memoria de Usuario" del enunciado. Entendemos que en la vida real todo está en memoria, pero a modo de simplificación no es necesario guardar el PCB completo para este TP.

2. Debe mandarle lo necesario para poder cumplir con la sección "Creación de proceso" del módulo Memoria. Es decir, todo lo necesario para asignarle un espacio en la memoria de usuario y que ese espacio pueda ser usado por todos los hilos que se vayan creando posteriormente.

Saludos

**Comment by AgustinHerzkovich** [comment]
Muchas gracias, saludos.
