### ISSUE TITLE
Duda Archivos de pseudocodigo, tamaño del Proceso, Planificacion de hilos y Particiones Memoria

### ISSUE THREAD

**Issue by Martlar1502** [sisoputnfrba/foro#4294]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

Buenas tardes,

Teniamos algunas dudas sobre  Archivos de pseudocodigo, tamaño del Proceso, Planificacion de hilos y Particiones Memoria del TP de Go

Archivos de pseudocodigo: 

- Estos archivos deberían de ser creados por nosotros con instrucciones cualquiera en assebler para modificar los registros del CPU?
- Cada hilo debería de tener un archivo de pseudocodigo o solamente debería de tenerlo el proceso?
- Ese archivo de pseudocodigo, debería almacenarse como una ruta hacia el archivo? O deberíamos almacenarlo como una lista de instrucciones dentro del proceso/hilo?

Tamaño del proceso:

- El tamaño del proceso, debería ser definido por nosotros como un valor ficticio o en que debería de basarse?

Planificacion de hilos:

- ¿La creacion de hilos es en diferentes listas de READY segun prioridad en largo plazo, y despues cada lista se vuelve a manejar con otra subplanificacion (fifo, prioridades, multinivel) en corto plazo? 
- Se deben de implementar fifo, prioridades, multinivel para la planificacion de hilos o solamente elegir una de ellas?

Particiones de Memoria:

- Las particiones de memoria  Fijas y  Dinamicas deben de estar las dos implementadas o se debe de elegir una de las dos para mantener fija? 

### 📔 Citas del enunciado/videos

Archivos de pseudocodigo y tamaño del proceso:

>Al iniciar el módulo Kernel, se creará un proceso inicial para que éste lo planifique. Para poder inicializarlo se requerirá que el Kernel recibirá dos parámetros (argumentos): el nombre del archivo de pseudocódigo que deberá ejecutar y el tamaño del proceso para ser inicializado en Memoria, el TID 0 creado por este proceso tendrá la prioridad máxima 0 (cero).
./bin/kernel [archivo_pseudocodigo] [tamanio_proceso] [...args]<

>Por cada TID del sistema, se deberá leer su archivo de pseudocódigo y guardar de forma estructurada las instrucciones del mismo para poder devolverlas una a una a pedido de la CPU. Queda a criterio del grupo utilizar la estructura que crea conveniente para este caso de uso.<

Planificacion de Hilos:
>
FIFO
Se elegirá al siguiente hilo a ejecutar según su orden de llegada a READY.
Prioridades
Se elegirá al siguiente hilo a ejecutar según cual tenga el número de prioridad más bajo, siendo 0 la máxima prioridad. En caso de tener varios hilos con la máxima prioridad, se desempata por FIFO. Se pide implementar este esquema con desalojo de manera que si llega un hilo a la cola de READY con mayor prioridad que el hilo que está actualmente ejecutando, se deberá desalojar a este último.
Colas Multinivel
Se elegirá al siguiente hilo a ejecutar según el siguiente esquema de colas multinivel:
- Se tendrá una cola por cada nivel de prioridad existente entre los hilos del sistema.
- El algoritmo entre colas es de prioridades con desalojo (mismo funcionamiento anteriormente explicado).
- Cada cola implementará un algoritmo Round Robin con un quantum (Q) definido por archivo de configuración.
- Al llegar un hilo a ready se posiciona siempre al final de la cola que le corresponda. Esto aplica también al desalojo entre colas, es decir, al desalojar un hilo por la llegada de otro de más prioridad, se pondrá al final de su respectiva cola (al igual que si hubiera sido desalojado por quantum).<

Particiones de Memoria:

>Particiones Fijas: En este esquema la lista de particiones vendrá dada por archivo de configuración y la misma no se podrá alterar a lo largo de la ejecución.
Particiones Dinámicas: En este esquema la lista de particiones, va a iniciar como una única partición libre del tamaño total de la memoria y la misma se va a ir subdividiendo a medida que lleguen los pedidos de creación de los procesos, es por esto que la lista será dinámica.
En ambos esquemas, el hueco a asignar y/o fraccionar se deberá elegir utilizando alguna de las siguientes estrategias:
First Fit
Best Fit
Worst Fit<

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Paso a responderte citando cada punto asi es mas facil 

### Archivos de pseudocodigo:

> Estos archivos deberían de ser creados por nosotros con instrucciones cualquiera en assebler para modificar los registros del CPU?

No son instrucciones de assembler, si no que son las instrucciones que les detallamos nosotros en la CPU, pero si, los tienen que crear uds hasta que les demos los scripts de pruebas, que posiblemente en un par de semanas estemos subiendo algunos como para que empiecen a probar algo.

> Cada hilo debería de tener un archivo de pseudocodigo o solamente debería de tenerlo el proceso?

Los archivos de pseudocódigo son por hilo.


> Ese archivo de pseudocodigo, debería almacenarse como una ruta hacia el archivo? O deberíamos almacenarlo como una lista de instrucciones dentro del proceso/hilo?

Elijan lo que mas simple les resulte, ahi el enunciado les da total libertad.


### Tamaño del proceso:

> El tamaño del proceso, debería ser definido por nosotros como un valor ficticio o en que debería de basarse?

Se basa en el parámetro que les llega en el CREATE_PROCESS o en el parametro que reciben al iniciar el Kernel para el proceso 0.

### Planificacion de hilos:

> ¿La creacion de hilos es en diferentes listas de READY segun prioridad en largo plazo, y despues cada lista se vuelve a manejar con otra subplanificacion (fifo, prioridades, multinivel) en corto plazo?

En este TP el concepto de Largo Plazo solo aplica para los procesos, los hilos al no reservar espacio en memoria siempre se pueden crear.


> Se deben de implementar fifo, prioridades, multinivel para la planificacion de hilos o solamente elegir una de ellas?

Se implementan los 3 algoritmos.


### Particiones de Memoria:

> Las particiones de memoria Fijas y Dinamicas deben de estar las dos implementadas o se debe de elegir una de las dos para mantener fija?

Se implementan los 2 esquemas.

Saludos.-

**Comment by SantiagoDopazo** [comment]
Hola buenas, La duda quedo resuelta? Si es así no olviden cerrar el issue.
