### ISSUE TITLE
sobre string duplicate

### ISSUE THREAD

**Issue by nicolasvultaggio** [sisoputnfrba/foro#4295]
### 🖋️ Descripción

string duplicate devuelve una copia del string en el heap o en el stack? es una pregunta medio pava pero estoy buscando en librerias y no puedo encontrar donde dice la respuesta

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by RaniAgus** [comment]
¡Buenas! Pueden consultar cualquier definición de cualquier función de las commons en su sitio de documentación: https://sisoputnfrba.github.io/so-commons-library/

Saludos
