### ISSUE TITLE
Duda sobre la creación de procesos en el enunciado

### ISSUE THREAD

**Issue by EmaSantoro** [sisoputnfrba/foro#4297]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

Buenas tardes, tenemos una duda con las colas en la creación de un proceso en Kernel.
Al crear el proceso, realizamos una go routine para inicializarlo. En la misma creamos el pcb y consultamos si hay espacio en memoria, en caso que lo haya lo encolamos en NEW el proceso y en READY el hilo 0 y quedaría inicializado.
Nuestra duda con el enunciado es que, al inicializar el primer proceso, no tenemos problema porque no hay ningún otro proceso en la cola NEW. Pero al seguir la misma lógica con el proceso que sigue, si tenemos un proceso en cola NEW, el mismo queda encolado.
Cuando se inicializaría ese proceso al quedar encolado en new? Inmediatamente independientemente al estar encolado?  o tiene que estar la cola de new vacia? Si es ese ultimo el caso, como seria? los procesos que se crean en new y se inicializan, los movemos a otra cola entre new y exit? o los procesos se inicializan en new, y cuando esta cola esta vacía, se inicializa el hilo y encola en ready si es que hay espacio en memoria.

### 📔 Citas del enunciado/videos

Se tendrá una cola NEW que será administrada estrictamente por FIFO para la creación de procesos. 
Al llegar un nuevo proceso a esta cola y la misma esté vacía se enviará un pedido a Memoria para inicializar el mismo, si la respuesta es positiva se crea el TID 0 de ese proceso y se lo pasa al estado READY y se sigue la misma lógica con el proceso que sigue. Si la respuesta es negativa (ya que la Memoria no tiene espacio suficiente para inicializarlo) se deberá esperar la finalización de otro proceso para volver a intentar inicializarlo.
Al llegar un proceso a esta cola, si ya hay otros esperando, el mismo simplemente se encola.

### 💭 Soluciones posibles
Comparto como iniciamos el proceso actualmente

	func iniciarProceso(path string, size int, prioridad int) error {
		pcb := createPCB()
		if consultaEspacioAMemoria(size, pcb) {

			nextTid = 0
			tcb := createTCB(pcb.Pid, prioridad) // creamos hilo main
			pcb.Tid = append(pcb.Tid, tcb.Tid)   // agregamos el hilo a la listas de hilos del proceso
			enviarTCBMemoria(tcb, path)

			encolarProcesoNew(pcb)

			encolarReady(tcb)

		} else {

			slog.Warn("El tamanio del proceso es mas grande que la memoria, esperando a que finalice otro proceso ....")
			// esperar a que finalize otro proceso y volver a consultar por el espacio en memoria para inicializarlo
			nextPid-- // decrementamos el pid para que el proximo proceso tenga el pid correcto

			<-finProceso // se bloquea hasta que finalice un proceso
			iniciarProceso(path, size, prioridad) \
		}	
	
		return nil
	}

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Si recordas la definición de una cola como la explican en algoritmos, es que el primero que entra es el primero que sale, por lo tanto, si tenemos algun proceso en NEW que no se pudo inicializar completamente por no poder entrar en la memoria, los que vengan atras van a quedarse ahi, esperando en NEW hasta que ese primero puedan inicializarlo completamente y una vez hecho eso, seguiran inicializando hasta que alguno no se pueda inicializar o quede vacía la cola de new.

Saludos.-
