### ISSUE TITLE
Finalizar hilo

### ISSUE THREAD

**Issue by JuanTerri** [sisoputnfrba/foro#4298]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

No termino de entender si esos hilos que creamos son realmente hilos, por ahora lo estamos tratando como procesos con una estructura distinta (los cuales tienen un proceso asociado, tal como si fueran hilos), esa accion de finalizar hilo seria como un finalizar proceso? (entendiendo que se finalizaria un hilo de X proceso). Nose si mi duda es suficientemente clara, lo principal es que estamos tratando esos hilos de procesos como si fueran procesos

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Acordate que en **este TP** los hilos no reservan memoria, por lo tanto si los tratan como procesos estamos en un problema porque estan reservando memoria de mas.

Lo que uds crean con el THREAD_CREATE es un hilo que tiene su TCB y pertenece a un proceso.

Saludos.-

**Comment by JuanTerri** [comment]
Perfecto, gracias.

**Comment by JuanTerri** [comment]
Buenas, vuelvo a preguntar sobre los hilos despues de investigar por internet, ¿Tenemos que usar la struct que viene con hilos "pthread_attr_t"?  Yo entendia que usariamos una Struct llamada TCB, por ejemplo cuando creamos el hilo, pasamos una funcion que seria setear_valores (TID, PRIORIDAD,PID (proceso asociado)), de esta forma el hilo tendria su propia TCB y a la hora de crearse se pondrian los valores.
Otra forma que pense es que cada proceso tenga dentro esa lista de TIDs pero q en realidad sea una lista de TCBs, donde para
el de la posicion 0, seria el que tenga TID 0 y todos los demas datos, posicion 1, TID 1 y asi con todos los hilos que cree.

**Comment by LeandroCarbajales** [comment]
Buenas!

> Buenas, vuelvo a preguntar sobre los hilos despues de investigar por internet, ¿Tenemos que usar la struct que viene con hilos "pthread_attr_t"? 

Usarías eso si quisieras ver la información de los hilos "reales" (de la biblioteca pthread).

La representación de hilos que el módulo kernel planifica la administran con sus propias estructuras como bien decís acá:

> Yo entendia que usariamos una Struct llamada TCB, por ejemplo cuando creamos el hilo, pasamos una funcion que seria setear_valores (TID, PRIORIDAD,PID (proceso asociado)), de esta forma el hilo tendria su propia TCB y a la hora de crearse se pondrian los valores.

Luego, esto que pensaron también es una implementación válida para ese fin :)

> Otra forma que pense es que cada proceso tenga dentro esa lista de TIDs pero q en realidad sea una lista de TCBs, donde para
> el de la posicion 0, seria el que tenga TID 0 y todos los demas datos, posicion 1, TID 1 y asi con todos los hilos que cree.

Te aclara la duda?
Saludos!
     Lean

**Comment by JuanTerri** [comment]
Me aclara la duda, muchas gracias.

**Comment by JuanTerri** [comment]
Buenas, vuelvo con ciertas dudas que me surgieron.
Tengo un proceso que crea 3 hilos, el hilo main ya fue creado anteriormente, con su TID 0, prioridad 0 y PID del proceso asociado, Los siguientes 3 hilos se crean correctamente, la creacion de los hilos la hago de esta forma, se le pasa una funcion a pthread_create, esta funcion crea un TCB, que asigna un TID, prioridad y el PID del proceso asociado, estos TCBs creados se van metiendo en la lista de TCBs que tengo en el PCB; Osea yo tengo 4 hilos del TID 0, 1, 2 y 3. Ahora a mi me surge la duda de como voy a hacer para que ejecute cierto hilo. Si yo quiero que ejecute el hilo del TID 2, yo se que en la lista de TCBs del proceso va a ser el que esta en 3ra posicion, pero a la hora de  ejecutar ese hilo que es TID 2 no se como hacerlo.
Los hilos pueden tener Struct? osea que tengan estos TCB q nosotros creamos asi podriamos identificar su TID.
Mi duda principal recae en como hago que ejecute cierto hilo de tal proceso.

**Comment by LeandroCarbajales** [comment]
Buenas!
Mi primera duda es cual es el propósito de hacer un pthread_create por cada hilo que quieren crear?

Luego, a efectos del trabajo, para que "ejecute" un hilo es suficiente con enviarle el PID y TID al módulo CPU para que éste comience su trabajo. Al mismo tiempo del lado del Kernel también podrían tenerlo diferenciado como que está en estado "exec" y esperar hasta que CPU responda por alguno de los motivos dispuestos en el enunciado del mismo.

**Comment by JuanTerri** [comment]
Lo de pthread_create era mas por la idea de usar crear literalmente un hilo, ahora por lo que entiendo no es necesario sino que ¿lo que se crearia un TCB?
Me queda mas claro la forma de ejecutar y lo de pasarlo a un estado "exec" era la idea desde un principio, esta bueno saber que eso esta bien.

**Comment by LeandroCarbajales** [comment]
De la misma forma que no crean un proceso real por cada "proceso" del trabajo, tampoco es necesario crear un hilo real por cada "hilo" del trabajo :)
Creen la estructura administrativa que ustedes crean necesaria, el "TCB" definido en el enunciado es lo mínimo para tener la info relevante, pero pueden extenderla como gusten.

**Comment by JuanTerri** [comment]
Perfecto ahora si me quedo mucho mas claro, me habia hecho un quilombo pensando que tenian que ser realmente hilos.
Gracias
