### ISSUE TITLE
Cola/Listas de procesos/hilos

### ISSUE THREAD

**Issue by JuanTerri** [sisoputnfrba/foro#4299]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Estoy realizando el planificador FIFO, Nosotros teníamos ciertas listas por ejemplo list_ready, pero ahi guardábamos procesos (PCB), deberiamos guardar hilos (TCB)? 

### 📔 Citas del enunciado/videos

"Se elegirá al siguiente hilo a ejecutar según su orden de llegada a READY."

### 💭 Soluciones posibles

Lo primero que se me ocurrio es como dije arriba guardar los hilos en las listas que estabamos usando, si en algun momento tendremos que llegar a matar un proceso con la lista de tids que tiene en el PCB podriamos matar a toda esa especie de hilos

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by JuanTerri** [comment]
Perfecto, gracias.

**Comment by tomyleca** [comment]
Buenass, aprovecho el issue para preguntar porque esta relacionado. Una vez que un proceso se inicializo solo se planifican los hilos, no? Osea que el proceso que esta en ejecucion depende de que hilo haya elegido el planificador a corto plazo y no hay ningun planificador que se encargue de los procesos. Me queda la duda porque en la teoría se ve la planificación a corto plazo más que nada con procesos.

**Comment by iago64** [comment]
@tomyleca Si tenes alguna duda, crea un issue nuevo y hace referencia a este issue.
