### ISSUE TITLE
Naturaleza de la syscall PROCESS_CREATE

### ISSUE THREAD

**Issue by GabrielBorre** [sisoputnfrba/foro#4300]
### 🖋️ Descripción

¡Buenas tardes! ¿Cómo están? Tengo una duda con respecto a la naturaleza de la syscall PROCESS_CREATE

Por lo que infiero del enunciado, entiendo que cuando un hilo hace la syscall PROCESS_CREATE,  el kernel atiende la solicitud creando un proceso y , una vez realizado esto, devuelve a CPU el hilo que solicitó dicha syscall. 

Sin embargo, durante el tiempo que el kernel está atendiendo la syscall, la CPU no ejecutaría las instrucciones de ningún hilo, por lo que estaríamos penalizando su uso.

La pregunta es: ¿no sería más conveniente mandar a ejecutar a CPU otro hilo, mientras el kernel atiende la syscall y además manda a la cola de Ready al hilo que realizó la syscall PROCESS_CREATE ?

Desde ya, muchas gracias ! (le erré a a la etiqueta, pero no me deja cambiarla, perdón!)

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by f-and** [comment]
Buenas!

No se si sería más conveniente, considerando que puede generar desorden en la planificación si hay un orden predilecto (algo que se hace en varias pruebas), lo que si sería es más eficiente, pero no es algo que apuntemos con el TP, considerando que para este, a diferencia de la vida real, ***no hay retraso en la conexión con memoria***, esta eficiencia ganada por enviar otros hilos a ejecutar sería minúscula en comparación. 

Lo mismo para otras syscalls, como THREAD_CREATE y MUTEX_CREATE, van a desalojar el proceso, pero no requieren una replanificación y no demorarian demasiado para beneficiar el forzar a replanificar constantemente.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Agrego algunos detalles no menores:

Relacionando el diseño del trabajo con la realidad, piensen que en un sistema/hardware real lo que sea que haga el Kernel para atender esa syscall estaría ejecutando en la misma CPU que el proceso acaba de cambiar de contexto, por lo que no habría posibilidad de poner a ejecutar otro hilo al mismo tiempo.

Por eso, desde el punto de vista del TP lo que plantean no cumpliría con el enunciado (y por lo tanto con las pruebas) del módulo Kernel ya que esas syscalls no conllevan necesariamente una replanificación o un cambio de estado del hilo en ejecución.

Queda más clara la duda?
Saludos!
     Lean

**Comment by GabrielBorre** [comment]
¡Buenas tardes @f-and y Lean @LeandroCarbajales ! Muchísimas gracias a ambos por su respuestas. Quedaron súper clarificadas mis dudas gracias a ellas. 
Muchas gracias por la paciencia y el tiempo y disculpen que no pude responder antes para cerrar el issue: me llegó la notificación de la respuesta en la facu y recién llego a mi casa.

Nuevamente, muchas gracias a ambos! Que tengan una buena semana. Cierro el issue
