### ISSUE TITLE
Duda planificacion procesos

### ISSUE THREAD

**Issue by tomyleca** [sisoputnfrba/foro#4302]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas, tengo una duda respecto a la planificacion de procesos. Una vez que un proceso se inicializo solo se planifican los hilos, no? Osea que el proceso que esta en ejecucion depende de que hilo haya elegido el planificador a corto plazo y, en este punto, no hay ningun planificador que se encargue de los procesos. Me queda la duda porque en la teoría se ve la planificación a corto plazo más que nada con procesos.

relacionado a #4299

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Si, en el TP van a planificar los hilos.

En los ejercicios de la teoría tambien se planifican hilos, solo que los ven como KLT (Kernel Level Threads).

Saludos.-

**Comment by tomyleca** [comment]
Ok, gracias!!
