### ISSUE TITLE
Duda starvation en planificador de colas multinivel

### ISSUE THREAD

**Issue by RodrigoSarmiento** [sisoputnfrba/foro#4303]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Hola que tal,

Con nuestro grupo encontramos que el algoritmo de colas multinivel puede que sufra starvation, no tenemos en claro si deberíamos tomar medidas para evitarlo y cómo podríamos hacerlo. Esta pregunta viene debido a que por lo que entendemos, el algoritmo de prioridades podría quedarse ejecutando las colas de prioridades más altas, inclusive evitando ejecutar la última cola que ejecutó.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by LeandroCarbajales** [comment]
Es correcto :)
El algoritmo como está planteado puede causar starvation si siempre hay algo para ejecutar en las colas más prioritarias, es el comportamiento esperado y no tienen que evitarlo.

Saludos!
       Lean

**Comment by SantiagoDopazo** [comment]
Hola buenas, La duda quedo resuelta? Si es así no olviden cerrar el issue.
Cierro el Issue pero si quedo alguna duda vuelvan a abrirlo sin ningun problema.

**Comment by SantiagoDopazo** [comment]
Hola buenas, La duda quedo resuelta? Si es así no olviden cerrar el issue.
Cierro el Issue pero si quedo alguna duda vuelvan a abrirlo sin ningun problema.

**Comment by SantiagoDopazo** [comment]
Hola buenas, La duda quedo resuelta? Si es así no olviden cerrar el issue.
@RodrigoSarmiento.

**Comment by SantiagoDopazo** [comment]
Cerramos el issue por inactividad, cualquier duda vuelvan a comunicarse.
