### ISSUE TITLE
Planificacion de procesos e hilos

### ISSUE THREAD

**Issue by matibapti** [sisoputnfrba/foro#4304]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Entiendo que el planificador a largo plazo se realiza para los procesos, es decir a medida que llegan procesos estos se ubican en la cola new(administrada por FIFO), ahora bien cuando memoria permite inicializar un proceso se crea el TID0 correspondiente a dicho proceso, en este punto es el proceso como tal el que pasa a la cola ready o es el TID0 el que pasa a ready, adjunto la parte del enunciado que genero esta duda.

![image](https://github.com/user-attachments/assets/97d9039f-c7cd-40c2-974b-49fa86338e53)

Bajo esta duda en nuestro grupo surgieron distintos puntos de vista sobre como encarar esta parte, paso a explicarlos.

La primera idea era que los procesos pasaban de new a ready, y recien cuando nos poniamos a ejecutar un proceso comenzaba la planificacion de los hilos que se creen dentro de ese proceso. Creiamos que teniamos que comenzar con un proceso, planificar los hilos de este y una vez que finalice el proceso pasamos al siguiente. No pudimos encontrar en el enunciado algo referente a que el proceso pueda estar suspendido, y por ende pasar a otro proceso que se encontraba en ready y comenzar la planificacion de sus respectivos hilos.

Bajo este punto surgio la otra forma de verlo, donde  los procesos llegarian a new si se pudieran inicializar un proceso en cola el que pasa a ready en si seria el hilo TID0 y los que se puedan crear a futuro (y no los procesos como tal), en este caso deberiamos planificar todos los hilos (creados por los distintos procesos ya inicializados) en conjunto???.

### 💭 Soluciones posibles

Si la respuesta fuese la ultima opcion, pensamos agregar dentro de la estructura de hilos un identificador que nos indique cual es el proceso al que esta asociado ese hilo, para que cuando tenga que finalizar un proceso pueda finalizar los hilos asociados a este.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by LeandroCarbajales** [comment]
Buenas!
El comportamiento esperado es la última opción, en este TP el planificador de corto plazo únicamente planifica hilos independientemente de a qué proceso pertenecen. Por lo tanto, una vez inicializado un proceso y su TID 0, este último se coloca en ready, quedando el proceso como una estructura que los relaciona dados sus recursos compartidos (mutex, memoria, etc).

> Si la respuesta fuese la ultima opcion, pensamos agregar dentro de la estructura de hilos un identificador que nos indique cual es el proceso al que esta asociado ese hilo, para que cuando tenga que finalizar un proceso pueda finalizar los hilos asociados a este.

Ya tienen la lista de TCBs asociados a un proceso en el PCB, pero pueden agregar también el reverso (tener el PID dentro del TCB) si les facilita el trabajo :)

Les aclara las dudas?
Saludos!
     Lean

**Comment by matibapti** [comment]
Perfecto me sirvio mucho la respuesta, desde ya muchas gracias.

Respecto a esto;
![image](https://github.com/user-attachments/assets/d4febfc6-a455-46b6-9e22-4ff4f16fcfc8)

Entiendo que al inicializar un proceso el primer TID sera 0 y este va incrementando a medida que creo nuevos hilos, por lo que podria tener varios procesos por ejemplo con una lista de TIDs [0, 1, 2, 3], por eso me parecio agregar ese PID dentro de los hilos. Lo cual nose si es correcto o hay algo que estoy malinterpretando.

**Comment by LeandroCarbajales** [comment]
Es correcto!
Como les decía, pueden agregar ese campo (u otros) si les facilita el trabajo, el enunciado solamente les da lo que consideramos es lo mínimo indispensable. Otra forma que se me ocurre es que en el PCB en lugar de tener los TIDs tengan directamente punteros a TCBs, de esa forma podrían recorrer esa lista y finalizarlos.
