### ISSUE TITLE
Duda sobre Syscalls

### ISSUE THREAD

**Issue by AgustinHerzkovich** [sisoputnfrba/foro#4306]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

Hola buenas, mi pregunta es :
Todas las syscalls son bloqueantes? La duda surge porque no sabríamos si un hilo al ejecutar MUTEX_LOCK debería bloquearse luego de que se le asigne, lo cual no nos hace sentido.
Muchas gracias, saludos.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

No, el comportamiento de las syscalls están detalladas para cada una, por ejemplo, en el caso del MUTEX_LOCK solo se va a bloquear si el mutex se encuentra tomado por otro hilo.
Un ejemplo que nunca va a bloquear por ejemplo es el de MUTEX_UNLOCK, ahi simplemente liberas el mutex que tenía tomado el hilo.
Otro ejemplo es el caso del DUMP_MEMORY que ahí siempre se va a bloquear el hilo.

Saludos.-

**Comment by AgustinHerzkovich** [comment]
Muchas gracias.
