### ISSUE TITLE
que se hace con los procesos que hacen segmentation fault

### ISSUE THREAD

**Issue by nicolasvultaggio** [sisoputnfrba/foro#4307]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

los procesos que hacen segmentation fault debemos finalizarlos? como si se hiciese thread cancel por ejemplo
pregunto porque en el modulo de kernel no dice que hacer cuando el motivo de desalojo es por segmentation fault

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by SantiagoDopazo** [comment]
Hola Buenas, 
Si alguno de los hilos de un proceso llegara a tener un problema de segmentation fault tendrías que finalizar todo el proceso ya que su manejo de memoria dejo de ser consistente. La función mas adecuada en este caso sería realizar un exit del proceso completo teniendo en cuenta la diferencia entre un PROCESS EXIT exitoso porque finalizo sin problemas a uno que termino por algún problema concreto, ya que un thread_cancel solo afecta a un hilo individual y no resuelve el problema de memoria del proceso.

Te dejo un issue anterior que hablan del tema: https://github.com/sisoputnfrba/foro/issues/4264

Saludos y cualquier cosa volve a preguntar.

**Comment by nicolasvultaggio** [comment]
perfecto! muchas gracias!
