### ISSUE TITLE
Duda con creacion de procesos (kernel)

### ISSUE THREAD

**Issue by Elias318** [sisoputnfrba/foro#4308]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas, tengo una duda sobre el enunciado en el modulo de kernel:

![image](https://github.com/user-attachments/assets/5036f1e5-e40e-4381-9276-5294d827e804)
Por un lado el enunciado dice que tengo que crear el TID y dejarlo en NEW al proceso.

![image](https://github.com/user-attachments/assets/b90ec7b0-11c8-400f-8694-493b9a3a281b)
Por otro lado me dice que tengo que asignarle el TID cuando reciba la respuesta de memoria de que le encotro espacion para asignarle. 

Entonces no termino de entender si hay que asignar el TID antes o despues de la respuesta de memoria.
Saludos!

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by RaniAgus** [comment]
¡Buenas! No hay ninguna diferencia entre un escenario y el otro: siempre el primer hilo del proceso va a tener TID 0 al momento de crearse.

Lo que se especifica en el apartado de "creación de procesos" es que se debe crear el contexto de ejecución del TID 0. O sea, se debe hacer una solicitud a Memoria para crear dicho hilo, una vez se haya podido crear el proceso exitosamente.

Saludos

**Comment by Elias318** [comment]
Ahhh perfecto. Osea que cada hilo tambien va a tener un contexto de ejec como el PCB ?

**Comment by iago64** [comment]
Buenas! Cómo va?

Si, de hecho el contexto de ejecución es de los hilos, los PCB y TCB en este TP solo tienen un par de valores que le permiten al kernel planificarlos sin tener que ir a la memoria.

Saludos.-

**Comment by Elias318** [comment]
Perfecto, muchas gracias!

**Comment by Elias318** [comment]
Buenas me surgio otra duda relacionado a esto y por eso vuelvo a abrir el issue. 
Estoy entre usar colas o listas para manejar los hilos por que con colas entiendo que siempre va a agarrar el primer elemento de la misma y capaz justo ese hilo que estaba primero pertenece a otro proceso.
En cambio en la lista buscaria al hilo por su tid o todos los Tcbs que tengan un determinado pid segun que procesos se ponga en ready .
Estoy errado o puede ir por ahi ?

**Comment by iago64** [comment]
Buenas! Cómo va?

Pueden usar cualquier estructura, idealmente traten de elegir la que mas facil les resulte de manejar, despues, por otro lado, ¿Qué problema tendrías con planificar hilos de diferentes procesos? Justamente la idea va a ser que se mezclen los hilos de los procesos durante la ejecución.

Saludos.-

**Comment by SantiagoDopazo** [comment]
Hola Buenas!

@Elias318  La duda quedo resuelta? algo mas en lo que podamos ayudar del tema?

Saludos.
