### ISSUE TITLE
Uso de ColasReady para Hilo y Funcionamiento de los modulos en Cliente/Server

### ISSUE THREAD

**Issue by Marco-Maggio** [sisoputnfrba/foro#4309]
### 🛠️ Lenguaje

Golang

### 🖋️ Descripción

Buenas, como estan?

Teniamos 2 puntos a consultar.

1) **Cola de Hilos en Ready, como definirla?**

Nos surgio una nueva duda con el uso de colasReady para Procesos/Hilos. Nosotros armamos todas las colas de Proceso separadas con una cola para cada nivel de prioridad.

Ahora cuando comenzamos a armar el planificador de Corto Plazo notamos que el FIFO no podria recorrer correctamente esas colas previamente mencionadas, que necesitamos una general donde se vayan encolando tipo "Pila". 
Nuestra pregunta es, deberiamos tener colas para separar por prioridad y tambien una general donde esten todos?

2)  **Funcionamiento de Modo Cliente/Servidor en Simultaneo para cada Modulo**

Cada modulo (Kernel, CPU, memoria, etc) trabaja por momentos en modo servidor y por otros momentos en modo cliente. Es correcto tener 2 archivos .go por módulo (Uno para cada caso) o hay alguna forma de que mientras escucha en un puerto continua ejecutando sus procesos internos cada modulo?

### 📔 Citas del enunciado/videos

En primer lugar el enunciado te pide esto:

"**Creación de hilos**
Para la creación de hilos, el Kernel deberá informar a la Memoria y luego ingresarlo directamente a la cola de READY correspondiente, según su nivel de prioridad."

Luego, para poder Aplicar FIFO; Tenemos dudas en como generar esa Cola:

"**Planificador de Corto Plazo**
Los hilos que estén en estado READY serán planificados mediante uno de los siguientes algoritmos:

- FIFO
- Prioridades
- Colas multinivel

**FIFO**
Se elegirá al siguiente hilo a ejecutar según su orden de llegada a READY.

**Prioridades**
Se elegirá al siguiente hilo a ejecutar según cual tenga el número de prioridad más bajo, siendo 0 la máxima prioridad. En caso de tener varios hilos con la máxima prioridad, se desempata por FIFO. Se pide implementar este esquema con desalojo de manera que si llega un hilo a la cola de READY con mayor prioridad que el hilo que está actualmente ejecutando, se deberá desalojar a este último."

### 💭 Soluciones posibles

Para el uso de Colas, nosotros generamos una colaReady para cada nivel de prioridad del hilo.
Ahora que nos piden utilizar FIFO necesitamos una cola general donde se acumulen por orden de llegada.

Nosotros pensabamos unificar todo en una cola, cuando se trate de FIFO usarlo recorriendola normalmente y para el uso por prioridad filtrando con el parametro "prioridad" que esta dentro del Struct del TCB.

Que opinan?

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by JeronimoAlo** [comment]
Buenas profe! desestimar la pregunta 1.

**🖋️ Descripción**
Tenemos una consulta más y es con respecto a las syscalls. Entendemos que para crear un Hilo dentro del sistema, además del pseudocódigo y su prioridad, necesitamos el PID o alguna referencia hacia su proceso padre. Esto debemos sumarlo cómo un parámetro a la syscall? o cómo recomiendan trabajarlo?

**📔 Citas del enunciado/videos**
En el enunciado dice:
_**"Las syscalls que puede atender el kernel referidas a threads son 4: THREAD_CREATE, THREAD_JOIN, THREAD_CANCEL y THREAD_EXIT.

THREAD_CREATE, esta syscall recibirá como parámetro de la CPU el nombre del archivo de pseudocódigo que deberá ejecutar el hilo a crear y su prioridad. Al momento de crear el nuevo hilo, deberá generar el nuevo TCB con un TID autoincremental y poner al mismo en el estado READY."**_

**📝 Normas del foro**
 Leí los lineamientos del foro

Gracias!!

**Comment by iago64** [comment]
Buenas! Cómo va?

Paso a responder citando porque va a ser mas facil:

> Cola de Hilos en Ready, como definirla?
> Nos surgio una nueva duda con el uso de colasReady para Procesos/Hilos. Nosotros armamos todas las colas de Proceso separadas con una cola para cada nivel de prioridad.
> Ahora cuando comenzamos a armar el planificador de Corto Plazo notamos que el FIFO no podria recorrer correctamente esas colas previamente mencionadas, que necesitamos una general donde se vayan encolando tipo "Pila".
> Nuestra pregunta es, deberiamos tener colas para separar por prioridad y tambien una general donde esten todos?

Pueden tener las estructuras que necesiten, en el TP hablamos de cola READY porque es como lo ven en la teoría, pero despues uds pueden rebuscarselas de las formas que quieran, de la misma manera que la cola de BLOCK, en la teoría ven el estado BLOCK, pero si quieren tener múltiples colas de acuerdo al motivo de bloqueo, pueden hacerlo.


> Funcionamiento de Modo Cliente/Servidor en Simultaneo para cada Modulo
> Cada modulo (Kernel, CPU, memoria, etc) trabaja por momentos en modo servidor y por otros momentos en modo cliente. Es correcto tener 2 archivos .go por módulo (Uno para cada caso) o hay alguna forma de que mientras escucha en un puerto continua ejecutando sus procesos internos cada modulo?

Esto es algo que venimos comentandole a los grupos que suelen pasar por soporte que son de Go, traten de no pensar el TP en terminos de cliente y servidor, ya que eso es mas del funcionamiento en C, mientras que en Go, uds van a manejar APIs con protocolo HTTP, entonces, ahi tienen la libertad de definirse los endpoints de la forma que mas comoda les queden, siendo que pueden tener 1 archivo con las definiciones de los endpoints y nada mas y en otros N archivos distribuir la lógica de lo que hace cada endpoint.

> Tenemos una consulta más y es con respecto a las syscalls. Entendemos que para crear un Hilo dentro del sistema, además del pseudocódigo y su prioridad, necesitamos el PID o alguna referencia hacia su proceso padre. Esto debemos sumarlo cómo un parámetro a la syscall? o cómo recomiendan trabajarlo?

Aca tienen bastantes libertades, una forma que se me ocurre pensando un poco el contexto del problema, es que, como en el TP tienen 1 sola CPU y por ende 1 solo hilo en EXEC, pueden guardarse también a que proceso pertenece ese hilo y entonces ya saben que pueden crearle el hilo a ese proceso, otra forma es como planteas, que es mandar en la petición de la syscall el PID, como dije, tienen libertad de resolver el problema como lo crean conveniente y por sobre todo, que les resulte mas facil.

Saludos.-

**Comment by iago64** [comment]
@Marco-Maggio @JeronimoAlo Cómo va? Se entendió la respuesta? Necesitan que veamos algun punto mas en detalle o desde otra perspectiva?

**Comment by JeronimoAlo** [comment]
Profe buenas noches cómo estás? Clarísimo todo. Tenemos solo una duda más con respecto a esta respuesta: 

"Esto es algo que venimos comentandole a los grupos que suelen pasar por soporte que son de Go, traten de no pensar el TP en terminos de cliente y servidor, ya que eso es mas del funcionamiento en C, mientras que en Go, uds van a manejar APIs con protocolo HTTP, entonces, ahi tienen la libertad de definirse los endpoints de la forma que mas comoda les queden, siendo que pueden tener 1 archivo con las definiciones de los endpoints y nada mas y en otros N archivos distribuir la lógica de lo que hace cada endpoint." A que llaman endpoint? a los handler? te pregunto esto porque es nuestra primera vez trabajando con APIs y algunos términos los desconocemos.

**Comment by RaniAgus** [comment]
¡Buenas! Un [API Endpoint](https://blog.postman.com/what-is-an-api-endpoint/) es la URL a través de la cual el cliente se comunica con el servidor. Los _handlers_ son las funciones que definen desde el lado del servidor para _manejar_ las solicitudes a ese endpoint. Saludos

**Comment by JeronimoAlo** [comment]
Clarísimo, gracias!

**Comment by SantiagoDopazo** [comment]
Hola buenas, La duda quedo resuelta? Si es así no olviden cerrar el issue.
@Marco-Maggio , @JeronimoAlo.
