### ISSUE TITLE
Campos de PCB y contenido de memoria

### ISSUE THREAD

**Issue by inaaranza** [sisoputnfrba/foro#4310]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas! Queria hacer unas consultas chiquitas sobre la memoria en general.

Por un lado quiero saber si es válido ponerle al PCB unos campos de base y tamaño (o limite) y que los valores de estos campos los setee la memoria. Entonces, cuando se necesita crear un proceso, el kernel le manda a la memoria, y la memoria al cargarlo dentro de la misma le setea los valores de estos campos.
Por otro lado queria preguntar si las estructuras de PCB y TCB se guardan en lo que es la memoria (el void* que representa a la memoria) o si se guardan los valores y todo solamente en sus structs correspondientes. En el caso que no se guarden en el void* que representa, ¿solamente se va a guardar en memoria las cosas que se escriban al hacer un WRITE__MEM?
Muchas gracias!!

**Comment by f-and** [comment]
Buenas!

Lo primero y principal es: El PCB y TCB, para lo que concerne el TP, se guardan en el Kernel, esto es distinto de la realidad, pero se hace para facilitarles la simulación de procesos. Por lo que casi todo lo que voy a decir importa para el Kernel.

Yendo una por una:

1. Al PCB y TCB se le pueden agregar los campos que crean necesarios usar. Lo que sí, los campos de base y limite ***ya se encuentran en el contexto de ejecución de cada hilo***, y no es algo necesario para el total del proceso, por lo que a lo mejor les resulta redundante hacer uno para el PCB. 

2. a. Como el PCB y el TCB se manejan en el Kernel, se almacenan directamente en el struct. 
b. Sí, efectivamente, el espacio de usuario solo maneja las instrucciones de WRITE_MEM, READ_MEM, y DUMP_MEMORY. Todo lo demás se maneja en el espacio de sistema (lease en structs), por lo que los contextos de ejecución, y los archivos de pseudocódigo se guardan en estructuras definidas por el equipo.

Espero haber contestado todo, si algo no quedó claro no dudes en repreguntar.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Me tomo el atrevimiento de hacer una aclaración con esta parte de la respuesta de @f-and :

> " Lo que sí, los campos de base y limite ya se encuentran en el contexto de ejecución de cada hilo, y no es algo necesario para el total del proceso, por lo que a lo mejor les resulta redundante hacer uno para el PCB. "

La base y el límite serían el mismo para todos los hilos de un mismo proceso ya que comparten el espacio que asigna la memoria, por lo que, como está especificado en el enunciado del módulo memoria, pueden tomarlos como campos asociados al PID en lugar de a cada TID.

**Comment by inaaranza** [comment]
Perfecto! Me quedó todo clarisimo!
Muchas gracias :)
