### ISSUE TITLE
Duda MUTEX_CREATE, MUTEX_LOCK, MUTEX_UNLOCK

### ISSUE THREAD

**Issue by Martlar1502** [sisoputnfrba/foro#4311]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

Buenas tardes, 

En los MUTEX_CREATE, MUTEX_LOCK, MUTEX_UNLOCK, tenemos que usar sync.Mutex/ Canales ('chan') que estan en la guia de GO?
Si es así, como podríamos conseguir el valor en el que este el mutex para saber si tenemos que bloquear el hilo?
No encontramos una funcion que te indique dicho valor.

Desde ya gracias,
Saludos

### 📔 Citas del enunciado/videos

>MUTEX_CREATE, crea un nuevo mutex para el proceso sin asignar a ningún hilo.
MUTEX_LOCK, se deberá verificar primero que exista el mutex solicitado y en caso de que exista y el mismo no se encuentre tomado se deberá asignar dicho mutex al hilo correspondiente. En caso de que el mutex se encuentre tomado, el hilo que realizó MUTEX_LOCK se bloqueará en la cola de bloqueados correspondiente a dicho mutex.
MUTEX_UNLOCK, se deberá verificar primero que exista el mutex solicitado y esté tomado por el hilo que realizó la syscall. En caso de que corresponda, se deberá desbloquear al primer hilo de la cola de bloqueados de ese mutex y le asignará el mutex al hilo recién desbloqueado. Una vez hecho esto, se devuelve la ejecución al hilo que realizó la syscall MUTEX_UNLOCK. En caso de que el hilo que realiza la syscall no tenga asignado el mutex, no realizará ningún desbloqueo.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by RaniAgus** [comment]
¡Buenas! No, en el enunciado no se especifica ninguna implementación en particular con mutex reales. De hecho, usar una goroutine por hilo y `sync.Mutex` para implementarlo puede que no sea lo más sencillo. Saludos

**Comment by iago64** [comment]
Buenas! @Martlar1502 Te sirvió la respuesta de Agus? Queda algo mas con lo que te podamos ayudar?

Saludos.-s

**Comment by SantiagoDopazo** [comment]
Hola @Martlar1502 , cierro el issue por inactividad pero si quedo alguna duda respecto al tema no dudes en abrirlo de nuevo.

**Comment by Elias318** [comment]
Buenas, tengo la misma consulta que el compañero pero en C por que no se como saber si el mutex esta "tomado" o no
