### ISSUE TITLE
Herencia de prioridades

### ISSUE THREAD

**Issue by AgustinHerzkovich** [sisoputnfrba/foro#4312]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

Hola buenas, en el caso en que un hilo de menor prioridad tenga un recurso mutex, y luego venga otro más prioritario que pida ese mismo recurso y se bloquee, el hilo que tiene el recurso debe heredar la prioridad del otro? Es decir, se debe implementar herencia de prioridades?
Muchas gracias, saludos.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by RaniAgus** [comment]
¡Buenas! En este TP, la prioridad de un hilo es siempre la misma a lo largo de su ejecución. Saludos

**Comment by AgustinHerzkovich** [comment]
Muchas gracias, saludos.
