### ISSUE TITLE
Bloqueo de mutex

### ISSUE THREAD

**Issue by AgustinHerzkovich** [sisoputnfrba/foro#4313]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

Hola buenas, en caso de que un hilo tenga asignado un mutex, y este finalice antes de liberarlo, el mismo se libera automáticamente?
Muchas gracias, saludos.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by LeandroCarbajales** [comment]
Buenas!
Correcto, debería liberar sus mutex, desbloqueando a los hilos que corresponda que estén esperando por ellos como está aclarado en la sección de finalización de hilos en Kernel.
Cabe destacar, que este comportamiento no necesariamente se condice con la realidad, muchas implementaciones de mutex simplemente quedan bloqueados indefinidamente tras la muerte repentina de un hilo que no liberó sus mutex previamente.

Saludos!
     Lean

**Comment by AgustinHerzkovich** [comment]
Perfecto, muchas gracias, aprovecho para hacer otra pregunta:
Supongamos que un hilo 0 tiene asignado un mutex, luego viene un hilo 1 y pide ese mismo mutex, entonces se bloquea porque no está disponible, si luego de esto el hilo 0 hace THREAD_JOIN del hilo 1, se generaría un deadlock. Este y otros casos más donde se genere deadlock, hay que tenerlos en cuenta para que no sucedan o simplemente lo dejamos estar?

**Comment by LeandroCarbajales** [comment]
Para esos casos, el comportamiento esperado es que queden en deadlock, no tienen que implementar ninguna estrategia para tratarlo :)

**Comment by AgustinHerzkovich** [comment]
Muchas gracias por las respuestas, saludos.
