### ISSUE TITLE
Duda algoritmo de planificacion + Tids y Pids

### ISSUE THREAD

**Issue by tomyleca** [sisoputnfrba/foro#4314]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenass. Tenemos dos consultas con respecto al modulo kernel:
1-Para el planificador a corto plazo estabamos pensando en crear la estructura donde se van a guardar los hilos en ready según el algoritmo que viene por archivo de configuración. Ahora, para hacer esto sería necesario que este no cambie en toda la ejecución del programa ¿Esto es asi no?
2-Con respecto a los PIDs y TIDs. Se especifica que el identificador debe ser un numero único en todo el sistema. ¿Con esto se refiere a que no debe ser compartido con ningun otro de su mismo tipo?(Osea que por ej. dos procesos no tengan el mismo PID) ¿O a que ninguna otra variable del sistema puede usar ese numero? En caso de ser la primera, si un proceso o hilo se finaliza, ¿Es un requisito que ese número liberado pueda ser utilizado por otro de su mismo tipo? ¿O con que dos procesos o hilos no compartan número alcanza?

### 📔 Citas del enunciado/videos

2-"PID: Identificador del proceso (deberá ser un número entero, único en todo el sistema)."
"TIDs: Lista de los identificadores de los hilos asociados al proceso (deberá ser un número entero, autoincremental dentro del mismo proceso, siendo el primer hilo del proceso el TID 0)."

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by SantiagoDopazo** [comment]
Hola Buenas !

Te respondo las dudas:

1. Es correcto lo que decís, el algoritmo de planificación no va a cambiar durante la ejecución del sistema. Una vez que se carga desde el archivo de configuración, el planificador va a seguir utilizando ese algoritmo durante toda la ejecución.

2. Lo primero que planteás es correcto: el PID (Identificador del Proceso) es único entre todos los procesos, y los TID (Identificadores de los Hilos) son únicos dentro de cada proceso. No hay restricciones que impidan que un PID coincida con un TID de un hilo en un proceso distinto, ya que estos identificadores se manejan en contextos separados.

En cuanto a la reutilización de identificadores, no te lo recomendaría, ya que es complicarsela. Lo más sencillo y seguro es que los números de PID sean únicos durante la vida del sistema, y los números de TID únicos dentro de cada proceso. Si se les complica, pueden pensar en el PID como un número autoincremental, así se aseguran de que nunca se repita.

**Comment by tomyleca** [comment]
Perfecto, todo claro. Gracias!!
