### ISSUE TITLE
Consulta release de pruebas para el check 2/ algoritmos de planificación

### ISSUE THREAD

**Issue by MartinSintas** [sisoputnfrba/foro#4315]
### 🖋️ Descripción

Buenas, que tal; con el grupo queríamos saber si durante estos días se iba a subir un archivo de pruebas para probar el funcionamiento deseado de los algoritmos de planificación. Si bien los podemos probar por nuestra cuenta; nos gustaría contar con un documento de pruebas oficial :D 

Desde ya muchas gracias.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Estamos trabajando en eso, pero para evitar que alguien sienta una presion innecesaria, los primeros scripts los vamos a liberar despues del parcial.
De todas formas si tienen algo armado y quieren validarlo lo podemos ver.

Saludos.-
