### ISSUE TITLE
Canal booleano no recibe "true" (wait no recibe signal)

### ISSUE THREAD

**Issue by Bru-Nicolas-FRBA** [sisoputnfrba/foro#4316]
### 🖋️ Descripción

Hola, en el modulo kernel/globals tenemos definida
```go
Sem_b_plani_corto  = make(chan bool, 1)
``` 

En kernel/api tenemos
```go
func Peticion_a_memoria_para_finalizar_hilo() {
	tcb_finalizado := <-globals.Sem_tcb_finalizar_hilo
	cliente := &http.Client{}
	//Paso por query path el tid del hilo y el pid del proceso al que pertenece
	url := fmt.Sprintf("http://%s:%d/finalizarHilo/%d/%d", globals.Config_kernel.Ip_memory, globals.Config_kernel.Port_memory, tcb_finalizado.TID, tcb_finalizado.PID)
	req, err := http.NewRequest("DELETE", url, nil)
	if err != nil {
		log.Printf("Error al enviar peticion a memoria")
		return
	}

	req.Header.Set("Content-Type", "application/json")
	respuesta, err := cliente.Do(req)
	if err != nil {
		return
	}

	if respuesta.StatusCode == http.StatusOK {
		log.Printf(color.Red+"## Memoria recibio peticion de finalizacion del hilo <TID: %d > del proceso <PID: %d >"+color.Reset, tcb_finalizado.TID, tcb_finalizado.PID)
		globals.Sem_b_plani_corto <- true
                log.Printf("Paso el semaforo")
	} else{
		log.Printf("Distinto de OK")
	}
	
}
```

Y en kernel/planificacion en la funcion de corto plazo tenemos
```go
func Corto_plazo() {
	for {
		<-globals.Sem_b_plani_corto
		log.Printf("CORTO PLAZO")
		switch globals.Config_kernel.Algoritmo_planificacion {
			case "FIFO":Algoritmo_FIFO()
			case "PRIORIDADES": Algoritmo_PRIORIDADES()
			case "CMN":Algoritmo_COLAS_MULTINIVEL()
			default:fmt.Println("CORTO PLAZO: Algoritmo de planificacion inexistente")
		}
	}
}
```

A que se puede deber este error? Ya intente varias cosas para "liberar" el semaforo despues de usarlo pero sigue sin funcionar nada de lo que intento.

A todo esto cabe aclarar que a esta altura el semaforo ya fue utilizado

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va? Voy a hacer un par de preguntas para entender un poco mejor por dónde puede estar el problema:

1. Cuando se refieren a que "a esta altura el semaforo ya fue utilizado", ¿esto significa que en el código hay otras goroutines consumiendo del mismo channel, o sea...?
```go
<- globals.Sem_b_plani_corto
```

2. Si corren el código con el debugger, ¿se ejecuta la línea que dice `"Paso el semaforo"` en `Peticion_a_memoria_para_finalizar_hilo`? ¿La goroutine que ejecuta `Corto_plazo` llegó a quedarse esperando a consumir el channel o está ejecutando otra línea? Pregunto porque enviar un mensaje por un channel es bloqueante si se alcanzó la capacidad máxima del buffer del mismo. En este caso, si hay otra rutina que publicó otro mensaje en `globals.Sem_b_plani_corto`, la función `Peticion_a_memoria_para_finalizar_hilo` se va a quedar esperando a que `Corto_plazo` consuma el anterior.

3. ¿Qué intentaron hacer para "liberar" el semáforo? Tengamos en cuenta que los channels son simplemente un productor-consumidor, no debería haber nada por "liberar" una vez recibido el elemento que fue enviado desde otra goroutine. Solamente el productor puede hacer `close(un_channel)` para avisarle al consumidor que no se van a enviar más mensajes, pero entiendo que este no sería el caso ya que el Kernel va a estar planificando constantemente.

Saludos

**Comment by Bru-Nicolas-FRBA** [comment]
Hola:
1. Si, ya tenemos otras rutinas y procesos los cuales realizan:
```go
globals.Sem_b_plani_corto <- true
``` 
Dado que varias acciones que sacan a procesos de exec necesitan llamar al corto plazo para que replanifique y busque el siguiente de ready

2. Si, la linea:
```go
log.Printf("Paso el semaforo")
``` 
aparece en la terminal:
![image](https://github.com/user-attachments/assets/1d7e17e6-0147-4394-a9b4-6fe9b93dc6c3)


3. Ante el problema (mentira, ante la desesperacion) se me ocurrio que quizas el semaforo una vez llamado deberia liberarse, algo asi como "sacarse la variable que le mandamos por el canal para que pueda llegar otra". Intente aplicar lo siguiente
```go
<-globals.Sem_b_plani_corto
defer func() { <-globals.Sem_b_plani_corto }()
``` 
Pensando que funcionaron, pero esto tampoco dio resultado

Leyendo el punto dos nuevamente creo que el problema radica que el Corto_plazo nunca vuelve a esperar al semaforo, voy a intentar solucionarlo por ese lado. Si veo que el error no es ese vuelvo a abrir este issue, muchas gracias
