### ISSUE TITLE
Duda sobre Thread Join

### ISSUE THREAD

**Issue by ahuarca** [sisoputnfrba/foro#4317]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Holaa!! Tengo una duda sobre esta parte del enunciado de la syscall Thread Join, ya que no especifican si la ejecución del TID pasado como parámetro tiene que ejecutarse inmediatamente después de bloquear al hilo que llama a la syscall o si  el TID tiene encolarse en la cola ready y respetar el algoritmo de planificación correspodiente y una vez se termina de ejecutar, ahi recién  se desbloquea el hilo que había llamado a la syscall.

`

### 📔 Citas del enunciado/videos

_THREAD_JOIN, esta syscall recibe como parámetro un TID, mueve el hilo que la invocó al estado BLOCK hasta que el TID pasado por parámetro finalice. En caso de que el TID pasado por parámetro no exista o ya haya finalizado, esta syscall no hace nada y el hilo que la invocó continuará su ejecución._

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by LeandroCarbajales** [comment]
Buenas!
El TID pasado por parámetro ejecutará (o no) cuando le corresponda, la llamada a esta función no modifica su planificación en absoluto. Es posible, por ejemplo, que ese TID pasado por parámetro nunca ejecute (ni finalice) por tener una prioridad baja y por ende el hilo que llamó al thread_join nunca se desbloquee.

Te aclara la duda?
Saludos!
     Lean

**Comment by SantiagoDopazo** [comment]
Hola Buenas!

@ahuarca La duda quedo resuelta? algo mas en lo que podamos ayudar del tema?

Saludos.

**Comment by ahuarca** [comment]
Hola Sisi, muchas gracias por la aclaración!!

**Comment by RaniAgus** [comment]
¡Buenas @ahuarca! Paso a patrullar para avisar (para la próxima) que si la duda ya fue resuelta pueden cerrar el issue 👮🏻‍♂️

Si en un futuro ven que algo no terminó de cuadrar pueden tomarse la libertad de abrir uno nuevo referenciando éste. 

¡Saludos!
