### ISSUE TITLE
Duda sobre RECURSO

### ISSUE THREAD

**Issue by Elias318** [sisoputnfrba/foro#4318]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

En el enunciado de CPU marca que a la hora de una syscall que tengo que enviarle a kernel para su ejecución, le tengo que enviar un RECURSO pero no se si se refiere a una dirección de una carpeta en el sistema o si recurso es una TAD que nosotros tenemos que crear.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by RaniAgus** [comment]
¡Buenas! ¿A cuál syscall en particular se refieren? Existen varias que requieren recursos, pero no todas. ¿Llegaron a consultar la sección de Kernel que explica el manejo de dicha syscall? Saludos

**Comment by RaniAgus** [comment]
Al revés: el **recurso** a crear/pedir/liberar es el propio **mutex** a través de `MUTEX_CREATE`, `MUTEX_LOCK` y `MUTEX_UNLOCK`. Es por esto que cada PCB tiene una lista de mutex.

Los **PCB** representan al **proceso** en sí, por lo que se crean al ejecutar `PROCESS_CREATE` (o al iniciar el Kernel en el caso del proceso 0) y se liberan al ejecutar `PROCESS_EXIT`.

**Comment by SantiagoDopazo** [comment]
Hola Buenas!

Aprovecho para comentar y  agregar a la respuesta de Agus que el parametro que se llama RECURSO en los ejemplos de `MUTEX_CREATE`,` MUTEX_LOCK` y `MUTEX_UNLOCK` es un char* (string) cualquiera representando el nombre de ese recurso.

Te dejo un issue anterior respondido por Dami que hablan del tema: https://github.com/sisoputnfrba/foro/issues/4271

**Comment by iago64** [comment]
@Elias318 Cómo va? Te sirvieron las respuestas de Agus y Santi?

Saludos.-

**Comment by Elias318** [comment]
Hola que tal, si perdon que no respondi. muchas gracias!
