### ISSUE TITLE
Duda creación de comunicación kernel-memoria al crear un proceso.

### ISSUE THREAD

**Issue by nahuel3pro** [sisoputnfrba/foro#4319]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas, tengo una duda de qué hacer en la memoria al recibir la instrucción de creación de un proceso de parte del kernel, entiendo que en esta parte iría manejo de memoria que todavía no vimos en clase, con lo que responder con un "ok" ya estaría. Pero mi duda es si en este paso se debería crear el TID 0 de cada proceso, o si al devolver el "ok" a kernel, este debe mandarle a memoria la operación de creación del hilo principal de dicho proceso.
Básicamente, el TID 0 de los procesos se debe crear en memoria al recibir la operación de creación de proceso o sólo cuando se reciba la operación de creación de hilos? Gracias.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

La comunicación entre Kernel y Memoria pueden resolverla como les resulte mas simple, si con la creación del proceso quieren ademas crear el TID 0 no hay nada que se los impida.

Saludos.-
