### ISSUE TITLE
Duda thread cancel

### ISSUE THREAD

**Issue by AgustinaGuitman** [sisoputnfrba/foro#4320]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas! Si tengo un proceso que tiene el hilo main (0) y otros hilos que fueron creados mediante thread create y se finaliza el hilo main a través de thread cancel, ¿debería finalizar el proceso y todos los hilos asociados?

Desde ya muchas gracias, saludos.

### 📔 Citas del enunciado/videos

THREAD_CANCEL, esta syscall recibe como parámetro un TID con el objetivo de finalizarlo pasando al mismo al estado EXIT. Se deberá indicar a la Memoria la finalización de dicho hilo. En caso de que el TID pasado por parámetro no exista o ya haya finalizado, esta syscall no hace nada. Finalmente, el hilo que la invocó continuará su ejecución.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

No esta en los planes mandarle un PTHREAD_CANCEL al TID 0, pero si quieren hacer esa comprobación para su tranquilidad va a estar bien igual.

Saludos.-

**Comment by AgustinaGuitman** [comment]
Buenísimo, muchas gracias. 
Saludos!
