### ISSUE TITLE
Otra duda con THREAD CANCEL

### ISSUE THREAD

**Issue by KirkSH** [sisoputnfrba/foro#4321]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas. Vi [este issue](https://github.com/sisoputnfrba/foro/issues/4320), y redoblo la apuesta.

¿Qué sucede si un hilo hace THREAD_CANCEL a él mismo?

### 💭 Soluciones posibles

¿Lo manejamos idéntico a un THREAD_EXIT?, ¿o esto tampoco será algo que ocurra en las pruebas?

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by LeandroCarbajales** [comment]
Buenas!
Misma respuesta que en ese issue. La solución que plantean (manejarlo como un thread_exit) estaría bien, pero no vamos a probar ese caso.

Saludos!
     Lean

**Comment by KirkSH** [comment]
Genial. Gracias.
