### ISSUE TITLE
Validacion de pseudocodigo 

### ISSUE THREAD

**Issue by tolaDiego** [sisoputnfrba/foro#4322]
### 🖋️ Descripción

Buenas tardes!
Estuve escribiendo estas instrucciones de pseudocodigo de prueba(algunas syscalls por sobre todo) segun lo que entiendo que deben hacer las instrucciones. 
Les agradeceria  que lo revisen/validen por si se me paso algo al escribir las instrucciones o el resultado esperado no es el correcto. 

Gracias.

### 📔 Citas del documento de pruebas

Prueba de deadlock de hilos.
Orden esperado de los hilos/procesos que finalizan:
KLTA3-KLTB1-KLTB0-ProcesoB-KLTC1-KLTC0-ProcesoC
Planificación: fifo
Tamanio de memoria total: 400
Proceso inicial A: instruccionesKLTA0, tamanio=200

```c++
Instrucciones KLTA0:		
MUTEX_CREATE mutexA1                
THREAD_CREATE instruccKLTA1 3
THREAD_CREATE instruccKLTA2 3		
THREAD_CREATE instruccKLTA3 2				
PROCESS_CREATE instruccKLTB0 200 5   
THREAD_JOIN 2				                
THREAD_EXIT				    
PROCESS_EXIT

Instrucciones KLTA1:
SET AX 2
SUM AX AX
MUTEX_LOCK mutexA1		           					
THREAD_EXIT	

Instrucciones KLTA2:        
SET AX 1
SET BX 2
SUM AX BX
MUTEX_LOCK mutexA1		               
THREAD_EXIT

Instrucciones KLTA3:
SET AX 1
SET BX 2
SUM AX BX					
THREAD_EXIT	
			
Proceso B
Instrucciones KLTB0:
MUTEX_CREATE mutexB1                
THREAD_CREATE instruccKLTB1 3		
PROCESS_CREATE instruccKLTC0 200 5  
THREAD_JOIN 1				                
THREAD_EXIT				    
PROCESS_EXIT

Instrucciones KLTB1:        
SET AX 1
SET BX 2
SUM AX BX               
THREAD_EXIT

Proceso C
Instrucciones KLTC0:               
THREAD_CREATE instruccKLTC1 3		
THREAD_JOIN 1				                
THREAD_EXIT				    
PROCESS_EXIT

Instrucciones KLTC1:        
SET AX 1
SET BX 2
SUM AX BX               
THREAD_EXIT
```

Con esta prueba se deberian desbloquear todos los hilos bloqueados el hilo1(por join/lock) cuando este sea terminado.
Orden de finalización esperado: KLTA1-KLTA6-KLTA2-KLTA3-KLTA4-KLTA5-KLTA0-ProcesoA
Planificación: fifo
Tamanio de memoria total: 400
Proceso inicial A: instruccionesKLTA0, tamanio=200

```c++
Instrucciones KLTA0:		
MUTEX_CREATE mutexA1                
THREAD_CREATE instruccKLTA1 3
THREAD_CREATE instruccKLTA2 3		
THREAD_CREATE instruccKLTA3 2	
THREAD_CREATE instruccKLTA4 2
THREAD_CREATE instruccKLTA5 2
THREAD_CREATE instruccKLTA6 2			 
THREAD_JOIN 6				                
THREAD_EXIT				    
PROCESS_EXIT

Instrucciones KLTA1:
SET AX 2
SUM AX AX
MUTEX_LOCK mutexA1
THREAD_JOIN 0		           					
THREAD_EXIT	


Instrucciones KLTA2:         
SET AX 1
SET BX 2
SUM AX BX
MUTEX_LOCK mutexA1		               
THREAD_EXIT

Instrucciones KLTA3:
SET AX 1
SET BX 2
SUM AX BX
THREAD_MUTEX mutexA1 					
THREAD_EXIT

Instrucciones KLTA4:
SET AX 1
SET BX 2
SUM AX BX
THREAD_JOIN 1					
THREAD_EXIT

Instrucciones KLTA5:
SET AX 1
SET BX 2
SUM AX BX
THREAD_JOIN 1					
THREAD_EXIT

Instrucciones KLTA6:
SET AX 1
SET BX 2
THREAD_CANCEL 1		
THREAD_EXIT	
``` 

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by LeandroCarbajales** [comment]
Buenas!
Te hago algunas observaciones en algunos puntos que no se comportarían como lo están esperando:

En primer lugar, nunca tendremos la syscall `THREAD_EXIT` en el hilo 0.
Si finaliza el hilo 0 con thread_exit, nunca llegaría a ejecutar process_exit. Siempre el hilo 0 tendrá únicamente process_exit, es decir, cuando finaliza el mismo, finaliza todo el proceso. Este comportamiento es muy similar a los hilos reales de Linux, donde retornar de la función main normalmente implica la finalización de todo el proceso.

En la primer prueba, dada la planificación FIFO los KLTA1 y KLTA2 no ejecutarían y finalizarían primero?

En la segunda prueba, mismo comentario, capaz es una malinterpretación referida a los mutex_lock, pero así como están no veo por qué no finalizarían KLTA2 y KLTA3 primero.
Luego, la única cosa rara que veo es relacionada con mi primer comentario, sería medio raro hacer un `THREAD_JOIN 0` ya que cuando el mismo finaliza, finaliza el proceso (y todos sus hilos)

**Comment by tolaDiego** [comment]
Gracias por las observaciones Leandro.
**Prueba 1**
En la primer prueba me falto poner un lock en el KLTA0 para generar el deadlock antes del join y que no puedan finalizar KLT1 y KLT2 primero. Ahora sí deberia resultar como lo espero no?
**Prueba 2**
Te describo mas o menos como lo pense(habiendo hecho las correcciones que marcaste): 
entiendo que el KLTA1 toma el mutexA1 y luego se bloquea haciendo que el resto tambien se bloquee porque esperan el mismo mutex o que finalice(incluidos KLA2 y KLTA3): al ejecutar KLTA6, este cancela KLTA1 y envia a ready los hilos que requerían algo(un mutex o su finalización) de KLTA1.La finalización de este hilo además debería desbloquear el hilo 0.
En este punto tendría: finalizados KLTA1-KLTA6
y en ready: KLTA2-KLTA3-KLTA4-KLTA5-KLTA0 que finalizan en este mismo orden.
Lo hice teniendo en cuenta esta parte del enunciado:
>Finalización de hilos
Al momento de finalizar un hilo, el Kernel deberá informar a la Memoria la finalización del mismo, liberar su TCB asociado y deberá mover al estado READY a todos los hilos que se encontraban bloqueados por ese TID. De esta manera, se desbloquean aquellos hilos bloqueados por THREAD_JOIN o por mutex tomados por el hilo finalizado (en caso que hubiera).

>
Te dejo de las instrucciones como quedaron con los cambios:

Prueba 1: deadlock
FIFO
Orden de los hilos/procesos que finalizan:
KLTA3-KLTB1-KLTB0-ProcesoB-KLTC1-KLTC0-ProcesoC

```c++
Instrucciones KLTA0:		
MUTEX_CREATE mutexA1                
THREAD_CREATE instruccKLTA1 3
THREAD_CREATE instruccKLTA2 3		
THREAD_CREATE instruccKLTA3 2				
PROCESS_CREATE instruccKLTB0 200 5
MUTEX_LOCK mutexA1   			//lock agregado
THREAD_JOIN 2					                		    
PROCESS_EXIT

Instrucciones KLTA1:
SET AX 2
SUM AX AX
MUTEX_LOCK mutexA1		          					
THREAD_EXIT	

Instrucciones KLTA2:        
SET AX 1
SET BX 2
SUM AX BX
MUTEX_LOCK mutexA1		              
THREAD_EXIT

Instrucciones KLTA3:
SET AX 1
SET BX 2
SUM AX BX					
THREAD_EXIT	
			
Proceso B
Instrucciones KLTB0:
MUTEX_CREATE mutexB1                
THREAD_CREATE instruccKLTB1 3		
PROCESS_CREATE instruccKLTC0 200 5  
THREAD_JOIN 1				                				    
PROCESS_EXIT

Instrucciones KLTB1:        
SET AX 1
SET BX 2
SUM AX BX               
THREAD_EXIT

Proceso C
Instrucciones KLTC0:              
THREAD_CREATE instruccKLTC1 3		
THREAD_JOIN 1				                				    
PROCESS_EXIT

Instrucciones KLTC1:        
SET AX 1
SET BX 2
SUM AX BX               
THREAD_EXIT
``` 
Prueba 2:
FIFO
Orden de finalización: KLTA1-KLTA6-KLTA2-KLTA3-KLTA4-KLTA5-KLTA0-ProcesoA

```c++
Instrucciones KLTA0:		
MUTEX_CREATE mutexA1                
THREAD_CREATE instruccKLTA1 3
THREAD_CREATE instruccKLTA2 3		
THREAD_CREATE instruccKLTA3 2	
THREAD_CREATE instruccKLTA4 2
THREAD_CREATE instruccKLTA5 2
THREAD_CREATE instruccKLTA6 2			 
THREAD_JOIN 6				                				    
PROCESS_EXIT

 
Instrucciones KLTA1:
SET AX 2
SUM AX AX
MUTEX_LOCK mutexA1
THREAD_JOIN 5		     //correccion de thread_join 0			
THREAD_EXIT
	
Instrucciones KLTA2: bloq por KLTA1        
SET AX 1
SET BX 2
SUM AX BX
MUTEX_LOCK mutexA1		               
THREAD_EXIT

Instrucciones KLTA3: bloq por KLTA1
SET AX 1
SET BX 2
SUM AX BX
THREAD_MUTEX mutexA1 					
THREAD_EXIT

Instrucciones KLTA4: bloq por join a 1
SET AX 1
SET BX 2
SUM AX BX
THREAD_JOIN 1					
THREAD_EXIT

Instrucciones KLTA5:  bloq por join a 1
SET AX 1
SET BX 2
SUM AX BX
THREAD_JOIN 1					
THREAD_EXIT

Instrucciones KLTA6:
SET AX 1
SET BX 2
THREAD_CANCEL 1		
THREAD_EXIT	
```

**Comment by LeandroCarbajales** [comment]
Ahora sí!
Lo veo bien :)

**Comment by tolaDiego** [comment]
Muchas gracias Leandro!!
