### ISSUE TITLE
Thread_Join 

### ISSUE THREAD

**Issue by JuanTerri** [sisoputnfrba/foro#4323]
### 🖋️ Descripción

No entiendo como puedo saber cual es el hilo que la invoco para pasarlo a block, yo entiendo que por parámetro se me pasa el TID del hilo al que voy a esperar que termine de ejecutar, para que el hilo que hizo la instrucción pueda continuar
La posible solución que se me ocurre es tener en cuenta que el hilo que realizo esta instrucción va a ser el primero en mi lista de EXEC?

### 📚 Búsqueda en documentación/foros

Vi este issue #4317 y entendi que no afecta en su planificacion pero sigo teniendo la duda que plantie anteriormente.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by mefederico** [comment]
Hola buenas! 

El hilo que invoca THREAD_JOIN solamente puede ser uno, que es el que está en ejecución al momento de atender la syscall misma. Ustedes deben pasar el hilo en ejecución a bloqueado y tener una referencia de alguna forma a que hilo está esperando, para en caso de finalizar ese hilo en cuestión poder desbloquear todos los que esperaban al mismo.

**Comment by JuanTerri** [comment]
Perfecto, entonces creo que la solución que pensé seria correcta. Muchas Gracias.
