### ISSUE TITLE
Sincronización de NEW y EXIT

### ISSUE THREAD

**Issue by KirkSH** [sisoputnfrba/foro#4324]
### 🖋️ Descripción

Hola. Les cuento.

En Kernel tenemos:
Un pthread para la cola NEW, que se encarga de `solicitar_creacion_de_proceso_a_memoria()`, y luego de la confirmación pasa su hilo main a READY.
Tenemos otro pthread para la cola de EXIT, que va pidiendo a memoria la eliminación de los hilos encolados, y que cuando corresponde tambien se encarga de `solicitar_eliminacion_de_proceso_a_memoria()`.

Estas funciones no solo mandan la solicitud a memoria, sino que además esperan la respuesta, e informan si fue exitosa o no para poder manejar cada caso.

En el enunciado menciona que ante una falla en la creación, se debe esperar una finalización, y volver a intentar.
Podemos sincronizar eso mediante semáforos, pero surge el inconveniente de que puede suceder que se terminó de intentar la creación (fallida) en el **pthread new**, y tome lugar el **pthread exit** antes de que el **pthread new** haga el sem_wait() (o la verificación que sea que use). Entonces un proceso podría estar finalizando, y "escapándose" al detector de "reintento" de creación.

¿Cómo podemos abordar el problema para solucionar ese caso límite?

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by f-and** [comment]
Buenas Kirk!

Para contestarte, te pregunto, como manejan la conexión entre Memoria y Kernel? Ya que si la manejan por dos puertos distintos (el de New y el de Exit por ponerles nombres), van a tener varios problemas para sincronizarlos; en cambio, si lo manejan con un solo puerto, como manejan el caso en el que se quiera mandar un proceso nuevo y terminar un proceso a la vez? La solución simple sería poner un Mutex que compruebe que nadie está comunicandose con Memoria en ese momento, y luego de esto poner el sem_wait() que mencionas. 

Te sirvió mi respuesta?
Saludos.-

**Comment by f-and** [comment]
Tenes razón, me corrigo con lo del mutex, se me había pasado lo del servidor multihilo jajaja.

Otra forma de verlo es como lo explica el enunciado mismo:

> [...] luego de recibir la confirmación por parte de la Memoria deberá liberar su PCB asociado e intentar inicializar uno de los que estén esperando en estado NEW si los hubiere.

Podes manejarlo de varias maneras, una posible sería verificar la cola de NEW después de que se termine el proceso y mandar a crear el proceso, en vez de manejar un semáforo.

Igual, en sí, como Memoria no tiene retraso para con el Kernel, es un caso muy borde de analizar. Considerando que apenas recibe la negación de la creación del proceso ya podrías mandar el sem_wait, no hay muchas chances de que ocurra en una prueba.

**Comment by KirkSH** [comment]
Oka. Gracias.
