### ISSUE TITLE
Duda sobre reservación de espacio en Mmeoria para procesos, hilos y contextos de ejecución

### ISSUE THREAD

**Issue by ahuarca** [sisoputnfrba/foro#4325]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Hola! Teniamos una duda sobre como proceder ante la creaciónde un proceso en Memoria:

1) No sabemos si hay que reservar espacio con malloc tanto para las particiones fijas y dinamicas o si hay que ir restando el espacio de cada proceso a la memoria de usuario o a las particones en si. 
2) Tampoco entendemos a que se refieren con **la parte del contexto de ejecución común para el proceso,*, ya que tenemos los contextos de ejecución de cada hilo y lo único que tienen en común sería el PID de su proceso.
3) No sabemos como sería en si el pasaje de direcciones lógicas a fisicas y viceversa, ¿Tendriamos que hacer un cálculo en especifico?¿o qué?

### 📔 Citas del enunciado/videos

Se deberá almacenar, **por cada PID del sistema, la parte del contexto de ejecución común para el proceso,** en este caso, es la requerida para **poder traducir las direcciones lógicas a físicas: base y límite.**
Luego, por cada TID del sistema, se tendrán los registros de la CPU propios de cada hilo: AX, BX, CX, DX, EX, FX, GX, HX y PC. Siendo todos ellos inicializados en 0.

**Creación de proceso**
Al momento de crear los procesos deberemos tener en cuenta qué esquema estamos utilizando, es por esto que vamos a diferenciar los dos esquemas:
**Particiones Fijas**: En este esquema la lista de particiones vendrá dada por archivo de configuración y la misma no se podrá alterar a lo largo de la ejecución.
**Particiones Dinámicas**: En este esquema la lista de particiones, va a iniciar como una única partición libre del tamaño total de la memoria y la misma se va a ir subdividiendo a medida que lleguen los pedidos de creación de los procesos, es por esto que la lista será dinámica.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by f-and** [comment]
Buenas Ahuarca.

1. Las particiones las van a tener que manejar con una estructura que diseñen ustedes. Consideren que el malloc ya lo hacen al principio de todo cuando crean el espacio de usuario. Por lo que necesitan pensar una forma en la cual, *sin tocar necesariamente el void \**, valide la Memoria que cada parte específica del espacio le pertenece a X PID. 

2. La parte común del contexto ejecución es justamente, además del PID, lo que describe a continuación en la cita que mencionas, la base y el límite, osea, donde empieza el espacio de ese proceso, y cual es su límite en bytes.

3. El pasaje de direcciones lógicas a físicas es un concepto que deberían ver en la teoría, no recuerdo bien cuando se da, pero no se preocupen si aun no vieron memoria. Es lo que maneja el apartado de [MMU en el enunciado](https://docs.google.com/document/d/1KloOXfXQb_c1S3PKDEEywnArX9YB3aApqGVmpNgv9_Q/edit?tab=t.0#heading=h.te5l1519s35q). Y la gist es que cada hilo no va a saber en qué dirección tiene almacenado X elemento, pero sabe que lo tiene en el byte Y de su sección de memoria, por lo que tiene que traducir ese Y byte de memoria a la posición de la memoria real. Por lo que sí tienen que hacer unos cálculos, pero el enunciado los explica bien y la teoría lo va a fundamentar más.

Espero haber contestado tu consulta.
Saludos.-

**Comment by ahuarca** [comment]
Holaa, siii, muchas gracias, nos diste la siguiente idea de como podríamos implementarlo:


Como el espacio de usuario lo tenemos como un void* espacioUsuario= malloc(1024), nos quedaría así

Para las **particones fijas**:

Tenemos un vector con las particiones dadas en la config de memoria, por cada partición vamos a chequear si el tamaño del proceso que nos mando Kernel junto con su PID, es menor o igual a la partición que le tocó, sino es así se finaliza el proceso, pero si se cumple el caso, le asignamos esa partición , guardamos la  estructura completa del proceso en una lista de structs PCB  en el módulo memoria y le seteamos el valor de su base y limite según la partición que le tocó, ejemplo: Mi proceso tiene tamaño 256 y le tocó la partición con valor 512, entonces su base sería 0 y su límite 512, ¿Acá que hariamos los 256 de espacio que nos sobran, podriamos usarlo para almacenar otro proceso? 
Volviendo al tema, le asignariamos un espacio de usuario con un malloc de 512 para esa partición, ya que necesitariamos escribir en ese espacio, el pid del proceso, el limite, la base,  el tid y los cde de cada hilo, al principio inicializados en cero y luego ir reescribiendo los valores cada vez que sea desalojado el hilo.

Para las **particiones dinámicas** 

Decidimos que cada vez que nos llegue un proceso con su respectivo tamaño, vamos a usar ese valor para delimitar la partición que le va a ser asignada, y luego vamos a hacer un memcpy(espacioUsuario,  campoDelPCB, tamañoCampoDelPCB), donde  copiariamos los campos del PCB, tales  como su pid, base, el  limite, el tid y el cde de cada hilo, luego modificariamos el desplazamiento dentro del espacio de usuario para que cuando llegue el proximo proceso no pise los valores del anterior.

**Comment by f-and** [comment]
Unas cosas a tener en cuenta:

> Mi proceso tiene tamaño 256 y le tocó la partición con valor 512, entonces su base sería 0 y su límite 512, ¿Acá que hariamos los 256 de espacio que nos sobran, podriamos usarlo para almacenar otro proceso?

Justamente, no, es un inconveniente de usar ese tipo de estructura, vivis con ese overhead de más, pero es algo que le dejo a los profesores explicar :P

> le asignariamos un espacio de usuario con un malloc de 512 para esa partición

No te va a funcionar hacer un malloc, ya que es algo que ya hiciste antes con el `void* espacioUsuario= malloc(1024)`. Lo que sea que tengas para asignar el espacio va a estar necesariamente ***fuera*** de este void*.

> ya que necesitariamos escribir en ese espacio, el pid del proceso, el limite, la base, el tid y los cde de cada hilo, al principio inicializados en cero y luego ir reescribiendo los valores cada vez que sea desalojado el hilo.

Ojo, que ahí no hay que confundir cosas, el espacio de usuario es una cosa, y la memoria de sistema es otra completamente distinta, en el primero (el void*) vas a guardar y leer valores únicamente cuando te llame a hacerlo el Kernel o el CPU con una operación de un hilo en ejecución, mientras que la memoria de sistema va a ser algo abstracto donde se incluyen estos contextos de ejecución, separado del void*, como los archivos de pseudocódigo.

> y luego vamos a hacer un memcpy(espacioUsuario, campoDelPCB, tamañoCampoDelPCB), donde copiariamos los campos del PCB, tales como su pid, base, el limite, el tid y el cde de cada hilo

Ídem de lo anterior, no pongan los contextos de ejecución en el espacio de usuario que van a hacerse un lio jajaja

**Comment by ahuarca** [comment]
Holaa, wenass, entonces teniendo en cuenta estas acalaraciones: 

**No te va a funcionar hacer un malloc, ya que es algo que ya hiciste antes con el void* espacioUsuario= malloc(1024). Lo que sea que tengas para asignar el espacio va a estar necesariamente fuera de este void*.

Claro, ¿El objetivo entonces tanto para particiones fijas y dinámicas, es ir reservando espacio para cada proceso según su tamaño dentro del void* espacioUsuario= malloc(1024)? Y luego para cada espacio asignado tendriamos que hacer una de estás 2 cosas:

1) Ir copiando solo los valores de PID, base y limite o ¿Hay algo más que debamos meter dentro de ese espacio asigando al proceso?.

2) No copiar nada en ese espacio reservado para el proceso, solo saber cual es su principio y final, para setear los valores de base y limite dentro de un struct del PCB. Y cuando queramos hacer un write mem, recién ahí se escribiría algo en ese espacio para luego ser leído por un write mem.

**Justamente, no, es un inconveniente de usar ese tipo de estructura, vivis con ese overhead de más, pero es algo que le dejo a los profesores explicar :P**

Ahhh, okk, entonces no tenemos que resolverlo, solo trabajar con ello, gracias!

**Comment by ahuarca** [comment]
Hola de nuevo, también nos surgió la duda de que si se da el caso de que el  espacio de usuario es sólo para que el proceso lea y escriba, ¿Cualquier hilo de ese proceso puede leer y escribir cualquier dato, no? respetando el tamaño de ese proceso, no hay que asignarle una "base y un limite " por así decirlo, al hilo en si, dentro del espacio de usuario.

**Comment by f-and** [comment]
> No copiar nada en ese espacio reservado para el proceso, solo saber cual es su principio y final, para setear los valores de base y limite dentro de un struct del PCB. Y cuando queramos hacer un write mem, recién ahí se escribiría algo en ese espacio para luego ser leído por un write mem.

Tienen que seguir esta opción, porque la información administrativa del proceso no entra en el espacio de usuario. [Lo que sí, esto se guardaría en un contexto de ejecución del proceso, no en el PCB.](https://docs.google.com/document/d/1KloOXfXQb_c1S3PKDEEywnArX9YB3aApqGVmpNgv9_Q/edit?tab=t.0#heading=h.prg0jxac8qgf)

> ¿Cualquier hilo de ese proceso puede leer y escribir cualquier dato, no? respetando el tamaño de ese proceso, no hay que asignarle una "base y un limite " por así decirlo, al hilo en si

Claro, cualquier hilo va a tener en un proceso "padre/madre" que tiene vinculado la base y el límite que va a usar dicho hilo. Por lo que todo hilo puede usar la memoria del proceso como se le plazca.

**Comment by LeandroCarbajales** [comment]
Buenas @ahuarca !
Te sirvió la respuesta de Fede? Quedó alguna duda?

**Comment by ahuarca** [comment]
Holaa, si me sirvió!! Gracias!! Por el momento no tengo más dudas, cierro issues
