### ISSUE TITLE
Duda con THREAD_JOIN

### ISSUE THREAD

**Issue by milagrosvera** [sisoputnfrba/foro#4326]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas, queriamos consultar si en thread_join, el hilo que es invocado (pasado por parámetro) debe ser puesto a ejecutar inmediatamente cuando se atiende la syscall, o si debemos esperar a que sea su turno de ejecución para que pueda finalizar.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by f-and** [comment]
Buenas Milagros, no, el hilo invocado es simplemente el "desbloqueante", y va a ejecutar cuando tenga que ejecutar (tal vez no ejecute directamente!).
Saludos.-

**Comment by milagrosvera** [comment]
perfecto graciass
