### ISSUE TITLE
Ciclo de Instruccion CPU: Syscalls

### ISSUE THREAD

**Issue by GabrielBorre** [sisoputnfrba/foro#4327]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

¡Buenos días! Cómo están?

Me surgió una duda sobre el ciclo de instrucción cuando en la fase "Decode"  la CPU identifica que la instrucción enviada por memoria es una syscall y no una instrucción que pueda ejecutar la CPU.

La pregunta es: si en plena fase "Decode" el kernel le envía una interrupción a CPU para desalojar un hilo que tiene como próxima instrucción a una syscall, ¿ la CPU le devuelve el hilo al kernel para que atienda la syscall o, por el contrario, la CPU desaloja al hilo, omite la syscall y espera por un nuevo hilo a ejecutar?

Yo entiendo que para las instrucciones ordinarias de la CPU el ciclo de instrucción nunca se interrumpe y se verifican las interrupciones en la última fase (Check Interrupt), pero al ser las syscalls instrucciones especiales que debe atender el kernel, mi duda es si ante una eventual interrupción en alguna parte del ciclo, la CPU debe devolverle la syscall para que el kernel la atienda, o si se omite la syscall y se desaloja al hilo, ya que la CPU no puede pasar por la fase "execute" de una syscall.

Si tuviera que razonar algo ,en este caso, diría que las syscalls no se deberían devolver al kernel para que este las atienda, puesto que en la vida real la mayoría de ellas no son atómicas (como sí lo son las instrucciones del procesador) y, consecuentemente , podrían ser interrumpidas en el medio de su atención. Sin embargo, pregunto porque no estoy seguro estar razonando correctamente,

Desde ya, mil gracias!!

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by LeandroCarbajales** [comment]
Buenas!

> ¿ la CPU le devuelve el hilo al kernel para que atienda la syscall o, por el contrario, la CPU desaloja al hilo, omite la syscall y espera por un nuevo hilo a ejecutar?

Si, devuelve el hilo al Kernel para que atienda la syscall.

> pero al ser las syscalls instrucciones especiales que debe atender el kernel, mi duda es si ante una eventual interrupción en alguna parte del ciclo, la CPU debe devolverle la syscall para que el kernel la atienda, o si se omite la syscall y se desaloja al hilo, ya que la CPU no puede pasar por la fase "execute" de una syscall.

La syscall en sí es una instrucción que se ejecuta normalmente y llega a la etapa de execute. La diferencia es que justamente lo que hace esa instrucción es causar un trap para que lo atienda el SO (cambio de contexto/modo) y éste ejecute la rutina correspondiente a esa syscall.

> Si tuviera que razonar algo ,en este caso, diría que las syscalls no se deberían devolver al kernel para que este las atienda, puesto que en la vida real la mayoría de ellas no son atómicas (como sí lo son las instrucciones del procesador) y, consecuentemente , podrían ser interrumpidas en el medio de su atención. Sin embargo, pregunto porque no estoy seguro estar razonando correctamente,

En la vida real la interrupción llegaría al procesador pero este mismo ya estaría ejecutando en modo Kernel, al atender la interrupción pondría al proceso correspondiente en ready y seguiría ejecutando la rutina de esa syscall. Por otro lado, la rutina misma de la syscall podría deshabilitar interrupciones (instrucción privilegiada "cli") para garantizar su propia atomicidad (no podría ser interrumpida), como en el caso de la syscalls correspondientes a semáforos.

Para resumir, a efectos del TP donde todo ese mecanismo y la CPU están muy simplificados, sigan los lineamientos del enunciado. Si llega la instrucción de syscall, se ejecuta. Si también llega una interrupción de Q, eventualmente ese proceso debería volver a ready (si es que aun no cambió de estado por la syscall misma).

Te aclara las dudas?
Saludos!
     Lean

**Comment by GabrielBorre** [comment]
Buenas Lean! 

En primer lugar, muchísimas gracias por la respuesta tan clara y detallada!

Lo único que me genera duda de la implementación aconsejada es que supongo que la CPU le podría estar devolviendo al Kernel dos veces el mismo hilo en un mismo ciclo de instruccion: la primera vez, cuando la instrucción decodificada sea una syscall y la segunda vez, cuando la fase Check Interrupt detecte que el kernel lanzó una interrupción par desalojar al hilo que había solicitado la syscall.

Ante la primera devolución, el kernel replanifica o manda de vuelta al hilo a ejecutar (según la naturaleza de la syscall), mientras que ante la segunda (por motivo de interrupcion), el kernel deberá replanificar, pero anteriormente ya había mandado un hilo a ejecutar, lo que hace que se crucen todos los cables jeje.

Lo que se me ocurre ahora es que, en caso de decodificar una syscall, la CPU se quede esperando en la fase Check Interrupt la devolución del hilo que solicitó la syscall para chequear si el kernel envió interrupciones en algún momento de su ejecución. En caso de que así, sea se le devuelve al kernel el hilo y este realiza la replanificación. 

¿Esta última aproximación sería correcta? Muchas gracias, Lean!

**Comment by LeandroCarbajales** [comment]
Buenas!
Pueden implementarlo de diferentes maneras y tener todos los chequeos que crean necesarios.
Esa última opción que proponen la veo bien :). Solamente tengan en cuenta que el hilo que vuelve puede ser otro y en ese caso quieran desechar la interrupción y comenzar un nuevo ciclo normalmente. El único caso medio rebuscado que se me ocurre es que si ese hilo es el único en el sistema: si viene una syscall bloqueante y al mismo tiempo una interrupción, el mismo se bloquearía y no ejecutaría ningún otro, luego, cuando se desbloquee y vuelva a CPU sería inmediatamente devuelvo por fin de Q lo que sería raro porque supuestamente ya había terminado su ráfaga debido al bloqueo, para este caso rebuscado pueden agregar algún chequeo más.
Otra opción que se me ocurre es que si el Kernel cambia el estado del hilo debido a la syscall, que cancele la interrupción si aun no la mandó y/o le mande un mensaje por el puerto de interrupt para decirle "che, olvidate la última interrupt que te mandé".

**Comment by GabrielBorre** [comment]
Excelente, Lean! Clarísimo todo, muchísimas gracias por tu ayuda, nos sirve un montón.

Nuevamente, muchas gracias y buen fin de semana.

Cierro el issue.

Saludos!
