### ISSUE TITLE
Dudas sobre la memoria

### ISSUE THREAD

**Issue by urielmayo** [sisoputnfrba/foro#4328]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas tarde, tengo dudas acerca de la asigancion de memoria de sistema y de usario. En el TP se habla de 2 estructuras, memoria de usuario y memoria de sistema.
Mi duda era cuanto hay que asignarle a cada uno. Leyendo el enunciado y revisando el archivo de configuracion, vi que hay una key **TAM_MEMORIA** y otra de **PARTICIONES**. 
Suponiendo que **TAM_MEMORIA=1024**. Esto quiere decir que le tengo que asignar 1024 bytes a memoria de sistema y 1024 bytes a memoria de usuario? 50% a cada uno?

### 📔 Citas del enunciado/videos

Las estructuras de este módulo las dividiremos en dos categorías, Memoria del Sistema y Memoria de Usuario.
Memoria de Sistema
Contextos de ejecución
Se deberá almacenar, por cada PID del sistema, la parte del contexto de ejecución común para el proceso, en este caso, es la requerida para poder traducir las direcciones lógicas a físicas: base y límite.
Luego, por cada TID del sistema, se tendrán los registros de la CPU propios de cada hilo: AX, BX, CX, DX, EX, FX, GX, HX y PC. Siendo todos ellos inicializados en 0.
Archivos de pseudocódigo
Por cada TID del sistema, se deberá leer su archivo de pseudocódigo y guardar de forma estructurada las instrucciones del mismo para poder devolverlas una a una a pedido de la CPU. Queda a criterio del grupo utilizar la estructura que crea conveniente para este caso de uso.
Memoria de Usuario
Esquema de memoria y Estructuras
La memoria al trabajar bajo dos esquemas diferentes. Al iniciar la memoria se definirá el esquema a utilizar mediante el archivo de configuración, estos esquemas pueden ser:

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by f-and** [comment]
Buenas Uriel, 

Lo que buscamos con separar la memoria de sistema del espacio de usuario es ayudarles a simplificar la parte más "burocrática" del TP, lo que serían los archivos de pseudocódigo y los contextos de ejecución, por lo que estos dos (las dos partes de la memoria de sistema) no necesitan un void* como si lo requiere el espacio de usuario, ustedes deberían almacenarlos en estructuras que diseñen para esa tarea, sin importar el tamaño de estos.

Por el otro lado, tanto la Key de TAM_MEMORIA como la de PARTICIONES que mencionas son ambas específicas del Espacio de Usuario, siendo la primera la que van a utilizar para Mallocear el void* y la segunda, en el caso que el particionamiento sea fijo, son las particiones de memoria que van a tener listas para asignarle a los procesos.

Espero haber contestado tu consulta.
Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas @urielmayo !
Te sirvió la respuesta de Fede? Quedaron dudas?

**Comment by iago64** [comment]
Cerramos el issue por inactividad, cualquier cosa pueden crear un nuevo issue haciendo referencia al mismo.
