### ISSUE TITLE
Dudas sobre como tratar las syscalls y las interrupciones 

### ISSUE THREAD

**Issue by MilagrosLu** [sisoputnfrba/foro#4330]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

Hola! Teníamos una duda sobre como tratar las syscalls desde la CPU. Nosotros interpretamos que cuando la instrucción a ejecutar es una syscall la misma enviaría el contexto de ejecución a memoria para que se actualice y luego mandaría un mensaje al kernel con la syscall a atender. Luego la CPU esperaría hasta que kernel finalice la ejecución de la misma, enviando el estado de finalización como repuesta. Luego de esto, la CPU continua con el ciclo de instrucciones y checkea las interrupciones. Si la syscall era bloqueante se bloqueara ya que el kernel previamente habría enviado la interrupción. Queríamos saber si esto era correcto, especialmente el hecho de esperar a la finalización de la syscall para la continuación del ciclo. 
También teníamos la duda de si se debe actualizar el contexto de ejecución en todas las syscalls incluso en aquellas que no son bloqueantes. 
Con respecto a la duda sobre el trato de las interrupciones no sabíamos como se debían tratar si llegan muchas interrupciones en un solo ciclo de instrucciones a la CPU. Deberían tratarse secuencialmente, por prioridad, realizar solo una interrupción y enviar al kernel las distintas razones que la causaron?
Desde ya muchas gracias, 
Saludos. 
 

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by LeandroCarbajales** [comment]
Buenas!
Les propongo pensarlo desde el punto de vista que el módulo CPU no sabe qué conlleva cada una de esas syscalls, solamente sabe "llamarlas".
Desde este punto de vista, la CPU no sabe si la misma será bloqueante o no (porque de hecho, una syscall como thread_lock es bloqueante condicionalmente al estado del semáforo, que solamente lo conoce el Kernel), ni tampoco sabe si la misma conllevará finalizar al hilo/proceso (debido a un error, o las syscalls de exit).
Por este motivo, como plantean los lineamientos del enunciado, la CPU debería actualizar el contexto de ejecución del hilo ante cualquier syscall y luego esperar a que el Kernel le vuelva a dar algo para ejecutar (que puede ser el mismo hilo u otro), a efectos teóricos pueden tomar esto como el "cambio de contexto" que vemos en clases.

Con respecto a las interrupciones, por suerte en este TP solamente contamos con la interrupción correspondiente al fin de Q y la de desalojo por prioridades (esta última únicamente en el enunciado de Go) que ambas cumplen el mismo objetivo, desalojar a un hilo en ejecución, por lo que no habrían prioridades en ese sentido.
Pueden tratarlas como mejor les parezca, lo importante es que se cumpla el comportamiento esperado, si el hilo a desalojar está en exec que eventualmente pase a ready.

Les aclara las dudas?
Saludos!
    Lean

**Comment by LeandroCarbajales** [comment]
Buenas @MilagrosLu !
Te sirvió la respuesta? Alguna parte que hayan quedado dudas?

**Comment by MilagrosLu** [comment]
Buenas, sí no quedo ninguna duda. Muchas gracias
