### ISSUE TITLE
Consulta DUMP_MEMORY

### ISSUE THREAD

**Issue by AgustinHerzkovich** [sisoputnfrba/foro#4332]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

Hola buenas, nuestra duda sería si cuando se le solicita a memoria que haga dump de un proceso, la respuesta se obtiene de manera inmediata o se debe esperar la misma en otra api, porque en el enunciado dice que el hilo se bloquea hasta que el módulo memoria confirme la finalización de la operación. Esa confirmación la obtenemos de forma inmediata al hacer el post en memoria, o simplemente hacemos el post y luego recibimos la confirmación en otra api? Es decir, la pregunta sería si para este caso la comunicación se realiza de manera síncrona o habría que definir dos métodos, uno para enviar y otro para recibir. Saludos, gracias.

### 📔 Citas del enunciado/videos

>Esta syscall bloqueará al hilo que la invocó hasta que el módulo memoria confirme la finalización de la operación, en caso de error, el proceso se enviará a EXIT. Caso contrario, el hilo se desbloquea normalmente pasando a READY.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by NachoMoscatelli** [comment]
Buenas, me sumo a la consulta.

Si el kernel abre y cierra una conexion con memoria por cada solicituda que deba realizar, me estaría dejando 2 opciones:

- El pedido de dump_memory es bloqueante para el flujo del kernel, lo cual pareciera un comportamiento no deseado ya que se quiere bloquear el hilo hasta tener respuesta de la memoria (¿Para que lo bloquearia si el Kernel detubiese su ejecucion hasta tener una respuesta?).

- El pedido de dump_memory no es bloqueante, pero aparece un problema el sistema operativo debería de esta constantemente pendiente de la respuesta de la memoria (entendiendo que abre y cierra comunicaciones solo para saber el estado de la operacion, lo cual no parece muy performante), y si esto lo hace por el mismo canal por el cual podria estar comunicandome al atender las distintas syscalls, esto podria llevar a que al leer una respuesta de memoria ante un pedido (crear proceso por ejemplo) se vea confundida con la respuesta que espero para el dump_memory, obligando a chequear en plana syscall el tipo de respuesta obtenida.

**Comment by AgustinHerzkovich** [comment]
Nosotros las peticiones de "inicializar y finalizar un proceso/hilo en memoria" las realizamos de manera sincrónica, es decir, obtenemos la respuesta de manera inmediata, pero en el caso de DUMP_MEMORY nos pareció que tal vez tenga más sentido que por un lado mande la solicitud a memoria, y en otra api reciba la respuesta cuando sea que memoria la mande.
Simplemente para agregar a lo anterior, saludos.

**Comment by nahuemazzeo** [comment]
Buenas! Como va? Primero creo que estamos en un problema @AgustinHerzkovich pregunto sobre como realizar algo en el TP realizado en Golang mientras que @NachoMoscatelli hizo consultas sobre el TP en C... Por favor, empecemos a taggear correctamente las dudas cuando se crean para evitar estas cosas.

Dicho eso...

@AgustinHerzkovich Lo que indica el enunciado es que el "hilo" que invoque esta Syscall va a pasar a bloqueado. Por lo que al pasar a bloqueado este hilo puede estar como 1 segundo o 2 minutos en bloqueado. Por lo que en el flow general del ciclo de ejecucion deberiamos manejarlo como cualquier otro, con dos apis. Un flow para invocar a memoria y dejar al hilo en blocked y otra api que permita desbloquear el hilo que lo invoco

@NachoMoscatelli Aca no entiendo mucho tu planteo. Aca lo que estamos bloqueando es el "hilo" y no el Kernel. Osea cuando llegue desde el CPU una solicitud de hacer un MEMORY_DUMP lo que deberiamos hacer es crear un hilo para atender esa solicitud y dejar al "hilo" en estado Blocked. Cuando el hilo resuelva su flow correspondiente con memoria ese hilo debe volver a pasar a Ready

Saludos.

**Comment by AgustinHerzkovich** [comment]
Muchas gracias por la respuesta, dejo el hilo abierto por si el otro compañero quiere agregar algo.
