### ISSUE TITLE
Grado de multiprogramacion 

### ISSUE THREAD

**Issue by JuanTerri** [sisoputnfrba/foro#4333]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas, mi duda es cuanto es el grado de multiprogramacion? Busque otros issues y no lo encontre.
Principalmente es si en ready cuantos procesos puede haber, va a estar solo los hilos del mismo proceso?

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by f-and** [comment]
Buenas, para este trabajo práctico no se maneja un esquema de grado de multiprogramación, el único límite para inicializar procesos es el espacio en memoria.
Saludos.-

**Comment by JuanTerri** [comment]
Okey, gracias.
