### ISSUE TITLE
Consulta severidad del checkpoint

### ISSUE THREAD

**Issue by GRogani** [sisoputnfrba/foro#4334]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buen día con el grupo tenemos una duda, estuvimos trabajando bastante en el tp pero no llegamos a cumplir con el 100% de los requerimientos del checkpoint, en caso de no llegar con estos estamos automaticamente bochados del tp? Porque si bien no llegamos a este checkpoint sentimos que podemos sacar el tp adelante, un saludo y muchas gracias. 

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by LeandroCarbajales** [comment]
Buenas!
Lo que corroboramos es que tengan el checkpoint taggeado antes de la fecha límite y con avances respecto al anterior.
Como indican las normas del trabajo práctico, recién en el 3er checkpoint podrían quedar fuera de la entrega final si por ejemplo no hubieran taggeado al menos 2 de ellos en tiempo y forma.
En resumen, sigan metiéndole hasta la última entrega si fuera necesario 💪 

Les aclara la duda?
Saludos!
        Lean

**Comment by GRogani** [comment]
Perfecto Lean, Gracias!

**Comment by GRogani** [comment]
Perfecto Lean, Gracias!
