### ISSUE TITLE
Consulta THREAD_CREATE

### ISSUE THREAD

**Issue by Elias318** [sisoputnfrba/foro#4336]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas, tengo una duda al recibir esta syscall (THREAD_CREATE). El enunciado me dice que cree el hilo y lo ponga en la cola de ready pero ese hilo deberia estar asociado a un proceso. Como se a que proceso asociarlo ? 

### 📔 Citas del enunciado/videos

THREAD_CREATE, esta syscall recibirá como parámetro de la CPU el nombre del archivo de pseudocódigo que deberá ejecutar el hilo a crear y su prioridad. Al momento de crear el nuevo hilo, deberá generar el nuevo TCB con un TID autoincremental y poner al mismo en el estado READY.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by SantiagoDopazo** [comment]
Hola Buenas,

Recorda que solo el propio proceso crea sus hilos por lo tanto al momento de ejecutar una Syscall del tipo `THREAD_CREATE`, el nuevo hilo que estas creando pertenece al proceso en ejecución, es decir el proceso que realizo `THREAD_CREATE` es el dueño del nuevo hilo.
En kernel deberían tener algún tipo de información de que hilo y que proceso se están ejecutando.

Para complementar te dejo un issue que habla del mismo tema: https://github.com/sisoputnfrba/foro/issues/4285.
