### ISSUE TITLE
pequeña duda sobre el quantum

### ISSUE THREAD

**Issue by nicolasvultaggio** [sisoputnfrba/foro#4337]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

El quantum es unico por cada cola de ready o es el mismo para todas las colas multinivel?
si fuera el segundo caso, como obtenemos los distintos quantum para cada cola en el archivo de configuracion?

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by SantiagoDopazo** [comment]
Hola Buenas,

El Quantum es el mismo para todas las colas sin importar su prioridad.

Te mando un issue anterior: https://github.com/sisoputnfrba/foro/issues/4240

Saludos!

**Comment by nicolasvultaggio** [comment]
gracias!
