### ISSUE TITLE
Duda READ_MEM lado CPU y lado Memoria

### ISSUE THREAD

**Issue by IgnacioLapko** [sisoputnfrba/foro#4338]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

Buenos dias!

Los molestaba con una consulta del enunciado. Si bien del lado del CPU la instruccion READ_MEM solo involucra a la direccion logica; ¿por que del lado de memoria debo acceder a la direccion fisica? ¿Tenemos que hacer la traduccion de direccion logica a fisica de igual manera?
Mas que nada, porque en el caso de WRITE_MEM del lado del CPU si nos solicita realizar dicha traduccion para luego ser usada por el WRITE_MEM de Memoria.

Desde ya muchas gracias!

### 📔 Citas del enunciado/videos

Pág. 16 - Execute
READ_MEM (Registro Datos, Registro Dirección): Lee el valor de memoria correspondiente a la Dirección Lógica que se encuentra en el Registro Dirección y lo almacena en el Registro Datos.
WRITE_MEM (Registro Dirección, Registro Datos): Lee el valor del Registro Datos y lo escribe en la dirección física de memoria obtenida a partir de la Dirección Lógica almacenada en el Registro Dirección.

Pág. 20 - Comunicación con CPU
READ MEM
Se deberá devolver el valor correspondiente a los primeros 4 bytes a partir del byte enviado como dirección física dentro de la Memoria de Usuario.
WRITE MEM
Se escribirán los 4 bytes enviados a partir del byte enviado como dirección física dentro de la Memoria de Usuario y se responderá como OK.

### 💭 Soluciones posibles

Una posible solucion es que READ_MEM traduzca la direccion logica a fisica en algun momento utilizando el MMU para que el READ_MEM del lado de memoria pueda devolver lo que corresponde.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by LeandroCarbajales** [comment]
Buenas!
En ambos casos la MMU(CPU) debe traducir la dirección lógica a física para poder pedírselo a la Memoria.
Evidentemente se nos pasó y no habían quedado iguales en el enunciado, ahí lo actualicé :)

**Comment by IgnacioLapko** [comment]
Buenos días Leandro, genial! Muchas gracias! Cierro el issue.
