### ISSUE TITLE
errores en memory dump

### ISSUE THREAD

**Issue by nicolasvultaggio** [sisoputnfrba/foro#4340]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Si un proceso falla por memory dump-> sí o si debemos generar una interrupcion r en caso de que  otro hilo del mismo proceso este ejecutando en cpu? porque yo tenia entendido que las unicas interrupciones pueden ser las de quantum?

entiendo que si el algoritmo es fifo o prioridades deberemos generar una de estas interrupciones, pero 
podria ser valida una implementación en la que si el algoritmo es multicolas, no se envía interrupción de fallo por memory dump y esperamos a que el proceso se desaloje por quantum? es algo que se probará? me conflictúa mucho el hecho de que puedan haber dos tipos de interrupciones en un mismo algoritmo, por eso pregunto

se va a testear el hecho de que dos hilos de un mismo proceso fallen por memory dump? o podemos suponer que solo uno MAXIMO va a fallar

**Comment by LeandroCarbajales** [comment]
Buenas!
Te respondo primero la última duda que es más sencilla de responder. 

> se va a testear el hecho de que dos hilos de un mismo proceso fallen por memory dump? o podemos suponer que solo uno MAXIMO va a fallar

Lo más probable es que si el memory_dump de un hilo falla, fallen todos los siguientes memory_dump de los hilos de ese mismo proceso dado que comparten el mismo espacio de memoria. Sin embargo, dado que el fallo de un memory_dump finaliza a todo el proceso, esto no debería ocurrir.

> Si un proceso falla por memory dump-> sí o si debemos generar una interrupcion r en caso de que otro hilo del mismo proceso este ejecutando en cpu? porque yo tenia entendido que las unicas interrupciones pueden ser las de quantum?

Creo que es un caso que no está contemplado en el enunciado. Dejemos este issue abierto y durante la semana te confirmo bien si es un caso posible de prueba. Si lo fuera tendríamos que agregar ese caso en una errata para que quede claro el comportamiento esperado.

**Comment by nicolasvultaggio** [comment]
okey! no hay problema

**Comment by nicolasvultaggio** [comment]
solo para confirmar entonces? el memory dump implica replanificacion de otro hilo entonces? o sea, no es que espero a la respuesta de la memoria para replanificar, debere realizar el pedido paralelamente y despues que llegue cuando llegue.
O sea, esta respuesta de memory dump puede llegar en cualquier momento, es imposible determinar cuando?
conviene por cada desalojo preguntar si finalizo esta peticion? o existe alguna manera recomendable para manejar estos casos?

**Comment by LeandroCarbajales** [comment]
Buenas!
Correcto, el memory dump bloquea al hilo que la realiza por lo que se replanifica en ese momento para que ejecute otro. Luego la respuesta de la memoria puede llegar en cualquier momento, por lo que recomiendo que manejen esa petición en un hilo aparte que se quede esperando la respuesta de Memoria, una vez respondido lo mueven a exit o ready según corresponda.

**Comment by LeandroCarbajales** [comment]
Buenas!
Te confirmo por el caso del error en memory dump mientras hay otro hilo del mismo proceso en ejecución que no se tienen que preocupar por ese caso. Trátenlo como mejor lo consideren, no será un caso de prueba que busquemos.

Saludos!
      Lean

**Comment by LeandroCarbajales** [comment]
@nicolasvultaggio 
Te sirvieron las respuestas? Quedó alguna duda?
