### ISSUE TITLE
Syscalls

### ISSUE THREAD

**Issue by JuanTerri** [sisoputnfrba/foro#4341]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas, la duda que tengo es si kernel tiene que trabajar como servidor o si cuando hay una Syscalls CPU la va a mandar por la conexión que ya esta establecida de "cpu_interrupt".

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by LeandroCarbajales** [comment]
Buenas!
Cito al enunciado:

`Una vez seleccionado el siguiente hilo a ejecutar, se lo transicionará al estado EXEC y se enviará al módulo CPU el TID y su PID asociado a ejecutar a través del puerto de dispatch, quedando a la espera de recibir dicho TID después de la ejecución junto con un motivo por el cual fue devuelto.`

Algunos de esos "motivos" por lo cuales el Kernel recibiría dicho TID-PID a través del puerto dispatch son las syscalls.

Te aclara la duda?
Saludos!
     Lean

**Comment by JuanTerri** [comment]
Perfecto muchas gracias.
