### ISSUE TITLE
Recepcion pedido de instrucciones por parte de CPU a memoria

### ISSUE THREAD

**Issue by Ranico1** [sisoputnfrba/foro#4342]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

Buenos dias. Queria consultar si a la hora de pedir una instruccion CPU ademas de mandar el TID y el PC, manda el PID del proceso que se esta ejecutando en el momento. En el enunciado no menciona el envio del mismo pero basandonos en eso no seria posible saber a que proceso pertenece dicho TID ya que puede haber TIDs iguales de distintos procesos y no sabriamos a cual esta asociado. Saludos y desde ya muchas gracias.

### 📔 Citas del enunciado/videos

Obtener instruccion
Deberemos devolverle la instrucción correspondiente al hilo y al Program Counter recibido. Por ejemplo, si el hilo 3 del proceso 1 pide la instrucción número 4, deberemos devolver la 5ta instrucción del pseudocódigo correspondiente a ese hilo.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by GadStam** [comment]
Hola! Correcto, si ustedes lo necesitan para poder diferenciar a que proceso pertenece cada hilo esa es una forma de identificarlos, la implementación queda en ustedes. Saludos!

**Comment by Ranico1** [comment]
Muchas gracias. Una consulta mas, el delay de respuesta es solo para las peticiones hechas por CPU  o para las de los demas modulos tambien?

**Comment by GadStam** [comment]
solo para las peticiones hechas por CPU. Saludos!
