### ISSUE TITLE
Duda sobre el archivo bloques.dat en FileSystem

### ISSUE THREAD

**Issue by zBlooDy** [sisoputnfrba/foro#4343]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

Buenas, tenia una dudas acerca del enunciado cuando se habla de Esquema de Archivos. 
1) Se menciona que bloques.dat tendra tanto los bloques de datos como los bloques de indices, no termino de comprender bien a que hacen referencia o de que tipo son estos "bloques de datos" y "bloques de indices". 
2) Por ahora entendi que bitmap.dat va a ser un archivo de bytes, en el que cada bite representa un bloque (no estoy seguro si es de datos o de que seria) y segun su valor estara ocupado o libre.
3) Por ultimo, cuando quiera leer el archivo bloques.dat y bajarlo a una estructura, no estoy seguro como se podria diferenciar cual es un bloque de indice o de datos.

Muchas graciass

### 📔 Citas del enunciado/videos

![image](https://github.com/user-attachments/assets/866d6a69-f9b3-42d9-8707-7388487f21f1)

Pagina 25 del Enunciado

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by GadStam** [comment]
Hola! Contesto tus tres preguntas de manera general.
Vos vas a tener un archivo en el cual se va a guardar información propia del archivo, ese es el bloques.dat, y por otro lado vas a tener tu archivo bitmap.dat el cual va a estar estrechamente relacionado uno con el otro. Te doy un ejemplo para que quede mas claro: si tengo que escribir "hola como estas" y este me ocupa 3 bloques, lo que voy a hacer es escribir en bloques.dat estos 3 bloques con ese contenido y en mi bitmap.dat voy a marcar 3 bloques como ocupados. Entonces en el bitmap vas a saber quienes están ocupados y en el bloques.dat vas a tener el contenido. Espero que con esto haya quedado un poco mas claro!

**Comment by zBlooDy** [comment]
Hola Gad, como andas? Creo que voy entendiendo con el ejemplo que me diste pero me quedo la siguiente duda.
En el ejemplo decís que el contenido lo guardo en bloques.dat y después los 3 bloques los marco como ocupados en bitmap.dat, lo que no termino de entender es el vínculo de esos "bloques de índice" o a qué se refiere ese término.

Disculpa las molestias y gracias 🫂

**Comment by GadStam** [comment]
El bloque índice hace referencia a donde comienza el contenido del archivo en el bloques.dat. Si dice que "index_block":10, su contenido comienza en el bloque 10 y luego según el size y el tamaño de bloques dados por la configuración, tendrán que ver cuantos bloques ocupa el archivo. Acá no hay molestias, estamos para ayudar, Buen finde!

**Comment by iago64** [comment]
@zBlooDy Cómo va? ¿Te sirvieron las respuestas de Gad?

Saludos.-

**Comment by zBlooDy** [comment]
Buenas! Sisi me sirvieron, había dejado el issue abierto por si me surgía alguna duda, voy a seguir viendo el tema de los archivos y si tengo otra duda puntual abro otro issue. Muchas gracias!
