### ISSUE TITLE
Campos de un struct de tcb en memoria

### ISSUE THREAD

**Issue by inaaranza** [sisoputnfrba/foro#4344]
### 🛠️ Lenguaje

C

Buenas!

Estoy trabajando en el módulo memoria y estoy usando un struct para representar los tcbs. Dentro de este struct tengo los campos de TID, PID, registros, base y tamaño (estos ultimos 2 campos tienen los mismos valores para todos los tcbs que corresponden a un mismo PID), pero no uso ninguna struct para representar pcbs. Mi duda es la siguiente: ¿está bien que solo tenga una estructura para hacer referencia para los tcbs y no tenga ninguna para los pcbs? ¿Es obligatorio tener un struct para representar a los pcbs en la memoria? Porque por la manera en la que lo tengo planteado solo manejo un struct de tcb y no hace falta que maneje pcbs, lo cual desconozco si es obligatorio para el TP o no.
Una manera que se me ocurrió para usar pcbs y tcbs es tener un struct pcb con 2 campos: PID y una lista de tcbs. De esta manera asocio un pcb a muchos tcbs. Decidí no ir por este lado por un tema de que es más simple manejar todo dentro de un struct tcb, pero reitero que no sé si es lo correcto en el TP.
Me quedo atento a la respuesta.

Saludos!

**Comment by nahuemazzeo** [comment]
Hola @inaaranza! Inicialmente con el struct que tenes deberias poder manejar el 100% de la funcionalidad que requiere el Trabajo Practico. Como planteaste tu implementacion es correcto que no tengas un struct de PCB. 

Saludos.

**Comment by inaaranza** [comment]
Muchas gracias nahue!
Abrazo!
