### ISSUE TITLE
Dudas sobre memoria (hilos y espacio usuario)

### ISSUE THREAD

**Issue by urielmayo** [sisoputnfrba/foro#4345]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas, Tengo una dudas. 
Un proceso puede no tener hilos? en ese caso, que TID se mandaría cuando pedimos el contexto de ejecución o queremos escribir memoria? Ejemplo PID 4, TID ¿0? ¿-1? 
Otra duda que tengo es si, al crear un proceso, tiene que haber si o si espacio para asignarle en el espacio de usuario no? Es decir. Si por ejemplo yo tengo una esquema de partición fija de 5 particiones, ya tengo creado 5 procesos y me llaga una solicitud para crear un proceso nuevo. Ese proceso no debería alojarse, correcto?

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by f-and** [comment]
Buenas Uriel, 

Un proceso ***siempre*** empieza con un hilo de TID 0. Además, siempre que se envíe algo a ejecutar eso va a tener un TID asociado, nunca se va a mandar un proceso solo a ejecutar, por lo que nunca vas a tener el problema de no tener un TID.

Para la segunda consulta (y en realidad en parte la primera) cito de la parte de creación de proceso del enunciado:

> Se tendrá una cola NEW [...] al llegar un nuevo proceso a esta cola y la misma esté vacía se enviará un pedido a Memoria para inicializar el mismo. Si la respuesta es positiva, se crea el hilo 0 de ese proceso, se lo pasa al estado READY y se sigue la misma lógica con el proceso que sigue. Si la respuesta es negativa (***ya que la Memoria no tiene espacio suficiente para inicializarlo***) se deberá esperar la finalización de otro proceso para volver a intentar inicializarlo.
Al llegar un proceso a esta cola y haya otros esperando, el mismo simplemente se encola.

Espero haber contestado tu consulta.
Saludos.-
