### ISSUE TITLE
Duda sobre EXECUTE en Kernel 

### ISSUE THREAD

**Issue by Elias318** [sisoputnfrba/foro#4346]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas, queria consultar si el "motivo" que Kernel tiene que esperar de CPU seria solo las syscalls(DUMP_MEMORY
IO (Tiempo)
PROCESS_CREATE, THREAD_CREATE, THREAD_JOIN, THREAD_CANCEL, etc... ) y cuando kernel desaloje el hilo ? O me estoy olvidando de algun otro caso.
Gracias!

### 📔 Citas del enunciado/videos

_Ejecución
Una vez seleccionado el siguiente hilo a ejecutar, se lo transicionará al estado EXEC y se enviará al módulo CPU el TID y su PID asociado a ejecutar a través del puerto de dispatch, quedando a la espera de recibir dicho TID después de la ejecución junto con un motivo por el cual fue devuelto.
En caso que el algoritmo requiera desalojar al hilo en ejecución, se enviará una interrupción a través de la conexión de interrupt para forzar el desalojo del mismo.
Al recibir el TID del hilo en ejecución, en caso de que el motivo de devolución implique replanificar, se seleccionará el siguiente hilo a ejecutar según indique el algoritmo. Durante este período la CPU se quedará esperando._

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

En principio vos tenes que poder tipificar los motivos de desalojo, algunos van a ser syscalls, otro puede ser que desde kernel le mandaste el fin de quantum o puede ser algún error en la MMU, que sería el Segmentation Fault, por las dudas te recomiendo que lo hagas de manera modular cosa que si te faltó algún motivo de desalojo no te vuelvas loco para agregarlo.

Saludos.-

**Comment by Elias318** [comment]
Perfecto Gracias!
