### ISSUE TITLE
Bloqueo de TCB al esperar respuesta del Kernel

### ISSUE THREAD

**Issue by zakerik10** [sisoputnfrba/foro#4347]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Hola, tenemos una duda con respecto a qué pasa con el TCB en ejecución cuando se quiere ejecutar ciertas instrucciones.

Cuando el proceso ejecuta CREATE_PROCESS, el proceso tiene que continuar su ejecución sin que le importe si se pudo crear o no el proceso? Refiriéndonos en el caso de que no se cree el proceso, es que no hay espacio en memoria, y el proceso nuevo queda en la cola de NEW

Y en los casos de MUTEX_LOCK, el TCB que se esta ejecutando, queda esperando a que el Kernel le confirme si hay recurso o no.
Si hay, continua ejecutando, y si no, se bloquea

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Si, no importa si el proceso nuevo queda en new o avanza, en el momento que vos dejaste el proceso nuevo en NEW volves a ejecutar normalmente y es problema del planificador de largo plazo ver cuando el proceso entra.

2.- Me parece que la estas complicando un poco de mas, ya que para la CPU sería mas simple devolver el par PID / TID al kernel para que este haga lo que tenga que hacer en la syscall y luego si el kernel lo considera mande el mismo par PID / TID a la CPU o mande otro porque el TID que solicito el mutex se bloqueo o lo tuviste que finalizar por pedir un recurso inválido.

Saludos.-
