### ISSUE TITLE
Duda sobre syscalls e interrupt

### ISSUE THREAD

**Issue by BenjaminAlegre** [sisoputnfrba/foro#4348]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Hola buenas! Tenia una duda sobre el enunciado. Segun el enunciado CPU tiene un Check Interrupt que atiende las interrupciones de parte de kernel. Cual es el origen de esas interrupciones? Nosotros pensamos que el orden seria: cpu lee una instruccion que es una syscall, envia al kernel por la conexion dispatch esa syscall, entonces kernel deberia mandar a cpu una interrupcion?

### 📔 Citas del enunciado/videos

>Check Interrupt
En este momento, se deberá chequear si el Kernel nos envió una interrupción al TID que se está ejecutando, en caso afirmativo, se actualiza el Contexto de Ejecución en la Memoria y se devuelve el TID al Kernel con motivo de la interrupción. Caso contrario, se descarta la interrupción.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by GadStam** [comment]
Buenas @BenjaminAlegre! Es correcto esto que decís. Cuando la CPU vea una instrucción que genera interrupción como por ejemplo "IO_GEN_SLEEP" le deberá avisarle al Kernel para que mande interrupción a CPU y atienda a la misma. Cualquier duda podes consultar, saludoss!

**Comment by LeandroCarbajales** [comment]
Buenas!
Cito la parte relevante del enunciado de Kernel en "Planificador de Corto Plazo"

> En caso que el algoritmo requiera desalojar al hilo en ejecución, se enviará una interrupción a través de la conexión de interrupt para forzar el desalojo del mismo.

Es decir, el módulo Kernel enviará mensajes a través del puerto interrupt a CPU cuando el mismo lo considere según el algoritmo (en este caso, para desalojar por quantum o prioridades). Esto es independiente a si la CPU ejecuta syscalls o no.
Desde el lado de la CPU, el procedimiento es el mismo que si ejecutara una syscall, le devuelve el TID a Kernel con motivo de la interrupción.

**Comment by BenjaminAlegre** [comment]
Genial, Me queda mas claro, muchas gracias!

**Comment by BenjaminAlegre** [comment]
Genial, me queda mucho mas claro. Gracias!
