### ISSUE TITLE
Duda conceptual sobre Planificadores y las Syscalls

### ISSUE THREAD

**Issue by David-Schmidt02** [sisoputnfrba/foro#4349]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenos días, como están?

Me plante una situación respecto al Planificador de Largo Plazo y frené el código para poder pensarlo mejor pero no sé si es correcto.
Por lo que entiendo en el enunciado, la única forma en la que se crean los procesos es a través de la Syscall "PROCESS_CREATE", verificando que haya espacio en memoria para poder crearlos y demás. Si bien ya teníamos creadas las syscalls, no las teníamos relacionadas directamente con el planificador, es correcto que se llame a la funcion/hilo que corre el "Planificador de Largo Plazo" desde la misma syscall? 
Si bien hay otras situaciones en las que se invocan a los planificadores, como cuando vuelve un hilo por fin de quantum, que implica una replanificacion (y por ende correr la funcion/hilo del "Planificador de Corto Plazo" en el caso de CMN) o como cuando el proceso finaliza porque todos sus hilos finalizaron (Largo Plazo), etc. ¿es correcto llamar a ambos planificadores desde las syscalls?

Sé que quizás puede parecer una obviedad, pero recién ahora cuando me plantee todas las situaciones en que se llaman a cada planificador terminé dándome cuenta que la mayor cantidad de solicitudes/llamadas que reciben, parten de las syscalls. También dudo porque son dos partes del enunciado "diferentes" las relacionadas con los planificadores y las de las syscalls. 

Desde ya muchas gracias.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! ¿Cómo va?

Por desgracia la respuesta es depende.
Depende de que tengan armado adentro del planificador de largo plazo, si es el que se encarga de llamar a la memoria y checkear si puede entrar el proceso, estaría bien que lo llamen al momento de ejecutar PROCESS_CREATE.
Respecto al planificador de corto plazo, conceptualmente, debería ejecutar cada vez que tenes que mandar un hilo a ejecutar a la CPU, con lo cual, ahi tenes varios momentos para que ejecute.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @David-Schmidt02 ! ¿Les sirvió la respuesta de Dami? Saludos

**Comment by David-Schmidt02** [comment]
¡Buenas!
Sí, nos sirvió bastante, como es mi primer "issue" no recordé cerrarlo. Saludos
