### ISSUE TITLE
Consulta syscall IO

### ISSUE THREAD

**Issue by AgustinaGuitman** [sisoputnfrba/foro#4350]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas! les quería consultar si cuando el hilo en ejecución termina de hacer io este sigue siendo el hilo en ejecución o si se tiene que poner en ejecución al siguiente hilo según el algoritmo. 
Desde ya muchas gracias

### 📔 Citas del enunciado/videos

Entrada Salida
Para la implementación de este trabajo práctico, el módulo Kernel simulará la existencia de un único dispositivo de Entrada Salida, el cual atenderá las peticiones bajo el algoritmo FIFO. Para “utilizar” esta interfaz, se dispone de la syscall IO. Esta syscall recibe como parámetro la cantidad de milisegundos que el hilo va a permanecer haciendo la operación de entrada/salida.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by LeandroCarbajales** [comment]
Buenas!
Quizás no está del todo explícito en el enunciado, pero funcionaría similar a como en los ejercicios de Planificación que se hacen en clases, parciales, etc.
Al llamar la syscall de IO, el hilo se bloquea hasta que finalice la operación, luego se encola en ready hasta que vuelva a ser elegido por el planificador de corto plazo.

Te resuelve la duda?
Saludos!
    Lean

**Comment by AgustinaGuitman** [comment]
Si perfecto, muchísmas gracias!
Saludos
