### ISSUE TITLE
built project

### ISSUE THREAD

**Issue by juanjoseninaquempe** [sisoputnfrba/foro#4351]
### 🖋️ Descripción

20:51:08 **** Incremental Build of configuration Default for project tp0 ****
make all 
make: *** No rule to make target 'all'.  Stop.
"make all" terminated with exit code 2. Build might be incomplete.

20:51:08 Build Failed. 1 errors, 0 warnings. (took 184ms)

### 📔 Citas del enunciado/videos

![Captura](https://github.com/user-attachments/assets/03636710-9c5e-443e-aec4-014edae09337)

### 💭 Soluciones posibles

![Captura](https://github.com/user-attachments/assets/9d8220e9-e2e6-4a81-9c39-314730a1c1c8)

no me deja crear el BINARIO(BINARIES)  para compilar .

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Si importas las 2 carpetas en eclipse no te va a funcionar, deberías importar cada proyecto, server y cliente, por separado.
En el caso del TP0, el mismo tiene un archivo tp0.code-workspace que sirve para que puedas abrirlo con Visual Studio Code como esta en el enunciado del TP0: https://docs.utnso.com.ar/primeros-pasos/tp0#abrir-desde-visual-studio-code

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @juanjoseninaquempe ! ¿Les sirvió la respuesta de Dami? Saludos

**Comment by juanjoseninaquempe** [comment]
![image](https://github.com/user-attachments/assets/d64c24a5-8954-418e-9793-897af1c5272a)

![image](https://github.com/user-attachments/assets/5386d3bf-4421-4c4b-b629-35ef75dbb9e4)
hola, disculpen . tengo ese error en la terminal ,desde ya gracias

**Comment by juanjoseninaquempe** [comment]
> ¡Buenas @juanjoseninaquempe ! ¿Les sirvió la respuesta de Dami? Saludos
si

**Comment by iago64** [comment]
@juanjoseninaquempe Te pido que por favor **no subas mas capturas de pantalla**, ya que el buscador de github no puede interpretar el texto que esta en las capturas, si el error lo podes copiar y pegar en texto hacelo, y lo mismo para el código, ya que si quisiera replicar el error no puedo hacerlo.

Respecto al error, te pregunto, ¿Guardaste los cambios en el archivo y recompilaste la solución?

Saludos.-

**Comment by juanjoseninaquempe** [comment]
como lo hago?

**Comment by RaniAgus** [comment]
Se guarda con el universalmente conocido `Ctrl`+`S` y se compila de la misma forma en que se encuentra explicado en la [guía de Eclipse](https://docs.utnso.com.ar/guias/herramientas/eclipse#como-importar-el-tp-en-eclipse-ide) 😌

**Comment by juanjoseninaquempe** [comment]
[INFO] 13:59:05:687 CL_LOG/(221044:221044): Hola! Soy un log
[0m[INFO] 13:59:05:690 CL_LOG/(221044:221044): VALOR leido de la config: valor
[0m> 

lo compile y me dio así

**Comment by RaniAgus** [comment]
¡Buenísimo! Recuerden que si la duda ya fue resuelta pueden cerrar el issue 👮🏻‍♂️

**Comment by juanjoseninaquempe** [comment]
utnso@utnso:~/tp0/client/bin$ ./client
[INFO] 14:12:32:042 CL_LOG/(221354:221354): Hola! Soy un log
Error al intentar cargar el config: No such file or directory
utnso@utnso:~/tp0/client/bin$ 


pero en la terminal persiste ese error,disculpa

**Comment by RaniAgus** [comment]
Para ello te recomiendo chusmear la siguiente guía: [Rutas Relativas y Absolutas](https://docs.utnso.com.ar/guias/consola/rutas).

**Comment by juanjoseninaquempe** [comment]
Rani disculpa la molestia, pero el ./server no me agarra lo que pongo en ./client 
![image](https://github.com/user-attachments/assets/1ef88664-8066-4f5d-b430-e457aa9bb6db)

**Comment by RaniAgus** [comment]
En los casos en los cuales el código no hace lo que nosotros esperábamos, siempre recomiendo comenzar por utilizar el [debugger](https://docs.utnso.com.ar/guias/herramientas/debugger), una herramienta que nos permite ejecutar línea por línea monitoreando el estado de todas las variables.
