### ISSUE TITLE
Ruta del bitmap.dat y bloques.dat

### ISSUE THREAD

**Issue by MartinSintas** [sisoputnfrba/foro#4352]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

Buenas! tenía una pregunt(ont)a acerca de las carpetas donde se van a alojar los archivos bitmap.dat y bloques.dat ya que en el enunciado figuran 2 distintas y en el archivo de config solo figura 1 :0 
Quería saber si está bien que sean carpetas distintas o si fue un error al redactarse el enunciado. Desde ya muchas gracias!

### 📔 Citas del enunciado/videos

bitmap.dat: Este archivo se encontrará directamente en la carpeta MNT_DIR

bloques.dat:  Este archivo se encontrará directamente en la carpeta MOUNT_DIR

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Van en el mismo directorio, fue un error al redactar la version de Go.

Saludos.-

**Comment by MartinSintas** [comment]
Genial Dami, muchas gracias por la aclaración!
