### ISSUE TITLE
Consulta estructura contexto de hilos

### ISSUE THREAD

**Issue by regueiranehuen** [sisoputnfrba/foro#4353]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas noches. Quisiera saber si se puede agregar como registro del contexto de ejecución de un hilo al PID de su proceso asociado, para así evitar problemas buscando cual es su PID asociado.
La idea con la que estuvimos trabajando por ahora es una lista global de contextos por cada proceso. 
Dentro del contexto de cada proceso, hay una lista de los contextos de sus hilos.
En código, se ve así:
```c
t_list*lista_contextos_pids;
typedef struct{
    int pid;
    t_list*contextos_tids;
    uint32_t base; 
    uint32_t limite; 
}t_contexto_pid;

typedef struct{
    uint32_t AX;
    uint32_t BX;
    uint32_t CX;
    uint32_t DX;
    uint32_t EX;
    uint32_t FX;
    uint32_t GX;
    uint32_t HX;
    uint32_t PC;
}t_registros_cpu; 

typedef struct{
    int tid;
    t_registros_cpu*registros;
}t_contexto_tid;
``` 
Una de las ideas que tengo es simplemente agregar el PID a la estructura t_contexto_tid, y la otra es la siguiente, guardando en memoria dos lista globales de contextos: Una para los hilos y otra para los procesos

```c
t_list*lista_contextos_pids;
t_list*lista_contextos_tids;
typedef struct{
    int pid;
    uint32_t base; 
    uint32_t limite; 
}t_contexto_pid;

typedef struct{
    uint32_t AX;
    uint32_t BX;
    uint32_t CX;
    uint32_t DX;
    uint32_t EX;
    uint32_t FX;
    uint32_t GX;
    uint32_t HX;
    uint32_t PC;
}t_registros_cpu; 

typedef struct{
    int pid;
    int tid;
    t_registros_cpu*registros;
}t_contexto_tid;


``` 

Hay alguna alternativa mejor que otra? Saludos!

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Si, no hay problema con que agreguen cosas en las estructuras administrativas, por eso les dejamos la libertad de que lo tengan de la forma que quieran en la "Memoria de Sistema"

Saludos.-

**Comment by regueiranehuen** [comment]
> Buenas! Cómo va?
> 
> Si, no hay problema con que agreguen cosas en las estructuras administrativas, por eso les dejamos la libertad de que lo tengan de la forma que quieran en la "Memoria de Sistema"
> 
> Saludos.-

Perfecto, muchas gracias!
