### ISSUE TITLE
Consulta consigna "contenido actual de la memoria del proceso"

### ISSUE THREAD

**Issue by Bru-Nicolas-FRBA** [sisoputnfrba/foro#4356]
### 🖋️ Descripción

Hola!
Tenemos una duda respecto al Memory Dump:

Cuando en la consigna habla del "contenido actual de la memoria del proceso" se refiere al contexto de ejecución?

O a TODO lo que tengamos de ese proceso guardado (refiriéndose a la estructura de datos _pcb.T_PCB_)?

### 📄 Código relevante

_Al momento de recibir la operación de memory dump el módulo memoria deberá solicitar al módulo FileSystem la creación de un nuevo archivo con el tamaño total de la memoria reservada por el proceso y debe escribir en dicho archivo **todo el contenido actual de la memoria del proceso**. El archivo debe llamarse “<PID>-<TID>-<TIMESTAMP>.dmp”.
En caso de que el FileSystem responda con error, se devolverá el mismo mensaje al Kernel, en caso positivo, se responde como OK._

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by f-and** [comment]
Buenas Nicolas! Cuando nos referimos a la memoria actual del proceso nos referimos a los datos que se encuentran en el [espacio de usuario](https://docs.google.com/document/d/1KloOXfXQb_c1S3PKDEEywnArX9YB3aApqGVmpNgv9_Q/edit?tab=t.0#heading=h.2slmahz8lnjg) de dicho proceso, no del pcb y tcbs (aunque necesitas un par de esos datos para el nombre del archivo generado).

**Comment by Bru-Nicolas-FRBA** [comment]
Muchas gracias por la respuesta profe
