### ISSUE TITLE
DUMP_MEMORY

### ISSUE THREAD

**Issue by fernandodanielmaqueda** [sisoputnfrba/foro#4357]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas, ¿cómo va?

Quisiera consultar si es correcto que por cada syscall `DUMP_MEMORY` en Kernel se haga un `pthread_create` cuya rutina se encargue de realizar la conexión efímera con memoria para hacerle la solicitud quedándose bloqueado (con `recv`) a la espera de la respuesta con el resultado de la operación y luego realizar las acciones pertinentes (llevar el hilo a READY o el proceso a EXIT) y terminar, ó si esperaban que hubiera una cantidad predeterminada de hilos dedicados (ej. uno que envíe las solicitudes y el otro que quede a la espera de las respuestas) que permanezcan durante todo el ciclo de vida del programa (aunque ésto me parece improbable ya que por cada solicitud se crea una nueva conexión/socket y habría que bloquearse con `recv`).

Saludos.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by nahuemazzeo** [comment]
Hola @fernandodanielmaqueda. Es correcta la solucion que estas plantenando

**Comment by fernandodanielmaqueda** [comment]
Excelente. ¡Gracias!
