### ISSUE TITLE
Recepción de las syscalls

### ISSUE THREAD

**Issue by regueiranehuen** [sisoputnfrba/foro#4358]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas noches. Quisiera saber si el Kernel recibe las syscalls a ejecutar por el socket de dispatch o por el socket de interrupt. Gracias!

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Esta duda fue resuelta en el issue #4262 

Saludos.-

**Comment by regueiranehuen** [comment]
> Buenas! Cómo va?
> 
> Esta duda fue resuelta en el issue #4262
> 
> Saludos.-

Perfecto, gracias!
