### ISSUE TITLE
Duda sobre la syscal THREAD_JOIN

### ISSUE THREAD

**Issue by ValenGriggio18** [sisoputnfrba/foro#4359]
### 🖋️ Descripción

Queríamos saber como manejar la siguiente situación: Nosotros tenemos una cola de bloqueados, tal que al ejecutarse la syscall THREAD_JOIN el hilo pasará a estado BLOCKED y lo moveremos a esa cola hasta que el TID pasado por parámetro finalice. Supongamos que hay otro hilo que ejecuta la syscall THREAD_JOIN y también lo debemos mover a la cola de bloqueados, en ese caso tendríamos dos hilos en la cola de bloqueados. Suponiendo que termina primero el THREAD_JOIN ejecutado por el segundo hilo que entró a la lista de bloqueados, lo sacamos de la cola de bloqueados y lo movemos a ready inmediatamente sin importar que tenga un hilo que llegó antes a la cola? o tendríamos que esperar a que primero termine el primero en entrar para que se desbloquee ese y luego desbloquear el que terminó primero?
Por como está expresado en el enunciado, nosotros suponemos que en este caso aunque el hilo no esté primero en la cola de bloqueados, debemos cambiar su estado y moverlo a la cola de ready inmediatamente sin respetar el orden de la cola, es decir tendríamos que encontrar algún tipo de algoritmo que nos permita recorrer la cola de bloqueados en busca de este hilo para que cuando lo encuentre lo mueva inmediatamente ignorando el orden de llegada de los hilos a dicha cola. Está bien esta suposición? o la cola de bloqueados debería funcionar por FIFO normalmente y en caso de que un hilo que no está primero deba desbloquearse espere a que se desbloqueen los otros.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by RaniAgus** [comment]
¡Buenas!

> Por como está expresado en el enunciado, nosotros suponemos que en este caso aunque el hilo no esté primero en la cola de bloqueados, debemos cambiar su estado y moverlo a la cola de ready inmediatamente sin respetar el orden de la cola, es decir tendríamos que encontrar algún tipo de algoritmo que nos permita recorrer la cola de bloqueados en busca de este hilo para que cuando lo encuentre lo mueva inmediatamente ignorando el orden de llegada de los hilos a dicha cola. Está bien esta suposición?

Sí, está bien la suposición: lo único que el hilo debe esperar es a que el otro hilo finalice. Otras esperas de otros hilos no deberían afectarlo.

Recordemos que la mayoría de los ejercicios de plani de la parte teórica parten asumiendo que existe un **único** dispositivo de Entrada/Salida que se planifica de forma FIFO, como podría ser una impresora (de ahí la "cola de bloqueados"), pero esto es una simplificación: en la vida real hay muchos dispositivos de Entrada/Salida y otros recursos para los cuales un hilo puede bloquearse y no entran todos a la misma cola común, sino que cada uno simplemente pasa al estado BLOCKED hasta que ese recurso esté disponible para ese hilo.

De hecho, hasta en el mismo enunciado verán que solo se habla de _transicionar al estado BLOCKED_, en ningún lado se asume que haya que agregarlos a una cola común de bloqueados.

Sino imaginate cómo sería un sistema operativo que no te deje mostrar un input del teclado hasta que no se termine de imprimir un documento en la impresora: no tendría sentido atender todas las I/O una a una. Lo mismo aplica para hilos: ¿por qué debería esperar a que otro JOIN de otro hilo que no me interesa finalice? No sería lo más óptimo 😅 

Saludos

**Comment by ValenGriggio18** [comment]
Perfecto! muchísimas gracias por la aclaración, tiene mucho sentido lo de no tener una cola común de bloqueados, saludos.
