### ISSUE TITLE
Read y Write de memoria y algunos chequeos

### ISSUE THREAD

**Issue by inaaranza** [sisoputnfrba/foro#4360]
### 🛠️ Lenguaje

C

Buenas!

Tengo una duda sobre la lectura y escritura de la memoria. Por lo que dice el enunciado, por el lado del read, dice "Se deberá devolver el valor correspondiente a los primeros 4 bytes a partir del byte enviado como dirección física" y en el write dice "Se escribirán los 4 bytes enviados a partir del byte enviado como dirección física dentro de la Memoria de Usuario". Por lo que entiendo solo se lee o se escribe de a 4 bytes, pero en los logs minimos y obligatorios pide el "tamaño". El tamaño de lo que se lee o escribe no va a ser 4? O habla del tamaño de la particion sobre la cual se esta escribiendo/leyendo?

También, viendo los logs minimos y obligatorios, vi que hay un log de instruccion en los que hay que printear los argumentos. La implementacion que teniamos en el grupo era que la memoria enviaba toda la instruccion a cpu y la cpu se encargaba de separar las palabras para poder resolverla, ¿esa implementacion esta mal? ¿La memoria deberia partir todas las palabras de la instruccion y enviarle todo?

Por otro lado, ¿los logs minimos y obligatorios en memoria los debo poner una vez que la instruccion ya fue realizada o cuando voy a comenzar a realizarla y ya tengo recibidos los datos que requiero para hacer el log?
Quedo atento a la respuesta.

Y por último tengo una duda sobre si algunos chequeos son necesarios o no. Por ejemplo, ¿debo chequear si un hilo quiere leer/escribir sobre alguna particion que no es la propia? 

Saludos!

**Comment by iago64** [comment]
Buenas! Cómo va?

Respecto al log de los bytes, nos quedo del cuatri pasado donde si teníamos diferentes tamaños de registros, aca pueden omitirlo o dejar hardcodeado el 4, no hay problema con eso.

La de las instrucciones es cuando la devuelven a la CPU y no hay problema si no esta el guión que separa la instrucción de los parámetros, lo que nos importa es ver que por ej están devolviendo la instrucción `SET AX 1` o la instrucción `SUM AX BX`

Sobre el tema de las lecturas y escrituras, en que caso les podría pasar que quieran escribir en una partición que no es del proceso / hilo? Tene en cuenta que las traducciones las hace la CPU y si se pasan del tamaño de la partición ya tienen el error del `Segmentation Fault`

Saludos.-

**Comment by inaaranza** [comment]
El tema de las escrituras y lecturas quería saber si se evalúa que la cpu envíe una dirección física que sea incorrecta (que la dirección que envia corresponda a otro proceso). Es más que nada para saber si puede existir ese caso y si se debe tener un manejo de error desde el lado de la memoria

**Comment by RaniAgus** [comment]
¡Buenas! Respondo la duda volviendo sobre la última pregunta de Dami: ¿se les ocurre algún escenario en el cual la CPU termine enviando dirección física inválida, o sea, que corresponda a otro proceso?

**Comment by inaaranza** [comment]
Hola Agus! A mí no se me ocurre un caso así en el TP pero lo pensé como si pudiese pasar como un error desde el punto de vista teórico de la materia. Tengo entendido que puede ocurrir que un proceso trate de escribir en una porción de memoria que no le corresponde y sería un error (me puedo estar equivocando tranquilamente)
Me quedo atento :)

**Comment by iago64** [comment]
Buenas! Cómo va?

Si vamos a la teoría pura, cuando vos haces las traducciones de direcciones logicas a fisicas ya estas teniendo la validación de que la dirección a la que estas intentando acceder es tuya, si no, como te comente antes, tendrías un `segmentation fault`.
Que no se te ocurra un escenario esta bien, ya que no debería existir y por lo tanto no se tienen que complicar, ya que en el momento en el que uds hicieron la traduccion en la mmu, el problema de las direcciones ya se terminó y la memoria solo tiene que leer o escribir en la dirección fisica que le estan pasando.

Saludos.-

**Comment by iago64** [comment]
@inaaranza Cómo va? Te sirvieron las respuestas? Hay algo que no explicamos bien?

**Comment by inaaranza** [comment]
Hola! Me re sirvió todo muchas gracias:)
Me había olvidado de cerrar el issue

Saludos!

**Comment by inaaranza** [comment]
Buenas! 

Abro de vuelta este issue por una cosita chiquita sobre los logs. Hay un log de memoria que es para loggear las conexiones de kernel, pero mi función para aceptar clientes se usa también para la cpu. Entonces cuando un cliente se conecta a la memoria no puedo diferenciar si es la cpu o si es una conexion de kernel. ¿Puedo poner un log sobre que se inició una conexión con el kernel aunque una sea de CPU? ¿O debo tener alguna manera de diferenciar una conexion de kernel con la que realiza la CPU?
Muchas gracias :)

Saludos

**Comment by iago64** [comment]
Buenas! Cómo va?

Algo copado de las commons es que los loggers soportan el concepto de [log_level](https://github.com/sisoputnfrba/so-commons-library/blob/981ad693ac55bf15d2473b8a5c922c7a5cc03eea/src/commons/log.h#L28), entondes uds pueden poner todo lo que quieran como DEBUG o TRACE y despues los obligatorios los dejan como INFO para que si aparezcan en las pruebas finales

Saludos.-

**Comment by inaaranza** [comment]
Perfecto! Muchas gracias!!!
