### ISSUE TITLE
Consulta prueba modular en filesystem

### ISSUE THREAD

**Issue by MartinSintas** [sisoputnfrba/foro#4362]
### 🖋️ Descripción

Buenas! estaba realizando una prueba casera en el módulo filesystem (ya que faltan pulir cosas del MEMORY_DUMP en memoria) y quería saber si la ejecución del mismo es correcta o debía hacer algunos cambios...

Algunas dudas que me surgieron fueron las siguientes:
1. Ante cada prueba se debe volver a generar la carpeta mount_dir? (Debido a que en la entrega final se corren varioas pruebas y no quedarían el bloques.dat y bitmap.dat "limpios")
2. Debería implementar algún comando de Hexdump en las funciones o eso lo vemos directamente por la terminal ejecutando hexdump -C /home/utnso/mount_dir/bloques.dat?

Paso a comentar un poco la prueba: se pide crear un DUMP el cual su tamaño es de 192 (teniendo en cuenta que nuestro block_size del config es igual a 64 serían 3 bloques) en el cual su contenido es "hola como estas", ocupando cada palabra en un bloque distinto

Desde ya, muchas gracias por tomarse el tiempo de responder. Saludos!

### LOG de FIleSystem (hay algunos logs que proximamente van a desaparecer)
utnso@utnso:~/tp-2024-2c-GOlazo/filesystem$ ./filesystem 
2024/10/24 16:44:43 Archivo de config de FILESYSTEM cargado!!!!!!!!!!!
2024/10/24 16:44:43 El directorio /home/utnso/mount_dir no existe. Creando...
2024/10/24 16:44:43 Creando archivo bitmap.dat...
2024/10/24 16:44:43 Creando archivo bloques.dat...
2024/10/24 16:44:43 Archivos de estructura verificados/creados correctamente.
2024/10/24 16:44:43 Bloque 0 marcado como ocupado en el bitmap.
2024/10/24 16:44:43 Bloque 1 marcado como ocupado en el bitmap.
2024/10/24 16:44:43 Bloque 2 marcado como ocupado en el bitmap.
2024/10/24 16:44:43 Bloque 3 marcado como ocupado en el bitmap.
2024/10/24 16:44:43 Directorio /home/utnso/mount_dir/files/ creado.
2024/10/24 16:44:43 Archivo de metadata para archivo_test-1729788283.dmp creado correctamente.
2024/10/24 16:44:43 Bloque 0 actualizado correctamente en bloques.dat.
2024/10/24 16:44:43 Bloque 0 actualizado correctamente en bloques.dat.
2024/10/24 16:44:43 Bloque 0 actualizado correctamente en bloques.dat.
2024/10/24 16:44:43 Bloque 1 actualizado correctamente en bloques.dat.
2024/10/24 16:44:43 Acceso al bloque 1 - Tipo: DATA
2024/10/24 16:44:58 Acceso completado.
2024/10/24 16:44:58 Bloque 2 actualizado correctamente en bloques.dat.
2024/10/24 16:44:58 Acceso al bloque 2 - Tipo: DATA
2024/10/24 16:45:13 Acceso completado.
2024/10/24 16:45:13 Bloque 3 actualizado correctamente en bloques.dat.
2024/10/24 16:45:13 Acceso al bloque 3 - Tipo: DATA
2024/10/24 16:45:28 Acceso completado.
2024/10/24 16:45:28 Archivo DUMP archivo_test-1729788283.dmp creado con éxito (PID: 1234, TID: 1).
2024/10/24 16:45:28 Archivo dump creado correctamente.
2024/10/24 16:45:28 Bloque 0 leído correctamente de bloques.dat.
Contenido del bloque 0: 
2024/10/24 16:45:28 Bloque 0 marcado como ocupado en el bitmap.
2024/10/24 16:45:28 Bloque 0 marcado como ocupado.
2024/10/24 16:45:28 El bloque 0 está ocupado: true
2024/10/24 16:45:28 Bloque 1 leído correctamente de bloques.dat.
Contenido del bloque 1: hola                                                            
2024/10/24 16:45:28 Bloque 1 marcado como ocupado en el bitmap.
2024/10/24 16:45:28 Bloque 1 marcado como ocupado.
2024/10/24 16:45:28 El bloque 1 está ocupado: true
2024/10/24 16:45:28 Bloque 2 leído correctamente de bloques.dat.
Contenido del bloque 2: como                                                            
2024/10/24 16:45:28 Bloque 2 marcado como ocupado en el bitmap.
2024/10/24 16:45:28 Bloque 2 marcado como ocupado.
2024/10/24 16:45:28 El bloque 2 está ocupado: true

### Hexdump
utnso@utnso:~$ hexdump -C /home/utnso/mount_dir/bloques.dat
00000000  00 00 00 03 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000040  68 6f 6c 61 20 20 20 20  20 20 20 20 20 20 20 20  |hola            |
00000050  20 20 20 20 20 20 20 20  20 20 20 20 20 20 20 20  |                |
*
00000080  63 6f 6d 6f 20 20 20 20  20 20 20 20 20 20 20 20  |como            |
00000090  20 20 20 20 20 20 20 20  20 20 20 20 20 20 20 20  |                |
*
000000c0  65 73 74 61 73 20 20 20  20 20 20 20 20 20 20 20  |estas           |
000000d0  20 20 20 20 20 20 20 20  20 20 20 20 20 20 20 20  |                |
*
00000100  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00010000

### Carpetas de archivos
![image](https://github.com/user-attachments/assets/e7aaedb0-ead2-46c9-a247-04df7f5694c4)

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- No, tienen que ver si existe un Fs previo y si no existe ahi recien lo crean.

2.- No hace falta, con el `hexdump -C <archivo>` o `xxd <archivo>` estamos bien :)

Saludos.-

**Comment by MartinSintas** [comment]
Genial Dami, gracias como siempre!
