### ISSUE TITLE
Duda sobre log de "Motivo de bloqueo", en Kernel

### ISSUE THREAD

**Issue by KirkSH** [sisoputnfrba/foro#4363]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Hola. Estaba leyendo lo que dice el enunciado sobre la syscall de Memory Dump, y entiendo que el hilo pasa a BLOCKED hasta recibir la respuesta que lo mandará a READY o EXIT. La implementación que tenemos para eso es muy similar a la descripta en [este issue](https://github.com/sisoputnfrba/foro/issues/4357).
Sin embargo, viendo los logs obligatorios (de Kernel), vimos que el log de "Motivo de bloqueo" no contempla entre sus opciones al "MEMORY_DUMP".
¿Lo ignoramos, o al enunciado capaz se le pasó?

### 📔 Citas del enunciado/videos

`Esta syscall bloqueará al hilo que la invocó hasta que el módulo memoria confirme la finalización de la operación, en caso de error, el proceso se enviará a EXIT. Caso contrario, el hilo se desbloquea normalmente pasando a READY.`

`Logs mínimos y obligatorios:`

`Motivo de Bloqueo: “## (<PID>:<TID>) - Bloqueado por: <PTHREAD_JOIN / MUTEX / IO>”`

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Nos olvidamos de ponerlo en el enunciado, pueden sumarlo para ser mas claros con los logs 😊.

Saludos.-

**Comment by KirkSH** [comment]
Ah oka. Gracias.
