### ISSUE TITLE
consulta sobre FILESYSTEM

### ISSUE THREAD

**Issue by fedemelgin** [sisoputnfrba/foro#4364]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

tengo 2 dudas 
1-la primera es sobre el contenido que se le pasa a filesystem desde memoria, no estaria entendiendo bien si recibe un string o el contexto de proceso o solo un array de bytes, en el caso de un array de bytes lo unico que deberia hacer es copiar el contenido y pegarlo directamente en los bloques correspondiente ya que son bytes no?
2- los bloques que se le asignan tanto el indice como los que contienen el contenido siempre serian contiguos no? ya q no existe ningun eliminar archivo que pueda dejar algun "hueco".

### 📔 Citas del enunciado/videos

La creación de los archivos de DUMP de memoria se crearán al recibir desde Memoria la petición de creación de un nuevo archivo de DUMP. En la petición deberá venir el nombre del archivo, el tamaño y **el contenido a grabar en el mismo.**

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Lo que reciben es el contenido de la memoria del usuario, cosa que en su caso como estan en Go, si, es un array de bytes y lo único que tienen que hacer es copiar el contenido en los bloques.

2.- Si, pueden asignarlos contiguos, ya que como bien decis, los archivos una vez creados quedan ahi, no se eliminan, ni modifican.

Saludos.-

**Comment by fedemelgin** [comment]
perfecto, graciass

**Comment by servasquezlizana** [comment]
Relacionado a esto.


1- Lo que se va escribir en el archivo bloques, entrara en un solo bloque? o puede que se escriba en mas?

**Comment by iago64** [comment]
@servasquezlizana Si la pregunta se encuentra cerrada y no resuelve completamente tu duda, _no escribas en esa misma pregunta_: anotá el número de issue para referirlo en tu nueva pregunta.
