### ISSUE TITLE
Consulta Memory Dump en Filesystem

### ISSUE THREAD

**Issue by zBlooDy** [sisoputnfrba/foro#4366]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

Buenas! Tenia unas consultas con la creacion de archivos de DUMP en Filesystem.
1)  En el paso 4 de la creacion dice que se debe acceder al archivo de punteros y grabar todos los punteros reservados.
El enunciado se refiere a acceder al bloque de indice correspondiente y escribir los punteros a los bloques de datos?

2) Podria antes de hacer el paso 3 de crear el archivo metadata, escribir los punteros en el bloque de indice (haciendo el retardo tambien)? Y luego de eso creo el archivo metadata y por ultimo accedo a los bloques de datos para escribir los datos
O esto es asi porque cuando accedo a un bloque tengo que logear el nombre del archivo?

3) Los N+1 accesos a bloques, el hecho de sumarle 1 es por el acceso a el bloque de indice? 

4) El log de asignacion de bloque, cuando me pide la cantidad de bloques libres, se refiere a buscar en el bitmap cuantos bloques tengo libres en el FS? O que bloques libres serian?

### 📔 Citas del enunciado/videos

![image](https://github.com/user-attachments/assets/66f8a6b2-8553-4b68-a798-9e0a138a81d2)

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Gracias por separar las dudas por puntos, hace mas facil que ahora vengan las respuestas:

1.- Exacto, como vos sabes de antemano el tamaño del archivo, podes reservar todos los bloques necesarios y despues en el archivo de punteros podes escribir todos los punteros a los bloques.

2.- Si, el orden de los pasos no afecta, mientras hagan todo y respeten los retardos no hay problema.

3.- Exacto, N bloques de datos y 1 bloque de indice o punteros.

4.- Son los bloques libres del FS, que lo pueden tener en alguna variable por fuera del bitmap que la cargan cuando inicia el FS, es para ayudarnos a que sea mas facil identificar cuando se esta por llenar el FS en las pruebas.

Saludos.-

**Comment by zBlooDy** [comment]
Genial Dami! Todo clarisimo las respuestas, lo unico que me quedo duda con el log de "Acceso a Bloque"

Esto hace mas referencia al paso 5 de la creacion del archivo DUMP? Que accedo al bloque de indice, y a partir de este bloque que tiene los punteros accedo a los bloques de datos (para escribir el contenido) y eso logearlo? 

Porque en varios casos hago un "acceso" a los bloques para verificar si hay espacio disponible o para marcarlos como ocupados por ejemplo.

**Comment by iago64** [comment]
Buenas! Cómo va?

Tal cual como decís, lo que te puede llevar a la pregunta de ¿Vamos a tener muchos logs de acceso a bloque? Y la respuesta es sí, pero no hay problema con eso

Saludos.-

**Comment by zBlooDy** [comment]
Buenas Dami, todo bien por suerte, genial entonces logeo cuando tenga que escribir el contenido!
Te hago una consulta que me surgio, esta un poco referido a lo de memory dump y al esquema de los archivos. Los archivos metadata se van creando a partir de que creo un archivo DUMP, pero estos archivos cuando inicializo el FS no hace falta bajarlos a una estructura ni nada por el estilo no? Porque simplemente creo los archivos cuando me mandan la request los creo en la ruta que dice el enunciado

**Comment by iago64** [comment]
Buenas! Cómo va?

Cuando decis bajarlos decis de abrir los archivos previos para hacer algo? Si es asi, no hace falta.
Este FS es medio "mentiroso" porque tiene solo las operaciones de crear archivo y escribir, no vamos a modificarlos ni eliminarlos.

Saludos.-

**Comment by zBlooDy** [comment]
Perfecto Dami, mil gracias por la ayuda en este issue, me quedaron las cosas más claras. Cualquier cosa vuelvo a abrir un issue preguntando

**Comment by iago64** [comment]
Dale, para la proxima nomas, acordate que el boton de cerrar es el que el check violeta jeje
![image](https://github.com/user-attachments/assets/a47bd5b8-2dee-4ad0-b007-2ebf2a832ed3)
