### ISSUE TITLE
Archivo de para cargar al ejecutar el Kernel

### ISSUE THREAD

**Issue by ezemartlopez** [sisoputnfrba/foro#4367]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

El enunciado del tp habla sobre un archivo que se pasara como argumento por consola y su size, tenia dudas si ese archivo lo generamos nosotros, o teniamos uno de prueba para ser utilizado. La verdad estoy un poco perdido en esa parte ya que no tengo idea como generarlo. Cualquier ayuda es recibida. Desde ya muchas gracias:
./bin/kernel [archivo_pseudocodigo] [tamanio_proceso] [...args]

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by SantiagoDopazo** [comment]
Hola Buenas!

Es un archivo donde cada linea van a ser las instrucciones que se plantean en el TP del estilo:

![image](https://github.com/user-attachments/assets/99bfe005-9b34-4b7a-878e-4491e364f056)
Por ahora pueden crear sus archivos para probrar las funcionalidades que quieran pero en un futuro estaran apareciendo pruebas para que puedan correrlas ustedes. 
Recuerden que los archivos van a tener 1 instrucción por línea, asi que van a poder operarlos sabiendo que el delimitador de cada instrucción es el caracter \n. Tambien podes buscar pruebas de tps anteriores pero solo te van a servir para ver la estructura porque las instrucciones y el funcionamiento cambian.

PD: la imagen que mostre no sigue una logica establecida pero es un ejemplo de como seria uno de estos archivos.

**Comment by iago64** [comment]
Cerramos el issue por inactividad 👮‍♂️
