### ISSUE TITLE
Conversion de un []Byte con 4 posiciones a una variable de tipo uint32

### ISSUE THREAD

**Issue by Jere1203** [sisoputnfrba/foro#4368]
### 🖋️ Descripción

Cuando recibo los 4 bytes por parte de memoria en la instruccion ReadMem y antes de setear ese valor en el registro que corresponda tenía la duda de cómo convertir los 4 bytes mencionados en una variable de tipo uint32 para poder trabajar con los registros.

### 📚 Búsqueda en documentación/foros

Indagando por foros encontré una función de golang que es binary.BigEndian.Uint32(), pero también hay una que es para LittleEndian. No estoy seguro de cuál de las dos corresponde utilizar.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Mientras sean consistentes y todas las operaciones las hagan teniendo en cuenta la misma notación el resultado no cambia, por las dudas en los logs de la CPU cuando impriman los registros, háganlo una vez convertidos a uint32 así es también más fácil de ver para uds a la hora de probar el TP.

De todas formas, para evitarse algún mini infarto a futuro, les recomiendo que utilicen BigEndian, esto es porque a la hora de hacer los dump de memoria, si abren los datos del archivo de `bloques.dat` en el FS con algún editor hexadecimal, van a ser más fácil de ver los valores, pero a nivel evaluación no debería haber problemas.

Saludos.-

**Comment by Jere1203** [comment]
Buenísimo, muchísimas gracias!
