### ISSUE TITLE
Duda en uso de select en kernel y cpu 

### ISSUE THREAD

**Issue by JoseMPaz** [sisoputnfrba/foro#4369]
### 🖋️ Descripción

Buenas noches, estoy teniendo dificultad en conectar el modulo kernel y cpu con select, queria saber si esta conexion se puede hacer con hilos, ya que el enunciado indica que la conexion entre ambos modulos es constante, y en teoria para no tener una espera activa select deberia ser la mejor solucion, mi duda es si select debe ir en el modulo kernel y cpu deberia tener 2 servidores  conetados a dispatch e interrupt, o si select va en cpu, saludos. 

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Si, se puede y de hecho ss mucho mejor que la hagan con hilos. 
Desde la cátedra ya casi que `select()` lo tenemos olvidado en el fondo del cajón de los recuerdos porque su uso te lleva a ser propenso a tener [código espagueti](https://es.wikipedia.org/wiki/C%C3%B3digo_espagueti) y que atenta con casi todas las buenas prácticas de programación.

Saludos.-

**Comment by JoseMPaz** [comment]
Genial, entonces usaremos hilos, me surgio una duda en los pcb_t va el pid y una lista de nodos apuntando a tids<int o tid_t(int tid;int prioridad)> y lista de nodos apuntando a mutex<int o pthread_mutex_t>. O sea tengo duda respecto al tipo de datos de los nodos en los pcb, cual deberia ser el tipo?

**Comment by iago64** [comment]
Buenas! Cómo va?

Los tipos de datos de las estructuras los pueden definir como les parezca a uds, como son estructuras administrativas que plantea cada grupo, no hay una única forma de hacerlo.

Saludos.-

**Comment by iago64** [comment]
Cerramos el issue por inactividad 👮‍♂️
