### ISSUE TITLE
Duda FileSystem

### ISSUE THREAD

**Issue by servasquezlizana** [sisoputnfrba/foro#4370]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Relacionado a esto:
[https://github.com/sisoputnfrba/foro/issues/4364](url)

1- Lo que se escribirá en el archivo bloques, entrará en un solo bloque? o puede que se escriba en mas bloques?
2- El retardo que hay en FS se usara luego de que se escriba en el archivo bloques.dat ?

### 📔 Citas del enunciado/videos

Esta operación resulta en que se deberán tener N+1 accesos a bloques, donde N es el número de bloques de datos del archivo y los retardos deberán realizarse luego de acceder a cada bloque.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- Puede ocumar varios bloques.

2.- Efectivamente, despues de que accedan a cada bloque simulan el retardo del acceso.

Saludos.-

**Comment by servasquezlizana** [comment]
Perfecto, muchas gracias!!!
