### ISSUE TITLE
Confusion sobre donde poner base y limite

### ISSUE THREAD

**Issue by GianLema** [sisoputnfrba/foro#4371]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Nosotros, para dar mas contexto, decidimos utilizar los structs PCB y TCB tanto en kernel como en memoria. Nuestra primera duda es si eso es lo correcto o si esta permitido/recomendado. Luego, con respecto a la base y al limite tenemos dudas sobre que hacer con ellos:
1)Poner base y limite solo el el PCB (esto entendemos que haria que cpu deba recibir tanto el hilo a ejecutar como a su proceso padre y cuando guardemos y enviemos el contexto, tengamos que guardar por separado los registros que van en el TCB y la base y limite que van en el PCB)
2)Poner base y limite en ambos PCB y TCB (todos los hilos de un proceso con los mismos valores)
3)Poner base y limite solo en TCB (esto no sabemos si trae problemas con la creacion de procesos ya que su entrada a memoria depende de su tamaño)

### 📔 Citas del enunciado/videos

a continuacion algunos fragmentos del enunciado:

>Se deberá almacenar, por cada PID del sistema, la parte del contexto de ejecución común para el proceso, en este caso, es la requerida para poder traducir las direcciones lógicas a físicas: base y límite.
Luego, por cada TID del sistema, se tendrán los registros de la CPU propios de cada hilo: AX, BX, CX, DX, EX, FX, GX, HX y PC. Siendo todos ellos inicializados en 0.

>Al llegar un nuevo proceso a esta cola y la misma esté vacía se enviará un pedido a Memoria para inicializar el mismo. Si la respuesta es positiva, se crea el hilo 0 de ese proceso, se lo pasa al estado READY y se sigue la misma lógica con el proceso que sigue. Si la respuesta es negativa (ya que la Memoria no tiene espacio suficiente para inicializarlo) se deberá esperar la finalización de otro proceso para volver a intentar inicializarlo.

>Deberemos devolverle el contexto de ejecución completo para el PID-TID pedido: AX, BX, CD, DX, EX, FX, GX, HX, PC, base y límite.

>Al momento de recibir un TID y PID de parte del Kernel la CPU deberá solicitarle el contexto de ejecución correspondiente a la Memoria para poder iniciar su ejecución.

### 💭 Soluciones posibles

aca dejo algunos extractos de nuestro codigo:

```
typedef struct{
	int PID;
	char* STATE_PROCESO;//duda en que estado esta un proceso con 2 de sus 3 hilos en ready y uno en running. y 1 en ready 1 en running y 1 en blocked?
	// suponemos con lean que el nivel de prioridad de los estados del proceso es RUNNING(1) READY(2) BLOCKED(3)
	t_list* id_hilos_hijos;//contiene los tid de los n hilos que va creando el proceso (va de 0 a n-1)
	t_list* mutex_creados;//contiene los mutex que va creando el proceso
	int TAM;
	int ultimo_tid;
	int pos_particion_en_lista;
	uint32_t base;
	uint32_t limite;
}PCB;


typedef struct{
	int TID;
	int id_proceso_padre;
	char* path_instrucciones;
	t_list* instrucciones;
	int prioridad;// 0 = maxima prioridad  
	uint32_t PC;
	uint32_t AX;
	uint32_t BX;
	uint32_t CX;
	uint32_t DX;
	uint32_t EX;
	uint32_t FX;
	uint32_t GX;
	uint32_t HX;
	char* STATE_KLT;
	//podemos pensar en mas datos auxiliares q esten piola sumar
	t_Quantum QUANTUM; //t_Quantum es int64_t!!!!
}TCB;


### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Base y limite son datos propios del proceso, mientras que lo que ejecutan es un hilo, lo ideal sería que la CPU solo reciba los valores de PID y TID y con eso le consulte a la memoria todos los datos necesarios, tambien conocidos como _contexto de ejecución._

Dicho lo anterior, tener los datos en el TCB es algo que carece de sentido, porque el proceso al momento de crearlo es el que te ocupa memoria, despues hilos podes crear 1000 o 1 aparte del hilo main o TID 0 del proceso.

Saludos.-

**Comment by iago64** [comment]
Cerramos el issue por inactividad 👮‍♂️
