### ISSUE TITLE
Operacion DUMP

### ISSUE THREAD

**Issue by christianMakinson95** [sisoputnfrba/foro#4372]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas noches,
Queria preguntar sobre el funcionamiento de memory dump, particularmente, cuando se ejecuta el dump, vamos a enviarle al filesystem todo aquello que se encuentre en la memoria de usuario asociado al PID, o hay que considerar el TCB. Es decir, en el siguiente caso:
Contexto: En el caso de no haya cambios en la memoria y dos TID distintos hacen dump

dump PID 3 TID 2
dump PID 3 TID 5 

Los dos deberian dumpear los mismos datos (es decir los datos de la particion del PCB)? o deberian ser particulares al TID?

Desde ya muchas gracias 

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Solo tienen que dumpear lo que se encuentra en la memoria de usuario, asi que, si no hubo cambios en la memoria entre un dump y otro debería ser el mismo archivo, independientemente de si lo hace el mismo TID o lo hacen TIDs distintos.

Saludos.-

**Comment by christianMakinson95** [comment]
Muchas gracias! cierro el issue
