### ISSUE TITLE
Duda con Block_access_delay de filesystem

### ISSUE THREAD

**Issue by fedemelgin** [sisoputnfrba/foro#4374]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

me surgió una duda con respecto con delay que se debe hacer ante cada acceso a bloques, no entiendo bien si el delay se debe hacer ante cada acceso al bloque o 1 vez luego de haber realizado todo en ese bloque. 
ejemplo:
para escribir en el bloque índice los 3 bloques que necesito para almacenar los datos, tengo una función FOR en la que en cada iteración accede al bloque índice para escribir el "puntero" asociado a ese bloque de dato, entonces mi duda es si en cada iteración tengo que hacer el delay o una vez que haya escrito todos en ese bloque, ahí recién se hace el DELAY, porque dice que deberian tener N+1 acceso a bloques pero despues dice que se debe hacer el retardo luego de acceder a cada bloque, entonces en el ejemplo tendria 3 accesos (bloque indice) y despues 3+ para escribir en cada bloque = 6 y  6 ≠ 4

### 📔 Citas del enunciado/videos

Esta operación resulta en que se deberán tener N+1 accesos a bloques, donde N es el número de bloques de datos del archivo y los retardos deberán realizarse luego de acceder a cada bloque.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by LeandroCarbajales** [comment]
Buenas!
Al igual que los bloques de datos, lo ideal sería que todo el bloque índice sea escrito de una (haciendo un solo acceso, independientemente de cuántos punteros haya que escribir).
Si se les complica la implementación pueden realizar el retardo una vez sola luego de terminar toda la escritura del bloque como proponés :). De esa manera a todos les debería quedar el N+1 retardos independientemente de la implementación.

Saludos!
     Lean

**Comment by fedemelgin** [comment]
muchas gracias, ahora voy a hacerlo para escribir todo de una como en los bloques de datos
