### ISSUE TITLE
Consultas sobre implementaciones de Memory Dump en Filesystem 

### ISSUE THREAD

**Issue by zBlooDy** [sisoputnfrba/foro#4375]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

Buenas tengo unas dudas sobre implementacion de algunas cosas en el apartado de memory dump
1) En mi caso cuando levanto el modulo de FileSystem, lo que hago es bajar a memoria el contenido de bloques.dat y bitmap.dat, con el objetivo de que, cuando tenga que hacer la operacion de Memory Dump, no tenga que hacer continuamente accesos a disco.
Es decir que cuando tengo que verificar si hay espacio, o reservar bloques/escribir el contenido en los mismos, directamente trabajo con esas variables globales. Entonces mi idea es que cuando finaliza la operacion de memory dump cargar esas variables en los archivos correspondientes y tener la informacion actualizada en cada archivo. Tenia dudas si es correcta la logica que estoy siguiendo

2) Por otra parte me quedo pendiente una duda de los logs, cuando accedo al bloque de indices para reservar los punteros, eso necesito logearlo? Porque yo tenia pensado logear todo en el 5to paso en el cual tengo que escribir el contenido, que me mandan por la request, en los bloques de datos correspondientes. Entonces ahi logearia el acceso al bloque de indice para saber cuales son los bloques de datos, y despues por cada acceso al bloque de dato hago un log.

Si no lo que se me habia ocurrido es hacer el paso 4 y 5 juntos, entonces ahi si logueo el acceso al bloque de indice para reservar los punteros, guardar esa informacion de los punteros que tiene ESE bloque de indice, y ahi acceder bloque a bloque y escribir el contenido

### 📔 Citas del enunciado/videos

![image](https://github.com/user-attachments/assets/045503fd-e264-4c9f-8439-ff2d6dbe87a5)

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by LeandroCarbajales** [comment]
Buenas!
1-
Está perfecto levantar el bitmap a memoria ya que sería super engorroso e ineficiente tener que leerlo del archivo cada vez. Desde el mismo ya podés verificar el espacio y marcar los bloques como ocupados :)

Lo que no me cierra es para qué levantar el bloques.dat a memoria en este caso, si la data a escribir ya te la pasa el módulo memoria y el mismo nunca requiere ser leído. No digo que esté mal, pero capaz te la estás complicando de más haciéndolo :)

2-
`Entonces ahi logearia el acceso al bloque de indice para saber cuales son los bloques de datos`
Los bloques de datos ya sabés cuáles son desde el momento en que los reservás (marcás ocupados) en el bitmap, sino no podrías escribir el archivo índice :)
En definitiva, el FS propuesto es solo de escritura, por lo que los accesos son solamente para escribir cada bloque (índice + datos).

Te aclara las dudas?
Saludos!
    Lean

**Comment by zBlooDy** [comment]
Buenas Lean como andas! Perdón que vuelvo a responder es para ver si termino cerrar las ideas:

1) Claro ahora que me lo decís de esa forma, es verdad que el bloques.dat no es necesario bajarlo a memoria ya que únicamente lo voy a usar para escribir el bloque índice y los bloques de datos correspondientes, es decir que no se harían tantos accesos a disco como en el Bitmap, no?

2) Entiendo, sisi yo los bloques que reservo los guardo cuando los reservo para después saber a dónde tengo que escribir. Entonces los accesos serían:
Bloque de índice => Escribir los punteros a los otros bloques
Bloque/s de datos => Escribir el contenido que me pasa memoria

**Comment by LeandroCarbajales** [comment]
Buenas!
Ninguna molestia, para eso está el foro.

1- Exactamente, el bitmap tendrás que accederlo para saber si tenés espacio suficiente y marcar bloques ocupados, sin embargo, ninguna de estas acciones conllevaría accesos a bloque/disco/archivo ya que lo tenés todo levantado en una variable. Luego para persisitirlo podés actualizar esos cambios todo de una en el archivo o tener el archivo mapeado a memoria.

2- Correcto!

**Comment by zBlooDy** [comment]
Perfecto Lean, muchísimas gracias va quedando todo más claro!  Cualquier cosa abro otro issue 👏🏻
