### ISSUE TITLE
MUTEX_UNLOCK

### ISSUE THREAD

**Issue by fernandodanielmaqueda** [sisoputnfrba/foro#4376]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas, ¿cómo va?

Quisiera consultar qué debería hacerse en caso de que el hilo que realiza la syscall MUTEX_UNLOCK no tenga asignado el mutex: si mandarlo a EXIT o reenviarlo hacia la CPU para continuar su ejecución normalmente. El enunciado sólo especifica que "no realizará ningún desbloqueo".

### 📔 Citas del enunciado/videos

MUTEX_UNLOCK, se deberá verificar primero que exista el mutex solicitado y esté tomado por el hilo que realizó la syscall. En caso de que corresponda, se deberá desbloquear al primer hilo de la cola de bloqueados de ese mutex y le asignará el mutex al hilo recién desbloqueado. Una vez hecho esto, se devuelve la ejecución al hilo que realizó la syscall MUTEX_UNLOCK. En caso de que el hilo que realiza la syscall no tenga asignado el mutex, no realizará ningún desbloqueo.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by RaniAgus** [comment]
¡Buenas! Como especifica la cita que mencionabas, se debe devolver la ejecución al hilo que realizó la syscall MUTEX_UNLOCK, pero en este caso sin realizar ningún desbloqueo. Saludos

**Comment by fernandodanielmaqueda** [comment]
¡Gracias, Agus!
Cierro issue.
