### ISSUE TITLE
Fin de programa

### ISSUE THREAD

**Issue by fernandodanielmaqueda** [sisoputnfrba/foro#4377]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas, ¿cómo va?

Quisiera consultar qué debería suceder si todos los hilos y procesos de Kernel llegaran a terminar su ejecución. ¿Debería detectar esto y terminar Kernel como programa, o quedaría en stand-by esperando hasta que alguien le de un CTRL + C?

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by mesaglio** [comment]
Hola, quedaria a la espera de nuevos procesos/hilos o un CTRL + C.

Saludos!

**Comment by fernandodanielmaqueda** [comment]
¡Buenas!
Según entiendo si todos los procesos/hilos terminan ya no existe posibilidad de que se creen nuevos (que es mediante las syscalls THREAD_CREATE y/o PROCESS_CREATE).
En esa situación Kernel quedaría sin nada más para hacer, por eso mi consulta de si en esa situación no habría que terminar el módulo.
¡Saludos!

**Comment by iago64** [comment]
Buenas! cómo va?

Si terminan todos los hilos se quedan ahi, haciendo nada y esperando que finalicen el proceso con un Ctrl + C como dijo Juan.

Saludos.-

**Comment by fernandodanielmaqueda** [comment]
¡Buenas!
Sólo para confirmar que estoy entendiendo bien, ¿si también terminan todos los procesos debería quedarme ahí sin hacer nada hasta que me llegue un SIGINT (CTRL + C) para poder finalizar Kernel?
Perdón por la repregunta, es que me resulta extraño que un programa continúe en ejecución si ya no tiene nada más que hacer.
¡Saludos!

**Comment by iago64** [comment]
Buenas! 

Si, se tienen que quedar ahi.

Saludos.-

**Comment by fernandodanielmaqueda** [comment]
Entendido.
¡Gracias a ambos!
