### ISSUE TITLE
Duda con MUTEX

### ISSUE THREAD

**Issue by Elias318** [sisoputnfrba/foro#4378]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas tardes, tengo 2 consultas.

La primera es como podría conseguir el valor en el que este el mutex para saber si tenemos que bloquear el hilo? Entiendo que a eso se refiere al decir "tomado". No encontré una función que te indique dicho valor.

La segunda es si hay que pasarle un nombre por parametro al hacer el mutex_create.

Gracias!

### 📔 Citas del enunciado/videos

MUTEX_CREATE, crea un nuevo mutex para el proceso sin asignar a ningún hilo.
MUTEX_LOCK, se deberá verificar primero que exista el mutex solicitado y en caso de que exista y el mismo no se encuentre tomado se deberá asignar dicho mutex al hilo correspondiente. En caso de que el mutex se encuentre tomado, el hilo que realizó MUTEX_LOCK se bloqueará en la cola de bloqueados correspondiente a dicho mutex.
MUTEX_UNLOCK, se deberá verificar primero que exista el mutex solicitado y esté tomado por el hilo que realizó la syscall. En caso de que corresponda, se deberá desbloquear al primer hilo de la cola de bloqueados de ese mutex y le asignará el mutex al hilo recién desbloqueado. Una vez hecho esto, se devuelve la ejecución al hilo que realizó la syscall MUTEX_UNLOCK. En caso de que el hilo que realiza la syscall no tenga asignado el mutex, no realizará ningún desbloqueo.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Los mutex son objetos que uds van a crear en el contexto de su trabajo práctico, por lo tanto, definan alguna estructura que les permita saber el valor si lo necesitan.

En respuesta a la segunda pregunta, si, los mutex en este TP los vamos a reconocer por medio del nombre que les pasamos en la syscall MUTEX_CREATE.

Saludos.-

**Comment by Elias318** [comment]
Perfecto! Y esto de que van a estar tomados por algun hilo podria ser que el TCB tenga en su estructura un lugar para el mutex asociado o a que se refiere con que este tomado por un hilo. Por que no puedo relacionar eso con la lista de mutex que tenemos en el pcb

**Comment by iago64** [comment]
Buenas! Cómo va?

No sería mas simple pensar que en la estructura del Mutex, tengas un valor que te diga quien lo tiene tomado?

Saludos.-

**Comment by Elias318** [comment]
Ahh perfecto. Gracias!
