### ISSUE TITLE
Duda sobre SEGMENTATION FAULT

### ISSUE THREAD

**Issue by JeronimoAlo** [sisoputnfrba/foro#4379]
### 🖋️ Descripción

Buenas tardes!

Tenemos una duda con respecto al manejo de un SEGMENTATION FAULT. Dentro de la CPU nos indican lo siguiente dentro del requerimiento de la MMU:

"Se debe validar que las solicitudes se encuentren dentro de la partición asignada, es decir que sea menor al límite de la partición. De fallar dicha validación, ocurrirá un “Segmentation Fault”, en cuyo caso, se deberá actualizar el contexto de ejecución en Memoria y devolver el Tid al Kernel con motivo de Segmentation Fault." 
Nuestra duda radica en que debemos hacer del lado de kernel al recibir un SEGMENTATION FAULT ya que no está especificado en el enunciado. Debemos finalizar el hilo y el proceso? O únicamente el hilo en cuestión?

Muchas gracias!
Saludos.

### 📚 Búsqueda en documentación/foros

Revisamos los demás issues pero no encontramos una respuesta.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by LeandroCarbajales** [comment]
Buenas!
Es una buena pregunta, se nos pasó explicitar en el enunciado de Kernel cuál es el comportamiento esperado. Tomando como referencia un caso real la idea es finalizar el proceso, estaremos actualizando el enunciado a la brevedad para reflejar esto.
Gracias por notar el bache 😅
Saludos!
