### ISSUE TITLE
Memoria de usuario

### ISSUE THREAD

**Issue by Nardelli-Federico** [sisoputnfrba/foro#4380]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

No terminamos de entender que es lo que iría en memoria de usuario, ahí debemos guardar únicamente el contexto de los pid-tid del sistema? 

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by RaniAgus** [comment]
¡Buenas @Nardelli-Federico ! ¿Les sirvió la respuesta de Dami? Saludos

**Comment by Nardelli-Federico** [comment]
Los datos que tipo de estructura tienen?

**Comment by Nardelli-Federico** [comment]
me refiero a los datos que van a ir en memoria de usuario

**Comment by RaniAgus** [comment]
¡Buenas! Como mencionó Dami antes, los datos que van a ir en memoria de usuario provienen de la instrucción MEM_WRITE (y se leen a través de MEM_READ).

Esto significa que lo que vamos a copiar es el contenido de los registros de CPU, cuyo tamaño está especificado en el enunciado, y el contenido son simplemente bytes.

Saludos

**Comment by Nardelli-Federico** [comment]
Quedo clarisimo, gracias
