### ISSUE TITLE
pequeña duda sobre thread_exit

### ISSUE THREAD

**Issue by nicolasvultaggio** [sisoputnfrba/foro#4381]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

podría ocurrir que un hilo haga thread_exit y que sea el unico hilo de ese proceso? de forma que tengamos que finalizar el proceso liberando todas las estructuras necesarias, no solo hacer una finalizacion del hilo

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by LeandroCarbajales** [comment]
Buenas!
Los pseudocódigos de los TID 0 siempre se probarán con un PROCESS_EXIT y nunca un THREAD_EXIT, por lo que no necesitan tener en cuenta ese caso de uso.

Te aclara la duda?
Saludos!
     Lean

**Comment by nicolasvultaggio** [comment]
perfecto, muchas gracias, es exactamente lo que quería saber!
