### ISSUE TITLE
duda sobre syscalls e interrupciones por Quantum

### ISSUE THREAD

**Issue by tolaDiego** [sisoputnfrba/foro#4382]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas!
Cuando un hilo ejecuta una syscall y este mismo siempre vuelve a ejecutar, como es el caso de; PROCESS_CREATE,
THREAD_CREATE, THREAD_CANCEL, MUTEX_CREAR, como se trata la interrupcion por quantum? 
¿debe volver a ejecutar con un nuevo Quantum completo(contaria como una replanificacion) y  cpu debe ignorar la interrupcion generada por el fin de Quantum viejo?
 O el hilo vuelve a ejecutar con el Quantum viejo?

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Vuelve a ejecutarcon el Quantum viejo.

Saludos.-

**Comment by RaniAgus** [comment]
¡Buenas @tolaDiego ! ¿Les sirvió la respuesta de Dami? Saludos

**Comment by tolaDiego** [comment]
Buenas!
Si, nos fue muy util la respuesta.
**Ahora surgio otra duda con el resto de syscalls y quisiera saber si la siguiente afirmacion es correcta:** 
para un hilo que hace una syscall (JOIN por ejemplo) que puede bloquearlo o continuar ejecutando; si se bloquea entiendo que aca sí se reiniciaria el quantum(cuando salga de ready) y si no se bloquea ejecutando la syscall su quantum no se renueva(teniendo en cuenta la respuesta que nos dieron).

Se agradece cualquier recomendacion que puedan darnos para manejar todas estas situaciones porque la verdad no se nos ocurre nada.

**Comment by iago64** [comment]
Buenas! Cómo va?

Es tal cual decis, si no se bloquea continua con el Quantum que tenia asignado previamente y si se bloquea ahi si reinicias el quantum la próxima vez que vuelve a ejecutar.

Saludos.-

**Comment by tolaDiego** [comment]
Entiendo.
Gracias por todo!
