### ISSUE TITLE
Dudas relacionadas con el filesystem

### ISSUE THREAD

**Issue by vrojas2022** [sisoputnfrba/foro#4383]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Hola, buenas noches, tenemos las siguientes dudas con el filesystem:

1) El punto de montaje y la carpeta files, de no existir, se crean a mano o debe crearlas el código.

2) Similar a 1), los archivos bitmap.dat y bloques.dat de no existir debería crearlos el código o nosotros a mano.

3) Se podría dar el caso de que cambie la cantidad de bloques en el archivo de configuración?, en tal caso ya no servirían los archivos bitmap.dat y bloques.dat si es que ya existían, deberíamos eliminarlos y que el código los vuelva a generar?, por lo que vemos en las pruebas que pasaron la cantidad de bloques no cambiaría?.

4) Con respecto al archivo bloques.dat, nos queda la duda si lo inicializamos o no, podría no ser necesario, porque como es solo escritura y el bitmap.dat va a indicar los bloques libres solo vamos a ir a pisar el dato que hay cuando haya que escribir en los bloques tanto de índice como de datos?

Muchas Gracias!!

### 📔 Citas del enunciado/videos

<img width="470" alt="Captura issue" src="https://github.com/user-attachments/assets/1cc2840c-bcd4-4fc3-b920-e1065145a2d7">

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Muchas gracias por ponerles un indice a las preguntas, asi es mas facil de responderlas :) 

1.- Pueden crearlo a mano, no hay problema con eso

2.- Idem punto 1, si les resulta mas simple crearlo a mano pueden hacerlo, tengan en cuenta nomas los tamaños de los archivos, porque una cosa es crearlos y otra es que tengan el tamaño necesario.

3.- Las pruebas son preliminares, aun no hay ninguna de FS propiamente dicha, igual no vamos a probarles el escenario donde tengan que levantar un FS existente y cambiemos el tamaño del mismo.

4.- Exacto, no tienen que inicializar nada, igual esto ojo porque es un tema teórico tambien, si el FS tuviera operaciones de lectura, tampoco deberían pisar los datos de los bloques*

Saludos.-

*Nota: esto de no pisar los datos de los bloques es lo que permite que existan herramientas que recuperan los datos borrados de los discos rigidos.

**Comment by iago64** [comment]
@vrojas2022 Cómo va? ¿Te sirvió la respuesta? ¿Hay algo que necesites que explique mejor?

Saludos.-

**Comment by iago64** [comment]
Cerramos el issue por inactividad
