### ISSUE TITLE
Files System - Duda sobre DUMP 

### ISSUE THREAD

**Issue by ahuarca** [sisoputnfrba/foro#4384]
### 🖋️ Descripción

Holaa! Tenemos una duda sobre como files system recibirá los valores encontrados en el espacio de usuario, porque en memoria para el dump memeory tenemos implementado esto:

```
            case DUMP_MEMORY:

		cargar_int_al_buffer(buffer_a_FS, pcb_con_MD->tamanio_proceso); //tamanio del archivo
                char* contenido = malloc(tamanio_proceso);
               memcpy(contenido, memoriaUsuario + pcb_con_MD->base, pcb_con_MD->tamanio_proceso);
                cargar_string_al_buffer(buffer, contenido);
		paquete->buffer = buffer_a_FS;
		enviar_paquete(paquete, socket_filesystem);
		
```
En files system tenemos esto:

```
   
void handle_cliente_memoria(void *arg){
    int cliente_memoria = *(int*) arg;
    cod_op code = recibir_operacion(cliente_memoria);
    switch (code){
        case DUMP_MEMORY: 
            t_buffer* buffer = recibir_buffer(cliente_memoria);
            char* nombre = extraer_string_del_buffer(buffer);
            int tamanio_archivo = extraer_int_del_buffer(buffer);
            char* contenido = extraer_string_del_buffer(buffer);
            
```

En donde enviamos los valores encontrados en el espacio de usuario del proceso, en la variable contenido que tiene tamaño igual al espacio del proceso, que es un char*. Lo cual hace que a la hora de recbir los valores por parte de files system, se nos dificulte determinar cuando dejar de agarra valores, noostros habiamos pensado que como en los registros se setean únicamente ints, iba a haber sólo inst en el espacio de usuario del propio proceso, por lo que a la hora de recibirlo en files system solo teniamos que hacer un memcpy de 4 bytes y copiar eso a un bloque, pero con esta implementación, no sabriamos cuando determinar que ya no hay valores "ints" que sacar y cuando empieza la basura que se haya quedado en el espacio de memoria del proceso restante, nuestra duda es cómo podriamos hacer para enviarle sólo los valores y no basura que haya en el espacio ocupado por el proceso en memoria de usuario

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

La idea del DUMP_MEMORY es que guarten TODO el espacio de memoria del proceso / hilo, este usado o no, por lo que les podría ser mucho mas simple si directamente leen toda la partición de memoria y la escriben sin preguntarse que tienen guardado ahi.

Saludos.-

**Comment by iago64** [comment]
@ahuarca Cómo va? ¿Te sirvió la respuesta? ¿Hay algo que necesites que explique mejor?

Saludos.-

**Comment by ahuarca** [comment]
Se entendió, gracias!!
