### ISSUE TITLE
Creación de procesos

### ISSUE THREAD

**Issue by ejdavenheimer** [sisoputnfrba/foro#4385]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

No logro terminar de comprender el enunciado de la creación de procesos. Si bien avanzamos con mi grupo, leí todos los issues relacionados y consulté por discord en su momento, personalmente sigo sin entenderlo. 
Interpretándolo textual, parece decir que si la cola está vacía, entonces se inicializa, pero si se encola un proceso y los subsiguientes,  se trabaría todo el programa? O si solo debe admitir un proceso en la cola, entonces sería mejor una variable? O si la cola NEW debe estar vacía para funcionar, qué inicializa si no hay nadie en la cola?

### 📔 Citas del enunciado/videos

Creación de procesos
Se tendrá una cola NEW que será administrada estrictamente por FIFO para la creación de procesos. 
**Al llegar un nuevo proceso a esta cola y la misma esté vacía se enviará un pedido a Memoria para inicializar el mismo.** Si la respuesta es positiva, se crea el hilo 0 de ese proceso, se lo pasa al estado READY y se sigue la misma lógica con el proceso que sigue. Si la respuesta es negativa, la memoria puede retornar dos valores...

### 💭 Soluciones posibles

Para mi, el Kernel recibe un proceso con el archivo pseudocódigo y el tamaño del mismo, luego lo guarda en la cola NEW. Una vez allí, el Kernel se conecta al endpoint que está en memoria para saber si hay memoria para inicializar el proceso. Si es afirmativo, luego la memoria se conecta al endpoint que está en el Kernel para dar pie a la inicialización del proceso y la creación del TID0. De esta manera, cada proceso que llega se encola en NEW y el proceso de inicialización es el mismo, según haya disponibilidad. Por lo tanto, no consigo meter la lógica de que la cola NEW esté vacía en la interpretación que le di. Probablemente lo esté pensando mal.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

El proceso idealmente lo que busca es que como NEW es una cola, si un proceso no entra, se queda bloqueandole la entrada al resto de procesos que quieren entar, por mas que los que vengan atras sean mas chicos y si puedan entrar en alguna de las particiones libres.

En el enunciado lo que se busca decir es que si no hay ningun proceso esperando entrar, que intentes iniciarlo, pero que si hay un proceso que esta esperando entrar y no puede porque no encuenta una partición de memoria, entonces ahi, no tienen que ver si pueden asignarle una partición al proceso que acaban de agregar a la cola de NEW.

No se si me expliqué o si la complique mas.

Saludos.-

**Comment by ejdavenheimer** [comment]
Buenas, voy de atrás para adelante, porque creo que lo entendí. Si está bien mi razonamiento, ignorá mis dudas en el segundo texto citado jaja.

> En el enunciado lo que se busca decir es que si no hay ningun proceso esperando entrar, que intentes iniciarlo, pero que si hay un proceso que esta esperando entrar y no puede porque no encuenta una partición de memoria, entonces ahi, no tienen que ver si pueden asignarle una partición al proceso que acaban de agregar a la cola de NEW.

Creo que entendí, sería así:

Llega proceso -> Pregunta, ¿la cola está vacía? --> Si --> Directamente inicializo el proceso ya que sabemos que hay espacio.
------------------------------------------------------> No -> Hay memoria para mi? -> Si -> Joya, se inicializa.
------------------------------------------------------> No -> Hay memoria para mi? -> No -> Lo metemos a la cola NEW.

> El proceso idealmente lo que busca es que como NEW es una cola, si un proceso no entra, se queda bloqueandole la entrada al resto de procesos que quieren entar, por mas que los que vengan atras sean mas chicos y si puedan entrar en alguna de las particiones libres.

¿Por qué no entraría el proceso a NEW? Entiendo que una cosa es que llegue un proceso y se meta a la cola y otra distinta es que se pueda inicializar según lo que diga memoria. A la cola entran todos los procesos que lleguen, mientras que la inicialización va tomando elementos de la cola de NEW por FIFO para inicializarlos. No comprendo el motivo de que esté vacía o no la cola mencionada, ya que si está vacía es porque no hay procesos para configurarlos y están listos para ser corridos en ready.


Muchísimas gracias

**Comment by ejdavenheimer** [comment]
Genial, muchas gracias por las respuestas.

**Comment by ejdavenheimer** [comment]
Genial, muchas gracias por las respuestas.
