### ISSUE TITLE
problema sobre segunda entrega

### ISSUE THREAD

**Issue by nicolasvultaggio** [sisoputnfrba/foro#4386]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Hola, que tal? tengo un problema y es que, yo estoy cursando Física, y me metieron un recuperatorio el 7 de diciembre, todavía no se la hora, el problema es que justo ese día es la segunda entrega del TP, si bien creo que con mi grupo llegaremos para la primera entrega, quería preguntar, nosotros podemos elegir si presentar el trabajo practico a la tarde o a la mañana, verdad? con cuanto tiempo de anticipación podremos avisar sobre la hora a la que querramos presentarnos?

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Por favor envia este tema por mail a la casilla de inscripciones y ahi lo vemos mas en detalle.

Saludos.-

**Comment by nicolasvultaggio** [comment]
muchas gracias, perdon es que no sabia por donde hacer la consulta
