### ISSUE TITLE
 Duda sobre la memoria de usuario y memoria del sistema

### ISSUE THREAD

**Issue by Julian-Mosquera** [sisoputnfrba/foro#4387]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Hola buenas tardes, con mi grupo tenemos una duda con respecto a la asignación de memoria al crear procesos. En el enunciado se menciona que, para crear un proceso, debemos asignar espacio en la memoria de usuario dependiendo del esquema que estamos utilizando pero en el issue #4380 se dijo que en la memoria de usuario se guardan los datos que les mandemos con la instrucción MEM_WRITE y que los contextos de los pid-tid van en la memoria del sistema y en el enunciado los esquemas y estructuras de la memoria recaen en la Memoria del Usuario. 

Nos gustaría saber más específicamente cuál es la diferencia entre la memoria de usuario y la memoria del sistema, y cómo se estructuran los datos en cada una. 

Muchas gracias!

### 📔 Citas del enunciado/videos

>Comunicación con Kernel
Creación de proceso
Al momento de crear los procesos deberemos asignarles espacio en la memoria de usuario teniendo en cuenta qué esquema estamos utilizando

>Memoria de Usuario
Esquema de memoria y Estructuras
La memoria al trabajar bajo dos esquemas diferentes. Al iniciar la memoria se definirá el esquema a utilizar mediante el archivo de configuración, estos esquemas pueden ser:
Particiones fijas. 
Particiones dinámicas. 

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

La memoria de sistema es donde uds van a tener guardados de la forma que **mas facil les resulte a uds** los contextos de ejecución y los archivos de pseudocódigo.
Ademas de eso, en esta parte van a tener que generar ciertas estructuras administrativas que les permitan dividir la memoria de usuario de forma **logica** para tener las diferentes particiones.

La memoria de usuario va a ser un conjunto de bytes que en el caso de C lo obtienen con `malloc()` y en el caso de Go lo definen como un `byte[]` y donde ahi los datos van a ser simplemente bytes, no les importa el tipo de dato, que despues casualmente en la CPU van a tener siempre registros de 4 bytes y esos van a ser los 4 bytes que van a leer y/o escribir en la memoria de usuario es otro tema.

Saludos.-

**Comment by Julian-Mosquera** [comment]
Gracias por la respuesta!
