### ISSUE TITLE
Duda sobre particiones fijas y tamaño proceso

### ISSUE THREAD

**Issue by taoliza** [sisoputnfrba/foro#4388]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Estamos teniendo la siguiente duda con respecto a las direcciones de memoria en el caso de particiones fijas: 
Si un proceso tiene un tamaño menor a la particion asignada, a la hora de chequear la direción fisica para ver si hay segmentation fault, tenemos que compararla el tamaño del proceso o el limite de la partición? Porque en el caso que sea con el tamaño del proceso tendriamos que ver donde lo guardamos para poder compararlo despues. 

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Cito al enunciado:

> Se debe validar que las solicitudes se encuentren dentro de la partición asignada, es decir que sea menor al **límite de la partición**. De fallar dicha validación, ocurrirá un “Segmentation Fault”, en cuyo caso, se deberá actualizar el contexto de ejecución en Memoria y devolver el Tid al Kernel con motivo de Segmentation Fault.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas @taoliza !

Te resolvió la duda la sección de enunciado citada?

**Comment by taoliza** [comment]
Buenas, sisi ya me quedo claro, gracias
