### ISSUE TITLE
Consulta Filesystem

### ISSUE THREAD

**Issue by AgustinHerzkovich** [sisoputnfrba/foro#4389]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

Hola buenas, mi consulta es: un archivo podría llegar a ocupar más de un bloque de índices en caso de que no le alcance con uno?
En ese caso debería tener más de un archivo de metadata?
Muchas gracias, saludos.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by RaniAgus** [comment]
¡Buenas! Cada archivo puede tener un solo bloque de índices. Saludos

**Comment by AgustinHerzkovich** [comment]
Muchas gracias por la respuesta.
Saludos.
