### ISSUE TITLE
Tamaño de la palabra de memoria de usuario

### ISSUE THREAD

**Issue by SchincaMauroE** [sisoputnfrba/foro#4390]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Hola, en nuestro grupo surgió la duda si lal palabra de memoria de usuario se considera de **1 byte** o si debería ser de **4 bytes**, ya que la lectura y escritura de memoria de usuario se realiza de a **4 bytes**. La pregunta sería: ¿cada dirección en memoria contiene **1 byte** de información o **4 bytes**? Nosotros nos inclinamos por lo primero, pero nos gustaría poder obtener confirmación. Saludos!

#### READ MEM
Se deberá devolver el valor correspondiente a los primeros 4 bytes a partir del byte enviado como dirección física dentro de la Memoria de Usuario.
#### WRITE MEM
Se escribirán los 4 bytes enviados a partir del byte enviado como dirección física dentro de la Memoria de Usuario y se responderá como OK.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by f-and** [comment]
Buenas Mauro!

Es como dicen, cada dirección de memoria contiene un byte. Lo que sí, van a terminar leyendo/escribiendo más de una posición en la memoria de usuario ya que tienen que usar 4 bytes.

Saludos.-

**Comment by SchincaMauroE** [comment]
Perfecto! Muchas gracias por la pronta respuesta! Saludos!
