### ISSUE TITLE
Consulta paso 5 de la creación de archivos en FS

### ISSUE THREAD

**Issue by AgustinaGuitman** [sisoputnfrba/foro#4391]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas, tenemos dudas acerca del contenido que se le pasa a filesystem desde memoria. Vimos que respondieron esta misma duda en el issue #4364 pero nosotros estamos haciendo el tp en C y no sabemos que es lo que cambia.

Desde ya muchas gracias, saludos!

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by LeandroCarbajales** [comment]
Buenas!
Conceptualmente la respuesta es la misma, deben enviarle todos los bytes de la partición asignada al proceso. A nivel implementación en C tendrían un void* en lugar de un array de bytes.

Les aclara la duda?
Saludos!
       Lean

**Comment by AgustinaGuitman** [comment]
Hola, si ahora entiendo. ¡Un millón de gracias!
Saludos
