### ISSUE TITLE
Duda sobre comportamiento de READ_MEM en RECURSOS_MUTEX_THREAD

### ISSUE THREAD

**Issue by KevinQ73** [sisoputnfrba/foro#4397]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas noches, estaba revisando las pruebas y veo que en RECURSOS_MUTEX_THREAD está el siguiente enunciado
```
SET DX 0
SET AX 14
SET CX 10
SET BX 1
SUB CX BX
MUTEX_LOCK MUTEX
READ_MEM DX AX
...
```

Suponiendo que la base del proceso es 1, el mutex MUTEX no esté tomado y no hay un caso de segmentation fault, veríamos que se setea el registro DX en 0, AX en 14, CX en 10, BX en 1 y se resta 10-1 quedando el registro CX en 9, de ahí se lockea el MUTEX y pasa a READ_MEM leyendo la dirección física 1+14 y el valor leído se lo almacena en DX.

Mi duda está en, se puede leer con READ_MEM si en la memoria de usuario no se escribió nada? En todo caso, en la prueba estaríamos queriendo leer valores vacíos o basura de la DF obtenida, que es lo que se debería almacenar en DX?

Talvez nuestro problema esté en que no comprendimos del todo la naturaleza de READ_MEM, espero puedan ayudarnos.

### 📔 Citas del documento de pruebas

READ MEM:
Se deberá devolver el valor correspondiente a los primeros 4 bytes a partir del byte enviado como
dirección física dentro de la Memoria de Usuario.

WRITE MEM:
Se escribirán los 4 bytes enviados a partir del byte enviado como dirección física dentro de la
Memoria de Usuario y se responderá como OK

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

La idea de `READ_MEM` y `WRITE_MEM` fue la de facilitar la implementación de lo que en C pueden ver como `memcpy()`, y al igual que en C, las funciones leen y/o escriben en un lugar donde no les importa si los bytes están inicializados o no.

Ahora bien, algo importante que creo que no estas teniendo en cuenta, es que la memoria se comparte entre TODOS los threads del mismo proceso y si leemos el proceso que crea los threads que usan el script `RECURSOS_MUTEX_THREAD`, vemos que la 3er instrucción escribe el valor 0 en la dirección lógica 14, con lo cual, aunque si bien con `READ_MEM` podrían leer un valor cualquiera en los threads, para este caso, el primer thread debería de leer un 0.

```
SET DX 0
SET AX 14
WRITE_MEM AX DX
```

Saludos.-

**Comment by KevinQ73** [comment]
Excelente, me había olvidado de ese detalle. De acá puedo asumir que siempre que se haga un `READ_MEM`, previamente se hará un `WRITE_MEM`? Como para preparar pruebas propias y tenerlo asumido para la entrega del TP. 

Entiendo que en sí nos debería dar igual porque si no hay nada escrito por nuestra cuenta en los bytes solicitados, si nos devuelve un número random por ser dato basura estaría perfecto, pero supongo que sería algo feo de probar eso, cualquier cosa estoy expectante a su respuesta.

Muchas gracias y que tengan un buen día.

**Comment by iago64** [comment]
Buenas! Cómo va?

No asumas nada, solo en este caso particular el valor va a estar pre-fijado porque hay un objetivo adicional aparte de probar el tema de los mutex, pero puede haber otra prueba que lea cualquier cosa solo por el hecho de leerlo y como decis, estaría bien que sea un número random.

Saludos.-

**Comment by KevinQ73** [comment]
Muchas gracias por la respuesta. Cierro issue
