### ISSUE TITLE
Registros en contextos de ejecución y utilidad syscalls de mutex

### ISSUE THREAD

**Issue by regueiranehuen** [sisoputnfrba/foro#4398]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Hola buenas tardes. Mi grupo y yo tenemos dudas sobre cómo deben manejarse los registros de los contextos de ejecución de los hilos. Citando el enunciado:

> Contextos de ejecución
> Se deberá almacenar, por cada PID del sistema, la parte del contexto de ejecución común para el proceso, en este caso, es la requerida para poder traducir las direcciones lógicas a físicas: base y límite.
> Luego, por cada TID del sistema, se tendrán los registros de la CPU propios de cada hilo: AX, BX, CX, DX, EX, FX, GX, HX y PC. Siendo todos ellos inicializados en 0.

Los contextos de hilos los tenemos modelados así:

```
typedef struct{
    int pid;
    int tid;
    t_registros_cpu*registros;
}t_contexto_tid;
```
Los registros:

```
typedef struct{
    uint32_t AX;
    uint32_t BX;
    uint32_t CX;
    uint32_t DX;
	uint32_t EX;
    uint32_t FX;
    uint32_t GX;
    uint32_t HX;
    uint32_t PC;
}t_registros_cpu; 
```

Entonces, cada vez que empieza a ejecutarse un hilo, independientemente si son del mismo proceso o no, inicializamos todos los registros del contexto en 0.  Así, si por ejemplo ejecutamos los siguientes pseudocódigos con FIFO:
Pseudocódigo del hilo 0
SET AX 1
THREAD_CREATE hilo1 1
IO 5000
LOG AX 
PROCESS_EXIT

Pseudocódigo hilo1:
SET AX 2
THREAD_EXIT

El LOG AX loggea un 1 y no un 2.  La forma en la que trabajamos es correcta? O todos los registros de los contextos de hilo (sin contar al program counter) deben ser compartidos entre hilos del mismo proceso?

Esto nos lleva a la segunda pregunta: Cuál sería la utilidad de las syscalls referidas a mutex? Porque de la forma en la que tenemos modelados los contextos nunca compartimos algo que podría considerarse "variable global" entre hilos

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Efectivamente, los contextos de ejecución son independientes, ahora algo importante y que al igual que ven en la teoría, es que la memoria si se comparte entre los hilos, entonces los mutex, al igual que en la teoría, sirven para delimitar los accesos a la memoria compartida.

Saludos.-

**Comment by regueiranehuen** [comment]
> Buenas! Cómo va?
> 
> Efectivamente, los contextos de ejecución son independientes, ahora algo importante y que al igual que ven en la teoría, es que la memoria si se comparte entre los hilos, entonces los mutex, al igual que en la teoría, sirven para delimitar los accesos a la memoria compartida.
> 
> Saludos.-

Perfecto muchas gracias!
