### ISSUE TITLE
duda sobre el deploy.sh

### ISSUE THREAD

**Issue by nicolasvultaggio** [sisoputnfrba/foro#4399]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas, tengo unas pequeñas dudas sobre el despliegue del tp y como funciona el deploy.sh
nosotros en el momento en el que tengamos las distintas terminales abiertas por ssh (supongamos que tenemos 4 computadoras distntas, una x modulo), tengo entendido que en cada una tendremos que instalar la commons, clonar el repositorio y cambiar las ips de cada config para que los modulos puedan conectarse, y se que hay un script de despligue que ayuda a hacer todo esto, pero no entiendo como se usa, o sea, yo primero bajo el repo mio de git y ahi clono el script de despliegue adentro? o primero clono el script de despliegue y este clona al repo? en sintesis, me genera muchas dudas las funcionalidades de este script, para que sirve, y el contexto en el que se aplica. Instala la commons tambien?

Además tengo entendido que con el deploy.sh puedo modificar todas las ips en todos los config del modulo cuando lo aplico, entonces, con hacer esto una vez al principio alcanza? o las ips podrían cambiar en medio de la prueba de forma que nosotros tengamos que tener preparada una forma de modificar las ips de todos los config del repo en medio de la prueba? la otra manera seria ir config por config pero esto sería medio engorroso

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

El deploy.sh no es mas que una herramienta que busca facilitarles el deploy, no es ni por cerca obligatoria de usar.
Ahora bien si quieren usar el script, solo tienen que indicarle los parámetros como estan especificados en el README del repo de deploy, entre ellos esta por ejemplo el nombre de su repo. 

Los parametros que reciben:
`-l` le agregan las libs como por ejemplo pthread
`-p` le indicas que "projectos" o carpetas tiene el tp
`-c` le indicas que config tiene que buscar en los archivos de config y cambiar

Ejemplo:
```bash
git clone https://github.com/sisoputnfrba/so-deploy.git
cd so-deploy
./deploy.sh -l=pthread -p=cpu -p=memoria -p=filesystem -p=kernel -c=IP_SERVER=192.168.0.32 tp-2022-1c-ejemplo
```

De todas formas siempre podes ver el repo de so-deploy que esta mas detallado el funcionamiento.


Saludos.-

**Comment by nicolasvultaggio** [comment]
Sisi, entiendo que funciona para eso y que no es obligatorio usarlo, pero quería entender como funciona para saber si usarlo o no.
Yo había leído el README, no se por qué no había entendido para que sirve el parametro -l, pero este mensaje me ayudó a entenderlo, y esa era mi duda principal, muchas gracias.
