### ISSUE TITLE
Contenido de memoria y luego para hacer el DUMP

### ISSUE THREAD

**Issue by inaaranza** [sisoputnfrba/foro#4400]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas!

Tengo una duda sobre qué tipo de dato es lo que se guarda siempre en la memoria. Yo lo tengo todo hecho como un void*. Osea, cada vez que escribo en la memoria, el contenido que recibo de CPU para escribir lo tomo como un void*. Está bien esto o lo podría tomar como un char*? Lo mismo para hacer el DUMP, como leo de memoria para enviar el contenido, yo lo estaba enviando como un void* pero finalmente pensé que puede ser de tipo char.
Muchas gracias :)

**Comment by iago64** [comment]
Buenas! Cómo va?

Esta bien que sea un `void*`, ya que para C toda la memoria es simplemente memoria, despues si lo ves como `char*` `int*` o `miestructuracustom*` en lo que te cambia es en que los desplazamientos dentro de la memoria son por el tamaño del puntero, pero con `void*` o `char*` el desplazamiento es igual y no hay ningun problema.

En las pruebas vamos a checkear el contenido con `xxd` o `hexdump` que muestran los valores en hexadecimal de lo que esta guardado en el archivo, que debería ser una copia de lo que esta en la memoria.

Saludos.-
