### ISSUE TITLE
Mal escrita las instrucciones READ_MEM y WRITE_MEM

### ISSUE THREAD

**Issue by tperezr** [sisoputnfrba/foro#4401]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas!
Las nuevas pruebas que subieron al repo tienen escritas al reves las instrucciones de read_mem y write_mem.

### 📔 Citas del documento de pruebas

- READ_MEM (Registro Datos, Registro Dirección): Lee el valor de memoria correspondiente a la dirección física obtenida a partir de la Dirección Lógica que se encuentra en el Registro Dirección y lo almacena en el Registro Datos.
- WRITE_MEM (Registro Dirección, Registro Datos): Lee el valor del Registro Datos y lo escribe en la dirección física de memoria obtenida a partir de la Dirección Lógica almacenada en el Registro Dirección.

```
SET CX 0
SET EX 4
SET AX 72
MEM_WRITE CX AX
SUM CX EX
SET AX 69
MEM_WRITE CX AX
```

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Gracias por el aviso, ya se encuentran corregidos los scripts de FIBO_*

Saludos.-
