### ISSUE TITLE
Cpu cierra inesperadamente.

### ISSUE THREAD

**Issue by AgustinaGuitman** [sisoputnfrba/foro#4402]
### 🖋️ Descripción

Buenas! 
Estamos tratando de correr la prueba PLANI PROC y nos esta pasando que después de pedir la syscall THREAD_CREATE a kernel, el módulo cpu se nos cierra (se cierra en el fetch cuando tiene q pedir la nueva instrucción (PC 3)). Nosotros estamos haciendo que cuando cpu le pide una syscall a kernel, le devuelva el contexto a memoria y deja de ejecutar ese proceso. Kernel hace lo que tiene que hacer de la syscall y lo vuelve a pasar a running mediante la conexión de cpu dispatch (excepto en los casos que tiene que replanificar). El problema viene cuando memoria le tiene que mandar de nuevo las instrucciones a cpu, nos tira un error de broken pipe y no entendemos el motivo. Corrimos valgrind y helgrind pero lo que nos dice no nos esta ayudando a resolver el problema. 
Les mandamos las consolas y lo que devuelve valgrind.  

memoria: 
![Imagen de WhatsApp 2024-11-25 a las 11 19 29_40d191b4](https://github.com/user-attachments/assets/2846401d-b1ab-4d43-9eca-b697fe3536cf)

cpu: 
![Imagen de WhatsApp 2024-11-25 a las 11 18 44_8dfb7356](https://github.com/user-attachments/assets/47b2ddef-c44c-4503-9b41-5d08858c3369)

kernel: 
![Imagen de WhatsApp 2024-11-25 a las 11 20 04_e478eefb](https://github.com/user-attachments/assets/72ad6dc3-3751-4b78-9754-385f1c17f6ea)

[memoria.txt](https://github.com/user-attachments/files/17904802/memoria.txt)
[cpu.txt](https://github.com/user-attachments/files/17904814/cpu.txt)
[kernel.txt](https://github.com/user-attachments/files/17904815/kernel.txt)

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Con los logs vamos a poder adivinar poco, pero para tener un poco de contexto, les dejo algunas preguntas:
Uds estan cerrando el socket en algun momento? 
Debuguearon la CPU para ver exactamente en que momento se cierra y por qué? 
Como tienen armado el "Servidor" en la CPU?

Saludos.-
