### ISSUE TITLE
Planificacion FIFO en C

### ISSUE THREAD

**Issue by JuanTerri** [sisoputnfrba/foro#4403]
### 🖋️ Descripción

Si yo tengo planificación FIFO, tengo mi hilo main con 5 instrucciones y la segunda instrucción es "thread_create" ¿Pasa a ejecutar ese hilo creado? quedando a la espera realizar las otras 3 instrucciones cuando finalice de ejecutar ese hilo creado?
O se terminan de ejecutar las 5 instrucciones que contiene mi hilo main y ahí recién continua a ejecutar ese hilo creado?

En la prueba de plani entiendo que deberían ejecutarse en el orden que se van creando pero según el enunciado entiendo que al crear un hilo se sigue ejecutando quien solicitó la creación y no se debería replanificar.

### 📚 Cito de enunciado

THREAD_CREATE, esta syscall recibirá como parámetro de la CPU el nombre del archivo de pseudocódigo que deberá ejecutar el hilo a crear y su prioridad. Al momento de crear el nuevo hilo, deberá generar el nuevo TCB con un TID autoincremental y poner al mismo en el estado READY.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Siguiendo los lineamientos teóricos en los que se basa el TP, **no deberían cambiar el hilo que ejecuta** ya que el THREAD_CREATE no es una syscall que bloquee al hilo.

Saludos.-

**Comment by JuanTerri** [comment]
Muchas gracias.
