### ISSUE TITLE
Prueba planificación con algoritmo prioridades

### ISSUE THREAD

**Issue by AgustinaGuitman** [sisoputnfrba/foro#4406]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas, estoy corriendo la prueba de planificación y cuando lo hago con prioridades, siempre se elige al hilo con tid 0 que tiene la mayor prioridad. El problema es que nunca llegan a ejecutar los otros hilos con menor prioridad ya que el tid 0 termina ejecutando un process exit (que nosotros hicimos que un process exit finalice todos los hilos del proceso) y los hilos poco prioritarios se mandan a finalizar sin haber podido ejecutar.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by LeandroCarbajales** [comment]
Buenas!
Es correcto que siempre se elija al tid0 por la prioridad, pero según [el archivo de código](https://github.com/sisoputnfrba/the-last-of-c-pruebas/blob/main/PLANI_PROC) la anteúltima instrucción del mismo es `THREAD_JOIN 4` por lo que en ese momento debería bloquearse hasta que finalice el tid4, dándole lugar a ejecutar a todo el resto de hilos.

**Comment by AgustinaGuitman** [comment]
Hola! Perfecto muchísimas gracias. Me surgió otra duda, cuando se hace el thread join el tid pasado por parámetro pasa directamente a running o tiene que respetar su turno según el algoritmo de planificación?

**Comment by LeandroCarbajales** [comment]
Nono, solamente bloquea al hilo que la llama, la planificación continúa normalmente. Por ejemplo, siguiendo un poco la lógica de la prueba, el hilo 4 al tener la prioridad más baja y ser el último en ser creado, seguramente ejecutará último.

**Comment by AgustinaGuitman** [comment]
Un millón de gracias, se re entendió.
Saludos
