### ISSUE TITLE
Duda sobre el retardo de los config. 

### ISSUE THREAD

**Issue by tomasRodriguezSpuch** [sisoputnfrba/foro#4409]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Hola, tenía una consulta, solo para confirmar, todos los valores de retardo que se deben usar para usleep, que son pasados por archivo de configuración (por ejemplo IO 600000), hay que multiplicarlos por 1000, no? Solo para saber si todos los valores temporales que se usan en usleep vienen en milisegundos, ya sea el parámetro de la instrucción IO, el retraso de peticiones en memoria o FS, o el QUANTUM.
Desde ya muchas gracias. 

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

El tiempo que se expresa en los configs es en milisegundos, si usan [`usleep()`](https://man7.org/linux/man-pages/man3/usleep.3.html) tienen que convertirlo a microsegundos.

Slaudos.-

**Comment by tomasRodriguezSpuch** [comment]
Buenisimo. Muchas gracias.
