### ISSUE TITLE
Consulta prueba MUTEX

### ISSUE THREAD

**Issue by DanielKesel** [sisoputnfrba/foro#4410]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas tardes ¿cómo están?
No estoy pudiendo entender los resultados esperados de la prueba Prueba Race Condition (ver cita). Estuve probando bastante, veo que en los 2 casos se bloquean algunos hilos y luego se van desbloqueando hasta en algún momento finalizar los hilos/proceso. Pero estoy haciendo la prueba con los 2 quantum requeridos y no veo una diferencia en los resultados sacando la diferencia que una prueba tarda más que la otra. Estoy leyendo lo que printeo del read_mem y las instrucciones LOG (0:0) DX entre otros y no entiendo como concluir si un resultado es deterministico y el otro no.
Por favor me podrán tirar un centro?
Muchas gracias y perdón las molestias.

### 📔 Citas del documento de pruebas

**Resultados Esperados**

- El valor final generado por los hilos sin mutex no es determinístico y puede no ser el esperado.
- El valor final generado por los hilos con mutex es correcto y determinístico.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by LeandroCarbajales** [comment]
Buenas!
Como punto de partida, corriendo la prueba con el quantum en 750, te da el mismo resultado final para ambos procesos? O alguno te da distinto?

**Comment by DanielKesel** [comment]
Buenas Lean ¿Cómo estás? gracias por la respuesta.
Los resultados para cada proceso (son solo 2)

**DEL PID1 TID 0**
LOG(DX) DEL PID 1 TID 0 = 10
READ_MEM DIR 46 = 10

**DEL PID 0 TID 0**
LOG(DX)  = 22
READ_MEM DIR 14 = 22

Otra consulta: ¿Es normal que esta prueba tarde más de 10 min?

Muchas gracias y saludos!

**Comment by LeandroCarbajales** [comment]
Perfecto, entonces el resultado final de ambos procesos te da distinto. Leyendo los archivos de código, no esperarías que el resultado final sea el mismo para ambos? O hay alguna diferencia que podría hacer que justamente el PID1 dé un resultado menor?
Una observación más que pueden hacer, al correrlo en cambio con Q en 3750, les da el mismo resultado que con 750 o varía el resultado de alguno de los procesos?

Con respecto al tiempo de la prueba de más de 10min, pueden acelerarlo reduciendo el tiempo de respuesta de memoria a 200ms por ejemplo.

**Comment by DanielKesel** [comment]
Con quantum 3750 los resultados son:

**DEL PID1 TID 0**
LOG(DX) DEL PID 1 TID 0 = 10 **(Se mantiene igual)**
READ_MEM DIR 46 = 10 **(Se mantiene igual)**

**DEL PID 0 TID 0**
LOG(DX) = 19 **(cambió respecto a la corrida con Q=750)**
READ_MEM DIR 14 = 19 **(cambió respecto a la corrida con Q=750)**

Lo que puedo observar es que claramente el proceso que NO lleva mutex da el mismo resultado independientemente el salto del Q mientras que el proceso que lleva mutex y realiza bloqueos y desbloqueos si varía. Por otro lado no se si estoy en lo correcto pero creo que la conclución simplemente sería que es correcto el numero mayor en el proceso del mutex ya que al bloquearse procesos realiza más operaciones en total. 
¿Estoy encaminado?
Muchas gracias!

**Comment by DanielKesel** [comment]
Perdón pero por temas de lógica de condicion de carrera estoy confundido, independientemente del Q si tienen NO tienen mutex da el mismo resultado pero si tienen mutex cambia... pero entiendo que la condición de carrera es que dependiendo como se ejecutan los proceso cambian los resultados cuando hay recursos compartidos... no debería variar el resultado sin mutex y mantenerme el resultado con mutex? muchas gracias!

**Comment by iago64** [comment]
Buenas! Cómo va?

¿Estas seguro que con los mutex da mas? ¿Estas siguiendo bien el orden de los procesos? Fijate las prioridades en el script, porque creo que estás viendo los resultados al reves.
Respecto a la condición de carrera, mucho cuidado porque es un tema teórico que entra tanto en parciales como en finales.

Saludos.-

**Comment by DanielKesel** [comment]
Buen día como están? Gracias por la respuesta y las preguntas que me ayudan a pensar mejor.
Les quiero mostrar cómo lo estoy pensando paso a paso a ver en qué me estoy equivocando:
El script inicial:
**RECURSOS_MUTEX_PROC**
SET DX 0
SET AX 14
WRITE_MEM AX DX
PROCESS_CREATE RECURSOS_RACE_PROC 16 **4**
MUTEX_CREATE MUTEX
THREAD_CREATE RECURSOS_MUTEX_THREAD **6**
THREAD_CREATE RECURSOS_MUTEX_THREAD **6**
THREAD_CREATE RECURSOS_MUTEX_THREAD **6**
THREAD_CREATE RECURSOS_MUTEX_THREAD **6**
**THREAD_JOIN 4**
READ_MEM DX AX
LOG DX
PROCESS_EXIT

Al ejecutar el primer proceso RECURSOS_MUTEX_PROC con tamaño 32, se crea el PID0 con su TID 0.
A partir del **THREAD_JOIN 4** se empieza a ejecutar el el proceso **RECURSOS_RACE_PROC** de prioridad **4** con PID 1. 

Observando el script del proceso **RECURSOS_RACE_PROC**
SET DX 0
SET AX 14
WRITE_MEM AX DX
THREAD_CREATE RECURSOS_RACE_THREAD 5
THREAD_CREATE RECURSOS_RACE_THREAD 5
THREAD_CREATE RECURSOS_RACE_THREAD 5
THREAD_CREATE RECURSOS_RACE_THREAD 5
THREAD_JOIN 4
SET AX 14
READ_MEM DX AX
**LOG DX** **_Este log es clave porque me va a indicar el valor final del proceso PID 1_**
PROCESS_EXIT

Hace el JOIN y entra a sus hilos:
SET DX 0
SET AX 14
SET CX 10
SET BX 1
SUB CX BX
READ_MEM DX AX
SUM DX BX
WRITE_MEM AX DX
LOG DX
JNZ CX 4
THREAD_EXIT

Por lo que observo los hilos del PID 1 no llevan MUTEX por lo que se van a ir ejecutando alternadamente debido al QUANTUM y a su instrucción JNZ que baja el valor del PC hasta que en un momento determinado el registro CX es 0, el PC no actualiza mas y el hilo se va a exit.
En este caso observo en el LOG DX del PID 1 y TID0 el valor 10. Tanto para el Q de 750 como el de 3750.

Una vez que finaliza el PID 1 se ejecutan los hilos del PID0 

SET DX 0
SET AX 14
SET CX 10
SET BX 1
SUB CX BX
MUTEX_LOCK MUTEX
READ_MEM DX AX
SUM DX BX
WRITE_MEM AX DX
MUTEX_UNLOCK MUTEX
LOG DX
JNZ CX 4
THREAD_EXIT

Acá es la misma lógica que los hilos del PID1 con la diferencia que estos llevan MUTEX, por lo que genera bloqueos y desbloqueos a lo largo de la ejecución. 
Al finalizar los hilos el LOG DX del PID 0 TID 0 es 19 si el QUANTUM es 750 y 22 si el QUANTUM es 3750.
Mientras escribía esto volví a correrlo pero con retardo de memoria en 200 para agilizar:
Los resultados fueron: 
**con Q=3750:**

DEL PID1 TID 0
LOG(DX) DEL PID 1 TID 0 = 13

DEL PID 0 TID 0
LOG(DX) = 37

**con Q=750:**
DEL PID 1 TID 0
LOG(DX)  = 18

DEL PID 0 TID 0
LOG(DX) = 25

Ahora con el retardo de respuesta en 200 (en vez de 1000) siempre me varían los valores finales de ambos procesos entre distintos QUANTUM.

Estoy leyendo los logs uno por uno y veo veo correcto el funcionamiento de ambos procesos. Logean lo que le corresponde al registro que llevaba el proceso en un determinado momento.

En conclusión sigo sin comprender donde puedo verificar el resultado determinístico o no.

Les pido disculpas por las molestias

**Comment by iago64** [comment]
Buenas! Cómo va?

Te invito a que saques la cabeza del teclado por 5 minutos y te pongas a pensar el "objetivo" de los scripts.
En todos los casos lo que vemos es que cada script por separado lo que hace es:
Leer una posición en memoria
Le suma 1
Escribir el resultado en la posición de memoria

Esto no es mas que obtener el valor de una variable y sumarle 1, que en nuestro lenguaje de scripts tiene un par de pasos extra porque son todas posiciones de memoria.

Ahora si los hijos ejecutasen solos por su cuenta que pasaría? entra el primero, va sumando de a 1 y va imprimiendo el resultado.
Ahora, que pasa si en el medio tenes otros hilos entrando a cambiar el valor de la variable... el resultado puede ser cualquier verdura, de hecho vos lo estas viendo cuando variando el quantum los resultados te dan cualquier cosa, y entonces el resultado final termina dependiendo del orden en el que se ejecutan las cosas, eso en la teoría ¿No tenía un nombre?.

Si ya hicimos el ejercicio teórico de entender lo que pasa en los scripts que se llaman `RECURSOS_RACE_*` que pasa en los otros, en los que se llaman `RECURSOS_MUTEX_*` ¿Qué le agregamos a los scripts? ¿Para qué usabamos las estructuras llamadas Mutex en la teoría? 

Si tenes las respuestas a las preguntas que te fui dejando y pudiste dejar de ver logs y picar teclas, deberías haberte dado cuenta que en los procesos que tienen mutex (`RECURSOS_MUTEX_*`), se debería dar una condición muy simple y es que no importa cuantas veces corras la prueba, el resultado no va a variar, mientras que en el otro caso... bueno... podemos decir que "puede fallar" (o no dar siempre el mismo resultado como te viene pasando)

Saludos.-

**Comment by DanielKesel** [comment]
Buenas tardes, muchas gracias por las aclaraciones,

Entiendo que el objetivo del ejercicio es analizar el comportamiento de los hilos con y sin mutex en relación con las condiciones de carrera.

**Para los hilos sin mutex (RECURSOS_RACE_*):**

Confirmo que los resultados varían dependiendo del quantum. Por ejemplo, con Q=750 y Q=3750, los valores finales del LOG(DX) en los hilos sin mutex cambian, lo que confirma que no son determinísticos.

**Para los hilos sin mutex (RECURSOS_MUTEX_*):**

Veo que los resultados finales del LOG(DX) deberían ser siempre los mismos para una configuración de quantum elegidad, porque los mutex sincronizan el acceso al recurso compartido.
En mis pruebas, con valores de Q=750 y Q=3750, los resultados con mutex cambian con distinto Q por lo qué mi conclusión final es que algo de mi prueba está mal. 

Ejemplo:
Volví a hacer la prueba con Retardo de memoria 1000 y con Q=750 me da el LOG final 22 y con Q=3750 me da 20 para los procesos con mutex por lo qué entiendo no deberían cambiar los resultados.

Tal véz el error esté que algo en mi codigo está desfasando el proceso respecto al QUANTUM, es dificil de explicar, por ejemplo nosotros ante una simultaneidad de un proceso que necesita ser bloqueado por una instrucción y un fin de QUANTUM priorizamos el proceso bloqueado por la instrucción con un if. No se si estará ahí el error, seguiré revisando.

**Comment by iago64** [comment]
Buenas! Cómo va?

La pregunta importante, ¿Cuando los hilos hacen MUTEX_LOCK, se llegan a bloquear esperando que otro les libere el MUTEX? Porque me da la sensación de que el problema esta en la sincro y no en los quantum.
Otra pregunta, ¿Los registros de los hilos, son propios de cada hilo verdad? ¿No hay nada compartido ahí no?

Saludos.-

**Comment by DanielKesel** [comment]
Respecto a la primera pregunta:
Sí, siempre que se bloquea un hilo  no se ejecutan hasta que otros los libere, o eso creía hasta el momento. Creo que ya encontré el error. Paso unos Logs que armé yo para hacer el seguimiento al tema. Al principio cuando TID 1 "entra" al mutex es porque adquirió el recurso, luego hasta que no sale del mutex ningun otro hilo se desbloquea. Luego el 1 sale del mutex y cuando el TID 2 dice "valor leído desde memoria" es que ya entró al mutex correspondiente. 
```
[ID:1] [INFO] 20:37:48:886 CPU/(382279:382302): -> (PID:TID) - (0:1) - SOLICITÓ RECURSO A KERNEL
[ID:2] [INFO] 20:37:48:886 CPU/(382279:382302): -> (PID:TID) - (0:1) - KERNEL LE RESPONDIÓ QUE HABÍA RECURSOS DISPONIBLES - ENTRA AL MUTEX
[ID:3] [INFO] 20:37:49:891 CPU/(382279:382302): -> (PID:TID) - (0:1) - Interrumpimos por fin de Quantum
[ID:4] [INFO] 20:37:51:989 CPU/(382279:382302): -> (PID:TID) - (0:2) - SOLICITÓ RECURSO A KERNEL
[ID:5] [INFO] 20:37:51:990 CPU/(382279:382302): -> (PID:TID) - (0:2) - KERNEL LE RESPONDIÓ QUE NO HABÍA RECURSOS DISPONIBLES - SE BLOQUEA EL PROCESO
[ID:6] [INFO] 20:37:55:090 CPU/(382279:382302): -> (PID:TID) - (0:3) - SOLICITÓ RECURSO A KERNEL
[ID:7] [INFO] 20:37:55:090 CPU/(382279:382302): -> (PID:TID) - (0:3) - KERNEL LE RESPONDIÓ QUE NO HABÍA RECURSOS DISPONIBLES - SE BLOQUEA EL PROCESO
[ID:8] [INFO] 20:37:58:184 CPU/(382279:382302): -> (PID:TID) - (0:4) - SOLICITÓ RECURSO A KERNEL
[ID:9] [INFO] 20:37:58:185 CPU/(382279:382302): -> (PID:TID) - (0:4) - KERNEL LE RESPONDIÓ QUE NO HABÍA RECURSOS DISPONIBLES - SE BLOQUEA EL PROCESO
[ID:10] [INFO] 20:38:02:277 CPU/(382279:382302): -> (PID:PID) - (0:1) - Valor leído desde memoria: 0
[ID:11] [INFO] 20:38:03:278 CPU/(382279:382302): -> (PID:TID) - (0:1) - Interrumpimos por fin de Quantum
[ID:12] [INFO] 20:38:06:384 CPU/(382279:382302): -> (PID:TID) - (0:1) - Interrumpimos por fin de Quantum
[ID:13] [INFO] 20:38:08:484 CPU/(382279:382302): -> (PID:TID) - (0:1) - Acción: ESCRIBIR - Dirección Física: AX EL VALOR: 1
[ID:14] [INFO] 20:38:10:486 CPU/(382279:382302): -> (PID:TID) - (0:1) - Interrumpimos por fin de Quantum
**[ID:15] [INFO] 20:38:12:594 CPU/(382279:382302): -> (PID:TID) - (0:1) - SALE DEL MUTEX**
[ID:16] [INFO] 20:38:13:601 CPU/(382279:382302): -> (PID:TID) - (0:1) - Interrumpimos por fin de Quantum
**[ID:17] [INFO] 20:38:16:719 CPU/(382279:382302): -> (PID:PID) - (0:2) - Valor leído desde memoria: 1**
[ID:18] [INFO] 20:38:17:720 CPU/(382279:382302): -> (PID:TID) - (0:2) - Interrumpimos por fin de Quantum
[ID:19] [INFO] 20:38:19:809 CPU/(382279:382302): -> (PID:TID) - (0:1) - LOG (DX): 1
[ID:20] [INFO] 20:38:20:810 CPU/(382279:382302): -> (PID:TID) - (0:1) - Interrumpimos por fin de Quantum
[ID:21] [INFO] 20:38:23:913 CPU/(382279:382302): -> (PID:TID) - (0:2) - Interrumpimos por fin de Quantum
[ID:22] [INFO] 20:38:27:007 CPU/(382279:382302): -> (PID:TID) - (0:1) - Interrumpimos por fin de Quantum
[ID:23] [INFO] 20:38:29:092 CPU/(382279:382302): -> (PID:TID) - (0:2) - Acción: ESCRIBIR - Dirección Física: AX EL VALOR: 2
[ID:24] [INFO] 20:38:31:094 CPU/(382279:382302): -> (PID:TID) - (0:2) - Interrumpimos por fin de Quantum
[ID:25] [INFO] 20:38:34:185 CPU/(382279:382302): -> (PID:TID) - (0:1) - Interrumpimos por fin de Quantum
**[ID:26] [INFO] 20:38:36:272 CPU/(382279:382302): -> (PID:TID) - (0:2) - SALE DEL MUTEX**
[ID:27] [INFO] 20:38:37:273 CPU/(382279:382302): -> (PID:TID) - (0:2) - Interrumpimos por fin de Quantum
**[ID:28] [INFO] 20:38:39:377 CPU/(382279:382302): -> (PID:TID) - (0:1) - SOLICITÓ RECURSO A KERNEL
[ID:29] [INFO] 20:38:39:378 CPU/(382279:382302): -> (PID:TID) - (0:1) - KERNEL LE RESPONDIÓ QUE HABÍA RECURSOS DISPONIBLES - ENTRA AL MUTEX**
[ID:30] [INFO] 20:38:40:379 CPU/(382279:382302): -> (PID:TID) - (0:1) - Interrumpimos por fin de Quantum
**[ID:31] [INFO] 20:38:43:465 CPU/(382279:382302): -> (PID:PID) - (0:3) - Valor leído desde memoria: 2**
[ID:32] [INFO] 20:38:44:466 CPU/(382279:382302): -> (PID:TID) - (0:3) - Interrumpimos por fin de Quantum

```
Como mencionaba, al principio el hilo 1 entra al mutex y no deja que el hilo 2, 3 y 4 entren.  Lo que estoy viendo extraño es lo siguiente. Siguiendo lo remarcado en negro en los logs de ID 15, 17, 26, 28 y 31, cuando TID 1 sale del mutex, arranca el TID 2 dentro del mutex (hasta ahí todo bien), luego el TID2 sale del mutex y el TID 1 vuelve a entrar al MUTEX, y por algún motivo el TID 3 entra al mutex también (ID 31) pero no pueden haber 2 hilos dentro del mutex.
Ahora voy a revisar bien por qué está sucediendo esto.
Gracias por la ayuda.

Con respecto a la segunda pregunta de los registros: Tenemos como dice el enunciado, cada hilo tiene sus propios registros a excepción de la base y el límite que es único para el proceso entero.

**Comment by LeandroCarbajales** [comment]
Excelente hallazgo @DanielKesel !
Conceptualmente lo que falta ahí es que al liberarse el mutex, se le debería asignar inmediatamente al hilo que sigue en su cola de bloqueados.
Por lo tanto, al salir el TID2 del mutex (en ID:26) debería asignarse inmediatamente al TID3 que es el siguiente que lo pidió. Por lo tanto, al volver a ejecutar TID1 y pedir el mutex, el Kernel debería responderle que no está disponible y bloquearlo/encolarlo.

**Comment by DanielKesel** [comment]
Buen día!, realizado lo mencionado logré pasar la prueba!

Muchas gracias a ambos por la ayuda!
