### ISSUE TITLE
Persistencia Bitmap y bloque de datos

### ISSUE THREAD

**Issue by inaaranza** [sisoputnfrba/foro#4411]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas!

Tengo una duda sobre el bitmap. Cuando ejecuto creo el bitmap y ocupo bloques les pongo el 1. Si doy de baja el modulo y lo levanto, deberia empezar el bitmap limpio de 0? O deberia mantener esos 1 y si sigo escribiendo ir llenando? La misma duda tengo con el bloque de datos
Muchas gracias:)

**Comment by iago64** [comment]
Buenas! Cómo va?

La idea de un FS es que si yo apago la PC (o bajo el módulo en este caso) y vuelvo a prender la PC (o levantar el módulo) los datos se persistan.

Saludos.-

**Comment by inaaranza** [comment]
Perfecto!

Muchas gracias :)
