### ISSUE TITLE
Prueba FS loop

### ISSUE THREAD

**Issue by tperezr** [sisoputnfrba/foro#4412]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas!
Puede ser que la prueba "PRUEBA_FS" este mal la instruccion JNZ? Porque estaria quedandose en un loop.
Saludos.

### 📔 Citas del documento de pruebas

```
SET AX 5
SET BX 1
PROCESS_CREATE FIBO_CROWN 96 0
PROCESS_CREATE FIBO_10 64 1
PROCESS_CREATE FIBO_20 128 1
PROCESS_CREATE FIBO_30 256 1
PROCESS_CREATE FIBO_40 256 1
PROCESS_CREATE FIBO_47 256 1
SUB AX BX
IO 30000
JNZ BX 3 <----- Deberia ser AX?
PROCESS_EXIT
```

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by tperezr** [comment]
Puede ser que el pesudo de "MEM_DINAMICA_PROC" tambien quede en un loop? AX siempre es 64
```
SET DX 0
SET AX 64
WRITE_MEM DX AX
READ_MEM BX DX
LOG BX
JNZ AX 0
PROCESS_EXIT
```

**Comment by tperezr** [comment]
Encontre otro mas en "THE_EMPTINESS_MACHINE". El registro BX siempre es 1 y nunca termina la ejecucion.

```
SET AX 10
SET BX 1
PROCESS_CREATE PLANI_PROC 16 0
PROCESS_CREATE RECURSOS_MUTEX_PROC 16 0
PROCESS_CREATE MEM_FIJA_BASE 12 0
PROCESS_CREATE MEM_DINAMICA_BASE 128 0
PROCESS_CREATE PRUEBA_FS 32 0
SUB AX BX
JNZ BX 2
PROCESS_EXIT
```

**Comment by iago64** [comment]
Buenas! Cómo va?

En los scripts `PRUEBA_FS` y `THE_EMPTINESS_MACHINE` si estaban mal los JNZ, en el caso de `MEM_DINAMICA_PROC` esta bien porque la idea es que esos procesos nunca finalicen para que no desalojen la memoria nunca.

Saludos.-
