### ISSUE TITLE
verificacion fs

### ISSUE THREAD

**Issue by nicolasvultaggio** [sisoputnfrba/foro#4413]
Una pregunta rapida sobre FILESYSTEM, cuando un archivo hace memory dump, el filesystem debe verificar que la cantidad de bloques (o sea la cantidad de punteros) necesarios para escribir todo el proceso en memoria, entre en el bloque de indices? 
O sea, si mis bloques son de 32 bytes, y mi tamaño de puntero son 4 bytes (como dice la consigna), entonces debemos verificar que la escritura del archivo en el FS no ocupe mas de 8 bloques de datos? o no se probara?

**Comment by iago64** [comment]
Buenas! Cómo va?

No hace falta, las pruebas de FS ya están subidas y pueden hace las cuentas previamente y controlar que **no vamos a probarles que tengan más punteros de los posibles**.

Saludos.-

**Comment by nicolasvultaggio** [comment]
perfecto, muchas gracias, buena semana
