### ISSUE TITLE
no se muestra el valor seteado en el metadata

### ISSUE THREAD

**Issue by nicolasvultaggio** [sisoputnfrba/foro#4414]
### 🖋️ Descripción

Buenas, con mi grupo recien llegamos a la prueba de FIBO, entonces, como nunca antes habiamos llegado al momento a probar un modulo que utilice tanto manejo de archivos o mapeos a memoria, nos estan saliendo muchas dudas. Las preguntas a continuacion son bastante "pavas" pero nos ayudarían mucho a saber si tenemos algo mal y no nos estamos dando cuenta.

1) Las computadoras en las que probaremos el FS ya tendran un directorio MOUNT_DIR creado como para que nosotros podramos levantar el filesystem? o deberemos crearlo en el despliegue? Pregunto porque nosotros para poder probarlo en el tp tuvimos que crearlo manualmente.

2) Puede ser que, por mas de que yo use CONFIG_SET_VALUE para configurar un valor en un metadata, este no se muestre si yo mantengo el archivo abierto en el editor de texto de visual studio? Porque usamos CONFIG_SET_VALUE para setear el valor, luego probamos leer el valor seteado con config_get_string_value y, efectivamente puede leerlo sin ningun tipo de error, sin embargo al abrir el archivo para ver el contenido escrito, aparece vacio, como si no se hubiera escrito.

Vemos que efectivamente puede conseguir los valores escritos, sin embargo:

![image](https://github.com/user-attachments/assets/e81e02c8-639f-4f07-a6df-6e06c1f2a94d)

se que no les gusta que se suban fotos, pero era la unica manera de mostrar que el contenido del archivo esta vacio y que los logs se dan correctamente.
 
 3) creo que estoy teniendo un error a la hora de escribir los archivos de bloques, ahora lo voy a probar bien que es lo que esta pasando, pero probablemente en un rato suba un issue distinto, pero si corrijo el error, aviso x este que no pasa nada

### 📚 Búsqueda en documentación/foros

Yo abri el metadata segun un issue que habia abierto hace varios meses #4041 
en ese momento no entendia mucho como funcionaban los configs

### 📄 Código relevante

```
void crear_archivo_metadata(char *nombre, int tamanio, int nro_bloque_indice){
   
    char * completo = concatenar_a_mount_dir(nombre);
    
    FILE * archivo = fopen(completo,"w");
    close(archivo);

    t_config *nueva_metadata = config_create(completo);

    escribir_en_metadata(nueva_metadata, "SIZE",tamanio);
    escribir_en_metadata(nueva_metadata, "INDEX_BLOCK",nro_bloque_indice);
    log_debug(logger,"Valor seteado en metadata: %s",config_get_string_value(nueva_metadata,"SIZE"));
    log_debug(logger,"Valor seteado en metadata: %s",config_get_string_value(nueva_metadata,"INDEX_BLOCK"));
    return;
}

void escribir_en_metadata(t_config * metadata,char * key, int valor){
   char * numero_en_string = string_itoa(valor);
   config_set_value(metadata, key,numero_en_string );
   free(numero_en_string);
   return;
}

char* concatenar_a_mount_dir(char * resto){
    char * barrita_que_falta = "/";
    char * completo=string_from_format("%s%s%s",filesystem_config->mount_dir,barrita_que_falta,resto);
    log_debug(logger,"Unido a MONTAJE: %s ----> %s",resto,completo);
    return completo;
}

```

### 🐛 Cómo reproducir el error

Lo unico que hice fue ejecutar normalmente, pero puse un breakpoint en la funcion crear_archivo_metadata, y porque recien ahi empiezan a existir los valores necesarios para poder crear el metadata.

### 💻 Logs

bueno, ya mostré todo en la foto

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

1.- El directorio lo pueden crear a mano antes de iniciar las pruebas, no hay problema con eso, tengan en cuenta que van a recibir una VM Server completamente limpia como la bajaron uds.

2.- El `config_set_value()` solamente les agrega el dato al diccionario de la config, despues tienen que usar el `config_save()` para que se persista y/o el `config_save_in_file()` para crear uno nuevo.

3.- Ok, si el error no le encuentran la vuelta creen un issue para el error y lo vemos :)

Saludos.-

**Comment by nicolasvultaggio** [comment]
perfecto! ahora lo pruebo, creo que pudimos solucionar el otro problema, por ahora cierro el issue, muchas gracias!
