### ISSUE TITLE
Prueba Plani CMN

### ISSUE THREAD

**Issue by AgustinaGuitman** [sisoputnfrba/foro#4415]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas! ¿Les podría preguntar cuanto tarda en ejecutarse una instrucción? Porque estoy probando el algoritmo de colas multinivel y me llama la atención que nunca hay interrupción por timer ya que los procesos siempre hacen una syscall antes de necesitar ser desalojados. 
Desde ya muchas gracias, saludos!

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Setearon bien los retardos de la memoria? recuerden que el valor de `RETARDO_RESPUESTA` es el **Tiempo en milisegundos que se deberá esperar antes de responder a las solicitudes de CPU.**

Saludos.-

**Comment by AgustinaGuitman** [comment]
Hola, gracias por la respuesta. Estamos haciendo que si kernel recibe una syscall no se desaloja el proceso por interrupción de timer (la idea era seguir la lógica de los ejercicios de planificación que hacemos en clase), imagino que debe ser eso lo que esta causando que nunca se desaloje por fin de quantum pero no se me ocurre otra forma de hacerlo.

**Comment by iago64** [comment]
Buenas! Cómo va?

Ojo con el tema de si reciben una syscall no bloquea al hilo, el mismo **SI** debería poder ser interrumpido por quantum.

Saludos.-

**Comment by AgustinaGuitman** [comment]
Gracias por la respuesta! Perdona pero aún no me queda claro si al recibir una syscall no se replanifica o si deberíamos pausar el reloj.

**Comment by RaniAgus** [comment]
¡Buenas! El pasaje a Kernel para ejecutar una syscall viene a representar un **cambio de contexto** (no una ráfaga de I/O). En la vida real, y en la teoría, la ejecución de la rutina de cada syscall siempre es una ráfaga de CPU en **modo kernel**, por lo que el proceso sigue estando en EXEC y puede ser interrumpido por fin de quantum.

Es por esto que no hay que resetear el quantum porque el proceso ejecuta una syscall.

Saludos

**Comment by AgustinaGuitman** [comment]
Hola, ahora entendí. ¡Muchas gracias a los dos! 
Saludos
