### ISSUE TITLE
Contenido guardado en el void* memoria

### ISSUE THREAD

**Issue by inaaranza** [sisoputnfrba/foro#4416]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas!

Tengo una duda respecto al formato en el que se guardan las cosas en el void* que representa la memoria. Al momento de hacer un WRITE_MEM, mi codigo es el siguiente:
```
//arriba hay mas codigo
   void *bytes_recibidos = malloc(4);
   recv(*fd_conexion, bytes_recibidos, 4, MSG_WAITALL);
   memcpy(MEMORIA + direccion, bytes_recibidos, 4);
   mem_hexdump(MEMORIA, 256);
   
   ```
   
Estoy realizando un ejemplo en el que se escribe el valor "64" en los primeros 4 bytes de la memoria. Cuando escribo el 64, al hacer el mem_hexdump(), figura que en los primeros 4 bytes se halla un "@" (el cual representa el 64 en ASCII). Mis dudas son: 
1) Está bien guardar el contenido en ASCII? Al momento de ver el contenido de la memoria en las pruebas, ¿no genera problema que esté en este formato?
Despues por otro lado si la CPU quiere realizar un READ_MEM y la memoria lee los primeros 4 bytes, le envía el "@". La CPU se encarga de ese "@" pasarlo a un valor entero y asignarselo al registro.
2) Si no hay problema en que el void* memoria tenga guardadas las cosas en ASCII, al momento de hacer un DUMP, en el archivo creado se debe escribir "@"? O se debe escribir "64"?

Muchas gracias:)

**Comment by iago64** [comment]
Buenas! Cómo va?

Algo interesante de la memoria es que el contenido son bytes y nada mas que bytes, despues si esos bytes representan que nosotros seteamos con `SET AX 64`, representan el caracter `@` o la cantidad de lingotes de Mantecol de 500gr que vamos a ingerir entre navidad y año nuevo es un problema del programa.

Ahora bien, dejando de lado el chiste del mantecol (que puede no serlo) nosotros para hacernos mas fácil la vida en las pruebas, siempre que tenemos un dump de memoria a un file system solemos jugar con esta bondad de la memoria que nos permite poner valores que despues se traducen facilmente a ascii para que cuando hagamos el hexdump del archivo veamos caracteres y saber que escribieron bien la memoria (De ahí que existe los scripts de `FIBO_CROWN` y `FIBO_SHOVEL`).

Dicho lo anterior, el contenido lo tienen que guardar en la memoria como `void *` y no tienen que preocuparse de la interpretación de los mismos.

Saludos.-

**Comment by inaaranza** [comment]
jajajajajajajaja perfecto entonces :)

Muchas gracias!
