### ISSUE TITLE
Volver a probar crear un proceso.

### ISSUE THREAD

**Issue by JuanTerri** [sisoputnfrba/foro#4417]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas, la duda que tengo es que si a la hora de no poder crear un proceso lo meto en la cola de procesos para que se vuelvan a crear, se finaliza un proceso entonces intento crear un proceso de esta cola de procesos, si justo llega la creacion de un proceso antes, este proceso no va a poder crearse, yo como lo saque de la cola estaba primero, ahora lo tengo que volver a meter en la cola ultimo? van a contemplar esta situacion que estoy describiendo?

### 📔 Citas del enunciado/videos

Se tendrá una cola NEW que será administrada estrictamente por FIFO para la creación de procesos. 
Al llegar un nuevo proceso a esta cola y la misma esté vacía se enviará un pedido a Memoria para inicializar el mismo. Si la respuesta es positiva, se crea el hilo 0 de ese proceso, se lo pasa al estado READY y se sigue la misma lógica con el proceso que sigue. Si la respuesta es negativa (ya que la Memoria no tiene espacio suficiente para inicializarlo) se deberá esperar la finalización de otro proceso para volver a intentar inicializarlo.
Al llegar un proceso a esta cola y haya otros esperando, el mismo simplemente se encola.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Creo que estas complicandola mas de lo que deberías.
Si no pueden crear un proceso lo dejan ahi en NEW y todos los que lleguen atras se van a ir encolando.
Al momento de finalizar un proceso van a la cola de NEW y se fijan cuantos pueden crear respetando el orden de llegada hasta que alguno no puedan crearlo o vacíen la cola (lo que ocurra primero)

Saludos.-

**Comment by JuanTerri** [comment]
Esta bien muchas gracias, me estaba complicando demasiado.
