### ISSUE TITLE
PROBLEMA CON LAS PRUEBA DE FIBONACCI

### ISSUE THREAD

**Issue by nicolasvultaggio** [sisoputnfrba/foro#4418]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Hola! estuvimos con mi grupo ejecutando la prueba de FIBONACCI y resulta que en ningún momento se nos ocupa el FILESYSTEM, quedan bloques libres por crearse. 
Estuvimos viendo el pseudocodigo de PRUEBA_FS:

> SET AX 5
SET BX 1
PROCESS_CREATE FIBO_CROWN 96 0
PROCESS_CREATE FIBO_10 64 1
PROCESS_CREATE FIBO_20 128 1
PROCESS_CREATE FIBO_30 256 1
PROCESS_CREATE FIBO_40 256 1
PROCESS_CREATE FIBO_47 256 1
SUB AX BX
IO 30000
JNZ AX 3
PROCESS_EXIT

 Suponiendo que cada vez que se ejecuta JNZ vuelve a la instruccion 3, siendo la instruccion 3 "PROCESS_CREATE FIBO_10 64 1",hicimos las cuentas matemáticamente, y creemos que en total deberían crearse 26 procesos.
1x 96bytes
+
5x64bytes
+
5x128bytes
+
15x256bytes
= 4896bytes de procesos que hace memory dump

dividiendo estos bytes por el tamaño de bloque (32 bytes) vemos que esto es un total de 153 bloques de datos, mas un total de 26 bloques de indices, lo que significa que, en total, en todo el fs se ocupan 179 bloques, sobrando 21 de los 200 totales.

Estuvimos viendo el respositorio de pruebas, y vimos que hay un archivo de pseudocodigo que nunca se usa, uno llamado FIBO_SHOVEL, revisando todos los pseudocodigos posibles, nunca se crea un proceso que usa este archivo como codigo.

Suponemos 3 causas para este problema:
-El mencionado, nunca se crea un proceso de programa FIBO_SHOVEL
- la instruccion JNZ en PRUEBA_FS debería decir JNZ AX  2 y no JNZ AX 3, ya que las instrucciones se empiezan a contar desde 0, no desde 1, para, por cada iteracion de JNZ, crear un proceso de programa FIBO_CROWN.
- Las instrucciones en realidad se comienzan a contar desde 1, lo que significa que en realidad nuestro grupo realizo una interpretacion incorrecta de la instruccion JNZ y eso hace que el proceso 0, por cada verificacion del registro AX, se "saltee" un proceso cuyo programa sea FIBO_CROWN

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Vamos en orden con algunas cosas:

1.- FIBO_SHOVEL no se usa, es verdad, pero no se olviden que en las [Normas del Trabajo Práctico](https://docs.utnso.com.ar/primeros-pasos/normas-tp#etapas-de-la-evaluacion) se menciona que:

> Durante las últimas 2 (dos) semanas antes de la fecha de la evaluación práctica se comunicará un documento de pruebas tentativas a realizarse durante la misma. Sin embargo, el mismo será de carácter informativo solamente, pudiendo cambiar el formato de evaluación de acuerdo a cómo sea considerado por los evaluadores.

Es decir, nos dejamos un script y podríamos subir mas en estos días o armar uno en el momento en caso de que lo necesitemos.

2.- El JNZ esta bien, FIBO_CROWN no lo queremos ejecutar mas de 1 vez, por eso hacemos el JNZ al 3 que sería la línea donde esta la inscricción `PROCESS_CREATE FIBO_10 64 1`

Saludos.-

**Comment by nicolasvultaggio** [comment]
Okey, entonces creo que ya entendimos lo que hicimos mal, en la primera ejecucion, no se completa el filesystem, pero al volver a ejecutarlo, NO se debe reiniciar el FS, o sea, el bitmap de bloques debe mantenerse, de forma que, ante una segunda ejecucion, todos los procesos finalizan. Nuestra implementacion, resetea el bitmap ante cada nueva ejecucion, esto no debe ser asi, por lo que entendemos, correcto?

**Comment by iago64** [comment]
Buenas! Cómo va?

Exacto, no tienen que reiniciar el bitmap, pensa que con su implementación es como si cada vez que prendes la PC, tuvieras que instalar Linux, Windows o MacOS para usarla porque se pierde todo lo guardado, o peor, prende el SO pero como los bloques estan libres cualquier escritura te pisara los archivos del SO.

Saludos.-

**Comment by nicolasvultaggio** [comment]
listo, tiene sentido, muchisimas gracias por la paciencia

**Comment by nicolasvultaggio** [comment]
Entonces para la prueba 6, que es de 8192 bloques de 64 bytes, que hacemos con los 200 de 32 bytes? Ahí como es una prueba distinta y un FS distinto, lo iniciamos de 0?

**Comment by f-and** [comment]
Buenas Nicolas! Solo para avisar, mientras que en la prueba de FS se solicita ejecutar de nuevo las pruebas, esta configuración no se acarrea hacia la prueba de estrés, y tampoco las pruebas anteriores se mantienen (si se llegaran a mantener) para pruebas anteriores, por lo que, en la entrega, seguro comprobamos los datos del file system después de correr la prueba, pero de ahí les vamos a pedir que eliminen los datos del mount_dir así pueden correr la prueba de estrés.

**Comment by nicolasvultaggio** [comment]
perfecto, muchas gracias! nos vemos el sábado!
