### ISSUE TITLE
Consulta Prueba FS

### ISSUE THREAD

**Issue by jagrivero** [sisoputnfrba/foro#4419]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buen día, quería consultar por la prueba de filesystem. 
El proceso FIBO_CROWN tiene 96 bytes, ocupa 3 bloques. Luego hay 5 iteraciones para crear los procesos FIBO_10, FIBO_20, FIBO_30, FIBO_40 y FIBO_47, con tamaños 64, 128, 256, 256 y 256 bytes respectivamente. Serían 960 bytes por iteración, que ocupan 30 bloques de datos. Serían 153 bloques entre las 3 iteraciones, además de 26 bloques de índices (podrían ser más, pero como cada bloque puede direccionar a 8 bloques de datos, ningún archivo precisa de más de un bloque de índices).
Concluyendo, ocupamos 179 bloques de los 200 disponibles en total.
Queríamos saber si podía haber un error en el resultado esperado en la prueba o es un error nuestro nomás con esta implementación lo que genera esta diferencia. 
Desde ya, muchas gracias.

### 📔 Citas del documento de pruebas

Resultados Esperados: Llega un momento en el cual no se pueden hacer mas DUMP porque se llena el FS.
FileSystem.config
BLOCK_SIZE=32. BLOCK_COUNT=200. RETARDO_ACCESO_BLOQUE=500

### 👍 Comportamiento esperado

El filesystem agota el espacio de bloques en el archivo bloques.dat

### 👎 Comportamiento obtenido

El filesystem aún tiene espacio en el archivo de bloques. 

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Por favor lean la prueba completa, en el punto 3 se pide que vuelvan a iniciar la prueba pero NO tienen que reiniciar el FS.

Saludos.-
