### ISSUE TITLE
Duda de file system (donde guardar los archivos)

### ISSUE THREAD

**Issue by curtiFacundo** [sisoputnfrba/foro#4420]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Hola, como estan?
Mi duda surge, en en donde tengo que guardar los archivos que se generan en el file system (bitmap.dat,bloques.dat y los archivos de metadata)
En el enunciado del tp dice que tiene que ir guardado en una carpeta MOUNT_DIR, pero esa va dentro de nuestro tp? mi pregunta surge porque MOUNT_DIR se le pasa por parametro en el .config, entonces como es? interpreto que o esta dentro del tp (generar de alguna forma la ruta) o la tiene que buscar dentro del mismo sistema, pero no me queda claro cual de las 2 es

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by f-and** [comment]
Buenas Facundo!
La segunda opción sería la más razonable, fijate que en el doc del TP indicamos de ejemplo:
`MOUNT_DIR=/home/utnso/mount_dir`
Por lo que, cualquier archivo se tiene que leer desde este punto (por ejemplo /home/utnso/mount_dir/bitmap.dat).
Para adentrarte un toque más te recomiendo la [guía de rutas relativas y absolutas](https://docs.utnso.com.ar/guias/consola/rutas), lo que tendrían que implementar son rutas absolutas.

**Comment by curtiFacundo** [comment]
Ok, entiendo eso, y si no existe me tendria que tirar un warning por ruta no existente?

**Comment by RaniAgus** [comment]
¡Buenas! Podrían hacer cualquiera de las dos siguientes alternativas:
1. Tirar un warning por ruta no existente y finalizar, asumiendo que los archivos deben estar creados a mano.
2. Crear los archivos desde código, para no tener que crear los archivos a mano antes de ejecutar las pruebas que lo requieran (**recomendado**).

Saludos

**Comment by curtiFacundo** [comment]
Perfecto, muchas gracuas por la solucion
