### ISSUE TITLE
Duda sobre prueba stress "THE_EMPTINESS_MACHINE"

### ISSUE THREAD

**Issue by tperezr** [sisoputnfrba/foro#4421]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas!
Me esta pasando en la prueba mencionada en el titulo que cuando llega a la prueba de MEM_DINAMICA_BASE se queda en un loop (que es el objetivo) pero no me terminan los demas procesos. En el documento menciona que todos los procesos deberian terminar, a excepcion de los procesos creados en MEM_DINAMICA_BASE?
Creo que monopolizan la ram, ocupando en total 7680 bytes y teniendo prioridad 0 ejecutan siempre.
Puedo estar equivocado, pero queria consultarlo para asegurarme.
Gracias!

### 📔 Citas del documento de pruebas

Esperar a que todos los procesos finalicen.

```
SET AX 10
SET BX 1
PROCESS_CREATE PLANI_PROC 16 0
PROCESS_CREATE RECURSOS_MUTEX_PROC 16 0
PROCESS_CREATE MEM_FIJA_BASE 12 0
PROCESS_CREATE MEM_DINAMICA_BASE 128 0    <-- Esta prueba nunca termina, entonces nunca terminaria la prueba completa
PROCESS_CREATE PRUEBA_FS 32 0
SUB AX BX
JNZ AX 2
PROCESS_EXIT
```

MEM_DINAMICA_BASE 
```
PROCESS_CREATE MEM_DINAMICA_PROC_FIN 64 0
PROCESS_CREATE MEM_DINAMICA_PROC_FIN 128 0
PROCESS_CREATE MEM_DINAMICA_PROC_FIN 64 0
PROCESS_CREATE MEM_DINAMICA_PROC 256 0
PROCESS_CREATE MEM_DINAMICA_PROC 64 0
PROCESS_CREATE MEM_DINAMICA_PROC_FIN 64 0
PROCESS_CREATE MEM_DINAMICA_PROC 320 0
PROCESS_CREATE MEM_DINAMICA_PROC 64 0
PROCESS_CREATE MEM_DINAMICA_PROC 64 0
SET DX 0
SET AX 64
WRITE_MEM DX AX
READ_MEM BX DX
LOG BX
IO 600000
PROCESS_EXIT
```

### 👍 Comportamiento esperado

Esperar a que todos los procesos finalicen.

### 👎 Comportamiento obtenido

No todos los procesos finalizan.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Ahi se ajustó la redacción de la prueba, el objetivo de la misma es validar esperas activas, memory leaks y/o comportamientos erraticos en la estabilidad y es verdad, hay algunos scripts que no finalizan ya que se pensaron para la prueba de memoria donde no queremos que esos procesos terminen.

Saludos.-

**Comment by tperezr** [comment]
Excelente, gracias!

**Comment by longonicolas** [comment]
Hola! A nuestro grupo le pasa algo similar en este test. 
Kernel comienza a desbloquear hilos y la ejecucion nunca finaliza (o no lo sabemos ya que son muchos hilos), este comportamiento es el esperado para dicho test?
