### ISSUE TITLE
Duración test FS

### ISSUE THREAD

**Issue by zakerik10** [sisoputnfrba/foro#4423]
### 🖋️ Descripción

Estoy ejecutando las pruebas del FS, el test de Fibonacci Sequence, pero el test prácticamente no me termina de ejecutar.
Al principio se genera un MEMORY_DUMP, pero después pueden pasar como unos 15, 20 minutos, que recién me aparecen algunos mas, y sigue con la ejecución.

Eso es normal?

### 📝 Normas del foro

- [x] Leí los lineamientos del foro

**Comment by f-and** [comment]
Buenas! 
La verdad es que creería que no, igual estaría bueno que publiques algunas capturas de pantalla para saber exactamente como se están ejecutando los procesos. 
A muy simple vista, diría que se fijen los tiempos de retardo y que sleep usan, recuerden que los retardos están dados en milisegundos, por lo que si ponen un sleep y no un usleep podrían estar demorando el proceso justamente por 5 a 10 mins por cada acceso a un bloque.
Saludos.-

**Comment by zakerik10** [comment]
En realidad no es que se demora mucho por que tiene tiempos de retardo largos, el test ejecuta "rápido". Lo que pasa es que queda bastante tiempo ejecutando entre ciertos procesos. Para tener una idea, los logs me generan miles de líneas, teniendo los logs mínimos y muy poco mas.

Por bastante rato se quedan ejecutando los procesos de prioridad 0
![image](https://github.com/user-attachments/assets/40a1f8db-f259-4e37-8803-2bb67d9fbd05)

Despues pasan los de prioridad 1
![image](https://github.com/user-attachments/assets/fa24f131-9f2c-4c99-90b4-48458a2092d7)

En el medio se generan algunos MEMORY_DUMP, unas 5 aprox, hasta que llega un punto que se me crashea, llega algún punto donde algún dato que se envía, esta roto.

**Comment by f-and** [comment]
Bueno, por un lado habría que ver el crash que te causa, por el otro, viendo los tiempos de ejecución, no veo que se demore significativamente, por lo que debería estar corriendo bien, y por ultimo, algo me hace ruido con las PID, porque contando los procesos que se generan me da 7 procesos en total (El PID debería quedar en 6), por lo que se me hace raro ver que tenes 11 procesos corriendo, estas con la prueba de FS no?

**Comment by f-and** [comment]
Ah, no había leído el IO, si, mirando el resto es probable que la prueba tarde poco más de 10 minutos, considerando el retraso, si quieren apurar la prueba mientras esten testeando las cosas pueden bajar los valores de la config, lo que sí, el crash se puede dar porque se llena el FS, fijense que se cumplan las condiciones pedidas por el docu de pruebas.

**Comment by zakerik10** [comment]
Ese es el tema, no se termina de llenar el FS, por que no se terminan de hacer los dumps, simplemente los procesos se quedan dando vueltas

**Comment by f-and** [comment]
En ese caso hay que ver los logs para ver que es lo que está fallando, prueben reduciendo los retrasos a ver si se ejecuta correctamente o si se rompe en alguna parte.

**Comment by zakerik10** [comment]
Pudimos avanzar algo, pero aun asi, hay algo que no cuadra
Probé ejecutar el test, pero a cada archivo FIBO_X, le saque la instrucción JNZ, para que haga el dump de forma directa, para ver cuantos se hacían.
Haciendo esto nos dimos cuenta que había una falla en la memoria, con respecto al particionamiento, en el momento de que se eliminaba un proceso, cosa que se solucionó
De esta manera, ya no tira fallas la ejecución, ejecutando todo los dumps, dejándonos en el FS 21 bloques libres
Después cuando vuelvo a ejecutar la prueba, ya esta vez hay muchos procesos que no pueden hacer dump por que no hay espacio en disco (cosa que estaría bien)

Después quiero volver a ejecutar todos los tests, pero esta vez devolviendo cada JNZ que había sacado anteriormente
De esta manera no termina como la ejecución anterior
Esta vez en la primer ejecución, me quedan 118 bloques libres, y no 21 como la anterior vez
Obviamente si vuelvo a ejecutar, todos los dumps se vuelven a guardar

**Comment by f-and** [comment]
Buenas, disculpa la tardanza, haciendo las cuentas, les deberían quedar muchos menos bloques libres que esos, por si las dudas les recomiendo actualizarse al ultimo commite de las pruebas porque estuvimos haciendo unas modificaciones en base a la primera entrega.
Si te queda alguna duda del issue, avisa, pero si no, te solicito cerrar el issue y abrir uno nuevo en caso que te surga otra duda!
Saludos.-

**Comment by f-and** [comment]
Buenas, cierro el Issue, por inactividad.
