### ISSUE TITLE
Prueba Race Condition

### ISSUE THREAD

**Issue by AgustinaGuitman** [sisoputnfrba/foro#4424]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas! Estamos corriendo la prueba de race condition y no se terminan de ejecutar todos los scripts porque quedan todos los hilos bloqueados por mutex. No sabemos si es lo esperado o si tenemos que cambiar algo. Adjuntamos los últimos logs que nos aparecen.
Desde ya muchas gracias. 

### 👎 Comportamiento obtenido

[INFO] 13:39:58:065 KERNEL/(41422:41451): ## Finaliza el proceso <1>
[INFO] 13:39:58:066 KERNEL/(41422:41451): PID <0> TID: <1> - Estado Anterior: READY - Estado Actual: EXEC
[INFO] 13:39:59:689 KERNEL/(41422:41451): ## (PID <0> TID: <1> ) - Solicitó syscall: <MUTEX_LOCK>
[INFO] 13:39:59:689 KERNEL/(41422:41451): PID <0> TID: <1> - Estado Actual: EXEC
[INFO] 13:40:01:329 KERNEL/(41422:41451): ## (PID <0> TID: <1> ) - Solicitó syscall: <MUTEX_UNLOCK>
[INFO] 13:40:01:329 KERNEL/(41422:41451): PID <0> TID: <1> - Estado Actual: EXEC
[INFO] 13:40:02:556 KERNEL/(41422:41451): ## (PID <0> TID: <1> ) - Solicitó syscall: <MUTEX_LOCK>
[INFO] 13:40:02:556 KERNEL/(41422:41451): ## (PID <0> : TID <1>) - Bloqueado por: <MUTEX>
[INFO] 13:40:02:556 KERNEL/(41422:41451): PID <0> TID: <2> - Estado Anterior: READY - Estado Actual: EXEC
[INFO] 13:40:04:172 KERNEL/(41422:41451): ## (PID <0> TID: <2> ) - Solicitó syscall: <MUTEX_LOCK>
[INFO] 13:40:04:172 KERNEL/(41422:41451): ## (PID <0> : TID <2>) - Bloqueado por: <MUTEX>
[INFO] 13:40:04:172 KERNEL/(41422:41451): PID <0> TID: <3> - Estado Anterior: READY - Estado Actual: EXEC
[INFO] 13:40:05:790 KERNEL/(41422:41451): ## (PID <0> TID: <3> ) - Solicitó syscall: <MUTEX_LOCK>
[INFO] 13:40:05:790 KERNEL/(41422:41451): ## (PID <0> : TID <3>) - Bloqueado por: <MUTEX>
[INFO] 13:40:05:790 KERNEL/(41422:41451): PID <0> TID: <4> - Estado Anterior: READY - Estado Actual: EXEC
[INFO] 13:40:07:448 KERNEL/(41422:41451): ## (PID <0> TID: <4> ) - Solicitó syscall: <MUTEX_LOCK>
[INFO] 13:40:07:448 KERNEL/(41422:41451): ## (PID <0> : TID <4>) - Bloqueado por: <MUTEX>

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by f-and** [comment]
Buenas Agustina!

No es el resultado esperado por dos detalles:
Uno, el más chico, es que no está detectando la razón de bloqueo por lo que solo muestra "Bloqueado por:", esto no parecería tanto error si no fuera por lo segundo; hay una falla en la lógica de los Mutex, fijate que el TID 1 eta bloqueando el Mutex, despues lo desbloquea y finalmente lo bloquea nuevamente, pero en esta ultima vez queda bloqueado el hilo aunque debería mantenerse ejecutando (el estado del Mutex haría 1 (estado inicial) -> 0 (primer bloqueo) -> 1 (desbloqueo) -> 0 (segundo bloqueo), nunca bajaría de 0), y con eso se te acarrea a lo demás, ya que no se están desbloqueando correctamente los recursos y no continúa la ejecución como debería.

Saludos.-

**Comment by AgustinaGuitman** [comment]
Buenas, perfecto muchas gracias.

Saludos.
