### ISSUE TITLE
Problema early EOF en el deploy con PUTTY

### ISSUE THREAD

**Issue by MartinSintas** [sisoputnfrba/foro#4425]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

Buenas, que tal? Estamos queriendo correr las pruebas en los labos de medrano y estamos siguiendo la guía de despliegue a la perfección, sin embargo al hacer el git clone post el script del readme.

### 📔 Citas del documento de pruebas

```
utnso@utnso:~/so-deploy$ git clone https://github.com/sisoputnfrba/tp-2024-2c-GOlazo
Cloning into 'tp-2024-2c-GOlazo'...
Username for 'https://github.com': MartinSintas
Password for 'https://MartinSintas@github.com':
remote: Enumerating objects: 3378, done.
remote: Counting objects: 100% (1327/1327), done.
remote: Compressing objects: 100% (312/312), done.
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
error: 3129 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
utnso@utnso:~/so-deploy$
```

Tengo entendido que esto pasa por un problema de wifi, también sé que antes estos casos el ayudante seleccionado se encarga de bajar el repo como zip y después se unzipea pero desconozco como hacerlo

**Comment by LeandroCarbajales** [comment]
Buenas!
Correcto, es un problema de internet/red del laboratorio.
Prueben corriendo `git config --global http.postBuffer 157286400` e intentando nuevamente.
