### ISSUE TITLE
problemas por conexion ssh

### ISSUE THREAD

**Issue by nicolasvultaggio** [sisoputnfrba/foro#4426]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Hola! Que tal? estamos probando el despliegue en los laboratorios, y resulta que, a la hora de conectarnos a las maquinas virtuales que ya están instaladas por SSH, en algunas computadoras, por algún motivo, y aleatoriamente parece, no funcionan las conexiones por ssh. Pero no es que se copien mal las ips (verificamos que se usan bien), directamente no puede reconocer el comando ssh:

>C:\Users\ALUMNO>ssh
"ssh" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

Esto a que puede deberse? podría pasarnos mañana en la entrega?

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by LeandroCarbajales** [comment]
Buenas!
Probaron conectarse usando [PuTTY](https://docs.utnso.com.ar/guias/herramientas/deploy#putty)?

**Comment by iago64** [comment]
Buenas! Cómo va?

Aprovecho a recordarles que hay una [Guía de despliegue de TP](https://docs.utnso.com.ar/guias/herramientas/deploy) donde pueden tener algo mas de info y les recomendamos que la vean antes de presentarse a la entrega.

Saludos.-

**Comment by nicolasvultaggio** [comment]
si, revisamos la guia, y tambien por si acaso el tp0, pero en ningun momento se menciona que pasa si no se reconoce el comando ssh, además es algo que en algunas computadoras funciona y en otras no, o sea, nosotros literalmente en alguns compus hacemos los mismos pasos que otra y se puede conectar y en otras no. Con PUTTY probamos y funcionó, pero al momento de usar el script de despliegue nos devuelve un error de early EOF, pero ahi vimos que en otro issue se propuso una solucion

**Comment by f-and** [comment]
Buenas Nicolas, Windows es un sistema operativo muy traicionero, y las compus del labo lo son aun más ;P considera que algunas pueden no tener instalado el paquete de SSH, pero esto no les va a importar en lo que concerne a las entregas ya que nosotros vamos un poco antes de los primeros horarios para validar que las computadoras que les demos tienen todo en orden. 
Para lo que les preocupa a ustedes acostumbrense a PuTTY que sirve mejor para lo que tienen que hacer y les permite desplegar más rapido.

**Comment by nicolasvultaggio** [comment]
okey, muchas gracias!!! perdon por la molestia
