### ISSUE TITLE
Reintentar cargar procesos que no pudieron ser cargados 

### ISSUE THREAD

**Issue by sgorbea** [sisoputnfrba/foro#4427]
### 🛠️ Lenguaje
C

En Kernel tenemos una duda sobre la carga de los procesos que no pudieron ser cargados por falta de espacio en memoria. Cuando se quita un proceso de memoria, intentamos cargar uno de los que no se pudo cargar. 
Siempre debo cargar primero el que esta en la primera posicion en la lista de pendientes de carga, o puedo cargar otro que si entre en el espacio de memoria liberado ?

**Comment by f-and** [comment]
Buenas! 

Citando del enunciado:
> Creación de Procesos
> Se tendrá una cola NEW que será administrada estrictamente por **FIFO** para la creación de procesos. 

Por lo que siempre se maneja el primero que llego en la cola, y no van a empezar procesos hasta que este entre en el espacio en memoria.
Saludos.-
