### ISSUE TITLE
Error doble free or corruption (fasstop) - Prueba FS

### ISSUE THREAD

**Issue by Sebastian-Faingerch** [sisoputnfrba/foro#4428]
### 🖋️ Descripción

Buenas como va? 

Estábamos corriendo la prueba de FS, cuando nos tira este error que no vimos nunca, nos resulta muy raro y no sabemos bien por donde podría venir el error,

![image](https://github.com/user-attachments/assets/625f212e-24e1-4b2e-90f7-581616c48bd1)

Esto ocurre después de que el proceso se destruye

Creemos que podría venir una vez que libera el espacio en memoria pero no vemos free de mas o algo por el estilo

Si nos podrían orientar, estaría genial

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by f-and** [comment]
Buenas Sebastian, el Double Free que mencionan puede ser por una variedad de razones dentro del código y habría que ver cada una de las funciones que se llama porque justamente se intenta liberar dos veces, lo que les puedo recomendar es que sigan la [guía de Valgrind y Helgrind](https://docs.utnso.com.ar/guias/herramientas/valgrind) ya que les puede llegar a mostrar donde se está causando este primer y segundo free.
Saludos.-
