### ISSUE TITLE
Resultados de prueba FS

### ISSUE THREAD

**Issue by DanielKesel** [sisoputnfrba/foro#4429]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas tardes! ¿Cómo están?
Si bien los resultados esperados de a prueba de FS es que se llene el FILESYSTEM en la 2da corrida... eso lo estamos logrando pero al leer los resultados no arroja una frase en concreto sino letras asi:
![image](https://github.com/user-attachments/assets/5080a5b4-0def-4277-a0a2-6bbfaeb376cd)
¿Es correcto?
Muchas gracias y saludos

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by DanielKesel** [comment]
estuve haciendo las cuentas manual y para el fibo_crown imprimimos una frase puntual, para el resto no

**Comment by iago64** [comment]
Es tal cual, solo FIBO_CROWN escribe, los demas son números.
