### ISSUE TITLE
Consulta resultado PRUEBA_FS

### ISSUE THREAD

**Issue by MartinSintas** [sisoputnfrba/foro#4430]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

Hola! estaba revisando los issues anteriores y en el #4419 se mencionan que utilizan 179 bloques.  Ejecute la prueba y en el caso de mi equipo utilizamos 39 bloques en total (33 para datos y 6 para índices), quería saber si esto es correcto o si me estoy equivocando en algo fundamental que no me estoy dando cuenta

### 📔 Citas del documento de pruebas

dejo como esta quedando el hexdump 

![image](https://github.com/user-attachments/assets/04bdb78c-826a-4e99-9543-99afcc0c119d)

### 👎 Comportamiento obtenido

2024/11/29 22:02:37 Me llego un solicitud de un proceso PID: 0 TID: 1 para un dump memory
2024/11/29 22:02:37 Bloque 0 marcado como ocupado en el bitmap.
2024/11/29 22:02:37 Bloque 1 marcado como ocupado en el bitmap.
2024/11/29 22:02:37 Bloque 2 marcado como ocupado en el bitmap.
2024/11/29 22:02:37 Bloque 3 marcado como ocupado en el bitmap.
2024/11/29 22:02:37 Directorio /home/utnso/mount_dir/files/ creado.
2024/11/29 22:02:37 Archivo de metadata para <1>-<0>-<20241129-220237>.dmp-1732917757.dmp creado correctamente.
2024/11/29 22:02:37 Bloque 0 actualizado correctamente en bloques.dat.
2024/11/29 22:02:37 Bloque 0 actualizado correctamente en bloques.dat.
2024/11/29 22:02:37 Bloque 0 actualizado correctamente en bloques.dat.
2024/11/29 22:02:37 Bloque 1 actualizado correctamente en bloques.dat.
2024/11/29 22:02:37 Acceso al bloque 1 - Tipo: DATA
2024/11/29 22:02:37 [32m## Bloque asignado: 1 - Archivo: <1>-<0>-<20241129-220237>.dmp-1732917757.dmp - Bloques Libres: 196[0m
2024/11/29 22:02:37 Acceso completado.
2024/11/29 22:02:37 Bloque 2 actualizado correctamente en bloques.dat.
2024/11/29 22:02:37 Acceso al bloque 2 - Tipo: DATA
2024/11/29 22:02:37 [32m## Bloque asignado: 2 - Archivo: <1>-<0>-<20241129-220237>.dmp-1732917757.dmp - Bloques Libres: 196[0m
2024/11/29 22:02:38 Acceso completado.
2024/11/29 22:02:38 Bloque 3 actualizado correctamente en bloques.dat.
2024/11/29 22:02:38 Acceso al bloque 3 - Tipo: DATA
2024/11/29 22:02:38 [32m## Bloque asignado: 3 - Archivo: <1>-<0>-<20241129-220237>.dmp-1732917757.dmp - Bloques Libres: 196[0m
2024/11/29 22:02:38 Acceso completado.
2024/11/29 22:02:38 [32m## Archivo Creado: <1>-<0>-<20241129-220237>.dmp-1732917757.dmp - Tamaño: 96[0m
2024/11/29 22:02:38 [38;5;205mArchivo DUMP <1>-<0>-<20241129-220237>.dmp-1732917757.dmp creado con éxito (PID: 1, TID: 0).
[0m
2024/11/29 22:03:08 Me llego un solicitud de un proceso PID: 0 TID: 3 para un dump memory
2024/11/29 22:03:08 Bloque 4 marcado como ocupado en el bitmap.
2024/11/29 22:03:08 Bloque 5 marcado como ocupado en el bitmap.
2024/11/29 22:03:08 Bloque 6 marcado como ocupado en el bitmap.
2024/11/29 22:03:08 Bloque 7 marcado como ocupado en el bitmap.
2024/11/29 22:03:08 Bloque 8 marcado como ocupado en el bitmap.
2024/11/29 22:03:08 Archivo de metadata para <3>-<0>-<20241129-220308>.dmp-1732917788.dmp creado correctamente.
2024/11/29 22:03:08 Bloque 4 actualizado correctamente en bloques.dat.
2024/11/29 22:03:08 Bloque 4 actualizado correctamente en bloques.dat.
2024/11/29 22:03:08 Bloque 4 actualizado correctamente en bloques.dat.
2024/11/29 22:03:08 Bloque 4 actualizado correctamente en bloques.dat.
2024/11/29 22:03:08 Bloque 5 actualizado correctamente en bloques.dat.
2024/11/29 22:03:08 Acceso al bloque 5 - Tipo: DATA
2024/11/29 22:03:08 [32m## Bloque asignado: 5 - Archivo: <3>-<0>-<20241129-220308>.dmp-1732917788.dmp - Bloques Libres: 191[0m
2024/11/29 22:03:08 Acceso completado.
2024/11/29 22:03:08 Bloque 6 actualizado correctamente en bloques.dat.
2024/11/29 22:03:08 Acceso al bloque 6 - Tipo: DATA
2024/11/29 22:03:08 [32m## Bloque asignado: 6 - Archivo: <3>-<0>-<20241129-220308>.dmp-1732917788.dmp - Bloques Libres: 191[0m
2024/11/29 22:03:09 Acceso completado.
2024/11/29 22:03:09 Bloque 7 actualizado correctamente en bloques.dat.
2024/11/29 22:03:09 Acceso al bloque 7 - Tipo: DATA
2024/11/29 22:03:09 [32m## Bloque asignado: 7 - Archivo: <3>-<0>-<20241129-220308>.dmp-1732917788.dmp - Bloques Libres: 191[0m
2024/11/29 22:03:09 Acceso completado.
2024/11/29 22:03:09 Bloque 8 actualizado correctamente en bloques.dat.
2024/11/29 22:03:09 Acceso al bloque 8 - Tipo: DATA
2024/11/29 22:03:09 [32m## Bloque asignado: 8 - Archivo: <3>-<0>-<20241129-220308>.dmp-1732917788.dmp - Bloques Libres: 191[0m
2024/11/29 22:03:10 Acceso completado.
2024/11/29 22:03:10 [32m## Archivo Creado: <3>-<0>-<20241129-220308>.dmp-1732917788.dmp - Tamaño: 128[0m
2024/11/29 22:03:10 [38;5;205mArchivo DUMP <3>-<0>-<20241129-220308>.dmp-1732917788.dmp creado con éxito (PID: 3, TID: 0).
[0m
2024/11/29 22:03:11 Me llego un solicitud de un proceso PID: 0 TID: 4 para un dump memory
2024/11/29 22:03:11 Bloque 9 marcado como ocupado en el bitmap.
2024/11/29 22:03:11 Bloque 10 marcado como ocupado en el bitmap.
2024/11/29 22:03:11 Bloque 11 marcado como ocupado en el bitmap.
2024/11/29 22:03:11 Bloque 12 marcado como ocupado en el bitmap.
2024/11/29 22:03:11 Bloque 13 marcado como ocupado en el bitmap.
2024/11/29 22:03:11 Bloque 14 marcado como ocupado en el bitmap.
2024/11/29 22:03:11 Bloque 15 marcado como ocupado en el bitmap.
2024/11/29 22:03:11 Bloque 16 marcado como ocupado en el bitmap.
2024/11/29 22:03:11 Bloque 17 marcado como ocupado en el bitmap.
2024/11/29 22:03:11 Archivo de metadata para <4>-<0>-<20241129-220311>.dmp-1732917791.dmp creado correctamente.
2024/11/29 22:03:11 Bloque 9 actualizado correctamente en bloques.dat.
2024/11/29 22:03:11 Bloque 9 actualizado correctamente en bloques.dat.
2024/11/29 22:03:11 Bloque 9 actualizado correctamente en bloques.dat.
2024/11/29 22:03:11 Bloque 9 actualizado correctamente en bloques.dat.
2024/11/29 22:03:11 Bloque 9 actualizado correctamente en bloques.dat.
2024/11/29 22:03:11 Bloque 9 actualizado correctamente en bloques.dat.
2024/11/29 22:03:11 Bloque 9 actualizado correctamente en bloques.dat.
2024/11/29 22:03:11 Bloque 9 actualizado correctamente en bloques.dat.
2024/11/29 22:03:11 Bloque 10 actualizado correctamente en bloques.dat.
2024/11/29 22:03:11 Acceso al bloque 10 - Tipo: DATA
2024/11/29 22:03:11 [32m## Bloque asignado: 10 - Archivo: <4>-<0>-<20241129-220311>.dmp-1732917791.dmp - Bloques Libres: 182[0m
2024/11/29 22:03:11 Acceso completado.
2024/11/29 22:03:11 Bloque 11 actualizado correctamente en bloques.dat.
2024/11/29 22:03:11 Acceso al bloque 11 - Tipo: DATA
2024/11/29 22:03:11 [32m## Bloque asignado: 11 - Archivo: <4>-<0>-<20241129-220311>.dmp-1732917791.dmp - Bloques Libres: 182[0m
2024/11/29 22:03:12 Acceso completado.
2024/11/29 22:03:12 Bloque 12 actualizado correctamente en bloques.dat.
2024/11/29 22:03:12 Acceso al bloque 12 - Tipo: DATA
2024/11/29 22:03:12 [32m## Bloque asignado: 12 - Archivo: <4>-<0>-<20241129-220311>.dmp-1732917791.dmp - Bloques Libres: 182[0m
2024/11/29 22:03:12 Acceso completado.
2024/11/29 22:03:12 Bloque 13 actualizado correctamente en bloques.dat.
2024/11/29 22:03:12 Acceso al bloque 13 - Tipo: DATA
2024/11/29 22:03:12 [32m## Bloque asignado: 13 - Archivo: <4>-<0>-<20241129-220311>.dmp-1732917791.dmp - Bloques Libres: 182[0m
2024/11/29 22:03:13 Acceso completado.
2024/11/29 22:03:13 Bloque 14 actualizado correctamente en bloques.dat.
2024/11/29 22:03:13 Acceso al bloque 14 - Tipo: DATA
2024/11/29 22:03:13 [32m## Bloque asignado: 14 - Archivo: <4>-<0>-<20241129-220311>.dmp-1732917791.dmp - Bloques Libres: 182[0m
2024/11/29 22:03:13 Acceso completado.
2024/11/29 22:03:13 Bloque 15 actualizado correctamente en bloques.dat.
2024/11/29 22:03:13 Acceso al bloque 15 - Tipo: DATA
2024/11/29 22:03:13 [32m## Bloque asignado: 15 - Archivo: <4>-<0>-<20241129-220311>.dmp-1732917791.dmp - Bloques Libres: 182[0m
2024/11/29 22:03:14 Acceso completado.
2024/11/29 22:03:14 Bloque 16 actualizado correctamente en bloques.dat.
2024/11/29 22:03:14 Acceso al bloque 16 - Tipo: DATA
2024/11/29 22:03:14 [32m## Bloque asignado: 16 - Archivo: <4>-<0>-<20241129-220311>.dmp-1732917791.dmp - Bloques Libres: 182[0m
2024/11/29 22:03:14 Acceso completado.
2024/11/29 22:03:14 Bloque 17 actualizado correctamente en bloques.dat.
2024/11/29 22:03:14 Acceso al bloque 17 - Tipo: DATA
2024/11/29 22:03:14 [32m## Bloque asignado: 17 - Archivo: <4>-<0>-<20241129-220311>.dmp-1732917791.dmp - Bloques Libres: 182[0m
2024/11/29 22:03:15 Acceso completado.
2024/11/29 22:03:15 [32m## Archivo Creado: <4>-<0>-<20241129-220311>.dmp-1732917791.dmp - Tamaño: 256[0m
2024/11/29 22:03:15 [38;5;205mArchivo DUMP <4>-<0>-<20241129-220311>.dmp-1732917791.dmp creado con éxito (PID: 4, TID: 0).
[0m
2024/11/29 22:03:16 Me llego un solicitud de un proceso PID: 0 TID: 5 para un dump memory
2024/11/29 22:03:16 Bloque 18 marcado como ocupado en el bitmap.
2024/11/29 22:03:16 Bloque 19 marcado como ocupado en el bitmap.
2024/11/29 22:03:16 Bloque 20 marcado como ocupado en el bitmap.
2024/11/29 22:03:16 Bloque 21 marcado como ocupado en el bitmap.
2024/11/29 22:03:16 Bloque 22 marcado como ocupado en el bitmap.
2024/11/29 22:03:16 Bloque 23 marcado como ocupado en el bitmap.
2024/11/29 22:03:16 Bloque 24 marcado como ocupado en el bitmap.
2024/11/29 22:03:16 Bloque 25 marcado como ocupado en el bitmap.
2024/11/29 22:03:16 Bloque 26 marcado como ocupado en el bitmap.
2024/11/29 22:03:16 Archivo de metadata para <5>-<0>-<20241129-220316>.dmp-1732917796.dmp creado correctamente.
2024/11/29 22:03:16 Bloque 18 actualizado correctamente en bloques.dat.
2024/11/29 22:03:16 Bloque 18 actualizado correctamente en bloques.dat.
2024/11/29 22:03:16 Bloque 18 actualizado correctamente en bloques.dat.
2024/11/29 22:03:16 Bloque 18 actualizado correctamente en bloques.dat.
2024/11/29 22:03:16 Bloque 18 actualizado correctamente en bloques.dat.
2024/11/29 22:03:16 Bloque 18 actualizado correctamente en bloques.dat.
2024/11/29 22:03:16 Bloque 18 actualizado correctamente en bloques.dat.
2024/11/29 22:03:16 Bloque 18 actualizado correctamente en bloques.dat.
2024/11/29 22:03:16 Bloque 19 actualizado correctamente en bloques.dat.
2024/11/29 22:03:16 Acceso al bloque 19 - Tipo: DATA
2024/11/29 22:03:16 [32m## Bloque asignado: 19 - Archivo: <5>-<0>-<20241129-220316>.dmp-1732917796.dmp - Bloques Libres: 173[0m
2024/11/29 22:03:16 Acceso completado.
2024/11/29 22:03:16 Bloque 20 actualizado correctamente en bloques.dat.
2024/11/29 22:03:16 Acceso al bloque 20 - Tipo: DATA
2024/11/29 22:03:16 [32m## Bloque asignado: 20 - Archivo: <5>-<0>-<20241129-220316>.dmp-1732917796.dmp - Bloques Libres: 173[0m
2024/11/29 22:03:17 Acceso completado.
2024/11/29 22:03:17 Bloque 21 actualizado correctamente en bloques.dat.
2024/11/29 22:03:17 Acceso al bloque 21 - Tipo: DATA
2024/11/29 22:03:17 [32m## Bloque asignado: 21 - Archivo: <5>-<0>-<20241129-220316>.dmp-1732917796.dmp - Bloques Libres: 173[0m
2024/11/29 22:03:17 Acceso completado.
2024/11/29 22:03:17 Bloque 22 actualizado correctamente en bloques.dat.
2024/11/29 22:03:17 Acceso al bloque 22 - Tipo: DATA
2024/11/29 22:03:17 [32m## Bloque asignado: 22 - Archivo: <5>-<0>-<20241129-220316>.dmp-1732917796.dmp - Bloques Libres: 173[0m
2024/11/29 22:03:18 Acceso completado.
2024/11/29 22:03:18 Bloque 23 actualizado correctamente en bloques.dat.
2024/11/29 22:03:18 Acceso al bloque 23 - Tipo: DATA
2024/11/29 22:03:18 [32m## Bloque asignado: 23 - Archivo: <5>-<0>-<20241129-220316>.dmp-1732917796.dmp - Bloques Libres: 173[0m
2024/11/29 22:03:18 Acceso completado.
2024/11/29 22:03:18 Bloque 24 actualizado correctamente en bloques.dat.
2024/11/29 22:03:18 Acceso al bloque 24 - Tipo: DATA
2024/11/29 22:03:18 [32m## Bloque asignado: 24 - Archivo: <5>-<0>-<20241129-220316>.dmp-1732917796.dmp - Bloques Libres: 173[0m
2024/11/29 22:03:19 Acceso completado.
2024/11/29 22:03:19 Bloque 25 actualizado correctamente en bloques.dat.
2024/11/29 22:03:19 Acceso al bloque 25 - Tipo: DATA
2024/11/29 22:03:19 [32m## Bloque asignado: 25 - Archivo: <5>-<0>-<20241129-220316>.dmp-1732917796.dmp - Bloques Libres: 173[0m
2024/11/29 22:03:19 Acceso completado.
2024/11/29 22:03:19 Bloque 26 actualizado correctamente en bloques.dat.
2024/11/29 22:03:19 Acceso al bloque 26 - Tipo: DATA
2024/11/29 22:03:19 [32m## Bloque asignado: 26 - Archivo: <5>-<0>-<20241129-220316>.dmp-1732917796.dmp - Bloques Libres: 173[0m
2024/11/29 22:03:20 Acceso completado.
2024/11/29 22:03:20 [32m## Archivo Creado: <5>-<0>-<20241129-220316>.dmp-1732917796.dmp - Tamaño: 256[0m
2024/11/29 22:03:20 [38;5;205mArchivo DUMP <5>-<0>-<20241129-220316>.dmp-1732917796.dmp creado con éxito (PID: 5, TID: 0).
[0m
2024/11/29 22:03:21 Me llego un solicitud de un proceso PID: 0 TID: 6 para un dump memory
2024/11/29 22:03:21 Bloque 27 marcado como ocupado en el bitmap.
2024/11/29 22:03:21 Bloque 28 marcado como ocupado en el bitmap.
2024/11/29 22:03:21 Bloque 29 marcado como ocupado en el bitmap.
2024/11/29 22:03:21 Bloque 30 marcado como ocupado en el bitmap.
2024/11/29 22:03:21 Bloque 31 marcado como ocupado en el bitmap.
2024/11/29 22:03:21 Bloque 32 marcado como ocupado en el bitmap.
2024/11/29 22:03:21 Bloque 33 marcado como ocupado en el bitmap.
2024/11/29 22:03:21 Bloque 34 marcado como ocupado en el bitmap.
2024/11/29 22:03:21 Bloque 35 marcado como ocupado en el bitmap.
2024/11/29 22:03:21 Archivo de metadata para <6>-<0>-<20241129-220321>.dmp-1732917801.dmp creado correctamente.
2024/11/29 22:03:21 Bloque 27 actualizado correctamente en bloques.dat.
2024/11/29 22:03:21 Bloque 27 actualizado correctamente en bloques.dat.
2024/11/29 22:03:21 Bloque 27 actualizado correctamente en bloques.dat.
2024/11/29 22:03:21 Bloque 27 actualizado correctamente en bloques.dat.
2024/11/29 22:03:21 Bloque 27 actualizado correctamente en bloques.dat.
2024/11/29 22:03:21 Bloque 27 actualizado correctamente en bloques.dat.
2024/11/29 22:03:21 Bloque 27 actualizado correctamente en bloques.dat.
2024/11/29 22:03:21 Bloque 27 actualizado correctamente en bloques.dat.
2024/11/29 22:03:21 Bloque 28 actualizado correctamente en bloques.dat.
2024/11/29 22:03:21 Acceso al bloque 28 - Tipo: DATA
2024/11/29 22:03:21 [32m## Bloque asignado: 28 - Archivo: <6>-<0>-<20241129-220321>.dmp-1732917801.dmp - Bloques Libres: 164[0m
2024/11/29 22:03:21 Acceso completado.
2024/11/29 22:03:21 Bloque 29 actualizado correctamente en bloques.dat.
2024/11/29 22:03:21 Acceso al bloque 29 - Tipo: DATA
2024/11/29 22:03:21 [32m## Bloque asignado: 29 - Archivo: <6>-<0>-<20241129-220321>.dmp-1732917801.dmp - Bloques Libres: 164[0m
2024/11/29 22:03:22 Acceso completado.
2024/11/29 22:03:22 Bloque 30 actualizado correctamente en bloques.dat.
2024/11/29 22:03:22 Acceso al bloque 30 - Tipo: DATA
2024/11/29 22:03:22 [32m## Bloque asignado: 30 - Archivo: <6>-<0>-<20241129-220321>.dmp-1732917801.dmp - Bloques Libres: 164[0m
2024/11/29 22:03:22 Acceso completado.
2024/11/29 22:03:22 Bloque 31 actualizado correctamente en bloques.dat.
2024/11/29 22:03:22 Acceso al bloque 31 - Tipo: DATA
2024/11/29 22:03:22 [32m## Bloque asignado: 31 - Archivo: <6>-<0>-<20241129-220321>.dmp-1732917801.dmp - Bloques Libres: 164[0m
2024/11/29 22:03:23 Acceso completado.
2024/11/29 22:03:23 Bloque 32 actualizado correctamente en bloques.dat.
2024/11/29 22:03:23 Acceso al bloque 32 - Tipo: DATA
2024/11/29 22:03:23 [32m## Bloque asignado: 32 - Archivo: <6>-<0>-<20241129-220321>.dmp-1732917801.dmp - Bloques Libres: 164[0m
2024/11/29 22:03:23 Acceso completado.
2024/11/29 22:03:23 Bloque 33 actualizado correctamente en bloques.dat.
2024/11/29 22:03:23 Acceso al bloque 33 - Tipo: DATA
2024/11/29 22:03:23 [32m## Bloque asignado: 33 - Archivo: <6>-<0>-<20241129-220321>.dmp-1732917801.dmp - Bloques Libres: 164[0m
2024/11/29 22:03:24 Acceso completado.
2024/11/29 22:03:24 Bloque 34 actualizado correctamente en bloques.dat.
2024/11/29 22:03:24 Acceso al bloque 34 - Tipo: DATA
2024/11/29 22:03:24 [32m## Bloque asignado: 34 - Archivo: <6>-<0>-<20241129-220321>.dmp-1732917801.dmp - Bloques Libres: 164[0m
2024/11/29 22:03:24 Acceso completado.
2024/11/29 22:03:24 Bloque 35 actualizado correctamente en bloques.dat.
2024/11/29 22:03:24 Acceso al bloque 35 - Tipo: DATA
2024/11/29 22:03:24 [32m## Bloque asignado: 35 - Archivo: <6>-<0>-<20241129-220321>.dmp-1732917801.dmp - Bloques Libres: 164[0m
2024/11/29 22:03:25 Acceso completado.
2024/11/29 22:03:25 [32m## Archivo Creado: <6>-<0>-<20241129-220321>.dmp-1732917801.dmp - Tamaño: 256[0m
2024/11/29 22:03:25 [38;5;205mArchivo DUMP <6>-<0>-<20241129-220321>.dmp-1732917801.dmp creado con éxito (PID: 6, TID: 0).
[0m
2024/11/29 22:03:26 Me llego un solicitud de un proceso PID: 0 TID: 2 para un dump memory
2024/11/29 22:03:26 Bloque 36 marcado como ocupado en el bitmap.
2024/11/29 22:03:26 Bloque 37 marcado como ocupado en el bitmap.
2024/11/29 22:03:26 Bloque 38 marcado como ocupado en el bitmap.
2024/11/29 22:03:26 Archivo de metadata para <2>-<0>-<20241129-220326>.dmp-1732917806.dmp creado correctamente.
2024/11/29 22:03:26 Bloque 36 actualizado correctamente en bloques.dat.
2024/11/29 22:03:26 Bloque 36 actualizado correctamente en bloques.dat.
2024/11/29 22:03:26 Bloque 37 actualizado correctamente en bloques.dat.
2024/11/29 22:03:26 Acceso al bloque 37 - Tipo: DATA
2024/11/29 22:03:26 [32m## Bloque asignado: 37 - Archivo: <2>-<0>-<20241129-220326>.dmp-1732917806.dmp - Bloques Libres: 161[0m
2024/11/29 22:03:26 Acceso completado.
2024/11/29 22:03:26 Bloque 38 actualizado correctamente en bloques.dat.
2024/11/29 22:03:26 Acceso al bloque 38 - Tipo: DATA
2024/11/29 22:03:26 [32m## Bloque asignado: 38 - Archivo: <2>-<0>-<20241129-220326>.dmp-1732917806.dmp - Bloques Libres: 161[0m
2024/11/29 22:03:27 Acceso completado.
2024/11/29 22:03:27 [32m## Archivo Creado: <2>-<0>-<20241129-220326>.dmp-1732917806.dmp - Tamaño: 64[0m
2024/11/29 22:03:27 [38;5;205mArchivo DUMP <2>-<0>-<20241129-220326>.dmp-1732917806.dmp creado con éxito (PID: 2, TID: 0).
[0m

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Los 39 bloques estan bien si solo corrieron 1 vez cada uno de los scripts FIBO_* que se encuentran en el script de PRUEBA_FS, si se fijan la prueba de FS hace 5 iteraciones de los 6 procesos.

Saludos.-

**Comment by MartinSintas** [comment]
Perfecto Dami, me quedo tranquilo entonces, muchas gracias.
