### ISSUE TITLE
Cantidad de instrucciones al ejecutar quantum

### ISSUE THREAD

**Issue by inaaranza** [sisoputnfrba/foro#4431]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas!

Estamos realizando las pruebas de race condition y tenemos un problema y es que, cuando un hilo comienza a ejecutar (q = 3750), a veces ejecuta 1 instruccion antes de ser bloqueado por quantum y a veces ejecuta 2. El tema que nos ocurre es que el hilo 4 capaz hace el thread_exit antes que otro hilo, por esto de que en alguna vuelta capaz ejecutó 2 instrucciones y asi, entonces cuando finaliza, se desbloquea el hilo 0. Cuando se desbloquea el hilo 0, por ser el de mayor prioridad, ejecuta hasta el final y no deja que los otros hilos que le quedaron sus ultimas instrucciones ejecuten. 
Por este tema de que a veces el hilo 4 termina antes que otros hilos, el resultado de la prueba nos da siempre entre 38 y 40. La implementacion que tenemos sobre el mutex funciona bien, pero nos liquida que el hilo 4 pueda terminar antes que otros.
Si bajamos el quantum a 750, el cual siempre termina ejecutando de a 1 instruccion, el resultado de la prueba siempre es el mismo (40).

Muchas gracias:)

**Comment by iago64** [comment]
Buenas! Cómo va?

En base al feedback que tuvimos de la 1er fecha de evaluación acabamos de subir unos cambios en una nueva rama de los scripts de pruebas (https://github.com/sisoputnfrba/the-last-of-c-pruebas/tree/fix/feedback-entrega) por las dudas tambien se agregaron algunos THREAD_JOIN en la prueba de MUTEX, ya no deberías tener mas problemas de que termine el proceso principal antes de que terminen los threads hijos.

Saludos.-

**Comment by inaaranza** [comment]
Joya! Muchísimas gracias!!
