### ISSUE TITLE
Resultado particiones dinamicas

### ISSUE THREAD

**Issue by sgorbea** [sisoputnfrba/foro#4432]
Buenas, tengo una consulta, el resultado esperado es que se deben ingresar los procesos a la planifiacion de largo plazo, puede ser que en ese resultado que espero, haya un proceso que no puede entrar a la memoria ??
Creo que cambiando el algoritmo de busqueda ingresan todos, pero no estoy seguro.

**Comment by iago64** [comment]
Buenas! Cómo va?

Acabamos de subir en una nueva rama en el [repo de scripts](https://github.com/sisoputnfrba/the-last-of-c-pruebas/tree/fix/feedback-entrega) con unos ajustes, ya que los mismos tenían un leve error en los tamaños de los procesos ya que los últimos 2 debían pesar 128 bytes en lugar de 64 y ahora si tendría mas sentido la frase del enunciado de las pruebas.

Saludos.-
