### ISSUE TITLE
Duda con IO y CMN

### ISSUE THREAD

**Issue by milagrosvera** [sisoputnfrba/foro#4433]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas, como va?
Tenemos una duda cuando se pide una syscall de entrada salida
En el caso de planificar por Colas Multinivel que cada cola implementará un algoritmo Round Robin, se podría interrumpir el hilo mientras se está atendiendo esta syscall?
 Y si cuando ya cumplió el tiempo que iba a permanecer haciendo la operación de entrada/salida habría posibilidad de que pase a running si su Quantum no finalizó (nosotros creíamos que sí pero logs solo contempla el caso que pasa a Ready)?

### 📔 Citas del enunciado/videos

Para la implementación de este trabajo práctico, el módulo Kernel simulará la existencia de un único dispositivo de Entrada Salida, el cual atenderá las peticiones bajo el algoritmo FIFO. Para “utilizar” esta interfaz, se dispone de la syscall IO. Esta syscall recibe como parámetro la cantidad de milisegundos que el hilo va a permanecer haciendo la operación de entrada/salida.
((PID : TID )) Finalizó IO y pasa a READY

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by milagrosvera** [comment]
Holaa, okey gracias!
Solo para estar segura las syscalls que sacan al proceso de EXEC serían CANCEL, EXIT, JOIN e IO?

**Comment by iago64** [comment]
Buenas! Cómo va?

Las syscalls que sacan al proceso de EXEC, son todas aquellas que lo pueden mover a BLOCK o a EXIT, lo pueden ver en el enunciado en la parte del Kernel -> [Syscalls](https://docs.google.com/document/d/1KloOXfXQb_c1S3PKDEEywnArX9YB3aApqGVmpNgv9_Q/edit?tab=t.0#heading=h.o4dclr11f6x2)

Saludos.-

**Comment by milagrosvera** [comment]
Dale, muchas gracias!
Saludos
