### ISSUE TITLE
Duda Prueba Race Condition - Manejo de Mutex

### ISSUE THREAD

**Issue by Santimaffini** [sisoputnfrba/foro#4435]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

Hola buenas! Mi duda consiste en el avance del PC y el manejo de mutex:

Cuando un hilo(llamemoslo hilo A) pide MUTEX_LOCK cuando el mutex ya esta en eso, ese hilo se bloquea hasta que se haga un MUTEX_UNLOCK de ese mutex. Pero cuando el hilo A vuelve a ready despues de eso, y vuelve a ejecutar, como avanzo su PC no realiza el MUTEX_LOCK de nuevo, ya que el PC continuo como de costumbre. Y esto ocurre tambien si hay varios hilos bloqueados detras del mismo mutex.

Mi pregunta entonces es, esta esto bien? O debería cpu mantener el PC en esa instruccion (MUTEX_LOCK) hasta que sea no sea bloqueado por ella? Lo que me hace dudar de esto es porque no hay aclaracion de esto en la consigna hasta donde yo vi, y se me ocurrio recién al pensarlo comparandolo con el comportamiento de los mutexs reales.

Espero haber explicado bien, gracias y espero la respuesta!

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Creo que el problema que estas teniendo es un error de concepto, por lo tanto, vamos a salir del TP por 2 minutos y vamos a volver a la teoría.
Cuando un proceso hace un lock de un semáforo y se bloquea, este proceso queda a la espera de ese recurso. Despues de un tiempo, cuando el Sistema Operativo lo desbloquea, ese proceso no vuelve a ejecutar el lock, ya que el SO al momento de desbloquearlo le tiene que haber asignado esa instancia o ese semáforo por el cual se bloqueo.

Saludos.-

**Comment by Santimaffini** [comment]
Entiendo perfectamente, muchas gracias!
