### ISSUE TITLE
Sin memoria para crear un nuevo hilo

### ISSUE THREAD

**Issue by valendelrizzo** [sisoputnfrba/foro#4436]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Hola, tenemos una pequeña incognita que nos fue surgiendo con las pruebas. 
En el caso de que falle la creacion de nuevos procesos/hilos por falta de memoria, el proceso que mandó esta instrucción, debe seguir ejecutando o debe pasar a la cola de bloqueados? 
Entiendo que el proceso/hilo nuevo que no llego a crearse por falta de memoria pasa al estado de new y queda a la espera de liberacion de memoria cuando finaliza algun proceso/hilo. 
Cuando hay una creacion de procesos/hilos y hay memoria suficiente se da el ok a CPU y este continua con su ejecucion sin desalojar, pero en este caso queriamos confirmar esta situación que se nos da.
Gracias!

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

El proceso / hilo que ejecuto el PROCESS_CREATE sigue ejecutando como si nada hubiera pasado.

Saludos.-

**Comment by valendelrizzo** [comment]
Muchas gracias!
