### ISSUE TITLE
Prueba de Race condition

### ISSUE THREAD

**Issue by AGanem** [sisoputnfrba/foro#4437]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas! Cómo están? Ejecutando la prueba de race condition en el script RECURSOS_MUTEX_THREAD, nos encontramos con un issue que nos mantiene en un loop.  

### 📔 Citas del documento de pruebas

SET DX 0
SET AX 14
SET CX 10
SET BX 1
SUB CX BX
MUTEX_LOCK MUTEX
READ_MEM DX AX
SUM DX BX
WRITE_MEM AX DX
MUTEX_UNLOCK MUTEX
LOG DX
JNZ CX 4
THREAD_EXIT

### 👍 Comportamiento esperado

Entendemos que lo que hace la prueba en líneas generales: Es decrementar en uno, la variable CX, 10 veces. Esto debido a la instrucción JNZ CX 4 que luego de su ejecución e incremento de PC, nos da como resultado que la siguiente instrucción es SUB CX BX.

### 👎 Comportamiento obtenido

En vez de ser la siguiente instrucción la SUB CX BX, se ejecuta la instrucción(6) MUTEX_LOCK MUTEX, por lo que nunca decrementa la variable y entra en un loop. 
Creemos que tiene que ver con que nuestro PC, empieza en 0 y en la memoria se maneja con los mismos índices, por lo que al pedir la instrucción 5, corresponde a la 6 en memoria.  O luego de ejecutar JNZ, no debería hacer PC+1?

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Es tal cual decis en la última oración, despues del JNZ no tenes que hacer el PC + 1, ya que el valor de program counter se actualizó en el JNZ.

Saludos.-

**Comment by AGanem** [comment]
Genial, gracias!
