### ISSUE TITLE
Dudas sobre Prueba De Stress

### ISSUE THREAD

**Issue by regueiranehuen** [sisoputnfrba/foro#4439]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Hola buenas tardes. Tenemos varias dudas respecto a lo pedido en la prueba.
Respecto al pseudocódigo de The Emptiness Machine:

```
SET AX 10
SET BX 1
PROCESS_CREATE PLANI_PROC 16 0
PROCESS_CREATE RECURSOS_MUTEX_PROC 16 0
PROCESS_CREATE MEM_FIJA_BASE 12 0
PROCESS_CREATE MEM_DINAMICA_BASE 128 0
PROCESS_CREATE PRUEBA_FS 32 0
SUB AX BX
JNZ AX 2
PROCESS_EXIT
```

No entendemos cómo podríamos correr la prueba de memoria fija y la prueba de memoria dinámica concurrentemente, siendo que ambas pruebas requieren que la memoria esté estructurada de una forma distinta.

Luego, respecto al punto 2 de actividades. Citando al enunciado:

>  Verificar los recursos utilizados y matar los procesos cuando se validen.

A qué se refieren con matar los procesos cuando se validen? Nosotros tenemos estructurados los módulos de manera que cuando se termina toda la ejecución, cada módulo se cierra, libera la memoria de sus estructuras y cierra sus sockets. Lo que piden es hacer un CTRL + C cuando termine la prueba? Sería así en todas las pruebas?

Saludos

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! cómo va?

No nos interesan los resultados, simplemente aprovechamos los scripts que ya existían para generar mas carga en el sistema en general y ver si tienen esperas activas y/o Memory Leaks.

Saludos.-

**Comment by regueiranehuen** [comment]
> Buenas! cómo va?
> 
> No nos interesan los resultados, simplemente aprovechamos los scripts que ya existían para generar mas carga en el sistema en general y ver si tienen esperas activas y/o Memory Leaks.
> 
> Saludos.-

Ah perfecto, gracias!
