### ISSUE TITLE
Duda config memoria en pruebas Planificación y Race Condition

### ISSUE THREAD

**Issue by KirkSH** [sisoputnfrba/foro#4440]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Hola. En el documento de las pruebas, las de Planificación y Race Condition figuran con el Memoria.config indicando:

TAM_MEMORIA=1024
ESQUEMA=FIJAS
PARTICIONES=[32,32,32,32,32,32,32,32]

La suma de los tamaños de las particiones no coincide con el tamaño de la memoria.
Para correr las pruebas simplemente interpretamos que esto era un error del documento, y modificamos nuestro Memoria.config para que si coincida.
¿Estamos en lo correcto?
¿O tal vez memoria, cuando la especificación del tamaño de las particiones no alcanza el tamaño de la memoria, debe completar el faltante automáticamente con otra partición?

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

En las pruebas nos quedo mal pero honestamente pueden cambiarlo como gusten, ya sea cambiar los 32 por 128 o pueden poner DINAMICAS como esquema, en ambos casos las pruebas van a funcionar ya que estan enfocadas en temas de recursos y la memoria la usamos como excusa nomas.

Saludos.-

**Comment by KirkSH** [comment]
Oka. Gracias.
