### ISSUE TITLE
Valgrind - duda sobre still recheable

### ISSUE THREAD

**Issue by Facundo-Vattone** [sisoputnfrba/foro#4441]
### 🖋️ Descripción

Buenas! Estoy ejecutando valgrind y solo me saltan byte en still recheable.  Mi consulta es si tenemos que hacer énfasis en reducir esos bytes? o simplemente no nos preocupamos? 
Igualmente estuvimos tratando de disminuir el numero pero no encontramos la forma de hacerlo, si es así nos podrían orientar en esto. Saludos cordiales! 
![Captura](https://github.com/user-attachments/assets/5b7dbf82-3e6a-42da-bb20-ae645ccec0d4)

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

No, Still reachable significa que mataste el proceso y tenias referencias de memoria cargadas, no se tienen que preocupar por eso, los que si son un problema con los definitely lost y los indirectly lost porque son referencias de memoria perdidas que no pueden recuperar.

Saludos.-

**Comment by Facundo-Vattone** [comment]
muchas gracias gracias! 
cerrando issue...
