### ISSUE TITLE
Duda soble implementacion realizada

### ISSUE THREAD

**Issue by KirkSH** [sisoputnfrba/foro#4442]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Hola. Les cuento.
En nuestro tp, a la hora de que CPU recibe el PID y TID de Kernel, implementamos de que pida el Contexto de Ejecución a MEMORIA, solo si el PID y TID recibido no es el último ejecutado (se guarda un registro de ello), pues en ese caso CPU ya posee el Contexto de Ejecución en cuestión.
Es decir, solo se lo solicitamos a Memoria cuando es necesario obtenerlo, pues los registros actuales del CPU no son los del Hilo que se quiere correr.
Nuestra consulta es si esta implementación es válida, o si tenemos que cambiarla para que SIEMPRE solicite el Contexto de Ejecución, aún cuando "no haga falta".

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Deberían pedir siempre el contexto de ejecución cuando reciben un PID y un TID nuevos.

Saludos.-

**Comment by KirkSH** [comment]
Perdón. No logré entender.
Siempre que se reciben "nuevos" (osea, DIFERENTES al hilo que ejecutó
último)? O siempre que se reciben "cualquiera sean"?

**Comment by iago64** [comment]
Buenas! Cómo va?

Con nuevos quise decir que cualquiera sean, es decir, no controlan si son los que tuvieron antes.

Saludos.-

**Comment by KirkSH** [comment]
Oka. Muchas gracias.
