### ISSUE TITLE
Prueba Race Condition - Duda sobre Segmentation Fault

### ISSUE THREAD

**Issue by Facundo-Vattone** [sisoputnfrba/foro#4443]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas! Estuvimos probando la prueba recursos_mutex_proc y en el momento en el que ejecuta PROCESS_CREATE RECURSOS_RACE_PROC 16 4, en el momento que llega este proceso nuevo con 16 de tamaño, se le asigna una partición 32 y quiere hacer un write_men AX DX (con AX = 14 y DX = 0 ) esta bien que ocurra un segmentation_fault? o estamos implementando mal la instrucción write_men? por que entendemos que esta misma escribe a partir del primer parámetro 14, hasta 17.

### 📔 Citas del documento de pruebas

Cpu
![image](https://github.com/user-attachments/assets/e4d9e422-a255-40e1-8c21-923f8724c8f1)
Memoria
![image](https://github.com/user-attachments/assets/448d3240-e1c4-4a8e-b71c-a7fdedde8a73)

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Cito el enunciado:

> Se debe validar que las solicitudes se encuentren dentro de la partición asignada,  es decir que sea menor al límite de la partición.

Si en la partición te da el tamaño, no tendría que haber ningún problema.
Saludos.-

**Comment by Facundo-Vattone** [comment]
Buenas! si muchas gracias!
