### ISSUE TITLE
Duda log obligatorio

### ISSUE THREAD

**Issue by regueiranehuen** [sisoputnfrba/foro#4445]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Hola buenas noches. Tenemos la duda de si el enunciado plantea que loggeemos el tamaño del proceso, el tamaño de la partición o el tamaño del registro que se escribió/leyó. Citándolo:

> Escritura / lectura en espacio de usuario: “## <Escritura/Lectura> - (PID:TID) - (<PID>:<TID>) - Dir. Física: <DIRECCIÓN_FÍSICA> - Tamaño: <TAMAÑO>”

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! cómo va?

La posta posta es que ese log lo copiamos del cuatri pasado donde si había diferentes tamaños de lectura, aca va a ser siempre 4 ya que son los registros de la CPU, es decir lo que se lee.

Saludos.-
