### ISSUE TITLE
Duda prueba Partciones Dinamicas

### ISSUE THREAD

**Issue by juancruznaimo** [sisoputnfrba/foro#4448]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

Buenas! Estamos teniendo una duda acerca de los resultados esperados sobre la prueba. Cuando se crea el proceso MEM_DINAMICA_PROC, este al ejecutar la instrucción JNZ termina saltando a la instrucción 0 continuamente y queriamos saber si esto era parte del resultado esperado en la prueba.

### 📔 Citas del documento de pruebas

MEM_DINAMICA_PROC:
SET DX 0
SET AX 64
WRITE_MEM DX AX
READ_MEM BX DX
LOG BX
JNZ AX 0
PROCESS_EXIT

### 👍 Comportamiento esperado

Los procesos ingresan respetando la planificación de largo plazo y creando la partición correspondiente.

### 👎 Comportamiento obtenido

Se queda en un loop ejecutando las instrucciones del proceso

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by f-and** [comment]
Buenas noches Juan, si, es como decís, fijate que hay dos archivos de procesos que se crean, los que son MEM_DINAMICA_PROC_FIN, que finalizan, y los MEM_DINAMICA_PROC, que no lo hacen, por lo que van a haber procesos que terminen y procesos que se quedan en loop.

**Comment by juancruznaimo** [comment]
Perfecto, muchas gracias!
