### ISSUE TITLE
Problemas prueba de stress

### ISSUE THREAD

**Issue by AgustinaGuitman** [sisoputnfrba/foro#4449]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas, estamos corriendo la prueba de stress y no podemos entender porque rompe en esta prueba si todas las otras pruebas andan bien. Probamos correr todas las pruebas con el retardo de respuesta de memoria y el quantum que se usa en esta prueba y no rompe, también probamos modificar alternadamente la prueba para que no se use uno de los procesos de las pruebas anteriores y rompe igual. 
Nos damos cuenta que hay un desfasaje (el hilo que esta ejecutando en kernel es distinto al que ejecuta en cpu) pero no podemos encontrar la forma de arreglarlo. 
Les mando los logs a ver si nos pueden dar una mano, cualquier sugerencia es de inmesa ayuda.
Desde ya muchas gracias. Saludos

### 👎 Comportamiento obtenido

[cpu.logs.txt](https://github.com/user-attachments/files/18103715/cpu.logs.txt)
[kernel.logs[1].txt](https://github.com/user-attachments/files/18103716/kernel.logs.1.txt)
[mem.logs.txt](https://github.com/user-attachments/files/18103717/mem.logs.txt)

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Revisando los logs es dificil entender, igual cuando dicen que se rompe, que es lo que les pasa? tienen un segment fault? o que tipo de error tienen?

Capaz si es un segment fault nos pueda ayudar mas el output de Valgrind.

Saludos.-

**Comment by LeandroCarbajales** [comment]
Buenas!
Para agregar algo viendo los logs. A partir de 23:24:41:309 parece haber un priblema con el paquete recibido de CPU por fin de quantum. Ya que Kernel loguea "Codigo de Operacion de CPU incorrecto" y empieza a mandar hilos a EXEC como loco.

> [INFO] 23:24:41:309 KERNEL/(3573:3658):  ## (PID <2>:TID <0>) - Desalojado por fin de Quantum
Codigo de Operacion de CPU incorrecto

Como les dice Dami, correr Kernel y CPU con Valgrind les puede dar un indicio de si se están comiendo algo de memoria. Otra opción es correr Kernel y/o CPU en debug, poniendo un breakpoint a la hora de recibir y enviar Q para ver en ese momento en que rompe qué es lo que se está enviando y está llegando.

**Comment by AgustinaGuitman** [comment]
Buenas! Al final pudimos arreglarlo, el problema era que desde kernel esperabamos que nos manden un hilo con motivo segmentation fault de una forma distinta a la que nos la estaban mandando y eso hacía que rompa todo. ¡Muchísimas gracias a los dos!
Saludos!
