### ISSUE TITLE
Duda sobre Thread Cancel

### ISSUE THREAD

**Issue by juancruznaimo** [sisoputnfrba/foro#4450]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

Buenas! estamos teniendo una duda acerca de la syscall  THREAD_CANCEL, porque no se utiliza en ninguna de las pruebas y queríamos poder probarlo. Queria saber si esta prueba hecha por nosotros sirve para probar el funcionamiento. Muchas gracias

### 📔 Citas del documento de pruebas

SET DX 0              
SET AX 1              
THREAD_CREATE PLANI_THREAD 6 
SUM DX AX             
THREAD_CREATE PLANI_THREAD 5 
SUM DX AX             
THREAD_CREATE PLANI_THREAD 4 
SUM DX AX             
THREAD_CREATE PLANI_THREAD 3 
SUM DX AX             
THREAD_CANCEL 4      
THREAD_JOIN 2         
PROCESS_EXIT          

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Respecto a su prueba, esta bien, no se probó el THREAD_CANCEL por una cuestión de tiempos en las pruebas, pero esta bien que lo prueben ya que es posible que un ayudante ante alguna duda en los resultados pueda escribir una prueba en el momento y la utilice.

Saludos.-

**Comment by juancruznaimo** [comment]
Genial, muchas gracias!
