### ISSUE TITLE
Consulta sobre la prueba 6, la prueba de stress

### ISSUE THREAD

**Issue by ValenGriggio18** [sisoputnfrba/foro#4452]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

Cuando nosotros ejecutamos la prueba, creemos que nos da bien, pero quizás no estamos viendo los datos correctos. En el caso de los memory leaks, se supone que en Go tenemos garbage collector con lo cual no nos van a quedar memory leaks, pero para confirmarlo, cuando ejecutamos la prueba vamos a ver el estado del sistema y verificamos que el uso de la memoria esté siempre estable y que no se llene. Esto está bien? o es otro el dato que hay que mirar para confirmarlo.
Por otro lado, en el casos de las esperas activas, verificamos que el programa en ningun momento se quede bloqueado sin avanzar, y que todos los procesos se ejecuten secuencialmente.
Está bien nuestra forma de asegurarnos de que la prueba 6 se cumple? o tenemos que observar otras cosas para confirmar que no hayan memory leaks ni esperas activas? 
Desde ya muchas gracias!!!

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Respecto a los memory leaks, efectivamente, en Go tienen que controlar que la memoria no se les escape.
Un memory leak en C viene por el hecho de perder referencias, en otros lenguajes con garbage collector como Go, Java o C#, un memory leak viene por el lado de mantener referencias que no se usan mas.
Sobre las esperas activas, lo que tienen que revisar es que el consumo de CPU no se les dispare, es decir, que no esten con la CPU al 100% o cerca.

Saludos.-
