### ISSUE TITLE
Duda sobre configuración de memoria en pruebas

### ISSUE THREAD

**Issue by JeronimoAlo** [sisoputnfrba/foro#4453]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

Buenas!
Estamos repasando las pruebas de planificación y race condition, y vemos que en la configuración de la memoria el esquema de las particiones es DINAMICAS pero recordamos que antes era FIJAS (Además nos dan la lista con el tamaño de las particiones).

Puede ser que sea un error?
Muchas gracias!

### 📔 Citas del documento de pruebas

![Captura de pantalla 2024-12-14 140951](https://github.com/user-attachments/assets/e1cbdc5b-06d3-4ce9-a5e3-e380f065f865)
![Captura de pantalla 2024-12-14 140936](https://github.com/user-attachments/assets/006a8f89-a405-4ed9-9f24-bda82659dd5b)

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! cómo va?

En ninguno de las 2 pruebas deberían afectarles el tema de las particiones, con lo cual, pueden omitir la lista de particiones, ya que antes decía FIJAS y tambien estaban mal porque 32 * 8 es 256 y no 1024.

Saludos.-
