### ISSUE TITLE
Consulta READ_MEM / WRITE_MEM

### ISSUE THREAD

**Issue by IgnacioLapko** [sisoputnfrba/foro#4454]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

Buenas noches! Queriamos consultarles una duda que nos surgió al pasar las pruebas. Si quiero leer la posición X a partir de un READ_MEM sobre el array []Memoria (memoria de usuario) sin antes haber hecho un WRITE_MEM sobre dicha posicion de memoria X, ¿READ_MEM va a estar leyendo el valor 0?
¿O deberia estar actualizando dicha posicion X desde algun otro lado del sistema previo a ejecutar READ_MEM?

La consulta viene mas que nada al querer ejecutar las instrucciones de RECURSOS_RACE_THREAD, donde primero se hace un READ_MEM sobre una posicion que no se escribió en ese hilo.

Teníamos otra cosa para avisarles, habiamos consultado en el issue #4338 una duda y habian quedado en actualizar el enunciado, pero vemos que esto no fue asi. ¿Esta la posiblidad de que se pueda actualiar el enunciado? Mas que nada por si otro grupo tiene que consultarlo.

Desde ya muchas gracias!

Saludos,
Ignacio

### 📔 Citas del enunciado/videos

[RECURSOS_RACE_THREAD]:
SET DX 0
SET AX 14
SET CX 10
SET BX 1
SUB CX BX
MUTEX_LOCK MUTEX
READ_MEM DX AX
SUM DX BX
WRITE_MEM AX DX
MUTEX_UNLOCK MUTEX
LOG DX
JNZ CX 4
THREAD_EXIT

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by RaniAgus** [comment]
¡Buenas!

> Si quiero leer la posición X a partir de un READ_MEM sobre el array []Memoria (memoria de usuario) sin antes haber hecho un WRITE_MEM sobre dicha posicion de memoria X, ¿READ_MEM va a estar leyendo el valor 0?
¿O deberia estar actualizando dicha posicion X desde algun otro lado del sistema previo a ejecutar READ_MEM?

Al igual que ocurre en lenguajes de más bajo nivel como C, en realidad ustedes no deberían hacer nada: simplemente leen los bytes que se encuentren ahí. Si el registro no fue inicializado, tendrían bytes "basura".

> La consulta viene mas que nada al querer ejecutar las instrucciones de RECURSOS_RACE_THREAD, donde primero se hace un READ_MEM sobre una posicion que no se escribió en ese hilo.

Recuerden que el hilo RECURSOS_RACE_PROC es el que crea los RECURSOS_RACE_THREAD, y antes de ello hay una escritura en la misma dirección lógica:

https://github.com/sisoputnfrba/the-last-of-c-pruebas/blob/ba7f3649223e23800ecf854cd8139ea81c3dba2d/RECURSOS_RACE_PROC#L3

Saludos

**Comment by IgnacioLapko** [comment]
Buenos dias Agus! Clarisimo todo, muchas gracias! Teniamos otra consulta, ¿es correcto el orden en el que quedaron los registros que reciben READ_MEM (Registro Datos, Registro Dirección) y WRITE_MEM (Registro Dirección, Registro Datos)? Mas que nada porque estan invertidos, y nos generó duda. 

Muchas gracias nuevamente!

**Comment by iago64** [comment]
Buenas! Cómo va?

Si, los registros estan invertidos entre instrucciones porque buscan ser un análogo a `memcpy()` donde vos tenes como primer parametro el destino y como segundo parametro el origen, en READ_MEM, tu destino es el registro y tu origen es la memoria y en WRITE_MEM tu origen es el registro y tu destino es la memoria.

Saludos.-

**Comment by IgnacioLapko** [comment]
Perfecto, muchas gracias! Cierro Issue
