### ISSUE TITLE
Duda Valgrind en Prueba De Stress

### ISSUE THREAD

**Issue by Julian-Mosquera** [sisoputnfrba/foro#4455]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas tardes, al ejecutar la Prueba De Stress y finalizar la ejecución ,Valgrind reporta pérdidas de memoria de tipo possibly lost y still reachable por terminar la ejecucion abruptamente.  ¿Es necesario eliminar estos tipos de pérdidas en todos los casos, o se consideran memory leaks solamente los definetly e indirectly lost?

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by RaniAgus** [comment]
¡Buenas! En la guía de Valgrind tenemos una sección que habla específicamente sobre estos casos: https://docs.utnso.com.ar/guias/herramientas/valgrind#los-leaks-que-no-son

Saludos

**Comment by Julian-Mosquera** [comment]
Muchas gracas!
