### ISSUE TITLE
Duda Particiones Fijas Posible Espera Activa

### ISSUE THREAD

**Issue by IgnacioLapko** [sisoputnfrba/foro#4456]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

Buenas noches! Queríamos consultarles algo que vimos al ejecutar las pruebas de Particiones Fijas con Algoritmo de Ubicacion WORST FIT. En cierto momento, a uno de los procesos no se le puede asignar una particion ya que el mismo excede el tamaño de todas las particiones libres. Frente a este caso, ¿estaría bien que dicho proceso quede en espera activa aguardando que otro proceso finalice su ejecución para liberar la partición que tiene asignada y asi el proceso en espera activa pueda ingresar?, ¿o deberíamos desalojar dicho proceso sin particion, consultar los otros procesos que se fueron creando y estan en la cola NEW y chequear si se les puede asignar una partición? En caso de la segunda opcion, ¿hay alguna restricción con el manejo de dicho proceso a desalojar?

Desde ya muchas gracias!

Saludos,
Ignacio

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Esta bien que se quede esperando por no tener una partición en memoria donde entre, eso es justamente lo que esta definido en el planificador de Largo Plazo del Kernel.

Saludos.-

**Comment by IgnacioLapko** [comment]
Buenas tardes Iago,

Muchas gracias por la respuesta! Si, en realidad no esta en espera activa porque no esta ejecutando, cometi un error de concepto.

Cierro el issue.
