### ISSUE TITLE
Duda de comportamiento prueba Race Condition

### ISSUE THREAD

**Issue by gonramirez36** [sisoputnfrba/foro#4458]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

Hola, espero que estén bien. 

Tenemos una duda cuando se crea el proceso 2, donde la base es 32 y el limite es 47, cuando se realiza las instrucciones WRITE_MEM y READ_MEM la dirección física de la MMU es correcta porque el registro AX es 14, entonces quiere acceder a la posición Base (32) + Desplazamiento (14) = 46 , entonces en cualquiera de las dos instrucciones se pide leer/escribir los próximos 4 bytes que supera el Límite (47). 

No sabemos cómo manejar esta situación, si lanzar un segmentation fault y finalizar el proceso o no hacer nada y seguir la ejecución de instrucciones.

Si bien leímos el issue #4443 no nos queda claro por qué le asigna una partición de 32 si es de 16 el tamaño del proceso y por eso nos lleva a preguntar algo similar.

### READ MEM
_Se deberá devolver el valor correspondiente a los primeros 4 bytes a partir del byte enviado como dirección física dentro de la Memoria de Usuario._

### WRITE MEM
_Se escribirán los 4 bytes enviados a partir del byte enviado como dirección física dentro de la Memoria de Usuario y se responderá como OK._

En ninguno de los dos casos se especifica qué hay que hacer en el caso de que se pase

### 👎 Comportamiento obtenido

En el caso de que continuemos la ejecución sin hacer nada, el registro DX nos queda distinto para cada hilo de cada proceso, siendo 40 en el hilo 0 y 4 del proceso 1  (39, 38 y 37 en los otros hilos) y siendo 0 en el hilo 0 del proceso 2 (aunque los otros 3 hilos el DX nos queda en 10)

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by LeandroCarbajales** [comment]
Buenas!
Se asigna una partición de 32 bytes porque la configuración de la memoria en esa prueba es de particiones fijas y todas son de 32 bytes. A diferencia de particiones dinámicas, no se asigna una partición necesariamente del tamaño exacto del proceso, sino una igual o mayor entre las ya fijadas.

Te aclara la duda?
Saludos!
      Lean

**Comment by gonramirez36** [comment]
Hola Lean! La prueba de Race Condition es con Dinámicas y bajo el algoritmo de búsqueda FIRST por eso nos llamaba la atención ese issue, no se si en algún momento hubo algún cambio o quizá alguien lo cambió sin querer. 

<img width="347" alt="image" src="https://github.com/user-attachments/assets/99aafb64-fc58-4e47-891d-e7862b911ff2" />

**Comment by LeandroCarbajales** [comment]
Buenas!
Efectivamente debe haberse tratado de un cambio por equivocación. Ahí lo volvimos a poner como estaba.

**Comment by gonramirez36** [comment]
Buenas! Genial, nos parecía que la primera vez que la hicimos era fijas. Gracias Lean!
