### ISSUE TITLE
Consulta sobre resultados race condition

### ISSUE THREAD

**Issue by JeronimoAlo** [sisoputnfrba/foro#4459]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

Buenas! Cómo andan? Les hago una consulta.
Esta bien que en la prueba de race condition el valor de DX para el proceso con mutex sea de 40 al finalizar pero el del proceso sin mutex sea 10? les consulto esto ya que sin mutex lo corrimos varias veces y parece que siempre nos da 10 (El resultado no es el esperado pero es deterministico por lo que entendemos).

Muchas gracias!

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by LeandroCarbajales** [comment]
Buenas!
Prueben corriendo con un quantum mucho más alto, por ejemplo 5000 y verán que da un valor más alto (incluso quizás dé 40)

**Comment by JeronimoAlo** [comment]
Joya ahi nos dio bien gracias!
