### ISSUE TITLE
Consulta prueba race condition

### ISSUE THREAD

**Issue by AlexiaDz** [sisoputnfrba/foro#4460]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas, tenemos una consulta sobre la prueba de race condition, cuando dice que pongamos el quantum en 150 ese tiempo es menor al del retardo de respuesta de memoria, que es 200. Nosotros estábamos empezando a contar el quantum antes de pedirle el contexto de ejecución a memoria, es decir, cuando se envía el tid y pid a cpu pero nos dimos cuenta que por lo mencionado anteriormente no se ejecuta ninguna instrucción. Tendríamos que esperar a que memoria envie el contexto de ejecución, que cpu le notifique a kernel y recién ahí empezar con el quantum?

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by RaniAgus** [comment]
¡Buenas! En CPU, deberían chequear si hubo interrupciones recién en la etapa de **check interrupt**, no antes. Por lo tanto, se debería poder completar la etapa de _fetch_, _decode_ y _execute_ de una instrucción antes de desalojar por fin de quantum.

Saludos

**Comment by AlexiaDz** [comment]
Hola, gracias por responder. La pregunta iba por otro lado.

La duda que estamos teniendo es cuándo arrancar a contar el quantum (ejecutar el usleep) porque lo estábamos empezando a contar antes de pedirle el contexto de ejecución a memoria, es decir, cuando se envía el tid y pid a cpu. Entonces, el quantum no nos alcanzaba para esperar el retardo de la memoria. Ahora lo cambiamos y enviamos una confirmación a kernel, desde cpu, de que recibimos el contexto antes de empezar a contar el quantum. Estaría bien así?

**Comment by RaniAgus** [comment]
Nono, deberían empezar a contar el quantum en el momento en el que se envía el TID y PID a CPU, como lo tenían antes.

Por eso justamente mencionaba las etapas del ciclo de CPU: fetch (pedir la instrucción a memoria), decode (interpretar la próxima instrucción), execute (ejecutar la instrucción) y check interrupt (corroborar si llegó una interrupción).

Si bien puede llegar la interrupción en la etapa de fetch, no se debe chequear hasta la etapa de check interrupt.

Saludos

**Comment by AlexiaDz** [comment]
ah okey, entonces contamos el tiempo que tarda memoria dentro del quantum pero seria parte del fetch, muchas gracias!

Saludos.

**Comment by RaniAgus** [comment]
¡No hay de qué! Recuerden que si la duda ya fue resuelta pueden cerrar el issue 👮🏻‍♂️
