### ISSUE TITLE
Duda sobre prueba Particiones Dinámicas

### ISSUE THREAD

**Issue by JeronimoAlo** [sisoputnfrba/foro#4461]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

Buenas noches! Les hago una consulta. 
Los hilos que ejecutan las instrucciones MEM_DINAMICA_PROC puede ser que entren en un loop por la instruccion JNZ AX 0?

Entendemos que la idea de la prueba es que estos hilos no finalicen pero los que ejecutan el archivo MEM_DINAMICA_PROC_FIN si finalicen.

Muchas gracias!

### 📔 Citas del documento de pruebas

Archivos de MEM_DINAMICA_PROC:

SET DX 0
SET AX 64
WRITE_MEM DX AX
READ_MEM BX DX
LOG BX
JNZ AX 0
PROCESS_EXIT

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Efectivamente, los hilos quedan en un loop infinito asi no liberan la memoria y en el caso de Go podemos ver despues como manejan la compactación.

Saludos.-
