### ISSUE TITLE
Prueba Race Condition - Duda sobre Segmentation Fault 

### ISSUE THREAD

**Issue by Facundo-Vattone** [sisoputnfrba/foro#4462]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas! Estuvimos probando la prueba recursos_mutex_proc y en el momento en el que ejecuta PROCESS_CREATE RECURSOS_RACE_PROC 16 4, en el momento que llega este proceso nuevo con 16 de tamaño, se le asigna una partición acorde a su tamaño(particiones dinámicas) y quiere hacer un write_men AX DX (con AX = 14 y DX = 0 ) esta bien que ocurra un segmentation_fault? o estamos implementando mal la instrucción write_men? por que entendemos que esta misma escribe a partir del primer parámetro 14, hasta 17.
Notamos que antes en la prueba se usaban particiones fijas (En este caso no pasaba el segmentation ya que la fragmentación interna evitaba pisar a otro proceso), pero ahora se cambio en el doc por dinamicas.

### 📔 Citas del documento de pruebas

CPU 
![image](https://github.com/user-attachments/assets/f564bd96-b4bf-4b79-be56-233f6ae405ad)
MEMORIA 
![image](https://github.com/user-attachments/assets/47f67464-37c8-4959-9e41-274eea991787)

DOC pruebas
![image](https://github.com/user-attachments/assets/46b8ceef-b681-4c95-a5ff-6d07949d8a6c)

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by LeandroCarbajales** [comment]
Buenas!
Respondido en #4458 . Debe haberse tratado de un cambio por equivocación. Ya está en fijas nuevamente.

Saludos!
    Lean

**Comment by Facundo-Vattone** [comment]
gracias! cierro el issue!
