### ISSUE TITLE
Duda Prueba-FS

### ISSUE THREAD

**Issue by ManuCabanas** [sisoputnfrba/foro#4463]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas tardes, tengo una duda sobre como es el comportamiento esperado acerca de la escritura en el archivo de bloques.dat en el test de Fibonacci. 

### 📔 Citas del documento de pruebas

Prueba FS - Fibonacci Sequence
Actividades
Iniciar los módulos.
Parámetros del Kernel
archivo_pseudocodigo: PRUEBA_FS
tamanio_proceso: 8
Esperar a que todos los procesos finalicen.
Volver a iniciar la prueba.

Resultados Esperados
Llega un momento en el cual no se pueden hacer mas DUMP porque se llena el FS.

### 👍 Comportamiento esperado

Tengo entendido que cuando se ejecuta por primera vez el test, se llena casi por completo el FS, quedando 21 bloques libres. Luego al ejecutar otra vez, se llega a llenar por completo FS y se deberia de ver escrito en el bloques.dat "HEAVY IS THE CROWN!"

### 👎 Comportamiento obtenido

Nosotros al ejecutar por separado el script de FIBO_CROWN, obtenemos el resultado esperado del bloques.dat, con el texto perfectamente escrito. A la hora de ejecutar el test gral, en la primera iteracion se nos llena casi por completo el FS, quedando 21 bloques libres. Cuando ejecutamos por segunda vez el script, se llena por completo el FS, haciendo un exit de los procesos que no pueden hacer el DUMP, pero al contrario de lo esperado en el bloques.dat, no esta escrito el mensaje de Heavy is The Crown. 

Es imprescindible que este escrito o solamente debemos tomar como resultado esperado de la prueba el llenado del FS? 

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Si con FIBO_CROWN, pueden ver la frase HEAVY IS THE CROWN en el archivo estan por el buen camino.
Despues tienen que revisar un poco mas a detalle los valores en hexa ya que los demas spcrits lo que hacen es imprimir la sucesión de fibonacci, con lo cual ahi pueden al menos ver los primeros valores 0, 1, 1, 2, 3, 5, 8, 13 sin mayores inconvenientes, despues cuando pasan de esos valores si se les va a complicar porque empiezan a jugarle en contra la representación de los [números en memoria](https://es.wikipedia.org/wiki/Endianness).

Saludos.-

**Comment by ManuCabanas** [comment]
Entonces para quedarme tranquilo. Ejecutamos cada prueba por separado y si vemos que se escribe bien los archivos en cada caso, sumado a que en la prueba gral el llenado se hace bien, tomamos que vamos en buen camino?

**Comment by iago64** [comment]
Buenas!

Y si corres la prueba completa y pasas el output del `hexdump -C` del archivo y vemos los resultados no te va a dejar mas tranquilo?

Saludos.-

**Comment by ManuCabanas** [comment]
Dale buenisimo! Te mando el output que tenemos ahora. Por lo que vimos cambiaron el tiempo que esta en IO, queria consultarte sobre eso. Antes cuando ejecutabamos con el IO viejo, nos quedaban 21 bloques libres en la primera ejecucion. Con el nuevo IO mas corto, la primera ejecucion nos queda en 123 ya que no se al hacer los process_create habiendo procesos todavia sin finalizar, memoria no tiene espacio para crearlos. Es la idea o debemos solucionar algo? 

[message (1).txt](https://github.com/user-attachments/files/18170287/message.1.txt)

**Comment by ManuCabanas** [comment]
Buenas!

Pudimos solucionar la escritura con respecto al caso de nuestro issue original, con el IO en 100000 (el viejo), ahora nos escribe bien el heavy crown y luego basura. Eso quedaria saldado, ahora mi consulta va sobre si esta bien que, con el IO nuevo, en nuestra primera iteracion se llena hasta el bloque 123, luego hacen falta 2 iteraciones mas para completar el FS. Entendemos que es por el cambio del IO, ya que con el valor mas alto, se nos llena en dos ejecuciones. Esta bien? 

Te adjunto como nos quedo el bloques.dat, al ejecutar dos veces con el nuevo IO. 
[ejecucion_nuevo_io_2_veces.txt](https://github.com/user-attachments/files/18170928/ejecucion_nuevo_io_2_veces.txt)

**Comment by iago64** [comment]
Bueno... vamos por partes, no se que tan bien va a salir esto porque en muchísimo mas facil en persona pero espero que se entienda:

Primera parte FIBO_CROWN
```
00000000  01 00 00 00 02 00 00 00  03 00 00 00 00 00 00 00  |................|
00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000020  48 00 00 00 45 00 00 00  41 00 00 00 56 00 00 00  |H...E...A...V...|
00000030  59 00 00 00 20 00 00 00  49 00 00 00 53 00 00 00  |Y... ...I...S...|
00000040  20 00 00 00 54 00 00 00  48 00 00 00 45 00 00 00  | ...T...H...E...|
00000050  20 00 00 00 43 00 00 00  52 00 00 00 4f 00 00 00  | ...C...R...O...|
00000060  57 00 00 00 4e 00 00 00  21 00 00 00 00 00 00 00  |W...N...!.......|
00000070  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
```
Aca efectivamente vemos la frase de Heavy is the Crown con algunos espacios porque estamos usando una variable de 4 bytes para escribir 1, hay un easter egg con el script de FIBO_SHOVEL que imprime una frase parecida por si lo quieren cambiar y correr.

Segunda parte FIBO_10
```
00000080  05 00 00 00 06 00 00 00  00 00 00 00 00 00 00 00  |................|
00000090  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000a0  00 00 00 00 01 00 00 00  01 00 00 00 02 00 00 00  |................|
000000b0  03 00 00 00 05 00 00 00  08 00 00 00 0d 00 00 00  |................|
000000c0  15 00 00 00 22 00 00 00  00 00 00 00 00 00 00 00  |...."...........|
000000d0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
```

Aca es donde se pone fulero, porque tenemos que analizar los octetos (o pares de numeritos en hexa)
en los 2 primeros vemos que hay un 05 y 06, esos son los números de bloque que estan usando en el FS
Despues vemos que tenemos a partir de la línea 000000a0 los siguientes números donde cada grupo de 4 bytes tiene su representación en decimal al lado:
```
00 00 00 00 --> 0
01 00 00 00 --> 1
01 00 00 00 --> 1
02 00 00 00 --> 2
03 00 00 00 --> 3
05 00 00 00 --> 5
08 00 00 00 --> 8
0d 00 00 00 --> 13
15 00 00 00 --> 21
22 00 00 00 --> 34
```

Al terminar vemos que tenemos los primeros 10 números de la sucesión de fibonacci.

En los demas scripts la cosa se pone mas peluda porque ya como te comente antes la representación de los [números en memoria](https://es.wikipedia.org/wiki/Endianness) se pone medio jodida y no es taaan facil de seguirla, pero ya con eso tienen una muestra de que la memoria la escriben bien y pasan bien el contenido a los bloques del FS.

Saludos.-

**Comment by ManuCabanas** [comment]
Muchas gracias por todo! Disculpe las molestias. Cierro issue!!

**Comment by ManuCabanas** [comment]
Buenisimo muchas gracias! y perdon por las molestias. Cierro issue.
