### ISSUE TITLE
Duda sobre liberacion de memoria ante PROCESS y THREAD EXIT

### ISSUE THREAD

**Issue by ManuCabanas** [sisoputnfrba/foro#4464]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas noches, como andan? Tengo la siguiente duda: 

A la hora de hacer un thread y process exit, la idea es que la información del hilo/proceso quede en memoria para garantizar la estadísticas en caso de necesitarlas, entendemos que así es en la teoría y queremos considerarlo para el tp. En nuestro caso al hacer un process y thread exit, cambia una variable de estado del struct pcb y tcb correspondiente, y se lo agrega a una lista_EXIT. En ambos caso se hace un malloc en el momento de crear los hilos/procesos, por lo que en algún momento debemos de liberar la memoria alocada. 

Esta bien que consideremos tan literal la teoría, o debemos de liberar la memoria cuando se hace un thread/process exit, sin considerar el hecho de dejar la info para las estadísticas? 

Muchas gracias, saludos!

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by f-and** [comment]
Buenas Manuel, preferiríamos que se atengan al scope del TP, estas estadísticas que ven en la teoría solo se aplicarían en un SO que va metódicamente evaluando el estado de sus procesos para modificar sus planificadores acordemente, como esto no se realiza en el trabajo práctico, es innecesario para lo que compete al mismo mantener los procesos en Memoria.
Espero que te haya servido la respuesta.
Saludos.-
