### ISSUE TITLE
CONSULTA SOBRE LOGS OBLIGATORIOS EN ARCHIVOS - MODULO FILESYSTEM

### ISSUE THREAD

**Issue by AgustinTejera** [sisoputnfrba/foro#4465]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Tengo la siguiente duda sobre el enunciado cuando menciona los logs:

En relacion a la creacion del archivo, queria saber si cuando inicializo el filesystem y creo el archivo bitmap.dat, bloques.dat y el archivo de metadata también se debe generar el log de la creacion del archivo. O este unicamente corresponde cuando se crean los archivos DUMP??

Ademas, queria saber si pueden estar visibles los log_debug para que nos sirvan de guia a la hora de ejecutar las distintas funcionalidades del modulo. Por ejemplo cuando levanto los valores de la config o inicializo el logger, etc.

### 📔 Citas del enunciado/videos

Logs mínimos y obligatorios
Creación Archivo: “## Archivo Creado: <NOMBRE_ARCHIVO> - Tamaño: <TAMAÑO_ARCHIVO>”
Asignación de bloque: “## Bloque asignado: <NUMERO_BLOQUE> - Archivo: <NOMBRE_ARCHIVO> - Bloques Libres: <CANTIDAD_BLOQUES_LIBRES>”
Acceso a Bloque: “## Acceso Bloque - Archivo: <NOMBRE_ARCHIVO> - Tipo Bloque: <DATOS / ÍNDICE> - Bloque File System <NUMERO_BLOQUE_FS>”
Fin Petición: “## Fin de solicitud - Archivo: <NOMBRE_ARCHIVO>”

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by AgustinTejera** [comment]
Entonces solamente muestro los logs para la creacion de los archivo DUMP?

**Comment by f-and** [comment]
Claro, para el File System solo deberían saltar los Logs obligatorios cuando se crean los archivos DUMP.

**Comment by AgustinTejera** [comment]
Perfecto, quedo claro muchas gracias!
