### ISSUE TITLE
problemas con el despliegue 

### ISSUE THREAD

**Issue by luchito12** [sisoputnfrba/foro#4466]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

hola buenas tardes, paso a comentar mi problema:
hoy fuimos al labo a realizar el despliegue, los pasos que hicimos fueron los siguientes 
conectamos una maquina virtual sin interfaz gráfica al putty  
luego conectamos otras 3 maquinas virtuales abiertas en 3 computadoras distintas (una por cada maquina) a ip la principal (la primera que creamos)
luego ejecutamos los siguientes comandos en el putty
1.git clone https://github.com/sisoputnfrba/so-deploy.git
2.cd so-deploy
3. ./deploy.sh -l=sisoputnfrba/so-commons-library -p=cpu -p=memoria -p=filesystem -p=kernel -c=IP_KERNEL= -c=IP_CPU= -c=IP_MEMORIA=  -c=IP_FILESYSTEM= -c=LOG_LEVEL=INFO tp-2024-2c-EstoyEntrenando

y acá viene el problema, cuando completamos los campos de las ips para que sean remplazados en todas las configuraciones 
al querer runrunear el programa  con el comando  ./bin/filesystem cfg/filesystem1-2-3.config (cfg es una carpeta que contiene las configuraciones) el programa no runnea y se queda tildado el putty, ahora si no configuramos ninguna ip en el codigo -c=IP_KERNEL= etc, el programa runnea normalmente y se conecta con el puerto, aclaro que el problema no es por la ip que usamos ya que siempre y cuando no se modifique con el comando -c el valor de ip que tenga asociado lo va a leer y va runnear sin problemas  

adjunto imagenes 
![image](https://github.com/user-attachments/assets/58c8cfb3-528e-4f1b-a730-239448228217)
![image](https://github.com/user-attachments/assets/67bca1ab-c114-4c90-9685-82c19b80d21a)
![image](https://github.com/user-attachments/assets/dde48b35-3325-4150-96f8-7b5476b92735)

como se puede ver a continuacion se cambian correctamente las ip
![image](https://github.com/user-attachments/assets/ef3ce5b4-bec1-4afa-8eac-5e8b2db4b9a4)

ahora si lo runneo  con ./bin/filesystem cfg/filesystem1-2-3.config
![image](https://github.com/user-attachments/assets/0f22aa4d-23ee-43ff-bec5-e0435e9b8740)
ahi se queda y no hace mas nada 

por ultimo si no cambio las ip pasa esto 
![image](https://github.com/user-attachments/assets/47c74a43-c6fb-44d5-8538-a0f5394cfc66)
y si runneo 
![image](https://github.com/user-attachments/assets/a623f2e8-4602-4b41-a232-7907b20a9545)

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by RaniAgus** [comment]
¡Buenas! En el caso del comando con las IPs configuradas, también están configurando los logs en nivel INFO, por lo que todos los logs que les aparecerían en nivel "trace" y "debug" van a permanecer ocultos.

Saludos

**Comment by luchito12** [comment]
buenas muchas gracias por responder y marcarnos esas cosas, pero creo que no se entendió la duda, lo que nos esta pasando es que nosotros no sabemos las ip hasta que vamos al laboratorio y comenzamos con el despliegue, entonces si nosotros usamos el comando para configurar las ip el programa después no nos runnea como se puede ver en las imágenes adjuntas, ahora si no las configuramos con el comando si runnea , la pregunta era saber como poder solucionar este problema

**Comment by RaniAgus** [comment]
¡Buenas! Entiendo, mi respuesta iba en base a la misma duda.

Lo único que veo en las capturas es que el programa no está imprimiendo nada por pantalla, pero esto no significa que el programa no ejecute. Entonces, lo que estoy sugiriendo que el programa probablemente **sí ejecute**, solo que no se ven los logs ya que están configurados en nivel INFO en lugar de TRACE.

Les recomiendo probar setear el nivel de log de vuelta a TRACE para corroborarlo. Pueden usar el editor `nano` para ello, [acá hay una guía sobre cómo usarlo](https://docs.utnso.com.ar/guias/consola/bash#nano) :)

Saludos

**Comment by luchito12** [comment]
muchas gracias por ayudarnos era lo de los logs, saludos
