### ISSUE TITLE
Duda sobre cantidad de instrucciones en un Quantum

### ISSUE THREAD

**Issue by JulianTettamanti** [sisoputnfrba/foro#4469]
### 🖋️ Descripción

Ejecutando la prueba de memorias fijas con WORST nos sucede que los procesos se van creandose correctamente y muriendo pero al momento de que el PID 4 y el 5 hagan su instrucción anterior a IO el 5 realiza 2 instrucciones. Entiendo que con la configuración de esta prueba cada instrucción debería hacer solo una instrucción por Q, puede suceder que se ejecute mas de una instrucción por algún motivo?

### 💻 Logs

INFO] 16:41:49:201 [CPU - Log obligatorio]/(5814:5820): ## TID: <0> - ## PID <4> - - Actualizo Contexto Ejecución
[INFO] 16:41:49:201 [CPU - Log obligatorio]/(5814:5956): TID: <0> - FETCH - Program Counter: <4>
[INFO] 16:41:49:343 [CPU - Log obligatorio]/(5814:5819): ## Llega interrupción al puerto Interrupt
[INFO] 16:41:49:343 [CPU - Log obligatorio]/(5814:5819): INTERRUPCION RECIBIDA: <PID:4> <TID:0> [T:DESALOJO_RR]
[INFO] 16:41:49:402 [CPU - Log obligatorio]/(5814:5956): TID: <0> - Ejecutando: <LOG> - <BX>
[INFO] 16:41:49:402 [CPU - Log obligatorio]/(5814:5956): Valor del registro <BX> es: 64
[INFO] 16:41:49:410 [CPU - Log obligatorio]/(5814:5958): ## TID: <0> - ## PID <2> - Solicito Contexto Ejecución
[INFO] 16:41:49:807 [CPU - Log obligatorio]/(5814:5820): ## TID: <0> - ## PID <2> - - Actualizo Contexto Ejecución
[INFO] 16:41:49:807 [CPU - Log obligatorio]/(5814:5958): TID: <0> - FETCH - Program Counter: <6>
[INFO] 16:41:49:910 [CPU - Log obligatorio]/(5814:5819): ## Llega interrupción al puerto Interrupt
[INFO] 16:41:49:910 [CPU - Log obligatorio]/(5814:5819): INTERRUPCION RECIBIDA: <PID:2> <TID:0> [T:DESALOJO_RR]
[INFO] 16:41:50:008 [CPU - Log obligatorio]/(5814:5958): TID: <0> - Ejecutando: <PROCESS_EXIT>
[INFO] 16:41:50:620 [CPU - Log obligatorio]/(5814:5963): ## TID: <0> - ## PID <5> - Solicito Contexto Ejecución
[INFO] 16:41:50:820 [CPU - Log obligatorio]/(5814:5820): ## TID: <0> - ## PID <5> - - Actualizo Contexto Ejecución
[INFO] 16:41:50:820 [CPU - Log obligatorio]/(5814:5963): TID: <0> - FETCH - Program Counter: <4>
[INFO] 16:41:51:021 [CPU - Log obligatorio]/(5814:5963): TID: <0> - Ejecutando: <LOG> - <BX>
[INFO] 16:41:51:021 [CPU - Log obligatorio]/(5814:5963): Valor del registro <BX> es: 64
[INFO] 16:41:51:022 [CPU - Log obligatorio]/(5814:5963): TID: <0> - FETCH - Program Counter: <5>
[INFO] 16:41:51:120 [CPU - Log obligatorio]/(5814:5819): ## Llega interrupción al puerto Interrupt
[INFO] 16:41:51:120 [CPU - Log obligatorio]/(5814:5819): INTERRUPCION RECIBIDA: <PID:5> <TID:0> [T:DESALOJO_RR]
[INFO] 16:41:51:222 [CPU - Log obligatorio]/(5814:5963): TID: <0> - Ejecutando: <IO> - <12000>

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

En la prueba de Memoria lo que nos importa es cuando se van creando los procesos, asi que la cantidad de instrucciones medio que nos da lo mismo.

Otra cosa importante aca es que las IO se tienen que encolar cosa de que tarden mucho en entrar los últimos procesos.

Saludos.-

**Comment by JulianTettamanti** [comment]
Muchas gracias por la respuesta!

**Comment by JulianTettamanti** [comment]
Gracias!!
