### ISSUE TITLE
Duda sobre las prioridades entre segmentation fault, syscall e interrupción

### ISSUE THREAD

**Issue by LaureanoIbarra** [sisoputnfrba/foro#4470]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas, tenía una duda sobre cuál es el orden de prioridades para estos tres casos: segmentation fault, syscall e interrupción. Estos tres casos implican un fin al ciclo de instrucción de ese momento y todo lo que conlleva eso, pero si llega una interrupción y a la vez se está ejecutando una syscall. ¿Cuál es la que tiene más prioridad? Entiendo que la syscall, pero me generaba duda esto. Desde ya muchas gracias y disculpen por las molestias. 

### 💭 Soluciones posibles

Este fue mi razonamiento, no sé si es el correcto para el tp o en la teoría. Está ordenado de prioridad más alta a más baja
1) segmentation fault, porque es en el decode, si esto pasa se tiene que actualizar el contexto, avisar a kernel y no se sigue con el ciclo actual
2) syscall, esto es porque sucede durante la ejecución de la instrucción, se actualiza el contexto, se tiene que avisar a kernel para que se encargue, termina ese ciclo y dependiendo de la syscall se replanifica o no.
3) la interrupción, porque esto sucede al finalizar el ciclo de instrucción (o en la instancia final con el check interrupt) y significaría que no llegaron ninguna de las anteriores antes.

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by tralph3** [comment]
En nuestro caso lo que hicimos fue atender la syscall y a la vez interrumpir el proceso, es decir, desalojarlo. Si la syscall en cuestión bloquea al proceso o lo cancela, no hacemos nada, pero si lo deja ejecutando, lo movemos a ready por la interrupción y le damos lugar a otro proceso.

Desconozco si es lo que se debería hacer, pero es la opción que tomamos nosotros.

**Comment by iago64** [comment]
Buenas! Cómo va?

Es muy dificil que se les den todas las condiciones al mismo tiempo... de hecho diria que es practicamente imposible ya que las VMs en el labo corren con 1 solo core, por lo tanto los procesos posta posta ejecutan de a 1.

De todas formas, como dice @tralph3 una opción es como lo hicieron ellos, otra es mandar en la interucción por quantum el PID y TID y ver con eso en la CPU cuando reciban el contexto de nuevo post syscall si lo tienen que interrumpir o no.

El caso de segfault es mas simple, porque ahi lo tienen que matar y no hay muchas alternativas, el fin de quantum es al final del ciclo de instrucción y aca lo estan matando en el decode / execute.

Saludos.-

**Comment by LaureanoIbarra** [comment]
Okaa, muchas gracias a los dos! Cierro el issue.

**Comment by LaureanoIbarra** [comment]
Okaa, muchas gracias a los dos! Cierro el issue.
