### ISSUE TITLE
Duda sobre resultado FileSystem

### ISSUE THREAD

**Issue by Martlar1502** [sisoputnfrba/foro#4471]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

Buenas tardes,

Les quería consultar sobre el resultado de la prueba de fibbonacci. 
Corrimos el archivo FIBO_CROWN y nos da el siguiente resultado en el bloque de datos:
![image](https://github.com/user-attachments/assets/c3d610fd-93dd-43a4-9f77-928b13d1dc40)

La consulta es si deberíamos guardar el bloque de indices del archivo en conjunto con el resto de los bloques de datos.

En la imagen, la parte del bloque de indices es la del codigo hexa: 0B7F020102FF80000106000007FF800003010203 que se encuentra en las primeras dos lineas del print.

Desde ya muchas gracias,
Saludos

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! cómo va?

Si, deberían guardar el bloque indices como un bloque mas dentro del FS.
Respecto al dump, revisen las respuestas del issue #4463 donde se habló exactamente de los resultados y como validarlos.

Saludos.-
