### ISSUE TITLE
Verificacion de funcionamiento correcto de las pruebas

### ISSUE THREAD

**Issue by arolla03** [sisoputnfrba/foro#4473]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Tengo una duda, en el test de Race Conditions los resultados esperados son en base al resultado del calculo de los hilos. Pero donde se guarda ese resultado si no hay un MEMORY_DUMP?

### 📔 Citas del documento de pruebas

# Prueba Race Condition

## Resultados Esperados

El valor final generado por los hilos sin mutex no es determinístico y puede no ser el esperado.
El valor final generado por los hilos con mutex es correcto y determinístico.

Pagina 6

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Para eso tienen la instrucción del LOG DX, para ir viendo el valor a lo largo de la ejecución.

Saludos.-

**Comment by arolla03** [comment]
Ah bueno gracias, cierro issue.
