### ISSUE TITLE
Logs en pantalla

### ISSUE THREAD

**Issue by Cpallmieri** [sisoputnfrba/foro#4474]
### 🛠️ Lenguaje

C

### 🖋️ Descripción

Buenas! Una consulta, con el tema Logs en pantalla, no puede estar presente ninguno o pueden estar los obligatorios impresos en pantalla?

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by RaniAgus** [comment]
¡Buenas! Respondo tu duda citando la página 8 del enunciado:
![image](https://github.com/user-attachments/assets/7090bb9b-f55d-4b9f-9923-ebb9372e5d1a)

Saludos
