### ISSUE TITLE
Desalojo de hilos según prioridad

### ISSUE THREAD

**Issue by RamiroAlonso2003** [sisoputnfrba/foro#4475]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

El proceso inicial asociado al archivo de instrucciones del proceso arranca con su tid prioridad 0 según el enunciado. Al crear nuevos hilos, siempre va a seguir ejecutando el 0 a menos que haya un threadExit ya que tiene la prioridad máxima. Mi duda es que algunos archivos de pseudocódigo al finalizar tiene el processExit. haciendo que nunca se ejecuten los demás hilos creados debido a que el máxima prioridad cerro el proceso. Por ejemplo el codigo de PLANI_PROC

### 📔 Citas del enunciado/videos

SET DX 0
SET AX 1
THREAD_CREATE PLANI_THREAD 6
SUM DX AX
THREAD_CREATE PLANI_THREAD 5
SUM DX AX
THREAD_CREATE PLANI_THREAD 5
SUM DX AX
THREAD_CREATE PLANI_THREAD 6
SUM DX AX
THREAD_JOIN 4
PROCESS_EXIT

### 💭 Soluciones posibles

La situación es coherente con lo que plantea el enunciado pero nos parece raro. Puede ser que antes de cerrar el proceso espere a los demás hilos que terminen sus tareas

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by LeandroCarbajales** [comment]
Buenas!
Es justamente esto que notás: "Puede ser que antes de cerrar el proceso espere a los demás hilos que terminen sus tareas".
Que es lo que debería ocurrir al ejecutar `THREAD_JOIN 4`. Ese hilo con prioridad 0 se debería bloquear hasta que finalice el hilo 4 de ese proceso.

Te aclara la duda?
Saludos!
     Lean
