### ISSUE TITLE
Los logs a veces crashean el programa

### ISSUE THREAD

**Issue by tralph3** [sisoputnfrba/foro#4476]
### 🖋️ Descripción

Hola, las funciones de logs de las commons a veces me crashean el programa. Es muy inconsistente, puede funcionar perfectamente por varios minutos y luego crashear de repente.

La forma en la que manejamos el logger es con estado global. Es decir, hay un logger por módulo, y todos los logs se hacen con ese mismo.

Lo único que se me ocurre es algún tipo de error de concurrencia (aunque el problema se ha dado en contextos en los que no tendría mucho sentido). ¿Es necesario utilizar mutex con el logger?

### 💻 Logs

Acá hay un backtrace del crash:

    #0  0x000072bc89de63f4 in ?? () from /usr/lib/libc.so.6
    #1  0x000072bc89d8d120 in raise () from /usr/lib/libc.so.6
    #2  0x000072bc89d744c3 in abort () from /usr/lib/libc.so.6
    #3  0x000072bc89d75354 in ?? () from /usr/lib/libc.so.6
    #4  0x000072bc89df0765 in ?? () from /usr/lib/libc.so.6
    #5  0x000072bc89df3f54 in ?? () from /usr/lib/libc.so.6
    #6  0x000072bc89df4902 in ?? () from /usr/lib/libc.so.6
    #7  0x000072bc89df5906 in realloc () from /usr/lib/libc.so.6
    #8  0x000072bc8a037684 in string_append () from /usr/lib/libcommons.so
    #9  0x000072bc8a0383d7 in _string_append_with_format_list () from /usr/lib/libcommons.so
    #10 0x000072bc8a037863 in string_from_vformat () from /usr/lib/libcommons.so
    #11 0x000072bc8a03746c in _log_write_in_level () from /usr/lib/libcommons.so
    #12 0x000072bc8a0371cd in log_info () from /usr/lib/libcommons.so
    #13 0x0000565ea870e1e0 in thread_cancel (tcb=0x72bc7c002cc0) at src/thread.c:83
    #14 0x0000565ea870cc9e in process_exit (pcb=0x72bc84005ab0) at src/process.c:94
    #15 0x0000565ea870db88 in attend_process_exit () at src/syscalls.c:167
    #16 0x0000565ea870deda in handle_syscall (instruction=..., interrupt=false)
        at src/syscalls.c:234
    #17 0x0000565ea870b837 in handle_dispatch (tcb=0x72bc7c002cc0) at src/cpu.c:72
    #18 0x0000565ea870d630 in short_term_scheduler (_=0x0) at src/short_term_scheduler.c:38
    #19 0x000072bc89de439d in ?? () from /usr/lib/libc.so.6
    #20 0x000072bc89e6949c in ?? () from /usr/lib/libc.so.6

En la consola se imprime lo siguiente:

    malloc(): unaligned fastbin chunk detected
    zsh: IOT instruction (core dumped)  ./out/kernel THE_EMPTINESS_MACHINE 16

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by iago64** [comment]
Buenas! Cómo va?

Lo corriste con [Valgrind](https://docs.utnso.com.ar/guias/herramientas/valgrind)? El log no te dice nada?

Saludos.-

**Comment by tralph3** [comment]
Hola, no pude identificar el problema. Pero me centro en otras cosas por ahora, gracias.
