### ISSUE TITLE
Logs obligatorios

### ISSUE THREAD

**Issue by ramirob03** [sisoputnfrba/foro#4477]
### 🛠️ Lenguaje

Go

### 🖋️ Descripción

Buenas, espero que anden bien. Quería consultar si se puede imprimir los logs con la función logPrintf, porque intentando utilizar slog no logramos que se impriman correctamente los logs tanto en consola como en el archivo

### 📔 Citas del enunciado/videos

> Cada módulo contará con un listado de logs mínimos y obligatorios los cuales deberán realizarse utilizando la biblioteca de [log/slog](https://pkg.go.dev/log/slog@go1.22.1) sugerida por la cátedra y los mismos deberán estar como Logger.Info(), pudiendo ser extendidos por necesidad del grupo utilizando Logger.Debug()

### 📝 Normas del foro

- [X] Leí los lineamientos del foro

**Comment by RaniAgus** [comment]
¡Buenas! Antes de descartar la idea de usar log/slog, ¿llegaron a leer la guía de logging en golang docs? ¿En qué los podemos ayudar con eso?

https://golang.utnso.com.ar/guias/programacion/logging

Saludos

**Comment by ramirob03** [comment]
Ya lo pudimos solucionar, gracias! Cierro el issue
