### ISSUE TITLE
problemas para debaguear

### ISSUE THREAD

**Issue by guillermo126** [sisoputnfrba/foro#469]
buenas estoy teniendo problemas para debaguear mi entrenador desde eclipse y queria hacer un par de pruebas antes de aplizar fuse, x ahora a mis entrenadores los ejecuto de la siguiente manera ./Entrenador ./ash.txt y me tira un eror que dice Can't find a source file at "/build/buildd/eglibc-2.19/string/../sysdeps/i386/i686/multiarch/strlen-sse2-bsf.S" 
Locate the file or edit the source lookup path to include its location.

nose si sera un error no pero la cuestion es q se me cierra el modo debag

¿como hago para poder debaguear?

**Comment by RaniAgus** [comment]
Resulta que en algunos casos el mensaje que tira Eclipse es `No source available`. Quizás por eso cuesta un toque encontrar el issue al buscar por este no-error, aunque la respuesta es la misma: es un error de vista.

Este comentario es solamente para que también aparezca el issue al buscarlo 😛
