### ISSUE TITLE
Error datos proporcionados por el header

### ISSUE THREAD

**Issue by dromero-7854** [sisoputnfrba/foro#480]
Buenos días, 

Mi consulta es la siguiente: formateé un archivo osada de 2GB  para empezar a trabajar. 

Estos son mis cálculos:
**F** (cantidad de bloques total) = 2^31 / 2^6=**2^25**
[0] Header: 1 bloque
[1] Bitmap: ((F/2^3)/2^6) = **2^16** bloques=**N**
[65537] Tabla de archivos: **1024** bloques
[66561] Tabla de asignaciones: ((F - 1 - N - 1024) * 4) / BLOCKSIZE = 2092992 bloques = A
[2159553] Bloque de datos: F - 1 - N - 1024 - A = 31394879 bloques

Verifico:  1 + 2^16 + 1024 + 2092992 + 31394879  = 2^25 = tamaño total del disco en bloques de 64bytes

**Primera duda**: Ahora bien, cuando leo el header del archivo formateado, el único dato que es igual a mis cuentas, es la cantidad total de bloques del archivo. Las posiciones de inicio de cada bloque (lo que se encuentra entre [ ] en mis cuentas) no me coincide ninguna.

Cuando se inicia el proceso, levanto del header el total de bloques y realizo las mismas cuentas para tener disponible las posiciones de inicio de cada bloque (**no utilizo la información brindaba por el header, que por el momento desconfío**)

**Segunda duda**: El problema que estoy teniendo es que a la hora de verificar si un directorio ya existe en la tabla de archivos (filesystem limpio, verifico los campos **estado**, **nombre**, y **bloque padre**) me parece que estoy verificando información mal formateada, ya que la primera vez encuentra un directorio (¿¿?? o por ahi algun error en mi lógica shit happens)
No se si el motivo es que no estoy utilizando los datos brindados por el header y estoy trabajando fuera del bloque de tablas de asignaciones. O algún error relacionado con el proceso que formatea el disco.

**Ultima pregunta**: Me podrian pasar un tamaño de disco que este verificado el correcto funcionamiento.

Disculpen si fui extenso, anoche me quede hasta la 3 am y no lo pude hacer andar jeje
Saludos y gracias...
Dante Romero

**Comment by tferraro** [comment]
Holis, @dromero-7854 te sirvió mi respuesta? Pudiste solucionar el problema?

**Comment by dromero-7854** [comment]
Como estás Tomás, 

Con respecto a la primera consulta, hoy verifico si los offset en bytes proporcionados por el header estan ok. Igualmente me imagino que si, sino algún otro grupo lo hubiera notado también. Todos mis cálculos están basados en bloques y no en bytes.

Con lo segundo, ya lo revise y fue un error en mi código, que ya pude solucionarlo.

Te pido disculpas por la demora...

Saludos y gracias
Dante Romero
