### ISSUE TITLE
Duda FUSE

### ISSUE THREAD

**Issue by ericstoppel** [sisoputnfrba/foro#481]
Hola, tengo una duda con el manejo de FUSE, basicamente con la logica del proceso que va a usar este metodo. Yo cuando cree un entrenador por dar un ejemplo y quiera buscar sus medallas tengo que crear a la vez con este un pokedexCliente que reciba el path del entrenador y monte el contenido del mismo en una carpeta vacia?

**Comment by tferraro** [comment]
Holis, @ericstoppel pudiste solucionar tu duda? Se puede cerrar el issue? :policeman:

**Comment by tferraro** [comment]
Cierro el tema por inactividad. Si la duda persiste, @ericstoppel volvé a abrir el issue!
