### ISSUE TITLE
Debuggiando FUSE Example

### ISSUE THREAD

**Issue by ntaboada** [sisoputnfrba/foro#485]
Buenas noches!

Vengo a molestar a ver si me tiran una mano. Quiero poder debbuggear con el IDE pero no estoy pudiendo. Me gustaria poder hacerlo para entender bien cuales son los parametros que reciben las funciones FUSE. Estos son los pasos que estoy haciendo:
1) Seteo un breakpoint en la funcion readDir.
2) Run Configuration > Path Variables > tmp (mando por argumento un punto de montaje)
3) Levanto en modo debugger lo corro hasta el "return fuse_main" 

Despues de eso empiezo a probar desde la consola parandome en el punto de montaje tirando un "ls" pero jamas entra al breakpoint. 
Que estoy haciendo mal?

**Comment by chrisgel15** [comment]
Ya lo logré hacer andar con lo que dijo @gastonprieto 

Gracias!!!
