### ISSUE TITLE
Abro la VM y se me reinicia la computadora.. WTF!?

### ISSUE THREAD

**Issue by fedeberco** [sisoputnfrba/foro#490]
Buenas tardes,
Estoy teniendo un problema insólito que no incumbe al tp pero quería consultarles. Desde hoy que cada vez que quiero abrir la VM se me reinicia la computadora. Copie la VM en otra computadora y abre perfecto. Se que es algún problema de mi computadora pero estuve buscando y no se solucionarlo. Desinstale VM Box, lo volvi a instalar y pasa lo mismo. Importe una copia vieja de la VM y pasa lo mismo. 
Por casualidad a alguno le pasó algo parecido? Alguna idea de como solucionarlo o que debería hacer?
Desde ya muchas gracias.

**Comment by mgarciaisaia** [comment]
Tendría que leerme las 5 páginas de [este thread en los foros de VirtualBox](https://forums.virtualbox.org/viewtopic.php?f=6&t=79028) para ayudarlos, y no tengo máquina en la que probarlo, y blah. Pero el último post que hay en este preciso momento es alguien quoteando a uno que dijo "Hey, gracias, eso anduvo", agregando "a mí también". Así que busquen en las últimas páginas ([uno](https://forums.virtualbox.org/viewtopic.php?p=374193#p374193) se pone a [gritarle a las nubes](http://knowyourmeme.com/memes/old-man-yells-at-cloud) quejándose de tener que apagar Hyper-V y no se qué más), que por ahí va a estar la solución seguramente.

Y, cuando la encuentren, cuentennos acá, así el próximo tarda menos en resolver, je.

Son los riesgos de estar en el tope de la ola con los updates. Se ve todo más lindo y canchero, pero a veces te adelantás tanto que te la das de trompa contra el piso :/

**Comment by FBerco** [comment]
¡FUNCIONÓ!
**Solucion**: Desactivar Hyper-V

@iago64 @mgarciaisaia Muchas gracias por el seguimiento de la issue, la verdad ya no sabía que hacer para solucionarlo. Abrazo grande

**Comment by mgarciaisaia** [comment]
🎉🎉🎉🎉

**Comment by iago64** [comment]
🎉Ahora a seguir con el TP!
@FBerco no tenes nada que agradecer, estamos para ayudar.

P.D: no te olvides de cerrar el issue ;)

**Comment by FBerco** [comment]
@iago64 no me estaria dejando cerrarla, la podes cerrar vos?

**Comment by leolopepe** [comment]
Hola, estoy teniendo el mismo problema tengo Windows 10 

![image](https://cloud.githubusercontent.com/assets/15298738/23532783/20bc3236-ff8c-11e6-8961-586d5104f330.png)

y tengo instalado virtualbox Versión 5.1.14 r112924 (Qt5.6.2)
también tengo instalado Visual Studio 2015 para desarrollar en Android

Provee de desinstalar Hyper-V, destildar la casilla, luego reinicia la maquina pero no queda desinstalado

![image](https://cloud.githubusercontent.com/assets/15298738/23533064/1819e162-ff8e-11e6-916d-b44193e39596.png)

lo provee con realizar la desinstalar por consola y no me deja.

dism.exe /Online /Disable-Feature:Microsoft-Hyper-V-All

Sera por que tengo instalado una maquina virtual de android??

**Comment by afilgueira** [comment]
Hola, nuestros ingenieros estan trabajando para ud. Mientras tanto, cito el readme, vimos esto de casualidad: _Si la pregunta estuviera cerrada y no resuelve completamente tu duda, no escribas en esa misma pregunta: anotá el número de issue para referirlo en tu nueva pregunta._ :policeman: :policeman: :policeman:

**Comment by mgarciaisaia** [comment]
**¡Aloha! 👋** _(cuánto hace que no escribía esto...)_

Estimo yo, por lo que contás, que el amigo Visual Studio debe estar encargándose en cada boot de volver a habilitar la configuración esa, básicamente porque la necesita para funcionar (para el fondo de [esta eterna discusión sin tanto sentido](https://social.technet.microsoft.com/Forums/en-US/894da9c5-e64f-41cd-bf80-ac802f7a133d/hyperv-turns-back-on-automatically-after-automatic-update-of-operating-system) parecen coincidir en que _puede que posta sea Visual Studio el que está molestando_).

Como sea, si necesitás Hyper-V para laburar, probablemente _no quieras_ deshabilitarlo.

Se me ocurren dos alternativas para ofrecerte, aunque ninguna me encanta al 100%.

La primera es que leas [este blogpost](http://www.hanselman.com/blog/SwitchEasilyBetweenVirtualBoxAndHyperVWithABCDEditBootEntryInWindows81.aspx) en el que explican cómo hacer para que Windows te pregunte en cada boot si querés que arranque con HyperV habilitado o no. Esto implicaría que cada vez que switcheás entre trabajar en Android y trabajar en el TP tengas que reiniciar la máquina 😵🔫 La ventaja es que vas a estar corriendo VirtualBox como todo buen hijo de vecino, bajando la fricción del trabajo práctico (digamos, vas a estar desarrollando en un ambiente _mucho más parecido_ al de la entrega).

La segunda opción es que [conviertas el disco de la VM](https://metalop.com/2015/12/07/converting-virtualbox-vdi-diskfiles-to-hyper-v-vhd-files/) que les damos (el .vdi que te bajaste) al formato que entiende HyperV (entiendo que .vdh), y corras la VM ahí. La ventaja es que no tenés que cambiar mucho en tu compu, ni andar reiniciando. Las desventajas son que quizá no anda ¯\\\_(ツ)\_/¯, y que, si anda, vas a estar _un poquito más lejos_ del ambiente en que vamos a probar el TP en las entregas. Uno quiere creer que no debería cambiar nada por usar un sistema de virtualización diferente, pero uno quiere _mucho más_ no tener problemas durante el TP. Ya lo vamos a hablar durante las charlas de principio de cuatrimestre: suele convenir eliminar variables, y mantenerse relativamente cerca de lo que les recomendamos que hagan, para no comprarse problemas extra. Pero, buen, en este caso, nada, quizá no tenés otra opción, o el riesgo sea más barato que andar reiniciando la máquina todo el tiempo.

Pegale una mirada y fijate qué onda. Me gustaría tener una compu con Win10 para probar (_¿posta me gustaría?_) y darte un poco mejor feedback (_buen, eso sí_), pero no estaría siendo el caso.

Contanos qué te parece, cómo te va, y, cualquier cosa, si se pone peluda la cosa, cuando lleguen las charlas, lo vemos.

¡Un abrazo!

----

[Acá](https://social.technet.microsoft.com/Forums/en-US/f89a6535-4026-433d-9bbc-fa6edc47e749/can-hyperv-and-virtualbox-coexist?forum=win10itprogeneral) explican por qué no pueden coexistir VirtualBox y HyperV. Con _un poquito de suerte_, para fin de cuatrimestre vas a tener un poco más de idea de virtualización, que te ayude a terminar de cerrar la idea, pero en principio el problema es que el modo de funcionamiento de cada uno de estos _sistemas de máquinas virtuales_ es incompatible entre sí ¯\\\_(ツ)\_/¯

**Comment by mauro199304** [comment]
me pasa lo mismo se apaga mi pc al iniciar linux en la VIRTUALBOX desde que instale los controladores para usb2.0 para que pueda reconocer mi TPlink usb wifi , entonces como puedo desistalarlo??

**Comment by RaniAgus** [comment]
@mauro199304 Buenas!

Antes que nada, vuelvo a citar [la sección cómo usar del readme](https://github.com/sisoputnfrba/foro/blob/master/README.md#c%C3%B3mo-usarlo): 

> Si la pregunta estuviera cerrada y no resuelve completamente tu duda, no escribas en esa misma pregunta: anotá el número de issue para referirlo en tu nueva pregunta.

Más que nada sirve para que podamos entrar al foro, encontrar el issue abierto y atender el problema lo más rápido posible (es más difícil encontrar y dar seguimiento de los issues ya cerrados).

Para estar seguros, un par de preguntas básicas:

- Haciendo una [búsqueda rápida](https://forums.virtualbox.org/viewtopic.php?f=6&t=82410) al parecer la forma correcta de utilizar un adaptador (o cualquier otro dispositivo USB) es siguiendo este orden, ¿te aseguraste de hacerlo así?:

1. Con la VM apagada, en Settings, agregar al adaptador entre los dispositivos USB
2. Quitar el adaptador
3. Arrancar la VM
4. Y *por último* insertar de nuevo el adaptador USB

- ¿Desactivaste Hyper-V como se dice más arriba en el issue?

Reabro el issue y doy el aviso así otro ayudante te puede asesorar mejor. Mientras, si eso no te funcionó, ¿podrías darnos más contexto sobre la PC sobre la que estás corriendo la VM? (Sistema Operativo host, motherboard, procesador, RAM y versión de VirtualBox)

**Comment by mauro199304** [comment]
hola @RaniAgus segui todos lo pasos que me dices active el usb retire el adaptador prendi el VM conecte denuevo y nada tambien desactive el Hyper-V y nada, mi adaptador se vee ahi pero no conecta internet, pero al poner el comando iwconfig en linux dentro del VM no aparace mi adaptador es como si no lo viera. el adaptador funciona muy bien en windows, mi systema operativo es Windows 10 pro, procesador AMD Ryzen 5 3400G 4 procesadores, RAM 16.0G , version de VM 6.1.18

**Comment by mauro199304** [comment]
![20210320_225459](https://user-images.githubusercontent.com/61486350/111893244-54455e80-89cf-11eb-990c-1f20770d4850.jpg)

**Comment by iago64** [comment]
@mauro199304 kali@kali? una consulta, de donde sacaste la vm? Porque este foro es solo para consultas de Sistemas Operativos de la UTN FRBA y las VMs que usamos nosotros no estan basadas en Kali Linux.

Saludos.-

**Comment by mauro199304** [comment]
no recuerdo muy bien de donde . llegue a este foro googleando buscando respuestas del por que se apagaba mi VM entonces fue como llegue a este foro , pero de todas maneras gracias,  saludos.

**Comment by felipe804** [comment]
alguien me dice por que cuando instalo el virtualbox se me reinicia la pc
