### ISSUE TITLE
Solución de Challenge.bin

### ISSUE THREAD

**Issue by Matias-Rivas** [sisoputnfrba/foro#491]
Buenas:
Estuve trabajando con el challenge.bin, y encontré:
- 134 archivos .txt con el ASCII ART correspondiente a los primeros 134 pokemon (me parece raro que no sean 151...)
- un archivo special.txt con caracteres extraños, que abajo de todo dice "El Pokémon misterioso es: MISSINGNO."
- un archivo README.txt que explica el contenido del .bin
- un video con extensión .mp4 de las primeras versiones de pokemon.

Así que con estos datos, arriesgo: el pokemon especial es MissingNo, se encuentra en Pueblo Paleta y el entrenador que gana la pelea es Wyatt (con un Squirtle).

¿Está bien? Ojalá que sí, quiero esas amables felicitaciones (?
Saludos

**Comment by sarietti** [comment]
Hola gracias a todos por las respuestas, ya pude leer correctamente los archivos, tenia un error en la aritmética de la lectura de bloques.

Efectivamente el video me dio el mismo md5sum que pusieron.

Saludos!

**Comment by CarolinaPonceRodriguez** [comment]
Hola que tal. Tengo una consulta sobre el archivo README.txt. Lo que hice para probar levantar ese archivo es directamente buscar en los bloques de datos el primer bloque que corresponde a ese archivo.
Y me levanta lo siguiente;
CHAR*MANDER CHALLENGE

Hay un Pokémon mistrioso escondido en nuestro directorio! Sabemos que un entrenador pudo encontrarlo y enfrentarse con el.

En la carpeta Pokemons vas a encontrar los ASCII-ART de cada especie, muy probablemente la información sobre el Pokémon misterioso esté allí!

Además, vas a poder encontrar a nuestro entrenador batallando con él.


Si no queres buscar los archivos a mano, te recomendamos usar el siguiente comando desde el punto de montaje:

find -type f | grep special


¿Cuál es el nombre del Pokémon misterioso?
L���
�/��v9�ףNepW  \
                |                           L
                |                           |
                |  _ /,                     |
                | | L)'..                   |
                | .    | `                  |
                '  \'   L                   '
                 \  \   |                  j
                  `. `__'                 /
                _,.--.---........__      /
               ---.,'---`         |   -j"
                .-'  '....__      L    |
              ""--..    _,-'       \ l||
                  ,-'  .....------. `||'
               _,'                /
             ,'                  /
            '---------+-        /
                     /         /
                   .'         /
                 .'          /
               ,'           /
             _'....----""""" mho�����G���vƼ+7ű�IA�(d���

Comparando con los demas pareciera que me esta dando valores de mas. Y lo que hice bien harcodeado fue esto:

t_BloqueDeDato * otro = pmap +((11501*64)+ (19138*64));

donde t_BloqueDeDato es una estructura con un campo unsigned char de 64 bytes, pmap apunta al comiento del challenge, 11501 son todos los bloques de (header,bitmap,tabla de archivos,tabla de asignaciones) y 19138 es el bloque inicial que obtengo para ese archivo de la tabla de archivos. Alguno me podria tirar una mano? 

Gracias!!!

**Comment by chrisgel15** [comment]
Según entiendo tu puntero apunta al principio de donde comienza ese archivo, y parece ser que está correcto porque empezas a leer bien.

Pero luego ese puntero como lo recorres para imprimirlo en el archivo o en la pantalla? En esa aritmetica te debés estar pasando del fin del archivo...

**Comment by CarolinaPonceRodriguez** [comment]
Ah creo que ya entendi que puede ser. Yo para mostrar los datos del bloque de datos de 64 bytes que lei hacia lo siguiente:
printf("Valor:  %s\n", otro->BloqueDato);
Bloque dato es un unsigned char de 64. Ahora lo que no estaba teniendo en cuenta es que es posible que el archivo pese menos de los 64 bytes, entonces los bytes proximos que estaria leyendo son basura.
Otra duda es la siguiente, si en tal caso cuando yo tengo un bloque que no esta ocupado del todo, por que tengo en la tabla de asignaciones en "puntero al siguiente". Osea, porque para este archivo README.txt yo obtuve que de la tabla de asignaciones esta conformado por los bloques consecutivos: 19138 y 19139.

Saludos!

**Comment by chrisgel15** [comment]
Es correcto que tenes que tener en cuenta que el archivo pese menos de 64 bytes y que por otro lado que pese mas de 64 bytes pero que el ultimo bloque no esté del todo completo. 

La forma que yo resolvi ese tipo de situaciones es ir comparando la tabla de asignaciones con el tamaño del archivo (que esta en el header). De esa forma podes ir leyendo de la tabla de asignaciones cual es el bloque siguiente pero sin pasarte del tamaño total. Tambien tenes que tener en cuenta para la logica del READ de FUSE que a veces te pide que le des bytes que no necesariamente sean desde el principio del archivo (ejemplo un archivo muy grande te lo va pidiendo de a partes, pero no son bloques multiplos de 64 bytes) entonces tenes que jugar con 
- El tamaño del archivo
- El primer bloque
- La tabla de asignaciones,  
- Los bloques de datos
- El byte donde comenzar a leer
- La cantidad a leer.

Para armar una logica que te permita pararte en el byte correcto a leer, y leer la cantidad necesaria que te piden sin pasarte del tamaño del archivo (porque sino vas a estar pasando mas bytes de los que pertenecen a ese archivo y vas a tener problemas como el que posteaste).

Espero te sirva, saludos!

**Comment by chrisgel15** [comment]
Ejemplo: Archivo 65 bytes.
Primer bloque 0.

Tabla Asignaciones
0 -> 1
1 -> 5
5 -> 8

Son dos bloques, pero como pesa 65 bytes tenes:
- Todo el primer bloque.
- 1 byte del segundo bloque.

--> No tenes que leer el bloque 8, ya que te estas pasando del tamaño total.

**Comment by CarolinaPonceRodriguez** [comment]
Osea que yo podria tener en la tabla de asignaciones ese bloque 8(como el ejemplo que diste) sin bytes correspondientes al archivo en si? No tiene mucho sentido.

Gracias!

**Comment by chrisgel15** [comment]
Para mi la tabla de asignaciones no necesita mas sentido que el que tiene.
Pensalo de esta forma, imaginate un archivo de 64 bytes (un bloque). 
En la tabla de archivos te puede decir decir: **Primer bloque: 1.**
Ese "1" es un indice...un indice para la **tabla de datos**. Entonces vos sabes que si lees el bloque 1 de la tabla de datos obtenes los 64 bytes de ese archivo, o sea todo el archivo.
Pero si vas a la tabla de **asignaciones**, en la posicion 1 del array ponele que tengas otro valor: el 15.

¿Eso significa que tenes que leer el bloque 15 de la tabla de datos? No, porque vos sabes que tu archivo ocupa un solo bloque (sabiendo el tamaño), ese valor 15 de la tabla de asignaciones puede haber quedado de otro archivo anteriormente grabado, o ser basura. ¿Me explico?

Por eso te digo que con el bloque inicial y con el tamaño del archivo, podes saber cuantas veces saltar por la tabla de asignaciones y cuales bloques leer de la tabla de datos. A eso le tenes que agregar una condicion para frenar la lectura, porque nadie te dice cual es el ultimo bloque o ultimo byte, lo tenes que calcular vos.

Con respecto a tu edicion, yo cuando hice la misma prueba que estas intentando hacer vos, lo que hice fue un **fopen** de un nuevo archivo y luego escribi en ese archivo los bloques que necesitaba con la funcion **fwrite**.

Igualmente si seguis con dudas quizas deberia responderte algun ayudante por si le estoy pifiando en algo, saludos!

**Comment by mgarciaisaia** [comment]
A las _genialidades_ que vino contando @chrisgel15 sólo quería agregar un detalle sobre [este comentario](https://github.com/sisoputnfrba/foro/issues/491#issuecomment-252510252) de @CarolinaPonceRodriguez.

`printf()` es una función que imprime texto en pantalla. La particularidad que tiene es que soporta recibir distintos _formatos_ para interpolar variables dentro del texto. Es decir, no sólo imprime strings constantes, si no que soporta que le pasemos variables, a las que muestra con el formato que le indiquemos. En tu caso, `printf("Valor: %s\n", otro->BloqueDato);` tiene un `%s`, que indica que muestre la variable correspondiente (en este caso, `otro->BloqueDato`) como un string. Y un string es, por definición, un array de `char`s que termina ante el primer caracter `\0` que contenga. Y eso es lo que hizo el `printf` en tu comentario anterior - tomó a `otro->BloqueDato` como un puntero, y empezó a imprimir caracter por caracter, hasta que encontró un `\0`. `printf` nunca se enteró de que había bloques de a 64 bytes, ni de OSADA, ni de nada en absoluto. Agarró el primer byte que le pasaste, vio que no era `\0`, lo imprimió, miró el siguiente, tampoco era un `\0`, lo imprimió... y así. Eventualmente, encontró un `\0`, y ahí dejó de imprimir. Claro, para ese momento no sólo ya había impreso los 64 bytes de un bloque de datos, si no los 64 del siguiente, y otros del siguiente, y... Bueno, se entiende.

Lo que quiero que se lleven de este párrafo es que `%s` en un `printf()` significa string - sin importar de qué tipo hayan declarado el puntero que le pasan. Si no es un string lo que quieren mostrar (es decir, si no quieren mostrar _todo hasta que aparezca el primer `\0`_), entonces no usen `%s`, porque no es lo que quieren hacer.

¡Salute!

**Comment by tferraro** [comment]
Cierro el tema por inactividad y porque ya perdió un poco la relevancia a esta altura del cuatri :stuck_out_tongue: .
