### ISSUE TITLE
Estado de Conexión en un socket

### ISSUE THREAD

**Issue by varas-c** [sisoputnfrba/foro#494]
Tengo la siguiente duda.

En el checkpoint me comentaron que el mensaje de "Turno Concedido" en el planificador fue eliminado. Es decir, los entrenadores mandan sus pedidos sin esperar un turno, pero sí esperan la respuesta del mapa ante esa solicitud.

Teniamos implementado un metodo de desconexión basado en el Turno Concedido, peero como lo sacaron y lo tuvimos que sacar del codigo, este método ya no es tan efectivo.
Como ahora los entrenadores mandan mensajes todo el tiempo sin esperar el turno, mi planificador se entera "tarde" que el entrenador se desconectó.

Mi pregunta es, ¿hay alguna forma de hacer "ping" sobre un socket para ver si el cliente está conectado o no? Se que la forma de ver si un entrenador se desconectó es hacer un recv y ver si los bytes leidos es cero, pero este metodo digamos que "se fija en el mensaje recibido" o sea en el buffer de cada socket. Hay alguna forma de "operar" directamente sobre la conexión? Por ejemplo haciendo un "ping" para ver si el entrenador esta "vivo" o se desconectó, sin ver necesariamente los mensajes que manda.

Espero haber sido claro :) Gracias!

PD: Probamos las funciones getsockopt y getpeername pero ninguna detecta las desconexiones. 
Info sacada de acá: http://stackoverflow.com/questions/4142012/how-to-find-the-socket-connection-state-in-c

**Comment by mgarciaisaia** [comment]
Che, está buenísimo que se te plantee esta duda. La verdad es que, sí, es un caso que cambió bastante con los cambios que hicimos al enunciado. Y hasta ahora, al menos a mí, no se me ocurrió cómo mejorar la situación.

Bah, una opción es implementar una _cola de mensajes_ en tu Mapa. Tenés un hilo que se dedica a hacerle `recv()` constantemente a todos los sockets, y cada vez que recibe un mensaje manda esos bytes a una cola de ese socket, y el hilo que "realmente" tiene que leer los mensajes (el planificador, digamos) lee esa cola en vez del socket. De ese modo, ni bien llega un mensaje lo mandás a _otro_ buffer, y podés seguir haciendo `recv()` sobre el socket para enterarte al instante de que se cayó la conexión.

De más está decir que ni a palos pretendemos que todos implementen esto. Es parte del tradeoff que elegimos cuando cambiamos el enunciado.

_Si algún grupo gustara hacerlo_, me encantaría verlo andar (para valores muy esotéricos de _me encantaría_), pero no es obligatorio ni prioritario en absoluto.

Para cerrar, estas cosas son las que nos gusta charlar en los temibles coloquios. Entender qué consecuencias trajo cada decisión de diseño (tanto nuestras en el enunciado como suyas en la implementación), qué ventajas y desventajas tuvo, y por qué decidieron que la que implementaron sí y las otras alternativas no.

Lindo thread, che :)

**Comment by varas-c** [comment]
Justamente lo de la cola de mensajes lo había pensado pero, es bastante laburo y laaaaaargo. Habiamos intentado con mi grupo ver formas de verificar si las conexiones seguian abiertas, teniamos varias en mente, como la de la lista de Mensajes que comentas o crear un hilo "chusma" que esté revisando todo el tiempo los mensajes mandados o una forma medio complicada, sería que el mapa envíe paquetes estilo "Ping" que sean ignorados por el jugador

Pero si, es mucho laburo y puede llevar a muchas fallas tambien. Ademas no somos expertos en redes, tcp y esas cosas, por lo que nuestro poco conocimiento nos impedía avanzar con este tema de ver si las conexiones estaban vivas o no y peor, la conexion se puede caer en cualquier momento.

Al final, decidimos hacerlo como comentaron mas arriba :) Igual, por lo menos a mi, me "picó" la curiosidad de saber como hacer esto. Quedará para mas adelante supongo
