### ISSUE TITLE
Consulta perdida de vida por señal

### ISSUE THREAD

**Issue by jjuli93** [sisoputnfrba/foro#497]
Buenas, me surgió una duda con respecto a las señales que se les puede mandar a entrenador. Según el enunciado le puedo mandar una señal para restarle una vida restante, ¿podría mandarle esta señal si las vidas restantes fueran 0? 
En el caso de ser posible, ¿como lo resolvería? Se me ocurre hacer que se muera el entrenador pero luego de ejecutarse la señal volvería a ejecutar desde donde se había quedado. (Tal vez podría tener un booleano y preguntar luego de que realize alguna acción si el entrenador tiene que morirse y matarlo ahí)

**Comment by tferraro** [comment]
Muy buenas! Me colgué de decir _la razón_ por la que volvimos a abrir el issue el sábado.

Hubo un desfasaje de lo que se quiso preguntar, lo que contesté y lo que se entendió de mi respuesta. Esto lo detectamos hablando con @jjuli93 el día del checkpoint presencial.

La pregunta original estaba orientada a:
> Si un entrenador se queda sin vidas (es decir, su contador de vidas se vuelve 0), que pasa?

Tal como cite al enunciado _más arriba_, se debe preguntar *si se desea reiniciar el juego*. Esto implica que el Entrenador pierde todo lo que había capturado y conseguido y se queda a la espera de si volver a empezar, aumentando el contador de reintentos o terminar su ejecución.

Siguiendo la pregunta original, `que pasaría si se le manda la señal estándo en 0 vidas?` No debería pasar nada, debería en si, ignorar dicha señal dado que se espera la confirmación si continuar o no.

Solo esa aclaración.

Si quedó más claro el desorden, @jjuli93 porfis confirmalo cerrando el issue.

Perdón por la desprolijidad del asunto :stuck_out_tongue: 

Tom
