### ISSUE TITLE
error: Cannot access memory at address 0x30

### ISSUE THREAD

**Issue by jhonSalazar** [sisoputnfrba/foro#500]
Hola,
tengo el siguiente código:

while (*mapas) {
		char* objetivo = string_from_format("obj[%s%s", *mapas,"]");
--->		char ** objetivos = config_get_array_value(archivo, objetivo);
		conectarse_con_mapa(*mapas, objetivos);
		++mapas;
		++size;
	}

Mi programa compila pero no ejecuta como debe ser, me imprime Segmentation fault. "Debuggueando" Me encontré con esto:

objetivos	char**	0x804c790

*objetivos char* 0x30 <error: Cannot access memory at address 0x30>

Name : *objetivos
	Details:0x30 <error: Cannot access memory at address 0x30>
	Default:0x30 <error: Cannot access memory at address 0x30>
	Decimal:48
	Hex:0x30
	Binary:110000
	Octal:060

Cuando comento esta sentencia char ** objetivos = config_get_array_value(archivo, objetivo);
Mi programa ejecuta y hace lo que tiene que hacer, pero no logro solucionar el problema, alguna sugerencia? Desde ya muchas gracias.

Saludos.

**Comment by jhonSalazar** [comment]
Buenas,

Nosé porque cuando te mostré el código no te muestra el char* (String) en la varibale objetivo, y el char** objetivos (array de string), pero te puedo asegurar que estoy usando los tipos adecuados. Sigo con el mismo problema,

**Comment by jazcarate** [comment]
Primero lo primero.... No salen los asteriscos `*` porque GitHub (y, en realidad, MarkDown) lo que hace es ponerlo *italizado*. Cuando queres mostrar código, pones tres `back-ticks`, _like so_:

```
while (mapas) {
    char objetivo = string_from_format("obj[%s%s", mapas,"]");
    char * objetivos = config_get_array_value(archivo, objetivo);
    conectarse_con_mapa(*mapas, objetivos);
    ++mapas;
    ++size;
}
```

Segúndo, y mucho menos importante, al debugear, el string que interpolas `objetivo` está bien generado?
encontras ese atributo en el archivo de configuración? Está bien abierto el archivo de configuración _(una facil, es ver si `archivo` vale `NULL` o `-1`, porque falló el abrirlo)_?

**Comment by jhonSalazar** [comment]
Muchas gracias por la info, lo voy a tener en cuenta para la próxima,

En cuanto al archivo abre perfectamente e incluso puedo leer los otros valores, como símbolo, vidas, etc. 
En estos momentos me acaba de funcionar perfectamente y la verdad ni idea de que es lo que estaba pasando.

**Comment by jazcarate** [comment]
Si vuelve a pasar; no nos dejes con la intriga! 💃

**Comment by jhonSalazar** [comment]
No lo haré,
Voy a continuar con el programa, les agradezco por su tiempo.

Saludos.
