### ISSUE TITLE
Problema al implementar write en FUSE

### ISSUE THREAD

**Issue by Matias-Rivas** [sisoputnfrba/foro#501]
Quizás me esté adelantando un poco. Éste es el problema:
Tengo getattr, readdir, read y write implementados, con las correspondientes asignaciones en el struct fuse_operations. Con los primeros tres no tengo problemas, abro y leo todos los archivos, pero cuando intento modificar un archivo abierto (en este caso, estoy intentando guardar cambios en el archivo "archivo.txt" que viene dentro de basic.bin con Leafpad), noto dos cosas:

- Salta un error que dice "No se puede abrir el archivo para escritura"
- De todas las lineas que aparecen con cada operación realizada en la terminal donde tengo a FUSE corriendo, hay una que dice que SETATTR(4) no está implementada (y según lo que leí, no es una de las operaciones corrientes).

Puse un par de printf (perdón...) dentro de mi implementación de write para ver si al menos entraba, pero ni siquiera.
Quisiera saber si tengo que tener algo más en cuenta. Intenté cambiar a `stbuf->st_mode = S_IFREG | 0777` en getattr (en el ejemplo está con 0444), pero no logré nada.

Desde ya muchas gracias.

**Comment by mgarciaisaia** [comment]
Juventud, divino tesoro: https://enunacalesita.wordpress.com/2012/05/27/solucionando-fuse-function-not-implemented-en-write/

**Comment by tferraro** [comment]
@Matias-Rivas te sirvió el link de Mati? Se puede cerrar el issue? :policeman:

**Comment by Matias-Rivas** [comment]
Si, muchas gracias!
