### ISSUE TITLE
Bug en so-nivel-gui: Coordenadas de una Pokenest

### ISSUE THREAD

**Issue by varas-c** [sisoputnfrba/foro#502]
Testeando el juego nos encontramos con el siguiente problema.

Las pokenest tienen una coordenada fija dado por su archivo metadata correspondiente.
Esas coordenadas indican la ubicación en la pantalla, o mejor dicho, en la terminal.
Por lo que estuvimos probando, **la cantidad de "coordenadas" que tiene una terminal, depende de la resolución de la misma.**

Es decir, si tenemos una pokenest con coordenada (50;30), puede ser que, **dependiendo del tamaño de la terminal, se muestre o no.** 

Una Pokenest con coordenada (50;30) en una terminal "normal" (con normal me refiero al tamaño estandar de la consola cuando apretas ctrl alt T) se ve asi

![terminal1](https://cloud.githubusercontent.com/assets/18077589/19198188/239c2d1e-8c94-11e6-94e4-3a7c2536ab7f.jpg)

Y en una terminal maximizada, se ve asi.

![terminal2](https://cloud.githubusercontent.com/assets/18077589/19198189/23a1262a-8c94-11e6-91e7-95cb00d8da80.jpg)

**El problema es la Pokenest B** que tiene unas coordenadas "muy grandes" dpendiendo el tamaño de la pantalla.

Cuando la pokenest tiene coordenadas muy grandes y la terminal es chiquita, se dibuja mal y **el entrenador al intentar caminar a esa coordenada muy grande, empieza a saltar para todos lados** PERO termina llegando a la pokenest y capturando por lo que **al parecer es un error GRAFICO** nada mas

Hay alguna solución al respecto? Para nosotros es un bug de la librería que no tiene en cuenta estos "detalles".

En caso de que sea muy complicado arreglar este bug, cual es el tamaño de consola "ideal" para probar los mapas? Cosa de que las pokenest y los entrenadores no se "caigan" del mapa

Gracias!

Edit: Por si ayuda, la resolución de mi pantalla es 1680x1050

**Comment by mgarciaisaia** [comment]
¡Aloha!

Sí, es súper cierto lo que decís. Probablemente la biblioteca gráfica debería soportar que se le diga el tamaño del mapa, quizá, o andá a saber.

Como sea, en algún lado especificamos que las PokeNests de las pruebas van a estar siempre en lugares "visibles". Las pruebas las haremos en la VM Server, el tamaño "estándar" es algo así como 80x25 creo, pero no importa - la _garantía_ que les damos es que no vamos a probar PokeNests que no entren en la terminal.

Así que nada de [andar cayéndose por ahí](http://strategywiki.org/wiki/Pok%C3%A9mon_Gold_and_Silver/Ecruteak_City#Gym_Battle_.234:_Morty) 👍

**Comment by varas-c** [comment]
Buenisimo, gracias! Ya habiamos entrado en Kernel Panic viendo al entrenador saltar por todos lados pero nos dimos cuenta de ésto (por suerte).

Solucionado, cierro el Issue
