### ISSUE TITLE
Consulta sobre listas 

### ISSUE THREAD

**Issue by meligomez** [sisoputnfrba/foro#503]
la cosa es asi, hice una lista con los pokemons y sus respectivos datos, la cosa es cuando los agrego en la lista el ultimo pokemon que se agrega como que pisa los demas valores y queda una lista de ese pokemon repetido(ej : en ciudad plateada tengo 3 pokemons (marowak , scizor  y pikachu) al ser pikachu el ultimo me repite 3 veces pikachu) , treate de poner un malloc antes de hacer el list_add del tamaño de la estructura, pero cuando la muestro se pone todo en null y 0,
nose que estoy haciendo mal,
agradezco una rta y calquier cosa te detallo mas..

**Comment by varas-c** [comment]
Nos habia pasado algo parecido hace un par de semanas.

Seguramente los "Pokemon" que estas poniendo en una lista son punteros no? Por ejemplo

`
Pokemon* miPokemon = "marowak"  
list_add(miLista,miPokemon)

miPokemon = "scizor"
list_add(miLista,miPokemon)

miPokemon = "pikachu"
list_add(miLista,miPokemon)
`

Ahora cuando revisas la lista te fijas y seguramente tenes todos pikachus. Esto pasa porque cuando vos haces un list_add no estas guardando (por ejemplo la primera vez) un "Marowak", **estas guardando un puntero que apunta a miPokemon**, que en este caso miPokemon apunta a "Marowak"

Es decir, en la lista tenes esto: unPuntero, a donde apunta este puntero? apunta a miPokemon. miPokemon a donde apunta? a "Marowak"

Ahora la segunda ves, vos estas modificando otra vez el puntero miPokemon. miPokemon ahora apunta a "scizor". hacemos un list_add(miLista,miPokemon)

y ahora tenes en la lista dos punteros: unPuntero, otroPuntero

otroPuntero apunta a miPokemon y miPokemon apunta a "scizor"

Peeero que pasó con "unPuntero" ? A donde apuntaba? unPuntero apuntaba a miPokemon ... y miPokemon a donde apunta ahora? A Scizor! Que pasó con el Marowak?

Esto lo podes solucionar, por ejemplo, reservando memoria cada vez que haces una asignacion de pokemon.
```

Pokemon* miPokemon = malloc( tamaño para un pokemon)
miPokemon = "marowak"  
list_add(miLista,miPokemon)

miPokemon = "scizor"
miPokemon = malloc( tamaño para un pokemon)
list_add(miLista,miPokemon)

miPokemon = "pikachu"
miPokemon = malloc( tamaño para un pokemon)
list_add(miLista,miPokemon)
```

Ahora ya no se van a pisar los Pokemon porque cuando haces un malloc, te devuelve un puntero que apunta a una memoria donde vas a poder guardar tus Pokemon sin que se "pisen"

Si no la pifié, esto es lo que te pasa, que me paso hace un par de semanas  y al menos yo, lo solucioné asi

Ojo, te no olvides de liberar todos esos malloc cuando ya no los necesites 

Ojala te sirva!

**Comment by meligomez** [comment]
ssssi, era eso, muchasss graciasss!! :dancer:

**Comment by mgarciaisaia** [comment]
¡Aloha!

Lo que dijo @varas-c está relativamente bien en cuanto al síntoma y solución, pero no es precisamente esa la causa.

Bah, un poco pasa que escribiendo pseudo-código no queda del todo claro qué quiseron decir, pero la frase que más ruido hace es `estas guardando un puntero que apunta a miPokemon`. Al hacer `list_add` no guardás un puntero a la variable, si no que la lista agrega un puntero igual al que le pasamos a `list_add` (`miPokemon`, en este caso).

El problema es que muchas veces, para no hacer `malloc`, declaramos una única variable, y agregamos a la lista varios punteros a esa misma variable, cambiando sus valores entre un `list_add` y otro. Algo así:

```c
struct pokemon miPokemon;
miPokemon.nombre = "marowak";
...
list_add(mi_lista, &miPokemon);

miPokemon.nombre = "pikachu";
...
list_add(mi_lista, &miPokemon);
```

Acá lo que pasa es que hay una única variable - un único bloque con memoria suficiente para almacenar un `struct pokemon` -, y la apuntamos dos veces desde la lista. Como nunca reservamos memoria _nueva_ entre una asignación de `.nombre` y otra, estamos sobreescribiendo _la misma_ variable, y el resultado es ese que veíamos.

Ahora, cuando `miPokemon` es una variable de tipo puntero, para poder hacer `miPokemon->nombre = "..."`, primero tenemos que reservarle memoria. Eso en general lo hacemos con un `malloc`. Pero la clave no está en hacer `malloc`, si no en hacerlo _una vez por cada estructura que necesitemos_. Es decir, si cambiamos ese código por este:

```c
// atenti, este codigo sigue fallando
struct pokemon *miPokemon = malloc(sizeof(struct pokemon));
miPokemon->nombre = "marowak";
...
list_add(mi_lista, miPokemon);

miPokemon->nombre = "pikachu";
...
list_add(mi_lista, miPokemon);
```

Seguimos teniendo **exactamente el mismo problema** - reservamos memoria una única vez, y desde la lista apuntamos dos veces a esa memoria.

Para solucionarlo, como bien dijo @varas-c, tenemos que reservar una nueva porción de memoria después del primer `list_add`, y antes de hacer `miPokemon->nombre = "pikachu";`.


_Cualquier similitud con las [múltiples referencias al mismo objeto](http://pdep-utn.mumuki.io/exercises/2780-programacion-con-objetos-referencias-identidad-revisada) de otros lenguajes **no es** casualidad_
