### ISSUE TITLE
Problemas para crear biblioteca compartida

### ISSUE THREAD

**Issue by jhonSalazar** [sisoputnfrba/foro#506]
Buenas,

Tenemos problemas para crear nuestra propia biblioteca compartida, el error es el siguiente:

/home/utnso/git/tp-2016-2c-Space-JAMMM/Mapa/Debug/Mapa: error while loading shared libraries: libBiblioteca_grupal.so: cannot open shared object file: No such file or directory.

Es muy raro que no nos funcione porque anteriormente ya habíamos creado la biblioteca compartida commons, siguiendo los mismos pasos del video tutorial en la página utn.so.

Alguna idea que nos pueda ayudar por favor?.

Saludos.

**Comment by mgarciaisaia** [comment]
¡Hola @jhonSalazar!

Ese problema es [bastante conocido](https://github.com/sisoputnfrba/foro/search?q=error+while+loading+shared+libraries&type=Issues&utf8=%E2%9C%93), pero increíblemente todavía no escribimos una respuesta canónica y genial para solucionarlo.

Tu programa está compilando bien - el problema que estás teniendo es que, al ejecutar, el sistema operativo no encuentra tu biblioteca compartida (el archivo `libBiblioteca_grupal.so` que se genera al compilar tu biblioteca).

Por defecto, al ejecutar un programa, el sistema operativo busca las bibliotecas dinámicas que necesite en un par de rutas estándar (aunque parece que [no hay un comando único para listar esas rutas](http://unix.stackexchange.com/q/307727/49371)). Lo importante es que, por defecto, al compilar tu biblioteca, esta **no se copia a estos directorios** (al hecho de copiar la biblioteca a una ubicación _estándar_ en que todos los programas pueden encontrarlo lo llamamos _instalar_ la biblioteca - es lo que se hace cuando hacemos [`make install` en las commons](https://github.com/sisoputnfrba/so-commons-library/blob/1c66859b81d685997d736f2be6546fd1282d35f3/src/makefile#L31-L33), por ejemplo).

Durante la compilación de tu programa que _usa_ la biblioteca, el parámetro `-L` de `gcc` (uno de los que habrás agregado en las Settings de tu proyecto) le indica al compilador _dónde buscar_ la biblioteca durante la compilación, pero al momento de ejecutar ya no se tiene esa información - porque uno puede compilar el programa en una computadora, y ejecutarlo en otra, con la biblioteca en otro directorio. Como el SO no puede encontrar la biblioteca, te da este error.

Para que el SO encuentre tu biblioteca, tenés dos opciones. Una es _instalar_ tu biblioteca - es decir, _copiarla_ a los directorios estándar del sistema. Con esto, cualquier programa de tu computadora (incluso de otros usuarios de la misma, si los hubiera) puede usar esa biblioteca, y entonces por eso necesitás permisos de root (digamos, usar `sudo`) para poder hacer este cambio. La desventaja de esto durante el desarrollo es que tenés que asegurarte de que _cada vez que actualizás la biblioteca, no sólo la compiles, si no también la vuelvas a copiar a la ruta estándar_. Tocando el `Makefile` se puede hacer, pero desde eclipse no es tan trivial como uno quisiera.

La alternativa es usar `LD_LIBRARY_PATH`. Esta es una variable de entorno (es decir, una variable que es distinta para cada sesión de consola de cada usuario del sistema) en la que podemos listar directorios _extra_ en los que queremos que se busquen las bibliotecas, además de los directorios estándar del sistema. Para desarrollo es de lo mejorcito, porque no afectamos a otros usuarios (no hay que ser root), y porque podemos agregar ahí el directorio en que se compila la biblioteca compartida, y entonces no tenemos duplicada la biblioteca - no hay que andar copiándola a ningún lado.

Para settear esa variable desde la consola se puede usar el comando `export` - podés revisarte [este comentario](https://github.com/sisoputnfrba/foro/issues/215#issuecomment-214801992) en el que un poquito cuentan cómo hacerlo. Eso sí - tenés que hacerlo _en cada sesión de consola_, o - como dijo Damián ahí -, poner ese comando en un archivo que se ejecuta cada vez que abrís una nueva consola (el `~/.bashrc`).

Para ejecutar desde eclipse, en el video de bibliotecas compartidas que tenemos se explica cómo settear la variable esa editando las Run Configurations. Revisate el video y contanos si te funcionó.

Si nada de esto funciona, mirate http://faq.utn.so/errores-eclipse para poder ayudarte un poco más.

¡Un abrazo!

**Comment by tferraro** [comment]
@jhonSalazar te sirvió la respuesta? Se puede cerrar el issue? :policeman:
