### ISSUE TITLE
Visualizar directorios en disco Challenge.bin

### ISSUE THREAD

**Issue by CarolinaPonceRodriguez** [sisoputnfrba/foro#507]
Buenas, que tal, si bien la pruebas las estoy haciendo en el disco challenge.bin, esto aplica para cualquier disco en general.
Nosotros para el check anterior mostramos el recorrido del arbol de directorios de la siguiente manera:

Nombre del archivo: 114.txt
Nombre del directorio Padre:Pokemons
Nombre del directorio Padre:Vermilion City

Pero deberiamos poder mostrarlo como ruta es cierto? Asi: ./Vermilion City/Pokemons/114.txt
Creo que si porque por ejemplo, el mapa necesitaria para sus metadatas las rutas de los archivos, sean pokemons, medallas, etc.

Pregunta medio boluda, pero me viene bien confirmarlo!.
Saludos!

**Comment by CarolinaPonceRodriguez** [comment]
Bueno, me respondo sola y lo cierro, la lectura de los directorios como rutas ya quedo implementada.

Saludos!

**Comment by mgarciaisaia** [comment]
Quizá sea tarde, pero igual voy...

Mostrar la ruta absoluta de un archivo cualquiera es una operación "artificial". Digamos, no hay ninguna operación de FUSE que sea "buscá un archivo llamado XXXX y contame en qué ruta se encuentra".

Los pedidos van a ser al revés: "contame si existe el archivo /ruta/a/un/archivo". Y ahí sí, vas a empezar buscando un directorio `ruta` en el raíz, un directorio `a` dentro de ese, y así siguiendo. Así que ponerse a buscar al revés me parece que no les va a servir de mucho.
