### ISSUE TITLE
Como leer un archivo desde el Bloque de Datos?

### ISSUE THREAD

**Issue by EduBeghe** [sisoputnfrba/foro#509]
Hola, 

Ante todo pido perdón si ya lo preguntaron, pero leí lo que pude y no encontré mi pregunta en el foro.
Ya leí el header, el bitmap, la tabla de archivos, la de asignaciones, tudo bom, tudo legal, esta todo donde debe estar y ninguna cosa rara. Mi pregunta mas que de sintaxis es conceptual, no entiendo como leer un archivo? Osea se, por la tabla de asignaciones, que, por ejemplo, mi archivo tiene asignados los bloques 2,6,7 y 9, ahora yo puedo buscarlos 1 por 1 del bloque de datos, y después? Que hago con eso? Como corroboro que el archivo esta completo y correcto? Si, según entiendo, al ser .txt los que tenemos de ejemplo debería poder imprimirlos por pantalla, pero esto lo hago concatenandolos con un for? Hay alguna manera de hacerlo para el alumno lvl 4? Alguna magia oculta?

Gracias de antemano!

**Comment by afilgueira** [comment]
Si, los bloques se concatenan y te dan el archivo. No hay mas magia que esa. En los de texto, vas a poder leerlos para ver que esten bien. En los que sean imagenes, podes probar abriendolos. Si es algun video (entiendo que en el challenge habia uno tambien) podes abrirlo. Y podes chequear el MD5 vs el thread del challenge, a ver si los estas tomando bien.

Saludos!

**Comment by mgarciaisaia** [comment]
¡Aloha!

¿Anduviste mirando FUSE ya?

La clave del asunto está en definir qué significa _leer un archivo_.

`printf()` es una función que muestra texto por pantalla. Ustedes tienen que desarrollar un programa que interactúe con el sistema operativo para proveer al usuario de archivos y directorios (también conocido como "un filesystem"). Esa interacción _no va a ser_ mostrando texto por pantalla.

El objetivo que tienen ustedes es interactuar correctamente con FUSE. Para ello, miren la interfaz de FUSE.

"Leer un archivo", en el mundo FUSE, significa crear una función que, dado un archivo, un offset, y una cantidad de bytes, copie en un buffer esa cantidad de bytes a partir del byte `offset` de ese archivo. Es decir, el objetivo último de su función es hacer `memcpy` para poner en el buffer que reciben los bytes correspondientes a ese intervalo del archivo.

Eso dice FUSE. Si hubiera una función mágica `dameLosBytesDesdeAcaHastaAllaDeEsteArchivo(archivo, aca, alla);` que te devolviera un puntero a esos bytes, toda tu función read sería algo de la pinta de:

```c
int mi_read(algunTipo archivo, int inicio, int longitud, void *buffer, ....) {
  void *elContenido = dameLosBytesDesdeAcaHastaAllaDeEsteArchivo(archivo, inicio, inicio + longitud);
  // TODO: chequear que `inicio + longitud` no supere el tamaño del archivo, actuar en consecuencia
  memcpy(buffer, elContenido, longitud);
  return longitud; // FUSE quiere que le devolvamos la cantidad de bytes que leímos
}
```

Ahora, como su FS implementa OSADA, `dameLosBytesDesdeAcaHastaAllaDeEsteArchivo` es todo el circo que ustedes conocen de recorrer la Tabla de Archivos, Asignaciones, y bloques de datos. Y, a eso, sumarle el temita de que las cosas circulan por la red.

O sea, en el cliente, `dameLosBytesDesdeAcaHastaAllaDeEsteArchivo` probablemente sea _mandar un mensaje al server pidiendo estos bytes de este archivo_, y ya, y en el Server metan la lógica de recorrer las tablas y bloques para armar ese buffer.

El tema con `printf` es que el `%s` indica un _string_ - es decir, una secuencia de bytes terminada en `\0` -, mientras que los archivos que se almacenan en un FS no tienen por qué ser un string.

**Comment by marcelocejas** [comment]
Hola, sumando a lo que dice Edu, espero no meter ruido, no hay forma de ver el archivo sin interactuar con el cliente? O sea leer el archivo "archivo.txt" que tengo supuestamente en un buffer para pasarle al cliente y en lugar de pasarlo escribirlo en disco y leerlo con un editor de texto?

**Comment by EduBeghe** [comment]
Gracias por las respuestas!

Una consulta mas, la manera de concatenar los bloqueas es tan simple como crearme un nuevo array y castearlo a un file? O hay que hacerlo de otra manera?

Gracias de nuevo!

**Comment by mgarciaisaia** [comment]
@marcelocejas podés hacer mil cosas distintas para lo que mencionás.

El enunciado te pide que hagas un FS distribuído, y para hacer eso tenés que implementar FUSE en el cliente, y hacer un servidor que entienda OSADA. Y ya.

Ahora, si, además, querés hacerte un programa `leer-archivo` que reciba como parámetro un path y un disco OSADA, y que busque ese path dentro del disco e imprima el contenido de ese archivo por pantalla - todo bien. Es una buena forma de ir construyendo de a pasos, y de testear más aisladamente tu desarrollo.

Lo que sí les recomendamos es que no se olviden cuál es el objetivo primordial - hacer el FS distribuído. Si sentís que hacer esas herramientas extra te ayuda, dale para adelante, que está buenísimo. Pero estate atento todo el tiempo por si sentís que estás invirtiendo en ello más tiempo del que deberías/necesitás/corresponde/te sirve. En la entrega tenés que mostrarnos un FS distribuído funcionando, tengas o no las herramientas extra.

----

@EduBeghe ¿qué sería concatenar los bloques? ¿Qué haría ese nuevo array? ¿Cómo lo "casteás a file"?

**Comment by tferraro** [comment]
@EduBeghe, @marcelocejas  les sirvió la(s) respuesta(s) de Mati? Lograron resolver las dudas? Si es así, plz @EduBeghe cerrá el issue.

Saludos!
