### ISSUE TITLE
Problema con READ de fuse

### ISSUE THREAD

**Issue by juanoubi6** [sisoputnfrba/foro#510]
Buenas, ando con el siguiente problema cuando se invoca mi funcion read de fuse:

Al realizar cat sobre un archivo: el contenido de ese archivo es un string con una longitud de 13. Pareciera que fuse hace todo correctamente (llena la estructura buffer con mi mensaje tal cual quiero que aparezca) pero luego de hacer el return no hay ningun cambio en la consola.

Acto seguido, vuelvo a ejectuar cat sobre el mismo archivo y fuse funciona a medias: devuelve solo una parte de toda mi cadena y todo en la misma linea.
![asdas](https://cloud.githubusercontent.com/assets/17948943/19251310/1a74dfaa-8f15-11e6-87fa-21d5a6ba8bf8.jpg)

El codigo que usa mi funcion read es el siguiente:

```c
respuesta->buffer[respuesta->tamano]='\0';
strcpy(buffer,respuesta->buffer);

int retorno = strlen(buffer);
free(mensaje->buffer);
free(mensaje->path);
free(mensaje);
free(respuesta);
return retorno; 
```

Ya probe hardcodeando lo que quiero que muestre pero el problema persiste. Que puede estar pasando?

**Comment by mgarciaisaia** [comment]
¡Aloha!

Tendría que revisar con más ganas todo esto, pero en principio lo que más ruido me hace es que uses `strcpy` y funciones de string para manejar el contenido del archivo - ¿quién te garantiza que el contenido del archivo es un string?

**Comment by juanoubi6** [comment]
Yo pensé que como el buffer que hay que llenar(el de la función read de fuse)es un char* me imaginé que cualquier información que yo tenía que devolver tenía que ser casteada a un char y luego llenar el buffer.

Con que estructura (o de que forma) debería llenar ese buffer. Si yo tuviera que devolver los datos de una imagen por ejemplo, con que lleno ese buffer?

**Comment by chrisgel15** [comment]
Yo la estoy llenando con un **memcpy**

**Comment by juanoubi6** [comment]
Sigo con el mismo problema. Ya probe con un memcpy pero tampoco. Alguna idea?

**Comment by fedebonisconti** [comment]
Estás seguro de que `respuesta->buffer` tiene algo? Me suena a que lo estás mandando por sockets a eso, y puede que tengas algún error de punteros o mallocs/frees.

Fijate bien que en todos los pasos donde usas `respuesta->buffer`tenga algo que tenga sentido!

**Comment by tferraro** [comment]
Buenas,

Como comento Mati antes, usar funciones de strings para manejar memoria es
un gran No. Que el char como tipo de datos tenga el tamaño de un byte justo
no implica que lo que tenga sea un string y cumpla con el formato de string.

Para copiar memoria de un lado a otro, conviene siempre usar memcpy o sus
vatiantes.

Probaste no usando funciones de string en su totalidad? Especialmente no
usar srtlen. Sino, estas seguro de que estas sacando todo del buffer del
socket? Muchas veces queda buffer remanente por no recibir todo.

Saludos!

**Comment by juanoubi6** [comment]
Buenas. Es correcto lo que plantearon: el buffer me viene por sockets y lo tengo con los datos "123456789012345". Son 15 caracteres (en el servidor en el buffer malloquie 15 exactos). La linea que transifere mis datos de la respuesta del socket al buffer es:

**memcpy(buffer,respuesta->buffer,size);** (aclaracion, no puse offset porque eso se lo mando al servidor y este me retorna exactamente lo que voy a meter en el buffer).En respuesta->buffer hay "0123456789012345", en size hay 4096.  Me sigue pasando que el primer cat es como que lo ignorara (aunque ya debugie y se ve como llena el buffer con los datos). Los sucesivos cat despues del primero me devuelven las cosas tal como aparece en la foto de arriba de todo (salvo que en vez de ser "vamolore" ahora es "01234567".

Tengo otra duda que no es de este error pero no me cierra. Hay algun problema con que en size tenga 4096 y ,aunque yo este leyendo del servidor solo 15 caracteres, este devolviendo size en el return? La funcion deberia retornar 4096 (lo que realmente me llego) o 15 (lo que realmente "lei" del servidor y voy a mostrar")?

**Comment by marcogatti** [comment]
Buenas! 

No me voy a meter en la pregunta original que te estaban dando una mano los chicos. 

Lo que si te puedo contestar es que si vos haces un send de X bytes por un socket, lo mas recomendable es que del morro lado hagas un receive de (o varios receive que totalicen) X bytes también. En tu ejemplo, si vos mandas un por socket 4096 y del otro lado solo recibis 15, te va a pasar que los 4081 restantes van a seguir esperando en el buffer del socket a que los leas. 

Entonces mi pregunta es, en que momento pensas que esos bytes restantes van a ser  leídos? 

Saludos!

**Comment by juanoubi6** [comment]
> Lo que si te puedo contestar es que si vos haces un send de X bytes por un socket, lo mas recomendable es que del morro lado hagas un receive de (o varios receive que totalicen) X bytes también. En tu ejemplo, si vos mandas un por socket 4096 y del otro lado solo recibis 15, te va a pasar que los 4081 restantes van a seguir esperando en el buffer del socket a que los leas. Entonces mi pregunta es, en que momento pensas que esos bytes restantes van a ser leídos? 

Estoy bastante seguro que no es un tema de sockets. Yo envio correctamente y me llega lo que quiero que me llegue. Es mas, debugueando puedo ver lo que me llega en el buffer del socket y luego puedo ver que efectivamente estoy llenando el bufer de la funcion read de fuse correctamente (se ve el contenido exacto de lo que quiero mostrar en el buffer de fuse). Mi ultima pregunta iba mas por el lado de que, segun la documentacion, la funcion read debe retornar exactamente lo que se leyo. Si en mi size me llega un 4096 y yo lleno el buffer con 15, debo retornar los 15 o los 4096?

**Comment by marcogatti** [comment]
> la funcion read debe retornar exactamente lo que se leyo

Te referis a la funcion read de FUSE, no? Segun la documentacion: 
> Read should return exactly the number of bytes requested except on EOF or error, otherwise the rest of the data will be substituted with zeroes.

Lo que te quiere decir es que si te piden que leas 15 bytes, devuelvas solo esos 15 bytes que te pidieron, salvo que te pases del final del archivo o en caso de error. Esto es independiente de como vos manejes los sockets. Esos 4096bytes que envias normalmente no estan relacionados con el contenido del archivo, sino que es una simplificacion que vos haces. Por lo tanto, por mas que vos leas 4096bytes del socket, vos sabes que solo 15 de ellos son utiles, por lo que solo le das a FUSE esos 15bytes.

Saludos!

**Comment by juanoubi6** [comment]
>  Por lo tanto, por mas que vos leas 4096bytes del socket, vos sabes que solo 15 de ellos son utiles, por lo que solo le das a FUSE esos 15bytes.

Ok, entonces devuelvo el tamaño verdadero de lo que yo vaya a poner el en buffer (el de la funcion read de fuse). 

Por otra parte, sigo con el problema de la lectura (el cat que lee mal). Me fije si era un tema del getattr (ya que en un momento tengo que preguntar las caracteristicas del archivo y devolver un tamaño), pero le estoy diciendo a fuse que el archivo a leer tiene un tamaño de igual valor al tamaño de la cadena que quiero mostrar (15 bytes) asique por ahi no va la mano. Alguna idea?

**Comment by mgarciaisaia** [comment]
@juanoubi6 ¿pudiste revisar algo de esto el sábado? ¿Avanzaste algo desde el último mensaje?

Contanos en qué andás, a ver si queda algo pendiente para ver.

**Comment by juanoubi6** [comment]
Sigo igual (como en el primer post que hice). Ya probamos varias cosas pero sigue igual

**Comment by mgarciaisaia** [comment]
Esto huele a que hay problemas de memoria. Pegale una corrida con [`valgrind`](http://faq.utn.so/valgrind) a tus procesos.

En el código que pusiste al principio, tu primer línea suena rara: `respuesta->buffer[respuesta->tamano]='\0';`. No estoy viendo todo tu código, pero si `buffer` es de tamaño `tamano` (cosa que parece sensata), hacer `buffer[tamano]` es un error - si tenés `tamano` posiciones en tu array, estas van desde el índice `0` hasta el `tamano-1`.

Fijate, también, estar haciendo el `return` de read correctamente en tu cliente.

Seguí buscando a ver qué pasa. No tenemos mucha más info para ver :/

Si seguís sin encontrarlo, pasate un [sábado de soporte](http://faq.utn.so/soporte), a ver en qué te pueden ayudar.

Metele, metele.

**Comment by juanoubi6** [comment]
Cambie un poco mi codigo, ahora lo que tengo es 
memcpy(buffer,respuesta->buffer+offset,size);
Le saque lo de /0, pero sigo con el mismo problema (el primer cat no hace nada, los siguientes leen solo una partecita de mi buffer a pesar de que debugueando yo veo el buffer con mas cosas)

**Comment by fedebonisconti** [comment]
En el `respuesta->buffer`, estás mandando el archivo entero? O lo que te solicitaron? 

Si el servidor está mandando lo que le solicitaron, estaría mal sumarle el offset (te estarías moviendo dentro de lo que te solicitaron, y podría ser que por casualidad no te dé segmentation fault).

**Comment by juanoubi6** [comment]
El servidor está mandando el archivo entero

**Comment by tferraro** [comment]
Buenas!

Creo que dado hemos atacado el problema por varios lados, creo que va a ser conveniente que lo veas fisicamente con algún ayudante. Te pasaste el sábado para ver este tema? Si no yo voy a andar por campus este sábado durante la mañana.

**Comment by juanoubi6** [comment]
Ya encontre la solucion. El problema que teniamos era que, al realizar el getattr del archivo, llenabamos el campo stbuf->st_size con un tamaño que no coincidia con el tamaño real del archivo (error en el envio de mensajes). Entonces, aunque le pusieramos al buffer de fuse una cadena de 50 caracteres, si el stbuf->st_size le pusimos un valor de 10 solo se iban a mostar 10 por pantalla.
