### ISSUE TITLE
Deadlock...Backtracking?

### ISSUE THREAD

**Issue by sebawars** [sisoputnfrba/foro#511]
Buenas, basicamente esa es mi duda.
En principio lo que hago es, en base a las matrices, separar en una lista a los entrenadores que cumplen estas condiciones:
-Tienen una petición que no se puede satisfacer con los recursos disponibles de esa pokenest.
-Tienen algún recurso asignado.
Luego debería chequear la espera circular para separar un deadlock pero acá surge un tema: en esta lista tengo los que están en deadlock e inanición entonces no me basta con tomar uno (el pivote) e ir recorriendo según quién tiene la petición del pivote, porque ese recurso lo puede tener algún entrenador que no tenga nada que ver con el deadlock que estoy buscando, lo cual me llevaría a descartar ese "camino" y probar los otros... y si no me equivoco se asemeja a backtracking (quizás me equivoco de concepto, pero creo que se entiende a lo que voy).
Gracias

**Comment by mgarciaisaia** [comment]
Seba, el amigo Stallings, en su libro mágico, expuso su _algoritmo de detección de deadlock_, que es el que pedimos que implementen. Acá un extracto de la 7ma versión de su libro en inglés:

![detecciondeadlock](https://cloud.githubusercontent.com/assets/1190974/19282501/05ff5748-8fc5-11e6-895e-3356ac124e78.png)

No tenemos nada en contra de crear sus propios algoritmos - de hecho, hemos visto lindos inventos a lo largo de los cuatrimestres -, pero saber reusar conceptos es una de las grandes herramientas con las que contamos los candidatos a ingenieros.

Lo que planteás tiene sentido. En lugar de hacer backtracking, un primer approach podría ser hacer _fuerza bruta_: cuando llegás a un caso como el que nombrás (en que el Entrenador que está bloqueando al recurso de tu pivote está en inanición, y no en deadlock) asumís que por ese camino no hay un deadlock, y buscás otro. Si ese pivote efectivamente estaba en deadlock, _eventualmente_ vas a pasar por otro Entrenador que se relacione con este y sí esté en deadlock; si no, es porque no estaba en deadlock.

¿Tiene sentido lo que digo?

**Comment by sebawars** [comment]
La primera parte en la que obtengo los que no pueden ejecutar ya está. A ver si decimos lo mismo con respecto a quiénes están en espera circular a partir de los obtenidos anteriormente: para saber si realmente un entrenador está en espera circular debería tomar a Roma y fijarme si alguno de los caminos (todos los que tienen ese recurso que pide Roma) conduce a Roma... lo cual terminaría siendo, por ejemplo, for de for de for... cierto?
