### ISSUE TITLE
Problema al ejecutar comando rm -rf

### ISSUE THREAD

**Issue by GuidoOliveri** [sisoputnfrba/foro#512]
Hola, cómo andan? Escribo porque tuve un problema bastante jodido, estaba probando unas cosas de Entrenador de Muerte cuando tengo que borrar todos los archivos del Dir de Bill, era tarde, no me di cuenta y ejecuté esto: 
`rm workspace/pokedex/Entrenadores/Red/Dir\ de\ Bill/ -rf *`

Después me di cuenta que eso borra recursivamente todas las carpetas y todo lo que tiene adentro. Yo adentro del workspace tenia el tp, lo que quiero saber es si hay alguna manera de recuperarlo, estuve investigando un montón, corrí lo que se llama el testdisk para poder recuperar las cosas, lo empecé a correr pero me di cuenta que no recuperaba carpetas y que era un lio darse cuenta dónde estaba el tp.
Mucha gente dice que es casi imposible, porque si bien no vacía las celdas, nada más las marca como libres, y tendría que saber qué celdas exactamente estaba ocupando. Lo que borré sigue escrito en el disco, pero está preparado para ser sobreescrito en cuanto se necesite, por lo que tengo entendido.

Hay alguna manera de recuperar la carpeta con el tp, algo que sepan? Porque sino perdería avances que había hecho y no había pusheado.

Desde ya muchas gracias!

**Comment by mgarciaisaia** [comment]
Antes que nada, hacé YA un snapshot de la VM. Hay algún video sobre eso en mi YouTube (no se si está linkeado en el blog).

Con eso vas a poder hacer varios intentos, pudiendo volver atrás cada tanto, por si en alguno de los intentos pisaste la data que estás queriendo recuperar.

**Comment by GuidoOliveri** [comment]
El video está, es este https://www.youtube.com/watch?v=UBGFe0231vU, ya lo había visto hace bastante y tenia un SnapShot tal cual lo haces vos en el video que se llama Base Recien Instalada, el tema es que lo corrí para ver qué pasaba, pero igual adentro del workspace no aparece el tp de este cuatrimestre, aparece el tp de otro cuatrimestre mío y otra carpeta más, lo que por lo menos aparece es el eclipse, cosa que tampoco la tenía después de que me pasó lo de  rm. 
 Me cree un SnapShot apenas me dijiste del estado de ahora, la corrí, y ni aparece la carpeta Workspace, tal como quedó cuando se borró con rm, hay alguna otra alternativa? 

Gracias!

**Comment by mgarciaisaia** [comment]
¿Restauraste ese snapshot Base Recien Instalada, entonces?

Si ese fue el caso, y no guardaste un nuevo snapshot al hacer eso (VirtualBox suele ofrecertelo), buen, sí - perdiste todo al carajo :/

Los snapshots son eso - versiones de tu VM. Cuando restaurás un snapshot viejo descartando el estado actual, perdés todos los cambios que hiciste a la VM desde que hiciste ese snapshot.

Una vez más, el estado más reciente de tu VM _también_ estuvo guardado como archivos en tu disco de tu PC física, por lo que podrías intentar usar herramientas de recuperación para ver si conseguís des-eliminar esos archivos. Pero tendrías que buscar recuperar el estado de la VM, para restaurarlo e intentar recuperar los archivos de tu workspace... Difícil.

Si el testdisk te recupera archivos, podés tratar de usar algo como `grep` para identificar qué archivo recuperado corresponde a cada archivo del TP, pero la verdad es que, sí, va a ser un bardo. Probablemente te sea más fácil re-hacer el laburo (y, de paso, testeás cuánto aprendiste en el camino) que meterte en este quilombo :/

Y, de acá en adelante, tener presente desarrollar de a pasos más autocontenidos, para ir commiteando más seguido el laburo :/

¡Un abrazo, che!

**Comment by GuidoOliveri** [comment]
Mati! Guardé el nuevo snapshot, entré a la VM con este nuevo snapshot, busqué en /home/utnso a ver si estaba la carpeta workspace , pero no estaba. Asi que bueno, si no está en otro lugar que vea ahora en un rato, ya me pongo directamente a trabajar en el snapshot de la Base Recien Instalada, donde tengo el eclipse y todo.
