### ISSUE TITLE
Batalla

### ISSUE THREAD

**Issue by aailenm** [sisoputnfrba/foro#513]
Hola! 
En caso de que haya mas de dos entrenadores en deadlock, y este configurado para que se resuelva por batalla, pelean todos con todos o solo pelean los que están en deadlock entre sí? 
Otra cosa más, hay que detectar espera circular o con detectar entre dos alcanza? 

Saludos!

**Comment by marcogatti** [comment]
Buenas! 

Justo hoy surgió esa pregunta en clase. Primero que nada, solo pelean aquellos entrenadores que esten involucrados en el deadlock, aquellos que estén en inhanicion o no participen de una forma obviamente no van a pelear. 

Dicho esto, el algoritmo de peleas solo soporta dos entrenadores. Lo que podes hacer, es que peleen dos entrenadores al azar, el perdedor pelea con el siguiente (que también podes elegir al azar), y así hasta que hayan peleado todos los entrenadores de ese deadlock. El entrenador que pierde en la última pelea puede ser la víctima del algoritmo. 

Avisa cualquier cosa. 

Saludos!

**Comment by aailenm** [comment]
Buenisimo! 
Para detectar el deadlock alcanza con que sea uno a uno ( A quiere lo de B y B quiere lo de A) o también tengo debería detectar espera circular??

**Comment by marcogatti** [comment]
Ailen,

Acordate que uno de los requisitos para que haya deadlock es justamente el que mencionas, la espera circular. Una posibilidad es en el ejemplo simple que ponias, A quiere algo que ya tiene B asignado y al reves. Ese caso es un deadlock y podes tratarlo como tal.

No entiendo bien a que te referis con
> o también tengo debería detectar espera circular??
Me darias algun ejemplo?

Saludos!

**Comment by aailenm** [comment]
Claro, me expresé mal, perdón!  
Pasa que nosotros ahora estamos verificando si A tiene algo que quiere B y B tiene algo que quiere A, osea ese caso particular de espera circular. 
Pero si A espera algo que tiene B, y B algo de C, y C algo de A, ya no lo detectamos. Me confundí pensando que eran dos casos distintos, mala mía! jaja 
Gracias!!
