### ISSUE TITLE
Problema con el repo

### ISSUE THREAD

**Issue by MMarussi** [sisoputnfrba/foro#514]
Buenas, como va?

Básicamente nuestro problema consiste en que algunos commits desaparecieron del repo. Estos no estan en el historial del repo y tampoco están reflejados en el código del TP. 
Probamos haciendo un commit nuevo y, por suerte, aparecieron algunos commits anteriores, pero todavía faltan algunos.

![commits1](https://cloud.githubusercontent.com/assets/11763032/19331859/8919bfbc-90bd-11e6-8ad8-8ab86b17ba6d.PNG)

![commits2](https://cloud.githubusercontent.com/assets/11763032/19331862/90721930-90bd-11e6-9dea-6e1a5eb297b1.PNG)

Como muestran las imágenes, parecería que hay 2 commits el 7 de octubre en el repo pero cuando queremos verlos, sólo figura uno. 

No sabemos cual es la causa del problema pero tenemos un par de ideas:

- Uno de los chicos empezó a tener problemas con los commits desde que Git reconoció mi usuario ( hasta el momento todos los commits que yo había hecho, si bien figuraban con mi nombre de usuario, no estaban linkeados a mi usuario realmente o sea, no aparecía en la pestaña colaboradores aunque había hecho los commits)

- Varios días después de que empezaron a desaparecer los commits hice un merge: Puede ser que esto haya englobado los commits perdidos?

![git merge](https://cloud.githubusercontent.com/assets/11763032/19330787/de15fe9c-90b6-11e6-8f7e-f6df08e435d2.PNG)

- Además les consultamos si es probable que la **branch Head** tenga algo que ver con nuestro problema?

![git head](https://cloud.githubusercontent.com/assets/11763032/19331100/f39cf1f6-90b8-11e6-82d9-cf9b342c6834.PNG)

![git head 2](https://cloud.githubusercontent.com/assets/11763032/19331121/28798ee8-90b9-11e6-8186-51c13e40856d.PNG)

Desde ya muchas gracias!

**Comment by iago64** [comment]
@MMarussi Si no recuerdo mal este tema lo resolvieron con ayuda de @mgarciaisaia el sabado no? Pueden comentarnos que entendieron de la explicación de mati y como evitar que vuelva a pasar este problema?

**Comment by GuidoOliveri** [comment]
Hola! Sí, es verdad, el problema habia sido que un integrante del grupo habia pusheado con `git push --force` (o algo parecido a este comando), entonces al hacer esto, git te pregunta si de verás querés pushear aunque no te trajiste los cambios primero que hizo otro. 
**Solución:** En estos casos, hay que mergear si o si, pero no hacer git push --force, porque se pisan los cambios que habia hecho otro, un poco de los que nos contó Mati estaba especificamente en esta diapositiva de la presentación de Git: https://docs.google.com/presentation/d/1IdRtJLY7mUiHG0zdnVNS-FkVjl50wFISIwZTQVGFkdQ/edit#slide=id.gddefb698_766

El commit amarillo sería el que yo subí al repo, el commit verde es el que tiene la otra persona que va a pushear en ese momento, para obtener el violeta hay que mergear, y ahi todo saldría bien.

Mil gracias por ayudarnos el sabado con esto!
