### ISSUE TITLE
Consulta checkpoint del sabado

### ISSUE THREAD

**Issue by varas-c** [sisoputnfrba/foro#515]
No se si éste es el lugar indicado para esta pregunta, si no es así, disculpen.

El checkpoint del sabado, donde podemos mostrar nuestro TP "funcionando", tiene que ser **necesariamente en una VM Server?** o se puede mostrar igualmente en la maquina con interfaz gráfica?

Pregunto porque anduve viendo la VM Server y por lo que vi no tiene nada instalado (creo que ni las commons). Asi que si quisieramos probar nuestro tp tendriamos que instalar todo eso y ademas hacer los makefile para poder "instalar" nuestro tp.

Si me pueden guiar, les agradezco. Seguro a alguien más le sirve este issue

**Comment by mgarciaisaia** [comment]
¡Aloha!

Un poco la idea del checkpoint es que descubran esto _ahora_, y no la noche anterior a la entrega :)

La idea es que _los grupos que estén en condiciones_, muestren en la Server del labo - exactamente el mismo ambiente en que vamos a hacer la entrega final. Pero, los que no, todo bien - pueden mostrar en sus compus o en la VM Desktop (aunque no garantizamos que la VM Desktop esté instalada en el labo).

Vale la pregunta 👍

¡Un abrazo!

**Comment by varas-c** [comment]
Gracias! Cierro el issue
