### ISSUE TITLE
problemas para debaguear

### ISSUE THREAD

**Issue by guillermo126** [sisoputnfrba/foro#516]
buenas como estan? tengo una problema... cuando me siento a programar y quiero debaguear mi proyecto por ejemplo mapa resulta que los sockets no se conectan... pero la cuestion es q las modificacion que hice no involucran para nada los sockets y anteriormente conectaba todo lo mas bien desde la consola... cuando debagueo creo q me tira un error de que falta el archivo fuente o algo asi no lo puedo ver bien xq aparace solo un segundo... me gustaria saber si alguno le paso ¿como hizo para resolverlo o que debo hacer? bueno gracias

**Comment by varas-c** [comment]
Si te da un error con los sockets, apagar la maquina virtual y prenderla otra vez suele funcionar. Ojo, apagarla posta, no "guardando el estado". A mi me pasó un par de veces que tuve error en los sockets pero despues de que se me haya colgado el mapa varias veces o cosas raras, despues de tocar un monton digamos. Apagar y prender siempre funciona jaja

**Comment by guillermo126** [comment]
dale voy a probar eso gracias

**Comment by mgarciaisaia** [comment]
¡Aloha!

Por lo que decís, parece que te estabas encontrando con esta ventana:

<img width="530" alt="screen shot 2016-10-17 at 6 19 44 pm" src="https://cloud.githubusercontent.com/assets/1190974/19456110/5f09e7ce-9496-11e6-8a26-628af87ce49b.png">

El mensaje de error dice algo así:

```
Can't find a source file at "/build/buildd/eglibc-2.19/stdio-common/printf.c" 
Locate the file or edit the source lookup path to include its location.
```

El archivo nombrado podría ser otro, no importa.

Ese error es un error de vista de Eclipse - lo que dice ahí es que Eclipse quiere mostrarte el código fuente de una función, pero no lo encuentra. Pero eso no es un error de tu programa, digamos.

Lo que sí suele pasar es que un error de tu programa haga que Eclipse quiera mostrarte el código fuente de funciones que no tenés. ¿Y cómo es esto? Cuando tu programa, por ejemplo, referencia una posición de memoria inválida, el sistema operativo le envía la señal `SIGSEGV` a tu proceso. Mientras estás debuggeando, el debugger por defecto frena la ejecución de tu proceso cada vez que este último recibe una señal, con el objetivo de que puedas debuggear la recepción de la señal - sobretodo si es un error, como en este caso. Lo que ocurre frecuentemente es que la referencia inválida no la hace directamente tu código, si no una función de una biblioteca que es llamada por tu programa - por ejemplo, tu programa hace `printf("%s\n", NULL);`, y entonces la referencia inválida no la hace tu código, si no la función `printf`.

Ahí es cuando Eclipse intenta mostrarte el código fuente de `printf`, pero, como no lo encuentra, te muestra ese error.

Para detectar si el caso es este, se puede mirar la vista de Debug de Eclipse:

<img width="714" alt="screen shot 2016-10-17 at 6 38 50 pm" src="https://cloud.githubusercontent.com/assets/1190974/19456705/0967d76a-9499-11e6-81d2-cdd813d7f1cf.png">

Ahí se ve, en la tercer línea, que el Thread 1 del proceso está en estado `SUSPENDED` por una `Signal` que llegó. Desde ahí mismo vas a poder clickear las lineas de abajo para navegar el stack de tu proceso hasta llegar a código realmente tuyo, en el que vas a poder mirar el estado de tus variables y tu proceso en general para entender por qué falló tu programa.
