### ISSUE TITLE
Duda con el uso del bitMap

### ISSUE THREAD

**Issue by salva-olacua** [sisoputnfrba/foro#517]
Buenas estoy tratando de obtener el bitMap pero no tengo en claro si es un puntero de int , un char* o  del tipo t_bitarray .
si fuera solo un char* o puntero de enteros podria acceder al contenido mas facil.
si es t_bitarray ya no entiendo como acceder a las posiciones que tienen 1s o 0s dependiendo de si el bloque esta ocupado o no.
Me fije que t_bitarray es una estructura que adentro contiene un char * bitarray , solo si quiero acceder al valor algun bit por ejemplo el del bit 5 tendria que hacer t_bitarray estructura
estrcutura->bitarray[5].
seria algo asi ??? o la estoy manqueando en algo.
espero puedan iluminarme.
saludos.

**Comment by mgarciaisaia** [comment]
El Bitmap de un disco OSADA es un array de bits que indica si el bloque de disco que comparte índice está libre u ocupado.

`t_bitarray` es un tipo de estructura que opera un array de bytes (un `char *`) entendiéndolo como un array de bits. Para eso, la función que inicializa un `t_bitarray` recibe un puntero al primer byte de memoria de ese array de bytes (es decir, el `t_bitarray` **no reserva** la memoria en que guarda los bits, si no que espera que el usuario se encargue de reservarla).

Como todo buen TAD, la mejor manera de usar el `t_bitarray` no es accediendo directamente a sus campos (lo que proponés de `estructura->bitarray[5]`), si no usando [las funciones asociadas a él](https://github.com/sisoputnfrba/so-commons-library/blob/58eb41ee9b43b4e2540b96bfcbfc13ea2491d826/src/commons/bitarray.h#L70-L92). Podés mirar ejemplos de cómo usar el bitarray revisando [sus tests en las commons](https://github.com/sisoputnfrba/so-commons-library/blob/58eb41ee9b43b4e2540b96bfcbfc13ea2491d826/tests/unit-tests/test_bitarray.c).

Con esas funciones vas a poder pedir fácilmente el bit en la posición X de tu bitarray.

**Comment by tferraro** [comment]
@salva-olacua como andamos con esto? Te sirvió la respuesta de Mati? Si es que si, plz cerrá el issue :wink:

**Comment by salva-olacua** [comment]
Estuve dándole pelea a eso y me sirvió mucho ese consejo , muchas gracias .
Cierro el issue.
