### ISSUE TITLE
Conexion de dos VM entre si

### ISSUE THREAD

**Issue by varas-c** [sisoputnfrba/foro#518]
Hola!

Estoy tratando de conectar dos maquinas virtuales entre sí. En una maquina virtual estoy corriendo un ubuntu server y en otra estoy corriendo Lubuntu (el cliente digamos).
El problema es que no se bien como conectar dos maquinas virtuales entre si, en el server ejecuto un mapa y desde lubuntu ejecuto un cliente, pero el cliente nunca logra conectarse.

Probé varias configuraciones de red desde VirtualBox (NAT y Red interna con modo promiscuo permitir todo) y no lo logro. Cuando uso NAT en las dos maquinas virtuales, las dos tienen la misma IP cuando hago ifconfig desde la consola. Cuando uso red interna con modo promiscuo permitir todo, no encuentro la ip cuando hago ifconfig asi que no se cual sería la IP de mi maquina.

El problema que noté es que Windows (mi maquina real) no me creó ningun adaptador de red de Virtual Box, estoy casi seguro que cada VM tiene un VirtualBox Host-Only Ethernet Adapter (o algo asi) cuando entras a los adaptadores de red de Windows, pero en mi caso solo tengo esto

![untitled](https://cloud.githubusercontent.com/assets/18077589/19371370/b998cd10-9188-11e6-85e1-5a71fc3a1f07.png)

Al intentar crear una red desde VirtualBox, me tira el siguiente error

![untitled](https://cloud.githubusercontent.com/assets/18077589/19371387/da5234c4-9188-11e6-83a0-4cb589db753a.png)

Estuve toda la tarde revisando y no puedo hacerlo funcionar. Voy a tratar de reinstalar virtualbox, pero si alguno tiene idea y me da una mano, le agradecería mucho :D :octocat:

**Comment by juanisierra** [comment]
Buenas!
Intenta reinstalando virtualbox. Por lo que se ve te falta el adaptador de
red de virtualbox y por eso no te deja crear la red.
Saludos

**Comment by varas-c** [comment]
Era ese mi problema, borre virtualbox, instalé todo desde 0 y me apareció el adaptador de red. Ya las pude conectar. 

Gracias!
