### ISSUE TITLE
Tiempos en proceso Entrenador

### ISSUE THREAD

**Issue by fpatalagoity** [sisoputnfrba/foro#520]
Buenas, tenemos una consulta respecto de esto:

> Una vez cumplidos los objetivos del último Mapa de su Hoja de Viaje, el Entrenador se habrá convertido en un Maestro Pokémon. El proceso Entrenador informará el logro por pantalla, indicando el Tiempo Total que le tomó toda la aventura, cuánto tiempo pasó bloqueado en las PokeNests, en cuántos Deadlocks estuvo involucrado, y cuántas veces Murió durante la hazaña (ver apartado siguiente).

¿Hay que calcular el Tiempo Total de la aventura y el tiempo que pasó bloqueado en magnitudes reales? Me refiero a, por ejemplo: Tiempo Total de la aventura: 3 minutos 40 segundos y (hagamos de cuenta que tiene 2 pokenests): Pokenest X: 20 segundos y Pokenest Y: 40 segundos.

Saludos!

**Comment by mgarciaisaia** [comment]
Efectivamente.

La única aclaración sería que no es en absoluto necesario mostrar los tiempos de cada PokeNest por separado (aunque no está mal si lo hacen), y, en cualquier caso, muestren el tiempo acumulado entre todas las PokeNests.

No es algo que cambie mucho la dinámica del sistema, pero sí está bueno que puedan poner en números tangibles la diferencia que hace o no un algoritmo u otro en diferentes escenarios. Como para bajar un poco más a tierra las comparaciones medio genéricas que se hacen en la teoría al ver los distintos algoritmos, ¿vio?

**Comment by fpatalagoity** [comment]
Excelente, sin caer en spoiling (aunque voy a caer igual jajaja), existe según investigamos una función clock()... estamos mínimamente bien encaminados? Gracias!

**Comment by mgarciaisaia** [comment]
Naaaa, tranca.

`clock`, función que desconocía hasta hace diez minutos, te da el tiempo de CPU que usó el proceso que la llama. Es decir, te dice cuánto tiempo pasó tu proceso en estado EXEC.

Lo que nosotros pedimos es cuánto tiempo pasó tu Entrenador en cada estado de la Planificación de esta simulación, que no es lo mismo.

La forma más fácil de calcularlo es haciendo `time()` o algo así para conseguir la hora del sistema en cada cambio de estado que hacen, y acumulando la diferencia entre cada vez que entran al estado y que salen.

No hay magia de programación, acá. El objetivo es tener esos números, para ver cómo se comporta la planificación - nada más.

**Comment by fpatalagoity** [comment]
Perfecto! Mil gracias!

**Comment by fpatalagoity** [comment]
Vuelvo a abrir el issue porque con mi grupo nos encontramos en una disyuntiva.
Supongamos que un entrenador se bloquea en una pokenest B por X cantidad de segundos, luego muere por deadlock y reinicia sus objetivos porque tiene vidas disponibles. Vuelve a pasar por la pokenest B y esta vez logra capturar al pokemon en R segundos (R sería el tiempo que estuvo bloqueado desde que llegó hasta que lo obtuvo).
¿Cuánto debería valer el tiempo total bloqueado para ese entrenador en la pokenest B en ese mapa? ¿R o R+X?
Porque en nuestro caso estaríamos tomando el último valor, que para el ejemplo es R, dado que al morir reinicia sus objetivos y con ellos, el contador de tiempo para todas las pokenest.

Saludos!

**Comment by jcorvalan93** [comment]
Tendría mas sentido R+X. Porque, además, te pide el tiempo de bloqueo a nivel mapa, no a nivel pokenest (o por lo menos yo lo pensé de esa forma).

Con respecto a que estén tomando el último valor y pierden el anterior porque tienen que reiniciar todo, tomando como referencia a lo que comentó @mgarciaisaia - si no es necesario tener discriminado los tiempos por cada pokenest - entonces una solución a esto sería tener estos tiempo separado de los datos que tengas de los objetivos.

**Comment by fpatalagoity** [comment]
Muchas gracias!!
