### ISSUE TITLE
archivo que necesita mas bloques de fat que los disponibles

### ISSUE THREAD

**Issue by maxmerutn** [sisoputnfrba/foro#521]
hola en el caso de que se necesiten mas bloques de los disponibles como en el special.mp4 se guardaria en un solo bloque con el flag FFFFFFFF?, ya que el archivo entra por su tamaño
, o no se puede guardar el archivo?

saludos
muchas gracias

**Comment by mgarciaisaia** [comment]
¡Aloha!

De no tener espacio disponible para seguir grabando el archivo, deberías dar un error `ENOSPC`, que es el que indica que no hay más espacio disponible en el dispositivo.

Mirando [`man 2 write`](https://linux.die.net/man/2/write) especifica como error:

> ### ENOSPC
> The device containing the file referred to by _fd_ has no room for the data.

Aunque [`truncate`](https://linux.die.net/man/2/truncate) no lo nombra :/

**Comment by maxmerutn** [comment]
ok, saludos
