### ISSUE TITLE
Objetos perdidos

### ISSUE THREAD

**Issue by mgarciaisaia** [sisoputnfrba/foro#522]
Si alguien siente que desde el sábado le está lloviendo más que de costumbre, puede que hayan olvidado un paraguas en el laboratorio durante el Checkpoint del sábado.

Me escriben por privado para ver cómo se los hago llegar.

¡Un abrazo!

**Comment by tferraro** [comment]
Up a esto. Apareció el dueño del paraguas?

**Comment by dromero-7854** [comment]
Me parece que soy yo... Quedenselo jaja

**Comment by mgarciaisaia** [comment]
@dromero-7854 si hoy pasás por Medrano, vení a buscar tu paraguas. Juraría que lo escuché sollozar por las noches de lo que te extraña.

**Comment by mgarciaisaia** [comment]
@sisoputnfrba/bash-ketchum tengo en mi poder un pendrive pequeño marca SanDisk con un script de instalación que clona el repo de su grupo. _Espero_ que el mismo pertenezca a alguno de ustedes.

@dromero-7854 sigo teniendo tu ☂️. No uso ☂️. Copate y vení la próxima entrega a recuperar tu ☂️. Dale.

**Comment by chrisgel15** [comment]
@mgarciaisaia Es mio el pendrive! Lo volvi a buscar el sabado pero no lo encontre. Te aviso para el dia de la proxima entrega, gracias!

**Comment by dromero-7854** [comment]
la última fecha de entrega voy a recuperar mi :open_umbrella: y a aprobar el tp :-P jeje

Saludos!

**Comment by chrisgel15** [comment]
@mgarciaisaia Me llevas el pen este sabado? Gracias!

**Comment by mgarciaisaia** [comment]
@chrisgel15:

![37647469](https://cloud.githubusercontent.com/assets/1190974/21271120/635329c2-c398-11e6-999e-96cc7546ee0d.jpg)


@dromero-7854 ☂️☂️☂️
