### ISSUE TITLE
Nombre de CarpetaPokenest y Pokemon.dat

### ISSUE THREAD

**Issue by fedeGiussa25** [sisoputnfrba/foro#523]
Hola!
Con mi grupo encontramos el siguiente problema en las rutas de la Pokenest y los archivos metadata de los pokemones de esa Pokenest

Los ejemplos que aparecen en el tp son estos:
/Mapas/Ciudad Paleta/PokeNests/Pikachu/Pikachu001.dat
/Mapas/Ciudad Paleta/PokeNests/Pikachu/Pikachu002.dat
/Mapas/Ciudad Paleta/PokeNests/Bulbasaur/Bulbasaur001.dat
 
El problema está en que el FileSystem no permite archivos con un nombre mayor a 17 caracteres
Por lo que si queremos crear la carpeta CHARMANDER con charmanderXXX.dat, el filesystem nos tira error porque justamente el nombre ''charmanderXXX.dat", no entra en el filesystem.

Asi que nuestra duda es: 
el nombre de la carpeta tiene que coincidir con el nombre de los archivos que tiene adentro?
O sea una carpeta "charmander" se supone que adentro tiene "charmanderXXX.dat" ? o puede haber una carpeta que se llame "charmander" y adentro tener "charmXXX.dat" (no coincide el nombre de la carpeta con sus archivos).

Esto es mas que nada porque los charmander no nos entraron en el filesystem y ademas tenemos funciones que siguen la regla de "el nombre de la carpeta coincide con el de sus archivos", asi que no sabemos si cambiar estas funciones o no.

Gracias

**Comment by mgarciaisaia** [comment]
Si el FS no permite archivos mayores a 17 caracteres, entonces el tamaño máximo de nombre de un Pokémon sólo podrá ser de 17 - 7 (`XXX.dat`) = 10 caracteres.

Ahora bien, `charmander` _tiene_ 10 caracteres. `charmander001.dat` tiene exactamente 17 caracteres - el tamaño de nombre máximo que soporta OSADA - por lo que deberías poder guardarlo sin problemas.

Lo que OSADA nunca dice es que el nombre del archivo sea un _string_. Probablemente por ese lado estén complicándose.

**Comment by Matias-Rivas** [comment]
Supongo que con 
> Lo que OSADA nunca dice es que el nombre del archivo sea un string.

te referís a que no va a haber un '\0' que indique fin de cadena. Pero considerando esto, ¿cómo haríamos para guardar un nombre de archivo de longitud menor que 17 bytes? Tendríamos que tener un centinela, y eso lo convertiría en un string.
Por otro lado, para el caso extremo de un nombre de exactamente 17 bytes, tendríamos que tener la precaución de agregarle un '\0' cada vez que lo manipulemos, por ejemplo para verificar que un archivo a crear no exista aún en el directorio, lo cual sería muy engorroso. Además, si el server envía los nombres sin centinela, el cliente debería hacerse cargo de agregárselo al final. ¿Tiene sentido?

**Comment by mgarciaisaia** [comment]
Bueno, cambiemos el wording: _no es necesario_ que sea un string.

Podés guardar el `\0` en todos los casos _salvo_ en el caso en que tengas un nombre de 17 caracteres.

Cuando el nombre mide menos, compro - de algún modo tenés que saber dónde termina el nombre, y usar el `\0` parece natural y sencillo. Pero si sabés que tu tamaño máximo de nombre es 17 bytes, y ves un nombre que no tiene ningún `\0`, ¿no es natural asumir que los 17 caracteres son _significativos_?

El `\0` al final de un string es una convención de C - no es un estándar de la informática. No se cuántos conocen Pascal, por ejemplo, pero ahí los strings se almacenan distinto - el primer byte es un entero que dice cuántos bytes mide el string. Entonces lo del `\0` tampoco es algo para comprar siempre.

Si no, tienen una tabla con un campo de 17 bytes de los que sólo pueden aprovecharse 16 como máximo. No suena muy astuto, ¿no?

**Comment by varas-c** [comment]
Ya lo solucionamos, ya podemos guardar archivos de hasta 17 caracteres en el nombre siguiendo tu recomendación.

Gracias! Cierro issue
