### ISSUE TITLE
Consulta sobre valor especial 

### ISSUE THREAD

**Issue by bolbasor** [sisoputnfrba/foro#524]
Buenas tardes en la tabla de archivos la posicion del directorio raiz se indica con un valor especial? Perdon si la pregunta es muy corta saludos

**Comment by mgarciaisaia** [comment]
¡Aloha!

No existe una entrada específica para el directorio raíz, ya que este no tiene nombre - la ruta para accederlo es el punto de montaje, y entonces no hay nada más para guardar en la tabla sobre este directorio.

¿Se entiende?

**Comment by bolbasor** [comment]
hola!ahora entiendo todo gracias
