### ISSUE TITLE
Segmentation fault, lista de colas 

### ISSUE THREAD

**Issue by Nicobile** [sisoputnfrba/foro#525]
Buenas! Llego el  finde y se que están con ganas de pasarselo programando, aprovechando eso, les traigo una duda que me esta comiendo la cabeza:

```
t_queue *colaAccion = queue_create();
entrenador* ent1 = malloc(sizeof(entrenador));
ent1 =  queue_pop(colaListos);
colaAccion =  list_get(listaDeColasAccion, ent1->numeroLlegada);
acto =queue_pop(colaAccion);
```

Debuggeando me encontre con que al llegar a  colaAction =  list_get(listaDeColasAccion, ent1->numeroLlegada); me tira segmenatiton fault, realmente no tengo idea del motivo, sigo buscando pero un ayudin no me vendria mal.

Muchas gracias!

PD: la colaListos esta inicializada mas arriba y la lisaDeColasAccion tambien, sera imposible hacer una lista de colas?

**Comment by mgarciaisaia** [comment]
¡Aloha!

Volvamos a las bases de C: el `=` es el operador de asignación. Es decir, cuando hago `unaCosa = otraCosa`, estoy haciendo que en la variable `unaCosa` se guarde el valor al que resuelva `otraCosa`. Si `otraCosa` es también una variable, entonces hago que `unaCosa` tenga el mismo valor que `otraCosa`. Pero si `otraCosa` es una expresión (es decir, algo más de la pinta de `otraCosa()` o `otraCosa + terceraCosa`, o andá a saber), se evalúa `otraCosa`, y el resultado de eso se asigna en `unaCosa`.

¿A qué voy con todo esto? A que cuando hacés `ent1 = malloc( ... )` estás asignando el valor de `ent1`, pero al hacer `ent1 = queue_pop( ... )` estás _volviendo a asignar_ `ent1`. Esto hace que, por un lado, _pierdas la memoria_ reservada por ese `malloc( ... )` (porque ya no tenemos ningún puntero a ese bloque de memoria, entonces no podemos referenciarlo); y, por otro, que `ent1` tenga o no un valor dependiendo del resultado de `queue_pop( ... )`.

Para despejar las dudas, sería interesante ver cuándo cae tu segmentation fault - si justo en la línea del `list_get( ... )`, o si más adentro (es decir, durante la _ejecución_ del `list_get`), que no es lo mismo. Mi conjetura es que ese `queue_pop` devuelve `NULL` (o algún puntero mocho por algún otro error en el código de ustedes), y entonces al intentar hacer `ent1->numeroLlegada` rompe queriendo acceder a lo apuntado por `ent1` (porque, como técnicamente mencioné, el puntero está _mocho_). Distinto sería si efectivamente logra acceder al campo `numeroLlegada`, y lo que rompe es _dentro_ de `list_get` (porque la lista no tiene tantos elementos, o porque la lista es inválida, o andá a saber qué).

Pero apostaría un botón y 3 chelines a que `ent1` apunta a cualquier lado. Usté dirá.

¡Un abrazo!

**Comment by Nicobile** [comment]
Efectivamente, el queue_pop estaba devolviendo NULL porque no había nada en esa cola, sincronización a marzo.

Muchas gracias!!! Cierro el issue
