### ISSUE TITLE
Comunicado a mapa de fin entrenador

### ISSUE THREAD

**Issue by FBerco** [sisoputnfrba/foro#527]
Buenas tardes,
Leyendo el enunciado desde gitbook, me di cuenta que en mapa ya no esta el comunicado del entrenador diciendo fin a su ejecución en el mapa. En base a eso tengo unas preguntas:
1) Antes le daba la dirección a la medalla cuando completaba el mapa, ahora en que momento se la doy? o no se la doy?
2) Como debería encarar el procedimiento para darme cuenta que el entrenador se fue del mapa tanto como por algún tipo de error o porque se fue a otro mapa?

Desde ya muchas gracias,
Saludos.

**Comment by varas-c** [comment]
La forma que lo hicimos con mi grupo fue la siguiente:

La direccion de la medalla la puede calcular el entrenador sin problemas. Los datos que necesitas son
1- Ruta Pokedex
2-Nombre del Mapa

La forma de la cadena para la medalla es la siguiente: RutaPokedex-Mapas-NombreMapa-ArchivoDeLaMedalla
Si tu ruta es /mnt/pokedex y tu mapa es "PuebloPaleta", la ruta te queda

/mnt/pokedex/Mapas/PuebloPaleta/medalla-PuebloPaleta

"Mapas" y "medalla" va hardcodeado, los demas, son datos que ya tenes. Cuando tu entrenador se de cuenta que terminó el nivel, solo formá la cadena necesaria para llegar a la medalla y copiala.

Espero que te sirva!

**Comment by GuidoOliveri** [comment]
Y con respecto a esto:

> 2) Como debería encarar el procedimiento para darme cuenta que el entrenador se fue del mapa tanto como por algún tipo de error o porque se fue a otro mapa?

Si el Entrenador termina por una situación anómala como dice el enunciado, sea Ctrl+c, kill o que se te apague la máquina, el Mapa es el que se va a tener que dar cuenta de que vos te desconectaste, y ahi ya no te tendría que planificar más. Y si llegas a morir por un tema del envio de alguna señal, ahi sí le vas a tener que avisar al Mapa que te mataron con las signal, para que el Mapa se entere. 

Espero ayudarte, un abrazo!
