### ISSUE TITLE
Mañana miercoles hay algun ayudante por campus

### ISSUE THREAD

**Issue by guillermo126** [sisoputnfrba/foro#528]
buenas! perdon por preguntar esto a ultimo pero ¿hay algun ayudante mañana miercoles por campus? necesito ver unas cosas con el tema de la resolucion del deadlock que no me estan saliendo y estoy trabado es consulta sobre mi codigo mas que nada, me parece q no tiene sentido que lo pregunte por aca. en fin, gracias

**Comment by afilgueira** [comment]
Buenas, date una vuelta por la 235 de Campus, despues de las 18:30, y vemos como te podemos ayudar.

Saludos!

**Comment by guillermo126** [comment]
joya gracias! a las 18:30 estoy ahi, saludos!
