### ISSUE TITLE
Nombre de medallas demasiado largo

### ISSUE THREAD

**Issue by varas-c** [sisoputnfrba/foro#529]
Estamos probando el file system integrado con el mapa y los entrenadores, específicamente en la parte del copiado de las medallas,y nos dimos cuenta de que el criterio de los nombres, que es 
`medalla-[nombre].jpg`
puede no coincidir con el límite de 17 caracteres para los nombres de archivos. Por ejemplo, el mapa 'CiudadAzafran' tiene 13 caracteres, por lo tanto 'medalla-CiudadAzafran.jpg' tiene 25 caracteres.

Para confirmar esto, en la parte del tp que explica el formato de las medallas, dice que una ruta posible es
`**Ejemplo de Ruta: /Mapas/Ciudad Paleta/medalla-Ciudad Paleta.jpg`
lo que tampoco entra en el file system OSADA.

Deberíamos cambiar el criterio, o adaptar los nombres de los mapas para que los nombres de las medallas entren en los 17 bytes.

**Comment by tferraro** [comment]
Buenas!

Adaptá el nombre. 

Una cosa es la especificación del filesystem en el que vas a trabajar y otra son los ejemplos que están puestos en el enunciado. 
Para poder describir los procesos de Mapa y Entrenador no se fue específico en que la configuración vaya bien con OSADA, porque hubiera confundido mucho si tuviera nombres cortos y capás se hubiera perdido la idea a trasmitir. 

Saludos!

Tom
