### ISSUE TITLE
Dudas/problemas con write en fuse

### ISSUE THREAD

**Issue by juanoubi6** [sisoputnfrba/foro#530]
Buenas, ando con unos problemas en la implementacion del read y el write en fuse. Paso a detallar:

1)Fuse no me esta detectando la funcion WRITE cuando quiero escribir un archivo ya creado, pero si me la toma cuando quiero crear un archivo nuevo para escribirlo. Por ejemplo, si tengo un directorio vacio y pongo los siguientes comandos en la terminal

cat > outfile.txt <<EOF
some text
to save
EOF

El archivo se me crea correctamente y fuse me capta la funcion write (y escribe). El problema es cuando quiero volver a escribir este archivo con el mismo codigo ya que fuse no me detecta la funcion (me tira FUNCION NO IMPLEMENTADA).

2)Cuando voy a escribir el archivo, lo que le llega a mi funcion write en el buffer es "pepe\n" que son 6 caracteres. Sin embargo, en el SIZE de fuse me esta llegando un 5. Esto me pasa siempre, es como que el size siempre es 1 menos que los caracteres que realmente tiene el buffer. El problema es que si o si la funcion tiene que devolver el mismo tamaño que haya en size o me tira un error de "fuse: wrote too many bytes" y en la terminal me aparece "cat: error de escritura: Dirección incorrecta". Yo podria decirle al servidor que en vez de escribir size, siempre escriba size+1, el problema es que no coincidira el tamaño de lo que estoy escribiendo en el servidor con lo que le devuelvo al fuse. Hay algun problema con esto?

A todo esto, no estoy pudiendo debugear el cliente de fuse por consola con -d.Parece que el cliente se queda constantemente tratando de leer el directorio /. Sin embargo, cuando lo corro con -f anda perfectamente.

![asdas](https://cloud.githubusercontent.com/assets/17948943/19745799/b8d7603c-9ba9-11e6-90b1-032d695d0782.png)

Muchas gracias !

**Comment by KevinTemes** [comment]
Chusmeate este link, que lo compartió @mgarciaisaia tiempo atrás: [https://enunacalesita.wordpress.com/2012/05/27/solucionando-fuse-function-not-implemented-en-write/](url). Básicamente, necesitás implementar la función .truncate, aunque no haga nada, para que write funcione correctamente.

**Comment by juanoubi6** [comment]
Muchas gracias, era esto que comentabas.
