### ISSUE TITLE
Problemas con el envio por socket y para levantar un disco

### ISSUE THREAD

**Issue by leofs94** [sisoputnfrba/foro#531]
Buenas:

Tengo dos problemas para poder seguir testeando mis procesos:

1) Problemas con las serializaciones: 
Lo que pasa basicamente es esto, yo por socket puedo mandar tanto cadenas como enteros como cualquier otro tipo, sin problema llega del otro lado y lo imprime correctamente, el problema se da cuando mando una estructura serializada, para ser exactos esta:
typedef struct{
    char\* rutaArchivo;
    char\* bufferAEscribir;
    int offset;
    int cantidadDeBytes;
}**attribute**((packed))
t_MensajeEscribirArchivoPokedexClient_PokedexServer;
el otro proceso recibe el paquete del otro lado pero cuando llega y lo de-serializa e imprimo o miro los campos en el debug me tira basura o nombres de mis propias funciones que no tienen nada que ver con lo que tendria que traer. Por ejemplo, en el debugger me mostraba algo como <mapearArchivo ´+115> y alguna basura mas, siendo mapearArchivo el nombre de otra funcion que hice, esto se da unicamente en los campos que son char\* de esta estructura, en el caso de los enteros los recibe bien.

ACLARACION: No pasa lo msimo si lo serializo y de-serializo en el mismo proceso, lo imprime y llena los campos a la perfeccion.

2) Cuando yo levanto un disco de los de prueba subidos por ustedes ya sea mapeandolo entero o por partes en la estructura que cree para que lo delimite campo por campo del fs, me mapea el header y el bitmap a la perfeccion, y despues no mapearia nada en el resto de las estructuras, la pregunta es: dentro del disco deberia estar la tabla de archivos, la de asignaciones, y obviamente los bloques de datos tambien? 

Desde ya muchas gracias.

**Comment by alkchofa** [comment]
Buenas, 
1) Estoy casi seguro que lo q sucede es lo siguiente: char* es un puntero a un string por lo que si vos mandas la estructura cargada en, digamos, una maquina A los char* apuntan a memoria de la maquina A, osea que el string esta en alguna parte de la maquina A, por lo que si vos le mandas esa info a una maquina B, la direccion a la que apunta es a una parte de la maquina B, en la cual no sabes que hay en esa parte de la memoria.

2) Si, dentro del disco estan todas las estructuras y los bloques de datos. 
Con respecto a los problemas en "mapeo", que estas usando, mmap o fopen ?
Como estas leyendo el contenido, memcpy o strcpy ?

**Comment by tferraro** [comment]
Buenas! @leofs94 como andamos con eso? La respuesta de Maxi te sirvió? Si es así, cerrá el issue porfis :policeman:

**Comment by leofs94** [comment]
Si gracias
