### ISSUE TITLE
Consulta string_split

### ISSUE THREAD

**Issue by riverosm** [sisoputnfrba/foro#532]
Buen día, estoy intentando hacer un split del path para poder encontrar el pathPadre:

`char** paths = string_split(path, "/");`

El problema es que si el path no tiene al menos dos "/" (por ejemplo path = "/Pokemons") me da violación de segmento.

¿Estoy haciendo algo mal?

Muchas gracias, saludos.

**Comment by jazcarate** [comment]
Buenas,
El `segmentation fault` te lo dá el `string_split`? o el codigo que está un poquito más adelante?

Si te fijas en la [especificación](https://github.com/sisoputnfrba/so-commons-library/blob/master/tests/unit-tests/test_string.c#L201) de `string_split`, si el string no tiene el valor que buscas (en tu caso `/`), lo que te devuelve es una lista con un elemento nulo; pero cabe la posibilidad de que hayas encontrado un error D:

**Comment by riverosm** [comment]
Buenas, gracias por la respuesta.

`int main(int argc, char** argv)
{
	char** paths = string_split("/", "/");
	int i = 0;
	while (paths[i] != NULL) {
		printf("%s \n", paths[i]);
		i++;
	}
	return 0;
}`

Y da violación de segmento. Estuve haciendo algunas pruebas y sólo falla con el path "/" así que directamente no invoco a la función.

Gracias!! Saludos

**Comment by tferraro** [comment]
Holis. Lo que estás experimentando es un bug [que ya tenemos reportado por aqui](https://github.com/sisoputnfrba/so-commons-library/issues/57) por lo que parece. :stuck_out_tongue:

**Comment by riverosm** [comment]
Gracias Tomás! Voy a comparar el string antes de invocar a la función.
Cierro el issue, saludos!

**Comment by mgarciaisaia** [comment]
Podés coparte y hacer un pull request a las commons, también 😝

Si lo hacés esta semana podés [ganarte una remera](https://hacktoberfest.digitalocean.com/) y todo.

**Comment by RaniAgus** [comment]
@mgarciaisaia parece que llegué un poco tarde para la remera :laughing: (?
https://github.com/sisoputnfrba/so-commons-library/pull/119

**Comment by mgarciaisaia** [comment]
@RaniAgus Metele que se viene la revancha: https://hacktoberfest.digitalocean.com

**Comment by RaniAgus** [comment]
@mgarciaisaia cómo es? Si hago 4 pull requests me puedo ganar una remera? 

Challenge accepted

**Comment by mgarciaisaia** [comment]
Ajam. Las primeras 70.000 personas que metan 4 pull requests no-spam a repos públicos en Github durante octubre se ganan una remera. Vos, o algun@ emplead@ de Aduana que frene el despacho.

**Comment by RaniAgus** [comment]
Yo próximamente en la Aduana: [Dónde está mi remera?!](https://static.vix.com/es/sites/default/files/styles/4x3/public/btg/donde-esta-mi-hamburguesa-15-gifs-de-homero-disfrutando-el-placer-de-comer-1.png)

Anyway, espero que sean útiles

**Comment by mgarciaisaia** [comment]
> Anyway, espero que sean útiles

¿L@s de la aduana? Llevá una sillita 😇

-----

Gracias por los PRs, ¡che! :)
