### ISSUE TITLE
Borrado directorio OSADA

### ISSUE THREAD

**Issue by riverosm** [sisoputnfrba/foro#533]
Buenas tardes, quería confirmar si al borrar un directorio por ejemplo:

`rm -R /mnt/pokedex/Pokemons`

Se debe además de poner en estado DELETED al directorio, eliminar todos sus archivos recursivamente, es decir, poner cada uno en estado DELETED y sus bitmaps asociados en 0.

¿O sólo se podrá eliminar un directorio si se encuentra vacío?

Muchas gracias, saludos.

**Comment by mgarciaisaia** [comment]
Tocayo, ¿probaste implementar las funciones dummy y ver qué hace FUSE?

Capaz encuentres la respuesta por ahí.

**Comment by riverosm** [comment]
Mati buenas, si ejecuto un rm normal no me deja eliminarlo por ser un directorio:

> rm: no se puede borrar «/mnt/cliente1/Pokemons/»: Es un directorio

Si lo ejecuto con el recursivo rm -R, y bien al estilo UNIX, no pregunta ni se fija si está vacío, empieza a eliminar todo su contenido invocando al unlink para cada archivo del directorio:

> unique: 280, opcode: UNLINK (10), nodeid: 2, insize: 48, pid: 30216
> unlink /Pokemons/125.txt
> unique: 280, error: -2 (No such file or directory), outsize: 16

Por eso me gustaría confirmar si nuestra implementación tiene que eliminar recursivamente liberando los bloques, o tenemos que previamente vaciar el directorio.

Gracias!!

**Comment by mgarciaisaia** [comment]
¡Bien! Ahora un poco más largo.

En [`man rm`](https://linux.die.net/man/1/rm) podemos ver que:
> rm removes each specified file. By default, it does not remove directories.

Más abajo dice que hay una opción:
> -r, -R, --recursive
>     remove directories and their contents recursively

No es capricho de `rm` no borrar directorios por default. La syscall para borrar archivos es [`unlink`](https://linux.die.net/man/3/unlink):
> The `unlink()` function shall remove a link to a file.
> [...]
> The `path` argument shall not name a directory unless the process has appropriate privileges and the implementation supports using `unlink()` on directories.

Y, más importante aún, [`rmdir`](https://linux.die.net/man/2/rmdir):
> `rmdir()` deletes a directory, which must be empty.

Y esa es la clave: para el sistema operativo, borrar un archivo y borrar un directorio son **operaciones distintas**.

FUSE sigue esa lógica: existen tanto [`unlink` como `rmdir`](https://www.cs.hmc.edu/~geoff/classes/hmc.cs135.201001/homework/fuse/fuse_doc.html), y FUSE va a llamar a la que corresponda en cada caso.

Volviendo a tu comando, como vimos acá, si hacés `rm -R unDirectorioNoVacio`, `rm` va a llamar a hacer `readdir` para leer el contenido de tu directorio, y va a eliminar cada uno de esos archivos, para después terminar eliminando con `rmdir` al directorio ya vaciado. Para eliminar cada archivo contenido, va a hacer el mismo procedimiento: fijarse si es un archivo o directorio; en el primer caso, le hace `unlink`, mientras que en el caso de los directorios _vuelve a fijarse su contenido, vaciarlo, y eliminarlo_.

A eso se refiere la parte de _**recursive**_: eliminar un directorio y su contenido implica revisar si algo de lo que contiene es un directorio... que pueda tener contenido, implicando que tiene que mirar su contenido...

El cuento de la buena pipa :)

**Comment by riverosm** [comment]
Buen día Mati, muchas gracias por la respuesta!

Me quedó claro, al tener correctamente implementados tanto el ulink como el rmdir lo hace automáticamente el blanqueo del bitmap de cada archivo (y el state->DELETED).

Cierro el issue, saludos!
