### ISSUE TITLE
Creacion de directorios y subdirectorios en OSADA

### ISSUE THREAD

**Issue by CarolinaPonceRodriguez** [sisoputnfrba/foro#535]
Buenas nuevas, tengo una consulta con respecto a lo que mencione arriba. Desconozco en que momento seria necesaria la creacion de un subdirectorio, el ejemplo que se me ocurre es cuando un entrenador gana una medalla. Es necesario que el entrenador tenga en el osada su metadata por lo cual un directorio para un entrenador podria ser /Entrenadores/Entrenador Ash.
La consulta seria si ya dentro de Entrenador Ash cuento con el directorio para las medallas(por dar un ejemplo) y cuando el entrenador gane alguna, solo queda agregarla o si por el hecho de no poseer medallas inicialmente, no exista dicho directorio por lo cual solamente se cree si el entrenador gane alguna

Saludos!

**Comment by riverosm** [comment]
Carolina buenas, dado que no te contestaron te comento lo que yo interpreté con este punto y es que se puedan crear directorios y subdirectorios en OSADA desde cualquier lado (una terminal, un navegador de archivos) sin importar si hay Mapas o Entrenadores conectados. Inclusive la parte de Mapa y Entrenador en ningún momento deben crear directorios, como bien decís.

Espero te sirva, saludos!

**Comment by mgarciaisaia** [comment]
Eso.

Su FS es, ante todo, un FS.

_Que además_ se use para jugar Pokemon, es "una casualidad". Pero primero es un FS, hecho y derecho.
