### ISSUE TITLE
Disco osada para el TP

### ISSUE THREAD

**Issue by riverosm** [sisoputnfrba/foro#538]
Buenas tardes, quería saber si en estos días tienen pensado subir algún disco para que podamos integrar con el TP, que contenga los Mapas y entrenadores con sus metadata, etc.

Muchas gracias desde ya, saludos.

**Comment by tferraro** [comment]
Buenas,

Probablemente más cerca de la fecha de Entrega estemos liberando algún documento de pruebas tentativas.

De todas maneras, las pruebas pueden ser alteradas completamente en el momento de la entrega, así que no esperen a que aparezca el documento de pruebas para hacer las suyas.

Saludos

**Comment by riverosm** [comment]
Buenas Tomas, gracias por la respuesta! Entiendo que las pruebas pueden ser alteradas, era más que nada para saber si podíamos probar todo integrado antes de la primer entrega.

Cierro el issue, saludos!
