### ISSUE TITLE
problemas con RW semaforos

### ISSUE THREAD

**Issue by fecheromero** [sisoputnfrba/foro#539]
consulta porque estoy a nada del panic atack:
Googleando por ahí encontré la existencia de los pthread_rwlock . Y decidimos usarlos para el manejo de la concurrencia del pokedex Server. Técnicamente estos semáforos existen para solucionar justamente casos de concurrencia en sistemas de escritura-lectura. El problema es que la ejecución del proceso **se esta bloqueando al unlockear el semáforo**... Cosa que me resulta rara xq hasta donde se la función de unlock de cualquier semáforo (y no encontré nada que diga lo contrario sobre este) no es bloqueante. Los lockeos funcionan perfectamente.
¿Alguien me puede dar una mano con eso ?.
PD: se que la documentación dice que la utilización de estos semáforos tiene resultados inesperados si se intentan hacer varios lockeos en un mismo hilo sin liberar el anterior ya que el unlock es único y unlockea el tipo de bloqueo que hiciste ultimo en el hilo.  Pero no es el caso... así que ya no se que puede estar pasando.

**Comment by FrankIglesias** [comment]
No te esta faltando un un unlock en algún lado? o tenes un unlock adentro de un if y el lock afuera? Debuggealo y fijate si realmente se detiene en el unlock.

**Comment by fecheromero** [comment]
Solucionado. Era un problema de memoria. Estaba inicializando el semáforo en un espacio no reservado entonces flasheaba cualquier cosa
