### ISSUE TITLE
Dudas con funciones FS

### ISSUE THREAD

**Issue by fpatalagoity** [sisoputnfrba/foro#540]
Buenas tardes, tengo que codear "release" y "fallocate" pero no entiendo lo que hacen...
¿Podrán guiarme?

Saludos!

**Comment by mgarciaisaia** [comment]
En [`fuse_operations`](http://libfuse.github.io/doxygen/structfuse__operations.html) dice que `release` tiene que liberar las estructuras que hayan reservado durante los `open` (algo así como un "free", digamos). FUSE garantiza que te va a llamar una única vez a `release()` (cuando se le haga el último `close()`).

[`fallocate`](http://libfuse.github.io/doxygen/structfuse__operations.html#a4fa8203e4bfa71d62c15deb5dffe4867) _ Allocates space for an open file_. Es decir, el kernel te va a pedir que reserves espacio (en el medio de almacenamiento - aka, el disco) para ese archivo - probablemente porque espera escribirte cosas ahí. Esto va relacionado con que, _en el vacío_, hacer `truncate` de un archivo no necesariamente le tiene que asignar el espacio en disco - podés hacerle `truncate` y no reservar espacio en disco hasta que no se graben bytes reales.

En el TP no necesitan implementar `fallocate` (porque `truncate` **tiene** que asignar los bloques), y `release` es más para "uso interno" que otra cosa - si hay estructuras que crean en memoria al hacer `open()` por primera vez que necesitan liberar _recién en el último_ `close()`, esta es la operación que andan buscando. Else, tampoco la implementan.

¡Abrazo!

**Comment by fpatalagoity** [comment]
Buenas! Gracias por la respuesta. Me queda una duda de interpretación: ¿No es necesario implementarla porque en la evaluación no se va a usar? O ¿no es necesaria implementarla porque no tiene uso alguno en el desarrollo del TP? Espero que se entienda la distinción que quiero hacer.
Gracias!

**Comment by iago64** [comment]
@fpatalagoity Fijate que estan subidas unas pruebas [Beta del FS ](https://docs.google.com/document/d/17EC4CfpuzmYntCcyycBHtp36t8KfPHWlHlajDMvdHNY/edit) Fijate si, sin tener implementadas las funciones que preguntaste el tp funciona (si lees la respuesta de mati de nuevo capaz te des cuenta que muy posiblemente funcionen, peeero just in case, testealo)

**Comment by tferraro** [comment]
@fpatalagoity te sirvieron las respuestas de los chicos? Se puede cerrar el issue?

**Comment by tferraro** [comment]
Cierro el issue. Cualquier cosa vuelvanlo a abrir!
