### ISSUE TITLE
Más y más dudas función write (fuse)

### ISSUE THREAD

**Issue by dromero-7854** [sisoputnfrba/foro#541]
Buenos días a todos,

Les escribo para aclarar ciertas dudas con respecto a la implementación de la función WRITE en OSADA. Espero ser lo más claro posible. Voy a intentarlo.

Según la documentación de FUSE, la función write debe escribir n bytes (**size**) que se encuentran en el buffer (**buf**), empezando de la posición m (**offset**)

Hasta ahí todo claro. Pero... (siempre hay un “pero”) 
¿Cómo me doy cuenta que la escritura terminó y saber cuál es el nuevo tamaño del archivo, para agregar bloques (si el archivo aumentó su tamaño) ó liberar bloques (si el archivo disminuyó su tamaño)?

Es decir, no hay algo como un carácter fin de archivo.

A pesar de esta duda, empecé a actuar y diseñé dos posibles soluciones que quiero saber cuál sería la correcta (o si ambas están mal diseñadas y nos dedicamos a otra cosa, siempre quise ser guitarrista)

**SOLUCION A**

- **Archivo que aumenta su tamaño**: Cuando estoy efectuando la escritura, tengo manera de saber si el archivo en esa escritura está aumentando de tamaño:
 tamaño_actual_del_archivo < offset + size
En este caso, añado los bloques necesarios para la escritura, y todo el mundo feliz.

- **Archivo que disminuye su tamaño**: Y acá es donde empiezo a hacer agua. La única manera que se me ocurre para achicar un archivo es a través de la función **truncate**. Es decir, el usuario luego de haber efectuado la escritura y sabiendo cuanto a disminuido en tamaño el archivo, debe llamar a la función **truncate** para amoldar el archivo a su nuevo tamaño. Ya que no hay manera (o al menos no se me ocurre) de darme cuenta de esto durante la escritura.

**SOLUCION B** (Tiro mis fichas acá)

- **Archivo que aumenta su tamaño**: la escritura “hace lo que puede” Ejemplo, el archivo contiene 100 bytes, y el usuario desea escribir 50 caracteres a partir del byte 89. Los primeros 10 caracteres se escriben (están dentro de los límites del archivo), y el resto de los caracteres se pierden en la NADA (¡como la Historia sin Fin!)
Si el usuario desea escribir más allá del archivo, debe agrandar el archivo a través de la función **truncate**.
	
- **Archivo que disminuye su tamaño**: Ver SOLUCION A, mismo punto.

Les pido un poco de luz en este tema que todavía no decidimos como encararlo.

Saludos y gracias
Dante Romero

**Comment by KevinTemes** [comment]
Me adhiero a la consulta; aunque hasta ahora nosotros siempre partimos de la suposición de que los archivos pueden variar de tamaño; lo que nos está mareando es, justamente, cómo determinar el nuevo tamaño del archivo, una vez que se lo modificó.

**Comment by gastonprieto** [comment]
Buenas!

Pensa en el caso que abris un archivo para agregarle contenido (`fopen("miArchivo", "a")`), sirven ambas soluciones, una sola? por qué?

**Comment by dromero-7854** [comment]
Como estas Gastón,

Imagino que **fopen** en ***append mode*** no sabe cuánto va a agregar, pero cuando escriba, **el offset va a ser el tamaño del archivo**. Por lo que intuyo que solamente la SOLUCION A (en caso de que el archivo aumente de tamaño) sirve para este caso. Lo voy a probar en este momento (ya tenía implementado el write de esta manera)

Ahora bien... ¿Cómo encaro el caso de que el archivo disminuya su tamaño?

**Comment by dromero-7854** [comment]
Efectivamente. Acabo de probar y cuando realizo un append desde la consola:

***echo 'text to append' >> README.txt***

A la función write **llega como offset el tamaño actual del archivo**. Es conveniente entonces, para realizar una escritura en modo append, la SOLUCION A.

¿Alguien que me ilumine con el otro caso?

**Comment by gastonprieto** [comment]
Correcta deducción.

Sobre el otro caso, como usuario las únicas formas son con `truncate`, o como hace `nano` que borra el archivo y lo vuelve a crear. 

Entonces, a nivel filesystem, a vos solo te importa `truncate`.

**Comment by dromero-7854** [comment]
Elemental mi querido Watson!

Acabo de levantar un archivo con el leafpad de Lubuntu, y cuando achico un archivo, hace un truncate a 0 bytes del archivo, y vuelve a escribirlo completo (como bien comentabas) 

Cierro el issue y agradezco la ayuda brindada.

Saludos
Dante Romero
