### ISSUE TITLE
FUSE búsqueda de carpetas/directorios inexistentes al iniciar

### ISSUE THREAD

**Issue by KevinTemes** [sisoputnfrba/foro#543]
Buenas!

Debugeando estos dias me empezó a saltar un error en fuse que antes no tenía. Cuando levanto fuse, inicialmente me hace una solicitud de getattr sobre los siguientes archivos/directorios:
/.trash
/.trash/1000\025

Hasta ahí nada grave; toqueteando un poco el código pude esquivar el problema (por "esquivar" entiendase "hardcodié" las respuestas en esos casos, para ver qué pasaba). El problema viene después. Cuando trato de acceder a la carpeta donde está ubicado el punto de montaje, primero hace una request de .getattr del directorio "/" como siempre, e inmediatamente hace otra solicitud de getattr de dos archivos llamados /.xdg-volume-info y /autorun.inf. Independientemente de lo que responda a esas dos solicitudes, el debug de fuse siempre me tira el siguiente mensaje por terminal:

_unique 4, error: -2 (no such file or directory), outsize:16
unique 5, error: -2 (no such file or directory), outsize:16
unique 6, error: -2 (no such file or directory), outsize:16_

Después de imprimir esos mensajes, el proceso se queda en standby, como a la espera de nuevas solicitudes. Pero si voy a la carpeta donde está alojado el punto de montaje, el explorador no me reconoce dicho punto como una carpeta, y por consiguiente no puedo acceder al contenido de osada.

En lo que respecta a código, no modifiqué nada previo que haya podido causar esto; lo único que se me ocurre que pueda ser el problema es que estuve tocando los parámetros de compilación del archivo .c, porque pensé que no los tenía ubicados donde correspondía. ¿Puede que sea ese el problema?
Intente iniciar el proceso con y sin la ejecucion en modo background (o sea, con y sin -f), pero el resultado es el mismo.

Es muy probable que sea un error bastante tonto, pero si alguien tiene idea de cómo solucionarlo agradecería que me lo comente, porque me está complicando la vida para poder seguir debugeando el resto del filesystem.

Saludos!

**Comment by mgarciaisaia** [comment]
#499

**Comment by KevinTemes** [comment]
Dicho y hecho, era muy tonto el problema. Gracias mati por el issue, habia buscado alguno en el que se hubiera planteado esto y no lo había encontrado.

Cierro el issue

**Comment by mgarciaisaia** [comment]
Na, no es nada tonto - nomás faltó buscar un poco antes de preguntar 😉
