### ISSUE TITLE
Consulta makefile

### ISSUE THREAD

**Issue by riverosm** [sisoputnfrba/foro#544]
Buenas, armé los makefile a mano copiando el formato de otros que saqué de sus repositorios.

El binario se genera correctamente y aparentemente funciona todo, el tema es que el tamaño difiere bastante respecto a si lo compilo desde Eclipse (éste último es bastante más pesado)

¿Puede traer algún problema esa diferencia de tamaños? ¿Alguna sugerencia de cómo generar los makefile?

Muchas gracias, saludos.

**Comment by tferraro** [comment]
Buenas,

Cuando compilas con tu makefile, le agregaste los flags de debug?

Por defecto Eclipse compila en ese modo y deja mucha metadata para poder
debuggear el proyecto.

Saludos

**Comment by riverosm** [comment]
Hola Tomas, gracias por la respuesta.

No, solamente agregué el flag que me pidió FUSE

> gcc -D_FILE_OFFSET_BITS=64 PokeDexServer.c socket.c -lcommons -lpthread -o PokeDexServer

Vi que eclipse le agrega un montón de flags más, ¿son necesarios?

Saludos

**Comment by tferraro** [comment]
Siempre depende de que quieras hacer ;).
Por ejemplo, el flag -Wall va a hacer que el compilador te muestre todos
los warnings. No recuerdo exactamente el nombre de la sección del eclipse
donde se agregan los flags, pero alli muestran varios y su función.

Si te funciona no deberías tener problema. La diferencoa de tamaño viene
por el lado de que al compilar en modo Release, el compilador genera
multiples optimizaciones para que tu código final sea más performante,
quitando, por ejemplo, las referencias a los numeros de línea.

En un producto terminado, hay que compilar siempre en modo Release, pero
tener en cuenta para el desarrollo, que sin los simbolos de debug, valgrind
no funca ;).

Saludos!

**Comment by riverosm** [comment]
Quedó clarísimo, muchas gracias por la respuesta!

Cierro el issue
