### ISSUE TITLE
Entrenador sin pokemon

### ISSUE THREAD

**Issue by maxmerutn** [sisoputnfrba/foro#545]
Podria ocurrir que al momento del deadlock haya un entrenador que no tenga pokemon para elegir? que pasaria en este caso?

muchas gracias

se nos ocurre tener un pokemon basico sin atrapar ninguno...

**Comment by mgarciaisaia** [comment]
Maxi, ¿cuál es el escenario mínimo de deadlock que podría ocurrir?

**Comment by maxmerutn** [comment]
es verdad, es cuando un entrenador tiene un pokemon que otro necesita, y el segundo entrenador tiene un pokemon que el primero necesita.

disculpas jaja

muchas gracias
