### ISSUE TITLE
Soporte presencial 12-11-2016 por PuTTY

### ISSUE THREAD

**Issue by fpatalagoity** [sisoputnfrba/foro#546]
Buenas, hablando con algunos compañeros de la materia me recomendaron que aprendiera a utilizar ese programa antes de que hagamos la presentación a la instancia de evaluación. La pregunta van en función de si es necesario acercarme presencialmente a los labos para que me expliquen su uso. En caso afirmativo, ¿va a haber alguien en Medrano? ¿en qué horario? Caso negativo, ¿qué debería aprender a hacer que se pueda googlear?

Saludos!

**Comment by tferraro** [comment]
Buenas, en el documento de pruebas se va a dar una breve introducción a que exactamente tenés que hacer con PuTTY, pero mientras tanto: [seguro debe haber algún loco que algo sabe de PuTTY](https://mediatemple.net/community/products/dv/204404604/using-ssh-in-putty-) :wink: 

Saludos,

Tom

**Comment by fpatalagoity** [comment]
Saludos! Gracias!
