### ISSUE TITLE
Tabla de Archivos: 1024 o 2048?

### ISSUE THREAD

**Issue by chrisgel15** [sisoputnfrba/foro#548]
Estimados, 

No se en que momento me hice la idea de que la tabla de archivos tenia un tamaño fijo de 1024 posiciones (para grabar 1024 archivos/directorios). Laburé desde el comienzo asi y tengo implementadas casi todas las funciones y he podido resolver el challenge y blabla.
Ahora, viendo las pruebas me doy cuenta que se pide poder crear 2048 archivos, y yendo a la especificacion de Osada, tambien dice que se pueden crear 2048 archivos (si esto fue asi desde el principio, mala mia), o quizas comenzó siendo 1024 y luego paso a 2048, ya que en la misma especificacion, aparece en imagenes y en las cuentas del header, el famoso 1024 (no se si deberian ser tambien 2048 esos valores).
En conclusion, cuando cambie mi #define de "tamaño de tabla de archivos" de 1024 a 2048, deje de poder ver el contenido de los archivos correctamente, la estructura del FS la tengo bien. 
Preguntas:
- El tamaño de la tabla de archivos es fijo?
- Cual es el tamaño?
- Las cuentas y las imagenes del enunciado son correctas?
- El disco del challenge está con el formato correcto?

Muchas gracias!
Christian

**Comment by mgarciaisaia** [comment]
¡Aloha!

Juraría que jamás cambiamos este valor. Pero, no tenés que creeme (mi memoria apesta) - mejor mirate [la de de erratas](http://faq.utn.so/errata).

Tu confusión probablemente venga de mezclar unidades. Los 1024 de la tabla de archivos son _bloques_. Es decir, la tabla de archivos pesa **siempre siempre** 1024 bloques.

Como la estructura que define a un archivo (el `osada_file`) convenientemente pesa 32 bytes (_medio bloque_), una tabla de archivos de 1024 bloques indica un máximo de 2048 archivos.

Entiendo que los datos que están en todos esos artifacts que nombrás (gráficos, disco de prueba, etc) están correctos - o al menos no estoy al tanto de errores. Si encontrás, este es un buen medio para comunicarlos, así los corregimos.

¡Un abrazo!

**Comment by chrisgel15** [comment]
Perfecto, aclarado!

Lo cierro!
