### ISSUE TITLE
Dudas respecto a la performance del FS

### ISSUE THREAD

**Issue by Matias-Rivas** [sisoputnfrba/foro#549]
Buenas, vengo a plantear un tema que hace muuucho me dijeron que plantee:

Mi File System funciona, y con "funciona" me refiero a que hace las operaciones que debe hacer con los resultados esperados, con un pequeño detalle: para algunas, tarda demasiado; por ejemplo, con los tests de creación que se subieron el viernes (algunas de las cuales ya había hecho antes de que las suban, o sea que no es un problema en ellas).
Estas son las pruebas que hice, varias veces cada una para verificar los resultados, con un server y tanto uno como tres clientes en la misma máquina (en diferentes puntos de montaje, pero todos conectándose a 127.0.0.1) como piden los tests:

- Crear (y también sobreescribir) los 2048 archivos lleva en promedio aprox. 7 minutos y medio. Para esto, FUSE realiza 4 operaciones: GETATTR, CREATE, GETATTR de nuevo, y WRITE.
- Borrarlos lleva aprox. 4 minutos, con FUSE invocando a GETATTR y luego a UNLINK (o DELETE).
- Crear un archivo de 10 MiB (el tamaño de mi FS de prueba) aprox. 6 minutos (creándolo y borrándolo al detectar falta de espacio, aunque esto es algo que podría corregir). Acá FUSE sólo llama a GETATTR y luego a WRITE, que se queda un rato trabajando, para luego llamar a UNLINK (y vuelta a esperar sentado).

Quería saber si estos tiempos se consideran normales. Yo estimo que, dentro de todo, sí, teniendo en cuenta que FUSE realiza varias operaciones por cada una, y que toda transferencia de datos es por sockets, que según tengo entendido son relativamente lentos.

Gracias de antemano y perdón por la demora.

Pd.: por lo que pude ver, me parece que el test de nombre largo no crea el archivo en la ruta de montaje que se pasa por parámetro, sino que lo crea en el mismo directorio donde están los tests.

**Comment by iago64** [comment]
Matias, que tal?

Respecto a los tiempos, no hay problema, somos conscientes de que cada grupo pudo (99,9% seguros) lo implementó de una forma diferente al FS, por lo cual no hay inconvenientes con respecto a los tiempos que demoren las pruebas de FS. Ademas como bien dijiste, ~~FUSE~~ El FS de linux, checkean muchas veces muchas cosas, asique de nuevo y quiero remarcarlo, no te preocupes por los tiempos.

Respecto al test del nombre largo ahora lo revisamos, gracias por avisar.

Saludos.-
