### ISSUE TITLE
Mapa recibe "Terminado Killed"

### ISSUE THREAD

**Issue by varas-c** [sisoputnfrba/foro#550]
Buenas.

Estoy testeando varios mapas levantados, haciendo deadlocks, etc etc. El problema que estoy teniendo es el siguiente:

- Probando en mi Desktop (mucha ram, mucho cpu), los mapas funcionan correctamente aunque a veces pasa lo que pasa probando en la netbook (abajo lo explico)

- Pero probando en una netbook (poca ram, poco cpu), si tengo una serie de mapas levantados, despues de un tiempo el primer mapa aborta sin ningun tipo de mensaje (no dice violacion de segmento, core generado, nada nada, sale "sin decir nada"). 
Si lo corro con valgrind, el programa recibe un "Terminado Killed". 
Leyendo lei que un "terminado killed" significa que el SO me mato el programa por ¿exceso de recursos?

Estuve revisando cual podría ser el problema y probe lo siguiente:

1-Revisar el log de valgrind: no dice ningun error de que el proceso fue terminado por una señal, solo tengo un par de "memory leaks":

------
```
==2974== HEAP SUMMARY:
==2974==     in use at exit: 185,479 bytes in 5,411 blocks
==2974==   total heap usage: 7,667 allocs, 2,256 frees, 541,633 bytes allocated

 LEAK SUMMARY:
==2974==    definitely lost: 29,129 bytes in 928 blocks
==2974==    indirectly lost: 77,056 bytes in 3,866 blocks
==2974==      possibly lost: 272 bytes in 2 blocks
==2974==    still reachable: 79,022 bytes in 615 blocks
==2974==         suppressed: 0 bytes in 0 blocks
==2974== Reachable blocks (those to which a pointer was found) are not shown.
==2974== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==2974== For counts of detected and suppressed errors, rerun with: -v
==2974== ERROR SUMMARY: 17 errors from 17 contexts (suppressed: 0 from 0)
```

--------------

2-Debuguear: Si lo debugueo el problema NO pasa nunca (típico del buen debugger), o al menos no me ocurrió las veces que probe

3-Revisar el tiempo de chequeo de deadlock: ¿Que tan bajo puede ser? Si es muy bajo, puede generar problemas? Es decir, un hilo que esta corriendo basicamente en un while infinito sin sleep. No se si esto genera error

4- Que sucede si un mapa loggea excesivamente en un archivo de texto? El hilo deadlock nuestro era una maquina de escribir por log, por lo que saque todo el loggeo, pero sigue pasando.

5- Capaz me equivoqué de carrera (? 

La memoria asignada en las maquinas virtuales (si no me equvioco) es 1gb para cada una.

Si me pueden dar una mano, les re agradezco. 

Gracias!

**Comment by sciciliani** [comment]
Todo indica que estás leakeando memoria. Al correrla en tu maquina con
mucha anda bien, cuando la corrés en la que no tiene tanta el sistema
operativo decide matar el proceso.

Correlo tu programa y en otra terminal corré el comando htop, ahi vas a
poder ver los recursos que consumen los procesos corriendo. Seguramente el
proceso mapa empieza a crecer en consumo de RAM y nunca baja.

**Comment by varas-c** [comment]
@sciciliani gracias por la respuesta. Me olvide de aclarar eso, estuve probandolo con htop y viendo el uso de recursos y nunca vi subir las barritas de memoria hasta un limite muy alto (las columnas no las entendí muy bien, pero el gráfico de barritas nunca subio mas de 500 megas, teniendo 1001mb). 

Estuve viendo cual otra podría ser la razón: Puede ser que el hilo deadlock, al tener un sleep de 1 segundo, ejecute muy rapido generando que el SO me lo mate? Tampoco vi que el CPU suba mucho, no mas que el 20% o 30%.

**Comment by mgarciaisaia** [comment]
Si probás mil cosas y no podés reproducir el problema de ningún otro modo que ejecutándolo directamente, probá el [debug postmortem](http://faq.utn.so/postmortem).

Pero mi primer consejo es que revises todo el log de `valgrind`, no sea cosa que justo justo hayas tenido un error de doble `free()` o algo por el estilo, que `valgrind` detecta pero disimula para continuar la ejecución de tu programa.

Descarto _de lleno_ las opciones 3, 4 y 5, desde ya. _Después de leer_ el reporte completo de `valgrind`, subilo a un gist.github.com, si seguís sin encontrar nada, así le pegamos una segunda mirada.

¿Lo revisó el resto de tu grupo? ¿A ellos les pasa lo mismo?

Cuando decís que "despues de un tiempo", ¿cuánto es ese tiempo? ¿Es más o menos siempre el mismo tiempo? Si metés más clientes, ¿falla más rápido? Si metés menos clientes, ¿falla más lento? ¿Sigue fallando? Si levantás menos mapas, o más mapas, ¿se comporta igual?

¿Siempre falla el primero que levantaste? ¿Y si los Entrenadores no pasan por ese mapa?

Busque, busque :)

**Comment by varas-c** [comment]
Hola @mgarciaisaia gracias por la respuesta.

Te aclaro que todo esto lo estoy haciendo desde la netbook que tiene menos hardware que la Desktop (en teoria las dos tienen 1gb de ram asignado a la vm).

Intenté generar el core con ulimit -c unlimited en la carpeta del ejecutable y despues ejecutando el mapa (sin valgrind). Tiré un par de entrenadores (estoy probando con 8), el programa rompe pero no me genera ningun core. Como dije mas arriba, el mapa no tira ningun error de "violacion de segmento" ni nada, solo "se va". Como si lo cerrara con Control C. Se va sin decir nada. Como no me manda un mensaje de violacion de segmento, no se si genera el core que debería

Probe generar el core usando valgrind para ejecutar el mapa, y recibo un "Terminado (killed)", como el de la foto pero, sigo sin obtener el core

![bug](https://cloud.githubusercontent.com/assets/18077589/20278135/4e8ed5ce-aa82-11e6-8491-8f9d3161da9d.jpg)

Este es el log que valgrind genera [](https://gist.github.com/varas-c/2244c6a4d8f1f8fad669dd5133f9eff3)

Me llamo la atencion que tenga mucho memory leak (en una matriz de 32,000 aprox), pero no me indica la razón del cierre como a veces si lo indica. Igualmente siendo sincero, no entiendo al 100% el log.

El problema por lo que vi, se genera cuando en mi mapa ejecuto 8 entrenadores, de los cuales van a entrar en deadlock de a pares. A veces, en algun deadlock, cuando lo estoy resolviendo, el programa aborta. Me di cuenta de esto porque siempre que mi mapa termina, un entrenador recibe un codigo invalido de operación de pelea. El problema es que debuggeando nunca genera error, probé poner un breakpoint para ir paso por paso en las peleas y no rompe nunca (al menos, no me rompió).

Por otra parte, lo ejecute unas facil, 7 veces en la desktop y funcionó sin problemas. Incluso apague la vm, la volvi a enceder, probe todo de nuevo y funciona bien. El problema es en la netbook, cosa que me imagino que deberia andar igual en cualquier maquina.

En la netbook probe otro test que hicimos, en el cual Nunca se genera ningun deadlock, y funciona bien. Asi que mi hipotesis es que tengo algun problema en el deadlock que a veces pasa y a veces no. Capaz tuve suerte en la desktop de que justo no rompa.

Mis compañeros no pudieron probar aun el juego, por eso estoy probandolo en dos compus distintas.

Gracias por tu tiempo! La verdad no se como encontrar el error. Estoy desde la mañana testeando :(

**Comment by mgarciaisaia** [comment]
[Por acá](http://stackoverflow.com/questions/726690/who-killed-my-process-and-why#comment538546_726762) dicen que el kernel loggea en _algún lado_ por qué mató a tu proceso. [Por acá](http://stackoverflow.com/a/20672691/641451) tiran un comando que puede ayudarte a encontrar el mensaje de log. Hay un poco más de info al respecto [acá](http://unix.stackexchange.com/a/128667/49371).

Efectivamente tu log de Valgrind no reporta problemas.

Cuando decís que tu netbook tiene poca RAM, ¿cuán poca es? No debería tener _mucho_ que ver, pero hacé la prueba de ver en el administrador de tareas del SO host de tu máquina (el _probablemente_ Windows en el que instalaste VirtualBox) a ver si es que _esa máquina_ se está quedando sin memoria, y de algún modo extraño tu Linux se entera y ajusta el uso de memoria. Pero suena raro, la verdad.

**Comment by varas-c** [comment]
Mi compañera de grupo probó el mismo caso que yo en su pc y le sucede lo mismo, el mapa "Paleta" se cierra sin avisar nada cuando intenta solucionar un deadlock. 

Lo raro es que sucede cuando hay 8 entrenadores en el mapa, los cuales entran en deadlock de a par (el jugador1 con el 2, el 3 con el 4, el 5 con el 6, etc).
Si solo tiro dos entrenadores, funciona bien. Asi que descarto que sea un problema "mio", es un problema al parecer al intentar solucionar el deadlock. El log de valgrind sigue sin tirar error tanto a mi como a mi compañera y el mapa yéndose sin decir nada.

Asi que calculo que hay un error en la funcion pelearEntrenadores (creo que en valgrind sale). 

Ahora me pongo a leer los posts que me mandaste y ver si puedo descubrir algo mas con eso :)

**Comment by varas-c** [comment]
Ya lo pudimos resolver! Teniamos un problema con las peleas pokemon, habia ciertas veces en las que teniamos mal los entrenadores e intentabamos hacer un "send" en un socket que del lado cliente le hicieron un close(). Por lo que leimos, la syscall send falla cuando el socket del lado cliente fue cerrado con close(). Cuando pasaba esto, el send se "colgaba" y linux mataba mi proceso con una señal SIGPIPE. Leimos y se puede solucionar poniendo un flag a send el cual es MSG_NOSIGNAL o haciendo un handler de sigpipe que basicamente no haga nada.

Por eso no recibiamos ni segfault, ni errores en valgrind. Ya lo pudimos solucionar, muchas gracias :)
Ya lo pudimos solucionar usando el flag MSG_NOSIGNAL.

Por si a alguno le pasa algo parecido, la info la sacamos de stackoverflow

> 
> You generally want to ignore the SIGPIPE and handle the error directly in your code. This is because signal handlers in C have many restrictions on what they can do.
> 
> The most portable way to do this is to set the SIGPIPE handler to SIG_IGN. This will prevent any socket or pipe write from causing a SIGPIPE signal.
> 
> To ignore the SIGPIPE signal, use the following code:
> 
> signal(SIGPIPE, SIG_IGN);
> 
> If you're using the send() call, another option is to use the MSG_NOSIGNAL option, which will turn the SIGPIPE behavior off on a per call basis. Note that not all operating systems support the MSG_NOSIGNAL flag.
> 
> Lastly, you may also want to consider the SO_SIGNOPIPE socket flag that can be set with setsockopt() on some operating systems. This will prevent SIGPIPE from being caused by writes just to the sockets it is set on.

Fuente: http://stackoverflow.com/questions/18935446/program-received-signal-sigpipe-broken-pipe

PD: 
![d-like-to-tha-stack-overflow-for-this-degree-i-2529594](https://cloud.githubusercontent.com/assets/18077589/20346639/f419a302-abdb-11e6-994b-bf06df4343d0.png)

**Comment by mgarciaisaia** [comment]
El problema de StackOverflow en esta materia es que el tag C en SO (StackOverflow) tiene más gente haciendo aplicaciones "del mundo real" que de las que hacemos nosotros, y muchas veces las soluciones parten de que no controlás el ambiente o cosas por el estilo.

En este caso, evitando que te llegue la señal simplemente... evitás que te llegue la señal. OK, tu proceso no se cae (y eso es una Buena Cosa Que Te Puede Pasar™), _peeeeeeero_ atacaste el síntoma, y no la enfermedad: **¿por qué estás haciendo un `send()` por un socket al que ya `close()`aron?**

Seguro - un TP con procesos que mueren por SIGPIPE tiene muchas menos chances que un TP con proceso que _se hacen los opa_ cuando les llega SIGPIPE. Pero eso no significa que un TP con procesos que ignoran la SIGPIPE sea un TP correcto, o que apruebe, del mismo modo que un tipo que toma ibuprofeno para tapar su dolor de muelas pueda vivir tranquilo, o evitarse una infección padraza. La pregunta es cuándo explota la bomba, digamos :)

**Comment by varas-c** [comment]
Estuvimos viendo por qué pasaba y el problema es que habia veces que el
hilo deadlock avisaba al mapa que A y B estaban en Deadlock, pero si el
mapa tardaba en atender ese deadlock, el hilo deadlock volvia a avisar que
A y B estaban en Deadlock. Es decir, teniamos en Deadlock a A,B,A,B. Al
intentar solucionarlo, se ve que matabamos a un entrenador (que hacia
close) y despues lo volviamos a hacer pelear. Como uno ya habia hecho
close, se moria el peoceso por sigpipe.

Pasaba muy de vez en cuando, arreglamos el tema de las repeticiones y ya no
pasó. Me exprese mal y lo del sigpipe no fue una solucion para la razon de
que mi proceso se muera por este bug del deadlock.

El sigpipe lo usamos para solucionar algo similar que nos dimos cuenta
"gracias" al error de Deadlock

. Cuando un entrenador quiere capturar un pokemon, el intercambio de
mensajes es asi:

-Entrenador manda mensaje de captura.
-El mapa recibe el pedido, busca el pokemon y antes de "asignarlo" hace un
send dandole el pokemon al cliente. (Se lo manda al proceso Cliente)
-Si el send no falló, el mapa asigna ese pokemon al entrenador (Lo asigna
del Lado Server).

Nosotros utilizamos close() del lado cliente para evitar que el mapa
atienda pedidos que quedaron en el buffer de un entrenador desconectado. Es
decir, recv recibe 0 (o -1, ,no me acuerdo) en un socket que le hicieron
close(), o sea, ignora los paquetes que esten en el buffer. El problema es
que en la captura hay un "send" para indicarle que capturó y send muere por
sigpipe cuando opera sobre un socket que fue closeado. Si justo matamos al
proceso-cliente cuando esta capturando... ops, sigpipe.
Lo hicimos asi porque nos parecia malo darle un pokemon a un entrenador que
sabemos que hizo un close().

Asi que en algunos send usamos el flag MSG_NOSIGNAL para ver si el.cliente
se fue y closeò el socket. El problema es como decis vos, si puede llegar a
explotar alguna bomba en otro lado que la verdad, no lo se.

El tema de matar a los entrenadores en plena ejecucion y en cualquier
momento, es bastante cuestion de "adivinar" cuando puede morir y tratar de
atajar todos los errores posibles.
