### ISSUE TITLE
Pokemons por mapa

### ISSUE THREAD

**Issue by JPfx** [sisoputnfrba/foro#552]
Estaba viendo el documento de pruebas y no veo que especifique la cantidad y tipos de pokemons que tiene cada mapa con sus respectivas metadatas. Lo van a subir en un disco OSADA?

**Comment by varas-c** [comment]
Estoy en la misma duda

Yo lo que interpreté de la prueba 1 es que hay 1 solo recurso de cada pokenest y quieren probar un deadlock con inanicion.
Trate de poner las pokenest cosa de que dos entren en deadlock y 1 en inanición.

En la ejecucion te tiene que quedar algo asi

Red: Atrapa P, pidio B
Gary: Atrapa B, pide P
Ash: Atrapa G, pide P

Justo en este momento, tenes que tirar a Blue que deberia pasar de largo, atrapar sus cosas e irse sin detenerse por el deadlock.

En el momento en el que tu hilo deadlock detecte la situacion, Red y Gary deberian pelear. Dependiendo del nivel y el pokemon que hayas creado, va a ganar 1 de esos. En teoria despues de esto, el juego deberia seguir funcionando y puede llegar a pasar que Ash y el ganador entren en deadlock otra vez.

Eso fue lo que yo mas o menos interpreté y me cree unos archivos para que pase eso. Capaz te sirve

**Comment by JPfx** [comment]
Hola!
Gracias por responder.

Voy a hacer eso mismo entonces!

Saludos
Juan Pablo

**Comment by mgarciaisaia** [comment]
¡Aloha!

Pueden encontrar los discos de prueba en http://faq.utn.so/pruebas-charmander

¡Éxitos!
