### ISSUE TITLE
duda con la funcion dictionary_clean_and_destroy_elements();

### ISSUE THREAD

**Issue by guillermo126** [sisoputnfrba/foro#554]
buenas eestoy queriendo usar esta funcion para borrar los elementos de un diccionario entiendo que en el primer parametro va el dicionario y en el segundo el tipo de dato,  por ejemplo yo hago:
dictionary_clean_and_destroy_elements(ClienteConfig->hojaDeViaje,*valuePokemon  ); lo probe asi y no me funciona lo puse de otra maneras y nada me dice: expected expression before ‘valuePokemon’ ¿como deberia poner el segundo parametro? bueno gracias

**Comment by gastonprieto** [comment]
Buenas!

Qué es exactamente lo que queres borrar? porque esa función sirve para sacar todos los elementos y destruirlos

**Comment by mgarciaisaia** [comment]
¿Miraste [los tests del TAD](https://github.com/sisoputnfrba/so-commons-library/blob/master/tests/unit-tests/test_dictionary.c#L117-L121)?

**Comment by guillermo126** [comment]
me olvide de mirar los test pense q iba un tipo de dato y no una funcion ya me funciono gracias
