### ISSUE TITLE
Problema con FUSE read

### ISSUE THREAD

**Issue by nachosoto93** [sisoputnfrba/foro#556]
Buenas.

Estoy teniendo problemas para leer archivos grandes(mas de 10MB) en mi Cliente(FUSE)
Cuando arranco las lecturas las primeras llamadas las hace correctamente y copia el contenido apropiado en el buffer. Luego de esto hace otra llamada, se desplaza correctamente y sigue leyendo el archivo en partes, durante 4 o 5 lecturas mas. 
El tema es que a partir de la 5ta o 6ta lectura(esto varia siempre) fuse deja de cargar el buffer donde estoy copiando el contenido del archivo que estoy leyendo. 

Algo interesante en esto es que el debugger de fuse solo muestra 5 o 6 llamadas a la función read(que es parcialmente la mitad de la lectura), pero cuando debugeo mi servidor recibe todas las llamadas correspondientes para la lectura del archivo. Por lo cual interpreto que fuse se sigue ejecutando, pero el debuger no muestra información y también deja de cargarse el buffer correspondiente.

Gracias por sus respuestas. =D!

**Comment by sciciliani** [comment]
Hola @nachosoto93 

En el trabajo practico para leer un archivo hay dos procesos interactuando de la siguiente manera:

Recibir la solicitud de Fuse, empaquetarla en un mensaje, esperar la respuesta del server, desempaquetarla y responderle a Fuse.

Lo que te recomendaría es que, por descarte, trates de encontrar cual de las operaciones está generando el problema.

Yo pondría el breakpoint después de recibir la información del server y antes de copiarla al buffer de FUSE. En otras palabras trataría de asegurarme de estar recibiendo y respondiendo información válida y consistente.

Es importante también que el valor de retorno sea exactamente la cantidad de bytes que estás devolviendo. Por ejemplo si te llega un read() de 1024 bytes pero el archivo solo tiene 100, asegurate de copiar solamente 100 bytes al buffer y de hacer return de 100.

En función de este valor el sistema operativo y la aplicación deciden que hacer a continuación.

**Comment by sciciliani** [comment]
Por otro lado pensaba también que te debería dar exactamente lo mismo leer un archivo de 10MB o 10TB.

Fuse te va a pedir exactamente el "cacho" de información que necesita mediante un offset y un size. Asegurate de pedirle al server exactamente eso, que el server responda exactamente eso y devolverle a fuse, exactamente eso.

Parece mentira pero los errores más comunes al interactuar con Fuse son no responder precisamente la solicitud

**Comment by tferraro** [comment]
@nachosoto93 te sirvió la respuesta? Como venís con eso?

**Comment by nachosoto93** [comment]
@sciciliani @tferraro Gracias por la respuesta. Me sirvio para darme cuenta que el problema estaba en que los buffer empezaban a fallar y me devolvian basura a partir de la 4ta o 5ta lectura. Luego vimos que en modo debug no fallaba pero si en modo de ejecucion(Heisenbug). Entonces decidi que antes de cada llamada a recibir sleepear el programa por unos cuantos microsegundos y de esa manera funcionaba. 
Pero al momento de probar en red, el buffer volvia a llenarse con basura luego de reiteradas llamadas.
La ultima solucion fue agregar el flag MSG_WAITALL dentro del recv, y con esto empezo a funcionar genial el envio de los buffers.
Gracias por su tiempo! Saludos!

**Comment by sciciliani** [comment]
Claro, no era que el buffer se llenaba de basura sino que el paquete se separaba en partes.


Una forma es usar el MSG_WAITALL, otra es, viste que el valor de retorno del recv() es la cantidad de bytes recibidos. En otras palabras si sabés estás mandando 1000 bytes, del otro lado iterás el recv() y concatenás hasta que hayas recibido 1000 bytes.

**Comment by chrisgel15** [comment]
+10 por el MSG_WAIT_ALL, salvando vidas!
