### ISSUE TITLE
Problemas con semaforo

### ISSUE THREAD

**Issue by gustofa** [sisoputnfrba/foro#557]
Hola.
Estoy implementando semaforos en el servidor Pokedex, pero cuando llego a hacer el lock:
pthread_mutex_lock(locks[file_block_number]);
se queda ahí como si ya estuviera bloqueado y quedara a la espera de que se libere el recurso, pero eso no es asi, el semaforo está recien inicializado.
El semaforo está definido global:
pthread_mutex_t* locks[2048];
Y luego inicializado dentro del main:
	for (i=0;i<2048;i++){
		locks[i] = malloc(sizeof(pthread_mutex_t));
		pthread_mutex_init( locks[i], NULL)
        }

Probé usando los del tipo pthread_rw_lock_t pero me sucede lo mismo al hacer el lock write...

Que estoy haciendo mal?

Gracias

**Comment by varas-c** [comment]
Creo que hacer locks[file_block_number] es lo mismo que hacer *(locks+file_block_number). Si no me equivoco le estas pasando un * a la funcion y espera que le pases una direccion, no el contenido de la direccion.

pthread_mutex_lock( & (locks[file_block_number] )) creo que te lo deberia solucionar, o en todo caso pthread_mutex_lock(locks+file_block_number) creo que es mas facil.

**Comment by chrisgel15** [comment]
Agrego una consulta que tiene que ver un poco con este tema de los semaforos. Al sincronizar e implementar la exclusion mutua en el disco lo debemos hacer a nivel de archivo? Esto es, se deberia poder permitir la escritura de 2 archivos distintos simultaneamente? Porque sinceramente no se me ocurre como implementar esa exclusion.
Yo creia que la escritura iba a ser a nivel del disco (un solo proceso escribiendo en el disco), mientras que al leer, varios podrian hacerlo simultaneamente.

Gracias!

**Comment by KevinTemes** [comment]
@chrisgel15  Estoy en la misma que vos, el bloqueo para escritura la lo implementé a nivel global; cuando alguien escribe, bloqueo todo el disco contra cualquier otra petición de escritura hasta que finalice la que está en curso.
La idea que plantean acá de implementar bloqueos a nivel bloque/archivo me parece genial, pero también tenía entendido que con bloquear "todo el disco" era suficiente.

**Comment by chrisgel15** [comment]
@KevinTemes Tambien tenia entendido lo mismo si mal no recuerdo de la charla que se dio acerca de FUSE.

**Comment by gustofa** [comment]
No tenia ese dato de la charla de fuse, lo encaramos asi luego de hablarlo con nuestro profesor (Masoero) en clase. Es una tema de criterio y de que tanta concurrencia queremos, bloquear todo el disco suena un poco mucho. En el documento donde se detallan las pruebas dice en el apartado de OSADA "El criterio de sincronización elegido por el equipo responde a un análisis teórico previo y no provoca el impedimento de la simultaneidad de acceso (tanto para escritura como para lectura) a archivos distintos"

**Comment by chrisgel15** [comment]
Entiendo que es mas criterioso bloquear archivos que todo el disco, y tambien vi ese comentario en el las pruebas (por eso mismo fue que me sume a la consulta, para saber como se iba a considerar este tema).

Esperemos la respuesta de algun ayudante que nos aclare la cuestion.

**Comment by tferraro** [comment]
Buenas!

@gustofa el problema es que estás haciendo `pthread_mutex_t* locks[2048];` que es equivalente a algo como: `pthread_mutex_t** locks;`, probalo haciendo: `pthread_mutex_t locks[2048];` o `pthread_mutex_t* locks = malloc(2048 * sizeof(pthread_mutex_t));`

@chrisgel15  @KevinTemes Respecto al otro lado de la conversación (plz para la próxima hagan otro hilo, así la pregunta original no se pierde): Tiene sentido que un filesystem bloquee todo acceso al mismo solo porque alguien está escribiendo? Incluso más allá de si tiene sentido, imaginen un escenario como Windows y su NTFS(ese fs que microsoft cuando fat32 le quedó chico), tendría sentido que el NTFS bloquee todos los accesos a disco hasta que, por ejemplo, Windows termine de paginar? 

Si nos retrotraemos a la teoría y dejamos la programación por un lado, no es para nada bueno sincronizar un sistema tomando una región crítica por demás, más allá de si es poco o mucho, porque en casos como este estarías afectando las funcionalidades del sistema de forma fatal (ni siquiera la performance) y, en realidad, lo que vos tendrías que sincronizar es la región crítica nada más, que en el caso de OSADA es el archivo.

El problema que veo no es la elección de cual método usar, sino que la justificación de el porqué usarlo no es adecuada (claramente no vale el 'era más facil codearlo' en estas cirscunstancias :stuck_out_tongue: )

Espero haber iluminado algo.

Saludos,

Tom

**Comment by KevinTemes** [comment]
Genial, muchas gracias @tferraro por la aclaración! Vamos a hacer las correcciones pertinentes.

**Comment by chrisgel15** [comment]
Gracias @tferraro, en mi caso no tenia ninguna justificacion mas que estaba casi seguro de haber escuchado en la charla que para el fin del TP era suficiente con bloquear el disco. 

Saludos!

**Comment by tferraro** [comment]
@gustofa que tul? Te sirvió mi respuesta?

**Comment by gustofa** [comment]
Si, lo terminé haciendo de la segunda manera a partir del comentario de @varas-c .
Gracias.
