### ISSUE TITLE
Fuse Operations: MKNOD y OPEN vs CREATE

### ISSUE THREAD

**Issue by chrisgel15** [sisoputnfrba/foro#559]
Estimados,

En el documento de pruebas se especifica que se va a revisar la implementacion de las funciones MKNOD y OPEN, mientras que yo he implementado la funcion CREATE.

De acuerdo a la documentacion:

![image](https://cloud.githubusercontent.com/assets/11690066/20393601/3f00512e-acbb-11e6-9fa7-95c32434265d.png)

La consulta es si es correcto lo que implementé o por algun motivo debo utilizar el otro approach.

Gracias!

**Comment by sciciliani** [comment]
Si tu filesystem permite crear archivos y correr los tests, está bien.
Lo ideal es implementar create()

**Comment by chrisgel15** [comment]
Gracias!
