### ISSUE TITLE
Problema para compilar massive file creator

### ISSUE THREAD

**Issue by sora797** [sisoputnfrba/foro#560]
Hola, cuando lo compila me tira esto:
utnso@utnso40:~/massive-file-creator$ gcc -o mfc massive-file-creator.c
massive-file-creator.c:14:25: fatal error: openssl/md5.h: No existe el archivo o el directorio
 #include <openssl/md5.h>
                         ^
compilation terminated.

lo compilé por eclipse también y me da error en la misma línea.

Saludos.

**Comment by riverosm** [comment]
Buenas, tenés que instalar lo siguiente:

> openSSL: apt-get install openssl

> libSSL: apt-get install libssl-dev

Saludos,

**Comment by sora797** [comment]
gracias!! cierro el issue.
