### ISSUE TITLE
Comienza nuevamente el Mapa en el que murió al perder una vida

### ISSUE THREAD

**Issue by maxmerutn** [sisoputnfrba/foro#561]
hola buenas pregunta... esto significa que al perder una vida por sigterm el entrenador muere y comienza de vuelta? o solo cuando le quedan 0 vidas? digamos que si tiene 5 vidas seguiria con 4 vidas ejecutando sin problemas? o muere y comienza otra vez con 4 vidas?

muchas gracias

**Comment by LeandroCarbajales** [comment]
Hola! Cito al enunciado:
"Además, el Entrenador puede recibir vidas a través del envío de la señal SIGUSR1 al proceso, y puede perder vidas mediante la señal SIGTERM. En estos casos, el desempeño del Entrenador en cada uno de los Mapas no se verá afectado, exceptuando el caso en que no tuviera vidas disponibles."
Es decir, si pierde una vida por SIGTERM no afecta en su ejecución a menos que quede con 0 vidas.
Saludos!
