### ISSUE TITLE
problemas con openDir

### ISSUE THREAD

**Issue by guillermo126** [sisoputnfrba/foro#563]
buenas estoy teniendo un problema con openDir lo que yo hago cada vez que lo utilizo es hacer un openDir
readDir y closeDir , lo que ocurre es que me funciona bien pero en un detrminado momento vuelvo a llamar a la funcon donde hago lo mismo  y eclipse me dice:
Can't find a source file at "/build/buildd/eglibc-2.19/dirent/../sysdeps/posix/opendir.c" 
Locate the file or edit the source lookup path to include its location.

no etiendo lo que significa. en la varialbe del tipo DIR * me dice:
expression      Type         value
dir                     Dir *        0x8053378
__size          char[24]       Error:failed to execute MI command:-var-create-*&((dir).__size) Error message from debugger back end:no hay ningun miembro llamado __size

cual seria el problema?

**Comment by mgarciaisaia** [comment]
Guille, ¿y #516? ¿Qué pasó?

¡Un abrazo!

**Comment by guillermo126** [comment]
Claro es parecido al otro problema q plantie en ese issue. Lo q hago yo es malloquear un char* despues le hago strcat y el char* que me queda le mando a openDir para q abra el directorio y cuando termino de operar le hago free al char* que maloquie y closeDir. la cuestion es q siempre me funciono solo en determinado momento me rompe. Segun lo q me pusiste la otra vez este problema q tengo seria que la referencia a esa variable osea al char* estaria invalida? El tema es q al debaguear el char* le llega correctamente. despues me fijo lo de las variables eso no me fije

**Comment by mgarciaisaia** [comment]
Lo que digo es que

> Can't find a source file at "/build/buildd/eglibc-2.19/dirent/../sysdeps/posix/opendir.c"
> Locate the file or edit the source lookup path to include its location.

ni

> expression Type value
> dir Dir * 0x8053378
> __size char[24] Error:failed to execute MI command:-var-create-*&((dir).__size) Error message from debugger back end:no hay ningun miembro llamado __size

son mensajes de error de tu programa, si no de Eclipse, que no te está pudiendo mostrar cosas que le gustaría mostrarte (un cacho de código, y el valor de una variable, respectivamente).

El mensaje subyacente es que tenés que buscar cuál es tu verdadero error - en #516 te conté cómo ver si a tu proceso le llegó una señal y por eso el debugger se detuvo -, y recién ahí vamos a poder tener idea de qué está pasando.

Probá con eso, y, si seguís sin resultados, quizá [`valgrind`](http://faq.utn.so/valgrind) también pueda ayudarte. Pero primero probá con el debugger, a ver qué onda.
