### ISSUE TITLE
Problemas de montaje del cliente con fuse

### ISSUE THREAD

**Issue by fpatalagoity** [sisoputnfrba/foro#564]
Buenas! Estamos tratando de probar la conexión entre el Pokedex cliente y el servidor y resulta que luego de levantar el cliente (ya habiendo levantado el servidor) ocurre algún problema dentro de la función fuse_main (de esto nos dimos cuenta porque no se hace el printf de fuse_main ni el siguiente) porque se sale del programa, es decir, corta el flujo de ejecución.
A su vez, no se monta nada hasta que el servidor no se cierra. 
Es decir, en el panel de la izquierda no aparece el "punto de montaje" hasta que no se cierre la consola en la que está corriendo el Pokedex Servidor.
Por otro lado, de vez en cuando ocurre que al ejecutar un cliente nos sale este cartel:

`fusermount: failed to access mountpoint /home/utnso/git/tp-2016-2c-Chamba/PokedexCliente/Debug/mnt: Permission denied`

¿Qué deberíamos tener en cuenta o revisar?
El código es este:
```
int main(int argc, char *argv[]){

	// Creo archivo log
		archivoLog = crearArchivoLog();

	//Recibo parametros por linea de comandos
		if(argc< 2){
			log_info(archivoLog,"El pokedexCliente no tiene los parametros correctamente seteados.");
			printf("Agregue un punto de montaje.\n");
			return 1;
		}
		puntoPontaje = argv[1]; //tmp
		log_info(archivoLog,"Punto de montaje: %s", puntoPontaje);

		struct fuse_args args = FUSE_ARGS_INIT(argc, argv);

	// Limpio la estructura que va a contener los parametros
		memset(&runtime_options, 0, sizeof(struct t_runtime_options));

	// Esta funcion de FUSE lee los parametros recibidos y los intepreta
		if (fuse_opt_parse(&args, &runtime_options, fuse_options, NULL) == -1){
		/** error parsing options */
			perror("Invalid arguments!");
			return EXIT_FAILURE;
		}

		//getting environment variable for connecting to server
		IP_SERVER = getenv("IP_SERVER");
		PORT = getenv("PUERTO");

		printf("Ip Server : %s\n", IP_SERVER);
		printf("Puerto : %s\n", PORT);

		create_socketClient(&pokedexServer, IP_SERVER, PORT);
		printf("Conectado al servidor\n");
		log_info(archivoLog, "POKEDEX_CLIENTE connected to POKEDEX_SERVIDOR successfully\n");

		log_info(archivoLog, "Levanto fuse\n");
		printf("Fuse montado\n");
		printf("%d",fuse_main(args.argc, args.argv, &chamba_oper, NULL);
                printf("Ejecute el fuse_main\n");
		return 1;
```

Gracias

**Comment by CeciliaRodriguez** [comment]
Hola @fpatalagoity pudieron resolver esto? Por lo primero, salvo que estén pasando mal los parámetros de fuse_main, dudo **mucho** que el error esté en esa función, por no decir imposible. Por el tema de los printf que no se muestran, ¿están ejecutando fuse en modo debug -d o foreground -f? (de otro modo, nunca van a aparecer).

Por el lado del error `fusermount: failed to access mountpoint /home/utnso/git/tp-2016-2c-Chamba/PokedexCliente/Debug/mnt: Permission denied` se me ocurren dos cosas, (siendo la primera la mas probable que les esté pasando):
1) están queriendo montar su filesystem en un directorio donde ya hay un filesystem montado (seguramente el suyo, que nunca lo desmontaron: `fusermount -u puntoDeMontaje`)
2) no tienen permisos sobre el directorio donde lo quieren montar

Otro error que suele aparecer es: `fuse: bad mount point puntoDeMontaje: Transport endpoint is not connected
` por ejemplo, cuando debuggean su filesystem desde eclipse y después le dan terminate. En este caso pasa lo mismo que en 1): el filesystem queda montado, por lo que `fusermount -u puntoDeMontaje` debería solucionarlo.
