### ISSUE TITLE
Problemas con semaforos

### ISSUE THREAD

**Issue by Nicobile** [sisoputnfrba/foro#565]
Buenas, estoy teniendo problemas con los semáforos. Implemente una cola de bloqueados , un hilo y 2 semaforos (uno para hacer de productor-consumidor de entrenadores y el otro por los pokemones disponibles) por pokenest. Todos estos elementos forman una estructura, que malloqueo y guardo en una lista cada vez que me encuentro con una pokenest distinta. Al momento de crear los hilos, les paso como parametro la misma estructura en la que se encuentran (hago esto para que cada hilo entienda cual es su correspondiente semaforo), por si no me explique bien, ahi va un poco de codigo:
int auxiliar;
	for (auxiliar = 0; auxiliar < list_size(listaContenedora); auxiliar++) {
		bloq* stru;
		stru = list_get(listaContenedora, auxiliar);
		pthread_create(&(stru->hilobloq), NULL, (void*) bloqui, (void*) stru);
	}
Siendo bloq, la estructura que contiene los elementos antes descriptos.

Luego, en el hilo, hago 2 sem_wait consecutivos (por el semaforo de entrenadores y el de pokemones disponibles). El sem_post del primer semaforo lo hago cada vez que el entrenador ingrese a una cola (con este nunca tuve problemas), con el que estoy teniendo problemas es con el semaforo de pokemones. De este ultimo hago un post al comienzo por cada pokemon que me encuentre (aca tampoco tengo problemas, porque cuando hago un sem_getvalue y al loguearlo me da el valor de la cantidad de pokemones que hay) y hago un post por cada pokemon que le es liberado a un entrenador cuando este se muere.
Al conectar 2 entrenadores en simultaneo, uno que quiere [P,B,G] y otro que quiere [G,B] y quedar en deadlock, uno muere (el primero) y el otro puede acceder al ultimo pokemon que le faltaba G y desconectarse, el primer entrenador quedaba en la cola de G y el segundo en la cola de B (ambos hilos bloqueados hasta que se libere un pokemon. Hasta aca seguimos bien, ahora el problema lo tengo cuando conecto estos dos entrenadores en conjunto con un tercero que tambien quiere [P,B,G],  al morir el primero, el segundo obtiene todos sus pokemones y se desconecta, pero el ultimo entrenador queda bloqueado en G, lo que hice fue imprimir cada semaforo y obtuve que el semaforo de G valia 1 al desconectarse el segundo entrenador pero valia 0 al llegar el ultimo y por eso quedaba bloqueado. No logro entender el porque. Si esta duda no puede ser resuelta por este medio ¿Alguien esta en la semana ,en cualquier sede, a cualquier hora? 

@lucaslencinas @CeciliaRodriguez 

Mushimisimas gracias

**Comment by tferraro** [comment]
Buenas!

Pingueate a tus ayudantes a ver si te pueden dar una mano con eso, me suena a que es algo muy especifico de lo que implementaste y por el foro va a estar super complicado de ver.

**Comment by Nicobile** [comment]
Creo haber encontrado una """"solución"""" verificando el estado del semáforo contra pokemones disponibles hasta el momento, pero no me convence del todo porque es una verificación que no tendría que ser necesaria porque hago un post cada vez que un pokemon es liberado (no se si me exprese bien). Dejo el issue abierto un rato mas por si surge algo, pero estaria ""solucionado"".

**Comment by Nicobile** [comment]
Esta cerrado pero fue, el problema estaba en que, cuando un entrenador muere, libero sus pokemones y le marco un flag de la estructura en 1, para liberarlo efectivamente con una función dentro del planificador, o del hilo de bloqueados correspondiente, el entrenador atravesaba el semáforo de pokemon para morir peeeeeero no hacia un post. Tengo que cambiar varias cosas, nuevamente GRACIAS Tom!!!! (No iba a ser complicado, iba a ser IMPOSIBLE solucionarlo por aca)

PD: escribo que fue lo que en realidad pasaba para ponerle un punto final definitivo al issue
