### ISSUE TITLE
Condicion de carrera en ls

### ISSUE THREAD

**Issue by yamilacasarini** [sisoputnfrba/foro#566]
Hola que tal estoy probando borrar todo lo de una carpeta y tirar en paralelo un ls. Cuando me lista el contenido de la carpeta me figuran los archivos borrados en rojo. Hay algun problema con que pase eso? Saludos.

**Comment by tferraro** [comment]
Buenas!

Dependerá del orden en el que lleguen las peticiones a tu FS OSADA, pero si el `ls` llegó luego que la petición de borrar una carpeta *no pueden aparecer archivos borrados*.

Esto es algo muy importante para mantener la consistencia del FS, ya que es condición mínima de aprobación que **el acceso a los datos en el Pokedex Servidor se encuentren correctamente sincronizados**.

Saludos!

Tom

**Comment by mgarciaisaia** [comment]
¡Aloha!

_Sólo para que estemos todos en la misma página_, recordar que recordamos que la atomicidad que ofrece FUSE "a mano" es a nivel de operaciones. Es decir, cuando Tom dice que _los datos [...] se encuentren correctamente sincronizados_, está queriendo decir que cada operación haga bien sus cosas y no se pise con las demás. A nivel operación.

Lo que nombrás de los archivos apareciendo rojos en `ls` _puede que_ ocurra porque tanto `ls` como `rm -rf ...` son comandos que _disparan múltiples operaciones_ de FUSE. Es posible que, por ejemplo, tengas un directorio con 30 archivos, y ejecutes "al mismo tiempo" un `rm -rf *` y un `ls`. El `rm -rf` va a listar los archivos (`readdir` + los `getattr` probablemente), y después les va a hacer `unlink` a cada uno de los archivos. Peeeeeero mientras se encolan y atienden esas operaciones para el `rm`, también cae el `ls`, que también va a hacer un `readdir` y los `getattr` de cada archivo que le contesten.

Y esos pedidos se encolan y atienden secuencialmente junto con los del `rm`, por lo que, por ejemplo, podría empezar a resolverse todo el `readdir` y `getattr`s correspondientes al `rm`, después atender el `readdir` del `ls`, después atender un par de `unlink`s del `rm`, e ir mechándolos con los `getattr` del `ls`. El resultado es que puede que, para el momento en que se le resuelve el `getattr`, algunos de los archivos que se le habían listado en el `readdir` al `ls` ya hayan sido `unlink`eados por `rm`, y entonces `geattr` contesta que ese archivo no existe, y ahí está tu colorcito rojo en la consola.

Y está todo bien con eso 👍

Quizá FUSE provea alguna forma de meterse más a bajo nivel y hacer que, por ejemplo, no se modifiquen los archivos listados en el `readdir` hasta que no se terminen sus `geattr`, o cosas flasheras por el estilo. Pero para eso seguramente haya que hacer FUSE multi-hilo, meterse con cosas de más bajo nivel de FUSE (sí, hay _mucho_ para abajo, todavía), y mil millones de cosas más... que no nos interesa que hagan.

La consistencia que pedimos es esa - que cada operación esté sincronizada con las otras que ocurran en paralelo, y que, cuando terminen de "competir" entre sí las operaciones, el resultado tenga sentido. Es decir, si _mientras corre_ el `rm`, un `ls` te muestra archivitos en rojo... ¯\\\_(ツ)\_/¯ Lo que sí necesitamos es que, ponele, si _volvés_ a ejecutar `ls`, los archivos que estaban rojitos ya no estén más (porque ahora el `readdir` no debería verlos), y que, cuando termine el `rm`, `ls no muestre ninguno en rojito.

**Comment by yamilacasarini** [comment]
Genial muchas gracias, quedo claro entonces. Cierro issue
