### ISSUE TITLE
Cambio algoritmo mapa por señal

### ISSUE THREAD

**Issue by jjuli93** [sisoputnfrba/foro#567]
Buenas, nos surgió una duda con respecto al cambio de algoritmo con el mapa ejecutando. ¿El cambio de algoritmo tiene que ser instantáneo? ¿o se podría esperar a que termine la ráfaga actual para cambiarlo? (ráfaga actual en srdf esperaría a que el entrenador ejecutando se bloquee)
Gracias..

**Comment by tferraro** [comment]
Buenas!

Según el enunciado:
_El Planificador podrá ir alternando el algoritmo de planificación entre Round Robin (con quantum configurable) y Shortest Remaining Distance First (SRDF) a medida que se relea su archivo de configuración. __Es válido esperar a finalizar la ráfaga de ejecución actual antes de efectivizar el cambio de algoritmo.___

Saludos!

**Comment by juanignaciog** [comment]
Buenas, recien veo issues anteriores y me quedó una duda de este. Por que, si el algoritmo fuera SRDF la rafaga recien terminaría cuando se bloquea el entrenador? No alcanzaría con que llegue a capturar a su proximo pokemon, entonces termina su rafaga hasta que tenga la ubicacion de su nueva pokenest?
