### ISSUE TITLE
Pruebas base

### ISSUE THREAD

**Issue by jjuli93** [sisoputnfrba/foro#568]
Buenas nuevamente, estaba leyendo el documento de pruebas y veo que especifica  los metadatas de los mapas y entrenadores pero en ningún lado hace referencia a los pokenests (las posiciones y cuantos pokemones contienen)

**Comment by tferraro** [comment]
Buenas!

No entiendo cual es la _consulta/duda_ del issue. Podés explayarte un poco más?

**Comment by jjuli93** [comment]
si, mala mia jaja.  El problema que tengo es que para realizar las pruebas básicas del documento necesito saber las posiciones y la cantidad de pokemones que contiene cada pokenest ya que de esto depende quien va a ejecutar primero en el SRDF y el tema de los deadlocks también.
Por ejemplo en la prueba base dice que quedan en deadlock los entrenadores 1,2 y 3 pero esto no pasaría si hay 3 pikachu y 3 bulbasaur en los pokenests.
Me parece que cada pokenest tendría un solo pokemon en este caso pero quería corroborar por las dudas.

**Comment by tferraro** [comment]
Ahora si!

El mismo sábado de la entrega se publicaron los archivos para usarse con el documento de pruebas. Podés pegarles una mirada entrando a [faq.utn.so/pruebas-charmander](http://faq.utn.so/pruebas-charmander)

Saludos!

**Comment by jjuli93** [comment]
Ahhh, genial. Gracias!
