### ISSUE TITLE
Problemas con Truncate

### ISSUE THREAD

**Issue by fedehermida** [sisoputnfrba/foro#569]
Hola,

Estuvimos intentando implementar el truncate sin dummy function, pero la misma siempre nos tira size 0 y deja el archivo sin bloques. Luego cuando intenta escribir devuelve una falla. Por lo que estuvimos viendo NANO borra todo el archivo y luego escribe todos los bytes desde 0, obviando el offset. 

Desde ya muchas gracias,

Federico.

**Comment by mgarciaisaia** [comment]
@fedehermida, ¿decís que nunca te llega un truncate que agregue bloques al archivo antes de las escrituras?

Que `nano` trunque el archivo a 0 antes de escribir es esperable y válido - cada editor trabaja como gusta. Lo que es raro es que antes del `write` no te llegue un nuevo `truncate` que agrande el archivo al tamaño correspondiente.

**Comment by fedehermida** [comment]
Matias,

Hace una única llamada al truncate, luego a setxattr y a getxattr y por ultimo al Write donde ya sin bloques escribe en el aire y explota.

**Comment by CeciliaRodriguez** [comment]
Hola @fedehermida hice la prueba, y las llamadas son tal como decís de la siguiente manera, para el siguiente ejemplo:

LOOKUP /prueba.txt
getattr /prueba.txt
   NODEID: 5
   unique: 197, success, outsize: 144
unique: 198, opcode: OPEN (14), nodeid: 5, insize: 48, pid: 4082
open flags: 0x8001 /prueba.txt
   open[0] flags: 0x8001 /prueba.txt
   unique: 198, success, outsize: 32
unique: 199, opcode: SETATTR (4), nodeid: 5, insize: 128, pid: 4082
**truncate /prueba.txt 0**
getattr /prueba.txt
   unique: 199, success, outsize: 120
unique: 200, opcode: WRITE (16), nodeid: 5, insize: 150, pid: 4082
write[0] 70 bytes to 0 flags: 0x8001
   **write[0] 70 bytes to 0**
   unique: 200, success, outsize: 24
unique: 201, opcode: RELEASE (18), nodeid: 5, insize: 64, pid: 0
unique: 202, opcode: LOOKUP (1), nodeid: 1, insize: 51, pid: 4082
LOOKUP /prueba.txt
getattr /prueba.txt
   unique: 201, success, outsize: 16
   NODEID: 5
   unique: 202, success, outsize: 144

Está claro que, primero lo trunca a 0 y cuando vuelve a llamar a write se invoca la función con TODO el contenido del archivo. Es decir, si con nano lo que hice fue agregar una línea, el archivo primero se trunca a 0 y después se va llamando a write **teniendo en el buf el contenido de lo que ya tenía el archivo + la nueva línea.** (por eso escribe 70 bytes desde 0, yo en realidad la línea que agregué no eran 70 bytes)

Ahora, el problema que estás teniendo es esto que decís que "escribe en el aire" y explota. Siempre que a vos te pidan escribir cosas en un archivo, tendrías que validar que tengas espacio en ese archivo y en caso contrario debieras intentar buscar bloques libres en el filesystem para asignarselos y luego poder escribir. **Es decir, de alguna forma, en tu write, si no tenés espacio (ó sea lo que te llega de offset+size es mayor que el size del archivo), vas a terminar truncando el archivo a offset + size para luego poder escribir. ¿Me explico?**

**Comment by chrisgel15** [comment]
Estimados,

Nosotros reportamos un error similar los issues de Osada-Test (btw: esos los ven?)

https://github.com/sisoputnfrba/osada-tests/issues/3

La consulta tiene que ver justamente con que queremos agregar a un archivo, mas bloques de los que tenemos disponibles en el FS. Fuse llama al truncate, borramos todo, y cuando vamos a escribir todo lo que se borro + lo que se agregó, nos encontramos con que no hay espacio y automaticamente FUSE llama al "unlink" (para tirar para atras todo).

O sea, tenemos un archivo, lo intentamos agrandar, y terminamos sin archivo (por la llamada a "unlink").

Como resolveriamos esa situacion? Entiendo que estamos hablando de algo parecido a lo que comentan aca.

Saludos

**Comment by chrisgel15** [comment]
Del comentario de @CeciliaRodriguez no entiendo lo siguiente:

> Siempre que a vos te pidan escribir cosas en un archivo, tendrías que validar que tengas espacio en ese archivo **y en caso contrario debieras intentar buscar bloques libres en el filesystem para asignarselos y luego poder escribir**

Si justamente me quede sin espacio en el disco y ya se ejecutó el truncate, como hacemos?

**Comment by mgarciaisaia** [comment]
No había visto los issues de osada-tests, gracias por recordarmelo 👍

¿Qué pasa si directamente devolves algo simil a `-ENOSPC` desde el `write`? ¿Vuelve a llamar a `truncate` con el size mas grande o algo?

Si les están pidiendo más bloques de los que hay disponibles, _alguien_ tiene que fallar - `truncate`, `write`, o el que sea, pero _alguna operación_ tiene que decir que se quedó sin espacio.

Con lo de que _automáticamente FUSE llama al `unlink`_, cuidado. Chequeen si realmente es FUSE el que manda el `unlink`, y no el editor de texto o el comando que estén ejecutando.

**Comment by Streq** [comment]
Hola, recién acabo de probarlo en mi implementación, si el llamado a write devuelve -EFBIG (o cualquier error, supongo yo) cuando se le intenta escribir con nano, el editor avisa del error por pantalla e inmediatamente vuelve a reescribir lo que había antes de truncar el archivo a 0.

**Comment by chrisgel15** [comment]
@mgarciaisaia 
Nuestro WRITE justamente esta devolviendo `-ENOSPC` cuando no hay espacio. Viendo el comentario de @Streq, vamos a probar con `-EFBIG`.

Con respecto a que FUSE llama _automaticamente a unlink_, me exprese mal, es el editor o comando quien lo llama.

@alexsem, te pido si podes probar con lo que comentan aca y tomar la posta del tema.

Saludos!

**Comment by alexsem** [comment]
@chrisgel15. Sir, yes sir.
