### ISSUE TITLE
SIGUSR1 O SIGUSR2?

### ISSUE THREAD

**Issue by Nicobile** [sisoputnfrba/foro#570]
Buenas, en el documento de las pruebas del tp, mas precisamente en mapa, lei estas tres condiciones que se requieren para aprobar:

El sistema permite, mediante la signal SIGUSR1, cambiar el algoritmo de planificación en tiempo de
ejecución
El sistema permite, mediante la signal SIGUSR1, cambiar el retardo del algoritmo de detección
Deadlock en tiempo de ejecución
El sistema permite, mediante la signal SIGUSR1, cambiar el retardo entre turnos en tiempo de
ejecución

Luego, el enunciado dice:

Cuando reciba la señal SIGUSR2, el proceso Mapa deberá releer su archivo de Metadata, actualizando estos parámetros durante la ejecución.

A quien le hago caso? SIGUSR2 o SIGUSR1?

**Comment by tferraro** [comment]
Al enunciado! Es un typo que quedo en el documento en pdf (sigo sin
recordar porque lo publicamos así...)

**Comment by Nicobile** [comment]
Listo, gracias Tom!
