### ISSUE TITLE
Testeando/Debugeando con massive file creator

### ISSUE THREAD

**Issue by KevinTemes** [sisoputnfrba/foro#571]
Buenas!

Estoy corriendo los tests del filesystem y me surgieron problemas con el último, el massive file creator. Lo corro con los parámetros especificados en el documento de pruebas y ejecuta correctamente.
El problema que estoy teniendo es que, si bien crea los archivos dentro del disco, los md5sum me devuelven BAD, y no estoy dándome cuenta de dónde está el error.
Mi única pista hasta ahora es que, al correr FUSE en modo debug, una vez que finaliza de crear los archivos, lanza las siguientes peticiones y mensajes:

> LOOKUP /pr_01file_1.test
> getattr /pr_01file_1.test
>    NODEID: 162
>    unique: 1556, success, outsize: 144
> unique: 1557, opcode: RELEASE (18), nodeid: 160, insize: 64, pid: 0
>    unique: 1557, success, outsize: 16
> unique: 1558, opcode: READ (15), nodeid: 161, insize: 80, pid: 6671
> read[0] 4096 bytes from 0 flags: 0x0
>    read[0] 1048576 bytes from 0
> fuse: read too many bytes
>    unique: 1558, success, outsize: 1048592
> fuse: writing device: Invalid argument
> unique: 1559, opcode: OPEN (14), nodeid: 162, insize: 48, pid: 6670
> open flags: 0x0 /pr_01file_1.test
>    open[0] flags: 0x0 /pr_01file_1.test
>    unique: 1559, success, outsize: 32
> unique: 1560, opcode: RELEASE (18), nodeid: 161, insize: 64, pid: 0
>    unique: 1560, success, outsize: 16
> unique: 1561, opcode: READ (15), nodeid: 162, insize: 80, pid: 6670
> read[0] 16384 bytes from 0 flags: 0x0
>    read[0] 1048576 bytes from 0
> fuse: read too many bytes
>    unique: 1561, success, outsize: 1048592
> fuse: writing device: Invalid argument
> unique: 1562, opcode: READ (15), nodeid: 162, insize: 80, pid: 6670
> read[0] 4096 bytes from 0 flags: 0x0
>    read[0] 1048576 bytes from 0
> fuse: read too many bytes
>    unique: 1562, success, outsize: 1048592
> fuse: writing device: Invalid argument
> unique: 1563, opcode: RELEASE (18), nodeid: 162, insize: 64, pid: 0
>    unique: 1563, success, outsize: 16

Esto lo repite varias veces, copio esta parte para que se den una idea.

Las líneas que más me hacen ruido son "fuse: writing device: Invalid argument" y "fuse: read too many bytes", que me hacen pensar que tengo algo raro dentro mis implementaciones de read/write; pero se me está complicando encontrar cuál es el problema. Revisé las funciones varias veces y (sacando este temita del md5sum) parecen funcionar correctamente.

Leyendo estos dos issues #556 y #542 , supuse que el problema podía venir de que estoy manejando mal los archivos de tamaño grande; lo que hice fue probar copiando al disco osada una imagen relativamente grande de una medalla (unos 30k bytes). La imagen se copió, pero al tratar de abrirla desde el disco el sistema me daba el mensaje "[Ruta de la imagen en el disco osada] contains no data." Lo que hice después fue copiar esa misma imagen desde el disco osada al escritorio de la VM, y cuando la quise abrir, lo hizo perfectamente, y la imagen se visualizaba sin problemas. Inclusive, cuando hago el md5sum de las tres instancias del archivo (la imagen original alojada en /home/utnso, la copiada en el disco osada y la del escritorio), las tres me devuelven exactamente el mismo valor...
Repetí todos estos pasos anteriores con un archivo de texto de tamaño similar (alrededor de 32 mil caracteres) y el resultado fue el mismo. Quise hacer exactamente lo mismo con los archivos que crea el script, pero al tratar de copiarlos fuera del disco me salta un aviso: "Error splicing file: error de entrada/salida", por lo que indudablemente algo en el proceso de creación de los archivos no se está haciendo bien.

Alguna idea de dónde puede estar el problema? Es factible que sea algo muy específico de mi código... de ser así, hay alguna chance de que pueda ubicar a algún ayudante en campus o medrano durante lo que queda de esta semana o la próxima, cosa de poder verlo?

Saludos!

**Comment by nachosoto93** [comment]
Creo que el error lo tenes en el escribir y leer. En nuestro grupo teniamos el mismo problema. Verifica con un printf que los tamaños de los buffer que estas enviando y recibiendo del servidor son exactamente los que solicita fuse. Eso te puede dar una pista de donde tenes el problema. 


Por otro lado, que se copie bien un archivo no quiere decir que se lea bien. Nosotros tuvimos problemas en los paquetes del leer(testeando desde localhost) y despues cuando testeamos en red se nos cagaban el listar y escribir.

Espero haberte ayudado. Saludos.

**Comment by KevinTemes** [comment]
Mil gracias por el comentario! Efectivamente, el problema estaba en el read. Había interpretado mal el funcionamiento de la función, y la habia implementado de manera que siempre leyera el archivo completo, y no contemplaba que se leyera una cantidad X de bytes a partir de un offset. Reimplementé esa parte y se solucionó.

Gracias de nuevo! cierro el issue
