### ISSUE TITLE
Manejo de concurrencia al leer y abrir un archivo

### ISSUE THREAD

**Issue by AlexanderLoyaga** [sisoputnfrba/foro#572]
Tenemos una duda conceptual, sobre como manejar la concurrencia en un mismo archivo que se quiere leer y escribir desde 2 terminales distintas. 
La duda en si, es sobre que cosa deberiamos contemplar.
Algo que por el momento no estabamos teniendo en cuenta, es si una terminal abre un archivo y empieza a escribir , luego otra terminal abre el mismo archivo y tambien quiere escribir.
Hay que tener en cuenta casos como este?

**Comment by tferraro** [comment]
Holis,

Para abrir un archivo para poder escribir, que hay que hacer?

Saludos!

Tom

PD: Palabras claves para esto: *Condiciones de Bernstein*

**Comment by chrisgel15** [comment]
Tengo una consulta con respecto a este caso.

De darse la situacion en que 2 clientes abran el archivo, cada uno edite lo que desee y lo guarden concurrentemente.

Es correcto manejar la sincronizacion de acuerdo a como llegan las peticiones al server? Esto es, el que primero llega se guarda (con exclusion), y el segundo luego pisa lo que el primero escribio (tambien con exclusion).

Haciendo pruebas en la VM con Gedit, veo que si abro 2 veces el mismo archivo de texto y en un escribo "A" y en el otro "B" (por ejemplo), el resultado final es el que guardé en segundo lugar.

Aguardo sus comentarios, 

Saludos!

**Comment by mgarciaisaia** [comment]
Sí, claro. El plan es que manejes la concurrencia _que puedas_. Para sincronizar no tenés más información que los pedidos de operaciones que te llegan, así que mucho más que eso (evitar que los dos writes se realicen en simultáneo) no tenés para hacer.

Y eso no tiene que ver con que el FS sea distribuído ni nada. Si probás en tu FS nativo, te va a pasar lo mismo: si mandás dos escrituras distintas al mismo tiempo, buen, va a quedar una sóla persistida - la otra será sobreescrita, o bien fallará.
