### ISSUE TITLE
Problema al compilar proyecto: "Please add -D_FILE_OFFSET_BITS=64 to your compile flags!"

### ISSUE THREAD

**Issue by fpatalagoity** [sisoputnfrba/foro#573]
Buenas, tuve que clonar el repositorio por un problema que tenía al ejecutar y al buildear uno de los proyectos me aparece el mensaje de error del título.
Todos los proyectos se buildean en modo Debug (en el martillito digamos).
Los includes están configurados (aunque los includes son -l y no -D).
Hice rebuild de los índices, refresh y clean y nada...
¿Qué más debería mirar?

Gracias!

**Comment by mgarciaisaia** [comment]
El `-D` es, efectivamente, un `#define`.

Lo agregás en las properties del proyecto de manera similar a los otros flags de configuración (en la parte de `Symbols` te muestra que equivale al `-D` de gcc), o bien agregás un `#define` con el valor de la constante en tu código fuente.

**Comment by fpatalagoity** [comment]
Lo agregué en Symbols y lo puse como  #define pero aún así me sigue dando el mismo mensaje... :/

**Comment by fpatalagoity** [comment]
Listo! Lo volví a clonar y anduvo.

Gracias!
