### ISSUE TITLE
Problemas con FUSE y el uso de sockets

### ISSUE THREAD

**Issue by dromero-7854** [sisoputnfrba/foro#574]
Buenas días a todos,

Quisiera si por favor me podrían ayudar con dos inconvenientes que estoy teniendo con FUSE y el manejo de sockets.

- **¿Cómo tendría que ser la interacción cliente-servidor con FUSE?**

Actualmente en FUSE **estoy abriendo y cerrando las conexiones al servidor en cada función que implementé en FUSE** (mkdir, getattr, read, write, etc) 
**Y del lado del servidor, no estoy cerrando la conexión** close(client_socket) (comento el motivo en _Inconvenientes con la función write_)

Desde el principio me pareció muy ineficiente esta solución pero es la única que logro hacer funcionar.

Es decir, intenté abrir en la función main de FUSE la conexión, y utilizar la misma en las funciones implementadas. Pero sólo me responde la primera petición realizada al servidor. Para la segunda petición, hay un error. En esta prueba cerraba la conexión del lado del servidor (capaz el error viene por ese lado)

Con respecto a este último punto, la duda que me surge es **¿Cómo funciona la función close() tanto del lado del cliente como del servidor?**

Es decir, si el cliente va a estar mandando peticiones al servidor, el servidor después de finalizar la petición ¿llama a la función close()? ¿lo hace el cliente luego de recibir la respuesta? ¿lo tiene que hacer ambos? ¿no lo tiene que hacer ninguno de los dos, ya que las peticiones van a ser continuas?

- **Inconvenientes con la función write**

El otro inconveniente que estoy teniendo, por ahi esta relacionado con el punto anterior, y tiene que ver con la función write.

Pruebo con escrituras de archivos de 10MB. Al principio incluí la función close() del lado del servidor, y me daba problemas. Intuyo que era porque cerraba la conexión con el cliente, que luego me volvía a solicitar una escritura, y ya no podía porque estaba cerrada la conexión.

Cuando le saqué la función close() del lado del servidor, empece a realizar escrituras de archivos de 10MB como un campeón. Hasta que en algún momento (y esto es aleatorio, no sucede todas las veces) se produce una desconexión con el socket (me muestra en el log como que el cliente esta desconecto y entra en un loop infinito mostrando ese mensaje)

Intuitivamente, puede ser un problema que se abren y se cierran conexiones socket a lo pavote por el problema anterior.

Otro posible motivo es que la funcion write, en el caso de que se solicite escribir 4096 bytes, y solo pueda escribir 100, no estoy retornando la cantidad específica de bytes escritos.

Gracias por cualquier ayuda que me puedan brindar...

Saludos
Dante Romero

**Comment by tferraro** [comment]
Buenas!

Me parece que no terminaste de entender que es lo que uno está haciendo al llamar a la función `close()`. :astonished: 

`close()` sirve para cerrar el socket, y por lo tanto, ese extremo de la conexión. La razón por la que se hacen en ambos lados, es por la dinámica normal que tienen los programas, si pido recursos, **tengo** que devolerlos. A nivel red, cerrar el socket, significa algo particular la conexión utilizando el protocolo TCP, porque [tiene una forma de cerrar la conexión que vas a ver en Redes](http://intronetworks.cs.luc.edu/1/html/_images/tcp_ladder_states.png).

Resumiendo sin irse por las ramas, si vas a cerrar la conexión en un extremo, cerralo en el otro, **siempre**, bajo cualquier circunstancia, sin importar lo que pase.

De todas maneras, dado que el cliente Pokedex se conecta al servidor y puede o no mandarle peticiones dependiendo de lo que diga FUSE, te recomendaría mantener abierta la conexión hasta que alguno de los 2 decida cerrarse.

Respecto de lo de la función write, arreglá lo que hablamos antes y fiajte si sigue pasando, así vamos descartando.

Saludos!

Tom

**Comment by dromero-7854** [comment]
Gracias Tomás por aclararme el uso de a función close(),

En el hipotético caso que abra la conexión en la función main de FUSE, y utilizando dicha conexión en cada función de FUSE, siguiendo lo explicado **no tendría que cerrar el socket (ni del lado del cliente, ni del lado del servidor) durante las peticiones del cliente**. 

Si es asi, el único motivo de cierre que se me ocurre del lado del cliente es un cuando mato el proceso FUSE y con el uso de señales cerrar correctamente el socket. Y del lado del servidor, cuando ya no recibo bytes del cliente (recv retorna 0 o -1) 

¿Entendí bien?
 Gracias...

**Comment by tferraro** [comment]
Si mal no recuerdo, no especificamos que tienen que manejar señales como `SIGINT` (la que manda con Ctrl+C) en el pokedex cliente, si quieren implementarlo, genial! Pero no descuiden el resto del TP, porque solo suma si cumplen todo el resto de las especificaciones.

La opción del lado del servidor la veo plausible para ambos casos, difiriendo en el que el cliente debería informar que paso, y si se puede, cerrarse correctamente.

Saludos!

**Comment by dromero-7854** [comment]
Como estas Tomás,

Estuve probando nuevos cambios a partir de lo comentado, y en este momento pareciera que esta funcionando correctamente. Se abre una sola conexión cliente-servidor y se trabaja sobre esta.

Gracias por la ayuda... Doy por cerrado el issue.

Saludos!
