### ISSUE TITLE
Duda con la funcion "fuse_fill_dir_t"

### ISSUE THREAD

**Issue by chrisgel15** [sisoputnfrba/foro#576]
Estimados,

Tengo un problema con la funcion "fuse_fill_dir_t" que se usa cuando FUSE invoca la funcion ReadDir.

Un poco de contexto...
Nosotros comenzamos planteando todo el filesystem de forma centralizada (haciendo funcionar todas sus operaciones) y ahora estamos expandiendolo a que funcione de forma distribuida (agregando los sockets, el protocolo de comunicacion y los semaforos)

En este escenario, no tuve ningun problema al utiliza la funcion "fuse_fill_dir_t" que FUSE me pasa como parametro, simplemente haciendo "filler(....)" y llenando el buffer que tambien me pasa FUSE.

Ahora, cuando expandimos a forma distribuida, lo que planteo es que FUSE llame a ReadDir, yo llame al server con el path solicitado, y ahi en el server, declarar una nueva variable de tipo "fuse_fill_dir_t", utilizarla para llenar el buffer y devolver al cliente este buffer ya completo.

El incoveniente es que esta implementacion me pincha en el servidor (con un error que me dice que estoy utilizando un valor que no está inicializado) cuando quiero utilizar la funcion "fuse_fill_dir_t", y creo que el problema es que está declarada en fuse.h de esta forma:

> typedef int (*fuse_fill_dir_t) (void *buf, const char *name, const struct stat *stbuf, off_t off);

Y me parece que para utilizarla debo hacer algo como...

> fuse_fill_dir_t filler = &"LA FUNCION QUE QUIERO LLAMAR"

Y aqui es donde me trabo, porque la funcion que quiero llamar esta en el archivo "fuse.c" que no puedo acceder.

Primera pregunta: ¿Esta interaccion entre cliente y servidor se resuelve asi? ¿Utilizando la funcion "fuse_fill_dir_t" en el servidor?

Porque la otra opcion que se me ocurre (que me sumaria muchos llamados entre cliente y servidor cada vez que se invoque "ReadDir"), es utilizar la funcion "fuse_fill_dir_t" en el cliente (que ya viene "instanciada" digamos como argumento en "ReadDir") y llamar muchisimas veces a mi servidor (una vez por archivo, o sea 2048 llamados) para ir devolviendo la informacion de ese directorio solicitado.

Espero se entienda y aguardo sus comentarios,

Saludos

Christian

**Comment by chrisgel15** [comment]
Closed.

Finalmente lo resolvi utilizando la funcion filler del lado del cliente. 

Saludos

**Comment by mgarciaisaia** [comment]
Esa es la que va.

La función filler esa es algo interno a la implementación de FUSE. FUSE te cuenta cuál es su interfaz, para que vos puedas llamarla, pero nada más.

No tendría sentido ejecutar un filler en el servidor, porque ahí no está corriendo con FUSE. Y vos no tenés _ninguna_ garantía sobre esa función, más que la interfaz.

Digamos, FUSE podría decidir (ni idea por qué, es hipotético este planteo) mandarte una función filler distinta en cada llamado... Y, mientras mantenga esa interfaz, a vos no debería calentarte.

Así que va bien la mano por donde resolvieron 👍
