### ISSUE TITLE
Consulta: Navegar el FS desde Consola vs. Gestor de archivos grafico

### ISSUE THREAD

**Issue by chrisgel15** [sisoputnfrba/foro#577]
Estimados,

Desde hace unos dias que estaba atorado implementando la version de FS distribuido (ya funciona de forma centralizada) pero estaba con diversos inconvenientes (memory leaks, implementacion del protocolo de comunicacion, etc).

Llegué un punto donde me estaba costando avanzar y descubri que está funcionando correctamente si lo navego desde la consola (me muestra correctamente las carpetas y archivos, que es lo que tengo implementado de forma distribuida hasta ahora, incluso utilizando mas de un cliente) pero cuando intento navegarlo a traves del gestor grafico comienzan los problemas: Me muestra contenido incorrecto dentro de los directorios, me muestra archivos que son carpetas y viceversa, y hasta en algun punto llega a colgarse y no responder mas.

De forma centralizada (sin sockets) utilizando el navegar grafico no venia teniendo inconvenientes, por lo que sospecho que puede ser algun tema de performance en el entorno grafico ahora que le agregue los sockets.

Queria consultar si esto es un comportamiento esperable o si suena a algun inconveniente de implementacion, y ademas, dada la cercania de la entrega, si debo tratar de corregir este mal funcionamiento en el entorno grafico ya que entiendo que las pruebas las hariamos en la Lubuntu Server donde solo tenemos la consola (y allí parece andar bien)

Gracias

**Comment by nachosoto93** [comment]
Yo revisaria como me están llegando los paquetes en los envíos. Tene en cuenta que si miras el debug de fuse, la cantidad de operaciones que lanza cuando navegas por un gestor de archivos, es mucho mas grande en comparación de navegar por consola. De hecho, el gestor de archivos de lubuntu cuando carga un directorio, no solo los lista, sino que tambien lee los archivos. Puede venir por ahi el tema. Espero haberte ayudado. Saludos :)

**Comment by varas-c** [comment]
Fijate cuando ejecutas tu pokedex cliente, ejecutarlo en modo single thread. Proba ejecutarlo asi

./PokedexCliente [rutaMontaje] -f -s

Si no me equivoco, el parametro que te soluciona esto es el -s. A nosotros nos pasaba lo mismo, por consola andaba perfecto, por interfaz grafica, se rompia.

Espero que te sea de ayuda

**Comment by chrisgel15** [comment]
@varas-c Mil gracias! Eso hizo la magia. La verdad que FUSE crea un monton de threads, de esta forma corre mucho mas prolijo!

@nachosoto93 Gracias por tu comentario!!

#closed
