### ISSUE TITLE
Condición de carrera al pedir bloques de datos libres para escritura

### ISSUE THREAD

**Issue by dromero-7854** [sisoputnfrba/foro#578]
Buenas a todos,

Capaz es una pregunta que me la voy a contestar solo, pero estaba pensando y me quedo la duda si es necesario sincronizar el pedido de bloques libres de datos para la escritura de datos.

Es decir, ¿puede ocurrir que cuando se estén escribiendo dos archivos, por algún motivo se le asignen el mismo bloque libre a los dos archivos?

Estamos utilizando la función _bitarray_test_bit_ para saber en el bitmap que bloques de datos estan libres.

Saludos
Dante Romero

**Comment by sciciliani** [comment]
Es MUY probable.

Lo que hacés en ese caso es que tu función que obtiene un bloque libre lo
busca, lo marca como ocupado y devuelve el número.

Luego si por alguna excepción fallara la escritura (no se me ocurre ahora
un ejemplo de por qué) en todo caso ahí lo volvés a marcar como liberado y
todos felices.

Desde ya que tu función "obtenerBloqueLibre" va con mutex arriba y abajo.
En otras palabras querés que si un hilo quiere buscar un bloque libre
mientras otro hilo está en el proceso de búsqueda, tenga que esperar a que
ese termine.

Una más: Es una GRAN optimización recordar el bit (o el byte) donde
encontraste el último bloque libre y empezar a recorrer de ahí. De última
si llegás al final y no encontraste nada, te das una segunda vueltita por
si se liberó algo atrás y sino fallás por falta de espacio libre.

Otra GRAN optimización es recordar el último bloque del archivo donde
escribiste algo (así no tenés que recorrer toda la tabla de asignación de
vuelta desde el comienzo).

**Comment by dromero-7854** [comment]
Gracias Santiago,

Muy buena la info. Cierro el issue

Saludos
Dante Romero
