### ISSUE TITLE
Fuse - Problema con write

### ISSUE THREAD

**Issue by gustofa** [sisoputnfrba/foro#580]
Hola.
Estamos teniendo un problema copiando archivos grandes dentro del punto de montaje.
Se copia el archivo, queda la copia con el mismo tamaño que el original, pero no coinciden sus md5sum.
La comunicación entre cliente y servidor de pokedex va bien, el server va escribiendo en OSADA los paquetes que le manda Fuse, de a 4096 byte. Pero notamos que en el medio de todas esas llamadas a write de 4096byte le llegan cada tanto una donde size es 4096byte pero el parametro buf está vacio, y luego sigue con las de 4096byte.
Este comportamiento es normal?   esos cortes significan algo?

Aclaro que estamos probando con un solo cliente mono hilo, y esto pasa cuando hacemos un cp de un archivo de 10mb desde fuera hacian dentro del punto de montaje.

Saludos

**Comment by nachosoto93** [comment]
@gustofa Hola! Estas seguro que el problema se esta dando en el write y no en el read?. Porque si la lectura esta fallando, por mas que los archivos sean identicos el md5sum va a dar distinto.

En caso de que no sea asi. Intenta analizar desde el lado del server que tamaños estas recibiendo y al mismo tiempo lo que escribis. 

Saludos, espero haberte ayudado.

**Comment by gustofa** [comment]
Hola.
Si, el problema era en el write. Estabamos pasando mal el tamaño del buffer desde el cliente al servidor. 
Ya fue solucionado. 

Gracias
