### ISSUE TITLE
Consulta sincronizacion lecturas y escrituras (inanicion)

### ISSUE THREAD

**Issue by chrisgel15** [sisoputnfrba/foro#581]
Estimados,

Les queria consultar como deberiamos manejar el caso en el cual haya multiples clientes leyendo un archivo y un cliente intentando escribirlo.

Segun lo que pienso, el sistema deberia permitir que quienes quieran leer lo puedan hacer a menos que alguien este escribiendo, en cuyo caso, todos (lectores y escritores) deberan esperar que se libere el recurso que esta siendo escrito.
De otra forma, cuando alguien quiera escribir debera verificar que no haya nadie escribiendo y que no haya nadie leyendo (para no modificar esas lecturas)

Ahora bien, este planteo podria generar inanicion para los escritores, ya que si un archivo es leido continuamente puede no atenderse el pedido de escritura.

Agradezco sus comentarios sobre como resolver este inconveniente o si no lo estamos considerando a los fines del TP.

Saludos!

**Comment by mgarciaisaia** [comment]
@chrisgel15 groso análisis 👍

Para modelar este problema de bloquear un recurso para lecturas o escrituras existen los `pthread_rwlock_t`, al que, por ejemplo, lockeás para lectura con [`pthread_rwlock_rdlock`](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_rwlock_rdlock.html). Ahí cuenta un poco en qué orden se van a entregar los locks en caso de que hubiera varios threads pidiéndolo en simultáneo, dependiendo de cosas como el algoritmo de planificación de threads y lo que decida cada implementación de la función (esta es la documentación de pthread dentro del "estándar POSIX", por lo que habla en general - cada implementación puede tener diferencias).

Así que, meh - tener o no inanición podría o no ser una limitación de tu inanición. Lo importante con las limitaciones es conocerlas, entenderlas, y decidir si son aceptables o no en un sistema.

Para este caso en particular, _eventualmente_ nos vamos a aburrir de poner nuevos procesos a leer/escribir el mismo archivo, así que está todo bien con la inanición. Mientras que no haya condiciones de carrera, nos fumamos la inanición, no pasa nada 👌

**Comment by chrisgel15** [comment]
Gracias!!
