### ISSUE TITLE
Massive file creator

### ISSUE THREAD

**Issue by franciscopuyo** [sisoputnfrba/foro#582]
Estamos usando el massive file creator para correr la prueba. Y nos dio este resultado:

Error abriendo archivo para lectura en thread numero 3014978368.
Error abriendo archivo para lectura en thread numero 3006585664.
Error abriendo archivo para lectura en thread numero 3040156480.
Error abriendo archivo para lectura en thread numero 2981407552.
Error abriendo archivo para lectura en thread numero 3048549184.
  1 - Archivo: fs/a_file_1.test
  1 - Se escribio con md5sum: 70852283543a2cf3c6e148f51e8224a7
  1 - Tras la lectura se obtuvo md5sum: 70852283543a2cf3c6e148f51e8224a7
  1 - Resultado: OK.

  2 - Archivo: fs/a_file_2.test
  2 - Se escribio con md5sum: 2be7c42ce44affb99e6c09e6807b5591
  2 - Tras la lectura se obtuvo md5sum: 2be7c42ce44affb99e6c09e6807b5591
  2 - Resultado: OK.

  3 - Archivo: fs/a_file_3.test
  3 - Se escribio con md5sum: 2be7c42ce44affb99e6c09e6807b5591
  3 - Tras la lectura se obtuvo md5sum: 2be7c42ce44affb99e6c09e6807b5591
  3 - Resultado: OK.

4 - El thread 3048549184 termino con error.
5 - El thread 3040156480 termino con error.
  6 - Archivo: fs/a_file_6.test
  6 - Se escribio con md5sum: 2655eb86bba7586601a1d8386b13627c
  6 - Tras la lectura se obtuvo md5sum: 2655eb86bba7586601a1d8386b13627c
  6 - Resultado: OK.

  7 - Archivo: fs/a_file_7.test
  7 - Se escribio con md5sum: 2655eb86bba7586601a1d8386b13627c
  7 - Tras la lectura se obtuvo md5sum: 2655eb86bba7586601a1d8386b13627c
  7 - Resultado: OK.

8 - El thread 3014978368 termino con error.
9 - El thread 3006585664 termino con error.
 10 - Archivo: fs/a_file_10.test
 10 - Se escribio con md5sum: 1aeec2d6cc15f0a80b6d1b011ffc71ba
 10 - Tras la lectura se obtuvo md5sum: 1aeec2d6cc15f0a80b6d1b011ffc71ba
 10 - Resultado: OK.

 11 - Archivo: fs/a_file_11.test
 11 - Se escribio con md5sum: 86826382193910ffefa6e87949c02dea
 11 - Tras la lectura se obtuvo md5sum: 86826382193910ffefa6e87949c02dea
 11 - Resultado: OK.

12 - El thread 2981407552 termino con error.
 13 - Archivo: fs/a_file_13.test
 13 - Se escribio con md5sum: 86826382193910ffefa6e87949c02dea
 13 - Tras la lectura se obtuvo md5sum: 86826382193910ffefa6e87949c02dea
 13 - Resultado: OK.

 14 - Archivo: fs/a_file_14.test
 14 - Se escribio con md5sum: 95666ba29084ed4fb0ea8b983fe47343
 14 - Tras la lectura se obtuvo md5sum: 95666ba29084ed4fb0ea8b983fe47343
 14 - Resultado: OK.

 15 - Archivo: fs/a_file_15.test
 15 - Se escribio con md5sum: 95666ba29084ed4fb0ea8b983fe47343
 15 - Tras la lectura se obtuvo md5sum: 95666ba29084ed4fb0ea8b983fe47343
 15 - Resultado: OK.

 16 - Archivo: fs/a_file_16.test
 16 - Se escribio con md5sum: 95666ba29084ed4fb0ea8b983fe47343
 16 - Tras la lectura se obtuvo md5sum: 95666ba29084ed4fb0ea8b983fe47343
 16 - Resultado: OK.

 17 - Archivo: fs/a_file_17.test
 17 - Se escribio con md5sum: 37fa2eee16b5241abe896b1d84deecf9
 17 - Tras la lectura se obtuvo md5sum: 37fa2eee16b5241abe896b1d84deecf9
 17 - Resultado: OK.

 18 - Archivo: fs/a_file_18.test
 18 - Se escribio con md5sum: 37fa2eee16b5241abe896b1d84deecf9
 18 - Tras la lectura se obtuvo md5sum: 37fa2eee16b5241abe896b1d84deecf9
 18 - Resultado: OK.

 19 - Archivo: fs/a_file_19.test
 19 - Se escribio con md5sum: c860ad7850e67a58ccee6e6eed561403
 19 - Tras la lectura se obtuvo md5sum: c860ad7850e67a58ccee6e6eed561403
 19 - Resultado: OK.

 20 - Archivo: fs/a_file_20.test
 20 - Se escribio con md5sum: c860ad7850e67a58ccee6e6eed561403
 20 - Tras la lectura se obtuvo md5sum: c860ad7850e67a58ccee6e6eed561403
 20 - Resultado: OK.

Y por ejemplo si lo corro con 100 o 200, fallan solo 10 y el resto andan bien.

Mi idea es que nosotros no dejamos que abra el archivo si se está escribiendo y no se como funcionará este programa, pero si un hilo quiere abrir un archivo y otro justo lo está esribiendo tira error (y es lo qe debería pasar)

Está bien? o lo correcto es que anden siempre todos los hilos?

Para ser mas claro: Nuestro fs servidor, si se abre un archivo (open) con escritura, si no se hace un release, el proximo open para lectura o escritura devuelve error (el archivo esta ocupad)

**Comment by marcogatti** [comment]
Buenas!

> Está bien? o lo correcto es que anden siempre todos los hilos?

Hmmmm, no estoy seguro si viene por ese lado, si miras el codigo del programita [acá](https://github.com/sisoputnfrba/massive-file-creator/blob/master/massive-file-creator.c#L188) vas a ver que cada uno de los archivos creados solo se leen una vez que terminan de ser escritos.

Fijate si hay algun otro motivo por el cual un archivo no pueda ser leido inmediatamente despues de ser cerrado en tu sistema. Particularmente, en el caso de que haya muchos archivos escribiendose y tratando de leerse.

> Mi idea es que nosotros no dejamos que abra el archivo si se está escribiendo y no se como funcionará este programa, pero si un hilo quiere abrir un archivo y otro justo lo está esribiendo tira error (y es lo qe debería pasar)

Justamente acá #581 se esta discutiendo algo parecido, fijate si te sirve.

Saludos!

**Comment by franciscopuyo** [comment]
Genial, gracias por facilitar el codigo. Al final me faltaron semaforos en una lista con archivos abiertos que tengo.

Saludos!
