### ISSUE TITLE
Duda con el OFFSET

### ISSUE THREAD

**Issue by jhonSalazar** [sisoputnfrba/foro#583]
Buenas,

el parámetro que recibe la función READ de FUSE, en este caso el offset, vale 0? Me pasa que en todas las lecturas que hago de los archivos, ése valor no se modifica. Es correcto eso?

Muchas gracias.

**Comment by mgarciaisaia** [comment]
No necesariamente va a valer 0. Si tu archivo es lo suficientemente grande como para que FUSE no lo lea todo en un único pedido, entonces te van a llegar otros pedidos de read con offset mayor a 0.

Si siempre te llegan pedidos de 0 y ves que tu FS no está leyendo completos a los archivos, probablemente te esté ganando retornar la cantidad de bytes leídos en la función read.

**Comment by jhonSalazar** [comment]
Ok,
En principio la idea era recorrer la _tabla de asignaciones_, de esa manera nos va indicar el p_róximo bloque_ y a su vez leer el _bloque de datos_, pero, no tuvimos éxito. A continuación te muestro el siguiente código.

`int osada_read(const char* path, char * buf, size_t size, off_t offset, struct fuse_file_info* fi){

		int tamanio_archivo;
		osada_block_pointer proximo_bloque;
		int nro_bloque=obtain_num_block(path);
		osada_file* p_bloque_datos= inicio_bloque_datos;
		int* p_inicio_tabla_asignacion=inicio_tabla_asignacion;
		osada_file* p_tabla_archivos=inicio_tabla_archivos;
		proximo_bloque=p_tabla_archivos[nro_bloque].first_block;
		tamanio_archivo=p_tabla_archivos[nro_bloque].file_size;

		if(offset < tamanio_archivo){
			printf("el tamanio del offset es :%d\n",offset);
			if(size+offset > tamanio_archivo){
				size= tamanio_archivo-offset;
						memcpy(buf,((char*)& p_bloque_datos[proximo_bloque+proximo_bloque+2])+ offset,size);
					}
		}
		return size;
}`
Ésta es la única manera que por el momento encontramos para leer el contenido de los archivos exitosamente, tanto para el challenge.bin y basic.bin.

Necesitamos saber que es lo que conceptualmente estamos fallando,  alguna sugerencia?.

Saludos.
