### ISSUE TITLE
Massive File Creator en disco sin espacio suficiente

### ISSUE THREAD

**Issue by chrisgel15** [sisoputnfrba/foro#584]
Una consulta, cual es el resultado esperado del Massive File Creator cuando no hay espacio suficiente en el disco?

Deberian crearse los archivos que entren y esos dar como resultado OK y los que no entren no?

Obtengo resultados un poco aleatorios sin espacio, a veces fallan todos y a veces algunos logran crearse bien.

Saludos!

**Comment by marcogatti** [comment]
Buenas! 

Pensa que este programita que crea N archivos *en paralelo* de un tamaño determinado. Que pasa si se llena el disco? Depende de el progreso en la creación de cada archivo. Entonces... Hay forma de saber de antemano cuales se van a crear y cuáles no? 

La respuesta corta es no :)

Saludos!

**Comment by chrisgel15** [comment]
Perfecto! Gracias
