### ISSUE TITLE
Problema al crear directorio con 17 caracteres

### ISSUE THREAD

**Issue by ahufa** [sisoputnfrba/foro#585]
Hola, buen día

Siguiendo con el doc de test, tenemos que probar crear un directorio con 17 caracteres. Al crearlo con 16, funciona perfecto y al hacerlo con 18, tira el error deseado.
El problema se encuentra al querer crearlo con 17, nos tira:
mkdir: no se puede crear el directorio «12345678901234567»: No existe el archivo o el directorio
pero además crea un directorio con el nombre 12345678901234567??@ y no sabemos porque lo rellena con caracteres no deseados que no entendemos su significado.

Gracias por su ayuda!

**Comment by tferraro** [comment]
Buenas!

Están tomando en cuenta el '\0' al chequear el tamaño? Están seguros que el
nombre del directorio llega con el formato de string? [con '\0' al final],
porque tiene toda la forma de este tipo de error.

Saludos!

Tom

**Comment by varas-c** [comment]
Fijate si ésto te es de ayuda. #523
