### ISSUE TITLE
soporte ayudantes presencial

### ISSUE THREAD

**Issue by leandroBenitez** [sisoputnfrba/foro#587]
Buenas noches, queria saber si los ayudantes en general van a estar dando algun tipo de soporte presencial en alguna de las sedes para poder evacuar dudas con respecto a la resolucion de algunos puntos del trabajo practico, ya que bien todos sabemos, solo queda una ultima instancia de presentacion del mismo.
Thanks in advance!
@cecilialuna

**Comment by christianmonasterios** [comment]
Me sumo al pedido de Leandro!

Qué día se podrían hacer consultas puntuales del TP?

Muchas gracias.

**Comment by epreyes** [comment]
Me sumo al pedido

**Comment by MaximilianoFelice** [comment]
Chicos, que tal?

Si todavía necesitan soporte, puedo acercarme hoy a Medrano. 

Les pido por favor que me manden un mail a maximilianofelice@gmail.com para confirmarme y arreglar el horario.

Saludos

**Comment by MaximilianoFelice** [comment]
Buenas again!

Confirmé con @epreyes para estar hoy en Medrano 6 y monedas. Voy a estar dando vueltas por el labo. Cualquiera que tenga ganas de darse una vuelta, es bienvenido.

Saludos!
