### ISSUE TITLE
Duda con TRUNCATE

### ISSUE THREAD

**Issue by fpatalagoity** [sisoputnfrba/foro#588]
Buenas! Tengo una duda respecto de la función. Supongamos que un archivo tiene tamaño de 1500 bytes. Si yo hago truncate de un tamaño igual a 800 entonces, me corta el archivo y al darle cat se abre y está incompleto. Si luego hago truncate de 1000, ¿esos 200 bytes que sobran, deberían ser barra cero? Es decir, si hago cat de ese archivo nuevamente, ¿debería ver lo mismo que vi cuando hice el cat de 800?

Saludos!

**Comment by chrisgel15** [comment]
Segun el documento de pruebas, creo que deberian ser '\0'

![image](https://cloud.githubusercontent.com/assets/11690066/20901881/67dd3d08-bb13-11e6-9ebf-03adb7787775.png)

**Comment by marcogatti** [comment]
Exacto!

Ademas, mirate la documentacion de `truncate` en el manual:

http://man7.org/linux/man-pages/man2/ftruncate.2.html

**Comment by fpatalagoity** [comment]
Gracias! Saludos!
