### ISSUE TITLE
Crear network y testear

### ISSUE THREAD

**Issue by alexsem** [sisoputnfrba/foro#589]
Buenos días, quería consultarles ¿Hay alguna guía o documento de como crear una red con las virtuales? En el laboratorio no tenemos problema conectar las partes del proyecto pero ya que estamos con los test finales necesitamos poder recrearlo cuando queramos y nos estamos rompiendo un poco la cabeza con las configuraciones.

Muchas gracias!

**Comment by gustofa** [comment]
Hola. 
En VM VirtualBox podes configurar un [red NAT](https://www.google.com.ar/?gws_rd=ssl#newwindow=1&q=virtualbox+red+nat).
Sale google a pleno.

**Comment by tferraro** [comment]
Holis,

Profundizando lo que dijo @gustofa, existen varios modos de trabajo de las
interfaces de red que puede usar virtualbox. Las 2 más importantes son
Adaptador
Puente y Red NAT, siendo la primera la que se encuentra configurada en el
laboratorio y la última la que viene por defecto.

No me voy a poner a profundizar sobre las diferencias entre una y otra; más
que nada porque está bastante bien explicado en el 3 link de la busqueda
que paso @gustofa :P.

Saludos!

Tom
​

2016-12-06 23:12 GMT-03:00 gustofa <notifications@github.com>:

**Comment by alexsem** [comment]
Si, el brigde lo probamos pero ni el ping respondia entre las virtuales. Probaremos con la red NAT a ver si funciona.

**Comment by chrisgel15** [comment]
@alexsem  #closed
