### ISSUE TITLE
Duda bloqueo

### ISSUE THREAD

**Issue by juanignaciog** [sisoputnfrba/foro#590]
Buenas, mi duda en realidad es lo que puse en este issue #567 , pero por las dudas lo creo en uno nuevo. Si alguien me lo puede aclarar se agradece.

Saludos

**Comment by varas-c** [comment]
Hola

No es necesario que el entrenador se "bloquee" para terminar su turno en SRDF. Una rafaga SRDF de un entrenador comienza cuando un entrenador empieza a moverse para llegar a la pokenest y termina cuando PIDE capturar. Si captura, termina su turno, si no puede capturar va a bloqueados, por lo que tambien termina su turno, por ende, su rafaga srdf. 

Para cambiar entre algoritmos tenes que esperar a que el entrenador que ya fue planificado (si lo hubiese) termine su turno, es decir, su rafaga.

**Comment by juanignaciog** [comment]
Ah, listo. Si, lo tenia pensado asi, pero cuando vi el issue diciendo que seguia hasta que se bloqueaba me asuste...
Muchas gracias!
