### ISSUE TITLE
Borrar directorios recursivo?

### ISSUE THREAD

**Issue by CarolinaPonceRodriguez** [sisoputnfrba/foro#591]
La consulta es si es necesario que la implementacion del borrado recursivo se encuentre en el codigo en si, es decir, conozco que llevando a cabo el siguiente comando rm -r directorioAborrar este se encarga de invocar a las funciones correspondientes, sea unlink para archivos o rmdir para directorio, verificar si dicho directorio tiene contenido y en tal caso, hacer su magia.
Lo que me estuvo pasando es que si esto lo llevo a la interfaz grafica, cuando elimino un directorio que tiene contenido "se borra", osea, dejo de verlo, pero internamente no hace lo que debe en el caso de los archivos y directorios que se encuentren dentro del mismo(no modifica los estados, ni bitmap para los archivos) de esto me doy cuenta porque si creo un nuevo directorio(de acuerdo a la logica que tengo, agarra el primer registro de la tabla de archivos en 0), a dicho directorio se le "asocia" el contenido del directorio que recientemente habia borrado.
La verdad que hacerla recursiva me esta quemando la cabeza y quiero saber si es totalmente indispensable.

Saludos!

**Comment by chrisgel15** [comment]
Hola,

Lo que entiendo es que en realidad, desde la interfaz grafica, cuando borras un directorio no es lo mismo que hacer "rm -r", es decir, no es recursivo. Si lo probas en el file system de linux, vas a recibir un error de que el directorio no esta vacio.

Entonces, creo que lo que debes hacer es poner un chequeo en el borrado, para verificar que el directorio este vacio, y en caso de no estarlo, devolver el error correspondiente sin borrarlo.

Espero te sirva, saludos!

**Comment by varas-c** [comment]
No falta un parametro para poder borrar directorios que no esten vacios? Proba con rm -rf [Ruta]. Creo que el parametro f es el que te permite borrar directirios no vacios. 

Si haces "rm -rf *" sin comillas, borras todo lo que tengas a partir del directorio en el que estes. Ojo, usalo con cuidado porqhe borra todo.

**Comment by tferraro** [comment]
Buenas!

@CarolinaPonceRodriguez Tal como dicen tus compañeros, `rm` tiene un comportamiento particular cuando se le pasa un directorio. Fijate de probarlo en consola, que casos podes encontrar que requieran flags? Le pegaste una mirada [a como funciona `rm`](http://man7.org/linux/man-pages/man1/rm.1.html)?

Saludos!

Tom

PD: @varas-c como aclaración, el flag `-f` es sinónimo siempre de `dale para adelante igual vieja, yo me banco los trapos sucios`. En este caso el `force` sirve para que ignore el prompt y borre los archivos que no existen o que tienen algún nivel de protección que hace que te pida si de verdad querés borrarlo. Lo que hace que vaya ejecutando los diferentes `unlink` o `rmdir` en el árbol de directorios es que se haga de forma **recursiva** :wink:

**Comment by CarolinaPonceRodriguez** [comment]
Perfecto gracias, pero sigo sin entender algunas cosas. De entrada ya se que rm directorioABorrar si directorioABorrar no es un archivo entonces me arroja el error, si le agrego el flag -r limpia todo, este o no vacio el directorio.
 Por otra parte, si pruebo desde la interfaz grafica de linux con el fs de linux, este me borra el directorio completo que yo le pase, puedo entender que de alguna manera invoca al rm -r .

Ahora, como dice @chrisgel15 "Entonces, creo que lo que debes hacer es poner un chequeo en el borrado, para verificar que el directorio este vacio, y en caso de no estarlo, devolver el error correspondiente sin borrarlo." 
No se si es del todo correcto poner ese chequeo de directorio vacio. Ejemplo, hago rm -r /home/utnso/pepito si mi funcion de borrado de directorio tiene ese chequeo y el directorio tiene contenido, cada vez que se invoque a la funcion de borradoDirectorio recursivamente no va a eliminar absolutamente nada.

O quiza me estoy confundiendo y lo que hace es lo siguiente:
Recibe ese directorio, se fija si tiene algo adentro, tiene.. avanza al siguiente y asi sucesivamente hasta que llegue a las hojas y a partir de ahi comienza a borrar hacia atras, osea, recorrer el arbol de hojas hasta el padre y borrarlo.
La idea era esa para el codigo, no se si especificamente rm -r trabaja asi como explique.

Saludos!

**Comment by mgarciaisaia** [comment]
Eso último.

No te olvides que tenés la compu - podés probar tus teorías.

Por ejemplo, podés implementar unlink y rmdir sin que realmente borren
nada, y ver qué operaciones te ejecuta FUSE cuando hacés un rm -r.

Yo juraría que va a hacerte un getattr a lo que le hayas pedido borrar,
para ver si existe, y de qué tipo es. Si es un directorio, seguramente te
haga un readdir, para ver si está vacío o no. Si lo encuentra vacío, te
llamará a rmdir; si no, va a depender de que tenga el -r o no. Si no está,
te dará un error rm (ni siquiera va a llamar a unlink para que falle,
estimo yo). Si está el -r, repite todo esto para cada archivo contenido.

Pero entiendo que casi nada de esto tenés que implementarlo vos. La mayoría
de esta lógica la resuelven rm y FUSE.

Pero, como siempre: no me creas, probalo. Y contanos cómo te fue.

Un abrazo!

**Comment by tferraro** [comment]
Que tul con esto @CarolinaPonceRodriguez ,pudiste probarlo?
