### ISSUE TITLE
Consulta sobre lectura

### ISSUE THREAD

**Issue by epreyes** [sisoputnfrba/foro#592]
Buenas, la consulta es la siguiente. Tengo un problema con la lectura de archivos que voy creando truncando un .jpg en diferentes tamaños. Con tamaños de hasta 16kb funciona bien pero cuando leo de 32k o mas me tira error de entrada/sailda (haciendo un md5sum)
Estuve leyendo algunos issues relacionados aca, y entiendo que lo que pida fuse es lo que debe darle el servidor. Pero hay casos en los que, por ejemplo si tengo un archivo de 8193 bytes, fuse pide 8192+4096. Es correcto responder 8193 y que la funcion de lectura del cliente retorne 8193 tambien? Este caso de 8193 bytes funciona, aunque no para tamaños mayores.

**Comment by epreyes** [comment]
Actualizo: no estaba haciendo "recv_all", pero aun asi tengo problemas con archivos de mas de 64kb, alguna idea que puede estar limitando?

**Comment by mgarciaisaia** [comment]
Esteban,

FUSE te pide que tu función read devuelva (con un `return`) la cantidad de bytes que _efectivamente_ pudiste leer. Es para casos como este: el loco no se fijó mucho cuántos bytes quedaban en tu archivo, y pidió lo que le pareció correcto. Si tu archivo no tiene tantos bytes, la forma de decirle "no hay más" es con un `return` de menos bytes que los que te pidió.

Fijate si eso ayuda.

Que el MD5 de los archivos difiera significa que los archivos no tienen contenidos exactamente iguales. Y, claro - si estás leyendo mal el archivo, cuando `md5sum` lo lea, va a leer algo distinto a lo esperado.

Un abrazo.

**Comment by epreyes** [comment]
Gracias por la respuesta.
 Ahora el problema es para leer archivos de mas de 64kb. Cuando intento leer un archivo del fs de 66000 bytes, el hash me da diferente con respecto al original (una de las medallas truncadas a 66000 bytes)

El hecho de que el hash sea diferente es seguro que es un problema de que estoy leyendo de forma incorrecta pero me gustaria que me orienten un poco en que podria estar fallando.

Lo que llegue a notar es que en la lectura de 64kb se involucra una sola lectura de fuse (de 64kb) y que en la lectura de 66000 bytes son dos (una de 64kb y otra de 4096bytes). En esa segunda peticion de fuse, solo le devuelvo lo que necesito que serian unos 464 bytes.

Puse logs tanto en el cliente como servidor, y lo que le envio desde el servidor al cliente es esa cantidad de bytes. El cliente recibe tambien lo mismo, (imprimi lo que recv devuelve y lo que la funcion read de fuse devuelve y es 464 bytes)

Algo que no hacia antes era hacer un "recv_all" o "send_all" lo cual ahora me solucciono un problema que tenia con archivos menor de 64kb, pero al pasar el limite de 64kb la lectura da diferente.

Puede que haya alguna configuracion de fuse con respecto a los 64kb? Cabe aclarar que del lado del servidor, en esa 2da lectura (464 bytes), me muevo con el offset que envia el cliente a traves de los bloques, en este caso leo los 464 bytes correspondientes a un offset de 65536 bytes (total 66000 bytes) y la lectura es sobre el/los bloques que corresponde (el siguiente al ultimo bloque que lee la lectura anterior)

**Comment by epreyes** [comment]
Tenia un problema con un malloc, cierro el issue.
