### ISSUE TITLE
Consulta sobre permisos (documento de pruebas)

### ISSUE THREAD

**Issue by chrisgel15** [sisoputnfrba/foro#593]
Estimados,

De acuerdo al documento de pruebas para la seccion de OSADA:

_"El sistema otorga los permisos necesarios a los archivos para que los Mapas y Entrenadores
puedan ejecutar normalmente"_

¿Con que operacion de fuse deberiamos implementar este pedido?

**Comment by mgarciaisaia** [comment]
Christian,

OSADA no es un sistema de archivos que soporte administración de permisos, pero FUSE (por interactuar con Linux) requiere ese concepto.

Entonces, ¿cómo manejar los permisos de un sistema de archivos que no maneja permisos? Bueno, hay que pensar un poco qué permisos son los que existen en Linux, y cuál es su situación en OSADA.

En Linux, se pueden dar o denegar permisos de lectura, escritura y ejecución al dueño de un archivo, a los usuarios del grupo que es dueño del archivo, y al resto de los usuarios del sistema. OSADA ni siquiera tiene el concepto de dueño del archivo, por lo que no puede distinguir entre estas categorías - es decir, los permisos para los 3 grupos van a ser iguales. Quien cree un archivo en OSADA necesitará poder crear archivos en un directorio (es decir, poder escribir en ese directorio), y para saber que existe tiene que poder leerlo - así que vamos a tener que darle permiso de lectura y escritura a todos los usuarios en todos los directorios. De modo parecido pasa con los archivos, con el extra de que, al menos algunos, vamos a querer ejecutarlos, también - así que los archivos deberán tener los tres permisos siempre.

En resumen, el sistema de permisos de Linux no trata sobre qué permisos dar a cada uno, si no, más bien, qué permisos _restringir_ a los usuarios. Un sistema de archivos que no maneja permisos es un sistema de archivos en el que todos tienen permiso para todo.

Sobre cómo implementar esto, FUSE seguramente tenga alguna operación `chmod` o similar, que es la que se usa para cambiar los permisos de un archivo. Pero, dado que recién dijimos que los permisos de cada archivo/directorio dependen únicamente de su tipo, entonces no tiene sentido permitir cambiar esos permisos - descartamos `chmod`.

Ahora... ¿Qué operación es la que cuenta qué permisos tiene cada archivo? ¿Te acordás de alguna que hayas implementado?

Mientras esa operación devuelva siempre los permisos correspondientes al tipo del archivo en cuestión, todo debería funcionar bien.

Un abrazo.

**Comment by alexsem** [comment]
Entonces el set y el get attribute son los que se ejecutan al hacer "ls -l" sobre una carpeta. Al ejecutar el comando me deberia dar siempre lectura y escritura para cualquier directorio y supongo que para los archivos tambien la capacidad de ejecutarlos. Osea que cuando se hace el get attribute se tendria que mostrar los permisos en el archivo como si se hubiera hecho un chmod 777, ¿no?

**Comment by tferraro** [comment]
> Mientras esa operación devuelva siempre los permisos correspondientes al tipo del archivo en cuestión, todo debería funcionar bien.

Mientras que, por ejemplo, no sea un directorio (ponele), permisos de +xrw para todos lo veo bastante acertado. En el caso de un directorio, tendría sentido que sea ejecutable?
