### ISSUE TITLE
Estructura de carpetas y archivos para testear el TP

### ISSUE THREAD

**Issue by alexsem** [sisoputnfrba/foro#594]
Buenas, queria consultar si los archivos y la estructura de carpetas para testear el programa nos lo van a dar en la fecha de entrega del TP. Si es asi, ¿hay además alguna version de prueba que podamos usar?

**Comment by tferraro** [comment]
[faq.utn.so/pruebas-charmander](faq.utn.so/pruebas-charmander)

**Comment by alexsem** [comment]
esta: https://github.com/sisoputnfrba/so-charmander-pruebas
(no lo habia visto)

Listo, gracias!
