### ISSUE TITLE
Problemas con READ - OFFSET muuuuy grande

### ISSUE THREAD

**Issue by fpatalagoity** [sisoputnfrba/foro#595]
Buenas noches! Estamos teniendo problemas con la función READ. Para archivos muy grandes, tal como specials.mp4, hemos detectado que Pokedex Server en su función READ recibe en el 4to pedido un offset muuuuy grande para ese momento y un size mayor a cero, con lo cual **se sobrepasa del archivo**. 
¿Es un caso posible? De ser así, ¿cómo debería tratarse?
Adjunto captura de pantalla para que puedan visualizar mejor lo que ocurre.
![problemaconread](https://cloud.githubusercontent.com/assets/11205541/21070922/778b6036-be6f-11e6-8c02-21f5ace734cb.jpeg)

Muchas gracias!

**Comment by TomasRS** [comment]
O sea tampoco entendemos por qué FUSE apenas manda la orden para leer un archivo, al 4to read ya nos manda un offset que debería mandarse en los últimos reads (porque es muy grande), no en los primeros. ¿Esto depende de nosotros o FUSE manda los offsets como quiere?

**Comment by iago64** [comment]
Tomas, que tal?

La verdad de la milanesa es que FUSE, te va a mandar los pedidos como el crean convenientes (o tambien como se los pida la aplicación que abrio el archivo) por eso es que no deberia asombrarte que te llegue un pedido de los prineros 500 bytes y al toque otro de los ultimos 1000.

Otra cosa a tener en cuenta es que FUSE muy posiblemente haya pedido algo mas grande que el archivo porque en realidad la aplicación que abrio el archivo haya hecho ese pedido asi.

**Comment by TomasRS** [comment]
Buenas, quería comentar que ya pudimos hacer funcionar el read para el mp4. El problema era que estábamos enviando más de 64kb por socket, por lo que al parecer el protocolo TCP no acepta. Así que básicamente partimos los send/recv en menos cantidad de bytes.

**Comment by tferraro** [comment]
Buenas!

Decir que el TCP no acepta paquetes de más de 64kbs es algo incorrecto. Lo
que pasa es que el tamaño máximo del paquete TCP es, efectivamente, de 64k,
pero eso no implica que el protocolo necesite varios send() para enviar
tamaños mayores de 64k, para eso el protocolo TCP tiene la capacidad de
dividir el mensaje.

Lo que les debe estar pasando es que no realizan la verificación de la
cantidad de bytes recibidos o no llamaron al recv con el flav MSG_WAITALL.
Tené en cuenta que el recv puede retornar sin haber copiado la cantidad
total de bytes que vos le pediste, pero te avisa la cantidad que trae con
el mismo. Esto viene de la mano de el funcionamiento de los sockets,
tamaños de buffers y un monton de cosas que no nos importan profundizar.

Peeeero, que quede claro, vos PODES mandar y recibir más de 64Kb, pero
tenés que estar realizando la entrega del mensaje de forma completa y
validar que así sea.

Saludos!​

**Comment by TomasRS** [comment]
Gracias por la respuesta! Es verdad, lo del tamaño era en relación al paquete.
Acabo de aplicarle el flag que mencionaste y sigue funcionando igual, por lo que está todavía mejor porque nos desligamos de tener que dividir el paquete y hacer muchos send/recv, dejamos que se encargue el mismo protocolo.

Saludos.
