### ISSUE TITLE
Consulta sobre formato de timestamp

### ISSUE THREAD

**Issue by fpatalagoity** [sisoputnfrba/foro#596]
Buenas! Tenemos una duda respecto de "Fecha de última actualización" en la Tabla de Archivos. En Valor dice "Timestamp de la última modificación" y tiene una llamada que referencia a `time()`
La consulta es: Cómo deberíamos interpretar esto? Porque la función time devuelve los segundos que pasaron desde X año, según leí. Eso es acorde, creo, al tipo de dato según lo que el enunciado menciona en tamaño porque son 4 bytes, pero nos devuelve un valor que no es de fácil lectura para cualquiera (devuelve segundos desde, no una fecha).
¿Deberíamos usar otra función? En la commons hay una en temporal.h pero devuelve un char* y el tipo de dato de la tabla de archivos es `typedef unsigned int uint32_t;`y para adaptarla, habría que manipular en char* y se volvería medio engorroso.

Saludos!

**Comment by dromero-7854** [comment]
Me sumo a la duda agregando ¿Como se le pasa ese valor en un formato que FUSE lo entienda?

La función getattr le paso el valor asi como viene, pero en la consola no se visualiza la fecha correctamente.

Saludos!

**Comment by mgarciaisaia** [comment]
Hay dos temas "separados" para considerar acá: cómo pide OSADA que guarden las fechas, y cómo pide FUSE que le cuenten las fechas.

Lo de OSADA es lo que dijo @fpatalagoity: guardar el valor como lo devuelve `time()`. Si uno sabe la cantidad de segundos que pasaron desde una fecha determinada, esa es una forma más o menos unívoca de determinar una fecha (hay temitas como los leap seconds y otras cosas raras sobre las fechas, pero para la precisión que necesitamos no nos calientan).

Y eso es todo. En el disco guardan los 4 bytes que `time()` te devuelve, y entonces con eso ya sabés la fecha. Para convertir eso a una fecha _humanamente legible_ tenemos que convertirla a un _string_ con un formato que nos guste. En la sección `See Also` de [la página de manual de `time`](https://linux.die.net/man/2/time) nombran a la función [`ctime`](https://linux.die.net/man/3/ctime), que sirve para convertir ("formatear") fechas. Puede que haya otras (de hecho, las commons seguramente usen alguna en el logger, para mostrar la fecha del mensaje), pero meh. Lo que necesito que quede claro es que la compu _no necesita_ que le formatees la fecha. OSADA te pide que guardes ese `time()`, así como te lo da el SO.

La otra parte de este tema es FUSE. ¿Qué formato de fecha le gustará a FUSE? La función [`getattr`](http://libfuse.github.io/doxygen/structfuse__operations.html#a60144dbd1a893008d9112e949300eb77) dice que hay que llenarle una `struct` de tipo `struct stat`, y no tiene la definición de ese tipo - porque es uno "nativo" de Linux. En [la documentación de la syscall `stat`](https://linux.die.net/man/2/stat) tienen (en la sección "Description") la definición de ese `struct`. Ahí van a ver 3 campos con esta pinta:

```
    time_t    st_atime;   /* time of last access */
    time_t    st_mtime;   /* time of last modification */
    time_t    st_ctime;   /* time of last status change */
```

Es decir, las fechas que pide FUSE (que son las mismas que pide Linux) son de tipo `time_t`... ¡Como las que devuelve `time()`!

¿Será casualidad? :)

**Comment by fpatalagoity** [comment]
Muchas gracias!! :D

**Comment by chrisgel15** [comment]
@alexsem Estamos alineados con esto?
