### ISSUE TITLE
consulta acerca del  RENAME de FUSE

### ISSUE THREAD

**Issue by salva-olacua** [sisoputnfrba/foro#597]
Buenas tengo una duda con la funcion RENAME de FUSE , si hago por consola : 

mv  archivo.txt  nuevoDir/otroArchivo.txt

Si nuevoDir no existe debemos crearlo?, o se tira un error de que el directorio especificado no existe?.
Espero puedan iluminarme, saludos.

**Comment by mgarciaisaia** [comment]
@salva-olacua si hacés eso mismo en el FS nativo de Linux, ¿qué pasa?

**Comment by salva-olacua** [comment]
buenas , en una carpeta cualquiera cree el archivo pepe me movi  a esa carpeta e hice esto:

mv pepe nueviDir/nuevoNombre 

me tiro "no se puede  mover <<pepe>> <<nuevoDir/nuevoNombre>> : no existe el archivo o directorio

y si solo pongo nuevoDir solo sin nuevoNombre me tira permiso denegado.

**Comment by salva-olacua** [comment]
Tambien tenemos la duda de porque rename lanzaria un error de EDQOUT, como lo especifica en la pagina de man.

**Comment by mgarciaisaia** [comment]
> me tiro "no se puede mover <> <<nuevoDir/nuevoNombre>> : no existe el archivo o directorio

¡Exacto! Eso se espera de tu función `rename` - que, si el directorio destino no existe, falle. Es decir, _sólo se pueden mover archivos a directorios existentes_.

Entonces, a tu pregunta original:

> Si nuevoDir no existe debemos crearlo?, o se tira un error de que el directorio especificado no existe?

¿Qué contestarías, ahora [ya iluminado](https://frinkiac.com/meme/S05E13/1118249.jpg)?

> porque rename lanzaria un error de EDQOUT, como lo especifica en la pagina de man

No te olvides que UNIX es un sistema operativo que corre tanto en [celulares](https://www.android.com/), [computadoras personales](http://lubuntu.net/), [servidores compartidos](http://grex.org/connect.xhtml) y [supercomputadoras](http://www.zdnet.com/article/almost-all-the-worlds-fastest-supercomputers-run-linux/). Entonces, así como pasó con las funciones para cambiar los permisos de un archivo (que OSADA no soporta), es de esperarse que algunos de los errores que el manual especifica para una llamada al sistema no apliquen a tu implementación en particular.

En este caso, el error dice:

> **EDQUOT**
>   The user's quota of disk blocks on the file system has been exhausted.

Sería algo así como "el usuario usó toda su cuota de file system", que no necesariamente es "el FS está lleno" - en sistemas multiusuario, el administrador podría determinar que cada usuario no pueda usar más de un porcentaje específico del espacio del disco, o cosas por el estilo.

Así que, en este caso, no aplica.

**Comment by salva-olacua** [comment]
Bastante iluminado ya con esas respuestas, muchas gracias , cierro el issue.
