### ISSUE TITLE
Duda con makefile

### ISSUE THREAD

**Issue by fpatalagoity** [sisoputnfrba/foro#598]
Buenas, estamos tratando de compilar el mapa en la ubuntu server (donde será evaluado el TP) y al hacer make nos devuelve muchos "referencia a 'una funcion' sin definir" pero los .h están bien en el proyecto en Eclipse y en la interfaz gráfica funciona perfectamente. Según pudimos entender, en base al makefile que genera Eclipse debíamos adaptarlo para que la ubuntu server lo tome bien...

El makefile que desde Eclipse ve es:
```
################################################################################
# Automatically-generated file. Do not edit!
################################################################################

-include ../makefile.init

RM := rm -rf

# All of the sources participating in the build are defined here
-include sources.mk
-include src/threads/subdir.mk
-include src/functions/subdir.mk
-include src/subdir.mk
-include subdir.mk
-include objects.mk

ifneq ($(MAKECMDGOALS),clean)
ifneq ($(strip $(C_DEPS)),)
-include $(C_DEPS)
endif
endif

-include ../makefile.defs

# Add inputs and outputs from these tool invocations to the build variables 

# All Target
all: Mapa

# Tool invocations
Mapa: $(OBJS) $(USER_OBJS)
	@echo 'Building target: $@'
	@echo 'Invoking: GCC C Linker'
	gcc -L/home/utnso/git/so-commons-library -o "Mapa" $(OBJS) $(USER_OBJS) $(LIBS)
	@echo 'Finished building target: $@'
	@echo ' '

# Other Targets
clean:
	-$(RM) $(OBJS)$(C_DEPS)$(EXECUTABLES) Mapa
	-@echo ' '

.PHONY: all clean dependents
.SECONDARY:

-include ../makefile.targets

```
Y el error que nos devuelve es:
![make](https://cloud.githubusercontent.com/assets/11205541/21248641/1b0901fe-c317-11e6-81a9-0cc339336d74.JPG)

Si bien ahí no se ve el contenido de las funciones que lanzan error las referencias, puedo ver que `crearArchivoLog` hace sólo uso de funciones de la bibliotea `stdio.h` y las `commons` de la cátedra...

Tratamos de agregar contenido al makefile agregando las bibliotecas en un apartado que vimos que se escribía como `LIBS:=` y no cambió nada. También probamos crear folders y hacer gcc de esas folder luego de la línea `gcc -L/home/utnso/git/so-commons-library -o "Mapa" $(OBJS) $(USER_OBJS) $(LIBS)`
pero tampoco cambió nada. 
¿Nos podrán dar alguna idea de cómo poder seguir?

Gracias!

**Comment by mgarciaisaia** [comment]
Hey, estuvo difícil esta.

Están versionando mal el directorio Debug. En particular, tienen [un `.gitignore`](https://github.com/sisoputnfrba/tp-2016-2c-Chamba/blob/master/Mapa/Debug/src/.gitignore) que hace que no se versionen los `subdir.mk` del directorio `functions/`, que es donde están los .c y .h que definen esas funciones que faltan.

Por eso debe andarles distinto en cada máquina - porque quizá levantan las cosas de eclipse, o quedaron los archivos de alguna versión vieja, o andá a saber.

El `.gitignore` global del proyecto ya ignora los archivos `.o`. Con agregarle que ignore los `.d` y el binario generado de cada compilación (digamos, `Mapa` y los demás ejecutables o shared libraries) deberían poder versionar el resto de las cosas sin problemas.

Por otro lado, fijense qué onda con [esta línea](https://github.com/sisoputnfrba/tp-2016-2c-Chamba/blob/bbf2ff7073cebaa09f659e714745e0bf9ad738ab/Mapa/Debug/src/subdir.mk#L23) que tiene mala pinta:

    gcc -Icommons -Icurses -Inivel-gui -Incurses -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"

Esos `-I` los están mezclando con los `-L` del linkeo. `-I` es para indicarle directorios extra en que buscar los .h que necesite - nada que ver con el `-L`, que indica qué bibliotecas linkear.

**Comment by fpatalagoity** [comment]
Buenas, estuvimos modificando el makefile haciendo lo siguiente y nos sigue tirando lo mismo:
1) Dejamos sin contenido el .gitignore al que hacías referencia en el primer párrafo.
2) Modificamos los -I por -L y -l (ele minúscula) (lo hicimos dos o tres veces con cada uno)
3) En el .gitignore general agregamos dos líneas:
    *.d
    Mapa

¿Hay algo que entendí mal, quizá?
Saludos!

**Comment by mgarciaisaia** [comment]
Mala mía, quedó muy por encima la explicación. Con _ deberían poder versionar el resto de las cosas sin problemas_ quise decir que, una vez que hayan hecho eso, carguen el proyecto desde Eclipse (para que les genere bien todos los makefiles y blah), y ahí van a poder agregar a git los archivos que faltaban.

O sea, la compilación les está fallando porque les faltan algunos archivos que explican cómo compilar el proyecto. _La causa_ de que falten esos archivos es que el `.gitignore` dice que no se versionen. Mi propuesta es que actualicen el `.gitignore` para _ahí sí_ poder agregar a git esos archivos que faltan, y una vez que tengan esos archivos en el repo, cuando los pulleen a la server van a tener todo lo que necesitan para compilar.

El _objetivo último_ es que esos archivos que faltan (los `subdir.mk` de `funciones/` y demás) lleguen a la VM Server. La forma más feliz de hacer esto (para que mañana durante la entrega _también_ lleguen esos archivos) es metiéndolos en el repo.

No revisé mucho más, pero existe la chance de que les pase algo parecido con los demás proyectos. O quizá no - si sólo metieron ese `.gitignore` fantasma en el Mapa.

**Comment by fpatalagoity** [comment]
Bien, ahora hago eso y pruebo, cualquier cosa vuelvo por acá o cierro el issue...
Hasta entonces, gracias!

**Comment by fpatalagoity** [comment]
Vacié todo los .gitignore contenidos en la carpeta Mapa pero sigue igual :/
¿Alguna otra cosa que pueda ser?

**Comment by fpatalagoity** [comment]
Con Entrenador **no** nos pasa lo mismo (compila bien) y los .gitignore tienen contenido... Sospecho que pueda ser algo más...

**Comment by mgarciaisaia** [comment]
¿Sigue siendo el mismo error?

¿En la Desktop compila?

No tengo más info para ayudarte ¯\_(ツ)_/¯

**Comment by fpatalagoity** [comment]
Uh, qué bajón. Sí, en la desktop compila perfectamente.

**Comment by mgarciaisaia** [comment]
Ahí revisé. Desconfío de eso de que en la desktop compila perfecto.

El tema son los `-I` esos que te decía, me parece.

Probá de hacer lo que dice el tuto de http://faq.utn.so/errores-eclipse en la desktop. Por más que no de errores, subí todo el log de la compilación, para ver qué está pasando distinto a la server.
