### ISSUE TITLE
Estructuras para testeo 

### ISSUE THREAD

**Issue by lamasnicolas** [sisoputnfrba/foro#599]
Buenas noches! Estaba viendo los archivos de prueba de : https://github.com/sisoputnfrba/so-charmander-pruebas

Y noté que los mapas no tienen ni puerto ni ip, asumo que debe ser para nosotros completarlas, pero ante la duda pregunto, si estas las agregamos nosotros o son (como en pokedex) variables de entorno.

Gracias, y saludos!

**Comment by tferraro** [comment]
Buenas!

Las van agregar en la entrega misma en los archivos, dado que la IP depende
del labo.

Saludos!

Tom

**Comment by lamasnicolas** [comment]
Listo, gracias!
