### ISSUE TITLE
Tiempo Promedio del Write

### ISSUE THREAD

**Issue by joelmatiassilva** [sisoputnfrba/foro#600]
Hola,

Quisiera saber más o menos el tiempo promedio que les está llevando llenar un disco de 10 MB. ¿Le está llevando más de 15 min?

**Comment by chrisgel15** [comment]
No estoy seguro en el mio, pero fijate si te sirve poner estar optimizaciones que son muy utiles, principalmente la del bitmap: #578 

Saludos y espero te sirva

**Comment by joelmatiassilva** [comment]
gracias @chrisgel15!, hicimos esas mejoras, pero al parecer no nos está dando un resultado óptimo en nuestro caso. 
En si, el gran problema es que estamos haciendo un for de cientos de miles de iteraciones para buscar bit por bit en el bitmap.

**Comment by chrisgel15** [comment]
Pero entonces como implementaron las mejoras? Porque justamente la mejora apunta a que no debas recorrer todo el bitmap para buscar un lugar libre.
Si recordas el ultimo lugar libre, es muy probable que cerca de ese lugar se encuentre el proximo libre, evitando tener que hacer tantas iteaciones como mencionas.
