### ISSUE TITLE
Campera perdida - Charla Turno Tarde

### ISSUE THREAD

**Issue by varas-c** [sisoputnfrba/foro#604]
Hoy en la charla del turno tarde alguien se dejó una campera abajo de un banco que estaba muy cerca del pizarrón. Si alguno estaba sentado en alguna de esas filas, la campera la dejamos en bedelía (en la ventana que esta en la entrada del Campus).

**Comment by jazcarate** [comment]
> Y en el pedestal se leen estas palabras:
> "Soy una campera, reina de reyes:
> ¡Contemplad mis obras, poderosos, y desesperad!"
> Nada queda a su lado. Alrededor de la decadencia
> de estas colosales ruinas, infinitas y desnudas
> se extienden, a lo lejos, las solitarias y llanas arenas
