### ISSUE TITLE
Consulta por Eclipse

### ISSUE THREAD

**Issue by robergto** [sisoputnfrba/foro#605]
Hola gente,
   Os escribo para preguntar por el Eclipse y su comportamiento (el del Eclipse, je). Instalé virtualbox con el disco de Lubuntu. Dentro, seguí las instrucciones para las guest additions, que francamente no tengo idea que son, pero se ve grande la pantalla, así que, genial. Contentísimo, emocionado, digo "oh, haré mi primer hola mundo en Eclipse, en C" al menos para sistemas operativos =D
Cuando toco el martillito, 'xplode'. Me mandó un errwor, y no compiló. Además, el errwor era del makefile ¿?  Me puse a llorar, y dije "dejo la carrera", pero me acordé de uno de los profes en la charla y dije "momento". Así que, traté nuevamente. Esta vez, qué bien, hice el proyecto por default. Noté que viene con una carpeta 'src', que en el video explicativo no estaba. Por lo que la creé, y metí dentro el mismo source que me había tirado errwor. Compiló, andó, y saludó al mundo ¬_¬ Quité el source de la carpeta src, y ¡Maldición! ¡Anduvo sin problemas!
Lo mismo me pasó en Lubunto posta, instalado nativo en una maquinola, con su eclipse y demás. Aunque, ahí el errwor se fue primero por cambiar todo de carpeta, a una sin mayúsculas, y con menos subdirectorios. Después, sin problemas. Al menos el 'Hola Mundo'
Oh, y otra cosa, que también me dejo rascándome, fue que al principio me tiró algo como:
'the selection cannot be launched'
A lo que, en vez de tocar "run" o F11, hice click derecho sobre el proyecto, 'run as' -> C/C++  y ahí saludó también.

Toda lo antedicho para preguntar Le what? ¿Ideas? ¿Alguien puede develar la magia oculta tras el Intetrated Development EnviroNment? ¿Hay algo que hago mal? Al Eclipse lo usé el año pasado, sobre windors, para Algorizzmos. También lo he usado para Java hace unos años. Nunca tuve problemas similares.

¡Muchas Gracias! ¡Buena onda!

**Comment by sebassco-dp** [comment]
Hola!

Podrías reformular la pregunta? No encuentro el motivo de consulta y está bueno que sea también comprensible para todos, en caso de que alguien se encuentre con lo mismo 😉

Saludos!

**Comment by robergto** [comment]
Dale. ¿Por qué haciendo lo mismo en Eclipse, en un momento da error y en otro no?
¿Gracias de nuevo!

**Comment by mgarciaisaia** [comment]
@robertgto, ¡aloha!

Uno de los tantos videos que tenemos linkeados desde _todos lados_ es el de [Cómo reportar errores desde Eclipse](http://faq.utn.so/errores-eclipse). Cada vez que le das "ejecutar", "compilar" o whatever, eclipse ejecuta entre 1 e infinitos comandos. La idea de que sea un IDE es que, justamente, no te importe _tanto_ qué es lo que está haciendo. Pero cuando las cosas van mal, lo mejor para entender es arremangarse, meterse en el barro, y ver qué está pasando "bajo el capó", como diría Maese Ciciliani. Ese video te muestra cómo ver qué comandos ejecutó eclipse, y qué resultados tuvo.

En particular, a mí se me ocurre, por este pintoresco relato que nos regalás, que al principio no anduvo porque habrás creado el archivo como un archivo común y silvestre en vez de como un Source File (y entonces eclipse no lo agrega como parte de la compilación), y en la segunda pasada anduvo porque el proyecto Hello world sí tiene a hello.c (o como se llame) como un source file que tiene que compilar. Una vez que es funcionó, cuando borraste todo y obtuviste _¡Anduvo sin problemas!_... ¿Qué te habrá faltado?

¿Qué paso te olvidaste entre escribir/modificar tu código, y ejecutar tu programa?

¿Qué pudo haber pasado para que funcione?

¡Abrazo de gol!

**Comment by robergto** [comment]
@mgarciaisaia Grazie! Qué buena onda tu respuesta, y que digas 'aloha'
   Say, la verdad, no sé. Y, como bien entendés, pretendo "embarrarme", por eso pregunto. En la charla hablaron de pormenores del lenguaje que me fascinan, y más allá de que pueda ser que compliquen la cosa, lo prefiero. Tanto mejor entender el "malloc" que hacer "new" =D
   Al caso, primero instalé Lubuntu y sus cosas en una máquina física. Entiendo lo de probarlo en el laboratorio y demás, pero también es para mí un desafío, e importante, aprender a utilizar este bello sistema. Sobre todo en lo referido a la línea de comandos y demás. Ya, instalarlo, me llevó un montón de tiempo útil invertido. Así las cosas, seguí (o intenté) el video que está en la página. Digamos, hice el código con sus #include y demás. Valga aclarar que, compilado "por fuera" del Eclipse, con 'gcc hello.c' me tiró un a.out, que al escribir './a.out' me respondió "Hello World!" Así que fue una emoción de la existencia. Aunque lo había escrito en inglés. Si lo traducía solo, salía corriendo =D
   Busqué y encontré que es un bug en eclipse que no sé qué. Poco faltaba para decir que había que suicidarse y reencarnar en Ken Thompson, no digo Ritchie para no faltarle el respeto. Por eso, hice "LO MISMO", pero cambié el directorio, digamos, por uno sin mayúsculas y con menos carpetas anidadas. No sé si fue eso, o lo qué, pero anduvo sin más =P Y, digo "LO MISMO" porque CREO que así fue =D Puede ser que haya hecho algo que no sea un source de C, pero lo dudo realmente, porque no sabría cómo, por un lado. Y por otro, porque usándolo para C++ hacía 'C++ source' (o algo así).-
   Perdón si me alargo, quisiera explicarme bien, aparte que, si bien el tiempo no sobra, el intercambio me gusta. Ysi es pintoresco, tanto mejor =)
   Parecido me pasó con la virtual que manda la cátedra. Primero me preguntó si quería actualizar a Lubuntu 16 =V Pero entiendo que no importa, o sí, pero no cambia el funcionamiento de las cosas. Eclipse, igual las cosas, el mismo (o parecido) error, uno con unos asteriscos [***] Error = 1 o similar, la verdad que no lo grabé. Mal ahí. A lo que, hice el proyecto, pero en vez de vacío, como conté, el ejemplo predeterminado. Como funcionó, y vi la carpeta src, hice lo mismo en el que NO había andado. Una carpeta de soure, donde tiré el mismo archivo (presumiblemente un source, sí, Je). Y ahí sí andó. Curiosamente, y eso me complica más, al quitar el MISMO archivo de la carpeta src y volver a tocar el martillito, sí compiló y saludó =S
   Ah, y en todo eso, pasó lo que dije, que tuve que hacerle 'run' al proyecto, y no al source. Después anduvo sin más.
   CREO que no se me escapa nada =D
   Seguiré, pues, practicando y viendo. Muchas Gracias, again, por la respuesta, la buena onda, el abrazo de gol y el video, que miraré después de contestar un cuestionario de otra materia.

Salutti!

PD. ¿Cómo es el saludo correspondiente a "aloha", say, para irse?

**Comment by iago64** [comment]
Para para para, vos me estas diciendo que instalaste las cosas en una maquina nativa en lugar de la VM? Hubiéramos empezado por ahí hombre! Te nos extendiste en los pormenores del problema y omitiste un detalle importante :(
No tengo ganas de sonar medio policia / inquisidor pero por esas casualidades... que versión de eclipse instalaste? instalaste make? Digo porque me esta empezando a sonar a que te falto alguna cosita dando vueltas y por eso tenes un ambiente a medio construir.
Para hacerte la vida un poquito mas fácil las cosas, te paso parte de un lindo [script de bash](https://gist.github.com/iago64/a5e5b7f6e6cd07b64a46391845fbed34) que en si es la minima base de cosas que te pueden hacer falta (a.k.a: tienen las VM instaladas y que posiblemente esten ahi porque hacen falta). fijate si eso te resuelve alguno de los problemas que estuviste teniendo. 

De todas formas no te olvides de que lo mejor si tenes chances es de usar las VM con el virtual box (porque sabemos que ahí las cosas andan en su gran mayoría bien) y porque es donde mas soporte podemos darte :)

Abrazo!

**Comment by robergto** [comment]
Hey! Tante Grazie iago64.
Instalé ambas cosas, a) nativo b) VM.
De ahí la pregunta, y la cuestión de que me tiró un error parecido que, pensé, estaba cometiendo igualmente. Me animaría a decir que andan las dos cosas ahora, seguí practicando y en la b) VM funcó. También en a) nativo.
Boenísimo el dato del script. en a) Nativa, el Eclipse es la última versión que está en la página. Lamento decirlo, sí, lo hice en modo gráfico =D Instalé, además, Java (para que funque). También instalé build-essential que, según entiendo, puso el gcc y otros elementos indispensables para compilar en C.

Salù!

**Comment by mgarciaisaia** [comment]
¡Aloha!

[Before the beginning](https://www.youtube.com/watch?v=Mdcl1teQG3A), está divertida la pintoresqueada, pero tiene el mismo problema que los [Te Lo Resumo Así Nomás](https://www.youtube.com/channel/UCw7Bz6EHxlnOoBUBlJZCWCw) de [Game of Thrones](https://www.youtube.com/watch?v=QDC5DKSyYcs): cuestan infinito seguirlos. El cuatrimestre recién está empezando, y un poco un byproduct de pasar por este TP es aprender bastante de las buenas prácticas de los programadores (principalmente las que no están relacionadas con el código en sí, si no con _el acto de escribirlo_). Entonces, una de las cosas que espero(amos) que se lleven es cómo pedir ayuda en Internet, cómo reportar errores, cómo buscar la solución a los problemas que se enfrenten. Entonces, joya con la buena onda, pero seamos un poco más expeditivos porfa.

Lo que más nos interesa es ser precisos. _Test your assumptions_. Siempre.

Tratemos de que los _creo_ se conviertan en _hice esto y esto, vi esto otro por acá, y entonces entiendo que eso significa que pasó tal o cual cosa_. Y, si hay un log, mejor. Contando qué entendés que hiciste, qué viste como respuesta, y qué creés que pasó nos permitís ver si lo que entendiste es correcto, si el error estuvo en alguna observación, o si había un mismatch entre lo que creías que tenía que pasar y lo que efectivamente tenía que pasar.

(Hace un par de semanas me leí [esta charla](https://jvns.ca/blog/so-you-want-to-be-a-wizard/) que cuenta muchas cosas piolas al respecto - aunque está en inglés)

La clave de todo tu mensaje de más arriba está en `[***] Error = 1`. Esa es la clave de todo este problema.

**Eclipse es medio idiota a veces.** Como te decía antes, Eclipse usa, _under the hood_, varias herramientas súper estándar (`make`, `gcc`, you-name-it). El error ese `*** Error = 1` es la última línea que muestra `make` cuando _algo falla_ durante la compilación. El problema es que `make` no tiene idea de cuál es el error, porque `make` llama a otros programas (`gcc`, principalmente). Entonces, el error está por ahí, un par de líneas más arriba en el log.

Pero claro, _Eclipse es medio idiota a veces_. Eclipse "lee" el log, encuentra un mensaje de error, y muestra eso en la interfaz. El mensaje que encuentra es `Error 1`, y él no sabe que eso no nos aporta demasiado, así que igual lo muestra.

La solución, como cuento en el video de más arriba (el de Reportar errores, no el de Game of Thrones) es leer el log en la vista Consola de Eclipse. Ahí vas a ver todo lo que `gcc` dijo, y entonces entender qué está pasando.

Ya perdí un poco el hilo, espero haber ayudado.

[_¡Aloha!_](https://en.wikipedia.org/wiki/Aloha)

**Comment by robergto** [comment]
Ayudadísimo, @mgarciaisaia . Muchas Gracias por todo.
Veré, la próxima, de ajustarme más a los mensajes del Eclipse, y guardarlos. Despintoreascaré, pues, mis relatos, así no se hacen tan largos.

Salute!
