### ISSUE TITLE
Cosulta sobre el MarioBash

### ISSUE THREAD

**Issue by GuidoBeltrame** [sisoputnfrba/foro#606]
Buenas tardes, disculpen la consulta por ahi es un poco sencilla pero estuve probando comando con el mario bash pero al intentar realizar el comando MV de todas las formas que eh probado no encuentra los directorios de origen. Me podran dar una mano?

Gracias!
![sin titulo](https://cloud.githubusercontent.com/assets/26509382/24336109/e631a470-125f-11e7-8186-d625e768380c.png)

**Comment by GonzaV** [comment]
Probaste solo con 1.moneda? Fijate si así funciona.

**Comment by GonzaV** [comment]
Definitivamente, con mv 1.moneda cofre funciona, creo que es porque ta estas dentro del directorio donde se encuentran las monedas.

**Comment by varas-c** [comment]
Hola!

No te preocupes si pensas que tu pregunta es "sencilla" o "tonta", todos
estamos acá para aprender y obvio que no hay preguntas tontas, es peor no
preguntar :)

El mario bash es una "consola especial" que capaz no funciona exactamente
como la consola real, pero es muy buena guía para aprender a usarla.

Cuando vos usas "mv", lo que tenes que pasarle como argumentos es "que
queres copiar y donde está" y "a donde lo queres copiar". Por ejemplo mv
[lo que quiero copiar] [a donde lo quiero copiar].

Si vos ya estas en el mundo_nube, podes hacer algo asi "mv 1.moneda cofre".
Esto funciona porque como vos ya estas en el mundo nube, mv va a buscar
"1.moneda" donde estás parado (o sea en el mundo nube) y la va a copiar a
la carpeta cofre que también está en el mundo nube. Lo que vos hiciste en
la consola real de una pc deberia funcionar, pero tene en cuenta lo que te
comenté del mario bash mas arriba.

Si queres saber por qué te funcionó el mv de esta forma, te dejo un link
que te va a servir para entenderlo y para la cursada :)
<http://www.linuxnix.com/abslute-path-vs-relative-path-in-linuxunix/>

PD: Todos los comandos de linux van en minusculas, mv funciona, MV no

Saludos!


2017-03-26 20:08 GMT-03:00 GuidoBeltrame <notifications@github.com>:

**Comment by GuidoBeltrame** [comment]
Grande chicos.. solucionado.. muchas gracias!!

**Comment by CeciliaRodriguez** [comment]
@GuidoBeltrame te encontraste con algún otro problema usando el MarioBash?, lo que te pasa definitivamente es algo a corregir!

**Comment by melaibanez** [comment]
Hola. Para no crear otro issue lo comento acá. Tenia la misma duda que @GuidoBeltrame y pude chequearlo aca :).
Ahora mi duda es que cuando avanzo al mundo_hongo me dice que en /home/luigi hay un mensaje.txt. Voy a al directorio donde se encuentran los personajes y no me aparece luigi :/
Tampoco entendí la consigna "tiene un mensaje.txt en /home/luigi .. host 192.168.05.

**Comment by mgarciaisaia** [comment]
¡Hola @melaibanez!

Un poco tarde, pero recién le dediqué un ratito a esto.

Las instrucciones del nivel dicen:

```
mario@utnso:~/mundo_hongo$ cat instrucciones.txt
[...]
3. Luigi tiene un mensaje.txt en /home/luigi en el host 192.168.0.5 
copialo 
en /home/mario/mundo_hongo (comando SCP), usando las credenciales: 
                        user: luigi
                        password: fusepasion
[...]
```

Es decir, tenés que traerte el archivo `/home/luigi/mensaje.txt` del host `192.168.0.5`, conectándote con el usuario `luigi` - y el password, cuando te lo pidan, es `fusepasion`.

Como querés traerte un archivo de otro host (el `192.168.0.5`) al directorio actual, tenés que usar la segunda forma del comando que te sugiere la documentación: `scp user@ip_host:/ruta_archivo_origen ruta_dir_destino`. Haciendo los reemplazos de esas variables, quedaría algo como `scp luigi@192.168.0.5:/home/luigi/mensaje.txt .`.

```
mario@utnso:~/mundo_hongo$ scp luigi@192.168.0.5:/home/luigi/mensaje.txt .
Password: **********
mensaje.txt                             100%   31      0.2KB/s      
00:00 
```

Fijate que el destino es `.`, es decir, _el directorio actual_. Bien podrías poner `/home/mundo_hongo` en lugar de ese `.`, o incluir el nombre que querés para el archivo resultante (`/home/mundo_hongo/mensaje.txt`).

Algo que MarioBash no acepta, pero que en un `scp` real sí funciona, es usar una ruta relativa para indicar el archivo remoto que quiero traer. Como la home de `luigi` en ese host está en `/home/luigi/`, es válido (y equivalente) el comando `scp luigi@192.168.0.5:mensaje.txt .`. Es decir, después del `:`, poner la ruta relativa al home del usuario en el sistema.

Perdón por la demora 😇
