### ISSUE TITLE
Actualizar carpeta local

### ISSUE THREAD

**Issue by Shupacabras** [sisoputnfrba/foro#607]
Hola a todos, tengo una duda, soy usuario linux y sigo una aplicacion cada 2 o 3 dias abro un terminal y ejecuto

`git clone git://git.XXXXXXX/XXXXX` 

pero para eso debo borrar mi carpeta actual 

Existe alguna forma de descargar solo los cambios para no tener que descargar todo de vuelta?

Saludos cordiales.

**Comment by jazcarate** [comment]
`git pull` es tu hombre.
Podrías leer [la documentación](https://git-scm.com/docs/git-pull), pero rápido y pronto sería: `git pull` dentro del repositorio (no hace falta poner la URL, porque ya está clonado).

**Comment by Shupacabras** [comment]
Perdon, corri el comando git --help pero no logre entender, gracias por la data

**Comment by jazcarate** [comment]
Si sentis que tu pregunta fué resuelta; no olvides apretar el botón de un chiquito más abajo --> [Close]

**Comment by Shupacabras** [comment]
Solucionado - Solved muchas gracias
