### ISSUE TITLE
Problema para confirmar equipo

### ISSUE THREAD

**Issue by GonzaV** [sisoputnfrba/foro#609]
Hola!

Perdón por la molestia, pero mis compañeros y yo estamos teniendo problemas para confirmar el equipo. Estando ya completo y con toda la información que requiere, simplemente no nos deja confirmarlo.
Adjunto una imagen, si es que sirve de algo. Agradecemos cualquier ayuda.

Muchas gracias. Saludos!

![error grupo](https://cloud.githubusercontent.com/assets/26558890/24385382/2c46fe7a-1340-11e7-80a6-e48cd55f5ed8.jpg)

**Comment by mgarciaisaia** [comment]
Uno quisiera creer que en el 2017 ya no existen estos problemas, pero si [todavía no se puede crear una carpeta llamada `CON` en Windows](http://www.hoax-slayer.net/cannot-create-windows-folder-named-con/), ¿por qué no ibamos a tener problemas de escapeo en nuestro humilde sistema?

Llamarse `c o u t << "q e p d";` es un acto de coraje más grande que [el de sacarle el jack de audio al iPhone](http://www.theverge.com/2016/9/7/12838024/apple-iphone-7-plus-headphone-jack-removal-courage). Probablemente el Sistema de Inscripciones no esté feliz con los caracteres raros que le hayan clavado al nombre del grupo.

Les sugeriría probar con algún nombre más estándar, incluso a costas de perderse un chiste interno el resto del cuatrimestre.

El nombre del grupo es tan bizarro que su repo se terminaría llamando `-`:

<img width="274" alt="screen shot 2017-03-28 at 10 44 54 am" src="https://cloud.githubusercontent.com/assets/1190974/24396500/ae55aaa2-13a3-11e7-9caf-bfef2eaa3638.png">

Nada - punto por la creatividad, pero amíguense con el sistema ¯\\\_(ツ)\_/¯

¡Un abrazo!

**Comment by yankkok** [comment]
Hola, como estas?

Seguimos con el problema! Pero nos dimos cuenta que no tenemos ninguna función que, funcione. No podemos cambiarle el nombre, y no podemos sacar a nadie del grupo. Esta roto :(.

Mil disculpas por las molestias, y gracias por la rta.

Saludos,
Ignacio Javier Fernández Soto

**Comment by yankkok** [comment]
Buenas noches.

Disculpas si revivo el post, pero estamos un poco nerviosos ya que se envió el TP y este sábado es la charla. Lo único que solicitamos es que se nos cambie el nombre del grupo, así podemos estar tranquilos.

Mil gracias! Y disculpas.

Saludos,
Ignacio Javier Fernández Soto

**Comment by sciciliani** [comment]
Podrian solicitar confirmación nuevamente? Ahi les cambiamos el nombre del
grupo

2017-03-28 22:30 GMT-03:00 yankkok <notifications@github.com>:

**Comment by yankkok** [comment]
Se rompió todo, no hay chance. Todas las funciones son inutilizables.

Reitero, gracias por la buena onda y disculpas por las molestias ocasionadas.

Saludos,
Ignacio Javier Fernández Soto

**Comment by sciciliani** [comment]
Intenten una vez mas por favor.

2017-03-28 23:36 GMT-03:00 yankkok <notifications@github.com>:

**Comment by GonzaV** [comment]
Solucionado, muchas gracias!
