### ISSUE TITLE
Problema en la iscripcion

### ISSUE THREAD

**Issue by fedeGiussa25** [sisoputnfrba/foro#610]
Hola, estoy tratando de inscribirme pero cada vez que pongo "Crear Nuevo Usuario", la ventana se cuelga y no hace nada. La foto que seleccione es de las dimensiones y tamaño que pide así que ese no es el problema.

**Comment by elepantQuito** [comment]
Me pasa exactamente lo mismo, no me deja inscribirme.

**Comment by tferraro** [comment]
Buenas! 

Efectivamente hay un problema con el sistema de inscripciones, pero no se preocupen! Estamos en proceso de solucionarlo, en breve se van a poder inscribir sin problemas, cosas que pasan ¯\_(ツ)_/¯

![image](http://www.chicadelatele.com/wp-content/uploads/2010/03/technicaldifficultieswp6.jpg)

**Comment by tferraro** [comment]
Me cuentan por la cucaracha que estamos online de nuevo!

Y deberían poder inscribirse. Si sigue habiendo algún problema nos avisan :wink:

**Comment by MaximilianoFelice** [comment]
El problema quedó solucionado. Las inscripciones vuelven a estar activas!
