### ISSUE TITLE
Consulta sobre charla introducción a TP 1/04 

### ISSUE THREAD

**Issue by gonziesc** [sisoputnfrba/foro#616]
Buenas! la charla sobre la introducción del TP y de introducción a Sockets es solamente en Campus?
Se recomienda llevar notebook o no hace falta?
Saludos!

**Comment by tferraro** [comment]
Holis!

Si, las charlas son en un único lugar, y dado que Medrano está casi completamente en obra, no hay chance de que consigamos siquiera un lugar para desdoblarla.

No hay necesidad de llevar notebooks, no tenemos programado un workshop :smiley: 

Byes!

**Comment by iago64** [comment]
Buenas!, Buenas?

Sumado a lo que dice Tom, no es necesario que lleven las notebooks pero si tienen algún problema con la VM o con algo del workshop de C pueden traerlas y en algún ratito libre lo vemos. :)

Saludos.-
