### ISSUE TITLE
Problema make: *** No hay ninguna regla para construir el objetivo «all».

### ISSUE THREAD

**Issue by guillelle** [sisoputnfrba/foro#617]
hola, 

estuve probando cosas y tengo el problema mencionado en el asunto cuando hago build con el botón del martillo, sumado a eso no me genera el Binary. Para asegurarme que no fuera un error de código reduje el mismo a lo siguiente y sigue dándome el mismo error

saludos

#include <stdio.h>
#include <stdlib.h>

int main(void) {
	printf("Hola");
	return EXIT_SUCCESS;
}

**Comment by guillelle** [comment]
hago una aclaración porque quizá por ahí venga el problema, pero no se que estoy haciendo mal. Este proyecto lo creé en otra computadora, lo subi a github y en lo cloné en la PC que tengo este problema, si mal no recuerdo en la PC que lo generé no tuve problemas.
Quizá lo importé mal, estoy probando variantes de importación pero si alguien tiene la posta se lo agradezco

saludos
Guille

**Comment by varas-c** [comment]
Hola!

Si creas un proyecto tuyo local, funciona? Es decir, el unico que tiene
problemas es el que clonaste pero los que vos creas en tu compu si
funcionan?

En caso afirmativo, capaz importaste mal el proyecto en tu eclipse o algo
pasó. Probá con ésto a ver si te sirve:

1- En el eclipse, fijate el menu izquierdo donde esta tu proyecto (Project
Explorer), dale click derecho a tu proyecto y seleccioná propiedades.
2 - Seleccioná la opcion C/C++ Build y seleccioná la opcion "Generate
MakeFiles automatically".
3 - Dale aceptar a los cambios, reiniciá el eclipse y probá compilar de
nuevo.

Si no te sirve, avisanos!

Saludos!

**Comment by jazcarate** [comment]
@guillelle ¿Pudiste con esto?

**Comment by nrmerlis** [comment]
Hola, yo tenia el mismo problema que @guillelle y me sirvió hacer lo que dijo @varas-c .
Gracias.

**Comment by varas-c** [comment]
@nrmerlis genial!

**Comment by candezunino** [comment]
Tengo un problema parecido y no se me resolvió con lo que puso @varas-c , me dice que no encuentra el binario y en los errors me aparece lo siguiente:
make: *** No hay ninguna regla para construir el objetivo «Kernel.o», necesario para «Kernel».  Alto.

**Comment by tferraro** [comment]
Holis!

@calvoluciano seguramente es algo de configuración del proyecto de Eclipse. Probablemente tratar de ver cual es el problema y solucionarlo online lleve un tiempito, así que te propongo algo: Dado que estamos a Viernes, fijate si te podes [pegar una vuelta mañana por la Facu](http://faq.utn.so/soporte) a ver si le encuentran la vuelta con los chicos.

MIentras tanto, sigamos con tu pregunta, en que orden aparecen las carpetas en tu proyecto?

Saludos!

**Comment by candezunino** [comment]
Dentro del Kernel las tengo asi: Includes,Debug,src
Saludos

**Comment by tferraro** [comment]
Tratando de ser simplista, se me escapó un poco la tortuga. Me refería a cual era tu estructura de los directorios, más que nada para descartar que el makefile esté bien generado.

**Comment by mgarciaisaia** [comment]
http://faq.utn.so/errores-eclipse

**Comment by candezunino** [comment]
Ya lo solucione, pueden cerrar el issue. Gracias.

**Comment by nicozar95** [comment]
¿Que paso?¿Que era?

![image](https://cloud.githubusercontent.com/assets/11698687/24832700/b8b1e2c2-1c8b-11e7-8f82-e5e8fe4e90f4.png)

**Comment by candezunino** [comment]
Había un problema con la shared library, estaba mal puesto el path para Debug
