### ISSUE TITLE
ayudante asignado y como arrancar

### ISSUE THREAD

**Issue by gonziesc** [sisoputnfrba/foro#618]
Buenas! Dado que en 12 días ya tenemos nuestro primer checkpoint, tengo un par de consultas:
1. Más o menos, cuando vamos a tener ayudante asignado?
2. Como para ir arrancando, cada proceso se hace en un proyecto diferente, correcto?
Saludos!

**Comment by tferraro** [comment]
Buenas!

1. Calculale que en aproximadamente 1 semana, recién ayer/hoy están cerrando las inscripciones de los grupos.
2. Yep :smile: 


Saludos!

**Comment by gonziesc** [comment]
Gracias!
