### ISSUE TITLE
Proceso CPU - Configuración

### ISSUE THREAD

**Issue by fedeGiussa25** [sisoputnfrba/foro#619]
Nos dimos cuenta que en el enunciado del TP el proceso CPU no posee especificación de algún archivo de configuración (.config), por lo que no tiene forma de saber a que puerto conectarse, ni tampoco la IP del proceso kernel. La CPU debería de leer su archivo de configuración para obtener dichos datos, verdad?

**Comment by nicozar95** [comment]
Buenas

Esta la posibilidad de ~~que nos lo hayamos olvidado~~ pero cito a @afilgueira que dijo en algun tp lejano:

> Hola, los archivos de configuracion del TP son a modo de ejemplo. Uds son libres de adaptarlos como crean conveniente.

Lo mas probable es que necesites un archivo de configuracion para conectarte al proceso memoria y al proceso kernel, adaptandolo como sea conveniente.

**Comment by fedeGiussa25** [comment]
Ok perfecto, entonces creamos un archivo de configuración para cpu con los datos para la conexión con kernel y memoria.
