### ISSUE TITLE
Duda SEM_IDS del proceso Kernel

### ISSUE THREAD

**Issue by fpatalagoity** [sisoputnfrba/foro#620]
Buenas, a la hora de leer el archivo de configuración del Kernel, SEM_IDS dice  "identificador de cada semáforo del sistema. Cada posición del array representa un semáforo". Si estoy en lo correcto, no tiene mucho sentido considerar cada elemento como un char* (es decir "SEM1", por ejemplo) porque no es lo que representa. Creo que en realidad es el atributo ID del pthread. Entonces, primero, ¿estoy en lo cierto si digo que es ese atributo? En ese caso, ¿existe alguna función de la biblioteca pthread que sirva para setear el ID de dicho semáforo?

**Comment by mgarciaisaia** [comment]
:wave: Las commons soportan un array como valor de configuración. La sintaxis es la que muestra el ejemplo de archivo de configuración más adelante en el enunciado (o, si no, también podes buscar los specs del TAD de config, que tiene al menos un array de ejemplo).

La idea de este campo es que listes los nombres de cada uno de los semáforos que existen en tu sistema, dado que el Kernel tiene que inicializarlos cuando arranca. Hay, además, otro campo de la configuración en que se indica el valor con que inicializar cada uno de esos semáforos.

La explicación habla de identificador porque el nombre este que le des a los semáforos acá va a ser la única forma que va a tener el código AnSISOP para referenciar al semáforo y, por consiguiente, de operar con él. Los nombres de los semáforos no se pueden repetir en este sistema, y por eso se los llama identificadores.

No te olvides de que esto está hablando de los semáforos que el sistema que tienen que crear va a exponer a los Programas AnSISOP - no tiene relación directa con los semáforos de Linux/POSIX, más allá de que representan un concepto similar. Es decir, no necesariamente tienen que usar semáforos POSIX para implementar los semáforos de su TP.

**Comment by fpatalagoity** [comment]
Creo haber entendido, gracias!! :D
