### ISSUE TITLE
Duda sobre Sockets

### ISSUE THREAD

**Issue by ngrosso** [sisoputnfrba/foro#621]
Que tal chicos, estuve jugando con el manual de beej de sockets y use su codigo fuente para crear un servidor y un cliente basico con el hola mundo, cuando levanto el servidor en la consola me queda: 
`Waiting for connections...`
 buenisimo, ahora cuando ejecuto el cliente dandole la ip que me aparece en `ifconfig` la cual es 127.0.0.1, el cliente me devuelve 
`error: Connect failed` 
Siento que es algo re estupido que me estoy comiendo... que es?

fuente del Cliente: http://beej.us/guide/bgnet/examples/client.c
fuente del Servidor: http://beej.us/guide/bgnet/examples/server.c

**Comment by nicozar95** [comment]
Buenas

Estoy casi seguro que el error es en la funcion `connect()`, la cagada de esta funcion es que si falla te tira -1 y no te dice nada mas ... sin embargo hace una vuelta de tuerca mas que hace antes de terminar

> On error, -1 is returned, and errno is set appropriately. 

Sacado del man, esto me dice que si tengo declarado algo como esto en tu codigo

`#include <errno.h>`
`int errno;`

La funcion me va a setear esa variable a el error correspondiente, los errores que te puede tirar connect son 15, que estan todos detallados en el man. Podrias chequear el valor de errno para saber que es lo que esta pasando antes de que se cierre el socket.

Me baje tu codigo, lo corri y me anda, asi que de seguro es un error de la maquina y no tuyo :smile:.

**Comment by ngrosso** [comment]
El error que me devolvia era el `Connection refused errno=111` y era que  el cliente se queria conectar al puerto equivocado. Le tuve que cambiar esta linea al cliente 
`serv_addr.sin_port = htons(5000);` por esta `serv_addr.sin_port = htons(3490);`
ya que en el servidor decia `#define PORT "3490"  // the port users will be connecting to`
esta bien no? nada va a explotar? me parece raro que vos @nicozar95 bajando el codigo y corriendolo de una te haya funcionado

**Comment by nicozar95** [comment]
No creo que explote, solo le cambiaste el puerto a conectarse, en el ejemplo que subiste el puerto donde se pone a escuchar el servidor es el 3490 ¿Me pasaste el mismo ejemplo que estabas usando? 

Una de las magias de C (o desgracias) es que al manejarse a tan bajo nivel, no corre en un ambiente "protegido" como una VM, que lo abstrae de los problemas del sistema operativo y el hardware, permitiendote hacer locuras con las memorias de tu computadora y demas, pero:

> Un gran poder conlleva una gran responsabilidad.

Esto hace que vos te choques con esos problemas y ha veces el mismo codigo puede no andar en maquinas distintas (puede ser por limitacion de RAM, por ejemplo) **por eso es muy importante que antes de la entrega final prueben su programa en el Ubuntu server**

**Comment by ngrosso** [comment]
Listo, se me habian escapado un par de lineas de otra guía, cierro, moraleja, tener cuidado con los puertos, gracias!
