### ISSUE TITLE
Sobre lectura de firmas de funciones

### ISSUE THREAD

**Issue by kevenvarela** [sisoputnfrba/foro#622]
Hola, me gustaria si pueden explicar como se leen las firmas de las funciones, muchas gracias.

Dejo algunos ejemplos

```
char* string_concat(const char*, const char*);

void mail_split(const char* mail, char** user, char** dominio);
```

(Son ejemplos tomados de [https://docs.google.com/document/d/1n_u1E8uKzExstQEJR_lJBBsT0P5Ru9kG-yW5VUiYnLs/edit#](url) )

**Comment by tferraro** [comment]
Holis,

Veamos, vamos por partes:

- La palabra `const` hace alusión a que lo que estás pasando no va a ser alterada dentro de la función. En este caso, como estás pasando una variable **por referencia**, estás diciendo que al valor al que apunta no va a ser modificado. No sirve más que para ser expresivos y para que, si se da el caso, el compilador pueda hacer optimizaciones sabiendo de antemano que no vas a modificar el valor.
- El retorno void, dado que las funciones en C siempre tienen que tener un retorno, se lo utiliza para detallar que lo que devuelve es, justamente, nada.
- Finalmente el `char **`. Un operador * doble significa que necesitás pasarle la referencia a un puntero que apunta a un char. Esto claramente no tiene mucho sentido así suelto, así que te paso un ejemplo más práctico de la función que pasaste:

Tenemos el string "hola@utn.so", que en C como no existen los strings, se lo representa como un `char*` que termina en `/0`. Por el nombre, tu función debe dividir el mail en el usuario y el dominio, pero como sabemos de antemano, el valor de retorno de las funciones en C es único, así que existen 2 caminos a tomar: o devolvés una estructura (o algo similar, una dupla de valores) ooo haces el famoso *te lo paso por referencia* para que lo que apunte ese puntero, si se modifica, sea accesible por fuera de la función.

Por lo tanto, podríamos decir que si tenés los literales `mail = "hola@utn.so"`, `usuario` y `dominio`, deberías invocar a la funcion pasandole los últimos 2 por referencia:

```
mail_split(mail, &usuario, &dominio);
```

De esta forma, luego de ejecutar la función si consultas los valores de la seguidilla de chars deberían ser **hola** y **utn.so**.

Para el caso de la primera función, siguiendo los lineamientos que dije antes, tu función estaría devolviendo un string y recibiendo 2 strings que te asegura que no va a modificar. Dado que se llama string_concat, seguramente el valor de retorno sea la concatenación de los carateres de los strings que le pasaste.


Cualquier cosa que te haya confundido más, chifla :stuck_out_tongue: 

Saludos!

**Comment by mgarciaisaia** [comment]
:wave: Para ir entrenándose/auto-corrigiéndose, [cdecl](https://cdecl.org/) es tu amigo:

[`char* string_concat(const char*, const char*)`](https://cdecl.org/?q=char*+string_concat%28const+char*%2C+const+char*%29)

Aunque `void mail_split(const char* mail, char** user, char** dominio)` y no se por qué (¿será un bug?).

¡Salute!

**Comment by kevenvarela** [comment]
Muchas gracias @tferraro  y @mgarciaisaia

**Comment by iago64** [comment]
@kevenvarela Kevin, que tal, tu pregunta fue respondida correctamente? se puede cerrar el issue?
