### ISSUE TITLE
Estructuras Administrativas de la Memoria

### ISSUE THREAD

**Issue by emanuelmartinez** [sisoputnfrba/foro#623]
Buenas, como va?

Estamos viendo de cómo crear las estructuras administrativas al crear el proceso memoria.

Vamos a tener 500 elementos de una lista conformada por:
-#Frame
-PID
-#Pag
Que podrían ser int de 4 bytes cada elemento. En total cada elemento será de 12 bytes.

Entonces si tenemos 500 elementos vamos a tener 6000 bytes. Si cada marco es de 256 bytes, tendremos 24 marcos.

Por lo tanto, nosotros concluimos que utilizaremos esos primeros 24 marcos para la estructura administrativas y tendremos disponibles 476 marcos para la memoria de los procesos.

Estamos bien encaminados? O no estamos entendiendo bien cómo manejarnos?

Muchas gracias!
Saludos,
Emanuel

**Comment by mgarciaisaia** [comment]
Asumiendo que tu archivo de configuración dice que tenés 500 marcos de 256 bytes cada uno, lo que pensaron es correctísimo.

Si los números fueran otros, buen, cambian un poco las cuentas, pero la base es la misma.

No recuerdo si explicitamos algo sobre qué pasa si el tamaño del marco no es múltiplo del tamaño de la estructura. En principio, me parece que no tiene sentido requerir que cada estructura esté en un único frame (porque en ningún caso manejás al frame individualmente, ¿o me estoy olvidando de algo?). Pero sí tiene sentido que no haya frames que tengan tanto estructuras administrativas como datos de usuario. Bah, capaz no es algo super importante en este caso, pero sí es algo que deberíamos ponernos todos más o menos de acuerdo y dejar explícito en el enunciado.

¿Se les ocurre algo al respecto?

**Comment by marcelocejas** [comment]
Hola Matias, soy parte del grupo de Emanuel, se entiende perfectamente y creo que la solución sería suicidarse. Pensando en ese extremo tambien podriamos pensar el valores que nos dejen apenas un par de marcos para trabajar. 
La verdad es que se me ocurre el caso de una PC que solo tiene espacio de memoria para el SO, o sea, no serviría para mucho me aperece, yo diría que no tiene suficiente memoria para procesar nada.

**Comment by iago64** [comment]
Marcelo, tampoco para llegar al extremo de suicidarse, sino muchos de los que usamos windows vista tendríamos que haberlo hecho.

Ahora Emanuel va encaminado perfectamente, ahora digo, si necesitan ahorrar espacio, no tienen alguna forma de hacerlo?
Para manejar ese tema, pensá en que cosas son las que pueden pasar? que no te quede espacio para ejecutar programas? no podes simplemente decirle, no tengo espacio disponible?

No traten de buscarle la 5ta pata al gato, paren la pelota y vean que es lo que tienen que hacer, no pierdan el objetivo que es presentar una plataforma para ejecutar "programar" AnSISOP.

**Comment by emanuelmartinez** [comment]
Chicos, muchas gracias por sus respuestas! 

Cierro la Issue!

Saludos,
Emanuel

**Comment by mgarciaisaia** [comment]
> Hola Matias, soy parte del grupo de Emanuel, se entiende perfectamente y creo que la solución sería suicidarse.

_🎵 No te pares, no te mates: solo es una forma más de demorarse🎵_

> Pensando en ese extremo tambien podriamos pensar el valores que nos dejen apenas un par de marcos para trabajar.

Correcto. Es una posibilidad, sí. Hoy tenemos GBs de RAM en prácticamente todas las computadoras, pero eso no quita que puedas [instalar software en hardware con los requerimientos mínimos](https://www.youtube.com/watch?v=g84Jq1HRMbY). La utilidad de hacer tal cosa es _súper_ discutible (digamos, _no querés_ usar eso para trabajar/estudiar/huevear en tu día a día, pero puede tener valor "académico", experimental, o simplemente hacerlo _porque sí_), pero ese no es problema del software/sistema, si no del usuario que lo intenta.

> La verdad es que se me ocurre el caso de una PC que solo tiene espacio de memoria para el SO, o sea, no serviría para mucho me aperece, yo diría que no tiene suficiente memoria para procesar nada.

Es una observación muy buena, en efecto. Si una de las responsabilidades principales de un sistema operativo es administrar programas de usuario, un sistema operativo que no deja lugar para programas de usuario no parece muy útil.

Aún así, si sos _el desarrollador del sistema operativo_, puede tener sentido hacer esa prueba, a ver cómo se comporta tu sistema en situaciones "desfavorables". Todo desarrollo tiene sus limitaciones. En este caso, una limitación de este esquema de administración de memoria es que, para ciertos tamaños de memoria, la proporción memoria útil/memoria total va a ser malísima.

En un sistema real, contarías los requisitos _mínimos_ de hardware para tu sistema, y los _recomendados_. En el caso del TP, miralo por el otro lado. Por lo general, uno no tiene la posibilidad de cambiar fácilmente la configuración de su computadora para probar el sistema con 21MB de RAM, después con 38MB, después con 2GB, y así. En el TP cambiás 2 números y podés hacer experimentos para ver cómo se comporta el sistema :)

Y ese es otro de los objetivos que estamos tratando de deslizar en los enunciados: que sirvan de "laboratorio". Que en la teoría les cuenten que el algoritmo de planificación _sarasa_ funciona mejor cuando hay muchos procesos verdes con pintitas amarillas, pero que se comporta peor que tal otro algoritmo cuando el día está soleado... y ustedes puedan probarlo. No subestimen el valor de tener la compu y poder probar las cosas en lugar de simplemente creerle a alguien que lo dice. No por desconfiar de Adro, si no por el ejercicio de probar, observar, sacar conclusiones, proponer alternativas que quizá puedan mejorar algún aspecto que les interese, volver a probarlo y ver si eso trajo algún otro costo oculto, decidir si les importa o no.

A eso nos dedicamos, un poco :)

¡Un abrazo!
