### ISSUE TITLE
Cuales son los archivos que podemos meter al gitignore?

### ISSUE THREAD

**Issue by mdb1** [sisoputnfrba/foro#624]
Es conveniente incluir esto en el .gitignore ademas de los que vienen por defecto?
Debug/
Workplace/
*.metadata/
.metadata/
*.log
Se pueden tambien sacar los .project y .cproject? O esos son necesarios para el repo?

**Comment by alkchofa** [comment]
Buenas, alguien ya lo preguntó aca [#220](https://github.com/sisoputnfrba/foro/issues/220)
Al final del issue @mgarciaisaia te da la respuesta.
