### ISSUE TITLE
Archivos de configuracion

### ISSUE THREAD

**Issue by ivanedh** [sisoputnfrba/foro#625]
Buenas, tengo dos consultas:
En el archivo de configuración del Kernel no hay ningún parámetro que indique la IP por la que recibirá nuevas conexiones. ¿Podrían adelantarnos cual seria el nombre del parámetro? ¿O se debe resolver de otra forma? Y la segunda es acerca del CPU, en este proceso no hay apartado asociado al archivo de configuración, entiendo que al menos serian necesarios IP/PORT para Kernel y Memoria, ¿Me estoy olvidando algo mas?

**Comment by iago64** [comment]
Ivan, que tal?
Todo lo que nosotros no aclaremos uds pueden definirlo como consideren (por ej el archivo de config de la CPU)
De hecho los archivos de config el día de la entrega los arman Uds como parte del deploy.

Saludos.-

**Comment by ivanedh** [comment]
Muchas gracias, saludos

**Comment by mgarciaisaia** [comment]
¡Aloha!

Solo quería agregar una aclaración a lo que dijo Dami: agreguen lo que necesiten a los archivos de configuración, pero **siempre** consulten con sus ayudantes designados a ver si no se están perdiendo algo.

En este caso no pusimos la IP del Kernel porque, dado que es el servidor, no le calienta por qué IP escuchar - escucha todas las que tenga disponibles esa máquina, y ya. _Se puede_ especificar una única IP, por lo que _podrían_ agregar eso en el archivo de configuración, pero definitivamente es algo que no vamos a querer hacer en el TP.

No se ensarten ni se compren más laburo del que ya tienen :)

¡Un abrazo!

**Comment by ivanedh** [comment]
Sinceramente, no habíamos encarado "conexiones", solo los metadatos y me pareció que iba a ser necesario, cuando Levante el Server entendí pq no estaba en el archivo.

**Comment by mgarciaisaia** [comment]
Alguna otra enseñanza puede haber en eso, aunque capaz es muy madrugada para que la note (:
