### ISSUE TITLE
archivos configuracion

### ISSUE THREAD

**Issue by feldespatos** [sisoputnfrba/foro#626]
Hola!
Quería saber si es absolutamente necesario recibir por parámetro la configuración del proceso o si se puede llegar a implementar alguna alternativa.
Saludos.

**Comment by alkchofa** [comment]
Buenas, no se si entiendo tu pregunta. 
Cada módulo tiene un archivo de configuración que indican ciertos valores q pueden variar como pueden ser los IPs, puertos, etc. 
Te referías a eso? Que alternativa se te ocurrió?

**Comment by feldespatos** [comment]
Si, me refiero a eso. Van a variar? Podríamos hardcodear la ruta del archivo y no recibirlo por parámetro.

**Comment by tferraro** [comment]
Holis, no hay penalización por que hardcodeen la ruta, siempre y cuando
sepan donde su sistema va a ir a buscar sus archivos de config. Se te
ocurren los pros y contras de hardcodear la ruta o pasarla como parámetro?

Tl;dr: Es un approach completamente válido ;)

Saludos!

**Comment by feldespatos** [comment]
Pensamos que es mejor recibirlo e independizarnos de la posición. Lo terminamos de cambiar anoche. Gracias!
