### ISSUE TITLE
Archivo de configuración

### ISSUE THREAD

**Issue by gonzarochlin** [sisoputnfrba/foro#628]
Buenas,
Quería saber si en algún lado estaba explicado como crear y como leer el archivo de configuración. 
Si no, si alguien me pudiera dar una mano, me vendría bastante bien.
Gracias!

**Comment by varas-c** [comment]
Hola,

Fijate que la cátedra te provee de un par de Bibliotecas que te facilitan
muchas cosas, por ejemplo las "Commons Library".

Investigalas un poco y cualquier cosa, pasate por acá otra vez.

Saludos!

**Comment by gonzarochlin** [comment]
Estuve viendo las "Commons Library". Entiendo que en mi proceso yo debería tener: 
`#include <commons/config.h>`  y que la biblioteca me da algunas funciones útiles.
Ahora, lo que no entiendo es donde se crea ese archivo de configuración.

Gracias

**Comment by nicozar95** [comment]
El archivo de configuracion lo tenes que crear vos a mano, es la configuracion inicial de tu modulo, es un archivo de texto comun y corriente. 
Fijate en el TP hay un par de ejemplos de como deberia estar armado ese archivo de configuracion y las funciones de las commons te ahorran todo el proceso de abrir el archivo, mover el puntero, leer tantos bytes, etc etc etc.... siempre y cuando manejes el mismo formato que el archivo de configuracion.

¿Se entiende?

**Comment by gonzarochlin** [comment]
Si! Se entiende.. Vi los ejemplos.
Y ese archivo de texto donde tendría que estar guardado? Dentro del proyecto?

**Comment by nicozar95** [comment]
No hay retricciones de ello, lo podes guardar adentro de tu proyecto o afuera. 
Lo podes harcodear o lo podes pasar como parametro, como se discutia en #626.

**Comment by SofiCortes** [comment]
No está especificado donde hay que guardar el archivo. Fijate que se habló un poco de esto en #626. Revisalo a ver si te ayuda :)

**Comment by SofiCortes** [comment]
Me ganaste de mano @nicozar95

**Comment by gonzarochlin** [comment]
Buenisimo!
Gracias!!
