### ISSUE TITLE
Tipo de dato IP - Archivo de configuración

### ISSUE THREAD

**Issue by gonzarochlin** [sisoputnfrba/foro#629]
Buenas,
Cuando leo el archivo de configuración, no estoy encontrando un tipo de dato para poder leer la IP.
Mi archivo de configuración es:
```
IP_KERNEL=127.0.0.1
PUERTO_KERNEL=8080
```
El puerto lo leo con `int 	  config_get_int_value(t_config*, char *key);` y lo devuelve perfecto.
Ahora, con cualquier tipo de dato que intento, el IP me devuelve sólo 127 o cualquier otro valor, pero no consigo que me devuelva la IP completa.
Podrían ayudarme con esto?
Gracias!

**Comment by mgarciaisaia** [comment]
Ahora, con cualquier tipo de dato que intento, el IP me devuelve sólo 127 o
cualquier otro valor, pero no consigo que me devuelva la IP completa.

Desconfío.

¿Qué tipos probaste?

¿En qué formato/tipo de dato necesitás la IP en tu programa?

**Comment by gonzarochlin** [comment]
Lo probé como int, long, double y char* (con comillas y sin comillas).
No se para que la necesito aún. Estoy leyendo el archivo de configuración según los ejemplos que aparecen en el TP.

**Comment by jazcarate** [comment]
La función que estás usando es de: `config_get_int_value`. El IP como está escrito; no es un numero; si no un `string`, por lo que lo tenes que _levantar_ como tal.

Si peudo llevarte a mirar los tests de las `commons` ([en particular uno que levanta un IP](https://github.com/sisoputnfrba/so-commons-library/blob/master/tests/unit-tests/test_config.c#L74-L76)) vas a ver como podes obtener todo el texto completo. O al menos, eso es lo que está en [el `.cfg` que se está levantando](https://github.com/sisoputnfrba/so-commons-library/blob/master/tests/unit-tests/resources/config.cfg#L2).

No quiero adelantarme a donde lo vas a usar -_y [Beej es mucho mejor que yo para explicarlo](http://beej.us/guide/bgnet/output/html/singlepage/bgnet.html#ipaddrs2)_- pero hay una función [`inet_addr`](https://linux.die.net/man/3/inet_addr) a la que le podes pasar justamente este `string` y hace la mágia de convertirlo a _lo qué necesitas_

**Comment by gonzarochlin** [comment]
La función que mostre fue a modo de ejemplo... Probé con todas.
En el archivo de configuración tengo ésto:
`IP_KERNEL="127.0.0.1"`

En el código, ésto:
```
if(config_has_property(puntero, "IP_KERNEL")){
	ipKernel = config_get_string_value(puntero, "IP_KERNEL");
}
```
Y lo que me retorna es:
`ipKernel = 149283528`

**Comment by nicozar95** [comment]
Buenas
Recien me hice este programita para testear que onda:
```

int main(void) {
	puts("Ejemplo de obtencion de IP");
	char* pathArchConfig ="./config.cfg";
	t_config * config = config_create(pathArchConfig);
	char* ip;

	if (config_has_property(config, "IP"))
				ip = config_get_string_value(config,"IP");

	printf(ip);
	return EXIT_SUCCESS;`

```
con este archivo de configuracion:
`
IP=127.0.0.1
`
y lo que me imprimio fue 

> Ejemplo de obtencion de IP
127.0.0.1

Puede que pusiste la IP_KERNEL en tu archivo de comunicacion entre comillas, que eso te esta largando cualquier cosa.

**Comment by gonzarochlin** [comment]
Ahí está!
Estaba teniendo un error cuando hacía el printf.
Muchas gracias!!

**Comment by jazcarate** [comment]
Se puede cerrar? 👮

**Comment by juanimoli** [comment]
Buenas,

Me sumo al issue para no abrir otro. Estoy intentando implementar la solucion de nico, pero no logro imprimir nada. No salta ningun error y compila perfecto. Cuando debuggeo, se me abre un nuevo archivo, con este mensaje: No source available for "config_has_property() at 0xb7fc2f12". Aca el codigo:

`int main(void) {
	char* path = "./config.txt";
	t_config * configFile = config_create(path);
	char* ipKernel;

	if(config_has_property(configFile,"IP_KERNEL"))
		ipKernel = config_get_string_value(configFile,"IP_KERNEL");

	printf(ipKernel);
	return EXIT_SUCCESS;
}`

**Comment by nicozar95** [comment]
Buenas
Fijate que este bien el path del archivo, en mi ejemplo mi archivo se llamaba "config.cfg"

**Comment by tferraro** [comment]
Sumandome a la recomendación de Nico, si no llega a ser eso, me suena que puede venir por el lado de algo que dijo mati, allá por el 2016 en #516. De todas maneras, hay una explicación más general en nuestra [Guía Gráfica del Eclipse](https://docs.google.com/document/d/16vNTvgYpmojT9vNOLf9MOSEG-EcmozHIGyNx8h5JmoI/pub#h.ieuosfa5yoi) de ese problema.

Suerte!

**Comment by juanimoli** [comment]
Efectivamente era el path. Lo del error que nombre es porque eclipse no me mostraba el codigo, pero puse el path completo y funciono. Gracias!

**Comment by nicozar95** [comment]
@juanimoli @gonzarochlin 
Se puede cerrar el issue? 👮

**Comment by varas-c** [comment]
@Juanimoli te recomiendo leer la diferencia entre Ruta absoluta y relativa
para una convivencia mas feliz con el tp y Linux :)

Te dejo un link
http://www.linuxnix.com/abslute-path-vs-relative-path-in-linuxunix/

**Comment by tferraro** [comment]
Cierro el issue porque parece que está resuelto el problema. Cualquier cosita lo volvemos a abrir ;)
