### ISSUE TITLE
nServidor undeclared en sockaddr_in

### ISSUE THREAD

**Issue by gonziesc** [sisoputnfrba/foro#630]
Buenas! quería dejar sentado un error en el cual estuve trabado por una hora, para que no les pase a otros.
Estaba siguiendo este tutorial: https://www.youtube.com/watch?v=Zd_YJtVScuA cuyo código está en este repo de Github: https://github.com/rodri042/sockets-c-ejemplo/blob/64f0c74382845cb3c01c8b461558b6feed45417a/servidor.c
Lo quise probar para ver cómo funcionaba, y me tiraba el error del título. El problema es que en esta línea:
struct sockaddr_in direcciónServidor;
dirección tiene tilde.
Saludos!

**Comment by jazcarate** [comment]
Gracias por compartir!
Ahorita cree yo un Pull Request para cambiar el texto del codigo; pero en el futuro; sentite libre de pedir directamente el cambio 😄 . Podes ver el pedido de cambió acá: https://github.com/rodri042/sockets-c-ejemplo/pull/1
Devuelta, gracias 👍
