### ISSUE TITLE
Problema al compilar proyecto (Levantar configuración)

### ISSUE THREAD

**Issue by Jaugustopose** [sisoputnfrba/foro#631]
Buenas malas,

Tengo un problema al compilar mi .c antes de correrlo desde la terminal. Creo que es un error de novato 200% pero no lo encuentro. Los pongo en contexto:

## Archivo kernel.cfg tiene esto:

PUERTO_CONSOLA=9010
PUERTO_CPU=9040
IP_MEMORIA=127.0.0.1
PUERTO_MEMORIA=9030
IP_FS=127.0.0.1
PUERTO_FS=9020
PUERTO_KERNEL=9050

## Archivo kernel.h tiene esto:

#ifndef KERNEL_H_
#define KERNEL_H_

#include <commons/config.h>
#include <unistd.h>

struct configuracion {

	int PUERTO_CONSOLA;
	int PUERTO_FS;
	int PUERTO_MEMORIA;
	int PUERTO_CPU;
	int PUERTO_KERNEL;
	char* IP_MEMORIA;
	char* IP_FS;
	// FALTAN AGREGAR VARIABLES SEGÚN AVANCE EL TP (SEMAFOROS, QUANTUM, ETC)
};

t_config* configKernel;
struct configuracion config;

#endif

## Archivo kernel.c tiene esto entre otras cosas (dentro del main llama a "cargarConfiguracion()"):

void cargarConfiguracion()
{
	t_config* configKernel = config_create("/kernel.cfg");

	if (config_has_property(configKernel, "IP_MEMORIA"))
			config.IP_MEMORIA = config_get_string_value(configKernel,"IP_MEMORIA");
	if (config_has_property(configKernel, "IP_FS"))
				config.IP_FS = config_get_string_value(configKernel,"IP_FS");
	if (config_has_property(configKernel, "PUERTO_KERNEL"))
				config.PUERTO_KERNEL = config_get_int_value(configKernel,"PUERTO_KERNEL");
	if (config_has_property(configKernel, "PUERTO_MEMORIA"))
			config.PUERTO_MEMORIA = config_get_int_value(configKernel,"PUERTO_MEMORIA");
	if (config_has_property(configKernel, "PUERTO_CPU"))
					config.PUERTO_CPU = config_get_int_value(configKernel,"PUERTO_CPU");
	if (config_has_property(configKernel, "PUERTO_FS"))
					config.PUERTO_FS = config_get_int_value(configKernel,"PUERTO_FS");
	if (config_has_property(configKernel, "PUERTO_CONSOLA"))
			config.PUERTO_CONSOLA = config_get_int_value(configKernel,"PUERTO_CONSOLA");
}
-------------------------------------------------------
Ahora bien, cuando lo compilo desde Eclipse, tiene 0 drama. Pero cuando hago "gcc -o kernel kernel.c" desde la terminal (ya parado en el directorio correspondiente y toda la bola) me dice:

/tmp/ccTHFGGr.o: En la función `cargarConfiguracion':
kernel.c:(.text+0xc2): referencia a `config_create' sin definir
kernel.c:(.text+0xd8): referencia a `config_has_property' sin definir
kernel.c:(.text+0xef): referencia a `config_get_string_value' sin definir
kernel.c:(.text+0x105): referencia a `config_has_property' sin definir
kernel.c:(.text+0x11c): referencia a `config_get_string_value' sin definir
kernel.c:(.text+0x132): referencia a `config_has_property' sin definir
kernel.c:(.text+0x149): referencia a `config_get_int_value' sin definir
kernel.c:(.text+0x15f): referencia a `config_has_property' sin definir
kernel.c:(.text+0x176): referencia a `config_get_int_value' sin definir
kernel.c:(.text+0x18c): referencia a `config_has_property' sin definir
kernel.c:(.text+0x1a3): referencia a `config_get_int_value' sin definir
kernel.c:(.text+0x1b9): referencia a `config_has_property' sin definir
kernel.c:(.text+0x1d0): referencia a `config_get_int_value' sin definir
kernel.c:(.text+0x1e6): referencia a `config_has_property' sin definir
kernel.c:(.text+0x1fd): referencia a `config_get_int_value' sin definir
collect2: error: ld returned 1 exit status

Si dice "sin definir", calculo que no esta pudiendo referenciar a la librería commons que le especifiqué en el kernel.h . Pero la referencie che!
La terminal no me quiere y presiento que es por que le estoy tirando un ladrillo.

PD: Perdón que mando un choclazo, pero tenía miedo de no mostrar el problema entero.

Saludos y que arranquen bien la semana =)

**Comment by varas-c** [comment]
Hola!

Linkeaste las commons a tu proyecto? Linkear NO ES agregar el header
correspondiente (#include <commons/config.h> si no me equivoco).



2017-04-09 22:02 GMT-03:00 Juan Pose <notifications@github.com>:

**Comment by nicozar95** [comment]
Buenas
¿Y si lo compilas desde Eclipse y lo corres por la consola te anda? Eclipse te genera el makefile de tu programa, detras de escena lo que Eclipse hace la hace un `make` al makefile que armo de tu programa y lo ejecuta.(cuando haces martillito y boton verde)

El makefile de tu programa es un poco mas complicado que hacer `gcc -o kernel kernel.c`, ya que ahi linkea todas las referencias y demas magias

**Comment by Jaugustopose** [comment]
Probé con el video de [la Talk 2 - Shared Library](https://www.youtube.com/watch?v=s5ac8CPDkMg&feature=youtu.be). Hice todo y ahora tengo el siguiente error al querer correr el programa (despues de usar make para compilarlo):
 
utnso@utnso40:~/Escritorio/tp-2017-1c-No-Se-Recursa/kernel/Debug$ ./kernel
Violación de segmento (`core' generado)
utnso@utnso40:~/Escritorio/tp-2017-1c-No-Se-Recursa/kernel/Debug$

Es un error de violación de segmento, por lo que creo que es un error dentro del código y no con el linkeo a las commons, ¿no? Si es así, cierro este thread y me pongo  aver si puedo arreglar lo otro. 

Saludos y gracias!

**Comment by varas-c** [comment]
Si te tiró Violación de Segmento, es un error de tu código (ya lo encontré
el error)

Te tiro una pista:
http://www.linuxnix.com/abslute-path-vs-relative-path-in-linuxunix/

Saludos!

**Comment by sciciliani** [comment]
@Jaugustopose fijate si te podes dar cuenta ejecutando el código paso a paso con el debugger en que punto da violación de segmento.

Posiblemente te esté faltando alguna verificación relacionada con alguna operación que asumís que se ejecuta correctamente y no se hizo, tal como @varas-c sugiere más arriba.

**Comment by Britanico10** [comment]
Yo tuve el mismo problema que vos. Desp de tanto probar pude encontrar la solucion:
Si usas la termina tenes que hacer :    gcc -o "nombre" "nombre.c" -lcommons

**Comment by Jaugustopose** [comment]
Habemus error solucionado.

El problema era el path que estaba recibiendo la función config_create. A la misma no se le puede (por lo que estuve probando) pasar un path relativo, tiene que ser absoluto (corrijanme si me equivoco).
Finalmente me queda así, y anda bien =D

t_config* configKernel = config_create("/home/utnso/Escritorio/tp-2017-1c-No-Se-Recursa/kernel/kernel.cfg");

Con esto, surge una pequeña duda más: ¿Hace falta que el resto de los miembros del grupo comparta el mismo path para llegar al archivo o existe alguna forma de hacerlo portable a cualquier pc? 

@varas-c te quiero @sciciliani sos mi religión y valgrind me voy a hacer un tatuaje tuyo.

Gracias totales.

**Comment by gastonprieto** [comment]
Si se puede :)

Probablemente no estes donde crees, podes usar esta función para saber el directorio actual: http://stackoverflow.com/questions/298510/how-to-get-the-current-directory-in-a-c-program

**Comment by mgarciaisaia** [comment]
O http://mgarciaisaia.github.io/tutorial-c/blog/2015/04/23/rutas-argentinas/ en su defecto ¯\\\_(ツ)\_/¯

**Comment by Jaugustopose** [comment]
Con los últimos comentarios llegue a algo medio/muy rupestre por llamarlo de alguna forma, aunque funciona:

char* pat = string_new(); // String que va a tener el path absoluto para pasarle al config_create
char cwd[1024]; // Variable donde voy a guardar el path absoluto hasta el /Debug
string_append(&pat, getcwd(cwd,sizeof(cwd)));
string_append(&pat,"/kernel.cfg"); // Le concateno el archivo de configuración
t_config* configKernel = config_create(pat);
printf("El directorio sobre el que se esta trabajando es %s\n", pat);
free(pat);

![68bd72e5-5738-49d3-bee4-9ffb518e30f3](https://cloud.githubusercontent.com/assets/18368754/24886874/3523375e-1e2e-11e7-889a-b5aab62886f8.jpg)

Cierro y muchísimas gracias a todos!
