### ISSUE TITLE
Problemas para linkear Shared Library 

### ISSUE THREAD

**Issue by ger912** [sisoputnfrba/foro#632]
Hola buenos dias,
Estoy teniendo problemas para linkear una Shared Library. Ya defini el LD_LIBRARY_PATH con la ruta correspondiente, el Eclipse me compila el programa sin embargo cuando quiero hacerlo por consola con gcc, no me reconoce el include de la Shared Library.
![image](https://cloud.githubusercontent.com/assets/13937147/24863653/2071cd44-1dd8-11e7-8451-b5fcb4b48604.png)
En la imagen se ve por un lado el Eclipse corriendo, y por otro lado la consola.
El LD_LIBRARY_PATH, lo habia editado primero en el .bashrc. Y no me lo levantaba ni el Eclipse.
Buscando en el foro, habian pasado este link.
[http://unix.stackexchange.com/questions/117467/how-to-permanently-set-environmental-variables/117470#117470](url)
Por lo que edite tambien el .profile, y despues de eso comenzo a andar con el Eclipse.
El resto de mi equipo no tuvo problemas con esto, y solo modificaron el .bashrc.

¿Alguien me puede dar una mano? 
Desde ya muchas gracias.
Saludos!

**Comment by nicozar95** [comment]
Buenas
Te referencio al issue #631 
Eclipse te genera el makefile para que directamente la compilacion de tu proceso sea a travez del comando `make` y no el compilador de C directamente, ya que dependes de un monton de dependencias extras y flags, que dentro del `gcc` se te complica un poco

Te dejo [un video de como podes compilar y usar las shared library por consola](https://www.youtube.com/watch?v=s5ac8CPDkMg&feature=youtu.be).

Avisame si te ayudo
Saludos

**Comment by ger912** [comment]
Sos un grande, gracias!
