### ISSUE TITLE
Problema para aceptar conexion Sockets

### ISSUE THREAD

**Issue by totojanin2** [sisoputnfrba/foro#633]
Hola,

Estamos tratando de establecer una conexion entre el proceso consola y el kernel.

Tenemos este código, sacado de Beej.

```
int aceptarConexion(int socketEscucha){
 struct sockaddr_in addressCliente;
 socklen_t  sin_size = sizeof(addressCliente);
 int nuevoFD = accept(socketEscucha, (struct sockaddr *) &addressCliente,&sin_size);
 return nuevoFD;
}
```

Cuando debuggeamos, llegamos hasta el metodo accept y al intentar ejecutarlo dice que no lo puede encontrar y tira este error:

> Can't find a source file at "/build/buildd/eglibc-2.19/socket/../sysdeps/unix/sysv/linux/i386/socket.S" 
> Locate the file or edit the source lookup path to include its location.

Cual podria ser el problema?

Gracias

**Comment by nicozar95** [comment]
Buenas
Fijate que el error que te larga el debugger es el famoso [error que no es](https://docs.google.com/document/d/16vNTvgYpmojT9vNOLf9MOSEG-EcmozHIGyNx8h5JmoI/pub#h.ieuosfa5yoi).
Fijate si podes resolver ese tema del debugger y asi seguimos con el problema.

**Comment by ziggylineous** [comment]
a mi no me andaba otra cosa debuggeando, mostrandome eso de buscar el source, sin poder hacer step out, diciendo "terminated". después encontré que estaba pasando un int en vez de char* para un puerto. (el compilador en debug no me decía nada, en release me tiraba un montón de giladas pero aparecía el error)
fijate si le pifiás algún tipo de parámetro, a mí me pasó eso

**Comment by nicozar95** [comment]
@totojanin2 ¿Lo solucionaste?¿Que paso?

**Comment by totojanin2** [comment]
Si, me olvide de cerrar el issue. Nos faltaban hacer unos pasos anteriores de socket, no era el accept en particular. Gracias
