### ISSUE TITLE
Eclipse no reconoce las shared librarys

### ISSUE THREAD

**Issue by samanthabillino** [sisoputnfrba/foro#634]
Hola! Con mi equipo estamos teniendo un problema, estamos queriendo crear una shared library siguiendo los pasos del video recomendado en el issue #632 , hacemos todos los pasos pero al compilar, eclipse no las reconoce, dice que la ruta no existe.
Existe alguna otra forma de poder linkear ?

Gracias,
Saludos!

**Comment by jazcarate** [comment]
Holitas,
Podrías darnos algo más de información? como, por ejemplo, el texto entero que te dice `Eclipse` de por qué no _las reconoce_? Como estás compliando? Como está configurado tu proyecto? 😅 

Como para ayudar, tenemos un videito sobre como [reportar errores con Eclipse](http://faq.utn.so/errores-eclipse)

**Comment by samanthabillino** [comment]
![270c61460a4c6a24db3dd268b86df1c474a9cbd141fe69bea0 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/22395396/25059201/7a882f66-2158-11e7-9809-1e3d58b0a466.jpg)
Eso es lo que nos pasa siguiendo los pasos hasta el minuto 6:13, al compilarlo tira 

> fatal error: FuncionesGenericas/funcionesGenericas.h :no existe el archivo o directorio
PD: En la foto dice funcionesGenericas/funcionesGenericas.h cuando en realidad es FuncionesGenericas/funcionesGenericas.h , pero de todas maneras poniendolo bien no funciona.

**Comment by nicozar95** [comment]
Buenas
Fijate si haciendo: **FileSystem -> Properties -> Paths and Symbols -> References** y dandole click a la casilla de FuncionesGenericas funca

**Comment by samanthabillino** [comment]
Esa casilla esta tildada, tal como lo hacen en el vídeo.

**Comment by jazcarate** [comment]
¿Nos pasarías la salida de lo que ejecuta Eclipse al compilar?
[Un chiquito antes de minuto 13 en el video que te dije más arriba](https://youtu.be/18cN8Jk4WjQ?t=173)

**Comment by samanthabillino** [comment]
Raramente ahora me compilo, debe ser uno de esos errores de eclipse. Cierro el issue. Gracias igual!
