### ISSUE TITLE
Problemas con Eclipse

### ISSUE THREAD

**Issue by deborahpergamenik** [sisoputnfrba/foro#635]
Hola!
Estoy teniendo muchos problemas con eclipse, para empezar que no me deja importar los proyectos que clono desde git. Hasta ahora estuve usando una computadora que tenia linux nativo pero se me rompió y estoy usando la del trabajo con la maquina virtual que provee la catedra. En mi computadora estaba usando el IDE "Clion" que me pareció mucho mas amigable que Eclipse, trate de bajarlo en la maquina virtual pero me pide java 1.8 o más, trate de actualizar el java de la maquina virtual pero no pude tampoco, hay alguna forma de poder hacerlo? Con respecto a eclipse estoy clonando y tratando de importar los proyectos de forma exacta a como lo explican en los videos pero eclipse me dice: "No projects are found to import" cuando selecciono el directorio que se clona de git dentro del workspace. Sabran por qué me puede estar pasando esto y como solucionarlo? (Aunque si se puede actualizar java es mucho mejor jaja)

Gracias!
Deborah

**Comment by jazcarate** [comment]
Holitas,
Vamos a de poco:
1. _[OT] A mi también me gusta CLion, pero es medio fiero como maneja el `make` con su sistema de `CMake`._
2. No veo por qué deberías tener problema instalando `Java 1.8`. ¿Donde te trabaste?
3. Mirando su Repo, solo tienen archivos `.c`s. No tienen ningúna configuración de `.project`, o `.cproject`; entonces al intentar "importar", el Eclipse no tiene nada que importar (de acá el error). Las soluciones son varias: a) Pedile a algun compañero que lo esté haciendo con Eclipse que suba esta "metadata" del proyecto, o b) Creá un proyecto en la misma carpeta que tenías en `CLion` y dejá que Eclipse descubra los `.c`s solo; y genere estos archivitos.

_`NaCl`u`2`_

**Comment by deborahpergamenik** [comment]
Hola! 
El problema con clion lo solucionamos en el grupo porque todos usan clion. Asique no sería un problema por ahora.  
Con respecto al Java, por ahí lo estoy bajando mal yo, lo descargué desde la página de Java e hice lo que dice en la página para instalarlo. Hay alguna manera más fácil? 

Gracias!

**Comment by jazcarate** [comment]
Desconozco qué dice "en la página", pero debería ser tan simple como descargar _algo_, descomprimirlo y configurar un par de variables de ambiente (`JAVA_HOME` y agregarlo al `PATH`).

Entiendo que también se puede hacer desde `apt-get`. Creeeeeeeo que es algo como: https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-get-on-ubuntu-16-04

**Comment by deborahpergamenik** [comment]
Ya pude actualizar java. Mucha gracias por la ayuda!
Saludos

**Comment by jazcarate** [comment]
![Wisdom of the Ancients](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)
