### ISSUE TITLE
Igualar dos fd_set

### ISSUE THREAD

**Issue by Mathy977** [sisoputnfrba/foro#636]
Tengo dos bolsas de sockets y no las puedo igualar usando el operador =

**Comment by jazcarate** [comment]
¿Como estas intentando igualarlas?
¿`unSet = otroSet`?

En C, la igualdad está definida por tipo primitivo; por lo que, si tus sets son `fd_set *fds`, en realidad son `int`; por lo que dos `fd_set*` son *iguales*, solo si comparten el mismo lugar en memoria _(lo cual, en algún lado, es cierto)_.

**Comment by jazcarate** [comment]
_Comentario adicional; por si las dudas: `=` asigna. `==` compara_

**Comment by nicozar95** [comment]
@Mathy977 ¿Te sirvio la respuesta de Joaco?¿En donde te quedaste?

**Comment by Mathy977** [comment]
Gracias, lo pudimos hacer comparando punteros

**Comment by mgarciaisaia** [comment]
Hey, ojo, no bardeen. No se olviden que hay una diferencia entre identidad e igualdad/equivalencia.

La comparación de punteros te va a decir unicamente si ambos punteros están apuntando a la misma dirección de memoria. Y eso implica que ambos sets son iguales, porque en realidad no hay dos sets - es uno solo, con dos "nombres" distintos. Es preguntar si Joaco y @jazcarate son iguales - es una única persona _(esquizofrenia aparte)_, por lo que es obvio que va a ser igual a sí mismo (Matemática Discreta, capítulo 3 - "Reflexividad").

Pero también existe la equivalencia - estos dos sets, ¿tienen los mismos valores?

Y eso no implica identidad. Yo puedo tener dos monedas de 1 peso que, a efectos de pagar cosas, son iguales - tanto da pagar con una o la otra. Pero siguen siendo dos monedas distintas, incluso si ambas fueran de la misma serie y todo.

Entonces, fijate bien cuál de los dos casos necesitás. Fijate si querés saber si ambos sets son el mismo, o si querés saber si ambos sets tienen el mismo valor.

Y, en base a eso, fijate qué es lo que esté haciendo tu código.
