### ISSUE TITLE
Hashing

### ISSUE THREAD

**Issue by sebawars** [sisoputnfrba/foro#637]
Buenas, tengo una duda con la función de hashing que da colisiones solo para frames contíguos... esto quiere decir que si mi último frame del sistema es el número 49 y si me resultan 3 colisiones para el 47, la tercer página no va a tener lugar en memoria por mas que, por ejemplo, el frame nro 4 esté libre, es así? Y lo mismo si el 48 y/o el 49 estaban ocupados.
Gracias

**Comment by sebawars** [comment]
Y de acá se desprende otro problema; si al inicializar un programa que requiere 10 páginas y a la página nro 9 no la puedo ubicar en memoria (si bien hay frames anteriores libres)... tendría que hacer una especie de rollback si no me equivoco

**Comment by iago64** [comment]
@sebawars Que tal? 
Por lo que planteas tu funcion tira los a los últimos frames de tu memoria a las ultimas páginas tu proceso cierto? 
En ese caso, no podrías hacer una especie de"reloj" y darle la vuelta a tu memoria y volver a empezar? Por otra parte, la función de Hash es algo muy posiblemente varíe mas adelante cuando vean bien el tema de memoria en la teoría, así que tene en cuenta lo que te comente pero espera a verlo bien en la teoría y en todo caso consulta con tu ayudante asignado.

**Comment by sebawars** [comment]
Ok entonces, en principio, en estos casos seguimos buscando desde el principio. Sólo para aclarar, la función de hash es la que me dice en qué marco se almacena la página a almacenar, verdad?

**Comment by nicozar95** [comment]
Claro,La funcion de hash te dice en que indice esta la pagina que queres acceder(puede ser para almacenar, leer, chusmear, etc) , cosa que yo le paso el PID del proceso y la pagina a acceder y me tire en que marco esta.

Esto es para evitar ir viendo uno por uno los marcos de mi memoria haber si es la pagina que yo quiero acceder, generalmente para pocas paginas de memoria no hay tanto quilombo de performance, pero para una memoria muy grande, se pierde mucho tiempo ir viendolo secuencialmente.

La funcion de hash tal vez es algo que se implementa un poco mas desde el lado de la matematica, si te pones a googlear vas a encontrar papers y papers de matematicos que buscan la funcion de hashing que sea mas performante, que tenga menos colisiones, que sea mas segura en desarrollar encriptacion de datos (no se si a nosotros nos interesa tanto esta parte), etc etc.

La funcion de hashing perfecta no existe, [eventualmente va a generar una colision que va a dar vuelta como tenias pensado tu sistema](http://www.theverge.com/2017/2/23/14712118/google-sha1-collision-broken-web-encryption-shattered), queda completamente a su criterio como quieren implementar esta funcion en su TP.

**Comment by sebawars** [comment]
Buenisimo y una última pregunta ya que estamos: la memoria cache ustedes requieren que sea sí o sí un espacio contíguo de memoria? o sea estaría mal que usemos diferentes malloc para diversas páginas y anidarlas en una lista por ejemplo?

**Comment by nicozar95** [comment]
>  la memoria cache ustedes requieren que sea sí o sí un espacio contíguo de memoria? o sea estaría mal que usemos diferentes malloc para diversas páginas y anidarlas en una lista por ejemplo?

No se si en el enunciado dice algo de que la memoria cache tiene que estar contigua a la memoria real.
Si no dice nada, hacelo con un malloc extra que es mas sencillo.

**Comment by sebawars** [comment]
Genial, gracias por las respuestas

**Comment by mgarciaisaia** [comment]
@sebawars estuvimos charlando un poco con @nicozar95, y _creo_ que hubo un mismatch entre lo que preguntaste y lo que Nico quiso contestarte.

La memoria cache tiene que ser un único bloque de memoria, del mismo modo que ocurre con la memoria principal. Lo que Nico te dijo (_un malloc extra_) es que no tiene por qué ser _el mismo bloque_ para la memoria y la cache. Es decir, si tenés 100k de memoria principal, y 2k de caché, hacé un `malloc` por 100k y otro por 2k, en lugar de hacer uno por 102k.

Pero lo que creo que preguntabas vos era si podías, en vez de hacer un malloc de 2k para la caché, hacer, no se, 8 `malloc`s de 256 bytes en el caso de que tuvieras 8 páginas de cache de 256 bytes cada uno.

Si esa era la pregunta, entonces la respuesta es "no: hacé un único bloque para toda la cache".

Si la pregunta era la que Nico respondió, entonces mandá todo este mensaje a `/dev/null` ^_^

**Comment by sebawars** [comment]
Buenisimo, gracias por revisarlo

**Comment by nicozar95** [comment]
Llegamos a unas conclusiones bastantes interesantes en el issue #663 sobre como manejar la estructura de la cache.

Si alguien esta recorriendo los issues, siguiendo el hilo de conversacion y quieren entender un poco mas de como manejar la memoria cache, vayanse a ese issue :smile:
