### ISSUE TITLE
[memoria] ¿Existe la posibilidad de dejar bytes inutilizables?

### ISSUE THREAD

**Issue by fedetrim** [sisoputnfrba/foro#639]
Llegué a una fórmula que dado un tamaño físico de memoria disponible para utilizar (`cantidad de frames * tamaño de frame`) y un tamaño de una estructura administrativa, obtengo la cantidad máxima de páginas que voy a poder otorgar a los procesos (y por ende también la cantidad necesaria de estructuras administrativas que necesito posicionar al comienzo de la memoria física).

Este número puede no ser entero, y no sé si tiene sentido quedarme con una página virtual cuyo tamaño sea menor al de los frames. Lo que había pensado es recortar la parte flotante de este número y quedarme solamente con la parte entera.

El tema es que hay cierta cantidad de bytes (menor al tamaño de un frame) que perdería y no podría utilizar para nada. ¿Tiene sentido?

**Comment by fedebonisconti** [comment]
Si estuvieses recortando lo que sobra de una página, estaría bien hablar de paginación?

Que es lo que tiene la paginación que no tienen otros esquemas de memoria?

Saludos!

**Comment by fedetrim** [comment]
Mmm no te terminé de entender. No estaría recortando lo que sobra de una página, estaría recortando bytes que no alcanzan para formar una página completa y por lo tanto no se la podría asignar a ningún proceso.

**Comment by mgarciaisaia** [comment]
@fedetrim lo que decís está perfecto. Sería raro asignar todas páginas de un tamaño predefinido, excepto una que es un poco más chica. En Sistemas es muy importante mantener invariantes, porque ello te simplifica toda tu operatoria, y asignar una página más chica que las demás te rompe eso de "todas las páginas tienen el mismo tamaño" - un invariante muy útil a la hora de manejar tus páginas.

Entonces, como bien seguís diciendo, puede pasarte que no uses algunos bytes que están al final de la memoria. Es correcto, también, afirmar que esa cantidad de bytes desperdiciados es estrictamente menor al tamaño de página (porque, claro: si fuera igual o mayor, podrías tener una página más).

Cuando veas en la cursada las clases de memoria vas a ver que este concepto se llama _fragmentación_ - tener bytes de memoria libres pero que no podés aprovechar debido a la forma de administración de memoria que elegiste usar.

En esa clase vas a ver, también, que existe la fragmentación externa y la interna. Una trata de, como en este caso, tener bytes que no podes usar porque no se los podes asignar a ninguna de tus unidades de memoria. La otra ocurre cuando te quedan bytes sin usar _dentro_ de la estructura, y que por eso no podés usarlos para otro proceso/usuario.

Por último, en esa clase también vas a ver cuál de las dos definiciones que acabo de escribir corresponde con cuál de los dos tipos de fragmentación. Tu tarea, en ese caso, va a ser recordarlos mejor que yo, que jamás me acuerdo cuál tipo era cada uno.

No seas como yo - aprendelos bien.

Un abrazo, y 5 puntos para Gryffindor por la observación (y porque siempre perrean los números a favor de Gryffindor).


(pd: los puntos no son canjeables como nota de parcial, TP ni final)

**Comment by mgarciaisaia** [comment]
Me gustaría tener un buen link para pasarte, pero una googleada más tarde entiendo que la fragmentación interna es cuando te queda espacio dentro de cada unidad de asignación, mientras que la externa es cuando te queda espacio sin asignar a ninguna de las unidades de asignación (la página, en este caso).

**Comment by fedetrim** [comment]
@mgarciaisaia se entendió perfecto, gracias por la larga respuesta. Estuve googleando sobre fragmentación interna y externa y sí, es como decís.

Cierro el issue. ¡Gracias!
