### ISSUE TITLE
Consulta Consola MultiHilos

### ISSUE THREAD

**Issue by calvoluciano** [sisoputnfrba/foro#641]
Consulta, en mi implementacion de la Consola cada hilo creado es un FileDescriptor cliente nuevo, por cada envio de script a ejecutar se dispara nuevamente el handshake etc etc, mi ayudante de TP me comento porque hacia eso y lo revisara bien, pero no me termina de cerrar como seria la mejor forma de resolverlo, si utilizo un solo FD cliente como genero cada hilo?  Por ese FD enviaría cada script a ejecutar, y como hago para saber el PID asignado, se me podrían mezclar PID y respuestas si solo trabajo sobre un solo FD? 
En conclusión para mi seria correcto crear un nuevo FD por cada hilo que disparo, desde ese FD voy a atender ese programa con el PID identificado y nunca se me van a mezclar respuestas.

Me fui con la idea de que no tengo que generar varios clientes de conexión en una consola, pero si lo pienso un poco no lo veo mal.

**Comment by iago64** [comment]
Luciano, que tal?
Esta mal crear un FD por cada Thread de la consola? la realidad es que no, pero vas a tener un tema y es que si por alguna razón (que casualmente no pueda ser alguna prueba del TP) alguien tira el comando de desconectar consola vas a tener que manejar varias (tantas como hilos tenga la consola que desconectas) desconexiones en el Kernel, osea vas a estar dando vueltas cerrando sockets en el Kernel por una única acción.
Aun asi te repito, MAL no esta que tengas una conexión por consola, simplemente hay otras formas y eso es lo lindo ya que no te obliga a hacerlo de una sola.

Si queres ir por la opción de no tener un FD por cada thread de la consola, podrías pensar como funciona el caso de que varios threads por ejemplo quieran acceder a algo en común, como por ejemplo un archivo (si no te termina de cerrar la idea, te prometo que el sábado en la charla de Threads voy a contar como se puede hacer :) ).

De todas formas para cerrar la idea y reforzar, no es la muerte de nadie ni van a desaprobar por levantar un socket por cada thread que tengan en la consola, ya que a fines prácticos, los mensajes van y vienen, ya sean por N vías o por 1 sola y que es lo que importa.

**Comment by calvoluciano** [comment]
Gracias,

Saludos,
