### ISSUE TITLE
Consulta CMake

### ISSUE THREAD

**Issue by Matias9635** [sisoputnfrba/foro#642]
Hola buenas tardes, estaba siguiendo las instrucciones para clonar, compilar, instalar cspec para los tests del repositorio del parser pero al momento de generar el Makefile con "cmake ." la consola me dice que no se pudo porque necesito tener instalado CMake. Entonces lo instalé haciendo "sudo apt-get install cmake". Pero cuando hago "cmake ." me aparece un error porque se necesita una versión más nueva del CMake.

> utnso@utnso40:~/ansisop-parser$ cmake .
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.5 or higher is required.  You are running version 2.8.12.2

-- Configuring incomplete, errors occurred!
utnso@utnso40:~/ansisop-parser$

Por las dudas quise consultar para saber si conviene bajarse una versión más nueva desde el navegador.
Un saludo, gracias!

**Comment by nicozar95** [comment]
Buenas

Si conviene tener una version actualizada del CMake para correr el test del parser.

Para consultar la version del cmake hace:
`cmake --version`
Fijate si se soluciona haciendo un:
`sudo apt-get update`
En caso de que no, [nuestros amigos del foro de Ubuntu tienen una posible solucion](https://askubuntu.com/questions/829310/how-to-upgrade-cmake-in-ubuntu)

**Comment by jazcarate** [comment]
Mil disculpas! El Readme quedó desactualizado 😄 .
Ahora no hace falta `CMake`. Podes simplemente hacer `make test` y correrían.
Ahora lo actualicé [👤](https://github.com/sisoputnfrba/ansisop-parser/commit/74fe5b91de984bf47184e4101cbe8f6b458c9327)

**Comment by Matias9635** [comment]
Genial, buenisimo entonces, gracias!
