### ISSUE TITLE
Duda sobre Páginas de código

### ISSUE THREAD

**Issue by fpatalagoity** [sisoputnfrba/foro#643]
Buenas, no comprendo bien para qué se usaría este campo (Páginas de Código) del PCB. No termino de entender bien si es un número que simboliza una cantidad (ejemplo: 3 para 3 páginas) o si son las páginas a ser utilizadas por el programa (ej: páginas 0, 1 y 2).

Gracias! Saludos

**Comment by nicozar95** [comment]
Buenas
Es un numero que simboliza una cantidad empezando del numero 0. Osea, si un script ansisop ocupara 2 paginas de memoria, deberias marcar ese valor como 1 en la Páginas de código.

Puede que parezca un tema medio jede empezar a contar desde el 0 y en parte lo es. Pero en otra parte "C empieza a contar desde 0"
