### ISSUE TITLE
Memoria, cómo administrar el segmento de estructuras administrativas.

### ISSUE THREAD

**Issue by FLavagnino** [sisoputnfrba/foro#644]
Hola buenas,

La parte de memoria que se reserva para las estructuras administrativas, se administra de forma paginada o puede tratarse como un único segmento? Por ejemplo, la tabla de paginas para guardarla tengo que dividirla en tantas partes como páginas necesite, y al accederla tengo que saber en que página esta la parte de la tabla de páginas que busco?

Gracias.

**Comment by nicozar95** [comment]
Buenas
Fijate que en el enunciado dice que se reserva una cantidad de bloques continuos para manejar las estructuras administrativas de la memoria, osea, si bien tu memoria va a estar manejada de forma paginada, la tabla de pagina de la memoria va a estar de forma continua, por lo tanto no se si es necesario saber en que pagina esta cada parte de mi tabla si la tengo ordenada y todo junta en un mismo espacio.
