### ISSUE TITLE
Diseño capa memoria

### ISSUE THREAD

**Issue by BrunoManchione** [sisoputnfrba/foro#645]
Buenas, estoy diseñando la parte que reserva la memoria en las paginas de Heap.
1.Para crear una pagina yo tendría que hacer malloc(tamañoDePagina) y usar el puntero que devuelve para desplazarme por la pagina, o es de otra forma que no entendi?
2.Siempre la primera "posicion" de la pagina va a estar ocupada por la estructura HeapMetaData. De que tipo tendria que ser el puntero para que funcione? Lo hago de tipo void* y voy casteando? De que tipo seria la parte Data de la pagina?
Gracias

**Comment by nicozar95** [comment]
Buenas

> 1.Para crear una pagina yo tendría que hacer malloc(tamañoDePagina) y usar el puntero que devuelve para desplazarme por la pagina, o es de otra forma que no entendi?

No, en la Memoria vas a tener que almacenar 3 cosas: El codigo de tu proceso,el stack de tu proceso y el heap de tu proceso. Cuando un proceso necesita memoria le vas a asignar una pagina a ese proceso en la memoria, osea, en el malloc enorme que hiciste al principio de tu programa vas a tener que darle una pagina contigua (como muestra el dibujito de la pagina 24), esto significa moverte a la pocision de memoria que represente la pagina a asignar. Por ejemplo, le vas a asignar la pagina 42 y tus paginas son de 512 bytes, entonces vos vas a empezar a escribir en la pagina desde el byte 42*512 que seria tu numero de pagina * el tamaño de pagina. ¿Se entiende?

> 2.Siempre la primera "posicion" de la pagina va a estar ocupada por la estructura HeapMetaData. De que tipo tendria que ser el puntero para que funcione? Lo hago de tipo void* y voy casteando? De que tipo seria la parte Data de la pagina?

No se si entendi bien esta preguna:
La primera pocision de la pagina que le asignaste al Heap si va a tener que tener algun tipo de metadata para simular lo que sucede en los sistemas operativos reales para manejar estructuras de memoria. Deberian guardar esa metadata en la pagina al principio con los datos que figura en el enunciado, la joda esta en como lees vos esa metadata. Si vos casteaste tu Memoria como todo un char* tendrias que poder levantar las estructuras de la metadata segun el tamaño que corresponda y administrarla adecuadamente ¿Me explico? Lo mismo va para el tema de la parte de la Data de la memoria, lo importante esta en como lo almacenas y como lo lees despues.

Saludos

**Comment by nicozar95** [comment]
Capas no te compliques tanto ahora con el tema de manejar los punteros de la pocisiones de memoria, este sabado van a full con serializacion y les van a explicar uno o dos trucos para manejar esto.

**Comment by varas-c** [comment]
@BrunoManchione pudiste solucionarlo? Si seguís teniendo dudas, avisá!
