### ISSUE TITLE
Tamaño de pagina de memoria.

### ISSUE THREAD

**Issue by marcelocejas** [sisoputnfrba/foro#646]
Hola, tengo una pregunta cortita y al pie. De donde se saca el tamaño de la pagina de memoria? no vemos que este descrito en el enunciado. Lo poco que vemos es que al conectarse el kernel lo primero que hace la memoria es decirle el tamaño de pagina, las opciones por las que optamos en caso que sea decisión de equipo es que sea una propiedad interna de la memoria, así a nadie se le ocurre tocarla o bien un parámetro mas de configuración.

**Comment by nicozar95** [comment]
Si es una propiedad de la Memoria, por eso el Kernel tiene que preguntar cuanto es el tamaño de pagina.
Vos sacas el tamaño de pagina del archivo de configuracion de la Memoria, donde dice:

>MARCO_SIZE

**Comment by varas-c** [comment]
Hola!

Está en el enunciado, en el archivo de configuracion de la memoria pero no
precisamente como "página". Fijate que dice "Marco Size", tenés idea que
significa eso?

**Comment by marcelocejas** [comment]
Pero hasta donde yo entendía un Marco esta dividido en varias paginas.

**Comment by nicozar95** [comment]
No, un marco ocupa una pagina

**Comment by marcelocejas** [comment]
ah! ya entendí! desde el punto de vista de la memoria son marcos, pero desde el punto de vista del proceso son paginas. ;) 
Listo! gracias!
