### ISSUE TITLE
Duda manejo memoria

### ISSUE THREAD

**Issue by feldespatos** [sisoputnfrba/foro#647]
Hola. Queria saber si está bien asumir que la pila es de una página. O de cuanto es?
Saludos.

**Comment by nicozar95** [comment]
Buenas
No esta bien asumir que la pila es de una pagina porque la pila va a ir creciendo. 
Vos tenes la cantidad de paginas que va a ocupar el stack en el archivo de configuracion del Kernel donde dice:

> STACK_SIZE

>

**Comment by feldespatos** [comment]
Se me estaba escapando ese detalle. Gracias!
