### ISSUE TITLE
Tabla de indice de codigo

### ISSUE THREAD

**Issue by dipatata** [sisoputnfrba/foro#649]
Buenas tardes,

Tenemos una duda en cuanto a la tabla de indice de codigo especificada en la pagina 31. Es una tabla de dos columnas con linea de codigo y offset de linea de codigo.
Por el enunciado se entiende que esta tabla debe estar almacenada en memoria. La pregunta es, como se almacena ? Cuando se crea un proceso, el kernel pide las paginas de codigo, las paginas de stack.. 

1) Ademas debe pedir una pagina especial para almacenar la tabla de indice de codigo ?
2) Quien realiza el parseo del codigo para crear esta estructura ? El kernel ?

Saludos y gracias

**Comment by nicozar95** [comment]
Buenas
Esa tabla **NO** se debe almacenar en Memoria, **lo unico de los scripts que vas a almacenar en memoria son: el codigo del programa, el stack del programa y el heap que te va a pedir de forma dinamica.**

Esta tabla te marca desde que byte y cuanto pesa cada instruccion, cuestion que puedas levantar la instruccion de Memoria a la CPU que corra tu script.

**Comment by dipatata** [comment]
Gracias por la respuesta.
Entiendo que la cpu va a buscar su instruccion a memoria sin pasar por kernel, por lo cual el puntero a esta tabla deberia estar en el pcb. Ahora, la tabla en si, puede estar en memoria del proceso kernel?

**Comment by nicozar95** [comment]
La tabla en si no hace falta que la almacenes en el proceso Memoria, es una tabla que pertenece al PCB de tu programa, que lo utiliza el Kernel para realizar su planificacion y la CPU lo utiliza para correr los scripts en el contexto marcado por la estructura del PCB.

La Memoria va a almacenar las paginas de los programas (codigo,stack y heap) y su estructura administrativa(tabla de paginas inversa).

¿Se entiende?
Saludos

**Comment by dipatata** [comment]
Me quedo claro que la tabla no va en memoria, en mi segunda respuesta te pregunto, la podemos tener en el kernel? 
Y ademas, esta bien que la genere el kernel cuando inicia un proceso?

**Comment by nicozar95** [comment]
Ahh entonces te entendí mal mil disculpas.

Si debería estar en el Kernel ya que es el que decide cuando corre cada
script, la CPU es bastante tosca, lo único que hace es correr lo que el
Kernel le da y actualizar la estructura administrativa del proceso, osea su
PCB.

Cuando un script se va de una CPU, la CPU debería estar "limpia" para
correr otro proceso con otra PCB, si así fuera el caso.

**Comment by dipatata** [comment]
Muchas gracias!

**Comment by LeonelCurti** [comment]
Hola a todos , leyendo todo aun estoy pensando por que el enunciado de la memoria en la pag 24 muestra varias estructuras administrativas (unas cuantas) y lo que nosotros debemos meter es la tabla invertida.
Por ahi me falta leer un poco mas la teoria pero no estoy visualizando que mas podriamos meter.

**Comment by nicozar95** [comment]
Buenas
No te confundas, en el enunciado te mostramos como estaría la memoria si la dividimos en paginas de cierto tamaño.
La estructura administrativa en ese ejemplo ocupa un total de 20 bloques, osea, tu tabla de paginas invertida ocupa un total de 20 paginas, no hace falta meter ninguna estructura administrativa mas.

Si algo te quedo colgado o no entendiste del todo alguna duda que se discutió en este issue, reabrilo asi nos enteramos :)
Saludos

**Comment by LeonelCurti** [comment]
Ah, voy entendiendo.La estructura administrativa va a tener muchas entradas, entonces la partiriamos en partes de tamaño igual al de los frame y el PID negativo indicaria que se trata de una administrativa

**Comment by varas-c** [comment]
@LeonelCurti pudiste solucionarlo? Avisá si necesitas mas ayuda!

**Comment by LeonelCurti** [comment]
Una pregunta soble la tabla invertida y la funcion de hashing. Supuestamente las paginas de un proceso pueden estar ubicados en marcos no contiguos por ejemplo:
frame   pid   pag
20       6         3
21      1          2
22      6          1
23      2          1
24      6          2
En el enunciado hacen incapie de usar una funcion de hashing que obtenga colisiones para frames contiguos y no una busqueda secuencial. No estoy viendo que ganancia obtenemos en el caso que la tabla este asi de desordenada por ejemplo.

**Comment by nicozar95** [comment]
Buenas
No entiendo del todo la pregunta
La razon de una función de hashing es que sea mas rapido, en una memoria muy grande, el acceso a la misma en vez de ir una por una.

Una buena funcion de hashing solo obtiene colisiones para frames contiguos en memoria ya que una vez que detecta una colision, empieza a ir evaluando secuencialmente desde donde le dio la colision a la pagina que desea acceder, no es lo mismo que despues de una colision te haga acceder secuencialmente a 500 pocisiones en la tabla que a 20, por eso es preferible que las colisiones sean a frames cotiguos. 

En un ejemplo, si yo quiero llegar al frame 35 y genero una colision con el frame 34, no esta tan mal porque puedo ir viendo secuencialmente y es solo una pagina a moverme; caso contrario, si yo quiero llegar al frame 35 y genero una colision con el 59846, y ahi la secuencia tarda un cacho mas. Con eso nos referiamos en el enunciado, que si la funcion de hash la pifea que sea por poco.

**Comment by LeonelCurti** [comment]
Ah, se va aclarando, hacer algo que no sea una busqueda barriendo secuencialmente sino que me acerque y barrer desde ese lugar ya sea para atras o para adelante. Puede ser que tenga suerte y estar cerca como puede que este mucho mas lejos el indice buscado.
