### ISSUE TITLE
Paso de New a Ready

### ISSUE THREAD

**Issue by fededri** [sisoputnfrba/foro#650]
Estamos trabajando sobre la creación de nuevos procesos y surgió la duda de cuantas paginas pedir inicialmente, lo que hicimos fue que el kernel calcule cuantas paginas ocupa el codigo, sume la cantidad maxima de paginas del stack por proceso y pida esa cantidad de paginas a la memoria. Con respecto al rechazo de la creacion del proceso  cuando la consola pide iniciar uno, verificamos en el kernel el nivel de multiprogramacion y  si esta ok pedimos a memoria que lo inicie. El nuevo proceso solo pasa el estado ready cuando la memoria le asigno paginas correctamente, segun lo que entendi del enunciado pasa a ready apenas se da el ok al nivel de multiprogramacion pero no le veo sentido en informarle a la consola que se creo el proceso para que luego reciba otro mensaje de rechazo por falta de espacio,  como lo hicimos nosotros la consola al iniciar el proceso recibe un solo mensaje informando si se acepto o no el proceso en el sistema

**Comment by fedebonisconti** [comment]
Buenas,

Lo que decís de las páginas es correcto, es la cantidad que deberían pedir.

Respecto del proceso dentro del sistema, podes pesarlo así: un proceso que no tiene suficiente memoria para inicializar, no puede ejecutar, por lo cuál termina inmediatamente. Podría hacerse una "similitud" con lo que pasa cuando hay un stackoverflow, tu proceso no tendría suficiente memoria como para seguir ejecutando (aunque sean diferentes porque uno es pasar de ready a exit, y el otro de running a exit). Pero en ambos casos están ya dentro del sistema porque el nivel de multiprogramación se los permitió.

Saludos!

**Comment by fededri** [comment]
Gracias
