### ISSUE TITLE
Funcion de hash + paginacion invertida

### ISSUE THREAD

**Issue by dipatata** [sisoputnfrba/foro#651]
Buenas,

Por lo que entiendo del enunciado, tenemos que generar una funcion la cual devuelva un indice en la tabla de paginas dado un pid y un numero de pagina.
Para simplificar el razonamiento, voy a saltear la memoria cache.

1) Ante un pedido de reservar una pagina en memoria, la misma recibe pid=2, pagina=2. La funcion hash me devuelve con estos valores, un indice en la tabla. Este registro podria estar usado por otra pagina, del mismo, o de otro proceso, con lo cual deberia recorrer secuencialmente hacia adelante hasta encontrar un frame libre (si es que hay).

2) Luego al leer la misma pagina pid=2, pagina=2, el hash me va a devolver el mismo indice de pagina y tendre que hacer el mismo recorrido secuencial que hice antes, hasta llegar a la pagina pedida.

Este razonamiento es correcto ?

Por ejemplo, una posible funcion podria ser
pid mod CANTIDAD_MARCOS

**Comment by iago64** [comment]
Que tal?

Respecto a tus preguntas:

1.- Si. efectivametne tu funcion dado un pid y un número de página te devuelve una posicion, la cual eventualmente puede estar usada entonces de ahi deberias buscar otra (generalmente de manera secuencial)

2.- Si, es el mismo procedimiento, si el resultado de tu función de hash te da una página que no es, al menos te acerco un poco y con la misma lógica que asignas deberías buscar una nueva página.

En cuanto a la función de hash, tene en cuenta que la misma tiene que reducir al mínimo la cantidad de colisiones, por ahi pid mod CANTIDAD_MARCOS te sirva pero lo que estaría bueno seria que hagas un programita chico que dado una serie de pids y paginas veas la cantidad de colisiones que te genera para ver si es viable.

**Comment by dipatata** [comment]
Muchas gracias
