### ISSUE TITLE
Duda con pedido de pagina para heap

### ISSUE THREAD

**Issue by dipatata** [sisoputnfrba/foro#652]
Tengo una consulta, en el momento que el kernel pide una pagina, el enunciado dice:

Asignar Páginas a Proceso
Parámetros: [Identificador del Programa] [Páginas requeridas]
Ante un pedido de asignación de páginas por parte del kernel, el proceso memoria deberá asignarle tantas páginas como se soliciten al proceso ampliando así su tamaño. En caso de que no se pueda asignar más páginas se deberá informar de la imposibilidad de asignar por falta de espacio.

Supongamos que el kernel pide asignar 3 paginas de heap nuevas al pid=3.
El que sabe bien cuantas paginas se habian asignado hasta el momento es el kernel, tiene una estructura especial para eso. En cambio la memoria, ante un pedido de 3 paginas nuevas deberia:
1) Barrer toda la tabla para asegurarse de cual fue la ultima pagina pedida para el pid=3
2) Luego de saber este numero, supongamos la pagina 11, empezar a asignar las paginas: 12, 13 y 14 para el pid=3

Pregunto, no podria el kernel enviar tambien el ultimo numero de pagina pedida para ese pid ? De esta manera la memoria sabe ya desde que numero empezar a incrementar.

Muchas gracias,

**Comment by iago64** [comment]
Que tal?

Muy buena pregunta! yo te hago una sola consulta, la memoria, no tiene forma de conocer el tamaño del proceso? si podes resolver el tamaño máximo de un proceso en páginas (cosa que casualmente tenes que hacer para uno de los comandos) 
No podrías como bien decís después ir asignando los frames que siguen y al final contestarle al Kernel, te asigne estas páginas?

Saludos.-

**Comment by dipatata** [comment]
Para esos casos en el que preguntas cuanto ocupa un proceso en memoria, pensaba barrer la tabla...
Tengo dos ideas y no me convencen ninguna de las dos

1) Que la memoria le pregunte al kernel por pid cuantas paginas tiene asignada (no tiene ningun sentido)
2) Que la memoria mantenga una estructura adicional con la cantidad de paginas que asigno por proceso.

Esto siempre y cuando quiera evitar barrer toda la tabla, que aunque es por hash, si quiero barrer las paginas de un pid, voy a tener que "probar" con pagina=1, pagina=2, pagina=3 hasta que no encuentre una.

**Comment by iago64** [comment]
Efectivamente el Kernel no sabe el tamaño del proceso, el que lo sabe posta posta es la memoria, con lo cual, lo que podrias hacer seria una vez que tenes el tamaño ir viendo como ir agregando la/las paginas que te pidan ;)

**Comment by nicozar95** [comment]
Buenas
Me quede en esto:

> Supongamos que el kernel pide asignar 3 paginas de heap nuevas al pid=3.
> El que sabe bien cuantas paginas se habian asignado hasta el momento es el kernel, tiene una estructura especial para eso. En cambio la memoria, ante un pedido de 3 paginas nuevas deberia:
> 
>1.  **Barrer toda la tabla para asegurarse de cual fue la ultima pagina pedida para el pid=3**
> 2. Luego de saber este numero, supongamos la pagina 11, **empezar a asignar las paginas: 12, 13 y 14** para el pid=3

No necesariamente te puede quedar asi, la asignacion de las paginas te puede quedar discontinua, puede que la pagina 12,13,14 esten siendo usadas para otro proceso de pid=20 y vos no deberias pisar espacio de memoria que no te corresponda.

**Comment by dipatata** [comment]
iago64: Entonces entiendo que deberia mantener una estructura auxiliar para saber las paginas asignadas de cada proceso.
Nicozar95: Si, entiendo que pueden quedar descontinuadas, cuando me referia a pagina 12,13,14 yo decia paginas de un mismo pid, no marcos de pagina en la tabla. La pagina 12 podria estar en el marco 12, la pagina 13 en el marco 85 y la pagina 14 en el marco 2.

**Comment by iago64** [comment]
@dipatata No necesariamente, podes recorrer toda la tabla de páginas cada vez que necesitas saber el tamaño de un proceso y después solamente vas sumando el número de página, mas que estructura, bien podría ser una variable local a la función que asigna páginas a un proceso.

**Comment by fededri** [comment]
@nicozar95  me surgio una duda con esto, los numeros de paginas arrancarían siempre desde cero para cada proceso o son globales en el sistema?

**Comment by nicozar95** [comment]
@fededri No, En tu memoria tenes una cantidad de marcos y tus procesos manejan paginas.
Osea, el proceso 1 ocupa 3 paginas [0,1,2] y el proceso 3 ocupa 5 paginas [0,1,2,3,4] . 
Estas paginas estan almacenadas en frame distintos pero no es lo mismo el marco de la pagina 0 del proceso 1 que el marco de la pagina 0 del proceso 3.

**Comment by dromero-7854** [comment]
Con todo lo expuesto... Me quedó la siguiente consulta: 

Si decido utilizar una estructura auxiliar | pid | cant. paginas | La misma tendría que formar parte de las estructuras administrativas del proceso Memoria, y guardarse en los bloques de memoria reservados para tal fin ¿no?
 
Si lo último es correcto ... ¿No tendría el inconveniente de no saber cómo calcular cual va a ser el tamaño máximo de procesos que van a pedir páginas a la memoria al levantar el proceso Memoria?

**Comment by nicozar95** [comment]
La única estructura administrativa que deberías almacenar de Memoria en el malloc enorme del sistema es la tabla de páginas invertida

**Comment by dipatata** [comment]
Esta bien, se entendio que la memoria va a tener que barrer la tabla para conocer todas las paginas de un proceso. Cierro el tema. Muchas gracias

**Comment by dromero-7854** [comment]
@nicozar95 Entonces ¿se puede utilizar estructuras por fuera del malloc enorme del sistema? Si es así, me parece mejor usar una estructura para saber la cantidad de páginas de un proceso (contador), que un recorrido secuencial cada vez que el Kernel pide una página para un proceso. ¿no?

**Comment by nicozar95** [comment]
Es lo que comento @iago64  arriba 😀
La memoria debe conocer de alguna manera la cantidad de páginas que asigno a cada proceso, esto lo podés hacer como vos quieras.

En los sistemas operativos reales no contas con este lujo y tenés que buscar alguna manera eficiente de conocer el espacio de los procesos.

**Comment by dromero-7854** [comment]
Claro... pero queria confirmar que es "legal" usar estructuras por fuera del malloc enorme... Para jugar limpio en el TP jejej

Gracias!

**Comment by nicozar95** [comment]
@dromero-7854 fíjate que acá digo lo que vas a tener que almacenar en ese bloque grande de Memoria #649
