### ISSUE TITLE
Escritura del kernel a memoria

### ISSUE THREAD

**Issue by fededri** [sisoputnfrba/foro#653]
Leyendo la interfaz del proceso memoria podría entender que solo los CPUs escriben en la memoria, sin embargo el kernel necesita guardar la metadata de los bloques que están dentro de las páginas para gestionar el heap de los procesos, es así o me equivoco?

**Comment by nicozar95** [comment]
Buenas
La Memoria maneja las operaciones en la página 26/27. 
A la memoria no le importa si lo que escribe es la metadata de los bloques, el código del programa, etc.

Para la memoria ella solo escribe bytes que le piden sus clientes, siempre y cuando esté en el espacio asignado.

El Kernel es el que maneja los syscall de los scripts, si un syscall manda a escribir en un espacio del proceso Memoria, entonces el Kernel debería poder mandar a escribir en Memoria (Por algo está conectado el Kernel con la Memoria)
Saludos

**Comment by fededri** [comment]
Claro, lo que no me quedaba claro era si el kernel escribia directamente en la memoria o no porque en la interfaz siempre se hace referencia a cuando pidan escribir las CPUs.
Entonces sí escribe en memoria el kernel, gracias!

**Comment by iago64** [comment]
@fededri Si la consulta fue contestada por favor no te olvides de cerrar el issue :)

**Comment by fededri** [comment]
Cierro, saludos!
