### ISSUE TITLE
Interacción Kernel-Memoria (Alcance 1° Checkpoint)

### ISSUE THREAD

**Issue by calvoluciano** [sisoputnfrba/foro#654]
Consulta, trabajando en base al alcance del 2° Chekpoint me surge la siguiente duda,

Las operaciones que tengo que desarrollar para que trabaje Kernel-Memoria,

-SolicitarBytes de una Pagina
-AlmacenarBytes en una Pagina
-AsignarPaginas a Proceso

Ahora bien,

La operación AsignarPaginas a Proceso, en mi caso lo interpreto de forma simple, el Kernel pide una Pagina para el PID X, si la memoria dice ok el Kernel va incrementar el numero de Pagina de mi PCB.
Acá que referencia Obtengo, mi única pagina sera una referencia, un entero con referencia al inicio de la pagina otorgada por la memoria? 

Luego,

el Kernel va tener que invocar la operación  AlmacenarBytes verdad? Acá tendría que ir mandando los datos que quiero guardar? en mi caso, mando etiquetas con su etiquetas size, luego el código literal y luego   instrucciones_serializado con su size, es correcto esto? Es decir en la Pagina 1, voy aumentando el offset y voy guardando cada bloque.

O cada bloque dentro de la pagina, lo debo reservar en la primer operción? y despues mandar a almecenar los bytes?

**Comment by nicozar95** [comment]
Buenas

> La operación AsignarPaginas a Proceso, en mi caso lo interpreto de forma simple, el Kernel pide una Pagina para el PID X, si la memoria dice ok el Kernel va incrementar el numero de Pagina de mi PCB.
Acá que referencia Obtengo, mi única pagina sera una referencia, un entero con referencia al inicio de la pagina otorgada por la memoria?

¿Que te parece que debe enviar memoria al kernel despues de asignarle una pagina/s? un OK si lo pudo asignar y un FALLO si no. No creo que esta función deba devolver algo mas complicado al kernel.

>el Kernel va tener que invocar la operación AlmacenarBytes verdad? Acá tendría que ir mandando los datos que quiero guardar? en mi caso, mando etiquetas con su etiquetas size, luego el código literal y luego instrucciones_serializado con su size, es correcto esto? Es decir en la Pagina 1, voy aumentando el offset y voy guardando cada bloque.

No, **lo unico que vas a tener que almacenar en memoria de los procesos son 3 cosas: el codigo, el stack y el heap** . Para este checkpoint no hace falta que distinguir entre todo este conjunto de datos, por que solo contamos con una pagina, sin embargo estaria bueno que esten hechas las funciones en Memoria para que el Kernel pueda leer y escribir bytes en este unico frame. 
Vos tendrias que mandar todo el archivo desde consola y la Memoria deberia recibir algo como:

```
//Almacenar bytes
[PID], [0], [0 /* arranco a escribir desde el byte 0*/], [/*lo que me pese el archivo*/] y [buffer]
```

La manera en que lo envia depende del protocolo de mensajes o handshake que hallan establecido en su grupo.

**Comment by calvoluciano** [comment]
Okey, aclaradas algunas dudas.

Ahora me surgió otra, en charla con mi ayudante se nos indico que se debe enviar el código Pre-procesado, eso no me termina de quedar claro, en Memoria es necesario el código literal y la estructura obtenida del resultado de la función parser metadata_desde_literal, o solo debo guardar el código literal y luego alguien pre-procesara el código.

**Comment by nicozar95** [comment]
Buenas
¿A que te referis con pre-procesar el codigo?¿De que forma estaria almacenado el codigo?

**Comment by calvoluciano** [comment]
Pre-procesar el código entiendo es utilizar la función metadata_desde_literal de la biblioteca parser, 

Donde se obtiene esta estructura,

	typedef struct {
		t_puntero_instruccion	instruccion_inicio;	//El numero de la primera instruccion (Begin)
		t_size			instrucciones_size;				// Cantidad de instrucciones
		t_intructions*	instrucciones_serializado; 		// Instrucciones del programa

		t_size			etiquetas_size;					// Tamaño del mapa serializado de etiquetas
		char*			etiquetas;							// La serializacion de las etiquetas

		int				cantidad_de_funciones;
		int				cantidad_de_etiquetas;
	} t_metadata_program;

Eso hay que guardar, o directamente se guarda el código como llegar desde el archivo de entrada por consola.

**Comment by nicozar95** [comment]
Buenas
¿Tiene sentido almacenar esa estructura en memoria, no seria mas útil que la misma este en el PCB de tu programa? 
Creo que lo mas simple y practico seria almacenar el código puro en tu Memoria y utilizar el `t_metadata_program` como una forma de crear las estructuras administrativas para manejar el script a lo largo de su ejecucion
Saludos

**Comment by calvoluciano** [comment]
Mucha gracias,

Me sirve lo que comentas para ajustar mi diseño.

Saludos,
