### ISSUE TITLE
Puntero a la memoria asignada

### ISSUE THREAD

**Issue by fededri** [sisoputnfrba/foro#655]
Supongamos que la cpu envia un pedido de 50 bytes al kernel, este chequea en las paginas asignadas al proceso si hay espacio disponible suficiente, suponiendo que no lo hay le pide a la memoria que le de una nueva pagina para el proceso, luego escribe en la pagina nueva la metadata señalando que está libre el bloque.
Luego pone el primer bloque de metadata usado con tamaño de 50 bytes y en la posicion 55 el bloque de metadata para indicar el resto del espacio libre.

1-¿Qué es lo que se debe retornar a la CPU? el enunciado indica el offset en la pagina que en este caso seria 5. Es valido enviarle a la cpu una estructura pagina-offset indicando donde se le asigno la memoria para el heap?

Gracias

**Comment by nicozar95** [comment]
Buenas
Generalmente todas las operaciones que CPU le va a hacer de memoria a Kernel o Memoria debe ser en base a una primitiva ansisop.

¿Sobre qué primitiva estás trabajando?¿Que tipo de pedido le está haciendo a Memoria desde el Kernel?
Saludos

**Comment by fededri** [comment]
Estuve leyendo la documentacion de ANSISOP y entiendo que lo que el kernel tiene que darle a la cpu es un tipo de dato t_puntero que no es mas que un un unsigned int,  sería aceptable entonces para traducir pagina-offset a este puntero, sumar pagina+offset ?

**Comment by nicozar95** [comment]
Fijate que estuvimos charlando un poquito de ese tema en el #648 

Tambien te dejo un parafito de @jazcarate para meditar:
> La CPU nunca debería estar enterada de si hay paginacion, segmentación, paginación inverdida con caché L5 ni la mar en coche; el solo sabe pedir memoria y almacenar en memoria.
Como se trasforma ese “numero” que la CPU habla (el t_puntero) a un lugar físico; es justamente la incumbencia de la memoria.

Saludos

**Comment by fededri** [comment]
Perfecto me quedo claro con el otro issue, muchas gracias.

**Comment by dipatata** [comment]
Yo tengo una duda, entiendo perfectamente que la cpu deba ser agnostica al tipo de gestion que hace la memoria. Me parece bien que solo hable de un entero que represente pagina * size + offset.
Pero, en la pagina 26 del tp, dice

> Solicitar bytes de una página
Parámetros: [Identificador del Programa], [#página], [offset] y [tamaño]
Ante un pedido de lectura de página de alguno de los procesos CPU, se realizará la traducción a marco (frame) y se devolverá el contenido correspondiente consultando primeramente a la Memoria Caché. En caso de que esta no contenga la info, se informará un Cache Miss, se deberá cargar la página en Caché y se devolverá la información solicitada.

Como hacer que la cpu sea agnostica a la paginacion, si al pedirle a la memoria una lectura debe usar esa interfaz ? Para poder convertir de t_puntero a #pagina se debe saber el pag_size

**Comment by nicozar95** [comment]
Buenas
Que la CPU sea agnostica del tipo de paginacion/segmentacion que se este usando significa que el t_puntero no se debe estar influido por ello, que no importa para la CPU el calculo que vos haces para devolverle el t_puntero, para la CPU va a segui siendo un numero representando un offset en memoria.

¿Que tipo de operacion de la CPU requiere que se utilize esa interfaz? fijate lo que dice el enunciado al momento de levantar una sentencia:

> al momento de ejecutar una instrucción, la cpu solicitará a la memoria la entrada del Índice correspondiente a la instrucción a ejecutar, determinada por el program counter. Teniendo el byte de inicio y longitud de la instrucción,realizará la petición a la memoria en el correspondiente valor de pagina,offset y longitud.

Cuando el ansisop parser fue diseñado se penso de tal manera que no le importe el sistema en el cual esta desarrollada la memoria, si es por segmento/paginacion. 
A la CPU a la larga no le importa que estes utilizando, porque si pedis por segmento/pagina el resultado va a ser el mismo, va a ser un t_puntero desde memoria.

Reconozco que tal vez el comentario mio causo mas confusion que otra cosa (ahora lo voy a editar :confused:) y pido mil discupas
Saludos
