### ISSUE TITLE
Tamaño entradas cache

### ISSUE THREAD

**Issue by sebawars** [sisoputnfrba/foro#656]
Buenas, algo no me cierra con el enunciado cuando dice "A modo de simplificar el desarrollo
de la Caché, la misma será una estructura de tamaño **configurable** por archivo de configuración.." y abajo especifica la estructura:
● Identificador del Proceso
● Número de Página
● Contenido de la Página

Es un error?

**Comment by nicozar95** [comment]
Buenas
Tal vez esta medio confuso en el enunciado pero esta hablando de 2 cosas distintas:

- Cuando se refiere a que la cache es una estructura de tamaño configurable se refiere a que el tamaño de la misma esta definida en el archivo de configuración de la Memoria:
`ENTRADAS_CACHE;CACHE_X_PROC`

- La estructura de:

> ● Identificador del Proceso
● Número de Página
● Contenido de la Página

Hace referencia a lo que deberia tener cada una de estas entradas a la cache. ¿Se entiende?

**Comment by sebawars** [comment]
Okey y otra cosa: las estructuras administrativas que se almacenan en los primeros marcos de la memoria son la tabla de páginas? o son dos cosas distintas? (hasta ahora venía haciéndolas por separado si bien guardan lo mismo) y otra pregunta obvia capaz: al hacer dump de la tabla de páginas, las entradas tienen que mostrarse ordenadas por frame como la típica tabla invertida?

**Comment by nicozar95** [comment]
Buenas

> las estructuras administrativas que se almacenan en los primeros marcos de la memoria son la tabla de páginas? o son dos cosas distintas? (hasta ahora venía haciéndolas por separado si bien guardan lo mismo

Es la tabla de pagina inversa

> al hacer dump de la tabla de páginas, las entradas tienen que mostrarse ordenadas por frame como la típica tabla invertida?

El diseño de la misma queda a criterio del equipo, estaria bueno que sea facil de entender asi es facil la correccion. Yo te recomiendo que sea lo mas parecido a las estructuras que vos utilizas en el Modulo pero que sea "human readable"

**Comment by sebawars** [comment]
O sea no hace falta que se muestre (y que se tenga) ordenado por frame como las tablas invertidas comunes? 
![tabla](https://cloud.githubusercontent.com/assets/12797458/25413677/7df360aa-2a02-11e7-8d9e-023a98eb139a.jpg)

**Comment by varas-c** [comment]
Hola,

lo que quiere decir es que lo configurable es "la cantidad de entradas que
puede tener la cache". No el "tamaño de las estructuras administrativas"

**Comment by nicozar95** [comment]
Si hace falta que se muestre la tabla de paginas por que es una de las cosas que les pedimos que desarrollen por el comando.

La manera en que la diseñan es a criterio de su equipo, si quieren mostrar la tabla de pagina ordenada frame por frame mejor por que es mas facil la correccion, si queres mostrar la tabla ordenada por pid tambien lo podes hacer.
Tengan en cuenta que la correccion la hacemos en base de lo que muestran en pantalla los comandos que les pedimos y el log asi que debe ser lo mas facil y entendible de leer para que la correccion del TP sea lo mas llevadera posible.

**Comment by sebawars** [comment]
Okey, gracias
