### ISSUE TITLE
Duda primitivas parser

### ISSUE THREAD

**Issue by fpatalagoity** [sisoputnfrba/foro#658]
Buenas! Estoy interpretando esto y quiero saber si estoy en lo correcto:

> ...Al recibirla, la parseará, ejecutará las operaciones requeridas, actualizará los valores del Programa en la Memoria

El parser tiene en sus primitivas algunas funciones que podrían encargarse de actualizar los valores del programa en memoria, ¿el mismo parser llamaría a esas funciones una vez que termine las operaciones o nosotros tendríamos que llamarlas?

Gracias!

**Comment by nicozar95** [comment]
Buenas
Vamos por partes (para aquellos que esten perdidos estamos en la CPU):

> Al recibirla, la parseará ...

Osea, lo que hace al principio la CPU es que recibe la **sentencia** del programa y con ella genera un conjunto de primitivas, por ejemplo `llamarSinRetorno;  irAlLabel; etc`, hasta aca todo bien

> ... ejecutará las operaciones requeridas, actualizará los valores del Programa en la Memoria ...

Simple, ejecuto todas las primitivas; Alguna de estas primitivas van a requerir que algun valor del programa en la memoria cambie como el stack y/o el heap de la memoria y esto es lo que ustedes necesitan desarrollar.

Por ejemplo, una primitiva del parser puede ser esta: 
`void (*AnSISOP_asignar)(t_puntero direccion_variable, t_valor_variable valor);`
Esta funcion manda a asignar un valor (`t_valor_variable valor`) a la variable (`t_puntero direccion_variable`)

¿Que deberia hacer esta funcion? Deberia asignarle el valor a la variable  ¯\_(ツ)_/¯
¿Donde lo hace? Fijate que el que guarda el scope de la ejecucion de tu programa es el stack
¿Donde esta el stack? En Memoria, el CPU deberia mandarle a la Memoria que cambie la columna 'vars' como figura en el enunciado (pagina 32)
¿Se entendio? Cualquier cosa avisa
Saludos

**Comment by fpatalagoity** [comment]
Se entendió perfecto! Muchas gracias!
