### ISSUE TITLE
Consulta sobre multiprogramación

### ISSUE THREAD

**Issue by CDNievas** [sisoputnfrba/foro#660]
Hola queria consultarles sobre el tema de la multiprogramación del TP ya que hay muy poca información sobre eso.

La consigna dice que el grado de multiprogramacion determina la cantidad de consolas siendo escuchadas al mismo tiempo y que Kernel debe validar esto.
Ahora la pregunta es como se puede validar algo que es manejado por la funcion select() que atiende todos los mensajes que llegan al socket.

**Comment by nicozar95** [comment]
Buenas
El grado de multiprogramacion determina la cantidad máxima de procesos que pueden ser aceptados en el sistema simultáneamente al inicio de la ejecución. No necesariamente **consolas**, una consola puede correr mas de un script.
> Ahora la pregunta es como se puede validar algo que es manejado por la funcion select() que atiende todos los mensajes que llegan al socket.

Deberias ir recorriendo toda la bolsa de fd aceptados hasta hallar el que esta haciendo "algo" y deberias tener una manera de identificar cada proceso con su fd.
Saludos

**Comment by varas-c** [comment]
@CDNievas pudiste solucionarlo? Si seguís teniendo dudas, avisá y te damos una mano.

**Comment by CDNievas** [comment]
Si ya pude resolverlo, muchas gracias :)
