### ISSUE TITLE
Consulta sobre list_get() - list.h

### ISSUE THREAD

**Issue by CDNievas** [sisoputnfrba/foro#661]
Tengo una consulta sobre el funcionamiento de la funcion list_get de las commons.
El codigo es el siguiente:

```
typdef struct{
	int socket;
	int ocupado;
} strSCKT;

t_list * lista
int i = 0;
strSCKT * str;

if (list_size(lista) == 0){
	print("NULL \n");
} else {
	str = list_get(lista,i);
	printf("%d \n", (*str).socket);
	printf("%d \n", str->socket);
}
```

Segun leí lo que hace list_get es devolverte un puntero al data (la estructura creada por mi y puesta en la lista con list_add) a partir de un índice.
Pero al mostrarlo por pantalla me imprime cualquier cosa (en ambos print), reconoce que es una estructura con esos campos pero no imprime lo que es debido.

Queria saber una posible solucion.

Muchas gracias

**Comment by nicozar95** [comment]
Buenas
¿Lo debugeaste haber por donde anda? Puede que le estes pasando mal un puntero ¿Estas asignando bien los valores a la lista? 
Saludos

**Comment by mgarciaisaia** [comment]
¿Cómo creás la lista? ¿Cómo le agregás valores?

¿Qué te está imprimiendo, y por qué creés que es erróneo? ¿Qué esperarías que imprima, en cambio?

**Comment by varas-c** [comment]
@CDNievas pudiste con éste tema? Seguís teniendo errores o lo solucionaste?

**Comment by CDNievas** [comment]
Si ya pude resolverlo, muchas gracias :)

**Comment by mgarciaisaia** [comment]
_¿Cómo?_ ¿Qué era lo que pasaba?

Contá, compartí, dale :)

Un poco para que la próxima persona que tenga el mismo problema encuentre una solución antes; otro poco para validar que tu solución _realmente_ soluciona el problema.

**Comment by nicozar95** [comment]
![image](https://cloud.githubusercontent.com/assets/11698687/25643384/e24d0f56-2f75-11e7-85c3-7d0a49199b53.png)

**Comment by CDNievas** [comment]
Básicamente, las funciones de listas de las commons no me estaban funcionando como lo esperaba, y era bastante complicado seguir el código. Lo que me pasaba era que para las funciones de listas de commons necesitaban definir distintos structs, por ejemplo strSocket str1; strSocket str2 .... con esto me refiero a que si solamente declaraba un struct strSocket str para todos, y luego editaba sus campos se editaban todos los de la lista porque en realidad las funciones de lista usaban un puntero a un struct, cosa que no me servia. Así que termine implementando mis propias funciones de listas para poder generar un unico struct strSocket general y poder redefinirlo independientemente cada vez que lo agrego a la lista creada por mi.

**Comment by nicozar95** [comment]
Buenas
Me quedé pensando ¿vos malloqueaste cada elemento de la lista al añadirla o siempre le pasabas el mismo puntero?

**Comment by varas-c** [comment]
Como dijo Nico arriba, si vos queres guardar muchos structs, debes reservar
memoria para cada struct que metas. Las listas no guardan una "copia" sino
que guardan referencias.

Vos seguramente estas haciendo algo asi

MiStruct str
For(i=0;i<20;i++) {
str.campo = i
List_add(unaLista, &str)
}

Lo que vos esperas es que haya 20 structs dentro de la lista, donde cada
uno tiene un valor 0,1,2,3,4 ... hasta 19.

Pero cuando lo revisas, tooodos los structs tienen valor 19, no? Eso es
porque estas guardando la referencia del struct str, no estas "copiandolo y
metiendolo a la lista".

Si realmente queres aue funcione, deberias hacer algo asi
MiStruct* str
For(i=0;i<20;i++) {
str = Malloc(sizeof(MiStruct))
str->campo = i
List_add(unaLista, str)
}

Reservas memoria para una variable nueva, y ahi si las vas metiendo a la
lista.

Se entiende? Fijate que hay tests en el repo. Tambien se hicieron varios
ejemplos en las charlas.

**Comment by CDNievas** [comment]
Siempre le pasaba el mismo puntero, no me di cuenta que podria haber usado el malloc asi, tonto de mi parte. Gracias por la ayuda y seguramente lo termine implementando para los proximos checkpoints
