### ISSUE TITLE
Consulta [Kernel] Panificación -  Estado Bloqueado y Syscalls

### ISSUE THREAD

**Issue by alejandrog87** [sisoputnfrba/foro#662]
Buenas tardes, tengo una consulta respecto a cuando un proceso abandona el estado de ejecución y  pasa a estado bloqueado: 
según la teoría cuando un proceso está esperando un evento (una solicitud a un dispositivo de entrada-salida) pasa a dicho estado.  
En el caso del tp, cuando un script ansisop ejecuta un fopen o printf se ejecuta una syscall que el kernel debe gestionar comunicándose con el proceso filesystem, en este escenario el proceso que ejecutó dicha syscall debería pasar al estado bloqueado  hasta que se responda dicha syscall, cierto? más sabiendo que las solicitudes hacia el proceso filesystem se encolan y puede demorar un tiempo hasta que sea atendido, por lo cual si no se ejecuta otro proceso mientras el cpu quedaría con tiempo ocioso.  Luego cuando la syscall sea finalizada, el proceso volvería al estado de Ready. 
Para las syscalls de memoria (gestión de heap, modificación semaforos y var globales) el comportamiento sería el mismo,  cuando un script ansisop realiza un malloc se debe ejecutar una syscall que atienda dicha solicitud, el proceso pasa al estado bloqueado y cuando el proceso memoria responda pasará al estado ready (con el pcb modificado)  o finalizado (en caso de que no exista el espacio solicitado).

**Comment by nicozar95** [comment]
Buenas
Es tal cual lo que vos decis a excepcion de:

> Para las syscalls de memoria (gestión de heap, modificación semaforos y var globales) el comportamiento sería el mismo, cuando un script ansisop realiza un malloc se debe ejecutar una syscall que atienda dicha solicitud, el proceso pasa al estado bloqueado y cuando el proceso memoria responda pasará al estado ready (con el pcb modificado) o finalizado (en caso de que no exista el espacio solicitado).

Si hace una syscall para modificar un semaforo, depende del Kernel si tiene que bloquear el proceso o no. Como seguramente vieron en la teoria, depende del valor que tiene ese semaforos si bloquea o no el proceso.
Sobre la gestion de heap y variables globales, no se tiene que bloquear el proceso

**Comment by fededri** [comment]
Si entendi bien el flujo sería: 
Proceso pide leer en un archivo
Kernel lo pasa a bloqueados, y pide lo correspondiente al filesystem
Cuando el filesystem responda se pasa al proceso a listos.
Al momento de volver a ejecutar ese proceso el kernel le tiene que mandar los datos pedidos, o sea  que de alguna manera tendria que persistir que procesos vinieron de bloqueados y pidieron alguna informacion para poder enviarsela.

**Comment by nicozar95** [comment]
@alejandrog87 @fededri 
Buenas
Estuvimos discutiendo un poco con los demas ayudantes sobre las operaciones bloqueantes y llegamos a la conclusion que:

**La unica razon por la cual un proceso se puede bloquear en este TP es debido a los semaforos.
Las syscalls sobre el FS como tambien los de la gestion del heap no bloquean el proceso ansisop**

Estuvimos discutiendo un poco eso y les digo el resumen de la discusion y porque llegamos a esa conclusion.
Basicamente en un principio se penso que las operaciones de las syscall para leer/escribir un archivo sean bloqueante como en los sistemas operativos reales que deben esperar a una entrada/salida del disco/sdd, el problema surge que no hay un tiempo de retardo en el FS y el aceso a memoria tarda mas (por el tiempo de retardo establecido por archivo de configuracion) que la lectura de un archivo, cosa que tampoco representa lo que sucede en los sistemas realmente.
Si agregaramos este tiempo de retardo (el mismo deberia ser mucho mayor que el de la memoria como en los sistemas reales) existe la posibilidad de que se bloquie el hilo Kernel esperando por un sleep de un proceso ansisop en el FS y se quede "colgado" de todos los demas procesos ansisop corriendo, cosa que no estaria muy copado.
Si no agregaramos el tiempo de retardo y las operaciones de las syscall al FS se bloquien, entonces seria lo mismo bloquear el proceso ansisop o no en la planificacion de la misma ya que seria tan rapido para el sistema que uno no persibiria este cambio en la evaluacion del TP.

Por lo tanto llegamos a la conclusion marcada, recuerden en el enunciado del TP:

> Debido al fin académico del trabajo práctico, los conceptos reflejados son, en general, ​ versiones
> simplificadas o alteradas de los componentes reales de hardware y de sistemas operativos
> modernos, a fin de resaltar algún aspecto de diseño. En algunos casos los aspectos no fueron
> tomados de manera literal, por lo que invitamos a los alumnos a leer las notas y comentarios al
> respecto que haya en el enunciado, como así también a reflexionar y discutir con sus compañeros,
> ayudantes y docentes al respecto.

Si bien es una version alterada de como funciona la planificacion, tomamos esta decision para no complicarles la vida en el TP.
Saludos

PD: En el afan de enseñar, a veces cometemos errores... Despues vamos a publicar una errata resumiendo las correcciones al TP de los temas que salieron de este foro, si anduvieron siguiendo los issues discutidos entonces ya saben que tipo de correcciones hicimos

![image](https://cloud.githubusercontent.com/assets/11698687/26021193/31950442-375f-11e7-9aa4-16ae23fded06.png)

**Comment by fedebonisconti** [comment]
@alejandrog87 se puede cerrar? 👮

**Comment by alejandrog87** [comment]
Si, muchas gracias por las respuestas.
