### ISSUE TITLE
Duda estructura cache

### ISSUE THREAD

**Issue by sebawars** [sisoputnfrba/foro#663]
Buenas, quería saber si el campo "contenido" de la cache puede ser un puntero al cual se le asigna memoria dinámica (y por lo tanto esa memoria no estaría de corrido con el resto de la estructura) o si requieren que todo ese chorro de bytes se encuentre de corrido por ejemplo declarandolo char contenido[TAMANIOPAGINA]; (si no me equivoco esto es memoria estática que está seguida de los otros campos de la estructura)
Gracias

**Comment by nicozar95** [comment]
Buenas
No se si entendi del todo la pregunta.
El "Contenido de la Página" forma parte de la estructura administrativa que vos utilizas para administrar las entradas de la cache.

La memoria cache debería tener sus paginas , para eso trae las paginas desde la Memoria a la Cache y sabe de que proceso es la pagina("Identificador del Proceso"), que pagina es del proceso("Número de Página") y el contenido propiamente dicho, que puede ser un puntero al frame de la Memoria cache.


Saludos

**Comment by sebawars** [comment]
Justamente si ese campo "contenido" es un puntero, apunta a un espacio de memoria dinámico que no se encuentra dentro del malloc de la cache. Mi pregunta es si está bien hacer un void* contenido y asignarle memoria con malloc o si requieren que esa memoria esté dentro del malloc gigante de la cache como los int pagina e int pid que están en cada entrada de la cache y no son punteros.

**Comment by nicozar95** [comment]
No es lo mismo la estructura administrativa que utilizas en la cache que la cache en si.
El contenido seria un puntero a la pocision del malloc de tu cache

**Comment by sebawars** [comment]
La estructura de las entradas de la caché deberá ser la siguiente
● Identificador del Proceso
● Número de Página
● Contenido de la Página

Cada entrada de la cache no es una de esos?
Imagino un struct con esos tres campos y la cache como void* cache = malloc(sizeof(estructuraCache) * cantidadEntradasCache)

**Comment by nicozar95** [comment]
La cache tiene una cierta cantidad de entradas, por lo tanto la cache seria algo del estilo

 `malloc(TAMANIO_DE_PAGINA*CANT_DE_ENTRADAS_CACHE)`

Esa estructura que figura en el enunciado es la estructura para administrar la cache misma y no deberia estar guardada dentro de las paginas asignadas para la cache.

Tal vez con un ejemplo sale mas facil, suponete que tenemos paginas de 512 bytes y entra un pagina a la cache en el frame 2 de la misma (en C se empieza a contar desde 0), la pagina pertenece al proceso 5 y representa su septima pagina, entonces la estructura administrativa de la cache te quedaria:

-  Identificador del Proceso = 5

- Número de Página = 6

- Contenido de la Página = (TAMANIO DE PAGINA * ENTRADA) = 512 * 2  = 1024

Fijate que el contenido de la pagina es un offset desde donde esta esa pagina en la cache

**Comment by sebawars** [comment]
Buenísimo ahí me quedó pero en mi opinión deberían aclararlo en el enunciado porque confunde bastante que diga: "La estructura de las entradas de la caché deberá ser la siguiente". Cualquiera entendería que cada entrada de la cache almacena eso.
Muchas gracias.

**Comment by nicozar95** [comment]
Ahora lo estamos charlando con los otros ayudantes y en parte tenes razón en como manejamos las paginas de la cache, en un rato te lo confirmo.

**Comment by sebawars** [comment]
![cache](https://cloud.githubusercontent.com/assets/12797458/25504590/d8bf4472-2b74-11e7-8e6f-ec2981bd755d.jpg)

Se me ocurren tres modelos, es alguno de estos?

**Comment by ziggylineous** [comment]
no puedo hacer que el campo contenido apunte a un frame de los que aloco para la ram y ya? hace falta copiar todo el contenido del frame en otro lugar? lo que importa no es que para acceder a la ram haya un delay pero para la caché el acceso es instantáneo?

**Comment by nicozar95** [comment]
Buenas
Charlandolo con los ayudantes llegamos a la conclusión de que la memoria cache al estar no especificada una forma de desarrollarla pero si una forma de administrar las entradas. son libres de elegir cualquier opcion para el desarrollo de la misma, siempre y cuando se respete el algoritmo de remplazo de paginas y este bien justificada la forma en que la desarrollaron en la evaluacion.
