### ISSUE TITLE
Duda con asignación de memoria a procesos 

### ISSUE THREAD

**Issue by picollomartin** [sisoputnfrba/foro#664]
Buenas 
La consulta sería si al asignar nuevas paginas a un proceso (ya sea al inicio o para el heap) deberíamos recorrer secuencialmente las estructuras administrativas (para chequear si tenemos espacio) o empezar a partir del indice que nos arrojaría el hash para dicha pagina de ese proceso ?

En caso que tengamos que aplicar el hash, no habría que conocer el numero de página que representa esa nueva página para el proceso (en el caso de la creación del proceso no habría este problema), lo que derivaría en otra búsqueda?

Saludos

**Comment by nicozar95** [comment]
Buenas
La asignación se hace de forma continua, esto implica tener que recorrer la tabla de paginas desde el inicio hasta encontrar la primera pagina libre.

Saludos

**Comment by picollomartin** [comment]
Ok, eso para las creación nos sobra. Pero no deberíamos buscar (en el caso que se le asignen mas paginas del heap por ejemplo) la ultima entrada de dicho proceso en la tabla para saber el numero de pagina siguiente ?

**Comment by nicozar95** [comment]
Claro, suponete que le tenes que asignar 3 paginas a tu proceso, vas hasta la ultima entrada de tu tabla (que sera la vacia ya que la asignacion es continua) y le asignas las 3 paginas.

La asignacion de paginas para el Heap o para el inicio del programa (Codigo + Stack) no deberia por que tratarse diferente (si es muy diferente lo que almaceno en cada pagina de cada uno de estos segmentos del proceso).

¿A eso te referias?

**Comment by picollomartin** [comment]
Me quedó mas claro eso, pero para saber el número de una nueva página podemos tener estructuras auxiliares (del estilo pid|cant pags) ?

**Comment by nicozar95** [comment]
Ese tema lo charlamos un poquito en #652 
Si algo no te quedo del todo claro avísanos

**Comment by picollomartin** [comment]
Dale gracias !
