### ISSUE TITLE
Problema preprocesador Shared

### ISSUE THREAD

**Issue by gonziesc** [sisoputnfrba/foro#665]
Buenas!
Tenemos un problema con la Shared Library. Está implementada, anda y compila. El tema es que cada vez que hacemos un cambio y lo implementamos en alguno de los procesos, tira lo nuevo en rojo como si fuese un error, por ejemplo diciendo "field could not be resolved". Después compila y los cambios nuevos andan perfecto. Tenemos configurado los includes del preprocesador y los paths and symbols, y los primeros cambios que hicimos en la shared si los detecta y no tira error. "Mágicamente", llega un momento en el que detecta los cambios y se van los errores.
La pregunta es: saben qué hay que hacer para que el preprocesador detecte los cambios en la shared library, sabiendo que ya está todo configurado correctamente, y que compila y anda?
Salydos!

**Comment by fedebonisconti** [comment]
Buenas, 

Pregunta: cada vez que decís que "anda", es cuando volves a compilar la lib, verdad? 
Recordá que cuando vos haces un cambio en la biblioteca, por más que lo guardes, no se va a ver reflejado en el linkeo, porque no estarías volviendo a compilarla.

Yendo corto y al pie, cada vez que hagan un cambio, vuelvan a compilarla :)

Saludos!

**Comment by gonziesc** [comment]
Sisi, cada vez que hacemos un cambio compilamos todo. Igualmente no se está reflejando en el linkeo. Es raro, ya que hay cambios que si están linkeados y cambios que no.

**Comment by dipatata** [comment]
Me pasa lo mismo, al agregar un cambio en el struct luego no lo reconoce y no estoy seguro que hago para que empiece a hacerlo.
Le doy build a la libreria, la quito del workspace, la agrego de nuevo, pero sigue dando el error. Finalmente me resigno y sigo trabajando.

**Comment by nicozar95** [comment]
Buenas
¿Probaron si le dan click derecho->Index->Rebuild?
Saludos

**Comment by dipatata** [comment]
Funciona !!!

**Comment by gonziesc** [comment]
Siiiii gracias!!!!

**Comment by nicozar95** [comment]
@gonziesc @dipatata ¡Genial! ¿Se puede cerrar entonces? :policeman:
