### ISSUE TITLE
Duda funcion llamarConRetorno

### ISSUE THREAD

**Issue by fpatalagoity** [sisoputnfrba/foro#666]
Buenas! Tengo una duda con la firma de esta función. Ninguno de los parámetros que tiene es la variable a la que se aplica la función en AnSISOP, es decir, si tengo la instrucción:
`d<-sumar a b c`
cuando se llama a llamarConRetorno no están como argumentos a ni b ni c. La duda es, llamarConRetorno ¿se encargaría de llamar a otras primitivas (como definirVariable por ejemplo) cuando lea dichas variables?

Saludos!

**Comment by alkchofa** [comment]
:smiling_imp::smiling_imp::smiling_imp:

Buenas, salvando las distancias con otro tp, te recomiendo que pases por [#350](https://github.com/sisoputnfrba/foro/issues/350) y por [#358](https://github.com/sisoputnfrba/foro/issues/358)

Ademas, si te interesa saber exactamente como lo hace podes pasar por [aca](https://github.com/sisoputnfrba/ansisop-parser/blob/master/parser/parser/parser.c#L165-L174).

Contanos si algo no queda claro, si?

:smiling_imp::smiling_imp::smiling_imp:

**Comment by fpatalagoity** [comment]
Leí esos issues pero no comprendo cómo añadir un elemento a "args". Entiendo que esa primitiva (llamarConRetorno) llame a definirVariable, pero definirVariable no agrega elementos a "args" sino a "vars" y no se me ocurre una forma de distinguir si la llamada la hizo una función o no... Espero ser claro con la duda, gracias desde ya!

**Comment by nicozar95** [comment]
Buenas
Fijate lo que dice el enunciado aca:

> Otro aspecto no menor a tener en cuenta es que el índice de args no se referencia por el nombre de
> la variable, sino que como se verá en el ​ Anexo II – Especificación del Lenguaje se referencian
> mediante un valor numérico comprendido entre ​ [0-9]​ y precedido por el signo ​ $

Osea que si definirVariable va a ser llamado desde una funcion, entonces el t_nombre_variable va a estar comprendido entre [0-9]​. ¿En que se traduce esto? Que vas a tener un gran `if()` en tu definirVariable.

Feliz issue numero 666
Saludos :smiling_imp:

**Comment by fpatalagoity** [comment]
AAAAAAAAAAAAAH, ahí entendí, gracias a los dos :D Cierro el feliz issue 666 jajaja

**Comment by fpatalagoity** [comment]
Me surgió una duda al querer codearlo, ¿el parser va a distinguir quién es el $2 por ejemplo? En el caso de mi ejemplo digamos... Yo sólo tendría que guardar en args la página, el off y el size.
Dicho sea de paso, en la página siguiente, en args no hay un campo ID, ¿eso es correcto?

Saludos!

**Comment by nicozar95** [comment]
Buenas
Si tenes un $2 como una de las variables, eso significa que ya tenes el argunmento 0 y 1 en tu contexto, eso significa que te va a llamar a definirVariable primero con el nombre 0 y dsp con el nombre 1.
Fijate como figura la descripcion de obtenerPocision:
		

> 
>  OBTENER POSICION de una VARIABLE
> 
> Devuelve el desplazamiento respecto al inicio del segmento Stacken que se encuentra el valor de la variable identificador_variable del contexto actual.
> En caso de error, retorna -1.
> 
>@sintax	        TEXT_REFERENCE_OP (&)
>@param	identificador_variable -> Nombre de la variable a buscar 
**(De ser un parametro, se invocara sin el '$')**
>@return	Donde se encuentre la variable buscada
>
>t_puntero (*AnSISOP_obtenerPosicionVariable)(t_nombre_variable identificador_variable);

Osea cuando vayas a obtener la posicion de un parametro, va a buscar la variable con el nombre '2' no va a buscar la variable '$2', el parser no distingue entre variables con nombre, por ejemplo 'a' y argumentos de una funcion, pero cuando llames a una funcion con parametros te va a mandar a escribirlos en distintas pocisiones.

Si, en args no habria un campo ID porque el ID seria el identificador que te detecta el parser (osea de 0-9), en el indice del stack deberias guardar el argumento como pagina, offset y tamaño.

Saludos

**Comment by fpatalagoity** [comment]
Bien, entonces:
1) ¿Está bien que yo en definirVariable me fije si '$' es el primer carácter de la variable que quiero definir para saber si me llamó una función?
2) ¿El campo ID NO tiene que estar en la estructura args en ningún momento? (en criollo, en esa página del TP ese campo no tendría que existir en esa estructura)

Gracias!

**Comment by nicozar95** [comment]
Buenas

> ¿Está bien que yo en definirVariable me fije si '$' es el primer carácter de la variable que quiero definir para saber si me llamó una función?

No, el parser te lo va a ser solo, para diferenciar entre un argumento y una variable yo me fijaria en el nombre de la variable con algo como esto:
`if (nombre_variable >= '0' && nombre_variable <= '9')`
Tal vez halla otras primitivas que tengas que hacer esa comparacion.
> ¿El campo ID NO tiene que estar en la estructura args en ningún momento? (en criollo, en esa página del TP ese campo no tendría que existir en esa estructura)

Ojo! args no esta escrito en ninguna pagina, forma parte de tu PCB que el Kernel se lo manda a la CPU, (estuvimos charlando un poco de eso en #659),
En el enunciado del TP pusimos a modo de ejemplo sobre el indice del stack que el argumento en el contexto 1 tiene ID, mas que nada para que no pierdan el hilo del ejemplo que el valor en el primer argumento es el mismo que en la variable 'a' , pero a medida que continua el ejemplo no le damos mas bolilla a ese campo y hacemos la aclaracion abajo.
En criollo, el campo ID en el argumento no tiene sentido porque los valores que puede tener son 0-9 dependiendo de la funcion a ejecutar.

Saludos

**Comment by fpatalagoity** [comment]
Gracias! :D
