### ISSUE TITLE
Duda con algoritmo de reemplazo de cache

### ISSUE THREAD

**Issue by dipatata** [sisoputnfrba/foro#667]
Buenas, tengo una duda con el algoritmo de reemplazo de registros en cache, en el tp dice:

> (pudiendo no alcanzarse el máximo establecido por proceso, hasta incluso no tener ninguna entrada por encontrarse la caché totalmente llena)

No entiendo, si el algoritmo es LRU, y es expropiativo entre procesos, como entonces es posible entonces que una pagina pueda no alojarse en cache ?

Si el pid=2 pide una pagina que no esta cacheada, ya alcanzo el maximo permitido, y el ultimo marco utilizado pertenece a otro proceso, okay, lo entiendo, no podria cachearla.
Pero si un proceso puede desalojar la pagina menos utilizada aun si pertenece a otro proceso, como es posible que un pid no alcance el maximo permitido de paginas cacheadas ?

Leyendo el issue
#663 
Algo quedo confuso, en resument, yo puedo tener una t_list* de struct (int pid, int pagina, char* contenido) como una cache ? O si o si necesito un malloc gigante (cantidad * tamanioCache) para la cache, y luego una estructura administrativa que apunte a lugares de ese malloc ?

**Comment by iago64** [comment]
Buenas!!

Puede que haya quedado medio confuso en el enunciado, pero a lo que apunta es que no tenes que de entrada reservarle todo el espacio maximo que puede usar en la cache al proceso cuando entra, porque por ej podes tener un proceso que se arregla con 3 paginas y si el limite maximo es 6, nunca vas a llegar a ese limite porque tenes todo lo que necesitas en 3 paginas.

Respecto a la implementación de la cache, la idea seria un gran malloc con la estructura que esta en el enunciado donde tenes:

PID | #Pag | Datos

Slds.-

**Comment by iago64** [comment]
Solo a modo de comentario (en realidad porque me acaban de preguntar lo mismo)
Si la cache esta llena, se elige una victima y el proceso entra a tener una página en cache, eso de que si esta llena no entra quedo de legado de la idea original de hacerla con reemplazo local. Mala mía, perdón!

Por otra parte, lo de la implementación de la cache es solamente _Una idea_ si lo quieren hacer de otra forma esta perfecto, lo que si, si vas a tener el gran malloc, vas a tener que encargarte de tener una función que recorra ese malloc (muy parecido a como vas a tener si lo implementas en una lista, lo único que te va a cambiar es como accedes a ese espacio, si con una lista de las commons o haciendo desplazamientos de una estructura en un array ;) ).

**Comment by dipatata** [comment]
Perfecto, quedo clarisimo, gracias.

**Comment by ziggylineous** [comment]
Puedo tener un par de estructuras aparte de esas entradas de cache para ayudarme a hacer la susitución LRU? Ponele un contador de entradas vacías (así sé si no tengo que expropiar a otro proceso) y un diccionario de la forma { proceso: [entradas] } (así se si tengo que expropiar al mismo proceso o buscar a cual proceso expropio). Porque si no, creo que hay que recorrer varias veces la estructura administrativa para saber eso (y hay que lockearla entera me parece)

**Comment by nicozar95** [comment]
Buenas @ziggylineous 
Estuvimos charlando un poco de eso en #675 
TL;DR: Si, deberias tener una estructura aparte para ayudarte con el reemplazo de las entradas del cache.
Saludos

**Comment by dipatata** [comment]
Una consulta con lo que dijo @ziggylineous 

> (así se si tengo que expropiar al mismo proceso o buscar a cual proceso expropio)

Entiendo que la expropiacion nunca es al mismo proceso. Digo, expropias la pagina menos utilizada, no te interesa si pertenece o no al mismo proceso...

1) Alcance el maximo permitido de paginas de cache por proceso ?
     SI: Entonces no podes pedir otra.
     NO: Entonces desaloja la menos utilizada y y cachea la que necesites.

**Comment by iago64** [comment]
@dipatata Efectivamente, es como pensas:

Si alcanzaste el máximo, tenes que matar alguna tuya, 
Si no alcanzaste el limite podes buscar a quien sacrificarle una página, incluso si eso hace que un proceso pierda su única pagina en Cache.

Slds.-

**Comment by dipatata** [comment]
Ah, pero lo que estas diciendo no es lo que dije yo.
Yo hablaba de que sea desalojo global SIEMPRE.
Vos estas hablando de desalojo local o global depende la situacion. Cuando un pid alcanzo el maximo de paginas, entonces se desaloja localmente. Si no lo alcanzo, entonces desaloja global.
Es asi entonces ? No quedo claro

**Comment by nicozar95** [comment]
> Cuando un pid alcanzo el maximo de paginas, entonces se desaloja localmente. Si no lo alcanzo, entonces desaloja global.

Claro, el desalojo es global eso significa que puedo sacarle una entrada de la cache a cualquier proceso, ahora bien, en este TP establecimos un limite de entradas por cada proceso, eso significa que no pueden haber mas de una cierta cantidad de entradas de un mismo proceso en la memoria cache, hasta aca nada nuevo.

El problema esta en que si yo alcance el maximo de entradas en la cache para mi proceso y tengo que alocar otra entrada mas en la cache, si o si voy a tener que matar a uno de los mios, ya que no puedo superar la cantidad de entradas por procesos definido en el archivo de configuracion.

En el caso de que no haya llegado a mi capacidad maxima de entradas en la cache, desalojo sin fijarme si la pagina es de mi proceso o de otro.¿Puede que la pagina que desaloje sea una pagina de mi proceso si bien no alcance el maximo? Si, totalmente, depende del algoritmo LRU de la cache.

¿Es asi como funciona realmete una memoria cache en la vida real, tiene un limite de entradas por proceso? No necesariamente, depende mucho del hw que este estableciendo y de varios factores mas.
Este TP es una version alterada de la realidad y lo diseñamos de tal manera para ver como aplican los conocimientos de remplazo de pagina de memoria.

**Comment by dipatata** [comment]
Gracias, queda muy claro.
