### ISSUE TITLE
Args en Vars

### ISSUE THREAD

**Issue by ziggylineous** [sisoputnfrba/foro#668]
hola. es necesarios tener separadas los argumentos y las variables en un nivel del stack? no alcanza con un solo diccionario? (para ahorrarme unos ifs cuando pide pos de variable y cuando crea 1 y la serialización separada)

**Comment by nicozar95** [comment]
Buenas
Si, deberías tener separadas las variables y argumentos en el stack. Mas que nada por una cuestión de que en la vida real se ve esta [diferencia entre ambos, donde se almacenan y como se utilizan](https://reverseengineering.stackexchange.com/questions/1722/determining-if-a-variable-is-local-or-an-argument-passed-to-a-function). y en el TP tratamos que sea lo mas parecido a la realidad (nos tomamos algunas libertades para no complicarles la vida tambien).

Fijate tambien que estuvimos hablando un poco como manejar eso en #666  
Saludos
