### ISSUE TITLE
Consulta sobre error

### ISSUE THREAD

**Issue by samanthabillino** [sisoputnfrba/foro#669]
![consultica](https://cloud.githubusercontent.com/assets/22395396/25686352/ee42f022-3043-11e7-8dd1-bbc33a51b14f.jpg)
Hola! Tengo una consulta, yo cree las funciones del ansisop en un ansisop.c que ya esta incluido en cpu.c. La cuestion es que cuando yo nombro la función me la reconoce, pero al compilarlo me tira un error de "referencia a #elnombredelafuncion# sin definir" y de yapa me tira un make *** [CPU] error 1.
Ahora si yo copio la función, por ejemplo en el caso de la foto "definirVariable" en cpu.c no me tira mas ese error
Alguien sabe como lo puedo solucionar?
Gracias!!

**Comment by nicozar95** [comment]
Buenas
¿Nos podrías mostrar que te muestra la consola de eclipse al compilar?
Saludos

**Comment by samanthabillino** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/22395396/25689522/440d447e-305f-11e7-9641-7c56957f02d5.jpg)

**Comment by samanthabillino** [comment]
> Building target: CPU
> Invoking: GCC C Linker
> gcc -L"/home/utnso/workspace/tp-2017-1c-caia/Socket/Debug" -L"/home/utnso/workspace/tp-2017-1c-caia/FuncionesGenericas/Debug" -o "CPU"  ./src/CPU.o ./src/ansiSop.o ./src/funcionesCpu.o ./src/funcionesSockets.o ./src/socket.o   -lcommons -lparser-ansisop
> ./src/CPU.o:(.data+0x0): referencia a `definirVariable' sin definir
> ./src/CPU.o:(.data+0xc): referencia a `asignar' sin definir
> ./src/CPU.o:(.data+0x28): referencia a `retornar' sin definir
> collect2: error: ld returned 1 exit status
> make: *** [CPU] Error 1
> 
> 00:20:10 Build Finished (took 456ms)
> 
>

**Comment by samanthabillino** [comment]
![aaaa](https://cloud.githubusercontent.com/assets/22395396/25689774/75780f60-3061-11e7-9287-ea3cac39c2ba.jpg)
Estos warning tambien me aparecen. Tal vez tienen algo que ver... Es raro porque los tengo agregados a los dos y cuando las uso funcionan

**Comment by mgarciaisaia** [comment]
Hay que usar el buscador, che :)

Mirá el issue #201

**Comment by samanthabillino** [comment]
No es eso, no es el mismo error y si pongo eso me tira error precisamente porque queda -l-l . 
El error esta en algo de que no me toma lo que yo defini en otro .c y .h.....
Si alguien me puede ayudar, se lo re agradezco.

**Comment by nicozar95** [comment]
Buenas
De lo que muestra por pantalla me quedo con esto:

> Building target: CPU
> (...) ./src/funcionesSockets.o ./src/socket.o **-lcommons -lparser-ansisop**
> (...)
> make: *** [CPU] Error 1

Ahi te dice "claramente" que estas tratando de compilar primero las commons y despues el parser, fijate si cambiando el orden de compilacion funca.
Si todavia seguis con el problema tal vez sea mejor verlo en vivo y en directo, si te podes pasar el sabado por soporte asi te damos una mano mejor.
Saludos

**Comment by mgarciaisaia** [comment]
☝️☝️☝️

Eso, o bien mirate el video de http://faq.utn.so/errores-eclipse y hacele caso.

Queremos ayudarte, pero para _poder_ necesitamos esa otra mitad :)

**Comment by samanthabillino** [comment]
Hola!
Sobre cambiarle el orden me sigue tirando exactamente lo mismo pero con el orden invertido. Como dice el video les copio lo que me aparece en la consola. Pido disculpas por haber sacado captura de pantalla directamente.
>  gcc -L"/home/utnso/workspace/tp-2017-1c-caia/Socket/Debug" -L"/home/utnso/workspace/tp-2017-1c-caia/FuncionesGenericas/Debug" -o "CPU"  ./src/CPU.o ./src/ansiSop.o ./src/funcionesCpu.o ./src/funcionesSockets.o ./src/socket.o -lparser-ansisop  -lcommons 
> ./src/CPU.o:(.data+0x0): referencia a `definirVariable' sin definir
> ./src/CPU.o:(.data+0xc): referencia a `asignar' sin definir
> ./src/CPU.o:(.data+0x28): referencia a `retornar' sin definir
> collect2: error: ld returned 1 exit status
> make: *** [CPU] Error 1
En rojo estan solo las "referencias a ... sin definir" .
Gracias por la paciencia!!

**Comment by jazcarate** [comment]
🤔 
¿Como hiciste para agregar, o cambiar el orden, de `-lparser-ansisop` y `-lcommons`?

Mi spidey-sense dice que faltó agregar la biblioteca del `Parser`. Una solución "rápida" sería _[instalarla](https://github.com/sisoputnfrba/ansisop-parser#guía-de-instalación)_.

**Comment by samanthabillino** [comment]
La tengo instalada. Habia hecho todo.
Lo solucione, pero lo solucione generando otro .c y .h nuevo. Rarisimo. 
Para cambiar el orden elimine desde build y settings, y los puse en el order parser ansisop y commons.
Cierro el issue, sinceramente no entiendo todavia de donde salia este error.
