### ISSUE TITLE
consulta File System

### ISSUE THREAD

**Issue by tomasdepi** [sisoputnfrba/foro#670]
Hola, me surgieron algunas dudas con el filesystem:
1) Esta quizá es un poco obvia. El filesystem se compone de n bloques de un tamaño determinado, ¿esta información la obtengo por archivo de configuración?

2) ¿De que me sirve tener en Metadata.bin el campo MAGIC_NUMBER=SADICA? Imagino que es simplemente para reconocer que esa metadata pertenece a un filesystem de tipo sadica.

Saludos, gracias

**Comment by mgarciaisaia** [comment]
Hey, ¡es super válida la consulta!

El proceso FileSystem recibe como parámetro la ruta de su archivo de
configuración, y ese archivo tiene un campo con la ruta del punto de
montaje - en otras palabras, "dónde están los datos".

Y la especificación de SADICA te cuenta que, por ejemplo, los file systems
SADICA tienen en su raíz un directorio llamado Metadata, que contiene un
archivo llamado Metadata.bin y otro Bitmap.bin. Además, en la raíz hay un
directorio Archivos, que contiene un archivo por cada archivo "de usuario",
y otro Bloques, en que habrá un archivo por cada bloque de datos del FS.

Digamos, la especificación de SADICA te cuenta que un FS SADICA usa al FS
nativo de la máquina en que está corriendo para almacenar su información.

La especificación dice que es el archivo Metadata/Metadata.bin el que
indica cuántos bloques y de qué tamaño habrá en el FS.

Además, ese archivo tiene el MAGIC_NUMBER. Podés googlearlo un poco, pero
un magic number es una especie de identificador medio aleatorio que cada
formato de archivo "canta" para sí mismo, para que los programas sepan si
ese archivo _realmente_ está queriendo seguir la especificación del
formato, o si es un archivo  cualquiera que nada que ver.

Digamos, podría existir en cualquier computadora un archivo Metadata.bin
dentro de un directorio Metadata. Al fin y al cabo, es un nombre
cualquiera, dentro de un directorio. Pero eso no significa necesariamente
que sea parte de un FS SADICA - quizá un usuario simplemente quiso usar
esos nombres.

Ahora, si la chance de que eso pase "por casualidad" es baja, imaginate si
_encima_ ese archivo tiene una entrada que diga MAGIC_NUMBER=SADICA. Buen,
es mucho mucho mucho menos probable que sea un error - ya seria demasiada
demasiada casualidad. El Magic number es eso: una forma sencilla de tener
algo más de confianza en que un archivo sigue una especificación dada. No
es una garantía absoluta, obvio, porque puede ser casualidad igual. Pero es
tan tan improbable, que confiamos bastante en que lo sea. Y podemos,
fácilmente y con mucha seguridad, descartar cosas que _no sean_ de ese
formato.

**Comment by tomasdepi** [comment]
Listo, gracias.
