### ISSUE TITLE
Instrucciones básicas de ANSISOP para el Checkpooint N°2

### ISSUE THREAD

**Issue by gustofa** [sisoputnfrba/foro#671]
Hola.
En el detalle del checkpoint nro. 2 dice respecto del proceso CPU

> Se visualiza ya la implementación de algunas instrucciones básicas de ANSISOP.

Cuales serían las instrucciones esperables que habría que tener?
O por cuales aconsejarían ustedes empezar?
Como para apuntar los cañones a esas y no a otras en vista de lo de mañana.

**Comment by nicozar95** [comment]
Buenas
En un principio nos gustaría que para este checkpoint hallan jugado un poco con las primitivas del parser y tengan una idea como funciona el parser, no esperamos que implementen correctamente una primitiva en particular, sino que vayan jugando con las primitivas y empiecen a desarrollar algunas.
Yo te recomiendo que arranques con las funciones sencillas(obtenerPocision por ejemplo) y de apoco vayas avanzando hasta las mas complicada(las syscalls).
Saludos

**Comment by jazcarate** [comment]
Sumo a la respuesta:
Pasate por el _nuevo y mejorado_ [repo del parser, donde subimos un proyectito de juguete de una CPU](https://github.com/sisoputnfrba/ansisop-parser/tree/master/dummy-cpu).

A grandes razgos, es una CPU que ejecuta un programa facil _(je, je, je, [el nombre](https://github.com/sisoputnfrba/ansisop-parser/blob/master/programas-ejemplo/facil.ansisop))_:
```
begin
	variables a, b
	a = 3
	b = 5
	a = b + 12
end
```

con las primitivas de: `AnSISOP_definirVariable`, `AnSISOP_obtenerPosicionVariable`, `AnSISOP_finalizar`, `AnSISOP_dereferenciar` y `AnSISOP_asignar`.

Como para empezar por algún lado 🕺

**Comment by gustofa** [comment]
Clarísimo. Muchas gracias.
