### ISSUE TITLE
Problema al cargar librerias

### ISSUE THREAD

**Issue by AltTomas** [sisoputnfrba/foro#672]
Hola a todos, estoy teniendo problemas al cargar las librerías propias que hicimos para el TP.
El problema es el siguiente al hacer RUN de uno de los proyectos:

>  /home/utnso/workspace/tp-2017-1c-Codeando-por-un-sueldo/consola/Debug/consola: error while loading shared libraries: libcpus-commons.so: cannot open shared object file: No such file or directory

Esto sucede en todos los otros, salvo uno (que las utiliza). La configuración es la misma en todos los proyectos. El LD_LIBRARY_PATH el proyecto que funciona no lo tiene y cuando se lo agrego a los demás poniendo como variable `${workspace_loc:cpus-commons}/Debug` o `${workspace_loc:tp-2017-1c-Codeando-por-un-sueldo:cpus-commons}/Debug` o `${workspace_loc:tp-2017-1c-Codeando-por-un-sueldo/cpus-commons}/Debug` o `${workspace_loc:tp-2017-1c-Codeando-por-un-sueldo}/cpus-commons/Debug` no funcionan, de ninguna manera, ponga lo que ponga, haga lo que haga.

Me parece raro porque a los demás les anda y tenemos todos el mismo path, de hecho borre todo el proyecto y clone e importe todo de 0 y sigue exactamente igual. 

Las librerías se compilan sin problemas, de hecho todo se compila sin problemas.

Gracias de antemano, Tomás.

**Comment by nicozar95** [comment]
Buenas
Tirame un poco mas de info, fijate aca :) ->  http://faq.utn.so/errores-eclipse 
¿Como tenes configuradas tus shared librarys?¿Es una propia que hicieron ustedes?

El LD_LIBRARY_PATH deberia apuntar al libcpus-commons.so que generalmente suele estar en donde te lo compila, en general el famoso directorio 'Debug' ¿Donde te generando el .so?
Saludos

**Comment by AltTomas** [comment]
El .so me lo genera en cpus-commos/Debug, o sea, el path donde genera el .so está bien, de hecho uno de los proyectos me lo reconoce bien y funciona y todo. El LD_LIBRARY_PATH aputa ese directorio, por lo que ahí no debería  haber problema.

 El video lo ví, pero sinceramente no sé que más info te puedo dar, es todo lo que veo que me dice Eclipse del error y te estoy dando todos los datos que vi que se piden en estos casos. Aún así no hay manera de hacerlo funcionar.

De todos modos, en el Linker la librería está agregada, el search path está bien. En compiler el include path está bien. 
En path and symbols en las pestañas include y library está cpus-commons (nombre de la libreria), en library path está el path cpus-commos/Debug y en references está checkeado cpus-commons.

Lo que me parece extrañisimo, es que un proyecto funcione bien y los otros con iguales configuraciones no.

**Comment by nicozar95** [comment]
¿Cuando dejo de andar la compilacion de tu proyecto al agregar la shared library?¿Ya habias usado una shared library en el proyecto que estas desarrollando?

Con estos tipos de errores es muy comun pasarse algo por alto a la hora de chequearlos, no tengo una solucion magica por que no se como tenes configurados tus proyectos, como esta configurada tu shared library, ni como esta el entorno de tu VM, pero si te puedo decir que estos tipos de errores son mucho mejor verlos en vivo asi nos damos cuenta de estos temas, si podes pasarte mañana por Campus o Medrano asi lo vemos bien, ¡Mejor!.

**Comment by AltTomas** [comment]
Mañana voy a ir a medrano con la notebook, justamente para ver esto. Lo postee acá porque tal vez había algo tonto de eclipse que estaba mal, pero parece que no está tan a simple vista.

Gracias de todos modos por tu ayuda!

**Comment by jazcarate** [comment]
Me parece noble ir a Medrano mañana y alguno te va a poder dar una mano; pero te dejo con la inquitúd de buscar [si no hay una herramienta del sistema operativo que te pueda listar las dependencias que tu ejecutable requiere; y donde las está intentando encontrar](http://man7.org/linux/man-pages/man1/ldd.1.html).
Nada. Dato de color 🔴

**Comment by fedebonisconti** [comment]
@AltTomas pudiste resolver el problema con la biblioteca? 👮
