### ISSUE TITLE
Duda con escritura en Memoria

### ISSUE THREAD

**Issue by EduBeghe** [sisoputnfrba/foro#673]
Buenas, hoy fui con mi grupo al Checkpoint y me quedo una duda con algo que me dijeron los chicos (los cuales nos atendieron muy bien!).

Llegué a la parte en que tengo que escribir en memoria y me encontré con 2 formas de escribir de hacerlo: Cuando escribo por primera vez en un frame y cuando escribo en un frame donde ya había escrito (son el mismo caso pero uno tiene el offset en 0). Con esta situación me surgió la duda de que pasa cuando alguien quiere escribir en un frame donde no hay mas espacio? Se lo consulte a los ayudantes y me dijeron que "si es el caso del stack no puedo seguir escribiendo, ya que no puedo asignar más páginas al stack", la cual es una restricción teórica, ya que buscamos emular lo que sucede en un sistema operativo. Y me surgió la duda, esto pasa también con el bloque de código? Me aclararon que con el Heap no pasa....entonces tengo que reservar SI O SI 2 frames de memoria como mínimo para cualquier proceso(stack y codigo)? Como diferencio un bloque normal de uno "fijo", se me ocurre que en la tabla invertida puedo agregar una columna, como si fuera una suerte de "permiso de solicitud de tamaño", lo cual solucionaría mi problema, ya que si alguien quiere escribir ahi le diria "aca no se puede seguir escribiendo una vez que superaste el tamaño del frame". También se me ocurre que en vez de un permiso de escritura sobre el frame podría poner una cuarta columna en la tabla de páginas que tenga una letra "C", "S","H", las C y S no pueden solicitar más páginas, la H si. 

Si no se entiende por favor diganme y lo aclaro.
Gracias de antemano!
Saludos,

**Comment by nicozar95** [comment]
Buenas
Te corrigo una cosita:

> tengo que reservar SI O SI 2 frames de memoria como mínimo para cualquier proceso(stack y codigo)?

No necesariamente tienen que ser 2 frames, si el codigo del programa ansisop va a ocupar una pagina en memoria, y el stack seteado en el STACK_SIZE dentro de la configuracion del Kernel es 2, entonces ni bien arranca vas a tener que reservar 3 frames en la Memoria.


> Como diferencio un bloque normal de uno "fijo", se me ocurre que en la tabla invertida puedo agregar una columna, como si fuera una suerte de "permiso de solicitud de tamaño", lo cual solucionaría mi problema, ya que si alguien quiere escribir ahi le diria "aca no se puede seguir escribiendo una vez que superaste el tamaño del frame". También se me ocurre que en vez de un permiso de escritura sobre el frame podría poner una cuarta columna en la tabla de páginas que tenga una letra "C", "S","H", las C y S no pueden solicitar más páginas, la H si.

Buenas, no hay que agregarle mas campos a la tabla de pagina invertida ya que esta debe estar escrita en Memoria y nos llena espacio valioso. Hay distintas maneras en la que uno lo puede diseñar, por ejemplo se me ocurre:

1. Vos ya sabes que lo primero que vas a escribir en la Memoria va a ser el codigo de tu programa, y gracias al PCB sabes cuantas paginas va a ocupar el codigo de tu programa, en el campo 'Paginas de codigo'.

2. Inmediatamente despues de las paginas asignadas al codigo, le vas a asignar las paginas al stack de tal manera que esten contiguas, la misma estan seteados por archivo de configuracion cuanto pueden pesar (El famoso STACK_SIZE ). Entonces si la CPU manda escribir en una pagina del stack, ya sabe que el pedido de pagina a Memoria se lo hace seguido de la asignacion de codigo y basandose en el indice de etiqueta.
**La Memoria debe tener alguna manera de controlar que cuando almacene bytes no almacene mas de lo que la pagina pueda masticar, entonces si vos sabes que el pedido de escritura te lo hizo la CPU lo unico que vas a escribir desde la CPU a la Memoria directamente, van a ser paginas del stack. El Kernel es el unico que escribe al principio el codigo del programa en la Memoria y despues manda a escribir el segmento del Heap si lo necesita, y para estos segmentos no vas a tenes drama a la hora de escribir**.Tal vez podrias controlar un cacho mas los pedidos de almacenamiento de bytes viniendo de las CPUs.
En sintesis: **Los pedidos de escritura a Memoria viniendo del CPU van a ser para escribir paginas en el stack**

3. Con el tema del segmento del heap, de eso se encarga el Kernel, con la ayuda de la Memoria, administra las paginas del heap como figura en el enunciado y va pidiendo paginas si se queda sin espacio.

Saludos

**Comment by nicozar95** [comment]
O podrias fijarte cuando vas a escribir en una pagina nueva que la pagina nueva no sea de un PID distinto o que no este asignada a nadie y eso se lo mandas al que corresponda.
Lo importante en todo esto es que **NUNCA JAMAS DEBEN AMPLIAR LA INTERFAZ DE LA MEMORIA**
:blush: 
Saludos

**Comment by EduBeghe** [comment]
Muchas Gracias chicos! Con esto puedo seguir. Cierro.

Saludos,

**Comment by dromero-7854** [comment]
Buenas a todos,

Escribo en este issue para no abrir otro con una duda que me quedo con respecto a lo leído.

Si un proceso tiene asignado [pag 3 - frame 3] y [pag 4 - frame 4] por ejemplo. Y me llega un pedido de escritura en la página 3 del proceso, que supera el tamaño de la página (o que el offset + size lo supera) 
En este caso ¿la memoria debe permitirlo porque el frame siguiente también esta asociado al proceso? ¿o la memoria debe responder "te pasates del limite" siempre en estos casos? ¿SEGMENTATION FAULT seria el error? (si existe quiero ponerle un lindo nombre)  

Otra duda es si la memoria tiene que discriminar si esta escribiendo paginas de codigo o paginas de stack (me quedo esa idea al leer las respuestas) ¿No deberia ser ajeno a todo esto y sólo escribir frames mientras esté dentro de los limites?

Espero me puedan ayudar...
Saludos

**Comment by nicozar95** [comment]
Buenas
Si no te quedo claro un tema discutido en el issue reabrilo  asi nos enteramos :)
Ahora con las consultas:

> Si un proceso tiene asignado [pag 3 - frame 3] y [pag 4 - frame 4] por ejemplo. Y me llega un pedido de escritura en la página 3 del proceso, que supera el tamaño de la página (o que el offset + size lo supera)
> En este caso ¿la memoria debe permitirlo porque el frame siguiente también esta asociado al proceso? ¿o la memoria debe responder "te pasates del limite" siempre en estos casos? ¿SEGMENTATION FAULT seria el error? (si existe quiero ponerle un lindo nombre)

Nunca ningun proceso le manda a escribir a la memoria mas de lo que tiene una pagina, por ejemplo, si tiene que escribir 51 bytes y las paginas son de 50 bytes, en vez de mandar un pedido de escritura con algo como pag:3 offset:51 deberia mandar pag:4 offset: 1.

> Otra duda es si la memoria tiene que discriminar si esta escribiendo paginas de codigo o paginas de stack (me quedo esa idea al leer las respuestas) ¿No deberia ser ajeno a todo esto y sólo escribir frames mientras esté dentro de los limites?

Es ajeno a todo eso, pero tambien tenes que mantener un grado de proteccion de memoria de los distintos segmentos.
El codigo lo escribe todo de una dependiendo de cuanto pese el codigo del programa.
El heap se pide dinamicamente, por lo tanto la unica manera en que no se pueda asignarle espacio para escritura del heap es si te quedas sin frames libres en memoria.
El stack es el problema, ya que tiene un tamaño fijo de frames asignables y no se puede expandir.

Deberias tener una manera de atacar ese problema sin expandir la interfaz que brindamos de memoria.
Saludos

**Comment by dromero-7854** [comment]
Buenas nuevamente,

Gracias por las respuestas, y voy a tener en cuenta lo de los issues para la proxima.

Voy a ver mas en detalle lo de la protección de memoria para los distintos segmentos.

Saludos

**Comment by jazcarate** [comment]
Se puede cerrar :innocent: ?

**Comment by dromero-7854** [comment]
Si si... No tengo la opción creo... Pero dale para adelante

**Comment by nicozar95** [comment]
Si te quedaste pensando cómo podés hacer para evitar que la Memoria escriba una pocision que no corresponde fíjate que en este issue puse 2 versiones de como lo pueden diseñar.
En mi opinión la mejor es la más simple pero todo depende de cómo lo justifiquen.

**Comment by kevinns** [comment]
Leyendo esto me surgió una duda 

> Vos ya sabes que lo primero que vas a escribir en la Memoria va a ser el código de tu programa

Esto es obligatoriamente así? Podría alocar primero las páginas de stack y luego de código?

**Comment by nicozar95** [comment]
Podrias no hay nada que te lo impida en el enunciado .

**Comment by lianndt** [comment]
Hola, tengo una duda con este tema.
En el momento en que kernel debe mandar el codigo de programa + stack a la memoria,  deberia hacerlo con la interfaz de "escribir bytes" de la memoria? Y de esta manera ir mandando todo por paginas, o se usa la interfaz de "iniciar programa"?  Esta ultima me genera duda porque tiene los mismos datos que el "asignar paginas"; osea se le manda el PID y una cantidad de paginas determinada. Deberia mandar el PID + el codigo de programa entero?

Gracias!

**Comment by tferraro** [comment]
Buenas @lianndt 

Asignar páginas a proceso e iniciar programa son 2 instrucciones completamente diferentes. Cito al enunciado un momento:

```
Inicializar programa
Parámetros: [Identificador del Programa] [Páginas requeridas]
Cuando el Proceso Kernel comunique el inicio de un nuevo Programa, se crearán las
estructuras necesarias para administrarlo correctamente. En una misma página no se podrán
tener datos referentes a 2 segmentos diferentes (por ej. Código y Stack, o Stack y Heap).

Asignar Páginas a Proceso
Parámetros: [Identificador del Programa] [Páginas requeridas]
Ante un pedido de asignación de páginas por parte del kernel, el proceso memoria deberá
asignarle tantas páginas como se soliciten al proceso ampliando así su tamaño. En caso de
que no se pueda asignar más páginas se deberá informar de la imposibilidad de asignar por
falta de espacio.
```

¿En que te parece que difieren?

Saludos!

**Comment by lianndt** [comment]
La segunda para asignar paginas ya la tengo implementada. En funcion al peso del codigo + el stack_size que me diga el kernel en el archivo de config, reservo las paginas iniciales. Ahora el Inicializar Programa, se usa para pasar el buffer con el codigo y el stack , todo de una? 
Esa es basicamente mi duda. Porque en el enunciado dice "Parámetros: [Identificador del Programa] [Páginas requeridas]" ,  ese segundo parametro no seria el buffer con la info? 

gracias!  @tferraro

**Comment by tferraro** [comment]
En ningún momento de la definición de ambas operaciones se habla de escribir información en las páginas, solo trabajo administrativo. ¿Como pensas que podrías hacerlo?

**Comment by lianndt** [comment]
@tferraro Mi idea era usar la interfaz de "escribir bytes", de manera de ir pasando el codigo de a bloques (osea, tamaño de pagina). Entiendo que la memoria siempre escribe de a unidades de pagina. Eso es valido para pasarle el codigo y stack? Porque en el enunciado hace referencia solamente a la CPU para escribir bytes con esa interfaz.

**Comment by nicozar95** [comment]
Es la unica manera que tiene la Memoria de escribir bytes en sus paginas. Sea codigo/stack/heap.

**Comment by lianndt** [comment]
Perfecto, gracias!

**Comment by nicozar95** [comment]
@lianndt @dromero-7854 @EduBeghe
¿Se puede cerrar este issue :sweat_smile: ? Se esta haciendo un toque largo con varias consultas

**Comment by dromero-7854** [comment]
Por mi no hay drama... Que la historia me juzgue... Mi voto es positivo para el cierre

**Comment by nicozar95** [comment]
@lianndt @dromero-7854 @EduBeghe
No escatimen en issues, si tienen una consulta hagan un nuevo issue. Si no entendieron algo que se estaba discutiendo en un issue cerrado abranlo, pero no acumulen muchas consultas distintas en un mismo issue.
