### ISSUE TITLE
FD para imprimir por Consola

### ISSUE THREAD

**Issue by cthaeh** [sisoputnfrba/foro#674]
Buenas tardes,

Hoy en el Checkpoint hablamos con un ayudante y le comentamos una duda que teniamos sobre el FD para imprimir por Consola y el ayudante nos pidio que carguemos ese tema aquí para hacerlo conocer.

El enunciado dice que el FD para imprimir por Consola es 1. Pero en el Parcer.h el tipo de dato DESCRIPTOR_SALIDA, que utiliza el analizadorLinea del Parcer.c para devolver el FD en cual escribir, esta definido como 0. Entonces cuando hago un codigo ansisop que tenga la funcion "prints", el analizador me devuelve el FD 0. 

Mi consulta es, tomo el 0 como FD para imprimir por Consola o modifico el Parcer.h para que el DESCRIPTOR_SALIDA sea 1?.

Muchas gracias.

**Comment by nicozar95** [comment]
Buenas
¡Es una buena observación! y algo que se nos paso de largo
¿Te animas a hacer un PR al repo del parser para cambiar ese valor? Siempre nos gusta que tengan una participacion en repos de la catedra :smile: 

Saludos
Nicolas Zarewsky

**Comment by cthaeh** [comment]
Muchas gracias.

No tengo problemas para cambiar el valor, pero a que te referis con PR?

**Comment by cthaeh** [comment]
No dije nada, ahi lo hice.

Saludos,
Barchiesi, Diego.

**Comment by jazcarate** [comment]
Gracias 👍
