### ISSUE TITLE
Memoria Cache - Estructura y Administración

### ISSUE THREAD

**Issue by redwarewolf** [sisoputnfrba/foro#675]
Saludos, tenía una duda respecto a la estructura y la forma de administrar la caché. De acuerdo el enunciado yo tendría una estructura administrativa de la forma pid/página/contenido, con la cual me relaciona una PID y una Página a una entrada específica dentro de mi bloque de memoria Cache (al estilo de la estructura administrativa de la memoria en si) el cuál estaría al principio de la memoria Cache lo cuál seguiría la lógica de que se auto-administra y que las estructuras de administración estarían en la propia memoria imitando la realidad? 
O cada entrada en la cache es una estructura del tipo PID/Página/Contenido, siendo el contenido no un puntero a una entrada dentro de la cache, sino el verdadero contenido el cuál quiero leer, teniendo ese struct dentro de un malloc una cantidad "entradas_cache" del config?
En el primer caso lo que cambiaría es donde tengo las estructuras administrativas, que el contenido es un puntero a una entrada, y que éstas ocuparían espacio en la propia cache.
Desde ya, muchas gracias.

**Comment by nicozar95** [comment]
Buenas
Fijate que estuvimos charlando un poco de como manejar la memoria cache en #663 
Avisa si algo no quedo del todo claro
Saludos

**Comment by redwarewolf** [comment]
Por lo que leí en ese issue, la caché sería un bloque de contenido y después, aparte, tendría una estructura para poder administrarla del estilo pid/página/númeroEntrada, pero esa estructura de administración no se va a guardar en las entradas de la caché como lo hace la memoria. Eso sería correcto? Se le pueden agregar más campos a esa estructura administrativa de ser necesario?

**Comment by nicozar95** [comment]
> Por lo que leí en ese issue, la caché sería un bloque de contenido y después, aparte, tendría una estructura para poder administrarla del estilo pid/página/númeroEntrada, pero esa estructura de administración no se va a guardar en las entradas de la caché como lo hace la memoria. Eso sería correcto? Se le pueden agregar más campos a esa estructura administrativa de ser necesario?

:policeman: **No se le pueden agregar mas campos a la estructura administrativa de la cache.** :policeman:
La cache y la memoria real son 2 estructuras distintas, en el enunciado te dice que cada entrada de la cache cuanta con PID/pagina/contenido pero no te dice como haces para manejar esa variable contenido dentro de cada una de las entradas de la cache.

Esto ustedes lo pueden manejar como quieran, por ejemplo: pueden hacer que esa variable contenido sea un puntero a un malloc enorme (distinto al de memoria real); o pueden hacer que la variable contenido sea un malloc de la pagina; o pueden hacer un malloc de las entradas de la cache que tenga las estructuras de la cache (`malloc(int + int + sizeof(tamanio_pagina))`osea, malloqueo espacio para el pid, el numero de pagina y la pagina en si); etc.
Toda elección que elijan la van a tener que justificar.

TL;DR Con los campos que te damos de la entrada de la cache (PID/PAGINA/CONTENIDO) manejalos como quieras, pero NO le podes agregar mas estructuras administrativas a la entrada de la cache ni le podes sacar

**Comment by redwarewolf** [comment]
En relación a los campos extra, puedo tener una estructura aparte que utilizo para el sistema de reemplazo LRU? No formaría parte de las estructuras administrativas de la caché, sino algo completamente separado que utilizo para poder realizar bien el LRU

**Comment by nicozar95** [comment]
Si no hay drama, de alguna manera vas a tener que tener una forma de saber cuando fue la ultima vez que usaron una pagina.
Siempre que no saques o pongas campos nuevos en la estructura de las entradas de la cache no hay problema.

**Comment by dipatata** [comment]
Perdon, pregunto aca porque es de lo que estan hablando...
Estaria mal reordenar la estructura de la cache para indicar el ultimo utilizado ?
Es decir, ante un acierto de cache, el registro de cache, va al frente de la cola. Cuando necesito desalojar, simplemente elimino el ultimo registro que estoy seguro que fue el menos utilizado.

**Comment by nicozar95** [comment]
Siempre y cuando no alteren la estructura de la entrada de la caché pueden manejarlo como quieran.

A esto me refiero que si o si deben estar esos campos iniciales de la caché, si querés manejarlo con una cola de estructuras que sean entradas(Pid/Página/Contenido) y registro de último uso, por ejemplo, son libres de hacerlo.
