### ISSUE TITLE
Stack Pointer

### ISSUE THREAD

**Issue by Matias9635** [sisoputnfrba/foro#676]
Hola, tengo una consulta sobre el valor del Stack Pointer. Se me ocurrió que la Memoria después de reservar espacio para el código y el stack, le envíe al Kernel el byte (absoluto) donde inicia este espacio reservado. Entonces como Memoria primero guarda el código y después el stack, yo se que el stack empieza una vez que termina el código, por lo que en mi Stack Pointer puedo guardar el byte que me envió Memoria sumado al tamaño del código en bytes. Pero no se si es correcto que Memoria envíe ese "byte de inicio" entonces quería preguntar primero.
Un saludo!

**Comment by nicozar95** [comment]
Buenas
El Kernel no tiene por que conocer en que pocision de Memoria se encuentra alocado el Stack, eso es responsabilidad de la Memoria. **El Stack Pointer representa en que contexto del Stack esta tu programa** para que el mismo, en caso de que cambie de CPU por la planificacion, sepa de donde buscar/escribir/leer las variables locales. **No marca una direccion en Memoria.**
Es muy importante que no expandan la interfaz de Memoria (Inicializar programa, Solicitar bytes de una página, Almacenar bytes en una página, Asignar Páginas a Proceso, Finalizar programa y Handshake del Kernel/CPU).

Saludos

**Comment by nicozar95** [comment]
Para saber en que pocision esta el stack de tu proceso te podes guiar por lo que me comentaste:

> ... como Memoria primero guarda el código y después el stack, yo se que el stack empieza una vez que termina el código...

Claro, y vos gracias al indice de código sabes cuanto pesa tu código -> sabes cuantas paginas pesa el código de tu programa -> sabes donde esta el primer byte de tu stack

**Comment by Matias9635** [comment]
Perfecto, entonces el Stack Pointer va empezar siempre en 0 y va a ir aumentando a medida que defina variables locales e ingrese a otras funciones. Lo que no me queda claro es cómo CPU sabe _(página, offset, longitud)_ **absolutos** para que Memoria entienda ya que CPU no conoce en qué dirección de memoria está el stack del proceso que se está ejecutando.
Gracias

**Comment by nicozar95** [comment]
No deberia porque saber direcciones absolutas. La CPU sabe que el stack del programa que esta corriendo esta, por ejemplo, en la pagina 4.
Si la pagina 4 esta almacenada en el frame 31 de la Memoria y su offset respecto al inicio de la Memoria es 4114083104910491039401, no le interesa a la CPU.
Suponiendo que esta pidiendo la primera variable local, lo unico que pidio la CPU fue un:

> Solicitar bytes de una página: [Identificador del Programa = PID], [#página = 4], [offset = 0] y [tamaño = 4]

Es responsabilidad de la Memoria traducir esa direccion logica a una direccion fisica y devolverle los bytes asignados.

**Comment by Matias9635** [comment]
Genial, se me había pasado que se le enviaba el PID. 
Muchas gracias!
