### ISSUE TITLE
Se busca integrante

### ISSUE THREAD

**Issue by Jaugustopose** [sisoputnfrba/foro#677]
Un integrante del grupo tuvo que dejar la materia por problemas personales, así que nos encontramos en la necesidad de incorporar a alguien.

Si existe algún alma solitaria ahí afuera, sepa que será bienvenida.

Saludos

**Comment by lcabello90** [comment]
Buenas, se buscan dos integrantes para el grupo.

Saludos,

**Comment by GerNov** [comment]
Yo y un compañero estamos buscando grupo, les dejo mi mail. 
german.novoa@gmail.com
Saludos.

**Comment by pabloxalejandro** [comment]
Yo ando buscando grupo.
Paso mi número para facilitar la comunicación: 1561270901
