### ISSUE TITLE
Procesos nuevos

### ISSUE THREAD

**Issue by fededri** [sisoputnfrba/foro#679]
Buenas, segun las ultimas aclaraciones sobre el enunciado se dijo que : 

**_El estado NEW, en la planificación del Kernel, tendrá su representación como una cola, manteniendo los procesos en ella hasta que el grado de multiprogramación permita su paso a READY. Ante una disminución del grado de multiprogramación, se debe dejar finalizar los procesos ANSISOP hasta obtener el nuevo grado._**

En caso de haber alcanzo el limite del nivel de multiprogramacion y al iniciar la consola un nuevo proceso, este se manda a una cola de New y se mantiene alli hasta que otro proceso termine.
Es valido asignarle a los procesos new un PID ya en el momento que se envian a la cola de New y enviar en ese momento el PID a la consola?

**Comment by fedebonisconti** [comment]
Buenas,

Totalmente válido, porque deberías que tener una manera de tener registrado que el proceso está en el sistema, y para eso usamos identificadores :)

Saludos!

**Comment by fededri** [comment]
Genial gracias
