### ISSUE TITLE
Comando detener planificación Kernel

### ISSUE THREAD

**Issue by picollomartin** [sisoputnfrba/foro#680]
Hola buenas la consulta es sobre este punto de kernel:

> 6. Detener la planificación a fin de que no se produzcan cambios de estado de los procesos.

Esto incluye reiniciar en algún momento la misma (con otro comando por ejemplo) o el sistema se queda frenado sin planificación indefinidamente?

**Comment by nicozar95** [comment]
Buenas
Si, seria la opcion de "pausa" del sistema para que nosotros los evaluemos en un determinado tiempo si la planificacion de los procesos es correcta.
Para reanudar podrias hacerlo con otro comando o con el mismo, como les sea mas comodo.
Saludos

**Comment by picollomartin** [comment]
Dale gracias !
