### ISSUE TITLE
CPU - Indice de código y tamaño de página

### ISSUE THREAD

**Issue by gustofa** [sisoputnfrba/foro#681]
Hola.
Al momento que CPU deba pedirle a Memoria la instrucción a ejecutar, se dice en el enunciado que deberá solicitar bytes pasandole a la memoria [Identificador del Programa], [#página], [offset] y [tamaño].

[Identificador del Programa] lo obtiene del PCB
[offset] y [tamaño] de la tabla de índice de código

Ahora bien, [#página] es mi problema. Sabiendo que el código es lo primero que kernel guarda en memoria, sabemos que este comienza en la página 0, y sumando los tamaños de las intrucciones anteriores podríamos calcular en qué página estamos, pero para ello necesitamos saber el tamaño de la página.
Leyendo el enunciado, a priori, no se menciona en ningún momento que CPU conozca este dato de la configuración del proceso Memoria, es correcto si hacemos un handshake entre CPU y Memoria tal como lo hace Kernel, para conocer el tamaño de la página?

Otra opción podrían ser modificar la tabla de índice de código agregando una columna que indique la página.
o también, si el offset es relativo al comienzo de cada página, cuando ese valor es 0 es porque comienza una nueva página. Esto no está aclarado en el enunciado, pero podría ser la solución más simple...

Saludos

**Comment by nicozar95** [comment]
Buenas
Es lo más correcto que cuando hagan el handshake entre Memoria y CPU, le pase el tamaño de la página.
Saludos

**Comment by gustofa** [comment]
Perfecto.

Gracias!
