### ISSUE TITLE
Duda para imprimir por consola

### ISSUE THREAD

**Issue by fpatalagoity** [sisoputnfrba/foro#682]
Buenas, estoy intentando imprimir por consola un número de dos formas distintas `imprimir 3` y `print 3`.
De ambas formas, el parser llama a la función llamarSinRetorno y recibe como parámetro "imprimir" o "print" (según cuál ejecute en cada momento).

La duda es, ¿está bien que llame a la primitiva llamarSinRetorno? Porque al ingresar en esa función no puedo llamar a AnSISOP_escribir dado que no tengo forma de pasarle el valor que quiero imprimir (porque llamarSinRetorno sólo recibe la "acción" por decirlo de alguna manera).

Gracias!

**Comment by nicozar95** [comment]
Buenas
Esas eran formas antiguas de imprimir por pantalla en el parser, anteriormente solo podia mandar a imprimir numeros, ahora tenes distintas maneras de impresion
```
	prints n 1+y //Imprime la variable y + 1 en pantalla
	prints s x //Imprime el contenido de la variable x de memoria
	prints l hola //Imprime un literal cadena "hola"
```
Fijate en los [test del parser](https://github.com/sisoputnfrba/ansisop-parser/blob/master/parser-tests/analizadorLineaTest.c#L74) como esta definido para imprimir algo por pantalla.

Tanto `print` como `imprimir` no son sentencias validas del parser en este TP, entonces el mismo piensa que estas queriendo llamar a una **funcion** que se llama  `print` o `imprimir` y como no lo estas guardando en ninguna variable te ejecuta llamarSinRetorno. 

Proba haciendo un `prints n 3` y fijate que va a disparar un escribir en el DESCRIPTOR_SALIDA
Saludos

**Comment by fpatalagoity** [comment]
Buenas! Gracias por la aclaración. 
Si hiciera `prints n !colas` ¿debería imprimir el contenido de la variable compartida colas?
Porque ni siquiera entra en la función de escribir del parser, es como si rompiera en el analizar línea.

Saludos!

**Comment by nicozar95** [comment]
¿Lo debuggeaste?¿Donde se te quedo tu programa?

**Comment by fpatalagoity** [comment]
No llega a entrar en la función AnSISOP_escribir

**Comment by jazcarate** [comment]
Buenas y santas.
En principio debería funcionar; pero solo para estar extra seguro le agregué [un test al parser](https://github.com/sisoputnfrba/ansisop-parser/blob/40e0328d35cf923a3cff99cd81ba5e77a30f57dd/parser-tests/analizadorLineaTest.c#L84-L89):
```
 it("imprimir un valor de una variable compartida") {
                analizadorLinea("prints n !colas", funciones, kernel);
                t_valor_variable valorColas = assertObtenerValorCompartida("colas");
                char *valorAImprimir = string_itoa(valorColas);
                assertEscribir(DESCRIPTOR_SALIDA, valorAImprimir, string_length(valorAImprimir)+1);
} end
```

y lo dejé para que imprima por consola el Test, así [quedaba en el CI el `trace` de ejecución](https://travis-ci.org/sisoputnfrba/ansisop-parser/builds/234586118#L298-L301):
```
[TRACE] 18:20:55:159 TEST/(4316:4316): Obtener valor de variable compartida [colas]
[TRACE] 18:20:55:159 TEST/(4316:4316): 	devuelve [16]
[TRACE] 18:20:55:159 TEST/(4316:4316): Escribir [16]:3 a [1]
    ✔ imprimir un valor de una variable compartida
```

Así que en principio diria que no es el Parser el que explota.
Fijate que antes de llamar a `AnSISOP_escribir`, se llama a `AnSISOP_obtenerValorCompartida`.
¿Puede que el error esté en esta función?

Saluditos

**Comment by fpatalagoity** [comment]
Bien, el asunto es que no llama a ninguna primitiva cuando le mando esa línea, pero ocurre sólo cuando quiero printear una variable compartida, cuando quiero printear una variable local, la muestra sin problemas. 
La cuestión entonces es, ¿por qué puede ser que cuando se trata de una variable compartida no llame a ninguna primitiva? La línea que recibe el analizador es exactamente la misma que vos agregaste en el test (la logueo en el log de CPU)

**Comment by jazcarate** [comment]
¿Por qué lo cerraste?
![Wisdom of the Ancients](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)

**Comment by fpatalagoity** [comment]
Jajaja, perdón, me apresuré a cerrarlo cuando gracias a @nicozar95 pude resolverlo.
Me estaba faltando declarar una de las funciones del parser en mi proyecto CPU.
Luego todo salió magnífico.

Gracias!!
