### ISSUE TITLE
File System enunciado

### ISSUE THREAD

**Issue by Emi0689** [sisoputnfrba/foro#683]
Buenas. Hoy fui al check con una duda del enunciado y me pidieron que levante este issue. 
La duda es: cuando en la parte de kernel habla de la función "abrir archivo", la misma no queda claro si debe abrirlo o crearlo, dado que en la parte del file system solo esta la función para crearlo. Parecería que dentro de la misma, tiene que validar que si ya existe el archivo solo lo habrá en modo lectura. Pero como en el enunciado no lo especifica, y dado que la interfaz no puede ser ampliada, consulto esta inquietud.

Muchas gracias por su tiempo!

**Comment by nicozar95** [comment]
Buenas
Segun el enunciado en la parte del FS:

> Validar Archivo
> Parámetros: [Path]

>    Cuando el Proceso Kernel reciba la operación de abrir un archivo deberá validar que el
>    archivo exista.

> Crear Archivo
> Parámetros: [Path]

>    Cuando el Proceso Kernel reciba la operación de abrir un archivo deberá, en caso que el
>    archivo no exista y este sea abierto en modo de creación (“c”), llamar a esta operación que
>    creará el archivo dentro del path solicitado. Por default todo archivo creado se le debe
>    asignar al menos 1 bloque de datos.

En mi opinion, cuando tengas que abrir un archivo, siempre valides que el archivo exista, en caso que no, lo creas. Por otro lado si el pedido de apertura se hizo con el flag 'c' lo creas directamente.
Saludos

**Comment by Emi0689** [comment]
Hola Nico. Gracias por tu pronta respuesta!
Ok. Quedo entonces a la espera de tu confirmación.

Muchas gracias!
Saludos.

**Comment by Emi0689** [comment]
Anexado a este Issue, tambien les consulto. Parece haber una correspondencia entre las funciones "Cerrar" del kernel y "Borrar" del FS. Pero podría pasar que quiera cerrar un archivo y no borrarlo? esto lo pregunto porque en el ansisop separa estas funciones como 2 distintas, pero en el kernel no tengo una funcion que llame para borrar el archivo o en el file system a una que sea solo cerrarlo.

Gracias por su tiempo y ayuda.

Saludos.!!

**Comment by nicozar95** [comment]
Buenas
Si podria existir el hecho que quiera cerrar un archivo y no borrarlo.
Cerrarlo: `void (*AnSISOP_cerrar)(t_descriptor_archivo descriptor_archivo);`
Implicaria que el Kernel elimine el FD de su tabla de archivos de procesos, y disminuir el contador de la tabla de archivos globales, si esta llegara a ser 0, se la sacaria de la entrada de archivos globales y se le permitiria borrar el archivo, que corresponde a otra operacion.

Borrar: `void (*AnSISOP_borrar)(t_descriptor_archivo direccion);`
Implicaria que el Kernel marque todos los bloques de ese archivo como libres y elimine la metadate de ese archivo. Siempre y cuando no tenga la entrada del archivo en la tabla de archivos globales.
Saludos

**Comment by Emi0689** [comment]
Buenos días. Gracias de nuevo por tu rápida respuesta. Me quedo bastante clara. Aguardo entonces la confirmación de la anterior. 

Saludos.!

**Comment by jbmild** [comment]
Segun yo entendi del enunciado. El abrir archivo implica solamente validar que exista. Si existe, ya podes cargarlo dentro de tu tabla global de archivos y la tabla de archivos del programa. Si no existe, tenes que fijarte con que permisos llamaron a tu funcion.si tiene permisos de creacion, lo creas y tambien lo cargas en las tablas.
El cerrar archivo, no implica el borrado. El cerrar archivo implica solamente borrar la entrada de la tabla de archivos del proceso y en caso que la cantidad de aperturas en la tabla global de archivos quedara en 0, tambien tendrias que borrar la entrada de dicha tabla.
El borrado de un archivo, solo podra hacerse si ningun otro programa lo tiene abierto.

Eso es lo que yo entendi...
Saludos

**Comment by iago64** [comment]
@jbmild Es exactamente lo que se espera que hagan, lo entendiste bien :)

@Emi0689 Te quedo claro el tema, el issue esta para cerrarlo?

**Comment by Emi0689** [comment]
Si perfecto. Muchas gracias!
