### ISSUE TITLE
Ansisop Funcion "Escribir" / File system

### ISSUE THREAD

**Issue by Emi0689** [sisoputnfrba/foro#684]
Buenas tardes, tengo una consulta: la funcion ansisop "Escribir", recibe 3 parametros, pero tanto el kernel como el FS reciben 4. Estaría faltando el offset. Podríamos entender que se quiere que se escriba al final del archivo, pero en el enunciado lo menciona al offset como una posición a leer variable en donde se quiere grabar. 

Espero puedan contestar mi inquietud. 
Desde ya gracias por su tiempo. 
Saludos!

PD: la misma duda la estaría teniendo en la funcion "leer" solo que ahí tiene "información a leer" en vez de offset. Entendiendolo como un buffer pasado por referencia y no como un posición en el archivo

**Comment by nicozar95** [comment]
Buenas
Existe otra funcion ansisop que se encarga de mover el cursor dentro del archivo, `void (*AnSISOP_moverCursor)(t_descriptor_archivo descriptor_archivo, t_valor_variable posicion);` entonces cuando vos llames a escribir, vas a escribir desde la pocision del cursor.
Ojo con esto, escribir[ no exige](https://github.com/sisoputnfrba/ansisop-parser/blob/master/parser/parser/parser.h#L309) que muevas el cursor una vez que hallas escrito algo en el archivo, solo escribe los datos en el cursor.

Lo mismo pasa con leer, que empieza a leer desde la pocision del cursor del archivo
Saludos

**Comment by Emi0689** [comment]
Muchas gracias de nuevo por tu rápida respuesta! Me quedo muy claro.
Cierro el issue.
Saludos!
