### ISSUE TITLE
Borrar archivo

### ISSUE THREAD

**Issue by jbmild** [sisoputnfrba/foro#685]
Buenos dias
estoy teniendo un problema con las interfaces que tenemos
Por un lado, el parser admite una funcion para borrar un archivo
Por otro lado, la interfaz que definieron del Filesystem, no tiene nada similar a una funcion para borrar un archivo.
Entonces, se puede borrar un archivo? De ser asi, tendriamos que ampliar la interfaz del FS para admitir la funcion de borrado.
Gracias,
Saludos!

**Comment by nicozar95** [comment]
Buenas
Fijate en las interfaces del proceso File System:

> Borrar
>     Parámetros: [Path]
>     Borrará el archivo en el path indicado, eliminando su archivo de metadata y marcando los
>     bloques como libres dentro del bitmap.

El FS tiene una interfaz para borrar archivos, lo que no tiene es para cerrar un archivo, esa es responsabilidad del Kernel.
Saludos

**Comment by jbmild** [comment]
Tenes razón, no se porque no había visto la de borrar....
Buenos gracias.
Si, lo del cerrar ya se, vendría a ser borrar de la tabla de archivos del proceso la entrada y si nadie mas lo esta usando de la tabla global de archivos.
Saludos
