### ISSUE TITLE
DESCRIPTOR_SALIDA

### ISSUE THREAD

**Issue by jbmild** [sisoputnfrba/foro#686]
Buenas,
haciendo pruebas, notamos que cuando un programa ansisop hace una impresion en pantalla nos llama a la funcion de escribir con el FD en 0 en lugar de en 1 que tiene la constante DESCRIPTOR_SALIDA.
Claramente si comparo contra la constante, nunca va a imprimir por pantalla.
Tiene un bug el parser? O en algun lado hicimos algo mal? Ya estuvimos probando y de momento no encontramos nada mal de nuestro lado.
Gracias,
Saludos!

**Comment by nicozar95** [comment]
Buenas
Fijate que estuvimos charlando de eso en #674 
Efectivamente habia un bug en el parser que ya fue arreglado, descargate la version mas nueva con el DESCRIPTOR_SALIDA arreglado
Saludos

**Comment by jbmild** [comment]
Ahh genial, gracias
Lo cierro
Saludos
