### ISSUE TITLE
CPU - Duda con definirVariable

### ISSUE THREAD

**Issue by gustofa** [sisoputnfrba/foro#687]
Hola.

Tengo dudas respecto a que debe hacer esta primitiva del parser.
En su definición dice:
	
> * Reserva en el Contexto de Ejecución Actual el espacio necesario para una variable llamada identificador_variable y la registra tanto en el Stack como en el Diccionario de Variables. Retornando la posición del valor de esta nueva variable del stack
> * El valor de la variable queda indefinido: no deberá inicializarlo con ningún valor default. 

Esto significa que deberá crear el registro dentro de la lista de Args o Vars según corresponda, hasta ahí bien, pero también debería comunicarse con Memoria para pedirle/indicarle la posición/tamaño de esa variable?
o esto último sucede recién en AnSISOP_asignar y hasta que no llega a esa función las páginas de stack en memoria estarán vacías y las variables solo existirán en el indice de stack del pcb?

Saludos

**Comment by fedebonisconti** [comment]
Buenas,

No, no debería comunicarse con memoria. Vos primero reservas el lugar para esa variable, y recién cuando se quiere asignar vas a memoria a escribirlo (y harás los chequeos correspondientes).

Saludos!

**Comment by gustofa** [comment]
ok. Gracias!

**Comment by gustofa** [comment]
Cuando me puse a codear esto me surgió otra duda.

> Vos primero reservas el lugar para esa variable, y recién cuando se quiere asignar vas a memoria a escribirlo (y harás los chequeos correspondientes).

Reservar el lugar para esa variable significa crear el registro en args o vars dentro en el stack, y ya ponerle por ejemplo (page=0; offset=0; size=4), no?

Lo que me hace ruido fue lo de los chequeos. Te estas refiriendo a ver si hay lugar en la página para esa variable o si se debe pasar a la siguiente página?
eso ya podría hacerlo al momento de reservar, porque puedo saber el tamaño ya usado en la pagina y sabe si tengo el espacio para la nueva variable.

Ahora bien, CPU no sabe, a priori, cuantas paginas de stack tiene el proceso disponible, entonces por ejemplo, si se tiene solo una pagina de stack y se llega al límite, se supone que definirVariable debe reservar lugar para la variable en la supuesta 2da pagina y que cuando vaya a escribir en memoria esa variable de un error porque no existe esa página de stack para el proceso?
cosa que cpu traduciría como Stackoverflow.

Gracias.
Saludos

**Comment by nicozar95** [comment]
Dentro de la memoria, una de las pocas operaciones que tiene es el de Almacenar bytes de Memoria y recien ahi dispara el error de que no puede asignarle mas espacio.

Es un caso muy raro el que estas presentando, en un prinicipio yo no me preocuparia si la vars/args que estamos marcando en el indice del stack no tengan espacio en el stack posta en Memoria, porque despues cuando lo vaya a escribir no va a poder. No le agreguemos mas responsabilidades a la CPU.

Generalmente el stackoverflow que esperariamos seria en el stack en Memoria y no en su indice de stack en el PCB.

**Comment by gustofa** [comment]
Clarisimo, gracias.
