### ISSUE TITLE
SADICA

### ISSUE THREAD

**Issue by Emi0689** [sisoputnfrba/foro#688]
Buenos días. Tengo varias consultas sobre como funciona el SADICA.

1) Entiendo que la información se guarda en no en los archivos creados propiamente, sino en archivos "tipo bloques" denominados 1.bin, 2.bin, etc. O sea que si quiero leer/guardar información en estos archivos, debo hacerlo en realidad en estos .bin, verdad? Todos tienen el mismo tamaño máximo de char/bytes?

2) si yo grabo un archivo con la palabra "hola" y tengo un máximo de bloques de 34 bytes, estos entraría (digamos en el 1.bin), pero sobraría espacio, el bitmap lo marcaría como ocupado? o sea provocaría fragmentación dado que el próximo a guardar estaría en el 2.bin?

Muchas gracias por su tiempo!

Saludos!!

**Comment by sciciliani** [comment]
1. Tal cual. El nombre del archivo es un indice que dice que bloques lo
componen (y su orden), por ejemplo [64, 18, 3, 453]. Fijate que no tienen
que ser necesariamente en orden o consecutivos, acordate que todos los
archivos comparten el conjunto de bloques.

Luego el contenido del archivo está compuesto por el contenido de los
archivos 64.bin, 18.bin, 3.bin y 453.bin

Si, los bloques tienen todos el mismo tamaño fijo.

Entenderás la problemática de que por error dos archivos tengan asignado el
mismo bloque o que un archivo tenga los bloques desordenados.

2. No necesariamente. Podrías grabar los primeros 4 bytes del archivo con
la palabra "hola" y luego en otra operación de escritura escribir 4 bytes
empezando del offset 30 y eso no ocuparía otro bloque.

Más aun, podrías escribir 4 bytes empezando del byte 32 y eso dejaría dos
bytes en cada bloque.


2017-05-24 9:20 GMT-03:00 Emi0689 <notifications@github.com>:

**Comment by Emi0689** [comment]
Hola. Gracias por tu pronta respuesta!

1) Super claro.
2) Esto me lleva a otra consulta. Entonces el bitmap solo se activa cuando "achivo bloque" .bin esta lleno? si me sobra un Byte el bit map queda en 0?
3) y agrego esta tercer "Entenderás la problemática de que por error dos archivos tengan asignado el
mismo bloque o que un archivo tenga los bloques desordenados." estas problemáticas se pueden/se deben solucionar en el contexto del trabajo practico?

de nuevo muchas gracias por tu tiempo.
saludos!!

**Comment by sciciliani** [comment]
2. El bitMap identifica si un bloque está libre u ocupado. Si lo asignás a
un archivo, lo usás y lo dejas registrado como si estuviera libre,
posiblemente termine asignado a otro archivo. Pensalo como usar una
habitación de hotel y dejarla marcada como disponible.

3. No y si :) Claramente un buen manejo de las estructuras administrativas
te permiten evitar entre otras cosas que por error asignes el mismo bloque
a dos archivos distintos. Un ejemplo sería el punto 2. ^

2017-05-24 9:56 GMT-03:00 Emi0689 <notifications@github.com>:

**Comment by Emi0689** [comment]
Ok bien. Me tome un rato para pensarlo y creo haber entendido bien. Muchas gracias por tu tiempo!
Saludos!
