### ISSUE TITLE
Duda parámetro t_puntero AnSISOP_leer para leer archivo de FS

### ISSUE THREAD

**Issue by fpatalagoity** [sisoputnfrba/foro#689]
Buenas, tengo una duda para implementar esta función entre CPU-Kernel-FS:
`void AnSISOP_leer(t_descriptor_archivo descriptor_archivo, t_puntero informacion, t_valor_variable tamanio)`

No entiendo si `informacion` es un puntero del Indice de Stack o si es un puntero que apunta a otro lado, dado que si apuntara al Indice de Stack, las variables que allí existen son valores enteros, con lo cual no se podría guardar un string... ¿alguna ayuda?

Gracias!

**Comment by jazcarate** [comment]
Si te puedo llevar a [los tests](https://github.com/sisoputnfrba/ansisop-parser/blob/master/parser-tests/analizadorLineaTest.c#L149-L153), la infromación es como decis, un puntero a _"algún lado"_.

Si pensamos como sería en C, uno hace algo como:
```c
char* foo = malloc(50);
int tamanio = 5;
getline(&foo, &tamanio, archivo);
```

Es muuuy parecido. Las chances son de que lo que le pases sea una posición de memoria que esté en el `heap`; pero a priori no hay diferencia.
Como AnSiSOP no es tán copado como `c` y en su stack solo puede almacenar enteros; sería medio extraño `leer` hacia una posición de `stack`; pero nade te lo impide! 
![El tio Bensabía](https://life0nthebrightside.files.wordpress.com/2014/05/spiderman-with-great-power-comes-great-responsibility.jpg)

**Comment by fpatalagoity** [comment]
Perdón, pero no estaría siguiendo tu  idea... ¿podrías guiarme un poquito más, porfa?

Gracias!!

**Comment by jazcarate** [comment]
Dos ideas:
1. La `t_puntero informacion` es un puntero *a memoria* como cualquier otro `t_puntero`; no necesariamente al Stack.
2. `AnSISOP_leer()` se inspira de [`getline()`](https://linux.die.net/man/3/getline).

¿Mejora?

**Comment by fpatalagoity** [comment]
Creo que sí jaja, gracias!
