### ISSUE TITLE
Duda funcion AnSISOP_borrar

### ISSUE THREAD

**Issue by fpatalagoity** [sisoputnfrba/foro#690]
Buenas, sólo para estar seguro de que estoy pensando lo correcto:

> 		 * BORRAR ARCHIVO
> 		 *
> 		 * Informa al Kernel que el proceso requiere que se borre un archivo.
> 		 *
> 		 * @syntax 	TEXT_DELETE_FILE (borrar)
> 		 * @param	direccion		Ruta al archivo a abrir
> 		 * @return	void
> 		 */
> 		void (*AnSISOP_borrar)(t_descriptor_archivo direccion);

`direccion` no es una ruta sino el file descriptor (no es un char* sino un int), ¿correcto?

Gracias!

**Comment by jazcarate** [comment]
Afirmativo!
Se nos pasó. Crearías el `Pull Request` 😸 ?

**Comment by fpatalagoity** [comment]
No tengo problema en crearlo, pero no sé como funcionan los pull requests... jajaja

**Comment by jazcarate** [comment]
https://github.com/sisoputnfrba/ansisop-parser/commit/fa8403229db68fa555a111b85dd6893878970c73
Cambiado 😄
