### ISSUE TITLE
FileSystem bitmap

### ISSUE THREAD

**Issue by CarolinaPonceRodriguez** [sisoputnfrba/foro#691]
Buenas que tal, tengo una consulta sobre el archivo bitmap.bin, entiendo que el mismo va a ser necesario leerlo y modificarlo de acuerdo a como se manipulen los archivos cuyos bloques van a significar cada uno un bit de bitmap. 
Ahora yo creo un bitmap en base al archivo metadata que se muestra en el tp, seria asi:
t_bitarray * bit = bitarray_create_with_mode(bitarray, vg_cantidad_bloques/8, LSB_FIRST)
 
Donde bitarray es un char * y vg_cantidad_bloques es lo que lei del metadata. La duda es como lo guardo/escribo en el archivo bitmap.bin se me ocurre que podria hacer uso de un fwrite pero no estoy del todo segura de como guardar el "el contenido" del puntero tipo t_bitarray y luego leerlo.
Podria ser asi fwrite(&bit,.....)?

Gracias.

**Comment by varas-c** [comment]
Hola!
Está bien lo que decís, el archivo lo tenés que ir leyendo y modificando según tus necesidades. Seguramente te diste cuenta que es bastante engorroso.

Quizás el amigo "mmap" te ayuda con ésto. [http://www.gnu.org/software/libc/manual/html_node/Memory_002dmapped-I_002fO.html](url)

**Comment by CarolinaPonceRodriguez** [comment]
Hola que tal, ya lo entendi, y ahora tengo otra consulta, ustedes nos darian el fs con archivos ya cargados? O yo tengo que contemplar la posibilidad de "formatear" un fs desde cero, esto implicaria iniciar un bitmap e ir cargando los archivos, si bien tengo que contemplar esto ultimo(crear archivos), lo que estoy haciendo siempre hasta ahora es iniciar mi fs vacio.

**Comment by nicozar95** [comment]
Les vamos a dar un fs con archivos ya cargados (bah! puede que les demos el /Metadata/ y el /Bloques/ y que el /Archivos/ este vacio...)
