### ISSUE TITLE
Bitmap (2)

### ISSUE THREAD

**Issue by Emi0689** [sisoputnfrba/foro#692]
Buenas tardes. Tengo una pregunta similar al anterior issue. Pero en este caso es que debería haber en el archivo Bitmap.bin?  guardo los ceros y unos de forma numérica que representan a los bloques (1 estando ocupando, 0 estando displonible)? 
De que me servirían las funciones bitarray de las commons si tengo que hacer lectura y escritura a través del archivo, no terminaría teniendo dos estructuras las cuales ambas tendría que actualizar ?

Muchas gracias por su tiempo y ayuda.
Saludos!

**Comment by varas-c** [comment]
Buenas!
El bitarray es justamente un array/vector de bits. En tu archivo bitmap.bin vas a tener guardado un bitarray como decís.
Pero para qué sirve el bitarray? Es una estructura administrativa que necesitás para saber qué bloques están ocupados y cuales están libres. 

Suponiendo que tenés el siguiente bitarray: 0-1-0-0-1 ... ¿Qué significa? Te está diciendo que el bloque 0 (posición 0 del bitarray) está libre (el contenido de la posición 0 es 0), que el bloque 1 está ocupado, el bloque 2 está libre, el bloque 3 está libre y el bloque 4 está ocupado ... y así sucesivamente (tal cual como lo pensaste)

Pero como bien decís, éste bitarray está en un archivo ... una opción es leer todo el bitarray y "llevarlo" a memoria y cada vez que cambia un valor, deberías ir actualizando el archivo ... es decir vas a estar constantemente leyendo/escribiendo un archivo con los posibles problemas que ésto te puede generar.

Por suerte a alguien ya le pasó algo parecido y se inventó una función que te ayuda con ésto, llamada "mmap" :) 

Te dejo un link para entrar en tema, igualmente googleando encontrás muchisimos ejemplos: http://www.gnu.org/software/libc/manual/html_node/Memory_002dmapped-I_002fO.html

Si no se entendió, no dudes en preguntar de nuevo!

**Comment by Emi0689** [comment]
Perfecto. Muchas gracias!!
