### ISSUE TITLE
Liberacion de paginas de HEAP

### ISSUE THREAD

**Issue by jbmild** [sisoputnfrba/foro#693]
Hola, buenas
Encontre en el tp cuando habla sobre el heap que dice:

> Si un proceso tiene una página con todos los bloques marcados como libres, esta debe ser liberada.

Mi problema con esto que si bien a nivel kernel puedo marcarla como liberada y no volverla a usar para el heap, la memoria tiene una interfaz que no permite liberar una pagina en particular y aparte de ello, dice que la interfaz de memoria no puede ser ampliada.

Sabiendo esto, como puedo desde kernel liberar dicha pagina en memoria?

**Comment by tferraro** [comment]
Buenas!

Lo hablamos puertas adentro y efectivamente, nos quedó un poco corta la interfaz de memoria. Pero tranquilo, [para esto existen las erratas :)](https://github.com/sisoputnfrba/2017-1c-esther-errata/pull/2).

Gracias por el aviso y mil disculpas!

**Comment by jbmild** [comment]
Bueno, genial por ese lado. Ahora teniendo esto nuevo en cuenta y teniendo en cuenta que la memoria da siempre paginas con numeración consecutiva. Podremos tener baches en esas paginas? suponiendo que el proceso tiene 5 paginas y libere la pagina 4 nos quedan solo las paginas: 0, 1, 2, 3, 5?
Y si se vuelve a pedir una pagina? Dicha pagina debería ser la nro 4 o la nro 6?
Saludos

**Comment by nicozar95** [comment]
Buenas
La asignacion de paginas es de forma continua, osea, que la proxima pagina que va a asignar es la pagina que sigue de las que no asigno.

Ejemplo: En mi sistema Esther, solo hay un solo proceso corriendo, el proceso x, asigne estos frames al proceso x en ese orden (suponiendo que en el frame 0 me entra la tabla de paginas):
1-2-3-4-5. 
Si despues libero el frame 3 por ejemplo, entonces los frames del proceso x son:
1-2-4-5.
Despues el kernel manda una solicitud de asignacion de paginas del heap para el proceso x, cuyos frames ahora son:
1-2-4-5-**6**
Osea que va a seguir asignando desde donde se quedo.

¿Me va a quedar un hueco en la memoria? Si y se debe resolver, fijate lo que dice el enunciado en la parte de la asignacion de paginas para el heap:

>Si el proceso ahora requiere un bloque de 250 bytes, el Kernel tendrá que pedir una página nueva
> para guardarlo. Esta situación se denomina ​ **Fragmentación Externa ​ y ​ puede ser atacada en algunos casos. Es responsabilidad del grupo realizar un análisis integral de cuáles son los casos salvables proponer un algoritmo para resolverlo.**

Saludos

**Comment by jbmild** [comment]
Si, lo de la fragmentacion externa ya lo sabemos y lo resolvemos con una defragmentacion. Mi pregunta era mas que nada lo que me respondieste con la secuencia de numeros de reserva de paginas. Que si me daba la pagina 6 o reutilizaba el numero de pagina 3 y me daba esa pagina. Sin mas. Queda resuelto. Gracias
