### ISSUE TITLE
Kernel-Permisos de archivos

### ISSUE THREAD

**Issue by CarolinaPonceRodriguez** [sisoputnfrba/foro#694]
En el enunciado dice: "El sistema permitirá la utilización de varias flags o modos de acceso al abrir un archivo. Cada flag
representa un privilegio que el proceso le solicita al sistema operativo para operar sobre un archivo.
A la hora de operar sobre un archivo, el Kernel deberá validar los privilegios del proceso en cuestión."

En donde radican los permisos en el proceso en si? Porque los mismos no forman parte del pcb del proceso ya que el mismo puede manejar distintos archivos con distintos permisos para cada uno. Veo que en la Tabla de archivos abiertos por proceso se visualizan los flags por archivo, pero eso "deberia llegar previamente de otro lado".
Tambien para redondear, el fs no cuenta con manejo de permisos para los archivos no?, sino que a este le llegan y ejecuta sus funciones de acuerdo a los mismos.

Saludos!

**Comment by nicozar95** [comment]
Los permisos son de archivos no de procesos, un proceso no puede no abrir un archivo por que "no tiene permisos de super usuario" (por ejemplo... ponele).
Si bien en los SO reales hay un grado de proteccion a los archivos establecido por que usuario creo tal archivo, en este TP no se tiene en cuenta ello.

Con los permisos de los archivos nos referimos mas que nada con los de escritura y lectura. Un proceso que abrio un archivo en modo lectura, no puede escribirlo y viceversa.

Los permisos del archivo forman parte de la tabla de archivos por procesos.

**Comment by CarolinaPonceRodriguez** [comment]
Entiendo, pero parandome como kernel, como se yo kernel que el archivo a.txt va a ser abierto por el proceso 1 en modo lectura, por el proceso 2 en modo lectoescritura y asi? A lo que voy es que se que esa informacion de permisos estara en la tabla de archivos abiertos por proceso pero lo que no se es como le "llega" al kernel esa informacion ya que este seria el que hace el "pasamano" entre el proceso y el archivo dentro o no del fs

**Comment by nicozar95** [comment]
Te digo masomenos como deberias hacer para saber el modo de apertura de los archivos:

- Cuando un proceso ansisop pide que se abra un archivo, el mismo dispara la primitiva `t_descriptor_archivo (*AnSISOP_abrir)(t_direccion_archivo direccion, t_banderas flags);`, esta primitiva va a recivir la direccion del fs de donde esta el archivo y un conjunto de flags (permisos). 

- La CPU le envia al Kernel la direccion del archivo que desea abrir el proceso junto con los flags.

- Cuando el Kernel recive esta primitiva, crea una nueva entrada en la tabla de archivos por proceso, declarando la direccion del fs, los flags o permisos con los que se llamo (r: lectura | w:escritura | rw:escritura y lectura) y el fd asociado.

- Si existia una entrada de ese archivo en la tabla de archivos globales, aumenta en uno el contador de ese archivo.

- Le devuelve a la CPU el fd asociado

Entonces cada vez que tu proceso ansisop quiera leer o escribir en un fd te fijas si tiene los permisos para ello, asociando el fd con tu tabla de archivos por proceso.
