### ISSUE TITLE
Planificación Cola New - Creación PCB e inicializacion del programa en Memoria

### ISSUE THREAD

**Issue by calvoluciano** [sisoputnfrba/foro#696]
Buenas noches,

Estoy con una duda respecto a la planificación esperada para el TP, nosotros en principio lo que pensamos es recibir el script incrementar la variable cant_programas global, crear el PCB asignándole un PID y guardando el codigoLiteral en un campo del PCB luego devolvemos el PID a la consola y metemos a ese PCB en la cola NEW, si el grado de multiprogramación lo permite ese PCB pasara a cola READY, previo a esto hago la solicitud a Memoria de las paginas necesarias y si hay espacio se enviara el código y se definen el resto de los datos de pre-procesamiento de código para terminar de definir el PCB. Es correcta esta interpretación ? Es correcto devolverle el PID a la consola previo a ingresar en la cola NEW? O debería ser al momento que pase a Ready? Porque podría no haber espacio de memoria y el programa nunca iniciar.

Saludos,

**Comment by fedebonisconti** [comment]
Buenas,

No deberías guardar el código en el PCB. Fijate que dice que:

```
A partir de esta información, el Proceso Kernel deberá solicitarle al Proceso Memoria que le asigne las páginas necesarias para almacenar el código del programa y el stack. Para simular el
comportamiento de un sistema real, también le enviará el código completo del Programa.
```
Cuando se conecta una consola crea el PCB, pide las páginas, y guarda el código (si todo sale bien).

Si pudieramos guardar todo en el PCB, no necesitaríamos la memoria :p

Saludos!

**Comment by calvoluciano** [comment]
buen dia,

El tema es que eso se me contrapone con esto,

"Los procesos no se crearán en la memoria hasta que no pasen del estado NEW al estado
READY. Esto quedará determinado por el grado de multiprogramación del sistema"

Lo consulte con nuestro ayudante pero no me termina de quedar claro, si cuando ingreso el proceso a NEW no reservo nada todavía a Memoria, y la reserva y escritura se hace en la transición NEW a READY (si la multiprogramación lo permite) , de acá es que pensaba guardar el código en el PCB hasta que al pasar a READY ahi elimino el código del PCB y lo mando a la Memoria.

Estoy mas confundido que antes.... esto no esta bien detallado en el enunciado.

Cuando meto un PCB en new, que informacion debería tener?  y en ese momento según el enunciado todavia no se deberia crear en Memoria. Es asi?

**Comment by fedebonisconti** [comment]
Punto para vos! Me lo confundí :)

No deberías reservar la memoria hasta que esté en Ready. 

Por otro lado, si estás usando una _lista de consolas_, podrías guardar el código ahí, en vez del PCB que no es tan lindo.

Saludos!

**Comment by alkchofa** [comment]
Una ultima cosa, asignale el pid una vez que te llega al Kernel. Cuando pase de new a ready, va a pedir memoria y muere si no tiene suficiente. Pero _los procesos que no tuvieron memoria para iniciar_ tenian un pid.

No se si me llego a explicar.

**Comment by calvoluciano** [comment]
Ahora me cerro la idea muchas gracias.

Saludos,
