### ISSUE TITLE
Consulta obtenerVariableCompartida

### ISSUE THREAD

**Issue by picollomartin** [sisoputnfrba/foro#697]
Hola buenas tardes, para el siguiente código el parser de ansisop llama a la funcion obtenerValorCompartida con el nombre de variable "Global\n" no debería ser solo "Global"?
> #!/usr/bin/ansisop
begin
	prints n !Global
end

**Comment by jbmild** [comment]
el \n te lo pone en todas las lineas ya que significa salte de linea. Lo que tendrías que hacer es reemplazarlo por \0 y no tengas problemas con el parser

**Comment by picollomartin** [comment]
Dale gracias!
