### ISSUE TITLE
Bit LIBRE/OCUPADO 

### ISSUE THREAD

**Issue by gvillarc91** [sisoputnfrba/foro#698]
Hay un issue relacionado pero no responde exactamente a mi duda.

Supongamos que tengo la siguiente secuencia: 10110001, donde cada bit representa el estado de un bloque (libre/ocupado) y cada bloque tiene un tamaño de 32 bytes. 
Quiero guardar información que necesita 30 bytes. Encuentro que el primer bloque libre es el de la posición dos del vector (el primer cero que hay ahi).

La pregunta es: **¿Ese bloque representado por CERO ahora debo marcarlo como UNO? Es decir, que un bloque esté ocupado significa que NO PUEDO seguir usando su espacio libre (los 2 bytes que restan para llegar a 32)?**

En otro issue pusieron el ejemplo de una habitación de hotel. Este sería el caso de una habitación de hotel para dos personas, donde tengo hospedada solo una persona. Tengo un lugar libre aún. Si hablamos de un hotel, entiendo que no podría ocuparla. Pero quizá hablamos de un hostel jaja.

**Comment by jbmild** [comment]
No hablamos de un hostel. Cada bloque lo puede ocupar un solo archivo. Cuando el archivo pida un bloque, y se encuentre el segundo del bitmap. Ese bloque pasa a estar ocupado por mas que el archivo use un solo bit del mismo.

**Comment by gvillarc91** [comment]
Buenisimo! Gracias.
