### ISSUE TITLE
Problemas con la VM 

### ISSUE THREAD

**Issue by aocoda** [sisoputnfrba/foro#700]
Me surgió un problema con la VM de la nada, ya probé rearmando la imagen del disco pero tampoco anda, este es el error que me tira:

Failed to open a session for the virtual machine Lubuntu.

Could not open the medium '/Users/agustin/Downloads/Lubuntu 4.0.1-disk1.vdi'.

VD: error VERR_FILE_NOT_FOUND opening image file '/Users/agustin/Downloads/Lubuntu 4.0.1-disk1.vdi' (VERR_FILE_NOT_FOUND).

Result Code: NS_ERROR_FAILURE (0x80004005)
Component: MediumWrap
Interface: IMedium {4afe423b-43e0-e9d0-82e8-ceb307940dda}

Hace un par de días andaba bien y hoy cuando me quise poner a trabajar me encuentro con eso.

Alguna sugerencia para fixearlo?
Saludos

**Comment by aocoda** [comment]
Solucionado, borré la maquina sin borrar los datos y cree una nueva utilizando el .vdi

**Comment by Franpanozzo** [comment]
Buenas, me estaria pasando lo mismo y no lo puedo solucionar, como hiciste exactamente?? Porque a la hora de crear una nueva me sigue apareciendo ese problema con el .vdi

**Comment by mesaglio** [comment]
@Franpanozzo podes proporcionar mas info del error (Error escrito, foto del error).

**Comment by Franpanozzo** [comment]
![Fallo VM](https://user-images.githubusercontent.com/62455934/106974918-4e9ffc00-6734-11eb-976f-3448a7704f2a.PNG)

**Comment by mesaglio** [comment]
@Franpanozzo ya que no es el mismo error que el estudiante que creo el issue te pido que crees uno nuevo con un poco mas de informacion. Por ejemplo version de virtual box.

**Comment by Franpanozzo** [comment]
@mesaglio Por lo que lei del mensaje de error que pego y copio el compañero es casi igual al que tengo yo, es un problema con el .vdi

**Comment by mesaglio** [comment]
Buenas @Franpanozzo, por lo que pude interpretar el error que se menciona en este issue al principio es que no encuentra el archivo vdi.
En cambio, en tu error habla sobre headers del archivo .vdi. Por lo que asumo que lo esta encontrando y abriendo, pero por alguna razon algo adentro del archivo esta roto o no le gusta.

**Comment by mgarciaisaia** [comment]
Como dice @mesaglio, OK, sí, _ambos tienen un error con el vdi_, pero son dos errores distintos. El post original menciona que el error es `VERR_FILE_NOT_FOUND` (es decir, no encuentra el archivo), el tuyo dice `VERR_VD_VDI_INVALID_HEADER`. En ambos casos _no anda_, pero es por causas diferentes.

¿Buscaste algo sobre ese error a ver qué puede ser?

También sirve que nos cuentes si alguna vez pudiste abrir la VM o si estás intentando arrancarla por primera vez.

Siendo que tuviste problemas con las descargas antes, sugeriría que valides el MD5 de los archivos, tanto los descargados como el descomprimido, a ver si están OK. Si estás intentando prender la VM por primera vez (es decir, no arrancó nunca aún), el MD5 del vdi descomprimido debería darte igual al que está publicado en la página de descarga (puede que lo veas en mayúsculas o en minúsculas, pero los caracteres deberían ser los mismos).
