### ISSUE TITLE
Tamaño maximo reservable en HEAP

### ISSUE THREAD

**Issue by jbmild** [sisoputnfrba/foro#701]
Porque tenemos que poner al final de cada pagina de nuevo la estructura de HeapMetadata? No estamos desperdiciando espacio? Aparte, no podemos usar esto como corte de control para indicarnos que llegamos al final de dicha pagina ya que de hacerlo puede sucedernos la misma situacion debido al uso normal del heap

**Comment by nicozar95** [comment]
Al principio de cada pagina tenes que poner el HeapMetadata y viene a simular la gestion de Memoria de un sistema real.
En los SO reales se tiene un grado de metadata mas [complicado](http://www.blackhat.com/presentations/bh-usa-07/Ferguson/Whitepaper/bh-usa-07-ferguson-WP.pdf) para el manejo de distintos segmentos del FS.

¿Porque no podes usar la metadata como corte de control? Si dentro de las paginas del heap tengo la metadata que me indica cuantos bytes tengo libres y cuantos usados

**Comment by jbmild** [comment]
El problema con usar eso como corte de control es que supone que tenés una página totalmente ocupada. Se te liberan 70 bytes. Después viene y necesita reservar 62 bytes. Los 8 que te sobran, pones La estructura del metadata que pesa 8 bytes. Y ese último bloque te queda libre pero de 0 bytes. Eso te puede pasar en cualquier lugar de La página de heap por lo que no podríamos usarlo como corte ya que mismo dentro de esa página tendremos en este caso 2 heapmetada libres con size 0...

**Comment by nicozar95** [comment]
La existecia de la metadata es para simular lo que pasa en los sistemas operativos, que hay una parte de la memoria que esta siendo utilizada para el manejo del heap. 
Siempre se va a tener que sacrificar un espacio de memoria/disco para el manejo de procesos en memoria (en el caso del TP con el tema del Heap y en el caso de los SO reales, de alguna manera el SO debe ser capaz de administrar los distintos segmentos del proceso) o de [archivos](https://www.youtube.com/watch?v=kiTTAbeqQKY)

Si te llega a pasar eso, entonces el Kernel deberia solicitar una pagina mas para el heap, eso es Fragmentacion Interna y no hay nada que puedas hacer para solucionarlo en este TP...¯\_(ツ)_/¯

**Comment by jbmild** [comment]
Bueno, lo planteo de esa forma entonces, Gracias
