### ISSUE TITLE
sizeof(HeapMetadata)

### ISSUE THREAD

**Issue by jbmild** [sisoputnfrba/foro#702]
En el enunciado toma que esta estructura tiene un tamaño de 5, cosa que tiene sentido por los 4 del int y 1 del bool pero por algun motivo cuando creo la estructura pesa 8. Probe de crear la estructura de diferentes formas pero siempre pesa 8. Porque es esto?

Mi codigo de la estructura
```
typedef struct{
	u_int32_t size;
	bool isFree;
}t_heapmetadata;
typedef struct{
	u_int32_t size;
	bool isFree;
}t_heapmetadata;
```

**Comment by jazcarate** [comment]
Muy fugazmente lo explicamos en la charla de serialización; pero en pocas palabras:
> `gcc` intenta alinear todas sus estructuras en `palabras`

Si te interesa *mucho* que no lo haga, podes agregarle a tu estructura un `__attribute__((__packed__))`, por lo que te quedaría algo como:
```
typedef struct{
	u_int32_t size;
	bool isFree;
} __attribute__((__packed__)) t_heapmetadata;;
```
_(más al respecto; podes buscar y encontrar cosas como [este](http://www.necessaryandsufficient.net/2014/06/struct-padding-in-gcc/) post)_

Pero la mejor pregunta sería: ¿Por qué te interesa tanto? Usá `sizeof` y sé feliz!

**Comment by jbmild** [comment]
ahh listo, no me importa ni un poco. Ya estoy usando el size off. Gracias!
