### ISSUE TITLE
Sintaxis del lenguaje ANSISOP

### ISSUE THREAD

**Issue by jbmild** [sisoputnfrba/foro#703]
Estoy intentando probar las funciones de alocar y liberar. Para eso cree el siguiente programa ansisop
```
begin
	variables a, b
	alocar a 50
	alocar b 61
	liberar a
	liberar b
end
```
la cuestion es que al llamar al alocar, me devuelve el puntero y despues el parser llama a la funcion asignar y le asigna en el stack de la variable a el valor del puntero que yo le devolvi de alocar.
y despues al liberar me manda la posicion del stack de la variable en lugar de la posicion devuelta por alocar.
Me parece que es un error que estoy teniendo mas con la sintaxis que con otra cosa
Ayuda :D

**Comment by jazcarate** [comment]
Toda la razón del multiverso!
[Incluso creamos mal el test!](https://github.com/sisoputnfrba/ansisop-parser/blob/master/parser-tests/analizadorLineaTest.c#L72-L73)
```c
analizadorLinea("liberar x", funciones, kernel);
t_puntero posicionX = assertObtenerPosicion('x');
assertLiberar(posicionX);
```

Mala mía! En algún momento de hoy o mañana actualizo el parser; la idea es lo que dice la documentación:
```
		/*
		 * LIBERAR MEMORIA
		 *
		 * Informa al kernel que libera la memoria previamente reservada con RESERVAR.
		 * Solo se podra liberar memoria previamente asignada con RESERVAR.
		 *
		 * @sintax	TEXT_FREE (liberar)
		 * @param	puntero Inicio de espacio de memoria a liberar (previamente retornado por RESERVAR)
		 * @return	void
		 */
		void (*AnSISOP_liberar)(t_puntero puntero);
```
debería ser el *valor* de `x`, no la *posición* de `x`.

**Comment by jbmild** [comment]
Bien, gracias quedo a la espera de la actualización del parser. Cierro el issue. Saludos

**Comment by jazcarate** [comment]
Ahí subí el PR. En algún momento lo revisará alguien y lo mergeará; o me criticará mi solución :sweat_smile:

**Comment by jazcarate** [comment]
_No se si a alguien le interesa.... pero quedó `merge`ado el fix este 😄 _

**Comment by jbmild** [comment]
Genial! Muchas gracias. Mañana lo miro :).
