### ISSUE TITLE
Filesystem, directorio /mnt

### ISSUE THREAD

**Issue by CarolinaPonceRodriguez** [sisoputnfrba/foro#704]
Buenas que tal, para el fs se indica como directorio raiz /mnt /FS_SADICA... la cuestion del mismo es que para crear carpetas y/o archivos dentro de mnt no cuento con permisos. Unicamente puedo hacerlo usando sudo. La pregunta es como hago para generar archivos mediante codigo si no cuento con los permisos adecuados? Por ejemplo, si me solicitan abrir un archivo y no lo tengo, si me pasan por parametro "c" entonces genero el archivo en el directorio indicado. Cuando trato de hacer esto con la funcion open(), no puedo, pero si le paso otro directorio cualquiera si, entiendo que es por eso.
Existe algun parametro para open para poder generarlo forzosamente? o deberia aplicarle un chown a ese directorio? 

Gracias

**Comment by nicozar95** [comment]
El directorio /mnt es a modo de ejemplo. En los SO ese es el directorio de montura de los distintos fs por eso lo elegimos como ejemplo, no es obligatorio que se encuentre el punto de montaje del FS ahi.

De cualquier manera, si vos queres escribir/abrir archivos de algo que no te deja por los permisos, podes correr tu programa como super usuario (sudo) o Administrados y te va a dejar.

**Comment by CarolinaPonceRodriguez** [comment]
Perfecto, muchas gracias por la info!
