### ISSUE TITLE
Asignacion de paginas - Tamaño maximo de Alloc

### ISSUE THREAD

**Issue by juanignaciog** [sisoputnfrba/foro#705]
Buenas, leyendo la parte de gestión de heap, hay cosas que no entiendo.
Dice: 

>*Tamaño máximo de Alloc*
Un dato que se desprende de nuestro análisis recae en la cantidad máxima de datos que podemos pedir. Como no contamos con un esquema de segmentación, no podemos asegurar que las páginas
que nos otorga la memoria se encuentren en posiciones contiguas. Por ende, tan solo podremos
pedir memoria de un tamaño que se encuentre comprendido dentro de una página.
**Como necesitamos, además de los datos, guardar la metadata de los bloques pedidos, el tamaño
máximo reservable por petición será de:**
**Tmax = PAGE_SIZE - 10 Bytes**

Lo que yo entiendo (y creo que le estoy pifiando, pero no se me ocurre otra cosa) es que no se va a poder reservar mas de 1 pagina por pedido, pero entonces no entiendo como le podría llegar una solicitud de varias paginas a memoria desde el kernel como ponen de ejemplo en #652.
Ademas de que tampoco entiendo por qué la función Asignar Paginas a Proceso tomaría por parámetro la cantidad de paginas si siempre va a tener como máximo 1 pagina.

Saludos

**Comment by nicozar95** [comment]
En un script ansisop lo que te va a pedir es alocar una cierta cantidad de bytes frente al llamado a la funcion del parser `t_puntero (*AnSISOP_reservar)(t_valor_variable espacio);` si la cantidad de bytes que te pido reservar es mayor a la capacidad de la pagina, al programa no le interesa, entonces el Kernel va a tener que pedir mas de una pagina a Memoria y fijate que en la interfaz que tiene la Memoria permite asignar mas de una pagina.

**Comment by juanignaciog** [comment]
A esta bien. Entonces qué quiere decir esa parte del enunciado que copié arriba? Me confunde lo del Tamaño máximo reservable por peticion.

**Comment by picollomartin** [comment]
De metido nada mas 
> si la cantidad de bytes que te pido reservar es mayor a la capacidad de la pagina

No es que si un pedido es mayor que el tamaño de una pagina (menos 10 bytes), se termina ese programa (porque solo se puede pedir de tamaños que estén comprendidos dentro de una página)?

**Comment by juanignaciog** [comment]
@picollomartin Eso es lo que entiendo yo cuando leo esa parte del enunciado y por eso la idea de que siempre el pedido de asignacion de pagina que hace Kernel a Memoria va a ser 1 como maximo (por cada peticion) pero la verdad es que tiene mas sentido lo que dice @nicozar95 (por lo que dije arriba de la funcion Asignar paginas a proceso). Por eso pienso que hay algo que estoy entendiendo mal.

**Comment by nicozar95** [comment]
@picollomartin 
Tenes razon. En el enunciado solo puedo hacer, por peticion, una reserva maxima de: 
**TamañoDePagina - 10** 
Entonces me corrigo, si bien podes tener una cantidad teoricamente infinita de frames de heap por procesos, el maximo de bytes que podes hacer por pedido es **TamañoDePagina - 10**

**Comment by picollomartin** [comment]
@juanignaciog ojo para mí igual puede haber pedidos de más de una página, el stack por ejemplo puede ocupar más de una y ahí le pedís N páginas a memoria

**Comment by nicozar95** [comment]
La interfaz de asignacion de paginas de la memoria permite asignar mas de una pagina para casos como cuando tenes que pedir X paginas para almacenar el codigo/stack.

Con el heap es mas complicado porque la asignacion no tiene un limite, entonces si dejo que reserven la cantidad de bytes que quiera, podria reservar 999999999999999 bytes ocupando todos mis frames por ejemplo y en cada frame escribir la metadata... Tambien ocurre si quiero escribir/leer un espacio de heap mas grande de mi pagina, entonces serian pedidos de lectura de distintas paginas, en el caso de escribir deberia actualizar cada parte de la metadata aunque esten en paginas distintas, etc, etc .... Y es un dolor de cabeza

Es mas facil para ustedes que el maximo que puedo hacer**por pedido** sea: **TamañoDePagina - 10**.

**Comment by juanignaciog** [comment]
Listo, ahi con lo ultimo me quedo todo claro. Muchas gracias

**Comment by santiagovarela86** [comment]
Con respecto a esto... sizeof(heapMetadata) = 8 (según leí es para que la estructura esté alineada).

Por lo tanto no debería ser Tmax = TamañoDePagina - 2 * sizeof(heapMetadata)?

**Comment by juanignaciog** [comment]
Si, en realidad el tamaño Max va a ser ese que decis
