### ISSUE TITLE
Salto condicional - enunciado

### ISSUE THREAD

**Issue by Emi0689** [sisoputnfrba/foro#706]
Buenas, quisiera hacer una consulta. El enunciado dice:

Salto condicional
"Estas instrucciones, por definición del enunciado, tendrán como origen y destino el procedimiento
actual. En otras palabras, el código de una función o procedimiento no podrá saltar dentro del
código de otro."

Pero en los ejemplo de pruebas, encuentro el que dice "stackoverflow.ansisop" el cual lo hace:
```

#!/usr/bin/ansisop
begin
	f
end

function f
	variables a
	a=1
	print a
	g
end

function g
	variables a
	a=0
	print a
	f
end

```

Es un ejemplo viejo? 

muchas gracias!!

**Comment by Emi0689** [comment]
Añado consulta, puede haber mas de dos CONTEXTOS en el stack AL MISMO tiempo? o sea entradas por contexto muchas, y puede terminar una funcion y entrar otra, generando otro contexto de ejecución. Pero puede haber mas de dos? (el general begin/end y el de la funcion?)

**Comment by nicozar95** [comment]
Sobre el salto condicional: En el codigo que subiste no figura el salto condicional. El mismo seria una linea de tipo jz/jnz por ejemplo: ` jnz algo etiqueta ` osea que si se fija si `algo` es distinto de 0, si es distinto de 0 va a donde dice `:etiqueta` en tu codigo.
Una cosa en ansisop es una funcion y otra es una etiqueta, cuando entras en una etiqueta no cambias el contexto del stack cuando entras en una funcion si. Fijate en el ejemplo que esta en el enunciado de salto condicional y el salto a la linea de etiqueta es en el mismo procedimiento.

> puede haber mas de dos CONTEXTOS en el stack AL MISMO tiempo? o sea entradas por contexto muchas, y puede terminar una funcion y entrar otra, generando otro contexto de ejecución. Pero puede haber mas de dos? (el general begin/end y el de la funcion?)

No se si entiendo esta pregunta, siempre el Stack esta en un contexto, y se maneja igual que una pila, si entra en una funcion, agrego un contexto y aumento en uno el SP. Si sale de una funcion, saco un contexto y bajo en uno el SP. Pero (por ahora) la ejecuccion de los scripts ansisop es secuencial, osea, se van a ejecutar sentencia por sentencia, una por una, entonces no hay manera de que un programa ansisop este en 2 contextos de ejecucion al mismo tiempo

**Comment by Emi0689** [comment]
En cuanto a la primer pregunta barbaro!! pensé que las funciones eran salto condicional tambien. Perfecto! Clarisimo.

En cuanto a lo segundo, entendiste barbaro! (perdon desde ya si me exprese mal, escribí en el colectivo XD). Ahora sobre esta ultima te vuelvo a consultar, primero por que el por ahora? te referis a por el checkpoint? y consulto, si en una funcion, entro a otra tendria en mi stack 3 contextos? 

Para aclarar esto: lo consulto dado que al entrar a una llamadaConRetorno tengo que guardar por un lado las variables, parámetros (aunque se que son numéricos), el puntero de instrucción y valor de retorno, todos dentro del mismo contexto del stack, pero no tiene que estar en un contexto igual que el original. Entonces como los diferencio? y pensé una forma sería con un ID de contexto (osea el SP). Es correcto esto?

Muchas gracias por tu tiempo y pronta respuesta!!

**Comment by nicozar95** [comment]
> Ahora sobre esta ultima te vuelvo a consultar, primero por que el por ahora? te referis a por el checkpoint?

Es a modo de comentario no tiene nada que ver con el TP, anda a saber como va a ser el parser de aca a unos años, lo mas probable es @jazcarate dando charlas a nivel mundial de ansisop.

> si en una funcion, entro a otra tendria en mi stack 3 contextos?

Depende de donde esta el stack, a lo que vos te referis debe ser algo por el estilo:
En el proceso principal ansisop (Stack Pointer o SP = 0) entro en una funcion, entonces ahora mi SP = 1, despues dentro de la misma funcion entro a otra funcion, ahora mi SP = 2 y asi sucesivamente.

>  lo consulto dado que al entrar a una llamadaConRetorno tengo que guardar por un lado las variables, parámetros (aunque se que son numéricos), el puntero de instrucción y valor de retorno, todos dentro del mismo contexto del stack, pero no tiene que estar en un contexto igual que el original. Entonces como los diferencio? y pensé una forma sería con un ID de contexto (osea el SP). Es correcto esto?

Fijate en el ejemplo del enunciado que cuando llama a `g <- double a` agrega una fila mas a la tabla del indice del stack, guardando ahi la pocision de retorno y todo lo necesario para que una vez terminado de ejecutar la funcion `double` pueda almacenarlo en la variable `g`. 
El stack es una pila, cada vez que vas a ingresar en un nuevo contexto agregas un nuevo elemento a esta pila con una pocision en el stack (SP), los argumentos con los que llamo al contexto, la variables que declara en el contexto, la pocision de retorno a la instruccion del contexto anterior y el valor de retorno. 
En el issue #659 hice un dibujo de como se manejaría masomenos el stack en memoria para que se den una idea de los contextos de ejecucion

**Comment by Emi0689** [comment]
Perfecto!!! super claro!! muchas gracias!!!!
