### ISSUE TITLE
Interpretacion del parser

### ISSUE THREAD

**Issue by NicoLuis** [sisoputnfrba/foro#707]
Buenas, estuve probando sin problemas varios scripts hasta que llegue a un problema con este caso especifico

```
begin
	variables a
	a = 20
	prints n a
end
```

La funcion metadata_desde_literal me indica q la cantidad de instrucciones es 3 y que la ultima es

```
prints n a
end
```

Por lo q no me toma el end como una instruccion, ahora si agrego un salto de linea antes del end si lo toma como una instruccion mas

**Comment by tferraro** [comment]
Holis,

De casualidad, el script esta hecho en windows originalmente?

**Comment by NicoLuis** [comment]
Lo copie directo del pdf del enunciado desde windows (y luego lo simplifique)
Ahora cree un nuevo archivo, escribi lo mismo a mano desde la vm y no tuve problema, mientras el anterior sigue fallando
No entiendo porque :P

**Comment by jazcarate** [comment]
Ah! El famosisimo problema del "salto de linea".
El parser [separa lineas *solo* por `\n`](https://github.com/sisoputnfrba/ansisop-parser/blob/master/parser/parser/metadata_program.c#L83), y al copiar desde Windows _(que separa lineas de maneras erraticas, extrañas y d̴̪͔̫͙͎͔e͡l̤͘ ̛̬̳̺̯m̘̗a̞͍̠͎̝ͅl̲̜̪̙̯)_ para el parser es solo una linea; aunque vos lo veas como dos.

Para más información; Wikipedia:
> Los sistemas basados en ASCII o en una codificación de caracteres compatible usan LF (salto de línea), CR (retorno de carro), o CRLF (CR seguido de LF):
> [--Wikipedia: Nueva línea](https://es.wikipedia.org/wiki/Nueva_l%C3%ADnea)

Podríamos cambiar la implementación; pero dado que solemos trabajar en ambientes de Linux.... 🤔 para pensar.

**Comment by NicoLuis** [comment]
Ah joya lo voy a tener en cuenta gracias!
