### ISSUE TITLE
Dudas varias paginas memoria

### ISSUE THREAD

**Issue by maurocostabella** [sisoputnfrba/foro#708]
Buenas tardes, hace bastante vengo arrastrando algunas dudas sobre el proceso memoria, sobre sus páginas precisamente.

1) Cuando le asigno paginas de heap al proceso? 
Por lo que vengo leyendo, lo hago en casos de mallocs, pero... ansisop sabe hacer eso? Hay algun instruccion en dicho lenguaje que reserve espacios de memoria? Como/cuando hago mallocs en ansisop?

2)Como se cuantas paginas de memoria le voy a asignar a los estrucuturas administrativas? Hay algun calculo? lo paso por archivo de configuracion? Elijo yo cuantas quiera?

3)Cuales son todas las estrucutras administratvivas que debo guardas en las paginas asignadas a administracion?
Tengo un par en mente, como los PCB, los indices de Codigo, Stack... pero no se cuantas mas... el bit map del FS, la tabla de paginacion invertida... Estoy en lo correcto con las que mencione? Hay muchas mas?

Gracias!

**Comment by nicozar95** [comment]
> Cuando le asigno paginas de heap al proceso?
> Por lo que vengo leyendo, lo hago en casos de mallocs, pero... ansisop sabe hacer eso? Hay algun instruccion en dicho lenguaje que reserve espacios de memoria? Como/cuando hago mallocs en ansisop?

Existe la instruccion [alocar](https://github.com/sisoputnfrba/ansisop-parser/blob/master/parser-tests/analizadorLineaTest.c#L63) en ansisop que te va a disparar una primitiva a `t_puntero (*AnSISOP_reservar)(t_valor_variable espacio);`

> 

> Como se cuantas paginas de memoria le voy a asignar a los estrucuturas administrativas? Hay algun calculo? lo paso por archivo de configuracion? Elijo yo cuantas quiera?

Depende. La estructura administrativa es la tabla de paginas, cada fila de esta tabla de paginas tiene un numero de frame, un numero de PID y un numero de pagina, por cada uno de los frames que tengas.

Depende de la cantidad de frames de la memoria la cantidad de paginas que debas pedir para almacenar esta tabla, entonces los bytes que va a pesar esta tabla se pueden calcular con algo como `(sizeof(nroFrame) + sizeof(nroDePID) + sizeof(nroDePagina)) * cant_frames`

> Cuales son todas las estrucutras administratvivas que debo guardas en las paginas asignadas a administracion?
> Tengo un par en mente, como los PCB, los indices de Codigo, Stack... pero no se cuantas mas... el bit map del FS, la tabla de paginacion invertida... Estoy en lo correcto con las que mencione? Hay muchas mas?

No. En Memoria se va a almacenar, en sus frames,:

- la tabla de paginas

- el codigo de los procesos ansisop

- el stack de los procesos ansisop

- el heap de los procesos ansisop (si llegara a pedir memoria dinamica el proceso)

**Comment by maurocostabella** [comment]
Muchas gracias, me aclaraste bastante.
Lo unico que no me queda claro es cuales son las estrcturas administrativas (se que la memoria se adminsitra mediante una tabla de pags) porque en la pag 24 del enunciado, donde dice "diagrama de paginas de la memoria" nos dice que los primeros N bloques (supongo yo que son los primeros N frames) van a reservarse para las estructuras administativas -> cuales son todas estas "estructuras administativas" que se guardan en los primeros N bloques? Como se cuantos N bloques debo reservar?

**Comment by nicozar95** [comment]
Lo que vas a almacenar en los primeros N frames es la tabla de página.

No hay otra estructura administrativa que almacenes en Memoria. ¿Cual otra  tenés pensado almacenar?

**Comment by maurocostabella** [comment]
No se, me parecia raro almacenar tantos frames, pero siendo asi, no quedan mas dudas. gracias!
