### ISSUE TITLE
Alojamiento Indice de Codigo

### ISSUE THREAD

**Issue by maurocostabella** [sisoputnfrba/foro#709]
Una vez que creo el indice de código, donde lo almaceno? Porque tengo entendido que en la memoria solo va el codigo, y el stack, y la unica estructura administrativa que tengo en memoria es su tabla de paginas.
Por otro lado, si los indices tienen que ser parte del pcb (porque yo habia pensado que el indice de codigo sea un puntero a la tabla) me generaría PCB´s de distinto tamaño... Entonces no se cual es la mejor decision... 1)La guardo en el proceso Kernel 2)Hago PCB´s de distintos tamaños 3) le busco algun lugar en memoria...

gracias.

**Comment by varas-c** [comment]
Hola,

En la memoria solo vas a guardar codigo, stack, heap y la tabla de páginas
nada mas. No debes guardar ningun otra estructura.

El indice de código forma parte del pcb. No hay ningún problema con que te
queden pcb's de tamaño variable.

Si no te convence, pensá quien necesita el indice de código para ejecutar
las instrucciones.

Saludos!

**Comment by maurocostabella** [comment]
gracias!

**Comment by LeonelCurti** [comment]
Pregunta referida tambien al indice de codigo, este se llena dentro del kernel para cargar el pcb y luego enviar el codigo a la memoria ? O, si no es asi en que momento llenamos el indice de codigo?.

**Comment by nicozar95** [comment]
El indice de codigo se llena con los datos que te devuelve el `t_metadata_program`. Esto lo deberia hacer el Kernel cuando recibe un script de un proceso ansisop. El Kernel mete esta estructura, junto con los demas cuando crea el PCB de este proceso ansisop.

Vos mira en el enunciado como trata el indice de codigo y fijate que no depende para nada de Memoria, osea que no marco en que pagina y offset esta mi linea de codigo sino marco en que byte empieza y cuantos bytes pesan cada instruccion.

Osea, primero pasa por el `t_metadata_program` y despues pasa por Memoria. ¿Podrian hacerlo al reves? En un principio si, pero no tiene sentido, para ello el Kernel deberia pasarle el codigo a Memoria y este despues devolverselo al Kernel para que cree el PCB... suena raro que se tiren el codigo de un lado para el otro.

**Comment by LeonelCurti** [comment]
Entendido, hago una  consultas mas, cuando parseamos el codigo de un programa para llenar el indice de codigo y por ejemplo tenemos funciones arriba del begin es necesario respetar el orden de ejecucion de las instrucciones o eso lo vamos a hacer en la CPU cuando ejecutemos las primitivas y se produzca un salto a la funcion?

**Comment by tferraro** [comment]
Holis, a que te referís con:
> (...) tenemos funciones arriba del begin es necesario respetar el orden de ejecucion de las instrucciones (...)

Las CPUs no conocen el concepto del orden del código en el estricto sentido de la palabra. Para ellas simplemente el orden se representa al revisar cual es la siguiente instrucción a buscar según el PC. Si algo alterara el PC y produca saltos en el orden en el que las cosas están en memoria para la CPU es indistinto.

**Comment by LeonelCurti** [comment]
Ya tengo el indice de codigo mas o menos interpretado, ahora, para que funcione metadata_buscar_etiqueta ademas del campo etiquetas de t_metadata_program tengo que guardarme el etiquetas_size en el pcb. Esto es asi?, por que sino no encuentro forma de sacar el tamaño de serializacion de las etiquetas.

**Comment by jazcarate** [comment]
@LeonelCurti Por qué no creas un issue especifico? así podemos cerrar este y queda todo más ordenadito? 😄 
_(de paso si abrís un issue nuevo, te contesto 😉 )_

**Comment by LeonelCurti** [comment]
Dale, se puede cerrar este.

**Comment by jazcarate** [comment]
_Lo podés cerrar vos :smile: _
