### ISSUE TITLE
PCB - Tamaño variable

### ISSUE THREAD

**Issue by maurocostabella** [sisoputnfrba/foro#711]
Buenas, como hago para saber el tamaño de los campos de tamaño variable del pcb? como algun char* o los indices? puedo tener un campo adicional con el tamaño de los campos variables? (no esta contemplado en la definicion del pcb en el tp)

**Comment by nicozar95** [comment]
Las commons brindan un monton de funciones zarpadas para hacer estos calculos (por eso fue que se inventaron para que NO se la pasen recorriendo char's y sacando tamaños de strings, no nos interesa eso para eso esta Algoritmos...). Te tiro un par muy copadas:
Para conocer longitud de strings
```
	/**
	* @NAME: string_length
	* @DESC: Retorna la longitud del string
	*/
	int 	string_length(char * text);
```

Y para conocer longitud de una lista:

```
	/**
	* @NAME: list_size
	* @DESC: Retorna el tamaño de la lista
	*/
	int list_size(t_list *);
```

Son libres de programar en C como quieran, pero es mas sencillo para ustedes que no reinventen la rueda que usen las estructuras de colecciones de las commons asi se ahorran tiempo.

**Comment by maurocostabella** [comment]
gracias, pero ponele... el indice de codigo, que es un vector de tamaño variable. yo puedo calcular su tamaño sabiendo la cantidad de instrucciones, pero eso es informacion que me da la metadata, no se encuentra en el pcb... como hago para saber su tamaño?

**Comment by nicozar95** [comment]
> el indice de codigo, que es un vector de tamaño variable. yo puedo calcular su tamaño sabiendo la cantidad de instrucciones, pero eso es informacion que me da la metadata, no se encuentra en el pcb

El indice de codigo no es de tamaño variable, si bien es distinto entre procesos y procesos ansisop, nunca va a cambiar su tamaño en ejecucion.

Con la metadata creas el PCB no al reves, fíjate que el metadata recibe todo el codigo ansisop como un char*
En el indice de codigo yo se que cada fila me va a pesar 8bytes (4bytes para marcar desde donde empieza y 4bytes para marcar cuanto mide cada instruccion) también conozco cuantas filas de instruccion voy a tener, gracias al metadata. 

Igual esto te sirve para serializar el indice de codigo y mandarlo por socket pero **no** lo tenes que volcar en ningun malloc grande.

**Comment by maurocostabella** [comment]
Tengo en claro que con la metadata se hace el pcb. Pudimos generar todo el pcb sin problemas, pero justamente tenemos los problemas para serializarlo y enviarlo... vuelvo a la pregunta, se que cada fila pesa 8, pero sin la informacion de metadata no se cuantas instrucciones hay, por ende tampoco se cuanto mide el total de la tabla... la pregunta concreta es, **con la informacion que tiene el pcb, como hago para saber su tamaño y seralizarlo**... en la diapositiva de serializacion, slide 28, ustedes guardan una variable del largo del char* por ejemplo...
Al momento de crear el pcb, yo tengo la info metadata, pero si lo quiero enviar depsues de crearlo, cuando ya me deshice de la info de metadata?

**Comment by nicozar95** [comment]
Siempre todos los mensajes dinamicos que envien por socket tienen un header adelante, en este header vuelco (ademas del handshake que tengan establecido) cuanto pesa mi estructura para poder sacarle el tamaño. Y este peso lo levanto como un int.

Por ejemplo, si yo envio mi nombre por socket lo que veria en forma "cruda" dentro del paquete seria algo como: `16nicolas zarewsky`, entonces cuando lo recibo primero levanto los primeros 4bytes que me dicen cuanto pesa y despues levanto el resto de mi nombre ya conociendo el tamaño.

**Comment by maurocostabella** [comment]
Sigo sin entender. Nuestra estructura pcb tiene un int pid, un int exit code, etc. El INDICE DE CODIGO no puede ser de tamaño fijo (para cada proceso varia, es constante durante la ejecucion, pero no es el mismo para todos) por ende, nosotros pusimos que es un puntero a un int (o mejor dicho a un struct de dos ints, desplazamiento, longitud)... yo puedo saber el tamaño de la tabla haciendo 2*int*cant_instrucciones, pero este ultimo operando es algo que sabe metadata... como hago para saber cuando pesa el indice? o sino como hago para que un campo del pcb sea una tabla (y no un puntero a ella) sin saber cuan grande va a ser...

**Comment by maurocostabella** [comment]
Osea la pregunta es anterior al envio... tengo que saber el tamaño de un malloc para serializar. yo tengo pcb1 pcb2, ambos con distintos tamaño de tabla de codigo, como hace para con la info de su pcb, saber cuanto pesa cada tabla? trate de hacer que un campo del struct sea por ejemplo int[size_instrucciones][2] pero me tiraba un error diciendo que size_instruccione podria varias en tiempos de ejecucion, entonces ahi decidi usar un puntero... el tema es que cuando quiera saber el tamaño de esa tabla a la que apunta, no tengo forma sin saber la cantidad de instruciones...

**Comment by jazcarate** [comment]
El tamaño del indice del código lo tenes. Si recordamos la estructura `t_metadata_program` que nos brinda el parser:
```
		t_puntero_instruccion	instruccion_inicio;	//El numero de la primera instruccion (Begin)
		t_size			instrucciones_size;		// Cantidad de instrucciones
```
[-- La documentación del parser](https://github.com/sisoputnfrba/ansisop-parser/blob/master/parser/parser/metadata_program.h#L36-L37)

Sería `metadata.instrucciones_size * sizeof( t_puntero_instruccion )`. 😃

**Comment by maurocostabella** [comment]
Si el tema es que no tengo esa informacion metadata una vez que el pcb esta creado. Ya lo pude solucionar con la ayuda de Nico, estoy probando... ni bien me quede bien comento aca y cierro el issue.

**Comment by maurocostabella** [comment]
Lo solucione usando listas y leyendo bastante sobre serializacion! gracias!
