### ISSUE TITLE
Funcion irAlLabel del parser. Que deberia hacer?

### ISSUE THREAD

**Issue by nicopriano** [sisoputnfrba/foro#712]
Buenas, estoy viendo el desarrollo de las primitivas, pero no entiendo bien que deberia hacer irAlLabel.

**Comment by jazcarate** [comment]
```
/*
 * IR a la ETIQUETA
 *
 * Cambia la linea de ejecucion a la correspondiente de la etiqueta buscada.
 *
 * @sintax	TEXT_GOTO (goto)
 * @param	t_nombre_etiqueta	Nombre de la etiqueta
 * @return	void
 */
void (*AnSISOP_irAlLabel)(t_nombre_etiqueta t_nombre_etiqueta);
```
[-- Documentación](https://github.com/sisoputnfrba/ansisop-parser/blob/master/parser/parser/parser.h#L142-L151)

Si estas ejecutando la linea 5; cuandoejecutes esta primitiva; vas a ejecutar la linea donde esté la etiqueta `t_nombre_etiqueta` (que mitandolo; fué un refactor que salió mal; el nombre del parametro debería ser algo como `nombre_etiqueta` :p ).

Ayuda en algo? O cual era la consulta más especifica?

**Comment by nicopriano** [comment]
Sisi me ayudo.Gracias!
