### ISSUE TITLE
Comparar tiempos (Cache - LRU)

### ISSUE THREAD

**Issue by dromero-7854** [sisoputnfrba/foro#713]
Mi pregunta es bien sencilla, y creo que la estoy haciendo de inseguro que soy nada mas.

¿Se podría utilizar la funcion definida en la commons library para comparar tiempos?
> char  * temporal_get_string_time()

Es decir, comparar horarios a partir de strings que representan horas.

Algo asi...

 ```
char * tiempo_A =  temporal_get_string_time();
char * tiempo_B =  temporal_get_string_time();

if (tiempo_A < tiempo_B) {
  // En este ejemplo siempre entra al if
}
```

**Comment by nicozar95** [comment]
Si, las commons estan para usarse :smile:

**Comment by dromero-7854** [comment]
Solo queria comfirmar que esa manera de comparar estaba bien planteada... Cierre y saludos!

**Comment by jazcarate** [comment]
*Ojo*!

Qué estás tratando de comparar con `if (tiempo_A < tiempo_B)`? Porque creo que no va a hacer lo que vos queres que haga :smile_cat:

**Comment by dromero-7854** [comment]
¿Y ahora me lo decis? jeje Quiero saber de dos horarios cual es el menor... 

Es decir, en mis estructuras de control de la cache guardo ultimo horario de utilización de una pagina en cache en formato string utilizando la libreria. Luego quiera saber si comparandolos como el ejemplo que puse (muy burdo) puedo saber cual es el menor para aplicar el algoritmo LRU.

**Comment by jazcarate** [comment]
Qué te devuelve `temporal_get_string_time();`?

**Comment by dromero-7854** [comment]
Segun la documentacion:

`Retorna un string con la hora actual, con el siguiente formato: hh:mm:ss:mmmm`

**Comment by dromero-7854** [comment]
mmm  ya se meti la pata estoy comparando puntero no?

**Comment by dromero-7854** [comment]
¿tengo que usar `strcmp()` no? Mala mia por apurado jejej

**Comment by jazcarate** [comment]
y un `String`, en realidad es un puntero a un `char`, si?

`temporal_get_string_time()` te devuelve una posición de memoria; por lo qué: `if (tiempo_A < tiempo_B)` te va a decir qué String está asignado en una posición de memoria entes que la otra.

Para cosas así, uno podría comparar `Strings` con funciones especificas de `String`: `strcmp`.

ahora, te pregunto.... `"01:00:00"` contra `"10:00:00"`, cual es más grande?

**Comment by dromero-7854** [comment]
Imagino que el valor `"10:00:00"` es mas grande que `"01:00:00"`

**Comment by nicozar95** [comment]
`strcmp` compara ambos string y te dice que si son iguales te devuelve 0. Si son distintos se fija en el valor ASCII del primer caracter distinto que encontro en ambos string.

Entonces si el string es `"10:00:00" `contra `"01:00:00"` compara el valor ASCII de "1" contra "0"

**Comment by dromero-7854** [comment]
estoy viendo los valores en una tabla ASCII:

ASCII    Simbolo
48         0
49         1

¿La respuesta seria correcta no?

**Comment by jazcarate** [comment]
La hermosa gracia de nuestra carrera.... probalo!
```
#include <stdio.h>
#include <string.h>

char* comparacion(char* unaHora, char* otraHora){
	int comparador = strcmp(unaHora, otraHora);

	if( comparador <0 )
		return "mas chica que";
	else if(comparador >0)
		return "mas grande que";
	else
		return "igual a";
}

void comparar(char* unaHora, char* otraHora){
	printf("%s es %s %s\n", unaHora, comparacion(unaHora, otraHora), otraHora);
}

int main (){
	comparar("10:00:00","01:00:00");
	comparar("01:00:00","10:00:00");
	comparar("01:00:00","01:00:00");
	return 0;
}
```

eso devuelve:
> 10:00:00 es mas grande que 01:00:00
> 01:00:00 es mas chica que 10:00:00
> 01:00:00 es igual a 01:00:00

**Comment by nicozar95** [comment]
@dromero-7854 ¿Lo pudiste solucionar?¿Se puede cerrar? :innocent:

**Comment by dromero-7854** [comment]
Si... Disculpa el cuelgue jeje Gracias!!!
