### ISSUE TITLE
Cada vez que se termina un proceso tengo que esperar que el bind libere el fd

### ISSUE THREAD

**Issue by ivodan** [sisoputnfrba/foro#714]
Buenas, me habian contado que andaba flotando por ahi un comando para no tener que esperar un minuto cada vez que termino un proceso (porque el bind tira error:adress alredy in use)

**Comment by nicozar95** [comment]
No se si hay un comando para eso (seguro lo hay) pero podrías usar antes de bindear el socket algo como `setsockopt(...)`

**Comment by alkchofa** [comment]
sudo fuser -k Port_Number/tcp

Saludos

**Comment by ivodan** [comment]
Muchas gracias!
