### ISSUE TITLE
¿Que deberian hacer exactamente las primtivas de cpu wait y signal?

### ISSUE THREAD

**Issue by BrunoManchione** [sisoputnfrba/foro#715]
¿Que deberian hacer exactamente las primtivas de cpu wait y signal? 
Ambas reciben el parametro de tipo t_nombre_semaforo, que deberia hacer kernel una vez los recibe? asumo que ordena que se bloquee el proceso si corresponde, pero si la variable t_nombre_semaforo es el nombre, donde deberian estar los semaforos de los procesos en ejecucion?  (para bloquearlo si corresponde el nombre). ¿de donde los obtuve? 
Gracias

**Comment by LeandroCarbajales** [comment]
Hola Bruno, 
Según el enunciado:
> Los semáforos estarán definidos por archivo de configuración con un identificador alfanumérico y un valor inicial, por ejemplo: SemSocket o SemDisco. Se crearán al iniciar el proceso Kernel con los valores definidos en el archivo de config en SEM_INIT.

En el ejemplo de archivo de configuración del Kernel se muestra cómo se declaran los semáforos con sus valores, luego pueden leerlo y crear una estructura para manejarlos.
Saludos!

**Comment by LeandroCarbajales** [comment]
Se resolvió la duda? Se puede cerrar el issue?
