### ISSUE TITLE
Dump de contenido de memoria 

### ISSUE THREAD

**Issue by loopmeagain** [sisoputnfrba/foro#716]
Buenas!
queria saber si hay alguna forma particular en la que tengamos que mostrar el contenido que esta en  memoria o en cache; nuestro problema es debido a que cuando cargamos una pagina con un contenido, esto lo hacemos a traves de un memcpy con un puntero a void, ahora cuando hacemos el dump y queremos visualizar el contenido, no encontramos ninguna forma de visualizar contenido void.

**Comment by gastonprieto** [comment]
Buenas!

De que tipo es la memoria? que almacena (en forma generica, no en el caso particular de este TP)?

**Comment by loopmeagain** [comment]
Ya cuando querria hacer el dump estaria haciendolo con respecto a los espacios de memoria fisica. 
Para la otra pregunta, bits? supongo

**Comment by nicozar95** [comment]
El `void*` es un puntero a nada, una estructura que ustedes no castiaron su tipo, sin embargo, cuando ustedes escriben en memoria con el memcpy, copien una cantidad de tamaño `n` de bytes, segun el [man](https://linux.die.net/man/3/memcpy).

La interpretacion de como leo estos cachos de `n` bytes depende de como los quiero leer, no de los bytes almacenados ¿Que interpretación le dieron?¿Ustedes que tipo de impresion probaron?

**Comment by loopmeagain** [comment]
Era cuestion de castearlo como queria que se vea antes de hacer el printf , gracias!
