### ISSUE TITLE
STACK - Ejecución incompleta de una CPU (desalojo)

### ISSUE THREAD

**Issue by gvillarc91** [sisoputnfrba/foro#718]
Supongamos el siguiente caso.
Una CPU está procesando un archivo ANSISOP asi:

```
begin
	variables b, g
	b = 1
	g <- funcion_loca b
	print g
end

function funcion_loca 
	variables c
	c=$0 + 1
	c <- funcion_loca c
end
```

Una vez dentro de la llamada a funcion_loca, kernel le dice que se le terminó el quantum y la desaloja.

Previo a ese desalojo, debo enviar el Stack como lo tengo hasta ese momento en el PCB? Es decir, el Kernel debe recuperar la estrcutura PCB con el stack para que la proxima CPU pueda retomar la ejecución desde funcion_loca?

Me surje la duda porque al recibir el PCB del kernel, almacenamos el stack como variable local del CPU y primtivas, entonces, si no lo envío, como sabe el proximo CPU el contexto de lo ultimo que se ejecutó?

Gracias.

**Comment by jazcarate** [comment]
Buenas,
El Stack *"vive"* en la memoria; no en el PCB ni localmente en la CPU.
Lo que si va a manejar el PCB es *donde* está el Stack.

**Comment by gvillarc91** [comment]
Con respecto a esta pregunta? Sigo sin entender.
"Me surje la duda porque al recibir el PCB del kernel, almacenamos el stack como variable local del CPU y primtivas, entonces, si no lo envío, como sabe el proximo CPU el contexto de lo ultimo que se ejecutó?"

**Comment by LeandroCarbajales** [comment]
Hola, como bien deducís se le debe devolver el PCB al kernel para que siga planificando al proceso y pueda darle el PCB actualizado al próximo CPU.
Saludos!

**Comment by LeandroCarbajales** [comment]
Hola, te quedó claro la duda? Podemos cerrar el issue?

**Comment by gvillarc91** [comment]
Ahi lo cierro, gracias!
