### ISSUE TITLE
Indice Etiquetas: Que guardo en PCB?

### ISSUE THREAD

**Issue by LeonelCurti** [sisoputnfrba/foro#719]
Con el tema del indice de etiquetas, para que funcione metadata_buscar_etiqueta en la CPU ademas del campo etiquetas de t_metadata_program tengo que guardarme el etiquetas_size en el pcb. Esto es asi?, por que sino no encuentro forma de sacar el tamaño de serializacion de las etiquetas.

**Comment by jazcarate** [comment]
Sip.

**Comment by LeonelCurti** [comment]
OK perfecto,  ultima pregunta y pueden cerrar el issue: 
t_size	etiquetas_size;				
char*        etiquetas; 
el etiquetas_size es exactamente tamaño en bytes del char* no?por que si le hago string_length a "etiquetas" me da otro valor.

**Comment by jazcarate** [comment]
Afirmativo.
_(El issue lo cerras vos con el botón de abajo)_
