### ISSUE TITLE
[Consola] Finalizacion forzosa de programas

### ISSUE THREAD

**Issue by Gruschka** [sisoputnfrba/foro#720]
Buenas! Estamos teniendo problemas con lo que es el comando "Finalizar Programa" de la consola. Entendemos que es abortivo, razon por la cual cada hilo programa que se quiera finalizar, tiene que cortar de inmediato sin importar que haga un 'clean up' de los recursos que tomo. Es por esto que decidimos usar ptread_kill

El problema que tenemos es que pthread_kill esta devolviendo 3 (cualquier cosa distinta de cero es error).  Lo curioso es que estamos usando un signal handler, ubicado al comienzo de la funcion que ejecuta cada hilo programa que hace un par de logs en consola, mediante la funcion write y nada de lo que se indica dentro del handler se muestra por pantalla, como si no entrara nunca.

Para dar un poco de contexto de como esta modelada la consola y el scope, consta de:

* Hilo principal (main): Este hilo ejecuta una funcion showMenu que da la opcion, entre otras, de ejecutar programas (startProgram)  y terminarlos (endProgram).
* Cuando se ejecuta startProgram se crea un nuevo hilo, que ejecuta la funcion executeProgram. Al comienzo de esta funcion se hace el signal handling con la siguiente linea de codigo:
        * signal(SIGUSR1, programThread_sig_handler);

Dentro del main, si se ejecuta endProgram se ejecuta -entre otras cosas- este codigo para matar al hilo:
  ```
    int result = pthread_kill(tToKill->threadID, SIGUSR1);

	if(result == 0){
	    	printf("Program finished successfully\n");
	    }else{
	    	printf("Error - program not finished successfully:[%d]\n",result);

	    }
	
```
	
Esto nos devuelve (3) como les conte anteriormente. 

Nuestro signal handler, por ahora, hace esto:

```
void programThread_sig_handler(int signo)
{
  write(1, "asd", 4);

  if (signo == SIGUSR1){
    write(1, "sig", 4);
    pthread_exit(0);
  }
    write(1, "sig", 4);


}
```
Muchisimas gracias!

**Comment by nicozar95** [comment]
Buenas
El valor 3 que te devuelve es el flag a ESRCH, que en humano vendría a ser que el id del thread que le estas pasando para cerrar (el `tToKill->threadID` ) no lo encuentra.

Fíjate si lo estas inicializando bien o si le estas pasando los punteros correctamente.

**Comment by Gruschka** [comment]
Hola @nicozar95 ! Muchas gracias por tu respuesta!

Si, me imagine que venia por la ahi la mano. Lo loco es que si yo debuggeo y me fijo el valor de tToKill y esta bien (en valor y tipo de dato). 

Saque un screenshot para que puedas ver esto (y una foto con el celu para que puedas ver el valor de tToKill->threadID al momento de la invocacion de pthread_kill, que como tengo que dejar el mouse posado sobre la variable no puedo pasar a mi sistema operativo host para sacar el screenshot). 

Mil gracias!!

![img_4614](https://cloud.githubusercontent.com/assets/11674324/26811949/37a1a792-4a4b-11e7-9492-64a7d81c9b59.JPG)
<img width="1875" alt="screen shot 2017-06-05 at 11 43 56 pm" src="https://cloud.githubusercontent.com/assets/11674324/26811951/37d08b02-4a4b-11e7-9761-3df7c6663890.png">

**Comment by nicozar95** [comment]
Buenas
Necesito un par de datos: ¿Que hace tu funcion `getThreadfromPID` (si no queres publicar codigo por  aca madamelo por mail)?¿Que ID te larga cuando creas el thread?

Estaria bueno que la impresion de errores sea con `perror` asi nos aseguramos que el error que te larga es porque no encuentra el thread, algo como:

```
int result=pthread_kill(....)
if (result != 0){
    perror("Error: ");
    return -1;
}
```

Asi podemos ver bien si el error es ESRCH, segun el man el valor 3 corresponde a ese, pero nunca se sabe.... mas que nada para sacarme esa duda.

**Comment by aocoda** [comment]
Hola @nicozar95, pudimos solucionar el tema de que el thread agarre la señal enviada con pthread_kill(), ahora la consulta respecto a eso seria, como podemos matar los hilos sin que nos mate el proceso main ya que si le mandamos SIGKILL, SIGABRT o SIGTERM nos finaliza el proceso padre también

Muchas Gracias

**Comment by nicozar95** [comment]
Segun el man de pthread_kill:

> Signal dispositions are process-wide: if a signal handler is
> installed, the handler will be invoked in the thread thread, but if
> the disposition of the signal is "stop", "continue", or "terminate",
> this action will affect the whole process.

En criollo, si vos le mandas SIGKILL, SIGABRT o SIGTERM se va a encargar el handler de signal del proceso, no de los hilos, prueben mandandole una señal distinta cuando llaman a pthread_kill como SIGUSR1 (como pusieron arriba)

**Comment by calvoluciano** [comment]
Estimados buenos días,

Estaba leyendo este issue, perdón que me meta en el incidente, el finalizar_programa debe ser abortivo?

Nosotros lo interpretamos como, enviar a Kernel un finalizar y una ves que el kernel devuelve el okey de finalizado se cerrara el hilo programa(El Kernel lo finalizara cuando salga de la cola Exec).

Entendemos que el Desconectar Consola si es abortivo y en ese caso si se matan todos los hilos sin liberar los recursos. Puede ser?

**Comment by nicozar95** [comment]
Ojo no te confundas, una cosa es el finalizar programa desde la consola del Kernel, que seria una finalizacion no abortiva.
Y otra cosa es que te desenchufe la computadora que estaba corriendo el proceso Consola, en ese caso la finalizacion seria derepente.

En el caso que te desconecte la Consola, si vas a tener que finalizar el resto de los procesos ansiso en el sistema.

**Comment by Gruschka** [comment]
@nicozar95 Me surge una duda con esta cuestion - mi ayudante me comento lo siguiente:

> Para determinar de que forma les conviene matar el hilo programa piensen que necesitan guardar un exit_code particular para un cierre por caída de consola y otro por el uso del comando finalizarPrograma, por lo que seguramente les convenga mandar algún mensaje al kernel para este último caso. El uso del comando finalizarPrograma es determinante, el programa tiene que finalizar su ejecución e ir a la cola de exit ni bien es enviado el comando.

Yo por esto entiendo que finalizar un programa via consola es abortivo - nosotros lo que estamos haciendo es llamar a _pthread_kill_ del hilo que se quiere finalizar (antes de matar el hilo se manda un exit code al kernel avisandole que se termino a pedido del usuario) pero en cualquier caso siempre se interrumpe la ejecucion del programa.

**Comment by nicozar95** [comment]
Esta bien, tenes 2 exit code uno es el abortivo lindo, que te mande a matar el proceso. Y el otro es el heavy metal, que te apago la maquina.
Puse no abortiva para que no se confunda con el abortiva heavy, pero de ambas maneras finaliza el proceso

**Comment by leandroventura** [comment]
Buenas, perdón que me meta en el tema, @aocoda como pudieron solucionar el inconveniente que tenían con el pthread_kill que les estaba devolviendo 3? A nosotros nos está pasando lo mismo. Agradecería si me decís como lo pudieron solucionar o que debieron tener en cuenta para eso. Saludos!

**Comment by sebastian-gulino** [comment]
Consulta, para terminar de redondear la idea, un programa puede finalizar por alguna de las siguientes formas:

**Comando finalizar programa** (Desde la consola del kernel o la consola consola): En este caso es no abortivo, y le tengo que pedir al kernel que lo finalice. Una vez que este me respondió el ok, puedo cancelar los hilos.

**Comando desconectar consola** (El que se envia dentro de la UI de la consola): En este caso es abortivo, le tengo que avisar al kernel (para que haga lo que corresponda), pero no espero respuesta y hago un kill de los hilos.

**Señal de interrupción** (Ctrl-C en el terminal): Idem al anterior, es abortivo, le tengo que avisar al kernel (para que haga lo que corresponda), pero no espero respuesta y hago un kill de los hilos.

**Muerte del proceso consola** (Se apago la maquina o cualquier idea similar): Acá quien tiene que detectarlo es el kernel, y hacer lo que corresponda. En la consola en sí no puedo hacer nada.

@nicozar95 si me podrías confirmar si es así, muy agradecido 😄

**Comment by nicozar95** [comment]
> Comando finalizar programa (Desde la consola del kernel o la consola consola): En este caso es no abortivo, y le tengo que pedir al kernel que lo finalice. Una vez que este me respondió el ok, puedo cancelar los hilos.

Es una finalizacion abortiva de la ejecucion normal del programa, entiendo que mi comentario anterior causo confusion ahi lo cambie :smile:.

> Comando desconectar consola (El que se envia dentro de la UI de la consola): En este caso es abortivo, le tengo que avisar al kernel (para que haga lo que corresponda), pero no espero respuesta y hago un kill de los hilos.
> 
> Señal de interrupción (Ctrl-C en el terminal): Idem al anterior, es abortivo, le tengo que avisar al kernel (para que haga lo que corresponda), pero no espero respuesta y hago un kill de los hilos.
> 
> Muerte del proceso consola (Se apago la maquina o cualquier idea similar): Acá quien tiene que detectarlo es el kernel, y hacer lo que corresponda. En la consola en sí no puedo hacer nada.

No veo diferencias :dancer:. Si las queres diferenciar hacelo, pero para mi es lo mismo, tene en cuenta que lo que nosostros vamos a evaluar es segun como muestran estos datos, traten de ser lo mas claros y expresivos en los logs que hagan, que no falten datos pero que no sobren.

Igual no se si lo diferenciaria tanto, uno para si apaque la maquina, otro para si tire el comando

Creo que hay mas, fijate en los exit code del enunciado porque otras razones puede terminar tu programa.

**Comment by sebastian-gulino** [comment]
Tenés toda la razon, cruzándolo con los exit code:

> Comando finalizar programa (Desde la consola del kernel o la consola consola): En este caso es no abortivo, y le tengo que pedir al kernel que lo finalice. Una vez que este me respondió el ok, puedo cancelar los hilos.

Es el unico caso en el cual la consola le va a "pedir" al kernel que lo finalice.
**Exit Code: -7 Finalizado a través del comando Finalizar Programa de la consola.** 

> Comando desconectar consola (El que se envia dentro de la UI de la consola): En este caso es abortivo, le tengo que avisar al kernel (para que haga lo que corresponda), pero no espero respuesta y hago un kill de los hilos.
> 
> Señal de interrupción (Ctrl-C en el terminal): Idem al anterior, es abortivo, le tengo que avisar al kernel (para que haga lo que corresponda), pero no espero respuesta y hago un kill de los hilos.
> 
> Muerte del proceso consola (Se apago la maquina o cualquier idea similar): Acá quien tiene que detectarlo es el kernel, y hacer lo que corresponda. En la consola en sí no puedo hacer nada.

Son todos lo mismo, la consola cierra, hace un kill de todo (siempre que pueda) y es el kernel quien va a detectar que se le desconecto un cliente X y tiene que hacer algo con eso.
**Exit Code: -6 Finalizado a través de desconexión de consola.**

Muchísimas gracias!

**Comment by calvoluciano** [comment]
@nicozar95

Tengo algunas dudas aun no cerradas,

-El Finalizar Programa (de Consola Consola), en los comentarios primero se dice que es abortivo después algunos interpretan que hay que mandar mensaje al kernel esperar respuesta y luego matar el hilo. Según tu comentario final no es así, debería ser abortivo es decir mando a kernel finalizar programa y termino el hilo, seria así?

-El finalizar programa (Consola Kernel), el Kernel mismo finalizara el programa y le mandara a consola que finalice y la consola matara el hilo en cuestion.

-Desconectar Consola, este si es abortivo mato todos los hilos y termino el proceso Consola, despues el kernel al detectar esta desconexion hara lo que corresponda con esos los procesos pertenecientes a esta consola.

Lo del control + C, hay que tenerlo en cuenta? No tendría porque hacerse un control+c de la consola, si tenemos el comando desconectar consola. no? Al menos no esta pedido en el TP.

**Comment by nicozar95** [comment]
> -El Finalizar Programa (de Consola Consola), en los comentarios primero se dice que es abortivo después algunos interpretan que hay que mandar mensaje al kernel esperar respuesta y luego matar el hilo. Según tu comentario final no es así, debería ser abortivo es decir mando a kernel finalizar programa y termino el hilo, seria así?

Es abortivo, es una manera de terminar **abortivamente** la ejecucion normal del programa. Ponele el nombre que quieras pero el programa no sigue con la planificacion normal del sistema.

> Lo del control + C, hay que tenerlo en cuenta? No tendría porque hacerse un control+c de la consola, si tenemos el comando desconectar consola. no? Al menos no esta pedido en el TP.

Si no pasa nada, si tenes el comando desconectar dejalo asi.

**Comment by calvoluciano** [comment]
@nicozar95 

Una consulta mas, respecto al Finalizar_Programa de Consola consola es necesario esperar el okey de finalizacion de programa del Kernel?
Porque por ejemplo en mi implementación utilizo un hilo que recibe mensajes del kernel, y por ejemplo yo mando finalizar_programa a PID 1, le mando el mensaje a kernel, el kernel hasta que termina la ejecucion me sigue mandando mensajes por ejemplo de impresión,  si yo mato mi hilo programa deberia hacer que se ignoren los mensajes que sigan llegando para el PID 1 (mientras el kernel finaliza la planificacion de ese PID)?

**Comment by Gruschka** [comment]
@calvoluciano 

El finalizar programa es abortivo entonces entiendo tiene que detener la ejecucion inmediatamente, mandandole  un mensaje al kernel con el exit code correspondiente pero no puede seguir ejecutando nada del programa con el pid 1.

**Comment by nicozar95** [comment]
@calvoluciano El tema es que el Kernel debe saber porque razon se cayo el programa ansisop cuando arma el trace de ejecucion de tu programa.

**Comment by calvoluciano** [comment]
@nicozar95

No entendí tu comentario?

La consola consola como la tengo armada manda el mensaje finalizar y termina el hilo, el kernel sabe que tiene que terminar cuando el CPU libere el pcb, mientras tanto va seguir ejecutando instrucciones, mi duda esta orientada a eso. 
En mi hilo escucha de mensajes de kernel me van a seguir llegando mensajes en el mientras tanto, siempre asumiendo que no hay desalojo del pcb por parte del kernel.

**Comment by nicozar95** [comment]
> La consola consola como la tengo armada manda el mensaje finalizar y termina el hilo, el kernel sabe que tiene que terminar cuando el CPU libere el pcb, mientras tanto va seguir ejecutando instrucciones, mi duda esta orientada a eso. 

Asi esta perfecto.

> En mi hilo escucha de mensajes de kernel me van a seguir llegando mensajes en el mientras tanto, siempre asumiendo que no hay desalojo del pcb por parte del kernel.

Lo que deberias hacer en ese caso es hacerle creer a tu programa que estas mandandole mensajes a la Consola. Por ejemplo, si tu programa justo manda a imprimir pero yo lo mate por consola. El kernel sabe que esos mensajes a impresion los tiene que ignorar, osea, le responde a la CPU como que ya imprimio en pantalla cuando en realidad ignoro el mensaje
