### ISSUE TITLE
tabla de paginas en memoria

### ISSUE THREAD

**Issue by lianndt** [sisoputnfrba/foro#721]
Buenas, 
Queria saber de que manera tiene que trabajar la tabla de paginas en memoria. Entiendo que la tabla tiene que estar grabada en los primeros N frames de la memoria. Calculo el peso de la tabla haciendo 12 bytes * cant. de frames / tamaño_frame y eso me da la cantidad de frames que tengo que reservar para la tabla. Hasta ahi todo bien, pero en el momento que tengo que escribir o leer, y por tanto usar la tabla, es valido hacer un "casteo" de memoria a una lista? Trabajarla en la estructura, y despues volver a bajarla con memcpy a memoria.

Gracias!

**Comment by nicozar95** [comment]
Si, siempre y cuando queden actualizada la tabla de paginas y el contenido de las paginas en el malloc enorme, son libres de administrarlo como quieran.

**Comment by nrmerlis** [comment]
hola, respecto a la tabla de paginas me surge la siguiente duda.
     1-  Aparte de guardar en el gran malloc las estructuras administrativas(Tabla de paginas), ¿Deberíamos también tener alguna otra estructura como una matriz para manejar los valores de esta tabla? o ¿deberíamos solo manejarla accediendo a sus campos y modificandolos desde el gran malloc?

     2- supongamos que tenemos 4 frames de 512 b, Estas estructuras se deberían guardar en el primer marco una al lado de la otra de a 12 b? osea.... el primer marco debería quedar ocupado con 48 bits? y solo los siguientes 3 marcos me quedarían libres para guardar paginas de procesos?

Gracias

**Comment by nicozar95** [comment]
> 1- Aparte de guardar en el gran malloc las estructuras administrativas(Tabla de paginas), ¿Deberíamos también tener alguna otra estructura como una matriz para manejar los valores de esta tabla? o ¿deberíamos solo manejarla accediendo a sus campos y modificandolos desde el gran malloc?

Creo que se discutio este asunto en otros issues, si podes usar estructuras administrativas aparte para manejar la tabla de pagina, siempre y cuando se vea reflejado los cambios en la tabla de pagina y los frames de memoria en el malloc enorme.

Lo mas sensato seria trabajar con la tabla de paginas y actualizarla directamente en vez de tener lista de entradas de tabla o una matriz.

> 2- supongamos que tenemos 4 frames de 512 b, Estas estructuras se deberían guardar en el primer marco una al lado de la otra de a 12 b? osea.... el primer marco debería quedar ocupado con 48 bits? y solo los siguientes 3 marcos me quedarían libres para guardar paginas de procesos?

Claro, el primer frame tendria el PID -1 ya que se corresponde a la tabla de pagina.
