### ISSUE TITLE
Duda return "validar" vs "validar" del check 4

### ISSUE THREAD

**Issue by TomasRS** [sisoputnfrba/foro#722]
Buenas, tengo una duda con respecto al resultado esperado de la función "validar" de FS.

En el enunciado dice:
Cuando el Proceso Kernel reciba la operación de abrir un archivo deberá **validar que el
archivo exista**.

Y para la entrega del check 4 hay un pequeño agregado que en el enunciado no lo dice:
El FS podrá responder una solicitud simple del Kernel como la existencia de un archivo **o su tamaño**.

¿La función validar entonces sólo dice si un archivo existe o además de validar si existe te devuelve el tamaño?

Gracias!

**Comment by nicozar95** [comment]
En el checkpoint 4 agregamos ese item para que ustedes lleguen al punto que se debe leer el archivo metadata del archivo sadica y puedan sacar la informacion correspondiente.

Ahora bien, en la entrega final. ¿Le sirve al Kernel conocer el tamaño?¿Cuando el Kernel le pide al FS que valide la existencia de un archivo?¿Para que?

**Comment by jbmild** [comment]
Claro, a eso iba nuestra pregunta. No hay ninguna primitiva que espere el tamaño del archivo por lo que solo usamos la info del tamaño internamente en el filesystem.
Por lo que para dejarlo en claro, no existe ni va a existir ninguna primitiva que solicite el size de un archivo, verdad?
