### ISSUE TITLE
Achicar el tamaño de archivos FS

### ISSUE THREAD

**Issue by jbmild** [sisoputnfrba/foro#723]
buenas,
se me genero una duda sobre el FS. Según veo las solicitudes que atiende y las primitivas que tenemos. Los archivos dentro del FS solo pueden crecer, nunca achicarse verdad? La única forma seria borrar el archivo y recrearlo con la nueva información?
Gracias

**Comment by nicozar95** [comment]
Asi es

**Comment by jbmild** [comment]
Genial, gracias
