### ISSUE TITLE
heap - lectura de pagina

### ISSUE THREAD

**Issue by juanignaciog** [sisoputnfrba/foro#725]
Hola

Me surgió una duda cuando se lee una pagina de heap de Memoria.
El Kernel tiene que ir leyendo los bloques de metadata de una pagina hasta que encuentre uno que muestre suficiente espacio para lo que necesita.
Mi duda es: 
Para hacer la lectura, el kernel podria pedir la pagina entera y después fijarse con todo el bloque que recibió, O podría realizar cada lectura de los bloques de metadata en diferentes solicitudes. Hay alguna manera o las 2 mal? O es a elección del grupo?

Gracias

**Comment by nicozar95** [comment]
> El Kernel tiene que ir leyendo los bloques de metadata de una pagina hasta que encuentre uno que muestre suficiente espacio para lo que necesita.

Ojo con esto, si el Kernel tiene que almacenar por ejemplo 500 bytes en una pagina del heap, puede que recorra todos los bloques de la pagina del heap y no encuentre ninguno que tiene espacio para ello.

Pero tal vez en esa pagina del heap en realidad habia 2 bloques de 250 bytes uno al lado del otro y tenia espacio para almacenarlo en esa pagina.... Deberias unificar estos 2 bloques libres si llegara a ser el caso.

> Para hacer la lectura, el kernel podria pedir la pagina entera y después fijarse con todo el bloque que recibió, O podría realizar cada lectura de los bloques de metadata en diferentes solicitudes. Hay alguna manera o las 2 mal? O es a elección del grupo?

Generalmente estaria bueno que se usara la red lo menos posible ¿Porque? Tarda mas, hay quilombos de sincronizacion de msj (aveces), etc, etc... Pero es a eleccion del grupo, si de ambas manera funciona y se respeta las operaciones de los modulos, entonces no hay drama :dancer:

**Comment by juanignaciog** [comment]
>Ojo con esto, si el Kernel tiene que almacenar por ejemplo 500 bytes en una pagina del heap, puede que recorra todos los bloques de la pagina del heap y no encuentre ninguno que tiene espacio para ello.
Pero tal vez en esa pagina del heap en realidad habia 2 bloques de 250 bytes uno al lado del otro y tenia espacio para almacenarlo en esa pagina.... Deberias unificar estos 2 bloques libres si llegara a ser el caso.

Si, tengo entendido que eso es parte de lo que se soluciona con la defragmentacion, si es asi, entonces no vamos a tener problema con eso. El resto ya me quedo claro, gracias.
