### ISSUE TITLE
pregunta sobre el exit code y señales en cpu

### ISSUE THREAD

**Issue by guillermo126** [sisoputnfrba/foro#726]
buenas hago dos preguntas:
1) ¿es resposabilidad de la cpu modificar el exit code porque cada que hay un error o se finaliza correctamente el programa?
2) cuando mando al señal SIGUSR1 dice que debera desconectarse la cpu una vez concluida la ejeccion del programa actual... eso significaria:
¿que por ejemplo para FIFO deberia terminar de ejecutar el ansisop de punta a punta y para RR deberia ejecutar hasta que se le termine el quantum y una vez pasado eso en ambos algoritmos mato a la cpu? eso no me quedo en claro..

**Comment by varas-c** [comment]
Hola!

Vamos por partes.

1 - La responsabilidad podes delegarla donde más te convenga. No está mal
que CPU o Kernel modifiquen el exit code, podes hacerlo como mas te
convenga.

2 - Es correcto lo que decís. Si hay un proceso ejecutando FIFO y mandas un
SIGUSR1 a la cpu, podés esperar a que ese proceso termine y ahí la bajás.
En Round Robin ocurre lo mismo. Si hay un proceso ejecutando y tirás un
SIGUSR1 al cpu, esperá a que termine su quantum para darla de baja.

Por si todavía tenés dudas sobre "qué es una señal", acá te dejo un poco de
info https://www.tutorialspoint.com/unix/unix-signals-traps.htm

Cualquier duda, pasate de nuevo!



2017-06-06 19:36 GMT-03:00 guillermo126 <notifications@github.com>:

**Comment by guillermo126** [comment]
Listo gracias cris!!
