### ISSUE TITLE
Consulta Consola de Kernel

### ISSUE THREAD

**Issue by fpatalagoity** [sisoputnfrba/foro#727]
Buenas, tengo una duda con esto:

> 2. Obtener para un proceso dado:
> b. La cantidad de operaciones privilegiadas que ejecutó.
> e. Cantidad de syscalls ejecutadas

¿Qué diferencia hay entre esos items? Porque a simple vista serían el mismo valor.

Gracias!

**Comment by varas-c** [comment]
Hola Fede!

Esther es una señora mayor y a veces se olvida o confunde cuando escribe
(?. Chiste aparte, tenés razón, es un ítem duplicado, los dos son la misma
cosa.

Gracias por el aviso!

2017-06-06 20:13 GMT-03:00 Francisco Patalagoity <notifications@github.com>:

**Comment by fpatalagoity** [comment]
Gracias!
