### ISSUE TITLE
Retorno de funciones parser (t_puntero) 

### ISSUE THREAD

**Issue by ivodan** [sisoputnfrba/foro#728]
Buenas!
Me quedaron algunas dudas sobre lo que estuvieron hablando en  #648 , mas que nada de la posicion que tiene que retornar la funcion.

> Ojo con eso porque aca vos estas manejando pocisiones de la Memoria en bytes, no paginas, estas pueden variar el tamaño segun el archivo de configuracion que tengas establecido, por ende la variable del tipo t_puntero seria algo como: pagina*tamaño_de_pagina + offset

Entonces por lo que entiendo, el valor del puntero hace referencia al "offset" que habria desde el inicio del bloque de memoria de mi proceso, hasta la posicion donde esta ubicada mi variable (incluyendo las paginas de codigo y de stack) ? 
Por ejemplo si tengo 2 paginas de codigo y suponiendo que el stack esta vacio, el puntero que retorna esta funcion seria 2*tamañoPagina+0  ?

**Comment by ivodan** [comment]
Leyendo la descripcion de la funcion obtenerPosicionVariable:

> Devuelve el desplazamiento respecto al inicio del segmento Stack en que se encuentra el valor de la variable identificador_variable del contexto actual.

Supongo que de manera análoga, definirVariable va a devolver tambien el desplazamiento desde el comienzo del stack, hasta mi variable. Agradecería que alguien me lo confirmara :)

Me surgio otra duda que tiene que ver con el issue, asi que la agrego:

> Reserva en el Contexto de Ejecución Actual el espacio necesario para una variable llamada identificador_variable y la registra tanto en el Stack como en el Diccionario de Variables.

Me nacen dos preguntas:

1. Cuando dice diccionario de variables se refiere al campo variables de mi indice de stack cierto?
2. Como dice "tanto en el stack como en el diccionario de variables", pienso que ademas que en el indice de stack, tengo que registrarlo en otro lado, pero supongo que al estar definiendo la variable, no tendria que guardar ningun valor en memoria. asi que la segunda pregunta seria: ademas de actualizar mi indice de stack, tengo que actualizar algo mas?

**Comment by nicozar95** [comment]
> Por ejemplo si tengo 2 paginas de codigo y suponiendo que el stack esta vacio, el puntero que retorna esta funcion seria 2*tamañoPagina+0 ?

Deberia

> definirVariable va a devolver tambien el desplazamiento desde el comienzo del stack, hasta mi variable. Agradecería que alguien me lo confirmara :)

El parser no entiende de Memoria el maneja punteros, como vos lo definas para que funcione, no hay problema.
Si vos estableciste que el obtenerPocisionVariable devuelve la pocision desde el inicio del stack, entonces deberias hacer que definir variable lo haga tambien desde ese lado.
Si vos estableciste que el obtenerPocisionVariable devuelve la pocision desde el inicio del espacio del proceso en Memoria, entonces deberias hacer que definir variable lo haga tambien desde ese lado.

> Cuando dice diccionario de variables se refiere al campo variables de mi indice de stack cierto?

Si, del contexto correspondiente.

> Como dice "tanto en el stack como en el diccionario de variables", pienso que ademas que en el indice de stack, tengo que registrarlo en otro lado, pero supongo que al estar definiendo la variable, no tendria que guardar ningun valor en memoria. asi que la segunda pregunta seria: ademas de actualizar mi indice de stack, tengo que actualizar algo mas?

Cuando llamas a definirVariable, solo definis la variable en tu indice de stack, no la guardas en Memoria aun. 
Despues si se actualizan otras estructuras del PCB. Y el program counter se actualiza cada vez que corres una sentencia...

**Comment by ivodan** [comment]
Todas las dudas resueltas, cierro el issue!
