### ISSUE TITLE
Guardado de codigo en Memoria

### ISSUE THREAD

**Issue by calvoluciano** [sisoputnfrba/foro#729]
Consulta, cuando tengo que enviar el código a Memoria, para el caso en el que el mismo ocupe mas de una pagina, debo recorrerlo y grabarlo en partes según el tamaño de pagina, ahora  como hago para que una instrucción no me quede cortada es decir una parte en una pagina y otra parte en otra?
Tengo que tener en cuenta esto?

**Comment by nicozar95** [comment]
Si, puede suceder que la instruccion te quede separada una en una pagina y otra en la otra, para ello la CPU deberia hacer otro pedido mas a Memoria.

**Comment by gabrielspisso** [comment]
Una consulta, es válido comprobar si va a cortarse una instrucción, y almacenarla  directamente en la próxima página?

**Comment by nicozar95** [comment]
Yo te diria que no, porque te queda una fragmentacion en tu Memoria, aparte es un toque mas rebuscado a la hora de escribir Codigo en Memoria.
Es mas facil, hacer 2 pedidos a Memoria uno de una parte, el otro de lo que te falta. Pegarlos y tener esa sentencia
