### ISSUE TITLE
Cursor de un archivo

### ISSUE THREAD

**Issue by Matias9635** [sisoputnfrba/foro#731]
Buenas, leyendo el issue #684 me surgió una duda: El Kernel debe conocer el valor del cursor para poder enviarle al File System en una petición de lectura o escritura el offset a partir del cual leer o escribir. Mi pregunta es si debo guardar el valor de cada cursor de cada archivo (para cada proceso) en el Kernel, por ejemplo agregando una columna "cursor" en la tabla de archivos de proceso.
Gracias.

**Comment by nicozar95** [comment]
Si, el Kernel es el que maneja los punteros de cada uno de los archivos para cada proceso. Podes manejarlo como quieras en la capa de FS del Kernel.

**Comment by Matias9635** [comment]
Perfecto, gracias
