### ISSUE TITLE
Variables compartidas

### ISSUE THREAD

**Issue by ivodan** [sisoputnfrba/foro#732]
Buenas,
Tengo una duda con respecto a las variables compartidas. En las funciones del cpu estan asignarValorCompartida y obtenerValorCompartida. No hay ninguna funcion que sea declarar o definir, por lo que se me ocurren dos soluciones en principio:
1.-El cpu solo puede usar las variables compartidas que ya vienen definidas en la configuracion del kernel.
2.-O desde el kernel (cuando el cpu me manda a asignar), si veo que no existe dicha variable la creo.
Gracias de antemano y saludos.

**Comment by nicozar95** [comment]
Buenas
En un programa ansisop no existe primitiva que defina **nuevas** variables globales, las variables globales la conocer el Kernel por archivo de configuracion, entonces si tengo un programita asi:

```
begin
   !colas = !colas +1
end
```

Eso deberia andar y fijate que nunca se define una variable ansisop, lo mas probable es que al ejecutar la linea del medio llame a obtenerValorCompartida y despues llame a asignarValorCompartida. Entonces con tus consultas

> 1-El cpu solo puede usar las variables compartidas que ya vienen definidas en la configuracion del kernel.

Si

> 2.-O desde el kernel (cuando el cpu me manda a asignar), si veo que no existe dicha variable la creo.

No. 

Los programas ansisop que les vamos a dar en la entrega final van a ser correctos, osea, no les vamos a poner nada raro para que el parser se queje, ni errores sintacticos ni semanticos
Saludos

**Comment by ivodan** [comment]
Buenisimo, muchas gracias!

> Los programas ansisop que les vamos a dar en la entrega final van a ser correctos, osea, no les vamos a poner nada raro para que el parser se queje, ni errores sintacticos ni semanticos
Saludos

Y muchas gracias! jaja
