### ISSUE TITLE
Administración Paginas Heap

### ISSUE THREAD

**Issue by picollomartin** [sisoputnfrba/foro#733]
Cuando administramos las paginas del heap de un proceso (que sabemos que tienen el espacio correspondiente al pedido), es conveniente traerse toda la página de memoria a kernel y trabajarla o ir pidiendo a demanda ?

Saludos!

**Comment by nicozar95** [comment]
Fijate que charlamos de eso en #725 
Si algo no se entiende avisa :smile:

**Comment by picollomartin** [comment]
Con eso me solucionas lo que pregunté, otra consulta relacionado con esto, puede suceder que un proceso pida memoria para una variable (50 bytes por ejemplo) y después asigne más de lo que pidió (60 bytes por ejemplo) ??

Saludos!

**Comment by nicozar95** [comment]
No, Los programas ansisop que les vamos a dar en la entrega final van a ser correctos, osea, no les vamos a poner nada raro para que el parser se queje, ni errores sintacticos ni semanticos
Saludos

**Comment by picollomartin** [comment]
Dale gracias !
