### ISSUE TITLE
Pedidos a Memoria y asignación de paginas iniciales.

### ISSUE THREAD

**Issue by sebachaves** [sisoputnfrba/foro#734]
Hola, tenemos unas dudas con estos temas.

Primero, las paginas iniciales, asignadas para código y stack, que su cantidad depende del tamaño del código y el STACK_SIZE. ¿Pueden estar en memoria de manera no contigua?

Segundo, si se solicita una lectura a la memoria que supera el limite de la pagina. ¿Es responsabilidad de la memoria buscar la pagina que tiene la información faltante?

Gracias!

**Comment by nicozar95** [comment]
Buenas

> Primero, las paginas iniciales, asignadas para código y stack, que su cantidad depende del tamaño del código y el STACK_SIZE. ¿Pueden estar en memoria de manera no contigua?

No, la asignacion de frames en la memoria es contigua, entonces los va a asignar contiguos.

> Segundo, si se solicita una lectura a la memoria que supera el limite de la pagina. ¿Es responsabilidad de la memoria buscar la pagina que tiene la información faltante?

No, La Memoria no sabe que le falta informacion, ni le interesa que informacion necesita cada moduo.
Si se solicita una lectura que supera el limite de pagina, osea, suponiendo que te quedo un cacho de los bytes en un frame y otro en el otro, deberias hacer 2 pedidos a Memoria.
¿Porque?
En sistemas operativos tratamos de acercarnos los mas posible a la realidad, En los sistemas reales lo que seria PAG,OFFSET en una arquitectura de paginas vendria a estar compuesto por un solo numero hexadecimal(depende mucho del hw esto y de la arquitectura de la computadora) entonces  si tengo este numerito en una arquitectura de paginas de 16bits: **0F,** se traduciria en pagina 0 offset 15. 
¿Como se traduciria el bit que sigue? No hay, esta en la otra pagina 
¿Como se traduciria la otra pagina? 10, pagina 1 offset 0.
En este tipo de arquitecturas no podes hacer algo como 0**G** porque a nivel bit es fisicamente imposible, estamos laburando en paginas de 15 bits.
¿Se entiende masomenos?
Por ahi viene la mano de que cuando hagas los pedidos de bytes lo hagas siguiendo el juego del tamaño de paginas, y si tenes que pedir un byte a una pagina y otro byte a otra, vas a tener q hacer 2 pedidos

**Comment by sebachaves** [comment]
Perfecto, super claro, gracias! :D

**Comment by dipatata** [comment]
Sebachaves, muy buena pregunta. Lo que no me queda claro entonces es, si en la memoria tengo 4 frames libres, pero dispersos. (puede pasar). Y el kernel me intenta iniciar un programa que ocupa no se, 2 paginas de codigo y una de stack. La memoria tendria que contestar que no puede iniciarlo porque no tiene 3 paginas contiguas aunque tenga 4 paginas libres ???

Gracias

**Comment by afilgueira** [comment]
Hola, después de charlar con Nico, hago una corrección.

La memoria LOGICA se asigna de forma contigua. Esto significa que nunca vas a tener una página N+1 sin haber tenido la N.

La memoria FISICA, para los procesos, se asigna usando la función de hash. Esto puede o no darte frames contiguos. Ver página 24 del enunciado de TP.

Saludos y disculpen los inconvenientes. Estamos trabajando para usted

**Comment by gonziesc** [comment]
Buenas! Pregunta con respecto a lo último.
Dice el enunciado:

> El Kernel será el encargado de administrar el ciclo de vida de estos bloques de memoria,
denominados Heap, de forma tal que permita al proceso reservar y liberar bloques de forma
aleatoria.

Entonces, cuando un proceso de pide memoria, dinámicamente le pido a memoria las páginas necesarias para cubrir ese espacio, inicializando con la estructura del metadata del heap, o esto se hace previamente y con una cantidad fija (o máxima) de páginas contiguas?
Mi pregunta sería cómo asegurar que las páginas destinadas a heap estén contiguas en memoria, ya que usando el hash las páginas físicas están dispersas, y cuándo realizar la asignación inicial.
Gracias!

**Comment by nicozar95** [comment]
> Entonces, cuando un proceso de pide memoria, dinámicamente le pido a memoria las páginas necesarias para cubrir ese espacio, inicializando con la estructura del metadata del heap, o esto se hace previamente y con una cantidad fija (o máxima) de páginas contiguas?

Cuando un proceso pide paginas a Memoria, Memoria se las da. Es responsabilidad del Kernel en escribir la metadata correspondiente al heap en esa paginas, osea, de hacerle un pedido de lectura.

> Mi pregunta sería cómo asegurar que las páginas destinadas a heap estén contiguas en memoria, ya que usando el hash las páginas físicas están dispersas, y cuándo realizar la asignación inicial.

No te podes asegurar, vos las paginas del proceso las manejas como si estuvieran una al lado de la otra, y los pedidos a Memoria los haces de la misma manera. La memoria es la que traduce ese pedido a un frame fisico. Por ejemplo: El proceso x solicita bytes de la pagina 0, la memoria se fija la pagina 0 de ese proceso a que frame corresponde, suponete que corresponde al 12839184. Va a ese frame y agarra el cacho de memoria.

> Además, en Memoria, Asignar Páginas a Proceso me tiene que retornar el puntero a la dirección que asigné, correcto?

No ¿Porque? Los punteros los manejas vos desde la pocision de tu proceso, no son los mismo los punteros logicos que los fisico. Los procesos manejan los punteros logicos, la memoria los traduce. Por ejemplo puede que el programa ansiso X e Y tengan el inicio de las paginas de codigo, ambos, en el puntero 0. Pero este no es el mismo puntero en la memoria fisica.

Asignar paginas te devolveria un si, si lo pudo asignar o un no si no lo pudo asignar.

**Comment by gonziesc** [comment]
Gracias!
