### ISSUE TITLE
consulta inicializacion indice de etiquetas

### ISSUE THREAD

**Issue by maurithebest** [sisoputnfrba/foro#735]
Consulta, cuando inicializamos el campo de indice de etiquetas del pcb?(creemos que es en el kernel cuando creamos la pcb)
Ademas queria preguntarles acerca de la funcion metadata_buscar_etiqueta, no estoy entiendiendo lo que hace y si deberia usarla para realizar la funicion irAlLabel, en el cual necesito las etiquetas para encontrar la que se esta usando en el GOTO y asi saber en que posicion esta para que siga la ejecucion del programa desde ese punto. Saludos.

**Comment by Emi0689** [comment]
Como estas? esto me paso así que te ayudo. Fijate que hay una función en el parser que se llama metadata_desde_literal, fijate que te devuelve un registro con todo lo que necesitas tanto para irALabel como las funciones de llamado.  Y la de metadata_buscar_etiqueta va a recibir desde el pcb lo que cargaste en medata_desde_literal y te va a devolver el puntero donde esta la etiqueta/funcion a donde queres ir.

**Comment by maurithebest** [comment]
Buenas, gracias por responder
A ver si entendi como funciona..
Yo en mi pcb, a la hora de inicializarlo, en el indice de etiquetas guardo los campos que me devuelve metadata_desde_literal: etiquetas (La serializacion de las etiquetas) y etiquetas_size. Luego en las funciones de salto que lee el cpu, uso metadata_buscar_etiqueta, pasandole por parametro el nombre de la etiqueta y los dos datos esos que antes guarde en el pcb. Esta funcion me devolveria la posicion de la etiqueta o de la primera instruccion util a partir de esa etiqueta?
Saludos!

**Comment by Emi0689** [comment]
Como estas? mira aclaro que soy alumno y no estoy del todo seguro hasta donde puedo contestar. Pero la idea es la que tenes! que instrucción te devuelve? te va a devolver en si donde esta la etiqueta, tene cuidado con los comentarios y demas porque por ahí por eso te da una posición menos o una mas, dependiendo tu modelo. Te recomiendo ir imprimiendo el valor de la instrucción a si vez que te devuelve. (Si no encuentra nada devuelve -1).

Por ultimo y no menor, para no hablar de mas, chequea los issues de la llamada con retorno, que llama a otras funciones antes con lo cual te puede variar el puntero que te devuelva y acomodarlo en base a eso.

Suerte!!

**Comment by maurithebest** [comment]
Muchas gracias. Saludos.
