### ISSUE TITLE
Politica de escritura en MP

### ISSUE THREAD

**Issue by dromero-7854** [sisoputnfrba/foro#736]
Buenas, les dejo dos consultas con respecto a la política de escritura en MP.

Según el enunciado, se aplica una política de escritura inmediata. Es decir, todas las operaciones de escritura se realizan tanto en cache como en MP, asegurando que la memoria principal siempre es válido.

1era Consulta: ¿Esto significa que todas las operaciones de escritura van a tener retardo de acceso a  memoria, por escribir siempre en MP?

2da Consulta: ¿Se puede aplicar una política de post-escritura? Es decir, actualizar solo la caché. Y en el caso que la entrada de la cache sea sustituido posteriormente, recién actualizar la MP, antes de pisar la entrada de cache (utilizar un bit "actualizar" para saber si antes de la sustitución debo actualizar la MP) De esta manera, no tendría retardo de acceso a memoria, si la pagina a actualizar se encuentra en la caché.

Espero sus comentarios...

Saludos
Dante Romero

**Comment by nicozar95** [comment]
> 1era Consulta: ¿Esto significa que todas las operaciones de escritura van a tener retardo de acceso a memoria, por escribir siempre en MP?

Si. El retardo de la MP, es un tiempo a responder al proceso que solicito la operacion. En el caso de escritura, como siempre se va a escribir en MP, y si la pagina llega a estar cacheada tambien en cache.
Osea, en caso de que vallas a escribir siempre tenes el retardo. En caso de que vayas a leer, depende si la pagina este en cache o no.

> 2da Consulta: ¿Se puede aplicar una política de post-escritura? Es decir, actualizar solo la caché. Y en el caso que la entrada de la cache sea sustituido posteriormente, recién actualizar la MP, antes de pisar la entrada de cache (utilizar un bit "actualizar" para saber si antes de la sustitución debo actualizar la MP) De esta manera, no tendría retardo de acceso a memoria, si la pagina a actualizar se encuentra en la caché.

No porque no cumple con las especificaciones de la operacion de escribir:

> **Almacenar bytes en una página**
>    **Parámetros: [Identificador del Programa], [#página], [offset], [tamaño] y [buffer]**
>     Ante un pedido de escritura de página de alguno de los procesadores, se realizará la
>     traducción a marco (frame), y se actualizará su contenido. En caso de que la página se
>     encuentre en Memoria Caché, se deberá actualizar también el frame alojado en la misma.

**Comment by dromero-7854** [comment]
Ok... Respondida la consulta... Cierro el issue... Gracias!!
