### ISSUE TITLE
Ansisop Escribir / File System / Firma

### ISSUE THREAD

**Issue by Emi0689** [sisoputnfrba/foro#737]
Buenas tardes/noches
Tengo una duda con la firma de la función ansisop "escribir". La misma entiendo que recibe el FD, "Texto", Size. Pero primero se ejecuta el obtener posición variable y al parecer lo hace en "Texto". O sea que "Texto" en realidad no debería ser una literal sino una variable? o sea que hay variables de string? Con un maximo de 4 bytes o pueden haber string gigantes? 

El ejemplo que probé es este: 
```

#!/usr/bin/ansisop
begin
	abrir LC Archivos/archivoPruebas.bin
	escribir 3 "bam" 4
end

```
Les agradezco mucho su tiempo!!!
Saludos!!

PD: el FD es 3 porque el primer archivo que creas tiene que arrancar en 3 por definicion de tp

**Comment by nicozar95** [comment]
Si, el texto vendria a ser una variable
En este TP, hay variables de sting en las paginas del heap, muy similar a cuando declaras un `char*` que tenes que pedir una cantidad de memoria con `malloc()`

El maximo de 4 bytes son para variables normales, en las variables que defino en el heap, puedo pedir el tamaño que me permita.

**Comment by Emi0689** [comment]
Perfecto! muchas gracias!

**Comment by Emi0689** [comment]
Mira me volvió a traer dudas.. Realmente hay variables de tipo String? El AsignarVariable recibe un int. Si le asigno un String para luego obtenerlo como una variable con el obtenerVariable, explota..  Pero el parser cada vez que ejecuto me llama al ObtenerVariable..

**Comment by Emi0689** [comment]
Pd: el reservar del heap también recibe un int. Si le mando String explotaria..

**Comment by nicozar95** [comment]
Si tenés razón. Era algo que me hacía un poco de ruido. Hoy confirme que las variables en el heap son de tipo entero... Si bien se sigue reservando memoria y todo lo demas

**Comment by Emi0689** [comment]
Joya con eso! Queda claro lo de las variables que son int. 
Entonces como haría para mandarle al ansioso escribir el texto?

**Comment by jazcarate** [comment]
la palabra `Hola!` en binario es: `01001000 01101111 01101100 01100001 00100001`, esto en int sin signo sería `18543 27745 8448 ` entonces sería:
```
begin
   variables a, b
   malloc a 20
   b = a
   *b = 18543
   b = b+4
   *b = 27745
   b = b+4
   *b = 8448
   escribir 1 a 5
   liberar a
end
```

**Comment by santiagovarela86** [comment]
Estos números sin signo son de 2 bytes, no debería sumarse 2 a b, es decir moverse 2 bytes de posición para guardar el siguiente número y no 4?

**Comment by riverosm** [comment]
Buenas, reabro este issue porque tengo la siguiente duda, a ver si entendí bien. En la prueba escribirFS.ansisop se ejecuta la siguiente línea:

> *b = 1095520072

¿En este caso no se debería dividir debido a que el valor entra en un entero sin signo? ¿b pasa a ser una variable de HEAP?

Muchas gracias, saludos.
