### ISSUE TITLE
buenas les hago una pregunta sobre la instruccion print de ansisop

### ISSUE THREAD

**Issue by guillermo126** [sisoputnfrba/foro#738]
buenas queria preguntarles cuales de las primitivas agarrar la funcion de ansisop print g, por ejemplo. por lo menos en paser.h no lo especifica o no me estoy dando cuenta, para ninguna de estas tipo de sentencias aparece cual primitiva la agarraria:

#define TEXT_PRINT_NUMBER "prints n"
	#define TEXT_PRINT_STRING "prints s"
	#define TEXT_PRINT_LITERAL "prints l"

 me gustaria que me digan cual la agarraria porque no me estoy dando cuenta, muchas gracias.

**Comment by fedebonisconti** [comment]
Buenas,

Fijate que en el _parser.c_, la función `_imprimir()` [es la que se llama](https://github.com/sisoputnfrba/ansisop-parser/blob/master/parser/parser/parser.c#L433) en cada uno de los distintos casos. Mirá bien dónde se usa la función dentro del `analizarLinea()`, y ahí te dice qué primitiva es la que usa!

Saludos!

**Comment by sebachaves** [comment]
Hola!

Consulta, estoy con el mismo problema. 

Estaba debugeando la ejecución de este código AnSISOP:

#!/usr/bin/ansisop
begin
variables a, g
	a = 1
	prints a
end

Y la primitiva a la que llama es "AnSISOP_llamarSinRetorno"

Saludos!
![2017-06-11-172029_1366x768_scrot](https://user-images.githubusercontent.com/11946985/27014241-3733372e-4ecb-11e7-9fad-a6cfadc879b1.png)

**Comment by nicozar95** [comment]
Buenas fijate que ya se trato ese tema en #682

**Comment by guillermo126** [comment]
buenas la verdad que me sigue sin quedar en claro que primitivas agarra y al leer el otro issue el #682 me hizo generar mas dudas... esto pusieron en ese issue:
prints n 1+y //Imprime la variable y + 1 en pantalla
	prints s x //Imprime el contenido de la variable x de memoria
	prints 1 hola //Imprime un literal cadena "hola"

yo me guie por ejemplo con el ansisop completo y por ejemplo en el mismo aparecen cosas como:
print $0+1 o imprimir A
a lo que me lleva a preguntar....
lo que pusieron ustedes es que la funcion en ansisop seria prints que iria con s y que recibe dos parametros, que es diferente al que esta en el del ejemplo del ansisop completo... 
¿de cual deberia guiarme de ahora en mas? y segundo
no entiendo cuales primitivas me agarraria para imprimir algo...
yo me hice un mock del parser y las primitivas que me agarra cuando ejecuto print A serian:

se ejecuta la primitiva OBTENER POSICION VARIABLE de: A
 se ejecuta la primitiva DESREFERENCIAR de 1
 se ejecuto la primitiva LLAMAR SIN RETORNO con el valor:print

no le veo sentido que llame a llamar sin retorno, gracias

**Comment by nicozar95** [comment]
El parser ha ido evolucionando a lo largo del tiempo, antiguamente existian esas versiones (imprimir/print) para imprimir por pantalla. En el repo que vos estas mirando, lo mas probable es que los scripts no este actualizados a la nueva version del parser. Quedense tranquilos que los scripts que les vamos a dar en la evaluacion final van a estar bien escritos. 
Si quieren probar la ejecucion del parser en sus TP son libres de actualizar estos scripts para usarlos como quieran, por ejemplo, reemplazando `print x` por `prints n x` por ejemplo.

El parser llama a LLAMAR SIN RETORNO cuando encuentra una palabra que no la tiene en la sintaxis, piensa que es una funcion y te dice "che ejecutame la funcion print". En la version mas actual del parser (la que estamos haciendo en este TP) `print` ya no es una palabra reservada del lenguaje, por que ahora podes imprimir strings.

**Comment by sebachaves** [comment]
Perfecto gracias!
