### ISSUE TITLE
Duda actualizacion de pcb

### ISSUE THREAD

**Issue by fededri** [sisoputnfrba/foro#739]
Buenas, me surgio una duda con lo siguiente:
Supongamos que ante un mensaje de la cpu, el kernel detecte un error y decida finalizar el proceso que la cpu tiene en ejecucion. 
La cpu deberia mandarle el pcb al kernel para que este deje en la cola de finalizados el pcb mas actualizado?

**Comment by nicozar95** [comment]
Si, se debe informa como termino cada proceso. Y para _rastrear_ masomenos los procesos que se ejecutaron y finalizaron de cualquier manera (anormal o normal) lo tiene en una cola de finalizacion el Kernel.

**Comment by lucasnvp** [comment]
Hola, tengo una consulta sobre la cola de finalizacion. Si cada proceso finalizado lo voy dejando en mi pila de Exit nunca estaría liberando el espacio que ocupa cada uno de los procesos. Mi consulta es, lo dejo ahí o los agrego a un log así puedo liberarlos. 

Saludos.

**Comment by LeandroCarbajales** [comment]
Por qué no podrías liberar los recursos de un proceso al momento de pasarlo a la cola _exit?_

**Comment by ivanedh** [comment]
Respecto a la ultima pregunta/respuesta:
- Si por recursos nos referimos al PCB, creo que pierde un poco el sentido guardar los procesos en una cola exit cuando no guardamos el estado final del PCB. Ademas en caso de liberar toda esta información lo que comenta nicozar95 no seria necesario, ¿Con que fin actualizamos el PCB de un proceso que fallo cuando vamos a liberar toda esa información?
- Si por recursos nos referimos a las memorias, estoy de acuerdo habría que liberarlas.

**Comment by LeandroCarbajales** [comment]
Buen análisis :), con recursos del proceso me refería al 2do punto, la memoria que el mismo tiene asignada. Liberando esa memoria pueden seguir ejecutando otros procesos y teniendo el pcb actualizado en una cola _exit_ les permite rastrear e informar el estado de finalización de los procesos.

**Comment by tferraro** [comment]
@lucasnvp te sirvió la respuesta de lean para ver por donde encararlo? Como lo solucionaste?
Lo mismo para @ivanedh, como venis con esto?

Así si están todas las dudas resueltas cerramos este issue.

Saludos!

**Comment by lucasnvp** [comment]
@tferraro Si me sirvió, muchas gracias. Lo dejo en la cola de EXIT y libero todos los recursos que no necesita. 

Saludos.
