### ISSUE TITLE
Duda sobre bitarray_create_with_mode

### ISSUE THREAD

**Issue by AltTomas** [sisoputnfrba/foro#740]
Hola! Será posible se me explique el uso al char * del primer parametro de la funcion? No termino de entender cual es el uso. Debería ahí poner el magic number de SADICA para hacer un chequeo de que ese archivo pertenece al FS? O se está esperando algún tipo de dato específico que no me doy cuenta?

Muchas gracias!
Saludos!

**Comment by jhonSalazar** [comment]
Buenas,
Ese primer parámetro, es el cacho de memoria del bitmap que vas obtener con una funcion read(   ) o mmap(  ). Luego de obener ese cacho de memoria se la pasa como argumento a la funcion 
bitarray_create_with_mode, de tal manera que puedas crear el bitarray.

Saludos.

**Comment by AltTomas** [comment]
Genial, muchas gracias.
Ahora bien, el lenght del mmap debería ser el tamaño del bitmap? O sea la cantidad de bloques que este debería tener, verdad?

**Comment by jhonSalazar** [comment]
Ese tamaño, debería ser el tamaño del archivo bitmap.bin, esos están a nivel  bytes( por ejemplo pueden pesar 5 bytes), cuando quieras recorrer el bitmap vas a tener que interar --> tamanio*8  ( 40 bloques) -->, ya que esta a nivel de bit y un byte son 8 bits,

Saludos.

**Comment by AltTomas** [comment]
Perfecto, gracias!
