### ISSUE TITLE
programa para probar fs

### ISSUE THREAD

**Issue by ziggylineous** [sisoputnfrba/foro#741]
buenas. quise descifrar cómo hacer un programa ansisop para probar fs pero no me salió. traté:

#!/usr/bin/ansisop
begin
    abrir CE hola.bin
    escribir 3 hola_amiguito_como_vas 22 
    cerrar 3
end

pero el escribir me llamó obtener variable con h o trató de dereferenciar h. Viendo en el parser ví que el 2ndo arg (en mi caso hola_amiguito...) es el nombre de una var o arg que te da un t_puntero a donde comienza el string que queres escribir. Entonces mi programa tendría que definir variables para poder escribir en el filesys? Así?

#!/usr/bin/ansisop
begin
    variables a, b, c
    a = 55
    b = 56
    c = 57
    abrir CE abc.bin
    escribir 3 a 3 
    cerrar 3
end

así escribiría en el stack 55 56 57 y le digo q empiece a leer en la posición de 'a' 3 bytes según lo q leí del parser. (por ahí tendría que decirle que lea 12). Así funciona?
si no suban un ejemplo y expliquen los args de escribir

**Comment by ziggylineous** [comment]
#737

**Comment by tferraro** [comment]
Holis,
Pegale una leída a las primitivas de ansisop antes de seguir leyendo esto.
Ahora si, con las primitivas en mano, fijate que escribir recibe como parámetro un _descriptor de archivo_ , ese descriptor lo tendrias que tener almacenado en algun lado, como en una variable. 
La pregunta es, de donde lo obtenemos? Mirate que dice que hace la función *abrir* 😉

Saludos!

**Comment by ziggylineous** [comment]
`abrir`, la func que implementamos nosotros retorna un descriptor, sí, pero el parser no ví que use ese valor para asignarselo a una var; por eso hardcodié 3.

Igual lo que más dudas tengo es cómo se le pasa a `escribir` el string que tiene que mandar a escribir a un archivo. Viendo el código parece que hay que pasarle una variable a partir de la que empieza a leer en el stack. Entonces para construir el string hay que ir metiendo ints en el stack? En parser.c para armar el texto se llama a _obtenerString que busca el offset en el stack del segundo arg de escribir y va leyendo a partir. O sea, el segundo arg no es un string, sino una var que usa para obtener una pos en el stack para empezar a leer

**Comment by jazcarate** [comment]
Usted muchacho, ha encontrado un problema!
`abrir` debería "devolver" el file descriptor.

Sobre lo segudo: si, `escribir` necesita una posición, pero no necesariamente de Stack. Lo más probable es que sea un pedazo de memoria del `heap`. Ansisop no sabe que es un String, por eso es que es tan "incomodo" usar texto :smile_cat:

**Comment by Emi0689** [comment]
Me sumo desde mi issue que es el mismo tema. #737
El problema con el heap, es que tampoco puede recibir un string. Reservar, recibe un int en sus parametros... si le mando para alocar un string rompe..

**Comment by ziggylineous** [comment]
entonces la firma de escribir es así no?:
escribir
    int descriptorProceso (por ahora hardcodearla llevando vos la cuenta),
    t_puntero donde empieza en memoria el string (puede ser en el stack o en heap), 
    int cantidad a leer desde el arg anterior

**Comment by ziggylineous** [comment]
Es medio raro esa forma de armar strings. Para armar el string el parser empieza a leer desde memoria desde la pos inicial que le pasas. lee la cantidad de veces que le pasas. lo que es medio raro es que va leyendo ints desde memoria y despues los va concatenando al string que forma como chars. además esos ints que lee son ints que va formando con 1 de offset.
si guardo en memoria 1, 2 y 3, en memoria queda:
00 00 00 01 | 00 00 00 02 | 00 00 00 03
pero después va leyendo 
00 00 00 01, 00 00 01 00, 00 01 00 00, 01 00 00 00, 
00 00 00 02, 00 00 02 00, 00 02 00 00, 02 00 00 00,
etc
y además eso lo concatena como char. Cómo armas un string así? Le estoy pifiando en algún lado?

**Comment by jazcarate** [comment]
@Emi0689 `strlen`, `fileDescriptor`, ni strings escritas como literales en el código funcionan en AnSISOP. Es un lenguaje muy limitado. En el issue que mencionas puse un ejemplo de como podría uno grabar un string (https://github.com/sisoputnfrba/foro/issues/737#issuecomment-308243743). Pero acá @ziggylineous podría corregirme; porque mirando [el test de escribir literales](https://github.com/sisoputnfrba/ansisop-parser/blob/master/parser-tests/analizadorLineaTest.c#L110-L121), parecería que pasa lo que vos decis; y que escribir va ciclando sumando de a 1 `char` y no un `int`; el culpable sería [esta linea de código](https://github.com/sisoputnfrba/ansisop-parser/blob/master/parser/parser/parser.c#L197), pero si sumasemos de a 4, sería diferente como se graba un string si se `lee` de un archivo, que si se "hace a mano"; así que por ahora mantengamos un AnSISOP para probar de:

```
begin
    variables a, b
    alocar a 50
    abrir LC /utn/so/archivo
    leer 3 a 5
    escribir 0 a 5
   liberar a
end
```

**Comment by nicozar95** [comment]
Buenas
Salio una nueva version del parser que ahora si devuelve el fd, lo qe cambio es que ahora cuando llamas al archivo es con una sentencia onda:
`abrir a LC /utn/so/archivo`
Esto va a disparar:

-  un `(*AnSISOP_abrir)` del archivo `/utn/so/archivo` con los flags `LC` devolviendo un fd.

- un `(*AnSISOP_obtenerPosicionVariable)` de la variable `a`

- un `(*AnSISOP_asignar)` del fd a la variable `a`

Saludos

**Comment by Emi0689** [comment]
Ok. Ahí lo actualizamos. Gracias por el aviso!
Quedo a la espera entonces de la confirmación oficial de como hacer el "escribir" si ciclar de a un char o un int.

**Comment by nicozar95** [comment]
Si escribir va a ir ciclando de a ints.

**Comment by ziggylineous** [comment]
ah ok, si va a cambiar eso también cierro
