### ISSUE TITLE
Administración del Heap

### ISSUE THREAD

**Issue by fedeGiussa25** [sisoputnfrba/foro#742]
Buenas.
Tengo 2 dudas. Primero, quería saber como sería la sintaxis completa de un programa ansisop que hace uso del Heap. Tengo entendido que para reservar memoria y liberarla sería algo como lo siguiente.
Ejemplo:
begin
      variables a,b
      alocar a 50
      alocar b 20
      liberar a
      liberar b
end

Mi duda es, como utilizo el espacio reservado? Si quiero guardar el valor de una variable , por ejemplo, guardar el valor 5 en un espacio reservado, como sería la sintaxis de dicha asignación en lenguaje ansisop?

Mi segunda duda es mas bien funcional. Si acaso en un programa de ansisop se reservara un espacio de 1 byte, y se intentara guardar el valor de una variable en dicho espacio, se ocasionaría con Segmentation Fault (Porque el tamaño de un entero es de 4 bytes). Deberíamos contemplar la posibilidad de que ocurra esto y hacer que desde el Kernel se maneje esto como una excepción, abortando el programa en cuestión? O en los programas con los que nos van a evaluar no esta contemplado dicho problema?

Muchas Gracias

**Comment by jazcarate** [comment]
1.
```
begin
    variables a, b
    alocar a 50
        #a va a tener el valor de la posicion de moemoria en el heap
    *a = 5
        # pondría al principio de ese cachito de stack el numero 5 en los primeros 4 bytes
    print n *a
        #deberia imprimir 20
    b = 3 + *a
    *b = 10
        #pondria el 10 en los sigueintes 3 bytes. Esto pisaria algunos bits del primer 5
    print n *a
        #deberia imprimir cosas horribles!
    liberar a
end
```

2. Sipi. AnSisop solo guarda valores enteros de 4 bytes. Pero el kernel debería contemplar que esto pueda pasar, y abortar.
A modo funcional, debería ser bastante gratis implementarlo, si lo implementas en _los otros "segmentos"_ que reservas. El de Heap no es diferente.

**Comment by fedeGiussa25** [comment]
Perfecto, se entendió todo. Muchas gracias. Cierro el issue.
