### ISSUE TITLE
Consulta: Guardar Fd retornado en abrir()

### ISSUE THREAD

**Issue by soga89** [sisoputnfrba/foro#743]
Tengo el siguiente codigo ansisop:
***************
begin
    variables a,b
    a=20
    b=abrir LC /utn/so
    prints n a
end
****************
cuando ejecuto la instruccion 'abrir ' esta le manda la direccion(path) y los permisos sobre dicho archivo al kernel, este le devuelve el fd 2 (hardcodeado) que es el que devuelvo como t_descriptor_archivo. Pero ocurren 2 cosas, si lo utilizo de la forma como lo tengo declarado el analizador no lo detecta como una instruccion de abrir archivo, solo de asignarle el valor de 'a' (direccion 0) a 'b'(direccion 4). Pero si utilizo la funcion sin el b=.... y solo lo coloco como ' abrir /.../ ' ingresa a dicha funcion pero no llama luego a la funcion asignar.¿donde debería almacenar el fd que recibí? ¿Es un error en el analizador o tendria que interpretarlo de otra manera?. Gracias

**Comment by ziggylineous** [comment]
fijate #741, los posts 4 y 5. por ahora hardcodeá el fd en el programa ansisop

**Comment by nicozar95** [comment]
Buenas
Salio una nueva version del parser que ahora si devuelve el fd, lo qe cambio es que ahora cuando llamas al archivo es con una sentencia onda:
`abrir a LC /utn/so/archivo`
Esto va a disparar:

-  un `(*AnSISOP_abrir)` del archivo `/utn/so/archivo` con los flags `LC` devolviendo un fd.

- un `(*AnSISOP_obtenerPosicionVariable)` de la variable `a`

- un `(*AnSISOP_asignar)` del fd a la variable `a`

Saludos

**Comment by soga89** [comment]
Listo, lo cierro!!!
