### ISSUE TITLE
Duda Reorganizacion Heap

### ISSUE THREAD

**Issue by santiagovarela86** [sisoputnfrba/foro#744]
Estimados,

Tengo la siguiente duda.

Si tengo el siguiente código:

`begin`
`variables a, b, c, d`
`alocar a 50`
`alocar b 50`
`alocar c 50`
`alocar d 50`
`liberar a`
`liberar b`
`end`

Esto primero me define las 4 variables, en una pagina de stack del proceso, en su offset correspondiente.
Esto da una direccion en el bloque de memoria para cada variable.
Ej.: &a = 11528, &b = 11532, &c = 11540, &d = 11548.

Luego cuando hago los 4 alocar, en cada direccion de las de arriba, guarda un valor, el valor del puntero de heap, es decir la posición donde empieza el bloque de heap.
Ej.: *a = 73728, *b = 73786, *c = 73844, *d = 73902

Ahora, cuando yo hago la liberación del bloque de heap, primero obtengo la posicion de la variable, luego con esto busco el valor de la variable y con esto obtengo la direccion del puntero que quiero eliminar.

Luego en la memoria ubico el metadata correspondiente a este bloque, lo marco como libre, y luego procedo a reordenar el espacio en la pagina de heap.

Lo que hago para reordenar es lo siguiente:

Desplazo hacia la izquierda en la pagina de heap todos los metadata que no están vacíos hasta la posicion del metadata que marqué como libre y luego al ultimo metadata libre le pongo el nuevo valor de espacio libre.

Hasta ahi todo estaría ok, entiendo. Lo que pasa es lo siguiente, ahora, cada bloque de memoria de heap, se desplazo hacia la izquierda N posiciones; N depende del tamaño del HeapMetadata y el tamaño del bloque liberado.

Ahora, cuando voy a ejecutar el segundo liberar (liberar b), el contenido de b, TIENE EL VIEJO VALOR del puntero de heap asociado y cuando va a liberar, el Kernel detecta que esa reserva no existe.

Yo en el kernel tengo una lista de administracion de paginas de heap, cada item de administración de pagina de heap tiene una lista de reservas, cada una de estas reservas tiene una direccion, a la cual le estoy haciendo el desplazamiento del valor indicado en memoria. Esto mantiene la coherencia en el Kernel con respecto a las direcciones de reservas de heap.

Lo que no estoy logrando comprender es como actualizar el contenido de las variables que tienen direcciones de puntero, para que refresquen el nuevo valor, haciendolo desde Memoria.

Es decir, luego de "liberar a", entiendo que los contenidos de las variables que apuntan a punteros de heap deberían quedar de la siguiente forma:

Ej.: *a = 0, *b = 73728, *c = 73786, *d = 73844.

**Comment by nicozar95** [comment]
Buenas
Alto laburo con los punteros estas haciendo para poder tener la menor fragmentacion externa. Sin embargo, no se si nos estirariamos hasta ese extremo para ahorrar memoria en el TP. Osea, no hace falta mover todos los punteros hasta la izquieda para poder dejar un cacho de memoria libre.
Con solo unificar los 2 cachos de memoria libres en uno solo alcanza, que los punteros c y d mantengan su pocision original en el heap.
Saludos
