### ISSUE TITLE
Metadata.bin y archivos de usuario

### ISSUE THREAD

**Issue by nicolasreyd** [sisoputnfrba/foro#745]
Hola, como va?

Tengo una consulta sobre la forma de escritura en los archivos mencionados.
Para poder consultarlos y actualizarlos de una forma fácil entiendo que lo mejor es tratarlos como un **t_config***. Por ejemplo el tema "Bloques" de un archivo de usuario, lo podría leer facilmente con: 
`config_get_array_value()`.

El tema que esta biblioteca no contempla la escritura de los mismos. 
Estoy tratando de hacer algo como esto pero aún no pude escribir correctamente (de hecho no escribe nada): 
```

 char* path = "/home/utnso/workspace/test";
 FILE* file = fopen(path, "w+");
```
	if (file == NULL) {
		return NULL;
	}

	t_config *config = malloc(sizeof(t_config));
	config->path = strdup(path);
	config->properties = dictionary_create();

	dictionary_put(config->properties, "VALOR", "1");`

Se les ocurre que puede estar pasando? Me leí el config.c y no hace mucho más que esto. Solo que parsea un buffer que lee de un archivo para despues convertirlo y guardarlo en el "properties" (diccionario) del config.

Saludos y gracias

**Comment by CarolinaPonceRodriguez** [comment]
Me sumo a la consulta, el mi caso trate de escribir con write pero me encuentro con un problema al realizar el salto de linea, ya que en general en los archivos de configuracion entre key y key "se deja espacio" pero al escribir con write, no se pueden dejar bytes libres entre medio.
Saludos.

**Comment by nicozar95** [comment]
Buenas
Subimos una [nueva versión de las commons](https://github.com/sisoputnfrba/so-commons-library) para poder escribir archivos de configuracion y solucionarles este tema.
Es un feature nuevo, hicimos un par de test pero si encuentren algun bug o algo que no les cierra por favor haganoslo avisar.

**Comment by nicolasreyd** [comment]
Hola, lo probe y anda 10 puntos. Mil gracias, me vino barbaro.

Cierro el issue.
