### ISSUE TITLE
Cierta parte de un archivo a un array de enteros

### ISSUE THREAD

**Issue by mezeitune** [sisoputnfrba/foro#746]
Hola como va?
Estoy teniendo un problema con pasar una especifica parte de un archivo a un array de enteros.
Por ejemplo el archivo seria este:
```
TAMANIO=250
BLOQUES=[40,21,45,67]
```
como tendria que hacer para que 40 , 21 , 45 , 67 me quede todo en un array?
estuve investigando un poco por stackoverflow , y con esto si me lo pasa a un array:
```
	FILE* f = fopen("../Archivos/test.bin", "r");
    int     someArr[32];
    int     i, ctr = 0;



    while((!feof(f)) && (ctr < 32))
    {
        fscanf(f, "%d,", &someArr[ctr++]);
    }
```

Pero solo si en el archivo esta 40,21,45,67 y nada mas.
Calculo yo que lo que me faltaria hacer es un fseek y dejar el puntero donde encuentre el corchete , pero no me estaria saliendo sinceramente.
Habra una funcion magica en las commons o alguien ya se topo con este problema?

Muchas Gracias

**Comment by CarolinaPonceRodriguez** [comment]
Hola! Tenes las funciones de las commons de config: get_config_array_value() o algo asi.
Saludos!

**Comment by mezeitune** [comment]
Muchas Gracias.
No la habia visto , sabia que por las commons tenia que haber algo jajaja.
Saludos
