### ISSUE TITLE
duda funcion BORRAR del parser

### ISSUE THREAD

**Issue by arurem** [sisoputnfrba/foro#747]
hola, buen dia, tengo una duda con la siguiente funcion que pertenece al parser.H:

                 * BORRAR ARCHIVO
		 *
		 * Informa al Kernel que el proceso requiere que se borre un archivo.
		 *
		 * @syntax 	TEXT_DELETE_FILE (borrar)
		 * @param	descriptor_archivo		Descriptor de archivo del archivo a borrar
		 * @return	void
		 */
		void (*AnSISOP_borrar)(t_descriptor_archivo descriptor_archivo);	

me parece que no entiendo bien como relacionar el t_descriptor_archivo que es de tipo u_int_32_t (un numero) con un path que es una cadena.

tengo las siguientes estructuras en kernel de la capa file system:

_ tabla global. la cual contiene el path que necesito para decirle a FS que borre el archivo.
_ tablas de los procesos.

lo que no entiendo es lo siguiente:
pude relacionar el descriptor de archivo (FD) con la tabla de proceso y ver el path en la tabla global, pero al darme cuenta de esto pude notar que:
1_ si el parser pide al kernel que cierre un archivo, se le tendra que restar 1 al campo open para ese path; si este es igual a 0 entoncs se tendra que quitar esta entrada de la tabla global.
2_ si el parser quiere borrar un fd, relacionando las tablas puedo llegar a obtener el path de la tabla global, pero esta entrada va a tener un open > 0, entoncs no la voy a poder borrar segun el enunciado. en el caso que no encuentre como relacionar una entrada de la tabla de un proceso con una entrada de la tabla global, ya sea porq no se encuentra el fd, o bien si está, no hay una entrada en la tabla tampoco puedo borrarlo porque no puedo conseguir el path del archivo.

la conclusion a la que llegue es qe esta funcion (Borrar del parser.h) nunca la voy a usar... lo que me hace pensar que como lo vine planteando esta mal.  =(

**Comment by jazcarate** [comment]
Holitas,
La relación entre la cadena `/home/utnso/miArchivo` y el File Descriptor `7` te la da el [`t_descriptor_archivo abrir(t_direccion_archivo direccion, t_banderas flags)`](https://github.com/sisoputnfrba/ansisop-parser/blob/master/parser/parser/parser.h#L257-L267).

Vas a poder borrar un archivo si sos *el único* que lo tiene abierto; osea que el atributo de cantidad de `open` en tu tabla _de archivos_ va a estár en `1` (este programa que quiera borrar).

```
begin
    variables a
    abrir a LC /unPath/unArchivo
    borrar a
```

después de ejecutar este programa; no debería existir el archivo `/unPath/unArchivo`

**Comment by arurem** [comment]
Ejecute el script, y el parser me tira que el path del archivo es LC. Cuando borro el LC y parser me da bien el path, lo que no se es donde deberian ir los flags.

**Comment by jazcarate** [comment]
Si debugeas tu función de `abrir` que le das al Parser; cuales son los atributos que llegan en `direccion` y `banderas`?

**Comment by NicoLuis** [comment]
Pusimos un breakpoint en la primer linea de la funcion abrir y al ejecutar el script nos dio esto

![sin titulo](https://user-images.githubusercontent.com/11791423/27412099-ab84a194-56c8-11e7-9d2d-c167f1bffed3.png)

**Comment by ivodan** [comment]
Pudieron resolver la duda al final?
Como logras obtener el path con el FD que te pasa el cpu, si no existe la entrada en la tabla global?

**Comment by mgarciaisaia** [comment]
@ivodan ¿por qué no existiría la entrada en la tabla global?

O, mirándolo por el otro lado, ¿cuándo _sí_ va a existir la entrada en la tabla global?

**Comment by ivodan** [comment]
Buenas @mgarciaisaia, la verdad es que llegue a esta conclusión mirando issues y analizando lo que dice el tp.

> ¿cuándo sí va a existir la entrada en la tabla global?

En el tp dice esto, con respecto a la peticion del cpu de abrir un archivo:

> El kernel recibirá un path de un archivo y los permisos de apertura, generará un File Descriptor y se
> lo devolverá a la CPU para que esta continúe con la ejecución.

Supongo que es en ese momento, que al archivo creado, el kernel le proporciona una entrada en la tabla de archivos del proceso, con la referencia a la tabla de archivos global y su entrada correspondiente.

> ¿por qué no existiría la entrada en la tabla global?

Con esta tengo mas dudas, porque en el issue #777 , @nicozar95 me dijo (tambien me dijo luego que el tema está en revisión) que para poder borrar un archivo, en la tabla global el campo 'open' (cant. de veces abierto) tiene que estar en 0, pero el hecho de que esté en 0, significa que el kernel eliminó la entrada de este archivo de la tabla global, debido a lo que dice el tp:

> La cantidad de procesos que se encuentran abriendo un mismo archivo será guardada en la
Tabla Global de Archivos. Cuando un archivo no se encuentre abierto por ningún proceso (es
decir, tenga el valor 0) en la tabla global, será eliminado de la misma.

Y por lo tanto, cuando al kernel le llegue la petición del cpu de borrar el archivo (con el FD), no tengo forma de obtener el path que me pide el FS para poder borrarlo.

Se me ocurren dos soluciones pero no se si están bien:

1.- Que en realidad un proceso pueda borrar un archivo cuando él sea el único que lo tiene abierto, como dice @jazcarate 

> Vas a poder borrar un archivo si sos el único que lo tiene abierto; osea que el atributo de cantidad de open en tu tabla de archivos va a estar en 1 (este programa que quiera borrar).

Con lo que todavía existiría la entrada en la tabla global de procesos, pudiendo obtener su path y enviar la petición a FS de que lo borre. Luego de esto, el contador llegaría a 0 y podría eliminar la entrada de la tabla global. Pero entiendo que eso se contradice con lo que me dijo @nicozar95 en el issue #777 

2.- Que al llegar a 0 el contador 'open' de la tabla global, el kernel no borre la entrada de esta tabla. Con lo que cuando llegue al kernel la petición de borrar el archivo, éste verifica que el contador esté en 0, obtiene el path y le pide al FS que lo elimine (y llegado este momento, si podría eliminarse la entrada en la tabla global).

Saludos!

**Comment by nicozar95** [comment]
@ivodan Fijate que actualizamos la errata, habia una contradiccion entre el parser y el enunciado

**Comment by ivodan** [comment]
Gracias!
