### ISSUE TITLE
Memoria - Eliminar pagina

### ISSUE THREAD

**Issue by dromero-7854** [sisoputnfrba/foro#748]
Acabo de leer la fe de erratas, lo siguiente con respecto al proceso memoria:
```
Liberar Página de un Proceso
  Parámetros: [Identificador del Programa] [Número de Página elegida]
  Ante un pedido de liberación de página por parte del kernel, el proceso memoria deberá liberar
  la página que corresponde con el número solicitado. En caso de que dicha página no exista
  o no pueda ser liberada, se deberá informar de la imposibilidad de realizar dicha operación
  como una excepcion de memoria.
```

Mi consulta es: En el caso que, luego de eliminar una página para un proceso, a memoria le llegue una solicitud para asignar páginas al mismo proceso: ¿debo asignarle el nro de página que liberé anteriormente?

**Comment by LeandroCarbajales** [comment]
Por qué le asignarías necesariamente el mismo?

**Comment by dromero-7854** [comment]
mmmm no lo se... me quedó la duda por el hecho que me va a quedar discontinuado los nros de páginas de un proceso 
(disculpa la demora en la respuesta)

**Comment by nicozar95** [comment]
Fijate en el #693 como lo manejarias en la Memoria logica.
En la Memoria fisica se la asignas segun la funcion de hash.

**Comment by dromero-7854** [comment]
Ok... cierro el issue a partir de la respuesta dada en[ #693](https://github.com/sisoputnfrba/foro/issues/693) 

Gracias...
