### ISSUE TITLE
HEAP - Paginas asignadas 

### ISSUE THREAD

**Issue by gvillarc91** [sisoputnfrba/foro#749]
**Escenario.**
Desde ANSISOP se requiere: alocar a 10. 
El tamaño de la pagina: 20.
Kernel utiliza "AsignarPaginasAProceso" de la interfaz memoria y le envia PID y paginas requeridas = 1,

**Dudas:**
1)Paginas requeridas SIEMPRE será 1 en el caso HEAP verdad?  Si nunca se puede pedir en una solicitud más del tamaño máximo de la página, descarto pedir algo que mas que una pagina como mucho.

2)Memoria hace lo suyo. **Cómo sabe Kernel qué número de página fue asignado?** es decir, cómo sabe la posicón asignada que necesita devolverle a la primitiva reservar memoria?

3)Por otro lado, se me ocurre que Kernel podría saber el número de esa página así:
**cantidad de paginas de codigo (lo sabe por el pcb) + STACK_SIZE + 1.**
(puse 1 porque se supone que acabo de hacer el primer pedido de la pagina).
Esto es correcto?

_(me leí todos los issues referentes al tema, si estaba mencionado, no lo terminé de entender. Por eso hago otro y me enfoco en esas 3 cuestiones)._

**Comment by gonziesc** [comment]
Agrego una pregunta de Heap: logro retornar el puntero a la dirección en donde tengo mi memoria dinámica alocada. Si me piden liberar memoria, me van a mandar este puntero, pero yo ya no tengo ningún dato asociado a este puntero, ya que este me lo devolvió memoria cuando asignó la página con la función de hash, y le sumamos el offset correspondiente por las estructuras HeapMetaData. Debería persistir los punteros que mando para poder asociarlos cuando me piden liberar memoria dinámica?

**Comment by nicozar95** [comment]
Buenas

> 1)Paginas requeridas SIEMPRE será 1 en el caso HEAP verdad? Si nunca se puede pedir en una solicitud más del tamaño máximo de la página, descarto pedir algo que mas que una pagina como mucho.

Si, nunca va a pedir alocar mas de la cantidad de bytes de una pagina

> 2)Memoria hace lo suyo. Cómo sabe Kernel qué número de página fue asignado? es decir, cómo sabe la posicón asignada que necesita devolverle a la primitiva reservar memoria?

Cuando vos asignas paginas a un proceso, este te devuelve un `t_puntero` ese puntero es el que tenes que almacenar en las variables adecuadas y lo trabajas en Memoria logica, no fisica. En la Memoria logica, las paginas se asignan contiguamente, entonces para el Kernel las paginas del proceso van a estar una al lado de la otra. Por ejemplo, si pusiste a tu codigo en la pagina 0, tu stack en la pagina 1, entonces tu heap esta en la pagina 2.

> 3)Por otro lado, se me ocurre que Kernel podría saber el número de esa página así:
> cantidad de paginas de codigo (lo sabe por el pcb) + STACK_SIZE + 1.
> (puse 1 porque se supone que acabo de hacer el primer pedido de la pagina).
> Esto es correcto?

Si, igual no le des mucha vuelta. El proceso ya te dice cuantas paginas ocupa y vos asignas la Memoria logica contiguamente, si te dijo que ocupaba 3 paginas, la nueva pagina del heap va a estar en la pagina siguiente, 4(si fuese necesario solicitar una pagina mas al heap).

>  logro retornar el puntero a la dirección en donde tengo mi memoria dinámica alocada. Si me piden liberar memoria, me van a mandar este puntero, pero yo ya no tengo ningún dato asociado a este puntero, ya que este me lo devolvió memoria cuando asignó la página con la función de hash, y le sumamos el offset correspondiente por las estructuras HeapMetaData. Debería persistir los punteros que mando para poder asociarlos cuando me piden liberar memoria dinámica?

No deberias porque tener datos a un puntero real fisico. Osea, si tu funcion de hash lo asigno en el frame 349234292. A el Kernel le importa poco y nada porque para el, el Heap esta en la pagina 4 del proceso X.

Abrazos!

**Comment by gonziesc** [comment]
Clarisimo, gracias!

**Comment by gvillarc91** [comment]
Gracias, clarisimo! Cierro issue.
