### ISSUE TITLE
Consola - Atender programas

### ISSUE THREAD

**Issue by Emi0689** [sisoputnfrba/foro#750]
Buen día.

Tenemos una duda con mi grupo. Nosotros en este momento gestionamos las entradas de programas con un hilo general y un select en el kernel el cual gestiona las multiples consolas. Al releer el enunciado nos encontramos con que la consola debe tener un hilo por cada programa creado. Quisieramos saber si es necesario cambiar nuestra arquitectura, entendiendo que al tener las peticiones del kernel de manera secuencial por programa, no se aprovecharía el multihilo.

En caso de ser necesario rediseñar la arquitectura e implementar multihilo en la consola, como haríamos para distinguir los datos que envía el kernel a la consola?

Muchas gracias por su tiempo!
Saludos!!

**Comment by nicozar95** [comment]
Buenas
En un principio cada programa ansisop de la Consola corre en hilos distintos, y tal vez deberias cambiar eso. Para que la consola sea multihilos y se comunique con el Kernel, tenes 2 maneras de hacerlo, puede haber mas estas son las que se me ocurren a mi:

- La facil y la que usan los chicos: Un socket por hilo, es la mas facil de implementar y no tiene mucha vuelta. Hay mil y un razones de porque no recomendar, pero no esta mal si la implementaron.

- La grosa y la que usan los machos pecho peludos: Hacer un hilo que se encarge de manejar los paquetes por socket y varios hilos por programa ansisop que esten sincronizados con el _hilo socket_. Si sincronizas bien los hilos en la consola, te queda un lujo, osea cuando el _hilo socket_ recibe algo del Kernel, este levanta un signal para que los demas hilos se fijen si el paquete les pertenece. 
Es un cacho mas jodido que hacer pero lo bueno es que solo tenes una sola via de comunicacion con el Kernel.

Saludos

**Comment by Emi0689** [comment]
Barbaro, gracias por la respuesta!!
PD: no se que tan muchos estamos a 20 días de la entrega, pero la hablamos en equipo y a ver si entre todos juntamos los pelos en le pecho suficientes XD

**Comment by sebastian-gulino** [comment]
Buenas! Vuelvo a abrir este issue con una consulta respecto al comentario de @nicozar95 , si seguimos la segunda opción la arquitectura sería un poco distinta a la mencionada en el enunciado no?

Según el enunciado tenemos:
- Hilo UI: Por medio del cual el usuario solicitará el inicio de programas, desconectar consola, limpiar mensajes, etc.

- Hilo programa: Uno por cada programa que se solicite ejecutar

Si seguimos esta solución tendríamos:
- Hilo UI
- Hilo programa.
- Hilo comunicación: Se me ocurre que para implementarlo podría tener dos posibilidades:

A) Manejará **todos** los mensajes entre consola/kernel, utilizando para esto una cola de mensajes a enviar (la cual será alimentada por los hilos programa) y el hilo debería estar iterando constantemente hasta que:
1) Haya mensajes a enviar en la cola
2) Haya mensajes para recibir del kernel.
En este último caso debería recibir el PID dentro del mensaje, con él conseguir el thread id del hilo que lo esta ejecutando e informarle el mensaje (entiendo que mediante el uso de señales).

B) Iterará indefinidamente escuchando los mensajes del kernel, realizará las impresiones por pantalla, e informará al thread correspondiente al PID que mandó el mensaje para que haga la acción correspondiente.
El envío de mensajes lo realizará cada hilo programa sin tener que pasar por el hilo comunicación.

Entiendo que la problematica es que no podemos tener a todos los hilos programa iterando para recibir mensajes del socket correspondiente al kernel, no solo por el tema de la sincronización, sino porque al recibir un mensaje en 1 hilo programa para verificar si le corresponde, ya no lo tendríamos en los demás.

Es recomendable ir por alguna de estas dos alternativas? O la estoy errando feo y hay algo mucho más facil que pueda hacerse?
