### ISSUE TITLE
Memoria - Funcionalidades

### ISSUE THREAD

**Issue by Emi0689** [sisoputnfrba/foro#751]
Buenas tardes

Tenemos una duda sobre las limitaciones del proceso memoria. En este momento tenemos una conexion de variables CPU-Memoria. O sea, cada vez que se necesita pedir memoria desde una variable el cpu llama a memoria desde la funcion definirVariable. 

Quisieramos saber si es correcto o si en realidad el kernel debe realizar esta gestión?
O sea que si en realidad gestión del heap y el stack tiene q estar del lado del kernel?

Muchas gracias!!
Saludos!

**Comment by nicozar95** [comment]
La gestion del heap queda en el Kernel.
La gestion del Stack, queda en la CPU.
Saludos

**Comment by Emi0689** [comment]
Muchas gracias!!!
