### ISSUE TITLE
Consulta heap

### ISSUE THREAD

**Issue by mauricio-figueroa** [sisoputnfrba/foro#752]
Buenas Tardes!

En el caso de recibir un pedido de memoria dinámica de 18 bytes, y solo tener un bloque de 20 bytes libres en la pagina de heap, podemos tomar dos caminos:

1-> Forzar a que ante un pedido se tenga lugar para dos estructuras de metada(en el cual en este caso, pediríamos una nueva pagina)

2-> Utilizar el bloque completo sabiendo que solo podemos disponer de 18 bytes(esto generaría un desperdicio de 2 bytes)

Esta es una decisión nuestra? (el tp no aclara esta situación).

Gracias, saludos!

**Comment by nicozar95** [comment]
Buenas
¿Con los 20 bytes del bloque libre te referis descontando la metadata?
Si ese es el caso, lo almacenas en el bloque de 20 bytes.
¿Genera una fragmentacion? Si, pero no puedo hacer nada frente a eso.
