### ISSUE TITLE
Heap - Contenido del DATA

### ISSUE THREAD

**Issue by gvillarc91** [sisoputnfrba/foro#753]
Está vinculado al issue: #645.

Tengo una duda conceptual. la sección  "Data" de la estructura administrativa del Kernel del Heap, que contenido tiene?
Entiendo que una vez alocado cierto espacio, se crea la estructura metada y data. Metadata tiene como contenido la información de lo que sigue, dónde comienza el primer byte de la data y dónde termina el ultimo, es decir, me dicen el espacio que tengo en memoria para ese bloque de la página.

Pero la data que contenido tiene? me refiero a *data. La duda nace de que, al crear la estructura, no se qué ponerle, y no entiendo si alguna vez tendrá algo o simplemente son espacios reservados para llevar un control de lo que se fue alocando.

espacio seria el espacio requerido para alocar en un script ansisop: alocar a 50.
t_bloqueHeap* nuevoBloque = malloc(sizeof(t_bloqueHeap));
nuevoBloque->metadata = metadata;
**nuevoBloque->data = malloc(sizeof(espacio));**

Gracias.

**Comment by nicozar95** [comment]
Buenas
En un principio en ese espacio del heap no vas a escribir nada, despues cuando te manden a escribir en heap, vas a ir escribiendo esos bloques.
Fijate en el #742 que tenes un ejemplo de como ir escribiendo en el heap.
Saludos

**Comment by gvillarc91** [comment]
Pero el heap no es mas que una representacion de direcciones logicas que necesita la memoria para traducir a memoria fisica? Cuando haya una aginación, obtendré el puntero de comienzo del data y su desplazamiento y termino pasandole a memoria una dirección. En que momento el kernel recibe ralmente un valor que vaya a guardar en ese data?

*data = unValor.

Digamos, esto nunca ocurre, simplemente necesito saber donde comienza y donde termina ese espacio que reserve en memoria para heap.

No entiendo para que conservar un "Data" en la estructura, si me bastaria con los metadata para determinar el esquema de la memoria.

**Comment by nicozar95** [comment]
No entendi del todo la consulta:

> Pero el heap no es mas que una representacion de direcciones logicas que necesita la memoria para traducir a memoria fisica?

No. El heap es un espacio de tu programa que vos utilizas para ir pidiendo memoria muy similar a un malloc en C , la traduccion de direcciones logicas a fisicas solo ocurre cuando vas a escribir/leer algo en Memoria, osea cuando "hablas" con el proceso Memoria. 

En este caso vos lo estarias manejando como un segmento de memoria logica, osea, si mi codigo esta en la pagina 0 y 1, mi stack en la pagina 2 y mi heap en la pagina 3. Vaya a saber en que frame esta, para eso esta la funcion de hash.

> Cuando haya una aginación, obtendré el puntero de comienzo del data y su desplazamiento y termino pasandole a memoria una dirección.

El valor que te devuelve debe ser el puntero despues de la metadata para no ir pisandola.
Lo que puede ser un poco dificil de ver es que la asignacion de valores en el heap es de a 4 bytes, por que asi es el parser ansisop, por eso puede ser complicado almacenar valores como enteros, fijate en el ejemplo en #737, para escribir un "Hola!" en un archivo.

No se si te referias a esto, cualquier cosa avisanos

**Comment by gvillarc91** [comment]
A ver si es más claro preguntandolo de esta forma:

Tengo la siguiente estructura de Heap en Kernel:
una lista de Pids. Cada elemento pid tiene una lista de paginas. cada elemento pagina tiene una lista de METADATAS. 
Ese metadata (tal cual definido en enunciado) me basta para definir mi esquema de direcciones.
ejemplo:

1: (usado, 200)
2: (usado,35)
3:(usado, 157)
4:(libre, 100)

Cuando creo un nuevo "bloque/metadata" en una pagina que ya tengo, yo puedo devolver:
"che, tu direccion en heap es: cantidadPaginasCodigo + stack_size + NroPagina * (sizeDelMetadata - 5)"

Este esquema, entiendo, me deja moverme por la paginación. Pero en ningun momento yo guardo valores acá. Supongo que no terminé de entender algo más conceptual, pero en primer lugar quiero saber si ese esquema es correcto.

**Comment by nicozar95** [comment]
Cuando te manden a ejecutar algo como:
`*b = 18543`
Suponiendo que b es va a tener el valor de la pocision de memoria de alocar. Vas a llamar a dereferenciar (*) y ahi es donde obtenes el valor de tus bloques "Data" y reemplazas con lo que corresponda.

La joda de la seccion del heap es que yo me pueda mover el puntero del mismo haciendo algo como:
`b = b+4`
Ahi es donde yo me corro 4 bytes en mi segmento "Data"

**Comment by tferraro** [comment]
@gvillarc91 como venis con esto? Te sirvió la respuesta de nico? Si es así, se puede cerrar el issue? Gracias!

**Comment by gustofa** [comment]
Hola. Leí esto ahora y se relaciona con una duda que se nos presentó.

> Cuando te manden a ejecutar algo como:
>   asterisco b = 18543    (al quotear no muestra el caracter asterisco)
> Suponiendo que b es va a tener el valor de la pocision de memoria de alocar. Vas a llamar a dereferenciar > (*) y ahi es donde obtenes el valor de tus bloques "Data" y reemplazas con lo que corresponda.

Siguiendo el razonamiento, cuando cpu lea esa instrucción (*b = 18543) que escribe un valor en una posición de memoria que corresponde a Heap, el parser llama a **asignar**, pero según entendimos por varios issues, **cpu no debe escribir en el heap** porque eso es potestad de kernel. Entonces al llamar a este asignar, cpu debería comunicarse con kernel para indicarle la escritura?  
   
Al no haber una syscall en ansisop como si están reservar y liberar, y toda escritura en una posición de memoria caer en asignar, como controlar cuando escribir directo en memoria y cuando pasar por kernel...
That is the question!

**Comment by gvillarc91** [comment]
Tengo entendido que  lo que no es potestad del CPU es pedir por si mismo la memoria al proceso memoria, pero si puede escribir el heap y entiendo que las direcciones (punteros) a esas posiciones las tiene en el stack luego de que kernel le devolvio el resultado de la "reserva" de memoria. No es asi?

**Comment by tferraro** [comment]
@gvillarc91 viene bien por donde aborda el tema que preguntas @gustofa . Va a ser la CPU quien escriba finalmente en memoria, pero para saber si la operación está bien encaminada o está embarrando la cancha, podría llegar a haber cierta comunicación con el kernel.

En Lo que si te estás equivocando, es que el campo data _no está en el kernel_. El campo data es el valor que tiene tu espacio de memoria dinámica. Lo único que tiene el kernel es una tabla con que tiene asignado a cada uno, nada más. Fijate que el enunciado plantea: `Para mantener la gestión de páginas utilizadas para Heap, el Kernel mantendrá una tabla, asociada al PCB que cuente con el PID del proceso, el número de página y el tamaño disponible dentro de la misma`

Cualquier cosa chiflen!

**Comment by gustofa** [comment]
mmmm... no se si te entiendo bien.
Yo no hice referencia a si el campo data estaba o no en kernel, pero según ese extracto del enunciado, lo que guarda esa tabla es el espacio libre que queda en cada página de heap del proceso, no las ubicaciones de los espacios utilizados, por ejemplo. 
No se a que apuntabas con "_saber si la operación está bien encaminada o está embarrando la cancha_",
pero la única validación que podría hacer kernel sobre esto es que esa dirección que se va a escribir pertenece a heap o no. Esto termina pareciendo un poco insulso, si cpu va a escribir tanto en stack como en heap, para que ir a pedir la venia de kernel en un caso? 
Y peor aún, cpu no podría saber en que caso ir a kernel a preguntar y en que caso no (porque no sabe de segmentos de codigo-stack-heap, para él son punteros a memoria), por lo que habría que ir siempre, en un caso kernel diría "es heap, te dejo escribir" y en el otro diría "no es heap, pero escribí igual porque es stack y no hacía falta que me preguntes".     o_O

En definitiva, casi que cpu en asignar escribe directo a memoria sea stack o heap, no?
Nosotros había bloqueado la opción de escribir en heap dando un error de memoria y abortando la ejecución de ese programa, pero cuando nos topamos con el *b=123456 se nos llenó un lugar de preguntas...

**Comment by gvillarc91** [comment]
@gustofa puedo aportar lo siguiente: cuando te piden alocar desde ansisop, se ejecuta "reservar" que le manda a Kernel el esapacio necesario. Kernel realiza su trabajo y le devuelve una posción (al estilo: acá tenés memoria, no me jodás más"). Esa posición valiosa la guarda en el stack y siempre que se refiera a "a", se usará esa posición sin distinguir entre heap y stack, porque basicamente, asignar es polimorfico: recibe posiciones a dónde asignar y le da al proceso memoria esa posición.

Corrijanme si está mal, sirve de paso para verificar si estoy en lo correcto.

**Comment by tferraro** [comment]
A lo ultimo del campo data venia por el lado de la pregunta otra pregunta.

Pasa lo siguiente, podrías llegar a querer preguntarle al kernel si hay o no heap, dependerá de como implementen en TP, de ahí el _podría_. Podés directamente comerte un error por acceder a memoria que no es tuya (-5).

Volviendo a tu pregunta, la cpu *si* tiene que poder escribir en el heap. Es un tema conceptual. La memoria, es memoria, para la CPU no debería haber mucha distinción entre una y otra, dado que _asignar_ escribe el valor dado en la posición de memoria dada.

**Comment by gustofa** [comment]
@gvillarc91 
> Corrijanme si está mal, sirve de paso para verificar si estoy en lo correcto.

Para mi está perfecto lo que decís, nosotros lo interpretamos y modelizamos siguiendo esa lógica también.

@tferraro 
>  la cpu si tiene que poder escribir en el heap
Esta era la confirmación que me estaba faltando, y que era lo más lógico. Hubo afirmaciones de lo contrario en algún issue pasado que nos nubló un poco esto y no nos terminaba de cerrar.

Gracias por la aclaración.

Por mi se puede cerrar el issue, no se que opina @gvillarc91

**Comment by gvillarc91** [comment]
Dale, lo cierro nomás!! Gracias.
