### ISSUE TITLE
Crear directorios

### ISSUE THREAD

**Issue by CarolinaPonceRodriguez** [sisoputnfrba/foro#754]
Hola que tal, me acaba de surgir una duda con lo siguiente:
En el tp dan como ejemplo que los archivos se encuentran en el siguiente path [Punto_Montaje]/Archivos/[PathDelArchivo]
Dentro de Archivos yo podria tener como PathDelArchivo a /directorio/hola.bin
Si a mi me pasar abrir ese archivo hola.bin en modo creacion, tendria que ser capaz de crear dicho archivo dentro del directorio especificado, pero el la especificacion del tp no se contempla la creacion de directorios, es decir, yo tendria que crear la carpeta directorio y dentro el archivo.bin para que sea consistente con lo solicitado.

Debo crear "la carpeta" directorio? O simplemente como no se puede ampliar la funcionalidad rechazar dicha peticion? Saludos.

**Comment by nicozar95** [comment]
Si deberias crear _la carpeta_ del archivo, porque es parte del path del mismo.
Saludos

**Comment by CarolinaPonceRodriguez** [comment]
Gracias, cierro!

**Comment by nicozar95** [comment]
Surgio un asunto que lo estamos discutiendo en #765
