### ISSUE TITLE
mmap / Escritura Fs

### ISSUE THREAD

**Issue by Emi0689** [sisoputnfrba/foro#755]
Buenas noches,

Acá estoy con una dificultad mas de C que otra cosa. Logro utilizar el mmap para leer, pero no para grabar. El codigo que tengo sería este:

  		  FILE * pFile;
   		  pFile = fopen (pathAbsoluto,"w+"); //esto para crearlo no se si hay una mejor manera
		  fputs(" ", pFile);
		  fseek(pFile, string_length(""), 0); //si no le meto un vacio, al mapearlo no lo encuentra..
                  fclose(pFile);

		  char* bloques = string_new();
		  string_append(&bloques , "prueba");

		int archNuevoMap = open(pathAbsoluto, O_RDWR);
		struct stat scriptMap;
		fstat(archNuevoMap, &scriptMap);
		int aux =string_length(bloques);
		char* archMap = mmap(0,scriptMap.st_size, PROT_WRITE, MAP_SHARED, archNuevoMap, 0);

		memcpy(archMap,bloques,aux);
	        munmap(archMap,aux);
		close(archNuevoMap);

Esto me graba solo "p" en el archivo, un solo caracter.. probe ya de todo... ponerle void* al archivo.. cambiarle los size... el tipo de apertura..

Espero que puedan ayudarme.
Muchas gracias por su tiempo!!
Saludos!!

**Comment by nicozar95** [comment]
¿Probaste `msync`? Generalmente cuando escribis en una region mapeada a memoria con `mmap` tenes que sincronizarlo al archivo con `msync`, se que eventualmente se sincroniza pero no tengo ni idea cuando lo hace, con esto vos lo _forzarias_ a que escriba en el archivo.

**Comment by Emi0689** [comment]
Hola. Si probé con eso tambien.. huele a que es un problema de punteros.. porque sincroniza y graba "p". Como que graba el primer char y no un puntero a char.. 

me esta volviendo loco..

**Comment by nicozar95** [comment]
En un principio tengo entendido que no, `mmap` solo trae el archivo a paginas en memoria.

Si quieren leer bloques, `mmap` es su amigo porque pueden mapear cada uno de los archivos de los bloques y concatenarlos para tener el archivo posta.
Si quieren escribir bloques, ahi depende si vas a aumentar el tamaño de tu archivo original vas a tener que hacer algo medio turbio. Si vas a mantener el tamaño original, `mmap` es tu amigo.

Ahora bien con tu consulta, yo no lo veo mal que grabes \0 en el archivo siempre y cuando se respete el tamaño de los bloques, es una buena estrategia pero puede ser un poco pesado a la hora de ir escribiendo todos con espacios vacios. Tal vez truncando el tamaño del archivo tanto como el tamaño del bloque sea mejor, pero no estoy 100% seguro. Son 2 estrategias a plantear y son libres para elegir

**Comment by Emi0689** [comment]
Perfecto!! Pienso tranquilo cual sería mejor la estrategia. 
Te agradezco mucho la respuesta!!
