### ISSUE TITLE
Sobre la tabla de archivos del Proceso

### ISSUE THREAD

**Issue by gustofa** [sisoputnfrba/foro#756]
Hola.
Partiendo de que la tabla de archivos del proceso se encuentra en el PCB, y considerando los últimos cambios en el parser mencionados al final del issue #741
Al momento de ejecutar la instrucción "abrir" le llegará la syscall a kernel, y éste deberá abrir el archivo, lo agregará a la tabla global si no estaba y demás. Pero es kernel quien agrega el nuevo registro a la tabla de archivos del proceso?
Dado que la tabla está en el PCB, el agregado lo hace al momento del fin de la instrucción cuando cPU le devuelve el PCB a kernel?

**Comment by nicozar95** [comment]
Si lo asigna el Kernel, el FD al archivo queda asociado a la entrada de la tabla de archivos (reservandote el numero 0,1 y 2) del proceso. Pero aca tenes un tema. La tabla de archivos por proceso esta en el Kernel, no en el PCB. Osea el Kernel va a tener una tabla por cada uno de los procesos que maneje

**Comment by gustofa** [comment]
Ok.
Gracias!
