### ISSUE TITLE
Alojamiento variables compartidas

### ISSUE THREAD

**Issue by maurocostabella** [sisoputnfrba/foro#757]
Hola, queria saber a donde almaceno las varibales compartidas. Cuando inicio el kernel, lee su configuacion e inicializa las variables compartidas en 0. Ahora...

1)Son variables del proceso (codigo de C) o le tengo que solicitar a memoria espacio para guardar las variables compartidas?

si la respuesta a 1 es si, entonces supongo que tambien tengo que guardar los valores de los semaforos... entonces, 
2)cuando le pido espacio a memoria? cuando hago el handshake? 
3) le pido n paginas para almacenar todas las variables compartidas y los semaforos  o lo guardo con las estrcturas administrativas? 
4) que pid uso (porque serian globales)? -1?

gracias!

**Comment by jazcarate** [comment]
Es complicado responder `si` o `no` a una respuesta que pregunta entre dos cosas; así que incluyamos `<stdbool.h>` donde
_Opción `0`_:
> Son variables del proceso 

_Opcion `1`_:
> le tengo que solicitar a memoria espacio

a lo que te respondo: `true`.
2) Nunca, cuando lees la configuración del Kernel reservas el espacio pertinente dentro del Kernel.
3) _ver 2_
4) _ver 2_

😸

**Comment by maurocostabella** [comment]
gracias!
