### ISSUE TITLE
Consola del kernel

### ISSUE THREAD

**Issue by fededri** [sisoputnfrba/foro#758]
Tengo un par de dudas con respecto al funcionamiento de la consola del kernel

1)El comando que pide mostrar el listado de procesos por estados, que informacion del proceso deberia dar? alcanza con PID y estado?

2)Detener la planificacion: el enunciado no lo pide, por lo que entiendo que no es necesario implementarlo pero por las dudas lo consulto... luego de detener la planificacion de procesos es posible que se reanude?
Pregunto porque si detengo la planificacion de procesos tendria que ignorar los mensajes entrantes de las cpus, por lo que las mismas van a quedarse colgadas y los mensajes se irian perdiendo.

3)Si el grado de multiprogramacion esta en 2, y tengo un proceso esperando en la cola de NEW, si cambio el grado de multiprogramacion a 3 deberia entrar instantameante el proceso New a la cola de Ready?

**Comment by nicozar95** [comment]
1) Si. Igual deberias hacer un comando para mostrar todos los procesos y otros para mostrar los procesos por estado (o el mismo con distintos flags).

2)Depende como pauses el sistema, la joda es que no haya cambios de estado de proceso. Podrias hacer que se siga ejecutando el programa lo mas bien pero a la hora de realizar un cambio de proceso que el Kernel le dija "banca que estoy en pausa" y se quede la CPU bloqueada en un _recv_.

3)En un principio si ¿Como lo habias pensado vos?
