### ISSUE TITLE
Archivos de metadata (File System)

### ISSUE THREAD

**Issue by JuanCrespo18** [sisoputnfrba/foro#759]
Tengo una duda respecto al archivo donde se encuentra la metadata del FS y también a los archivos que van a contener la metadata de cada archivo en general (dígase el tamaño de los datos y los bloques donde están contenidos). Estos se deberían leer como archivos binarios, es decir, con fread, fseek, etc? O se pueden/deben leer como si fueran archivos de configuración? Tengo la duda porque en el enunciado los datos ejemplo aparecen como si fuera un archivo de configuración (me refiero a que tienen clave-valor) pero a la vez en la ruta de dichos archivos ejemplo, la extensión es .bin, o sea serían archivos binarios. Al principio asumí que ésta última opción era la correcta pero luego me di cuenta que cada dato lo leía en un específico orden y si este varía ya me rompe todo, y ni hablar considerando que el archivo de metadata del fs lo va a proveer la cátedra al momento de la evaluación.

**Comment by nicozar95** [comment]
Buenas
Levantalo como un archivo de configuracion, es mas, ahora hay una [nueva version](https://github.com/sisoputnfrba/so-commons-library/releases) de las commons que te permite escribir archivos de configuracion para que sea mas facil cambiarle el tamaño a los archivos, crear archivos nuevos, etc en el FS SADICA

**Comment by fedebonisconti** [comment]
Buenas,

Acordate que "leer algo como x", es simplemente darle un formato de x a los bytes.

El ejemplo más fácil sería:
```c
char letra = 'a'
printf("%c,  %d\n", letra, letra);
```

Esto imprimiría 'a' y 97. Por qué? Porque estamos poniendo diferentes representaciones de lo mismo, que en el fondo, son bytes.

Algo muy parecido pasa con tus archivos! Podés abrir un .mp3 como texto, y editarlo. Así como podrías leer un .bin como si fuese un config :)

Saludos!

**Comment by JuanCrespo18** [comment]
Buenisimo, gracias!
