### ISSUE TITLE
Bitmap.bin

### ISSUE THREAD

**Issue by Emi0689** [sisoputnfrba/foro#760]
Buenas!
Quisiera hacerles una consulta. Tengo entendido que en este archivo (Bitmap.bin) tengo que mantenerlo actualizado al el estado del bitarray creado con las commons. 
El tema es que no entiendo cual campo tengo que grabar en este archivo. Entiendo que deben ser ceros y unos que reprensentan si los bloques estan ocupados o no, pero el bitarray que tengo veo:

	typedef struct {
		char *bitarray; // tiene un valor que no entiendo como interpretar de tipo "\002"
		size_t size; // un int con la cantidad de archivos de bloques creados ej: 30
		bit_numbering_t mode; // el tipo de modo...
	} t_bitarray;

Debería grabiar el char* bitarray?

Muchas gracias por su tiempo!!
Saludos!!

**Comment by mezeitune** [comment]
Hola , en el archivo Bitmap que vos vas a tener especificamente no vas a ver 1s y 0s , ya que lo que vos vas a ver son caracteres (bytes) que representan 8 bits , esos van a ser 1s y 0s osea que no van a estar a tu vista , como podes manejar esto? , pasando tu bitmap.bin a una variable mmap que lo que hace es mapearte todo tu bitmap a memoria , esto mucho no te importa es solo un procedimiento , pero esto es lo que te va a permitir tener el bitmap en el bitarray para manejarlo como vos quieras.

```
inicializarMmap():

	bitarray = bitarray_create_with_mode(mmapBitmap,sizeBitMap, MSB_FIRST);

	printf("El tamano del bitarray es de : %d\n\n\n",bitarray_get_max_bit(bitarray));
```
En el inicializarMmap harias todas las operaciones correspondientes para inicializarlo , y lo pondrias en una variable global , al menos asi lo hice yo , y despues con bitarray ya tenes todo para manejarlo.
Usando bitarray_set_bit , o clean lo que sea

Saludos

**Comment by Emi0689** [comment]
Hola! Gracias por tu pronta respuesta. Por lo que veo sos alumno.

Entendí. Te comento una cosa en agradecimiento, y de paso por si alguien mas lo lee. Ayer discutía esto en este issue (#755) .  

El mmap tiene un problema que es que trae dificultades cuando queres aumentar el tamaño del archivo que estas mapeando. O sea, si en el archivo tenes 20 caracteres, lo mapeas y queres grabar un char* de 24 caracteres, solo te va a guardar 20. Esto con cualquier archivo en general. Y el archivo que bitmap.bin que creas (imagino con fopen), lo trae vacío! 

Esto me pasó cuando estaba mapeando los bloques. Una solución que pensé, fue insertar primeramente vacios, como tantos necesite para luego ser reemplazados por el contenido original. Y el ayudante me dijo que no estaba mal la idea.

Espero te sea util.

Saludos!!

**Comment by mezeitune** [comment]
Pero el mmap hace falta que se extienda? por que justamente en el archivo Metadata.bin te dice la cantidad de bloques que vas a tener , y por lo que tengo entendido eso no va a cambiar por lo menos a lo largo de la ejecución del sistema , por lo tanto el size tanto del mmap como del bitarray debería ser siempre el mismo.
Decime si me equivoco.

**Comment by Emi0689** [comment]
Cuando vos haces en el ansisop "escribir", estas agregando caracteres. No en el archivo real creado necesariamente (ya que este solo tiene tamaño y bloques), sino en los 1.bin, 2.bin, etc. Estos nacen vacios. Entonces al mapearlos traen problemas. 
Vos cada vez que escrbis agregas caracteres en cada uno de estos "numeritos".bin y ahí tenes el problema con el mmap.

**Comment by mezeitune** [comment]
Claro si , ahí te entendí mejor , pensé que te referías al bitmap.

**Comment by Emi0689** [comment]
Es que el bitmap.bin (acá donde no estoy 100% seguro) va a funcionar igual. Vos cuando lo creas aparece vacio. Si lo mapeas debería darte error, a menos que justo le asignes algo con algo del tipo fputs. Pero debería no dejarte agregar mas bloques (de la manera que sea que lo esta agregando en el archivo) de los que ya tiene porque aumentarías su tamaño/escritura y eso el mmap no lo mapea...

**Comment by fedebonisconti** [comment]
Buenas,

No. El bitmap no va a estar vacío. El bitmap lo que va a contener es los _n bits_, cada uno representando un bloque dentro de tu FS. Tu FS tiene un tamaño predeterminado (en este caso, n bloques), y no lo vas a poder extender a más de n, ni reducir (porque es justamente parte del formato del FS, sino habría que formatearlo).

Como dijo @mezeitune, podés manejarlo con _mmap_. Para no tener que andar cambiando de tamaños usando _mmap_, cuando creas el archivo, lo podes crear del tamaño total del FS.

Saludos!

**Comment by Emi0689** [comment]
Buenas!
Gracias por tu respuesta y aclaración!

Pero entonces tengo una duda, existe alguna funcion que cree un archivo de tamaño determinado? La unica que conozco es fopen pero (independientemente del flag) que lo crea vacio.

Muchas gracias por tu tiempo!

**Comment by fedebonisconti** [comment]
Podés usar la función [dd](https://linux.die.net/man/1/dd) para eso!

**Comment by Emi0689** [comment]
ahh! no la tenía esa! Muchas gracias!!
