### ISSUE TITLE
Comunicación en consola multithread

### ISSUE THREAD

**Issue by sebastian-gulino** [sisoputnfrba/foro#761]
Buenas! Abro este issue con una consulta respecto al comentario de @nicozar95 en el issue  [https://github.com/sisoputnfrba/foro/issues/750]() si seguimos la segunda opción la arquitectura sería un poco distinta a la mencionada en el enunciado no?

Según el enunciado tenemos:

Hilo UI: Por medio del cual el usuario solicitará el inicio de programas, desconectar consola, limpiar mensajes, etc.

Hilo programa: Uno por cada programa que se solicite ejecutar

Si seguimos esta solución tendríamos:

Hilo UI
Hilo programa.
Hilo comunicación: Se me ocurre que para implementarlo podría tener dos posibilidades:
A) Manejará todos los mensajes entre consola/kernel, utilizando para esto una cola de mensajes a enviar (la cual será alimentada por los hilos programa) y el hilo debería estar iterando constantemente hasta que:

Haya mensajes a enviar en la cola
Haya mensajes para recibir del kernel.
En este último caso debería recibir el PID dentro del mensaje, con él conseguir el thread id del hilo que lo esta ejecutando e informarle el mensaje (entiendo que mediante el uso de señales).
B) Iterará indefinidamente escuchando los mensajes del kernel, realizará las impresiones por pantalla, e informará al thread correspondiente al PID que mandó el mensaje para que haga la acción correspondiente.
El envío de mensajes lo realizará cada hilo programa sin tener que pasar por el hilo comunicación.

Entiendo que la problematica es que no podemos tener a todos los hilos programa iterando para recibir mensajes del socket correspondiente al kernel, no solo por el tema de la sincronización, sino porque al recibir un mensaje en 1 hilo programa para verificar si le corresponde, ya no lo tendríamos en los demás.

Es recomendable ir por alguna de estas dos alternativas? O la estoy errando feo y hay algo mucho más facil que pueda hacerse?

**Comment by nicozar95** [comment]
No somos una materia de programación, les hacemos programar.
Lo importante de la consola es que halla un hilo por cada programa ansisop, luego se pueden tomar algunas libertades tecnicas que hacen que su tp sea suyo. Osea que hace unico a cada tp :dancer: .

 **Esto es mas una decision de diseño mas que del TP**
Si lo hicieron con un hilo por socket esta bien. 
Si lo hicieron de mi manera, esta bien.
¿Puede haber otras maneras? Seguro, a mi solo se me ocurrieron 2 y a vos se te ocurrieron 2 implementacion a usar, ninguna de las 2 implementaciones esta mal todas tienen sus pro y con, sin embargo **evitaria la que te genera una espera activa, ya que en la materia ven formas de atacar eso**. Cualquiera de las alternativas que eligas es lo que hace unico a tu TP :smile:
Siempre y cuando tengan un hilo por programa ansisop, esta decision de diseño es 100% suya.

La que yo habia pensado era que este _hilo comunicacion_ se quede bloqueado en el recv del socket.
El resto de los hilos ansisop se quedan bloqueados en un wait.
Cuando llega un mensaje, llega el PID el cual lo tengo asociado a un hilo, el _hilo comunicacion_ levanta un signal, los demas hilos van a ver si el paquete es suyo. Si es genial y hago lo que tengo que hacer. Si no, vuelvo al wait.

**Comment by calvoluciano** [comment]
Nico,

Leyendo este incidente estoy con la misma cuestión la bendita consola multihilos, cual seria la mejor forma de mantener la referencia del hilo que recibe mensajes del kernel con los hilos programas, en mi caso cada hilo manda un script al kernel y este le devuelve el numero de PID asignado, ahora si yo mando 2 script de una forma super rapida en mi hilo recv, como se a que hilo programa asignarle el PID?

**Comment by nicozar95** [comment]
Luciano,

Si lo haces de mi manera, vas a tener que encontrar una forma de sincronizar cada PID con un hilo, podrias tener una cola de mensajes cuando se pregunta por un PID, para ir asignandoles a cada uno se me ocurre a mi.

Si vos ya lo hiciste con un proceso por hilo, a esta altura del partido no lo cambies que te vas a hacer mas problemas implementando la alternativa. No esta mal hacerlo de esa manera.

**Comment by sebastian-gulino** [comment]
Como siempre, muchas gracias por el tiempo invertido en las respuestas nico, la verdad que quería encararlo por el lado de tener 1 solo socket abierto en el proceso consola y que todos los hilos lo reutilicen, pero tendríamos para eso que armar una estructura como te mencionaba de colas de mensajes y sincronización que nos va a complicar mucho la solución (más considerando todo lo que nos falta hacer aún). 
Nos resignamos a no ser _machos pecho peludos_ y vamos por la solución de 1 socket por cada hilo programa (asumiendo todo lo que tenemos que cerrar al matar una consola).

**Comment by cthaeh** [comment]
Buenas noches Nico,

Estoy teniendo problemas con este tma también, pero lo mio es otra cosa. 

Ya logramos crear un hilo por programa, cada hilo sabe el PID del programa que esta administrando, y no tengo espera activa. 

En mi implementación hice (no se si es correcto) un signal(SIGUSR2, manejador_señal) dentro de cada hilo. Y en el hilo que hace los recv del kernel esta el raise(SIGUSR2).

Esto funciona perfecto si corro un programa tras otro, pero si quiero correr 2 programas juntos en la misma consola, ya no funciona.
Lo que me esta ocurriendo es que únicamente el último hilo que se creo ( y por lo tanto, el último hilo que hizo el signal(SIGUSR2, manejador_señal) ) es el que entra a la funcion manejador_señal, el resto no lo hace. 

Nose si es error mio de código o si es algo que me esta faltando considerar.
Saludos,

**Comment by nicozar95** [comment]
Yo tenia pensado que lo sincronizen con semaforos no con señales, igual no esta mal tu implementacion. Fijate de ir debuggeando haber que onda.

Igual repito lo que puse arriba, ustedes deciden sobre como atacar ciertos problemas del TP y son libres de elegir como resolver esa problematica, en sw no son todos blancos o negros todo depende.
Mi implementacion tiene sus pro y sus contras como tambien la tienen el resto de las implementaciones, programar bien es elegir la mejor para su TP y su grupo. Esto por lo general suele ser la implementacion mas facil y practica.
