### ISSUE TITLE
Cambios Ansisop

### ISSUE THREAD

**Issue by Emi0689** [sisoputnfrba/foro#762]
Buenas. Necesitaba abrir este issue a fin de encapsular bien los cambios que aun hacen falta en el ansisop (si es que los hay). Varios se discutieron en estos issues (#741 y #737). Pero sinceramente no estoy del todo seguro bien que esta y que falta, así que encapusulo en preguntas.

1) Tengo entendido que el abrir ya guarda su fd en una variable, pero aun esas variables no pueden ser usadas por leer y escribir ya que estas siguen esperando un valor verdad?

2) La funcion escribir ya esta completa? Tengo entendido que se graba a partir de numeros pero aun no estoy seguro si ya graba de a un char o un bytes. Esto se discutió en lo issues de arriba.

3) Y si es posible, sería de mucha ayuda un ejemplo de como deberían estar las funciones leer y escribir, como pusieron en los casos de pruebas donde estaban los facil.ansisop, completo.ansisop, etc.

Muchas gracias por su tiempo!

Saludos!!

**Comment by jazcarate** [comment]
Holitas,
1. Ya funcionaban el `leer` y el `escribir`. Para hacerlo más claro agregué los tests al respecto.
2. Siempre estuvo completa. _Un `char` es un `byte`, no?_. Si, se escribe de a un `char`, no de a un `int`. El lenguaje no está _preparado_ para manejar `chars` super cómodo; pero es lo que hay.
3. No es super extensivo _(y les prometo en algún momento ejemplos)_ pero el el issue que referis; puse un ejemplo en https://github.com/sisoputnfrba/foro/issues/741#issuecomment-308278768

Saluditos

**Comment by Emi0689** [comment]
Hola, gracias por tu respuesta.

1) Estas 100% seguro que funcionan leer y escribir sin harcodear el FD? Esto lo pregunto porque si mandas una instrucción como "leer a c 5" (con a = FD) debería ejecutar obtenerPosicionVarible y deferenciar de "a". Y no me ejecuta eso... de hecho debugeando veo que me llega un int con la posición de memoria.

2) Ok. Barbaro!!!

3) Si, esta muy bien este ejemplo. El problema que tendría es que no me sirve mucho para probar los casos de grabar y leer lo grabado, saltar de varios bloques, etc. En el #737 pusiste un ejemplo mas completo, este ejemplo funcionaría? Si es así tendría varias preguntas: la conversión a binario esta bien? por que tengo 3 numeros en decimal para 5 chars?

Muchas gracias por tu tiempo!!
Saludos!!

**Comment by Emi0689** [comment]
CORRECCIÓN del punto 1!!
Funciona. Se me ocurrió esta mañana hacer un fetch por si acaso y agarro! "Cierro" punto 1!

**Comment by jazcarate** [comment]
1. Dejé el PR con los tests pertinentes del punto 1 [acá](https://github.com/sisoputnfrba/ansisop-parser/pull/20/files#diff-d9566baae8558cb571cd1e6c262b61d9R171)
2. Woohoo
3. Creería que si. Este Sabado tengo agendado un rato para pensar mejores ejemplos; y voy a [estar en Campus](faq.utn.so/sabados) resolviendo dudas de AnSISOP, y generando casos de ejemplo; así que dejame confirmarte super super bien el Sábado a la noche. Pero como para responder algo: AnSISOP no se lleva archi bien con los `char`s, entonces sería esperable que uno no pudiese _facilmente_ leer un string de un archivo, y cambiarle una letra, por ejemplo.

**Comment by Emi0689** [comment]
Barbaro!! Quedo a la espera entonces de los ejemplos cuando puedas!

Muchas gracias!
Saludos!!
