### ISSUE TITLE
Problema con librería bitarray

### ISSUE THREAD

**Issue by ezequieliriso** [sisoputnfrba/foro#764]
Hola
No se si el problema es mio o no, pero la hacer esto
--

> void *data;
   data = mmap((caddr_t)0,sbuf.st_size, PROT_WRITE, MAP_PRIVATE, fd,0);
   t_bitarray *dataBitArray = bitarray_create_with_mode(data,sbuf.st_size,MSB_FIRST);
   for(i=63*8;i<64*8;i++)
	bitarray_set_bit(dataB,i);

--
en ningún Momento se modifica el archivo real, cosa que me parece pertinente para el tipo de estructura que tiene el Filesystem
Please HELP

**Comment by nicozar95** [comment]
Buenas!

- `mmap` devuelve` void*` no `void` solo.

- ¿Que es `sbuf.st_size`?¿Donde lo inicializas y como? Ya que quiero conocer el estado de mi archivo. Deberia ser inicializado algo como:
```
struct stat sbuf;
fstat(fd, &sbuf); //fd es lo que me devuelve despues de abrir el archivo con open
```

- En vez de `PROT_WRITE`, mete `PROT_WRITE | PROT_READ`, vos queres ambos protocolos en tu area mappeada. Igual son protocolos de area mappeada no de archivo, asi que mucho no cambia. Es mas que nada como manejas eso.

- ¿Por que esto: `for(i=638;i<648;i++)`?

- Idem con `mmap`: `bitarray_create_with_mode` devuelve `t_bitarray*` no `t_bitarray`

- `dataBitArray != dataB` en la ultima linea.

- Falto el `msync`, falto el `munmap` (no se si queres unmapear tu bitarray, si no entonces no falta unmapear, era solo para poder meter la fotito de los simpsons)
![image](https://user-images.githubusercontent.com/11698687/27413357-3309de2e-56d1-11e7-90c5-d53bded5b5e3.png)

Ese es mi pseudo-code review, **anda debuggeando para ver como tenes los punteros que me parece que por ahi anda**. Si inicializaste bien el `fstat`, estarias llamando bien a `mmap`. El tema de los protocolos es un tema mio que no estoy seguro si sirve de mucho, tiene la menor prioridad en este caso. 

Saludos!

**Comment by ezequieliriso** [comment]
Cuando copie y pegue me borro los * 
Oka, ahora lo único q faltaría es msync
El fd lo obtengo de un open
El stat viene de ahí
Gracias

**Comment by salva-olacua** [comment]
Buenas, quisiera aprovechar este issue para comentar un problema parecido con el bitarray:

-El tamaño del bitarray seria la (cantidad_de_bloques_del_FS / 8 )?,(tamaño que va en el create_with_mode).
-Se debe mapear un char* al que previamente se le hizo un memset(bitMat,'0',bloques_totales_del_FS) y se guardo en el archivo Bitmap.bin?
(ya que estoy haciendo eso y al hacer set_bit(bitArray,0) y bit(bitArray,7), no me esta quedando dentro del archivo 10000001 sino 10000000, suponiendo que tenemos 8 bloques nada mas en el FS ). 

PD: No hice el msync, eso influye ? o sera que estoy haciendo algo mal.
saludos.

**Comment by salva-olacua** [comment]
Tambien aprovecho para preguntar si el archivo Bitmap.bin nos lo daran ustedes ya que estoy creando todas las estructuras yo mismo, menos la carpeta Metadata y el archivo Metadata.bin.

**Comment by tferraro** [comment]
#789 :wink:

**Comment by tferraro** [comment]
@salva-olacua @ezequieliriso les sirvieron las respuestas? El issue se puede cerrar?

**Comment by ezequieliriso** [comment]
Si cerralo. Me entraba a spam y no lo leí.
Mil perdones por la demora

**Comment by tferraro** [comment]
No zapa nada ;)
