### ISSUE TITLE
[FileSystem] Consulta - Metadata archivos directorio

### ISSUE THREAD

**Issue by alejandrog87** [sisoputnfrba/foro#765]
Buen día, tengo una consulta respecto a los archivos del tipo directorio para el tp:

Según el enunciado cada archivo tiene asociado un archivo metadata que indica:

- tamaño total del archivo (bytes)

- lista de bloques asignados al archivo

por lo cual yo podría leer un archivo concatenando todos los bloques que lo componen.

Esto queda claro para un archivo regular, pero que sucede en el caso de los directorios?

por ejemplo, dado el path:

/mnt/FS_SADICA/Archivos/passwords/alumnosSIGA.bin

alumnosSIGA.bin es un archivo regular que tiene el archivo metadata asociado anteriormente, perfecto.

passwords es un archivo del tipo directorio, pero no tiene un archivo metadata asociado que indique el tamaño y bloques que ocupa, sé que por lo general los directorios tienen el tamaño de un bloque , pero este bloque no está especificado en ningún archivo metadata, deberíamos utilizar cualquier bloque libre? (por ejemplo cuando levantamos el arbol de directorios), o podemos directamente no asignarle ningún bloque a este tipo de archivos (ya que no tendría sentido leer un archivo directorio, debería arrojar error al leerlo? ) 

Gracias.

**Comment by nicozar95** [comment]
Buenas
No le asignen ningun bloque. SADICA tiene, a grandes rasgos, 2 partes una estructura de arboles de directorios y la otra con los datos de los archivos. 
La de los datos de los archivos es la que tiene toda la joda que ponemos en el enunciado y lo que vos decis, los directorios son simples, no tienen nada.

> ya que no tendría sentido leer un archivo directorio, debería arrojar error al leerlo?
En la evaluacion final no les vamos a dar que abran un directorio, los programas van a ser correctos. Sin errores sintacticos ni nada raro.
Saludos

**Comment by dromero-7854** [comment]
Buenas... con respecto a esto... ¿No debería existir una función para crear un directorio?

Es decir... Siguiendo con el ejemplo

Si me llega una petición para crear el archivo 
/mnt/FS_SADICA/Archivos/passwords/alumnosSIGA.bin

¿Debo crear el directorio "passwords" antes de crear el archivo "alumnosSIGA.bin"? (verificando que ya no exista etc. etc.)

¿Qué pasaría si debo crear el siguiente archivo /mnt/FS_SADICA/Archivos/sucursales/utnMedrano/alumnos/passwords/alumnosSIGA.bin?
¿Debo ir creando el arbol de directorios antes de crear el archivo?

**Comment by nicozar95** [comment]
> Buenas... con respecto a esto... ¿No debería existir una función para crear un directorio?

No, los directorios de SADICA no es nada raro, son directorios comun y corrientes. Algo como `mkdir` alcanza.

> Si me llega una petición para crear el archivo
> /mnt/FS_SADICA/Archivos/passwords/alumnosSIGA.bin
> 
> ¿Debo crear el directorio "passwords" antes de crear el archivo "alumnosSIGA.bin"? (verificando que ya no exista etc. etc.)

> ¿Qué pasaría si debo crear el siguiente archivo /mnt/FS_SADICA/Archivos/sucursales/utnMedrano/alumnos/passwords/alumnosSIGA.bin?
> ¿Debo ir creando el arbol de directorios antes de crear el archivo?

Lo lindo es que lo podemos probar :smile_cat: .Fijate que pasa si hago algo como esto;
```

#include <stdlib.h>
#include <stdio.h>

int main(){
	FILE *fp = fopen("./hola/operativos.bin", "ab+");;
	return 0;
}
```

Si en la carpeta donde estoy corriendo mi programa no tengo el directorio `/hola`, de esa manera no me lo va a crear. Entonces, deberia crear el directorio `/hola` y recien ahi me va a dejar crear mi archivo.

**Comment by dromero-7854** [comment]
Por eso mismo preguntaba, había hecho la prueba y había llegado a esa conclusión...

Entonces, por lo que estoy entendiendo, la función "Crear Archivo" debería, además de crear el archivo, crear todos los directorios del path del archivo a crear (si es que no existen)

¿Entendí bien?

**Comment by nicozar95** [comment]
Claro.

**Comment by dromero-7854** [comment]
Buenisimo, por mi cerraría el issue pero no soy el que lo abrió jeje Gracias!!

**Comment by nicozar95** [comment]
@dromero-7854 @alejandrog87 
No lo cierren aun. A mi del todo no me cierra, ahora lo estamos consultando ni bien tenga una respuesta contundente les digo

**Comment by alejandrog87** [comment]
Cierro el issue.

Gracias
