### ISSUE TITLE
Filesystem escribir archivo

### ISSUE THREAD

**Issue by dipatata** [sisoputnfrba/foro#766]
Buenas tardes, tengo una duda con el enunciado:

Resulta que la firma de la funcion que escribe en archivos del parser.h es:

void (*AnSISOP_escribir)(t_descriptor_archivo descriptor_archivo, void* informacion, t_valor_variable tamanio);

Cuenta con descriptor, la informacion a escribir y el tamaño de la informacion a escribir.

Pero en el tp, la funcion escribir a filesystem esta definida como:

Guardar Datos
Parámetros: [Path, Offset, Size, Buffer]

De donde sacamos el parametro del offset que pide el tp pero no esta en las funciones del parser?

**Comment by Emi0689** [comment]
Como estas? fijate que hay una funcion que es moverCursor. Tanto leer como escribir, lo haran dependiendo "como este el cursor" al momento de ejecutarse.

Saludos!!
