### ISSUE TITLE
Duda sobre guardar datos en File System

### ISSUE THREAD

**Issue by JuanCrespo18** [sisoputnfrba/foro#767]
Mi duda es la siguiente: cuando se quieren guardar datos en un archivo a partir de determinado offset, yo a partir de ese offset tengo que sobreescribir todo lo que venga después que ya está guardado o tengo que escribir en el medio sin borrar todo lo demás?

No se si la pregunta es muy obvia, si está en explícito en el enunciado o no, pero estuve pensando un buen rato y no estoy seguro. Le pegué otra leída al enunciado y no lo saqué, así que mejor pregunto acá.

Gracias!

**Comment by nicozar95** [comment]
Cuando vos escribis un archivo pisas lo que estaba antes escrito en esa pocision del archivo. Si yo te digo escribime desde el byte 1, 4 bytes. Los 4bytes que pise no me importa.

A partir del offset tenes que sobrescribir. No entiendo a que te referis con escribir en el medio sin borrar todo lo demas.¿Como manejarias eso?

**Comment by JuanCrespo18** [comment]
No claro, ni pensé cómo sería escribir en el medio, creo que sería un lindo quilombo. Me imaginaba que estaba más del lado de sobreescribir. 
Ahora si esos bytes que me piden escribir abarcan más de un bloque se aplica lo mismo, correcto? Es decir tengo que ir sobreescribiendo los datos en cada bloque hasta terminar de escribir todo.

Por si las dudas un ejemplo:
Me piden escribir 20 bytes desde el offset 5  y mi archivo ya tiene 3 bloques asignados (tengo bloques de 10 bytes). Debería sobreescribir 5 bytes del primer bloque, el segundo bloque entero y en el tercero 5 bytes más. Es así?

**Comment by nicozar95** [comment]
> Me piden escribir 20 bytes desde el offset 5 y mi archivo ya tiene 3 bloques asignados (tengo bloques de 10 bytes). Debería sobreescribir 5 bytes del primer bloque, el segundo bloque entero y en el tercero 5 bytes más. Es así?

Es asi :smile:

**Comment by JuanCrespo18** [comment]
Gracias!
