### ISSUE TITLE
Guardar datos en el FS

### ISSUE THREAD

**Issue by CarolinaPonceRodriguez** [sisoputnfrba/foro#768]
Si bien ya hicieron preguntas parecidas, vengo con la siguiente, ya que no se si se puede llegar a solicitar o no.
Si tengo un archivo que tiene 3 bloques asignados de 10 bytes cada uno y me piden escribir 5 bytes a partir del byte 31, esto implicaria sin lugar a duda, agregar un bloque mas, por lo cual pasaria a tener 4 bloques.
Seria posible que se solicite un offset mucho mayor y deba asignar bloques con  "basura"?
Pienso en la posibilidad de que (usando el mismo ejemplo) se me pida escribir  desde el byte 55 lo que implicaria:
- Los 3 bloques que ya tenia asignados
- Asignar un 4to bloque(tendria basura porque no se me pidio escribir en este aun)
-Asignar un 5to bloque(a partir de este se me solicito escribir un size dado y dependiendo el mismo, agregare o no mas bloques).

Todo esto porque al asignar bloques incrementaria mi tamanio de archivo por cada uno y el offset debe estar "contenido" dentro de ese tamanio para ser valido.

Espero haber sido clara!
Saludos!!

**Comment by nicozar95** [comment]
Claro, osea a medida que vas a escribir va ir creciendo el archivo. Si te piden escribir desde una pocision que no tenes vas a tener que asignarle otro bloque, hasta que te quedes sin bloques libres en tu FS.

**Comment by CarolinaPonceRodriguez** [comment]
Claro, entiendo que el bloque con basura, va a sumar en el total del tamanio del archivo.
Ahora tengo otra consulta, pero creo que aplica por igual. Cuando creo un archivo nuevo y tengo que asignarle por defecto un bloque, al tamanio del archivo se le va a asignar el tamanio del bloque verdad? 
Mi archivo nuevo quedaria asi:
TAMANIO= tamanio_bloque
BLOQUES=[bloque]

A fin de cuentas seria como hacer un touch del archivo y luego un truncate con el tamanio de bloque.
Saludos!.

**Comment by nicozar95** [comment]
No, ni bien creas un archivo le vas a asignar un bloque pero su tamaño es 0.
¿Por que? Cuando vayas escribiendo va a ir aumentando el tamaño del archivo y pueden que te queden bytes basuras en el archivo y esos no los queres levantar.
ejemplo con bloques de 10 bytes:

TAMANIO=25
BLOQUES=[0,5,6]

Del ultimo bloque vos vas a considerar los 5 primeros bytes, no me interesa los otros bytes que tenga el bloque 6

Es un tema distintos cuando moves el cursor, si el cursor lo moviste a una pocision que se va del tamaño de mi archivo, le tenes que asignar ese bloque (si hace falta) y empezas a escribir desde el nuevo offset. Todo lo que te tuviste que correr para llegar a esa nueva pocision es como que lo escribiste, por eso se suma al tamaño de tu archivo.

por ejemplo tengo el mismo archivo de arriba, pero ahora mande a escribir en la pocision 35, 10 bytes entonces me queda:

TAMANIO=45
BLOQUES=[0,5,6,3,4]

Osea los primeros 25 bytes que estan en los bloques 0,5 y en la mitad del 6 eran mis datos originales.
La otra mitad del 6 y la primera mitar del 3 es lo que me tuve que mover, tiene basura pero no me importa es como si hubiera escrito 10 bytes de basura desde la pocision 25.
La segunda mitad del 3 y la primera mitad del 4 corresponden a los datos que escribir desde la pocision 35.
La segunda mitad del 4 tiene basura que NO la levanto porque si la considero mi archivo tendria un tamaño de 50 bytes en vez de 45 ¿Se entiende ?

Cuando vos creas un archivo nuevo y no escribiste nada quedaria el archivo de configuracion de la siguiente manera:

TAMANIO=0
BLOQUES=[20] 

20 seria el bloque que le asigne.
Si seguimos con el ejemplo de que los bloques pesan 10 bytes, si yo voy a la carpeta de /Bloques y me fijo en el tamaño de 20.bin (algo como click derecho + propiedades) me va a decir que el archivo 20.bin pesa 10 bytes, porque ese es el tamaño de mis bloques.

¿Se entiende masomenos? Cualquier cosa avisanos

**Comment by picollomartin** [comment]
Una duda que me surgió leyendo este issue, la asignación de bytes en los bloques no es continua? (así lo había pensado) porque sino como sabemos el offset de cada bloque donde hay que empezar a leer ?Hay algun byte de corte o algo por el estilo?

Saludos

**Comment by nicozar95** [comment]
Tenes el cursor por cada uno de los archivos que abris, este arranca en 0 y lo moves por donde vos quieras. Si yo te dijo escribime desde el offset 0, 10 bytes. Esos 10 bytes estan uno al lado del otro en el bloque correspondiente (suponiendo que entran todos esos bytes en ese bloque). En caso de que no te entre en un bloque, vos vas a pedir otro y te van a quedar bytes al final de un bloque y bytes al principio.
Ojo con eso, cuando vos escribis o lees un archivo **no tenes que mover el cursor del mismo**

En el ejemplo de arriba, cuando vos moviste tu cursor a una pocision que se te va del tamaño del archivo ese desplazamiento lo consideras como bytes escritos en el archivo.

**Comment by nicozar95** [comment]
Igual a mi me parece un caso muy raro de que hagamos que el cursor se mueva a una pocision fuera del tamaño del archivo. Ahora les confirmo si este caso se va a evaluar. 
Para mi no tiene sentido.

**Comment by nicozar95** [comment]
@CarolinaPonceRodriguez @picollomartin Charlandolo con el resto de los ayudantes, no vamos a evaluar que el puntero este fuera del archivo correspondiente

**Comment by CarolinaPonceRodriguez** [comment]
Entendido! Cierro el issue.
Gracias!!!
