### ISSUE TITLE
Problema con bitarray_set_bit

### ISSUE THREAD

**Issue by AltTomas** [sisoputnfrba/foro#769]
Hola a todos, tengo una duda, creo que yo estoy haciendo algo mal, pero no me doy cuenta. Acá pongo el código, a ver si me pueden dar una mano, ya que el bitarray_set_bit no cambia el bit (de 0 a 1) o el msync no hace la escritura.
Lo que hice fue lo siguiente: 

Acá creo el bitmap:
```
void crearBitmap(){
	FILE * bitmap = fopen("/home/utnso/Escritorio/mount/Metadata/Bitmap.bin", "rb");

	bmap = mmap(NULL, sizeof(bitmap), PROT_WRITE | PROT_READ, MAP_SHARED, bitmap, sysconf(_SC_PAGE_SIZE));

	bitarray = bitarray_create_with_mode(bmap, 5200/8, MSB_FIRST);
}
```

Y en esta parte de la función quiero cambiar un bit del bitmap ya que sería la función donde le asigno un bloque a un archivo:

```
	off_t test = 5;
	
	bitarray_set_bit(&bitarray,test);
	
	msync(&bmap, sizeof(&bitarray), MS_SYNC);
```
	
Qué me está faltando/estoy haciendo mal?

Muchas gracias!

EDIT: Otra pregunta, si yo pongo bitarray_set_bit(&bitarray,test); no rompe, ahora si pongo bitarray_set_bit(bitarray,test); (sin el &) rompe, por qué motivo?

**Comment by nicozar95** [comment]
Buenas
Aca tenes un par de arreglos a hacer en el mmap:

```
FILE * bitmap = open("/home/utnso/Escritorio/mount/Metadata/Bitmap.bin", O_RDWR); //No uses fopen, usa open, asi esta en la documentacion del mmap

/*Calculo que bmap ya lo inicializaste arriba :)
* el sizeof(bitmap) no es lo que corresponde deberias hacer:
*/
struct stat mystat;

if (fstat(fd, &mystat) < 0) {
    printf("Error al establecer fstat\n");
    close(fd);
    return NULL;
}

//El ultimo argumento de mmap es el offset del mapeo, si bien tiene que ser multiplo del tamaño de pagina del sistema por eso usas sysconf(_SC_PAGE_SIZE), esto te esta corriendo un cacho el mapeo
// de tu archivo y te va a dar problemas. Mas facil y lindo que empieze en 0 :D

bmap = mmap(NULL, mystat.st_size, PROT_WRITE | PROT_READ, MAP_SHARED, bitmap, 0);
```

Ahora con la segunda parte:

```
//Va sin &, recive el puntero, no la direccion en memoria igual depende mucho de como lo estes llamando.
bitarray_set_bit(bitarray,test);

//Aca tenes un tema, es el mismo que el anterior, depende mucho como estes manipulando los punteros
msync(bmap, sizeof(bitarray), MS_SYNC);

```

> EDIT: Otra pregunta, si yo pongo bitarray_set_bit(&bitarray,test); no rompe, ahora si pongo bitarray_set_bit(bitarray,test); (sin el &) rompe, por qué motivo?

AHA! Eso confirma lo que pensaba estas manipulando los punteros a tu manera, lo mas probable es que rompa porque le estas pasando mal la pocision a la funcion que hace todo lo del bitmap. Estas teniendo un mambo con los punteros, fijate de ir debuggeando haber que onda si la pocision inicial donde creaste el mapeo es la misma que le llega cuando creas el bitmap, y si esta es la misma cuando la seteas

Saludos

**Comment by AltTomas** [comment]
Nico, muchas gracias, me quedo muy claro. Sin embargo, debugeando veo lo siguiente:

Cuando hago el bitarray_create_with_mode que es asignado en bitarray (variable que asigno como t_bitarray en el .h para que todas las funciones del .c puedan usarlo), si yo veo lo que me dice sobre "bitarray" es que en la estructura t_bitarray, el campo "mode" y "size" están correctos, sin embargo el campo "bitarray" me dice: 
`Name : bitarray
	Details:0xffffffff <error: No se puede acceder a la memoria en la dirección 0xffffffff>
	Default:0xffffffff <error: No se puede acceder a la memoria en la dirección 0xffffffff>
	Decimal:4294967295
	Hex:0xffffffff
	Binary:11111111111111111111111111111111
	Octal:037777777777
`
y además, cuando abro bitarray, y veo que me dice *bitarray, es lo siguiente:

`Failed to execute MI command:
-data-evaluate-expression *((bitarray)->bitarray)
Error message from debugger back end:
No se puede acceder a la memoria en la dirección 0xffffffff`

Es un error en el mmap? al pasarle la addr como NULL?. Yo le pasé NULL ya que leyendo dicen que es lo mejor porque el kernel se encarga de elegir la dirección y así no te podes mandar ninguna cagada pisando algo que ya esté mapeado.

Muchas gracias!

**Comment by nicozar95** [comment]
No, el NULL esta bien porque a vos no te interesa en que pocision de la memoria mapea tu archivo.
¿Cuales es la direccion que te devuelve al mapear?¿Es 0xffffffff? Es una direccion rara para mapearte tu archivo. Esa direccion en memoria representa la ultima direccion fisica de una arquitectura de 32 bits.

Para ver si te mapeo, debajo del mmap mete:

```
if (bmap == MAP_FAILED) {
		printf("Error al mapear a memoria: %s\n", strerror(errno));
		close(fd);
		return NULL;
}
```

**Comment by AltTomas** [comment]
Hay un error de argumento. Cuando debuggeo y veo los argumentos, veo que todos están (aparentemente) bien, sin embargo size que sale de mystat.st_size el valor es 0. Será por eso? por qué me da que el valor del tamaño del archivo es 0?. El código me quedó así:

```
void crearBitmap(){


	int bitmap = open("/home/utnso/Escritorio/mount/Metadata/Bitmap.bin", O_RDWR);

	struct stat mystat;

	if (fstat(bitmap, &mystat) < 0) {
	    printf("Error al establecer fstat\n");
	    close(bitmap);
	}

	bmap = mmap(NULL, mystat.st_size, PROT_WRITE | PROT_READ, MAP_SHARED, bitmap, 0);

	if (bmap == MAP_FAILED) {
			printf("Error al mapear a memoria: %s\n", strerror(errno));

	}

	bitarray = bitarray_create_with_mode(bmap, 5200/8, MSB_FIRST);

}
```

Se me complica entender el error porque eclipse no me tira ningún tipo de error ni advertencia.

**Comment by nicozar95** [comment]
Eclipse no te va a tirar ningun error ni advertencia porque esto es C. Y C asume que vos queres hacer eso, que el error es del programador.

Si el st_size del archivo es 0, significa que el archivo que queres abrir esta vacio y como esta vacio no tiene nada para mapear en Memoria.

**Comment by AltTomas** [comment]
Listo! Ya anda todo bien, si hago el set_bit lo escribe en el archivo y si hago el clean_bit también. Ahora mi última duda es: Si yo abro el archivo con hex editor es medio raro, cuatros por acá, veintes por allá, sin embargo el set y clean parecen andar como deben ya que el test_bit así lo verifica. No le doy bola a lo que me diga el hex editor?

**Comment by nicozar95** [comment]
¿Que era? Nunca use la opcion de hex editor en eclipse asi que no tengo idea.
Calculo que es para ver tu archivo en hexadecimal, no? Si es asi tiene sentido que no se entienda nada

**Comment by AltTomas** [comment]
Es el Bless de la VM. 
Una pregunta más, en el validar archivo, a mi se me va a dar un path por ejemplo mnt/archivos/carpeta1/archivo1.bin o se me va a dar un path cualquiera de la VM?

O sea, para hacer algo más clara la pregunta, los archivos que pide un programa ANSISOP pueden estar en cualquier lado o van a estar siempre en el punto de montaje del FS?

**Comment by nicozar95** [comment]
> O sea, para hacer algo más clara la pregunta, los archivos que pide un programa ANSISOP pueden estar en cualquier lado o van a estar siempre en el punto de montaje del FS?

Van a ser todos en el punto de montaje del FS SADICA en el directorio /Archivos y en los subdirectorios de este (ejemplo /Archivos/alumnos/passwords.bin).
No van a estar en cualquier lado.

**Comment by AltTomas** [comment]
Ahh, perfecto, me estaba haciendo un lío bárbaro suponiendo que el archivo podía estar en cualquier lado.
Gracias!
