### ISSUE TITLE
Fin de programa - FD

### ISSUE THREAD

**Issue by jbmild** [sisoputnfrba/foro#770]
Buenas, nos surgio una duda.
Cuando un programa finaliza y el codigo .ansisop no cierra el archivo. Tendria que cerrar los FD? Yo entiendo que si deberia ya que el SO deberia liberar todos los recursos pero, me lo confirman? :D
Gracias

**Comment by nicozar95** [comment]
Si

**Comment by jbmild** [comment]
Grax
