### ISSUE TITLE
2ndo arg de leer archivo

### ISSUE THREAD

**Issue by ziggylineous** [sisoputnfrba/foro#772]
el 2ndo arg de leer es una posición en memoria donde guardar lo que se lee desde el fs. Pasa que el parser espera una variable acá (hace un obtenerPosición, por lo q hay q pasarle una var o arg). Y obtiene la posición relativa al inicio del stack de esa variable (0, 4, 8, 12, 16, ...). A esto le tenemos que sumar el offset donde empieza el stack en nuestra función ansisop_leer? Mi duda es porque si es así entonces no se le puede mandar un posición de memoria dinámica, del heap (porq siempre busca la posición de la var en el stack). Le sumo dónde empieza el stack?

**Comment by nicozar95** [comment]
Buenas
Ahora lo estoy consultando, ni bien tenga novedades les respondo
Saludos

**Comment by ziggylineous** [comment]
si le pasas una var que usaste en un `alocar` no toma el valor (dir en memoria dinámica) sino su posición relativa al inicio del stack (porq el parser hace _obtenerPosición en ese token)

```
variables d, a
alocar a 20
abrir d LE archivo.txt
leer d a 10
```

el parser no guarda lo q haya en el archivo en la página de memoria dinámica, sino que llama a nuestra implementación de `leer` con la posición de `a` relativa al inicio del stack (en este caso, 4). Por ahora estoy sumandole el offset del stack, pero no parece que debiera funcionar así

**Comment by jazcarate** [comment]
Como decís, `leer` debería tener el *valor*, no la posición. Cree un PR en el parser para arreglar esto 👍.
Gracias

**Comment by ziggylineous** [comment]
joya, gracias
