### ISSUE TITLE
Reglas para BORRAR archivo en Kernel

### ISSUE THREAD

**Issue by jlusnich** [sisoputnfrba/foro#773]
Buenas,

Vemos que en el enunciado del Kernel no se realiza ninguna aclaración acerca de qué condiciones se deben cumplir para borrar un archivo.

La pregunta entonces es: que reglas tomamos? Simplemente que un archivo no puede ser borrado si lo tiene abierto un proceso? Gracias

**Comment by nicozar95** [comment]
Fíjate que dice algo:

> Un archivo ​ no puede ser borrado del FileSystem si existe su entrada en la Global File Table. ​ El
> mismo debe finalizar abruptamente si no puede realizar esta operación.

Osea, para poder borrar el archivo el mismo no tiene que estar abierto por ningún proceso, no tiene que tener una entrada en la tabla global de procesos.

**Comment by fededri** [comment]
O sea que primero para borrar un archivo, el mismo tiene que haber sido cerrado por todos los procesos que lo hayan abierto, si no el proceso que quiera borrarlo sera finalizado?
