### ISSUE TITLE
[Valgrind - Consola] Dudas respecto al reporte

### ISSUE THREAD

**Issue by Gruschka** [sisoputnfrba/foro#774]
Hola gente!

Estoy corriendole Valgrind a la consola (no manejo muy bien que digamos a Valgrind) para ver que no este leakeando nada y la verdad es que no llego a entender si esta leakeando o no (entiendo que si segun el tutorial que esta en la pagina del a catedra) y hasta que punto. Segun lo que me dice el log de valgrind yo _entiendo_ que tendria leaks solamente en el heap porque dice que hago mas mallocs que free (en mi codigo hay una relacion 1-1 en cantidad de mallocs y frees, incluso en algunos casos 1-2 segun la circunstancia que se de) pero me confunde el hecho de que abajo diga que en total perdi 0 bytes.

Ademas no llego a entender - en caso de que efectivamente este leakeando - cual seria el origen.

El reporte lo saque de esta manera:

`valgrind --log-file="fullcheck_leakkinds" --leak-check=full --show-leak-kinds=all ./consola.c`

Adjunto el reporte en cuestion a ver
[fullcheck_leakkinds.txt](https://github.com/sisoputnfrba/foro/files/1100128/fullcheck_leakkinds.txt)

Muchas gracias de antemano!

**Comment by mgarciaisaia** [comment]
👋 Tu log de valgrind dice que no hay leaks. Sólo dice que, cuando finaliza el programa, todavía hay algunos bloques no liberados, pero a los que todavía se puede acceder - es decir, no se _perdió memoria_, si no que _no se liberaron_ algunos bloques antes de finalizar el programa. Eso no calienta, en general, porque al finalizar el programa se libera toda la memoria, así que meh. Lo único que podría marcar eso es que haya algún bloque de memoria que esté viviendo más tiempo que lo necesario, pero no nos calienta en absoluto.

**El problema** es que el log de valgrind dice otra cosa más: que el programa analizado es `/bin/dash` - es decir, la consola de Linux (y no _tu programa). Y esto, ¿por qué?

Bueno, porque tu línea de valgrind dice que estás corriendo `./consola.c`. Quizá tengan una convención _bastante rara_, pero, en principio, los archivos fuente `.c` **no son ejecutables**. Uno los compila, y ejecuta el compilado.

Esto, sumado al temita del `/bin/dash`, más una pizca de experiencia de unos cuatris siendo ayudante de la materia, me hacen creer que probablemente _armaron un script en bash_ llamado  `consola.c` que compila y ejecuta su programa (probablemente agregándole el export del `LD_LIBRARY_PATH`, incluso).

Si ese es el caso, lo que están corriendo con valgrind es _la ejecución de ese script_, que es un proceso `/bin/dash`, y que está más o menos bien testeado, así que sería raro que leakee memoria. Pero eso no dice nada sobre **tu** programa.

Si tienen un script, metan la línea de valgrind ahí adentro, en donde sea que estén llamando a su ejecutable. O dejen de usar ese script, como prefieran.

Ahora sí se va a poner picante 🙃

**Comment by Gruschka** [comment]
Hola @mgarciaisaia ! Muchisimas gracias por tu respuesta!

Me parecia raro que me marque todas direcciones de memoria de /bin/dash.

Cuando ejecuto a valgrind deberia hacerlo con el binario de la consola, no? Osea, el ejecutable que resulta de la compilacion? Siempre lo tengo en la misma carpeta que el .c (src) pero en mi caso no aparece. Cuando me fijo en Eclipse que hace cuando ejecuta la consola, el path que toma gcc es el que te muestro en el screenshot que adjunto. Entonces, yo deberia llamar a valgrind pasandole ese path?

<img width="1053" alt="screen shot 2017-06-25 at 11 10 05 am" src="https://user-images.githubusercontent.com/11674324/27517425-d818fbec-59a2-11e7-877c-1218516f1668.png">

Si es asi, te molesto con una pregunta boba. Como veras en el path del screenshot, lo hace incluyendo un par de libraries (commons, pthread y shared leto que es una nuestra). Si entonces yo tengo que llamar a Valgrind debo pasar estas bibliotecas como parametro o de alguna forma para que las incluya? Porque cuando quiero llamar a Valgrind al path en cuestion me aparece este error:

<img width="1060" alt="screen shot 2017-06-25 at 12 38 02 pm" src="https://user-images.githubusercontent.com/11674324/27517438-2f6f0e72-59a3-11e7-8d3b-aab87f21e11a.png">

Trate de incluir esa libreria de distintas maneras y no tuve suerte. 

Tambien intente generar un ejecutable usando gcc (copiando la forma en que aparece en eclipse) pero me tira este error:

<img width="1000" alt="screen shot 2017-06-25 at 12 42 25 pm" src="https://user-images.githubusercontent.com/11674324/27517469-c75fc622-59a3-11e7-8a24-3d0761b5ebd7.png">

De modo que no estoy seguro si estoy mandando el archivo erroneo a Valgrind o si le estoy pasando mal los parametros (si tengo que incluir las bibliotecas que use mi _consola.c_).

Disculpa que la pregunta sea re boba pero estoy dando vueltas con esto y no le tomo la mano.

Mil gracias de nuevo!

**Comment by nicozar95** [comment]
Hola!
Si vos queres ejecutar valgrind en el proceso consola en vez de pasar por el script, compilalo en Eclipse y fijate en tu carpeta Debug algun archivo ejecutable.

![image](https://user-images.githubusercontent.com/11698687/27518273-61a12466-59b2-11e7-980a-f44202f3e708.png)

Este error es de la shared library, ahi hace el export de tu progama, osea antes de ejecutar el `./consola` hace:
 `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~<Donde este el .so de tu shared library>`

![image](https://user-images.githubusercontent.com/11698687/27518298-f131e156-59b2-11e7-9200-cb6087638c0d.png)

Este otro error es mas rebuscado, aca vos estas compilando todo el proceso consola con el compilador `gcc`, este compilador tiene un monton de flags y cosas que le tenes que pasar para que te cree el ejecutable. Para programitas sencillos en C esta buenisimo, para un TP de operativos... vas a estar mas tiempo pasandole la cantidad de argumentos que requiere para compilar que en la evaluacion final.
En vez de explicarte que argumentos le tenes que pasar a `gcc` (yo no tengo mucha idea tampoco) hacela mas facil con el `make` :smile: 
Eclipse genera un makefile para compilar tu proyecto, con ese makefile ya podes generar tu ejecutable con un simple comando en vez de ir pasandole todas las dependencias correspondientes.
Entonces anda a la carpeta donde tengas el makefile de tu programa (en este caso /consola/Debug creo) y ejecuta el comando: `make`
Con eso te deberia aparecer el programa ejecutable que despues lo podes llamar con valgrind con:
`valgrind ./consola`

Saludos

**Comment by Gruschka** [comment]
Hola @nicozar95 ! Muchas gracias nuevamente por tu respuesta!

Si, yo el ejecutable lo tengo en la carpeta Debug.

Corri el export de esta manera y no paso nada:
<img width="1431" alt="screen shot 2017-06-25 at 3 14 26 pm" src="https://user-images.githubusercontent.com/11674324/27518561-1c76784e-59b9-11e7-9295-6b4c1fbd3bb3.png">

Cuando quiero correr la consola me sigue tirando el error. Quise tirar un man de export y no no hay entrada de manual. Mande export solo y me salto lo siguiente que me parece relevante, ya que pareciera como que el LD_LIBRARY_PATH me quedo concatenado muchas veces y por eso no lo encuentra (quizas estoy diciendo una huevada). 

<img width="1628" alt="screen shot 2017-06-25 at 3 03 36 pm" src="https://user-images.githubusercontent.com/11674324/27518573-84806c74-59b9-11e7-87d1-3be40bab144c.png">

Si esto es asi, habria una manera de borrarlo para cargarle la path correspondiente? El path que le pase me parece el correcto:
<img width="550" alt="screen shot 2017-06-25 at 3 16 38 pm" src="https://user-images.githubusercontent.com/11674324/27518567-5e41dfd4-59b9-11e7-88c8-fe290b68fbef.png">

Por ultimo intente hacer un make de consola y me dice que esta actualizado asi que entiendo que lo del ejecutable ya estaria.

Mil gracias por su ayuda chicos!

**Comment by Gruschka** [comment]
Bueno, como @mgarciaisaia predijo se puso todo muy picante jajajajaja.

Pude correr valgrind y levantar los archivos, todo perfecto. 

Para cerrar el thread quisiera saber si solamente me tengo que preocupar por los bytes que dicen _"definitely lost"_ y no por los que son _"possibly lost"_ o _"still reachable"_ .

Ademas quisiera saber que tolerancia tenemos para los leaks de memoria. Segun el Leak Summary del reporte que me tiro valgrind recien, despues de abrir tres programas, dejarlos correr un ratito y cerrarlos uno por uno termine con:

 LEAK SUMMARY:
==4532==    definitely lost: 588 bytes in 21 blocks
==4532==    indirectly lost: 0 bytes in 0 blocks
==4532==      possibly lost: 408 bytes in 3 blocks
==4532==    still reachable: 626 bytes in 14 blocks
==4532==         suppressed: 0 bytes in 0 blocks

Mil gracias a todos, son unos capos!

**Comment by tferraro** [comment]
Medio tarde esto, peeero, mejor tarde que nunca :P.

Idealmente, lo que sea parte de tu código estaría genial que no tenga "definitely lost", "possibly lost" o "still reachable", ojo, _su_ parte del codigo, si son las commons o otra biblioteca, no se preocupen demasiado. Más que nada, por un tema de prolijidad y porque si esa pequeña pérdida memoria, no es estática (no es constante durante toda la ejecución), el memory leak pasa a ser un problema importante que es tomado como condición básica de aprobación y además porque les puede hacer volar el TP en cualquier momento :disappointed: 

Para más información de que significa cada cosa, así no me extiendo mucho, pegale una leida (aunque seguramente ya lo hiciste) al [tuto de valgrind que tenemos dando vueltas por ahi](faq.utn.so/valgrind)!

Cualquier cosa chifla!

**Comment by tferraro** [comment]
@Gruschka te sirvó mi respuesta? Algo más en lo que podamos darte una mano o se puede cerrar el issue?

**Comment by Gruschka** [comment]
@tferraro Me vino ideal! Mil gracias a todos. Estaba recontra perdido con Valgrind, ahora pierde 0 bytes la consola!

Como nota para referencia por si alguno le pasa: Los possibly lost eran en su gran mayoría los hilos que al finalizarlos abortivamente no liberaban recursos (faltaba setearlos como detachables).

De nuevo, mil mil gracias!

**Comment by NicoUTN** [comment]
Perdón que me meta pero me gustaría mandarme a hacer una pregunta antes que cierren el issue de algo que me quedó medio colgado. Cuando comentaban que:

"Idealmente, lo que sea parte de tu código estaría genial que no tenga "definitely lost", "possibly lost" o "still reachable", ojo, su parte del codigo, si son las commons o otra biblioteca, no se preocupen demasiado."

Cual sería el problema de que tenga "still reachable"? Según lo que tengo entendido la categoría "still reachable" hace referencia a bloques que no fueron liberados, pero podrían ser liberados si el programador desea porque de todas maneras el programa aún los referencia. Entonces en qué difiere que uno se ponga a liberarlos "a mano" o simplemente deje que se de por finalizado el programa provocando que se liberen?

**Comment by tferraro** [comment]
Como primera instancia, porque estas rompiendo el contrato que te da la interfaz para pedir recursos del Sistema Operativo. No necesariamente el SO va a liberarte todos los recursos, y tampoco lo hace de forma instantánea.

Además, más allá de los problemas que podes encontrar si confias en que el SO va a hacer las cosas de una manera (cosa que nunca te garantiza), esto forma parte de las denominadas Buenas Prácticas.

**Comment by NicoUTN** [comment]
Ok. Gracias!
