### ISSUE TITLE
Duda paths filesystem

### ISSUE THREAD

**Issue by AltTomas** [sisoputnfrba/foro#775]
Hola a todos, haciendo las funciones del FS me entró la duda sobre los paths que los programas ansisop puedan llegar a pedir. Estos van a ser absolutos? osea por ejemplo ./mnt/Archivos/password/Alumnos.bin
o van a ser, ./password/Alumnos.bin y el ./mnt/Archivos/ nosotros ya lo levantamos cuando nos dan el punto de montaje? o pueden ser de las dos maneras?

Pregunto esto ya que me cambia bastante como manejo los paths al momento de intentar manipular los archivos.

Gracias!

@nicozar95

**Comment by CarolinaPonceRodriguez** [comment]
Mira, tengo entendido que el path que te llegue va a ser relativo, a lo que se apunta con esto es a que sea responsabilidad exclusiva del filesystem conocer su punto de montaje porque podrias montar tu fs en donde se te cante y cuando el kernel te pase la ruta de un archivo "concatenar" con tu punto de montaje y fijarte si esta ahi, dentro de tu fs. Como dice en el tp: [punto de montaje]/Archivos/[path]  vos recibirias path y te encargarias de armar el resto.
Saludos!

**Comment by tferraro** [comment]
@AltTomas te sirvió la respuesta de Carolina? (aunque parezca que no, tiene un +1 de un ayudabnte, y te confirmo que lo que dijo es correcto :P). Si es así, se puede cerrar el issue?

Saludos!

**Comment by AltTomas** [comment]
Si! Perdón por colgarlo! Cerra nomás.
Gracias!

**Comment by tferraro** [comment]
Barbaro!
