### ISSUE TITLE
Consulta sobre abrir archivo en el contexto del kernel

### ISSUE THREAD

**Issue by ivodan** [sisoputnfrba/foro#776]
En el enunciado dice:

> Un mismo proceso puede abrir más de una vez a un mismo archivo, con diferentes o iguales
permisos. Esta situación puede darse, por ejemplo, cuando varios Threads de un proceso se
encuentran operando sobre el mismo archivo.

En el momento que llega la segunda petición de abrir el archivo ¿Qué sucede con los flags en la tabla de archivos del proceso?
¿Deberían respetarse los flags de la primera vez que se abrió el archivo?¿Sobreescribirlos con los que llegan de la segunda vez?¿Acumular los flags de ambas(es decir si la primera vez se abrio en escritura y la segunda en lectura, que en la tabla quede como lectura y escritura)?

Muchas gracias!

**Comment by nicozar95** [comment]
Buenas
Cuando llega una peticion de abrir un archivo, creas una entrada en la tabla con los flags correspondientes, no importa si el proceso ya abrio el archivo.
Por ejemplo, suponete que abriste el archivo /hola.bin con permisos de lectura y escritura, entonces tu tabla de archivos por proceso te queda algo como:

"rw" | 1 -> fd = 3

Donde 1 vendria a ser el Global FD.
El fd asociado al proceso es el 3.
Si el proceso vuelve a abrir el mismo archivo pero ahora con el flag de lectura, no te haces drama y creas una nueva entrada, ahora tu tabla de archivos para ese proceso te queda:

"rw" | 1 -> fd =3
"r" | 1 -> fd=4

Fijate que ambas entradas apuntan al mismo GlobalFD, en la tabla global de archivos, asumiendo que solo ese proceso abrio el archivo /hola.bin, entonces la entrada de /hola.bin en la tabla global de archivos tiene 2 procesos en su contador, osea, que el archivo esta abierto 2 veces.

¿Que pasa con los permisos? Si yo mande a escribir en mi primer archivo, el que tiene un fd asociado al proceso igual a 3, el que lo abrí con permisos de lectura y escritura, entonces voy a poder escribir sin problemas.
Ahora bien si mando a escribir en mi fd = 4, no me deberia dejar porque ese fd esta abierto con permisos de lectura nada mas.
Si bien es el mismo archivo, los permisos de cada uno de los fd asociados son distintos, depende con que fd llames a la funcion escribir/leer.
Saludos

**Comment by ivodan** [comment]
Mas claro imposible, muchas gracias!
