### ISSUE TITLE
Duda con borrar archivos

### ISSUE THREAD

**Issue by ivodan** [sisoputnfrba/foro#777]
Buenas
Tengo una duda con el alcance de la función borrar archivo, ya que el kernel solo borra archivos llegado el punto de que ningún proceso lo tenga abierto. 
Por ejemplo ¿Qué debería hacer el kernel si un proceso le pide borrar un archivo que está abierto por varios procesos?
Muchas gracias!

**Comment by nicozar95** [comment]
Decirle que no y terminar el proceso ansisop :dancer:

**Comment by ivodan** [comment]
Bien,
y en el caso en que el proceso sea el único que tiene abierto un archivo, cerrar y abrir tendrían el mismo resultado no?

**Comment by nicozar95** [comment]
Para borrarlo no tienen que haber entradas de ese archivo en la tabla global. 
¿Cuando sale un archivo de la tabla global de archivos? Cuando su contador es 0
¿Cuando disminuye su contador? Cuando se cierra un fd asociado a ese archivo.
¿Cuando aumenta su contador? Cuando se abre un fd asociado a ese archivo.

En el caso de que sea un unico proceso que:
Lo abrio -> Crea la entrada y el contador esta en 1.
Si despues lo cerro -> Disminuye el contador que ahora esta en 0, como esta en 0 lo puedo sacar de la tabla de archivos globales y **ahora lo puedo borrar**
Si despues lo volvio a abrir -> Vuelve a crear la entrada en la tabla global de archivos y pongo el contador en 1, **ahora NO lo puedo borra**
Si ahora lo quiere borrar -> Le digo que no y que termine :dancer:

**Comment by ivodan** [comment]
ahh no estaba entendiendo..
Pensaba que el kernel borraba el archivo cuando ningún proceso lo tenia abierto(cuando el contador de quedaba en 0), pero en realidad es que el kernel PERMITE borrar archivos solo si nadie los tiene abiertos verdad?

**Comment by nicozar95** [comment]
Si, una cosa es cerrar el archivo, osea que ese proceso no lo va a tocar mas. Y otra cosa es borrar el archivo y marcar todos sus bloques como libres.

Si yo cerre mi archivo, lo puedo volver a abrir y leer lo que yo quiera. Si yo borre mi archivo... :wave: chau a mis datos, no los puedo recuperar.

**Comment by ivodan** [comment]
Te agradezco, saludos!

**Comment by nicozar95** [comment]
@ivodan Se esta revisando este tema ya que el parser recibe un fd en vez de un path. 
Y no lo vas a poder borrar un archivo sin fd
