### ISSUE TITLE
Quantum sleep en archivo de configuración

### ISSUE THREAD

**Issue by lucaspolonuer** [sisoputnfrba/foro#778]
Hola, estábamos revisando el enunciado y nos dimos cuenta que se nos pasó de largo, lo que dice en la página 19 abajo de todo en letra chiquita, que da a entender que el archivo de configuración debería poder modificarse y el sistema debería detectar los cambios. Nosotros para cambiar el quantum sleep y demas configuraciones en tiempo de ejecución lo hacemos desde la consola del kernel. Es válido que lo dejemos así?
Gracias!

**Comment by agustinkoszczej** [comment]
Si, nosotros también tenemos esa duda, a mi en un checkpoint me habían dicho que los archivos de configuración no los iban a cambiar, por lo que mi duda sería si entonces lo hacemos por consola que se cambie?

**Comment by fededri** [comment]
Yo tambien me di cuenta tarde, pero el enunciado dice que se tiene que cambiar en tiempo de ejecucion desde el archivo el quantum sleep. Lo hice usando la biblioteca de inotify

**Comment by fedebonisconti** [comment]
Como bien dijo @fededri, tiene que cambiar en tiempo de ejecución, y para eso pueden usar [inotify](http://man7.org/linux/man-pages/man7/inotify.7.html)!

**Comment by tferraro** [comment]
@agustinkoszczej una cosa es que no se cambien a nivel estructural y otra lo que dice en enunciado. Quedó claro lo que confirmaron los Fedes? Si es así, se puede cerrar?

Saludos!

**Comment by tferraro** [comment]
Cierro esto por inactividadd. Cualquier cosa que la duda persista, abrilo de nuevo :wink:

**Comment by marrtins** [comment]
Buenas, me quedo una duda con respecto a esto...

Nosotros le avisamos a las cpus el quantum_sleep en el handshake una vez se conectan y nunca mas.. Si detectamos cambios con el inotify, el nuevo quantum_sleep se lo daríamos a las cpus que se conecten al sistema desde ese momento en adelante. Esta bien esto o tambien hay que informar el nuevo valor a las cpus existentes? 
Saludos

**Comment by iago64** [comment]
Buenas!
Tienen que informárselo también a las CPUs existentes.

Saludos.

**Comment by marrtins** [comment]
Ok. Mil gracias
