### ISSUE TITLE
problema config_set_value

### ISSUE THREAD

**Issue by AltTomas** [sisoputnfrba/foro#780]
Hola a todos!

Estoy teniendo un problema con esa función. Mi idea es tratar a los archivos.bin de la carpeta Archivos del filesystem como configs ya que es mucho más facil para manejar.

Ahora bien, yo cree un diccionario de la siguiente manera: 
```
fileDictionary = dictionary_create();
	dictionary_put(fileDictionary, "SIZE", 0);
	dictionary_put(fileDictionary, "BLOCKS", 0);
```

Y luego lo asigne a una variable t_config:

`fileData.properties = fileDictionary;
`
Guardé el config en el archivo:

`config_save_in_file(&fileData, path);
`
y después quise setear un valor

`config_set_value(&fileData, "SIZE", "1");`

Todo se hace bien, hasta el set_value, que no hace absolutamente nada.

Cual puede ser el problema? Algún parametro mal?

Muchas gracias!

**Comment by fedebonisconti** [comment]
Buenas, cómo va?

Estás guardando el config en el archivo? Con el `config_set_value()` lo único que haces es agregar en la config ése key-value, para persistirlo en el archivo tenés que usar `config_save()` (el hermano bueno de `config_save_in_file()`) DESPUÉS de agregarlo.

Mirate un poco los [tests](https://github.com/sisoputnfrba/so-commons-library/blob/master/tests/unit-tests/test_config.c) si no queda muy claro :)

Saludos!

**Comment by AltTomas** [comment]
Perfecto! Ya pude hacerlo bien! Muchas gracias.

Otra cosa, estoy haciendo el borrar archivo del FS. Esto es lo que hago:
```

sprintf(pathFile, "%s/Archivos/%s", configuracion.puntoMontaje, path);

		fileData = config_create(pathFile);

		char** bloques= config_get_array_value(fileData, "BLOCKS");

		int var;

		int max = sizeof(bloques);

		for (var = 0; var < max-1; ++var) {

			char charBloque = &bloques[var];
			
			off_t bloque = charBloque - '0';
			
			sprintf(blockPath, "%s/Bloques/%zu.bin", configuracion.puntoMontaje, bloque);

			remove(blockPath);
			
			bitarray_clean_bit(bitarray, bloque);

			if(msync(bmap, mystat.st_size, MS_SYNC) < 0){
					printf("Error es: %s\n", strerror(errno));
				}
		}

                           remove(pathFile);
```

Esto no rompe, pero no elimina los bloques y tampoco hace el clean como debe. Me di cuenta después de hacer un print del valor de los bloques que se debe a que estos tienen cualquier cosa. Por lo que creo que lo que estoy haciendo mal es algo de las siguientes lineas:

`char** bloques= config_get_array_value(fileData, "BLOCKS");`

```
char charBloque = &bloques[var];
			
off_t bloque = charBloque - '0';
```

Pero la verdad es que no sé como puedo hacer para terminar con un off_t del valor de cada elemento del array que tiene mi archivo .bin que es, supongamos [1, 5, 3, 10, 8]

Muchas gracias!

**Comment by CarolinaPonceRodriguez** [comment]
Se me ocurre lo siguiente:
bloques es puntero a puntero, por lo cual si haces lo siguiente char * charBloque = bloques[var]
tendrias el valor de cada bloque en ese charBloque, solo restaria convertirlo al tipo que necesita bit_array_clean_bit.

Por otra parte, veo que haces un remove(blockPath); estas eliminando fisicamente el bloque? Esto es innecesario, unicamente necesitas liberarlo en el bitmap, te invito a pensarlo un poquito.

PD: Debuggear salva las papas, y mucho.
Saludos.

**Comment by fedebonisconti** [comment]
Como dijo @CarolinaPonceRodriguez, debuggear ayuda :)

Por otro lado, estoy seguro que estás haciendo algo mal cuando haces `int max = sizeof(bloques)`!

Saludos

**Comment by AltTomas** [comment]
Ya encontré el error, o mejor dicho, lo que NO estaba haciendo, que era usar atoi() para pasar de string a int (cada bloque es un string y no un char como lo había pensado).
Gracias!.
