### ISSUE TITLE
Escribir y Leer FS

### ISSUE THREAD

**Issue by sebaplawner** [sisoputnfrba/foro#781]
Buenas noches,
Estoy teniendo problemas para entender qué quieren de mi las instrucciones escribir y leer para FS.

**Contexto:**
Como todo lo que se viene manejando en el TP son números enteros y la primitiva **cpu_dereferenciar** devuelve **t_valor_variable** (que es un int) fue entendible que armáramos todas las primitivas para que manejen enteros.
La memoria además guarda todas las variables de a 4 bytes, por ser enteros. Todo bonito. Siempre pensando en bytes, pero de grupos de 4.

**Problema:**
Llegaron los nuevos ejemplos de programas ansisop y con ellos, nuevas dudas. Voy a anotarlas en items para mantener un orden.
- **leer f a 10**: Esta instrucción me dice que quiere leer del archivo en el FD f, con un tamaño de 10 bytes y guardarlo en la variable dinámica a. Hasta acá todo bien. Pero con el caso del ejemplo **copiarArchivo.ansisop** previamente no se escribe el archivo **origen**. Cómo debería interpretar eso? Error al leer un archivo vacío? Leer nada y devolver ""?
- **escribir g a 10**: Si ejecuto esa instrucción, va a ir al **t_puntero** de a y va a dereferenciar 10 veces. Si a es 100, hace 100, 101, 102... Lo que me da a pensar que pretende leer un char* de memoria pero, como antes dije, sólo puedo manejar enteros en el código ansisop, y memoria está toda preparada para funcionar con enteros. Por qué ahora pasa a querer leer texto cuando sólo puedo manejarme con enteros?

Lo que intenté para darle forma a esto fue modificar el programa ejemplo así:
`
    #!/usr/bin/ansisop

    begin
        variables a, f, g, h
        h = 101
        alocar a 100
        abrir f LEC /origen
        abrir g LEC /destino
        escribir f h 1
        leer f a 3
        escribir g a 3
        cerrar f
        cerrar g
        liberar a
    end
`

¿Qué interpreto de esto? 
- La memoria dinámica va a almacenar la información como si fuera un char* para poder llevarse bien con los archivos de FS.
- Si escribo con tamaño 1 agarro 1 int y eso lo transformo a char* para poder escribir 100 como "1", "0", "1".
- Cuando la primitiva **kernel_escribir** recibe el parámetro **void informacion** tengo que castearlo a char* y agarrar las **n** primeras posiciones, siendo n el tamaño. Lo que me trae el problema que en el primer escribir tengo que pasar de entero a char* pero en los próximos ya van a estar en char*
- La memoria funciona toda por variables enteras, los archivos de FS por caracteres ascii para poder leerlos.

¿Qué opinan de esa interpretación?
Gracias.

**Comment by iago64** [comment]
La memoria dinámica son bytes, que vos los quieras interpretar como char*, como void* o como int8_t* corre por tu cuenta, de hecho nadie asegura que en una prueba no les guardemos un número en la memoria dinámica.
el tamaño es en bytes, si te llega un int en todo caso debrias guardar 1 byte del int y no pasarlo a char y guardar el primer char.
Informacion es void porque no necesariamente van a llegarte solamente cosas del tipo char*, de hecho podriamos por ej mandarte un número y nada mas.

**Comment by calvoluciano** [comment]
Hola,
Tengo la misma duda, pero el comentario @iago64 no me quedo claro, si estamos de acuerdo en que la memoria maneja bytes, pero ansisop maneja solo variables numericas, como haríamos por código ansisop para guardar un string en un archivo?

para el código copiarArchivo.ansisop, que  tendríamos que hacer cuando se hace un leer de algo vacío para guardarlo en una variable alocada?
