### ISSUE TITLE
señal SIGUSR1

### ISSUE THREAD

**Issue by calvoluciano** [sisoputnfrba/foro#783]
Consulta,

Como ultima tarea del CPU estoy trabajando esto del SIGUSR1, en principio la funcionalidad que solo le veo a esto es de Consola linux enviar un kill(int pid, int sig) y finalizar la CPU una ves que termine las rafagas correspondientes, es esto lo esperado?

**Comment by mgarciaisaia** [comment]
> Mediante la señal SIGUSR1, se le podrá notificar a un CPU que deberá desconectarse una vez concluida la ejecución del Programa actual, dejando de dar servicio al sistema

Lo que dice el enunciado es que, cuando a tu proceso CPU le llegue la señal `SIGUSR1`, va a tener que desconectarse tras terminar de ejecutar la ráfaga actual.

Para que esa señal le llegue al proceso CPU, investigate [el builtin `kill` de bash](https://ss64.com/bash/kill.html) (podés verlo con `help kill`). No hace falta que uses [la _función_ `kill`](https://linux.die.net/man/2/kill).

**Comment by maria-angslz** [comment]
Buenas, ese kill que tenemos que usar entonces corresponde a la consola de linux? Como debería usarlo atraves de mi código, con system? es el único que conozco que me permite ejecutar comandos en la consola de linux. Saludos.

**Comment by tferraro** [comment]
Medio tarde mi respuesta :/.

Respuesta corta: Si. Cuando Mati hace mención del builtin de bash, está haciendo referencia a la consola es una consola bash :smiley: 

A paaaarte, podes usar el programa `htop`, que entre otras cosas, permite mandar señales a los procesos mediante una linda(?) interfaz gráfica en consola.

Saludos!
