### ISSUE TITLE
Cerrar archivos en FS-kernel-CPU

### ISSUE THREAD

**Issue by CarolinaPonceRodriguez** [sisoputnfrba/foro#784]
Tengo una duda que involucra a los 3 procesos. Doy un ejemplo:
-un proceso le solicita a CPU abrir un archivo hola.txt en modo escritura
-kernel recibe el path del archivo y el modo de apertura, le consulta al fs si posee dicho archivo y si lo tiene le de el correspondiente fd, lo agrega a la tabla de archivos globales y a la tabla de archivos por proceso
-si CPU hace alguna solicitud para ese fd entonces kernel lo busca en sus tablas y le manda la accion correspondiente al fs.

La pregunta es: en que momento se cierra el archivo en el fs ? Deberia generar una funcion para cerrar los archivos en el fs? ya que el cpu tiene una funcion para cerrar que le envia al kernel y no se si kernel deba enviarle al fs.
Por otra parte, que pasa en el fs si se abre el mismo archivo en modo escritura? Tendria una nueva entrada en la tabla de archivos por procesos independientemente de que el archivo fuese abierto por otro proceso. Que sucederia en el fs si "toco" un mismo archivo al mismo tiempo? Si bien tendria fd distintos el archivo es siempre el mismo.

Deberia agregar mutex en el fs para esos casos ? 

Saludos.

**Comment by iago64** [comment]
El FS es totalmente agnóstico de que un archivo esta abierto o no, eso queda a nivel del Kernel.

**Comment by CarolinaPonceRodriguez** [comment]
Ya se resolvio en issue referenciado. Cierro.

Saludos.
