### ISSUE TITLE
Validar archivo/ Abrir archivo en fs

### ISSUE THREAD

**Issue by CarolinaPonceRodriguez** [sisoputnfrba/foro#785]
Buenas, este issue tiene relacion con el #784. Como ya termine con las funciones del fs, estoy viendo la comunicacion entre CPU-KERNEL-FILESYSTEM y me surgen algunas dudas de puntos que no estan muy detallados en el tp.
El fs cuenta con 4 funciones: validar, borrar, escribirDatos y guardarDatos.
Cuando la CPU solicita abrir un archivo, en el modo que sea, kernel recibe la peticion y se la pasa al fileSystem.
El fileSytem verifica la existencia de ese archivo, y dependiendo del flag:
c: lo crea y lo deja abierto.
r: lo abre
w: lo abre
Es asi? Como en el tp no especifica una funcion de apertura en si, me marea un poco.

Saludos.

**Comment by fededri** [comment]
Yo lo que hice fue desde el kernel validar si existe el archivo, si no existe le mando crear

**Comment by CarolinaPonceRodriguez** [comment]
Gracias, pero no es lo que estoy consultando.

Saludos.

**Comment by iago64** [comment]
@CarolinaPonceRodriguez La apertura o cierre de un archivo esta asociado a algo a nivel del Kernel, es decir, para el FS el abrir o no un archivo le importa poco porque tiene una capa antes que no le manda los mensajes si no corresponde.

@fededri Ojo que si lo tenes para lectura no deberías crearlo.

**Comment by CarolinaPonceRodriguez** [comment]
Entiendo, entonces a fin de cuentas, el kernel no necesitaria que yo como FS le mande, por ejemplo, el fd de un archivo que me pidio abrir. Sino que el va a manejar "aleatoriamente" en sus tablas un valor de fd para los archivos, no sale de abrir un archivo con open() en el FS.
Supongamos el mismo ejemplo de apertura de archivo:
-El FS lo unico que validara es que exista, si no existe y tiene flag de creacion, lo crea. Esto no implica tener que realizar un open() del archivo.
-En el caso de las operaciones de guardarDatos y escribirDatos el fs las opera, no importa si abre o no el archivo en si solicitado (lo que si hay que manejar es la apertura y cierre de bloques, pero de esto, el kernel ni idea tiene).

Espero sea masomenos asi.

Saludos.

**Comment by CarolinaPonceRodriguez** [comment]
Acabo de leer algo en el TP que habia pasado por alto del kernel:

"Abrir archivo: el kernel recibira un path de archivo  y los permisos de apertura, generara un FileDescriptor y se lo devolvera  a la CPU para que continue con su ejecucion".

Osea que el kernel recibe, consulta al FS si tiene el archivo(intervienen los flags), genera el fd aleatorio y avisa a CPU.

Me lo confirman?

Saludos.

**Comment by iago64** [comment]
Efectivamente, el kernel le pregunta al FS si tiene el archivo (eventualmente si lo indica el flag lo crea) y genera el FD que le devuelve a la CPU.

**Comment by fededri** [comment]
@CarolinaPonceRodriguez  a eso último me refería.

@iago64  Claro, o sea que si por ejemplo la cpu manda abrir archivo con permisos de lectura, y el archivo no existe...tendria que devolver un error y cerrar el proceso no?

**Comment by iago64** [comment]
Efectivamente, si es lectura y no existe el archivo, no hay nada para leer :)

**Comment by CarolinaPonceRodriguez** [comment]
Gracias a todos! Cierro issue.

Saludos.
