### ISSUE TITLE
Función desconectar consola

### ISSUE THREAD

**Issue by ahufa** [sisoputnfrba/foro#787]
Buenas!

Tenemos una consulta respecto de la función desconectar consola

> Desconectar Consola: Este comando finalizará la conexión de todos los threads de la consola
> con el kernel, dando por muertos todos los programas de manera abortiva.

Debería finalizar la ejecución de TODA la consola o solo finalizan los programas que están corriendo en ese momento dando la posibilidad de iniciar nuevos programas???

Gracias!!!

**Comment by tferraro** [comment]
@ahufa como vienen con esto? Les sirvió la respuesta? Si es así, se puede cerrar?

**Comment by ahufa** [comment]
Entonces el hilo interfaz de usuario nunca se tendría que morir???

**Comment by tferraro** [comment]
El comando se llama "Desconectar Consola", eso hace alusión a que la consola se desconecta completamente del kernel, pero es desconectar, no apagar o cerrar :wink: 

Esto implicaría que podes volver a conectar la consola al kernel mandando nuevos procesos a ejecutar, y para eso necesitas que el proceso tenga una consola donde poner los comandos :)
