### ISSUE TITLE
Dudas en obtener datos del FS.

### ISSUE THREAD

**Issue by AltTomas** [sisoputnfrba/foro#788]
Hola a todos! Terminé de hacer la función de obtener datos del FS y aunque no me chilla nada ni me rompe, siento que estoy haciendo algo mal.
Antes de leer (u obtener) algún dato de X archivo, verifico que el archivo haya sido abierto (o sea la función ANSISOP lo abrió de tal manera) con el flag de read. Ahí creo que todo bien. 

Luego obtengo de un campo del archivo .bin llamado "BLOCKS" los bloques que contienen todos los datos de este archivo. 

Ahora bien, para yo saber donde empezar a leer debo fijarme en el TAMAÑO DE CADA BLOQUE y en el OFFSET que se me envió como dato. Por lo que yo haciendo floor(OFFSET/TAMAÑODEB), obtengo el numero de bloques ENTEROS que me tengo que mover ("descartar" podría decirse).

Luego con el offset, el size que me enviaron y el tamaño del bloque, calculo lo que le voy a mandar a la función PREAD que es la que va a leer de cada bloque necesario.

Ahora bien, acá va la parte donde creo yo que estoy haciendo mal las cosas:

(todo esto es dentro de un while que hace otras cosas, mayormente cuentas)

`pread(fd, buffer, readSize, archivo.offset);`

Acá yo leo del bloque X.bin y lo guardo en un buffer. Inicializado como:
 `void * buffer = malloc(metadata.bloque_size);`
Siendo readSize lo que yo calculo y el offset (también se calcula el offset final si este es mayor al tamaño de los bloques)

`string_append(&dataObtenida, buffer);`

Acá esta mi mayor duda, si realmente está bien esto. dataObtenida es un void * sin más.
Con esto lo que yo quiero hacer es en dataObtenida ir juntando cada cosa que leo y guardo en buffer, y así crear un "chorizo" de bytes de lo que leí para poder ser enviado luego al kernel. Es esta la manera correcta? Más allá que no rompe ni chilla ni nada y la verdad que intenté debuggearlo pero sinceramente no logro encontrarle la vuelta a los valores que me va dando.

Básicamente es lo único que nos queda de FS y no logro darme cuenta si es correcto eso último, si estoy usando las funciones correctas o hay maneras más optimas de lograr esto. Si podrían echar un poco de agua para aclarármelo, estaría inmensamente agradecido!.

Gracias!.

**Comment by CarolinaPonceRodriguez** [comment]
Hola que tal para poder ayudarte creo que es necesario que digas que funcion de read estas tratando de usar, si es la syscall o el wrapper, los parametros que reciben read() y fread() son un poco distintos.
Mas alla de eso, ambas con lo que leen completan un buffer de tipo void *, hasta ahi vamos bien, pero si vos tratas de hacer un string_append() de un void * te va a estallar por todos lados porque la especificacion de dicha funcion diche que recibe como parametros dos char *.
El char * tiene implicito un \0. Es como si trataras de hacer un printf("%s, buffer), como buffer es void * va a tratar de buscar el \0 pero no lo va a encontrar y te va a arrojar basura de mas.

No verifique la logica de lectura, disculpas, pero la idea de completar un buffer y mandarlo todo de una con todo lo que debias leer de todos los bloques es la manera correcta creo yo.

Pista: quiza para ver que tu buffer se complete bien, te conviene hacer un write en algun archivo.. por lo que dije mas arriba.

Saludos!.

**Comment by AltTomas** [comment]
Lo pude arreglar, el problema era que necesitaba inicializar el dataObtenida con un "string_new" y el buffer no hacerle un  maloc al principio si no cada vez que entraba en el while ya que si lo que leía era menor a lo asignado al hacer el append, se escribian cosas de más.
