### ISSUE TITLE
Iniciar filesystem-documento de pruebas

### ISSUE THREAD

**Issue by CarolinaPonceRodriguez** [sisoputnfrba/foro#789]
Buenas que tal estuve viendo el documento de pruebas y tengo algunas dudas con el fs. Si bien para probar el fs me genero el propio a "manopla", ustedes van a subir un fs para las pruebas? Porque sino, esto implicaria que agregue a mi codigo funciones que inicien un filesystem, ejemplo, que creen todos los bloques.bin o crear el bitmap.bin y levantarlo y asi, obviamente seria un fs "limpio" y no tendria demasiado sentido para probar.

Saludos.

**Comment by alejandrog87** [comment]
Yo tuve que hacer eso que decís para generarme mi propio fs y probar, después de un par de pruebas ya no era un fs limpio .  Igualmente me sumo al pedido, estaría bueno que suban un fs "certificado/homologado" con el cual realizar las pruebas :D.

**Comment by alejandrog87** [comment]
Alguna novedad sobre este issue? Vamos a tener un fs de "prueba" o lo vamos a tener que llevar nosotros? Pregunto porque como dice la autora del issue se deberian agregar unas funciones de inicializacion/creación de bitmap/bloques. 
Gracias

**Comment by gonziesc** [comment]
Buenas! lo subieron hace unos días:
https://github.com/sisoputnfrba/ansisop-parser/tree/master/programas-ejemplo/evaluacion-final-esther/FS-ejemplo

**Comment by gonziesc** [comment]
Hace unos días subieron un ejemplo de FS al repositorio del parser:
https://github.com/sisoputnfrba/ansisop-parser/tree/master/programas-ejemplo/evaluacion-final-esther/FS-ejemplo
Yo estoy probando con ese.

**Comment by tferraro** [comment]
Holis, les pido perdón por haber colgado con esto. Efectivamente como dicen :point_up_2:, el filesystem de ejemplo está subido junto con las pruebas.

Saludos!

**Comment by iago64** [comment]
@CarolinaPonceRodriguez hay un FS subido en el repo del parser que es el que se usa en las pruebas.
Teniendo en cuenta eso se puede cerrar el issue?

**Comment by tferraro** [comment]
Cierro el issue asumiendo que se solucionó la duda. Cualquier cosa que la duda persista, no duden en volverlo a abrir!
