### ISSUE TITLE
Pruebas Base EditarFS

### ISSUE THREAD

**Issue by picollomartin** [sisoputnfrba/foro#790]
Hola! 

Mi consulta es acerca de la siguiente prueba base:

> begin
	variables a, b
	alocar a 500
	abrir b LEC /unArchivo
	leer b a 10
	*a = 70
	escribir b a 10
	cerrar b
	liberar a
end

No estoy seguro de lo que quieren que escribamos en el archivo, porque según lo que estuve viendo el parser va dereferenciando los valores a partir de la posición de la variable que le pasamos y no desde la posición del heap que es el valor de la variable a (el t_puntero devuelto por alocar). Me podrían aclarar eso?

Saludos y Gracias!

**Comment by picollomartin** [comment]
Para sumar claridad me refiero a esta [linea](https://github.com/sisoputnfrba/ansisop-parser/blob/master/parser/parser/parser.c#L188) del parser. Ahí no debería dereferenciar ese puntero, que contiene la dirección donde arranca el heap para esa variable ?

Saludos!

**Comment by jazcarate** [comment]
Perdón, no entiendo la pregunta :see_no_evil: 
La idea de la prueba es la de leer un archivo, cambiarle _"al azar"_ un par de bytes, y volver a guardarlo.
Particularmente *qué* cambia, es medio incomodo de leer y transformar _(porque endian-nes, pasar decimal a binario, y esas cosas horribles)_.

Con comentarios, sería:
```
begin
    variables a, b
    alocar a 500
    abrir b LEC /unArchivo
    leer b a 10 #Pone los primeros 10 bytes del archivo en memoria
    *a = 70 #cambia algo de ese pedazo en memoria.
    escribir b a 10 # vuelve a guardar en el archivo la memoria que leyó y editó
    cerrar b
    liberar a
end
```

¿Ayuda en algo?

**Comment by picollomartin** [comment]
El problema lo tengo con la [linea del parser ](https://github.com/sisoputnfrba/ansisop-parser/blob/master/parser/parser/parser.c#L188) que comenté más arriba, porque esa linea determina donde arranca a leer la para armar la información que se le pasa a escribir (que en este caso esta en el heap). 
Supongamos el caso que la variable (a) esta al principio del stack (offset 0 pagina 2) con el valor 880 (que corresponde al inicio del bloque del heap que reservó), lo que veo que hace es que arranca desde el offset 0 y no desde el 880 (como entiendo que debería hacer).
Lo que me lleva a pensar que ese 70 que estamos modificando no va a afectar en nada de lo que se escriba en el archivo, ya que arranca a leer en otro lado y no va a buscar a la posición del heap.

Me explico?

**Comment by ziggylineous** [comment]
parece como lo que pasaba en leer en #772, donde al leer me llegaba la dirección de la variable del stack en vez del valor de la var (posición en memoria dinámica). Ahí lo arreglaron con _operar en vez de _obtenerPosición. No se puede hacer igual acá? (de última, si quiero la posición de una var del stack uso &a)

En una de las pruebas para anotarse, escribirFS.ansisop, esto nos va a pasar.
```
begin
  variables a, f
  alocar a 100
  abrir f LE /archivo.bin
  a*=88              # corregir *a = 88
  escribir f a 10
  # ...
end
```

**Comment by jazcarate** [comment]
https://github.com/sisoputnfrba/ansisop-parser/pull/25 😇

**Comment by picollomartin** [comment]
Hola buenas podrían mergear este PR en el repo del parser, así lo damos por cerrado al tema?
