### ISSUE TITLE
prints n imprime los bytes al reves? (cuando se printea algo leído desde archivo)

### ISSUE THREAD

**Issue by ziggylineous** [sisoputnfrba/foro#791]
estoy probando leerFS pero con lorem.txt en vez de de archivo.bin (porq escribir archivo.bin parece escribir raro #790). leerFS hace:

```
alocar a 100
abrir f LE lorem.txt

leer f a 10
prints n *a
```

lorem.txt empieza con "Lorem ipsum dol...". prints n trata de imprimir "Lore" como número, que sería: 1282372197. Pero me printea 1701998412, que son los bytes de 1282372197 al reves

**Comment by ziggylineous** [comment]
probe armar el archivo.bin con 4 bytes, o sea, un número:

`00 00 00 10` 

(En decimal es 16). Pero `prints n *a` imprime: `268435456`, que probé con bless hex editor y es
`10 00 00 00`, o sea, el 16 de arriba al reves.

Puede ser el string esta grabado o leido al reves? y después quiere tratarlo como int y queda al reves? Alguno probó esto? (crear archivo bin para que se le asigne el bloque, abrir el bloque con editor hexadecimal bless hex y ponerle un numero y despues probar que imprime en Consola)

**Comment by jazcarate** [comment]
El _problema_ con el que te encontras, es que por _[razónes](https://en.wikipedia.org/wiki/Endianness)_ los bytes no se guardan en el orden que uno realmente espera. No es un problema. No se espera que AnSISOP (lenguaje limitado a entender enteros) pueda leer y escribir archivos con texto, ni interpretarlos.

**Comment by ziggylineous** [comment]
gracias
