### ISSUE TITLE
SW alternativo para Hamachi

### ISSUE THREAD

**Issue by fpatalagoity** [sisoputnfrba/foro#792]
Buenas! Estuvimos intentando probar el TP con Hamachi pero la cuenta trial de LogMeIn de varios de nuestro grupo expiró y no podemos usarlo más en esa version. ¿Conocen algún SW alternativo que sea "simple" de instalar y configurar? Sabemos que lo ideal es probar el TP en los laboratorios de Medrano, pero por lo general por la noche (las veces que fuimos) estaban repletos, por ese motivo esta pregunta.

Gracias y buen domingo!

**Comment by mgarciaisaia** [comment]
¡Aloha!

No lo probé, pero la internet dice que teamviewer lo hace.

http://www.smartpctricks.com/2013/05/how-to-setup-configure-free-vpn-virtual-private-network-with-team-viewer-vpn-client-software.html

El post parece medio medio, pero con suerte te sirve de punta para seguir
buscando.

**Comment by fpatalagoity** [comment]
Gracias! Acabamos de descubrir que no era por la versión trial que Hamachi no nos funcionaba bien. Era por la red de wifi de la facu...
Desde nuestras casas pudimos conectarnos. 

Gracias nuevamente! Saludos
