### ISSUE TITLE
Problema "dereferenciando" - Heap 

### ISSUE THREAD

**Issue by digerzo** [sisoputnfrba/foro#793]
Buenas, como va?

Estoy teniendo un problema a la hora de "dereferenciar" los punteros del heap. Suponiendo que corro el siguiente ansisop:

begin
    variables a,b
    alocar a 50
    alocar b 30
    *a = 3
     liberar b
     liberar a
end

Lo que me esta pasando, es que supuestamente cuando llega a la linea `*a = 3` tendria que traerme el valor que esta almacenado dentro de a (que es el puntero que reserve en `alocar a 50`) pero en ninguna primitiva lee el *, me lo interpreta como si fuese un simple `a = 3`. Tambien probe tanto` *a = 3 ` como, ` a* = 3`

La pregunta es: ¿Como puedo diferenciar si la variable que estoy leyendo (a) es un puntero, ya que el parser no lo esta identificando?

Quizas estoy haciendo mal algo en otro lugar, asique cualquier sugerencia es bienvenida.

Muchas gracias.

**Comment by jazcarate** [comment]
Buenas, ahí agregué [el test de `*x=3`](https://github.com/sisoputnfrba/ansisop-parser/compare/c5d670d48cae...57c1835eddc4), donde en [el trace](https://travis-ci.org/sisoputnfrba/ansisop-parser/builds/249364228#L265-L270) dice:
```
[TRACE] 16:07:54:741 TEST/(3711:3711): Obtener posicion variable [x]
[TRACE] 16:07:54:741 TEST/(3711:3711): 	devuelve [0xa]
[TRACE] 16:07:54:741 TEST/(3711:3711): Dereferenciar [0xa]
[TRACE] 16:07:54:741 TEST/(3711:3711): 	devuelve [11]
[TRACE] 16:07:54:741 TEST/(3711:3711): Asignar a [0xb] el valor [3]
```
_(con un poco de cariño, el 11 que devuelve es el `0xb` que toma como primer parámetro el asignar)_

A diferencia del test que está un poquitín más arriba que _(simplificandolo)_ hace `x=3` y el trace diría:
```
[TRACE] 16:07:54:741 TEST/(3711:3711): Obtener posicion variable [x]
[TRACE] 16:07:54:741 TEST/(3711:3711): 	devuelve [0xa]
[TRACE] 16:07:54:741 TEST/(3711:3711): Asignar a [0xa] el valor [3]
```

**Comment by digerzo** [comment]
Perfecto! Ya lo pude hacer andar, ademas no estaba seguro de la sintaxis.

Gracias, cierro el issue.
