### ISSUE TITLE
Consulta STACK SIZE

### ISSUE THREAD

**Issue by santiagovarela86** [sisoputnfrba/foro#794]
Buenos días,

Tenemos una duda con respecto a la prueba de StackOverflow.ansisop.

~~En el documento de Prueba Base indica que el límite del Stack es 2. Esto significa que el Stack puede llegar a tener un máximo de 2 contextos? O Mejor dicho a qué se refiere el "2" en este parámetro?~~

Releyendo el TP STACK_SIZE indica que es el número de páginas máximo que debe ocupar el Stack.

Ahora mi duda es la siguiente:

1) ¿En las páginas de Stack va el Stack completo o solo van las variables a las que apunta el Stack?

Hoy en día nosotros tenemos la estructura del Stack en el PCB, que va y viene entre CPU y Kernel de forma serializada.
Y dentro de la estructura del Stack, hay, entre otras cosas, hay una lista de Variables y una lista de Argumentos. Estas variables están en páginas de memoria.

Saludos y gracias.

**Comment by ziggylineous** [comment]
Nosotros hicimos así: en las págs del stack en memoria están los valores de las variables que el programa va definiendo. En el índice de stack en cpu están las pos en memoria de las vars
