### ISSUE TITLE
Escribir archivo

### ISSUE THREAD

**Issue by agustinkoszczej** [sisoputnfrba/foro#795]
```
begin
  variables a, f
  alocar a 100
  abrir f LE /smallFile.bin
  a*=88
  escribir f a 10
  cerrar f
  liberar a
end
```
Tengo una duda probando este ansisop de las pruebas que mandaron:
1° Si el archivo smallFile.bin lo tenemos que creer nosotros, porque al abrir solo en Lectura y Escritura y no existir siempre va a tirar error de que no existe
2° La parte de `a*=88` no deberia ser `*a=88` porque sino solo se asigna 88 a la variable, en vez de al heap
3° Cuando se llega la instruccion `escribir f a 10`, llamo a la primitiva de 

> _**obtener direccion**_

 de la variable a, y después 

> _**dereferencio**_ diez veces de esa posición obtenida

Pero dereferenciar lee de a 4 bytes (porque siempre se usaba para leer valor de variables ya que no recibe ningún tamaño de lo que va a leer, solo una posición), entonces por ejemplo derefencia primero de las posiciones 0, 1, 2, 3 de esa dirección de la variable 'a', después esa misma dirección corrida 1 byte, osea 1, 2, 3, 4, luego 2, 3, 4, 5 y así 10 veces por ese `escribir f a 10`, acumulandome basura. Entonces mi mayor duda es eso, cual es el objetivo de esta (y basicamente todas) las test de cuando escribe, porque en otras tests también escribe cosas de un tamaño mayor al que puede soportar una variable (4 bytes).
Gracias!

**Comment by nicozar95** [comment]
Hola!
Si en 1 y 2 era un error nuestro, ya esta arreglado.
Sobre 3: El objetivo de esto es ver que ustedes puedan escribir el tamaño correspondiente y no solo los bytes que establecimos ¿Va a escribir basura? Si eso es lo que queremos, el objetivo de este test es poder ver que el archivo crecio en tamaño.

**Comment by tomasdepi** [comment]
Hola, que tal?
¿Puede ser que en creaGigante.ansisop pase similar? el archivo también tiene que crearse, faltaría el flag C. Asi luego se escribe con un offset muy grande, haciendo que se le reserven todos los bloques y poder evaluar el objetivo de ese test.

Saludos, gracias

**Comment by nicozar95** [comment]
@tomasdepi 
Si, y gracias por notar el error que habia. En ese caso movias el puntero a una pocision muy larga y despues escribias. Eso lo discutimos en #768 que no se iva a evaluar.

Ahora deberia escribir un monton de bytes basura.

**Comment by tferraro** [comment]
@tomasdepi te sirvió la respuesta de Nico? Si no quedan más dudas, se puede cerrar este issue? Gracias!

**Comment by tomasdepi** [comment]
Si si, quedo en claro el tema de los archivos. Gracias. Este issue no lo abrí yo, así que no puedo cerrarlo jajaja

Saludos.

**Comment by tferraro** [comment]
Genial!! @agustinkoszczej vos en que andas? Pudiste resolver la duda?
