### ISSUE TITLE
Estadistica de resultados

### ISSUE THREAD

**Issue by jlusnich** [sisoputnfrba/foro#796]
Buenas,

Les hacemos una pregunta para todos, no solo para los ayudantes, para ver que opinan.
Nos estamos cuestionando si "Hora de inicio de ejecución" de un programa se refiere a:

A) Cuando el Kernel lo pone en Cola de News.
B) Cuando el Kernel se lo asigna por primera vez a una CPU.

Si bien es simplemente cambiar de lugar dos lineas de codigo, queremos asegurarnos para cumplir con el contenido mínino de _Al finalizar un programa se muestran correctamente las estadísticas de su ejecución._

Gracias

**Comment by afilgueira** [comment]
Hola, a fines practicos no te va a cambiar demasiado (pensa que es imperceptible para el ojo humano). 

A fines del tp, yo iria con la opcion A, pensando en que podrias tener las CPUs ocupadas durante un buen tiempo, pero para el usuario final "el programa ya arranco". 

Saludos!
