### ISSUE TITLE
Borrado de archivos kernel

### ISSUE THREAD

**Issue by fededri** [sisoputnfrba/foro#797]
https://github.com/sisoputnfrba/foro/issues/773
Vi este issue  y otro mas que estaba por ahi, por lo que entiendo entonces si uno o mas procesos tiene un archivo abierto el mismo no puede ser borrado. El proceso que lo quiera borrar tiene que CERRARLO antes de borrarlo, por ende la entrada en la tabla de paginas se borra y el file descriptor deja de tener validez, cuando mande el borrar como va a saber el kernel cual es el archivo?

**Comment by nicozar95** [comment]
Aca hay un tema, el parser recibe un fd para borrar el archivo. Si vos cerraste tu archivo, asumiendo que cerraste todos los fd, entonces no tenes que fd borrar. ¿Como se borra entonces?

Habia una contradiccion en el parser  frente al enunciado que lo aclaramos en la errata:

> En el enunciado se establece que para borrar un archivo se necesita que no tenga entradas en la tabla de archivos globales, sin embargo se contradice con la primitiva del parser para borrar archivos que requiere un fd. Para solucionar esta contradiccion. Si un programa ansisop requiere borrar un archivo, debe ser el único que lo tiene abierto; osea que el atributo de cantidad de open en la tabla de archivos va a estár en 1.

**Comment by fededri** [comment]
Gracias, no habia visto que actualizaron la errata. Cierro entonces
