### ISSUE TITLE
creaGigante

### ISSUE THREAD

**Issue by ziggylineous** [sisoputnfrba/foro#798]
`escribir f a 332280` 
Esto va a querer acceder a memoria en paginas q el proceso no tiene a través de la primitiva `dereferenciar`. Nuestra memoria devuelve algo como "no pude leer" cuando le mandas una pág q el proceso no tiene. En `dereferenciar` cuando esto nos pasaba poníamos un exit code en -5 (error memoria). Pero esto termina el programa. Lo arreglo haciendo q `dereferenciar` retorne 0 y no termine el programa?

**Comment by ziggylineous** [comment]
Puede ser que lleve más de 1/2 hora ejecutar? a alguien le pasa así?

**Comment by picollomartin** [comment]
Estamos en la misma tarda mucho en crear el string para escribir...

**Comment by picollomartin** [comment]
Estamos en la misma tarda mucho en crear el string para escribir...

**Comment by ziggylineous** [comment]
gracias

**Comment by nachoperez714** [comment]
bump

**Comment by ziggylineous** [comment]
en la prueba probaron con muchos menos bytes. Deberían cambiar el ansisop
