### ISSUE TITLE
Problema metadata_desde_literal

### ISSUE THREAD

**Issue by ivodan** [sisoputnfrba/foro#799]
Buenas

Probando las primitivas del parser, me encontre con que la funcion metadata_buscar_etiqueta me estaba devolviendo -1 (lo que supongo significa que no encontro la etiqueta). Esto me hizo volver unos pasos atras y verificar los valores que me devolvia la funcion metadata_desde_literal. Probe por ejemplo con el script stackOverflow y me devuelve lo siguiente:

> metadata->etiquetas_size: 12.
> metadata->etiquetas: f.
> metadata->cantidad_de_etiquetas: 0.

A simple vista me llama la atencion que en el serializado de etiquetas este solo 'f', cuando existe la funcion 'g', y tambien que la cantidad de etiquetas sea 0. Los demas atributos del struct son correctos, en principio me estarian fallando los que tienen que ver con las etiquetas.

Espero alguna respuesta que me guie un poco, saludos!

**Comment by lamasnicolas** [comment]
@ivodan Nosotros estamos teniendo el mismo problema, metadata_buscar_etiqueta nos devuelve un puntero que apunta a un lugar imposible

**Comment by juanignaciog** [comment]
Hola
tengo entendido que en ese script cantidad_de_etiquetas tiene que ser 0, creo que te estas confundiendo con cantidad_de_funciones que me da 2 a mi. Fijate si a vos también.
Con lo de metadata->etiquetas no se si quisiste decir esto con lo que pusiste, pero acordate que ese campo es un stream de palabras e ints (la direccion de la etiqueta/funcion) separadas por '\0' por eso si lo lees normal (el campo esta definido como un char*) solo te lee la primer palabra, tendrías que ir recorriendo todo el atributo sumando posiciones para ver si de verdad esta 'g'

Avisame si entendí algo mal o si te cambio algo lo que dije, saludos

**Comment by mgarciaisaia** [comment]
Bueno, terminamos discutiendo esto en #805. Peguenle una mirada a eso y avisen si sigue sin solucionar el problema.

**Comment by ivodan** [comment]
Genial, cierro issue!
