### ISSUE TITLE
Error malloc (assertion failed)

### ISSUE THREAD

**Issue by maurocostabella** [sisoputnfrba/foro#801]
Buenos dias, al ejecutar este codigo:
tipoPCB* recibir_pcb(int socketCPU){
	int tamanoPCB, aux, i,j, elemento;
	printf("Recibiendo pcb1\n");
	recibir_int(socketCPU,&tamanoPCB);
	printf("tamano pcb %u\n",tamanoPCB);
	tamanoPCB = tamanoPCB - sizeof(int);
	printf("Recibiendo pcb2\n");
	tipoPCB* pcb = malloc(tamanoPCB);
	printf("Recibiendo pcb3\n");
...

se me imprimir esto;
Recibiendo pcb1
tamano pcb 124
Recibiendo pcb2
...
y despues... me tira este error:
kernel: malloc.c:2372: sysmalloc: Assertion `(old_top == (((mbinptr) (((char *) &((av)->bins[((1) - 1) * 2])) - __builtin_offsetof (struct malloc_chunk, fd)))) && old_size == 0) || ((unsigned long) (old_size) >= (unsigned long)((((__builtin_offsetof (struct malloc_chunk, fd_nextsize))+((2 *(sizeof(size_t))) - 1)) & ~((2 *(sizeof(size_t))) - 1))) && ((old_top)->size & 0x1) && ((unsigned long) old_end & pagemask) == 0)' failed.
Abortado (`core' generado)

no entiendo por qué si es un simple malloc con un int adentro... gracias

**Comment by maurocostabella** [comment]
cuando lo corro con valgrind no me tira ese error... sigue la ejecucion normal

**Comment by tferraro** [comment]
Holis,
Tratá de no poner código sin formatear porque si fuera un poquito más complicado el código no se hubiera entendido nada :stuck_out_tongue: 

Fijate que rompe en un malloc y yo veo que haces `recibir_int(socketCPU,&tamanoPCB);` no se que estarás haciendo adentro de esa función, pero _estás seguro que lo que está asignado en tamanoPCB es un numero **entero positivo**_?

Valgrind en el momento exacto te dice que paso pero no necesariamente hace que explote el proceso, justamente porque es una herramienta para chequear estos problemas.

Saludos!

**Comment by maurocostabella** [comment]
Sisi fijate que esta definido como un int y cuando lo muestro con print me muestra el numero... (probe nuevamente con %d por la dudas)
por otro lado si yo pongo un int directamente, por ejemplo "tipoPCB* pcb = malloc(200);" tambien me tira el mismo error

**Comment by maurocostabella** [comment]
![sin titulo](https://user-images.githubusercontent.com/22394727/27919757-e1e5d592-6248-11e7-8168-368fff1a5a92.png)
Esto me muestra valgrind...

**Comment by tferraro** [comment]
[Pics or didnt happen](http:/faq.utn.so/valgrind)

**Comment by maurocostabella** [comment]
si... me puse a hacer eso, me voy a fijar de arreglar los errores y ver si me lo sigue haciendo

**Comment by maurocostabella** [comment]
corregi todos los errores de valgrind y anduvo todo bien, perdon.

**Comment by tferraro** [comment]
Tranqui :wink: Si bien es irónico que mandaste una imagen y mi frase quedo medio fuera de lugar jaja, la idea era que usen un poco algunos recursos que tenemos, aunque medio escondidos y no taaan a la vista, que es infinito más rápido que tratar de dilucidar el problema de una máquina a otra.

Cualquier duda que tengas, incluso con el doc en si, plasmalas en el foro que nos pueden servir para mejorar el material :smile:
