### ISSUE TITLE
Problema creaGigante

### ISSUE THREAD

**Issue by nachoperez714** [sisoputnfrba/foro#802]
👋 ¡Hola!
 En el Script creaGigante:
begin
  | variables a, f
  | alocar a 100
  | abrir f LEC /largeFile.bin
  | *a=88
  | escribir f a 332280
  | cerrar f
  | liberar a
  | end

Se supone por la consigna que guarda en FS ese tamano gigante ocupando todo el FS. Ahora, escribir pone en f esa cantidad gigante de lo que se encuentra en a, pero ese tamano gigante es mas de lo alocado y MP no tiene que permitirle meterse a eso y por eso rompe. Es un problema de la consigna o no estamos entendiendo?

**Comment by ziggylineous** [comment]
a mí me pasaba eso (#798). no respondieron e hice que no setee un exit code -5 (error memoria) sino q devuelva 0. Después de eso funcionó, pero no termina más.

**Comment by nachoperez714** [comment]
Si pero si tira ese error no puedo completar la prueba que me piden que es llenar todo el filesystem. O como hicieron?

**Comment by ziggylineous** [comment]
nosotros vemos qué responde memoria al pedido de leer (una página que no existe para el proceso). La memoria puede decirnos "no pude leer" o algo así. Antes seteabamos error code = ERROR_MEMORY y terminaba el programa. Ahora no seteamos ese error y retornamos 0 (en dereferenciar).

**Comment by nachoperez714** [comment]
Si si la parte de hacerlo tirar error la entiendo. Pero si tiramos ese error nunca vamos a cumplir esta consigna: 

> Ejecutar el script creaGigante.ansisop y controlar que se crea un archivo que ocupa
todos los bloques del FS, para ello ejecutar un creaArchivo.ansisop y verificar que el
script falla por no poder crear el archivo por falta de espacio.

y queria saber si algun @sisoputnfrba/ayudantes me podia decir si era un error de consigna o como hacemos sino

**Comment by ziggylineous** [comment]
otra q se me ocurrió pero me dio paja es antes de escribir alocar un monton de espacio, un loop con alocar seria 300 000 / frame size veces. ahí el proceso va a tener paginas y no tira error

**Comment by tferraro** [comment]
Holis!

Les pido que me banquen un rato que ando revisando las pruebas y charlando con otros ayudantes y les traigo la posta. Cosas que puedo confirmarles: No queremos 300_000 operaciones y el tiempo que viene acompañado; ni tampoco que tengan que adaptar el codigo si hay algo que no les cierra.

Peace out!

PD: Claramente son una versión beta porque muchas veces se nos escapan cosas y siempre las tuneamos de acuerdo a como venga la mano (a veces se pueden resumir incluso para optimizar el tiempo).

**Comment by iago64** [comment]
Buenas!!

Ya que andan testeando, les pido si por favor pueden tirar una pruebita con un nuevo posible candidato al crearGigante?

`
begin
	variables a, f, b, i, u, c
	alocar a 100
	abrir f LEC /largeFile.bin
	:foralocar
	i=0
	u=333
	alocar b 100
	i=i+1
	c=u-i
	jnz c foralocar
	escribir f a 332280
	cerrar f
	liberar a
end
`

La idea ahora es que se reserve la memoria necesaria para el proceso y después intente grabar el archivo.
Eventualmente puede tardar muchísimo tiempo y lo se pero la idea es ver si asi no les rompe y veremos de achicar un poco el FS para la prueba.

Saludos.-

**Comment by picollomartin** [comment]
Hay que agrandar memoria para que este script funcione, con 100 marcos de 256 bytes (como esta la configuración de la prueba) no te alcanza. No pueden usar un FS más chico para esta prueba?

**Comment by iago64** [comment]
@picollomartin Si si, me olvide de aclarar que agranden la memoria, estoy viendo como achicar el FS para que nos de una prueba que no tarde una vida

**Comment by calvoluciano** [comment]
Hola,

Finalmente cual es la resolución al creaGigante, en mi caso la cpu se me cae no veo como resolverlo.

En mis dereferenciar devuelvo 0 ante una determinada posición donde ya la memoria no me devuelve okey de lo que pido, luego cuando hago un memcpy del puntero void informacion con el tamanio indicado me da Segmentation Fault.

Cual es la respuesta esperada a este script?

**Comment by ZabreLight** [comment]
Hola, me adhiero a la pregunta. En nuestro caso también salta error en memoria. Intentamos probar como respondería FS hardcodeandolo, pero no sabemos si lo que hace el script es guardar un buffer muy grande que ocupe todo los bloques del FS, o si offsetea todos los bloques y en los últimos escribe algo pequeño. Así mismo, si fuese lo primero, a nosotros nos salta un error del memcpy cuando intentamos copiar una parte del buffer inmenso en un bloque. Nos genera un core interno. Si probamos con menos bloques y el buffer es de alrededor de 700Bytes, nos funciona perfecto. En caso de que la respuesta fuese offsetear los bloques FS responde bien, pero al correr el .anisop rompe por memoria. Como seria el script final para la prueba?

**Comment by mgarciaisaia** [comment]
:wave: Con un poquito de suerte, para el mediodía les tenemos el script corregido. El objetivo de la prueba está claro: probar qué pasa con el sistema cuando se llena el FS.

> Ejecutar el script `creaGigante.ansisop` y controlar que se crea un archivo que ocupa todos los bloques del FS, para ello ejecutar un `creaArchivo.ansisop` y verificar que el script falla por no poder crear el archivo por falta de espacio.

Lo más probable es que terminemos reservando un único bloque, de tamaño moderado (los 100 bytes que hay en el script actual, ponele), y lo escribamos repetidas veces en el archivo, hasta llegar a un tamaño que sepamos que llena el disco. Para eso, seguramente usemos `buscar` para mover el cursor del archivo a una posición que nos sirva, y un loop con una etiqueta + `jnz` como en el script que compartió @iago64 hace un par de comentarios.

Si alguien quiere escribirse su propio script que llene el disco, sientanse más que libres de compartirlo por acá.

¡Un abrazo!

**Comment by mgarciaisaia** [comment]
Chicos, ¿me pueden confirmar si este script funciona y hace más o menos lo que esperamos?

```
begin
  variables a, f, c, i, t

  # 332280 bytes de FS son 3692 bloques de 90 bytes
  # reservo 91 para no buscar fuera del archivo
  t=91
  i=3692
  # reservo el bloque que voy a copiar
  alocar a t
  *a=88

  # abro el archivo destino
  abrir f LEC /largeFile.bin
  
  c=0
  
  :escribeotro
  escribir f a t
  i=i-1
  c=c+1

  # me muevo al byte anterior al siguiente bloque de 90
  buscar f (c*90 - 1)

  # loopeo
  jnz i escribeotro

  # cleanup
  cerrar f
  liberar a
end
```

**Comment by PacoErik** [comment]
Hola, el script que diste no podría funcionar debido a que AnSISOP no soporta la operación de producto (el problema justamente lo causa la línea  `buscar f (c*90 - 1)`).

Había una vieja versión de este script creaGigante.ansisop que consistía en mover el cursor a un lugar muy lejano de modo tal que al escribir, causaría que el archivo creado ocupe todos los bloques restantes en el FS. Este viejo script estaba bueno ya que no era necesario tener tantas iteraciones y no nos quita tanto tiempo.

Lo modifiqué un poco de modo que encajara con el FS de prueba que dieron hace no mucho tiempo,

Los cálculos realizados son: 
- Comenzando con **583 bloques ocupados**, se obtienen los bloques libres (5192 - 583) = **4609 bloques libres**
- Luego, multiplicamos los bloques libres por el tamaño de cada bloque para obtener la posición extrema (en la cual no se podría escribir ya que los bloques comienzan con el índice 0): 4609 * 64 = **294976 nth posición**
- Vamos a escribir 10 bytes, por lo que le restamos a esa posición 10 unidades y así obtenemos la posición a la cual debemos mover el cursor: 294976 - 10 = **294966 nth posición**

Y el script resultante, creaGigante.ansisop, sería:

```
begin
 variables a, f
 alocar a 100
 abrir f LEC /largeFile.bin
 buscar f 294966
 *a=88
 escribir f a 10
 cerrar f
 liberar a
end
```
Y luego se puede verificar con el comando `xxd -b Bitmap.bin` que todos los bloques restantes fueron ocupados (se ve un archivo lleno de **1**s).

**Comment by mgarciaisaia** [comment]
Mala mía, no recordaba el temita del producto. De todos modos, se podría reemplazar por un acumulador y una suma fácilmente.

El problema con el script que proponés es que en #768 habíamos decidido que es comportamiento no determinado hacer un `buscar` más allá del tamaño actual del archivo.

Entonces, lo podemos llegar a usar en los grupos en los que eso funcione (si el de ustedes cumple, groso), pero como script oficial no nos sirve.

Una nueva versión, sin multiplicar, sería esta:

```
begin
  variables a, f, p, i, t

  # 332280 bytes de FS son 3692 bloques de 90 bytes
  # reservo 91 para no buscar fuera del archivo
  t=91
  i=3692
  # reservo el bloque que voy a copiar
  alocar a t
  *a=88

  # abro el archivo destino
  abrir f LEC /largeFile.bin

  # p apunta siempre al byte anterior al nuevo bloque de 90
  p=-1
  
  :escribeotro
  escribir f a t
  i=i-1

  # adelanto 90 bytes, al byte anterior al siguiente bloque
  p=p+90
  buscar f p

  # loopeo
  jnz i escribeotro

  # cleanup
  cerrar f
  liberar a
end
```

**Comment by calvoluciano** [comment]
Recien probe el script y en la instruccion,

p=-1

el parser invoca la primitiva obtenerPosicionVariable pero esta viniendo vacio el argumento de la funcion (t_nombre_variable identificador_variable) entonces no puedo obtener la posición de mi stack, para esa variable no me paso en ninguna prueba esto hasta ahora.

**Comment by PacoErik** [comment]
Cambialo por:
p = 0
p = p - 1
Y echate una siesta porque va a tardar un siglo en terminar el script :P

**Comment by mgarciaisaia** [comment]
@PacoErik pero... ¿termina? ¿Lograste que funcione?

**Comment by calvoluciano** [comment]
Lo tengo corriendo todavia!!! ja

**Comment by PacoErik** [comment]
@mgarciaisaia eventualmente termina. Lo estuve corriendo por más de 30 minutos y solo llegó a ocupar ~30% de los bloques del FS y .. 😴 
Habría que optimizar el programita para que no escriba de a tantos bytes. Con 2 bytes sería suficiente, uno para el fin de bloque y el otro para el bloque consecuente (aún así serían demasiadas iteraciones 🤒 )

**Comment by iago64** [comment]
Buenas buenas? Vengo a romperles un poco los esquemas a @calvoluciano  y a @PacoErik  que veo que estan testeando esto.
Pueden probar de achicar el FS a 50 bloques de 64 bytes y para el script que les quede:

```
begin
  variables a, f, p, i, t

  # reservo 65 para no buscar fuera del archivo
  t=65
  i=50
  # reservo el bloque que voy a copiar
  alocar a t
  *a=60

  # abro el archivo destino
  abrir f LEC /largeFile.bin

  # p apunta siempre al byte anterior al nuevo bloque de 90
  p=-1
  
  :escribeotro
  escribir f a t
  i=i-1

  # adelanto 64 bytes, al byte anterior al siguiente bloque
  p=p+64
  buscar f p

  # loopeo
  jnz i escribeotro

  # cleanup
  cerrar f
  liberar a
end
```

Por favor les pido que lo corran y me digan cuanto les toma

**Comment by PacoErik** [comment]
Arreglando esta línea `p=-1`, funciona bien. Lo ejecuté y llenó los bloques 0.bin hasta 49.bin en **326s** (FIFO, retardo de memoria 1ms).

**Comment by iago64** [comment]
@PacoErik muchisimas gracias por la prueba, me base en el script de Mati y se me paso ajustar lo del p=-1.

**Comment by calvoluciano** [comment]
Perfecto este finaliza correctamente, y en un tiempo coherente.

Gracias,

**Comment by iago64** [comment]
En todo caso si quieren y pueden por favor vean como les queda con 20 bloques (i=20) y me dicen cuanto les tarda? porque asi ajustamos el FS para eso :)

**Comment by PacoErik** [comment]
Con una regla de 3 simple sale **~130s** jeje, igual sería más cómodo que la cantidad de bloques sea una potencia del 2, por el tema del bitmap.

Saludos!

**Comment by iago64** [comment]
Claaaro, la regla de 3 me daba aprox 2 min peeero queria confirmar como venian con eso, igual mas que potencia de 2 podemos hacer potencia de 8 y usar 24 bloques :)

**Comment by roavakian** [comment]
Hola, entonces en qué quedó? Saludos!

**Comment by iago64** [comment]
@roavakian Ahora estoy terminando de armar un tar.gz con el FS nuevo y actualizo el script de creagigante, dame unos 15 min :)

**Comment by iago64** [comment]
Listo el nuevo FS y el script de creaGigante.ansisop chequeenlo y cualquier cosa tiren un @ por aca :)

**Comment by riverosm** [comment]
Buenas tardes @iago64! ¿Con este último FS se van a ejecutar todas las pruebas?

Gracias, saludos.

**Comment by iago64** [comment]
Buenas! si señor, con este FS estamos haciendo la prueba del TP.
Cualquier duda o inconveniente avisa y lo checkeamos.

**Comment by iago64** [comment]
@nachoperez714 @roavakian @PacoErik @picollomartin  Este issue ya se encuentra resuelto?, hay algo mas en lo que podamos ayudarlos?

**Comment by picollomartin** [comment]
@iago64 por mi parte más que resuelto

**Comment by tferraro** [comment]
Buenass, cierro el issue asumiendo que se han resuelto las dudas. Si alguna persiste, no duden en volverlo a abrir y las charlamos!
