### ISSUE TITLE
Consola de Memoria

### ISSUE THREAD

**Issue by sebawars** [sisoputnfrba/foro#803]
Buenas, me queda una duda de un comando de la consola de memoria: 

○ Caché: Este comando hará un dump completo de la memoria Caché.
○ Estructuras de memoria : Tabla de Páginas y Listado de procesos Activos
○ Contenido de memoria : Datos almacenados en la memoria de todos los procesos o
de un proceso en particular.

El "Contenido de la Memoria" qué sería?  mostrar todo de corrido como string todo lo que tenga el malloc en los frames de datos?

**Comment by mgarciaisaia** [comment]
👋 Idealmente, me encantaría que impriman la memoria en hexadecimal, como corresponde para datos binarios (probá, por ejemplo, correr `hd /bin/ls` para ver un _hex dump_ del binario `/bin/ls`). Pero esto es un laburito más o menos grande para hacer (que algún día quizá hagan las commons - sisoputnfrba/so-commons-library#91), así que no creo que valga la pena que se gasten en esto.

Si querés chorearte una función ya armada (como [esta](https://gist.github.com/ccbrown/9722406), ponele), golazo. Si no, buen, imprimí como string, y que pasen cosas chanchas. La verdad es que imprimir el string no sirve de mucho, y, por el contrario, tener un hexdump les puede servir _bocha_ a ustedes para debuggear durante el desarrollo y pruebas. Obviamente, esto hubiera sido más útil _hace 3 semanas_ que hoy, pero buen...

Abrazo de gol, ¡che!
