### ISSUE TITLE
Consulta prueba con varias VMs en una Pc

### ISSUE THREAD

**Issue by ivodan** [sisoputnfrba/foro#804]
Buenas, 
A la hora de realizar la prueba base en distintas VMs como dice el documento:
[https://utn.so/wp-content/uploads/2017/06/1C2017-ESTheR-PruebaBase.pdf](url)
que consideraciones tendría que tener en cuenta con respecto a las IP y los puertos de los archivos de configuración? Porque intenté hacer las conexiones que normalmente, en una maquina, me funcionan, pero  ni cerca de que ande. Tengo que configurar las vms de alguna forma en particular o descargar algun otro programa que me facilite la conexion? 
Saludos!

**Comment by fededri** [comment]
Fijate la configuración de las VMS en "Redes" que esté en "adaptador puente"
Yo no tuve problemas con eso. con ifconfig ves la ip

**Comment by ivodan** [comment]
Hola, estuve probando lo que me dijiste pero no me funciono.. seguramente no hice algo bien. La ip que tengo que usar es 192.168.1.10 no? 

![image](https://user-images.githubusercontent.com/22500487/27968386-31bce1e4-631d-11e7-8fab-deef03c40876.png)

Porque abro el proceso memoria en la vm de la foto, en otra vm en el archivo config del kernel pongo esa ip, y cuando ejecuto el kernel me tira connection refused. En configuracion puse adaptador puente como dijiste.. nose si se me esta pasando algo.

**Comment by iago64** [comment]
@ivodan efectivamente, la ip que tenes que poner es 192.168.1.10, que es la ip asignada a la "placa de red" de tu VM. la ip 127.0.0.1 es la localhost.

**Comment by ivodan** [comment]
Entonces nose porque no me estaria conectando.

**Comment by mgarciaisaia** [comment]
Probá hacer ping desde la otra VM a esa IP.

¿Están ambas VMs en la misma red? Ver qué dice el comando `arp -a` en cada
VM después del ping también puede ayudar.

Por último, podés hacer correr el proceso que da Connection refused con
`strace`, y mandar todo ese log a un archivo, y subirlo a Internet para que
lo miremos.

Algo como esto puede ayudarte a subirlo:
https://stackoverflow.com/a/24130329

¿Algún detalle de la red que armaste que te esté faltando y pueda ser
relevante?

**Comment by mgarciaisaia** [comment]
¡Están todas las VMs en la misma máquina!

Chequeá que tengan MAC addresses distintas (el identificador "físico" de la
placa de red), o abrí las settings de la vm y ponele que genere uno nuevo.

O, en lugar de usar un adaptador puente, crea una red interna en
virtualbox, y conecta todas las vms a esa misma red.

**Comment by mgarciaisaia** [comment]
¿Qué pasó con esto, che, al final? ¿Andó o no le andó? 🙃

**Comment by loopmeagain** [comment]
Hola, disculpa la demora de la respuesta, si el problema estaba en que cuando clonabamos la vm no le dabamos a que le asigne una nueva mac, ahora le andó perfecto. Gracias!
