### ISSUE TITLE
Metadata_buscar_etiqueta  - Bug de parser

### ISSUE THREAD

**Issue by lamasnicolas** [sisoputnfrba/foro#805]
Buenas noches, encontramos un error en la librería parser. 
Existe una inconsistencia entre las primitivas de parser y las funciones de metadata_program. Por ejemplo, entre esta primitiva:

 `void (*AnSISOP_llamarConRetorno)(t_nombre_etiqueta etiqueta, t_puntero donde_retornar)`

Y: `t_puntero_instruccion metadata_buscar_etiqueta(const t_nombre_etiqueta objetivo, const char *etiquetas, const t_size etiquetas_size)`

¿Esto será solucionado? ¿Como será considerado esto en la entrega?  

Creyendo que el error era de parte nuestra, perdimos tiempo durante estas semanas

**Comment by mgarciaisaia** [comment]
¿Cuál es la inconsistencia, che?

Esas dos funciones que nombran funcionan a niveles distintos. `AnSISOP_llamarConRetorno` tiene una semántica muy particular, específica, mientras que `metadata_buscar_etiqueta` probablemente la vayan a usar en más de una ocasión.

¿Cuál es la inconsistencia que ven?

**Comment by pabloavendano** [comment]
metadata_buscar_etiqueta no encuentra la etiqueta que recibe la función AnSiSOP_llamarConRetorno y retorna un valor incorrecto.

**Comment by SantiagoBoffa** [comment]
Ademas de esto existe otra inconsistencia al momento en el que se asigna valor una variable a través de la función:
void (*AnSISOP_asignar)(t_puntero direccion_variable, t_valor_variable valor);
ya que esta función se llama desde las instrucciones del tipo "a =5" y "alocar a 500", según lo que tengo entendido estas dos instrucciones tiene una lógica distinta.
La instrucción de alocar reserva un espacio en memoria igual a 500, y la función "a = 5" asigna a la variable 'a' el valor de 5 (guarda en el espacio de memoria asignado a 'a' el valor de 5).
Al parsear estas funciones la instrucción "a = 5" pasa como valor 5 y "alocar a 500" un número que corresponde a un puntero.
Al tener que asignar en un caso memoria y en otro un valor , la función depende de la instrucción que proviene para definir su comportamiento.
Nose si es un error mio de comprensión o un error de definición de la primitiva que tiene que contemplar ambos casos.

**Comment by tferraro** [comment]
Yo tampoco veo la inconsistencia que decis :/. Que retorne un valor
incorrecto puede deberse a otra cosa, no necesariamente un error del parser.

Respecto a la segunda pregunta, si tuvieras que asignar 5 o el nro que
represente tu posición de memoria que pediste, en que cambiaría para el
asignar? En que parte difieren que el código ha de tener qué diferenciarlos
como planteas?

**Comment by pabloavendano** [comment]
Es error del parser ¿Probaron el archivo stackoverflow.ansisop? Las instrucciones que procesa analizadorLinea terminan en '\n'. Por ejemplo, una instrucción del programa stackoverflow.ansisop es "a <- f", esta instrucción finaliza con '\n' (así guarda metadata_desde_literal en el campo instrucciones_serializado). El valor que toma la variable etiqueta cuando el parser invoca el método void (*AnSISOP_llamarConRetorno)(t_nombre_etiqueta etiqueta, t_puntero donde_retornar) es "f\n".  metadata_buscar_etiqueta nunca encuentra esta etiqueta. Analizamos el códgio de esta función y las etiquetas finalizan con el carater '\0' por eso no coincide la buscada. Creamos un parche en nuestro códgio para este error: etiqueta[strlen(etiqueta) - 1] = '\0';
Así logramos que funcione, pero solamente en el caso que la función invocada en el programa no tenga parametros. En el caso que tenga parámetros este parche no sirve ya que recibe un etiqueta que finaliza con el caracter '\0'

La inconsistencia esta en el parser.

![error](https://user-images.githubusercontent.com/11395208/27986594-7e4e2f76-63d7-11e7-9dfa-d7cb8305d9cb.png)

**Comment by mgarciaisaia** [comment]
Che, es raro lo que cuentan, porque hace como [3 años que no tocamos esa parte del parser](https://github.com/sisoputnfrba/ansisop-parser/blame/master/parser/parser/parser.c#L166-L175), y estamos viendo grupos en los que funciona.

No entiendo muy bien, igual, por qué habría un `\n` en ese string - claramente no tiene sentido que eso ocurra.

Si alguno anda cerca de Medrano y se quiere acercar, tratamos de ver qué onda - traté de levantarles el TP a ver qué onda, pero no tengo CLion y ¯\\\_(ツ)\_/¯

**Comment by guillermo126** [comment]
si me pasa lo mismo y ademas hubo otro grupo que conozco que tambien le paso lo mismo... ¿como podriamos hacer?? ¿se encuentra alguien en medrano el jueves a partir de las 18 hs?

**Comment by SantiagoBoffa** [comment]
Hola @mgarciaisaia , pase este sabado por Medrano para que veamos el problema del parser , y nos dijiste que probemos en un a VM de 32 bits , tratamos de probarlo pero decidimos seguir con la realización del tp llevándola acabo con un pequeño arreglo de parte nuestra, ya que no podemos probar esto rápidamente y tampoco destinar tiempo de desarrollo en más pruebas; revisamos durante una semana nuestro código creyendo que el error era nuestro. Ahora que existe una alta probabilidad de que el error esté en la librería ¿no podrían probar ustedes?
Ya que si el error esta en la libreria seria conveniente que se les informe lo antes posible a los alumnos para que no pierdan tiempo de desarrollo, que en esta instancia es valioso, tratando de corregir un error que tal ves no es culpa suya y el cual es difícil de descubrir sin meterse a mirar código del parser.

**Comment by guillermo126** [comment]
@pabloavendano en donde fue que agregaste  etiqueta[strlen(etiqueta)-1]= '\0'?? En el código del parser o en el tuyo? Te pregunto así puedo seguir probando, gracias ;)

**Comment by pabloavendano** [comment]
En el nuestro, en la implementación de las primitas .AnSISOP_llamarSinRetorno y .AnSISOP_llamarConRetorno.

void corregir_nombre_etiqueta(t_nombre_etiqueta etiqueta) {
    if (etiqueta[strlen(etiqueta) - 1] == '\n') {
        etiqueta[strlen(etiqueta) - 1] = '\0';
    }
}

**Comment by guillermo126** [comment]
Gracias después pruebo

**Comment by alejandrog87** [comment]
Buenas noches, soy del mismo grupo que Guillermo, acabo de actualizar la .so del ansisop parser a la ultima versión, y probando en la vm oficial (32b) de la cátedra el error persiste, vamos a probar el fix que propone Pablo para ver si se soluciona este extraño comportamiento del parser.

**Comment by gonziesc** [comment]
Buenas, yo soy de otro grupo, y también tenemos el mismo problema con las funciones que reciben parámetros. El tema es que como en las pruebas de la entrega no figura ninguna función así, no le dimos mucha bola. Pero pasamos por exactamente la misma situación.

**Comment by alejandrog87** [comment]
Nosotros tenemos este problema al correr el script stackoverflow.ansisop , que es uno de los scripts que aparece en el documento de pruebas.

**Comment by mgarciaisaia** [comment]
¿Algun@ me puede pasar un commit de su repo en el que sea fácil reproducir el problema?

**Comment by pabloavendano** [comment]
El último podría ser: 46fa13e12f96faaba8f9674923064535b1fd2dd5

También encontramos el mismo problema en las funciones de variable compartida.
Si una instrucción termina en el nombre de la variable compartida, por ej.: "a = !pasadas" El parser asigna en el parametro "t_nombre_compartida variable" de la función AnSISOP_obtenerValorCompartida el valor "pasadas\n".
En cambio si el nombre de la variable no está al final de la instrucción, por ej.: !pasadas=!pasadas + 1 El valor que toma el parámetro es "pasadas".

**Comment by guillermo126** [comment]
aca dejo mi commit 583c212e4630c10178af3a4a8e1cd7868218c5f9

**Comment by alangadiel** [comment]
nosotros usamos esto y nos anda bien stackoverflow.ansisop
void limpiar_string(char** string){
	int i ;
	for(i=0;i<string_length(*string); i++){
		if((*string)[i]=='\n' || (*string)[i]=='\r' )
			(*string)[i]='\0';
	}
}

para llamarla:
limpiar_string(&elString);

**Comment by ankomas** [comment]
Nos pasa lo mismo, termine agregando a fuerza al final de todas las etiquetas el '\0'.

`	memcpy(etiqueta+strlen(etiqueta)-1,"\0",1);`

Viendo la solución de los demas creo que voy a agregar el "if=='\n'".

Tuvimos que usar eso para "irALabel" "llamarSinRetorno" y "llamarConRetorno". Nosotros también probamos con stackoverflow.ansisop.

**Comment by guillermo126** [comment]
nosotros probamos lo que propuso @pabloavendano  y no nos funciono. ahora depsues vamos a probar lo que hizo @alangadiel . me gustaria saber cual de los ayudante se encuentra mañana jueves  disponible despues de  las 18 hs para poder ver arreglar esta situacion... puedo ir a medrano, campus no.

**Comment by iago64** [comment]
Muchachos, puntualmente la solución al problema es bastante mas simple de lo que parece, solo tienen que frenar la pelota un segundo y ponerse a pensar como pueden uds parsear la cadena que les devuelve el parser (valga la redundancia) y obtener lo que les sirva.
Tengan como idea que siempre un \0 o un \n les va a venir en el código, con lo cual, evocando a algún no tan celebre filosofo, podemos decir que el problema se soluciona con un for y un if.

**Comment by pabloavendano** [comment]
Disculpa ¿vos perteneces a la cátedra? De ser así tu respuesta es poco pertinente, reduccionista y simplista. a) Olvidas el proceso de prueba y depuración que es necesario para encontrar el defecto que causa la falla. La cátedra remarca con tanta insistencia que la librería no tiene ningún error que nuestro grupo busco por, al menos una semana, el defecto en nuestro código. Resultó ser que la librería tiene un comportamiento errático, no determinístico en los casos que marcamos y esto es un error.
b) Para poder llegar a la conclusión que es necesario reemplazar el caracter '\n' por '\0' necesito conocer la implementación de la función metadata_buscar_etiqueta. Fue al utilizar esa función que tuvimos la falla. Apenas existe documentación de la librería obligatoria (si un ejemplo incompleto es considerado documentación) y obviamente, no existe ninguna especificación de la implementación interna de la funciones. Entender el funcionamiento interno de la librería obligatoria está fuera del alcance del trabajo práctico y si fuese necesario debería existir documentación y especificaciones.

Este trabajo práctico es complejo por su alcance, por el tiempo de desarrollo y por el conocimiento de programación necesario (conocimiento que no es abordado en esta materia ni en otras, con la profundidad necesaria). Insisto, si sos de la cátedra deberías entender la complejidad del trabajo práctico y elaborar una respuesta con mayor altura. Hasta ahora solo queda claro la falta de voluntad que existe para asumir la responsabilidad por el error (o posible error), y tomar acciones en consecuencia para no perjudicar a las personas que ponemos mucho tiempo y esfuerzo para alcanzar los objetivos propuestos por la materia. Por ej. podrían reparar el error o al menos notificar por el medio oficial la problemática y la solución temporal.

**Comment by jazcarate** [comment]
Holitas :)

Perdón que caigo un poco tarde, pero mirando un poco como está funcionando el `metadata_desde_literal`, una de las primeras cosas que hace es `_separarLineas` que remplaza todos los `\n`s por `\0`s internamente. Más adelante genera una instrucción `{ .start = position, .offset = strlen(buffer) +1 };`.

De la misma manera que `\tvariables a` tiene 13 caracteres; `\tf <- a` tiene 8; claro que en el programa real, esa última posición es un `\n` y no un `\0` como en el stream que maneja el `metadata_desde_literal`, pero es siempre igual, donde tiene "un caracter final de más". Eso se va a repetir en todas las _lineas_ que tomes de AnSISOP, no solo cuando uno busque etiquetas (que es ciertamente donde aparece el problema).

¿No les pasó que todas las lineas que analiza el `analizadorLinea`?
Para probar mi teoría, una rapida, en su `cpu/cpu.c`, dentro de la función `obtener_instruccion_memoria` prueben agarrar la linea antes de devolverla, y ponerle un `\0` al final:
```
    char *string = pedir_lectura_pagina(memoria_id, &pedido);
    string[offset-1] = '\0';
    return string;
```
Esto sería, que cuando le piden a la memoria; seteen el ultimo en `\0`.

¿Eso sirve?

**Comment by sciciliani** [comment]
Hola Pablo.

Algunas cosas que quiero dejar en claro.

No decimos que el parser no tenga bugs. Una prueba clara de esto es la cantidad de correcciones que se le hicieron este cuatrimestre. Por mi parte en la presentación del TP dije que el parser se entrega con código fuente como una ayuda para que no lo tengan que hacer uds. Si algún grupo prefiere codearlo se lo desaconsejaría pero estaría permitido.

Por otro lado, mirando la actividad del thread que tiene 5 días veo que hubo colaboración de alumnos y ayudantes por lo que no siento que este tema se haya "colgado" o que haya habido falta de voluntad. 
En mi caso, aun teniendo ayudantes que me contaban que tuvieron que corregir eso mismo en su TP, todavía estaba algo escéptico del bug, por lo mismo que dice Matias. Hace 3 años que ese código está igual y aprobaron docenas de grupos usando ese parser, varios este sábado que pasó.

Finalmente, en relación a Damián, te aseguro que su respuesta tuvo la intención de ser amena e informal, como solemos hacer siempre. Hacer un cambio al código del Parser en esta instancia probablemente perjudique a más grupos de los que ayude, por lo que lo vamos a dejar como está y desde el lado de uds tendrán que considerar este escenario. No es por falta de voluntad ni por querer simplificar la solución.

**Comment by pabloavendano** [comment]
@jazcarate Gracias por revisar el código. Esta corrección `string[strlen(string)-1] = '\0';` la aplicamos, cuando encontramos la falla, en el valor que toman los parámetros de la primitivas. No nos atrevimos a corregir la instrucción completa porque desconocemos la implementación de `analizadorLinea` y que consecuecias podría traer.

@sciciliani Entiendo la dificultad de publicar un arreglo a esta altura y el impacto que podría tener. Algunos grupos seguramente detectaron esto e hicieron el enmiendo necesario como nosotros hicimos. Lo grupos que ya aprobaron, obviamente, también. Pero pueden existir otros grupos que aún no y una publicación los podría ayudar o destrabar; o bien, otra solución podría ser crear otra rama con el arreglo.

**Comment by mgarciaisaia** [comment]
:wave: A riesgo de seguir acaudalando el río de bytes vertidos en esta charla, quería contarles que estuve revisando un poco el código del parser para entender mejor la situación.

El hecho de que la línea que se traen de memoria incluya el whitespace que haya en el archivo es _por diseño_. No es un bug: el parser está pensado para que el `instrucciones_serializado` contenga líneas completas. Pueden revisar [el código relevante](https://github.com/sisoputnfrba/ansisop-parser/blob/b11d9796ea30461fe5cb75c189256c9d3c9c50f2/parser/parser/metadata_program.c#L35-L36): primero indexa, y _recién después_ elimina whitespace para operar esa línea.

Podemos discutir un rato largo sobre si es una buena decisión de diseño o no, pero no es comportamiento _errático_ o nada por el estilo. Es decir, es responsabilidad del usuario del parser eliminar esos espacios en blanco.

Si revisan el link, queda _bastante expreso_ cómo eliminar esos espacios en blanco (espero).

Entonces, lo que veíamos el otro día en el labo, de que la línea _incluída_ el `\n`, es el comportamiento esperado. `_separarLineas` [reemplazar cada `\n` por un `\0`](https://github.com/sisoputnfrba/ansisop-parser/blob/master/parser/parser/metadata_program.c#L83-L85) para cortar las líneas, pero _está trabajando sobre una copia_. Cuando después usen esos índices sobre el texto original del programa, ahí van a encontrar los `\n`. Incluso, los índices que les da el `instrucciones_serializado` no son (salvo, quizá, el último) strings, siquiera, dado que **no terminan en `\0`**. Es responsabilidad del usuario del parser hacer todo ese manejo.

-----

La moraleja que me llevo es que tengo que hacer las cosas bien, o no hacerlas. Hacer las cosas por la mitad, o sin muchas ganas, sólo complica y dilata las cosas. Si hubiera dedicado las 3 horas que le metí ahora hace un par de días, nos ahorrábamos un montón de fricción al pedo. Por esa parte, les pido mil disculpas.

También hay bastante para pensar sobre cómo nos comunicamos, y sobre cómo nos llevamos con el sesgo de confirmación.

El texto escrito es uno de los peores medios para representar emociones y transmitir metalenguaje (al punto de que, como industria, nos hayamos dedicado a [crear un estándar internacional que nos permita transmitir "💩"](http://unicode.org/emoji/charts/full-emoji-list.html)), y entonces es muy fácil interpretar de mal modo los mensajes de los demás, y de muy buen modo los propios.

El sesgo de confirmación nos lleva a interpretar que cualquier dato que se alinea con lo que creemos es cierto y relevante, y a descartar o menospreciar cualquier dato que vaya en contra. De este modo, siempre estuve convencido de que el `\n` del final era un problema de ustedes por correr en 64 bits (incluso probé cosas en un par de VMs hace un ratito), y hasta que no paré la pelota, empecé de cero, e hice un programa simple para testear esto, no pude ver el real inconveniente. De modo similar, creo yo, se concentraron tanto en que era un bug del parser que no pudieron ver que esto no era un comportamiento errático de `llamarSinRetorno` o `asignar`, si no que quizá el parser propone usarlo de otra manera.

Nada, espero que esto aclare la situación, y, posta, les pido disculpas por un lado, y les agradezco por el otro el hacer[me/nos] notar todo esto que pasó. Como diría un gran maestro, [_meditate on this, I will_](https://www.youtube.com/watch?v=G67eMq1YwmI).

Un abrazo, y ¡nos vemos el sábado!

**Comment by ericvaloschin** [comment]
Buenas! puede que un poco tarde tal vez, pero estaba teniendo un problema con el tema de las etiquetas: el script llenandomemoria me estaba destruyendo el parser y los proximos scripts que mandaba se leian mal (la tipica ir a etiqueta -1 y romper todo). Acabo de encontrar el problema (y la solucion):  **darle enter al script de llenando memoria despues de la etiqueta**. Asi lo esta en consumidor y ese anda fenomeno. No se que sera, pero ahora anda todo de 10. 
Espero haber aportado algo!
Saludos

**Comment by tferraro** [comment]
Buenass,

Dado que ya se detectó cual era el problema en particular, se propuso un workaround y volviendo al tema Mati confirmó que no existía más el bug, doy por cerrado el tema. Cualquier cosa, si la duda persiste vuélvanlo a abrir!
