### ISSUE TITLE
Duda Alocar

### ISSUE THREAD

**Issue by nicogena90** [sisoputnfrba/foro#806]
Buenas, tenemos una duda con la siguiente instrucción:

> alocar a 100

Creemos que debería reservar heap para la variable a, pero al invocar a la primitiva reservar lo hace solo con el valor 100. ¿Cómo podemos saber que ese espacio asignado es para la variable a? ¿Lo tenemos que manejar nosotros en el Kernel?

Muchas gracias, saludos.

**Comment by mgarciaisaia** [comment]
¿Qué función análoga a Alocar conocés en C?

¿Cómo funciona? ¿Cuáles son sus parámetros?

**Comment by riverosm** [comment]
Buenas Mati, estoy en el grupo con Nico.

Entendemos que se trata de un malloc:

> void* a = malloc(100);

Reserva 100 para la variable a, nosotros hacemos:

> alocar a 100

Pero en la llamada a la primitiva reservar sólo tenemos el valor 100, ¿cómo sabemos que esos 100 son para la variable a?

Muchas gracias, saludos.

**Comment by tferraro** [comment]
Holis!

Le pegaste en el palo! Efectivamente, Mati se refería al malloc, peeeero
solamente a la función denominada malloc, fijate que lo que escribiste
tiene algo demás.

Que pide como parámetro y que esperas que malloc te devuelva?

Entonces, vamos de nuevo, exactamente, que hace malloc?

**Comment by riverosm** [comment]
Un puntero, por eso la función devuelve t_puntero.

Evidentemente el otro día a las 3am no lo vimos, gracias, cierro.

Saludos

**Comment by mgarciaisaia** [comment]
Por si alguien se pierde el salto de razonamiento que hizo @riverosm:

`malloc` es una función que reserva un bloque de memoria del tamaño que le digamos, y devuelve un puntero al inicio de ese bloque. **`malloc` no sabe qué vamos a hacer nosotros con ese puntero**, ni le importa.

Lo más razonable es que uno pida un bloque de memoria _porque quiere guardar algo ahí_, y entonces prácticamente siempre vamos a guardar el resultado de `malloc` en una variable, pero esto **es externo a la función** en sí.

En el caso de AnSISOP no es tan tan así. La _instrucción_ `alocar` **requiere** que le pasemos la variable en que va a guardar el puntero, pero [la primitiva `reservar` no](https://github.com/sisoputnfrba/ansisop-parser/blob/fa84032/parser/parser/parser.h#L233-L243).
