### ISSUE TITLE
Escritura en Memoria

### ISSUE THREAD

**Issue by calvoluciano** [sisoputnfrba/foro#808]
Consulta,

En el script de prueba escribirFS, una de las instrucciones es,

b=a+4
*b=1095520072

Como bien sabemos las variables de ansisop ocupan 4 bytes, cuando yo mando a guardar en memoria solo queda 1095, el resto no se guarda.

Luego en la instrucción,

 escribir f a 100

Hace una desreferencia de a 100 veces avanzando uno a uno barriendo la posicion del puntero a memoria, hasta que llega y encuentra a partir de la 4ta posicion, 1095 despues 095.. 95 y 5

El resto de los valores están vacios. Esta bien esto es lo esperado?

**Comment by mgarciaisaia** [comment]
@calvoluciano el enunciado dice que las variables de AnSISOP son "solamente de tipo entero con signo", de 4 bytes en particular. Eso significa que podés almacenar cualquier número hasta 2^31 o 2^31 - 1 (un bit para el signo, los 31 restantes van para el número, ponele que vos elegís si el 0 cuenta como positivo o no). Ese número estúpidamente grande que el script quiere guardar entra joya en 31 bits (es `0100 0001 0100 1100 0100 1111 0100 1000`).

Supongo que ese temita hace que todo lo demás cambie... bastante.

¡Un abrazo!
