### ISSUE TITLE
problmas con la funcion metada_desde_literal()

### ISSUE THREAD

**Issue by guillermo126** [sisoputnfrba/foro#809]
buenas noches, estoy tratado de correr el programa stackoverflow y al mandarle el codigo de ese programa a la funcion metada_desde_literal() solamenteme me pone como etiqueta a la funcion f y no a la funcion g me fije muchas veces si el script que le tiene que llegar por paramatreo le llega bien y le llega bien actualize el parser y aun asi tampoco tengo resultados... desde la funcion solo me reconoce como etiqueta a la funcion f, al debaguear entre a la funcion y como que no me copia a g en las etiquetas... a alguno le paso?? como podria solucionar esto? bueno muchas gracias

**Comment by guillermo126** [comment]
buenas, disculpen que insista pero necesito una pronta respuesta todavia no me reconoce bien las etiquetas la funcion metadata_buscar_etiqueta(); desde la otra funcion metada_desde_literal()  solo me esta leyendo a f como etiqueta y deberia tambien leerme a g. gracias

**Comment by mgarciaisaia** [comment]
@guillermo126 suena parecido a #805

¿Estás corriendo esto en las VMs? ¿Puede que estés corriendo el sistema en una máquina de 64 bits?

Si es el mismo problema, cerrá este issue y sigamos troubleshooteando allá 👍
