### ISSUE TITLE
Consulta compilación TP

### ISSUE THREAD

**Issue by riverosm** [sisoputnfrba/foro#810]
Buenas, para la compilación final del TP en las disintas virtuales del laboratorio, ¿podemos ejecutar make con privilegios de root?

> sudo make

Mas que nada para saber si linkeamos las librerías con el LD_LIBRARY_PATH o podemos copiarlas al /usr como lo haría cualquier make install.

Muchas gracias, saludos.

**Comment by sciciliani** [comment]
Idealmente hagan `make` para compilar y luego `sudo make install` para copiar las bibliotecas.

**Comment by riverosm** [comment]
Gracias Santiago! Cierro el issue.
