### ISSUE TITLE
Problema creaGigante V2.0

### ISSUE THREAD

**Issue by calvoluciano** [sisoputnfrba/foro#812]
Hola,

Creo un nuevo incidente con la esperanza de una respuesta.

Finalmente cual es la resolución al creaGigante, en mi caso la cpu se me cae no veo como resolverlo.

En mis dereferenciar devuelvo 0 ante una determinada posición donde ya la memoria no me devuelve okey de lo que pido, luego cuando hago un memcpy del puntero void informacion con el tamanio indicado me da Segmentation Fault.

Cual es la respuesta esperada a este script?

**Comment by mgarciaisaia** [comment]
La seguimos en #802 para no fragmentar la data.
