### ISSUE TITLE
Consulta escribirFS

### ISSUE THREAD

**Issue by riverosm** [sisoputnfrba/foro#813]
Buenas, haciendo referencia a #737 me quedó la siguiente duda, a ver si entendí bien. En la prueba escribirFS.ansisop se ejecuta la siguiente línea:

    *b = 1095520072

¿En este caso no se debería dividir debido a que el valor entra en un entero sin signo? ¿b pasa a ser una variable de HEAP?

Muchas gracias, saludos.

**Comment by tferraro** [comment]
Holis!

Fijate lo que está haciendo esa linea, está referenciando el puntero que está en b y le está asignado a la posición apuntada el valor 1095520072....queeee, si seguís la misma idea de joaco del issue que referenciaste

1095520072d -> 01000001010011000100111101001000b -> ALOH (está al reves por los endianness) :wink:

b no es una variable de HEAP, siempre vive en el stack, dado que la definición de la variable hace que *siempre esté en el stack*, peeeeero te estás confundiendo porque b tiene asignado un valor muy especial 😛 

Saludos!

**Comment by iago64** [comment]
@riverosm Ya se encuentra resuelto el issue? podemos ayudarte en algo mas?

**Comment by riverosm** [comment]
Sí, lo cierro, gracias!
