### ISSUE TITLE
Problemas de linkeo para compilar en el server

### ISSUE THREAD

**Issue by Matias9635** [sisoputnfrba/foro#814]
Hola buenas tardes, estamos teniendo problemas para compilar en el server porque no nos reconoce las librerías a pesar de que están instaladas. Quería saber si nos podían dar alguna mano con esto, y si hay algún ayudante en Medrano. Estamos en el laboratorio rojo en Medrano.
Muchas gracias

**Comment by tferraro** [comment]
Mieeentras tanto, tenés una descripción más amplia de lo que está pasando? Sus bibliotecas se instalan en el sistema o las están corriendo seteando el `LD_LIBRARY_PATH`? Las bibliotecas están compiladas correctamente?

Se me ocurren miles de preguntas, pero como dije antes, mientras tanto, contanos que pasa.

Saludos!

PD: biblioteca, no libreria (?)

**Comment by FVolo** [comment]
Ya logramos solucionarlo, estaban instaladas las bibliotecas y compiladas correctamente pero estabamos linkeandolas antes del .c.

Cuando lo probamos compilar como: `gcc arch. -o Arch -l...` nos empezo a andar.
