### ISSUE TITLE
[DUDA] Comando finalizar programa (consola y kernel)

### ISSUE THREAD

**Issue by marrtins** [sisoputnfrba/foro#816]
Buenas, nos surgió un problema de interpretación de la consigna a la hora de finalizar procesos.

Leímos el issue #720 y eso nos confundió un poco, esto es lo que tenemos por ahora y no sabemos si cumple con lo pedido; resumiendo:

1-El finalizar programa del proceso CONSOLA y el finalizar programa del proceso KERNEL se comporta de la misma manera?

Es decir, dejar que cpu siga ejecutando hasta que devuelva el pcb (ya sea por fin de la ejecucion o fin de quantum) y recien ahí setear el exitcode(-7 finalizado a traves del comando Finalizar Programa de la consola) y avisar a la consola para que finalice el hilo del programa correspondiente??

2-En ese caso, en las estadisticas de ejecucion, el momento de finalizacion sería cuando usamos el comando finalizar o cuando terminamos el hilo??

**Comment by varas-c** [comment]
Hola Martin,

El finalizar por consola o finalizar por kernel debería ser igual. Es
decir, a tu proceso le da lo mismo si lo mató su consola o el kernel. Si
esperás en ambos casos que finalice la ráfaga de cpu, está bien.

La diferencia es que si matas por kernel, de alguna forma tenés que
avisarle a la consola respectiva, que ese proceso finalizó, si no, se va a
quedar esperando a un proceso que ya murió.

Con lo del tiempo de fin de ejecución, no somos taaaan estrictos. Lo ideal
sería que manejes ésto desde la consola. Es decir, cuando le avises a la
consola que terminó el proceso pid x, tomás el tiempo de fin.en ese
momento. Lo mismo cuando la misma consola finaliza el pid x.

Si no se entendió bien o tenés alguna otra duda, avisanos!

Saludos!

**Comment by marrtins** [comment]
Ok, listo. En ambos casos le avisaríamos a la consola que el proceso termino cuando cpu devuelve el pcb. Luego la consola sabrá a través del exit code y eliminará el thread correspondiente.

Mil gracias!
