### ISSUE TITLE
Consulta creación archivo

### ISSUE THREAD

**Issue by riverosm** [sisoputnfrba/foro#818]
Buenas, les hago una consulta respecto a la creación de los archivos:

> abrir f CE /archivo.bin

¿Qué pasa si lo intento abrir con el flag de creación y el archivo ya existe? ¿Debería dar un error o debería "pisar" el contenido?

Muchas gracias, saludos.

**Comment by tferraro** [comment]
Buenas!

Idealmente, no va a pasar en las pruebas porque:
- Estaríamos probando algo muy border que pierde el sentido
- No se encuentra especificado un comportamiento (no porque sea una errata, sino porque no requerimos un comportamiento en particular, son libres a elegir).

Sin embargo, si querés implementar el caso, dado que el enunciado dice `Create ( c ): Crea el archivo al abrirlo si este no existe.` , si existe podes ignorar directamente el flag y abrirlo con el resto de los permisos.

Saludos!

**Comment by riverosm** [comment]
Gracias! Cierro
