### ISSUE TITLE
Ansisop Productor-Consumidor

### ISSUE THREAD

**Issue by ulukacher** [sisoputnfrba/foro#819]
Buenas noches, con mi equipo estamos teniendo problemas al ejecutar los ansisop de productor y consumidor. 
Los casos de prueba dicen: 

> Iniciar el FS; el Kernel; las Consolas 1 y 2 ; las CPUs 1, 2 y 3. y validar las conexiones.
> Ejecutar en la Consola 1 un proceso productor.ansisop e iniciar un proceso
> consumidor.ansisop en la Consola 2.

Es decir, comenzará ejecutando el productor, hará un wait(luego de este, el semaforo "**b**" pasará a valer cero), incrementará la variable colas, hará un signal del semaforo "**c**" el cual pasara a valer 1 y finalmente se bloquea al ejecutar el segundo wait.  Luego, se inicia un **consumidor.ansisop** y se van alternando los valores de los semaforos y un proceso desbloquea al otro; hasta aca vamos bien.

> Finalizar el proceso **productor.ansisop** que está ejecutando en la Consola 1 y verificar
> que el proceso **consumidor.ansisop** detiene su ejecución quedando en la cola de
> bloqueados.
> Iniciar un proceso consumidor.ansisop en la Consola 1 y verificar que se bloquea.
> Iniciar un proceso productor.ansisop en la Consola 2 y verificar que se alternan los
> consumidores de las consolas 1 y 2 en mostrar los resultados.

El problema nuestro empieza cuando se finaliza el productor debido a que luego de esperar a que este termine de ejecutar en una CPU las rafagas que le fueron asignadas, el semáforo "b" pasa a valer -1 mientras que **c**, cero. Esto hará que el **consumidor** se bloquee, y finalmente, el semaforo "b" pase a valer cero y **c** tendrá el valor de -1.
Luego, intentamos correr otro **consumidor** y se bloquea correctamente,tal cual lo piden las pruebas. Lo que nos ocurre es que al intentar correr otro "productor", este se bloquea debido a que como el semaforo **b** tenía cero, al hacer wait, tendrá -1 y se bloqueará; esto nos genera un deadlock.
No estamos encontrando la forma de salir de esto.
Habrá que validar que luego de solicitar desde la consola, finalizar al productor, no se ejecuten las syscall que este pide? ( tal vez de esta manera no se hará wait del semaforo **b** y en vez de ser quedar en -1, quede en 0).
Adjunto ambos códigos.
Muchas gracias

Productor: 
```
#!/usr/bin/ansisop
begin	
	:etiqueta
	
	wait b
	!colas = !colas +1
	signal c
	
	#Ciclar indefinidamente
	goto etiqueta

end

```
Consumidor:
```
#!/usr/bin/ansisop
begin	
	:etiqueta
	
	wait c
	prints n !colas
	signal b
	
	#Ciclar indefinidamente
	goto etiqueta

end
```

**Comment by iago64** [comment]
@ulukacher No se preocupen, si se bloquea el productor nuevo es un comportamiento posible y esperado ya que como bien analizas puede ser que no llegue a ejecutar justo el signal, un poco la idea de la prueba va también de la mano en que vean que se pueden dar situaciones de deadlock en su tp con los scripts ansisop y que aun asi esos procesos bloqueados no obstaculizaran a otros que quieran correr como por ej un stackoverflow o un EscribirFS / LeerFS :)

Saludos.-

**Comment by tferraro** [comment]
@ulukacher te sirvió la respuesta de Dami? Se puede cerrar el issue? Gracias!

**Comment by ulukacher** [comment]
Sisi, se puede cerrar. Gracias!
