### ISSUE TITLE
Problema con bitarray_destroy de las commons

### ISSUE THREAD

**Issue by SLDG1297** [sisoputnfrba/foro#820]
Hola, qué tal! Todo bien?

Abrí este issue porque la función bitarray_destroy de las commons leakea memoria.

Mientras estaba testeando el Bitmap para el File System, Valgrind me tiraba que perdía 649 bytes de memoria, que coincidían con los que necesitaba alocar para el array de bits según el ejemplo que dice el enunciado.

Así que inspeccioné la implementación de bitarray.c, que está acá:
[https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/bitarray.c](url)

Y me encontré con esto:

``` c
// Estructura de t_bitarray

typedef struct {
	char *bitarray;
	size_t size;
	bit_numbering_t mode;
} t_bitarray;

// Función de las commons

void bitarray_destroy(t_bitarray *self) {
	free(self);
}
```
Como pueden ver, `bitarray_destroy` solo libera a `t_bitarray* self`, y no al `char* bitarray` que hay adentro de la estructura, por lo que  los bytes ocupados por `char* bitarray` se pierden para siempre.

Sugiero que agreguen la línea `free(self->bitarray)` en `bitarray_destroy` para solucionar el problema.

Espero que se entienda el problema. Igualmente, no sé si se lo olvidaron, o bien está hecho así a propósito para no perder el array de bits. Confirmenme esto cuando puedan.

Saludos!

**Comment by gastonprieto** [comment]
Buenas,

Eso no es un issue de las commons, estan pensadas para funcionar de esa forma. Fíjate que las commons no son responsables de hacer un `malloc` de lo que apunta la variable `bitarray`, por lo tanto tampoco son responsables de hacerle un `free`.

Por ejemplo, esto se diseño así, para que pueda funcionar con un puntero a memoria estática, al resultado de un mmap o a con lo que devuelve un `malloc`, el que cree el `bitarray` va a ser el responsable de liberar dicho puntero si fuerea necesario.

**Comment by mgarciaisaia** [comment]
(Cuando contesto mails a las 4am no tengo que preocuparme por que me primereen la respuesta, como en este caso 😹)

> 🎵 [_Hola amiga, ¿todo bien? No me importa cómo estás: vine a hacerte sonreir..._](https://youtu.be/Ps8oY8Ie-48?t=1m22s) 🎶

Me gusta la investigación que hiciste, che 👍

Pero... _(sí, hay un pero)_

Además de mirar la estructura, habría que ver """el constructor""" - es decir, la función que te permite inicializar una nueva estructura bitarray. [Acá están](https://github.com/sisoputnfrba/so-commons-library/blob/790dbb0db26e68e7e266690ec33f3e8046aed418/src/commons/bitarray.c#L32-L44).

Lo que se ve ahí es que la estructura bitarray no se encarga de reservar la memoria para el mismo, si no que recibe los bytes "desde afuera". Y, entonces, la convención dice que si yo no me encargo de reservar la memoria, en general tampoco me voy a encargar de liberarla.

El motivo de que el contrato de bitarray sea así es por la forma de usarlo. Un caso de uso súper común del bitarray es mantener una tabla de bits en un FS, para saber qué bloques están libres y cuáles ocupados. Esa tabla suele persistirse en un disco, y entonces una forma muy simple de usar el bitarray es `mmap`eando el archivo que contiene el bitarray, y usando directamente esa memoria para la estructura.

Lo que eso significa, también, es que _no hay que liberar esa memoria con `free`_, si no con `munmap`. ¿Cómo harías para meter ese comportamiento en la función destroy? ¿Cuántas otras formas de conseguir un cacho de memoria podrían haber? Entonces, más vale que sea el usuario del TAD quien, ya que se encarga de reservar la memoria, también se encargue de liberarla.

Un abrazo.

**Comment by SLDG1297** [comment]
Ok. Entendí re bien.

La verdad es que me quedé un poco corto de visión con esas liberaciones de memoria. Apenas vi que Valgrind no me tiraba más error, tiré el issue XD

Muchas gracias a todos. Saludos, y cierro el issue.
