### ISSUE TITLE
DUDA SIGUSR1

### ISSUE THREAD

**Issue by marrtins** [sisoputnfrba/foro#821]
Buenas,  tenemos una duda con el tema de cpu y la desconexion por SIGUSR1.. Tal como leimos en los issues #726 y #783 los podemos implementar y esa señal la tiraría desde otra consola de _linux_.. y desconectar la cpu si no esta ejecutando nada en ese momento o esperar a que termine la rafaga..

Ahora la duda es, nosotros al finalizar la rafaga, le mandamos al kernel el pcb actualizado con el exitcode, etc etc...
Esto lo hacemos igual por mas que cpu detecte la señal o ni bien termina, desconectamos la cpu sin avisarle nada al kernel y que éste se las arregle???

Muchas gracias, martín

**Comment by tferraro** [comment]
Holis, pegale una mirada a la respuesta de Cris en el #726 

Al ser una desconexión donde la cpu maneja su cierre, no debería funcionar de forma diferente a nivel algoritmo, solo que cuando termina la ráfaga/ejecución, la CPU deberìa desconectarse y listo

**Comment by marrtins** [comment]
oka listo, entonces la manejamos con normalidad y al final la desconectamos!

gracias
