### ISSUE TITLE
Multiprogramacion - Varias CPUs

### ISSUE THREAD

**Issue by gvillarc91** [sisoputnfrba/foro#822]
Tengo la siguiente duda conceptual.

Es posible tener dos instancias de la CPU corriendo SIMULTANEAMENTE dos scripts diferentes?
(En criollo, tendría que ver ambas terminales de ambas CPUs procesando instrucciones?)
Tengo entendido que el multiprocesamiento es la ejecución  simultánea posible gracias a la existencia de varios procesadores. En otro caso, habiendo un solo procesador, se simula simultaneidad con la multiprogramación.

Nunca se menciona multiprocesamiento, pero quiero asegurarme que no se me escape una consideración de diseño de este estilo.

**Comment by varas-c** [comment]
Hola!

Es como decís. La gracia de tener mas de 1 cpu es que puedan ejecutar en
paralelo.

Cuando tu kernel planifica los procesos en estado ready, deberia preguntar
si hay cpus disponible. Si hay, mandas a ejecutar un proceso. Ahora agarras
otro y si hay cpu disponible, tambien lo mandas a ejecutar y así
sucesivamente. Con éste ejemplo, tenes dos cpu ejecutando dos procesos
distintos al mismo tiempo.

Lo que no puede pasar es que un mismo proceso esté ejecutando en dos cpu
distintos al mismo tiempo (sería medio raro no?).

Cualquier duda, pasate por acá de nuevo!

Saludos!

**Comment by gvillarc91** [comment]
Clarisimo, gracias! cierro.
