### ISSUE TITLE
crearGigante y escribirFS

### ISSUE THREAD

**Issue by agustinkoszczej** [sisoputnfrba/foro#823]
Hola! 
Tenía una duda del [escribirFS](https://github.com/sisoputnfrba/ansisop-parser/blob/master/programas-ejemplo/evaluacion-final-esther/Scripts-Prueba/escribirFS.ansisop)

Escribe un _HOLA_ en un tamaño de 100, usando el **Metadata.bin** que ustedes subieron al repo del parser, dice que los Bloques son de 64, por lo que necesitaría 2 bloques (ya que es de 100 el tamaño en `escribir f a 100`). Ahora bien: debería escribir _HO_ en el Bloque 0 y _LA_ en el Bloque 1? Y que pasaría que si por ejemplo tuviera una palabra de longitud impar como _HOLAS_, cómo quedaría dividido, aunque también eso me lleva a la pregunta de si para la entrega solo vamos a usar [estos ](https://github.com/sisoputnfrba/ansisop-parser/tree/master/programas-ejemplo/evaluacion-final-esther/Scripts-Prueba) ansisops y **no** [estos](https://github.com/sisoputnfrba/ansisop-parser/tree/master/programas-ejemplo) que por ejemplo el completo ya tiene diferente sintaxis.

Y mi segunda pregunta es de qué debería pasar si yo [creoUnArchivo](https://github.com/sisoputnfrba/ansisop-parser/blob/master/programas-ejemplo/evaluacion-final-esther/Scripts-Prueba/creaArchivo.ansisop) y luego hago el [crearGigante](https://github.com/sisoputnfrba/ansisop-parser/blob/master/programas-ejemplo/evaluacion-final-esther/Scripts-Prueba/creaGigante.ansisop), ya que este ocupada justo los 24 bloques que hay en el Metadata.bin, pero ya tengo ocupado 1, además de un principio de tirar error, debería crearse el archivo? Porque es un script iterativo, y va escribiendo de a 1 bloque hasta que se llena, entonces mi duda es que si cuando el FileSystem dice que no tiene más bloques libres si debería borrarse el archivo con los bloques anteriores escritos, o lo dejo "incompleto".

Gracias!

**Comment by iago64** [comment]
Buenas buenas!!!

Respecto a tu pregunta sobre los scripts, los que se van a usar van a ser los de la carpeta [Sripts-Prueba](https://github.com/sisoputnfrba/ansisop-parser/tree/master/programas-ejemplo/evaluacion-final-esther/Scripts-Prueba)

Respecto al segundo punto, simplemente deberías avisar que no podes avanzar mas porque no tenes espacio.

Saludos.-

**Comment by tferraro** [comment]
Holis, @agustinkoszczej te sirvio la respuesta de dami? Si es asì, se puede cerrar el issue? :)

**Comment by salva-olacua** [comment]
Buenas, aprovecho este issue para preguntar por las pruebas del file system.
Nos indican que pongamos una ruta en el config, pero en esa ruta habra un FS brindado por ustedes o lo tenemos que crear nosostros?.
Espero su pronta respuesta.

**Comment by mgarciaisaia** [comment]
@salva-olacua fijate que [en el blog](https://www.utn.so/filesystem-numeracion-de-bloques/) linkeamos al FS de ejemplo 👍

**Comment by salva-olacua** [comment]
Muchas gracias por la info.
Otra duda que me quedo , es acerca del script leeBorra.ansisop .
Que debería imprimir por consola ? , ( ya que tiene una instrucción prints es script ).
Saludos.

**Comment by iago64** [comment]
Si no me falla la memoria el leeBorra.ansisop debería imprimir basura (o lo que estuviera previamente en el archivo), no es el caso de la combinacion de escribirFS y leerFS que ahí si el resultado debería entre todo lo que puede traer, ser algo que se puede leer en español :)

Saludos.-

**Comment by agustinkoszczej** [comment]
@iago64 leeBorra, leé lo del escribirArchivo (escribirFS y leerFS se manejan sobre archivo.bin, mientras que leeBorra y escribirArchivo sobre smallFile.bin) y lo de imprimir, imprime normal, porque primero imprime y después borra (si fuera al revez directamente al querer abrir el archivo te va a decir que no existe)

**Comment by gustofa** [comment]
Hola. Sobre la prueba que usa primero creaArchivo.ansisop y despues leeBorra.ansisop, el primero pone una "X" en el archivo. Pero cuando corremos leeBorra llegamos a imprimir números. No estoy seguro que sea el comportamiento esperado, pero veo que el script usa "prints n *a", esa "n" indica justamente que se imprimen números, no?

El parser usa estas funciones:
`
[TRACE] 11:50:53:256 CPU/(4910:4910): Evaluando instruccion: prints n *a

[TRACE] 11:50:53:256 CPU/(4910:4910): Obtener posicion variable [a]

[TRACE] 11:50:53:256 CPU/(4910:4910): Retorno el t_puntero [256]

[TRACE] 11:50:53:256 CPU/(4910:4910): Dereferenciar [0x100]

[TRACE] 11:50:53:256 CPU/(4910:4910): Dereferenciar [0x308]

[TRACE] 11:50:53:256 CPU/(4910:4910): Escribir [11 bytes]:1563492440 a [1]
`

Ese "1563492440" es lo que desreferenció de la variable a y es lo que llegamos a imprimir por consola. Está bien o se debería imrpimir la "X"?

**Comment by tferraro** [comment]
Holis, va bien, tiene que mostrar el numero, sino deberia ser prints s &a.
