### ISSUE TITLE
leeBorra.ansisop

### ISSUE THREAD

**Issue by gustofa** [sisoputnfrba/foro#825]
Hola.

Este es el script leeBorra.ansisop:
begin
  variables a, f
  alocar a 100
  abrir f LE /smallFile.bin
  leer f a 10
  prints n *a
  borrar f
  cerrar f
  liberar a
end

Es correcto que primero se llame a "borrar f" y luego a "cerrar f"?
Entendemos que la instrucción borrar elimina el archivo del file system en el caso que solo ese proceso lo tenga abierto, con lo cual el archivo no existirá ni en las tablas de archivos de kernel ni en el filesystem cuando luego se intente cerrar.

Es correcto este razonamiento y las instrucciones deben ir al reves?

Saludos

**Comment by sebastian-gulino** [comment]
Buenas! Te digo al menos en base a lo que armamos nosotros, las instrucciones estarían bien, el Borrar debería unicamente limitarse a eso mismo, y el cerrar el que actualice las tablas de archivos del kernel.

Por otro lado si tenes ganas, capaz esto ustedes ya lo pasaron y me podes tirar un centro con este issue que abri recien https://github.com/sisoputnfrba/foro/issues/826.

Gracias!

**Comment by agustinkoszczej** [comment]
Me adhiero a la duda de si el borrar también lo quita de las tablas por proceso y global de kernel? Y es correcto que si un proceso terminó sin cerrar el archivo que abrió si también se debería quitar de las tablas de kernel?

**Comment by gustofa** [comment]
En el parser dice:
void (*AnSISOP_borrar)(t_descriptor_archivo descriptor_archivo);
           Informa al Kernel que el proceso requiere que se borre un archivo.

void (*AnSISOP_cerrar)(t_descriptor_archivo descriptor_archivo);
 Informa al Kernel que el proceso requiere que se cierre un archivo.

Entonces en el script se pide primero eliminar el archivo y luego cerrar?

Nosotros en el borrar estamos eliminando en archivo en el filesystem y en las tablas de kernel (global y del proceso), entonces al momento de cerrar ya no hay qué cerrar...
Se debería entonces eliminar el archivo pero mantenerlo en las tablas de kernel hasta que llegue un cerrar?

**Comment by sebastian-gulino** [comment]
A mi entender si, lo unico que antes de borrarlo tenes que controlar que este abierto solo por tu proceso, si es así luz verde y borras, caso contrario se lo podes llegar a borrar a otro proceso que lo este usando. Las tablas no las tocas, al momento de cerrar ahi actualizas los valores.

Respecto a lo que dijo agustin, nosotros como medida practica siempre al finalizar un proceso revisamos que no hayan quedado archivos abiertos, y en caso de encontrarlos los cerramos

Aclaro que no soy ayudante, solo trato de darles una mano con algunas cuestiones que a nosotros también se nos presentaron.

**Comment by nicozar95** [comment]
@sebastian-gulino tiene la posta, para borrar el archivo, el proceso que pidio borrarlo tienen que ser el unico que lo tiene abierto y actualizas los valores de las tablas recien en el cerrar.

**Comment by gustofa** [comment]
Ok, lo cambio para seguir ese criterio.

Gracias.

Saludos
