### ISSUE TITLE
Resultado esperado - Escritura de archivos

### ISSUE THREAD

**Issue by sebastian-gulino** [sisoputnfrba/foro#826]
Buenas! Les hago una consulta pq estuve leyendo los issues que hay sobre escritura de archivos y no me termina de quedar claro si el resultado que estoy teniendo es el correcto.

- **creaArchivo.ansisop**: Al momento de ejecutar: " escribir f a 10" termino generando un archivo con solo 1 bloque, y dentro queda: X y 4 caracteres basura a continuacion.

- **escribirFS.ansisop**: Escribe HOLA en el primero de los dos bloques que registra para el archivo, y despues toda basura. Entiendo que es porque tengo que escribir con un tamaño de 100, pero la verdad que al no tener contra que contrastar el resultado para ver si esta bien me desorienta. 

![image](https://user-images.githubusercontent.com/7218670/28650991-90d1b924-7255-11e7-9c4a-86f2c861a09b.png)

![image](https://user-images.githubusercontent.com/7218670/28651005-a444fe9e-7255-11e7-8f3c-da0a55282315.png)

Gracias!

**Comment by nicozar95** [comment]
Buenas

> creaArchivo.ansisop: Al momento de ejecutar: " escribir f a 10" termino generando un archivo con solo 1 bloque, y dentro queda: X y 4 caracteres basura a continuacion.


Lo importante de creaArchivo.ansisop es que el archivo creado tenga 10 bytes de tamaño, osea, al momento de ver el archivo que figure que tenga un tamaño de 10. ¿Va a escribir basura? Si. Lo importante de este script es que el archivo se cree y que su creacion sea con el tamaño adecuado(10 bytes).

> escribirFS.ansisop: Escribe HOLA en el primero de los dos bloques que registra para el archivo, y despues toda basura. Entiendo que es porque tengo que escribir con un tamaño de 100, pero la verdad que al no tener contra que contrastar el resultado para ver si esta bien me desorienta.

Me mareaste un poco con las fotos que subiste, esta bien que escriba datos basura porque pasa lo mismo que en el anterior. Te damos mas bytes para escribir de los que realmente estas usando.

**Comment by sebastian-gulino** [comment]
Ahi esta perfecto! El primero se me generó con 10 bytes, ahora en el segundo caso los dos archivos de bloque se me generaron por 64 bytes, entiendo que debo tener un error al armar el segundo... ahora voy a revisarlo.

Las fotos que pretendian aclarar algo (e hicieron el efecto inverso jajaja) era lo que veia con un editor de texto dentro de los .bin de cada bloque!

**Comment by agustinkoszczej** [comment]
@nicozar95 Y cuando imprima eso con el leerFS.ansisop, debería mostrar basura? Porque en nuestro caso al escribir HOLA en la página del Heap y después tener espacios vacios, cuando arma la palabra "HOLA  (muchos espacios en blanco con \0 de cosas sin ocupar por el alocar de 100)" al tener esos espacios en blanco la palabra termina en "HOLA" y se escribe HOLA en el FS, y se imprime HOLA en Consola

**Comment by nicozar95** [comment]
@agustinkoszczej Si esta bien, siempre y cuando el tamaño del archivo creado en el fs es de 100. Y se manejen bien los bloques del heap
