### ISSUE TITLE
Ayuda con ubuntu server

### ISSUE THREAD

**Issue by santinucera** [sisoputnfrba/foro#827]
Hola quería saber si había algún ayudante disponible entre hoy y mañana en los laboratorios de medrano que me puedan ayudar con el tema de ubuntu server que no se bien como usarlo. Muchas gracias.

**Comment by varas-c** [comment]
Hola!

Qué es especificamente lo que no sabés usar?

-No podes levantar la VM?
-No sabés usar la Consola y las instrucciones?

**Comment by santinucera** [comment]
No se usar la consola y las instrucciones. Tampoco muy claro como levantar VM

**Comment by iago64** [comment]
Buenas?

Respecto a como levantar la VM, la misma la levantas igual que la de lubuntu, con la unica diferencia que en lugar de tener la GUI vas a tener una terminal donde te va a pedir usuario y password (utnso en ambos casos)

Respecto a los comandos de la consola, te recomiendo que si podes le des una revisada al juego de [Mario Bash](http://mariobash.utn.so/) (jugandolo con la intro).

Espero haber podido ayudarte un poco.
Saludos.-
