### ISSUE TITLE
Leak de memoria en pthread_create

### ISSUE THREAD

**Issue by aocoda** [sisoputnfrba/foro#829]
Buenas!. Queria consultar sobre un leak que me esta registrando valgrind en la consola específicamente en el pthread_create(). Este leak se registra únicamente si al correrla con valgrind yo mato la consola con Ctrl + C, todos los hilos que no hayan sido finalizados mediante el comando finalizarPrograma tiene exactamente el mismo leak. Para tratar de solucionarlo me puse a revisar mi función a la que llamaba el pthread_create() dado que no encontraba ningún error del estilo malloc sin free lo proba hasta comentando todo el código de la función e incluso así me seguía perdiendo la misma cantidad de bytes. Ahora bien, nosotros creamos los hilos así:

	//Thread ID
	pthread_t threadId;

	//Create thread attributes
	pthread_attr_t attr;
	pthread_attr_init(&attr);

	//Set to detached
	pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_DETACHED);

	//Create thread
	pthread_create(&threadId, &attr, executeProgram, programPath);

Se suponía que el problema de una desconexión de la consola se solucionaba haciendo que los estén detached. Valgrind me dice de  "Possibly Lost: 136 bytes" por cada hilo no matado son 136 bytes mas.

siendo el log de valgrind este:

==3868== 136 bytes in 1 blocks are possibly lost in loss record 12 of 13
==3868==    at 0x402C109: calloc (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==3868==    by 0x401117E: allocate_dtv (dl-tls.c:296)
==3868==    by 0x40118EB: _dl_allocate_tls (dl-tls.c:460)
==3868==    by 0x40647A2: pthread_create@@GLIBC_2.1 (allocatestack.c:589)
==3868==    by 0x804937F: startProgram (consola.c:117)
==3868==    by 0x80492BE: showMenu (consola.c:75)
==3868==    by 0x804006F: ???
==3868== 
==3868== LEAK SUMMARY:
==3868==    definitely lost: 0 bytes in 0 blocks
==3868==    indirectly lost: 0 bytes in 0 blocks
==3868==      possibly lost: 136 bytes in 1 blocks
==3868==    still reachable: 654 bytes in 15 blocks

Alguna posible solución?

Gracias!

**Comment by iago64** [comment]
Buenas?

Ahi lo que te quiere decir valgrind es que posiblemente termines perdiendo esa cantidad de bytes si no haces el free, pero todavía no los perdiste. Si ese es el unico punto complicado del tp te diria que enfoques en cumplir y revisar leaks mayores en cosas que sean recurrentes como por ej serializar un mensaje y no con esto que eventualmente vas a perder 136 bytes por cada hilo.

Saludos.-

**Comment by aocoda** [comment]
Gracias @iago64 por responder. Entonces no me preocupo por ese leak en particular. Cierro el issue
