### ISSUE TITLE
Grado Multiprogramacion Kernel

### ISSUE THREAD

**Issue by agustinkoszczej** [sisoputnfrba/foro#830]
Una pregunta, si yo por ejemplo tengo grado de multiprogramación 3, y tengo corriendo 3 scripts corriendo en paralelo en 3 CPUS con Round Robin, si bajo el grado de multiprogramación a 2 mientras estan ejecutando, cuando algún script termine su quantum y pasé de exec a ready, va a seguir ejecutandose los 3 scripts por más que haya grado de multiprogramación de 2, porque ya están en Ready y cargados en memoria no?
Gracias!

**Comment by mgarciaisaia** [comment]
> cuando algún script termine su quantum y pasé de exec a ready, va a seguir ejecutandose los 3 scripts por más que haya grado de multiprogramación de 2, porque ya están en Ready y cargados en memoria no?

![476375](https://user-images.githubusercontent.com/1190974/28739105-76416288-73ce-11e7-9228-86d73ad0ff55.jpg)


La pregunta es **muy buena**. Y la respuesta que conjeturaste también.

Pensándolo desde el lado de la memoria, sí, tiene todo el sentido del mundo que si el programa _ya tiene_ memoria reservada, entonces siga ejecutando, por más que esté pasado del límite.

Pero también es válido pensar que si como administrador del sistema pongo un límite de procesos, ese límite debiera cumplirse, y entonces **también aceptamos como válido** que al cambiar este límite, sólo 2 procesos queden ejecutando (y el tercero quede en Ready, ponele).

Pero la opción que proponés es súper correctísima 👍

¡Salutes!
