### ISSUE TITLE
Consumidor-Productor

### ISSUE THREAD

**Issue by sebaplawner** [sisoputnfrba/foro#831]
Buenas tardes,

Me surgió una duda después de leer un issue reciente sobre el comportamiento de los semáforos y quería verificar que los de nuestro TP funcionen como corresponden. Van unos casos:

Semáforo c inicializa en 0
Abro 2 Consumidores, los 2 se bloquean, el semáforo c queda en -2
Aborto ambos procesos, el semáforo vuelve a su estado original 0

Ejecuto un Productor, hace un signal y se bloquea.
Lo cierro y su semáforo vuelve al estado original, mientras que al que hizo el signal permanece +1 de su estado inicial.

Si pongo muchos productores y consumidores se alternan tanto la producción como el consumo. Muestra bien los datos. Corto todo y los semáforos no siempre vuelven a su estado original. Algunos tiraron más signals y queda b=2 c=0 cuando deberá ser b=1 c=0.
Si vuelvo a arrancar una secuencia cualquiera, funciona, pero los semáforos ya no vuelven a su estado original, quedan "desconfigurados". Andando, pero "desconfigurados".

¿Está bien que se produzcan estos fenómenos?

Gracias.

**Comment by mgarciaisaia** [comment]
Mientras que tengan sentido los valores que quedan (digamos, si hubieron 3 `signal`s en total, que ese semáforo no quede en 25), sí, está joya.

En el ejemplo del TP es medio un chiste, porque más allá de hacer `signal` y `wait`, no hay _algo_ que realmente se esté produciendo.

Pero pensá en el ejemplo típico de un buffer (una cola de mensajes, ponele) en el que se produce y consume, y que tiene un límite máximo de tamaño. Si el buffer está vacío y meto un consumidor, no tiene nada para hacer, y "el sistema le debe un mensaje" - el semáforo está en -1.

Si ahí saco a ese consumidor, ya no debo nada - incremento el semáforo en 1, para dejarlo en 0, y todos felices.

Ahora bien, si el sistema está vacío y meto un productor, éste mete un mensaje en el buffer, y elimino al productor del sistema, ¿cómo quedó el sistema? Bueno, tengo 1 mensaje listo para ser consumido, entonces el semáforo debería reflejar eso.

TL;DR: suena completamente razonable lo que contás.

¡Un abrazo!
