### ISSUE TITLE
no consigo instalar mod_evasive 

### ISSUE THREAD

**Issue by pythonGHub** [sisoputnfrba/foro#834]
Hola uso plesk en la version onyx 17.5.3 quiero instalar mod_evasive pero plesk no lo tiene osea que tengo que instalarlo via ssh pero no lo consigo me da muchos errores nunca instale nada en mi servidor que no venga implementado en plesk estos son los requisitos.

CentOS Linux 7.3.1611 (Core)
Server version: Apache/2.4.6 (CentOS)

necesitaria realizar bien los pasos para poder instalar mod_evasive es un 64bits espero me puedan ayudar.
Saludos

**Comment by sciciliani** [comment]
Hola,

Para esa version de Centos entiendo que esta el rpm. Encontre este link, espero que te pueda ayudar.

https://www.digitalocean.com/community/tutorials/how-to-protect-against-dos-and-ddos-with-mod_evasive-for-apache-on-centos-7

Por otro lado tengo la curiosidad de saber como terminaste abriendo un issue con esta consulta en nuestro tracker que nada que ver, pero todo bien...

**Comment by pythonGHub** [comment]
ese enlace ya lo intente pero no lo consigo creo que no esta en el repositorio . perdon creo que me equivoque.
alguien me puede mover al sitio correcto.
gracias
