### ISSUE TITLE
Segmentation Fault con función de las commons

### ISSUE THREAD

**Issue by pabloquinci** [sisoputnfrba/foro#835]
Buenas que tal?

Estoy teniendo un inconveniente con la funciona "config_has_property" cuando la quiero usar para levantar una configuración de cliente. Me tira un segmentation fault que me provoca la desconexión automática cuando intento enviarle datos a un servidor. Dejo las capturas de dónde es utilizada dicha función y el error que me tira

![image](https://user-images.githubusercontent.com/11711534/29806910-01b8ba44-8c68-11e7-9f10-612a29eda86c.png)

![segmentation fault](https://user-images.githubusercontent.com/11711534/29806874-e195fa06-8c67-11e7-9799-83caf2a30384.PNG)

Gracias

Saludos,
Pablo

**Comment by nicozar95** [comment]
Buenas
¿Que le estás pasando a la función en el momento que llamas a "config_create"?
Saludos

**Comment by mgarciaisaia** [comment]
Si pasás por #32 podés leer a Joaco llamándome _hermoso_ - y la probable [explicación y solución a tu problema](http://mgarciaisaia.github.io/tutorial-c/blog/2015/04/23/rutas-argentinas/).

**Comment by pabloquinci** [comment]
Sii era la ruta reativa que le estaba pasando y que en la consola me la tomada desde Debug!
Gracias @mgarciaisaia @nicozar95 !

Saludos
