### ISSUE TITLE
Estilografo encontrado

### ISSUE THREAD

**Issue by tferraro** [sisoputnfrba/foro#836]
👋 ¡Hola!

Luego de la charla de la tarde del día de ayer, encontramos un estilógrafo 0.05 (0.5mm) con cierto personaje bastante conocido del Studio Ghibli.

Si es tuyo, voy a andar por Medrano durante la noche de Martes a Viernes y el sábado durante la mañana; así como en la 3er charla.

Fin del comunicado!

Tom

**Comment by nicozar95** [comment]
![image](https://user-images.githubusercontent.com/11698687/30255805-8584707a-967c-11e7-9a45-65f9fc912173.png)

Si no lo reclaman en el checkpoint sera propiedad de @afilgueira

**Comment by tferraro** [comment]
![image](https://media.diariopopular.com.ar/adjuntos/143/imagenes/004/072/0004072573.jpg)

Este sábado a la tarde hay revancha. Metele al Quini poniendole las fichas a Totoro, que sale si o si!

**Comment by fedebonisconti** [comment]
Por lo visto ya es propiedad de @afilgueira. Cierro el issue 🙃
