### ISSUE TITLE
Archivo de configuracion FileSystem

### ISSUE THREAD

**Issue by CarolinaPonceRodriguez** [sisoputnfrba/foro#837]
Buenas nuevas!

Posteo porque veo que falta el archivo de configuracion para el filesystem, en principio estimo que lleva puerto jaja, pero quiza deba contar con otras variables que estoy pasando por alto.

Saludos.

**Comment by tferraro** [comment]
Buenas!

No hay necesidad obligatoria del uso de un archivo de configuración en el FS. Esto es, principalmente, porque será el FS quien creará sus archivos de trabajo (tablas de directorios, nodos, archivos).

De todas maneras, son buenas prácticas contar con un archivo de configuración donde contar, por ejemplo, del puerto como decís, o del directorio donde se va a encontrar la carpeta de metadata del FS, pero esto ya es opcional y depende de como desee diseñar tu TP cada grupo.

Saludos!

Tom

**Comment by CarolinaPonceRodriguez** [comment]
Buenas, 
Debiera estar correctamente aclarado en el enunciado entonces ya que dice: "Al iniciar, leerá su archivo de configuración y quedará a la espera de las conexiones de los procesos DataNode". Cualquiera entendería que el mismo es de carácter obligatorio y esperaría encontrarlo en la especificación de FS.

Cierro.
Saludos!
