### ISSUE TITLE
Dudas Enunciado - FS - Archivos binarios y de texto

### ISSUE THREAD

**Issue by dromero-7854** [sisoputnfrba/foro#838]
Buenas a todos,

Estoy leyendo la sección de FS del enunciado, y me queda una duda con lo siguiente:

> En el caso de los archivos de texto, dado que los mismos pueden no necesariamente
terminan alineados a 1 MB, para evitar que queden registros partidos la operación de
escritura debe asegurarse antes de escribir cada nuevo renglón (\n)3 que el espacio en el
bloque sea suficiente.

La duda **¿Debo guardar el archivo en bloques por cada cada salto de linea (\n)? (considero que cada linea no supera 1MB)** 
**¿O considero el tamaño del archivo completo para saber cuantos bloques se necesitan?**
Por ejemplo, si el archivo pesa 3670016 bytes (3,5MB), serian 3 bloques y medio (sin contar los bloques de las copias)

Espero sus comentarios...
Gracias!

**Comment by tferraro** [comment]
Buenas!

El enunciado plantea 2 escenarios, un archivo **binario** y un archivo de **texto**.

Para el 2do caso, para evitar que las líneas queden partidas se debe analizar cuando se quiera partir en bloques, que una línea no quede cortada, debiendo ser escrita en el siguiente bloque (para no sobre pasar el tamaño del bloque).

> ¿Debo guardar el archivo en bloques por cada cada salto de linea (\n)? (considero que cada linea no supera 1MB)

Nope, lease arriba

> ¿O considero el tamaño del archivo completo para saber cuantos bloques se necesitan?

Tampoco, es solo válido si el archivo es binario, si es un archivo de texto, la cosa cambia.


Se te ocurre alguna razón porque es así? 

Saludos!

Tom

**Comment by cmedrano** [comment]
Yo entiendo que lo que hay que lograr es que el registro(reglòn) completo este en un solo bloque y no partido en dos bloques, por eso hay que leer el registro siguiente y validar que tengas espacio en el bloque actual para guardarlo si lo tenes entonces lo grabas en el bloque actual y si no te alcanza el espacio entonces lo guardas en otro bloque.

**Comment by dromero-7854** [comment]
Ok... Ahi entendi la idea. 

La verdad no se me ocurre cual sería el motivo porque es así. Pero tampoco entiendo bien todavía la idea general del tp (¿la idea del tp es comprimir archivos? ¿qué contenido tienen los archivos? ¿si ahorcas a un pitufo, de qué color se pone?) 

Esto recien comienza. Seguro más adelante voy a ir decantando todo el tp.

Gracias por la aclaración. Doy por cerrado el issue.

Saludos!

**Comment by dromero-7854** [comment]
Perdón por reabrirlo, pero me quedo una duda más:

Siguiendo la lógica planteada: Cada linea, no debe abarcar más de un 1 MB (tamaño de cada bloque) ¿no?

**Comment by sciciliani** [comment]
Correcto. Podes tomar como restricción implícita que no hay "renglones" de
más de 1M.

**Comment by nicozar95** [comment]
Buenas
Las lineas de los registros no van a ser de mas de 1MB ya que deberia entrar toda una linea en un bloque y que no te queden lineas cortadas.

> Pero tampoco entiendo bien todavía la idea general del tp (¿la idea del tp es comprimir archivos? ¿qué contenido tienen los archivos? ¿si ahorcas a un pitufo, de qué color se pone?)
> 
> Esto recien comienza. Seguro más adelante voy a ir decantando todo el tp.

Estamos para ayudarlos:

> ¿la idea del tp es comprimir archivos? 

- No, vendria a ser un sistema de procesamiento distribuido que se encarga de muchas tares. Se utilizan mucho para analizar casos cientificos y procesamiento de grandes cantidades de datos. 
**Por ejemplo:**
Suponete que Google tiene los datos de en que año nacieron cada una de las personas del mundo (alrededor de 7mil millones) y quieren sacar un promedio de todo. Si hacen un programa que vaya recorriendo cada uno de esos registros en una sola computadora, tardaria banda en sumar todos esos registros. Entonces lo que hace Google es separar esos 7mil millones de registros en registros mas chicos, que cada maquina los procese y dsp junta el resultado de todas esas maquinas en uno.
Eso fue un ejemplo, la idea principal es evitar que una computadora haga todo el procesamiento del programa independiente de que registros sean y que haga el programa (de aca el tema de la caja negra).

> ¿qué contenido tienen los archivos?

- Los archivos de texto van a contener texto en forma de registros y los binarios van a contener datos que parecen basura al abrirlos como `cat gatitos.jpg`, porque no son de texto (gatitos.jpg es esta [foto](https://notasdemascotas.com/wp-content/uploads/2015/02/que-hacer-cuando-traes-un-gatito-a-casa-324x235.jpg))

> ¿si ahorcas a un pitufo, de qué color se pone?

Violeta

Saludos

**Comment by dromero-7854** [comment]
Jaja No se porque no pensé en Violeta... Gracias por la info!

Saludos!!
