### ISSUE TITLE
[FileSystem] Dudas conexiones y data.bin

### ISSUE THREAD

**Issue by DanielMarcelletti** [sisoputnfrba/foro#839]
Buenas, tenemos un par de dudas en cuanto al proceso FS:

1) A la hora de conectar el proceso YAMA al FS:
a) ¿Tengo que esperar indefinidamente a adquirir un estado estable y recien ahí permitir la conexion de YAMA? ó 
b) si YAMA se conecta, y aún no adquirí un estado estable ¿debo cerrarle la conexión y terminar el proceso YAMA de forma abortiva?

En caso de ir por la opción b), ¿es correcto aceptar la conexión, realizar el handshake y en ese momento chequear si el sistema se encuentra en estado seguro?

2) ¿El proceso FS tiene un único puerto para aceptar todas las conexiones, o un puerto para YAMA y otro para Nodos ?

3) Por último, el tamaño del archivo data.bin, en caso de ser creado, el tamaño: ¿esta definido por el usuario a través de la consola, por archivo de configuración o por alguna otra opción que no se me ocurre en este momento?

Muchas gracias desde ya por su tiempo !

Saludos !

**Comment by nicozar95** [comment]
Buenas

> A la hora de conectar el proceso YAMA al FS:
> a) ¿Tengo que esperar indefinidamente a adquirir un estado estable y recien ahí permitir la conexion de YAMA? ó

No indefinidamente, solo hasta que tenga una copia de cada uno de los archivos del FS. Recien cuando esta en un estado estable, se puede conectar con YAMA.

> b) si YAMA se conecta, y aún no adquirí un estado estable ¿debo cerrarle la conexión y terminar el proceso YAMA de forma abortiva?

Asi es

> En caso de ir por la opción b), ¿es correcto aceptar la conexión, realizar el handshake y en ese momento chequear si el sistema se encuentra en estado seguro?

Si eso deberian chequear a la hora de establecer las conexiones FS-YAMA

> ¿El proceso FS tiene un único puerto para aceptar todas las conexiones, o un puerto para YAMA y otro para Nodos ?

No esta especificado, pueden hacerlo de cualquier manera.

> Por último, el tamaño del archivo data.bin, en caso de ser creado, el tamaño: ¿esta definido por el usuario a través de la consola, por archivo de configuración o por alguna otra opción que no se me ocurre en este momento?

Ni bien se levanta un nodo puede leer el archivo de configuracion la ruta del data.bin, por ejemplo: `/hom/utnso/data.bin`. 

El mismo se debio haber creado con anterioridad con comandos en la consola de linux como:
 `truncate data.bin --size [tamanio]` o se lo podemos dar nosotros con un par de bloques ya grabados.

El tamaño del archivo `data.bin` va a estar definido en las evaluaciones del TP. Lo importante es que ustedes sean capaces de dividir logicamente este archivo en bloques de 1MB, para que al sistema le de lo mismo levantar un data.bin de 30MB como de 5MB 

Saludos

**Comment by DanielMarcelletti** [comment]
Fantástico Nico, muchas gracias por tu respuesta !

Saludos !
