### ISSUE TITLE
Como importar la biblioteca de readline a mi proyecto?

### ISSUE THREAD

**Issue by gerosamore** [sisoputnfrba/foro#840]
Cuando quier utilizar el readline(), primero importo el header "#include <readline/readline.h>" pero no encuentra el archivo. Alguien sabe como importarlo? Gracias

**Comment by tferraro** [comment]
Buenas!

Si bien `readline` es una biblioteca de GNU, no es parte del standard, por lo que hace falta agregarla como dependencia (ese flag `-l`  que tiene gcc!). Te recomiendo que le pegues una mirada a los videos que tenemos en el blog ([https://www.utnso.com/recursos/video-tutoriales/](https://www.utnso.com/recursos/video-tutoriales/) y particularmente [este video](https://www.youtube.com/watch?v=9GHERvUS6m8), aunque esté en ingles 😛.

Era eso? O ya lo habías intentado? Comentanos que onda!

Saludos!

Tom

PD: Psss, porfis no digas librería 👮 , es biblioteca. Cada vez que alguien lo dice, se muere un gatito 😢 .

**Comment by gerosamore** [comment]
ok, mil gracias.

**Comment by melaibanez** [comment]
Gracias, me sirvió mucho!
