### ISSUE TITLE
Diseño de Nodo

### ISSUE THREAD

**Issue by maacosta** [sisoputnfrba/foro#842]
Consulta con respecto a este concepto de Nodo.
Entiendo que el DataNode y el Worker (o workers) son ejecuciones separadas, pero, podría ser un solo proceso (Nodo) que crea un hilo para manejar el DataNode y otro hilo para manejar el Worker (o workers)?
Pregunto esto ya que ambos trabajan sobre el mismo archivo y leen la misma configuración.

**Comment by nicozar95** [comment]
Buenas

La respuesta corta es:
NO
La respuesta larga es:
No porque los workers requieren la ejecucion de procesos hijos y al forkear un programa que tiene hilos, lo que va a pasar es que se van a bloquear todos los hilos salvo el ejectubable, entonces esto puede llegar a traer problemas.
Se diseño por esa razon, para evitar tener este problema con los hilos y demas. Ademas es mas facil tener las responsabilidades de los procesos separados :smile: 

Saludos

**Comment by lucasnvp** [comment]
Me sumo a otra pregunta respecto al Diseño del Nodo; en el archivo de configuración del Nodo menciona el puerto del DATANODE, tengo entendido que se DATANODE se conecta al servidor del FileSystem. Mi consulta es: se necesita un servidor en el DATANODE?

**Comment by tferraro** [comment]
Holis,

@lucasnvp el archivo de configuración del Nodo es único, justamente por eso es utilizado por tanto el Worker como el DataNode.

Ambos son procesos diferentes que lo unico que comparten es la apartura de el data.bin y el archivo de configuración. Sabiendo que el DataNode se conecta al FS tal como dijiste, porqué plantearías un escenario en el que el DataNode necesitaría ser un servidor? Que crees que te aporta si es así/o si no lo fuera?

**Comment by afilgueira** [comment]
@veritoreinoso @Natt87

**Comment by lucasnvp** [comment]
@tferraro con más razón, yo creo que el DataNode no necesita un servidor porque la conexión que necesita con el FileSystem ya esta establecida. Lo que me genera duda es para que necesita otro puerto el DataNode? Osea, en el archivo de configuración el puerto del DataNode, para que finalidad es?

**Comment by tferraro** [comment]
Eso, es a lo que le llamamos una errata😛. Good catch

Efectivamente quedó colgada esa entrada en el archivo de configuración. No
haría falta el puerto del DataNode en esta Arquitectura.

Obvialo mientras cocinamos la errata😉

Saludos!

Tom

**Comment by gustofa** [comment]
@dromero-7854

**Comment by lucasnvp** [comment]
@tferraro  Muchas gracias!

**Comment by tferraro** [comment]
Buenas! @maacosta te sirvió la respuesta de Nico?

**Comment by maacosta** [comment]
Perfecto Gente!
