### ISSUE TITLE
pregunta sobre RR

### ISSUE THREAD

**Issue by guillermo126** [sisoputnfrba/foro#843]
Buenas ¿como estan?

les hago una pregunta para planificacion para RR ¿la etapa de transformacion seria un quantum, la de reduccion local seria otroa y la global otro? 
o ¿un job entero de tres etapas cuenta como un quantum?

Saludos.

**Comment by tferraro** [comment]
Buenas!

Asumí que cada operación a realizar (transformación, reducción, etc) tiene un **único** quantum de peso.

**Comment by guillermo126** [comment]
Perfecto gracias ;)
