### ISSUE TITLE
Proceso Worker - Enunciado - guardar resultado reduccion global en yamafs

### ISSUE THREAD

**Issue by alejandrog87** [sisoputnfrba/foro#844]
Buenas noches, 

Tengo una consulta sobre el enunciado en cuanto a la responsabilidad del proceso Worker, en la charla del sábado pasado hicieron énfasis que el proceso Worker solo guarda los resultados de las transformaciones y reducciones de forma local, en el diagrama de la arquitectura del sistema no existe conexión entre el proceso Worker y el proceso FileSystem. Sin embargo en el apartado de solicitud de almacenado final de YAMA (página 12) indica :

> "El proceso Master entonces le solicitará al Worker encargado que se conecte al Filesystem
> y le envié el contenido del archivo de Reducción Global y el nombre y ruta que este deberá
> tener
> Concluida​ ​esta​ ​operación​ ​se​ ​da​ ​por​ ​terminado​ ​el​ ​Job​ ​y​ ​el​ ​proceso​ ​Master​ ​terminará.
> Si la operación de escritura del archivo en el FileSystem fallara, el Worker deberá informar
> el error al proceso Master, quien a su vez deberá notificarlo a YAMA.".
> 

Por ésta linea entiendo que es responsabilidad del Worker conectarse al FileSystem y utilizar la interfaz de éste último para persistir el archivo resultante de la reducción global en el YamaFS, lo cual contradice lo dicho en la charla y nos presenta un poco de confusión. ¿Quièn es el que realiza la solicitud al FileSystem para persistir el archivo?¿Si el resultado de la solicitud es una falla FileSystem se lo notifica al Worker y este empieza la cadena hacia Master y Yama como indica el enunciado o es de otra manera?

Gracias

**Comment by nicozar95** [comment]
Buenas
A mi tambien me confundio ese parrafo pero te cuento masomenos como va la mano:

> ¿Quièn es el que realiza la solicitud al FileSystem para persistir el archivo?

A ultimo momento, una vez que el Worker hace el apareo entre nodos, ese se conecta a el Filesystem y le pasa el archivo, osea el Worker le solicita que persista este archivo.

> ¿Si el resultado de la solicitud es una falla FileSystem se lo notifica al Worker y este empieza la cadena hacia Master y Yama como indica el enunciado o es de otra manera?

Solo cuando falla la escritura del archivo, por ejemplo porque no hay mas bloques, entonces el Worker le dice al master y este a Yama para notificarlo.

Saludos

**Comment by iago64** [comment]
@alejandrog87 Este tema se puede cerrar? fue respondida tu consulta? Hay algo mas con lo que te podamos ayudar?

**Comment by alejandrog87** [comment]
Gracias. Cierro el issue
