### ISSUE TITLE
Proceso YAMA - Diseño - Notificaciòn Workers a Yama

### ISSUE THREAD

**Issue by alejandrog87** [sisoputnfrba/foro#845]
Buenas noches, tenemos la siguiente consulta:

Según el enunciado el responsable de balancear la carga de trabajo de los nodos/worker es el proceso Yama, por lo cual, éste debería tener noción de toda conexión/desconexiòn de los worker, sin embargo, en el diagrama del sistema no hay relación entre el proceso Worker y Yama. El Worker es por naturaleza Server, espera la conexión de un proceso Master, nosotros pensamos que como parte del proceso de inicializaciòn del proceso worker debería notificar al proceso YAMA (mediante un mensaje) su ingreso al sistema. La parte de la liberación del worker (porque terminò la etapa normalmente o de forma abrupta) la notifica el proceso Master a Yama según lo que entendimos. Queríamos validarlo con ustedes.
Gracias.

**Comment by tferraro** [comment]
Buenas!

A diferencia de capas otras partes del diagrama, cuyas conexiones omitimos
para que no sea un mamarracho, YAMA *nunca* se conectará directamente con
los Workers.

Si bien YAMA interactua con los workers mediante los Masters, puede llegar
a tener noción de la existencia de los mismos de antemano, usando las
conexiones existentes, se te ocurre como haría para conocer la información
del ip y puerto de los Workers?

Algo a tener en cuenta: Los Nodos son una entidad lógica que si bien a
fines prácticos termina siendo olvidada, para el resto del sistema no se
están conectando a DataNode 2 o al Worker 2, se están conectando al Nodo2,
sin tener conocimiento de que son 2 procesos diferentes.

Saludos!

Tom

**Comment by gustofa** [comment]
Hola.

> Si bien YAMA interactua con los workers mediante los Masters, puede llegar
a tener noción de la existencia de los mismos de antemano, usando las
conexiones existentes, se te ocurre como haría para conocer la información
del ip y puerto de los Workers?

DataNode podría pasarle a Filesystem además de sus datos, el puerto del worker, para que éste se lo de a YAMA, la IP será la misma que el DataNode, obviamente.
Es correcto?

Saludos

**Comment by sciciliani** [comment]
Es correcto. El DataNode comparte el archivo de configuración con el Worker

**Comment by iago64** [comment]
@alejandrog87 Este tema se puede cerrar? fue respondida tu consulta? Hay algo mas con lo que te podamos ayudar?

**Comment by alejandrog87** [comment]
Gracias por sus aportes. Cierro el issue.
