### ISSUE TITLE
Proceso Yama - Enunciado - Espera en planificaciòn de Jobs

### ISSUE THREAD

**Issue by alejandrog87** [sisoputnfrba/foro#846]
Buenas noches,

Querìamos validar lo siguiente con ustedes:
El Proceso Yama es el encargado de balancear los jobs entre los nodos existentes en el sistema, supongamos el caso en que se inicializan 16 jobs (cada uno en su Master) , y actualmente en el sistema hay 4 nodos (4 workers) , Yama va a ir distribuyendo cada etapa de los jobs entre esos 4 nodos comunicandoselo a cada master , y cada worker deberà ir forkeandose para atender la solicitud de cada master cierto? osea no hay ningún tipo de "espera" por parte de los jobs, no es que si un nodo ya està ocupado con una etapa de otro job, el nuevo job debe "esperar" a que se encuentre liberado. Entendemos que Yama va a mantener una cola por cada nodo donde se van a ir encolando las etapas de cada job a procesar y que va a ir limpiando a medida que la etapa concluya.

Gracias

**Comment by nicozar95** [comment]
Claro, te aclaro una cosa que me hizo un poco de ruido:

> cada worker deberà ir forkeandose para atender la solicitud de cada master cierto?

Se va forkeando por cada una solicitud de tareas del master y el proceso hijo termina. El Worker permite la ejecuccion en paralelo ya que estamos trabajando con procesos hijos, lo importante es que la carga de trabajo sea distribuida para cada Nodo

**Comment by guillermo126** [comment]
Buenas agrego una consulta: cuando por ejemplo en un job hay 3 transformaciones y master le pide la etapa de transformacion a yama, primero yama le manda la lista con todos los nodos a los que se tiene que conectar master y despues de ya enviada la lista enmediatamente deberia planificar el job? estaria en lo correcto o me equivoco?

**Comment by iago64** [comment]
@guillermo126 Exacto, una vez que YAMA te dice donde tenes que ejecutar cada transformación, vos desde Master creas un hilo por cada transformación y te conectas a los Worker.
El retardo es parte del [proceso YAMA](https://sisoputnfrba.gitbooks.io/yama-tp-2c2017/content/proceso-yama.html) :)

**Comment by tferraro** [comment]
> ...primero yama le manda la lista con todos los nodos a los que se tiene que conectar master y despues de ya enviada la lista enmediatamente deberia planificar el job?...

Guarda con esto. Master no planifica, YAMA si. YAMA planifica asignación de recursos al Job y una vez que ha dicidido que nodos van a ser utilizados, le pasa la lista a Master para que el haga su trabajo.

**Comment by alejandrog87** [comment]
Tengo una consulta respecto a esto, Yama debería planificar por etapas no? Osea primero manda la lista de los nodos que van a relaizar las transformaciones (si son 5 transformaciones una lista de 5 nodos), después la reducción local y por último la global, va decidiendo esto según la carga de los nodos. O manda todo junto ? Y si Yama manda por etapas es posible que llegue a completar una y se quede sin nodos para otra (por desconexión por ejemplo) en ese caso aborta el job, cierto?

**Comment by tferraro** [comment]
>  Yama debería planificar por etapas no? Osea primero manda la lista de los nodos que van a relaizar las transformaciones (si son 5 transformaciones una lista de 5 nodos), después la reducción local y por último la global, va decidiendo esto según la carga de los nodos.

Efectivamente

> Y si Yama manda por etapas es posible que llegue a completar una y se quede sin nodos para otra (por desconexión por ejemplo) en ese caso aborta el job, cierto?

Si; solamente el fallo de una tarea de transformación se replanifica.

**Comment by alejandrog87** [comment]
Cierro el issue. Gracias
