### ISSUE TITLE
[Checkpoint 1] - Consulta propagación de archivo 

### ISSUE THREAD

**Issue by mtimossi** [sisoputnfrba/foro#847]
El hito 1 del TP pide:
_Desarrollar una comunicación simple entre los procesos que permita propagar un archivo abierto por Master._

A que se refieren con esto? Deberíamos hacer que master mande un archivo cualquiera a través de todos los procesos?

Saludos.

**Comment by jazcarate** [comment]
El proceso **Master** solo enviará archivos enteros al proceso **Worker**, por lo que solo haría falta codificar esta una conexión.
La idea de ese punto del checkpoint es que se familiaricen con la lectura de un archivo que está en el disco; y que puedan mandar contenido de tamaño variable mediante sockets a otros procesos.
Ambas cosas van a tener que replicarlas -en mayor o menor medida- a lo largo de todos los procesos.
