### ISSUE TITLE
Proceso FS/DataNode - Tamaño de nodo y cantidad de bloques

### ISSUE THREAD

**Issue by Gruschka** [sisoputnfrba/foro#849]
Hola!

Tengo unas duda respecto al enunciado, mas específicamente con los tamaños de los nodos y persistencia del FS

1. Menciona que el tamaño de cada bloque será de 1MB y en el apartado de data.bin dice que para que un nodo tenga 20MB de almacenamiento su archivo de datos deberá ser de 20mb para que tenga 20 bloques de 1mb. Como sabemos el tamaño que va a tener cada nodo para crear su archivo de datos con el tamaño correspondiente?
2. El FS tiene que persistir archivos en una carpeta llamada metadata (tabla de nodos, tabla de archivos, bitmap, etc). Mi duda al respecto es: El directorio donde se monta el filesystem lo tenemos que elegir nosotros o es justamente la carpeta metadata? (por ej. el tp anterior era /mnt/SADICA/metadata. etc). Edit: El path del data.bin esta en el config del nodo, lo que me faltaria es saber el tamaño del data.bin en si.

Perdón si las preguntas son medio tontas, estoy releyendo el tp a ver si le encuentro la vuelta pero no logro verlo.

Gracias!

Saludos!

**Comment by tferraro** [comment]
Buenas!!

No hay preguntas tontas, siempre es mejor aclarar las dudas, por más chicas que sean, y nos evitamos que generen confusión 😃 

1) El tamaño de cada Nodo, lo conoce el propio nodo (valga la redundancia) en función del tamaño que tenga su data.bin, el cual ya debería estar creado. El tamaño final en si, dependerá de las pruebas que se quieran ejecutar, es completamente configurable.

2) No hay un directorio en específico del filesystem local donde deban tener la metadata, sigan lo que dicte su corazón (como el config y eso) 😉 . Solamente traten de ser consistentes de donde la ponen.

Saludos!

Tom

**Comment by Gruschka** [comment]
Tom,

Mil gracias por la rapida respuesta, queda todo claro!

Entonces solo para reconfirmar: Seria valido entonces que mi proceso DataNode, al levantar el config se fije si existe el data.bin en el path que recibio del mismo config y si no existe crearlo? El tamaño del data.bin lo hardcodeo o bien - si se puede - lo paso tambien dentro del config del nodo.

Gracias de nuevo!

Slds,

**Comment by tferraro** [comment]
Es un buen approach, pero tendrías que saber el tamaño que vas a tener de alguna forma, tipo como decis, en el archivo de configuración. No hay nada definido de forma obligatoria a que hacer en ese caso, así  que son libres de agregarle lo  que deseen (con criterio) al archivo de configuración dependiendo de la impementación que quieran hacer 😉 .

**Comment by Gruschka** [comment]
Excelente Tom! Esto responde a mis preguntas. Muchas gracias!

**Comment by tferraro** [comment]
Cerrá el issue plz 😛
