### ISSUE TITLE
Problema levantando informacion del archivo config usando la commons

### ISSUE THREAD

**Issue by Gruschka** [sisoputnfrba/foro#850]
Buenas!

Otra vez tengo una pregunta boba. Estoy teniendo un problema con la biblioteca config, que cuando quiero levantar algun dato del archivo usando por ejemplo config_get_int_value me tira seg fault. Despues de debuggear veo que por alguna razon config_create no afecta en nada al puntero  a t_config que le paso como parametro, razon por la cual entiendo que me tira este error. 

El codigo lo tengo literalmente igual a como lo tenia el cuatri anterior - debuggeando el proyecto del cuatri anterior veo que efectivamente despues del config_create se altera el puntero config que le paso como parametro, pero esto no esta sucediendo ahora.

La idea es tener una funcion que me llene el struct que guarde toda la config del DataNode, pero como eso pinchaba para descartar cualquier cosa rara simplifique el codigo dejandolo de esta manera:

<img width="1319" alt="codigo" src="https://user-images.githubusercontent.com/11674324/30245382-7dab2b60-95ae-11e7-9244-86a9e06edb00.png">

Debuggeando el codigo, llegando al instante anterior a llamar a config_create veo que mi puntero config no tiene nada adentro:
<img width="1871" alt="debug antes" src="https://user-images.githubusercontent.com/11674324/30245395-a2c90f70-95ae-11e7-88ea-307a5133c500.png">

Despues de hacer un step over, veo que el config_create no lo altero en nada:

<img width="1873" alt="debug despues" src="https://user-images.githubusercontent.com/11674324/30245408-df367452-95ae-11e7-8ba8-02d98da090f7.png">

Y si hago un step over mas para ver que pasa cuando intento tomar el primer valor del archivo, me salta el segmentation fault:

<img width="1910" alt="screen shot 2017-09-09 at 10 33 22 pm" src="https://user-images.githubusercontent.com/11674324/30245412-074aa45e-95af-11e7-83e1-7f7ef751c684.png">

Si pongo un watch expression en argv[1] veo que el parametro estaria bien (es exactamente el mismo que pasaba en el filesystem del cuatri anterior). A su vez, en eclipse configure para que pase por parametro el archivo de la siguiente manera:

<img width="795" alt="run config" src="https://user-images.githubusercontent.com/11674324/30245421-3c27d2f0-95af-11e7-8bb3-d177a8595a35.png">

Ademas, probe correrlo por consola pasando manualmente el archivo de configuracion como parametro y tambien salta el seg fault.

Perdon por el post infinito y la consulta que seguramente es una boludez pero no se que estoy haciendo mal! No me tira errores al buildear y ejecuta todo bien.

Gracias!

**Comment by jazcarate** [comment]
Buenas buenas!
Fijate que el valor de retorno de `config_create` es 0.

Fijate si el issue https://github.com/sisoputnfrba/foro/issues/835 te ayuda un poco a entender qué anda pasando 😄

**Comment by Gruschka** [comment]
Hola @jazcarate !

Mil gracias por la data!

No llego a entender que sea un tema de como puse el path porque literalmente lo tengo igual que en el otro proyecto y ahi anda y en el nuevo no.

Igual me sirvio mucho lo que me pasaste porque en Run config puse el path absoluto y ahora anda. Esta mal hacer esto? 

Mil gracias de nuevo!

Slds,

**Comment by jazcarate** [comment]
No, pasar la ruta absoluta "mal" como "**mal**" no está. (muchos negativos juntos 😸 ).

**Comment by Gruschka** [comment]
Excelente entonces - lo dejo asi. Muchas gracias!

**Comment by mgarciaisaia** [comment]
El mayor problema con poner el path absoluto en lugar del relativo es que eso significa que no terminaste de entender el problema, y la estás zafando. Si la entrega final fuera en 10hs, sí, hackeala y aprobá como puedas. Pero hoy te quedan un par de meses hasta la entrega - imaginate cómo va a llegar tu código a este ritmo :/

En el #835 está linkeado el post ese de Rutas Argentinas, para entender un poco qué pasa. Podés probar de comparar la Run configuration de ambos proyectos, a ver si hay alguna diferencia, o mirar bien bien bien ambos archivos de configuración, por si están en rutas "no equivalentes" (capaz en uno tenés el config _dentro_ de `Debug/` y en el otro no, qué se yo).

Y ponete algún tema del Flaco Spinetta para acompañar el post - en mi barrio, el Flaco hace cualquier tarea más amena ¯\\_(ツ)\_\/¯

**Comment by Gruschka** [comment]
Gracias @mgarciaisaia toda la razon, es un workaround muy trucho teniendo tiempo todavia. Ya lo tengo andando con path relativo. 

El articulo de Rutas Argentinas me sirvio mucho. Es gracioso porque lo primero que pense al ver el nombre de la pagina fue en el Flaco jajaja.

Muchas gracias!
