### ISSUE TITLE
Proceso Worker y forks por operacion

### ISSUE THREAD

**Issue by ccalvoromero** [sisoputnfrba/foro#851]
Buenas noches a todos,

Tengo una consulta respecto al proceso Worker. Tengo entendido que a un Worker puede conectarse más de un proceso Master (para atender varias etapas de distintos job), por ende cuando se me conecte alguno, después de hacer un handshake y al no tener la posibilidad de usar hilos para atender las conexiones, debería hacer un fork() para lo cual el proceso padre seguiría esperando nuevas conexiones de procesos Master y el hijo ya esperaría recibir el mensaje del Master conectado para saber que etapa tiene que ejecutar y sobre que archivo. Al ya tener todo lo requerido para hacer la transformacion/reducción, solo tendría que hacer un system() para ejecutar la operación que me pidieron. 
Estoy planteando bien esto? Hay algo que haya malinterpretado o se pueda encarar de una manera más óptima o "linda"? Porqué hay cosas que hay en el enunciado que me confunden un poco y pude haber delirado bastante con lo que pensé.

Agradezco de antemano.

Saludos!

**Comment by nicozar95** [comment]
Esta perfecto, vos deberias disparar un `fork() `por cada etada de transformacion/reduccion/cosa que te pida el Master.

Podrias hacerlo con `exec()` pero no hay ninguna restriccion a que lo tenes que usar si o si, asi que con `system()` da lo mismo.

Saludos

**Comment by ccalvoromero** [comment]
Entonces solo para confirmar: al proceso hijo forkeado anteriormente, o sea el que esta esperando el mensaje de que etapa ejecutar o lo que me pida ese Master, tengo que forkearlo nuevamente para usar el exec() o system() y al terminar, matar este procesito, mientras el otro sigue escuchando mensajes para ejecutar otra etapa del Master conectado. En paralelo a todo esto, el padre y "abuelo" de ambos sigue esperando la conexión de otro proceso Master.

Perdón si maree, pero es medio complicado de explicar escrito, jaja.

Gracias.

**Comment by nicozar95** [comment]
Con un fork alcanza, corres lo que tengas que correr con system y matas al proceso.
No se si valdria la pena tener un proceso "abuelo".

Saludos.

**Comment by ccalvoromero** [comment]
Listo, genial. Muchas gracias.

Saludos
