### ISSUE TITLE
Iniciar filesystem

### ISSUE THREAD

**Issue by CarolinaPonceRodriguez** [sisoputnfrba/foro#852]
Buenas, que tal, tengo una duda en cuanto al inicio desde "cero" del fs. Siguiendo la idea de los checks aun no es requerido implementar la opcion de poder levantar un fs viejo si existiese, por lo cual, la verificacion de estado estable y no estable queda trunca de a momento.
Mi duda es como se espera que inicie mi filesystem? Entiendo que existe el comando format que yo misma debo desarrollar, en tal caso, no debiera permitir que nadie se conecte hasta que tenga mi sistema ya formateado, es correcto? Sea por "formateado a nuevo" o en su defecto, haber iniciado con un estado anterior.
De todas maneras, el format lo unico que haria es crear los directorios y archivos correspondientes vacios, ya que los mismos se iran llenando una vez que el fs reciba informacion.

Saludos!.

**Comment by tferraro** [comment]
Buenas!

No termino de entender a que apuntas específicamente con la pregunta,
porque como inicia el FileSystem? Es medio amplio.

> Idealmente, el format serviria, como dijo Santi en las charlas, para darle
el tamaño al Filesystem, fijar los nodos de uso y crear las estructuras.
Una vez formateado, ahi tendrías tu FS en estado estable.

De todas formas, esa parte quedo poco clara originalmente, _por la forma en
que lo escribimos_. Así que te invito que le pegues una mirada a la errata
que anunciamos *hace un ratito,* y tu mail me hizo acordar que faltana
hacerla pública* 😛.*

Saludos!

Tom

**Comment by CarolinaPonceRodriguez** [comment]
Muchas gracias por la respuesta, aunque ahora tengo mas dudas, por ejemplo cuando dice:

1) "Mientras que el FileSystem no posea al menos 1 copia de cada uno de los archivos almacenados en los DataNodes conectados, se denomina que **el proceso FileSystem está en un estado no-estable**. Una vez adquiridas al menos 1 copia de cada archivo, se considerará que **el proceso FileSystem ha pasado a un estado estable** y permitirá nuevamente conexiones de los demás procesos."

Supongo que con esto se refiere a que el fs si o si debe tener todos los archivos(en tabla de archivos) que se conforman  de los  Nodos que se encuentren conectados y en caso de no tenerlos "armarlos" y guardarselos, es asi? 

2) "Como aclaración final, si el proceso FileSystem es ejecutado con el flag `--clean` se procederá a ignorar e eliminar el estado anterior. Sin embargo, el proceso FileSystem se inicializará en un **estado no-estable** hasta que se efectúe la conexión de un Nodo, luego de la cual, pasará a un **estado estable**."

Con este flag eliminaria el contenido de todas las estructuras incluido la tabla de nodos? Porque si fuera ese el caso, al momento de conectarse un datanode, entiendo que pasaria a estado estable por lo cual podria conectarse yama y tambien a posterior, conectarse mas datanodes los cuales se agregarian a la tabla ya que no podria haber un unico nodo conectado.

3) "Sin embargo, aunque el proceso FileSystem pase a un _estado estable_, permitirá que los nodos que todavía no se conectaron, vuelvan a hacerlo."
Si al agregar el flag clean, el contenido de la tabla de nodos persiste, entonces en los unicos dos casos en los que se pueden conectar mas nodos en estado-estable  luego de YAMA pero que figuraban en la tabla de nodos es cuando levanta el fs anterior normalmente y/o cuando lo hace con el flag clean tambien.

Saludos y gracias!

**Comment by tferraro** [comment]
Buenas!

Lo que estás leyendo es, justamente, el porque no hacer las cosas apurado.
La edición web de github+gitbook me jugó una mala pasada y no verifique que
se estuviera cargando todo bien. Mala mía ahí, te pido disculpas por haber
generado esta confusión. Ahora las aclaraciones:

1) Así es
2) No le des bola a lo que está después del 'Sin embargo', debería estar
borrado.
3) Esta frase va antes de la explicación del estado clean. Es una
aclaración respecto al estado no-limpio, de que pasa con el resto de los
nodos una vez que adquirió estado estable por tener todos los archivos.

Una vez más, mil disculpas por la confusión 😰, trataré de arreglar esto en
algún momento de la tarde.

**Comment by CarolinaPonceRodriguez** [comment]
Buenas gracias por la respuesta, de todas maneras dejo el issue abierto porque es posible que luego de que la nueva corrección este subida, me surjan dudas en base a "como era, y como es ahora".

Saludos.

**Comment by CarolinaPonceRodriguez** [comment]
Creo haber entendido correctamente, por lo cual procedo a cerrar el issue, por otra parte, no veo agregada la errata Errata v1.1.1 #2 en el repo del tp. Mas que nada, aclaro para que todos lo puedan ver.

Saludos.
