### ISSUE TITLE
Format/--clean en  filesystem

### ISSUE THREAD

**Issue by CarolinaPonceRodriguez** [sisoputnfrba/foro#853]
Buenas, este issue tiene relacion con el #852. Genero uno nuevo ya que me surgieron dudas en base a la ultima correccion.

En principio sabemos que el FS iniciará y puede pasar lo siguiente:
1) Ejecutarse con flag --clean
2) Ejecutarse sin flag --clean

Para el caso 1) en caso de tener un estado anterior, procederá a limpiarlo, pero exactamente que estructuras limpia? Todas las del FS?
a) Si limpia todas las estructuras, pero dejando el "cascaron", cuando se conecten los datanodes y se complete la tabla de nodos, no sabra que archivos tienen esos nodos ya que la tabla de archivos, al igual que la de directorios y el bitmap de nodos estarian vacios. No tendria ninguna informacion en mi sistema con el cual el FS pueda trabajar y eventualmente pasarle a YAMA.
b) Si unicamente limpiase los nodos que estaban conectados, permitiendo conexion de cualquier nodo, pasaria lo mismo, no contaria con la info de archivos de nuevos nodos.

Para el caso 2), pueden pasar dos cosas:
c) Contar con un estado anterior por lo cual lo levanto y  espero la conexion de nodos, de acuerdo a lo que posea conectado si esto me genera poseer una copia de cada bloque de archivo perteneciente a los data.bin, paso a estado estable, sino, continuo en estado no estable hasta que se conecten mas datanodes y obtenga un OK  para el chequeo anterior. Despues de eso permito que se conecten otros procesos y mas datanodes.
d) Si no cuento con el estado anterior, dejo que se conecten datanodes y en algun momento envio el comando format. Mi sistema trabajara sobre los datanodes conectados, ahora: como se que archivos tienen mis data.bin, que bloques los componen si el format crea las estructuras pero no las completa? No hay manera de obtener esa informacion de otro lado ya que los data.bin unicamente poseen los bloques de datos a SOLO que ustedes nos pasen en principio que archivos van a componer nuestro sistema, es decir, la info para "rellenar" la tabla de archivos, tabla de directorios, bitmap, etc.

Perdon si es medio largo, pero me falta info al respecto.

Saludos.

**Comment by iago64** [comment]
Carolina, que tal?

Caso 1, se ejecuta con el flag --clean:
Se limpian **todas** las estructuras del FS, es un inicio en limpio, tal cual dice el enunciado:
> Como aclaración final, si el proceso FileSystem es ejecutado con el flag --clean se procederá a ignorar e eliminar el estado anterior.

Los archivos que tengan o no los DataNode dejan de importarte ya que estas arrancando un estado limpio, pensa que vos primero inicias el FS y despues se te conectan los DataNode, con lo cual al no tener estructuras de archivos, asumís que cada DataNode que se te conecta esta limpio, con lo cual tirar un Format, seria irrelevante porque no tendrías estructuras para eliminar.

Caso 2, se ejecuta sin el flag --clean:
Levantas el estado anterior y esperas que se te conecten los Datanode para eventualmente llegar a un estado estable.

_En ninguno de los 2 casos el comando Format tiene que eliminar los datos de los DataNode, solo trabajas sobre las estructuras administrativas del FS_
El comando Format del proceso FS, vendría a simular, funcionar parecido al format de windows, donde lo único que haces es modificar las estructuras administrativas y los datos de los archivos quedan perdidos en el ether (de hecho gracias a eso es que es posible recuperar archivos borrados)

**Comment by CarolinaPonceRodriguez** [comment]
Osea basicamente:
Caso 1:
Los data.bin de cada datanode tienen un espacio inicial disponible pero no tienen informacion alguna (es como si les hubiese aplicado truncate).

"En ninguno de los 2 casos el comando Format tiene que eliminar los datos de los DataNode, solo trabajas sobre las estructuras administrativas del FS".
Entiendo que el format unicamente trabaja sobre las estructuras del FS y que al formatearse el mismo, trabajara sobre los nodos que ya se conectaron, pero en este caso, seria como tambien asumir que los datanodes van a estar limpios ya que la informacion que yo tuviese en mis estructuras no me importara y podra ser "reescrita"(en base a lo que decis, que no se borra en si).

Otra duda que me queda es la siguiente:
Format es un comando que puedo arrojar cuando se me cante, si yo levanto un estado anterior, tendre en mi tabla de nodos todos los nodos que podrian conectarse a mi FS. Al formatear, todos los nodos de mi lista son los que se podran conectar sin importar el estado del sistema al momento del format? Saludos.

**Comment by tferraro** [comment]
Holis! 👋 

> Los data.bin de cada datanode tienen un espacio inicial disponible pero no tienen informacion alguna (es como si les hubiese aplicado truncate).

Guarda que esto es lógico nomás eh. Información la siguen teniendo, pero, citando a Hernancito, es bassura y para el nuevo FS no significa nada, "como si estuviera vacio". Justamente lo que dijiste en función al comment de Dami sobre el format.

> Format es un comando que puedo arrojar cuando se me cante, si yo levanto un estado anterior, tendre en mi tabla de nodos todos los nodos que podrian conectarse a mi FS. Al formatear, todos los nodos de mi lista son los que se podran conectar sin importar el estado del sistema al momento del format?

Si te entendí bien, supongamos esta escena:

Estado Inicial -> Se conectan 5 nodos -> format -> Se cae -> Se levanta y se conectan 4 -> Le vuelvo a dar format

**Tu pregunta es**, que si después del 2do format, la lista de nodos va a estar compuesta por esos 4 y que el 5 se puede ir para su casa, porque el FS es nuevito? si es así, entonces si 😄 

Tom

**Comment by iago64** [comment]
@CarolinaPonceRodriguez Como va? se entendió la respuesta de Tom? podemos ayudarte con algo mas?

**Comment by CarolinaPonceRodriguez** [comment]
Buenas, se entendio. Cierro.
Gracias!
