### ISSUE TITLE
Archivo config de Nodo

### ISSUE THREAD

**Issue by CarolinaPonceRodriguez** [sisoputnfrba/foro#854]
Buenas en base al issue #842 y la posterior errata del archivo de configuracion del Nodo, vi en el enunciado lo siguiente:
"El Worker es un proceso encargado de aplicar operaciones sobre bloques de archivos o sobre archivos temporales. Las operaciones son recibidas por parte del Master quien se conecta al Worker para ejecutar una tarea comandada por YAMA."

Resalto: Master quien se conecta al Worker, en este caso, worker no seria el servidor y necesitaria de la ip del archivo de configuracion? Entiendo que del nodo, tango datanode como worker comparten el mismo archivo.

Saludos.

**Comment by iago64** [comment]
Carolina, que tal?

Justo en el caso del Nodo no quedo explicitado, pero lo que se hace en el enunciado es que en los archivos de config, es dejar un modelo básico, que es lo que entendemos que tienen que tener en un config, pero generalmente hay una aclaración que dice algo así como:

> Queda a decisión del grupo el agregado de más parámetros al mismo.

Con lo cual si les hacen falta más parámetros se los pueden agregar sin problema.

**Comment by CarolinaPonceRodriguez** [comment]
Perfecto gracias, cierro issue.
