### ISSUE TITLE
Conexión DataNode a FS

### ISSUE THREAD

**Issue by dromero-7854** [sisoputnfrba/foro#855]
Buenas, tengo una pequeña consulta con respecto a la conexión del DataNode a FS.

Presento los dos contextos:
Existe un estado previo del FS: En este caso ¿DataNode sólo deberia enviar el nro. de nodo, no? FS toma los  datos de la tabla de nodos que se encuentra en /metadata/nodos.bin como válidos ¿no?

No existe un estado previo del FS (FS limpio): ¿DataNode además de enviar el nro. de nodo, debería enviar  la cantidad de bloques libres, no? Tengo entendido que el tamaño del data.bin en  los nodos puede variar.

Espero sus comentarios
Saludos!
Dante Romero

**Comment by tferraro** [comment]
Buenas!

> Existe un estado previo del FS: En este caso ¿DataNode sólo deberia enviar el nro. de nodo, no? FS toma los datos de la tabla de nodos que se encuentra en /metadata/nodos.bin como válidos ¿no?

Entre las cosas que deben comunicarse el DataNode contra el FS, con el nro de Nodo debería ser suficiente ante restaurar un estado anterior

Sin embargo:

> No existe un estado previo del FS (FS limpio): ¿DataNode además de enviar el nro. de nodo, debería enviar la cantidad de bloques libres, no? Tengo entendido que el tamaño del data.bin en los nodos puede variar.

Guarda con esto. El nodo no tiene mucha idea de bloques libres u ocupados. Debería enviar la cantidad de bloques que posee.

Saludos!

Tom

**Comment by CarolinaPonceRodriguez** [comment]
Yo entiendo que si no tenes un estado anterior y se te conectan datanodes "nuevos" para el fs todos los bloques de cada data.bin van a estar libres, porque no tiene con que contrastar cual es el estado de data.bin de cada datanode. Unicamente puede saber la cantidad de bloques que lo componen.

**Comment by dromero-7854** [comment]
Con respecto a la segunda consulta que hice, esta mal redactada. Se considera que todos los bloques libres. 

Mi duda básicamente es que en el enunciado no encontré que DataNode le manda a FS, la cantidad de bloques que posee, por eso quería confirmar que ese dato es necesario.

Doy por cerrado el issue.

Gracias!
