### ISSUE TITLE
Filesystem - Esquema de conexión

### ISSUE THREAD

**Issue by gvillarc91** [sisoputnfrba/foro#856]
El  Filesystem es un proceso que se comunica de la siguiente forma:
-Recibe conexiones de DataNode(s)
-Recibe UNA conexion de YAMA
-Desconexiones posibles de DataNode(s) (por errores quiza)
-Solicitudes de YAMA (transformacion)
-Solicitudes de DataNode (almacenar/leer archivo)

Asumiendo como válido lo anterior pregunto: 
¿Sería válido que el Filesystem tenga una esquema de servidor con o sin select?
Esta pregunta me surge porque si elegimos esta opción cada interacción de un proceso con el FS será secuencial, por ende, tendrán que esperar los demás.

La alternativa a esto sería crear un thread por conexión generada con el FS, pero solo optaríamos por esta opción si se requeire atención inmediata de las peticiones hacia FS. Entonces, ¿Se requiere?

Gracias.

**Comment by CarolinaPonceRodriguez** [comment]
Buenas, no se, puedo estar equivocada, pero pongo el siguiente ejemplo:
Estas corriendo un programa y en un momento determinado ese programa llama a alguna operacion que requiera ejecutar una accion contra un archivo que tu FS tiene, si tu FS  se pone pancho y te dice "estoy haciendo otra cosa, esperame a que termine con esto y te atiendo" vas a tener a tu programa bloqueado hasta que el FS atienda la operacion que solicito, podria no ser practico si tenes muchas operaciones que atender.
Entiendo que quiza lo practico del FS distribuido no es solamente distribuir la carga de contenido sino tambien distribuir la atencion de peticiones, la ventaja de los hilos sera poder ejecutar en simultaneo.

Saludos.

**Comment by iago64** [comment]
Buenas buenas :)

El enunciado no te especifica que tenes que usar para manejar el FS, por lo cual ambas opciones son completamente válidas y queda en decisión del grupo ver cual van a usar.
Eventualmente van a tener 2 hilos, uno va a ser el que maneje las conexiones y otro va a ser el que maneje la consola del FS.
Yo personalmente les diría que de momento no se compliquen mucho ya que no es necesario para este primer checkpoint que tengan armado el FS completo y que si no la tienen muy clara con Threads esperen a la 3er charla (el 30/09) que ahí se va a tocar el tema y muy posiblemente se charle un poco sobre las ventajas y las desventajas de usar threads o select.

Lo que comenta Carolina no esta mal tiene un buen punto para tratar el tema de una alta disponibilidad y alta carga de trabajo, pero en el caso de este tp los tiempos de espera que van a tener los procesos para ser atendidos por el FS muy posiblemente sean mucho mas cortos que los tiempos de ejecución de los jobs. Con lo cual si el FS tarda un poquito de mas en contestar no sería la muerte de nadie y seria perfectamente valido :)

Saludos.-

**Comment by gvillarc91** [comment]
@iago64 Buenisimo! me quedó claro. No tenía noción de esos tiempos como para tomar una u otra decision. Muchas gracias, cierro.

**Comment by nahueloyha** [comment]
Buenas @iago64 ! Revisando las pruebas hacen especial mención a que "El   sistema   aprovecha   el   paralelismo   de   los   DataNodes   para   acceder   a   la   información", y nos resurgió esta duda respecto a usar select vs threads en el FS. 
Si bien es cierto que a nivel del scope de este TP la diferencia en tiempos entre ambas soluciones es despreciable, también es cierto que usando select eventualmente no "escala" a cientos/miles de nodos, por lo que no sabemos que tan justificable es esa decisión.
