### ISSUE TITLE
Duda mmap y binario

### ISSUE THREAD

**Issue by carogon** [sisoputnfrba/foro#857]
Hola! Con mi grupo tenemos una duda:
Tenemos un archivo de texto que con un memcpy() lo pasamos a un binario. Hasta ahí todo bien. El problema es levantar el binario. Sabemos que tenemos que usar mmap(), el tema es que cuando recorremos el char* que nos devuelve lee algo que no sabemos que es.  Es decir, no podemos recuperar/releer lo que guardamos.

Saludos.

**Comment by CarolinaPonceRodriguez** [comment]
Creo que te convendria adjuntar una porcion de codigo(sin levantar la perdiz) de que es lo que estas tratando de hacer, a tener en cuenta:
- Que hacen con el archivo? Lo abren y usan fread?
- Que parametros le pasan al memcpy()?
- Que parametros le pasan a mmap? (tener en cuenta que esta funcion retorna un void * )

Se necesita un poco mas de info al respecto para poder ayudar a resolver el problema.
Saludos.

**Comment by fedebonisconti** [comment]
Está bueno recordar que el _archivo de texto_ son bytes representados como _texto_, que también podrían ser bytes representados como _números_, o como cualquier otra cosa.

Dicho esto, [acá](https://stackoverflow.com/a/20460969/5379362) podés encontrar un ejemplo de cómo usar [mmap](http://man7.org/linux/man-pages/man2/mmap.2.html) para leer un _archivo de texto_. :)

De todos modos, como dice @CarolinaPonceRodriguez, sin un poquito de código/stacktrace es difícil saber el por qué.

Saludos!

**Comment by varas-c** [comment]
Hola @carogon como venís con ésto? Te quedó alguna duda? Si todavía no pudiste resolverlo, avisanos y te damos una mano!

**Comment by carogon** [comment]
Sí, ya nos quedo claro. 
Disculpen la demora y gracias.
