### ISSUE TITLE
[FileSystem] -Inicializacion - Recuperar estado anterior

### ISSUE THREAD

**Issue by alejandrog87** [sisoputnfrba/foro#858]
Buenas tardes, recién salimos del checkpoint y se nos presentó una duda con el ayudante que nos pidió postearlo en el foro para que quede registrada la respuesta y  también chequeada.

El FileSystem precisa alcanzar un estado estable para aceptar al proceso YAMA y que el sistema pueda comenzar a operar, según el enunciado el estado estable se compone:
-De un número minimo de nodos ,que supongo residirá en el archivo de configuración.
-De que haya al menos una copia de cada bloque de cada archivo del filesystem.

Por lo cual en el proceso de inicialización del mismo se pueden dar los siguientes casos:

1) Se ejecuta el proceso filesystem y no existe ningún archivo correspondiente a una ejecución anterior, entonces el filesystem debería aguardar la conexión del mínimo de nodos y copias de bloques (estado estable), formatear y recién puede aceptar al proceso Yama y Workers. También en las erratas del enunciado se indica: 

"Además, una vez formateado el FileSystem, no se permitirán nuevos Nodos en el sistema"
, por lo cual,entiendo que la cantidad de nodos con los que trabaja filesystem sería fija luego del formateado lo que se contradice con lo indicado en otra errata del TP que dice:
"Además, aunque el proceso FileSystem pase a un _estado estable_, permitirá que los nodos que todavía no se conectaron, vuelvan a hacerlo."
Luego del formateado, se puden conectar más nodos o no?

2)Se ejecuta el proceso filesystem con el flag --clean , el filesystem debería ignorar el estado anterior y actuar como en el caso 1, cierto?

3)Se ejecuta el proceso filesystem y existen archivos correspondientes a una ejecución anterior:
El proceso Filesystem debe aguardar por la conexion de los nodos que participaron en esa ejecución anterior, rechazando todo intento de conexión de un nodo con id distinto, por lo cual, también entiendo que la cantidad de nodos con los que trabaja fs va a ser fija y no va a poder sumar nuevos nodos en tiempo de ejecución, cierto?.

Otras consultas que aplican a los 3 casos:

-El proceso de formateo, de los casos 1 y 2,  implica que todos los bloques de todos los nodos estén disponibles/libres (está vacio) , cierto?, osea que en esos 2 casos los archivos sobres los cuales van a trabajar las transformaciones van a tener que ser "copiados" por la interfaz del filesystem.

-Si el filesystem recupera una ejecución anterior, "asume" que  los archivos/bloques que existen en dicho nodo son los que se especifica en el archivo que representa la estructura administrativa, es decir, no valida nada. 

Gracias.

**Comment by tferraro** [comment]
Buenas!!

Vamos por partes

1) Hasta la última parte venías bien. Lo que mencionas como "_permitirá que los nodos que todavía no se conectaron, vuelvan a hacerlo._" hace referencia a los Nodos que se se encontraban conectados cuando se formateó el fs la primera vez, de ahí el "vuelvan". En otras palabras, nuevos nodos no pueden conectarse, pero si reconectarse Nodos viejos.

2) Detalle sobre el caso 1, va a pasar al estado estable una vez que se formatee, con los nodos que se encuentren conectados, no bajo una mínima cantidad de nodos.

3) Efectivamente! Una vez formateado el FS, la cantidad de nodos se mantiene fija, incluso si se cae y se vuelve a levantar. Sin embargo, un nodo que se desconectó debería poder volver a conectarse y ser tomado en cuenta.

Extras:

> El proceso de formateo, de los casos 1 y 2, implica que todos los bloques de todos los nodos estén disponibles/libres (está vacio) , cierto?, osea que en esos 2 casos los archivos sobres los cuales van a trabajar las transformaciones van a tener que ser "copiados" por la interfaz del filesystem.

Si! Para tener archivos en el FS hay que agregarlos por la consola, o levantar un estado anterior :).

> Si el filesystem recupera una ejecución anterior, "asume" que los archivos/bloques que existen en dicho nodo son los que se especifica en el archivo que representa la estructura administrativa, es decir, no valida nada.

Yep, no se requiere que se hagan validaciones sobre los datos del Nodo, si quieren agregarlo, queda a desición suya 😛 

Saludos!

Tom

**Comment by alejandrog87** [comment]
Gracias por tu respuesta, sumo otras consultas:

-El proceso de formateo va a ser ingesado por consola, no? por el comando de la interfaz de consola, es decir, no es que el formateo se hace automaticamente en una función de inicialización. Sino que se conectan DataNodes y en un momento determinado por consola se ingresa format y recién a partir de ahi se permiten conexiones de Yama y Worker.

-Los procesos que se pueden conectar a fs son: yama. datanodes, worker:
    -La interacción de worker es para guardar exclusiamente el resultado de una reducción global en el filesystem, ya que para la lectura de bloques cada worker trabaja de forma local con el archivo data.bin, no mediante la interfaz del filesystem.
   - La interacción de los datanode con el filesystem es exclusivamente por la interfaz de obtenerBloque y escribirBloque, no se puede ampliar.
   -La interacción de Yama con el filesystem es puramente por datos administrativos, conocer el estado del filsystem, espacio libre, ubicación de los bloques de un archivo,etc pero yama va a utilizar la interfaz de almacenar y leer archivo? ya que el trabajo de las reducciones y transformaciones lo realizan los nodos.

Gracias

**Comment by tferraro** [comment]
> El proceso de formateo va a ser ingesado por consola, no? por el comando de la interfaz de consola, es decir, no es que el formateo se hace automaticamente en una función de inicialización. Sino que se conectan DataNodes y en un momento determinado por consola se ingresa format y recién a partir de ahi se permiten conexiones de Yama y Worker.

Efectivamente!

> Los procesos que se pueden conectar a fs son: yama. datanodes, worker:

Ajá

> La interacción de worker es para guardar exclusiamente el resultado de una reducción global en el filesystem, ya que para la lectura de bloques cada worker trabaja de forma local con el archivo data.bin, no mediante la interfaz del filesystem.

Idem anteriores

> La interacción de los datanode con el filesystem es exclusivamente por la interfaz de obtenerBloque y escribirBloque, no se puede ampliar.
-La interacción de Yama con el filesystem es puramente por datos administrativos, conocer el estado del filsystem, espacio libre, ubicación de los bloques de un archivo,etc pero yama va a utilizar la interfaz de almacenar y leer archivo? ya que el trabajo de las reducciones y transformaciones lo realizan los nodos.

Claro, la interfaz de YAMA no se encuentra limitada por la interfaz obtener/escribirBloque. Dicha interfaz es para la interacción interna del FS. Justamente porque a YAMA le interesa la metadata del archivo, no el archivo en sí (porque, como decis, no va a operar con él).

Saludos!

Tom

**Comment by alejandrog87** [comment]
Gracias por la respuesta.
