### ISSUE TITLE
Posible error - Archivo de Log - WORKER

### ISSUE THREAD

**Issue by miguelshevchuk** [sisoputnfrba/foro#859]
Buenas tardes.

Repasando un poco el enunciado, note que la descripción del requerimiento de archivo de log para el WORKER, es exactamente igual al requerimiento de archivo de log para el datanode.. Es decir, en ambos apartados el texto es el siguiente : 

El proceso DataNode deberá contar con un archivo de configuración en el cual se logearán todas las operaciones realizadas. Las mismas deberán ser mostradas por pantalla.

Paginas 27 y 30 del enunciado

Supongo que es algo mínimo, pero no deja claro que es lo que debemos mostrar en pantalla para el worker.

Saludos y gracias

**Comment by tferraro** [comment]
Buenas!

Mostrá las operaciones del Worker. Cosas del Copy/Paste 😛

En un rato lo paso a la errata!

Gracias!
