### ISSUE TITLE
[FileSystem] - Copiar de archivo a YAMA

### ISSUE THREAD

**Issue by lucianasorbelli** [sisoputnfrba/foro#860]
Buenas noches:

Mi consulta es la siguiente, para la entrega 2, uno de los hitos dice " El Fs debe permitir la copia de un archivo al YAMA y almacenarlo partiendolo en bloques " .

Lo que yo había entendido es que al FS le llega un archivo resultado del **worker**, para particionarlo y guardarlo...y que YAMA no interviene en esto. 

Por favor, pueden aclararme esto?

Saludos.

**Comment by tferraro** [comment]
Holis

Aclaración: el enunciado dice yamafs, no YAMA. Como dice el apartado del
proceso master, se utilizará el prefijo yamfs para referirse a archivos
dentro del proceso FileSystem.

Saludos!

Tom

**Comment by varas-c** [comment]
Hola @lucianasorbelli  como venís con ésto? Te quedó alguna duda? Si todavía no pudiste resolverlo, avisanos y te damos una mano!

**Comment by lucianasorbelli** [comment]
Buenos días ! Perdón por no responder antes. Sí, está claro. 
Gracias !

Saludos
