### ISSUE TITLE
Worker - Duda con algoritmo sort luego de la etapa de Transformacion

### ISSUE THREAD

**Issue by DarkWood97** [sisoputnfrba/foro#861]
Hola que tal? En el enunciado del TP dice que luego de ejecutar el script de transformacion, el resultado debe ser guardado de manera ordenada. Mi duda era de que manera hay que ordenar ese "resultado", o sea pueden haber multiples formas y el enunciado no especifica cual puede ser, nose si es un error mio de interpretacion. Desde ya, muchas gracias!!

**Comment by mgarciaisaia** [comment]
¿Cuáles múltiples formas se te ocurren?

Contanos opciones, y por qué podrías preferir una sobre otra, y entonces
entre todos vemos cuáles de las alternativas tienen sentido y cuáles no,
¿te parece?

**Comment by DarkWood97** [comment]
Me parece perfecto!! Yo tenia pensado que podrian haber multiples maneras como por ejemplo: algoritmos alfabeticamente descendentes, el de ordenamiento por seleccion, burbuja, heapsort, quicksort (para que no este media hora ordenando), igual habria que considerar los tipos de datos con los que estoy tratando y supongo que son desconocidos ya que lo que hay adentro del resultado es "caja negra" para mi, entonces yo ordenaria considerando los bytes

**Comment by fedebonisconti** [comment]
Quizás te la estás complicando un poco de más!

Fijate el [sort que viene en el coreutils de linux](https://www.gnu.org/software/coreutils/manual/html_node/sort-invocation.html), que fue el que se [mencionó en la charla del enunciado](https://docs.google.com/presentation/d/1Td3EzTN3OIdDa_EhGPoS2Dqzj4Cpyfp0qMGy9JH9qMI/edit#slide=id.g266f59a077_0_246), y con eso vas a estar perfecto. No es algo que nos interese el que hagan los algoritmos de sort ustedes (es parte del temario de GDD, así que ahí lo van a ver bien). Preferimos una solución rápida y ya hecha!

Sólo por si te interesa un poquito más, [`sort`](https://superuser.com/a/234061) usa merge sort :)

**Comment by DarkWood97** [comment]
Buenisimo!! Usaré eso entonces, desde ya muchas gracias!! Cierro el issue
Ah el merge sort que esta basado en el concepto "divide y venceras", no?

Saludos
