### ISSUE TITLE
¿Como saber si un archivo puede guardarse en el FS?

### ISSUE THREAD

**Issue by dromero-7854** [sisoputnfrba/foro#862]
Buenas,

Leyendo el enunciado me llegó la siguiente duda:

Contexto: El FS ya se encuentra ejecutando, con todos los nodos conectados. El FS conoce el tamaño total del FS distribuido, cantidad de bloques de cada nodo y bloques disponibles de cada nodo (archivo metadata/nodos.bin pag. 25 del enunciado)

Duda: Al cargar un archivo, debo verificar que tenga el espacio requerido en el FS. Uno diria "verifico el valor de LIBRE en el archivo metadata/nodos.bin y listo..." Pero luego pienso: el bloque original y la copia no pueden estar en el mismo nodo, por lo que no resulta tan sencillo saber si es posible guardar el archivo. 
Por ejemplo, el archivo necesita 20 bloques para guardarse (10 para originales y 10 para copias) y tengo dos nodos conectados, uno con 30 bloques libres y el otro totalmente ocupado. El valor de LIBRE en el archivo metadata/nodos.bin seria de 30. Pero como los bloques originales y las copias no pueden convivir en el mismo nodo **no es posible guardar el archivo**.

¿Como podría encarar una solución para saber si un archivo puede cargarse en el FS, teniendo en cuenta la restricción comentada de que no pueden convivir un bloque original y su copia en el mismo nodo?

Espero sus comentarios...

Saludos!
Dante

**Comment by dromero-7854** [comment]
Pensándolo un poco más, podría tratar de asignar los bloques al archivo de a uno, En el caso de que este todo ok, paso a escribir los bloques ya asignados. Si durante la asignación, me quedo sin bloques, libero los bloques asignados previamente y retorno un error.

No se... se me acaba de ocurrir :-P

**Comment by tferraro** [comment]
Buenas!

Se me ocurren múltiples forma de como hacer el chequeo, pero se terminan reduciendo a _no usar el tamaño máximo del FS para chequear si podes guardar un archivo_.
Que se te ocurre que podrías usar, en vez del tamaño del FS?

Te parece una buena opción no calcular si entra o no y perder tiempo en asignar bloques y copiar data? Si el archivo es bastante grande, no afectaría el tiempo de respuesta? Para pensar 🤔 

Saludos!

**Comment by epreyes** [comment]
Una forma seria guardar en alguna lista los bloques que se que estan libres, si alcanza para el archivo proceder con la escritura, caso contrario error, con esto evito tener que hacer el rollback de lo que ya haya escrito si no alcanzaron los bloques

**Comment by dromero-7854** [comment]
Capaz la idea no se entendió del todo. Primero asignaría los bloques para el archivo y su copia. Y si los bloques alcanzaron y se reservaron todos, recién en ese momento avanzo con la escritura, sabiendo que ya tengo el espacio total reservado.

El tema de calcular si entra o no previo a la reserva de bloques, tendría que considerar si se van a cargar dos archivos al mismo tiempo al FS. Porque es ese caso, entraría en juego el tema de la sincronización de las estructuras administrativas. Y tendría que reservar bloques si o si, para que para en el proceso a la par del otro archivo, no aparezca como disponible.

Por lo que dejo la siguiente consulta: **¿Se van a cargar dos archivos al FS al mismo tiempo?**

Saludos!
Dante Romero

**Comment by nicozar95** [comment]
No creo, ya que el FS tiene que balancear el contenido entre los diversos datanode. Entonces si almacenara 2 archivos al mismo tiempo se le complicaria. 

Saludos

**Comment by dromero-7854** [comment]
Ok... gracias por las ideas y aclaraciones...

Doy por cerrado el issue

Saludos!
