### ISSUE TITLE
Scripts para testing

### ISSUE THREAD

**Issue by aocoda** [sisoputnfrba/foro#863]
Buenas,

Quería consultar si hay scripts de transformación y reducción de prueba para correr sobre los archivos.

Saludos!

**Comment by tferraro** [comment]
Buenas!

Todavía estamos a una etapa temprana del cuatrimestre, por lo que falta para que publiquemos _la versión beta de las pruebas_.

De todas maneras, eso no evita que _armes tus propios scripts de prueba_. No importa el comportamiento en si, dado que los Jobs que se corren en el sistema son agnosticos a los scripts.
Que ideas se te ocurren para usar de scripts de transformación y reducción. Dada la interfaz que va a tener (leer de stdin y mostrar por stdout), como encararías tener que armar tus propios scripts?

Saludos!

**Comment by gustofa** [comment]
Hola. 
Nosotros estamos usando scripts bash básicos, usando comandos como ls, grep, sort, etc...
Tal vez te sirve la idea.


Saludos

**Comment by aocoda** [comment]
Gracias @tferraro y @gustofa , con lo que habia dicho tomas se me vino a la cabeza utilizar algunos comandos basicos de bash.

Saludos
