### ISSUE TITLE
Almacenado Final - Comunicación Worker -> FileSystem

### ISSUE THREAD

**Issue by gvillarc91** [sisoputnfrba/foro#864]
(relacionado con el issue #844, pero no me aclaró las dudas)

**Almacenado final**

"El proceso Master entonces le solicitará al Worker encargado que se conecte al FileSystem y le envie el contenido del archivo de reduccion global **y el nombre y ruta que este deberá tener**".

**Interfaz FileSystem**
"Almacenar Archivo: recibirá una ruta completa, el nombre del archivo, el tipo y los datos correspondientes. Responderá confirmación".

**Según entiendo esto sería algo como:**
Master le envia a Worker encargado el path (que le pasó YAMA) y worker debe envarle al FileSystem el contenido del archivo, la ruta y el nombre.

**Dudas:**
1) En la interfaz FileSystem esa ruta la asumo como la ruta donde se colocará mi contenido. ¿Es correcto?
1) ¿La ruta y el nombre "que deberá tener" de donde las saca el worker?
2) Si quiere worker pegarle a la interfaz Almacenar Archivo del FileSystem necesita enviarle datos que no entiendo de dónde sacar: nombre del archivo, tipo.

Gracias

**Comment by gvillarc91** [comment]
#844

**Comment by juanlarosa96** [comment]
Buenas!

1. Exacto. La ruta que le pasas al FS será la ruta de yamafs en la que se almacenará el nuevo archivo

 2. Si te fijas, en el enunciado, en el apartado de Master especifica:
> *Almacenado final
Para finalizar la tarea se almacenará el archivo resultante del Job en el Filesystem distribuído para ser accedido por el usuario o por otro Job con el nombre y la ruta especificadas por el usuario al ejecutar el proceso Master.*
La ruta y el nombre la da el usuario al iniciar el job, pasandosela al Master por parametro cuando se inicia

3. El nombre sabemos que lo tiene el Master, que sabe la ruta del almacenamiento final ¿Y cual proceso es el que conoce los tipos de los archivos almacenados?

**Comment by gvillarc91** [comment]
Gracias!!!
