### ISSUE TITLE
Etapas - Enviar rutina de reducción/transformación 

### ISSUE THREAD

**Issue by gvillarc91** [sisoputnfrba/foro#865]
Cuando el enunciado dice que **Master debe enviarle a Worker "la rutina de reducción"** (lo mismo para la transformación), no me queda claro si debo enviarle un path o un contenido.

En caso de tener que enviarle un contenido, ¿Cómo hago?
Entiendo que los scripts de rutinas son caja negra (a nivel entender qué hacen), pero si tengo que mandarle un archivo por sockets quiero saber si existe alguna posibilidad, o bien de enviar ese archivo o de enviar ese contenido.

Gracias.

**Comment by mgarciaisaia** [comment]
👋 ¡Aloha!

La idea es que los programas transformadores/reductores viven en la máquina en la que corre el proceso Master, pero son los Nodos quienes tienen que ejecutarlo. Entonces, en ese caso, mandar un path no te va a servir de mucho - porque no podés, así nomás, ejecutar un programa dada su ubicación _en otra máquina_.

Así que vas a tener que enviar el programa.

Los scripts son de caja negra, claro. Pero, ¿qué sabés de ellos? Buen, en principio sabés que son _archivos_. Más específicamente: un archivo tiene el programa de transformación, y otro el de reducción. Entonces, nada - enviá esos programas (y a cruzar los dedos para que la otra máquina pueda ejecutarlos 🤷‍♂️ ). Será, entonces, un requisito de la plataforma en la que vayas a ejecutar los Nodos que tengan "arquitecturas" compatibles entre sí - es decir, todos tienen que poder ejecutar los mismos programas de transformación/reducción. En el caso del TP, van a ser todos la misma VM, así que **tenés** esa garantía.

¿Cómo harías para mandar un archivo por red?

¡Un abrazo!

**Comment by gvillarc91** [comment]
Genial, muchas gracias!
