### ISSUE TITLE
ConsolaFs

### ISSUE THREAD

**Issue by gaboxxz** [sisoputnfrba/foro#866]
Buenas. Consulta rapida. La consola del Filesystem se inicia al levantar el fs? o es un proceso aparte que se puede ejecutar desde cualqueir pc y se conecta por socket para enviarle los comandos al fs y recibir una respuesta ?
Por el momento veniamos haciendo la consola para que se ejecute desde cualquier lugar, lo que permitiria varias conexiones al fs, pero tal vez solo se necesita una consola que se levante en la pc del fs y solo se usaria ahi.
  ##Saludps

**Comment by tferraro** [comment]
Holis

Nope, la consola del FS es justamente eso, una consola del proceso, debe
ser parte del proceso y sera el nexo entre el usuario y el FS a traves de
la linea de comandos.

Saludos!

Pss: Para estos casos en los que necesitas hacer multiples cosas al
simultáneo que requieren compartir memoria, _nos viene fenómeno una
herramienta_, se te ocurre cual puede ser?

**Comment by gaboxxz** [comment]
Claro creo que entiendo. Tendriamos dos hilos. Uno para manejar la consola y otro para manejar todas las peticiones al fs del yama. es correcto?

**Comment by gaboxxz** [comment]
Como que llego vacia la respuesta creo

**Comment by tferraro** [comment]
Pucha, que raro.

En fin, es así nomas!
