### ISSUE TITLE
[Filesystem] Disponibilidad de un archivo 

### ISSUE THREAD

**Issue by alejandrog87** [sisoputnfrba/foro#867]
Buenas noches, tengo la siguiente consulta: la estructura del archivo de yamafs tiene un atributo que es Estado: Disponible o No disponible. 
Se considera que un archivo está disponible si existe al menos una copia del mismo? Es decir por definición existen 2 copias de cada archivo del fs, si por consola eliminan todos los bloques correspondientes a una copia del archivo, el mismo sigue estando disponible no? Me causa un poco de ruido porque siguiendo este razonamiento solo estaria No disponible si no existiese ninguna copia del mismo en el fs, lo cual también podría interpretarse como que el archivo ya no existe en el filesystem ( no hay más copias del archivo, el archivo no existe). Pensándolo en bloques, si mi archivo se compone de 4 bloques  y no existe al menos una copia de esos 4 bloques, el estado sería no disponible, si alguien por consola borra bloques del archivo y solo deja 3 mi estado sería No disponible, cierto?

Gracias.

**Comment by juanlarosa96** [comment]
Hola!
Si un archivo tiene una copia de cada uno de sus bloques en el fs, el archivo estará disponible. Hasta ahí vamos bien.
Si en el fs no se encuentra disponible uno o más de sus bloques, o sea que no se tiene ninguna de las dos copias de estos bloques, el archivo pasa a estar no disponible.
En el caso de no tener ninguna de ningun bloque del archivo, también se considera no disponible. Esto no quiere decir que "no existe" el archivo, porque figura en las estructuras administrativas del fs. El archivo dejaría de existir en el caso de que se lo borre de la tabla de archivos. Ahi estaría la diferencia

**Comment by tferraro** [comment]
@alejandrog87 como andás con esto? Te sirvió la respuesta de Juan?

**Comment by alejandrog87** [comment]
Si, muchas gracias. Cierro
