### ISSUE TITLE
Consulta File system / Multiples datanodes

### ISSUE THREAD

**Issue by Gruschka** [sisoputnfrba/foro#868]
Hola chicos!

Tengo una duda sobre como implementar el hecho de que al FS se le conecten muchos DataNodes y que pueda hacerle pedidos a cada uno de ellos cuando los necesite.

Claramente el FS seria un servidor y los DataNodes clientes que se le van conectando, ahora bien, cual seria la mejor manera para manejar esas multiples conexiones? Por otra parte, no veo como hacer para pedirle algo a un nodo que se conecto hace un tiempo.

Estoy evaluando dos alternativas pero no se que tan correctas sean:

1. Por cada nodo que se conecte crear un hilo nuevo con cada conexion de un data node al file system (seria un child del hilo principal que ejecuto al levantar el FS que basicamente lo que hace esperar conexiones entrantes de data nodes). Osea que yo en mi hilo que escucha nuevas conexiones, debajo del accept llamo a pthread_create.
2. Uso [select](http://man7.org/linux/man-pages/man2/select.2.html) que aparentemente permite monitorear muchos fd. 

No estoy seguro de ninguna de estas maneras y en ambos casos mi duda persiste en cómo hago para pedirle a cada datanode informacion una vez que ya se conectaron.

Muchas gracias!

Slds

**Comment by tferraro** [comment]
Buenas!

La elección del uso de un servidor multihilo o un servidor multiplexador (que es lo que hace el select) son ideas validas si estan bien justificadas.

Que cosas a favor te ofrece cada solución? Y en contra?

En base a lo anterior, que te convendria adoptar?

Saludos!

Tom

**Comment by Gruschka** [comment]
Hola @tferraro !

Estuve viendo esto por mi cuenta y hoy fui a la clase de consulta en campus.

Entiendo que es una cuestion de diseño y que ambas vias son validas tecnicamente. Por un lado hacerlo con hilos me parecia lo mas 'modular' y sencillo de implementar, ya que se manejar hilos yo pero select nunca use. Ademas, se me ocurre que usar hilos para cada Data Node puede ser mas util si le saco provecho al paralelismo / concurrencia.

El problema que tengo ahora es que a nivel diseño no se como sacarle provecho al paralelismo de los hilos, por como tengo encarado el FS. Actualmente tengo el hilo main que corre lo que es el FS y dos hilos hijos del main: Uno que escucha conexiones entrantes que sean Data Nodes y otro que espera al YAMA que se dispara solo cuando el FS este estable. La idea es que del hilo que escucha conexiones de Data Nodes, salgan _n_ hilos hijos de dicho hilo siendo _n_ cada Data Node nuevo. Si mal no entendi en la consultas que hice hoy en campus, esto no me estaria permitiendo sacar provecho del paralelismo, puede ser? Estoy encarando mal el diseño del FS?

Gracias como siempre!

**Comment by tferraro** [comment]
Buenas!

Así como está, no sabría decirte si le estás o no sacando provecho al paralelismo, dado que para hacerlo necesitas no solo una arquitectura que te lo permita, sino una tarea diseñada para eso.

Con usar un servidor multihilo, ya tenés una arquitectura que te lo permite. Ahora te falta definir: que tareas va a hacer el FS contra los Nodos? Tenes alguna, que sea de especial importancia, que pueda sacar provecho a realizar tareas al simultáneo?

Particularmente, hay una que es bastante polémica: el dividir un archivo en bloques mandándolos. Porque, a fin de cuentas, terminás teniendo un cuello de botella en la Red, pero a nivel ráfagas de CPU, aunque sean bastante I/O-Bound esos hilos, podrías llegar a lograr cierto paralelismo. 

Usando este ejemplo particular, son completamente válidos ambos enfoques, dado que para ver si alguna es más veloz que otra ya habría que correr varios benchmarks y ya nos vamos un poco de lo primordial de la materia.

Así que, siguiendo esta linea de pensamiento. Hacé lo que dicte tu sentido común 😄 

Saludos!

Tom

**Comment by Gruschka** [comment]
Muchas gracias Tom!

Ya me queda todo claro - cierro el issue.

Muchas gracias de nuevo!
