### ISSUE TITLE
Planificacion en Yama

### ISSUE THREAD

**Issue by lianndt** [sisoputnfrba/foro#869]
Hola, tengo una duda en la parte de planificacion. Lei en otro issue que en la parte de transformacion de un job, yama deberia mandarle la lista de bloques a transformar al master. Osea, cada bloque con el ip/puerto del worker seleccionado, etc. Habria que enviarle todo junto o puedo hacer un mensaje por cada transformacion a ejecutar? Osea, por cada mensaje envio: ip/puerto de worker, nro bloque, bytes ocupados, etc. 
Y una cosa mas, no entiendo bien como interviene el algoritmo de planificacion en las etapas posteriores (ambas reducciones). Entiendo que yama le solicita a master una reduccion local de un nodo cuando este termina todas sus transformaciones, osea cuando yama recibe de master el fin de tarea de la ultima transformacion de un worker, la pregunta es: le solicita inmediatamente a master que haga reduccion local sobre ese mismo worker, no? 

Gracias!

**Comment by nicozar95** [comment]
Buenas

> Hola, tengo una duda en la parte de planificacion. Lei en otro issue que en la parte de transformacion de un job, yama deberia mandarle la lista de bloques a transformar al master. Osea, cada bloque con el ip/puerto del worker seleccionado, etc. Habria que enviarle todo junto o puedo hacer un mensaje por cada transformacion a ejecutar? Osea, por cada mensaje envio: ip/puerto de worker, nro bloque, bytes ocupados, etc.

Creo que va mas por el lado de como lo quieran diseñar. En un principio yo te recomendaría que no, que mandes todo junto ¿Porque? Es medio una cagada trabajar por red porque podes llegar a tener problemas de sincronizacion de mensajes y ese es un problema jodido.
Por otro lado, si te va mandando de a partes, tal vez es mas simple de ejecutar del lado del Master. No vas a tener que deserializar mucho. 
Son libres de elegir como quieran

> Y una cosa mas, no entiendo bien como interviene el algoritmo de planificacion en las etapas posteriores (ambas reducciones). Entiendo que yama le solicita a master una reduccion local de un nodo cuando este termina todas sus transformaciones, osea cuando yama recibe de master el fin de tarea de la ultima transformacion de un worker, la pregunta es: le solicita inmediatamente a master que haga reduccion local sobre ese mismo worker, no?

Fijate que la distribucion de tareas es en la etapa de Transformacion, Cuando un nodo termina todas sus etapas de transformacion, ahi va a poder empezar con sus etapas de reduccion, no se fija en la planificacion del mismo.

Saludos y feliz dia del estudiante!

**Comment by lianndt** [comment]
Ok gracias! Entiendo que mandar todo el paquete junto es tedioso para la serializacion justamente.
Los algoritmos de planificacion intervienen para la distribucion de transformaciones, luego las reducciones se ejecutan en serie a medida que terminan las transformaciones de un nodo.  Ahi me quedo claro.
Saludos y feliz dia!
