### ISSUE TITLE
Nombre de los NODOS 

### ISSUE THREAD

**Issue by gvillarc91** [sisoputnfrba/foro#870]
Es un detalle pero a efectos de simplificar quizá el protocolo me surge la consulta:

**¿El largo del nombre de un nodo se pretende que sea variable o da igual?**

Pregunto porque si tomamos una convención: NODO1, NODO2, NODOX siempre contamos con un largo fijo a la hora de serializarlo y safamos de enviar de antemano el tamaño (como con la IP).

Ahora, si se pretende que sea flexible y que el nodo quiza se llama: soyUnNodoReLargo1 lo hacemos dinámico.

Alcaración: me refiero al nombre que figura en la composición del archivo que dice: BLOQUE0COPIA0=[NODO1, 34].

Gracias.

**Comment by nicozar95** [comment]
Buenas

> ¿El largo del nombre de un nodo se pretende que sea variable o da igual?

¿Cambia mucho? Si la mayor complejidad de el nombre es que ademas tenes que mandar el tamaño para serializarlo, no me parece tan grave tener un largo variable. 
Dicho esto, nos da lo mismo la longitud del nombre del nodo, si es variable o igual. Elijan la que les sea mas facil para ustedes :smile: 

Saludos y feliz dia del estudiante!

**Comment by gvillarc91** [comment]
Esmás que nada para tener en cuenta todas las alternativas y no terminar eligiendo una que viole el enunciado por estos detalles. Muchas gracias e igualmente!!
