### ISSUE TITLE
memcpy segmentation fault para serializar

### ISSUE THREAD

**Issue by guillelle** [sisoputnfrba/foro#871]
Hola,

estoy teniendo problemas de segmentation fault para serializar un struct y quizá alguien sepa por qué, pongo el código:

typedef struct{
	int id;
	int tamPayload;
}headerProtocolo;
char* serializarHeader(headerProtocolo header){
	char *headerSerializado=malloc(sizeof(int));
	memcpy(headerSerializado,(char *) header.id,sizeof(int));
	memcpy(headerSerializado,(char *) header.tamPayload,sizeof(int));
	return headerSerializado;
}

mirando la ppt de serialización y buscando en internet deduje esa forma de hacerlo y no se qué está mal

gracias
saludos

**Comment by juanlarosa96** [comment]
Hola!
Fijate que los parametros del memcpy son 3. El primero es el puntero en donde vas a copiar los datos, el segundo es el puntero desde donde vas a copiar los datos y el último es el tamaño de lo que vas a copiar. 
> memcpy(headerSerializado,(char *) header.id,sizeof(int));

Acá como segundo parámetro estas pasando header.id. Por un lado, lo estas parseando como un (char *), fijate que header.id no es un puntero, sino que es la variable id dentro del struct , la cual definiste como un int. Al memcpy tenes que pasarle el puntero del cual tiene que leer los datos, no la variable directamente. Para referirte a la direccion de memoria que contiene a esa variable, tenes que escribirla como &header.id. El & indica que te referis a la direccion de memoria de esa variable.

TL;DR; Agregale el & al header.id

**Comment by juanlarosa96** [comment]
Una segunda cosa que acabo de notar. 
> memcpy(headerSerializado,(char *) header.id,sizeof(int));
memcpy(headerSerializado,(char *) header.tamPayload,sizeof(int));

Estas haciendo los dos memcpy sobre el puntero headerSerializado. O sea que estas escribiendo el id en memoria y luego sobreescribiendolo con el tamPayload. Ustedes en la serialización, lo que esperan tener es los dos int en memoria, uno al lado de otro, pero como hago para decirle al memcpy que escriba el segundo int a continuación del primero, en vez de escribirlo encima? Bueno la solución está en que averigüen un poco sobre aritmética de punteros

**Comment by guillelle** [comment]
bien, con el & se corrigió el error de segmentation fault pero me seguía dando problemas porque no se copiaba bien. Lo solucioné con la función de las commons char * string_itoa(int).
Me queda resolver la segunda parte que es la aritmética de punteros
gracias

**Comment by sciciliani** [comment]
Perdón que me meta, pero serializar un (solo) struct es como agarrar una
caja que viene del correo, sacar el contenido, meterlo en una caja
exactamente igual, cerrarla y mandarla al correo.

En palabras más técnicas, un struct es memoria contigua, por ende podrías
leerla/copiarla/transferirla completa directamente desde el identificador.

Hacer esto:
memcpy(headerSerializado,(char *) header.id,sizeof(int));
memcpy(headerSerializado *+ sizeof(int),*(char *)
header.tamPayload,sizeof(int));

Te va a dar el mismo resultado que esto:
memcpy(headerSerializado,(char *) header <http://header.id/>
,sizeof(header));

:-)

Llegado el caso que a continuación del struct header quieras agregar algo
más, un payload por ejemplo, ahí si tiene sentido serializar. El resultado
de ese malloc sería algo tipo:

| struct header | void* payload |


Armate una función que reciba un payload de tipo void* (cualquier cosa), un
tamaño y un identificador de mensaje y devuelva otro void* que sea el ese
payload con la cabecera correspondiente delante.

Ultima. Fijate que le agregué a tu codigo el +sizeof(int). Te faltó el
desplazamiento en headerSerializado. Sin eso ambas copias van a caer al
principio y no uno a continuación del otro



2017-09-21 23:06 GMT-03:00 guillelle <notifications@github.com>:
