### ISSUE TITLE
Consulta sobre planificacion

### ISSUE THREAD

**Issue by guillermo126** [sisoputnfrba/foro#872]
Buenas tengo una duda sobre la planificacion,

supongamos que tengo dos masters: master 1 y master2  y el quantum es de 3 y cada uno tiene por igual 6 etapas de transformacion, 2 de reduccion local y bueno una global(cada master solo tiene un nodo para que se ejecuten las etapas). a la hora de planificar me surge dudas de como se plantea, yama deberia:

1¿darle a master las 3 rafagas de una? es decir 3 periodos de transformacion y cambiar de proceso
o
2)¿ deberia ir mandando de a una esperando a q termine una para que pueda avanzar con la otra y asi hacerlo hasta que termine el quantum?

**Comment by lianndt** [comment]
Adhiero consulta... yo hasta el momento entiendo que el Round Robin lo que hace es ir asignando las transformaciones de bloques de a uno,  uno por worker. Por ejemplo: si master me pide trabajar sobre un archivo que tiene 6 bloques, y yo en el sistema tengo 2 workers conectados. Entonces va recorriendo los bloques de a uno y va asignando: bloque 1 a worker1, bloque 2 a worker2, bloque3 a worker1, bloque 4 a worker2, etc.
Seria correcta esta manera? En ese caso, estaria trabajando con un quantum = 1?

**Comment by tferraro** [comment]
Muy buenas!

Dado que ustedes no fueron los primeros que consultaron respecto de esto, decidimos estandarizar [el funcionamiento de los algoritmos](https://sisoputnfrba.gitbooks.io/yama-tp-2c2017/content/anexo-ii--algoritmos-de-planificacion.html).

Terminaba pasando que se generaba una confusión entre la variación RR que tenían que implementar y el que ven en la teoría. Esto se da, principalmente, por lo que se explica al principio del doc, dado que el funcionamiento del uso del "Quantum" está muy ligado a la versión de RR de planificación de procesos, no la genérica. Por lo tanto, cortamos por lo sano, definimos bien detallado justamente lo que están preguntando (y de paso le cambiamos el nombre así se evitan confusiones).

Cualquier consulta me avisan. Saludos!

Tom

PD: Quería contestarles antes, pero sin el doc publicado iba a ser difícil 😢

**Comment by tferraro** [comment]
Buenas!

El uso de los algoritmos es **obligatorio**, para poder estandarizar las pruebas. Si no, vamos a tener 20 soluciones distintas al mismo escenario de pruebas y el resultado que van a obtener no va nunca a coincidir.

Terminás implementando básicamente lo mismo a fin de cuenta. En tu versión, por ejemplo, si solo  avanzas circularmente como corresponde, si un bloque no te corresponde con ese worker, tenés un problema y la forma de elegir siempre el primero te terminaría generando que tengas una gran carga en un par de nodos y el resto vacio, ese es, por ejemplo, el problema de tu implementación.

Respecto a esto, te pido disculpas el bolonqui, teníamos en mente un par de implementaciones similares entre si, que daban el mismo resultado y lo dejamos libre a elección......cosa que claramente no paso, porque no había solamente un par similares; y era necesario parar el carro antes de que se descarrillen todos los vagones.

Saludos!

**Comment by lianndt** [comment]
Ok gracias!, Lo que pensaba hacer era salvar cual fue el worker al cual se le asigno bloque la ultima vez, cosa que en la proxima asignacion de bloques se continua con el siguiente. De esa manera habria una distribucion equitativa. Pero ahora por la estandarizacion lo voy a llevar al formato de calcular esa disponibilidad.

Saludos!

**Comment by tferraro** [comment]
@guillermo126 el anexo aclaró un poco los tantos?

**Comment by guillermo126** [comment]
ahora que se cambio el algoritmo de planificacion sigo con un par de dudas:
a) yo tenia entendido que antes lo que se planificaban eran los job/master, ahora en clock y w-clock lo que se planifican son los workes nada mas?  siempre considere al job/master al proceso al cual yo tenia que planificar ya que es el que lanza la acntidad ya realizar, pero quizas este confundido.
b) por lo que yo entiendo estos algoritmos hacen una pre-planificacion y me determinan el proximo worker a ejecutar calculando la carga que tienen y el que menor carga tenga es el proximo que ejecute, eso seria correcto? 
c) en cuanto a rafagas de ejecucion, el worker selecionado de esa pre-planificacion deberia realizar toda la actividad sobre el/los bloques y hasta que no termine yo no podria volver a planificar entre los otros nodos, no?

**Comment by tferraro** [comment]
Buenas!

a - El problema que vas a tener es que no podes planificar Jobs, tal como ampliamos en el anexo y _en las charlas del sábado_. Esto pasa porque, primero nunca vas a planificar más de 1 Job al simultáneo y segundo porque no existe el concepto de asignación ni de expropiación sobre un Job asignado a un Nodo.

b - Si y no. La pre-planificación te va a decir cuales son los Workers sobre los que el Job tiene que ejecutar su actividad, no son secuenciales.

c - Justamente, no hay ráfagas de ejecución. El cambio de nombre fue, en parte, porque nos dimos cuenta que algo así iba a pasar:  Cuando uno habla de RR en la teoría, habla del RR para planificación de procesos, el RR básico es un tanto más diferente. Además, el TP no planifica procesos, _posee un balanceador de carga_, esto implica otra versión del RR que no corresponde al de planificación de procesos, de ahí el cambio de nombre. Pero si, lo que decís es correcto, justamente no hay expropiación en la actividad sobre los Nodos.

Quedó un poco más claro?

Saludos!

**Comment by lianndt** [comment]
Gracias Tomas, ahora que se va entendiendo mas la nueva propuesta de planificacion, tengo algunas dudas mas:

1) En las reglas de funcionamiento, paso 2 dice: "Si se encuentra, se deberá reducir en 1 el valor de disponibilidad y avanzar el Clock al siguiente Worker". Ahi entiendo que si el numero de bloque se encuentra en el datanode correspondiente al worker elegido por el clock, se hace la asignacion, actualizo mi tabla de estado y despues actualizo disponibilidad. Ahora bien, esa disponibilidad se debe restar en 1 siempre, sin importar el algoritmo? O es solamente en el caso de que sea Clock? Me genero esa duda, porque si el algoritmo es el WClock, no habria que actualizar la disponibilidad de TODOS los workers? Ya que la disponibilidad depende de la carga de trabajo global de todos. No es el caso de Clock, donde solamente toco la disponibilidad del worker en cuestion. 
Osea, cuando actualizo las disponibilidades pisaria la de cada uno aplicando la formula: AV(w) = base + PWL(w). Mismo caso si tengo que RESTAURAR la disponibilidad porque se llego a cero, aplico la formula directamente.

**Comment by guillermo126** [comment]
Tomas se entendió perfecto sólo me qda una pregunta sobre el apartado B en el cual me respondiste si y no.
Planteó denuevo un ejemplo en el cual yo pienso q funcionaría así y me gustaría q me respondan si es q sería correcto o no: tengo dos jobs cada uno con dos nodos cada uno, j1 tiene n1 con carga de 2 y n2 con carga de 3 y j2 tiene n3 y n4 de carga 3 y 4 respectivamente. Yo pienso q la pre planificación me determina esas cargas (de cada nodo)y después yama tendría que mandar a ejecutar en orden según la menor carga. Siguiendo el ejemplo para mi ejecutarla primero n1 luego n2,n3 y por último n4 sería correcto pensarlo Así?

**Comment by tferraro** [comment]
Buenas!

@lianndt Si, la diferencia entre el nClock y el W-Clock es solamente, el cómo calculas la Función de Disponibilidad. El resto del comportamiento es exactamente el mismo.

@guillermo126 No, vamos por partes. YAMA pre-planifica a demanda, arma el _Plan de Ejecución del Job_ y se lo pasa a Master. No manda a ejecutar según un orden de menor carga, los Jobs se pre-planificarán mientras vayan apareciendo, justamente es la diferencia fundamental de **porque no es un escenario de planificación**.

**Comment by guillermo126** [comment]
Claro perfecto, entonces esto quiere decir que a medida q a yama se le conecten jobs, lo que hace es armarles el plan de ejecución según el algoritmo de pre planificación y después manda a ejecutar. No hay ningún orden de ejecución para los jobs sólo que respeten la pre-planificación anteriormente echa. ¿asi sería?

**Comment by tferraro** [comment]
![image](https://user-images.githubusercontent.com/7110539/31198222-dea4122c-a929-11e7-8f87-a12d6e6bdea8.png)

**Comment by fmc21** [comment]
Consultas:
1) En el momento en que YAMA planifica (es decir que un Master le envió una solicitud de procesamiento de un archivo) y corre el algoritmo, se incrementa en 1 la carga de los workers seleccionados, a) ¿también debería ya elegir al worker encargado de la reduccion global? b) ¿o lo elige cuando el Master le informa que finalizó la última Reducción Local? Si fuese en b) ¿se elige al encargado entre todos los workers, sin importar que haya o no realizado alguna Transformacion/Reduccion Local?

Si bien en el enunciado dice lo siguiente:
> 
> Etapa de Reducción Global
> Al recibir la última notificación de una tarea de Reducción Local deberá ejecutar la etapa de Reducción Global involucrando los archivos pre-agregados de todos los nodos. Para la misma, se seleccionará un Nodo que actuará como Encargado de realizar la misma. Dicho Nodo será seleccionado por ser el que menos carga de trabajo poseía al momento de empezar la etapa (Least Loaded Node).

La duda se me generó por el ejemplo que vimos en la charla, en el cual se selecciona al encargado cuando termina de correr el algoritmo:
![imagen](https://user-images.githubusercontent.com/26329474/31242742-5a3bf9e0-a9de-11e7-838c-30a01d3c8295.png)
Supogo que el ejemplo considera que no se planificó otra solicitud de otro Master, por lo que en el momento de elegir al worker encargado de la Reduccion Global las cargas se mantuvieron iguales.

2) Yo entendí que sin importar el algoritmo, sea CLOCK o W-CLOCK, al comienzo de cada planificación, se deben calcular las disponibilidades de todos los workers (en base al algoritmo) y luego apuntar el Clock al primero de mayor disponibilidad. ¿Esto es correcto?

3) En el ejemplo que dieron en el Anexo II no entiendo por qué en la tercera ejecución el Clock apunta al worker 1 (W1) cuando en realidad, por lo que entendí, debería apuntar al de mayor disponibilidad, en este caso el worker 3 (W3).
![imagen](https://user-images.githubusercontent.com/26329474/31244399-3ad00608-a9e0-11e7-9204-fe12d848956d.png)

4) En la charla me dijeron que la lista de workers no hace falta que esté ordenada, ¿no podría pasar que al no estar ordenada se puedan generar diferentes resultados del algoritmo? Consulto debido a la respuesta que se dió en este mismo issue donde comentan lo siguiente:
> Si no, vamos a tener 20 soluciones distintas al mismo escenario de pruebas y el resultado que van a obtener no va nunca a coincidir.

Para que YAMA obtenga la lista de workers, lo que pensamos es que cuando el FS le da la lista de bloques con sus copias, analice si el nodo/worker ya está en la lista y sino lo agrega. ¿Esto está bien? ¿o en el momento en que YAMA se conecta con el FS por primera vez, el FS ya le debería dar la info de todos los nodos/workers del sistema?

**Comment by tferraro** [comment]
Holis

Primero que nada, la pre-planificación se hace solo 1 vez., eso implica que la elección del encargado tambien también se realiza en ese momento, solamente cambiando si es necesaria volver a pre-planificar. En la charla, la ppt está puesta así a fines didácticos, pero nunca implicó que se hiciera más tarde, en la misma charla justamente dijimos esto. 

2 - Correcto! La única diferencia entre ambos es la forma de obtener la disponibilidad.
3- Riesgos del Copypaste 😄. El resultado es correcto, pero nos olvidamos de modificar el funcionamiento respecto del anterior, debería quedar así:

![image](https://user-images.githubusercontent.com/7110539/31247034-c29fb696-a9e5-11e7-9a42-7905a411b5a4.png)


4 - No hace falta que esté ordenada según un criterio en particular, pero siempre tiene que estar en el mismo orden, idealmente, alfabético, pero nunca reordenar la lista, de ahí venia la respuesta que dieron en la charla.
5? - Te reprogunto. Si YAMA ya se conectó al filesystem y agregaron un nuevo archivo sobre el cual vas a trabajar, con tu segunda opción, funcionaria?

**Comment by lianndt** [comment]
Hola! Estaba pensando en hacer la actualizacion de disponibilidades de workers cada vez que se actualiza la tabla de estado, y no cuando se inicia la planificacion. 
Tendria sentido esto? Supongamos que le asigno el bloque1 a worker1, en ese momento la tabla de estado se le agrego un registro, por lo tanto el WLMax del sistema se incremento en 1, por tanto tambien el WL del worker. En ese momento no tendria que actualizar las disponibilidades de todos antes de pasar al proximo bloque? Ya que vario el peso del sistema (esto tiene sentido con W Clock, pero con Clock bastaria con restarle un 1 al worker en cuestion). Resumiendo, siempre hay que restar en 1 la disp del worker, sin importar el algoritmo?? La formula se aplica una sola vez al principio de la planificacion?

**Comment by fmc21** [comment]
Gracias por la pronta respuesta!

1) Entonces habría que modificarlo en el enunciado ya que dice todo lo contrario y presta a confusiones. Dice que se elige al encargado cuando le llega a YAMA la última notificación de una tarea de Reducción Local. 

> Etapa de Reducción Global
Al recibir la última notificación de una tarea de Reducción Local deberá ejecutar la etapa de Reducción Global involucrando los archivos pre-agregados de todos los nodos. Para la misma, se seleccionará un Nodo que actuará como Encargado de realizar la misma. Dicho Nodo será seleccionado por ser el que menos carga de trabajo poseía al momento de empezar la etapa (Least Loaded Node).

2), 3) y 4) Perfecto!

5) Claramente no xD

**Comment by tferraro** [comment]
Buenas!

Ya masomenos cerraron todas las dudas?

**Comment by fmc21** [comment]
Por mi parte si!

**Comment by tferraro** [comment]
Genial!

@guillermo126 @lianndt por su lado?

**Comment by lianndt** [comment]
Si ya esta, por mi podemos cerrar esto

**Comment by tferraro** [comment]
Cierro esto, cualquier cosa me chiflan y lo volvemos a abrir 😄

**Comment by maria-angslz** [comment]
Buenas, nosotros teníamos pensado hacer lo mismo que plantearon aca, en el handshake pedir la ip y el puerto de los nodos que tenga conectados el filesystem y luego tener un hilo de escucha activo en yama,  para en caso de que ocurriera algun cambio en alguno de lo nodos 
poder modificar alguno de esos valores, pero leyendo la respuesta no sugiere que el envio de esa información sea en el handshake ya que podria cambiar el archivo, entonces como podriamos encarar eso? Que nos sugieren? En que caso va a cambiar el archivo? A que se refieren exactamente?  Gracias
