### ISSUE TITLE
[FS] Consulta escritura en archivos

### ISSUE THREAD

**Issue by Gruschka** [sisoputnfrba/foro#873]
Hola!

Tengo una duda super newbie pero que me tiene desde las 10pm hasta casi las 2 AM sin poder avanzar.

Estoy haciendo el tema de la tabla de Nodos. Mas precisamente, guardar el nodos.bin que tiene el tamanio de todos los nodos conectados al fs, bloques libres, etc. 

Yo tengo una funcion que, cuando se conecta un dataNode por primera vez, se fija si existe el archivo nodes.bin. Si existe devuelve un puntero al archivo y si no lo crea, tambien devolviendo un puntero al archivo. Esa funcion se ve mas o menos asi:

<img width="673" alt="screen shot 2017-09-25 at 1 50 30 am" src="https://user-images.githubusercontent.com/11674324/30792837-f0f26e4e-a193-11e7-9a5a-c263554c5eb3.png">

Despues de invocar a esta funcion, inmediatamente invoco a una funcion que actualiza el nodes.bin. Aca tengo el problema. Basicamente arranco sacando el valor que haya despues del '=' en TAMANIO usando string_split y en nodeTableParameter[1] me termina quedando '0\n'  porque el fgets incluye siempre el \n (en la primer corrida, si vengo de crear el nodes.bin, tamanio es 0). Despues hago una grasada para sacarle el \n y pasarlo a entero con atoi (probablemente esto que este haciendo esta como el tuje pero es lo unico que se me ocurrio a estas horas, aunque debuggeando eso parece andar y acumula el valor correctamente segun los distintos datanodes que conecto al fs ¯\_(ツ)_/¯)
La funcion en cuestion es esta:
<img width="1106" alt="screen shot 2017-09-25 at 1 59 10 am" src="https://user-images.githubusercontent.com/11674324/30793009-26591492-a195-11e7-8ff1-2549f1a6129d.png">

El problema que tengo es que fputs, por alguna razon que no logro ver (sospecho que de alguna manera estoy sacando un \n?) me escribe un caracter de mas, y me queda el archivo de nodes.bin asi:

<img width="116" alt="screen shot 2017-09-25 at 2 00 14 am" src="https://user-images.githubusercontent.com/11674324/30793034-4fff1486-a195-11e7-93b8-3cec8d7a0db8.png">

Entiendo que la primera vez al tener un 0 es un solo digito, y que si yo lo reemplazo por un entero de dos digitos estaria reemplazando el digito siguiente, puede ser?  Porejemplo, si yo guardo "TAMANIO=%d                \n" no tengo este problema porque tiene mas caracteres hasta el \n para ir reemplazando, pero entiendo que esto es muy grasa hasta para mis estandares.

Disculpen otra vez el wall of text y si la pregunta no corresponde al ser mas bien de codigo.

Muchas gracias por la mano como siempre!

**Comment by varas-c** [comment]
Hola!

No llegué a entender exactamente cual es el problema. Aproximadamente en
qué linea decís que está fallando? En la que es fputs(lineBuffer,
nodeTableFile)? (casi la última de la 2da imagen)

Cual és el "caracter de más" que supuestamente está escribiendo? Viendo la
foto del "resultado", a "Libre" le falta una L y en Nodos hay un caracter
especial (similar a un rectángulo). Decis que cuando guardás "Tamanio", hay
algo que está pisando la L del siguiente renglón?



2017-09-25 2:08 GMT-03:00 Gruschka <notifications@github.com>:

**Comment by fedebonisconti** [comment]
Se parece _bastante_ a un [archivo de configuración de las commons](https://github.com/sisoputnfrba/so-commons-library/blob/master/tests/unit-tests/resources/config.cfg), no?

Siendo así, podrías ver de usar [esta](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/config.c#L124) función :)

**Comment by nicozar95** [comment]
Buenas
Fijate que cuando estas escribiendo el archivo, el mismo se parece mucho a un archivo de configuracion y podes aprovechar las siguientes funciones de las commons para [escribirlo](https://github.com/sisoputnfrba/so-commons-library/blob/master/src/commons/config.h#L92).

Igual si queres seguir por como lo estas encarando (no recomendable) estas escribiendo mas datos de lo que tenias antes, entonces estas pisando la otra linea. Para que te remplaze justamente lo que vos queres tenes que estar escribiendo el mismo tamaño de linea que la que estas reemplazando
(Por ejemplo, reemplazar `TAMANIO=0` con `TAMANIO=2`, cosa que no siempre el tamanio de un nodo va a ser desde 0 a 9 :P)

Entonces lo que deberias hacer, si es que vas a encarar por ese camino en vez de usar las commons, seria leer todo el archivo, cambiar la linea que quieras cambiar y reescribir todo el archivo. Que es como implementamos la funcion de modificar un archivo de configuracion en las commons y como lo hacen la mayoria de los editores de texto :wink: 

Saludos
Nicolas Zarewsky

**Comment by Gruschka** [comment]
Hola Chicos!

Muchas gracias a todos! Es una excelente idea encararlo con las funciones de config, no se me hubiera ocurrido a mi.

Una consulta: Yo ya tengo importado config.h en mi proyecto, pero no veo las funciones que comentan para setear valores. Puede ser que no la tenga 'actualizada'? Si yo hago ctrl click en una funcion de config.h para abrirlo en eclipse, solamente me aparecen estas funciones:

	t_config *config_create(char *path);

	/**
	* @NAME: config_has_property
	* @DESC: Retorna true si key se encuentra en la configuracion.
	*/
	bool 	  config_has_property(t_config*, char* key);

	/**
	* @NAME: config_get_string_value
	* @DESC: Retorna un string con el valor asociado a key.
	*/
	char 	 *config_get_string_value(t_config*, char *key);

	/**
	* @NAME: config_get_int_value
	* @DESC:Retorna un int con el valor asociado a key.
	*/
	int 	  config_get_int_value(t_config*, char *key);

	/**
	* @NAME: config_get_long_value
	* @DESC:Retorna un long con el valor asociado a key.
	*/
	long	  config_get_long_value(t_config*, char *key);

	/**
	* @NAME: config_get_double_value
	* @DESC:Retorna un double con el valor asociado a key.
	*/
	double 	  config_get_double_value(t_config*, char *key);

	/**
	* @NAME: config_get_array_value
	* @DESC: Retorna un array con los valores asociados a la key especificada.
	* En el archivo de configuracion un valor de este tipo debería ser representado
	* de la siguiente forma [lista_valores_separados_por_coma]
	* Ejemplo:
	* VALORES=[1,2,3,4,5]
	* El array que devuelve termina en NULL
	*/
	char**    config_get_array_value(t_config*, char* key);

	/**
	* @NAME: config_key_amount
	* @DESC: Retorna la cantidad de keys.
	*/
	int 	  config_keys_amount(t_config*);

	/**
	* @NAME: config_destroy
	* @DESC: Destruye la estructura config.
	*/
	void 	  config_destroy(t_config *config);

**Comment by nicozar95** [comment]
¿Cuando instalaste las commons? Porque esta nueva funcionalidad se agrego hace 3 meses.
Fijate de actualizarlas

Saludos

**Comment by Gruschka** [comment]
Ahi actualice la commons. Si abro yo los archivos manualmente las nuevas funciones me aparecen, pero en eclipse no se reflejan los cambios, ya saque la commons y la volvi a incluir. Hay algo mas que haya que hacer? 

Perdon por la pregunta boba jaja.

Muchas gracias!

**Comment by nicozar95** [comment]
Fijate si haces click derecho->Index->Rebuild ¿Te compila y anda las nuevas funciones?

**Comment by Gruschka** [comment]
Mmmm no me toma las nuevas funciones, solo estas:
<img width="472" alt="screen shot 2017-09-25 at 10 26 00 am" src="https://user-images.githubusercontent.com/11674324/30810575-f866995a-a1db-11e7-85b8-13500918337b.png">

Y si abro el archivo .h de la commons veo esto que supungo esta actualizado:
<img width="828" alt="screen shot 2017-09-25 at 10 27 53 am" src="https://user-images.githubusercontent.com/11674324/30810678-372206d4-a1dc-11e7-8d0b-4a259059a62d.png">

**Comment by CarolinaPonceRodriguez** [comment]
Buenas, fijate que aparte de pullearte la libreria, tenes que "recompilarla": hacer el make y make install nuevamente, hacer lo mismo que decia en el video para instalar las commons.

Saludos.

**Comment by Gruschka** [comment]
Esto anduvo perfecto. 
> Buenas, fijate que aparte de pullearte la libreria, tenes que "recompilarla": hacer el make y make install nuevamente, hacer lo mismo que decia en el video para instalar las commons.

Perdón otra vez por la pregunta tonta nuevamente. Encaro entonces esto con las funciones de la commons. Gracias chicos!
