### ISSUE TITLE
Ejecución de las etapas de Transformación y Reducción Local 

### ISSUE THREAD

**Issue by mtimossi** [sisoputnfrba/foro#874]
Sería un enfoque correcto esperar a que todas las transformaciones hayan terminado para comenzar la etapa de reducción local? El enunciado dice lo siguiente (Etapa de Transformación):

_Cuando en un Nodo se ejecutaron todas las operaciones de Transformación, inmediatamente pasará a la Etapa de Reducción Local._

... y está en negrita. Estaría mal encararlo de la otra manera?

**Comment by sciciliani** [comment]
La reducción local requiere que todas las transformaciones* de ese Nodo*
hayan terminado.

Entonces no sería correcto esperar a todas las transformaciones (del
sistema) sino solamente a las que corresponden a ese Nodo.



2017-09-26 10:02 GMT-03:00 Matías Timossi <notifications@github.com>:

**Comment by mtimossi** [comment]
Entiendo que con todas las transformaciones del sistema te referis a **todas las transformaciones de un job especifico**. Cuando afirmas  que hay que esperar solamente a las que corresponden a ese Nodo, te referis a que si hubiera multiples transformaciones de distintos jobs ejectuandose en un mismo nodo deberíamos esperar a que terminen las mismas?

**Comment by sciciliani** [comment]
Tal cual.

2017-09-26 10:45 GMT-03:00 Matías Timossi <notifications@github.com>:

**Comment by mtimossi** [comment]
Gracias!

**Comment by gustofa** [comment]
Consulta sobre esto.
Matias pregunta:
>  Cuando afirmas que hay que esperar solamente a las que corresponden a ese Nodo, te referis a que si hubiera multiples transformaciones de distintos jobs ejectuandose en un mismo nodo deberíamos esperar a que terminen las mismas?

y se le confirma
> Tal cual.

No se supone que para que se ejecute la Reducción Local deben haber terminado todas las transformaciones de ese Nodo que corresponden a ese job en particular?
De lo dicho arriba se entiende otra cosa, que habría que esperar a que finalicen todas las transformaciones del nodo sea cual sea el job al que corresponde.



Saludos

**Comment by mtimossi** [comment]
Reabro el issue para que se le conteste a @gustofa. Saludos.

**Comment by tferraro** [comment]
Buenas!

El _Tal cual_ de Santi fue respecto a:

> Entiendo que con todas las transformaciones del sistema te referis a todas las transformaciones de un job especifico

No a la segunda parte, que sería un _"o pasa esto"_.

tl;dr: Con que se completen las transformaciones del Nodo en ese Job de __ese__ Master, ya puede lanzar una reducción local. en ese Nodo

**Comment by gustofa** [comment]
Perfecto. Gracias por la confirmación.

Saludos
