### ISSUE TITLE
Consulta sobre Yama Agnóstico

### ISSUE THREAD

**Issue by mtimossi** [sisoputnfrba/foro#875]
El enunciado afirma que:

_El proceso YAMA es agnóstico de qué operación realiza el proceso Master sobre los datos sin embargo es quién conoce dónde y cuándo ejecutar las operaciones para obtener el resultado deseado._

Sin embargo debe poseer una tabla indicando **la etapa**  en la que se encuentra cada worker. 
Incluso de alguna forma debemos poder diferenciar en YAMA si la operacion que estamos realizando requiere de multiples nodos (reducción local) o de uno solo (reducción global) .

**Esto nos genera ciertas dudas de que tan agnostico sea el YAMA. Estaría mal que exista algun tipo de tipificación de las operaciones en YAMA?**

**Comment by iago64** [comment]
Aloha aloha, 

A lo que hace referencia el TP de que YAMA es agnóstico es en referencia al script que ejecuta,  YAMA solo sabe las etapas (y en consecuente los tipos de operación pueden ser preparación, reducción local, reducción global), es decir, podrias y no estaria mal tener una tabla donde tengas una especie de secuencia de ejecución del proceso.
Ahora si el script que ejecuta sobre los datos es para obtener la cantidad de letras E que le puso el Diego a una frase transcrita desde Instagram o si esta tratando de encontrar la clave del Home Banking de Ricardo Fort en la base de datos del Banco Nación a YAMA le da lo mismo :)

**Comment by sciciliani** [comment]
Hola Matías,

El enunciado, en otras palabras, dice que YAMA no sabe que se va a hacer
sobre los datos, es decir, no sabe que va a hacer el programa transformador
o el programa reductor (cajas negras) sobre los archivos. Lo que si sabe es
el orden en el que lo debe ejecutar y sobre que bloques.

Las tareas en YAMA están tipificadas como las diversas etapas.




2017-09-26 10:31 GMT-03:00 Matías Timossi <notifications@github.com>:

**Comment by mtimossi** [comment]
Clarisimo, gracias!
