### ISSUE TITLE
Almacenar archivo de tipo TEXTO

### ISSUE THREAD

**Issue by CarolinaPonceRodriguez** [sisoputnfrba/foro#876]
Buenas, tengo una duda con la siguiente parte del enunciado: 
_"En el caso de los archivos de texto, dado que los mismos pueden no necesariamente terminan alineados a 1 MB, para evitar que queden registros partidos la operación de escritura debe asegurarse antes de escribir cada nuevo renglón (\n)[^3] que el espacio en el bloque sea suficiente"_

Para el caso de un archivo binario es sencillo, divido el choclo de bytes en partes iguales de 1MB y todos felices, pero no se como hacer con un archivo de texto.
Lo que se me ocurria era que es posible que el ultimo bloque a escribir pueda no necesariamente terminar a un 1MB, pero "bloques intermedios" pueden no estar completos por bytes del mismo archivo sino, entiendo que por basura, ya que un bloque puede contener unicamente a bytes de un archivo.
Para hacerlo mas sencillo pongo un ejemplo, supongamos bloques de 10 bytes y yo tengo un archivo de 32 bytes, lo logico para mi seria guardar asi:
1er bloque: 10 bytes
2do bloque: 10 bytes
3er bloque: 10 bytes
4to bloque: 2 bytes (8 restantes son basura)

Es asi? 
Gracias!

**Comment by iago64** [comment]
Efectivamente, muy posiblemente en el 99,9% de los casos te pase que te quede un espacio al final del ultimo bloque.
En el caso de un archivo de texto de 32 bytes y si suponemos registros de 8 bytes y bloques de 10 bytes te debería quedar de la siguiente forma:
1er bloque: 8 bytes - 2 bytes de basura
2do bloque: 8 bytes - 2 bytes de basura
3er bloque: 8 bytes - 2 bytes de basura
4to bloque: 8 bytes - 2 bytes de basura

Saludos.-

**Comment by CarolinaPonceRodriguez** [comment]
Entonces resumiendo:

Archivo Binario: Los registros seran de 1MB, esto coincide con los bloques de los nodos de 1MB, por lo cual  los bloques siempre se usaran en su totalidad. 
1)Podrian existir casos en los que dichos archivos no completen el ultimo bloque y en tal caso rechazar el guardado del archivo? 

Archivo de Texto: Se puede determinar un tamaño de registro distinto al tamaño de bloque.
2) En el caso de un registro mas chico al tamaño de bloque, queda basura en el bloque.
3) Que sucede si el registro es mas grande que el tamaño de bloque? Guardo el sobrante en el siguiente bloque o rechazo el guardado del archivo? 
3) Donde se determina el tamaño del registro del archivo?

Gracias.

**Comment by iago64** [comment]
1.- No, si no completan el ultimo bloque no pasa nada, simplemente tenes que poder saber donde termina el archivo para no pasarle basura al script que procese esos datos.

2.- Exacto, esa basura tenes que poder identificarla para evitar pasarsela al script como parte del registro.

3.- No va a pasar ya que los bloques son de 1MB y no vamos a hacer registros muy grandes, 1Mb es mucho para una línea de texto. 
Eventualmente si queres checkear que cada registro no supere el tamaño de 1Mb podes hacerlo.

3 (bis).- El tamaño del registro viene determinado por el caracter \n tal cual esta explicado en el apartado del[ File System](https://sisoputnfrba.gitbooks.io/yama-tp-2c2017/content/proceso-filesystem.html)

> En el caso de los archivos de texto, dado que los mismos pueden no necesariamente terminan alineados a 1 MB, para evitar que queden registros partidos la operación de escritura debe asegurarse antes de escribir cada nuevo renglón (\n)3 que el espacio en el bloque sea suficiente.

> 3- El valor \n indica ‘New Line’ o ‘Nueva línea’. Equivale al ingreso de un [Enter] en el teclado.

**Comment by CarolinaPonceRodriguez** [comment]
Perfecto! No habia entendido que iba a encontrar el \n "escrito" en el texto.
Gracias!

**Comment by sciciliani** [comment]
El "\n" es la representación del *enter* (salto de linea) en un texto.

**Comment by CarolinaPonceRodriguez** [comment]
Buenas, ahora realizando una prueba me surge una duda con el salto de linea:
Si yo tengo un archivo del cual debo leer para formar mis registros esto es sencillo porque busco hasta encontrar el caracter \n "no es visible pero esta".
El tema surge cuando yo recibo el choclo de texto para guardar, el fs recibe un char * con el texto a guardar, el tema es que en este caso, para que sea reconocido el salto de linea debo escribir el \n para que este sea reconocido por el interprete.
Doy el siguiente ejemplo:
"Esta es\n una prueba \n de salto de\n linea"
Daria:
1) Esta es
2)  una prueba 
3) de salto de
4) linea

Osea para el caso en el que tengo que guardar los datos, ese char * es lo que recibo del worker, y esa es la unica manera que encuentro posible de que sea reconocido el salto de linea, que este explicito.
Estoy en lo correcto?
Saludos.

**Comment by iago64** [comment]
Carolina, 

En una prueba de escritorio si, vos tendrias que poner los caracteres \n, pero eventualmente en el texto vos podrias tener el mismo efecto si por ejemplo tomas un texto y le pones los enter a mano en un editor de texto y lo guardas.

Otra forma que podes llegar a tener para probar el tema de los saltos de linea es por ejemplo armarte algún archivo de excel con un par de columnas de datos aunque sean numeros y guardarlo como csv:

![image](https://user-images.githubusercontent.com/1622109/30913152-8ad1ebf2-a365-11e7-8d68-cf5137591d18.png)

Y eventualmente si abris el resultado con un editor vas a ver algo asi:

![image](https://user-images.githubusercontent.com/1622109/30913172-9e85ed92-a365-11e7-9371-1fddf30e0b50.png)

Si te fijas ves que tiene varios ; porque son celdas vacías y terminan todas con un salto de linea que es el \n que vos estas esperando.

**Comment by CarolinaPonceRodriguez** [comment]
Entiendo lo que decis pero no es a lo que me estoy refiriendo,  en el enunciado dice lo siguiente:
_"El proceso Master entonces le solicitará al Worker encargado que se conecte al Filesystem y le envié el contenido del archivo de Reducción Global y el nombre y ruta que este deberá tener."_

Eventualmente el FS recibe de worker un paquete que contiene la ruta, nombre de archivo y los datos a guardar. Esos datos a guardar lo definimos como char *.  Puedo como FS suponer que ese char * ya cuenta con el caracter \n implicito?  Porque el unico caso en el que leo de un archivo fisico los saltos de linea es cuando tengo que armar el archivo con los bloques de los nodos conectados.

Saludos.

**Comment by iago64** [comment]
Aaaah ahora si estamos en tema :)
Si, no te preocupes, como FS vos recibís el char* y asumís que el resultado ya esta con el formato que corresponde, tené en cuenta que puede pasar que un resultado final de la reducción global sea 1 solo registro con un número :)

**Comment by CarolinaPonceRodriguez** [comment]
Aun así deberá tener su correspondiente \n implicito si se definio que era un archivo de texto, si fuese archivo binario seria otro tema.
Gracias! Cierro issue.
