### ISSUE TITLE
Funciones de Consola Fs

### ISSUE THREAD

**Issue by CarolinaPonceRodriguez** [sisoputnfrba/foro#877]
Buenas, esta consulta tiene relacion con lo requerido para el FS para el check 2 y algunas funciones de la consola del Fs.
Para este check se solicita:
-Desarrollar las Estructuras del FileSystem (Tablas de Directorios, Archivos, Nodos, Bitmap)
-El FileSystem debe permitir la copa de un archivo al yamafs y almacenarlo partiéndolo en bloques.

Para almacenar un archivo el fs lo corta en bloques y guarda dos copias de cada bloque en nodos distintos.  A su vez, esto implica actualizar las estructuras administrativas correspondientes. Mi pregunta  es con respecto a si es necesario "hacer uso" de las funciones de la consola para llevar a cabo ciertas operaciones que el FS necesita hacer para almacenar un archivo. 
Por ejemplo, el FS recibe una ruta X del archivo y si no la tiene en la tabla de directorios procederia a crearla tanto logicamente como fisicamente. 
Quiza entiendo que la consola es un plus y no es estrictamente necesario operar sobre la misma para llevar a cabo el procesamiento de los archivos en el FS, lo que si hara la misma es alterar las estructuras del mismo dependiendo del comando que se utilice.

Gracias.

**Comment by juanlarosa96** [comment]
No estoy seguro de entender la pregunta, pero por lo que decis si, la consola "es un plus" en el sentido de que cuando al FS le llegue por ejemplo un pedido de almacenamiento en una etapa de Almacenamiento Final, no es necesario que involucre a la consola en el proceso. De todas formas, seguramente vayan a tener una funcion "AlmacenarNuevoArchivo" y tanto la consola como los pedidos de almacenamiento la van a usar, pero eso no quiere decir que el pedido de almacenamiento tenga que pasar por la consola. 
¿Esto te aclaró las dudas o venia por otro lado lo tuyo?

**Comment by CarolinaPonceRodriguez** [comment]
Pegaste en el palo! Gracias, cierro issue.

Saludos!
