### ISSUE TITLE
Worker - Apareo de archivos

### ISSUE THREAD

**Issue by gustofa** [sisoputnfrba/foro#878]
👋 ¡Hola!

Respecto al apareo que debe hacerse de los archivos temporales antes de correr la rutina de reducción, ya sea local o global, es correcto que el mismo se realice en el proceso "padre" antes de hacer el fork que se encargará de correr el script de reducción?

Saludos

**Comment by iago64** [comment]
Buenas buenas!
Te puedo contestar con otra pregunta? 
Si vos desde el proceso padre le pasas el input por entrada estándar al proceso hijo con los datos sobre los que tiene que ejecutar la rutina de reducción, que otra alternativa tenes si no es haciendo el apareo en el padre? 

La respuesta es que alternativas, como haber, hay muchas, la que planteas es válida, otra (**muy fea** pero viable) que se me ocurre es que podrías hacer un proceso hijo que arme el apareo y este a su vez tenga otro hijo para que procese.

Fijate la forma que les resulte mas amigable de implementar, ya que en el [enunciado ](https://sisoputnfrba.gitbooks.io/yama-tp-2c2017/content/componente-nodo.html)no te dice nada respecto a quien tiene que hacer el apareo, solo te dice que tenes que hacer antes de pasarselo al script de reducción

**Comment by gustofa** [comment]
Si, pensaba lo mismo, pero quería confirmarlo.

Gracias
