### ISSUE TITLE
¿Como diferenciar archivos de texto y binarios al cargar?

### ISSUE THREAD

**Issue by dromero-7854** [sisoputnfrba/foro#879]
Buenas nuevamente,

Estoy implementando el comando **cpfrom** _path_archivo_origen directorio_yamafs_ y me queda la siguiente consulta:

Hay dos tipos de archivos: binarios y de texto. Dependiendo el tipo de archivo, se guarda el archivo dentro de yamafs con una cierta lógica: los archivos binarios se cortan en _bloques de 1MB_, y los de texto en registros completos de _hasta 1MB_.

Dentro de los parámetros no se encuentra que tipo de archivo estoy copiando a yamafs. ¿Es viable tomar que si el achivo tiene extensión _.bin_ es un archivo binario? ¿Hay alguna función en C que me pueda proveer esta información?

**Comment by CarolinaPonceRodriguez** [comment]
Buenas, estuve investigando un poquito  y hay un comando que es file, este te devuelve info referida al archivo, como por ejemplo, el tipo de archivo. Ahora supongamos que le pasas un PDF, este te devuelve que es de tipo PDF text, en este caso no sabria si considerarlo como un archivo de texto, desconozco como se interpretaria asi que me sumo al pedido.
Un plus: para ejecutar comandos tenes las funciones system() y/o popen()

Saludos.

**Comment by dromero-7854** [comment]
Estoy leyendo que la sintaxis de los comandos no es de carácter obligatorio, por lo que podría incluir un parámetro que me indique que el archivo es binario...

**Comment by iago64** [comment]
Aloha!
@CarolinaPonceRodriguez , La idea que propones esta muy buena peeeero estas sumandote algo de laburo extra de entender una funcion.
Como bien dice @dromero-7854 si bien les pasamos una sintaxis en el [enunciado](https://sisoputnfrba.gitbooks.io/yama-tp-2c2017/content/proceso-filesystem.html), hay una pequeña parte que aclara:

> A continuación se hará una breve descripción de los comandos a utilizar mediante una sintaxis cómoda pensado por la cátedra. La sintaxis de los mismos **no es de carácter obligatorio**, pero se recomienda su uso dada la similaridad con los comandos usuales. Como aclaración, algunos comandos pueden llegar a ser reutilizables para diferentes tareas. Debido a esto, cada una de ellas tendrán asignadas un flag (no combinables entre sí) para identificar de qué comportamiento se trata.

Con lo cual pueden por ej poner el parametro tipo que sea B o T para Binario o Texto (por dar un ejemplo)

**Comment by dromero-7854** [comment]
Buenisimo... Gracias por la aclaración.

Cierro el issue.

Saludos!
