### ISSUE TITLE
Sobre el proceso de inicialización del FileSystem

### ISSUE THREAD

**Issue by nanorarias** [sisoputnfrba/foro#880]
Buenas:

Estaba releyendo [la sección que habla de la inicialización del proceso FileSystem](https://sisoputnfrba.gitbooks.io/yama-tp-2c2017/content/proceso-filesystem.html), cuando me topé con un par de dudas. En particular sobre lo que resalto en negrita en estos dos párrafos:

> […] Una vez que se hayan conectado los DataNode requeridos, se deberá **formatear el FileSystem, pasando el mismo a un estado estable**, en el cual **permitirá que se conecten Workers** o YAMA, a quien responderá solicitudes sobre los archivos. Mientras que el FileSystem no adquiera un estado estable, el mismo no deberá permitir la conexión de YAMA u otro proceso que no sean DataNode. Además, **una vez formateado el FileSystem, no se permitirán nuevos Nodos en el sistema**.
> 
> […] Una vez adquiridas **al menos 1 copia de cada archivo**, se considerará que el proceso FileSystem ha pasado a un estado estable y permitirá nuevamente conexiones de los demás procesos. Además, **aunque el proceso FileSystem pase a un estado estable, permitirá que los nodos que todavía no se conectaron, vuelvan a hacerlo**.

1. En ninguna otra parte del enunciado más que en esta se hace alusión a una conexión directa entre un proceso **Worker** y el **FileSystem**. ¿Puede ser que sea un error? ¿O realmente tiene que haber conexión directa vía sockets entre los Workers y el FileSystem? Porque si la tiene que haber, no logro ver por qué sería.
2. ¿Los «nodos que todavía no se conectaron» vendrían a ser los que habían quedado en el estado anterior recuperado por el FileSystem al iniciar? Una vez alcanzado el estado estable, el FileSystem solo debería dejar que se conecten instancias de **DataNode** —¿Y **Worker**?— del estado anterior y el proceso **YAMA**, ¿correcto?
3. Con lo de «al menos una copia de cada archivo», se refiere a que cada archivo tenga replicados sus bloques por lo menos una vez, con cada bloque copia guardado en un nodo distinto del que guarda el bloque original, ¿cierto?
4. Para conseguir el estado estable del **FileSystem** se necesitan los archivos. Para conseguir los archivos se necesita que el usuario ejecute instancias de **Master** y se los pase como argumento. Para ejecutar instancias de **Master** se necesita que **YAMA** esté corriendo. Para que pueda correr **YAMA** se necesita que el **FileSystem** esté en estado estable. ¿Esto no sería un _[catch-22](https://en.wiktionary.org/wiki/Catch-22)_?

Edición: agrego un par de dudas más.

**Comment by tferraro** [comment]
Buenas!

1.  Revisate el apartado de la etapa de Almacenamiento Final 😄 
2.  Nodo es la forma abstracta en la que la ve el resto del Sistema, cuando desde el punto de vista del FS se interactúa hacia un nodo, es hacia el proceso DataNode. Justamente, el texto que citas hace alusión a los Nodos (DataNodes fisicamente) que estaban conectados en una version anterior del FS pero no se conectaron todavia.
3. No, con que solo haya una sola copia del bloque en todo el FS está, osea, una sola "instancia". La forma de referirse a esto es similar a los hardlinks que ven en la teoría.
4. Te estás mezclando. Master trabaja sobre archivos existentes en el FS, dado que está modelado bajo el concepto de WORM. Los archivos del FS se copian al mismo o desde consola o como resultados de un Job ( y solamente resultados, los temporales, y scripts no forman parte dle yamafs). Obviamente, si el FS no tiene archivos, con lo mínimo para almacenar 1 archivo estamos (que en este caso son 2 Nodos, dado que estaríamos en un escenario muuuuy parecido a RAID 1+0).

Si con esta última parte en el punto 4 seguís sin que te termine de cerrar, buscame el sábado en las charlas y lo ampliamos :).

Saludos!

**Comment by nanorarias** [comment]
> 3. No, con que solo haya una sola copia del bloque en todo el FS está, osea, una sola "instancia".

Perfecto. Me gusta más eso de llamarlas instancias de bloque, más que copias, porque la palabra copia presta a confusión en este contexto. O sea que —a ver si entendí bien— si, por ejemplo, el estado anterior tenía un solo archivo y justo se conecta un DataNode que tiene una instancia para todos y cada uno de los bloques de ese archivo, ¿el FileSystem ya podría pasar a un estado estable?

> Master trabaja sobre archivos existentes en el FS, dado que está modelado bajo el concepto de WORM.

Entiendo. Una pregunta relacionada con esto: el enunciado dice que cuando le pasás a Master los archivos de origen y destino como argumento, se los pasás con el prefijo `yamafs:` para indicar que son archivos del file system de YAMA. ¿Qué debería pasar si le paso una ruta sin ese prefijo como archivo de origen? ¿Debería copiar ese archivo del file system local al file system de YAMA?

> si el FS no tiene archivos, con lo mínimo para almacenar 1 archivo estamos (que en este caso son 2 Nodos, dado que estaríamos en un escenario muuuuy parecido a RAID 1+0).

¿O sea que para formatear un FileSystem sin estado anterior necesitás como mínimo dos nodos (uno para los bloques originales y otro para los bloques copia), pero para levantar un FileSystem con estado previo necesitás como mínimo un solo nodo (que contenga una instancia de cada bloque de cada archivo del estado guardado)?

**Comment by tferraro** [comment]
Re 1. Si!
Re 2. Nada, podrías incluso pasarselos sin el prefijo. Está por un tema didáctico de evitar confusiones entre el filesystem local y el filesystem del tp.
Re 3.  En realidad, no. No hay ninguna limitación a nivel tp que diga que no podes pasar a estado estable con 1 solo nodo cuando lo levantás desde 0, justamente para ese caso se pasa a estado estable una vez que se formatea. Incluso con un estado anterior, pero sin archivos (ojo que no es lo mismo), con 1 podrías levantarlo y estar en un estado estable. Esto es a decisión suya como grupo, lo mio era una sugerencia.

Particularmente viene por esto: ` una operación de escritura deberá balancear la asignación de los bloques entre todos los Nodos del sistema, junto con evitar que el mismo bloque de datos de un archivo esté más de una vez en el mismo nodo.` . Hay que tratar de evitarlo, pero en casos limites, se puede tomar una solución de compromiso y decir "fue, quedará duplicado el bloque en el mismo nodo". Lo importante, como dije antes, es que puedas almacenar al menos 1 archivo, sino dejaría de tener sentido no?

**Comment by nanorarias** [comment]
Perfecto, resueltas todas las dudas. ¡Gracias!
