### ISSUE TITLE
Ordenamiento y apareo de archivos binarios

### ISSUE THREAD

**Issue by nanorarias** [sisoputnfrba/foro#881]
Cuando el enunciado habla sobre hacer un ordenamiento (_sort_) para almacenar el resultado de una transformación de manera ordenada, y después cuando habla del _apareo_, los ejemplos que da siempre son con archivos de texto:

[![](https://sisoputnfrba.gitbooks.io/yama-tp-2c2017/content/assets/pipeline.png)](https://sisoputnfrba.gitbooks.io/yama-tp-2c2017/content/componente-nodo.html#etapa-de-transformación)

[![](https://sisoputnfrba.gitbooks.io/yama-tp-2c2017/content/assets/apareo.png)](https://sisoputnfrba.gitbooks.io/yama-tp-2c2017/content/anexo-i--apareo-de-archivos.html)

Pero el sistema YAMA también soporta archivos binarios, con lo cual me surge la duda: ¿cómo sería el ordenamiento y el apareo con archivos binarios?

**Comment by tferraro** [comment]
Buenas!

Eso es porque _los archivos binarios sirven/existen sólo a nivel FileSystem_, los Jobs trabajarán siempre con archivos de texto.

Saludos!

**Comment by nanorarias** [comment]
O sea que si el usuario hace `./Master transformador.sh reductor.py yamafs:/imagen.png yamafs:/resultado.jpg` podría detectar que está queriendo ejecutar una tarea sobre un archivo binario y no dejarlo, ¿no?

Gracias, duda resuelta.
