### ISSUE TITLE
Discrepancia en el enunciado en la etapa de reducción local

### ISSUE THREAD

**Issue by nanorarias** [sisoputnfrba/foro#882]
Leyendo la sección de la etapa de [reducción local del lado de YAMA](https://sisoputnfrba.gitbooks.io/yama-tp-2c2017/content/proceso-yama.html#etapa-de-reducción-local) y comparándola con la de la [misma etapa del lado de Master](https://sisoputnfrba.gitbooks.io/yama-tp-2c2017/content/proceso-master.html#etapa-de-reducción-local), me encontré con la siguiente discrepancia:

#### Reducción local del lado de YAMA

> Al recibir los mensajes del proceso Master notificando que una tarea de Transformación fue concluida deberá revisar en la tabla de estados ha concluído todas las Transformaciones para **un mismo nodo**, en ese caso puede iniciar las tareas de Reducción Local.

#### Reducción local del lado de Master

> En esta etapa el proceso Master deberá indicarle a **los Workers** correspondientes cuáles son los archivos temporales sobre los cuales deberá aplicarse el programa de Reducción, y dónde guardar sus resultados.

En la sección de YAMA siempre se habla de _un_ nodo en particular que termina las transformaciones y puede empezar la reducción local, pero en la sección de Master se habla de _varios_ Workers —por consiguiente varios nodos—, y de que recibe de YAMA información de varios nodos, cuando en la sección de YAMA decía que solo había terminado uno con las transformaciones.

¿A qué se debe esta diferencia? ¿Hay algo que se está obviando / dando por entendido o es un error del enunciado?

**Comment by tferraro** [comment]
Buenas!
No entiendo la consulta. Ambos textos simplemente hablan de 2 cosas diferentes, uno sobre que YAMA permite que se efectúe una etapa de reducción en el Nodo una vez completadas las transformaciones del mismo (mirate #874 si te sigue sin cerrar) y el otro habla que Master debe delegar la tarea de reducción local a cada uno de los Workers.

Worker es un término indistinto para Nodo en este caso dada la arquitectura del sistema planteada. Cuando hayaque generar una reducción local puede hacerse en 1+ Nodos, pero se van a ir ejecutando una vez que se vayan concluyendo sus Transformaciones, no se iniciarán todas las simultáneo siempre.

Saludos!

**Comment by nanorarias** [comment]
Había leído #874, y entiendo todo lo que decís, pero no iba a lo que preguntaba.

Lo pongo como si fuese un diálogo entre los procesos, que me parece que se va a entender mejor:

**MASTER.**—Che, YAMA, la tarea de transformación del nodo #X terminó bien.
**YAMA.**—Bien, era la última así que ya podemos pasar a la reducción local. Arrancá nomás.
**MASTER.**—Dale, ahora le aviso a los Workers correspondientes que pueden empezar con eso.

Eso es lo que entiendo yo que pasa según lo que dice la parte que cité del enunciado. Termina **un nodo** pero Master le avisa no a uno, sino a **N Workers**. ¿Por qué? ¿Quiénes son estos N Workers? ¿No debería avisarle solo al Worker correspondiente al nodo que terminó la transformación?

**Comment by tferraro** [comment]
Ahí te seguí, se te están mezclando los temas: Una cosa es lo que dicen los fragmentos del enunciado, que están haciendo referencia a 2 cosas diferentes y otra la forma en la que interactúan.

Uno de los textos habla como interactúa Master con Yama y el otro Master con los Workers; pero eso no implica que sea todo seguido (si no, estaría redactado todo junto y no en 2 apartados diferentes). Justamente esto es lo que te decía antes, respecto de lo que estás armando como diálogo, está bien, solo esto:

MASTER.—Dale, ahora le aviso *al Worker* correspondiente.

Esto lo hace n veces según los workers que haya.

**Comment by nanorarias** [comment]
¿O sea que en ningún momento Master recibe de YAMA una solicitud de reducción local que involucre a **varios nodos** como da a entender el enunciado (ver imagen a continuación)? ¿Siempre es **una solicitud para cada nodo**?

![](https://i.imgur.com/RE5pUHD.png)

**Comment by tferraro** [comment]
Buenas!

Vamos por partes, estás planteando 2 situaciones diferentes.

Una es la que venimos hablando que es que tomas tus transformaciones terminadas de un mismo nodo y generás un evento para empezar la reducción.

En la otra situación, lo que estás pasando es un _ejemplo_ de algo que puede pasar, que hayan terminado varias al simultáneo y esté iniciando varias reducciones. La idea es que la respuesta termine siendo una especie de array con 1 o más elementos. Esta respuesta múltiple no es obligatoria, es una causalidad; la respuesta, en la mayoria de los casos van a ser async y van a terminar respondiendo sobre 1 nodo, pero es menester aclarar este tipo de respuesta en el enunciado **porque es un caso que puede pasar**.

Si ves que te sigue sin cerrar, creo que esto amerita más una charla, que verlo por un medio digital. Venite mañana a las charlas y lo vemos :wink:

Saludos!

**Comment by nanorarias** [comment]
Ahora sí me quedó claro. Gracias.
