### ISSUE TITLE
Inicializacion de Filesystem

### ISSUE THREAD

**Issue by CarolinaPonceRodriguez** [sisoputnfrba/foro#884]
Buenas, genero este issue en base al #880, particularmente sobre el siguiente parrafo comentado por @tferraro : 
_"Particularmente viene por esto: una operación de escritura deberá balancear la asignación de los bloques entre todos los Nodos del sistema, junto con evitar que el mismo bloque de datos de un archivo esté más de una vez en el mismo nodo. . Hay que tratar de evitarlo, pero en casos limites, se puede tomar una solución de compromiso y decir "fue, quedará duplicado el bloque en el mismo nodo". Lo importante, como dije antes, es que puedas almacenar al menos 1 archivo, sino dejaría de tener sentido no?"_

Como no esta especificado quiero saber si la siguiente opcion podria ser valida si esta correctamente justificada:
Para poder entrar en un estado estable suponiendo que el sistema es nuevo necesitaria como minimo dos nodos conectados para poder tratar el balanceo de asignacion de bloques ya que se requiere que exista dos instancias en nodos distintos, por otra parte, si alguno de ellos se desconectara, aun tendria disponible los bloques en el nodo restante.

Saludos.

**Comment by tferraro** [comment]
Buenas!

Me parece bien! Perdería el sentido tener los bloques duplicados para generar redundancia, pero de nuevo, como dije ne el issue que mencionás, depende de lo que quieran implementar. Si les cierra implementarlo así, 10 puntos! La justificación es más que adecuada.

**Comment by CarolinaPonceRodriguez** [comment]
Perfecto! Cierro, saludos.
