### ISSUE TITLE
Consulta al devolver los bloques de un archivo

### ISSUE THREAD

**Issue by cmedrano** [sisoputnfrba/foro#885]
Hola tengo una duda al devolver los bloques de un archivo

Cuando el FS tiene que devolver a YAMA los bloques que compone un archivo , el FS tiene que consultar en ese momento la info que esta en el data.bin es decir lo que esta en el disco o puedo consultar la info que tengo en una lista de bloques del archivo que tengo armado en memoria en ese momento.
que se aconseja en este caso? 

Saludos

**Comment by mgarciaisaia** [comment]
:wave: Cris, fijate que, si no me estoy olvidando de algo, el FS no le devuelve a YAMA _los bloques_, si no _el listado de bloques_. Es decir, a YAMA no le interesa _el contenido_ de los bloques (los datos que el archivo contenga), si no simplemente saber en dónde se encuentra cada bloque de datos que compone el archivo.

Para conseguir esa info, ¿qué estructuras necesita mirar el FS?

**Comment by tferraro** [comment]
Buenas! @cmedrano te sirvió la respuesta de Mati? Contanos en que andas! 😄

**Comment by tferraro** [comment]
Cierro este issue por inactividad :slightly_smiling_face: . Cualquier cosa que la duda siga, no dudes en volverlo a abrir!
