### ISSUE TITLE
¿Error en el enunciado? 

### ISSUE THREAD

**Issue by gastonbaeza** [sisoputnfrba/foro#886]
Buenas, en el enunciado hay un párrafo que se repite, lo copio:

"Archivo​ ​de​ ​Log
El proceso DataNode deberá contar con un archivo de configuración en el cual se logearán
todas las operaciones realizadas. Las mismas deberán ser mostradas por pantalla."

(Mitad de página 27 y principio de página 30). 

Yo entiendo que el repetido en realidad se refiere al proceso Worker, pero igual quise preguntar por las dudas y para algún despistado.

**Comment by tferraro** [comment]
Buenas!

Por estas cosas es que _no hay que imprimirse o seguir una versión vieja del enunciado_. Esto fue reportado en #859 y fixeado en la versión 1.1.2 de la errata :smile: 

Saludos!
