### ISSUE TITLE
¿Otro Error en el enunciado?

### ISSUE THREAD

**Issue by dromero-7854** [sisoputnfrba/foro#887]
Buenas, les dejo una consulta...

Cuando se definen los comando de la consola de fs, dice:

`cpto [path_archivo_yamafs] [directorio_filesystem] - Copiar un archivo local al yamafs`

¿No seria "Copiar una archivo yamafs a un directorio local"? Si no entendí mal, el comando _cpfrom_ ya realiza esa función.

Saludos
Dante Romero

**Comment by tferraro** [comment]
Buenas!

Si, efectivamente debería decir: Copiar un archivo local **desde el** yamafs. En un ratito le fixeo el typo así nadie más se pierde.

Se agradece el debuggeo de copy/paste :smiley: !

**Comment by dromero-7854** [comment]
De nada jeje Saludos!
