### ISSUE TITLE
FS - Sobre el estado del sistema, al conectar nodos

### ISSUE THREAD

**Issue by dromero-7854** [sisoputnfrba/foro#888]
Buenas, consulta rapida: Entendí que el sistema se encuentra estable cuando existe para todos los archivos del FS, el bloque original y el bloque copia ¿esto es asi? ¿o con que exista una de las dos alcanza?

**Comment by juanlarosa96** [comment]
Buenas!
>Mientras que el FileSystem no posea al menos 1 copia de cada uno de los archivos almacenados en los DataNodes conectados, se denomina que el proceso FileSystem está en un estado no-estable.

Para que el FS esté en estado estable, tiene que poder acceder a todos sus archivos, así que con una sola instancia disponible de cada bloque alcanza

**Comment by tferraro** [comment]
:stuck_out_tongue: :eyes: https://github.com/sisoputnfrba/foro/issues/880#issuecomment-332872295

**Comment by dromero-7854** [comment]
Buenisimo, aclarado... Gracias!
