### ISSUE TITLE
Consulta sobre tabla de directorios (Posible error en al consigna?)

### ISSUE THREAD

**Issue by Gruschka** [sisoputnfrba/foro#889]
Hola Chicos,

Tengo una duda sobre la tabla de directorios.

Cada entrada deberia ser del orden: Index Nombre Index Del Parent?

Porque si yo veo la consigna:

<img width="550" alt="screen shot 2017-10-08 at 17 06 09" src="https://user-images.githubusercontent.com/11674324/31320442-034984d0-ac4b-11e7-82d6-c45ede7b76ee.png">

User tiene Index 1 y Juan y Jose tienen parent 1. Ahora bien Datos y Fotos que estan bajo Juan tienen como parent 2 que seria jose pero en realidad su padre es juan. Esto es asi?

Gracias!

**Comment by CarolinaPonceRodriguez** [comment]
Buenas, entiendo lo mismo que vos, se equivocaron, el padre para datos y fotos deberia ser el index 3.

Saludos.!

**Comment by sciciliani** [comment]
Buenas, entiendo lo mismo que vos, se equivocaron, el padre para datos y
fotos debería ser el index 3.
Saludos!

Pd: Va a la errata

**Comment by tferraro** [comment]
Presto la errata

![image](https://user-images.githubusercontent.com/7110539/31440505-8e1b88de-ae66-11e7-974b-b658c0386826.png)
