### ISSUE TITLE
FileSystem- Información referente a los Nodos

### ISSUE THREAD

**Issue by dromero-7854** [sisoputnfrba/foro#890]
Buenas, les dejo otra consulta:

Enunciado: 

>... YAMA obtendrá el proceso FileSystem toda la información referente a los Nodos sobre los cuales se encuentran los bloques a utilizar ...

Mi consulta es: La info que retorna FS sobre en que Nodos se encuentran los bloques del archivo ¿solamente incluye nodos conectados al FS no? ¿O también debe retornar datos sobre Nodos no conectados? La copia de un bloque debe encontrarse en otro Nodo, y el mismo puede no estar conectado, por eso la consulta.

Saludos!

**Comment by tferraro** [comment]
Buenas!

Le serviría a YAMA consultar sobre bloques que no están accesibles o no van a ser usados por el/los Jobs? Para pensar🤔

**Comment by dromero-7854** [comment]
Estoy entendiendo que a partir de tu pregunta que no. Mi duda venia de la mano que un proceso Worker puede estar ejecutándose, sin que en el nodo se levante un proceso DataNode. Pero intuyo que los procesos que forman parte del Nodo se ejecutan al mismo tiempo.

Cierro el issue y gracias por la aclaración.

Saludos!
