### ISSUE TITLE
Archivos de texto - Filesystem

### ISSUE THREAD

**Issue by gonzarochlin** [sisoputnfrba/foro#891]
Buenas, basándome en el enunciado y en algunas issues (#838, entre otras), me siguen surgiendo un par de dudas sobre como separar en bloques los archivos de texto.
Pensé en hacer un split del map y que me quede un array con el texto separado en todos los "/n".
Ahora, yo debería ir viendo:
Primero, si un renglón (una posición del array ya spliteado) es menor que el tamaño del bloque (1MB), y si así lo fuera, intentar concatenarle otro renglón (con el "/n") siempre respetando que sea menor que 1MB, y así sucesivamente hasta que no entre otro renglón.
Se entiende? Estoy en lo correcto?

Otra consulta... Para saber el tamaño en bytes de un char* (para ir comparando con el tamaño del bloque)?
Probé con sizeof(), strlen() pero no estoy seguro si alguno de esos es el tamaño en bytes...

Muchas gracias!

**Comment by tferraro** [comment]
Buenas!

No entiendo bien la pregunta, estás consultando si hay que guardar la data en los bloques separándolo con saltos de línea? Por lo que entiendo de lo que decís, lo dice bien claro en esta parte del enunciado :)
> En el caso de los archivos de texto, dado que los mismos pueden no necesariamente terminan alineados a 1 MB, para evitar que queden registros partidos la operación de escritura debe asegurarse antes de escribir cada nuevo renglón (\n)3 que el espacio en el bloque sea suficiente. En caso de que no lo sea, anotará la posición del último byte con contenido válido en la estructura administrativa del archivo y continuará en el próximo bloque. Cabe aclarar, que incluso si un bloque no estuviera completamente ocupado, solamente podrá ser ocupado por un único archivo a la vez.

Para la otra consulta: Tenés idea que es lo que hacen `sizeof` y `strlen()`? Cual es la diferencia entre los 2? `strlen()` necesita que se cumpla algo para que su comportamiento sea deterministico, cual es?

Saludos!

Tom

Nota: el `sizeof` es un _operador unario_, a pesar de que parezca una función, así que no hace falta agregarle los paréntesis, es completamente válido hacer `sizeof int`.

**Comment by gonzarochlin** [comment]
Buenas,
Mi duda era básicamente si hay que separararlos por salto de línea o ir acumulando las líneas hasta que no entren más.

Por otro lado, por lo que tengo entendido, strlen() me devuelve el tamaño del string sin incluir el ultimo dígito nulo y sizeof devuelve el tamaño en bytes de una variable o de un tipo de dato.
Gracias!

**Comment by tferraro** [comment]
Buenas!

La forma que lo quieras implementar, dependerá de lo que gustes, solo recordá que si el archivo es de texto y el proximo salto de linea se te pasa del tamaño de bloque, entonces tenés que cortar en el anterior.

> Por otro lado, por lo que tengo entendido, strlen() me devuelve el tamaño del string sin incluir el ultimo dígito nulo y sizeof devuelve el tamaño en bytes de una variable o de un tipo de dato.

Justamente como decís, `strlen()` devuelve el tamaño de el **string** que le pases. Guarda con los `char *` que no respeten el formato del string. Si tu `char *`  no respeta el formato, _no lo uses, repito, no lo uses_, vas a terminar generando comportamientos aleatorios.
Ahora, que podés hacer si ese es el caso? La primera pregunta a trabajar es: ¿Porqué querés saber la longitud de un stream?¿Si se comporta como string para vos (en vez de un stream), porqué no cumple con el formato del string?

Saludos!

tom

**Comment by nanorarias** [comment]
> Nota: el sizeof es un operador unario, a pesar de que parezca una función, así que no hace falta agregarle los paréntesis, es completamente válido hacer sizeof int.

No, justo en ese caso sí necesitás los paréntesis. Podés usar el `sizeof` sin paréntesis cuando estás evaluando el tamaño de expresiones (v. g. `sizeof una_variable`), pero al evaluar tipos tenés que ponerle los paréntesis sí o sí: `sizeof(int)`.

**Comment by tferraro** [comment]
Lo que dice @nanorarias es correcto! 

Te contesté respecto al escenario que planteaste sobre saber el tamaño de la variable, que en ese caso es un operador. Para el caso en el que se quiera saber el tamaño de un tipo de datos, los paréntesis son requeridos.

**Comment by gonzarochlin** [comment]
Ahí creo que lo entendí un toque más...
Lo que yo hago es acumular las líneas del archivo de texto en una variable de tipo char* (también acumulo los /n).
Así que creo que debería hacer algo a sí:
sizeOf(char*)*strlen(variable)
Eso me daría el tamaño en bytes, no?

**Comment by varas-c** [comment]
Gonza, guarda con sizeof(char*), creo que no es lo que buscás. Char* es un
puntero y lo que estas preguntando ahí, como dijo Tom mas arriba, es el
tamaño del tipo de dato o sea el tamaño del tipo de dato "puntero a char"

Hace la siguiente prueba y fijate lo que te muestra:

char *mensaje = "Hola como estan todos?"
print( sizeof(char*) )
print( sizeof(mensaje) )
print ( strlen(mensaje) )

En todo caso si queres realmente saber cuanto pesa en bytes una cadena,
supongamos char* mensaje = "Gonzalo"; Si haces strlen te va a dar el largo
de la cadena (sin el \n) o sea 7. Una cadena está compuesta por montón de
"char" juntos. Y como sabes cuanto pesa un "char"?

Podrías hacer algo como "Tamaño de un char" por "longitud de la cadena" no?



2017-10-12 9:09 GMT-03:00 gonzarochlin <notifications@github.com>:

**Comment by gonzarochlin** [comment]
Claro, tenes razón...
Muchas gracias!
