### ISSUE TITLE
Readline Autocompletado

### ISSUE THREAD

**Issue by juanignaciog** [sisoputnfrba/foro#892]
Hola

Quería saber si me podían dar una mano para el autocompletado de la biblioteca. Estaria funcionando con los comandos, pero se complica para que autocomplete los paths de yamafs por lo de tener el punto de montaje en un lugar diferente al root del fs linux(si le quiero pasar como argumento de un comando, una ruta del yamafs, no sabe como autocompletar). Hay una forma de agregar el punto de montaje a algun lado para que el readline verifique los directorios/archivos de ahi también? o la solucion va por otro lado?
Espero haber sido claro.

Saludos

**Comment by tferraro** [comment]
Buenas!

No entres ahí :stuck_out_tongue: 

Lo que te está pasando es que como el `yamafs` no existe como un filesystem para el ubuntu, el autocompletar simple de archivos no te va a funcionar.

Existen 2 soluciones: o cambiar la arquitectura del sistema para que el FS trabaje con el kernel (**NO QUEREMOS ESTO**), oooo ir por el lado de que tenés que implementar un set de opciones custom para autocompletar. Esto tampoco es muy feliz, aunque más fácil que lo anterior, justamente por eso _nunca terminé ese post medium, porque requiere un trabajo un poco más complejo_.

Si te interesa agregarlo, te diría que primero se preocupen por cerrar bien el TP. Una vez que lo tengan bien sólido, pueden empezar a agregar este tipo de detallitos. Si te sirve, te paso este [post](https://robots.thoughtbot.com/tab-completion-in-gnu-readline) que explica de manera bastante didáctica la base de como empezar; aunque para acá tendrías que poder darle acceso para leer tu tabla de directorios :disappointed_relieved: 

Saludos!

Tom

**Comment by juanignaciog** [comment]
Muchas gracias! Dale lo dejo asi entonces, me quedara leer el post en otro momento. Saludos
