### ISSUE TITLE
Comando MD5 sobre archivos YAMA

### ISSUE THREAD

**Issue by dromero-7854** [sisoputnfrba/foro#893]
Buenas nuevamente,

Estoy encarando el comando md5 del FS. No encontré una librería estandar de Ansi C para esta función.

- ¿Hay alguna manera de utilizar el comando md5sum de linux en el proceso FS? ¿Cómo?
- De ser asi, ¿podría ser una posible solución descargar un archivo yama a un directorio local y aplicarle dicha función para devolver el MD5?

Saludos
Dante Romero

**Comment by tferraro** [comment]
Buenas!

* Podrías hacer uso de _la misma idea que se plantea para las transformaciones y reducciones_. Estamos bajo el mismo caso de que querés ejecutar algo, que no sabés como está implementado, pero toma data del `stdin` y la devuelve por `stdout` :)
* Mientras que no quede en el filesystem y sea un archivo completamente temporal, no lo veo mal. Sin embargo, hay formas de hacerlo si armar el archivo en el filesystem local, aprovechando los pipes.

Saludos!

Tom

**Comment by dromero-7854** [comment]
1- Entendí la primera parte, pero no entiendo como lo aplico a mi problema. 
2- ¿Qué son los pipes en C? ¿Como los puedo aprovechar? (No se si es un tema de la materia jeje)

**Comment by tferraro** [comment]
Te paso una lectura recomendada de la parte del Nodo: https://github.com/nicozar95/ejemplo_correr-script_so, que contesta tu 2da pregunta, y seguramente tambien la primera :slightly_smiling_face:

**Comment by juanignaciog** [comment]
Hola

Me surgieron un par de dudas con esto. ¿La idea seria usar los pipes con el fork como hacemos con worker? ¿No dijeron que no hay que usar en el mismo proceso hilos (ya se usa uno para la consola del fs) y forks? Capaz entendí mal la idea que estabas tirando con lo de los pipes

Saludos

**Comment by nicopatronelli** [comment]
Aprovecho el issue... @tferraro por lo que entiendo, la función md5 se aplica sobre un archivo completo, por lo que primero debería armar el archivo que está distribuido por los distintos Nodos y luego aplicarla, es decir, tendría que unir los bloques que conforman el archivo... Entiendo que podría usar pipes dentro de un mismo Nodo, pero no como los aplicaría para armar el archivo distribuido por distintos Nodos...

Había pensado en calcular el md5 de cada archivo que se cargue en yamafs antes de distribuirlo por los Nodos, entonces me lo guardo en una matriz o archivo, y después simplemente lo consulto de ahí... el problema de esto es que no me salvo del caso anterior, pues también nos pueden dar un estado anterior de yamafs con los bloques ya distribuidos, y ahí ya no tengo más opción que hacer lo que mencione en el primer párrafo.... 

Gracias por el tiempo!

**Comment by tferraro** [comment]
Buenas!

@juanignaciog mezclar forks con hilos no es "malo", lo malo es no entender las implicancias que eso tiene y tooodo lo que conlleva. Aunque tenés un punto, cuando tiré la sugerencia, olvidé que les pedimos que no lo hagan así para no complicarse.
Andá por la que dijiste que es infinito más sencilla, armá el archivo con los bloques en un archivo temporal y aplicale el md5; y cuando termines lo eliminas :).

@nicopatronelli Tendrías que traerte una instancia de cada bloque del archivo, volverlos a unir y hacer el md5 sobre eso, no vale calcularlo de antemano 😏 .

La idea atrás del _¿¿Porqué nos hacen implementar el md5 de un archivo??_, es que tengan algo para chequear que separan bien el archivo, y si tienen problemas en los resultados de los Jobs, pueden distinguir si el problema está en el FS o en los Nodos.

Saludos!

Tom

**Comment by tferraro** [comment]
@dromero-7854 @juanignaciog @nicopatronelli Como vienen con esto?

**Comment by dromero-7854** [comment]
Como estas @tferraro

Ya implemente el comando. Armo el archivo temporal, aplico md5 y elimino el archivo. Utilizo la función _system_ para ejecutar el comando _md5sum_  sobre el archivo temporal. Todavía no lo probé, pero creo que va a funcionar.

Por mi parte, cerraría el issue. Pero no se si el resto esta de acuerdo y no tiene más dudas.

Saludos!
Dante

**Comment by juanignaciog** [comment]
A mi también me quedo claro, no tengo mas dudas

**Comment by tferraro** [comment]
Asumo que @nicopatronelli también pudo resolver sus dudas :stuck_out_tongue: así que voy dandole cierre a esto. Cualquier cosa no duden en abrirlo!
