### ISSUE TITLE
FS - cpblock

### ISSUE THREAD

**Issue by dromero-7854** [sisoputnfrba/foro#894]
Buenas, estoy desarrollando el comando **cpblock**:
> **cpblock** [path_archivo] [nro_bloque] [id_nodo] - Crea una copia de un bloque de un archivo en el nodo dado.

Consultas:
 ¿La copia del bloque se lo asigna al mismo archivo? 
De ser asi ¿Debo controlar que no haya más de tres copias del mismo bloque de archivo?

Saludos
Dante Romero

**Comment by tferraro** [comment]
Buenas!

Si! La idea del comando es que puedas crear una instancia más del bloque, para tener redundancia de los datos. Ahora, porqué controlarías que no haya más de 3?

Entendería el que no haya más de 2 por una interpretación conservadora del enunciado (por como pone los esquemas de ejemplo); pero a fines prácticos no debería haber ninguna limitante (más allá de espacio y esas yerbas) que te diga que no podes tener la cantidad de bloques que quieras.

Saludos!

Tom

**Comment by dromero-7854** [comment]
Mmmmm me surgue otra duda mas preocupante...

Si un bloque puede tener mas de dos copias, al momento de buscar el bloque para levantar el archivo (comando cpto) ¿Como verifico si existe la copia del bloque si no se cuantas copias hay del mismo? 

Es decir... Cuando levanto un archivo recorro el archivo metadata y voy consultando si existe la clave BLOQUE#COPIA0 ó BLOQUE#COPIA1 (se pueden eliminar comando rm -b) 
Si no existen ambas, doy por terminado la carga del archivo. No puedo tomar el tamaño del archivo para este fin, ya que para archivos de texto no me sirve esa información, ya que por la forma en que se guardan los mismos, puede por ejemplo pesar un 1Mb pero estar en dos bloques.

Estoy considerando hasta ahora que sólo puede haber dos copias de cada bloque. Si no es asi ¿Cómo soluciono la carga de archivos de texto sabiendo que puede haber X cantidad de copias para cada archivo y no teniendo esa información en el metadata del archivo?

**Comment by dromero-7854** [comment]
Ya encontré una posible solución a la ultima pregunta:

- Cuando levanto un archivo, puedo recorrer la clave BLOQUE#BYTES para saber cuando terminar de levantar (es una clave única por bloque)
- Y para saber cuantas copias de un bloque tengo en un archivo, puedo utilizar la función config_keys_amount de config.h, donde tengo un parámetro para saber cuantas consultas de existencia de la clave BLOQUEXCOPIA#. Si el archivo metadata no tiene problemas de fiabilidad, alguna copia deberia existir antes de llegar al valor de keys_amount. 

Voy a tener que revisar todas mis funciones, menos mal que salio el tema de las cantidad de copias de un bloque.

Gracias!

**Comment by dromero-7854** [comment]
Ya se me ocurrió una solución a la ultima consulta:

- Cuando levanto un archivo puedo utilizar la clave BLOQUE#BYTES (es única por bloque)
- Puedo utilizar la función config_keys_amount de config.h para tener un parámetro a la hora de consultar por la existencia de la clave BLOQUEXCOPIA#, y poder saber cuantas copias hay de un bloque.

Ya lo habia escrito pero no quedo en el issue. Lo cierro nuevamente.

Menos mal que salió el tema de la cantidad de copias de un bloque jaja

Gracias!

**Comment by dromero-7854** [comment]
Ya encontré una posible solución a la ultima pregunta:

- Cuando levanto un archivo, puedo recorrer la clave BLOQUE#BYTES para saber cuando terminar de levantar (es una clave única por bloque)
- Y para saber cuantas copias de un bloque tengo en un archivo, puedo utilizar la función config_keys_amount de config.h, donde tengo un parámetro para saber cuantas consultas de existencia de la clave BLOQUEXCOPIA#. Si el archivo metadata no tiene problemas de fiabilidad, alguna copia deberia existir antes de llegar al valor de keys_amount.

Voy a tener que revisar todas mis funciones, menos mal que salio el tema de las cantidad de copias de un bloque.

Gracias!
