### ISSUE TITLE
Consulta FORK

### ISSUE THREAD

**Issue by marrtins** [sisoputnfrba/foro#895]
Buenas, estaba siguiendo con la parte de workers-master y quería verificar que lo que estaba haciendo venía por buen camino...
Por ahora como estamos manejando el tema, en la parte de la transformacion) de procesos hijos es master le manda al worker _principal_(el padre) la solicitud de inicio, el script de transformación, el bloque a transformar y todos los detalles para poder hacer esta parte del proceso y luego, siguiendo el ejemplo que subió nico a github [ejemplo_system.c](https://github.com/nicozar95/ejemplo_correr-script_so/blob/master/ejemplo_system.c) hacemos la llamada system con los datos de entrada, el sort, la salida etc y nada más en el proceso hijo.

La duda es si, entendimos bien lo que refiere a system(); osea, la llamada system() ya hace el fork solo? con lo cual simplifica todo el hecho de ir haciendo fork() | pid==0 {} {}..etc etc o no estamos viendo bien lo que hace system() y todo eso lo tendríamos que cambiar...
 Por otro lado, la otra duda es que haciendo como lo tenemos, siempre estaríamos confiando en que esta transformación sale bien, ya que con esa linea sola de system(comandos a ejecutar), no podemos avisarle al proceso padre si la transfo salio bien o mal..

Gracias, Martín

**Comment by fedebonisconti** [comment]
Buenas!

Sí, [system()](http://man7.org/linux/man-pages/man3/system.3.html) hace fork, y después ejecuta [execv()](https://linux.die.net/man/3/execv).

[Acá](http://www.eglibc.org/cgi-bin/viewvc.cgi/branches/eglibc-2_9/libc/sysdeps/posix/system.c?view=markup&pathrev=7350) hay una implementación de [system()](http://man7.org/linux/man-pages/man3/system.3.html) hecha en _egclib_, como para ver cuál es la idea :)

En qué casos pensas que podría salir mal la transformación?

**Comment by marrtins** [comment]
Creemos que en ninguno, era mas que nada por las dudas..

Entonces con el tema del system(), podríamos recibir con el proceso padre todos los parametros para hacer la transformacion hacer un system(| transformador|sort| >... etc etc) y nos ahorramos el hecho de hacer fork()=pid y manejar el resto con un if grande, que compara el valor de pid, y decide dependiendo de que sea un proceso padre e hijo?

**Comment by tferraro** [comment]
Exactamente!

Podes o DIY y tener más control del asunto, o delegarle la operación completa a `system()`, que como hace el fork+execv internamente, no hace falta hacerlo ni la comparación para distringuir si es el padre o el hijo.

De todas maneras, recordá que **si** tienen que usar fork para las conexiones, eso no es opcional.

Saludos!

Tom

**Comment by marrtins** [comment]
Claro esa es la duda, si system ya hace el fork.. Para que necesito hacer yo otro fork() ?

Quería ver si podía evitar hacerlo.. Si hiciera fork y despues system es como hiciera 2 forks??

Perdón por estas dudas, pero como es medio difícil de debugear y ver, se me mezcló todo un poco

**Comment by tferraro** [comment]
Depende de **que** es lo que le pases a `system()`. Si haces el trabajo dentro de system con los pipes de bash ( | ) entonces, _no hace falta_.

La pregunta es: ¿Porque no hace falta? Tiene sentido crear un proceso hijo que va a ejecutar un `system` y esperarlo, _mientras el padre está esperando al hijo?_ Obvio que no 😄 , por eso no hace falta.

**Comment by marrtins** [comment]
Claro, es por eso que no se si esta bien que en ningún momento use la funcion fork() y dejar que system() haga todo el trabajo.

Yo armo un string grande con los | y ; para ejecutar toda la funcion desde system(muchos comandos) y entiendo que funcionaría bien en lugar del fork

**Comment by tferraro** [comment]
Buenas!

Aprovecho el espacio para hacer una aclaración. Hoy hablando con @eliasgabrielkim (creo que era el 😛) me comento algo que capas podria estar de fondo en este tema que no se pregunto pero viene bien aclararlo para evitarnos algun problema futuro.

En los Workers _no hay que usar select_, dado que es necesario que el Worker pueda procesar de forma simultanea los pedidos. Como no se puede usar hilos, la respuesta está en el enunciado: hacer un servidor multi-‘fork’ en vez de multi-hilo.

Saludos!

Tom

**Comment by gustofa** [comment]
Hola
> hacer un servidor multi-‘fork’

Eso me generó dudas.
Nosotros tenemos a Worker esperando con un recv dentro de un bucle infinito. Cuando llega el pedido de Master se procesa según la etapa que sea y se forkea para correr el script de transformación/reducción, pasándole por pipe al hijo lo que debe procesar.
Ahora bien, dentro del if de la bifurcación padre/hijo, en la parte de padre, usamos 
`waitpid(pid_hijo,&status,0);`
para esperar la finalización del hijo, leer el resultado por otro pipe y guardarlo en el archivo indicado.
Hasta que no pasa de ahí no vuelve a entrar al bucle para recibir otro pedido de master, con lo cual el multi-fork es secuencial, esto está bien?
o se podría hacer de otra manera?

**Comment by marrtins** [comment]
Nosotros  como servidor multi-hilo tambien, tenemos 1 accept solo adentro de un while, llega la solicitud de master, nos pasa el script al proceso padre y ahi hacemos fork y en el if del hijo una llamada a system con sus propios datos, ya que al haber recibido todo antes de ahcer el fork, el hijo ahora tambien lo va a tener
Exit y termina el proceso hijo.

Eso es lo que interpretamos como sv multi-hilo

**Comment by tferraro** [comment]
Buenas!

La de @marrtins es la forma que tenía en mente 😄 . Más que nada, porque con las demás uno empieza a tener algunos casos border que son complicados de solucionar.

**Comment by gustofa** [comment]
Ok, entiendo entonces que una vez hecho el fork, el proceso padre ya no espera nada del hijo y sigue iterando a la espera de una nueva solicitud de Master para volver a hacer otro fork, etc.
En el hijo usamos execv para correr el script, eso nos imposibilitaba de hacer algo en el hijo luego de esa línea, por eso lo pensábamos hacer en el padre al terminar el proceso hijo.

Si padre no espera a hijo, si es un padre ausente que los abandona y sigue procreando, dentro del if del hijo la única manera procesar el script y luego avisar al master que terminó es usando system, no?

O sea que en definitiva se estaría haciendo un fork implícito (usando system) dentro del fork explícito que hace el worker padre.

Está bien este razonamiento y mandé cualquiera?

Gracias. 
Saludos!

**Comment by marrtins** [comment]
El tema es que no debería hacer waitpid ni nada así porque sino desaprovecho el tema del paralelismo... Pero si el hijo hace system() y muere.. Como haría para avisarle al master que esa etapa de la transformación termino?

**Comment by tferraro** [comment]
@gustofa 

> Si padre no espera a hijo, si es un padre ausente que los abandona y sigue procreando, dentro del if del hijo la única manera procesar el script y luego avisar al master que terminó es usando system, no?

Best. Analogía. Ever. - Esa misma es la idea, tiene el mismo ciclo de vida que tendría un hilo.

> O sea que en definitiva se estaría haciendo un fork implícito (usando system) dentro del fork explícito que hace el worker padre.

Exactamente. Podes o hacer de nuevo un fork, con pipes y todo; ooo hacerla facil, lanzar un `system()` con los pipes de bash en el string (`| `) y lo maneja la biblioteca.

@marrtins Antes de llamar `exit()` te comunicás con Master y listo. De la doc del `fork(2)`:

>The child inherits copies of the parent’s set of open file  descriptors. Each  file  descriptor  in the child refers to the same open file description (see open(2)) as the corresponding file  descriptor in  the parent.  This means that the two descriptors share open file status flags, current file offset, and signal-driven I/O  attributes (see the description of F_SETOWN and F_SETSIG in fcntl(2)).

Osea, sí. Los FDs abiertos se heredan.
Y sí, la transformación podría fallar. Si el Nodo le avisa a Master que hubo un error o Master no recibe respuesta y se cerró el otro extremo, podríamos asumir que hubo un error no?

**Nota para los 2**, que es algo que capás no están tomando en cuenta (lo dije varias veces en forma física pero no me acuerdo a quien 😛 ): Si uno hace `exit()` en vez de retornar normalmente, está llamando a la syscall que provoca la eliminación del proceso. Diferencias? En un proceso normal, el compilador reemplaza el `return` de la función main justamente por un `exit`, para provocar esa salida. Sin embargo, en un proceso hijo, producto de un fork, no lo reemplaza con un `exit()`, sino que por algo más, que sirve para poder hacer `wait_pid()` y por lo tanto _dejando al hijo como zombie si todavía no se hizo el wait_pid en el padre_. Que solución podemos hacer para evitar eso y reemplazar el return del main?

**Comment by marrtins** [comment]
> Que solución podemos hacer para evitar eso y reemplazar el return del main?
Eso no tengo muy claro, yo por ahora venia haciendo directo con el exit que habia preguntado por otro lado... pense que con eso alcanzaba

Y en esto:
> Y sí, la transformación podría fallar. Si el Nodo le avisa a Master que hubo un error o Master no recibe respuesta y se cerró el otro extremo, podríamos asumir que hubo un error no?
Entiendo que si el nodo se va sin mandar msj es porque fallo, pero cuando el nodo le manda un msj a master asumiendo que hubo un error.. Como se daria cuenta? Eso no me queda muy claro

**Comment by tferraro** [comment]
@marrtins  Pos si, la respuesta era terminar el hijo con `exit()` 😛 

Para lo otro, vos definirías si terminó con error o no, por ende el mensaje lo elegís vos. Si el tema es, como haces para saber si hubo un error? http://man7.org/linux/man-pages/man3/system.3.html#RETURN_VALUE

**Comment by gustofa** [comment]
Aclaradas varias dudas.
Tengo que hacer varios cambios.  :satisfied:

Gracias!

**Comment by DarkWood97** [comment]
Disculpen por si ya lo respondieron pero entonces no hay que hacer un wait_pid porque sino no hay paralelismo, no? O sea con el exit en el hijo basta? No se originarian procesos zombies?

**Comment by tferraro** [comment]
> En un proceso normal, el compilador reemplaza el return de la función main justamente por un exit, para provocar esa salida. Sin embargo, en un proceso hijo, producto de un fork, no lo reemplaza con un exit(), sino que por algo más, que sirve para poder hacer wait_pid() y por lo tanto dejando al hijo como zombie si todavía no se hizo el wait_pid en el padre. Que solución podemos hacer para evitar eso y reemplazar el return del main?

Me remito a mi comentario anterior 🙂

**Comment by DarkWood97** [comment]
Despues de leerlo 100 veces en el dia, lo entendi, gracias!! Iba por buen camino

**Comment by gustofa** [comment]
Volví con otra pequeña cuestión respecto del system para ejecutar el script de transformación/reducción:
La forma de pasarle el flujo de entrada sería poniendo un "cat archivo_a_procesar.txt |" antes del script?
Se podría usar popen()?   o hay alguna contraindicación?

**Comment by tferraro** [comment]
Pueden usar cualquiera de las 2 formas, ambas son válidas.

**Comment by tferraro** [comment]
Todo bien con esto @gustofa ? Así le damos cierre al issue :slightly_smiling_face:

**Comment by gustofa** [comment]
Si, adelante. Gracias

**Comment by marrtins** [comment]
Buenas, @tferraro , viendo un poco el htop nos aparecio esto dps de los forks de transformacion y demas. Nosotros los terminamos con exit los procesos hijos, como nos dijiste aca arriba hace ya un tiempo.
Supongo que es esperable que estén ahi esos procesos que no consumen nada hasta que el padre (el worker original) muera, no?

![image](https://user-images.githubusercontent.com/18755426/33335894-279a485e-d44d-11e7-834d-642763b86685.png)

**Comment by tferraro** [comment]
Buenas!

Por lo general, cuando llamas exit así nomás, forzás el cierre y no deberías tener procesos zombies. Sin embargo, (fijate que ahí tienen la Z de zombie) esto probablemente se deba a que hay un exit-code seteado por el system().

Mi recomendación es, que usen el handler que `SIGCHLD` tiene para estos casos, que es  `SIG_IGN`. Si bien esto es medio overkill (porque hace que tu proceso no pase por el trabajo de dejar el valor de retorno en algún lado) para este caso particular les evitaría los zombies.

**Comment by marrtins** [comment]
Mmm, estuve luchando con eso y no funciono. 
Cuando pongo la linea signal(SIGCHLD, SIG_IGN); 
no entiendo porque pero todas las llamadas system q hago, ya sea para transformar reducir o mismo para darle permisos 777 a los scripts no me las permite y devuelve -1. Voy a tener que probar ocn otra cosa

**Comment by marrtins** [comment]
Edito, aparentemente poner ese handler, algo le hace al system ya que yo todas las veces que lo usaba lo igualaba a un entero que siempre daba 0 cuando todo iba bien. No entiendo porque da -1, pero las cosas igual las hace, asi que lo dejaré con ese handler y espero que el system nunca falle porque nunca me voy a enterar

**Comment by tferraro** [comment]
> Si bien esto es medio overkill (porque hace que tu proceso no pase por el trabajo de dejar el valor de retorno en algún lado)

Viste cuando dije antes que hace que no deje un valor de retorno? Bueno, _es por eso que devuelve -1_; de ahí que es bastante overkill esa solución, porque sirve, _pero se te disminuyen los chequeos_.

Podés asumir como bien decis, que system _no debiera fallar_. No hay (ni va a haber), scripts mal formados como para que falle como resultado esperado. Lo que si (y esto es porqué no sugerí esta solución al principio), asegurate que lo que se le esté pasando a `system()` sea correcto. En otras palabras, asegurate de probar bien el módulo del Worker que se encarga de ejecutar scripts, porque sin valor de retorno debuggear se complica.

Saludos!
Tom

**Comment by marrtins** [comment]
Uh, ahora eso nos dio otro problema.... Cuando matamos a un worker en el medio de alguna transformacion, lo veníamos haciendo con ctrl c. Lo que pasa ahora es que ahora al matar al padre con ctrl c, los scripts finalizan su ejecucion y devuelven -1... pero como ya no hay chequeo de errores, mandan que la transfo salio ok. Lo cual es un problema :( . 
El día de la entrega como se van a matar los procesos para ver como replanifica? por ahí mandandole otra señal para que finalice no permite a los procesos ni mandar que el resultado salió ok

**Comment by tferraro** [comment]
Mmmm, buen punto, no había pensado en esa opción. Probá sin cambiar el handler de SIGCHLD, dejandolo como viene default y haciendo `waitpid()` de los hijos, peeero, para que no se cuelgue en eso, acordate de usar el flag `WNOHANG` en las opciones.

Esta sería la solución más "linda" por así decirlo, porque además podes saber que paso en los hijos. El problema es que te agrega un poco de overhead en el proceso padre por tener que preguntar siempre, a pesar de que no haya hijos esperando. Si bien no se va a bloquear por ese flag, a veces es preferible no ir por este camino porque no nos importa el resultado que tengan y es más fácil y rápido (y especialmente violento, tirar un exit).

**Comment by marrtins** [comment]
Dejandolo como viene default significaría no agergar nada, no?

Ahora lo que probe es que lo hijos hagna exit y el padre 
waitpid(pidRedGl,&pidStat,0); y de esa forma desaparecen los zombies, peeeeeeero es bloqueante..

con waitpid(pidRedGl,&pidStat,WNOHANG); tambien está el problema de los zombies lo cual no entiendo porque esta pasando..

**Comment by tferraro** [comment]
Si justamente eso, no agregar nada.

Respecto a que sigue generando zombies, cuando lo hace? Tené en cuenta que si tu proceso se bloquea por un accept, no va a poder llamar a `waitpid()` hasta que llegue un nuevo connect.

**Comment by marrtins** [comment]
Claro, si o si tiene que ir con wnohang.. El tema es que cuando le ponemos esa flag misteriosamente los zombies siguen apareciendo no entiendo pqe...

Por otro lado, los zombies que molestan, no serían los que consumen recursos? estos no consumen nada

**Comment by DarkWood97** [comment]
Consumen el PID creo yo

**Comment by tferraro** [comment]
Vuelvo a abrir el issue, porque no es algo trivial ya 😛 

No hay _zombies que no molestan_. Siempre están consumiendo recursos. El htop no lo muestra porque muestra los recursos que tiene asignados, en vez de los recursos reales que ocupan. Cual es la definición de un proceso zombie?

@marrtins puede ser que con ese método tengas un par de zombies momentáneos, producto de eso que te dije antes. Chequea que sea eso, sino el problema no viene por este lado, algo le debés estar pifiando en otra parte del código

**Comment by marrtins** [comment]
Ya lo pudimos resolver todo el asunto nosotros, gracias !

**Comment by nicolasreyd** [comment]
Hola @marrtins , la solución era utilizar el waitpid(pid,&status,WNOHANG)?

gracias

**Comment by DarkWood97** [comment]
Esa seria la manera facil, sino podes hacer un manejador que los espere
