### ISSUE TITLE
Etapas del proceso Master

### ISSUE THREAD

**Issue by maacosta** [sisoputnfrba/foro#896]
Buenas!
Pongo primero en contexto. El proceso Master, cuando recibe la info de los bloques de Yama, se conecta a cada Worker enviando el programa transformador/reductor. Luego, envia el bloque a transformar/reducir segun la etapa. Y debe crear un hilo por cada bloque a transformar según el enunciado.
Pero, si hay dos bloques en el mismo nodo, ¿no podría usar el mismo hilo para conectar al Worker, enviar el programa y luego procesar secuencialmente los bloques?

**Comment by tferraro** [comment]
Buenas!

No. Primero que nada, por la palabra **secuenciar**. La parte copada de los trabajos paralelizables sobre gran cantidad de datos es, justamente, hacerlos de forma paralela.

Además, si lo haces como decis, no sentís que estarías agregando un caso **"si pasa eso, hago esto, sino hago lo otro**? Es algo común buscar una solución genérica, en vez de múltiples saltos en la línea de ejecución. Por eso la especificación del TP lo contempla, a pesar de que termine generando múltiples conexiones contra el mismo Nodo.

Saludos!

Tom

**Comment by maacosta** [comment]
Perfecto! Gracias!
