### ISSUE TITLE
[Planificación] Ayuda para entender el ejemplo del tp

### ISSUE THREAD

**Issue by FedericoVigi** [sisoputnfrba/foro#897]
Buenas, 
Estuvimos en la 3ra charla y no tuvimos mucho drama para seguir el ejemplo que [dieron](https://docs.google.com/presentation/d/1FLeG-s8XLx7LhVtOnQ6sdGgqBTTOTBtmEtnbyz93D-Q/edit#slide=id.g26c5617000_1_11).
Pero tenemos problemas para seguir el ejemplo del tp:

![image](https://user-images.githubusercontent.com/8700754/31570221-ff562976-b057-11e7-8082-1db4ef87d333.png)

Puntualmente el paso 3: Del ejemplo de las ppt (slides 15 y 16) y del enunciado, entendemos que no hay que permitir que al actualizar el puntero/clock éste caiga en un worker con disponibilidad 0, en ese caso hay que ir omitiendo los workers que tienen disponibilidad 0 y restaurarles la disponibilidad al valor base ( en la charla decían que pasarlo por alto era como una recompensa) hasta caer en un  worker con 
 disponibilidad > 0. 

> Si dicho clock fuera a ser asignado a un Worker cuyo nivel de disponibilidad fuera 0, se deberá restaurar la disponibilidad al valor de la disponibilidad base y luego, avanzar el clock al siguiente Worker, repitiendo el paso 2.

Pero en el paso 3 del ejemplo de más arriba se ve que actualizó la base pero no lo omitió, y como consecuencia en el paso siguiente se lo deja apuntado (haciendo que tenga más carga). No podemos encontrar la lógica de ese paso :-1:  

Por otro lado, es correcto decir que solamente se actualiza el clock cuando el bloque fue asignado al worker que apuntaba el mismo?

Gracias.

**Comment by juanlarosa96** [comment]
Hola! 
Esta consulta ya fue respondida en [este thread](https://github.com/sisoputnfrba/foro/issues/872). Fue un error de consigna... Ups. Te dejaría la imagen corregida, pero github no me estaría dejando, igual esta en el thread! 
Y respondiendo a la pregunta, si, el clock solo se modifica cuando se asigna el bloque al worker al que apuntaba (y se sigue avanzando hasta encontrar un worker con disponibilidad mayor a 0)

**Comment by FedericoVigi** [comment]
Disculpá, no estaría viendo en ese issue el ejemplo de lo que planteamos acá, si te referís a lo que corrigieron en la errata de posicionar el clock en el worker con mayor disponibilidad no mencioné eso en ningún momento. 
Por ahí no me explico bien:
![image](https://user-images.githubusercontent.com/8700754/31578211-ff867f4a-b0f2-11e7-9edc-1b07d82922f5.png) 

Llevar la cuenta de la disponibilidad de los workers no tiene mucho sentido si cuando estos quedan en 0 solo se las restauras y los seguís apuntando, o si? Disculpá si es medio obvia la respuesta, la verdad no la podemos deducir.

**Comment by juanlarosa96** [comment]
Si, te había entendido mal la primera vez, mala mia. Tenes razón, en ese caso habria que haber salteado el worker despues de restaurarle la disponibilidad, sino la disponibilidad no aportaría mucho. Se ve que es otra cosa que se nos pasó. El ejemplo de la 3ra charla esta correcto. Pueden guiarse con ese.

**Comment by FedericoVigi** [comment]
Ok, nos guiamos por el de la ppt. Gracias.
