### ISSUE TITLE
FS|filesystem Que se debe hacer al no poder guardar un archivo.

### ISSUE THREAD

**Issue by GauntStrelok** [sisoputnfrba/foro#898]
Cuando un archivo no puede ser guardado, que por ejemplo no entre la copia, o no entren algunos bloques que deberiamos hacer? 
Lo primero que se me ocurre es no guardarlo directamente y tirar algun error.(pregunte por mail y esta fue la respuesta que me dieron)
Tambien puede ser que se guarde hasta donde se pudo, o solamente guardar una copia del archivo.

**Comment by tferraro** [comment]
Buenas!

Andá por la que te contestaron por email. La otra opción tiene bastantes cosas en contra, se te ocurren cuales?

**Comment by tferraro** [comment]
@GauntStrelok up a esto. Como venís? Pudiste resolver la duda?

**Comment by GauntStrelok** [comment]
Si, ya esta resuelto, estaba viendo como solucionar el problema de grabarlo pero no grabarlo hasta que este terminado.

**Comment by tferraro** [comment]
Ok! Entonces plz cerralo 🙏

**Comment by tferraro** [comment]
Fue, lo cierro por acá. La próxima plz cerralo @GauntStrelok :policeman:
