### ISSUE TITLE
[Planificación] Carga de Trabajo Actual (WL(w)) vs. Cantidad de Tareas realizadas históricamente

### ISSUE THREAD

**Issue by juanmaconstenla** [sisoputnfrba/foro#899]
Buenas!

Tengo una duda con estos dos conceptos del algoritmo de balanceo de carga. Por un lado, en el paso 1 de las reglas de funcionamiento dice:

> Se posicionará el Clock en el Worker de mayor disponibilidad, desempatando por
> el primer worker que tenga menor cantidad de tareas realizadas históricamente.

La consulta sería: son dos valores distintos que tenemos que tener en cuenta para cada Worker, no? Por un lado la Carga de trabajo actual y por otro la de tareas realizadas históricamente?

Esto a su vez se relaciona con el último párrafo de la sección de Actualización de Carga de los Workers, que dice:

> Finalmente, luego de que se finalice un Job, se deberá reducir la WL(w) la cantidad de
> unidades que se sumaron, a fin de reducir la carga de trabajo del Worker.

Si restauramos el valor de WL(w), no tendríamos nunca un valor histórico, por eso creo que son dos valores distintos.

Y otro tema que también me estaba confundiendo es que en los ejemplos del enunciado, cuando tira un segundo y tercer job, está teniendo en cuenta valores de la WL(w) luego de aplicados los Jobs anteriores sobre el mismo archivo. Entonces, la reducción de la WL(w) en la cantidad de unidades que se sumaron cuándo se haría? Recién una vez finalizada la Reducción Global del Job y el Almacenamiento Final?

Gracias, saludos!

**Comment by juanlarosa96** [comment]
Hola!
1) Si! Son dos valores distintos. El WL(w) esta definido a partir de las tareas que se tengan que hacer en ese worker, mientras que las tareas historicas son simplemente un contador de las tareas que se fueron ejecutando en ese worker.
2) Ahí mismo en el texto que citaste dice "luego de que se finalice el Job". El Job se da por finalizado cuando termina todas sus etapas, así que sería cuando termine la etapa de Almacenamiento Final. Tené en cuenta que en los ejemplos del enunciado no toma los valores del WL _luego_ de aplicar los jobs anteriores. Toma los valores del WL que se obtienen cuando se crea el plan de ejecución del Job, asi que en el ejemplo del enunciado todos esos Jobs se estan ejecutando en simultaneo

**Comment by juanmaconstenla** [comment]
Hola @juanlarosa96, gracias por la respuesta!

1. Creo que me quedó claro. 
Entonces el WL(w) sería, además de para un Worker determinado, en un momento particular determinado. Y puede aumentar (por llegada de nuevos jobs con sus transformaciones y reducciones locales o por tener que asignarle una reducción global a un worker encargado para uno de los jobs que ya teníamos) y disminuir (porque ya realizamos la etapa de almacenamiento final, entonces la carga de trabajo que impuso ese Job para cada worker en las diferentes etapas se reduce).
En cambio, la cantidad de tareas que se realizaron históricamente siempre va a ir en aumento.

2. Me parece que te entendí. El ejemplo nada más está teniendo en cuenta el balanceo para la transformación y reducción local, pero no se realiza la reducción global y el almacenamiento final de esos jobs, por eso se mantienen las WL(w). Algo similar sucedería con el ejemplo de la PPT que usaron en la charla en la que explicaron este algoritmo.

Por las dudas te hago una última consulta, en referencia a lo último que dijiste, "todos esos Jobs se están ejecutando en simultáneo". Por más que esto sea así, y podamos tener en un mismo momento en el sistema varias instancias de Master ejecutando cada una su correspondiente Job, en un mismo momento sólo se va a estar balanceando la carga para un sólo Job en particular (independientemente de la etapa en la que se encuentre), no?

**Comment by juanlarosa96** [comment]
Con estar balanceando la carga a que te referís? Tene en cuenta que YAMA no usa hilos, así que no hace nada realmente en simultáneo. Balancear la carga en realidad sería crear el plan de ejecución del job. No se si te referis a esto con la pregunta, pero si es asi, seria más acertado decir que "en un mismo momento solo se va a estar creando un solo plan de ejecución de Job"

**Comment by juanmaconstenla** [comment]
Sí, estaba usando indistintamente balancear carga / crear plan de ejecución / preplanificar xD

Creo que ya me quedaron resueltas las consultas. Lo único que me había confundido un poco era lo de que en los ejemplos del enunciado todos los jobs se ejecutan en simultáneo.

Muchas gracias por las respuestas Juan, saludos!
