### ISSUE TITLE
Crear y destruir muchos configs usando la commons esta tirando seg. fault

### ISSUE THREAD

**Issue by Gruschka** [sisoputnfrba/foro#900]
Hola chicos!

Estoy trabajando con la parte de la tabla de archivos. Como las mismas son parecidas a un  archivo de config, lo estoy haciendo usando la biblioteca de config de la commons. En pseudocodigo mi algoritmo se ve asi:

```
while(1){
  config = config_create(path);
  usarconfig(config);
  config_destroy(config);
  path = siguientePath();
 }
```

El problema que estoy teniendo es que despues de la primer iteracion (y del primer config_destroy) me tira segmentation fault cuando quiero hacer el config_create. Si comento el config_destroy por alguna razon no tira seg fault.

Ademas cuando hago config_destroy se me rompen otras cosas como el logger (que tambien tira seg fault) por alguna razon.

**Comment by tferraro** [comment]
Buenas!

Guarda que el config_destroy() elimina el TAD de configuración y toda la
memoria donde almacena los valores. En otras palabras, si le pedis una key
que es un path, si lo destruis esa memoria pasa a ser liberada y no
podrías, en el mejor de los casos, referenciarla a pesar que te guardes el
puntero en otro lado.

Algo estás haciendo en siguientePath() que seguramente requiera alguna data
de configuración, de ahí que si se destruye, el config_create() fallaría.

Esto es meramente una especulación, te recomiendo que debuggees el codigo y
nos cuentes los valores de las variables a ver de donde viene el problema.
No tengo el link a mano aca pero buscate en el blog, en la sección de video
tutoriales y guías que hay algunas que te pueden servir😉.

Saludos!

Tom

>

**Comment by Gruschka** [comment]
@tferraro muchisimas gracias como siempre por tu respuesta!

Quiero grabar un video de todo el debuggeo asi te muestro bien los valores de cada variable (que parecieran estar bien). El tema es que esto lo estabamos programando en la compu de un compañero del grupo y cuando llego a mi casa se me rompio la VM que por alguna razon se quedo sin internet y me tira esto cuando quiero ver las opciones de red:

<img width="1919" alt="screen shot 2017-10-15 at 10 52 23" src="https://user-images.githubusercontent.com/11674324/31585390-f51fda34-b196-11e7-9986-9ad538cb9281.png">

Ya probe ponerlo de distintas formas, conectando la compu directamente a red, etc. No hay caso. Entonces no puedo pullear para mostrarte el debug.

No se si servira de algo mientras trato de arreglar esto para poder pullear y mostrarte el debug directamente pero esta es la funcion en cuestion (aparece con los + porque lo saque de Github - esta en [nuestro ultimo commit](https://github.com/sisoputnfrba/tp-2017-2c-Deus-Vult/commit/6a115b1c7923b89520dc14417bc8c8d6dd327d47#diff-9720e1988f63f9ffcf6d80c7a6ddeb67R417):

Basicamente esto lo que hace es ir leyendo de un archivo que genera el FS con todas las entradas de archivos del FS, genera un config del mismo y lo lee para saber si esta en nodo y el bloque. Disculpa que tire esto asi medio croto, voy a tratar de arreglar la VM cuanto antes y mostrar el debug directamente.
```
int fs_isStable() {
 +	FILE *fileListFileDescriptor = fopen(myFS.FSFileList,"r+");
 +	char buffer[255];
 +	memset(buffer,0,255);
 +	int size;
 +	int blockCount;
 +	int iterator;
 +	int copy;
 +	char * mountPathCopy = "/mnt/FS/";
 +	t_config *fileMetadata;
 +	while(fgets(buffer,255,fileListFileDescriptor)){
 +		if(buffer[strlen(buffer)-1] == '\n'){ //Para que no quede el \n en el nombre del archivo
 +			buffer[strlen(buffer)-1] = '\0';
 +		}
  
 +		char *fullFilePath = string_from_format("/mnt/FS/%s",buffer);
 +		fileMetadata = config_create(fullFilePath);
 +		char *sizeString = config_get_string_value(fileMetadata,"TAMANIO");
 +		size = atoi(sizeString);
 +
 +		blockCount = size / BLOCK_SIZE;
 +
 +		iterator = 0;
 +		copy = 0;
 +
 +		while(iterator < blockCount){
 +			char *blockToSearch = string_from_format("BLOQUE%dCOPIA%d", iterator,copy);
 +			char *nodeBlockTupleAsString = config_get_string_value(fileMetadata,blockToSearch);
 +			char **nodeBlockTupleAsArray = string_get_string_as_array(nodeBlockTupleAsString);
 +
 +			int blockNumber = atoi(nodeBlockTupleAsArray[1]);
 +
 +			//si tenes el nodo y el nodo tiene el bloque esta OK, sin importar si la data es valida
 +			if(!fs_checkNodeBlockTupleConsistency(nodeBlockTupleAsArray[0],blockNumber)){
 +				free(blockToSearch);
 +				free(nodeBlockTupleAsString);
 +				//free(nodeBlockTupleAsArray);
 +				iterator++;
 +				copy=0;
 +			}else{
 +				if(!copy){ //Flag para que si no encontro el primero que intente con la copia 
 +					copy = 1;
 +				}else{
 +					//no pudo armar el bloque
 +					log_debug(logger,"consistency error for file %s",buffer);
 +					log_debug(logger,"missing block no. %s",blockToSearch);
 +					config_destroy(fileMetadata);
 +					free(sizeString);
 +					//free(fullFilePath);
 +					return EXIT_FAILURE;
 +				}
 +			}
 +		}
 +		config_destroy(fileMetadata);
 +		free(sizeString);
 +		free(fullFilePath);
 +	}
 +
 +	fclose(fileListFileDescriptor);
 +
 +	return EXIT_SUCCESS;
  }
```

Mil gracias como siempre!

**Comment by varas-c** [comment]
Hola German, si no tenes red en la VM, configuralo desde VirtualBox. Con
Lubuntu apagado, en el menu principal de VirtualBox, en el listado
izquierdo donde aparecen las vms, a tu Lubuntu y seleccioná Settings.

Andá a la opcion Network y desde ahi lo podes configurar. Te dejo una
screenshot para que te guies un poco.


​

Otra cosa que podes hacer es (si tenés Windows) ir a Panel de Control y
buscar la parte donde te figuran los hardware de red. Hay un dispositivo de
red que tiene que decir algo de "VirtualBox". No recuerdo exáctamente donde
y que dice (No tengo windows ahora :( ), pero era por ahi. Si lo encontrás,
entonces tenes algun problema de configuracion con la VM. Si lo encontrás
por ningun lado el dispositivo, quiere decir que VirtualBox no te creó el
dispositivo de red para que puedas tener Internet en la VM. Si es asi,
desinstalá por completo Virtualbox e instalalo de nuevo

Si no lo encontrás o seguis teniendo problemas, avisanos!

2017-10-15 11:04 GMT-03:00 German Gruschka <notifications@github.com>:

**Comment by Gruschka** [comment]
Hola @varas-c , muchas gracias por la respuesta!

Sisi estuve cambiando la configuracion asi. Es re loco porque no hice nada con mi compu ya que trabajamos los dos en otra y sin embargo cuando llegue a la mia puff no andaba.

Ya lo pude arreglar... por alguna razon el adaptador USB a RJ45 que vengo usando desde el principio era el culpable. Cuando lo desconecte, arranco internet (y eso que probe con la configuracoin que tome solo wifi ignorando el puerto usb). Muchas gracias!

Resuelvo los conflictos y filmo el debug asi lo ven. 

Gracias de nuevo chicos!

**Comment by fedebonisconti** [comment]
@Gruschka probaste de usar [valgrind](https://faq.utnso.com/valgrind) para ver por qué es el segmentation fault?

**Comment by Gruschka** [comment]
Hola Chicos!

Gracias a todos por la mano!

Recien ahora pude ponerme. Me puse a debuggearlo poniendo watch expressions en todas las variables que creia podian llegar a tener problemas considerando lo que me comento @tferraro que si mal no entendi cuando elimino el config tambien estoy eliminando toda la informacion que saque del mismo.

Me _parece_ que el problema viene de una liberacion de memoria que estoy haciendo que estaria de mas. Yo tengo una variable que es 	
	
`char *sizeString = config_get_string_value(fileMetadata,"TAMANIO");
`

En esta foto pueden ver el estado de las variables antes del destroy:

<img width="2032" alt="before destroy" src="https://user-images.githubusercontent.com/11674324/31619640-89578984-b26b-11e7-931e-3af18b50e4b0.png">

Aca despues (sizeString parece liberarse o alterarse al menos):

<img width="2032" alt="after destroy" src="https://user-images.githubusercontent.com/11674324/31619652-91b1e9bc-b26b-11e7-826e-4bc8a0c84461.png">

Y despues yo estoy liberando sizeString y queda de esta manera (le agrega una V):

<img width="2032" alt="after free" src="https://user-images.githubusercontent.com/11674324/31619669-9a66c53c-b26b-11e7-8bf7-f0c38feed702.png">

Entonces lo que me parece que estaria pasando es que estoy intentando 'liberar memoria ya liberada'. Estoy en lo correcto o estoy flasheando? De buenas a primeras, saque el free de sizeString y no me tira mas segmentation fault.

Si esto es asi, estaria bien sacar como conclusion que todas las variables que yo saque con el config no hace falta liberarlas manualmente ya que todas vuelan con el destroy?

Muchisimas gracias de nuevo a todos!

German

**Comment by mgarciaisaia** [comment]
@Gruschka fijate que [la implementación de `config_destroy`](https://github.com/sisoputnfrba/so-commons-library/blob/1dd52d058e5c468f7dbe83ad8579a059d5c5ff38/src/commons/config.c#L103-L107) llama a `dictionary_destroy_and_destroy_element`, que efectivamente libera todos los elementos que haya reservado antes - así que, sí, no tenés que liberarlos vos.

Esto significa un par de cosas. Por un lado, que eso valores """no son tuyos""" - los crea una biblioteca externa, por lo que podría no ser tan pésima idea hacerte tu propia copia de esos elementos si quisieras desacoplarte del ciclo de vida de esa biblioteca. Probablemente no quieras comprarte ese problema para el TP, pero es una consideración de diseño a tener en cuenta.

Por otro lado, eso significa que los tests de la config son medio medio, porque no hablan de esto. Sos más que bienvenido a pensar/implementar algún test sobre esto y compartirlo.

Por último, que, de haber corrido tu código con `valgrind`, de toque hubieras visto que el programa seguía ejecutando sin romperse, pero con un error GIGANTE de "Invalid free" diciendo que el bloque ya había sido liberado antes. Nada, conocer las herramientas, usarlas para lo que corresponde :)

¡Un abrazo!

**Comment by Gruschka** [comment]
@mgarciaisaia muchas gracias!

Totalmente - me volvi loco dando vueltas por todos lados de forma completamente innecesaria si corria valgrind de primera, que va a ser lo primero que haga la proxima vez.

Muchisimas gracias como siempre por el tiempo de todos!

Cierro el issue ya que esto esta solucionado.

Abrazo!
