### ISSUE TITLE
Consulta sobre reducción local

### ISSUE THREAD

**Issue by mtimossi** [sisoputnfrba/foro#901]
El enunciado da a entender que cuando finalizan las tareas de transformación en un worker (para un job) comienza la etapa de reducción local en el mismo. O sea que mientras algunos workers están realizando tareas de transformación, otros pueden estar ejecutando tareas de reducción.

Supongamos que:

**Worker A:** Termino sus transformaciones y esta ejecutando la reducción local.
**Worker B:** Acaba de fallar una de sus transformaciones y hay que replanificar.

Yama replanifica y resulta que la copia de los bloques de B esta en A. Entonces, mediante master,  enviamos las nuevas tareas de transformación a  A. 

Worker A termina la reducción y realiza las nuevas transformaciones. **Luego tiene que efectuar otra reducción sobre lo reducido anteriormente + el resultado de las nuevas transformaciones de la replanificacion.** **Esto es correcto?**

Para nosotros seria muchísimo mas fácil esperar que todos los workers de un job terminen sus transformaciones antes de empezar cualquier reducción. **Estaría mal tomar este enfoque?**

**Comment by tferraro** [comment]
Buenas!

Es un caso bastante borde el que planteas, pero pensémoslo de forma paralelizable.

Cada flow de trabajo es independiente entre sí. De esta forma, te aseguras paralelismo posta posta. Veamos el caso un mismo nodo con 2 flows diferentes, porque el primero fue el que elegimos la primera vez y el otro fue una re-pre-planificación de otros bloques de otros nodos.
La reducción global sí espera a todos, a diferencia de la local, y es un cuello de botella, por lo que para hacerla necesitas que todos las tareas estén terminadas. 

Hasta antes de este punto, las tareas tienen que ser paralelizables. Entonces, las reducciones locales no tienen que esperar a que todo termine, porque perderíamos la paralelización de los datos. Pensá que la data pesada está en ese proceso, no en la **reducción global**, por eso el cuello de botella no nos afecta tanto.

Esto hace que tengas 2 posibles escenarios: **El que planteás**, como tengo una reducción ya hecha, puedo agarrar lo que escupió la transformación de la parte que se volvió a pre-planificar y unirlos y pasarlo de nuevo por una reducción, dado que sabemos que si el script sirve para una reducción global, sirve para esto.
La otra opción es **reducir los archivos transformados solos** y cuando haya que enviar los datos al Nodo Encargado, se envían los 2 juntos ordenados. Esta segunda tiene un nivel de complegidad capás un poquito mayor a la hora de enviar, pero menor a la hora de manejar los datos.

Ambos escenarios son válidos, dado que responden al mismo peso que es esperaría en la planificación y se estaría aprovechado el paralelismo :slightly_smiling_face: 

TL;DR: _No vale esperar a que terminen las transformaciones, hay que hacer las reducciones a demanda_, tal como dijimos en #874 , pero en este caso particular, eso de _esperar a que terminen todas las del nodo, se puede resolver con lo de arriba_. Si fuera el caso que todaviiiia no llegó a hacer una reducción, es válido meter todo en la misma bolsa de reducción, pero no hacer la reducción toda de nuevo si ya hay parte hecha.

Saludos!

Tom

**Comment by mtimossi** [comment]
Muchas gracias por la respuesta, ahí lo entendí bien!
