### ISSUE TITLE
Balanceo en Reducción Global

### ISSUE THREAD

**Issue by juanmaconstenla** [sisoputnfrba/foro#902]
Hola!

Otra duda sobre el Anexo II.
En la sección "Actualización de Carga de los Workers" dice:

> Además, se deberá sumar una cantidad igual a la mitad (redondeando hacia arriba) de la cantidad de archivos temporales a reducir, a la carga de trabajo Worker Encargado, a modo de denotar el diferente peso de las tareas a realizar entre los Workers en dicha etapa.

Es correcto tener en cuenta la cantidad de archivos temporales a reducir (luego de la reducción local) o hay un error en el enunciado y se referían a la cantidad de bloques (que sería la misma cantidad de archivos temporales luego de la transformación y previo a la reducción local)? Porque si tenemos en cuenta la cantidad de archivos temporales luego de la reducción local, será uno por cada Worker implicado. En cambio, teniendo en cuenta la cantidad de archivos temporales luego de la transformación, será uno por cada bloque (lo que tiene más sentido y por lo que veo en la PPT del Anexo es lo que se hacía).

Saludos!

**Comment by tferraro** [comment]
Buenas!

Hace referencia a la reducción global, dado que se está hablando sobre la cantidad que se va a sumar por esa etapa.

La PPT tenía un typo, ahí la corregí, guiate por el enunciado en esta. (Contamos la cantidad de archivos temporales y nos colgamos en sacar la mitad😛 )

Saludos!

Tom

**Comment by juanmaconstenla** [comment]
Hola Tomás, cómo va?

Claro, entonces tenemos en cuenta la mitad de la cantidad de archivos temporales generados en la reducción local.
Me había confundido porque la PPT tenía en cuenta los bloques (que sería la misma cantidad que los archivos temporales generados en la transformación, si no me equivoco) y le sumaba al WL del tercer Worker la mitad de eso.

Gracias por la respuesta, saludos!

**Comment by tferraro** [comment]
Cierro el issue, para la próxima @juanmaconstenla cerralo vos :policeman: jaja

**Comment by fmc21** [comment]
Buenas!
por lo que dijeron en la charla la carga que se le debe sumar al encargado de la Reducción Global es la cantidad de transformaciones / 2. Es más, lo aclara en la formula que indica la cantidad total de carga de un job:

![imagen](https://user-images.githubusercontent.com/26329474/31805276-e08405b2-b535-11e7-94f2-6124d4d4e8bc.png)

Como en el ejemplo eran 6 transformaciones (o bloques, o archivos temporales de transformacion), la carga que se le sumaba era 3, y quedaba con un total de 5.
Me lo dejé anotado específicamente durante la charla ya que en el enunciado no aclaraba sobre qué archivos temporales se refería.

**Comment by tferraro** [comment]
Vieron cuando uno dice ganzadas, porque el enunciado está redactado de una forma y uno, a las apuradas, lee otra? Bueno algo así.

Pegándole una revisada más profunda al enunciado, el mismo dice lo siguiente:
> (...)se deberá sumar una cantidad igual a la mitad (redondeando hacia arriba) de la cantidad de archivos temporales a reducir(...)

La frase clave es: _cantidad de archivos temporales a **reducir**_. Por como viene la frase (y si lo lees a las apuradas como yo hace un par de días) da a entender que habla de la reducción global.

Sin embargo, y en esto te pido mil disculpas @juanmaconstenla (voy a terminar debiendo facturas por esto) pero el enunciado está hablando de **reducción** de forma general, contemplando el proceso completo. Esto implica hace referencia, de una forma y otra, **a la cantidad de archivos temporales que generaron las transformaciones** (osea, la cantidad de bloques que se usaron, a fin de cuentas).

Nada, eso. Mil gracias a @fmc21 por haberme hecho mirar esto con la cabeza más fria y disculpen el bardo :/

Tom
