### ISSUE TITLE
Valores de disponibilidad en preplanificacion

### ISSUE THREAD

**Issue by alabarque** [sisoputnfrba/foro#903]
Buenas!
Tengo una pregunta respecto a algo que surgio en #899 y me parecio conveniente escribirlo en un nuevo issue. Cito algo que me llamo la atencion de dicho issue:
> toma valores del WL luego de aplicarlos jobs anteriores.
Como se evalua la disponibilidad de cada worker en el siguiente job, asumiendo que el siguiente es w-clock?

Invento un ejemplo:
Supongamos que preplanificamos un job para 3 bloques, hay 3 nodos y el valor base es 2. Los nodos A, B y C tendrian los bloques (0,2 ; 0,1 ; 1,2) respectivamente y la disponibilidad de cada nodo es de 2.

Entonces la preplanifacion daria algo asi:
> bloque0, workerA, disp restante 1
> bloque1, workerB, disp restante 1
> bloque2, workerC, disp restante 1

Hasta aca todo bien, pero si el siguiente job a preplanificar se lo pide con el algoritmo w-clock para los mismos nodos, que valor obtendriamos para las disponibilidades?
Entre opciones que se me ocurren serian:
a) la disponibilidad que ya tenia cada bloque, es decir: 1 para cada bloque.
b) utilizar la disponibilidad de cada bloque y sumarle el PWL, es decir: 1 + WLmax - WL(w) = 1 + 3 - 1
c) utilizar la funcion tal cual como esta en el enunciado, es decir: base + WLmax - WL(w) = 2 + 3 -1

Y tengo una pregunta mas, dado que en ese issue se menciono que los ejemplos de preplanificacion del enunciado se ejecutan en simultaneo, ¿esto tambien puede ocurrir en el tp?

Muchas gracias.

**Comment by juanlarosa96** [comment]
Buenas!
La respuesta es la c... ish. En el ejemplo del anexo de algoritmos de Planificación se muestra lo que estas planteando. Lo que se hace es base + WLmax + WL(w). Tu base es 2. El WL(w) es 1 en todos tus workers en este caso. Pero el WLmax es la mayor carga de trabajo que haya en un solo worker. Aca todos los workers tienen una carga de 1, porque tienen un solo bloque a transformar cada uno. Así que el WLmax sería 1. Si uno de esos workers tuviese dos bloques a transformar, la WLmax sería 2 porque ese es el WL máximo.
Respect a lo otro, en el otro thread aclare que el proceso yama, al no usar hilos, no hace nada realmente en simultáneo. Pueden llegarle peticiones de inicio de jobs al mismo tiempo, pero la creación de la preplanificacion para cada job se hace de manera secuencial

**Comment by alabarque** [comment]
Gracias juan! Me aclaraste las dudas. 
Cierro el issue.
