### ISSUE TITLE
Comando md5 y archivos en YAMAfs

### ISSUE THREAD

**Issue by CarolinaPonceRodriguez** [sisoputnfrba/foro#904]
Buenas, consulto lo siguiente en base al comando md5:
-Para obtener el md5 de un archivo que este "almacenado" en YAMAfs lo que deberia hacer es buscar los bloques correspondientes en los nodos que esten involucrados. Ahora lo que entiendo es que la idea del fs distribuido es justamente tener la informacion de un archivo en los distintos nodos, y para poder obtener el md5 del archivo, no me quedaria otra que tener el archivo en mi local, es cierto? 
Doy el ejemplo del tp, tengo la metadata del archivo en metadata/archivos/5/ejemplo.csv por lo cual tendria que buscar los bloques correspondientes, "guardar el archivo fisico" en mi local en /user/juan/datos/ejemplo.csv y de ahi recien el md5.

Saludos.

**Comment by iago64** [comment]
buenas buenas!

Para hacer el MD5 tenes al menos 2 formas, la primera, mas fácil y _que recomiendo que hagan_ seria como decís, obtener todos los bloques. armar el archivo en fisico y tirar un system para ejecutar el MD5.

La otra que **no recomiendo bajo ningun concepto** pero por si alguien busca seguro la encuentra es meterse en el quilombo del include de openssl.

Saludos.-

**Comment by CarolinaPonceRodriguez** [comment]
Perfecto, y ya que me tiro por la opcion de armar el archivo fisico luego de obtener el resultado del MD5 seria lo correcto eliminarlo? Porque en principio, la creacion del mismo es para obtener el MD5 y mantenerlo en mi FileSystem seria un desproposito ya que la idea es que la informacion persista en los nodos y eventualmente "me la traiga" para operar.

Saludos.

**Comment by tferraro** [comment]
🙂 #893

**Comment by CarolinaPonceRodriguez** [comment]
"y cuando termines lo eliminas :) " mas claro, echale agua!
Gracias, cierro!!
