### ISSUE TITLE
Manejo archivos de Texto y Binarios en Fs

### ISSUE THREAD

**Issue by CarolinaPonceRodriguez** [sisoputnfrba/foro#905]
Buenas, si bien ya resolvi el tema me surgio una duda y quiero asegurarme de no estar manqueandola feo.
En el caso de que el FS recibe por parte del worker los datos para guardar esto lo defini como un char * , es decir, ahi tengo la informacion para dividir en bloques/registros. Como cada char es un byte, si yo hago un strlen del contenido de ese char * me da el largo en bytes por lo cual la cadena "hola" son 4 bytes.
Se me ocurrio para el caso de los archivos binarios usar la funcion string_substring() que de la manera en que la uso me permite obtener los registros que conforman ese char * .
Para el caso del archivo binario, toca buscar el salto de linea.

La consulta es: es correcto el manejo que estoy haciendo? Para el caso de los archivos binarios me confunde un poco ya que estoy manejando bytes como cadenas, no se si sea del todo correcto o si hay otra manera sea usando algun memcpy().

Saludos.

**Comment by tferraro** [comment]
Buenas!

No estoy entendiendo la pregunta. Porqué buscarías el salto de línea para el archivo binario? En que caso particular de trabajo sobre un archivo del yamafs se centra tu pregunta?

Saludos!

Tom

PD: ` char es un byte` tomalo con pinzas, depende de la arquitectura.

**Comment by CarolinaPonceRodriguez** [comment]
Mala mia, lo que quise decir en pocas palabras es que de parte del worker me llegan los datos a guardar en un char * y ese mismo lo usaria tanto para archivos binarios como archivos de texto.

Si no puedo asegurar que un char es un byte, de que manera me convendria obtener cuantos bytes tiene ese char * ? Un strlen() no seria confiable.

Saludos.

**Comment by varas-c** [comment]
Como dijo Tomas, el tamaño de un char depende de la arquitectura. Con este
tp no vas a tener problemas porque todas las vms son iguales, en las cuales
1 char = 1 byte, asi que longitud de la cadena = peso de la cadena (guarda
con el \n final, fijate bien que hace strlen)

Si realmente no sabes cuanto pesa 1 char, la forma "correcta" de
averiguarlo sería preguntarle al sistema cuánto pesa 1 char.

Si vos queres saber cuanto pesa 1 tipo de dato, lo podes obtener de alguna
forma con una funcion no?

Asi que tu cuenta queda reducida a: Tamaño de un char por longitud de la
cadena.

Si no se entendió, preguntá de nuevo sin drama :)

**Comment by CarolinaPonceRodriguez** [comment]
> "Si vos queres saber cuanto pesa 1 tipo de dato, lo podes obtener de alguna
forma con una funcion no?"
Si, haciendo el sizeof(char);

Por lo cual entiendo que puedo hacer uso de las funciones de cadenas para hacer el recuento de bytes y dividir registros en el caso del tipo binario y separar en lineas segun \n para el archivo de texto 
Gracias! Cierro.

**Comment by tferraro** [comment]
Aprovecho a hacer una aclaración a esto:
> PD: char es un byte tomalo con pinzas, depende de la arquitectura.

Que quedó medio colgado y es algo bastante loco.

En la mayoría de las arquitecturas, 1b char == 1b, tanto para x86 como para x64, porque el tamaño del char es siempre "1 byte" por especificación de C, pero el tema es: es 1 byte 8 bits? En el 90% de los casos, cualquiera me diría _que flasheas?_, pero hay algunas implementaciones en los que no. Si, posta, no lo es, porque la implementación original de 1 byte es "el tamaño de un char", y en algunos casos el tamaño del char era de 9bits o de menos de 8 (casi no existen esas arquitecturas, pero no quiero que esto quede perdido).

En lo que hay que prestar atención es en los que terminan cayendo en `int` `long` y `pointer`. Tanto `char` como `short` no tienen dramas en cambiazos x64 vs x86.

_Nota para mi_: Hacer un Medium sobre esto así lo referencio :stuck_out_tongue:
