### ISSUE TITLE
Comando cpfrom YAMAfs

### ISSUE THREAD

**Issue by CarolinaPonceRodriguez** [sisoputnfrba/foro#906]
Buenas, quiza la respuesta  es obvia pero consulto por las dudas:
Esta funcion es simplemente una "invocacion" de la operacion  Almacenar archivo o tambien incluye el guardado del archivo en el YAMAfs? 
En el caso de la operacion almacenar archivo lo unico que se hace es guardar los datos recibidos en los datanodes que se encuentren conectados.

Saludos.

**Comment by tferraro** [comment]
Buenas!

La interfaz que estás mencionando es solo válida para nodos, guarda con eso. Mira lo que dice el enunciado:
> (...)Contará con una interfaz detallada contra los Nodos(...)

Ahora, si internamente terminan llamando a una función que reusas para ambos casos, allá ustedes :stuck_out_tongue:

**Comment by CarolinaPonceRodriguez** [comment]
No lo comprendo del todo, dice  que "seguira los lineamientos de la operacion Almacenar Archivo" y la misma lo que hace es guardar lo que reciba en los nodos conectados.
No se supone que cpfrom hara "lo mismo" pero en vez de recibir los datos del worker los lee de un archivo almacenado localmente? 

Saludos.

**Comment by tferraro** [comment]
Lo que estás citando hace referencia a lo de **partir el archivo en bloques** y la explicación sobre que hay que tener en cuenta.

De todas formas, no estás errada, justamente a lo que me refería: _Si ambos puntos de entrada (la consola y la interfaz para los nodos) de una forma o de otra terminan llamando a una función_ que parta las cosas en bloques, mande la info a los Nodos y actualice las estructuras, es su implementación y cumple con lo que dice el enunciado :smirk:

**Comment by CarolinaPonceRodriguez** [comment]
Perfecto, muchas gracias! Cierro.
