### ISSUE TITLE
YAMA - Borrado de bloques

### ISSUE THREAD

**Issue by guillermo126** [sisoputnfrba/foro#907]
Buenas ¿como andan?

Les queria hacer una consulta que sobre el borrado de bloques, que maneja el FS. que se pueden borrar por el comando rm de la consola del FS en tiempos de ejecucion.
¿como deberia proceder yama cuando se borra algun bloque?  deberia procesar los bloques que quedan del archivo?  o como el archivo no esta completo no procesar nada e informar un error?

**Comment by tferraro** [comment]
Buenas!

En el próximo Job que vaya a pre-planificarse, debería tomar en cuenta el
cambio. Si ya hay un job pre-planificado sigue igual.

Cabe la posibilidad de la ‘corrupción’ del job si se crea un nuevo archivo
y se pisa el espacio del bloque con un nuevo contenido. Pero es tan border
que no lo consideren, no va a pasar.

Saludos!

Tom

**Comment by guillermo126** [comment]
perfecto muchas gracias!
