### ISSUE TITLE
YAMA Planificacion - Dudas varias

### ISSUE THREAD

**Issue by dromero-7854** [sisoputnfrba/foro#908]
Buenas nuevamente,

Estoy analizando el algoritmo de planificación y me surgieron las siguientes dudas:

- Para el algoritmo WClock, se modifica el calculo para obtener la disponibilidad: 
A(w) = Base + [WLmax - WL(w)]
WLmax: la mayor carga de trabajo existente entre todos Workers 
WL(w): la carga de trabajo actual del Worker

Estoy viendo el ejemplo de WClock del tp y **no entiendo como se obtienen esos valores**
![image](https://user-images.githubusercontent.com/12041032/31833185-3721dcea-b5a0-11e7-92ac-e5ee1b440d62.png)

- Estaba viendo el issue #897, y lo que entendí es que si dicho clock fuera a ser asignado a un Worker cuyo nivel de disponibilidad fuera 0, se deberá restaurar la disponibilidad al valor de la disponibilidad base y luego, avanzar el clock al siguiente Worker, repitiendo el paso 2.

Ahora en otro punto del Tp se aclara:

> Si se volviera a caer en el Worker apuntado por el clock por no existir disponibilidad en los Workers (es decir, da una vuelta completa a los Workers), se deberá sumar al valor de disponibilidad de todos los workers el valor de la Disponibilidad Base configurado al inicio de la pre-planificación.

**Esto ultimo ¿tiene sentido si se aplica lo primero?** (restaurar la disponibilidad al valor de la disponibilidad base y luego, avanzar el clock al siguiente Worker, repitiendo el paso 2)

Desde ya muchas gracias
Saludos!
Dante

**Comment by tferraro** [comment]
Buenas!

El caso aclarado al final es un sub-caso del primero, en el que se cumple esa condición en particular. Eso implica que, como ya sumaste la Disp. Base a los que estaban en 0, tendrías que sumarla al resto de los que no estaban en 0 y permitieron que dieras la vuelta, como para cumplir el caso de la última condición.

Sacando eso de lado, que parte no entendés de como se calculan los A(w)? El caso que estás planteando es el de la 2da iteración con wClock, con lo cual: ¿Qué valores de carga tienen cada nodo?

**Comment by dromero-7854** [comment]
Como estas?

Acabo de leer mejor el algoritmo. Y ya tengo una primera versión. Entendí mejor como se calcula A(w)

Igualmente me sigue generando ruido el punto del Tp:

> Si se volviera a caer en el Worker apuntado por el clock por no existir disponibilidad en los Workers (es decir, da una vuelta completa a los Workers), se deberá sumar al valor de disponibilidad de todos los workers el valor de la Disponibilidad Base configurado al inicio de la pre-planificación.

Es decir, si el worker apuntado por clock, contiene el bloque que necesito, pero su disponibilidad es igual a 0, debo restaurar su disponibilidad al valor de la disponibilidad base, y luego avanzar el clock al siguiente Worker, siguiendo la busqueda de un worker que tenga dicho bloque y disp > 0. 

Eso fue lo que entendi de los issues y el enunciado.

Ahora... si restauro al momento de encontrar el worker con el bloque con disp = 0 ¿Se daria el caso de dar una vuelta completa por no existir disponibilidad en los Workers?

Me parece mejor ir a consultar a Medrano con un ayudante mejor, viendo codigo. Es complicado explicarlo jeje

Saludos!!

**Comment by dromero-7854** [comment]
@tferraro ¿Que días proximos estarias en Medrano - Campus? Me gustaría mucho despejarme las dudas del algoritmo personalmente. Es muy dificil hacerlo por este medio.

Te lo agradecería un monton.

Saludos
Dante Romero

**Comment by tferraro** [comment]
Buenas!

Hoy, mañana y el viernes me encontrás a la noche en Medrano. Sino sábado a la mañana (también en Medrano). No te ofresco juntarnos en otro horario, porque ando medio complicado, pero te puedo ofrecer ver si algún ayudante está disponible 🙂

**Comment by dromero-7854** [comment]
Dale, esta noche voy para allá... ¿Vas a estar en el laboratorio?

**Comment by dromero-7854** [comment]
Después de lo explicado cierro el issue,  gracias!
