### ISSUE TITLE
Problema para mapear un array de struct con mmap

### ISSUE THREAD

**Issue by matifalcone** [sisoputnfrba/foro#909]
Buenas,

Estoy teniendo un problema a la hora de mapear el archivo de directorios. Lo que yo quiero hacer es mapear la siguiente estructura que tengo en memoria:

`struct t_directory arrayDirectorios[100];`

Lo que a mi me gustaria hacer sería algo asi:

`arrayDirectorios =  mmap(0, sizeof(t_directory) * 100, PROT_WRITE, MAP_SHARED, fd, 0);`

De esta manera se me simplificaría acceder a cada uno de los directorios para poder actualizar directamente en memoria y que se consista en el archivo automaticamente.

Se que tengo que castear la función `mmap `pero probé de mil maneras y no me estoy dando cuenta qué estoy haciendo mal. 

¿Me podrían ayudar?

Saludos y gracias,

Matías

**Comment by iago64** [comment]
Matias, que tal?

Vos el array de directorios lo estas definiendo como una variable de estack y mmap te devuelve un puntero, lo que eventualmente podrias hacer seria declarar tu arrayDirectorios como un puntero al struct t_directory y despues vos ya sabes por enunciado que tenes maximo 100 directorios, con lo cual podrias simplemente recorrerlo con un for  un while.

Saludos.-

**Comment by matifalcone** [comment]
Damián, ¿cómo va?

Bien, creo que ya estoy un poco más encaminado. Aloqué memoria para 100 directorios en arrayDirectorios y casteé la salida de mmap a (struct t_directory*). Luego recorrí arrayDirectorios 100 veces y actualicé lo que necesitaba. Ahora, quiero que se refleje en el área mapeada y no lo estoy consiguiendo. Lo que tengo sería lo siguiente:

`arrayDirectorios = malloc(sizeof(struct t_directory) * cantidadDirectorios);
struct t_directory* mapeo =  (struct t_directory*) mmap(0, sizeof(struct t_directory) * cantidadDirectorios, PROT_READ | PROT_WRITE, MAP_SHARED, (int)tablaDirectorios, 0);
memcpy(mapeo, arrayDirectorios, sizeof(struct t_directory) * cantidadDirectorios);`

Me está dando Segmentation Fault en el memcpy (¿tenés idea qué está mal?). Por otro lado, ¿es correcto hacer memcpy o se puede trabajar directamente en el área mapeada?

Saludos y gracias por la respuesta!

**Comment by iago64** [comment]
Matias, que tal?

Una pregunta rapida, el archivo, ya esta con el tamaño correspondiente? porque si es un archivo vacio me da que sospechar que eso es lo que hace que te rompa el mmap.

Por otra parte, para trabajar con el área mapeada podrias simplemente hacerlo de la siguiente manera:

`#define MAXDIR 100`
`struct t_directory* mapeo = (struct t_directory*) mmap(0, sizeof(struct t_directory) * cantidadDirectorios, PROT_READ | PROT_WRITE, MAP_SHARED, (int)tablaDirectorios, 0);`

Y después para recorrerlo podes usar un pequeño "hack" (también conocido como interpretar la memoria de otra forma) y en lugarde de tomar el puntero como un puntero, lo interpretas como un array de t_directory
`for (int i = 0; i < MAXDIR; i++) { //y aca haces lo que necesites }`

Saludos.-

**Comment by matifalcone** [comment]
Damián,

Sí, el archivo lo creé con "truncate" y es de 10 MB. Eso lo comprobé. El mmap no me rompe, lo que me rompe es lo que hago después. 

Hoy cuando llego a casa lo pruebo, pero al parecer no estaría haciendo nada extraño y lo que pensé es bastante parecido a lo que me planteas.

Después te aviso cómo me fue.

Saludos y gracias de nuevo,

Matías

**Comment by matifalcone** [comment]
Damián,

Volví al principio. Pude recorrer sin problemas el array pero sigo sin poder escribir el área mapeada. Obtengo un error en la siguiente línea, al finalizar la actualización de todos los datos del array y querer copiarlos en el retorno de `mmap`:

`memcpy(mapeo, arrayDirectorios, sizeof(struct t_directory) * cantidadDirectorios);`

El error que obtengo es:

`SIGBUS: Bus Error`

Metiéndome un poco más, no es que no puedo escribir en `mapeo`, directamente no puedo acceder. Veo que lo que me devuelve `mmap` es válido (es distinto de `MAP_FAILED`) pero cuando miro la dirección de memoria con el debugger de Eclipse, veo esto:

`Failed to execute MI command:
-data-evaluate-expression (mapeo)->index
Error message from debugger back end:
No se puede acceder a la memoria en la dirección 0xb7fce000`

Probé también trabajando directamente sobre el retorno de`mmap` pero me pasa lo mismo: sigo sin poder acceder a ése puntero. 

¿Tendrás idea de qué puede ser?

Saludos y gracias,

Matías

**Comment by iago64** [comment]
Me llama la atencion ese error, nunca lo habia visto, hice un ejemplo rapido y me esta funcionando correctamente:
`int fdDirectorios = open("/home/iago64/workspace/c/Data/directorios.bin",  O_RDWR);`
`t_directory* tablaDirectorios = (t_directory*)mmap((caddr_t)0, 10485760, PROT_READ | PROT_WRITE, MAP_SHARED, fdDirectorios, (off_t) 0);`

y sobre ese espacio de direcciones puedo trabajar sin problema de hecho no necesito modificar nada ni hacer memcpy, de todas formas probe el memcpy y no tuve problemas.

Saludos.-

**Comment by tferraro** [comment]
Buenas!

Si revisás [la doc de mmap](http://pubs.opengroup.org/onlinepubs/009695399/functions/mmap.html) dice lo siguiente:

> The mmap() function can be used to map a region of memory that is larger than the current size of the object. Memory access within the mapping but beyond the current end of the underlying objects may result in SIGBUS signals being sent to the process. The reason for this is that the size of the object can be manipulated by other processes and can change at any moment. The implementation should tell the application that a memory reference is outside the object where this can be detected; otherwise, written data may be lost and read data may not reflect actual data in the object.
Note that references beyond the end of the object do not extend the object as the new end cannot be determined precisely by most virtual memory hardware. Instead, the size can be directly manipulated by ftruncate().

De acá se puede extraer que posiblemente estés mapeando más memoria que el tamaño del archivo, y cuando estés haciendo `memcpy` estás pisando memoria que es más grande que el tamaño actual del archivo.

Fijate que onda y contanos

**Comment by matifalcone** [comment]
Tomás, ¿cómo estás?

Efectivamente, el problema venía por ese lado. Me enrosqué tanto con `mmap` que me olvidé del pequeño detalle de asignarle espacio al archivo que estoy mapeando...

En fin, ¡muchas gracias a ambos!

Saludos,

Matías
