### ISSUE TITLE
Pregunta sobre data.bin en testing de entrega final

### ISSUE THREAD

**Issue by CDNievas** [sisoputnfrba/foro#910]
Hola, hice esta pregunta en el checkpoint ayer y me dijeron que cree un issue acá.

Quisiera saber como es que se va a hacer el deploy de los data.bin en el testing el día de la entrega final.

Se van a crear los data.bin vacíos o nos los van a dar cargados y el datanode/filesystem tienen que ser responsables de reconocerlos. Y si el segundo caso es el correcto, saber si nos van a dar los respectivos bitarrays o los tenemos que crear nosotros recorriendo el data.bin para reconocer bloques llenos y vacíos.

Muchas gracias

**Comment by tferraro** [comment]
Buenas!

Por defecto, vacíos.

Como un extremo, se podrían llegar a van a generar algunos data.bin con una configuración del FS a levantar con el modelado por defecto que indica el TP.
Todo esto con la posibilidad de alterar la data de las estructuras para matchearlas al modelo que hayan finalmente implementado en su trabajo práctico, ya que los expuestos por el enunciado son ejemplos, pero puede llegar a haber más campos que ustedes hayan agregado por la implementación que hicieron.

Saludos!

**Comment by CDNievas** [comment]
> Buenas! 
> Por defecto, vacíos.
> Como un extremo, se podrían llegar a van a generar algunos data.bin con una configuración del FS a 
> levantar con el modelado por defecto que indica el TP.
> Todo esto con la posibilidad de alterar la data de las estructuras para matchearlas al modelo que
> hayan finalmente implementado en su trabajo práctico, ya que los expuestos por el enunciado son
> ejemplos, pero puede llegar a haber más campos que ustedes hayan agregado por la implementación
> que hicieron.
> Saludos!

Discúlpame pero no entendí muy bien lo que quisiste poner, me quede solo con la parte de por defecto vacíos no mas jajajaja

**Comment by tferraro** [comment]
Quise decir que o como regla general los crea el FS desde limpio; y como mucho para una prueba en particular, de adaptarán los que se van a proveer para que puedan funcionar en su FS. Pero si les proveemos los data.bin, también las estructuras administrativas del FS.

**Comment by CDNievas** [comment]
Listo muchas gracias
