### ISSUE TITLE
Desconexión Nodo - Implicancias en YAMA y FS

### ISSUE THREAD

**Issue by dromero-7854** [sisoputnfrba/foro#911]
Buenas, estoy trabajando en YAMA y FS,  y el tema de desconexiones de Nodos me hace mucho ruido.

- ¿Como sabe YAMA que un Nodo se desconectó? YAMA recibe toda la información de FS con respecto a los Nodos, no sabe el estado de los Nodos. La única idea que se me ocurre es que MASTER, al mandar el resultado de transformación de un bloque, mande específicamente el error NODO_DESCONECTADO

- ¿Como influye la desconexión de un Nodo en FS? Al levantar el FS, el mismo se encuentra en estado **no-estable**. No permite que se conecte YAMA. A medida que se conectan los NODOS, pasa a un **estado estable**, y permite la conexión de YAMA. Si un NODO se desconecta, puedo volver a un estado no-estable ¿no? ¿Qué hago en ese caso?

**Comment by tferraro** [comment]
Buenas!

* Si YAMA planifica cada vez que se lo piden, tendría alguna forma de obtener todos los nodos que están UP dentro de los que tiene que trabajar?

> Si un NODO se desconecta, puedo volver a un estado no-estable ¿no? ¿Qué hago en ese caso?

No. El estado no-estable es un estado inicial para armar la base del FS o reconstruirlo. Si se le van Nodos al FS y un archivo queda inaccesible 🤷‍♂️, fallarán las peticiones sobre el mismo hasta que los Nodos se vuelvan a levantar; pero el resto del sistema tiene que seguir andando.

**Comment by dromero-7854** [comment]
gracias!!! Cierro el issue... Saludos!
