### ISSUE TITLE
Error que muestra Valgrind sobre string_new() de las "Commons"

### ISSUE THREAD

**Issue by AlexFalconR** [sisoputnfrba/foro#912]
Buenas,
Estoy teniendo problemas de memoria con una funcion, por ende decidí correr Valgrind. El error que marca, es que estoy escribiendo en un espacio de memoria que no debería. Este error lo muestra sobre una linea que ejecuta la función string_new() de la librería "Commons". No entiendo si tengo roto el Valgrind, si estoy haciendo algo mal de código, si están mal las "Commons" o si simplemente es algo normal.
Adjunto capturas de pantalla del código y de Valgrind.

Código:
![codigo](https://user-images.githubusercontent.com/11712503/31905080-5fa0d256-b803-11e7-88b6-648d9256e62b.jpg)

Valgrind:
![valgrind](https://user-images.githubusercontent.com/11712503/31905117-7e3203b6-b803-11e7-9f42-c8ec5debdc24.jpg)

**Comment by tferraro** [comment]
https://faq.utnso.com/valgrind `or didn't happen` 😛 

PD: Guarda que `string_new()`, como dice la doc: _Crea un string vacío_.  Volver a asignar otro valor al mismo puntero hace que pierdas la referencia a la memoria que el `string_new()` te devuelve. _Esto es mucho muy importante_

**Comment by tferraro** [comment]
@AlexFalconR que tul? Pudiste interpretar lo que decía valgrind? Con eso, que conclusiones sacaste?

**Comment by CarolinaPonceRodriguez** [comment]
Buenas, tengo una consulta con respecto a lo comentado ya que es algo que aplico bastante en mi codigo, doy el siguiente ejemplo:
For(){
Cadena = string_new();
/*
Mas codigo
*/
Free(cadena);
}

Con esto me estaria asegurando que cada vez que aloco lo libero, es correcto el planteo? 
Gracias

**Comment by varas-c** [comment]
Si no haces ningún otro string_new sobre Cadena, está bien lo que planteas,
alocas memoria y la liberás cuando ya no la necesitás.

El problema se daría en éste caso:

char* cadena;
cadena =  string_new()
//Codigo y blabla
cadena = string_new()
//mas codigo
free(cadena)

Llegás a ver "por qué" hay un problema?

2017-10-26 9:51 GMT-03:00 Carolina Ponce Rodriguez <notifications@github.com

**Comment by tferraro** [comment]
@CarolinaPonceRodriguez te sirvió la respuesta de Chris?

**Comment by CarolinaPonceRodriguez** [comment]
Si, @varas-c  ya referencia al espacio de memoria ocupado por la primer cadena quedo perdida en el eter, solamente estaria liberando el segundo.
@tferraro  Sirvio la respuesta, gracias!

**Comment by tferraro** [comment]
Bárbaro, cierro esto asumiendo que se resolvió tambien el problema de @AlexFalconR . Cualquier cosa volvelo a abrir!
