### ISSUE TITLE
Duda con comando cpblock [path_archivo] [nro_bloque] [id_nodo]

### ISSUE THREAD

**Issue by CarolinaPonceRodriguez** [sisoputnfrba/foro#913]
Buenas que tal, la duda o confirmacion mas bien, es que este comando permitiria crear mas bloques en distintos nodos para un determinado bloque de archivo,  por lo cual, podria llegar a tenes 2+ n instancias de un bloque, es asi? 
Supongo que lo que corresponde seria agregarlo a la tabla de archivos correspondiente tambien.

Saludos!.

**Comment by tferraro** [comment]
Buenas!

La especificación del TP nunca elimina la posibilidad de tener N instancias de bloque, aunque en los casos prácticos habla de 2 por un tema de simplicidad. Pero si, también tendría que tener su entrada en la tabla de archivos.

Como les aclaré a unos chicos el sábado, si lo tiene, genial, es lo _deseable_, pero tampoco es un tema grave el no soportar 2+. Primero obtengan un TP funcional y luego agreguenle esa feature si lo diseñaron de una forma que no lo soporte.

De todas formas, el propósito de la función es poder volver a un estado de 2 copias, si eliminás/se cae un nodo.

Saludos!

**Comment by CarolinaPonceRodriguez** [comment]
Perfecto, gracias! Cierro.

**Comment by CarolinaPonceRodriguez** [comment]
Buenas reabro por lo siguiente: 
"Primero obtengan un TP funcional y luego agreguenle esa feature si lo diseñaron de una forma que no lo soporte."
Necesito con certeza saber que el hecho de no implementar la opcion de 2+ n no implicaria no aprobar el tp. En el punto actual, agregar ese feature implicaria un refactor importante en cuanto a la estructura del FS y a la comunicacion con YAMA lo que este ultimo recibe por parte del FS.
Si no es condicion necesaria, por como van los tiempos, prefiero inclinarme por la opcion de unicamente soportar 2 instancias de bloque.

Saludos.

**Comment by epreyes** [comment]
Entiendo que este comando permite crear la copia de un bloque en caso de que no lo tenga (porque se borro con rm). Yo iria por quedar en 2 instancias del bloque como maximo.

**Comment by tferraro** [comment]
> Como les aclaré a unos chicos el sábado, si lo tiene, genial, es lo deseable, pero tampoco es un tema grave el no soportar 2+.

**Comment by CarolinaPonceRodriguez** [comment]
Perfecto, 
Me quedo con eso entonces.
Saludos, cierro.
