### ISSUE TITLE
[Persistencia] Tabla de directorios y bitmaps

### ISSUE THREAD

**Issue by DanielMarcelletti** [sisoputnfrba/foro#914]
Buenas !

Queríamos consultarles como interpretar los distintos archivos de persistencia:
A) Para el de directorios:
> La tabla de directorios debe ser almacenada en un archivo en el filesystem local (no yamafs) denominado metadata/directorios.dat como un array de 100 posiciones de t_directory struct .
> struct t_directory {
> int index,
> char nombre[255],
> int padre
> }

La consulta es, ¿cómo diferenciamos, de los 100 elementos, cúales son útiles y cúales son basura?
Ya que no necesariamente tenemos las 100 entradas utilizadas, nosotros utilizamos un valor negativo en el  padre: queremos saber cómo interpretar el archivo que nos den ustedes para las pruebas, ya que el enunciado dice que se persisten 100 elementos, pero no dice cómo diferenciarlos.

B) Para los bitmaps

> Por cada DataNode del Filesystem se deberá almacenar un bitmap indicando el estado (libre/ocupado) de cada bloque. Esta información se deberá persistir en metadata/bitmaps/[nombre-de-nodo].dat. Ejemplo: metadata/bitmaps/nodo2.dat

Cuando creamos un bitmap, usamos MSB. Queríamos saber si van a usar MSB o LSB en los archivos de bitmaps que nos den en las pruebas para no tener errores.

Gracias !

**Comment by tferraro** [comment]
Buenas!

Es indistinto, depende de como quiera implementarlo ustedes. Como dije por aca https://github.com/sisoputnfrba/foro/issues/910#issuecomment-339081557, como mucho se adaptarán los archivos de las pruebas para que matcheen.

**Comment by tferraro** [comment]
@DanielMarcelletti up a esto. Te sirvió mi respuesta?

**Comment by FedericoVigi** [comment]
Hola! @tferraro soy del mismo grupo que Daniel; entonces con bitmaps usamos cualquiera de los 2 y después se adaptaran los archivos de prueba que nos den ustedes. 
Con el array de directorios pueden hacer lo mismo?

**Comment by tferraro** [comment]
![image](https://user-images.githubusercontent.com/7110539/32134259-dae71bcc-bbbf-11e7-9db2-f1fde9779c71.png)

**Comment by DanielMarcelletti** [comment]
Listo entonces, gracias por las respuestas !
