### ISSUE TITLE
YAMA - Planificación - posicionamiento inicial del puntero

### ISSUE THREAD

**Issue by guillelle** [sisoputnfrba/foro#915]
Hola,

el anexo del algoritmo de planificación especifica que al inicio el puntero se debe colocar en el worker con mayor disponibilidad y también especifica cómo desempatar, lo que no me queda claro es si el resto de los workers (nodos) se ordenan de mayor a menor disponibilidad o no afecta demasiado

copio el extracto del TP: 
"Se posicionará el Clock en el Worker de mayor disponibilidad, desempatando por el primer worker que tenga menor cantidad de tareas realizadas históricamente."

saludos

**Comment by tferraro** [comment]
Buenas!

Planificá pensando que los Nodos van a estar en orden natural (Nodo1, Nodo2, Nodo5, Nodo17,...NodoX)

**Comment by tferraro** [comment]
@guillelle up a esto! Como venimos? Se entendió mi respuesta? :slightly_smiling_face:

**Comment by tferraro** [comment]
Cierro esto por inactividad. Cualquier cosa, volverlo a abrir sin drama!

**Comment by guillelle** [comment]
perdón, colgué en responder. Lo que hice fue ordenar los nodos de mayor a menor disponibilidad y asegurarme así empezar por el de mayor disponibilidad.
gracias
