### ISSUE TITLE
Dudas comando cat()

### ISSUE THREAD

**Issue by CarolinaPonceRodriguez** [sisoputnfrba/foro#916]
Buenas, doy como ejemplo este comando pero tambien podria aplicar para otros del listado. Para este mismo yo considere el unico caso en el que se le pase por parametro un archivo que se encuentre en el FS, es decir, valido que tenga archivo su archivo de metadata y a partir de ahi busco sus bloques correspondientes. 
La duda viene por el lado de si es posible que yo le pase a este comando una ruta que sea la ruta del archivo de metadata, supongamos el ejemplo del tp:  metadata/archivos/5/ejemplo.csv
No se si considerar esta ultima opcion desde el comando cat() ya que el comando info() haria por su descripcion un cat de ese archivo.

Por otro lado, ahora que lo pienso, los directorios y archivos que forman parte de las estructuras administrativas debieran ser invisibles para estos comandos y unicamente verse modificados si se modifican los archivos que estos mismos contienen, por ejemplo si hago un rm, mv o o rename.

Saludos.

**Comment by nicozar95** [comment]
Buenas

Tal cual como vos decis, los archivos metadata deberian ser invisibles para estos comandos, entonces deberias usar los comandos cat, rm, info, etc con los paths del yamafs

**Comment by CarolinaPonceRodriguez** [comment]
Gracias, cierro!
