### ISSUE TITLE
¿Como mostrar la tabla de estados de YAMA para controlar el resultado de las ejecuciones?

### ISSUE THREAD

**Issue by dromero-7854** [sisoputnfrba/foro#918]
Hola, 

Quería saber si para mostrar la tabla de estados de YAMA, se podría crear una mini consola, solo para mostrar por pantalla el resultado de las ejecuciones en cada etapa.

¿Que otras opciones podría considerar?

Gracias!

**Comment by tferraro** [comment]
Buenas!

La recomendación es siempre: _Chequiá si te es cómodo para saber en todo momento en que estado está el sistema. Si algo no podes inferir o saber con los logs, es porque algo te falta_

Si querés crear una consolita para mostrar con algún comando rápido el estado de la tabla, además de ir mostrando las acciones/logs que va haciendo YAMA, bienvenido sea. Cuanto el TP más expreviso, mejor. Tanto para que ustedes lo puedan debuggear, como para darnos herramientas para testearlos.

**Comment by lianndt** [comment]
Buenas! 
Yo por el momento estoy mostrando la tabla con un simple printf en formato de columnas para verlo mejor, siempre que se termina la pre-planificacion de algun job y distribuyo los bloques, en ese momento muestro la tabla. Ahora en la entrega del tp, seria logico mostrar la tabla siempre en ese momento? Pregunto mas que nada para saber cual va a ser el metodo de ustedes para testear

Gracias!

**Comment by varas-c** [comment]
No hay *tanto* problema en "cómo lo muestres". Lo importantes es "que lo
muestres". Como dice Tom, siempre que puedan informar X estado del sistema
es bueno, nos permite a la hora de evaluar ver mejor el estado del sistema
y "qué es lo que está haciendo por atrás". Además les sirve a ustedes para
ver como anda su tp mientras lo desarrollan.

Lo que sí, traten de hacer que estos "informes" sean "fáciles" de ver. Si
ustedes imprimen por pantalla una tabla enorme una vez por segundo, para
nosotros es bastante incómodo porque no se puede ver bien, la pantalla va
"volando" digamos y se complica evaluar. Lo mejor sería loguearlo en un
archivo (ya que hay unas buenas funciones en las commons para eso). Ojo,
aclaro que no es motivo de desaprobación que el logueo por pantalla "vaya
muy rápido", pero como dije arriba, es incómodo para evaluar y además no
les sirve mucho a ustedes para ver el estado de su sistema.

Un tip que te va a servir, en vez de imprimir por pantalla para poder ver
los logueos "en tiempo real", pueden usar el comando "tail -f" de Linux.
Por ejemplo, podrías loguear en un archivo la tabla de estados de Yama,
supongamos en el archivo "tablaEstados.txt" y desde otra consola abrir el
archivo haciendo "tail -f tablaEstados.txt"

El comando tail te muestra las 10 últimas lineas de un archivo (creo que
hay un flag para decirle que te muestre más lineas pero no me lo acuerdo
ahora) y el "-f" (menos efe) hace que, cuando edites el archivo
tablaEstado.txt desde algún otro lado, el comando se de cuenta que hubo una
modificación sobre ese archivo y automaticamente te va a imprimir por
pantalla el archivo actualizado sin necesidad de volver a abrirlo.

Prácticamente con ésto emulás lo vos querés hacer, lo de crear una nueva
consola que imprima por pantalla en tiempo real.

Probalo y si tenés alguna duda, pasate por acá de nuevo que estamos para
ayudarte.

Saludos! :D



2017-10-26 10:44 GMT-03:00 lianndt <notifications@github.com>:

**Comment by dromero-7854** [comment]
Buenisimo, gracias por los comentarios. Voy analizando entonces como armarlo.

Cierro el issue. Saludos!
