### ISSUE TITLE
SegFault with string.

### ISSUE THREAD

**Issue by FedericoJoel** [sisoputnfrba/foro#919]
Hola,como estan?

Estoy armando una funcion para cortar strings y estoy teniendo un segmentation fault.
La idea es que le mande un mensaje un array de string por referencia, corte el string en pedasos y me devuelva el array de string con los pedasos y un int con la cantidad de bloques del array
Ya probe varias formas y no logro que funcione por completo.

asi es como llamo a la funcion
```
int cant_bloques = size_in_bloks("hola1");  // esto se fija en cuantos bloques va a entrar(devuelve 2).
char** bloques[2];
int cantidad = cortar_datos("hola1",&bloques);
```
y esta es la funcion.
```
int cortar_datos(char* mensaje,char*** bloques) {
   int i=0;
   size_t mensaje_size = strlen(mensaje);
   char** bloques_array = *bloques;
   char* head = string_substring(mensaje, 0, bloque_size);
   bloques_array[i] = string_from_format(head); // aca rompe
   char* body = string_substring(mensaje, bloque_size, mensaje_size-bloque_size);
}
```

Bueno, el codigo sigue con un while que va cortando los body hasta que quedan todos ubicados en el array de string.

Me podran pegar una mano, no se que probar ya

Abrazo.

**Comment by juanlarosa96** [comment]
Hola!
Me parece que hay un lio de punteros aca.
> char** bloques[2]; 
int cantidad = cortar_datos("hola1",&bloques);

Por un lado tenes un vector de char** de tamaño 2. Por lo que entendí que intentas hacer, queres que la funcion corte el string en bloques, asi que lo que querrias es una lista de strings. Si un string es un char *, una lista de strings seria un char * vector[]. O mismo seria un char**. Un char ** vector[] (que seria ya un char***) es una lista de listas de strings y entiendo que no es eso lo que queres.
Por otro lado, vos le pasas a la funcion como parametro &bloques. bloques en tu definicion es un char** bloques[2]. La expresion "bloques" asi a secas, es el mismo puntero que devolveria &bloques[0], pero la expresion "&bloques" es el puntero de algo que es un char** vector[] (o un char***), asi que &bloques seria un char****. Por ese lado ahi estaria mal definido el parametro de tu funcion y eso te podria estar tirando el error, pero por lo que entiendo esto no es lo que estarias buscando. Con solo un char** te alcanzaria

**Comment by FedericoJoel** [comment]
solucionado!! Era char*bloques[2] la definicion y la funcion recibe char**

Abrazo gracias por la ayuda
