### ISSUE TITLE
No anda el link a proceso FileSystem en el gitbook

### ISSUE THREAD

**Issue by GauntStrelok** [sisoputnfrba/foro#920]
Solo lo del titulo.

**Comment by tferraro** [comment]
![image](https://user-images.githubusercontent.com/7110539/32056371-dd2d3226-ba3a-11e7-8f55-5da14d41c5b8.png)

Me remito a los hechos :stuck_out_tongue:

**Comment by GauntStrelok** [comment]
fine, cuando cree el issue no andaba jajajaa, buenisimo :P

**Comment by tferraro** [comment]
Juro que no levanté la página después el comentario. Tanto poder no tengo 🙂
