### ISSUE TITLE
YAMA - WClock - ¿Aumentar Carga de nodo al iniciar etapa de Reducción Local?

### ISSUE THREAD

**Issue by dromero-7854** [sisoputnfrba/foro#921]
Buenas,

Les dejo otra consulta con respecto al algoritmo de planificación:

> **Actualización de la Carga de los Workers**
> Tras haber finalizado la creación del plan de ejecución, es necesario que YAMA actualice la carga de trabajo Worker (WL(w)), importantes para la ejecución del algoritmo W-Clock, siendo una unidad por cada Bloque sobre el cual ejecutar una transformación + reducción local.

Consulta 1:
Esta parte no me queda clara. Lo que entiendo hasta el momento es que a la carga del nodo, le tengo que aumentar una cantidad igual a número de transformaciones que se hagan en el mismo.
Ahora bien, cuando inicio la etapa de reducción local en el nodo: ¿Aumento la carga en uno (1)? ¿O dejo el valor como está? 

Consulta 2:
La reducción de la carga de un nodo, ¿Se hace al finalizar un JOB? reduciendo todos los valores que fueron agregados ¿O se puede ir reduciendo la carga de un nodo a medida que me llegan los resultados de cada etapa por parte de Master?

Saludos!!

**Comment by tferraro** [comment]
Buenas!

Estas fueron 2 cosas que no llegué a terminar de hacerte cerrar el otro día :smile: . La reducción local no agrega 1 a la carga, tal como dice el estracto del enunciado que citas. Para lo segundo: https://github.com/sisoputnfrba/foro/issues/874#issuecomment-332348989

**Comment by tferraro** [comment]
Buenass!

@dromero-7854 que onda con esto? Te cerró la idea?

**Comment by dromero-7854** [comment]
Todo claro... gracias de nuevo! Cierro el issue...
