### ISSUE TITLE
Consultas de enunciado -- Replanificacion y Tabla de Estados

### ISSUE THREAD

**Issue by marrtins** [sisoputnfrba/foro#922]
Buenas, hoy mientras avanzaba me surgieron 2 dudas...

En primer lugar, con el tema de la replanificacion. Llegado el caso que yo replanifique la transformacion, (osea solo tenga 1 nodo para elegir) al asignarle la tarea a dicho worker ¿tengo que actualizar cargas-disponibilidades-clock-etc y todo lo relacionado con la planificacion? Por el momento consideré que no era necesario, ya que si o si tengo que asignarselo y solo le sume +1 a la lista de cargas historicas que se usa para desempatar..

Por otra parte, viendo la tabla de estados me surgio la duda de como completarla en caso de ser una reduccion..
Por el momento estoy con la reduccion local, tendría que aparecer solo 1 _fila_ para mostrar la reduccion de cada nodo, ¿no? 
(es decir enun job en el que participaron 3 nodos, hay 3 filas de reducción local asociadas a dicho job)
Osea, en ese caso, con que valor completo el campo **BLOQUE** de la tabla que hay en el enunciado e imagino tengo que mostrarla en pantalla tal cual ya que la reduccion local se trataría de todos los bloques en los que ese nodo transformó. 

--adjunto la tabla--

![image](https://user-images.githubusercontent.com/18755426/32072302-7867fe7e-ba68-11e7-9088-0fb31a154f89.png)

Muchas gracias, martín

**Comment by lianndt** [comment]
Hola,adhiero consulta.
El campo bloque no tiene sentido en ninguna de las dos reducciones , porque justamente no estas trabajando a nivel de bloque. Deberia aparecer en blanco?

gracias!

**Comment by tferraro** [comment]
Buenas!

> En primer lugar, con el tema de la replanificacion. Llegado el caso que yo replanifique la transformacion, (osea solo tenga 1 nodo para elegir) al asignarle la tarea a dicho worker ¿tengo que actualizar cargas-disponibilidades-clock-etc y todo lo relacionado con la planificacion? Por el momento consideré que no era necesario, ya que si o si tengo que asignarselo y solo le sume +1 a la lista de cargas historicas que se usa para desempatar..

Si, deberías tomar en cuenta cuales son las cargas actuales de los Nodos y aumentar en función de la asignación. Recordá tenér en cuenta la Reducción Global al momento de re-planificar porque pueden haber cambiado los tantos y la reducción global podría quedarte en un Nodo que está caído, por ejemplo.

Para el caso del campo **BLOQUE**, debería mostrar los bloques sobre los cuales se trabajó. Si bien trabaja a nivel "archivo temporal de transformación", YAMA debería mostrar o los mismos en ese campo, o los bloques involucrados. En el ejemplo del enunciado, toma la segunda opción como ejemplo y trabaja sobre una única transformación.

Saludos!

Tom

**Comment by marrtins** [comment]
Ok. entiendo, gracias!
