### ISSUE TITLE
Error librería GNU

### ISSUE THREAD

**Issue by AlexFalconR** [sisoputnfrba/foro#923]
Estimados, por inconvenientes estoy intentando levantar el proyecto (versión que actualmente compila, que se encuentra en git) en una nueva VM. Al intentar compilar el proyecto me dice que no existen las siguiente dependencias:

error include
![error include](https://user-images.githubusercontent.com/11712503/32082151-fdbcf81e-ba8f-11e7-83c0-a32bd4c597ad.png)

error properties
![error properties](https://user-images.githubusercontent.com/11712503/32082153-033ee202-ba90-11e7-8a88-b928f7046d47.png)

Espero su respuesta.
Saludos

**Comment by farellano91** [comment]
Hola!
Instalaste la librería readline? En caso de que sí, podés probar dándole un update al index del proyecto para actualizar las dependencias; a veces eso arregla ese tipo de problemas.

**Comment by varas-c** [comment]
Hola!
Probá como dijo Fernando arriba 👆 y cualquier cosa pasate de nuevo

**Comment by AlexFalconR** [comment]
Buenas, hoy antes de hacer el update hice un rebuild dentro del proyecto y esto hizo que funcione.. Muchas gracias.
Saudos
