### ISSUE TITLE
[Worker] Problema con system

### ISSUE THREAD

**Issue by ltrinidad** [sisoputnfrba/foro#926]
Buenas ! Estoy teniendo un problema bizarro con la ejecución de system en el worker... La cosa es que si se le conecta un solo hilo de master (una sola transformación) la hace completa sin drama... Ahora, con 2 o mas hilos flashea : una transformación la hace completa y system retorna 0, pero con la o las otras system retorna -1 ... lo extraño es que aunque retorna -1 esa transformación la esta haciendo perfecto (en este log no se va a ver bien porque el nombre del temporal donde guarda el resultado es el mismo para las dos transformaciones, pero había probado mandarle nombres diferentes y andaba bárbaro)... hace dos días que le estoy dando vueltas a esto, seguro es una pavada... 

Este seria el código de la transformación que ejecutan los procesos hijos: 
``` c
int realizar_transformacion(t_datos_transformacion datos_transformacion, t_script script_transformacion){

	void* bloque = leer_bloque(datos_transformacion.numero_bloque, datos_transformacion.ocupado_del_bloque);

	if(bloque == NULL){
		log_error(log_worker, "No se pudo leer el bloque (numero %d) completo segun el tamanio especificado (%d bytes)",
							  datos_transformacion.numero_bloque, datos_transformacion.ocupado_del_bloque);
		return -1;
	}

        ((char*)bloque)[datos_transformacion.ocupado_del_bloque] = '\0';

	int resultado = ejecutar_comando_transformacion(bloque, script_transformacion, datos_transformacion.ruta_archivo_temporal);

	free(bloque);

	if(resultado < 0){ // segun man system retorna -1 si salio mal la ejecucion, y retorna cero si el comando es nulo (cosa que creo que no pasa).
		log_error(log_worker, "No se pudo transformar y ordenar el bloque solicitado. System devolvio %d", resultado);
		return -1;
	}

	log_trace(log_worker, "Se pudo transformar y ordenar correctamente el bloque solicitado. System devolvio %d", resultado);

	return 0;

}

int ejecutar_comando_transformacion(void* bloque, t_script script_transformacion, char* ruta_archivo_temporal){

	char* comando_ejecucion = string_new();

	string_append_with_format(&comando_ejecucion, "echo %s | ./%s | sort > %s",
							  bloque, script_transformacion.ruta, ruta_archivo_temporal);

	log_trace(log_worker, "el comando a ejecutar es %s", comando_ejecucion);

	int resultado = system(comando_ejecucion);

	free(comando_ejecucion);

	return resultado;

}
```
Va el log: 
```
[TRACE] 15:59:10:797 Worker/(7764:7764): Se agrego el cliente 6
[TRACE] 15:59:10:797 Worker/(7764:7764): Agrege al cliente conectado al socket 6 a la lista de clientes sin identificar
[TRACE] 15:59:10:798 Worker/(7764:7764): Se agrego el cliente 7
[TRACE] 15:59:10:798 Worker/(7764:7764): Agrege al cliente conectado al socket 7 a la lista de clientes sin identificar
[TRACE] 15:59:10:808 Worker/(7764:7764): Un master se conecto correctamente, y ya fue notificado de la conexion.
[TRACE] 15:59:10:813 Worker/(7764:7764): Un master se conecto correctamente, y ya fue notificado de la conexion.
[TRACE] 15:59:10:814 Worker/(7764:7768): El pedido del cliente 6 esta siendo atendido
[TRACE] 15:59:10:818 Worker/(7764:7769): El pedido del cliente 7 esta siendo atendido
[TRACE] 15:59:10:961 Worker/(7764:7769): Se construyo el script de transformacion de nombre: deWXKB, en el directorio ../temp/scripts_transformacion/, para atender el pedido del cliente 7
[TRACE] 15:59:10:961 Worker/(7764:7769): el comando a ejecutar es echo Lorem ipsum dolor sit amet, consectetur  | ./../temp/scripts_transformacion/deWXKB | sort > ../temp/bloques_transformados/b1
[TRACE] 15:59:10:975 Worker/(7764:7768): Se construyo el script de transformacion de nombre: Ru0SMB, en el directorio ../temp/scripts_transformacion/, para atender el pedido del cliente 6
[TRACE] 15:59:10:978 Worker/(7764:7768): el comando a ejecutar es echo Lorem ipsum dolor sit amet, consectetur  | ./../temp/scripts_transformacion/Ru0SMB | sort > ../temp/bloques_transformados/b1
[TRACE] 15:59:11:241 Worker/(7764:7768): Se pudo transformar y ordenar correctamente el bloque solicitado. System devolvio 0
[TRACE] 15:59:11:244 Worker/(7764:7768): Se desconecto el cliente 6 y el mismo fue notificado.
[ERROR] 15:59:11:280 Worker/(7764:7769): No se pudo transformar y ordenar el bloque solicitado. System devolvio -1
[ERROR] 15:59:11:280 Worker/(7764:7769): Fallo la transformacion de datos iniciada por el cliente 7, se aborto la etapa
[TRACE] 15:59:11:288 Worker/(7764:7769): Se desconecto el cliente 7 y el mismo fue notificado.

```
Ayudaaa! ...

**Comment by tferraro** [comment]
Buenas!

Primero que nada `((char*)bloque)[datos_transformacion.ocupado_del_bloque] = '\0';` Guarda con esto, estás escribiendo en el super malloc. Si llega a estar ocupando 1MB completo, podrías estar pisando el principio del bloque siguiente.

Volviendo al tema, fijate que en la doc de `system()`, dice:
> If a child process could not be created, or its status could not be retrieved, the return value is -1.

Tus scripts de prueba, están devolviendo un valor de retorno?

**Comment by ltrinidad** [comment]
Gracias por responder Tomás ! 

Sobre el tema del bloque: creo que lo solucione, agregue esa linea adentro de *leer_bloque* y al malloc le sume un uno. 

```c
char* leer_bloque(int numero_bloque, int ocupado_bloque){

	void* bloque = malloc(ocupado_bloque + 1);

	if(numero_bloque == 0){
		fseek(data_bin, 0, SEEK_SET);
	} else if(numero_bloque > 0){
		fseek(data_bin, (numero_bloque-1)* TAMANIO_BLOQUE_DATABIN, SEEK_SET);
	} else return NULL;

	int cant_leida = fread(bloque, 1, ocupado_bloque, data_bin);

	if(cant_leida != ocupado_bloque){
		return NULL;
	}

	((char*)bloque)[ocupado_bloque] = '\0';

	return bloque;
}
```

Por otro lado, el script que estoy usando para probar es el que esta en el [repo de nicozar](https://github.com/nicozar95/ejemplo_correr-script_so/blob/441439816983aca5f63b3f3235e062cef1039ac6/script_transformacion.py#L1-L18), y para contestar concretamente tu pregunta lo que hice para poder fijarme el valor de retorno de la ejecución del script fue alterar la linea que arma el comando por la siguiente : 

```c 
string_append_with_format(&comando_ejecucion, "echo %s | ./%s && echo $?",
						bloque, script_transformacion.ruta);
```
Porque supuestamente echo $? muestra el código de retorno del ultimo proceso ejecutado... y la salida es: 

```
[TRACE] 16:20:12:648 Worker/(3698:3698): Se agrego el cliente 6
[TRACE] 16:20:12:649 Worker/(3698:3698): Agrege al cliente conectado al socket 6 a la lista de clientes sin identificar
[TRACE] 16:20:12:654 Worker/(3698:3698): Se agrego el cliente 7
[TRACE] 16:20:12:654 Worker/(3698:3698): Agrege al cliente conectado al socket 7 a la lista de clientes sin identificar
[TRACE] 16:20:12:659 Worker/(3698:3698): Un master se conecto correctamente, y ya fue notificado de la conexion.
[TRACE] 16:20:12:661 Worker/(3698:3698): Un master se conecto correctamente, y ya fue notificado de la conexion.
[TRACE] 16:20:12:662 Worker/(3698:3702): El pedido del cliente 6 esta siendo atendido
[TRACE] 16:20:12:669 Worker/(3698:3703): El pedido del cliente 7 esta siendo atendido
[TRACE] 16:20:12:748 Worker/(3698:3702): Se construyo el script de transformacion de nombre: Fb4CrR, en el directorio ../temp/scripts_transformacion/, para atender el pedido del cliente 6
[TRACE] 16:20:12:749 Worker/(3698:3702): el comando a ejecutar es echo Lorem ipsum dolor sit amet, consectetur  | ./../temp/scripts_transformacion/Fb4CrR && echo $?
[TRACE] 16:20:12:811 Worker/(3698:3703): Se construyo el script de transformacion de nombre: aOChtP, en el directorio ../temp/scripts_transformacion/, para atender el pedido del cliente 7
[TRACE] 16:20:12:819 Worker/(3698:3703): el comando a ejecutar es echo Lorem ipsum dolor sit amet, consectetur  | ./../temp/scripts_transformacion/aOChtP && echo $?
lorem 1
ipsum 1
dolor 1
sit 1
amet 1
consectetur 1
lorem 1
ipsum 1
dolor 1
sit 1
amet 1
consectetur 1
0
[ERROR] 16:20:13:12 Worker/(3698:3703): No se pudo transformar y ordenar el bloque solicitado. System devolvio -1
[ERROR] 16:20:13:12 Worker/(3698:3703): Fallo la transformacion de datos iniciada por el cliente 7, se aborto la etapa
[TRACE] 16:20:13:17 Worker/(3698:3703): Se desconecto el cliente 7 y el mismo fue notificado.
0
[TRACE] 16:20:13:24 Worker/(3698:3702): Se pudo transformar y ordenar correctamente el bloque solicitado. System devolvio 0
[TRACE] 16:20:13:28 Worker/(3698:3702): Se desconecto el cliente 6 y el mismo fue notificado.

```

Si no entiendo mal , lo que vos sugerís es que system no esta "agarrando" el valor de retorno de los procesos hijos (que según se ve en el log es 0 para ambos casos).... si es ese el problema entonces :
¿Como lo puedo solucionar?  
¿Por que la primera vez si anda y el resto no? 
😱

**Comment by tferraro** [comment]
Ok! Entonces devuelve 0.

Fijate el resultado de evaluar WEXITSTATUS(status) para ver exactamente
porque rompe.

**Comment by ltrinidad** [comment]
Ok, estoy haciendo : 
```c
int resultado = system(comando_ejecucion);

int status;

wait(&status);

if(WIFEXITED(status)){
	log_trace(log_worker, "El exit status del comando fue %d", WEXITSTATUS(status));
}else{
	log_trace(log_worker, "Se ve que system no termino normalmente... el codigo de resultado fue: %d", resultado);
}

```
Y pasa casi lo mismo, la primera transformación que ejecuta el worker me muestra : 
```
[TRACE] 11:51:57:39 Worker/(7428:7433): El exit status del comando fue 150
```
Varia entre un montón de números que segun [esto](http://tldp.org/LDP/abs/html/exitcodes.html) no tienen ningún significado particular, a veces tira 86, 214, 182...
Y de la segunda a la enésima transformación se va por el lado del else y me dice que el resultado fue -1, y ahi supuestamente por lo que lei de `man wait` ya no puedo consultar WEXITSTATUS(status) porque WIFEXITED(status) dio falso... 
>*WIFEXITED(status)*
>**returns true if the child terminated normally**, that is, by calling exit(3) or _exit(2), or by returning from main().
>*WEXITSTATUS(status)*
>returns the exit status of the child. This consists of the least significant 8 bits of the status argument that the child specified in a call to exit(3) or _exit(2) or as the argument for a return statement in main(). **This macro should only be employed if WIFEXITED returned true.**

Igualmente probé y lo sustituí por esto : 
```c
int resultado = system(comando_ejecucion);

int status;

wait(&status);

log_trace(log_worker, "El exit status del comando fue %d\n", WEXITSTATUS(status));

```
Y ahora en todas las transformaciones desde que levanto el worker devuelve lo mismo (de la primera a la N), y da 26, o 27, o 29....

¿Lo estoy haciendo bien? ¿Que representa toda esta flasheada de números? ¿Nos sirven para resolver el problema?

**Comment by tferraro** [comment]
Interesante, no tira ninguno de los defaults. Cuando esté frente a la pc lo
pruebo y veo si encuentro algo raro😉

**Comment by ltrinidad** [comment]
Uuu que grande ! gracias !! 😄

**Comment by tferraro** [comment]
Buenas!

No pude encontrar exactamente la razón del comportamiento, pero te pido que pruebes lo siguiente:
- Fijate de no usar `echo`, y en su lugar usar `printf`. Echo tiene comportamientos que probablemente no estés esperando: _como el hecho de que si querés hacer `echo hola\n`_ va a imprimir `holan` (y si haces `echo "hola\n"` va a mostrar `hola\n`.

No se hasta que punto modifica en esta segunda forma si uno le pasa lo que va a printear a otra aplicación con los pipes de bash (u otro archivo en este caso), dado que para que muestre bien, habría que usar el flag -e con echo.

Más allá de eso, vos estás haciendo la primera, con lo que no estaría mostrándote los \n y no se hasta que punto funciona bien el script sin eso 😛 

- Por otro lado, algo más que puede estar pasando, si lo anterior no funciona, es que como estás levantando toda la info a memoria y pasandole un super string de 1Mb +- un par de bytes, que se ponga difícil por el tamaño y esté pinchando. **Si lo anterior no anduvo**, fijate en usar un archivo temporal con la data del bloque y mostrarlo por stdout con `cat` y después eliminas el archivo.

Cualquier cosa, estoy a un msj de distancia 😉 

Saludos!

Tom

**Comment by tferraro** [comment]
Buenas!

@ltrinidad alguna noticia con esto?

**Comment by ltrinidad** [comment]
Hola Tomás! Estuve arreglando otras cosas en el worker y no probé lo que me dijiste todavia... estoy complicado con diseño estos días :/...
Ni bien lo pruebe aviso! 
Gracias por la ayuda!!!!!

**Comment by ltrinidad** [comment]
Buenas ! 
No se que onda, pero todavía no lo pude resolver !! 
Hice primero lo de cambiar echo por printf y pasaba lo mismo, despues me guarde el bloque en un archivo y ... LO MISMO :cry:

```c
int realizar_transformacion(t_datos_transformacion datos_transformacion, t_script script_transformacion){

	char* bloque = leer_bloque(datos_transformacion.numero_bloque, datos_transformacion.ocupado_del_bloque);

	if(bloque == NULL){
		log_error(log_worker, "No se pudo leer el bloque (numero %d) completo segun el tamanio especificado (%d bytes)",
							  datos_transformacion.numero_bloque, datos_transformacion.ocupado_del_bloque);
		return -1;
	}

	t_script archivo_temporal_bloque = reconstruir_archivo("../temp/bloques_sin_transformar/", bloque, datos_transformacion.ocupado_del_bloque +1);

	if(archivo_temporal_bloque.ruta == NULL){
		log_error(log_worker, "No se pudo construir el archivo temporal para almacenar el contenido del bloque leido");

		free(bloque);

		script_destroy(archivo_temporal_bloque);

		return -1;
	}

	int resultado = ejecutar_comando_transformacion(archivo_temporal_bloque, script_transformacion, datos_transformacion.ruta_archivo_temporal);

	script_destroy(archivo_temporal_bloque);

	free(bloque);

	if(resultado < 0){ // segun man system retorna -1 si salio mal la ejecucion, y retorna cero si el comando es nulo (cosa que creo que no pasa).
		log_error(log_worker, "No se pudo transformar y ordenar el bloque solicitado. System devolvio %d", resultado);
		return -1;
	}

	log_trace(log_worker, "Se pudo transformar y ordenar correctamente el bloque solicitado. System devolvio %d", resultado);


	return 0;

}
```
``` c
int ejecutar_comando_transformacion(t_script archivo_temporal_bloque, t_script script_transformacion, char* ruta_archivo_temporal){

	char* comando_ejecucion = string_new();

	string_append_with_format(&comando_ejecucion, "cat %s | ./%s > %s",
			archivo_temporal_bloque.ruta, script_transformacion.ruta, ruta_archivo_temporal);

	log_trace(log_worker, "el comando a ejecutar es %s", comando_ejecucion);

	int resultado = system(comando_ejecucion);

	int status;

	wait(&status);

	if(WIFEXITED(status)){
		log_trace(log_worker, "El exit status del comando fue %d\n", WEXITSTATUS(status));
	}else{
		log_trace(log_worker, "Se ve que system no termino normalmente... el codigo de resultado fue: %d\n", resultado);
	}

	free(comando_ejecucion);

	return resultado;

}
```

```
[INFO] 17:51:09:175 Worker/(2474:2474): Worker se inicio correctamente y esta a la espera de conexiones.
[TRACE] 17:51:22:432 Worker/(2474:2474): Un master se conecto correctamente, y ya fue notificado de la conexion.
[TRACE] 17:51:22:435 Worker/(2474:2478): El pedido del cliente 6 esta siendo atendido
[TRACE] 17:51:22:506 Worker/(2474:2478): Se construyo el script de transformacion de nombre: oOLcW3, en el directorio ../temp/scripts_transformacion/, para atender el pedido del cliente 6
[TRACE] 17:51:22:545 Worker/(2474:2478): el comando a ejecutar es cat ../temp/bloques_sin_transformar/EoG20o | ./../temp/scripts_transformacion/oOLcW3 > ../temp/bloques_transformados/b1
[TRACE] 17:51:22:642 Worker/(2474:2478): Se ve que system no termino normalmente... el codigo de resultado fue: 0

[TRACE] 17:51:22:642 Worker/(2474:2478): Se pudo transformar y ordenar correctamente el bloque solicitado. System devolvio 0
[TRACE] 17:51:22:645 Worker/(2474:2478): Se desconecto el cliente 6 y el mismo fue notificado.
[TRACE] 17:51:36:222 Worker/(2474:2474): Un master se conecto correctamente, y ya fue notificado de la conexion.
[TRACE] 17:51:36:232 Worker/(2474:2490): El pedido del cliente 7 esta siendo atendido
[TRACE] 17:51:36:299 Worker/(2474:2490): Se construyo el script de transformacion de nombre: xzTw8u, en el directorio ../temp/scripts_transformacion/, para atender el pedido del cliente 7
[TRACE] 17:51:36:328 Worker/(2474:2490): el comando a ejecutar es cat ../temp/bloques_sin_transformar/G6QUfw | ./../temp/scripts_transformacion/xzTw8u > ../temp/bloques_transformados/b1
[TRACE] 17:51:36:534 Worker/(2474:2490): Se ve que system no termino normalmente... el codigo de resultado fue: -1

[ERROR] 17:51:36:537 Worker/(2474:2490): No se pudo transformar y ordenar el bloque solicitado. System devolvio -1
[ERROR] 17:51:36:537 Worker/(2474:2490): Fallo la transformacion de datos iniciada por el cliente 7, se aborto la etapa
[TRACE] 17:51:36:539 Worker/(2474:2490): Se desconecto el cliente 7 y el mismo fue notificado.

```

Ademas parece que hace algo raro cuando consulta WIFEXITED porque siempre esta entrando por el else, capaz lo estoy usando mal yo ... igual lo probé sin eso del if y pasaba lo mismo... solo que por todas las transformaciones que hace dice que el exit status fue 148 ... 

En fin, no se que onda con esto !!! El sabado va a haber soporte en Medrano ? Me doy una vuelta ...

**Comment by tferraro** [comment]
Mmm, podría ser que tuvieras este problema: https://github.com/sisoputnfrba/foro/issues/940#issuecomment-343135043? Tengo mis dudas porque la primera vez agarra y las demás no. Creo que va a ser más conveniente verlo físicamente que por acá.

Todavía no hay nadie anotado para el sábado (vienen complicadas estas semanas respecto a tiempos) pero trato de conseguir a alguien que te de una mano :slightly_smiling_face:

**Comment by ltrinidad** [comment]
Probé lo que sugeriste en ese issue, y tira que : 

```
[TRACE] 11:49:09:76 Worker/(2851:2855): el comando a ejecutar es 'cat ../temp/bloques_sin_transformar/Nvd6Q3 | ./../temp/scripts_transformacion/O35yya > ../temp/bloques_transformados/b1'
sh: 1: cat ../temp/bloques_sin_transformar/Nvd6Q3 | ./../temp/scripts_transformacion/O35yya > ../temp/bloques_transformados/b1: not found
[TRACE] 11:49:09:101 Worker/(2851:2855): El exit status del comando fue 36

[TRACE] 11:49:09:101 Worker/(2851:2855): Se pudo transformar y ordenar correctamente el bloque solicitado. System devolvio 32512
[TRACE] 11:49:09:103 Worker/(2851:2855): Se desconecto el cliente 6 y el mismo fue notificado.

```

Tira ese error loco porque en el shebang del script dice que el interprete es el de python??, igual re turbio lo que paso, porque fallo y system no retorno -1 😭 !!!! 

Dale, voy checkeando el twitter de la cátedra para ver si algún ayudante aparece por Medrano ... 
Muchas gracias Tomas!!! 😄

**Comment by tferraro** [comment]
Mientras tanto: que pase algo como `sh: 1: not found` es normal, quiere decir que con las comillas no anduvo y no está detectando el comando :stuck_out_tongue:

**Comment by ltrinidad** [comment]
Aaa, ok ok ! :sweat_smile:

**Comment by tferraro** [comment]
Buenas! al final que paso con esto? Pudiste verlo en persona con algún ayudante?

**Comment by tferraro** [comment]
Cierro el tema por inactividad. Si sigue, @ltrinidad volvelo a abrir y lo vemos!
