### ISSUE TITLE
Parametros del master: reductor

### ISSUE THREAD

**Issue by damian1791** [sisoputnfrba/foro#927]
Buenas, mi consulta tal como lo dice el titulo es por el parametro que recibe el master, porque reductor local hasta donde entiendo es el apareo (en el worker) no entiendo para que se usa ese parametro.

**Comment by damian1791** [comment]
Buenas, mi consulta tal como lo dice el titulo es por el parametro que recibe el master, porque reductor local hasta donde entiendo es el apareo (en el worker) no entiendo para que se usa ese parametro.

**Comment by tferraro** [comment]
Buenas!

La reducción local no es un apareo, es una etapa donde se va a aplicar el script de reducción entre otras cosas.

Siento que esta respuesta va a abrir una puerta a muchas dudas más. Te recomiendo que te pases hoy (o el sábado que viene) por el Soporte en Campus. Va a ser más fácil evacuar dudas que por texto escrito :slightly_smiling_face: 

Saludos!

Tom

**Comment by tferraro** [comment]
Buenas!

Que tul con esto @damian1791 ? Te cerró la idea?

**Comment by damian1791** [comment]
Sisi. Muchas gracias. Cierro el issues!
