### ISSUE TITLE
Funcion rename y mv de fsYAMA

### ISSUE THREAD

**Issue by CarolinaPonceRodriguez** [sisoputnfrba/foro#928]
Buenas nuevas, tengo unas consultas sobre estas dos funciones del fs. Me confunden un poco debido a que por la especificacion de las mismas, parecieran iguales, es decir, mv haria un rename y viceversa.

Por lo que vi, mv de unix es exactamente igual, pero el comando rename de unix recibe un  regex y un archivo/lista de archivos.

Como seria realmente? 

Saludos.

**Comment by tferraro** [comment]
Buenas!

Si bien los comandos están hechos lo más similar a la realidad posible, existen ciertas limitaciones. Una es, por ejemplo, que en la interfaz del FS de Linux no está el comando _renombrar_, sino que hace uso de "mover" para ponerlo en el mismo directorio con otro nombre.
No son _iguales_ pero _move_ (mv) puede funcionar como _rename_ bajo ese caso particular. Sin embargo, _mv_ es mucho más complejo que solamente renombrar.

Volviendo a la sintaxis que plantea el enunciado, está pensada de forma cómoda para que la entiendan y les sea fácil implementar, justamente por eso _es opcional_ (aunque les recomendamos que la usen o la usen como base).

Saludos!

Tom

**Comment by CarolinaPonceRodriguez** [comment]
Buenas, 

A ver si entendi:
1)Si tengo un directorio sin archivo, renombro el directorio, pero todo lo que tenia el directorio anterior lo tengo que mover al nuevo directorio, sino, queda inconsistente. Es asi? 
2) Si le paso un archivo, renombro el directorio y el archivo, por lo cual ambos se moverian, pero tambien tengo que mover todo lo que el directorio contenia(aparte del archivo que renombre)? 

En el caso del rename, entiendo que si o si voy a terminar llamando a mv de una u otra manera, porque si no lo hago, con el solo hecho de renombrar y no mover, estaria quedando inconsistente. Un ejemplo de pseudocodigo:

rename(){
mv()
}

Saludos!

**Comment by manutuero** [comment]
Adhiero a la consulta, viendo la firma: rename [path_original] [nombre_final] al comando lo implemente de modo que le pasas un path (que puede ser un archivo o directorio) y en función de lo que sea hace esto:

*En el caso de un directorio:
rename /root/usuario usr 

quedandote /root/usr

* En el caso de un archivo:
rename /root/nombreInicial.txt nombreFinal.txt

quedandote  /root/nombreFinal.txt

...por atrás actualizo en memoria y en disco lo que corresponda.
Quería saber si el enfoque esta bien.

Gracias y saludos!

**Comment by tferraro** [comment]
Buenas!

@CarolinaPonceRodriguez:
1 -¿Haría falta mover el contenido del directorio?
2 - No entiendo a que apuntas con pasarle un path y renombrar el directorio y el archivo.

¿ Que comportamiento esperarías vos de una función que "mueva" un archivo o un directorio de un lado a otro del FS?

Para @manutuero viene por ese lado la cosa. Tendría sentido que una función que se llama "renombrar" tuviera otro funcionamiento?

**Comment by CarolinaPonceRodriguez** [comment]
Buenas!
 
@tferraro  Te respondo a tu preguntas:
1) El movimiento del contenido del directorio no seria fisico, sino logico, es decir, si yo cambio el nombre de un directorio en la tabla de directorios, todo lo que contenia ese directorio apuntaria al mismo padre, pero seria otro nombre.
2) Supongamos el siguiente caso: 
rename /root/user/pepito/archivo.txt  /root/usuario/juan/archivo2.txt

En un caso asi, debiera modificar desde /user en adelante o este tipo de casos no se presentarian?  Si esto no pasara unicamente tomaria el comportamiento que detallo @manutuero 

Saludos.

**Comment by tferraro** [comment]
Buenas!
1 - Bien, quería asegurarme que el concepto se entendía.
Respecto a tu ejemplo, te estás confundiendo algo. El `rename` tiene como objetivo cambiar de nombre, incluso el segundo argumento es el nombre final (no el path final, a diferencia del `mv`). Siento que estas confundiendo el "mover" con "renombrar" cuando las firmas que tienen ambas funcionalidades son diferentes.

**Comment by CarolinaPonceRodriguez** [comment]
Detalle, no me habia dado cuenta que en la firma del rename el segundo argumento decia [nombre_final], puede pasar. Quedo claro!
Cierro, gracias!
