### ISSUE TITLE
Consulta Apareo

### ISSUE THREAD

**Issue by marrtins** [sisoputnfrba/foro#929]
Buenas, estaba con el tema del apareo de los archivos temporales en la reduccion local. 
leyendo [man sort](https://linux.die.net/man/1/sort) vi que con -m ya hace un apareo de varios archivos ya ordenados, con esto ya es suficiente? o tendría que pensar alguna forma hecha por mí porque esa solución no cumple por ser muy costosa (aunque lo dudo)... o algún otro factor de la consigna?

Gracias, martín

**Comment by tferraro** [comment]
Buenas!

Para el caso de la reducción local, viene bien, solo tené en cuenta nomás eso de que el apareo lo hace, pero tienen que _estar ordenados anteriormente_.
Para la reducción global ya la cosa no es taaan sencilla, porque vas a tener que ir inyectando los streams de los diferentes Nodos al Encargado e irlos apareando para meterlos en la reducción global.

Saludos!
Tom

**Comment by marrtins** [comment]
¿Como? No entendí el tema de la reducción global.. Yo tenía pensado que cada worker envíe su temporal de la reducción local al worker encargado y este haga el apareo.. ¿No es así?

**Comment by tferraro** [comment]
Si, a a enviar su temporal!..A demanda 🙂 la idea es que los pedacitos que se vayan recibiendo (si podés hacer un recv de 1MB y que no corte antes, tuviste suerte) los vayan apareando con el resto de los archivos que recibas y se lo vayas metiendo de alguna forma al script de reducción.

**Comment by marrtins** [comment]
Ah, no sabía eso. gracias

**Comment by DarkWood97** [comment]
Entonces cuando el worker tiene que hacer el almacenado final y enviarle el archivo a filesystem, el filesystem tiene que recibir de a cachitos para que no rompa el socket? Digo porque este archivo creo que es grande.

**Comment by marrtins** [comment]
Pero en ese caso, sería lo mismo recibir de a cachitos todos los temporales y una vez que tenga a todos hago rl merge?  Va a ser más óptimo que cualquier apareo que pueda hacer yo, o no?

**Comment by DarkWood97** [comment]
Para mi seria lo mas viable pero creo que malgastas memoria esperando a recibir todos los cachitos y guardandolos, creo que el proposito es ir apareandolos mientras lleguen

**Comment by tferraro** [comment]
Buenas!

@marrtins tal cual como dice @DarkWood97. Una de las ideas bases de la materia es el correcto manejo de los recursos, y levantando X megas a memoria al simultáneo cuando podrías tranquilamente usar simultáneamente 3, parece un mal diseño no?

Respecto a la pregunta anterior de @DarkWood97 , si, tranquilamente. Aunque, no "rompe el socket". Simplemente es el comportamiento esperado. Nunca los sockets te prometen que te van a devolver el tamaño que vos querés (nunca más, pero probablemente menos), pero te prometen decirte _cuantos_ recibiste. Dado su funcionamiento interno, esperar poder recibir 50 megas por socket es un poco... _complicado_. La dinámica 1send-Nrecv es una de las buenas prácticas de programación :slightly_smiling_face: 

Saludos!

Tom

**Comment by marrtins** [comment]
Claro, pero pensé que lo que perdía almacenando los temporales en otra pc, que son un par de mb de mas,  lo ganaba haciendo el apareo mas eficiente( que es haciendo sort -m que ya provee el SO), pensé que no iba a cambiar tanto y además como no estaba en la consigna pensé que valía. 
pero bueno lo cambiaré. gracias!

**Comment by tferraro** [comment]
Buenas!

Hicimos esta aclaración en ambas charlas, más que mal, porque es un tema de buenas prácticas, más que de enunciado del TP.

Como corolario, si no lo hacés, podés correr el riesgo de quedarte realizar un uso extensivo de la memoria y terminar dándose el caso de una falla por falta de memoria. Si esto pasa durante la entrega final, es un problema potencial.

Si las dudas quedaron resueltas, plz cerrá el issue! :policeman:
