### ISSUE TITLE
Consulta sobre causa de replanificacion

### ISSUE THREAD

**Issue by LautaroOdriozola** [sisoputnfrba/foro#930]
Hola!

Queria saber cuales podrian ser las causas de replanificacion ademas de la desconexion de un worker y como se deberia actuar en cada caso. Esto visto desde la parte de Master.

**Comment by tferraro** [comment]
Buenas!

¿Cuáles posibles caminos se te ocurren?

**Comment by BeviF** [comment]
Buenas perdon que me meta pero agrego, yo habia pensado 3 posibles situaciones:
1-El script falla al querer realizar la operacion(sea transformacion o reduccion).
2-El nodo se desconecta.
3-El proceso hijo de worker que esta atendiendo la operacion se termina(lo matan mientras ejecuta).

Esta bien? hay otros casos que se puedan estar escapando?

**Comment by lianndt** [comment]
Hola, una consulta.
Sea cual fuere la razon por la cual falla una TRANSFORMACION... en el momento de replanificar, hay que generar otro registro en la tabla de estado con otro archivo temporal? O se "reutiliza" el mismo archivo de la operacion que fallo? 

Gracias!

**Comment by LautaroOdriozola** [comment]
Habia pensado las mismas situaciones que vos @BeviF pero pensé que podia haber alguna mas. Muchas gracias por responder. Cierro Issue.
