### ISSUE TITLE
Consulta socket descriptors repetidos

### ISSUE THREAD

**Issue by guillelle** [sisoputnfrba/foro#931]
Hola,
luego de entender y armar el select() y las funciones de sockets nos surgió una duda sobre el socket descriptor que asigna la función socket().
Está claro que devuelve un valor entero, ese valor en algún momento imaginamos que se puede repetir, es así?
Por ejemplo, le asigna el SD 20 a una conexión, mientras siga abierta esa conexión no asignará el 20 a otra pero cuando se cierre puede asignarle el 20 a una nueva conexión?

gracias
saludos

**Comment by tferraro** [comment]
Posiblemente 🙂 , dependerá del orden que quiera hacer el sistema operativo para asignar los nros de FD, pero si no hay un FD asociado a ese nº, tranquilamente podría ser tomado cuando requiera crear otro FD, por la razon que fuese.

**Comment by guillelle** [comment]
Por las pruebas que hicimos pareciera que genera números de sockets consecutivos y diferentes mientras no se cierre el proceso server (en este caso YAMA), y a medida que se le conectan MASTERS les asigna un FD nuevo consecutivo del último asignado.
Esta duda surge porque queremos saber si hicimos bien en usar el FD para identificar al MASTER en la tabla de estados, por lo que parece mientras no se cierre el proceso YAMA no tendríamos problemas, teniendo en cuenta que hay una sola instancia del YAMA y si se cierra hay que empezar toooooodo de nuevo en cuanto a la ejecución de los jobs

**Comment by varas-c** [comment]
Como bien dice Tomas en el mensaje de arriba, puede ser que un fd que fue
usado por otro proceso y luego fue cerrado, sea asignado a otro proceso
nuevo por el sistema operativo.

Es decir, si en un cierto momento vos tenes las conexiones 4,5,6,7,8 y por
ejemplo, la 6 se desconecta, ahora pasas a tener las conexiones 4,5,7,8,
quedando la seis libre. Si viene otro proceso y se quiere conectar, nada le
impide al sistema operativo asignarle a esa nueva conexion, el fd numero 6
(porque está libre no?) y no va a haber ningún problema. Ojo, también
podría darle el 9 por alguna razón, lo cual también está bien.

Lo que jamás te va a pasar, es que si tenes una conexión abierta en el fd
(por ejemplo) 8 y viene otro proceso, el sistema operativo NO le va a dar
el fd 8. ¿Por qué? Porque está ocupado.

En resumen, si el fd está "libre" (porque nadie lo usó, porque ya fue
liberado por otro proceso, etc) puede ser reutilizado por el sistema
operativo. Si el fd está ocupado, NO te lo va a pisar con ninguna conexión
entrante.

Con ésto, fijate si llegás a la respuesta del problema que planteás.

Si no se entendió algo o tenés alguna otra duda, pasate de nuevo por acá :)



2017-11-02 15:19 GMT-03:00 guillelle <notifications@github.com>:

**Comment by guillelle** [comment]
sisi, entendí, no puedo usar el FD como un "identificador" de los masters porque en el momento que uno termine el job y se desconecte otro puede tomar ese mismo "identificador", bueno, vemos que inventar entonces,

gracias
saludos

**Comment by tferraro** [comment]
**Nota de color**: La versión que estamos usando de Linux está basado en una parte del core de Unix que soporta el `/dev/fd`. ¿Qué es eso? Es un directorio, donde están tooodos los FDs en uso. Por default seguramente encuentres el ,0 1 2 3 y 255 😛 , y si hacés  en la consola `echo 'hola' >> /dev/1` es lo mismo que hacer  `echo 'hola'`, porque lo va a imprimir por pantalla.

**Comment by varas-c** [comment]
Guille, si la consulta quedó resuelta y no tenés más dudas, no te olvides
de cerrar éste issue!
