### ISSUE TITLE
Funcion rm -b

### ISSUE THREAD

**Issue by AlexFalconR** [sisoputnfrba/foro#932]
Buenas, quería hacer una consulta de enunciado, la función rm -r tiene como parametro tres cosas, un path, un numero de bloque y un numero de copia, la consulta es, estos tres parametros son obligatorios (asumo que el path si)? o puede que no me pasen el numero de bloque o el numero de copia?
Espero su respuesta.
Saludos

**Comment by CarolinaPonceRodriguez** [comment]
Buenas, yo trato de verlo como una consola en linux, si no le pasas algun parametro que necesita el comando para funcionar, que sucede? Te arroja un error de que es invalido. Mi pregunta va para los ayudantes tambien, si es estrictamente necesario validar la sintaxis del comando con todos los parametros que serian obligarios.
Obviamente si una vez recibidos esos parametros, que el fs valide que dichos parametros son validos, sea path, nro bloque , nro copia, etc
Saludos.

**Comment by tferraro** [comment]
> (...)yo trato de verlo como una consola en linux, si no le pasas algun parametro que necesita el comando para funcionar, que sucede? Te arroja un error de que es invalido. (...)

Eso mismo :slightly_smiling_face: 

La sintaxis, es recomendada, más si, no obligatoria, pero sí tienen que tener **esas mismas funcionalidades**. 

Si algo no tiene sentido, el sentido común dicta que informe un error no? Más que trate de hacer algo y explotar por todos lados :stuck_out_tongue:

**Comment by tferraro** [comment]
@AlexFalconR que tul esto? Se puede cerrar?

**Comment by AlexFalconR** [comment]
Sisi, lo cierro yo?


El 8 nov. 2017 14:39, Tomás Ferraro <notifications@github.com> escribió:

@AlexFalconR<https://github.com/alexfalconr> que tul esto? Se puede cerrar?

**Comment by tferraro** [comment]
Dele gass
