### ISSUE TITLE
Levantar tabla de archivos 

### ISSUE THREAD

**Issue by AndresMarcovecchio** [sisoputnfrba/foro#933]
Si vos tenes que levantar por ejemplo el archivo "metadata/archivos/5/ejemplo.csv" como haces para saber que existen en ese directorio "metadata/archivos/5/" un archivo con el nombre "ejemplo.csv", por que no hay ningún otro archivo que persista el nombre "ejemplo.csv", tendríamos que hacer un list del directorio?

**Comment by tferraro** [comment]
Buenas!

No entiendo la pregunta. Estamos hablando sobre cuando un proceso FileSystem se inicia con un estado no-limpio verdad?

Te pregunta es ¿Cómo se yo que existe el archivo XXX entre la metadata? Primero tendrías que saber que **sí existe para tu FS**. Si existe para tu FS, podrías asumir que por algo está ahí e irlo a buscar no? En caso de que algo falle, un programa hecho y derecho probablemente informe que hubo un error haciendo una tarea Y y entonces no se pudo iniciar.

Dí en el clavo?

Saludos!
Tom

**Comment by AndresMarcovecchio** [comment]
Claro la cosa es como se que existe para mi FS, se los directorios que tengo pero no los archivos que hay en los directorios, en el único lugar que se persiste la ruta completa del archivo que esta en el FS es en el mismo archivo, así que como lo levanto si no se donde esta? y ni siquiera se si existe o no...

**Comment by tferraro** [comment]
No estás viendo algo sutil en el ejemplo del enunciado, El nro que aparece en el path (el 5), a que hace alusión? Te suena de donde podrías obtenerlo para armar el path, sabiendo que los paths de algunos archivos en la metadata de los archivos corresponde a `metadata/nro_de_algo/*`, sin listar todo el contenido del directorio metadata?

**Comment by AndresMarcovecchio** [comment]
Ponele que tengo que levantar el archivo del ejemplo del tp:

metadata/archivos/5/ejemplo.csv
TAMANIO=12356334
TIPO=TEXTO
BLOQUE0COPIA0=[Nodo1, 33]
BLOQUE0COPIA1=[Nodo2, 11]
BLOQUE0BYTES=1048500
BLOQUE1COPIA0=[Nodo1, 34]
BLOQUE1COPIA1=[Nodo2, 12]
BLOQUE0BYTES=1048532
...

de donde saco que se llama "ejemplo.csv" y que esta en el indice de directorio 5

**Comment by AndresMarcovecchio** [comment]
Ponele que tengo que levantar el archivo del ejemplo del tp:

metadata/archivos/5/ejemplo.csv
TAMANIO=12356334
TIPO=TEXTO
BLOQUE0COPIA0=[Nodo1, 33]
BLOQUE0COPIA1=[Nodo2, 11]
BLOQUE0BYTES=1048500
BLOQUE1COPIA0=[Nodo1, 34]
BLOQUE1COPIA1=[Nodo2, 12]
BLOQUE0BYTES=1048532
...

de donde saco que se llama "ejemplo.csv"

**Comment by tferraro** [comment]
Ahí te seguí. En ese caso, **ahí si vas a tener que "listar"**, pero eso no es un tema de listar el contenido de metadata, sino del contenido del directorio `metadata/5/`. Con parsear lo que devuelve `ls` sobre ese directorio sería suficiente para obtener los archivos que existen allí.

**Comment by AndresMarcovecchio** [comment]
Joya ahora si me cerro, muchas gracias.
