### ISSUE TITLE
Bloques y corte de archivos de texto

### ISSUE THREAD

**Issue by FedericoJoel** [sisoputnfrba/foro#935]
Como estan?

Una consulta, al cortar texto con los \n.. los \n tienen que quedar incluidos en el bloque?
Por ejemplo si yo tuviese un bloque de 10 bytes y el texto
hola como\n  > en el bloque tendria que estar el \n?

Abrazo.

**Comment by varas-c** [comment]
Buenas!

Pensalo desde el lado de la "lectura". Imaginate que guardas todo sin los
\n y ahora queres leer todo lo que guardaste. Al no tener los \n, se te va
a complicar la lectura?
Ahora imaginate que guardás todo con los \n. Te modifica en algo la lectura?

**Comment by tferraro** [comment]
Agrego algo a lo de Chris: Si un archivo que guardaste en el FS, y vos sacás los \n,_sigue siendo el mismo archivo_? Si lo reconstruís, el contenido es el mismo?

**Comment by epreyes** [comment]
Los \n siguen siendo bytes ocupados en el archivo (al igual que los caracteres) que le pertenecen, yo lo consideraria

**Comment by mgarciaisaia** [comment]
Creo que la pregunta se refiere al último \n de cada bloque, y no a los \n
en general.

Podés pensar eso de "los bloques de arman cortando en los \n" como que los
bloques están compuestos por un conjunto de líneas. Y parte de la línea es
el delimitador.

Así que, sí - el último carácter útil de cada bloque debería ser un \n, en
principio.

**Comment by tferraro** [comment]
@FedericoJoel que onda esto? Te sirvieron las respuestas para encarar algo?

**Comment by tferraro** [comment]
Cierro el tema, cualquier cosa lo volvemos abrir!
