### ISSUE TITLE
YAMA - Lectura de archivos 

### ISSUE THREAD

**Issue by dromero-7854** [sisoputnfrba/foro#936]
Buenas, tengo otra consulta de FS. 
Segun el enunciado:
> Leer archivo
> 
> Recibirá una ruta completa con el nombre del archivo. Responderá con el contenido completo del mismo. 
>

Mi consulta es ¿En que parte de todo el proceso se va a utilizar este servicio? ¿O esta haciendo referencia al comando _cat_ disponible en la consola del FS?

Gracias!!

**Comment by tferraro** [comment]
Buenas!

Hace referencia al comando cat! Está puesto duplicado allí para dar el sentido de doble-vía de la comunicación entre el FS y los Nodos nomás.

**Comment by dromero-7854** [comment]
Listo... Gracias!
