### ISSUE TITLE
Envio y Recepcion de bloques por Socket, FS-Datanode

### ISSUE THREAD

**Issue by CarolinaPonceRodriguez** [sisoputnfrba/foro#937]
Buenas, estuve leyendo algunos issues sobre el tema del envio y recepcion de archivos por sockets y la consulta es si pudiera tener el mismo inconveniente en cuanto al envio y recepcion de los bloques. 
Hasta ahora probe enviar contenido que no supere 1k, meramente por pruebas, pero en la realidad, como esta armado mi codigo y por enunciado mismo, cuando envio o recibo un bloque puede ser como maximo de 1MB. Deberia considerar alguna opcion de cortar el bloque y enviarlo a cachitos o no deberia tener inconvenientes de enviar un 1mb por vez? 

Saludos.

**Comment by varas-c** [comment]
Hola! Cómo va?

Recv siempre te devuelve la cantidad de bytes recibidos. Si de antemano ya
sabes la cantidad de bytes que deberías recibir y recv te devuelve la
cantidad de bytes que realmente recibió, no es para nada mala idea
verificar que "lo esperado", sea lo "realmente recibido".

Cuando vos haces un "send", le pedís al sistema operativo que envíe cierta
información a un cierto lugar (lo hace el SO porque es una Syscall). Si el
paquete es considerado "chiquito", lo mas probable es que el sistema
operativo mande todo el paquete de una y listo.
Pero que pasa si es muy grande como para mandarlo todo "de una"? El So
puede decidir enviar el paquete de a pedazos de X tamaño. Por ejemplo,
hacer 1 send de 20k, otro de 30k y otro de 25k. Entonces, deberías vos
hacer una función que se encargue de mandar de a pedacitos chiquitos un
paquete grande? Lo mas probable es que no, porque el SO ya lo hace por
vos 😉

Como te comenté al principio, si sabes el tamaño de lo que deberías recibir
y sabes cuanto realmente recibiste, podrías verificar si esperado ==
recibido. Con un while y la condición correcta, ya lo soluciónas, es
bastante sencillo.

Por suerte alguien un día aburrido se dió cuenta que éste problema era
bastante común y estar metiendo while con recvs era medio un garrón y se le
ocurrió inventar las flags para el recv
<http://man7.org/linux/man-pages/man2/recv.2.html>

Como comentario final, personalmente he visto a grupos desaprobar entregas
porque nunca se les ocurrió mandar "paquetes grandes" ni verificar los
recv. Pensá que los mensajes es una de las cosas mas importantes del TP. Si
la comunicación falla, prácticamente se cae todo.

Cualquier otra duda pasate de nuevo!

2017-11-03 13:31 GMT-03:00 Carolina Ponce Rodriguez <
notifications@github.com>:

**Comment by CarolinaPonceRodriguez** [comment]
Gracias!! cierro.
