### ISSUE TITLE
Consulta sobre md5 

### ISSUE THREAD

**Issue by DPoma** [sisoputnfrba/foro#938]
Hola, tengo una duda acerca del md5.
Para distinguir fácilmente que tipo de archivo quiero copiar agregue al cpfrom dos flag (-b y -t).
Ahora bien, por ejemplo, si tengo un archivo "file.bin" o "file.txt" y lo copio a yamafs como binario (cpfrom -b) y como texto (cpfrom -t) cuando pida su md5 el valor que me devuelve debería ser el mismo en ambos casos? Es decir no importa de que forma copie un archivo el md5 nunca debería cambiar o puede dar diferente dependiendo de la forma que lo copie?

**Comment by tferraro** [comment]
Buenas!

Deberían ser iguales.
El cómo se almacenen no debería afectar la información final que guardan 🙂.

Saludos!

Tom

**Comment by DPoma** [comment]
Supongo que eso solo deberia pasar con los archivos que nos van a dar ustedes.
Porque si yo ahora agarro un archivo cualquiera que pesa 5,5 mb y lo copio en mi yamafs como binario va a ocupar 6 bloques y la mitad del ultimo bloque va a tener basura (porque para yamafs los binarios deben utilizar si o si bloques completos), en cambio si lo copio como texto va a ir a buscar un \n para saber donde termina el registro que puede estar o no, quien sabe.
Es correcto lo que digo o estoy diciendo cualquier cosa?

**Comment by tferraro** [comment]
El tema es, la forma en las que yamafs almacene no va a importar a la hora
de trabajar con el archivo. Es decir, si tu sistema los almacena en una
forma fija que requiere rellenar con basura, esa basura no forma parte de
tu archivo no? Tendría sentido usarla en el calculo del md5?

**Comment by CarolinaPonceRodriguez** [comment]
Buenas consulta, 
Yo deje abierta la posibilidad de que para un archivo binario el ultimo bloque pueda o no ser completado en su totalidad y el resto sea basura. Sino, unicamente te permitiria guardar archivos de 1mb, 3mb, 6mb y asi sucesivamente. Es una posibilidad que puedo contemplar?

Saludos.

**Comment by tferraro** [comment]
Que el sistema de almacenamiento deje espacio vacio y no complete el
bloque, es un defecto de su diseño, queee corresponde un tipo de
fragmentación en particular, pero no implica que el archivo cambie.

**Comment by CarolinaPonceRodriguez** [comment]
Creo que no se entendio lo que pregunte. A lo que iba es que permito que un archivo binario sea escrito sin importar que el ultimo bloque del mismo ocupe 1 mb entero. Ahora a la hora de leerlo y/o por ejemplo, hacerle md5, este va a leer del ultimo bloque unicamente el contenido que es valido porque los bloques anteriores si van a completar 1 mb cada uno. Podria ser asi?

Saludos.

**Comment by tferraro** [comment]
No te sigo che 🙁

**Comment by CarolinaPonceRodriguez** [comment]
Lo pongo asi, cito del texto:
"En el caso de los archivos binarios, todo el bloque debe utilizarse completo." En mi caso, yo permiti que el ultimo bloque no necesariamente este completo para tener mayor flexibilidad a la hora  de almacenar un archivo de tipo binario.

Saludos.

**Comment by tferraro** [comment]
Ahora si! Sep, ese disclaimer es para partir el archivo, si por su tamaño no completa el bloque, no completa y listo🙂

**Comment by DPoma** [comment]
Si entiendo que a la hora de calcular el md5 solo hay que usar el contenido valido. 
Pero mi duda es si el md5 deberia ser igual (ya sea que lo copie como binario o como texto) para cualquier archivo en general.
Por ejemplo si ahora agarro un archivo "gatitos.jpg" y lo copio de forma binaria lo voy a "cortar" en bloques y en caso de que ultimo bloque quede a medio llenar me guardo el ultimo byte valido y listo.
Ahora, si lo copio en forma de texto según lo que entendí hay que ir a buscando los \n para saber donde termina el registro, pero en "gatitos.jpg" supongo que el \n puede estar en cualquier parte, incluso pasando el MB o ni siquiera estar por lo tanto cuando haga el copiar en forma de texto seguramente tire error.
Resumiendo, si me dicen que los archivos que ustedes nos den en las pruebas van a tener \n y los registros no van a superar el tamaño del bloque ahi si estoy de acuerdo que el md5 tiene que dar igual independientemente de la forma en que lo copie.
En cambio si me dicen que el md5 debería ser igual para cualquier archivo que se me ocurra probar (ya sea imagen, texto etc)  sin importar importar la forma en que lo copie, entonces no estaria entendiendo como implementarlo.

**Comment by tferraro** [comment]
@DPoma no va a haber archivos cuya línea supere el 1MB. Eso ya sería jugar hasta que punto aguanta la especificación, que la definimos nosotros, por su lado mucho no pueden hacer mucho más que fallar de la forma que quieran (sea porque no pudo almacenar por no poder cortar o porque se de cuenta).

**Comment by alejandrog87** [comment]
Justo iba a preguntar algo similar, de un caso no tan "border":
La definicion del enunciado dice:
"En el caso de los archivos binarios, todo el bloque debe utilizarse completo"
obviamente si yo tengo un archivo binario de 6,5 mb voy a "leer" hasta ese tamaño , por lo cual el 0,5 mb restante será lo que haya en dicho bloque (basura).
Según la sección "Esquema de filesystem de ejemplo" del enunciado los bloques tienen un atributo "Fin Bloque" que indica el ultimo byte válido, que según dicha sección del enunciado para los archivos de texto parece variar mientras que para los archivos binarios se mantiene fijo en el tamaño de bloque. Éste atributo deberíamos usarlo de igual forma en ambos tipos de archivos, ya que si yo hago un md5 de un archivo binario de 6,5 mb en yamafs y no tengo en cuenta solo el contenido válido (es decir no tengo en cuenta que del ultimo bloque solo es válido la mitad) voy a tener una diferencia respecto al md5 que puedo hacer del archivo en mi file system local de linux.
Este caso se daría con archivos binarios que no fueran de un tamaño entero (1.5, 3.2, etc) , los archivos con los que se va a probar el fsyama pueden caer en esta situación o van a ser de un tamaño entero?
Gracias.

**Comment by tferraro** [comment]
No solo pueden, sino que seguro van a no ser de tamaño entero😛.

**Comment by alejandrog87** [comment]
ok, gracias por la pronta respuesta.

**Comment by tferraro** [comment]
@DPoma vos que abriste el issue originalmente, quedó claro? Se puede cerrar?

**Comment by DPoma** [comment]
Si ya me quedo claro, gracias, cierro.
