### ISSUE TITLE
Problema de memoria

### ISSUE THREAD

**Issue by AlexFalconR** [sisoputnfrba/foro#939]
Buenas tardes, estoy teniendo un problema con una función que estaba funcionando y de un día para otro dejo de hacerlo.
El error que tengo es "*** Error in `/home/utnso/Escritorio/Git/tp-2017-2c-LaYamaQueLlama/fileSystem/Debug/fileSystem': free(): invalid next size (fast): 0x096c3180 ***", lo que claramente marca que tengo un problema al usar un free(), Debbuguenado vi que rompe en esta parte del códgo(Linea seleccionada):
![image](https://user-images.githubusercontent.com/11712503/32458686-f269aa14-c30b-11e7-88c4-33984069e53e.png)

Asu vez, si yo comento los free() (de ambos strings) el programa segun eclipse funciona, pero segun valgrind no llega a compilar y no muestra ningún tipo de ejecución.

Espero su respuesta.
Saludos

**Comment by tferraro** [comment]
Buenas!
El error de valgrind que describís, es porque estás corrompiendo la memoria de la aplicación. El hecho de sacar el free, solo evita que rompa pero no implica que lo que estés haciendo está bien.
Te diría que revises bien las funciones que llamás, porque si de un día para otro cambió, probablemente hay un commit de diferencia :wink:

**Comment by AlexFalconR** [comment]
Si, es obvio que hay un commit de diferencia, pero no es normal que me tire un error en un free() de algo que hacen las commons. A su vez, tengo problema en todos los mallocs que hago, por ejemplo:
![image](https://user-images.githubusercontent.com/11712503/32476444-2ddd8288-c356-11e7-80ea-c1d9006523db.png)

haciendo ese malloc, si intento hacer, free(nuevoBloque); tambien tira error, no se si eso es un problema mio o si es algo normal del enguaje

**Comment by fedebonisconti** [comment]
Te fijaste el valor de retorno del getline? Que no te este devolviendo un error ahí?

Tene cuidado con el segundo bloque que copiaste que estás teniendo un memory leak con el malloc. Por otro lado, estaría bueno saber qué tiene la lista (que es el struct), para entender un poco más el problema

**Comment by FedericoVigi** [comment]
Hola @AlexFalconR perdón que me meta (no soy ayudante) pero alguna vez tuve una duda similar por no entender como funcionaban las listas de las commons y vi el issue tratando de resolver otra duda y quería sumar una ~boludez~ a lo que dijeron que te puede servir.
![image](https://user-images.githubusercontent.com/8700754/32514661-7ed31ad2-c3dc-11e7-9988-08d0924c5296.png)

Fijate que en esta lógica hay un leak; tenes un puntero **_nuevoBloque_** que apunta a memoria que reservas con _malloc_ pero en la línea siguiente perdés esa referencia haciendo que **_nuevoBloque_**  cambie y ahora apunte a un elemento de tu lista, y lo que es más grave es que si intentas hacer un free, como dijiste que hacías, estas destruyendo el elemento de tu lista (pero sin sacarlo de ésta), lo más probable es que si tenés esta lógica en varios lugares estés haciendo varias veces _free()_ de los mismos elementos de la lista y valgrind te llore por todos lados .  
Lo importante es tener en cuenta que las listas de las commons son listas de "punteros" o sea que  list_get() te retorna un puntero a un elemento (cuyo espacio ya fue reservado en memoria en otro momento) y **no** los valores de los elementos y ese malloc que haces no tiene sentido si solo vas a usar el puntero **_nuevoBloque_**  para que apunte a un elemento de tu lista temporalmente. _Mis 2 centavos._

**Comment by varas-c** [comment]
Excelente Fede.

Puede ser que el problema de los free() venga por ese lado, tal cual como
lo explicó tu compañero.

Al hacer list_get estas pisando la direccion a la cual apuntaba tu puntero
nuevoBloque, por ende perdes la referencia y ahí tenes un memory leak.

Al hacer free() no estas liberando la memoria que hiciste con el malloc de
un par de renglones arriba, si no que estas liberando memoria de un
elemento de tu lista y no se si es eso lo que realmente estés queriendo
hacer.

Fijate si no estás teniendo este mismo error por varios lugares y si es la
causa del error. Lo que NO debes hacer es decir "ya fue, borro los free así
anda" porque basicamente estás pateando la bomba para más adelante. Puede
ser que te ande esa parte del tp pero te explote por otro lado.

Si seguís con dudas, pasate por acá de nuevo

**Comment by AlexFalconR** [comment]
Buenas, si, definitivamente uno de los problrmas que tenia era el que dijo el compañero. Ahora estoy igual con el config_destroy () pero voy a esperar un rato para subir la duda, primero quiero revisar bien el codigo.
Saludos y gracias a todos

El 8 nov. 2017 08:45, varas-c <notifications@github.com> escribió:
Excelente Fede.

Puede ser que el problema de los free() venga por ese lado, tal cual como
lo explicó tu compañero.

Al hacer list_get estas pisando la direccion a la cual apuntaba tu puntero
nuevoBloque, por ende perdes la referencia y ahí tenes un memory leak.

Al hacer free() no estas liberando la memoria que hiciste con el malloc de
un par de renglones arriba, si no que estas liberando memoria de un
elemento de tu lista y no se si es eso lo que realmente estés queriendo
hacer.

Fijate si no estás teniendo este mismo error por varios lugares y si es la
causa del error. Lo que NO debes hacer es decir "ya fue, borro los free así
anda" porque basicamente estás pateando la bomba para más adelante. Puede
ser que te ande esa parte del tp pero te explote por otro lado.

Si seguís con dudas, pasate por acá de nuevo
