### ISSUE TITLE
Worker - System en Eclipse

### ISSUE THREAD

**Issue by gustofa** [sisoputnfrba/foro#940]
Hola.
Tengo un comportamiento extraño en Eclipse al usar la llamada al sistema System, lo tengo configurado para que al debugear siga al hijo al hacer el fork.
En el fork todo bien, se crea el hijo y en eclipse se me bifurca la ejecución, quedando el proceso padre por un lado y yo paso a debugear al hijo. Ahora bien, cuando dentro del hijo ejecuto system() para, por ejemplo, correr la transformación, Eclipse crea un nuevo proceso y es como si pasara a esa ejecución, pero nunca más vuelve a las otras, queda como en un limbo.

![error_eclipse](https://user-images.githubusercontent.com/4429106/32477737-fa845750-c35e-11e7-8938-7b1cdac29d4f.png)

La línea 149 la corre el proceso 6762, la instrucción es 
"cat /home/utnso/yama/bloque | sh /home/utnso/yama/script.sh | sort > /home/utnso/yama/resultado_tranformacion.txt"
y en principio es correcta, la ejecuto por consola y corre bien.
Al ejecutar system(instruccion) eclipse crea el proceso 6792 y se queda ahí, además por consola tira esos mensajes sobre los breakpoints y direcciones de memoria.

No se si es un mal uso de system, alguna config de eclipse que me falta tocar o algo más.

Esto hace que no podamos debugear worker y nos está complicando, estoy considerando cambiar el system por otro fork+pipes, pero antes no quería dejar de consultar aqui.

Es tarde, si mañana alguno puede darme alguna idea de que puede estar pasando se los agradeceré mucho.

Buenas noches.

**Comment by mgarciaisaia** [comment]
PE DA ZO de reporte, papá. Gracias.

Los mensajes de error que ves ahí dicen que Eclipse intentó setear en `gdb` los breakpoints que tiene configurados tu proyecto. El problema es que, claro, lo que estás corriendo en ese nuevo proceso no es tu `worker`, si no `/bin/sh`, y entonces probablemente no encuentre las funciones de tu código en ese programa - por eso no puede poner los breakpoints.

Ahí arriba en la vista de Debug dice que tenés un proceso 6707 que está frenado. ¿No será este? ¿Te quedó de una ejecución anterior?

Si cambiás `instruccion` para que sea algo más sencillo (ponele, un `instruccion = "/bin/ls"` justo antes de llamar a `system`), ¿ejecuta bien?

Tiene sentido que el proceso principal se quede esperando a que el proceso hijo termine, porque, buen, ese es el comportamiento de `system`. Lo que habría que ver es por qué se quedó colgado el proceso hijo. ¿Seguro que no está laburando y simplemente tarda un rato?

Lo otro que podés hacer es correr el comando ese con `strace`. Onda, hacé que `instruccion` sea `strace cat ...`, así te muestra en la consola las llamadas a sistema que está haciendo. Capaz ahí podés ver que, no se, el proceso la colgó esperando leer algo por teclado, o algo raro así.

O pasate esta noche por el curso de Esteban (o mañana por el de Adro, probablemente, que suelen haber ayudantes, o el sábado por el soporte) así lo vemos, porque parece estar peluda de debuggear :)

¡Un abrazo, che!

**Comment by gustofa** [comment]
Yendo por partes:


> Ahí arriba en la vista de Debug dice que tenés un proceso 6707 que está frenado. ¿No será este? ¿Te quedó de una ejecución anterior?

Descartado, ese proceso es el worker original, el que hace la recepción del mensaje de master y se forkea.


> Si cambiás instruccion para que sea algo más sencillo (ponele, un instruccion = "/bin/ls" justo antes de llamar a system), ¿ejecuta bien?

No, con una instrucción sencilla sucede exactamente lo mismo.


> ¿Seguro que no está laburando y simplemente tarda un rato?

Al ejecutar la misma instrucción directo por consola resuelve inmediatamente


> Lo otro que podés hacer es correr el comando ese con strace

Da error ese comando al usarlo en Eclipse:
`[0mstrace: test_ptrace_setoptions_for_all: PTRACE_TRACEME doesn't work: Operation not permitted
strace: test_ptrace_setoptions_for_all: unexpected exit status 1`


En fin, sigo con el problemilla.
Datos que serán de vital importancia para la próxima temporada:
Esto sucede solo al debugear en Eclipse con las opciones "Non-stop mode" y "Automatically debug forked processes". Y solo sucede en transformación, en las otras etapas también uso el system() así y no aparece este problema...

Esto último lo acabo de detectar, pero ya estoy muy quemado como para seguir esa pista, quedará para el próximo capítulo. 

Gracias!

**Comment by gustofa** [comment]
ok, tengo novedades para este boletín.

Primero que nada, ignorar esto:

>  Y solo sucede en transformación, en las otras etapas también uso el system() así y no aparece este problema...

Mala mía, si sucede en las otras etapas al debuggear.

Por otro lado, resulta que encontré donde ver el trace del proceso. CHAN
y resulta que encontré la causa del problema. CHAN CHAN

Dentro de toda una parva de información que tira la traza, buscando por pid del proceso creado por system(), entonces esto:
`{id="15205\
",type="process",description="sh -c  cat /home/utnso/yama/bloque | sh /home/utnso/yama/script.sh | sort > /home/utnso/yama/resultado_tranformacion.txt",user="utnso",cores=["0"]}`

el tema está con ese `sh -c` que agrega antes del cat. Si ejecuto eso mismo por consola también se queda muerto!   wtf!   :scream:
En cambio, si ejecuto por consola la instrucción sin el `sh -c` corre perfecto y al instante.

Ideas?    se puede evitar que haga eso?    Estoy pasandole mal la instrucción a system()?

Ayuda.
Gracias!

**Comment by tferraro** [comment]
Prueba rápida: Fijate de que el string que estés armando tenga quotation marks, tipo `'cat /home/utnso/yama/bloque | sh /home/utnso/yama/script.sh | sort > /home/utnso/yama/resultado_tranformacion.txt' `

Si funciona, después te explico que onda :stuck_out_tongue:

**Comment by gustofa** [comment]
Esta noche lo pruebo!    Gracias!

**Comment by tferraro** [comment]
No le des pelota a mi comentario, acá (#926) ya demostré que no sirve 😛

**Comment by gustofa** [comment]
Por consola agregarle el entrecomillado a la instrucción funciona, pero desde eclipse debugueando no, sigue haciendo lo mismo...
Habrá soporte el sábado para ver este tema en vivo?

**Comment by gustofa** [comment]
Hola. Sigo sin resolverlo.
Por ahora optamos por comentar la instrucción system().

Me puse a probar este comportamiento en un proyecto limpio, con este código. Sigue pasando lo mismo.

`#include <commons/string.h>`
`int main(){`
`	int pid;`
`	char* instruccion = string_new();`
`	string_append(&instruccion,"ls -la > prueba.txt");`
`	if ((pid=fork()) == 0 ){`
`		printf("Proceso Hijo PID %d (PID del Padre: %d)",getpid(),getppid());`
`		system(instruccion);`
`		printf("despues del system");`
`	}else{`
`		printf("Proceso Padre %d",getpid());`
`	}`
`	return 0;`
`}`

Cuando debugeo con estas opciones activadas:
![debug_config](https://user-images.githubusercontent.com/4429106/32733986-81fb1790-c86f-11e7-88fb-c29ddd43a45f.png)

Desactivandolas system corre perfecto pero no puedo debugear el hijo...

**Comment by iruasi** [comment]
Bueno te comento, probé con ese código recién y me pasaba lo mismo, se queda ahi en el 'sh' hasta que lo mate a manopla... Peero pude hacerlo andar, para eso simplemente puse un breakpoint en el printf() del hijo, y una vez ahí dentro, saque el breakpoint y listo. Fijate si con ese yuyo te resolves los bardos en el Worker posta y ya podés seguir laburando.

**Comment by tferraro** [comment]
@gustofa me gusta la opción de @iruasi, seguis con este problema o le encontraste la vuelta?

**Comment by gustofa** [comment]
Hola. 
La verdad que no pudimos reproducir esa solución, pero bueno, cortamos por lo sano comentando la línea del system() cuando debugueamos worker...

Cierro el issue?

**Comment by tferraro** [comment]
Dale nomás :slightly_smiling_face:
