### ISSUE TITLE
[FileSystem] Tamaño máximo de archivos

### ISSUE THREAD

**Issue by FedericoVigi** [sisoputnfrba/foro#941]
Buenas, queríamos saber un tamaño máximo aproximado de archivo que vamos a manejar para las funciones *cat*, *cpfrom* y *cpto*,  ya que en FS trabajamos con los archivos cargados en memoria (por ejemplo para hacer un cat). 

Gracias :+1:

**Comment by mgarciaisaia** [comment]
> _en FS trabajamos con los archivos cargados en memoria (por ejemplo para hacer un cat)_

¿Elaborás un poco más? ¿Qué significa "los archivos cargados en memoria"?

**Comment by FedericoVigi** [comment]
@mgarciaisaia 
Si perdón, me refiero a que trabajamos con los archivos cargados en memoria principal; si por ejemplo voy a hacer un cat, obtengo todos los bloques de los nodos y los voy copiando con _memcpy_  en un buffer reservado con _malloc_, si los archivos que ustedes nos van a dar son de 1GB (por tirar un numero) ese _malloc_ va a intentar hacerse por 1GB cosa que no veo viable.  
Lo decidimos así porque en el primer checkpoint preguntamos por mmap y nos dijeron que era obligatorio para los databin pero el enunciado no aclara sobre el manejo de archivos para la interfaz de FS.

**Comment by tferraro** [comment]
Aprovecho par hacer una aclaración. Malloc vá (y va a poder) hacer una reserva de 1GB (incluso si las vms son de 1GB) por esas magias que les cuentan Adro, Esteban, Nestor, y demaces en la teoría 🙂 ; pero `mmap` tiene un limite posta, que es un cuasi-2GB, por el overflow de cierto tamaño de nro.

De todas formas, no van haber archivos de esa magnitud cerca del punto de corte, enfatizo el **no**. 

Archivos salvajes de 200-300Mb pueden llegar a aparecer, pero nada overkill que haga imposible testear (dentro del tiempo razonable que tenemos en el laboratorio), como 1GB.

**Comment by FedericoVigi** [comment]
> Archivos salvajes de 200-300Mb pueden llegar a aparecer, pero nada overkill que haga imposible testear (dentro del tiempo razonable que tenemos en el laboratorio), como 1GB.

Buenísimo @tferraro :+1:
