### ISSUE TITLE
[Master] Consulta sobre métricas

### ISSUE THREAD

**Issue by mtimossi** [sisoputnfrba/foro#942]
Buenas noches,

Con respecto a la parte del enunciado que dice:

> 2. Tiempo promedio de ejecución de cada etapa principal del Job (Transformaciòn, Reducción y Reducción Local). Can3. tidad máxima de tareas de Transformación y Reducción Local ejecutadas de forma paralela.

Entiendo que lo que se quiere es el máximo de tareas ejecutadas en forma paralelo y sin importar a que etapa pertenecen. Por ejemplo, si tuviéramos 3 tareas de transformación y 2 de reducción local corriendo en forma paralela esa cantidad se contaría como 5.
Es esto correcto? 

Saludos

**Comment by varas-c** [comment]
Hola,

En ese caso tenes 3 transformaciones en paralelo (como maximo) y 2
reducciones en paralelo (como maximo). El enunciado te pide discriminarlos
(o sea informar 3 y 2, no informar 5).

Ademas te pide el tiempo promedio de cada etapa. Si hubo 5 transformaciones
y cada una tardo 3 segundos, la etapa de transformacion duró 15.

Es "mas o menos" un promedio. No lo vamos a evaluar con un cronómetro ni
nada parecido. Con que el resultado mas o menos sea coherente, es
suficiente.

Cualquier otra duda pasate por acá de nuevo.

**Comment by mtimossi** [comment]
Perfecto, gracias!

**Comment by mtimossi** [comment]
Releyendo lo que hablamos me entro una duda sobre lo siguiente:

> Ademas te pide el tiempo promedio de cada etapa. Si hubo 5 transformaciones
> y cada una tardo 3 segundos, la etapa de transformación duró 15.
> 
> Es "mas o menos" un promedio.

Por lo que entiendo entonces, para calcular el tiempo promedio de una etapa tendríamos que hacer  la sumatoria del tiempo de ejecución de cada una de sus tareas?

**Comment by tferraro** [comment]
Buenas!

Eso es correcto!

**Comment by SantiagoFlynnUTN** [comment]
ah, no hay que dividir  la sumatoria por la cantidad de transformaciones hechas?

**Comment by tferraro** [comment]
Lei cualquier cosa, disculpen. Lei con detenimiento hasta lo que dijo Chris pero lo que no se termino de plasmar es que el habla de 3 etapas diferentes.

Pero si, si tenes 3 transformaciones que duraron 4 6 y 8, tu tiempo de la etapa es 6, es el promedio. No le den bola al comentario de arriba que le falta contexto.

**Comment by mtimossi** [comment]
Claro, me había llamado la atención que dijeran que el promedio era una sumatoria y por eso lo estaba repreguntando. Habiendo quedado claro que se trata de un promedio y no una sumatoria cierro el Issue. Saludos y gracias!

**Comment by marrtins** [comment]
Buenas, una consulta.. La cantidad de tareas en paralelo, por ejemplo de la transformacion.. Debería ser la cantidad de transformaciones, no? Porque el hecho de que cada worker haga un fork para cada solicitud que le llega, nos va a dar como resultado que se ejecuten todas juntas o no? sino de que otra forma puedo ver cuantas son en paralelo?
