### ISSUE TITLE
[Worker] - Se debe conectar a fileSystem?

### ISSUE THREAD

**Issue by pnmorrone** [sisoputnfrba/foro#943]
Buenas, 

Viendo la arquitectura del sistema y de lo que recuerdo de las charlas, Worker solo debía comunicarse con Master(o con otros workers) y este ser el nexo con las demás aplicaciones.
![image](https://user-images.githubusercontent.com/10654771/32549484-6fe1b196-c468-11e7-87d3-0ccb05ecaddf.png)

En la documentación del Proceso Master, cuando explica como hacer el almacenado final dice lo siguiente:
"El proceso Master entonces le solicitará al Worker encargado que se conecte al Filesystem y le envié el contenido del archivo de Reducción Global y el nombre y ruta que este deberá tener."
Por lo que entiendo que el Worker debería conectarse al Fileystem.

Por lo tanto debería conectarme a Filesystem desde Worker o no?

Muchas gracias.
Pablo.

**Comment by tferraro** [comment]
https://github.com/sisoputnfrba/foro/issues/844#issuecomment-327984968

**Comment by pmorrone10** [comment]
gracias.

**Comment by tferraro** [comment]
:pray: plz cerrá el issue si te sirvió la respuesta :wink:
