### ISSUE TITLE
Almacenamiento final - Worker y FS

### ISSUE THREAD

**Issue by DarkWood97** [sisoputnfrba/foro#944]
Buenas noches, tenia una duda, esta masomenos fue encarada en el issue #881 pero no me fue aclarada, worker trabaja solo con archivo de textos o puede trabajar con archivos binarios tambien? Es que en el comentario de ese issue decia que el job solo trabaja con archivos de textos y en almacenamiento final el FS me pide si o si que le envie el tipo de archivo (texto o binario).

Desde ya, muchas gracias.

**Comment by tferraro** [comment]
Buenas!

Los Jobs trabajan a nivel de archivos de texto, pero la especificación del FileSystem permite ambos. Por lo tanto, si tuvieras un Job-v2 que trabajara con archivos binarios con scripts medio locos, no debería haber diferencias fundamentales en el FileSystem.

Es _más_, el FS no sabe que los Jobs no toman como válidos el uso de archivos binarios, por lo que permite eso :slightly_smiling_face:

**Comment by DarkWood97** [comment]
Gracias por la respuesta!! Entonces no habria probema con el apareo de los archivos en este job v2? Es que yo en el apareo global, aparie agarrando hasta el /n de cada archivo

**Comment by DarkWood97** [comment]
Ah ya entendi! Duda resuelta, mil gracias!! Cierro issue.
