### ISSUE TITLE
Balanceo de contenido (FileSystem -> Datanodes)

### ISSUE THREAD

**Issue by gerosamore** [sisoputnfrba/foro#945]
Hola!
Probando el trabajo práctico, nos surgió una duda sobre el balanceo de contenido que tiene que hacer filesystem para guardar los bloques en los correspondientes datanodes. Nos surgieron varias ideas y las cito a continuación:

1. Primero habíamos pensado hacer una **cuenta de proporcionalidad** que consistía básicamente en la siguiente formula:
**proporción = bloquesOcupadosEnDatabin / bloquesTotalesDatabin**
De esta forma, se ordena una lista (que contiene los nodos conectados) por el que tiene la menor proporción (que es el que más espacio tiene en relación a su capacidad y sus bloques ocupados). Como ejemplo, si tenemos 3 nodos con los siguientes tamaños respectivamente: 20MB, 30MB, 50MB

_Primer Bloque: **(cuando son iguales, se eligen los primeros encontrados)**_ 
Nodo1: 0/20 = 0 --> Se manda la copia 0
Nodo2: 0/30 = 0 --> Se mando la copia 1
Nodo3: 0/50 = 0

_Segundo Bloque:_ 
Nodo1: 1/20 = 0.05
Nodo2: 1/30 = 0.033 --> Se mando la copia 1
Nodo3: 0/50 = 0 --> Se mando la copia 0

_Tercer Bloque:_ 
Nodo1: 1/20 = 0.05 --> Se mando la copia 1
Nodo2: 2/30 = 0.066 
Nodo3: 1/50 = 0.02 --> Se mando la copia 0

_Cuarto Bloque:_ 
Nodo1: 2/20 = 0.1 
Nodo2: 2/30 = 0.066 --> Se mando la copia 1
Nodo3: 2/50 = 0.04 --> Se mando la copia 0

...............(etc)

El tema de esta solución es que no es completamente exacto el algoritmo. Para citar un ejemplo, creamos 4 datanodes con los siguientes tamaños de databin: 20, 30, 50, 100. Intentamos hacer un cpfrom de un archivo de 100MB (caso límite) y lo que sucede es que se llenan completamente los nodos Nodo1 (20MB), Nodo2 (30MB), Nodo3 (50MB) pero el Nodo4 por un tema de cuentas, termina con 2 MB de espacio Disponible (tenía 100MB) y el último bloque no lo podemos enviar por que no se puede almacenar 2 copias en el mismo nodo.

2. La otra solución, un tanto más sencilla era primero almacenar los bloques en los datanodes que tengan más capacidad, y luego seguir con los más chicos (esto es lo que tenemos implementado ahora). Ejemplo con los mismos tamaños anteriores 20MB, 30MB, 50MB:
_Primer Bloque:_ 
Nodo1: 20MB
Nodo2: 30MB --> se manda la copia 1
Nodo3: 50MB --> se manda la copia 0

_Segundo Bloque:_ 
Nodo1: 20MB
Nodo2: 29MB --> se manda la copia 1
Nodo3: 49MB --> se manda la copia 0

_Tercer Bloque:_ 
Nodo1: 20MB
Nodo2: 28MB --> se manda la copia 1
Nodo3: 48MB --> se manda la copia 0

................

_Decimo Bloque: (cuando son iguales, se elige el primero encontrado)_ 
Nodo1: 20MB --> se manda la copia 1
Nodo2: 20MB 
Nodo3: 30MB --> se manda la copia 0

_Decimo Bloque:_ 
Nodo1: 19MB 
Nodo2: 20MB --> se manda la copia 1
Nodo3: 29MB --> se manda la copia 0

_DecimoPrimero Bloque:_ 
Nodo1: 19MB --> se manda la copia 1
Nodo2: 19MB
Nodo3: 28MB --> se manda la copia 0

......(etc)

El problema de esto es que la mayoría de copias se guardan en el databin mas grande, no se hace un buen balanceo (a nuestro criterio), pero nos funciona perfectamente y es un algoritmo fácil de implementar.

Queríamos saber cuales eran sus consejos, y si este tema es de mucha importancia, o estamos poniendo mucho énfasis en algo secundario.

**Desde ya, muchas gracias!**

**Comment by tferraro** [comment]
Buenas!

La primera opción es la más optima, justamente por eso que mencionás, que el _Balanceo no es bueno_. Una buena forma de mirarlo es el impacto que tendrían en un Job de YAMA:

Si lo hiciéramos sobre la opción 2, todas las transformaciones probablemente cayeran repartidas en 2 mismos nodos, cuando si se distribuye mejor, se puede distribuir de forma más efectiva la carga a posteriori en un Job.

**Comment by CarolinaPonceRodriguez** [comment]
Buenas, en mi caso aplique la segunda opcion teniendo en cuenta la simplicidad de la misma (tambien porque al momento, no se me ocurrio otra).  Si bien como dice @tferraro, los resultados de los jobs se repartirian al principio en los nodos de databin mas grandes, una vez que se "equiparen los numeros" podria elegir a los nodos restantes como victimas, es la forma en que yo lo veo.
Yo diria que es correcto que el balanceo sea lo mas adecuado, pero no creo que sea lo mas fundamental en el tp.
Espero no equivocarme, sino tendre que cambiarlo tambien jaja
Saludos!.

**Comment by tferraro** [comment]
> (...)Queríamos saber cuales eran sus consejos(...)

No está estipulado la forma que tienen que hacer el balanceo, mientras que sea efectivo. el algoritmo a usar corre por parte de ustedes.
- Es importante que sea efectivo? Totalmente.
- Es importante que todos hayamos elegido el mismo? No, la idea es que busquen por su propia cuenta lo que más les parezca
- Podemos pedir opiniones en función a como lo queremos implementar? _Siempre_, forma parte del proceso de aprendizaje y a eso estaba orientada mi respuesta
- Hace falta cambiarlo si encuentro uno que funcione mejor y me guste más? A gusto y piacere, mientras que TP funcione... :wink:

**Comment by tferraro** [comment]
@gerosamore que onda con esto? Te sirvió la respuesta?

**Comment by gerosamore** [comment]
Hola! 
Sí, perdón por no contestar. Estamos implementando un algoritmo que teoricamente funciona, pero tenemos que terminar de implementarlo, pero en definitiva sí, encontramos una solución. Cualquier cosa que no funcione o tengamos alguna duda, paso por acá.
Gracias !
