### ISSUE TITLE
Consulta entrada estandar scripts

### ISSUE THREAD

**Issue by marrtins** [sisoputnfrba/foro#946]
Buenas, mientras avanzaba con los workers, siempre fui probando ejecutar scripts con el archivo WBAN.csv como unico parametro quedandome una linea:
system(cat WBAN.csv | scriptreductorNodoX.sh > tmp1asd) .. etc

Ahora ya probando el tp, para cambiar ese wban con el bloque del binario que el worker va a leer me surgieron un par de dudas de como poner en esa linea del system el parametro, que sería el texto a reducir. 
(**primera pregunta**, siempre va a ser texto lo que reduzca el worker?)

Por ahora estaba probando y funcionaba, el hecho de que el worker con un mmap lea el bloque que necesita, luego con un memcpy y un par de cosas mas tenia en un char * todo el bloque del binario que me interesa. 

eso por el momento creo que esta bastante bien, si yo hago un printf("%s",linea) me muestra x pantalla todo lo que hay en el bloque.

Ahora la duda es, como hacer para que esa linea sea el parametro de los scripts? Lo unico que se me ocurrio por el momento es guardar la linea en un archivo temporal, y luego hacer cat de este, de la misma forma que haría cat WBAN.csv.. ¿Esto es valido?  De ninguna otra forma se nos ocurrio, y si bien anda por ahora, no se que otros tipos de datos puedan haber en el bloque del binario y podria dejar de funcionar esa solución que planteé.

Muchas, gracías martín

**Comment by tferraro** [comment]
Buenas!

Respecto a la primera pregunta: https://github.com/sisoputnfrba/foro/issues/881#issuecomment-333133848

Respecto a la segunda: lo ideal sería que no uses un archivo temporal, hay una forma bastante sencilla con `echo` :smile:. Lo que tendrías que probar es si hay problemas con ejecutarlo con system teniendo una línea muy larga. Si ves que trae problemas, avisame y lo vemos desde el lado del archivo temporal.

**Comment by marrtins** [comment]
Claro, ese es el tema me preocupa q pueda pasar con lineas largas y como no tengo para probar estaba yendo por lo seguro..

**Comment by tferraro** [comment]
Probablemente no tengas problemas por la longitud de la línea, dado que no debería pesar más que el bloque 🙂 . De todas formas, porque no tenés para probar? La prueba hace al maestro, aunque sea un mock 😉

**Comment by marrtins** [comment]
nono obvio que estoy probando con los scripts y el WBAN.csv que subieron de ejemplo, pero por ahi despues con otros datos de entrada u otros scripts cambiaba y ahi me iba a joder.
