### ISSUE TITLE
Duda formato archivo Reduccion Global

### ISSUE THREAD

**Issue by nicolasreyd** [sisoputnfrba/foro#947]
Hola, cómo andan?

Tenemos una duda respecto al formato de archivos que vamos a tener en la reducción gobal. 
Consideramos que saber esto es importante, ya que según el enunciado del tp el apareo es por **palabras** y antes de comenzar con la tarea tenemos que identificar estas **palabras** en un archivo.
Podrán darnos un ejemplo de archivo que leeríamos en esta instancia de la reducción?

Nuestra idea es enviar todas las palabras en un paquete al worker encargado, y que este último haga tantos recv() como palabras haya, para poder ir apareandolas a medida llegan. Esto puede ser una posible solución?

Saludos y gracias

**Comment by lepeg123** [comment]
Una palabra es una linea, porque debido al sort, esta todo dividido por lineas. Podes leer de a una linea para aparear

**Comment by DarkWood97** [comment]
Supongo que es como dice @lepeg123 yo lei de a una linea para aparear porque sino no tenes forma

**Comment by tferraro** [comment]
Lineas líneas!

**Comment by nicolasreyd** [comment]
Gracias a todos!
