### ISSUE TITLE
Eliminar key en Tabla de archivos

### ISSUE THREAD

**Issue by CarolinaPonceRodriguez** [sisoputnfrba/foro#948]
Buenas, tengo una duda sobre como eliminar una key con su contenido  en alguno de los archivos que corresponda a la tabla de archivos. Esto se da cuando se elimina un bloque con el comando rm, debo actualizarlo en dicho archivo. Se que no existe funcion de las config para esto, pero tampoco estoy muy orientada a como hacerlo. ideas?
gracias!

**Comment by CarolinaPonceRodriguez** [comment]
Para los ayudantes, voy a obtener respuesta o procedo a cerrar el issue y buscar el soporte necesario en otro lado? 

Saludos.

**Comment by epreyes** [comment]
Yo lo que pense para ese caso es reescribir el archivo de metadata con la lista de bloques ya actualizada. Sino otra (que no la probe) es probar hacer memcpy de \0 en el archivo mapeado.

**Comment by varas-c** [comment]
Buenas!

Mil disculpas, entre tanto mail se me pasó el tuyo. Lo que necesitás es
usando Config.h remover una key? Si es así, fijate que un Config tiene un
dictionary donde almacena los elementos. Config no tiene un remover, pero
dictionary si.

Podrías implementar algo asi:

void config_remove_key(t_config *, char *key) {
        dictionary_remove(t_config -> dictionary, key)
}

A eso te referías? Otra vez, disculpá la demora 🙁

**Comment by CarolinaPonceRodriguez** [comment]
Buenas!
Mil gracias, lo probe y va perfecto, mucho mejor que recorrer todo el archivo como una desgraciada.

Pd: Son varios los ayudantes, la responsabilidad no tiene por que recaer sobre uno solo.

Saludos y cierro!
