### ISSUE TITLE
Guardar tabla de estados?

### ISSUE THREAD

**Issue by SantiagoFlynnUTN** [sisoputnfrba/foro#949]
Buenas, nos surgió la duda de si es necesario en algún momento hacer un volcado de la tabla de estados en un archivo, o mostrarla por pantalla para hacer un seguimiento de las operaciones el día de la entrega.
O simplemente alcanza con ir logueando cada entrada que se genera?

**Comment by tferraro** [comment]
Buenas!

Cuanto más expresivo sea su tp, mejor; tanto para poder analizar su funcionamiento en la entrega, como para que ustedes puedan probarlo con más facilidad.

Saludos!
Tom

**Comment by SantiagoFlynnUTN** [comment]
Ok, gracias!

cierro.
