### ISSUE TITLE
Hilos para comunicacion en reduccion global

### ISSUE THREAD

**Issue by lepeg123** [sisoputnfrba/foro#950]
Hola a todos,

Estaba leyendo en el enunciado sobre el tema de solo usar fork (y no hilos) en Worker, pero tenia una duda sobre si eso solo aplicaba para atender las solicitudes de Master y si se podia tambien manejar la comunicacion del Worker encargado hacia el resto de los workers con hilos para cada uno de los distintos workers. 
Dejo adjuntada la parte del enunciado de la que hablo.
Gracias!
![screenshot from 2017-11-19 21-45-34](https://user-images.githubusercontent.com/12883708/32997839-dca6364e-cd73-11e7-842b-77bed18f85f7.png)

**Comment by DPoma** [comment]
Me sumo a la pregunta!

**Comment by tferraro** [comment]
No! No se puede usar hilos en ninguna parte del proceso Worker.

De todas formas, no podrías tener alguna función que hiciera homogéneo y que diferencie al momento de ejecutar el comportamiento particular de cada caso, sea Master o otro Worker? Esto tiene un nombre loco que a la gente de diseño les gusta llamar _strategy_ 😉

**Comment by lepeg123** [comment]
Lo tenia planteado como decis igual, pero pregunte por si acaso. Gracias!
