### ISSUE TITLE
Duda con script en reduccion global

### ISSUE THREAD

**Issue by DPoma** [sisoputnfrba/foro#951]
Hola, tengo una duda con respecto a la reduccion global.
Estoy haciendo pruebas utilizando el repo yama-test1 y me dice que puedo ejecutar este comando para probarlo

`cat WBAN.csv | ./transformador.sh | sort | ./reductor.pl`

Segun mi interpretacion si hago esto:

`cat WBAN.csv | ./transformador.sh | sort | ./reductor.pl > resultado`

El archivo "resultado" seria la salida "oficial", el cual deberia ser igual al archivo que voy a guardar en yamafs en el almacenado final (si comparara los md5 deberian ser iguales).

Segun lo que vi en el script de reduccion es que espera un input tipo `DATE;WBAN;TEMP;TIME` (que son los registros de los temporales de transformacion) y genera `DATE;WBAN;MAX_DAILY_TEMP_IN_WBAN;TIME_OF_MEASUREMENT` (que son los registros de los temporales de la reduccion local), en el caso de la reduccion local todo bien porque le voy a pasar al script el archivo resultante del apareo de todos los temporales de transformacion del nodo por lo tanto le envio entradas para que me genere salidas distinta. 
Ahora una vez que terminaron todas las reducciones locales inicio la reduccion global por lo tanto tengo que aparear todos los temporales de las reducciones locales, supongamos que lo guardo "archivoApareo" cuando le pase  "archivoApareo" al script de reduccion podriamos decir que le estaria pasando inputs `DATE;WBAN;MAX_DAILY_TEMP_IN_WBAN;TIME_OF_MEASUREMENT` para que genere lo mismo `DATE;WBAN;MAX_DAILY_TEMP_IN_WBAN;TIME_OF_MEASUREMENT` 
No se si tendra efecto alguno o hace alguna cosa extra de la que no me estoy dando cuenta.

Basicamente mi duda es que en la reduccion global, una vez que termine de aparear todos los temporales de las reducciones locales, ya tendria un archivo igual a "resultado", por lo tanto no estaria entendiendo porque hay correr el script de reduccion nuevamente y ademas si lo corro le estaria pasando entradas para que me genere salidas iguales.

**Comment by tferraro** [comment]
Buenas!

Por lo que te logré entender, tu consulta es: ¿Para que hacer la reducción global?

Imaginate que tenés el archivo partido en pedacitos (_una analogía pedorra para decir que lo tenemos dividido en bloques_), y un par de líneas del 23/11/2017 te quedan en una parte y el resto en la parte siguiente, te daría igual que si tuvieras todo junto?

Fuera de eso, los scripts/datos son cajas negras, **no** (y enfatizo ese no) tienen que entender que hacen, ni como lo hacen, solo que respetan la interfaz que vos tenes definida con ellos ante las transformaciones y reducciones. Pasándolo a térmicos más académicos, como definirías las firmas de las transf. y reducciones según lo que conocés sobre el TP y lo que vieron en paradigmas?

Saludos!
Tom

**Comment by DPoma** [comment]
Si, entiendo el objetivo de la reduccion global, lo que me hacia ruido era lo que hacia ese script en particular pero bueno si no es algo por lo que tenga que preocuparme, ni me molesto en tratar de entenderlo, solo lo corro y listo, gracias!
