### ISSUE TITLE
Consulta replanificacion

### ISSUE THREAD

**Issue by marrtins** [sisoputnfrba/foro#952]
Buenas, probando un poco manejar errores de los workers se me dio un escenario que no habia manejado en ninguna prueba y no se que tan posible puede ser que suceda, porque en la consigna no vi nada por el estilo, pero bueno..

Resulta que yo tengo un archivo con bastantes bloques divididos en 3 nodos, comienza la etapa de transformacion 20 transformaciones para cada worker y a la transformacion nro 10 mato el worker2.. 

Lo que me esta pasando es que las primeras 10 transformaciones que el w2 realizo, salieron ok y ya le avise a yama que esta todo ok. las siguientes 10 van a fallar, le avisaré a yama, las replanificara y esos ultimos 10 bloques los transformara worker1 o worker 3. El tema es que tendria que hacer con las 10 que salieron bien pero ya no estan disponibles para pasarlas en la reduccion local, ya que el worker que las realizo murio?... Tengo que replanificar las 20 tareas de una? o esas las dejo pasar y bueno el resultado final estará incompleto?

gracias

**Comment by lromano97** [comment]
Según tengo entendido, el no replanificar las que salieron bien llevaría a que falle la reducción local en la siguiente etapa, dado que al no tener el worker disponible, tampoco vas a tener los temporales. Discutiéndolo con uno de mis ayudantes termine replanificando todas las tareas del nodo que fallo.

**Comment by DarkWood97** [comment]
Concuerdo plenamente con ironman97, no tendria sentido replanificar por bloque, se tiene que replanificar el nodo entero

**Comment by tferraro** [comment]
Buenas!

Es una buena aproximación la que comentan.
Si bien puede pasar que 1 transformación falle y el Nodo siga activo; hay muchas más probabilidades de que una transformación que terminó primero se informe como OK y luego el Nodo se caiga antes de terminar las demás. En ese caso sería incorrecto no re planificar todas no?

Al ser un escenario muy border, está bueno tomar una solución de compromiso como la que plantean bajo la contrapartida de capas tener que volver a planificar transformaciones con resultados que eran accesibles y usables.

Saludos!
Tom

**Comment by marrtins** [comment]
claro, yo siempre pensé eso pero seguí lo que planteaba el enunciado que era replanificar solo las etapas que fallaron...

Lo dejo asi o replanifico todo el nodo de una?

**Comment by tferraro** [comment]
Mientras que el resultado sea el mismo a fin de cuentas, tomen la solución de compromiso que quieran. Pero tomá en cuenta que si solo replanificás los que fallan, de chequear si el nodo está caído o no; porque sino va a diferir el resultado.
