### ISSUE TITLE
malloc(): memory corruption

### ISSUE THREAD

**Issue by guillelle** [sisoputnfrba/foro#953]
Hola,

tengo problemas de memory corruption ocasionalmente y por lo que deduzco es de acuerdo al valor que le paso al malloc, o sea, depende de la cantidad de memoria que deseo. En principio pensé que sería un problema de que no pueda darme esa cantidad, pero en ese caso el malloc devuelve null y no es el caso, simplemente explota.
De todas formas NO es un problema de que no encuentre esa cantidad de memoria libre porque le pido más y sí me la asigna, ejemplifico para clarificar

```
char *malditoArray = malloc(31);  --- rompe
char *malditoArray = malloc(43);  --- funciona
char *malditoArray = malloc(65);  --- rompe
char *malditoArray = malloc(87);  --- rompe
char *malditoArray = malloc(120);  --- funciona
```

les digo más... eso lo estoy haciendo dentro de una función y me da error, no dentro del main, en el main, en la primer línea del main, NINGUNA de las pruebas anteriores genera error. Incluso puestos uno abajo de otro de la siguiente forma:

```
char *malditoArray1 = malloc(65);
char *malditoArray2 = malloc(87);
char *malditoArray3 = malloc(31);
char *malditoArray4 = malloc(120);
```

gracias
saludos

**Comment by mgarciaisaia** [comment]
@guillelle ¿qué dice [`valgrind`](https://faq.utnso.com/valgrind) al respecto?

**Comment by guillelle** [comment]
con el valgrind tengo un problema, no me muestra el número de línea donde detecta algo, entonces no se exactamente si me decía algo sobre ese problema en particular, sí me decía que tenía problemas de memoria en varios lugares que usaba strcpy que los pude identificar porque muestra la línea del código.
En fin, luego de tu pregunta @tferraro sobre qué decía el valgrind quise hacer un printscreen para que lo vean y me encuentro con que no falla más, todo lo que expliqué antes ya no sucede, no pude ni siquiera forzar el error para obtener la respuesta del valgrind. 
Yo no se si se alinearon los planetas u otros arreglos que hice en mallocs y frees, que estaban mal y el valgrind me los marcaba, en otras partes del código influyeron para que se arreglara esto pero bueh... por el momento dejamos el issue acá y sigo con otras cosas, si me sucede de nuevo vuelvo con la info del valgrind

gracias
saludos

**Comment by tferraro** [comment]
Buenas!

Si valgrind no te muestra el nro de linea, es probablemente porque tu ejecutable no fue compilado con los flags de debug, que evitan ciertas optimizaciones y dejan el detalle de los nros de linea, entre otras cosas, para poder debuggear tranquilo. Esencialmente, hay que compilar con el flag `-g` de gcc.

Cuando existe un problema de memory corruption, por lo general, donde explota el proceso no suele ser donde uno se mandó una macana. De ahí que Mati te pidió que nos muestres que decía Valgrind.

Más allá de eso. Pudiste solucionarlo de alguna forma no? Podrías contarnos cuando lo encuentres? El issue se puede cerrar?

Saludos!
Tom

**Comment by tferraro** [comment]
Holis de nuevo 🙂 

Algo con lo que no me expresé bien en el mensaje anterior, es que @guillelle no cuelgues con el error, tenés idea de como se solucionó momentáneamente? Si bien es más importante que le den robustez al tp, también lo es tener en cuenta estos casos, porque puede ser que al correr las pruebas vuelva a pasar porque no tenés bien definido que hiciste.

Nada, ponele a eso, pero no cuelgues con eso y en comentarnos que fue lo que anduviste haciendo.

**Comment by tferraro** [comment]
@guillelle up up!  Que onda esto? Como lo solucionaste? :slightly_smiling_face:

**Comment by tferraro** [comment]
Por inactividad cierro el issue, cualquier cosa abrilo de nuevo..o contanos como lo solucionaste! 😄
