### ISSUE TITLE
Pruebas?

### ISSUE THREAD

**Issue by SantiagoFlynnUTN** [sisoputnfrba/foro#954]
Buenas, estamos a 3 días de la entrega final y dado que no han subido pruebas quería saber más o menos qué escenarios deberíamos estar listos para bancar con el tp.

Estamos tratando de tener en cuenta todos los posibles fallos y situaciones que se puedan dar. Pero estamos seguros que más de una cosa se nos puede estar escapando y no queremos esperar al viernes a la noche para que rompa y tengamos que desvelarnos buscando errores difíciles de detectar.

Les agradezco de antemano cualquier aporte.

Saludos!

**Comment by tferraro** [comment]
Buenas!

Estamos terminando de pulir algunos temas que surgieron sobre los scripts, por un tema de versiones entre los intérpretes.

Les pedimos paciencia (y disculpas!) y en el transcurso de la mañana (mediodía a más tardar) las publicamos!

Saludos!
Tom

**Comment by mgarciaisaia** [comment]
Para que no les digan, y no les cuenten, [acá están las pruebas](https://www.utnso.com/documento-de-pruebas-2c2017/).

¡Un abrazo!
