### ISSUE TITLE
Dudas menores respecto a los nodos

### ISSUE THREAD

**Issue by DPoma** [sisoputnfrba/foro#955]
Hola, tengo unas pequeñas dudas de cara a la entrega

1) Supongamos que un nodo esta corriendo, si mato el datanode, deberia morir su worker correspondiente para simular la "muerte" de un nodo? O pueden ser independientes?
Si deberian morir ambos a la vez (caso contrario ignorar esto) como seria la parte de comunicacion, porque digamos que muere un datanode, el FS se entera y le avisa a yama y este solo podria comunicarse con el worker si hay un Master de por medio, el cual puede estar o no. A menos que el worker este conectado durante toda su vida con el FS, pero segun tengo entendido solo se conecta para el almacenado final nada mas. Tampoco podria ser que el datanode le avise al worker ya que solo comparten el databin, ninguno sabe de la existencia del otro.

2) El data.bin es "fijo" para un nodo o podria llegar a cambiar en tiempo de ejecucion? 
Ejemplo: Levanto un nodo con "data1.bin", lo desconecto, ahora por archivo de configuracion le paso "data2.bin", lo vuelvo a levantar, el FS deberia tomarlo sin problemas? Yo creo que si este caso fuera posible si o si deberia hacer un format para actualizar las estructuras como el bitmap, nodos.bin ya que el tamaño del data.bin posiblemente sea distinto.
En caso de que fuera "fijo" solo podria cambiar el data.bin si levanto el FS ignorando el estado anterior (--clean), ya que en ese estado puede conectarse cualquier nodo con cualquier data.bin y una vez que tiro el format queda todo "fijo" hasta la proxima vez que ejecute con --clean no?

3) Un nodo siempre se ejecuta en la misma maquina o puede cambiar en tiempo de ejecucion? Como el nodo tiene un nombre que lo identifica quizas la ip y el puerto podrian cambiar tranquilamente, por lo tanto cada vez que se reconecta un nodo deberia fijarme si la ip y el puerto cambiarion (esto punto creo no tendria sentido ya que si cambio de maquina, deberia "trasladar" el databin a la nueva maquina, pero lo pregunto por las dudas).

Quizas algunos casos sean muy rebuscados, pero bueno quiero validar todo lo que se me ocurra para que luego no hayan "sorpresas".

**Comment by tferraro** [comment]
Buenas!

1 - Si matas a un Worker/DataNode, tenes que matar manualmente también a su contraparte, dado que no hay comunicación entre ellos.
2 - No cambia en tiempo de ejecución, ni si el FS ya está formateado.
3 - Los Nodos podrían moverse, pero dependerá de la implementación particular que hayan hecho. La identificación base debería ser por el nombre del mismo no por la IP. Pero a esta altura del cuatrimestre, no es algo en lo que les diría que le pongan atención.

**Comment by DPoma** [comment]
Listo, gracias por la rápida respuesta!
