### ISSUE TITLE
Duda etapa 4 - Documento de pruebas

### ISSUE THREAD

**Issue by CarolinaPonceRodriguez** [sisoputnfrba/foro#956]
Buenas, 

Tengo una duda con respecto a la siguiente parte del enunciado en la etapa 4: 
"Finalmente, haciendo uso del copiar-pegar, crear 94 directorios dentro de /directorios, y
validar que no es posible crear otro más. Luego, formatear el yamafs ​nuevamente y validar
que las estructuras administrativas se han eliminado y no hubo mensajes a los Nodos."

A que se refiere con "copiar-pegar" exactamente? 
1) Si se refiere a hacer copy-paste del comando mkdir de la consola no seria tan acertado  porque si yo copio "mkdir /directorio/directorio1" la primera vez lo crea, la segunda no porque ya directorio cuenta con directorio1
O hay otra opcion que no estoy contemplando? 

Saludos!

**Comment by epreyes** [comment]
Entiendo que copiarian al portapapeles 94 comandos que copien 94 directorios diferentes y ejecutarian en forma masiva, el tema es que para una consola sin readline no funcionaria

**Comment by CarolinaPonceRodriguez** [comment]
Igual la consola con readline tampoco lo acepta, yo busque emular el funcionamiento de una consola comun y corriente, ingresas un comando lo ejecutas, ingresas otro y asi, no considere una opcion masiva porque no esta requerido en el tp.
Como se resuelve? 
Saludos.

**Comment by iago64** [comment]
Buenas!

Lo que quiere decir la prueba es que uds puedan hacer:

mkdir /dir/dir1
mkdir /dir/dir2
....
mkdir /dir/dir94

y que para que tengan que escribir todo sea algo asi como:

mkdir /dir/dir y despues sea algo asi como:

Ctrl + V --> apretar el numero --> apretar Enter
Asi hasta que no puedan mas porque llenaron el FS

Saludos.-

**Comment by CarolinaPonceRodriguez** [comment]
Buenas, gracias por la respuesta.
Entiendo que la idea de la prueba es que valide que no se puedan crear mas de 100 directorios. Pero no es un desproposito esto? No resta al dinamismo que se pide para presentar el tp? 
En mi caso tendria dos opciones:
1) Podria en el codigo modificar un define que tengo que indica la cantidad de directorios del fs
2) Crear otro comando que  por ejemplo, lea de un archivo los directorios y por cada uno ejecute el mkdir de mi consola.

Gracias por la respuesta.
Cierro.

**Comment by mtimossi** [comment]
También se podría agregar otro comando que ejecute n veces el de mkdir sino nos vamos a volver changos haciendo copy paste je
