### ISSUE TITLE
[Master] Pruebas - Detalle 

### ISSUE THREAD

**Issue by mtimossi** [sisoputnfrba/foro#957]
Hola!

Observando la hoja de pruebas veo que a diferencia de otros procesos no hay cargado un detalle para el Proceso Master. Esto es así intencionalmente?

Saludos!

**Comment by tferraro** [comment]
Buenas!

A que te referís que no hay detalle del Proceso Master? Existe un título con el label `Configuración de los Master` que muestra que archivos se tendrán que usar durante la ejecución. A eso te referías?

**Comment by mtimossi** [comment]
Buenas Tom,

Me refiero a a que la grilla de máster no tiene ítems de detalle:

Para la aprobación un Trabajo Práctico deberá contar con todos los ítems marcados como
“Contenidos​ ​Mínimos​”.
Una vez alcanzada la aprobación, los ítems marcados como “Detalle” tienen un valor
asociado que suman puntaje en caso de ser cumplidos, teniendo como base la nota 6 (seis)
y como máximo la nota 10 (diez).

Entiendo que podría estar bien que no haya ítems de detalle para Master pero quería asegurarme que no se haya pasado.

Saludos!

**Comment by iago64** [comment]
Matias, efectivamente, en el caso del Master no hay puntos de Detalle, no te preocupes por eso :)

Saludos.-

**Comment by mtimossi** [comment]
Gracias!
