### ISSUE TITLE
Dudas sobre las pruebas

### ISSUE THREAD

**Issue by DPoma** [sisoputnfrba/foro#958]
Hola, al leer el documento se me presentaron las siguientes dudas:

Etapa 3:
> Corroborar que se cumpla el orden de las etapas en cada Job y la existencia de los
archivos temporales en el yamafs.

1) Con archivos temporales supongo se refiere a los resultantes de las transformaciones y reducciones, pero cuando dice "en el yamafs" a que se refiere, a la carpeta de metadata? porque yo ahora lo guardo en una carpeta "temp" en el escritorio del FS local. Tampoco creo que haga referencia a guardar temporales en los data.bin ya que los workers solo leen.

Etapa 4:

> Se iniciará nuevamente el yamafs con el flag de limpio. Validar que se han eliminado las
estructuras administrativas. Conectar sus correspondientes nodos y formatear dicho
filesystem

2) Cuando dice "Conectar sus correspondientes nodos" supongo que se podría conectar cualquier cantidad de nodos  ya que como aun no se formateo no hay un limite, recién cuando escriba "format" pasaría a tener una cantidad fija de nodos (que son los que estaban conectados al momento de ejecutar el comando).

> Copiar el archivo txt_grande.txt en el directorio prueba y validar que todos los bloques estén
asignados. Renombrar​ ​el archivo /prueba/txt_grande.txt a txt_procesado.txt.

3) Los archivos "txt_grande.txt" y "txt_chico_txt" están subidos en algún lado porque no los encuentro en ninguna parte, cuando menciona a txt_grande.txt este esta subrayado, puede ser que se hayan olvidado de poner el link? O quizás estos archivos solo se utilicen durante la entrega?

> Finalmente, haciendo uso del copiar-pegar, crear 94 directorios dentro de /directorios, y
validar que no es posible crear otro más.

4) Según lo que tenia entendido hacer un format y ejecutar con --clean es casi lo mismo (ya que ambos te reinician las estructuras administrativas, por lo tanto perdiste todo lo que tenias archivos,directorios , nodos, etc). 
Si esto fuera cierto en esta etapa pide ejecutar el FS con --clean entonces los directorios /base, /out/, out/job1, out/ job2 (de la etapa 1) se eliminarian quedando 99 directorios disponibles (1 siempre esta ocupado por el root, segun el ejemplo del enunciado). Por lo tanto a partir de este momento según la prueba tengo que crear los siguiente directorios:
/pruebas (+1)
/pruebas/data (+0 porque se crea y se elimina)
/directorios (+1)
/directorios/1 ... /directorios/94 (+94)
En total crearía 96 directorios y  me quedarían 3 (100-96-1) directorios disponibles así que cuando cree otro directorio me va a dejar hacerlo tranquilamente. 
Si lo que digo esta mal no estaria entiendo que hace el --clean y que hace el format.

**Comment by tferraro** [comment]
Buenas!

1 - No fue la forma más feliz de describirlo. Es como decís, en el FS local.
2 - Precisamente
3 - Con la idea de no perder más tiempo, esto salió a la gran Ubisoft. Que los bugs los encuentren los usuarios(?). Chistes aparte, pueden haber quedado discrepancias en la redacción por partes viejas de las pruebas, como es este caso (y el del 4). Para el txt_grande correspondería al nombres.csv completo y el txt_chico a alguna de sus contraparte dividida.
4 - Idem a lo de arriba, si, son 96, no no 94.

En breve actualizo el doc así estos cambios no se pierden 😉 y gracias totales por los detalles.

Saludos!
Tom

**Comment by DPoma** [comment]
De nada! ahora si me quedo mas tranquilo, cierro.
