### ISSUE TITLE
Consulta Apareo Global

### ISSUE THREAD

**Issue by marrtins** [sisoputnfrba/foro#959]
Buenas, estoy con una duda con el tema de lo que estaría tardando el apareo global.. 

Estoy usando los tests que nos dieron, y para la transformacion del script transformador.pl .. con los datos reducidos (el archivo de 33mb) el apareo global tarda muchísimo y no se si esto esta bien que suceda...

De la forma en que yo lo planteé (que es supongo la que habia que llevar) es que cada worker me pase de a 1 linea de texto, (en este caso de a 1 nombre) y ahi hago la comparacion entre todos los nombres, escribiendo el menor y pidiendole al worker que me pasó ese nombre alfabeticamente menor que me pase otro y asi todo el tiempo..

Si fuera así, con las listas larguísimas de nombres, resultado de las reducciones locales de cada nodo (aprox 5mb cada una), el apareo se me hace como mencioné antes bastante largo.. ¿Es la idea?

Gracias

**Comment by iago64** [comment]
Buenas!
Los tiempos óptimos no los tenemos calculados, ya que no conocemos todas las posibles implementaciones, de todas formas no deberia ser algo excesivamente largo ya que estamos hablando de 4 archivos.

Como dato no menor, hay que tener especial cuidado al probar el TP por WiFi, porque las redes WiFi son mas lentas y mas aun con los routers que dan las empresas (Telecentro, Fibertel, Telefonica, etc) que no son puntualmente equipos mas rapidos rapidos del mercado. 
Con lo cual como consejo seria recomendable que las pruebas las hagan _de ser posible_ por red cableada para no tener retardos en cuanto a la red.
Otra cosa importante es que si corren todo en una misma maquina, es muy posible que los workers empiecen a competir entre si por el único procesador de la VM, con lo cual ahí tendrían otro posible cuello de botella :(

**Comment by marrtins** [comment]
aparentemente el problema era correrlo todo en una misma máquina. No tenia idea que podía pasar eso, en red tardo menos de la mitad. Estaba desesperando, gracias!
