### ISSUE TITLE
Test Worker Apareo

### ISSUE THREAD

**Issue by nicolasreyd** [sisoputnfrba/foro#960]
Buenas noches, 

Quería consultar sobre el test del Worker que dice:
"_Los archivos de cada operación de reducción local y global se aparean antes de comenzar las mismas_"

Se refiere a que antes de **ejecutar los scripts** se deben aparear los archivos? De otra forma no tengo forma de saber desde el Worker esto antes de que empiece cada etapa.

Saludos

**Comment by iago64** [comment]
Aloha!

Efectivamente, lo que quiere decir es que uds primero aparean los resultados del transformador, o de las reducciones locales, y después ejecutan el script de reducción.

Slds.-

**Comment by nicolasreyd** [comment]
Muchas gracias
