### ISSUE TITLE
Consulta bitmap

### ISSUE THREAD

**Issue by nicopatronelli** [sisoputnfrba/foro#961]
Buenas, molesto con una consulta: ¿Es obligatorio que el bitmap de bloques disponibles de los nodos este implementado utilizando las funciones de bitarray de las commons? ¿O es posible implementarlo utilizando un vector de enteros, por ejemplo? Nosotros, por ahora, lo tenemos hecho de esta última manera. 

Pregunto, básicamente, por si nos dan un estado anterior donde FILESYSTEM deba reconocer el bitmap de un Nodo y el mismo este basado en las funciones de bitarray. 

Gracias!

**Comment by tferraro** [comment]
Buenas!

No es casualidad que se pida que sea un bitmap y no un array de enteros. Las commons son solo una simplificación para su uso.

La razón atrás de todo esto viene por el mismo lado de porqué se usa en el exFAT, cual es la unidad más chica que podes tener para saber los bloques libres y ocupados? Tiene sentido que tu metadata, por una mala elección de tamaños, termine siendo sustancialmente grande, alcanzando el tamaño de la data? Ahí hay algo que no suena bien, no?

No es obligatorio el uso de las commons para manejar el bitmap, pero _si que sea un bitmap_.

Saludos!
Tom
