### ISSUE TITLE
Eclipse- cannot insert breakpoint ..

### ISSUE THREAD

**Issue by CarolinaPonceRodriguez** [sisoputnfrba/foro#962]
Buenas, 
Tengo la siguiente consulta, estos ultimos dias tuve problemas para debuggear porque me sale el siguiente error al insertar algun breakpoint:

![2017-11-23-230137_1920x950_scrot](https://user-images.githubusercontent.com/11802137/33192666-e7d47dbe-d0a2-11e7-9d76-5041b260db9b.png)

Dice que no se puede acceder a XXXX direccion de memoria. No muere ninguno de los procesos involucrados, pero no me deja seguir debuggeando, por otra parte, al ejecutar normalmente pasa.
Para entrar un poco mas en contexto, el codigo pertenece al filesystem y lo que estoy probando en este caso es levantar dos nodos, ejecutandolos normalmente y luego proceder a debuggear la funcion que atiende al proceso YAMA.

Seria posible que fuese algun leak de memoria que interviene en este caso? 

Saludos.

**Comment by CarolinaPonceRodriguez** [comment]
Al parecer me ilumine luego de armar el issue, lo que generaba el error era que tenia activada la opcion Non-stop mode del debugger y al marcar un breakpoint esta haciendo exactamente lo que se busca que no haga que es frenar la ejecucion en algun punto determinado. Al menos asi lo entendi yo.

Saludos!.

**Comment by mgarciaisaia** [comment]
¡Muchacha!

Fijate que, al menos en el screenshot que subiste, el proceso que Eclipse está intentando debuggear es el `sh` (con PID 7777). Dado que `sh` (`/bin/sh`) es un programa que viene en el sistema, ya compilado, que no incluye símbolos de debug, al debugger le cuesta attachearse. _Además_, los breakpoints que tenés configurados en Eclipse son para tu código (ponele, la línea 362 del FileSystem.c de tu proceso FS, o su equivalente ~mexicano~ compilado), y entonces _ni a palos_ van a aparecer esas ubicaciones en el proceso `/bin/sh`.

Suena razonable todo esto, ¿no?

La pregunta del millón es por qué Eclipse está queriendo debuggear un `sh`.

¿Se te ocurre?
