### ISSUE TITLE
Consulta reducciones y resultado md5

### ISSUE THREAD

**Issue by kevdorfman** [sisoputnfrba/foro#964]
Estamos con un par de problemas con worker y el resultado de los md5.. 
Lo que pasa es lo sig: durante todo el cuatri hicimos las pruebas con wban, siempre siguiendo la transformacion de cada bloque con el sort, despues el apareo del nodo, la reduccion del nodo, el apareo global y una reduccion mas y eso nos estaba dando siempre el mismo resultado..

Ahora desde el miercoles con las pruebas que subieron, hay algo que no se si me estoy comiendo o qué pero el md5 da otra cosa a lo que deberia dar. El (el export lc_all=c se hizo, no es eso).
Despues de mucho putear, fuimos agarrando los temporales a mano y realizando todos los pasos desde la consola, y lo que nos pasa es que si no hacemos la reduccion local, es decir apareo local del nodo, lo mandamos al apareo global y por ultimo reducimos ese apareo global si funciona y el md5 da igual, en cambio haciendo las 2 reducciones, el md5 da distinto. Y es mas, el resultado final termina siendo mas grande en tamaño que el del apareo global.

Quería ver si alguien podía darnos una mano o si tenia idea en que podiamos estar pifiando, porque debe ser una pavada pero no lo estamos viendo y es lo que nos falta para cerrarlo!

**Comment by tferraro** [comment]
Buenas!

Por la interfaz que tiene, _deberían_ ser iguales. Incluso si al resultado le corrés una reducción, no debería cambiar.

Pues, pasa que tenía un bug el script :disappointed_relieved: , así que te pido que te bajes de nuevo los scripts y lo pruebes, que _ahora deberían funcionar...mejor_.

Cualquier cosa chiflanos.
Tom
