### ISSUE TITLE
consulta apareo

### ISSUE THREAD

**Issue by marrtins** [sisoputnfrba/foro#965]
Buenas, estamos con unas consultas con el tema del apareo..

Como ahora se da que dura bastante cada apareo, al ejecutar 2 jobs en simultaneo se nos da la cuestión de si los apareos hay que hacerlos en simultaneo o no.. Ya que por ahora, como no podemos usar hilos en los workers, hacemos de a 1 apareo a la vez y lo que sucede es que:
job 1 inicia apareo, mientras esto sucede, llega la solicitud del job 2 para iniciar la reduccion global. una vez finalizada la reduccion global del job1, inicia la reduccion global del job2.. en ese momento llega a worker la solicitud para iniciar el almacenamiento, el cual no se da hasta que se termine el apareamiento del job2..

La cuestion es, si para el apareo los workers no encargados estén exclusivamente pendientes de ir mandando mensajes al encargado o si tienen que ir mechando ese paso de mensajes con hacer otras tareas que otros jobs le soliciten? 
En caso de que se así, tendriamos que realizar el apareo global desde el lado del encargado en el proceso hijo de este, sino se trabaría todo. El encargado esperando que le manden las lineas pero a su vez el otro encargado esta esperando que el resto tambien le mande las lineas..

**Comment by tferraro** [comment]
Buenas!

La ejecución de cada Job es independiente del otro, justamente por eso no aplica un algoritmo de planificación tradicional, porque la ejecución de un Job en un Nodo _no es un recurso que se puede retener_ (entre otras cosas). Esto aplica para cada etapa de los Jobs, sea transformación, **o sea el apareo**.

Si no podés usar hilos, que otra alternativa se te ocurre?

Saludos!
Tom

**Comment by marrtins** [comment]
Claro, lo que pensamos ahora es que el apareo se haga directo en el proceso hijo. Así estaria haciendo varios en paralelo. No se porque teniamos planteado hacerlo afuera, sería asi, no?

**Comment by tferraro** [comment]
Algo así, sí. Tenés que dividir las responsabilidades correctamente y mantener cierto nivel de cohesión. En este caso, el proceso padre solo tendría que tener una única responsabilidad, cual? Todo el resto estaría demás, debería estar delegado a sus hijos.

**Comment by marrtins** [comment]
recibir la info de la tarea que va a ejecutar, no? ahora estoy probando todo y anda mejor el paralelismo, obviamente se hace mas lento el promedio de la reduccion global al hacer las 4 al mismo tiempo pero bueno eso es lógico. Hay un rango de tiempo aprox en lo que tiene q durar el apareo global? Pq se nos esta dando bastante, son como 30.000mensajes que manda cada nodo

**Comment by iago64** [comment]
Martin, que tal?

En cuanto a tiempos no tenemos un valor maximo, pero a priori seria bueno que puedan procesar el dataset de 30Mb sin que estos les tome mucho mas que 15 o 20 min en el peor de los casos.

Saludos.-

**Comment by marrtins** [comment]
ok excelente, son esos los valores que tenemos mas o menos. 
gracias, cierro!
