### ISSUE TITLE
[Worker] Problema con scripts

### ISSUE THREAD

**Issue by DarkWood97** [sisoputnfrba/foro#966]
Hola! Tenia una duda respecto a la ejecucion de los scripts ya que cuando ejecuto el system con el comando " cat Bloque | ./transformador.py | sort > LaRutaDeDestino" empieza a transformar y se traba la compu porque son 34 transformaciones que hace (o sea 34 procesos hijos), luego de que responde, abre el archivo en la ruta de destino y este esta vacio. No entiendo cual podria ser el error, si ejecuto el script por consola con los mismos parametros si me genera un resultado pero cuando hago el system de mi proceso no pasa lo mismo. Ademas yo le doy permisos de ejecucion al script asi que no creo que tenga problema con eso.

Desde ya, muchas gracias!!

**Comment by DarkWood97** [comment]
Problema solucionado, disculpen las molestias!! Habia un error de logica.

**Comment by tferraro** [comment]
No nos dejes con la duda, _cuál_ error de lógica? :slightly_smiling_face:

**Comment by DarkWood97** [comment]
Disculpa por la tardanza de la respuesta!! El problema es que no estaba haciendo el mmap y supongo que al buscarlo al archivo y no tenerlo cargado en la memoria se generaba una sobresaturacion en el disco por los 34 procesos de transformacion ejecutando y explotaba todo
