### ISSUE TITLE
Entendiendo MD5 en documento de pruebas

### ISSUE THREAD

**Issue by dromero-7854** [sisoputnfrba/foro#967]
Buenos días,

Estoy leyendo el documentos de prueba, y no llego a entender del todo como debo hacer la validación de los md5.

- Ahora estamos ejecutando:

master ./transformador.py  ./reductor.py /nombres.csv /resultado.csv
¿Contra que md5 debo comparar el archivo /resultado.csv para saber que fue ejecutado correctamente?

- ¿Qué es lo de Juego de Datos Completo divididos y sanitizados?

- Lo que estoy entendiendo del documento es que si luego hago
master ./transformador_iniciales.py  ./reductor.py nombres.csv /resultado.csv

Tendria que comparar el md5 con:
a. md5​ dataset Completo: 975f82dcc9da6722b712bd981f1ef822  (archivo con el apareo sin reducción)
b. md5​ dataset Reducido: b20e8cce4cd27a6b843c949e20941430 (archivo con el apareo reducido)
¿Es asi?

Saludos y gracias!

**Comment by tferraro** [comment]
Buenas!

El "completo" hace alusión al dataset completo (el que pesa 200 megas que está en el drive), mientras que el reducido, que es el más optimo para pruebas rápidas, es el "reducido".

Ambos se llaman `nombres.csv` para simplificar el armado del comando del master.

**Comment by dromero-7854** [comment]
Ahi encontre el link del completo... cuando llegue a casa lo descargo y veo si me quedo alguna duda (en el laburo no puedo hacer descargas)

**Comment by tferraro** [comment]
@dromero-7854 que tul con esto? Te matchearon los md5s?

**Comment by dromero-7854** [comment]
Hola de nuevo,

Hasta ahora machearon. Pero queremos hacer la prueba con el set de 200MB. 

¿Como los descargo al Ubuntu Server? (se encuentran en Google Drive)

Saludos!
Dante Romero

**Comment by tferraro** [comment]
Podes bajarlo a la máquina local y usar scp como dice el doc de pruebas, ooo [buscar muchas más opciones en internet](http://lmgtfy.com/?q=wget+google+drive) :stuck_out_tongue_winking_eye:

**Comment by dromero-7854** [comment]
Complicado el tutorial de cómo buscar en Google :stuck_out_tongue_winking_eye: 
Gracias por la ayuda! Seguro nos vemos el sábado.

Saludos!

**Comment by tferraro** [comment]
Genial! Cualquier duda/bardo que tengan no dudes en abrir otro issue. Voy a tratar de al menos hasta antes de empezar las entregas de contestar todos los que haya :wink:
