### ISSUE TITLE
problema con pipes

### ISSUE THREAD

**Issue by joaquin3684** [sisoputnfrba/foro#968]
Hola que tal? 
el problema que tengo es que estoy tratando de usar los pipes para el tema del fork en el worker. por lo que me puse a ver el ejemplo que esta en el tp con forks y pipes. la cuestion es que copie el codigo igual y no me funciona. y no logro entender porque. explota en la linea 50 (write). cuando paso esa linea explota y me tira "No source available for "__kernel_vsyscall() at 0xb7fdd424" ". me dijeron que esto lo tira porque en debug no esta el flag entonces no encuentra las syscall del kernel. aca tengo dos problemas uno no entiendo porque no lo encuentra porque pruebo debuguear un write con pipes y anda bien sin explotar. dos si sigo pasando las lineas cuando hago el read para leer lo que me mando el proceso hijo en este no hay nada. 

        pipe(pipe_padreAHijo);
	pipe(pipe_hijoAPadre);

	if((childWorker = fork()) == 0){

		dup2(pipe_padreAHijo[0], STDIN_FILENO);
		dup2(pipe_hijoAPadre[1], STDOUT_FILENO);
	   	close(pipe_padreAHijo[1]);
	  	close(pipe_hijoAPadre[0]);
		close(pipe_hijoAPadre[1]);
		close(pipe_padreAHijo[0]);
		char *argv[] = {NULL};
		char *envp[] = {NULL};
		execve("cat ", argv, envp);
		exit(1);

	} else {

		close(pipe_padreAHijo[0]);
		close(pipe_hijoAPadre[1]);
		write(pipe_padreAHijo[1], "src/worker.c", 12);
		close(pipe_padreAHijo[1]);
		waitpid(childWorker,&status,0);
		read(pipe_hijoAPadre[0], buffer, 4);
		printf("alsdkjfalksdf %s\n", buffer);
		close(pipe_hijoAPadre[0]);
	}

**Comment by tferraro** [comment]
![image](https://user-images.githubusercontent.com/7110539/33373604-7900947a-d4e1-11e7-99c2-6df1416f325e.png)
