### ISSUE TITLE
problema STDOUT

### ISSUE THREAD

**Issue by joaquin3684** [sisoputnfrba/foro#969]
buenas, tengo el siguiente problema estoy haciendo la comunicacion con pipes en el worker. y estoy en la etapa de transformacion. el problema que tengo es que al ejecutar el sort no puedo guardar la respuesta en un buffer sino que me lo imprime por pantalla. yo lo que estoy haciendo en el hijo es ejecutar el script de transformacion y el resultado me llega al STDIN del padre. pero al ejecutar el sort no logro guardarlo en el file descriptor "fd", al ejecutar el read del buffer del fd este sale vacio

```
dup2(pipe_hijoAPadre[0], STDIN_FILENO);
int fd = open("testfile.txt", O_RDWR | O_CREAT);
dup2(fd, STDOUT_FILENO);

close(pipe_padreAHijo[0]);
close(pipe_hijoAPadre[1]);
close(pipe_hijoAPadre[0]);
close(fd);


write(pipe_padreAHijo[1], bin, strlen(bin));
close(pipe_padreAHijo[1]);

waitpid(childWorker,&status,0);
system("sort");

read(fd, buffer, 10);
printf("prueba %s\n", buffer);
```

**Comment by tferraro** [comment]
Buenas!

Para asegurarme, el código que pusiste es el del hijo verdad?

`system()` y pipes no se suelen llevar bien. Esto es porque los pipes se usan con `fork()` y `exec()`, pero a diferencia de `exec()`, `system()` no reemplaza al proceso, **sino que genera otro**. Esto, aparte de causar más overhead, hace que tus pipes queden bien colgados :slightly_smiling_face: .

Regla de oro: Si es una tarea de única vez que puedas aprovechar comandos de consola, system viene fenomeno. Peeero, si vas a realizar multiples ejecuciones de la tarea al simultáneo, el overhead te puede matar y capas necesitas ir por pipes+fork.

**Comment by joaquin3684** [comment]
el codigo que puse es el padre, como explique antes, el codigo ese es del padre, yo lo que estoy haciendo es que el hijo recibe por stdin el archivo que en el tp seria el contenido de un bloque, el hijo ejecuta el transformador y por STDOUT se lo envia al padre, el padre por STDIN recibe el resultado de la transformacion, y ejecuta sort. en este momento se presenta el problema porque cuando ejecuta sort no hacer que se guarde la salida esa en un buffer. automaticamente una vez que termino de ejcutar el sort lo muestra por pantalla. ese es el problema que tengo que nose como hacer para guardarlo

**Comment by tferraro** [comment]
Entonces ahí tenés el problema, como te dije antes, system no reemplaza al proceso, genera otro, por lo que si pones `sort`  solo, es lo mismo que no tener pipes. Hay mútiples opciones de como solucionar este inconveniente, cuales se te ocurren?

**Comment by joaquin3684** [comment]
lo que se me ocurrio es en el hijo ejecutar system("transformacion.sh | sort"). y ahi el padre recibe la respuesta y ya lo puedo guardar  y todo. El problema con esto es que como hago yo para saber cual es la longitud del resultado de la trasnformacion para poder guardarlo en un buffer y despues guardarlo en el archivo temporal ?

**Comment by tferraro** [comment]
Podés delegarselo a bash! 😉

Investigate sobre **operador ">"** (o probalo en la consola 🙂 )

**Comment by joaquin3684** [comment]
Buenas, estuve investigando el operador y con system lo puedo hacer todo de
una pero me queda una duda todavia.

yo por ejemplo en el caso del transformador en uno de los test que me dan
ustedes el codigo del transformador es el siguiente:

cat - | awk -F ',' '{print $2 ";" $1  ";" $13 ";" $3}'

entonces si yo ejecuto system sobre eso el proceso se queda colgado ahi
porque esta esperando el standar input. lo que no logro darme cuenta es si
yo quiero hacer todo con system yo deberia hacer algo como

system( cat bloqueArchivo | awk -F ',' '{print $2 ";" $1  ";" $13 ";" $3}'
| sort > archivoTemporal )

pero el problema que tengo con esto es que ami el codigo que tengo que
ejecutar, por ejemplo en este caso tiene el "cat -" donde el "-" me dice
que esta esperando un standarInput. pero yo al estar usando system no tiene
sentido que use pipes para cambiar el standar input para poder mandarselo a
system.  a su vez va a haber capaz codigos que tenga que ejecutar que no
tengan el "-" (esto es una suposicion mia). entonces como hago para
reemplazar el guion directamente por el bloque a leer.

Calculo que buscar el primer guion del script y reemplazarlo por el bloque
seria medio kamikaze

2017-12-01 17:59 GMT-03:00 Tomás Ferraro <notifications@github.com>:

**Comment by joaquin3684** [comment]
creo que ya encontre la solucion seria poner cat bloque |
./transformacion.py | sort > temporal.

de esa forma no interesa que tenga adentro del transformacion va a
funcionar. pero esto me trajo otro problema que ami master me dice que
bloque tengo que leer y cuanto tengo que leer y cuantos bytes tengo que
leer del mismo. el problema con esto es que yo voy a tener un string algo
asi

Valentina,3850,2000
Agustin,2614,2000
Juan Ignacio,2457,2000
Camila,2420,2000
Agustina,2380,2000

entonces bloque va a tener eso adentro el problema es que si yo hago "cat
bloque" con eso me hace el cat de la primera linea (valentina,3850,2000) y
despues sigue ejecutando el resto sin ningun comando. entonces como puedo
hacer para que me ejecute por todo el bloque y no por la primer linea.
probe con echo pero pasa lo mismo. una solucion capaz seria guardar ese
bloque en un archivo temporal y ahi si el cat va a funcionar. pero no
parece muy performante que digamos.

**Comment by tferraro** [comment]
Buenas!

Primero y principal, _no mires el contenido del script_, solo aceptá la interfaz que exponen. Te imaginás como podría ser para un transformador y un reductor? (Vale armarla en cualquier forma que quieras).

el problema que estás encontrando es que `cat` es una función que concatena el contenido de n archivos y lo muestra por stdout. Si le pasas el contenido directamente, **nunca te va a funcionar**, la función que creo que estás buscando es **echo -n**

**Comment by tferraro** [comment]
@joaquin3684 que onda por aca? Probaste con echo al final? Si no, como lo encaraste?
