### ISSUE TITLE
Problema con conexión entre Master y Worker

### ISSUE THREAD

**Issue by eliasgabrielkim** [sisoputnfrba/foro#972]
Buenas ! 
Este problema que estamos sucediendo ocurre en la etapa de transformación. Adoptamos un diseño en donde cada hilo que es creado en dicha etapa se conecta a un hijo de worker. En el proceso worker, apenas recibe una conexión realiza un fork y luego hace el handshake. 

Con nombres.csv reducido (33mib aproximadamente) el sistema funciona perfectamente. Sin embargo, cuando queremos probar el completo (212 mib), los hilos de master se caen porque reciben un código de error -1, en nuestro sistema master toma dicho error como la caída de un worker. Pero el worker nunca se cayó ! 
Posible problema:
- Que el socket se puede estar pisando en el worker y al pisarse hace que a master le llegue ese -1.

En un principio pensamos que master era el que tenía el problema ya que éste era el que tiraba el error, este supuesto problema era condición de carrera, pero analizándolo profundamente llegamos a la conclusión de que no, porque todas las regiones críticas están bien atomizadas con semáforos, los recursos se liberan adecuadamente y los hilos se matan correctamente. De la misma manera, worker se liberan los recursos adecuadamente y se mata bien a los hijos.

Desde ya, muchas gracias!

**Comment by tferraro** [comment]
Buenas!

Cuando decís que: _ los hilos de master se caen porque reciben un código de error -1_, lo reciben por socket? Quién se los manda?

Si no es así, de dodne saca el cod de error?

Si es por socket, me suena a un clasico escenario de que se están olvidando algo en el socket. Si no, tengo la sensación de que están pisando memoria de una variable con otra (y no salta SegFault porque _es memoria que pidieron en algún momento y no está libre_).

Saludos!
Tom

**Comment by eliasgabrielkim** [comment]
Me expresé mal, cuando digo que a master le llega ese -1, es porque el socket por el cual se comunica con worker es igual -1, es decir, se muere el socket. 
Qué me puedo estar olvidando del socket ? Porque si llega haber un error, libero los recursos y cierro el socket correspondiente, y sinceramente me estoy volviendo loco con esto, porque si anda con 33 hilos, debería andar con 212 tranquilamente. Y la variable no se pisa porque la declaro bien, y la libero bien. Hay algún detalle teórico de sockets que estoy pasando de largo ? También pensé en agregar un signal() con SIGCHLD, pero no creo que tenga que ver con eso...

**Comment by tferraro** [comment]
Buenas!

Que `recv()` devuelva -1 no implica que "el socket se muere". Si le pegás una mirada al [man](http://man7.org/linux/man-pages/man2/recv.2.html#RETURN_VALUE), fijate que habla que cuando se hizo un cierre correcto, retorna 0. -1 está reservado para errores múltiples, que no necesariamente están alineados con que se haya cerrado mal la conexión del otro lado, _tendrías que revisar el errno para estar seguro_.

> Porque si llega haber un error, libero los recursos y cierro el socket correspondiente, y sinceramente me estoy volviendo loco con esto, porque si anda con 33 hilos, debería andar con 212 tranquilamente. Y la variable no se pisa porque la declaro bien, y la libero bien.

Esto tomalo con pinzas, es claro que uno no mete errores a sabiendas, por lo que parece bien hecho [muchas veces esconde algo atrás](http://i0.kym-cdn.com/entries/icons/original/000/017/046/BptVE1JIEAAA3dT.jpg).

Contanos cual es el valor de errno a ver que pasa :slightly_smiling_face:

**Comment by eliasgabrielkim** [comment]
El errno del recv() del lado del master tira "Connection reset by peer", eso quiere decir que el worker estaría cerrando la conexión. 
El worker recibe todo bien, y los systems los ejecuta adecuadamente, es decir, el status me da 0, no me tira nada raro.
```
while(true){
socketAceptado = aceptarSocket(socketEscucha);
recibirPaquete(socketAceptado);
if(fork() == 0){ 
 socketFork = socketAceptado;
handshake(socketFork)
switch(){
 ....
}
 }
}

Es un pequeño pseudocódigo de lo que estoy haciendo, espero que sirva para entender el problema que estoy teniendo...

**Comment by econtarino** [comment]
Me sumo al pedido nos pasa exactamente lo mismo del hiloMaster con los workers  en un momento con el archivo de 200mb nos tira exactamente esto  "Connection reset by peer" y no sabemos que puede ser ya que con otro archivo de prueba funciona bien, es mas si a yama le ponemos un tiempo de wait con mas espera funciona pero al bajar esa espera pincha.

**Comment by tferraro** [comment]
> si a yama le ponemos un tiempo de wait con mas espera funciona pero al bajar esa espera pincha.

Plz dont.

Durante el finde anduve viendo esto, así que les pido que comprueben lo siguiente:

Por lo general, ese error es por querer interactuar con una conexión que ya se cerró del otro lado.
Sin embargo, suele aparecer cuando uno no revisa el retorno del read, y solo chequea el -1 (incluso a veces usando el WAITALL, aunque no puedo probarlo, nunca lo vi en vivo y en directo). Si quedara info en el buffer por no haberlo recibido completo, el SO te trata de obligar a que lo vacíes, pero como esa conexión ya se cerró, salta el error de `Connection reset by peer`.

Avísenme que onda.

Tom

**Comment by GauntStrelok** [comment]
Hola, estoy en el grupo con econtarino, cabe aclarar que los sockets que tiran error son sockets nuevos que todavia no se cerraron y se acaban de abrir.

**Comment by tferraro** [comment]
De todas formas, prueben eso y me cuentan. Mientras tanto, pasenme cual es
la línea que manda el error, si no llega a ser lo reviso en el código a ver
que onda.

**Comment by tferraro** [comment]
@eliasgabrielkim por lo que hablamos el sábado, asumo que la duda está resuelte :stuck_out_tongue: , pero @econtarino @GauntStrelok que onda por allá? Les sirvió? Pasenme igual lo que les pedí así lo vemos :slightly_smiling_face:

**Comment by GauntStrelok** [comment]
Hola, dale, te paso las lineas, primero te digo el commit actual de master asi las lineas no cambian :P
5fbce04c36b86cc3e5778970ebac71ad43553800

Se recibe en la linea 48 de hiloRealizarTransfWorker.c adentro de master, y el send correspondiente esta en la linea 552 de worker.c

Cualquier cosa te volvemos a avisar.

**Comment by tferraro** [comment]
@GauntStrelok por lo que ví en tu código, estás haciendo algo así:
```
if (recv(unWorker,header,sizeof(t_header),0) <= 0){
    log_error(...);
    avisarAYama(...);
    close(archivofd);
    pthread_exit(NULL);
}
```

El problema que a priori veo, es que _no estás cerrando el socket cuando falla_ :slightly_smiling_face: Si encuentro algo más aviso.

Y algo que no me percaté de preguntarles antes, que dice valgrind al respecto?

**Comment by nicolasreyd** [comment]
Hola, como se resolvió este problema? Lo que nos esta pasando a nosotros es que con el archivo de 33Mb funciona todo bien. Pero cuando queremos usar el archivo de 212Mb **solo funciona si lo ejecutamos con Valgrind**.. 
Descartamos que sea una condición de carrera pq comentamos todo el código en el Master que utilizaba recursos compartidos.
Lo que sucede es que Master termina muriendo con un SegFault..

**Comment by varas-c** [comment]
Nicolas, consulta. Están verificando que los recv reciban TODO lo que
deberían recibir?

Es decir, si ustedes hacen un send de 20 megas, estan verificando que
lleguen los 20 megas del otro lado?

2017-12-10 17:12 GMT-03:00 nicolasreyd <notifications@github.com>:

**Comment by nfederico** [comment]
@varas-c  Buenas sobre la consulta que le haces a Nico, el el rcv() esta con el flag WAITALL.

Saludos

**Comment by varas-c** [comment]
Estaría bueno que analicen que errores les reporta Valgrind (si es que les
marca alguno). Como dicen ustedes, puede darse el caso de que un código no
funcione pero sí lo hace corriendo con Valgrind.

Lo que sucede es que a veces Valgrind trata de solucionar ciertos problemas
por atrás. Es raro que suceda ésto, pero puede pasar.

Les recomiendo ver éste video del groso de @matiasgarciaisaia que a mi me
sirvió cuando cursé la materia :)

https://www.youtube.com/watch?v=-CI4MexyU3I

**Comment by mtimossi** [comment]
Esa función de postmortem es lo mas groso que vi, o sea... tremendo.
