### ISSUE TITLE
Consulta Retardo YAMA

### ISSUE THREAD

**Issue by leandroventura** [sisoputnfrba/foro#973]
Buenas, tengo una consulta respecto del retardo de YAMA en la planificación. En las pruebas nos piden que sean de 500ms, dado que la función usleep trabaja en microsegundos. Pero viendo que el retardo está para probar que en el momento que esté planificando YAMA, no se le cambie la configuración hasta que termine, no entiendo que sentido tiene tener un tiempo tan chico, ya que los cambios se avisan mediante la señal SIGUSR1 y no nos darían las manos para responder en un tiempo tan pequeño. Otra duda que tengo es si el usleep lo hago una sola vez, o cada vez que esté evaluando el algoritmo dentro de la planificación.

**Comment by dadais216** [comment]
Hola, quería agregar a esta consulta que no entiendo donde se deberían poner los retardos ni que función cumplen

**Comment by tferraro** [comment]
Buenas!

El tiempo del retardo está puesto en 500ms para agilizar las pruebas, pero la idea es tener una herramienta para ralentizar el sistema y poder probar mejor el algoritmo si es necesario y ver como se van actualizando los valores de disponibilidad despues de cada planificación. Está bien que no cambia hasta la próxima planificación, es la idea.

**Comment by leandroventura** [comment]
Ok, yo preguntaba porque lo máximo que se podría retardar con usleep sería 1 segundo que es lo máximo que admite la función. Ahora bien, debería ejecutar la función una sola vez en la planificación, o reiteradas veces por cada vez que se evalúa el algoritmo dentro del ciclo?

**Comment by tferraro** [comment]
Exacto! La idea es que no se amontonen los requests en los Workers en realidad, YAMA mucho no importa porque ejecutan las cosas de forma serializada. Con 1 seg de diferencia, los logs no deberían amontonarse si es necesario revisarlos más afondo :slightly_smiling_face: .

Con 1 sola vez por planificación está bien. (Si quieren retrazarlo por cada ciclo, aun mejor, pero depende de la implementación que elijan y el tiempo que seteen si eligen esta config).

**Comment by leandroventura** [comment]
Entonces lo que buscan con esto es tener tiempo, pero para evaluar los pedidos a los Workers. Yo puse la función una sola vez justo antes de entrar a planificar, creo que es lo mismo la ubicación, siempre y cuando se retrase antes de enviar las conexiones a Master, pero pregunto igual, está bien ahí o debería cambiarlo de lugar? Y otra cosa, tiene que ser usleep entonces? Pregunto pq en el enunciado dice que veamos esa función y quería saber mas que nada por los tiempos que nos van a pedir en la configuración al momento de evaluar el sistema.

**Comment by tferraro** [comment]
> Entonces lo que buscan con esto es tener tiempo, pero para evaluar los pedidos a los Workers. Yo puse la función una sola vez justo antes de entrar a planificar, creo que es lo mismo la ubicación, siempre y cuando se retrase antes de enviar las conexiones a Master, pero pregunto igual, está bien ahí o debería cambiarlo de lugar? 

Está barbaro

> Y otra cosa, tiene que ser usleep entonces? Pregunto pq en el enunciado dice que veamos esa función y quería saber mas que nada por los tiempos que nos van a pedir en la configuración al momento de evaluar el sistema.

Está puesto a modo de sugerencia, dado que sleep no acepta valores menores a 1 (y mayores a 0). Si quieren alternar entre las 2 para darle mayor rango de uso, fenómeno, pero no es obligatorio, depende de la implementación que elijan usar.

**Comment by leandroventura** [comment]
Buenísimo, quería confirmar que había hecho eso bien. Mil gracias! Cierro el issue.
