### ISSUE TITLE
problema con señales y select

### ISSUE THREAD

**Issue by dadais216** [sisoputnfrba/foro#974]
Hola, estaba intentando agregar la reconfiguracion en yama cuando se recibe una señal. Cuando envío la señal y yama esta bloqueado en el select, sale el mensaje "select: Interrupted system call" y luego se cierra.

Estuve leyendo en internet y dice que tengo que usar sigaction en vez de signal y meter el flag SA_RESTART para que no pase esto, intente varias formas pero sigue sin funcionarme. Leí que es algo que varia entre implementaciones de linux

Acá muestro el codigo que tengo y el mensaje que sale:

![image](https://user-images.githubusercontent.com/26806141/33472593-c15548d0-d651-11e7-88d5-a3c74042c45e.png)

Saludos

**Comment by varas-c** [comment]
Buenas, como va?

Efectivamente, si tenés un proceso bloqueado en Select y llega una señal,
el Proceso se desbloquea.

Una forma fácil de verificar ésto, es preguntar si errno == EINTR.

Por ejemplo:

int retval = select(parametros...)

if(retval < 0) { //Hubo un problema y select se desbloqueó por alguna razón

 if(errno == EINTR)
    //Se recibió una señal, deberíamos volver a ejecutar el select porque
fue interrumpido
 else
    //Problema desconocido, se desbloqueó y no fue por alguna señal. Como
no sabemos que hacer, abortamos el proceso
}

Fijate si ésto te sirve (ajustándolo a tus necesidades obviamente).

Cualquier cosa, avisanos!

2017-12-01 4:42 GMT-03:00 Daniel Martin <notifications@github.com>:

**Comment by dadais216** [comment]
Si, era eso. Las funciones que estaba intentando usar no me sirvieron, pero bueno, manejandolo como decis vos anduvo todo bien
