### ISSUE TITLE
Horario entrega

### ISSUE THREAD

**Issue by DPoma** [sisoputnfrba/foro#975]
Hola nosotros habiamos elegido desde las 15:30 hasta la 17:30 para la entrega, pero nos dieron que es a las 12, hasta que hora van a estar? porque no se si llegamos a tiempo, llegariamos mas tarde.

**Comment by iago64** [comment]
Hola que tal?
Los horarios son los asignados, si tienen algun inconveniente puntual por favor envien un mail a la casilla de inscripciones.
Saludos.-

**Comment by DPoma** [comment]
Cual es el mail?

**Comment by iago64** [comment]
inscripciones@utnso.com

**Comment by DPoma** [comment]
Muchas gracias!
