### ISSUE TITLE
Varias consultas

### ISSUE THREAD

**Issue by lepeg123** [sisoputnfrba/foro#976]
Buenas tardes,

Teniamos varias consultas sobre temas del tp, ya sean del enunciado, o de errores que tenemos en el codigo.

1. En el pdf de pruebas se menciona algo sobre LC_ALL = C para cuando se hace sort para que ordene correctamente las cosas, pero, donde se hace esto? Se tiene que hacer en la misma llamada system donde se hace el sort? O es posible setear ese valor desde algun momento y que quede fijo como cuando le das permisos a un archivo y ya queda con esos archivos?

2. Cuando menciona el retardo de Yama, que es el que lee del archivo de configuracion, ese retardo va donde? Es decir, cuando es que tiene que ocurrir esa cantidad de tiempo que indica el archivo de configuracion? Antes de arrancar la planificacion? No vimos en el enunciado que eso se especifique.

3. En la parte de la reconfiguracion de Yama cuando se le envia el signal SIGUSR1, ya supimos plantearlo para que Yama reciba esa signal, pero cuando le llega el proceso Yama muere debido a que se encuentra dentro de un esperarConexiones que esta bloqueado dentro de un select, y al llegarle la signal, muere el proceso con el mensaje de error: "Interrupted system call: select". Hay alguna manera de evitar este problema?

Por favor, cuanto antes puedan ayudarnos mejor. Gracias!

Saludos.

**Comment by nahueloyha** [comment]
Hola! Sobre el punto 3 se habló en el issue #974 , fijate si te sirve!

**Comment by veritoreinoso** [comment]
Hola! el punto 1 es simplemente un "export LC_ALL=C" que lo tiras por consola al momento de la prueba y por única vez, y sobre el punto 2 entiendo que le afecta cuando lo mandas a replanificar que haga un usleep de 'x' cantidad de microsegundos. Saludos!

**Comment by lepeg123** [comment]
Gracias a ambos! Cierro el issue entonces.
