### ISSUE TITLE
Como hacer debug de Fork

### ISSUE THREAD

**Issue by econtarino** [sisoputnfrba/foro#977]
Quería hacer este pedido por que me canse de probar  el worker con logs... no estoy pudiendo hacer debug del fork y quisiera ver por que algo rompe en worker. 
Habilite Non-stop mode, me esta faltando algo mas?
Gracias
Saludos.

![debug](https://user-images.githubusercontent.com/7339127/33620874-de521926-d9c7-11e7-9598-0cb09cf54a29.png)

**Comment by tferraro** [comment]
No se si es que no se ve o simplemente no aparece, pero debeŕia haber una opción de `Automatically debug forked processes` que necesario activar.

Aparte de eso, pusiste los breakpoints adecuados para poder seguir a los hijos? Porque por la config que tenés ahí, no se va a detener a penas se inicia. Además, a que te referís con no poder hacer debug del fork?b

Más allá de repreguntarte no puedo hacer desde acá, nos estás dando poca info :stuck_out_tongue: 

Saludos!
Tom

**Comment by econtarino** [comment]
Tomas ya pude hacerlo, estaba probando desde ubuntu y un linux Mint con otra  version de Eclipse, me pase a la VM y pude hacer el debug del fork.
Gracias igualmente.
Saludos.

**Comment by tferraro** [comment]
Genial! Te quedó algún inconveniente para debugear el fork? Si se resolvió todo, te invito a contarnos que diferencias notaste entre las versiones y a despues de contarnos, cerrar el issue :slightly_smiling_face:
