### ISSUE TITLE
Pruebas en Laboratorio con ayudantes

### ISSUE THREAD

**Issue by sebastianciancio** [sisoputnfrba/foro#978]
Tenemos pensado la semana que viene ir al Laboratorio y hacer una prueba completa de todo el sistema. La pregunta es para saber si se puede coordinar con algún ayudante para hacer una "simulación" de entrega y ver potenciales problemas.

Lo publico por acá porque, de ser posible, por ahí hay otros grupos interesados.

Gracias y aguardamos respuesta.
Saludos.

**Comment by nicozar95** [comment]
Buenas!
Yo el miércoles 13 me voy a pasar un rato por el labo después del mediodía. Búsquenme y hacemos una "simulación" de evaluación (siempre y cuando no haya labos reservados)

**Comment by tferraro** [comment]
> Lo ideal siempre es Medrano, para probar en las mismas pcs del labo😉

**Comment by sebastianciancio** [comment]
Perfecto... entonces del Campus nos vamos a Medrano. Gracias.

Lo dejo abierto el Issues unos días por si algún grupo le interesa y le sirve

**Comment by nahuelm** [comment]
Sebastian, agrego a lo que dijo Nicolas. Vamos a estar varios ayudantes en el laboratorio de Medrano a partir de las 18/19hs dando soporte a todos los grupos que lo necesiten

**Comment by nahuelm** [comment]
Aclaro ya que veo que no puse fecha. Vamos a estar el miércoles 13/12 y Jueves 14/12. Ya genereamos un post en el blog con dicha informacion: 
https://www.utnso.com/dias-de-consultas-pre-entrega-segundo-recuperatorio/

**Comment by sebastianciancio** [comment]
Perfecto. Cierre el Issue.
