### ISSUE TITLE
[Worker] Duda en reduccion global

### ISSUE THREAD

**Issue by DarkWood97** [sisoputnfrba/foro#979]
Hola! Me agarro una duda existencial mientras estaba probando 2 masters en simultaneo ya que por ejemplo, si en la reduccion global, cuando los demas workers les envian sus archivos temporales de reduccion local al worker encargado de la reduccion global, estos para hacer todo el proceso del envio, deben de antes forkear asi de esto se ocupa un proceso hijo y estos pueden seguir escuchando peticiones de otro master/worker? Yo unicamente forkie cuando el master me envia una peticion de transformacion, reduccion local, reduccion global o almacenamiento ya que el enunciado especifica que cuando se recibe una conexion de master, automaticamente se debe de forkear asi el proceso hijo se encarga del resto y el padre escucha pero no dice nada de cuando otro worker recibe una conexion de otro worker. Desde ya, muchas gracias!

**Comment by tferraro** [comment]
Buenas!

Lo ideal es que si, que toda tarea sea paralela y no retenible, inclusive
la conexión Worker-Worker. Incluso sería más fácil de manejar, en la misma
petición que te hacen, forkeas de una después del accept y después chequeas
que tipo de operación es, no te parece?

Dependiendo de tu código, que tanto te complica cambiarlo? Porque si es
jodido, claramente hay algo mal diseñado 😛.

Saludos!
Tom

**Comment by DarkWood97** [comment]
Buenas noches tomas, eso pensaba, asi se aprovecha el paralelismo con los forks y ademas en el caso de que tenga 2 masters, no se me quede algun worker colgado. Desde ya, muchas gracias!! Y no, no se me complica cambiar el codigo ya que solamente tengo que agregar el fork y nada mas, en todo el cuatrimestre estuve borrando y rehaciendo devuelta para tener un worker que este bien diseñado y que un minimo cambio no me afecte demasiado

**Comment by DarkWood97** [comment]
Buenas noches tomas, eso pensaba, asi se aprovecha el paralelismo con los forks y ademas en el caso de que tenga 2 masters, no se me quede algun worker colgado. Desde ya, muchas gracias!! Y no, no se me complica cambiar el codigo ya que solamente tengo que agregar el fork y nada mas, en todo el cuatrimestre estuve rompiendome la cabeza para tener un worker que este bien diseñado y que un minimo cambio no me afecte demasiado

**Comment by tferraro** [comment]
Bárbaro!!!
