### ISSUE TITLE
pedir bloques al replanificar????

### ISSUE THREAD

**Issue by guillelle** [sisoputnfrba/foro#980]
Hola,

hago una consulta sobre un tema que nos planteó un ayudante el sábado pasado, cuando YAMA replanifica porque hubo un error en la transformación de un bloque debe volver a pedirle a FS los bloques de ese archivo? 
La duda surgió porque puede ocurrir que el nodo donde estaba la copia esté caído y YAMA no se haya enterado y le indique a MASTER que use ese nodo caído, situación que ya el FS pudo haber solucionado moviendo los bloques de archivo a otro nodo, pero el YAMA no se entera de esta reubicación si no pide nuevamente los bloques
En resumen, al replanificar, YAMA debería pedir de nuevo los bloques del archivo en cuestión al FS???????
O esta situación se la puede tomar como una de las razones para abortar un job????

gracias
saludos

**Comment by tferraro** [comment]
Buenas!

Dependiendo de como esté armado tu protocolo, podría ser o no necesario. La consistencia de "si agrego una copia de un bloque en otro nodo y quiero que al replanificar lo tome" es un caso utópico, el mejor si se quiere. Sin embargo, dependerá del protocolo que hayan armado si hace falta o no, o si permite su agregado o no (si es que no lo contemplaron).

En el mejor de los casos, que YAMA pida cada vez que debe planificar (o replanificar) la información de bloques al FS te asegura que siempre esté trabajando con información actualizada, no?

FInalmente, la única razon para abortar un job es que lo que fallen sean procesos de reducción (tanto local como global) en adelante o que un bloque de un archivo sea inaccesible al momento de replanificar, por lo que debería abortar.

Saludos!
Tom

**Comment by guillelle** [comment]
ok, entonces pido de nuevo los bloques al replanificar, usaría las mismas funciones que en la planificación inicial. 
Pero en ese caso se deberían replanificar los bloques que no se pudieron transformar, no todo de nuevo, digo bien?

**Comment by guillermo126** [comment]
Hola ¿cómo estan? yo pregunté algo parecido en el issue 907 y me dijeron q solo yama en entera al momento cuando inicia un nuevo job.

**Comment by lianndt** [comment]
Hola como va?
Segun el enunciado y por lo que lei del issue 907, a yama le interesa verificar la consistencia de los workers conectados y los bloques del archivo justo antes de hacer la pre-planificacion. Lo que pasa con los bloques en el medio de un job no es incumbencia de yama. De ultima si se borra un  bloque en medio de un job, yama recibe los errores correspondientes y se aborta. En cambio el siguiente job que se inicie despues de ese borrado de bloque ya va a tener la info actualizada cuando se la pida a FS. Estaria bien este punto de vista?
Gracias!

**Comment by tferraro** [comment]
Buenas!

Una cosa es que ya esté prepanificado un Job y se caiga un nodo que no afecte a ese Job, por consiguiente, todo se ejecuta bien y no hay comunicación contra Yama, que es el caso del #907; y otra este escenario.

Este escenario responde a donde el nodo que se cae es uno de transformación y volves a preguntarle a Yama, y Yama tiene _que volver a pre-planificar_, es decir coloquialmente "_la próxima pre-planificación_" o una **re-planificación** (puede ser incluso una planificación de otro Job). Pero lo importante es que cada vez que planifique, le consulte al FS el estado de los bloques que componen al archivo en sí. Tendría sentido que re-planificar sin consultar eso?
Si se cayeron las copias que habían y hay nuevas copias disponibles? En un Job que tarda, hipotéticamente mucho tiempo, tiene sentido cortar todo por algo así? Mantendríamos la idea de alta disponibilidad?

**Comment by lianndt** [comment]
Hola Tom! Ahora queda claro. En el otro issue hace referencia al borrado de un bloque explicito en medio de un job. eso obviamente no tiene nada que influir en yama mientras planifica o después, excepto que master comunique error de transformación. Pero en el caso que se caiga un nodo que estaba haciendo transformaciones o bien haya un error explicito de una transformación,  tiene sentido actualizar los bloques antes de re-replanificar. Sino se seguiría con datos inconsistentes y por tanto una potencial falla al replanificar. Así se sigue respetando/aprovechando la disponibilidad.
Thanks!

Leandro

**Comment by guillelle** [comment]
hola, yo de nuevo... pregunto de nuevo con otras palabras.
El tema concretamente es si se cae un nodo que estaba haciendo transformación, x ej, hay 200 bloques transformandose en 10 nodos. Si se cae el nodo 1 va a haber 20 bloques que corren riesgo de no transformarse, supongamos que de esos 20 bloques, 10 habían terminado bien y otros 10 no pudieron transformarse. Master le indica a YAMA los 10 bloques del nodo 1 que no pudieron transformarse. Ahora viene la cuestión:

      1. en el enunciado y ahora tb en los requerimientos mínimos de las pruebas dice que se replanifica en el nodo donde se encuentra la copia de ese bloque para realizar la transformación (asumo que es buscar los datos de dicho nodo y pasarselo a Master), y si el nodo con la copia no está funcionando no se puede replanificar y se aborta el job.

      2. Ahora, en los requerimientos de promoción dice que al replanificar la carga es pareja y se respeta el algoritmo, para eso debería pedir de nuevo al FileSystem los bloques y ejecutar la planificacion, y pasarle a master sólo los bloques que fallaron

Los dos escenarios son correctos? o entendimos cualquier cosa?

**Comment by iago64** [comment]
Buenas buenas!

Tene en cuenta que si se te cae un nodo, no vas a poder acceder ni a los que estaban transformados ok ni a los que se estaban transformando, asi que deberias volver a transformar los bloques que estaban bien en ese nodo.

Respecto a los escenarios:
_Escenario 1:_ Efectivamente, si no tenes copias, abortas el Job y decis que es porque no se puede replanificar porque te faltan bloques

_Escenario 2:_ Efectivamente, solo tenes que replanificar lo que estaba en el nodo que se cayó, con lo cual, la carga es pareja dentro de lo que se puede hacer ya que los nodos que tengan las copias van a verse sobrecargados y puede que tengas algun desbalance (totalmente valido).

Saludos.-

**Comment by guillelle** [comment]
Aclaradísimo!!!!! muchas gracias
También estoy pensando en que si un nodo había terminado la reducción local con la planificación original y ahora le meto nuevas transformaciones como resultado de la replanificación, debería rehacer la reducción local en ese nodo

muchas gracias
saludos
