### ISSUE TITLE
Usar system para correr los scripts, que comandos se pueden usar en el bash

### ISSUE THREAD

**Issue by GauntStrelok** [sisoputnfrba/foro#981]
Hola, en nuestro TP estamos usando system para correr los scripts sobre los archivos, y en principio lo teniamos hecho con printf, pero nos estaba fallando por el largo del printf, como si el comando fuera muy largo.

Una de las cosas que se nos ocurrio para arreglar esto fue usar un cat de un archivo temporal creado por nosotros que contenga la data a transformar (esto a si mismo trae el overhead de tener que grabar el archivo temporal antes de transformarlo).

Una cosa que se me ocurrio a mi(pero aun no probe en la vm) es usar el comando dd y que se traiga la data correspondiente al bloque directamente del archivo .bin del nodo, por ejemplo
dd if=./datos.bin bs=1 skip=SIZE_BLOQUE * numBloque count=tamanioOcupado

Tengo que verificar aun si es posible usar ese comando en la VM, hay alguna limitacion de que cosas podemos utilizar ademas de las no contadas por default en la VM?

**Comment by tferraro** [comment]
Buenas!

Es válido si quieren bajarlo a un archivo. No es lo ideal, pero es válido. Respecto al dd, también se puede usar!

Saludos!
Tom

**Comment by GauntStrelok** [comment]
Gracias, cierro.
