### ISSUE TITLE
Pruebas Yama- transformador.py sobre dataset reducido

### ISSUE THREAD

**Issue by alejandrog87** [sisoputnfrba/foro#983]
Buenas tardes,

Estamos realizando pruebas en el laboratorio con los diversos transformadores, y notamos que el transformador.py demora demasiado, un tiempo que excede el disponible para la evaluación, este cuello de botella se produce en el apareo global.  El apareo global lo hicimos en base a lo que recomendó @tferraro en el issue #883, vamos recibiendo de cada nodo una linea y haciendo el apareo de forma "online" como un stream (descartando nuestra idea del principio que lo habiamos pensado como que cada nodo le enviaba su archivo de redu local  al nodo de la redu global  y después éste hacia el apareo global localmente con todos los archivos). 
Queríamos saber si ésto les sucedió a otros grupos  y que alternativa se siguió para evaluarlos, ya que vemos dificil poder ejecutar dicho transformador.  Los otros transformadores iniciales y anuales terminan enseguida.
Desde ya muchas gracias.

**Comment by alejandrog87** [comment]
No se olviden de mi 😊

**Comment by iago64** [comment]
Aloha!!
Mil disculpas por la demora en ver el tema.
Es muy posible que demore mucho el hacer el apareo, pero si las dudas eso esta contemplado y por eso hay 2 scripts de transformacion que son mucho mas chicos y que son el transformador_anuales.py y el transformador_iniciales.py que como trabajan sobre keys mas chicas deberian tardarles mucho menos en procesar.

Proba con esos transformadores y comentame si mejoran los tiempos de la reduccion global.

Abrazo!

**Comment by tferraro** [comment]
Guarda que podés llegar a tener una versión _no actual de los scripts_ (#964)

**Comment by alejandrog87** [comment]
Gracias por la respuesta, con los otros transformadores si obtenemos tiempos razonables.
Saludos!
