### ISSUE TITLE
Error al ejecutar script transformador

### ISSUE THREAD

**Issue by ccalvoromero** [sisoputnfrba/foro#984]
Hola chicos, estamos con un problema de que el MD5 no nos coincide con los que da la cátedra al ejecutar el script mencionado en el título del issue. Entonces... nos tomamos la molestia de ejecutar aparte en un bloque cualquiera, aislado, la transformación, tal cual, lo haríamos con System() ... y nos tira el siguiente error

![image](https://user-images.githubusercontent.com/11811170/33798110-dbcb00b4-dcf1-11e7-89c2-ce4f93dde302.png)

y mas allá de eso... cuando hago un cat del archivo destino, hay datos, pero hay caractéres raros al final, y tememos que esa sea la razón de que nos den MD5 distintos.

![image](https://user-images.githubusercontent.com/11811170/33798121-18ee361e-dcf2-11e7-96b7-e97e52b65da7.png)

Nos podrían orientar un poquito con esto?

Muchas gracias!

**Comment by iago64** [comment]
Buenas!!
Por esas casualidades estan probando con alguno de los datasets por lutros? Si es asi, descartenlos, esos estan solo para probar la copia de varios archivos.

Los datasets que sirven son el de nombres.csv (tanto el de 200mb que esta en drive como el de 30mb que esta en el repositorio)

Un abrazo!

**Comment by ccalvoromero** [comment]
Hola,

Usamos el dataset del nombres.csv

Por otro lado, estaba usando cat (sobre un archivo donde tengo ese bloque) pero decidí cambiarlo por un echo -n, y tira otros errores por el salto de línea (se suponía que el parámetro -n contemplaba esto no?)

En determinados casos, el bloque queda cortado a la mitad o con un salto de línea y eso hace romper la transformación. Cosa que si arreglo a mano, funciona

**Comment by iago64** [comment]
Lo del echo si va a tirarte errores porque lo interpreta distinto, mientras que cat lo que hace es mostrar el contenido.
De todas formas acabo de revisar el archivo de nombres. csv que esta subido en el [repositorio ](https://github.com/iago64/SO-Nombres-Dataset)y no tiene ningun inconveniente, no esta tirandome ningun error ejecutar los transformadores / reductor.
Si haces la prueba tal cual esta en el README.md del repo te funciona correctamente? el md5 del archivo de nombres.csv coincide con el que esta en el doc de pruebas?

**Comment by calvoromeroc** [comment]
Haciendo unas pruebas... basándome en el README.md, ejecute el comando:

`cat nombres.csv | ./transformador_Iniciales.py | sort | ./reductor.py > cantidadPersonas_Iniciales.txt`

Y el md5 resultante (*********f0d455) no coincide con el del documento de pruebas (que es éste:  "md5​ dataset Reducido: b20e8cce4cd27a6b843c949e20941430").

Hice también, el md5 al nombres.csv y es el mismo del documento de pruebas -> 0f25d7d69f1fca92bf9e3c045f577e81

**Comment by tferraro** [comment]
#964 guarda que podés no tener los scripts actualizados che :stuck_out_tongue:

**Comment by ccalvoromero** [comment]
Hice la prueba que está en el README.md y efectivamente da el MD5 del documento de pruebas (Nos habíamos olvidado del export LC_ALL=C al principio, pero haciendolo, dio bien. Vamos a seguir revisando y vuelvo a pasar un status. Gracias!

PD: Los scripts los bajé ayer nuevamente, así que descarto eso.

**Comment by iago64** [comment]
@ccalvoromero Buenisimo :) me quedo mas tranquilo entonces que el problema puede venir por el lado del export :)
Quedo a la espera de novedades.

Abrazo!

**Comment by ccalvoromero** [comment]
Chicos,

@iago64 @tferraro , Encontramos el problema. Ya nos da el MD5 del documento de pruebas. 
Gracias!

**Comment by iago64** [comment]
@ccalvoromero Buenisimo 👍 ! Los esperamos el sabado temprano entonces :)
