### ISSUE TITLE
Solicitud de soporte 

### ISSUE THREAD

**Issue by ivigilante** [sisoputnfrba/foro#985]
Hola buenas tardes, estábamos avanzando y ya cerrando y empezaron a surgir algunos inconvenientes que no sabemos cómo solucionar, habría posibilidad de organizar soporte en el laboratorio de Medrano? 
Muchísimas gracias. Saludos.

**Comment by varas-c** [comment]
Pasate por el blog  y ahí vas a encontrar mas info:

https://www.utnso.com/dias-de-consultas-pre-entrega-segundo-recuperatorio/


2017-12-12 9:21 GMT-03:00 ivigilante <notifications@github.com>:

**Comment by ivigilante** [comment]
Gracias! Cierro entonces.

**Comment by lepeg123** [comment]
Hola, yo vi ese post, pero no vi como es que se puede comentar en el para avisar de que vamos a ir. Gracias. Saludos!

**Comment by ivigilante** [comment]
No estan habilitado los comentarios, puede ser?

**Comment by mgarciaisaia** [comment]
Oh, sí. Los comentarios están cerrados porque nunca recordamos leerlos (ni
recordamos que están cerrados, tampoco). Pero los mails si que los leemos.
