### ISSUE TITLE
MD5 para probar los archivos generados

### ISSUE THREAD

**Issue by sebastianciancio** [sisoputnfrba/foro#986]
Hola muchachos,
   Quisiera consultar sobre los MD5 del almacenado final que no nos coinciden.

   Estamos usando nombres.csv (reducido de 34 MiB). El MD5 de ese archivo tanto en linux como en YamaFS da igual, es decir, 0f25d7d69f1fca92bf9e3c045f577e81.

  Luego corremos el master con los parametros ./master files/transformador.py files/reductor.py /nombres.csv /final.csv.

   Ese archivo final.csv nos termina pesando 16.604.076 bytes y el MD5 es 
a2b88929b4a908eb27226633b0e9e4a3 y entiendo debiera dar 8b11d4503f9c0e4d515cbf838fe4b114.

   Alguna guía de como hacer debug de esto? El archivo final cuanto debiera pesar?

   Gracias.

**Comment by francoalbornoz92** [comment]
Lo primero que haría yo es correr a mano el transformador y reductor sobre el archivo y chequear qué md5 me devuelve. Si no te da lo mismo que el de yama, entonces en alguna parte del proceso algo está saliendo mal.

**Comment by sebastianciancio** [comment]
El comando export LC_ALL=C lo tenemos ejecutados en todas las consolas.. asi que eso no debiera ser.

Estos son los 3 scripts que corremos, según la etapa:

**TRANSFORMACION**
chmod +x files/scripts/CopiaT-transformador.py;cat files/bloques/job1-NODO2-temp26 | ./files/scripts/CopiaT-transformador.py | sort > files/tmp/job1-NODO2-temp26

**REDUCCION LOCAL**
chmod +x files/scripts/CopiaR-reductor.py;sort -m files/tmp/job1-NODO2-temp32 files/tmp/job1-NODO2-temp30 files/tmp/job1-NODO2-temp28 files/tmp/job1-NODO2-temp26 files/tmp/job1-NODO2-temp24 files/tmp/job1-NODO2-temp22 files/tmp/job1-NODO2-temp20 files/tmp/job1-NODO2-temp18 files/tmp/job1-NODO2-temp16 files/tmp/job1-NODO2-temp14 files/tmp/job1-NODO2-temp12 files/tmp/job1-NODO2-temp10 files/tmp/job1-NODO2-temp8 files/tmp/job1-NODO2-temp6 files/tmp/job1-NODO2-temp4 files/tmp/job1-NODO2-temp2 files/tmp/job1-NODO2-temp0  | ./files/scripts/CopiaR-reductor.py > files/tmp/Master1-job1-RL2NODO2

**REDUCCION GLOBAL**
chmod +x files/scripts/CopiaR-reductor.py;sort -m files/tmp/Master1-job1-RL2NODO2 files/tmp/Master1-job1-RL1NODO1  | ./files/scripts/CopiaR-reductor.py > files/final/output/final.csv

Ven algo que no es compatible?

**Comment by sebastianciancio** [comment]
Esos comandos antes indicados lo corremos con system()

**Comment by sciciliani** [comment]
Hola, es dificil hacer el troubleshooting a la distancia pero te tiro
algunas ideas a ver si te podes dar cuenta al menos por donde viene el
problema:

1) El comando export lo haces antes de ejecutar el código o desde un script?
Fijate si ves la variable exportada en la terminal haciendo un: export |
grep LC_ALL

2) Si ejecutas los scripts en la misma terminal, el resultado coincide con
el md5? Ejemplo: cat nombres.csv | files/transformador.py | sort |
files/reductor.py > final.csv

3) Mirando el resultado del archivo procesado con Yama. Ves algo raro? Por
ejemplo que el orden no necesariamente sea alfabetico para todos los
nombres, etc. Esto lo podes mirar desde el Excel o el Google Sheets.

Avisame

**Comment by sebastianciancio** [comment]
Listo muchachos... era el export LC_ALL=C
Lo habiamos agregado automaticamente en un script para no olvidarnos pero no se que paso... si no anduvo o que. Ahora lo corrimos en todas las terminales en forma manual y el MD5 final fue el deseado.

Muchas gracias por la ayuda.
Cierro el caso.
