### ISSUE TITLE
system no esta ejecutando o problema de echo

### ISSUE THREAD

**Issue by ivigilante** [sisoputnfrba/foro#987]
Hola, buenas tardes.
Estoy teniendo un problema con el uso de system()
Lo que estoy haciendo yo es usar un string_from_format para crear un string que contenga:

"echo \"aca iria todo lo que saco del bloque\" | ./transformador.py | sort -d - > /aca/el/archvio/temp"

y eso se lo paso a system.

Ahora mi problema es que hice un printf del string que genero y para el caso de nombres.csv printea

"varios nombres...
.
.
.
Ludmila Denisse,2,2000
" | ./transformador.py | ......y el resto

Estos \n no sé si están afectando el funcionamiento de system, porque aveces genera el archivo temporal y aveces no, pero cuando lo hace, el mismo esta vacío.
Alguna mano con este problema?

**Comment by iago64** [comment]
Buenas buenas!
Es medio raro el problema y muy posiblemente los \n sean los que te estan jodiendo.
Eventualmente, que tanto se te complica bajar el contenido a un archivo temporal para hacerle cat y ejecutar desde system:

cat <archivoTemporalDelBloque>  | ./transformador.py | sort -d - > /aca/el/archvio/temp"

Saludos.-

**Comment by tferraro** [comment]
Guarda que, según el [man de echo](http://linuxcommand.org/lc3_man_pages/echoh.html)
 ```
DESCRIPTION
    Write arguments to the standard output.
    
    Display the ARGs on the standard output followed by a newline.
    
    Options:
      -n	do not append a newline
      -e	enable interpretation of the following backslash escapes
      -E	explicitly suppress interpretation of backslash escapes
```

Echo siempre le agrega una nueva línea al final, te faltaría el `-n}` .

**Comment by mgarciaisaia** [comment]
No hay que olvidar que `system`, en definitiva, está ejecutando una shell, pasándole tu línea de comandos.

Entonces tenés que tener en cuenta que las shells en general [tienen un límite de longitud de línea de comando](https://serverfault.com/questions/163371/linux-command-line-character-limit). En el link mencionan 128k, creo - algo que es bastante fácil de superar con los tamaños de bloque que maneja el TP.

En lugar de leer todo el contenido del bloque a la memoria de tu proceso, armar un string que contenga todo ese contenido, ejecutar una shell pasándole todo eso, y que el comando `echo` mande todo eso a la salida estándar, para que el transformador lo reciba por entrada estándar... Quizá convenga evitar tanto malabareo de bytes.

Además, ¿tenés garantías de que el bloque que estás leyendo no tiene `"` y `'` y otros caracteres que la shell considera "especiales"? Armar el comando con datos externos es propenso a [inyección de código](https://en.wikipedia.org/wiki/Code_injection) (que no solo son un problema si hay alguien intentando atacarte, si no también si _justo, justo, justo_ metés datos raros sin darte cuenta).

Entonces, ¿cómo "cortar" un bloque de todo tu archivo de disco? `head` y `tail`. Uno se queda con los primeros X bytes de un archivo, el otro se queda con los últimos Y. Y así te evitás tener datos del usuario (que vos no manejás) en la línea de comandos.

La alternativa es que, en vez de usar `system`, manejes vos los `fork`s de los procesos, crees pipes, y le mandes los datos desde C - en lugar de usar `echo`.

O la de Tom de crear un archivo temporal y hacerle `cat` - con el overhead de espacio y bla bla que implica.

¡Un abrazo!

**Comment by ivigilante** [comment]
Gracias por las respuestas.

> Eventualmente, que tanto se te complica bajar el contenido a un archivo temporal para hacerle cat y ejecutar desde system:
>cat | ./transformador.py | sort -d - > /aca/el/archvio/temp"

Esta puede ser que sea la opción que opte por una cuestión de tiempo.

> Echo siempre le agrega una nueva línea al final, te faltaría el -n .

Había probado con el -n pero igual tuve inconvenientes.

> Además, ¿tenés garantías de que el bloque que estás leyendo no tiene " y ' y otros caracteres que la shell considera "especiales"?

No entiendo como con head y tail me aseguro de salvarme de eso

> Entonces tenés que tener en cuenta que las shells en general tienen un límite de longitud de línea de comando. En el link mencionan 128k, creo - algo que es bastante fácil de superar con los tamaños de bloque que maneja el TP.

Esto puede ser definitivamente, pero mi shell permite 2097152 caracteres, yo creería que estoy dentro de esos números al ser bloques de 1M


Voy a probar hacer un archivo temporal donde guarde el bloque y pasárselo con cat y ver si funciona

**Comment by mgarciaisaia** [comment]
>> Entonces tenés que tener en cuenta que las shells en general tienen un límite de longitud de línea de comando. En el link mencionan 128k, creo - algo que es bastante fácil de superar con los tamaños de bloque que maneja el TP.
>
>Esto puede ser definitivamente, pero mi shell permite 2097152 caracteres, yo creería que estoy dentro de esos números al ser bloques de 1M

True story. No lo había chequeado, pero es cierto - el límite es mayor.

>> Además, ¿tenés garantías de que el bloque que estás leyendo no tiene " y ' y otros caracteres que la shell considera "especiales"?
>
> No entiendo como con head y tail me aseguro de salvarme de eso

Con `head` y `tail` pasa que _en ningún momento_ los datos son parte de tu línea de comandos. Digamos, si el contenido de tu archivo fuera `Hola"; halt -p; "Chau`, tu línea de comandos a ejecutar via `system` termina siendo `echo "Hola"; halt -p; "Chau" | ./transformador.py | sort -d - > /aca/el/archvio/temp`. En cambio, usando `head` y `tail`, te queda `head -n 1234 elarchivo.bin | tail -n 2345 | ./transformador.py.....` - no importa qué datos sean, nunca son parte del comando a ejecutar.

**Comment by lepeg123** [comment]
Nosotros teniamos problemas con la longitud de la cadena que mandabamos a la funcion system. Cuando probe bajandolo a un archivo el contenido del bloque y levantarlo con cat dentro del system anduvo sin problema

**Comment by ivigilante** [comment]
Ahora al parecer esta funcionando bien, lo que hice fue guardar el archivo temporal y al nombre hacerle un string_from_format y poniendo Nodo y numero de bloque, para tener una idea de que estaba entrando al system en cada caso.
Pero ahora, mi problema es que me imprime esto el system en la terminal:

`Traceback (most recent call last):`
 ` File "./transformador.py", line 15, in <module>`
    `map(getRegistro, data)`
  `File "./transformador.py", line 6, in getRegistro`
  `  if(len(linea.split(',')[0]) > 0 and len(linea.split(',')[1]) > 0):`
`IndexError: list index out of range`

Supongo que lo que esta entrando no es correcto...

**Comment by iago64** [comment]
@ivigilante bueno, ese es un error en el script de python (o mejor dicho un error en los datos)
Por esas casualidades te pregunto, con que dataset estan probando? 
Como recomendacion tienen que usar el nombres.csv que esta en el repo (o el de 200Mb que esta subido a drive), los datasets por lustros estan para hacer pruebas de grabar multiples archivos en el YamaFS y ver que estos se graben correctamente.

Abrazo!

**Comment by ivigilante** [comment]
Lamentablemente estoy probando con nombres.csv que pesa 30 y pico de megas

**Comment by lepeg123** [comment]
Te diria que es un problema de los datanode/filesystem mas que el worker. Si no estas verificando que guarde de a lineas cuando es un archivo de texto (para que cuando llegue a un 1MB no corte a la mitad de una linea) lo que pasa es que despues el worker lee el bloque del datanode y la ultima linea no tiene un \n y entonces recibe algo incorrecto el script.

**Comment by ccalvoromero** [comment]
A nosotros nos pasaba algo similar, y era porqué los bloques por error, en algunos casos lo estabamos cortando en el medio de alguna linea y por eso rompe el .py, fijate en los temporales de los bloques que vas creando si están todos completos, o si tienen un salto de linea al final (aunque éste no debiera ser problema). Tampoco se olviden del export LC_ALL=C

**Comment by lucasmcenturion** [comment]
Soy del grupo de @ivigilante. Eso de que sea error de datanode/filesystem no creo que sea porque por ejemplo si haces el md5 te da lo que tiene que dar y eso significa que se guardaron bien los datos.

**Comment by lepeg123** [comment]
@lucasmcenturion si lo guardas como binario, la linea que se corta a la mitad, la sigue en el bloque siguiente. Por lo cual cuando haces el md5, levanta la info de todos los bloques y los datos estan, pero no saca el hecho de que puede estar cortado a la mitad una linea

**Comment by lucasmcenturion** [comment]
Pero por qué guardaría como binario un archivo que ya sé que es de texto? Justamente cuando hago el cpfrom le paso un parámetro para indicar que estoy guardando un archivo de texto.

**Comment by mgarciaisaia** [comment]
Para calcular el md5, sin importar que el archivo esté cortado en líneas o no, ustedes deberían _primero_ reconstruir el archivo, y después hashearlo. Esa reconstrucción del archivo debería tener en cuenta si almacenaron los datos cortados de a líneas o no - y hacer el camino inverso, para conseguir una copia exacta del archivo original.

Ahora bien, si a la hora de levantar el bloque para transformar no le dan mucha bola a esto, ahí la van a embarrar.

Si cortan de a líneas, el primer bloque de un archivo probablemente pese menos de 1MB (digamos, 900k, porque tienen líneas muuuuuuuuy largas). Pero si ustedes, al leer ese bloque, no le dan bola al tamaño efectivo de ese bloque, van a pasarle al transformador 1MB de datos - incluyendo los últimos 100k del bloque, que van a ser nuestra vieja y querida basura. Y ahí el transformador se va a mamar, porque hay buenas chances de que el último dato no sea una línea completa.

La otra es que el transformador espere que los datos que le pasan sean todas líneas completas (ie, que termine en `\n`) y ustedes estén obviando el último salto, o que esté pasando al revés.

**Comment by tferraro** [comment]
@lucasmcenturion tranqui :slightly_smiling_face: lo que trata de decir @lepeg123 es que no descartes cosas que no estés del todo seguro, porque podés estar reconstruyendolo bien y creyendo que lo guardás como texto, pero en algún momento se les puede deschabetar la cosa y están guardando una línea a medias.
Pensá que ni les anda la transformación, así que te están aportando diferentes puntos de vista para capas encontrar el error :wink: 

Como dijo dami más arriba, el error que te está tirando es porque la línea no respeta lo que espera el script. _Como sabemos que la linea del archivo posta si lo respeta_, posiblemente o:
 - Estás cortando una línea en algún lado
 - Estás agregando líneas con basura (porque si mirás lo que escupe el script, está chequeando la long de la cadena). Esta es la que me parece más probable, fijate de estar usando el tamaño posta que estás ocupand en el bloque y no el bloque en si.

**Comment by ivigilante** [comment]
Al final el problema parecía ser que a los workers les llegaba otro nodo, entonces abrian otro data.bin con los bytesOcupados de otro data.bin.

Igual, ahora mismo logramos hacer la transf, pero hay UNA que rompe, estuve viendo y como uso archivos temporales lo abrí y no parece tener nada raro, pero si le borro el ultimo caracter (que es un newline, un enter, un \n) y corro la transf con ese archivo solo por consola, funciona.
Puede ser que nos estemos pasando de bytesOcupados por un par de bytes y halla basura que no veo cuando abro el archivo temporal de texto? hay forma de abrirlo y ver si tiene basura?

Otro tema es que los byteOcupados me dan 1.500.450 bytes
Y cuando me fijo cuanto pesan los archivos temporales que uso, pesan 150.045 bytes. como dividio por 10...

**Comment by ivigilante** [comment]
Al final creímos haber resuelto el problema de los nodos, pero todavía no estaba solucionado. Una vez solucionado se logro hacer transformación bien. Cierro el issue! Gracias!!
