### ISSUE TITLE
Replanificación vs Reducción Local

### ISSUE THREAD

**Issue by sebastianciancio** [sisoputnfrba/foro#988]
Duda de último momento!!!

Planteo el siguiente escenario.
- 2 Nodos corriendo, Nodo1 y Nodo2
- El Master manda a Transformar y Reducir un archivo de 30 bloques.
- Yama aplica algoritmo y distribuye 15 bloques al Nodo1 y 15 al Nodo2 para que sean transformados.
- El Nodo1 transforma sin problema los 15 bloques y le notifica a Master/Yama del exito. En función de esto, Yama le manda al Nodo1 (via Master) la orden de Reducción Local ya que todos sus bloques fueron transformados correctamente.
- El Nodo2 logra transformar 10 bloques y, por algún motivo, los 5 restantes falla y notifica a Master/Yama para que proceda con la replanificación de estos bloques. Yama recibe dichas notificaciones y le manda al Nodo1 (copia2) la replanificación de las transformaciones.
- El Nodo1 recibe los 5 bloques para transformar y le avisa a Yama (via Master) que el resultado fue satisfactorio.
- El Nodo2 recibe la notificación de Yama para que proceda a la Reducción Local de los 10 bloques que pudo transformar.
- Yama, en consecuencia, le avisa a Nodo1 que proceda a la Reducción Local de esos nuevos 5 bloques.

**Conclusion**
El Nodo1 recibió 2 pedidos de Reducción Local sobre bloques diferentes (20 bloques) y el Nodo2 recibió 1 pedido de Reducción Local sobre los 10 bloques que pudo transformar.

**Pregunta**
1) Es válido que el Nodo1 haya recibido 2 pedidos de Reducción Local?
2) Debería Yama esperar a recibir el 100% de las transformaciones de los bloques para iniciar las Reducciones Locales?

**Comment by tferraro** [comment]
Buenas!

Esto justo lo charlamos en https://github.com/sisoputnfrba/foro/issues/901#issuecomment-337619415

Lo más acertado es la pregunta 1, cuya respuesta es un Si, solo que la forma de integrar las 2 reducciones locales, dependerá de como lo quieran implementar. Como dije en el issue anterior, tenés 2 formas, o terminar teniendo 2 archivos de red a mandar a la red. global, o aprovechar la interfaz que tienen los reductores y junto a todos los tmp de transf, mechar la reducción ya hecha (la cual no debería cambiar en nada, porque respeta la interfaz).

**Comment by sebastianciancio** [comment]
Muchisimas gracias por la respuesta y la referencia al issue. Era exactamente lo planteado.
