### ISSUE TITLE
Diferencia en resultado de Reduccion local

### ISSUE THREAD

**Issue by ivigilante** [sisoputnfrba/foro#989]
Hola, les traigo otro issue porque resulta que estoy haciendo la reducción local con worker, haciendo sort -m de los archivos temporales que genera la transformación, y eso mandándolo al script reductor.
Pero para hacer una prueba corrí por terminal

`sort -m j1n1b* | /home/utnso/Scripts/reductor.py > archivoRL`

Que haría la reducción local del nodo 1, y me esta dando una diferencia de 198 bytes de más con respecto al resultado del worker.
Ejecute diff en terminal y vi que efectivamente hay lineas distintas.
Esta el md5 de la reducción local en algún lado como para verificar cual de los dos esta bien?

PD: Hago sort -m y escribo manualmente todos los archivos temporales de la transf y me da igual que en el worker. Es solo en el caso de hacer sort -m j1n1b*
Efectivamente verifique que lo que llega al system de worker este bien, llegan todos los temporales, nada raro.

**Comment by iago64** [comment]
Aloha!

Lo que es el sort deberias ejecutarlo sin el -m, no hace falta.
La pregunta el millon es, ejecutaste posta posta el `export LC_ALL=C` ? ese export es el que hace que sort funcione de forma correcta (o al menos concordante con las  pruebas) si tenes alguna duda al respecto de si esta bien seteada podes hacer un echo de la variable de entorno LC_ALL a ver si esta configurada.

Saludos.-

**Comment by ivigilante** [comment]
No estaba hecho el export, pero al hacerlo la diferencia sigue estando, ahora el archivo que genera el worker tiene 19 bytes más que el que me da la terminal.
El -m no es para hacer el merge entre archivos que ya estaría sorteados antes? Que es justamente lo que quiero hacer en la Reducción Local, probe correr por terminal sin el -m y fue peor, tenia como 100.000 bytes menos.
Puede ser que le orden en que pongo los archivos este afectando el sort?

**Comment by iago64** [comment]
Aaaah! ahora si.

Ese problema podes resolverlo haciendo un cat de los archivos temporales para concatenarlos y la salida de ese cat pasarselo directo a sort :)

**Comment by ivigilante** [comment]
Reemplazo entonces el sort -m  por cat de los archivos y luego pipe a sort y te comento!

**Comment by ivigilante** [comment]
Bueno al reemplazarlo no me esta funcionando el comando
Quedo: 
cat /tmp/archivo1 /tmp/archivo2 | sort | /home/utnso/Script/reductor.py > /tmp/final
Queda vacío el archivo final. Que me esta faltando???

**Comment by iago64** [comment]
En esa carpeta /tmp tenes solo los archivos temporales de la reduccion de ese job?
Lo que podria hacer seria por ej tener un /tmp/JobX y despues haces:

cat * | sort | <path al archivo de reduccion> > /tmp/jobXfinal.txt

**Comment by ivigilante** [comment]
Cuando hago el sort, no hay problemas, el problema esta cuando meto el reductor.py
si hago
`cat /tmp/archivo1 /tmp/archivo2 | sort ` 
tengo output, pero ya si meto
`cat /tmp/archivo1 /tmp/archivo2 | sort | /home/utnso/Script/reductor.py ` 
dejo de tener

Haciendo la prueba que dijiste, guarde todo en una carpeta y corrí 
`cat * | sort > /tmp/jobXfinal.txt`
y después
`cat jobXfinal.txt | /home/utnso/Scripts/reductor.py > prueba` 
y prueba esta vacío.

**Comment by iago64** [comment]
Podes subir una parte del archivo que se forma a la salida del jobXfinal.txt? porque es muy raro que te este generando un archivo vacio.

**Comment by ivigilante** [comment]
Mala mía! 😜 
En algún momento se me borró el script, no se ni como ni cuando. 
Pero bueno, vuelvo a hacer las pruebas para ver que los tamaños esten bien o den igual
Probablemente de tanto comandos que meti y los nervios de que no salia, pifie en uno y mande > reductor.py y rompí todo.

**Comment by iago64** [comment]
Tranqui, son cosas que pasan, por favor avisa si se resuelve el problema :)

**Comment by ivigilante** [comment]
Se resolvió! Cierro el issue, gracias por la paciencia!
Usando cat de los archivos y sort, me dan los mismos tamaños
