### ISSUE TITLE
sh errores al transformar

### ISSUE THREAD

**Issue by MarcoPorracin** [sisoputnfrba/foro#990]
Hola,

Durante la transformación nos tira 3 errores:

`
sh: 1: ./#!: not found
sh: 2: import: not found
sh: 4: Syntax error: "(" unexpected
`

Sin embargo comparó los md5 entre el archivo original y el archivo de transformación que escribe el worker (recibido por socket) y me dan igual. Por que puede estar pasando?

**Comment by iago64** [comment]
Marco, que tal?

el error es bastante extraño ya que no estamos usando bash en las transformaciones, los 4 scripts que hay estan [hechos en python ](https://github.com/iago64/SO-Nombres-Dataset).

Podrias pasar algo mas de info al respecto de como estas ejecutando la transformación?

Saludos.-

**Comment by mgarciaisaia** [comment]
¿Puede que tengan un `./#!` como she-bang de alguno de los scripts en lugar de sólo el `#!`?

**Comment by MarcoPorracin** [comment]
Para ejecutar la transformacion corremos utilizamos system() a quien le pasamos un char* generado con un:
` string_from_format("cat %s | %s | sort -d > %s", rutaAlBloque, rutaAlScript, rutaATemporal)`

Abri con además de los md5 abri con vi :get list los scripts, esta la comparación entre el original y el que escribe.

![whatsapp image 2017-12-15 at 16 18 32](https://user-images.githubusercontent.com/22181136/34058053-6ef344bc-e1b8-11e7-9a00-c3cebb3cdbed.jpeg)
