### ISSUE TITLE
Sin acceso al repositorio del TP0

### ISSUE THREAD

**Issue by santiluccadeguevara** [sisoputnfrba/foro#991]
Hola, qué tal! Espero que anden bien.

Perdón por tan pronta pregunta, pero con mi equipo decidimos hacer el TP0 antes del Workshop para aprovechar el máximo tiempo posible, y no pudimos clonar el repositorio del TP0 en nuestras VM a través del link que nos da el enunciado: GitHub nos indica que no encuentra el repositorio.

Queríamos saber por qué no tenemos acceso al repositorio del TP0, o bien si hay algo que no estemos teniendo en cuenta a la hora de clonarlo en nuestras VM.

Espero haber sido claro. Desde ya, muchas gracias.

Saludos.

**Comment by tferraro** [comment]
Muy buenas!

El enunciado que está puesto está a modo ilustrativo para que vayan viendo los temas que se van a tratar. Por lo que el código todavía no está publicado :), lo vamos a estar publicando cerca de la primer charla, así ya lo tienen visto.

Pero porqué en ese momento _y no antes_? Porque la idea es que podamos ir resolviéndolo en conjunto, que estén acompañados por los ayudantes y no solo el grupo :muscle:.

De esa forma evitar un poco de ruido por la inexperiencia en el desarollo y dejar ciertos temas bien firmes, que programando solos suelen quedar en el tintero para más adelante.

Solo eso, te pedimos paciencia, joven padawan, todo a su debido tiempo :stuck_out_tongue: 

_Peeero_ si quieren ir poniéndose a tiro pueden revisar los docs de:
https://www.utnso.com/bienvenido-al-tp-de-sistemas-operativos-2/
y de
https://www.utnso.com/recursos/guias/

Que con las guias y los ejercicios de C van a tener suficiente para matar el tiempo :smile: 

Saludos!
Tom

**Comment by santiluccadeguevara** [comment]
Entiendo. Paciencia entonces XD

Mil gracias por la pronta respuesta y la info extra :+1: 

Saludos!
