### ISSUE TITLE
Problemas para instalar ubuntu

### ISSUE THREAD

**Issue by Nickingo** [sisoputnfrba/foro#992]
Hola chicos!

Estaba descargando las partes del ubuntu para poder tener todo instalado y preparado para el tp, pero tuve el inconveniente de que al momento de descomprimirlas, me figuran los siguientes errores:

-Si utilizo el winrar, el error que se dispara es que la parte 2, 3, 4 y 5 están dañadas y no se puede descomprimir el archivo.
-Si utilizo el 7z, me aparece:
  - Parte 1 a 5: No se puede abrir el archivo como un archivo 7z.
  - Parte 2 a 5: El archivo se abrió como archivo Ar.

Los archivos los descargué en formato "rar".
Quisiera saber como puedo solucionar este problema porque todavía no logre ningún resultado.

Espero que se haya entendido.
Muchas gracias.

Saludos.

**Comment by varas-c** [comment]
Hola! Cómo estas?

Lo mas probable es que los archivos se hayan descargado "mal" por alguna
razón por lo que tenes archivos corruptos.

Lo que deberías hacer primero es verificar que los archivos que hayas
descargados sean realmente lo que estabas esperando descargar y que no se
hayan "roto" en el camino.

Para ésto, debés calcular el md5 de las 5 partes que bajaste. Por si no lo
sabés (no pasa nada) el md5 es una funcion de hash. Imaginate una función
matemática (una funcion lineal y una recta con pendiente positiva, tipo asi
" / " ). Vos le das una X y te devuelve una Y. Si vos le das otra X te va a
dar otra Y distinta.

Así que si a la funcion md5 vos le pasas un archivo, te va a devolver un
"hash"  (le das una X y te devuelve una Y).

https://www.utnso.com/recursos/maquinas-virtuales/ Fijate que en el blog
estan los "hashes" md5 de los archivos. Calculá los md5 de los archivos que
vos tenes y si se dan distinto, quieren decir que NO son el mismo archivo
(es decir son X distintas por lo que te van a dar Y distintas) por lo que
vas a tener que bajar alguna parte de nuevo. Si todos los hashes te dan
igual, quiere decir que descargaste bien los archivos y el error debe ir
por otra parte.

Si no se entendío o tenés alguna otra duda, avisanos!






2018-03-23 21:30 GMT-03:00 Nickingo <notifications@github.com>:

**Comment by Nickingo** [comment]
Si, entendí bien la explicación, pero para calcularlo hay que usar algún programa? O existe algún comando en el cmd de windows que lo permite calcular?

**Comment by tferraro** [comment]
Buenas!

En windows nativamente no se puede calcular el MD5. Podes, o hacerlo con algun soft de descargas (por lo general practicamente todos soportan md5) o bajandote [el utility de microsoft](https://www.microsoft.com/en-us/download/details.aspx?id=11533) (en este basta con ejecutar `fciv.exe --md5 nombre_del_archivo` en la consola del cmd)

> Los archivos los descargué en formato "rar".

No te seguí esto, la extensión que tienen los archivitos es .7z.00X no .rar, vendrá por ese lado?

Cualquier cosa chiflanos!

PD: Por las dudas, me baje todas las partes y te confirmo que están en perfecto estado, así que es algo de la descarga.

**Comment by Nickingo** [comment]
Ahi encontré como calcular el md5 de cada archivo y me dan igual que los que aparecen en el blog de la pagina. 

Se ve que lo estoy descargando mal porque cuando voy a guardar el archivo a descargar, le coloco la extensión al final del nombre del archivo ".rar".
Por ej: si se llama utnso-lubuntu-5.0.1.7z.001, "lo guardo como utnso-lubuntu-Parte1.7z.rar"
        y asi con las demas partes.

Puede ser que por esa modificación se genere conflicto con el archivo?

**Comment by varas-c** [comment]
Si los md5 te dan igual que los que están en el blog, cambiale la extensión
a los archivos para que queden como debería y probalo de nuevo!

**Comment by Nickingo** [comment]
Ahí probé de vuelta de descargar los archivos y por suerte pude descomprimirlos sin ningún problema.

Muchas gracias por el tiempo y la ayuda.
Saludos.
