### ISSUE TITLE
Problema Inscripción legajo 1421931

### ISSUE THREAD

**Issue by PabloAntivero** [sisoputnfrba/foro#993]
Buen Día, 
tengo problemas para inscribirme mi numero de legajo es 1421931 es la primera vez que curso la materia, me sale un mensaje 1421931-6 ya se encuentra inscripto. Que debo hacer?? 
Desde ya muchas Gracias

👋 ¡Hola!

Ojalá el foro te sea de ayuda. Para agilizar las cosas para tod@s, te pedimos un par de
cosas antes de que hagas una nueva pregunta:

- [ ] 🔍 ¡Buscá! Acá arriba hay un "Search" que te permite buscar consultas que hayan
hecho antes tus compañer@s. Quizá ya encontrás la respuesta servida.
- [ ] 📝 ¡Se detallad@! Si no encontraste tu respuesta, se tan clar@ y detallad@ en tu
pregunta como puedas. Tratá de contar qué hacés, qué observás, y qué entendés a partir
de eso - ¡pero sin mezclarlas!
- [ ] 📹 ¡Mirá cómo reportar desde Eclipse! Si tu problema es con código en Eclipse,
mirá el video [Cómo reportar errores desde Eclipse](https://youtu.be/18cN8Jk4WjQ) para
tener todos los detalles que necesitamos.

🙇 Gracias por leernos, y ¡éxitos!

**Comment by nahuelm** [comment]
Hola Pablo, estoy viendo el sistema. ¿Podrías volver a intentar ingresar al mismo desde otra sesión del navagador? Por favor, confirmame si persiste el problema.

**Comment by PabloAntivero** [comment]
Buen día Nahuel, ingrese sin problemas, ya me encuentro adentro.

Desde ya muchas Gracias por la pronta respuesta.

**Comment by PabloAntivero** [comment]
finalizado
