### ISSUE TITLE
Problema inscripción legajo 11746783

### ISSUE THREAD

**Issue by jloffredo** [sisoputnfrba/foro#994]
Buenas tardes, estoy intentando registrarme y me da error que el legajo y el usuario ya existen. 
Gracias

**Comment by nahuelm** [comment]
Hola Javier. ¿Puede ser que el legajo sea 117.467-8? Si es así, por favor, intenta volver a ingresar desde otra sesión del navegador. Aguardo confirmación del resultado.

**Comment by jloffredo** [comment]
Si. ahora si. gracias!

**Comment by LeaTex** [comment]
"El nombre debe contener solamente caracteres del alfabeto"

Al parecer no se permiten caracteres con tilde.  ¯\_(ツ)_/¯

**Comment by LeaTex** [comment]
Legajo: 115350-0  ===>  Error: El legajo debe ser numerico

Legajo: 1153500  ===>  Error: El valor **_1153500-6_** ya está tomado en la base de datos

**Comment by nahuelm** [comment]
Hola Leandro, disculpa la demora. Por favor volve a intentar ingresar con otra sesión del navegador.  Aguardo tu respuesta y la resolucion del issue.

Saludos. Nahuel

**Comment by LeaTex** [comment]
Perfecto @nahuelm ya pude entrar.
Saludos
