### ISSUE TITLE
Codigo del ejemplo presentado en la primera jornada

### ISSUE THREAD

**Issue by NiCOi** [sisoputnfrba/foro#995]
¿Podrán subir el código, tanto del .h como del .c del ejemplo que codearon durante la primera jornada en el Aula Magna? Sí, ese que codearon como 5 veces hoy.
¡Muchas gracias!

**Comment by iago64** [comment]
@NiCOi Como va? Perdon por la demora, ya estan subidos los ejemplos en el siguiente [repo](https://github.com/sisoputnfrba/1c-2018-ejercicio-1ra-charla)

Y no lo codeamos 5 veces, solo fueron 4 :)

Cualquier duda o consulta no dudes en levantar la mano .
Saludos!
