### ISSUE TITLE
Enlace Valgrind caido en el Blog

### ISSUE THREAD

**Issue by davidosvaldoperez** [sisoputnfrba/foro#997]
Buenas!

En el post del blog de [resumen de la priemra charla](https://www.utnso.com/resumen-de-la-primera-charla) hay un enlace de introduccion a Vlagrind que apunta a `http://faq.utn.so/valgrind`.
Deberia ser `http://faq.utnso.com/valgrind`.

Se podrá corregir ese enlace?
Gracias.
___
Aclaro que no se si corresponde el issue para este problema (busque issues sobre "blog" y no encontre).
Antes intente comentar en el blog pero no se puede por lo visto.

**Comment by nahuelm** [comment]
Hola @davidosvaldoperez. Muchas gracias por el aviso. Ya se encuentra corregido.
