### ISSUE TITLE
Subscribir grupo con cambio de curso en tramite

### ISSUE THREAD

**Issue by davidosvaldoperez** [sisoputnfrba/foro#999]
Buenas!

Tengo una consulta administrativa, pero que tiene que ver con el tp.

Tenemos un miembro en proceso de cambio de curso.
Hay opciones:
- Crear el grupo **YA** e inscribir al miembro con el curso que tiene actualmente.
- Esperar a que bedelia confirme el cambio de curso, y recien ahi registrar el grupo.

¿Que es lo recomendable?

Gracias
Saludos

**Comment by tferraro** [comment]
Buenas!

Denle mecha e inscribanse con el curso que tengan ahora. Si se cambia finalmente, mandenos un mail y lo cambiamos on the fly :wink: 

Saludos!
Tom

**Comment by davidosvaldoperez** [comment]
Perfecto. Muchas gracias!

Cierro
